v8::internal::compiler::RedundancyElimination::EffectPathChecks Class Reference
Public Member Functions
bool Equals (EffectPathChecks const *that) const
void Merge (EffectPathChecks const *that)
EffectPathChecks const * AddCheck (Zone *zone, Node *node) const
Node * LookupCheck (Node *node, JSGraph *jsgraph) const
Node * LookupBoundsCheckFor (Node *node) const
Static Public Member Functions
static EffectPathChecks * Copy (Zone *zone, EffectPathChecks const *checks)
static EffectPathChecks const * Empty (Zone *zone)
Private Member Functions
EffectPathChecks (Check *head, size_t size)
Private Attributes
friend Zone
Check * head_
size_t size_
Detailed Description
Definition at line 35 of file redundancy-elimination.h.
Constructor & Destructor Documentation
EffectPathChecks()
v8::internal::compiler::RedundancyElimination::EffectPathChecks::EffectPathChecks (Check * head, size_t size) [inline], [private]
Definition at line 49 of file redundancy-elimination.h.
: head_(head), size_(size) {}
Member Function Documentation
AddCheck()
RedundancyElimination::EffectPathChecks const * v8::internal::compiler::RedundancyElimination::EffectPathChecks::AddCheck (Zone * zone, Node * node) const
Definition at line 139 of file redundancy-elimination.cc.
                                                                    {
  Check* head = zone->New<Check>(node, head_);
  return zone->New<EffectPathChecks>(head, size_ + 1);
}
References v8::internal::Zone::New(), and v8::internal::compiler::RedundancyElimination::zone().
Referenced by v8::internal::compiler::RedundancyElimination::ReduceCheckNode().
Copy()
RedundancyElimination::EffectPathChecks * v8::internal::compiler::RedundancyElimination::EffectPathChecks::Copy (Zone * zone, EffectPathChecks const * checks) [static]
Definition at line 85 of file redundancy-elimination.cc.
                                                                              {
  return zone->New<EffectPathChecks>(*checks);
}
References v8::internal::Zone::New(), and v8::internal::compiler::RedundancyElimination::zone().
Referenced by v8::internal::compiler::RedundancyElimination::ReduceEffectPhi().
Empty()
RedundancyElimination::EffectPathChecks const * v8::internal::compiler::RedundancyElimination::EffectPathChecks::Empty (Zone * zone) [static]
Definition at line 92 of file redundancy-elimination.cc.
                                                       {
  return zone->New<EffectPathChecks>(nullptr, 0);
}
References v8::internal::Zone::New(), and v8::internal::compiler::RedundancyElimination::zone().
Referenced by v8::internal::compiler::RedundancyElimination::ReduceStart().
Equals()
bool v8::internal::compiler::RedundancyElimination::EffectPathChecks::Equals (EffectPathChecks const * that) const
Definition at line 96 of file redundancy-elimination.cc.
                                        {
  if (this->size_ != that->size_) return false;
  Check* this_head = this->head_;
  Check* that_head = that->head_;
  while (this_head != that_head) {
    if (this_head->node != that_head->node) return false;
    this_head = this_head->next;
    that_head = that_head->next;
  }
  return true;
}
References head_, v8::internal::compiler::RedundancyElimination::Check::next, v8::internal::compiler::RedundancyElimination::Check::node, and size_.
Referenced by v8::internal::compiler::RedundancyElimination::UpdateChecks().
LookupBoundsCheckFor()
Node * v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupBoundsCheckFor (Node * node) const
Definition at line 336 of file redundancy-elimination.cc.
                      {
  for (Check const* check = head_; check != nullptr; check = check->next) {
    if (check->node->opcode() == IrOpcode::kCheckBounds &&
        check->node->InputAt(0) == node && TypeSubsumes(node, check->node) &&
        !(CheckBoundsParametersOf(check->node->op()).flags() &
          CheckBoundsFlag::kConvertStringAndMinusZero)) {
      return check->node;
    }
  }
  return nullptr;
}
References v8::internal::compiler::CheckBoundsParametersOf(), v8::internal::compiler::CheckBoundsParameters::flags(), v8::internal::compiler::kConvertStringAndMinusZero, v8::internal::compiler::RedundancyElimination::Check::next, and v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::TypeSubsumes().
Referenced by v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), and v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation().
LookupCheck()
Node * v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck (Node * node, JSGraph * jsgraph) const
Definition at line 318 of file redundancy-elimination.cc.
                                        {
  for (Check const* check = head_; check != nullptr; check = check->next) {
    Subsumption subsumption =
        CheckSubsumes(check->node, node, jsgraph->machine());
    if (!subsumption.IsNone() && TypeSubsumes(node, check->node)) {
      DCHECK(!check->node->IsDead());
      Node* result = check->node;
      if (subsumption.IsWithConversion()) {
        result = jsgraph->graph()->NewNode(subsumption.conversion_operator(),
                                           result);
      }
      return result;
    }
  }
  return nullptr;
}
References v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::DCHECK(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::RedundancyElimination::Check::next, v8::base::internal::result, and v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::TypeSubsumes().
Referenced by v8::internal::compiler::RedundancyElimination::ReduceCheckNode().
Merge()
void v8::internal::compiler::RedundancyElimination::EffectPathChecks::Merge (EffectPathChecks const * that)
Definition at line 109 of file redundancy-elimination.cc.
                                  {
  // Change the current check list to a longest common tail of this check
  // list and the other list.
  // First, we throw away the prefix of the longer list, so that
  // we have lists of the same length.
  Check* that_head = that->head_;
  size_t that_size = that->size_;
  while (that_size > size_) {
    that_head = that_head->next;
    that_size--;
  }
  while (size_ > that_size) {
    head_ = head_->next;
    size_--;
  }
  // Then we go through both lists in lock-step until we find
  // the common tail.
  while (head_ != that_head) {
    DCHECK_LT(0u, size_);
    DCHECK_NOT_NULL(head_);
    size_--;
    head_ = head_->next;
    that_head = that_head->next;
  }
}
References DCHECK_LT, DCHECK_NOT_NULL, head_, v8::internal::compiler::RedundancyElimination::Check::next, and size_.
Referenced by v8::internal::compiler::RedundancyElimination::ReduceEffectPhi().
Member Data Documentation
head_
Check* v8::internal::compiler::RedundancyElimination::EffectPathChecks::head_ [private]
Definition at line 53 of file redundancy-elimination.h.
Referenced by Equals(), and Merge().
size_
size_t v8::internal::compiler::RedundancyElimination::EffectPathChecks::size_ [private]
Definition at line 54 of file redundancy-elimination.h.
Referenced by Equals(), and Merge().
Zone
friend v8::internal::compiler::RedundancyElimination::EffectPathChecks::Zone [private]
Definition at line 47 of file redundancy-elimination.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/redundancy-elimination.h
/mnt/V8SourceCode/src/compiler/redundancy-elimination.cc