v8::internal::RegExpMatchInfo Class Reference
#include <regexp-match-info.h>
Classes
class BodyDescriptor
Public Types
using Shape = RegExpMatchInfoShape
Public Member Functions
int number_of_capture_registers () const
void set_number_of_capture_registers (int value)
Tagged< String > last_subject () const
void set_last_subject (Tagged< String > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > last_input () const
void set_last_input (Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
int capture (int index) const
void set_capture (int index, int value)
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< RegExpMatchInfo > New (Isolate *isolate, int capture_count, AllocationType allocation=AllocationType::kYoung)
static DirectHandle< RegExpMatchInfo > ReserveCaptures (Isolate *isolate, DirectHandle< RegExpMatchInfo > match_info, int capture_count)
static constexpr int capture_start_index (int capture_index)
static constexpr int capture_end_index (int capture_index)
Static Public Attributes
static constexpr int kMinCapacity = 2
Private Types
using Super = TaggedArrayBase< RegExpMatchInfo, RegExpMatchInfoShape >
Additional Inherited Members
Detailed Description
Definition at line 44 of file regexp-match-info.h.
Member Typedef Documentation
Shape
using v8::internal::RegExpMatchInfo::Shape = RegExpMatchInfoShape
Definition at line 49 of file regexp-match-info.h.
Super
using v8::internal::RegExpMatchInfo::Super = TaggedArrayBase<RegExpMatchInfo, RegExpMatchInfoShape> [private]
Definition at line 46 of file regexp-match-info.h.
Member Function Documentation
capture()
int v8::internal::RegExpMatchInfo::capture (int index) const [inline]
Definition at line 42 of file regexp-match-info-inl.h.
{ return get(index).value(); }
References v8::internal::TaggedArrayBase< RegExpMatchInfo, RegExpMatchInfoShape >::get(), and v8::internal::index.
capture_end_index()
static constexpr int v8::internal::RegExpMatchInfo::capture_end_index (int capture_index) [inline], [static], [constexpr]
Definition at line 81 of file regexp-match-info.h.
                                                            {
    return capture_index * 2 + 1;
  }
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::RegExpUtils::GenericCaptureGetter(), and v8::internal::RegExpUtils::IsMatchedCapture().
capture_start_index()
static constexpr int v8::internal::RegExpMatchInfo::capture_start_index (int capture_index) [inline], [static], [constexpr]
Definition at line 78 of file regexp-match-info.h.
                                                              {
    return capture_index * 2;
  }
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::RegExpUtils::GenericCaptureGetter(), and v8::internal::RegExpUtils::IsMatchedCapture().
last_input()
Tagged< Object > v8::internal::RegExpMatchInfo::last_input () const [inline]
Definition at line 34 of file regexp-match-info-inl.h.
                                                 {
  return last_input_.load();
}
last_subject()
Tagged< String > v8::internal::RegExpMatchInfo::last_subject () const [inline]
Definition at line 26 of file regexp-match-info-inl.h.
                                                   {
  return last_subject_.load();
}
New()
DirectHandle< RegExpMatchInfo > v8::internal::RegExpMatchInfo::New (Isolate * isolate, int capture_count, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 12 of file regexp-match-info.cc.
                                                                              {
  int capacity = JSRegExp::RegistersForCaptureCount(capture_count);
  DCHECK_GE(capacity, kMinCapacity);
  std::optional<DisallowGarbageCollection> no_gc;
  DirectHandle<RegExpMatchInfo> result =
      Allocate(isolate, capacity, &no_gc, allocation);
  ReadOnlyRoots roots{isolate};
  MemsetTagged(result->RawFieldOfFirstElement(), Smi::zero(), capacity);
  result->set_number_of_capture_registers(capacity);
  result->set_last_subject(*isolate->factory()->empty_string(),
                           SKIP_WRITE_BARRIER);
  result->set_last_input(roots.undefined_value(), SKIP_WRITE_BARRIER);
  return result;
}
References v8::internal::TaggedArrayBase< RegExpMatchInfo, RegExpMatchInfoShape >::Allocate(), DCHECK_GE, v8::internal::Isolate::factory(), kMinCapacity, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Smi::zero().
Referenced by v8::internal::Genesis::InitializeGlobal(), ReserveCaptures(), and v8::internal::Debug::StartSideEffectCheckMode().
number_of_capture_registers()
int v8::internal::RegExpMatchInfo::number_of_capture_registers () const [inline]
Definition at line 19 of file regexp-match-info-inl.h.
                                                       {
  return number_of_capture_registers_.load().value();
}
ReserveCaptures()
DirectHandle< RegExpMatchInfo > v8::internal::RegExpMatchInfo::ReserveCaptures (Isolate * isolate, DirectHandle< RegExpMatchInfo > match_info, int capture_count) [static]
Definition at line 31 of file regexp-match-info.cc.
                       {
  int required_capacity = JSRegExp::RegistersForCaptureCount(capture_count);
  if (required_capacity > match_info->capacity()) {
    DirectHandle<RegExpMatchInfo> new_info = New(isolate, capture_count);
    RegExpMatchInfo::CopyElements(isolate, *new_info, 0, *match_info, 0,
                                  match_info->capacity());
    match_info = new_info;
  }
  match_info->set_number_of_capture_registers(required_capacity);
  return match_info;
}
References v8::internal::TaggedArrayBase< RegExpMatchInfo, RegExpMatchInfoShape >::CopyElements(), New(), and v8::internal::JSRegExp::RegistersForCaptureCount().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::RegExp::SetLastMatchInfo().
set_capture()
void v8::internal::RegExpMatchInfo::set_capture (int index, int value) [inline]
Definition at line 44 of file regexp-match-info-inl.h.
                                                      {
  set(index, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::TaggedArrayBase< RegExpMatchInfo, RegExpMatchInfoShape >::set(), and v8::internal::value.
set_last_input()
void v8::internal::RegExpMatchInfo::set_last_input (Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 37 of file regexp-match-info-inl.h.
                                                            {
  last_input_.store(this, value, mode);
}
References mode(), and v8::internal::value.
set_last_subject()
void v8::internal::RegExpMatchInfo::set_last_subject (Tagged< String > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 29 of file regexp-match-info-inl.h.
                                                              {
  last_subject_.store(this, value, mode);
}
References mode(), and v8::internal::value.
set_number_of_capture_registers()
void v8::internal::RegExpMatchInfo::set_number_of_capture_registers (int value) [inline]
Definition at line 22 of file regexp-match-info-inl.h.
                                                               {
  number_of_capture_registers_.store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), and v8::internal::value.
Member Data Documentation
kMinCapacity
constexpr int v8::internal::RegExpMatchInfo::kMinCapacity = 2 [static], [constexpr]
Definition at line 85 of file regexp-match-info.h.
Referenced by v8::internal::Genesis::InitializeGlobal(), New(), and v8::internal::TF_BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/regexp-match-info.h
/mnt/V8SourceCode/src/objects/regexp-match-info-inl.h
/mnt/V8SourceCode/src/objects/regexp-match-info.cc