v8::internal::wasm::StringBuilder Class Reference
#include <string-builder.h>
Public Member Functions
StringBuilder ()
StringBuilder (const StringBuilder &)=delete
StringBuilder & operator= (const StringBuilder &)=delete
~StringBuilder ()
char * allocate (size_t n)
void write (const uint8_t *data, size_t n)
void write (const char *data, size_t n)
const char * start () const
const char * cursor () const
size_t length () const
void rewind_to_start ()
void backspace ()
Protected Types
enum OnGrowth : bool { kKeepOldChunks
, kReplacePreviousChunk
 }
Protected Member Functions
StringBuilder (OnGrowth on_growth)
void start_here ()
size_t approximate_size_mb ()
Private Member Functions
void Grow (size_t requested)
Private Attributes
char stack_buffer_ [kStackSize]
std::vector< char * > chunks_
char * start_ = stack_buffer_
char * cursor_ = stack_buffer_
size_t remaining_bytes_ = kStackSize
const OnGrowth on_growth_
Static Private Attributes
static constexpr size_t kStackSize = 256
static constexpr size_t kChunkSize = 1024 * 1024
Detailed Description
Definition at line 26 of file string-builder.h.
Member Enumeration Documentation
OnGrowth
enum v8::internal::wasm::StringBuilder::OnGrowth : bool [protected]
Enumerator
kKeepOldChunks
kReplacePreviousChunk
Definition at line 75 of file string-builder.h.
: bool { kKeepOldChunks, kReplacePreviousChunk };
Constructor & Destructor Documentation
StringBuilder() [1/3]
v8::internal::wasm::StringBuilder::StringBuilder () [inline]
Definition at line 28 of file string-builder.h.
: on_growth_(kReplacePreviousChunk) {}
StringBuilder() [2/3]
v8::internal::wasm::StringBuilder::StringBuilder (const StringBuilder &) [explicit], [delete]
 StringBuilder()
v8::internal::wasm::StringBuilder::~StringBuilder () [inline]
Definition at line 31 of file string-builder.h.
                   {
    for (char* chunk : chunks_) delete[] chunk;
    if (on_growth_ == kReplacePreviousChunk && start_ != stack_buffer_) {
      delete[] start_;
    }
  }
References chunks_, kReplacePreviousChunk, on_growth_, stack_buffer_, and start_.
StringBuilder() [3/3]
v8::internal::wasm::StringBuilder::StringBuilder (OnGrowth on_growth) [inline], [explicit], [protected]
Definition at line 78 of file string-builder.h.
: on_growth_(on_growth) {}
Member Function Documentation
allocate()
char* v8::internal::wasm::StringBuilder::allocate (size_t n) [inline]
Definition at line 41 of file string-builder.h.
                           {
    if (remaining_bytes_ < n) Grow(n);
    char* result = cursor_;
    cursor_ += n;
    remaining_bytes_ -= n;
    return result;
  }
References cursor_, Grow(), remaining_bytes_, and v8::base::internal::result.
Referenced by v8::internal::wasm::MultiLineStringBuilder::NextLine(), v8::internal::wasm::operator<<(), v8::internal::wasm::MultiLineStringBuilder::PatchLabel(), v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber(), and write().
approximate_size_mb()
size_t v8::internal::wasm::StringBuilder::approximate_size_mb () [inline], [protected]
Definition at line 81 of file string-builder.h.
                               {
    static_assert(kChunkSize == size_t{MB});
    return chunks_.size();
  }
References chunks_, kChunkSize, and v8::internal::MB.
Referenced by v8::internal::wasm::MultiLineStringBuilder::ApproximateSizeMB().
backspace()
void v8::internal::wasm::StringBuilder::backspace () [inline]
Definition at line 68 of file string-builder.h.
                   {
    DCHECK_GT(cursor_, start_);
    cursor_--;
    remaining_bytes_++;
  }
References cursor_, DCHECK_GT, remaining_bytes_, and start_.
cursor()
const char* v8::internal::wasm::StringBuilder::cursor () const [inline]
Definition at line 59 of file string-builder.h.
{ return cursor_; }
References cursor_.
Referenced by v8::internal::wasm::MultiLineStringBuilder::PatchLabel().
Grow()
void v8::internal::wasm::StringBuilder::Grow (size_t requested) [inline], [private]
Definition at line 87 of file string-builder.h.
                              {
    size_t used = length();
    size_t required = used + requested;
    size_t chunk_size;
    if (on_growth_ == kKeepOldChunks) {
      // Usually grow by kChunkSize, unless super-long lines need even more.
      chunk_size = required < kChunkSize ? kChunkSize : required * 2;
    } else {
      // When we only have one chunk, always (at least) double its size
      // when it grows, to minimize both wasted memory and growth effort.
      chunk_size = required * 2;
    }
    char* new_chunk = new char[chunk_size];
    memcpy(new_chunk, start_, used);
    if (on_growth_ == kKeepOldChunks) {
      chunks_.push_back(new_chunk);
    } else if (start_ != stack_buffer_) {
      delete[] start_;
    }
    start_ = new_chunk;
    cursor_ = new_chunk + used;
    remaining_bytes_ = chunk_size - used;
  }
References chunks_, cursor_, kChunkSize, kKeepOldChunks, length(), on_growth_, remaining_bytes_, stack_buffer_, and start_.
Referenced by allocate().
length()
size_t v8::internal::wasm::StringBuilder::length () const [inline]
Definition at line 60 of file string-builder.h.
{ return static_cast<size_t>(cursor_ - start_); }
References cursor_, and start_.
Referenced by v8::internal::wasm::NamesProvider::ComputeExportName(), v8::internal::wasm::NamesProvider::ComputeImportName(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), Grow(), v8::internal::wasm::MultiLineStringBuilder::NextLine(), v8::internal::wasm::MultiLineStringBuilder::PatchLabel(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::ModuleDisassembler::PrintModule(), rewind_to_start(), v8::internal::wasm::MultiLineStringBuilder::ToDisassemblyCollector(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString(), and v8::internal::wasm::MultiLineStringBuilder::WriteTo().
operator=()
StringBuilder& v8::internal::wasm::StringBuilder::operator= (const StringBuilder &) [delete]
rewind_to_start()
void v8::internal::wasm::StringBuilder::rewind_to_start () [inline]
Definition at line 61 of file string-builder.h.
                         {
    remaining_bytes_ += length();
    cursor_ = start_;
  }
References cursor_, length(), remaining_bytes_, and start_.
Referenced by v8::internal::wasm::MultiLineStringBuilder::PatchLabel().
start()
const char* v8::internal::wasm::StringBuilder::start () const [inline]
Definition at line 58 of file string-builder.h.
{ return start_; }
References start_.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::wasm::NamesProvider::ComputeExportName(), v8::internal::wasm::NamesProvider::ComputeImportName(), v8::internal::wasm::MultiLineStringBuilder::NextLine(), v8::internal::wasm::MultiLineStringBuilder::PatchLabel(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString().
start_here()
void v8::internal::wasm::StringBuilder::start_here () [inline], [protected]
Definition at line 79 of file string-builder.h.
{ start_ = cursor_; }
References cursor_, and start_.
Referenced by v8::internal::wasm::MultiLineStringBuilder::NextLine(), and v8::internal::wasm::MultiLineStringBuilder::PatchLabel().
write() [1/2]
void v8::internal::wasm::StringBuilder::write (const char * data, size_t n) [inline]
Definition at line 53 of file string-builder.h.
                                         {
    char* ptr = allocate(n);
    memcpy(ptr, data, n);
  }
References allocate().
write() [2/2]
void v8::internal::wasm::StringBuilder::write (const uint8_t * data, size_t n) [inline]
Definition at line 49 of file string-builder.h.
                                            {
    char* ptr = allocate(n);
    memcpy(ptr, data, n);
  }
References allocate().
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::operator<<(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::CanonicalTypeNamesProvider::PrintFieldName(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::CanonicalTypeNamesProvider::PrintTypeName(), and v8::internal::wasm::NamesProvider::WriteRef().
Member Data Documentation
chunks_
std::vector<char*> v8::internal::wasm::StringBuilder::chunks_ [private]
Definition at line 118 of file string-builder.h.
Referenced by approximate_size_mb(), Grow(), and ~StringBuilder().
cursor_
char* v8::internal::wasm::StringBuilder::cursor_ = stack_buffer_ [private]
Definition at line 120 of file string-builder.h.
Referenced by allocate(), backspace(), cursor(), Grow(), length(), rewind_to_start(), and start_here().
kChunkSize
constexpr size_t v8::internal::wasm::StringBuilder::kChunkSize = 1024 * 1024 [static], [constexpr], [private]
Definition at line 115 of file string-builder.h.
Referenced by approximate_size_mb(), and Grow().
kStackSize
constexpr size_t v8::internal::wasm::StringBuilder::kStackSize = 256 [static], [constexpr], [private]
Definition at line 113 of file string-builder.h.
on_growth_
const OnGrowth v8::internal::wasm::StringBuilder::on_growth_ [private]
Definition at line 122 of file string-builder.h.
Referenced by Grow(), and ~StringBuilder().
remaining_bytes_
size_t v8::internal::wasm::StringBuilder::remaining_bytes_ = kStackSize [private]
Definition at line 121 of file string-builder.h.
Referenced by allocate(), backspace(), Grow(), and rewind_to_start().
stack_buffer_
char v8::internal::wasm::StringBuilder::stack_buffer_[kStackSize] [private]
Definition at line 117 of file string-builder.h.
Referenced by Grow(), and ~StringBuilder().
start_
char* v8::internal::wasm::StringBuilder::start_ = stack_buffer_ [private]
Definition at line 119 of file string-builder.h.
Referenced by backspace(), Grow(), length(), rewind_to_start(), start(), start_here(), and ~StringBuilder().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/string-builder.h