v8::internal::compiler::CheckTaggedInputParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckTaggedInputParameters (CheckTaggedInputMode mode, const FeedbackSource &feedback)
CheckTaggedInputMode mode () const
const FeedbackSource & feedback () const
Private Attributes
CheckTaggedInputMode mode_
FeedbackSource feedback_
Detailed Description
Definition at line 389 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckTaggedInputParameters()
v8::internal::compiler::CheckTaggedInputParameters::CheckTaggedInputParameters (CheckTaggedInputMode mode, const FeedbackSource & feedback) [inline]
Definition at line 391 of file simplified-operator.h.
      : mode_(mode), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::CheckTaggedInputParameters::feedback () const [inline]
Definition at line 396 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
mode()
CheckTaggedInputMode v8::internal::compiler::CheckTaggedInputParameters::mode () const [inline]
Definition at line 395 of file simplified-operator.h.
{ return mode_; }
Referenced by v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::CheckTaggedInputParameters::feedback_ [private]
Definition at line 400 of file simplified-operator.h.
mode_
CheckTaggedInputMode v8::internal::compiler::CheckTaggedInputParameters::mode_ [private]
Definition at line 399 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h