v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer Class Reference
#include <loop-unrolling-reducer.h>
Public Member Functions
LoopUnrollingAnalyzer (Zone *phase_zone, Graph *input_graph, bool is_wasm)
bool ShouldFullyUnrollLoop (const Block *loop_header) const
bool ShouldPartiallyUnrollLoop (const Block *loop_header) const
size_t GetPartialUnrollCount (const Block *loop_header) const
bool ShouldRemoveLoop (const Block *loop_header) const
IterationCount GetIterationCount (const Block *loop_header) const
ZoneSet< const Block *, LoopFinder::BlockCmp > GetLoopBody (const Block *loop_header)
const Block * GetLoopHeader (const Block *block)
bool CanUnrollAtLeastOneLoop () const
Static Public Attributes
static constexpr size_t kMaxLoopSizeForFullUnrolling = 150
static constexpr size_t kMaxFunctionSizeForPartialUnrolling = 1'000'000
static constexpr size_t kJSMaxLoopSizeForPartialUnrolling = 50
static constexpr size_t kWasmMaxLoopSizeForPartialUnrolling = 80
static constexpr size_t kWasmMaxUnrolledLoopSize = 240
static constexpr size_t kMaxLoopIterationsForFullUnrolling = 4
static constexpr size_t kMaxPartialUnrollingCount = 4
static constexpr size_t kMaxIterForStackCheckRemoval = 5000
Private Member Functions
void DetectUnrollableLoops ()
IterationCount GetLoopIterationCount (const LoopFinder::LoopInfo &info) const
Private Attributes
Graph * input_graph_
OperationMatcher matcher_
LoopFinder loop_finder_
ZoneUnorderedMap< const Block *, IterationCount > loop_iteration_count_
const StaticCanonicalForLoopMatcher canonical_loop_matcher_
const bool is_wasm_
const size_t kMaxLoopSizeForPartialUnrolling
bool can_unroll_at_least_one_loop_ = false
ZoneAbslFlatHashSet< uint32_t > & stack_checks_to_remove_
Detailed Description
Definition at line 168 of file loop-unrolling-reducer.h.
Constructor & Destructor Documentation
LoopUnrollingAnalyzer()
v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::LoopUnrollingAnalyzer (Zone * phase_zone, Graph * input_graph, bool is_wasm) [inline]
Definition at line 182 of file loop-unrolling-reducer.h.
      : input_graph_(input_graph),
        matcher_(*input_graph),
        loop_finder_(phase_zone, input_graph,
                     {LoopFinder::ConfigFlags::kFindCalls}),
        loop_iteration_count_(phase_zone),
        canonical_loop_matcher_(matcher_),
        is_wasm_(is_wasm),
        stack_checks_to_remove_(input_graph->stack_checks_to_remove()) {
    DetectUnrollableLoops();
  }
References v8::internal::compiler::turboshaft::LoopFinder::kFindCalls.
Member Function Documentation
CanUnrollAtLeastOneLoop()
bool v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::CanUnrollAtLeastOneLoop () const [inline]
Definition at line 261 of file loop-unrolling-reducer.h.
{ return can_unroll_at_least_one_loop_; }
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingPhase::Run().
DetectUnrollableLoops()
void v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::DetectUnrollableLoops () [private]
Definition at line 27 of file loop-unrolling-reducer.cc.
                                                  {
  for (const auto& [start, info] : loop_finder_.LoopHeaders()) {
    IterationCount iter_count = GetLoopIterationCount(info);
    TRACE("LoopUnrollingAnalyzer: loop at "
          << start->index() << " ==> iter_count=" << iter_count);
    loop_iteration_count_.insert({start, iter_count});
    if (ShouldFullyUnrollLoop(start) || ShouldPartiallyUnrollLoop(start)) {
      can_unroll_at_least_one_loop_ = true;
    }
    if (iter_count.IsSmallerThan(kMaxIterForStackCheckRemoval)) {
      stack_checks_to_remove_.insert(start->index().id());
    }
  }
}
References can_unroll_at_least_one_loop_, GetLoopIterationCount(), v8::internal::compiler::turboshaft::IterationCount::IsSmallerThan(), kMaxIterForStackCheckRemoval, loop_finder_, loop_iteration_count_, v8::internal::compiler::turboshaft::LoopFinder::LoopHeaders(), ShouldFullyUnrollLoop(), ShouldPartiallyUnrollLoop(), stack_checks_to_remove_, and v8::internal::TRACE().
GetIterationCount()
IterationCount v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetIterationCount (const Block * loop_header) const [inline]
Definition at line 245 of file loop-unrolling-reducer.h.
                                                                   {
    DCHECK(loop_header->IsLoop());
    auto it = loop_iteration_count_.find(loop_header);
    if (it == loop_iteration_count_.end()) return IterationCount::Unknown();
    return it->second;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::IterationCount::Unknown().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FullyUnrollLoop().
GetLoopBody()
ZoneSet<const Block*, LoopFinder::BlockCmp> v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopBody (const Block * loop_header) [inline]
Definition at line 252 of file loop-unrolling-reducer.h.
                                {
    return loop_finder_.GetLoopBody(loop_header);
  }
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FullyUnrollLoop(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::PartiallyUnrollLoop().
GetLoopHeader()
const Block* v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopHeader (const Block * block) [inline]
Definition at line 257 of file loop-unrolling-reducer.h.
                                                 {
    return loop_finder_.GetLoopHeader(block);
  }
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Branch().
GetLoopIterationCount()
IterationCount v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetLoopIterationCount (const LoopFinder::LoopInfo & info) const [private]
Definition at line 44 of file loop-unrolling-reducer.cc.
                                          {
  const Block* start = info.start;
  DCHECK(start->IsLoop());
  // Checking that the condition for the loop can be computed statically, and
  // that the loop contains no more than kMaxLoopIterationsForFullUnrolling
  // iterations.
  const BranchOp* branch =
      start->LastOperation(*input_graph_).TryCast<BranchOp>();
  if (!branch) {
    // This looks like an infinite loop, or like something weird is used to
    // decide whether to loop or not.
    return {};
  }
  // Checking that one of the successor of the loop header is indeed not in the
  // loop (otherwise, the Branch that ends the loop header is not the Branch
  // that decides to exit the loop).
  const Block* if_true_header = loop_finder_.GetLoopHeader(branch->if_true);
  const Block* if_false_header = loop_finder_.GetLoopHeader(branch->if_false);
  if (if_true_header == if_false_header) {
    return {};
  }
  // If {if_true} is in the loop, then we're looping if the condition is true,
  // but if {if_false} is in the loop, then we're looping if the condition is
  // false.
  bool loop_if_cond_is = if_true_header == start;
  return canonical_loop_matcher_.GetIterCountIfStaticCanonicalForLoop(
      start, branch->condition(), loop_if_cond_is);
}
References canonical_loop_matcher_, v8::internal::compiler::turboshaft::BranchOp::condition(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::GetIterCountIfStaticCanonicalForLoop(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopHeader(), v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::LastOperation(), loop_finder_, v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::start, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by DetectUnrollableLoops().
GetPartialUnrollCount()
size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetPartialUnrollCount (const Block * loop_header) const [inline]
Definition at line 216 of file loop-unrolling-reducer.h.
                                                               {
    // Don't unroll if the function is already huge.
    // Otherwise we have run into pathological runtimes or large memory usage,
    // e.g., in register allocation in the past, see https://crbug.com/383661627
    // for an example / reproducer.
    // Even though we return an unroll count of one (i.e., don't unroll at all
    // really), running this phase can speed up subsequent optimizations,
    // probably because it produces loops in a "compact"/good block order for
    // analyses, namely <loop header>, <loop body>, <loop exit>, <rest of code>.
    // In principle, we should fix complexity problems in analyses, make sure
    // loops are already produced in this order, and not rely on the "unrolling"
    // here for the order alone, but this is a longer standing issue.
    if (input_graph_->op_id_count() > kMaxFunctionSizeForPartialUnrolling) {
      return 1;
    }
    if (is_wasm_) {
      LoopFinder::LoopInfo info = loop_finder_.GetLoopInfo(loop_header);
      return std::min(
          LoopUnrollingAnalyzer::kMaxPartialUnrollingCount,
          LoopUnrollingAnalyzer::kWasmMaxUnrolledLoopSize / info.op_count);
    }
    return LoopUnrollingAnalyzer::kMaxPartialUnrollingCount;
  }
References kMaxPartialUnrollingCount, kWasmMaxUnrolledLoopSize, and v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::op_count.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::PartiallyUnrollLoop().
ShouldFullyUnrollLoop()
bool v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldFullyUnrollLoop (const Block * loop_header) const [inline]
Definition at line 194 of file loop-unrolling-reducer.h.
                                                             {
    DCHECK(loop_header->IsLoop());
    LoopFinder::LoopInfo header_info = loop_finder_.GetLoopInfo(loop_header);
    if (header_info.has_inner_loops) return false;
    if (header_info.op_count > kMaxLoopSizeForFullUnrolling) return false;
    auto iter_count = GetIterationCount(loop_header);
    return iter_count.IsExact() &&
           iter_count.exact_count() < kMaxLoopIterationsForFullUnrolling;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::has_inner_loops, v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::op_count.
Referenced by DetectUnrollableLoops(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
ShouldPartiallyUnrollLoop()
bool v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldPartiallyUnrollLoop (const Block * loop_header) const [inline]
Definition at line 206 of file loop-unrolling-reducer.h.
                                                                 {
    DCHECK(loop_header->IsLoop());
    LoopFinder::LoopInfo info = loop_finder_.GetLoopInfo(loop_header);
    return !info.has_inner_loops && !info.has_any_call &&
           info.op_count < kMaxLoopSizeForPartialUnrolling;
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::has_any_call, v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::has_inner_loops, v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::LoopFinder::LoopInfo::op_count.
Referenced by DetectUnrollableLoops(), and v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
ShouldRemoveLoop()
bool v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::ShouldRemoveLoop (const Block * loop_header) const [inline]
Definition at line 240 of file loop-unrolling-reducer.h.
                                                        {
    auto iter_count = GetIterationCount(loop_header);
    return iter_count.IsExact() && iter_count.exact_count() == 0;
  }
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::Goto().
Member Data Documentation
can_unroll_at_least_one_loop_
bool v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::can_unroll_at_least_one_loop_ = false [private]
Definition at line 295 of file loop-unrolling-reducer.h.
Referenced by DetectUnrollableLoops().
canonical_loop_matcher_
const StaticCanonicalForLoopMatcher v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::canonical_loop_matcher_ [private]
Definition at line 290 of file loop-unrolling-reducer.h.
Referenced by GetLoopIterationCount().
input_graph_
Graph* v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::input_graph_ [private]
Definition at line 283 of file loop-unrolling-reducer.h.
is_wasm_
const bool v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::is_wasm_ [private]
Definition at line 291 of file loop-unrolling-reducer.h.
kJSMaxLoopSizeForPartialUnrolling
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kJSMaxLoopSizeForPartialUnrolling = 50 [static], [constexpr]
Definition at line 272 of file loop-unrolling-reducer.h.
kMaxFunctionSizeForPartialUnrolling
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kMaxFunctionSizeForPartialUnrolling = 1'000'000 [static], [constexpr]
Definition at line 271 of file loop-unrolling-reducer.h.
kMaxIterForStackCheckRemoval
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kMaxIterForStackCheckRemoval = 5000 [static], [constexpr]
Definition at line 277 of file loop-unrolling-reducer.h.
Referenced by DetectUnrollableLoops().
kMaxLoopIterationsForFullUnrolling
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kMaxLoopIterationsForFullUnrolling = 4 [static], [constexpr]
Definition at line 275 of file loop-unrolling-reducer.h.
kMaxLoopSizeForFullUnrolling
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kMaxLoopSizeForFullUnrolling = 150 [static], [constexpr]
Definition at line 266 of file loop-unrolling-reducer.h.
kMaxLoopSizeForPartialUnrolling
const size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kMaxLoopSizeForPartialUnrolling [private]
Initial value:
=
      is_wasm_ ? kWasmMaxLoopSizeForPartialUnrolling
               : kJSMaxLoopSizeForPartialUnrolling
Definition at line 292 of file loop-unrolling-reducer.h.
kMaxPartialUnrollingCount
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kMaxPartialUnrollingCount = 4 [static], [constexpr]
Definition at line 276 of file loop-unrolling-reducer.h.
Referenced by GetPartialUnrollCount().
kWasmMaxLoopSizeForPartialUnrolling
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kWasmMaxLoopSizeForPartialUnrolling = 80 [static], [constexpr]
Definition at line 273 of file loop-unrolling-reducer.h.
kWasmMaxUnrolledLoopSize
constexpr size_t v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::kWasmMaxUnrolledLoopSize = 240 [static], [constexpr]
Definition at line 274 of file loop-unrolling-reducer.h.
Referenced by GetPartialUnrollCount().
loop_finder_
LoopFinder v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::loop_finder_ [private]
Definition at line 285 of file loop-unrolling-reducer.h.
Referenced by DetectUnrollableLoops(), and GetLoopIterationCount().
loop_iteration_count_
ZoneUnorderedMap<const Block*, IterationCount> v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::loop_iteration_count_ [private]
Definition at line 289 of file loop-unrolling-reducer.h.
Referenced by DetectUnrollableLoops().
matcher_
OperationMatcher v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::matcher_ [private]
Definition at line 284 of file loop-unrolling-reducer.h.
stack_checks_to_remove_
ZoneAbslFlatHashSet<uint32_t>& v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::stack_checks_to_remove_ [private]
Definition at line 297 of file loop-unrolling-reducer.h.
Referenced by DetectUnrollableLoops().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.cc