v8::internal::SeqSubStringKey< SeqString > Class Template Reference
#include <string-inl.h>
Public Types
using Char = typename SeqString::Char
Public Member Functions
SeqSubStringKey (Isolate *isolate, DirectHandle< SeqString > string, int from, int len, bool convert=false)
bool IsMatch (Isolate *isolate, Tagged< String > string)
void PrepareForInsertion (Isolate *isolate)
DirectHandle< String > GetHandleForInsertion (Isolate *isolate)
Private Attributes
DirectHandle< typename CharTraits< Char >::String > string_
int from_
bool convert_
DirectHandle< String > internalized_string_
Additional Inherited Members
Detailed Description
template<typename SeqString>
class v8::internal::SeqSubStringKey< SeqString >
Definition at line 608 of file string-inl.h.
Member Typedef Documentation
Char
template<typename SeqString >
using v8::internal::SeqSubStringKey< SeqString >::Char = typename SeqString::Char
Definition at line 610 of file string-inl.h.
Constructor & Destructor Documentation
SeqSubStringKey()
template<typename SeqString >
v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey (Isolate * isolate, DirectHandle< SeqString > string, int from, int len, bool convert = false) [inline]
Definition at line 619 of file string-inl.h.
      : StringTableKey(0, len),
        string_(string),
        from_(from),
        convert_(convert) {
    // We have to set the hash later.
    DisallowGarbageCollection no_gc;
    uint32_t raw_hash_field = StringHasher::HashSequentialString(
        string->GetChars(no_gc) + from, len, HashSeed(isolate));
    set_raw_hash_field(raw_hash_field);
    DCHECK_LE(0, length());
    DCHECK_LE(from_ + length(), string_->length());
    DCHECK_EQ(IsSeqOneByteString(*string_), sizeof(Char) == 1);
    DCHECK_EQ(IsSeqTwoByteString(*string_), sizeof(Char) == 2);
  }
References DCHECK_EQ, DCHECK_LE, v8::internal::SeqSubStringKey< SeqString >::from_, v8::internal::HashSeed(), v8::internal::StringHasher::HashSequentialString(), v8::internal::StringTableKey::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StringTableKey::raw_hash_field(), v8::internal::StringTableKey::set_raw_hash_field(), v8::internal::string, and v8::internal::SeqSubStringKey< SeqString >::string_.
Member Function Documentation
GetHandleForInsertion()
template<typename SeqString >
DirectHandle<String> v8::internal::SeqSubStringKey< SeqString >::GetHandleForInsertion (Isolate * isolate) [inline]
Definition at line 669 of file string-inl.h.
                                                               {
    DCHECK(!internalized_string_.is_null());
    return internalized_string_;
  }
References v8::internal::DCHECK(), and v8::internal::SeqSubStringKey< SeqString >::internalized_string_.
IsMatch()
template<typename SeqString >
bool v8::internal::SeqSubStringKey< SeqString >::IsMatch (Isolate * isolate, Tagged< String > string) [inline]
Definition at line 640 of file string-inl.h.
                                                        {
    DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(string));
    DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(*string_));
    DisallowGarbageCollection no_gc;
    return string->IsEqualTo<String::EqualityType::kNoLengthCheck>(
        base::Vector<const Char>(string_->GetChars(no_gc) + from_, length()),
        isolate);
  }
References v8::internal::DCHECK(), v8::internal::SeqSubStringKey< SeqString >::from_, v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::String::kNoLengthCheck, v8::internal::StringTableKey::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SeqSubStringKey< SeqString >::string_.
PrepareForInsertion()
template<typename SeqString >
void v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion (Isolate * isolate) [inline]
Definition at line 649 of file string-inl.h.
                                             {
    if (sizeof(Char) == 1 || (sizeof(Char) == 2 && convert_)) {
      DirectHandle<SeqOneByteString> result =
          isolate->factory()->AllocateRawOneByteInternalizedString(
              length(), raw_hash_field());
      DisallowGarbageCollection no_gc;
      CopyChars(result->GetChars(no_gc), string_->GetChars(no_gc) + from_,
                length());
      internalized_string_ = result;
    } else {
      DirectHandle<SeqTwoByteString> result =
          isolate->factory()->AllocateRawTwoByteInternalizedString(
              length(), raw_hash_field());
      DisallowGarbageCollection no_gc;
      CopyChars(result->GetChars(no_gc), string_->GetChars(no_gc) + from_,
                length());
      internalized_string_ = result;
    }
  }
References v8::internal::FactoryBase< Impl >::AllocateRawOneByteInternalizedString(), v8::internal::FactoryBase< Impl >::AllocateRawTwoByteInternalizedString(), v8::internal::SeqSubStringKey< SeqString >::convert_, v8::internal::CopyChars(), v8::internal::Isolate::factory(), v8::internal::SeqSubStringKey< SeqString >::from_, v8::internal::SeqSubStringKey< SeqString >::internalized_string_, v8::internal::StringTableKey::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StringTableKey::raw_hash_field(), v8::base::internal::result, and v8::internal::SeqSubStringKey< SeqString >::string_.
Member Data Documentation
convert_
template<typename SeqString >
bool v8::internal::SeqSubStringKey< SeqString >::convert_ [private]
Definition at line 677 of file string-inl.h.
Referenced by v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion().
from_
template<typename SeqString >
int v8::internal::SeqSubStringKey< SeqString >::from_ [private]
Definition at line 676 of file string-inl.h.
Referenced by v8::internal::SeqSubStringKey< SeqString >::IsMatch(), v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion(), and v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey().
internalized_string_
template<typename SeqString >
DirectHandle<String> v8::internal::SeqSubStringKey< SeqString >::internalized_string_ [private]
Definition at line 678 of file string-inl.h.
Referenced by v8::internal::SeqSubStringKey< SeqString >::GetHandleForInsertion(), and v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion().
string_
template<typename SeqString >
DirectHandle<typename CharTraits<Char>::String> v8::internal::SeqSubStringKey< SeqString >::string_ [private]
Definition at line 675 of file string-inl.h.
Referenced by v8::internal::SeqSubStringKey< SeqString >::IsMatch(), v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion(), and v8::internal::SeqSubStringKey< SeqString >::SeqSubStringKey().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-inl.h