v8::internal::maglev::CheckMapsWithAlreadyLoadedMap Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckMapsWithAlreadyLoadedMap (uint64_t bitfield, const compiler::ZoneRefSet< Map > &maps)
CheckMapsWithAlreadyLoadedMap (uint64_t bitfield, base::Vector< const compiler::MapRef > maps, Zone *zone)
const compiler::ZoneRefSet< Map > & maps () const
Input & object_input ()
Input & map_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputNodeT< 2, CheckMapsWithAlreadyLoadedMap >
Private Attributes
const compiler::ZoneRefSet< Map > maps_
Additional Inherited Members
Detailed Description
Definition at line 6866 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::Base = FixedInputNodeT<2, CheckMapsWithAlreadyLoadedMap> [private]
Definition at line 6868 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckMapsWithAlreadyLoadedMap() [1/2]
v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::CheckMapsWithAlreadyLoadedMap (uint64_t bitfield, const compiler::ZoneRefSet< Map > & maps) [inline], [explicit]
Definition at line 6871 of file maglev-ir.h.
      : Base(bitfield), maps_(maps) {}
CheckMapsWithAlreadyLoadedMap() [2/2]
v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::CheckMapsWithAlreadyLoadedMap (uint64_t bitfield, base::Vector< const compiler::MapRef > maps, Zone * zone) [inline], [explicit]
Definition at line 6874 of file maglev-ir.h.
      : Base(bitfield), maps_(maps.begin(), maps.end(), zone) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::GenerateCode (MaglevAssembler * , const ProcessingState &)
map_input()
Input& v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::map_input () [inline]
Definition at line 6886 of file maglev-ir.h.
{ return input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
maps()
const compiler::ZoneRefSet<Map>& v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::maps () const [inline]
Definition at line 6883 of file maglev-ir.h.
{ return maps_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::object_input () [inline]
Definition at line 6885 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::options () const [inline]
Definition at line 6892 of file maglev-ir.h.
{ return std::tuple{maps_}; }
PrintParams()
void v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8044 of file maglev-ir.cc.
                                                               {
  os << "(";
  bool first = true;
  for (compiler::MapRef map : maps()) {
    if (first) {
      first = false;
    } else {
      os << ", ";
    }
    os << *map.object();
  }
  os << ")";
}
References maps().
SetValueLocationConstraints()
void v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 6880 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::EagerDeopt() | OpProperties::CanRead()
Definition at line 6878 of file maglev-ir.h.
maps_
const compiler::ZoneRefSet<Map> v8::internal::maglev::CheckMapsWithAlreadyLoadedMap::maps_ [private]
Definition at line 6895 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc