v8::internal::StoreGlobalIC Class Reference
#include <ic.h>
Public Member Functions
StoreGlobalIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Store (Handle< Name > name, DirectHandle< Object > value)
Additional Inherited Members
Detailed Description
Definition at line 292 of file ic.h.
Constructor & Destructor Documentation
StoreGlobalIC()
v8::internal::StoreGlobalIC::StoreGlobalIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind) [inline]
Definition at line 294 of file ic.h.
      : StoreIC(isolate, vector, slot, kind) {}
Member Function Documentation
Store()
MaybeDirectHandle< Object > v8::internal::StoreGlobalIC::Store (Handle< Name > name, DirectHandle< Object > value)
Definition at line 1738 of file ic.cc.
                                                                           {
  DCHECK(IsString(*name));
  // Look up in script context table.
  DirectHandle<String> str_name = Cast<String>(name);
  Handle<JSGlobalObject> global = isolate()->global_object();
  DirectHandle<ScriptContextTable> script_contexts(
      global->native_context()->script_context_table(), isolate());
  VariableLookupResult lookup_result;
  if (script_contexts->Lookup(str_name, &lookup_result)) {
    DisallowGarbageCollection no_gc;
    DisableGCMole no_gcmole;
    Tagged<Context> script_context =
        script_contexts->get(lookup_result.context_index);
    if (IsImmutableLexicalVariableMode(lookup_result.mode)) {
      AllowGarbageCollection yes_gc;
      return TypeError(MessageTemplate::kConstAssign, global, name);
    }
    if (script_context->IsElementTheHole(lookup_result.slot_index)) {
      // Do not install stubs and stay pre-monomorphic for uninitialized
      // accesses.
      AllowGarbageCollection yes_gc;
      THROW_NEW_ERROR(
          isolate(),
          NewReferenceError(MessageTemplate::kAccessedUninitializedVariable,
                            name));
    }
    bool use_ic = (state() != NO_FEEDBACK) && v8_flags.use_ic;
    if (use_ic) {
      if (nexus()->ConfigureLexicalVarMode(
              lookup_result.context_index, lookup_result.slot_index,
              IsImmutableLexicalVariableMode(lookup_result.mode))) {
        TRACE_HANDLER_STATS(isolate(), StoreGlobalIC_StoreScriptContextField);
      } else {
        // Given combination of indices can't be encoded, so use slow stub.
        TRACE_HANDLER_STATS(isolate(), StoreGlobalIC_SlowStub);
        SetCache(name, StoreHandler::StoreSlow(isolate()));
      }
      TraceIC("StoreGlobalIC", name);
    } else if (state() == NO_FEEDBACK) {
      TraceIC("StoreGlobalIC", name);
    }
    AllowGarbageCollection yes_gc;
    Context::Set(handle(script_context, isolate()), lookup_result.slot_index,
                 value, isolate());
    return value;
  }
  return StoreIC::Store(global, name, value);
}
References v8::internal::FeedbackNexus::ConfigureLexicalVarMode(), v8::internal::VariableLookupResult::context_index, v8::internal::DCHECK(), v8::internal::Isolate::global_object(), v8::internal::handle(), v8::internal::if(), v8::internal::IsImmutableLexicalVariableMode(), v8::internal::IC::isolate(), v8::internal::VariableLookupResult::mode, v8::internal::name, v8::internal::IC::nexus(), v8::internal::NO_FEEDBACK, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::Set(), v8::internal::IC::SetCache(), v8::internal::VariableLookupResult::slot_index, v8::internal::IC::state(), v8::internal::StoreIC::Store(), v8::internal::StoreHandler::StoreSlow(), THROW_NEW_ERROR, TRACE_HANDLER_STATS, v8::internal::IC::TraceIC(), v8::internal::IC::TypeError(), v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc