cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper Class Reference
Public Member Functions
MutatorThreadSweeper (HeapBase *heap, cppgc::Platform *platform, StatsCollector *stats_collector, BaseSpace *space, size_t *unused_destroyed_normal_pages, FreeMemoryHandling free_memory_handling, EmptyPageHandling empty_page_handling)
void Sweep (SpaceStates &states)
void Sweep (SweepingState &state)
void SweepPage (BasePage &page)
bool FinalizeAndSweepWithDeadline (StatsCollector::ScopeId scope_id, SweepingState &state, v8::base::TimeTicks deadline, MutatorThreadSweepingMode sweeping_mode)
bool SweepWithDeadlineAndSize (StatsCollector::ScopeId scope_id, SweepingState &state, v8::base::TimeTicks deadline, size_t size)
Static Public Member Functions
static void SweepLiveLargePage (LargePage &page, StickyBits sticky_bits)
Private Types
using FreeMemoryHandling = SweepingConfig::FreeMemoryHandling
Private Member Functions
bool SweepSpaceWithDeadline (SweepingState *state, v8::base::TimeTicks deadline)
bool VisitNormalPage (NormalPage &page)
bool VisitLargePage (LargePage &page)
Private Attributes
cppgc::Platform * platform_
StatsCollector * stats_collector_
size_t largest_consecutive_block_ = 0
BaseSpace * space_
size_t * unused_destroyed_normal_pages_
const FreeMemoryHandling free_memory_handling_
const EmptyPageHandling empty_page_handling_
const StickyBits sticky_bits_
Friends
class HeapVisitor< MutatorThreadSweeper >
Detailed Description
Definition at line 605 of file sweeper.cc.
Member Typedef Documentation
FreeMemoryHandling
using cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::FreeMemoryHandling = SweepingConfig::FreeMemoryHandling [private]
Definition at line 608 of file sweeper.cc.
Constructor & Destructor Documentation
MutatorThreadSweeper()
cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::MutatorThreadSweeper (HeapBase * heap, cppgc::Platform * platform, StatsCollector * stats_collector, BaseSpace * space, size_t * unused_destroyed_normal_pages, FreeMemoryHandling free_memory_handling, EmptyPageHandling empty_page_handling) [inline]
Definition at line 611 of file sweeper.cc.
      : platform_(platform),
        stats_collector_(stats_collector),
        space_(space),
        unused_destroyed_normal_pages_(unused_destroyed_normal_pages),
        free_memory_handling_(free_memory_handling),
        empty_page_handling_(empty_page_handling),
        sticky_bits_(heap->sticky_bits()) {}
Member Function Documentation
FinalizeAndSweepWithDeadline()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::FinalizeAndSweepWithDeadline (StatsCollector::ScopeId scope_id, SweepingState & state, v8::base::TimeTicks deadline, MutatorThreadSweepingMode sweeping_mode) [inline]
Definition at line 650 of file sweeper.cc.
                                                                             {
    // First, prioritize finalization of pages that were swept concurrently.
    SweepFinalizer finalizer(
        platform_, stats_collector_, space_, unused_destroyed_normal_pages_,
        free_memory_handling_, EmptyPageHandling::kDestroy);
    if (!finalizer.FinalizeWithDeadline(scope_id, state, deadline)) {
      return false;
    }
    if (sweeping_mode != MutatorThreadSweepingMode::kOnlyFinalizers) {
      // Help out the concurrent sweeper.
      if (!SweepSpaceWithDeadline(&state, deadline)) {
        return false;
      }
    }
    return true;
  }
References cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadline().
Sweep() [1/2]
void cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::Sweep (SpaceStates & states) [inline]
Definition at line 634 of file sweeper.cc.
                                  {
    for (SweepingState& state : states) {
      Sweep(state);
    }
  }
Sweep() [2/2]
void cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::Sweep (SweepingState & state) [inline]
Definition at line 640 of file sweeper.cc.
                                   {
    while (auto page = state.unswept_pages.Pop()) {
      SweepPage(**page);
    }
  }
References cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::unswept_pages.
SweepLiveLargePage()
static void cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage (LargePage & page, StickyBits sticky_bits) [inline], [static]
Definition at line 624 of file sweeper.cc.
                                                                          {
    HeapObjectHeader* header = page.ObjectHeader();
    CHECK(header->IsMarked());
    StickyUnmark(header, sticky_bits);
    if (sticky_bits == StickyBits::kDisabled) {
      page.ResetMarkedBytes();
    }
    page.space().AddPage(&page);
  }
References cppgc::internal::BaseSpace::AddPage(), CHECK, cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kDisabled, cppgc::internal::LargePage::ObjectHeader(), cppgc::internal::BasePage::ResetMarkedBytes(), cppgc::internal::BasePage::space(), and cppgc::internal::anonymous_namespace{sweeper.cc}::StickyUnmark().
SweepPage()
void cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepPage (BasePage & page) [inline]
Definition at line 646 of file sweeper.cc.
{ Traverse(page); }
SweepSpaceWithDeadline()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepSpaceWithDeadline (SweepingState * state, v8::base::TimeTicks deadline) [inline], [private]
Definition at line 692 of file sweeper.cc.
                                                        {
    DeadlineChecker deadline_check(deadline);
    while (auto page = state->unswept_pages.Pop()) {
      Traverse(**page);
      if (deadline_check.Check()) {
        return false;
      }
    }
    return true;
  }
References cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::Check(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::unswept_pages.
SweepWithDeadlineAndSize()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepWithDeadlineAndSize (StatsCollector::ScopeId scope_id, SweepingState & state, v8::base::TimeTicks deadline, size_t size) [inline]
Definition at line 671 of file sweeper.cc.
                                                                       {
    if (state.unswept_pages.IsEmpty()) {
      return false;
    }
    StatsCollector::DisabledScope sweep_scope(stats_collector_, scope_id);
    DeadlineChecker deadline_check(deadline);
    while (auto page = state.unswept_pages.Pop()) {
      SweepPage(**page);
      if (size <= largest_consecutive_block_) {
        return true;
      }
      if (deadline_check.Check()) {
        break;
      }
    }
    return false;
  }
References cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::Check(), size(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::unswept_pages.
VisitLargePage()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage (LargePage & page) [inline], [private]
Definition at line 741 of file sweeper.cc.
                                       {
    HeapObjectHeader* header = page.ObjectHeader();
    CHECK(!header->IsMarked());
    DCHECK_EQ(page.marked_bytes(), 0u);
    header->Finalize();
    largest_consecutive_block_ =
        std::max(page.PayloadSize(), largest_consecutive_block_);
    LargePage::Destroy(&page);
    return true;
  }
References CHECK, DCHECK_EQ, cppgc::internal::LargePage::Destroy(), cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::BasePage::marked_bytes(), cppgc::internal::LargePage::ObjectHeader(), and cppgc::internal::LargePage::PayloadSize().
VisitNormalPage()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage (NormalPage & page) [inline], [private]
Definition at line 705 of file sweeper.cc.
                                         {
    if (free_memory_handling_ == FreeMemoryHandling::kDiscardWherePossible) {
      page.ResetDiscardedMemory();
    }
    const auto result =
        free_memory_handling_ == FreeMemoryHandling::kDiscardWherePossible
            ? SweepNormalPage<
                  InlinedFinalizationBuilder<DiscardingFreeHandler>>(
                  &page, *platform_->GetPageAllocator(), sticky_bits_)
            : SweepNormalPage<InlinedFinalizationBuilder<RegularFreeHandler>>(
                  &page, *platform_->GetPageAllocator(), sticky_bits_);
    if (result.is_empty &&
        empty_page_handling_ == EmptyPageHandling::kDestroy) {
      NormalPage::Destroy(&page);
      (*unused_destroyed_normal_pages_)++;
    } else {
      if (space_) {
        DCHECK_IMPLIES(!result.is_empty, space_ == &page.space());
        page.ChangeOwner(*space_);
      }
      auto& target_space = NormalPageSpace::From(page.space());
      target_space.AddPage(&page);
      if (result.is_empty) {
        target_space.free_list().Add({page.PayloadStart(), page.PayloadSize()});
      }
      // The page was eagerly finalized and all the freelist have been merged.
      // Verify that the bitmap is consistent with headers.
      ObjectStartBitmapVerifier().Verify(page);
      largest_consecutive_block_ =
          std::max(result.is_empty ? page.PayloadSize()
                                   : result.largest_new_free_list_entry,
                   largest_consecutive_block_);
    }
    return true;
  }
References cppgc::internal::BasePage::ChangeOwner(), DCHECK_IMPLIES, cppgc::internal::NormalPage::Destroy(), cppgc::internal::NormalPageSpace::From(), cppgc::internal::kDiscardWherePossible, cppgc::internal::NormalPage::PayloadSize(), cppgc::internal::NormalPage::PayloadStart(), cppgc::internal::BasePage::ResetDiscardedMemory(), v8::base::internal::result, cppgc::internal::BasePage::space(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::Verify().
Friends And Related Function Documentation
HeapVisitor< MutatorThreadSweeper >
friend class HeapVisitor< MutatorThreadSweeper > [friend]
Definition at line 602 of file sweeper.cc.
Member Data Documentation
empty_page_handling_
const EmptyPageHandling cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::empty_page_handling_ [private]
Definition at line 760 of file sweeper.cc.
free_memory_handling_
const FreeMemoryHandling cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::free_memory_handling_ [private]
Definition at line 759 of file sweeper.cc.
largest_consecutive_block_
size_t cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::largest_consecutive_block_ = 0 [private]
Definition at line 756 of file sweeper.cc.
platform_
cppgc::Platform* cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::platform_ [private]
Definition at line 752 of file sweeper.cc.
space_
BaseSpace* cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::space_ [private]
Definition at line 757 of file sweeper.cc.
stats_collector_
StatsCollector* cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::stats_collector_ [private]
Definition at line 753 of file sweeper.cc.
sticky_bits_
const StickyBits cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::sticky_bits_ [private]
Definition at line 761 of file sweeper.cc.
unused_destroyed_normal_pages_
size_t* cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::unused_destroyed_normal_pages_ [private]
Definition at line 758 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc