v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped > Class Template Reference
#include <code-assembler.h>
Public Member Functions
CheckedNode (compiler::Node *node, CodeAssembler *, const char *)
template<class A >
operator TNode< A > ()
Node * node () const
Private Attributes
Node * node_
Detailed Description
template<class PreviousType, bool FromTyped>
class v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >
Definition at line 481 of file code-assembler.h.
Constructor & Destructor Documentation
CheckedNode()
template<class PreviousType , bool FromTyped>
v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::CheckedNode (compiler::Node * node, CodeAssembler * , const char *) [inline]
Definition at line 487 of file code-assembler.h.
        : node_(node) {}
Member Function Documentation
node()
template<class PreviousType , bool FromTyped>
Node* v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::node () const [inline]
Definition at line 523 of file code-assembler.h.
{ return node_; }
operator TNode< A >()
template<class PreviousType , bool FromTyped>
template<class A >
v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::operator TNode< A > () [inline]
Definition at line 492 of file code-assembler.h.
                        {
      static_assert(!std::is_same_v<A, Tagged<MaybeObject>>,
                    "Can't cast to Tagged<MaybeObject>, use explicit "
                    "conversion functions. ");
      static_assert(types_have_common_values<A, PreviousType>::value,
                    "Incompatible types: this cast can never succeed.");
      static_assert(std::is_convertible_v<TNode<A>, TNode<MaybeObject>> ||
                        std::is_convertible_v<TNode<A>, TNode<Object>>,
                    "Coercion to untagged values cannot be "
                    "checked.");
      static_assert(
          !FromTyped || !std::is_convertible_v<TNode<PreviousType>, TNode<A>>,
          "Unnecessary CAST: types are convertible.");
#ifdef DEBUG
      if (v8_flags.slow_debug_code) {
        TNode<ExternalReference> function = code_assembler_->ExternalConstant(
            ExternalReference::check_object_type());
        code_assembler_->CallCFunction(
            function, MachineType::AnyTagged(),
            std::make_pair(MachineType::AnyTagged(), node_),
            std::make_pair(MachineType::TaggedSigned(),
                           code_assembler_->SmiConstant(
                               static_cast<int>(ObjectTypeOf<A>::value))),
            std::make_pair(MachineType::AnyTagged(),
                           code_assembler_->StringConstant(location_)));
      }
#endif
      return TNode<A>::UncheckedCast(node_);
    }
References v8::internal::A, v8::internal::MachineType::AnyTagged(), v8::internal::MachineType::TaggedSigned(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::v8_flags.
Member Data Documentation
node_
template<class PreviousType , bool FromTyped>
Node* v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::node_ [private]
Definition at line 526 of file code-assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/code-assembler.h