v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData Class Reference
Public Member Functions
AssignType assign_type () const
bool is_private_assign_type () const
Expression * expr () const
Expression * object_expr () const
Register object () const
Register key () const
const AstRawString * name () const
RegisterList super_property_args () const
Static Public Member Functions
static AssignmentLhsData NonProperty (Expression *expr)
static AssignmentLhsData NamedProperty (Expression *object_expr, Register object, const AstRawString *name)
static AssignmentLhsData KeyedProperty (Register object, Register key)
static AssignmentLhsData PrivateMethodOrAccessor (AssignType type, Property *property, Register object, Register key)
static AssignmentLhsData PrivateDebugEvaluate (AssignType type, Property *property, Register object)
static AssignmentLhsData NamedSuperProperty (RegisterList super_property_args)
static AssignmentLhsData KeyedSuperProperty (RegisterList super_property_args)
Private Member Functions
AssignmentLhsData (AssignType assign_type, Expression *expr, RegisterList super_property_args, Register object, Register key, Expression *object_expr, const AstRawString *name)
Private Attributes
AssignType assign_type_
Expression * expr_
RegisterList super_property_args_
Register object_
Register key_
Expression * object_expr_
const AstRawString * name_
Detailed Description
Definition at line 115 of file bytecode-generator.h.
Constructor & Destructor Documentation
AssignmentLhsData()
v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::AssignmentLhsData (AssignType assign_type, Expression * expr, RegisterList super_property_args, Register object, Register key, Expression * object_expr, const AstRawString * name) [inline], [private]
Definition at line 171 of file bytecode-generator.h.
        : assign_type_(assign_type),
          expr_(expr),
          super_property_args_(super_property_args),
          object_(object),
          key_(key),
          object_expr_(object_expr),
          name_(name) {}
Referenced by NonProperty().
Member Function Documentation
assign_type()
AssignType v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::assign_type () const [inline]
Definition at line 134 of file bytecode-generator.h.
{ return assign_type_; }
References assign_type_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment().
expr()
Expression* v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::expr () const [inline]
Definition at line 142 of file bytecode-generator.h.
                             {
      DCHECK(assign_type_ == NON_PROPERTY || is_private_assign_type());
      return expr_;
    }
References assign_type_, v8::internal::DCHECK(), expr_, is_private_assign_type(), and v8::internal::NON_PROPERTY.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment(), and NonProperty().
is_private_assign_type()
bool v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::is_private_assign_type () const [inline]
Definition at line 135 of file bytecode-generator.h.
                                        {
      return assign_type_ == PRIVATE_METHOD ||
             assign_type_ == PRIVATE_GETTER_ONLY ||
             assign_type_ == PRIVATE_SETTER_ONLY ||
             assign_type_ == PRIVATE_GETTER_AND_SETTER ||
             assign_type_ == PRIVATE_DEBUG_DYNAMIC;
    }
References assign_type_, v8::internal::PRIVATE_DEBUG_DYNAMIC, v8::internal::PRIVATE_GETTER_AND_SETTER, v8::internal::PRIVATE_GETTER_ONLY, v8::internal::PRIVATE_METHOD, and v8::internal::PRIVATE_SETTER_ONLY.
Referenced by expr(), key(), and object().
key()
Register v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::key () const [inline]
Definition at line 155 of file bytecode-generator.h.
                         {
      DCHECK((assign_type_ == KEYED_PROPERTY || is_private_assign_type()) &&
             assign_type_ != PRIVATE_DEBUG_DYNAMIC);
      return key_;
    }
References assign_type_, v8::internal::DCHECK(), is_private_assign_type(), key_, v8::internal::KEYED_PROPERTY, and v8::internal::PRIVATE_DEBUG_DYNAMIC.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
KeyedProperty()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::KeyedProperty (Register object, Register key) [static]
Definition at line 4981 of file bytecode-generator.cc.
                                                                  {
  return AssignmentLhsData(KEYED_PROPERTY, nullptr, RegisterList(), object, key,
                           nullptr, nullptr);
}
References v8::internal::key, and v8::internal::KEYED_PROPERTY.
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
KeyedSuperProperty()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::KeyedSuperProperty (RegisterList super_property_args) [static]
Definition at line 5010 of file bytecode-generator.cc.
                                      {
  return AssignmentLhsData(KEYED_SUPER_PROPERTY, nullptr, super_property_args,
                           Register(), Register(), nullptr, nullptr);
}
References v8::internal::KEYED_SUPER_PROPERTY, and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
name()
const AstRawString* v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::name () const [inline]
Definition at line 160 of file bytecode-generator.h.
                                     {
      DCHECK(assign_type_ == NAMED_PROPERTY);
      return name_;
    }
References assign_type_, v8::internal::DCHECK(), name_, and v8::internal::NAMED_PROPERTY.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
NamedProperty()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NamedProperty (Expression * object_expr, Register object, const AstRawString * name) [static]
Definition at line 4973 of file bytecode-generator.cc.
                                                                              {
  return AssignmentLhsData(NAMED_PROPERTY, nullptr, RegisterList(), object,
                           Register(), object_expr, name);
}
References v8::internal::name, v8::internal::NAMED_PROPERTY, and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
NamedSuperProperty()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NamedSuperProperty (RegisterList super_property_args) [static]
Definition at line 4988 of file bytecode-generator.cc.
                                      {
  return AssignmentLhsData(NAMED_SUPER_PROPERTY, nullptr, super_property_args,
                           Register(), Register(), nullptr, nullptr);
}
References v8::internal::NAMED_SUPER_PROPERTY, and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
NonProperty()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NonProperty (Expression * expr) [static]
Definition at line 4967 of file bytecode-generator.cc.
                                                                {
  return AssignmentLhsData(NON_PROPERTY, expr, RegisterList(), Register(),
                           Register(), nullptr, nullptr);
}
References AssignmentLhsData(), expr(), v8::internal::NON_PROPERTY, and v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
object()
Register v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::object () const [inline]
Definition at line 150 of file bytecode-generator.h.
                            {
      DCHECK(assign_type_ == NAMED_PROPERTY || assign_type_ == KEYED_PROPERTY ||
             is_private_assign_type());
      return object_;
    }
References assign_type_, v8::internal::DCHECK(), is_private_assign_type(), v8::internal::KEYED_PROPERTY, v8::internal::NAMED_PROPERTY, and object_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
object_expr()
Expression* v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::object_expr () const [inline]
Definition at line 146 of file bytecode-generator.h.
                                    {
      DCHECK_EQ(assign_type_, NAMED_PROPERTY);
      return object_expr_;
    }
References assign_type_, DCHECK_EQ, v8::internal::NAMED_PROPERTY, and object_expr_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
PrivateDebugEvaluate()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::PrivateDebugEvaluate (AssignType type, Property * property, Register object) [static]
Definition at line 5002 of file bytecode-generator.cc.
                                                                            {
  return AssignmentLhsData(type, property, RegisterList(), object, Register(),
                           nullptr, nullptr);
}
References v8::internal::ETWJITInterface::Register(), and v8::internal::tracing::type.
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
PrivateMethodOrAccessor()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::PrivateMethodOrAccessor (AssignType type, Property * property, Register object, Register key) [static]
Definition at line 4995 of file bytecode-generator.cc.
                                                                        {
  return AssignmentLhsData(type, property, RegisterList(), object, key, nullptr,
                           nullptr);
}
References v8::internal::key, and v8::internal::tracing::type.
Referenced by v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs().
super_property_args()
RegisterList v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::super_property_args () const [inline]
Definition at line 164 of file bytecode-generator.h.
                                             {
      DCHECK(assign_type_ == NAMED_SUPER_PROPERTY ||
             assign_type_ == KEYED_SUPER_PROPERTY);
      return super_property_args_;
    }
References assign_type_, v8::internal::DCHECK(), v8::internal::KEYED_SUPER_PROPERTY, v8::internal::NAMED_SUPER_PROPERTY, and super_property_args_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
Member Data Documentation
assign_type_
AssignType v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::assign_type_ [private]
Definition at line 183 of file bytecode-generator.h.
Referenced by assign_type(), expr(), is_private_assign_type(), key(), name(), object(), object_expr(), and super_property_args().
expr_
Expression* v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::expr_ [private]
Definition at line 192 of file bytecode-generator.h.
Referenced by expr().
key_
Register v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::key_ [private]
Definition at line 195 of file bytecode-generator.h.
Referenced by key().
name_
const AstRawString* v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::name_ [private]
Definition at line 197 of file bytecode-generator.h.
Referenced by name().
object_
Register v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::object_ [private]
Definition at line 194 of file bytecode-generator.h.
Referenced by object().
object_expr_
Expression* v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::object_expr_ [private]
Definition at line 196 of file bytecode-generator.h.
Referenced by object_expr().
super_property_args_
RegisterList v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::super_property_args_ [private]
Definition at line 193 of file bytecode-generator.h.
Referenced by super_property_args().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.h
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc