v8::internal::wasm::CompileTimeImports Class Reference
#include <wasm-features.h>
Public Member Functions
CompileTimeImports ()=default
CompileTimeImports (const CompileTimeImports &other) V8_NOEXCEPT=default
CompileTimeImports & operator= (const CompileTimeImports &other) V8_NOEXCEPT=default
CompileTimeImports (CompileTimeImports &&other) V8_NOEXCEPT
CompileTimeImports & operator= (CompileTimeImports &&other) V8_NOEXCEPT
bool empty () const
bool has_string_constants (base::Vector< const uint8_t > name) const
bool contains (CompileTimeImport imp) const
int compare (const CompileTimeImports &other) const
void Add (CompileTimeImport imp)
std::string & constants_module ()
const std::string & constants_module () const
CompileTimeImportFlags flags () const
Static Public Member Functions
static CompileTimeImports FromSerialized (CompileTimeImportFlags::StorageType flags, base::Vector< const char > constants_module)
Private Attributes
CompileTimeImportFlags bits_
std::string constants_module_
Detailed Description
Definition at line 150 of file wasm-features.h.
Constructor & Destructor Documentation
CompileTimeImports() [1/3]
v8::internal::wasm::CompileTimeImports::CompileTimeImports () [default]
CompileTimeImports() [2/3]
v8::internal::wasm::CompileTimeImports::CompileTimeImports (const CompileTimeImports & other) [default]
CompileTimeImports() [3/3]
v8::internal::wasm::CompileTimeImports::CompileTimeImports (CompileTimeImports && other) [inline]
Definition at line 157 of file wasm-features.h.
                                                             {
    *this = std::move(other);
  }
Member Function Documentation
Add()
void v8::internal::wasm::CompileTimeImports::Add (CompileTimeImport imp) [inline]
Definition at line 189 of file wasm-features.h.
{ bits_.Add(imp); }
References v8::base::EnumSet< E, T >::Add(), and bits_.
compare()
int v8::internal::wasm::CompileTimeImports::compare (const CompileTimeImports & other) const [inline]
Definition at line 183 of file wasm-features.h.
                                                     {
    if (bits_.ToIntegral() < other.bits_.ToIntegral()) return -1;
    if (bits_.ToIntegral() > other.bits_.ToIntegral()) return 1;
    return constants_module_.compare(other.constants_module_);
  }
References bits_, constants_module_, and v8::base::EnumSet< E, T >::ToIntegral().
Referenced by v8::internal::wasm::NativeModuleCache::Key::operator<(), v8::internal::wasm::NativeModuleCache::Key::operator==(), and v8::internal::wasm::NativeModuleDeserializer::Read().
constants_module() [1/2]
std::string& v8::internal::wasm::CompileTimeImports::constants_module () [inline]
Definition at line 191 of file wasm-features.h.
{ return constants_module_; }
References constants_module_.
Referenced by v8::internal::wasm::NativeModule::EstimateCurrentMemoryConsumption(), FromSerialized(), v8::internal::wasm::GetImports(), v8::internal::wasm::NativeModuleSerializer::Measure(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), and v8::internal::wasm::NativeModuleSerializer::WriteHeader().
constants_module() [2/2]
const std::string& v8::internal::wasm::CompileTimeImports::constants_module () const [inline]
Definition at line 192 of file wasm-features.h.
{ return constants_module_; }
References constants_module_.
contains()
bool v8::internal::wasm::CompileTimeImports::contains (CompileTimeImport imp) const [inline]
Definition at line 181 of file wasm-features.h.
{ return bits_.contains(imp); }
References bits_, and v8::base::EnumSet< E, T >::contains().
Referenced by v8::internal::wasm::WasmCompilationUnit::CompileWasmFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), v8::internal::wasm::GetImports(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), and v8::internal::wasm::ValidateAndSetBuiltinImports().
empty()
bool v8::internal::wasm::CompileTimeImports::empty () const [inline]
Definition at line 175 of file wasm-features.h.
{ return bits_.empty(); }
References bits_, and v8::base::EnumSet< E, T >::empty().
Referenced by v8::internal::wasm::ValidateAndSetBuiltinImports().
flags()
CompileTimeImportFlags v8::internal::wasm::CompileTimeImports::flags () const [inline]
Definition at line 194 of file wasm-features.h.
{ return bits_; }
References bits_.
Referenced by FromSerialized(), and v8::internal::wasm::NativeModuleSerializer::WriteHeader().
FromSerialized()
static CompileTimeImports v8::internal::wasm::CompileTimeImports::FromSerialized (CompileTimeImportFlags::StorageType flags, base::Vector< const char > constants_module) [inline], [static]
Definition at line 165 of file wasm-features.h.
                                               {
    CompileTimeImports result;
    result.bits_ = CompileTimeImportFlags::FromIntegral(flags);
    result.constants_module_.assign(constants_module.begin(),
                                    constants_module.end());
    return result;
  }
References constants_module(), flags(), v8::base::EnumSet< CompileTimeImport, int >::FromIntegral(), and v8::base::internal::result.
Referenced by v8::internal::wasm::NativeModuleDeserializer::ReadHeader().
has_string_constants()
bool v8::internal::wasm::CompileTimeImports::has_string_constants (base::Vector< const uint8_t > name) const [inline]
Definition at line 176 of file wasm-features.h.
                                                                  {
    return bits_.contains(CompileTimeImport::kStringConstants) &&
           constants_module_.size() == name.size() &&
           std::equal(name.begin(), name.end(), constants_module_.begin());
  }
References bits_, constants_module_, v8::base::EnumSet< E, T >::contains(), v8::internal::equal, v8::internal::wasm::kStringConstants, and v8::internal::wasm::name().
Referenced by v8::internal::wasm::ValidateAndSetBuiltinImports().
operator=() [1/2]
CompileTimeImports& v8::internal::wasm::CompileTimeImports::operator= (CompileTimeImports && other) [inline]
Definition at line 160 of file wasm-features.h.
                                                                        {
    bits_ = other.bits_;
    constants_module_ = std::move(other.constants_module_);
    return *this;
  }
References v8::base::EnumSet< E, T >::bits_, bits_, and constants_module_.
operator=() [2/2]
CompileTimeImports& v8::internal::wasm::CompileTimeImports::operator= (const CompileTimeImports & other) [default]
Member Data Documentation
bits_
CompileTimeImportFlags v8::internal::wasm::CompileTimeImports::bits_ [private]
Definition at line 197 of file wasm-features.h.
Referenced by Add(), compare(), contains(), empty(), flags(), has_string_constants(), and operator=().
constants_module_
std::string v8::internal::wasm::CompileTimeImports::constants_module_ [private]
Definition at line 198 of file wasm-features.h.
Referenced by compare(), constants_module(), has_string_constants(), and operator=().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-features.h