v8::internal::SerializedHandleChecker Class Reference
#include <startup-serializer.h>
Public Member Functions
SerializedHandleChecker (Isolate *isolate, std::vector< Tagged< Context >> *contexts)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
bool CheckGlobalAndEternalHandles ()
Private Member Functions
void AddToSet (Tagged< FixedArray > serialized)
Private Attributes
Isolate * isolate_
std::unordered_set< Tagged< Object >, Object::Hasher > serialized_
bool ok_ = true
Additional Inherited Members
Detailed Description
Definition at line 60 of file startup-serializer.h.
Constructor & Destructor Documentation
SerializedHandleChecker()
v8::internal::SerializedHandleChecker::SerializedHandleChecker (Isolate * isolate, std::vector< Tagged< Context >> * contexts)
Definition at line 187 of file startup-serializer.cc.
    : isolate_(isolate) {
  AddToSet(Cast<FixedArray>(isolate->heap()->serialized_objects()));
  for (auto const& context : *contexts) {
    AddToSet(Cast<FixedArray>(context->serialized_objects()));
  }
}
References AddToSet(), and v8::internal::Isolate::heap().
Member Function Documentation
AddToSet()
void v8::internal::SerializedHandleChecker::AddToSet (Tagged< FixedArray > serialized) [private]
Definition at line 217 of file startup-serializer.cc.
                                                                    {
  int length = serialized->length();
  for (int i = 0; i < length; i++) serialized_.insert(serialized->get(i));
}
References v8::internal::length, and serialized_.
Referenced by SerializedHandleChecker().
CheckGlobalAndEternalHandles()
bool v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles ()
Definition at line 236 of file startup-serializer.cc.
                                                           {
  isolate_->global_handles()->IterateAllRoots(this);
  isolate_->traced_handles()->Iterate(this);
  isolate_->eternal_handles()->IterateAllRoots(this);
  return ok_;
}
References v8::internal::Isolate::eternal_handles(), v8::internal::Isolate::global_handles(), isolate_, v8::internal::TracedHandles::Iterate(), v8::internal::GlobalHandles::IterateAllRoots(), v8::internal::EternalHandles::IterateAllRoots(), ok_, and v8::internal::Isolate::traced_handles().
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob().
VisitRootPointers()
void v8::internal::SerializedHandleChecker::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 222 of file startup-serializer.cc.
                                                                    {
  for (FullObjectSlot p = start; p < end; ++p) {
    if (serialized_.find(*p) != serialized_.end()) continue;
    PrintF("%s handle not serialized: ",
           root == Root::kGlobalHandles ? "global" : "eternal");
    Print(*p);
    PrintF("\n");
    ok_ = false;
  }
}
References v8::internal::compiler::end(), ok_, v8::internal::Print(), v8::internal::PrintF(), and serialized_.
Member Data Documentation
isolate_
Isolate* v8::internal::SerializedHandleChecker::isolate_ [private]
Definition at line 71 of file startup-serializer.h.
Referenced by CheckGlobalAndEternalHandles().
ok_
bool v8::internal::SerializedHandleChecker::ok_ = true [private]
Definition at line 73 of file startup-serializer.h.
Referenced by CheckGlobalAndEternalHandles(), and VisitRootPointers().
serialized_
std::unordered_set<Tagged<Object>, Object::Hasher> v8::internal::SerializedHandleChecker::serialized_ [private]
Definition at line 72 of file startup-serializer.h.
Referenced by AddToSet(), and VisitRootPointers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/startup-serializer.h
/mnt/V8SourceCode/src/snapshot/startup-serializer.cc