v8::internal::AstFunctionLiteralIdReindexer Class Reference
#include <ast-function-literal-id-reindexer.h>
Public Member Functions
AstFunctionLiteralIdReindexer (size_t stack_limit, int delta)
AstFunctionLiteralIdReindexer (const AstFunctionLiteralIdReindexer &)=delete
AstFunctionLiteralIdReindexer & operator= (const AstFunctionLiteralIdReindexer &)=delete
~AstFunctionLiteralIdReindexer ()
void Reindex (Expression *pattern)
void VisitFunctionLiteral (FunctionLiteral *lit)
void VisitClassLiteral (ClassLiteral *lit)
void VisitCall (Call *lit)
Private Member Functions
void CheckVisited (Expression *expr)
Private Attributes
int delta_
Additional Inherited Members
Detailed Description
Definition at line 19 of file ast-function-literal-id-reindexer.h.
Constructor & Destructor Documentation
AstFunctionLiteralIdReindexer() [1/2]
v8::internal::AstFunctionLiteralIdReindexer::AstFunctionLiteralIdReindexer (size_t stack_limit, int delta)
Definition at line 12 of file ast-function-literal-id-reindexer.cc.
    : AstTraversalVisitor(stack_limit), delta_(delta) {}
AstFunctionLiteralIdReindexer() [2/2]
v8::internal::AstFunctionLiteralIdReindexer::AstFunctionLiteralIdReindexer (const AstFunctionLiteralIdReindexer &) [delete]
 AstFunctionLiteralIdReindexer()
v8::internal::AstFunctionLiteralIdReindexer::~AstFunctionLiteralIdReindexer () [default]
Member Function Documentation
CheckVisited()
void v8::internal::AstFunctionLiteralIdReindexer::CheckVisited (Expression * expr) [inline], [private]
Definition at line 46 of file ast-function-literal-id-reindexer.h.
{}
Referenced by Reindex(), and VisitClassLiteral().
operator=()
AstFunctionLiteralIdReindexer& v8::internal::AstFunctionLiteralIdReindexer::operator= (const AstFunctionLiteralIdReindexer &) [delete]
Reindex()
void v8::internal::AstFunctionLiteralIdReindexer::Reindex (Expression * pattern)
Definition at line 18 of file ast-function-literal-id-reindexer.cc.
                                                               {
#ifdef DEBUG
  visited_.clear();
#endif
  Visit(pattern);
  CheckVisited(pattern);
}
References CheckVisited(), and v8::internal::AstVisitor< Subclass >::Visit().
Referenced by v8::internal::Parser::ReindexArrowFunctionFormalParameters(), and v8::internal::Parser::ReindexComputedMemberName().
VisitCall()
void v8::internal::AstFunctionLiteralIdReindexer::VisitCall (Call * lit)
Definition at line 34 of file ast-function-literal-id-reindexer.cc.
                                                        {
  AstTraversalVisitor::VisitCall(expr);
  if (expr->is_possibly_eval()) {
    expr->adjust_eval_scope_info_index(delta_);
  }
}
References v8::internal::Call::adjust_eval_scope_info_index(), delta_, and v8::internal::Call::is_possibly_eval().
VisitClassLiteral()
void v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral (ClassLiteral * lit)
Definition at line 41 of file ast-function-literal-id-reindexer.cc.
                                                                        {
  // Manually visit the class literal so that we can change the property walk.
  // This should be kept in-sync with AstTraversalVisitor::VisitClassLiteral.
  if (expr->extends() != nullptr) {
    Visit(expr->extends());
  }
  Visit(expr->constructor());
  if (expr->static_initializer() != nullptr) {
    Visit(expr->static_initializer());
  }
  if (expr->instance_members_initializer_function() != nullptr) {
    Visit(expr->instance_members_initializer_function());
  }
  ZonePtrList<ClassLiteral::Property>* private_members =
      expr->private_members();
  for (int i = 0; i < private_members->length(); ++i) {
    ClassLiteralProperty* prop = private_members->at(i);
    // Private fields have their key and value present in
    // instance_members_initializer_function, so they will
    // already have been visited.
    if (prop->kind() == ClassLiteralProperty::Kind::FIELD) {
      CheckVisited(prop->value());
    } else {
      Visit(prop->value());
    }
  }
  ZonePtrList<ClassLiteral::Property>* props = expr->public_members();
  for (int i = 0; i < props->length(); ++i) {
    ClassLiteralProperty* prop = props->at(i);
    // Public fields with computed names have their key
    // and value present in instance_members_initializer_function, so they will
    // already have been visited.
    if (prop->is_computed_name() &&
        prop->kind() == ClassLiteralProperty::Kind::FIELD) {
      if (!prop->key()->IsLiteral()) {
        CheckVisited(prop->key());
      }
      CheckVisited(prop->value());
    } else {
      if (!prop->key()->IsLiteral()) {
        Visit(prop->key());
      }
      Visit(prop->value());
    }
  }
}
References v8::internal::ZoneList< T >::at(), CheckVisited(), v8::internal::ClassLiteral::constructor(), v8::internal::ClassLiteral::extends(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ClassLiteral::instance_members_initializer_function(), v8::internal::LiteralProperty::is_computed_name(), v8::internal::LiteralProperty::key(), v8::internal::ClassLiteralProperty::kind(), v8::internal::ZoneList< T >::length(), v8::internal::ClassLiteral::private_members(), v8::internal::ClassLiteral::public_members(), v8::internal::ClassLiteral::static_initializer(), v8::internal::LiteralProperty::value(), and v8::internal::AstVisitor< Subclass >::Visit().
VisitFunctionLiteral()
void v8::internal::AstFunctionLiteralIdReindexer::VisitFunctionLiteral (FunctionLiteral * lit)
Definition at line 26 of file ast-function-literal-id-reindexer.cc.
                                                                             {
  // Make sure we're not already in the visited set.
  DCHECK(visited_.insert(lit).second);
  AstTraversalVisitor::VisitFunctionLiteral(lit);
  lit->set_function_literal_id(lit->function_literal_id() + delta_);
}
References v8::internal::DCHECK(), delta_, v8::internal::FunctionLiteral::function_literal_id(), and v8::internal::FunctionLiteral::set_function_literal_id().
Member Data Documentation
delta_
int v8::internal::AstFunctionLiteralIdReindexer::delta_ [private]
Definition at line 36 of file ast-function-literal-id-reindexer.h.
Referenced by VisitCall(), and VisitFunctionLiteral().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast-function-literal-id-reindexer.h
/mnt/V8SourceCode/src/ast/ast-function-literal-id-reindexer.cc