v8::internal::compiler::LoopFinderImpl Class Reference
Public Member Functions
LoopFinderImpl (TFGraph *graph, LoopTree *loop_tree, TickCounter *tick_counter, Zone *zone)
void Run ()
void Print ()
Private Member Functions
int num_nodes ()
bool PropagateBackwardMarks (Node *from, Node *to, int loop_filter)
bool SetBackwardMark (Node *to, int loop_num)
bool SetForwardMark (Node *to, int loop_num)
bool PropagateForwardMarks (Node *from, Node *to)
bool IsInLoop (Node *node, int loop_num)
void PropagateBackward ()
int CreateLoopInfo (Node *node)
void SetLoopMark (Node *node, int loop_num)
void SetLoopMarkForLoopHeader (Node *node, int loop_num)
void ResizeBackwardMarks ()
void ResizeForwardMarks ()
void PropagateForward ()
bool IsLoopHeaderNode (Node *node)
bool IsLoopExitNode (Node *node)
bool IsBackedge (Node *use, int index)
int LoopNum (Node *node)
NodeInfo & info (Node *node)
void Queue (Node *node)
void AddNodeToLoop (NodeInfo *node_info, TempLoopInfo *loop, int loop_num)
void FinishLoopTree ()
void FinishSingleLoop ()
void SerializeLoop (LoopTree::Loop *loop)
LoopTree::Loop * ConnectLoopTree (int loop_num)
void PrintLoop (LoopTree::Loop *loop)
Private Attributes
Zone * zone_
Node * end_
NodeDeque queue_
NodeMarker< bool > queued_
ZoneVector< NodeInfo > info_
ZoneVector< TempLoopInfo > loops_
ZoneVector< int > loop_num_
LoopTree * loop_tree_
int loops_found_
int width_
uint32_t * backward_
uint32_t * forward_
TickCounter *const tick_counter_
Detailed Description
Definition at line 60 of file loop-analysis.cc.
Constructor & Destructor Documentation
LoopFinderImpl()
v8::internal::compiler::LoopFinderImpl::LoopFinderImpl (TFGraph * graph, LoopTree * loop_tree, TickCounter * tick_counter, Zone * zone) [inline]
Definition at line 62 of file loop-analysis.cc.
      : zone_(zone),
        end_(graph->end()),
        queue_(zone),
        queued_(graph, 2),
        info_(graph->NodeCount(), {nullptr, nullptr, false}, zone),
        loops_(zone),
        loop_num_(graph->NodeCount(), -1, zone),
        loop_tree_(loop_tree),
        loops_found_(0),
        width_(0),
        backward_(nullptr),
        forward_(nullptr),
        tick_counter_(tick_counter) {}
Member Function Documentation
AddNodeToLoop()
void v8::internal::compiler::LoopFinderImpl::AddNodeToLoop (NodeInfo * node_info, TempLoopInfo * loop, int loop_num) [inline], [private]
Definition at line 374 of file loop-analysis.cc.
                                                                            {
    if (LoopNum(node_info->node) == loop_num) {
      if (IsLoopHeaderNode(node_info->node)) {
        node_info->next = loop->header_list;
        loop->header_list = node_info;
      } else {
        DCHECK(IsLoopExitNode(node_info->node));
        node_info->next = loop->exit_list;
        loop->exit_list = node_info;
      }
    } else {
      node_info->next = loop->body_list;
      loop->body_list = node_info;
    }
  }
References v8::internal::compiler::TempLoopInfo::body_list, v8::internal::DCHECK(), v8::internal::compiler::TempLoopInfo::exit_list, v8::internal::compiler::TempLoopInfo::header_list, IsLoopExitNode(), IsLoopHeaderNode(), LoopNum(), v8::internal::compiler::NodeInfo::next, and v8::internal::compiler::NodeInfo::node.
Referenced by FinishLoopTree(), and FinishSingleLoop().
ConnectLoopTree()
LoopTree::Loop* v8::internal::compiler::LoopFinderImpl::ConnectLoopTree (int loop_num) [inline], [private]
Definition at line 497 of file loop-analysis.cc.
                                              {
    TempLoopInfo& li = loops_[loop_num - 1];
    if (li.loop != nullptr) return li.loop;
    NodeInfo& ni = info(li.header);
    LoopTree::Loop* parent = nullptr;
    for (int i = 1; i <= loops_found_; i++) {
      if (i == loop_num) continue;
      if (IsInLoop(ni.node, i)) {
        // recursively create potential parent loops first.
        LoopTree::Loop* upper = ConnectLoopTree(i);
        if (parent == nullptr || upper->depth_ > parent->depth_) {
          parent = upper;
        }
      }
    }
    li.loop = &loop_tree_->all_loops_[loop_num - 1];
    loop_tree_->SetParent(parent, li.loop);
    return li.loop;
  }
References v8::internal::compiler::LoopTree::all_loops_, v8::internal::compiler::LoopTree::Loop::depth_, v8::internal::compiler::TempLoopInfo::header, info(), IsInLoop(), v8::internal::compiler::TempLoopInfo::loop, loop_tree_, loops_, loops_found_, v8::internal::compiler::NodeInfo::node, and v8::internal::compiler::LoopTree::SetParent().
Referenced by FinishLoopTree().
CreateLoopInfo()
int v8::internal::compiler::LoopFinderImpl::CreateLoopInfo (Node * node) [inline], [private]
Definition at line 249 of file loop-analysis.cc.
                                 {
    DCHECK_EQ(IrOpcode::kLoop, node->opcode());
    int loop_num = LoopNum(node);
    if (loop_num > 0) return loop_num;
    loop_num = ++loops_found_;
    if (INDEX(loop_num) >= width_) ResizeBackwardMarks();
    // Create a new loop.
    loops_.push_back({node, nullptr, nullptr, nullptr, nullptr});
    loop_tree_->NewLoop();
    SetLoopMarkForLoopHeader(node, loop_num);
    return loop_num;
  }
References DCHECK_EQ, INDEX, loop_tree_, LoopNum(), loops_, loops_found_, v8::internal::compiler::LoopTree::NewLoop(), v8::internal::compiler::Node::opcode(), ResizeBackwardMarks(), SetLoopMarkForLoopHeader(), and width_.
Referenced by PropagateBackward().
FinishLoopTree()
void v8::internal::compiler::LoopFinderImpl::FinishLoopTree () [inline], [private]
Definition at line 390 of file loop-analysis.cc.
                        {
    DCHECK(loops_found_ == static_cast<int>(loops_.size()));
    DCHECK(loops_found_ == static_cast<int>(loop_tree_->all_loops_.size()));
    // Degenerate cases.
    if (loops_found_ == 0) return;
    if (loops_found_ == 1) return FinishSingleLoop();
    for (int i = 1; i <= loops_found_; i++) ConnectLoopTree(i);
    size_t count = 0;
    // Place the node into the innermost nested loop of which it is a member.
    for (NodeInfo& ni : info_) {
      if (ni.node == nullptr) continue;
      TempLoopInfo* innermost = nullptr;
      int innermost_index = 0;
      int pos = ni.node->id() * width_;
      // Search the marks word by word.
      for (int i = 0; i < width_; i++) {
        uint32_t marks = backward_[pos + i] & forward_[pos + i];
        for (int j = 0; j < 32; j++) {
          if (marks & (1u << j)) {
            int loop_num = i * 32 + j;
            if (loop_num == 0) continue;
            TempLoopInfo* loop = &loops_[loop_num - 1];
            if (innermost == nullptr ||
                loop->loop->depth_ > innermost->loop->depth_) {
              innermost = loop;
              innermost_index = loop_num;
            }
          }
        }
      }
      if (innermost == nullptr) continue;
      // Return statements should never be found by forward or backward walk.
      CHECK(ni.node->opcode() != IrOpcode::kReturn);
      AddNodeToLoop(&ni, innermost, innermost_index);
      count++;
    }
    // Serialize the node lists for loops into the loop tree.
    loop_tree_->loop_nodes_.reserve(count);
    for (LoopTree::Loop* loop : loop_tree_->outer_loops_) {
      SerializeLoop(loop);
    }
  }
References AddNodeToLoop(), v8::internal::compiler::LoopTree::all_loops_, backward_, CHECK, ConnectLoopTree(), v8::internal::DCHECK(), v8::internal::compiler::LoopTree::Loop::depth_, FinishSingleLoop(), forward_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, info_, v8::internal::compiler::TempLoopInfo::loop, v8::internal::compiler::LoopTree::loop_nodes_, loop_tree_, loops_, loops_found_, v8::internal::compiler::LoopTree::outer_loops_, v8::internal::ZoneVector< T >::reserve(), SerializeLoop(), and width_.
Referenced by Run().
FinishSingleLoop()
void v8::internal::compiler::LoopFinderImpl::FinishSingleLoop () [inline], [private]
Definition at line 442 of file loop-analysis.cc.
                          {
    // Place nodes into the loop header and body.
    TempLoopInfo* li = &loops_[0];
    li->loop = &loop_tree_->all_loops_[0];
    loop_tree_->SetParent(nullptr, li->loop);
    size_t count = 0;
    for (NodeInfo& ni : info_) {
      if (ni.node == nullptr || !IsInLoop(ni.node, 1)) continue;
      // Return statements should never be found by forward or backward walk.
      CHECK(ni.node->opcode() != IrOpcode::kReturn);
      AddNodeToLoop(&ni, li, 1);
      count++;
    }
    // Serialize the node lists for the loop into the loop tree.
    loop_tree_->loop_nodes_.reserve(count);
    SerializeLoop(li->loop);
  }
References AddNodeToLoop(), v8::internal::compiler::LoopTree::all_loops_, CHECK, info_, IsInLoop(), v8::internal::compiler::TempLoopInfo::loop, v8::internal::compiler::LoopTree::loop_nodes_, loop_tree_, loops_, v8::internal::ZoneVector< T >::reserve(), SerializeLoop(), and v8::internal::compiler::LoopTree::SetParent().
Referenced by FinishLoopTree().
info()
NodeInfo& v8::internal::compiler::LoopFinderImpl::info (Node * node) [inline], [private]
Definition at line 361 of file loop-analysis.cc.
                             {
    NodeInfo& i = info_[node->id()];
    if (i.node == nullptr) i.node = node;
    return i;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), and info_.
Referenced by ConnectLoopTree(), PropagateBackward(), and SetLoopMark().
IsBackedge()
bool v8::internal::compiler::LoopFinderImpl::IsBackedge (Node * use, int index) [inline], [private]
Definition at line 347 of file loop-analysis.cc.
                                        {
    if (LoopNum(use) <= 0) return false;
    if (NodeProperties::IsPhi(use)) {
      return index != NodeProperties::FirstControlIndex(use) &&
             index != kAssumedLoopEntryIndex;
    } else if (use->opcode() == IrOpcode::kLoop) {
      return index != kAssumedLoopEntryIndex;
    }
    DCHECK(IsLoopExitNode(use));
    return false;
  }
References v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::index, IsLoopExitNode(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::kAssumedLoopEntryIndex, LoopNum(), and use().
Referenced by PropagateBackward(), and PropagateForward().
IsInLoop()
bool v8::internal::compiler::LoopFinderImpl::IsInLoop (Node * node, int loop_num) [inline], [private]
Definition at line 185 of file loop-analysis.cc.
                                          {
    int offset = node->id() * width_ + INDEX(loop_num);
    return backward_[offset] & forward_[offset] & BIT(loop_num);
  }
References backward_, BIT, forward_, v8::internal::compiler::Node::id(), INDEX, and width_.
Referenced by ConnectLoopTree(), and FinishSingleLoop().
IsLoopExitNode()
bool v8::internal::compiler::LoopFinderImpl::IsLoopExitNode (Node * node) [inline], [private]
Definition at line 341 of file loop-analysis.cc.
                                  {
    return node->opcode() == IrOpcode::kLoopExit ||
           node->opcode() == IrOpcode::kLoopExitValue ||
           node->opcode() == IrOpcode::kLoopExitEffect;
  }
References v8::internal::compiler::Node::opcode().
Referenced by AddNodeToLoop(), and IsBackedge().
IsLoopHeaderNode()
bool v8::internal::compiler::LoopFinderImpl::IsLoopHeaderNode (Node * node) [inline], [private]
Definition at line 337 of file loop-analysis.cc.
                                    {
    return node->opcode() == IrOpcode::kLoop || NodeProperties::IsPhi(node);
  }
References v8::internal::compiler::NodeProperties::IsPhi(), and v8::internal::compiler::Node::opcode().
Referenced by AddNodeToLoop().
LoopNum()
int v8::internal::compiler::LoopFinderImpl::LoopNum (Node * node) [inline], [private]
Definition at line 359 of file loop-analysis.cc.
{ return loop_tree_->node_to_loop_num_[node->id()]; }
References v8::internal::compiler::Node::id(), loop_tree_, and v8::internal::compiler::LoopTree::node_to_loop_num_.
Referenced by AddNodeToLoop(), CreateLoopInfo(), IsBackedge(), and PropagateForward().
num_nodes()
int v8::internal::compiler::LoopFinderImpl::num_nodes () [inline], [private]
Definition at line 131 of file loop-analysis.cc.
                  {
    return static_cast<int>(loop_tree_->node_to_loop_num_.size());
  }
References loop_tree_, v8::internal::compiler::LoopTree::node_to_loop_num_, and v8::internal::ZoneVector< T >::size().
Referenced by ResizeBackwardMarks(), and ResizeForwardMarks().
Print()
void v8::internal::compiler::LoopFinderImpl::Print () [inline]
Definition at line 84 of file loop-analysis.cc.
               {
    // Print out the results.
    for (NodeInfo& ni : info_) {
      if (ni.node == nullptr) continue;
      for (int i = 1; i <= loops_found_; i++) {
        int index = ni.node->id() * width_ + INDEX(i);
        bool marked_forward = forward_[index] & BIT(i);
        bool marked_backward = backward_[index] & BIT(i);
        if (marked_forward && marked_backward) {
          PrintF("X");
        } else if (marked_forward) {
          PrintF(">");
        } else if (marked_backward) {
          PrintF("<");
        } else {
          PrintF(" ");
        }
      }
      PrintF(" #%d:%s\n", ni.node->id(), ni.node->op()->mnemonic());
    }
    int i = 0;
    for (TempLoopInfo& li : loops_) {
      PrintF("Loop %d headed at #%d\n", i, li.header->id());
      i++;
    }
    for (LoopTree::Loop* loop : loop_tree_->outer_loops_) {
      PrintLoop(loop);
    }
  }
References backward_, BIT, forward_, INDEX, v8::internal::index, info_, loop_tree_, loops_, loops_found_, v8::internal::compiler::LoopTree::outer_loops_, v8::internal::PrintF(), PrintLoop(), and width_.
PrintLoop()
void v8::internal::compiler::LoopFinderImpl::PrintLoop (LoopTree::Loop * loop) [inline], [private]
Definition at line 518 of file loop-analysis.cc.
                                     {
    for (int i = 0; i < loop->depth_; i++) PrintF(" ");
    PrintF("Loop depth = %d ", loop->depth_);
    int i = loop->header_start_;
    while (i < loop->body_start_) {
      PrintF(" H#%d", loop_tree_->loop_nodes_[i++]->id());
    }
    while (i < loop->exits_start_) {
      PrintF(" B#%d", loop_tree_->loop_nodes_[i++]->id());
    }
    while (i < loop->exits_end_) {
      PrintF(" E#%d", loop_tree_->loop_nodes_[i++]->id());
    }
    PrintF("\n");
    for (LoopTree::Loop* child : loop->children_) PrintLoop(child);
  }
References v8::internal::compiler::LoopTree::Loop::children_, v8::internal::compiler::LoopTree::Loop::depth_, v8::internal::compiler::LoopTree::Loop::header_start_, v8::internal::compiler::LoopTree::loop_nodes_, loop_tree_, and v8::internal::PrintF().
Referenced by Print().
PropagateBackward()
void v8::internal::compiler::LoopFinderImpl::PropagateBackward () [inline], [private]
Definition at line 191 of file loop-analysis.cc.
                           {
    ResizeBackwardMarks();
    SetBackwardMark(end_, 0);
    Queue(end_);
    while (!queue_.empty()) {
      tick_counter_->TickAndMaybeEnterSafepoint();
      Node* node = queue_.front();
      info(node).backwards_visited = true;
      queue_.pop_front();
      queued_.Set(node, false);
      int loop_num = -1;
      // Setup loop headers first.
      if (node->opcode() == IrOpcode::kLoop) {
        // found the loop node first.
        loop_num = CreateLoopInfo(node);
      } else if (NodeProperties::IsPhi(node)) {
        // found a phi first.
        Node* merge = node->InputAt(node->InputCount() - 1);
        if (merge->opcode() == IrOpcode::kLoop) {
          loop_num = CreateLoopInfo(merge);
        }
      } else if (node->opcode() == IrOpcode::kLoopExit) {
        // Intentionally ignore return value. Loop exit node marks
        // are propagated normally.
        CreateLoopInfo(node->InputAt(1));
      } else if (node->opcode() == IrOpcode::kLoopExitValue ||
                 node->opcode() == IrOpcode::kLoopExitEffect) {
        Node* loop_exit = NodeProperties::GetControlInput(node);
        // Intentionally ignore return value. Loop exit node marks
        // are propagated normally.
        CreateLoopInfo(loop_exit->InputAt(1));
      }
      // Propagate marks backwards from this node.
      for (int i = 0; i < node->InputCount(); i++) {
        Node* input = node->InputAt(i);
        if (IsBackedge(node, i)) {
          // Only propagate the loop mark on backedges.
          if (SetBackwardMark(input, loop_num) ||
              !info(input).backwards_visited) {
            Queue(input);
          }
        } else {
          // Entry or normal edge. Propagate all marks except loop_num.
          // TODO(manoskouk): Add test that needs backwards_visited to function
          // correctly, probably using wasm loop unrolling when it is available.
          if (PropagateBackwardMarks(node, input, loop_num) ||
              !info(input).backwards_visited) {
            Queue(input);
          }
        }
      }
    }
  }
References v8::internal::compiler::NodeInfo::backwards_visited, CreateLoopInfo(), end_, v8::internal::compiler::NodeProperties::GetControlInput(), info(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), IsBackedge(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::Node::opcode(), PropagateBackwardMarks(), Queue(), queue_, queued_, ResizeBackwardMarks(), v8::internal::compiler::NodeMarker< State >::Set(), SetBackwardMark(), tick_counter_, and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
Referenced by Run().
PropagateBackwardMarks()
bool v8::internal::compiler::LoopFinderImpl::PropagateBackwardMarks (Node * from, Node * to, int loop_filter) [inline], [private]
Definition at line 136 of file loop-analysis.cc.
                                                                     {
    if (from == to) return false;
    uint32_t* fp = &backward_[from->id() * width_];
    uint32_t* tp = &backward_[to->id() * width_];
    bool change = false;
    for (int i = 0; i < width_; i++) {
      uint32_t mask = i == INDEX(loop_filter) ? ~BIT(loop_filter) : 0xFFFFFFFF;
      uint32_t prev = tp[i];
      uint32_t next = prev | (fp[i] & mask);
      tp[i] = next;
      if (!change && (prev != next)) change = true;
    }
    return change;
  }
References backward_, BIT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), INDEX, and width_.
Referenced by PropagateBackward().
PropagateForward()
void v8::internal::compiler::LoopFinderImpl::PropagateForward () [inline], [private]
Definition at line 316 of file loop-analysis.cc.
                          {
    ResizeForwardMarks();
    for (TempLoopInfo& li : loops_) {
      SetForwardMark(li.header, LoopNum(li.header));
      Queue(li.header);
    }
    // Propagate forward on paths that were backward reachable from backedges.
    while (!queue_.empty()) {
      tick_counter_->TickAndMaybeEnterSafepoint();
      Node* node = queue_.front();
      queue_.pop_front();
      queued_.Set(node, false);
      for (Edge edge : node->use_edges()) {
        Node* use = edge.from();
        if (!IsBackedge(use, edge.index())) {
          if (PropagateForwardMarks(node, use)) Queue(use);
        }
      }
    }
  }
References IsBackedge(), LoopNum(), loops_, PropagateForwardMarks(), Queue(), queue_, queued_, ResizeForwardMarks(), v8::internal::compiler::NodeMarker< State >::Set(), SetForwardMark(), tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), use(), and v8::internal::compiler::Node::use_edges().
Referenced by Run().
PropagateForwardMarks()
bool v8::internal::compiler::LoopFinderImpl::PropagateForwardMarks (Node * from, Node * to) [inline], [private]
Definition at line 170 of file loop-analysis.cc.
                                                   {
    if (from == to) return false;
    bool change = false;
    int findex = from->id() * width_;
    int tindex = to->id() * width_;
    for (int i = 0; i < width_; i++) {
      uint32_t marks = backward_[tindex + i] & forward_[findex + i];
      uint32_t prev = forward_[tindex + i];
      uint32_t next = prev | marks;
      forward_[tindex + i] = next;
      if (!change && (prev != next)) change = true;
    }
    return change;
  }
References backward_, forward_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), and width_.
Referenced by PropagateForward().
Queue()
void v8::internal::compiler::LoopFinderImpl::Queue (Node * node) [inline], [private]
Definition at line 367 of file loop-analysis.cc.
                         {
    if (!queued_.Get(node)) {
      queue_.push_back(node);
      queued_.Set(node, true);
    }
  }
References v8::internal::compiler::NodeMarker< State >::Get(), queue_, queued_, and v8::internal::compiler::NodeMarker< State >::Set().
Referenced by PropagateBackward(), and PropagateForward().
ResizeBackwardMarks()
void v8::internal::compiler::LoopFinderImpl::ResizeBackwardMarks () [inline], [private]
Definition at line 293 of file loop-analysis.cc.
                             {
    int new_width = width_ + 1;
    int max = num_nodes();
    uint32_t* new_backward = zone_->AllocateArray<uint32_t>(new_width * max);
    memset(new_backward, 0, new_width * max * sizeof(uint32_t));
    if (width_ > 0) { // copy old matrix data.
      for (int i = 0; i < max; i++) {
        uint32_t* np = &new_backward[i * new_width];
        uint32_t* op = &backward_[i * width_];
        for (int j = 0; j < width_; j++) np[j] = op[j];
      }
    }
    width_ = new_width;
    backward_ = new_backward;
  }
References v8::internal::Zone::AllocateArray(), backward_, num_nodes(), width_, and zone_.
Referenced by CreateLoopInfo(), and PropagateBackward().
ResizeForwardMarks()
void v8::internal::compiler::LoopFinderImpl::ResizeForwardMarks () [inline], [private]
Definition at line 309 of file loop-analysis.cc.
                            {
    int max = num_nodes();
    forward_ = zone_->AllocateArray<uint32_t>(width_ * max);
    memset(forward_, 0, width_ * max * sizeof(uint32_t));
  }
References v8::internal::Zone::AllocateArray(), forward_, num_nodes(), width_, and zone_.
Referenced by PropagateForward().
Run()
void v8::internal::compiler::LoopFinderImpl::Run () [inline]
Definition at line 78 of file loop-analysis.cc.
             {
    PropagateBackward();
    PropagateForward();
    FinishLoopTree();
  }
References FinishLoopTree(), PropagateBackward(), and PropagateForward().
SerializeLoop()
void v8::internal::compiler::LoopFinderImpl::SerializeLoop (LoopTree::Loop * loop) [inline], [private]
Definition at line 465 of file loop-analysis.cc.
                                         {
    int loop_num = loop_tree_->LoopNum(loop);
    TempLoopInfo& li = loops_[loop_num - 1];
    // Serialize the header.
    loop->header_start_ = static_cast<int>(loop_tree_->loop_nodes_.size());
    for (NodeInfo* ni = li.header_list; ni != nullptr; ni = ni->next) {
      loop_tree_->loop_nodes_.push_back(ni->node);
      loop_tree_->node_to_loop_num_[ni->node->id()] = loop_num;
    }
    // Serialize the body.
    loop->body_start_ = static_cast<int>(loop_tree_->loop_nodes_.size());
    for (NodeInfo* ni = li.body_list; ni != nullptr; ni = ni->next) {
      loop_tree_->loop_nodes_.push_back(ni->node);
      loop_tree_->node_to_loop_num_[ni->node->id()] = loop_num;
    }
    // Serialize nested loops.
    for (LoopTree::Loop* child : loop->children_) SerializeLoop(child);
    // Serialize the exits.
    loop->exits_start_ = static_cast<int>(loop_tree_->loop_nodes_.size());
    for (NodeInfo* ni = li.exit_list; ni != nullptr; ni = ni->next) {
      loop_tree_->loop_nodes_.push_back(ni->node);
      loop_tree_->node_to_loop_num_[ni->node->id()] = loop_num;
    }
    loop->exits_end_ = static_cast<int>(loop_tree_->loop_nodes_.size());
  }
References v8::internal::compiler::TempLoopInfo::body_list, v8::internal::compiler::LoopTree::Loop::body_start_, v8::internal::compiler::LoopTree::Loop::children_, v8::internal::compiler::TempLoopInfo::exit_list, v8::internal::compiler::LoopTree::Loop::exits_end_, v8::internal::compiler::LoopTree::Loop::exits_start_, v8::internal::compiler::TempLoopInfo::header_list, v8::internal::compiler::LoopTree::Loop::header_start_, v8::internal::compiler::LoopTree::loop_nodes_, loop_tree_, v8::internal::compiler::LoopTree::LoopNum(), loops_, v8::internal::compiler::NodeInfo::next, v8::internal::compiler::LoopTree::node_to_loop_num_, v8::internal::ZoneVector< T >::push_back(), and v8::internal::ZoneVector< T >::size().
Referenced by FinishLoopTree(), and FinishSingleLoop().
SetBackwardMark()
bool v8::internal::compiler::LoopFinderImpl::SetBackwardMark (Node * to, int loop_num) [inline], [private]
Definition at line 152 of file loop-analysis.cc.
                                               {
    uint32_t* tp = &backward_[to->id() * width_ + INDEX(loop_num)];
    uint32_t prev = tp[0];
    uint32_t next = prev | BIT(loop_num);
    tp[0] = next;
    return next != prev;
  }
References backward_, BIT, v8::internal::compiler::Node::id(), INDEX, and width_.
Referenced by PropagateBackward(), and SetLoopMark().
SetForwardMark()
bool v8::internal::compiler::LoopFinderImpl::SetForwardMark (Node * to, int loop_num) [inline], [private]
Definition at line 161 of file loop-analysis.cc.
                                              {
    uint32_t* tp = &forward_[to->id() * width_ + INDEX(loop_num)];
    uint32_t prev = tp[0];
    uint32_t next = prev | BIT(loop_num);
    tp[0] = next;
    return next != prev;
  }
References BIT, forward_, v8::internal::compiler::Node::id(), INDEX, and width_.
Referenced by PropagateForward().
SetLoopMark()
void v8::internal::compiler::LoopFinderImpl::SetLoopMark (Node * node, int loop_num) [inline], [private]
Definition at line 264 of file loop-analysis.cc.
                                             {
    info(node); // create the NodeInfo
    SetBackwardMark(node, loop_num);
    loop_tree_->node_to_loop_num_[node->id()] = loop_num;
  }
References v8::internal::compiler::Node::id(), info(), loop_tree_, v8::internal::compiler::LoopTree::node_to_loop_num_, and SetBackwardMark().
Referenced by SetLoopMarkForLoopHeader().
SetLoopMarkForLoopHeader()
void v8::internal::compiler::LoopFinderImpl::SetLoopMarkForLoopHeader (Node * node, int loop_num) [inline], [private]
Definition at line 270 of file loop-analysis.cc.
                                                          {
    DCHECK_EQ(IrOpcode::kLoop, node->opcode());
    SetLoopMark(node, loop_num);
    for (Node* use : node->uses()) {
      if (NodeProperties::IsPhi(use)) {
        SetLoopMark(use, loop_num);
      }
      // Do not keep the loop alive if it does not have any backedges.
      if (node->InputCount() <= 1) continue;
      if (use->opcode() == IrOpcode::kLoopExit) {
        SetLoopMark(use, loop_num);
        for (Node* exit_use : use->uses()) {
          if (exit_use->opcode() == IrOpcode::kLoopExitValue ||
              exit_use->opcode() == IrOpcode::kLoopExitEffect) {
            SetLoopMark(exit_use, loop_num);
          }
        }
      }
    }
  }
References DCHECK_EQ, v8::internal::compiler::Node::InputCount(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::Node::opcode(), SetLoopMark(), use(), and v8::internal::compiler::Node::uses().
Referenced by CreateLoopInfo().
Member Data Documentation
backward_
uint32_t* v8::internal::compiler::LoopFinderImpl::backward_ [private]
Definition at line 127 of file loop-analysis.cc.
Referenced by FinishLoopTree(), IsInLoop(), Print(), PropagateBackwardMarks(), PropagateForwardMarks(), ResizeBackwardMarks(), and SetBackwardMark().
end_
Node* v8::internal::compiler::LoopFinderImpl::end_ [private]
Definition at line 118 of file loop-analysis.cc.
Referenced by PropagateBackward().
forward_
uint32_t* v8::internal::compiler::LoopFinderImpl::forward_ [private]
Definition at line 128 of file loop-analysis.cc.
Referenced by FinishLoopTree(), IsInLoop(), Print(), PropagateForwardMarks(), ResizeForwardMarks(), and SetForwardMark().
info_
ZoneVector<NodeInfo> v8::internal::compiler::LoopFinderImpl::info_ [private]
Definition at line 121 of file loop-analysis.cc.
Referenced by FinishLoopTree(), FinishSingleLoop(), info(), and Print().
loop_num_
ZoneVector<int> v8::internal::compiler::LoopFinderImpl::loop_num_ [private]
Definition at line 123 of file loop-analysis.cc.
loop_tree_
LoopTree* v8::internal::compiler::LoopFinderImpl::loop_tree_ [private]
Definition at line 124 of file loop-analysis.cc.
Referenced by ConnectLoopTree(), CreateLoopInfo(), FinishLoopTree(), FinishSingleLoop(), LoopNum(), num_nodes(), Print(), PrintLoop(), SerializeLoop(), and SetLoopMark().
loops_
ZoneVector<TempLoopInfo> v8::internal::compiler::LoopFinderImpl::loops_ [private]
Definition at line 122 of file loop-analysis.cc.
Referenced by ConnectLoopTree(), CreateLoopInfo(), FinishLoopTree(), FinishSingleLoop(), Print(), PropagateForward(), and SerializeLoop().
loops_found_
int v8::internal::compiler::LoopFinderImpl::loops_found_ [private]
Definition at line 125 of file loop-analysis.cc.
Referenced by ConnectLoopTree(), CreateLoopInfo(), FinishLoopTree(), and Print().
queue_
NodeDeque v8::internal::compiler::LoopFinderImpl::queue_ [private]
Definition at line 119 of file loop-analysis.cc.
Referenced by PropagateBackward(), PropagateForward(), and Queue().
queued_
NodeMarker<bool> v8::internal::compiler::LoopFinderImpl::queued_ [private]
Definition at line 120 of file loop-analysis.cc.
Referenced by PropagateBackward(), PropagateForward(), and Queue().
tick_counter_
TickCounter* const v8::internal::compiler::LoopFinderImpl::tick_counter_ [private]
Definition at line 129 of file loop-analysis.cc.
Referenced by PropagateBackward(), and PropagateForward().
width_
int v8::internal::compiler::LoopFinderImpl::width_ [private]
Definition at line 126 of file loop-analysis.cc.
Referenced by CreateLoopInfo(), FinishLoopTree(), IsInLoop(), Print(), PropagateBackwardMarks(), PropagateForwardMarks(), ResizeBackwardMarks(), ResizeForwardMarks(), SetBackwardMark(), and SetForwardMark().
zone_
Zone* v8::internal::compiler::LoopFinderImpl::zone_ [private]
Definition at line 117 of file loop-analysis.cc.
Referenced by ResizeBackwardMarks(), and ResizeForwardMarks().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/loop-analysis.cc