v8::internal::compiler::UseInfo Class Reference
#include <use-info.h>
Public Member Functions
UseInfo (MachineRepresentation representation, Truncation truncation, TypeCheckKind type_check=TypeCheckKind::kNone, const FeedbackSource &feedback=FeedbackSource())
MachineRepresentation representation () const
Truncation truncation () const
TypeCheckKind type_check () const
CheckForMinusZeroMode minus_zero_check () const
const FeedbackSource & feedback () const
Static Public Member Functions
static UseInfo TruncatingWord32 ()
static UseInfo TruncatingWord64 ()
static UseInfo CheckedBigIntTruncatingWord64 (const FeedbackSource &feedback)
static UseInfo CheckedBigInt64AsWord64 (const FeedbackSource &feedback)
static UseInfo Word64 (IdentifyZeros identify_zeros=kDistinguishZeros)
static UseInfo Word ()
static UseInfo Bool ()
static UseInfo Float32 ()
static UseInfo Float16RawBits ()
static UseInfo Float64 ()
static UseInfo TruncatingFloat64 (IdentifyZeros identify_zeros=kDistinguishZeros)
static UseInfo TruncatingFloat16RawBits (IdentifyZeros identify_zeros=kDistinguishZeros)
static UseInfo CheckedSafeIntTruncatingWord32 (const FeedbackSource &feedback)
static UseInfo CheckedSafeIntAsWord64 (const FeedbackSource &feedback)
static UseInfo TruncatingFloat64OrUndefined (IdentifyZeros identify_zeros=kDistinguishZeros)
static UseInfo AnyTagged ()
static UseInfo TaggedSigned ()
static UseInfo TaggedPointer ()
static UseInfo CheckedTaggedAsArrayIndex (const FeedbackSource &feedback)
static UseInfo CheckedHeapObjectAsTaggedPointer (const FeedbackSource &feedback)
static UseInfo CheckedBigIntAsTaggedPointer (const FeedbackSource &feedback)
static UseInfo CheckedSignedSmallAsTaggedSigned (const FeedbackSource &feedback, IdentifyZeros identify_zeros=kDistinguishZeros)
static UseInfo CheckedSignedSmallAsWord32 (IdentifyZeros identify_zeros, const FeedbackSource &feedback)
static UseInfo CheckedSigned32AsWord32 (IdentifyZeros identify_zeros, const FeedbackSource &feedback)
static UseInfo CheckedSigned64AsWord64 (IdentifyZeros identify_zeros, const FeedbackSource &feedback)
static UseInfo CheckedNumberAsFloat64 (IdentifyZeros identify_zeros, const FeedbackSource &feedback)
static UseInfo CheckedNumberAsWord32 (const FeedbackSource &feedback)
static UseInfo CheckedNumberOrBooleanAsFloat64 (IdentifyZeros identify_zeros, const FeedbackSource &feedback)
static UseInfo CheckedNumberOrOddballAsFloat64 (IdentifyZeros identify_zeros, const FeedbackSource &feedback)
static UseInfo CheckedNumberOrOddballAsWord32 (const FeedbackSource &feedback)
static UseInfo Any ()
static UseInfo AnyTruncatingToBool ()
static UseInfo None ()
Private Attributes
MachineRepresentation representation_
Truncation truncation_
TypeCheckKind type_check_
FeedbackSource feedback_
Detailed Description
Definition at line 214 of file use-info.h.
Constructor & Destructor Documentation
UseInfo()
v8::internal::compiler::UseInfo::UseInfo (MachineRepresentation representation, Truncation truncation, TypeCheckKind type_check = TypeCheckKind::kNone, const FeedbackSource & feedback = FeedbackSource()) [inline]
Definition at line 216 of file use-info.h.
      : representation_(representation),
        truncation_(truncation),
        type_check_(type_check),
        feedback_(feedback) {}
Referenced by Any(), AnyTagged(), AnyTruncatingToBool(), Bool(), CheckedBigInt64AsWord64(), CheckedBigIntAsTaggedPointer(), CheckedBigIntTruncatingWord64(), CheckedHeapObjectAsTaggedPointer(), CheckedNumberAsFloat64(), CheckedNumberAsWord32(), CheckedNumberOrBooleanAsFloat64(), CheckedNumberOrOddballAsFloat64(), CheckedNumberOrOddballAsWord32(), CheckedSafeIntAsWord64(), CheckedSafeIntTruncatingWord32(), CheckedSigned32AsWord32(), CheckedSigned64AsWord64(), CheckedSignedSmallAsTaggedSigned(), CheckedSignedSmallAsWord32(), CheckedTaggedAsArrayIndex(), Float16RawBits(), Float32(), Float64(), None(), TaggedPointer(), TaggedSigned(), TruncatingFloat16RawBits(), TruncatingFloat64(), TruncatingFloat64OrUndefined(), TruncatingWord32(), TruncatingWord64(), Word(), and Word64().
Member Function Documentation
Any()
static UseInfo v8::internal::compiler::UseInfo::Any () [inline], [static]
Definition at line 371 of file use-info.h.
                       {
    return UseInfo(MachineRepresentation::kNone, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kNone, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), v8::internal::compiler::RepresentationSelector::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
AnyTagged()
static UseInfo v8::internal::compiler::UseInfo::AnyTagged () [inline], [static]
Definition at line 290 of file use-info.h.
                             {
    return UseInfo(MachineRepresentation::kTagged, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kTagged, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::UseInfoForBasePointer(), v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument(), v8::internal::compiler::RepresentationSelector::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitCheck(), v8::internal::compiler::RepresentationSelector::VisitFastApiCall(), v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitInputs(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectIs(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), v8::internal::compiler::RepresentationSelector::VisitReturn(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
AnyTruncatingToBool()
static UseInfo v8::internal::compiler::UseInfo::AnyTruncatingToBool () [inline], [static]
Definition at line 374 of file use-info.h.
                                       {
    return UseInfo(MachineRepresentation::kNone, Truncation::Bool());
  }
References v8::internal::compiler::Truncation::Bool(), v8::internal::kNone, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Bool()
static UseInfo v8::internal::compiler::UseInfo::Bool () [inline], [static]
Definition at line 250 of file use-info.h.
                        {
    return UseInfo(MachineRepresentation::kBit, Truncation::Bool());
  }
References v8::internal::compiler::Truncation::Bool(), v8::internal::kBit, and UseInfo().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitSelect().
CheckedBigInt64AsWord64()
static UseInfo v8::internal::compiler::UseInfo::CheckedBigInt64AsWord64 (const FeedbackSource & feedback) [inline], [static]
Definition at line 238 of file use-info.h.
                                                                         {
    DCHECK(Is64());
    return UseInfo(MachineRepresentation::kWord64, Truncation::Any(),
                   TypeCheckKind::kBigInt64, feedback);
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::DCHECK(), feedback(), v8::internal::Is64(), v8::internal::compiler::kBigInt64, v8::internal::kWord64, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedBigIntAsTaggedPointer()
static UseInfo v8::internal::compiler::UseInfo::CheckedBigIntAsTaggedPointer (const FeedbackSource & feedback) [inline], [static]
Definition at line 312 of file use-info.h.
                                                                              {
    return UseInfo(MachineRepresentation::kTaggedPointer, Truncation::Any(),
                   TypeCheckKind::kBigInt, feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kBigInt, v8::internal::kTaggedPointer, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedBigIntTruncatingWord64()
static UseInfo v8::internal::compiler::UseInfo::CheckedBigIntTruncatingWord64 (const FeedbackSource & feedback) [inline], [static]
Definition at line 230 of file use-info.h.
                                                                               {
    DCHECK(Is64());
    // Note that Trunction::Word64() can safely use kIdentifyZero, because
    // TypeCheckKind::kBigInt will make sure we deopt for anything other than
    // type BigInt anyway.
    return UseInfo(MachineRepresentation::kWord64, Truncation::Word64(),
                   TypeCheckKind::kBigInt, feedback);
  }
References v8::internal::DCHECK(), feedback(), v8::internal::Is64(), v8::internal::compiler::kBigInt, v8::internal::kWord64, UseInfo(), and v8::internal::compiler::Truncation::Word64().
Referenced by v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument(), and v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedHeapObjectAsTaggedPointer()
static UseInfo v8::internal::compiler::UseInfo::CheckedHeapObjectAsTaggedPointer (const FeedbackSource & feedback) [inline], [static]
Definition at line 306 of file use-info.h.
                                      {
    return UseInfo(MachineRepresentation::kTaggedPointer, Truncation::Any(),
                   TypeCheckKind::kHeapObject, feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kHeapObject, v8::internal::kTaggedPointer, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitCheck(), and v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedNumberAsFloat64()
static UseInfo v8::internal::compiler::UseInfo::CheckedNumberAsFloat64 (IdentifyZeros identify_zeros, const FeedbackSource & feedback) [inline], [static]
Definition at line 342 of file use-info.h.
                                                                        {
    return UseInfo(MachineRepresentation::kFloat64,
                   Truncation::Any(identify_zeros), TypeCheckKind::kNumber,
                   feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::kFloat64, v8::internal::compiler::kNumber, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsFloat64FromHint(), and v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument().
CheckedNumberAsWord32()
static UseInfo v8::internal::compiler::UseInfo::CheckedNumberAsWord32 (const FeedbackSource & feedback) [inline], [static]
Definition at line 348 of file use-info.h.
                                                                       {
    return UseInfo(MachineRepresentation::kWord32, Truncation::Word32(),
                   TypeCheckKind::kNumber, feedback);
  }
References feedback(), v8::internal::compiler::kNumber, v8::internal::kWord32, UseInfo(), and v8::internal::compiler::Truncation::Word32().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint(), and v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument().
CheckedNumberOrBooleanAsFloat64()
static UseInfo v8::internal::compiler::UseInfo::CheckedNumberOrBooleanAsFloat64 (IdentifyZeros identify_zeros, const FeedbackSource & feedback) [inline], [static]
Definition at line 352 of file use-info.h.
                                                                    {
    return UseInfo(MachineRepresentation::kFloat64,
                   Truncation::Any(identify_zeros),
                   TypeCheckKind::kNumberOrBoolean, feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::kFloat64, v8::internal::compiler::kNumberOrBoolean, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsFloat64FromHint().
CheckedNumberOrOddballAsFloat64()
static UseInfo v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsFloat64 (IdentifyZeros identify_zeros, const FeedbackSource & feedback) [inline], [static]
Definition at line 358 of file use-info.h.
                                                                    {
    return UseInfo(MachineRepresentation::kFloat64,
                   Truncation::Any(identify_zeros),
                   TypeCheckKind::kNumberOrOddball, feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::kFloat64, v8::internal::compiler::kNumberOrOddball, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsFloat64FromHint(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp(), and v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus().
CheckedNumberOrOddballAsWord32()
static UseInfo v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsWord32 (const FeedbackSource & feedback) [inline], [static]
Definition at line 364 of file use-info.h.
                                      {
    return UseInfo(MachineRepresentation::kWord32, Truncation::Word32(),
                   TypeCheckKind::kNumberOrOddball, feedback);
  }
References feedback(), v8::internal::compiler::kNumberOrOddball, v8::internal::kWord32, UseInfo(), and v8::internal::compiler::Truncation::Word32().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint().
CheckedSafeIntAsWord64()
static UseInfo v8::internal::compiler::UseInfo::CheckedSafeIntAsWord64 (const FeedbackSource & feedback) [inline], [static]
Definition at line 279 of file use-info.h.
                                                                        {
    DCHECK(Is64());
    return UseInfo(MachineRepresentation::kWord64,
                   Truncation::Any(kDistinguishZeros, true),
                   TypeCheckKind::kAdditiveSafeInteger, feedback);
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::DCHECK(), feedback(), v8::internal::Is64(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kDistinguishZeros, v8::internal::kWord64, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp().
CheckedSafeIntTruncatingWord32()
static UseInfo v8::internal::compiler::UseInfo::CheckedSafeIntTruncatingWord32 (const FeedbackSource & feedback) [inline], [static]
Definition at line 272 of file use-info.h.
                                      {
    DCHECK(Is64());
    return UseInfo(MachineRepresentation::kWord32,
                   Truncation::Word32WithSafeIntCheck(),
                   TypeCheckKind::kAdditiveSafeInteger, feedback);
  }
References v8::internal::DCHECK(), feedback(), v8::internal::Is64(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::kWord32, UseInfo(), and v8::internal::compiler::Truncation::Word32WithSafeIntCheck().
Referenced by v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp().
CheckedSigned32AsWord32()
static UseInfo v8::internal::compiler::UseInfo::CheckedSigned32AsWord32 (IdentifyZeros identify_zeros, const FeedbackSource & feedback) [inline], [static]
Definition at line 330 of file use-info.h.
                                                                         {
    return UseInfo(MachineRepresentation::kWord32,
                   Truncation::Any(identify_zeros), TypeCheckKind::kSigned32,
                   feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kSigned32, v8::internal::kWord32, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
CheckedSigned64AsWord64()
static UseInfo v8::internal::compiler::UseInfo::CheckedSigned64AsWord64 (IdentifyZeros identify_zeros, const FeedbackSource & feedback) [inline], [static]
Definition at line 336 of file use-info.h.
                                                                         {
    return UseInfo(MachineRepresentation::kWord64,
                   Truncation::Any(identify_zeros), TypeCheckKind::kSigned64,
                   feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kSigned64, v8::internal::kWord64, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument(), and v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
CheckedSignedSmallAsTaggedSigned()
static UseInfo v8::internal::compiler::UseInfo::CheckedSignedSmallAsTaggedSigned (const FeedbackSource & feedback, IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 317 of file use-info.h.
                                                        {
    return UseInfo(MachineRepresentation::kTaggedSigned,
                   Truncation::Any(identify_zeros), TypeCheckKind::kSignedSmall,
                   feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kSignedSmall, v8::internal::kTaggedSigned, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedSignedSmallAsWord32()
static UseInfo v8::internal::compiler::UseInfo::CheckedSignedSmallAsWord32 (IdentifyZeros identify_zeros, const FeedbackSource & feedback) [inline], [static]
Definition at line 324 of file use-info.h.
                                                                            {
    return UseInfo(MachineRepresentation::kWord32,
                   Truncation::Any(identify_zeros), TypeCheckKind::kSignedSmall,
                   feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kSignedSmall, v8::internal::kWord32, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint(), and v8::internal::compiler::RepresentationSelector::VisitNode().
CheckedTaggedAsArrayIndex()
static UseInfo v8::internal::compiler::UseInfo::CheckedTaggedAsArrayIndex (const FeedbackSource & feedback) [inline], [static]
Definition at line 301 of file use-info.h.
                                                                           {
    return UseInfo(MachineType::PointerRepresentation(),
                   Truncation::Any(kIdentifyZeros), TypeCheckKind::kArrayIndex,
                   feedback);
  }
References v8::internal::compiler::Truncation::Any(), feedback(), v8::internal::compiler::kArrayIndex, v8::internal::compiler::kIdentifyZeros, v8::internal::MachineType::PointerRepresentation(), and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
feedback()
const FeedbackSource& v8::internal::compiler::UseInfo::feedback () const [inline]
Definition at line 391 of file use-info.h.
{ return feedback_; }
References feedback_.
Referenced by CheckedBigInt64AsWord64(), CheckedBigIntAsTaggedPointer(), CheckedBigIntTruncatingWord64(), CheckedHeapObjectAsTaggedPointer(), CheckedNumberAsFloat64(), CheckedNumberAsWord32(), CheckedNumberOrBooleanAsFloat64(), CheckedNumberOrOddballAsFloat64(), CheckedNumberOrOddballAsWord32(), CheckedSafeIntAsWord64(), CheckedSafeIntTruncatingWord32(), CheckedSigned32AsWord32(), CheckedSigned64AsWord64(), CheckedSignedSmallAsTaggedSigned(), CheckedSignedSmallAsWord32(), CheckedTaggedAsArrayIndex(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Float16RawBits()
static UseInfo v8::internal::compiler::UseInfo::Float16RawBits () [inline], [static]
Definition at line 256 of file use-info.h.
                                  {
    return UseInfo(MachineRepresentation::kFloat16RawBits, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kFloat16RawBits, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation().
Float32()
static UseInfo v8::internal::compiler::UseInfo::Float32 () [inline], [static]
Definition at line 253 of file use-info.h.
                           {
    return UseInfo(MachineRepresentation::kFloat32, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kFloat32, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation().
Float64()
static UseInfo v8::internal::compiler::UseInfo::Float64 () [inline], [static]
Definition at line 259 of file use-info.h.
                           {
    return UseInfo(MachineRepresentation::kFloat64, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kFloat64, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
minus_zero_check()
CheckForMinusZeroMode v8::internal::compiler::UseInfo::minus_zero_check () const [inline]
Definition at line 386 of file use-info.h.
                                                 {
    return truncation().IdentifiesZeroAndMinusZero()
               ? CheckForMinusZeroMode::kDontCheckForMinusZero
               : CheckForMinusZeroMode::kCheckForMinusZero;
  }
References v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), v8::internal::compiler::kCheckForMinusZero, v8::internal::compiler::kDontCheckForMinusZero, and truncation().
Referenced by v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), and v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
None()
static UseInfo v8::internal::compiler::UseInfo::None () [inline], [static]
Definition at line 379 of file use-info.h.
                        {
    return UseInfo(MachineRepresentation::kNone, Truncation::None());
  }
References v8::internal::kNone, v8::internal::compiler::Truncation::None(), and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectIs(), v8::internal::compiler::RepresentationSelector::VisitPhi(), and v8::internal::compiler::RepresentationSelector::VisitUnused().
representation()
MachineRepresentation v8::internal::compiler::UseInfo::representation () const [inline]
Definition at line 383 of file use-info.h.
{ return representation_; }
References representation_.
Referenced by v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
TaggedPointer()
static UseInfo v8::internal::compiler::UseInfo::TaggedPointer () [inline], [static]
Definition at line 296 of file use-info.h.
                                 {
    return UseInfo(MachineRepresentation::kTaggedPointer, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kTaggedPointer, and UseInfo().
TaggedSigned()
static UseInfo v8::internal::compiler::UseInfo::TaggedSigned () [inline], [static]
Definition at line 293 of file use-info.h.
                                {
    return UseInfo(MachineRepresentation::kTaggedSigned, Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kTaggedSigned, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), and v8::internal::compiler::RepresentationSelector::VisitNode().
TruncatingFloat16RawBits()
static UseInfo v8::internal::compiler::UseInfo::TruncatingFloat16RawBits (IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 267 of file use-info.h.
                                                        {
    return UseInfo(MachineRepresentation::kFloat16,
                   Truncation::OddballAndBigIntToNumber(identify_zeros));
  }
References v8::internal::kFloat16, v8::internal::compiler::Truncation::OddballAndBigIntToNumber(), and UseInfo().
TruncatingFloat64()
static UseInfo v8::internal::compiler::UseInfo::TruncatingFloat64 (IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 262 of file use-info.h.
                                                        {
    return UseInfo(MachineRepresentation::kFloat64,
                   Truncation::OddballAndBigIntToNumber(identify_zeros));
  }
References v8::internal::kFloat64, v8::internal::compiler::Truncation::OddballAndBigIntToNumber(), and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), v8::internal::compiler::RepresentationSelector::VisitFloat64Binop(), and v8::internal::compiler::RepresentationSelector::VisitNode().
TruncatingFloat64OrUndefined()
static UseInfo v8::internal::compiler::UseInfo::TruncatingFloat64OrUndefined (IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 285 of file use-info.h.
                                                        {
    return UseInfo(MachineRepresentation::kFloat64,
                   Truncation::BooleanAndNullAndBigIntToNumber(identify_zeros));
  }
References v8::internal::compiler::Truncation::BooleanAndNullAndBigIntToNumber(), v8::internal::kFloat64, and UseInfo().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), and v8::internal::compiler::RepresentationSelector::VisitNode().
TruncatingWord32()
static UseInfo v8::internal::compiler::UseInfo::TruncatingWord32 () [inline], [static]
Definition at line 223 of file use-info.h.
                                    {
    return UseInfo(MachineRepresentation::kWord32, Truncation::Word32());
  }
References v8::internal::kWord32, UseInfo(), and v8::internal::compiler::Truncation::Word32().
Referenced by v8::internal::compiler::JSGraphAssembler::ArrayBufferDetachedBit(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::compiler::JSGraphAssembler::LoadElementsKind(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitReturn(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeInt32Binop(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), and v8::internal::compiler::RepresentationSelector::VisitWord32TruncatingBinop().
TruncatingWord64()
static UseInfo v8::internal::compiler::UseInfo::TruncatingWord64 () [inline], [static]
Definition at line 227 of file use-info.h.
                                    {
    return UseInfo(MachineRepresentation::kWord64, Truncation::Word64());
  }
References v8::internal::kWord64, UseInfo(), and v8::internal::compiler::Truncation::Word64().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation().
truncation()
Truncation v8::internal::compiler::UseInfo::truncation () const [inline]
Definition at line 384 of file use-info.h.
{ return truncation_; }
References truncation_.
Referenced by v8::internal::compiler::RepresentationSelector::NodeInfo::AddUse(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::hash_value(), minus_zero_check(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitForCheckedInt32Mul().
type_check()
TypeCheckKind v8::internal::compiler::UseInfo::type_check () const [inline]
Definition at line 385 of file use-info.h.
{ return type_check_; }
References type_check_.
Referenced by v8::internal::compiler::JSGraphAssembler::EnterMachineGraph(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Word()
static UseInfo v8::internal::compiler::UseInfo::Word () [inline], [static]
Definition at line 247 of file use-info.h.
                        {
    return UseInfo(MachineType::PointerRepresentation(), Truncation::Any());
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::MachineType::PointerRepresentation(), and UseInfo().
Referenced by v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::UseInfoForBasePointer(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Word64()
static UseInfo v8::internal::compiler::UseInfo::Word64 (IdentifyZeros identify_zeros = kDistinguishZeros) [inline], [static]
Definition at line 243 of file use-info.h.
                                                                          {
    return UseInfo(MachineRepresentation::kWord64,
                   Truncation::Any(identify_zeros));
  }
References v8::internal::compiler::Truncation::Any(), v8::internal::kWord64, and UseInfo().
Referenced by v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitInt64Binop(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::UseInfo::feedback_ [private]
Definition at line 397 of file use-info.h.
Referenced by feedback().
representation_
MachineRepresentation v8::internal::compiler::UseInfo::representation_ [private]
Definition at line 394 of file use-info.h.
Referenced by representation().
truncation_
Truncation v8::internal::compiler::UseInfo::truncation_ [private]
Definition at line 395 of file use-info.h.
Referenced by truncation().
type_check_
TypeCheckKind v8::internal::compiler::UseInfo::type_check_ [private]
Definition at line 396 of file use-info.h.
Referenced by type_check().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/use-info.h