v8::internal::compiler::TypeNarrowingReducer Class Reference
#include <type-narrowing-reducer.h>
Public Member Functions
TypeNarrowingReducer (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker)
~TypeNarrowingReducer () final
TypeNarrowingReducer (const TypeNarrowingReducer &)=delete
TypeNarrowingReducer & operator= (const TypeNarrowingReducer &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
JSGraph * jsgraph () const
TFGraph * graph () const
Zone * zone () const
Private Attributes
JSGraph *const jsgraph_
OperationTyper op_typer_
Detailed Description
Definition at line 19 of file type-narrowing-reducer.h.
Constructor & Destructor Documentation
TypeNarrowingReducer() [1/2]
v8::internal::compiler::TypeNarrowingReducer::TypeNarrowingReducer (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker)
Definition at line 14 of file type-narrowing-reducer.cc.
    : AdvancedReducer(editor),
      jsgraph_(jsgraph),
      op_typer_(broker, zone()) {}
 TypeNarrowingReducer()
v8::internal::compiler::TypeNarrowingReducer::~TypeNarrowingReducer () [final], [default]
TypeNarrowingReducer() [2/2]
v8::internal::compiler::TypeNarrowingReducer::TypeNarrowingReducer (const TypeNarrowingReducer &) [delete]
Member Function Documentation
graph()
TFGraph * v8::internal::compiler::TypeNarrowingReducer::graph () const [private]
Definition at line 80 of file type-narrowing-reducer.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by zone().
jsgraph()
JSGraph* v8::internal::compiler::TypeNarrowingReducer::jsgraph () const [inline], [private]
Definition at line 32 of file type-narrowing-reducer.h.
{ return jsgraph_; }
Referenced by graph().
operator=()
TypeNarrowingReducer& v8::internal::compiler::TypeNarrowingReducer::operator= (const TypeNarrowingReducer &) [delete]
Reduce()
Reduction v8::internal::compiler::TypeNarrowingReducer::Reduce (Node * node) [final]
Definition at line 22 of file type-narrowing-reducer.cc.
                                                 {
  Type new_type = Type::Any();
  switch (node->opcode()) {
    case IrOpcode::kNumberLessThan: {
      // TODO(turbofan) Reuse the logic from typer.cc (by integrating relational
      // comparisons with the operation typer).
      Type left_type = NodeProperties::GetType(node->InputAt(0));
      Type right_type = NodeProperties::GetType(node->InputAt(1));
      if (left_type.Is(Type::PlainNumber()) &&
          right_type.Is(Type::PlainNumber())) {
        if (left_type.Max() < right_type.Min()) {
          new_type = op_typer_.singleton_true();
        } else if (left_type.Min() >= right_type.Max()) {
          new_type = op_typer_.singleton_false();
        }
      }
      break;
    }
    case IrOpcode::kTypeGuard: {
      new_type = op_typer_.TypeTypeGuard(
          node->op(), NodeProperties::GetType(node->InputAt(0)));
      break;
    }
#define DECLARE_CASE(Name) \
  case IrOpcode::k##Name: { \
    new_type = op_typer_.Name(NodeProperties::GetType(node->InputAt(0)), \
                              NodeProperties::GetType(node->InputAt(1))); \
    break; \
  }
      SIMPLIFIED_NUMBER_BINOP_LIST(DECLARE_CASE)
      DECLARE_CASE(SameValue)
#undef DECLARE_CASE
#define DECLARE_CASE(Name) \
  case IrOpcode::k##Name: { \
    new_type = op_typer_.Name(NodeProperties::GetType(node->InputAt(0))); \
    break; \
  }
      SIMPLIFIED_NUMBER_UNOP_LIST(DECLARE_CASE)
      DECLARE_CASE(ToBoolean)
#undef DECLARE_CASE
    default:
      return NoChange();
  }
  Type original_type = NodeProperties::GetType(node);
  Type restricted = Type::Intersect(new_type, original_type, zone());
  if (!original_type.Is(restricted)) {
    NodeProperties::SetType(node, restricted);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::turboshaft::Type::Any(), DECLARE_CASE, v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), v8::internal::compiler::Node::op(), op_typer_, v8::internal::compiler::Node::opcode(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::SameValue(), v8::internal::compiler::NodeProperties::SetType(), SIMPLIFIED_NUMBER_BINOP_LIST, SIMPLIFIED_NUMBER_UNOP_LIST, v8::internal::compiler::OperationTyper::singleton_false(), v8::internal::compiler::OperationTyper::singleton_true(), v8::internal::compiler::OperationTyper::TypeTypeGuard(), and zone().
reducer_name()
const char* v8::internal::compiler::TypeNarrowingReducer::reducer_name () const [inline], [override]
Definition at line 27 of file type-narrowing-reducer.h.
{ return "TypeNarrowingReducer"; }
zone()
Zone * v8::internal::compiler::TypeNarrowingReducer::zone () const [private]
Definition at line 82 of file type-narrowing-reducer.cc.
{ return graph()->zone(); }
References graph(), and v8::internal::compiler::TFGraph::zone().
Referenced by Reduce().
Member Data Documentation
jsgraph_
JSGraph* const v8::internal::compiler::TypeNarrowingReducer::jsgraph_ [private]
Definition at line 36 of file type-narrowing-reducer.h.
op_typer_
OperationTyper v8::internal::compiler::TypeNarrowingReducer::op_typer_ [private]
Definition at line 37 of file type-narrowing-reducer.h.
Referenced by Reduce().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/type-narrowing-reducer.h
/mnt/V8SourceCode/src/compiler/type-narrowing-reducer.cc