v8::internal::CallApiCallbackOptimizedDescriptor Class Reference
#include <interface-descriptors.h>
Static Public Member Functions
static constexpr Register FunctionTemplateInfoRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 2278 of file interface-descriptors.h.
Member Function Documentation
FunctionTemplateInfoRegister()
constexpr Register v8::internal::CallApiCallbackOptimizedDescriptor::FunctionTemplateInfoRegister () [inline], [static], [constexpr]
Definition at line 353 of file interface-descriptors-riscv-inl.h.
                                                                 {
  return a3;
}
Referenced by v8::internal::Builtins::Generate_CallApiCallbackImpl(), and registers().
registers()
constexpr auto v8::internal::CallApiCallbackOptimizedDescriptor::registers () [inline], [static], [constexpr]
Definition at line 711 of file interface-descriptors-inl.h.
                                                             {
  return RegisterArray(ApiFunctionAddressRegister(),
                       ActualArgumentsCountRegister(),
                       FunctionTemplateInfoRegister());
}
References FunctionTemplateInfoRegister(), and v8::internal::RegisterArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h