v8::internal::ZoneChunkList< T > Class Template Reference
#include <zone-chunk-list.h>
Classes
struct Chunk
struct SeekResult
Public Types
using iterator = ZoneChunkListIterator< T, false, true >
using const_iterator = ZoneChunkListIterator< T, false, false >
using reverse_iterator = ZoneChunkListIterator< T, true, true >
using const_reverse_iterator = ZoneChunkListIterator< T, true, false >
Public Member Functions
ZoneChunkList (Zone *zone)
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (ZoneChunkList)
size_t size () const
bool empty () const
T & front ()
const T & front () const
T & back ()
const T & back () const
void push_back (const T &item)
void push_front (const T &item)
void Rewind (const size_t limit=0)
iterator Find (const size_t index)
const_iterator Find (const size_t index) const
ZoneChunkList< T > SplitAt (iterator split_begin)
void Append (ZoneChunkList< T > &other)
void CopyTo (T *ptr)
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
void swap (ZoneChunkList< T > &other)
Static Public Attributes
static constexpr uint32_t kInitialChunkCapacity = 8
static constexpr uint32_t kMaxChunkCapacity = 256
Private Member Functions
Chunk * NewChunk (const uint32_t capacity)
SeekResult SeekIndex (size_t index) const
Static Private Member Functions
static uint32_t NextChunkCapacity (uint32_t previous_capacity)
Private Attributes
Zone * zone_
size_t size_ = 0
Chunk * front_ = nullptr
Chunk * last_nonempty_ = nullptr
Friends
template<typename S , bool backwards, bool modifiable>
class ZoneChunkListIterator
Detailed Description
template<typename T>
class v8::internal::ZoneChunkList< T >
Definition at line 39 of file zone-chunk-list.h.
Member Typedef Documentation
const_iterator
template<typename T >
using v8::internal::ZoneChunkList< T >::const_iterator = ZoneChunkListIterator<T, false, false>
Definition at line 42 of file zone-chunk-list.h.
const_reverse_iterator
template<typename T >
using v8::internal::ZoneChunkList< T >::const_reverse_iterator = ZoneChunkListIterator<T, true, false>
Definition at line 44 of file zone-chunk-list.h.
iterator
template<typename T >
using v8::internal::ZoneChunkList< T >::iterator = ZoneChunkListIterator<T, false, true>
Definition at line 41 of file zone-chunk-list.h.
reverse_iterator
template<typename T >
using v8::internal::ZoneChunkList< T >::reverse_iterator = ZoneChunkListIterator<T, true, true>
Definition at line 43 of file zone-chunk-list.h.
Constructor & Destructor Documentation
ZoneChunkList()
template<typename T >
v8::internal::ZoneChunkList< T >::ZoneChunkList (Zone * zone) [inline], [explicit]
Definition at line 49 of file zone-chunk-list.h.
: zone_(zone) {}
Member Function Documentation
Append()
template<typename T >
void v8::internal::ZoneChunkList< T >::Append (ZoneChunkList< T > & other)
Definition at line 499 of file zone-chunk-list.h.
                                                     {
  DCHECK_EQ(zone_, other.zone_);
  if (other.front_ == nullptr) return;
  last_nonempty_->next_ = other.front_;
  other.front_->previous_ = last_nonempty_;
  last_nonempty_ = other.last_nonempty_;
  size_ += other.size_;
#ifdef DEBUG
  Verify();
#endif
  // Leave `other` in empty, but valid state.
  other.front_ = nullptr;
  other.last_nonempty_ = nullptr;
  other.size_ = 0;
}
References DCHECK_EQ, v8::internal::ZoneChunkList< T >::front_, v8::internal::ZoneChunkList< T >::last_nonempty_, v8::internal::ZoneChunkList< T >::Chunk::previous_, v8::internal::ZoneChunkList< T >::size_, and v8::internal::ZoneChunkList< T >::zone_.
back() [1/2]
template<typename T >
T & v8::internal::ZoneChunkList< T >::back
Definition at line 321 of file zone-chunk-list.h.
                          {
  DCHECK(!empty());
  // Avoid the branch in `ZoneChunkListIterator::Begin()`.
  V8_ASSUME(size_ != 0);
  return *rbegin();
}
References v8::internal::DCHECK(), and V8_ASSUME.
back() [2/2]
template<typename T >
const T & v8::internal::ZoneChunkList< T >::back
Definition at line 329 of file zone-chunk-list.h.
                                      {
  DCHECK(!empty());
  // Avoid the branch in `ZoneChunkListIterator::Begin()`.
  V8_ASSUME(size_ != 0);
  return *rbegin();
}
References v8::internal::DCHECK(), and V8_ASSUME.
begin() [1/2]
template<typename T >
iterator v8::internal::ZoneChunkList< T >::begin () [inline]
Definition at line 87 of file zone-chunk-list.h.
{ return iterator::Begin(this); }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin().
begin() [2/2]
template<typename T >
const_iterator v8::internal::ZoneChunkList< T >::begin () const [inline]
Definition at line 91 of file zone-chunk-list.h.
{ return const_iterator::Begin(this); }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin().
CopyTo()
template<typename T >
void v8::internal::ZoneChunkList< T >::CopyTo (T * ptr)
Definition at line 521 of file zone-chunk-list.h.
                                    {
  for (Chunk* current = front_; current != nullptr; current = current->next_) {
    void* start = current->items();
    void* end = current->items() + current->position_;
    size_t bytes = static_cast<size_t>(reinterpret_cast<uintptr_t>(end) -
                                       reinterpret_cast<uintptr_t>(start));
    MemCopy(ptr, current->items(), bytes);
    ptr += current->position_;
  }
}
References v8::internal::compiler::end(), v8::internal::MemCopy(), and v8::internal::ZoneChunkList< T >::Chunk::next_.
empty()
template<typename T >
bool v8::internal::ZoneChunkList< T >::empty () const [inline]
Definition at line 54 of file zone-chunk-list.h.
{ return size() == 0; }
References v8::internal::ZoneChunkList< T >::size().
Referenced by v8::internal::Parser::ParseExportDeclaration().
end() [1/2]
template<typename T >
iterator v8::internal::ZoneChunkList< T >::end () [inline]
Definition at line 88 of file zone-chunk-list.h.
{ return iterator::End(this); }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End().
end() [2/2]
template<typename T >
const_iterator v8::internal::ZoneChunkList< T >::end () const [inline]
Definition at line 92 of file zone-chunk-list.h.
{ return const_iterator::End(this); }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End().
Find() [1/2]
template<typename T >
ZoneChunkList< T >::iterator v8::internal::ZoneChunkList< T >::Find (const size_t index)
Definition at line 423 of file zone-chunk-list.h.
                                                                           {
  SeekResult seek_result = SeekIndex(index);
  return typename ZoneChunkList<T>::iterator(seek_result.chunk_,
                                             seek_result.chunk_index_);
}
References v8::internal::ZoneChunkList< T >::SeekResult::chunk_, v8::internal::ZoneChunkList< T >::SeekResult::chunk_index_, and v8::internal::index.
Find() [2/2]
template<typename T >
ZoneChunkList< T >::const_iterator v8::internal::ZoneChunkList< T >::Find (const size_t index) const
Definition at line 430 of file zone-chunk-list.h.
                              {
  SeekResult seek_result = SeekIndex(index);
  return typename ZoneChunkList<T>::const_iterator(seek_result.chunk_,
                                                   seek_result.chunk_index_);
}
References v8::internal::ZoneChunkList< T >::SeekResult::chunk_, v8::internal::ZoneChunkList< T >::SeekResult::chunk_index_, and v8::internal::index.
front() [1/2]
template<typename T >
T & v8::internal::ZoneChunkList< T >::front
Definition at line 309 of file zone-chunk-list.h.
                           {
  DCHECK(!empty());
  return *begin();
}
References v8::internal::compiler::begin(), and v8::internal::DCHECK().
front() [2/2]
template<typename T >
const T & v8::internal::ZoneChunkList< T >::front
Definition at line 315 of file zone-chunk-list.h.
                                       {
  DCHECK(!empty());
  return *begin();
}
References v8::internal::compiler::begin(), and v8::internal::DCHECK().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
template<typename T >
v8::internal::ZoneChunkList< T >::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (ZoneChunkList< T >)
NewChunk()
template<typename T >
Chunk* v8::internal::ZoneChunkList< T >::NewChunk (const uint32_t capacity) [inline], [private]
Definition at line 126 of file zone-chunk-list.h.
                                           {
    void* memory = zone_->Allocate<Chunk>(sizeof(Chunk) + capacity * sizeof(T));
    Chunk* chunk = new (memory) Chunk();
    chunk->capacity_ = capacity;
    return chunk;
  }
References v8::internal::Zone::Allocate(), v8::internal::ZoneChunkList< T >::Chunk::capacity_, and v8::internal::ZoneChunkList< T >::zone_.
NextChunkCapacity()
template<typename T >
static uint32_t v8::internal::ZoneChunkList< T >::NextChunkCapacity (uint32_t previous_capacity) [inline], [static], [private]
Definition at line 133 of file zone-chunk-list.h.
                                                                {
    return std::min(previous_capacity * 2, kMaxChunkCapacity);
  }
References v8::internal::ZoneChunkList< T >::kMaxChunkCapacity.
push_back()
template<typename T >
void v8::internal::ZoneChunkList< T >::push_back (const T & item)
Definition at line 337 of file zone-chunk-list.h.
                                              {
  if (last_nonempty_ == nullptr) {
    // Initially empty chunk list.
    front_ = NewChunk(kInitialChunkCapacity);
    last_nonempty_ = front_;
  } else if (last_nonempty_->full()) {
    // If there is an empty chunk following, reuse that, otherwise allocate.
    if (last_nonempty_->next_ == nullptr) {
      Chunk* chunk = NewChunk(NextChunkCapacity(last_nonempty_->capacity_));
      last_nonempty_->next_ = chunk;
      chunk->previous_ = last_nonempty_;
    }
    last_nonempty_ = last_nonempty_->next_;
    DCHECK(!last_nonempty_->full());
  }
  last_nonempty_->items()[last_nonempty_->position_] = item;
  ++last_nonempty_->position_;
  ++size_;
  DCHECK_LE(last_nonempty_->position_, last_nonempty_->capacity_);
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::ZoneChunkList< T >::Chunk::next_, and v8::internal::ZoneChunkList< T >::Chunk::previous_.
Referenced by v8::internal::Parser::ParseExportClause().
push_front()
template<typename T >
void v8::internal::ZoneChunkList< T >::push_front (const T & item)
Definition at line 360 of file zone-chunk-list.h.
                                               {
  if (front_ == nullptr) {
    // Initially empty chunk list.
    front_ = NewChunk(kInitialChunkCapacity);
    last_nonempty_ = front_;
  } else if (front_->full()) {
    // First chunk at capacity, so prepend a new chunk.
    DCHECK_NULL(front_->previous_);
    Chunk* chunk = NewChunk(NextChunkCapacity(front_->capacity_));
    front_->previous_ = chunk;
    chunk->next_ = front_;
    front_ = chunk;
  }
  DCHECK(!front_->full());
  T* end = front_->items() + front_->position_;
  std::move_backward(front_->items(), end, end + 1);
  front_->items()[0] = item;
  ++front_->position_;
  ++size_;
  DCHECK_LE(front_->position_, front_->capacity_);
}
References v8::internal::DCHECK(), DCHECK_LE, DCHECK_NULL, v8::internal::compiler::end(), and v8::internal::ZoneChunkList< T >::Chunk::next_.
rbegin() [1/2]
template<typename T >
reverse_iterator v8::internal::ZoneChunkList< T >::rbegin () [inline]
Definition at line 89 of file zone-chunk-list.h.
{ return reverse_iterator::Begin(this); }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin().
rbegin() [2/2]
template<typename T >
const_reverse_iterator v8::internal::ZoneChunkList< T >::rbegin () const [inline]
Definition at line 93 of file zone-chunk-list.h.
                                        {
    return const_reverse_iterator::Begin(this);
  }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::Begin().
rend() [1/2]
template<typename T >
reverse_iterator v8::internal::ZoneChunkList< T >::rend () [inline]
Definition at line 90 of file zone-chunk-list.h.
{ return reverse_iterator::End(this); }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End().
rend() [2/2]
template<typename T >
const_reverse_iterator v8::internal::ZoneChunkList< T >::rend () const [inline]
Definition at line 96 of file zone-chunk-list.h.
                                      {
    return const_reverse_iterator::End(this);
  }
References v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::End().
Rewind()
template<typename T >
void v8::internal::ZoneChunkList< T >::Rewind (const size_t limit = 0)
Definition at line 397 of file zone-chunk-list.h.
                                                {
  if (limit >= size()) return;
  SeekResult seek_result = SeekIndex(limit);
  DCHECK_NOT_NULL(seek_result.chunk_);
  // Do a partial rewind of the chunk containing the index.
  seek_result.chunk_->position_ = seek_result.chunk_index_;
  // Set last_nonempty_ so iterators will work correctly.
  last_nonempty_ = seek_result.chunk_;
  // Do full rewind of all subsequent chunks.
  for (Chunk* current = seek_result.chunk_->next_; current != nullptr;
       current = current->next_) {
    current->position_ = 0;
  }
  size_ = limit;
#ifdef DEBUG
  Verify();
#endif
}
References v8::internal::ZoneChunkList< T >::SeekResult::chunk_, v8::internal::ZoneChunkList< T >::SeekResult::chunk_index_, DCHECK_NOT_NULL, v8::internal::ZoneChunkList< T >::Chunk::next_, v8::internal::ZoneChunkList< T >::Chunk::position_, and size().
SeekIndex()
template<typename T >
ZoneChunkList< T >::SeekResult v8::internal::ZoneChunkList< T >::SeekIndex (size_t index) const [private]
Definition at line 384 of file zone-chunk-list.h.
                        {
  DCHECK_LT(index, size());
  Chunk* current = front_;
  while (index >= current->capacity_) {
    index -= current->capacity_;
    current = current->next_;
  }
  DCHECK_LT(index, current->capacity_);
  return {current, static_cast<uint32_t>(index)};
}
References v8::internal::ZoneChunkList< T >::Chunk::capacity_, DCHECK_LT, v8::internal::index, v8::internal::ZoneChunkList< T >::Chunk::next_, and size().
size()
template<typename T >
size_t v8::internal::ZoneChunkList< T >::size () const [inline]
Definition at line 53 of file zone-chunk-list.h.
{ return size_; }
References v8::internal::ZoneChunkList< T >::size_.
Referenced by v8::internal::ZoneChunkList< T >::empty().
SplitAt()
template<typename T >
ZoneChunkList< T > v8::internal::ZoneChunkList< T >::SplitAt (iterator split_begin)
Definition at line 438 of file zone-chunk-list.h.
                                                               {
  ZoneChunkList<T> result(zone_);
  // `result` is an empty freshly-constructed list.
  if (split_begin == end()) return result;
  // `this` is empty after the split and `result` contains everything.
  if (split_begin == begin()) {
    this->swap(result);
    return result;
  }
  // There is at least one element in both `this` and `result`.
  // Split the chunk.
  Chunk* split_chunk = split_begin.current_;
  DCHECK_LE(split_begin.position_, split_chunk->position_);
  T* chunk_split_begin = split_chunk->items() + split_begin.position_;
  T* chunk_split_end = split_chunk->items() + split_chunk->position_;
  uint32_t new_chunk_size =
      static_cast<uint32_t>(chunk_split_end - chunk_split_begin);
  uint32_t new_chunk_capacity = std::max(
      kInitialChunkCapacity, base::bits::RoundUpToPowerOfTwo32(new_chunk_size));
  CHECK_LE(new_chunk_size, new_chunk_capacity);
  Chunk* new_chunk = NewChunk(new_chunk_capacity);
  std::copy(chunk_split_begin, chunk_split_end, new_chunk->items());
  new_chunk->position_ = new_chunk_size;
  split_chunk->position_ = split_begin.position_;
  // Split the linked list.
  result.front_ = new_chunk;
  result.last_nonempty_ =
      (last_nonempty_ == split_chunk) ? new_chunk : last_nonempty_;
  new_chunk->next_ = split_chunk->next_;
  if (new_chunk->next_) {
    new_chunk->next_->previous_ = new_chunk;
  }
  last_nonempty_ = split_chunk;
  split_chunk->next_ = nullptr;
  // Compute the new size.
  size_t new_size = 0;
  for (Chunk* chunk = front_; chunk != split_chunk; chunk = chunk->next_) {
    DCHECK(!chunk->empty());
    new_size += chunk->size();
  }
  new_size += split_chunk->size();
  DCHECK_LT(new_size, size());
  result.size_ = size() - new_size;
  size_ = new_size;
#ifdef DEBUG
  Verify();
  result.Verify();
#endif
  return result;
}
References v8::internal::compiler::begin(), CHECK_LE, v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::current_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, v8::internal::compiler::end(), v8::internal::ZoneChunkList< T >::Chunk::items(), v8::internal::ZoneChunkList< T >::Chunk::next_, v8::internal::ZoneChunkList< T >::Chunk::position_, v8::internal::ZoneChunkListIterator< T, backwards, modifiable >::position_, v8::internal::ZoneChunkList< T >::Chunk::previous_, v8::base::internal::result, v8::internal::ZoneChunkList< T >::Chunk::size(), and size().
swap()
template<typename T >
void v8::internal::ZoneChunkList< T >::swap (ZoneChunkList< T > & other) [inline]
Definition at line 100 of file zone-chunk-list.h.
                                     {
    DCHECK_EQ(zone_, other.zone_);
    std::swap(size_, other.size_);
    std::swap(front_, other.front_);
    std::swap(last_nonempty_, other.last_nonempty_);
  }
References DCHECK_EQ, v8::internal::ZoneChunkList< T >::front_, v8::internal::ZoneChunkList< T >::last_nonempty_, v8::internal::ZoneChunkList< T >::size_, and v8::internal::ZoneChunkList< T >::zone_.
Friends And Related Function Documentation
ZoneChunkListIterator
template<typename T >
template<typename S , bool backwards, bool modifiable>
friend class ZoneChunkListIterator [friend]
Definition at line 109 of file zone-chunk-list.h.
Member Data Documentation
front_
template<typename T >
Chunk* v8::internal::ZoneChunkList< T >::front_ = nullptr [private]
Definition at line 183 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkList< T >::Append(), and v8::internal::ZoneChunkList< T >::swap().
kInitialChunkCapacity
template<typename T >
constexpr uint32_t v8::internal::ZoneChunkList< T >::kInitialChunkCapacity = 8 [static], [constexpr]
Definition at line 46 of file zone-chunk-list.h.
kMaxChunkCapacity
template<typename T >
constexpr uint32_t v8::internal::ZoneChunkList< T >::kMaxChunkCapacity = 256 [static], [constexpr]
Definition at line 47 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkList< T >::NextChunkCapacity().
last_nonempty_
template<typename T >
Chunk* v8::internal::ZoneChunkList< T >::last_nonempty_ = nullptr [private]
Definition at line 184 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkList< T >::Append(), and v8::internal::ZoneChunkList< T >::swap().
size_
template<typename T >
size_t v8::internal::ZoneChunkList< T >::size_ = 0 [private]
Definition at line 182 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkList< T >::Append(), v8::internal::ZoneChunkList< T >::size(), and v8::internal::ZoneChunkList< T >::swap().
zone_
template<typename T >
Zone* v8::internal::ZoneChunkList< T >::zone_ [private]
Definition at line 180 of file zone-chunk-list.h.
Referenced by v8::internal::ZoneChunkList< T >::Append(), v8::internal::ZoneChunkList< T >::NewChunk(), and v8::internal::ZoneChunkList< T >::swap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/zone/zone-chunk-list.h