v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask Class Reference
Public Member Functions
HeapSnapshotTask (V8HeapProfilerAgentImpl *agent, std::shared_ptr< AsyncCallbacks > asyncCallbacks, HeapSnapshotProtocolOptions protocolOptions, std::unique_ptr< TakeHeapSnapshotCallback > callback)
void Run () override
void Run (cppgc::EmbedderStackState stackState)
Private Attributes
V8HeapProfilerAgentImpl * m_agent
std::weak_ptr< AsyncCallbacks > m_asyncCallbacks
HeapSnapshotProtocolOptions m_protocolOptions
std::unique_ptr< TakeHeapSnapshotCallback > m_callback
Detailed Description
Definition at line 198 of file v8-heap-profiler-agent-impl.cc.
Constructor & Destructor Documentation
HeapSnapshotTask()
v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::HeapSnapshotTask (V8HeapProfilerAgentImpl * agent, std::shared_ptr< AsyncCallbacks > asyncCallbacks, HeapSnapshotProtocolOptions protocolOptions, std::unique_ptr< TakeHeapSnapshotCallback > callback) [inline]
Definition at line 200 of file v8-heap-profiler-agent-impl.cc.
      : m_agent(agent),
        m_asyncCallbacks(asyncCallbacks),
        m_protocolOptions(protocolOptions),
        m_callback(std::move(callback)) {}
Member Function Documentation
Run() [1/2]
void v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::Run () [inline], [override], [virtual]
Implements v8::Task.
Definition at line 209 of file v8-heap-profiler-agent-impl.cc.
{ Run(cppgc::EmbedderStackState::kNoHeapPointers); }
References cppgc::kNoHeapPointers, and Run().
Referenced by Run().
Run() [2/2]
void v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::Run (cppgc::EmbedderStackState stackState) [inline]
Definition at line 211 of file v8-heap-profiler-agent-impl.cc.
                                               {
    Response response = Response::Success();
    {
      // If the async callbacks object still exists and is not canceled, then
      // the V8HeapProfilerAgentImpl still exists, so we can safely take a
      // snapshot.
      std::shared_ptr<AsyncCallbacks> asyncCallbacks = m_asyncCallbacks.lock();
      if (!asyncCallbacks) return;
      v8::base::MutexGuard lock(&asyncCallbacks->m_mutex);
      if (asyncCallbacks->m_canceled) return;
      auto& heapSnapshotTasks = asyncCallbacks->m_heapSnapshotTasks;
      auto it =
          std::find(heapSnapshotTasks.begin(), heapSnapshotTasks.end(), this);
      if (it == heapSnapshotTasks.end()) {
        // This task must have already been run. This can happen because the
        // task was queued with PostNonNestableTask but then got run early by
        // takePendingHeapSnapshots.
        return;
      }
      heapSnapshotTasks.erase(it);
      response = m_agent->takeHeapSnapshotNow(m_protocolOptions, stackState);
    }
    // The rest of this function runs without the mutex, because Node expects to
    // be able to dispose the profiler agent during the callback, which would
    // deadlock if this function still held the mutex. It's safe to call the
    // callback without the mutex; the internal implementation of the callback
    // uses weak pointers to avoid doing anything dangerous if other components
    // have been disposed (see DomainDispatcher::Callback::sendIfActive).
    if (response.IsSuccess()) {
      m_callback->sendSuccess();
    } else {
      m_callback->sendFailure(std::move(response));
    }
  }
References m_agent, m_asyncCallbacks, m_callback, m_protocolOptions, and v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshotNow().
Member Data Documentation
m_agent
V8HeapProfilerAgentImpl* v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::m_agent [private]
Definition at line 250 of file v8-heap-profiler-agent-impl.cc.
Referenced by Run().
m_asyncCallbacks
std::weak_ptr<AsyncCallbacks> v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::m_asyncCallbacks [private]
Definition at line 251 of file v8-heap-profiler-agent-impl.cc.
Referenced by Run().
m_callback
std::unique_ptr<TakeHeapSnapshotCallback> v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::m_callback [private]
Definition at line 253 of file v8-heap-profiler-agent-impl.cc.
Referenced by Run().
m_protocolOptions
HeapSnapshotProtocolOptions v8_inspector::V8HeapProfilerAgentImpl::HeapSnapshotTask::m_protocolOptions [private]
Definition at line 252 of file v8-heap-profiler-agent-impl.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/v8-heap-profiler-agent-impl.cc