v8::internal::compiler::JSCallNodeBase< kOpcodes > Class Template Reference
#include <js-operator.h>
Public Member Functions
constexpr JSCallNodeBase (Node *node)
const CallParameters & Parameters () const
int ArgumentCount () const override
Static Public Attributes
static constexpr int kReceiverInputCount = 1
Additional Inherited Members
Detailed Description
template<int... kOpcodes>
class v8::internal::compiler::JSCallNodeBase< kOpcodes >
Definition at line 1462 of file js-operator.h.
Constructor & Destructor Documentation
JSCallNodeBase()
template<int... kOpcodes>
constexpr v8::internal::compiler::JSCallNodeBase< kOpcodes >::JSCallNodeBase (Node * node) [inline], [explicit], [constexpr]
Definition at line 1464 of file js-operator.h.
                                                : JSCallOrConstructNode(node) {
    DCHECK(IsExpectedOpcode<kOpcodes...>(node->opcode()));
  }
References v8::internal::DCHECK(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
ArgumentCount()
template<int... kOpcodes>
int v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount () const [inline], [override], [virtual]
Implements v8::internal::compiler::JSCallOrConstructNode.
Definition at line 1482 of file js-operator.h.
                                     {
    // Note: The count reported by this function depends only on the parameter,
    // thus adding/removing inputs will not affect it.
    return Parameters().arity_without_implicit_args();
  }
References v8::internal::compiler::CallParameters::arity_without_implicit_args(), and v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducer::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathBinary(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceMathUnary(), v8::internal::compiler::JSCallReducer::ReduceNumberIsFinite(), v8::internal::compiler::JSCallReducer::ReduceNumberIsInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberIsNaN(), v8::internal::compiler::JSCallReducer::ReduceNumberIsSafeInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstring(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
Parameters()
template<int... kOpcodes>
const CallParameters& v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters () const [inline]
Definition at line 1468 of file js-operator.h.
                                           {
    return CallParametersOf(node()->op());
  }
References v8::internal::compiler::CallParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePop(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceMathBinary(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceMathUnary(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCharCodeAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstring(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
Member Data Documentation
kReceiverInputCount
template<int... kOpcodes>
constexpr int v8::internal::compiler::JSCallNodeBase< kOpcodes >::kReceiverInputCount = 1 [static], [constexpr]
Definition at line 1478 of file js-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h