v8::internal::RegExpParser Class Reference
#include <regexp-parser.h>
Static Public Member Functions
static bool ParseRegExpFromHeapString (Isolate *isolate, Zone *zone, DirectHandle< String > input, RegExpFlags flags, RegExpCompileData *result)
template<class CharT >
static bool VerifyRegExpSyntax (Zone *zone, uintptr_t stack_limit, const CharT *input, int input_length, RegExpFlags flags, RegExpCompileData *result, const DisallowGarbageCollection &no_gc)
Detailed Description
Definition at line 20 of file regexp-parser.h.
Member Function Documentation
ParseRegExpFromHeapString()
bool v8::internal::RegExpParser::ParseRegExpFromHeapString (Isolate * isolate, Zone * zone, DirectHandle< String > input, RegExpFlags flags, RegExpCompileData * result) [static]
Definition at line 3248 of file regexp-parser.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  uintptr_t stack_limit = isolate->stack_guard()->real_climit();
  String::FlatContent content = input->GetFlatContent(no_gc);
  if (content.IsOneByte()) {
    base::Vector<const uint8_t> v = content.ToOneByteVector();
    return RegExpParserImpl<uint8_t>{v.begin(), v.length(), flags,
                                     stack_limit, zone, no_gc}
        .Parse(result);
  } else {
    base::Vector<const base::uc16> v = content.ToUC16Vector();
    return RegExpParserImpl<base::uc16>{v.begin(), v.length(), flags,
                                        stack_limit, zone, no_gc}
        .Parse(result);
  }
}
References v8::base::Vector< T >::begin(), v8::internal::flags, v8::internal::String::FlatContent::IsOneByte(), v8::base::Vector< T >::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StackGuard::real_climit(), v8::base::internal::result, v8::internal::Isolate::stack_guard(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::RegExp::Compile(), v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), and v8::internal::RegExpImpl::CompileIrregexp().
VerifyRegExpSyntax()
template<class CharT >
template bool v8::internal::RegExpParser::VerifyRegExpSyntax< uint8_t > (Zone * zone, uintptr_t stack_limit, const CharT * input, int input_length, RegExpFlags flags, RegExpCompileData * result, const DisallowGarbageCollection & no_gc) [static]
Definition at line 3270 of file regexp-parser.cc.
                                                                              {
  return RegExpParserImpl<CharT>{input, input_length, flags,
                                 stack_limit, zone, no_gc}
      .Parse(result);
}
References v8::internal::flags, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::RegExp::VerifySyntax().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-parser.h
/mnt/V8SourceCode/src/regexp/regexp-parser.cc