v8::internal::compiler::BytecodeLoopAssignments Class Reference
#include <bytecode-analysis.h>
Public Member Functions
BytecodeLoopAssignments (int parameter_count, int register_count, Zone *zone)
void Add (interpreter::Register r)
void AddList (interpreter::Register r, uint32_t count)
void Union (const BytecodeLoopAssignments &other)
bool ContainsParameter (int index) const
bool ContainsLocal (int index) const
int parameter_count () const
int local_count () const
Private Attributes
int const parameter_count_
BitVector *const bit_vector_
Detailed Description
Definition at line 24 of file bytecode-analysis.h.
Constructor & Destructor Documentation
BytecodeLoopAssignments()
v8::internal::compiler::BytecodeLoopAssignments::BytecodeLoopAssignments (int parameter_count, int register_count, Zone * zone)
Definition at line 27 of file bytecode-analysis.cc.
    : parameter_count_(parameter_count),
      bit_vector_(
          zone->New<BitVector>(parameter_count + register_count, zone)) {}
Member Function Documentation
Add()
void v8::internal::compiler::BytecodeLoopAssignments::Add (interpreter::Register r)
Definition at line 33 of file bytecode-analysis.cc.
                                                       {
  if (r.is_parameter()) {
    bit_vector_->Add(r.ToParameterIndex());
  } else {
    bit_vector_->Add(parameter_count_ + r.index());
  }
}
References v8::internal::BitVector::Add(), bit_vector_, v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), parameter_count_, and v8::internal::interpreter::Register::ToParameterIndex().
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments().
AddList()
void v8::internal::compiler::BytecodeLoopAssignments::AddList (interpreter::Register r, uint32_t count)
Definition at line 41 of file bytecode-analysis.cc.
                                                                           {
  if (r.is_parameter()) {
    for (uint32_t i = 0; i < count; i++) {
      DCHECK(interpreter::Register(r.index() + i).is_parameter());
      bit_vector_->Add(r.ToParameterIndex() + i);
    }
  } else {
    for (uint32_t i = 0; i < count; i++) {
      DCHECK(!interpreter::Register(r.index() + i).is_parameter());
      bit_vector_->Add(parameter_count_ + r.index() + i);
    }
  }
}
References v8::internal::BitVector::Add(), bit_vector_, v8::internal::DCHECK(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), parameter_count_, and v8::internal::interpreter::Register::ToParameterIndex().
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments().
ContainsLocal()
bool v8::internal::compiler::BytecodeLoopAssignments::ContainsLocal (int index) const
Definition at line 66 of file bytecode-analysis.cc.
                                                           {
  DCHECK_GE(index, 0);
  DCHECK_LT(index, local_count());
  return bit_vector_->Contains(parameter_count_ + index);
}
References bit_vector_, v8::internal::BitVector::Contains(), DCHECK_GE, DCHECK_LT, v8::internal::index, local_count(), and parameter_count_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoop(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit().
ContainsParameter()
bool v8::internal::compiler::BytecodeLoopAssignments::ContainsParameter (int index) const
Definition at line 60 of file bytecode-analysis.cc.
                                                               {
  DCHECK_GE(index, 0);
  DCHECK_LT(index, parameter_count());
  return bit_vector_->Contains(index);
}
References bit_vector_, v8::internal::BitVector::Contains(), DCHECK_GE, DCHECK_LT, v8::internal::index, and parameter_count().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoop(), and v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit().
local_count()
int v8::internal::compiler::BytecodeLoopAssignments::local_count () const [inline]
Definition at line 36 of file bytecode-analysis.h.
{ return bit_vector_->length() - parameter_count_; }
Referenced by ContainsLocal().
parameter_count()
int v8::internal::compiler::BytecodeLoopAssignments::parameter_count () const [inline]
Definition at line 35 of file bytecode-analysis.h.
{ return parameter_count_; }
Referenced by ContainsParameter().
Union()
void v8::internal::compiler::BytecodeLoopAssignments::Union (const BytecodeLoopAssignments & other)
Definition at line 56 of file bytecode-analysis.cc.
                                                                        {
  bit_vector_->Union(*other.bit_vector_);
}
References bit_vector_, and v8::internal::BitVector::Union().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
Member Data Documentation
bit_vector_
BitVector* const v8::internal::compiler::BytecodeLoopAssignments::bit_vector_ [private]
Definition at line 40 of file bytecode-analysis.h.
Referenced by Add(), AddList(), ContainsLocal(), ContainsParameter(), and Union().
parameter_count_
int const v8::internal::compiler::BytecodeLoopAssignments::parameter_count_ [private]
Definition at line 39 of file bytecode-analysis.h.
Referenced by Add(), AddList(), and ContainsLocal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/bytecode-analysis.h
/mnt/V8SourceCode/src/compiler/bytecode-analysis.cc