v8::internal::SamplingThread Class Reference
Public Member Functions
SamplingThread (sampler::Sampler *sampler, int interval_microseconds)
void Run () override
Static Public Attributes
static const int kSamplingThreadStackSize = 64 * KB
Private Attributes
sampler::Sampler * sampler_
const int interval_microseconds_
Additional Inherited Members
Detailed Description
Definition at line 1027 of file log.cc.
Constructor & Destructor Documentation
SamplingThread()
v8::internal::SamplingThread::SamplingThread (sampler::Sampler * sampler, int interval_microseconds) [inline]
Definition at line 1031 of file log.cc.
      : base::Thread(
            base::Thread::Options("SamplingThread", kSamplingThreadStackSize)),
        sampler_(sampler),
        interval_microseconds_(interval_microseconds) {}
Member Function Documentation
Run()
void v8::internal::SamplingThread::Run () [inline], [override], [virtual]
Implements v8::base::Thread.
Definition at line 1037 of file log.cc.
                      {
    while (sampler_->IsActive()) {
      sampler_->DoSample();
      base::OS::Sleep(
          base::TimeDelta::FromMicroseconds(interval_microseconds_));
    }
  }
References v8::sampler::Sampler::DoSample(), v8::base::TimeDelta::FromMicroseconds(), interval_microseconds_, v8::sampler::Sampler::IsActive(), sampler_, and v8::base::OS::Sleep().
Member Data Documentation
interval_microseconds_
const int v8::internal::SamplingThread::interval_microseconds_ [private]
Definition at line 1047 of file log.cc.
Referenced by Run().
kSamplingThreadStackSize
const int v8::internal::SamplingThread::kSamplingThreadStackSize = 64 * KB [static]
Definition at line 1029 of file log.cc.
sampler_
sampler::Sampler* v8::internal::SamplingThread::sampler_ [private]
Definition at line 1046 of file log.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/log.cc