v8::internal::CallInterfaceDescriptorData Class Reference
#include <interface-descriptors.h>
Public Types
enum Flag {
kNoFlags = 0u
, kNoContext = 1u << 0
, kNoStackScan = 1u << 1
, kAllowVarArgs = 1u << 2
,
kCalleeSaveRegisters = 1u << 3
 }
using Flags = base::Flags< Flag >
Public Member Functions
CallInterfaceDescriptorData ()=default
CallInterfaceDescriptorData (const CallInterfaceDescriptorData &)=delete
CallInterfaceDescriptorData & operator= (const CallInterfaceDescriptorData &)=delete
void InitializeRegisters (Flags flags, CodeEntrypointTag tag, CodeSandboxingMode sandboxing_mode, int return_count, int parameter_count, StackArgumentOrder stack_order, int register_parameter_count, const Register *registers, const DoubleRegister *double_registers, const Register *return_registers, const DoubleRegister *return_double_registers)
void InitializeTypes (const MachineType *machine_types, int machine_types_length)
void Reset ()
bool IsInitialized () const
Flags flags () const
CodeEntrypointTag tag () const
CodeSandboxingMode sandboxing_mode () const
int return_count () const
int param_count () const
int register_param_count () const
Register register_param (int index) const
DoubleRegister double_register_param (int index) const
Register register_return (int index) const
DoubleRegister double_register_return (int index) const
MachineType return_type (int index) const
MachineType param_type (int index) const
StackArgumentOrder stack_order () const
void RestrictAllocatableRegisters (const Register *registers, size_t num)
RegList allocatable_registers () const
Static Public Attributes
static constexpr int kUninitializedCount = -1
Private Member Functions
bool IsInitializedRegisters () const
bool IsInitializedTypes () const
Private Attributes
int register_param_count_ = kUninitializedCount
int return_count_ = kUninitializedCount
int param_count_ = kUninitializedCount
Flags flags_ = kNoFlags
CodeEntrypointTag tag_ = kDefaultCodeEntrypointTag
CodeSandboxingMode sandboxing_mode_ = CodeSandboxingMode::kSandboxed
StackArgumentOrder stack_order_ = StackArgumentOrder::kDefault
RegList allocatable_registers_
const Register * register_params_ = nullptr
const DoubleRegister * double_register_params_ = nullptr
const Register * register_returns_ = nullptr
const DoubleRegister * double_register_returns_ = nullptr
MachineType * machine_types_ = nullptr
Detailed Description
Definition at line 176 of file interface-descriptors.h.
Member Typedef Documentation
Flags
using v8::internal::CallInterfaceDescriptorData::Flags = base::Flags<Flag>
Definition at line 192 of file interface-descriptors.h.
Member Enumeration Documentation
Flag
enum v8::internal::CallInterfaceDescriptorData::Flag
Enumerator
kNoFlags
kNoContext
kNoStackScan
kAllowVarArgs
kCalleeSaveRegisters
Definition at line 178 of file interface-descriptors.h.
            {
    kNoFlags = 0u,
    kNoContext = 1u << 0,
    // This indicates that the code uses a special frame that does not scan the
    // stack arguments, e.g. EntryFrame. And this allows the code to use
    // untagged stack arguments.
    kNoStackScan = 1u << 1,
    // In addition to the specified parameters, additional arguments can be
    // passed on the stack.
    // This does not indicate if arguments adaption is used or not.
    kAllowVarArgs = 1u << 2,
    // Callee save allocatable_registers.
    kCalleeSaveRegisters = 1u << 3,
  };
Constructor & Destructor Documentation
CallInterfaceDescriptorData() [1/2]
v8::internal::CallInterfaceDescriptorData::CallInterfaceDescriptorData () [default]
CallInterfaceDescriptorData() [2/2]
v8::internal::CallInterfaceDescriptorData::CallInterfaceDescriptorData (const CallInterfaceDescriptorData &) [delete]
Member Function Documentation
allocatable_registers()
RegList v8::internal::CallInterfaceDescriptorData::allocatable_registers () const [inline]
Definition at line 263 of file interface-descriptors.h.
{ return allocatable_registers_; }
double_register_param()
DoubleRegister v8::internal::CallInterfaceDescriptorData::double_register_param (int index) const [inline]
Definition at line 238 of file interface-descriptors.h.
                                                        {
    return double_register_params_[index];
  }
References v8::internal::index.
double_register_return()
DoubleRegister v8::internal::CallInterfaceDescriptorData::double_register_return (int index) const [inline]
Definition at line 242 of file interface-descriptors.h.
                                                         {
    return double_register_returns_[index];
  }
References v8::internal::index.
flags()
Flags v8::internal::CallInterfaceDescriptorData::flags () const [inline]
Definition at line 231 of file interface-descriptors.h.
{ return flags_; }
Referenced by InitializeRegisters().
InitializeRegisters()
void v8::internal::CallInterfaceDescriptorData::InitializeRegisters (Flags flags, CodeEntrypointTag tag, CodeSandboxingMode sandboxing_mode, int return_count, int parameter_count, StackArgumentOrder stack_order, int register_parameter_count, const Register * registers, const DoubleRegister * double_registers, const Register * return_registers, const DoubleRegister * return_double_registers)
Definition at line 39 of file interface-descriptors.cc.
                                                   {
  DCHECK(!IsInitializedTypes());
#ifdef DEBUG
  CheckRegisterConfiguration(register_parameter_count, registers,
                             double_registers);
  CheckRegisterConfiguration(return_count, return_registers,
                             return_double_registers);
#endif
  flags_ = flags;
  tag_ = tag;
  sandboxing_mode_ = sandboxing_mode;
  stack_order_ = stack_order;
  return_count_ = return_count;
  param_count_ = parameter_count;
  register_param_count_ = register_parameter_count;
  // The caller owns the the registers array, so we just set the pointer.
  register_params_ = registers;
  double_register_params_ = double_registers;
  register_returns_ = return_registers;
  double_register_returns_ = return_double_registers;
}
References v8::internal::DCHECK(), double_register_params_, double_register_returns_, flags(), flags_, IsInitializedTypes(), param_count_, register_param_count_, register_params_, register_returns_, return_count(), return_count_, sandboxing_mode(), sandboxing_mode_, stack_order(), stack_order_, tag(), and tag_.
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::Initialize().
InitializeTypes()
void v8::internal::CallInterfaceDescriptorData::InitializeTypes (const MachineType * machine_types, int machine_types_length)
Definition at line 69 of file interface-descriptors.cc.
                                                                {
  DCHECK(IsInitializedRegisters());
  const int types_length = return_count_ + param_count_;
  // Machine types are either fully initialized or null.
  if (machine_types == nullptr) {
    machine_types_ =
        NewArray<MachineType>(types_length, MachineType::AnyTagged());
  } else {
    DCHECK_EQ(machine_types_length, types_length);
    machine_types_ = NewArray<MachineType>(types_length);
    for (int i = 0; i < types_length; i++) machine_types_[i] = machine_types[i];
  }
  if (!(flags_ & kNoStackScan)) DCHECK(AllStackParametersAreTagged());
}
References v8::internal::MachineType::AnyTagged(), v8::internal::DCHECK(), DCHECK_EQ, flags_, IsInitializedRegisters(), kNoStackScan, machine_types_, param_count_, and return_count_.
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::InitializeTypes().
IsInitialized()
bool v8::internal::CallInterfaceDescriptorData::IsInitialized () const [inline]
Definition at line 227 of file interface-descriptors.h.
                             {
    return IsInitializedRegisters() && IsInitializedTypes();
  }
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::Initialize().
IsInitializedRegisters()
bool v8::internal::CallInterfaceDescriptorData::IsInitializedRegisters () const [inline], [private]
Definition at line 266 of file interface-descriptors.h.
                                      {
    const bool initialized =
        return_count_ != kUninitializedCount &&
        param_count_ != kUninitializedCount &&
        (register_param_count_ == 0 || register_params_ != nullptr);
    // Register initialization happens before type initialization.
    return initialized;
  }
Referenced by InitializeTypes().
IsInitializedTypes()
bool v8::internal::CallInterfaceDescriptorData::IsInitializedTypes () const [inline], [private]
Definition at line 274 of file interface-descriptors.h.
                                  {
    const bool initialized = machine_types_ != nullptr;
    // Register initialization happens before type initialization.
    return initialized;
  }
Referenced by InitializeRegisters().
operator=()
CallInterfaceDescriptorData& v8::internal::CallInterfaceDescriptorData::operator= (const CallInterfaceDescriptorData &) [delete]
param_count()
int v8::internal::CallInterfaceDescriptorData::param_count () const [inline]
Definition at line 235 of file interface-descriptors.h.
{ return param_count_; }
param_type()
MachineType v8::internal::CallInterfaceDescriptorData::param_type (int index) const [inline]
Definition at line 249 of file interface-descriptors.h.
                                          {
    DCHECK_LT(index, param_count_);
    return machine_types_[return_count_ + index];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::CallInterfaceDescriptor::CheckFloatingPointParameters().
register_param()
Register v8::internal::CallInterfaceDescriptorData::register_param (int index) const [inline]
Definition at line 237 of file interface-descriptors.h.
{ return register_params_[index]; }
References v8::internal::index.
Referenced by v8::internal::CallInterfaceDescriptor::CheckFloatingPointParameters().
register_param_count()
int v8::internal::CallInterfaceDescriptorData::register_param_count () const [inline]
Definition at line 236 of file interface-descriptors.h.
{ return register_param_count_; }
Referenced by v8::internal::CallInterfaceDescriptor::CheckFloatingPointParameters().
register_return()
Register v8::internal::CallInterfaceDescriptorData::register_return (int index) const [inline]
Definition at line 241 of file interface-descriptors.h.
{ return register_returns_[index]; }
References v8::internal::index.
Reset()
void v8::internal::CallInterfaceDescriptorData::Reset ()
Definition at line 99 of file interface-descriptors.cc.
                                        {
  delete[] machine_types_;
  machine_types_ = nullptr;
  register_params_ = nullptr;
  double_register_params_ = nullptr;
  register_returns_ = nullptr;
  double_register_returns_ = nullptr;
}
References double_register_params_, double_register_returns_, machine_types_, register_params_, and register_returns_.
RestrictAllocatableRegisters()
void v8::internal::CallInterfaceDescriptorData::RestrictAllocatableRegisters (const Register * registers, size_t num) [inline]
Definition at line 255 of file interface-descriptors.h.
                                                                           {
    DCHECK(allocatable_registers_.is_empty());
    for (size_t i = 0; i < num; ++i) {
      allocatable_registers_.set(registers[i]);
    }
    DCHECK(!allocatable_registers_.is_empty());
  }
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::Initialize().
return_count()
int v8::internal::CallInterfaceDescriptorData::return_count () const [inline]
Definition at line 234 of file interface-descriptors.h.
{ return return_count_; }
Referenced by InitializeRegisters().
return_type()
MachineType v8::internal::CallInterfaceDescriptorData::return_type (int index) const [inline]
Definition at line 245 of file interface-descriptors.h.
                                           {
    DCHECK_LT(index, return_count_);
    return machine_types_[index];
  }
References DCHECK_LT, and v8::internal::index.
sandboxing_mode()
CodeSandboxingMode v8::internal::CallInterfaceDescriptorData::sandboxing_mode () const [inline]
Definition at line 233 of file interface-descriptors.h.
{ return sandboxing_mode_; }
Referenced by InitializeRegisters().
stack_order()
StackArgumentOrder v8::internal::CallInterfaceDescriptorData::stack_order () const [inline]
Definition at line 253 of file interface-descriptors.h.
{ return stack_order_; }
Referenced by InitializeRegisters().
tag()
CodeEntrypointTag v8::internal::CallInterfaceDescriptorData::tag () const [inline]
Definition at line 232 of file interface-descriptors.h.
{ return tag_; }
Referenced by InitializeRegisters().
Member Data Documentation
allocatable_registers_
RegList v8::internal::CallInterfaceDescriptorData::allocatable_registers_ [private]
Definition at line 294 of file interface-descriptors.h.
double_register_params_
const DoubleRegister* v8::internal::CallInterfaceDescriptorData::double_register_params_ = nullptr [private]
Definition at line 303 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and Reset().
double_register_returns_
const DoubleRegister* v8::internal::CallInterfaceDescriptorData::double_register_returns_ = nullptr [private]
Definition at line 305 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and Reset().
flags_
Flags v8::internal::CallInterfaceDescriptorData::flags_ = kNoFlags [private]
Definition at line 287 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and InitializeTypes().
kUninitializedCount
constexpr int v8::internal::CallInterfaceDescriptorData::kUninitializedCount = -1 [static], [constexpr]
Definition at line 194 of file interface-descriptors.h.
machine_types_
MachineType* v8::internal::CallInterfaceDescriptorData::machine_types_ = nullptr [private]
Definition at line 306 of file interface-descriptors.h.
Referenced by InitializeTypes(), and Reset().
param_count_
int v8::internal::CallInterfaceDescriptorData::param_count_ = kUninitializedCount [private]
Definition at line 286 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and InitializeTypes().
register_param_count_
int v8::internal::CallInterfaceDescriptorData::register_param_count_ = kUninitializedCount [private]
Definition at line 284 of file interface-descriptors.h.
Referenced by InitializeRegisters().
register_params_
const Register* v8::internal::CallInterfaceDescriptorData::register_params_ = nullptr [private]
Definition at line 302 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and Reset().
register_returns_
const Register* v8::internal::CallInterfaceDescriptorData::register_returns_ = nullptr [private]
Definition at line 304 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and Reset().
return_count_
int v8::internal::CallInterfaceDescriptorData::return_count_ = kUninitializedCount [private]
Definition at line 285 of file interface-descriptors.h.
Referenced by InitializeRegisters(), and InitializeTypes().
sandboxing_mode_
CodeSandboxingMode v8::internal::CallInterfaceDescriptorData::sandboxing_mode_ = CodeSandboxingMode::kSandboxed [private]
Definition at line 289 of file interface-descriptors.h.
Referenced by InitializeRegisters().
stack_order_
StackArgumentOrder v8::internal::CallInterfaceDescriptorData::stack_order_ = StackArgumentOrder::kDefault [private]
Definition at line 290 of file interface-descriptors.h.
Referenced by InitializeRegisters().
tag_
CodeEntrypointTag v8::internal::CallInterfaceDescriptorData::tag_ = kDefaultCodeEntrypointTag [private]
Definition at line 288 of file interface-descriptors.h.
Referenced by InitializeRegisters().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors.cc