v8::internal::maglev::Int32ToBoolean Class Reference
#include <maglev-ir.h>
Public Member Functions
Int32ToBoolean (uint64_t bitfield, bool flip)
Input & value ()
constexpr bool flip () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kInt32}
Private Types
using Base = FixedInputValueNodeT< 1, Int32ToBoolean >
using FlipBitField = NextBitField< bool, 1 >
Additional Inherited Members
Detailed Description
Definition at line 3321 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Int32ToBoolean::Base = FixedInputValueNodeT<1, Int32ToBoolean> [private]
Definition at line 3322 of file maglev-ir.h.
FlipBitField
using v8::internal::maglev::Int32ToBoolean::FlipBitField = NextBitField<bool, 1> [private]
Definition at line 3341 of file maglev-ir.h.
Constructor & Destructor Documentation
Int32ToBoolean()
v8::internal::maglev::Int32ToBoolean::Int32ToBoolean (uint64_t bitfield, bool flip) [inline], [explicit]
Definition at line 3325 of file maglev-ir.h.
      : Base(FlipBitField::update(bitfield, flip)) {}
Member Function Documentation
flip()
constexpr bool v8::internal::maglev::Int32ToBoolean::flip () const [inline], [constexpr]
Definition at line 3332 of file maglev-ir.h.
{ return FlipBitField::decode(bitfield()); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), options(), and PrintParams().
GenerateCode()
void v8::internal::maglev::Int32ToBoolean::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::Int32ToBoolean::options () const [inline]
Definition at line 3338 of file maglev-ir.h.
{ return std::tuple{flip()}; }
References flip().
PrintParams()
void v8::internal::maglev::Int32ToBoolean::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8323 of file maglev-ir.cc.
                                                                            {
  if (flip()) {
    os << "(flipped)";
  }
}
References flip().
SetValueLocationConstraints()
void v8::internal::maglev::Int32ToBoolean::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::Int32ToBoolean::value () [inline]
Definition at line 3330 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::Int32ToBoolean::kInputTypes {ValueRepresentation::kInt32} [static], [constexpr]
Definition at line 3328 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc