v8::internal::JSSynchronizationPrimitive Class Reference
#include <js-atomics-synchronization.h>
Classes
class BodyDescriptor
Public Member Functions
Tagged< Object > NumWaitersForTesting (Isolate *requester)
void SetNullWaiterQueueHead ()
Static Public Member Functions
static void IsolateDeinit (Isolate *isolate)
Static Public Attributes
static constexpr int kEndOfTaggedFieldsOffset = JSObject::kHeaderSize
Protected Types
using StateT = uint32_t
using HasWaitersField = base::BitField< bool, 0, 1 >
using IsWaiterQueueLockedField = HasWaitersField::Next< bool, 1 >
template<class T , int size>
using NextBitField = IsWaiterQueueLockedField::Next< T, size >
using DequeueMatcher = std::function< bool(WaiterQueueNode *)>
Protected Member Functions
std::atomic< StateT > * AtomicStatePtr ()
WaiterQueueNode * DestructivelyGetWaiterQueueHead (Isolate *requester)
StateT SetWaiterQueueHead (Isolate *requester, WaiterQueueNode *waiter_head, StateT new_state)
Static Protected Member Functions
static void SetWaiterQueueStateOnly (std::atomic< StateT > *state, StateT new_state)
static bool TryLockWaiterQueueExplicit (std::atomic< StateT > *state, StateT &expected)
Static Protected Attributes
static constexpr StateT kEmptyState = 0
static constexpr StateT kWaiterQueueMask
Private Member Functions
WaiterQueueNode ** waiter_queue_head_location () const
Static Private Member Functions
static void CleanupAsyncWaiterLists (Isolate *isolate, DequeueMatcher matcher)
Friends
class WaiterQueueLockGuard
Detailed Description
Definition at line 43 of file js-atomics-synchronization.h.
Member Typedef Documentation
DequeueMatcher
using v8::internal::JSSynchronizationPrimitive::DequeueMatcher = std::function<bool(WaiterQueueNode*)> [protected]
Definition at line 101 of file js-atomics-synchronization.h.
HasWaitersField
using v8::internal::JSSynchronizationPrimitive::HasWaitersField = base::BitField<bool, 0, 1> [protected]
Definition at line 70 of file js-atomics-synchronization.h.
IsWaiterQueueLockedField
using v8::internal::JSSynchronizationPrimitive::IsWaiterQueueLockedField = HasWaitersField::Next<bool, 1> [protected]
Definition at line 74 of file js-atomics-synchronization.h.
NextBitField
template<class T , int size>
using v8::internal::JSSynchronizationPrimitive::NextBitField = IsWaiterQueueLockedField::Next<T, size> [protected]
Definition at line 77 of file js-atomics-synchronization.h.
StateT
using v8::internal::JSSynchronizationPrimitive::StateT = uint32_t [protected]
Definition at line 58 of file js-atomics-synchronization.h.
Member Function Documentation
AtomicStatePtr()
std::atomic< JSSynchronizationPrimitive::StateT > * v8::internal::JSSynchronizationPrimitive::AtomicStatePtr () [inline], [protected]
Definition at line 28 of file js-atomics-synchronization-inl.h.
                                           {
  StateT* state_ptr = reinterpret_cast<StateT*>(field_address(kStateOffset));
  DCHECK(IsAligned(reinterpret_cast<uintptr_t>(state_ptr), sizeof(StateT)));
  return base::AsAtomicPtr(state_ptr);
}
References v8::base::AsAtomicPtr(), v8::internal::DCHECK(), and IsAligned().
Referenced by DestructivelyGetWaiterQueueHead(), NumWaitersForTesting(), and SetWaiterQueueHead().
CleanupAsyncWaiterLists()
void v8::internal::JSSynchronizationPrimitive::CleanupAsyncWaiterLists (Isolate * isolate, DequeueMatcher matcher) [static], [private]
Definition at line 426 of file js-atomics-synchronization.cc.
                                              {
  DisallowGarbageCollection no_gc;
  std::list<std::unique_ptr<WaiterQueueNode>>& async_waiter_queue_nodes_list =
      isolate->async_waiter_queue_nodes();
  if (!async_waiter_queue_nodes_list.empty()) {
    // There is no allocation in the following code, so there shouldn't be any
    // GC, but we use a HandleScope to dereference the global handles.
    HandleScope handle_scope(isolate);
    auto it = async_waiter_queue_nodes_list.begin();
    while (it != async_waiter_queue_nodes_list.end()) {
      WaiterQueueNode* async_node = it->get();
      if (!matcher(async_node)) {
        it++;
        continue;
      }
      async_node->CleanupMatchingAsyncWaiters(matcher);
      it = async_waiter_queue_nodes_list.erase(it);
    }
  }
}
References v8::internal::Isolate::async_waiter_queue_nodes(), v8::internal::detail::WaiterQueueNode::CleanupMatchingAsyncWaiters(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by IsolateDeinit().
DestructivelyGetWaiterQueueHead()
WaiterQueueNode * v8::internal::JSSynchronizationPrimitive::DestructivelyGetWaiterQueueHead (Isolate * requester) [inline], [protected]
Definition at line 57 of file js-atomics-synchronization-inl.h.
                        {
  if (V8_UNLIKELY(DEBUG_BOOL)) {
    StateT state = AtomicStatePtr()->load(std::memory_order_relaxed);
    DCHECK(IsWaiterQueueLockedField::decode(state));
    USE(state);
  }
#if V8_COMPRESS_POINTERS
  ExternalPointerHandle handle =
      base::AsAtomic32::Relaxed_Load(waiter_queue_head_handle_location());
  if (handle == kNullExternalPointerHandle) return nullptr;
  // Clear external pointer after decoding as a safeguard, no other thread
  // should be trying to access though the same non-null handle.
  WaiterQueueNode* waiter_head = reinterpret_cast<WaiterQueueNode*>(
      requester->shared_external_pointer_table().Exchange(handle, kNullAddress,
                                                          kWaiterQueueNodeTag));
  return waiter_head;
#else
  return base::AsAtomicPointer::Relaxed_Load(waiter_queue_head_location());
#endif // V8_COMPRESS_POINTERS
}
References AtomicStatePtr(), v8::internal::DCHECK(), DEBUG_BOOL, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::handle(), v8::internal::kNullAddress, v8::internal::kNullExternalPointerHandle, v8::internal::kWaiterQueueNodeTag, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), USE, V8_UNLIKELY, and waiter_queue_head_location().
Referenced by NumWaitersForTesting().
IsolateDeinit()
void v8::internal::JSSynchronizationPrimitive::IsolateDeinit (Isolate * isolate) [static]
Definition at line 420 of file js-atomics-synchronization.cc.
                                                               {
  CleanupAsyncWaiterLists(isolate, [=](WaiterQueueNode* waiter) {
    return waiter->IsSameIsolateForAsyncCleanup(isolate);
  });
}
References CleanupAsyncWaiterLists(), and v8::internal::detail::WaiterQueueNode::IsSameIsolateForAsyncCleanup().
Referenced by v8::internal::Isolate::Deinit().
NumWaitersForTesting()
Tagged< Object > v8::internal::JSSynchronizationPrimitive::NumWaitersForTesting (Isolate * requester)
Definition at line 471 of file js-atomics-synchronization.cc.
                        {
  DisallowGarbageCollection no_gc;
  std::atomic<StateT>* state = AtomicStatePtr();
  StateT current_state = state->load(std::memory_order_acquire);
  // There are no waiters.
  if (!HasWaitersField::decode(current_state)) return Smi::FromInt(0);
  int num_waiters;
  {
    // If this is counting the number of waiters on a mutex, the js mutex
    // can be taken by another thread without acquiring the queue lock. We
    // handle the state manually to release the queue lock without changing the
    // "is locked" bit.
    while (!TryLockWaiterQueueExplicit(state, current_state)) {
      YIELD_PROCESSOR;
    }
    if (!HasWaitersField::decode(current_state)) {
      // The queue was emptied while waiting for the queue lock.
      SetWaiterQueueStateOnly(state, kEmptyState);
      return Smi::FromInt(0);
    }
    // Get the waiter queue head.
    WaiterQueueNode* waiter_head = DestructivelyGetWaiterQueueHead(requester);
    DCHECK_NOT_NULL(waiter_head);
    num_waiters = WaiterQueueNode::LengthFromHead(waiter_head);
    // Release the queue lock and reinstall the same queue head by creating a
    // new state.
    DCHECK_EQ(state->load(),
              IsWaiterQueueLockedField::update(current_state, true));
    StateT new_state = SetWaiterQueueHead(requester, waiter_head, kEmptyState);
    new_state = IsWaiterQueueLockedField::update(new_state, false);
    SetWaiterQueueStateOnly(state, new_state);
  }
  return Smi::FromInt(num_waiters);
}
References AtomicStatePtr(), DCHECK_EQ, DCHECK_NOT_NULL, v8::base::BitField< T, shift, size, U >::decode(), DestructivelyGetWaiterQueueHead(), v8::internal::Smi::FromInt(), kEmptyState, v8::internal::detail::WaiterQueueNode::LengthFromHead(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SetWaiterQueueHead(), SetWaiterQueueStateOnly(), TryLockWaiterQueueExplicit(), v8::base::BitField< T, shift, size, U >::update(), and YIELD_PROCESSOR.
SetNullWaiterQueueHead()
void v8::internal::JSSynchronizationPrimitive::SetNullWaiterQueueHead () [inline]
Definition at line 34 of file js-atomics-synchronization-inl.h.
                                                        {
#if V8_COMPRESS_POINTERS
  base::AsAtomic32::Relaxed_Store(waiter_queue_head_handle_location(),
                                  kNullExternalPointerHandle);
#else
  base::AsAtomicPointer::Relaxed_Store(waiter_queue_head_location(), nullptr);
#endif // V8_COMPRESS_POINTERS
}
References v8::internal::kNullExternalPointerHandle, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and waiter_queue_head_location().
SetWaiterQueueHead()
JSSynchronizationPrimitive::StateT v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead (Isolate * requester, WaiterQueueNode * waiter_head, StateT new_state) [inline], [protected]
Definition at line 80 of file js-atomics-synchronization-inl.h.
                                                                 {
  if (V8_UNLIKELY(DEBUG_BOOL)) {
    StateT state = AtomicStatePtr()->load(std::memory_order_relaxed);
    DCHECK(IsWaiterQueueLockedField::decode(state));
    USE(state);
  }
#if V8_COMPRESS_POINTERS
  ExternalPointerHandle handle =
      base::AsAtomic32::Relaxed_Load(waiter_queue_head_handle_location());
  if (waiter_head) {
    new_state = HasWaitersField::update(new_state, true);
    ExternalPointerTable& table = requester->shared_external_pointer_table();
    if (handle == kNullExternalPointerHandle) {
      handle = table.AllocateAndInitializeEntry(
          requester->shared_external_pointer_space(),
          reinterpret_cast<Address>(waiter_head), kWaiterQueueNodeTag);
      // Use a Release_Store to ensure that the store of the pointer into the
      // table is not reordered after the store of the handle. Otherwise, other
      // threads may access an uninitialized table entry and crash.
      base::AsAtomic32::Release_Store(waiter_queue_head_handle_location(),
                                      handle);
      EXTERNAL_POINTER_WRITE_BARRIER(*this, kWaiterQueueHeadOffset,
                                     kWaiterQueueNodeTag);
      return new_state;
    }
    if (DEBUG_BOOL) {
      Address old = requester->shared_external_pointer_table().Exchange(
          handle, reinterpret_cast<Address>(waiter_head), kWaiterQueueNodeTag);
      DCHECK_EQ(kNullAddress, old);
      USE(old);
    } else {
      requester->shared_external_pointer_table().Set(
          handle, reinterpret_cast<Address>(waiter_head), kWaiterQueueNodeTag);
    }
  } else {
    new_state = HasWaitersField::update(new_state, false);
    if (handle) {
      requester->shared_external_pointer_table().Set(handle, kNullAddress,
                                                     kWaiterQueueNodeTag);
    }
  }
#else
  new_state = HasWaitersField::update(new_state, waiter_head);
  base::AsAtomicPointer::Relaxed_Store(waiter_queue_head_location(),
                                       waiter_head);
#endif // V8_COMPRESS_POINTERS
  return new_state;
}
References AtomicStatePtr(), v8::internal::DCHECK(), DCHECK_EQ, DEBUG_BOOL, v8::base::BitField< T, shift, size, U >::decode(), EXTERNAL_POINTER_WRITE_BARRIER, v8::internal::handle(), v8::internal::kNullAddress, v8::internal::kNullExternalPointerHandle, v8::internal::kWaiterQueueNodeTag, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), v8::base::BitField< T, shift, size, U >::update(), USE, V8_UNLIKELY, and waiter_queue_head_location().
Referenced by NumWaitersForTesting().
SetWaiterQueueStateOnly()
void v8::internal::JSSynchronizationPrimitive::SetWaiterQueueStateOnly (std::atomic< StateT > * state, StateT new_state) [static], [protected]
Definition at line 459 of file js-atomics-synchronization.cc.
                                                {
  // Set the new state changing only the waiter queue bits.
  DCHECK_EQ(new_state & ~kWaiterQueueMask, 0);
  StateT expected = state->load(std::memory_order_relaxed);
  StateT desired;
  do {
    desired = new_state | (expected & ~kWaiterQueueMask);
  } while (!state->compare_exchange_weak(
      expected, desired, std::memory_order_release, std::memory_order_relaxed));
}
References DCHECK_EQ, and kWaiterQueueMask.
Referenced by NumWaitersForTesting().
TryLockWaiterQueueExplicit()
bool v8::internal::JSSynchronizationPrimitive::TryLockWaiterQueueExplicit (std::atomic< StateT > * state, StateT & expected) [static], [protected]
Definition at line 449 of file js-atomics-synchronization.cc.
                                                {
  // Try to acquire the queue lock.
  expected = IsWaiterQueueLockedField::update(expected, false);
  return state->compare_exchange_weak(
      expected, IsWaiterQueueLockedField::update(expected, true),
      std::memory_order_acquire, std::memory_order_relaxed);
}
References v8::base::BitField< T, shift, size, U >::update().
Referenced by NumWaitersForTesting(), and v8::internal::detail::WaiterQueueLockGuard::WaiterQueueLockGuard().
waiter_queue_head_location()
WaiterQueueNode ** v8::internal::JSSynchronizationPrimitive::waiter_queue_head_location () const [inline], [private]
Definition at line 50 of file js-atomics-synchronization-inl.h.
          {
  Address location = field_address(kWaiterQueueHeadOffset);
  return reinterpret_cast<WaiterQueueNode**>(location);
}
Referenced by DestructivelyGetWaiterQueueHead(), SetNullWaiterQueueHead(), and SetWaiterQueueHead().
Friends And Related Function Documentation
WaiterQueueLockGuard
friend class WaiterQueueLockGuard [friend]
Definition at line 108 of file js-atomics-synchronization.h.
Member Data Documentation
kEmptyState
constexpr StateT v8::internal::JSSynchronizationPrimitive::kEmptyState = 0 [static], [constexpr], [protected]
Definition at line 103 of file js-atomics-synchronization.h.
Referenced by NumWaitersForTesting().
kEndOfTaggedFieldsOffset
constexpr int v8::internal::JSSynchronizationPrimitive::kEndOfTaggedFieldsOffset = JSObject::kHeaderSize [static], [constexpr]
Definition at line 48 of file js-atomics-synchronization.h.
Referenced by v8::internal::JSSynchronizationPrimitive::BodyDescriptor::IterateBody().
kWaiterQueueMask
constexpr StateT v8::internal::JSSynchronizationPrimitive::kWaiterQueueMask [static], [constexpr], [protected]
Initial value:
=
      base::BitFieldUnion<HasWaitersField, IsWaiterQueueLockedField>::kMask
Definition at line 104 of file js-atomics-synchronization.h.
Referenced by SetWaiterQueueStateOnly().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.h
/mnt/V8SourceCode/src/objects/js-atomics-synchronization-inl.h
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.cc