v8::internal::Version Class Reference
#include <version.h>
Static Public Member Functions
static int GetMajor ()
static int GetMinor ()
static int GetBuild ()
static int GetPatch ()
static const char * GetEmbedder ()
static bool IsCandidate ()
static uint32_t Hash ()
static void GetString (base::Vector< char > str)
static void GetSONAME (base::Vector< char > str)
static const char * GetVersion ()
Static Private Attributes
static int major_ = V8_MAJOR_VERSION
static int minor_ = V8_MINOR_VERSION
static int build_ = V8_BUILD_NUMBER
static int patch_ = V8_PATCH_LEVEL
static const char * embedder_ = V8_EMBEDDER_STRING
static bool candidate_ = (V8_IS_CANDIDATE_VERSION != 0)
static const char * soname_ = SONAME
static const char * version_string_ = V8_VERSION_STRING
Friends
void SetVersion (int major, int minor, int build, int patch, const char *embedder, bool candidate, const char *soname)
Detailed Description
Definition at line 21 of file version.h.
Member Function Documentation
GetBuild()
static int v8::internal::Version::GetBuild () [inline], [static]
Definition at line 26 of file version.h.
{ return build_; }
Referenced by GetSONAME(), GetString(), and v8::internal::LogFile::WriteLogHeader().
GetEmbedder()
static const char* v8::internal::Version::GetEmbedder () [inline], [static]
Definition at line 28 of file version.h.
{ return embedder_; }
Referenced by GetSONAME(), GetString(), and v8::internal::LogFile::WriteLogHeader().
GetMajor()
static int v8::internal::Version::GetMajor () [inline], [static]
Definition at line 24 of file version.h.
{ return major_; }
Referenced by GetSONAME(), GetString(), and v8::internal::LogFile::WriteLogHeader().
GetMinor()
static int v8::internal::Version::GetMinor () [inline], [static]
Definition at line 25 of file version.h.
{ return minor_; }
Referenced by GetSONAME(), GetString(), and v8::internal::LogFile::WriteLogHeader().
GetPatch()
static int v8::internal::Version::GetPatch () [inline], [static]
Definition at line 27 of file version.h.
{ return patch_; }
Referenced by GetSONAME(), GetString(), and v8::internal::LogFile::WriteLogHeader().
GetSONAME()
void v8::internal::Version::GetSONAME (base::Vector< char > str) [static]
Definition at line 41 of file version.cc.
                                            {
  if (soname_ == nullptr || *soname_ == '\0') {
    // Generate generic SONAME if no specific SONAME is defined.
    const char* candidate = IsCandidate() ? "-candidate" : "";
    if (GetPatch() > 0) {
      SNPrintF(str, "libv8-%d.%d.%d.%d%s%s.so", GetMajor(), GetMinor(),
               GetBuild(), GetPatch(), GetEmbedder(), candidate);
    } else {
      SNPrintF(str, "libv8-%d.%d.%d%s%s.so", GetMajor(), GetMinor(), GetBuild(),
               GetEmbedder(), candidate);
    }
  } else {
    // Use specific SONAME.
    SNPrintF(str, "%s", soname_);
  }
}
References GetBuild(), GetEmbedder(), GetMajor(), GetMinor(), GetPatch(), IsCandidate(), v8::base::SNPrintF(), and soname_.
GetString()
void v8::internal::Version::GetString (base::Vector< char > str) [static]
Definition at line 29 of file version.cc.
                                            {
  const char* candidate = IsCandidate() ? " (candidate)" : "";
  if (GetPatch() > 0) {
    base::SNPrintF(str, "%d.%d.%d.%d%s%s", GetMajor(), GetMinor(), GetBuild(),
                   GetPatch(), GetEmbedder(), candidate);
  } else {
    base::SNPrintF(str, "%d.%d.%d%s%s", GetMajor(), GetMinor(), GetBuild(),
                   GetEmbedder(), candidate);
  }
}
References GetBuild(), GetEmbedder(), GetMajor(), GetMinor(), GetPatch(), IsCandidate(), and v8::base::SNPrintF().
Referenced by v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CheckVersion(), v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CreateSnapshotBlob(), and v8::internal::Snapshot::VersionIsValid().
GetVersion()
static const char* v8::internal::Version::GetVersion () [inline], [static]
Definition at line 41 of file version.h.
{ return version_string_; }
Referenced by v8::V8::GetVersion().
Hash()
static uint32_t v8::internal::Version::Hash () [inline], [static]
Definition at line 30 of file version.h.
                         {
    return static_cast<uint32_t>(
        base::hash_combine(major_, minor_, build_, patch_));
  }
References v8::base::hash_combine().
Referenced by v8::ScriptCompiler::CachedDataVersionTag(), v8::internal::SerializedCodeData::SanityCheckWithoutSource(), v8::internal::SerializedCodeData::SerializedCodeData(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
IsCandidate()
static bool v8::internal::Version::IsCandidate () [inline], [static]
Definition at line 29 of file version.h.
{ return candidate_; }
Referenced by GetSONAME(), GetString(), and v8::internal::LogFile::WriteLogHeader().
Friends And Related Function Documentation
SetVersion
void SetVersion (int major, int minor, int build, int patch, const char * embedder, bool candidate, const char * soname) [friend]
Member Data Documentation
build_
int v8::internal::Version::build_ = V8_BUILD_NUMBER [static], [private]
Definition at line 47 of file version.h.
candidate_
bool v8::internal::Version::candidate_ = (V8_IS_CANDIDATE_VERSION != 0) [static], [private]
Definition at line 50 of file version.h.
embedder_
const char * v8::internal::Version::embedder_ = V8_EMBEDDER_STRING [static], [private]
Definition at line 49 of file version.h.
major_
int v8::internal::Version::major_ = V8_MAJOR_VERSION [static], [private]
Definition at line 45 of file version.h.
minor_
int v8::internal::Version::minor_ = V8_MINOR_VERSION [static], [private]
Definition at line 46 of file version.h.
patch_
int v8::internal::Version::patch_ = V8_PATCH_LEVEL [static], [private]
Definition at line 48 of file version.h.
soname_
const char * v8::internal::Version::soname_ = SONAME [static], [private]
Definition at line 51 of file version.h.
Referenced by GetSONAME().
version_string_
const char * v8::internal::Version::version_string_ = V8_VERSION_STRING [static], [private]
Definition at line 52 of file version.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/version.h
/mnt/V8SourceCode/src/utils/version.cc