v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next > Class Template Reference
#include <loop-unrolling-reducer.h>
Public Member Functions
void Bind (Block *new_block)
V< None > REDUCE_INPUT_GRAPH() JSStackCheck (V< None > ig_idx, const JSStackCheckOp &stack_check)
Private Attributes
bool skip_next_stack_check_ = false
const ZoneAbslFlatHashSet< uint32_t > & stack_checks_to_remove_
bool remove_stack_checks_ = !stack_checks_to_remove_.empty()
JSHeapBroker * broker_ = __ data() -> broker()
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >
Definition at line 304 of file loop-unrolling-reducer.h.
Member Function Documentation
Bind()
template<class Next >
void v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::Bind (Block * new_block) [inline]
Definition at line 308 of file loop-unrolling-reducer.h.
                              {
    Next::Bind(new_block);
    if (!remove_stack_checks_) return;
    if (new_block->IsLoop()) {
      const Block* origin = new_block->OriginForBlockEnd();
      if (origin) {
        if (stack_checks_to_remove_.contains(origin->index().id())) {
          skip_next_stack_check_ = true;
        }
      }
    }
  }
References v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::OriginForBlockEnd(), v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::remove_stack_checks_, v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::skip_next_stack_check_, and v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::stack_checks_to_remove_.
JSStackCheck()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::JSStackCheck (V< None > ig_idx, const JSStackCheckOp & stack_check) [inline]
Definition at line 322 of file loop-unrolling-reducer.h.
                                                                              {
    if (skip_next_stack_check_ &&
        stack_check.kind == JSStackCheckOp::Kind::kLoop) {
      skip_next_stack_check_ = false;
      return {};
    }
    return Next::ReduceInputGraphJSStackCheck(ig_idx, stack_check);
  }
References v8::internal::compiler::turboshaft::JSStackCheckOp::kLoop, and v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::skip_next_stack_check_.
Member Data Documentation
broker_
template<class Next >
JSHeapBroker* v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::broker_ = __ data() -> broker() [private]
Definition at line 354 of file loop-unrolling-reducer.h.
remove_stack_checks_
template<class Next >
bool v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::remove_stack_checks_ = !stack_checks_to_remove_.empty() [private]
Definition at line 352 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::Bind().
skip_next_stack_check_
template<class Next >
bool v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::skip_next_stack_check_ = false [private]
Definition at line 345 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::Bind(), and v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::JSStackCheck().
stack_checks_to_remove_
template<class Next >
const ZoneAbslFlatHashSet<uint32_t>& v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::stack_checks_to_remove_ [private]
Initial value:
=
      __ input_graph().stack_checks_to_remove()
Definition at line 350 of file loop-unrolling-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoopStackCheckElisionReducer< Next >::Bind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.h