v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope Class Reference
#include <graph.h>
Public Member Functions
ReplaceScope (OperationBuffer *buffer, OpIndex replaced)
~ReplaceScope ()
ReplaceScope (const ReplaceScope &)=delete
ReplaceScope & operator= (const ReplaceScope &)=delete
Private Attributes
OperationBuffer * buffer_
OpIndex replaced_
OperationStorageSlot * old_end_
uint16_t old_slot_count_
Detailed Description
Definition at line 44 of file graph.h.
Constructor & Destructor Documentation
ReplaceScope() [1/2]
v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::ReplaceScope (OperationBuffer * buffer, OpIndex replaced) [inline]
Definition at line 46 of file graph.h.
        : buffer_(buffer),
          replaced_(replaced),
          old_end_(buffer->end_),
          old_slot_count_(buffer->SlotCount(replaced)) {
      buffer_->end_ = buffer_->Get(replaced);
    }
References buffer_, v8::internal::compiler::turboshaft::OperationBuffer::end_, and v8::internal::compiler::turboshaft::OperationBuffer::Get().
 ReplaceScope()
v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::~ReplaceScope () [inline]
Definition at line 53 of file graph.h.
                    {
      DCHECK_LE(buffer_->SlotCount(replaced_), old_slot_count_);
      buffer_->end_ = old_end_;
      // Preserve the original operation size in case it has become smaller.
      buffer_->operation_sizes_[replaced_.id()] = old_slot_count_;
      buffer_->operation_sizes_[OpIndex(replaced_.offset() +
                                        static_cast<uint32_t>(old_slot_count_) *
                                            sizeof(OperationStorageSlot))
                                    .id() -
                                1] = old_slot_count_;
    }
References buffer_, DCHECK_LE, v8::internal::compiler::turboshaft::OperationBuffer::end_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::OpIndex::offset(), old_end_, old_slot_count_, v8::internal::compiler::turboshaft::OperationBuffer::operation_sizes_, v8::internal::compiler::turboshaft::OpIndex, replaced_, and v8::internal::compiler::turboshaft::OperationBuffer::SlotCount().
ReplaceScope() [2/2]
v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::ReplaceScope (const ReplaceScope &) [delete]
Member Function Documentation
operator=()
ReplaceScope& v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::operator= (const ReplaceScope &) [delete]
Member Data Documentation
buffer_
OperationBuffer* v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::buffer_ [private]
Definition at line 69 of file graph.h.
Referenced by ReplaceScope(), and ~ReplaceScope().
old_end_
OperationStorageSlot* v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::old_end_ [private]
Definition at line 71 of file graph.h.
Referenced by ~ReplaceScope().
old_slot_count_
uint16_t v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::old_slot_count_ [private]
Definition at line 72 of file graph.h.
Referenced by ~ReplaceScope().
replaced_
OpIndex v8::internal::compiler::turboshaft::OperationBuffer::ReplaceScope::replaced_ [private]
Definition at line 70 of file graph.h.
Referenced by ~ReplaceScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/graph.h