v8::internal::compiler::LoadElimination::AbstractElements Class Reference
Classes
struct Element
Public Member Functions
AbstractElements (Zone *zone)
AbstractElements (Node *object, Node *index, Node *value, MachineRepresentation representation, Zone *zone)
AbstractElements const * Extend (Node *object, Node *index, Node *value, MachineRepresentation representation, Zone *zone) const
Node * Lookup (Node *object, Node *index, MachineRepresentation representation) const
AbstractElements const * Kill (Node *object, Node *index, Zone *zone) const
bool Equals (AbstractElements const *that) const
AbstractElements const * Merge (AbstractElements const *that, Zone *zone) const
void Print () const
Private Attributes
Element elements_ [kMaxTrackedElements]
size_t next_index_ = 0
Detailed Description
Definition at line 51 of file load-elimination.h.
Constructor & Destructor Documentation
AbstractElements() [1/2]
v8::internal::compiler::LoadElimination::AbstractElements::AbstractElements (Zone * zone) [inline], [explicit]
Definition at line 53 of file load-elimination.h.
                                          {
      for (size_t i = 0; i < arraysize(elements_); ++i) {
        elements_[i] = Element();
      }
    }
References arraysize, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
AbstractElements() [2/2]
v8::internal::compiler::LoadElimination::AbstractElements::AbstractElements (Node * object, Node * index, Node * value, MachineRepresentation representation, Zone * zone) [inline]
Definition at line 58 of file load-elimination.h.
        : AbstractElements(zone) {
      elements_[next_index_++] = Element(object, index, value, representation);
    }
References v8::internal::index, and v8::internal::value.
Member Function Documentation
Equals()
bool v8::internal::compiler::LoadElimination::AbstractElements::Equals (AbstractElements const * that) const
Definition at line 193 of file load-elimination.cc.
                                        {
  if (this == that) return true;
  for (size_t i = 0; i < arraysize(elements_); ++i) {
    Element this_element = this->elements_[i];
    if (this_element.object == nullptr) continue;
    for (size_t j = 0;; ++j) {
      if (j == arraysize(elements_)) return false;
      Element that_element = that->elements_[j];
      if (this_element.object == that_element.object &&
          this_element.index == that_element.index &&
          this_element.value == that_element.value) {
        break;
      }
    }
  }
  for (size_t i = 0; i < arraysize(elements_); ++i) {
    Element that_element = that->elements_[i];
    if (that_element.object == nullptr) continue;
    for (size_t j = 0;; ++j) {
      if (j == arraysize(elements_)) return false;
      Element this_element = this->elements_[j];
      if (that_element.object == this_element.object &&
          that_element.index == this_element.index &&
          that_element.value == this_element.value) {
        break;
      }
    }
  }
  return true;
}
References arraysize, elements_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::LoadElimination::AbstractElements::Element::index, v8::internal::compiler::LoadElimination::AbstractElements::Element::object, and v8::internal::compiler::LoadElimination::AbstractElements::Element::value.
Referenced by v8::internal::compiler::LoadElimination::AbstractState::Equals().
Extend()
AbstractElements const* v8::internal::compiler::LoadElimination::AbstractElements::Extend (Node * object, Node * index, Node * value, MachineRepresentation representation, Zone * zone) const [inline]
Definition at line 64 of file load-elimination.h.
                                                     {
      AbstractElements* that = zone->New<AbstractElements>(*this);
      that->elements_[that->next_index_] =
          Element(object, index, value, representation);
      that->next_index_ = (that->next_index_ + 1) % arraysize(elements_);
      return that;
    }
References arraysize, elements_, v8::internal::index, v8::internal::Zone::New(), next_index_, and v8::internal::value.
Referenced by v8::internal::compiler::LoadElimination::AbstractState::AddElement().
Kill()
LoadElimination::AbstractElements const * v8::internal::compiler::LoadElimination::AbstractElements::Kill (Node * object, Node * index, Zone * zone) const
Definition at line 170 of file load-elimination.cc.
                                                          {
  for (Element const element : this->elements_) {
    if (element.object == nullptr) continue;
    if (MayAlias(object, element.object)) {
      AbstractElements* that = zone->New<AbstractElements>(zone);
      for (Element const element2 : this->elements_) {
        if (element2.object == nullptr) continue;
        DCHECK_NOT_NULL(element2.index);
        DCHECK_NOT_NULL(element2.value);
        if (!MayAlias(object, element2.object) ||
            !NodeProperties::GetType(index).Maybe(
                NodeProperties::GetType(element2.index))) {
          that->elements_[that->next_index_++] = element2;
        }
      }
      that->next_index_ %= arraysize(elements_);
      return that;
    }
  }
  return this;
}
References arraysize, DCHECK_NOT_NULL, elements_, v8::internal::compiler::NodeProperties::GetType(), v8::internal::index, v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias(), v8::internal::compiler::Type::Maybe(), v8::internal::Zone::New(), next_index_, and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::KillElement().
Lookup()
Node * v8::internal::compiler::LoadElimination::AbstractElements::Lookup (Node * object, Node * index, MachineRepresentation representation) const
Definition at line 155 of file load-elimination.cc.
                                                                           {
  for (Element const element : elements_) {
    if (element.object == nullptr) continue;
    DCHECK_NOT_NULL(element.index);
    DCHECK_NOT_NULL(element.value);
    if (MustAlias(object, element.object) && MustAlias(index, element.index) &&
        IsCompatible(representation, element.representation)) {
      return element.value;
    }
  }
  return nullptr;
}
References DCHECK_NOT_NULL, elements_, v8::internal::index, v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsCompatible(), and v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MustAlias().
Merge()
LoadElimination::AbstractElements const * v8::internal::compiler::LoadElimination::AbstractElements::Merge (AbstractElements const * that, Zone * zone) const
Definition at line 226 of file load-elimination.cc.
                                                           {
  if (this->Equals(that)) return this;
  AbstractElements* copy = zone->New<AbstractElements>(zone);
  for (Element const this_element : this->elements_) {
    if (this_element.object == nullptr) continue;
    for (Element const that_element : that->elements_) {
      if (this_element.object == that_element.object &&
          this_element.index == that_element.index &&
          this_element.value == that_element.value) {
        copy->elements_[copy->next_index_++] = this_element;
        break;
      }
    }
  }
  copy->next_index_ %= arraysize(elements_);
  return copy;
}
References arraysize, elements_, v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::compiler::LoadElimination::AbstractElements::Element::index, v8::internal::Zone::New(), next_index_, v8::internal::compiler::LoadElimination::AbstractElements::Element::object, v8::internal::compiler::LoadElimination::AbstractElements::Element::value, and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::Merge().
Print()
void v8::internal::compiler::LoadElimination::AbstractElements::Print () const
Definition at line 245 of file load-elimination.cc.
                                                  {
  for (Element const& element : elements_) {
    if (element.object) {
      PrintF(" #%d:%s @ #%d:%s -> #%d:%s\n", element.object->id(),
             element.object->op()->mnemonic(), element.index->id(),
             element.index->op()->mnemonic(), element.value->id(),
             element.value->op()->mnemonic());
    }
  }
}
References v8::internal::PrintF().
Member Data Documentation
elements_
Element v8::internal::compiler::LoadElimination::AbstractElements::elements_[kMaxTrackedElements] [private]
Definition at line 98 of file load-elimination.h.
Referenced by Equals(), Extend(), Kill(), Lookup(), and Merge().
next_index_
size_t v8::internal::compiler::LoadElimination::AbstractElements::next_index_ = 0 [private]
Definition at line 99 of file load-elimination.h.
Referenced by Extend(), Kill(), and Merge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/load-elimination.h
/mnt/V8SourceCode/src/compiler/load-elimination.cc