cppgc::internal::PageBackend Class Reference
#include <page-memory.h>
Public Member Functions
PageBackend (PageAllocator &normal_page_allocator, PageAllocator &large_page_allocator)
~PageBackend ()
Address TryAllocateNormalPageMemory ()
void FreeNormalPageMemory (Address writeable_base)
Address TryAllocateLargePageMemory (size_t size)
void FreeLargePageMemory (Address writeable_base)
Address Lookup (ConstAddress) const
PageBackend (const PageBackend &)=delete
PageBackend & operator= (const PageBackend &)=delete
void ReleasePooledPages ()
PageMemoryRegionTree & get_page_memory_region_tree_for_testing ()
NormalPageMemoryPool & page_pool ()
Private Attributes
v8::base::Mutex mutex_
PageAllocator & normal_page_allocator_
PageAllocator & large_page_allocator_
NormalPageMemoryPool page_pool_
PageMemoryRegionTree page_memory_region_tree_
std::unordered_map< PageMemoryRegion *, std::unique_ptr< PageMemoryRegion > > normal_page_memory_regions_
std::unordered_map< PageMemoryRegion *, std::unique_ptr< PageMemoryRegion > > large_page_memory_regions_
Detailed Description
Definition at line 136 of file page-memory.h.
Constructor & Destructor Documentation
PageBackend() [1/2]
cppgc::internal::PageBackend::PageBackend (PageAllocator & normal_page_allocator, PageAllocator & large_page_allocator)
Definition at line 197 of file page-memory.cc.
    : normal_page_allocator_(normal_page_allocator),
      large_page_allocator_(large_page_allocator) {}
 PageBackend()
cppgc::internal::PageBackend::~PageBackend () [default]
PageBackend() [2/2]
cppgc::internal::PageBackend::PageBackend (const PageBackend &) [delete]
Member Function Documentation
FreeLargePageMemory()
void cppgc::internal::PageBackend::FreeLargePageMemory (Address writeable_base)
Definition at line 249 of file page-memory.cc.
                                                            {
  v8::base::MutexGuard guard(&mutex_);
  PageMemoryRegion* pmr = page_memory_region_tree_.Lookup(writeable_base);
  page_memory_region_tree_.Remove(pmr);
  auto size = large_page_memory_regions_.erase(pmr);
  USE(size);
  DCHECK_EQ(1u, size);
}
References DCHECK_EQ, large_page_memory_regions_, cppgc::internal::PageMemoryRegionTree::Lookup(), mutex_, page_memory_region_tree_, cppgc::internal::PageMemoryRegionTree::Remove(), size(), and USE.
Referenced by cppgc::internal::LargePage::Destroy().
FreeNormalPageMemory()
void cppgc::internal::PageBackend::FreeNormalPageMemory (Address writeable_base)
Definition at line 226 of file page-memory.cc.
                                                             {
  v8::base::MutexGuard guard(&mutex_);
  auto* pmr = page_memory_region_tree_.Lookup(writeable_base);
  DCHECK_NOT_NULL(pmr);
  page_memory_region_tree_.Remove(pmr);
  page_pool_.Add(pmr);
}
References cppgc::internal::NormalPageMemoryPool::Add(), DCHECK_NOT_NULL, cppgc::internal::PageMemoryRegionTree::Lookup(), mutex_, page_memory_region_tree_, page_pool_, and cppgc::internal::PageMemoryRegionTree::Remove().
Referenced by cppgc::internal::NormalPage::Destroy().
get_page_memory_region_tree_for_testing()
PageMemoryRegionTree& cppgc::internal::PageBackend::get_page_memory_region_tree_for_testing () [inline]
Definition at line 170 of file page-memory.h.
                                                                  {
    return page_memory_region_tree_;
  }
Lookup()
Address cppgc::internal::PageBackend::Lookup (ConstAddress address) const [inline]
Definition at line 209 of file page-memory.h.
                                                      {
  v8::base::MutexGuard guard(&mutex_);
  PageMemoryRegion* pmr = page_memory_region_tree_.Lookup(address);
  return pmr ? pmr->Lookup(address) : nullptr;
}
References cppgc::internal::PageMemoryRegion::Lookup(), cppgc::internal::PageMemoryRegionTree::Lookup(), mutex_, and page_memory_region_tree_.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), and cppgc::internal::ConservativeTracingVisitor::TryTracePointerConservatively().
operator=()
PageBackend& cppgc::internal::PageBackend::operator= (const PageBackend &) [delete]
page_pool()
NormalPageMemoryPool& cppgc::internal::PageBackend::page_pool () [inline]
Definition at line 174 of file page-memory.h.
{ return page_pool_; }
ReleasePooledPages()
void cppgc::internal::PageBackend::ReleasePooledPages ()
Definition at line 258 of file page-memory.cc.
                                     {
  page_pool_.ReleasePooledPages(normal_page_allocator_);
}
References normal_page_allocator_, page_pool_, and cppgc::internal::NormalPageMemoryPool::ReleasePooledPages().
Referenced by cppgc::internal::Sweeper::SweeperImpl::NotifyDone().
TryAllocateLargePageMemory()
Address cppgc::internal::PageBackend::TryAllocateLargePageMemory (size_t size)
Definition at line 234 of file page-memory.cc.
                                                           {
  v8::base::MutexGuard guard(&mutex_);
  auto pmr = CreateLargePageMemoryRegion(large_page_allocator_, size);
  if (!pmr) {
    return nullptr;
  }
  const auto memory_region = pmr->region();
  if (V8_LIKELY(TryUnprotect(large_page_allocator_, memory_region))) {
    page_memory_region_tree_.Add(pmr.get());
    large_page_memory_regions_.emplace(pmr.get(), std::move(pmr));
    return memory_region.base();
  }
  return nullptr;
}
References cppgc::internal::PageMemoryRegionTree::Add(), cppgc::internal::anonymous_namespace{page-memory.cc}::CreateLargePageMemoryRegion(), large_page_allocator_, large_page_memory_regions_, mutex_, page_memory_region_tree_, size(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect(), and V8_LIKELY.
Referenced by cppgc::internal::LargePage::TryCreate().
TryAllocateNormalPageMemory()
Address cppgc::internal::PageBackend::TryAllocateNormalPageMemory ()
Definition at line 204 of file page-memory.cc.
                                                 {
  v8::base::MutexGuard guard(&mutex_);
  if (PageMemoryRegion* cached = page_pool_.Take()) {
    const auto region = cached->region();
    DCHECK_NE(normal_page_memory_regions_.end(),
              normal_page_memory_regions_.find(cached));
    page_memory_region_tree_.Add(cached);
    return region.base();
  }
  auto pmr = CreateNormalPageMemoryRegion(normal_page_allocator_);
  if (!pmr) {
    return nullptr;
  }
  const auto memory_region = pmr->region();
  if (V8_LIKELY(TryUnprotect(normal_page_allocator_, memory_region))) {
    page_memory_region_tree_.Add(pmr.get());
    normal_page_memory_regions_.emplace(pmr.get(), std::move(pmr));
    return memory_region.base();
  }
  return nullptr;
}
References cppgc::internal::PageMemoryRegionTree::Add(), cppgc::internal::anonymous_namespace{page-memory.cc}::CreateNormalPageMemoryRegion(), DCHECK_NE, mutex_, normal_page_allocator_, normal_page_memory_regions_, page_memory_region_tree_, page_pool_, cppgc::internal::NormalPageMemoryPool::Take(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect(), and V8_LIKELY.
Referenced by cppgc::internal::NormalPage::TryCreate().
Member Data Documentation
large_page_allocator_
PageAllocator& cppgc::internal::PageBackend::large_page_allocator_ [private]
Definition at line 180 of file page-memory.h.
Referenced by TryAllocateLargePageMemory().
large_page_memory_regions_
std::unordered_map<PageMemoryRegion*, std::unique_ptr<PageMemoryRegion> > cppgc::internal::PageBackend::large_page_memory_regions_ [private]
Definition at line 192 of file page-memory.h.
Referenced by FreeLargePageMemory(), and TryAllocateLargePageMemory().
mutex_
v8::base::Mutex cppgc::internal::PageBackend::mutex_ [mutable], [private]
Definition at line 178 of file page-memory.h.
Referenced by FreeLargePageMemory(), FreeNormalPageMemory(), Lookup(), TryAllocateLargePageMemory(), and TryAllocateNormalPageMemory().
normal_page_allocator_
PageAllocator& cppgc::internal::PageBackend::normal_page_allocator_ [private]
Definition at line 179 of file page-memory.h.
Referenced by ReleasePooledPages(), and TryAllocateNormalPageMemory().
normal_page_memory_regions_
std::unordered_map<PageMemoryRegion*, std::unique_ptr<PageMemoryRegion> > cppgc::internal::PageBackend::normal_page_memory_regions_ [private]
Definition at line 190 of file page-memory.h.
Referenced by TryAllocateNormalPageMemory().
page_memory_region_tree_
PageMemoryRegionTree cppgc::internal::PageBackend::page_memory_region_tree_ [private]
Definition at line 188 of file page-memory.h.
Referenced by FreeLargePageMemory(), FreeNormalPageMemory(), Lookup(), TryAllocateLargePageMemory(), and TryAllocateNormalPageMemory().
page_pool_
NormalPageMemoryPool cppgc::internal::PageBackend::page_pool_ [private]
Definition at line 187 of file page-memory.h.
Referenced by FreeNormalPageMemory(), ReleasePooledPages(), and TryAllocateNormalPageMemory().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/page-memory.h
/mnt/V8SourceCode/src/heap/cppgc/page-memory.cc