v8::internal::FreeListMany Class Reference
#include <free-list.h>
Public Member Functions
PageMetadata * GetPageForSize (size_t size_in_bytes) override
FreeListMany ()
~FreeListMany () override
V8_WARN_UNUSED_RESULT Tagged< FreeSpace > Allocate (size_t size_in_bytes, size_t *node_size, AllocationOrigin origin) override
Protected Member Functions
FreeListCategoryType SelectFreeListCategoryType (size_t size_in_bytes) override
FRIEND_TEST (SpacesTest, FreeListManySelectFreeListCategoryType)
FRIEND_TEST (SpacesTest, FreeListManyGuaranteedAllocatable)
Static Protected Attributes
static constexpr size_t kMinBlockSize = 3 * kTaggedSize
static constexpr size_t kMaxBlockSize = MutablePageMetadata::kPageSize
static constexpr size_t kPreciseCategoryMaxSize = 256
static constexpr int kNumberOfCategories = 24
static constexpr unsigned int categories_min [kNumberOfCategories]
Additional Inherited Members
Detailed Description
Definition at line 295 of file free-list.h.
Constructor & Destructor Documentation
FreeListMany()
v8::internal::FreeListMany::FreeListMany ()
Definition at line 201 of file free-list.cc.
                           : FreeList(kNumberOfCategories, kMinBlockSize) {
  // Initializing base (FreeList) fields
  categories_ = new FreeListCategory*[number_of_categories_]();
  Reset();
}
References v8::internal::FreeList::categories_, v8::internal::FreeList::number_of_categories_, and v8::internal::FreeList::Reset().
 FreeListMany()
v8::internal::FreeListMany::~FreeListMany () [override]
Definition at line 207 of file free-list.cc.
{ delete[] categories_; }
References v8::internal::FreeList::categories_.
Member Function Documentation
Allocate()
Tagged< FreeSpace > v8::internal::FreeListMany::Allocate (size_t size_in_bytes, size_t * node_size, AllocationOrigin origin) [override], [virtual]
Implements v8::internal::FreeList.
Reimplemented in v8::internal::FreeListManyCachedOrigin, v8::internal::FreeListManyCachedFastPathBase, and v8::internal::FreeListManyCached.
Definition at line 223 of file free-list.cc.
                                                                  {
  DCHECK_GE(kMaxBlockSize, size_in_bytes);
  Tagged<FreeSpace> node;
  FreeListCategoryType type = SelectFreeListCategoryType(size_in_bytes);
  for (int i = type; i < last_category_ && node.is_null(); i++) {
    node = TryFindNodeIn(static_cast<FreeListCategoryType>(i), size_in_bytes,
                         node_size);
  }
  if (node.is_null()) {
    // Searching each element of the last category.
    node = SearchForNodeInList(last_category_, size_in_bytes, node_size);
  }
  if (!node.is_null()) {
    PageMetadata::FromHeapObject(node)->IncreaseAllocatedBytes(*node_size);
  }
  VerifyAvailable();
  return node;
}
References DCHECK_GE, v8::internal::PageMetadata::FromHeapObject(), v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes(), v8::internal::Tagged< HeapObject >::is_null(), kMaxBlockSize, v8::internal::FreeList::last_category_, v8::internal::FreeList::SearchForNodeInList(), SelectFreeListCategoryType(), v8::internal::FreeList::TryFindNodeIn(), v8::internal::tracing::type, and v8::internal::FreeList::VerifyAvailable().
FRIEND_TEST() [1/2]
v8::internal::FreeListMany::FRIEND_TEST (SpacesTest , FreeListManyGuaranteedAllocatable) [protected]
FRIEND_TEST() [2/2]
v8::internal::FreeListMany::FRIEND_TEST (SpacesTest , FreeListManySelectFreeListCategoryType) [protected]
GetPageForSize()
PageMetadata * v8::internal::FreeListMany::GetPageForSize (size_t size_in_bytes) [override], [virtual]
Implements v8::internal::FreeList.
Definition at line 209 of file free-list.cc.
                                                               {
  FreeListCategoryType minimum_category =
      SelectFreeListCategoryType(size_in_bytes);
  PageMetadata* page = nullptr;
  for (int cat = minimum_category + 1; !page && cat <= last_category_; cat++) {
    page = GetPageForCategoryType(cat);
  }
  if (!page) {
    // Might return a page in which |size_in_bytes| will not fit.
    page = GetPageForCategoryType(minimum_category);
  }
  return page;
}
References v8::internal::FreeList::GetPageForCategoryType(), v8::internal::FreeList::last_category_, and SelectFreeListCategoryType().
SelectFreeListCategoryType()
FreeListCategoryType v8::internal::FreeListMany::SelectFreeListCategoryType (size_t size_in_bytes) [inline], [override], [protected], [virtual]
Implements v8::internal::FreeList.
Definition at line 330 of file free-list.h.
                                     {
    if (size_in_bytes <= kPreciseCategoryMaxSize) {
      if (size_in_bytes < categories_min[1]) return 0;
      return static_cast<FreeListCategoryType>(size_in_bytes >> 4) - 1;
    }
    for (int cat = (kPreciseCategoryMaxSize >> 4) - 1; cat < last_category_;
         cat++) {
      if (size_in_bytes < categories_min[cat + 1]) {
        return cat;
      }
    }
    return last_category_;
  }
Referenced by Allocate(), v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), v8::internal::FreeListManyCached::Free(), and GetPageForSize().
Member Data Documentation
categories_min
constexpr unsigned int v8::internal::FreeListMany::categories_min [static], [constexpr], [protected]
Initial value:
= {
      24, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192,
      208, 224, 240, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536}
Definition at line 325 of file free-list.h.
kMaxBlockSize
constexpr size_t v8::internal::FreeListMany::kMaxBlockSize = MutablePageMetadata::kPageSize [static], [constexpr], [protected]
Definition at line 311 of file free-list.h.
Referenced by Allocate(), v8::internal::FreeListManyCached::Allocate(), and v8::internal::FreeListManyCachedFastPathBase::Allocate().
kMinBlockSize
constexpr size_t v8::internal::FreeListMany::kMinBlockSize = 3 * kTaggedSize [static], [constexpr], [protected]
Definition at line 307 of file free-list.h.
kNumberOfCategories
constexpr int v8::internal::FreeListMany::kNumberOfCategories = 24 [static], [constexpr], [protected]
Definition at line 324 of file free-list.h.
kPreciseCategoryMaxSize
constexpr size_t v8::internal::FreeListMany::kPreciseCategoryMaxSize = 256 [static], [constexpr], [protected]
Definition at line 314 of file free-list.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/free-list.h
/mnt/V8SourceCode/src/heap/free-list.cc