v8::internal::compiler::CheckBoundsParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckBoundsParameters (const FeedbackSource &feedback, CheckBoundsFlags flags)
CheckBoundsFlags flags () const
const CheckParameters & check_parameters () const
Private Attributes
CheckParameters check_parameters_
CheckBoundsFlags flags_
Detailed Description
Definition at line 295 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckBoundsParameters()
v8::internal::compiler::CheckBoundsParameters::CheckBoundsParameters (const FeedbackSource & feedback, CheckBoundsFlags flags) [inline]
Definition at line 297 of file simplified-operator.h.
      : check_parameters_(feedback), flags_(flags) {}
Member Function Documentation
check_parameters()
const CheckParameters& v8::internal::compiler::CheckBoundsParameters::check_parameters () const [inline]
Definition at line 301 of file simplified-operator.h.
{ return check_parameters_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), and v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
flags()
CheckBoundsFlags v8::internal::compiler::CheckBoundsParameters::flags () const [inline]
Definition at line 300 of file simplified-operator.h.
{ return flags_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupBoundsCheckFor(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), and v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
Member Data Documentation
check_parameters_
CheckParameters v8::internal::compiler::CheckBoundsParameters::check_parameters_ [private]
Definition at line 304 of file simplified-operator.h.
flags_
CheckBoundsFlags v8::internal::compiler::CheckBoundsParameters::flags_ [private]
Definition at line 305 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h