v8::internal::torque::Scope Class Reference
#include <declarable.h>
Public Member Functions
Scope (Declarable::Kind kind)
std::vector< Declarable * > LookupShallow (const QualifiedName &name)
std::vector< Declarable * > Lookup (const QualifiedName &name)
template<class T >
T * AddDeclarable (const std::string &name, T *declarable)
const SpecializationRequester & GetSpecializationRequester () const
void SetSpecializationRequester (const SpecializationRequester &requester)
Private Attributes
std::unordered_map< std::string, std::vector< Declarable * > > declarations_
SpecializationRequester requester_ = SpecializationRequester::None()
Additional Inherited Members
Detailed Description
Definition at line 172 of file declarable.h.
Constructor & Destructor Documentation
Scope()
v8::internal::torque::Scope::Scope (Declarable::Kind kind) [inline], [explicit]
Definition at line 175 of file declarable.h.
: Declarable(kind) {}
Member Function Documentation
AddDeclarable()
template<class T >
T* v8::internal::torque::Scope::AddDeclarable (const std::string & name, T * declarable) [inline]
Definition at line 196 of file declarable.h.
                                                         {
    declarations_[name].push_back(declarable);
    return declarable;
  }
References declarations_, and v8::internal::name.
Referenced by v8::internal::torque::Declarations::DeclareOperator().
GetSpecializationRequester()
const SpecializationRequester& v8::internal::torque::Scope::GetSpecializationRequester () const [inline]
Definition at line 201 of file declarable.h.
                                                                    {
    return requester_;
  }
References requester_.
Referenced by v8::internal::torque::MessageBuilder::MessageBuilder(), and v8::internal::torque::SpecializationRequester::SpecializationRequester().
Lookup()
std::vector< Declarable * > v8::internal::torque::Scope::Lookup (const QualifiedName & name)
Definition at line 90 of file declarable.cc.
                                                              {
  if (!name.namespace_qualification.empty() &&
      name.namespace_qualification[0].empty()) {
    return GlobalContext::GetDefaultNamespace()->Lookup(
        name.DropFirstNamespaceQualification());
  }
  std::vector<Declarable*> result;
  if (ParentScope()) {
    result = ParentScope()->Lookup(name);
  }
  for (Declarable* declarable : LookupShallow(name)) {
    result.push_back(declarable);
  }
  return result;
}
References v8::internal::torque::GlobalContext::GetDefaultNamespace(), Lookup(), LookupShallow(), v8::internal::name, v8::internal::torque::Declarable::ParentScope(), and v8::base::internal::result.
Referenced by Lookup(), and v8::internal::torque::Declarations::LookupGlobalScope().
LookupShallow()
std::vector<Declarable*> v8::internal::torque::Scope::LookupShallow (const QualifiedName & name) [inline]
Definition at line 177 of file declarable.h.
                                                                  {
    if (!name.HasNamespaceQualification()) return declarations_[name.name];
    Scope* child = nullptr;
    for (Declarable* declarable :
         declarations_[name.namespace_qualification.front()]) {
      if (Scope* scope = Scope::DynamicCast(declarable)) {
        if (child != nullptr) {
          ReportError("ambiguous reference to scope ",
                      name.namespace_qualification.front());
        }
        child = scope;
      }
    }
    if (child == nullptr) return {};
    return child->LookupShallow(name.DropFirstNamespaceQualification());
  }
References declarations_, LookupShallow(), v8::internal::name, and v8::internal::torque::ReportError().
Referenced by Lookup(), and LookupShallow().
SetSpecializationRequester()
void v8::internal::torque::Scope::SetSpecializationRequester (const SpecializationRequester & requester) [inline]
Definition at line 204 of file declarable.h.
                                                                            {
    requester_ = requester;
  }
References requester_.
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
Member Data Documentation
declarations_
std::unordered_map<std::string, std::vector<Declarable*> > v8::internal::torque::Scope::declarations_ [private]
Definition at line 209 of file declarable.h.
Referenced by AddDeclarable(), and LookupShallow().
requester_
SpecializationRequester v8::internal::torque::Scope::requester_ = SpecializationRequester::None() [private]
Definition at line 214 of file declarable.h.
Referenced by GetSpecializationRequester(), and SetSpecializationRequester().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declarable.h
/mnt/V8SourceCode/src/torque/declarable.cc