v8::internal::StoreInArrayLiteralIC Class Reference
#include <ic.h>
Public Member Functions
StoreInArrayLiteralIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot)
MaybeDirectHandle< Object > Store (DirectHandle< JSArray > array, Handle< Object > index, DirectHandle< Object > value)
Additional Inherited Members
Detailed Description
Definition at line 346 of file ic.h.
Constructor & Destructor Documentation
StoreInArrayLiteralIC()
v8::internal::StoreInArrayLiteralIC::StoreInArrayLiteralIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot) [inline]
Definition at line 348 of file ic.h.
      : KeyedStoreIC(isolate, vector, slot,
                     FeedbackSlotKind::kStoreInArrayLiteral) {
    DCHECK(IsStoreInArrayLiteralICKind(kind()));
  }
References v8::internal::DCHECK(), v8::internal::IsStoreInArrayLiteralICKind(), v8::internal::IC::kind(), and v8::internal::kStoreInArrayLiteral.
Member Function Documentation
Store()
MaybeDirectHandle< Object > v8::internal::StoreInArrayLiteralIC::Store (DirectHandle< JSArray > array, Handle< Object > index, DirectHandle< Object > value)
Definition at line 2756 of file ic.cc.
                                {
  DCHECK(!array->map()->IsMapInArrayPrototypeChain(isolate()));
  DCHECK(IsNumber(*index));
  if (!v8_flags.use_ic || state() == NO_FEEDBACK ||
      MigrateDeprecated(isolate(), array)) {
    MAYBE_RETURN_NULL(StoreOwnElement(isolate(), array, index, value));
    TraceIC("StoreInArrayLiteralIC", index);
    return value;
  }
  // TODO(neis): Convert HeapNumber to Smi if possible?
  KeyedAccessStoreMode store_mode = KeyedAccessStoreMode::kInBounds;
  if (IsSmi(*index)) {
    DCHECK_GE(Smi::ToInt(*index), 0);
    uint32_t index32 = static_cast<uint32_t>(Smi::ToInt(*index));
    store_mode = GetStoreMode(array, index32);
  }
  Handle<Map> old_array_map(array->map(), isolate());
  MAYBE_RETURN_NULL(StoreOwnElement(isolate(), array, index, value));
  if (IsSmi(*index)) {
    DCHECK(!old_array_map->is_abandoned_prototype_map());
    UpdateStoreElement(old_array_map, store_mode,
                       handle(array->map(), isolate()));
  } else {
    set_slow_stub_reason("index out of Smi range");
  }
  if (vector_needs_update()) {
    ConfigureVectorState(MEGAMORPHIC, index);
  }
  TraceIC("StoreInArrayLiteralIC", index);
  return value;
}
References v8::internal::IC::ConfigureVectorState(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::anonymous_namespace{ic.cc}::GetStoreMode(), v8::internal::handle(), v8::internal::index, v8::internal::IsNumber(), v8::internal::IC::isolate(), v8::internal::IsSmi(), v8::internal::kInBounds, MAYBE_RETURN_NULL, v8::internal::MEGAMORPHIC, v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated(), v8::internal::NO_FEEDBACK, v8::internal::IC::set_slow_stub_reason(), v8::internal::IC::state(), v8::internal::anonymous_namespace{ic.cc}::StoreOwnElement(), v8::internal::Smi::ToInt(), v8::internal::IC::TraceIC(), v8::internal::KeyedStoreIC::UpdateStoreElement(), v8::internal::v8_flags, v8::internal::value, and v8::internal::IC::vector_needs_update().
Referenced by v8::internal::RUNTIME_FUNCTION().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc