v8::internal::Isolate::ThreadDataTable Class Reference
Classes
struct Hasher
Public Member Functions
ThreadDataTable ()=default
PerIsolateThreadData * Lookup (ThreadId thread_id)
void Insert (PerIsolateThreadData *data)
void Remove (PerIsolateThreadData *data)
void RemoveAllThreads ()
Private Attributes
std::unordered_map< ThreadId, PerIsolateThreadData *, Hasher > table_
Detailed Description
Definition at line 2497 of file isolate.h.
Constructor & Destructor Documentation
ThreadDataTable()
v8::internal::Isolate::ThreadDataTable::ThreadDataTable () [default]
Member Function Documentation
Insert()
void v8::internal::Isolate::ThreadDataTable::Insert (Isolate::PerIsolateThreadData * data)
Definition at line 4007 of file isolate.cc.
                                                                     {
  bool inserted = table_.insert(std::make_pair(data->thread_id_, data)).second;
  CHECK(inserted);
}
References CHECK, and v8::internal::Isolate::PerIsolateThreadData::thread_id_.
Referenced by v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread().
Lookup()
Isolate::PerIsolateThreadData * v8::internal::Isolate::ThreadDataTable::Lookup (ThreadId thread_id)
Definition at line 4000 of file isolate.cc.
                        {
  auto t = table_.find(thread_id);
  if (t == table_.end()) return nullptr;
  return t->second;
}
References v8::internal::Isolate::thread_id().
Referenced by v8::internal::Isolate::DiscardPerThreadDataForThisThread(), v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread(), and v8::internal::Isolate::FindPerThreadDataForThread().
Remove()
void v8::internal::Isolate::ThreadDataTable::Remove (PerIsolateThreadData * data)
Definition at line 4012 of file isolate.cc.
                                                              {
  table_.erase(data->thread_id_);
  delete data;
}
References v8::internal::Isolate::PerIsolateThreadData::thread_id_.
Referenced by v8::internal::Isolate::DiscardPerThreadDataForThisThread().
RemoveAllThreads()
void v8::internal::Isolate::ThreadDataTable::RemoveAllThreads ()
Definition at line 4017 of file isolate.cc.
                                              {
  for (auto& x : table_) {
    delete x.second;
  }
  table_.clear();
}
Referenced by v8::internal::Isolate::Deinit().
Member Data Documentation
table_
std::unordered_map<ThreadId, PerIsolateThreadData*, Hasher> v8::internal::Isolate::ThreadDataTable::table_ [private]
Definition at line 2513 of file isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/isolate.h
/mnt/V8SourceCode/src/execution/isolate.cc