v8::CompileHintsCollector Class Reference
#include <v8-script.h>
Public Member Functions
std::vector< int > GetCompileHints (Isolate *isolate) const
Returns the positions of lazy functions which were compiled and executed.
Detailed Description
Definition at line 341 of file v8-script.h.
Member Function Documentation
GetCompileHints()
std::vector< int > v8::CompileHintsCollector::GetCompileHints (Isolate * isolate) const
Returns the positions of lazy functions which were compiled and executed.
Definition at line 2036 of file api.cc.
                               {
  i::DisallowGarbageCollection no_gc;
  auto script = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::Tagged<i::Object> maybe_array_list =
      script->compiled_lazy_function_positions();
  std::vector<int> result;
  if (!IsUndefined(maybe_array_list, i_isolate)) {
    i::Tagged<i::ArrayList> array_list =
        i::Cast<i::ArrayList>(maybe_array_list);
    result.reserve(array_list->length());
    for (int i = 0; i < array_list->length(); ++i) {
      i::Tagged<i::Object> item = array_list->get(i);
      CHECK(IsSmi(item));
      result.push_back(i::Smi::ToInt(item));
    }
  }
  return result;
}
References CHECK, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsSmi(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::script, and v8::internal::Smi::ToInt().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc