v8::internal::compiler::RawMachineAssembler Class Reference
#include <raw-machine-assembler.h>
Public Types
using CFunctionArg = std::pair< MachineType, Node * >
Public Member Functions
RawMachineAssembler (Isolate *isolate, TFGraph *graph, CallDescriptor *call_descriptor, MachineRepresentation word=MachineType::PointerRepresentation(), MachineOperatorBuilder::Flags flags=MachineOperatorBuilder::Flag::kNoFlags, MachineOperatorBuilder::AlignmentRequirements alignment_requirements=MachineOperatorBuilder::AlignmentRequirements::FullUnalignedAccessSupport())
~RawMachineAssembler ()=default
RawMachineAssembler (const RawMachineAssembler &)=delete
RawMachineAssembler & operator= (const RawMachineAssembler &)=delete
Isolate * isolate () const
TFGraph * graph () const
Zone * zone () const
MachineOperatorBuilder * machine ()
CommonOperatorBuilder * common ()
SimplifiedOperatorBuilder * simplified ()
CallDescriptor * call_descriptor () const
Schedule * ExportForTest ()
TFGraph * ExportForOptimization ()
Node * NullConstant ()
Node * UndefinedConstant ()
Node * PointerConstant (void *value)
Node * IntPtrConstant (intptr_t value)
Node * RelocatableIntPtrConstant (intptr_t value, RelocInfo::Mode rmode)
Node * Int32Constant (int32_t value)
Node * StackSlot (MachineRepresentation rep, int alignment=0)
Node * StackSlot (int size, int alignment)
Node * Int64Constant (int64_t value)
Node * NumberConstant (double value)
Node * Float32Constant (float value)
Node * Float64Constant (double value)
Node * HeapConstant (Handle< HeapObject > object)
Node * ExternalConstant (ExternalReference address)
Node * RelocatableInt32Constant (int32_t value, RelocInfo::Mode rmode)
Node * RelocatableInt64Constant (int64_t value, RelocInfo::Mode rmode)
Node * Projection (int index, Node *a)
Node * Load (MachineType type, Node *base)
Node * Load (MachineType type, Node *base, Node *index)
Node * LoadImmutable (MachineType type, Node *base)
Node * LoadImmutable (MachineType type, Node *base, Node *index)
bool IsMapOffsetConstant (Node *node)
bool IsMapOffsetConstantMinusTag (Node *node)
bool IsMapOffsetConstantMinusTag (int offset)
Node * LoadFromObject (MachineType type, Node *base, Node *offset)
Node * LoadProtectedPointerFromObject (Node *base, Node *offset)
Node * Store (MachineRepresentation rep, Node *base, Node *value, WriteBarrierKind write_barrier)
Node * Store (MachineRepresentation rep, Node *base, Node *index, Node *value, WriteBarrierKind write_barrier)
void StoreToObject (MachineRepresentation rep, Node *object, Node *offset, Node *value, WriteBarrierKind write_barrier)
void OptimizedStoreField (MachineRepresentation rep, Node *object, int offset, Node *value, WriteBarrierKind write_barrier)
void OptimizedStoreIndirectPointerField (Node *object, int offset, IndirectPointerTag tag, Node *value, WriteBarrierKind write_barrier)
void OptimizedStoreMap (Node *object, Node *value, WriteBarrierKind write_barrier=kMapWriteBarrier)
Node * Retain (Node *value)
Node * OptimizedAllocate (Node *size, AllocationType allocation)
Node * UnalignedLoad (MachineType type, Node *base)
Node * UnalignedLoad (MachineType type, Node *base, Node *index)
Node * UnalignedStore (MachineRepresentation rep, Node *base, Node *value)
Node * UnalignedStore (MachineRepresentation rep, Node *base, Node *index, Node *value)
Node * AtomicLoad (AtomicLoadParameters rep, Node *base, Node *index)
Node * AtomicLoad64 (AtomicLoadParameters rep, Node *base, Node *index)
Node * AtomicStore (AtomicStoreParameters params, Node *base, Node *index, Node *value)
Node * AtomicStore64 (AtomicStoreParameters params, Node *base, Node *index, Node *value, Node *value_high)
Node * AtomicCompareExchange (MachineType type, Node *base, Node *index, Node *old_value, Node *new_value)
Node * AtomicCompareExchange64 (Node *base, Node *index, Node *old_value, Node *old_value_high, Node *new_value, Node *new_value_high)
Node * MemoryBarrier (AtomicMemoryOrder order)
Node * WordAnd (Node *a, Node *b)
Node * WordOr (Node *a, Node *b)
Node * WordXor (Node *a, Node *b)
Node * WordShl (Node *a, Node *b)
Node * WordShr (Node *a, Node *b)
Node * WordSar (Node *a, Node *b)
Node * WordSarShiftOutZeros (Node *a, Node *b)
Node * WordRor (Node *a, Node *b)
Node * WordEqual (Node *a, Node *b)
Node * WordNotEqual (Node *a, Node *b)
Node * WordNot (Node *a)
Node * Word32And (Node *a, Node *b)
Node * Word32Or (Node *a, Node *b)
Node * Word32Xor (Node *a, Node *b)
Node * Word32Shl (Node *a, Node *b)
Node * Word32Shr (Node *a, Node *b)
Node * Word32Sar (Node *a, Node *b)
Node * Word32SarShiftOutZeros (Node *a, Node *b)
Node * Word32Ror (Node *a, Node *b)
Node * Word32Clz (Node *a)
Node * Word32Equal (Node *a, Node *b)
Node * Word32NotEqual (Node *a, Node *b)
Node * Word32BitwiseNot (Node *a)
Node * Word32BinaryNot (Node *a)
Node * Word64And (Node *a, Node *b)
Node * Word64Or (Node *a, Node *b)
Node * Word64Xor (Node *a, Node *b)
Node * Word64Shl (Node *a, Node *b)
Node * Word64Shr (Node *a, Node *b)
Node * Word64Sar (Node *a, Node *b)
Node * Word64Ror (Node *a, Node *b)
Node * Word64Clz (Node *a)
Node * Word64Equal (Node *a, Node *b)
Node * Word64NotEqual (Node *a, Node *b)
Node * Word64Not (Node *a)
Node * Int32Add (Node *a, Node *b)
Node * Int32AddWithOverflow (Node *a, Node *b)
Node * Int32Sub (Node *a, Node *b)
Node * Int32SubWithOverflow (Node *a, Node *b)
Node * Int32Mul (Node *a, Node *b)
Node * Int32MulHigh (Node *a, Node *b)
Node * Int32MulWithOverflow (Node *a, Node *b)
Node * Int32Div (Node *a, Node *b)
Node * Int32Mod (Node *a, Node *b)
Node * Int32LessThan (Node *a, Node *b)
Node * Int32LessThanOrEqual (Node *a, Node *b)
Node * Uint32Div (Node *a, Node *b)
Node * Uint32LessThan (Node *a, Node *b)
Node * Uint32LessThanOrEqual (Node *a, Node *b)
Node * Uint32Mod (Node *a, Node *b)
Node * Uint32MulHigh (Node *a, Node *b)
Node * Int32GreaterThan (Node *a, Node *b)
Node * Int32GreaterThanOrEqual (Node *a, Node *b)
Node * Uint32GreaterThan (Node *a, Node *b)
Node * Uint32GreaterThanOrEqual (Node *a, Node *b)
Node * Int32Neg (Node *a)
Node * Int64Add (Node *a, Node *b)
Node * Int64AddWithOverflow (Node *a, Node *b)
Node * Int64Sub (Node *a, Node *b)
Node * Int64SubWithOverflow (Node *a, Node *b)
Node * Int64Mul (Node *a, Node *b)
Node * Int64MulHigh (Node *a, Node *b)
Node * Uint64MulHigh (Node *a, Node *b)
Node * Int64MulWithOverflow (Node *a, Node *b)
Node * Int64Div (Node *a, Node *b)
Node * Int64Mod (Node *a, Node *b)
Node * Int64Neg (Node *a)
Node * Int64LessThan (Node *a, Node *b)
Node * Int64LessThanOrEqual (Node *a, Node *b)
Node * Uint64LessThan (Node *a, Node *b)
Node * Uint64LessThanOrEqual (Node *a, Node *b)
Node * Int64GreaterThan (Node *a, Node *b)
Node * Int64GreaterThanOrEqual (Node *a, Node *b)
Node * Uint64GreaterThan (Node *a, Node *b)
Node * Uint64GreaterThanOrEqual (Node *a, Node *b)
Node * Uint64Div (Node *a, Node *b)
Node * Uint64Mod (Node *a, Node *b)
Node * Int32PairAdd (Node *a_low, Node *a_high, Node *b_low, Node *b_high)
Node * Int32PairSub (Node *a_low, Node *a_high, Node *b_low, Node *b_high)
Node * Int32PairMul (Node *a_low, Node *a_high, Node *b_low, Node *b_high)
Node * Word32PairShl (Node *low_word, Node *high_word, Node *shift)
Node * Word32PairShr (Node *low_word, Node *high_word, Node *shift)
Node * Word32PairSar (Node *low_word, Node *high_word, Node *shift)
Node * Word32Popcnt (Node *a)
Node * Word64Popcnt (Node *a)
Node * Word32Ctz (Node *a)
Node * Word64Ctz (Node *a)
Node * Word32Select (Node *condition, Node *b, Node *c)
Node * Word64Select (Node *condition, Node *b, Node *c)
Node * StackPointerGreaterThan (Node *value)
Node * Int32AbsWithOverflow (Node *a)
Node * Int64AbsWithOverflow (Node *a)
Node * IntPtrAbsWithOverflow (Node *a)
Node * Float32Add (Node *a, Node *b)
Node * Float32Sub (Node *a, Node *b)
Node * Float32Mul (Node *a, Node *b)
Node * Float32Div (Node *a, Node *b)
Node * Float32Abs (Node *a)
Node * Float32Neg (Node *a)
Node * Float32Sqrt (Node *a)
Node * Float32Equal (Node *a, Node *b)
Node * Float32NotEqual (Node *a, Node *b)
Node * Float32LessThan (Node *a, Node *b)
Node * Float32LessThanOrEqual (Node *a, Node *b)
Node * Float32GreaterThan (Node *a, Node *b)
Node * Float32GreaterThanOrEqual (Node *a, Node *b)
Node * Float32Max (Node *a, Node *b)
Node * Float32Min (Node *a, Node *b)
Node * Float64Add (Node *a, Node *b)
Node * Float64Sub (Node *a, Node *b)
Node * Float64Mul (Node *a, Node *b)
Node * Float64Div (Node *a, Node *b)
Node * Float64Mod (Node *a, Node *b)
Node * Float64Max (Node *a, Node *b)
Node * Float64Min (Node *a, Node *b)
Node * Float64Abs (Node *a)
Node * Float64Neg (Node *a)
Node * Float64Acos (Node *a)
Node * Float64Acosh (Node *a)
Node * Float64Asin (Node *a)
Node * Float64Asinh (Node *a)
Node * Float64Atan (Node *a)
Node * Float64Atanh (Node *a)
Node * Float64Atan2 (Node *a, Node *b)
Node * Float64Cbrt (Node *a)
Node * Float64Cos (Node *a)
Node * Float64Cosh (Node *a)
Node * Float64Exp (Node *a)
Node * Float64Expm1 (Node *a)
Node * Float64Log (Node *a)
Node * Float64Log1p (Node *a)
Node * Float64Log10 (Node *a)
Node * Float64Log2 (Node *a)
Node * Float64Pow (Node *a, Node *b)
Node * Float64Sin (Node *a)
Node * Float64Sinh (Node *a)
Node * Float64Sqrt (Node *a)
Node * Float64Tan (Node *a)
Node * Float64Tanh (Node *a)
Node * Float64Equal (Node *a, Node *b)
Node * Float64NotEqual (Node *a, Node *b)
Node * Float64LessThan (Node *a, Node *b)
Node * Float64LessThanOrEqual (Node *a, Node *b)
Node * Float64GreaterThan (Node *a, Node *b)
Node * Float64GreaterThanOrEqual (Node *a, Node *b)
Node * Float32Select (Node *condition, Node *b, Node *c)
Node * Float64Select (Node *condition, Node *b, Node *c)
Node * BitcastTaggedToWord (Node *a)
Node * BitcastTaggedToWordForTagAndSmiBits (Node *a)
Node * BitcastMaybeObjectToWord (Node *a)
Node * BitcastWordToTagged (Node *a)
Node * BitcastWordToTaggedSigned (Node *a)
Node * TruncateFloat64ToWord32 (Node *a)
Node * ChangeFloat32ToFloat64 (Node *a)
Node * ChangeInt32ToFloat64 (Node *a)
Node * ChangeInt64ToFloat64 (Node *a)
Node * ChangeUint32ToFloat64 (Node *a)
Node * ChangeFloat64ToInt32 (Node *a)
Node * ChangeFloat64ToInt64 (Node *a)
Node * ChangeFloat64ToUint32 (Node *a)
Node * ChangeFloat64ToUint64 (Node *a)
Node * TruncateFloat64ToUint32 (Node *a)
Node * TruncateFloat32ToInt32 (Node *a, TruncateKind kind)
Node * TruncateFloat32ToUint32 (Node *a, TruncateKind kind)
Node * TruncateFloat64ToInt64 (Node *a, TruncateKind kind)
Node * TryTruncateFloat32ToInt64 (Node *a)
Node * TryTruncateFloat64ToInt64 (Node *a)
Node * TryTruncateFloat32ToUint64 (Node *a)
Node * TryTruncateFloat64ToUint64 (Node *a)
Node * TryTruncateFloat64ToInt32 (Node *a)
Node * TryTruncateFloat64ToUint32 (Node *a)
Node * ChangeInt32ToInt64 (Node *a)
Node * ChangeInt32ToIntPtr (Node *a)
Node * ChangeUint32ToUint64 (Node *a)
Node * TruncateFloat64ToFloat32 (Node *a)
Node * TruncateFloat64ToFloat16RawBits (Node *a)
Node * TruncateInt64ToInt32 (Node *a)
Node * RoundFloat64ToInt32 (Node *a)
Node * RoundInt32ToFloat32 (Node *a)
Node * RoundInt64ToFloat32 (Node *a)
Node * RoundInt64ToFloat64 (Node *a)
Node * RoundUint32ToFloat32 (Node *a)
Node * RoundUint64ToFloat32 (Node *a)
Node * RoundUint64ToFloat64 (Node *a)
Node * BitcastFloat32ToInt32 (Node *a)
Node * BitcastFloat64ToInt64 (Node *a)
Node * BitcastInt32ToFloat32 (Node *a)
Node * BitcastInt64ToFloat64 (Node *a)
Node * Float32RoundDown (Node *a)
Node * Float64RoundDown (Node *a)
Node * Float32RoundUp (Node *a)
Node * Float64RoundUp (Node *a)
Node * Float32RoundTruncate (Node *a)
Node * Float64RoundTruncate (Node *a)
Node * Float64RoundTiesAway (Node *a)
Node * Float32RoundTiesEven (Node *a)
Node * Float64RoundTiesEven (Node *a)
Node * Word32ReverseBytes (Node *a)
Node * Word64ReverseBytes (Node *a)
Node * Float64ExtractLowWord32 (Node *a)
Node * Float64ExtractHighWord32 (Node *a)
Node * Float64InsertLowWord32 (Node *a, Node *b)
Node * Float64InsertHighWord32 (Node *a, Node *b)
Node * Float64SilenceNaN (Node *a)
Node * LoadFramePointer ()
Node * LoadParentFramePointer ()
Node * I8x16Splat (Node *a)
Node * I8x16BitMask (Node *a)
Node * I8x16Eq (Node *a, Node *b)
Node * TargetParameter ()
Node * Parameter (size_t index)
Node * LoadRootRegister ()
Node * LoadFromPointer (void *address, MachineType type, int32_t offset=0)
Node * StoreToPointer (void *address, MachineRepresentation rep, Node *node)
Node * UnalignedLoadFromPointer (void *address, MachineType type, int32_t offset=0)
Node * UnalignedStoreToPointer (void *address, MachineRepresentation rep, Node *node)
Node * StringConstant (const char *string)
Node * CallN (CallDescriptor *call_descriptor, int input_count, Node *const *inputs)
Node * CallNWithFrameState (CallDescriptor *call_descriptor, int input_count, Node *const *inputs)
void TailCallN (CallDescriptor *call_descriptor, int input_count, Node *const *inputs)
template<class... CArgs>
Node * CallCFunction (Node *function, std::optional< MachineType > return_type, CArgs... cargs)
Node * CallCFunction (Node *function, std::optional< MachineType > return_type, std::initializer_list< CFunctionArg > args)
template<class... CArgs>
Node * CallCFunctionWithoutFunctionDescriptor (Node *function, MachineType return_type, CArgs... cargs)
Node * CallCFunctionWithoutFunctionDescriptor (Node *function, MachineType return_type, std::initializer_list< CFunctionArg > args)
template<class... CArgs>
Node * CallCFunctionWithCallerSavedRegisters (Node *function, MachineType return_type, SaveFPRegsMode mode, CArgs... cargs)
Node * CallCFunctionWithCallerSavedRegisters (Node *function, MachineType return_type, SaveFPRegsMode mode, std::initializer_list< CFunctionArg > args)
void Goto (RawMachineLabel *label)
void Branch (Node *condition, RawMachineLabel *true_val, RawMachineLabel *false_val, BranchHint branch_hint=BranchHint::kNone)
void Switch (Node *index, RawMachineLabel *default_label, const int32_t *case_values, RawMachineLabel **case_labels, size_t case_count)
void Return (Node *value)
void Return (Node *v1, Node *v2)
void Return (Node *v1, Node *v2, Node *v3)
void Return (Node *v1, Node *v2, Node *v3, Node *v4)
void Return (int count, Node *v[])
void PopAndReturn (Node *pop, Node *value)
void PopAndReturn (Node *pop, Node *v1, Node *v2)
void PopAndReturn (Node *pop, Node *v1, Node *v2, Node *v3)
void PopAndReturn (Node *pop, Node *v1, Node *v2, Node *v3, Node *v4)
void Bind (RawMachineLabel *label)
void Deoptimize (Node *state)
void AbortCSADcheck (Node *message)
void DebugBreak ()
void Unreachable ()
void Comment (const std::string &msg)
void StaticAssert (Node *value, const char *source)
bool InsideBlock ()
void Continuations (Node *call, RawMachineLabel *if_success, RawMachineLabel *if_exception)
Node * Phi (MachineRepresentation rep, Node *n1, Node *n2)
Node * Phi (MachineRepresentation rep, Node *n1, Node *n2, Node *n3)
Node * Phi (MachineRepresentation rep, Node *n1, Node *n2, Node *n3, Node *n4)
Node * Phi (MachineRepresentation rep, int input_count, Node *const *inputs)
void AppendPhiInput (Node *phi, Node *new_input)
Node * AddNode (const Operator *op, int input_count, Node *const *inputs)
Node * AddNode (const Operator *op)
template<class... TArgs>
Node * AddNode (const Operator *op, Node *n1, TArgs... args)
void SetCurrentExternalSourcePosition (FileAndLine file_and_line)
FileAndLine GetCurrentExternalSourcePosition () const
SourcePositionTable * source_positions ()
size_t parameter_count () const
Node * dynamic_js_parameter_count ()
void set_dynamic_js_parameter_count (Node *parameter_count)
Private Member Functions
Node * MakeNode (const Operator *op, int input_count, Node *const *inputs)
BasicBlock * Use (RawMachineLabel *label)
BasicBlock * EnsureBlock (RawMachineLabel *label)
BasicBlock * CurrentBlock ()
void MakeReschedulable ()
Node * CreateNodeFromPredecessors (const std::vector< BasicBlock * > &predecessors, const std::vector< Node * > &sidetable, const Operator *op, const std::vector< Node * > &additional_inputs)
void MakePhiBinary (Node *phi, int split_point, Node *left_control, Node *right_control)
void MarkControlDeferred (Node *control_input)
Schedule * schedule ()
Static Private Member Functions
static void OptimizeControlFlow (Schedule *schedule, TFGraph *graph, CommonOperatorBuilder *common)
Private Attributes
Isolate * isolate_
TFGraph * graph_
Schedule * schedule_
SourcePositionTable * source_positions_
MachineOperatorBuilder machine_
CommonOperatorBuilder common_
SimplifiedOperatorBuilder simplified_
CallDescriptor * call_descriptor_
Node * dynamic_js_parameter_count_
Node * target_parameter_
NodeVector parameters_
BasicBlock * current_block_
Detailed Description
Definition at line 47 of file raw-machine-assembler.h.
Member Typedef Documentation
CFunctionArg
using v8::internal::compiler::RawMachineAssembler::CFunctionArg = std::pair<MachineType, Node*>
Definition at line 1043 of file raw-machine-assembler.h.
Constructor & Destructor Documentation
RawMachineAssembler() [1/2]
v8::internal::compiler::RawMachineAssembler::RawMachineAssembler (Isolate * isolate, TFGraph * graph, CallDescriptor * call_descriptor, MachineRepresentation word = MachineType::PointerRepresentation(), MachineOperatorBuilder::Flags flags = MachineOperatorBuilder::Flag::kNoFlags, MachineOperatorBuilder::AlignmentRequirements alignment_requirements = MachineOperatorBuilder::AlignmentRequirements:: FullUnalignedAccessSupport())
Definition at line 19 of file raw-machine-assembler.cc.
    : isolate_(isolate),
      graph_(graph),
      schedule_(zone()->New<Schedule>(zone())),
      source_positions_(zone()->New<SourcePositionTable>(graph)),
      machine_(zone(), word, flags, alignment_requirements),
      common_(zone()),
      simplified_(zone()),
      call_descriptor_(call_descriptor),
      dynamic_js_parameter_count_(nullptr),
      target_parameter_(nullptr),
      parameters_(parameter_count(), zone()),
      current_block_(schedule()->start()) {
  int param_count = static_cast<int>(parameter_count());
  // Add an extra input for the JSFunction parameter to the start node.
  graph->SetStart(graph->NewNode(common_.Start(param_count + 1)));
  if (call_descriptor->IsJSFunctionCall()) {
    target_parameter_ = AddNode(
        common()->Parameter(Linkage::kJSCallClosureParamIndex), graph->start());
  }
  for (size_t i = 0; i < parameter_count(); ++i) {
    parameters_[i] =
        AddNode(common()->Parameter(static_cast<int>(i)), graph->start());
  }
  graph->SetEnd(graph->NewNode(common_.End(0)));
  source_positions_->AddDecorator();
}
References v8::internal::compiler::SourcePositionTable::AddDecorator(), AddNode(), call_descriptor(), common(), common_, v8::internal::compiler::CommonOperatorBuilder::End(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), v8::internal::compiler::Linkage::kJSCallClosureParamIndex, v8::internal::compiler::TFGraph::NewNode(), Parameter(), parameter_count(), parameters_, v8::internal::compiler::TFGraph::SetEnd(), v8::internal::compiler::TFGraph::SetStart(), source_positions_, v8::internal::compiler::TFGraph::start(), v8::internal::compiler::CommonOperatorBuilder::Start(), and target_parameter_.
 RawMachineAssembler()
v8::internal::compiler::RawMachineAssembler::~RawMachineAssembler () [default]
RawMachineAssembler() [2/2]
v8::internal::compiler::RawMachineAssembler::RawMachineAssembler (const RawMachineAssembler &) [delete]
Member Function Documentation
AbortCSADcheck()
void v8::internal::compiler::RawMachineAssembler::AbortCSADcheck (Node * message)
Definition at line 677 of file raw-machine-assembler.cc.
                                                      {
  AddNode(machine()->AbortCSADcheck(), message);
}
References AddNode(), and machine().
Referenced by v8::internal::compiler::CodeAssembler::AbortCSADcheck().
AddNode() [1/3]
Node* v8::internal::compiler::RawMachineAssembler::AddNode (const Operator * op) [inline]
Definition at line 1152 of file raw-machine-assembler.h.
                                    {
    return AddNode(op, 0, static_cast<Node* const*>(nullptr));
  }
AddNode() [2/3]
Node * v8::internal::compiler::RawMachineAssembler::AddNode (const Operator * op, int input_count, Node *const * inputs)
Definition at line 855 of file raw-machine-assembler.cc.
                                                        {
  DCHECK_NOT_NULL(schedule_);
  DCHECK_NOT_NULL(current_block_);
  Node* node = MakeNode(op, input_count, inputs);
  schedule()->AddNode(CurrentBlock(), node);
  return node;
}
References v8::internal::compiler::Schedule::AddNode(), current_block_, CurrentBlock(), DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::detail::input_count(), MakeNode(), schedule(), and schedule_.
Referenced by AbortCSADcheck(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), CallN(), CallNWithFrameState(), Comment(), DebugBreak(), v8::internal::compiler::CodeAssembler::HandleException(), OptimizedAllocate(), Phi(), RawMachineAssembler(), and StaticAssert().
AddNode() [3/3]
template<class... TArgs>
Node* v8::internal::compiler::RawMachineAssembler::AddNode (const Operator * op, Node * n1, TArgs... args) [inline]
Definition at line 1157 of file raw-machine-assembler.h.
                                                             {
    Node* buffer[] = {n1, args...};
    return AddNode(op, sizeof...(args) + 1, buffer);
  }
References v8::base::args.
AppendPhiInput()
void v8::internal::compiler::RawMachineAssembler::AppendPhiInput (Node * phi, Node * new_input)
Definition at line 848 of file raw-machine-assembler.cc.
                                                                   {
  const Operator* op = phi->op();
  const Operator* new_op = common()->ResizeMergeOrPhi(op, phi->InputCount());
  phi->InsertInput(zone(), phi->InputCount() - 1, new_input);
  NodeProperties::ChangeOp(phi, new_op);
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::InsertInput(), v8::internal::compiler::Node::op(), v8::internal::compiler::CommonOperatorBuilder::ResizeMergeOrPhi(), and zone().
AtomicCompareExchange()
Node* v8::internal::compiler::RawMachineAssembler::AtomicCompareExchange (MachineType type, Node * base, Node * index, Node * old_value, Node * new_value) [inline]
Definition at line 346 of file raw-machine-assembler.h.
                                                                {
    DCHECK_NE(type.representation(), MachineRepresentation::kWord64);
    return AddNode(machine()->Word32AtomicCompareExchange(type), base, index,
                   old_value, new_value);
  }
References DCHECK_NE, v8::internal::index, v8::internal::kWord64, and v8::internal::tracing::type.
AtomicCompareExchange64()
Node* v8::internal::compiler::RawMachineAssembler::AtomicCompareExchange64 (Node * base, Node * index, Node * old_value, Node * old_value_high, Node * new_value, Node * new_value_high) [inline]
Definition at line 353 of file raw-machine-assembler.h.
                                                      {
    if (machine()->Is64()) {
      DCHECK_NULL(old_value_high);
      DCHECK_NULL(new_value_high);
      // This uses Uint64() intentionally: AtomicCompareExchange is not
      // implemented for Int64(), which is fine because the machine instruction
      // only cares about words.
      return AddNode(
          machine()->Word64AtomicCompareExchange(MachineType::Uint64()), base,
          index, old_value, new_value);
    } else {
      return AddNode(machine()->Word32AtomicPairCompareExchange(), base, index,
                     old_value, old_value_high, new_value, new_value_high);
    }
  }
References DCHECK_NULL, v8::internal::index, v8::internal::Is64(), and v8::internal::MachineType::Uint64().
AtomicLoad()
Node* v8::internal::compiler::RawMachineAssembler::AtomicLoad (AtomicLoadParameters rep, Node * base, Node * index) [inline]
Definition at line 274 of file raw-machine-assembler.h.
                                                                      {
    DCHECK_NE(rep.representation().representation(),
              MachineRepresentation::kWord64);
    return AddNode(machine()->Word32AtomicLoad(rep), base, index);
  }
References DCHECK_NE, v8::internal::index, v8::internal::kWord64, v8::internal::MachineType::representation(), and v8::internal::compiler::AtomicLoadParameters::representation().
Referenced by v8::internal::compiler::CodeAssembler::AtomicLoad().
AtomicLoad64()
Node* v8::internal::compiler::RawMachineAssembler::AtomicLoad64 (AtomicLoadParameters rep, Node * base, Node * index) [inline]
Definition at line 280 of file raw-machine-assembler.h.
                                                                        {
    if (machine()->Is64()) {
      // This uses Uint64() intentionally: AtomicLoad is not implemented for
      // Int64(), which is fine because the machine instruction only cares
      // about words.
      return AddNode(machine()->Word64AtomicLoad(rep), base, index);
    } else {
      return AddNode(machine()->Word32AtomicPairLoad(rep.order()), base, index);
    }
  }
References v8::internal::index, v8::internal::Is64(), and v8::internal::compiler::AtomicLoadParameters::order().
AtomicStore()
Node* v8::internal::compiler::RawMachineAssembler::AtomicStore (AtomicStoreParameters params, Node * base, Node * index, Node * value) [inline]
Definition at line 297 of file raw-machine-assembler.h.
                                 {
    DCHECK(!IsMapOffsetConstantMinusTag(index));
    DCHECK_NE(params.representation(), MachineRepresentation::kWord64);
    return AddNode(machine()->Word32AtomicStore(params), base, index, value);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::index, v8::internal::kWord64, v8::internal::compiler::AtomicStoreParameters::representation(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::AtomicStore().
AtomicStore64()
Node* v8::internal::compiler::RawMachineAssembler::AtomicStore64 (AtomicStoreParameters params, Node * base, Node * index, Node * value, Node * value_high) [inline]
Definition at line 304 of file raw-machine-assembler.h.
                                                     {
    if (machine()->Is64()) {
      DCHECK_NULL(value_high);
      return AddNode(machine()->Word64AtomicStore(params), base, index, value);
    } else {
      DCHECK(params.representation() != MachineRepresentation::kTaggedPointer &&
             params.representation() != MachineRepresentation::kTaggedSigned &&
             params.representation() != MachineRepresentation::kTagged);
      return AddNode(machine()->Word32AtomicPairStore(params.order()), base,
                     index, VALUE_HALVES);
    }
  }
References v8::internal::DCHECK(), DCHECK_NULL, v8::internal::index, v8::internal::Is64(), v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::compiler::AtomicStoreParameters::order(), v8::internal::compiler::AtomicStoreParameters::representation(), v8::internal::value, and VALUE_HALVES.
Referenced by v8::internal::compiler::CodeAssembler::AtomicStore64().
Bind()
void v8::internal::compiler::RawMachineAssembler::Bind (RawMachineLabel * label)
Definition at line 801 of file raw-machine-assembler.cc.
                                                     {
  DCHECK_NULL(current_block_);
  DCHECK(!label->bound_);
  label->bound_ = true;
  current_block_ = EnsureBlock(label);
  current_block_->set_deferred(label->deferred_);
}
References v8::internal::compiler::RawMachineLabel::bound_, current_block_, v8::internal::DCHECK(), DCHECK_NULL, v8::internal::compiler::RawMachineLabel::deferred_, EnsureBlock(), and v8::internal::compiler::BasicBlock::set_deferred().
BitcastFloat32ToInt32()
Node* v8::internal::compiler::RawMachineAssembler::BitcastFloat32ToInt32 (Node * a) [inline]
Definition at line 909 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->BitcastFloat32ToInt32(), a);
  }
BitcastFloat64ToInt64()
Node* v8::internal::compiler::RawMachineAssembler::BitcastFloat64ToInt64 (Node * a) [inline]
Definition at line 912 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->BitcastFloat64ToInt64(), a);
  }
BitcastInt32ToFloat32()
Node* v8::internal::compiler::RawMachineAssembler::BitcastInt32ToFloat32 (Node * a) [inline]
Definition at line 915 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->BitcastInt32ToFloat32(), a);
  }
BitcastInt64ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::BitcastInt64ToFloat64 (Node * a) [inline]
Definition at line 918 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->BitcastInt64ToFloat64(), a);
  }
BitcastMaybeObjectToWord()
Node* v8::internal::compiler::RawMachineAssembler::BitcastMaybeObjectToWord (Node * a) [inline]
Definition at line 799 of file raw-machine-assembler.h.
                                          {
    return AddNode(machine()->BitcastMaybeObjectToWord(), a);
  }
BitcastTaggedToWord()
Node* v8::internal::compiler::RawMachineAssembler::BitcastTaggedToWord (Node * a) [inline]
Definition at line 793 of file raw-machine-assembler.h.
                                     {
      return AddNode(machine()->BitcastTaggedToWord(), a);
  }
BitcastTaggedToWordForTagAndSmiBits()
Node* v8::internal::compiler::RawMachineAssembler::BitcastTaggedToWordForTagAndSmiBits (Node * a) [inline]
Definition at line 796 of file raw-machine-assembler.h.
                                                     {
    return AddNode(machine()->BitcastTaggedToWordForTagAndSmiBits(), a);
  }
BitcastWordToTagged()
Node* v8::internal::compiler::RawMachineAssembler::BitcastWordToTagged (Node * a) [inline]
Definition at line 802 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->BitcastWordToTagged(), a);
  }
BitcastWordToTaggedSigned()
Node* v8::internal::compiler::RawMachineAssembler::BitcastWordToTaggedSigned (Node * a) [inline]
Definition at line 805 of file raw-machine-assembler.h.
                                           {
      return AddNode(machine()->BitcastWordToTaggedSigned(), a);
  }
Branch()
void v8::internal::compiler::RawMachineAssembler::Branch (Node * condition, RawMachineLabel * true_val, RawMachineLabel * false_val, BranchHint branch_hint = BranchHint::kNone)
Definition at line 541 of file raw-machine-assembler.cc.
                                                         {
  DCHECK(current_block_ != schedule()->end());
  Node* branch = MakeNode(common()->Branch(branch_hint), 1, &condition);
  BasicBlock* true_block = schedule()->NewBasicBlock();
  BasicBlock* false_block = schedule()->NewBasicBlock();
  schedule()->AddBranch(CurrentBlock(), branch, true_block, false_block);
  true_block->AddNode(MakeNode(common()->IfTrue(), 1, &branch));
  schedule()->AddGoto(true_block, Use(true_val));
  false_block->AddNode(MakeNode(common()->IfFalse(), 1, &branch));
  schedule()->AddGoto(false_block, Use(false_val));
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddBranch(), v8::internal::compiler::Schedule::AddGoto(), v8::internal::compiler::BasicBlock::AddNode(), common(), current_block_, CurrentBlock(), v8::internal::DCHECK(), v8::internal::compiler::end(), MakeNode(), v8::internal::compiler::Schedule::NewBasicBlock(), schedule(), and Use().
Referenced by v8::internal::compiler::CodeAssembler::Branch(), and MarkControlDeferred().
call_descriptor()
CallDescriptor* v8::internal::compiler::RawMachineAssembler::call_descriptor () const [inline]
Definition at line 68 of file raw-machine-assembler.h.
{ return call_descriptor_; }
Referenced by CallN(), CallNWithFrameState(), v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::ExecuteJobImpl(), v8::internal::compiler::CodeAssembler::GetJSContextParameter(), v8::internal::compiler::CodeAssembler::IsJSFunctionCall(), PopAndReturn(), RawMachineAssembler(), and TailCallN().
CallCFunction() [1/2]
template<class... CArgs>
Node* v8::internal::compiler::RawMachineAssembler::CallCFunction (Node * function, std::optional< MachineType > return_type, CArgs... cargs) [inline]
Definition at line 1047 of file raw-machine-assembler.h.
                                      {
    static_assert(
        std::conjunction_v<std::is_convertible<CArgs, CFunctionArg>...>,
        "invalid argument types");
    return CallCFunction(function, return_type, {cargs...});
  }
CallCFunction() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::CallCFunction (Node * function, std::optional< MachineType > return_type, std::initializer_list< CFunctionArg > args)
CallCFunctionWithCallerSavedRegisters() [1/2]
template<class... CArgs>
Node* v8::internal::compiler::RawMachineAssembler::CallCFunctionWithCallerSavedRegisters (Node * function, MachineType return_type, SaveFPRegsMode mode, CArgs... cargs) [inline]
Definition at line 1076 of file raw-machine-assembler.h.
                                                              {
    static_assert(
        std::conjunction_v<std::is_convertible<CArgs, CFunctionArg>...>,
        "invalid argument types");
    return CallCFunctionWithCallerSavedRegisters(function, return_type, mode,
                                                 {cargs...});
  }
References mode().
CallCFunctionWithCallerSavedRegisters() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::CallCFunctionWithCallerSavedRegisters (Node * function, MachineType return_type, SaveFPRegsMode mode, std::initializer_list< CFunctionArg > args)
CallCFunctionWithoutFunctionDescriptor() [1/2]
template<class... CArgs>
Node* v8::internal::compiler::RawMachineAssembler::CallCFunctionWithoutFunctionDescriptor (Node * function, MachineType return_type, CArgs... cargs) [inline]
Definition at line 1060 of file raw-machine-assembler.h.
                                                               {
    static_assert(
        std::conjunction_v<std::is_convertible<CArgs, CFunctionArg>...>,
        "invalid argument types");
    return CallCFunctionWithoutFunctionDescriptor(function, return_type,
                                                  {cargs...});
  }
CallCFunctionWithoutFunctionDescriptor() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::CallCFunctionWithoutFunctionDescriptor (Node * function, MachineType return_type, std::initializer_list< CFunctionArg > args)
CallN()
Node * v8::internal::compiler::RawMachineAssembler::CallN (CallDescriptor * call_descriptor, int input_count, Node *const * inputs)
Definition at line 700 of file raw-machine-assembler.cc.
                                                                       {
  DCHECK(!call_descriptor->NeedsFrameState());
  // +1 is for target.
  DCHECK_EQ(input_count, call_descriptor->ParameterCount() + 1);
  return AddNode(common()->Call(call_descriptor), input_count, inputs);
}
References AddNode(), call_descriptor(), common(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::CallDescriptor::NeedsFrameState(), and v8::internal::compiler::CallDescriptor::ParameterCount().
Referenced by v8::internal::compiler::CodeAssembler::CallCFunctionN(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), and v8::internal::compiler::CodeAssembler::CallStubN().
CallNWithFrameState()
Node * v8::internal::compiler::RawMachineAssembler::CallNWithFrameState (CallDescriptor * call_descriptor, int input_count, Node *const * inputs)
Definition at line 708 of file raw-machine-assembler.cc.
                                                                    {
  DCHECK(call_descriptor->NeedsFrameState());
  // +2 is for target and frame state.
  DCHECK_EQ(input_count, call_descriptor->ParameterCount() + 2);
  return AddNode(common()->Call(call_descriptor), input_count, inputs);
}
References AddNode(), call_descriptor(), common(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::CallDescriptor::NeedsFrameState(), and v8::internal::compiler::CallDescriptor::ParameterCount().
ChangeFloat32ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeFloat32ToFloat64 (Node * a) [inline]
Definition at line 811 of file raw-machine-assembler.h.
                                        {
    return AddNode(machine()->ChangeFloat32ToFloat64(), a);
  }
ChangeFloat64ToInt32()
Node* v8::internal::compiler::RawMachineAssembler::ChangeFloat64ToInt32 (Node * a) [inline]
Definition at line 823 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->ChangeFloat64ToInt32(), a);
  }
ChangeFloat64ToInt64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeFloat64ToInt64 (Node * a) [inline]
Definition at line 826 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->ChangeFloat64ToInt64(), a);
  }
ChangeFloat64ToUint32()
Node* v8::internal::compiler::RawMachineAssembler::ChangeFloat64ToUint32 (Node * a) [inline]
Definition at line 829 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->ChangeFloat64ToUint32(), a);
  }
ChangeFloat64ToUint64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeFloat64ToUint64 (Node * a) [inline]
Definition at line 832 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->ChangeFloat64ToUint64(), a);
  }
ChangeInt32ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeInt32ToFloat64 (Node * a) [inline]
Definition at line 814 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->ChangeInt32ToFloat64(), a);
  }
ChangeInt32ToInt64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeInt32ToInt64 (Node * a) [inline]
Definition at line 865 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->ChangeInt32ToInt64(), a);
  }
ChangeInt32ToIntPtr()
Node* v8::internal::compiler::RawMachineAssembler::ChangeInt32ToIntPtr (Node * a) [inline]
Definition at line 868 of file raw-machine-assembler.h.
                                     {
    if (kSystemPointerSize == 8) {
      return ChangeInt32ToInt64(a);
    } else {
      return a;
    }
  }
References v8::internal::kSystemPointerSize.
ChangeInt64ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeInt64ToFloat64 (Node * a) [inline]
Definition at line 817 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->ChangeInt64ToFloat64(), a);
  }
ChangeUint32ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeUint32ToFloat64 (Node * a) [inline]
Definition at line 820 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->ChangeUint32ToFloat64(), a);
  }
ChangeUint32ToUint64()
Node* v8::internal::compiler::RawMachineAssembler::ChangeUint32ToUint64 (Node * a) [inline]
Definition at line 875 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->ChangeUint32ToUint64(), a);
  }
Comment()
void v8::internal::compiler::RawMachineAssembler::Comment (const std::string & msg)
Definition at line 689 of file raw-machine-assembler.cc.
                                                      {
  size_t length = msg.length() + 1;
  char* zone_buffer = zone()->AllocateArray<char>(length);
  MemCopy(zone_buffer, msg.c_str(), length);
  AddNode(machine()->Comment(zone_buffer));
}
References AddNode(), v8::internal::Zone::AllocateArray(), v8::internal::length, machine(), v8::internal::MemCopy(), and zone().
Referenced by v8::internal::compiler::CodeAssembler::EmitComment().
common()
CommonOperatorBuilder* v8::internal::compiler::RawMachineAssembler::common () [inline]
Definition at line 66 of file raw-machine-assembler.h.
{ return &common_; }
Referenced by AppendPhiInput(), Branch(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), CallN(), CallNWithFrameState(), ExportForOptimization(), v8::internal::compiler::CodeAssembler::HandleException(), MakePhiBinary(), MakeReschedulable(), MarkControlDeferred(), OptimizeControlFlow(), Phi(), PopAndReturn(), RawMachineAssembler(), Return(), StaticAssert(), Switch(), TailCallN(), and Unreachable().
Continuations()
void v8::internal::compiler::RawMachineAssembler::Continuations (Node * call, RawMachineLabel * if_success, RawMachineLabel * if_exception)
Definition at line 559 of file raw-machine-assembler.cc.
                                                                       {
  DCHECK_NOT_NULL(schedule_);
  DCHECK_NOT_NULL(current_block_);
  schedule()->AddCall(CurrentBlock(), call, Use(if_success), Use(if_exception));
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddCall(), current_block_, CurrentBlock(), DCHECK_NOT_NULL, schedule(), schedule_, and Use().
Referenced by v8::internal::compiler::CodeAssembler::HandleException().
CreateNodeFromPredecessors()
Node * v8::internal::compiler::RawMachineAssembler::CreateNodeFromPredecessors (const std::vector< BasicBlock * > & predecessors, const std::vector< Node * > & sidetable, const Operator * op, const std::vector< Node * > & additional_inputs) [private]
Definition at line 378 of file raw-machine-assembler.cc.
                                               {
  if (predecessors.size() == 1) {
    return sidetable[predecessors.front()->id().ToSize()];
  }
  std::vector<Node*> inputs;
  inputs.reserve(predecessors.size());
  for (BasicBlock* predecessor : predecessors) {
    inputs.push_back(sidetable[predecessor->id().ToSize()]);
  }
  for (Node* additional_input : additional_inputs) {
    inputs.push_back(additional_input);
  }
  return graph()->NewNode(op, static_cast<int>(inputs.size()), inputs.data());
}
References graph(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by MakeReschedulable().
CurrentBlock()
BasicBlock * v8::internal::compiler::RawMachineAssembler::CurrentBlock () [private]
Definition at line 835 of file raw-machine-assembler.cc.
                                              {
  DCHECK(current_block_);
  return current_block_;
}
References current_block_, and v8::internal::DCHECK().
Referenced by AddNode(), Branch(), Continuations(), Goto(), PopAndReturn(), Return(), Switch(), TailCallN(), and Unreachable().
DebugBreak()
void v8::internal::compiler::RawMachineAssembler::DebugBreak ()
Definition at line 681 of file raw-machine-assembler.cc.
{ AddNode(machine()->DebugBreak()); }
References AddNode(), and machine().
Referenced by v8::internal::compiler::CodeAssembler::DebugBreak().
Deoptimize()
void v8::internal::compiler::RawMachineAssembler::Deoptimize (Node * state)
dynamic_js_parameter_count()
Node* v8::internal::compiler::RawMachineAssembler::dynamic_js_parameter_count () [inline]
Definition at line 1188 of file raw-machine-assembler.h.
{ return dynamic_js_parameter_count_; }
Referenced by v8::internal::compiler::CodeAssembler::HasDynamicJSParameterCount().
EnsureBlock()
BasicBlock * v8::internal::compiler::RawMachineAssembler::EnsureBlock (RawMachineLabel * label) [private]
Definition at line 794 of file raw-machine-assembler.cc.
                                                                   {
  if (label->block_ == nullptr) {
    label->block_ = schedule()->NewBasicBlock();
  }
  return label->block_;
}
References v8::internal::compiler::RawMachineLabel::block_, v8::internal::compiler::Schedule::NewBasicBlock(), and schedule().
Referenced by Bind(), and Use().
ExportForOptimization()
TFGraph * v8::internal::compiler::RawMachineAssembler::ExportForOptimization ()
Definition at line 110 of file raw-machine-assembler.cc.
                                                    {
  // Compute the correct codegen order.
  DCHECK(schedule_->rpo_order()->empty());
  if (v8_flags.trace_turbo_scheduler) {
    PrintF("--- RAW SCHEDULE -------------------------------------------\n");
    StdoutStream{} << *schedule_;
  }
  schedule_->EnsureCFGWellFormedness();
  OptimizeControlFlow(schedule_, graph(), common());
  Scheduler::ComputeSpecialRPO(zone(), schedule_);
  if (v8_flags.trace_turbo_scheduler) {
    PrintF("--- SCHEDULE BEFORE GRAPH CREATION -------------------------\n");
    StdoutStream{} << *schedule_;
  }
  MakeReschedulable();
  // Invalidate RawMachineAssembler.
  schedule_ = nullptr;
  return graph();
}
References common(), v8::internal::compiler::Scheduler::ComputeSpecialRPO(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::Schedule::EnsureCFGWellFormedness(), graph(), MakeReschedulable(), OptimizeControlFlow(), v8::internal::PrintF(), v8::internal::compiler::Schedule::rpo_order(), schedule_, v8::internal::v8_flags, and zone().
ExportForTest()
Schedule * v8::internal::compiler::RawMachineAssembler::ExportForTest ()
Definition at line 88 of file raw-machine-assembler.cc.
                                             {
  // Compute the correct codegen order.
  DCHECK(schedule_->rpo_order()->empty());
  if (v8_flags.trace_turbo_scheduler) {
    PrintF("--- RAW SCHEDULE -------------------------------------------\n");
    StdoutStream{} << *schedule_;
  }
  schedule_->EnsureCFGWellFormedness();
  Scheduler::ComputeSpecialRPO(zone(), schedule_);
  Scheduler::GenerateDominatorTree(schedule_);
  schedule_->PropagateDeferredMark();
  if (v8_flags.trace_turbo_scheduler) {
    PrintF("--- EDGE SPLIT AND PROPAGATED DEFERRED SCHEDULE ------------\n");
    StdoutStream{} << *schedule_;
  }
  // Invalidate RawMachineAssembler.
  source_positions_->RemoveDecorator();
  Schedule* schedule = schedule_;
  schedule_ = nullptr;
  return schedule;
}
References v8::internal::compiler::Scheduler::ComputeSpecialRPO(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::Schedule::EnsureCFGWellFormedness(), v8::internal::compiler::Scheduler::GenerateDominatorTree(), v8::internal::PrintF(), v8::internal::compiler::Schedule::PropagateDeferredMark(), v8::internal::compiler::SourcePositionTable::RemoveDecorator(), v8::internal::compiler::Schedule::rpo_order(), schedule(), schedule_, source_positions_, v8::internal::v8_flags, and zone().
ExternalConstant()
Node* v8::internal::compiler::RawMachineAssembler::ExternalConstant (ExternalReference address) [inline]
Definition at line 121 of file raw-machine-assembler.h.
                                                    {
    return AddNode(common()->ExternalConstant(address));
  }
Float32Abs()
Node* v8::internal::compiler::RawMachineAssembler::Float32Abs (Node * a) [inline]
Definition at line 695 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float32Abs(), a); }
References Float32Abs().
Referenced by Float32Abs().
Float32Add()
Node* v8::internal::compiler::RawMachineAssembler::Float32Add (Node * a, Node * b) [inline]
Definition at line 683 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float32Add(), a, b);
  }
Float32Constant()
Node* v8::internal::compiler::RawMachineAssembler::Float32Constant (float value) [inline]
Definition at line 112 of file raw-machine-assembler.h.
                                     {
    return AddNode(common()->Float32Constant(value));
  }
References v8::internal::value.
Float32Div()
Node* v8::internal::compiler::RawMachineAssembler::Float32Div (Node * a, Node * b) [inline]
Definition at line 692 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float32Div(), a, b);
  }
Float32Equal()
Node* v8::internal::compiler::RawMachineAssembler::Float32Equal (Node * a, Node * b) [inline]
Definition at line 698 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->Float32Equal(), a, b);
  }
Float32GreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::Float32GreaterThan (Node * a, Node * b) [inline]
Definition at line 710 of file raw-machine-assembler.h.
{ return Float32LessThan(b, a); }
Float32GreaterThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Float32GreaterThanOrEqual (Node * a, Node * b) [inline]
Definition at line 711 of file raw-machine-assembler.h.
                                                    {
    return Float32LessThanOrEqual(b, a);
  }
Float32LessThan()
Node* v8::internal::compiler::RawMachineAssembler::Float32LessThan (Node * a, Node * b) [inline]
Definition at line 704 of file raw-machine-assembler.h.
                                          {
    return AddNode(machine()->Float32LessThan(), a, b);
  }
Float32LessThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Float32LessThanOrEqual (Node * a, Node * b) [inline]
Definition at line 707 of file raw-machine-assembler.h.
                                                 {
    return AddNode(machine()->Float32LessThanOrEqual(), a, b);
  }
Float32Max()
Node* v8::internal::compiler::RawMachineAssembler::Float32Max (Node * a, Node * b) [inline]
Definition at line 714 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float32Max(), a, b);
  }
Float32Min()
Node* v8::internal::compiler::RawMachineAssembler::Float32Min (Node * a, Node * b) [inline]
Definition at line 717 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float32Min(), a, b);
  }
Float32Mul()
Node* v8::internal::compiler::RawMachineAssembler::Float32Mul (Node * a, Node * b) [inline]
Definition at line 689 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float32Mul(), a, b);
  }
Float32Neg()
Node* v8::internal::compiler::RawMachineAssembler::Float32Neg (Node * a) [inline]
Definition at line 696 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float32Neg(), a); }
References Float32Neg().
Referenced by Float32Neg().
Float32NotEqual()
Node* v8::internal::compiler::RawMachineAssembler::Float32NotEqual (Node * a, Node * b) [inline]
Definition at line 701 of file raw-machine-assembler.h.
                                          {
    return Word32BinaryNot(Float32Equal(a, b));
  }
Float32RoundDown()
Node* v8::internal::compiler::RawMachineAssembler::Float32RoundDown (Node * a) [inline]
Definition at line 921 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->Float32RoundDown().op(), a);
  }
Float32RoundTiesEven()
Node* v8::internal::compiler::RawMachineAssembler::Float32RoundTiesEven (Node * a) [inline]
Definition at line 942 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Float32RoundTiesEven().op(), a);
  }
Float32RoundTruncate()
Node* v8::internal::compiler::RawMachineAssembler::Float32RoundTruncate (Node * a) [inline]
Definition at line 933 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Float32RoundTruncate().op(), a);
  }
Float32RoundUp()
Node* v8::internal::compiler::RawMachineAssembler::Float32RoundUp (Node * a) [inline]
Definition at line 927 of file raw-machine-assembler.h.
                                {
    return AddNode(machine()->Float32RoundUp().op(), a);
  }
Float32Select()
Node* v8::internal::compiler::RawMachineAssembler::Float32Select (Node * condition, Node * b, Node * c) [inline]
Definition at line 785 of file raw-machine-assembler.h.
                                                         {
    return AddNode(machine()->Float32Select().op(), condition, b, c);
  }
Float32Sqrt()
Node* v8::internal::compiler::RawMachineAssembler::Float32Sqrt (Node * a) [inline]
Definition at line 697 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float32Sqrt(), a); }
References Float32Sqrt().
Referenced by Float32Sqrt().
Float32Sub()
Node* v8::internal::compiler::RawMachineAssembler::Float32Sub (Node * a, Node * b) [inline]
Definition at line 686 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float32Sub(), a, b);
  }
Float64Abs()
Node* v8::internal::compiler::RawMachineAssembler::Float64Abs (Node * a) [inline]
Definition at line 741 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Abs(), a); }
References Float64Abs().
Referenced by Float64Abs().
Float64Acos()
Node* v8::internal::compiler::RawMachineAssembler::Float64Acos (Node * a) [inline]
Definition at line 743 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Acos(), a); }
References Float64Acos().
Referenced by Float64Acos().
Float64Acosh()
Node* v8::internal::compiler::RawMachineAssembler::Float64Acosh (Node * a) [inline]
Definition at line 744 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Acosh(), a); }
References Float64Acosh().
Referenced by Float64Acosh().
Float64Add()
Node* v8::internal::compiler::RawMachineAssembler::Float64Add (Node * a, Node * b) [inline]
Definition at line 720 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Add(), a, b);
  }
References v8::internal::compiler::Float64Add().
Float64Asin()
Node* v8::internal::compiler::RawMachineAssembler::Float64Asin (Node * a) [inline]
Definition at line 745 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Asin(), a); }
References Float64Asin().
Referenced by Float64Asin().
Float64Asinh()
Node* v8::internal::compiler::RawMachineAssembler::Float64Asinh (Node * a) [inline]
Definition at line 746 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Asinh(), a); }
References Float64Asinh().
Referenced by Float64Asinh().
Float64Atan()
Node* v8::internal::compiler::RawMachineAssembler::Float64Atan (Node * a) [inline]
Definition at line 747 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Atan(), a); }
References Float64Atan().
Referenced by Float64Atan().
Float64Atan2()
Node* v8::internal::compiler::RawMachineAssembler::Float64Atan2 (Node * a, Node * b) [inline]
Definition at line 749 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->Float64Atan2(), a, b);
  }
Float64Atanh()
Node* v8::internal::compiler::RawMachineAssembler::Float64Atanh (Node * a) [inline]
Definition at line 748 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Atanh(), a); }
References Float64Atanh().
Referenced by Float64Atanh().
Float64Cbrt()
Node* v8::internal::compiler::RawMachineAssembler::Float64Cbrt (Node * a) [inline]
Definition at line 752 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Cbrt(), a); }
References Float64Cbrt().
Referenced by Float64Cbrt().
Float64Constant()
Node* v8::internal::compiler::RawMachineAssembler::Float64Constant (double value) [inline]
Definition at line 115 of file raw-machine-assembler.h.
                                      {
    return AddNode(common()->Float64Constant(value));
  }
References v8::internal::value.
Float64Cos()
Node* v8::internal::compiler::RawMachineAssembler::Float64Cos (Node * a) [inline]
Definition at line 753 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Cos(), a); }
References Float64Cos().
Referenced by Float64Cos().
Float64Cosh()
Node* v8::internal::compiler::RawMachineAssembler::Float64Cosh (Node * a) [inline]
Definition at line 754 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Cosh(), a); }
References Float64Cosh().
Referenced by Float64Cosh().
Float64Div()
Node* v8::internal::compiler::RawMachineAssembler::Float64Div (Node * a, Node * b) [inline]
Definition at line 729 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Div(), a, b);
  }
Float64Equal()
Node* v8::internal::compiler::RawMachineAssembler::Float64Equal (Node * a, Node * b) [inline]
Definition at line 769 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->Float64Equal(), a, b);
  }
Float64Exp()
Node* v8::internal::compiler::RawMachineAssembler::Float64Exp (Node * a) [inline]
Definition at line 755 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Exp(), a); }
References Float64Exp().
Referenced by Float64Exp().
Float64Expm1()
Node* v8::internal::compiler::RawMachineAssembler::Float64Expm1 (Node * a) [inline]
Definition at line 756 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Expm1(), a); }
References Float64Expm1().
Referenced by Float64Expm1().
Float64ExtractHighWord32()
Node* v8::internal::compiler::RawMachineAssembler::Float64ExtractHighWord32 (Node * a) [inline]
Definition at line 959 of file raw-machine-assembler.h.
                                          {
    return AddNode(machine()->Float64ExtractHighWord32(), a);
  }
Float64ExtractLowWord32()
Node* v8::internal::compiler::RawMachineAssembler::Float64ExtractLowWord32 (Node * a) [inline]
Definition at line 956 of file raw-machine-assembler.h.
                                         {
    return AddNode(machine()->Float64ExtractLowWord32(), a);
  }
Float64GreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::Float64GreaterThan (Node * a, Node * b) [inline]
Definition at line 781 of file raw-machine-assembler.h.
{ return Float64LessThan(b, a); }
Float64GreaterThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Float64GreaterThanOrEqual (Node * a, Node * b) [inline]
Definition at line 782 of file raw-machine-assembler.h.
                                                    {
    return Float64LessThanOrEqual(b, a);
  }
Float64InsertHighWord32()
Node* v8::internal::compiler::RawMachineAssembler::Float64InsertHighWord32 (Node * a, Node * b) [inline]
Definition at line 965 of file raw-machine-assembler.h.
                                                  {
    return AddNode(machine()->Float64InsertHighWord32(), a, b);
  }
Float64InsertLowWord32()
Node* v8::internal::compiler::RawMachineAssembler::Float64InsertLowWord32 (Node * a, Node * b) [inline]
Definition at line 962 of file raw-machine-assembler.h.
                                                 {
    return AddNode(machine()->Float64InsertLowWord32(), a, b);
  }
Float64LessThan()
Node* v8::internal::compiler::RawMachineAssembler::Float64LessThan (Node * a, Node * b) [inline]
Definition at line 775 of file raw-machine-assembler.h.
                                          {
    return AddNode(machine()->Float64LessThan(), a, b);
  }
Float64LessThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Float64LessThanOrEqual (Node * a, Node * b) [inline]
Definition at line 778 of file raw-machine-assembler.h.
                                                 {
    return AddNode(machine()->Float64LessThanOrEqual(), a, b);
  }
Float64Log()
Node* v8::internal::compiler::RawMachineAssembler::Float64Log (Node * a) [inline]
Definition at line 757 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Log(), a); }
References Float64Log().
Referenced by Float64Log().
Float64Log10()
Node* v8::internal::compiler::RawMachineAssembler::Float64Log10 (Node * a) [inline]
Definition at line 759 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Log10(), a); }
References Float64Log10().
Referenced by Float64Log10().
Float64Log1p()
Node* v8::internal::compiler::RawMachineAssembler::Float64Log1p (Node * a) [inline]
Definition at line 758 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Log1p(), a); }
References Float64Log1p().
Referenced by Float64Log1p().
Float64Log2()
Node* v8::internal::compiler::RawMachineAssembler::Float64Log2 (Node * a) [inline]
Definition at line 760 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Log2(), a); }
References Float64Log2().
Referenced by Float64Log2().
Float64Max()
Node* v8::internal::compiler::RawMachineAssembler::Float64Max (Node * a, Node * b) [inline]
Definition at line 735 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Max(), a, b);
  }
Float64Min()
Node* v8::internal::compiler::RawMachineAssembler::Float64Min (Node * a, Node * b) [inline]
Definition at line 738 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Min(), a, b);
  }
Float64Mod()
Node* v8::internal::compiler::RawMachineAssembler::Float64Mod (Node * a, Node * b) [inline]
Definition at line 732 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Mod(), a, b);
  }
Float64Mul()
Node* v8::internal::compiler::RawMachineAssembler::Float64Mul (Node * a, Node * b) [inline]
Definition at line 726 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Mul(), a, b);
  }
Float64Neg()
Node* v8::internal::compiler::RawMachineAssembler::Float64Neg (Node * a) [inline]
Definition at line 742 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Neg(), a); }
References Float64Neg().
Referenced by Float64Neg().
Float64NotEqual()
Node* v8::internal::compiler::RawMachineAssembler::Float64NotEqual (Node * a, Node * b) [inline]
Definition at line 772 of file raw-machine-assembler.h.
                                          {
    return Word32BinaryNot(Float64Equal(a, b));
  }
Float64Pow()
Node* v8::internal::compiler::RawMachineAssembler::Float64Pow (Node * a, Node * b) [inline]
Definition at line 761 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Pow(), a, b);
  }
Float64RoundDown()
Node* v8::internal::compiler::RawMachineAssembler::Float64RoundDown (Node * a) [inline]
Definition at line 924 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->Float64RoundDown().placeholder(), a);
  }
Float64RoundTiesAway()
Node* v8::internal::compiler::RawMachineAssembler::Float64RoundTiesAway (Node * a) [inline]
Definition at line 939 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Float64RoundTiesAway().op(), a);
  }
Float64RoundTiesEven()
Node* v8::internal::compiler::RawMachineAssembler::Float64RoundTiesEven (Node * a) [inline]
Definition at line 945 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Float64RoundTiesEven().placeholder(), a);
  }
Float64RoundTruncate()
Node* v8::internal::compiler::RawMachineAssembler::Float64RoundTruncate (Node * a) [inline]
Definition at line 936 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Float64RoundTruncate().placeholder(), a);
  }
Float64RoundUp()
Node* v8::internal::compiler::RawMachineAssembler::Float64RoundUp (Node * a) [inline]
Definition at line 930 of file raw-machine-assembler.h.
                                {
    return AddNode(machine()->Float64RoundUp().placeholder(), a);
  }
Float64Select()
Node* v8::internal::compiler::RawMachineAssembler::Float64Select (Node * condition, Node * b, Node * c) [inline]
Definition at line 788 of file raw-machine-assembler.h.
                                                         {
    return AddNode(machine()->Float64Select().op(), condition, b, c);
  }
Float64SilenceNaN()
Node* v8::internal::compiler::RawMachineAssembler::Float64SilenceNaN (Node * a) [inline]
Definition at line 968 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Float64SilenceNaN(), a);
  }
Float64Sin()
Node* v8::internal::compiler::RawMachineAssembler::Float64Sin (Node * a) [inline]
Definition at line 764 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Sin(), a); }
References Float64Sin().
Referenced by Float64Sin().
Float64Sinh()
Node* v8::internal::compiler::RawMachineAssembler::Float64Sinh (Node * a) [inline]
Definition at line 765 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Sinh(), a); }
References Float64Sinh().
Referenced by Float64Sinh().
Float64Sqrt()
Node* v8::internal::compiler::RawMachineAssembler::Float64Sqrt (Node * a) [inline]
Definition at line 766 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Sqrt(), a); }
References Float64Sqrt().
Referenced by Float64Sqrt().
Float64Sub()
Node* v8::internal::compiler::RawMachineAssembler::Float64Sub (Node * a, Node * b) [inline]
Definition at line 723 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->Float64Sub(), a, b);
  }
Float64Tan()
Node* v8::internal::compiler::RawMachineAssembler::Float64Tan (Node * a) [inline]
Definition at line 767 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Tan(), a); }
References Float64Tan().
Referenced by Float64Tan().
Float64Tanh()
Node* v8::internal::compiler::RawMachineAssembler::Float64Tanh (Node * a) [inline]
Definition at line 768 of file raw-machine-assembler.h.
{ return AddNode(machine()->Float64Tanh(), a); }
References Float64Tanh().
Referenced by Float64Tanh().
GetCurrentExternalSourcePosition()
FileAndLine v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition () const
Definition at line 59 of file raw-machine-assembler.cc.
                                                                        {
  SourcePosition p = source_positions_->GetCurrentPosition();
  if (!p.IsKnown()) return {nullptr, -1};
  int file_id = p.ExternalFileId();
  const char* file_name = isolate()->GetExternallyCompiledFilename(file_id);
  int line = p.ExternalLine();
  return {file_name, line};
}
References v8::internal::SourcePosition::ExternalFileId(), v8::internal::SourcePosition::ExternalLine(), v8::internal::compiler::SourcePositionTable::GetCurrentPosition(), v8::internal::Isolate::GetExternallyCompiledFilename(), v8::internal::SourcePosition::IsKnown(), isolate(), and source_positions_.
Referenced by v8::internal::compiler::CodeAssembler::PushSourcePosition().
Goto()
void v8::internal::compiler::RawMachineAssembler::Goto (RawMachineLabel * label)
Definition at line 535 of file raw-machine-assembler.cc.
                                                     {
  DCHECK(current_block_ != schedule()->end());
  schedule()->AddGoto(CurrentBlock(), Use(label));
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddGoto(), current_block_, CurrentBlock(), v8::internal::DCHECK(), v8::internal::compiler::end(), schedule(), and Use().
Referenced by v8::internal::compiler::CodeAssembler::Goto().
graph()
TFGraph* v8::internal::compiler::RawMachineAssembler::graph () const [inline]
Definition at line 63 of file raw-machine-assembler.h.
{ return graph_; }
Referenced by v8::internal::compiler::CodeAssembler::BreakOnNode(), CreateNodeFromPredecessors(), ExportForOptimization(), MakeNode(), MakePhiBinary(), MakeReschedulable(), OptimizeControlFlow(), Phi(), RawMachineAssembler(), and Switch().
HeapConstant()
Node* v8::internal::compiler::RawMachineAssembler::HeapConstant (Handle< HeapObject > object) [inline]
Definition at line 118 of file raw-machine-assembler.h.
                                                {
    return AddNode(common()->HeapConstant(object));
  }
Referenced by NullConstant(), and UndefinedConstant().
I8x16BitMask()
Node* v8::internal::compiler::RawMachineAssembler::I8x16BitMask (Node * a) [inline]
Definition at line 980 of file raw-machine-assembler.h.
{ return AddNode(machine()->I8x16BitMask(), a); }
References I8x16BitMask().
Referenced by I8x16BitMask().
I8x16Eq()
Node* v8::internal::compiler::RawMachineAssembler::I8x16Eq (Node * a, Node * b) [inline]
Definition at line 981 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->I8x16Eq(), a, b);
  }
I8x16Splat()
Node* v8::internal::compiler::RawMachineAssembler::I8x16Splat (Node * a) [inline]
Definition at line 979 of file raw-machine-assembler.h.
{ return AddNode(machine()->I8x16Splat(), a); }
References I8x16Splat().
Referenced by I8x16Splat().
InsideBlock()
bool v8::internal::compiler::RawMachineAssembler::InsideBlock ()
Definition at line 833 of file raw-machine-assembler.cc.
{ return current_block_ != nullptr; }
References current_block_.
Int32AbsWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int32AbsWithOverflow (Node * a) [inline]
Definition at line 670 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Int32AbsWithOverflow().op(), a);
  }
Int32Add()
Node* v8::internal::compiler::RawMachineAssembler::Int32Add (Node * a, Node * b) [inline]
Definition at line 476 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int32Add(), a, b);
  }
Int32AddWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int32AddWithOverflow (Node * a, Node * b) [inline]
Definition at line 479 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int32AddWithOverflow(), a, b);
  }
Int32Constant()
Node* v8::internal::compiler::RawMachineAssembler::Int32Constant (int32_t value) [inline]
Definition at line 97 of file raw-machine-assembler.h.
                                     {
    return AddNode(common()->Int32Constant(value));
  }
References v8::internal::value.
Referenced by Return().
Int32Div()
Node* v8::internal::compiler::RawMachineAssembler::Int32Div (Node * a, Node * b) [inline]
Definition at line 497 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int32Div(), a, b);
  }
Int32GreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::Int32GreaterThan (Node * a, Node * b) [inline]
Definition at line 524 of file raw-machine-assembler.h.
{ return Int32LessThan(b, a); }
Int32GreaterThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Int32GreaterThanOrEqual (Node * a, Node * b) [inline]
Definition at line 525 of file raw-machine-assembler.h.
                                                  {
    return Int32LessThanOrEqual(b, a);
  }
Int32LessThan()
Node* v8::internal::compiler::RawMachineAssembler::Int32LessThan (Node * a, Node * b) [inline]
Definition at line 503 of file raw-machine-assembler.h.
                                        {
    return AddNode(machine()->Int32LessThan(), a, b);
  }
Int32LessThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Int32LessThanOrEqual (Node * a, Node * b) [inline]
Definition at line 506 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int32LessThanOrEqual(), a, b);
  }
Int32Mod()
Node* v8::internal::compiler::RawMachineAssembler::Int32Mod (Node * a, Node * b) [inline]
Definition at line 500 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int32Mod(), a, b);
  }
Int32Mul()
Node* v8::internal::compiler::RawMachineAssembler::Int32Mul (Node * a, Node * b) [inline]
Definition at line 488 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int32Mul(), a, b);
  }
Int32MulHigh()
Node* v8::internal::compiler::RawMachineAssembler::Int32MulHigh (Node * a, Node * b) [inline]
Definition at line 491 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->Int32MulHigh(), a, b);
  }
Int32MulWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int32MulWithOverflow (Node * a, Node * b) [inline]
Definition at line 494 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int32MulWithOverflow(), a, b);
  }
Int32Neg()
Node* v8::internal::compiler::RawMachineAssembler::Int32Neg (Node * a) [inline]
Definition at line 532 of file raw-machine-assembler.h.
{ return Int32Sub(Int32Constant(0), a); }
Int32PairAdd()
Node* v8::internal::compiler::RawMachineAssembler::Int32PairAdd (Node * a_low, Node * a_high, Node * b_low, Node * b_high) [inline]
Definition at line 591 of file raw-machine-assembler.h.
                                                                           {
    return AddNode(machine()->Int32PairAdd(), a_low, a_high, b_low, b_high);
  }
Referenced by v8::internal::compiler::CodeAssembler::Int32PairAdd().
Int32PairMul()
Node* v8::internal::compiler::RawMachineAssembler::Int32PairMul (Node * a_low, Node * a_high, Node * b_low, Node * b_high) [inline]
Definition at line 597 of file raw-machine-assembler.h.
                                                                           {
    return AddNode(machine()->Int32PairMul(), a_low, a_high, b_low, b_high);
  }
Int32PairSub()
Node* v8::internal::compiler::RawMachineAssembler::Int32PairSub (Node * a_low, Node * a_high, Node * b_low, Node * b_high) [inline]
Definition at line 594 of file raw-machine-assembler.h.
                                                                           {
    return AddNode(machine()->Int32PairSub(), a_low, a_high, b_low, b_high);
  }
Referenced by v8::internal::compiler::CodeAssembler::Int32PairSub().
Int32Sub()
Node* v8::internal::compiler::RawMachineAssembler::Int32Sub (Node * a, Node * b) [inline]
Definition at line 482 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int32Sub(), a, b);
  }
Int32SubWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int32SubWithOverflow (Node * a, Node * b) [inline]
Definition at line 485 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int32SubWithOverflow(), a, b);
  }
Int64AbsWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int64AbsWithOverflow (Node * a) [inline]
Definition at line 674 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Int64AbsWithOverflow().op(), a);
  }
Int64Add()
Node* v8::internal::compiler::RawMachineAssembler::Int64Add (Node * a, Node * b) [inline]
Definition at line 534 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int64Add(), a, b);
  }
Int64AddWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int64AddWithOverflow (Node * a, Node * b) [inline]
Definition at line 537 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int64AddWithOverflow(), a, b);
  }
Int64Constant()
Node* v8::internal::compiler::RawMachineAssembler::Int64Constant (int64_t value) [inline]
Definition at line 106 of file raw-machine-assembler.h.
                                     {
    return AddNode(common()->Int64Constant(value));
  }
References v8::internal::value.
Int64Div()
Node* v8::internal::compiler::RawMachineAssembler::Int64Div (Node * a, Node * b) [inline]
Definition at line 558 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int64Div(), a, b);
  }
Int64GreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::Int64GreaterThan (Node * a, Node * b) [inline]
Definition at line 577 of file raw-machine-assembler.h.
{ return Int64LessThan(b, a); }
Int64GreaterThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Int64GreaterThanOrEqual (Node * a, Node * b) [inline]
Definition at line 578 of file raw-machine-assembler.h.
                                                  {
    return Int64LessThanOrEqual(b, a);
  }
Int64LessThan()
Node* v8::internal::compiler::RawMachineAssembler::Int64LessThan (Node * a, Node * b) [inline]
Definition at line 565 of file raw-machine-assembler.h.
                                        {
    return AddNode(machine()->Int64LessThan(), a, b);
  }
Int64LessThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Int64LessThanOrEqual (Node * a, Node * b) [inline]
Definition at line 568 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int64LessThanOrEqual(), a, b);
  }
Int64Mod()
Node* v8::internal::compiler::RawMachineAssembler::Int64Mod (Node * a, Node * b) [inline]
Definition at line 561 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int64Mod(), a, b);
  }
Int64Mul()
Node* v8::internal::compiler::RawMachineAssembler::Int64Mul (Node * a, Node * b) [inline]
Definition at line 546 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int64Mul(), a, b);
  }
Int64MulHigh()
Node* v8::internal::compiler::RawMachineAssembler::Int64MulHigh (Node * a, Node * b) [inline]
Definition at line 549 of file raw-machine-assembler.h.
                                       {
    return AddNode(machine()->Int64MulHigh(), a, b);
  }
Int64MulWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int64MulWithOverflow (Node * a, Node * b) [inline]
Definition at line 555 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int64MulWithOverflow(), a, b);
  }
Int64Neg()
Node* v8::internal::compiler::RawMachineAssembler::Int64Neg (Node * a) [inline]
Definition at line 564 of file raw-machine-assembler.h.
{ return Int64Sub(Int64Constant(0), a); }
Int64Sub()
Node* v8::internal::compiler::RawMachineAssembler::Int64Sub (Node * a, Node * b) [inline]
Definition at line 540 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Int64Sub(), a, b);
  }
Int64SubWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::Int64SubWithOverflow (Node * a, Node * b) [inline]
Definition at line 543 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->Int64SubWithOverflow(), a, b);
  }
IntPtrAbsWithOverflow()
Node* v8::internal::compiler::RawMachineAssembler::IntPtrAbsWithOverflow (Node * a) [inline]
Definition at line 678 of file raw-machine-assembler.h.
                                       {
    return kSystemPointerSize == 8 ? Int64AbsWithOverflow(a)
                                   : Int32AbsWithOverflow(a);
  }
References v8::internal::kSystemPointerSize.
IntPtrConstant()
Node* v8::internal::compiler::RawMachineAssembler::IntPtrConstant (intptr_t value) [inline]
Definition at line 91 of file raw-machine-assembler.h.
                                       {
    // TODO(dcarney): mark generated code as unserializable if value != 0.
    return kSystemPointerSize == 8 ? Int64Constant(value)
                                   : Int32Constant(static_cast<int>(value));
  }
References v8::internal::kSystemPointerSize, and v8::internal::value.
IsMapOffsetConstant()
bool v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstant (Node * node) [inline]
Definition at line 151 of file raw-machine-assembler.h.
                                       {
    Int64Matcher m(node);
    if (m.Is(HeapObject::kMapOffset)) return true;
    // Test if `node` is a `Phi(Int64Constant(0))`
    if (node->opcode() == IrOpcode::kPhi) {
      for (Node* input : node->inputs()) {
        if (!Int64Matcher(input).Is(HeapObject::kMapOffset)) return false;
      }
      return true;
    }
    return false;
  }
References v8::internal::compiler::Node::inputs(), v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::Is(), v8::internal::HeapObject::kMapOffset, and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::CodeAssembler::IsMapOffsetConstant().
IsMapOffsetConstantMinusTag() [1/2]
bool v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstantMinusTag (int offset) [inline]
Definition at line 167 of file raw-machine-assembler.h.
                                               {
    return offset == HeapObject::kMapOffset - kHeapObjectTag;
  }
References v8::internal::kHeapObjectTag, and v8::internal::HeapObject::kMapOffset.
IsMapOffsetConstantMinusTag() [2/2]
bool v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstantMinusTag (Node * node) [inline]
Definition at line 163 of file raw-machine-assembler.h.
                                               {
    Int64Matcher m(node);
    return m.Is(HeapObject::kMapOffset - kHeapObjectTag);
  }
References v8::internal::compiler::IntMatcher< T, kOpcode >::Is(), v8::internal::kHeapObjectTag, and v8::internal::HeapObject::kMapOffset.
isolate()
Isolate* v8::internal::compiler::RawMachineAssembler::isolate () const [inline]
Definition at line 62 of file raw-machine-assembler.h.
{ return isolate_; }
Referenced by GetCurrentExternalSourcePosition(), v8::internal::compiler::CodeAssembler::isolate(), NullConstant(), SetCurrentExternalSourcePosition(), and UndefinedConstant().
Load() [1/2]
Node* v8::internal::compiler::RawMachineAssembler::Load (MachineType type, Node * base) [inline]
Definition at line 136 of file raw-machine-assembler.h.
                                           {
    return Load(type, base, IntPtrConstant(0));
  }
References v8::internal::compiler::IntPtrConstant(), v8::Load(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::CodeAssembler::Load().
Load() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::Load (MachineType type, Node * base, Node * index) [inline]
Definition at line 139 of file raw-machine-assembler.h.
                                                        {
    const Operator* op = machine()->Load(type);
    Node* load = AddNode(op, base, index);
    return load;
  }
References v8::internal::index, and v8::internal::tracing::type.
LoadFramePointer()
Node* v8::internal::compiler::RawMachineAssembler::LoadFramePointer () [inline]
Definition at line 973 of file raw-machine-assembler.h.
{ return AddNode(machine()->LoadFramePointer()); }
References LoadFramePointer().
Referenced by LoadFramePointer().
LoadFromObject()
Node* v8::internal::compiler::RawMachineAssembler::LoadFromObject (MachineType type, Node * base, Node * offset) [inline]
Definition at line 170 of file raw-machine-assembler.h.
                                                                   {
    DCHECK_IMPLIES(V8_MAP_PACKING_BOOL && IsMapOffsetConstantMinusTag(offset),
                   type == MachineType::MapInHeader());
    ObjectAccess access = {type, WriteBarrierKind::kNoWriteBarrier};
    Node* load = AddNode(simplified()->LoadFromObject(access), base, offset);
    return load;
  }
References DCHECK_IMPLIES, v8::internal::compiler::kNoWriteBarrier, v8::internal::MachineType::MapInHeader(), v8::internal::tracing::type, and V8_MAP_PACKING_BOOL.
Referenced by v8::internal::compiler::CodeAssembler::LoadFromObject().
LoadFromPointer()
Node* v8::internal::compiler::RawMachineAssembler::LoadFromPointer (void * address, MachineType type, int32_t offset = 0) [inline]
Definition at line 1009 of file raw-machine-assembler.h.
                                                                             {
    return Load(type, PointerConstant(address), Int32Constant(offset));
  }
References v8::Load(), v8::internal::compiler::PointerConstant(), and v8::internal::tracing::type.
LoadImmutable() [1/2]
Node* v8::internal::compiler::RawMachineAssembler::LoadImmutable (MachineType type, Node * base) [inline]
Definition at line 144 of file raw-machine-assembler.h.
                                                    {
    return LoadImmutable(type, base, IntPtrConstant(0));
  }
References v8::internal::compiler::IntPtrConstant(), and v8::internal::tracing::type.
LoadImmutable() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::LoadImmutable (MachineType type, Node * base, Node * index) [inline]
Definition at line 147 of file raw-machine-assembler.h.
                                                                 {
    const Operator* op = machine()->LoadImmutable(type);
    return AddNode(op, base, index);
  }
References v8::internal::index, and v8::internal::tracing::type.
LoadParentFramePointer()
Node* v8::internal::compiler::RawMachineAssembler::LoadParentFramePointer () [inline]
Definition at line 974 of file raw-machine-assembler.h.
                                 {
    return AddNode(machine()->LoadParentFramePointer());
  }
LoadProtectedPointerFromObject()
Node* v8::internal::compiler::RawMachineAssembler::LoadProtectedPointerFromObject (Node * base, Node * offset) [inline]
Definition at line 178 of file raw-machine-assembler.h.
                                                                 {
#if V8_ENABLE_SANDBOX
    static_assert(COMPRESS_POINTERS_BOOL);
    Node* tagged = LoadFromObject(MachineType::Int32(), base, offset);
    Node* trusted_cage_base =
        LoadImmutable(MachineType::Pointer(), LoadRootRegister(),
                      IntPtrConstant(IsolateData::trusted_cage_base_offset()));
    return BitcastWordToTagged(
        WordOr(trusted_cage_base, ChangeUint32ToUint64(tagged)));
#else
    return LoadFromObject(MachineType::AnyTagged(), base, offset);
#endif // V8_ENABLE_SANDBOX
  }
References v8::internal::MachineType::AnyTagged(), COMPRESS_POINTERS_BOOL, v8::internal::MachineType::Int32(), v8::internal::compiler::IntPtrConstant(), and v8::internal::MachineType::Pointer().
Referenced by v8::internal::compiler::CodeAssembler::LoadProtectedPointerFromObject().
LoadRootRegister()
Node* v8::internal::compiler::RawMachineAssembler::LoadRootRegister () [inline]
Definition at line 1006 of file raw-machine-assembler.h.
{ return AddNode(machine()->LoadRootRegister()); }
References LoadRootRegister().
Referenced by LoadRootRegister().
machine()
MachineOperatorBuilder* v8::internal::compiler::RawMachineAssembler::machine () [inline]
Definition at line 65 of file raw-machine-assembler.h.
{ return &machine_; }
Referenced by AbortCSADcheck(), Comment(), DebugBreak(), v8::internal::compiler::CodeAssembler::Is32(), v8::internal::compiler::CodeAssembler::Is64(), v8::internal::compiler::CodeAssembler::IsFloat64RoundDownSupported(), v8::internal::compiler::CodeAssembler::IsFloat64RoundTiesEvenSupported(), v8::internal::compiler::CodeAssembler::IsFloat64RoundTruncateSupported(), v8::internal::compiler::CodeAssembler::IsFloat64RoundUpSupported(), v8::internal::compiler::CodeAssembler::IsInt32AbsWithOverflowSupported(), v8::internal::compiler::CodeAssembler::IsInt64AbsWithOverflowSupported(), v8::internal::compiler::CodeAssembler::IsTruncateFloat64ToFloat16RawBitsSupported(), v8::internal::compiler::CodeAssembler::IsWord32CtzSupported(), v8::internal::compiler::CodeAssembler::IsWord32PopcntSupported(), v8::internal::compiler::CodeAssembler::IsWord64CtzSupported(), v8::internal::compiler::CodeAssembler::IsWord64PopcntSupported(), v8::internal::compiler::CodeAssembler::UnalignedLoadSupported(), v8::internal::compiler::CodeAssembler::UnalignedStoreSupported(), and v8::internal::compiler::CodeAssembler::Word32ShiftIsSafe().
MakeNode()
Node * v8::internal::compiler::RawMachineAssembler::MakeNode (const Operator * op, int input_count, Node *const * inputs) [private]
Definition at line 864 of file raw-machine-assembler.cc.
                                                         {
  // The raw machine assembler nodes do not have effect and control inputs,
  // so we disable checking input counts here.
  return graph()->NewNodeUnchecked(op, input_count, inputs);
}
References graph(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::compiler::TFGraph::NewNodeUnchecked().
Referenced by AddNode(), Branch(), PopAndReturn(), Return(), Switch(), TailCallN(), and Unreachable().
MakePhiBinary()
void v8::internal::compiler::RawMachineAssembler::MakePhiBinary (Node * phi, int split_point, Node * left_control, Node * right_control) [private]
Definition at line 396 of file raw-machine-assembler.cc.
                                                             {
  int value_count = phi->op()->ValueInputCount();
  if (value_count == 2) return;
  DCHECK_LT(split_point, value_count);
  DCHECK_GT(split_point, 0);
  MachineRepresentation rep = PhiRepresentationOf(phi->op());
  int left_input_count = split_point;
  int right_input_count = value_count - split_point;
  Node* left_input;
  if (left_input_count == 1) {
    left_input = NodeProperties::GetValueInput(phi, 0);
  } else {
    std::vector<Node*> inputs;
    inputs.reserve(left_input_count);
    for (int i = 0; i < left_input_count; ++i) {
      inputs.push_back(NodeProperties::GetValueInput(phi, i));
    }
    inputs.push_back(left_control);
    left_input =
        graph()->NewNode(common()->Phi(rep, static_cast<int>(left_input_count)),
                         static_cast<int>(inputs.size()), inputs.data());
  }
  Node* right_input;
  if (right_input_count == 1) {
    right_input = NodeProperties::GetValueInput(phi, split_point);
  } else {
    std::vector<Node*> inputs;
    for (int i = split_point; i < value_count; ++i) {
      inputs.push_back(NodeProperties::GetValueInput(phi, i));
    }
    inputs.push_back(right_control);
    right_input = graph()->NewNode(
        common()->Phi(rep, static_cast<int>(right_input_count)),
        static_cast<int>(inputs.size()), inputs.data());
  }
  Node* control = NodeProperties::GetControlInput(phi);
  phi->TrimInputCount(3);
  phi->ReplaceInput(0, left_input);
  phi->ReplaceInput(1, right_input);
  phi->ReplaceInput(2, control);
  NodeProperties::ChangeOp(phi, common()->Phi(rep, 2));
}
References v8::internal::compiler::NodeProperties::ChangeOp(), common(), DCHECK_GT, DCHECK_LT, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), Phi(), v8::internal::compiler::PhiRepresentationOf(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by MakeReschedulable().
MakeReschedulable()
void v8::internal::compiler::RawMachineAssembler::MakeReschedulable () [private]
Definition at line 224 of file raw-machine-assembler.cc.
                                            {
  std::vector<Node*> block_final_control(schedule_->all_blocks_.size());
  std::vector<Node*> block_final_effect(schedule_->all_blocks_.size());
  struct LoopHeader {
    BasicBlock* block;
    Node* loop_node;
    Node* effect_phi;
  };
  std::vector<LoopHeader> loop_headers;
  // These are hoisted outside of the loop to avoid re-allocation.
  std::vector<Node*> merge_inputs;
  std::vector<Node*> effect_phi_inputs;
  for (BasicBlock* block : *schedule_->rpo_order()) {
    Node* current_control;
    Node* current_effect;
    if (block == schedule_->start()) {
      current_control = current_effect = graph()->start();
    } else if (block == schedule_->end()) {
      for (size_t i = 0; i < block->PredecessorCount(); ++i) {
        NodeProperties::MergeControlToEnd(
            graph(), common(), block->PredecessorAt(i)->control_input());
      }
    } else if (block->IsLoopHeader()) {
      // The graph()->start() inputs are just placeholders until we computed the
      // real back-edges and re-structure the control flow so the loop has
      // exactly two predecessors.
      current_control = graph()->NewNode(common()->Loop(2), graph()->start(),
                                         graph()->start());
      current_effect =
          graph()->NewNode(common()->EffectPhi(2), graph()->start(),
                           graph()->start(), current_control);
      Node* terminate = graph()->NewNode(common()->Terminate(), current_effect,
                                         current_control);
      NodeProperties::MergeControlToEnd(graph(), common(), terminate);
      loop_headers.push_back(
          LoopHeader{block, current_control, current_effect});
    } else if (block->PredecessorCount() == 1) {
      BasicBlock* predecessor = block->PredecessorAt(0);
      DCHECK_LT(predecessor->rpo_number(), block->rpo_number());
      current_effect = block_final_effect[predecessor->id().ToSize()];
      current_control = block_final_control[predecessor->id().ToSize()];
    } else {
      // Create control merge nodes and effect phis for all predecessor blocks.
      merge_inputs.clear();
      effect_phi_inputs.clear();
      int predecessor_count = static_cast<int>(block->PredecessorCount());
      for (int i = 0; i < predecessor_count; ++i) {
        BasicBlock* predecessor = block->PredecessorAt(i);
        DCHECK_LT(predecessor->rpo_number(), block->rpo_number());
        merge_inputs.push_back(block_final_control[predecessor->id().ToSize()]);
        effect_phi_inputs.push_back(
            block_final_effect[predecessor->id().ToSize()]);
      }
      current_control = graph()->NewNode(common()->Merge(predecessor_count),
                                         static_cast<int>(merge_inputs.size()),
                                         merge_inputs.data());
      effect_phi_inputs.push_back(current_control);
      current_effect = graph()->NewNode(
          common()->EffectPhi(predecessor_count),
          static_cast<int>(effect_phi_inputs.size()), effect_phi_inputs.data());
    }
    auto update_current_control_and_effect = [&](Node* node) {
      bool existing_effect_and_control =
          IrOpcode::IsIfProjectionOpcode(node->opcode()) ||
          IrOpcode::IsPhiOpcode(node->opcode());
      if (node->op()->EffectInputCount() > 0) {
        DCHECK_EQ(1, node->op()->EffectInputCount());
        if (existing_effect_and_control) {
          NodeProperties::ReplaceEffectInput(node, current_effect);
        } else {
          node->AppendInput(graph()->zone(), current_effect);
        }
      }
      if (node->op()->ControlInputCount() > 0) {
        DCHECK_EQ(1, node->op()->ControlInputCount());
        if (existing_effect_and_control) {
          NodeProperties::ReplaceControlInput(node, current_control);
        } else {
          node->AppendInput(graph()->zone(), current_control);
        }
      }
      if (node->op()->EffectOutputCount() > 0) {
        DCHECK_EQ(1, node->op()->EffectOutputCount());
        current_effect = node;
      }
      if (node->op()->ControlOutputCount() > 0) {
        current_control = node;
      }
    };
    for (Node* node : *block) {
      update_current_control_and_effect(node);
    }
    if (block->deferred()) MarkControlDeferred(current_control);
    if (Node* block_terminator = block->control_input()) {
      update_current_control_and_effect(block_terminator);
    }
    block_final_effect[block->id().ToSize()] = current_effect;
    block_final_control[block->id().ToSize()] = current_control;
  }
  // Fix-up loop backedges and re-structure control flow so that loop nodes have
  // exactly two control predecessors.
  for (const LoopHeader& loop_header : loop_headers) {
    BasicBlock* block = loop_header.block;
    std::vector<BasicBlock*> loop_entries;
    std::vector<BasicBlock*> loop_backedges;
    for (size_t i = 0; i < block->PredecessorCount(); ++i) {
      BasicBlock* predecessor = block->PredecessorAt(i);
      if (block->LoopContains(predecessor)) {
        loop_backedges.push_back(predecessor);
      } else {
        DCHECK(loop_backedges.empty());
        loop_entries.push_back(predecessor);
      }
    }
    DCHECK(!loop_entries.empty());
    DCHECK(!loop_backedges.empty());
    int entrance_count = static_cast<int>(loop_entries.size());
    int backedge_count = static_cast<int>(loop_backedges.size());
    Node* control_loop_entry = CreateNodeFromPredecessors(
        loop_entries, block_final_control, common()->Merge(entrance_count), {});
    Node* control_backedge =
        CreateNodeFromPredecessors(loop_backedges, block_final_control,
                                   common()->Merge(backedge_count), {});
    Node* effect_loop_entry = CreateNodeFromPredecessors(
        loop_entries, block_final_effect, common()->EffectPhi(entrance_count),
        {control_loop_entry});
    Node* effect_backedge = CreateNodeFromPredecessors(
        loop_backedges, block_final_effect, common()->EffectPhi(backedge_count),
        {control_backedge});
    loop_header.loop_node->ReplaceInput(0, control_loop_entry);
    loop_header.loop_node->ReplaceInput(1, control_backedge);
    loop_header.effect_phi->ReplaceInput(0, effect_loop_entry);
    loop_header.effect_phi->ReplaceInput(1, effect_backedge);
    for (Node* node : *block) {
      if (node->opcode() == IrOpcode::kPhi) {
        MakePhiBinary(node, static_cast<int>(loop_entries.size()),
                      control_loop_entry, control_backedge);
      }
    }
  }
}
References v8::internal::compiler::Schedule::all_blocks_, common(), CreateNodeFromPredecessors(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::compiler::Schedule::end(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::IrOpcode::IsIfProjectionOpcode(), v8::internal::compiler::IrOpcode::IsPhiOpcode(), v8::internal::compiler::BasicBlock::LoopContains(), MakePhiBinary(), MarkControlDeferred(), v8::internal::compiler::NodeProperties::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::BasicBlock::PredecessorAt(), v8::internal::compiler::BasicBlock::PredecessorCount(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), schedule_, v8::internal::ZoneVector< T >::size(), v8::internal::compiler::Schedule::start(), v8::internal::compiler::TFGraph::start(), v8::internal::Terminate(), v8::internal::compiler::BasicBlock::Id::ToSize(), and zone().
Referenced by ExportForOptimization().
MarkControlDeferred()
void v8::internal::compiler::RawMachineAssembler::MarkControlDeferred (Node * control_input) [private]
Definition at line 445 of file raw-machine-assembler.cc.
                                                                {
  BranchHint new_branch_hint;
  Node* responsible_branch = nullptr;
  while (responsible_branch == nullptr) {
    switch (control_node->opcode()) {
      case IrOpcode::kIfException:
        // IfException projections are deferred by default.
        return;
      case IrOpcode::kIfSuccess:
        control_node = NodeProperties::GetControlInput(control_node);
        continue;
      case IrOpcode::kIfValue: {
        IfValueParameters parameters = IfValueParametersOf(control_node->op());
        if (parameters.hint() != BranchHint::kFalse) {
          NodeProperties::ChangeOp(
              control_node, common()->IfValue(parameters.value(),
                                              parameters.comparison_order(),
                                              BranchHint::kFalse));
        }
        return;
      }
      case IrOpcode::kIfDefault:
        if (BranchHintOf(control_node->op()) != BranchHint::kFalse) {
          NodeProperties::ChangeOp(control_node,
                                   common()->IfDefault(BranchHint::kFalse));
        }
        return;
      case IrOpcode::kIfTrue: {
        Node* branch = NodeProperties::GetControlInput(control_node);
        BranchHint hint = BranchHintOf(branch->op());
        if (hint == BranchHint::kTrue) {
          // The other possibility is also deferred, so the responsible branch
          // has to be before.
          control_node = NodeProperties::GetControlInput(branch);
          continue;
        }
        new_branch_hint = BranchHint::kFalse;
        responsible_branch = branch;
        break;
      }
      case IrOpcode::kIfFalse: {
        Node* branch = NodeProperties::GetControlInput(control_node);
        BranchHint hint = BranchHintOf(branch->op());
        if (hint == BranchHint::kFalse) {
          // The other possibility is also deferred, so the responsible branch
          // has to be before.
          control_node = NodeProperties::GetControlInput(branch);
          continue;
        }
        new_branch_hint = BranchHint::kTrue;
        responsible_branch = branch;
        break;
      }
      case IrOpcode::kMerge:
        for (int i = 0; i < control_node->op()->ControlInputCount(); ++i) {
          MarkControlDeferred(NodeProperties::GetControlInput(control_node, i));
        }
        return;
      case IrOpcode::kLoop:
        control_node = NodeProperties::GetControlInput(control_node, 0);
        continue;
      case IrOpcode::kBranch:
      case IrOpcode::kSwitch:
        UNREACHABLE();
      case IrOpcode::kStart:
        return;
      default:
        DCHECK_EQ(1, control_node->op()->ControlInputCount());
        control_node = NodeProperties::GetControlInput(control_node);
        continue;
    }
  }
  BranchHint hint = BranchHintOf(responsible_branch->op());
  if (hint == new_branch_hint) return;
  NodeProperties::ChangeOp(responsible_branch,
                           common()->Branch(new_branch_hint));
}
References Branch(), v8::internal::compiler::BranchHintOf(), v8::internal::compiler::NodeProperties::ChangeOp(), common(), v8::internal::compiler::IfValueParameters::comparison_order(), v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::IfValueParameters::hint(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::IfValueParametersOf(), v8::internal::compiler::turboshaft::kBranch, v8::internal::kFalse, v8::kStart, v8::internal::wasm::kSwitch, v8::internal::kTrue, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::UNREACHABLE(), and v8::internal::compiler::IfValueParameters::value().
Referenced by MakeReschedulable().
MemoryBarrier()
Node* v8::internal::compiler::RawMachineAssembler::MemoryBarrier (AtomicMemoryOrder order) [inline]
Definition at line 371 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->MemoryBarrier(order));
  }
Referenced by v8::internal::compiler::CodeAssembler::MemoryBarrier().
NullConstant()
Node * v8::internal::compiler::RawMachineAssembler::NullConstant ()
Definition at line 68 of file raw-machine-assembler.cc.
                                        {
  return HeapConstant(isolate()->factory()->null_value());
}
References HeapConstant(), and isolate().
NumberConstant()
Node* v8::internal::compiler::RawMachineAssembler::NumberConstant (double value) [inline]
Definition at line 109 of file raw-machine-assembler.h.
                                     {
    return AddNode(common()->NumberConstant(value));
  }
References v8::internal::compiler::NumberConstant(), and v8::internal::value.
operator=()
RawMachineAssembler& v8::internal::compiler::RawMachineAssembler::operator= (const RawMachineAssembler &) [delete]
OptimizeControlFlow()
void v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow (Schedule * schedule, TFGraph * graph, CommonOperatorBuilder * common) [static], [private]
Definition at line 130 of file raw-machine-assembler.cc.
                                                                             {
  for (bool changed = true; changed;) {
    changed = false;
    for (size_t i = 0; i < schedule->all_blocks()->size(); ++i) {
      BasicBlock* block = (*schedule->all_blocks())[i];
      if (block == nullptr) continue;
      // Short-circuit a goto if the succeeding block is not a control-flow
      // merge. This is not really useful on it's own since graph construction
      // has the same effect, but combining blocks improves the pattern-match on
      // their structure below.
      if (block->control() == BasicBlock::kGoto) {
        DCHECK_EQ(block->SuccessorCount(), 1);
        BasicBlock* successor = block->SuccessorAt(0);
        if (successor->PredecessorCount() == 1) {
          DCHECK_EQ(successor->PredecessorAt(0), block);
          for (Node* node : *successor) {
            schedule->SetBlockForNode(nullptr, node);
            schedule->AddNode(block, node);
          }
          block->set_control(successor->control());
          Node* control_input = successor->control_input();
          block->set_control_input(control_input);
          if (control_input) {
            schedule->SetBlockForNode(block, control_input);
          }
          if (successor->deferred()) block->set_deferred(true);
          block->ClearSuccessors();
          schedule->MoveSuccessors(successor, block);
          schedule->ClearBlockById(successor->id());
          changed = true;
          --i;
          continue;
        }
      }
      // Block-cloning in the simple case where a block consists only of a phi
      // node and a branch on that phi. This just duplicates the branch block
      // for each predecessor, replacing the phi node with the corresponding phi
      // input.
      if (block->control() == BasicBlock::kBranch && block->NodeCount() == 1) {
        Node* phi = block->NodeAt(0);
        if (phi->opcode() != IrOpcode::kPhi) continue;
        Node* branch = block->control_input();
        DCHECK_EQ(branch->opcode(), IrOpcode::kBranch);
        if (NodeProperties::GetValueInput(branch, 0) != phi) continue;
        if (phi->UseCount() != 1) continue;
        DCHECK_EQ(phi->op()->ValueInputCount(), block->PredecessorCount());
        // Turn projection blocks into normal blocks.
        DCHECK_EQ(block->SuccessorCount(), 2);
        BasicBlock* true_block = block->SuccessorAt(0);
        BasicBlock* false_block = block->SuccessorAt(1);
        DCHECK_EQ(true_block->NodeAt(0)->opcode(), IrOpcode::kIfTrue);
        DCHECK_EQ(false_block->NodeAt(0)->opcode(), IrOpcode::kIfFalse);
        (*true_block->begin())->Kill();
        true_block->RemoveNode(true_block->begin());
        (*false_block->begin())->Kill();
        false_block->RemoveNode(false_block->begin());
        true_block->ClearPredecessors();
        false_block->ClearPredecessors();
        size_t arity = block->PredecessorCount();
        for (size_t j = 0; j < arity; ++j) {
          BasicBlock* predecessor = block->PredecessorAt(j);
          predecessor->ClearSuccessors();
          if (block->deferred()) predecessor->set_deferred(true);
          Node* branch_clone = graph->CloneNode(branch);
          int phi_input = static_cast<int>(j);
          NodeProperties::ReplaceValueInput(
              branch_clone, NodeProperties::GetValueInput(phi, phi_input), 0);
          BasicBlock* new_true_block = schedule->NewBasicBlock();
          BasicBlock* new_false_block = schedule->NewBasicBlock();
          new_true_block->AddNode(
              graph->NewNode(common->IfTrue(), branch_clone));
          new_false_block->AddNode(
              graph->NewNode(common->IfFalse(), branch_clone));
          schedule->AddGoto(new_true_block, true_block);
          schedule->AddGoto(new_false_block, false_block);
          DCHECK_EQ(predecessor->control(), BasicBlock::kGoto);
          predecessor->set_control(BasicBlock::kNone);
          schedule->AddBranch(predecessor, branch_clone, new_true_block,
                              new_false_block);
        }
        branch->Kill();
        schedule->ClearBlockById(block->id());
        changed = true;
        continue;
      }
    }
  }
}
References v8::internal::compiler::Schedule::AddBranch(), v8::internal::compiler::Schedule::AddGoto(), v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::BasicBlock::AddNode(), v8::internal::compiler::Schedule::all_blocks(), v8::internal::compiler::BasicBlock::begin(), v8::internal::compiler::Schedule::ClearBlockById(), v8::internal::compiler::BasicBlock::ClearPredecessors(), v8::internal::compiler::BasicBlock::ClearSuccessors(), v8::internal::compiler::TFGraph::CloneNode(), common(), v8::internal::compiler::BasicBlock::control(), v8::internal::compiler::BasicBlock::control_input(), DCHECK_EQ, v8::internal::compiler::BasicBlock::deferred(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::CommonOperatorBuilder::IfFalse(), v8::internal::compiler::CommonOperatorBuilder::IfTrue(), v8::internal::compiler::BasicBlock::kBranch, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::BasicBlock::kGoto, v8::internal::compiler::Node::Kill(), v8::internal::compiler::BasicBlock::kNone, v8::internal::compiler::Schedule::MoveSuccessors(), v8::internal::compiler::Schedule::NewBasicBlock(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::BasicBlock::NodeAt(), v8::internal::compiler::BasicBlock::NodeCount(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::BasicBlock::PredecessorAt(), v8::internal::compiler::BasicBlock::PredecessorCount(), v8::internal::compiler::BasicBlock::RemoveNode(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), schedule(), v8::internal::compiler::BasicBlock::set_control(), v8::internal::compiler::BasicBlock::set_control_input(), v8::internal::compiler::BasicBlock::set_deferred(), v8::internal::compiler::Schedule::SetBlockForNode(), size(), v8::internal::compiler::BasicBlock::SuccessorAt(), v8::internal::compiler::BasicBlock::SuccessorCount(), v8::internal::compiler::Node::UseCount(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by ExportForOptimization().
OptimizedAllocate()
Node * v8::internal::compiler::RawMachineAssembler::OptimizedAllocate (Node * size, AllocationType allocation)
Definition at line 83 of file raw-machine-assembler.cc.
                                                                        {
  return AddNode(simplified()->AllocateRaw(Type::Any(), allocation), size);
}
References AddNode(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::compiler::turboshaft::Type::Any(), simplified(), and size().
OptimizedStoreField()
void v8::internal::compiler::RawMachineAssembler::OptimizedStoreField (MachineRepresentation rep, Node * object, int offset, Node * value, WriteBarrierKind write_barrier) [inline]
Definition at line 208 of file raw-machine-assembler.h.
                                                                        {
    DCHECK(!IsMapOffsetConstantMinusTag(offset));
    DCHECK_NE(rep, MachineRepresentation::kIndirectPointer);
    AddNode(simplified()->StoreField(
                FieldAccess(BaseTaggedness::kTaggedBase, offset,
                            MaybeHandle<Name>(), OptionalMapRef(), Type::Any(),
                            MachineType::TypeForRepresentation(rep),
                            write_barrier, "OptimizedStoreField")),
            object, value);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::kIndirectPointer, v8::internal::compiler::kTaggedBase, v8::internal::MachineType::TypeForRepresentation(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::OptimizedStoreField(), v8::internal::compiler::CodeAssembler::OptimizedStoreFieldAssertNoWriteBarrier(), and v8::internal::compiler::CodeAssembler::OptimizedStoreFieldUnsafeNoWriteBarrier().
OptimizedStoreIndirectPointerField()
void v8::internal::compiler::RawMachineAssembler::OptimizedStoreIndirectPointerField (Node * object, int offset, IndirectPointerTag tag, Node * value, WriteBarrierKind write_barrier) [inline]
Definition at line 219 of file raw-machine-assembler.h.
                                                                          {
    DCHECK(!IsMapOffsetConstantMinusTag(offset));
    DCHECK(write_barrier == WriteBarrierKind::kNoWriteBarrier ||
           write_barrier == WriteBarrierKind::kIndirectPointerWriteBarrier);
    FieldAccess access(BaseTaggedness::kTaggedBase, offset, MaybeHandle<Name>(),
                       OptionalMapRef(), Type::Any(),
                       MachineType::IndirectPointer(), write_barrier,
                       "OptimizedStoreIndirectPointerField");
    access.indirect_pointer_tag = tag;
    AddNode(simplified()->StoreField(access), object, value);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::DCHECK(), v8::internal::compiler::FieldAccess::indirect_pointer_tag, v8::internal::MachineType::IndirectPointer(), v8::internal::compiler::kIndirectPointerWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::OptimizedStoreIndirectPointerField(), and v8::internal::compiler::CodeAssembler::OptimizedStoreIndirectPointerFieldNoWriteBarrier().
OptimizedStoreMap()
void v8::internal::compiler::RawMachineAssembler::OptimizedStoreMap (Node * object, Node * value, WriteBarrierKind write_barrier = kMapWriteBarrier) [inline]
Definition at line 232 of file raw-machine-assembler.h.
                                                                            {
    AddNode(simplified()->StoreField(AccessBuilder::ForMap(write_barrier)),
            object, value);
  }
References v8::internal::compiler::AccessBuilder::ForMap(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::OptimizedStoreMap().
Parameter()
Node * v8::internal::compiler::RawMachineAssembler::Parameter (size_t index)
Definition at line 529 of file raw-machine-assembler.cc.
                                                 {
  DCHECK_LT(index, parameter_count());
  return parameters_[index];
}
References DCHECK_LT, v8::internal::index, parameter_count(), and parameters_.
Referenced by RawMachineAssembler(), and v8::internal::compiler::CodeAssembler::UntypedParameter().
parameter_count()
size_t v8::internal::compiler::RawMachineAssembler::parameter_count () const [inline]
Definition at line 1167 of file raw-machine-assembler.h.
{ return call_descriptor_->ParameterCount(); }
Referenced by Parameter(), and RawMachineAssembler().
Phi() [1/4]
Node * v8::internal::compiler::RawMachineAssembler::Phi (MachineRepresentation rep, int input_count, Node *const * inputs)
Definition at line 840 of file raw-machine-assembler.cc.
                                                    {
  Node** buffer = zone()->AllocateArray<Node*>(input_count + 1);
  std::copy(inputs, inputs + input_count, buffer);
  buffer[input_count] = graph()->start();
  return AddNode(common()->Phi(rep, input_count), input_count + 1, buffer);
}
References AddNode(), v8::internal::Zone::AllocateArray(), common(), graph(), v8::internal::compiler::turboshaft::detail::input_count(), Phi(), v8::internal::compiler::TFGraph::start(), and zone().
Phi() [2/4]
Node* v8::internal::compiler::RawMachineAssembler::Phi (MachineRepresentation rep, Node * n1, Node * n2) [inline]
Definition at line 1133 of file raw-machine-assembler.h.
                                                           {
    return AddNode(common()->Phi(rep, 2), n1, n2, graph()->start());
  }
References graph().
Referenced by MakePhiBinary(), and Phi().
Phi() [3/4]
Node* v8::internal::compiler::RawMachineAssembler::Phi (MachineRepresentation rep, Node * n1, Node * n2, Node * n3) [inline]
Definition at line 1136 of file raw-machine-assembler.h.
                                                                     {
    return AddNode(common()->Phi(rep, 3), n1, n2, n3, graph()->start());
  }
References graph().
Phi() [4/4]
Node* v8::internal::compiler::RawMachineAssembler::Phi (MachineRepresentation rep, Node * n1, Node * n2, Node * n3, Node * n4) [inline]
Definition at line 1139 of file raw-machine-assembler.h.
                                                                               {
    return AddNode(common()->Phi(rep, 4), n1, n2, n3, n4, graph()->start());
  }
References graph().
PointerConstant()
Node* v8::internal::compiler::RawMachineAssembler::PointerConstant (void * value) [inline]
Definition at line 88 of file raw-machine-assembler.h.
                                     {
    return IntPtrConstant(reinterpret_cast<intptr_t>(value));
  }
References v8::internal::compiler::IntPtrConstant(), and v8::internal::value.
PopAndReturn() [1/4]
void v8::internal::compiler::RawMachineAssembler::PopAndReturn (Node * pop, Node * v1, Node * v2)
Definition at line 654 of file raw-machine-assembler.cc.
                                                                    {
  Node* values[] = {pop, v1, v2};
  Node* ret = MakeNode(common()->Return(2), 3, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), MakeNode(), Return(), and schedule().
PopAndReturn() [2/4]
void v8::internal::compiler::RawMachineAssembler::PopAndReturn (Node * pop, Node * v1, Node * v2, Node * v3)
Definition at line 661 of file raw-machine-assembler.cc.
                                                 {
  Node* values[] = {pop, v1, v2, v3};
  Node* ret = MakeNode(common()->Return(3), 4, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), MakeNode(), Return(), and schedule().
PopAndReturn() [3/4]
void v8::internal::compiler::RawMachineAssembler::PopAndReturn (Node * pop, Node * v1, Node * v2, Node * v3, Node * v4)
Definition at line 669 of file raw-machine-assembler.cc.
                                                 {
  Node* values[] = {pop, v1, v2, v3, v4};
  Node* ret = MakeNode(common()->Return(4), 5, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), MakeNode(), Return(), and schedule().
PopAndReturn() [4/4]
void v8::internal::compiler::RawMachineAssembler::PopAndReturn (Node * pop, Node * value)
Definition at line 632 of file raw-machine-assembler.cc.
                                                             {
  // PopAndReturn is supposed to be used ONLY in CSA/Torque builtins for
  // dropping ALL JS arguments that are currently located on the stack.
  // The check below ensures that there are no directly accessible stack
  // parameters from current builtin, which implies that the builtin with
  // JS calling convention (TFJ) was created with kDontAdaptArgumentsSentinel.
  // This simplifies semantics of this instruction because in case of presence
  // of directly accessible stack parameters it's impossible to distinguish
  // the following cases:
  // 1) stack parameter is included in JS arguments (and therefore it will be
  // dropped as a part of 'pop' number of arguments),
  // 2) stack parameter is NOT included in JS arguments (and therefore it should
  // be dropped in ADDITION to the 'pop' number of arguments).
  // Additionally, in order to simplify assembly code, PopAndReturn is also
  // not allowed in builtins with stub linkage and parameters on stack.
  CHECK_EQ(call_descriptor()->ParameterSlotCount(), 0);
  Node* values[] = {pop, value};
  Node* ret = MakeNode(common()->Return(1), 2, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), call_descriptor(), CHECK_EQ, common(), current_block_, CurrentBlock(), MakeNode(), Return(), schedule(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::PopAndReturn().
Projection()
Node* v8::internal::compiler::RawMachineAssembler::Projection (int index, Node * a) [inline]
Definition at line 131 of file raw-machine-assembler.h.
                                       {
    return AddNode(common()->Projection(index), a);
  }
References v8::internal::index.
Referenced by v8::internal::compiler::CodeAssembler::Projection().
RelocatableInt32Constant()
Node* v8::internal::compiler::RawMachineAssembler::RelocatableInt32Constant (int32_t value, RelocInfo::Mode rmode) [inline]
Definition at line 124 of file raw-machine-assembler.h.
                                                                     {
    return AddNode(common()->RelocatableInt32Constant(value, rmode));
  }
References v8::internal::value.
Referenced by RelocatableIntPtrConstant().
RelocatableInt64Constant()
Node* v8::internal::compiler::RawMachineAssembler::RelocatableInt64Constant (int64_t value, RelocInfo::Mode rmode) [inline]
Definition at line 127 of file raw-machine-assembler.h.
                                                                     {
    return AddNode(common()->RelocatableInt64Constant(value, rmode));
  }
References v8::internal::value.
Referenced by RelocatableIntPtrConstant().
RelocatableIntPtrConstant()
Node * v8::internal::compiler::RawMachineAssembler::RelocatableIntPtrConstant (intptr_t value, RelocInfo::Mode rmode)
Definition at line 76 of file raw-machine-assembler.cc.
                                                                          {
  return kSystemPointerSize == 8
             ? RelocatableInt64Constant(value, rmode)
             : RelocatableInt32Constant(static_cast<int>(value), rmode);
}
References v8::internal::kSystemPointerSize, RelocatableInt32Constant(), RelocatableInt64Constant(), and v8::internal::value.
Retain()
Node* v8::internal::compiler::RawMachineAssembler::Retain (Node * value) [inline]
Definition at line 237 of file raw-machine-assembler.h.
{ return AddNode(common()->Retain(), value); }
References Retain(), and v8::internal::value.
Referenced by Retain().
Return() [1/5]
void v8::internal::compiler::RawMachineAssembler::Return (int count, Node * v[])
Definition at line 621 of file raw-machine-assembler.cc.
                                                      {
  using Node_ptr = Node*;
  Node** values = new Node_ptr[count + 1];
  values[0] = Int32Constant(0);
  for (int i = 0; i < count; ++i) values[i + 1] = vs[i];
  Node* ret = MakeNode(common()->Return(count), count + 1, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
  delete[] values;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, Int32Constant(), MakeNode(), Return(), schedule(), and v8::internal::vs.
Return() [2/5]
void v8::internal::compiler::RawMachineAssembler::Return (Node * v1, Node * v2)
Definition at line 600 of file raw-machine-assembler.cc.
                                                   {
  Node* values[] = {Int32Constant(0), v1, v2};
  Node* ret = MakeNode(common()->Return(2), 3, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), Int32Constant(), MakeNode(), Return(), and schedule().
Return() [3/5]
void v8::internal::compiler::RawMachineAssembler::Return (Node * v1, Node * v2, Node * v3)
Definition at line 607 of file raw-machine-assembler.cc.
                                                             {
  Node* values[] = {Int32Constant(0), v1, v2, v3};
  Node* ret = MakeNode(common()->Return(3), 4, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), Int32Constant(), MakeNode(), Return(), and schedule().
Return() [4/5]
void v8::internal::compiler::RawMachineAssembler::Return (Node * v1, Node * v2, Node * v3, Node * v4)
Definition at line 614 of file raw-machine-assembler.cc.
                                                                       {
  Node* values[] = {Int32Constant(0), v1, v2, v3, v4};
  Node* ret = MakeNode(common()->Return(4), 5, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), Int32Constant(), MakeNode(), Return(), and schedule().
Return() [5/5]
void v8::internal::compiler::RawMachineAssembler::Return (Node * value)
Definition at line 593 of file raw-machine-assembler.cc.
                                            {
  Node* values[] = {Int32Constant(0), value};
  Node* ret = MakeNode(common()->Return(1), 2, values);
  schedule()->AddReturn(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddReturn(), common(), current_block_, CurrentBlock(), Int32Constant(), MakeNode(), schedule(), and v8::internal::value.
Referenced by PopAndReturn(), Return(), and v8::internal::compiler::CodeAssembler::Return().
RoundFloat64ToInt32()
Node* v8::internal::compiler::RawMachineAssembler::RoundFloat64ToInt32 (Node * a) [inline]
Definition at line 888 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->RoundFloat64ToInt32(), a);
  }
RoundInt32ToFloat32()
Node* v8::internal::compiler::RawMachineAssembler::RoundInt32ToFloat32 (Node * a) [inline]
Definition at line 891 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->RoundInt32ToFloat32(), a);
  }
RoundInt64ToFloat32()
Node* v8::internal::compiler::RawMachineAssembler::RoundInt64ToFloat32 (Node * a) [inline]
Definition at line 894 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->RoundInt64ToFloat32(), a);
  }
RoundInt64ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::RoundInt64ToFloat64 (Node * a) [inline]
Definition at line 897 of file raw-machine-assembler.h.
                                     {
    return AddNode(machine()->RoundInt64ToFloat64(), a);
  }
RoundUint32ToFloat32()
Node* v8::internal::compiler::RawMachineAssembler::RoundUint32ToFloat32 (Node * a) [inline]
Definition at line 900 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->RoundUint32ToFloat32(), a);
  }
RoundUint64ToFloat32()
Node* v8::internal::compiler::RawMachineAssembler::RoundUint64ToFloat32 (Node * a) [inline]
Definition at line 903 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->RoundUint64ToFloat32(), a);
  }
RoundUint64ToFloat64()
Node* v8::internal::compiler::RawMachineAssembler::RoundUint64ToFloat64 (Node * a) [inline]
Definition at line 906 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->RoundUint64ToFloat64(), a);
  }
schedule()
Schedule* v8::internal::compiler::RawMachineAssembler::schedule () [inline], [private]
Definition at line 1211 of file raw-machine-assembler.h.
{ return schedule_; }
Referenced by AddNode(), Branch(), Continuations(), EnsureBlock(), ExportForTest(), Goto(), OptimizeControlFlow(), PopAndReturn(), Return(), Switch(), TailCallN(), and Unreachable().
set_dynamic_js_parameter_count()
void v8::internal::compiler::RawMachineAssembler::set_dynamic_js_parameter_count (Node * parameter_count) [inline]
Definition at line 1189 of file raw-machine-assembler.h.
                                                             {
    dynamic_js_parameter_count_ = parameter_count;
  }
Referenced by v8::internal::compiler::CodeAssembler::SetDynamicJSParameterCount().
SetCurrentExternalSourcePosition()
void v8::internal::compiler::RawMachineAssembler::SetCurrentExternalSourcePosition (FileAndLine file_and_line)
Definition at line 50 of file raw-machine-assembler.cc.
                               {
  int file_id =
      isolate()->LookupOrAddExternallyCompiledFilename(file_and_line.first);
  SourcePosition p = SourcePosition::External(file_and_line.second, file_id);
  DCHECK_EQ(p.ExternalLine(), file_and_line.second);
  source_positions()->SetCurrentPosition(p);
}
References DCHECK_EQ, v8::internal::SourcePosition::External(), v8::internal::SourcePosition::ExternalLine(), isolate(), v8::internal::Isolate::LookupOrAddExternallyCompiledFilename(), v8::internal::compiler::SourcePositionTable::SetCurrentPosition(), and source_positions().
Referenced by v8::internal::compiler::CodeAssembler::SetSourcePosition().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::RawMachineAssembler::simplified () [inline]
Definition at line 67 of file raw-machine-assembler.h.
{ return &simplified_; }
Referenced by OptimizedAllocate().
source_positions()
SourcePositionTable* v8::internal::compiler::RawMachineAssembler::source_positions () [inline]
Definition at line 1164 of file raw-machine-assembler.h.
{ return source_positions_; }
Referenced by SetCurrentExternalSourcePosition().
StackPointerGreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::StackPointerGreaterThan (Node * value) [inline]
Definition at line 626 of file raw-machine-assembler.h.
                                             {
    return AddNode(
        machine()->StackPointerGreaterThan(StackCheckKind::kCodeStubAssembler),
        value);
  }
References v8::internal::compiler::kCodeStubAssembler, and v8::internal::value.
StackSlot() [1/2]
Node* v8::internal::compiler::RawMachineAssembler::StackSlot (int size, int alignment) [inline]
Definition at line 103 of file raw-machine-assembler.h.
                                           {
    return AddNode(machine()->StackSlot(size, alignment));
  }
References size().
StackSlot() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::StackSlot (MachineRepresentation rep, int alignment = 0) [inline]
Definition at line 100 of file raw-machine-assembler.h.
                                                                {
    return AddNode(machine()->StackSlot(rep, alignment));
  }
StaticAssert()
void v8::internal::compiler::RawMachineAssembler::StaticAssert (Node * value, const char * source)
Definition at line 696 of file raw-machine-assembler.cc.
                                                                      {
  AddNode(common()->StaticAssert(source), value);
}
References AddNode(), common(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::StaticAssert().
Store() [1/2]
Node* v8::internal::compiler::RawMachineAssembler::Store (MachineRepresentation rep, Node * base, Node * index, Node * value, WriteBarrierKind write_barrier) [inline]
Definition at line 196 of file raw-machine-assembler.h.
                                              {
    return AddNode(machine()->Store(StoreRepresentation(rep, write_barrier)),
                   base, index, value);
  }
References v8::internal::index, v8::internal::wasm::liftoff::Store(), and v8::internal::value.
Store() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::Store (MachineRepresentation rep, Node * base, Node * value, WriteBarrierKind write_barrier) [inline]
Definition at line 192 of file raw-machine-assembler.h.
                                              {
    return Store(rep, base, IntPtrConstant(0), value, write_barrier);
  }
References v8::internal::compiler::IntPtrConstant(), v8::internal::wasm::liftoff::Store(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::Store(), v8::internal::compiler::CodeAssembler::StoreEphemeronKey(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), and v8::internal::compiler::CodeAssembler::UnsafeStoreNoWriteBarrier().
StoreToObject()
void v8::internal::compiler::RawMachineAssembler::StoreToObject (MachineRepresentation rep, Node * object, Node * offset, Node * value, WriteBarrierKind write_barrier) [inline]
Definition at line 201 of file raw-machine-assembler.h.
                                                                  {
    ObjectAccess access = {MachineType::TypeForRepresentation(rep),
                           write_barrier};
    DCHECK(!IsMapOffsetConstantMinusTag(offset));
    AddNode(simplified()->StoreToObject(access), object, offset, value);
  }
References v8::internal::DCHECK(), v8::internal::MachineType::TypeForRepresentation(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeAssembler::StoreToObject().
StoreToPointer()
Node* v8::internal::compiler::RawMachineAssembler::StoreToPointer (void * address, MachineRepresentation rep, Node * node) [inline]
Definition at line 1012 of file raw-machine-assembler.h.
                                                                             {
    return Store(rep, PointerConstant(address), node, kNoWriteBarrier);
  }
References v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::PointerConstant(), and v8::internal::wasm::liftoff::Store().
StringConstant()
Node* v8::internal::compiler::RawMachineAssembler::StringConstant (const char * string) [inline]
Definition at line 1023 of file raw-machine-assembler.h.
                                           {
    return HeapConstant(isolate()->factory()->InternalizeUtf8String(string));
  }
Switch()
void v8::internal::compiler::RawMachineAssembler::Switch (Node * index, RawMachineLabel * default_label, const int32_t * case_values, RawMachineLabel ** case_labels, size_t case_count)
Definition at line 567 of file raw-machine-assembler.cc.
                                                    {
  DCHECK_NE(schedule()->end(), current_block_);
  size_t succ_count = case_count + 1;
  Node* switch_node = MakeNode(common()->Switch(succ_count), 1, &index);
  BasicBlock** succ_blocks = zone()->AllocateArray<BasicBlock*>(succ_count);
  for (size_t i = 0; i < case_count; ++i) {
    int32_t case_value = case_values[i];
    BasicBlock* case_block = schedule()->NewBasicBlock();
    Node* case_node =
        graph()->NewNode(common()->IfValue(case_value), switch_node);
    schedule()->AddNode(case_block, case_node);
    schedule()->AddGoto(case_block, Use(case_labels[i]));
    succ_blocks[i] = case_block;
  }
  BasicBlock* default_block = schedule()->NewBasicBlock();
  Node* default_node = graph()->NewNode(common()->IfDefault(), switch_node);
  schedule()->AddNode(default_block, default_node);
  schedule()->AddGoto(default_block, Use(default_label));
  succ_blocks[case_count] = default_block;
  schedule()->AddSwitch(CurrentBlock(), switch_node, succ_blocks, succ_count);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddGoto(), v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::Schedule::AddSwitch(), v8::internal::Zone::AllocateArray(), common(), current_block_, CurrentBlock(), DCHECK_NE, v8::internal::compiler::end(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, MakeNode(), v8::internal::compiler::Schedule::NewBasicBlock(), v8::internal::compiler::TFGraph::NewNode(), schedule(), Use(), and zone().
Referenced by v8::internal::compiler::CodeAssembler::Switch().
TailCallN()
void v8::internal::compiler::RawMachineAssembler::TailCallN (CallDescriptor * call_descriptor, int input_count, Node *const * inputs)
Definition at line 717 of file raw-machine-assembler.cc.
                                                                          {
  // +1 is for target.
  DCHECK_EQ(input_count, call_descriptor->ParameterCount() + 1);
  Node* tail_call =
      MakeNode(common()->TailCall(call_descriptor), input_count, inputs);
  schedule()->AddTailCall(CurrentBlock(), tail_call);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddTailCall(), call_descriptor(), common(), current_block_, CurrentBlock(), DCHECK_EQ, v8::internal::compiler::turboshaft::detail::input_count(), MakeNode(), v8::internal::compiler::CallDescriptor::ParameterCount(), and schedule().
Referenced by v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch(), v8::internal::compiler::CodeAssembler::TailCallJSCode(), v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl(), v8::internal::compiler::CodeAssembler::TailCallStubImpl(), and v8::internal::compiler::CodeAssembler::TailCallStubThenBytecodeDispatchImpl().
TargetParameter()
Node * v8::internal::compiler::RawMachineAssembler::TargetParameter ()
Definition at line 524 of file raw-machine-assembler.cc.
                                           {
  DCHECK_NOT_NULL(target_parameter_);
  return target_parameter_;
}
References DCHECK_NOT_NULL, and target_parameter_.
Referenced by v8::internal::compiler::CodeAssembler::UntypedParameter().
TruncateFloat32ToInt32()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat32ToInt32 (Node * a, TruncateKind kind) [inline]
Definition at line 838 of file raw-machine-assembler.h.
                                                           {
    return AddNode(machine()->TruncateFloat32ToInt32(kind), a);
  }
TruncateFloat32ToUint32()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat32ToUint32 (Node * a, TruncateKind kind) [inline]
Definition at line 841 of file raw-machine-assembler.h.
                                                            {
    return AddNode(machine()->TruncateFloat32ToUint32(kind), a);
  }
TruncateFloat64ToFloat16RawBits()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat64ToFloat16RawBits (Node * a) [inline]
Definition at line 881 of file raw-machine-assembler.h.
                                                 {
    return AddNode(machine()->TruncateFloat64ToFloat16RawBits().placeholder(),
                   a);
  }
TruncateFloat64ToFloat32()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat64ToFloat32 (Node * a) [inline]
Definition at line 878 of file raw-machine-assembler.h.
                                          {
    return AddNode(machine()->TruncateFloat64ToFloat32(), a);
  }
TruncateFloat64ToInt64()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat64ToInt64 (Node * a, TruncateKind kind) [inline]
Definition at line 844 of file raw-machine-assembler.h.
                                                           {
    return AddNode(machine()->TruncateFloat64ToInt64(kind), a);
  }
TruncateFloat64ToUint32()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat64ToUint32 (Node * a) [inline]
Definition at line 835 of file raw-machine-assembler.h.
                                         {
    return AddNode(machine()->TruncateFloat64ToUint32(), a);
  }
TruncateFloat64ToWord32()
Node* v8::internal::compiler::RawMachineAssembler::TruncateFloat64ToWord32 (Node * a) [inline]
Definition at line 808 of file raw-machine-assembler.h.
                                         {
    return AddNode(machine()->TruncateFloat64ToWord32(), a);
  }
TruncateInt64ToInt32()
Node* v8::internal::compiler::RawMachineAssembler::TruncateInt64ToInt32 (Node * a) [inline]
Definition at line 885 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->TruncateInt64ToInt32(), a);
  }
TryTruncateFloat32ToInt64()
Node* v8::internal::compiler::RawMachineAssembler::TryTruncateFloat32ToInt64 (Node * a) [inline]
Definition at line 847 of file raw-machine-assembler.h.
                                           {
    return AddNode(machine()->TryTruncateFloat32ToInt64(), a);
  }
TryTruncateFloat32ToUint64()
Node* v8::internal::compiler::RawMachineAssembler::TryTruncateFloat32ToUint64 (Node * a) [inline]
Definition at line 853 of file raw-machine-assembler.h.
                                            {
    return AddNode(machine()->TryTruncateFloat32ToUint64(), a);
  }
TryTruncateFloat64ToInt32()
Node* v8::internal::compiler::RawMachineAssembler::TryTruncateFloat64ToInt32 (Node * a) [inline]
Definition at line 859 of file raw-machine-assembler.h.
                                           {
    return AddNode(machine()->TryTruncateFloat64ToInt32(), a);
  }
TryTruncateFloat64ToInt64()
Node* v8::internal::compiler::RawMachineAssembler::TryTruncateFloat64ToInt64 (Node * a) [inline]
Definition at line 850 of file raw-machine-assembler.h.
                                           {
    return AddNode(machine()->TryTruncateFloat64ToInt64(), a);
  }
TryTruncateFloat64ToUint32()
Node* v8::internal::compiler::RawMachineAssembler::TryTruncateFloat64ToUint32 (Node * a) [inline]
Definition at line 862 of file raw-machine-assembler.h.
                                            {
    return AddNode(machine()->TryTruncateFloat64ToUint32(), a);
  }
TryTruncateFloat64ToUint64()
Node* v8::internal::compiler::RawMachineAssembler::TryTruncateFloat64ToUint64 (Node * a) [inline]
Definition at line 856 of file raw-machine-assembler.h.
                                            {
    return AddNode(machine()->TryTruncateFloat64ToUint64(), a);
  }
Uint32Div()
Node* v8::internal::compiler::RawMachineAssembler::Uint32Div (Node * a, Node * b) [inline]
Definition at line 509 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Uint32Div(), a, b);
  }
Uint32GreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::Uint32GreaterThan (Node * a, Node * b) [inline]
Definition at line 528 of file raw-machine-assembler.h.
{ return Uint32LessThan(b, a); }
Uint32GreaterThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Uint32GreaterThanOrEqual (Node * a, Node * b) [inline]
Definition at line 529 of file raw-machine-assembler.h.
                                                   {
    return Uint32LessThanOrEqual(b, a);
  }
Uint32LessThan()
Node* v8::internal::compiler::RawMachineAssembler::Uint32LessThan (Node * a, Node * b) [inline]
Definition at line 512 of file raw-machine-assembler.h.
                                         {
    return AddNode(machine()->Uint32LessThan(), a, b);
  }
Uint32LessThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Uint32LessThanOrEqual (Node * a, Node * b) [inline]
Definition at line 515 of file raw-machine-assembler.h.
                                                {
    return AddNode(machine()->Uint32LessThanOrEqual(), a, b);
  }
Uint32Mod()
Node* v8::internal::compiler::RawMachineAssembler::Uint32Mod (Node * a, Node * b) [inline]
Definition at line 518 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Uint32Mod(), a, b);
  }
References v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod().
Uint32MulHigh()
Node* v8::internal::compiler::RawMachineAssembler::Uint32MulHigh (Node * a, Node * b) [inline]
Definition at line 521 of file raw-machine-assembler.h.
                                        {
    return AddNode(machine()->Uint32MulHigh(), a, b);
  }
Uint64Div()
Node* v8::internal::compiler::RawMachineAssembler::Uint64Div (Node * a, Node * b) [inline]
Definition at line 585 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Uint64Div(), a, b);
  }
Uint64GreaterThan()
Node* v8::internal::compiler::RawMachineAssembler::Uint64GreaterThan (Node * a, Node * b) [inline]
Definition at line 581 of file raw-machine-assembler.h.
{ return Uint64LessThan(b, a); }
Uint64GreaterThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Uint64GreaterThanOrEqual (Node * a, Node * b) [inline]
Definition at line 582 of file raw-machine-assembler.h.
                                                   {
    return Uint64LessThanOrEqual(b, a);
  }
Uint64LessThan()
Node* v8::internal::compiler::RawMachineAssembler::Uint64LessThan (Node * a, Node * b) [inline]
Definition at line 571 of file raw-machine-assembler.h.
                                         {
    return AddNode(machine()->Uint64LessThan(), a, b);
  }
Uint64LessThanOrEqual()
Node* v8::internal::compiler::RawMachineAssembler::Uint64LessThanOrEqual (Node * a, Node * b) [inline]
Definition at line 574 of file raw-machine-assembler.h.
                                                {
    return AddNode(machine()->Uint64LessThanOrEqual(), a, b);
  }
Uint64Mod()
Node* v8::internal::compiler::RawMachineAssembler::Uint64Mod (Node * a, Node * b) [inline]
Definition at line 588 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Uint64Mod(), a, b);
  }
Uint64MulHigh()
Node* v8::internal::compiler::RawMachineAssembler::Uint64MulHigh (Node * a, Node * b) [inline]
Definition at line 552 of file raw-machine-assembler.h.
                                        {
    return AddNode(machine()->Uint64MulHigh(), a, b);
  }
UnalignedLoad() [1/2]
Node* v8::internal::compiler::RawMachineAssembler::UnalignedLoad (MachineType type, Node * base) [inline]
Definition at line 242 of file raw-machine-assembler.h.
                                                    {
    return UnalignedLoad(type, base, IntPtrConstant(0));
  }
References v8::internal::compiler::IntPtrConstant(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::CodeAssembler::UnalignedLoad().
UnalignedLoad() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::UnalignedLoad (MachineType type, Node * base, Node * index) [inline]
Definition at line 245 of file raw-machine-assembler.h.
                                                                 {
    MachineRepresentation rep = type.representation();
    // Tagged or compressed should never be unaligned
    DCHECK(!(IsAnyTagged(rep) || IsAnyCompressed(rep)));
    if (machine()->UnalignedLoadSupported(rep)) {
      return AddNode(machine()->Load(type), base, index);
    } else {
      return AddNode(machine()->UnalignedLoad(type), base, index);
    }
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::IsAnyCompressed(), v8::internal::IsAnyTagged(), v8::Load(), and v8::internal::tracing::type.
UnalignedLoadFromPointer()
Node* v8::internal::compiler::RawMachineAssembler::UnalignedLoadFromPointer (void * address, MachineType type, int32_t offset = 0) [inline]
Definition at line 1015 of file raw-machine-assembler.h.
                                                     {
    return UnalignedLoad(type, PointerConstant(address), Int32Constant(offset));
  }
References v8::internal::compiler::PointerConstant(), and v8::internal::tracing::type.
UnalignedStore() [1/2]
Node* v8::internal::compiler::RawMachineAssembler::UnalignedStore (MachineRepresentation rep, Node * base, Node * index, Node * value) [inline]
Definition at line 258 of file raw-machine-assembler.h.
                                    {
    // Tagged or compressed should never be unaligned
    DCHECK(!(IsAnyTagged(rep) || IsAnyCompressed(rep)));
    if (machine()->UnalignedStoreSupported(rep)) {
      return AddNode(machine()->Store(StoreRepresentation(
                         rep, WriteBarrierKind::kNoWriteBarrier)),
                     base, index, value);
    } else {
      return AddNode(
          machine()->UnalignedStore(UnalignedStoreRepresentation(rep)), base,
          index, value);
    }
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::IsAnyCompressed(), v8::internal::IsAnyTagged(), v8::internal::compiler::kNoWriteBarrier, v8::internal::wasm::liftoff::Store(), and v8::internal::value.
UnalignedStore() [2/2]
Node* v8::internal::compiler::RawMachineAssembler::UnalignedStore (MachineRepresentation rep, Node * base, Node * value) [inline]
Definition at line 255 of file raw-machine-assembler.h.
                                                                           {
    return UnalignedStore(rep, base, IntPtrConstant(0), value);
  }
References v8::internal::compiler::IntPtrConstant(), and v8::internal::value.
UnalignedStoreToPointer()
Node* v8::internal::compiler::RawMachineAssembler::UnalignedStoreToPointer (void * address, MachineRepresentation rep, Node * node) [inline]
Definition at line 1019 of file raw-machine-assembler.h.
                                            {
    return UnalignedStore(rep, PointerConstant(address), node);
  }
References v8::internal::compiler::PointerConstant().
UndefinedConstant()
Node * v8::internal::compiler::RawMachineAssembler::UndefinedConstant ()
Definition at line 72 of file raw-machine-assembler.cc.
                                             {
  return HeapConstant(isolate()->factory()->undefined_value());
}
References HeapConstant(), and isolate().
Unreachable()
void v8::internal::compiler::RawMachineAssembler::Unreachable ()
Definition at line 683 of file raw-machine-assembler.cc.
                                      {
  Node* ret = MakeNode(common()->Throw(), 0, nullptr);
  schedule()->AddThrow(CurrentBlock(), ret);
  current_block_ = nullptr;
}
References v8::internal::compiler::Schedule::AddThrow(), common(), current_block_, CurrentBlock(), MakeNode(), and schedule().
Referenced by v8::internal::compiler::CodeAssembler::Unreachable().
Use()
BasicBlock * v8::internal::compiler::RawMachineAssembler::Use (RawMachineLabel * label) [private]
Definition at line 789 of file raw-machine-assembler.cc.
                                                           {
  label->used_ = true;
  return EnsureBlock(label);
}
References EnsureBlock(), and v8::internal::compiler::RawMachineLabel::used_.
Referenced by Branch(), Continuations(), Goto(), and Switch().
Word32And()
Node* v8::internal::compiler::RawMachineAssembler::Word32And (Node * a, Node * b) [inline]
Definition at line 412 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32And(), a, b);
  }
Word32BinaryNot()
Node* v8::internal::compiler::RawMachineAssembler::Word32BinaryNot (Node * a) [inline]
Definition at line 444 of file raw-machine-assembler.h.
{ return Word32Equal(a, Int32Constant(0)); }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Word32BitwiseNot()
Node* v8::internal::compiler::RawMachineAssembler::Word32BitwiseNot (Node * a) [inline]
Definition at line 443 of file raw-machine-assembler.h.
{ return Word32Xor(a, Int32Constant(-1)); }
Word32Clz()
Node* v8::internal::compiler::RawMachineAssembler::Word32Clz (Node * a) [inline]
Definition at line 436 of file raw-machine-assembler.h.
{ return AddNode(machine()->Word32Clz(), a); }
References Word32Clz().
Referenced by Word32Clz().
Word32Ctz()
Node* v8::internal::compiler::RawMachineAssembler::Word32Ctz (Node * a) [inline]
Definition at line 615 of file raw-machine-assembler.h.
{ return AddNode(machine()->Word32Ctz().op(), a); }
References Word32Ctz().
Referenced by Word32Ctz().
Word32Equal()
Node* v8::internal::compiler::RawMachineAssembler::Word32Equal (Node * a, Node * b) [inline]
Definition at line 437 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Word32Equal(), a, b);
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Word32NotEqual()
Node* v8::internal::compiler::RawMachineAssembler::Word32NotEqual (Node * a, Node * b) [inline]
Definition at line 440 of file raw-machine-assembler.h.
                                         {
    return Word32BinaryNot(Word32Equal(a, b));
  }
References v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Word32Or()
Node* v8::internal::compiler::RawMachineAssembler::Word32Or (Node * a, Node * b) [inline]
Definition at line 415 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Word32Or(), a, b);
  }
Word32PairSar()
Node* v8::internal::compiler::RawMachineAssembler::Word32PairSar (Node * low_word, Node * high_word, Node * shift) [inline]
Definition at line 606 of file raw-machine-assembler.h.
                                                                    {
    return AddNode(machine()->Word32PairSar(), low_word, high_word, shift);
  }
Word32PairShl()
Node* v8::internal::compiler::RawMachineAssembler::Word32PairShl (Node * low_word, Node * high_word, Node * shift) [inline]
Definition at line 600 of file raw-machine-assembler.h.
                                                                    {
    return AddNode(machine()->Word32PairShl(), low_word, high_word, shift);
  }
Word32PairShr()
Node* v8::internal::compiler::RawMachineAssembler::Word32PairShr (Node * low_word, Node * high_word, Node * shift) [inline]
Definition at line 603 of file raw-machine-assembler.h.
                                                                    {
    return AddNode(machine()->Word32PairShr(), low_word, high_word, shift);
  }
Word32Popcnt()
Node* v8::internal::compiler::RawMachineAssembler::Word32Popcnt (Node * a) [inline]
Definition at line 609 of file raw-machine-assembler.h.
                              {
    return AddNode(machine()->Word32Popcnt().op(), a);
  }
Word32ReverseBytes()
Node* v8::internal::compiler::RawMachineAssembler::Word32ReverseBytes (Node * a) [inline]
Definition at line 948 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32ReverseBytes(), a);
  }
Word32Ror()
Node* v8::internal::compiler::RawMachineAssembler::Word32Ror (Node * a, Node * b) [inline]
Definition at line 433 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32Ror(), a, b);
  }
Word32Sar()
Node* v8::internal::compiler::RawMachineAssembler::Word32Sar (Node * a, Node * b) [inline]
Definition at line 427 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32Sar(), a, b);
  }
Word32SarShiftOutZeros()
Node* v8::internal::compiler::RawMachineAssembler::Word32SarShiftOutZeros (Node * a, Node * b) [inline]
Definition at line 430 of file raw-machine-assembler.h.
                                                 {
    return AddNode(machine()->Word32SarShiftOutZeros(), a, b);
  }
Word32Select()
Node* v8::internal::compiler::RawMachineAssembler::Word32Select (Node * condition, Node * b, Node * c) [inline]
Definition at line 618 of file raw-machine-assembler.h.
                                                        {
    return AddNode(machine()->Word32Select().op(), condition, b, c);
  }
Word32Shl()
Node* v8::internal::compiler::RawMachineAssembler::Word32Shl (Node * a, Node * b) [inline]
Definition at line 421 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32Shl(), a, b);
  }
Word32Shr()
Node* v8::internal::compiler::RawMachineAssembler::Word32Shr (Node * a, Node * b) [inline]
Definition at line 424 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32Shr(), a, b);
  }
Word32Xor()
Node* v8::internal::compiler::RawMachineAssembler::Word32Xor (Node * a, Node * b) [inline]
Definition at line 418 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word32Xor(), a, b);
  }
Word64And()
Node* v8::internal::compiler::RawMachineAssembler::Word64And (Node * a, Node * b) [inline]
Definition at line 446 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64And(), a, b);
  }
Word64Clz()
Node* v8::internal::compiler::RawMachineAssembler::Word64Clz (Node * a) [inline]
Definition at line 467 of file raw-machine-assembler.h.
{ return AddNode(machine()->Word64Clz(), a); }
References Word64Clz().
Referenced by Word64Clz().
Word64Ctz()
Node* v8::internal::compiler::RawMachineAssembler::Word64Ctz (Node * a) [inline]
Definition at line 616 of file raw-machine-assembler.h.
{ return AddNode(machine()->Word64Ctz().op(), a); }
References Word64Ctz().
Referenced by Word64Ctz().
Word64Equal()
Node* v8::internal::compiler::RawMachineAssembler::Word64Equal (Node * a, Node * b) [inline]
Definition at line 468 of file raw-machine-assembler.h.
                                      {
    return AddNode(machine()->Word64Equal(), a, b);
  }
Word64Not()
Node* v8::internal::compiler::RawMachineAssembler::Word64Not (Node * a) [inline]
Definition at line 474 of file raw-machine-assembler.h.
{ return Word64Xor(a, Int64Constant(-1)); }
Word64NotEqual()
Node* v8::internal::compiler::RawMachineAssembler::Word64NotEqual (Node * a, Node * b) [inline]
Definition at line 471 of file raw-machine-assembler.h.
                                         {
    return Word32BinaryNot(Word64Equal(a, b));
  }
Word64Or()
Node* v8::internal::compiler::RawMachineAssembler::Word64Or (Node * a, Node * b) [inline]
Definition at line 449 of file raw-machine-assembler.h.
                                   {
    return AddNode(machine()->Word64Or(), a, b);
  }
Word64Popcnt()
Node* v8::internal::compiler::RawMachineAssembler::Word64Popcnt (Node * a) [inline]
Definition at line 612 of file raw-machine-assembler.h.
                              {
    return AddNode(machine()->Word64Popcnt().op(), a);
  }
Word64ReverseBytes()
Node* v8::internal::compiler::RawMachineAssembler::Word64ReverseBytes (Node * a) [inline]
Definition at line 951 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64ReverseBytes(), a);
  }
Word64Ror()
Node* v8::internal::compiler::RawMachineAssembler::Word64Ror (Node * a, Node * b) [inline]
Definition at line 464 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64Ror(), a, b);
  }
Word64Sar()
Node* v8::internal::compiler::RawMachineAssembler::Word64Sar (Node * a, Node * b) [inline]
Definition at line 461 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64Sar(), a, b);
  }
Word64Select()
Node* v8::internal::compiler::RawMachineAssembler::Word64Select (Node * condition, Node * b, Node * c) [inline]
Definition at line 622 of file raw-machine-assembler.h.
                                                        {
    return AddNode(machine()->Word64Select().op(), condition, b, c);
  }
Word64Shl()
Node* v8::internal::compiler::RawMachineAssembler::Word64Shl (Node * a, Node * b) [inline]
Definition at line 455 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64Shl(), a, b);
  }
Word64Shr()
Node* v8::internal::compiler::RawMachineAssembler::Word64Shr (Node * a, Node * b) [inline]
Definition at line 458 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64Shr(), a, b);
  }
Word64Xor()
Node* v8::internal::compiler::RawMachineAssembler::Word64Xor (Node * a, Node * b) [inline]
Definition at line 452 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->Word64Xor(), a, b);
  }
WordAnd()
Node* v8::internal::compiler::RawMachineAssembler::WordAnd (Node * a, Node * b) [inline]
Definition at line 376 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->WordAnd(), a, b);
  }
WordEqual()
Node* v8::internal::compiler::RawMachineAssembler::WordEqual (Node * a, Node * b) [inline]
Definition at line 398 of file raw-machine-assembler.h.
                                    {
    return AddNode(machine()->WordEqual(), a, b);
  }
WordNot()
Node* v8::internal::compiler::RawMachineAssembler::WordNot (Node * a) [inline]
Definition at line 404 of file raw-machine-assembler.h.
                         {
    if (machine()->Is32()) {
      return Word32BitwiseNot(a);
    } else {
      return Word64Not(a);
    }
  }
WordNotEqual()
Node* v8::internal::compiler::RawMachineAssembler::WordNotEqual (Node * a, Node * b) [inline]
Definition at line 401 of file raw-machine-assembler.h.
                                       {
    return Word32BinaryNot(WordEqual(a, b));
  }
WordOr()
Node* v8::internal::compiler::RawMachineAssembler::WordOr (Node * a, Node * b) [inline]
Definition at line 379 of file raw-machine-assembler.h.
{ return AddNode(machine()->WordOr(), a, b); }
References WordOr().
Referenced by WordOr().
WordRor()
Node* v8::internal::compiler::RawMachineAssembler::WordRor (Node * a, Node * b) [inline]
Definition at line 395 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->WordRor(), a, b);
  }
WordSar()
Node* v8::internal::compiler::RawMachineAssembler::WordSar (Node * a, Node * b) [inline]
Definition at line 389 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->WordSar(), a, b);
  }
WordSarShiftOutZeros()
Node* v8::internal::compiler::RawMachineAssembler::WordSarShiftOutZeros (Node * a, Node * b) [inline]
Definition at line 392 of file raw-machine-assembler.h.
                                               {
    return AddNode(machine()->WordSarShiftOutZeros(), a, b);
  }
WordShl()
Node* v8::internal::compiler::RawMachineAssembler::WordShl (Node * a, Node * b) [inline]
Definition at line 383 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->WordShl(), a, b);
  }
WordShr()
Node* v8::internal::compiler::RawMachineAssembler::WordShr (Node * a, Node * b) [inline]
Definition at line 386 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->WordShr(), a, b);
  }
WordXor()
Node* v8::internal::compiler::RawMachineAssembler::WordXor (Node * a, Node * b) [inline]
Definition at line 380 of file raw-machine-assembler.h.
                                  {
    return AddNode(machine()->WordXor(), a, b);
  }
zone()
Zone* v8::internal::compiler::RawMachineAssembler::zone () const [inline]
Definition at line 64 of file raw-machine-assembler.h.
{ return graph()->zone(); }
References graph().
Referenced by AppendPhiInput(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), Comment(), ExportForOptimization(), ExportForTest(), MakeReschedulable(), Phi(), Switch(), and v8::internal::compiler::CodeAssembler::zone().
Member Data Documentation
call_descriptor_
CallDescriptor* v8::internal::compiler::RawMachineAssembler::call_descriptor_ [private]
Definition at line 1224 of file raw-machine-assembler.h.
common_
CommonOperatorBuilder v8::internal::compiler::RawMachineAssembler::common_ [private]
Definition at line 1222 of file raw-machine-assembler.h.
Referenced by RawMachineAssembler().
current_block_
BasicBlock* v8::internal::compiler::RawMachineAssembler::current_block_ [private]
Definition at line 1232 of file raw-machine-assembler.h.
Referenced by AddNode(), Bind(), Branch(), Continuations(), CurrentBlock(), Goto(), InsideBlock(), PopAndReturn(), Return(), Switch(), TailCallN(), and Unreachable().
dynamic_js_parameter_count_
Node* v8::internal::compiler::RawMachineAssembler::dynamic_js_parameter_count_ [private]
Definition at line 1229 of file raw-machine-assembler.h.
graph_
TFGraph* v8::internal::compiler::RawMachineAssembler::graph_ [private]
Definition at line 1218 of file raw-machine-assembler.h.
isolate_
Isolate* v8::internal::compiler::RawMachineAssembler::isolate_ [private]
Definition at line 1216 of file raw-machine-assembler.h.
machine_
MachineOperatorBuilder v8::internal::compiler::RawMachineAssembler::machine_ [private]
Definition at line 1221 of file raw-machine-assembler.h.
parameters_
NodeVector v8::internal::compiler::RawMachineAssembler::parameters_ [private]
Definition at line 1231 of file raw-machine-assembler.h.
Referenced by Parameter(), and RawMachineAssembler().
schedule_
Schedule* v8::internal::compiler::RawMachineAssembler::schedule_ [private]
Definition at line 1219 of file raw-machine-assembler.h.
Referenced by AddNode(), Continuations(), ExportForOptimization(), ExportForTest(), and MakeReschedulable().
simplified_
SimplifiedOperatorBuilder v8::internal::compiler::RawMachineAssembler::simplified_ [private]
Definition at line 1223 of file raw-machine-assembler.h.
source_positions_
SourcePositionTable* v8::internal::compiler::RawMachineAssembler::source_positions_ [private]
Definition at line 1220 of file raw-machine-assembler.h.
Referenced by ExportForTest(), GetCurrentExternalSourcePosition(), and RawMachineAssembler().
target_parameter_
Node* v8::internal::compiler::RawMachineAssembler::target_parameter_ [private]
Definition at line 1230 of file raw-machine-assembler.h.
Referenced by RawMachineAssembler(), and TargetParameter().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/raw-machine-assembler.h
/mnt/V8SourceCode/src/compiler/raw-machine-assembler.cc