v8::debug::ScopeIterator Class Reference
#include <debug-interface.h>
Public Types
enum ScopeType {
ScopeTypeGlobal = 0
, ScopeTypeLocal
, ScopeTypeWith
, ScopeTypeClosure
,
ScopeTypeCatch
, ScopeTypeBlock
, ScopeTypeScript
, ScopeTypeEval
,
ScopeTypeModule
, ScopeTypeWasmExpressionStack
 }
Public Member Functions
ScopeIterator ()=default
virtual ~ScopeIterator ()=default
ScopeIterator (const ScopeIterator &)=delete
ScopeIterator & operator= (const ScopeIterator &)=delete
virtual bool Done ()=0
virtual void Advance ()=0
virtual ScopeType GetType ()=0
virtual v8::Local< v8::Object > GetObject ()=0
virtual v8::Local< v8::Value > GetFunctionDebugName ()=0
virtual int GetScriptId ()=0
virtual bool HasLocationInfo ()=0
virtual debug::Location GetStartLocation ()=0
virtual debug::Location GetEndLocation ()=0
virtual bool SetVariableValue (v8::Local< v8::String > name, v8::Local< v8::Value > value)=0
Static Public Member Functions
static std::unique_ptr< ScopeIterator > CreateForFunction (v8::Isolate *isolate, v8::Local< v8::Function > func)
static std::unique_ptr< ScopeIterator > CreateForGeneratorObject (v8::Isolate *isolate, v8::Local< v8::Object > generator)
Detailed Description
Definition at line 479 of file debug-interface.h.
Member Enumeration Documentation
ScopeType
enum v8::debug::ScopeIterator::ScopeType
Enumerator
ScopeTypeGlobal
ScopeTypeLocal
ScopeTypeWith
ScopeTypeClosure
ScopeTypeCatch
ScopeTypeBlock
ScopeTypeScript
ScopeTypeEval
ScopeTypeModule
ScopeTypeWasmExpressionStack
Definition at line 491 of file debug-interface.h.
                 {
    ScopeTypeGlobal = 0,
    ScopeTypeLocal,
    ScopeTypeWith,
    ScopeTypeClosure,
    ScopeTypeCatch,
    ScopeTypeBlock,
    ScopeTypeScript,
    ScopeTypeEval,
    ScopeTypeModule,
    ScopeTypeWasmExpressionStack
  };
Constructor & Destructor Documentation
ScopeIterator() [1/2]
v8::debug::ScopeIterator::ScopeIterator () [default]
 ScopeIterator()
virtual v8::debug::ScopeIterator::~ScopeIterator () [virtual], [default]
ScopeIterator() [2/2]
v8::debug::ScopeIterator::ScopeIterator (const ScopeIterator &) [delete]
Member Function Documentation
Advance()
virtual void v8::debug::ScopeIterator::Advance () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
CreateForFunction()
std::unique_ptr< debug::ScopeIterator > v8::debug::ScopeIterator::CreateForFunction (v8::Isolate * isolate, v8::Local< v8::Function > func) [static]
Definition at line 13 of file debug-scope-iterator.cc.
                                                        {
  internal::DirectHandle<internal::JSReceiver> receiver =
      Utils::OpenDirectHandle(*v8_func);
  // Besides JSFunction and JSBoundFunction, {v8_func} could be an
  // ObjectTemplate with a CallAsFunctionHandler. We only handle plain
  // JSFunctions.
  if (!IsJSFunction(*receiver)) return nullptr;
  auto function = internal::Cast<internal::JSFunction>(receiver);
  CHECK(function->has_context());
  return std::unique_ptr<debug::ScopeIterator>(new internal::DebugScopeIterator(
      reinterpret_cast<internal::Isolate*>(v8_isolate), function));
}
References CHECK, and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Debugger::getTargetScopes().
CreateForGeneratorObject()
std::unique_ptr< debug::ScopeIterator > v8::debug::ScopeIterator::CreateForGeneratorObject (v8::Isolate * isolate, v8::Local< v8::Object > generator) [static]
Definition at line 31 of file debug-scope-iterator.cc.
                                                           {
  internal::Handle<internal::Object> generator =
      Utils::OpenHandle(*v8_generator);
  DCHECK(IsJSGeneratorObject(*generator));
  return std::unique_ptr<debug::ScopeIterator>(new internal::DebugScopeIterator(
      reinterpret_cast<internal::Isolate*>(v8_isolate),
      internal::Cast<internal::JSGeneratorObject>(generator)));
}
References DCHECK, and v8::Utils::OpenHandle().
Referenced by v8_inspector::V8Debugger::getTargetScopes().
Done()
virtual bool v8::debug::ScopeIterator::Done () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
GetEndLocation()
virtual debug::Location v8::debug::ScopeIterator::GetEndLocation () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
GetFunctionDebugName()
virtual v8::Local<v8::Value> v8::debug::ScopeIterator::GetFunctionDebugName () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
GetObject()
virtual v8::Local<v8::Object> v8::debug::ScopeIterator::GetObject () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
GetScriptId()
virtual int v8::debug::ScopeIterator::GetScriptId () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
GetStartLocation()
virtual debug::Location v8::debug::ScopeIterator::GetStartLocation () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
GetType()
virtual ScopeType v8::debug::ScopeIterator::GetType () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
HasLocationInfo()
virtual bool v8::debug::ScopeIterator::HasLocationInfo () [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes().
operator=()
ScopeIterator& v8::debug::ScopeIterator::operator= (const ScopeIterator &) [delete]
SetVariableValue()
virtual bool v8::debug::ScopeIterator::SetVariableValue (v8::Local< v8::String > name, v8::Local< v8::Value > value) [pure virtual]
Implemented in v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator, and v8::internal::DebugScopeIterator.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-scope-iterator.cc