v8::internal::PlatformEmbeddedFileWriterGeneric Class Reference
#include <platform-embedded-file-writer-generic.h>
Public Member Functions
PlatformEmbeddedFileWriterGeneric (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os)
void SectionText () override
void SectionRoData () override
void AlignToCodeAlignment () override
void AlignToPageSizeIfNeeded () override
void AlignToDataAlignment () override
void DeclareUint32 (const char *name, uint32_t value) override
void DeclareSymbolGlobal (const char *name) override
void DeclareLabel (const char *name) override
void SourceInfo (int fileid, const char *filename, int line) override
void DeclareFunctionBegin (const char *name, uint32_t size) override
void DeclareFunctionEnd (const char *name) override
void Comment (const char *string) override
void FilePrologue () override
void DeclareExternalFilename (int fileid, const char *filename) override
void FileEpilogue () override
int IndentedDataDirective (DataDirective directive) override
DataDirective ByteChunkDataDirective () const override
Private Attributes
const EmbeddedTargetArch target_arch_
const EmbeddedTargetOs target_os_
Additional Inherited Members
Detailed Description
Definition at line 14 of file platform-embedded-file-writer-generic.h.
Constructor & Destructor Documentation
PlatformEmbeddedFileWriterGeneric()
v8::internal::PlatformEmbeddedFileWriterGeneric::PlatformEmbeddedFileWriterGeneric (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os) [inline]
Definition at line 17 of file platform-embedded-file-writer-generic.h.
      : target_arch_(target_arch), target_os_(target_os) {
    DCHECK(target_os_ == EmbeddedTargetOs::kChromeOS ||
           target_os_ == EmbeddedTargetOs::kFuchsia ||
           target_os_ == EmbeddedTargetOs::kGeneric);
  }
References v8::internal::DCHECK(), v8::internal::kChromeOS, v8::internal::kFuchsia, v8::internal::kGeneric, and target_os_.
Member Function Documentation
AlignToCodeAlignment()
void v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToCodeAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 63 of file platform-embedded-file-writer-generic.cc.
                                                             {
#if (V8_OS_ANDROID || V8_OS_LINUX) && \
    (V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_ARM64)
  // On these architectures and platforms, we remap the builtins, so need these
  // to be aligned on a page boundary.
  fprintf(fp_, ".balign 4096\n");
#elif V8_TARGET_ARCH_X64
  // On x64 use 64-bytes code alignment to allow 64-bytes loop header alignment.
  static_assert(64 >= kCodeAlignment);
  fprintf(fp_, ".balign 64\n");
#elif V8_TARGET_ARCH_PPC64
  // 64 byte alignment is needed on ppc64 to make sure p10 prefixed instructions
  // don't cross 64-byte boundaries.
  static_assert(64 >= kCodeAlignment);
  fprintf(fp_, ".balign 64\n");
#else
  static_assert(32 >= kCodeAlignment);
  fprintf(fp_, ".balign 32\n");
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::kCodeAlignment.
AlignToDataAlignment()
void v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToDataAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 92 of file platform-embedded-file-writer-generic.cc.
                                                             {
  // On Windows ARM64, s390, PPC and possibly more platforms, aligned load
  // instructions are used to retrieve v8_Default_embedded_blob_ and/or
  // v8_Default_embedded_blob_size_. The generated instructions require the
  // load target to be aligned at 8 bytes (2^3).
  static_assert(8 >= InstructionStream::kMetadataAlignment);
  fprintf(fp_, ".balign 8\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::InstructionStream::kMetadataAlignment.
AlignToPageSizeIfNeeded()
void v8::internal::PlatformEmbeddedFileWriterGeneric::AlignToPageSizeIfNeeded () [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 84 of file platform-embedded-file-writer-generic.cc.
                                                                {
#if (V8_OS_ANDROID || V8_OS_LINUX) && \
    (V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_ARM64)
  // Since the builtins are remapped, need to pad until the next page boundary.
  fprintf(fp_, ".balign 4096\n");
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
ByteChunkDataDirective()
DataDirective v8::internal::PlatformEmbeddedFileWriterGeneric::ByteChunkDataDirective () const [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 166 of file platform-embedded-file-writer-generic.cc.
          {
#if defined(V8_TARGET_ARCH_MIPS64) || defined(V8_TARGET_ARCH_LOONG64)
  // MIPS and LOONG64 uses a fixed 4 byte instruction set, using .long
  // to prevent any unnecessary padding.
  return kLong;
#else
  // Other ISAs just listen to the base
  return PlatformEmbeddedFileWriterBase::ByteChunkDataDirective();
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::ByteChunkDataDirective(), and v8::internal::kLong.
Comment()
void v8::internal::PlatformEmbeddedFileWriterGeneric::Comment (const char * string) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 101 of file platform-embedded-file-writer-generic.cc.
                                                                  {
  fprintf(fp_, "// %s\n", string);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
DeclareExternalFilename()
void v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareExternalFilename (int fileid, const char * filename) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 142 of file platform-embedded-file-writer-generic.cc.
                                      {
  // Replace any Windows style paths (backslashes) with forward
  // slashes.
  std::string fixed_filename(filename);
  std::replace(fixed_filename.begin(), fixed_filename.end(), '\\', '/');
  fprintf(fp_, ".file %d \"%s\"\n", fileid, fixed_filename.c_str());
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::string.
DeclareFunctionBegin()
void v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareFunctionBegin (const char * name, uint32_t size) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 115 of file platform-embedded-file-writer-generic.cc.
                                                                            {
#if V8_ENABLE_DRUMBRAKE
  if (IsDrumBrakeInstructionHandler(name)) {
    DeclareSymbolGlobal(name);
  }
#endif // V8_ENABLE_DRUMBRAKE
  DeclareLabel(name);
  if (target_arch_ == EmbeddedTargetArch::kArm ||
      target_arch_ == EmbeddedTargetArch::kArm64) {
    // ELF format binaries on ARM use ".type <function name>, %function"
    // to create a DWARF subprogram entry.
    fprintf(fp_, ".type %s, %%function\n", name);
  } else {
    // Other ELF Format binaries use ".type <function name>, @function"
    // to create a DWARF subprogram entry.
    fprintf(fp_, ".type %s, @function\n", name);
  }
  fprintf(fp_, ".size %s, %u\n", name, size);
}
References DeclareLabel(), DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::kArm, v8::internal::kArm64, v8::internal::name, size(), and target_arch_.
DeclareFunctionEnd()
void v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareFunctionEnd (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 138 of file platform-embedded-file-writer-generic.cc.
{}
DeclareLabel()
void v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareLabel (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 105 of file platform-embedded-file-writer-generic.cc.
                                                                     {
  fprintf(fp_, "%s%s:\n", SYMBOL_PREFIX, name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::name, and SYMBOL_PREFIX.
Referenced by DeclareFunctionBegin(), and DeclareUint32().
DeclareSymbolGlobal()
void v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareSymbolGlobal (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 56 of file platform-embedded-file-writer-generic.cc.
                                                                            {
  fprintf(fp_, ".global %s%s\n", SYMBOL_PREFIX, name);
  // These symbols are not visible outside of the final binary, this allows for
  // reduced binary size, and less work for the dynamic linker.
  fprintf(fp_, ".hidden %s\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::name, and SYMBOL_PREFIX.
Referenced by DeclareFunctionBegin(), and DeclareUint32().
DeclareUint32()
void v8::internal::PlatformEmbeddedFileWriterGeneric::DeclareUint32 (const char * name, uint32_t value) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 47 of file platform-embedded-file-writer-generic.cc.
                                                                      {
  DeclareSymbolGlobal(name);
  DeclareLabel(name);
  IndentedDataDirective(kLong);
  fprintf(fp_, "%d", value);
  Newline();
}
References DeclareLabel(), DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, IndentedDataDirective(), v8::internal::kLong, v8::internal::name, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), and v8::internal::value.
FileEpilogue()
void v8::internal::PlatformEmbeddedFileWriterGeneric::FileEpilogue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 151 of file platform-embedded-file-writer-generic.cc.
                                                     {
  // Omitting this section can imply an executable stack, which is usually
  // a linker warning/error. C++ compilers add these automatically, but
  // compiling assembly requires the .note.GNU-stack section to be inserted
  // manually.
  // Additional documentation:
  // https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart
  fprintf(fp_, ".section .note.GNU-stack,\"\",%%progbits\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
FilePrologue()
void v8::internal::PlatformEmbeddedFileWriterGeneric::FilePrologue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 140 of file platform-embedded-file-writer-generic.cc.
{}
IndentedDataDirective()
int v8::internal::PlatformEmbeddedFileWriterGeneric::IndentedDataDirective (DataDirective directive) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 161 of file platform-embedded-file-writer-generic.cc.
                             {
  return fprintf(fp_, " %s ", DirectiveAsString(directive));
}
References v8::internal::anonymous_namespace{platform-embedded-file-writer-generic.cc}::DirectiveAsString(), and v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Referenced by DeclareUint32().
SectionRoData()
void v8::internal::PlatformEmbeddedFileWriterGeneric::SectionRoData () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 43 of file platform-embedded-file-writer-generic.cc.
                                                      {
  fprintf(fp_, ".section .rodata\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
SectionText()
void v8::internal::PlatformEmbeddedFileWriterGeneric::SectionText () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 35 of file platform-embedded-file-writer-generic.cc.
                                                    {
  if (target_os_ == EmbeddedTargetOs::kChromeOS) {
    fprintf(fp_, ".section .text.hot.embedded\n");
  } else {
    fprintf(fp_, ".section .text\n");
  }
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::kChromeOS, and target_os_.
SourceInfo()
void v8::internal::PlatformEmbeddedFileWriterGeneric::SourceInfo (int fileid, const char * filename, int line) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 109 of file platform-embedded-file-writer-generic.cc.
                                                             {
  fprintf(fp_, ".loc %d %d\n", fileid, line);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Member Data Documentation
target_arch_
const EmbeddedTargetArch v8::internal::PlatformEmbeddedFileWriterGeneric::target_arch_ [private]
Definition at line 52 of file platform-embedded-file-writer-generic.h.
Referenced by DeclareFunctionBegin().
target_os_
const EmbeddedTargetOs v8::internal::PlatformEmbeddedFileWriterGeneric::target_os_ [private]
Definition at line 53 of file platform-embedded-file-writer-generic.h.
Referenced by PlatformEmbeddedFileWriterGeneric(), and SectionText().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-generic.h
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-generic.cc