v8::internal::FeedbackCell Class Reference
#include <feedback-cell.h>
Classes
class BodyDescriptor
Public Types
enum ClosureCountTransition { kNoneToOne
, kOneToMany
, kMany
 }
Public Member Functions
void clear_interrupt_budget ()
void clear_dispatch_handle ()
void clear_padding ()
void reset_feedback_vector (std::optional< std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target)>> gc_notify_updated_slot=std::nullopt)
ClosureCountTransition IncrementClosureCount (Isolate *isolate)
Static Public Attributes
static const int kUnalignedSize = kSize
static const int kAlignedSize = RoundUp<kObjectAlignment>(int{kSize})
Detailed Description
Definition at line 26 of file feedback-cell.h.
Member Enumeration Documentation
ClosureCountTransition
enum v8::internal::FeedbackCell::ClosureCountTransition
Enumerator
kNoneToOne
kOneToMany
kMany
Definition at line 54 of file feedback-cell.h.
{ kNoneToOne, kOneToMany, kMany };
Member Function Documentation
clear_dispatch_handle()
void v8::internal::FeedbackCell::clear_dispatch_handle () [inline]
Definition at line 59 of file feedback-cell-inl.h.
                                         {
  WriteField<JSDispatchHandle::underlying_type>(kDispatchHandleOffset,
                                                kNullJSDispatchHandle.value());
}
References v8::internal::kNullJSDispatchHandle(), and v8::base::StrongAlias< TagType, UnderlyingType >::value().
clear_interrupt_budget()
void v8::internal::FeedbackCell::clear_interrupt_budget () [inline]
Definition at line 54 of file feedback-cell-inl.h.
                                          {
  // This value is always reset to a proper budget before it's used.
  set_interrupt_budget(0);
}
Referenced by reset_feedback_vector().
clear_padding()
void v8::internal::FeedbackCell::clear_padding () [inline]
Definition at line 30 of file feedback-cell-inl.h.
                                 {
  if (FeedbackCell::kAlignedSize == FeedbackCell::kUnalignedSize) return;
  DCHECK_GE(FeedbackCell::kAlignedSize, FeedbackCell::kUnalignedSize);
  memset(reinterpret_cast<uint8_t*>(address() + FeedbackCell::kUnalignedSize),
         0, FeedbackCell::kAlignedSize - FeedbackCell::kUnalignedSize);
}
References DCHECK_GE, kAlignedSize, and kUnalignedSize.
IncrementClosureCount()
FeedbackCell::ClosureCountTransition v8::internal::FeedbackCell::IncrementClosureCount (Isolate * isolate) [inline]
Definition at line 78 of file feedback-cell-inl.h.
                      {
  ReadOnlyRoots r(isolate);
  if (map() == r.no_closures_cell_map()) {
    set_map(isolate, r.one_closure_cell_map());
    return kNoneToOne;
  } else if (map() == r.one_closure_cell_map()) {
    set_map(isolate, r.many_closures_cell_map());
    return kOneToMany;
  } else {
    DCHECK(map() == r.many_closures_cell_map());
    return kMany;
  }
}
References v8::internal::DCHECK(), kMany, kNoneToOne, and kOneToMany.
reset_feedback_vector()
void v8::internal::FeedbackCell::reset_feedback_vector (std::optional< std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target)> , gc_notify_updated_slot = std::nullopt) [inline]
Definition at line 37 of file feedback-cell-inl.h.
                                {
  clear_interrupt_budget();
  if (IsUndefined(value()) || IsClosureFeedbackCellArray(value())) return;
  CHECK(IsFeedbackVector(value()));
  Tagged<ClosureFeedbackCellArray> closure_feedback_cell_array =
      Cast<FeedbackVector>(value())->closure_feedback_cell_array();
  set_value(closure_feedback_cell_array, kReleaseStore);
  if (gc_notify_updated_slot) {
    (*gc_notify_updated_slot)(*this, RawField(FeedbackCell::kValueOffset),
                              closure_feedback_cell_array);
  }
}
References CHECK, clear_interrupt_budget(), v8::kReleaseStore, and v8::internal::value.
Member Data Documentation
kAlignedSize
const int v8::internal::FeedbackCell::kAlignedSize = RoundUp<kObjectAlignment>(int{kSize}) [static]
Definition at line 32 of file feedback-cell.h.
Referenced by clear_padding(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::Factory::NewManyClosuresCell(), v8::internal::Factory::NewNoClosuresCell(), v8::internal::Factory::NewOneClosureCell(), and v8::internal::FeedbackCell::BodyDescriptor::SizeOf().
kUnalignedSize
const int v8::internal::FeedbackCell::kUnalignedSize = kSize [static]
Definition at line 31 of file feedback-cell.h.
Referenced by clear_padding().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-cell.h
/mnt/V8SourceCode/src/objects/feedback-cell-inl.h