v8::internal::compiler::LoopPeeler Class Reference
#include <loop-peeling.h>
Public Member Functions
LoopPeeler (TFGraph *graph, CommonOperatorBuilder *common, LoopTree *loop_tree, Zone *tmp_zone, SourcePositionTable *source_positions, NodeOriginTable *node_origins)
bool CanPeel (LoopTree::Loop *loop)
PeeledIteration * Peel (LoopTree::Loop *loop)
void PeelInnerLoopsOfTree ()
Static Public Member Functions
static void EliminateLoopExits (TFGraph *graph, Zone *tmp_zone)
static void EliminateLoopExit (Node *loop)
Static Public Attributes
static const size_t kMaxPeeledNodes = 1000
Private Member Functions
void PeelInnerLoops (LoopTree::Loop *loop)
Private Attributes
TFGraph *const graph_
CommonOperatorBuilder *const common_
LoopTree *const loop_tree_
Zone *const tmp_zone_
SourcePositionTable *const source_positions_
NodeOriginTable *const node_origins_
Detailed Description
Definition at line 35 of file loop-peeling.h.
Constructor & Destructor Documentation
LoopPeeler()
v8::internal::compiler::LoopPeeler::LoopPeeler (TFGraph * graph, CommonOperatorBuilder * common, LoopTree * loop_tree, Zone * tmp_zone, SourcePositionTable * source_positions, NodeOriginTable * node_origins) [inline]
Definition at line 37 of file loop-peeling.h.
      : graph_(graph),
        common_(common),
        loop_tree_(loop_tree),
        tmp_zone_(tmp_zone),
        source_positions_(source_positions),
        node_origins_(node_origins) {}
Member Function Documentation
CanPeel()
bool v8::internal::compiler::LoopPeeler::CanPeel (LoopTree::Loop * loop) [inline]
Definition at line 46 of file loop-peeling.h.
                                   {
    return LoopFinder::HasMarkedExits(loop_tree_, loop);
  }
References v8::internal::compiler::LoopFinder::HasMarkedExits().
Referenced by Peel().
EliminateLoopExit()
void v8::internal::compiler::LoopPeeler::EliminateLoopExit (Node * loop) [static]
Definition at line 239 of file loop-peeling.cc.
                                             {
  DCHECK_EQ(IrOpcode::kLoopExit, node->opcode());
  // The exit markers take the loop exit as input. We iterate over uses
  // and remove all the markers from the graph.
  for (Edge edge : node->use_edges()) {
    if (NodeProperties::IsControlEdge(edge)) {
      Node* marker = edge.from();
      if (marker->opcode() == IrOpcode::kLoopExitValue) {
        NodeProperties::ReplaceUses(marker, marker->InputAt(0));
        marker->Kill();
      } else if (marker->opcode() == IrOpcode::kLoopExitEffect) {
        NodeProperties::ReplaceUses(marker, nullptr,
                                    NodeProperties::GetEffectInput(marker));
        marker->Kill();
      }
    }
  }
  NodeProperties::ReplaceUses(node, nullptr, nullptr,
                              NodeProperties::GetControlInput(node, 0));
  node->Kill();
}
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceUses(), and v8::internal::compiler::Node::use_edges().
Referenced by EliminateLoopExits().
EliminateLoopExits()
void v8::internal::compiler::LoopPeeler::EliminateLoopExits (TFGraph * graph, Zone * tmp_zone) [static]
Definition at line 270 of file loop-peeling.cc.
                                                                  {
  ZoneQueue<Node*> queue(tmp_zone);
  BitVector visited(static_cast<int>(graph->NodeCount()), tmp_zone);
  queue.push(graph->end());
  while (!queue.empty()) {
    Node* node = queue.front();
    queue.pop();
    if (node->opcode() == IrOpcode::kLoopExit) {
      Node* control = NodeProperties::GetControlInput(node);
      EliminateLoopExit(node);
      if (!visited.Contains(control->id())) {
        visited.Add(control->id());
        queue.push(control);
      }
    } else {
      for (int i = 0; i < node->op()->ControlInputCount(); i++) {
        Node* control = NodeProperties::GetControlInput(node, i);
        if (!visited.Contains(control->id())) {
          visited.Add(control->id());
          queue.push(control);
        }
      }
    }
  }
}
References v8::internal::BitVector::Add(), v8::internal::BitVector::Contains(), EliminateLoopExit(), v8::internal::compiler::NodeProperties::GetControlInput(), graph(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by PeelInnerLoopsOfTree(), and v8::internal::compiler::LoopExitEliminationPhase::Run().
Peel()
PeeledIteration * v8::internal::compiler::LoopPeeler::Peel (LoopTree::Loop * loop)
Definition at line 125 of file loop-peeling.cc.
                                                    {
  if (!CanPeel(loop)) return nullptr;
  //============================================================================
  // Construct the peeled iteration.
  //============================================================================
  PeeledIterationImpl* iter = tmp_zone_->New<PeeledIterationImpl>(tmp_zone_);
  uint32_t estimated_peeled_size = 5 + loop->TotalSize() * 2;
  NodeCopier copier(graph_, estimated_peeled_size, &iter->node_pairs_, 1);
  Node* dead = graph_->NewNode(common_->Dead());
  // Map the loop header nodes to their entry values.
  for (Node* node : loop_tree_->HeaderNodes(loop)) {
    copier.Insert(node, node->InputAt(kAssumedLoopEntryIndex));
  }
  // Copy all the nodes of loop body for the peeled iteration.
  copier.CopyNodes(graph_, tmp_zone_, dead, loop_tree_->BodyNodes(loop),
                   source_positions_, node_origins_);
  //============================================================================
  // Replace the entry to the loop with the output of the peeled iteration.
  //============================================================================
  Node* loop_node = loop_tree_->GetLoopControl(loop);
  Node* new_entry;
  int backedges = loop_node->InputCount() - 1;
  if (backedges > 1) {
    // Multiple backedges from original loop, therefore multiple output edges
    // from the peeled iteration.
    NodeVector inputs(tmp_zone_);
    for (int i = 1; i < loop_node->InputCount(); i++) {
      inputs.push_back(copier.map(loop_node->InputAt(i)));
    }
    Node* merge =
        graph_->NewNode(common_->Merge(backedges), backedges, &inputs[0]);
    // Merge values from the multiple output edges of the peeled iteration.
    for (Node* node : loop_tree_->HeaderNodes(loop)) {
      if (node->opcode() == IrOpcode::kLoop) continue; // already done.
      inputs.clear();
      for (int i = 0; i < backedges; i++) {
        inputs.push_back(copier.map(node->InputAt(1 + i)));
      }
      for (Node* input : inputs) {
        if (input != inputs[0]) { // Non-redundant phi.
          inputs.push_back(merge);
          const Operator* op = common_->ResizeMergeOrPhi(node->op(), backedges);
          Node* phi = graph_->NewNode(op, backedges + 1, &inputs[0]);
          node->ReplaceInput(0, phi);
          break;
        }
      }
    }
    new_entry = merge;
  } else {
    // Only one backedge, simply replace the input to loop with output of
    // peeling.
    for (Node* node : loop_tree_->HeaderNodes(loop)) {
      node->ReplaceInput(0, copier.map(node->InputAt(1)));
    }
    new_entry = copier.map(loop_node->InputAt(1));
  }
  loop_node->ReplaceInput(0, new_entry);
  //============================================================================
  // Change the exit and exit markers to merge/phi/effect-phi.
  //============================================================================
  for (Node* exit : loop_tree_->ExitNodes(loop)) {
    switch (exit->opcode()) {
      case IrOpcode::kLoopExit:
        // Change the loop exit node to a merge node.
        exit->ReplaceInput(1, copier.map(exit->InputAt(0)));
        NodeProperties::ChangeOp(exit, common_->Merge(2));
        break;
      case IrOpcode::kLoopExitValue:
        // Change exit marker to phi.
        exit->InsertInput(graph_->zone(), 1, copier.map(exit->InputAt(0)));
        NodeProperties::ChangeOp(
            exit, common_->Phi(LoopExitValueRepresentationOf(exit->op()), 2));
        break;
      case IrOpcode::kLoopExitEffect:
        // Change effect exit marker to effect phi.
        exit->InsertInput(graph_->zone(), 1, copier.map(exit->InputAt(0)));
        NodeProperties::ChangeOp(exit, common_->EffectPhi(2));
        break;
      default:
        break;
    }
  }
  return iter;
}
References v8::internal::compiler::LoopTree::BodyNodes(), CanPeel(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::ZoneVector< T >::clear(), common_, v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::CommonOperatorBuilder::Dead(), v8::internal::compiler::CommonOperatorBuilder::EffectPhi(), v8::internal::compiler::LoopTree::ExitNodes(), v8::internal::compiler::LoopTree::GetLoopControl(), graph_, v8::internal::compiler::LoopTree::HeaderNodes(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::NodeCopier::Insert(), v8::internal::compiler::kAssumedLoopEntryIndex, loop_tree_, v8::internal::compiler::LoopExitValueRepresentationOf(), v8::internal::compiler::NodeCopier::map(), v8::internal::compiler::CommonOperatorBuilder::Merge(), v8::internal::Zone::New(), v8::internal::compiler::TFGraph::NewNode(), node_origins_, v8::internal::compiler::PeeledIterationImpl::node_pairs_, v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::CommonOperatorBuilder::ResizeMergeOrPhi(), source_positions_, tmp_zone_, v8::internal::compiler::LoopTree::Loop::TotalSize(), and v8::internal::compiler::TFGraph::zone().
Referenced by PeelInnerLoops().
PeelInnerLoops()
void v8::internal::compiler::LoopPeeler::PeelInnerLoops (LoopTree::Loop * loop) [private]
Definition at line 218 of file loop-peeling.cc.
                                                  {
  // If the loop has nested loops, peel inside those.
  if (!loop->children().empty()) {
    for (LoopTree::Loop* inner_loop : loop->children()) {
      PeelInnerLoops(inner_loop);
    }
    return;
  }
  // Only peel small-enough loops.
  if (loop->TotalSize() > LoopPeeler::kMaxPeeledNodes) return;
  if (v8_flags.trace_turbo_loop) {
    PrintF("Peeling loop with header: ");
    for (Node* node : loop_tree_->HeaderNodes(loop)) {
      PrintF("%i ", node->id());
    }
    PrintF("\n");
  }
  Peel(loop);
}
References v8::internal::compiler::LoopTree::Loop::children(), v8::internal::compiler::LoopTree::HeaderNodes(), kMaxPeeledNodes, loop_tree_, Peel(), v8::internal::PrintF(), v8::internal::compiler::LoopTree::Loop::TotalSize(), and v8::internal::v8_flags.
Referenced by PeelInnerLoopsOfTree().
PeelInnerLoopsOfTree()
void v8::internal::compiler::LoopPeeler::PeelInnerLoopsOfTree ()
Definition at line 261 of file loop-peeling.cc.
                                      {
  for (LoopTree::Loop* loop : loop_tree_->outer_loops()) {
    PeelInnerLoops(loop);
  }
  EliminateLoopExits(graph_, tmp_zone_);
}
References EliminateLoopExits(), graph_, loop_tree_, v8::internal::compiler::LoopTree::outer_loops(), PeelInnerLoops(), and tmp_zone_.
Referenced by v8::internal::compiler::LoopPeelingPhase::Run().
Member Data Documentation
common_
CommonOperatorBuilder* const v8::internal::compiler::LoopPeeler::common_ [private]
Definition at line 58 of file loop-peeling.h.
Referenced by Peel().
graph_
TFGraph* const v8::internal::compiler::LoopPeeler::graph_ [private]
Definition at line 57 of file loop-peeling.h.
Referenced by Peel(), and PeelInnerLoopsOfTree().
kMaxPeeledNodes
const size_t v8::internal::compiler::LoopPeeler::kMaxPeeledNodes = 1000 [static]
Definition at line 54 of file loop-peeling.h.
Referenced by PeelInnerLoops().
loop_tree_
LoopTree* const v8::internal::compiler::LoopPeeler::loop_tree_ [private]
Definition at line 59 of file loop-peeling.h.
Referenced by Peel(), PeelInnerLoops(), and PeelInnerLoopsOfTree().
node_origins_
NodeOriginTable* const v8::internal::compiler::LoopPeeler::node_origins_ [private]
Definition at line 62 of file loop-peeling.h.
Referenced by Peel().
source_positions_
SourcePositionTable* const v8::internal::compiler::LoopPeeler::source_positions_ [private]
Definition at line 61 of file loop-peeling.h.
Referenced by Peel().
tmp_zone_
Zone* const v8::internal::compiler::LoopPeeler::tmp_zone_ [private]
Definition at line 60 of file loop-peeling.h.
Referenced by Peel(), and PeelInnerLoopsOfTree().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/loop-peeling.h
/mnt/V8SourceCode/src/compiler/loop-peeling.cc