v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator Class Reference
Classes
struct Result
Public Member Functions
ValueTypeFieldIterator (const Type *type, size_t index)
const Result operator* () const
ValueTypeFieldIterator & operator++ ()
bool operator== (const ValueTypeFieldIterator &other) const
bool operator!= (const ValueTypeFieldIterator &other) const
Private Attributes
const Type * type_
size_t index_
Detailed Description
Definition at line 28 of file class-debug-reader-generator.cc.
Constructor & Destructor Documentation
ValueTypeFieldIterator()
v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::ValueTypeFieldIterator (const Type * type, size_t index) [inline]
Definition at line 30 of file class-debug-reader-generator.cc.
      : type_(type), index_(index) {}
Member Function Documentation
operator!=()
bool v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator!= (const ValueTypeFieldIterator & other) const [inline]
Definition at line 66 of file class-debug-reader-generator.cc.
                                                             {
    return !(*this == other);
  }
operator*()
const Result v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator* () const [inline]
Definition at line 39 of file class-debug-reader-generator.cc.
                                 {
    if (auto struct_type = type_->StructSupertype()) {
      const auto& field = (*struct_type)->fields()[index_];
      return {field.name_and_type, field.pos, *field.offset, 0, 0};
    }
    const Type* type = type_;
    int bitfield_start_offset = 0;
    if (const auto type_wrapped_in_smi =
            Type::MatchUnaryGeneric(type_, TypeOracle::GetSmiTaggedGeneric())) {
      type = *type_wrapped_in_smi;
      bitfield_start_offset = TargetArchitecture::SmiTagAndShiftSize();
    }
    if (const BitFieldStructType* bit_field_struct_type =
            BitFieldStructType::DynamicCast(type)) {
      const auto& field = bit_field_struct_type->fields()[index_];
      return {field.name_and_type, field.pos, 0, field.num_bits,
              field.offset + bitfield_start_offset};
    }
    UNREACHABLE();
  }
References v8::internal::torque::TypeOracle::GetSmiTaggedGeneric(), v8::internal::torque::Type::MatchUnaryGeneric(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::Result::name_and_type, v8::internal::torque::TargetArchitecture::SmiTagAndShiftSize(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
operator++()
ValueTypeFieldIterator& v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator++ () [inline]
Definition at line 59 of file class-debug-reader-generator.cc.
                                       {
    ++index_;
    return *this;
  }
operator==()
bool v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator== (const ValueTypeFieldIterator & other) const [inline]
Definition at line 63 of file class-debug-reader-generator.cc.
                                                             {
    return type_ == other.type_ && index_ == other.index_;
  }
References index_, and type_.
Member Data Documentation
index_
size_t v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::index_ [private]
Definition at line 72 of file class-debug-reader-generator.cc.
Referenced by operator==().
type_
const Type* v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::type_ [private]
Definition at line 71 of file class-debug-reader-generator.cc.
Referenced by operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/class-debug-reader-generator.cc