v8::internal::NexusConfig Class Reference
#include <feedback-vector.h>
Public Types
enum Mode { MainThread
, BackgroundThread
 }
Public Member Functions
Mode mode () const
Isolate * isolate () const
MaybeObjectHandle NewHandle (Tagged< MaybeObject > object) const
template<typename T >
Handle< T > NewHandle (Tagged< T > object) const
bool can_write () const
Tagged< MaybeObject > GetFeedback (Tagged< FeedbackVector > vector, FeedbackSlot slot) const
void SetFeedback (Tagged< FeedbackVector > vector, FeedbackSlot slot, Tagged< MaybeObject > object, WriteBarrierMode mode=UPDATE_WRITE_BARRIER) const
std::pair< Tagged< MaybeObject >, Tagged< MaybeObject > > GetFeedbackPair (Tagged< FeedbackVector > vector, FeedbackSlot slot) const
void SetFeedbackPair (Tagged< FeedbackVector > vector, FeedbackSlot start_slot, Tagged< MaybeObject > feedback, WriteBarrierMode mode, Tagged< MaybeObject > feedback_extra, WriteBarrierMode mode_extra) const
Static Public Member Functions
static NexusConfig FromMainThread (Isolate *isolate)
static NexusConfig FromBackgroundThread (Isolate *isolate, LocalHeap *local_heap)
Private Member Functions
NexusConfig (Isolate *isolate)
NexusConfig (Isolate *isolate, LocalHeap *local_heap)
Private Attributes
Isolate *const isolate_
LocalHeap *const local_heap_
Detailed Description
Definition at line 881 of file feedback-vector.h.
Member Enumeration Documentation
Mode
enum v8::internal::NexusConfig::Mode
Enumerator
MainThread
BackgroundThread
Definition at line 894 of file feedback-vector.h.
{ MainThread, BackgroundThread };
Constructor & Destructor Documentation
NexusConfig() [1/2]
v8::internal::NexusConfig::NexusConfig (Isolate * isolate) [inline], [explicit], [private]
Definition at line 922 of file feedback-vector.h.
      : isolate_(isolate), local_heap_(nullptr) {}
NexusConfig() [2/2]
v8::internal::NexusConfig::NexusConfig (Isolate * isolate, LocalHeap * local_heap) [inline], [private]
Definition at line 924 of file feedback-vector.h.
      : isolate_(isolate), local_heap_(local_heap) {}
Member Function Documentation
can_write()
bool v8::internal::NexusConfig::can_write () const [inline]
Definition at line 906 of file feedback-vector.h.
{ return mode() == MainThread; }
References mode().
Referenced by SetFeedback(), and SetFeedbackPair().
FromBackgroundThread()
static NexusConfig v8::internal::NexusConfig::FromBackgroundThread (Isolate * isolate, LocalHeap * local_heap) [inline], [static]
Definition at line 888 of file feedback-vector.h.
                                                                 {
    DCHECK_NOT_NULL(isolate);
    return NexusConfig(isolate, local_heap);
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::JSHeapBroker::feedback_nexus_config().
FromMainThread()
static NexusConfig v8::internal::NexusConfig::FromMainThread (Isolate * isolate) [inline], [static]
Definition at line 883 of file feedback-vector.h.
                                                      {
    DCHECK_NOT_NULL(isolate);
    return NexusConfig(isolate);
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::JSHeapBroker::feedback_nexus_config().
GetFeedback()
Tagged< MaybeObject > v8::internal::NexusConfig::GetFeedback (Tagged< FeedbackVector > vector, FeedbackSlot slot) const [inline]
Definition at line 533 of file feedback-vector-inl.h.
                                                                      {
  return vector->SynchronizedGet(slot);
}
GetFeedbackPair()
std::pair< Tagged< MaybeObject >, Tagged< MaybeObject > > v8::internal::NexusConfig::GetFeedbackPair (Tagged< FeedbackVector > vector, FeedbackSlot slot) const
Definition at line 576 of file feedback-vector.cc.
                                                      {
  base::MutexGuardIf guard(isolate()->feedback_vector_access(),
                           mode() == BackgroundThread);
  Tagged<MaybeObject> feedback = vector->Get(slot);
  Tagged<MaybeObject> feedback_extra = vector->Get(slot.WithOffset(1));
  return std::make_pair(feedback, feedback_extra);
}
References BackgroundThread, isolate(), mode(), and v8::internal::FeedbackSlot::WithOffset().
Referenced by v8::internal::FeedbackNexus::GetFeedbackPair().
isolate()
Isolate* v8::internal::NexusConfig::isolate () const [inline]
Definition at line 900 of file feedback-vector.h.
{ return isolate_; }
Referenced by v8::internal::FeedbackNexus::ConfigureCloneObject(), v8::internal::FeedbackNexus::ConfigureMegamorphic(), v8::internal::FeedbackNexus::ConfigureUninitialized(), v8::internal::FeedbackNexus::CreateArrayOfSize(), GetFeedbackPair(), v8::internal::FeedbackNexus::ic_state(), and SetFeedbackPair().
mode()
Mode v8::internal::NexusConfig::mode () const [inline]
Definition at line 896 of file feedback-vector.h.
                    {
    return local_heap_ == nullptr ? MainThread : BackgroundThread;
  }
Referenced by GetFeedbackPair(), NewHandle(), SetFeedback(), and SetFeedbackPair().
NewHandle() [1/2]
MaybeObjectHandle v8::internal::NexusConfig::NewHandle (Tagged< MaybeObject > object) const
Definition at line 554 of file feedback-vector.cc.
                                                                         {
  if (mode() == Mode::MainThread) {
    return handle(object, isolate_);
  }
  DCHECK_EQ(mode(), Mode::BackgroundThread);
  return handle(object, local_heap_);
}
References DCHECK_EQ, v8::internal::handle(), isolate_, local_heap_, and mode().
Referenced by v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), v8::internal::FeedbackNexus::ExtractMegaDOMHandler(), v8::internal::FeedbackIterator::FeedbackIterator(), v8::internal::FeedbackNexus::FindHandlerForMap(), v8::internal::FeedbackNexus::GetConstructorFeedback(), and v8::internal::FeedbackNexus::IterateMapsWithUnclearedHandler().
NewHandle() [2/2]
template<typename T >
Handle< T > v8::internal::NexusConfig::NewHandle (Tagged< T > object) const
Definition at line 525 of file feedback-vector-inl.h.
                                                       {
  if (mode() == Mode::MainThread) {
    return handle(object, isolate_);
  }
  DCHECK_EQ(mode(), Mode::BackgroundThread);
  return handle(object, local_heap_);
}
References DCHECK_EQ, v8::internal::handle(), isolate_, local_heap_, and mode().
SetFeedback()
void v8::internal::NexusConfig::SetFeedback (Tagged< FeedbackVector > vector, FeedbackSlot slot, Tagged< MaybeObject > object, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) const [inline]
Definition at line 538 of file feedback-vector-inl.h.
                                                           {
  DCHECK(can_write());
  vector->SynchronizedSet(slot, feedback, mode);
}
References can_write(), v8::internal::DCHECK(), and mode().
Referenced by v8::internal::FeedbackNexus::SetFeedback().
SetFeedbackPair()
void v8::internal::NexusConfig::SetFeedbackPair (Tagged< FeedbackVector > vector, FeedbackSlot start_slot, Tagged< MaybeObject > feedback, WriteBarrierMode mode, Tagged< MaybeObject > feedback_extra, WriteBarrierMode mode_extra) const
Definition at line 562 of file feedback-vector.cc.
                                                                     {
  CHECK(can_write());
  CHECK_GT(vector->length(), start_slot.WithOffset(1).ToInt());
  base::MutexGuard mutex_guard(isolate()->feedback_vector_access());
  vector->Set(start_slot, feedback, mode);
  vector->Set(start_slot.WithOffset(1), feedback_extra, mode_extra);
}
References can_write(), CHECK, CHECK_GT, isolate(), mode(), v8::internal::FeedbackSlot::ToInt(), and v8::internal::FeedbackSlot::WithOffset().
Referenced by v8::internal::FeedbackNexus::SetFeedback().
Member Data Documentation
isolate_
Isolate* const v8::internal::NexusConfig::isolate_ [private]
Definition at line 927 of file feedback-vector.h.
Referenced by NewHandle().
local_heap_
LocalHeap* const v8::internal::NexusConfig::local_heap_ [private]
Definition at line 928 of file feedback-vector.h.
Referenced by NewHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector-inl.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc