v8::internal::BaseConsumedPreparseData< Data > Class Template Reference
#include <preparse-data-impl.h>
Classes
class ByteData
Public Member Functions
BaseConsumedPreparseData ()
BaseConsumedPreparseData (const BaseConsumedPreparseData &)=delete
BaseConsumedPreparseData & operator= (const BaseConsumedPreparseData &)=delete
virtual Data GetScopeData ()=0
virtual ProducedPreparseData * GetChildData (Zone *zone, int child_index)=0
ProducedPreparseData * GetDataForSkippableFunction (Zone *zone, int start_position, int *end_position, int *num_parameters, int *function_length, int *num_inner_functions, bool *uses_super_property, LanguageMode *language_mode) final
void RestoreScopeAllocationData (DeclarationScope *scope, AstValueFactory *ast_value_factory, Zone *zone) final
Private Member Functions
void RestoreDataForScope (Scope *scope, AstValueFactory *ast_value_factory, Zone *zone)
void RestoreDataForVariable (Variable *var)
void RestoreDataForInnerScopes (Scope *scope, AstValueFactory *ast_value_factory, Zone *zone)
Private Attributes
std::unique_ptr< ByteData > scope_data_
int child_index_
Additional Inherited Members
Detailed Description
template<class Data>
class v8::internal::BaseConsumedPreparseData< Data >
Definition at line 45 of file preparse-data-impl.h.
Constructor & Destructor Documentation
BaseConsumedPreparseData() [1/2]
template<class Data >
v8::internal::BaseConsumedPreparseData< Data >::BaseConsumedPreparseData () [inline]
Definition at line 156 of file preparse-data-impl.h.
: scope_data_(new ByteData()), child_index_(0) {}
BaseConsumedPreparseData() [2/2]
template<class Data >
v8::internal::BaseConsumedPreparseData< Data >::BaseConsumedPreparseData (const BaseConsumedPreparseData< Data > &) [delete]
Member Function Documentation
GetChildData()
template<class Data >
virtual ProducedPreparseData* v8::internal::BaseConsumedPreparseData< Data >::GetChildData (Zone * zone, int child_index) [pure virtual]
Implemented in v8::internal::ZoneConsumedPreparseData, and v8::internal::OnHeapConsumedPreparseData.
GetDataForSkippableFunction()
template<class Data >
ProducedPreparseData * v8::internal::BaseConsumedPreparseData< Data >::GetDataForSkippableFunction (Zone * zone, int start_position, int * end_position, int * num_parameters, int * function_length, int * num_inner_functions, bool * uses_super_property, LanguageMode * language_mode) [final], [virtual]
Implements v8::internal::ConsumedPreparseData.
Definition at line 586 of file preparse-data.cc.
                                 {
  // The skippable function *must* be the next function in the data. Use the
  // start position as a sanity check.
  typename ByteData::ReadingScope reading_scope(this);
  CHECK(scope_data_->HasRemainingBytes(
      PreparseByteDataConstants::kSkippableFunctionMinDataSize));
  int start_position_from_data = scope_data_->ReadVarint32();
  CHECK_EQ(start_position, start_position_from_data);
  *end_position = scope_data_->ReadVarint32();
  DCHECK_GT(*end_position, start_position);
  uint32_t has_data_and_num_parameters = scope_data_->ReadVarint32();
  bool has_data = HasDataField::decode(has_data_and_num_parameters);
  *num_parameters =
      NumberOfParametersField::decode(has_data_and_num_parameters);
  bool length_equals_parameters =
      LengthEqualsParametersField::decode(has_data_and_num_parameters);
  if (length_equals_parameters) {
    *function_length = *num_parameters;
  } else {
    *function_length = scope_data_->ReadVarint32();
  }
  *num_inner_functions = scope_data_->ReadVarint32();
  uint8_t language_and_super = scope_data_->ReadQuarter();
  *language_mode = LanguageMode(LanguageField::decode(language_and_super));
  *uses_super_property = UsesSuperField::decode(language_and_super);
  if (!has_data) return nullptr;
  // Retrieve the corresponding PreparseData and associate it to the
  // skipped function. If the skipped functions contains inner functions, those
  // can be skipped when the skipped function is eagerly parsed.
  return GetChildData(zone, child_index_++);
}
References CHECK, CHECK_EQ, DCHECK_GT, and v8::internal::PreparseByteDataConstants::kSkippableFunctionMinDataSize.
GetScopeData()
template<class Data >
virtual Data v8::internal::BaseConsumedPreparseData< Data >::GetScopeData () [pure virtual]
Implemented in v8::internal::ZoneConsumedPreparseData, and v8::internal::OnHeapConsumedPreparseData.
operator=()
template<class Data >
BaseConsumedPreparseData& v8::internal::BaseConsumedPreparseData< Data >::operator= (const BaseConsumedPreparseData< Data > &) [delete]
RestoreDataForInnerScopes()
template<typename Data >
void v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForInnerScopes (Scope * scope, AstValueFactory * ast_value_factory, Zone * zone) [private]
Definition at line 744 of file preparse-data.cc.
                                                                  {
  for (Scope* inner = scope->inner_scope(); inner != nullptr;
       inner = inner->sibling()) {
    RestoreDataForScope(inner, ast_value_factory, zone);
  }
}
References v8::internal::Scope::inner_scope(), and v8::internal::Scope::sibling().
RestoreDataForScope()
template<typename Data >
void v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope (Scope * scope, AstValueFactory * ast_value_factory, Zone * zone) [private]
Definition at line 649 of file preparse-data.cc.
                                                                  {
  if (scope->is_declaration_scope() &&
      scope->AsDeclarationScope()->is_skipped_function()) {
    return;
  }
  // It's possible that scope is not present in the data at all (since PreParser
  // doesn't create the corresponding scope). In this case, the Scope won't
  // contain any variables for which we need the data.
  if (!PreparseDataBuilder::ScopeNeedsData(scope)) return;
  // scope_type is stored only in debug mode.
  DCHECK_EQ(scope_data_->ReadUint8(), scope->scope_type());
  CHECK(scope_data_->HasRemainingBytes(ByteData::kUint8Size));
  uint32_t scope_data_flags = scope_data_->ReadUint8();
  if (ScopeSloppyEvalCanExtendVarsBit::decode(scope_data_flags)) {
    scope->RecordEvalCall();
  }
  if (InnerScopeCallsEvalField::decode(scope_data_flags)) {
    scope->RecordInnerScopeEvalCall();
  }
  if (NeedsPrivateNameContextChainRecalcField::decode(scope_data_flags)) {
    scope->AsDeclarationScope()->RecordNeedsPrivateNameContextChainRecalc();
  }
  if (ShouldSaveClassVariableIndexField::decode(scope_data_flags)) {
    Variable* var = scope->AsClassScope()->class_variable();
    // An anonymous class whose class variable needs to be saved might not
    // have the class variable created during reparse since we skip parsing
    // the inner scopes that contain potential access to static private
    // methods. So create it now.
    if (var == nullptr) {
      DCHECK(scope->AsClassScope()->is_anonymous_class());
      var = scope->AsClassScope()->DeclareClassVariable(
          ast_value_factory, ast_value_factory->empty_string(),
          kNoSourcePosition);
      AstNodeFactory factory(ast_value_factory, zone);
      Declaration* declaration =
          factory.NewVariableDeclaration(kNoSourcePosition);
      scope->declarations()->Add(declaration);
      declaration->set_var(var);
    }
    var->set_is_used();
    var->ForceContextAllocation();
    scope->AsClassScope()->set_should_save_class_variable();
  }
  if (scope->is_function_scope()) {
    Variable* function = scope->AsDeclarationScope()->function_var();
    if (function != nullptr) RestoreDataForVariable(function);
  }
  for (Variable* var : *scope->locals()) {
    if (IsSerializableVariableMode(var->mode())) RestoreDataForVariable(var);
  }
  RestoreDataForInnerScopes(scope, ast_value_factory, zone);
}
References v8::internal::Scope::AsClassScope(), v8::internal::Scope::AsDeclarationScope(), CHECK, v8::internal::ClassScope::class_variable(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scope::declarations(), v8::internal::ClassScope::DeclareClassVariable(), v8::internal::Variable::ForceContextAllocation(), v8::internal::DeclarationScope::function_var(), v8::internal::ClassScope::is_anonymous_class(), v8::internal::Scope::is_declaration_scope(), v8::internal::Scope::is_function_scope(), v8::internal::DeclarationScope::is_skipped_function(), v8::internal::IsSerializableVariableMode(), v8::internal::kNoSourcePosition, v8::internal::PreparseByteDataConstants::kUint8Size, v8::internal::Scope::locals(), v8::internal::AstNodeFactory::NewVariableDeclaration(), v8::internal::Scope::RecordEvalCall(), v8::internal::Scope::RecordInnerScopeEvalCall(), v8::internal::DeclarationScope::RecordNeedsPrivateNameContextChainRecalc(), v8::internal::Scope::scope_type(), v8::internal::PreparseDataBuilder::ScopeNeedsData(), v8::internal::Variable::set_is_used(), v8::internal::ClassScope::set_should_save_class_variable(), and v8::internal::Declaration::set_var().
RestoreDataForVariable()
template<typename Data >
void v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForVariable (Variable * var) [private]
Definition at line 709 of file preparse-data.cc.
                                                                         {
#ifdef DEBUG
  const AstRawString* name = var->raw_name();
  bool data_one_byte = scope_data_->ReadUint8();
  DCHECK_IMPLIES(name->is_one_byte(), data_one_byte);
  DCHECK_EQ(scope_data_->ReadUint32(), static_cast<uint32_t>(name->length()));
  if (!name->is_one_byte() && data_one_byte) {
    // It's possible that "name" is a two-byte representation of the string
    // stored in the data.
    for (int i = 0; i < 2 * name->length(); i += 2) {
#if defined(V8_TARGET_LITTLE_ENDIAN)
      DCHECK_EQ(scope_data_->ReadUint8(), name->raw_data()[i]);
      DCHECK_EQ(0, name->raw_data()[i + 1]);
#else
      DCHECK_EQ(scope_data_->ReadUint8(), name->raw_data()[i + 1]);
      DCHECK_EQ(0, name->raw_data()[i]);
#endif // V8_TARGET_LITTLE_ENDIAN
    }
  } else {
    for (int i = 0; i < name->length(); ++i) {
      DCHECK_EQ(scope_data_->ReadUint8(), name->raw_data()[i]);
    }
  }
#endif
  uint8_t variable_data = scope_data_->ReadQuarter();
  if (VariableMaybeAssignedField::decode(variable_data)) {
    var->SetMaybeAssigned();
  }
  if (VariableContextAllocatedField::decode(variable_data)) {
    var->set_is_used();
    var->ForceContextAllocation();
  }
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Variable::ForceContextAllocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::name, v8::internal::Variable::raw_name(), v8::internal::Variable::set_is_used(), and v8::internal::Variable::SetMaybeAssigned().
RestoreScopeAllocationData()
template<class Data >
void v8::internal::BaseConsumedPreparseData< Data >::RestoreScopeAllocationData (DeclarationScope * scope, AstValueFactory * ast_value_factory, Zone * zone) [final], [virtual]
Implements v8::internal::ConsumedPreparseData.
Definition at line 626 of file preparse-data.cc.
                                                                             {
  DCHECK_EQ(scope->scope_type(), ScopeType::FUNCTION_SCOPE);
  typename ByteData::ReadingScope reading_scope(this);
#ifdef DEBUG
  int magic_value_from_data = scope_data_->ReadUint32();
  // Check that we've consumed all inner function data.
  DCHECK_EQ(magic_value_from_data, ByteData::kMagicValue);
  int start_position_from_data = scope_data_->ReadUint32();
  int end_position_from_data = scope_data_->ReadUint32();
  DCHECK_EQ(start_position_from_data, scope->start_position());
  DCHECK_EQ(end_position_from_data, scope->end_position());
#endif
  RestoreDataForScope(scope, ast_value_factory, zone);
  // Check that we consumed all scope data.
  DCHECK_EQ(scope_data_->RemainingBytes(), 0);
}
References DCHECK_EQ, v8::internal::Scope::end_position(), v8::internal::FUNCTION_SCOPE, v8::internal::Scope::scope_type(), and v8::internal::Scope::start_position().
Member Data Documentation
child_index_
template<class Data >
int v8::internal::BaseConsumedPreparseData< Data >::child_index_ [private]
Definition at line 188 of file preparse-data-impl.h.
scope_data_
template<class Data >
std::unique_ptr<ByteData> v8::internal::BaseConsumedPreparseData< Data >::scope_data_ [private]
Definition at line 185 of file preparse-data-impl.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data-impl.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc