v8::internal::BoyerMooreLookahead Class Reference
#include <regexp-compiler.h>
Public Member Functions
BoyerMooreLookahead (int length, RegExpCompiler *compiler, Zone *zone)
int length ()
int max_char ()
RegExpCompiler * compiler ()
int Count (int map_number)
BoyerMoorePositionInfo * at (int i)
void Set (int map_number, int character)
void SetInterval (int map_number, const Interval &interval)
void SetAll (int map_number)
void SetRest (int from_map)
void EmitSkipInstructions (RegExpMacroAssembler *masm)
Private Member Functions
int GetSkipTable (int min_lookahead, int max_lookahead, DirectHandle< ByteArray > boolean_skip_table, DirectHandle< ByteArray > nibble_table=DirectHandle< ByteArray >{})
bool FindWorthwhileInterval (int *from, int *to)
int FindBestInterval (int max_number_of_chars, int old_biggest_points, int *from, int *to)
Private Attributes
int length_
RegExpCompiler * compiler_
int max_char_
ZoneList< BoyerMoorePositionInfo * > * bitmaps_
Detailed Description
Definition at line 171 of file regexp-compiler.h.
Constructor & Destructor Documentation
BoyerMooreLookahead()
v8::internal::BoyerMooreLookahead::BoyerMooreLookahead (int length, RegExpCompiler * compiler, Zone * zone)
Definition at line 2876 of file regexp-compiler.cc.
    : length_(length),
      compiler_(compiler),
      max_char_(MaxCodeUnit(compiler->one_byte())) {
  bitmaps_ = zone->New<ZoneList<BoyerMoorePositionInfo*>>(length, zone);
  for (int i = 0; i < length; i++) {
    bitmaps_->Add(zone->New<BoyerMoorePositionInfo>(), zone);
  }
}
References bitmaps_, length(), and v8::internal::Zone::New().
Member Function Documentation
at()
BoyerMoorePositionInfo* v8::internal::BoyerMooreLookahead::at (int i) [inline]
Definition at line 181 of file regexp-compiler.h.
{ return bitmaps_->at(i); }
References bitmaps_.
Referenced by v8::internal::AssertionNode::EmitBoundaryCheck().
compiler()
RegExpCompiler* v8::internal::BoyerMooreLookahead::compiler () [inline]
Definition at line 177 of file regexp-compiler.h.
{ return compiler_; }
References compiler_.
Referenced by v8::internal::ActionNode::FillInBMInfo(), and v8::internal::TextNode::FillInBMInfo().
Count()
int v8::internal::BoyerMooreLookahead::Count (int map_number) [inline]
Definition at line 179 of file regexp-compiler.h.
{ return bitmaps_->at(map_number)->map_count(); }
References bitmaps_.
Referenced by FindBestInterval().
EmitSkipInstructions()
void v8::internal::BoyerMooreLookahead::EmitSkipInstructions (RegExpMacroAssembler * masm)
Definition at line 3009 of file regexp-compiler.cc.
                                                                         {
  const int kSize = RegExpMacroAssembler::kTableSize;
  int min_lookahead = 0;
  int max_lookahead = 0;
  if (!FindWorthwhileInterval(&min_lookahead, &max_lookahead)) return;
  // Check if we only have a single non-empty position info, and that info
  // contains precisely one character.
  bool found_single_character = false;
  int single_character = 0;
  for (int i = max_lookahead; i >= min_lookahead; i--) {
    BoyerMoorePositionInfo* map = bitmaps_->at(i);
    if (map->map_count() == 0) continue;
    if (found_single_character || map->map_count() > 1) {
      found_single_character = false;
      break;
    }
    DCHECK(!found_single_character);
    DCHECK_EQ(map->map_count(), 1);
    found_single_character = true;
    single_character = BitsetFirstSetBit(map->raw_bitset());
    DCHECK_NE(single_character, -1);
  }
  int lookahead_width = max_lookahead + 1 - min_lookahead;
  if (found_single_character && lookahead_width == 1 && max_lookahead < 3) {
    // The mask-compare can probably handle this better.
    return;
  }
  if (found_single_character) {
    // TODO(pthier): Add vectorized version.
    Label cont, again;
    masm->Bind(&again);
    masm->LoadCurrentCharacter(max_lookahead, &cont, true);
    if (max_char_ > kSize) {
      masm->CheckCharacterAfterAnd(single_character,
                                   RegExpMacroAssembler::kTableMask, &cont);
    } else {
      masm->CheckCharacter(single_character, &cont);
    }
    masm->AdvanceCurrentPosition(lookahead_width);
    masm->GoTo(&again);
    masm->Bind(&cont);
    return;
  }
  Factory* factory = masm->isolate()->factory();
  Handle<ByteArray> boolean_skip_table =
      factory->NewByteArray(kSize, AllocationType::kOld);
  Handle<ByteArray> nibble_table;
  const int skip_distance = max_lookahead + 1 - min_lookahead;
  if (masm->SkipUntilBitInTableUseSimd(skip_distance)) {
    // The current implementation is tailored specifically for 128-bit tables.
    static_assert(kSize == 128);
    nibble_table =
        factory->NewByteArray(kSize / kBitsPerByte, AllocationType::kOld);
  }
  GetSkipTable(min_lookahead, max_lookahead, boolean_skip_table, nibble_table);
  DCHECK_NE(0, skip_distance);
  masm->SkipUntilBitInTable(max_lookahead, boolean_skip_table, nibble_table,
                            skip_distance);
}
References v8::internal::RegExpMacroAssembler::AdvanceCurrentPosition(), v8::internal::RegExpMacroAssembler::Bind(), bitmaps_, v8::internal::anonymous_namespace{regexp-compiler.cc}::BitsetFirstSetBit(), v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::RegExpMacroAssembler::CheckCharacterAfterAnd(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::factory(), FindWorthwhileInterval(), GetSkipTable(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::kBitsPerByte, v8::internal::kOld, v8::internal::RegExpMacroAssembler::kTableMask, v8::internal::RegExpMacroAssembler::kTableSize, v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::BoyerMoorePositionInfo::map_count(), max_char_, v8::internal::FactoryBase< Impl >::NewByteArray(), v8::internal::BoyerMoorePositionInfo::raw_bitset(), v8::internal::RegExpMacroAssembler::SkipUntilBitInTable(), and v8::internal::RegExpMacroAssembler::SkipUntilBitInTableUseSimd().
Referenced by v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch().
FindBestInterval()
int v8::internal::BoyerMooreLookahead::FindBestInterval (int max_number_of_chars, int old_biggest_points, int * from, int * to) [private]
Definition at line 2910 of file regexp-compiler.cc.
                                                   {
  int biggest_points = old_biggest_points;
  static const int kSize = RegExpMacroAssembler::kTableSize;
  for (int i = 0; i < length_;) {
    while (i < length_ && Count(i) > max_number_of_chars) i++;
    if (i == length_) break;
    int remembered_from = i;
    BoyerMoorePositionInfo::Bitset union_bitset;
    for (; i < length_ && Count(i) <= max_number_of_chars; i++) {
      union_bitset |= bitmaps_->at(i)->raw_bitset();
    }
    int frequency = 0;
    // Iterate only over set bits.
    int j;
    while ((j = BitsetFirstSetBit(union_bitset)) != -1) {
      DCHECK(union_bitset[j]); // Sanity check.
      // Add 1 to the frequency to give a small per-character boost for
      // the cases where our sampling is not good enough and many
      // characters have a frequency of zero. This means the frequency
      // can theoretically be up to 2*kSize though we treat it mostly as
      // a fraction of kSize.
      frequency += compiler_->frequency_collator()->Frequency(j) + 1;
      union_bitset.reset(j);
    }
    // We use the probability of skipping times the distance we are skipping to
    // judge the effectiveness of this. Actually we have a cut-off: By
    // dividing by 2 we switch off the skipping if the probability of skipping
    // is less than 50%. This is because the multibyte mask-and-compare
    // skipping in quickcheck is more likely to do well on this case.
    bool in_quickcheck_range =
        ((i - remembered_from < 4) ||
         (compiler_->one_byte() ? remembered_from <= 4 : remembered_from <= 2));
    // Called 'probability' but it is only a rough estimate and can actually
    // be outside the 0-kSize range.
    int probability = (in_quickcheck_range ? kSize / 2 : kSize) - frequency;
    int points = (i - remembered_from) * probability;
    if (points > biggest_points) {
      *from = remembered_from;
      *to = i - 1;
      biggest_points = points;
    }
  }
  return biggest_points;
}
References bitmaps_, v8::internal::anonymous_namespace{regexp-compiler.cc}::BitsetFirstSetBit(), compiler_, Count(), v8::internal::DCHECK(), v8::internal::FrequencyCollator::Frequency(), v8::internal::RegExpCompiler::frequency_collator(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpMacroAssembler::kTableSize, length_, and v8::internal::RegExpCompiler::one_byte().
Referenced by FindWorthwhileInterval().
FindWorthwhileInterval()
bool v8::internal::BoyerMooreLookahead::FindWorthwhileInterval (int * from, int * to) [private]
Definition at line 2890 of file regexp-compiler.cc.
                                                                   {
  int biggest_points = 0;
  // If more than 32 characters out of 128 can occur it is unlikely that we can
  // be lucky enough to step forwards much of the time.
  const int kMaxMax = 32;
  for (int max_number_of_chars = 4; max_number_of_chars < kMaxMax;
       max_number_of_chars *= 2) {
    biggest_points =
        FindBestInterval(max_number_of_chars, biggest_points, from, to);
  }
  if (biggest_points == 0) return false;
  return true;
}
References FindBestInterval().
Referenced by EmitSkipInstructions().
GetSkipTable()
int v8::internal::BoyerMooreLookahead::GetSkipTable (int min_lookahead, int max_lookahead, DirectHandle< ByteArray > boolean_skip_table, DirectHandle< ByteArray > nibble_table = DirectHandle<ByteArray>{}) [private]
Definition at line 2971 of file regexp-compiler.cc.
                                          {
  const int kSkipArrayEntry = 0;
  const int kDontSkipArrayEntry = 1;
  std::memset(boolean_skip_table->begin(), kSkipArrayEntry,
              boolean_skip_table->length());
  const bool fill_nibble_table = !nibble_table.is_null();
  if (fill_nibble_table) {
    std::memset(nibble_table->begin(), 0, nibble_table->length());
  }
  for (int i = max_lookahead; i >= min_lookahead; i--) {
    BoyerMoorePositionInfo::Bitset bitset = bitmaps_->at(i)->raw_bitset();
    // Iterate only over set bits.
    int j;
    while ((j = BitsetFirstSetBit(bitset)) != -1) {
      DCHECK(bitset[j]); // Sanity check.
      boolean_skip_table->set(j, kDontSkipArrayEntry);
      if (fill_nibble_table) {
        int lo_nibble = j & 0x0f;
        int hi_nibble = (j >> 4) & 0x07;
        int row = nibble_table->get(lo_nibble);
        row |= 1 << hi_nibble;
        nibble_table->set(lo_nibble, row);
      }
      bitset.reset(j);
    }
  }
  const int skip = max_lookahead + 1 - min_lookahead;
  return skip;
}
References bitmaps_, v8::internal::anonymous_namespace{regexp-compiler.cc}::BitsetFirstSetBit(), v8::internal::DCHECK(), and v8::internal::DirectHandle< T >::is_null().
Referenced by EmitSkipInstructions().
length()
int v8::internal::BoyerMooreLookahead::length () [inline]
Definition at line 175 of file regexp-compiler.h.
{ return length_; }
References length_.
Referenced by BoyerMooreLookahead(), and v8::internal::TextNode::FillInBMInfo().
max_char()
int v8::internal::BoyerMooreLookahead::max_char () [inline]
Definition at line 176 of file regexp-compiler.h.
{ return max_char_; }
References max_char_.
Referenced by v8::internal::TextNode::FillInBMInfo().
Set()
void v8::internal::BoyerMooreLookahead::Set (int map_number, int character) [inline]
Definition at line 183 of file regexp-compiler.h.
                                          {
    if (character > max_char_) return;
    BoyerMoorePositionInfo* info = bitmaps_->at(map_number);
    info->Set(character);
  }
References bitmaps_, v8::internal::character, max_char_, and v8::internal::BoyerMoorePositionInfo::Set().
Referenced by v8::internal::TextNode::FillInBMInfo().
SetAll()
void v8::internal::BoyerMooreLookahead::SetAll (int map_number) [inline]
Definition at line 199 of file regexp-compiler.h.
{ bitmaps_->at(map_number)->SetAll(); }
References bitmaps_.
Referenced by v8::internal::TextNode::FillInBMInfo(), and SetRest().
SetInterval()
void v8::internal::BoyerMooreLookahead::SetInterval (int map_number, const Interval & interval) [inline]
Definition at line 189 of file regexp-compiler.h.
                                                             {
    if (interval.from() > max_char_) return;
    BoyerMoorePositionInfo* info = bitmaps_->at(map_number);
    if (interval.to() > max_char_) {
      info->SetInterval(Interval(interval.from(), max_char_));
    } else {
      info->SetInterval(interval);
    }
  }
References bitmaps_, v8::internal::Interval::from(), max_char_, v8::internal::BoyerMoorePositionInfo::SetInterval(), and v8::internal::Interval::to().
Referenced by v8::internal::TextNode::FillInBMInfo().
SetRest()
void v8::internal::BoyerMooreLookahead::SetRest (int from_map) [inline]
Definition at line 201 of file regexp-compiler.h.
                             {
    for (int i = from_map; i < length_; i++) SetAll(i);
  }
References length_, and SetAll().
Referenced by v8::internal::BackReferenceNode::FillInBMInfo(), v8::internal::ChoiceNode::FillInBMInfo(), and v8::internal::LoopChoiceNode::FillInBMInfo().
Member Data Documentation
bitmaps_
ZoneList<BoyerMoorePositionInfo*>* v8::internal::BoyerMooreLookahead::bitmaps_ [private]
Definition at line 215 of file regexp-compiler.h.
Referenced by at(), BoyerMooreLookahead(), Count(), EmitSkipInstructions(), FindBestInterval(), GetSkipTable(), Set(), SetAll(), and SetInterval().
compiler_
RegExpCompiler* v8::internal::BoyerMooreLookahead::compiler_ [private]
Definition at line 212 of file regexp-compiler.h.
Referenced by compiler(), and FindBestInterval().
length_
int v8::internal::BoyerMooreLookahead::length_ [private]
Definition at line 211 of file regexp-compiler.h.
Referenced by FindBestInterval(), length(), and SetRest().
max_char_
int v8::internal::BoyerMooreLookahead::max_char_ [private]
Definition at line 214 of file regexp-compiler.h.
Referenced by EmitSkipInstructions(), max_char(), Set(), and SetInterval().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc