v8::internal::maglev::CheckInstanceType Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckInstanceType (uint64_t bitfield, CheckType check_type, const InstanceType first_instance_type, const InstanceType last_instance_type)
Input & receiver_input ()
CheckType check_type () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
InstanceType first_instance_type () const
InstanceType last_instance_type () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::EagerDeopt()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kReceiverIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckInstanceType >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Private Attributes
const InstanceType first_instance_type_
const InstanceType last_instance_type_
Additional Inherited Members
Detailed Description
Definition at line 7157 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckInstanceType::Base = FixedInputNodeT<1, CheckInstanceType> [private]
Definition at line 7158 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::CheckInstanceType::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 7191 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckInstanceType()
v8::internal::maglev::CheckInstanceType::CheckInstanceType (uint64_t bitfield, CheckType check_type, const InstanceType first_instance_type, const InstanceType last_instance_type) [inline], [explicit]
Definition at line 7161 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)),
        first_instance_type_(first_instance_type),
        last_instance_type_(last_instance_type) {
    DCHECK_LE(first_instance_type, last_instance_type);
  }
References DCHECK_LE.
Member Function Documentation
check_type()
CheckType v8::internal::maglev::CheckInstanceType::check_type () const [inline]
Definition at line 7177 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
first_instance_type()
InstanceType v8::internal::maglev::CheckInstanceType::first_instance_type () const [inline]
Definition at line 7187 of file maglev-ir.h.
{ return first_instance_type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CheckInstanceType::GenerateCode (MaglevAssembler * , const ProcessingState &)
last_instance_type()
InstanceType v8::internal::maglev::CheckInstanceType::last_instance_type () const [inline]
Definition at line 7188 of file maglev-ir.h.
{ return last_instance_type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::CheckInstanceType::options () const [inline]
Definition at line 7183 of file maglev-ir.h.
                       {
    return std::tuple{check_type(), first_instance_type_, last_instance_type_};
  }
PrintParams()
void v8::internal::maglev::CheckInstanceType::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8113 of file maglev-ir.cc.
                                                                               {
  os << "(" << first_instance_type_;
  if (first_instance_type_ != last_instance_type_) {
    os << " - " << last_instance_type_;
  }
  os << ")";
}
References first_instance_type_, and last_instance_type_.
receiver_input()
Input& v8::internal::maglev::CheckInstanceType::receiver_input () [inline]
Definition at line 7175 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CheckInstanceType::SetValueLocationConstraints ()
Member Data Documentation
first_instance_type_
const InstanceType v8::internal::maglev::CheckInstanceType::first_instance_type_ [private]
Definition at line 7192 of file maglev-ir.h.
Referenced by PrintParams().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckInstanceType::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 7172 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckInstanceType::kProperties = OpProperties::EagerDeopt() [static], [constexpr]
Definition at line 7170 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CheckInstanceType::kReceiverIndex = 0 [static], [constexpr]
Definition at line 7174 of file maglev-ir.h.
last_instance_type_
const InstanceType v8::internal::maglev::CheckInstanceType::last_instance_type_ [private]
Definition at line 7193 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc