v8::Extension Class Reference
Ignore.
#include <v8-extension.h>
Public Member Functions
Extension (const char *name, const char *source=nullptr, int dep_count=0, const char **deps=nullptr, int source_length=-1)
virtual ~Extension ()
virtual Local< FunctionTemplate > GetNativeFunctionTemplate (Isolate *isolate, Local< String > name)
const char * name () const
size_t source_length () const
const String::ExternalOneByteStringResource * source () const
int dependency_count () const
const char ** dependencies () const
void set_auto_enable (bool value)
bool auto_enable ()
Extension (const Extension &)=delete
void operator= (const Extension &)=delete
Private Attributes
const char * name_
size_t source_length_
String::ExternalOneByteStringResource * source_
int dep_count_
const char ** deps_
bool auto_enable_
Detailed Description
Ignore.
Definition at line 23 of file v8-extension.h.
Constructor & Destructor Documentation
Extension() [1/2]
v8::Extension::Extension (const char * name, const char * source = nullptr, int dep_count = 0, const char ** deps = nullptr, int source_length = -1)
Definition at line 494 of file api.cc.
    : name_(name),
      source_length_(source_length >= 0
                         ? source_length
                         : (source ? static_cast<int>(strlen(source)) : 0)),
      dep_count_(dep_count),
      deps_(deps),
      auto_enable_(false) {
  source_ = new ExtensionResource(source, source_length_);
  CHECK(source != nullptr || source_length_ == 0);
}
References CHECK, source(), source_, and source_length_.
 Extension()
virtual v8::Extension::~Extension () [inline], [virtual]
Definition at line 29 of file v8-extension.h.
{ delete source_; }
Extension() [2/2]
v8::Extension::Extension (const Extension &) [delete]
Member Function Documentation
auto_enable()
bool v8::Extension::auto_enable () [inline]
Definition at line 43 of file v8-extension.h.
{ return auto_enable_; }
dependencies()
const char** v8::Extension::dependencies () const [inline]
Definition at line 41 of file v8-extension.h.
{ return deps_; }
Referenced by v8::internal::Genesis::InstallExtension().
dependency_count()
int v8::Extension::dependency_count () const [inline]
Definition at line 40 of file v8-extension.h.
{ return dep_count_; }
Referenced by v8::internal::Genesis::InstallExtension().
GetNativeFunctionTemplate()
virtual Local<FunctionTemplate> v8::Extension::GetNativeFunctionTemplate (Isolate * isolate, Local< String > name) [inline], [virtual]
Reimplemented in v8::internal::FuzzilliExtension, v8::internal::VTuneDomainSupportExtension, v8::internal::TriggerFailureExtension, v8::internal::StatisticsExtension, v8::internal::IgnitionStatisticsExtension, v8::internal::GCExtension, v8::internal::ExternalizeStringExtension, and v8::internal::CpuTraceMarkExtension.
Definition at line 30 of file v8-extension.h.
                                            {
    return Local<FunctionTemplate>();
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
name()
const char* v8::Extension::name () const [inline]
Definition at line 35 of file v8-extension.h.
{ return name_; }
Referenced by v8::internal::Genesis::CompileExtension(), v8::internal::StatisticsExtension::GetCounters(), v8::internal::IgnitionStatisticsExtension::GetNativeFunctionTemplate(), and v8::internal::Genesis::InstallExtension().
operator=()
void v8::Extension::operator= (const Extension &) [delete]
set_auto_enable()
void v8::Extension::set_auto_enable (bool value) [inline]
Definition at line 42 of file v8-extension.h.
{ auto_enable_ = value; }
References v8::internal::value.
source()
const String::ExternalOneByteStringResource* v8::Extension::source () const [inline]
Definition at line 37 of file v8-extension.h.
                                                            {
    return source_;
  }
Referenced by v8::internal::Genesis::CompileExtension(), and Extension().
source_length()
size_t v8::Extension::source_length () const [inline]
Definition at line 36 of file v8-extension.h.
{ return source_length_; }
Member Data Documentation
auto_enable_
bool v8::Extension::auto_enable_ [private]
Definition at line 55 of file v8-extension.h.
dep_count_
int v8::Extension::dep_count_ [private]
Definition at line 53 of file v8-extension.h.
deps_
const char** v8::Extension::deps_ [private]
Definition at line 54 of file v8-extension.h.
name_
const char* v8::Extension::name_ [private]
Definition at line 50 of file v8-extension.h.
source_
String::ExternalOneByteStringResource* v8::Extension::source_ [private]
Definition at line 52 of file v8-extension.h.
Referenced by Extension().
source_length_
size_t v8::Extension::source_length_ [private]
Definition at line 51 of file v8-extension.h.
Referenced by Extension().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-extension.h
/mnt/V8SourceCode/src/api/api.cc