v8::internal::CpuFeatures Class Reference
#include <cpu-features.h>
Public Member Functions
CpuFeatures (const CpuFeatures &)=delete
CpuFeatures & operator= (const CpuFeatures &)=delete
Static Public Member Functions
static void Probe (bool cross_compile)
static unsigned SupportedFeatures ()
static bool IsSupported (CpuFeature f)
static void SetSupported (CpuFeature f)
static void SetUnsupported (CpuFeature f)
static bool SupportsWasmSimd128 ()
static bool SupportsOptimizer ()
static unsigned icache_line_size ()
static unsigned dcache_line_size ()
static void PrintTarget ()
static void PrintFeatures ()
Static Private Member Functions
static void FlushICache (void *start, size_t size)
static void ProbeImpl (bool cross_compile)
Static Private Attributes
static unsigned supported_ = 0
static unsigned icache_line_size_ = 0
static unsigned dcache_line_size_ = 0
static bool initialized_ = false
static bool supports_wasm_simd_128_ = false
static bool supports_cetss_ = false
Friends
class ExternalReference
void V8_EXPORT_PRIVATE FlushInstructionCache (void *, size_t)
Detailed Description
Definition at line 114 of file cpu-features.h.
Constructor & Destructor Documentation
CpuFeatures()
v8::internal::CpuFeatures::CpuFeatures (const CpuFeatures &) [delete]
Member Function Documentation
dcache_line_size()
static unsigned v8::internal::CpuFeatures::dcache_line_size () [inline], [static]
Definition at line 147 of file cpu-features.h.
                                            {
    DCHECK_NE(dcache_line_size_, 0);
    return dcache_line_size_;
  }
References DCHECK_NE.
FlushICache()
void v8::internal::CpuFeatures::FlushICache (void * start, size_t size) [static], [private]
Definition at line 15 of file cpu-riscv.cc.
                                                      {
#if !defined(USE_SIMULATOR)
  char* end = reinterpret_cast<char*>(start) + size;
  // SYS_riscv_flush_icache is a symbolic constant used in user-space code to
  // identify the flush_icache system call, while __NR_riscv_flush_icache is the
  // corresponding system call number used in the kernel to dispatch the system
  // call.
  // The flag set to zero will flush all cpu cores.
  syscall(__NR_riscv_flush_icache, start, end, 0);
#endif // !USE_SIMULATOR.
}
References v8::internal::compiler::end(), and size().
icache_line_size()
static unsigned v8::internal::CpuFeatures::icache_line_size () [inline], [static]
Definition at line 142 of file cpu-features.h.
                                            {
    DCHECK_NE(icache_line_size_, 0);
    return icache_line_size_;
  }
References DCHECK_NE.
IsSupported()
static bool v8::internal::CpuFeatures::IsSupported (CpuFeature f) [inline], [static]
Definition at line 131 of file cpu-features.h.
                                        {
    return (supported_ & (1u << f)) != 0;
  }
Referenced by v8::internal::Assembler::aligned_cmpb(), v8::internal::Assembler::aligned_cmpw(), v8::internal::Assembler::aligned_j(), v8::internal::Assembler::aligned_jmp(), v8::internal::Assembler::aligned_testb(), v8::internal::Assembler::aligned_testw(), v8::internal::wasm::liftoff::AtomicBinop(), v8::internal::SharedMacroAssemblerBase::Blendvpd(), v8::internal::SharedMacroAssemblerBase::Blendvps(), v8::internal::MacroAssembler::CalcScaledAddress(), v8::internal::compiler::fast_api_call::CanOptimizeFastSignature(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::CheckBailoutAllowed(), v8::internal::MacroAssembler::Clz32(), v8::internal::compiler::Clz64Latency(), v8::internal::MacroAssembler::Ctz32(), v8::internal::SharedMacroAssemblerBase::AvxHelper< Dst, Arg, Args >::emit(), v8::internal::Assembler::emit_aligned_cmp(), v8::internal::Assembler::emit_aligned_test(), v8::internal::wasm::LiftoffAssembler::emit_f32_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f32_floor(), v8::internal::wasm::LiftoffAssembler::emit_f32_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f32_trunc(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_floor(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f32x4_trunc(), v8::internal::wasm::LiftoffAssembler::emit_f64_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f64_floor(), v8::internal::wasm::LiftoffAssembler::emit_f64_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f64_trunc(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_ceil(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_floor(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_nearest_int(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_trunc(), v8::internal::wasm::LiftoffAssembler::emit_i32_divs(), v8::internal::wasm::LiftoffAssembler::emit_i32_divu(), v8::internal::wasm::LiftoffAssembler::emit_i32_rems(), v8::internal::wasm::LiftoffAssembler::emit_i32_remu(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI8x16Swizzle(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitRelaxedLaneSelect(), v8::internal::wasm::liftoff::EmitSatTruncateFloatToInt(), v8::internal::wasm::liftoff::EmitSatTruncateFloatToUInt64(), v8::internal::wasm::liftoff::EmitSimdCommutativeBinOp(), v8::internal::wasm::liftoff::EmitSimdNonCommutativeBinOp(), v8::internal::wasm::liftoff::EmitSimdShiftOp(), v8::internal::wasm::liftoff::EmitSimdShiftOpImm(), v8::internal::wasm::liftoff::EmitTruncateFloatToInt(), v8::internal::MacroAssembler::ExtractBitRange(), v8::internal::wasm::F16x8BinOpViaF32(), v8::internal::wasm::F16x8CmpOpViaF32(), v8::internal::SharedMacroAssemblerBase::F32x4Max(), v8::internal::SharedMacroAssemblerBase::F32x4Min(), v8::internal::SharedMacroAssemblerBase::F32x4Splat(), v8::internal::SharedMacroAssembler< Impl >::F64x2ConvertLowI32x4U(), v8::internal::SharedMacroAssemblerBase::F64x2ExtractLane(), v8::internal::SharedMacroAssemblerBase::F64x2Max(), v8::internal::SharedMacroAssemblerBase::F64x2Min(), v8::internal::SharedMacroAssemblerBase::F64x2ReplaceLane(), v8::internal::SharedMacroAssembler< Impl >::FloatUnop(), v8::internal::anonymous_namespace{register-configuration.cc}::get_allocatable_double_codes(), v8::internal::anonymous_namespace{register-configuration.cc}::get_num_allocatable_double_registers(), v8::internal::anonymous_namespace{simd.cc}::get_vectorization_kind(), v8::internal::SharedMacroAssemblerBase::I16x8DotI8x16I7x16S(), v8::internal::SharedMacroAssembler< Impl >::I16x8ExtAddPairwiseI8x16S(), v8::internal::SharedMacroAssembler< Impl >::I16x8ExtAddPairwiseI8x16U(), v8::internal::SharedMacroAssemblerBase::I16x8ExtMulHighS(), v8::internal::SharedMacroAssemblerBase::I16x8ExtMulHighU(), v8::internal::SharedMacroAssemblerBase::I16x8Q15MulRSatS(), v8::internal::SharedMacroAssemblerBase::I16x8SConvertI8x16High(), v8::internal::SharedMacroAssemblerBase::I16x8Splat(), v8::internal::SharedMacroAssemblerBase::I16x8SplatPreAvx2(), v8::internal::SharedMacroAssemblerBase::I16x8UConvertI8x16High(), v8::internal::SharedMacroAssemblerBase::I32x4DotI8x16I7x16AddS(), v8::internal::SharedMacroAssembler< Impl >::I32x4ExtAddPairwiseI16x8S(), v8::internal::SharedMacroAssemblerBase::I32x4ExtAddPairwiseI16x8U(), v8::internal::SharedMacroAssemblerBase::I32x4ExtMul(), v8::internal::wasm::liftoff::I32x4ExtMulHelper(), v8::internal::SharedMacroAssembler< Impl >::I32x4SConvertF32x4(), v8::internal::SharedMacroAssemblerBase::I32x4SConvertI16x8High(), v8::internal::SharedMacroAssembler< Impl >::I32x4TruncF32x4U(), v8::internal::SharedMacroAssembler< Impl >::I32x4TruncSatF64x2SZero(), v8::internal::SharedMacroAssembler< Impl >::I32x4TruncSatF64x2UZero(), v8::internal::SharedMacroAssemblerBase::I32x4UConvertI16x8High(), v8::internal::SharedMacroAssemblerBase::I64x2Abs(), v8::internal::SharedMacroAssemblerBase::I64x2ExtMul(), v8::internal::SharedMacroAssemblerBase::I64x2GeS(), v8::internal::SharedMacroAssemblerBase::I64x2GtS(), v8::internal::SharedMacroAssemblerBase::I64x2Mul(), v8::internal::SharedMacroAssemblerBase::I64x2Neg(), v8::internal::SharedMacroAssemblerBase::I64x2SConvertI32x4High(), v8::internal::SharedMacroAssemblerBase::I64x2ShrS(), v8::internal::SharedMacroAssemblerBase::I64x2UConvertI32x4High(), v8::internal::SharedMacroAssembler< Impl >::I8x16Popcnt(), v8::internal::SharedMacroAssemblerBase::I8x16Shl(), v8::internal::SharedMacroAssemblerBase::I8x16ShrU(), v8::internal::SharedMacroAssemblerBase::I8x16Splat(), v8::internal::SharedMacroAssemblerBase::I8x16SplatPreAvx2(), v8::internal::SharedMacroAssembler< Impl >::I8x16Swizzle(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), v8::internal::MacroAssembler::LoadZeroIfConditionNotZero(), v8::internal::MacroAssembler::LoadZeroIfConditionZero(), v8::internal::MacroAssembler::MoveIfZero(), v8::internal::SharedMacroAssemblerBase::Movhps(), v8::internal::SharedMacroAssemblerBase::Movlps(), v8::internal::MacroAssembler::MulS32(), v8::internal::MacroAssembler::MulS64(), v8::internal::SharedMacroAssemblerBase::Pblendvb(), v8::internal::SharedMacroAssembler< Impl >::Pextrd(), v8::internal::SharedMacroAssembler< Impl >::Pinsrd(), v8::internal::SharedMacroAssemblerBase::PinsrHelper(), v8::internal::MacroAssembler::Popcnt32(), v8::internal::wasm::LiftoffAssembler::PrepareStackFrame(), PrintFeatures(), v8::internal::SharedMacroAssemblerBase::Pshufb(), v8::internal::SharedMacroAssemblerBase::S128Load16Splat(), v8::internal::SharedMacroAssemblerBase::S128Load32Splat(), v8::internal::SharedMacroAssemblerBase::S128Load8Splat(), v8::internal::SharedMacroAssemblerBase::S128Select(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::Assembler::set_target_address_at(), v8::internal::compiler::ShouldAlignForJCCErratum(), v8::internal::SharedMacroAssemblerBase::Shufps(), v8::internal::MacroAssembler::SignExtendByte(), v8::internal::MacroAssembler::SignExtendShort(), v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags(), v8::internal::DoubleRegister::SupportedRegisterCount(), SupportsWasmSimd128(), v8::internal::Assembler::target_address_at(), v8::internal::compiler::TryMatchInt32MulWithOverflow(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), and v8::internal::compiler::VisitStoreCommon().
operator=()
CpuFeatures& v8::internal::CpuFeatures::operator= (const CpuFeatures &) [delete]
PrintFeatures()
void v8::internal::CpuFeatures::PrintFeatures () [static]
Definition at line 131 of file assembler-riscv.cc.
                                {
  printf("supports_wasm_simd_128=%d\n", CpuFeatures::SupportsWasmSimd128());
  printf("RISC-V Extension zba=%d,zbb=%d,zbs=%d,ZICOND=%d\n",
         CpuFeatures::IsSupported(ZBA), CpuFeatures::IsSupported(ZBB),
         CpuFeatures::IsSupported(ZBS), CpuFeatures::IsSupported(ZICOND));
}
References IsSupported(), and SupportsWasmSimd128().
Referenced by v8::internal::FlagList::PrintHelp().
PrintTarget()
void v8::internal::CpuFeatures::PrintTarget () [static]
Definition at line 130 of file assembler-riscv.cc.
{}
Referenced by v8::internal::FlagList::PrintHelp().
Probe()
static void v8::internal::CpuFeatures::Probe (bool cross_compile) [inline], [static]
Definition at line 119 of file cpu-features.h.
                                        {
    static_assert(NUMBER_OF_CPU_FEATURES <= kBitsPerInt);
    if (initialized_) return;
    initialized_ = true;
    ProbeImpl(cross_compile);
  }
References v8::internal::kBitsPerInt, and v8::internal::NUMBER_OF_CPU_FEATURES.
Referenced by v8::internal::V8::Initialize(), main(), and v8::internal::FlagList::PrintHelp().
ProbeImpl()
void v8::internal::CpuFeatures::ProbeImpl (bool cross_compile) [static], [private]
Definition at line 96 of file assembler-riscv.cc.
                                              {
  supported_ |= CpuFeaturesImpliedByCompiler();
#ifdef _RISCV_TARGET_SIMULATOR
  supported_ |= SimulatorFeatures();
#endif // _RISCV_TARGET_SIMULATOR
  // Only use statically determined features for cross compile (snapshot).
  if (cross_compile) return;
  // Probe for additional features at runtime.
#ifndef USE_SIMULATOR
  base::CPU cpu;
  if (cpu.has_fpu()) supported_ |= 1u << FPU;
  if (cpu.has_rvv()) supported_ |= 1u << RISCV_SIMD;
  if (cpu.has_zba()) supported_ |= 1u << ZBA;
  if (cpu.has_zbb()) supported_ |= 1u << ZBB;
  if (cpu.has_zbs()) supported_ |= 1u << ZBS;
  if (v8_flags.riscv_b_extension) {
    supported_ |= (1u << ZBA) | (1u << ZBB) | (1u << ZBS);
  }
#ifdef V8_COMPRESS_POINTERS
  if (cpu.riscv_mmu() == base::CPU::RV_MMU_MODE::kRiscvSV57) {
    FATAL("SV57 is not supported");
    UNIMPLEMENTED();
  }
#endif // V8_COMPRESS_POINTERS
#endif // USE_SIMULATOR
  // Set a static value on whether SIMD is supported.
  // This variable is only used for certain archs to query SupportWasmSimd128()
  // at runtime in builtins using an extern ref. Other callers should use
  // CpuFeatures::SupportWasmSimd128().
  CpuFeatures::supports_wasm_simd_128_ = CpuFeatures::SupportsWasmSimd128();
}
References v8::internal::CpuFeaturesImpliedByCompiler(), FATAL, v8::base::CPU::has_fpu(), v8::base::CPU::has_rvv(), v8::base::CPU::has_zba(), v8::base::CPU::has_zbb(), v8::base::CPU::has_zbs(), v8::base::CPU::kRiscvSV57, v8::base::CPU::riscv_mmu(), supported_, supports_wasm_simd_128_, SupportsWasmSimd128(), v8::internal::UNIMPLEMENTED(), and v8::internal::v8_flags.
SetSupported()
static void v8::internal::CpuFeatures::SetSupported (CpuFeature f) [inline], [static]
Definition at line 135 of file cpu-features.h.
{ supported_ |= 1u << f; }
SetUnsupported()
static void v8::internal::CpuFeatures::SetUnsupported (CpuFeature f) [inline], [static]
Definition at line 136 of file cpu-features.h.
{ supported_ &= ~(1u << f); }
SupportedFeatures()
static unsigned v8::internal::CpuFeatures::SupportedFeatures () [inline], [static]
Definition at line 126 of file cpu-features.h.
                                      {
    Probe(false);
    return supported_;
  }
Referenced by v8::internal::compiler::InstructionSelector::SupportedFeatures(), and v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::WriteHeader().
SupportsOptimizer()
bool v8::internal::CpuFeatures::SupportsOptimizer () [inline], [static]
Definition at line 52 of file assembler-arm-inl.h.
{ return true; }
Referenced by v8::internal::Isolate::use_optimizer().
SupportsWasmSimd128()
bool v8::internal::CpuFeatures::SupportsWasmSimd128 () [static]
Definition at line 94 of file assembler-riscv.cc.
{ return IsSupported(RISCV_SIMD); }
References IsSupported().
Referenced by v8::internal::wasm::CheckHardwareSupportsSimd(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineMemCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MaybeBailoutForUnsupportedType(), PrintFeatures(), ProbeImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::S128Const(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SetDefaultValue(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Simd8x16ShuffleOp(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdLaneOp(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
Friends And Related Function Documentation
ExternalReference
friend class ExternalReference [friend]
Definition at line 157 of file cpu-features.h.
FlushInstructionCache
void V8_EXPORT_PRIVATE FlushInstructionCache (void * , size_t) [friend]
Definition at line 14 of file flush-instruction-cache.cc.
                                                     {
  if (size == 0) return;
  if (v8_flags.jitless) return;
  TRACE_EVENT2(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "FlushInstructionCache",
               "start", start, "size", size);
#if defined(USE_SIMULATOR)
  base::MutexGuard lock_guard(Simulator::i_cache_mutex());
  Simulator::FlushICache(Simulator::i_cache(), start, size);
#else
  CpuFeatures::FlushICache(start, size);
#endif // USE_SIMULATOR
}
Member Data Documentation
dcache_line_size_
unsigned v8::internal::CpuFeatures::dcache_line_size_ = 0 [static], [private]
Definition at line 166 of file cpu-features.h.
icache_line_size_
unsigned v8::internal::CpuFeatures::icache_line_size_ = 0 [static], [private]
Definition at line 165 of file cpu-features.h.
initialized_
bool v8::internal::CpuFeatures::initialized_ = false [static], [private]
Definition at line 167 of file cpu-features.h.
supported_
unsigned v8::internal::CpuFeatures::supported_ = 0 [static], [private]
Definition at line 164 of file cpu-features.h.
Referenced by ProbeImpl().
supports_cetss_
bool v8::internal::CpuFeatures::supports_cetss_ = false [static], [private]
Definition at line 172 of file cpu-features.h.
supports_wasm_simd_128_
bool v8::internal::CpuFeatures::supports_wasm_simd_128_ = false [static], [private]
Definition at line 171 of file cpu-features.h.
Referenced by ProbeImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/cpu-features.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h
/mnt/V8SourceCode/src/codegen/assembler.cc
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32-inl.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64-inl.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64-inl.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc-inl.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv-inl.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.cc
/mnt/V8SourceCode/src/codegen/riscv/cpu-riscv.cc
/mnt/V8SourceCode/src/codegen/s390/assembler-s390-inl.h
/mnt/V8SourceCode/src/codegen/x64/assembler-x64-inl.h