v8::internal::compiler::OperationTyper Class Reference
#include <operation-typer.h>
Public Types
enum ComparisonOutcomeFlags { kComparisonTrue = 1
, kComparisonFalse = 2
, kComparisonUndefined = 4
 }
Public Member Functions
OperationTyper (JSHeapBroker *broker, Zone *zone)
Type Merge (Type left, Type right)
Type ToPrimitive (Type type)
Type ToNumber (Type type)
Type ToNumberConvertBigInt (Type type)
Type ToBigInt (Type type)
Type ToBigIntConvertNumber (Type type)
Type ToNumeric (Type type)
Type ToBoolean (Type type)
Type WeakenRange (Type current_range, Type previous_range)
Type ChangeUint32ToUint64 (Type input)
Type SameValue (Type lhs, Type rhs)
Type SameValueNumbersOnly (Type lhs, Type rhs)
Type StrictEqual (Type lhs, Type rhs)
Type CheckBounds (Type index, Type length)
Type CheckFloat64Hole (Type type)
Type CheckNumber (Type type)
Type CheckNumberOrUndefined (Type type)
Type CheckNumberFitsInt32 (Type type)
Type ConvertTaggedHoleToUndefined (Type type)
Type TypeTypeGuard (const Operator *sigma_op, Type input)
Type singleton_false () const
Type singleton_true () const
Private Types
using ComparisonOutcome = base::Flags< ComparisonOutcomeFlags >
Private Member Functions
ComparisonOutcome Invert (ComparisonOutcome)
Type Invert (Type)
Type FalsifyUndefined (ComparisonOutcome)
Type Rangify (Type)
Type AddRanger (double lhs_min, double lhs_max, double rhs_min, double rhs_max)
Type SubtractRanger (double lhs_min, double lhs_max, double rhs_min, double rhs_max)
Type MultiplyRanger (double lhs_min, double lhs_max, double rhs_min, double rhs_max)
Zone * zone () const
Private Attributes
Zone *const zone_
TypeCache const * cache_
Type infinity_
Type minus_infinity_
Type singleton_NaN_string_
Type singleton_zero_string_
Type singleton_false_
Type singleton_true_
Type signed32ish_
Type unsigned32ish_
Type singleton_empty_string_
Type truish_
Type falsish_
Detailed Description
Definition at line 49 of file operation-typer.h.
Member Typedef Documentation
ComparisonOutcome
using v8::internal::compiler::OperationTyper::ComparisonOutcome = base::Flags<ComparisonOutcomeFlags> [private]
Definition at line 111 of file operation-typer.h.
Member Enumeration Documentation
ComparisonOutcomeFlags
enum v8::internal::compiler::OperationTyper::ComparisonOutcomeFlags
Enumerator
kComparisonTrue
kComparisonFalse
kComparisonUndefined
Definition at line 101 of file operation-typer.h.
                              {
    kComparisonTrue = 1,
    kComparisonFalse = 2,
    kComparisonUndefined = 4
  };
Constructor & Destructor Documentation
OperationTyper()
v8::internal::compiler::OperationTyper::OperationTyper (JSHeapBroker * broker, Zone * zone)
Definition at line 17 of file operation-typer.cc.
    : zone_(zone), cache_(TypeCache::Get()) {
  infinity_ = Type::Constant(V8_INFINITY, zone);
  minus_infinity_ = Type::Constant(-V8_INFINITY, zone);
  Type truncating_to_zero = Type::MinusZeroOrNaN();
  DCHECK(!truncating_to_zero.Maybe(Type::Integral32()));
  singleton_empty_string_ =
      Type::Constant(broker, broker->empty_string(), zone);
  singleton_NaN_string_ = Type::Constant(broker, broker->NaN_string(), zone);
  singleton_zero_string_ = Type::Constant(broker, broker->zero_string(), zone);
  singleton_false_ = Type::Constant(broker, broker->false_value(), zone);
  singleton_true_ = Type::Constant(broker, broker->true_value(), zone);
  signed32ish_ = Type::Union(Type::Signed32(), truncating_to_zero, zone);
  unsigned32ish_ = Type::Union(Type::Unsigned32(), truncating_to_zero, zone);
  falsish_ = Type::Union(
      Type::Undetectable(),
      Type::Union(Type::Union(singleton_false_, cache_->kZeroish, zone),
                  singleton_empty_string_, zone),
      zone);
  truish_ = Type::Union(
      singleton_true_,
      Type::Union(Type::DetectableReceiver(), Type::Symbol(), zone), zone);
}
References broker(), cache_, v8::internal::compiler::Type::Constant(), v8::internal::DCHECK(), falsish_, infinity_, v8::internal::compiler::TypeCache::kZeroish, v8::internal::compiler::Type::Maybe(), minus_infinity_, signed32ish_, singleton_empty_string_, singleton_false_, singleton_NaN_string_, singleton_true_, singleton_zero_string_, truish_, v8::internal::compiler::Type::Union(), unsigned32ish_, V8_INFINITY, and zone().
Member Function Documentation
AddRanger()
Type v8::internal::compiler::OperationTyper::AddRanger (double lhs_min, double lhs_max, double rhs_min, double rhs_max) [private]
Definition at line 165 of file operation-typer.cc.
                                               {
  double results[4];
  results[0] = lhs_min + rhs_min;
  results[1] = lhs_min + rhs_max;
  results[2] = lhs_max + rhs_min;
  results[3] = lhs_max + rhs_max;
  // Since none of the inputs can be -0, the result cannot be -0 either.
  // However, it can be nan (the sum of two infinities of opposite sign).
  // On the other hand, if none of the "results" above is nan, then the
  // actual result cannot be nan either.
  int nans = 0;
  for (int i = 0; i < 4; ++i) {
    if (std::isnan(results[i])) ++nans;
  }
  if (nans == 4) return Type::NaN();
  Type type = Type::Range(array_min(results, 4), array_max(results, 4), zone());
  if (nans > 0) type = Type::Union(type, Type::NaN(), zone());
  // Examples:
  // [-inf, -inf] + [+inf, +inf] = NaN
  // [-inf, -inf] + [n, +inf] = [-inf, -inf] \/ NaN
  // [-inf, +inf] + [n, +inf] = [-inf, +inf] \/ NaN
  // [-inf, m] + [n, +inf] = [-inf, +inf] \/ NaN
  return type;
}
References v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_max(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_min(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Type::Range(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and zone().
ChangeUint32ToUint64()
Type v8::internal::compiler::OperationTyper::ChangeUint32ToUint64 (Type input)
Definition at line 1198 of file operation-typer.cc.
                                                    {
  return Type::Machine();
}
CheckBounds()
Type v8::internal::compiler::OperationTyper::CheckBounds (Type index, Type length)
Definition at line 1342 of file operation-typer.cc.
                                                        {
  DCHECK(length.Is(cache_->kPositiveSafeInteger));
  if (length.Is(cache_->kSingletonZero)) return Type::None();
  Type const upper_bound = Type::Range(0.0, length.Max() - 1, zone());
  if (index.Maybe(Type::String())) return upper_bound;
  if (index.Maybe(Type::MinusZero())) {
    index = Type::Union(index, cache_->kSingletonZero, zone());
  }
  return Type::Intersect(index, upper_bound, zone());
}
References cache_, v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::Type::Intersect(), v8::internal::compiler::TypeCache::kPositiveSafeInteger, v8::internal::compiler::TypeCache::kSingletonZero, v8::internal::length, v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Type::Range(), v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
CheckFloat64Hole()
Type v8::internal::compiler::OperationTyper::CheckFloat64Hole (Type type)
Definition at line 1353 of file operation-typer.cc.
                                               {
  if (type.Maybe(Type::Hole())) {
    // Turn a "hole" into undefined.
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    type = Type::Intersect(type, Type::NumberOrUndefined(), zone());
#else
    type = Type::Intersect(type, Type::Number(), zone());
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    type = Type::Union(type, Type::Undefined(), zone());
  }
  return type;
}
References v8::internal::compiler::Hole, v8::internal::compiler::Type::Intersect(), v8::internal::tracing::type, v8::internal::compiler::Undefined, v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
CheckNumber()
Type v8::internal::compiler::OperationTyper::CheckNumber (Type type)
Definition at line 1366 of file operation-typer.cc.
                                          {
  return Type::Intersect(type, Type::Number(), zone());
}
References v8::internal::compiler::Type::Intersect(), v8::internal::tracing::type, and zone().
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
CheckNumberFitsInt32()
Type v8::internal::compiler::OperationTyper::CheckNumberFitsInt32 (Type type)
Definition at line 1374 of file operation-typer.cc.
                                                   {
  return Type::Intersect(type, Type::Signed32(), zone());
}
References v8::internal::compiler::Type::Intersect(), v8::internal::tracing::type, and zone().
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
CheckNumberOrUndefined()
Type v8::internal::compiler::OperationTyper::CheckNumberOrUndefined (Type type)
Definition at line 1370 of file operation-typer.cc.
                                                     {
  return Type::Intersect(type, Type::NumberOrUndefined(), zone());
}
References v8::internal::compiler::Type::Intersect(), v8::internal::tracing::type, and zone().
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
ConvertTaggedHoleToUndefined()
Type v8::internal::compiler::OperationTyper::ConvertTaggedHoleToUndefined (Type type)
Definition at line 1382 of file operation-typer.cc.
                                                            {
  if (input.Maybe(Type::Hole())) {
    // Turn a "hole" into undefined.
    Type type = Type::Intersect(input, Type::NonInternal(), zone());
    return Type::Union(type, Type::Undefined(), zone());
  }
  return input;
}
References v8::internal::compiler::Hole, v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::Maybe(), v8::internal::tracing::type, v8::internal::compiler::Undefined, v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::UpdateFeedbackType().
FalsifyUndefined()
Type v8::internal::compiler::OperationTyper::FalsifyUndefined (ComparisonOutcome outcome) [private]
Definition at line 1264 of file operation-typer.cc.
                                                               {
  if ((outcome & kComparisonFalse) != 0 ||
      (outcome & kComparisonUndefined) != 0) {
    return (outcome & kComparisonTrue) != 0 ? Type::Boolean()
                                            : singleton_false();
  }
  // Type should be non empty, so we know it should be true.
  DCHECK_NE(0, outcome & kComparisonTrue);
  return singleton_true();
}
References DCHECK_NE, kComparisonFalse, kComparisonTrue, kComparisonUndefined, singleton_false(), and singleton_true().
Invert() [1/2]
OperationTyper::ComparisonOutcome v8::internal::compiler::OperationTyper::Invert (ComparisonOutcome outcome) [private]
Definition at line 1255 of file operation-typer.cc.
                               {
  ComparisonOutcome result(0);
  if ((outcome & kComparisonUndefined) != 0) result |= kComparisonUndefined;
  if ((outcome & kComparisonTrue) != 0) result |= kComparisonFalse;
  if ((outcome & kComparisonFalse) != 0) result |= kComparisonTrue;
  return result;
}
References kComparisonFalse, kComparisonTrue, kComparisonUndefined, and v8::base::internal::result.
Invert() [2/2]
Type v8::internal::compiler::OperationTyper::Invert (Type type) [private]
Definition at line 1247 of file operation-typer.cc.
                                     {
  DCHECK(type.Is(Type::Boolean()));
  CHECK(!type.IsNone());
  if (type.Is(singleton_false())) return singleton_true();
  if (type.Is(singleton_true())) return singleton_false();
  return type;
}
References CHECK, v8::internal::DCHECK(), singleton_false(), singleton_true(), and v8::internal::tracing::type.
Merge()
Type v8::internal::compiler::OperationTyper::Merge (Type left, Type right)
Definition at line 43 of file operation-typer.cc.
                                                {
  return Type::Union(left, right, zone());
}
References v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::RepresentationSelector::TypePhi(), and v8::internal::compiler::RepresentationSelector::TypeSelect().
MultiplyRanger()
Type v8::internal::compiler::OperationTyper::MultiplyRanger (double lhs_min, double lhs_max, double rhs_min, double rhs_max) [private]
Definition at line 216 of file operation-typer.cc.
                                                                    {
  double results[4];
  results[0] = lhs_min * rhs_min;
  results[1] = lhs_min * rhs_max;
  results[2] = lhs_max * rhs_min;
  results[3] = lhs_max * rhs_max;
  // If the result may be nan, we give up on calculating a precise type,
  // because the discontinuity makes it too complicated. Note that even if
  // none of the "results" above is nan, the actual result may still be, so we
  // have to do a different check:
  for (int i = 0; i < 4; ++i) {
    if (std::isnan(results[i])) {
      return cache_->kIntegerOrMinusZeroOrNaN;
    }
  }
  double min = array_min(results, 4);
  double max = array_max(results, 4);
  Type type = Type::Range(min, max, zone());
  if (min <= 0.0 && 0.0 <= max && (lhs_min < 0.0 || rhs_min < 0.0)) {
    type = Type::Union(type, Type::MinusZero(), zone());
  }
  // 0 * V8_INFINITY is NaN, regardless of sign
  if (((lhs_min == -V8_INFINITY || lhs_max == V8_INFINITY) &&
       (rhs_min <= 0.0 && 0.0 <= rhs_max)) ||
      ((rhs_min == -V8_INFINITY || rhs_max == V8_INFINITY) &&
       (lhs_min <= 0.0 && 0.0 <= lhs_max))) {
    type = Type::Union(type, Type::NaN(), zone());
  }
  return type;
}
References v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_max(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_min(), cache_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::TypeCache::kIntegerOrMinusZeroOrNaN, v8::internal::compiler::Type::Range(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), V8_INFINITY, and zone().
Rangify()
Type v8::internal::compiler::OperationTyper::Rangify (Type type) [private]
Definition at line 123 of file operation-typer.cc.
                                      {
  if (type.IsRange()) return type; // Shortcut.
  if (!type.Is(cache_->kInteger)) {
    return type; // Give up on non-integer types.
  }
  return Type::Range(type.Min(), type.Max(), zone());
}
References cache_, v8::internal::compiler::TypeCache::kInteger, v8::internal::compiler::Type::Range(), v8::internal::tracing::type, and zone().
SameValue()
Type v8::internal::compiler::OperationTyper::SameValue (Type lhs, Type rhs)
Definition at line 1291 of file operation-typer.cc.
                                                 {
  if (lhs.IsNone() || rhs.IsNone()) return Type::None();
  if (!JSType(lhs).Maybe(JSType(rhs))) return singleton_false();
  if (lhs.Is(Type::NaN())) {
    if (rhs.Is(Type::NaN())) return singleton_true();
    if (!rhs.Maybe(Type::NaN())) return singleton_false();
  } else if (rhs.Is(Type::NaN())) {
    if (!lhs.Maybe(Type::NaN())) return singleton_false();
  }
  if (lhs.Is(Type::MinusZero())) {
    if (rhs.Is(Type::MinusZero())) return singleton_true();
    if (!rhs.Maybe(Type::MinusZero())) return singleton_false();
  } else if (rhs.Is(Type::MinusZero())) {
    if (!lhs.Maybe(Type::MinusZero())) return singleton_false();
  }
  if (lhs.Is(Type::OrderedNumber()) && rhs.Is(Type::OrderedNumber()) &&
      (lhs.Max() < rhs.Min() || lhs.Min() > rhs.Max())) {
    return singleton_false();
  }
  return Type::Boolean();
}
References v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::JSType(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Type::Min(), v8::internal::compiler::turboshaft::Type::None(), singleton_false(), and singleton_true().
Referenced by SameValueNumbersOnly(), and v8::internal::compiler::Typer::Visitor::SameValueTyper().
SameValueNumbersOnly()
Type v8::internal::compiler::OperationTyper::SameValueNumbersOnly (Type lhs, Type rhs)
Definition at line 1313 of file operation-typer.cc.
                                                            {
  // SameValue and SamevalueNumbersOnly only differ in treatment of
  // strings and biginits. Since the SameValue typer does not do anything
  // special about strings or bigints, we can just use it here.
  return SameValue(lhs, rhs);
}
References SameValue().
Referenced by v8::internal::compiler::Typer::Visitor::SameValueNumbersOnlyTyper().
singleton_false()
Type v8::internal::compiler::OperationTyper::singleton_false () const [inline]
Definition at line 107 of file operation-typer.h.
{ return singleton_false_; }
Referenced by FalsifyUndefined(), Invert(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), SameValue(), StrictEqual(), and v8::internal::compiler::Typer::Typer().
singleton_true()
Type v8::internal::compiler::OperationTyper::singleton_true () const [inline]
Definition at line 108 of file operation-typer.h.
{ return singleton_true_; }
Referenced by FalsifyUndefined(), Invert(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), SameValue(), StrictEqual(), and v8::internal::compiler::Typer::Typer().
StrictEqual()
Type v8::internal::compiler::OperationTyper::StrictEqual (Type lhs, Type rhs)
Definition at line 1320 of file operation-typer.cc.
                                                   {
  CHECK(!lhs.IsNone());
  CHECK(!rhs.IsNone());
  if (!JSType(lhs).Maybe(JSType(rhs))) return singleton_false();
  if (lhs.Is(Type::NaN()) || rhs.Is(Type::NaN())) return singleton_false();
  if (lhs.Is(Type::Number()) && rhs.Is(Type::Number()) &&
      (lhs.Max() < rhs.Min() || lhs.Min() > rhs.Max())) {
    return singleton_false();
  }
  if (lhs.IsSingleton() && rhs.Is(lhs)) {
    // Types are equal and are inhabited only by a single semantic value,
    // which is not nan due to the earlier check.
    DCHECK(lhs.Is(rhs));
    return singleton_true();
  }
  if ((lhs.Is(Type::Unique()) || rhs.Is(Type::Unique())) && !lhs.Maybe(rhs)) {
    // One of the inputs has a canonical representation but types don't overlap.
    return singleton_false();
  }
  return Type::Boolean();
}
References CHECK, v8::internal::DCHECK(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::Type::IsSingleton(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::JSType(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Type::Min(), singleton_false(), and singleton_true().
SubtractRanger()
Type v8::internal::compiler::OperationTyper::SubtractRanger (double lhs_min, double lhs_max, double rhs_min, double rhs_max) [private]
Definition at line 191 of file operation-typer.cc.
                                                                    {
  double results[4];
  results[0] = lhs_min - rhs_min;
  results[1] = lhs_min - rhs_max;
  results[2] = lhs_max - rhs_min;
  results[3] = lhs_max - rhs_max;
  // Since none of the inputs can be -0, the result cannot be -0.
  // However, it can be nan (the subtraction of two infinities of same sign).
  // On the other hand, if none of the "results" above is nan, then the actual
  // result cannot be nan either.
  int nans = 0;
  for (int i = 0; i < 4; ++i) {
    if (std::isnan(results[i])) ++nans;
  }
  if (nans == 4) return Type::NaN(); // [inf..inf] - [inf..inf] (all same sign)
  Type type = Type::Range(array_min(results, 4), array_max(results, 4), zone());
  return nans == 0 ? type : Type::Union(type, Type::NaN(), zone());
  // Examples:
  // [-inf, +inf] - [-inf, +inf] = [-inf, +inf] \/ NaN
  // [-inf, -inf] - [-inf, -inf] = NaN
  // [-inf, -inf] - [n, +inf] = [-inf, -inf] \/ NaN
  // [m, +inf] - [-inf, n] = [-inf, +inf] \/ NaN
}
References v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_max(), v8::internal::compiler::anonymous_namespace{operation-typer.cc}::array_min(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Type::Range(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and zone().
ToBigInt()
Type v8::internal::compiler::OperationTyper::ToBigInt (Type type)
Definition at line 308 of file operation-typer.cc.
                                       {
  if (type.Is(Type::BigInt())) {
    return type;
  }
  return Type::BigInt();
}
References v8::internal::tracing::type.
Referenced by v8::internal::compiler::Typer::Visitor::ToBigInt(), and ToBigIntConvertNumber().
ToBigIntConvertNumber()
Type v8::internal::compiler::OperationTyper::ToBigIntConvertNumber (Type type)
Definition at line 316 of file operation-typer.cc.
                                                    {
  if (type.Is(Type::Unsigned32OrMinusZero())) {
    return Type::UnsignedBigInt63();
  } else if (type.Is(Type::Signed32OrMinusZero())) {
    return Type::SignedBigInt64();
  }
  bool maybe_number =
      type.Maybe(Type::Number()) || type.Maybe(Type::Receiver());
  type = ToBigInt(Type::Intersect(type, Type::NonNumber(), zone()));
  return maybe_number ? Type::Union(type, Type::BigInt(), zone()) : type;
}
References v8::internal::compiler::Type::Intersect(), ToBigInt(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::Typer::Visitor::ToBigIntConvertNumber().
ToBoolean()
Type v8::internal::compiler::OperationTyper::ToBoolean (Type type)
Definition at line 1391 of file operation-typer.cc.
                                        {
  if (type.Is(Type::Boolean())) return type;
  if (type.Is(falsish_)) return singleton_false_;
  if (type.Is(truish_)) return singleton_true_;
  if (type.Is(Type::Number())) {
    return NumberToBoolean(type);
  }
  return Type::Boolean();
}
References falsish_, singleton_false_, singleton_true_, truish_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::Typer::Visitor::ToBoolean(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
ToNumber()
Type v8::internal::compiler::OperationTyper::ToNumber (Type type)
Definition at line 261 of file operation-typer.cc.
                                       {
  if (type.Is(Type::Number())) return type;
  // If {type} includes any receivers, we cannot tell what kind of
  // Number their callbacks might produce. Similarly in the case
  // where {type} includes String, it's not possible at this point
  // to tell which exact numbers are going to be produced.
  if (type.Maybe(Type::StringOrReceiver())) return Type::Number();
  // Both Symbol and BigInt primitives will cause exceptions
  // to be thrown from ToNumber conversions, so they don't
  // contribute to the resulting type anyways.
  type = Type::Intersect(type, Type::PlainPrimitive(), zone());
  // This leaves us with Number\/Oddball, so deal with the individual
  // Oddball primitives below.
  DCHECK(type.Is(Type::NumberOrOddball()));
  if (type.Maybe(Type::Null())) {
    // ToNumber(null) => +0
    type = Type::Union(type, cache_->kSingletonZero, zone());
  }
  if (type.Maybe(Type::Undefined())) {
    // ToNumber(undefined) => NaN
    type = Type::Union(type, Type::NaN(), zone());
  }
  if (type.Maybe(singleton_false_)) {
    // ToNumber(false) => +0
    type = Type::Union(type, cache_->kSingletonZero, zone());
  }
  if (type.Maybe(singleton_true_)) {
    // ToNumber(true) => +1
    type = Type::Union(type, cache_->kSingletonOne, zone());
  }
  return Type::Intersect(type, Type::Number(), zone());
}
References cache_, v8::internal::DCHECK(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::TypeCache::kSingletonOne, v8::internal::compiler::TypeCache::kSingletonZero, v8::internal::compiler::Null, singleton_false_, singleton_true_, v8::internal::tracing::type, v8::internal::compiler::Undefined, v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::Typer::Visitor::ToNumber(), ToNumberConvertBigInt(), ToNumeric(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
ToNumberConvertBigInt()
Type v8::internal::compiler::OperationTyper::ToNumberConvertBigInt (Type type)
Definition at line 297 of file operation-typer.cc.
                                                    {
  // If the {type} includes any receivers, then the callbacks
  // might actually produce BigInt primitive values here.
  bool maybe_bigint =
      type.Maybe(Type::BigInt()) || type.Maybe(Type::Receiver());
  type = ToNumber(Type::Intersect(type, Type::NonBigInt(), zone()));
  // Any BigInt is rounded to an integer Number in the range [-inf, inf].
  return maybe_bigint ? Type::Union(type, cache_->kInteger, zone()) : type;
}
References cache_, v8::internal::compiler::Type::Intersect(), v8::internal::compiler::TypeCache::kInteger, ToNumber(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), and v8::internal::compiler::Typer::Visitor::ToNumberConvertBigInt().
ToNumeric()
Type v8::internal::compiler::OperationTyper::ToNumeric (Type type)
Definition at line 329 of file operation-typer.cc.
                                        {
  // If the {type} includes any receivers, then the callbacks
  // might actually produce BigInt primitive values here.
  if (type.Maybe(Type::Receiver())) {
    type = Type::Union(type, Type::BigInt(), zone());
  }
  return Type::Union(ToNumber(Type::Intersect(type, Type::NonBigInt(), zone())),
                     Type::Intersect(type, Type::BigInt(), zone()), zone());
}
References v8::internal::compiler::Type::Intersect(), ToNumber(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), and zone().
Referenced by v8::internal::compiler::Typer::Visitor::ToNumeric().
ToPrimitive()
Type v8::internal::compiler::OperationTyper::ToPrimitive (Type type)
Definition at line 1240 of file operation-typer.cc.
                                          {
  if (type.Is(Type::Primitive())) {
    return type;
  }
  return Type::Primitive();
}
References v8::internal::tracing::type.
TypeTypeGuard()
Type v8::internal::compiler::OperationTyper::TypeTypeGuard (const Operator * sigma_op, Type input)
Definition at line 1378 of file operation-typer.cc.
                                                                       {
  return Type::Intersect(input, TypeGuardTypeOf(sigma_op), zone());
}
References v8::internal::compiler::Type::Intersect(), v8::internal::compiler::TypeGuardTypeOf(), and zone().
Referenced by v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
WeakenRange()
Type v8::internal::compiler::OperationTyper::WeakenRange (Type current_range, Type previous_range)
Definition at line 47 of file operation-typer.cc.
                                                                        {
  static const double kWeakenMinLimits[] = {0.0,
                                            -1073741824.0,
                                            -2147483648.0,
                                            -4294967296.0,
                                            -8589934592.0,
                                            -17179869184.0,
                                            -34359738368.0,
                                            -68719476736.0,
                                            -137438953472.0,
                                            -274877906944.0,
                                            -549755813888.0,
                                            -1099511627776.0,
                                            -2199023255552.0,
                                            -4398046511104.0,
                                            -8796093022208.0,
                                            -17592186044416.0,
                                            -35184372088832.0,
                                            -70368744177664.0,
                                            -140737488355328.0,
                                            -281474976710656.0,
                                            -562949953421312.0};
  static const double kWeakenMaxLimits[] = {0.0,
                                            1073741823.0,
                                            2147483647.0,
                                            4294967295.0,
                                            8589934591.0,
                                            17179869183.0,
                                            34359738367.0,
                                            68719476735.0,
                                            137438953471.0,
                                            274877906943.0,
                                            549755813887.0,
                                            1099511627775.0,
                                            2199023255551.0,
                                            4398046511103.0,
                                            8796093022207.0,
                                            17592186044415.0,
                                            35184372088831.0,
                                            70368744177663.0,
                                            140737488355327.0,
                                            281474976710655.0,
                                            562949953421311.0};
  static_assert(arraysize(kWeakenMinLimits) == arraysize(kWeakenMaxLimits));
  double current_min = current_range.Min();
  double new_min = current_min;
  // Find the closest lower entry in the list of allowed
  // minima (or negative infinity if there is no such entry).
  if (current_min != previous_range.Min()) {
    new_min = -V8_INFINITY;
    for (double const min : kWeakenMinLimits) {
      if (min <= current_min) {
        new_min = min;
        break;
      }
    }
  }
  double current_max = current_range.Max();
  double new_max = current_max;
  // Find the closest greater entry in the list of allowed
  // maxima (or infinity if there is no such entry).
  if (current_max != previous_range.Max()) {
    new_max = V8_INFINITY;
    for (double const max : kWeakenMaxLimits) {
      if (max >= current_max) {
        new_max = max;
        break;
      }
    }
  }
  return Type::Range(new_min, new_max, zone());
}
References arraysize, v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), v8::internal::compiler::Type::Range(), V8_INFINITY, and zone().
Referenced by v8::internal::compiler::RepresentationSelector::Weaken().
zone()
Zone* v8::internal::compiler::OperationTyper::zone () const [inline], [private]
Definition at line 125 of file operation-typer.h.
{ return zone_; }
Referenced by AddRanger(), CheckBounds(), CheckFloat64Hole(), CheckNumber(), CheckNumberFitsInt32(), CheckNumberOrUndefined(), ConvertTaggedHoleToUndefined(), Merge(), MultiplyRanger(), OperationTyper(), Rangify(), SubtractRanger(), ToBigIntConvertNumber(), ToNumber(), ToNumberConvertBigInt(), ToNumeric(), TypeTypeGuard(), and WeakenRange().
Member Data Documentation
cache_
TypeCache const* v8::internal::compiler::OperationTyper::cache_ [private]
Definition at line 128 of file operation-typer.h.
Referenced by CheckBounds(), MultiplyRanger(), OperationTyper(), Rangify(), ToNumber(), and ToNumberConvertBigInt().
falsish_
Type v8::internal::compiler::OperationTyper::falsish_ [private]
Definition at line 140 of file operation-typer.h.
Referenced by OperationTyper(), and ToBoolean().
infinity_
Type v8::internal::compiler::OperationTyper::infinity_ [private]
Definition at line 130 of file operation-typer.h.
Referenced by OperationTyper().
minus_infinity_
Type v8::internal::compiler::OperationTyper::minus_infinity_ [private]
Definition at line 131 of file operation-typer.h.
Referenced by OperationTyper().
signed32ish_
Type v8::internal::compiler::OperationTyper::signed32ish_ [private]
Definition at line 136 of file operation-typer.h.
Referenced by OperationTyper().
singleton_empty_string_
Type v8::internal::compiler::OperationTyper::singleton_empty_string_ [private]
Definition at line 138 of file operation-typer.h.
Referenced by OperationTyper().
singleton_false_
Type v8::internal::compiler::OperationTyper::singleton_false_ [private]
Definition at line 134 of file operation-typer.h.
Referenced by OperationTyper(), ToBoolean(), and ToNumber().
singleton_NaN_string_
Type v8::internal::compiler::OperationTyper::singleton_NaN_string_ [private]
Definition at line 132 of file operation-typer.h.
Referenced by OperationTyper().
singleton_true_
Type v8::internal::compiler::OperationTyper::singleton_true_ [private]
Definition at line 135 of file operation-typer.h.
Referenced by OperationTyper(), ToBoolean(), and ToNumber().
singleton_zero_string_
Type v8::internal::compiler::OperationTyper::singleton_zero_string_ [private]
Definition at line 133 of file operation-typer.h.
Referenced by OperationTyper().
truish_
Type v8::internal::compiler::OperationTyper::truish_ [private]
Definition at line 139 of file operation-typer.h.
Referenced by OperationTyper(), and ToBoolean().
unsigned32ish_
Type v8::internal::compiler::OperationTyper::unsigned32ish_ [private]
Definition at line 137 of file operation-typer.h.
Referenced by OperationTyper().
zone_
Zone* const v8::internal::compiler::OperationTyper::zone_ [private]
Definition at line 127 of file operation-typer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/operation-typer.h
/mnt/V8SourceCode/src/compiler/operation-typer.cc