v8::PerIsolateData::ExplicitRealmScope Class Reference
#include <d8.h>
Public Member Functions
ExplicitRealmScope (PerIsolateData *data, int index)
~ExplicitRealmScope ()
Local< Context > context () const
Private Attributes
PerIsolateData * data_
Local< Context > realm_
int index_
int previous_index_
Detailed Description
Definition at line 315 of file d8.h.
Constructor & Destructor Documentation
ExplicitRealmScope()
v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope (PerIsolateData * data, int index) [explicit]
Definition at line 2079 of file d8.cc.
    : data_(data), index_(index) {
  realm_ = Local<Context>::New(data->isolate_, data->realms_[index_]);
  realm_->Enter();
  previous_index_ = data->realm_current_;
  data->realm_current_ = data->realm_switch_ = index_;
}
References v8::Context::Enter(), index_, v8::PerIsolateData::isolate_, v8::Local< T >::New(), previous_index_, realm_, v8::PerIsolateData::realm_current_, v8::PerIsolateData::realm_switch_, and v8::PerIsolateData::realms_.
 ExplicitRealmScope()
v8::PerIsolateData::ExplicitRealmScope::~ExplicitRealmScope ()
Definition at line 2088 of file d8.cc.
                                                      {
  realm_->Exit();
  data_->realm_current_ = data_->realm_switch_ = previous_index_;
}
Member Function Documentation
context()
Local< Context > v8::PerIsolateData::ExplicitRealmScope::context () const
Definition at line 2093 of file d8.cc.
                                                               {
  return realm_;
}
Referenced by v8::Shell::RealmEval().
Member Data Documentation
data_
PerIsolateData* v8::PerIsolateData::ExplicitRealmScope::data_ [private]
Definition at line 323 of file d8.h.
index_
int v8::PerIsolateData::ExplicitRealmScope::index_ [private]
Definition at line 325 of file d8.h.
Referenced by ExplicitRealmScope().
previous_index_
int v8::PerIsolateData::ExplicitRealmScope::previous_index_ [private]
Definition at line 326 of file d8.h.
Referenced by ExplicitRealmScope().
realm_
Local<Context> v8::PerIsolateData::ExplicitRealmScope::realm_ [private]
Definition at line 324 of file d8.h.
Referenced by ExplicitRealmScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc