v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBitwiseBinaryOpAssembler Class Reference
Public Member Functions
InterpreterBitwiseBinaryOpAssembler (CodeAssemblerState *state, Bytecode bytecode, OperandScale operand_scale)
void BitwiseBinaryOpWithFeedback (Operation bitwise_op)
void BitwiseBinaryOpWithSmi (Operation bitwise_op)
Additional Inherited Members
Detailed Description
Definition at line 1127 of file interpreter-generator.cc.
Constructor & Destructor Documentation
InterpreterBitwiseBinaryOpAssembler()
v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBitwiseBinaryOpAssembler::InterpreterBitwiseBinaryOpAssembler (CodeAssemblerState * state, Bytecode bytecode, OperandScale operand_scale) [inline]
Definition at line 1129 of file interpreter-generator.cc.
      : InterpreterAssembler(state, bytecode, operand_scale) {}
Member Function Documentation
BitwiseBinaryOpWithFeedback()
void v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBitwiseBinaryOpAssembler::BitwiseBinaryOpWithFeedback (Operation bitwise_op) [inline]
Definition at line 1134 of file interpreter-generator.cc.
                                                         {
    TNode<Object> left = LoadRegisterAtOperandIndex(0);
    TNode<Object> right = GetAccumulator();
    TNode<Context> context = GetContext();
    TNode<UintPtrT> slot_index = BytecodeOperandIdx(1);
    TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
        LoadFeedbackVectorOrUndefinedIfJitless();
    static constexpr UpdateFeedbackMode mode = DefaultUpdateFeedbackMode();
    BinaryOpAssembler binop_asm(state());
    TNode<Object> result = binop_asm.Generate_BitwiseBinaryOpWithFeedback(
        bitwise_op, left, right, [=] { return context; }, slot_index,
        [=] { return maybe_feedback_vector; }, mode, false);
    SetAccumulator(result);
    Dispatch();
  }
References v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithFeedback(), mode(), and v8::base::internal::result.
BitwiseBinaryOpWithSmi()
void v8::internal::interpreter::anonymous_namespace{interpreter-generator.cc}::InterpreterBitwiseBinaryOpAssembler::BitwiseBinaryOpWithSmi (Operation bitwise_op) [inline]
Definition at line 1152 of file interpreter-generator.cc.
                                                    {
    TNode<Object> left = GetAccumulator();
    TNode<Smi> right = BytecodeOperandImmSmi(0);
    TNode<UintPtrT> slot_index = BytecodeOperandIdx(1);
    TNode<Context> context = GetContext();
    TNode<Union<FeedbackVector, Undefined>> maybe_feedback_vector =
        LoadFeedbackVectorOrUndefinedIfJitless();
    static constexpr UpdateFeedbackMode mode = DefaultUpdateFeedbackMode();
    BinaryOpAssembler binop_asm(state());
    TNode<Object> result = binop_asm.Generate_BitwiseBinaryOpWithFeedback(
        bitwise_op, left, right, [=] { return context; }, slot_index,
        [=] { return maybe_feedback_vector; }, mode, true);
    SetAccumulator(result);
    Dispatch();
  }
References v8::internal::BinaryOpAssembler::Generate_BitwiseBinaryOpWithFeedback(), mode(), and v8::base::internal::result.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/interpreter-generator.cc