v8::internal::wasm::LazilyGeneratedNames Class Reference
#include <wasm-module.h>
Public Member Functions
WireBytesRef LookupFunctionName (ModuleWireBytes wire_bytes, uint32_t function_index)
void AddForTesting (int function_index, WireBytesRef name)
bool Has (uint32_t function_index)
size_t EstimateCurrentMemoryConsumption () const
Private Attributes
base::Mutex mutex_
bool has_functions_ {false}
NameMap function_names_
Detailed Description
Definition at line 379 of file wasm-module.h.
Member Function Documentation
AddForTesting()
void v8::internal::wasm::LazilyGeneratedNames::AddForTesting (int function_index, WireBytesRef name)
Definition at line 153 of file wasm-module.cc.
                                                            {
  base::MutexGuard lock(&mutex_);
  function_names_.Put(function_index, name);
}
References function_names_, mutex_, v8::internal::wasm::name(), and v8::internal::wasm::AdaptiveMap< Value >::Put().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::LazilyGeneratedNames::EstimateCurrentMemoryConsumption () const
Definition at line 762 of file wasm-module.cc.
                                                                    {
  base::MutexGuard lock(&mutex_);
  return function_names_.EstimateCurrentMemoryConsumption();
}
Has()
bool v8::internal::wasm::LazilyGeneratedNames::Has (uint32_t function_index)
Definition at line 97 of file wasm-module.cc.
                                                      {
  DCHECK(has_functions_);
  base::MutexGuard lock(&mutex_);
  return function_names_.Get(function_index) != nullptr;
}
References v8::internal::DCHECK(), function_names_, v8::internal::wasm::AdaptiveMap< Value >::Get(), has_functions_, and mutex_.
Referenced by v8::internal::wasm::NamesProvider::ComputeFunctionNamesFromImportsExports().
LookupFunctionName()
WireBytesRef v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName (ModuleWireBytes wire_bytes, uint32_t function_index)
Definition at line 85 of file wasm-module.cc.
                                                         {
  base::MutexGuard lock(&mutex_);
  if (!has_functions_) {
    has_functions_ = true;
    DecodeFunctionNames(wire_bytes.module_bytes(), function_names_);
  }
  const WireBytesRef* result = function_names_.Get(function_index);
  if (!result) return WireBytesRef();
  return *result;
}
References v8::internal::wasm::DecodeFunctionNames(), function_names_, v8::internal::wasm::AdaptiveMap< Value >::Get(), has_functions_, v8::internal::wasm::ModuleWireBytes::module_bytes(), mutex_, and v8::base::internal::result.
Referenced by v8::internal::wasm::WasmCode::DebugName(), v8::internal::compiler::GetDebugName(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::WasmModuleObject::GetRawFunctionName(), v8::internal::wasm::NamesProvider::PrintFunctionName(), and v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
function_names_
NameMap v8::internal::wasm::LazilyGeneratedNames::function_names_ [private]
Definition at line 394 of file wasm-module.h.
Referenced by AddForTesting(), Has(), and LookupFunctionName().
has_functions_
bool v8::internal::wasm::LazilyGeneratedNames::has_functions_ {false} [private]
Definition at line 393 of file wasm-module.h.
Referenced by Has(), and LookupFunctionName().
mutex_
base::Mutex v8::internal::wasm::LazilyGeneratedNames::mutex_ [mutable], [private]
Definition at line 392 of file wasm-module.h.
Referenced by AddForTesting(), Has(), and LookupFunctionName().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module.h
/mnt/V8SourceCode/src/wasm/wasm-module.cc