v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency Class Reference
Public Member Functions
PretenureModeDependency (AllocationSiteRef site, AllocationType allocation)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const AllocationSiteRef site_
const AllocationType allocation_
Additional Inherited Members
Detailed Description
Definition at line 690 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
PretenureModeDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::PretenureModeDependency (AllocationSiteRef site, AllocationType allocation) [inline]
Definition at line 692 of file compilation-dependencies.cc.
      : CompilationDependency(kPretenureMode),
        site_(site),
        allocation_(allocation) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 712 of file compilation-dependencies.cc.
                                                                {
    const PretenureModeDependency* const zat = that->AsPretenureMode();
    return site_.equals(zat->site_) && allocation_ == zat->allocation_;
  }
References allocation_, and site_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 707 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(site_), allocation_);
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 700 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(site_.object(),
                   DependentCode::kAllocationSiteTenuringChangedGroup);
  }
References broker(), v8::internal::DependentCode::kAllocationSiteTenuringChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 697 of file compilation-dependencies.cc.
                                                    {
    return allocation_ == site_.object()->GetAllocationType();
  }
Member Data Documentation
allocation_
const AllocationType v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::allocation_ [private]
Definition at line 718 of file compilation-dependencies.cc.
Referenced by Equals().
site_
const AllocationSiteRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PretenureModeDependency::site_ [private]
Definition at line 717 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc