cppgc::NameProvider Class Reference
NameProvider allows for providing a human-readable name for garbage-collected objects.
#include <name-provider.h>
Public Member Functions
virtual ~NameProvider ()=default
virtual const char * GetHumanReadableName () const =0
Specifies a name for the garbage-collected object.
Static Public Member Functions
static constexpr bool SupportsCppClassNamesAsObjectNames ()
Indicating whether the build supports extracting C++ names as object names.
Static Public Attributes
static constexpr const char kHiddenName [] = `InternalNode`
Name that is used when hiding internals.
static constexpr const char kNoNameDeducible [] = `<No name>`
Name that is used in case compiler support is missing for composing a name from C++ types.
Detailed Description
NameProvider allows for providing a human-readable name for garbage-collected objects.
There's two cases of names to distinguish: a. Explicitly specified names via using NameProvider. Such names are always preserved in the system. b. Internal names that Oilpan infers from a C++ type on the class hierarchy of the object. This is not necessarily the type of the actually instantiated object.
Depending on the build configuration, Oilpan may hide names, i.e., represent them with kHiddenName, of case b. to avoid exposing internal details.
Definition at line 26 of file name-provider.h.
Constructor & Destructor Documentation
 NameProvider()
virtual cppgc::NameProvider::~NameProvider () [virtual], [default]
Member Function Documentation
GetHumanReadableName()
virtual const char* cppgc::NameProvider::GetHumanReadableName () const [pure virtual]
Specifies a name for the garbage-collected object.
Such names will never be hidden, as they are explicitly specified by the user of this API.
Implementations of this function must not allocate garbage-collected objects or otherwise modify the cppgc heap.
V8 may call this function while generating a heap snapshot or at other times. If V8 is currently generating a heap snapshot (according to HeapProfiler::IsTakingSnapshot), then the returned string must stay alive until the snapshot generation has completed. Otherwise, the returned string must stay alive forever. If you need a place to store a temporary string during snapshot generation, use HeapProfiler::CopyNameForHeapSnapshot.
Returns
a human readable name for the object.
Implemented in v8::Object::Wrappable.
Referenced by cppgc::internal::NameTrait< T >::GetNameFor().
SupportsCppClassNamesAsObjectNames()
static constexpr bool cppgc::NameProvider::SupportsCppClassNamesAsObjectNames () [inline], [static], [constexpr]
Indicating whether the build supports extracting C++ names as object names.
Returns
true if C++ names should be hidden and represented by kHiddenName.
Definition at line 44 of file name-provider.h.
                                                             {
#if CPPGC_SUPPORTS_OBJECT_NAMES
    return true;
#else // !CPPGC_SUPPORTS_OBJECT_NAMES
    return false;
#endif // !CPPGC_SUPPORTS_OBJECT_NAMES
  }
Referenced by cppgc::internal::HeapStatisticsCollector::CollectDetailedStatistics(), and cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::RecordObjectType().
Member Data Documentation
kHiddenName
constexpr const char cppgc::NameProvider::kHiddenName = `InternalNode` [static], [constexpr]
Name that is used when hiding internals.
Definition at line 31 of file name-provider.h.
Referenced by cppgc::internal::anonymous_namespace{gc-info.cc}::GetHiddenName(), and cppgc::internal::NameTrait< T >::GetNameFor().
kNoNameDeducible
constexpr const char cppgc::NameProvider::kNoNameDeducible = `<No name>` [static], [constexpr]
Name that is used in case compiler support is missing for composing a name from C++ types.
Definition at line 37 of file name-provider.h.
Referenced by cppgc::internal::NameTraitBase::GetNameFromTypeSignature().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/name-provider.h
/mnt/V8SourceCode/src/heap/cppgc/name-trait.cc