v8::DataView Class Reference
An instance of DataView constructor (ES6 draft 15.13.7).
#include <v8-array-buffer.h>
Static Public Member Functions
static Local< DataView > New (Local< ArrayBuffer > array_buffer, size_t byte_offset, size_t length)
static Local< DataView > New (Local< SharedArrayBuffer > shared_array_buffer, size_t byte_offset, size_t length)
static DataView * Cast (Value *value)
Private Member Functions
DataView ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of DataView constructor (ES6 draft 15.13.7).
Definition at line 478 of file v8-array-buffer.h.
Constructor & Destructor Documentation
DataView()
v8::DataView::DataView () [private]
Member Function Documentation
Cast()
static DataView* v8::DataView::Cast (Value * value) [inline], [static]
Definition at line 484 of file v8-array-buffer.h.
                                                {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<DataView*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::DataView::CheckCast (Value * obj) [static], [private]
Definition at line 4117 of file api.cc.
                                      {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSDataView(obj) || IsJSRabGsabDataView(obj),
                  "v8::DataView::Cast()", "Value is not a DataView");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New() [1/2]
Local< DataView > v8::DataView::New (Local< ArrayBuffer > array_buffer, size_t byte_offset, size_t length) [static]
Definition at line 9327 of file api.cc.
                                                                      {
  auto buffer = Utils::OpenDirectHandle(*array_buffer);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_DataView_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto obj = i::Cast<i::JSDataView>(
      i_isolate->factory()->NewJSDataViewOrRabGsabDataView(buffer, byte_offset,
                                                           byte_length));
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSDataViewOrRabGsabDataView(), and v8::Utils::OpenDirectHandle().
New() [2/2]
Local< DataView > v8::DataView::New (Local< SharedArrayBuffer > shared_array_buffer, size_t byte_offset, size_t length) [static]
Definition at line 9339 of file api.cc.
                                                                      {
  auto buffer = Utils::OpenDirectHandle(*shared_array_buffer);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_DataView_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto obj = i::Cast<i::JSDataView>(
      i_isolate->factory()->NewJSDataViewOrRabGsabDataView(buffer, byte_offset,
                                                           byte_length));
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSDataViewOrRabGsabDataView(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-array-buffer.h
/mnt/V8SourceCode/src/api/api.cc