v8::internal::SharedMacroAssemblerBase Class Reference
#include <macro-assembler-shared-ia32-x64.h>
Classes
struct AvxHelper
Public Member Functions
void Move (Register dst, uint32_t src)
void Move (Register dst, Register src)
void Add (Register dst, Immediate src)
void And (Register dst, Immediate src)
void Movhps (XMMRegister dst, XMMRegister src1, Operand src2)
void Movlps (XMMRegister dst, XMMRegister src1, Operand src2)
void Blendvps (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister mask)
void Blendvpd (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister mask)
void Pblendvb (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister mask)
template<typename Op >
void Pinsrb (XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t *load_pc_offset=nullptr)
template<typename Op >
void Pinsrw (XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t *load_pc_offset=nullptr)
template<typename Op >
void Pshufb (XMMRegister dst, XMMRegister src, Op mask)
template<typename Op >
void Pshufb (XMMRegister dst, Op mask)
void Shufps (XMMRegister dst, XMMRegister src1, XMMRegister src2, uint8_t imm8)
void F64x2ExtractLane (DoubleRegister dst, XMMRegister src, uint8_t lane)
void F64x2ReplaceLane (XMMRegister dst, XMMRegister src, DoubleRegister rep, uint8_t lane)
void F64x2Min (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
void F64x2Max (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
void F32x4Splat (XMMRegister dst, DoubleRegister src)
void F32x4ExtractLane (FloatRegister dst, XMMRegister src, uint8_t lane)
void F32x4Min (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
void F32x4Max (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
void S128Store32Lane (Operand dst, XMMRegister src, uint8_t laneidx)
void I8x16Splat (XMMRegister dst, Register src, XMMRegister scratch)
void I8x16Splat (XMMRegister dst, Operand src, XMMRegister scratch)
void I8x16Shl (XMMRegister dst, XMMRegister src1, uint8_t src2, Register tmp1, XMMRegister tmp2)
void I8x16Shl (XMMRegister dst, XMMRegister src1, Register src2, Register tmp1, XMMRegister tmp2, XMMRegister tmp3)
void I8x16ShrS (XMMRegister dst, XMMRegister src1, uint8_t src2, XMMRegister tmp)
void I8x16ShrS (XMMRegister dst, XMMRegister src1, Register src2, Register tmp1, XMMRegister tmp2, XMMRegister tmp3)
void I8x16ShrU (XMMRegister dst, XMMRegister src1, uint8_t src2, Register tmp1, XMMRegister tmp2)
void I8x16ShrU (XMMRegister dst, XMMRegister src1, Register src2, Register tmp1, XMMRegister tmp2, XMMRegister tmp3)
void I16x8Splat (XMMRegister dst, Register src)
void I16x8Splat (XMMRegister dst, Operand src)
void I16x8ExtMulLow (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scrat, bool is_signed)
void I16x8ExtMulHighS (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
void I16x8ExtMulHighU (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
void I16x8SConvertI8x16High (XMMRegister dst, XMMRegister src)
void I16x8UConvertI8x16High (XMMRegister dst, XMMRegister src, XMMRegister scratch)
void I16x8Q15MulRSatS (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
void I16x8DotI8x16I7x16S (XMMRegister dst, XMMRegister src1, XMMRegister src2)
void I32x4DotI8x16I7x16AddS (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister scratch, XMMRegister splat_reg)
void I32x4ExtAddPairwiseI16x8U (XMMRegister dst, XMMRegister src, XMMRegister tmp)
void I32x4ExtMul (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch, bool low, bool is_signed)
void I32x4SConvertI16x8High (XMMRegister dst, XMMRegister src)
void I32x4UConvertI16x8High (XMMRegister dst, XMMRegister src, XMMRegister scratch)
void I64x2Neg (XMMRegister dst, XMMRegister src, XMMRegister scratch)
void I64x2Abs (XMMRegister dst, XMMRegister src, XMMRegister scratch)
void I64x2GtS (XMMRegister dst, XMMRegister src0, XMMRegister src1, XMMRegister scratch)
void I64x2GeS (XMMRegister dst, XMMRegister src0, XMMRegister src1, XMMRegister scratch)
void I64x2ShrS (XMMRegister dst, XMMRegister src, uint8_t shift, XMMRegister xmm_tmp)
void I64x2ShrS (XMMRegister dst, XMMRegister src, Register shift, XMMRegister xmm_tmp, XMMRegister xmm_shift, Register tmp_shift)
void I64x2Mul (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister tmp1, XMMRegister tmp2)
void I64x2ExtMul (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch, bool low, bool is_signed)
void I64x2SConvertI32x4High (XMMRegister dst, XMMRegister src)
void I64x2UConvertI32x4High (XMMRegister dst, XMMRegister src, XMMRegister scratch)
void S128Not (XMMRegister dst, XMMRegister src, XMMRegister scratch)
void S128Select (XMMRegister dst, XMMRegister mask, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
void S128Load8Splat (XMMRegister dst, Operand src, XMMRegister scratch)
void S128Load16Splat (XMMRegister dst, Operand src, XMMRegister scratch)
void S128Load32Splat (XMMRegister dst, Operand src)
void S128Store64Lane (Operand dst, XMMRegister src, uint8_t laneidx)
void F64x2Qfma (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
void F64x2Qfms (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
void F32x4Qfma (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
void F32x4Qfms (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
MacroAssemblerBase (Isolate *isolate, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (Isolate *isolate, MaybeAssemblerZone zone, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (Isolate *isolate, const AssemblerOptions &options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (Isolate *isolate, MaybeAssemblerZone zone, AssemblerOptions options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (MaybeAssemblerZone zone, AssemblerOptions options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
Protected Types
template<typename Op >
using AvxFn = void(Assembler::*)(XMMRegister, XMMRegister, Op, uint8_t)
template<typename Op >
using NoAvxFn = void(Assembler::*)(XMMRegister, Op, uint8_t)
Protected Member Functions
template<typename Op >
void PinsrHelper (Assembler *assm, AvxFn< Op > avx, NoAvxFn< Op > noavx, XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t *load_pc_offset=nullptr, std::optional< CpuFeature > feature=std::nullopt)
Private Member Functions
template<typename Op >
void I8x16SplatPreAvx2 (XMMRegister dst, Op src, XMMRegister scratch)
template<typename Op >
void I16x8SplatPreAvx2 (XMMRegister dst, Op src)
Additional Inherited Members
Detailed Description
Definition at line 110 of file macro-assembler-shared-ia32-x64.h.
Member Typedef Documentation
AvxFn
template<typename Op >
using v8::internal::SharedMacroAssemblerBase::AvxFn = void (Assembler::*)(XMMRegister, XMMRegister, Op, uint8_t) [protected]
Definition at line 570 of file macro-assembler-shared-ia32-x64.h.
NoAvxFn
template<typename Op >
using v8::internal::SharedMacroAssemblerBase::NoAvxFn = void (Assembler::*)(XMMRegister, Op, uint8_t) [protected]
Definition at line 572 of file macro-assembler-shared-ia32-x64.h.
Member Function Documentation
Add()
void v8::internal::SharedMacroAssemblerBase::Add (Register dst, Immediate src)
Definition at line 54 of file macro-assembler-shared-ia32-x64.cc.
                                                              {
  // Helper to paper over the different assembler function names.
#if V8_TARGET_ARCH_IA32
  add(dst, src);
#elif V8_TARGET_ARCH_X64
  addq(dst, src);
#else
#error Unsupported target architecture.
#endif
}
References v8::internal::Assembler::add().
Referenced by I8x16Shl(), I8x16ShrS(), and I8x16ShrU().
And()
void v8::internal::SharedMacroAssemblerBase::And (Register dst, Immediate src)
Definition at line 65 of file macro-assembler-shared-ia32-x64.cc.
                                                              {
  // Helper to paper over the different assembler function names.
#if V8_TARGET_ARCH_IA32
  and_(dst, src);
#elif V8_TARGET_ARCH_X64
  if (is_uint32(src.value())) {
    andl(dst, src);
  } else {
    andq(dst, src);
  }
#else
#error Unsupported target architecture.
#endif
}
References v8::internal::Assembler::and_(), and v8::internal::Immediate::value().
Referenced by I64x2ShrS(), I8x16Shl(), I8x16ShrS(), and I8x16ShrU().
Blendvpd()
void v8::internal::SharedMacroAssemblerBase::Blendvpd (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister mask)
Definition at line 105 of file macro-assembler-shared-ia32-x64.cc.
                                                                            {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vblendvpd(dst, src1, src2, mask);
  } else {
    CpuFeatureScope scope(this, SSE4_1);
    DCHECK_EQ(mask, xmm0);
    DCHECK_EQ(dst, src1);
    blendvpd(dst, src2);
  }
}
References DCHECK_EQ, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vblendvpd().
Blendvps()
void v8::internal::SharedMacroAssemblerBase::Blendvps (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister mask)
Definition at line 118 of file macro-assembler-shared-ia32-x64.cc.
                                                                            {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vblendvps(dst, src1, src2, mask);
  } else {
    CpuFeatureScope scope(this, SSE4_1);
    DCHECK_EQ(mask, xmm0);
    DCHECK_EQ(dst, src1);
    blendvps(dst, src2);
  }
}
References DCHECK_EQ, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vblendvps().
F32x4ExtractLane()
void v8::internal::SharedMacroAssemblerBase::F32x4ExtractLane (FloatRegister dst, XMMRegister src, uint8_t lane)
Definition at line 359 of file macro-assembler-shared-ia32-x64.cc.
                                                                               {
  ASM_CODE_COMMENT(this);
  DCHECK_LT(lane, 4);
  // These instructions are shorter than insertps, but will leave junk in
  // the top lanes of dst.
  if (lane == 0) {
    if (dst != src) {
      Movaps(dst, src);
    }
  } else if (lane == 1) {
    Movshdup(dst, src);
  } else if (lane == 2 && dst == src) {
    // Check dst == src to avoid false dependency on dst.
    Movhlps(dst, src);
  } else if (dst == src) {
    Shufps(dst, src, src, lane);
  } else {
    Pshufd(dst, src, lane);
  }
}
References ASM_CODE_COMMENT, DCHECK_LT, and Shufps().
F32x4Max()
void v8::internal::SharedMacroAssemblerBase::F32x4Max (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
Definition at line 231 of file macro-assembler-shared-ia32-x64.cc.
                                                                              {
  ASM_CODE_COMMENT(this);
  // The maxps instruction doesn't propagate NaNs and +0's in its first
  // operand. Perform maxps in both orders, merge the results, and adjust.
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vmaxps(scratch, lhs, rhs);
    vmaxps(dst, rhs, lhs);
  } else if (dst == lhs || dst == rhs) {
    XMMRegister src = dst == lhs ? rhs : lhs;
    movaps(scratch, src);
    maxps(scratch, dst);
    maxps(dst, src);
  } else {
    movaps(scratch, lhs);
    maxps(scratch, rhs);
    movaps(dst, rhs);
    maxps(dst, lhs);
  }
  // Find discrepancies.
  Xorps(dst, scratch);
  // Propagate NaNs, which may be non-canonical.
  Orps(scratch, dst);
  // Propagate sign discrepancy and (subtle) quiet NaNs.
  Subps(scratch, scratch, dst);
  // Canonicalize NaNs by clearing the payload. Sign is non-deterministic.
  Cmpunordps(dst, dst, scratch);
  Psrld(dst, dst, uint8_t{10});
  Andnps(dst, dst, scratch);
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
F32x4Min()
void v8::internal::SharedMacroAssemblerBase::F32x4Min (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
Definition at line 202 of file macro-assembler-shared-ia32-x64.cc.
                                                                              {
  ASM_CODE_COMMENT(this);
  // The minps instruction doesn't propagate NaNs and +0's in its first
  // operand. Perform minps in both orders, merge the results, and adjust.
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vminps(scratch, lhs, rhs);
    vminps(dst, rhs, lhs);
  } else if (dst == lhs || dst == rhs) {
    XMMRegister src = dst == lhs ? rhs : lhs;
    movaps(scratch, src);
    minps(scratch, dst);
    minps(dst, src);
  } else {
    movaps(scratch, lhs);
    minps(scratch, rhs);
    movaps(dst, rhs);
    minps(dst, lhs);
  }
  // Propagate -0's and NaNs, which may be non-canonical.
  Orps(scratch, dst);
  // Canonicalize NaNs by quieting and clearing the payload.
  Cmpunordps(dst, dst, scratch);
  Orps(scratch, dst);
  Psrld(dst, dst, uint8_t{10});
  Andnps(dst, dst, scratch);
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
F32x4Qfma()
void v8::internal::SharedMacroAssemblerBase::F32x4Qfma (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
Definition at line 1310 of file macro-assembler-shared-ia32-x64.cc.
                                                          {
  QFMA(ps)
}
References v8::internal::Assembler::ps(), and QFMA.
F32x4Qfms()
void v8::internal::SharedMacroAssemblerBase::F32x4Qfms (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
Definition at line 1316 of file macro-assembler-shared-ia32-x64.cc.
                                                          {
  QFMS(ps)
}
References v8::internal::Assembler::ps(), and QFMS.
F32x4Splat()
void v8::internal::SharedMacroAssemblerBase::F32x4Splat (XMMRegister dst, DoubleRegister src)
Definition at line 341 of file macro-assembler-shared-ia32-x64.cc.
                                                                             {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    vbroadcastss(dst, src);
  } else if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vshufps(dst, src, src, 0);
  } else {
    if (dst == src) {
      // 1 byte shorter than pshufd.
      shufps(dst, src, 0);
    } else {
      pshufd(dst, src, 0);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::pshufd(), v8::internal::Assembler::shufps(), v8::internal::Assembler::vbroadcastss(), and v8::internal::Assembler::vshufps().
F64x2ExtractLane()
void v8::internal::SharedMacroAssemblerBase::F64x2ExtractLane (DoubleRegister dst, XMMRegister src, uint8_t lane)
Definition at line 157 of file macro-assembler-shared-ia32-x64.cc.
                                                                               {
  ASM_CODE_COMMENT(this);
  if (lane == 0) {
    if (dst != src) {
      Movaps(dst, src);
    }
  } else {
    DCHECK_EQ(1, lane);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      // Pass src as operand to avoid false-dependency on dst.
      vmovhlps(dst, src, src);
    } else {
      movhlps(dst, src);
    }
  }
}
References ASM_CODE_COMMENT, DCHECK_EQ, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movhlps(), and v8::internal::Assembler::vmovhlps().
F64x2Max()
void v8::internal::SharedMacroAssemblerBase::F64x2Max (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
Definition at line 301 of file macro-assembler-shared-ia32-x64.cc.
                                                                              {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    // The maxpd instruction doesn't propagate NaNs and +0's in its first
    // operand. Perform maxpd in both orders, merge the resuls, and adjust.
    vmaxpd(scratch, lhs, rhs);
    vmaxpd(dst, rhs, lhs);
    // Find discrepancies.
    vxorpd(dst, dst, scratch);
    // Propagate NaNs, which may be non-canonical.
    vorpd(scratch, scratch, dst);
    // Propagate sign discrepancy and (subtle) quiet NaNs.
    vsubpd(scratch, scratch, dst);
    // Canonicalize NaNs by clearing the payload. Sign is non-deterministic.
    vcmpunordpd(dst, dst, scratch);
    vpsrlq(dst, dst, uint8_t{13});
    vandnpd(dst, dst, scratch);
  } else {
    if (dst == lhs || dst == rhs) {
      XMMRegister src = dst == lhs ? rhs : lhs;
      movaps(scratch, src);
      maxpd(scratch, dst);
      maxpd(dst, src);
    } else {
      movaps(scratch, lhs);
      movaps(dst, rhs);
      maxpd(scratch, rhs);
      maxpd(dst, lhs);
    }
    xorpd(dst, scratch);
    orpd(scratch, dst);
    subpd(scratch, dst);
    cmpunordpd(dst, scratch);
    psrlq(dst, uint8_t{13});
    andnpd(dst, scratch);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::psrlq(), and v8::internal::Assembler::vpsrlq().
F64x2Min()
void v8::internal::SharedMacroAssemblerBase::F64x2Min (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister scratch)
Definition at line 263 of file macro-assembler-shared-ia32-x64.cc.
                                                                              {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    // The minpd instruction doesn't propagate NaNs and +0's in its first
    // operand. Perform minpd in both orders, merge the resuls, and adjust.
    vminpd(scratch, lhs, rhs);
    vminpd(dst, rhs, lhs);
    // propagate -0's and NaNs, which may be non-canonical.
    vorpd(scratch, scratch, dst);
    // Canonicalize NaNs by quieting and clearing the payload.
    vcmpunordpd(dst, dst, scratch);
    vorpd(scratch, scratch, dst);
    vpsrlq(dst, dst, uint8_t{13});
    vandnpd(dst, dst, scratch);
  } else {
    // Compare lhs with rhs, and rhs with lhs, and have the results in scratch
    // and dst. If dst overlaps with lhs or rhs, we can save a move.
    if (dst == lhs || dst == rhs) {
      XMMRegister src = dst == lhs ? rhs : lhs;
      movaps(scratch, src);
      minpd(scratch, dst);
      minpd(dst, src);
    } else {
      movaps(scratch, lhs);
      movaps(dst, rhs);
      minpd(scratch, rhs);
      minpd(dst, lhs);
    }
    orpd(scratch, dst);
    cmpunordpd(dst, scratch);
    orpd(scratch, dst);
    psrlq(dst, uint8_t{13});
    andnpd(dst, scratch);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::psrlq(), and v8::internal::Assembler::vpsrlq().
F64x2Qfma()
void v8::internal::SharedMacroAssemblerBase::F64x2Qfma (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
Definition at line 1322 of file macro-assembler-shared-ia32-x64.cc.
                                                          {
  QFMA(pd);
}
References v8::internal::Assembler::pd(), and QFMA.
F64x2Qfms()
void v8::internal::SharedMacroAssemblerBase::F64x2Qfms (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister tmp)
Definition at line 1328 of file macro-assembler-shared-ia32-x64.cc.
                                                          {
  QFMS(pd);
}
References v8::internal::Assembler::pd(), and QFMS.
F64x2ReplaceLane()
void v8::internal::SharedMacroAssemblerBase::F64x2ReplaceLane (XMMRegister dst, XMMRegister src, DoubleRegister rep, uint8_t lane)
Definition at line 176 of file macro-assembler-shared-ia32-x64.cc.
                                                              {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    if (lane == 0) {
      vmovsd(dst, src, rep);
    } else {
      vmovlhps(dst, src, rep);
    }
  } else {
    CpuFeatureScope scope(this, SSE4_1);
    if (dst != src) {
      DCHECK_NE(dst, rep); // Ensure rep is not overwritten.
      movaps(dst, src);
    }
    if (lane == 0) {
      movsd(dst, rep);
    } else {
      movlhps(dst, rep);
    }
  }
}
References ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::movlhps(), v8::internal::Assembler::movsd(), v8::internal::Assembler::vmovlhps(), and v8::internal::Assembler::vmovsd().
I16x8DotI8x16I7x16S()
void v8::internal::SharedMacroAssemblerBase::I16x8DotI8x16I7x16S (XMMRegister dst, XMMRegister src1, XMMRegister src2)
Definition at line 738 of file macro-assembler-shared-ia32-x64.cc.
                                                                     {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpmaddubsw(dst, src2, src1);
  } else {
    if (dst != src2) {
      movdqa(dst, src2);
    }
    pmaddubsw(dst, src1);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movdqa().
I16x8ExtMulHighS()
void v8::internal::SharedMacroAssemblerBase::I16x8ExtMulHighS (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
Definition at line 594 of file macro-assembler-shared-ia32-x64.cc.
                                                                     {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpunpckhbw(scratch, src1, src1);
    vpsraw(scratch, scratch, 8);
    vpunpckhbw(dst, src2, src2);
    vpsraw(dst, dst, 8);
    vpmullw(dst, dst, scratch);
  } else {
    if (dst != src1) {
      movaps(dst, src1);
    }
    movaps(scratch, src2);
    punpckhbw(dst, dst);
    psraw(dst, 8);
    punpckhbw(scratch, scratch);
    psraw(scratch, 8);
    pmullw(dst, scratch);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::psraw(), and v8::internal::Assembler::vpsraw().
I16x8ExtMulHighU()
void v8::internal::SharedMacroAssemblerBase::I16x8ExtMulHighU (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
Definition at line 619 of file macro-assembler-shared-ia32-x64.cc.
                                                                     {
  ASM_CODE_COMMENT(this);
  // The logic here is slightly complicated to handle all the cases of register
  // aliasing. This allows flexibility for callers in TurboFan and Liftoff.
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    if (src1 == src2) {
      vpxor(scratch, scratch, scratch);
      vpunpckhbw(dst, src1, scratch);
      vpmullw(dst, dst, dst);
    } else {
      if (dst == src2) {
        // We overwrite dst, then use src2, so swap src1 and src2.
        std::swap(src1, src2);
      }
      vpxor(scratch, scratch, scratch);
      vpunpckhbw(dst, src1, scratch);
      vpunpckhbw(scratch, src2, scratch);
      vpmullw(dst, dst, scratch);
    }
  } else {
    if (src1 == src2) {
      xorps(scratch, scratch);
      if (dst != src1) {
        movaps(dst, src1);
      }
      punpckhbw(dst, scratch);
      pmullw(dst, scratch);
    } else {
      // When dst == src1, nothing special needs to be done.
      // When dst == src2, swap src1 and src2, since we overwrite dst.
      // When dst is unique, copy src1 to dst first.
      if (dst == src2) {
        std::swap(src1, src2);
        // Now, dst == src1.
      } else if (dst != src1) {
        // dst != src1 && dst != src2.
        movaps(dst, src1);
      }
      xorps(scratch, scratch);
      punpckhbw(dst, scratch);
      punpckhbw(scratch, src2);
      psrlw(scratch, 8);
      pmullw(dst, scratch);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), and v8::internal::Assembler::psrlw().
I16x8ExtMulLow()
void v8::internal::SharedMacroAssemblerBase::I16x8ExtMulLow (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scrat, bool is_signed)
Definition at line 584 of file macro-assembler-shared-ia32-x64.cc.
                                                              {
  ASM_CODE_COMMENT(this);
  is_signed ? Pmovsxbw(scratch, src1) : Pmovzxbw(scratch, src1);
  is_signed ? Pmovsxbw(dst, src2) : Pmovzxbw(dst, src2);
  Pmullw(dst, scratch);
}
References ASM_CODE_COMMENT, and v8::internal::is_signed().
I16x8Q15MulRSatS()
void v8::internal::SharedMacroAssemblerBase::I16x8Q15MulRSatS (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
Definition at line 719 of file macro-assembler-shared-ia32-x64.cc.
                                                                     {
  ASM_CODE_COMMENT(this);
  // k = i16x8.splat(0x8000)
  Pcmpeqd(scratch, scratch);
  Psllw(scratch, scratch, uint8_t{15});
  if (!CpuFeatures::IsSupported(AVX) && (dst != src1)) {
    movaps(dst, src1);
    src1 = dst;
  }
  Pmulhrsw(dst, src1, src2);
  Pcmpeqw(scratch, dst);
  Pxor(dst, scratch);
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
I16x8SConvertI8x16High()
void v8::internal::SharedMacroAssemblerBase::I16x8SConvertI8x16High (XMMRegister dst, XMMRegister src)
Definition at line 670 of file macro-assembler-shared-ia32-x64.cc.
                                                                       {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // src = |a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p| (high)
    // dst = |i|i|j|j|k|k|l|l|m|m|n|n|o|o|p|p|
    vpunpckhbw(dst, src, src);
    vpsraw(dst, dst, 8);
  } else {
    CpuFeatureScope sse_scope(this, SSE4_1);
    if (dst == src) {
      // 2 bytes shorter than pshufd, but has depdency on dst.
      movhlps(dst, src);
      pmovsxbw(dst, dst);
    } else {
      // No dependency on dst.
      pshufd(dst, src, 0xEE);
      pmovsxbw(dst, dst);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movhlps(), v8::internal::Assembler::pshufd(), and v8::internal::Assembler::vpsraw().
I16x8Splat() [1/2]
void v8::internal::SharedMacroAssemblerBase::I16x8Splat (XMMRegister dst, Operand src)
Definition at line 573 of file macro-assembler-shared-ia32-x64.cc.
                                                                      {
  ASM_CODE_COMMENT(this);
  DCHECK_OPERAND_IS_NOT_REG(src);
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    vpbroadcastw(dst, src);
  } else {
    I16x8SplatPreAvx2(dst, src);
  }
}
References ASM_CODE_COMMENT, DCHECK_OPERAND_IS_NOT_REG, I16x8SplatPreAvx2(), and v8::internal::CpuFeatures::IsSupported().
I16x8Splat() [2/2]
void v8::internal::SharedMacroAssemblerBase::I16x8Splat (XMMRegister dst, Register src)
Definition at line 562 of file macro-assembler-shared-ia32-x64.cc.
                                                                       {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    Movd(dst, src);
    vpbroadcastw(dst, dst);
  } else {
    I16x8SplatPreAvx2(dst, src);
  }
}
References ASM_CODE_COMMENT, I16x8SplatPreAvx2(), and v8::internal::CpuFeatures::IsSupported().
I16x8SplatPreAvx2()
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::I16x8SplatPreAvx2 (XMMRegister dst, Op src) [private]
Definition at line 555 of file macro-assembler-shared-ia32-x64.cc.
                                                                        {
  DCHECK(!CpuFeatures::IsSupported(AVX2));
  Movd(dst, src);
  Pshuflw(dst, dst, uint8_t{0x0});
  Punpcklqdq(dst, dst);
}
References v8::internal::DCHECK(), and v8::internal::CpuFeatures::IsSupported().
Referenced by I16x8Splat().
I16x8UConvertI8x16High()
void v8::internal::SharedMacroAssemblerBase::I16x8UConvertI8x16High (XMMRegister dst, XMMRegister src, XMMRegister scratch)
Definition at line 693 of file macro-assembler-shared-ia32-x64.cc.
                                                                           {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // tmp = |0|0|0|0|0|0|0|0 | 0|0|0|0|0|0|0|0|
    // src = |a|b|c|d|e|f|g|h | i|j|k|l|m|n|o|p|
    // dst = |0|a|0|b|0|c|0|d | 0|e|0|f|0|g|0|h|
    XMMRegister tmp = dst == src ? scratch : dst;
    vpxor(tmp, tmp, tmp);
    vpunpckhbw(dst, src, tmp);
  } else {
    CpuFeatureScope sse_scope(this, SSE4_1);
    if (dst == src) {
      // xorps can be executed on more ports than pshufd.
      xorps(scratch, scratch);
      punpckhbw(dst, scratch);
    } else {
      // No dependency on dst.
      pshufd(dst, src, 0xEE);
      pmovzxbw(dst, dst);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::pshufd().
I32x4DotI8x16I7x16AddS()
void v8::internal::SharedMacroAssemblerBase::I32x4DotI8x16I7x16AddS (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister src3, XMMRegister scratch, XMMRegister splat_reg)
Definition at line 753 of file macro-assembler-shared-ia32-x64.cc.
                                                {
  ASM_CODE_COMMENT(this);
#if V8_TARGET_ARCH_X64
  if (CpuFeatures::IsSupported(AVX_VNNI_INT8)) {
    CpuFeatureScope avx_vnni_int8_scope(this, AVX_VNNI_INT8);
    if (dst == src3) {
      vpdpbssd(dst, src2, src1);
    } else {
      DCHECK_NE(dst, src1);
      DCHECK_NE(dst, src2);
      Movdqa(dst, src3);
      vpdpbssd(dst, src2, src1);
    }
    return;
  } else if (CpuFeatures::IsSupported(AVX_VNNI)) {
    CpuFeatureScope avx_scope(this, AVX_VNNI);
    if (dst == src3) {
      vpdpbusd(dst, src2, src1);
    } else {
      DCHECK_NE(dst, src1);
      DCHECK_NE(dst, src2);
      Movdqa(dst, src3);
      vpdpbusd(dst, src2, src1);
    }
    return;
  }
#endif
  // k = i16x8.splat(1)
  Pcmpeqd(splat_reg, splat_reg);
  Psrlw(splat_reg, splat_reg, uint8_t{15});
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpmaddubsw(scratch, src2, src1);
  } else {
    movdqa(scratch, src2);
    pmaddubsw(scratch, src1);
  }
  Pmaddwd(scratch, splat_reg);
  if (dst == src3) {
    Paddd(dst, scratch);
  } else {
    Movdqa(dst, src3);
    Paddd(dst, scratch);
  }
}
References ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movdqa(), v8::internal::Assembler::vpdpbssd(), and v8::internal::Assembler::vpdpbusd().
I32x4ExtAddPairwiseI16x8U()
void v8::internal::SharedMacroAssemblerBase::I32x4ExtAddPairwiseI16x8U (XMMRegister dst, XMMRegister src, XMMRegister tmp)
Definition at line 803 of file macro-assembler-shared-ia32-x64.cc.
                                                                          {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // src = |a|b|c|d|e|f|g|h| (low)
    // scratch = |0|a|0|c|0|e|0|g|
    vpsrld(tmp, src, 16);
    // dst = |0|b|0|d|0|f|0|h|
    vpblendw(dst, src, tmp, 0xAA);
    // dst = |a+b|c+d|e+f|g+h|
    vpaddd(dst, tmp, dst);
  } else if (CpuFeatures::IsSupported(SSE4_1)) {
    CpuFeatureScope sse_scope(this, SSE4_1);
    // There is a potentially better lowering if we get rip-relative
    // constants, see https://github.com/WebAssembly/simd/pull/380.
    movaps(tmp, src);
    psrld(tmp, 16);
    if (dst != src) {
      movaps(dst, src);
    }
    pblendw(dst, tmp, 0xAA);
    paddd(dst, tmp);
  } else {
    // src = |a|b|c|d|e|f|g|h|
    // tmp = i32x4.splat(0x0000FFFF)
    pcmpeqd(tmp, tmp);
    psrld(tmp, uint8_t{16});
    // tmp =|0|b|0|d|0|f|0|h|
    andps(tmp, src);
    // dst = |0|a|0|c|0|e|0|g|
    if (dst != src) {
      movaps(dst, src);
    }
    psrld(dst, uint8_t{16});
    // dst = |a+b|c+d|e+f|g+h|
    paddd(dst, tmp);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::pblendw(), v8::internal::Assembler::psrld(), v8::internal::Assembler::vpblendw(), and v8::internal::Assembler::vpsrld().
I32x4ExtMul()
void v8::internal::SharedMacroAssemblerBase::I32x4ExtMul (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch, bool low, bool is_signed)
Definition at line 847 of file macro-assembler-shared-ia32-x64.cc.
                                                           {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpmullw(scratch, src1, src2);
    is_signed ? vpmulhw(dst, src1, src2) : vpmulhuw(dst, src1, src2);
    low ? vpunpcklwd(dst, scratch, dst) : vpunpckhwd(dst, scratch, dst);
  } else {
    DCHECK_EQ(dst, src1);
    movaps(scratch, src1);
    pmullw(dst, src2);
    is_signed ? pmulhw(scratch, src2) : pmulhuw(scratch, src2);
    low ? punpcklwd(dst, scratch) : punpckhwd(dst, scratch);
  }
}
References ASM_CODE_COMMENT, DCHECK_EQ, v8::internal::is_signed(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
Referenced by v8::internal::wasm::liftoff::I32x4ExtMulHelper().
I32x4SConvertI16x8High()
void v8::internal::SharedMacroAssemblerBase::I32x4SConvertI16x8High (XMMRegister dst, XMMRegister src)
Definition at line 866 of file macro-assembler-shared-ia32-x64.cc.
                                                                       {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // src = |a|b|c|d|e|f|g|h| (high)
    // dst = |e|e|f|f|g|g|h|h|
    vpunpckhwd(dst, src, src);
    vpsrad(dst, dst, 16);
  } else {
    CpuFeatureScope sse_scope(this, SSE4_1);
    if (dst == src) {
      // 2 bytes shorter than pshufd, but has depdency on dst.
      movhlps(dst, src);
      pmovsxwd(dst, dst);
    } else {
      // No dependency on dst.
      pshufd(dst, src, 0xEE);
      pmovsxwd(dst, dst);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movhlps(), v8::internal::Assembler::pshufd(), and v8::internal::Assembler::vpsrad().
I32x4UConvertI16x8High()
void v8::internal::SharedMacroAssemblerBase::I32x4UConvertI16x8High (XMMRegister dst, XMMRegister src, XMMRegister scratch)
Definition at line 889 of file macro-assembler-shared-ia32-x64.cc.
                                                                           {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // scratch = |0|0|0|0|0|0|0|0|
    // src = |a|b|c|d|e|f|g|h|
    // dst = |0|a|0|b|0|c|0|d|
    XMMRegister tmp = dst == src ? scratch : dst;
    vpxor(tmp, tmp, tmp);
    vpunpckhwd(dst, src, tmp);
  } else {
    if (dst == src) {
      // xorps can be executed on more ports than pshufd.
      xorps(scratch, scratch);
      punpckhwd(dst, scratch);
    } else {
      CpuFeatureScope sse_scope(this, SSE4_1);
      // No dependency on dst.
      pshufd(dst, src, 0xEE);
      pmovzxwd(dst, dst);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::pshufd().
I64x2Abs()
void v8::internal::SharedMacroAssemblerBase::I64x2Abs (XMMRegister dst, XMMRegister src, XMMRegister scratch)
Definition at line 932 of file macro-assembler-shared-ia32-x64.cc.
                                                             {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    XMMRegister tmp = dst == src ? scratch : dst;
    vpxor(tmp, tmp, tmp);
    vpsubq(tmp, tmp, src);
    vblendvpd(dst, src, tmp, src);
  } else {
    CpuFeatureScope sse_scope(this, SSE3);
    movshdup(scratch, src);
    if (dst != src) {
      movaps(dst, src);
    }
    psrad(scratch, 31);
    xorps(dst, scratch);
    psubq(dst, scratch);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::movshdup(), v8::internal::Assembler::psrad(), and v8::internal::Assembler::vblendvpd().
I64x2ExtMul()
void v8::internal::SharedMacroAssemblerBase::I64x2ExtMul (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister scratch, bool low, bool is_signed)
Definition at line 1135 of file macro-assembler-shared-ia32-x64.cc.
                                                           {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    if (low) {
      vpunpckldq(scratch, src1, src1);
      vpunpckldq(dst, src2, src2);
    } else {
      vpunpckhdq(scratch, src1, src1);
      vpunpckhdq(dst, src2, src2);
    }
    if (is_signed) {
      vpmuldq(dst, scratch, dst);
    } else {
      vpmuludq(dst, scratch, dst);
    }
  } else {
    uint8_t mask = low ? 0x50 : 0xFA;
    pshufd(scratch, src1, mask);
    pshufd(dst, src2, mask);
    if (is_signed) {
      CpuFeatureScope sse4_scope(this, SSE4_1);
      pmuldq(dst, scratch);
    } else {
      pmuludq(dst, scratch);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::is_signed(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::pshufd().
I64x2GeS()
void v8::internal::SharedMacroAssemblerBase::I64x2GeS (XMMRegister dst, XMMRegister src0, XMMRegister src1, XMMRegister scratch)
Definition at line 987 of file macro-assembler-shared-ia32-x64.cc.
                                                                               {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpcmpgtq(dst, src1, src0);
    vpcmpeqd(scratch, scratch, scratch);
    vpxor(dst, dst, scratch);
  } else if (CpuFeatures::IsSupported(SSE4_2)) {
    CpuFeatureScope sse_scope(this, SSE4_2);
    DCHECK_NE(dst, src0);
    if (dst != src1) {
      movaps(dst, src1);
    }
    pcmpgtq(dst, src0);
    pcmpeqd(scratch, scratch);
    xorps(dst, scratch);
  } else {
    CpuFeatureScope sse_scope(this, SSE3);
    DCHECK_NE(dst, src0);
    DCHECK_NE(dst, src1);
    movaps(dst, src0);
    movaps(scratch, src1);
    psubq(dst, src1);
    pcmpeqd(scratch, src0);
    andps(dst, scratch);
    movaps(scratch, src1);
    pcmpgtd(scratch, src0);
    orps(dst, scratch);
    movshdup(dst, dst);
    pcmpeqd(scratch, scratch);
    xorps(dst, scratch);
  }
}
References ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::movshdup(), v8::internal::Assembler::pcmpgtq(), and v8::internal::Assembler::vpcmpgtq().
I64x2GtS()
void v8::internal::SharedMacroAssemblerBase::I64x2GtS (XMMRegister dst, XMMRegister src0, XMMRegister src1, XMMRegister scratch)
Definition at line 953 of file macro-assembler-shared-ia32-x64.cc.
                                                                               {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpcmpgtq(dst, src0, src1);
  } else if (CpuFeatures::IsSupported(SSE4_2)) {
    CpuFeatureScope sse_scope(this, SSE4_2);
    if (dst == src0) {
      pcmpgtq(dst, src1);
    } else if (dst == src1) {
      movaps(scratch, src0);
      pcmpgtq(scratch, src1);
      movaps(dst, scratch);
    } else {
      movaps(dst, src0);
      pcmpgtq(dst, src1);
    }
  } else {
    CpuFeatureScope sse_scope(this, SSE3);
    DCHECK_NE(dst, src0);
    DCHECK_NE(dst, src1);
    movaps(dst, src1);
    movaps(scratch, src0);
    psubq(dst, src0);
    pcmpeqd(scratch, src1);
    andps(dst, scratch);
    movaps(scratch, src0);
    pcmpgtd(scratch, src1);
    orps(dst, scratch);
    movshdup(dst, dst);
  }
}
References ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::movshdup(), v8::internal::Assembler::pcmpgtq(), and v8::internal::Assembler::vpcmpgtq().
I64x2Mul()
void v8::internal::SharedMacroAssemblerBase::I64x2Mul (XMMRegister dst, XMMRegister lhs, XMMRegister rhs, XMMRegister tmp1, XMMRegister tmp2)
Definition at line 1085 of file macro-assembler-shared-ia32-x64.cc.
                                                          {
  ASM_CODE_COMMENT(this);
  DCHECK(!AreAliased(dst, tmp1, tmp2));
  DCHECK(!AreAliased(lhs, tmp1, tmp2));
  DCHECK(!AreAliased(rhs, tmp1, tmp2));
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // 1. Multiply high dword of each qword of left with right.
    vpsrlq(tmp1, lhs, uint8_t{32});
    vpmuludq(tmp1, tmp1, rhs);
    // 2. Multiply high dword of each qword of right with left.
    vpsrlq(tmp2, rhs, uint8_t{32});
    vpmuludq(tmp2, tmp2, lhs);
    // 3. Add 1 and 2, then shift left by 32 (this is the high dword of result).
    vpaddq(tmp2, tmp2, tmp1);
    vpsllq(tmp2, tmp2, uint8_t{32});
    // 4. Multiply low dwords (this is the low dword of result).
    vpmuludq(dst, lhs, rhs);
    // 5. Add 3 and 4.
    vpaddq(dst, dst, tmp2);
  } else {
    // Same algorithm as AVX version, but with moves to not overwrite inputs.
    movaps(tmp1, lhs);
    movaps(tmp2, rhs);
    psrlq(tmp1, uint8_t{32});
    pmuludq(tmp1, rhs);
    psrlq(tmp2, uint8_t{32});
    pmuludq(tmp2, lhs);
    paddq(tmp2, tmp1);
    psllq(tmp2, uint8_t{32});
    if (dst == rhs) {
      // pmuludq is commutative
      pmuludq(dst, lhs);
    } else {
      if (dst != lhs) {
        movaps(dst, lhs);
      }
      pmuludq(dst, rhs);
    }
    paddq(dst, tmp2);
  }
}
References v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::psllq(), v8::internal::Assembler::psrlq(), v8::internal::Assembler::vpsllq(), and v8::internal::Assembler::vpsrlq().
I64x2Neg()
void v8::internal::SharedMacroAssemblerBase::I64x2Neg (XMMRegister dst, XMMRegister src, XMMRegister scratch)
Definition at line 915 of file macro-assembler-shared-ia32-x64.cc.
                                                             {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vpxor(scratch, scratch, scratch);
    vpsubq(dst, scratch, src);
  } else {
    if (dst == src) {
      movaps(scratch, src);
      std::swap(src, scratch);
    }
    pxor(dst, dst);
    psubq(dst, src);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
I64x2SConvertI32x4High()
void v8::internal::SharedMacroAssemblerBase::I64x2SConvertI32x4High (XMMRegister dst, XMMRegister src)
Definition at line 1167 of file macro-assembler-shared-ia32-x64.cc.
                                                                       {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpunpckhqdq(dst, src, src);
    vpmovsxdq(dst, dst);
  } else {
    CpuFeatureScope sse_scope(this, SSE4_1);
    if (dst == src) {
      movhlps(dst, src);
    } else {
      pshufd(dst, src, 0xEE);
    }
    pmovsxdq(dst, dst);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movhlps(), and v8::internal::Assembler::pshufd().
I64x2ShrS() [1/2]
void v8::internal::SharedMacroAssemblerBase::I64x2ShrS (XMMRegister dst, XMMRegister src, Register shift, XMMRegister xmm_tmp, XMMRegister xmm_shift, Register tmp_shift)
Definition at line 1055 of file macro-assembler-shared-ia32-x64.cc.
                                                             {
  ASM_CODE_COMMENT(this);
  DCHECK_NE(xmm_tmp, dst);
  DCHECK_NE(xmm_tmp, src);
  DCHECK_NE(xmm_shift, dst);
  DCHECK_NE(xmm_shift, src);
  // tmp_shift can alias shift since we don't use shift after masking it.
  // See I64x2ShrS with constant shift for explanation of this algorithm.
  Pcmpeqd(xmm_tmp, xmm_tmp);
  Psllq(xmm_tmp, uint8_t{63});
  // Shift modulo 64.
  Move(tmp_shift, shift);
  And(tmp_shift, Immediate(0x3F));
  Movd(xmm_shift, tmp_shift);
  if (!CpuFeatures::IsSupported(AVX) && (dst != src)) {
    movaps(dst, src);
    src = dst;
  }
  Pxor(dst, src, xmm_tmp);
  Psrlq(dst, xmm_shift);
  Psrlq(xmm_tmp, xmm_shift);
  Psubq(dst, xmm_tmp);
}
References And(), ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), Move(), and v8::internal::Assembler::shift().
I64x2ShrS() [2/2]
void v8::internal::SharedMacroAssemblerBase::I64x2ShrS (XMMRegister dst, XMMRegister src, uint8_t shift, XMMRegister xmm_tmp)
Definition at line 1022 of file macro-assembler-shared-ia32-x64.cc.
                                                                             {
  ASM_CODE_COMMENT(this);
  DCHECK_GT(64, shift);
  DCHECK_NE(xmm_tmp, dst);
  DCHECK_NE(xmm_tmp, src);
  // Use logical right shift to emulate arithmetic right shifts:
  // Given:
  // signed >> c
  // == (signed + 2^63 - 2^63) >> c
  // == ((signed + 2^63) >> c) - (2^63 >> c)
  // ^^^^^^^^^
  // xmm_tmp
  // signed + 2^63 is an unsigned number, so we can use logical right shifts.
  // xmm_tmp = wasm_i64x2_const(0x80000000'00000000).
  Pcmpeqd(xmm_tmp, xmm_tmp);
  Psllq(xmm_tmp, uint8_t{63});
  if (!CpuFeatures::IsSupported(AVX) && (dst != src)) {
    movaps(dst, src);
    src = dst;
  }
  // Add a bias of 2^63 to convert signed to unsigned.
  // Since only highest bit changes, use pxor instead of paddq.
  Pxor(dst, src, xmm_tmp);
  // Logically shift both value and bias.
  Psrlq(dst, shift);
  Psrlq(xmm_tmp, shift);
  // Subtract shifted bias to convert back to signed value.
  Psubq(dst, xmm_tmp);
}
References ASM_CODE_COMMENT, DCHECK_GT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), and v8::internal::Assembler::shift().
I64x2UConvertI32x4High()
void v8::internal::SharedMacroAssemblerBase::I64x2UConvertI32x4High (XMMRegister dst, XMMRegister src, XMMRegister scratch)
Definition at line 1185 of file macro-assembler-shared-ia32-x64.cc.
                                                                           {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpxor(scratch, scratch, scratch);
    vpunpckhdq(dst, src, scratch);
  } else {
    if (dst == src) {
      // xorps can be executed on more ports than pshufd.
      xorps(scratch, scratch);
      punpckhdq(dst, scratch);
    } else {
      CpuFeatureScope sse_scope(this, SSE4_1);
      // No dependency on dst.
      pshufd(dst, src, 0xEE);
      pmovzxdq(dst, dst);
    }
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::pshufd().
I8x16Shl() [1/2]
void v8::internal::SharedMacroAssemblerBase::I8x16Shl (XMMRegister dst, XMMRegister src1, Register src2, Register tmp1, XMMRegister tmp2, XMMRegister tmp3)
Definition at line 449 of file macro-assembler-shared-ia32-x64.cc.
                                                                            {
  ASM_CODE_COMMENT(this);
  DCHECK(!AreAliased(dst, tmp2, tmp3));
  DCHECK(!AreAliased(src1, tmp2, tmp3));
  // Take shift value modulo 8.
  Move(tmp1, src2);
  And(tmp1, Immediate(7));
  Add(tmp1, Immediate(8));
  // Create a mask to unset high bits.
  Movd(tmp3, tmp1);
  Pcmpeqd(tmp2, tmp2);
  Psrlw(tmp2, tmp2, tmp3);
  Packuswb(tmp2, tmp2);
  if (!CpuFeatures::IsSupported(AVX) && (dst != src1)) {
    movaps(dst, src1);
    src1 = dst;
  }
  // Mask off the unwanted bits before word-shifting.
  Pand(dst, src1, tmp2);
  Add(tmp1, Immediate(-8));
  Movd(tmp3, tmp1);
  Psllw(dst, dst, tmp3);
}
References Add(), And(), v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), and Move().
I8x16Shl() [2/2]
void v8::internal::SharedMacroAssemblerBase::I8x16Shl (XMMRegister dst, XMMRegister src1, uint8_t src2, Register tmp1, XMMRegister tmp2)
Definition at line 427 of file macro-assembler-shared-ia32-x64.cc.
                                                          {
  ASM_CODE_COMMENT(this);
  DCHECK_NE(dst, tmp2);
  // Perform 16-bit shift, then mask away low bits.
  if (!CpuFeatures::IsSupported(AVX) && (dst != src1)) {
    movaps(dst, src1);
    src1 = dst;
  }
  uint8_t shift = truncate_to_int3(src2);
  Psllw(dst, src1, uint8_t{shift});
  uint8_t bmask = static_cast<uint8_t>(0xff << shift);
  uint32_t mask = bmask << 24 | bmask << 16 | bmask << 8 | bmask;
  Move(tmp1, mask);
  Movd(tmp2, tmp1);
  Pshufd(tmp2, tmp2, uint8_t{0});
  Pand(dst, tmp2);
}
References ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), Move(), and v8::internal::Assembler::shift().
I8x16ShrS() [1/2]
void v8::internal::SharedMacroAssemblerBase::I8x16ShrS (XMMRegister dst, XMMRegister src1, Register src2, Register tmp1, XMMRegister tmp2, XMMRegister tmp3)
Definition at line 490 of file macro-assembler-shared-ia32-x64.cc.
                                                                             {
  ASM_CODE_COMMENT(this);
  DCHECK(!AreAliased(dst, tmp2, tmp3));
  DCHECK_NE(src1, tmp2);
  // Unpack the bytes into words, do arithmetic shifts, and repack.
  Punpckhbw(tmp2, src1);
  Punpcklbw(dst, src1);
  // Prepare shift value
  Move(tmp1, src2);
  // Take shift value modulo 8.
  And(tmp1, Immediate(7));
  Add(tmp1, Immediate(8));
  Movd(tmp3, tmp1);
  Psraw(tmp2, tmp3);
  Psraw(dst, tmp3);
  Packsswb(dst, tmp2);
}
References Add(), And(), v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), DCHECK_NE, and Move().
I8x16ShrS() [2/2]
void v8::internal::SharedMacroAssemblerBase::I8x16ShrS (XMMRegister dst, XMMRegister src1, uint8_t src2, XMMRegister tmp)
Definition at line 476 of file macro-assembler-shared-ia32-x64.cc.
                                                                        {
  ASM_CODE_COMMENT(this);
  // Unpack bytes into words, do word (16-bit) shifts, and repack.
  DCHECK_NE(dst, tmp);
  uint8_t shift = truncate_to_int3(src2) + 8;
  Punpckhbw(tmp, src1);
  Punpcklbw(dst, src1);
  Psraw(tmp, shift);
  Psraw(dst, shift);
  Packsswb(dst, tmp);
}
References ASM_CODE_COMMENT, DCHECK_NE, and v8::internal::Assembler::shift().
I8x16ShrU() [1/2]
void v8::internal::SharedMacroAssemblerBase::I8x16ShrU (XMMRegister dst, XMMRegister src1, Register src2, Register tmp1, XMMRegister tmp2, XMMRegister tmp3)
Definition at line 533 of file macro-assembler-shared-ia32-x64.cc.
                                                                             {
  ASM_CODE_COMMENT(this);
  DCHECK(!AreAliased(dst, tmp2, tmp3));
  DCHECK_NE(src1, tmp2);
  // Unpack the bytes into words, do logical shifts, and repack.
  Punpckhbw(tmp2, src1);
  Punpcklbw(dst, src1);
  // Prepare shift value.
  Move(tmp1, src2);
  // Take shift value modulo 8.
  And(tmp1, Immediate(7));
  Add(tmp1, Immediate(8));
  Movd(tmp3, tmp1);
  Psrlw(tmp2, tmp3);
  Psrlw(dst, tmp3);
  Packuswb(dst, tmp2);
}
References Add(), And(), v8::internal::AreAliased(), ASM_CODE_COMMENT, v8::internal::DCHECK(), DCHECK_NE, and Move().
I8x16ShrU() [2/2]
void v8::internal::SharedMacroAssemblerBase::I8x16ShrU (XMMRegister dst, XMMRegister src1, uint8_t src2, Register tmp1, XMMRegister tmp2)
Definition at line 511 of file macro-assembler-shared-ia32-x64.cc.
                                                           {
  ASM_CODE_COMMENT(this);
  DCHECK_NE(dst, tmp2);
  if (!CpuFeatures::IsSupported(AVX) && (dst != src1)) {
    movaps(dst, src1);
    src1 = dst;
  }
  // Perform 16-bit shift, then mask away high bits.
  uint8_t shift = truncate_to_int3(src2);
  Psrlw(dst, src1, shift);
  uint8_t bmask = 0xff >> shift;
  uint32_t mask = bmask << 24 | bmask << 16 | bmask << 8 | bmask;
  Move(tmp1, mask);
  Movd(tmp2, tmp1);
  Pshufd(tmp2, tmp2, uint8_t{0});
  Pand(dst, tmp2);
}
References ASM_CODE_COMMENT, DCHECK_NE, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), Move(), and v8::internal::Assembler::shift().
I8x16Splat() [1/2]
void v8::internal::SharedMacroAssemblerBase::I8x16Splat (XMMRegister dst, Operand src, XMMRegister scratch)
Definition at line 415 of file macro-assembler-shared-ia32-x64.cc.
                                                               {
  ASM_CODE_COMMENT(this);
  DCHECK_OPERAND_IS_NOT_REG(src);
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    vpbroadcastb(dst, src);
  } else {
    I8x16SplatPreAvx2(dst, src, scratch);
  }
}
References ASM_CODE_COMMENT, DCHECK_OPERAND_IS_NOT_REG, I8x16SplatPreAvx2(), and v8::internal::CpuFeatures::IsSupported().
I8x16Splat() [2/2]
void v8::internal::SharedMacroAssemblerBase::I8x16Splat (XMMRegister dst, Register src, XMMRegister scratch)
Definition at line 403 of file macro-assembler-shared-ia32-x64.cc.
                                                               {
  ASM_CODE_COMMENT(this);
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    Movd(scratch, src);
    vpbroadcastb(dst, scratch);
  } else {
    I8x16SplatPreAvx2(dst, src, scratch);
  }
}
References ASM_CODE_COMMENT, I8x16SplatPreAvx2(), and v8::internal::CpuFeatures::IsSupported().
I8x16SplatPreAvx2()
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::I8x16SplatPreAvx2 (XMMRegister dst, Op src, XMMRegister scratch) [private]
Definition at line 393 of file macro-assembler-shared-ia32-x64.cc.
                                                                      {
  ASM_CODE_COMMENT(this);
  DCHECK(!CpuFeatures::IsSupported(AVX2));
  CpuFeatureScope ssse3_scope(this, SSSE3);
  Movd(dst, src);
  Xorps(scratch, scratch);
  Pshufb(dst, scratch);
}
References ASM_CODE_COMMENT, v8::internal::DCHECK(), v8::internal::CpuFeatures::IsSupported(), and Pshufb().
Referenced by I8x16Splat().
MacroAssemblerBase() [1/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase [inline]
Definition at line 26 of file macro-assembler-base.h.
                                                             {})
      : MacroAssemblerBase(isolate, AssemblerOptions::Default(isolate),
                           create_code_object, std::move(buffer)) {}
MacroAssemblerBase() [2/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase
Definition at line 36 of file macro-assembler-base.cc.
    : MacroAssemblerBase(isolate, isolate->allocator(), options,
                         create_code_object, std::move(buffer)) {}
MacroAssemblerBase() [3/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase
Definition at line 39 of file macro-assembler-base.cc.
    : Assembler(zone, options, std::move(buffer)), isolate_(isolate) {
  if (create_code_object == CodeObjectRequired::kYes) {
    code_object_ = IndirectHandle<HeapObject>::New(
        ReadOnlyRoots(isolate).self_reference_marker(), isolate);
  }
}
MacroAssemblerBase() [4/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase [inline]
Definition at line 30 of file macro-assembler-base.h.
                                                             {})
      : MacroAssemblerBase(isolate, zone, AssemblerOptions::Default(isolate),
                           create_code_object, std::move(buffer)) {}
MacroAssemblerBase() [5/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase [inline]
Definition at line 44 of file macro-assembler-base.h.
                                                             {})
      : MacroAssemblerBase(nullptr, zone, options, create_code_object,
                           std::move(buffer)) {}
Move() [1/2]
void v8::internal::SharedMacroAssemblerBase::Move (Register dst, Register src)
Definition at line 41 of file macro-assembler-shared-ia32-x64.cc.
                                                              {
  // Helper to paper over the different assembler function names.
  if (dst != src) {
#if V8_TARGET_ARCH_IA32
    mov(dst, src);
#elif V8_TARGET_ARCH_X64
    movq(dst, src);
#else
#error Unsupported target architecture.
#endif
  }
}
References v8::internal::Assembler::mov(), and v8::internal::Assembler::movq().
Move() [2/2]
void v8::internal::SharedMacroAssemblerBase::Move (Register dst, uint32_t src)
Definition at line 30 of file macro-assembler-shared-ia32-x64.cc.
                                                              {
  // Helper to paper over the different assembler function names.
#if V8_TARGET_ARCH_IA32
  mov(dst, Immediate(src));
#elif V8_TARGET_ARCH_X64
  movl(dst, Immediate(src));
#else
#error Unsupported target architecture.
#endif
}
References v8::internal::Assembler::mov(), and v8::internal::Assembler::movl().
Referenced by I64x2ShrS(), I8x16Shl(), I8x16ShrS(), and I8x16ShrU().
Movhps()
void v8::internal::SharedMacroAssemblerBase::Movhps (XMMRegister dst, XMMRegister src1, Operand src2)
Definition at line 80 of file macro-assembler-shared-ia32-x64.cc.
                                                    {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vmovhps(dst, src1, src2);
  } else {
    if (dst != src1) {
      movaps(dst, src1);
    }
    movhps(dst, src2);
  }
}
References v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::movhps(), and v8::internal::Assembler::vmovhps().
Referenced by S128Store64Lane().
Movlps()
void v8::internal::SharedMacroAssemblerBase::Movlps (XMMRegister dst, XMMRegister src1, Operand src2)
Definition at line 93 of file macro-assembler-shared-ia32-x64.cc.
                                                    {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vmovlps(dst, src1, src2);
  } else {
    if (dst != src1) {
      movaps(dst, src1);
    }
    movlps(dst, src2);
  }
}
References v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::movlps(), and v8::internal::Assembler::vmovlps().
Referenced by S128Store64Lane().
Pblendvb()
void v8::internal::SharedMacroAssemblerBase::Pblendvb (XMMRegister dst, XMMRegister src1, XMMRegister src2, XMMRegister mask)
Definition at line 131 of file macro-assembler-shared-ia32-x64.cc.
                                                                            {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope scope(this, AVX);
    vpblendvb(dst, src1, src2, mask);
  } else {
    CpuFeatureScope scope(this, SSE4_1);
    DCHECK_EQ(mask, xmm0);
    DCHECK_EQ(dst, src1);
    pblendvb(dst, src2);
  }
}
References DCHECK_EQ, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vpblendvb().
Pinsrb()
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::Pinsrb (XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t * load_pc_offset = nullptr) [inline]
Definition at line 132 of file macro-assembler-shared-ia32-x64.h.
                                                  {
    PinsrHelper(this, &Assembler::vpinsrb, &Assembler::pinsrb, dst, src1, src2,
                imm8, load_pc_offset, {SSE4_1});
  }
References v8::internal::Assembler::pinsrb(), and v8::internal::Assembler::vpinsrb().
PinsrHelper()
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::PinsrHelper (Assembler * assm, AvxFn< Op > avx, NoAvxFn< Op > noavx, XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t * load_pc_offset = nullptr, std::optional< CpuFeature > feature = std::nullopt) [inline], [protected]
Definition at line 575 of file macro-assembler-shared-ia32-x64.h.
                                                                 {
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope scope(assm, AVX);
      if (load_pc_offset) *load_pc_offset = assm->pc_offset();
      (assm->*avx)(dst, src1, src2, imm8);
      return;
    }
    if (dst != src1) assm->movaps(dst, src1);
    if (load_pc_offset) *load_pc_offset = assm->pc_offset();
    if (feature.has_value()) {
      DCHECK(CpuFeatures::IsSupported(*feature));
      CpuFeatureScope scope(assm, *feature);
      (assm->*noavx)(dst, src2, imm8);
    } else {
      (assm->*noavx)(dst, src2, imm8);
    }
  }
References v8::internal::DCHECK(), v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), and v8::internal::AssemblerBase::pc_offset().
Pinsrw()
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::Pinsrw (XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t * load_pc_offset = nullptr) [inline]
Definition at line 139 of file macro-assembler-shared-ia32-x64.h.
                                                  {
    PinsrHelper(this, &Assembler::vpinsrw, &Assembler::pinsrw, dst, src1, src2,
                imm8, load_pc_offset);
  }
References v8::internal::Assembler::pinsrw(), and v8::internal::Assembler::vpinsrw().
Pshufb() [1/2]
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::Pshufb (XMMRegister dst, Op mask) [inline]
Definition at line 163 of file macro-assembler-shared-ia32-x64.h.
                                        {
    Pshufb(dst, dst, mask);
  }
Pshufb() [2/2]
template<typename Op >
void v8::internal::SharedMacroAssemblerBase::Pshufb (XMMRegister dst, XMMRegister src, Op mask) [inline]
Definition at line 147 of file macro-assembler-shared-ia32-x64.h.
                                                         {
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      vpshufb(dst, src, mask);
    } else {
      // Make sure these are different so that we won't overwrite mask.
      DCHECK_NE(mask, dst);
      if (dst != src) {
        movaps(dst, src);
      }
      CpuFeatureScope sse_scope(this, SSSE3);
      pshufb(dst, mask);
    }
  }
References DCHECK_NE, and v8::internal::CpuFeatures::IsSupported().
Referenced by I8x16SplatPreAvx2().
S128Load16Splat()
void v8::internal::SharedMacroAssemblerBase::S128Load16Splat (XMMRegister dst, Operand src, XMMRegister scratch)
Definition at line 1263 of file macro-assembler-shared-ia32-x64.cc.
                                                                    {
  ASM_CODE_COMMENT(this);
  // The trap handler uses the current pc to creating a landing, so that it can
  // determine if a trap occured in Wasm code due to a OOB load. Make sure the
  // first instruction in each case below is the one that loads.
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    vpbroadcastw(dst, src);
  } else if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // Avoid dependency on previous value of dst.
    vpinsrw(dst, scratch, src, uint8_t{0});
    vpshuflw(dst, dst, uint8_t{0});
    vpunpcklqdq(dst, dst, dst);
  } else {
    pinsrw(dst, src, uint8_t{0});
    pshuflw(dst, dst, uint8_t{0});
    movlhps(dst, dst);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movlhps(), v8::internal::Assembler::pinsrw(), v8::internal::Assembler::pshuflw(), v8::internal::Assembler::vpinsrw(), and v8::internal::Assembler::vpshuflw().
S128Load32Splat()
void v8::internal::SharedMacroAssemblerBase::S128Load32Splat (XMMRegister dst, Operand src)
Definition at line 1285 of file macro-assembler-shared-ia32-x64.cc.
                                                                           {
  ASM_CODE_COMMENT(this);
  // The trap handler uses the current pc to creating a landing, so that it can
  // determine if a trap occured in Wasm code due to a OOB load. Make sure the
  // first instruction in each case below is the one that loads.
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vbroadcastss(dst, src);
  } else {
    movss(dst, src);
    shufps(dst, dst, uint8_t{0});
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movss(), v8::internal::Assembler::shufps(), and v8::internal::Assembler::vbroadcastss().
S128Load8Splat()
void v8::internal::SharedMacroAssemblerBase::S128Load8Splat (XMMRegister dst, Operand src, XMMRegister scratch)
Definition at line 1240 of file macro-assembler-shared-ia32-x64.cc.
                                                                   {
  ASM_CODE_COMMENT(this);
  // The trap handler uses the current pc to creating a landing, so that it can
  // determine if a trap occured in Wasm code due to a OOB load. Make sure the
  // first instruction in each case below is the one that loads.
  if (CpuFeatures::IsSupported(AVX2)) {
    CpuFeatureScope avx2_scope(this, AVX2);
    vpbroadcastb(dst, src);
  } else if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    // Avoid dependency on previous value of dst.
    vpinsrb(dst, scratch, src, uint8_t{0});
    vpxor(scratch, scratch, scratch);
    vpshufb(dst, dst, scratch);
  } else {
    CpuFeatureScope ssse4_scope(this, SSE4_1);
    pinsrb(dst, src, uint8_t{0});
    xorps(scratch, scratch);
    pshufb(dst, scratch);
  }
}
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::pinsrb(), and v8::internal::Assembler::vpinsrb().
S128Not()
void v8::internal::SharedMacroAssemblerBase::S128Not (XMMRegister dst, XMMRegister src, XMMRegister scratch)
Definition at line 1207 of file macro-assembler-shared-ia32-x64.cc.
                                                            {
  ASM_CODE_COMMENT(this);
  if (dst == src) {
    Pcmpeqd(scratch, scratch);
    Pxor(dst, scratch);
  } else {
    Pcmpeqd(dst, dst);
    Pxor(dst, src);
  }
}
References ASM_CODE_COMMENT.
S128Select()
void v8::internal::SharedMacroAssemblerBase::S128Select (XMMRegister dst, XMMRegister mask, XMMRegister src1, XMMRegister src2, XMMRegister scratch)
Definition at line 1219 of file macro-assembler-shared-ia32-x64.cc.
                                                               {
  ASM_CODE_COMMENT(this);
  // v128.select = v128.or(v128.and(v1, c), v128.andnot(v2, c)).
  // pandn(x, y) = !x & y, so we have to flip the mask and input.
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vpandn(scratch, mask, src2);
    vpand(dst, src1, mask);
    vpor(dst, dst, scratch);
  } else {
    DCHECK_EQ(dst, mask);
    // Use float ops as they are 1 byte shorter than int ops.
    movaps(scratch, mask);
    andnps(scratch, src2);
    andps(dst, src1);
    orps(dst, scratch);
  }
}
References ASM_CODE_COMMENT, DCHECK_EQ, v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::movaps().
S128Store32Lane()
void v8::internal::SharedMacroAssemblerBase::S128Store32Lane (Operand dst, XMMRegister src, uint8_t laneidx)
Definition at line 381 of file macro-assembler-shared-ia32-x64.cc.
                                                                {
  ASM_CODE_COMMENT(this);
  if (laneidx == 0) {
    Movss(dst, src);
  } else {
    DCHECK_GE(3, laneidx);
    Extractps(dst, src, laneidx);
  }
}
References ASM_CODE_COMMENT, and DCHECK_GE.
S128Store64Lane()
void v8::internal::SharedMacroAssemblerBase::S128Store64Lane (Operand dst, XMMRegister src, uint8_t laneidx)
Definition at line 1299 of file macro-assembler-shared-ia32-x64.cc.
                                                                {
  ASM_CODE_COMMENT(this);
  if (laneidx == 0) {
    Movlps(dst, src);
  } else {
    DCHECK_EQ(1, laneidx);
    Movhps(dst, src);
  }
}
References ASM_CODE_COMMENT, DCHECK_EQ, Movhps(), and Movlps().
Shufps()
void v8::internal::SharedMacroAssemblerBase::Shufps (XMMRegister dst, XMMRegister src1, XMMRegister src2, uint8_t imm8)
Definition at line 144 of file macro-assembler-shared-ia32-x64.cc.
                                                                      {
  if (CpuFeatures::IsSupported(AVX)) {
    CpuFeatureScope avx_scope(this, AVX);
    vshufps(dst, src1, src2, imm8);
  } else {
    if (dst != src1) {
      movaps(dst, src1);
    }
    shufps(dst, src2, imm8);
  }
}
References v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::movaps(), v8::internal::Assembler::shufps(), and v8::internal::Assembler::vshufps().
Referenced by F32x4ExtractLane().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/shared-ia32-x64/macro-assembler-shared-ia32-x64.h
/mnt/V8SourceCode/src/codegen/shared-ia32-x64/macro-assembler-shared-ia32-x64.cc