v8::internal::maglev::TestUndetectable Class Reference
#include <maglev-ir.h>
Public Member Functions
TestUndetectable (uint64_t bitfield, CheckType check_type)
Input & value ()
CheckType check_type () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, TestUndetectable >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Additional Inherited Members
Detailed Description
Definition at line 5069 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TestUndetectable::Base = FixedInputValueNodeT<1, TestUndetectable> [private]
Definition at line 5070 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::TestUndetectable::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 5089 of file maglev-ir.h.
Constructor & Destructor Documentation
TestUndetectable()
v8::internal::maglev::TestUndetectable::TestUndetectable (uint64_t bitfield, CheckType check_type) [inline], [explicit]
Definition at line 5073 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)) {}
Member Function Documentation
check_type()
CheckType v8::internal::maglev::TestUndetectable::check_type () const [inline]
Definition at line 5080 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by options(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::TestUndetectable::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::TestUndetectable::options () const [inline]
Definition at line 5086 of file maglev-ir.h.
{ return std::tuple{check_type()}; }
References check_type().
PrintParams()
void v8::internal::maglev::TestUndetectable::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5084 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::TestUndetectable::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::TestUndetectable::value () [inline]
Definition at line 5079 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TestUndetectable::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 5077 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h