v8::base::ConditionVariable Class Reference
#include <condition-variable.h>
Public Member Functions
ConditionVariable ()
ConditionVariable (const ConditionVariable &)=delete
ConditionVariable & operator= (const ConditionVariable &)=delete
~ConditionVariable ()
void NotifyOne ()
void NotifyAll ()
void Wait (Mutex *mutex)
bool WaitFor (Mutex *mutex, const TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
Private Attributes
absl::CondVar native_handle_
Detailed Description
Definition at line 37 of file condition-variable.h.
Constructor & Destructor Documentation
ConditionVariable() [1/2]
v8::base::ConditionVariable::ConditionVariable () [default]
ConditionVariable() [2/2]
v8::base::ConditionVariable::ConditionVariable (const ConditionVariable &) [delete]
 ConditionVariable()
v8::base::ConditionVariable::~ConditionVariable () [default]
Member Function Documentation
NotifyAll()
void v8::base::ConditionVariable::NotifyAll ()
Definition at line 25 of file condition-variable.cc.
{ native_handle_.SignalAll(); }
References native_handle_.
Referenced by v8::internal::Sweeper::AddSweptPage(), v8::internal::CollectionBarrier::CancelCollectionAndResumeThreads(), v8::internal::OptimizingCompileTaskExecutor::ClearTaskState(), v8::internal::wasm::NativeModuleCache::Erase(), v8::internal::Sweeper::NotifyPromotedPageIterationFinished(), v8::internal::Sweeper::NotifyPromotedPagesIterationFinished(), v8::internal::CollectionBarrier::NotifyShutdownRequested(), v8::internal::CollectionBarrier::ResumeThreadsAwaitingCollection(), v8::internal::wasm::NativeModuleCache::StreamingCompilationFailed(), and v8::internal::wasm::NativeModuleCache::Update().
NotifyOne()
void v8::base::ConditionVariable::NotifyOne ()
Definition at line 23 of file condition-variable.cc.
{ native_handle_.Signal(); }
References native_handle_.
Referenced by v8::platform::DefaultJobState::DidRunTask(), v8::internal::LazyCompileDispatcher::DoBackgroundWork(), v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::Notify(), v8::internal::FutexWaitListNode::NotifyWake(), v8::platform::DefaultForegroundTaskRunner::PostDelayedTaskLocked(), v8::platform::DefaultForegroundTaskRunner::PostTaskLocked(), v8::internal::OperationsBarrier::Release(), v8::internal::CancelableTaskManager::RemoveFinishedTask(), v8::internal::ProfilerEventsProcessor::StopSynchronously(), v8::internal::CancelableTaskManager::TryAbort(), and v8::internal::FutexEmulation::Wake().
operator=()
ConditionVariable& v8::base::ConditionVariable::operator= (const ConditionVariable &) [delete]
Wait()
void v8::base::ConditionVariable::Wait (Mutex * mutex)
Definition at line 27 of file condition-variable.cc.
                                         {
  mutex->AssertHeldAndUnmark();
  native_handle_.Wait(&mutex->native_handle_);
  mutex->AssertUnheldAndMark();
}
References v8::base::Mutex::AssertHeldAndUnmark(), v8::base::Mutex::AssertUnheldAndMark(), native_handle_, and v8::base::Mutex::native_handle_.
Referenced by v8::internal::CollectionBarrier::AwaitCollectionBackground(), v8::platform::DefaultJobState::CancelAndWait(), v8::internal::CancelableTaskManager::CancelAndWait(), v8::internal::OperationsBarrier::CancelAndWait(), v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIterationImpl(), v8::platform::DefaultJobState::Join(), v8::internal::wasm::NativeModuleCache::MaybeGetNativeModule(), v8::internal::LazyCompileDispatcher::WaitForJobIfRunningOnBackground(), v8::internal::Sweeper::WaitForPageToBeSwept(), v8::platform::DefaultForegroundTaskRunner::WaitForTaskLocked(), v8::internal::FutexEmulation::WaitSync(), and v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate().
WaitFor()
bool v8::base::ConditionVariable::WaitFor (Mutex * mutex, const TimeDelta & rel_time)
Definition at line 33 of file condition-variable.cc.
                                                                       {
  uint64_t time = rel_time.InNanoseconds();
  absl::Duration duration = absl::Nanoseconds(time);
  mutex->AssertHeldAndUnmark();
  bool timed_out =
      native_handle_.WaitWithTimeout(&mutex->native_handle_, duration);
  mutex->AssertUnheldAndMark();
  return !timed_out;
}
References v8::base::Mutex::AssertHeldAndUnmark(), v8::base::Mutex::AssertUnheldAndMark(), v8::internal::duration, v8::base::TimeDelta::InNanoseconds(), native_handle_, v8::base::Mutex::native_handle_, and time().
Referenced by v8::internal::SamplingEventsProcessor::Run(), v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::WaitFor(), v8::platform::DefaultForegroundTaskRunner::WaitForTaskLocked(), and v8::internal::FutexEmulation::WaitSync().
Member Data Documentation
native_handle_
absl::CondVar v8::base::ConditionVariable::native_handle_ [private]
Definition at line 70 of file condition-variable.h.
Referenced by NotifyAll(), NotifyOne(), Wait(), and WaitFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/condition-variable.h
/mnt/V8SourceCode/src/base/platform/condition-variable.cc