v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner Class Reference
Public Member Functions
YoungStringForwardingTableCleaner (Heap *heap)
void ProcessYoungObjects ()
Private Member Functions
void ClearNonLiveYoungObjects (StringForwardingTable::Record *record)
Additional Inherited Members
Detailed Description
Definition at line 460 of file minor-mark-sweep.cc.
Constructor & Destructor Documentation
YoungStringForwardingTableCleaner()
v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::YoungStringForwardingTableCleaner (Heap * heap) [inline], [explicit]
Definition at line 463 of file minor-mark-sweep.cc.
      : StringForwardingTableCleanerBase(heap) {}
Member Function Documentation
ClearNonLiveYoungObjects()
void v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ClearNonLiveYoungObjects (StringForwardingTable::Record * record) [inline], [private]
Definition at line 480 of file minor-mark-sweep.cc.
                                                                     {
    Tagged<Object> original = record->OriginalStringObject(isolate_);
    if (!IsHeapObject(original)) {
      DCHECK_EQ(original, StringForwardingTable::deleted_element());
      return;
    }
    Tagged<String> original_string = Cast<String>(original);
    if (!HeapLayout::InYoungGeneration(original_string)) return;
    if (!marking_state_->IsMarked(original_string)) {
      DisposeExternalResource(record);
      record->set_original_string(StringForwardingTable::deleted_element());
    }
  }
References DCHECK_EQ, v8::internal::StringForwardingTable::deleted_element(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::IsHeapObject(), v8::internal::StringForwardingTable::Record::OriginalStringObject(), and v8::internal::StringForwardingTable::Record::set_original_string().
ProcessYoungObjects()
void v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ProcessYoungObjects () [inline]
Definition at line 469 of file minor-mark-sweep.cc.
                             {
    DCHECK(v8_flags.always_use_string_forwarding_table);
    StringForwardingTable* forwarding_table =
        isolate_->string_forwarding_table();
    forwarding_table->IterateElements(
        [&](StringForwardingTable::Record* record) {
          ClearNonLiveYoungObjects(record);
        });
  }
References v8::internal::DCHECK(), v8::internal::StringForwardingTable::IterateElements(), and v8::internal::v8_flags.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/minor-mark-sweep.cc