v8::internal::DoubleRegister Class Reference
#include <register-ppc.h>
Public Member Functions
Simd128Register toSimd () const
Static Public Member Functions
static int SupportedRegisterCount ()
static int SupportedRegisterCount ()
Static Public Attributes
static constexpr int kSizeInBytes = 8
Private Member Functions
constexpr DoubleRegister (int code)
constexpr DoubleRegister (int code)
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 234 of file register-ppc.h.
Constructor & Destructor Documentation
DoubleRegister() [1/2]
constexpr v8::internal::DoubleRegister::DoubleRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 258 of file register-ppc.h.
: RegisterBase(code) {}
DoubleRegister() [2/2]
constexpr v8::internal::DoubleRegister::DoubleRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 202 of file register-s390.h.
: RegisterBase(code) {}
Member Function Documentation
SupportedRegisterCount() [1/2]
int v8::internal::DoubleRegister::SupportedRegisterCount () [inline], [static]
Definition at line 54 of file assembler-arm-inl.h.
                                           {
  return CpuFeatures::IsSupported(VFP32DREGS) ? 32 : 16;
}
References v8::internal::CpuFeatures::IsSupported().
SupportedRegisterCount() [2/2]
static int v8::internal::DoubleRegister::SupportedRegisterCount () [inline], [static]
toSimd()
Simd128Register v8::internal::DoubleRegister::toSimd () const [inline]
Definition at line 250 of file register-ppc.h.
                                 {
    int reg_code = code();
    V8_ASSUME(reg_code >= 0 && reg_code < kSimd128AfterLast);
    return Simd128Register(reg_code);
  }
References v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::code(), v8::internal::kSimd128AfterLast, and V8_ASSUME.
Referenced by v8::internal::wasm::liftoff::StoreToMemory().
Friends And Related Function Documentation
RegisterBase
RegisterBase [friend]
Definition at line 257 of file register-ppc.h.
Member Data Documentation
kSizeInBytes
static constexpr int v8::internal::DoubleRegister::kSizeInBytes = 8 [static], [constexpr]
Definition at line 240 of file register-ppc.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/ppc/register-ppc.h
/mnt/V8SourceCode/src/codegen/s390/register-s390.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h