v8::internal::ForEachStatement Class Reference
#include <ast.h>
Public Types
enum VisitMode { ENUMERATE
, ITERATE
 }
Public Member Functions
void Initialize (Expression *each, Expression *subject, Statement *body, Scope *subject_scope)
Expression * each () const
Expression * subject () const
Scope * subject_scope () const
void Initialize (Statement *body)
Static Public Member Functions
static const char * VisitModeString (VisitMode mode)
Protected Member Functions
ForEachStatement (int pos, NodeType type)
Protected Attributes
friend Zone
Expression * each_
Expression * subject_
Scope * subject_scope_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 522 of file ast.h.
Member Enumeration Documentation
VisitMode
enum v8::internal::ForEachStatement::VisitMode
Enumerator
ENUMERATE
ITERATE
Definition at line 524 of file ast.h.
                 {
    ENUMERATE, // for (each in subject) body;
    ITERATE // for (each of subject) body;
  };
Constructor & Destructor Documentation
ForEachStatement()
v8::internal::ForEachStatement::ForEachStatement (int pos, NodeType type) [inline], [protected]
Definition at line 555 of file ast.h.
      : IterationStatement(pos, type),
        each_(nullptr),
        subject_(nullptr),
        subject_scope_(nullptr) {}
Member Function Documentation
each()
Expression* v8::internal::ForEachStatement::each () const [inline]
Definition at line 543 of file ast.h.
{ return each_; }
References each_.
Referenced by v8::internal::interpreter::BytecodeGenerator::ForInScope::ForInScope(), and Initialize().
Initialize() [1/2]
void v8::internal::ForEachStatement::Initialize (Expression * each, Expression * subject, Statement * body, Scope * subject_scope) [inline]
Definition at line 535 of file ast.h.
                                        {
    IterationStatement::Initialize(body);
    each_ = each;
    subject_ = subject;
    subject_scope_ = subject_scope;
  }
References v8::internal::IterationStatement::body(), each(), each_, v8::internal::IterationStatement::Initialize(), subject(), subject_, subject_scope(), and subject_scope_.
Initialize() [2/2]
void v8::internal::IterationStatement::Initialize [inline]
Definition at line 445 of file ast.h.
{ body_ = body; }
subject()
Expression* v8::internal::ForEachStatement::subject () const [inline]
Definition at line 544 of file ast.h.
{ return subject_; }
References subject_.
Referenced by Initialize().
subject_scope()
Scope* v8::internal::ForEachStatement::subject_scope () const [inline]
Definition at line 549 of file ast.h.
{ return subject_scope_; }
References subject_scope_.
Referenced by Initialize().
VisitModeString()
static const char* v8::internal::ForEachStatement::VisitModeString (VisitMode mode) [inline], [static]
Definition at line 531 of file ast.h.
                                                     {
    return mode == ITERATE ? "for-of" : "for-in";
  }
References ITERATE, and mode().
Referenced by v8::internal::ParserBase< Impl >::ParseForEachStatementWithDeclarations().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 552 of file ast.h.
Member Data Documentation
each_
Expression* v8::internal::ForEachStatement::each_ [protected]
Definition at line 561 of file ast.h.
Referenced by each(), and Initialize().
subject_
Expression* v8::internal::ForEachStatement::subject_ [protected]
Definition at line 562 of file ast.h.
Referenced by Initialize(), and subject().
subject_scope_
Scope* v8::internal::ForEachStatement::subject_scope_ [protected]
Definition at line 563 of file ast.h.
Referenced by Initialize(), and subject_scope().
Zone
friend v8::internal::ForEachStatement::Zone [protected]
Definition at line 553 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h