v8::internal::RunningStringHasher Class Reference
#include <string-hasher.h>
Public Member Functions
RunningStringHasher (uint32_t seed)
void AddCharacter (uint16_t c)
uint32_t Finalize ()
Private Attributes
uint32_t running_hash_
Detailed Description
Definition at line 21 of file string-hasher.h.
Constructor & Destructor Documentation
RunningStringHasher()
v8::internal::RunningStringHasher::RunningStringHasher (uint32_t seed) [inline], [explicit]
Definition at line 23 of file string-hasher.h.
: running_hash_(seed) {}
Member Function Documentation
AddCharacter()
void v8::internal::RunningStringHasher::AddCharacter (uint16_t c) [inline]
Definition at line 77 of file string-hasher-inl.h.
                                                 {
  running_hash_ += c;
  running_hash_ += (running_hash_ << 10);
  running_hash_ ^= (running_hash_ >> 6);
}
References running_hash_.
Referenced by v8::internal::Heap::AllocationTrackerForDebugging::UpdateAllocationsHash().
Finalize()
uint32_t v8::internal::RunningStringHasher::Finalize () [inline]
Definition at line 83 of file string-hasher-inl.h.
                                       {
  running_hash_ += (running_hash_ << 3);
  running_hash_ ^= (running_hash_ >> 11);
  running_hash_ += (running_hash_ << 15);
  return detail::ConvertRawHashToUsableHash(running_hash_);
}
References v8::internal::detail::ConvertRawHashToUsableHash(), and running_hash_.
Referenced by v8::internal::Heap::AllocationTrackerForDebugging::PrintAllocationsHash().
Member Data Documentation
running_hash_
uint32_t v8::internal::RunningStringHasher::running_hash_ [private]
Definition at line 29 of file string-hasher.h.
Referenced by AddCharacter(), and Finalize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/string-hasher.h
/mnt/V8SourceCode/src/strings/string-hasher-inl.h