v8::internal::AssemblerRISCVZicsr Class Reference
#include <extension-riscv-zicsr.h>
Public Member Functions
void csrrw (Register rd, ControlStatusReg csr, Register rs1)
void csrrs (Register rd, ControlStatusReg csr, Register rs1)
void csrrc (Register rd, ControlStatusReg csr, Register rs1)
void csrrwi (Register rd, ControlStatusReg csr, uint8_t imm5)
void csrrsi (Register rd, ControlStatusReg csr, uint8_t imm5)
void csrrci (Register rd, ControlStatusReg csr, uint8_t imm5)
void rdinstret (Register rd)
void rdinstreth (Register rd)
void rdcycle (Register rd)
void rdcycleh (Register rd)
void rdtime (Register rd)
void rdtimeh (Register rd)
void csrr (Register rd, ControlStatusReg csr)
void csrw (ControlStatusReg csr, Register rs)
void csrs (ControlStatusReg csr, Register rs)
void csrc (ControlStatusReg csr, Register rs)
void csrwi (ControlStatusReg csr, uint8_t imm)
void csrsi (ControlStatusReg csr, uint8_t imm)
void csrci (ControlStatusReg csr, uint8_t imm)
void frcsr (Register rd)
void fscsr (Register rd, Register rs)
void fscsr (Register rs)
void frrm (Register rd)
void fsrm (Register rd, Register rs)
void fsrm (Register rs)
void frflags (Register rd)
void fsflags (Register rd, Register rs)
void fsflags (Register rs)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-zicsr.h.
Member Function Documentation
csrc()
void v8::internal::AssemblerRISCVZicsr::csrc (ControlStatusReg csr, Register rs) [inline]
Definition at line 36 of file extension-riscv-zicsr.h.
{ csrrc(zero_reg, csr, rs); }
References csrrc().
csrci()
void v8::internal::AssemblerRISCVZicsr::csrci (ControlStatusReg csr, uint8_t imm) [inline]
Definition at line 40 of file extension-riscv-zicsr.h.
{ csrrci(zero_reg, csr, imm); }
References csrrci().
csrr()
void v8::internal::AssemblerRISCVZicsr::csrr (Register rd, ControlStatusReg csr) [inline]
Definition at line 33 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr, zero_reg); }
References csrrs().
csrrc()
void v8::internal::AssemblerRISCVZicsr::csrrc (Register rd, ControlStatusReg csr, Register rs1)
Definition at line 23 of file extension-riscv-zicsr.cc.
                                              {
  GenInstrCSR_ir(0b011, rd, csr, rs1);
}
References v8::internal::AssemblerRiscvBase::GenInstrCSR_ir().
Referenced by csrc().
csrrci()
void v8::internal::AssemblerRISCVZicsr::csrrci (Register rd, ControlStatusReg csr, uint8_t imm5)
Definition at line 38 of file extension-riscv-zicsr.cc.
                                               {
  GenInstrCSR_ii(0b111, rd, csr, imm5);
}
References v8::internal::AssemblerRiscvBase::GenInstrCSR_ii().
Referenced by csrci(), and v8::internal::MacroAssembler::RoundFloatingPointToInteger().
csrrs()
void v8::internal::AssemblerRISCVZicsr::csrrs (Register rd, ControlStatusReg csr, Register rs1)
Definition at line 18 of file extension-riscv-zicsr.cc.
                                              {
  GenInstrCSR_ir(0b010, rd, csr, rs1);
}
References v8::internal::AssemblerRiscvBase::GenInstrCSR_ir().
Referenced by csrr(), csrs(), frcsr(), frflags(), frrm(), rdcycle(), rdcycleh(), rdinstret(), rdinstreth(), rdtime(), and rdtimeh().
csrrsi()
void v8::internal::AssemblerRISCVZicsr::csrrsi (Register rd, ControlStatusReg csr, uint8_t imm5)
Definition at line 33 of file extension-riscv-zicsr.cc.
                                               {
  GenInstrCSR_ii(0b110, rd, csr, imm5);
}
References v8::internal::AssemblerRiscvBase::GenInstrCSR_ii().
Referenced by csrsi().
csrrw()
void v8::internal::AssemblerRISCVZicsr::csrrw (Register rd, ControlStatusReg csr, Register rs1)
Definition at line 13 of file extension-riscv-zicsr.cc.
                                              {
  GenInstrCSR_ir(0b001, rd, csr, rs1);
}
References v8::internal::AssemblerRiscvBase::GenInstrCSR_ir().
Referenced by csrw(), fscsr(), fsflags(), and fsrm().
csrrwi()
void v8::internal::AssemblerRISCVZicsr::csrrwi (Register rd, ControlStatusReg csr, uint8_t imm5)
Definition at line 28 of file extension-riscv-zicsr.cc.
                                               {
  GenInstrCSR_ii(0b101, rd, csr, imm5);
}
References v8::internal::AssemblerRiscvBase::GenInstrCSR_ii().
Referenced by csrwi().
csrs()
void v8::internal::AssemblerRISCVZicsr::csrs (ControlStatusReg csr, Register rs) [inline]
Definition at line 35 of file extension-riscv-zicsr.h.
{ csrrs(zero_reg, csr, rs); }
References csrrs().
csrsi()
void v8::internal::AssemblerRISCVZicsr::csrsi (ControlStatusReg csr, uint8_t imm) [inline]
Definition at line 39 of file extension-riscv-zicsr.h.
{ csrrsi(zero_reg, csr, imm); }
References csrrsi().
csrw()
void v8::internal::AssemblerRISCVZicsr::csrw (ControlStatusReg csr, Register rs) [inline]
Definition at line 34 of file extension-riscv-zicsr.h.
{ csrrw(zero_reg, csr, rs); }
References csrrw().
csrwi()
void v8::internal::AssemblerRISCVZicsr::csrwi (ControlStatusReg csr, uint8_t imm) [inline]
Definition at line 38 of file extension-riscv-zicsr.h.
{ csrrwi(zero_reg, csr, imm); }
References csrrwi().
frcsr()
void v8::internal::AssemblerRISCVZicsr::frcsr (Register rd) [inline]
Definition at line 42 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_fcsr, zero_reg); }
References v8::internal::csr_fcsr, and csrrs().
frflags()
void v8::internal::AssemblerRISCVZicsr::frflags (Register rd) [inline]
Definition at line 50 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_fflags, zero_reg); }
References v8::internal::csr_fflags, and csrrs().
Referenced by v8::internal::MacroAssembler::RoundFloatingPointToInteger().
frrm()
void v8::internal::AssemblerRISCVZicsr::frrm (Register rd) [inline]
Definition at line 46 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_frm, zero_reg); }
References v8::internal::csr_frm, and csrrs().
fscsr() [1/2]
void v8::internal::AssemblerRISCVZicsr::fscsr (Register rd, Register rs) [inline]
Definition at line 43 of file extension-riscv-zicsr.h.
{ csrrw(rd, csr_fcsr, rs); }
References v8::internal::csr_fcsr, and csrrw().
fscsr() [2/2]
void v8::internal::AssemblerRISCVZicsr::fscsr (Register rs) [inline]
Definition at line 44 of file extension-riscv-zicsr.h.
{ csrrw(zero_reg, csr_fcsr, rs); }
References v8::internal::csr_fcsr, and csrrw().
fsflags() [1/2]
void v8::internal::AssemblerRISCVZicsr::fsflags (Register rd, Register rs) [inline]
Definition at line 51 of file extension-riscv-zicsr.h.
{ csrrw(rd, csr_fflags, rs); }
References v8::internal::csr_fflags, and csrrw().
fsflags() [2/2]
void v8::internal::AssemblerRISCVZicsr::fsflags (Register rs) [inline]
Definition at line 52 of file extension-riscv-zicsr.h.
{ csrrw(zero_reg, csr_fflags, rs); }
References v8::internal::csr_fflags, and csrrw().
fsrm() [1/2]
void v8::internal::AssemblerRISCVZicsr::fsrm (Register rd, Register rs) [inline]
Definition at line 47 of file extension-riscv-zicsr.h.
{ csrrw(rd, csr_frm, rs); }
References v8::internal::csr_frm, and csrrw().
fsrm() [2/2]
void v8::internal::AssemblerRISCVZicsr::fsrm (Register rs) [inline]
Definition at line 48 of file extension-riscv-zicsr.h.
{ csrrw(zero_reg, csr_frm, rs); }
References v8::internal::csr_frm, and csrrw().
rdcycle()
void v8::internal::AssemblerRISCVZicsr::rdcycle (Register rd) [inline]
Definition at line 28 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_cycle, zero_reg); }
References v8::internal::csr_cycle, and csrrs().
rdcycleh()
void v8::internal::AssemblerRISCVZicsr::rdcycleh (Register rd) [inline]
Definition at line 29 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_cycleh, zero_reg); }
References v8::internal::csr_cycleh, and csrrs().
rdinstret()
void v8::internal::AssemblerRISCVZicsr::rdinstret (Register rd) [inline]
Definition at line 26 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_instret, zero_reg); }
References v8::internal::csr_instret, and csrrs().
rdinstreth()
void v8::internal::AssemblerRISCVZicsr::rdinstreth (Register rd) [inline]
Definition at line 27 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_instreth, zero_reg); }
References v8::internal::csr_instreth, and csrrs().
rdtime()
void v8::internal::AssemblerRISCVZicsr::rdtime (Register rd) [inline]
Definition at line 30 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_time, zero_reg); }
References v8::internal::csr_time, and csrrs().
rdtimeh()
void v8::internal::AssemblerRISCVZicsr::rdtimeh (Register rd) [inline]
Definition at line 31 of file extension-riscv-zicsr.h.
{ csrrs(rd, csr_timeh, zero_reg); }
References v8::internal::csr_timeh, and csrrs().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-zicsr.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-zicsr.cc