v8::internal::maglev::CreateRegExpLiteral Class Reference
#include <maglev-ir.h>
Public Member Functions
CreateRegExpLiteral (uint64_t bitfield, compiler::StringRef pattern, const compiler::FeedbackSource &feedback, int flags)
compiler::StringRef pattern ()
compiler::FeedbackSource feedback () const
int flags () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
Private Types
using Base = FixedInputValueNodeT< 0, CreateRegExpLiteral >
Private Attributes
compiler::StringRef pattern_
const compiler::FeedbackSource feedback_
const int flags_
Additional Inherited Members
Detailed Description
Definition at line 6659 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CreateRegExpLiteral::Base = FixedInputValueNodeT<0, CreateRegExpLiteral> [private]
Definition at line 6661 of file maglev-ir.h.
Constructor & Destructor Documentation
CreateRegExpLiteral()
v8::internal::maglev::CreateRegExpLiteral::CreateRegExpLiteral (uint64_t bitfield, compiler::StringRef pattern, const compiler::FeedbackSource & feedback, int flags) [inline], [explicit]
Definition at line 6664 of file maglev-ir.h.
      : Base(bitfield), pattern_(pattern), feedback_(feedback), flags_(flags) {}
Member Function Documentation
feedback()
compiler::FeedbackSource v8::internal::maglev::CreateRegExpLiteral::feedback () const [inline]
Definition at line 6670 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
flags()
int v8::internal::maglev::CreateRegExpLiteral::flags () const [inline]
Definition at line 6671 of file maglev-ir.h.
{ return flags_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CreateRegExpLiteral::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CreateRegExpLiteral::MaxCallStackArgs () const
pattern()
compiler::StringRef v8::internal::maglev::CreateRegExpLiteral::pattern () [inline]
Definition at line 6669 of file maglev-ir.h.
{ return pattern_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CreateRegExpLiteral::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 6681 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::CreateRegExpLiteral::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::CreateRegExpLiteral::feedback_ [private]
Definition at line 6685 of file maglev-ir.h.
flags_
const int v8::internal::maglev::CreateRegExpLiteral::flags_ [private]
Definition at line 6686 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CreateRegExpLiteral::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Call() | OpProperties::CanAllocate() |
      OpProperties::NotIdempotent() | OpProperties::CanThrow()
Definition at line 6674 of file maglev-ir.h.
pattern_
compiler::StringRef v8::internal::maglev::CreateRegExpLiteral::pattern_ [private]
Definition at line 6684 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h