v8::internal::compiler::RiscvOperandConverter Class Reference
Public Member Functions
RiscvOperandConverter (CodeGenerator *gen, Instruction *instr)
FloatRegister OutputSingleRegister (size_t index=0)
FloatRegister InputSingleRegister (size_t index)
FloatRegister ToSingleRegister (InstructionOperand *op)
Register InputOrZeroRegister (size_t index)
DoubleRegister InputOrZeroDoubleRegister (size_t index)
DoubleRegister InputOrZeroSingleRegister (size_t index)
Operand InputImmediate (size_t index)
Operand InputOperand (size_t index)
MemOperand MemoryOperand (size_t *first_index)
MemOperand MemoryOperand (size_t index=0)
MemOperand ToMemOperand (InstructionOperand *op) const
MemOperand SlotToMemOperand (int slot) const
Additional Inherited Members
Detailed Description
Definition at line 32 of file code-generator-riscv.cc.
Constructor & Destructor Documentation
RiscvOperandConverter()
v8::internal::compiler::RiscvOperandConverter::RiscvOperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 34 of file code-generator-riscv.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
InputImmediate()
Operand v8::internal::compiler::RiscvOperandConverter::InputImmediate (size_t index) [inline]
Definition at line 85 of file code-generator-riscv.cc.
                                       {
    Constant constant = ToConstant(instr_->InputAt(index));
    switch (constant.type()) {
      case Constant::kInt32:
        return Operand(constant.ToInt32());
      case Constant::kInt64:
        return Operand(constant.ToInt64());
      case Constant::kFloat32:
        return Operand::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Operand::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kCompressedHeapObject: {
        RootIndex root_index;
        if (gen_->isolate()->roots_table().IsRootHandle(constant.ToHeapObject(),
                                                        &root_index)) {
          CHECK(COMPRESS_POINTERS_BOOL);
          CHECK(V8_STATIC_ROOTS_BOOL || !gen_->isolate()->bootstrapper());
          Tagged_t ptr =
              MacroAssemblerBase::ReadOnlyRootPtr(root_index, gen_->isolate());
          return Operand(ptr);
        }
        return Operand(constant.ToHeapObject());
      }
      case Constant::kExternalReference:
      case Constant::kHeapObject:
        // TODO(plind): Maybe we should handle ExtRef & HeapObj here?
        // maybe not done on arm due to const pool ??
        break;
      case Constant::kRpoNumber:
        UNREACHABLE(); // TODO(titzer): RPO immediates
    }
    UNREACHABLE();
  }
References v8::internal::Isolate::bootstrapper(), CHECK, COMPRESS_POINTERS_BOOL, v8::internal::Operand::EmbeddedNumber(), v8::internal::compiler::InstructionOperandConverter::gen_, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::CodeGenerator::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::Isolate::roots_table(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), V8_STATIC_ROOTS_BOOL, and v8::base::Double::value().
Referenced by InputOperand().
InputOperand()
Operand v8::internal::compiler::RiscvOperandConverter::InputOperand (size_t index) [inline]
Definition at line 119 of file code-generator-riscv.cc.
                                     {
    InstructionOperand* op = instr_->InputAt(index);
    if (op->IsRegister()) {
      return Operand(ToRegister(op));
    }
    return InputImmediate(index);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), InputImmediate(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::InstructionOperand::IsRegister(), and v8::internal::compiler::InstructionOperandConverter::ToRegister().
InputOrZeroDoubleRegister()
DoubleRegister v8::internal::compiler::RiscvOperandConverter::InputOrZeroDoubleRegister (size_t index) [inline]
Definition at line 73 of file code-generator-riscv.cc.
                                                         {
    if (instr_->InputAt(index)->IsImmediate()) return kDoubleRegZero;
    return InputDoubleRegister(index);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::kDoubleRegZero.
InputOrZeroRegister()
Register v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister (size_t index) [inline]
Definition at line 51 of file code-generator-riscv.cc.
                                             {
    if (instr_->InputAt(index)->IsImmediate()) {
      Constant constant = ToConstant(instr_->InputAt(index));
      switch (constant.type()) {
        case Constant::kInt32:
        case Constant::kInt64:
          DCHECK_EQ(0, InputInt32(index));
          break;
        case Constant::kFloat32:
          DCHECK_EQ(0, base::bit_cast<int32_t>(InputFloat32(index)));
          break;
        case Constant::kFloat64:
          DCHECK_EQ(0, base::bit_cast<int64_t>(InputDouble(index)));
          break;
        default:
          UNREACHABLE();
      }
      return zero_reg;
    }
    return InputRegister(index);
  }
References DCHECK_EQ, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::InputDouble(), v8::internal::compiler::InstructionOperandConverter::InputFloat32(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::type(), and v8::internal::UNREACHABLE().
InputOrZeroSingleRegister()
DoubleRegister v8::internal::compiler::RiscvOperandConverter::InputOrZeroSingleRegister (size_t index) [inline]
Definition at line 79 of file code-generator-riscv.cc.
                                                         {
    if (instr_->InputAt(index)->IsImmediate()) return kSingleRegZero;
    return InputSingleRegister(index);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), InputSingleRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::kSingleRegZero.
InputSingleRegister()
FloatRegister v8::internal::compiler::RiscvOperandConverter::InputSingleRegister (size_t index) [inline]
Definition at line 41 of file code-generator-riscv.cc.
                                                  {
    return ToSingleRegister(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToSingleRegister().
Referenced by InputOrZeroSingleRegister().
MemoryOperand() [1/2]
MemOperand v8::internal::compiler::RiscvOperandConverter::MemoryOperand (size_t * first_index) [inline]
Definition at line 127 of file code-generator-riscv.cc.
                                                {
    const size_t index = *first_index;
    switch (AddressingModeField::decode(instr_->opcode())) {
      case kMode_None:
        break;
      case kMode_MRI:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputInt32(index + 1));
      case kMode_Root:
        return MemOperand(kRootRegister, InputInt32(index));
      case kMode_MRR:
        // TODO(plind): r6 address mode, to be implemented ...
        UNREACHABLE();
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
MemoryOperand() [2/2]
MemOperand v8::internal::compiler::RiscvOperandConverter::MemoryOperand (size_t index = 0) [inline]
Definition at line 144 of file code-generator-riscv.cc.
{ return MemoryOperand(&index); }
References v8::internal::index, and MemoryOperand().
Referenced by MemoryOperand().
OutputSingleRegister()
FloatRegister v8::internal::compiler::RiscvOperandConverter::OutputSingleRegister (size_t index = 0) [inline]
Definition at line 37 of file code-generator-riscv.cc.
                                                       {
    return ToSingleRegister(instr_->OutputAt(index));
  }
References v8::internal::index, v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Instruction::OutputAt(), and ToSingleRegister().
SlotToMemOperand()
MemOperand v8::internal::compiler::RiscvOperandConverter::SlotToMemOperand (int slot) const [inline]
Definition at line 152 of file code-generator-riscv.cc.
                                              {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    return MemOperand(offset.from_stack_pointer() ? sp : fp, offset.offset());
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToMemOperand().
ToMemOperand()
MemOperand v8::internal::compiler::RiscvOperandConverter::ToMemOperand (InstructionOperand * op) const [inline]
Definition at line 146 of file code-generator-riscv.cc.
                                                        {
    DCHECK_NOT_NULL(op);
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToMemOperand(AllocatedOperand::cast(op)->index());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToMemOperand().
ToSingleRegister()
FloatRegister v8::internal::compiler::RiscvOperandConverter::ToSingleRegister (InstructionOperand * op) [inline]
Definition at line 45 of file code-generator-riscv.cc.
                                                         {
    // Single (Float) and Double register namespace is same on RISC-V,
    // both are typedefs of FPURegister.
    return ToDoubleRegister(op);
  }
References v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister().
Referenced by InputSingleRegister(), and OutputSingleRegister().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/riscv/code-generator-riscv.cc