v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value > Class Template Reference
#include <layered-hash-map.h>
Classes
struct Entry
Public Member Functions
LayeredHashMap (Zone *zone, uint32_t initial_capacity=64)
void StartLayer ()
void DropLastLayer ()
void InsertNewKey (Key key, Value value)
bool Contains (Key key)
std::optional< Value > Get (Key key)
Private Member Functions
void ResizeIfNeeded ()
size_t NextEntryIndex (size_t index)
Entry * FindEntryForKey (Key key, size_t hash=0)
Entry * InsertEntry (Entry entry)
size_t ComputeHash (Key key)
Private Attributes
size_t mask_
size_t entry_count_
base::Vector< Entry > table_
ZoneVector< Entry * > depths_heads_
Zone * zone_
Static Private Attributes
static constexpr double kNeedResizePercentage = 0.75
static constexpr int kGrowthFactor = 2
Detailed Description
template<class Key, class Value>
class v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >
Definition at line 39 of file layered-hash-map.h.
Constructor & Destructor Documentation
LayeredHashMap()
template<class Key , class Value >
v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::LayeredHashMap (Zone * zone, uint32_t initial_capacity = 64) [explicit]
Definition at line 78 of file layered-hash-map.h.
    : entry_count_(0), depths_heads_(zone), zone_(zone) {
  // Setting the minimal capacity to 16
  initial_capacity = std::max<uint32_t>(initial_capacity, 16);
  // {initial_capacity} should be a power of 2, so that we can compute offset
  // in {table_} with a mask rather than a modulo.
  initial_capacity = base::bits::RoundUpToPowerOfTwo32(initial_capacity);
  mask_ = initial_capacity - 1;
  // Allocating the table_
  table_ = zone_->NewVector<Entry>(initial_capacity);
}
References v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::mask_, v8::internal::Zone::NewVector(), v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::table_, and v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::zone_.
Member Function Documentation
ComputeHash()
template<class Key , class Value >
size_t v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::ComputeHash (Key key) [inline], [private]
Definition at line 62 of file layered-hash-map.h.
                              {
    size_t hash = fast_hash<Key>()(key);
    return V8_UNLIKELY(hash == 0) ? 1 : hash;
  }
References v8::internal::key, and V8_UNLIKELY.
Contains()
template<class Key , class Value >
bool v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Contains (Key key)
Definition at line 136 of file layered-hash-map.h.
                                                 {
  return Get(key).has_value();
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::key.
DropLastLayer()
template<class Key , class Value >
void v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::DropLastLayer
Definition at line 97 of file layered-hash-map.h.
                                               {
  DCHECK_GT(depths_heads_.size(), 0);
  for (Entry* entry = depths_heads_.back(); entry != nullptr;) {
    entry_count_--;
    Entry* next = entry->depth_neighboring_entry;
    *entry = Entry();
    entry = next;
  }
  depths_heads_.pop_back();
}
References DCHECK_GT, and v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::depth_neighboring_entry.
FindEntryForKey()
template<class Key , class Value >
LayeredHashMap< Key, Value >::Entry * v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::FindEntryForKey (Key key, size_t hash = 0) [private]
Definition at line 110 of file layered-hash-map.h.
                                                                {
  for (size_t i = hash & mask_;; i = NextEntryIndex(i)) {
    if (table_[i].hash == 0) return &table_[i];
    if (table_[i].hash == hash && table_[i].key == key) return &table_[i];
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::key.
Get()
template<class Key , class Value >
std::optional< Value > v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Get (Key key)
Definition at line 129 of file layered-hash-map.h.
                                                          {
  Entry* destination = FindEntryForKey(key, ComputeHash(key));
  if (destination->hash == 0) return std::nullopt;
  return destination->value;
}
References v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::hash, v8::internal::key, and v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::value.
InsertEntry()
template<class Key , class Value >
Entry* v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::InsertEntry (Entry entry) [private]
InsertNewKey()
template<class Key , class Value >
void v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::InsertNewKey (Key key, Value value)
Definition at line 118 of file layered-hash-map.h.
                                                                  {
  ResizeIfNeeded();
  size_t hash = ComputeHash(key);
  Entry* destination = FindEntryForKey(key, hash);
  DCHECK_EQ(destination->hash, 0);
  *destination = Entry{hash, key, value, depths_heads_.back()};
  depths_heads_.back() = destination;
  entry_count_++;
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::hash, v8::internal::key, and v8::internal::value.
NextEntryIndex()
template<class Key , class Value >
size_t v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::NextEntryIndex (size_t index) [inline], [private]
Definition at line 58 of file layered-hash-map.h.
{ return (index + 1) & mask_; }
References v8::internal::index, and v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::mask_.
ResizeIfNeeded()
template<class Key , class Value >
void v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::ResizeIfNeeded [private]
Definition at line 141 of file layered-hash-map.h.
                                                {
  if (table_.size() * kNeedResizePercentage > entry_count_) return;
  CHECK_LE(table_.size(), std::numeric_limits<size_t>::max() / kGrowthFactor);
  table_ = zone_->NewVector<Entry>(table_.size() * kGrowthFactor);
  mask_ = table_.size() - 1;
  DCHECK_EQ(base::bits::CountPopulation(mask_),
            sizeof(mask_) * 8 - base::bits::CountLeadingZeros(mask_));
  for (size_t depth_idx = 0; depth_idx < depths_heads_.size(); depth_idx++) {
    // It's important to fill the new hash by inserting data in increasing
    // depth order, in order to avoid holes when later calling DropLastLayer.
    // Consider for instance:
    //
    // ---+------+------+------+----
    // | a1 | a2 | a3 |
    // ---+------+------+------+----
    //
    // Where a1, a2 and a3 have the same hash. By construction, we know that
    // depth(a1) <= depth(a2) <= depth(a3). If, when re-hashing, we were to
    // insert them in another order, say:
    //
    // ---+------+------+------+----
    // | a3 | a1 | a2 |
    // ---+------+------+------+----
    //
    // Then, when we'll call DropLastLayer to remove entries from a3's depth,
    // we'll get this:
    //
    // ---+------+------+------+----
    // | null | a1 | a2 |
    // ---+------+------+------+----
    //
    // And, when looking if a1 is in the hash, we'd find a "null" where we
    // expect it, and assume that it's not present. If, instead, we always
    // conserve the increasing depth order, then when removing a3, we'd get:
    //
    // ---+------+------+------+----
    // | a1 | a2 | null |
    // ---+------+------+------+----
    //
    // Where we can still find a1 and a2.
    Entry* entry = depths_heads_[depth_idx];
    depths_heads_[depth_idx] = nullptr;
    while (entry != nullptr) {
      Entry* new_entry_loc = FindEntryForKey(entry->key, entry->hash);
      *new_entry_loc = *entry;
      Entry* next_entry = entry->depth_neighboring_entry;
      new_entry_loc->depth_neighboring_entry = depths_heads_[depth_idx];
      depths_heads_[depth_idx] = new_entry_loc;
      entry = next_entry;
    }
  }
}
References CHECK_LE, v8::base::bits::CountLeadingZeros(), v8::base::bits::CountPopulation(), DCHECK_EQ, v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::depth_neighboring_entry, v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::hash, and v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::Entry::key.
StartLayer()
template<class Key , class Value >
void v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::StartLayer
Definition at line 92 of file layered-hash-map.h.
                                            {
  depths_heads_.push_back(nullptr);
}
Member Data Documentation
depths_heads_
template<class Key , class Value >
ZoneVector<Entry*> v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::depths_heads_ [private]
Definition at line 70 of file layered-hash-map.h.
entry_count_
template<class Key , class Value >
size_t v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::entry_count_ [private]
Definition at line 68 of file layered-hash-map.h.
kGrowthFactor
template<class Key , class Value >
constexpr int v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::kGrowthFactor = 2 [static], [constexpr], [private]
Definition at line 74 of file layered-hash-map.h.
kNeedResizePercentage
template<class Key , class Value >
constexpr double v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::kNeedResizePercentage = 0.75 [static], [constexpr], [private]
Definition at line 73 of file layered-hash-map.h.
mask_
template<class Key , class Value >
size_t v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::mask_ [private]
Definition at line 67 of file layered-hash-map.h.
Referenced by v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::LayeredHashMap(), and v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::NextEntryIndex().
table_
template<class Key , class Value >
base::Vector<Entry> v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::table_ [private]
Definition at line 69 of file layered-hash-map.h.
Referenced by v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::LayeredHashMap().
zone_
template<class Key , class Value >
Zone* v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::zone_ [private]
Definition at line 71 of file layered-hash-map.h.
Referenced by v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::LayeredHashMap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/layered-hash-map.h