v8::internal::compiler::Reduction Class Reference
#include <graph-reducer.h>
Public Member Functions
Reduction (Node *replacement=nullptr)
Node * replacement () const
bool Changed () const
Reduction FollowedBy (Reduction next) const
Private Attributes
Node * replacement_
Detailed Description
Definition at line 34 of file graph-reducer.h.
Constructor & Destructor Documentation
Reduction()
v8::internal::compiler::Reduction::Reduction (Node * replacement = nullptr) [inline], [explicit]
Definition at line 36 of file graph-reducer.h.
: replacement_(replacement) {}
Member Function Documentation
Changed()
bool v8::internal::compiler::Reduction::Changed () const [inline]
Definition at line 39 of file graph-reducer.h.
{ return replacement() != nullptr; }
References replacement().
Referenced by v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::JSBinopReduction::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::TypedOptimization::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::JSCallReducer::Finalize(), v8::internal::compiler::JSInliningHeuristic::Finalize(), FollowedBy(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::MachineOperatorReducer::Int32Add(), v8::internal::compiler::MachineOperatorReducer::Int32Sub(), v8::internal::compiler::MachineOperatorReducer::Int64Add(), v8::internal::compiler::MachineOperatorReducer::Int64Sub(), v8::internal::compiler::GraphReducer::Reduce(), v8::internal::compiler::ValueNumberingReducer::Reduce(), v8::internal::compiler::Reducer::Reduce(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadProperty(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToString(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::GraphReducer::ReduceTop(), v8::internal::compiler::DeadCodeElimination::ReduceUnreachableOrIfException(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32And(), v8::internal::compiler::MachineOperatorReducer::TruncateInt64ToInt32(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw(), v8::internal::compiler::MemoryOptimizer::VisitLoadField(), v8::internal::compiler::MachineOperatorReducer::Word32And(), and v8::internal::compiler::MachineOperatorReducer::Word64And().
FollowedBy()
Reduction v8::internal::compiler::Reduction::FollowedBy (Reduction next) const [inline]
Definition at line 40 of file graph-reducer.h.
                                             {
    if (next.Changed()) return next;
    return *this;
  }
References Changed().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::MachineOperatorReducer::ReduceConditional(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
replacement()
Node* v8::internal::compiler::Reduction::replacement () const [inline]
Definition at line 38 of file graph-reducer.h.
{ return replacement_; }
References replacement_.
Referenced by v8::internal::compiler::GraphAssembler::AddNode(), Changed(), v8::internal::compiler::JSBinopReduction::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::TypedOptimization::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::JSCallReducer::Finalize(), v8::internal::compiler::MachineOperatorReducer::Int32Add(), v8::internal::compiler::MachineOperatorReducer::Int32Sub(), v8::internal::compiler::MachineOperatorReducer::Int64Add(), v8::internal::compiler::MachineOperatorReducer::Int64Sub(), v8::internal::compiler::GraphReducer::Reduce(), v8::internal::compiler::Reducer::Reduce(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSTypedLowering::ReduceJSToString(), v8::internal::compiler::GraphReducer::ReduceTop(), v8::internal::compiler::MachineOperatorReducer::TruncateInt64ToInt32(), v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw(), v8::internal::compiler::MemoryOptimizer::VisitLoadField(), v8::internal::compiler::MemoryOptimizer::VisitLoadFromObject(), v8::internal::compiler::MachineOperatorReducer::Word32And(), and v8::internal::compiler::MachineOperatorReducer::Word64And().
Member Data Documentation
replacement_
Node* v8::internal::compiler::Reduction::replacement_ [private]
Definition at line 46 of file graph-reducer.h.
Referenced by replacement().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/graph-reducer.h