v8::internal::JavaScriptFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override=0
Tagged< JSFunction > function () const override
Tagged< Object > unchecked_function () const
Tagged< Script > script () const
Tagged< Object > context () const override
int GetActualArgumentCount () const override
void set_receiver (Tagged< Object > value)
void SetParameterValue (int index, Tagged< Object > value) const
bool IsConstructor () const override
void Iterate (RootVisitor *v) const override
void Print (StringStream *accumulator, PrintMode mode, int index) const override
virtual void GetFunctions (std::vector< Tagged< SharedFunctionInfo >> *functions) const
void GetFunctions (std::vector< Handle< SharedFunctionInfo >> *functions) const
std::tuple< Tagged< AbstractCode >, int > GetActiveCodeAndOffset () const
bool is_unoptimized () const
bool is_optimized () const
bool is_turbofan () const
Static Public Member Functions
static Register fp_register ()
static Register context_register ()
static Register constant_pool_pointer_register ()
static JavaScriptFrame * cast (StackFrame *frame)
static void PrintFunctionAndOffset (Isolate *isolate, Tagged< JSFunction > function, Tagged< AbstractCode > code, int code_offset, FILE *file, bool print_line_number)
static void PrintTop (Isolate *isolate, FILE *file, bool print_args, bool print_line_number)
static void CollectFunctionAndOffsetForICStats (Isolate *isolate, Tagged< JSFunction > function, Tagged< AbstractCode > code, int code_offset)
Protected Member Functions
JavaScriptFrame (StackFrameIteratorBase *iterator)
Address GetCallerStackPointer () const override
virtual void PrintFrameKind (StringStream *accumulator) const
Private Member Functions
Tagged< Object > function_slot_object () const
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 757 of file frames.h.
Constructor & Destructor Documentation
JavaScriptFrame()
v8::internal::JavaScriptFrame::JavaScriptFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 266 of file frames-inl.h.
    : CommonFrameWithJSLinkage(iterator) {}
Member Function Documentation
cast()
static JavaScriptFrame* v8::internal::JavaScriptFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 801 of file frames.h.
                                                  {
    DCHECK(frame->is_javascript());
    return static_cast<JavaScriptFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_javascript().
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::Debug::AllFramesOnStackAreBlackboxed(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::DebuggableStackFrameIterator::FrameFunctionCount(), v8::internal::Debug::HandleDebugBreak(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::InitSummaries(), v8::internal::FrameInspector::javascript_frame(), v8::internal::DebuggableStackFrameIterator::javascript_frame(), v8::internal::Debug::OnException(), v8::internal::Debug::PrepareStep(), v8::internal::Debug::PrepareStepOnThrow(), v8::internal::JavaScriptStackFrameIterator::Reframe(), and v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack().
CollectFunctionAndOffsetForICStats()
void v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats (Isolate * isolate, Tagged< JSFunction > function, Tagged< AbstractCode > code, int code_offset) [static]
Definition at line 2593 of file frames.cc.
                     {
  auto ic_stats = ICStats::instance();
  ICInfo& ic_info = ic_stats->Current();
  PtrComprCageBase cage_base = GetPtrComprCageBase(function);
  Tagged<SharedFunctionInfo> shared = function->shared(cage_base);
  ic_info.function_name = ic_stats->GetOrCacheFunctionName(isolate, function);
  ic_info.script_offset = code_offset;
  int source_pos = code->SourcePosition(isolate, code_offset);
  Tagged<Object> maybe_script = shared->script(cage_base, kAcquireLoad);
  if (IsScript(maybe_script, cage_base)) {
    Tagged<Script> script = Cast<Script>(maybe_script);
    Script::PositionInfo info;
    script->GetPositionInfo(source_pos, &info);
    ic_info.line_num = info.line + 1;
    ic_info.column_num = info.column + 1;
    ic_info.script_name = ic_stats->GetOrCacheScriptName(script);
  }
}
References code, v8::internal::Script::PositionInfo::column, v8::internal::ICInfo::column_num, v8::internal::ICInfo::function_name, v8::internal::GetPtrComprCageBase(), v8::internal::ICStats::instance(), v8::internal::StackFrame::isolate(), v8::kAcquireLoad, v8::internal::Script::PositionInfo::line, v8::internal::ICInfo::line_num, script(), v8::internal::ICInfo::script_name, and v8::internal::ICInfo::script_offset.
Referenced by v8::internal::IC::TraceIC().
constant_pool_pointer_register()
Register v8::internal::JavaScriptFrame::constant_pool_pointer_register () [static]
Definition at line 15 of file frame-constants-riscv.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
context()
Tagged< Object > v8::internal::JavaScriptFrame::context () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 2506 of file frames.cc.
                                              {
  const int offset = StandardFrameConstants::kContextOffset;
  Tagged<Object> maybe_result(Memory<Address>(fp() + offset));
  DCHECK(!IsSmi(maybe_result));
  return maybe_result;
}
References v8::internal::DCHECK(), v8::internal::StackFrame::fp(), v8::internal::IsSmi(), and v8::internal::StandardFrameConstants::kContextOffset.
Referenced by v8::internal::Isolate::GetIncumbentContextSlow(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::DebugEvaluate::WithTopmostArguments().
context_register()
Register v8::internal::JavaScriptFrame::context_register () [static]
Definition at line 14 of file frame-constants-riscv.cc.
{ return cp; }
References v8::internal::cp.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
fp_register()
Register v8::internal::JavaScriptFrame::fp_register () [static]
Definition at line 13 of file frame-constants-riscv.cc.
{ return v8::internal::fp; }
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeOutputFrames(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
function()
Tagged< JSFunction > v8::internal::JavaScriptFrame::function () const [override], [virtual]
Implements v8::internal::CommonFrameWithJSLinkage.
Definition at line 2488 of file frames.cc.
                                                   {
  return Cast<JSFunction>(function_slot_object());
}
References function_slot_object().
Referenced by v8::internal::SamplingHeapProfiler::AddStack(), v8::internal::AllocationTracker::AllocationEvent(), v8::internal::Isolate::GetAbstractPC(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), v8::internal::Debug::HandleDebugBreak(), v8::internal::Debug::IsBreakAtReturn(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::Debug::PrepareRestartFrame(), v8::internal::Debug::PrepareStep(), v8::internal::Debug::PrepareStepOnThrow(), PrintTop(), v8::internal::RUNTIME_FUNCTION(), v8::internal::RUNTIME_FUNCTION_RETURN_PAIR(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::IC::TraceIC(), and v8::internal::RedirectActiveFunctions::VisitThread().
function_slot_object()
Tagged< Object > v8::internal::JavaScriptFrame::function_slot_object () const [inline], [private]
Definition at line 291 of file frames-inl.h.
                                                                  {
  const int offset = StandardFrameConstants::kFunctionOffset;
  return Tagged<Object>(base::Memory<Address>(fp() + offset));
}
References v8::internal::StackFrame::fp(), v8::internal::StandardFrameConstants::kFunctionOffset, and v8::internal::Tagged< Object >.
Referenced by function(), and unchecked_function().
GetActiveCodeAndOffset()
std::tuple< Tagged< AbstractCode >, int > v8::internal::JavaScriptFrame::GetActiveCodeAndOffset () const
Definition at line 2449 of file frames.cc.
          {
  int code_offset = 0;
  Tagged<AbstractCode> abstract_code;
  if (is_interpreted()) {
    const InterpretedFrame* iframe = InterpretedFrame::cast(this);
    code_offset = iframe->GetBytecodeOffset();
    abstract_code = Cast<AbstractCode>(iframe->GetBytecodeArray());
  } else if (is_baseline()) {
    // TODO(pthier): AbstractCode should fully support Baseline code.
    const BaselineFrame* baseline_frame = BaselineFrame::cast(this);
    code_offset = baseline_frame->GetBytecodeOffset();
    abstract_code = Cast<AbstractCode>(baseline_frame->GetBytecodeArray());
  } else {
    Tagged<Code> code;
    int pc_offset = -1;
    std::tie(code, pc_offset) = LookupCodeAndOffset();
    abstract_code = Cast<AbstractCode>(code);
  }
  return {abstract_code, code_offset};
}
References v8::internal::InterpretedFrame::cast(), v8::internal::BaselineFrame::cast(), code, v8::internal::UnoptimizedJSFrame::GetBytecodeArray(), v8::internal::InterpretedFrame::GetBytecodeOffset(), v8::internal::BaselineFrame::GetBytecodeOffset(), v8::internal::StackFrame::is_baseline(), v8::internal::StackFrame::is_interpreted(), and v8::internal::StackFrame::LookupCodeAndOffset().
Referenced by PrintTop(), and v8::internal::IC::TraceIC().
GetActualArgumentCount()
int v8::internal::JavaScriptFrame::GetActualArgumentCount () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 2628 of file frames.cc.
                                                  {
  return static_cast<int>(
             Memory<intptr_t>(fp() + StandardFrameConstants::kArgCOffset)) -
         kJSArgcReceiverSlots;
}
References v8::internal::StackFrame::fp(), v8::internal::StandardFrameConstants::kArgCOffset, and v8::internal::kJSArgcReceiverSlots.
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), and v8::internal::TranslatedState::TranslatedState().
GetCallerStackPointer()
Address v8::internal::JavaScriptFrame::GetCallerStackPointer () const [override], [protected], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 2428 of file frames.cc.
                                                     {
  return fp() + StandardFrameConstants::kCallerSPOffset;
}
References v8::internal::StackFrame::fp(), and v8::internal::CommonFrameConstants::kCallerSPOffset.
GetFunctions() [1/2]
void v8::internal::JavaScriptFrame::GetFunctions (std::vector< Handle< SharedFunctionInfo >> * functions) const
Definition at line 2438 of file frames.cc.
                                                            {
  DCHECK(functions->empty());
  std::vector<Tagged<SharedFunctionInfo>> raw_functions;
  GetFunctions(&raw_functions);
  Isolate* isolate = Isolate::Current();
  for (const auto& raw_function : raw_functions) {
    functions->push_back(Handle<SharedFunctionInfo>(raw_function, isolate));
  }
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), GetFunctions(), and v8::internal::StackFrame::isolate().
GetFunctions() [2/2]
void v8::internal::JavaScriptFrame::GetFunctions (std::vector< Tagged< SharedFunctionInfo >> * functions) const [virtual]
Reimplemented in v8::internal::OptimizedJSFrame.
Definition at line 2432 of file frames.cc.
                                                            {
  DCHECK(functions->empty());
  functions->push_back(function()->shared());
}
References v8::internal::DCHECK().
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::DebuggableStackFrameIterator::FrameFunctionCount(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), GetFunctions(), v8::internal::OptimizedJSFrame::GetFunctions(), v8::internal::GetShouldThrow(), v8::internal::Debug::IsFrameBlackboxed(), v8::internal::Debug::PrepareStep(), v8::internal::Debug::PrepareStepOnThrow(), and v8::internal::DebugStackTraceIterator::UpdateInlineFrameIndexAndResumableFnOnStack().
is_optimized()
bool v8::internal::JavaScriptFrame::is_optimized () const [inline]
Definition at line 798 of file frames.h.
{ return is_optimized_js(); }
References v8::internal::StackFrame::is_optimized_js().
Referenced by v8::internal::FrameInspector::FrameInspector(), v8::internal::Debug::IsBreakAtReturn(), and v8::internal::Debug::PrepareRestartFrame().
is_turbofan()
bool v8::internal::JavaScriptFrame::is_turbofan () const [inline]
Definition at line 799 of file frames.h.
{ return is_turbofan_js(); }
References v8::internal::StackFrame::is_turbofan_js().
Referenced by v8::internal::RUNTIME_FUNCTION().
is_unoptimized()
bool v8::internal::JavaScriptFrame::is_unoptimized () const [inline]
Definition at line 797 of file frames.h.
{ return is_unoptimized_js(); }
References v8::internal::StackFrame::is_unoptimized_js().
Referenced by v8::internal::Isolate::GetAbstractPC(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::ScopeIterator::SetLocalVariableValue().
IsConstructor()
bool v8::internal::JavaScriptFrame::IsConstructor () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 2410 of file frames.cc.
                                          {
  return IsConstructFrame(caller_fp());
}
References v8::internal::CommonFrame::caller_fp(), and v8::internal::CommonFrameWithJSLinkage::IsConstructFrame().
Referenced by PrintTop(), and v8::internal::DebugEvaluate::WithTopmostArguments().
Iterate()
void v8::internal::JavaScriptFrame::Iterate (RootVisitor * v) const [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::TurbofanJSFrame, and v8::internal::MaglevFrame.
Definition at line 4094 of file frames.cc.
                                                  {
  // The frame contains the actual argument count (intptr) that should not be
  // visited.
  FullObjectSlot argc(
      &Memory<Address>(fp() + StandardFrameConstants::kArgCOffset));
  const int last_object_offset = StandardFrameConstants::kLastObjectOffset;
  FullObjectSlot base(&Memory<Address>(sp()));
  FullObjectSlot limit(&Memory<Address>(fp() + last_object_offset) + 1);
  v->VisitRootPointers(Root::kStackRoots, nullptr, base, argc);
  v->VisitRootPointers(Root::kStackRoots, nullptr, argc + 1, limit);
  IteratePc(v, constant_pool_address(), GcSafeLookupCode());
}
References v8::internal::StandardFrameConstants::kArgCOffset, v8::internal::StandardFrameConstants::kLastObjectOffset, and v8::internal::RootVisitor::VisitRootPointers().
Print()
void v8::internal::JavaScriptFrame::Print (StringStream * accumulator, PrintMode mode, int index) const [override], [virtual]
Reimplemented from v8::internal::StackFrame.
Definition at line 3967 of file frames.cc.
                                             {
  DirectHandle<SharedFunctionInfo> shared(function()->shared(), isolate());
  SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate(), shared);
  DisallowGarbageCollection no_gc;
  Tagged<Object> receiver = this->receiver();
  Tagged<JSFunction> function = this->function();
  accumulator->PrintSecurityTokenIfChanged(isolate(), function);
  PrintIndex(accumulator, mode, index);
  PrintFrameKind(accumulator);
  if (IsConstructor()) accumulator->Add("new ");
  accumulator->PrintFunction(isolate(), function, receiver);
  accumulator->Add(" [%p]", function);
  // Get scope information for nicer output, if possible. If code is nullptr, or
  // doesn't contain scope info, scope_info will return 0 for the number of
  // parameters, stack local variables, context local variables, stack slots,
  // or context slots.
  Tagged<ScopeInfo> scope_info = shared->scope_info();
  Tagged<Object> script_obj = shared->script();
  if (IsScript(script_obj)) {
    Tagged<Script> script = Cast<Script>(script_obj);
    accumulator->Add(" [");
    accumulator->PrintName(script->name());
    if (is_interpreted()) {
      const InterpretedFrame* iframe = InterpretedFrame::cast(this);
      Tagged<BytecodeArray> bytecodes = iframe->GetBytecodeArray();
      int offset = iframe->GetBytecodeOffset();
      int source_pos = bytecodes->SourcePosition(offset);
      int line = script->GetLineNumber(source_pos) + 1;
      accumulator->Add(":%d] [bytecode=%p offset=%d]", line,
                       reinterpret_cast<void*>(bytecodes.ptr()), offset);
    } else {
      int function_start_pos = shared->StartPosition();
      int line = script->GetLineNumber(function_start_pos) + 1;
      accumulator->Add(":~%d] [pc=%p]", line, reinterpret_cast<void*>(pc()));
    }
  }
  accumulator->Add("(this=%o", receiver);
  // Print the parameters.
  int parameters_count = ComputeParametersCount();
  for (int i = 0; i < parameters_count; i++) {
    accumulator->Add(",");
    accumulator->Add("%o", GetParameter(i));
  }
  accumulator->Add(")");
  if (mode == OVERVIEW) {
    accumulator->Add("\n");
    return;
  }
  if (is_optimized()) {
    accumulator->Add(" {\n// optimized frame\n");
    PrintFunctionSource(accumulator, *shared);
    accumulator->Add("}\n");
    return;
  }
  accumulator->Add(" {\n");
  // Compute the number of locals and expression stack elements.
  int heap_locals_count = scope_info->ContextLocalCount();
  int expressions_count = ComputeExpressionsCount();
  // Try to get hold of the context of this frame.
  Tagged<Context> context;
  if (IsContext(this->context())) {
    context = Cast<Context>(this->context());
    while (context->IsWithContext()) {
      context = context->previous();
      DCHECK(!context.is_null());
    }
  }
  // Print heap-allocated local variables.
  if (heap_locals_count > 0) {
    accumulator->Add(" // heap-allocated locals\n");
  }
  for (auto it : ScopeInfo::IterateLocalNames(scope_info, no_gc)) {
    accumulator->Add(" var ");
    accumulator->PrintName(it->name());
    accumulator->Add(" = ");
    if (!context.is_null()) {
      int slot_index = Context::MIN_CONTEXT_SLOTS + it->index();
      if (slot_index < context->length()) {
        accumulator->Add("%o", context->get(slot_index, kRelaxedLoad));
      } else {
        accumulator->Add(
            "// warning: missing context slot - inconsistent frame?");
      }
    } else {
      accumulator->Add("// warning: no context found - inconsistent frame?");
    }
    accumulator->Add("\n");
  }
  // Print the expression stack.
  if (0 < expressions_count) {
    accumulator->Add(" // expression stack (top to bottom)\n");
  }
  for (int i = expressions_count - 1; i >= 0; i--) {
    accumulator->Add(" [%02d] : %o\n", i, GetExpression(i));
  }
  PrintFunctionSource(accumulator, *shared);
  accumulator->Add("}\n\n");
}
References v8::internal::StringStream::Add(), v8::internal::InterpretedFrame::cast(), v8::internal::DCHECK(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::UnoptimizedJSFrame::GetBytecodeArray(), v8::internal::InterpretedFrame::GetBytecodeOffset(), v8::internal::index, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::ScopeInfo::IterateLocalNames(), v8::kRelaxedLoad, v8::internal::length, v8::internal::Context::MIN_CONTEXT_SLOTS, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StringStream::PrintFunction(), v8::internal::anonymous_namespace{frames.cc}::PrintFunctionSource(), v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), v8::internal::StringStream::PrintName(), v8::internal::StringStream::PrintSecurityTokenIfChanged(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FrameSummary::receiver(), and v8::internal::FrameSummary::script().
PrintFrameKind()
virtual void v8::internal::JavaScriptFrame::PrintFrameKind (StringStream * accumulator) const [inline], [protected], [virtual]
Definition at line 824 of file frames.h.
{}
PrintFunctionAndOffset()
void v8::internal::JavaScriptFrame::PrintFunctionAndOffset (Isolate * isolate, Tagged< JSFunction > function, Tagged< AbstractCode > code, int code_offset, FILE * file, bool print_line_number) [static]
Definition at line 2528 of file frames.cc.
                                                                     {
  PtrComprCageBase cage_base = GetPtrComprCageBase(function);
  PrintF(file, "%s", CodeKindToMarker(code->kind(cage_base), false));
  function->PrintName(file);
  PrintF(file, "+%d", code_offset);
  if (print_line_number) {
    Tagged<SharedFunctionInfo> shared = function->shared();
    int source_pos = code->SourcePosition(isolate, code_offset);
    Tagged<Object> maybe_script = shared->script();
    if (IsScript(maybe_script)) {
      Tagged<Script> script = Cast<Script>(maybe_script);
      int line = script->GetLineNumber(source_pos) + 1;
      Tagged<Object> script_name_raw = script->name();
      if (IsString(script_name_raw)) {
        Tagged<String> script_name = Cast<String>(script->name());
        std::unique_ptr<char[]> c_script_name = script_name->ToCString();
        PrintF(file, " at %s:%d", c_script_name.get(), line);
      } else {
        PrintF(file, " at <unknown>:%d", line);
      }
    } else {
      PrintF(file, " at <unknown>:<unknown>");
    }
  }
}
References code, v8::internal::CodeKindToMarker(), file(), v8::internal::GetPtrComprCageBase(), v8::internal::StackFrame::isolate(), v8::internal::PrintF(), and script().
Referenced by PrintTop().
PrintTop()
void v8::internal::JavaScriptFrame::PrintTop (Isolate * isolate, FILE * file, bool print_args, bool print_line_number) [static]
Definition at line 2558 of file frames.cc.
                                                       {
  // constructor calls
  DisallowGarbageCollection no_gc;
  JavaScriptStackFrameIterator it(isolate);
  while (!it.done()) {
    if (it.frame()->is_javascript()) {
      JavaScriptFrame* frame = it.frame();
      if (frame->IsConstructor()) PrintF(file, "new ");
      Tagged<JSFunction> function = frame->function();
      int code_offset = 0;
      Tagged<AbstractCode> code;
      std::tie(code, code_offset) = frame->GetActiveCodeAndOffset();
      PrintFunctionAndOffset(isolate, function, code, code_offset, file,
                             print_line_number);
      if (print_args) {
        // function arguments
        // (we are intentionally only printing the actually
        // supplied parameters, not all parameters required)
        PrintF(file, "(this=");
        ShortPrint(frame->receiver(), file);
        const int length = frame->ComputeParametersCount();
        for (int i = 0; i < length; i++) {
          PrintF(file, ", ");
          ShortPrint(frame->GetParameter(i), file);
        }
        PrintF(file, ")");
      }
      break;
    }
    it.Advance();
  }
}
References v8::internal::JavaScriptStackFrameIterator::Advance(), code, v8::internal::CommonFrameWithJSLinkage::ComputeParametersCount(), v8::internal::JavaScriptStackFrameIterator::done(), file(), v8::internal::JavaScriptStackFrameIterator::frame(), function(), GetActiveCodeAndOffset(), v8::internal::CommonFrameWithJSLinkage::GetParameter(), v8::internal::StackFrame::is_javascript(), IsConstructor(), v8::internal::StackFrame::isolate(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), PrintFunctionAndOffset(), v8::internal::CommonFrameWithJSLinkage::receiver(), and v8::internal::ShortPrint().
Referenced by v8::internal::JSObject::PrintElementsTransition(), v8::internal::anonymous_namespace{map-updater.cc}::PrintGeneralization(), v8::internal::anonymous_namespace{map-updater.cc}::PrintReconfiguration(), and v8::internal::RUNTIME_FUNCTION().
script()
Tagged< Script > v8::internal::JavaScriptFrame::script () const
Definition at line 2513 of file frames.cc.
                                             {
  return Cast<Script>(function()->shared()->script());
}
Referenced by CollectFunctionAndOffsetForICStats(), and PrintFunctionAndOffset().
set_receiver()
void v8::internal::JavaScriptFrame::set_receiver (Tagged< Object > value) [inline]
Definition at line 281 of file frames-inl.h.
                                                              {
  base::Memory<Address>(GetParameterSlot(-1)) = value.ptr();
}
References v8::internal::CommonFrameWithJSLinkage::GetParameterSlot(), and v8::internal::value.
SetParameterValue()
void v8::internal::JavaScriptFrame::SetParameterValue (int index, Tagged< Object > value) const
Definition at line 2406 of file frames.cc.
                                                                             {
  Memory<Address>(GetParameterSlot(index)) = value.ptr();
}
References v8::internal::CommonFrameWithJSLinkage::GetParameterSlot(), v8::internal::index, and v8::internal::value.
Referenced by v8::internal::ScopeIterator::SetLocalVariableValue().
type()
Type v8::internal::JavaScriptFrame::type () const [override], [pure virtual]
Implements v8::internal::StackFrame.
Implemented in v8::internal::TurbofanJSFrame, v8::internal::MaglevFrame, v8::internal::BaselineFrame, and v8::internal::InterpretedFrame.
unchecked_function()
Tagged< Object > v8::internal::JavaScriptFrame::unchecked_function () const
Definition at line 2492 of file frames.cc.
                                                         {
  // During deoptimization of an optimized function, we may have yet to
  // materialize some closures on the stack. The arguments marker object
  // marks this case.
  DCHECK(IsJSFunction(function_slot_object()) ||
         ReadOnlyRoots(isolate()).arguments_marker() == function_slot_object());
  return function_slot_object();
}
References v8::internal::DCHECK(), function_slot_object(), and v8::internal::StackFrame::isolate().
Referenced by v8::internal::SamplingHeapProfiler::AddStack().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 829 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc
/mnt/V8SourceCode/src/execution/riscv/frame-constants-riscv.cc