v8::internal::ZoneSnapshot Class Reference
#include <zone.h>
Public Member Functions
void Restore (Zone *zone) const
Private Member Functions
ZoneSnapshot (const Zone *zone)
Private Attributes
const size_t allocation_size_
const size_t segment_bytes_allocated_
const Address position_
const Address limit_
Segment *const segment_head_
Friends
class Zone
Detailed Description
Definition at line 283 of file zone.h.
Constructor & Destructor Documentation
ZoneSnapshot()
v8::internal::ZoneSnapshot::ZoneSnapshot (const Zone * zone) [explicit], [private]
Definition at line 201 of file zone.cc.
    :
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
      allocation_size_for_tracing_(zone->allocation_size_for_tracing_),
      freed_size_for_tracing_(zone->freed_size_for_tracing_),
#endif
      allocation_size_(zone->allocation_size_),
      segment_bytes_allocated_(zone->segment_bytes_allocated_),
      position_(zone->position_),
      limit_(zone->limit_),
      segment_head_(zone->segment_head_) {
}
Member Function Documentation
Restore()
void v8::internal::ZoneSnapshot::Restore (Zone * zone) const
Definition at line 214 of file zone.cc.
                                           {
  // Release segments up to the stored segment_head_.
  Segment* current = zone->segment_head_;
  while (current != segment_head_) {
    // If this check failed, then either you passed a wrong zone, or the zone
    // was reset to an earlier snapshot already. We cannot move forward again.
    CHECK_NOT_NULL(current);
    Segment* next = current->next();
    zone->ReleaseSegment(current);
    current = next;
  }
  // Un-poison the trailing segment content so we can reuse or zap it later.
  if (segment_head_ != nullptr) {
    void* const start = reinterpret_cast<void*>(position_);
    DCHECK_GE(start, reinterpret_cast<void*>(current->start()));
    DCHECK_LE(start, reinterpret_cast<void*>(current->end()));
    const size_t length = current->end() - reinterpret_cast<Address>(start);
    ASAN_UNPOISON_MEMORY_REGION(start, length);
  }
  // Reset the Zone to the stored state.
  zone->allocation_size_ = allocation_size_;
  zone->segment_bytes_allocated_ = segment_bytes_allocated_;
  zone->position_ = position_;
  zone->limit_ = limit_;
  zone->segment_head_ = segment_head_;
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
  zone->allocation_size_for_tracing_ = allocation_size_for_tracing_;
  zone->freed_size_for_tracing_ = freed_size_for_tracing_;
#endif
}
References v8::internal::Zone::allocation_size_, allocation_size_, ASAN_UNPOISON_MEMORY_REGION, CHECK_NOT_NULL, DCHECK_GE, DCHECK_LE, v8::internal::Segment::end(), v8::internal::length, v8::internal::Zone::limit_, limit_, v8::internal::Segment::next(), v8::internal::Zone::position_, position_, v8::internal::Zone::ReleaseSegment(), v8::internal::Zone::segment_bytes_allocated_, segment_bytes_allocated_, v8::internal::Zone::segment_head_, segment_head_, and v8::internal::Segment::start().
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup(), and v8::internal::ZoneScope::~ZoneScope().
Friends And Related Function Documentation
Zone
friend class Zone [friend]
Definition at line 291 of file zone.h.
Member Data Documentation
allocation_size_
const size_t v8::internal::ZoneSnapshot::allocation_size_ [private]
Definition at line 297 of file zone.h.
Referenced by Restore().
limit_
const Address v8::internal::ZoneSnapshot::limit_ [private]
Definition at line 300 of file zone.h.
Referenced by Restore().
position_
const Address v8::internal::ZoneSnapshot::position_ [private]
Definition at line 299 of file zone.h.
Referenced by Restore().
segment_bytes_allocated_
const size_t v8::internal::ZoneSnapshot::segment_bytes_allocated_ [private]
Definition at line 298 of file zone.h.
Referenced by Restore().
segment_head_
Segment* const v8::internal::ZoneSnapshot::segment_head_ [private]
Definition at line 301 of file zone.h.
Referenced by Restore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/zone/zone.h
/mnt/V8SourceCode/src/zone/zone.cc