v8::internal::wasm::CanonicalStructType Class Reference
#include <struct-types.h>
Public Types
using Builder = StructTypeBase::BuilderImpl< CanonicalStructType, CanonicalValueType >
Public Member Functions
CanonicalStructType (uint32_t field_count, uint32_t *field_offsets, const CanonicalValueType *reps, const bool *mutabilities, bool is_descriptor, bool is_shared)
CanonicalValueType field (uint32_t index) const
bool operator== (const CanonicalStructType &other) const
base::iterator_range< const CanonicalValueType * > fields () const
Additional Inherited Members
Detailed Description
Definition at line 273 of file struct-types.h.
Member Typedef Documentation
Builder
using v8::internal::wasm::CanonicalStructType::Builder = StructTypeBase::BuilderImpl<CanonicalStructType, CanonicalValueType>
Definition at line 275 of file struct-types.h.
Constructor & Destructor Documentation
CanonicalStructType()
v8::internal::wasm::CanonicalStructType::CanonicalStructType (uint32_t field_count, uint32_t * field_offsets, const CanonicalValueType * reps, const bool * mutabilities, bool is_descriptor, bool is_shared) [inline]
Definition at line 278 of file struct-types.h.
      : StructTypeBase(field_count, field_offsets, reps, mutabilities,
                       is_descriptor, is_shared) {}
Member Function Documentation
field()
CanonicalValueType v8::internal::wasm::CanonicalStructType::field (uint32_t index) const [inline]
Definition at line 284 of file struct-types.h.
                                                 {
    return CanonicalValueType{StructTypeBase::field(index)};
  }
References v8::internal::wasm::StructTypeBase::field(), and v8::internal::index.
fields()
base::iterator_range<const CanonicalValueType*> v8::internal::wasm::CanonicalStructType::fields () const [inline]
Definition at line 298 of file struct-types.h.
                                                               {
    const CanonicalValueType* cast_reps =
        static_cast<const CanonicalValueType*>(reps_);
    return {cast_reps, cast_reps + field_count_};
  }
References v8::internal::wasm::StructTypeBase::field_count_, and v8::internal::wasm::StructTypeBase::reps_.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualStructType(), and operator==().
operator==()
bool v8::internal::wasm::CanonicalStructType::operator== (const CanonicalStructType & other) const [inline]
Definition at line 288 of file struct-types.h.
                                                          {
    if (this == &other) return true;
    if (field_count() != other.field_count()) return false;
    if (is_descriptor() != other.is_descriptor()) return false;
    return std::equal(fields().begin(), fields().end(),
                      other.fields().begin()) &&
           std::equal(mutabilities().begin(), mutabilities().end(),
                      other.mutabilities().begin());
  }
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::equal, v8::internal::wasm::StructTypeBase::field_count(), fields(), v8::internal::wasm::StructTypeBase::is_descriptor(), and v8::internal::wasm::StructTypeBase::mutabilities().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h