v8::WasmModuleObject Class Reference
#include <v8-wasm.h>
Public Member Functions
WasmModuleObject ()=delete
CompiledWasmModule GetCompiledModule ()
Get the compiled module for this module object.
Static Public Member Functions
static MaybeLocal< WasmModuleObject > FromCompiledModule (Isolate *isolate, const CompiledWasmModule &)
Efficiently re-create a WasmModuleObject, without recompiling, from a CompiledWasmModule.
static MaybeLocal< WasmModuleObject > Compile (Isolate *isolate, MemorySpan< const uint8_t > wire_bytes)
Compile a Wasm module from the provided uncompiled bytes.
static WasmModuleObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
Definition at line 91 of file v8-wasm.h.
Constructor & Destructor Documentation
WasmModuleObject()
v8::WasmModuleObject::WasmModuleObject () [delete]
Member Function Documentation
Cast()
static WasmModuleObject* v8::WasmModuleObject::Cast (Value * value) [inline], [static]
Definition at line 114 of file v8-wasm.h.
                                                        {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<WasmModuleObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::WasmModuleObject::CheckCast (Value * obj) [static], [private]
Definition at line 4002 of file api.cc.
                                              {
  Utils::ApiCheck(that->IsWasmModuleObject(), "v8::WasmModuleObject::Cast",
                  "Value is not a WasmModuleObject");
}
References v8::Utils::ApiCheck(), and v8::Value::IsWasmModuleObject().
Compile()
MaybeLocal< WasmModuleObject > v8::WasmModuleObject::Compile (Isolate * isolate, MemorySpan< const uint8_t > wire_bytes) [static]
Compile a Wasm module from the provided uncompiled bytes.
Definition at line 8844 of file api.cc.
                                                               {
#if V8_ENABLE_WEBASSEMBLY
  base::OwnedVector<const uint8_t> bytes = base::OwnedCopyOf(wire_bytes);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  // We don't check for `IsWasmCodegenAllowed` here, because this function is
  // used for ESM integration, which in terms of security is equivalent to
  // <script> tags rather than to {eval}.
  i::MaybeDirectHandle<i::WasmModuleObject> maybe_compiled;
  {
    i::wasm::ErrorThrower thrower(i_isolate, "WasmModuleObject::Compile()");
    auto enabled_features =
        i::wasm::WasmEnabledFeatures::FromIsolate(i_isolate);
    // TODO(14179): Provide an API method that supports compile options.
    maybe_compiled = i::wasm::GetWasmEngine()->SyncCompile(
        i_isolate, enabled_features, i::wasm::CompileTimeImports{}, &thrower,
        std::move(bytes));
  }
  CHECK_EQ(maybe_compiled.is_null(), i_isolate->has_exception());
  if (maybe_compiled.is_null()) return {};
  return Utils::ToLocal(maybe_compiled.ToHandleChecked());
#else
  Utils::ApiCheck(false, "WasmModuleObject::Compile",
                  "WebAssembly support is not enabled");
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::Utils::ApiCheck(), CHECK_EQ, v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::has_exception(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::base::OwnedCopyOf(), v8::internal::wasm::WasmEngine::SyncCompile(), v8::internal::MaybeDirectHandle< T >::ToHandleChecked(), and UNREACHABLE.
Referenced by v8::Shell::FetchModuleSource().
FromCompiledModule()
MaybeLocal< WasmModuleObject > v8::WasmModuleObject::FromCompiledModule (Isolate * isolate, const CompiledWasmModule & compiled_module) [static]
Efficiently re-create a WasmModuleObject, without recompiling, from a CompiledWasmModule.
Definition at line 8830 of file api.cc.
                                                                    {
#if V8_ENABLE_WEBASSEMBLY
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DirectHandle<i::WasmModuleObject> module_object =
      i::wasm::GetWasmEngine()->ImportNativeModule(
          i_isolate, compiled_module.native_module_,
          base::VectorOf(compiled_module.source_url()));
  return Utils::ToLocal(module_object);
#else
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::WasmEngine::ImportNativeModule(), v8::CompiledWasmModule::native_module_, v8::CompiledWasmModule::source_url(), UNREACHABLE, and v8::base::VectorOf().
Referenced by v8::Deserializer::GetWasmModuleFromId().
GetCompiledModule()
CompiledWasmModule v8::WasmModuleObject::GetCompiledModule ()
Get the compiled module for this module object.
The compiled module can be shared by several module objects.
Definition at line 8816 of file api.cc.
                                                       {
#if V8_ENABLE_WEBASSEMBLY
  auto obj = i::Cast<i::WasmModuleObject>(Utils::OpenDirectHandle(this));
  auto url = i::direct_handle(i::Cast<i::String>(obj->script()->name()),
                              i::Isolate::Current());
  size_t length;
  std::unique_ptr<char[]> cstring = url->ToCString(&length);
  return CompiledWasmModule(std::move(obj->shared_native_module()),
                            cstring.get(), length);
#else
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::length, v8::Utils::OpenDirectHandle(), and UNREACHABLE.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-wasm.h
/mnt/V8SourceCode/src/api/api.cc