v8::internal::compiler::Variable Class Reference
#include <escape-analysis.h>
Public Member Functions
Variable ()
bool operator== (Variable other) const
bool operator!= (Variable other) const
bool operator< (Variable other) const
Static Public Member Functions
static Variable Invalid ()
Private Types
using Id = int
Private Member Functions
Variable (Id id)
Private Attributes
Id id_
Static Private Attributes
static const Id kInvalid = -1
Friends
class VariableTracker
size_t hash_value (Variable v)
std::ostream & operator<< (std::ostream &os, Variable var)
Detailed Description
Definition at line 83 of file escape-analysis.h.
Member Typedef Documentation
Id
using v8::internal::compiler::Variable::Id = int [private]
Definition at line 98 of file escape-analysis.h.
Constructor & Destructor Documentation
Variable() [1/2]
v8::internal::compiler::Variable::Variable () [inline]
Definition at line 85 of file escape-analysis.h.
: id_(kInvalid) {}
Referenced by Invalid().
Variable() [2/2]
v8::internal::compiler::Variable::Variable (Id id) [inline], [explicit], [private]
Definition at line 99 of file escape-analysis.h.
: id_(id) {}
Member Function Documentation
Invalid()
static Variable v8::internal::compiler::Variable::Invalid () [inline], [static]
Definition at line 89 of file escape-analysis.h.
{ return Variable(kInvalid); }
References kInvalid, and Variable().
Referenced by v8::internal::compiler::VariableTracker::State::Get(), and v8::internal::compiler::VariableTracker::State::Set().
operator!=()
bool v8::internal::compiler::Variable::operator!= (Variable other) const [inline]
Definition at line 87 of file escape-analysis.h.
{ return id_ != other.id_; }
References id_.
operator<()
bool v8::internal::compiler::Variable::operator< (Variable other) const [inline]
Definition at line 88 of file escape-analysis.h.
{ return id_ < other.id_; }
References id_.
operator==()
bool v8::internal::compiler::Variable::operator== (Variable other) const [inline]
Definition at line 86 of file escape-analysis.h.
{ return id_ == other.id_; }
References id_.
Friends And Related Function Documentation
hash_value
size_t hash_value (Variable v) [friend]
Definition at line 90 of file escape-analysis.h.
                                                 {
    return base::hash_value(v.id_);
  }
operator<<
std::ostream& operator<< (std::ostream & os, Variable var) [friend]
Definition at line 93 of file escape-analysis.h.
                                                              {
    return os << var.id_;
  }
VariableTracker
friend class VariableTracker [friend]
Definition at line 103 of file escape-analysis.h.
Member Data Documentation
id_
Id v8::internal::compiler::Variable::id_ [private]
Definition at line 100 of file escape-analysis.h.
Referenced by v8::internal::compiler::VariableTracker::MergeInputs(), operator!=(), operator<(), and operator==().
kInvalid
const Id v8::internal::compiler::Variable::kInvalid = -1 [static], [private]
Definition at line 101 of file escape-analysis.h.
Referenced by Invalid().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.h