v8::internal::WasmExportedFunctionData Class Reference
#include <wasm-objects.h>
Public Types
using BodyDescriptor = StackedBodyDescriptor< SubclassBodyDescriptor< WasmFunctionData::BodyDescriptor, FixedBodyDescriptorFor< WasmExportedFunctionData > >, WithProtectedPointer< kProtectedInstanceDataOffset >, WithStrongCodePointer< kCWrapperCodeOffset > >
Public Member Functions
wasm::CanonicalTypeIndex sig_index () const
bool is_promising () const
bool MatchesSignature (wasm::CanonicalTypeIndex other_canonical_sig_index)
Detailed Description
Definition at line 1100 of file wasm-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::WasmExportedFunctionData::BodyDescriptor = StackedBodyDescriptor< SubclassBodyDescriptor<WasmFunctionData::BodyDescriptor, FixedBodyDescriptorFor<WasmExportedFunctionData> >, WithProtectedPointer<kProtectedInstanceDataOffset>, WithStrongCodePointer<kCWrapperCodeOffset> >
Definition at line 1120 of file wasm-objects.h.
Member Function Documentation
is_promising()
bool v8::internal::WasmExportedFunctionData::is_promising () const [inline]
Definition at line 479 of file wasm-objects-inl.h.
                                                  {
  return WasmFunctionData::PromiseField::decode(js_promise_flags()) ==
         wasm::kPromise;
}
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::wasm::kPromise.
MatchesSignature()
bool v8::internal::WasmExportedFunctionData::MatchesSignature (wasm::CanonicalTypeIndex other_canonical_sig_index)
Definition at line 3059 of file wasm-objects.cc.
                                                       {
  return wasm::GetTypeCanonicalizer()->IsCanonicalSubtype(
      sig_index(), other_canonical_type_index);
}
References v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::TypeCanonicalizer::IsCanonicalSubtype(), and sig_index().
sig_index()
kWasmInternalFunctionIndirectPointerTag kProtectedInstanceDataOffset const wasm::CanonicalSig kSigOffset wasm::CanonicalTypeIndex v8::internal::WasmExportedFunctionData::sig_index () const [inline]
Definition at line 474 of file wasm-objects-inl.h.
                                                                 {
  return wasm::CanonicalTypeIndex{
      static_cast<uint32_t>(canonical_type_index())};
}
Referenced by MatchesSignature().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc