v8::internal::IntegerLiteral Class Reference
#include <integer-literal.h>
Public Member Functions
IntegerLiteral (bool negative, uint64_t absolute_value)
template<typename T >
IntegerLiteral (T value)
bool is_negative () const
uint64_t absolute_value () const
template<typename T >
bool IsRepresentableAs () const
template<typename T >
T To () const
template<typename T >
std::optional< T > TryTo () const
int Compare (const IntegerLiteral &other) const
std::string ToString () const
Private Member Functions
template<typename T >
IntegerLiteral (T value, bool perform_dcheck)
Private Attributes
bool negative_
uint64_t absolute_value_
Detailed Description
Definition at line 15 of file integer-literal.h.
Constructor & Destructor Documentation
IntegerLiteral() [1/3]
v8::internal::IntegerLiteral::IntegerLiteral (bool negative, uint64_t absolute_value) [inline]
Definition at line 17 of file integer-literal.h.
      : negative_(negative), absolute_value_(absolute_value) {
    if (absolute_value == 0) negative_ = false;
  }
References absolute_value(), and negative_.
Referenced by IsRepresentableAs().
IntegerLiteral() [2/3]
template<typename T >
v8::internal::IntegerLiteral::IntegerLiteral (T value) [inline], [explicit]
Definition at line 23 of file integer-literal.h.
: IntegerLiteral(value, true) {}
IntegerLiteral() [3/3]
template<typename T >
v8::internal::IntegerLiteral::IntegerLiteral (T value, bool perform_dcheck) [inline], [explicit], [private]
Definition at line 68 of file integer-literal.h.
                                                        : negative_(false) {
    static_assert(std::is_integral_v<T>, "Integral type required");
    absolute_value_ = static_cast<uint64_t>(value);
    if (value < T(0)) {
      negative_ = true;
      absolute_value_ = ~absolute_value_ + 1;
    }
    if (perform_dcheck) DCHECK_EQ(To<T>(), value);
  }
References absolute_value_, DCHECK_EQ, negative_, T, and v8::internal::value.
Member Function Documentation
absolute_value()
uint64_t v8::internal::IntegerLiteral::absolute_value () const [inline]
Definition at line 26 of file integer-literal.h.
{ return absolute_value_; }
References absolute_value_.
Referenced by IntegerLiteral(), v8::internal::operator+(), v8::internal::operator<<(), v8::internal::operator|(), and v8::internal::torque::ImplementationVisitor::Visit().
Compare()
int v8::internal::IntegerLiteral::Compare (const IntegerLiteral & other) const [inline]
Definition at line 53 of file integer-literal.h.
                                                 {
    if (absolute_value_ == other.absolute_value_) {
      if (absolute_value_ == 0 || negative_ == other.negative_) return 0;
      return negative_ ? -1 : 1;
    } else if (absolute_value_ < other.absolute_value_) {
      return other.negative_ ? 1 : -1;
    } else {
      return negative_ ? -1 : 1;
    }
  }
References absolute_value_, and negative_.
Referenced by IsRepresentableAs(), v8::internal::operator!=(), and v8::internal::operator==().
is_negative()
bool v8::internal::IntegerLiteral::is_negative () const [inline]
Definition at line 25 of file integer-literal.h.
{ return negative_; }
References negative_.
Referenced by v8::internal::operator+(), v8::internal::operator<<(), v8::internal::operator|(), and v8::internal::torque::ImplementationVisitor::Visit().
IsRepresentableAs()
template<typename T >
bool v8::internal::IntegerLiteral::IsRepresentableAs () const [inline]
Definition at line 29 of file integer-literal.h.
                                 {
    static_assert(std::is_integral_v<T>, "Integral type required");
    static_assert(sizeof(T) <= sizeof(uint64_t),
                  "Types with more than 64 bits are not supported");
    return Compare(IntegerLiteral(std::numeric_limits<T>::min(), false)) >= 0 &&
           Compare(IntegerLiteral(std::numeric_limits<T>::max(), false)) <= 0;
  }
References Compare(), and IntegerLiteral().
To()
template<typename T >
T v8::internal::IntegerLiteral::To () const [inline]
Definition at line 38 of file integer-literal.h.
               {
    static_assert(std::is_integral_v<T>, "Integral type required");
    DCHECK(IsRepresentableAs<T>());
    uint64_t v = absolute_value_;
    if (negative_) v = ~v + 1;
    return static_cast<T>(v);
  }
References absolute_value_, v8::internal::DCHECK(), and negative_.
ToString()
std::string v8::internal::IntegerLiteral::ToString () const [inline]
Definition at line 14 of file integer-literal-inl.h.
                                                {
  if (negative_) return std::string("-") + std::to_string(absolute_value_);
  return std::to_string(absolute_value_);
}
References absolute_value_, negative_, and v8::internal::string.
Referenced by v8::internal::operator<<().
TryTo()
template<typename T >
std::optional<T> v8::internal::IntegerLiteral::TryTo () const [inline]
Definition at line 47 of file integer-literal.h.
                               {
    static_assert(std::is_integral_v<T>, "Integral type required");
    if (!IsRepresentableAs<T>()) return std::nullopt;
    return To<T>();
  }
Member Data Documentation
absolute_value_
uint64_t v8::internal::IntegerLiteral::absolute_value_ [private]
Definition at line 79 of file integer-literal.h.
Referenced by absolute_value(), Compare(), IntegerLiteral(), To(), and ToString().
negative_
bool v8::internal::IntegerLiteral::negative_ [private]
Definition at line 78 of file integer-literal.h.
Referenced by Compare(), IntegerLiteral(), is_negative(), To(), and ToString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/numbers/integer-literal.h
/mnt/V8SourceCode/src/numbers/integer-literal-inl.h