v8::internal::wasm::WireBytesRef Class Reference
#include <wasm-module.h>
Public Member Functions
constexpr WireBytesRef ()=default
constexpr WireBytesRef (uint32_t offset, uint32_t length)
uint32_t offset () const
uint32_t length () const
uint32_t end_offset () const
bool is_empty () const
bool is_set () const
Private Attributes
uint32_t offset_ = 0
uint32_t length_ = 0
Detailed Description
Definition at line 60 of file wasm-module.h.
Constructor & Destructor Documentation
WireBytesRef() [1/2]
constexpr v8::internal::wasm::WireBytesRef::WireBytesRef () [constexpr], [default]
WireBytesRef() [2/2]
constexpr v8::internal::wasm::WireBytesRef::WireBytesRef (uint32_t offset, uint32_t length) [inline], [constexpr]
Definition at line 63 of file wasm-module.h.
      : offset_(offset), length_(length) {
    DCHECK_IMPLIES(offset_ == 0, length_ == 0);
    DCHECK_LE(offset_, offset_ + length_); // no uint32_t overflow.
  }
References DCHECK_IMPLIES, DCHECK_LE, length_, and offset_.
Member Function Documentation
end_offset()
uint32_t v8::internal::wasm::WireBytesRef::end_offset () const [inline]
Definition at line 71 of file wasm-module.h.
{ return offset_ + length_; }
References length_, and offset_.
Referenced by v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::GetContainingWasmFunction(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), v8::internal::wasm::ModuleDisassembler::PrintString(), v8::internal::wasm::PrintStringAsJSON(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::wasm::ValidateAndSetBuiltinImports(), and v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded().
is_empty()
bool v8::internal::wasm::WireBytesRef::is_empty () const [inline]
Definition at line 72 of file wasm-module.h.
{ return length_ == 0; }
References length_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames(), v8::internal::wasm::WasmCode::LogCode(), and v8::internal::wasm::InstanceBuilder::SanitizeImports().
is_set()
bool v8::internal::wasm::WireBytesRef::is_set () const [inline]
Definition at line 73 of file wasm-module.h.
{ return offset_ != 0; }
References offset_.
Referenced by v8::internal::WasmModuleObject::GetModuleNameOrNull(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::wasm::NamesProvider::PrintDataSegmentName(), v8::internal::wasm::NamesProvider::PrintElementSegmentName(), v8::internal::wasm::NamesProvider::PrintFieldName(), v8::internal::wasm::NamesProvider::PrintFunctionName(), v8::internal::wasm::NamesProvider::PrintGlobalName(), v8::internal::wasm::NamesProvider::PrintLabelName(), v8::internal::wasm::NamesProvider::PrintLocalName(), v8::internal::wasm::NamesProvider::PrintMemoryName(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::NamesProvider::PrintTableName(), v8::internal::wasm::NamesProvider::PrintTagName(), and v8::internal::wasm::NamesProvider::PrintTypeName().
length()
uint32_t v8::internal::wasm::WireBytesRef::length () const [inline]
Definition at line 70 of file wasm-module.h.
{ return length_; }
References length_.
Referenced by v8::internal::wasm::ModuleWireBytes::BoundsCheck(), v8::internal::wasm::NamesProvider::ComputeExportName(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), and v8::internal::wasm::NamesProvider::WriteRef().
offset()
uint32_t v8::internal::wasm::WireBytesRef::offset () const [inline]
Definition at line 69 of file wasm-module.h.
{ return offset_; }
References offset_.
Referenced by v8::internal::wasm::ModuleWireBytes::BoundsCheck(), v8::internal::wasm::NamesProvider::ComputeExportName(), v8::internal::wasm::DecodedNameSection::DecodedNameSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::DisassembleFunctionImpl(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::WasmCompilationUnit::ExecuteCompilation(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::GetContainingWasmFunction(), v8::internal::wasm::ModuleWireBytes::GetNameOrNull(), v8::internal::WasmScript::GetPossibleBreakpoints(), v8::internal::WasmTrustedInstanceData::InitDataSegmentArrays(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed(), v8::internal::wasm::InstanceBuilder::LoadDataSegments(), v8::internal::wasm::ModuleDisassembler::PrintInitExpression(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ModuleDisassembler::PrintString(), v8::internal::wasm::PrintStringAsJSON(), v8::internal::RUNTIME_FUNCTION(), v8::internal::WasmScript::SetBreakPoint(), v8::internal::WasmScript::SetBreakPointForFunction(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::WasmGraphBuilder::TryWasmInlining(), v8::internal::wasm::ValidateAndSetBuiltinImports(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::ValidateFunctionNowIfNeeded(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), and v8::internal::wasm::NamesProvider::WriteRef().
Member Data Documentation
length_
uint32_t v8::internal::wasm::WireBytesRef::length_ = 0 [private]
Definition at line 77 of file wasm-module.h.
Referenced by end_offset(), is_empty(), length(), and WireBytesRef().
offset_
uint32_t v8::internal::wasm::WireBytesRef::offset_ = 0 [private]
Definition at line 76 of file wasm-module.h.
Referenced by end_offset(), is_set(), offset(), and WireBytesRef().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-module.h