v8::internal::TypedSlots Class Reference
#include <slot-set.h>
Classes
struct Chunk
struct TypedSlot
Public Member Functions
TypedSlots ()=default
virtual ~TypedSlots ()
void Insert (SlotType type, uint32_t offset)
void Merge (TypedSlots *other)
Static Public Attributes
static const int kMaxOffset = 1 << 29
Protected Types
using OffsetField = base::BitField< int, 0, 29 >
using TypeField = base::BitField< SlotType, 29, 3 >
Protected Member Functions
Chunk * EnsureChunk ()
Chunk * NewChunk (Chunk *next, size_t capacity)
Static Protected Member Functions
static size_t NextCapacity (size_t capacity)
Protected Attributes
Chunk * head_ = nullptr
Chunk * tail_ = nullptr
Static Protected Attributes
static const size_t kInitialBufferSize = 100
static const size_t kMaxBufferSize = 16 * KB
Detailed Description
Definition at line 273 of file slot-set.h.
Member Typedef Documentation
OffsetField
using v8::internal::TypedSlots::OffsetField = base::BitField<int, 0, 29> [protected]
Definition at line 282 of file slot-set.h.
TypeField
using v8::internal::TypedSlots::TypeField = base::BitField<SlotType, 29, 3> [protected]
Definition at line 283 of file slot-set.h.
Constructor & Destructor Documentation
TypedSlots()
v8::internal::TypedSlots::TypedSlots () [default]
 TypedSlots()
v8::internal::TypedSlots::~TypedSlots () [virtual]
Definition at line 13 of file slot-set.cc.
                        {
  Chunk* chunk = head_;
  while (chunk != nullptr) {
    Chunk* next = chunk->next;
    delete chunk;
    chunk = next;
  }
  head_ = nullptr;
  tail_ = nullptr;
}
References head_, v8::internal::TypedSlots::Chunk::next, and tail_.
Member Function Documentation
EnsureChunk()
TypedSlots::Chunk * v8::internal::TypedSlots::EnsureChunk () [protected]
Definition at line 46 of file slot-set.cc.
                                         {
  if (!head_) {
    head_ = tail_ = NewChunk(nullptr, kInitialBufferSize);
  }
  if (head_->buffer.size() == head_->buffer.capacity()) {
    head_ = NewChunk(head_, NextCapacity(head_->buffer.capacity()));
  }
  return head_;
}
References v8::internal::TypedSlots::Chunk::buffer, head_, kInitialBufferSize, NewChunk(), NextCapacity(), and tail_.
Referenced by Insert().
Insert()
void v8::internal::TypedSlots::Insert (SlotType type, uint32_t offset)
Definition at line 24 of file slot-set.cc.
                                                      {
  TypedSlot slot = {TypeField::encode(type) | OffsetField::encode(offset)};
  Chunk* chunk = EnsureChunk();
  DCHECK_LT(chunk->buffer.size(), chunk->buffer.capacity());
  chunk->buffer.push_back(slot);
}
References v8::internal::TypedSlots::Chunk::buffer, DCHECK_LT, v8::base::BitField< T, shift, size, U >::encode(), EnsureChunk(), and v8::internal::tracing::type.
Referenced by v8::internal::RememberedSet< type >::InsertTyped().
Merge()
void v8::internal::TypedSlots::Merge (TypedSlots * other)
Definition at line 31 of file slot-set.cc.
                                        {
  if (other->head_ == nullptr) {
    return;
  }
  if (head_ == nullptr) {
    head_ = other->head_;
    tail_ = other->tail_;
  } else {
    tail_->next = other->head_;
    tail_ = other->tail_;
  }
  other->head_ = nullptr;
  other->tail_ = nullptr;
}
References head_, v8::internal::TypedSlots::Chunk::next, and tail_.
Referenced by v8::internal::RememberedSet< type >::MergeAndDeleteTyped(), and v8::internal::RememberedSet< type >::MergeTyped().
NewChunk()
TypedSlots::Chunk * v8::internal::TypedSlots::NewChunk (Chunk * next, size_t capacity) [protected]
Definition at line 56 of file slot-set.cc.
                                                                  {
  Chunk* chunk = new Chunk;
  chunk->next = next;
  chunk->buffer.reserve(capacity);
  DCHECK_EQ(chunk->buffer.capacity(), capacity);
  return chunk;
}
References v8::internal::TypedSlots::Chunk::buffer, DCHECK_EQ, and v8::internal::TypedSlots::Chunk::next.
Referenced by EnsureChunk().
NextCapacity()
static size_t v8::internal::TypedSlots::NextCapacity (size_t capacity) [inline], [static], [protected]
Definition at line 293 of file slot-set.h.
                                              {
    return std::min({kMaxBufferSize, capacity * 2});
  }
Referenced by EnsureChunk().
Member Data Documentation
head_
Chunk* v8::internal::TypedSlots::head_ = nullptr [protected]
Definition at line 298 of file slot-set.h.
Referenced by EnsureChunk(), Merge(), and ~TypedSlots().
kInitialBufferSize
const size_t v8::internal::TypedSlots::kInitialBufferSize = 100 [static], [protected]
Definition at line 291 of file slot-set.h.
Referenced by EnsureChunk().
kMaxBufferSize
const size_t v8::internal::TypedSlots::kMaxBufferSize = 16 * KB [static], [protected]
Definition at line 292 of file slot-set.h.
kMaxOffset
const int v8::internal::TypedSlots::kMaxOffset = 1 << 29 [static]
Definition at line 275 of file slot-set.h.
Referenced by v8::internal::LargePageMetadata::LargePageMetadata().
tail_
Chunk* v8::internal::TypedSlots::tail_ = nullptr [protected]
Definition at line 299 of file slot-set.h.
Referenced by EnsureChunk(), Merge(), and ~TypedSlots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/slot-set.h
/mnt/V8SourceCode/src/heap/slot-set.cc