v8::internal::EmbedderDataArray::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 1440 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 1443 of file objects-body-descriptors-inl.h.
                                                                    {
#ifdef V8_COMPRESS_POINTERS
    static_assert(kEmbedderDataSlotSize == 2 * kTaggedSize);
    for (int offset = EmbedderDataArray::OffsetOfElementAt(0);
         offset < object_size; offset += kEmbedderDataSlotSize) {
      IteratePointer(obj, offset + EmbedderDataSlot::kTaggedPayloadOffset, v);
      v->VisitExternalPointer(
          obj, obj->RawExternalPointerField(
                   offset + EmbedderDataSlot::kExternalPointerOffset,
                   kEmbedderDataSlotPayloadTag));
    }
#else
    // We store raw aligned pointers as Smis, so it's safe to iterate the whole
    // array.
    static_assert(kEmbedderDataSlotSize == kTaggedSize);
    IteratePointers(obj, EmbedderDataArray::kHeaderSize, object_size, v);
#endif
  }
References v8::internal::BodyDescriptorBase::IteratePointer(), v8::internal::BodyDescriptorBase::IteratePointers(), v8::internal::kEmbedderDataSlotPayloadTag, v8::internal::kEmbedderDataSlotSize, v8::internal::EmbedderDataSlot::kExternalPointerOffset, v8::internal::EmbedderDataArray::kHeaderSize, v8::internal::EmbedderDataSlot::kTaggedPayloadOffset, v8::internal::kTaggedSize, v8::internal::EmbedderDataArray::OffsetOfElementAt(), and v8::internal::ObjectVisitor::VisitExternalPointer().
SizeOf()
static int v8::internal::EmbedderDataArray::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 1464 of file objects-body-descriptors-inl.h.
                                                                       {
    return object->SizeFromMap(map);
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h