v8::internal::ExternalStringTableCleanerVisitor< mode > Class Template Reference
#include <mark-sweep-utilities.h>
Public Member Functions
ExternalStringTableCleanerVisitor (Heap *heap)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
Private Attributes
Heap * heap_
Additional Inherited Members
Detailed Description
template<ExternalStringTableCleaningMode mode>
class v8::internal::ExternalStringTableCleanerVisitor< mode >
Definition at line 76 of file mark-sweep-utilities.h.
Constructor & Destructor Documentation
ExternalStringTableCleanerVisitor()
template<ExternalStringTableCleaningMode mode>
v8::internal::ExternalStringTableCleanerVisitor< mode >::ExternalStringTableCleanerVisitor (Heap * heap) [inline], [explicit]
Definition at line 78 of file mark-sweep-utilities.h.
: heap_(heap) {}
Member Function Documentation
VisitRootPointers()
template<ExternalStringTableCleaningMode mode>
void v8::internal::ExternalStringTableCleanerVisitor< mode >::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 97 of file mark-sweep-utilities.cc.
                        {
  // Visit all HeapObject pointers in [start, end).
  DCHECK_EQ(static_cast<int>(root),
            static_cast<int>(Root::kExternalStringsTable));
  NonAtomicMarkingState* marking_state = heap_->non_atomic_marking_state();
  Tagged<Object> the_hole = ReadOnlyRoots(heap_).the_hole_value();
  for (FullObjectSlot p = start; p < end; ++p) {
    Tagged<Object> o = *p;
    if (!IsHeapObject(o)) continue;
    Tagged<HeapObject> heap_object = Cast<HeapObject>(o);
    // MinorMS doesn't update the young strings set and so it may contain
    // strings that are already in old space.
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state, heap_object))
      continue;
    if ((mode == ExternalStringTableCleaningMode::kYoungOnly) &&
        !HeapLayout::InYoungGeneration(heap_object))
      continue;
    if (IsExternalString(o)) {
      heap_->FinalizeExternalString(Cast<String>(o));
    } else {
      // The original external string may have been internalized.
      DCHECK(IsThinString(o));
    }
    // Set the entry to the_hole_value (as deleted).
    p.store(the_hole);
  }
}
References DCHECK, DCHECK_EQ, v8::internal::compiler::end(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::InstanceTypeChecker::IsThinString(), and mode().
Member Data Documentation
heap_
template<ExternalStringTableCleaningMode mode>
Heap* v8::internal::ExternalStringTableCleanerVisitor< mode >::heap_ [private]
Definition at line 84 of file mark-sweep-utilities.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/mark-sweep-utilities.h
/mnt/V8SourceCode/src/heap/mark-sweep-utilities.cc