v8::internal::ContextDeserializer Class Reference
#include <context-deserializer.h>
Static Public Member Functions
static MaybeDirectHandle< Context > DeserializeContext (Isolate *isolate, const SnapshotData *data, size_t context_index, bool can_rehash, DirectHandle< JSGlobalProxy > global_proxy, DeserializeEmbedderFieldsCallback embedder_fields_deserializer)
Private Member Functions
ContextDeserializer (Isolate *isolate, const SnapshotData *data, bool can_rehash)
MaybeDirectHandle< Object > Deserialize (Isolate *isolate, DirectHandle< JSGlobalProxy > global_proxy, DeserializeEmbedderFieldsCallback embedder_fields_deserializer)
void DeserializeEmbedderFields (DirectHandle< NativeContext > context, DeserializeEmbedderFieldsCallback embedder_fields_deserializer)
void DeserializeApiWrapperFields (const v8::DeserializeAPIWrapperCallback &api_wrapper_callback)
Additional Inherited Members
Detailed Description
Definition at line 19 of file context-deserializer.h.
Constructor & Destructor Documentation
ContextDeserializer()
v8::internal::ContextDeserializer::ContextDeserializer (Isolate * isolate, const SnapshotData * data, bool can_rehash) [inline], [explicit], [private]
Definition at line 28 of file context-deserializer.h.
      : Deserializer(isolate, data->Payload(), data->GetMagicNumber(), false,
                     can_rehash) {}
Member Function Documentation
Deserialize()
MaybeDirectHandle< Object > v8::internal::ContextDeserializer::Deserialize (Isolate * isolate, DirectHandle< JSGlobalProxy > global_proxy, DeserializeEmbedderFieldsCallback embedder_fields_deserializer) [private]
Definition at line 47 of file context-deserializer.cc.
                                                                    {
  // Replace serialized references to the global proxy and its map with the
  // given global proxy and its map.
  AddAttachedObject(global_proxy);
  AddAttachedObject(direct_handle(global_proxy->map(), isolate));
  DirectHandle<Object> result;
  {
    // There's no code deserialized here. If this assert fires then that's
    // changed and logging should be added to notify the profiler et al. of
    // the new code, which also has to be flushed from instruction cache.
    DisallowCodeAllocation no_code_allocation;
    result = ReadObject();
    DCHECK(IsNativeContext(*result));
    DeserializeDeferredObjects();
    DeserializeEmbedderFields(Cast<NativeContext>(result),
                              embedder_fields_deserializer);
    DeserializeApiWrapperFields(
        embedder_fields_deserializer.api_wrapper_callback);
    LogNewMapEvents();
    WeakenDescriptorArrays();
  }
  if (should_rehash()) Rehash();
  return result;
}
References v8::internal::Deserializer< Isolate >::AddAttachedObject(), v8::internal::DeserializeEmbedderFieldsCallback::api_wrapper_callback, v8::internal::DCHECK(), DeserializeApiWrapperFields(), v8::internal::Deserializer< Isolate >::DeserializeDeferredObjects(), DeserializeEmbedderFields(), v8::internal::direct_handle(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::Deserializer< Isolate >::LogNewMapEvents(), v8::internal::Deserializer< Isolate >::ReadObject(), v8::internal::Deserializer< Isolate >::Rehash(), v8::base::internal::result, v8::internal::Deserializer< Isolate >::should_rehash(), and v8::internal::Deserializer< Isolate >::WeakenDescriptorArrays().
Referenced by DeserializeContext().
DeserializeApiWrapperFields()
void v8::internal::ContextDeserializer::DeserializeApiWrapperFields (const v8::DeserializeAPIWrapperCallback & api_wrapper_callback) [private]
Definition at line 136 of file context-deserializer.cc.
                                                                 {
  if (!source()->HasMore() || source()->Peek() != kApiWrapperFieldsData) {
    return;
  }
  // Consume `kApiWrapperFieldsData`.
  source()->Get();
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate());
  DisallowCompilation no_compile(isolate());
  // Buffer is reused across various deserializations. We always copy N bytes
  // into the backing and pass that N bytes to the embedder via StartupData.
  PlainBuffer<char> buffer;
  // The block for `kApiWrapperFieldsData` consists of consecutive `kNewObject`
  // blocks that are in the end terminated with a `kSynchronize`.
  for (int code = source()->Get(); code != kSynchronize;
       code = source()->Get()) {
    HandleScope scope(isolate());
    DirectHandle<JSObject> js_object =
        Cast<JSObject>(GetBackReferencedObject());
    const int size = source()->GetUint30();
    buffer.EnsureCapacity(size);
    source()->CopyRaw(buffer.data(), size);
    DCHECK_NOT_NULL(api_wrapper_callback.callback);
    api_wrapper_callback.callback(v8::Utils::ToLocal(js_object),
                                  {buffer.data(), size},
                                  api_wrapper_callback.data);
  }
}
References v8::DeserializeAPIWrapperCallback::callback, code, v8::internal::SnapshotByteSource::CopyRaw(), v8::DeserializeAPIWrapperCallback::data, v8::internal::PlainBuffer< T >::data(), DCHECK_NOT_NULL, v8::internal::PlainBuffer< T >::EnsureCapacity(), v8::internal::SnapshotByteSource::Get(), v8::internal::compiler::turboshaft::Get(), v8::internal::Deserializer< Isolate >::GetBackReferencedObject(), v8::internal::SnapshotByteSource::GetUint30(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::SerializerDeserializer::kApiWrapperFieldsData, v8::internal::SerializerDeserializer::kSynchronize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::Deserializer< Isolate >::source().
Referenced by Deserialize().
DeserializeContext()
MaybeDirectHandle< Context > v8::internal::ContextDeserializer::DeserializeContext (Isolate * isolate, const SnapshotData * data, size_t context_index, bool can_rehash, DirectHandle< JSGlobalProxy > global_proxy, DeserializeEmbedderFieldsCallback embedder_fields_deserializer) [static]
Definition at line 17 of file context-deserializer.cc.
                                                                    {
  TRACE_EVENT0("v8", "V8.DeserializeContext");
  RCS_SCOPE(isolate, RuntimeCallCounterId::kDeserializeContext);
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.profile_deserialization)) timer.Start();
  NestedTimedHistogramScope histogram_timer(
      isolate->counters()->snapshot_deserialize_context());
  ContextDeserializer d(isolate, data, can_rehash);
  MaybeDirectHandle<Object> maybe_result =
      d.Deserialize(isolate, global_proxy, embedder_fields_deserializer);
  if (V8_UNLIKELY(v8_flags.profile_deserialization)) {
    // ATTENTION: The Memory.json benchmark greps for this exact output. Do not
    // change it without also updating Memory.json.
    const int bytes = static_cast<int>(data->RawData().size());
    const double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Deserializing context #%zu (%d bytes) took %0.3f ms]\n",
           context_index, bytes, ms);
  }
  DirectHandle<Object> result;
  if (!maybe_result.ToHandle(&result)) return {};
  return Cast<Context>(result);
}
References v8::internal::Isolate::counters(), Deserialize(), v8::base::ElapsedTimer::Elapsed(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::PrintF(), v8::internal::SnapshotData::RawData(), RCS_SCOPE, v8::base::internal::result, v8::base::Vector< T >::size(), v8::base::ElapsedTimer::Start(), v8::internal::MaybeDirectHandle< T >::ToHandle(), TRACE_EVENT0, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Snapshot::NewContextFromSnapshot().
DeserializeEmbedderFields()
void v8::internal::ContextDeserializer::DeserializeEmbedderFields (DirectHandle< NativeContext > context, DeserializeEmbedderFieldsCallback embedder_fields_deserializer) [private]
Definition at line 95 of file context-deserializer.cc.
                                                                    {
  if (!source()->HasMore() || source()->Peek() != kEmbedderFieldsData) {
    return;
  }
  // Consume `kEmbedderFieldsData`.
  source()->Get();
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate());
  DisallowCompilation no_compile(isolate());
  // Buffer is reused across various deserializations. We always copy N bytes
  // into the backing and pass that N bytes to the embedder via StartupData.
  PlainBuffer<char> buffer;
  for (int code = source()->Get(); code != kSynchronize;
       code = source()->Get()) {
    HandleScope scope(isolate());
    DirectHandle<HeapObject> heap_object =
        Cast<HeapObject>(GetBackReferencedObject());
    const int index = source()->GetUint30();
    const int size = source()->GetUint30();
    buffer.EnsureCapacity(size);
    source()->CopyRaw(buffer.data(), size);
    if (IsJSObject(*heap_object)) {
      DirectHandle<JSObject> obj = Cast<JSObject>(heap_object);
      v8::DeserializeInternalFieldsCallback callback =
          embedder_fields_deserializer.js_object_callback;
      DCHECK_NOT_NULL(callback.callback);
      callback.callback(v8::Utils::ToLocal(obj), index, {buffer.data(), size},
                        callback.data);
    } else {
      DCHECK(IsEmbedderDataArray(*heap_object));
      v8::DeserializeContextDataCallback callback =
          embedder_fields_deserializer.context_callback;
      DCHECK_NOT_NULL(callback.callback);
      callback.callback(v8::Utils::ToLocal(context), index,
                        {buffer.data(), size}, callback.data);
    }
  }
}
References v8::DeserializeInternalFieldsCallback::callback, v8::DeserializeContextDataCallback::callback, code, v8::internal::DeserializeEmbedderFieldsCallback::context_callback, v8::internal::SnapshotByteSource::CopyRaw(), v8::DeserializeInternalFieldsCallback::data, v8::DeserializeContextDataCallback::data, v8::internal::PlainBuffer< T >::data(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::PlainBuffer< T >::EnsureCapacity(), v8::internal::SnapshotByteSource::Get(), v8::internal::compiler::turboshaft::Get(), v8::internal::Deserializer< Isolate >::GetBackReferencedObject(), v8::internal::SnapshotByteSource::GetUint30(), v8::internal::index, v8::internal::Deserializer< Isolate >::isolate(), v8::internal::DeserializeEmbedderFieldsCallback::js_object_callback, v8::internal::SerializerDeserializer::kEmbedderFieldsData, v8::internal::SerializerDeserializer::kSynchronize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::Deserializer< Isolate >::source().
Referenced by Deserialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/context-deserializer.h
/mnt/V8SourceCode/src/snapshot/context-deserializer.cc