v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder Class Reference
Public Member Functions
ActivationsFinder (Tagged< GcSafeCode > topmost_optimized_code, bool safe_to_deopt_topmost_optimized_code)
void VisitThread (Isolate *isolate, ThreadLocalTop *top) override
Additional Inherited Members
Detailed Description
Definition at line 331 of file deoptimizer.cc.
Constructor & Destructor Documentation
ActivationsFinder()
v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::ActivationsFinder (Tagged< GcSafeCode > topmost_optimized_code, bool safe_to_deopt_topmost_optimized_code) [inline]
Definition at line 333 of file deoptimizer.cc.
                                                               {
#ifdef DEBUG
    topmost_ = topmost_optimized_code;
    safe_to_deopt_ = safe_to_deopt_topmost_optimized_code;
#endif
  }
Member Function Documentation
VisitThread()
void v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread (Isolate * isolate, ThreadLocalTop * top) [inline], [override], [virtual]
Implements v8::internal::ThreadVisitor.
Definition at line 344 of file deoptimizer.cc.
                                                                   {
    for (StackFrameIterator it(isolate, top); !it.done(); it.Advance()) {
      if (it.frame()->is_optimized_js()) {
        Tagged<GcSafeCode> code = it.frame()->GcSafeLookupCode();
        if (CodeKindCanDeoptimize(code->kind()) &&
            code->marked_for_deoptimization()) {
          // Obtain the trampoline to the deoptimizer call.
          int trampoline_pc;
          if (code->is_maglevved()) {
            MaglevSafepointEntry safepoint = MaglevSafepointTable::FindEntry(
                isolate, code, it.frame()->pc());
            trampoline_pc = safepoint.trampoline_pc();
          } else {
            SafepointEntry safepoint = SafepointTable::FindEntry(
                isolate, code, it.frame()->maybe_unauthenticated_pc());
            trampoline_pc = safepoint.trampoline_pc();
          }
          // TODO(saelo): currently we have to use full pointer comparison as
          // builtin Code is still inside the sandbox while runtime-generated
          // Code is in trusted space.
          static_assert(!kAllCodeObjectsLiveInTrustedSpace);
          DCHECK_IMPLIES(code.SafeEquals(topmost_), safe_to_deopt_);
          static_assert(SafepointEntry::kNoTrampolinePC == -1);
          CHECK_GE(trampoline_pc, 0);
          Address new_pc = code->instruction_start() + trampoline_pc;
          if (it.frame()->InFastCCall()) {
            // Fast C calls call directly to C++, so there may not be a return
            // address on the stack. Instead we patch the code after the call.
            // For C calls the caller has to pop parameters off the stack. This
            // has to happen before deoptimization. Therefore we add the offset
            // here that is needed for popping the arguments.
            Address pc =
                *it.frame()->pc_address() + kMaxSizeOfMoveAfterFastCall;
            Deoptimizer::PatchToJump(pc, new_pc);
          } else {
            if (v8_flags.cet_compatible) {
              Address pc = *it.frame()->pc_address();
              Deoptimizer::PatchToJump(pc, new_pc);
            } else {
              // Replace the current pc on the stack with the trampoline.
              // TODO(v8:10026): avoid replacing a signed pointer.
              Address* pc_addr = it.frame()->pc_address();
              PointerAuthentication::ReplacePC(pc_addr, new_pc,
                                               kSystemPointerSize);
            }
          }
        }
      }
    }
  }
References CHECK_GE, code, v8::internal::CodeKindCanDeoptimize(), DCHECK_IMPLIES, v8::internal::StackFrameIteratorBase::done(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::SafepointTable::FindEntry(), v8::internal::kAllCodeObjectsLiveInTrustedSpace, v8::internal::kMaxSizeOfMoveAfterFastCall, v8::internal::SafepointEntryBase::kNoTrampolinePC, v8::internal::kSystemPointerSize, v8::internal::Deoptimizer::PatchToJump(), v8::internal::PointerAuthentication::ReplacePC(), v8::internal::SafepointEntryBase::trampoline_pc(), and v8::internal::v8_flags.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/deoptimizer/deoptimizer.cc