v8::internal::Decoder< V > Class Template Reference
#include <decoder-arm64.h>
Public Member Functions
Decoder ()
virtual ~Decoder ()
virtual void Decode (Instruction *instr)
Decoder (const disasm::NameConverter &converter, v8::base::Vector< char > out_buffer)
~Decoder ()
Decoder (const Decoder &)=delete
Decoder & operator= (const Decoder &)=delete
int InstructionDecode (uint8_t *instruction)
Private Member Functions
void DecodePCRelAddressing (Instruction *instr)
void DecodeAddSubImmediate (Instruction *instr)
void DecodeBranchSystemException (Instruction *instr)
void DecodeLoadStore (Instruction *instr)
void DecodeLogical (Instruction *instr)
void DecodeBitfieldExtract (Instruction *instr)
void DecodeDataProcessing (Instruction *instr)
void DecodeFP (Instruction *instr)
void DecodeNEONLoadStore (Instruction *instr)
void DecodeNEONVectorDataProcessing (Instruction *instr)
void DecodeNEONScalarDataProcessing (Instruction *instr)
void PrintChar (const char ch)
void Print (const char *str)
void PrintRegister (int reg)
void PrintFPURegister (int freg)
void PrintVRegister (int reg)
void PrintFPUStatusRegister (int freg)
void PrintRs1 (Instruction *instr)
void PrintRs2 (Instruction *instr)
void PrintRd (Instruction *instr)
void PrintUimm (Instruction *instr)
void PrintVs1 (Instruction *instr)
void PrintVs2 (Instruction *instr)
void PrintVd (Instruction *instr)
void PrintFRs1 (Instruction *instr)
void PrintFRs2 (Instruction *instr)
void PrintFRs3 (Instruction *instr)
void PrintFRd (Instruction *instr)
void PrintImm12 (Instruction *instr)
void PrintImm12X (Instruction *instr)
void PrintImm20U (Instruction *instr)
void PrintImm20J (Instruction *instr)
void PrintShamt (Instruction *instr)
void PrintShamt32 (Instruction *instr)
void PrintRvcImm6 (Instruction *instr)
void PrintRvcImm6U (Instruction *instr)
void PrintRvcImm6Addi16sp (Instruction *instr)
void PrintRvcShamt (Instruction *instr)
void PrintRvcImm6Ldsp (Instruction *instr)
void PrintRvcImm6Lwsp (Instruction *instr)
void PrintRvcImm6Sdsp (Instruction *instr)
void PrintRvcImm6Swsp (Instruction *instr)
void PrintRvcImm5W (Instruction *instr)
void PrintRvcImm5D (Instruction *instr)
void PrintRvcImm8Addi4spn (Instruction *instr)
void PrintRvcImm11CJ (Instruction *instr)
void PrintRvcImm8B (Instruction *instr)
void PrintRvvVm (Instruction *instr)
void PrintAcquireRelease (Instruction *instr)
void PrintBranchOffset (Instruction *instr)
void PrintStoreOffset (Instruction *instr)
void PrintCSRReg (Instruction *instr)
void PrintRvvSEW (Instruction *instr)
void PrintRvvLMUL (Instruction *instr)
void PrintRvvSimm5 (Instruction *instr)
void PrintRvvUimm5 (Instruction *instr)
void PrintRoundingMode (Instruction *instr)
void PrintMemoryOrder (Instruction *instr, bool is_pred)
void DecodeRType (Instruction *instr)
void DecodeR4Type (Instruction *instr)
void DecodeRAType (Instruction *instr)
void DecodeRFPType (Instruction *instr)
void DecodeIType (Instruction *instr)
void DecodeSType (Instruction *instr)
void DecodeBType (Instruction *instr)
void DecodeUType (Instruction *instr)
void DecodeJType (Instruction *instr)
void DecodeCRType (Instruction *instr)
void DecodeCAType (Instruction *instr)
void DecodeCIType (Instruction *instr)
void DecodeCIWType (Instruction *instr)
void DecodeCSSType (Instruction *instr)
void DecodeCLType (Instruction *instr)
void DecodeCSType (Instruction *instr)
void DecodeCJType (Instruction *instr)
void DecodeCBType (Instruction *instr)
void DecodeVType (Instruction *instr)
void DecodeRvvIVV (Instruction *instr)
void DecodeRvvFVV (Instruction *instr)
void DecodeRvvFVF (Instruction *instr)
void DecodeRvvIVI (Instruction *instr)
void DecodeRvvIVX (Instruction *instr)
void DecodeRvvVL (Instruction *instr)
void DecodeRvvVS (Instruction *instr)
void DecodeRvvMVV (Instruction *instr)
void DecodeRvvMVX (Instruction *instr)
void PrintInstructionName (Instruction *instr)
void PrintTarget (Instruction *instr)
int FormatRegister (Instruction *instr, const char *option)
int FormatFPURegisterOrRoundMode (Instruction *instr, const char *option)
int FormatRvcRegister (Instruction *instr, const char *option)
int FormatRvcImm (Instruction *instr, const char *option)
int FormatOption (Instruction *instr, const char *option)
void Format (Instruction *instr, const char *format)
void Unknown (Instruction *instr)
int switch_sew (Instruction *instr)
int switch_nf (Instruction *instr)
Private Attributes
const disasm::NameConverter & converter_
v8::base::Vector< char > out_buffer_
int out_buffer_pos_
Additional Inherited Members
Detailed Description
template<typename V>
class v8::internal::Decoder< V >
Definition at line 148 of file decoder-arm64.h.
Constructor & Destructor Documentation
Decoder() [1/3]
template<typename V >
v8::internal::Decoder< V >::Decoder () [inline]
Definition at line 150 of file decoder-arm64.h.
{}
 Decoder() [1/2]
template<typename V >
virtual v8::internal::Decoder< V >::~Decoder () [inline], [virtual]
Definition at line 151 of file decoder-arm64.h.
{}
Decoder() [2/3]
template<typename V >
v8::internal::Decoder< V >::Decoder (const disasm::NameConverter & converter, v8::base::Vector< char > out_buffer) [inline]
Definition at line 47 of file disasm-riscv.cc.
      : converter_(converter), out_buffer_(out_buffer), out_buffer_pos_(0) {
    out_buffer_[out_buffer_pos_] = '\0';
  }
References v8::internal::Decoder< V >::out_buffer_, and v8::internal::Decoder< V >::out_buffer_pos_.
 Decoder() [2/2]
template<typename V >
v8::internal::Decoder< V >::~Decoder () [inline]
Definition at line 53 of file disasm-riscv.cc.
{}
Decoder() [3/3]
template<typename V >
v8::internal::Decoder< V >::Decoder (const Decoder< V > &) [delete]
Member Function Documentation
Decode()
template<typename V >
void v8::internal::Decoder< V >::Decode (Instruction * instr) [virtual]
Definition at line 16 of file decoder-arm64-inl.h.
                                          {
  if (instr->Bits(28, 27) == 0) {
    V::VisitUnallocated(instr);
  } else {
    switch (instr->Bits(27, 24)) {
      // 0: PC relative addressing.
      case 0x0:
        DecodePCRelAddressing(instr);
        break;
      // 1: Add/sub immediate.
      case 0x1:
        DecodeAddSubImmediate(instr);
        break;
      // A: Logical shifted register.
      // Add/sub with carry.
      // Conditional compare register.
      // Conditional compare immediate.
      // Conditional select.
      // Data processing 1 source.
      // Data processing 2 source.
      // B: Add/sub shifted register.
      // Add/sub extended register.
      // Data processing 3 source.
      case 0xA:
      case 0xB:
        DecodeDataProcessing(instr);
        break;
      // 2: Logical immediate.
      // Move wide immediate.
      case 0x2:
        DecodeLogical(instr);
        break;
      // 3: Bitfield.
      // Extract.
      case 0x3:
        DecodeBitfieldExtract(instr);
        break;
      // 4: Unconditional branch immediate.
      // Exception generation.
      // Compare and branch immediate.
      // 5: Compare and branch immediate.
      // Conditional branch.
      // System.
      // 6,7: Unconditional branch.
      // Test and branch immediate.
      case 0x4:
      case 0x5:
      case 0x6:
      case 0x7:
        DecodeBranchSystemException(instr);
        break;
      // 8,9: Load/store register pair post-index.
      // Load register literal.
      // Load/store register unscaled immediate.
      // Load/store register immediate post-index.
      // Load/store register immediate pre-index.
      // Load/store register offset.
      // Load/store exclusive.
      // Load/store ordered.
      // Compare and swap [Armv8.1].
      // Compare and swap pair [Armv8.1].
      // Atomic memory operations [Armv8.1].
      // C,D: Load/store register pair offset.
      // Load/store register pair pre-index.
      // Load/store register unsigned immediate.
      // Advanced SIMD.
      case 0x8:
      case 0x9:
      case 0xC:
      case 0xD:
        DecodeLoadStore(instr);
        break;
      // E: FP fixed point conversion.
      // FP integer conversion.
      // FP data processing 1 source.
      // FP compare.
      // FP immediate.
      // FP data processing 2 source.
      // FP conditional compare.
      // FP conditional select.
      // Advanced SIMD.
      // F: FP data processing 3 source.
      // Advanced SIMD.
      case 0xE:
      case 0xF:
        DecodeFP(instr);
        break;
    }
  }
}
References v8::internal::Instruction::Bits().
Referenced by v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes(), and v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall().
DecodeAddSubImmediate()
template<typename V >
void v8::internal::Decoder< V >::DecodeAddSubImmediate (Instruction * instr) [private]
Definition at line 399 of file decoder-arm64-inl.h.
                                                         {
  DCHECK_EQ(0x1, instr->Bits(27, 24));
  if (instr->Bit(23) == 1) {
    V::VisitUnallocated(instr);
  } else {
    V::VisitAddSubImmediate(instr);
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), and DCHECK_EQ.
DecodeBitfieldExtract()
template<typename V >
void v8::internal::Decoder< V >::DecodeBitfieldExtract (Instruction * instr) [private]
Definition at line 374 of file decoder-arm64-inl.h.
                                                         {
  DCHECK_EQ(0x3, instr->Bits(27, 24));
  if ((instr->Mask(0x80400000) == 0x80000000) ||
      (instr->Mask(0x80400000) == 0x00400000) ||
      (instr->Mask(0x80008000) == 0x00008000)) {
    V::VisitUnallocated(instr);
  } else if (instr->Bit(23) == 0) {
    if ((instr->Mask(0x80200000) == 0x00200000) ||
        (instr->Mask(0x60000000) == 0x60000000)) {
      V::VisitUnallocated(instr);
    } else {
      V::VisitBitfield(instr);
    }
  } else {
    if ((instr->Mask(0x60200000) == 0x00200000) ||
        (instr->Mask(0x60000000) != 0x00000000)) {
      V::VisitUnallocated(instr);
    } else {
      V::VisitExtract(instr);
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), DCHECK_EQ, and v8::internal::Instruction::Mask().
DecodeBranchSystemException()
template<typename V >
void v8::internal::Decoder< V >::DecodeBranchSystemException (Instruction * instr) [private]
Definition at line 124 of file decoder-arm64-inl.h.
                                                               {
  DCHECK_EQ(0x4, instr->Bits(27, 24) & 0xC); // 0x4, 0x5, 0x6, 0x7
  switch (instr->Bits(31, 29)) {
    case 0:
    case 4: {
      V::VisitUnconditionalBranch(instr);
      break;
    }
    case 1:
    case 5: {
      if (instr->Bit(25) == 0) {
        V::VisitCompareBranch(instr);
      } else {
        V::VisitTestBranch(instr);
      }
      break;
    }
    case 2: {
      if (instr->Bit(25) == 0) {
        if ((instr->Bit(24) == 0x1)) {
          V::VisitUnallocated(instr);
        } else {
          V::VisitConditionalBranch(instr);
        }
      } else {
        V::VisitUnallocated(instr);
      }
      break;
    }
    case 6: {
      if (instr->Bit(25) == 0) {
        if (instr->Bit(24) == 0) {
          if ((instr->Bits(4, 2) != 0) ||
              (instr->Mask(0x00E0001D) == 0x00200001) ||
              (instr->Mask(0x00E0001D) == 0x00400001) ||
              (instr->Mask(0x00E0001E) == 0x00200002) ||
              (instr->Mask(0x00E0001E) == 0x00400002) ||
              (instr->Mask(0x00E0001C) == 0x00600000) ||
              (instr->Mask(0x00E0001C) == 0x00800000) ||
              (instr->Mask(0x00E0001F) == 0x00A00000) ||
              (instr->Mask(0x00C0001C) == 0x00C00000)) {
            V::VisitUnallocated(instr);
          } else {
            V::VisitException(instr);
          }
        } else {
          if (instr->Bits(23, 22) == 0) {
            const Instr masked_003FF0E0 = instr->Mask(0x003FF0E0);
            if ((instr->Bits(21, 19) == 0x4) ||
                (masked_003FF0E0 == 0x00033000) ||
                (masked_003FF0E0 == 0x003FF020) ||
                (masked_003FF0E0 == 0x003FF060) ||
                (masked_003FF0E0 == 0x003FF0E0) ||
                (instr->Mask(0x00388000) == 0x00008000) ||
                (instr->Mask(0x0038E000) == 0x00000000) ||
                (instr->Mask(0x0039E000) == 0x00002000) ||
                (instr->Mask(0x003AE000) == 0x00002000) ||
                (instr->Mask(0x003CE000) == 0x00042000) ||
                (instr->Mask(0x0038F000) == 0x00005000) ||
                (instr->Mask(0x0038E000) == 0x00006000)) {
              V::VisitUnallocated(instr);
            } else {
              V::VisitSystem(instr);
            }
          } else {
            V::VisitUnallocated(instr);
          }
        }
      } else {
        if ((instr->Bit(24) == 0x1) || (instr->Bits(20, 16) != 0x1F) ||
            (instr->Bits(15, 10) != 0) || (instr->Bits(4, 0) != 0) ||
            (instr->Bits(24, 21) == 0x3) || (instr->Bits(24, 22) == 0x3)) {
          V::VisitUnallocated(instr);
        } else {
          V::VisitUnconditionalBranchToRegister(instr);
        }
      }
      break;
    }
    case 3:
    case 7: {
      V::VisitUnallocated(instr);
      break;
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), DCHECK_EQ, and v8::internal::Instruction::Mask().
DecodeBType()
template<typename V >
void v8::internal::Decoder< V >::DecodeBType (Instruction * instr) [private]
Definition at line 2039 of file disasm-riscv.cc.
                                            {
  switch (instr->InstructionBits() & kBTypeMask) {
    case RO_BEQ:
      Format(instr, "beq 'rs1, 'rs2, 'offB");
      break;
    case RO_BNE:
      Format(instr, "bne 'rs1, 'rs2, 'offB");
      break;
    case RO_BLT:
      Format(instr, "blt 'rs1, 'rs2, 'offB");
      break;
    case RO_BGE:
      Format(instr, "bge 'rs1, 'rs2, 'offB");
      break;
    case RO_BLTU:
      Format(instr, "bltu 'rs1, 'rs2, 'offB");
      break;
    case RO_BGEU:
      Format(instr, "bgeu 'rs1, 'rs2, 'offB");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBTypeMask, v8::internal::RO_BEQ, v8::internal::RO_BGE, v8::internal::RO_BGEU, v8::internal::RO_BLT, v8::internal::RO_BLTU, v8::internal::RO_BNE, and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCAType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCAType (Instruction * instr) [private]
Definition at line 2123 of file disasm-riscv.cc.
                                             {
  switch (instr->InstructionBits() & kCATypeMask) {
    case RO_C_SUB:
      Format(instr, "sub 'Crs1s, 'Crs1s, 'Crs2s");
      break;
    case RO_C_XOR:
      Format(instr, "xor 'Crs1s, 'Crs1s, 'Crs2s");
      break;
    case RO_C_OR:
      Format(instr, "or 'Crs1s, 'Crs1s, 'Crs2s");
      break;
    case RO_C_AND:
      Format(instr, "and 'Crs1s, 'Crs1s, 'Crs2s");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_C_SUBW:
      Format(instr, "subw 'Crs1s, 'Crs1s, 'Crs2s");
      break;
    case RO_C_ADDW:
      Format(instr, "addw 'Crs1s, 'Crs1s, 'Crs2s");
      break;
#endif
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kCATypeMask, v8::internal::RO_C_AND, v8::internal::RO_C_OR, v8::internal::RO_C_SUB, v8::internal::RO_C_XOR, and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCBType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCBType (Instruction * instr) [private]
Definition at line 2286 of file disasm-riscv.cc.
                                             {
  switch (instr->RvcOpcode()) {
    case RO_C_BNEZ:
      Format(instr, "bnez 'Crs1s, x0, 'Cimm8B");
      break;
    case RO_C_BEQZ:
      Format(instr, "beqz 'Crs1s, x0, 'Cimm8B");
      break;
    case RO_C_MISC_ALU:
      if (instr->RvcFunct2BValue() == 0b00) {
        Format(instr, "srli 'Crs1s, 'Crs1s, 'Cshamt");
        break;
      } else if (instr->RvcFunct2BValue() == 0b01) {
        Format(instr, "srai 'Crs1s, 'Crs1s, 'Cshamt");
        break;
      } else if (instr->RvcFunct2BValue() == 0b10) {
        Format(instr, "andi 'Crs1s, 'Crs1s, 'Cimm6");
        break;
      } else {
        UNSUPPORTED_RISCV();
      }
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_BEQZ, v8::internal::RO_C_BNEZ, v8::internal::RO_C_MISC_ALU, v8::internal::InstructionGetters< T >::RvcFunct2BValue(), v8::internal::InstructionGetters< T >::RvcOpcode(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCIType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCIType (Instruction * instr) [private]
Definition at line 2150 of file disasm-riscv.cc.
                                             {
  switch (instr->RvcOpcode()) {
    case RO_C_NOP_ADDI:
      if (instr->RvcRdValue() == 0)
        Format(instr, "nop");
      else
        Format(instr, "addi 'Crd, 'Crd, 'Cimm6");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_C_ADDIW:
      Format(instr, "addiw 'Crd, 'Crd, 'Cimm6");
      break;
#endif
    case RO_C_LI:
      Format(instr, "li 'Crd, 'Cimm6");
      break;
    case RO_C_LUI_ADD:
      if (instr->RvcRdValue() == 2) {
        Format(instr, "addi sp, sp, 'Cimm6Addi16sp");
        break;
      } else if (instr->RvcRdValue() != 0 && instr->RvcRdValue() != 2) {
        Format(instr, "lui 'Crd, 'Cimm6U");
        break;
      } else {
        UNSUPPORTED_RISCV();
      }
    case RO_C_SLLI:
      Format(instr, "slli 'Crd, 'Crd, 'Cshamt");
      break;
    case RO_C_FLDSP:
      Format(instr, "fld 'Cfd, 'Cimm6Ldsp(sp)");
      break;
    case RO_C_LWSP:
      Format(instr, "lw 'Crd, 'Cimm6Lwsp(sp)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_C_LDSP:
      Format(instr, "ld 'Crd, 'Cimm6Ldsp(sp)");
      break;
#elif defined(V8_TARGET_ARCH_32_BIT)
    case RO_C_FLWSP:
      Format(instr, "flw 'Cfd, 'Cimm6Ldsp(sp)");
      break;
#endif
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_FLDSP, v8::internal::RO_C_LI, v8::internal::RO_C_LUI_ADD, v8::internal::RO_C_LWSP, v8::internal::RO_C_NOP_ADDI, v8::internal::RO_C_SLLI, v8::internal::InstructionGetters< T >::RvcOpcode(), v8::internal::InstructionGetters< T >::RvcRdValue(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCIWType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCIWType (Instruction * instr) [private]
Definition at line 2199 of file disasm-riscv.cc.
                                              {
  switch (instr->RvcOpcode()) {
    case RO_C_ADDI4SPN:
      Format(instr, "addi 'Crs2s, sp, 'Cimm8Addi4spn");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_ADDI4SPN, v8::internal::InstructionGetters< T >::RvcOpcode(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCJType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCJType (Instruction * instr) [private]
Definition at line 2276 of file disasm-riscv.cc.
                                             {
  switch (instr->RvcOpcode()) {
    case RO_C_J:
      Format(instr, "j 'Cimm11CJ");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_J, v8::internal::InstructionGetters< T >::RvcOpcode(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCLType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCLType (Instruction * instr) [private]
Definition at line 2231 of file disasm-riscv.cc.
                                             {
  switch (instr->RvcOpcode()) {
    case RO_C_FLD:
      Format(instr, "fld 'Cfs2s, 'Cimm5D('Crs1s)");
      break;
    case RO_C_LW:
      Format(instr, "lw 'Crs2s, 'Cimm5W('Crs1s)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_C_LD:
      Format(instr, "ld 'Crs2s, 'Cimm5D('Crs1s)");
      break;
#elif defined(V8_TARGET_ARCH_32_BIT)
    case RO_C_FLW:
      Format(instr, "flw 'Cfs2s, 'Cimm5D('Crs1s)");
      break;
#endif
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_FLD, v8::internal::RO_C_LW, v8::internal::InstructionGetters< T >::RvcOpcode(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCRType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCRType (Instruction * instr) [private]
Definition at line 2093 of file disasm-riscv.cc.
                                             {
  switch (instr->RvcFunct4Value()) {
    case 0b1000:
      if (instr->RvcRs1Value() != 0 && instr->RvcRs2Value() == 0) {
        Format(instr, "jr 'Crs1");
        break;
      } else if (instr->RvcRdValue() != 0 && instr->RvcRs2Value() != 0) {
        Format(instr, "mv 'Crd, 'Crs2");
        break;
      } else {
        UNSUPPORTED_RISCV();
      }
    case 0b1001:
      if (instr->RvcRs1Value() == 0 && instr->RvcRs2Value() == 0) {
        Format(instr, "ebreak");
        break;
      } else if (instr->RvcRdValue() != 0 && instr->RvcRs2Value() == 0) {
        Format(instr, "jalr 'Crs1");
        break;
      } else if (instr->RvcRdValue() != 0 && instr->RvcRs2Value() != 0) {
        Format(instr, "add 'Crd, 'Crd, 'Crs2");
        break;
      } else {
        UNSUPPORTED_RISCV();
      }
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::InstructionGetters< T >::RvcFunct4Value(), v8::internal::InstructionGetters< T >::RvcRdValue(), v8::internal::InstructionGetters< T >::RvcRs1Value(), v8::internal::InstructionGetters< T >::RvcRs2Value(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCSSType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCSSType (Instruction * instr) [private]
Definition at line 2209 of file disasm-riscv.cc.
                                              {
  switch (instr->RvcOpcode()) {
    case RO_C_SWSP:
      Format(instr, "sw 'Crs2, 'Cimm6Swsp(sp)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_C_SDSP:
      Format(instr, "sd 'Crs2, 'Cimm6Sdsp(sp)");
      break;
#elif defined(V8_TARGET_ARCH_32_BIT)
    case RO_C_FSWSP:
      Format(instr, "fsw 'Cfs2, 'Cimm6Sdsp(sp)");
      break;
#endif
    case RO_C_FSDSP:
      Format(instr, "fsd 'Cfs2, 'Cimm6Sdsp(sp)");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_FSDSP, v8::internal::RO_C_SWSP, v8::internal::InstructionGetters< T >::RvcOpcode(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeCSType()
template<typename V >
void v8::internal::Decoder< V >::DecodeCSType (Instruction * instr) [private]
Definition at line 2254 of file disasm-riscv.cc.
                                             {
  switch (instr->RvcOpcode()) {
    case RO_C_FSD:
      Format(instr, "fsd 'Cfs2s, 'Cimm5D('Crs1s)");
      break;
    case RO_C_SW:
      Format(instr, "sw 'Crs2s, 'Cimm5W('Crs1s)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_C_SD:
      Format(instr, "sd 'Crs2s, 'Cimm5D('Crs1s)");
      break;
#elif defined(V8_TARGET_ARCH_32_BIT)
    case RO_C_FSW:
      Format(instr, "fsw 'Cfs2s, 'Cimm5D('Crs1s)");
      break;
#endif
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::RO_C_FSD, v8::internal::RO_C_SW, v8::internal::InstructionGetters< T >::RvcOpcode(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeDataProcessing()
template<typename V >
void v8::internal::Decoder< V >::DecodeDataProcessing (Instruction * instr) [private]
Definition at line 409 of file decoder-arm64-inl.h.
                                                        {
  DCHECK((instr->Bits(27, 24) == 0xA) || (instr->Bits(27, 24) == 0xB));
  if (instr->Bit(24) == 0) {
    if (instr->Bit(28) == 0) {
      if (instr->Mask(0x80008000) == 0x00008000) {
        V::VisitUnallocated(instr);
      } else {
        V::VisitLogicalShifted(instr);
      }
    } else {
      switch (instr->Bits(23, 21)) {
        case 0: {
          if (instr->Mask(0x0000FC00) != 0) {
            V::VisitUnallocated(instr);
          } else {
            V::VisitAddSubWithCarry(instr);
          }
          break;
        }
        case 2: {
          if ((instr->Bit(29) == 0) || (instr->Mask(0x00000410) != 0)) {
            V::VisitUnallocated(instr);
          } else {
            if (instr->Bit(11) == 0) {
              V::VisitConditionalCompareRegister(instr);
            } else {
              V::VisitConditionalCompareImmediate(instr);
            }
          }
          break;
        }
        case 4: {
          if (instr->Mask(0x20000800) != 0x00000000) {
            V::VisitUnallocated(instr);
          } else {
            V::VisitConditionalSelect(instr);
          }
          break;
        }
        case 6: {
          if (instr->Bit(29) == 0x1) {
            V::VisitUnallocated(instr);
          } else {
            if (instr->Bit(30) == 0) {
              if ((instr->Bit(15) == 0x1) || (instr->Bits(15, 11) == 0) ||
                  (instr->Bits(15, 12) == 0x1) ||
                  (instr->Bits(15, 12) == 0x3) ||
                  (instr->Bits(15, 13) == 0x3) ||
                  (instr->Mask(0x8000EC00) == 0x00004C00) ||
                  (instr->Mask(0x8000E800) == 0x80004000) ||
                  (instr->Mask(0x8000E400) == 0x80004000)) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitDataProcessing2Source(instr);
              }
            } else {
              if ((instr->Bits(20, 16) != 0) || (instr->Bits(15, 10) > 8) ||
                  (instr->Mask(0xFFFFFC00) == 0x5AC00C00)) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitDataProcessing1Source(instr);
              }
            }
            break;
          }
          [[fallthrough]];
        }
        case 1:
        case 3:
        case 5:
        case 7:
          V::VisitUnallocated(instr);
          break;
      }
    }
  } else {
    if (instr->Bit(28) == 0) {
      if (instr->Bit(21) == 0) {
        if ((instr->Bits(23, 22) == 0x3) ||
            (instr->Mask(0x80008000) == 0x00008000)) {
          V::VisitUnallocated(instr);
        } else {
          V::VisitAddSubShifted(instr);
        }
      } else {
        if ((instr->Mask(0x00C00000) != 0x00000000) ||
            (instr->Mask(0x00001400) == 0x00001400) ||
            (instr->Mask(0x00001800) == 0x00001800)) {
          V::VisitUnallocated(instr);
        } else {
          V::VisitAddSubExtended(instr);
        }
      }
    } else {
      if ((instr->Bit(30) == 0x1) || (instr->Bits(30, 29) == 0x1) ||
          (instr->Mask(0xE0600000) == 0x00200000) ||
          (instr->Mask(0xE0608000) == 0x00400000) ||
          (instr->Mask(0x60608000) == 0x00408000) ||
          (instr->Mask(0x60E00000) == 0x00E00000) ||
          (instr->Mask(0x60E00000) == 0x00800000) ||
          (instr->Mask(0x60E00000) == 0x00600000)) {
        V::VisitUnallocated(instr);
      } else {
        V::VisitDataProcessing3Source(instr);
      }
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), v8::internal::DCHECK(), and v8::internal::Instruction::Mask().
DecodeFP()
template<typename V >
void v8::internal::Decoder< V >::DecodeFP (Instruction * instr) [private]
Definition at line 520 of file decoder-arm64-inl.h.
                                            {
  DCHECK((instr->Bits(27, 24) == 0xE) || (instr->Bits(27, 24) == 0xF));
  if (instr->Bit(28) == 0) {
    DecodeNEONVectorDataProcessing(instr);
  } else {
    if (instr->Bits(31, 30) == 0x3) {
      V::VisitUnallocated(instr);
    } else if (instr->Bits(31, 30) == 0x1) {
      DecodeNEONScalarDataProcessing(instr);
    } else {
      if (instr->Bit(29) == 0) {
        if (instr->Bit(24) == 0) {
          if (instr->Bit(21) == 0) {
            if ((instr->Bit(23) == 1) || (instr->Bit(18) == 1) ||
                (instr->Mask(0x80008000) == 0x00000000) ||
                (instr->Mask(0x000E0000) == 0x00000000) ||
                (instr->Mask(0x000E0000) == 0x000A0000) ||
                (instr->Mask(0x00160000) == 0x00000000) ||
                (instr->Mask(0x00160000) == 0x00120000)) {
              V::VisitUnallocated(instr);
            } else {
              V::VisitFPFixedPointConvert(instr);
            }
          } else {
            if (instr->Bits(15, 10) == 32) {
              V::VisitUnallocated(instr);
            } else if (instr->Bits(15, 10) == 0) {
              if ((instr->Bits(23, 22) == 0x3) ||
                  (instr->Mask(0x000E0000) == 0x000A0000) ||
                  (instr->Mask(0x000E0000) == 0x000C0000) ||
                  (instr->Mask(0x00160000) == 0x00120000) ||
                  (instr->Mask(0x00160000) == 0x00140000) ||
                  (instr->Mask(0x20C40000) == 0x00800000) ||
                  (instr->Mask(0x20C60000) == 0x00840000) ||
                  (instr->Mask(0xA0C60000) == 0x80060000) ||
                  (instr->Mask(0xA0C60000) == 0x00860000) ||
                  (instr->Mask(0xA0CE0000) == 0x80860000) ||
                  (instr->Mask(0xA0CE0000) == 0x804E0000) ||
                  (instr->Mask(0xA0CE0000) == 0x000E0000) ||
                  (instr->Mask(0xA0D60000) == 0x00160000) ||
                  (instr->Mask(0xA0D60000) == 0x80560000) ||
                  (instr->Mask(0xA0D60000) == 0x80960000)) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitFPIntegerConvert(instr);
              }
            } else if (instr->Bits(14, 10) == 16) {
              const Instr masked_A0DF8000 = instr->Mask(0xA0DF8000);
              if ((instr->Mask(0x80180000) != 0) ||
                  (masked_A0DF8000 == 0x00020000) ||
                  (masked_A0DF8000 == 0x00030000) ||
                  (masked_A0DF8000 == 0x00068000) ||
                  (masked_A0DF8000 == 0x00428000) ||
                  (masked_A0DF8000 == 0x00430000) ||
                  (masked_A0DF8000 == 0x00468000) ||
                  (instr->Mask(0xA0D80000) == 0x00800000) ||
                  (instr->Mask(0xA0DE0000) == 0x00C00000) ||
                  (instr->Mask(0xA0DF0000) == 0x00C30000) ||
                  (instr->Mask(0xA0DC0000) == 0x00C40000)) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitFPDataProcessing1Source(instr);
              }
            } else if (instr->Bits(13, 10) == 8) {
              if ((instr->Bits(15, 14) != 0) || (instr->Bits(2, 0) != 0) ||
                  (instr->Mask(0x80800000) != 0x00000000)) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitFPCompare(instr);
              }
            } else if (instr->Bits(12, 10) == 4) {
              if ((instr->Bits(9, 5) != 0) ||
                  (instr->Mask(0x80800000) != 0x00000000)) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitFPImmediate(instr);
              }
            } else {
              if (instr->Mask(0x80800000) != 0x00000000) {
                V::VisitUnallocated(instr);
              } else {
                switch (instr->Bits(11, 10)) {
                  case 1: {
                    V::VisitFPConditionalCompare(instr);
                    break;
                  }
                  case 2: {
                    if ((instr->Bits(15, 14) == 0x3) ||
                        (instr->Mask(0x00009000) == 0x00009000) ||
                        (instr->Mask(0x0000A000) == 0x0000A000)) {
                      V::VisitUnallocated(instr);
                    } else {
                      V::VisitFPDataProcessing2Source(instr);
                    }
                    break;
                  }
                  case 3: {
                    V::VisitFPConditionalSelect(instr);
                    break;
                  }
                  default:
                    UNREACHABLE();
                }
              }
            }
          }
        } else {
          // Bit 30 == 1 has been handled earlier.
          DCHECK_EQ(0, instr->Bit(30));
          if (instr->Mask(0xA0800000) != 0) {
            V::VisitUnallocated(instr);
          } else {
            V::VisitFPDataProcessing3Source(instr);
          }
        }
      } else {
        V::VisitUnallocated(instr);
      }
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Instruction::Mask(), and v8::internal::UNREACHABLE().
DecodeIType()
template<typename V >
void v8::internal::Decoder< V >::DecodeIType (Instruction * instr) [private]
Definition at line 1668 of file disasm-riscv.cc.
                                            {
  switch (instr->InstructionBits() & kITypeMask) {
    case RO_JALR:
      if (instr->RdValue() == zero_reg.code() &&
          instr->Rs1Value() == ra.code() && instr->Imm12Value() == 0)
        Format(instr, "ret");
      else if (instr->RdValue() == zero_reg.code() && instr->Imm12Value() == 0)
        Format(instr, "jr 'rs1");
      else if (instr->RdValue() == ra.code() && instr->Imm12Value() == 0)
        Format(instr, "jalr 'rs1");
      else
        Format(instr, "jalr 'rd, 'imm12('rs1)");
      break;
    case RO_LB:
      Format(instr, "lb 'rd, 'imm12('rs1)");
      break;
    case RO_LH:
      Format(instr, "lh 'rd, 'imm12('rs1)");
      break;
    case RO_LW:
      Format(instr, "lw 'rd, 'imm12('rs1)");
      break;
    case RO_LBU:
      Format(instr, "lbu 'rd, 'imm12('rs1)");
      break;
    case RO_LHU:
      Format(instr, "lhu 'rd, 'imm12('rs1)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_LWU:
      Format(instr, "lwu 'rd, 'imm12('rs1)");
      break;
    case RO_LD:
      Format(instr, "ld 'rd, 'imm12('rs1)");
      break;
#endif /*V8_TARGET_ARCH_64_BIT*/
    case RO_ADDI:
      if (instr->Imm12Value() == 0) {
        if (instr->RdValue() == zero_reg.code() &&
            instr->Rs1Value() == zero_reg.code())
          Format(instr, "nop");
        else
          Format(instr, "mv 'rd, 'rs1");
      } else if (instr->Rs1Value() == zero_reg.code()) {
        Format(instr, "li 'rd, 'imm12");
      } else {
        Format(instr, "addi 'rd, 'rs1, 'imm12");
      }
      break;
    case RO_SLTI:
      Format(instr, "slti 'rd, 'rs1, 'imm12");
      break;
    case RO_SLTIU:
      if (instr->Imm12Value() == 1)
        Format(instr, "seqz 'rd, 'rs1");
      else
        Format(instr, "sltiu 'rd, 'rs1, 'imm12");
      break;
    case RO_XORI:
      if (instr->Imm12Value() == -1)
        Format(instr, "not 'rd, 'rs1");
      else
        Format(instr, "xori 'rd, 'rs1, 'imm12x");
      break;
    case RO_ORI:
      Format(instr, "ori 'rd, 'rs1, 'imm12x");
      break;
    case RO_ANDI:
      Format(instr, "andi 'rd, 'rs1, 'imm12x");
      break;
    case OP_SHL:
      switch (instr->Funct6FieldRaw() | OP_SHL) {
        case RO_SLLI:
          Format(instr, "slli 'rd, 'rs1, 's64");
          break;
        case RO_BCLRI:
          Format(instr, "bclri 'rd, 'rs1, 's64");
          break;
        case RO_BINVI:
          Format(instr, "binvi 'rd, 'rs1, 's64");
          break;
        case RO_BSETI:
          Format(instr, "bseti 'rd, 'rs1, 's64");
          break;
        case OP_COUNT:
          switch (instr->Shamt()) {
            case 0:
              Format(instr, "clz 'rd, 'rs1");
              break;
            case 1:
              Format(instr, "ctz 'rd, 'rs1");
              break;
            case 2:
              Format(instr, "cpop 'rd, 'rs1");
              break;
            case 4:
              Format(instr, "sext.b 'rd, 'rs1");
              break;
            case 5:
              Format(instr, "sext.h 'rd, 'rs1");
              break;
            default:
              UNSUPPORTED_RISCV();
          }
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    case OP_SHR: { // RO_SRAI
      switch (instr->Funct6FieldRaw() | OP_SHR) {
        case RO_SRLI:
          Format(instr, "srli 'rd, 'rs1, 's64");
          break;
        case RO_SRAI:
          Format(instr, "srai 'rd, 'rs1, 's64");
          break;
        case RO_BEXTI:
          Format(instr, "bexti 'rd, 'rs1, 's64");
          break;
        case RO_ORCB&(kFunct6Mask | OP_SHR):
          Format(instr, "orc.b 'rd, 'rs1");
          break;
        case RO_RORI:
#ifdef V8_TARGET_ARCH_64_BIT
          Format(instr, "rori 'rd, 'rs1, 's64");
          break;
#elif defined(V8_TARGET_ARCH_RISCV32)
          Format(instr, "rori 'rd, 'rs1, 's32");
          break;
#endif
        case RO_REV8: {
          if (instr->Imm12Value() == RO_REV8_IMM12) {
            Format(instr, "rev8 'rd, 'rs1");
            break;
          }
          UNSUPPORTED_RISCV();
        }
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_ADDIW:
      if (instr->Imm12Value() == 0)
        Format(instr, "sext.w 'rd, 'rs1");
      else
        Format(instr, "addiw 'rd, 'rs1, 'imm12");
      break;
    case OP_SHLW:
      switch (instr->Funct7FieldRaw() | OP_SHLW) {
        case RO_SLLIW:
          Format(instr, "slliw 'rd, 'rs1, 's32");
          break;
        case RO_SLLIUW:
          Format(instr, "slli.uw 'rd, 'rs1, 's32");
          break;
        case OP_COUNTW: {
          switch (instr->Shamt()) {
            case 0:
              Format(instr, "clzw 'rd, 'rs1");
              break;
            case 1:
              Format(instr, "ctzw 'rd, 'rs1");
              break;
            case 2:
              Format(instr, "cpopw 'rd, 'rs1");
              break;
            default:
              UNSUPPORTED_RISCV();
          }
          break;
        }
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    case OP_SHRW: { // RO_SRAI
      switch (instr->Funct7FieldRaw() | OP_SHRW) {
        case RO_SRLIW:
          Format(instr, "srliw 'rd, 'rs1, 's32");
          break;
        case RO_SRAIW:
          Format(instr, "sraiw 'rd, 'rs1, 's32");
          break;
        case RO_RORIW:
          Format(instr, "roriw 'rd, 'rs1, 's32");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
#endif /*V8_TARGET_ARCH_64_BIT*/
    case RO_FENCE:
      if (instr->MemoryOrder(true) == PSIORW &&
          instr->MemoryOrder(false) == PSIORW)
        Format(instr, "fence");
      else
        Format(instr, "fence 'pre, 'suc");
      break;
    case RO_ECALL: { // RO_EBREAK
      if (instr->Imm12Value() == 0) { // ECALL
        Format(instr, "ecall");
      } else if (instr->Imm12Value() == 1) { // EBREAK
        Format(instr, "ebreak");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    // TODO(riscv): use Zifencei Standard Extension macro block
    case RO_FENCE_I:
      Format(instr, "fence.i");
      break;
    // TODO(riscv): use Zicsr Standard Extension macro block
    // FIXME(RISC-V): Add special formatting for CSR registers
    case RO_CSRRW:
      if (instr->CsrValue() == csr_fcsr) {
        if (instr->RdValue() == zero_reg.code())
          Format(instr, "fscsr 'rs1");
        else
          Format(instr, "fscsr 'rd, 'rs1");
      } else if (instr->CsrValue() == csr_frm) {
        if (instr->RdValue() == zero_reg.code())
          Format(instr, "fsrm 'rs1");
        else
          Format(instr, "fsrm 'rd, 'rs1");
      } else if (instr->CsrValue() == csr_fflags) {
        if (instr->RdValue() == zero_reg.code())
          Format(instr, "fsflags 'rs1");
        else
          Format(instr, "fsflags 'rd, 'rs1");
      } else if (instr->RdValue() == zero_reg.code()) {
        Format(instr, "csrw 'csr, 'rs1");
      } else {
        Format(instr, "csrrw 'rd, 'csr, 'rs1");
      }
      break;
    case RO_CSRRS:
      if (instr->Rs1Value() == zero_reg.code()) {
        switch (instr->CsrValue()) {
          case csr_instret:
            Format(instr, "rdinstret 'rd");
            break;
          case csr_instreth:
            Format(instr, "rdinstreth 'rd");
            break;
          case csr_time:
            Format(instr, "rdtime 'rd");
            break;
          case csr_timeh:
            Format(instr, "rdtimeh 'rd");
            break;
          case csr_cycle:
            Format(instr, "rdcycle 'rd");
            break;
          case csr_cycleh:
            Format(instr, "rdcycleh 'rd");
            break;
          case csr_fflags:
            Format(instr, "frflags 'rd");
            break;
          case csr_frm:
            Format(instr, "frrm 'rd");
            break;
          case csr_fcsr:
            Format(instr, "frcsr 'rd");
            break;
          default:
            UNREACHABLE();
        }
      } else if (instr->Rs1Value() == zero_reg.code()) {
        Format(instr, "csrr 'rd, 'csr");
      } else if (instr->RdValue() == zero_reg.code()) {
        Format(instr, "csrs 'csr, 'rs1");
      } else {
        Format(instr, "csrrs 'rd, 'csr, 'rs1");
      }
      break;
    case RO_CSRRC:
      if (instr->RdValue() == zero_reg.code())
        Format(instr, "csrc 'csr, 'rs1");
      else
        Format(instr, "csrrc 'rd, 'csr, 'rs1");
      break;
    case RO_CSRRWI:
      if (instr->RdValue() == zero_reg.code())
        Format(instr, "csrwi 'csr, 'uimm");
      else
        Format(instr, "csrrwi 'rd, 'csr, 'uimm");
      break;
    case RO_CSRRSI:
      if (instr->RdValue() == zero_reg.code())
        Format(instr, "csrsi 'csr, 'uimm");
      else
        Format(instr, "csrrsi 'rd, 'csr, 'uimm");
      break;
    case RO_CSRRCI:
      if (instr->RdValue() == zero_reg.code())
        Format(instr, "csrci 'csr, 'uimm");
      else
        Format(instr, "csrrci 'rd, 'csr, 'uimm");
      break;
    // TODO(riscv): use F Extension macro block
    case RO_FLW:
      Format(instr, "flw 'fd, 'imm12('rs1)");
      break;
    case RO_FLH:
      Format(instr, "flh 'fd, 'imm12('rs1)");
      break;
    // TODO(riscv): use D Extension macro block
    case RO_FLD:
      Format(instr, "fld 'fd, 'imm12('rs1)");
      break;
    default:
#ifdef CAN_USE_RVV_INSTRUCTIONS
      if (instr->vl_vs_width() != -1) {
        DecodeRvvVL(instr);
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
#else
      UNSUPPORTED_RISCV();
#endif
  }
}
References v8::internal::csr_cycle, v8::internal::csr_cycleh, v8::internal::csr_fcsr, v8::internal::csr_fflags, v8::internal::csr_frm, v8::internal::csr_instret, v8::internal::csr_instreth, v8::internal::csr_time, v8::internal::csr_timeh, v8::internal::InstructionGetters< T >::CsrValue(), v8::internal::Decoder< V >::DecodeRvvVL(), v8::internal::Decoder< V >::Format(), v8::internal::InstructionBase::Funct6FieldRaw(), v8::internal::InstructionBase::Funct7FieldRaw(), v8::internal::InstructionGetters< T >::Imm12Value(), v8::internal::Instruction::InstructionBits(), v8::internal::kFunct6Mask, v8::internal::kITypeMask, v8::internal::InstructionGetters< T >::MemoryOrder(), v8::internal::OP_COUNT, v8::internal::OP_SHL, v8::internal::OP_SHR, v8::internal::PSIORW, v8::internal::Instruction::RdValue(), v8::internal::RO_ADDI, v8::internal::RO_ANDI, v8::internal::RO_BCLRI, v8::internal::RO_BEXTI, v8::internal::RO_BINVI, v8::internal::RO_BSETI, v8::internal::RO_CSRRC, v8::internal::RO_CSRRCI, v8::internal::RO_CSRRS, v8::internal::RO_CSRRSI, v8::internal::RO_CSRRW, v8::internal::RO_CSRRWI, v8::internal::RO_ECALL, v8::internal::RO_FENCE, v8::internal::RO_FENCE_I, v8::internal::RO_FLD, v8::internal::RO_FLH, v8::internal::RO_FLW, v8::internal::RO_JALR, v8::internal::RO_LB, v8::internal::RO_LBU, v8::internal::RO_LH, v8::internal::RO_LHU, v8::internal::RO_LW, v8::internal::RO_ORCB, v8::internal::RO_ORI, v8::internal::RO_REV8, v8::internal::RO_SLLI, v8::internal::RO_SLTI, v8::internal::RO_SLTIU, v8::internal::RO_SRAI, v8::internal::RO_SRLI, v8::internal::RO_XORI, v8::internal::InstructionGetters< T >::Rs1Value(), v8::internal::InstructionGetters< T >::Shamt(), v8::internal::UNREACHABLE(), UNSUPPORTED_RISCV, and v8::internal::InstructionGetters< T >::vl_vs_width().
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeJType()
template<typename V >
void v8::internal::Decoder< V >::DecodeJType (Instruction * instr) [private]
Definition at line 2077 of file disasm-riscv.cc.
                                            {
  // J Type doesn't have additional mask
  switch (instr->BaseOpcodeValue()) {
    case JAL:
      if (instr->RdValue() == zero_reg.code())
        Format(instr, "j 'imm20J");
      else if (instr->RdValue() == ra.code())
        Format(instr, "jal 'imm20J");
      else
        Format(instr, "jal 'rd, 'imm20J");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::InstructionBase::BaseOpcodeValue(), v8::internal::Decoder< V >::Format(), v8::internal::JAL, v8::internal::Instruction::RdValue(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeLoadStore()
template<typename V >
void v8::internal::Decoder< V >::DecodeLoadStore (Instruction * instr) [private]
Definition at line 213 of file decoder-arm64-inl.h.
                                                   {
  DCHECK_EQ(0x8, instr->Bits(27, 24) & 0xA); // 0x8, 0x9, 0xC, 0xD
  if ((instr->Bit(28) == 0) && (instr->Bit(29) == 0) && (instr->Bit(26) == 1)) {
    DecodeNEONLoadStore(instr);
    return;
  }
  if (instr->Bit(24) == 0) {
    if (instr->Bit(28) == 0) {
      if (instr->Bit(29) == 0) {
        if (instr->Bit(26) == 0) {
          if (instr->Mask(0xA08000) == 0x800000) {
            V::VisitUnallocated(instr);
          } else if (instr->Mask(0xA08000) == 0) {
            // Load/Store exclusive without acquire/release are unimplemented.
            V::VisitUnimplemented(instr);
          } else {
            V::VisitLoadStoreAcquireRelease(instr);
          }
        } else {
          // This is handled by DecodeNEONLoadStore().
          UNREACHABLE();
        }
      } else {
        if ((instr->Bits(31, 30) == 0x3) ||
            (instr->Mask(0xC4400000) == 0x40000000)) {
          V::VisitUnallocated(instr);
        } else {
          if (instr->Bit(23) == 0) {
            if (instr->Mask(0xC4400000) == 0xC0400000) {
              V::VisitUnallocated(instr);
            } else {
              // Nontemporals are unimplemented.
              V::VisitUnimplemented(instr);
            }
          } else {
            V::VisitLoadStorePairPostIndex(instr);
          }
        }
      }
    } else {
      if (instr->Bit(29) == 0) {
        if (instr->Mask(0xC4000000) == 0xC4000000) {
          V::VisitUnallocated(instr);
        } else {
          V::VisitLoadLiteral(instr);
        }
      } else {
        if ((instr->Mask(0x44800000) == 0x44800000) ||
            (instr->Mask(0x84800000) == 0x84800000)) {
          V::VisitUnallocated(instr);
        } else {
          if (instr->Bit(21) == 0) {
            switch (instr->Bits(11, 10)) {
              case 0: {
                V::VisitLoadStoreUnscaledOffset(instr);
                break;
              }
              case 1: {
                if (instr->Mask(0xC4C00000) == 0xC0800000) {
                  V::VisitUnallocated(instr);
                } else {
                  V::VisitLoadStorePostIndex(instr);
                }
                break;
              }
              case 2: {
                // TODO(all): VisitLoadStoreRegisterOffsetUnpriv.
                V::VisitUnimplemented(instr);
                break;
              }
              case 3: {
                if (instr->Mask(0xC4C00000) == 0xC0800000) {
                  V::VisitUnallocated(instr);
                } else {
                  V::VisitLoadStorePreIndex(instr);
                }
                break;
              }
            }
          } else {
            if (instr->Bits(11, 10) == 0x2) {
              if (instr->Bit(14) == 0) {
                V::VisitUnallocated(instr);
              } else {
                V::VisitLoadStoreRegisterOffset(instr);
              }
            } else {
              if ((instr->Bits(11, 10) == 0x0) &&
                  (instr->Bits(26, 25) == 0x0)) {
                if ((instr->Bit(15) == 1) &&
                    ((instr->Bits(14, 12) == 0x1) || (instr->Bit(13) == 1) ||
                     (instr->Bits(14, 12) == 0x5) ||
                     ((instr->Bits(14, 12) == 0x4) &&
                      ((instr->Bit(23) == 0) ||
                       (instr->Bits(23, 22) == 0x3))))) {
                  V::VisitUnallocated(instr);
                } else {
                  V::VisitAtomicMemory(instr);
                }
              } else {
                V::VisitUnallocated(instr);
              }
            }
          }
        }
      }
    }
  } else {
    if (instr->Bit(28) == 0) {
      if (instr->Bit(29) == 0) {
        V::VisitUnallocated(instr);
      } else {
        if ((instr->Bits(31, 30) == 0x3) ||
            (instr->Mask(0xC4400000) == 0x40000000)) {
          V::VisitUnallocated(instr);
        } else {
          if (instr->Bit(23) == 0) {
            V::VisitLoadStorePairOffset(instr);
          } else {
            V::VisitLoadStorePairPreIndex(instr);
          }
        }
      }
    } else {
      if (instr->Bit(29) == 0) {
        V::VisitUnallocated(instr);
      } else {
        if ((instr->Mask(0x84C00000) == 0x80C00000) ||
            (instr->Mask(0x44800000) == 0x44800000) ||
            (instr->Mask(0x84800000) == 0x84800000)) {
          V::VisitUnallocated(instr);
        } else {
          V::VisitLoadStoreUnsignedOffset(instr);
        }
      }
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), DCHECK_EQ, v8::internal::Instruction::Mask(), and v8::internal::UNREACHABLE().
DecodeLogical()
template<typename V >
void v8::internal::Decoder< V >::DecodeLogical (Instruction * instr) [private]
Definition at line 355 of file decoder-arm64-inl.h.
                                                 {
  DCHECK_EQ(0x2, instr->Bits(27, 24));
  if (instr->Mask(0x80400000) == 0x00400000) {
    V::VisitUnallocated(instr);
  } else {
    if (instr->Bit(23) == 0) {
      V::VisitLogicalImmediate(instr);
    } else {
      if (instr->Bits(30, 29) == 0x1) {
        V::VisitUnallocated(instr);
      } else {
        V::VisitMoveWideImmediate(instr);
      }
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), DCHECK_EQ, and v8::internal::Instruction::Mask().
DecodeNEONLoadStore()
template<typename V >
void v8::internal::Decoder< V >::DecodeNEONLoadStore (Instruction * instr) [private]
Definition at line 644 of file decoder-arm64-inl.h.
                                                       {
  DCHECK_EQ(0x6, instr->Bits(29, 25));
  if (instr->Bit(31) == 0) {
    if ((instr->Bit(24) == 0) && (instr->Bit(21) == 1)) {
      V::VisitUnallocated(instr);
      return;
    }
    if (instr->Bit(23) == 0) {
      if (instr->Bits(20, 16) == 0) {
        if (instr->Bit(24) == 0) {
          V::VisitNEONLoadStoreMultiStruct(instr);
        } else {
          V::VisitNEONLoadStoreSingleStruct(instr);
        }
      } else {
        V::VisitUnallocated(instr);
      }
    } else {
      if (instr->Bit(24) == 0) {
        V::VisitNEONLoadStoreMultiStructPostIndex(instr);
      } else {
        V::VisitNEONLoadStoreSingleStructPostIndex(instr);
      }
    }
  } else {
    V::VisitUnallocated(instr);
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), and DCHECK_EQ.
DecodeNEONScalarDataProcessing()
template<typename V >
void v8::internal::Decoder< V >::DecodeNEONScalarDataProcessing (Instruction * instr) [private]
Definition at line 766 of file decoder-arm64-inl.h.
                                                                  {
  DCHECK_EQ(0xF, instr->Bits(28, 25));
  if (instr->Bit(24) == 0) {
    if (instr->Bit(21) == 0) {
      if (instr->Bit(15) == 0) {
        if (instr->Bit(10) == 0) {
          if (instr->Bit(29) == 0) {
            if (instr->Bit(11) == 0) {
              V::VisitUnallocated(instr);
            } else {
              V::VisitUnallocated(instr);
            }
          } else {
            V::VisitUnallocated(instr);
          }
        } else {
          if (instr->Bits(23, 22) == 0) {
            V::VisitNEONScalarCopy(instr);
          } else {
            V::VisitUnallocated(instr);
          }
        }
      } else {
        V::VisitUnallocated(instr);
      }
    } else {
      if (instr->Bit(10) == 0) {
        if (instr->Bit(11) == 0) {
          V::VisitNEONScalar3Diff(instr);
        } else {
          if (instr->Bits(18, 17) == 0) {
            if (instr->Bit(20) == 0) {
              if (instr->Bit(19) == 0) {
                V::VisitNEONScalar2RegMisc(instr);
              } else {
                if (instr->Bit(29) == 0) {
                  V::VisitUnallocated(instr);
                } else {
                  V::VisitUnallocated(instr);
                }
              }
            } else {
              if (instr->Bit(19) == 0) {
                V::VisitNEONScalarPairwise(instr);
              } else {
                V::VisitUnallocated(instr);
              }
            }
          } else {
            V::VisitUnallocated(instr);
          }
        }
      } else {
        V::VisitNEONScalar3Same(instr);
      }
    }
  } else {
    if (instr->Bit(10) == 0) {
      V::VisitNEONScalarByIndexedElement(instr);
    } else {
      if (instr->Bit(23) == 0) {
        V::VisitNEONScalarShiftImmediate(instr);
      } else {
        V::VisitUnallocated(instr);
      }
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), and DCHECK_EQ.
DecodeNEONVectorDataProcessing()
template<typename V >
void v8::internal::Decoder< V >::DecodeNEONVectorDataProcessing (Instruction * instr) [private]
Definition at line 675 of file decoder-arm64-inl.h.
                                                                  {
  DCHECK_EQ(0x7, instr->Bits(28, 25));
  if (instr->Bit(31) == 0) {
    if (instr->Bit(24) == 0) {
      if (instr->Bit(21) == 0) {
        if (instr->Bit(15) == 0) {
          if (instr->Bit(10) == 0) {
            if (instr->Bit(29) == 0) {
              if (instr->Bit(11) == 0) {
                V::VisitNEONTable(instr);
              } else {
                V::VisitNEONPerm(instr);
              }
            } else {
              V::VisitNEONExtract(instr);
            }
          } else {
            if (instr->Bits(23, 22) == 0) {
              V::VisitNEONCopy(instr);
            } else {
              if (instr->Bit(14) == 0 && instr->Bit(22)) {
                V::VisitNEON3SameHP(instr);
              } else {
                V::VisitUnallocated(instr);
              }
            }
          }
        } else {
          if (instr->Bit(10) == 1) {
            V::VisitNEON3Extension(instr);
          } else {
            V::VisitUnallocated(instr);
          }
        }
      } else {
        if (instr->Bit(10) == 0) {
          if (instr->Bit(11) == 0) {
            V::VisitNEON3Different(instr);
          } else {
            if (instr->Bits(18, 17) == 0) {
              if (instr->Bit(20) == 0) {
                if (instr->Bit(19) == 0) {
                  V::VisitNEON2RegMisc(instr);
                } else {
                  if (instr->Bits(30, 29) == 0x2) {
                    V::VisitUnallocated(instr);
                  } else {
                    V::VisitUnallocated(instr);
                  }
                }
              } else {
                if (instr->Bit(19) == 0) {
                  V::VisitNEONAcrossLanes(instr);
                } else {
                  // Half-precision version.
                  V::VisitNEON2RegMisc(instr);
                }
              }
            } else {
              V::VisitUnallocated(instr);
            }
          }
        } else {
          V::VisitNEON3Same(instr);
        }
      }
    } else {
      if (instr->Bit(10) == 0) {
        V::VisitNEONByIndexedElement(instr);
      } else {
        if (instr->Bit(23) == 0) {
          if (instr->Bits(22, 19) == 0) {
            V::VisitNEONModifiedImmediate(instr);
          } else {
            V::VisitNEONShiftImmediate(instr);
          }
        } else {
          V::VisitUnallocated(instr);
        }
      }
    }
  } else {
    if (instr->Bit(30) == 1) {
      V::VisitNEONSHA3(instr);
    } else {
      V::VisitUnallocated(instr);
    }
  }
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), and DCHECK_EQ.
DecodePCRelAddressing()
template<typename V >
void v8::internal::Decoder< V >::DecodePCRelAddressing (Instruction * instr) [private]
Definition at line 115 of file decoder-arm64-inl.h.
                                                         {
  DCHECK_EQ(0x0, instr->Bits(27, 24));
  // We know bit 28 is set, as <b28:b27> = 0 is filtered out at the top level
  // decode.
  DCHECK_EQ(0x1, instr->Bit(28));
  V::VisitPCRelAddressing(instr);
}
References v8::internal::Instruction::Bit(), v8::internal::Instruction::Bits(), and DCHECK_EQ.
DecodeR4Type()
template<typename V >
void v8::internal::Decoder< V >::DecodeR4Type (Instruction * instr) [private]
Definition at line 1622 of file disasm-riscv.cc.
                                             {
  switch (instr->InstructionBits() & kR4TypeMask) {
    // TODO(riscv): use F Extension macro block
    case RO_FMADD_S:
      Format(instr, "fmadd.s 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FMSUB_S:
      Format(instr, "fmsub.s 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FNMSUB_S:
      Format(instr, "fnmsub.s 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FNMADD_S:
      Format(instr, "fnmadd.s 'fd, 'fs1, 'fs2, 'fs3");
      break;
    // TODO(riscv): use F Extension macro block
    case RO_FMADD_D:
      Format(instr, "fmadd.d 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FMSUB_D:
      Format(instr, "fmsub.d 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FNMSUB_D:
      Format(instr, "fnmsub.d 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FNMADD_D:
      Format(instr, "fnmadd.d 'fd, 'fs1, 'fs2, 'fs3");
      break;
    // TODO(riscv): use ZFH Extension macro block
    case RO_FMADD_H:
      Format(instr, "fmadd.h 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FMSUB_H:
      Format(instr, "fmsub.h 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FNMSUB_H:
      Format(instr, "fnmsub.h 'fd, 'fs1, 'fs2, 'fs3");
      break;
    case RO_FNMADD_H:
      Format(instr, "fnmadd.h 'fd, 'fs1, 'fs2, 'fs3");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kR4TypeMask, v8::internal::RO_FMADD_D, v8::internal::RO_FMADD_H, v8::internal::RO_FMADD_S, v8::internal::RO_FMSUB_D, v8::internal::RO_FMSUB_H, v8::internal::RO_FMSUB_S, v8::internal::RO_FNMADD_D, v8::internal::RO_FNMADD_H, v8::internal::RO_FNMADD_S, v8::internal::RO_FNMSUB_D, v8::internal::RO_FNMSUB_H, v8::internal::RO_FNMSUB_S, and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeRAType()
template<typename V >
void v8::internal::Decoder< V >::DecodeRAType (Instruction * instr) [private]
Definition at line 1073 of file disasm-riscv.cc.
                                             {
  // TODO(riscv): Add macro for RISCV A extension
  // Special handling for A extension instructions because it uses func5
  // For all A extension instruction, V8 simulator is pure sequential. No
  // Memory address lock or other synchronizaiton behaviors.
  switch (instr->InstructionBits() & kRATypeMask) {
    case RO_LR_W:
      Format(instr, "lr.w'a 'rd, ('rs1)");
      break;
    case RO_SC_W:
      Format(instr, "sc.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOSWAP_W:
      Format(instr, "amoswap.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOADD_W:
      Format(instr, "amoadd.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOXOR_W:
      Format(instr, "amoxor.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOAND_W:
      Format(instr, "amoand.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOOR_W:
      Format(instr, "amoor.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMIN_W:
      Format(instr, "amomin.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMAX_W:
      Format(instr, "amomax.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMINU_W:
      Format(instr, "amominu.w'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMAXU_W:
      Format(instr, "amomaxu.w'a 'rd, 'rs2, ('rs1)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_LR_D:
      Format(instr, "lr.d'a 'rd, ('rs1)");
      break;
    case RO_SC_D:
      Format(instr, "sc.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOSWAP_D:
      Format(instr, "amoswap.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOADD_D:
      Format(instr, "amoadd.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOXOR_D:
      Format(instr, "amoxor.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOAND_D:
      Format(instr, "amoand.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOOR_D:
      Format(instr, "amoor.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMIN_D:
      Format(instr, "amomin.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMAX_D:
      Format(instr, "amomax.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMINU_D:
      Format(instr, "amominu.d'a 'rd, 'rs2, ('rs1)");
      break;
    case RO_AMOMAXU_D:
      Format(instr, "amomaxu.d'a 'rd, 'rs2, ('rs1)");
      break;
#endif /*V8_TARGET_ARCH_64_BIT*/
    // TODO(riscv): End Add macro for RISCV A extension
    default: {
      UNSUPPORTED_RISCV();
    }
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kRATypeMask, v8::internal::RO_AMOADD_W, v8::internal::RO_AMOAND_W, v8::internal::RO_AMOMAX_W, v8::internal::RO_AMOMAXU_W, v8::internal::RO_AMOMIN_W, v8::internal::RO_AMOMINU_W, v8::internal::RO_AMOOR_W, v8::internal::RO_AMOSWAP_W, v8::internal::RO_AMOXOR_W, v8::internal::RO_LR_W, v8::internal::RO_SC_W, and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::DecodeRType().
DecodeRFPType()
template<typename V >
void v8::internal::Decoder< V >::DecodeRFPType (Instruction * instr) [private]
Definition at line 1154 of file disasm-riscv.cc.
                                              {
  // OP_FP instructions (F/D) uses func7 first. Some further uses fun3 and rs2()
  // kRATypeMask is only for func7
  switch (instr->InstructionBits() & kRFPTypeMask) {
    // TODO(riscv): Add macro for RISCV F extension
    case RO_FADD_S:
      Format(instr, "fadd.s 'fd, 'fs1, 'fs2");
      break;
    case RO_FSUB_S:
      Format(instr, "fsub.s 'fd, 'fs1, 'fs2");
      break;
    case RO_FMUL_S:
      Format(instr, "fmul.s 'fd, 'fs1, 'fs2");
      break;
    case RO_FDIV_S:
      Format(instr, "fdiv.s 'fd, 'fs1, 'fs2");
      break;
    case RO_FSQRT_S:
      Format(instr, "fsqrt.s 'fd, 'fs1");
      break;
    case RO_FSGNJ_S: { // RO_FSGNJN_S RO_FSGNJX_S
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FSGNJ_S
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fmv.s 'fd, 'fs1");
          else
            Format(instr, "fsgnj.s 'fd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FSGNJN_S
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fneg.s 'fd, 'fs1");
          else
            Format(instr, "fsgnjn.s 'fd, 'fs1, 'fs2");
          break;
        case 0b010: // RO_FSGNJX_S
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fabs.s 'fd, 'fs1");
          else
            Format(instr, "fsgnjx.s 'fd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FMIN_S: { // RO_FMAX_S
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FMIN_S
          Format(instr, "fmin.s 'fd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FMAX_S
          Format(instr, "fmax.s 'fd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_W_S: { // RO_FCVT_WU_S , 64F RO_FCVT_L_S RO_FCVT_LU_S
      switch (instr->Rs2Value()) {
        case 0b00000: // RO_FCVT_W_S
          Format(instr, "fcvt.w.s ['frm] 'rd, 'fs1");
          break;
        case 0b00001: // RO_FCVT_WU_S
          Format(instr, "fcvt.wu.s ['frm] 'rd, 'fs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b00010: // RO_FCVT_L_S
          Format(instr, "fcvt.l.s ['frm] 'rd, 'fs1");
          break;
        case 0b00011: // RO_FCVT_LU_S
          Format(instr, "fcvt.lu.s ['frm] 'rd, 'fs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FMV_X_W: { // RO_FCLASS_S
      if (instr->Rs2Value() != 0b00000) {
        UNSUPPORTED_RISCV();
      }
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FMV_X_W
          Format(instr, "fmv.x.w 'rd, 'fs1");
          break;
        case 0b001: // RO_FCLASS_S
          Format(instr, "fclass.s 'rd, 'fs1");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FLE_S: { // RO_FEQ_S RO_FLT_S RO_FLE_S
      switch (instr->Funct3Value()) {
        case 0b010: // RO_FEQ_S
          Format(instr, "feq.s 'rd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FLT_S
          Format(instr, "flt.s 'rd, 'fs1, 'fs2");
          break;
        case 0b000: // RO_FLE_S
          Format(instr, "fle.s 'rd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_S_W: { // RO_FCVT_S_WU , 64F RO_FCVT_S_L RO_FCVT_S_LU
      switch (instr->Rs2Value()) {
        case 0b00000: // RO_FCVT_S_W
          Format(instr, "fcvt.s.w 'fd, 'rs1");
          break;
        case 0b00001: // RO_FCVT_S_WU
          Format(instr, "fcvt.s.wu 'fd, 'rs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b00010: // RO_FCVT_S_L
          Format(instr, "fcvt.s.l 'fd, 'rs1");
          break;
        case 0b00011: // RO_FCVT_S_LU
          Format(instr, "fcvt.s.lu 'fd, 'rs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default: {
          UNSUPPORTED_RISCV();
        }
      }
      break;
    }
    case RO_FMV_W_X: {
      if (instr->Funct3Value() == 0b000) {
        Format(instr, "fmv.w.x 'fd, 'rs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    // TODO(riscv): Add macro for RISCV D extension
    case RO_FADD_D:
      Format(instr, "fadd.d 'fd, 'fs1, 'fs2");
      break;
    case RO_FSUB_D:
      Format(instr, "fsub.d 'fd, 'fs1, 'fs2");
      break;
    case RO_FMUL_D:
      Format(instr, "fmul.d 'fd, 'fs1, 'fs2");
      break;
    case RO_FDIV_D:
      Format(instr, "fdiv.d 'fd, 'fs1, 'fs2");
      break;
    case RO_FSQRT_D: {
      if (instr->Rs2Value() == 0b00000) {
        Format(instr, "fsqrt.d 'fd, 'fs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FSGNJ_D: { // RO_FSGNJN_D RO_FSGNJX_D
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FSGNJ_D
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fmv.d 'fd, 'fs1");
          else
            Format(instr, "fsgnj.d 'fd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FSGNJN_D
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fneg.d 'fd, 'fs1");
          else
            Format(instr, "fsgnjn.d 'fd, 'fs1, 'fs2");
          break;
        case 0b010: // RO_FSGNJX_D
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fabs.d 'fd, 'fs1");
          else
            Format(instr, "fsgnjx.d 'fd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FMIN_D: { // RO_FMAX_D
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FMIN_D
          Format(instr, "fmin.d 'fd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FMAX_D
          Format(instr, "fmax.d 'fd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case (RO_FCVT_S_D & kRFPTypeMask): {
      if (instr->Rs2Value() == 0b00001) {
        Format(instr, "fcvt.s.d ['frm] 'fd, 'fs1");
      } else if (instr->Rs2Value() == 0b00010) {
        Format(instr, "fcvt.s.h ['frm] 'fd, 'fs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_D_S: { // RO_FCVT_D_H
      if (instr->Rs2Value() == 0b00000) {
        Format(instr, "fcvt.d.s ['frm] 'fd, 'fs1");
      } else if (instr->Rs2Value() == 0b00010) {
        Format(instr, "fcvt.d.h ['frm] 'fd, 'fs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FLE_D: { // RO_FEQ_D RO_FLT_D RO_FLE_D
      switch (instr->Funct3Value()) {
        case 0b010: // RO_FEQ_S
          Format(instr, "feq.d 'rd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FLT_D
          Format(instr, "flt.d 'rd, 'fs1, 'fs2");
          break;
        case 0b000: // RO_FLE_D
          Format(instr, "fle.d 'rd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case (RO_FCLASS_D & kRFPTypeMask): { // RO_FCLASS_D , 64D RO_FMV_X_D
      if (instr->Rs2Value() != 0b00000) {
        UNSUPPORTED_RISCV();
      }
      switch (instr->Funct3Value()) {
        case 0b001: // RO_FCLASS_D
          Format(instr, "fclass.d 'rd, 'fs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b000: // RO_FMV_X_D
          Format(instr, "fmv.x.d 'rd, 'fs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_W_D: { // RO_FCVT_WU_D , 64F RO_FCVT_L_D RO_FCVT_LU_D
      switch (instr->Rs2Value()) {
        case 0b00000: // RO_FCVT_W_D
          Format(instr, "fcvt.w.d ['frm] 'rd, 'fs1");
          break;
        case 0b00001: // RO_FCVT_WU_D
          Format(instr, "fcvt.wu.d ['frm] 'rd, 'fs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b00010: // RO_FCVT_L_D
          Format(instr, "fcvt.l.d ['frm] 'rd, 'fs1");
          break;
        case 0b00011: // RO_FCVT_LU_D
          Format(instr, "fcvt.lu.d ['frm] 'rd, 'fs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_D_W: { // RO_FCVT_D_WU , 64F RO_FCVT_D_L RO_FCVT_D_LU
      switch (instr->Rs2Value()) {
        case 0b00000: // RO_FCVT_D_W
          Format(instr, "fcvt.d.w 'fd, 'rs1");
          break;
        case 0b00001: // RO_FCVT_D_WU
          Format(instr, "fcvt.d.wu 'fd, 'rs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b00010: // RO_FCVT_D_L
          Format(instr, "fcvt.d.l 'fd, 'rs1");
          break;
        case 0b00011: // RO_FCVT_D_LU
          Format(instr, "fcvt.d.lu 'fd, 'rs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_FMV_D_X: {
      if (instr->Funct3Value() == 0b000 && instr->Rs2Value() == 0b00000) {
        Format(instr, "fmv.d.x 'fd, 'rs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
#endif /* V8_TARGET_ARCH_64_BIT */
    // TODO(riscv): Add macro for RISCV ZFH extension
    case RO_FADD_H:
      Format(instr, "fadd.h 'fd, 'fs1, 'fs2");
      break;
    case RO_FSUB_H:
      Format(instr, "fsub.h 'fd, 'fs1, 'fs2");
      break;
    case RO_FMUL_H:
      Format(instr, "fmul.h 'fd, 'fs1, 'fs2");
      break;
    case RO_FDIV_H:
      Format(instr, "fdiv.h 'fd, 'fs1, 'fs2");
      break;
    case RO_FSQRT_H:
      Format(instr, "fsqrt.h 'fd, 'fs1");
      break;
    case RO_FSGNJ_H: { // RO_FSGNJN_H RO_FSGNJX_H
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FSGNJ_H
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fmv.h 'fd, 'fs1");
          else
            Format(instr, "fsgnj.h 'fd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FSGNJN_H
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fneg.h 'fd, 'fs1");
          else
            Format(instr, "fsgnjn.h 'fd, 'fs1, 'fs2");
          break;
        case 0b010: // RO_FSGNJX_H
          if (instr->Rs1Value() == instr->Rs2Value())
            Format(instr, "fabs.h 'fd, 'fs1");
          else
            Format(instr, "fsgnjx.h 'fd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FMIN_H: { // RO_FMAX_H
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FMIN_H
          Format(instr, "fmin.h 'fd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FMAX_H
          Format(instr, "fmax.h 'fd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_W_H: { // RO_FCVT_WU_H , 64F RO_FCVT_L_H RO_FCVT_LU_H
      switch (instr->Rs2Value()) {
        case 0b00000: // RO_FCVT_W_H
          Format(instr, "fcvt.w.h ['frm] 'rd, 'fs1");
          break;
        case 0b00001: // RO_FCVT_WU_H
          Format(instr, "fcvt.wu.h ['frm] 'rd, 'fs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b00010: // RO_FCVT_L_H
          Format(instr, "fcvt.l.h ['frm] 'rd, 'fs1");
          break;
        case 0b00011: // RO_FCVT_LU_H
          Format(instr, "fcvt.lu.h ['frm] 'rd, 'fs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_S_H: {
      if (instr->Rs2Value() == 0b00010) {
        Format(instr, "fcvt.s.h ['frm] 'fd, 'fs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_H_S: {
      if (instr->Rs2Value() == 0b00000) {
        Format(instr, "fcvt.h.s ['frm] 'fd, 'fs1");
      } else if (instr->Rs2Value() == 0b00001) {
        Format(instr, "fcvt.h.d ['frm] 'fd, 'fs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FMV_X_H: { // RO_FCLASS_H
      if (instr->Rs2Value() != 0b00000) {
        UNSUPPORTED_RISCV();
      }
      switch (instr->Funct3Value()) {
        case 0b000: // RO_FMV_X_H
          Format(instr, "fmv.x.h 'rd, 'fs1");
          break;
        case 0b001: // RO_FCLASS_H
          Format(instr, "fclass.h 'rd, 'fs1");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FLE_H: { // RO_FEQ_H RO_FLT_H RO_FLE_H
      switch (instr->Funct3Value()) {
        case 0b010: // RO_FEQ_H
          Format(instr, "feq.h 'rd, 'fs1, 'fs2");
          break;
        case 0b001: // RO_FLT_H
          Format(instr, "flt.h 'rd, 'fs1, 'fs2");
          break;
        case 0b000: // RO_FLE_H
          Format(instr, "fle.h 'rd, 'fs1, 'fs2");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_FCVT_H_W: { // RO_FCVT_H_WU , 64F RO_FCVT_H_L RO_FCVT_H_LU
      switch (instr->Rs2Value()) {
        case 0b00000: // RO_FCVT_H_W
          Format(instr, "fcvt.h.w ['frm] 'fd, 'rs1");
          break;
        case 0b00001: // RO_FCVT_H_WU
          Format(instr, "fcvt.h.wu ['frm] 'fd, 'rs1");
          break;
#ifdef V8_TARGET_ARCH_64_BIT
        case 0b00010: // RO_FCVT_H_L
          Format(instr, "fcvt.h.l ['frm] 'fd, 'rs1");
          break;
        case 0b00011: // RO_FCVT_H_LU
          Format(instr, "fcvt.h.lu ['frm] 'fd, 'rs1");
          break;
#endif /* V8_TARGET_ARCH_64_BIT */
        default: {
          UNSUPPORTED_RISCV();
        }
      }
      break;
    }
    case RO_FMV_H_X: {
      if (instr->Funct3Value() == 0b000) {
        Format(instr, "fmv.h.x 'fd, 'rs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    default: {
      UNSUPPORTED_RISCV();
    }
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::InstructionGetters< T >::Funct3Value(), v8::internal::Instruction::InstructionBits(), v8::internal::kRFPTypeMask, v8::internal::RO_FADD_D, v8::internal::RO_FADD_H, v8::internal::RO_FADD_S, v8::internal::RO_FCLASS_D, v8::internal::RO_FCVT_D_S, v8::internal::RO_FCVT_D_W, v8::internal::RO_FCVT_H_S, v8::internal::RO_FCVT_H_W, v8::internal::RO_FCVT_S_D, v8::internal::RO_FCVT_S_H, v8::internal::RO_FCVT_S_W, v8::internal::RO_FCVT_W_D, v8::internal::RO_FCVT_W_H, v8::internal::RO_FCVT_W_S, v8::internal::RO_FDIV_D, v8::internal::RO_FDIV_H, v8::internal::RO_FDIV_S, v8::internal::RO_FLE_D, v8::internal::RO_FLE_H, v8::internal::RO_FLE_S, v8::internal::RO_FMIN_D, v8::internal::RO_FMIN_H, v8::internal::RO_FMIN_S, v8::internal::RO_FMUL_D, v8::internal::RO_FMUL_H, v8::internal::RO_FMUL_S, v8::internal::RO_FMV_H_X, v8::internal::RO_FMV_W_X, v8::internal::RO_FMV_X_H, v8::internal::RO_FMV_X_W, v8::internal::RO_FSGNJ_D, v8::internal::RO_FSGNJ_H, v8::internal::RO_FSGNJ_S, v8::internal::RO_FSQRT_D, v8::internal::RO_FSQRT_H, v8::internal::RO_FSQRT_S, v8::internal::RO_FSUB_D, v8::internal::RO_FSUB_H, v8::internal::RO_FSUB_S, v8::internal::InstructionGetters< T >::Rs1Value(), v8::internal::InstructionGetters< T >::Rs2Value(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::DecodeRType().
DecodeRType()
template<typename V >
void v8::internal::Decoder< V >::DecodeRType (Instruction * instr) [private]
Definition at line 872 of file disasm-riscv.cc.
                                            {
  switch (instr->InstructionBits() & kRTypeMask) {
    case RO_ADD:
      Format(instr, "add 'rd, 'rs1, 'rs2");
      break;
    case RO_SUB:
      if (instr->Rs1Value() == zero_reg.code())
        Format(instr, "neg 'rd, 'rs2");
      else
        Format(instr, "sub 'rd, 'rs1, 'rs2");
      break;
    case RO_SLL:
      Format(instr, "sll 'rd, 'rs1, 'rs2");
      break;
    case RO_SLT:
      if (instr->Rs2Value() == zero_reg.code())
        Format(instr, "sltz 'rd, 'rs1");
      else if (instr->Rs1Value() == zero_reg.code())
        Format(instr, "sgtz 'rd, 'rs2");
      else
        Format(instr, "slt 'rd, 'rs1, 'rs2");
      break;
    case RO_SLTU:
      if (instr->Rs1Value() == zero_reg.code())
        Format(instr, "snez 'rd, 'rs2");
      else
        Format(instr, "sltu 'rd, 'rs1, 'rs2");
      break;
    case RO_XOR:
      Format(instr, "xor 'rd, 'rs1, 'rs2");
      break;
    case RO_SRL:
      Format(instr, "srl 'rd, 'rs1, 'rs2");
      break;
    case RO_SRA:
      Format(instr, "sra 'rd, 'rs1, 'rs2");
      break;
    case RO_OR:
      Format(instr, "or 'rd, 'rs1, 'rs2");
      break;
    case RO_AND:
      Format(instr, "and 'rd, 'rs1, 'rs2");
      break;
    case RO_ANDN:
      Format(instr, "andn 'rd, 'rs1, 'rs2");
      break;
    case RO_ORN:
      Format(instr, "orn 'rd, 'rs1, 'rs2");
      break;
    case RO_XNOR:
      Format(instr, "xnor 'rd, 'rs1, 'rs2");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_ADDW:
      Format(instr, "addw 'rd, 'rs1, 'rs2");
      break;
    case RO_ADDUW:
      if (instr->Rs2Value() == zero_reg.code()) {
        Format(instr, "zext.w 'rd, 'rs1");
      } else {
        Format(instr, "add.uw 'rd, 'rs1, 'rs2");
      }
      break;
    case RO_SUBW:
      if (instr->Rs1Value() == zero_reg.code())
        Format(instr, "negw 'rd, 'rs2");
      else
        Format(instr, "subw 'rd, 'rs1, 'rs2");
      break;
    case RO_SLLW:
      Format(instr, "sllw 'rd, 'rs1, 'rs2");
      break;
    case RO_SRLW:
      Format(instr, "srlw 'rd, 'rs1, 'rs2");
      break;
    case RO_SRAW:
      Format(instr, "sraw 'rd, 'rs1, 'rs2");
      break;
#endif /* V8_TARGET_ARCH_64_BIT */
    // TODO(riscv): Add RISCV M extension macro
    case RO_MUL:
      Format(instr, "mul 'rd, 'rs1, 'rs2");
      break;
    case RO_MULH:
      Format(instr, "mulh 'rd, 'rs1, 'rs2");
      break;
    case RO_MULHSU:
      Format(instr, "mulhsu 'rd, 'rs1, 'rs2");
      break;
    case RO_MULHU:
      Format(instr, "mulhu 'rd, 'rs1, 'rs2");
      break;
    case RO_DIV:
      Format(instr, "div 'rd, 'rs1, 'rs2");
      break;
    case RO_DIVU:
      Format(instr, "divu 'rd, 'rs1, 'rs2");
      break;
    case RO_REM:
      Format(instr, "rem 'rd, 'rs1, 'rs2");
      break;
    case RO_REMU:
      Format(instr, "remu 'rd, 'rs1, 'rs2");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_MULW:
      Format(instr, "mulw 'rd, 'rs1, 'rs2");
      break;
    case RO_DIVW:
      Format(instr, "divw 'rd, 'rs1, 'rs2");
      break;
    case RO_DIVUW:
      Format(instr, "divuw 'rd, 'rs1, 'rs2");
      break;
    case RO_REMW:
      Format(instr, "remw 'rd, 'rs1, 'rs2");
      break;
    case RO_REMUW:
      Format(instr, "remuw 'rd, 'rs1, 'rs2");
      break;
    case RO_SH1ADDUW:
      Format(instr, "sh1add.uw 'rd, 'rs1, 'rs2");
      break;
    case RO_SH2ADDUW:
      Format(instr, "sh2add.uw 'rd, 'rs1, 'rs2");
      break;
    case RO_SH3ADDUW:
      Format(instr, "sh3add.uw 'rd, 'rs1, 'rs2");
      break;
    case RO_ROLW:
      Format(instr, "rolw 'rd, 'rs1, 'rs2");
      break;
    case RO_RORW:
      Format(instr, "rorw 'rd, 'rs1, 'rs2");
      break;
#endif /*V8_TARGET_ARCH_64_BIT*/
    case RO_SH1ADD:
      Format(instr, "sh1add 'rd, 'rs1, 'rs2");
      break;
    case RO_SH2ADD:
      Format(instr, "sh2add 'rd, 'rs1, 'rs2");
      break;
    case RO_SH3ADD:
      Format(instr, "sh3add 'rd, 'rs1, 'rs2");
      break;
    case RO_MAX:
      Format(instr, "max 'rd, 'rs1, 'rs2");
      break;
    case RO_MAXU:
      Format(instr, "maxu 'rd, 'rs1, 'rs2");
      break;
    case RO_MIN:
      Format(instr, "min 'rd, 'rs1, 'rs2");
      break;
    case RO_MINU:
      Format(instr, "minu 'rd, 'rs1, 'rs2");
      break;
    case RO_ZEXTH:
      Format(instr, "zext.h 'rd, 'rs1");
      break;
    case RO_ROL:
      Format(instr, "rol 'rd, 'rs1, 'rs2");
      break;
    case RO_ROR:
      Format(instr, "ror 'rd, 'rs1, 'rs2");
      break;
    case RO_BCLR:
      Format(instr, "bclr 'rd, 'rs1, 'rs2");
      break;
    case RO_BEXT:
      Format(instr, "bext 'rd, 'rs1, 'rs2");
      break;
    case RO_BINV:
      Format(instr, "binv 'rd, 'rs1, 'rs2");
      break;
    case RO_BSET:
      Format(instr, "bset 'rd, 'rs1, 'rs2");
      break;
    case RO_CZERO_EQZ:
      Format(instr, "czero.eqz 'rd, 'rs1, 'rs2");
      break;
    case RO_CZERO_NEZ:
      Format(instr, "czero.nez 'rd, 'rs1, 'rs2");
      break;
    // TODO(riscv): End Add RISCV M extension macro
    default: {
      switch (instr->BaseOpcode()) {
        case AMO:
          DecodeRAType(instr);
          break;
        case OP_FP:
          DecodeRFPType(instr);
          break;
        default:
          PrintF("instr:%x\n", instr->InstructionBits());
          UNSUPPORTED_RISCV();
      }
    }
  }
}
References v8::internal::AMO, v8::internal::InstructionGetters< T >::BaseOpcode(), v8::internal::Decoder< V >::DecodeRAType(), v8::internal::Decoder< V >::DecodeRFPType(), v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kRTypeMask, v8::internal::OP_FP, v8::internal::PrintF(), v8::internal::RO_ADD, v8::internal::RO_AND, v8::internal::RO_ANDN, v8::internal::RO_BCLR, v8::internal::RO_BEXT, v8::internal::RO_BINV, v8::internal::RO_BSET, v8::internal::RO_CZERO_EQZ, v8::internal::RO_CZERO_NEZ, v8::internal::RO_DIV, v8::internal::RO_DIVU, v8::internal::RO_MAX, v8::internal::RO_MAXU, v8::internal::RO_MIN, v8::internal::RO_MINU, v8::internal::RO_MUL, v8::internal::RO_MULH, v8::internal::RO_MULHSU, v8::internal::RO_MULHU, v8::internal::RO_OR, v8::internal::RO_ORN, v8::internal::RO_REM, v8::internal::RO_REMU, v8::internal::RO_ROL, v8::internal::RO_ROR, v8::internal::RO_SH1ADD, v8::internal::RO_SH2ADD, v8::internal::RO_SH3ADD, v8::internal::RO_SLL, v8::internal::RO_SLT, v8::internal::RO_SLTU, v8::internal::RO_SRA, v8::internal::RO_SRL, v8::internal::RO_SUB, v8::internal::RO_XNOR, v8::internal::RO_XOR, v8::internal::InstructionGetters< T >::Rs1Value(), v8::internal::InstructionGetters< T >::Rs2Value(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeRvvFVF()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvFVF (Instruction * instr) [private]
Definition at line 2946 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_FVF);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VFSGNJ_VF:
      Format(instr, "vfsgnj.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFSGNJN_VF:
      Format(instr, "vfsgnjn.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFSGNJX_VF:
      Format(instr, "vfsgnjn.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFMV_VF:
      if (instr->RvvVM()) {
        Format(instr, "vfmv.v.f 'vd, 'fs1");
      } else {
        Format(instr, "vfmerge.vfm 'vd, 'vs2, 'fs1, v0");
      }
      break;
    case RO_V_VFMADD_VF:
      Format(instr, "vfmadd.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFNMADD_VF:
      Format(instr, "vfnmadd.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFMSUB_VF:
      Format(instr, "vfmsub.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFNMSUB_VF:
      Format(instr, "vfnmsub.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFMACC_VF:
      Format(instr, "vfmacc.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFNMACC_VF:
      Format(instr, "vfnmacc.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFMSAC_VF:
      Format(instr, "vfmsac.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFNMSAC_VF:
      Format(instr, "vfnmsac.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFWADD_VF:
      Format(instr, "vfwadd.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFWSUB_VF:
      Format(instr, "vfwsub.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFWADD_W_VF:
      Format(instr, "vfwadd.wf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFWSUB_W_VF:
      Format(instr, "vfwsub.wf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFWMUL_VF:
      Format(instr, "vfwmul.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFWMACC_VF:
      Format(instr, "vfwmacc.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFWNMACC_VF:
      Format(instr, "vfwnmacc.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFWMSAC_VF:
      Format(instr, "vfwmsac.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFWNMSAC_VF:
      Format(instr, "vfwnmsac.vf 'vd, 'fs1, 'vs2'vm");
      break;
    case RO_V_VFADD_VF:
      Format(instr, "vfadd.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFMV_SF:
      if (instr->Vs2Value() == 0x0) {
        Format(instr, "vfmv.s.f 'vd, 'fs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    case RO_V_VFSLIDE1DOWN_VF:
      Format(instr, "vfslide1down.vf 'vd, 'vs2, 'fs1'vm");
      break;
    case RO_V_VFSLIDE1UP_VF:
      Format(instr, "vfslide1up.vf 'vd, 'vs2, 'fs1'vm");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_FVF, v8::internal::RO_V_VFADD_VF, v8::internal::RO_V_VFMACC_VF, v8::internal::RO_V_VFMADD_VF, v8::internal::RO_V_VFMSAC_VF, v8::internal::RO_V_VFMSUB_VF, v8::internal::RO_V_VFMV_SF, v8::internal::RO_V_VFMV_VF, v8::internal::RO_V_VFNMACC_VF, v8::internal::RO_V_VFNMADD_VF, v8::internal::RO_V_VFNMSAC_VF, v8::internal::RO_V_VFNMSUB_VF, v8::internal::RO_V_VFSGNJ_VF, v8::internal::RO_V_VFSGNJN_VF, v8::internal::RO_V_VFSGNJX_VF, v8::internal::RO_V_VFSLIDE1DOWN_VF, v8::internal::RO_V_VFSLIDE1UP_VF, v8::internal::RO_V_VFWADD_VF, v8::internal::RO_V_VFWADD_W_VF, v8::internal::RO_V_VFWMACC_VF, v8::internal::RO_V_VFWMSAC_VF, v8::internal::RO_V_VFWMUL_VF, v8::internal::RO_V_VFWNMACC_VF, v8::internal::RO_V_VFWNMSAC_VF, v8::internal::RO_V_VFWSUB_VF, v8::internal::RO_V_VFWSUB_W_VF, v8::internal::InstructionGetters< T >::RvvVM(), UNSUPPORTED_RISCV, and v8::internal::InstructionGetters< T >::Vs2Value().
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvFVV()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvFVV (Instruction * instr) [private]
Definition at line 2764 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_FVV);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VFUNARY0:
      switch (instr->Vs1Value()) {
        case VFCVT_XU_F_V:
          Format(instr, "vfcvt.xu.f.v 'vd, 'vs2'vm");
          break;
        case VFCVT_X_F_V:
          Format(instr, "vfcvt.x.f.v 'vd, 'vs2'vm");
          break;
        case VFNCVT_F_F_W:
          Format(instr, "vfncvt.f.f.w 'vd, 'vs2'vm");
          break;
        case VFNCVT_X_F_W:
          Format(instr, "vfncvt.x.f.w 'vd, 'vs2'vm");
          break;
        case VFNCVT_XU_F_W:
          Format(instr, "vfncvt.xu.f.w 'vd, 'vs2'vm");
          break;
        case VFCVT_F_X_V:
          Format(instr, "vfcvt.f.x.v 'vd, 'vs2'vm");
          break;
        case VFCVT_F_XU_V:
          Format(instr, "vfcvt.f.xu.v 'vd, 'vs2'vm");
          break;
        case VFWCVT_XU_F_V:
          Format(instr, "vfwcvt.xu.f.v 'vd, 'vs2'vm");
          break;
        case VFWCVT_X_F_V:
          Format(instr, "vfwcvt.x.f.v 'vd, 'vs2'vm");
          break;
        case VFWCVT_F_X_V:
          Format(instr, "vfwcvt.f.x.v 'vd, 'vs2'vm");
          break;
        case VFWCVT_F_XU_V:
          Format(instr, "vfwcvt.f.xu.v 'vd, 'vs2'vm");
          break;
        case VFWCVT_F_F_V:
          Format(instr, "vfwcvt.f.f.v 'vd, 'vs2'vm");
          break;
        default:
          UNSUPPORTED_RISCV();
      }
      break;
    case RO_V_VFUNARY1:
      switch (instr->Vs1Value()) {
        case VFCLASS_V:
          Format(instr, "vfclass.v 'vd, 'vs2'vm");
          break;
        case VFSQRT_V:
          Format(instr, "vfsqrt.v 'vd, 'vs2'vm");
          break;
        case VFRSQRT7_V:
          Format(instr, "vfrsqrt7.v 'vd, 'vs2'vm");
          break;
        case VFREC7_V:
          Format(instr, "vfrec7.v 'vd, 'vs2'vm");
          break;
        default:
          break;
      }
      break;
    case RO_V_VMFEQ_VV:
      Format(instr, "vmfeq.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMFNE_VV:
      Format(instr, "vmfne.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMFLT_VV:
      Format(instr, "vmflt.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMFLE_VV:
      Format(instr, "vmfle.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFMAX_VV:
      Format(instr, "vfmax.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFREDMAX_VV:
      Format(instr, "vfredmax.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFMIN_VV:
      Format(instr, "vfmin.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFSGNJ_VV:
      Format(instr, "vfsgnj.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFSGNJN_VV:
      if (instr->Vs1Value() == instr->Vs2Value()) {
        Format(instr, "vfneg.vv 'vd, 'vs1'vm");
      } else {
        Format(instr, "vfsgnjn.vv 'vd, 'vs2, 'vs1'vm");
      }
      break;
    case RO_V_VFSGNJX_VV:
      if (instr->Vs1Value() == instr->Vs2Value()) {
        Format(instr, "vabs.vv 'vd, 'vs1'vm");
      } else {
        Format(instr, "vfsgnjn.vv 'vd, 'vs2, 'vs1'vm");
      }
      break;
    case RO_V_VFADD_VV:
      Format(instr, "vfadd.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFSUB_VV:
      Format(instr, "vfsub.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFDIV_VV:
      Format(instr, "vfdiv.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFMUL_VV:
      Format(instr, "vfmul.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFMADD_VV:
      Format(instr, "vfmadd.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFNMADD_VV:
      Format(instr, "vfnmadd.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFMSUB_VV:
      Format(instr, "vfmsub.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFNMSUB_VV:
      Format(instr, "vfnmsub.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFMACC_VV:
      Format(instr, "vfmacc.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFNMACC_VV:
      Format(instr, "vfnmacc.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFMSAC_VV:
      Format(instr, "vfmsac.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFNMSAC_VV:
      Format(instr, "vfnmsac.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFMV_FS:
      if (instr->Vs1Value() == 0x0) {
        Format(instr, "vfmv.f.s 'fd, 'vs2");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    case RO_V_VFWADD_VV:
      Format(instr, "vfwadd.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWSUB_VV:
      Format(instr, "vfwsub.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWADD_W_VV:
      Format(instr, "vfwadd.wv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWSUB_W_VV:
      Format(instr, "vfwsub.wv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWREDUSUM_VS:
      Format(instr, "vfwredusum.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWREDOSUM_VS:
      Format(instr, "vfwredosum.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWMUL_VV:
      Format(instr, "vfwmul.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VFWMACC_VV:
      Format(instr, "vfwmacc.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFWNMACC_VV:
      Format(instr, "vfwnmacc.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFWMSAC_VV:
      Format(instr, "vfwmsac.vv 'vd, 'vs1, 'vs2'vm");
      break;
    case RO_V_VFWNMSAC_VV:
      Format(instr, "vfwnmsac.vv 'vd, 'vs1, 'vs2'vm");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_FVV, v8::internal::RO_V_VFADD_VV, v8::internal::RO_V_VFDIV_VV, v8::internal::RO_V_VFMACC_VV, v8::internal::RO_V_VFMADD_VV, v8::internal::RO_V_VFMAX_VV, v8::internal::RO_V_VFMIN_VV, v8::internal::RO_V_VFMSAC_VV, v8::internal::RO_V_VFMSUB_VV, v8::internal::RO_V_VFMUL_VV, v8::internal::RO_V_VFMV_FS, v8::internal::RO_V_VFNMACC_VV, v8::internal::RO_V_VFNMADD_VV, v8::internal::RO_V_VFNMSAC_VV, v8::internal::RO_V_VFNMSUB_VV, v8::internal::RO_V_VFREDMAX_VV, v8::internal::RO_V_VFSGNJ_VV, v8::internal::RO_V_VFSGNJN_VV, v8::internal::RO_V_VFSGNJX_VV, v8::internal::RO_V_VFSUB_VV, v8::internal::RO_V_VFUNARY0, v8::internal::RO_V_VFUNARY1, v8::internal::RO_V_VFWADD_VV, v8::internal::RO_V_VFWADD_W_VV, v8::internal::RO_V_VFWMACC_VV, v8::internal::RO_V_VFWMSAC_VV, v8::internal::RO_V_VFWMUL_VV, v8::internal::RO_V_VFWNMACC_VV, v8::internal::RO_V_VFWNMSAC_VV, v8::internal::RO_V_VFWREDOSUM_VS, v8::internal::RO_V_VFWREDUSUM_VS, v8::internal::RO_V_VFWSUB_VV, v8::internal::RO_V_VFWSUB_W_VV, v8::internal::RO_V_VMFEQ_VV, v8::internal::RO_V_VMFLE_VV, v8::internal::RO_V_VMFLT_VV, v8::internal::RO_V_VMFNE_VV, UNSUPPORTED_RISCV, v8::internal::VFCLASS_V, v8::internal::VFCVT_F_X_V, v8::internal::VFCVT_F_XU_V, v8::internal::VFCVT_X_F_V, v8::internal::VFCVT_XU_F_V, v8::internal::VFNCVT_F_F_W, v8::internal::VFNCVT_X_F_W, v8::internal::VFNCVT_XU_F_W, v8::internal::VFREC7_V, v8::internal::VFRSQRT7_V, v8::internal::VFSQRT_V, v8::internal::VFWCVT_F_F_V, v8::internal::VFWCVT_F_X_V, v8::internal::VFWCVT_F_XU_V, v8::internal::VFWCVT_X_F_V, v8::internal::VFWCVT_XU_F_V, v8::internal::InstructionGetters< T >::Vs1Value(), and v8::internal::InstructionGetters< T >::Vs2Value().
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvIVI()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvIVI (Instruction * instr) [private]
Definition at line 2419 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_IVI);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VADD_VI:
      Format(instr, "vadd.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VSADD_VI:
      Format(instr, "vsadd.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VSADDU_VI:
      Format(instr, "vsaddu.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VRSUB_VI:
      Format(instr, "vrsub.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VAND_VI:
      Format(instr, "vand.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VOR_VI:
      Format(instr, "vor.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VXOR_VI:
      Format(instr, "vxor.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VRGATHER_VI:
      Format(instr, "vrgather.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VMV_VI:
      if (instr->RvvVM()) {
        Format(instr, "vmv.vi 'vd, 'simm5");
      } else {
        Format(instr, "vmerge.vim 'vd, 'vs2, 'simm5, v0");
      }
      break;
    case RO_V_VMSEQ_VI:
      Format(instr, "vmseq.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VMSNE_VI:
      Format(instr, "vmsne.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VMSLEU_VI:
      Format(instr, "vmsleu.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VMSLE_VI:
      Format(instr, "vmsle.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VMSGTU_VI:
      Format(instr, "vmsgtu.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VMSGT_VI:
      Format(instr, "vmsgt.vi 'vd, 'vs2, 'simm5'vm");
      break;
    case RO_V_VSLIDEDOWN_VI:
      Format(instr, "vslidedown.vi 'vd, 'vs2, 'uimm5'vm");
      break;
    case RO_V_VSLIDEUP_VI:
      Format(instr, "vslideup.vi 'vd, 'vs2, 'uimm5'vm");
      break;
    case RO_V_VSRL_VI:
      Format(instr, "vsrl.vi 'vd, 'vs2, 'uimm5'vm");
      break;
    case RO_V_VSRA_VI:
      Format(instr, "vsra.vi 'vd, 'vs2, 'uimm5'vm");
      break;
    case RO_V_VSLL_VI:
      Format(instr, "vsll.vi 'vd, 'vs2, 'uimm5'vm");
      break;
    case RO_V_VADC_VI:
      if (!instr->RvvVM()) {
        Format(instr, "vadc.vim 'vd, 'vs2, 'uimm5");
      } else {
        UNREACHABLE();
      }
      break;
    case RO_V_VMADC_VI:
      if (!instr->RvvVM()) {
        Format(instr, "vmadc.vim 'vd, 'vs2, 'uimm5");
      } else {
        UNREACHABLE();
      }
      break;
    case RO_V_VNCLIP_WI:
      Format(instr, "vnclip.wi 'vd, 'vs2, 'uimm5");
      break;
    case RO_V_VNCLIPU_WI:
      Format(instr, "vnclipu.wi 'vd, 'vs2, 'uimm5");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_IVI, v8::internal::RO_V_VADC_VI, v8::internal::RO_V_VADD_VI, v8::internal::RO_V_VAND_VI, v8::internal::RO_V_VMADC_VI, v8::internal::RO_V_VMSEQ_VI, v8::internal::RO_V_VMSGT_VI, v8::internal::RO_V_VMSGTU_VI, v8::internal::RO_V_VMSLE_VI, v8::internal::RO_V_VMSLEU_VI, v8::internal::RO_V_VMSNE_VI, v8::internal::RO_V_VMV_VI, v8::internal::RO_V_VNCLIP_WI, v8::internal::RO_V_VNCLIPU_WI, v8::internal::RO_V_VOR_VI, v8::internal::RO_V_VRGATHER_VI, v8::internal::RO_V_VRSUB_VI, v8::internal::RO_V_VSADD_VI, v8::internal::RO_V_VSADDU_VI, v8::internal::RO_V_VSLIDEDOWN_VI, v8::internal::RO_V_VSLIDEUP_VI, v8::internal::RO_V_VSLL_VI, v8::internal::RO_V_VSRA_VI, v8::internal::RO_V_VSRL_VI, v8::internal::RO_V_VXOR_VI, v8::internal::InstructionGetters< T >::RvvVM(), v8::internal::UNREACHABLE(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvIVV()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvIVV (Instruction * instr) [private]
Definition at line 2312 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_IVV);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VADD_VV:
      Format(instr, "vadd.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VSADD_VV:
      Format(instr, "vsadd.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VSADDU_VV:
      Format(instr, "vsaddu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VSUB_VV:
      Format(instr, "vsub.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VSSUB_VV:
      Format(instr, "vssub.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VSSUBU_VV:
      Format(instr, "vssubu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMIN_VV:
      Format(instr, "vmin.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMINU_VV:
      Format(instr, "vminu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMAX_VV:
      Format(instr, "vmax.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMAXU_VV:
      Format(instr, "vmaxu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VAND_VV:
      Format(instr, "vand.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VOR_VV:
      Format(instr, "vor.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VXOR_VV:
      Format(instr, "vxor.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VRGATHER_VV:
      Format(instr, "vrgather.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMSEQ_VV:
      Format(instr, "vmseq.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMSNE_VV:
      Format(instr, "vmsne.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMSLT_VV:
      Format(instr, "vmslt.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMSLTU_VV:
      Format(instr, "vmsltu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMSLE_VV:
      Format(instr, "vmsle.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMSLEU_VV:
      Format(instr, "vmsleu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMV_VV:
      if (instr->RvvVM()) {
        Format(instr, "vmv.vv 'vd, 'vs1");
      } else {
        Format(instr, "vmerge.vvm 'vd, 'vs2, 'vs1, v0");
      }
      break;
    case RO_V_VADC_VV:
      if (!instr->RvvVM()) {
        Format(instr, "vadc.vvm 'vd, 'vs2, 'vs1");
      } else {
        UNREACHABLE();
      }
      break;
    case RO_V_VMADC_VV:
      if (!instr->RvvVM()) {
        Format(instr, "vmadc.vvm 'vd, 'vs2, 'vs1");
      } else {
        UNREACHABLE();
      }
      break;
    case RO_V_VNCLIP_WV:
      Format(instr, "vnclip.wv 'vd, 'vs2, 'vs1");
      break;
    case RO_V_VNCLIPU_WV:
      Format(instr, "vnclipu.wv 'vd, 'vs2, 'vs1");
      break;
    case RO_V_VSLL_VV:
      Format(instr, "vsll.vv 'vd, 'vs2, 'vs1");
      break;
    case RO_V_VSRL_VV:
      Format(instr, "vsrl.vv 'vd, 'vs2, 'vs1");
      break;
    case RO_V_VSRA_VV:
      Format(instr, "vsra.vv 'vd, 'vs2, 'vs1");
      break;
    case RO_V_VSMUL_VV:
      Format(instr, "vsmul.vv 'vd, 'vs2, 'vs1");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_IVV, v8::internal::RO_V_VADC_VV, v8::internal::RO_V_VADD_VV, v8::internal::RO_V_VAND_VV, v8::internal::RO_V_VMADC_VV, v8::internal::RO_V_VMAX_VV, v8::internal::RO_V_VMAXU_VV, v8::internal::RO_V_VMIN_VV, v8::internal::RO_V_VMINU_VV, v8::internal::RO_V_VMSEQ_VV, v8::internal::RO_V_VMSLE_VV, v8::internal::RO_V_VMSLEU_VV, v8::internal::RO_V_VMSLT_VV, v8::internal::RO_V_VMSLTU_VV, v8::internal::RO_V_VMSNE_VV, v8::internal::RO_V_VMV_VV, v8::internal::RO_V_VNCLIP_WV, v8::internal::RO_V_VNCLIPU_WV, v8::internal::RO_V_VOR_VV, v8::internal::RO_V_VRGATHER_VV, v8::internal::RO_V_VSADD_VV, v8::internal::RO_V_VSADDU_VV, v8::internal::RO_V_VSLL_VV, v8::internal::RO_V_VSMUL_VV, v8::internal::RO_V_VSRA_VV, v8::internal::RO_V_VSRL_VV, v8::internal::RO_V_VSSUB_VV, v8::internal::RO_V_VSSUBU_VV, v8::internal::RO_V_VSUB_VV, v8::internal::RO_V_VXOR_VV, v8::internal::InstructionGetters< T >::RvvVM(), v8::internal::UNREACHABLE(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvIVX()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvIVX (Instruction * instr) [private]
Definition at line 2511 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_IVX);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VADD_VX:
      Format(instr, "vadd.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSADD_VX:
      Format(instr, "vsadd.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSADDU_VX:
      Format(instr, "vsaddu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSUB_VX:
      Format(instr, "vsub.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSSUB_VX:
      Format(instr, "vssub.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VRSUB_VX:
      if (instr->Rs1Value() == zero_reg.code())
        Format(instr, "vneg.vv 'vd, 'vs2'vm");
      else
        Format(instr, "vrsub.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMIN_VX:
      Format(instr, "vmin.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMINU_VX:
      Format(instr, "vminu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMAX_VX:
      Format(instr, "vmax.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMAXU_VX:
      Format(instr, "vmaxu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VAND_VX:
      Format(instr, "vand.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VOR_VX:
      Format(instr, "vor.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VXOR_VX:
      Format(instr, "vxor.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VRGATHER_VX:
      Format(instr, "vrgather.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMV_VX:
      if (instr->RvvVM()) {
        Format(instr, "vmv.vx 'vd, 'rs1");
      } else {
        Format(instr, "vmerge.vxm 'vd, 'vs2, 'rs1, v0");
      }
      break;
    case RO_V_VMSEQ_VX:
      Format(instr, "vmseq.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSNE_VX:
      Format(instr, "vmsne.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSLT_VX:
      Format(instr, "vmslt.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSLTU_VX:
      Format(instr, "vmsltu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSLE_VX:
      Format(instr, "vmsle.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSLEU_VX:
      Format(instr, "vmsleu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSGT_VX:
      Format(instr, "vmsgt.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMSGTU_VX:
      Format(instr, "vmsgtu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSLIDEDOWN_VX:
      Format(instr, "vslidedown.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSLIDEUP_VX:
      Format(instr, "vslideup.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VADC_VX:
      if (!instr->RvvVM()) {
        Format(instr, "vadc.vxm 'vd, 'vs2, 'rs1");
      } else {
        UNREACHABLE();
      }
      break;
    case RO_V_VMADC_VX:
      if (!instr->RvvVM()) {
        Format(instr, "vmadc.vxm 'vd, 'vs2, 'rs1");
      } else {
        UNREACHABLE();
      }
      break;
    case RO_V_VSLL_VX:
      Format(instr, "vsll.vx 'vd, 'vs2, 'rs1");
      break;
    case RO_V_VSRL_VX:
      Format(instr, "vsrl.vx 'vd, 'vs2, 'rs1");
      break;
    case RO_V_VSRA_VX:
      Format(instr, "vsra.vx 'vd, 'vs2, 'rs1");
      break;
    case RO_V_VNCLIP_WX:
      Format(instr, "vnclip.wx 'vd, 'vs2, 'rs1");
      break;
    case RO_V_VNCLIPU_WX:
      Format(instr, "vnclipu.wx 'vd, 'vs2, 'rs1");
      break;
    case RO_V_VSMUL_VX:
      Format(instr, "vsmul.vx 'vd, 'vs2, 'vs1");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_IVX, v8::internal::RO_V_VADC_VX, v8::internal::RO_V_VADD_VX, v8::internal::RO_V_VAND_VX, v8::internal::RO_V_VMADC_VX, v8::internal::RO_V_VMAX_VX, v8::internal::RO_V_VMAXU_VX, v8::internal::RO_V_VMIN_VX, v8::internal::RO_V_VMINU_VX, v8::internal::RO_V_VMSEQ_VX, v8::internal::RO_V_VMSGT_VX, v8::internal::RO_V_VMSGTU_VX, v8::internal::RO_V_VMSLE_VX, v8::internal::RO_V_VMSLEU_VX, v8::internal::RO_V_VMSLT_VX, v8::internal::RO_V_VMSLTU_VX, v8::internal::RO_V_VMSNE_VX, v8::internal::RO_V_VMV_VX, v8::internal::RO_V_VNCLIP_WX, v8::internal::RO_V_VNCLIPU_WX, v8::internal::RO_V_VOR_VX, v8::internal::RO_V_VRGATHER_VX, v8::internal::RO_V_VRSUB_VX, v8::internal::RO_V_VSADD_VX, v8::internal::RO_V_VSADDU_VX, v8::internal::RO_V_VSLIDEDOWN_VX, v8::internal::RO_V_VSLIDEUP_VX, v8::internal::RO_V_VSLL_VX, v8::internal::RO_V_VSMUL_VX, v8::internal::RO_V_VSRA_VX, v8::internal::RO_V_VSRL_VX, v8::internal::RO_V_VSSUB_VX, v8::internal::RO_V_VSUB_VX, v8::internal::RO_V_VXOR_VX, v8::internal::InstructionGetters< T >::Rs1Value(), v8::internal::InstructionGetters< T >::RvvVM(), v8::internal::UNREACHABLE(), and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvMVV()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvMVV (Instruction * instr) [private]
Definition at line 2633 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_MVV);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VMUNARY0: {
      if (instr->Vs1Value() == VID_V) {
        Format(instr, "vid.v 'rd, 'vs2'vm");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    }
    case RO_V_VWXUNARY0:
      if (instr->Vs1Value() == 0x0) {
        Format(instr, "vmv.x.s 'rd, 'vs2");
      } else if (instr->Vs1Value() == 0b10001) {
        Format(instr, "vfirst.m 'rd, 'vs2");
      } else if (instr->Vs1Value() == 0b10000) {
        Format(instr, "vcpop.m 'rd, 'vs2");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    case RO_V_VREDMAXU:
      Format(instr, "vredmaxu.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VREDMAX:
      Format(instr, "vredmax.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VREDMIN:
      Format(instr, "vredmin.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VREDMINU:
      Format(instr, "vredminu.vs 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VXUNARY0:
      if (instr->Vs1Value() == 0b00010) {
        Format(instr, "vzext.vf8 'vd, 'vs2'vm");
      } else if (instr->Vs1Value() == 0b00011) {
        Format(instr, "vsext.vf8 'vd, 'vs2'vm");
      } else if (instr->Vs1Value() == 0b00100) {
        Format(instr, "vzext.vf4 'vd, 'vs2'vm");
      } else if (instr->Vs1Value() == 0b00101) {
        Format(instr, "vsext.vf4 'vd, 'vs2'vm");
      } else if (instr->Vs1Value() == 0b00110) {
        Format(instr, "vzext.vf2 'vd, 'vs2'vm");
      } else if (instr->Vs1Value() == 0b00111) {
        Format(instr, "vsext.vf2 'vd, 'vs2'vm");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    case RO_V_VWMUL_VV:
      Format(instr, "vwmul.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VWMULU_VV:
      Format(instr, "vwmulu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMUL_VV:
      Format(instr, "vmul.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VMULHU_VV:
      Format(instr, "vmulhu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VDIV_VV:
      Format(instr, "vdiv.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VDIVU_VV:
      Format(instr, "vdivu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VWADDU_VV:
      Format(instr, "vwaddu.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VWADD_VV:
      Format(instr, "vwadd.vv 'vd, 'vs2, 'vs1'vm");
      break;
    case RO_V_VCOMPRESS_VV:
      Format(instr, "vcompress.vm 'vd, 'vs2, 'vs1'vm");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_MVV, v8::internal::RO_V_VCOMPRESS_VV, v8::internal::RO_V_VDIV_VV, v8::internal::RO_V_VDIVU_VV, v8::internal::RO_V_VMUL_VV, v8::internal::RO_V_VMULHU_VV, v8::internal::RO_V_VMUNARY0, v8::internal::RO_V_VREDMAX, v8::internal::RO_V_VREDMAXU, v8::internal::RO_V_VREDMIN, v8::internal::RO_V_VREDMINU, v8::internal::RO_V_VWADD_VV, v8::internal::RO_V_VWADDU_VV, v8::internal::RO_V_VWMUL_VV, v8::internal::RO_V_VWMULU_VV, v8::internal::RO_V_VWXUNARY0, v8::internal::RO_V_VXUNARY0, UNSUPPORTED_RISCV, v8::internal::VID_V, and v8::internal::InstructionGetters< T >::Vs1Value().
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvMVX()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvMVX (Instruction * instr) [private]
Definition at line 2716 of file disasm-riscv.cc.
                                             {
  DCHECK_EQ(instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask), OP_MVX);
  switch (instr->InstructionBits() & kVTypeMask) {
    case RO_V_VRXUNARY0:
      if (instr->Vs2Value() == 0x0) {
        Format(instr, "vmv.s.x 'vd, 'rs1");
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
    case RO_V_VWMUL_VX:
      Format(instr, "vwmul.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VWMULU_VX:
      Format(instr, "vwmulu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMUL_VX:
      Format(instr, "vmul.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VMULHU_VX:
      Format(instr, "vmulhu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VDIV_VX:
      Format(instr, "vdiv.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VDIVU_VX:
      Format(instr, "vdivu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VWADDUW_VX:
      Format(instr, "vwaddu.wx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VWADDU_VX:
      Format(instr, "vwaddu.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VWADD_VX:
      Format(instr, "vwadd.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSLIDE1DOWN_VX:
      Format(instr, "vslide1down.vx 'vd, 'vs2, 'rs1'vm");
      break;
    case RO_V_VSLIDE1UP_VX:
      Format(instr, "vslide1up.vx 'vd, 'vs2, 'rs1'vm");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References DCHECK_EQ, v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::kVTypeMask, v8::internal::OP_MVX, v8::internal::RO_V_VDIV_VX, v8::internal::RO_V_VDIVU_VX, v8::internal::RO_V_VMUL_VX, v8::internal::RO_V_VMULHU_VX, v8::internal::RO_V_VRXUNARY0, v8::internal::RO_V_VSLIDE1DOWN_VX, v8::internal::RO_V_VSLIDE1UP_VX, v8::internal::RO_V_VWADD_VX, v8::internal::RO_V_VWADDU_VX, v8::internal::RO_V_VWADDUW_VX, v8::internal::RO_V_VWMUL_VX, v8::internal::RO_V_VWMULU_VX, UNSUPPORTED_RISCV, and v8::internal::InstructionGetters< T >::Vs2Value().
Referenced by v8::internal::Decoder< V >::DecodeVType().
DecodeRvvVL()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvVL (Instruction * instr) [private]
Definition at line 3104 of file disasm-riscv.cc.
                                            {
  char str[50];
  uint32_t instr_temp =
      instr->InstructionBits() & (kRvvMopMask | kRvvNfMask | kBaseOpcodeMask);
  // switch (instr->InstructionBits() &
  // (kRvvMopMask | kRvvNfMask | kBaseOpcodeMask)) {
  if (RO_V_VL == instr_temp) {
    if (!(instr->InstructionBits() & (kRvvRs2Mask))) {
      snprintf(str, sizeof(str), "vle%d.v 'vd, ('rs1)'vm",
               instr->vl_vs_width());
      Format(instr, str);
    } else {
      snprintf(str, sizeof(str), "vle%dff.v 'vd, ('rs1)'vm",
               instr->vl_vs_width());
      Format(instr, str);
    }
  } else if (RO_V_VLS == instr_temp) {
    snprintf(str, sizeof(str), "vlse%d.v 'vd, ('rs1), 'rs2'vm",
             instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VLX == instr_temp) {
    snprintf(str, sizeof(str), "vlxei%d.v 'vd, ('rs1), 'vs2'vm",
             instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VLSEG2 == instr_temp || RO_V_VLSEG3 == instr_temp ||
             RO_V_VLSEG4 == instr_temp || RO_V_VLSEG5 == instr_temp ||
             RO_V_VLSEG6 == instr_temp || RO_V_VLSEG7 == instr_temp ||
             RO_V_VLSEG8 == instr_temp) {
    if (!(instr->InstructionBits() & (kRvvRs2Mask))) {
      snprintf(str, sizeof(str), "vlseg%de%d.v 'vd, ('rs1)'vm",
               switch_nf(instr), instr->vl_vs_width());
    } else {
      snprintf(str, sizeof(str), "vlseg%de%dff.v 'vd, ('rs1)'vm",
               switch_nf(instr), instr->vl_vs_width());
    }
    Format(instr, str);
  } else if (RO_V_VLSSEG2 == instr_temp || RO_V_VLSSEG3 == instr_temp ||
             RO_V_VLSSEG4 == instr_temp || RO_V_VLSSEG5 == instr_temp ||
             RO_V_VLSSEG6 == instr_temp || RO_V_VLSSEG7 == instr_temp ||
             RO_V_VLSSEG8 == instr_temp) {
    snprintf(str, sizeof(str), "vlsseg%de%d.v 'vd, ('rs1), 'rs2'vm",
             switch_nf(instr), instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VLXSEG2 == instr_temp || RO_V_VLXSEG3 == instr_temp ||
             RO_V_VLXSEG4 == instr_temp || RO_V_VLXSEG5 == instr_temp ||
             RO_V_VLXSEG6 == instr_temp || RO_V_VLXSEG7 == instr_temp ||
             RO_V_VLXSEG8 == instr_temp) {
    snprintf(str, sizeof(str), "vlxseg%dei%d.v 'vd, ('rs1), 'vs2'vm",
             switch_nf(instr), instr->vl_vs_width());
    Format(instr, str);
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kRvvMopMask, v8::internal::kRvvNfMask, v8::internal::kRvvRs2Mask, v8::internal::RO_V_VL, v8::internal::RO_V_VLS, v8::internal::RO_V_VLSEG2, v8::internal::RO_V_VLSEG3, v8::internal::RO_V_VLSEG4, v8::internal::RO_V_VLSEG5, v8::internal::RO_V_VLSEG6, v8::internal::RO_V_VLSEG7, v8::internal::RO_V_VLSEG8, v8::internal::RO_V_VLSSEG2, v8::internal::RO_V_VLSSEG3, v8::internal::RO_V_VLSSEG4, v8::internal::RO_V_VLSSEG5, v8::internal::RO_V_VLSSEG6, v8::internal::RO_V_VLSSEG7, v8::internal::RO_V_VLSSEG8, v8::internal::RO_V_VLX, v8::internal::RO_V_VLXSEG2, v8::internal::RO_V_VLXSEG3, v8::internal::RO_V_VLXSEG4, v8::internal::RO_V_VLXSEG5, v8::internal::RO_V_VLXSEG6, v8::internal::RO_V_VLXSEG7, v8::internal::RO_V_VLXSEG8, v8::internal::Decoder< V >::switch_nf(), and v8::internal::InstructionGetters< T >::vl_vs_width().
Referenced by v8::internal::Decoder< V >::DecodeIType().
DecodeRvvVS()
template<typename V >
void v8::internal::Decoder< V >::DecodeRvvVS (Instruction * instr) [private]
Definition at line 3195 of file disasm-riscv.cc.
                                            {
  char str[50];
  uint32_t instr_temp =
      instr->InstructionBits() & (kRvvMopMask | kRvvNfMask | kBaseOpcodeMask);
  if (RO_V_VS == instr_temp) {
    snprintf(str, sizeof(str), "vse%d.v 'vd, ('rs1)'vm",
             instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VSS == instr_temp) {
    snprintf(str, sizeof(str), "vsse%d.v 'vd, ('rs1), 'rs2'vm",
             instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VSX == instr_temp) {
    snprintf(str, sizeof(str), "vsxei%d.v 'vd, ('rs1), 'vs2'vm",
             instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VSU == instr_temp) {
    snprintf(str, sizeof(str), "vsuxei%d.v 'vd, ('rs1), 'vs2'vm",
             instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VSSEG2 == instr_temp || RO_V_VSSEG3 == instr_temp ||
             RO_V_VSSEG4 == instr_temp || RO_V_VSSEG5 == instr_temp ||
             RO_V_VSSEG6 == instr_temp || RO_V_VSSEG7 == instr_temp ||
             RO_V_VSSEG8 == instr_temp) {
    snprintf(str, sizeof(str), "vsseg%de%d.v 'vd, ('rs1)'vm",
             switch_nf(instr), instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VSSSEG2 == instr_temp || RO_V_VSSSEG3 == instr_temp ||
             RO_V_VSSSEG4 == instr_temp || RO_V_VSSSEG5 == instr_temp ||
             RO_V_VSSSEG6 == instr_temp || RO_V_VSSSEG7 == instr_temp ||
             RO_V_VSSSEG8 == instr_temp) {
    snprintf(str, sizeof(str), "vssseg%de%d.v 'vd, ('rs1), 'rs2'vm",
             switch_nf(instr), instr->vl_vs_width());
    Format(instr, str);
  } else if (RO_V_VSXSEG2 == instr_temp || RO_V_VSXSEG3 == instr_temp ||
             RO_V_VSXSEG4 == instr_temp || RO_V_VSXSEG5 == instr_temp ||
             RO_V_VSXSEG6 == instr_temp || RO_V_VSXSEG7 == instr_temp ||
             RO_V_VSXSEG8 == instr_temp) {
    snprintf(str, sizeof(str), "vsxseg%dei%d.v 'vd, ('rs1), 'vs2'vm",
             switch_nf(instr), instr->vl_vs_width());
    Format(instr, str);
  }
}
References v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kRvvMopMask, v8::internal::kRvvNfMask, v8::internal::RO_V_VS, v8::internal::RO_V_VSS, v8::internal::RO_V_VSSEG2, v8::internal::RO_V_VSSEG3, v8::internal::RO_V_VSSEG4, v8::internal::RO_V_VSSEG5, v8::internal::RO_V_VSSEG6, v8::internal::RO_V_VSSEG7, v8::internal::RO_V_VSSEG8, v8::internal::RO_V_VSSSEG2, v8::internal::RO_V_VSSSEG3, v8::internal::RO_V_VSSSEG4, v8::internal::RO_V_VSSSEG5, v8::internal::RO_V_VSSSEG6, v8::internal::RO_V_VSSSEG7, v8::internal::RO_V_VSSSEG8, v8::internal::RO_V_VSU, v8::internal::RO_V_VSX, v8::internal::RO_V_VSXSEG2, v8::internal::RO_V_VSXSEG3, v8::internal::RO_V_VSXSEG4, v8::internal::RO_V_VSXSEG5, v8::internal::RO_V_VSXSEG6, v8::internal::RO_V_VSXSEG7, v8::internal::RO_V_VSXSEG8, v8::internal::Decoder< V >::switch_nf(), and v8::internal::InstructionGetters< T >::vl_vs_width().
Referenced by v8::internal::Decoder< V >::DecodeSType().
DecodeSType()
template<typename V >
void v8::internal::Decoder< V >::DecodeSType (Instruction * instr) [private]
Definition at line 1998 of file disasm-riscv.cc.
                                            {
  switch (instr->InstructionBits() & kSTypeMask) {
    case RO_SB:
      Format(instr, "sb 'rs2, 'offS('rs1)");
      break;
    case RO_SH:
      Format(instr, "sh 'rs2, 'offS('rs1)");
      break;
    case RO_SW:
      Format(instr, "sw 'rs2, 'offS('rs1)");
      break;
#ifdef V8_TARGET_ARCH_64_BIT
    case RO_SD:
      Format(instr, "sd 'rs2, 'offS('rs1)");
      break;
#endif /*V8_TARGET_ARCH_64_BIT*/
    // TODO(riscv): use F Extension macro block
    case RO_FSW:
      Format(instr, "fsw 'fs2, 'offS('rs1)");
      break;
    case RO_FSH:
      Format(instr, "fsh 'fs2, 'offS('rs1)");
      break;
    // TODO(riscv): use D Extension macro block
    case RO_FSD:
      Format(instr, "fsd 'fs2, 'offS('rs1)");
      break;
    default:
#ifdef CAN_USE_RVV_INSTRUCTIONS
      if (instr->vl_vs_width() != -1) {
        DecodeRvvVS(instr);
      } else {
        UNSUPPORTED_RISCV();
      }
      break;
#else
      UNSUPPORTED_RISCV();
#endif
  }
}
References v8::internal::Decoder< V >::DecodeRvvVS(), v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kSTypeMask, v8::internal::RO_FSD, v8::internal::RO_FSH, v8::internal::RO_FSW, v8::internal::RO_SB, v8::internal::RO_SH, v8::internal::RO_SW, UNSUPPORTED_RISCV, and v8::internal::InstructionGetters< T >::vl_vs_width().
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeUType()
template<typename V >
void v8::internal::Decoder< V >::DecodeUType (Instruction * instr) [private]
Definition at line 2063 of file disasm-riscv.cc.
                                            {
  // U Type doesn't have additional mask
  switch (instr->BaseOpcodeFieldRaw()) {
    case LUI:
      Format(instr, "lui 'rd, 'imm20U");
      break;
    case AUIPC:
      Format(instr, "auipc 'rd, 'imm20U");
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::AUIPC, v8::internal::InstructionBase::BaseOpcodeFieldRaw(), v8::internal::Decoder< V >::Format(), v8::internal::LUI, and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
DecodeVType()
template<typename V >
void v8::internal::Decoder< V >::DecodeVType (Instruction * instr) [private]
Definition at line 3037 of file disasm-riscv.cc.
                                            {
  switch (instr->InstructionBits() & (kBaseOpcodeMask | kFunct3Mask)) {
    case OP_IVV:
      DecodeRvvIVV(instr);
      return;
    case OP_FVV:
      DecodeRvvFVV(instr);
      return;
    case OP_MVV:
      DecodeRvvMVV(instr);
      return;
    case OP_IVI:
      DecodeRvvIVI(instr);
      return;
    case OP_IVX:
      DecodeRvvIVX(instr);
      return;
    case OP_FVF:
      DecodeRvvFVF(instr);
      return;
    case OP_MVX:
      DecodeRvvMVX(instr);
      return;
  }
  switch (instr->InstructionBits() &
          (kBaseOpcodeMask | kFunct3Mask | 0x80000000)) {
    case RO_V_VSETVLI:
      Format(instr, "vsetvli 'rd, 'rs1, 'sew, 'lmul");
      break;
    case RO_V_VSETVL:
      if (!(instr->InstructionBits() & 0x40000000)) {
        Format(instr, "vsetvl 'rd, 'rs1, 'rs2");
      } else {
        Format(instr, "vsetivli 'rd, 'uimm, 'sew, 'lmul");
      }
      break;
    default:
      UNSUPPORTED_RISCV();
  }
}
References v8::internal::Decoder< V >::DecodeRvvFVF(), v8::internal::Decoder< V >::DecodeRvvFVV(), v8::internal::Decoder< V >::DecodeRvvIVI(), v8::internal::Decoder< V >::DecodeRvvIVV(), v8::internal::Decoder< V >::DecodeRvvIVX(), v8::internal::Decoder< V >::DecodeRvvMVV(), v8::internal::Decoder< V >::DecodeRvvMVX(), v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kFunct3Mask, v8::internal::OP_FVF, v8::internal::OP_FVV, v8::internal::OP_IVI, v8::internal::OP_IVV, v8::internal::OP_IVX, v8::internal::OP_MVV, v8::internal::OP_MVX, v8::internal::RO_V_VSETVL, v8::internal::RO_V_VSETVLI, and UNSUPPORTED_RISCV.
Referenced by v8::internal::Decoder< V >::InstructionDecode().
Format()
template<typename V >
void v8::internal::Decoder< V >::Format (Instruction * instr, const char * format) [private]
Definition at line 849 of file disasm-riscv.cc.
                                                           {
  if (instr->IsShortInstruction() && !v8_flags.use_aliases &&
      (out_buffer_pos_ < (out_buffer_.length() - 2))) {
    out_buffer_[out_buffer_pos_++] = 'c';
    out_buffer_[out_buffer_pos_++] = '.';
  }
  char cur = *format++;
  while ((cur != 0) && (out_buffer_pos_ < (out_buffer_.length() - 1))) {
    if (cur == '\'') { // Single quote is used as the formatting escape.
      format += FormatOption(instr, format);
    } else {
      out_buffer_[out_buffer_pos_++] = cur;
    }
    cur = *format++;
  }
  out_buffer_[out_buffer_pos_] = '\0';
}
References v8::internal::format, v8::internal::Decoder< V >::FormatOption(), v8::internal::InstructionBase::IsShortInstruction(), v8::base::Vector< T >::length(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::internal::v8_flags.
Referenced by v8::internal::Decoder< V >::DecodeBType(), v8::internal::Decoder< V >::DecodeCAType(), v8::internal::Decoder< V >::DecodeCBType(), v8::internal::Decoder< V >::DecodeCIType(), v8::internal::Decoder< V >::DecodeCIWType(), v8::internal::Decoder< V >::DecodeCJType(), v8::internal::Decoder< V >::DecodeCLType(), v8::internal::Decoder< V >::DecodeCRType(), v8::internal::Decoder< V >::DecodeCSSType(), v8::internal::Decoder< V >::DecodeCSType(), v8::internal::Decoder< V >::DecodeIType(), v8::internal::Decoder< V >::DecodeJType(), v8::internal::Decoder< V >::DecodeR4Type(), v8::internal::Decoder< V >::DecodeRAType(), v8::internal::Decoder< V >::DecodeRFPType(), v8::internal::Decoder< V >::DecodeRType(), v8::internal::Decoder< V >::DecodeRvvFVF(), v8::internal::Decoder< V >::DecodeRvvFVV(), v8::internal::Decoder< V >::DecodeRvvIVI(), v8::internal::Decoder< V >::DecodeRvvIVV(), v8::internal::Decoder< V >::DecodeRvvIVX(), v8::internal::Decoder< V >::DecodeRvvMVV(), v8::internal::Decoder< V >::DecodeRvvMVX(), v8::internal::Decoder< V >::DecodeRvvVL(), v8::internal::Decoder< V >::DecodeRvvVS(), v8::internal::Decoder< V >::DecodeSType(), v8::internal::Decoder< V >::DecodeUType(), v8::internal::Decoder< V >::DecodeVType(), v8::internal::Decoder< V >::InstructionDecode(), and v8::internal::Decoder< V >::Unknown().
FormatFPURegisterOrRoundMode()
template<typename V >
int v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode (Instruction * instr, const char * option) [private]
Definition at line 531 of file disasm-riscv.cc.
                                                              {
  DCHECK_EQ(format[0], 'f');
  if (format[1] == 's') { // 'fs[1-3]: Rs register.
    if (format[2] == '1') {
      int reg = instr->Rs1Value();
      PrintFPURegister(reg);
      return 3;
    } else if (format[2] == '2') {
      int reg = instr->Rs2Value();
      PrintFPURegister(reg);
      return 3;
    } else if (format[2] == '3') {
      int reg = instr->Rs3Value();
      PrintFPURegister(reg);
      return 3;
    }
    UNREACHABLE();
  } else if (format[1] == 'd') { // 'fd: fd register.
    int reg = instr->RdValue();
    PrintFPURegister(reg);
    return 2;
  } else if (format[1] == 'r') { // 'frm
    DCHECK(STRING_STARTS_WITH(format, "frm"));
    PrintRoundingMode(instr);
    return 3;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::format, v8::internal::Decoder< V >::PrintFPURegister(), v8::internal::Decoder< V >::PrintRoundingMode(), v8::internal::Instruction::RdValue(), v8::internal::InstructionGetters< T >::Rs1Value(), v8::internal::InstructionGetters< T >::Rs2Value(), v8::internal::InstructionGetters< T >::Rs3Value(), STRING_STARTS_WITH, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::FormatOption().
FormatOption()
template<typename V >
int v8::internal::Decoder< V >::FormatOption (Instruction * instr, const char * option) [private]
Definition at line 702 of file disasm-riscv.cc.
                                                                {
  switch (format[0]) {
    case 'C': { // `C extension
      if (format[1] == 'r' || format[1] == 'f') {
        return FormatRvcRegister(instr, format);
      } else if (format[1] == 'i') {
        return FormatRvcImm(instr, format);
      } else if (format[1] == 's') {
        DCHECK(STRING_STARTS_WITH(format, "Cshamt"));
        PrintRvcShamt(instr);
        return 6;
      }
      UNREACHABLE();
    }
    case 'c': { // `csr: CSR registers
      if (format[1] == 's') {
        if (format[2] == 'r') {
          PrintCSRReg(instr);
          return 3;
        }
      }
      UNREACHABLE();
    }
    case 'i': { // 'imm12, 'imm12x, 'imm20U, or 'imm20J: Immediates.
      if (format[3] == '1') {
        if (format[4] == '2') {
          DCHECK(STRING_STARTS_WITH(format, "imm12"));
          if (format[5] == 'x') {
            PrintImm12X(instr);
            return 6;
          }
          PrintImm12(instr);
          return 5;
        }
      } else if (format[3] == '2' && format[4] == '0') {
        DCHECK(STRING_STARTS_WITH(format, "imm20"));
        switch (format[5]) {
          case 'U':
            DCHECK(STRING_STARTS_WITH(format, "imm20U"));
            PrintImm20U(instr);
            break;
          case 'J':
            DCHECK(STRING_STARTS_WITH(format, "imm20J"));
            PrintImm20J(instr);
            break;
        }
        return 6;
      }
      UNREACHABLE();
    }
    case 'o': { // 'offB or 'offS: Offsets.
      if (format[3] == 'B') {
        DCHECK(STRING_STARTS_WITH(format, "offB"));
        PrintBranchOffset(instr);
        return 4;
      } else if (format[3] == 'S') {
        DCHECK(STRING_STARTS_WITH(format, "offS"));
        PrintStoreOffset(instr);
        return 4;
      }
      UNREACHABLE();
    }
    case 'r': { // 'r: registers.
      return FormatRegister(instr, format);
    }
    case 'f': { // 'f: FPUregisters or `frm
      return FormatFPURegisterOrRoundMode(instr, format);
    }
    case 'a': { // 'a: Atomic acquire and release.
      PrintAcquireRelease(instr);
      return 1;
    }
    case 'p': { // `pre
      DCHECK(STRING_STARTS_WITH(format, "pre"));
      PrintMemoryOrder(instr, true);
      return 3;
    }
    case 's': { // 's32 or 's64: Shift amount.
      if (format[1] == '3') {
        DCHECK(STRING_STARTS_WITH(format, "s32"));
        PrintShamt32(instr);
        return 3;
      } else if (format[1] == '6') {
        DCHECK(STRING_STARTS_WITH(format, "s64"));
        PrintShamt(instr);
        return 3;
      } else if (format[1] == 'u') {
        DCHECK(STRING_STARTS_WITH(format, "suc"));
        PrintMemoryOrder(instr, false);
        return 3;
      } else if (format[1] == 'e') {
        DCHECK(STRING_STARTS_WITH(format, "sew"));
        PrintRvvSEW(instr);
        return 3;
      } else if (format[1] == 'i') {
        DCHECK(STRING_STARTS_WITH(format, "simm5"));
        PrintRvvSimm5(instr);
        return 5;
      }
      UNREACHABLE();
    }
    case 'v': {
      if (format[1] == 'd') {
        DCHECK(STRING_STARTS_WITH(format, "vd"));
        PrintVd(instr);
        return 2;
      } else if (format[2] == '1') {
        DCHECK(STRING_STARTS_WITH(format, "vs1"));
        PrintVs1(instr);
        return 3;
      } else if (format[2] == '2') {
        DCHECK(STRING_STARTS_WITH(format, "vs2"));
        PrintVs2(instr);
        return 3;
      } else {
        DCHECK(STRING_STARTS_WITH(format, "vm"));
        PrintRvvVm(instr);
        return 2;
      }
    }
    case 'l': {
      DCHECK(STRING_STARTS_WITH(format, "lmul"));
      PrintRvvLMUL(instr);
      return 4;
    }
    case 'u': {
      if (STRING_STARTS_WITH(format, "uimm5")) {
        PrintRvvUimm5(instr);
        return 5;
      } else {
        DCHECK(STRING_STARTS_WITH(format, "uimm"));
        PrintUimm(instr);
        return 4;
      }
    }
    case 't': { // 'target: target of branch instructions'
      DCHECK(STRING_STARTS_WITH(format, "target"));
      PrintTarget(instr);
      return 6;
    }
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::format, v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode(), v8::internal::Decoder< V >::FormatRegister(), v8::internal::Decoder< V >::FormatRvcImm(), v8::internal::Decoder< V >::FormatRvcRegister(), v8::internal::Decoder< V >::PrintAcquireRelease(), v8::internal::Decoder< V >::PrintBranchOffset(), v8::internal::Decoder< V >::PrintCSRReg(), v8::internal::Decoder< V >::PrintImm12(), v8::internal::Decoder< V >::PrintImm12X(), v8::internal::Decoder< V >::PrintImm20J(), v8::internal::Decoder< V >::PrintImm20U(), v8::internal::Decoder< V >::PrintMemoryOrder(), v8::internal::Decoder< V >::PrintRvcShamt(), v8::internal::Decoder< V >::PrintRvvLMUL(), v8::internal::Decoder< V >::PrintRvvSEW(), v8::internal::Decoder< V >::PrintRvvSimm5(), v8::internal::Decoder< V >::PrintRvvUimm5(), v8::internal::Decoder< V >::PrintRvvVm(), v8::internal::Decoder< V >::PrintShamt(), v8::internal::Decoder< V >::PrintShamt32(), v8::internal::Decoder< V >::PrintStoreOffset(), v8::internal::Decoder< V >::PrintTarget(), v8::internal::Decoder< V >::PrintUimm(), v8::internal::Decoder< V >::PrintVd(), v8::internal::Decoder< V >::PrintVs1(), v8::internal::Decoder< V >::PrintVs2(), STRING_STARTS_WITH, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::Format().
FormatRegister()
template<typename V >
int v8::internal::Decoder< V >::FormatRegister (Instruction * instr, const char * option) [private]
Definition at line 508 of file disasm-riscv.cc.
                                                                  {
  DCHECK_EQ(format[0], 'r');
  if (format[1] == 's') { // 'rs[12]: Rs register.
    if (format[2] == '1') {
      int reg = instr->Rs1Value();
      PrintRegister(reg);
      return 3;
    } else if (format[2] == '2') {
      int reg = instr->Rs2Value();
      PrintRegister(reg);
      return 3;
    }
    UNREACHABLE();
  } else if (format[1] == 'd') { // 'rd: rd register.
    int reg = instr->RdValue();
    PrintRegister(reg);
    return 2;
  }
  UNREACHABLE();
}
References DCHECK_EQ, v8::internal::format, v8::internal::Decoder< V >::PrintRegister(), v8::internal::Instruction::RdValue(), v8::internal::InstructionGetters< T >::Rs1Value(), v8::internal::InstructionGetters< T >::Rs2Value(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::FormatOption().
FormatRvcImm()
template<typename V >
int v8::internal::Decoder< V >::FormatRvcImm (Instruction * instr, const char * option) [private]
Definition at line 617 of file disasm-riscv.cc.
                                                                {
  // TODO(riscv): add other rvc imm format
  DCHECK(STRING_STARTS_WITH(format, "Cimm"));
  if (format[4] == '6') {
    if (format[5] == 'U') {
      DCHECK(STRING_STARTS_WITH(format, "Cimm6U"));
      PrintRvcImm6U(instr);
      return 6;
    } else if (format[5] == 'A') {
      if (format[9] == '1' && format[10] == '6') {
        DCHECK(STRING_STARTS_WITH(format, "Cimm6Addi16sp"));
        PrintRvcImm6Addi16sp(instr);
        return 13;
      }
      UNREACHABLE();
    } else if (format[5] == 'L') {
      if (format[6] == 'd') {
        if (format[7] == 's') {
          DCHECK(STRING_STARTS_WITH(format, "Cimm6Ldsp"));
          PrintRvcImm6Ldsp(instr);
          return 9;
        }
      } else if (format[6] == 'w') {
        if (format[7] == 's') {
          DCHECK(STRING_STARTS_WITH(format, "Cimm6Lwsp"));
          PrintRvcImm6Lwsp(instr);
          return 9;
        }
      }
      UNREACHABLE();
    } else if (format[5] == 'S') {
      if (format[6] == 'w') {
        DCHECK(STRING_STARTS_WITH(format, "Cimm6Swsp"));
        PrintRvcImm6Swsp(instr);
        return 9;
      } else if (format[6] == 'd') {
        DCHECK(STRING_STARTS_WITH(format, "Cimm6Sdsp"));
        PrintRvcImm6Sdsp(instr);
        return 9;
      }
      UNREACHABLE();
    }
    PrintRvcImm6(instr);
    return 5;
  } else if (format[4] == '5') {
    DCHECK(STRING_STARTS_WITH(format, "Cimm5"));
    if (format[5] == 'W') {
      DCHECK(STRING_STARTS_WITH(format, "Cimm5W"));
      PrintRvcImm5W(instr);
      return 6;
    } else if (format[5] == 'D') {
      DCHECK(STRING_STARTS_WITH(format, "Cimm5D"));
      PrintRvcImm5D(instr);
      return 6;
    }
    UNREACHABLE();
  } else if (format[4] == '8') {
    DCHECK(STRING_STARTS_WITH(format, "Cimm8"));
    if (format[5] == 'A') {
      DCHECK(STRING_STARTS_WITH(format, "Cimm8Addi4spn"));
      PrintRvcImm8Addi4spn(instr);
      return 13;
    } else if (format[5] == 'B') {
      DCHECK(STRING_STARTS_WITH(format, "Cimm8B"));
      PrintRvcImm8B(instr);
      return 6;
    }
    UNREACHABLE();
  } else if (format[4] == '1') {
    DCHECK(STRING_STARTS_WITH(format, "Cimm1"));
    if (format[5] == '1') {
      DCHECK(STRING_STARTS_WITH(format, "Cimm11CJ"));
      PrintRvcImm11CJ(instr);
      return 8;
    }
    UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::format, v8::internal::Decoder< V >::PrintRvcImm11CJ(), v8::internal::Decoder< V >::PrintRvcImm5D(), v8::internal::Decoder< V >::PrintRvcImm5W(), v8::internal::Decoder< V >::PrintRvcImm6(), v8::internal::Decoder< V >::PrintRvcImm6Addi16sp(), v8::internal::Decoder< V >::PrintRvcImm6Ldsp(), v8::internal::Decoder< V >::PrintRvcImm6Lwsp(), v8::internal::Decoder< V >::PrintRvcImm6Sdsp(), v8::internal::Decoder< V >::PrintRvcImm6Swsp(), v8::internal::Decoder< V >::PrintRvcImm6U(), v8::internal::Decoder< V >::PrintRvcImm8Addi4spn(), v8::internal::Decoder< V >::PrintRvcImm8B(), STRING_STARTS_WITH, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::FormatOption().
FormatRvcRegister()
template<typename V >
int v8::internal::Decoder< V >::FormatRvcRegister (Instruction * instr, const char * option) [private]
Definition at line 563 of file disasm-riscv.cc.
                                                                     {
  DCHECK_EQ(format[0], 'C');
  DCHECK(format[1] == 'r' || format[1] == 'f');
  if (format[2] == 's') { // 'Crs[12]: Rs register.
    if (format[3] == '1') {
      if (format[4] == 's') { // 'Crs1s: 3-bits register
        int reg = instr->RvcRs1sValue();
        if (format[1] == 'r') {
          PrintRegister(reg);
        } else if (format[1] == 'f') {
          PrintFPURegister(reg);
        }
        return 5;
      }
      int reg = instr->RvcRs1Value();
      if (format[1] == 'r') {
        PrintRegister(reg);
      } else if (format[1] == 'f') {
        PrintFPURegister(reg);
      }
      return 4;
    } else if (format[3] == '2') {
      if (format[4] == 's') { // 'Crs2s: 3-bits register
        int reg = instr->RvcRs2sValue();
        if (format[1] == 'r') {
          PrintRegister(reg);
        } else if (format[1] == 'f') {
          PrintFPURegister(reg);
        }
        return 5;
      }
      int reg = instr->RvcRs2Value();
      if (format[1] == 'r') {
        PrintRegister(reg);
      } else if (format[1] == 'f') {
        PrintFPURegister(reg);
      }
      return 4;
    }
    UNREACHABLE();
  } else if (format[2] == 'd') { // 'Crd: rd register.
    int reg = instr->RvcRdValue();
    if (format[1] == 'r') {
      PrintRegister(reg);
    } else if (format[1] == 'f') {
      PrintFPURegister(reg);
    }
    return 3;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::format, v8::internal::Decoder< V >::PrintFPURegister(), v8::internal::Decoder< V >::PrintRegister(), v8::internal::InstructionGetters< T >::RvcRdValue(), v8::internal::InstructionGetters< T >::RvcRs1sValue(), v8::internal::InstructionGetters< T >::RvcRs1Value(), v8::internal::InstructionGetters< T >::RvcRs2sValue(), v8::internal::InstructionGetters< T >::RvcRs2Value(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::FormatOption().
InstructionDecode()
template<typename V >
int v8::internal::Decoder< V >::InstructionDecode (uint8_t * instruction)
Definition at line 3243 of file disasm-riscv.cc.
                                                 {
  Instruction* instr = Instruction::At(instr_ptr);
  // Print raw instruction bytes.
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_,
                                    "%08x ", instr->InstructionBits());
  switch (instr->InstructionType()) {
    case Instruction::kRType:
      DecodeRType(instr);
      break;
    case Instruction::kR4Type:
      DecodeR4Type(instr);
      break;
    case Instruction::kIType:
      DecodeIType(instr);
      break;
    case Instruction::kSType:
      DecodeSType(instr);
      break;
    case Instruction::kBType:
      DecodeBType(instr);
      break;
    case Instruction::kUType:
      DecodeUType(instr);
      break;
    case Instruction::kJType:
      DecodeJType(instr);
      break;
    case Instruction::kCRType:
      DecodeCRType(instr);
      break;
    case Instruction::kCAType:
      DecodeCAType(instr);
      break;
    case Instruction::kCJType:
      DecodeCJType(instr);
      break;
    case Instruction::kCIType:
      DecodeCIType(instr);
      break;
    case Instruction::kCIWType:
      DecodeCIWType(instr);
      break;
    case Instruction::kCSSType:
      DecodeCSSType(instr);
      break;
    case Instruction::kCLType:
      DecodeCLType(instr);
      break;
    case Instruction::kCSType:
      DecodeCSType(instr);
      break;
    case Instruction::kCBType:
      DecodeCBType(instr);
      break;
#ifdef CAN_USE_RVV_INSTRUCTIONS
    case Instruction::kVType:
      DecodeVType(instr);
      break;
#endif
    default:
      Format(instr, "UNSUPPORTED");
      break;
  }
  return instr->InstructionSize();
}
References v8::internal::Instruction::At(), v8::internal::Decoder< V >::DecodeBType(), v8::internal::Decoder< V >::DecodeCAType(), v8::internal::Decoder< V >::DecodeCBType(), v8::internal::Decoder< V >::DecodeCIType(), v8::internal::Decoder< V >::DecodeCIWType(), v8::internal::Decoder< V >::DecodeCJType(), v8::internal::Decoder< V >::DecodeCLType(), v8::internal::Decoder< V >::DecodeCRType(), v8::internal::Decoder< V >::DecodeCSSType(), v8::internal::Decoder< V >::DecodeCSType(), v8::internal::Decoder< V >::DecodeIType(), v8::internal::Decoder< V >::DecodeJType(), v8::internal::Decoder< V >::DecodeR4Type(), v8::internal::Decoder< V >::DecodeRType(), v8::internal::Decoder< V >::DecodeSType(), v8::internal::Decoder< V >::DecodeUType(), v8::internal::Decoder< V >::DecodeVType(), v8::internal::Decoder< V >::Format(), v8::internal::Instruction::InstructionBits(), v8::internal::InstructionBase::InstructionSize(), v8::internal::InstructionBase::InstructionType(), v8::internal::InstructionBase::kBType, v8::internal::InstructionBase::kCAType, v8::internal::InstructionBase::kCBType, v8::internal::InstructionBase::kCIType, v8::internal::InstructionBase::kCIWType, v8::internal::InstructionBase::kCJType, v8::internal::InstructionBase::kCLType, v8::internal::InstructionBase::kCRType, v8::internal::InstructionBase::kCSSType, v8::internal::InstructionBase::kCSType, v8::internal::InstructionBase::kIType, v8::internal::InstructionBase::kJType, v8::internal::InstructionBase::kR4Type, v8::internal::InstructionBase::kRType, v8::internal::InstructionBase::kSType, v8::internal::InstructionBase::kUType, v8::internal::InstructionBase::kVType, v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::base::SNPrintF().
Referenced by disasm::Disassembler::InstructionDecode().
operator=()
template<typename V >
Decoder& v8::internal::Decoder< V >::operator= (const Decoder< V > &) [delete]
Print()
template<typename V >
void v8::internal::Decoder< V >::Print (const char * str) [private]
Definition at line 172 of file disasm-riscv.cc.
                                   {
  char cur = *str++;
  while (cur != '\0' && (out_buffer_pos_ < (out_buffer_.length() - 1))) {
    PrintChar(cur);
    cur = *str++;
  }
  out_buffer_[out_buffer_pos_] = 0;
}
References v8::base::Vector< T >::length(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::internal::Decoder< V >::PrintChar().
Referenced by v8::internal::Decoder< V >::PrintFPURegister(), v8::internal::Decoder< V >::PrintRegister(), and v8::internal::Decoder< V >::PrintVRegister().
PrintAcquireRelease()
template<typename V >
void v8::internal::Decoder< V >::PrintAcquireRelease (Instruction * instr) [private]
Definition at line 403 of file disasm-riscv.cc.
                                                    {
  bool aq = instr->AqValue();
  bool rl = instr->RlValue();
  if (aq || rl) {
    out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, ".");
  }
  if (aq) {
    out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "aq");
  }
  if (rl) {
    out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "rl");
  }
}
References v8::internal::InstructionGetters< T >::AqValue(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RlValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintBranchOffset()
template<typename V >
void v8::internal::Decoder< V >::PrintBranchOffset (Instruction * instr) [private]
Definition at line 275 of file disasm-riscv.cc.
                                                  {
  int32_t imm = instr->BranchOffset();
  const char* target =
      converter_.NameOfAddress(reinterpret_cast<uint8_t*>(instr) + imm);
  out_buffer_pos_ +=
      base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d -> %s", imm, target);
}
References v8::internal::InstructionGetters< T >::BranchOffset(), v8::internal::Decoder< V >::converter_, disasm::NameConverter::NameOfAddress(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintChar()
template<typename V >
void v8::internal::Decoder< V >::PrintChar (const char ch) [private]
Definition at line 169 of file disasm-riscv.cc.
{ out_buffer_[out_buffer_pos_++] = ch; }
References v8::internal::Decoder< V >::out_buffer_, and v8::internal::Decoder< V >::out_buffer_pos_.
Referenced by v8::internal::Decoder< V >::Print().
PrintCSRReg()
template<typename V >
void v8::internal::Decoder< V >::PrintCSRReg (Instruction * instr) [private]
Definition at line 417 of file disasm-riscv.cc.
                                            {
  int32_t csr_reg = instr->CsrValue();
  std::string s;
  switch (csr_reg) {
    case csr_fflags: // Floating-Point Accrued Exceptions (RW)
      s = "csr_fflags";
      break;
    case csr_frm: // Floating-Point Dynamic Rounding Mode (RW)
      s = "csr_frm";
      break;
    case csr_fcsr: // Floating-Point Control and Status Register (RW)
      s = "csr_fcsr";
      break;
    case csr_cycle:
      s = "csr_cycle";
      break;
    case csr_time:
      s = "csr_time";
      break;
    case csr_instret:
      s = "csr_instret";
      break;
    case csr_cycleh:
      s = "csr_cycleh";
      break;
    case csr_timeh:
      s = "csr_timeh";
      break;
    case csr_instreth:
      s = "csr_instreth";
      break;
    default:
      UNREACHABLE();
  }
  out_buffer_pos_ +=
      base::SNPrintF(out_buffer_ + out_buffer_pos_, "%s", s.c_str());
}
References v8::internal::csr_cycle, v8::internal::csr_cycleh, v8::internal::csr_fcsr, v8::internal::csr_fflags, v8::internal::csr_frm, v8::internal::csr_instret, v8::internal::csr_instreth, v8::internal::csr_time, v8::internal::csr_timeh, v8::internal::InstructionGetters< T >::CsrValue(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::base::SNPrintF(), v8::internal::string, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintFPURegister()
template<typename V >
void v8::internal::Decoder< V >::PrintFPURegister (int freg) [private]
Definition at line 226 of file disasm-riscv.cc.
                                       {
  Print(converter_.NameOfXMMRegister(freg));
}
References v8::internal::Decoder< V >::converter_, disasm::NameConverter::NameOfXMMRegister(), and v8::internal::Decoder< V >::Print().
Referenced by v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode(), v8::internal::Decoder< V >::FormatRvcRegister(), v8::internal::Decoder< V >::PrintFRd(), v8::internal::Decoder< V >::PrintFRs1(), v8::internal::Decoder< V >::PrintFRs2(), and v8::internal::Decoder< V >::PrintFRs3().
PrintFPUStatusRegister()
template<typename V >
void v8::internal::Decoder< V >::PrintFPUStatusRegister (int freg) [private]
PrintFRd()
template<typename V >
void v8::internal::Decoder< V >::PrintFRd (Instruction * instr) [private]
Definition at line 245 of file disasm-riscv.cc.
                                         {
  int reg = instr->RdValue();
  PrintFPURegister(reg);
}
References v8::internal::Decoder< V >::PrintFPURegister(), and v8::internal::Instruction::RdValue().
PrintFRs1()
template<typename V >
void v8::internal::Decoder< V >::PrintFRs1 (Instruction * instr) [private]
Definition at line 230 of file disasm-riscv.cc.
                                          {
  int reg = instr->Rs1Value();
  PrintFPURegister(reg);
}
References v8::internal::Decoder< V >::PrintFPURegister(), and v8::internal::InstructionGetters< T >::Rs1Value().
PrintFRs2()
template<typename V >
void v8::internal::Decoder< V >::PrintFRs2 (Instruction * instr) [private]
Definition at line 235 of file disasm-riscv.cc.
                                          {
  int reg = instr->Rs2Value();
  PrintFPURegister(reg);
}
References v8::internal::Decoder< V >::PrintFPURegister(), and v8::internal::InstructionGetters< T >::Rs2Value().
PrintFRs3()
template<typename V >
void v8::internal::Decoder< V >::PrintFRs3 (Instruction * instr) [private]
Definition at line 240 of file disasm-riscv.cc.
                                          {
  int reg = instr->Rs3Value();
  PrintFPURegister(reg);
}
References v8::internal::Decoder< V >::PrintFPURegister(), and v8::internal::InstructionGetters< T >::Rs3Value().
PrintImm12()
template<typename V >
void v8::internal::Decoder< V >::PrintImm12 (Instruction * instr) [private]
Definition at line 255 of file disasm-riscv.cc.
                                           {
  int32_t imm = instr->Imm12Value();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::InstructionGetters< T >::Imm12Value(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintImm12X()
template<typename V >
void v8::internal::Decoder< V >::PrintImm12X (Instruction * instr) [private]
Definition at line 250 of file disasm-riscv.cc.
                                            {
  int32_t imm = instr->Imm12Value();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "0x%x", imm);
}
References v8::internal::InstructionGetters< T >::Imm12Value(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintImm20J()
template<typename V >
void v8::internal::Decoder< V >::PrintImm20J (Instruction * instr) [private]
Definition at line 313 of file disasm-riscv.cc.
                                            {
  int32_t imm = instr->Imm20JValue();
  const char* target =
      converter_.NameOfAddress(reinterpret_cast<uint8_t*>(instr) + imm);
  out_buffer_pos_ +=
      base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d -> %s", imm, target);
}
References v8::internal::Decoder< V >::converter_, v8::internal::InstructionGetters< T >::Imm20JValue(), disasm::NameConverter::NameOfAddress(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintImm20U()
template<typename V >
void v8::internal::Decoder< V >::PrintImm20U (Instruction * instr) [private]
Definition at line 308 of file disasm-riscv.cc.
                                            {
  int32_t imm = instr->Imm20UValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "0x%x", imm);
}
References v8::internal::InstructionGetters< T >::Imm20UValue(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintInstructionName()
template<typename V >
void v8::internal::Decoder< V >::PrintInstructionName (Instruction * instr) [private]
Definition at line 504 of file disasm-riscv.cc.
{}
PrintMemoryOrder()
template<typename V >
void v8::internal::Decoder< V >::PrintMemoryOrder (Instruction * instr, bool is_pred) [private]
Definition at line 484 of file disasm-riscv.cc.
                                                               {
  int memOrder = instr->MemoryOrder(is_pred);
  std::string s;
  if ((memOrder & PSI) == PSI) {
    s += "i";
  }
  if ((memOrder & PSO) == PSO) {
    s += "o";
  }
  if ((memOrder & PSR) == PSR) {
    s += "r";
  }
  if ((memOrder & PSW) == PSW) {
    s += "w";
  }
  out_buffer_pos_ +=
      base::SNPrintF(out_buffer_ + out_buffer_pos_, "%s", s.c_str());
}
References v8::internal::InstructionGetters< T >::MemoryOrder(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::PSI, v8::internal::PSO, v8::internal::PSR, v8::internal::PSW, v8::base::SNPrintF(), and v8::internal::string.
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintRd()
template<typename V >
void v8::internal::Decoder< V >::PrintRd (Instruction * instr) [private]
Definition at line 200 of file disasm-riscv.cc.
                                        {
  int reg = instr->RdValue();
  PrintRegister(reg);
}
References v8::internal::Decoder< V >::PrintRegister(), and v8::internal::Instruction::RdValue().
PrintRegister()
template<typename V >
void v8::internal::Decoder< V >::PrintRegister (int reg) [private]
Definition at line 182 of file disasm-riscv.cc.
                                   {
  Print(converter_.NameOfCPURegister(reg));
}
References v8::internal::Decoder< V >::converter_, disasm::NameConverter::NameOfCPURegister(), and v8::internal::Decoder< V >::Print().
Referenced by v8::internal::Decoder< V >::FormatRegister(), v8::internal::Decoder< V >::FormatRvcRegister(), v8::internal::Decoder< V >::PrintRd(), v8::internal::Decoder< V >::PrintRs1(), and v8::internal::Decoder< V >::PrintRs2().
PrintRoundingMode()
template<typename V >
void v8::internal::Decoder< V >::PrintRoundingMode (Instruction * instr) [private]
Definition at line 455 of file disasm-riscv.cc.
                                                  {
  int frm = instr->RoundMode();
  std::string s;
  switch (frm) {
    case RNE:
      s = "RNE";
      break;
    case RTZ:
      s = "RTZ";
      break;
    case RDN:
      s = "RDN";
      break;
    case RUP:
      s = "RUP";
      break;
    case RMM:
      s = "RMM";
      break;
    case DYN:
      s = "DYN";
      break;
    default:
      UNREACHABLE();
  }
  out_buffer_pos_ +=
      base::SNPrintF(out_buffer_ + out_buffer_pos_, "%s", s.c_str());
}
References v8::internal::DYN, v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::RDN, v8::internal::RMM, v8::internal::RNE, v8::internal::InstructionGetters< T >::RoundMode(), v8::internal::RTZ, v8::internal::RUP, v8::base::SNPrintF(), v8::internal::string, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode().
PrintRs1()
template<typename V >
void v8::internal::Decoder< V >::PrintRs1 (Instruction * instr) [private]
Definition at line 190 of file disasm-riscv.cc.
                                         {
  int reg = instr->Rs1Value();
  PrintRegister(reg);
}
References v8::internal::Decoder< V >::PrintRegister(), and v8::internal::InstructionGetters< T >::Rs1Value().
PrintRs2()
template<typename V >
void v8::internal::Decoder< V >::PrintRs2 (Instruction * instr) [private]
Definition at line 195 of file disasm-riscv.cc.
                                         {
  int reg = instr->Rs2Value();
  PrintRegister(reg);
}
References v8::internal::Decoder< V >::PrintRegister(), and v8::internal::InstructionGetters< T >::Rs2Value().
PrintRvcImm11CJ()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm11CJ (Instruction * instr) [private]
Definition at line 386 of file disasm-riscv.cc.
                                                {
  int32_t imm = instr->RvcImm11CJValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm11CJValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm5D()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm5D (Instruction * instr) [private]
Definition at line 376 of file disasm-riscv.cc.
                                              {
  int32_t imm = instr->RvcImm5DValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm5DValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm5W()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm5W (Instruction * instr) [private]
Definition at line 371 of file disasm-riscv.cc.
                                              {
  int32_t imm = instr->RvcImm5WValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm5WValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6 (Instruction * instr) [private]
Definition at line 331 of file disasm-riscv.cc.
                                             {
  int32_t imm = instr->RvcImm6Value();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6Value(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6Addi16sp()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6Addi16sp (Instruction * instr) [private]
Definition at line 341 of file disasm-riscv.cc.
                                                     {
  int32_t imm = instr->RvcImm6Addi16spValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6Addi16spValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6Ldsp()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6Ldsp (Instruction * instr) [private]
Definition at line 351 of file disasm-riscv.cc.
                                                 {
  int32_t imm = instr->RvcImm6LdspValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6LdspValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6Lwsp()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6Lwsp (Instruction * instr) [private]
Definition at line 356 of file disasm-riscv.cc.
                                                 {
  int32_t imm = instr->RvcImm6LwspValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6LwspValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6Sdsp()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6Sdsp (Instruction * instr) [private]
Definition at line 366 of file disasm-riscv.cc.
                                                 {
  int32_t imm = instr->RvcImm6SdspValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6SdspValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6Swsp()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6Swsp (Instruction * instr) [private]
Definition at line 361 of file disasm-riscv.cc.
                                                 {
  int32_t imm = instr->RvcImm6SwspValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6SwspValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm6U()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm6U (Instruction * instr) [private]
Definition at line 336 of file disasm-riscv.cc.
                                              {
  int32_t imm = instr->RvcImm6Value() & 0xFFFFF;
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "0x%x", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm6Value(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm8Addi4spn()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm8Addi4spn (Instruction * instr) [private]
Definition at line 381 of file disasm-riscv.cc.
                                                     {
  int32_t imm = instr->RvcImm8Addi4spnValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm8Addi4spnValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcImm8B()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcImm8B (Instruction * instr) [private]
Definition at line 391 of file disasm-riscv.cc.
                                              {
  int32_t imm = instr->RvcImm8BValue();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcImm8BValue(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatRvcImm().
PrintRvcShamt()
template<typename V >
void v8::internal::Decoder< V >::PrintRvcShamt (Instruction * instr) [private]
Definition at line 346 of file disasm-riscv.cc.
                                              {
  int32_t imm = instr->RvcShamt6();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvcShamt6(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintRvvLMUL()
template<typename V >
void v8::internal::Decoder< V >::PrintRvvLMUL (Instruction * instr) [private]
Definition at line 293 of file disasm-riscv.cc.
                                             {
  const char* lmul = instr->RvvLMUL();
  out_buffer_pos_ += SNPrintF(out_buffer_ + out_buffer_pos_, "%s", lmul);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvvLMUL(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintRvvSEW()
template<typename V >
void v8::internal::Decoder< V >::PrintRvvSEW (Instruction * instr) [private]
Definition at line 288 of file disasm-riscv.cc.
                                            {
  const char* sew = instr->RvvSEW();
  out_buffer_pos_ += SNPrintF(out_buffer_ + out_buffer_pos_, "%s", sew);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvvSEW(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintRvvSimm5()
template<typename V >
void v8::internal::Decoder< V >::PrintRvvSimm5 (Instruction * instr) [private]
Definition at line 298 of file disasm-riscv.cc.
                                              {
  const int simm5 = instr->RvvSimm5();
  out_buffer_pos_ += SNPrintF(out_buffer_ + out_buffer_pos_, "%d", simm5);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvvSimm5(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintRvvUimm5()
template<typename V >
void v8::internal::Decoder< V >::PrintRvvUimm5 (Instruction * instr) [private]
Definition at line 303 of file disasm-riscv.cc.
                                              {
  const uint32_t uimm5 = instr->RvvUimm5();
  out_buffer_pos_ += SNPrintF(out_buffer_ + out_buffer_pos_, "%u", uimm5);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvvUimm5(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintRvvVm()
template<typename V >
void v8::internal::Decoder< V >::PrintRvvVm (Instruction * instr) [private]
Definition at line 396 of file disasm-riscv.cc.
                                           {
  uint8_t imm = instr->RvvVM();
  if (imm == 0) {
    out_buffer_pos_ += SNPrintF(out_buffer_ + out_buffer_pos_, " v0.t");
  }
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::RvvVM(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintShamt()
template<typename V >
void v8::internal::Decoder< V >::PrintShamt (Instruction * instr) [private]
Definition at line 321 of file disasm-riscv.cc.
                                           {
  int32_t imm = instr->Shamt();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::Shamt(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintShamt32()
template<typename V >
void v8::internal::Decoder< V >::PrintShamt32 (Instruction * instr) [private]
Definition at line 326 of file disasm-riscv.cc.
                                             {
  int32_t imm = instr->Shamt32();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::Shamt32(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintStoreOffset()
template<typename V >
void v8::internal::Decoder< V >::PrintStoreOffset (Instruction * instr) [private]
Definition at line 283 of file disasm-riscv.cc.
                                                 {
  int32_t imm = instr->StoreOffset();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "%d", imm);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::base::SNPrintF(), and v8::internal::InstructionGetters< T >::StoreOffset().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintTarget()
template<typename V >
void v8::internal::Decoder< V >::PrintTarget (Instruction * instr) [private]
Definition at line 260 of file disasm-riscv.cc.
                                            {
  if (Assembler::IsJalr(instr->InstructionBits())) {
    if (Assembler::IsAuipc((instr - 4)->InstructionBits()) &&
        (instr - 4)->RdValue() == instr->Rs1Value()) {
      int32_t imm = Assembler::BrachlongOffset((instr - 4)->InstructionBits(),
                                               instr->InstructionBits());
      const char* target =
          converter_.NameOfAddress(reinterpret_cast<uint8_t*>(instr - 4) + imm);
      out_buffer_pos_ +=
          base::SNPrintF(out_buffer_ + out_buffer_pos_, " -> %s", target);
      return;
    }
  }
}
References v8::internal::Assembler::BrachlongOffset(), v8::internal::Decoder< V >::converter_, v8::internal::Instruction::InstructionBits(), v8::internal::AssemblerRISCVI::IsAuipc(), v8::internal::Assembler::IsJalr(), disasm::NameConverter::NameOfAddress(), v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::Rs1Value(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintUimm()
template<typename V >
void v8::internal::Decoder< V >::PrintUimm (Instruction * instr) [private]
Definition at line 205 of file disasm-riscv.cc.
                                          {
  int val = instr->Rs1Value();
  out_buffer_pos_ += base::SNPrintF(out_buffer_ + out_buffer_pos_, "0x%x", val);
}
References v8::internal::Decoder< V >::out_buffer_, v8::internal::Decoder< V >::out_buffer_pos_, v8::internal::InstructionGetters< T >::Rs1Value(), and v8::base::SNPrintF().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintVd()
template<typename V >
void v8::internal::Decoder< V >::PrintVd (Instruction * instr) [private]
Definition at line 220 of file disasm-riscv.cc.
                                        {
  int reg = instr->VdValue();
  PrintVRegister(reg);
}
References v8::internal::Decoder< V >::PrintVRegister(), and v8::internal::Instruction::VdValue().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintVRegister()
template<typename V >
void v8::internal::Decoder< V >::PrintVRegister (int reg) [private]
Definition at line 186 of file disasm-riscv.cc.
                                    {
  Print(v8::internal::VRegisters::Name(reg));
}
References v8::internal::VRegisters::Name(), and v8::internal::Decoder< V >::Print().
Referenced by v8::internal::Decoder< V >::PrintVd(), v8::internal::Decoder< V >::PrintVs1(), and v8::internal::Decoder< V >::PrintVs2().
PrintVs1()
template<typename V >
void v8::internal::Decoder< V >::PrintVs1 (Instruction * instr) [private]
Definition at line 210 of file disasm-riscv.cc.
                                         {
  int reg = instr->Vs1Value();
  PrintVRegister(reg);
}
References v8::internal::Decoder< V >::PrintVRegister(), and v8::internal::InstructionGetters< T >::Vs1Value().
Referenced by v8::internal::Decoder< V >::FormatOption().
PrintVs2()
template<typename V >
void v8::internal::Decoder< V >::PrintVs2 (Instruction * instr) [private]
Definition at line 215 of file disasm-riscv.cc.
                                         {
  int reg = instr->Vs2Value();
  PrintVRegister(reg);
}
References v8::internal::Decoder< V >::PrintVRegister(), and v8::internal::InstructionGetters< T >::Vs2Value().
Referenced by v8::internal::Decoder< V >::FormatOption().
switch_nf()
template<typename V >
int v8::internal::Decoder< V >::switch_nf (Instruction * instr) [private]
Definition at line 3077 of file disasm-riscv.cc.
                                         {
  int nf = 0;
  switch (instr->InstructionBits() & kRvvNfMask) {
    case 0x20000000:
      nf = 2;
      break;
    case 0x40000000:
      nf = 3;
      break;
    case 0x60000000:
      nf = 4;
      break;
    case 0x80000000:
      nf = 5;
      break;
    case 0xa0000000:
      nf = 6;
      break;
    case 0xc0000000:
      nf = 7;
      break;
    case 0xe0000000:
      nf = 8;
      break;
  }
  return nf;
}
References v8::internal::Instruction::InstructionBits(), and v8::internal::kRvvNfMask.
Referenced by v8::internal::Decoder< V >::DecodeRvvVL(), and v8::internal::Decoder< V >::DecodeRvvVS().
switch_sew()
template<typename V >
int v8::internal::Decoder< V >::switch_sew (Instruction * instr) [private]
Definition at line 3158 of file disasm-riscv.cc.
                                          {
  int width = 0;
  if ((instr->InstructionBits() & kBaseOpcodeMask) != LOAD_FP &&
      (instr->InstructionBits() & kBaseOpcodeMask) != STORE_FP)
    return -1;
  switch (instr->InstructionBits() & (kRvvWidthMask | kRvvMewMask)) {
    case 0x0:
      width = 8;
      break;
    case 0x00005000:
      width = 16;
      break;
    case 0x00006000:
      width = 32;
      break;
    case 0x00007000:
      width = 64;
      break;
    case 0x10000000:
      width = 128;
      break;
    case 0x10005000:
      width = 256;
      break;
    case 0x10006000:
      width = 512;
      break;
    case 0x10007000:
      width = 1024;
      break;
    default:
      width = -1;
      break;
  }
  return width;
}
References v8::internal::Instruction::InstructionBits(), v8::internal::kBaseOpcodeMask, v8::internal::kRvvMewMask, v8::internal::kRvvWidthMask, v8::internal::LOAD_FP, and v8::internal::STORE_FP.
Unknown()
template<typename V >
void v8::internal::Decoder< V >::Unknown (Instruction * instr) [private]
Definition at line 869 of file disasm-riscv.cc.
{ Format(instr, "unknown"); }
References v8::internal::Decoder< V >::Format().
Member Data Documentation
converter_
template<typename V >
const disasm::NameConverter& v8::internal::Decoder< V >::converter_ [private]
Definition at line 159 of file disasm-riscv.cc.
Referenced by v8::internal::Decoder< V >::PrintBranchOffset(), v8::internal::Decoder< V >::PrintFPURegister(), v8::internal::Decoder< V >::PrintImm20J(), v8::internal::Decoder< V >::PrintRegister(), and v8::internal::Decoder< V >::PrintTarget().
out_buffer_
template<typename V >
v8::base::Vector<char> v8::internal::Decoder< V >::out_buffer_ [private]
Definition at line 160 of file disasm-riscv.cc.
Referenced by v8::internal::Decoder< V >::Decoder(), v8::internal::Decoder< V >::Format(), v8::internal::Decoder< V >::InstructionDecode(), v8::internal::Decoder< V >::Print(), v8::internal::Decoder< V >::PrintAcquireRelease(), v8::internal::Decoder< V >::PrintBranchOffset(), v8::internal::Decoder< V >::PrintChar(), v8::internal::Decoder< V >::PrintCSRReg(), v8::internal::Decoder< V >::PrintImm12(), v8::internal::Decoder< V >::PrintImm12X(), v8::internal::Decoder< V >::PrintImm20J(), v8::internal::Decoder< V >::PrintImm20U(), v8::internal::Decoder< V >::PrintMemoryOrder(), v8::internal::Decoder< V >::PrintRoundingMode(), v8::internal::Decoder< V >::PrintRvcImm11CJ(), v8::internal::Decoder< V >::PrintRvcImm5D(), v8::internal::Decoder< V >::PrintRvcImm5W(), v8::internal::Decoder< V >::PrintRvcImm6(), v8::internal::Decoder< V >::PrintRvcImm6Addi16sp(), v8::internal::Decoder< V >::PrintRvcImm6Ldsp(), v8::internal::Decoder< V >::PrintRvcImm6Lwsp(), v8::internal::Decoder< V >::PrintRvcImm6Sdsp(), v8::internal::Decoder< V >::PrintRvcImm6Swsp(), v8::internal::Decoder< V >::PrintRvcImm6U(), v8::internal::Decoder< V >::PrintRvcImm8Addi4spn(), v8::internal::Decoder< V >::PrintRvcImm8B(), v8::internal::Decoder< V >::PrintRvcShamt(), v8::internal::Decoder< V >::PrintRvvLMUL(), v8::internal::Decoder< V >::PrintRvvSEW(), v8::internal::Decoder< V >::PrintRvvSimm5(), v8::internal::Decoder< V >::PrintRvvUimm5(), v8::internal::Decoder< V >::PrintRvvVm(), v8::internal::Decoder< V >::PrintShamt(), v8::internal::Decoder< V >::PrintShamt32(), v8::internal::Decoder< V >::PrintStoreOffset(), v8::internal::Decoder< V >::PrintTarget(), and v8::internal::Decoder< V >::PrintUimm().
out_buffer_pos_
template<typename V >
int v8::internal::Decoder< V >::out_buffer_pos_ [private]
Definition at line 161 of file disasm-riscv.cc.
Referenced by v8::internal::Decoder< V >::Decoder(), v8::internal::Decoder< V >::Format(), v8::internal::Decoder< V >::InstructionDecode(), v8::internal::Decoder< V >::Print(), v8::internal::Decoder< V >::PrintAcquireRelease(), v8::internal::Decoder< V >::PrintBranchOffset(), v8::internal::Decoder< V >::PrintChar(), v8::internal::Decoder< V >::PrintCSRReg(), v8::internal::Decoder< V >::PrintImm12(), v8::internal::Decoder< V >::PrintImm12X(), v8::internal::Decoder< V >::PrintImm20J(), v8::internal::Decoder< V >::PrintImm20U(), v8::internal::Decoder< V >::PrintMemoryOrder(), v8::internal::Decoder< V >::PrintRoundingMode(), v8::internal::Decoder< V >::PrintRvcImm11CJ(), v8::internal::Decoder< V >::PrintRvcImm5D(), v8::internal::Decoder< V >::PrintRvcImm5W(), v8::internal::Decoder< V >::PrintRvcImm6(), v8::internal::Decoder< V >::PrintRvcImm6Addi16sp(), v8::internal::Decoder< V >::PrintRvcImm6Ldsp(), v8::internal::Decoder< V >::PrintRvcImm6Lwsp(), v8::internal::Decoder< V >::PrintRvcImm6Sdsp(), v8::internal::Decoder< V >::PrintRvcImm6Swsp(), v8::internal::Decoder< V >::PrintRvcImm6U(), v8::internal::Decoder< V >::PrintRvcImm8Addi4spn(), v8::internal::Decoder< V >::PrintRvcImm8B(), v8::internal::Decoder< V >::PrintRvcShamt(), v8::internal::Decoder< V >::PrintRvvLMUL(), v8::internal::Decoder< V >::PrintRvvSEW(), v8::internal::Decoder< V >::PrintRvvSimm5(), v8::internal::Decoder< V >::PrintRvvUimm5(), v8::internal::Decoder< V >::PrintRvvVm(), v8::internal::Decoder< V >::PrintShamt(), v8::internal::Decoder< V >::PrintShamt32(), v8::internal::Decoder< V >::PrintStoreOffset(), v8::internal::Decoder< V >::PrintTarget(), and v8::internal::Decoder< V >::PrintUimm().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm64/decoder-arm64.h
/mnt/V8SourceCode/src/diagnostics/riscv/disasm-riscv.cc
/mnt/V8SourceCode/src/codegen/arm64/decoder-arm64-inl.h