v8::internal::ChoiceNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
ChoiceNode (int expected_size, Zone *zone)
ChoiceNode * AsChoiceNode () override
void Accept (NodeVisitor *visitor) override
void AddAlternative (GuardedAlternative node)
ZoneList< GuardedAlternative > * alternatives ()
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
bool being_calculated ()
bool not_at_start ()
void set_not_at_start ()
void set_being_calculated (bool b)
virtual bool try_to_emit_quick_check_for_alternative (bool is_first)
RegExpNode * FilterOneByte (int depth, RegExpCompiler *compiler) override
virtual bool read_backward ()
Protected Member Functions
int FixedLengthLoopLengthForAlternative (GuardedAlternative *alternative)
Protected Attributes
ZoneList< GuardedAlternative > * alternatives_
Private Member Functions
void GenerateGuard (RegExpMacroAssembler *macro_assembler, Guard *guard, Trace *trace)
int CalculatePreloadCharacters (RegExpCompiler *compiler, int eats_at_least)
void EmitOutOfLineContinuation (RegExpCompiler *compiler, Trace *trace, GuardedAlternative alternative, AlternativeGeneration *alt_gen, int preload_characters, bool next_expects_preload)
void SetUpPreLoad (RegExpCompiler *compiler, Trace *current_trace, PreloadState *preloads)
void AssertGuardsMentionRegisters (Trace *trace)
int EmitOptimizedUnanchoredSearch (RegExpCompiler *compiler, Trace *trace)
Trace * EmitFixedLengthLoop (RegExpCompiler *compiler, Trace *trace, AlternativeGenerationList *alt_gens, PreloadState *preloads, FixedLengthLoopState *fixed_length_loop_state, int text_length)
void EmitChoices (RegExpCompiler *compiler, AlternativeGenerationList *alt_gens, int first_choice, Trace *trace, PreloadState *preloads)
Private Attributes
bool not_at_start_
bool being_calculated_
Friends
template<typename... >
class Analysis
Additional Inherited Members
Detailed Description
Definition at line 657 of file regexp-nodes.h.
Constructor & Destructor Documentation
ChoiceNode()
v8::internal::ChoiceNode::ChoiceNode (int expected_size, Zone * zone) [inline], [explicit]
Definition at line 659 of file regexp-nodes.h.
      : RegExpNode(zone),
        alternatives_(
            zone->New<ZoneList<GuardedAlternative>>(expected_size, zone)),
        not_at_start_(false),
        being_calculated_(false) {}
Member Function Documentation
Accept()
void v8::internal::ChoiceNode::Accept (NodeVisitor * visitor) [override], [virtual]
Implements v8::internal::RegExpNode.
Reimplemented in v8::internal::LoopChoiceNode, and v8::internal::NegativeLookaroundChoiceNode.
AddAlternative()
void v8::internal::ChoiceNode::AddAlternative (GuardedAlternative node) [inline]
Definition at line 667 of file regexp-nodes.h.
                                               {
    alternatives()->Add(node, zone());
  }
References alternatives(), and v8::internal::RegExpNode::zone().
Referenced by v8::internal::LoopChoiceNode::AddAlternative(), v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate(), and v8::internal::RegExpCompiler::PreprocessRegExp().
alternatives()
ZoneList<GuardedAlternative>* v8::internal::ChoiceNode::alternatives () [inline]
Definition at line 670 of file regexp-nodes.h.
{ return alternatives_; }
References alternatives_.
Referenced by AddAlternative(), FillInBMInfo(), v8::internal::Analysis< Propagators >::VisitChoice(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitChoice(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitChoice(), v8::internal::Analysis< Propagators >::VisitLoopChoice(), and v8::internal::Analysis< Propagators >::VisitNegativeLookaroundChoice().
AsChoiceNode()
ChoiceNode* v8::internal::ChoiceNode::AsChoiceNode () [inline], [override]
Definition at line 665 of file regexp-nodes.h.
{ return this; }
AssertGuardsMentionRegisters()
void v8::internal::ChoiceNode::AssertGuardsMentionRegisters (Trace * trace) [private]
Definition at line 3178 of file regexp-compiler.cc.
                                                          {
#ifdef DEBUG
  int choice_count = alternatives_->length();
  for (int i = 0; i < choice_count - 1; i++) {
    GuardedAlternative alternative = alternatives_->at(i);
    ZoneList<Guard*>* guards = alternative.guards();
    int guard_count = (guards == nullptr) ? 0 : guards->length();
    for (int j = 0; j < guard_count; j++) {
      DCHECK(!trace->mentions_reg(guards->at(j)->reg()));
    }
  }
#endif
}
References alternatives_, v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), v8::internal::GuardedAlternative::guards(), v8::internal::ZoneList< T >::length(), and v8::internal::Trace::mentions_reg().
Referenced by Emit().
being_calculated()
bool v8::internal::ChoiceNode::being_calculated () [inline]
Definition at line 678 of file regexp-nodes.h.
{ return being_calculated_; }
References being_calculated_.
CalculatePreloadCharacters()
int v8::internal::ChoiceNode::CalculatePreloadCharacters (RegExpCompiler * compiler, int eats_at_least) [private]
Definition at line 2732 of file regexp-compiler.cc.
                                                              {
  int preload_characters = std::min(4, eats_at_least);
  DCHECK_LE(preload_characters, 4);
  if (compiler->macro_assembler()->CanReadUnaligned()) {
    bool one_byte = compiler->one_byte();
    if (one_byte) {
      // We can't preload 3 characters because there is no machine instruction
      // to do that. We can't just load 4 because we could be reading
      // beyond the end of the string, which could cause a memory fault.
      if (preload_characters == 3) preload_characters = 2;
    } else {
      if (preload_characters > 2) preload_characters = 2;
    }
  } else {
    if (preload_characters > 1) preload_characters = 1;
  }
  return preload_characters;
}
References v8::internal::RegExpMacroAssembler::CanReadUnaligned(), DCHECK_LE, v8::internal::RegExpCompiler::macro_assembler(), and v8::internal::RegExpCompiler::one_byte().
Referenced by SetUpPreLoad().
Emit()
void v8::internal::ChoiceNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Implements v8::internal::RegExpNode.
Reimplemented in v8::internal::LoopChoiceNode.
Definition at line 3207 of file regexp-compiler.cc.
                                                            {
  int choice_count = alternatives_->length();
  if (choice_count == 1 && alternatives_->at(0).guards() == nullptr) {
    alternatives_->at(0).node()->Emit(compiler, trace);
    return;
  }
  AssertGuardsMentionRegisters(trace);
  LimitResult limit_result = LimitVersions(compiler, trace);
  if (limit_result == DONE) return;
  DCHECK(limit_result == CONTINUE);
  // For loop nodes we already flushed (see LoopChoiceNode::Emit), but for
  // other choice nodes we only flush if we are out of code size budget.
  if (trace->flush_budget() == 0 && trace->has_any_actions()) {
    trace->Flush(compiler, this);
    return;
  }
  RecursionCheck rc(compiler);
  PreloadState preload;
  preload.init();
  // This must be outside the 'if' because the trace we use for what
  // comes after the fixed_length_loop is inside it and needs the lifetime.
  FixedLengthLoopState fixed_length_loop_state(not_at_start(), this);
  int text_length = FixedLengthLoopLengthForAlternative(&alternatives_->at(0));
  AlternativeGenerationList alt_gens(choice_count, zone());
  if (choice_count > 1 && text_length != kNodeIsTooComplexForFixedLengthLoops) {
    trace = EmitFixedLengthLoop(compiler, trace, &alt_gens, &preload,
                                &fixed_length_loop_state, text_length);
  } else {
    preload.eats_at_least_ = EmitOptimizedUnanchoredSearch(compiler, trace);
    EmitChoices(compiler, &alt_gens, 0, trace, &preload);
  }
  // At this point we need to generate slow checks for the alternatives where
  // the quick check was inlined. We can recognize these because the associated
  // label was bound.
  int new_flush_budget = trace->flush_budget() / choice_count;
  for (int i = 0; i < choice_count; i++) {
    AlternativeGeneration* alt_gen = alt_gens.at(i);
    Trace new_trace(*trace);
    // If there are actions to be flushed we have to limit how many times
    // they are flushed. Take the budget of the parent trace and distribute
    // it fairly amongst the children.
    if (new_trace.has_any_actions()) {
      new_trace.set_flush_budget(new_flush_budget);
    }
    bool next_expects_preload =
        i == choice_count - 1 ? false : alt_gens.at(i + 1)->expects_preload;
    EmitOutOfLineContinuation(compiler, &new_trace, alternatives_->at(i),
                              alt_gen, preload.preload_characters_,
                              next_expects_preload);
  }
}
References alternatives_, AssertGuardsMentionRegisters(), v8::internal::AlternativeGenerationList::at(), v8::internal::RegExpNode::CONTINUE, v8::internal::DCHECK(), v8::internal::RegExpNode::DONE, v8::internal::PreloadState::eats_at_least_, EmitChoices(), EmitFixedLengthLoop(), EmitOptimizedUnanchoredSearch(), EmitOutOfLineContinuation(), v8::internal::AlternativeGeneration::expects_preload, false, FixedLengthLoopLengthForAlternative(), v8::internal::Trace::Flush(), v8::internal::Trace::flush_budget(), v8::internal::Trace::has_any_actions(), v8::internal::PreloadState::init(), v8::internal::RegExpNode::kNodeIsTooComplexForFixedLengthLoops, v8::internal::RegExpNode::LimitVersions(), not_at_start(), v8::internal::PreloadState::preload_characters_, v8::internal::Trace::set_flush_budget(), and v8::internal::RegExpNode::zone().
Referenced by v8::internal::LoopChoiceNode::Emit().
EmitChoices()
void v8::internal::ChoiceNode::EmitChoices (RegExpCompiler * compiler, AlternativeGenerationList * alt_gens, int first_choice, Trace * trace, PreloadState * preloads) [private]
Definition at line 3356 of file regexp-compiler.cc.
                                                    {
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  SetUpPreLoad(compiler, trace, preload);
  // For now we just call all choices one after the other. The idea ultimately
  // is to use the Dispatch table to try only the relevant ones.
  int choice_count = alternatives_->length();
  int new_flush_budget = trace->flush_budget() / choice_count;
  for (int i = first_choice; i < choice_count; i++) {
    bool is_last = i == choice_count - 1;
    bool fall_through_on_failure = !is_last;
    GuardedAlternative alternative = alternatives_->at(i);
    AlternativeGeneration* alt_gen = alt_gens->at(i);
    alt_gen->quick_check_details.set_characters(preload->preload_characters_);
    ZoneList<Guard*>* guards = alternative.guards();
    int guard_count = (guards == nullptr) ? 0 : guards->length();
    Trace new_trace(*trace);
    new_trace.set_characters_preloaded(
        preload->preload_is_current_ ? preload->preload_characters_ : 0);
    if (preload->preload_has_checked_bounds_) {
      new_trace.set_bound_checked_up_to(preload->preload_characters_);
    }
    new_trace.quick_check_performed()->Clear();
    if (not_at_start_) new_trace.set_at_start(Trace::FALSE_VALUE);
    if (!is_last) {
      new_trace.set_backtrack(&alt_gen->after);
    }
    alt_gen->expects_preload = preload->preload_is_current_;
    bool generate_full_check_inline = false;
    if (v8_flags.regexp_optimization &&
        try_to_emit_quick_check_for_alternative(i == 0) &&
        alternative.node()->EmitQuickCheck(
            compiler, trace, &new_trace, preload->preload_has_checked_bounds_,
            &alt_gen->possible_success, &alt_gen->quick_check_details,
            fall_through_on_failure, this)) {
      // Quick check was generated for this choice.
      preload->preload_is_current_ = true;
      preload->preload_has_checked_bounds_ = true;
      // If we generated the quick check to fall through on possible success,
      // we now need to generate the full check inline.
      if (!fall_through_on_failure) {
        macro_assembler->Bind(&alt_gen->possible_success);
        new_trace.set_quick_check_performed(&alt_gen->quick_check_details);
        new_trace.set_characters_preloaded(preload->preload_characters_);
        new_trace.set_bound_checked_up_to(preload->preload_characters_);
        generate_full_check_inline = true;
      }
    } else if (alt_gen->quick_check_details.cannot_match()) {
      if (!fall_through_on_failure) {
        macro_assembler->GoTo(trace->backtrack());
      }
      continue;
    } else {
      // No quick check was generated. Put the full code here.
      // If this is not the first choice then there could be slow checks from
      // previous cases that go here when they fail. There's no reason to
      // insist that they preload characters since the slow check we are about
      // to generate probably can't use it.
      if (i != first_choice) {
        alt_gen->expects_preload = false;
        new_trace.InvalidateCurrentCharacter();
      }
      generate_full_check_inline = true;
    }
    if (generate_full_check_inline) {
      if (new_trace.has_any_actions()) {
        new_trace.set_flush_budget(new_flush_budget);
      }
      for (int j = 0; j < guard_count; j++) {
        GenerateGuard(macro_assembler, guards->at(j), &new_trace);
      }
      alternative.node()->Emit(compiler, &new_trace);
      preload->preload_is_current_ = false;
    }
    macro_assembler->Bind(&alt_gen->after);
  }
}
References v8::internal::AlternativeGeneration::after, alternatives_, v8::internal::AlternativeGenerationList::at(), v8::internal::ZoneList< T >::at(), v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::QuickCheckDetails::cannot_match(), v8::internal::QuickCheckDetails::Clear(), v8::internal::RegExpNode::Emit(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::AlternativeGeneration::expects_preload, v8::internal::Trace::FALSE_VALUE, v8::internal::Trace::flush_budget(), GenerateGuard(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::GuardedAlternative::guards(), v8::internal::Trace::has_any_actions(), v8::internal::Trace::InvalidateCurrentCharacter(), v8::internal::ZoneList< T >::length(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::GuardedAlternative::node(), not_at_start_, v8::internal::AlternativeGeneration::possible_success, v8::internal::PreloadState::preload_characters_, v8::internal::PreloadState::preload_has_checked_bounds_, v8::internal::PreloadState::preload_is_current_, v8::internal::AlternativeGeneration::quick_check_details, v8::internal::Trace::quick_check_performed(), v8::internal::Trace::set_at_start(), v8::internal::Trace::set_backtrack(), v8::internal::Trace::set_bound_checked_up_to(), v8::internal::QuickCheckDetails::set_characters(), v8::internal::Trace::set_characters_preloaded(), v8::internal::Trace::set_flush_budget(), v8::internal::Trace::set_quick_check_performed(), SetUpPreLoad(), try_to_emit_quick_check_for_alternative(), and v8::internal::v8_flags.
Referenced by Emit(), and EmitFixedLengthLoop().
EmitFixedLengthLoop()
Trace * v8::internal::ChoiceNode::EmitFixedLengthLoop (RegExpCompiler * compiler, Trace * trace, AlternativeGenerationList * alt_gens, PreloadState * preloads, FixedLengthLoopState * fixed_length_loop_state, int text_length) [private]
Definition at line 3269 of file regexp-compiler.cc.
                     {
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  // Here we have special handling for greedy loops containing only text nodes
  // and other simple nodes. We call these fixed length loops. These are
  // handled by pushing the current position on the stack and then incrementing
  // the current position each time around the switch. On backtrack we
  // decrement the current position and check it against the pushed value.
  // This avoids pushing backtrack information for each iteration of the loop,
  // which could take up a lot of space.
  DCHECK(trace->fixed_length_loop_state() == nullptr);
  macro_assembler->PushCurrentPosition();
  // This is the label for trying to match what comes after the greedy
  // quantifier, either because the body of the quantifier failed, or because
  // we have stepped back to try again with one iteration fewer.
  Label after_body_match_attempt;
  Trace fixed_length_match_trace;
  if (not_at_start()) fixed_length_match_trace.set_at_start(Trace::FALSE_VALUE);
  fixed_length_match_trace.set_backtrack(&after_body_match_attempt);
  fixed_length_loop_state->BindLoopTopLabel(macro_assembler);
  fixed_length_match_trace.set_fixed_length_loop_state(fixed_length_loop_state);
  alternatives_->at(0).node()->Emit(compiler, &fixed_length_match_trace);
  macro_assembler->Bind(&after_body_match_attempt);
  Trace* new_trace = fixed_length_loop_state->counter_backtrack_trace();
  // In a fixed length loop there is only one other choice, which is what
  // comes after the greedy quantifer. Try to match that now.
  EmitChoices(compiler, alt_gens, 1, new_trace, preload);
  fixed_length_loop_state->BindStepBackwardsLabel(macro_assembler);
  // If we have unwound to the bottom then backtrack.
  macro_assembler->CheckFixedLengthLoop(trace->backtrack());
  // Otherwise try the second priority at an earlier position.
  macro_assembler->AdvanceCurrentPosition(-text_length);
  macro_assembler->GoTo(&after_body_match_attempt);
  return new_trace;
}
References v8::internal::RegExpMacroAssembler::AdvanceCurrentPosition(), alternatives_, v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::FixedLengthLoopState::BindLoopTopLabel(), v8::internal::FixedLengthLoopState::BindStepBackwardsLabel(), v8::internal::RegExpMacroAssembler::CheckFixedLengthLoop(), v8::internal::FixedLengthLoopState::counter_backtrack_trace(), v8::internal::DCHECK(), EmitChoices(), v8::internal::Trace::FALSE_VALUE, v8::internal::Trace::fixed_length_loop_state(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::RegExpCompiler::macro_assembler(), not_at_start(), v8::internal::RegExpMacroAssembler::PushCurrentPosition(), v8::internal::Trace::set_at_start(), v8::internal::Trace::set_backtrack(), and v8::internal::Trace::set_fixed_length_loop_state().
Referenced by Emit().
EmitOptimizedUnanchoredSearch()
int v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch (RegExpCompiler * compiler, Trace * trace) [private]
Definition at line 3310 of file regexp-compiler.cc.
                                                            {
  int eats_at_least = PreloadState::kEatsAtLeastNotYetInitialized;
  if (alternatives_->length() != 2) return eats_at_least;
  GuardedAlternative alt1 = alternatives_->at(1);
  if (alt1.guards() != nullptr && alt1.guards()->length() != 0) {
    return eats_at_least;
  }
  RegExpNode* eats_anything_node = alt1.node();
  if (eats_anything_node->GetSuccessorOfOmnivorousTextNode(compiler) != this) {
    return eats_at_least;
  }
  // Really we should be creating a new trace when we execute this function,
  // but there is no need, because the code it generates cannot backtrack, and
  // we always arrive here with a trivial trace (since it's the entry to a
  // loop. That also implies that there are no preloaded characters, which is
  // good, because it means we won't be violating any assumptions by
  // overwriting those characters with new load instructions.
  DCHECK(trace->is_trivial());
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  Isolate* isolate = macro_assembler->isolate();
  // At this point we know that we are at a non-greedy loop that will eat
  // any character one at a time. Any non-anchored regexp has such a
  // loop prepended to it in order to find where it starts. We look for
  // a pattern of the form ...abc... where we can look 6 characters ahead
  // and step forwards 3 if the character is not one of abc. Abc need
  // not be atoms, they can be any reasonably limited character class or
  // small alternation.
  BoyerMooreLookahead* bm = bm_info(false);
  if (bm == nullptr) {
    eats_at_least = std::min(kMaxLookaheadForBoyerMoore, EatsAtLeast(false));
    if (eats_at_least >= 1) {
      bm = zone()->New<BoyerMooreLookahead>(eats_at_least, compiler, zone());
      GuardedAlternative alt0 = alternatives_->at(0);
      alt0.node()->FillInBMInfo(isolate, 0, kRecursionBudget, bm, false);
    }
  }
  if (bm != nullptr) {
    bm->EmitSkipInstructions(macro_assembler);
  }
  return eats_at_least;
}
References alternatives_, v8::internal::RegExpNode::bm_info(), v8::internal::DCHECK(), v8::internal::RegExpNode::EatsAtLeast(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::RegExpNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::GuardedAlternative::guards(), v8::internal::Trace::is_trivial(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::PreloadState::kEatsAtLeastNotYetInitialized, v8::internal::regexp_compiler_constants::kMaxLookaheadForBoyerMoore, v8::internal::RegExpNode::kRecursionBudget, v8::internal::RegExpCompiler::macro_assembler(), v8::internal::Zone::New(), v8::internal::GuardedAlternative::node(), and v8::internal::RegExpNode::zone().
Referenced by Emit().
EmitOutOfLineContinuation()
void v8::internal::ChoiceNode::EmitOutOfLineContinuation (RegExpCompiler * compiler, Trace * trace, GuardedAlternative alternative, AlternativeGeneration * alt_gen, int preload_characters, bool next_expects_preload) [private]
Definition at line 3439 of file regexp-compiler.cc.
                                                                      {
  if (!alt_gen->possible_success.is_linked()) return;
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  macro_assembler->Bind(&alt_gen->possible_success);
  Trace out_of_line_trace(*trace);
  out_of_line_trace.set_characters_preloaded(preload_characters);
  out_of_line_trace.set_quick_check_performed(&alt_gen->quick_check_details);
  if (not_at_start_) out_of_line_trace.set_at_start(Trace::FALSE_VALUE);
  ZoneList<Guard*>* guards = alternative.guards();
  int guard_count = (guards == nullptr) ? 0 : guards->length();
  if (next_expects_preload) {
    Label reload_current_char;
    out_of_line_trace.set_backtrack(&reload_current_char);
    for (int j = 0; j < guard_count; j++) {
      GenerateGuard(macro_assembler, guards->at(j), &out_of_line_trace);
    }
    alternative.node()->Emit(compiler, &out_of_line_trace);
    macro_assembler->Bind(&reload_current_char);
    // Reload the current character, since the next quick check expects that.
    // We don't need to check bounds here because we only get into this
    // code through a quick check which already did the checked load.
    macro_assembler->LoadCurrentCharacter(trace->cp_offset(), nullptr, false,
                                          preload_characters);
    macro_assembler->GoTo(&(alt_gen->after));
  } else {
    out_of_line_trace.set_backtrack(&(alt_gen->after));
    for (int j = 0; j < guard_count; j++) {
      GenerateGuard(macro_assembler, guards->at(j), &out_of_line_trace);
    }
    alternative.node()->Emit(compiler, &out_of_line_trace);
  }
}
References v8::internal::AlternativeGeneration::after, v8::internal::ZoneList< T >::at(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::Trace::cp_offset(), v8::internal::RegExpNode::Emit(), v8::internal::Trace::FALSE_VALUE, GenerateGuard(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::GuardedAlternative::guards(), v8::internal::Label::is_linked(), v8::internal::ZoneList< T >::length(), v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::GuardedAlternative::node(), not_at_start_, v8::internal::AlternativeGeneration::possible_success, v8::internal::AlternativeGeneration::quick_check_details, v8::internal::Trace::set_at_start(), v8::internal::Trace::set_backtrack(), v8::internal::Trace::set_characters_preloaded(), and v8::internal::Trace::set_quick_check_performed().
Referenced by Emit().
FillInBMInfo()
void v8::internal::ChoiceNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Reimplemented in v8::internal::LoopChoiceNode, and v8::internal::NegativeLookaroundChoiceNode.
Definition at line 3957 of file regexp-compiler.cc.
                                                                          {
  ZoneList<GuardedAlternative>* alts = alternatives();
  budget = (budget - 1) / alts->length();
  for (int i = 0; i < alts->length(); i++) {
    GuardedAlternative& alt = alts->at(i);
    if (alt.guards() != nullptr && alt.guards()->length() != 0) {
      bm->SetRest(offset); // Give up trying to fill in info.
      SaveBMInfo(bm, not_at_start, offset);
      return;
    }
    alt.node()->FillInBMInfo(isolate, offset, budget, bm, not_at_start);
  }
  SaveBMInfo(bm, not_at_start, offset);
}
References alternatives(), v8::internal::ZoneList< T >::at(), v8::internal::RegExpNode::FillInBMInfo(), v8::internal::GuardedAlternative::guards(), v8::internal::ZoneList< T >::length(), v8::internal::GuardedAlternative::node(), not_at_start(), v8::internal::RegExpNode::SaveBMInfo(), and v8::internal::BoyerMooreLookahead::SetRest().
Referenced by v8::internal::LoopChoiceNode::FillInBMInfo().
FilterOneByte()
RegExpNode * v8::internal::ChoiceNode::FilterOneByte (int depth, RegExpCompiler * compiler) [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Reimplemented in v8::internal::LoopChoiceNode, and v8::internal::NegativeLookaroundChoiceNode.
Definition at line 2019 of file regexp-compiler.cc.
                                                                         {
  if (info()->replacement_calculated) return replacement();
  if (depth < 0) return this;
  if (info()->visited) return this;
  VisitMarker marker(info());
  int choice_count = alternatives_->length();
  for (int i = 0; i < choice_count; i++) {
    GuardedAlternative alternative = alternatives_->at(i);
    if (alternative.guards() != nullptr &&
        alternative.guards()->length() != 0) {
      set_replacement(this);
      return this;
    }
  }
  int surviving = 0;
  RegExpNode* survivor = nullptr;
  for (int i = 0; i < choice_count; i++) {
    GuardedAlternative alternative = alternatives_->at(i);
    RegExpNode* replacement =
        alternative.node()->FilterOneByte(depth - 1, compiler);
    DCHECK(replacement != this); // No missing EMPTY_MATCH_CHECK.
    if (replacement != nullptr) {
      alternatives_->at(i).set_node(replacement);
      surviving++;
      survivor = replacement;
    }
  }
  if (surviving < 2) return set_replacement(survivor);
  set_replacement(this);
  if (surviving == choice_count) {
    return this;
  }
  // Only some of the nodes survived the filtering. We need to rebuild the
  // alternatives list.
  ZoneList<GuardedAlternative>* new_alternatives =
      zone()->New<ZoneList<GuardedAlternative>>(surviving, zone());
  for (int i = 0; i < choice_count; i++) {
    RegExpNode* replacement =
        alternatives_->at(i).node()->FilterOneByte(depth - 1, compiler);
    if (replacement != nullptr) {
      alternatives_->at(i).set_node(replacement);
      new_alternatives->Add(alternatives_->at(i), zone());
    }
  }
  alternatives_ = new_alternatives;
  return this;
}
References v8::internal::ZoneList< T >::Add(), alternatives_, v8::internal::DCHECK(), v8::internal::RegExpNode::FilterOneByte(), v8::internal::GuardedAlternative::guards(), v8::internal::RegExpNode::info(), v8::internal::Zone::New(), v8::internal::GuardedAlternative::node(), v8::internal::RegExpNode::replacement(), v8::internal::RegExpNode::set_replacement(), and v8::internal::RegExpNode::zone().
Referenced by v8::internal::LoopChoiceNode::FilterOneByte().
FixedLengthLoopLengthForAlternative()
int v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative (GuardedAlternative * alternative) [protected]
Definition at line 2667 of file regexp-compiler.cc.
                                     {
  int length = 0;
  RegExpNode* node = alternative->node();
  // Later we will generate code for all these text nodes using recursion
  // so we have to limit the max number.
  int recursion_depth = 0;
  while (node != this) {
    if (recursion_depth++ > RegExpCompiler::kMaxRecursion) {
      return kNodeIsTooComplexForFixedLengthLoops;
    }
    int node_length = node->FixedLengthLoopLength();
    if (node_length == kNodeIsTooComplexForFixedLengthLoops) {
      return kNodeIsTooComplexForFixedLengthLoops;
    }
    length += node_length;
    node = node->AsSeqRegExpNode()->on_success();
  }
  if (read_backward()) {
    length = -length;
  }
  // Check that we can jump by the whole text length. If not, return sentinel
  // to indicate the we can't construct a fixed length loop.
  if (length < RegExpMacroAssembler::kMinCPOffset ||
      length > RegExpMacroAssembler::kMaxCPOffset) {
    return kNodeIsTooComplexForFixedLengthLoops;
  }
  return length;
}
References v8::internal::RegExpNode::AsSeqRegExpNode(), v8::internal::RegExpNode::FixedLengthLoopLength(), v8::internal::RegExpMacroAssembler::kMaxCPOffset, v8::internal::RegExpCompiler::kMaxRecursion, v8::internal::RegExpMacroAssembler::kMinCPOffset, v8::internal::RegExpNode::kNodeIsTooComplexForFixedLengthLoops, v8::internal::length, v8::internal::GuardedAlternative::node(), v8::internal::SeqRegExpNode::on_success(), and read_backward().
Referenced by Emit(), and v8::internal::LoopChoiceNode::Emit().
GenerateGuard()
void v8::internal::ChoiceNode::GenerateGuard (RegExpMacroAssembler * macro_assembler, Guard * guard, Trace * trace) [private]
Definition at line 728 of file regexp-compiler.cc.
                                                           {
  switch (guard->op()) {
    case Guard::LT:
      DCHECK(!trace->mentions_reg(guard->reg()));
      macro_assembler->IfRegisterGE(guard->reg(), guard->value(),
                                    trace->backtrack());
      break;
    case Guard::GEQ:
      DCHECK(!trace->mentions_reg(guard->reg()));
      macro_assembler->IfRegisterLT(guard->reg(), guard->value(),
                                    trace->backtrack());
      break;
  }
}
References v8::internal::Trace::backtrack(), v8::internal::DCHECK(), v8::internal::Guard::GEQ, v8::internal::RegExpMacroAssembler::IfRegisterGE(), v8::internal::RegExpMacroAssembler::IfRegisterLT(), v8::internal::Guard::LT, v8::internal::Trace::mentions_reg(), v8::internal::Guard::op(), v8::internal::Guard::reg(), and v8::internal::Guard::value().
Referenced by EmitChoices(), and EmitOutOfLineContinuation().
GetQuickCheckDetails()
void v8::internal::ChoiceNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [override], [virtual]
Implements v8::internal::RegExpNode.
Reimplemented in v8::internal::LoopChoiceNode, and v8::internal::NegativeLookaroundChoiceNode.
Definition at line 2152 of file regexp-compiler.cc.
                                                         {
  not_at_start = (not_at_start || not_at_start_);
  int choice_count = alternatives_->length();
  DCHECK_LT(0, choice_count);
  alternatives_->at(0).node()->GetQuickCheckDetails(
      details, compiler, characters_filled_in, not_at_start);
  for (int i = 1; i < choice_count; i++) {
    QuickCheckDetails new_details(details->characters());
    RegExpNode* node = alternatives_->at(i).node();
    node->GetQuickCheckDetails(&new_details, compiler, characters_filled_in,
                               not_at_start);
    // Here we merge the quick match details of the two branches.
    details->Merge(&new_details, characters_filled_in);
  }
}
References alternatives_, v8::internal::QuickCheckDetails::characters(), DCHECK_LT, v8::internal::RegExpNode::GetQuickCheckDetails(), v8::internal::QuickCheckDetails::Merge(), not_at_start(), and not_at_start_.
Referenced by v8::internal::LoopChoiceNode::GetQuickCheckDetails().
not_at_start()
bool v8::internal::ChoiceNode::not_at_start () [inline]
Definition at line 679 of file regexp-nodes.h.
{ return not_at_start_; }
References not_at_start_.
Referenced by Emit(), EmitFixedLengthLoop(), FillInBMInfo(), v8::internal::LoopChoiceNode::FillInBMInfo(), GetQuickCheckDetails(), v8::internal::NegativeLookaroundChoiceNode::GetQuickCheckDetails(), v8::internal::LoopChoiceNode::GetQuickCheckDetails(), and v8::internal::LoopChoiceNode::GetQuickCheckDetailsFromLoopEntry().
read_backward()
virtual bool v8::internal::ChoiceNode::read_backward () [inline], [virtual]
Reimplemented in v8::internal::LoopChoiceNode.
Definition at line 686 of file regexp-nodes.h.
{ return false; }
Referenced by FixedLengthLoopLengthForAlternative().
set_being_calculated()
void v8::internal::ChoiceNode::set_being_calculated (bool b) [inline]
Definition at line 681 of file regexp-nodes.h.
{ being_calculated_ = b; }
References being_calculated_.
set_not_at_start()
void v8::internal::ChoiceNode::set_not_at_start () [inline]
Definition at line 680 of file regexp-nodes.h.
{ not_at_start_ = true; }
References not_at_start_.
SetUpPreLoad()
void v8::internal::ChoiceNode::SetUpPreLoad (RegExpCompiler * compiler, Trace * current_trace, PreloadState * preloads) [private]
Definition at line 3192 of file regexp-compiler.cc.
                                                   {
  if (state->eats_at_least_ == PreloadState::kEatsAtLeastNotYetInitialized) {
    // Save some time by looking at most one machine word ahead.
    state->eats_at_least_ =
        EatsAtLeast(current_trace->at_start() == Trace::FALSE_VALUE);
  }
  state->preload_characters_ =
      CalculatePreloadCharacters(compiler, state->eats_at_least_);
  state->preload_is_current_ =
      (current_trace->characters_preloaded() == state->preload_characters_);
  state->preload_has_checked_bounds_ = state->preload_is_current_;
}
References v8::internal::Trace::at_start(), CalculatePreloadCharacters(), v8::internal::Trace::characters_preloaded(), v8::internal::PreloadState::eats_at_least_, v8::internal::RegExpNode::EatsAtLeast(), v8::internal::Trace::FALSE_VALUE, v8::internal::PreloadState::kEatsAtLeastNotYetInitialized, v8::internal::PreloadState::preload_characters_, v8::internal::PreloadState::preload_has_checked_bounds_, and v8::internal::PreloadState::preload_is_current_.
Referenced by EmitChoices().
try_to_emit_quick_check_for_alternative()
virtual bool v8::internal::ChoiceNode::try_to_emit_quick_check_for_alternative (bool is_first) [inline], [virtual]
Reimplemented in v8::internal::NegativeLookaroundChoiceNode.
Definition at line 682 of file regexp-nodes.h.
                                                                      {
    return true;
  }
Referenced by EmitChoices().
Friends And Related Function Documentation
Analysis
template<typename... >
friend class Analysis [friend]
Definition at line 694 of file regexp-nodes.h.
Member Data Documentation
alternatives_
ZoneList<GuardedAlternative>* v8::internal::ChoiceNode::alternatives_ [protected]
Definition at line 690 of file regexp-nodes.h.
Referenced by alternatives(), AssertGuardsMentionRegisters(), v8::internal::LoopChoiceNode::EatsAtLeastFromLoopEntry(), Emit(), v8::internal::LoopChoiceNode::Emit(), EmitChoices(), EmitFixedLengthLoop(), EmitOptimizedUnanchoredSearch(), FilterOneByte(), v8::internal::NegativeLookaroundChoiceNode::FilterOneByte(), GetQuickCheckDetails(), and v8::internal::LoopChoiceNode::GetQuickCheckDetails().
being_calculated_
bool v8::internal::ChoiceNode::being_calculated_ [private]
Definition at line 720 of file regexp-nodes.h.
Referenced by being_calculated(), and set_being_calculated().
not_at_start_
bool v8::internal::ChoiceNode::not_at_start_ [private]
Definition at line 719 of file regexp-nodes.h.
Referenced by EmitChoices(), EmitOutOfLineContinuation(), GetQuickCheckDetails(), not_at_start(), and set_not_at_start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc