v8_inspector::InspectedContext Class Reference
#include <inspected-context.h>
Classes
class ContextCollectedCallbacks
class WeakCallbackData
Public Member Functions
~InspectedContext ()
InspectedContext (const InspectedContext &)=delete
InspectedContext & operator= (const InspectedContext &)=delete
v8::Local< v8::Context > context () const
int contextId () const
int contextGroupId () const
String16 origin () const
String16 humanReadableName () const
internal::V8DebuggerId uniqueId () const
String16 auxData () const
bool isReported (int sessionId) const
void setReported (int sessionId, bool reported)
v8::Isolate * isolate () const
V8InspectorImpl * inspector () const
InjectedScript * getInjectedScript (int sessionId)
InjectedScript * createInjectedScript (int sessionId)
void discardInjectedScript (int sessionId)
bool addInternalObject (v8::Local< v8::Object > object, V8InternalValueType type)
V8InternalValueType getInternalType (v8::Local< v8::Object > object)
Static Public Member Functions
static int contextId (v8::Local< v8::Context >)
Private Member Functions
InspectedContext (V8InspectorImpl *, const V8ContextInfo &, int contextId)
Private Attributes
V8InspectorImpl * m_inspector
v8::Global< v8::Context > m_context
int m_contextId
int m_contextGroupId
const String16 m_origin
const String16 m_humanReadableName
const String16 m_auxData
const internal::V8DebuggerId m_uniqueId
std::unordered_set< int > m_reportedSessionIds
std::unordered_map< int, std::unique_ptr< InjectedScript > > m_injectedScripts
WeakCallbackData * m_weakCallbackData
v8::Global< v8::debug::EphemeronTable > m_internalObjects
Friends
class V8InspectorImpl
Detailed Description
Definition at line 40 of file inspected-context.h.
Constructor & Destructor Documentation
 InspectedContext()
v8_inspector::InspectedContext::~InspectedContext ()
Definition at line 98 of file inspected-context.cc.
                                    {
  // If we destory InspectedContext before weak callback is invoked then we need
  // to delete data here.
  if (!m_context.IsEmpty()) delete m_weakCallbackData;
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), m_context, and m_weakCallbackData.
InspectedContext() [1/2]
v8_inspector::InspectedContext::InspectedContext (const InspectedContext &) [delete]
InspectedContext() [2/2]
v8_inspector::InspectedContext::InspectedContext (V8InspectorImpl * inspector, const V8ContextInfo & info, int contextId) [private]
Definition at line 62 of file inspected-context.cc.
    : m_inspector(inspector),
      m_context(inspector->isolate(), info.context),
      m_contextId(contextId),
      m_contextGroupId(info.contextGroupId),
      m_origin(toString16(info.origin)),
      m_humanReadableName(toString16(info.humanReadableName)),
      m_auxData(toString16(info.auxData)),
      m_uniqueId(internal::V8DebuggerId::generate(inspector)) {
  v8::debug::SetContextId(info.context, contextId);
  m_weakCallbackData =
      new WeakCallbackData(this, m_inspector, m_contextGroupId, m_contextId);
  m_context.SetWeak(m_weakCallbackData,
                    &InspectedContext::WeakCallbackData::resetContext,
                    v8::WeakCallbackType::kParameter);
  v8::Context::Scope contextScope(info.context);
  v8::HandleScope handleScope(inspector->isolate());
  v8::Local<v8::Object> global = info.context->Global();
  v8::Local<v8::Value> console;
  if (!global->Get(info.context, toV8String(inspector->isolate(), "console"))
           .ToLocal(&console) ||
      !console->IsObject()) {
    return;
  }
  m_inspector->console()->installAsyncStackTaggingAPI(info.context,
                                                      console.As<v8::Object>());
  if (info.hasMemoryOnConsole) {
    m_inspector->console()->installMemoryGetter(info.context,
                                                console.As<v8::Object>());
  }
}
References v8::Local< T >::As(), v8_inspector::V8InspectorImpl::console(), v8_inspector::V8ContextInfo::context, contextId(), v8::Object::Get(), v8::Context::Global(), v8_inspector::V8ContextInfo::hasMemoryOnConsole, inspector(), v8_inspector::V8Console::installAsyncStackTaggingAPI(), v8_inspector::V8Console::installMemoryGetter(), v8::Value::IsObject(), v8_inspector::V8InspectorImpl::isolate(), v8::kParameter, m_context, m_contextGroupId, m_contextId, m_inspector, m_weakCallbackData, v8_inspector::InspectedContext::WeakCallbackData::resetContext(), v8::debug::SetContextId(), v8::PersistentBase< T >::SetWeak(), v8::MaybeLocal< T >::ToLocal(), and v8_inspector::toV8String().
Member Function Documentation
addInternalObject()
bool v8_inspector::InspectedContext::addInternalObject (v8::Local< v8::Object > object, V8InternalValueType type)
Definition at line 145 of file inspected-context.cc.
                                                                   {
  if (m_internalObjects.IsEmpty()) {
    m_internalObjects.Reset(isolate(),
                            v8::debug::EphemeronTable::New(isolate()));
  }
  v8::Local<v8::debug::EphemeronTable> new_map =
      m_internalObjects.Get(isolate())->Set(
          isolate(), object,
          v8::Integer::New(isolate(), static_cast<int>(type)));
  m_internalObjects.Reset(isolate(), new_map);
  return true;
}
References v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), isolate(), m_internalObjects, v8::Integer::New(), v8::debug::EphemeronTable::New(), v8::PersistentBase< T >::Reset(), and v8::internal::tracing::type.
Referenced by v8_inspector::V8Debugger::addInternalObject().
auxData()
String16 v8_inspector::InspectedContext::auxData () const [inline]
Definition at line 54 of file inspected-context.h.
{ return m_auxData; }
References m_auxData.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated().
context()
v8::Local< v8::Context > v8_inspector::InspectedContext::context () const
Definition at line 109 of file inspected-context.cc.
                                                   {
  return m_context.Get(isolate());
}
References v8::PersistentBase< T >::Get(), isolate(), and m_context.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::InjectedScript::addPromiseCallback(), v8_inspector::InjectedScript::commandLineAPI(), v8_inspector::V8InspectorImpl::contextById(), contextId(), v8_inspector::V8DebuggerAgentImpl::continueToLocation(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::InjectedScript::getInternalAndPrivateProperties(), v8_inspector::V8DebuggerAgentImpl::getPossibleBreakpoints(), v8_inspector::InjectedScript::getProperties(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::resolveCallArgument(), v8_inspector::V8DebuggerAgentImpl::setBreakpointImpl(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), v8_inspector::V8InspectorSessionImpl::unwrapObject(), v8_inspector::V8ConsoleMessage::wrapArguments(), v8_inspector::InjectedScript::wrapEvaluateResult(), v8_inspector::V8ConsoleMessage::wrapException(), v8_inspector::InjectedScript::wrapObject(), v8_inspector::InjectedScript::wrapObjectMirror(), and v8_inspector::InjectedScript::wrapTable().
contextGroupId()
int v8_inspector::InspectedContext::contextGroupId () const [inline]
Definition at line 50 of file inspected-context.h.
{ return m_contextGroupId; }
References m_contextGroupId.
Referenced by v8_inspector::V8InspectorImpl::uniqueDebuggerId().
contextId() [1/2]
int v8_inspector::InspectedContext::contextId () const [inline]
Definition at line 49 of file inspected-context.h.
{ return m_contextId; }
References m_contextId.
Referenced by v8_inspector::V8Debugger::addInternalObject(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::InjectedScript::bindRemoteObjectIfNeeded(), v8_inspector::V8InspectorImpl::contextDestroyed(), v8_inspector::V8InspectorImpl::contextGroupId(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::contextId(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8InspectorImpl::exceptionThrown(), v8_inspector::V8ContextInfo::executionContextId(), v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), InspectedContext(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom(), v8_inspector::V8InspectorSessionImpl::wrapObject(), and v8_inspector::V8InspectorSessionImpl::wrapTable().
contextId() [2/2]
int v8_inspector::InspectedContext::contextId (v8::Local< v8::Context > context) [static]
Definition at line 105 of file inspected-context.cc.
                                                          {
  return v8::debug::GetContextId(context);
}
References context(), and v8::debug::GetContextId().
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::InjectedScript::addPromiseCallback(), v8_inspector::InjectedScript::bindObject(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed(), and v8_inspector::InjectedScript::resolveCallArgument().
createInjectedScript()
InjectedScript * v8_inspector::InspectedContext::createInjectedScript (int sessionId)
Definition at line 133 of file inspected-context.cc.
                                                                    {
  std::unique_ptr<InjectedScript> injectedScript =
      std::make_unique<InjectedScript>(this, sessionId);
  CHECK(m_injectedScripts.find(sessionId) == m_injectedScripts.end());
  m_injectedScripts[sessionId] = std::move(injectedScript);
  return getInjectedScript(sessionId);
}
References CHECK, getInjectedScript(), and m_injectedScripts.
Referenced by v8_inspector::V8InspectorSessionImpl::findInjectedScript().
discardInjectedScript()
void v8_inspector::InspectedContext::discardInjectedScript (int sessionId)
Definition at line 141 of file inspected-context.cc.
                                                          {
  m_injectedScripts.erase(sessionId);
}
References m_injectedScripts.
Referenced by v8_inspector::V8InspectorSessionImpl::discardInjectedScripts().
getInjectedScript()
InjectedScript * v8_inspector::InspectedContext::getInjectedScript (int sessionId)
Definition at line 128 of file inspected-context.cc.
                                                                 {
  auto it = m_injectedScripts.find(sessionId);
  return it == m_injectedScripts.end() ? nullptr : it->second.get();
}
References m_injectedScripts, and nullptr.
Referenced by v8_inspector::InjectedScript::bindRemoteObjectIfNeeded(), createInjectedScript(), v8_inspector::V8InspectorSessionImpl::findInjectedScript(), v8_inspector::anonymous_namespace{custom-preview.cc}::getInjectedScript(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::injectedScript(), v8_inspector::V8InspectorSessionImpl::releaseObjectGroup(), and v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled().
getInternalType()
V8InternalValueType v8_inspector::InspectedContext::getInternalType (v8::Local< v8::Object > object)
Definition at line 159 of file inspected-context.cc.
                              {
  if (m_internalObjects.IsEmpty()) return V8InternalValueType::kNone;
  v8::Local<v8::Value> typeValue;
  if (!m_internalObjects.Get(isolate())
           ->Get(isolate(), object)
           .ToLocal(&typeValue) ||
      !typeValue->IsUint32()) {
    return V8InternalValueType::kNone;
  }
  return static_cast<V8InternalValueType>(typeValue.As<v8::Int32>()->Value());
}
References v8::Local< T >::As(), v8::internal::compiler::turboshaft::Get(), v8::PersistentBase< T >::Get(), v8::api_internal::IndirectHandleBase::IsEmpty(), isolate(), v8::Value::IsUint32(), v8_inspector::kNone, and m_internalObjects.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::v8InternalValueTypeFrom().
humanReadableName()
String16 v8_inspector::InspectedContext::humanReadableName () const [inline]
Definition at line 52 of file inspected-context.h.
{ return m_humanReadableName; }
References m_humanReadableName.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBindings(), and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated().
inspector()
V8InspectorImpl* v8_inspector::InspectedContext::inspector () const [inline]
Definition at line 60 of file inspected-context.h.
{ return m_inspector; }
References m_inspector.
Referenced by v8_inspector::InjectedScript::bindObject(), v8_inspector::InjectedScript::commandLineAPI(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), InspectedContext(), v8_inspector::InjectedScript::resolveCallArgument(), and v8_inspector::InjectedScript::wrapEvaluateResult().
isolate()
v8::Isolate * v8_inspector::InspectedContext::isolate () const
Definition at line 113 of file inspected-context.cc.
                                           {
  return m_inspector->isolate();
}
References v8_inspector::V8InspectorImpl::isolate(), and m_inspector.
Referenced by addInternalObject(), v8_inspector::InjectedScript::bindObject(), v8_inspector::InjectedScript::commandLineAPI(), context(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::InjectedScript::findObject(), getInternalType(), v8_inspector::InjectedScript::getProperties(), v8_inspector::InjectedScript::lastEvaluationResult(), v8_inspector::InjectedScript::resolveCallArgument(), v8_inspector::InjectedScript::setLastEvaluationResult(), v8_inspector::V8ConsoleMessage::wrapArguments(), v8_inspector::InjectedScript::wrapEvaluateResult(), v8_inspector::V8ConsoleMessage::wrapException(), v8_inspector::InjectedScript::wrapObjectMirror(), and v8_inspector::InjectedScript::wrapTable().
isReported()
bool v8_inspector::InspectedContext::isReported (int sessionId) const
Definition at line 117 of file inspected-context.cc.
                                                     {
  return m_reportedSessionIds.find(sessionId) != m_reportedSessionIds.cend();
}
References m_reportedSessionIds.
Referenced by v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed().
operator=()
InspectedContext& v8_inspector::InspectedContext::operator= (const InspectedContext &) [delete]
origin()
String16 v8_inspector::InspectedContext::origin () const [inline]
Definition at line 51 of file inspected-context.h.
{ return m_origin; }
References m_origin.
Referenced by v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated().
setReported()
void v8_inspector::InspectedContext::setReported (int sessionId, bool reported)
Definition at line 121 of file inspected-context.cc.
                                                               {
  if (reported)
    m_reportedSessionIds.insert(sessionId);
  else
    m_reportedSessionIds.erase(sessionId);
}
References m_reportedSessionIds.
Referenced by v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed().
uniqueId()
internal::V8DebuggerId v8_inspector::InspectedContext::uniqueId () const [inline]
Definition at line 53 of file inspected-context.h.
{ return m_uniqueId; }
References m_uniqueId.
Referenced by v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed().
Friends And Related Function Documentation
V8InspectorImpl
friend class V8InspectorImpl [friend]
Definition at line 71 of file inspected-context.h.
Member Data Documentation
m_auxData
const String16 v8_inspector::InspectedContext::m_auxData [private]
Definition at line 83 of file inspected-context.h.
Referenced by auxData().
m_context
v8::Global<v8::Context> v8_inspector::InspectedContext::m_context [private]
Definition at line 78 of file inspected-context.h.
Referenced by context(), InspectedContext(), and ~InspectedContext().
m_contextGroupId
int v8_inspector::InspectedContext::m_contextGroupId [private]
Definition at line 80 of file inspected-context.h.
Referenced by contextGroupId(), and InspectedContext().
m_contextId
int v8_inspector::InspectedContext::m_contextId [private]
Definition at line 79 of file inspected-context.h.
Referenced by contextId(), and InspectedContext().
m_humanReadableName
const String16 v8_inspector::InspectedContext::m_humanReadableName [private]
Definition at line 82 of file inspected-context.h.
Referenced by humanReadableName().
m_injectedScripts
std::unordered_map<int, std::unique_ptr<InjectedScript> > v8_inspector::InspectedContext::m_injectedScripts [private]
Definition at line 86 of file inspected-context.h.
Referenced by createInjectedScript(), discardInjectedScript(), and getInjectedScript().
m_inspector
V8InspectorImpl* v8_inspector::InspectedContext::m_inspector [private]
Definition at line 77 of file inspected-context.h.
Referenced by InspectedContext(), inspector(), and isolate().
m_internalObjects
v8::Global<v8::debug::EphemeronTable> v8_inspector::InspectedContext::m_internalObjects [private]
Definition at line 88 of file inspected-context.h.
Referenced by addInternalObject(), and getInternalType().
m_origin
const String16 v8_inspector::InspectedContext::m_origin [private]
Definition at line 81 of file inspected-context.h.
Referenced by origin().
m_reportedSessionIds
std::unordered_set<int> v8_inspector::InspectedContext::m_reportedSessionIds [private]
Definition at line 85 of file inspected-context.h.
Referenced by isReported(), and setReported().
m_uniqueId
const internal::V8DebuggerId v8_inspector::InspectedContext::m_uniqueId [private]
Definition at line 84 of file inspected-context.h.
Referenced by uniqueId().
m_weakCallbackData
WeakCallbackData* v8_inspector::InspectedContext::m_weakCallbackData [private]
Definition at line 87 of file inspected-context.h.
Referenced by InspectedContext(), and ~InspectedContext().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/inspected-context.h
/mnt/V8SourceCode/src/inspector/inspected-context.cc