v8::internal::MeasureMemoryDelegate Class Reference
Public Member Functions
MeasureMemoryDelegate (v8::Isolate *isolate, v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > promise, v8::MeasureMemoryMode mode)
~MeasureMemoryDelegate () override=default
bool ShouldMeasure (v8::Local< v8::Context > context) override
Returns true if the size of the given context needs to be measured.
void MeasurementComplete (Result result) override
This function is called when memory measurement finishes.
Private Attributes
v8::Isolate * isolate_
const v8::Global< v8::Context > context_
const v8::Global< v8::Promise::Resolver > promise_
const v8::MeasureMemoryMode mode_
Additional Inherited Members
Detailed Description
Definition at line 110 of file memory-measurement.cc.
Constructor & Destructor Documentation
MeasureMemoryDelegate()
v8::internal::MeasureMemoryDelegate::MeasureMemoryDelegate (v8::Isolate * isolate, v8::Local< v8::Context > context, v8::Local< v8::Promise::Resolver > promise, v8::MeasureMemoryMode mode)
Definition at line 129 of file memory-measurement.cc.
    : isolate_(isolate),
      context_(isolate_, context),
      promise_(isolate_, promise),
      mode_(mode) {}
 MeasureMemoryDelegate()
v8::internal::MeasureMemoryDelegate::~MeasureMemoryDelegate () [override], [virtual], [default]
Reimplemented from v8::MeasureMemoryDelegate.
Member Function Documentation
MeasurementComplete()
void v8::internal::MeasureMemoryDelegate::MeasurementComplete (Result result) [override], [virtual]
This function is called when memory measurement finishes.
Parameters
result the result of the measurement.
Reimplemented from v8::MeasureMemoryDelegate.
Definition at line 143 of file memory-measurement.cc.
                                                             {
  size_t shared_size = result.unattributed_size_in_bytes;
  size_t wasm_code = result.wasm_code_size_in_bytes;
  size_t wasm_metadata = result.wasm_metadata_size_in_bytes;
  v8::Local<v8::Context> v8_context = context_.Get(isolate_);
  v8::Context::Scope scope(v8_context);
  size_t total_size = 0;
  size_t current_size = 0;
  DCHECK_EQ(result.contexts.size(), result.sizes_in_bytes.size());
  for (size_t i = 0; i < result.contexts.size(); ++i) {
    total_size += result.sizes_in_bytes[i];
    if (context_ == result.contexts[i]) {
      current_size = result.sizes_in_bytes[i];
    }
  }
  MemoryMeasurementResultBuilder result_builder(isolate_);
  result_builder.AddTotal(total_size, total_size, total_size + shared_size);
  if (wasm_code > 0 || wasm_metadata > 0) {
    result_builder.AddWasm(wasm_code, wasm_metadata);
  }
  if (mode_ == v8::MeasureMemoryMode::kDetailed) {
    result_builder.AddCurrent(current_size, current_size,
                              current_size + shared_size);
    for (size_t i = 0; i < result.contexts.size(); ++i) {
      if (context_ != result.contexts[i]) {
        size_t other_size = result.sizes_in_bytes[i];
        result_builder.AddOther(other_size, other_size,
                                other_size + shared_size);
      }
    }
  }
  auto v8_result = ToApiHandle<v8::Object>(result_builder.Build());
  auto v8_promise = promise_.Get(isolate_);
  if (v8_promise->Resolve(v8_context, v8_result).IsNothing()) {
    CHECK(reinterpret_cast<Isolate*>(isolate_)->is_execution_terminating());
  }
}
References CHECK, context_, DCHECK_EQ, v8::PersistentBase< T >::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::kDetailed, mode_, promise_, and v8::base::internal::result.
ShouldMeasure()
bool v8::internal::MeasureMemoryDelegate::ShouldMeasure (v8::Local< v8::Context > context) [override], [virtual]
Returns true if the size of the given context needs to be measured.
Implements v8::MeasureMemoryDelegate.
Definition at line 137 of file memory-measurement.cc.
                                      {
  return context_.Get(isolate_)->GetSecurityToken() ==
         other_context->GetSecurityToken();
}
References context_, v8::PersistentBase< T >::Get(), v8::Context::GetSecurityToken(), and isolate_.
Member Data Documentation
context_
const v8::Global<v8::Context> v8::internal::MeasureMemoryDelegate::context_ [private]
Definition at line 124 of file memory-measurement.cc.
Referenced by MeasurementComplete(), and ShouldMeasure().
isolate_
v8::Isolate* v8::internal::MeasureMemoryDelegate::isolate_ [private]
Definition at line 123 of file memory-measurement.cc.
Referenced by MeasurementComplete(), and ShouldMeasure().
mode_
const v8::MeasureMemoryMode v8::internal::MeasureMemoryDelegate::mode_ [private]
Definition at line 126 of file memory-measurement.cc.
Referenced by MeasurementComplete().
promise_
const v8::Global<v8::Promise::Resolver> v8::internal::MeasureMemoryDelegate::promise_ [private]
Definition at line 125 of file memory-measurement.cc.
Referenced by MeasurementComplete().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/memory-measurement.cc