v8::internal::Runtime Class Reference
#include <runtime.h>
Classes
struct Function
Public Types
enum FunctionId : int32_t { FOR_EACH_INTRINSIC
 }
enum IntrinsicType { RUNTIME
, INLINE
 }
Static Public Member Functions
static bool NeedsExactContext (FunctionId id)
static bool IsNonReturning (FunctionId id)
static bool MayAllocate (FunctionId id)
static bool IsEnabledForFuzzing (FunctionId id)
static const Function * FunctionForName (const unsigned char *name, int length)
static V8_EXPORT_PRIVATE const Function * FunctionForId (FunctionId id)
static const Function * FunctionForEntry (Address ref)
static const Function * RuntimeFunctionTable (Isolate *isolate)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > DeleteObjectProperty (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Object > key, LanguageMode language_mode)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetObjectProperty (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, DirectHandle< Object > value, MaybeDirectHandle< JSAny > receiver, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >())
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetObjectProperty (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, DirectHandle< Object > value, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw=Nothing< ShouldThrow >())
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > DefineObjectOwnProperty (Isolate *isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, DirectHandle< Object > value, StoreOrigin store_origin)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetObjectProperty (Isolate *isolate, DirectHandle< JSAny > lookup_start_object, DirectHandle< Object > key, DirectHandle< JSAny > receiver={}, bool *is_found=nullptr)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetPrivateMember (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetPrivateMember (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc, DirectHandle< Object > value)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > HasProperty (Isolate *isolate, DirectHandle< Object > object, DirectHandle< Object > key)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< JSArray > GetInternalProperties (Isolate *isolate, DirectHandle< Object >)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > ThrowIteratorError (Isolate *isolate, DirectHandle< Object > object)
Static Public Attributes
static constexpr int kNumInlineFunctions
static const int kNotFound = -1
static constexpr bool kCanTriggerGC []
Detailed Description
Definition at line 913 of file runtime.h.
Member Enumeration Documentation
FunctionId
enum v8::internal::Runtime::FunctionId : int32_t
Enumerator
FOR_EACH_INTRINSIC
Definition at line 915 of file runtime.h.
                  : int32_t {
#define F(name, nargs, ressize, ...) k##name,
#define I(name, nargs, ressize, ...) kInline##name,
    FOR_EACH_INTRINSIC(F) FOR_EACH_INLINE_INTRINSIC(I)
#undef I
#undef F
        kNumFunctions,
  };
IntrinsicType
enum v8::internal::Runtime::IntrinsicType
Enumerator
RUNTIME
INLINE
Definition at line 929 of file runtime.h.
{ RUNTIME, INLINE };
Member Function Documentation
DefineObjectOwnProperty()
MaybeDirectHandle< Object > v8::internal::Runtime::DefineObjectOwnProperty (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, DirectHandle< Object > value, StoreOrigin store_origin) [static]
Definition at line 431 of file runtime-object.cc.
                                                          {
  if (IsNullOrUndefined(*object, isolate)) {
    MaybeDirectHandle<String> maybe_property =
        Object::NoSideEffectsToMaybeString(isolate, key);
    DirectHandle<String> property_name;
    if (maybe_property.ToHandle(&property_name)) {
      THROW_NEW_ERROR(
          isolate,
          NewTypeError(MessageTemplate::kNonObjectPropertyStoreWithProperty,
                       object, property_name));
    } else {
      THROW_NEW_ERROR(
          isolate,
          NewTypeError(MessageTemplate::kNonObjectPropertyStore, object));
    }
  }
  // Check if the given key is an array index.
  bool success = false;
  PropertyKey lookup_key(isolate, key, &success);
  if (!success) return MaybeDirectHandle<Object>();
  if (IsSymbol(*key) && Cast<Symbol>(*key)->is_private_name()) {
    LookupIterator it(isolate, object, lookup_key, LookupIterator::OWN);
    Maybe<bool> can_store = JSReceiver::CheckPrivateNameStore(&it, true);
    MAYBE_RETURN_NULL(can_store);
    // If the state is ACCESS_CHECK, the faliled access check callback
    // is configured but it did't throw.
    DCHECK_IMPLIES(it.IsFound(), it.state() == LookupIterator::ACCESS_CHECK &&
                                     !can_store.FromJust());
    if (!can_store.FromJust()) {
      return isolate->factory()->undefined_value();
    }
    MAYBE_RETURN_NULL(
        JSReceiver::AddPrivateField(&it, value, Nothing<ShouldThrow>()));
  } else {
    MAYBE_RETURN_NULL(JSReceiver::CreateDataProperty(
        isolate, object, lookup_key, value, Nothing<ShouldThrow>()));
  }
  return value;
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::JSReceiver::CreateDataProperty(), DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::IsFound(), v8::internal::IsNullOrUndefined(), v8::internal::key, MAYBE_RETURN_NULL, v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::LookupIterator::OWN, v8::internal::LookupIterator::state(), THROW_NEW_ERROR, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::KeyedStoreIC::Store().
DeleteObjectProperty()
Maybe< bool > v8::internal::Runtime::DeleteObjectProperty (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Object > key, LanguageMode language_mode) [static]
Definition at line 75 of file runtime-object.cc.
                                                                      {
  bool success = false;
  PropertyKey lookup_key(isolate, key, &success);
  if (!success) return Nothing<bool>();
  LookupIterator it(isolate, receiver, lookup_key, LookupIterator::OWN);
  return JSReceiver::DeleteProperty(&it, language_mode);
}
References v8::internal::JSReceiver::DeleteProperty(), v8::internal::key, and v8::internal::LookupIterator::OWN.
Referenced by v8::Object::Delete(), v8::Object::DeletePrivate(), and v8::internal::anonymous_namespace{runtime-object.cc}::DeleteProperty().
FunctionForEntry()
const Runtime::Function * v8::internal::Runtime::FunctionForEntry (Address ref) [static]
Definition at line 339 of file runtime.cc.
                                                              {
  for (size_t i = 0; i < arraysize(kIntrinsicFunctions); ++i) {
    if (entry == kIntrinsicFunctions[i].entry) {
      return &(kIntrinsicFunctions[i]);
    }
  }
  return nullptr;
}
References arraysize, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::kIntrinsicFunctions.
Referenced by v8::internal::operator<<().
FunctionForId()
const Runtime::Function * v8::internal::Runtime::FunctionForId (Runtime::FunctionId id) [static]
Definition at line 349 of file runtime.cc.
                                                                  {
  return &(kIntrinsicFunctions[static_cast<int>(id)]);
}
References v8::internal::kIntrinsicFunctions.
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext(), v8::internal::MacroAssembler::CallRuntime(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::compiler::JSOperatorBuilder::CallRuntime(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntimeForPair(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntimeImpl(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), v8::internal::ExternalReference::Create(), v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), v8::internal::DebugEvaluate::IsSideEffectFreeIntrinsic(), v8::internal::interpreter::anonymous_namespace{bytecode-decoder.cc}::NameForRuntimeId(), v8::internal::AstNodeFactory::NewCallRuntime(), v8::internal::operator<<(), v8::internal::maglev::CallRuntime::PrintParams(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException(), v8::internal::compiler::JSIntrinsicLowering::Reduce(), v8::internal::MacroAssembler::TailCallRuntime(), and v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl().
FunctionForName()
const Runtime::Function * v8::internal::Runtime::FunctionForName (const unsigned char * name, int length) [static]
Definition at line 325 of file runtime.cc.
                                                              {
  base::CallOnce(&initialize_function_name_map_once,
                 &InitializeIntrinsicFunctionNames);
  IntrinsicFunctionIdentifier identifier(name, length);
  base::HashMap::Entry* entry =
      kRuntimeFunctionNameMap->Lookup(&identifier, identifier.Hash());
  if (entry) {
    return reinterpret_cast<Function*>(entry->value);
  }
  return nullptr;
}
References v8::base::CallOnce(), v8::internal::anonymous_namespace{runtime.cc}::InitializeIntrinsicFunctionNames(), v8::internal::anonymous_namespace{runtime.cc}::kRuntimeFunctionNameMap, v8::internal::length, and v8::internal::name.
Referenced by v8::internal::Parser::NewV8Intrinsic().
GetInternalProperties()
MaybeHandle< JSArray > v8::internal::Runtime::GetInternalProperties (Isolate * isolate, DirectHandle< Object > object) [static]
Definition at line 201 of file runtime-debug.cc.
                                                   {
  DirectHandle<ArrayList> result = ArrayList::New(isolate, 8 * 2);
  if (IsJSObject(*object)) {
    PrototypeIterator iter(isolate, Cast<JSObject>(object), kStartAtReceiver);
    if (iter.HasAccess()) {
      iter.Advance();
      DirectHandle<Object> prototype = PrototypeIterator::GetCurrent(iter);
      if (!iter.IsAtEnd() && iter.HasAccess() && IsJSGlobalProxy(*object)) {
        // Skip JSGlobalObject as the [[Prototype]].
        DCHECK(IsJSGlobalObject(*prototype));
        iter.Advance();
        prototype = PrototypeIterator::GetCurrent(iter);
      }
      if (!IsNull(*prototype, isolate)) {
        result = ArrayList::Add(
            isolate, result,
            isolate->factory()->NewStringFromStaticChars("[[Prototype]]"),
            prototype);
      }
    }
  }
  if (IsJSBoundFunction(*object)) {
    auto function = Cast<JSBoundFunction>(object);
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[TargetFunction]]"),
        direct_handle(function->bound_target_function(), isolate));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[BoundThis]]"),
        direct_handle(function->bound_this(), isolate));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[BoundArgs]]"),
        isolate->factory()->NewJSArrayWithElements(
            isolate->factory()->CopyFixedArray(
                handle(function->bound_arguments(), isolate))));
  } else if (IsJSMapIterator(*object)) {
    DirectHandle<JSMapIterator> iterator = Cast<JSMapIterator>(object);
    result = AddIteratorInternalProperties(isolate, result, iterator);
  } else if (IsJSSetIterator(*object)) {
    DirectHandle<JSSetIterator> iterator = Cast<JSSetIterator>(object);
    result = AddIteratorInternalProperties(isolate, result, iterator);
  } else if (IsJSGeneratorObject(*object)) {
    auto generator = Cast<JSGeneratorObject>(object);
    const char* status = "suspended";
    if (generator->is_closed()) {
      status = "closed";
    } else if (generator->is_executing()) {
      status = "running";
    } else {
      DCHECK(generator->is_suspended());
    }
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[GeneratorState]]"),
        isolate->factory()->NewStringFromAsciiChecked(status));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[GeneratorFunction]]"),
        direct_handle(generator->function(), isolate));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[GeneratorReceiver]]"),
        direct_handle(generator->receiver(), isolate));
  } else if (IsJSPromise(*object)) {
    auto promise = Cast<JSPromise>(object);
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[PromiseState]]"),
        isolate->factory()->NewStringFromAsciiChecked(
            JSPromise::Status(promise->status())));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[PromiseResult]]"),
        promise->status() == Promise::kPending
            ? isolate->factory()->undefined_value()
            : direct_handle(promise->result(), isolate));
  } else if (IsJSProxy(*object)) {
    auto js_proxy = Cast<JSProxy>(object);
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[Handler]]"),
        direct_handle(js_proxy->handler(), isolate));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[Target]]"),
        direct_handle(js_proxy->target(), isolate));
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[IsRevoked]]"),
        isolate->factory()->ToBoolean(js_proxy->IsRevoked()));
  } else if (IsJSPrimitiveWrapper(*object)) {
    auto js_value = Cast<JSPrimitiveWrapper>(object);
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[PrimitiveValue]]"),
        direct_handle(js_value->value(), isolate));
  } else if (IsJSWeakRef(*object)) {
    auto js_weak_ref = Cast<JSWeakRef>(object);
    result = ArrayList::Add(
        isolate, result,
        isolate->factory()->NewStringFromAsciiChecked("[[WeakRefTarget]]"),
        direct_handle(js_weak_ref->target(), isolate));
  } else if (IsJSArrayBuffer(*object)) {
    DirectHandle<JSArrayBuffer> js_array_buffer = Cast<JSArrayBuffer>(object);
    if (js_array_buffer->was_detached()) {
      // Mark a detached JSArrayBuffer and such and don't even try to
      // create views for it, since the TypedArray constructors will
      // throw a TypeError when the underlying buffer is detached.
      result = ArrayList::Add(
          isolate, result,
          isolate->factory()->NewStringFromAsciiChecked("[[IsDetached]]"),
          isolate->factory()->true_value());
    } else {
      const size_t byte_length = js_array_buffer->byte_length();
      static_assert(JSTypedArray::kMaxByteLength ==
                    JSArrayBuffer::kMaxByteLength);
      using DataView = std::tuple<const char*, ExternalArrayType, size_t>;
      for (auto [name, type, elem_size] :
           {DataView{"[[Int8Array]]", kExternalInt8Array, 1},
            DataView{"[[Uint8Array]]", kExternalUint8Array, 1},
            DataView{"[[Int16Array]]", kExternalInt16Array, 2},
            DataView{"[[Int32Array]]", kExternalInt32Array, 4}}) {
        if ((byte_length % elem_size) != 0) continue;
        size_t length = byte_length / elem_size;
        result =
            ArrayList::Add(isolate, result,
                           isolate->factory()->NewStringFromAsciiChecked(name),
                           isolate->factory()->NewJSTypedArray(
                               type, js_array_buffer, 0, length));
      }
      result =
          ArrayList::Add(isolate, result,
                         isolate->factory()->NewStringFromAsciiChecked(
                             "[[ArrayBufferByteLength]]"),
                         isolate->factory()->NewNumberFromSize(byte_length));
      auto backing_store = js_array_buffer->GetBackingStore();
      DirectHandle<Object> array_buffer_data;
      if (backing_store) {
        array_buffer_data =
            isolate->factory()->NewNumberFromUint(backing_store->id());
      } else {
        array_buffer_data = isolate->factory()->null_value();
      }
      result = ArrayList::Add(
          isolate, result,
          isolate->factory()->NewStringFromAsciiChecked("[[ArrayBufferData]]"),
          array_buffer_data);
      DirectHandle<Symbol> memory_symbol =
          isolate->factory()->array_buffer_wasm_memory_symbol();
      DirectHandle<Object> memory_object =
          JSObject::GetDataProperty(isolate, js_array_buffer, memory_symbol);
      if (!IsUndefined(*memory_object, isolate)) {
        result = ArrayList::Add(isolate, result,
                                isolate->factory()->NewStringFromAsciiChecked(
                                    "[[WebAssemblyMemory]]"),
                                memory_object);
      }
    }
#if V8_ENABLE_WEBASSEMBLY
  } else if (IsWasmInstanceObject(*object)) {
    result = AddWasmInstanceObjectInternalProperties(
        isolate, result, Cast<WasmInstanceObject>(object));
  } else if (IsWasmModuleObject(*object)) {
    result = AddWasmModuleObjectInternalProperties(
        isolate, result, Cast<WasmModuleObject>(object));
  } else if (IsWasmTableObject(*object)) {
    result = AddWasmTableObjectInternalProperties(
        isolate, result, Cast<WasmTableObject>(object));
#endif // V8_ENABLE_WEBASSEMBLY
  }
  return isolate->factory()->NewJSArrayWithElements(
      ArrayList::ToFixedArray(isolate, result), PACKED_ELEMENTS);
}
References v8::internal::ArrayList::Add(), v8::internal::anonymous_namespace{runtime-debug.cc}::AddIteratorInternalProperties(), v8::internal::AddWasmInstanceObjectInternalProperties(), v8::internal::AddWasmModuleObjectInternalProperties(), v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::PrototypeIterator::Advance(), v8::internal::Factory::CopyFixedArray(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::handle(), v8::internal::PrototypeIterator::HasAccess(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsNull(), v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, v8::internal::kExternalUint8Array, v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::JSTypedArray::kMaxByteLength, v8::Promise::kPending, v8::internal::kStartAtReceiver, v8::internal::length, v8::internal::name, v8::internal::ArrayList::New(), v8::internal::Factory::NewJSArrayWithElements(), v8::internal::Factory::NewJSTypedArray(), v8::internal::FactoryBase< Impl >::NewNumberFromSize(), v8::internal::FactoryBase< Impl >::NewNumberFromUint(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::Factory::NewStringFromStaticChars(), v8::internal::PACKED_ELEMENTS, v8::internal::prototype, v8::base::internal::result, v8::internal::status, v8::internal::JSPromise::Status(), v8::internal::FactoryBase< Impl >::ToBoolean(), v8::internal::ArrayList::ToFixedArray(), and v8::internal::tracing::type.
Referenced by v8::debug::GetInternalProperties().
GetObjectProperty()
MaybeDirectHandle< Object > v8::internal::Runtime::GetObjectProperty (Isolate * isolate, DirectHandle< JSAny > lookup_start_object, DirectHandle< Object > key, DirectHandle< JSAny > receiver = {}, bool * is_found = nullptr) [static]
Definition at line 25 of file runtime-object.cc.
                                                                            {
  if (receiver.is_null()) {
    receiver = lookup_start_object;
  }
  if (IsNullOrUndefined(*lookup_start_object, isolate)) {
    ErrorUtils::ThrowLoadFromNullOrUndefined(isolate, lookup_start_object, key);
    return MaybeDirectHandle<Object>();
  }
  bool success = false;
  PropertyKey lookup_key(isolate, key, &success);
  if (!success) return MaybeDirectHandle<Object>();
  LookupIterator it =
      LookupIterator(isolate, receiver, lookup_key, lookup_start_object);
  MaybeDirectHandle<Object> result = Object::GetProperty(&it);
  if (result.is_null()) {
    return result;
  }
  if (is_found) {
    *is_found = it.state() != LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND &&
                it.state() != LookupIterator::NOT_FOUND;
  }
  return result;
}
References v8::internal::Object::GetProperty(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IsNullOrUndefined(), v8::internal::key, v8::internal::LookupIterator::NOT_FOUND, v8::base::internal::result, v8::internal::LookupIterator::state(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::DefineClass(), v8::Object::Get(), v8::internal::anonymous_namespace{builtins-array.cc}::IsConcatSpreadable(), v8::internal::RUNTIME_FUNCTION(), v8::internal::KeyedLoadIC::RuntimeLoad(), and v8::internal::JSReceiver::SetOrCopyDataProperties().
GetPrivateMember()
MaybeDirectHandle< Object > v8::internal::Runtime::GetPrivateMember (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc) [static]
Definition at line 1485 of file runtime-object.cc.
                               {
  PrivateMember result;
  MAYBE_RETURN_NULL(FindPrivateMembersFromReceiver(
      isolate, receiver, desc, MessageTemplate::kInvalidPrivateMemberRead,
      &result));
  switch (result.type) {
    case PrivateMemberType::kPrivateField:
    case PrivateMemberType::kPrivateMethod: {
      return result.value;
    }
    case PrivateMemberType::kPrivateAccessor: {
      // The accessors are collected from the contexts, so there is no need to
      // perform brand checks.
      auto pair = Cast<AccessorPair>(result.value);
      if (IsNull(pair->getter())) {
        THROW_NEW_ERROR(
            isolate,
            NewError(MessageTemplate::kInvalidPrivateGetterAccess, desc));
      }
      DCHECK(IsJSFunction(pair->getter()));
      DirectHandle<JSFunction> getter(Cast<JSFunction>(pair->getter()),
                                      isolate);
      return Execution::Call(isolate, getter, receiver, {});
    }
  }
}
References v8::internal::Execution::Call(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{runtime-object.cc}::FindPrivateMembersFromReceiver(), v8::internal::IsNull(), v8::internal::kPrivateAccessor, v8::internal::kPrivateField, v8::internal::kPrivateMethod, MAYBE_RETURN_NULL, v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::base::internal::result, and THROW_NEW_ERROR.
Referenced by v8::internal::RUNTIME_FUNCTION().
HasProperty()
MaybeDirectHandle< Object > v8::internal::Runtime::HasProperty (Isolate * isolate, DirectHandle< Object > object, DirectHandle< Object > key) [static]
Definition at line 54 of file runtime-object.cc.
                                                                         {
  // Check that {object} is actually a receiver.
  if (!IsJSReceiver(*object)) {
    THROW_NEW_ERROR(
        isolate,
        NewTypeError(MessageTemplate::kInvalidInOperatorUse, key, object));
  }
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(object);
  // Convert the {key} to a name.
  DirectHandle<Name> name;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, name, Object::ToName(isolate, key));
  // Lookup the {name} on {receiver}.
  Maybe<bool> maybe = JSReceiver::HasProperty(isolate, receiver, name);
  if (maybe.IsNothing()) return MaybeDirectHandle<Object>();
  return isolate->factory()->ToBoolean(maybe.FromJust());
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::HasProperty(), v8::Maybe< T >::IsNothing(), v8::internal::key, v8::internal::name, THROW_NEW_ERROR, and v8::internal::FactoryBase< Impl >::ToBoolean().
Referenced by v8::internal::KeyedLoadIC::RuntimeLoad().
IsEnabledForFuzzing()
bool v8::internal::Runtime::IsEnabledForFuzzing (FunctionId id) [static]
Definition at line 196 of file runtime.cc.
                                               {
  CHECK(v8_flags.fuzzing);
  // In general, all runtime functions meant for testing should also be exposed
  // to the fuzzers. That way, the fuzzers are able to import and mutate
  // regression tests that use those functions. Internal runtime functions
  // (which are e.g. only called from other builtins, etc.) should not directly
  // be exposed as they are not meant to be called directly from JavaScript.
  // However, exceptions exist: some test functions cannot be used for certain
  // types of fuzzing (e.g. differential fuzzing), or would cause false
  // positive crashes and therefore should not be exposed to fuzzers at all.
  // For differential fuzzing, only a handful of functions are allowed,
  // everything else is disabled. Many runtime functions are unsuited for
  // differential fuzzing as they for example expose internal engine state
  // (e.g. functions such as %HasFastProperties). To avoid having to maintain a
  // large denylist of such functions, we instead use an allowlist for
  // differential fuzzing.
  bool is_differential_fuzzing =
      v8_flags.allow_natives_for_differential_fuzzing;
  if (is_differential_fuzzing) {
    switch (id) {
      case Runtime::kArrayBufferDetach:
      case Runtime::kDeoptimizeFunction:
      case Runtime::kDeoptimizeNow:
      case Runtime::kDisableOptimizationFinalization:
      case Runtime::kEnableCodeLoggingForTesting:
      case Runtime::kFinalizeOptimization:
      case Runtime::kGetUndetectable:
      case Runtime::kNeverOptimizeFunction:
      case Runtime::kOptimizeFunctionOnNextCall:
      case Runtime::kOptimizeMaglevOnNextCall:
      case Runtime::kOptimizeOsr:
      case Runtime::kPrepareFunctionForOptimization:
      case Runtime::kPretenureAllocationSite:
      case Runtime::kSetAllocationTimeout:
      case Runtime::kSetForceSlowPath:
      case Runtime::kSimulateNewspaceFull:
      case Runtime::kWaitForBackgroundOptimization:
      case Runtime::kSetBatterySaverMode:
      case Runtime::kSetPriorityBestEffort:
      case Runtime::kSetPriorityUserVisible:
      case Runtime::kSetPriorityUserBlocking:
      case Runtime::kIsEfficiencyModeEnabled:
      case Runtime::kBaselineOsr:
      case Runtime::kCompileBaseline:
#if V8_ENABLE_WEBASSEMBLY && V8_WASM_RANDOM_FUZZERS
      case Runtime::kWasmGenerateRandomModule:
#endif // V8_ENABLE_WEBASSEMBLY && V8_WASM_RANDOM_FUZZERS
#if V8_ENABLE_WEBASSEMBLY
      case Runtime::kWasmArray:
      case Runtime::kWasmStruct:
      case Runtime::kWasmTierUpFunction:
      case Runtime::kWasmTriggerTierUpForTesting:
#endif // V8_ENABLE_WEBASSEMBLY
        return true;
      default:
        return false;
    }
  }
  // Runtime functions disabled for all/most types of fuzzing.
  // Reasons for a function to be in this list include that it is not useful
  // for fuzzing (e.g. %DebugPrint) or not fuzzing-safe and therefore would
  // cause false-positive crashes (e.g. %AbortJS).
  switch (id) {
    case Runtime::kAbort:
    case Runtime::kAbortCSADcheck:
    case Runtime::kAbortJS:
    case Runtime::kSystemBreak:
    case Runtime::kBenchMaglev:
    case Runtime::kBenchTurbofan:
    case Runtime::kDebugPrint:
    case Runtime::kDisassembleFunction:
    case Runtime::kGetFunctionForCurrentFrame:
    case Runtime::kGetCallable:
    case Runtime::kGetAbstractModuleSource:
    case Runtime::kTurbofanStaticAssert:
    case Runtime::kClearFunctionFeedback:
    case Runtime::kStringIsFlat:
    case Runtime::kGetInitializerFunction:
#ifdef V8_ENABLE_WEBASSEMBLY
    case Runtime::kWasmTraceEnter:
    case Runtime::kWasmTraceExit:
    case Runtime::kWasmTraceMemory:
    case Runtime::kCheckIsOnCentralStack:
    case Runtime::kSetWasmInstantiateControls:
    case Runtime::kWasmNull:
    case Runtime::kFreezeWasmLazyCompilation:
    case Runtime::kDeserializeWasmModule:
#endif // V8_ENABLE_WEBASSEMBLY
    // TODO(353685107): investigate whether these should be exposed to fuzzers.
    case Runtime::kConstructDouble:
    case Runtime::kConstructConsString:
    case Runtime::kConstructSlicedString:
    case Runtime::kConstructInternalizedString:
    case Runtime::kConstructThinString:
    // TODO(353971258): investigate whether this should be exposed to fuzzers.
    case Runtime::kSerializeDeserializeNow:
    // TODO(353928347): investigate whether this should be exposed to fuzzers.
    case Runtime::kCompleteInobjectSlackTracking:
    // TODO(354005312): investigate whether this should be exposed to fuzzers.
    case Runtime::kShareObject:
    // TODO(354310130): investigate whether this should be exposed to fuzzers.
    case Runtime::kForceFlush:
      return false;
    case Runtime::kLeakHole:
      return v8_flags.hole_fuzzing;
    default:
      break;
  }
  // The default case: test functions are exposed, everything else is not.
  switch (id) {
#define F(name, nargs, ressize, ...) case k##name:
#define I(name, nargs, ressize, ...) case kInline##name:
    FOR_EACH_INTRINSIC_TEST(F, I)
    IF_WASM(FOR_EACH_INTRINSIC_WASM_TEST, F, I)
#undef I
#undef F
    return true;
    default:
      return false;
  }
}
References CHECK, v8::internal::F, FOR_EACH_INTRINSIC_TEST, FOR_EACH_INTRINSIC_WASM_TEST, v8::internal::I, IF_WASM, and v8::internal::v8_flags.
Referenced by v8::internal::Parser::NewV8RuntimeFunctionForFuzzing().
IsNonReturning()
bool v8::internal::Runtime::IsNonReturning (FunctionId id) [static]
Definition at line 145 of file runtime.cc.
                                          {
  switch (id) {
    case Runtime::kThrowUnsupportedSuperError:
    case Runtime::kThrowConstructorNonCallableError:
    case Runtime::kThrowStaticPrototypeError:
    case Runtime::kThrowSuperAlreadyCalledError:
    case Runtime::kThrowSuperNotCalled:
    case Runtime::kReThrow:
    case Runtime::kReThrowWithMessage:
    case Runtime::kThrow:
    case Runtime::kThrowApplyNonFunction:
    case Runtime::kThrowCalledNonCallable:
    case Runtime::kThrowConstructedNonConstructable:
    case Runtime::kThrowConstructorReturnedNonObject:
    case Runtime::kThrowInvalidStringLength:
    case Runtime::kThrowInvalidTypedArrayAlignment:
    case Runtime::kThrowIteratorError:
    case Runtime::kThrowIteratorResultNotAnObject:
    case Runtime::kThrowThrowMethodMissing:
    case Runtime::kThrowSymbolIteratorInvalid:
    case Runtime::kThrowNotConstructor:
    case Runtime::kThrowRangeError:
    case Runtime::kThrowReferenceError:
    case Runtime::kThrowAccessedUninitializedVariable:
    case Runtime::kThrowStackOverflow:
    case Runtime::kThrowSymbolAsyncIteratorInvalid:
    case Runtime::kThrowTypeError:
    case Runtime::kThrowConstAssignError:
    case Runtime::kTerminateExecution:
#if V8_ENABLE_WEBASSEMBLY
    case Runtime::kThrowWasmError:
    case Runtime::kThrowWasmStackOverflow:
    case Runtime::kThrowWasmSuspendError:
#endif // V8_ENABLE_WEBASSEMBLY
      return true;
    default:
      return false;
  }
}
MayAllocate()
bool v8::internal::Runtime::MayAllocate (FunctionId id) [static]
Definition at line 185 of file runtime.cc.
                                       {
  switch (id) {
    case Runtime::kCompleteInobjectSlackTracking:
    case Runtime::kCompleteInobjectSlackTrackingForMap:
    case Runtime::kGlobalPrint:
      return false;
    default:
      return true;
  }
}
Referenced by v8::internal::compiler::CodeAssembler::CallRuntimeImpl().
NeedsExactContext()
bool v8::internal::Runtime::NeedsExactContext (FunctionId id) [static]
Definition at line 92 of file runtime.cc.
                                             {
  switch (id) {
    case Runtime::kInlineAsyncFunctionReject:
    case Runtime::kInlineAsyncFunctionResolve:
      // For %_AsyncFunctionReject and %_AsyncFunctionResolve we don't
      // really need the current context, which in particular allows
      // us to usually eliminate the catch context for the implicit
      // try-catch in async function.
      return false;
    case Runtime::kCreatePrivateAccessors:
    case Runtime::kCopyDataProperties:
    case Runtime::kCreateDataProperty:
    case Runtime::kCreatePrivateNameSymbol:
    case Runtime::kCreatePrivateBrandSymbol:
    case Runtime::kLoadPrivateGetter:
    case Runtime::kLoadPrivateSetter:
    case Runtime::kReThrow:
    case Runtime::kReThrowWithMessage:
    case Runtime::kThrow:
    case Runtime::kThrowApplyNonFunction:
    case Runtime::kThrowCalledNonCallable:
    case Runtime::kThrowConstAssignError:
    case Runtime::kThrowConstructorNonCallableError:
    case Runtime::kThrowConstructedNonConstructable:
    case Runtime::kThrowConstructorReturnedNonObject:
    case Runtime::kThrowInvalidStringLength:
    case Runtime::kThrowInvalidTypedArrayAlignment:
    case Runtime::kThrowIteratorError:
    case Runtime::kThrowIteratorResultNotAnObject:
    case Runtime::kThrowNotConstructor:
    case Runtime::kThrowRangeError:
    case Runtime::kThrowReferenceError:
    case Runtime::kThrowAccessedUninitializedVariable:
    case Runtime::kThrowStackOverflow:
    case Runtime::kThrowStaticPrototypeError:
    case Runtime::kThrowSuperAlreadyCalledError:
    case Runtime::kThrowSuperNotCalled:
    case Runtime::kThrowSymbolAsyncIteratorInvalid:
    case Runtime::kThrowSymbolIteratorInvalid:
    case Runtime::kThrowThrowMethodMissing:
    case Runtime::kThrowTypeError:
    case Runtime::kThrowUnsupportedSuperError:
    case Runtime::kTerminateExecution:
#if V8_ENABLE_WEBASSEMBLY
    case Runtime::kThrowWasmError:
    case Runtime::kThrowWasmStackOverflow:
#endif // V8_ENABLE_WEBASSEMBLY
      return false;
    default:
      return true;
  }
}
Referenced by v8::internal::compiler::OperatorProperties::NeedsExactContext().
RuntimeFunctionTable()
const Runtime::Function * v8::internal::Runtime::RuntimeFunctionTable (Isolate * isolate) [static]
Definition at line 353 of file runtime.cc.
                                                                     {
#ifdef USE_SIMULATOR
  // When running with the simulator we need to provide a table which has
  // redirected runtime entry addresses.
  if (!isolate->runtime_state()->redirected_intrinsic_functions()) {
    size_t function_count = arraysize(kIntrinsicFunctions);
    Function* redirected_functions = new Function[function_count];
    memcpy(redirected_functions, kIntrinsicFunctions,
           sizeof(kIntrinsicFunctions));
    for (size_t i = 0; i < function_count; i++) {
      ExternalReference redirected_entry =
          ExternalReference::Create(static_cast<Runtime::FunctionId>(i));
      redirected_functions[i].entry = redirected_entry.address();
    }
    isolate->runtime_state()->set_redirected_intrinsic_functions(
        redirected_functions);
  }
  return isolate->runtime_state()->redirected_intrinsic_functions();
#else
  return kIntrinsicFunctions;
#endif
}
References v8::internal::ExternalReference::address(), arraysize, v8::internal::ExternalReference::Create(), v8::internal::Runtime::Function::entry, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kIntrinsicFunctions, v8::internal::RuntimeState::redirected_intrinsic_functions(), v8::internal::Isolate::runtime_state(), and v8::internal::RuntimeState::set_redirected_intrinsic_functions().
SetObjectProperty() [1/2]
MaybeDirectHandle< Object > v8::internal::Runtime::SetObjectProperty (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, DirectHandle< Object > value, MaybeDirectHandle< JSAny > receiver, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>()) [static]
Definition at line 379 of file runtime-object.cc.
                                     {
  DirectHandle<JSAny> receiver;
  if (!maybe_receiver.ToHandle(&receiver)) {
    receiver = lookup_start_obj;
  }
  if (IsNullOrUndefined(*lookup_start_obj, isolate)) {
    MaybeDirectHandle<String> maybe_property =
        Object::NoSideEffectsToMaybeString(isolate, key);
    DirectHandle<String> property_name;
    if (maybe_property.ToHandle(&property_name)) {
      THROW_NEW_ERROR(
          isolate,
          NewTypeError(MessageTemplate::kNonObjectPropertyStoreWithProperty,
                       lookup_start_obj, property_name));
    } else {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kNonObjectPropertyStore,
                                   lookup_start_obj));
    }
  }
  // Check if the given key is an array index.
  bool success = false;
  PropertyKey lookup_key(isolate, key, &success);
  if (!success) return MaybeDirectHandle<Object>();
  LookupIterator it(isolate, receiver, lookup_key, lookup_start_obj);
  if (IsSymbol(*key) && Cast<Symbol>(*key)->is_private_name()) {
    Maybe<bool> can_store = JSReceiver::CheckPrivateNameStore(&it, false);
    MAYBE_RETURN_NULL(can_store);
    if (!can_store.FromJust()) {
      return isolate->factory()->undefined_value();
    }
  }
  MAYBE_RETURN_NULL(
      Object::SetProperty(&it, value, store_origin, should_throw));
  return value;
}
References v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::IsNullOrUndefined(), v8::internal::key, MAYBE_RETURN_NULL, v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::Object::SetProperty(), THROW_NEW_ERROR, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::Object::Set(), SetObjectProperty(), v8::internal::JSReceiver::SetOrCopyDataProperties(), and v8::internal::KeyedStoreIC::Store().
SetObjectProperty() [2/2]
MaybeDirectHandle< Object > v8::internal::Runtime::SetObjectProperty (Isolate * isolate, DirectHandle< JSAny > object, DirectHandle< Object > key, DirectHandle< Object > value, StoreOrigin store_origin, Maybe< ShouldThrow > should_throw = Nothing<ShouldThrow>()) [static]
Definition at line 423 of file runtime-object.cc.
                                     {
  return SetObjectProperty(isolate, object, key, value, object, store_origin,
                           should_throw);
}
References v8::internal::key, SetObjectProperty(), and v8::internal::value.
SetPrivateMember()
MaybeDirectHandle< Object > v8::internal::Runtime::SetPrivateMember (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< String > desc, DirectHandle< Object > value) [static]
Definition at line 1515 of file runtime-object.cc.
                                                           {
  PrivateMember result;
  MAYBE_RETURN_NULL(FindPrivateMembersFromReceiver(
      isolate, receiver, desc, MessageTemplate::kInvalidPrivateMemberRead,
      &result));
  switch (result.type) {
    case PrivateMemberType::kPrivateField: {
      auto symbol = Cast<Symbol>(result.brand_or_field_symbol);
      return Object::SetProperty(isolate, receiver, symbol, value,
                                 StoreOrigin::kMaybeKeyed);
    }
    case PrivateMemberType::kPrivateMethod: {
      THROW_NEW_ERROR(
          isolate, NewError(MessageTemplate::kInvalidPrivateMethodWrite, desc));
    }
    case PrivateMemberType::kPrivateAccessor: {
      // The accessors are collected from the contexts, so there is no need to
      // perform brand checks.
      auto pair = Cast<AccessorPair>(result.value);
      if (IsNull(pair->setter())) {
        THROW_NEW_ERROR(
            isolate,
            NewError(MessageTemplate::kInvalidPrivateSetterAccess, desc));
      }
      DCHECK(IsJSFunction(pair->setter()));
      DirectHandle<Object> args[] = {value};
      DirectHandle<JSFunction> setter(Cast<JSFunction>(pair->setter()),
                                      isolate);
      return Execution::Call(isolate, setter, receiver, base::VectorOf(args));
    }
  }
}
References v8::base::args, v8::internal::Execution::Call(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{runtime-object.cc}::FindPrivateMembersFromReceiver(), v8::internal::IsNull(), v8::internal::kMaybeKeyed, v8::internal::kPrivateAccessor, v8::internal::kPrivateField, v8::internal::kPrivateMethod, MAYBE_RETURN_NULL, v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), v8::base::internal::result, v8::internal::Object::SetProperty(), v8::internal::setter, THROW_NEW_ERROR, v8::internal::value, and v8::base::VectorOf().
Referenced by v8::internal::RUNTIME_FUNCTION().
ThrowIteratorError()
static V8_WARN_UNUSED_RESULT MaybeDirectHandle<Object> v8::internal::Runtime::ThrowIteratorError (Isolate * isolate, DirectHandle< Object > object) [static]
Member Data Documentation
kCanTriggerGC
constexpr bool v8::internal::Runtime::kCanTriggerGC[] [static], [constexpr]
Initial value:
= {
#define F(name, nargs, ressize, ...)
      FOR_EACH_INTRINSIC(F) FOR_EACH_INLINE_INTRINSIC(F)}
Definition at line 1047 of file runtime.h.
Referenced by v8::internal::compiler::turboshaft::AnalyzeCall().
kNotFound
const int v8::internal::Runtime::kNotFound = -1 [static]
Definition at line 949 of file runtime.h.
kNumInlineFunctions
constexpr int v8::internal::Runtime::kNumInlineFunctions [static], [constexpr]
Initial value:
=
#define COUNT(...)
      FOR_EACH_INLINE_INTRINSIC(COUNT)
Definition at line 924 of file runtime.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/runtime/runtime.h
/mnt/V8SourceCode/src/runtime/runtime-debug.cc
/mnt/V8SourceCode/src/runtime/runtime-object.cc
/mnt/V8SourceCode/src/runtime/runtime.cc