v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass > Class Template Reference
#include <struct-types.h>
Public Types
enum ComputeOffsets : bool { kComputeOffsets = true
, kUseProvidedOffsets = false
 }
Public Member Functions
BuilderImpl (Zone *zone, uint32_t field_count, bool is_descriptor, bool is_shared)
void AddField (ValueTypeSubclass type, bool mutability, uint32_t offset=0)
void set_total_fields_size (uint32_t size)
Subclass * Build (ComputeOffsets compute_offsets=kComputeOffsets)
Private Attributes
Zone *const zone_
const uint32_t field_count_
const bool is_descriptor_
const bool is_shared_
uint32_t cursor_
uint32_t * field_offsets_
ValueTypeSubclass *const buffer_
bool *const mutabilities_
Detailed Description
template<class Subclass, class ValueTypeSubclass>
class v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >
Definition at line 146 of file struct-types.h.
Member Enumeration Documentation
ComputeOffsets
template<class Subclass , class ValueTypeSubclass >
enum v8::internal::wasm::StructTypeBase::BuilderImpl::ComputeOffsets : bool
Enumerator
kComputeOffsets
kUseProvidedOffsets
Definition at line 148 of file struct-types.h.
                        : bool {
      kComputeOffsets = true,
      kUseProvidedOffsets = false
    };
Constructor & Destructor Documentation
BuilderImpl()
template<class Subclass , class ValueTypeSubclass >
v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::BuilderImpl (Zone * zone, uint32_t field_count, bool is_descriptor, bool is_shared) [inline]
Definition at line 153 of file struct-types.h.
        : zone_(zone),
          field_count_(field_count),
          is_descriptor_(is_descriptor),
          is_shared_(is_shared),
          cursor_(0),
          field_offsets_(zone_->AllocateArray<uint32_t>(field_count_)),
          buffer_(zone->AllocateArray<ValueTypeSubclass>(
              static_cast<int>(field_count))),
          mutabilities_(
              zone->AllocateArray<bool>(static_cast<int>(field_count))) {}
Member Function Documentation
AddField()
template<class Subclass , class ValueTypeSubclass >
void v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField (ValueTypeSubclass type, bool mutability, uint32_t offset = 0) [inline]
Definition at line 166 of file struct-types.h.
                                       {
      DCHECK_LT(cursor_, field_count_);
      if (cursor_ > 0) {
        field_offsets_[cursor_ - 1] = offset;
      } else {
        // offset == 0 could mean that we'll compute the offsets later,
        // or that this is the first field's offset being copied over from
        // another struct type.
        DCHECK(offset == 0 || (is_descriptor_ && offset == kTaggedSize));
      }
      mutabilities_[cursor_] = mutability;
      buffer_[cursor_++] = type;
    }
References v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::buffer_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::cursor_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_count_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_offsets_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::is_descriptor_, v8::internal::kTaggedSize, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::mutabilities_, v8::internal::wasm::StructTypeBase::mutability(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
Build()
template<class Subclass , class ValueTypeSubclass >
Subclass* v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build (ComputeOffsets compute_offsets = kComputeOffsets) [inline]
Definition at line 189 of file struct-types.h.
                                                                      {
      DCHECK_EQ(cursor_, field_count_);
      Subclass* result =
          zone_->New<Subclass>(field_count_, field_offsets_, buffer_,
                               mutabilities_, is_descriptor_, is_shared_);
      if (compute_offsets == kComputeOffsets) {
        result->InitializeOffsets();
      } else {
#if DEBUG
        bool offsets_specified = true;
        for (uint32_t i = 0; i < field_count_; i++) {
          if (field_offsets_[i] == 0) {
            offsets_specified = false;
            break;
          }
        }
        result->offsets_initialized_ = offsets_specified;
#endif
      }
      return result;
    }
References v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::buffer_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::cursor_, DCHECK_EQ, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_count_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_offsets_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::is_descriptor_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::is_shared_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::kComputeOffsets, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::mutabilities_, v8::internal::Zone::New(), v8::base::internal::result, and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::zone_.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
set_total_fields_size()
template<class Subclass , class ValueTypeSubclass >
void v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::set_total_fields_size (uint32_t size) [inline]
Definition at line 181 of file struct-types.h.
                                              {
      if (field_count_ == 0) {
        DCHECK_EQ(is_descriptor_ ? kTaggedSize : 0, size);
        return;
      }
      field_offsets_[field_count_ - 1] = size;
    }
References DCHECK_EQ, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_count_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_offsets_, v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::is_descriptor_, v8::internal::kTaggedSize, and size().
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef().
Member Data Documentation
buffer_
template<class Subclass , class ValueTypeSubclass >
ValueTypeSubclass* const v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::buffer_ [private]
Definition at line 218 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build().
cursor_
template<class Subclass , class ValueTypeSubclass >
uint32_t v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::cursor_ [private]
Definition at line 216 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build().
field_count_
template<class Subclass , class ValueTypeSubclass >
const uint32_t v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_count_ [private]
Definition at line 213 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::set_total_fields_size().
field_offsets_
template<class Subclass , class ValueTypeSubclass >
uint32_t* v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::field_offsets_ [private]
Definition at line 217 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::set_total_fields_size().
is_descriptor_
template<class Subclass , class ValueTypeSubclass >
const bool v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::is_descriptor_ [private]
Definition at line 214 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::set_total_fields_size().
is_shared_
template<class Subclass , class ValueTypeSubclass >
const bool v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::is_shared_ [private]
Definition at line 215 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build().
mutabilities_
template<class Subclass , class ValueTypeSubclass >
bool* const v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::mutabilities_ [private]
Definition at line 219 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), and v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build().
zone_
template<class Subclass , class ValueTypeSubclass >
Zone* const v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::zone_ [private]
Definition at line 212 of file struct-types.h.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h