v8::internal::TimedHistogram Class Reference
#include <counters.h>
Public Member Functions
void RecordAbandon (base::ElapsedTimer *timer, Isolate *isolate)
V8_EXPORT_PRIVATE void AddTimedSample (base::TimeDelta sample)
Protected Member Functions
void Stop (base::ElapsedTimer *timer)
void LogStart (Isolate *isolate)
void LogEnd (Isolate *isolate)
TimedHistogram ()=default
TimedHistogram (const TimedHistogram &)=delete
TimedHistogram & operator= (const TimedHistogram &)=delete
void Initialize (const char *name, int min, int max, TimedHistogramResolution resolution, int num_buckets, Counters *counters)
Protected Attributes
TimedHistogramResolution resolution_
Friends
class Counters
class CountersInitializer
Detailed Description
Definition at line 233 of file counters.h.
Constructor & Destructor Documentation
TimedHistogram() [1/2]
v8::internal::TimedHistogram::TimedHistogram () [protected], [default]
TimedHistogram() [2/2]
v8::internal::TimedHistogram::TimedHistogram (const TimedHistogram &) [protected], [delete]
Member Function Documentation
AddTimedSample()
void v8::internal::TimedHistogram::AddTimedSample (base::TimeDelta sample)
Definition at line 66 of file counters.cc.
                                                        {
  if (Enabled()) {
    int64_t sample_int = resolution_ == TimedHistogramResolution::MICROSECOND
                             ? sample.InMicroseconds()
                             : sample.InMilliseconds();
    AddSample(static_cast<int>(sample_int));
  }
}
References v8::internal::Histogram::AddSample(), v8::internal::Histogram::Enabled(), v8::base::TimeDelta::InMicroseconds(), v8::base::TimeDelta::InMilliseconds(), v8::internal::MICROSECOND, and resolution_.
Referenced by Stop(), and v8::internal::BaseTimedHistogramScope::StopInternal().
Initialize()
void v8::internal::TimedHistogram::Initialize (const char * name, int min, int max, TimedHistogramResolution resolution, int num_buckets, Counters * counters) [inline], [protected]
Definition at line 265 of file counters.h.
                                      {
    Histogram::Initialize(name, min, max, num_buckets, counters);
    resolution_ = resolution;
  }
References v8::internal::Histogram::counters(), v8::internal::Histogram::Initialize(), v8::internal::Histogram::max(), v8::internal::Histogram::min(), v8::internal::Histogram::name(), v8::internal::Histogram::num_buckets(), and resolution_.
Referenced by v8::internal::NestedTimedHistogram::NestedTimedHistogram(), and v8::internal::CountersInitializer::Visit().
LogEnd()
void v8::internal::TimedHistogram::LogEnd (Isolate * isolate) [protected]
LogStart()
void v8::internal::TimedHistogram::LogStart (Isolate * isolate) [protected]
operator=()
TimedHistogram& v8::internal::TimedHistogram::operator= (const TimedHistogram &) [protected], [delete]
RecordAbandon()
void v8::internal::TimedHistogram::RecordAbandon (base::ElapsedTimer * timer, Isolate * isolate)
Definition at line 75 of file counters.cc.
                                                     {
  if (Enabled()) {
    DCHECK(timer->IsStarted());
    timer->Stop();
    int64_t sample = resolution_ == TimedHistogramResolution::MICROSECOND
                         ? base::TimeDelta::Max().InMicroseconds()
                         : base::TimeDelta::Max().InMilliseconds();
    AddSample(static_cast<int>(sample));
  }
  if (isolate != nullptr) {
    V8FileLogger::CallEventLogger(isolate, name(), v8::LogEventStatus::kEnd,
                                  true);
  }
}
References v8::internal::Histogram::AddSample(), v8::internal::V8FileLogger::CallEventLogger(), v8::internal::DCHECK(), v8::internal::Histogram::Enabled(), v8::base::TimeDelta::InMicroseconds(), v8::base::TimeDelta::InMilliseconds(), v8::base::ElapsedTimer::IsStarted(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::base::TimeDelta::Max(), v8::internal::MICROSECOND, v8::internal::Histogram::name(), resolution_, and v8::base::ElapsedTimer::Stop().
Stop()
void v8::internal::TimedHistogram::Stop (base::ElapsedTimer * timer) [protected]
Definition at line 60 of file counters.cc.
                                                 {
  DCHECK(Enabled());
  AddTimedSample(timer->Elapsed());
  timer->Stop();
}
References AddTimedSample(), v8::internal::DCHECK(), v8::base::ElapsedTimer::Elapsed(), v8::internal::Histogram::Enabled(), and v8::base::ElapsedTimer::Stop().
Friends And Related Function Documentation
Counters
friend class Counters [friend]
Definition at line 256 of file counters.h.
CountersInitializer
friend class CountersInitializer [friend]
Definition at line 257 of file counters.h.
Member Data Documentation
resolution_
TimedHistogramResolution v8::internal::TimedHistogram::resolution_ [protected]
Definition at line 259 of file counters.h.
Referenced by AddTimedSample(), Initialize(), and RecordAbandon().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc