v8::internal::maglev::FastCreateClosure Class Reference
#include <maglev-ir.h>
Public Member Functions
FastCreateClosure (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell)
compiler::SharedFunctionInfoRef shared_function_info () const
compiler::FeedbackCellRef feedback_cell () const
Input & context ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, FastCreateClosure >
Private Attributes
const compiler::SharedFunctionInfoRef shared_function_info_
const compiler::FeedbackCellRef feedback_cell_
Additional Inherited Members
Detailed Description
Definition at line 6624 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::FastCreateClosure::Base = FixedInputValueNodeT<1, FastCreateClosure> [private]
Definition at line 6625 of file maglev-ir.h.
Constructor & Destructor Documentation
FastCreateClosure()
v8::internal::maglev::FastCreateClosure::FastCreateClosure (uint64_t bitfield, compiler::SharedFunctionInfoRef shared_function_info, compiler::FeedbackCellRef feedback_cell) [inline], [explicit]
Definition at line 6628 of file maglev-ir.h.
      : Base(bitfield),
        shared_function_info_(shared_function_info),
        feedback_cell_(feedback_cell) {}
Member Function Documentation
context()
Input& v8::internal::maglev::FastCreateClosure::context () [inline]
Definition at line 6640 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback_cell()
compiler::FeedbackCellRef v8::internal::maglev::FastCreateClosure::feedback_cell () const [inline]
Definition at line 6638 of file maglev-ir.h.
{ return feedback_cell_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::FastCreateClosure::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::FastCreateClosure::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::FastCreateClosure::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7972 of file maglev-ir.cc.
                                                                               {
  os << "(" << *shared_function_info().object() << ", "
     << feedback_cell().object() << ")";
}
References feedback_cell(), v8::internal::compiler::FeedbackCellRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), and shared_function_info().
SetValueLocationConstraints()
void v8::internal::maglev::FastCreateClosure::SetValueLocationConstraints ()
shared_function_info()
compiler::SharedFunctionInfoRef v8::internal::maglev::FastCreateClosure::shared_function_info () const [inline]
Definition at line 6635 of file maglev-ir.h.
                                                             {
    return shared_function_info_;
  }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_cell_
const compiler::FeedbackCellRef v8::internal::maglev::FastCreateClosure::feedback_cell_ [private]
Definition at line 6656 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::FastCreateClosure::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6647 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::FastCreateClosure::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::Call() | OpProperties::CanAllocate() |
      OpProperties::LazyDeopt() | OpProperties::NotIdempotent()
Definition at line 6643 of file maglev-ir.h.
shared_function_info_
const compiler::SharedFunctionInfoRef v8::internal::maglev::FastCreateClosure::shared_function_info_ [private]
Definition at line 6655 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc