v8::internal::CompilationCacheEvalOrScript Class Reference
#include <compilation-cache.h>
Public Member Functions
CompilationCacheEvalOrScript (Isolate *isolate)
Handle< CompilationCacheTable > GetTable ()
void Iterate (RootVisitor *v)
void Clear ()
void Remove (DirectHandle< SharedFunctionInfo > function_info)
Protected Member Functions
Isolate * isolate () const
DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheEvalOrScript)
Protected Attributes
Isolate *const isolate_
Tagged< Object > table_
Detailed Description
Definition at line 23 of file compilation-cache.h.
Constructor & Destructor Documentation
CompilationCacheEvalOrScript()
v8::internal::CompilationCacheEvalOrScript::CompilationCacheEvalOrScript (Isolate * isolate) [inline], [explicit]
Definition at line 25 of file compilation-cache.h.
: isolate_(isolate) {}
Member Function Documentation
Clear()
void v8::internal::CompilationCacheEvalOrScript::Clear ()
Definition at line 120 of file compilation-cache.cc.
                                         {
  table_ = ReadOnlyRoots(isolate()).undefined_value();
}
References isolate(), and table_.
Referenced by v8::internal::CompilationCache::Clear().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::CompilationCacheEvalOrScript::DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheEvalOrScript) [protected]
GetTable()
Handle< CompilationCacheTable > v8::internal::CompilationCacheEvalOrScript::GetTable ()
Definition at line 32 of file compilation-cache.cc.
                                                                     {
  if (IsUndefined(table_, isolate())) {
    return CompilationCacheTable::New(isolate(), kInitialCacheSize);
  }
  return handle(Cast<CompilationCacheTable>(table_), isolate());
}
References v8::internal::handle(), isolate(), v8::internal::kInitialCacheSize, v8::internal::anonymous_namespace{intl-objects.cc}::New(), and table_.
Referenced by v8::internal::CompilationCacheEval::Lookup(), v8::internal::CompilationCacheScript::Lookup(), v8::internal::CompilationCacheEval::Put(), v8::internal::CompilationCacheScript::Put(), and v8::internal::CompilationCacheEval::UpdateEval().
isolate()
Isolate* v8::internal::CompilationCacheEvalOrScript::isolate () const [inline], [protected]
Definition at line 40 of file compilation-cache.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::CompilationCacheScript::Age(), v8::internal::CompilationCacheEval::Age(), Clear(), GetTable(), v8::internal::CompilationCacheEval::Lookup(), v8::internal::CompilationCacheScript::Lookup(), v8::internal::CompilationCacheScript::Put(), and Remove().
Iterate()
void v8::internal::CompilationCacheEvalOrScript::Iterate (RootVisitor * v)
Definition at line 109 of file compilation-cache.cc.
                                                         {
  v->VisitRootPointer(Root::kCompilationCache, nullptr,
                      FullObjectSlot(&table_));
}
References table_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::CompilationCache::Iterate().
Remove()
void v8::internal::CompilationCacheEvalOrScript::Remove (DirectHandle< SharedFunctionInfo > function_info)
Definition at line 129 of file compilation-cache.cc.
                                                    {
  if (IsUndefined(table_, isolate())) return;
  Cast<CompilationCacheTable>(table_)->Remove(*function_info);
}
References isolate(), and table_.
Referenced by v8::internal::CompilationCache::Remove().
Member Data Documentation
isolate_
Isolate* const v8::internal::CompilationCacheEvalOrScript::isolate_ [protected]
Definition at line 42 of file compilation-cache.h.
Referenced by isolate().
table_
Tagged<Object> v8::internal::CompilationCacheEvalOrScript::table_ [protected]
Definition at line 43 of file compilation-cache.h.
Referenced by v8::internal::CompilationCacheScript::Age(), v8::internal::CompilationCacheEval::Age(), Clear(), GetTable(), Iterate(), v8::internal::CompilationCacheEval::Put(), v8::internal::CompilationCacheScript::Put(), and Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compilation-cache.h
/mnt/V8SourceCode/src/codegen/compilation-cache.cc