v8::internal::compiler::SimdImmediateParameter< simd_size, typename > Class Template Reference
#include <machine-operator.h>
Public Member Functions
SimdImmediateParameter (const uint8_t immediate[simd_size])
SimdImmediateParameter ()=default
const std::array< uint8_t, simd_size > & immediate () const
const uint8_t * data () const
uint8_t operator[] (int x) const
Private Attributes
std::array< uint8_t, simd_size > immediate_
Detailed Description
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
class v8::internal::compiler::SimdImmediateParameter< simd_size, typename >
Definition at line 302 of file machine-operator.h.
Constructor & Destructor Documentation
SimdImmediateParameter() [1/2]
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::SimdImmediateParameter (const uint8_t immediate[simd_size]) [inline], [explicit]
Definition at line 304 of file machine-operator.h.
                                                                      {
    std::copy(immediate, immediate + simd_size, immediate_.begin());
  }
References v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate(), and v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate_.
SimdImmediateParameter() [2/2]
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::SimdImmediateParameter () [default]
Member Function Documentation
data()
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
const uint8_t* v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::data () const [inline]
Definition at line 309 of file machine-operator.h.
{ return immediate_.data(); }
References v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate_.
Referenced by v8::internal::compiler::SLPTree::BuildTreeRec(), and v8::internal::compiler::Revectorizer::VectorizeTree().
immediate()
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
const std::array<uint8_t, simd_size>& v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate () const [inline]
Definition at line 308 of file machine-operator.h.
{ return immediate_; }
References v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator==(), and v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::SimdImmediateParameter().
operator[]()
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
uint8_t v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::operator[] (int x) const [inline]
Definition at line 310 of file machine-operator.h.
{ return immediate_[x]; }
References v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate_.
Member Data Documentation
immediate_
template<const int simd_size = kSimd128Size, typename = std::enable_if_t<simd_size == kSimd128Size || simd_size == kSimd256Size>>
std::array<uint8_t, simd_size> v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate_ [private]
Definition at line 313 of file machine-operator.h.
Referenced by v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::data(), v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::immediate(), v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::operator[](), and v8::internal::compiler::SimdImmediateParameter< simd_size, typename >::SimdImmediateParameter().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h