v8::internal::MaybeObjectDirectHandle Class Reference
#include <maybe-handles.h>
Public Member Functions
MaybeObjectDirectHandle ()
MaybeObjectDirectHandle (Tagged< MaybeObject > object, Isolate *isolate)
MaybeObjectDirectHandle (Tagged< Object > object, Isolate *isolate)
MaybeObjectDirectHandle (Tagged< Smi > object, Isolate *isolate)
MaybeObjectDirectHandle (Tagged< MaybeObject > object, LocalHeap *local_heap)
MaybeObjectDirectHandle (Tagged< Object > object, LocalHeap *local_heap)
MaybeObjectDirectHandle (Tagged< Smi > object, LocalHeap *local_heap)
MaybeObjectDirectHandle (DirectHandle< Object > object)
MaybeObjectDirectHandle (MaybeObjectHandle obj)
Tagged< MaybeObject > operator* () const
Tagged< MaybeObject > operator-> () const
DirectHandle< Object > object () const
bool is_identical_to (const MaybeObjectDirectHandle &other) const
bool is_identical_to (const MaybeObjectHandle &other) const
bool is_null () const
HeapObjectReferenceType reference_type () const
Static Public Member Functions
static MaybeObjectDirectHandle Weak (Tagged< Object > object, Isolate *isolate)
static MaybeObjectDirectHandle Weak (DirectHandle< Object > object)
Private Member Functions
MaybeObjectDirectHandle (Tagged< Object > object, HeapObjectReferenceType reference_type, Isolate *isolate)
MaybeObjectDirectHandle (DirectHandle< Object > object, HeapObjectReferenceType reference_type)
Private Attributes
HeapObjectReferenceType reference_type_
MaybeDirectHandle< Object > handle_
Detailed Description
Definition at line 310 of file maybe-handles.h.
Constructor & Destructor Documentation
MaybeObjectDirectHandle() [1/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle () [inline]
Definition at line 312 of file maybe-handles.h.
      : reference_type_(HeapObjectReferenceType::STRONG) {}
Referenced by Weak().
MaybeObjectDirectHandle() [2/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< MaybeObject > object, Isolate * isolate) [inline]
Definition at line 200 of file maybe-handles-inl.h.
                                                                   {
  Tagged<HeapObject> heap_object;
  DCHECK(!object.IsCleared());
  if (object.GetHeapObjectIfWeak(&heap_object)) {
    handle_ = direct_handle(heap_object, isolate);
    reference_type_ = HeapObjectReferenceType::WEAK;
  } else {
    handle_ = direct_handle(Cast<Object>(object), isolate);
    reference_type_ = HeapObjectReferenceType::STRONG;
  }
}
References DCHECK, v8::internal::direct_handle(), STRONG, and WEAK.
MaybeObjectDirectHandle() [3/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< Object > object, Isolate * isolate) [inline]
Definition at line 226 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, isolate) {}
MaybeObjectDirectHandle() [4/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< Smi > object, Isolate * isolate) [inline]
Definition at line 231 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, isolate) {}
MaybeObjectDirectHandle() [5/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< MaybeObject > object, LocalHeap * local_heap) [inline]
Definition at line 213 of file maybe-handles-inl.h.
                                                                        {
  Tagged<HeapObject> heap_object;
  DCHECK(!object.IsCleared());
  if (object.GetHeapObjectIfWeak(&heap_object)) {
    handle_ = direct_handle(heap_object, local_heap);
    reference_type_ = HeapObjectReferenceType::WEAK;
  } else {
    handle_ = direct_handle(Cast<Object>(object), local_heap);
    reference_type_ = HeapObjectReferenceType::STRONG;
  }
}
References DCHECK, v8::internal::direct_handle(), STRONG, and WEAK.
MaybeObjectDirectHandle() [6/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< Object > object, LocalHeap * local_heap) [inline]
Definition at line 236 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, local_heap) {}
MaybeObjectDirectHandle() [7/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< Smi > object, LocalHeap * local_heap) [inline]
Definition at line 241 of file maybe-handles-inl.h.
    : reference_type_(HeapObjectReferenceType::STRONG),
      handle_(object, local_heap) {}
MaybeObjectDirectHandle() [8/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (DirectHandle< Object > object) [inline], [explicit]
Definition at line 321 of file maybe-handles.h.
      : reference_type_(HeapObjectReferenceType::STRONG), handle_(object) {}
MaybeObjectDirectHandle() [9/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (MaybeObjectHandle obj) [inline]
Definition at line 251 of file maybe-handles-inl.h.
    : reference_type_(object.reference_type_), handle_(object.handle_) {}
MaybeObjectDirectHandle() [10/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (Tagged< Object > object, HeapObjectReferenceType reference_type, Isolate * isolate) [inline], [private]
Definition at line 246 of file maybe-handles-inl.h.
    : reference_type_(reference_type), handle_(object, isolate) {}
MaybeObjectDirectHandle() [11/11]
v8::internal::MaybeObjectDirectHandle::MaybeObjectDirectHandle (DirectHandle< Object > object, HeapObjectReferenceType reference_type) [inline], [private]
Definition at line 348 of file maybe-handles.h.
      : reference_type_(reference_type), handle_(object) {}
Member Function Documentation
is_identical_to() [1/2]
bool v8::internal::MaybeObjectDirectHandle::is_identical_to (const MaybeObjectDirectHandle & other) const [inline]
Definition at line 260 of file maybe-handles-inl.h.
                                                {
  DirectHandle<Object> this_handle;
  DirectHandle<Object> other_handle;
  return reference_type_ == other.reference_type_ &&
         handle_.ToHandle(&this_handle) ==
             other.handle_.ToHandle(&other_handle) &&
         this_handle.is_identical_to(other_handle);
}
References handle_, v8::internal::DirectHandle< T >::is_identical_to(), and reference_type_.
Referenced by v8::internal::IC::UpdatePolymorphicIC().
is_identical_to() [2/2]
bool v8::internal::MaybeObjectDirectHandle::is_identical_to (const MaybeObjectHandle & other) const [inline]
Definition at line 270 of file maybe-handles-inl.h.
                                          {
  DirectHandle<Object> this_handle;
  Handle<Object> other_handle;
  return reference_type_ == other.reference_type_ &&
         handle_.ToHandle(&this_handle) ==
             other.handle_.ToHandle(&other_handle) &&
         this_handle.is_identical_to(other_handle);
}
References v8::internal::MaybeObjectHandle::handle_, handle_, v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::MaybeObjectHandle::reference_type_, and reference_type_.
is_null()
bool v8::internal::MaybeObjectDirectHandle::is_null () const [inline]
Definition at line 340 of file maybe-handles.h.
{ return handle_.is_null(); }
References handle_.
Referenced by v8::internal::FeedbackNexus::ConfigureMonomorphic(), v8::internal::MapsAndHandlers::emplace_back(), v8::internal::KeyedLoadIC::GetKeyedAccessLoadModeFor(), v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecksImpl(), v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::MapsAndHandlers::set_handler(), v8::internal::IC::ShouldRecomputeHandler(), and v8::internal::StoreHandler::StoreThroughPrototype().
object()
DirectHandle<Object> v8::internal::MaybeObjectDirectHandle::object () const [inline]
Definition at line 334 of file maybe-handles.h.
                                             {
    return handle_.ToHandleChecked();
  }
References handle_.
Referenced by v8::internal::MapsAndHandlers::emplace_back(), and v8::internal::MapsAndHandlers::set_handler().
operator*()
Tagged< MaybeObject > v8::internal::MaybeObjectDirectHandle::operator* () const [inline]
Definition at line 280 of file maybe-handles-inl.h.
                                                             {
  if (reference_type_ == HeapObjectReferenceType::WEAK) {
    return MakeWeak(*handle_.ToHandleChecked());
  } else {
    return *handle_.ToHandleChecked();
  }
}
References handle_, v8::internal::MakeWeak(), reference_type_, and WEAK.
operator->()
Tagged< MaybeObject > v8::internal::MaybeObjectDirectHandle::operator-> () const [inline]
Definition at line 288 of file maybe-handles-inl.h.
                                                              {
  if (reference_type_ == HeapObjectReferenceType::WEAK) {
    return MakeWeak(*handle_.ToHandleChecked());
  } else {
    return *handle_.ToHandleChecked();
  }
}
References handle_, v8::internal::MakeWeak(), reference_type_, and WEAK.
reference_type()
HeapObjectReferenceType v8::internal::MaybeObjectDirectHandle::reference_type () const [inline]
Definition at line 342 of file maybe-handles.h.
{ return reference_type_; }
References reference_type_.
Referenced by v8::internal::MapsAndHandlers::emplace_back(), and v8::internal::MapsAndHandlers::set_handler().
Weak() [1/2]
static MaybeObjectDirectHandle v8::internal::MaybeObjectDirectHandle::Weak (DirectHandle< Object > object) [inline], [static]
Definition at line 328 of file maybe-handles.h.
                                                                          {
    return MaybeObjectDirectHandle(object, HeapObjectReferenceType::WEAK);
  }
References MaybeObjectDirectHandle(), and WEAK.
Weak() [2/2]
MaybeObjectDirectHandle v8::internal::MaybeObjectDirectHandle::Weak (Tagged< Object > object, Isolate * isolate) [inline], [static]
Definition at line 254 of file maybe-handles-inl.h.
                                                                        {
  return MaybeObjectDirectHandle(object, HeapObjectReferenceType::WEAK,
                                 isolate);
}
References MaybeObjectDirectHandle(), and WEAK.
Referenced by v8::internal::Isolate::AddDetachedContext(), v8::internal::ObjectDeserializer::CommitPostProcessedObjects(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::BackgroundCompileTask::FinalizeScript(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::MapsAndHandlers::operator[](), v8::internal::Factory::ProcessNewScript(), v8::internal::StoreHandler::StoreProxy(), v8::internal::StoreHandler::StoreThroughPrototype(), v8::internal::IC::UpdateMegaDOMIC(), v8::internal::WasmMemoryObject::UseInInstance(), and v8::internal::Map::WrapFieldType().
Member Data Documentation
handle_
MaybeDirectHandle<Object> v8::internal::MaybeObjectDirectHandle::handle_ [private]
Definition at line 353 of file maybe-handles.h.
Referenced by is_identical_to(), is_null(), object(), operator*(), and operator->().
reference_type_
HeapObjectReferenceType v8::internal::MaybeObjectDirectHandle::reference_type_ [private]
Definition at line 352 of file maybe-handles.h.
Referenced by is_identical_to(), operator*(), operator->(), and reference_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/maybe-handles.h
/mnt/V8SourceCode/src/handles/maybe-handles-inl.h