v8::internal::wasm::ZoneBuffer Class Reference
#include <wasm-module-builder.h>
Classes
struct Buffer
Public Member Functions
ZoneBuffer (Zone *zone, size_t initial=kInitialSize)
void write_u8 (uint8_t x)
void write_u16 (uint16_t x)
void write_u32 (uint32_t x)
void write_u64 (uint64_t x)
void write_u32v (uint32_t val)
void write_u32v (ModuleTypeIndex index)
void write_i32v (int32_t val)
void write_u64v (uint64_t val)
void write_i64v (int64_t val)
void write_size (size_t val)
void write_f32 (float val)
void write_f64 (double val)
void write (const uint8_t *data, size_t size)
void write_string (base::Vector< const char > name)
size_t reserve_u32v ()
void patch_u32v (size_t offset, uint32_t val)
void patch_u8 (size_t offset, uint8_t val)
size_t offset () const
size_t size () const
uint8_t * data () const
uint8_t * begin () const
uint8_t * end () const
void EnsureSpace (size_t size)
void Truncate (size_t size)
uint8_t ** pos_ptr ()
Static Public Attributes
static constexpr size_t kInitialSize = 1024
Private Attributes
Zone * zone_
uint8_t * buffer_
uint8_t * pos_
uint8_t * end_
Detailed Description
Definition at line 28 of file wasm-module-builder.h.
Constructor & Destructor Documentation
ZoneBuffer()
v8::internal::wasm::ZoneBuffer::ZoneBuffer (Zone * zone, size_t initial = kInitialSize) [inline], [explicit]
Definition at line 34 of file wasm-module-builder.h.
      : zone_(zone), buffer_(zone->AllocateArray<uint8_t, Buffer>(initial)) {
    pos_ = buffer_;
    end_ = buffer_ + initial;
  }
References buffer_, end_, and pos_.
Member Function Documentation
begin()
uint8_t* v8::internal::wasm::ZoneBuffer::begin () const [inline]
Definition at line 137 of file wasm-module-builder.h.
{ return buffer_; }
References buffer_.
Referenced by v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable(), and v8::internal::wasm::WasmFunctionBuilder::WriteBody().
data()
uint8_t* v8::internal::wasm::ZoneBuffer::data () const [inline]
Definition at line 136 of file wasm-module-builder.h.
{ return buffer_; }
References buffer_.
Referenced by write().
end()
uint8_t* v8::internal::wasm::ZoneBuffer::end () const [inline]
Definition at line 138 of file wasm-module-builder.h.
{ return pos_; }
References pos_.
EnsureSpace()
void v8::internal::wasm::ZoneBuffer::EnsureSpace (size_t size) [inline]
Definition at line 140 of file wasm-module-builder.h.
                                {
    if ((pos_ + size) > end_) {
      size_t new_size = size + (end_ - buffer_) * 2;
      uint8_t* new_buffer = zone_->AllocateArray<uint8_t, Buffer>(new_size);
      memcpy(new_buffer, buffer_, (pos_ - buffer_));
      pos_ = new_buffer + (pos_ - buffer_);
      buffer_ = new_buffer;
      end_ = new_buffer + new_size;
    }
    DCHECK(pos_ + size <= end_);
  }
References v8::internal::Zone::AllocateArray(), buffer_, v8::internal::DCHECK(), end_, pos_, size(), and zone_.
Referenced by reserve_u32v(), write(), write_i32v(), write_i64v(), write_size(), write_u16(), write_u32(), write_u32v(), write_u64(), write_u64v(), write_u8(), and v8::internal::wasm::WasmFunctionBuilder::WriteBody().
offset()
size_t v8::internal::wasm::ZoneBuffer::offset () const [inline]
Definition at line 134 of file wasm-module-builder.h.
{ return static_cast<size_t>(pos_ - buffer_); }
References buffer_, and pos_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::FixupSection(), patch_u32v(), patch_u8(), reserve_u32v(), Truncate(), v8::internal::wasm::WasmFunctionBuilder::WriteBody(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
patch_u32v()
void v8::internal::wasm::ZoneBuffer::patch_u32v (size_t offset, uint32_t val) [inline]
Definition at line 115 of file wasm-module-builder.h.
                                               {
    uint8_t* ptr = buffer_ + offset;
    for (size_t pos = 0; pos != kPaddedVarInt32Size; ++pos) {
      uint32_t next = val >> 7;
      uint8_t out = static_cast<uint8_t>(val & 0x7f);
      if (pos != kPaddedVarInt32Size - 1) {
        *(ptr++) = 0x80 | out;
        val = next;
      } else {
        *(ptr++) = out;
      }
    }
  }
References buffer_, v8::internal::wasm::kPaddedVarInt32Size, and offset().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::FixupSection(), and v8::internal::wasm::WasmFunctionBuilder::WriteBody().
patch_u8()
void v8::internal::wasm::ZoneBuffer::patch_u8 (size_t offset, uint8_t val) [inline]
Definition at line 129 of file wasm-module-builder.h.
                                            {
    DCHECK_GE(size(), offset);
    buffer_[offset] = val;
  }
References buffer_, DCHECK_GE, offset(), and size().
pos_ptr()
uint8_t** v8::internal::wasm::ZoneBuffer::pos_ptr () [inline]
Definition at line 157 of file wasm-module-builder.h.
{ return &pos_; }
References pos_.
Referenced by v8::internal::wasm::WasmFunctionBuilder::WriteBody().
reserve_u32v()
size_t v8::internal::wasm::ZoneBuffer::reserve_u32v () [inline]
Definition at line 107 of file wasm-module-builder.h.
                        {
    size_t off = offset();
    EnsureSpace(kMaxVarInt32Size);
    pos_ += kMaxVarInt32Size;
    return off;
  }
References EnsureSpace(), v8::internal::wasm::kMaxVarInt32Size, offset(), and pos_.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::EmitSection(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
size()
size_t v8::internal::wasm::ZoneBuffer::size () const [inline]
Definition at line 135 of file wasm-module-builder.h.
{ return static_cast<size_t>(pos_ - buffer_); }
References buffer_, and pos_.
Referenced by v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset(), v8::internal::wasm::WasmFunctionBuilder::DeleteCodeAfter(), v8::internal::wasm::WasmFunctionBuilder::EmitDirectCallIndex(), EnsureSpace(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), patch_u8(), v8::internal::wasm::WasmFunctionBuilder::SetAsmFunctionStartPosition(), Truncate(), write(), v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable(), and v8::internal::wasm::WasmFunctionBuilder::WriteBody().
Truncate()
void v8::internal::wasm::ZoneBuffer::Truncate (size_t size) [inline]
Definition at line 152 of file wasm-module-builder.h.
                             {
    DCHECK_GE(offset(), size);
    pos_ = buffer_ + size;
  }
References buffer_, DCHECK_GE, offset(), pos_, and size().
Referenced by v8::internal::wasm::WasmFunctionBuilder::DeleteCodeAfter().
write()
void v8::internal::wasm::ZoneBuffer::write (const uint8_t * data, size_t size) [inline]
Definition at line 95 of file wasm-module-builder.h.
                                               {
    if (size == 0) return;
    EnsureSpace(size);
    memcpy(pos_, data, size);
    pos_ += size;
  }
References data(), EnsureSpace(), pos_, and size().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitCode(), write_string(), v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable(), v8::internal::wasm::WasmFunctionBuilder::WriteBody(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
write_f32()
void v8::internal::wasm::ZoneBuffer::write_f32 (float val) [inline]
Definition at line 91 of file wasm-module-builder.h.
{ write_u32(base::bit_cast<uint32_t>(val)); }
References write_u32().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitF32Const(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
write_f64()
void v8::internal::wasm::ZoneBuffer::write_f64 (double val) [inline]
Definition at line 93 of file wasm-module-builder.h.
{ write_u64(base::bit_cast<uint64_t>(val)); }
References write_u64().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitF64Const(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
write_i32v()
void v8::internal::wasm::ZoneBuffer::write_i32v (int32_t val) [inline]
Definition at line 70 of file wasm-module-builder.h.
                               {
    EnsureSpace(kMaxVarInt32Size);
    LEBHelper::write_i32v(&pos_, val);
  }
References EnsureSpace(), v8::internal::wasm::kMaxVarInt32Size, pos_, and v8::internal::wasm::LEBHelper::write_i32v().
Referenced by v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset(), v8::internal::wasm::WasmFunctionBuilder::EmitI32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithI32V(), v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteHeapType(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
write_i64v()
void v8::internal::wasm::ZoneBuffer::write_i64v (int64_t val) [inline]
Definition at line 80 of file wasm-module-builder.h.
                               {
    EnsureSpace(kMaxVarInt64Size);
    LEBHelper::write_i64v(&pos_, val);
  }
References EnsureSpace(), v8::internal::wasm::kMaxVarInt64Size, pos_, and v8::internal::wasm::LEBHelper::write_i64v().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitI64Const(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
write_size()
void v8::internal::wasm::ZoneBuffer::write_size (size_t val) [inline]
Definition at line 85 of file wasm-module-builder.h.
                              {
    EnsureSpace(kMaxVarInt32Size);
    DCHECK_EQ(val, static_cast<uint32_t>(val));
    LEBHelper::write_u32v(&pos_, static_cast<uint32_t>(val));
  }
References DCHECK_EQ, EnsureSpace(), v8::internal::wasm::kMaxVarInt32Size, pos_, and v8::internal::wasm::LEBHelper::write_u32v().
Referenced by write_string(), v8::internal::wasm::WasmModuleBuilder::WriteAsmJsOffsetTable(), v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable(), v8::internal::wasm::WasmFunctionBuilder::WriteBody(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
write_string()
void v8::internal::wasm::ZoneBuffer::write_string (base::Vector< const char > name) [inline]
Definition at line 102 of file wasm-module-builder.h.
                                                 {
    write_size(name.length());
    write(reinterpret_cast<const uint8_t*>(name.begin()), name.length());
  }
References v8::internal::wasm::name(), write(), and write_size().
Referenced by v8::internal::wasm::WasmModuleBuilder::WriteTo().
write_u16()
void v8::internal::wasm::ZoneBuffer::write_u16 (uint16_t x) [inline]
Definition at line 45 of file wasm-module-builder.h.
                             {
    EnsureSpace(2);
    base::WriteLittleEndianValue<uint16_t>(reinterpret_cast<Address>(pos_), x);
    pos_ += 2;
  }
References EnsureSpace(), and pos_.
write_u32()
void v8::internal::wasm::ZoneBuffer::write_u32 (uint32_t x) [inline]
Definition at line 51 of file wasm-module-builder.h.
                             {
    EnsureSpace(4);
    base::WriteLittleEndianValue<uint32_t>(reinterpret_cast<Address>(pos_), x);
    pos_ += 4;
  }
References EnsureSpace(), and pos_.
Referenced by write_f32(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
write_u32v() [1/2]
void v8::internal::wasm::ZoneBuffer::write_u32v (ModuleTypeIndex index) [inline]
Definition at line 68 of file wasm-module-builder.h.
{ write_u32v(index.index); }
References v8::internal::index, and write_u32v().
Referenced by write_u32v().
write_u32v() [2/2]
void v8::internal::wasm::ZoneBuffer::write_u32v (uint32_t val) [inline]
Definition at line 63 of file wasm-module-builder.h.
                                {
    EnsureSpace(kMaxVarInt32Size);
    LEBHelper::write_u32v(&pos_, val);
  }
References EnsureSpace(), v8::internal::wasm::kMaxVarInt32Size, pos_, and v8::internal::wasm::LEBHelper::write_u32v().
Referenced by v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset(), v8::internal::wasm::WasmFunctionBuilder::EmitU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback(), v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd(), v8::internal::wasm::WasmFunctionBuilder::WriteSignature(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
write_u64()
void v8::internal::wasm::ZoneBuffer::write_u64 (uint64_t x) [inline]
Definition at line 57 of file wasm-module-builder.h.
                             {
    EnsureSpace(8);
    base::WriteLittleEndianValue<uint64_t>(reinterpret_cast<Address>(pos_), x);
    pos_ += 8;
  }
References EnsureSpace(), and pos_.
Referenced by write_f64().
write_u64v()
void v8::internal::wasm::ZoneBuffer::write_u64v (uint64_t val) [inline]
Definition at line 75 of file wasm-module-builder.h.
                                {
    EnsureSpace(kMaxVarInt64Size);
    LEBHelper::write_u64v(&pos_, val);
  }
References EnsureSpace(), v8::internal::wasm::kMaxVarInt64Size, pos_, and v8::internal::wasm::LEBHelper::write_u64v().
Referenced by v8::internal::wasm::WasmFunctionBuilder::EmitU64V(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
write_u8()
void v8::internal::wasm::ZoneBuffer::write_u8 (uint8_t x) [inline]
Definition at line 40 of file wasm-module-builder.h.
                           {
    EnsureSpace(1);
    *(pos_++) = x;
  }
References EnsureSpace(), and pos_.
Referenced by v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitByte(), v8::internal::wasm::WasmFunctionBuilder::EmitF32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitF64Const(), v8::internal::wasm::WasmFunctionBuilder::EmitI64Const(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::EmitSection(), v8::internal::wasm::WasmFunctionBuilder::EmitWithI32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8U8(), v8::internal::wasm::ProfileGenerator::SerializeTieringInfo(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteHeapType(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpression(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd(), v8::internal::wasm::WasmModuleBuilder::WriteTo(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteValueType().
Member Data Documentation
buffer_
uint8_t* v8::internal::wasm::ZoneBuffer::buffer_ [private]
Definition at line 161 of file wasm-module-builder.h.
Referenced by begin(), data(), EnsureSpace(), offset(), patch_u32v(), patch_u8(), size(), Truncate(), and ZoneBuffer().
end_
uint8_t* v8::internal::wasm::ZoneBuffer::end_ [private]
Definition at line 163 of file wasm-module-builder.h.
Referenced by EnsureSpace(), and ZoneBuffer().
kInitialSize
constexpr size_t v8::internal::wasm::ZoneBuffer::kInitialSize = 1024 [static], [constexpr]
Definition at line 33 of file wasm-module-builder.h.
pos_
uint8_t* v8::internal::wasm::ZoneBuffer::pos_ [private]
Definition at line 162 of file wasm-module-builder.h.
Referenced by end(), EnsureSpace(), offset(), pos_ptr(), reserve_u32v(), size(), Truncate(), write(), write_i32v(), write_i64v(), write_size(), write_u16(), write_u32(), write_u32v(), write_u64(), write_u64v(), write_u8(), and ZoneBuffer().
zone_
Zone* v8::internal::wasm::ZoneBuffer::zone_ [private]
Definition at line 160 of file wasm-module-builder.h.
Referenced by EnsureSpace().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-module-builder.h