v8::internal::Execution Class Reference
#include <execution.h>
Public Types
enum class MessageHandling { kReport
, kKeepPending
 }
enum class Target { kCallable
, kRunMicrotasks
 }
Static Public Member Functions
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Object > Call (Isolate *isolate, DirectHandle< Object > callable, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT MaybeHandle< Object > CallScript (Isolate *isolate, DirectHandle< JSFunction > callable, DirectHandle< Object > receiver, DirectHandle< Object > host_defined_options)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > CallBuiltin (Isolate *isolate, DirectHandle< JSFunction > builtin, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > New (Isolate *isolate, DirectHandle< Object > constructor, base::Vector< const DirectHandle< Object >> args)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > New (Isolate *isolate, DirectHandle< Object > constructor, DirectHandle< Object > new_target, base::Vector< const DirectHandle< Object >> args)
static V8_EXPORT_PRIVATE MaybeDirectHandle< Object > TryCall (Isolate *isolate, DirectHandle< Object > callable, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args, MessageHandling message_handling, MaybeDirectHandle< Object > *exception_out)
static V8_EXPORT_PRIVATE MaybeDirectHandle< Object > TryCallScript (Isolate *isolate, DirectHandle< JSFunction > script_function, DirectHandle< Object > receiver, DirectHandle< FixedArray > host_defined_options)
static MaybeDirectHandle< Object > TryRunMicrotasks (Isolate *isolate, MicrotaskQueue *microtask_queue)
Detailed Description
Definition at line 16 of file execution.h.
Member Enumeration Documentation
MessageHandling
enum v8::internal::Execution::MessageHandling [strong]
Enumerator
kReport
kKeepPending
Definition at line 19 of file execution.h.
{ kReport, kKeepPending };
Target
enum v8::internal::Execution::Target [strong]
Enumerator
kCallable
kRunMicrotasks
Definition at line 20 of file execution.h.
{ kCallable, kRunMicrotasks };
Member Function Documentation
Call()
MaybeHandle< Object > v8::internal::Execution::Call (Isolate * isolate, DirectHandle< Object > callable, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args) [static]
Definition at line 525 of file execution.cc.
                                                 {
  // Use Execution::CallScript instead for scripts:
  DCHECK_IMPLIES(IsJSFunction(*callable),
                 !Cast<JSFunction>(*callable)->shared()->is_script());
  return Invoke(isolate,
                InvokeParams::SetUpForCall(isolate, callable, receiver, args));
}
References v8::base::args, DCHECK_IMPLIES, and v8::internal::anonymous_namespace{execution.cc}::Invoke().
Referenced by v8::internal::JsonStringifier::ApplyReplacerFunction(), v8::internal::JsonStringifier::ApplyToJsonFunction(), v8::internal::BUILTIN(), v8::Function::Call(), v8::Object::CallAsFunction(), v8::debug::CallFunctionOn(), v8::internal::JSFinalizationRegistry::Cleanup(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::JSDisposableStackBase::DisposeResources(), v8::internal::DebugEvaluate::Evaluate(), v8::internal::wasm::InstanceBuilder::ExecuteStartFunction(), v8::internal::ErrorUtils::FormatStackTrace(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::Runtime::GetPrivateMember(), v8::internal::JSProxy::GetProperty(), v8::internal::Object::GetPropertyWithDefinedGetter(), v8::internal::JSProxy::GetPrototype(), v8::internal::JSProxy::HasProperty(), v8::internal::Object::InstanceOf(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::JSProxy::IsExtensible(), v8::internal::JSProxy::PreventExtensions(), v8::internal::ValueDeserializer::ReadJSMap(), v8::internal::ValueDeserializer::ReadJSSet(), v8::internal::RegExpUtils::RegExpExec(), v8::internal::requires(), v8::internal::SourceTextModule::RunInitializationCode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Runtime::SetPrivateMember(), v8::internal::JSProxy::SetProperty(), v8::internal::Object::SetPropertyWithDefinedSetter(), and v8::internal::JSProxy::SetPrototype().
CallBuiltin()
MaybeHandle< Object > v8::internal::Execution::CallBuiltin (Isolate * isolate, DirectHandle< JSFunction > builtin, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args) [static]
Definition at line 547 of file execution.cc.
                                                 {
  DCHECK(builtin->code(isolate)->is_builtin());
  DisableBreak no_break(isolate->debug());
  return Invoke(isolate,
                InvokeParams::SetUpForCall(isolate, builtin, receiver, args));
}
References v8::base::args, v8::internal::DCHECK(), v8::internal::Isolate::debug(), and v8::internal::anonymous_namespace{execution.cc}::Invoke().
Referenced by v8::Set::Add(), v8::Promise::Catch(), v8::Map::Delete(), v8::Set::Delete(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::anonymous_namespace{builtins-console.cc}::Formatter(), v8::Function::FunctionProtoToString(), v8::Map::Get(), v8::Map::Has(), v8::Set::Has(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::Object::ObjectProtoToString(), v8::internal::JSDisposableStackBase::ResolveAPromiseWithValueAndReturnIt(), v8::Map::Set(), and v8::Promise::Then().
CallScript()
MaybeHandle< Object > v8::internal::Execution::CallScript (Isolate * isolate, DirectHandle< JSFunction > callable, DirectHandle< Object > receiver, DirectHandle< Object > host_defined_options) [static]
Definition at line 537 of file execution.cc.
                                                                              {
  DCHECK(script_function->shared()->is_script());
  DCHECK(IsJSGlobalProxy(*receiver) || IsJSGlobalObject(*receiver));
  return Invoke(isolate,
                InvokeParams::SetUpForCall(isolate, script_function, receiver,
                                           {&host_defined_options, 1}));
}
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{execution.cc}::Invoke().
Referenced by v8::internal::DebugEvaluate::Global(), and v8::Script::Run().
New() [1/2]
MaybeDirectHandle< JSReceiver > v8::internal::Execution::New (Isolate * isolate, DirectHandle< Object > constructor, base::Vector< const DirectHandle< Object >> args) [static]
Definition at line 558 of file execution.cc.
                                                 {
  return New(isolate, constructor, constructor, args);
}
References v8::base::args.
Referenced by v8::Object::CallAsConstructor(), v8::Function::NewInstanceWithSideEffectType(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SliceHelper(), and v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
New() [2/2]
MaybeDirectHandle< JSReceiver > v8::internal::Execution::New (Isolate * isolate, DirectHandle< Object > constructor, DirectHandle< Object > new_target, base::Vector< const DirectHandle< Object >> args) [static]
Definition at line 565 of file execution.cc.
                                                 {
  return Cast<JSReceiver>(Invoke(
      isolate,
      InvokeParams::SetUpForNew(isolate, constructor, new_target, args)));
}
References v8::base::args, and v8::internal::anonymous_namespace{execution.cc}::Invoke().
TryCall()
MaybeDirectHandle< Object > v8::internal::Execution::TryCall (Isolate * isolate, DirectHandle< Object > callable, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args, MessageHandling message_handling, MaybeDirectHandle< Object > * exception_out) [static]
Definition at line 589 of file execution.cc.
                                              {
  // Use Execution::TryCallScript instead for scripts:
  DCHECK_IMPLIES(IsJSFunction(*callable),
                 !Cast<JSFunction>(*callable)->shared()->is_script());
  return InvokeWithTryCatch(
      isolate, InvokeParams::SetUpForTryCall(isolate, callable, receiver, args,
                                             message_handling, exception_out));
}
References v8::base::args, DCHECK_IMPLIES, and v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch().
Referenced by v8::internal::SourceTextModule::ExecuteModule(), and v8::internal::SourceTextModule::InnerExecuteAsyncModule().
TryCallScript()
MaybeDirectHandle< Object > v8::internal::Execution::TryCallScript (Isolate * isolate, DirectHandle< JSFunction > script_function, DirectHandle< Object > receiver, DirectHandle< FixedArray > host_defined_options) [static]
Definition at line 575 of file execution.cc.
                                                   {
  DCHECK(script_function->shared()->is_script());
  DCHECK(IsJSGlobalProxy(*receiver) || IsJSGlobalObject(*receiver));
  DirectHandle<Object> argument = host_defined_options;
  return InvokeWithTryCatch(
      isolate, InvokeParams::SetUpForTryCall(
                   isolate, script_function, receiver, {&argument, 1},
                   MessageHandling::kKeepPending, nullptr));
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), and kKeepPending.
Referenced by v8::internal::Genesis::CompileExtension().
TryRunMicrotasks()
MaybeDirectHandle< Object > v8::internal::Execution::TryRunMicrotasks (Isolate * isolate, MicrotaskQueue * microtask_queue) [static]
Definition at line 604 of file execution.cc.
                                                       {
  return InvokeWithTryCatch(
      isolate, InvokeParams::SetUpForRunMicrotasks(isolate, microtask_queue));
}
References v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch().
Referenced by v8::internal::MicrotaskQueue::RunMicrotasks().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/execution.h
/mnt/V8SourceCode/src/execution/execution.cc