v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits > Class Template Reference
#include <pointer-with-payload.h>
Public Member Functions
PointerWithPayload ()=default
PointerWithPayload (PointerType *pointer)
PointerWithPayload (PayloadType payload)
PointerWithPayload (PointerType *pointer, PayloadType payload)
PointerType * GetPointer () const
PointerType * GetPointerWithKnownPayload (PayloadType payload) const
PointerType * operator-> () const
void Update (PointerType *new_pointer, PayloadType new_payload)
void SetPointer (PointerType *newptr)
PayloadType GetPayload () const
void SetPayload (PayloadType new_payload)
uintptr_t raw () const
Private Attributes
uintptr_t pointer_with_payload_ = 0
Static Private Attributes
static constexpr int kAvailableBits
static constexpr uintptr_t kPayloadMask
static constexpr uintptr_t kPointerMask = ~kPayloadMask
Detailed Description
template<typename PointerType, typename PayloadType, int NumPayloadBits>
class v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >
Definition at line 40 of file pointer-with-payload.h.
Constructor & Destructor Documentation
PointerWithPayload() [1/4]
template<typename PointerType , typename PayloadType , int NumPayloadBits>
v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload () [default]
PointerWithPayload() [2/4]
template<typename PointerType , typename PayloadType , int NumPayloadBits>
v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload (PointerType * pointer) [inline], [explicit]
Definition at line 44 of file pointer-with-payload.h.
      : pointer_with_payload_(reinterpret_cast<uintptr_t>(pointer)) {
    DCHECK_EQ(GetPointer(), pointer);
    DCHECK_EQ(GetPayload(), static_cast<PayloadType>(0));
  }
References DCHECK_EQ, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer().
PointerWithPayload() [3/4]
template<typename PointerType , typename PayloadType , int NumPayloadBits>
v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload (PayloadType payload) [inline], [explicit]
Definition at line 50 of file pointer-with-payload.h.
      : pointer_with_payload_(static_cast<uintptr_t>(payload)) {
    DCHECK_EQ(GetPointer(), nullptr);
    DCHECK_EQ(GetPayload(), payload);
  }
References DCHECK_EQ, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer().
PointerWithPayload() [4/4]
template<typename PointerType , typename PayloadType , int NumPayloadBits>
v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload (PointerType * pointer, PayloadType payload) [inline]
Definition at line 56 of file pointer-with-payload.h.
                                                                {
    Update(pointer, payload);
  }
References v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::Update().
Member Function Documentation
GetPayload()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
PayloadType v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload () const [inline]
Definition at line 87 of file pointer-with-payload.h.
                                           {
    return static_cast<PayloadType>(pointer_with_payload_ & kPayloadMask);
  }
References v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPayloadMask, and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
Referenced by v8::internal::ZoneCompactSet< T >::at(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointerWithKnownPayload(), v8::internal::ZoneCompactSet< T >::is_list(), v8::internal::ZoneCompactSet< T >::is_singleton(), v8::internal::maglev::LoadMergeState(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPayload(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::Update().
GetPointer()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
PointerType* v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer () const [inline]
Definition at line 60 of file pointer-with-payload.h.
                                            {
    return reinterpret_cast<PointerType*>(pointer_with_payload_ & kPointerMask);
  }
References v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPointerMask, and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
Referenced by v8::internal::maglev::LoadMergeState(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::operator->(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPointer(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::Update().
GetPointerWithKnownPayload()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
PointerType* v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointerWithKnownPayload (PayloadType payload) const [inline]
Definition at line 65 of file pointer-with-payload.h.
                                                                               {
    DCHECK_EQ(GetPayload(), payload);
    return reinterpret_cast<PointerType*>(pointer_with_payload_ -
                                          static_cast<uintptr_t>(payload));
  }
References DCHECK_EQ, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
Referenced by v8::internal::ZoneCompactSet< T >::list(), and v8::internal::ZoneCompactSet< T >::singleton().
operator->()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
PointerType* v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::operator-> () const [inline]
Definition at line 71 of file pointer-with-payload.h.
{ return GetPointer(); }
References v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer().
raw()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
uintptr_t v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::raw () const [inline]
Definition at line 99 of file pointer-with-payload.h.
{ return pointer_with_payload_; }
References v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
Referenced by v8::base::operator==().
SetPayload()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
void v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPayload (PayloadType new_payload) [inline]
Definition at line 91 of file pointer-with-payload.h.
                                                     {
    uintptr_t new_payload_ptr = static_cast<uintptr_t>(new_payload);
    DCHECK_EQ(new_payload_ptr & kPayloadMask, new_payload_ptr);
    pointer_with_payload_ =
        (pointer_with_payload_ & kPointerMask) | new_payload_ptr;
    DCHECK_EQ(GetPayload(), new_payload);
  }
References DCHECK_EQ, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPayloadMask, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPointerMask, and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
SetPointer()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
void v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPointer (PointerType * newptr) [inline]
Definition at line 80 of file pointer-with-payload.h.
                                                 {
    DCHECK_EQ(reinterpret_cast<uintptr_t>(newptr) & kPayloadMask, 0);
    pointer_with_payload_ = reinterpret_cast<uintptr_t>(newptr) |
                            (pointer_with_payload_ & kPayloadMask);
    DCHECK_EQ(GetPointer(), newptr);
  }
References DCHECK_EQ, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPayloadMask, and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
Update()
template<typename PointerType , typename PayloadType , int NumPayloadBits>
void v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::Update (PointerType * new_pointer, PayloadType new_payload) [inline]
Definition at line 73 of file pointer-with-payload.h.
                                                                           {
    pointer_with_payload_ = reinterpret_cast<uintptr_t>(new_pointer) |
                            static_cast<uintptr_t>(new_payload);
    DCHECK_EQ(GetPayload(), new_payload);
    DCHECK_EQ(GetPointer(), new_pointer);
  }
References DCHECK_EQ, v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_.
Referenced by v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::PointerWithPayload().
Member Data Documentation
kAvailableBits
template<typename PointerType , typename PayloadType , int NumPayloadBits>
constexpr int v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kAvailableBits [static], [constexpr], [private]
Initial value:
= PointerWithPayloadTraits<
      std::remove_const_t<PointerType>>::kAvailableBits
Definition at line 102 of file pointer-with-payload.h.
kPayloadMask
template<typename PointerType , typename PayloadType , int NumPayloadBits>
constexpr uintptr_t v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPayloadMask [static], [constexpr], [private]
Initial value:
=
      (uintptr_t{1} << NumPayloadBits) - 1
Definition at line 110 of file pointer-with-payload.h.
Referenced by v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPayload(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPointer().
kPointerMask
template<typename PointerType , typename PayloadType , int NumPayloadBits>
constexpr uintptr_t v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::kPointerMask = ~kPayloadMask [static], [constexpr], [private]
Definition at line 112 of file pointer-with-payload.h.
Referenced by v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPayload().
pointer_with_payload_
template<typename PointerType , typename PayloadType , int NumPayloadBits>
uintptr_t v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::pointer_with_payload_ = 0 [private]
Definition at line 114 of file pointer-with-payload.h.
Referenced by v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointer(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::GetPointerWithKnownPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::raw(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPayload(), v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::SetPointer(), and v8::base::PointerWithPayload< PointerType, PayloadType, NumPayloadBits >::Update().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/pointer-with-payload.h