v8::internal::compiler::CreateClosureParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateClosureParameters (SharedFunctionInfoRef shared_info, CodeRef code, AllocationType allocation)
SharedFunctionInfoRef shared_info () const
CodeRef code () const
AllocationType allocation () const
Private Attributes
const SharedFunctionInfoRef shared_info_
const CodeRef code_
AllocationType const allocation_
Friends
bool operator== (CreateClosureParameters const &, CreateClosureParameters const &)
bool operator!= (CreateClosureParameters const &, CreateClosureParameters const &)
size_t hash_value (CreateClosureParameters const &)
std::ostream & operator<< (std::ostream &, CreateClosureParameters const &)
Detailed Description
Definition at line 676 of file js-operator.h.
Constructor & Destructor Documentation
CreateClosureParameters()
v8::internal::compiler::CreateClosureParameters::CreateClosureParameters (SharedFunctionInfoRef shared_info, CodeRef code, AllocationType allocation) [inline]
Definition at line 678 of file js-operator.h.
      : shared_info_(shared_info), code_(code), allocation_(allocation) {}
Member Function Documentation
allocation()
AllocationType v8::internal::compiler::CreateClosureParameters::allocation () const [inline]
Definition at line 684 of file js-operator.h.
{ return allocation_; }
References allocation_.
code()
CodeRef v8::internal::compiler::CreateClosureParameters::code () const [inline]
Definition at line 683 of file js-operator.h.
{ return code_; }
References code_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure().
shared_info()
SharedFunctionInfoRef v8::internal::compiler::CreateClosureParameters::shared_info () const [inline]
Definition at line 682 of file js-operator.h.
{ return shared_info_; }
References shared_info_.
Referenced by v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), and v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor().
Friends And Related Function Documentation
hash_value
size_t hash_value (CreateClosureParameters const & p) [friend]
Definition at line 567 of file js-operator.cc.
                                                    {
  return base::hash_combine(p.allocation(), p.code_.object().location(),
                            p.shared_info_.object().location());
}
operator!=
bool operator!= (CreateClosureParameters const & lhs, CreateClosureParameters const & rhs) [friend]
Definition at line 561 of file js-operator.cc.
                                                    {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, CreateClosureParameters const & p) [friend]
Definition at line 573 of file js-operator.cc.
                                                                         {
  return os << p.allocation() << ", " << Brief(*p.shared_info_.object()) << ", "
            << Brief(*p.code_.object());
}
operator==
bool operator== (CreateClosureParameters const & lhs, CreateClosureParameters const & rhs) [friend]
Definition at line 552 of file js-operator.cc.
                                                    {
  return lhs.allocation() == rhs.allocation() &&
         lhs.code_.object().location() == rhs.code_.object().location() &&
         lhs.shared_info_.object().location() ==
             rhs.shared_info_.object().location();
}
Member Data Documentation
allocation_
AllocationType const v8::internal::compiler::CreateClosureParameters::allocation_ [private]
Definition at line 689 of file js-operator.h.
Referenced by allocation().
code_
const CodeRef v8::internal::compiler::CreateClosureParameters::code_ [private]
Definition at line 688 of file js-operator.h.
Referenced by code().
shared_info_
const SharedFunctionInfoRef v8::internal::compiler::CreateClosureParameters::shared_info_ [private]
Definition at line 687 of file js-operator.h.
Referenced by shared_info().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h