v8::internal::compiler::Operator Class Reference
#include <operator.h>
Public Types
enum Property {
kNoProperties = 0
, kCommutative = 1 << 0
, kAssociative = 1 << 1
, kIdempotent = 1 << 2
,
kNoRead = 1 << 3
, kNoWrite = 1 << 4
, kNoThrow = 1 << 5
, kNoDeopt = 1 << 6
,
kFoldable = kNoRead | kNoWrite
, kEliminatable = kNoDeopt | kNoWrite | kNoThrow
, kKontrol = kNoDeopt | kFoldable | kNoThrow
, kPure = kKontrol | kIdempotent
 }
enum class PrintVerbosity { kVerbose
, kSilent
 }
using Opcode = uint16_t
using Properties = base::Flags< Property, uint8_t >
Public Member Functions
Operator (Opcode opcode, Properties properties, const char *mnemonic, size_t value_in, size_t effect_in, size_t control_in, size_t value_out, size_t effect_out, size_t control_out)
Operator (const Operator &)=delete
Operator & operator= (const Operator &)=delete
virtual ~Operator ()=default
constexpr Opcode opcode () const
const char * mnemonic () const
virtual bool Equals (const Operator *that) const
virtual size_t HashCode () const
bool HasProperty (Property property) const
Properties properties () const
int ValueInputCount () const
int EffectInputCount () const
int ControlInputCount () const
int ValueOutputCount () const
int EffectOutputCount () const
int ControlOutputCount () const
void PrintTo (std::ostream &os, PrintVerbosity verbose=PrintVerbosity::kVerbose) const
void PrintPropsTo (std::ostream &os) const
Static Public Member Functions
static size_t ZeroIfEliminatable (Properties properties)
static size_t ZeroIfNoThrow (Properties properties)
static size_t ZeroIfPure (Properties properties)
Protected Member Functions
virtual void PrintToImpl (std::ostream &os, PrintVerbosity verbose) const
Private Attributes
const char * mnemonic_
Opcode opcode_
Properties properties_
uint32_t value_in_
uint32_t effect_in_
uint32_t control_in_
uint32_t value_out_
uint8_t effect_out_
uint32_t control_out_
Detailed Description
Definition at line 33 of file operator.h.
Member Typedef Documentation
Opcode
using v8::internal::compiler::Operator::Opcode = uint16_t
Definition at line 35 of file operator.h.
Properties
using v8::internal::compiler::Operator::Properties = base::Flags<Property, uint8_t>
Definition at line 60 of file operator.h.
Member Enumeration Documentation
PrintVerbosity
enum v8::internal::compiler::Operator::PrintVerbosity [strong]
Enumerator
kVerbose
kSilent
Definition at line 61 of file operator.h.
{ kVerbose, kSilent };
Property
enum v8::internal::compiler::Operator::Property
Enumerator
kNoProperties
kCommutative
kAssociative
kIdempotent
kNoRead
kNoWrite
kNoThrow
kNoDeopt
kFoldable
kEliminatable
kKontrol
kPure
Definition at line 39 of file operator.h.
                {
    kNoProperties = 0,
    kCommutative = 1 << 0, // OP(a, b) == OP(b, a) for all inputs.
    kAssociative = 1 << 1, // OP(a, OP(b,c)) == OP(OP(a,b), c) for all inputs.
    kIdempotent = 1 << 2, // OP(a); OP(a) == OP(a).
    kNoRead = 1 << 3, // Has no scheduling dependency on Effects
    kNoWrite = 1 << 4, // Does not modify any Effects and thereby
                            // create new scheduling dependencies.
    kNoThrow = 1 << 5, // Can never generate an exception.
    kNoDeopt = 1 << 6, // Can never generate an eager deoptimization exit.
    kFoldable = kNoRead | kNoWrite,
    kEliminatable = kNoDeopt | kNoWrite | kNoThrow,
    kKontrol = kNoDeopt | kFoldable | kNoThrow,
    kPure = kKontrol | kIdempotent
  };
Constructor & Destructor Documentation
Operator() [1/2]
v8::internal::compiler::Operator::Operator (Opcode opcode, Properties properties, const char * mnemonic, size_t value_in, size_t effect_in, size_t control_in, size_t value_out, size_t effect_out, size_t control_out)
Definition at line 27 of file operator.cc.
    : mnemonic_(mnemonic),
      opcode_(opcode),
      properties_(properties),
      value_in_(CheckRange<uint32_t>(value_in)),
      effect_in_(CheckRange<uint32_t>(effect_in)),
      control_in_(CheckRange<uint32_t>(control_in)),
      value_out_(CheckRange<uint32_t>(value_out)),
      effect_out_(CheckRange<uint8_t>(effect_out)),
      control_out_(CheckRange<uint32_t>(control_out)) {}
Operator() [2/2]
v8::internal::compiler::Operator::Operator (const Operator &) [delete]
 Operator()
virtual v8::internal::compiler::Operator::~Operator () [virtual], [default]
Member Function Documentation
ControlInputCount()
int v8::internal::compiler::Operator::ControlInputCount () const [inline]
Definition at line 103 of file operator.h.
{ return control_in_; }
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::OperatorProperties::GetTotalInputCount(), v8::internal::compiler::RepresentationChanger::InsertConversion(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::BytecodeGraphBuilder::MakeNode(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::BytecodeGraphBuilder::MergeControl(), v8::internal::compiler::BytecodeGraphBuilder::MergeEffect(), v8::internal::compiler::BytecodeGraphBuilder::MergeValue(), v8::internal::compiler::NodeProperties::PastControlIndex(), v8::internal::compiler::GraphC1Visualizer::PrintInputs(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::DeadCodeElimination::PropagateDeadControl(), v8::internal::compiler::WasmGCOperatorReducer::Reduce(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), v8::internal::compiler::BranchElimination::ReduceOtherControl(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::LoopVariableOptimizer::Run(), v8::internal::compiler::LoopVariableOptimizer::VisitBackedge(), and v8::internal::compiler::LoopVariableOptimizer::VisitOtherControl().
ControlOutputCount()
int v8::internal::compiler::Operator::ControlOutputCount () const [inline]
Definition at line 107 of file operator.h.
{ return control_out_; }
Referenced by v8::internal::compiler::CFGBuilder::BuildBlocksForSuccessors(), v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::compiler::CFGBuilder::ConnectSwitch(), v8::internal::compiler::Control::Control(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::BranchElimination::Reduce(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::Reduce(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::GraphAssembler::UpdateEffectControlWith(), and v8::internal::compiler::RepresentationSelector::VisitNode().
EffectInputCount()
int v8::internal::compiler::Operator::EffectInputCount () const [inline]
Definition at line 102 of file operator.h.
{ return effect_in_; }
Referenced by v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::NodeProperties::FindFrameStateBefore(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::OperatorProperties::GetTotalInputCount(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint(), v8::internal::compiler::BytecodeGraphBuilder::MakeNode(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::NodeProperties::NoObservableSideEffectBetween(), v8::internal::compiler::NodeProperties::PastEffectIndex(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::GraphC1Visualizer::PrintInputs(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::RepresentationSelector::ProcessInput(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::EscapeAnalysisReducer::Reduce(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), v8::internal::compiler::CsaLoadElimination::ReduceOtherNode(), v8::internal::compiler::LoadElimination::ReduceOtherNode(), v8::internal::compiler::RedundancyElimination::ReduceOtherNode(), v8::internal::compiler::WasmLoadElimination::ReduceOtherNode(), v8::internal::compiler::DeadCodeElimination::ReducePureNode(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::VariableTracker::Scope::Scope(), and v8::internal::compiler::MemoryOptimizer::VisitNode().
EffectOutputCount()
int v8::internal::compiler::Operator::EffectOutputCount () const [inline]
Definition at line 106 of file operator.h.
{ return effect_out_; }
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildCallNode(), v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::WasmGraphBuilder::BuildWasmCall(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::Effect::Effect(), v8::internal::compiler::JSBinopReduction::GetCompareBigIntOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareNumberOperationHint(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::JSBinopReduction::IsInternalizedStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverOrNullOrUndefinedCompareOperation(), v8::internal::compiler::JSBinopReduction::IsStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsStringOrOddballCompareOperation(), v8::internal::compiler::JSBinopReduction::IsSymbolCompareOperation(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::CsaLoadElimination::ReduceOtherNode(), v8::internal::compiler::LoadElimination::ReduceOtherNode(), v8::internal::compiler::RedundancyElimination::ReduceOtherNode(), v8::internal::compiler::WasmLoadElimination::ReduceOtherNode(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::RedundancyElimination::TakeChecksFromFirstEffect(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::GraphAssembler::UpdateEffectControlWith(), v8::internal::compiler::MemoryOptimizer::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::WriteBarrierAssertFailed().
Equals()
virtual bool v8::internal::compiler::Operator::Equals (const Operator * that) const [inline], [virtual]
Reimplemented in v8::internal::compiler::Operator1< T, Pred, Hash >, v8::internal::compiler::Operator1< TruncateKind >, v8::internal::compiler::Operator1< CheckFloat64HoleParameters >, v8::internal::compiler::Operator1< StackCheckKind >, v8::internal::compiler::Operator1< SparseInputMask >, v8::internal::compiler::Operator1< CheckMinusZeroParameters >, v8::internal::compiler::Operator1< GrowFastElementsParameters >, v8::internal::compiler::Operator1< BigIntOperationParameters >, v8::internal::compiler::Operator1< CheckIfParameters >, v8::internal::compiler::Operator1< MachineRepresentation >, v8::internal::compiler::Operator1< RegionObservability >, v8::internal::compiler::Operator1< StoreRepresentation >, v8::internal::compiler::Operator1< AtomicMemoryOrder >, v8::internal::compiler::Operator1< const char * >, v8::internal::compiler::Operator1< SilenceNanMode >, v8::internal::compiler::Operator1< size_t >, v8::internal::compiler::Operator1< ParameterInfo >, v8::internal::compiler::Operator1< ShiftKind >, v8::internal::compiler::Operator1< StackSlotRepresentation >, v8::internal::compiler::Operator1< NumberOperationParameters >, v8::internal::compiler::Operator1< CheckTaggedInputParameters >, v8::internal::compiler::Operator1< DeoptimizeParameters >, v8::internal::compiler::Operator1< BranchParameters >, v8::internal::compiler::Operator1< ConvertReceiverMode >, and v8::internal::compiler::Operator1< CheckForMinusZeroMode >.
Definition at line 84 of file operator.h.
                                                  {
    return this->opcode() == that->opcode();
  }
References opcode().
Referenced by v8::internal::compiler::NodeProperties::Equals().
HashCode()
virtual size_t v8::internal::compiler::Operator::HashCode () const [inline], [virtual]
Reimplemented in v8::internal::compiler::Operator1< T, Pred, Hash >, v8::internal::compiler::Operator1< TruncateKind >, v8::internal::compiler::Operator1< CheckFloat64HoleParameters >, v8::internal::compiler::Operator1< StackCheckKind >, v8::internal::compiler::Operator1< SparseInputMask >, v8::internal::compiler::Operator1< CheckMinusZeroParameters >, v8::internal::compiler::Operator1< GrowFastElementsParameters >, v8::internal::compiler::Operator1< BigIntOperationParameters >, v8::internal::compiler::Operator1< CheckIfParameters >, v8::internal::compiler::Operator1< MachineRepresentation >, v8::internal::compiler::Operator1< RegionObservability >, v8::internal::compiler::Operator1< StoreRepresentation >, v8::internal::compiler::Operator1< AtomicMemoryOrder >, v8::internal::compiler::Operator1< const char * >, v8::internal::compiler::Operator1< SilenceNanMode >, v8::internal::compiler::Operator1< size_t >, v8::internal::compiler::Operator1< ParameterInfo >, v8::internal::compiler::Operator1< ShiftKind >, v8::internal::compiler::Operator1< StackSlotRepresentation >, v8::internal::compiler::Operator1< NumberOperationParameters >, v8::internal::compiler::Operator1< CheckTaggedInputParameters >, v8::internal::compiler::Operator1< DeoptimizeParameters >, v8::internal::compiler::Operator1< BranchParameters >, v8::internal::compiler::Operator1< ConvertReceiverMode >, and v8::internal::compiler::Operator1< CheckForMinusZeroMode >.
Definition at line 91 of file operator.h.
{ return base::hash<Opcode>()(opcode()); }
Referenced by v8::internal::compiler::NodeProperties::HashCode().
HasProperty()
bool v8::internal::compiler::Operator::HasProperty (Property property) const [inline]
Definition at line 94 of file operator.h.
                                            {
    return (properties() & property) == property;
  }
Referenced by v8::internal::compiler::GraphAssembler::AddClonedNode(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::AddMatcher(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::BaseWithIndexAndDisplacementMatcher(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::NodeProperties::FindFrameStateBefore(), v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection(), v8::internal::compiler::CodeAssembler::HandleException(), v8::internal::compiler::NodeMatcher::HasProperty(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::RepresentationSelector::ProcessInput(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::compiler::ValueNumberingReducer::Reduce(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::CsaLoadElimination::ReduceOtherNode(), v8::internal::compiler::LoadElimination::ReduceOtherNode(), v8::internal::compiler::WasmLoadElimination::ReduceOtherNode(), v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::SideEffectFree(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), and v8::internal::compiler::RepresentationSelector::VisitNode().
mnemonic()
const char* v8::internal::compiler::Operator::mnemonic () const [inline]
Definition at line 79 of file operator.h.
{ return mnemonic_; }
Referenced by v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::SimplifiedLoweringVerifier::CheckType(), v8::internal::compiler::Verifier::Visitor::CheckValueInputIs(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::Scheduler::DecrementUnscheduledUseCount(), v8::internal::compiler::RepresentationSelector::DeferReplacement(), v8::internal::compiler::LoopFinder::HasMarkedExits(), v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::compiler::RepresentationSelector::MarkAsPossibleRevisit(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::Node::NewImpl(), v8::internal::compiler::Schedule::PlanNode(), v8::internal::compiler::PackNode::Print(), v8::internal::compiler::CsaLoadElimination::HalfState::Print(), PrintToImpl(), v8::internal::compiler::Operator1< T, Pred, Hash >::PrintToImpl(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::RepresentationSelector::PropagateTruncation(), v8::internal::compiler::RepresentationSelector::PushNodeToRevisitIfVisited(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::EscapeAnalysis::Reduce(), v8::internal::compiler::SimplifiedLoweringVerifier::ReportInvalidTypeCombination(), v8::internal::compiler::RepresentationSelector::RetypeNode(), v8::internal::compiler::EffectGraphReducer::Revisit(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::compiler::SafeMnemonic(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetEscaped(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetReplacement(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::CFGBuilder::TraceConnect(), v8::internal::compiler::RepresentationChanger::TypeError(), v8::internal::compiler::Revectorizer::UpdateSources(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement(), v8::internal::compiler::ControlEquivalence::VisitBackedge(), v8::internal::compiler::PrepareUsesVisitor::VisitInputs(), v8::internal::compiler::ControlEquivalence::VisitMid(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::ControlEquivalence::VisitPost(), v8::internal::compiler::ControlEquivalence::VisitPre(), and v8::internal::compiler::RepresentationSelector::VisitUnused().
opcode()
constexpr Opcode v8::internal::compiler::Operator::opcode () const [inline], [constexpr]
Definition at line 75 of file operator.h.
{ return opcode_; }
Referenced by v8::internal::compiler::AbortReasonOf(), v8::internal::compiler::AllocateParametersOf(), v8::internal::compiler::AllocateTypeOf(), v8::internal::compiler::AllocationTypeOf(), v8::internal::compiler::ArgumentsStateTypeOf(), v8::internal::compiler::AssertParametersOf(), v8::internal::compiler::AtomicLoadParametersOf(), v8::internal::compiler::AtomicOpParametersOf(), v8::internal::compiler::AtomicStoreParametersOf(), v8::internal::compiler::BigIntOperationHintOf(), v8::internal::compiler::BigIntOperationParametersOf(), v8::internal::compiler::BranchHintOf(), v8::internal::compiler::BranchParametersOf(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOpWithImmediate(), v8::internal::compiler::BytecodeGraphBuilder::BuildCall(), v8::internal::compiler::BytecodeGraphBuilder::BuildCompareOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildLoadGlobal(), v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), v8::internal::compiler::BytecodeGraphBuilder::BuildUnaryOp(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::CallDescriptorOf(), v8::internal::compiler::CallForwardVarargsParametersOf(), v8::internal::compiler::CallParametersOf(), v8::internal::compiler::CallRuntimeParametersOf(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::CheckBoundsParametersOf(), v8::internal::compiler::CheckFloat64HoleParametersOf(), v8::internal::compiler::CheckIfParametersOf(), v8::internal::compiler::CheckMapsParametersOf(), v8::internal::compiler::CheckMinusZeroModeOf(), v8::internal::compiler::CheckMinusZeroParametersOf(), v8::internal::compiler::CheckParametersOf(), v8::internal::compiler::CheckTaggedInputParametersOf(), v8::internal::compiler::CloneObjectParametersOf(), v8::internal::compiler::CompareMapsParametersOf(), v8::internal::compiler::ConstructForwardVarargsParametersOf(), v8::internal::compiler::ConstructParametersOf(), v8::internal::compiler::ContextAccessOf(), v8::internal::compiler::ConvertReceiverModeOf(), v8::internal::compiler::CreateArgumentsTypeOf(), v8::internal::compiler::CreateArrayIteratorParametersOf(), v8::internal::compiler::CreateArrayParametersOf(), v8::internal::compiler::CreateBoundFunctionParametersOf(), v8::internal::compiler::CreateClosureParametersOf(), v8::internal::compiler::CreateCollectionIteratorParametersOf(), v8::internal::compiler::CreateFunctionContextParametersOf(), v8::internal::compiler::CreateLiteralParametersOf(), v8::internal::compiler::DeadValueRepresentationOf(), v8::internal::compiler::DefineNamedOwnPropertyParametersOf(), v8::internal::compiler::DeoptimizeParametersOf(), v8::internal::compiler::DoubleMapParameterOf(), v8::internal::compiler::Effect::Effect(), v8::internal::compiler::ElementAccessOf(), v8::internal::compiler::ElementsTransitionOf(), v8::internal::compiler::ElementsTransitionWithMultipleSourcesOf(), v8::internal::compiler::Operator1< T, Pred, Hash >::Equals(), Equals(), v8::internal::compiler::ExitMachineGraphParametersOf(), v8::internal::compiler::ExternalArrayTypeOf(), v8::internal::compiler::FastApiCallParametersOf(), v8::internal::compiler::FastMapParameterOf(), v8::internal::compiler::FeedbackCellOf(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::FindInsertionPoint(), v8::internal::compiler::ForInParametersOf(), v8::internal::compiler::FormalParameterCountOf(), v8::internal::compiler::FrameStateInfoOf(), v8::internal::compiler::GeneratorStoreValueCountOf(), v8::internal::compiler::GetIteratorParametersOf(), v8::internal::compiler::GetTemplateObjectParametersOf(), v8::internal::compiler::GrowFastElementsParametersOf(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::Operator1< T, Pred, Hash >::HashCode(), v8::internal::compiler::HeapConstantOf(), v8::internal::compiler::IfValueParametersOf(), v8::internal::compiler::OperatorProperties::IsBasicBlockBegin(), v8::internal::compiler::IsCheckedWithFeedback(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLoadFloat16ArrayElement(), v8::internal::compiler::Word32Adapter::IsWordNSarShiftOutZeros(), v8::internal::compiler::Word64Adapter::IsWordNSarShiftOutZeros(), v8::internal::compiler::LoadGlobalParametersOf(), v8::internal::compiler::LoadRepresentationOf(), v8::internal::compiler::LoopExitValueRepresentationOf(), v8::internal::compiler::MachineTypesOf(), v8::internal::compiler::BytecodeGraphBuilder::MakeNode(), v8::internal::compiler::MachineOperatorReducer::Map64To32Comparison(), v8::internal::compiler::MapGuardMapsOf(), v8::internal::compiler::NamedAccessOf(), v8::internal::compiler::OperatorProperties::NeedsExactContext(), v8::internal::compiler::NewArgumentsElementsParametersOf(), v8::internal::compiler::TypedOptimization::NumberComparisonFor(), v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::NumberOperationParametersOf(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NumberOpFromSpeculativeNumberOp(), v8::internal::compiler::ObjectAccessOf(), v8::internal::compiler::ObjectIdOf(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementsAccess(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfFieldAccess(), v8::internal::compiler::ObservableNodeState::opcode(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::OperatorCanBePacked(), v8::internal::compiler::OsrValueIndexOf(), v8::internal::compiler::ParameterIndexOf(), v8::internal::compiler::ParameterInfoOf(), v8::internal::compiler::PhiRepresentationOf(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::ProjectionIndexOf(), v8::internal::compiler::PropertyAccessOf(), v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceConstructOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceGetIteratorOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceLoadKeyedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceLoadNamedOperation(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::JSTypeHintLowering::ReduceStoreKeyedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceStoreNamedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation(), v8::internal::compiler::RegionObservabilityOf(), v8::internal::compiler::RegisterCountOf(), v8::internal::compiler::CommonOperatorBuilder::ResizeMergeOrPhi(), v8::internal::compiler::RestoreRegisterIndexOf(), v8::internal::compiler::ScopeInfoOf(), v8::internal::compiler::SelectParametersOf(), v8::internal::compiler::ShiftKindOf(), v8::internal::compiler::SilenceNanModeOf(), v8::internal::compiler::SLVerifierHintParametersOf(), v8::internal::compiler::SparseInputMaskOf(), v8::internal::compiler::SpeculativeBigIntAsNParametersOf(), v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeBigIntCompareOp(), v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeBigIntOp(), v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeNumberCompareOp(), v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeNumberOp(), v8::internal::compiler::StackCheckKindOf(), v8::internal::compiler::StackSlotRepresentationOf(), v8::internal::compiler::StaticAssertSourceOf(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), v8::internal::compiler::StoreGlobalParametersOf(), v8::internal::compiler::StorePairRepresentationOf(), v8::internal::compiler::StoreRepresentationOf(), v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildNumberCompare(), v8::internal::compiler::TypeGuardTypeOf(), v8::internal::compiler::UnalignedStoreRepresentationOf(), v8::internal::compiler::ValueInputCountOfReturn(), and v8::internal::compiler::ValueTypeParameterOf().
operator=()
Operator& v8::internal::compiler::Operator::operator= (const Operator &) [delete]
PrintPropsTo()
void v8::internal::compiler::Operator::PrintPropsTo (std::ostream & os) const
Definition at line 49 of file operator.cc.
                                                {
  std::string separator = "";
#define PRINT_PROP_IF_SET(name) \
  if (HasProperty(Operator::k##name)) { \
    os << separator; \
    os << #name; \
    separator = ", "; \
  }
  OPERATOR_PROPERTY_LIST(PRINT_PROP_IF_SET)
#undef PRINT_PROP_IF_SET
}
References OPERATOR_PROPERTY_LIST, PRINT_PROP_IF_SET, v8::internal::separator, and v8::internal::string.
Referenced by v8::internal::compiler::JSONGraphWriter::PrintNode().
PrintTo()
void v8::internal::compiler::Operator::PrintTo (std::ostream & os, PrintVerbosity verbose = PrintVerbosity::kVerbose) const [inline]
Definition at line 125 of file operator.h.
                                                                      {
    // We cannot make PrintTo virtual, because default arguments to virtual
    // methods are banned in the style guide.
    return PrintToImpl(os, verbose);
  }
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::JSONGraphWriter::PrintNode().
PrintToImpl()
void v8::internal::compiler::Operator::PrintToImpl (std::ostream & os, PrintVerbosity verbose) const [protected], [virtual]
Reimplemented in v8::internal::compiler::Operator1< T, Pred, Hash >, v8::internal::compiler::Operator1< TruncateKind >, v8::internal::compiler::Operator1< CheckFloat64HoleParameters >, v8::internal::compiler::Operator1< StackCheckKind >, v8::internal::compiler::Operator1< SparseInputMask >, v8::internal::compiler::Operator1< CheckMinusZeroParameters >, v8::internal::compiler::Operator1< GrowFastElementsParameters >, v8::internal::compiler::Operator1< BigIntOperationParameters >, v8::internal::compiler::Operator1< CheckIfParameters >, v8::internal::compiler::Operator1< MachineRepresentation >, v8::internal::compiler::Operator1< RegionObservability >, v8::internal::compiler::Operator1< StoreRepresentation >, v8::internal::compiler::Operator1< AtomicMemoryOrder >, v8::internal::compiler::Operator1< const char * >, v8::internal::compiler::Operator1< SilenceNanMode >, v8::internal::compiler::Operator1< size_t >, v8::internal::compiler::Operator1< ParameterInfo >, v8::internal::compiler::Operator1< ShiftKind >, v8::internal::compiler::Operator1< StackSlotRepresentation >, v8::internal::compiler::Operator1< NumberOperationParameters >, v8::internal::compiler::Operator1< CheckTaggedInputParameters >, v8::internal::compiler::Operator1< DeoptimizeParameters >, v8::internal::compiler::Operator1< BranchParameters >, v8::internal::compiler::Operator1< ConvertReceiverMode >, and v8::internal::compiler::Operator1< CheckForMinusZeroMode >.
Definition at line 45 of file operator.cc.
                                                                       {
  os << mnemonic();
}
References mnemonic().
properties()
Properties v8::internal::compiler::Operator::properties () const [inline]
Definition at line 98 of file operator.h.
{ return properties_; }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::NodeProperties::NoObservableSideEffectBetween(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::OperatorCanBePacked(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), and v8::internal::compiler::JSTypedLowering::ReduceJSToObject().
ValueInputCount()
int v8::internal::compiler::Operator::ValueInputCount () const [inline]
Definition at line 101 of file operator.h.
{ return value_in_; }
Referenced by v8::internal::compiler::NodeProperties::AllValueInputsAreTyped(), v8::internal::compiler::RepresentationSelector::BothInputsAre(), v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::RepresentationSelector::CanSpeculateAdditiveSafeInteger(), v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::JSGraphAssembler::Chained(), v8::internal::compiler::RepresentationSelector::ChangeToDeadValue(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::OperatorProperties::GetTotalInputCount(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::RepresentationSelector::InputCannotBe(), v8::internal::compiler::RepresentationSelector::InputIs(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::BytecodeGraphBuilder::MakeNode(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RepresentationSelector::OneInputCannotBe(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::NodeProperties::PastValueIndex(), v8::internal::compiler::GraphC1Visualizer::PrintInputs(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::NodeProperties::RemoveNonValueInputs(), v8::internal::compiler::NodeProperties::RemoveValueInputs(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::RepresentationSelector::TypePhi(), v8::internal::compiler::ValueInputCountOfReturn(), v8::internal::compiler::RepresentationSelector::VisitBinop(), v8::internal::compiler::RepresentationSelector::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitFastApiCall(), v8::internal::compiler::StringBuilderOptimizer::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitPhi(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeInt32Binop(), and v8::internal::compiler::RepresentationSelector::VisitUnop().
ValueOutputCount()
int v8::internal::compiler::Operator::ValueOutputCount () const [inline]
Definition at line 105 of file operator.h.
{ return value_out_; }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::StartNode::ContextParameterIndex_MaybeNonStandardLayout(), v8::internal::compiler::Typer::Decorator::Decorate(), v8::internal::compiler::StartNode::FormalParameterCount(), v8::internal::compiler::StartNode::FormalParameterCountWithoutReceiver(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::Typer::Visitor::Reduce(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), and v8::internal::compiler::RepresentationSelector::VisitNode().
ZeroIfEliminatable()
static size_t v8::internal::compiler::Operator::ZeroIfEliminatable (Properties properties) [inline], [static]
Definition at line 109 of file operator.h.
                                                          {
    return (properties & kEliminatable) == kEliminatable ? 0 : 1;
  }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call().
ZeroIfNoThrow()
static size_t v8::internal::compiler::Operator::ZeroIfNoThrow (Properties properties) [inline], [static]
Definition at line 113 of file operator.h.
                                                     {
    return (properties & kNoThrow) == kNoThrow ? 0 : 2;
  }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call().
ZeroIfPure()
static size_t v8::internal::compiler::Operator::ZeroIfPure (Properties properties) [inline], [static]
Definition at line 117 of file operator.h.
                                                  {
    return (properties & kPure) == kPure ? 0 : 1;
  }
Referenced by v8::internal::compiler::CommonOperatorBuilder::Call().
Member Data Documentation
control_in_
uint32_t v8::internal::compiler::Operator::control_in_ [private]
Definition at line 143 of file operator.h.
control_out_
uint32_t v8::internal::compiler::Operator::control_out_ [private]
Definition at line 146 of file operator.h.
effect_in_
uint32_t v8::internal::compiler::Operator::effect_in_ [private]
Definition at line 142 of file operator.h.
effect_out_
uint8_t v8::internal::compiler::Operator::effect_out_ [private]
Definition at line 145 of file operator.h.
mnemonic_
const char* v8::internal::compiler::Operator::mnemonic_ [private]
Definition at line 138 of file operator.h.
opcode_
Opcode v8::internal::compiler::Operator::opcode_ [private]
Definition at line 139 of file operator.h.
properties_
Properties v8::internal::compiler::Operator::properties_ [private]
Definition at line 140 of file operator.h.
value_in_
uint32_t v8::internal::compiler::Operator::value_in_ [private]
Definition at line 141 of file operator.h.
value_out_
uint32_t v8::internal::compiler::Operator::value_out_ [private]
Definition at line 144 of file operator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/operator.h
/mnt/V8SourceCode/src/compiler/operator.cc