v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups Class Reference
Static Public Member Functions
static base::Vector< int > Filter (int pc, base::Vector< int > registers, base::Vector< uint64_t > quantifiers_clocks, base::Vector< uint64_t > capture_clocks, std::optional< base::Vector< uint64_t >> lookaround_clocks, base::Vector< int > filtered_registers, base::Vector< const RegExpInstruction > bytecode, Zone *zone)
Private Member Functions
FilterGroups (int pc, base::Vector< const RegExpInstruction > bytecode, Zone *zone)
void Up ()
void IncrementPC ()
bool IsAtNodeEnd ()
base::Vector< int > Run (base::Vector< int > registers_, base::Vector< uint64_t > quantifiers_clocks_, base::Vector< uint64_t > capture_clocks_, std::optional< base::Vector< uint64_t >> lookaround_clocks, base::Vector< int > filtered_registers_)
Private Attributes
int pc_
uint64_t max_clock_
ZoneStack< int > pc_stack_
ZoneStack< uint64_t > max_clock_stack_
base::Vector< const RegExpInstruction > bytecode_
Detailed Description
Definition at line 85 of file experimental-interpreter.cc.
Constructor & Destructor Documentation
FilterGroups()
v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::FilterGroups (int pc, base::Vector< const RegExpInstruction > bytecode, Zone * zone) [inline], [private]
Definition at line 112 of file experimental-interpreter.cc.
      : pc_(pc),
        max_clock_(0),
        pc_stack_(zone),
        max_clock_stack_(zone),
        bytecode_(bytecode) {}
Member Function Documentation
Filter()
static base::Vector<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::Filter (int pc, base::Vector< int > registers, base::Vector< uint64_t > quantifiers_clocks, base::Vector< uint64_t > capture_clocks, std::optional< base::Vector< uint64_t >> lookaround_clocks, base::Vector< int > filtered_registers, base::Vector< const RegExpInstruction > bytecode, Zone * zone) [inline], [static]
Definition at line 87 of file experimental-interpreter.cc.
                                                                {
    /* Capture groups that were not traversed in the last iteration of a
     * quantifier need to be discarded. In order to determine which groups need
     * to be discarded, the interpreter maintains a clock, an internal count of
     * bytecode instructions executed. Whenever it reaches a quantifier or
     * a capture group, it records the current clock. After a match is found,
     * the interpreter filters out capture groups that were defined in any other
     * iteration than the last. To do so, it compares the last clock value of
     * the group with the last clock value of its parent quantifier/group,
     * keeping only groups that were defined after the parent quantifier/group
     * last iteration. The structure of the bytecode used is explained in
     * `FilterGroupsCompileVisitor` (experimental-compiler.cc). */
    return FilterGroups(pc, bytecode, zone)
        .Run(registers, quantifiers_clocks, capture_clocks, lookaround_clocks,
             filtered_registers);
  }
References Run().
IncrementPC()
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::IncrementPC () [inline], [private]
Definition at line 132 of file experimental-interpreter.cc.
                     {
    if (IsAtNodeEnd()) {
      Up();
    } else {
      pc_++;
    }
  }
IsAtNodeEnd()
bool v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::IsAtNodeEnd () [inline], [private]
Definition at line 140 of file experimental-interpreter.cc.
                     {
    return pc_ + 1 == bytecode_.length() ||
           bytecode_[pc_ + 1].opcode != RegExpInstruction::FILTER_CHILD;
  }
References v8::internal::RegExpInstruction::FILTER_CHILD.
Run()
base::Vector<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::Run (base::Vector< int > registers_, base::Vector< uint64_t > quantifiers_clocks_, base::Vector< uint64_t > capture_clocks_, std::optional< base::Vector< uint64_t >> lookaround_clocks, base::Vector< int > filtered_registers_) [inline], [private]
Definition at line 145 of file experimental-interpreter.cc.
                                                             {
    pc_stack_.push(pc_);
    max_clock_stack_.push(max_clock_);
    while (!pc_stack_.empty()) {
      auto instr = bytecode_[pc_];
      switch (instr.opcode) {
        case RegExpInstruction::FILTER_CHILD:
          // We only need to come back for the next instructions if we are at
          // the end of the node.
          if (!IsAtNodeEnd()) {
            pc_stack_.push(pc_ + 1);
            max_clock_stack_.push(max_clock_);
          }
          // Enter the child's node.
          pc_ = instr.payload.pc;
          break;
        case RegExpInstruction::FILTER_GROUP: {
          int group_id = instr.payload.group_id;
          // Checks whether the captured group should be saved or discarded.
          int register_id = 2 * group_id;
          if (capture_clocks_[register_id] >= max_clock_ &&
              capture_clocks_[register_id] != kUndefinedClockValue) {
            filtered_registers_[register_id] = registers_[register_id];
            filtered_registers_[register_id + 1] = registers_[register_id + 1];
            IncrementPC();
          } else {
            // If the node should be discarded, all its children should be too.
            // By going back to the parent, we don't visit the children, and
            // therefore don't copy their registers.
            Up();
          }
          break;
        }
        case RegExpInstruction::FILTER_QUANTIFIER: {
          int quantifier_id = instr.payload.quantifier_id;
          // Checks whether the quantifier should be saved or discarded.
          if (quantifiers_clocks_[quantifier_id] >= max_clock_) {
            max_clock_ = quantifiers_clocks_[quantifier_id];
            IncrementPC();
          } else {
            // If the node should be discarded, all its children should be too.
            // By going back to the parent, we don't visit the children, and
            // therefore don't copy their registers.
            Up();
          }
          break;
        }
        case RegExpInstruction::FILTER_LOOKAROUND: {
          // Checks whether the lookaround should be saved or discarded.
          if (!lookaround_clocks.has_value() ||
              lookaround_clocks->at(instr.payload.lookaround_id) >=
                  max_clock_) {
            // lookaround_clocks->at(instr.payload.lookaround_id);
            IncrementPC();
          } else {
            // If the node should be discarded, all its children should be
            // too. By going back to the parent, we don't visit the
            // children, and therefore don't copy their registers.
            Up();
          }
          break;
        }
        default:
          UNREACHABLE();
      }
    }
    return filtered_registers_;
  }
References v8::internal::RegExpInstruction::FILTER_CHILD, v8::internal::RegExpInstruction::FILTER_GROUP, v8::internal::RegExpInstruction::FILTER_LOOKAROUND, v8::internal::RegExpInstruction::FILTER_QUANTIFIER, v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedClockValue, and v8::internal::UNREACHABLE().
Referenced by Filter().
Up()
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::Up () [inline], [private]
Definition at line 122 of file experimental-interpreter.cc.
            {
    if (pc_stack_.size() > 0) {
      pc_ = pc_stack_.top();
      max_clock_ = max_clock_stack_.top();
      pc_stack_.pop();
      max_clock_stack_.pop();
    }
  }
Member Data Documentation
bytecode_
base::Vector<const RegExpInstruction> v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::bytecode_ [private]
Definition at line 237 of file experimental-interpreter.cc.
max_clock_
uint64_t v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::max_clock_ [private]
Definition at line 231 of file experimental-interpreter.cc.
max_clock_stack_
ZoneStack<uint64_t> v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::max_clock_stack_ [private]
Definition at line 235 of file experimental-interpreter.cc.
pc_
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::pc_ [private]
Definition at line 227 of file experimental-interpreter.cc.
pc_stack_
ZoneStack<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::FilterGroups::pc_stack_ [private]
Definition at line 234 of file experimental-interpreter.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-interpreter.cc