v8::metrics::Recorder Class Reference
This class serves as a base class for recording event-based metrics in V8.
#include <v8-metrics.h>
Classes
class ContextId
Public Member Functions
virtual ~Recorder ()=default
virtual void NotifyIsolateDisposal ()
Static Public Member Functions
static MaybeLocal< Context > GetContext (Isolate *isolate, ContextId id)
static ContextId GetContextId (Local< Context > context)
Detailed Description
This class serves as a base class for recording event-based metrics in V8.
There a two kinds of metrics, those which are expected to be thread-safe and whose implementation is required to fulfill this requirement and those whose implementation does not have that requirement and only needs to be executable on the main thread. If such an event is triggered from a background thread, it will be delayed and executed by the foreground task runner.
The embedder is expected to call v8::Isolate::SetMetricsRecorder() providing its implementation and have the virtual methods overwritten for the events it cares about.
Definition at line 186 of file v8-metrics.h.
Constructor & Destructor Documentation
 Recorder()
virtual v8::metrics::Recorder::~Recorder () [virtual], [default]
Member Function Documentation
GetContext()
MaybeLocal< Context > v8::metrics::Recorder::GetContext (Isolate * isolate, ContextId id) [static]
Definition at line 7276 of file api.cc.
                                                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  return i_isolate->GetContextFromRecorderContextId(id);
}
References v8::internal::Isolate::GetContextFromRecorderContextId().
GetContextId()
metrics::Recorder::ContextId v8::metrics::Recorder::GetContextId (Local< Context > context) [static]
Definition at line 7282 of file api.cc.
                            {
  auto i_context = Utils::OpenDirectHandle(*context);
  i::Isolate* i_isolate = i::Isolate::Current();
  return i_isolate->GetOrRegisterRecorderContextId(
      direct_handle(i_context->native_context(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::GetOrRegisterRecorderContextId(), and v8::Utils::OpenDirectHandle().
NotifyIsolateDisposal()
virtual void v8::metrics::Recorder::NotifyIsolateDisposal () [inline], [virtual]
Definition at line 238 of file v8-metrics.h.
{}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-metrics.h
/mnt/V8SourceCode/src/api/api.cc