unibrow::Utf8 Class Reference
#include <unicode.h>
Classes
struct EncodingResult
Public Types
using State = Utf8DfaDecoder::State
using Utf8IncrementalBuffer = uint32_t
Static Public Member Functions
static unsigned LengthOneByte (uint8_t chr)
static unsigned Length (uchar chr, int previous)
static unsigned EncodeOneByte (char *out, uint8_t c)
static unsigned Encode (char *out, uchar c, int previous, bool replace_invalid=false)
static uchar CalculateValue (const uint8_t *str, size_t length, size_t *cursor)
static uchar ValueOf (const uint8_t *str, size_t length, size_t *cursor)
static uchar ValueOfIncremental (const uint8_t **cursor, State *state, Utf8IncrementalBuffer *buffer)
static uchar ValueOfIncrementalFinish (State *state)
static bool IsValidCharacter (uchar c)
static bool ValidateEncoding (const uint8_t *str, size_t length)
template<typename Char >
static EncodingResult Encode (v8::base::Vector< const Char > string, char *buffer, size_t capacity, bool write_null, bool replace_invalid_utf8)
Static Public Attributes
static const uchar kBadChar = 0xFFFD
static const uchar kBufferEmpty = 0x0
static const uchar kIncomplete = 0xFFFFFFFC
static const unsigned kMaxEncodedSize = 4
static const unsigned kMaxOneByteChar = 0x7f
static const unsigned kMaxTwoByteChar = 0x7ff
static const unsigned kMaxThreeByteChar = 0xffff
static const unsigned kMaxFourByteChar = 0x1fffff
static const unsigned kBytesSavedByCombiningSurrogates = 2
static const unsigned kSizeOfUnmatchedSurrogate = 3
static const unsigned kMax16BitCodeUnitSize = 3
static const unsigned kMax8BitCodeUnitSize = 2
Detailed Description
Definition at line 161 of file unicode.h.
Member Typedef Documentation
State
using unibrow::Utf8::State = Utf8DfaDecoder::State
Definition at line 163 of file unicode.h.
Utf8IncrementalBuffer
using unibrow::Utf8::Utf8IncrementalBuffer = uint32_t
Definition at line 197 of file unicode.h.
Member Function Documentation
CalculateValue()
uchar unibrow::Utf8::CalculateValue (const uint8_t * str, size_t length, size_t * cursor) [static]
Definition at line 204 of file unicode.cc.
                                           {
  DCHECK_GT(max_length, 0);
  DCHECK_GT(str[0], kMaxOneByteChar);
  State state = State::kAccept;
  Utf8IncrementalBuffer buffer = 0;
  uchar t;
  const uint8_t* start = str;
  const uint8_t* end = str + max_length;
  do {
    t = ValueOfIncremental(&str, &state, &buffer);
  } while (str < end && t == kIncomplete);
  *cursor += str - start;
  return (state == State::kAccept) ? t : kBadChar;
}
References DCHECK_GT, v8::internal::compiler::end(), kBadChar, kIncomplete, kMaxOneByteChar, and ValueOfIncremental().
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeString(), and ValueOf().
Encode() [1/2]
unsigned unibrow::Utf8::Encode (char * out, uchar c, int previous, bool replace_invalid = false) [inline], [static]
Definition at line 134 of file unicode-inl.h.
                                                                            {
  static const int kMask = ~(1 << 6);
  if (c <= kMaxOneByteChar) {
    str[0] = c;
    return 1;
  } else if (c <= kMaxTwoByteChar) {
    str[0] = 0xC0 | (c >> 6);
    str[1] = 0x80 | (c & kMask);
    return 2;
  } else if (c <= kMaxThreeByteChar) {
    DCHECK(!Utf16::IsLeadSurrogate(Utf16::kNoPreviousCharacter));
    if (Utf16::IsSurrogatePair(previous, c)) {
      const int kUnmatchedSize = kSizeOfUnmatchedSurrogate;
      return Encode(str - kUnmatchedSize,
                    Utf16::CombineSurrogatePair(previous, c),
                    Utf16::kNoPreviousCharacter, replace_invalid) -
             kUnmatchedSize;
    } else if (replace_invalid &&
               (Utf16::IsLeadSurrogate(c) || Utf16::IsTrailSurrogate(c))) {
      c = kBadChar;
    }
    str[0] = 0xE0 | (c >> 12);
    str[1] = 0x80 | ((c >> 6) & kMask);
    str[2] = 0x80 | (c & kMask);
    return 3;
  } else {
    str[0] = 0xF0 | (c >> 18);
    str[1] = 0x80 | ((c >> 12) & kMask);
    str[2] = 0x80 | ((c >> 6) & kMask);
    str[3] = 0x80 | (c & kMask);
    return 4;
  }
}
References unibrow::Utf16::CombineSurrogatePair(), DCHECK, unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsSurrogatePair(), unibrow::Utf16::IsTrailSurrogate(), kBadChar, kMaxOneByteChar, kMaxThreeByteChar, kMaxTwoByteChar, unibrow::Utf16::kNoPreviousCharacter, and kSizeOfUnmatchedSurrogate.
Referenced by Encode(), v8::internal::anonymous_namespace{uri.cc}::EncodePair(), v8::internal::anonymous_namespace{uri.cc}::EncodeSingle(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::RUNTIME_FUNCTION(), v8::internal::StringCharacterStream::WriteUtf8Bytes(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
Encode() [2/2]
template<typename Char >
Utf8::EncodingResult unibrow::Utf8::Encode (v8::base::Vector< const Char > string, char * buffer, size_t capacity, bool write_null, bool replace_invalid_utf8) [static]
Definition at line 210 of file unicode-inl.h.
                                                                              {
  constexpr bool kSourceIsOneByte = sizeof(Char) == 1;
  if constexpr (kSourceIsOneByte) {
    // Only 16-bit characters can contain invalid unicode.
    replace_invalid_utf8 = false;
  }
  size_t write_index = 0;
  const Char* characters = string.begin();
  size_t content_capacity = capacity - write_null;
  CHECK_LE(content_capacity, capacity);
  uint16_t last = Utf16::kNoPreviousCharacter;
  size_t read_index = 0;
  for (; read_index < string.size(); read_index++) {
    Char character = characters[read_index];
    size_t required_capacity;
    if constexpr (kSourceIsOneByte) {
      required_capacity = Utf8::LengthOneByte(character);
    } else {
      required_capacity = Utf8::Length(character, last);
    }
    size_t remaining_capacity = content_capacity - write_index;
    if (remaining_capacity < required_capacity) {
      // Not enough space left, so stop here.
      if (Utf16::IsSurrogatePair(last, character)) {
        DCHECK_GE(write_index, Utf8::kSizeOfUnmatchedSurrogate);
        // We're in the middle of a surrogate pair. Delete the first part again.
        write_index -= Utf8::kSizeOfUnmatchedSurrogate;
        // We've already read at least one character which is a lead surrogate
        DCHECK_NE(read_index, 0);
        --read_index;
      }
      break;
    }
    if constexpr (kSourceIsOneByte) {
      write_index += Utf8::EncodeOneByte(buffer + write_index, character);
    } else {
      // Handle the case where we cut off in the middle of a surrogate pair.
      if ((read_index + 1 < string.size()) &&
          Utf16::IsSurrogatePair(character, characters[read_index + 1])) {
        write_index += Utf8::kSizeOfUnmatchedSurrogate;
      } else {
        write_index += Utf8::Encode(buffer + write_index, character, last,
                                    replace_invalid_utf8);
      }
    }
    last = character;
  }
  DCHECK_LE(write_index, capacity);
  if (write_null) {
    DCHECK_LT(write_index, capacity);
    buffer[write_index++] = '\0';
  }
  size_t bytes_written = write_index;
  size_t characters_processed = read_index;
  return {bytes_written, characters_processed};
}
References v8::internal::character, CHECK_LE, DCHECK_GE, DCHECK_LE, DCHECK_LT, DCHECK_NE, Encode(), EncodeOneByte(), unibrow::Utf16::IsSurrogatePair(), unibrow::Utf16::kNoPreviousCharacter, kSizeOfUnmatchedSurrogate, Length(), LengthOneByte(), and size().
EncodeOneByte()
unsigned unibrow::Utf8::EncodeOneByte (char * out, uint8_t c) [inline], [static]
Definition at line 118 of file unicode-inl.h.
                                                 {
  static const int kMask = ~(1 << 6);
  if (c <= kMaxOneByteChar) {
    str[0] = c;
    return 1;
  } else {
    str[0] = 0xC0 | (c >> 6);
    str[1] = 0x80 | (c & kMask);
    return 2;
  }
}
References kMaxOneByteChar.
Referenced by Encode(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
IsValidCharacter()
bool unibrow::Utf8::IsValidCharacter (uchar c) [inline], [static]
Definition at line 203 of file unicode-inl.h.
                                   {
  return c < 0xD800u || (c >= 0xE000u && c < 0xFDD0u) ||
         (c > 0xFDEFu && c <= 0x10FFFFu && (c & 0xFFFEu) != 0xFFFEu &&
          c != kBadChar);
}
References kBadChar.
Length()
unsigned unibrow::Utf8::Length (uchar chr, int previous) [inline], [static]
Definition at line 187 of file unicode-inl.h.
                                           {
  if (c <= kMaxOneByteChar) {
    return 1;
  } else if (c <= kMaxTwoByteChar) {
    return 2;
  } else if (c <= kMaxThreeByteChar) {
    DCHECK(!Utf16::IsLeadSurrogate(Utf16::kNoPreviousCharacter));
    if (Utf16::IsSurrogatePair(previous, c)) {
      return kSizeOfUnmatchedSurrogate - kBytesSavedByCombiningSurrogates;
    }
    return 3;
  } else {
    return 4;
  }
}
References DCHECK, unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsSurrogatePair(), kBytesSavedByCombiningSurrogates, kMaxOneByteChar, kMaxThreeByteChar, kMaxTwoByteChar, unibrow::Utf16::kNoPreviousCharacter, and kSizeOfUnmatchedSurrogate.
Referenced by v8::internal::StringCharacterStream::CountUtf8Bytes(), Encode(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), v8::String::Utf8Length(), v8::internal::String::Utf8Length(), and v8::internal::StringCharacterStream::WriteUtf8Bytes().
LengthOneByte()
unsigned unibrow::Utf8::LengthOneByte (uint8_t chr) [inline], [static]
Definition at line 179 of file unicode-inl.h.
                                      {
  if (c <= kMaxOneByteChar) {
    return 1;
  } else {
    return 2;
  }
}
References kMaxOneByteChar.
Referenced by Encode().
ValidateEncoding()
bool unibrow::Utf8::ValidateEncoding (const uint8_t * str, size_t length) [static]
Definition at line 236 of file unicode.cc.
                                                               {
  return simdutf::validate_utf8(reinterpret_cast<const char*>(bytes), length);
}
References v8::internal::length, and v8::internal::wasm::validate_utf8().
Referenced by v8::internal::wasm::consume_string(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), and v8::internal::wasm::validate_utf8().
ValueOf()
uchar unibrow::Utf8::ValueOf (const uint8_t * str, size_t length, size_t * cursor) [inline], [static]
Definition at line 168 of file unicode-inl.h.
                                                                       {
  if (length == 0) return kBadChar;
  uint8_t first = bytes[0];
  // Characters between 0000 and 007F are encoded as a single character
  if (V8_LIKELY(first <= kMaxOneByteChar)) {
    *cursor += 1;
    return first;
  }
  return CalculateValue(bytes, length, cursor);
}
References CalculateValue(), kBadChar, kMaxOneByteChar, v8::internal::length, and V8_LIKELY.
Referenced by v8::internal::anonymous_namespace{uri.cc}::DecodeOctets().
ValueOfIncremental()
uchar unibrow::Utf8::ValueOfIncremental (const uint8_t ** cursor, State * state, Utf8IncrementalBuffer * buffer) [inline], [static]
Definition at line 73 of file unicode-inl.h.
                                                              {
  DCHECK_NOT_NULL(buffer);
  State old_state = *state;
  uint8_t next = **cursor;
  *cursor += 1;
  if (V8_LIKELY(next <= kMaxOneByteChar && old_state == State::kAccept)) {
    DCHECK_EQ(0u, *buffer);
    return static_cast<uchar>(next);
  }
  // So we're at the lead byte of a 2/3/4 sequence, or we're at a continuation
  // char in that sequence.
  Utf8DfaDecoder::Decode(next, state, buffer);
  switch (*state) {
    case State::kAccept: {
      uchar t = *buffer;
      *buffer = 0;
      return t;
    }
    case State::kReject:
      *state = State::kAccept;
      *buffer = 0;
      // If we hit a bad byte, we need to determine if we were trying to start
      // a sequence or continue one. If we were trying to start a sequence,
      // that means it's just an invalid lead byte and we need to continue to
      // the next (which we already did above). If we were already in a
      // sequence, we need to reprocess this same byte after resetting to the
      // initial state.
      if (old_state != State::kAccept) {
        // We were trying to continue a sequence, so let's reprocess this byte
        // next time.
        *cursor -= 1;
      }
      return kBadChar;
    default:
      return kIncomplete;
  }
}
Referenced by CalculateValue(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), and v8::internal::Utf8ExternalStreamingStream::SkipToPosition().
ValueOfIncrementalFinish()
uchar unibrow::Utf8::ValueOfIncrementalFinish (State * state) [static]
Definition at line 226 of file unicode.cc.
                                                 {
  if (*state == State::kAccept) {
    return kBufferEmpty;
  } else {
    DCHECK_GT(*state, State::kAccept);
    *state = State::kAccept;
    return kBadChar;
  }
}
References DCHECK_GT, kBadChar, and kBufferEmpty.
Referenced by v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk().
Member Data Documentation
kBadChar
const uchar unibrow::Utf8::kBadChar = 0xFFFD [static]
Definition at line 175 of file unicode.h.
Referenced by CalculateValue(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::anonymous_namespace{uri.cc}::DecodeOctets(), Encode(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), IsValidCharacter(), v8::internal::RUNTIME_FUNCTION(), v8::internal::HeapSnapshotJSONSerializer::SerializeString(), v8::internal::Utf8DecoderBase< Utf8Decoder >::Utf8DecoderBase(), ValueOf(), and ValueOfIncrementalFinish().
kBufferEmpty
const uchar unibrow::Utf8::kBufferEmpty = 0x0 [static]
Definition at line 176 of file unicode.h.
Referenced by v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), and ValueOfIncrementalFinish().
kBytesSavedByCombiningSurrogates
const unsigned unibrow::Utf8::kBytesSavedByCombiningSurrogates = 2 [static]
Definition at line 186 of file unicode.h.
Referenced by Length().
kIncomplete
const uchar unibrow::Utf8::kIncomplete = 0xFFFFFFFC [static]
Definition at line 177 of file unicode.h.
Referenced by CalculateValue(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), and v8::internal::Utf8ExternalStreamingStream::SkipToPosition().
kMax16BitCodeUnitSize
const unsigned unibrow::Utf8::kMax16BitCodeUnitSize = 3 [static]
Definition at line 190 of file unicode.h.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::MaxEncodedSize().
kMax8BitCodeUnitSize
const unsigned unibrow::Utf8::kMax8BitCodeUnitSize = 2 [static]
Definition at line 193 of file unicode.h.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::MaxEncodedSize().
kMaxEncodedSize
const unsigned unibrow::Utf8::kMaxEncodedSize = 4 [static]
Definition at line 178 of file unicode.h.
Referenced by v8::internal::anonymous_namespace{uri.cc}::IntoTwoByte(), v8::internal::anonymous_namespace{runtime-wasm.cc}::MeasureWtf8(), and v8::anonymous_namespace{api.cc}::WriteUtf8Impl().
kMaxFourByteChar
const unsigned unibrow::Utf8::kMaxFourByteChar = 0x1fffff [static]
Definition at line 182 of file unicode.h.
kMaxOneByteChar
const unsigned unibrow::Utf8::kMaxOneByteChar = 0x7f [static]
Definition at line 179 of file unicode.h.
Referenced by CalculateValue(), v8::internal::Utf8DecoderBase< Decoder >::Decode(), Encode(), EncodeOneByte(), v8::internal::anonymous_namespace{uri.cc}::IntoOneAndTwoByte(), v8::internal::anonymous_namespace{uri.cc}::IntoTwoByte(), Length(), LengthOneByte(), v8::internal::NonAsciiStart(), v8::internal::Utf8DecoderBase< Utf8Decoder >::Utf8DecoderBase(), and ValueOf().
kMaxThreeByteChar
const unsigned unibrow::Utf8::kMaxThreeByteChar = 0xffff [static]
Definition at line 181 of file unicode.h.
Referenced by Encode(), and Length().
kMaxTwoByteChar
const unsigned unibrow::Utf8::kMaxTwoByteChar = 0x7ff [static]
Definition at line 180 of file unicode.h.
Referenced by Encode(), and Length().
kSizeOfUnmatchedSurrogate
const unsigned unibrow::Utf8::kSizeOfUnmatchedSurrogate = 3 [static]
Definition at line 187 of file unicode.h.
Referenced by Encode(), and Length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/unicode.h
/mnt/V8SourceCode/src/strings/unicode-inl.h
/mnt/V8SourceCode/src/strings/unicode.cc