v8::internal::wasm::WasmSectionIterator Class Reference
#include <module-decoder-impl.h>
Public Member Functions
WasmSectionIterator (Decoder *decoder, ITracer *tracer)
bool more () const
SectionCode section_code () const
const uint8_t * section_start () const
uint32_t section_length () const
base::Vector< const uint8_t > payload () const
const uint8_t * payload_start () const
uint32_t payload_length () const
const uint8_t * section_end () const
void advance (bool move_to_section_end=false)
Private Member Functions
void next ()
Private Attributes
Decoder * decoder_
ITracer * tracer_
SectionCode section_code_
const uint8_t * section_start_
const uint8_t * payload_start_
const uint8_t * section_end_
Detailed Description
Definition at line 163 of file module-decoder-impl.h.
Constructor & Destructor Documentation
WasmSectionIterator()
v8::internal::wasm::WasmSectionIterator::WasmSectionIterator (Decoder * decoder, ITracer * tracer) [inline], [explicit]
Definition at line 165 of file module-decoder-impl.h.
      : decoder_(decoder),
        tracer_(tracer),
        section_code_(kUnknownSectionCode),
        section_start_(decoder->pc()),
        section_end_(decoder->pc()) {
    next();
  }
References next().
Member Function Documentation
advance()
void v8::internal::wasm::WasmSectionIterator::advance (bool move_to_section_end = false) [inline]
Definition at line 198 of file module-decoder-impl.h.
                                                 {
    if (move_to_section_end && decoder_->pc() < section_end_) {
      decoder_->consume_bytes(
          static_cast<uint32_t>(section_end_ - decoder_->pc()));
    }
    if (decoder_->pc() != section_end_) {
      const char* msg = decoder_->pc() < section_end_ ? "shorter" : "longer";
      decoder_->errorf(decoder_->pc(),
                       "section was %s than expected size "
                       "(%u bytes expected, %zu decoded)",
                       msg, section_length(),
                       static_cast<size_t>(decoder_->pc() - section_start_));
    }
    next();
  }
References v8::internal::wasm::Decoder::consume_bytes(), decoder_, v8::internal::wasm::Decoder::errorf(), next(), v8::internal::wasm::Decoder::pc(), section_end_, section_length(), and section_start_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection().
more()
bool v8::internal::wasm::WasmSectionIterator::more () const [inline]
Definition at line 174 of file module-decoder-impl.h.
{ return decoder_->ok() && decoder_->more(); }
References decoder_, v8::internal::wasm::Decoder::more(), and v8::internal::wasm::Decoder::ok().
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection().
next()
void v8::internal::wasm::WasmSectionIterator::next () [inline], [private]
Definition at line 224 of file module-decoder-impl.h.
              {
    if (!decoder_->more()) {
      section_code_ = kUnknownSectionCode;
      return;
    }
    section_start_ = decoder_->pc();
    // Empty line before next section.
    if (tracer_) tracer_->NextLine();
    uint8_t section_code = decoder_->consume_u8("section kind", tracer_);
    if (tracer_) {
      tracer_->Description(": ");
      tracer_->Description(SectionName(static_cast<SectionCode>(section_code)));
      tracer_->NextLine();
    }
    // Read and check the section size.
    uint32_t section_length = decoder_->consume_u32v("section length", tracer_);
    if (tracer_) {
      tracer_->Description(section_length);
      tracer_->NextLine();
    }
    payload_start_ = decoder_->pc();
    section_end_ = payload_start_ + section_length;
    if (section_length > decoder_->available_bytes()) {
      decoder_->errorf(
          section_start_,
          "section (code %u, \"%s\") extends past end of the module "
          "(length %u, remaining bytes %u)",
          section_code, SectionName(static_cast<SectionCode>(section_code)),
          section_length, decoder_->available_bytes());
      section_end_ = payload_start_;
    }
    if (section_code == kUnknownSectionCode) {
      // Check for the known "name", "sourceMappingURL", or "compilationHints"
      // section.
      // To identify the unknown section we set the end of the decoder bytes to
      // the end of the custom section, so that we do not read the section name
      // beyond the end of the section.
      const uint8_t* module_end = decoder_->end();
      decoder_->set_end(section_end_);
      section_code = IdentifyUnknownSectionInternal(decoder_, tracer_);
      if (decoder_->ok()) decoder_->set_end(module_end);
      // As a side effect, the above function will forward the decoder to after
      // the identifier string.
      payload_start_ = decoder_->pc();
    } else if (!IsValidSectionCode(section_code)) {
      decoder_->errorf(decoder_->pc(), "unknown section code #0x%02x",
                       section_code);
    }
    section_code_ = decoder_->failed() ? kUnknownSectionCode
                                       : static_cast<SectionCode>(section_code);
    if (section_code_ == kUnknownSectionCode && section_end_ > decoder_->pc()) {
      // Skip to the end of the unknown section.
      uint32_t remaining = static_cast<uint32_t>(section_end_ - decoder_->pc());
      decoder_->consume_bytes(remaining, "section payload", tracer_);
    }
  }
References v8::internal::wasm::Decoder::available_bytes(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), decoder_, v8::internal::wasm::ITracer::Description(), v8::internal::wasm::Decoder::end(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::failed(), v8::internal::wasm::IdentifyUnknownSectionInternal(), v8::internal::wasm::IsValidSectionCode(), v8::internal::wasm::kUnknownSectionCode, v8::internal::wasm::Decoder::more(), v8::internal::wasm::ITracer::NextLine(), v8::internal::wasm::Decoder::ok(), payload_start_, v8::internal::wasm::Decoder::pc(), section_code(), section_code_, section_end_, section_length(), section_start_, v8::internal::wasm::SectionName(), v8::internal::wasm::Decoder::set_end(), and tracer_.
Referenced by advance(), and WasmSectionIterator().
payload()
base::Vector<const uint8_t> v8::internal::wasm::WasmSectionIterator::payload () const [inline]
Definition at line 184 of file module-decoder-impl.h.
                                            {
    return {payload_start_, payload_length()};
  }
References payload_length(), and payload_start_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection().
payload_length()
uint32_t v8::internal::wasm::WasmSectionIterator::payload_length () const [inline]
Definition at line 190 of file module-decoder-impl.h.
                                  {
    return static_cast<uint32_t>(section_end_ - payload_start_);
  }
References payload_start_, and section_end_.
Referenced by payload().
payload_start()
const uint8_t* v8::internal::wasm::WasmSectionIterator::payload_start () const [inline]
Definition at line 188 of file module-decoder-impl.h.
{ return payload_start_; }
References payload_start_.
section_code()
SectionCode v8::internal::wasm::WasmSectionIterator::section_code () const [inline]
Definition at line 176 of file module-decoder-impl.h.
{ return section_code_; }
References section_code_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeModule(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), and next().
section_end()
const uint8_t* v8::internal::wasm::WasmSectionIterator::section_end () const [inline]
Definition at line 194 of file module-decoder-impl.h.
{ return section_end_; }
References section_end_.
section_length()
uint32_t v8::internal::wasm::WasmSectionIterator::section_length () const [inline]
Definition at line 180 of file module-decoder-impl.h.
                                  {
    return static_cast<uint32_t>(section_end_ - section_start_);
  }
References section_end_, and section_start_.
Referenced by advance(), and next().
section_start()
const uint8_t* v8::internal::wasm::WasmSectionIterator::section_start () const [inline]
Definition at line 178 of file module-decoder-impl.h.
{ return section_start_; }
References section_start_.
Member Data Documentation
decoder_
Decoder* v8::internal::wasm::WasmSectionIterator::decoder_ [private]
Definition at line 215 of file module-decoder-impl.h.
Referenced by advance(), more(), and next().
payload_start_
const uint8_t* v8::internal::wasm::WasmSectionIterator::payload_start_ [private]
Definition at line 219 of file module-decoder-impl.h.
Referenced by next(), payload(), payload_length(), and payload_start().
section_code_
SectionCode v8::internal::wasm::WasmSectionIterator::section_code_ [private]
Definition at line 217 of file module-decoder-impl.h.
Referenced by next(), and section_code().
section_end_
const uint8_t* v8::internal::wasm::WasmSectionIterator::section_end_ [private]
Definition at line 220 of file module-decoder-impl.h.
Referenced by advance(), next(), payload_length(), section_end(), and section_length().
section_start_
const uint8_t* v8::internal::wasm::WasmSectionIterator::section_start_ [private]
Definition at line 218 of file module-decoder-impl.h.
Referenced by advance(), next(), section_length(), and section_start().
tracer_
ITracer* v8::internal::wasm::WasmSectionIterator::tracer_ [private]
Definition at line 216 of file module-decoder-impl.h.
Referenced by next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h