v8::internal::maglev::SetNamedGeneric Class Reference
#include <maglev-ir.h>
Public Member Functions
SetNamedGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource &feedback)
compiler::NameRef name () const
compiler::FeedbackSource feedback () const
Input & context ()
Input & object_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
static constexpr int kContextIndex = 0
static constexpr int kObjectIndex = 1
static constexpr int kValueIndex = 2
Private Types
using Base = FixedInputValueNodeT< 3, SetNamedGeneric >
Private Attributes
const compiler::NameRef name_
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 9390 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::SetNamedGeneric::Base = FixedInputValueNodeT<3, SetNamedGeneric> [private]
Definition at line 9391 of file maglev-ir.h.
Constructor & Destructor Documentation
SetNamedGeneric()
v8::internal::maglev::SetNamedGeneric::SetNamedGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 9394 of file maglev-ir.h.
      : Base(bitfield), name_(name), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::SetNamedGeneric::context () [inline]
Definition at line 9410 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::SetNamedGeneric::feedback () const [inline]
Definition at line 9405 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::SetNamedGeneric::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::SetNamedGeneric::MaxCallStackArgs () const
name()
compiler::NameRef v8::internal::maglev::SetNamedGeneric::name () const [inline]
Definition at line 9404 of file maglev-ir.h.
{ return name_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::SetNamedGeneric::object_input () [inline]
Definition at line 9411 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::SetNamedGeneric::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8279 of file maglev-ir.cc.
                                                                             {
  os << "(" << *name_.object() << ")";
}
References name_, and v8::internal::compiler::NameRef::object().
SetValueLocationConstraints()
void v8::internal::maglev::SetNamedGeneric::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::SetNamedGeneric::value_input () [inline]
Definition at line 9412 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::SetNamedGeneric::feedback_ [private]
Definition at line 9421 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::SetNamedGeneric::kContextIndex = 0 [static], [constexpr]
Definition at line 9407 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::SetNamedGeneric::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 9400 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::SetNamedGeneric::kObjectIndex = 1 [static], [constexpr]
Definition at line 9408 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::SetNamedGeneric::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9399 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::SetNamedGeneric::kValueIndex = 2 [static], [constexpr]
Definition at line 9409 of file maglev-ir.h.
name_
const compiler::NameRef v8::internal::maglev::SetNamedGeneric::name_ [private]
Definition at line 9420 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc