v8::internal::JSSet Class Reference
#include <js-collection.h>
Public Member Functions
void Rehash (Isolate *isolate)
Static Public Member Functions
static void Initialize (DirectHandle< JSSet > set, Isolate *isolate)
static void Clear (Isolate *isolate, DirectHandle< JSSet > set)
Detailed Description
Definition at line 31 of file js-collection.h.
Member Function Documentation
Clear()
void v8::internal::JSSet::Clear (Isolate * isolate, DirectHandle< JSSet > set) [static]
Definition at line 6314 of file objects.cc.
                                                           {
  Handle<OrderedHashSet> table(Cast<OrderedHashSet>(set->table()), isolate);
  table = OrderedHashSet::Clear(isolate, table);
  set->set_table(*table);
}
References v8::internal::OrderedHashTable< OrderedHashSet, 1 >::Clear().
Referenced by v8::internal::BUILTIN(), and v8::Set::Clear().
Initialize()
void v8::internal::JSSet::Initialize (DirectHandle< JSSet > set, Isolate * isolate) [static]
Definition at line 6309 of file objects.cc.
                                                                {
  DirectHandle<OrderedHashSet> table = isolate->factory()->NewOrderedHashSet();
  set->set_table(*table);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewOrderedHashSet().
Referenced by v8::internal::Factory::NewJSSet().
Rehash()
void v8::internal::JSSet::Rehash (Isolate * isolate)
Definition at line 6320 of file objects.cc.
                                   {
  Handle<OrderedHashSet> table_handle(Cast<OrderedHashSet>(table()), isolate);
  DirectHandle<OrderedHashSet> new_table =
      OrderedHashSet::Rehash(isolate, table_handle).ToHandleChecked();
  set_table(*new_table);
}
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-collection.h
/mnt/V8SourceCode/src/objects/objects.cc