v8::internal::TrustedFixedArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Static Public Member Functions
template<class IsolateT >
static Handle< TrustedFixedArray > New (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kTrusted)
Static Public Attributes
static constexpr int kMaxLength = TrustedFixedArray::kMaxCapacity
static constexpr int kMaxRegularLength
Private Types
using Super = TaggedArrayBase< TrustedFixedArray, TrustedArrayShape, TrustedObjectLayout >
Additional Inherited Members
Detailed Description
Definition at line 299 of file fixed-array.h.
Member Typedef Documentation
Super
using v8::internal::TrustedFixedArray::Super = TaggedArrayBase<TrustedFixedArray, TrustedArrayShape, TrustedObjectLayout> [private]
Definition at line 302 of file fixed-array.h.
Member Function Documentation
New()
template<class IsolateT >
Handle< TrustedFixedArray > v8::internal::TrustedFixedArray::New (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kTrusted) [inline], [static]
Definition at line 312 of file fixed-array-inl.h.
                                                                            {
  DCHECK(allocation == AllocationType::kTrusted ||
         allocation == AllocationType::kSharedTrusted);
  if (V8_UNLIKELY(static_cast<unsigned>(capacity) >
                  TrustedFixedArray::kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d (see crbug.com/1201626)",
          capacity);
  }
  // TODO(saelo): once we have trusted read-only roots, we can return the
  // empty_trusted_fixed_array here. Currently this isn't possible because the
  // (mutable) empty_trusted_fixed_array will be created via this function.
  // The same is true for the other trusted-space arrays below.
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<TrustedFixedArray> result =
      Cast<TrustedFixedArray>(Allocate(isolate, capacity, &no_gc, allocation));
  MemsetTagged((*result)->RawFieldOfFirstElement(), Smi::zero(), capacity);
  return result;
}
References v8::internal::TaggedArrayBase< TrustedFixedArray, TrustedArrayShape, TrustedObjectLayout >::Allocate(), v8::internal::DCHECK(), FATAL, kMaxLength, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
Member Data Documentation
kMaxLength
constexpr int v8::internal::TrustedFixedArray::kMaxLength = TrustedFixedArray::kMaxCapacity [static], [constexpr]
Definition at line 316 of file fixed-array.h.
Referenced by v8::internal::TrustedWeakFixedArray::New(), v8::internal::ProtectedWeakFixedArray::New(), and New().
kMaxRegularLength
constexpr int v8::internal::TrustedFixedArray::kMaxRegularLength [static], [constexpr]
Initial value:
=
      TrustedFixedArray::kMaxRegularCapacity
Definition at line 317 of file fixed-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h