v8::base::ThreadTicks Class Reference
#include <time.h>
Public Member Functions
constexpr ThreadTicks ()
Static Public Member Functions
static bool IsSupported ()
static void WaitUntilInitialized ()
static ThreadTicks Now ()
Private Member Functions
constexpr ThreadTicks (int64_t ticks)
Friends
template<class TimeClass >
class time_internal::TimeBase
Additional Inherited Members
Detailed Description
Definition at line 428 of file time.h.
Constructor & Destructor Documentation
ThreadTicks() [1/2]
constexpr v8::base::ThreadTicks::ThreadTicks () [inline], [constexpr]
Definition at line 431 of file time.h.
: TimeBase(0) {}
Referenced by Now().
ThreadTicks() [2/2]
constexpr v8::base::ThreadTicks::ThreadTicks (int64_t ticks) [inline], [explicit], [constexpr], [private]
Definition at line 466 of file time.h.
: TimeBase(ticks) {}
Member Function Documentation
IsSupported()
bool v8::base::ThreadTicks::IsSupported () [static]
Definition at line 779 of file time.cc.
                              {
#if V8_OS_STARBOARD
  return starboard::CurrentMonotonicThreadTime() != 0;
#elif defined(__PASE__)
  // Thread CPU time accounting is unavailable in PASE
  return false;
#elif (defined(_POSIX_THREAD_CPUTIME) && (_POSIX_THREAD_CPUTIME >= 0)) || \
    defined(V8_OS_DARWIN) || defined(V8_OS_ANDROID) || \
    defined(V8_OS_SOLARIS) || defined(V8_OS_ZOS)
  return true;
#elif defined(V8_OS_WIN)
  return IsSupportedWin();
#else
  return false;
#endif
}
Now()
ThreadTicks v8::base::ThreadTicks::Now () [static]
Definition at line 797 of file time.cc.
                             {
#if V8_OS_STARBOARD
  const int64_t now = starboard::CurrentMonotonicThreadTime();
  if (now != 0)
    return ThreadTicks(now);
  UNREACHABLE();
#elif V8_OS_DARWIN
  return ThreadTicks(ComputeThreadTicks());
#elif V8_OS_FUCHSIA
  return ThreadTicks(GetFuchsiaThreadTicks());
#elif (defined(_POSIX_THREAD_CPUTIME) && (_POSIX_THREAD_CPUTIME >= 0)) || \
    defined(V8_OS_ANDROID) || defined(V8_OS_ZOS)
  return ThreadTicks(ClockNow(CLOCK_THREAD_CPUTIME_ID));
#elif V8_OS_SOLARIS
  return ThreadTicks(gethrvtime() / Time::kNanosecondsPerMicrosecond);
#elif V8_OS_WIN
  return ThreadTicks::GetForThread(::GetCurrentThread());
#else
  UNREACHABLE();
#endif
}
References v8::base::TimeConstants::kNanosecondsPerMicrosecond, ThreadTicks(), and UNREACHABLE.
Referenced by v8::platform::tracing::TracingController::CurrentCpuTimestampMicroseconds().
WaitUntilInitialized()
static void v8::base::ThreadTicks::WaitUntilInitialized () [inline], [static]
Definition at line 438 of file time.h.
                                     {
#if V8_OS_WIN
    WaitUntilInitializedWin();
#endif
  }
Friends And Related Function Documentation
time_internal::TimeBase
template<class TimeClass >
friend class time_internal::TimeBase [friend]
Definition at line 462 of file time.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/time.h
/mnt/V8SourceCode/src/base/platform/time.cc