v8::internal::StartupDeserializer Class Reference
#include <startup-deserializer.h>
Public Member Functions
StartupDeserializer (Isolate *isolate, const SnapshotData *startup_data, bool can_rehash)
void DeserializeIntoIsolate ()
Private Member Functions
void FlushICache ()
void LogNewMapEvents ()
void DeserializeAndCheckExternalReferenceTable ()
Additional Inherited Members
Detailed Description
Definition at line 15 of file startup-deserializer.h.
Constructor & Destructor Documentation
StartupDeserializer()
v8::internal::StartupDeserializer::StartupDeserializer (Isolate * isolate, const SnapshotData * startup_data, bool can_rehash) [inline], [explicit]
Definition at line 17 of file startup-deserializer.h.
      : Deserializer(isolate, startup_data->Payload(),
                     startup_data->GetMagicNumber(), false, can_rehash) {}
Member Function Documentation
DeserializeAndCheckExternalReferenceTable()
void v8::internal::StartupDeserializer::DeserializeAndCheckExternalReferenceTable () [private]
Definition at line 95 of file startup-deserializer.cc.
                                                                    {
  // Verify that any external reference entries that were deduplicated in the
  // serializer are also deduplicated in this isolate.
  ExternalReferenceTable* table = isolate()->external_reference_table();
  while (true) {
    uint32_t index = source()->GetUint30();
    if (index == ExternalReferenceTable::kSizeIsolateIndependent) break;
    uint32_t encoded_index = source()->GetUint30();
    CHECK_EQ(table->address(index), table->address(encoded_index));
  }
}
References v8::internal::ExternalReferenceTable::address(), CHECK_EQ, v8::internal::Isolate::external_reference_table(), v8::internal::SnapshotByteSource::GetUint30(), v8::internal::index, v8::internal::Deserializer< Isolate >::isolate(), v8::internal::ExternalReferenceTable::kSizeIsolateIndependent, and v8::internal::Deserializer< Isolate >::source().
Referenced by DeserializeIntoIsolate().
DeserializeIntoIsolate()
void v8::internal::StartupDeserializer::DeserializeIntoIsolate ()
Definition at line 20 of file startup-deserializer.cc.
                                                 {
  TRACE_EVENT0("v8", "V8.DeserializeIsolate");
  RCS_SCOPE(isolate(), RuntimeCallCounterId::kDeserializeIsolate);
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.profile_deserialization)) timer.Start();
  NestedTimedHistogramScope histogram_timer(
      isolate()->counters()->snapshot_deserialize_isolate());
  HandleScope scope(isolate());
  // No active threads.
  DCHECK_NULL(isolate()->thread_manager()->FirstThreadStateInUse());
  // No active handles.
  DCHECK(isolate()->handle_scope_implementer()->blocks()->empty());
  // Startup object cache is not yet populated.
  DCHECK(isolate()->startup_object_cache()->empty());
  // Builtins are not yet created.
  DCHECK(!isolate()->builtins()->is_initialized());
  {
    DeserializeAndCheckExternalReferenceTable();
    isolate()->heap()->IterateSmiRoots(this);
    isolate()->heap()->IterateRoots(
        this,
        base::EnumSet<SkipRoot>{SkipRoot::kUnserializable, SkipRoot::kWeak,
                                SkipRoot::kTracedHandles});
    IterateStartupObjectCache(isolate(), this);
    isolate()->heap()->IterateWeakRoots(
        this, base::EnumSet<SkipRoot>{SkipRoot::kUnserializable});
    DeserializeDeferredObjects();
    for (DirectHandle<AccessorInfo> info : accessor_infos()) {
      RestoreExternalReferenceRedirector(isolate(), *info);
    }
    for (DirectHandle<FunctionTemplateInfo> info : function_template_infos()) {
      RestoreExternalReferenceRedirector(isolate(), *info);
    }
    // Flush the instruction cache for the entire code-space. Must happen after
    // builtins deserialization.
    FlushICache();
  }
  isolate()->heap()->set_native_contexts_list(
      ReadOnlyRoots(isolate()).undefined_value());
  // The allocation site list is build during root iteration, but if no sites
  // were encountered then it needs to be initialized to undefined.
  if (isolate()->heap()->allocation_sites_list() == Smi::zero()) {
    isolate()->heap()->set_allocation_sites_list(
        ReadOnlyRoots(isolate()).undefined_value());
  }
  isolate()->heap()->set_dirty_js_finalization_registries_list(
      ReadOnlyRoots(isolate()).undefined_value());
  isolate()->heap()->set_dirty_js_finalization_registries_list_tail(
      ReadOnlyRoots(isolate()).undefined_value());
  isolate()->builtins()->MarkInitialized();
  LogNewMapEvents();
  WeakenDescriptorArrays();
  if (should_rehash()) {
    // Hash seed was initialized in ReadOnlyDeserializer.
    Rehash();
  }
  if (V8_UNLIKELY(v8_flags.profile_deserialization)) {
    // ATTENTION: The Memory.json benchmark greps for this exact output. Do not
    // change it without also updating Memory.json.
    const int bytes = source()->length();
    const double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Deserializing isolate (%d bytes) took %0.3f ms]\n", bytes, ms);
  }
}
References v8::internal::Deserializer< Isolate >::accessor_infos(), v8::internal::Isolate::builtins(), v8::internal::DCHECK(), DCHECK_NULL, DeserializeAndCheckExternalReferenceTable(), v8::internal::Deserializer< Isolate >::DeserializeDeferredObjects(), v8::base::ElapsedTimer::Elapsed(), FlushICache(), v8::internal::Deserializer< Isolate >::function_template_infos(), v8::internal::Isolate::heap(), heap(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateSmiRoots(), v8::internal::SerializerDeserializer::IterateStartupObjectCache(), v8::internal::Heap::IterateWeakRoots(), v8::internal::kTracedHandles, v8::internal::kUnserializable, v8::internal::kWeak, v8::internal::SnapshotByteSource::length(), LogNewMapEvents(), v8::internal::Builtins::MarkInitialized(), v8::internal::PrintF(), RCS_SCOPE, v8::internal::Deserializer< Isolate >::Rehash(), v8::internal::SerializerDeserializer::RestoreExternalReferenceRedirector(), v8::internal::Heap::set_allocation_sites_list(), v8::internal::Heap::set_dirty_js_finalization_registries_list(), v8::internal::Heap::set_dirty_js_finalization_registries_list_tail(), v8::internal::Heap::set_native_contexts_list(), v8::internal::Deserializer< Isolate >::should_rehash(), v8::internal::Deserializer< Isolate >::source(), v8::base::ElapsedTimer::Start(), TRACE_EVENT0, v8::internal::v8_flags, V8_UNLIKELY, v8::internal::Deserializer< Isolate >::WeakenDescriptorArrays(), and v8::internal::Smi::zero().
Referenced by v8::internal::Isolate::Init().
FlushICache()
void v8::internal::StartupDeserializer::FlushICache () [private]
Definition at line 111 of file startup-deserializer.cc.
                                      {
  DCHECK(!deserializing_user_code());
  // The entire isolate is newly deserialized. Simply flush all code pages.
  for (PageMetadata* p : *isolate()->heap()->code_space()) {
    FlushInstructionCache(p->area_start(), p->area_end() - p->area_start());
  }
}
References v8::internal::DCHECK(), v8::internal::Deserializer< Isolate >::deserializing_user_code(), v8::internal::FlushInstructionCache(), heap(), and v8::internal::Deserializer< Isolate >::isolate().
Referenced by DeserializeIntoIsolate().
LogNewMapEvents()
void v8::internal::StartupDeserializer::LogNewMapEvents () [private]
Definition at line 107 of file startup-deserializer.cc.
                                          {
  if (v8_flags.log_maps) LOG(isolate(), LogAllMaps());
}
References v8::internal::Deserializer< Isolate >::isolate(), LOG, and v8::internal::v8_flags.
Referenced by DeserializeIntoIsolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/startup-deserializer.h
/mnt/V8SourceCode/src/snapshot/startup-deserializer.cc