v8::internal::interpreter::Interpreter Class Reference
#include <interpreter.h>
Public Member Functions
Interpreter (Isolate *isolate)
virtual ~Interpreter ()=default
Interpreter (const Interpreter &)=delete
Interpreter & operator= (const Interpreter &)=delete
V8_EXPORT_PRIVATE Tagged< Code > GetBytecodeHandler (Bytecode bytecode, OperandScale operand_scale)
void SetBytecodeHandler (Bytecode bytecode, OperandScale operand_scale, Tagged< Code > handler)
V8_EXPORT_PRIVATE DirectHandle< JSObject > GetDispatchCountersObject ()
void ForEachBytecode (const std::function< void(Bytecode, OperandScale)> &f)
void Initialize ()
bool IsDispatchTableInitialized () const
Address dispatch_table_address ()
Address bytecode_dispatch_counters_table ()
Address address_of_interpreter_entry_trampoline_instruction_start () const
Static Public Member Functions
static std::unique_ptr< UnoptimizedCompilationJob > NewCompilationJob (ParseInfo *parse_info, FunctionLiteral *literal, Handle< Script > script, AccountingAllocator *allocator, std::vector< FunctionLiteral * > *eager_inner_literals, LocalIsolate *local_isolate)
static std::unique_ptr< UnoptimizedCompilationJob > NewSourcePositionCollectionJob (ParseInfo *parse_info, FunctionLiteral *literal, Handle< BytecodeArray > existing_bytecode, AccountingAllocator *allocator, LocalIsolate *local_isolate)
Private Member Functions
V8_EXPORT_PRIVATE void InitDispatchCounters ()
V8_EXPORT_PRIVATE uintptr_t GetDispatchCounter (Bytecode from, Bytecode to) const
Static Private Member Functions
static size_t GetDispatchTableIndex (Bytecode bytecode, OperandScale operand_scale)
Private Attributes
Isolate * isolate_
Address dispatch_table_ [kDispatchTableSize]
std::unique_ptr< uintptr_t[]> bytecode_dispatch_counters_table_
Address interpreter_entry_trampoline_instruction_start_
Static Private Attributes
static const int kNumberOfWideVariants = BytecodeOperands::kOperandScaleCount
static const int kDispatchTableSize = kNumberOfWideVariants * (kMaxUInt8 + 1)
static const int kNumberOfBytecodes = static_cast<int>(Bytecode::kLast) + 1
Friends
class SetupInterpreter
class v8::internal::SetupIsolateDelegate
class v8::internal::IgnitionStatisticsTester
Detailed Description
Definition at line 38 of file interpreter.h.
Constructor & Destructor Documentation
Interpreter() [1/2]
v8::internal::interpreter::Interpreter::Interpreter (Isolate * isolate) [explicit]
Definition at line 65 of file interpreter.cc.
    : isolate_(isolate),
      interpreter_entry_trampoline_instruction_start_(kNullAddress) {
  memset(dispatch_table_, 0, sizeof(dispatch_table_));
  if (V8_IGNITION_DISPATCH_COUNTING_BOOL) {
    InitDispatchCounters();
  }
}
References dispatch_table_, InitDispatchCounters(), and V8_IGNITION_DISPATCH_COUNTING_BOOL.
 Interpreter()
virtual v8::internal::interpreter::Interpreter::~Interpreter () [virtual], [default]
Interpreter() [2/2]
v8::internal::interpreter::Interpreter::Interpreter (const Interpreter &) [delete]
Member Function Documentation
address_of_interpreter_entry_trampoline_instruction_start()
Address v8::internal::interpreter::Interpreter::address_of_interpreter_entry_trampoline_instruction_start () const [inline]
Definition at line 88 of file interpreter.h.
                                                                            {
    return reinterpret_cast<Address>(
        &interpreter_entry_trampoline_instruction_start_);
  }
References interpreter_entry_trampoline_instruction_start_.
bytecode_dispatch_counters_table()
Address v8::internal::interpreter::Interpreter::bytecode_dispatch_counters_table () [inline]
Definition at line 84 of file interpreter.h.
                                             {
    return reinterpret_cast<Address>(bytecode_dispatch_counters_table_.get());
  }
References bytecode_dispatch_counters_table_.
dispatch_table_address()
Address v8::internal::interpreter::Interpreter::dispatch_table_address () [inline]
Definition at line 80 of file interpreter.h.
                                   {
    return reinterpret_cast<Address>(&dispatch_table_[0]);
  }
References dispatch_table_.
ForEachBytecode()
void v8::internal::interpreter::Interpreter::ForEachBytecode (const std::function< void(Bytecode, OperandScale)> & f)
Definition at line 329 of file interpreter.cc.
                                                        {
  constexpr OperandScale kOperandScales[] = {
#define VALUE(Name, _) OperandScale::k##Name,
      OPERAND_SCALE_LIST(VALUE)
#undef VALUE
  };
  for (OperandScale operand_scale : kOperandScales) {
    for (int i = 0; i < Bytecodes::kBytecodeCount; i++) {
      f(Bytecodes::FromByte(i), operand_scale);
    }
  }
}
References v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::interpreter::Bytecodes::kBytecodeCount, OPERAND_SCALE_LIST, and VALUE.
Referenced by Initialize().
GetBytecodeHandler()
Tagged< Code > v8::internal::interpreter::Interpreter::GetBytecodeHandler (Bytecode bytecode, OperandScale operand_scale)
Definition at line 114 of file interpreter.cc.
                                                                         {
  Builtin builtin = BuiltinIndexFromBytecode(bytecode, operand_scale);
  return isolate_->builtins()->code(builtin);
}
References v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode(), v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), and isolate_.
GetDispatchCounter()
uintptr_t v8::internal::interpreter::Interpreter::GetDispatchCounter (Bytecode from, Bytecode to) const [private]
Definition at line 379 of file interpreter.cc.
                                                                          {
  int from_index = Bytecodes::ToByte(from);
  int to_index = Bytecodes::ToByte(to);
  CHECK_WITH_MSG(bytecode_dispatch_counters_table_ != nullptr,
                 "Dispatch counters require building with "
                 "v8_enable_ignition_dispatch_counting");
  return bytecode_dispatch_counters_table_[from_index * kNumberOfBytecodes +
                                           to_index];
}
References bytecode_dispatch_counters_table_, CHECK_WITH_MSG, kNumberOfBytecodes, and v8::internal::interpreter::Bytecodes::ToByte().
Referenced by GetDispatchCountersObject().
GetDispatchCountersObject()
DirectHandle< JSObject > v8::internal::interpreter::Interpreter::GetDispatchCountersObject ()
Definition at line 389 of file interpreter.cc.
                                                              {
  DirectHandle<JSObject> counters_map =
      isolate_->factory()->NewJSObjectWithNullProto();
  // Output is a JSON-encoded object of objects.
  //
  // The keys on the top level object are source bytecodes,
  // and corresponding value are objects. Keys on these last are the
  // destinations of the dispatch and the value associated is a counter for
  // the correspondent source-destination dispatch chain.
  //
  // Only non-zero counters are written to file, but an entry in the top-level
  // object is always present, even if the value is empty because all counters
  // for that source are zero.
  for (int from_index = 0; from_index < kNumberOfBytecodes; ++from_index) {
    Bytecode from_bytecode = Bytecodes::FromByte(from_index);
    DirectHandle<JSObject> counters_row =
        isolate_->factory()->NewJSObjectWithNullProto();
    for (int to_index = 0; to_index < kNumberOfBytecodes; ++to_index) {
      Bytecode to_bytecode = Bytecodes::FromByte(to_index);
      uintptr_t counter = GetDispatchCounter(from_bytecode, to_bytecode);
      if (counter > 0) {
        DirectHandle<Object> value =
            isolate_->factory()->NewNumberFromSize(counter);
        JSObject::AddProperty(isolate_, counters_row,
                              Bytecodes::ToString(to_bytecode), value, NONE);
      }
    }
    JSObject::AddProperty(isolate_, counters_map,
                          Bytecodes::ToString(from_bytecode), counters_row,
                          NONE);
  }
  return counters_map;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::interpreter::Bytecodes::FromByte(), GetDispatchCounter(), isolate_, kNumberOfBytecodes, v8::internal::Factory::NewJSObjectWithNullProto(), v8::internal::FactoryBase< Impl >::NewNumberFromSize(), v8::internal::NONE, v8::internal::interpreter::Bytecodes::ToString(), and v8::internal::value.
Referenced by v8::internal::IgnitionStatisticsExtension::GetIgnitionDispatchCounters().
GetDispatchTableIndex()
size_t v8::internal::interpreter::Interpreter::GetDispatchTableIndex (Bytecode bytecode, OperandScale operand_scale) [static], [private]
Definition at line 130 of file interpreter.cc.
                                                                      {
  static const size_t kEntriesPerOperandScale = 1u << kBitsPerByte;
  size_t index = static_cast<size_t>(bytecode);
  return index + BytecodeOperands::OperandScaleAsIndex(operand_scale) *
                     kEntriesPerOperandScale;
}
References v8::internal::index, v8::internal::kBitsPerByte, and v8::internal::interpreter::BytecodeOperands::OperandScaleAsIndex().
Referenced by SetBytecodeHandler().
InitDispatchCounters()
void v8::internal::interpreter::Interpreter::InitDispatchCounters () [private]
Definition at line 75 of file interpreter.cc.
                                       {
  static const int kBytecodeCount = static_cast<int>(Bytecode::kLast) + 1;
  bytecode_dispatch_counters_table_.reset(
      new uintptr_t[kBytecodeCount * kBytecodeCount]);
  memset(bytecode_dispatch_counters_table_.get(), 0,
         sizeof(uintptr_t) * kBytecodeCount * kBytecodeCount);
}
References bytecode_dispatch_counters_table_, and v8::internal::interpreter::kLast.
Referenced by Interpreter().
Initialize()
void v8::internal::interpreter::Interpreter::Initialize ()
Definition at line 344 of file interpreter.cc.
                             {
  Builtins* builtins = isolate_->builtins();
  // Set the interpreter entry trampoline entry point now that builtins are
  // initialized.
  DirectHandle<Code> code = BUILTIN_CODE(isolate_, InterpreterEntryTrampoline);
  DCHECK(builtins->is_initialized());
  DCHECK(!code->has_instruction_stream());
  interpreter_entry_trampoline_instruction_start_ = code->instruction_start();
  // Initialize the dispatch table.
  ForEachBytecode([=, this](Bytecode bytecode, OperandScale operand_scale) {
    Builtin builtin = BuiltinIndexFromBytecode(bytecode, operand_scale);
    Tagged<Code> handler = builtins->code(builtin);
    if (Bytecodes::BytecodeHasHandler(bytecode, operand_scale)) {
#ifdef DEBUG
      std::string builtin_name(Builtins::name(builtin));
      std::string expected_name =
          (Bytecodes::IsShortStar(bytecode)
               ? "ShortStar"
               : Bytecodes::ToString(bytecode, operand_scale, "")) +
          "Handler";
      DCHECK_EQ(expected_name, builtin_name);
#endif
    }
    SetBytecodeHandler(bytecode, operand_scale, handler);
  });
  DCHECK(IsDispatchTableInitialized());
}
References BUILTIN_CODE, v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode(), v8::internal::Isolate::builtins(), v8::internal::interpreter::Bytecodes::BytecodeHasHandler(), v8::internal::Builtins::code(), code, v8::internal::DCHECK(), DCHECK_EQ, ForEachBytecode(), interpreter_entry_trampoline_instruction_start_, v8::internal::Builtins::is_initialized(), IsDispatchTableInitialized(), isolate_, v8::internal::interpreter::Bytecodes::IsShortStar(), v8::internal::Builtins::name(), SetBytecodeHandler(), v8::internal::string, and v8::internal::interpreter::Bytecodes::ToString().
Referenced by v8::internal::Isolate::Init().
IsDispatchTableInitialized()
bool v8::internal::interpreter::Interpreter::IsDispatchTableInitialized () const
Definition at line 375 of file interpreter.cc.
                                                   {
  return dispatch_table_[0] != kNullAddress;
}
References dispatch_table_, and v8::internal::kNullAddress.
Referenced by Initialize().
NewCompilationJob()
std::unique_ptr< UnoptimizedCompilationJob > v8::internal::interpreter::Interpreter::NewCompilationJob (ParseInfo * parse_info, FunctionLiteral * literal, Handle< Script > script, AccountingAllocator * allocator, std::vector< FunctionLiteral * > * eager_inner_literals, LocalIsolate * local_isolate) [static]
Definition at line 308 of file interpreter.cc.
                                 {
  return std::make_unique<InterpreterCompilationJob>(
      parse_info, literal, script, allocator, eager_inner_literals,
      local_isolate);
}
References v8::internal::script.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::ExecuteSingleUnoptimizedCompilationJob().
NewSourcePositionCollectionJob()
std::unique_ptr< UnoptimizedCompilationJob > v8::internal::interpreter::Interpreter::NewSourcePositionCollectionJob (ParseInfo * parse_info, FunctionLiteral * literal, Handle< BytecodeArray > existing_bytecode, AccountingAllocator * allocator, LocalIsolate * local_isolate) [static]
Definition at line 319 of file interpreter.cc.
                                 {
  auto job = std::make_unique<InterpreterCompilationJob>(
      parse_info, literal, Handle<Script>(), allocator, nullptr, local_isolate);
  job->compilation_info()->SetBytecodeArray(existing_bytecode);
  return job;
}
Referenced by v8::internal::Compiler::CollectSourcePositions().
operator=()
Interpreter& v8::internal::interpreter::Interpreter::operator= (const Interpreter &) [delete]
SetBytecodeHandler()
void v8::internal::interpreter::Interpreter::SetBytecodeHandler (Bytecode bytecode, OperandScale operand_scale, Tagged< Code > handler)
Definition at line 120 of file interpreter.cc.
                                                           {
  DCHECK(!handler->has_instruction_stream());
  DCHECK(handler->kind() == CodeKind::BYTECODE_HANDLER);
  size_t index = GetDispatchTableIndex(bytecode, operand_scale);
  dispatch_table_[index] = handler->instruction_start();
}
References v8::internal::DCHECK(), dispatch_table_, GetDispatchTableIndex(), and v8::internal::index.
Referenced by Initialize().
Friends And Related Function Documentation
SetupInterpreter
friend class SetupInterpreter [friend]
Definition at line 94 of file interpreter.h.
v8::internal::IgnitionStatisticsTester
friend class v8::internal::IgnitionStatisticsTester [friend]
Definition at line 96 of file interpreter.h.
v8::internal::SetupIsolateDelegate
friend class v8::internal::SetupIsolateDelegate [friend]
Definition at line 95 of file interpreter.h.
Member Data Documentation
bytecode_dispatch_counters_table_
std::unique_ptr<uintptr_t[]> v8::internal::interpreter::Interpreter::bytecode_dispatch_counters_table_ [private]
Definition at line 112 of file interpreter.h.
Referenced by bytecode_dispatch_counters_table(), GetDispatchCounter(), and InitDispatchCounters().
dispatch_table_
Address v8::internal::interpreter::Interpreter::dispatch_table_[kDispatchTableSize] [private]
Definition at line 111 of file interpreter.h.
Referenced by dispatch_table_address(), Interpreter(), IsDispatchTableInitialized(), and SetBytecodeHandler().
interpreter_entry_trampoline_instruction_start_
Address v8::internal::interpreter::Interpreter::interpreter_entry_trampoline_instruction_start_ [private]
Definition at line 113 of file interpreter.h.
Referenced by address_of_interpreter_entry_trampoline_instruction_start(), and Initialize().
isolate_
Isolate* v8::internal::interpreter::Interpreter::isolate_ [private]
Definition at line 110 of file interpreter.h.
Referenced by GetBytecodeHandler(), GetDispatchCountersObject(), and Initialize().
kDispatchTableSize
const int v8::internal::interpreter::Interpreter::kDispatchTableSize = kNumberOfWideVariants * (kMaxUInt8 + 1) [static], [private]
Definition at line 107 of file interpreter.h.
kNumberOfBytecodes
const int v8::internal::interpreter::Interpreter::kNumberOfBytecodes = static_cast<int>(Bytecode::kLast) + 1 [static], [private]
Definition at line 108 of file interpreter.h.
Referenced by GetDispatchCounter(), and GetDispatchCountersObject().
kNumberOfWideVariants
const int v8::internal::interpreter::Interpreter::kNumberOfWideVariants = BytecodeOperands::kOperandScaleCount [static], [private]
Definition at line 106 of file interpreter.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/interpreter.h
/mnt/V8SourceCode/src/interpreter/interpreter.cc