v8::internal::CompiledReplacement Class Reference
Classes
struct ReplacementPart
Public Member Functions
CompiledReplacement (Isolate *isolate)
bool Compile (Isolate *isolate, DirectHandle< JSRegExp > regexp, DirectHandle< RegExpData > regexp_data, DirectHandle< String > replacement, int capture_count, int subject_length)
void Apply (ReplacementStringBuilder *builder, int match_from, int match_to, int32_t *match)
int parts ()
Private Types
enum PartType {
SUBJECT_PREFIX = 1
, SUBJECT_SUFFIX
, SUBJECT_CAPTURE
, REPLACEMENT_SUBSTRING
,
REPLACEMENT_STRING
, EMPTY_REPLACEMENT
, NUMBER_OF_PART_TYPES
 }
Private Member Functions
template<typename Char >
bool ParseReplacementPattern (base::Vector< Char > characters, Tagged< FixedArray > capture_name_map, int capture_count, int subject_length)
Private Attributes
base::SmallVector< ReplacementPart, kStaticVectorSlots > parts_
DirectHandleSmallVector< String, kStaticVectorSlots > replacement_substrings_
Detailed Description
Definition at line 87 of file runtime-regexp.cc.
Member Enumeration Documentation
PartType
enum v8::internal::CompiledReplacement::PartType [private]
Enumerator
SUBJECT_PREFIX
SUBJECT_SUFFIX
SUBJECT_CAPTURE
REPLACEMENT_SUBSTRING
REPLACEMENT_STRING
EMPTY_REPLACEMENT
NUMBER_OF_PART_TYPES
Definition at line 106 of file runtime-regexp.cc.
                {
    SUBJECT_PREFIX = 1,
    SUBJECT_SUFFIX,
    SUBJECT_CAPTURE,
    REPLACEMENT_SUBSTRING,
    REPLACEMENT_STRING,
    EMPTY_REPLACEMENT,
    NUMBER_OF_PART_TYPES
  };
Constructor & Destructor Documentation
CompiledReplacement()
v8::internal::CompiledReplacement::CompiledReplacement (Isolate * isolate) [inline], [explicit]
Definition at line 89 of file runtime-regexp.cc.
      : replacement_substrings_(isolate) {}
Member Function Documentation
Apply()
void v8::internal::CompiledReplacement::Apply (ReplacementStringBuilder * builder, int match_from, int match_to, int32_t * match)
Definition at line 404 of file runtime-regexp.cc.
                                                                              {
  DCHECK_LT(0, parts_.size());
  for (ReplacementPart& part : parts_) {
    switch (part.tag) {
      case SUBJECT_PREFIX:
        if (match_from > 0) builder->AddSubjectSlice(0, match_from);
        break;
      case SUBJECT_SUFFIX: {
        int subject_length = part.data;
        if (match_to < subject_length) {
          builder->AddSubjectSlice(match_to, subject_length);
        }
        break;
      }
      case SUBJECT_CAPTURE: {
        int capture = part.data;
        int from = match[capture * 2];
        int to = match[capture * 2 + 1];
        if (from >= 0 && to > from) {
          builder->AddSubjectSlice(from, to);
        }
        break;
      }
      case REPLACEMENT_SUBSTRING:
      case REPLACEMENT_STRING:
        builder->AddString(replacement_substrings_[part.data]);
        break;
      case EMPTY_REPLACEMENT:
        break;
      default:
        UNREACHABLE();
    }
  }
}
References v8::internal::ReplacementStringBuilder::AddString(), v8::internal::ReplacementStringBuilder::AddSubjectSlice(), DCHECK_LT, EMPTY_REPLACEMENT, parts_, REPLACEMENT_STRING, REPLACEMENT_SUBSTRING, replacement_substrings_, SUBJECT_CAPTURE, SUBJECT_PREFIX, SUBJECT_SUFFIX, and v8::internal::UNREACHABLE().
Referenced by v8::internal::StringReplaceGlobalRegExpWithString().
Compile()
bool v8::internal::CompiledReplacement::Compile (Isolate * isolate, DirectHandle< JSRegExp > regexp, DirectHandle< RegExpData > regexp_data, DirectHandle< String > replacement, int capture_count, int subject_length)
Definition at line 346 of file runtime-regexp.cc.
                                                                         {
  {
    DisallowGarbageCollection no_gc;
    String::FlatContent content = replacement->GetFlatContent(no_gc);
    DCHECK(content.IsFlat());
    Tagged<FixedArray> capture_name_map;
    if (capture_count > 0) {
      // capture_count > 0 implies IrRegExpData. Since capture_count is in
      // trusted space, this is not a SBXCHECK.
      DCHECK(Is<IrRegExpData>(*regexp_data));
      Tagged<IrRegExpData> re_data = Cast<IrRegExpData>(*regexp_data);
      Tagged<Object> maybe_capture_name_map = re_data->capture_name_map();
      if (IsFixedArray(maybe_capture_name_map)) {
        capture_name_map = Cast<FixedArray>(maybe_capture_name_map);
      }
    }
    bool simple;
    if (content.IsOneByte()) {
      simple =
          ParseReplacementPattern(content.ToOneByteVector(), capture_name_map,
                                  capture_count, subject_length);
    } else {
      DCHECK(content.IsTwoByte());
      simple = ParseReplacementPattern(content.ToUC16Vector(), capture_name_map,
                                       capture_count, subject_length);
    }
    if (simple) return true;
  }
  // Find substrings of replacement string and create them as String objects.
  replacement_substrings_.reserve(parts());
  int substring_index = 0;
  for (ReplacementPart& part : parts_) {
    int tag = part.tag;
    if (tag <= 0) { // A replacement string slice.
      int from = -tag;
      int to = part.data;
      replacement_substrings_.emplace_back(
          isolate->factory()->NewSubString(replacement, from, to));
      part.tag = REPLACEMENT_SUBSTRING;
      part.data = substring_index;
      substring_index++;
    } else if (tag == REPLACEMENT_STRING) {
      replacement_substrings_.emplace_back(replacement);
      part.data = substring_index;
      substring_index++;
    }
  }
  return false;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ParseReplacementPattern(), parts(), parts_, REPLACEMENT_STRING, REPLACEMENT_SUBSTRING, replacement_substrings_, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by v8::internal::StringReplaceGlobalRegExpWithString().
ParseReplacementPattern()
template<typename Char >
bool v8::internal::CompiledReplacement::ParseReplacementPattern (base::Vector< Char > characters, Tagged< FixedArray > capture_name_map, int capture_count, int subject_length) [inline], [private]
Definition at line 166 of file runtime-regexp.cc.
                                                                      {
    // Equivalent to String::GetSubstitution, except that this method converts
    // the replacement string into an internal representation that avoids
    // repeated parsing when used repeatedly.
    int length = characters.length();
    int last = 0;
    for (int i = 0; i < length; i++) {
      Char c = characters[i];
      if (c == '$') {
        int next_index = i + 1;
        if (next_index == length) { // No next character!
          break;
        }
        Char c2 = characters[next_index];
        switch (c2) {
          case '$':
            if (i > last) {
              // There is a substring before. Include the first "$".
              parts_.emplace_back(
                  ReplacementPart::ReplacementSubString(last, next_index));
              last = next_index + 1; // Continue after the second "$".
            } else {
              // Let the next substring start with the second "$".
              last = next_index;
            }
            i = next_index;
            break;
          case '`':
            if (i > last) {
              parts_.emplace_back(
                  ReplacementPart::ReplacementSubString(last, i));
            }
            parts_.emplace_back(ReplacementPart::SubjectPrefix());
            i = next_index;
            last = i + 1;
            break;
          case '\'':
            if (i > last) {
              parts_.emplace_back(
                  ReplacementPart::ReplacementSubString(last, i));
            }
            parts_.emplace_back(ReplacementPart::SubjectSuffix(subject_length));
            i = next_index;
            last = i + 1;
            break;
          case '&':
            if (i > last) {
              parts_.emplace_back(
                  ReplacementPart::ReplacementSubString(last, i));
            }
            parts_.emplace_back(ReplacementPart::SubjectMatch());
            i = next_index;
            last = i + 1;
            break;
          case '0':
          case '1':
          case '2':
          case '3':
          case '4':
          case '5':
          case '6':
          case '7':
          case '8':
          case '9': {
            int capture_ref = c2 - '0';
            if (capture_ref > capture_count) {
              i = next_index;
              continue;
            }
            int second_digit_index = next_index + 1;
            if (second_digit_index < length) {
              // Peek ahead to see if we have two digits.
              Char c3 = characters[second_digit_index];
              if ('0' <= c3 && c3 <= '9') { // Double digits.
                int double_digit_ref = capture_ref * 10 + c3 - '0';
                if (double_digit_ref <= capture_count) {
                  next_index = second_digit_index;
                  capture_ref = double_digit_ref;
                }
              }
            }
            if (capture_ref > 0) {
              if (i > last) {
                parts_.emplace_back(
                    ReplacementPart::ReplacementSubString(last, i));
              }
              DCHECK(capture_ref <= capture_count);
              parts_.emplace_back(ReplacementPart::SubjectCapture(capture_ref));
              last = next_index + 1;
            }
            i = next_index;
            break;
          }
          case '<': {
            if (capture_name_map.is_null()) {
              i = next_index;
              break;
            }
            // Scan until the next '>', and let the enclosed substring be the
            // groupName.
            const int name_start_index = next_index + 1;
            int closing_bracket_index = -1;
            for (int j = name_start_index; j < length; j++) {
              if (characters[j] == '>') {
                closing_bracket_index = j;
                break;
              }
            }
            // If no closing bracket is found, '$<' is treated as a string
            // literal.
            if (closing_bracket_index == -1) {
              i = next_index;
              break;
            }
            if (i > last) {
              parts_.emplace_back(
                  ReplacementPart::ReplacementSubString(last, i));
            }
            base::Vector<Char> requested_name =
                characters.SubVector(name_start_index, closing_bracket_index);
            // If capture is undefined or does not exist, replace the text
            // through the following '>' with the empty string.
            // Otherwise, replace the text through the following '>' with
            // ? ToString(capture).
            // For duplicated capture group names we don't know which of them
            // matches at this point in time, so we create a separate
            // replacement for each possible match. When applying the
            // replacement unmatched groups will be skipped.
            int capture_index = 0;
            int capture_name_map_index = 0;
            while (capture_index != -1) {
              capture_index = LookupNamedCapture(
                  [=](Tagged<String> capture_name) {
                    return capture_name->IsEqualTo(requested_name);
                  },
                  capture_name_map, &capture_name_map_index);
              DCHECK(capture_index == -1 ||
                     (1 <= capture_index && capture_index <= capture_count));
              parts_.emplace_back(
                  capture_index == -1
                      ? ReplacementPart::EmptyReplacement()
                      : ReplacementPart::SubjectCapture(capture_index));
            }
            last = closing_bracket_index + 1;
            i = closing_bracket_index;
            break;
          }
          default:
            i = next_index;
            break;
        }
      }
    }
    if (length > last) {
      if (last == 0) {
        // Replacement is simple. Do not use Apply to do the replacement.
        return true;
      } else {
        parts_.emplace_back(
            ReplacementPart::ReplacementSubString(last, length));
      }
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::CompiledReplacement::ReplacementPart::EmptyReplacement(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Tagged< HeapObject >::is_null(), v8::base::Vector< T >::length(), v8::internal::length, v8::internal::anonymous_namespace{runtime-regexp.cc}::LookupNamedCapture(), parts_, v8::internal::CompiledReplacement::ReplacementPart::ReplacementSubString(), v8::internal::CompiledReplacement::ReplacementPart::SubjectCapture(), v8::internal::CompiledReplacement::ReplacementPart::SubjectMatch(), v8::internal::CompiledReplacement::ReplacementPart::SubjectPrefix(), v8::internal::CompiledReplacement::ReplacementPart::SubjectSuffix(), and v8::base::Vector< T >::SubVector().
Referenced by Compile().
parts()
int v8::internal::CompiledReplacement::parts () [inline]
Definition at line 103 of file runtime-regexp.cc.
{ return static_cast<int>(parts_.size()); }
References parts_.
Referenced by Compile(), and v8::internal::StringReplaceGlobalRegExpWithString().
Member Data Documentation
parts_
base::SmallVector<ReplacementPart, kStaticVectorSlots> v8::internal::CompiledReplacement::parts_ [private]
Definition at line 342 of file runtime-regexp.cc.
Referenced by Apply(), Compile(), ParseReplacementPattern(), and parts().
replacement_substrings_
DirectHandleSmallVector<String, kStaticVectorSlots> v8::internal::CompiledReplacement::replacement_substrings_ [private]
Definition at line 343 of file runtime-regexp.cc.
Referenced by Apply(), and Compile().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-regexp.cc