v8::internal::compiler::ZoneStats Class Reference
#include <zone-stats.h>
Classes
class Scope
class StatsScope
Public Member Functions
ZoneStats (AccountingAllocator *allocator)
~ZoneStats ()
ZoneStats (const ZoneStats &)=delete
ZoneStats & operator= (const ZoneStats &)=delete
size_t GetMaxAllocatedBytes () const
size_t GetTotalAllocatedBytes () const
size_t GetCurrentAllocatedBytes () const
Private Types
using Zones = std::vector< Zone * >
using Stats = std::vector< StatsScope * >
Private Member Functions
Zone * NewEmptyZone (const char *zone_name)
void ReturnZone (Zone *zone)
Private Attributes
Zones zones_
Stats stats_
size_t max_allocated_bytes_
size_t total_deleted_bytes_
AccountingAllocator * allocator_
Static Private Attributes
static const size_t kMaxUnusedSize = 3
Detailed Description
Definition at line 17 of file zone-stats.h.
Member Typedef Documentation
Stats
using v8::internal::compiler::ZoneStats::Stats = std::vector<StatsScope*> [private]
Definition at line 104 of file zone-stats.h.
Zones
using v8::internal::compiler::ZoneStats::Zones = std::vector<Zone*> [private]
Definition at line 103 of file zone-stats.h.
Constructor & Destructor Documentation
ZoneStats() [1/2]
v8::internal::compiler::ZoneStats::ZoneStats (AccountingAllocator * allocator) [explicit]
Definition at line 65 of file zone-stats.cc.
    : max_allocated_bytes_(0), total_deleted_bytes_(0), allocator_(allocator) {}
 ZoneStats()
v8::internal::compiler::ZoneStats::~ZoneStats ()
Definition at line 68 of file zone-stats.cc.
                      {
  DCHECK(zones_.empty());
  DCHECK(stats_.empty());
}
References v8::internal::DCHECK(), stats_, and zones_.
ZoneStats() [2/2]
v8::internal::compiler::ZoneStats::ZoneStats (const ZoneStats &) [delete]
Member Function Documentation
GetCurrentAllocatedBytes()
size_t v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes () const
Definition at line 77 of file zone-stats.cc.
                                                 {
  size_t total = 0;
  for (Zone* zone : zones_) {
    total += static_cast<size_t>(zone->allocation_size());
  }
  return total;
}
References zones_.
Referenced by v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin(), v8::internal::compiler::ZoneStats::StatsScope::GetMaxAllocatedBytes(), GetMaxAllocatedBytes(), GetTotalAllocatedBytes(), ReturnZone(), and v8::internal::compiler::ZoneStats::StatsScope::ZoneReturned().
GetMaxAllocatedBytes()
size_t v8::internal::compiler::ZoneStats::GetMaxAllocatedBytes () const
Definition at line 73 of file zone-stats.cc.
                                             {
  return std::max(max_allocated_bytes_, GetCurrentAllocatedBytes());
}
References GetCurrentAllocatedBytes(), and max_allocated_bytes_.
GetTotalAllocatedBytes()
size_t v8::internal::compiler::ZoneStats::GetTotalAllocatedBytes () const
Definition at line 85 of file zone-stats.cc.
                                               {
  return total_deleted_bytes_ + GetCurrentAllocatedBytes();
}
References GetCurrentAllocatedBytes(), and total_deleted_bytes_.
NewEmptyZone()
Zone * v8::internal::compiler::ZoneStats::NewEmptyZone (const char * zone_name) [private]
Definition at line 89 of file zone-stats.cc.
                                                   {
  Zone* zone = new Zone(allocator_, zone_name);
  zones_.push_back(zone);
  return zone;
}
References allocator_, and zones_.
operator=()
ZoneStats& v8::internal::compiler::ZoneStats::operator= (const ZoneStats &) [delete]
ReturnZone()
void v8::internal::compiler::ZoneStats::ReturnZone (Zone * zone) [private]
Definition at line 95 of file zone-stats.cc.
                                     {
  size_t current_total = GetCurrentAllocatedBytes();
  // Update max.
  max_allocated_bytes_ = std::max(max_allocated_bytes_, current_total);
  // Update stats.
  for (StatsScope* stat_scope : stats_) {
    stat_scope->ZoneReturned(zone);
  }
  // Remove from used.
  Zones::iterator it = std::find(zones_.begin(), zones_.end(), zone);
  DCHECK(it != zones_.end());
  zones_.erase(it);
  total_deleted_bytes_ += static_cast<size_t>(zone->allocation_size());
  delete zone;
}
References v8::internal::Zone::allocation_size(), v8::internal::DCHECK(), GetCurrentAllocatedBytes(), max_allocated_bytes_, stats_, total_deleted_bytes_, and zones_.
Member Data Documentation
allocator_
AccountingAllocator* v8::internal::compiler::ZoneStats::allocator_ [private]
Definition at line 110 of file zone-stats.h.
Referenced by NewEmptyZone().
kMaxUnusedSize
const size_t v8::internal::compiler::ZoneStats::kMaxUnusedSize = 3 [static], [private]
Definition at line 102 of file zone-stats.h.
max_allocated_bytes_
size_t v8::internal::compiler::ZoneStats::max_allocated_bytes_ [private]
Definition at line 108 of file zone-stats.h.
Referenced by v8::internal::compiler::ZoneStats::StatsScope::GetMaxAllocatedBytes(), GetMaxAllocatedBytes(), ReturnZone(), and v8::internal::compiler::ZoneStats::StatsScope::ZoneReturned().
stats_
Stats v8::internal::compiler::ZoneStats::stats_ [private]
Definition at line 107 of file zone-stats.h.
Referenced by ReturnZone(), v8::internal::compiler::ZoneStats::StatsScope::StatsScope(), and ~ZoneStats().
total_deleted_bytes_
size_t v8::internal::compiler::ZoneStats::total_deleted_bytes_ [private]
Definition at line 109 of file zone-stats.h.
Referenced by GetTotalAllocatedBytes(), and ReturnZone().
zones_
Zones v8::internal::compiler::ZoneStats::zones_ [private]
Definition at line 106 of file zone-stats.h.
Referenced by GetCurrentAllocatedBytes(), NewEmptyZone(), ReturnZone(), v8::internal::compiler::ZoneStats::StatsScope::StatsScope(), and ~ZoneStats().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/zone-stats.h
/mnt/V8SourceCode/src/compiler/zone-stats.cc