v8::internal::compiler::turboshaft::WordRepresentation Class Reference
#include <representations.h>
Public Types
enum class Enum : uint8_t { kWord32 = static_cast<int>(RegisterRepresentation::Enum::kWord32)
, kWord64 = static_cast<int>(RegisterRepresentation::Enum::kWord64)
 }
Public Member Functions
constexpr WordRepresentation (Enum value)
WordRepresentation ()=default
constexpr WordRepresentation (RegisterRepresentation rep)
constexpr Enum value () const
constexpr operator Enum () const
constexpr uint64_t MaxUnsignedValue () const
constexpr int64_t MinSignedValue () const
constexpr int64_t MaxSignedValue () const
Static Public Member Functions
static constexpr WordRepresentation Word32 ()
static constexpr WordRepresentation Word64 ()
static constexpr WordRepresentation WordPtr ()
Detailed Description
Definition at line 427 of file representations.h.
Member Enumeration Documentation
Enum
enum v8::internal::compiler::turboshaft::WordRepresentation::Enum : uint8_t [strong]
Enumerator
kWord32
kWord64
Definition at line 429 of file representations.h.
                  : uint8_t {
    kWord32 = static_cast<int>(RegisterRepresentation::Enum::kWord32),
    kWord64 = static_cast<int>(RegisterRepresentation::Enum::kWord64)
  };
Constructor & Destructor Documentation
WordRepresentation() [1/3]
constexpr v8::internal::compiler::turboshaft::WordRepresentation::WordRepresentation (Enum value) [inline], [explicit], [constexpr]
Definition at line 433 of file representations.h.
      : RegisterRepresentation(
            static_cast<RegisterRepresentation::Enum>(value)) {}
WordRepresentation() [2/3]
v8::internal::compiler::turboshaft::WordRepresentation::WordRepresentation () [default]
Referenced by Word32(), Word64(), and WordPtr().
WordRepresentation() [3/3]
constexpr v8::internal::compiler::turboshaft::WordRepresentation::WordRepresentation (RegisterRepresentation rep) [inline], [explicit], [constexpr]
Definition at line 437 of file representations.h.
      : WordRepresentation(static_cast<Enum>(rep.value())) {
    DCHECK(rep.IsWord());
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsWord().
Member Function Documentation
MaxSignedValue()
constexpr int64_t v8::internal::compiler::turboshaft::WordRepresentation::MaxSignedValue () const [inline], [constexpr]
Definition at line 474 of file representations.h.
                                           {
    switch (this->value()) {
      case Word32():
        return std::numeric_limits<int32_t>::max();
      case Word64():
        return std::numeric_limits<int64_t>::max();
    }
  }
References value(), Word32(), and Word64().
Referenced by v8::internal::compiler::turboshaft::ConstantOp::Validate().
MaxUnsignedValue()
constexpr uint64_t v8::internal::compiler::turboshaft::WordRepresentation::MaxUnsignedValue () const [inline], [constexpr]
Definition at line 458 of file representations.h.
                                              {
    switch (this->value()) {
      case Word32():
        return std::numeric_limits<uint32_t>::max();
      case Word64():
        return std::numeric_limits<uint64_t>::max();
    }
  }
References value(), Word32(), and Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceWithTruncation(), and v8::internal::compiler::turboshaft::ConstantOp::Validate().
MinSignedValue()
constexpr int64_t v8::internal::compiler::turboshaft::WordRepresentation::MinSignedValue () const [inline], [constexpr]
Definition at line 466 of file representations.h.
                                           {
    switch (this->value()) {
      case Word32():
        return std::numeric_limits<int32_t>::min();
      case Word64():
        return std::numeric_limits<int64_t>::min();
    }
  }
References value(), Word32(), and Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv().
operator Enum()
constexpr v8::internal::compiler::turboshaft::WordRepresentation::operator Enum () const [inline], [constexpr]
Definition at line 456 of file representations.h.
{ return value(); }
References value().
value()
constexpr Enum v8::internal::compiler::turboshaft::WordRepresentation::value () const [inline], [constexpr]
Definition at line 453 of file representations.h.
                               {
    return static_cast<Enum>(RegisterRepresentation::value());
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::value().
Referenced by v8::internal::compiler::IsWord32Binop(), MaxSignedValue(), MaxUnsignedValue(), MinSignedValue(), operator Enum(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordConstant().
Word32()
static constexpr WordRepresentation v8::internal::compiler::turboshaft::WordRepresentation::Word32 () [inline], [static], [constexpr]
Definition at line 442 of file representations.h.
                                               {
    return WordRepresentation(Enum::kWord32);
  }
References kWord32, and WordRepresentation().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterations(), v8::internal::compiler::turboshaft::WordUnaryOp::IsSupported(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), MaxSignedValue(), MaxUnsignedValue(), MinSignedValue(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TruncateWord(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop(), v8::internal::compiler::turboshaft::Typer::TypeWordBinop(), v8::internal::compiler::turboshaft::WordBinopDeoptOnOverflowOp::Validate(), v8::internal::compiler::turboshaft::ConstantOp::Validate(), v8::internal::compiler::turboshaft::ConvertUntaggedToJSPrimitiveOp::Validate(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::InstructionSelector::VisitWordCompareZero(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ZeroExtendWord32ToRep().
Word64()
static constexpr WordRepresentation v8::internal::compiler::turboshaft::WordRepresentation::Word64 () [inline], [static], [constexpr]
Definition at line 445 of file representations.h.
                                               {
    return WordRepresentation(Enum::kWord64);
  }
References kWord64, and WordRepresentation().
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterations(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant(), v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant(), MaxSignedValue(), MaxUnsignedValue(), MinSignedValue(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::outputs_rep(), v8::internal::compiler::turboshaft::OverflowCheckedUnaryOp::outputs_rep(), v8::internal::compiler::turboshaft::TryChangeOp::outputs_rep(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::ProcessOperation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceUnsignedDiv(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Shift(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::StoreLoadInfo(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TruncateWord(), v8::internal::compiler::turboshaft::detail::BitfieldCheck::TryDetectShiftAndMaskOneBit(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop(), v8::internal::compiler::turboshaft::Typer::TypeWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ZeroExtendWord32ToRep().
WordPtr()
static constexpr WordRepresentation v8::internal::compiler::turboshaft::WordRepresentation::WordPtr () [inline], [static], [constexpr]
Definition at line 449 of file representations.h.
                                                {
    return WordRepresentation(RegisterRepresentation::WordPtr());
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr(), and WordRepresentation().
Referenced by v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Allocate(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustElementScale(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustOffset(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordPtrConstant().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/representations.h