v8::internal::compiler::SpecialRPONumberer Class Reference
Classes
struct LoopInfo
struct SpecialRPOStackFrame
Public Member Functions
SpecialRPONumberer (Zone *zone, Schedule *schedule)
void ComputeSpecialRPO ()
void UpdateSpecialRPO (BasicBlock *entry, BasicBlock *end)
void SerializeRPOIntoSchedule ()
void PrintAndVerifySpecialRPO ()
const ZoneVector< BasicBlock * > & GetOutgoingBlocks (BasicBlock *block)
bool HasLoopBlocks () const
Private Types
using Backedge = std::pair< BasicBlock *, size_t >
Private Member Functions
int Push (int depth, BasicBlock *child, int unvisited)
BasicBlock * PushFront (BasicBlock *head, BasicBlock *block)
BasicBlock * BeyondEndSentinel ()
void ComputeAndInsertSpecialRPO (BasicBlock *entry, BasicBlock *end)
void ComputeLoopInfo (ZoneVector< SpecialRPOStackFrame > *queue, size_t num_loops, ZoneVector< Backedge > *backedges)
Static Private Member Functions
static int GetLoopNumber (BasicBlock *block)
static void SetLoopNumber (BasicBlock *block, int loop_number)
static bool HasLoopNumber (BasicBlock *block)
Private Attributes
Zone * zone_
Schedule * schedule_
BasicBlock * order_
BasicBlock * beyond_end_
ZoneVector< LoopInfo > loops_
ZoneVector< Backedge > backedges_
ZoneVector< SpecialRPOStackFrame > stack_
size_t previous_block_count_
ZoneVector< BasicBlock * > const empty_
Static Private Attributes
static const int kBlockOnStack = -2
static const int kBlockVisited1 = -3
static const int kBlockVisited2 = -4
static const int kBlockUnvisited1 = -1
static const int kBlockUnvisited2 = kBlockVisited1
Detailed Description
Definition at line 661 of file scheduler.cc.
Member Typedef Documentation
Backedge
using v8::internal::compiler::SpecialRPONumberer::Backedge = std::pair<BasicBlock*, size_t> [private]
Definition at line 720 of file scheduler.cc.
Constructor & Destructor Documentation
SpecialRPONumberer()
v8::internal::compiler::SpecialRPONumberer::SpecialRPONumberer (Zone * zone, Schedule * schedule) [inline]
Definition at line 663 of file scheduler.cc.
      : zone_(zone),
        schedule_(schedule),
        order_(nullptr),
        beyond_end_(nullptr),
        loops_(zone),
        backedges_(zone),
        stack_(zone),
        previous_block_count_(0),
        empty_(0, zone) {}
Member Function Documentation
BeyondEndSentinel()
BasicBlock* v8::internal::compiler::SpecialRPONumberer::BeyondEndSentinel () [inline], [private]
Definition at line 775 of file scheduler.cc.
                                  {
    if (beyond_end_ == nullptr) {
      BasicBlock::Id id = BasicBlock::Id::FromInt(-1);
      beyond_end_ = schedule_->zone()->New<BasicBlock>(schedule_->zone(), id);
    }
    return beyond_end_;
  }
References beyond_end_, v8::internal::compiler::BasicBlock::Id::FromInt(), v8::internal::Zone::New(), schedule_, and v8::internal::compiler::Schedule::zone().
Referenced by ComputeAndInsertSpecialRPO(), and SerializeRPOIntoSchedule().
ComputeAndInsertSpecialRPO()
void v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO (BasicBlock * entry, BasicBlock * end) [inline], [private]
Definition at line 785 of file scheduler.cc.
                                                                      {
    // RPO should not have been serialized for this schedule yet.
    CHECK_EQ(kBlockUnvisited1, schedule_->start()->loop_number());
    CHECK_EQ(kBlockUnvisited1, schedule_->start()->rpo_number());
    CHECK_EQ(0, static_cast<int>(schedule_->rpo_order()->size()));
    // Find correct insertion point within existing order.
    BasicBlock* insertion_point = entry->rpo_next();
    BasicBlock* order = insertion_point;
    // Perform an iterative RPO traversal using an explicit stack,
    // recording backedges that form cycles. O(|B|).
    DCHECK_LT(previous_block_count_, schedule_->BasicBlockCount());
    stack_.resize(schedule_->BasicBlockCount() - previous_block_count_);
    previous_block_count_ = schedule_->BasicBlockCount();
    int stack_depth = Push(0, entry, kBlockUnvisited1);
    int num_loops = static_cast<int>(loops_.size());
    while (stack_depth > 0) {
      int current = stack_depth - 1;
      SpecialRPOStackFrame* frame = &stack_[current];
      if (frame->block != end &&
          frame->index < frame->block->SuccessorCount()) {
        // Process the next successor.
        BasicBlock* succ = frame->block->SuccessorAt(frame->index++);
        if (succ->rpo_number() == kBlockVisited1) continue;
        if (succ->rpo_number() == kBlockOnStack) {
          // The successor is on the stack, so this is a backedge (cycle).
          backedges_.push_back(Backedge(frame->block, frame->index - 1));
          if (!HasLoopNumber(succ)) {
            // Assign a new loop number to the header if it doesn't have one.
            SetLoopNumber(succ, num_loops++);
          }
        } else {
          // Push the successor onto the stack.
          DCHECK_EQ(kBlockUnvisited1, succ->rpo_number());
          stack_depth = Push(stack_depth, succ, kBlockUnvisited1);
        }
      } else {
        // Finished with all successors; pop the stack and add the block.
        order = PushFront(order, frame->block);
        frame->block->set_rpo_number(kBlockVisited1);
        stack_depth--;
      }
    }
    // If no loops were encountered, then the order we computed was correct.
    if (num_loops > static_cast<int>(loops_.size())) {
      // Otherwise, compute the loop information from the backedges in order
      // to perform a traversal that groups loop bodies together.
      ComputeLoopInfo(&stack_, num_loops, &backedges_);
      // Initialize the "loop stack". Note the entry could be a loop header.
      LoopInfo* loop =
          HasLoopNumber(entry) ? &loops_[GetLoopNumber(entry)] : nullptr;
      order = insertion_point;
      // Perform an iterative post-order traversal, visiting loop bodies before
      // edges that lead out of loops. Visits each block once, but linking loop
      // sections together is linear in the loop size, so overall is
      // O(|B| + max(loop_depth) * max(|loop|))
      stack_depth = Push(0, entry, kBlockUnvisited2);
      while (stack_depth > 0) {
        SpecialRPOStackFrame* frame = &stack_[stack_depth - 1];
        BasicBlock* block = frame->block;
        BasicBlock* succ = nullptr;
        if (block != end && frame->index < block->SuccessorCount()) {
          // Process the next normal successor.
          succ = block->SuccessorAt(frame->index++);
        } else if (HasLoopNumber(block)) {
          // Process additional outgoing edges from the loop header.
          if (block->rpo_number() == kBlockOnStack) {
            // Finish the loop body the first time the header is left on the
            // stack.
            DCHECK(loop != nullptr && loop->header == block);
            loop->start = PushFront(order, block);
            order = loop->end;
            block->set_rpo_number(kBlockVisited2);
            // Pop the loop stack and continue visiting outgoing edges within
            // the context of the outer loop, if any.
            loop = loop->prev;
            // We leave the loop header on the stack; the rest of this iteration
            // and later iterations will go through its outgoing edges list.
          }
          // Use the next outgoing edge if there are any.
          size_t outgoing_index = frame->index - block->SuccessorCount();
          LoopInfo* info = &loops_[GetLoopNumber(block)];
          DCHECK(loop != info);
          if (block != entry && info->outgoing != nullptr &&
              outgoing_index < info->outgoing->size()) {
            succ = info->outgoing->at(outgoing_index);
            frame->index++;
          }
        }
        if (succ != nullptr) {
          // Process the next successor.
          if (succ->rpo_number() == kBlockOnStack) continue;
          if (succ->rpo_number() == kBlockVisited2) continue;
          DCHECK_EQ(kBlockUnvisited2, succ->rpo_number());
          if (loop != nullptr && !loop->members->Contains(succ->id().ToInt())) {
            // The successor is not in the current loop or any nested loop.
            // Add it to the outgoing edges of this loop and visit it later.
            loop->AddOutgoing(zone_, succ);
          } else {
            // Push the successor onto the stack.
            stack_depth = Push(stack_depth, succ, kBlockUnvisited2);
            if (HasLoopNumber(succ)) {
              // Push the inner loop onto the loop stack.
              DCHECK(GetLoopNumber(succ) < num_loops);
              LoopInfo* next = &loops_[GetLoopNumber(succ)];
              next->end = order;
              next->prev = loop;
              loop = next;
            }
          }
        } else {
          // Finished with all successors of the current block.
          if (HasLoopNumber(block)) {
            // If we are going to pop a loop header, then add its entire body.
            LoopInfo* info = &loops_[GetLoopNumber(block)];
            for (BasicBlock* b = info->start; true; b = b->rpo_next()) {
              if (b->rpo_next() == info->end) {
                b->set_rpo_next(order);
                info->end = order;
                break;
              }
            }
            order = info->start;
          } else {
            // Pop a single node off the stack and add it to the order.
            order = PushFront(order, block);
            block->set_rpo_number(kBlockVisited2);
          }
          stack_depth--;
        }
      }
    }
    // Publish new order the first time.
    if (order_ == nullptr) order_ = order;
    // Compute the correct loop headers and set the correct loop ends.
    LoopInfo* current_loop = nullptr;
    BasicBlock* current_header = entry->loop_header();
    int32_t loop_depth = entry->loop_depth();
    if (entry->IsLoopHeader()) --loop_depth; // Entry might be a loop header.
    for (BasicBlock* b = order; b != insertion_point; b = b->rpo_next()) {
      BasicBlock* current = b;
      // Reset BasicBlock::rpo_number again.
      current->set_rpo_number(kBlockUnvisited1);
      // Finish the previous loop(s) if we just exited them.
      while (current_header != nullptr &&
             current == current_header->loop_end()) {
        DCHECK(current_header->IsLoopHeader());
        DCHECK_NOT_NULL(current_loop);
        current_loop = current_loop->prev;
        current_header =
            current_loop == nullptr ? nullptr : current_loop->header;
        --loop_depth;
      }
      current->set_loop_header(current_header);
      // Push a new loop onto the stack if this loop is a loop header.
      if (HasLoopNumber(current)) {
        ++loop_depth;
        current_loop = &loops_[GetLoopNumber(current)];
        BasicBlock* loop_end = current_loop->end;
        current->set_loop_end(loop_end == nullptr ? BeyondEndSentinel()
                                                  : loop_end);
        current_header = current_loop->header;
        TRACE("id:%d is a loop header, increment loop depth to %d\n",
              current->id().ToInt(), loop_depth);
      }
      current->set_loop_depth(loop_depth);
      if (current->loop_header() == nullptr) {
        TRACE("id:%d is not in a loop (depth == %d)\n", current->id().ToInt(),
              current->loop_depth());
      } else {
        TRACE("id:%d has loop header id:%d, (depth == %d)\n",
              current->id().ToInt(), current->loop_header()->id().ToInt(),
              current->loop_depth());
      }
    }
  }
References v8::internal::compiler::SpecialRPONumberer::LoopInfo::AddOutgoing(), v8::internal::ZoneVector< T >::at(), backedges_, v8::internal::compiler::Schedule::BasicBlockCount(), BeyondEndSentinel(), v8::internal::compiler::SpecialRPONumberer::SpecialRPOStackFrame::block, CHECK_EQ, ComputeLoopInfo(), v8::internal::BitVector::Contains(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::compiler::end(), v8::internal::compiler::SpecialRPONumberer::LoopInfo::end, GetLoopNumber(), HasLoopNumber(), v8::internal::compiler::SpecialRPONumberer::LoopInfo::header, v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::SpecialRPONumberer::SpecialRPOStackFrame::index, v8::internal::compiler::BasicBlock::IsLoopHeader(), kBlockOnStack, kBlockUnvisited1, kBlockUnvisited2, kBlockVisited1, kBlockVisited2, v8::internal::compiler::BasicBlock::loop_depth(), v8::internal::compiler::BasicBlock::loop_end(), v8::internal::compiler::BasicBlock::loop_header(), v8::internal::compiler::BasicBlock::loop_number(), loops_, v8::internal::compiler::SpecialRPONumberer::LoopInfo::members, nullptr, order_, v8::internal::compiler::SpecialRPONumberer::LoopInfo::outgoing, v8::internal::compiler::SpecialRPONumberer::LoopInfo::prev, previous_block_count_, Push(), v8::internal::ZoneVector< T >::push_back(), PushFront(), v8::internal::compiler::BasicBlock::rpo_next(), v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), schedule_, v8::internal::compiler::BasicBlock::set_loop_depth(), v8::internal::compiler::BasicBlock::set_loop_end(), v8::internal::compiler::BasicBlock::set_loop_header(), v8::internal::compiler::BasicBlock::set_rpo_number(), SetLoopNumber(), v8::internal::ZoneVector< T >::size(), stack_, v8::internal::compiler::Schedule::start(), v8::internal::compiler::SpecialRPONumberer::LoopInfo::start, v8::internal::compiler::BasicBlock::SuccessorAt(), v8::internal::compiler::BasicBlock::SuccessorCount(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::TRACE(), and zone_.
Referenced by ComputeSpecialRPO(), and UpdateSpecialRPO().
ComputeLoopInfo()
void v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo (ZoneVector< SpecialRPOStackFrame > * queue, size_t num_loops, ZoneVector< Backedge > * backedges) [inline], [private]
Definition at line 979 of file scheduler.cc.
                                                                          {
    // Extend existing loop membership vectors.
    for (LoopInfo& loop : loops_) {
      loop.members->Resize(static_cast<int>(schedule_->BasicBlockCount()),
                           zone_);
    }
    // Extend loop information vector.
    loops_.resize(num_loops, LoopInfo());
    // Compute loop membership starting from backedges.
    // O(max(loop_depth) * max(|loop|)
    for (size_t i = 0; i < backedges->size(); i++) {
      BasicBlock* member = backedges->at(i).first;
      BasicBlock* header = member->SuccessorAt(backedges->at(i).second);
      size_t loop_num = GetLoopNumber(header);
      if (loops_[loop_num].header == nullptr) {
        loops_[loop_num].header = header;
        loops_[loop_num].members = zone_->New<BitVector>(
            static_cast<int>(schedule_->BasicBlockCount()), zone_);
      }
      int queue_length = 0;
      if (member != header) {
        // As long as the header doesn't have a backedge to itself,
        // Push the member onto the queue and process its predecessors.
        if (!loops_[loop_num].members->Contains(member->id().ToInt())) {
          loops_[loop_num].members->Add(member->id().ToInt());
        }
        (*queue)[queue_length++].block = member;
      }
      // Propagate loop membership backwards. All predecessors of M up to the
      // loop header H are members of the loop too. O(|blocks between M and H|).
      while (queue_length > 0) {
        BasicBlock* block = (*queue)[--queue_length].block;
        for (size_t j = 0; j < block->PredecessorCount(); j++) {
          BasicBlock* pred = block->PredecessorAt(j);
          if (pred != header) {
            if (!loops_[loop_num].members->Contains(pred->id().ToInt())) {
              loops_[loop_num].members->Add(pred->id().ToInt());
              (*queue)[queue_length++].block = pred;
            }
          }
        }
      }
    }
  }
References v8::internal::ZoneVector< T >::at(), v8::internal::compiler::Schedule::BasicBlockCount(), GetLoopNumber(), v8::internal::compiler::BasicBlock::id(), loops_, v8::internal::Zone::New(), v8::internal::compiler::BasicBlock::PredecessorAt(), v8::internal::compiler::BasicBlock::PredecessorCount(), schedule_, v8::internal::ZoneVector< T >::size(), v8::internal::compiler::BasicBlock::SuccessorAt(), v8::internal::compiler::BasicBlock::Id::ToInt(), and zone_.
Referenced by ComputeAndInsertSpecialRPO().
ComputeSpecialRPO()
void v8::internal::compiler::SpecialRPONumberer::ComputeSpecialRPO () [inline]
Definition at line 676 of file scheduler.cc.
                           {
    DCHECK_EQ(0, schedule_->end()->SuccessorCount());
    DCHECK(!order_); // Main order does not exist yet.
    ComputeAndInsertSpecialRPO(schedule_->start(), schedule_->end());
  }
References ComputeAndInsertSpecialRPO(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Schedule::end(), order_, schedule_, v8::internal::compiler::Schedule::start(), and v8::internal::compiler::BasicBlock::SuccessorCount().
Referenced by v8::internal::compiler::Scheduler::ComputeSpecialRPO(), and v8::internal::compiler::Scheduler::ComputeSpecialRPONumbering().
GetLoopNumber()
static int v8::internal::compiler::SpecialRPONumberer::GetLoopNumber (BasicBlock * block) [inline], [static], [private]
Definition at line 765 of file scheduler.cc.
{ return block->loop_number(); }
References v8::internal::compiler::BasicBlock::loop_number().
Referenced by ComputeAndInsertSpecialRPO(), ComputeLoopInfo(), and GetOutgoingBlocks().
GetOutgoingBlocks()
const ZoneVector<BasicBlock*>& v8::internal::compiler::SpecialRPONumberer::GetOutgoingBlocks (BasicBlock * block) [inline]
Definition at line 709 of file scheduler.cc.
                                                                      {
    if (HasLoopNumber(block)) {
      LoopInfo const& loop = loops_[GetLoopNumber(block)];
      if (loop.outgoing) return *loop.outgoing;
    }
    return empty_;
  }
References empty_, GetLoopNumber(), HasLoopNumber(), loops_, and v8::internal::compiler::SpecialRPONumberer::LoopInfo::outgoing.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock().
HasLoopBlocks()
bool v8::internal::compiler::SpecialRPONumberer::HasLoopBlocks () const [inline]
Definition at line 717 of file scheduler.cc.
{ return !loops_.empty(); }
References loops_.
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock(), v8::internal::compiler::Scheduler::ScheduleEarly(), and v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode().
HasLoopNumber()
static bool v8::internal::compiler::SpecialRPONumberer::HasLoopNumber (BasicBlock * block) [inline], [static], [private]
Definition at line 769 of file scheduler.cc.
                                               {
    return block->loop_number() >= 0;
  }
References v8::internal::compiler::BasicBlock::loop_number().
Referenced by ComputeAndInsertSpecialRPO(), and GetOutgoingBlocks().
PrintAndVerifySpecialRPO()
void v8::internal::compiler::SpecialRPONumberer::PrintAndVerifySpecialRPO () [inline]
Definition at line 702 of file scheduler.cc.
                                  {
#if DEBUG
    if (v8_flags.trace_turbo_scheduler) PrintRPO();
    VerifySpecialRPO();
#endif
  }
References v8::internal::v8_flags.
Referenced by v8::internal::compiler::Scheduler::ComputeSpecialRPO(), and v8::internal::compiler::Scheduler::SealFinalSchedule().
Push()
int v8::internal::compiler::SpecialRPONumberer::Push (int depth, BasicBlock * child, int unvisited) [inline], [private]
Definition at line 750 of file scheduler.cc.
                                                        {
    if (child->rpo_number() == unvisited) {
      stack_[depth].block = child;
      stack_[depth].index = 0;
      child->set_rpo_number(kBlockOnStack);
      return depth + 1;
    }
    return depth;
  }
References kBlockOnStack, v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::BasicBlock::set_rpo_number(), and stack_.
Referenced by ComputeAndInsertSpecialRPO().
PushFront()
BasicBlock* v8::internal::compiler::SpecialRPONumberer::PushFront (BasicBlock * head, BasicBlock * block) [inline], [private]
Definition at line 760 of file scheduler.cc.
                                                             {
    block->set_rpo_next(head);
    return block;
  }
References v8::internal::compiler::BasicBlock::set_rpo_next().
Referenced by ComputeAndInsertSpecialRPO().
SerializeRPOIntoSchedule()
void v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule () [inline]
Definition at line 692 of file scheduler.cc.
                                  {
    int32_t number = 0;
    for (BasicBlock* b = order_; b != nullptr; b = b->rpo_next()) {
      b->set_rpo_number(number++);
      schedule_->rpo_order()->push_back(b);
    }
    BeyondEndSentinel()->set_rpo_number(number);
  }
References BeyondEndSentinel(), order_, v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::BasicBlock::rpo_next(), v8::internal::compiler::Schedule::rpo_order(), schedule_, and v8::internal::compiler::BasicBlock::set_rpo_number().
Referenced by v8::internal::compiler::Scheduler::ComputeSpecialRPO(), and v8::internal::compiler::Scheduler::SealFinalSchedule().
SetLoopNumber()
static void v8::internal::compiler::SpecialRPONumberer::SetLoopNumber (BasicBlock * block, int loop_number) [inline], [static], [private]
Definition at line 766 of file scheduler.cc.
                                                                {
    return block->set_loop_number(loop_number);
  }
References v8::internal::compiler::BasicBlock::set_loop_number().
Referenced by ComputeAndInsertSpecialRPO().
UpdateSpecialRPO()
void v8::internal::compiler::SpecialRPONumberer::UpdateSpecialRPO (BasicBlock * entry, BasicBlock * end) [inline]
Definition at line 685 of file scheduler.cc.
                                                            {
    DCHECK(order_); // Main order to be updated is present.
    ComputeAndInsertSpecialRPO(entry, end);
  }
References ComputeAndInsertSpecialRPO(), v8::internal::DCHECK(), v8::internal::compiler::end(), and order_.
Referenced by v8::internal::compiler::Scheduler::FuseFloatingControl().
Member Data Documentation
backedges_
ZoneVector<Backedge> v8::internal::compiler::SpecialRPONumberer::backedges_ [private]
Definition at line 1135 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO().
beyond_end_
BasicBlock* v8::internal::compiler::SpecialRPONumberer::beyond_end_ [private]
Definition at line 1133 of file scheduler.cc.
Referenced by BeyondEndSentinel().
empty_
ZoneVector<BasicBlock*> const v8::internal::compiler::SpecialRPONumberer::empty_ [private]
Definition at line 1138 of file scheduler.cc.
Referenced by GetOutgoingBlocks().
kBlockOnStack
const int v8::internal::compiler::SpecialRPONumberer::kBlockOnStack = -2 [static], [private]
Definition at line 723 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO(), and Push().
kBlockUnvisited1
const int v8::internal::compiler::SpecialRPONumberer::kBlockUnvisited1 = -1 [static], [private]
Definition at line 726 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO().
kBlockUnvisited2
const int v8::internal::compiler::SpecialRPONumberer::kBlockUnvisited2 = kBlockVisited1 [static], [private]
Definition at line 727 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO().
kBlockVisited1
const int v8::internal::compiler::SpecialRPONumberer::kBlockVisited1 = -3 [static], [private]
Definition at line 724 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO().
kBlockVisited2
const int v8::internal::compiler::SpecialRPONumberer::kBlockVisited2 = -4 [static], [private]
Definition at line 725 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO().
loops_
ZoneVector<LoopInfo> v8::internal::compiler::SpecialRPONumberer::loops_ [private]
Definition at line 1134 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO(), ComputeLoopInfo(), GetOutgoingBlocks(), and HasLoopBlocks().
order_
BasicBlock* v8::internal::compiler::SpecialRPONumberer::order_ [private]
Definition at line 1132 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO(), ComputeSpecialRPO(), SerializeRPOIntoSchedule(), and UpdateSpecialRPO().
previous_block_count_
size_t v8::internal::compiler::SpecialRPONumberer::previous_block_count_ [private]
Definition at line 1137 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO().
schedule_
Schedule* v8::internal::compiler::SpecialRPONumberer::schedule_ [private]
Definition at line 1131 of file scheduler.cc.
Referenced by BeyondEndSentinel(), ComputeAndInsertSpecialRPO(), ComputeLoopInfo(), ComputeSpecialRPO(), and SerializeRPOIntoSchedule().
stack_
ZoneVector<SpecialRPOStackFrame> v8::internal::compiler::SpecialRPONumberer::stack_ [private]
Definition at line 1136 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO(), and Push().
zone_
Zone* v8::internal::compiler::SpecialRPONumberer::zone_ [private]
Definition at line 1130 of file scheduler.cc.
Referenced by ComputeAndInsertSpecialRPO(), and ComputeLoopInfo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/scheduler.cc