v8::internal::interpreter::BytecodeGenerator::IteratorRecord Class Reference
Public Member Functions
IteratorRecord (Register object_register, Register next_register, IteratorType type=IteratorType::kNormal)
IteratorType type () const
Register object () const
Register next () const
Private Attributes
IteratorType type_
Register object_
Register next_
Detailed Description
Definition at line 1202 of file bytecode-generator.cc.
Constructor & Destructor Documentation
IteratorRecord()
v8::internal::interpreter::BytecodeGenerator::IteratorRecord::IteratorRecord (Register object_register, Register next_register, IteratorType type = IteratorType::kNormal) [inline]
Definition at line 1204 of file bytecode-generator.cc.
      : type_(type), object_(object_register), next_(next_register) {
    DCHECK(object_.is_valid() && next_.is_valid());
  }
References v8::internal::DCHECK().
Member Function Documentation
next()
Register v8::internal::interpreter::BytecodeGenerator::IteratorRecord::next () const [inline]
Definition at line 1212 of file bytecode-generator.cc.
{ return next_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext().
object()
Register v8::internal::interpreter::BytecodeGenerator::IteratorRecord::object () const [inline]
Definition at line 1211 of file bytecode-generator.cc.
{ return object_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), and v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext().
type()
IteratorType v8::internal::interpreter::BytecodeGenerator::IteratorRecord::type () const [inline]
Definition at line 1210 of file bytecode-generator.cc.
{ return type_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), and v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext().
Member Data Documentation
next_
Register v8::internal::interpreter::BytecodeGenerator::IteratorRecord::next_ [private]
Definition at line 1217 of file bytecode-generator.cc.
object_
Register v8::internal::interpreter::BytecodeGenerator::IteratorRecord::object_ [private]
Definition at line 1216 of file bytecode-generator.cc.
type_
IteratorType v8::internal::interpreter::BytecodeGenerator::IteratorRecord::type_ [private]
Definition at line 1215 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc