v8::internal::SemiSpace Class Reference
#include <new-spaces.h>
Public Types
using iterator = PageIterator
using const_iterator = ConstPageIterator
Public Member Functions
SemiSpace (Heap *heap, SemiSpaceId semispace)
V8_EXPORT_PRIVATE ~SemiSpace ()
bool Contains (Tagged< HeapObject > o) const
bool Contains (Tagged< Object > o) const
template<typename T >
bool Contains (Tagged< T > o) const
bool ContainsSlow (Address a) const
void Uncommit ()
bool IsCommitted () const
Address space_start () const
PageMetadata * current_page () const
Address page_low () const
Address page_high () const
bool AdvancePage (size_t target_capacity)
void RemovePage (PageMetadata *page)
void MovePageToTheEnd (PageMetadata *page)
PageMetadata * InitializePage (MutablePageMetadata *chunk) final
size_t current_capacity () const
size_t current_capacity_safe () const
SemiSpaceId id () const
size_t CommittedPhysicalMemory () const final
size_t Size () const final
size_t SizeOfObjects () const final
size_t Available () const final
PageMetadata * first_page () final
PageMetadata * last_page () final
const PageMetadata * first_page () const final
const PageMetadata * last_page () const final
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::unique_ptr< ObjectIterator > GetObjectIterator (Heap *heap) final
void AddRangeToActiveSystemPages (Address start, Address end)
void MoveQuarantinedPage (MemoryChunk *chunk)
Static Public Member Functions
static void Swap (SemiSpace *from, SemiSpace *to)
static void AssertValidRange (Address from, Address to)
Private Member Functions
bool AllocateFreshPage ()
void RewindPages (int num_pages)
void FixPagesFlags ()
void IncrementCommittedPhysicalMemory (size_t increment_value)
void DecrementCommittedPhysicalMemory (size_t decrement_value)
void ShrinkCapacityTo (size_t capacity)
void Reset ()
Private Attributes
size_t current_capacity_ = 0
size_t committed_physical_memory_ = 0
SemiSpaceId id_
PageMetadata * current_page_ = nullptr
size_t quarantined_pages_count_ = 0
Friends
class SemiSpaceNewSpace
class SemiSpaceObjectIterator
Additional Inherited Members
Detailed Description
Definition at line 43 of file new-spaces.h.
Member Typedef Documentation
const_iterator
using v8::internal::SemiSpace::const_iterator = ConstPageIterator
Definition at line 46 of file new-spaces.h.
iterator
using v8::internal::SemiSpace::iterator = PageIterator
Definition at line 45 of file new-spaces.h.
Constructor & Destructor Documentation
SemiSpace()
v8::internal::SemiSpace::SemiSpace (Heap * heap, SemiSpaceId semispace)
Definition at line 54 of file new-spaces.cc.
    : Space(heap, NEW_SPACE, nullptr), id_(semispace) {}
 SemiSpace()
v8::internal::SemiSpace::~SemiSpace ()
Definition at line 57 of file new-spaces.cc.
                      {
  const bool is_marking = heap_->isolate()->isolate_data()->is_marking();
  while (!memory_chunk_list_.Empty()) {
    MutablePageMetadata* page = memory_chunk_list_.front();
    memory_chunk_list_.Remove(page);
    if (is_marking) {
      page->ClearLiveness();
    }
    heap_->memory_allocator()->Free(MemoryAllocator::FreeMode::kPool, page);
  }
}
References v8::internal::MutablePageMetadata::ClearLiveness(), v8::internal::MemoryAllocator::Free(), v8::internal::BaseSpace::heap_, v8::internal::IsolateData::is_marking(), v8::internal::Heap::isolate(), v8::internal::Isolate::isolate_data(), v8::internal::MemoryAllocator::kPool, v8::internal::Heap::memory_allocator(), and v8::internal::Space::memory_chunk_list_.
Member Function Documentation
AddRangeToActiveSystemPages()
void v8::internal::SemiSpace::AddRangeToActiveSystemPages (Address start, Address end)
Definition at line 267 of file new-spaces.cc.
                                                                      {
  PageMetadata* page = current_page();
  MemoryChunk* chunk = page->Chunk();
  DCHECK_LE(chunk->address(), start);
  DCHECK_LT(start, end);
  DCHECK_LE(end, chunk->address() + PageMetadata::kPageSize);
  const size_t added_pages = page->active_system_pages()->Add(
      chunk->Offset(start), chunk->Offset(end),
      MemoryAllocator::GetCommitPageSizeBits());
  IncrementCommittedPhysicalMemory(added_pages *
                                   MemoryAllocator::GetCommitPageSize());
}
References v8::internal::PageMetadata::active_system_pages(), heap::base::ActiveSystemPages::Add(), v8::internal::MemoryChunk::address(), v8::internal::MemoryChunkMetadata::Chunk(), current_page(), DCHECK_LE, DCHECK_LT, end(), v8::internal::MemoryAllocator::GetCommitPageSize(), v8::internal::MemoryAllocator::GetCommitPageSizeBits(), IncrementCommittedPhysicalMemory(), v8::internal::MutablePageMetadata::kPageSize, and v8::internal::MemoryChunk::Offset().
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation().
AdvancePage()
bool v8::internal::SemiSpace::AdvancePage (size_t target_capacity)
Definition at line 220 of file new-spaces.cc.
                                                  {
  PageMetadata* next_page;
  if (current_page_) {
    next_page = current_page_->next_page();
  } else {
    // Start allocating on the first page but skip the quarantined pages.
    DCHECK_GE(memory_chunk_list_.size(), quarantined_pages_count_);
    next_page = first_page();
    for (size_t i = 0; i < quarantined_pages_count_; i++) {
      DCHECK_NOT_NULL(next_page);
      next_page = next_page->next_page();
    }
  }
  if (!next_page && current_capacity_ < target_capacity) {
    DCHECK_IMPLIES(current_page_, current_page_ == last_page());
    if (!AllocateFreshPage()) return false;
    next_page = last_page();
    DCHECK_NOT_NULL(next_page);
  }
  if (!next_page) {
    return false;
  }
  current_page_ = next_page;
  base::AsAtomicWord::Relaxed_Store(
      &current_capacity_, current_capacity_ + PageMetadata::kPageSize);
  DCHECK_IMPLIES(current_capacity_ > target_capacity,
                 heap()->IsNewSpaceAllowedToGrowAboveTargetCapacity());
  return true;
}
References AllocateFreshPage(), current_capacity_, current_page_, DCHECK_GE, DCHECK_IMPLIES, DCHECK_NOT_NULL, first_page(), v8::internal::BaseSpace::heap(), v8::internal::MutablePageMetadata::kPageSize, last_page(), v8::internal::Space::memory_chunk_list_, v8::internal::PageMetadata::next_page(), quarantined_pages_count_, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store().
Referenced by v8::internal::SemiSpaceNewSpace::AddFreshPage().
AllocateFreshPage()
bool v8::internal::SemiSpace::AllocateFreshPage () [private]
Definition at line 116 of file new-spaces.cc.
                                  {
  PageMetadata* new_page = heap()->memory_allocator()->AllocatePage(
      MemoryAllocator::AllocationMode::kUsePool, this, NOT_EXECUTABLE);
  if (new_page == nullptr) {
    return false;
  }
  memory_chunk_list_.PushBack(new_page);
  IncrementCommittedPhysicalMemory(new_page->CommittedPhysicalMemory());
  AccountCommitted(PageMetadata::kPageSize);
  heap()->CreateFillerObjectAt(new_page->area_start(),
                               static_cast<int>(new_page->area_size()));
  return true;
}
References v8::internal::BaseSpace::AccountCommitted(), v8::internal::MemoryAllocator::AllocatePage(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::BaseSpace::heap(), IncrementCommittedPhysicalMemory(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::MemoryAllocator::kUsePool, v8::internal::Heap::memory_allocator(), v8::internal::Space::memory_chunk_list_, and v8::internal::NOT_EXECUTABLE.
Referenced by AdvancePage(), and v8::internal::SemiSpaceNewSpace::AllocateOnNewPageBeyondCapacity().
AssertValidRange()
static void v8::internal::SemiSpace::AssertValidRange (Address from, Address to) [inline], [static]
Definition at line 134 of file new-spaces.h.
{}
Available()
size_t v8::internal::SemiSpace::Available () const [inline], [final], [virtual]
Implements v8::internal::Space.
Definition at line 102 of file new-spaces.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
begin() [1/2]
iterator v8::internal::SemiSpace::begin () [inline]
Definition at line 118 of file new-spaces.h.
{ return iterator(first_page()); }
References first_page().
begin() [2/2]
const_iterator v8::internal::SemiSpace::begin () const [inline]
Definition at line 121 of file new-spaces.h.
{ return const_iterator(first_page()); }
References first_page().
CommittedPhysicalMemory()
size_t v8::internal::SemiSpace::CommittedPhysicalMemory () const [final], [virtual]
Implements v8::internal::BaseSpace.
Definition at line 110 of file new-spaces.cc.
                                                {
  if (!IsCommitted()) return 0;
  if (!base::OS::HasLazyCommits()) return CommittedMemory();
  return committed_physical_memory_;
}
References committed_physical_memory_, v8::internal::BaseSpace::CommittedMemory(), v8::base::OS::HasLazyCommits(), and IsCommitted().
Referenced by v8::internal::SemiSpaceNewSpace::CommittedPhysicalMemory(), and Uncommit().
Contains() [1/3]
bool v8::internal::SemiSpace::Contains (Tagged< HeapObject > o) const [inline]
Definition at line 26 of file new-spaces-inl.h.
                                                   {
  MemoryChunk* memory_chunk = MemoryChunk::FromHeapObject(o);
  if (memory_chunk->IsLargePage()) return false;
  return id_ == kToSpace ? memory_chunk->IsToPage()
                         : memory_chunk->IsFromPage();
}
References v8::internal::MemoryChunk::FromHeapObject(), id_, v8::internal::MemoryChunk::IsFromPage(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MemoryChunk::IsToPage(), and v8::internal::kToSpace.
Referenced by Contains().
Contains() [2/3]
bool v8::internal::SemiSpace::Contains (Tagged< Object > o) const [inline]
Definition at line 33 of file new-spaces-inl.h.
                                               {
  return IsHeapObject(o) && Contains(Cast<HeapObject>(o));
}
References Contains(), and v8::internal::IsHeapObject().
Contains() [3/3]
template<typename T >
bool v8::internal::SemiSpace::Contains (Tagged< T > o) const [inline]
Definition at line 38 of file new-spaces-inl.h.
                                                 {
  static_assert(kTaggedCanConvertToRawObjects);
  return Contains(*o);
}
References Contains(), and v8::internal::kTaggedCanConvertToRawObjects.
ContainsSlow()
bool v8::internal::SemiSpace::ContainsSlow (Address a) const [inline]
Definition at line 43 of file new-spaces-inl.h.
                                            {
  for (const PageMetadata* p : *this) {
    if (p == MemoryChunkMetadata::FromAddress(a)) return true;
  }
  return false;
}
References v8::internal::MemoryChunkMetadata::FromAddress().
Referenced by v8::internal::SemiSpaceNewSpace::ContainsSlow().
current_capacity()
size_t v8::internal::SemiSpace::current_capacity () const [inline]
Definition at line 84 of file new-spaces.h.
{ return current_capacity_; }
References current_capacity_.
Referenced by v8::internal::SemiSpaceNewSpace::GarbageCollectionEpilogue(), and v8::internal::SemiSpaceNewSpace::Size().
current_capacity_safe()
size_t v8::internal::SemiSpace::current_capacity_safe () const [inline]
Definition at line 86 of file new-spaces.h.
                                       {
    return base::AsAtomicWord::Relaxed_Load(&current_capacity_);
  }
References current_capacity_, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
current_page()
PageMetadata* v8::internal::SemiSpace::current_page () const [inline]
Definition at line 68 of file new-spaces.h.
{ return current_page_; }
References current_page_.
Referenced by AddRangeToActiveSystemPages().
DecrementCommittedPhysicalMemory()
void v8::internal::SemiSpace::DecrementCommittedPhysicalMemory (size_t decrement_value) [private]
Definition at line 261 of file new-spaces.cc.
                                                                       {
  if (!base::OS::HasLazyCommits()) return;
  DCHECK_LE(decrement_value, committed_physical_memory_);
  committed_physical_memory_ -= decrement_value;
}
References committed_physical_memory_, DCHECK_LE, and v8::base::OS::HasLazyCommits().
Referenced by RemovePage(), and RewindPages().
end() [1/2]
iterator v8::internal::SemiSpace::end () [inline]
Definition at line 119 of file new-spaces.h.
{ return iterator(nullptr); }
Referenced by AddRangeToActiveSystemPages().
end() [2/2]
const_iterator v8::internal::SemiSpace::end () const [inline]
Definition at line 122 of file new-spaces.h.
{ return const_iterator(nullptr); }
first_page() [1/2]
const PageMetadata* v8::internal::SemiSpace::first_page () const [inline], [final], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 111 of file new-spaces.h.
                                               {
    return reinterpret_cast<const PageMetadata*>(memory_chunk_list_.front());
  }
References v8::internal::Space::memory_chunk_list_.
first_page() [2/2]
PageMetadata* v8::internal::SemiSpace::first_page () [inline], [final], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 104 of file new-spaces.h.
                                   {
    return PageMetadata::cast(memory_chunk_list_.front());
  }
References v8::internal::PageMetadata::cast(), and v8::internal::Space::memory_chunk_list_.
Referenced by AdvancePage(), begin(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags(), and space_start().
FixPagesFlags()
void v8::internal::SemiSpace::FixPagesFlags () [private]
Definition at line 146 of file new-spaces.cc.
                              {
  const auto to_space_flags =
      MemoryChunk::YoungGenerationPageFlags(
          heap()->incremental_marking()->marking_mode()) |
      MemoryChunk::TO_PAGE;
  for (PageMetadata* page : *this) {
    MemoryChunk* chunk = page->Chunk();
    page->set_owner(this);
    if (id_ == kToSpace) {
      chunk->SetFlagsNonExecutable(to_space_flags);
    } else {
      DCHECK_EQ(id_, kFromSpace);
      // From space must preserve `NEW_SPACE_BELOW_AGE_MARK` which is used for
      // deciding on whether to copy or promote an object.
      chunk->SetFlagNonExecutable(MemoryChunk::FROM_PAGE);
      chunk->ClearFlagNonExecutable(MemoryChunk::TO_PAGE);
    }
    DCHECK(chunk->InYoungGeneration());
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagNonExecutable(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::FROM_PAGE, v8::internal::BaseSpace::heap(), id_, v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::kFromSpace, v8::internal::kToSpace, v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::MemoryChunk::SetFlagNonExecutable(), v8::internal::MemoryChunk::SetFlagsNonExecutable(), v8::internal::MemoryChunk::TO_PAGE, and v8::internal::MemoryChunk::YoungGenerationPageFlags().
Referenced by Swap().
GetObjectIterator()
std::unique_ptr< ObjectIterator > v8::internal::SemiSpace::GetObjectIterator (Heap * heap) [final], [virtual]
Implements v8::internal::Space.
Definition at line 282 of file new-spaces.cc.
                                                                     {
  // Use the SemiSpaceNewSpace::NewObjectIterator to iterate the ToSpace.
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
id()
SemiSpaceId v8::internal::SemiSpace::id () const [inline]
Definition at line 90 of file new-spaces.h.
{ return id_; }
References id_.
Referenced by InitializePage().
IncrementCommittedPhysicalMemory()
void v8::internal::SemiSpace::IncrementCommittedPhysicalMemory (size_t increment_value) [private]
Definition at line 254 of file new-spaces.cc.
                                                                       {
  if (!base::OS::HasLazyCommits()) return;
  DCHECK_LE(committed_physical_memory_,
            committed_physical_memory_ + increment_value);
  committed_physical_memory_ += increment_value;
}
References committed_physical_memory_, DCHECK_LE, and v8::base::OS::HasLazyCommits().
Referenced by AddRangeToActiveSystemPages(), AllocateFreshPage(), and MoveQuarantinedPage().
InitializePage()
PageMetadata * v8::internal::SemiSpace::InitializePage (MutablePageMetadata * chunk) [final], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 42 of file new-spaces.cc.
                                                                         {
  bool in_to_space = (id() != kFromSpace);
  MemoryChunk* chunk = mutable_page->Chunk();
  chunk->SetFlagNonExecutable(in_to_space ? MemoryChunk::TO_PAGE
                                          : MemoryChunk::FROM_PAGE);
  PageMetadata* page = PageMetadata::cast(mutable_page);
  page->list_node().Initialize();
  CHECK(page->IsLivenessClear());
  chunk->InitializationMemoryFence();
  return page;
}
References v8::internal::PageMetadata::cast(), CHECK, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::FROM_PAGE, id(), v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::MutablePageMetadata::IsLivenessClear(), v8::internal::kFromSpace, v8::internal::MutablePageMetadata::list_node(), v8::internal::MemoryChunk::SetFlagNonExecutable(), and v8::internal::MemoryChunk::TO_PAGE.
IsCommitted()
bool v8::internal::SemiSpace::IsCommitted () const [inline]
Definition at line 60 of file new-spaces.h.
{ return !memory_chunk_list_.Empty(); }
References v8::internal::Space::memory_chunk_list_.
Referenced by CommittedPhysicalMemory(), v8::internal::SemiSpaceNewSpace::CommittedPhysicalMemory(), ShrinkCapacityTo(), and Uncommit().
last_page() [1/2]
const PageMetadata* v8::internal::SemiSpace::last_page () const [inline], [final], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 114 of file new-spaces.h.
                                              {
    return reinterpret_cast<const PageMetadata*>(memory_chunk_list_.back());
  }
References v8::internal::Space::memory_chunk_list_.
last_page() [2/2]
PageMetadata* v8::internal::SemiSpace::last_page () [inline], [final], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 107 of file new-spaces.h.
                                  {
    return PageMetadata::cast(memory_chunk_list_.back());
  }
References v8::internal::PageMetadata::cast(), and v8::internal::Space::memory_chunk_list_.
Referenced by AdvancePage(), and RewindPages().
MovePageToTheEnd()
void v8::internal::SemiSpace::MovePageToTheEnd (PageMetadata * page)
Definition at line 183 of file new-spaces.cc.
                                                   {
  DCHECK_EQ(page->owner(), this);
  memory_chunk_list_.Remove(page);
  memory_chunk_list_.PushBack(page);
  current_page_ = page;
}
References current_page_, DCHECK_EQ, v8::internal::Space::memory_chunk_list_, and v8::internal::MutablePageMetadata::owner().
Referenced by v8::internal::SemiSpaceNewSpace::AddParkedAllocationBuffer().
MoveQuarantinedPage()
void v8::internal::SemiSpace::MoveQuarantinedPage (MemoryChunk * chunk)
Definition at line 375 of file new-spaces.cc.
                                                      {
  // Quarantining pages happens at the end of scavenge, after the semi spaces
  // have been swapped. Thus, the quarantined page originates from "from space"
  // to is moved to "to space" to keep pinned objects as live.
  DCHECK_EQ(kToSpace, id_);
  DCHECK(chunk->IsQuarantined());
  DCHECK(!chunk->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED));
  DCHECK(chunk->IsFromPage());
  PageMetadata* page = PageMetadata::cast(chunk->Metadata());
  SemiSpace& from_space = heap_->semi_space_new_space()->from_space();
  DCHECK_EQ(&from_space, page->owner());
  DCHECK_NE(&from_space, this);
  from_space.RemovePage(page);
  chunk->ClearFlagNonExecutable(MemoryChunk::IS_QUARANTINED);
  chunk->ClearFlagNonExecutable(MemoryChunk::FROM_PAGE);
  chunk->SetFlagNonExecutable(MemoryChunk::TO_PAGE);
  page->set_owner(this);
  AccountCommitted(PageMetadata::kPageSize);
  IncrementCommittedPhysicalMemory(page->CommittedPhysicalMemory());
  memory_chunk_list_.PushFront(page);
  quarantined_pages_count_++;
}
References v8::internal::BaseSpace::AccountCommitted(), v8::internal::PageMetadata::cast(), v8::internal::MemoryChunk::ClearFlagNonExecutable(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::MemoryChunk::FROM_PAGE, v8::internal::SemiSpaceNewSpace::from_space(), v8::internal::BaseSpace::heap_, id_, IncrementCommittedPhysicalMemory(), v8::internal::MemoryChunk::IS_QUARANTINED, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsFromPage(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::kToSpace, v8::internal::Space::memory_chunk_list_, v8::internal::MemoryChunk::Metadata(), v8::internal::MutablePageMetadata::owner(), quarantined_pages_count_, RemovePage(), v8::internal::Heap::semi_space_new_space(), v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::MemoryChunk::SetFlagNonExecutable(), v8::internal::MemoryChunk::TO_PAGE, and v8::internal::MemoryChunk::WILL_BE_PROMOTED.
Referenced by v8::internal::SemiSpaceNewSpace::MoveQuarantinedPage().
page_high()
Address v8::internal::SemiSpace::page_high () const [inline]
Definition at line 74 of file new-spaces.h.
{ return current_page_->area_end(); }
References v8::internal::MemoryChunkMetadata::area_end(), and current_page_.
Referenced by v8::internal::SemiSpaceNewSpace::AddFreshPage(), v8::internal::SemiSpaceNewSpace::Allocate(), v8::internal::SemiSpaceNewSpace::FillCurrentPageForTesting(), and v8::internal::SemiSpaceNewSpace::GetSpaceRemainingOnCurrentPageForTesting().
page_low()
Address v8::internal::SemiSpace::page_low () const [inline]
Definition at line 71 of file new-spaces.h.
{ return current_page_->area_start(); }
References v8::internal::MemoryChunkMetadata::area_start(), and current_page_.
Referenced by v8::internal::SemiSpaceNewSpace::Size().
RemovePage()
void v8::internal::SemiSpace::RemovePage (PageMetadata * page)
Definition at line 167 of file new-spaces.cc.
                                             {
  if (current_page_ == page) {
    if (page->prev_page()) {
      current_page_ = page->prev_page();
    }
  }
  memory_chunk_list_.Remove(page);
  AccountUncommitted(PageMetadata::kPageSize);
  DecrementCommittedPhysicalMemory(page->CommittedPhysicalMemory());
  ForAll<ExternalBackingStoreType>(
      [this, page](ExternalBackingStoreType type, int index) {
        DecrementExternalBackingStoreBytes(
            type, page->ExternalBackingStoreBytes(type));
      });
}
References v8::internal::BaseSpace::AccountUncommitted(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), current_page_, DecrementCommittedPhysicalMemory(), v8::internal::Space::DecrementExternalBackingStoreBytes(), v8::internal::MutablePageMetadata::ExternalBackingStoreBytes(), v8::internal::index, v8::internal::MutablePageMetadata::kPageSize, v8::internal::Space::memory_chunk_list_, v8::internal::PageMetadata::prev_page(), and v8::internal::tracing::type.
Referenced by MoveQuarantinedPage(), and v8::internal::SemiSpaceNewSpace::RemovePage().
Reset()
void v8::internal::SemiSpace::Reset () [private]
Definition at line 287 of file new-spaces.cc.
                      {
  current_page_ = nullptr;
  current_capacity_ = 0;
  quarantined_pages_count_ = 0;
}
References current_capacity_, current_page_, and quarantined_pages_count_.
Referenced by v8::internal::SemiSpaceNewSpace::SwapSemiSpaces().
RewindPages()
void v8::internal::SemiSpace::RewindPages (int num_pages) [private]
Definition at line 130 of file new-spaces.cc.
                                         {
  DCHECK_GT(num_pages, 0);
  DCHECK(last_page());
  AccountUncommitted(num_pages * PageMetadata::kPageSize);
  size_t uncommitted_physical_memory = 0;
  while (num_pages > 0) {
    MutablePageMetadata* last = last_page();
    CHECK_NOT_NULL(last);
    uncommitted_physical_memory += last->CommittedPhysicalMemory();
    memory_chunk_list_.Remove(last);
    heap()->memory_allocator()->Free(MemoryAllocator::FreeMode::kPool, last);
    num_pages--;
  }
  DecrementCommittedPhysicalMemory(uncommitted_physical_memory);
}
References v8::internal::BaseSpace::AccountUncommitted(), CHECK_NOT_NULL, v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::DCHECK(), DCHECK_GT, DecrementCommittedPhysicalMemory(), v8::internal::MemoryAllocator::Free(), v8::internal::BaseSpace::heap(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::MemoryAllocator::kPool, last_page(), v8::internal::Heap::memory_allocator(), and v8::internal::Space::memory_chunk_list_.
Referenced by ShrinkCapacityTo(), and Uncommit().
ShrinkCapacityTo()
void v8::internal::SemiSpace::ShrinkCapacityTo (size_t capacity) [private]
Definition at line 69 of file new-spaces.cc.
                                                {
  DCHECK_IMPLIES(!IsCommitted(), CommittedMemory() == 0);
  // Only the to-space is allowed to have quarantined pages.
  DCHECK_IMPLIES(id_ != kToSpace, quarantined_pages_count_ == 0);
  DCHECK_GE(memory_chunk_list_.size(), quarantined_pages_count_);
  const size_t quarantined_pages =
      id_ == kToSpace ? quarantined_pages_count_ : 0;
  // Quarantined pages are not accounted against the capacity of the space.
  const int pages_available_for_allocation =
      static_cast<int>(memory_chunk_list_.size() - quarantined_pages);
  const int num_pages = static_cast<int>((capacity / PageMetadata::kPageSize)) -
                        pages_available_for_allocation;
  if (num_pages >= 0) {
    // The space is already smaller than it needs to be.
    return;
  }
  RewindPages(-num_pages);
  DCHECK_EQ(capacity + quarantined_pages * PageMetadata::kPageSize,
            CommittedMemory());
  DCHECK_EQ(
      static_cast<int>(capacity / PageMetadata::kPageSize) + quarantined_pages,
      memory_chunk_list_.size());
}
References v8::internal::BaseSpace::CommittedMemory(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, id_, IsCommitted(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::kToSpace, v8::internal::Space::memory_chunk_list_, quarantined_pages_count_, and RewindPages().
Referenced by v8::internal::SemiSpaceNewSpace::GarbageCollectionEpilogue(), and v8::internal::SemiSpaceNewSpace::Shrink().
Size()
size_t v8::internal::SemiSpace::Size () const [inline], [final], [virtual]
Implements v8::internal::BaseSpace.
Definition at line 98 of file new-spaces.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Referenced by SizeOfObjects().
SizeOfObjects()
size_t v8::internal::SemiSpace::SizeOfObjects () const [inline], [final], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 100 of file new-spaces.h.
{ return Size(); }
References Size().
space_start()
Address v8::internal::SemiSpace::space_start () const [inline]
Definition at line 63 of file new-spaces.h.
                              {
    const PageMetadata* page = first_page();
    return page ? page->area_start() : kNullAddress;
  }
References v8::internal::MemoryChunkMetadata::area_start(), first_page(), and v8::internal::kNullAddress.
Swap()
void v8::internal::SemiSpace::Swap (SemiSpace * from, SemiSpace * to) [static]
Definition at line 190 of file new-spaces.cc.
                                                   {
  // We swap all properties but id_.
  std::swap(from->memory_chunk_list_, to->memory_chunk_list_);
  std::swap(from->current_page_, to->current_page_);
  ForAll<ExternalBackingStoreType>(
      [from, to](ExternalBackingStoreType type, int index) {
        const size_t tmp = from->external_backing_store_bytes_[index].load(
            std::memory_order_relaxed);
        from->external_backing_store_bytes_[index].store(
            to->external_backing_store_bytes_[index].load(
                std::memory_order_relaxed),
            std::memory_order_relaxed);
        to->external_backing_store_bytes_[index].store(
            tmp, std::memory_order_relaxed);
      });
  std::swap(from->committed_physical_memory_, to->committed_physical_memory_);
  {
    // Swap committed atomic counters.
    size_t to_commited = to->committed_.load();
    to->committed_.store(from->committed_.load());
    from->committed_.store(to_commited);
  }
  std::swap(from->quarantined_pages_count_, to->quarantined_pages_count_);
  // Swapping the `memory_cunk_list_` essentially swaps out the pages (actual
  // payload) from to and from space.
  to->FixPagesFlags();
  from->FixPagesFlags();
}
References v8::internal::BaseSpace::committed_, committed_physical_memory_, current_page_, v8::internal::Space::external_backing_store_bytes_, FixPagesFlags(), v8::internal::index, v8::internal::Space::memory_chunk_list_, quarantined_pages_count_, and v8::internal::tracing::type.
Referenced by v8::internal::SemiSpaceNewSpace::SwapSemiSpaces().
Uncommit()
void v8::internal::SemiSpace::Uncommit ()
Definition at line 96 of file new-spaces.cc.
                         {
  DCHECK_EQ(CommittedMemory(),
            memory_chunk_list_.size() * PageMetadata::kPageSize);
  if (!memory_chunk_list_.Empty()) {
    RewindPages(static_cast<int>(memory_chunk_list_.size()));
  }
  current_page_ = nullptr;
  current_capacity_ = 0;
  quarantined_pages_count_ = 0;
  DCHECK_EQ(CommittedPhysicalMemory(), 0);
  DCHECK_EQ(CommittedMemory(), 0);
  DCHECK(!IsCommitted());
}
References v8::internal::BaseSpace::CommittedMemory(), CommittedPhysicalMemory(), current_capacity_, current_page_, v8::internal::DCHECK(), DCHECK_EQ, IsCommitted(), v8::internal::MutablePageMetadata::kPageSize, v8::internal::Space::memory_chunk_list_, quarantined_pages_count_, and RewindPages().
Referenced by v8::internal::SemiSpaceNewSpace::Shrink().
Friends And Related Function Documentation
SemiSpaceNewSpace
friend class SemiSpaceNewSpace [friend]
Definition at line 172 of file new-spaces.h.
SemiSpaceObjectIterator
friend class SemiSpaceObjectIterator [friend]
Definition at line 173 of file new-spaces.h.
Member Data Documentation
committed_physical_memory_
size_t v8::internal::SemiSpace::committed_physical_memory_ = 0 [private]
Definition at line 164 of file new-spaces.h.
Referenced by CommittedPhysicalMemory(), DecrementCommittedPhysicalMemory(), IncrementCommittedPhysicalMemory(), and Swap().
current_capacity_
size_t v8::internal::SemiSpace::current_capacity_ = 0 [private]
Definition at line 163 of file new-spaces.h.
Referenced by AdvancePage(), current_capacity(), current_capacity_safe(), Reset(), and Uncommit().
current_page_
PageMetadata* v8::internal::SemiSpace::current_page_ = nullptr [private]
Definition at line 166 of file new-spaces.h.
Referenced by AdvancePage(), current_page(), MovePageToTheEnd(), page_high(), page_low(), RemovePage(), Reset(), Swap(), and Uncommit().
id_
SemiSpaceId v8::internal::SemiSpace::id_ [private]
Definition at line 165 of file new-spaces.h.
Referenced by Contains(), FixPagesFlags(), id(), MoveQuarantinedPage(), and ShrinkCapacityTo().
quarantined_pages_count_
size_t v8::internal::SemiSpace::quarantined_pages_count_ = 0 [private]
Definition at line 170 of file new-spaces.h.
Referenced by AdvancePage(), MoveQuarantinedPage(), Reset(), v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags(), ShrinkCapacityTo(), Swap(), and Uncommit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/new-spaces.h
/mnt/V8SourceCode/src/heap/new-spaces-inl.h
/mnt/V8SourceCode/src/heap/new-spaces.cc