v8::internal::GeneratedCode< Return, Args > Class Template Reference
#include <simulator.h>
Public Types
using Signature = Return(Args...)
Public Member Functions
DISABLE_CFI_ICALL Return Call (Args... args)
DISABLE_CFI_ICALL Return CallSandboxed (Args... args)
Static Public Member Functions
static GeneratedCode FromAddress (Isolate *isolate, Address addr)
static GeneratedCode FromBuffer (Isolate *isolate, uint8_t *buffer)
static GeneratedCode FromCode (Isolate *isolate, Tagged< Code > code)
Private Member Functions
GeneratedCode (Isolate *isolate, Signature *fn_ptr)
Private Attributes
Isolate * isolate_
Signature * fn_ptr_
Friends
class GeneratedCode< Return(Args...)>
Detailed Description
template<typename Return, typename... Args>
class v8::internal::GeneratedCode< Return, Args >
Definition at line 150 of file simulator.h.
Member Typedef Documentation
Signature
template<typename Return , typename... Args>
using v8::internal::GeneratedCode< Return, Args >::Signature = Return(Args...)
Definition at line 152 of file simulator.h.
Constructor & Destructor Documentation
GeneratedCode()
template<typename Return , typename... Args>
v8::internal::GeneratedCode< Return, Args >::GeneratedCode (Isolate * isolate, Signature * fn_ptr) [inline], [private]
Definition at line 226 of file simulator.h.
      : isolate_(isolate), fn_ptr_(fn_ptr) {}
Referenced by v8::internal::GeneratedCode< Return, Args >::FromAddress(), and v8::internal::GeneratedCode< Return, Args >::FromBuffer().
Member Function Documentation
Call()
template<typename Return , typename... Args>
DISABLE_CFI_ICALL Return v8::internal::GeneratedCode< Return, Args >::Call (Args... args) [inline]
Definition at line 184 of file simulator.h.
                                              {
    // When running without a simulator we call the entry directly.
// Starboard is a platform abstraction interface that also include Windows
// platforms like UWP.
#if defined(V8_TARGET_OS_WIN) && !defined(V8_OS_WIN) && \
    !defined(V8_OS_STARBOARD)
    FATAL("Generated code execution not possible during cross-compilation.");
#endif // defined(V8_TARGET_OS_WIN) && !defined(V8_OS_WIN)
#if ABI_USES_FUNCTION_DESCRIPTORS
#if V8_OS_ZOS
    // z/OS ABI requires function descriptors (FD). Artificially create a pseudo
    // FD to ensure correct dispatch to generated code.
    void* function_desc[2] = {0, reinterpret_cast<void*>(fn_ptr_)};
    asm volatile(" stg 5,%0 " : "=m"(function_desc[0])::"r5");
    Signature* fn = reinterpret_cast<Signature*>(function_desc);
    return fn(args...);
#else
    // AIX ABI requires function descriptors (FD). Artificially create a pseudo
    // FD to ensure correct dispatch to generated code. The 'volatile'
    // declaration is required to avoid the compiler from not observing the
    // alias of the pseudo FD to the function pointer, and hence, optimizing the
    // pseudo FD declaration/initialization away.
    volatile Address function_desc[] = {reinterpret_cast<Address>(fn_ptr_), 0,
                                        0};
    Signature* fn = reinterpret_cast<Signature*>(function_desc);
    return fn(args...);
#endif // V8_OS_ZOS
#else
    return fn_ptr_(args...);
#endif // ABI_USES_FUNCTION_DESCRIPTORS
  }
References v8::base::args, FATAL, and v8::internal::GeneratedCode< Return, Args >::fn_ptr_.
Referenced by v8::internal::GeneratedCode< Return, Args >::CallSandboxed(), and v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin().
CallSandboxed()
template<typename Return , typename... Args>
DISABLE_CFI_ICALL Return v8::internal::GeneratedCode< Return, Args >::CallSandboxed (Args... args) [inline]
Definition at line 217 of file simulator.h.
                                                       {
    EnterSandboxScope sandboxed;
    return Call(args...);
  }
References v8::base::args, and v8::internal::GeneratedCode< Return, Args >::Call().
FromAddress()
template<typename Return , typename... Args>
static GeneratedCode v8::internal::GeneratedCode< Return, Args >::FromAddress (Isolate * isolate, Address addr) [inline], [static]
Definition at line 154 of file simulator.h.
                                                                   {
    return GeneratedCode(isolate, reinterpret_cast<Signature*>(addr));
  }
References v8::internal::GeneratedCode< Return, Args >::GeneratedCode().
Referenced by v8::internal::GeneratedCode< Return, Args >::FromCode().
FromBuffer()
template<typename Return , typename... Args>
static GeneratedCode v8::internal::GeneratedCode< Return, Args >::FromBuffer (Isolate * isolate, uint8_t * buffer) [inline], [static]
Definition at line 158 of file simulator.h.
                                                                     {
    return GeneratedCode(isolate, reinterpret_cast<Signature*>(buffer));
  }
References v8::internal::GeneratedCode< Return, Args >::GeneratedCode().
FromCode()
template<typename Return , typename... Args>
static GeneratedCode v8::internal::GeneratedCode< Return, Args >::FromCode (Isolate * isolate, Tagged< Code > code) [inline], [static]
Definition at line 162 of file simulator.h.
                                                                     {
    return FromAddress(isolate, code->instruction_start());
  }
References code, and v8::internal::GeneratedCode< Return, Args >::FromAddress().
Referenced by v8::internal::NativeRegExpMacroAssembler::Execute().
Friends And Related Function Documentation
GeneratedCode< Return(Args...)>
template<typename Return , typename... Args>
friend class GeneratedCode< Return(Args...)> [friend]
Definition at line 217 of file simulator.h.
Member Data Documentation
fn_ptr_
template<typename Return , typename... Args>
Signature* v8::internal::GeneratedCode< Return, Args >::fn_ptr_ [private]
Definition at line 225 of file simulator.h.
Referenced by v8::internal::GeneratedCode< Return, Args >::Call().
isolate_
template<typename Return , typename... Args>
Isolate* v8::internal::GeneratedCode< Return, Args >::isolate_ [private]
Definition at line 224 of file simulator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/simulator.h