v8::base::RegionAllocator Class Reference
#include <region-allocator.h>
Classes
struct AddressEndOrder
class Region
struct SizeAddressOrder
Public Types
enum class RegionState { kFree
, kExcluded
, kAllocated
 }
enum class AllocationStrategy { kFirstFit
, kLargestFit
 }
using Address = uintptr_t
using SplitMergeCallback = std::function< void(Address start, size_t size)>
Public Member Functions
RegionAllocator (Address address, size_t size, size_t page_size)
RegionAllocator (const RegionAllocator &)=delete
RegionAllocator & operator= (const RegionAllocator &)=delete
~RegionAllocator ()
void set_on_split_callback (SplitMergeCallback callback)
void set_on_merge_callback (SplitMergeCallback callback)
Address AllocateRegion (size_t size, AllocationStrategy allocation_strategy=AllocationStrategy::kFirstFit)
Address AllocateRegion (RandomNumberGenerator *rng, size_t size)
bool AllocateRegionAt (Address requested_address, size_t size, RegionState region_state=RegionState::kAllocated)
Address AllocateAlignedRegion (size_t size, size_t alignment)
Address AllocateRegion (Address hint, size_t size, size_t alignment)
size_t FreeRegion (Address address)
size_t TrimRegion (Address address, size_t new_size)
bool TryGrowRegion (Address address, size_t new_size)
size_t CheckRegion (Address address)
bool IsFree (Address address, size_t size)
Address begin () const
Address end () const
size_t size () const
bool contains (Address address) const
bool contains (Address address, size_t size) const
size_t free_size () const
size_t page_size () const
void Print (std::ostream &os) const
Static Public Attributes
static constexpr Address kAllocationFailure = static_cast<Address>(-1)
Private Types
using AllRegionsSet = std::set< Region *, AddressEndOrder >
Private Member Functions
AllRegionsSet::iterator FindRegion (Address address)
void FreeListAddRegion (Region *region)
Region * FreeListFindRegion (size_t size)
Region * FreeListFindLargestRegion (size_t size)
void FreeListRemoveRegion (Region *region)
Region * Split (Region *region, size_t new_size)
void Merge (AllRegionsSet::iterator prev_iter, AllRegionsSet::iterator next_iter)
FRIEND_TEST (RegionAllocatorTest, AllocateExcluded)
FRIEND_TEST (RegionAllocatorTest, AllocateRegionRandom)
FRIEND_TEST (RegionAllocatorTest, Contains)
FRIEND_TEST (RegionAllocatorTest, FindRegion)
FRIEND_TEST (RegionAllocatorTest, Fragmentation)
Private Attributes
const Region whole_region_
const size_t region_size_in_pages_
const size_t max_load_for_randomization_
size_t free_size_
const size_t page_size_
AllRegionsSet all_regions_
std::set< Region *, SizeAddressOrder > free_regions_
SplitMergeCallback on_split_
SplitMergeCallback on_merge_
Detailed Description
Definition at line 26 of file region-allocator.h.
Member Typedef Documentation
Address
using v8::base::RegionAllocator::Address = uintptr_t
Definition at line 28 of file region-allocator.h.
AllRegionsSet
using v8::base::RegionAllocator::AllRegionsSet = std::set<Region*, AddressEndOrder> [private]
Definition at line 190 of file region-allocator.h.
SplitMergeCallback
using v8::base::RegionAllocator::SplitMergeCallback = std::function<void(Address start, size_t size)>
Definition at line 30 of file region-allocator.h.
Member Enumeration Documentation
AllocationStrategy
enum v8::base::RegionAllocator::AllocationStrategy [strong]
Enumerator
kFirstFit
kLargestFit
Definition at line 43 of file region-allocator.h.
                                {
    // Allocates in the first large enough free region.
    kFirstFit,
    // Allocates in the largest free region.
    kLargestFit,
  };
RegionState
enum v8::base::RegionAllocator::RegionState [strong]
Enumerator
kFree
kExcluded
kAllocated
Definition at line 34 of file region-allocator.h.
                         {
    // The region can be allocated from.
    kFree,
    // The region has been carved out of the wider area and is not allocatable.
    kExcluded,
    // The region has been allocated and is managed by a RegionAllocator.
    kAllocated,
  };
Constructor & Destructor Documentation
RegionAllocator() [1/2]
v8::base::RegionAllocator::RegionAllocator (Address address, size_t size, size_t page_size)
Definition at line 23 of file region-allocator.cc.
    : whole_region_(memory_region_begin, memory_region_size,
                    RegionState::kFree),
      region_size_in_pages_(size() / page_size),
      max_load_for_randomization_(
          static_cast<size_t>(size() * kMaxLoadFactorForRandomization)),
      free_size_(0),
      page_size_(page_size) {
  CHECK_LT(begin(), end());
  CHECK(base::bits::IsPowerOfTwo(page_size_));
  CHECK(IsAligned(size(), page_size_));
  CHECK(IsAligned(begin(), page_size_));
  // Initial region.
  Region* region = new Region(whole_region_);
  all_regions_.insert(region);
  FreeListAddRegion(region);
}
References all_regions_, begin(), CHECK, CHECK_LT, end(), FreeListAddRegion(), IsAligned(), v8::base::bits::IsPowerOfTwo(), page_size_, size(), and whole_region_.
RegionAllocator() [2/2]
v8::base::RegionAllocator::RegionAllocator (const RegionAllocator &) [delete]
 RegionAllocator()
v8::base::RegionAllocator::~RegionAllocator ()
Definition at line 45 of file region-allocator.cc.
                                  {
  // TODO(chromium:1218005) either (D)CHECK that all allocated regions have
  // been freed again (and thus merged into a single region) or do that now.
  for (Region* region : all_regions_) {
    delete region;
  }
}
References all_regions_.
Member Function Documentation
AllocateAlignedRegion()
RegionAllocator::Address v8::base::RegionAllocator::AllocateAlignedRegion (size_t size, size_t alignment)
Definition at line 239 of file region-allocator.cc.
                                   {
  DCHECK(IsAligned(size, page_size_));
  DCHECK(IsAligned(alignment, page_size_));
  DCHECK_GE(alignment, page_size_);
  const size_t padded_size = size + alignment - page_size_;
  Region* region = FreeListFindRegion(padded_size);
  if (region == nullptr) {
    // In case we are out of space we might still fit an allocation without
    // padding and the result might still satisfy our alignment requirements.
    region = FreeListFindRegion(size);
  }
  if (region == nullptr) return kAllocationFailure;
  if (!IsAligned(region->begin(), alignment)) {
    size_t start = RoundUp(region->begin(), alignment);
    if (start + size > region->end()) {
      return kAllocationFailure;
    }
    region = Split(region, start - region->begin());
    DCHECK_EQ(region->begin(), start);
    DCHECK(IsAligned(region->begin(), alignment));
  }
  if (region->size() != size) {
    Split(region, size);
  }
  DCHECK(IsAligned(region->begin(), alignment));
  DCHECK_EQ(region->size(), size);
  // Mark region as used.
  FreeListRemoveRegion(region);
  region->set_state(RegionState::kAllocated);
  return region->begin();
}
References v8::base::AddressRegion::begin(), DCHECK, DCHECK_EQ, DCHECK_GE, v8::base::AddressRegion::end(), FreeListFindRegion(), FreeListRemoveRegion(), IsAligned(), kAllocated, kAllocationFailure, page_size_, RoundUp(), v8::base::RegionAllocator::Region::set_state(), v8::base::AddressRegion::size(), size(), and Split().
Referenced by v8::base::BoundedPageAllocator::AllocatePages(), and AllocateRegion().
AllocateRegion() [1/3]
RegionAllocator::Address v8::base::RegionAllocator::AllocateRegion (Address hint, size_t size, size_t alignment)
Definition at line 276 of file region-allocator.cc.
                                                                           {
  DCHECK(IsAligned(alignment, page_size()));
  DCHECK(IsAligned(hint, alignment));
  if (hint && contains(hint, size)) {
    if (AllocateRegionAt(hint, size)) {
      return hint;
    }
  }
  Address address;
  if (alignment <= page_size()) {
    // TODO(chromium:1218005): Consider using randomized version here.
    address = AllocateRegion(size);
  } else {
    address = AllocateAlignedRegion(size, alignment);
  }
  return address;
}
References AllocateAlignedRegion(), AllocateRegion(), AllocateRegionAt(), contains(), DCHECK, IsAligned(), page_size(), and size().
AllocateRegion() [2/3]
RegionAllocator::Address v8::base::RegionAllocator::AllocateRegion (RandomNumberGenerator * rng, size_t size)
Definition at line 173 of file region-allocator.cc.
                                             {
  if (free_size() >= max_load_for_randomization_) {
    // There is enough free space for trying to randomize the address.
    size_t random = 0;
    for (int i = 0; i < kMaxRandomizationAttempts; i++) {
      rng->NextBytes(&random, sizeof(random));
      size_t random_offset = page_size_ * (random % region_size_in_pages_);
      Address address = begin() + random_offset;
      if (AllocateRegionAt(address, size, RegionState::kAllocated)) {
        return address;
      }
    }
    // Fall back to free list allocation.
  }
  return AllocateRegion(size);
}
References AllocateRegion(), AllocateRegionAt(), begin(), free_size(), kAllocated, v8::base::kMaxRandomizationAttempts, max_load_for_randomization_, v8::base::RandomNumberGenerator::NextBytes(), page_size_, random(), region_size_in_pages_, and size().
AllocateRegion() [3/3]
RegionAllocator::Address v8::base::RegionAllocator::AllocateRegion (size_t size, AllocationStrategy allocation_strategy = AllocationStrategy::kFirstFit)
Definition at line 145 of file region-allocator.cc.
                                                         {
  DCHECK_NE(size, 0);
  DCHECK(IsAligned(size, page_size_));
  Region* region = nullptr;
  if (allocation_strategy == AllocationStrategy::kFirstFit) {
    region = FreeListFindRegion(size);
  } else {
    DCHECK_EQ(allocation_strategy, AllocationStrategy::kLargestFit);
    region = FreeListFindLargestRegion(size);
  }
  if (region == nullptr) return kAllocationFailure;
  if (region->size() != size) {
    Split(region, size);
  }
  DCHECK(IsAligned(region->begin(), page_size_));
  DCHECK_EQ(region->size(), size);
  // Mark region as used.
  FreeListRemoveRegion(region);
  region->set_state(RegionState::kAllocated);
  return region->begin();
}
References v8::base::AddressRegion::begin(), DCHECK, DCHECK_EQ, DCHECK_NE, FreeListFindLargestRegion(), FreeListFindRegion(), FreeListRemoveRegion(), IsAligned(), kAllocated, kAllocationFailure, kFirstFit, kLargestFit, page_size_, v8::base::RegionAllocator::Region::set_state(), v8::base::AddressRegion::size(), size(), and Split().
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePages(), AllocateRegion(), v8::base::VirtualAddressSubspace::AllocateSharedPages(), and v8::base::VirtualAddressSubspace::AllocateSubspace().
AllocateRegionAt()
bool v8::base::RegionAllocator::AllocateRegionAt (Address requested_address, size_t size, RegionState region_state = RegionState::kAllocated)
Definition at line 192 of file region-allocator.cc.
                                                                 {
  DCHECK(IsAligned(requested_address, page_size_));
  DCHECK_NE(size, 0);
  DCHECK(IsAligned(size, page_size_));
  DCHECK_NE(region_state, RegionState::kFree);
  Address requested_end = requested_address + size;
  // Fail if the region would outgrow the total reservation or the addition
  // overflows.
  if (requested_end > end() || requested_end < requested_address) {
    return false;
  }
  DCHECK_LE(requested_end, end());
  Region* region;
  {
    AllRegionsSet::iterator region_iter = FindRegion(requested_address);
    if (region_iter == all_regions_.end()) {
      return false;
    }
    region = *region_iter;
  }
  if (!region->is_free() || region->end() < requested_end) {
    return false;
  }
  // Found free region that includes the requested one.
  if (region->begin() != requested_address) {
    // Split the region at the |requested_address| boundary.
    size_t new_size = requested_address - region->begin();
    DCHECK(IsAligned(new_size, page_size_));
    region = Split(region, new_size);
  }
  if (region->end() != requested_end) {
    // Split the region at the |requested_end| boundary.
    Split(region, size);
  }
  DCHECK_EQ(region->begin(), requested_address);
  DCHECK_EQ(region->size(), size);
  // Mark region as used.
  FreeListRemoveRegion(region);
  region->set_state(region_state);
  return true;
}
References all_regions_, v8::base::AddressRegion::begin(), DCHECK, DCHECK_EQ, DCHECK_LE, DCHECK_NE, v8::base::AddressRegion::end(), end(), FindRegion(), FreeListRemoveRegion(), v8::base::RegionAllocator::Region::is_free(), IsAligned(), kFree, page_size_, v8::base::RegionAllocator::Region::set_state(), v8::base::AddressRegion::size(), size(), and Split().
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocateGuardRegion(), v8::base::VirtualAddressSubspace::AllocateGuardRegion(), v8::base::BoundedPageAllocator::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePagesAt(), AllocateRegion(), v8::base::BoundedPageAllocator::ReserveForSharedMemoryMapping(), and TryGrowRegion().
begin()
Address v8::base::RegionAllocator::begin () const [inline]
Definition at line 128 of file region-allocator.h.
{ return whole_region_.begin(); }
Referenced by AllocateRegion(), v8::base::BoundedPageAllocator::begin(), Print(), and RegionAllocator().
CheckRegion()
size_t v8::base::RegionAllocator::CheckRegion (Address address)
Definition at line 378 of file region-allocator.cc.
                                                   {
  AllRegionsSet::iterator region_iter = FindRegion(address);
  if (region_iter == all_regions_.end()) {
    return 0;
  }
  Region* region = *region_iter;
  if (region->begin() != address || region->is_free()) {
    return 0;
  }
  return region->size();
}
References all_regions_, v8::base::AddressRegion::begin(), FindRegion(), v8::base::RegionAllocator::Region::is_free(), and v8::base::AddressRegion::size().
Referenced by v8::base::BoundedPageAllocator::ReleasePages().
contains() [1/2]
bool v8::base::RegionAllocator::contains (Address address) const [inline]
Definition at line 132 of file region-allocator.h.
                                       {
    return whole_region_.contains(address);
  }
Referenced by v8::base::BoundedPageAllocator::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePagesAt(), AllocateRegion(), IsFree(), v8::base::BoundedPageAllocator::RecommitPages(), v8::base::BoundedPageAllocator::ReserveForSharedMemoryMapping(), and v8::base::BoundedPageAllocator::SetPermissions().
contains() [2/2]
bool v8::base::RegionAllocator::contains (Address address, size_t size) const [inline]
Definition at line 136 of file region-allocator.h.
                                                    {
    return whole_region_.contains(address, size);
  }
References size().
end()
Address v8::base::RegionAllocator::end () const [inline]
Definition at line 129 of file region-allocator.h.
{ return whole_region_.end(); }
Referenced by AllocateRegionAt(), Print(), and RegionAllocator().
FindRegion()
RegionAllocator::AllRegionsSet::iterator v8::base::RegionAllocator::FindRegion (Address address) [private]
Definition at line 53 of file region-allocator.cc.
                     {
  if (!whole_region_.contains(address)) return all_regions_.end();
  Region key(address, 0, RegionState::kFree);
  AllRegionsSet::iterator iter = all_regions_.upper_bound(&key);
  // Regions in |all_regions_| are compared by end() values and key's end()
  // points exactly to the address we are querying, so the upper_bound will
  // find the region whose |end()| is greater than the requested address.
  DCHECK_NE(iter, all_regions_.end());
  DCHECK((*iter)->contains(address));
  return iter;
}
References all_regions_, v8::base::AddressRegion::contains(), DCHECK, DCHECK_NE, v8::internal::key, kFree, and whole_region_.
Referenced by AllocateRegionAt(), CheckRegion(), IsFree(), TrimRegion(), and TryGrowRegion().
free_size()
size_t v8::base::RegionAllocator::free_size () const [inline]
Definition at line 141 of file region-allocator.h.
{ return free_size_; }
Referenced by AllocateRegion(), and Print().
FreeListAddRegion()
void v8::base::RegionAllocator::FreeListAddRegion (Region * region) [private]
Definition at line 67 of file region-allocator.cc.
                                                      {
  free_size_ += region->size();
  free_regions_.insert(region);
}
References free_regions_, free_size_, and v8::base::AddressRegion::size().
Referenced by RegionAllocator(), Split(), and TrimRegion().
FreeListFindLargestRegion()
RegionAllocator::Region * v8::base::RegionAllocator::FreeListFindLargestRegion (size_t size) [private]
Definition at line 78 of file region-allocator.cc.
                 {
  Region* region = nullptr;
  for (Region* free_region : free_regions_) {
    if (free_region->size() < size) continue;
    if (!region || free_region->size() > region->size()) {
      region = free_region;
    }
  }
  return region;
}
References free_regions_, v8::base::AddressRegion::size(), and size().
Referenced by AllocateRegion().
FreeListFindRegion()
RegionAllocator::Region * v8::base::RegionAllocator::FreeListFindRegion (size_t size) [private]
Definition at line 72 of file region-allocator.cc.
                                                                      {
  Region key(0, size, RegionState::kFree);
  auto iter = free_regions_.lower_bound(&key);
  return iter == free_regions_.end() ? nullptr : *iter;
}
References free_regions_, v8::internal::key, kFree, nullptr, and size().
Referenced by AllocateAlignedRegion(), and AllocateRegion().
FreeListRemoveRegion()
void v8::base::RegionAllocator::FreeListRemoveRegion (Region * region) [private]
Definition at line 90 of file region-allocator.cc.
                                                         {
  DCHECK(region->is_free());
  auto iter = free_regions_.find(region);
  DCHECK_NE(iter, free_regions_.end());
  DCHECK_EQ(region, *iter);
  DCHECK_LE(region->size(), free_size_);
  free_size_ -= region->size();
  free_regions_.erase(iter);
}
References DCHECK, DCHECK_EQ, DCHECK_LE, DCHECK_NE, free_regions_, free_size_, v8::base::RegionAllocator::Region::is_free(), and v8::base::AddressRegion::size().
Referenced by AllocateAlignedRegion(), AllocateRegion(), AllocateRegionAt(), Split(), and TrimRegion().
FreeRegion()
size_t v8::base::RegionAllocator::FreeRegion (Address address) [inline]
Definition at line 109 of file region-allocator.h.
{ return TrimRegion(address, 0); }
Referenced by v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePagesAt(), v8::base::VirtualAddressSubspace::AllocateSharedPages(), v8::base::VirtualAddressSubspace::AllocateSubspace(), v8::base::EmulatedVirtualAddressSubspace::FreeGuardRegion(), v8::base::VirtualAddressSubspace::FreeGuardRegion(), v8::base::EmulatedVirtualAddressSubspace::FreePages(), v8::base::VirtualAddressSubspace::FreePages(), v8::base::BoundedPageAllocator::FreePages(), v8::base::VirtualAddressSubspace::FreeSharedPages(), and v8::base::VirtualAddressSubspace::FreeSubspace().
FRIEND_TEST() [1/5]
v8::base::RegionAllocator::FRIEND_TEST (RegionAllocatorTest , AllocateExcluded) [private]
FRIEND_TEST() [2/5]
v8::base::RegionAllocator::FRIEND_TEST (RegionAllocatorTest , AllocateRegionRandom) [private]
FRIEND_TEST() [3/5]
v8::base::RegionAllocator::FRIEND_TEST (RegionAllocatorTest , Contains) [private]
FRIEND_TEST() [4/5]
v8::base::RegionAllocator::FRIEND_TEST (RegionAllocatorTest , FindRegion) [private]
FRIEND_TEST() [5/5]
v8::base::RegionAllocator::FRIEND_TEST (RegionAllocatorTest , Fragmentation) [private]
IsFree()
bool v8::base::RegionAllocator::IsFree (Address address, size_t size)
Definition at line 390 of file region-allocator.cc.
                                                         {
  CHECK(contains(address, size));
  AllRegionsSet::iterator region_iter = FindRegion(address);
  if (region_iter == all_regions_.end()) {
    return true;
  }
  Region* region = *region_iter;
  return region->is_free() && region->contains(address, size);
}
References all_regions_, CHECK, v8::base::AddressRegion::contains(), contains(), FindRegion(), v8::base::RegionAllocator::Region::is_free(), and size().
Merge()
void v8::base::RegionAllocator::Merge (AllRegionsSet::iterator prev_iter, AllRegionsSet::iterator next_iter) [private]
Definition at line 128 of file region-allocator.cc.
                                                             {
  Region* prev = *prev_iter;
  Region* next = *next_iter;
  DCHECK_EQ(prev->end(), next->begin());
  if (on_merge_) on_merge_(prev->begin(), prev->size() + next->size());
  prev->set_size(prev->size() + next->size());
  all_regions_.erase(next_iter); // prev_iter stays valid.
  // The |next| region must already not be in the free list.
  DCHECK_EQ(free_regions_.find(next), free_regions_.end());
  delete next;
}
References all_regions_, v8::base::AddressRegion::begin(), DCHECK_EQ, v8::base::AddressRegion::end(), free_regions_, on_merge_, v8::base::AddressRegion::set_size(), and v8::base::AddressRegion::size().
Referenced by TrimRegion(), and TryGrowRegion().
operator=()
RegionAllocator& v8::base::RegionAllocator::operator= (const RegionAllocator &) [delete]
page_size()
size_t v8::base::RegionAllocator::page_size () const [inline]
Definition at line 145 of file region-allocator.h.
{ return page_size_; }
Referenced by v8::base::BoundedPageAllocator::AllocatePages(), and AllocateRegion().
Print()
void v8::base::RegionAllocator::Print (std::ostream & os) const
Definition at line 422 of file region-allocator.cc.
                                                {
  std::ios::fmtflags flags = os.flags(std::ios::hex | std::ios::showbase);
  os << "RegionAllocator: [" << begin() << ", " << end() << ")";
  os << "\nsize: " << size();
  os << "\nfree_size: " << free_size();
  os << "\npage_size: " << page_size_;
  os << "\nall regions: ";
  for (const Region* region : all_regions_) {
    os << "\n ";
    region->Print(os);
  }
  os << "\nfree regions: ";
  for (const Region* region : free_regions_) {
    os << "\n ";
    region->Print(os);
  }
  os << "\n";
  os.flags(flags);
}
References all_regions_, begin(), end(), flags(), free_regions_, free_size(), page_size_, and size().
set_on_merge_callback()
void v8::base::RegionAllocator::set_on_merge_callback (SplitMergeCallback callback) [inline]
Definition at line 73 of file region-allocator.h.
                                                          {
    on_merge_ = callback;
  }
Referenced by v8::base::VirtualAddressSubspace::VirtualAddressSubspace().
set_on_split_callback()
void v8::base::RegionAllocator::set_on_split_callback (SplitMergeCallback callback) [inline]
Definition at line 68 of file region-allocator.h.
                                                          {
    on_split_ = callback;
  }
Referenced by v8::base::VirtualAddressSubspace::VirtualAddressSubspace().
size()
size_t v8::base::RegionAllocator::size () const [inline]
Definition at line 130 of file region-allocator.h.
{ return whole_region_.size(); }
Referenced by AllocateAlignedRegion(), AllocateRegion(), AllocateRegionAt(), FreeListFindLargestRegion(), FreeListFindRegion(), IsFree(), Print(), RegionAllocator(), v8::base::BoundedPageAllocator::size(), and TrimRegion().
Split()
RegionAllocator::Region * v8::base::RegionAllocator::Split (Region * region, size_t new_size) [private]
Definition at line 100 of file region-allocator.cc.
                                                                 {
  DCHECK(IsAligned(new_size, page_size_));
  DCHECK_NE(new_size, 0);
  DCHECK_GT(region->size(), new_size);
  if (on_split_) on_split_(region->begin(), new_size);
  // Create new region and put it to the lists after the |region|.
  DCHECK(!region->is_excluded());
  RegionState state = region->state();
  Region* new_region =
      new Region(region->begin() + new_size, region->size() - new_size, state);
  if (state == RegionState::kFree) {
    // Remove region from the free list before updating it's size.
    FreeListRemoveRegion(region);
  }
  region->set_size(new_size);
  all_regions_.insert(new_region);
  if (state == RegionState::kFree) {
    FreeListAddRegion(region);
    FreeListAddRegion(new_region);
  }
  return new_region;
}
References all_regions_, v8::base::AddressRegion::begin(), DCHECK, DCHECK_GT, DCHECK_NE, FreeListAddRegion(), FreeListRemoveRegion(), v8::base::RegionAllocator::Region::is_excluded(), IsAligned(), kFree, on_split_, page_size_, v8::base::AddressRegion::set_size(), v8::base::AddressRegion::size(), and v8::base::RegionAllocator::Region::state().
Referenced by AllocateAlignedRegion(), AllocateRegion(), AllocateRegionAt(), and TrimRegion().
TrimRegion()
size_t v8::base::RegionAllocator::TrimRegion (Address address, size_t new_size)
Definition at line 299 of file region-allocator.cc.
                                                                   {
  DCHECK(IsAligned(new_size, page_size_));
  AllRegionsSet::iterator region_iter = FindRegion(address);
  if (region_iter == all_regions_.end()) {
    return 0;
  }
  Region* region = *region_iter;
  if (region->begin() != address || !region->is_allocated()) {
    return 0;
  }
  // The region must not be in the free list.
  DCHECK_EQ(free_regions_.find(*region_iter), free_regions_.end());
  if (new_size > 0) {
    region = Split(region, new_size);
    ++region_iter;
  }
  size_t size = region->size();
  region->set_state(RegionState::kFree);
  // Merge current region with the surrounding ones if they are free.
  if (region->end() != whole_region_.end()) {
    // There must be a range after the current one.
    AllRegionsSet::iterator next_iter = std::next(region_iter);
    DCHECK_NE(next_iter, all_regions_.end());
    if ((*next_iter)->is_free()) {
      // |next| region object will be deleted during merge, remove it from
      // the free list.
      FreeListRemoveRegion(*next_iter);
      Merge(region_iter, next_iter);
    }
  }
  if (new_size == 0 && region->begin() != whole_region_.begin()) {
    // There must be a range before the current one.
    AllRegionsSet::iterator prev_iter = std::prev(region_iter);
    DCHECK_NE(prev_iter, all_regions_.end());
    if ((*prev_iter)->is_free()) {
      // |prev| region's size will change, we'll have to re-insert it into
      // the proper place of the free list.
      FreeListRemoveRegion(*prev_iter);
      Merge(prev_iter, region_iter);
      // |prev| region becomes the current region.
      region_iter = prev_iter;
      region = *region_iter;
    }
  }
  FreeListAddRegion(region);
  return size;
}
References all_regions_, v8::base::AddressRegion::begin(), DCHECK, DCHECK_EQ, DCHECK_NE, v8::base::AddressRegion::end(), FindRegion(), free_regions_, FreeListAddRegion(), FreeListRemoveRegion(), v8::base::RegionAllocator::Region::is_allocated(), IsAligned(), kFree, Merge(), page_size_, v8::base::RegionAllocator::Region::set_state(), v8::base::AddressRegion::size(), size(), Split(), and whole_region_.
Referenced by v8::base::BoundedPageAllocator::ReleasePages(), and v8::base::BoundedPageAllocator::ResizeAllocationAt().
TryGrowRegion()
bool v8::base::RegionAllocator::TryGrowRegion (Address address, size_t new_size)
Definition at line 351 of file region-allocator.cc.
                                                                    {
  DCHECK(IsAligned(new_size, page_size_));
  AllRegionsSet::iterator region_iter = FindRegion(address);
  if (region_iter == all_regions_.end()) {
    return false;
  }
  Region* region = *region_iter;
  if (region->begin() != address || !region->is_allocated()) {
    return false;
  }
  // The region must not be in the free list.
  DCHECK_EQ(free_regions_.find(*region_iter), free_regions_.end());
  DCHECK_LT(region->size(), new_size);
  if (!AllocateRegionAt(region->end(), new_size - region->size())) {
    return false;
  }
  AllRegionsSet::iterator new_region_iter = std::next(region_iter);
  DCHECK_NE(new_region_iter, all_regions_.end());
  Merge(region_iter, new_region_iter);
  return true;
}
References all_regions_, AllocateRegionAt(), v8::base::AddressRegion::begin(), DCHECK, DCHECK_EQ, DCHECK_LT, DCHECK_NE, v8::base::AddressRegion::end(), FindRegion(), free_regions_, v8::base::RegionAllocator::Region::is_allocated(), IsAligned(), Merge(), page_size_, and v8::base::AddressRegion::size().
Referenced by v8::base::BoundedPageAllocator::ResizeAllocationAt().
Member Data Documentation
all_regions_
AllRegionsSet v8::base::RegionAllocator::all_regions_ [private]
Definition at line 191 of file region-allocator.h.
Referenced by AllocateRegionAt(), CheckRegion(), FindRegion(), IsFree(), Merge(), Print(), RegionAllocator(), Split(), TrimRegion(), TryGrowRegion(), and ~RegionAllocator().
free_regions_
std::set<Region*, SizeAddressOrder> v8::base::RegionAllocator::free_regions_ [private]
Definition at line 200 of file region-allocator.h.
Referenced by FreeListAddRegion(), FreeListFindLargestRegion(), FreeListFindRegion(), FreeListRemoveRegion(), Merge(), Print(), TrimRegion(), and TryGrowRegion().
free_size_
size_t v8::base::RegionAllocator::free_size_ [private]
Definition at line 179 of file region-allocator.h.
Referenced by FreeListAddRegion(), and FreeListRemoveRegion().
kAllocationFailure
constexpr Address v8::base::RegionAllocator::kAllocationFailure = static_cast<Address>(-1) [static], [constexpr]
Definition at line 32 of file region-allocator.h.
Referenced by AllocateAlignedRegion(), v8::base::EmulatedVirtualAddressSubspace::AllocatePages(), v8::base::VirtualAddressSubspace::AllocatePages(), v8::base::BoundedPageAllocator::AllocatePages(), AllocateRegion(), v8::base::VirtualAddressSubspace::AllocateSharedPages(), and v8::base::VirtualAddressSubspace::AllocateSubspace().
max_load_for_randomization_
const size_t v8::base::RegionAllocator::max_load_for_randomization_ [private]
Definition at line 176 of file region-allocator.h.
Referenced by AllocateRegion().
on_merge_
SplitMergeCallback v8::base::RegionAllocator::on_merge_ [private]
Definition at line 204 of file region-allocator.h.
Referenced by Merge().
on_split_
SplitMergeCallback v8::base::RegionAllocator::on_split_ [private]
Definition at line 203 of file region-allocator.h.
Referenced by Split().
page_size_
const size_t v8::base::RegionAllocator::page_size_ [private]
Definition at line 182 of file region-allocator.h.
Referenced by AllocateAlignedRegion(), AllocateRegion(), AllocateRegionAt(), Print(), RegionAllocator(), Split(), TrimRegion(), and TryGrowRegion().
region_size_in_pages_
const size_t v8::base::RegionAllocator::region_size_in_pages_ [private]
Definition at line 172 of file region-allocator.h.
Referenced by AllocateRegion().
whole_region_
const Region v8::base::RegionAllocator::whole_region_ [private]
Definition at line 169 of file region-allocator.h.
Referenced by FindRegion(), RegionAllocator(), and TrimRegion().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/region-allocator.h
/mnt/V8SourceCode/src/base/region-allocator.cc