v8::internal::OptimizingCompileTaskExecutor Class Reference
#include <optimizing-compile-dispatcher.h>
Classes
class CompileTask
Public Member Functions
OptimizingCompileTaskExecutor ()
~OptimizingCompileTaskExecutor ()
void EnsureStarted ()
void Stop ()
void RunCompilationJob (OptimizingCompileTaskState &task_state, Isolate *isolate, LocalIsolate &local_isolate, TurbofanCompilationJob *job)
TurbofanCompilationJob * NextInput (OptimizingCompileTaskState &task_state)
TurbofanCompilationJob * NextInputIfIsolateMatches (OptimizingCompileTaskState &task_state)
bool IsTaskRunningForIsolate (Isolate *isolate)
void ClearTaskState (OptimizingCompileTaskState &task_state)
void ResetJob (OptimizingCompileTaskState &task_state)
bool TryQueueForOptimization (std::unique_ptr< TurbofanCompilationJob > &job)
void WaitUntilCompilationJobsDoneForIsolate (Isolate *isolate)
void CancelCompilationJobsForIsolate (Isolate *isolate)
bool HasCompilationJobsForIsolate (Isolate *isolate)
Private Attributes
OptimizingCompileInputQueue input_queue_
int recompilation_delay_
std::unique_ptr< JobHandle > job_handle_
base::OwnedVector< OptimizingCompileTaskState > task_states_
bool is_initialized_ = false
Static Private Attributes
static constexpr TaskPriority kTaskPriority = TaskPriority::kUserVisible
static constexpr TaskPriority kEfficiencyTaskPriority
Friends
class OptimizingCompileDispatcher
Detailed Description
Definition at line 75 of file optimizing-compile-dispatcher.h.
Constructor & Destructor Documentation
OptimizingCompileTaskExecutor()
v8::internal::OptimizingCompileTaskExecutor::OptimizingCompileTaskExecutor ()
Definition at line 94 of file optimizing-compile-dispatcher.cc.
    : input_queue_(v8_flags.concurrent_recompilation_queue_length),
      recompilation_delay_(v8_flags.concurrent_recompilation_delay) {}
 OptimizingCompileTaskExecutor()
v8::internal::OptimizingCompileTaskExecutor::~OptimizingCompileTaskExecutor ()
Definition at line 98 of file optimizing-compile-dispatcher.cc.
                                                              {
  DCHECK_EQ(input_queue_.Length(), 0);
  DCHECK(!job_handle_);
}
References v8::internal::DCHECK(), DCHECK_EQ, input_queue_, job_handle_, and v8::internal::OptimizingCompileInputQueue::Length().
Member Function Documentation
CancelCompilationJobsForIsolate()
void v8::internal::OptimizingCompileTaskExecutor::CancelCompilationJobsForIsolate (Isolate * isolate)
Definition at line 241 of file optimizing-compile-dispatcher.cc.
                      {
  base::MutexGuard guard(&input_queue_.mutex_);
  DCHECK(!input_queue_.HasJobForIsolate(isolate));
  for (auto& task_state : task_states_) {
    if (task_state.isolate == isolate && task_state.job) {
      task_state.job->Cancel();
    }
  }
}
References v8::internal::DCHECK(), v8::internal::OptimizingCompileInputQueue::HasJobForIsolate(), input_queue_, v8::internal::OptimizingCompileInputQueue::mutex_, and task_states_.
Referenced by v8::internal::OptimizingCompileDispatcher::FlushQueues(), and v8::internal::OptimizingCompileDispatcher::StartTearDown().
ClearTaskState()
void v8::internal::OptimizingCompileTaskExecutor::ClearTaskState (OptimizingCompileTaskState & task_state)
Definition at line 192 of file optimizing-compile-dispatcher.cc.
                                            {
  base::MutexGuard guard(input_queue_.mutex_);
  DCHECK_NOT_NULL(task_state.isolate);
  task_state.isolate = nullptr;
  DCHECK_NULL(task_state.job);
  input_queue_.task_finished_.NotifyAll();
}
References DCHECK_NOT_NULL, DCHECK_NULL, input_queue_, v8::internal::OptimizingCompileTaskState::isolate, v8::internal::OptimizingCompileTaskState::job, v8::internal::OptimizingCompileInputQueue::mutex_, v8::base::ConditionVariable::NotifyAll(), and v8::internal::OptimizingCompileInputQueue::task_finished_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run().
EnsureStarted()
void v8::internal::OptimizingCompileTaskExecutor::EnsureStarted ()
Definition at line 103 of file optimizing-compile-dispatcher.cc.
                                                  {
  if (is_initialized_) return;
  is_initialized_ = true;
  if (v8_flags.concurrent_recompilation ||
      v8_flags.concurrent_builtin_generation) {
    int max_tasks;
    if (v8_flags.concurrent_turbofan_max_threads == 0) {
      max_tasks = V8::GetCurrentPlatform()->NumberOfWorkerThreads();
    } else {
      max_tasks = v8_flags.concurrent_turbofan_max_threads;
    }
    task_states_ =
        base::OwnedVector<OptimizingCompileTaskState>::New(max_tasks);
    job_handle_ = V8::GetCurrentPlatform()->PostJob(
        kTaskPriority, std::make_unique<CompileTask>(this));
  }
}
References v8::internal::V8::GetCurrentPlatform(), is_initialized_, job_handle_, kTaskPriority, v8::base::OwnedVector< T >::New(), v8::Platform::NumberOfWorkerThreads(), v8::Platform::PostJob(), task_states_, and v8::internal::v8_flags.
HasCompilationJobsForIsolate()
bool v8::internal::OptimizingCompileTaskExecutor::HasCompilationJobsForIsolate (Isolate * isolate)
Definition at line 185 of file optimizing-compile-dispatcher.cc.
                      {
  base::MutexGuard guard(input_queue_.mutex_);
  return input_queue_.HasJobForIsolate(isolate) ||
         IsTaskRunningForIsolate(isolate);
}
References v8::internal::OptimizingCompileInputQueue::HasJobForIsolate(), input_queue_, IsTaskRunningForIsolate(), and v8::internal::OptimizingCompileInputQueue::mutex_.
Referenced by v8::internal::OptimizingCompileDispatcher::HasJobs().
IsTaskRunningForIsolate()
bool v8::internal::OptimizingCompileTaskExecutor::IsTaskRunningForIsolate (Isolate * isolate)
Definition at line 173 of file optimizing-compile-dispatcher.cc.
                                                                            {
  input_queue_.mutex_.AssertHeld();
  for (auto& task_state : task_states_) {
    if (task_state.isolate == isolate) {
      return true;
    }
  }
  return false;
}
References v8::base::Mutex::AssertHeld(), input_queue_, v8::internal::OptimizingCompileInputQueue::mutex_, and task_states_.
Referenced by HasCompilationJobsForIsolate(), and WaitUntilCompilationJobsDoneForIsolate().
NextInput()
TurbofanCompilationJob * v8::internal::OptimizingCompileTaskExecutor::NextInput (OptimizingCompileTaskState & task_state)
Definition at line 136 of file optimizing-compile-dispatcher.cc.
                                            {
  return input_queue_.Dequeue(task_state);
}
References v8::internal::OptimizingCompileInputQueue::Dequeue(), and input_queue_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run().
NextInputIfIsolateMatches()
TurbofanCompilationJob * v8::internal::OptimizingCompileTaskExecutor::NextInputIfIsolateMatches (OptimizingCompileTaskState & task_state)
Definition at line 142 of file optimizing-compile-dispatcher.cc.
                                            {
  return input_queue_.DequeueIfIsolateMatches(task_state);
}
References v8::internal::OptimizingCompileInputQueue::DequeueIfIsolateMatches(), and input_queue_.
Referenced by v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run().
ResetJob()
void v8::internal::OptimizingCompileTaskExecutor::ResetJob (OptimizingCompileTaskState & task_state)
Definition at line 201 of file optimizing-compile-dispatcher.cc.
                                            {
  base::MutexGuard guard(input_queue_.mutex_);
  DCHECK_NOT_NULL(task_state.isolate);
  DCHECK_NOT_NULL(task_state.job);
  task_state.job = nullptr;
}
References DCHECK_NOT_NULL, input_queue_, v8::internal::OptimizingCompileTaskState::isolate, v8::internal::OptimizingCompileTaskState::job, and v8::internal::OptimizingCompileInputQueue::mutex_.
Referenced by RunCompilationJob().
RunCompilationJob()
void v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob (OptimizingCompileTaskState & task_state, Isolate * isolate, LocalIsolate & local_isolate, TurbofanCompilationJob * job)
Definition at line 147 of file optimizing-compile-dispatcher.cc.
                                                              {
  TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                         "V8.OptimizeBackground", job->trace_id(),
                         TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  TimerEventScope<TimerEventRecompileConcurrent> timer(isolate);
  if (recompilation_delay_ != 0) {
    base::OS::Sleep(base::TimeDelta::FromMilliseconds(recompilation_delay_));
  }
  RCS_SCOPE(&local_isolate, RuntimeCallCounterId::kOptimizeBackgroundTurbofan);
  // The function may have already been optimized by OSR. Simply continue.
  CompilationJob::Status status =
      job->ExecuteJob(local_isolate.runtime_call_stats(), &local_isolate);
  USE(status); // Prevent an unused-variable error.
  // Remove the job first from task_state before adding it to the output queue.
  // As soon as the job is in the output queue it could be deleted any moment.
  ResetJob(task_state);
  isolate->optimizing_compile_dispatcher()->QueueFinishedJob(job);
}
References v8::internal::OptimizedCompilationJob::ExecuteJob(), v8::base::TimeDelta::FromMilliseconds(), v8::internal::Isolate::optimizing_compile_dispatcher(), v8::internal::OptimizingCompileDispatcher::QueueFinishedJob(), RCS_SCOPE, recompilation_delay_, ResetJob(), v8::internal::LocalIsolate::runtime_call_stats(), v8::base::OS::Sleep(), v8::internal::status, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_EVENT_WITH_FLOW0, v8::internal::TurbofanCompilationJob::trace_id(), and USE.
Referenced by v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run().
Stop()
void v8::internal::OptimizingCompileTaskExecutor::Stop ()
Definition at line 124 of file optimizing-compile-dispatcher.cc.
                                         {
  if (job_handle_) {
    DCHECK(job_handle_->IsValid());
    // Cancel all running tasks.
    job_handle_->Cancel();
    job_handle_.reset();
  }
  is_initialized_ = false;
}
References v8::internal::DCHECK(), is_initialized_, and job_handle_.
TryQueueForOptimization()
bool v8::internal::OptimizingCompileTaskExecutor::TryQueueForOptimization (std::unique_ptr< TurbofanCompilationJob > & job)
Definition at line 209 of file optimizing-compile-dispatcher.cc.
                                                {
  Isolate* isolate = job->isolate();
  DCHECK_NOT_NULL(isolate);
  if (input_queue_.Enqueue(job)) {
    if (job_handle_->UpdatePriorityEnabled()) {
      job_handle_->UpdatePriority(isolate->EfficiencyModeEnabledForTiering()
                                      ? kEfficiencyTaskPriority
                                      : kTaskPriority);
    }
    job_handle_->NotifyConcurrencyIncrease();
    return true;
  } else {
    return false;
  }
}
References DCHECK_NOT_NULL, v8::internal::Isolate::EfficiencyModeEnabledForTiering(), v8::internal::OptimizingCompileInputQueue::Enqueue(), input_queue_, v8::internal::Factory::isolate(), job_handle_, kEfficiencyTaskPriority, and kTaskPriority.
Referenced by v8::internal::OptimizingCompileDispatcher::TryQueueForOptimization().
WaitUntilCompilationJobsDoneForIsolate()
void v8::internal::OptimizingCompileTaskExecutor::WaitUntilCompilationJobsDoneForIsolate (Isolate * isolate)
Definition at line 227 of file optimizing-compile-dispatcher.cc.
                      {
  // Once we have ensured that no task is working on the given isolate, we also
  // know that there are no more LocalHeaps for this isolate from CompileTask.
  // This is because CompileTask::Run() only updates the isolate once the
  // LocalIsolate/LocalHeap for it was destroyed.
  base::MutexGuard guard(&input_queue_.mutex_);
  while (input_queue_.HasJobForIsolate(isolate) ||
         IsTaskRunningForIsolate(isolate)) {
    input_queue_.task_finished_.Wait(&input_queue_.mutex_);
  }
}
References v8::internal::OptimizingCompileInputQueue::HasJobForIsolate(), input_queue_, IsTaskRunningForIsolate(), v8::internal::OptimizingCompileInputQueue::mutex_, v8::internal::OptimizingCompileInputQueue::task_finished_, and v8::base::ConditionVariable::Wait().
Referenced by v8::internal::OptimizingCompileDispatcher::FinishTearDown(), and v8::internal::OptimizingCompileDispatcher::WaitUntilCompilationJobsDone().
Friends And Related Function Documentation
OptimizingCompileDispatcher
friend class OptimizingCompileDispatcher [friend]
Definition at line 152 of file optimizing-compile-dispatcher.h.
Member Data Documentation
input_queue_
OptimizingCompileInputQueue v8::internal::OptimizingCompileTaskExecutor::input_queue_ [private]
Definition at line 136 of file optimizing-compile-dispatcher.h.
Referenced by CancelCompilationJobsForIsolate(), ClearTaskState(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::GetMaxConcurrency(), HasCompilationJobsForIsolate(), IsTaskRunningForIsolate(), NextInput(), NextInputIfIsolateMatches(), ResetJob(), TryQueueForOptimization(), WaitUntilCompilationJobsDoneForIsolate(), and ~OptimizingCompileTaskExecutor().
is_initialized_
bool v8::internal::OptimizingCompileTaskExecutor::is_initialized_ = false [private]
Definition at line 150 of file optimizing-compile-dispatcher.h.
Referenced by EnsureStarted(), and Stop().
job_handle_
std::unique_ptr<JobHandle> v8::internal::OptimizingCompileTaskExecutor::job_handle_ [private]
Definition at line 145 of file optimizing-compile-dispatcher.h.
Referenced by EnsureStarted(), Stop(), TryQueueForOptimization(), and ~OptimizingCompileTaskExecutor().
kEfficiencyTaskPriority
constexpr TaskPriority v8::internal::OptimizingCompileTaskExecutor::kEfficiencyTaskPriority [static], [constexpr], [private]
Initial value:
=
      TaskPriority::kBestEffort
Definition at line 133 of file optimizing-compile-dispatcher.h.
Referenced by TryQueueForOptimization().
kTaskPriority
constexpr TaskPriority v8::internal::OptimizingCompileTaskExecutor::kTaskPriority = TaskPriority::kUserVisible [static], [constexpr], [private]
Definition at line 132 of file optimizing-compile-dispatcher.h.
Referenced by EnsureStarted(), and TryQueueForOptimization().
recompilation_delay_
int v8::internal::OptimizingCompileTaskExecutor::recompilation_delay_ [private]
Definition at line 143 of file optimizing-compile-dispatcher.h.
Referenced by RunCompilationJob().
task_states_
base::OwnedVector<OptimizingCompileTaskState> v8::internal::OptimizingCompileTaskExecutor::task_states_ [private]
Definition at line 147 of file optimizing-compile-dispatcher.h.
Referenced by CancelCompilationJobsForIsolate(), EnsureStarted(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::GetMaxConcurrency(), IsTaskRunningForIsolate(), and v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.h
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.cc