v8::internal::FeedbackMetadataIterator Class Reference
#include <feedback-vector.h>
Public Member Functions
FeedbackMetadataIterator (Handle< FeedbackMetadata > metadata)
FeedbackMetadataIterator (Tagged< FeedbackMetadata > metadata)
bool HasNext () const
FeedbackSlot Next ()
FeedbackSlotKind kind () const
int entry_size () const
Private Member Functions
Tagged< FeedbackMetadata > metadata () const
Private Attributes
Handle< FeedbackMetadata > metadata_handle_
Tagged< FeedbackMetadata > metadata_
FeedbackSlot cur_slot_
FeedbackSlot next_slot_
FeedbackSlotKind slot_kind_
Detailed Description
Definition at line 829 of file feedback-vector.h.
Constructor & Destructor Documentation
FeedbackMetadataIterator() [1/2]
v8::internal::FeedbackMetadataIterator::FeedbackMetadataIterator (Handle< FeedbackMetadata > metadata) [inline], [explicit]
Definition at line 831 of file feedback-vector.h.
      : metadata_handle_(metadata),
        next_slot_(FeedbackSlot(0)),
        slot_kind_(FeedbackSlotKind::kInvalid) {}
FeedbackMetadataIterator() [2/2]
v8::internal::FeedbackMetadataIterator::FeedbackMetadataIterator (Tagged< FeedbackMetadata > metadata) [inline], [explicit]
Definition at line 836 of file feedback-vector.h.
      : metadata_(metadata),
        next_slot_(FeedbackSlot(0)),
        slot_kind_(FeedbackSlotKind::kInvalid) {}
Member Function Documentation
entry_size()
int v8::internal::FeedbackMetadataIterator::entry_size () const [inline]
Definition at line 520 of file feedback-vector-inl.h.
                                               {
  return FeedbackMetadata::GetSlotSize(kind());
}
References v8::internal::FeedbackMetadata::GetSlotSize(), and kind().
Referenced by Next(), and v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails().
HasNext()
bool v8::internal::FeedbackMetadataIterator::HasNext () const [inline]
Definition at line 508 of file feedback-vector-inl.h.
                                             {
  return next_slot_.ToInt() < metadata()->slot_count();
}
References metadata(), next_slot_, and v8::internal::FeedbackSlot::ToInt().
Referenced by v8::internal::FeedbackVector::ClearSlots(), Next(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), and v8::internal::RUNTIME_FUNCTION().
kind()
FeedbackSlotKind v8::internal::FeedbackMetadataIterator::kind () const [inline]
Definition at line 846 of file feedback-vector.h.
                                {
    DCHECK_NE(FeedbackSlotKind::kInvalid, slot_kind_);
    return slot_kind_;
  }
References DCHECK_NE, v8::internal::kInvalid, and slot_kind_.
Referenced by entry_size(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), and v8::internal::RUNTIME_FUNCTION().
metadata()
Tagged<FeedbackMetadata> v8::internal::FeedbackMetadataIterator::metadata () const [inline], [private]
Definition at line 855 of file feedback-vector.h.
                                            {
    return !metadata_handle_.is_null() ? *metadata_handle_ : metadata_;
  }
References metadata_, and metadata_handle_.
Referenced by HasNext(), and Next().
Next()
FeedbackSlot v8::internal::FeedbackMetadataIterator::Next () [inline]
Definition at line 512 of file feedback-vector-inl.h.
                                            {
  DCHECK(HasNext());
  cur_slot_ = next_slot_;
  slot_kind_ = metadata()->GetKind(cur_slot_);
  next_slot_ = FeedbackSlot(next_slot_.ToInt() + entry_size());
  return cur_slot_;
}
References cur_slot_, v8::internal::DCHECK(), entry_size(), HasNext(), metadata(), next_slot_, slot_kind_, and v8::internal::FeedbackSlot::ToInt().
Referenced by v8::internal::FeedbackVector::ClearSlots(), v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails(), and v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
cur_slot_
FeedbackSlot v8::internal::FeedbackMetadataIterator::cur_slot_ [private]
Definition at line 864 of file feedback-vector.h.
Referenced by Next().
metadata_
Tagged<FeedbackMetadata> v8::internal::FeedbackMetadataIterator::metadata_ [private]
Definition at line 863 of file feedback-vector.h.
Referenced by metadata().
metadata_handle_
Handle<FeedbackMetadata> v8::internal::FeedbackMetadataIterator::metadata_handle_ [private]
Definition at line 862 of file feedback-vector.h.
Referenced by metadata().
next_slot_
FeedbackSlot v8::internal::FeedbackMetadataIterator::next_slot_ [private]
Definition at line 865 of file feedback-vector.h.
Referenced by HasNext(), and Next().
slot_kind_
FeedbackSlotKind v8::internal::FeedbackMetadataIterator::slot_kind_ [private]
Definition at line 866 of file feedback-vector.h.
Referenced by kind(), and Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector-inl.h