v8::internal::LoadWithReceiverAndVectorDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged()) static const expr inline Register LookupStartObjectRegister()
Static Public Member Functions
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1490 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::LoadWithReceiverAndVectorDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged()) const
registers()
constexpr auto v8::internal::LoadWithReceiverAndVectorDescriptor::registers () [static], [constexpr]
Definition at line 587 of file interface-descriptors-inl.h.
                                                              {
  return RegisterArray(
      LoadDescriptor::ReceiverRegister(), LookupStartObjectRegister(),
      LoadDescriptor::NameRegister(), LoadDescriptor::SlotRegister(),
      LoadWithVectorDescriptor::VectorRegister());
}
References v8::internal::LoadDescriptor::NameRegister(), v8::internal::RegisterArray(), and v8::internal::LoadDescriptor::SlotRegister().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h