v8::ThreadIsolatedAllocator Class Reference
An allocator that uses per-thread permissions to protect the memory.
#include <v8-platform.h>
Public Types
enum class Type { kPkey
 }
Public Member Functions
virtual ~ThreadIsolatedAllocator ()=default
virtual void * Allocate (size_t size)=0
virtual void Free (void *object)=0
virtual Type Type () const =0
virtual int Pkey () const
Return the pkey used to implement the thread isolation if Type == kPkey.
Detailed Description
An allocator that uses per-thread permissions to protect the memory.
The implementation is platform/hardware specific, e.g. using pkeys on x64.
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Definition at line 687 of file v8-platform.h.
Member Enumeration Documentation
Type
enum v8::ThreadIsolatedAllocator::Type [strong]
Enumerator
kPkey
Definition at line 695 of file v8-platform.h.
                  {
    kPkey,
  };
Constructor & Destructor Documentation
 ThreadIsolatedAllocator()
virtual v8::ThreadIsolatedAllocator::~ThreadIsolatedAllocator () [virtual], [default]
Member Function Documentation
Allocate()
virtual void* v8::ThreadIsolatedAllocator::Allocate (size_t size) [pure virtual]
Referenced by v8::internal::ThreadIsolation::StlAllocator< T >::allocate(), and v8::internal::ThreadIsolation::ConstructNew().
Free()
virtual void v8::ThreadIsolatedAllocator::Free (void * object) [pure virtual]
Referenced by v8::internal::ThreadIsolation::StlAllocator< T >::deallocate(), and v8::internal::ThreadIsolation::Delete().
Pkey()
virtual int v8::ThreadIsolatedAllocator::Pkey () const [inline], [virtual]
Return the pkey used to implement the thread isolation if Type == kPkey.
Definition at line 704 of file v8-platform.h.
{ return -1; }
Referenced by v8::internal::ThreadIsolation::Initialize().
Type()
virtual Type v8::ThreadIsolatedAllocator::Type () const [pure virtual]
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-platform.h