v8::debug::DebugDelegate Class Reference
#include <debug-interface.h>
Public Types
enum class ActionAfterInstrumentation { kPause
, kPauseIfBreakpointsHit
, kContinue
 }
Public Member Functions
virtual ~DebugDelegate ()=default
virtual void ScriptCompiled (v8::Local< Script > script, bool is_live_edited, bool has_compile_error)
virtual void BreakProgramRequested (v8::Local< v8::Context > paused_context, const std::vector< debug::BreakpointId > &inspector_break_points_hit, base::EnumSet< BreakReason > break_reasons={})
virtual ActionAfterInstrumentation BreakOnInstrumentation (v8::Local< v8::Context > paused_context, const debug::BreakpointId instrumentationId)
virtual void ExceptionThrown (v8::Local< v8::Context > paused_context, v8::Local< v8::Value > exception, v8::Local< v8::Value > promise, bool is_uncaught, ExceptionType exception_type)
virtual bool IsFunctionBlackboxed (v8::Local< debug::Script > script, const debug::Location &start, const debug::Location &end)
virtual bool ShouldBeSkipped (v8::Local< v8::debug::Script > script, int line, int column)
virtual void BreakpointConditionEvaluated (v8::Local< v8::Context > context, debug::BreakpointId breakpoint_id, bool exception_thrown, v8::Local< v8::Value > exception)
Detailed Description
Definition at line 301 of file debug-interface.h.
Member Enumeration Documentation
ActionAfterInstrumentation
enum v8::debug::DebugDelegate::ActionAfterInstrumentation [strong]
Enumerator
kPause
kPauseIfBreakpointsHit
kContinue
Definition at line 312 of file debug-interface.h.
                                        {
    kPause,
    kPauseIfBreakpointsHit,
    kContinue
  };
Constructor & Destructor Documentation
 DebugDelegate()
virtual v8::debug::DebugDelegate::~DebugDelegate () [virtual], [default]
Reimplemented in v8::internal::wasm::gdb_server::GdbServer::DebugDelegate.
Member Function Documentation
BreakOnInstrumentation()
virtual ActionAfterInstrumentation v8::debug::DebugDelegate::BreakOnInstrumentation (v8::Local< v8::Context > paused_context, const debug::BreakpointId instrumentationId) [inline], [virtual]
Reimplemented in v8_inspector::V8Debugger.
Definition at line 317 of file debug-interface.h.
                                                 {
    return ActionAfterInstrumentation::kPauseIfBreakpointsHit;
  }
References kPauseIfBreakpointsHit.
Referenced by v8::internal::Debug::OnInstrumentationBreak().
BreakpointConditionEvaluated()
virtual void v8::debug::DebugDelegate::BreakpointConditionEvaluated (v8::Local< v8::Context > context, debug::BreakpointId breakpoint_id, bool exception_thrown, v8::Local< v8::Value > exception) [inline], [virtual]
Reimplemented in v8_inspector::V8Debugger.
Definition at line 338 of file debug-interface.h.
                                                                        {}
Referenced by v8::internal::Debug::CheckBreakPoint().
BreakProgramRequested()
virtual void v8::debug::DebugDelegate::BreakProgramRequested (v8::Local< v8::Context > paused_context, const std::vector< debug::BreakpointId > & inspector_break_points_hit, base::EnumSet< BreakReason > break_reasons = {}) [inline], [virtual]
Definition at line 308 of file debug-interface.h.
                                               {}) {}
Referenced by v8::internal::Debug::OnDebugBreak().
ExceptionThrown()
virtual void v8::debug::DebugDelegate::ExceptionThrown (v8::Local< v8::Context > paused_context, v8::Local< v8::Value > exception, v8::Local< v8::Value > promise, bool is_uncaught, ExceptionType exception_type) [inline], [virtual]
Reimplemented in v8_inspector::V8Debugger, and v8::internal::wasm::gdb_server::GdbServer::DebugDelegate.
Definition at line 322 of file debug-interface.h.
                                                             {}
Referenced by v8::internal::Debug::OnException().
IsFunctionBlackboxed()
virtual bool v8::debug::DebugDelegate::IsFunctionBlackboxed (v8::Local< debug::Script > script, const debug::Location & start, const debug::Location & end) [inline], [virtual]
Reimplemented in v8_inspector::V8Debugger, and v8::internal::wasm::gdb_server::GdbServer::DebugDelegate.
Definition at line 326 of file debug-interface.h.
                                                              {
    return false;
  }
Referenced by v8::internal::Debug::IsFunctionBlackboxed().
ScriptCompiled()
virtual void v8::debug::DebugDelegate::ScriptCompiled (v8::Local< Script > script, bool is_live_edited, bool has_compile_error) [inline], [virtual]
Reimplemented in v8_inspector::V8Debugger, and v8::internal::wasm::gdb_server::GdbServer::DebugDelegate.
Definition at line 304 of file debug-interface.h.
                                                      {}
Referenced by v8::internal::Debug::ProcessCompileEvent().
ShouldBeSkipped()
virtual bool v8::debug::DebugDelegate::ShouldBeSkipped (v8::Local< v8::debug::Script > script, int line, int column) [inline], [virtual]
Reimplemented in v8_inspector::V8Debugger.
Definition at line 331 of file debug-interface.h.
                                           {
    return false;
  }
Referenced by v8::internal::Debug::ShouldBeSkipped().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-interface.h