v8::internal::compiler::JSOperator Class Reference
#include <js-operator.h>
Static Public Member Functions
static constexpr bool IsUnaryWithFeedback (Operator::Opcode opcode)
static constexpr bool IsBinaryWithFeedback (Operator::Opcode opcode)
Detailed Description
Definition at line 53 of file js-operator.h.
Member Function Documentation
IsBinaryWithFeedback()
static constexpr bool v8::internal::compiler::JSOperator::IsBinaryWithFeedback (Operator::Opcode opcode) [inline], [static], [constexpr]
Definition at line 67 of file js-operator.h.
                                                                    {
#define CASE(Name, ...) \
  case IrOpcode::k##Name: \
    return true;
    switch (opcode) {
      JS_BINOP_WITH_FEEDBACK(CASE);
      default:
        return false;
    }
#undef CASE
  }
References CASE, and JS_BINOP_WITH_FEEDBACK.
Referenced by v8::internal::compiler::anonymous_namespace{js-operator.cc}::BinopProperties(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::JSBinaryOpNode::JSBinaryOpNode(), and v8::internal::compiler::JSGenericLowering::ReplaceBinaryOpWithBuiltinCall().
IsUnaryWithFeedback()
static constexpr bool v8::internal::compiler::JSOperator::IsUnaryWithFeedback (Operator::Opcode opcode) [inline], [static], [constexpr]
Definition at line 55 of file js-operator.h.
                                                                   {
#define CASE(Name, ...) \
  case IrOpcode::k##Name: \
    return true;
    switch (opcode) {
      JS_UNOP_WITH_FEEDBACK(CASE);
      default:
        return false;
    }
#undef CASE
  }
References CASE, and JS_UNOP_WITH_FEEDBACK.
Referenced by v8::internal::compiler::FeedbackParameterOf(), and v8::internal::compiler::JSUnaryOpNode::JSUnaryOpNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h