v8::internal::compiler::turboshaft::FloatType< Bits > Class Template Reference
#include <types.h>
Public Types
enum Special : uint32_t { kNoSpecialValues = 0x0
, kNaN = 0x1
, kMinusZero = 0x2
 }
using float_t = float_type< Bits >
using value_type = float_t
Public Member Functions
bool is_only_special_values () const
bool is_only_nan () const
bool is_only_minus_zero () const
bool is_range () const
bool is_set () const
bool is_any () const
bool is_constant () const
uint32_t special_values () const
bool has_special_values () const
bool has_nan () const
bool has_minus_zero () const
float_t range_min () const
float_t range_max () const
std::pair< float_t, float_t > range () const
int set_size () const
float_t set_element (int index) const
base::Vector< const float_t > set_elements () const
float_t min () const
float_t max () const
std::pair< float_t, float_t > minmax () const
std::optional< float_t > try_get_constant () const
bool is_constant (float_t value) const
float_t range_or_set_min () const
float_t range_or_set_max () const
std::pair< float_t, float_t > range_or_set_minmax () const
bool Contains (float_t value) const
bool Equals (const FloatType &other) const
bool IsSubtypeOf (const FloatType &other) const
void PrintTo (std::ostream &stream) const
Handle< TurboshaftType > AllocateOnHeap (Factory *factory) const
Static Public Member Functions
static FloatType OnlySpecialValues (uint32_t special_values)
static FloatType NaN ()
static FloatType MinusZero ()
static FloatType Any (uint32_t special_values=Special::kNaN|Special::kMinusZero)
static FloatType Range (float_t min, float_t max, Zone *zone)
static FloatType Range (float_t min, float_t max, uint32_t special_values, Zone *zone)
template<size_t N>
static FloatType Set (const base::SmallVector< const float_t, N > &elements, Zone *zone)
template<size_t N>
static FloatType Set (const base::SmallVector< float_t, N > &elements, uint32_t special_values, Zone *zone)
static FloatType Set (const std::initializer_list< float_t > &elements, uint32_t special_values, Zone *zone)
static FloatType Set (const std::vector< float_t > &elements, Zone *zone)
static FloatType Set (const std::vector< float_t > &elements, uint32_t special_values, Zone *zone)
static FloatType Set (base::Vector< const float_t > elements, uint32_t special_values, Zone *zone)
static FloatType Constant (float_t constant)
static FloatType LeastUpperBound (const FloatType &lhs, const FloatType &rhs, Zone *zone)
static Type Intersect (const FloatType &lhs, const FloatType &rhs, Zone *zone)
Static Public Attributes
static constexpr int kMaxSetSize = 8
Private Types
enum class SubKind : uint8_t { kRange
, kSet
, kOnlySpecialValues
 }
using Payload_Range = detail::Payload_Range< float_t >
using Payload_InlineSet = detail::Payload_InlineSet< float_t >
using Payload_OutlineSet = detail::Payload_OutlineSet< float_t >
using Payload_OnlySpecial = detail::Payload_Empty
Private Member Functions
SubKind sub_kind () const
template<typename Payload >
FloatType (SubKind sub_kind, uint8_t set_size, uint32_t special_values, const Payload &payload)
Static Private Member Functions
static uint32_t IdentifyMinusZero (float_t &value)
static Type ReplacedSpecialValues (const FloatType &t, uint32_t special_values)
Static Private Attributes
static constexpr int kMaxInlineSetSize = 2
static constexpr Kind KIND = Bits == 32 ? Kind::kFloat32 : Kind::kFloat64
Friends
class Type
Additional Inherited Members
Detailed Description
template<size_t Bits>
class v8::internal::compiler::turboshaft::FloatType< Bits >
Definition at line 509 of file types.h.
Member Typedef Documentation
float_t
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatType< Bits >::float_t = float_type<Bits>
Definition at line 522 of file types.h.
Payload_InlineSet
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatType< Bits >::Payload_InlineSet = detail::Payload_InlineSet<float_t> [private]
Definition at line 792 of file types.h.
Payload_OnlySpecial
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatType< Bits >::Payload_OnlySpecial = detail::Payload_Empty [private]
Definition at line 794 of file types.h.
Payload_OutlineSet
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatType< Bits >::Payload_OutlineSet = detail::Payload_OutlineSet<float_t> [private]
Definition at line 793 of file types.h.
Payload_Range
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatType< Bits >::Payload_Range = detail::Payload_Range<float_t> [private]
Definition at line 791 of file types.h.
value_type
template<size_t Bits>
using v8::internal::compiler::turboshaft::FloatType< Bits >::value_type = float_t
Definition at line 523 of file types.h.
Member Enumeration Documentation
Special
template<size_t Bits>
enum v8::internal::compiler::turboshaft::FloatType::Special : uint32_t
Enumerator
kNoSpecialValues
kNaN
kMinusZero
Definition at line 525 of file types.h.
               : uint32_t {
    kNoSpecialValues = 0x0,
    kNaN = 0x1,
    kMinusZero = 0x2,
  };
SubKind
template<size_t Bits>
enum v8::internal::compiler::turboshaft::FloatType::SubKind : uint8_t [strong], [private]
Enumerator
kRange
kSet
kOnlySpecialValues
Definition at line 514 of file types.h.
                     : uint8_t {
    kRange,
    kSet,
    kOnlySpecialValues,
  };
Constructor & Destructor Documentation
FloatType()
template<size_t Bits>
template<typename Payload >
v8::internal::compiler::turboshaft::FloatType< Bits >::FloatType (SubKind sub_kind, uint8_t set_size, uint32_t special_values, const Payload & payload) [inline], [private]
Definition at line 797 of file types.h.
      : Type(KIND, static_cast<uint8_t>(sub_kind), set_size, special_values, 0,
             payload) {
    DCHECK_EQ(special_values & ~(Special::kNaN | Special::kMinusZero), 0);
  }
References DCHECK_EQ.
Member Function Documentation
AllocateOnHeap()
template<size_t Bits>
Handle< TurboshaftType > v8::internal::compiler::turboshaft::FloatType< Bits >::AllocateOnHeap (Factory * factory) const
Definition at line 651 of file types.cc.
                                                                             {
  float_t min = 0.0f, max = 0.0f;
  constexpr uint32_t padding = 0;
  if (is_only_special_values()) {
    min = std::numeric_limits<float_t>::infinity();
    max = -std::numeric_limits<float_t>::infinity();
    return factory->NewTurboshaftFloat64RangeType(
        special_values(), padding, min, max, AllocationType::kYoung);
  } else if (is_range()) {
    std::tie(min, max) = minmax();
    return factory->NewTurboshaftFloat64RangeType(
        special_values(), padding, min, max, AllocationType::kYoung);
  } else {
    DCHECK(is_set());
    auto result = factory->NewTurboshaftFloat64SetType(
        special_values(), set_size(), AllocationType::kYoung);
    for (int i = 0; i < set_size(); ++i) {
      result->set_elements(i, set_element(i));
    }
    return result;
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kYoung, and v8::base::internal::result.
Any()
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Any (uint32_t special_values = Special::kNaN | Special::kMinusZero) [inline], [static]
Definition at line 545 of file types.h.
                                                                    {
    return FloatType::Range(-std::numeric_limits<float_t>::infinity(),
                            std::numeric_limits<float_t>::infinity(),
                            special_values, nullptr);
  }
References v8::internal::compiler::turboshaft::Range().
Constant()
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Constant (float_t constant) [inline], [static]
Definition at line 620 of file types.h.
                                              {
    return Set({constant}, 0, nullptr);
  }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::Typer::TypeConstant().
Contains()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::Contains (float_t value) const
Definition at line 466 of file types.cc.
                                                  {
  if (IsMinusZero(value)) return has_minus_zero();
  if (std::isnan(value)) return has_nan();
  switch (sub_kind()) {
    case SubKind::kOnlySpecialValues:
      return false;
    case SubKind::kRange: {
      return range_min() <= value && value <= range_max();
    }
    case SubKind::kSet: {
      for (int i = 0; i < set_size(); ++i) {
        if (set_element(i) == value) return true;
      }
      return false;
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsMinusZero(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
Equals()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::Equals (const FloatType< Bits > & other) const
Definition at line 485 of file types.cc.
                                                               {
  if (sub_kind() != other.sub_kind()) return false;
  if (special_values() != other.special_values()) return false;
  switch (sub_kind()) {
    case SubKind::kOnlySpecialValues:
      return true;
    case SubKind::kRange: {
      return range() == other.range();
    }
    case SubKind::kSet: {
      if (set_size() != other.set_size()) {
        return false;
      }
      for (int i = 0; i < set_size(); ++i) {
        if (set_element(i) != other.set_element(i)) return false;
      }
      return true;
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatType< Bits >::range(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_element(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_size(), v8::internal::compiler::turboshaft::FloatType< Bits >::special_values(), and v8::internal::compiler::turboshaft::FloatType< Bits >::sub_kind().
has_minus_zero()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::has_minus_zero () const [inline]
Definition at line 649 of file types.h.
                              {
    return (special_values() & Special::kMinusZero) != 0;
  }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
has_nan()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::has_nan () const [inline]
Definition at line 648 of file types.h.
{ return (special_values() & Special::kNaN) != 0; }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
has_special_values()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::has_special_values () const [inline]
Definition at line 647 of file types.h.
{ return special_values() != 0; }
IdentifyMinusZero()
template<size_t Bits>
static uint32_t v8::internal::compiler::turboshaft::FloatType< Bits >::IdentifyMinusZero (float_t & value) [inline], [static], [private]
Definition at line 771 of file types.h.
                                                    {
    if (V8_UNLIKELY(detail::is_minus_zero(value))) {
      value = float_t{0};
      return Special::kMinusZero;
    }
    return Special::kNoSpecialValues;
  }
References v8::internal::compiler::turboshaft::detail::is_minus_zero(), V8_UNLIKELY, and v8::internal::value.
Intersect()
template<size_t Bits>
Type v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect (const FloatType< Bits > & lhs, const FloatType< Bits > & rhs, Zone * zone) [static]
Definition at line 578 of file types.cc.
                                                                        {
  const uint32_t special_values = lhs.special_values() & rhs.special_values();
  if (lhs.is_any()) return ReplacedSpecialValues(rhs, special_values);
  if (rhs.is_any()) return ReplacedSpecialValues(lhs, special_values);
  if (lhs.is_only_special_values() || rhs.is_only_special_values()) {
    return special_values ? OnlySpecialValues(special_values) : Type::None();
  }
  if (lhs.is_set() || rhs.is_set()) {
    const auto& x = lhs.is_set() ? lhs : rhs;
    const auto& y = lhs.is_set() ? rhs : lhs;
    base::SmallVector<float_t, kMaxSetSize * 2> result_elements;
    for (int i = 0; i < x.set_size(); ++i) {
      const float_t element = x.set_element(i);
      if (y.Contains(element)) result_elements.push_back(element);
    }
    if (result_elements.empty()) {
      return special_values ? OnlySpecialValues(special_values) : Type::None();
    }
    return Set(result_elements, special_values, zone);
  }
  DCHECK(lhs.is_range() && rhs.is_range());
  const float_t result_min = std::max(lhs.min(), rhs.min());
  const float_t result_max = std::min(lhs.max(), rhs.max());
  if (result_min < result_max) {
    return Range(result_min, result_max, special_values, zone);
  } else if (result_min == result_max) {
    return Set({result_min}, special_values, zone);
  }
  return special_values ? OnlySpecialValues(special_values) : Type::None();
}
References v8::internal::DCHECK(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatType< Bits >::is_any(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_special_values(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_range(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::internal::compiler::turboshaft::FloatType< Bits >::max(), v8::internal::compiler::turboshaft::FloatType< Bits >::min(), v8::internal::compiler::turboshaft::Type::None(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::Range(), v8::internal::compiler::turboshaft::FloatType< Bits >::special_values(), and v8::internal::y.
Referenced by v8::internal::compiler::turboshaft::Typer::BranchRefinements::RefineTypes().
is_any()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_any () const [inline]
Definition at line 637 of file types.h.
                      {
    return is_range() &&
           range_min() == -std::numeric_limits<float_t>::infinity() &&
           range_max() == std::numeric_limits<float_t>::infinity();
  }
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), and v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound().
is_constant() [1/2]
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_constant () const [inline]
Definition at line 642 of file types.h.
                           {
    DCHECK_EQ(set_size_ > 0, is_set());
    return set_size_ == 1 && !has_special_values();
  }
References DCHECK_EQ.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power().
is_constant() [2/2]
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_constant (float_t value) const [inline]
Definition at line 723 of file types.h.
                                        {
    if (V8_UNLIKELY(std::isnan(value))) return is_only_nan();
    if (V8_UNLIKELY(IsMinusZero(value))) return is_only_minus_zero();
    if (auto c = try_get_constant()) return *c == value;
    return false;
  }
References v8::internal::IsMinusZero(), V8_UNLIKELY, and v8::internal::value.
is_only_minus_zero()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_minus_zero () const [inline]
Definition at line 631 of file types.h.
                                  {
    return is_only_special_values() &&
           (special_values() == Special::kMinusZero);
  }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power().
is_only_nan()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_nan () const [inline]
Definition at line 628 of file types.h.
                           {
    return is_only_special_values() && (special_values() == Special::kNaN);
  }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
is_only_special_values()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_special_values () const [inline]
Definition at line 625 of file types.h.
                                      {
    return sub_kind() == SubKind::kOnlySpecialValues;
  }
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), and v8::internal::compiler::turboshaft::FloatType< Bits >::ReplacedSpecialValues().
is_range()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_range () const [inline]
Definition at line 635 of file types.h.
{ return sub_kind() == SubKind::kRange; }
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), and v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf().
is_set()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::is_set () const [inline]
Definition at line 636 of file types.h.
{ return sub_kind() == SubKind::kSet; }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
IsSubtypeOf()
template<size_t Bits>
bool v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf (const FloatType< Bits > & other) const
Definition at line 507 of file types.cc.
                                                                    {
  if (special_values() & ~other.special_values()) return false;
  switch (sub_kind()) {
    case SubKind::kOnlySpecialValues:
      return true;
    case SubKind::kRange:
      if (!other.is_range()) {
        // This relies on the fact that we don't have singleton ranges.
        DCHECK_NE(range_min(), range_max());
        return false;
      }
      return other.range_min() <= range_min() &&
             range_max() <= other.range_max();
    case SubKind::kSet: {
      switch (other.sub_kind()) {
        case SubKind::kOnlySpecialValues:
          return false;
        case SubKind::kRange:
          return other.range_min() <= min() && max() <= other.range_max();
        case SubKind::kSet:
          for (int i = 0; i < set_size(); ++i) {
            if (!other.Contains(set_element(i))) return false;
          }
          return true;
      }
    }
  }
}
References v8::internal::compiler::turboshaft::FloatType< Bits >::Contains(), DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FloatType< Bits >::is_range(), v8::internal::compiler::turboshaft::FloatType< Bits >::range_max(), v8::internal::compiler::turboshaft::FloatType< Bits >::range_min(), v8::internal::compiler::turboshaft::FloatType< Bits >::special_values(), and v8::internal::compiler::turboshaft::FloatType< Bits >::sub_kind().
LeastUpperBound()
template<size_t Bits>
FloatType< Bits > v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound (const FloatType< Bits > & lhs, const FloatType< Bits > & rhs, Zone * zone) [static]
Definition at line 538 of file types.cc.
                                                             {
  uint32_t special_values = lhs.special_values() | rhs.special_values();
  if (lhs.is_any() || rhs.is_any()) {
    return Any(special_values);
  }
  const bool lhs_finite = lhs.is_set() || lhs.is_only_special_values();
  const bool rhs_finite = rhs.is_set() || rhs.is_only_special_values();
  if (lhs_finite && rhs_finite) {
    base::SmallVector<float_t, kMaxSetSize * 2> result_elements;
    if (lhs.is_set()) base::vector_append(result_elements, lhs.set_elements());
    if (rhs.is_set()) base::vector_append(result_elements, rhs.set_elements());
    if (result_elements.empty()) {
      return OnlySpecialValues(special_values);
    }
    base::sort(result_elements);
    auto it = std::unique(result_elements.begin(), result_elements.end());
    result_elements.pop_back(std::distance(it, result_elements.end()));
    if (result_elements.size() <= kMaxSetSize) {
      return Set(result_elements, special_values, zone);
    }
    return Range(result_elements.front(), result_elements.back(),
                 special_values, zone);
  } else if (lhs.is_only_special_values()) {
    return ReplacedSpecialValues(rhs, special_values).template AsFloat<Bits>();
  } else if (rhs.is_only_special_values()) {
    return ReplacedSpecialValues(lhs, special_values).template AsFloat<Bits>();
  }
  // We need to construct a range.
  float_t result_min = std::min(lhs.range_or_set_min(), rhs.range_or_set_min());
  float_t result_max = std::max(lhs.range_or_set_max(), rhs.range_or_set_max());
  return Range(result_min, result_max, special_values, zone);
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::front(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_any(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_special_values(), v8::internal::compiler::turboshaft::FloatType< Bits >::is_set(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), v8::internal::compiler::turboshaft::Range(), v8::internal::compiler::turboshaft::FloatType< Bits >::range_or_set_max(), v8::internal::compiler::turboshaft::FloatType< Bits >::range_or_set_min(), v8::internal::compiler::turboshaft::FloatType< Bits >::set_elements(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::base::sort(), v8::internal::compiler::turboshaft::FloatType< Bits >::special_values(), and v8::base::vector_append().
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
max()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::max () const [inline]
Definition at line 700 of file types.h.
                      {
    switch (sub_kind()) {
      case SubKind::kOnlySpecialValues:
        if (has_minus_zero()) return float_t{-0.0};
        DCHECK(is_only_nan());
        return nan_v<Bits>;
      case SubKind::kRange:
        if (has_minus_zero()) return std::max(float_t{-0.0}, range_max());
        return range_max();
      case SubKind::kSet:
        if (has_minus_zero()) {
          return std::max(float_t{-0.0}, set_element(set_size() - 1));
        }
        return set_element(set_size() - 1);
    }
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True().
min()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::min () const [inline]
Definition at line 686 of file types.h.
                      {
    switch (sub_kind()) {
      case SubKind::kOnlySpecialValues:
        if (has_minus_zero()) return float_t{-0.0};
        DCHECK(is_only_nan());
        return nan_v<Bits>;
      case SubKind::kRange:
        if (has_minus_zero()) return std::min(float_t{-0.0}, range_min());
        return range_min();
      case SubKind::kSet:
        if (has_minus_zero()) return std::min(float_t{-0.0}, set_element(0));
        return set_element(0);
    }
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThan(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::LessThanOrEqual(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True().
minmax()
template<size_t Bits>
std::pair<float_t, float_t> v8::internal::compiler::turboshaft::FloatType< Bits >::minmax () const [inline]
Definition at line 716 of file types.h.
{ return {min(), max()}; }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract().
MinusZero()
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::MinusZero () [inline], [static]
Definition at line 541 of file types.h.
                               {
    return FloatType{SubKind::kOnlySpecialValues, 0, Special::kMinusZero,
                     Payload_OnlySpecial{}};
  }
Referenced by v8::internal::compiler::turboshaft::Typer::TypeConstant().
NaN()
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::NaN () [inline], [static]
Definition at line 537 of file types.h.
                         {
    return FloatType{SubKind::kOnlySpecialValues, 0, Special::kNaN,
                     Payload_OnlySpecial{}};
  }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Divide(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Max(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Min(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Modulus(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Multiply(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Subtract(), and v8::internal::compiler::turboshaft::Typer::TypeConstant().
OnlySpecialValues()
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::OnlySpecialValues (uint32_t special_values) [inline], [static]
Definition at line 532 of file types.h.
                                                              {
    DCHECK_NE(0, special_values);
    return FloatType{SubKind::kOnlySpecialValues, 0, special_values,
                     Payload_OnlySpecial{}};
  }
References DCHECK_NE.
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Add(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set().
PrintTo()
template<size_t Bits>
void v8::internal::compiler::turboshaft::FloatType< Bits >::PrintTo (std::ostream & stream) const
Definition at line 613 of file types.cc.
                                                      {
  auto PrintSpecials = [this](auto& stream) {
    if (has_nan()) {
      stream << "NaN" << (has_minus_zero() ? "|MinusZero" : "");
    } else {
      DCHECK(has_minus_zero());
      stream << "MinusZero";
    }
  };
  stream << (Bits == 32 ? "Float32" : "Float64");
  switch (sub_kind()) {
    case SubKind::kOnlySpecialValues:
      PrintSpecials(stream);
      break;
    case SubKind::kRange:
      stream << "[" << range_min() << ", " << range_max() << "]";
      if (has_special_values()) {
        stream << "|";
        PrintSpecials(stream);
      }
      break;
    case SubKind::kSet:
      stream << "{";
      for (int i = 0; i < set_size(); ++i) {
        if (i != 0) stream << ", ";
        stream << set_element(i);
      }
      if (has_special_values()) {
        stream << "}|";
        PrintSpecials(stream);
      } else {
        stream << "}";
      }
      break;
  }
}
References v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
range()
template<size_t Bits>
std::pair<float_t, float_t> v8::internal::compiler::turboshaft::FloatType< Bits >::range () const [inline]
Definition at line 662 of file types.h.
                                          {
    DCHECK(is_range());
    return {range_min(), range_max()};
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Equals().
Range() [1/2]
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Range (float_t min, float_t max, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 554 of file types.h.
                                     {
    special_values |= IdentifyMinusZero(min);
    special_values |= IdentifyMinusZero(max);
    DCHECK(!detail::is_float_special_value(min));
    DCHECK(!detail::is_float_special_value(max));
    DCHECK_LE(min, max);
    if (min == max) return Set({min}, special_values, zone);
    return FloatType{SubKind::kRange, 0, special_values,
                     Payload_Range{min, max}};
  }
References DCHECK, DCHECK_LE, and v8::internal::compiler::turboshaft::detail::is_float_special_value().
Range() [2/2]
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Range (float_t min, float_t max, Zone * zone) [inline], [static]
Definition at line 551 of file types.h.
                                                               {
    return Range(min, max, Special::kNoSpecialValues, zone);
  }
References v8::internal::compiler::turboshaft::Range().
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Range(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_False(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThan_True(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_False(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::RestrictionForLessThanOrEqual_True().
range_max()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::range_max () const [inline]
Definition at line 658 of file types.h.
                            {
    DCHECK(is_range());
    return get_payload<Payload_Range>().max;
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf().
range_min()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::range_min () const [inline]
Definition at line 654 of file types.h.
                            {
    DCHECK(is_range());
    return get_payload<Payload_Range>().min;
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf().
range_or_set_max()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::range_or_set_max () const [inline]
Definition at line 743 of file types.h.
                                   {
    switch (sub_kind()) {
      case SubKind::kOnlySpecialValues:
        UNREACHABLE();
      case SubKind::kRange:
        return range_max();
      case SubKind::kSet:
        return set_element(set_size() - 1);
    }
  }
References UNREACHABLE.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound().
range_or_set_min()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::range_or_set_min () const [inline]
Definition at line 731 of file types.h.
                                   {
    switch (sub_kind()) {
      case SubKind::kOnlySpecialValues:
        UNREACHABLE();
      case SubKind::kRange:
        return range_min();
      case SubKind::kSet:
        return set_element(0);
    }
  }
References UNREACHABLE.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound().
range_or_set_minmax()
template<size_t Bits>
std::pair<float_t, float_t> v8::internal::compiler::turboshaft::FloatType< Bits >::range_or_set_minmax () const [inline]
Definition at line 753 of file types.h.
                                                        {
    return {range_or_set_min(), range_or_set_max()};
  }
ReplacedSpecialValues()
template<size_t Bits>
static Type v8::internal::compiler::turboshaft::FloatType< Bits >::ReplacedSpecialValues (const FloatType< Bits > & t, uint32_t special_values) [inline], [static], [private]
Definition at line 778 of file types.h.
                                                             {
    if (special_values == 0 && t.is_only_special_values()) {
      return FloatType::None();
    }
    auto result = t;
    result.bitfield_ = special_values;
    DCHECK_EQ(result.bitfield_, result.special_values());
    return result;
  }
References DCHECK_EQ, v8::internal::compiler::turboshaft::FloatType< Bits >::is_only_special_values(), v8::None, and v8::base::internal::result.
Set() [1/6]
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Set (base::Vector< const float_t > elements, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 586 of file types.h.
                                                            {
    DCHECK(detail::is_unique_and_sorted(elements));
    // NaN should be passed via {special_values} rather than {elements}.
    DCHECK(base::none_of(elements, [](float_t f) { return std::isnan(f); }));
    DCHECK_IMPLIES(elements.size() > kMaxInlineSetSize, zone != nullptr);
    DCHECK_GT(elements.size(), 0);
    DCHECK_LE(elements.size(), kMaxSetSize);
    if (elements.size() <= kMaxInlineSetSize) {
      // Use inline storage.
      Payload_InlineSet p;
      DCHECK_LT(0, elements.size());
      p.elements[0] = elements[0];
      special_values |= IdentifyMinusZero(p.elements[0]);
      if (elements.size() > 1) {
        p.elements[1] = elements[1];
        special_values |= IdentifyMinusZero(p.elements[1]);
      }
      return FloatType{SubKind::kSet, static_cast<uint8_t>(elements.size()),
                       special_values, p};
    } else {
      // Allocate storage in the zone.
      Payload_OutlineSet p;
      p.array = zone->AllocateArray<float_t>(elements.size());
      DCHECK_NOT_NULL(p.array);
      for (size_t i = 0; i < elements.size(); ++i) {
        p.array[i] = elements[i];
        special_values |= IdentifyMinusZero(p.array[i]);
      }
      return FloatType{SubKind::kSet, static_cast<uint8_t>(elements.size()),
                       special_values, p};
    }
  }
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::turboshaft::detail::Payload_OutlineSet< T >::array, DCHECK, DCHECK_GT, DCHECK_IMPLIES, DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::detail::Payload_InlineSet< T >::elements, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::is_unique_and_sorted(), v8::base::none_of(), and v8::base::Vector< T >::size().
Set() [2/6]
template<size_t Bits>
template<size_t N>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Set (const base::SmallVector< const float_t, N > & elements, Zone * zone) [inline], [static]
Definition at line 566 of file types.h.
                                   {
    return Set(elements, Special::kNoSpecialValues, zone);
  }
Referenced by v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Power(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::Set().
Set() [3/6]
template<size_t Bits>
template<size_t N>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Set (const base::SmallVector< float_t, N > & elements, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 571 of file types.h.
                                                            {
    return Set(base::VectorOf(elements), special_values, zone);
  }
References v8::base::VectorOf().
Set() [4/6]
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Set (const std::initializer_list< float_t > & elements, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 575 of file types.h.
                                                            {
    return Set(base::VectorOf(elements), special_values, zone);
  }
References v8::base::VectorOf().
Set() [5/6]
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Set (const std::vector< float_t > & elements, uint32_t special_values, Zone * zone) [inline], [static]
Definition at line 582 of file types.h.
                                                            {
    return Set(base::VectorOf(elements), special_values, zone);
  }
References v8::base::VectorOf().
Set() [6/6]
template<size_t Bits>
static FloatType v8::internal::compiler::turboshaft::FloatType< Bits >::Set (const std::vector< float_t > & elements, Zone * zone) [inline], [static]
Definition at line 579 of file types.h.
                                                                       {
    return Set(elements, Special::kNoSpecialValues, zone);
  }
set_element()
template<size_t Bits>
float_t v8::internal::compiler::turboshaft::FloatType< Bits >::set_element (int index) const [inline]
Definition at line 670 of file types.h.
                                       {
    DCHECK(is_set());
    DCHECK_GE(index, 0);
    DCHECK_LT(index, set_size());
    return set_elements()[index];
  }
References DCHECK, DCHECK_GE, DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Equals(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet().
set_elements()
template<size_t Bits>
base::Vector<const float_t> v8::internal::compiler::turboshaft::FloatType< Bits >::set_elements () const [inline]
Definition at line 676 of file types.h.
                                                 {
    DCHECK(is_set());
    if (set_size() <= kMaxInlineSetSize) {
      return base::Vector<const float_t>(
          get_payload<Payload_InlineSet>().elements, set_size());
    } else {
      return base::Vector<const float_t>(
          get_payload<Payload_OutlineSet>().array, set_size());
    }
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound().
set_size()
template<size_t Bits>
int v8::internal::compiler::turboshaft::FloatType< Bits >::set_size () const [inline]
Definition at line 666 of file types.h.
                       {
    DCHECK(is_set());
    return static_cast<int>(set_size_);
  }
References DCHECK.
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Equals(), v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::IsIntegerSet(), and v8::internal::compiler::turboshaft::FloatOperationTyper< Bits >::ProductSet().
special_values()
template<size_t Bits>
uint32_t v8::internal::compiler::turboshaft::FloatType< Bits >::special_values () const [inline]
Definition at line 646 of file types.h.
{ return bitfield_; }
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Equals(), v8::internal::compiler::turboshaft::FloatType< Bits >::Intersect(), v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf(), and v8::internal::compiler::turboshaft::FloatType< Bits >::LeastUpperBound().
sub_kind()
template<size_t Bits>
SubKind v8::internal::compiler::turboshaft::FloatType< Bits >::sub_kind () const [inline], [private]
Definition at line 790 of file types.h.
{ return static_cast<SubKind>(sub_kind_); }
Referenced by v8::internal::compiler::turboshaft::FloatType< Bits >::Equals(), and v8::internal::compiler::turboshaft::FloatType< Bits >::IsSubtypeOf().
try_get_constant()
template<size_t Bits>
std::optional<float_t> v8::internal::compiler::turboshaft::FloatType< Bits >::try_get_constant () const [inline]
Definition at line 717 of file types.h.
                                                {
    if (!is_constant()) return std::nullopt;
    DCHECK(is_set());
    DCHECK_EQ(set_size(), 1);
    return set_element(0);
  }
References DCHECK, and DCHECK_EQ.
Friends And Related Function Documentation
Type
template<size_t Bits>
friend class Type [friend]
Definition at line 511 of file types.h.
Member Data Documentation
KIND
template<size_t Bits>
constexpr Kind v8::internal::compiler::turboshaft::FloatType< Bits >::KIND = Bits == 32 ? Kind::kFloat32 : Kind::kFloat64 [static], [constexpr], [private]
Definition at line 789 of file types.h.
kMaxInlineSetSize
template<size_t Bits>
constexpr int v8::internal::compiler::turboshaft::FloatType< Bits >::kMaxInlineSetSize = 2 [static], [constexpr], [private]
Definition at line 512 of file types.h.
kMaxSetSize
template<size_t Bits>
constexpr int v8::internal::compiler::turboshaft::FloatType< Bits >::kMaxSetSize = 8 [static], [constexpr]
Definition at line 521 of file types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/types.h
/mnt/V8SourceCode/src/compiler/turboshaft/types.cc