v8::internal::compiler::ResumeJumpTarget Class Reference
#include <bytecode-analysis.h>
Public Member Functions
int suspend_id () const
int target_offset () const
bool is_leaf () const
Static Public Member Functions
static ResumeJumpTarget Leaf (int suspend_id, int target_offset)
static ResumeJumpTarget AtLoopHeader (int loop_header_offset, const ResumeJumpTarget &next)
Private Member Functions
ResumeJumpTarget (int suspend_id, int target_offset, int final_target_offset)
Private Attributes
int suspend_id_
int target_offset_
int final_target_offset_
Detailed Description
Definition at line 44 of file bytecode-analysis.h.
Constructor & Destructor Documentation
ResumeJumpTarget()
v8::internal::compiler::ResumeJumpTarget::ResumeJumpTarget (int suspend_id, int target_offset, int final_target_offset) [private]
Definition at line 72 of file bytecode-analysis.cc.
    : suspend_id_(suspend_id),
      target_offset_(target_offset),
      final_target_offset_(final_target_offset) {}
Referenced by AtLoopHeader(), and Leaf().
Member Function Documentation
AtLoopHeader()
ResumeJumpTarget v8::internal::compiler::ResumeJumpTarget::AtLoopHeader (int loop_header_offset, const ResumeJumpTarget & next) [static]
Definition at line 82 of file bytecode-analysis.cc.
                                                                              {
  return ResumeJumpTarget(next.suspend_id(), loop_header_offset,
                          next.target_offset());
}
References ResumeJumpTarget(), suspend_id(), and target_offset().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
is_leaf()
bool v8::internal::compiler::ResumeJumpTarget::is_leaf () const [inline]
Definition at line 56 of file bytecode-analysis.h.
{ return target_offset_ == final_target_offset_; }
Leaf()
ResumeJumpTarget v8::internal::compiler::ResumeJumpTarget::Leaf (int suspend_id, int target_offset) [static]
Definition at line 78 of file bytecode-analysis.cc.
                                                                         {
  return ResumeJumpTarget(suspend_id, target_offset, target_offset);
}
References ResumeJumpTarget(), suspend_id(), and target_offset().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), and v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::AnalyzeBCInLoop< Bytecode::kSuspendGenerator >().
suspend_id()
int v8::internal::compiler::ResumeJumpTarget::suspend_id () const [inline]
Definition at line 54 of file bytecode-analysis.h.
{ return suspend_id_; }
Referenced by AtLoopHeader(), and Leaf().
target_offset()
int v8::internal::compiler::ResumeJumpTarget::target_offset () const [inline]
Definition at line 55 of file bytecode-analysis.h.
{ return target_offset_; }
Referenced by AtLoopHeader(), and Leaf().
Member Data Documentation
final_target_offset_
int v8::internal::compiler::ResumeJumpTarget::final_target_offset_ [private]
Definition at line 64 of file bytecode-analysis.h.
suspend_id_
int v8::internal::compiler::ResumeJumpTarget::suspend_id_ [private]
Definition at line 60 of file bytecode-analysis.h.
target_offset_
int v8::internal::compiler::ResumeJumpTarget::target_offset_ [private]
Definition at line 62 of file bytecode-analysis.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/bytecode-analysis.h
/mnt/V8SourceCode/src/compiler/bytecode-analysis.cc