v8::internal::RegExpImpl Class Reference
Static Public Member Functions
static DirectHandle< String > ToString (DirectHandle< Object > value)
static void IrregexpInitialize (Isolate *isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, int capture_count, uint32_t backtrack_limit)
static int IrregexpPrepare (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject)
static void AtomCompile (Isolate *isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, DirectHandle< String > match_pattern)
static int AtomExecRaw (Isolate *isolate, DirectHandle< AtomRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, int result_offsets_vector_length)
static int AtomExecRaw (Isolate *isolate, const String::FlatContent &pattern, const String::FlatContent &subject, int index, RegExpFlags flags, int32_t *result_offsets_vector, int result_offsets_vector_length, const DisallowGarbageCollection &no_gc)
static int AtomExec (Isolate *isolate, DirectHandle< AtomRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, int result_offsets_vector_length)
static int IrregexpExecRaw (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t *output, int output_size)
static V8_WARN_UNUSED_RESULT std::optional< int > IrregexpExec (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
static bool CompileIrregexp (Isolate *isolate, DirectHandle< IrRegExpData > re_data, DirectHandle< String > sample_subject, bool is_one_byte)
static bool EnsureCompiledIrregexp (Isolate *isolate, DirectHandle< IrRegExpData > re_data, DirectHandle< String > sample_subject, bool is_one_byte)
static bool Compile (Isolate *isolate, Zone *zone, RegExpCompileData *input, RegExpFlags flags, DirectHandle< String > pattern, DirectHandle< String > sample_subject, bool is_one_byte, uint32_t &backtrack_limit)
Detailed Description
Definition at line 32 of file regexp.cc.
Member Function Documentation
AtomCompile()
void v8::internal::RegExpImpl::AtomCompile (Isolate * isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, DirectHandle< String > match_pattern) [static]
Definition at line 386 of file regexp.cc.
                                                                 {
  isolate->factory()->SetRegExpAtomData(
      re, pattern, JSRegExp::AsJSRegExpFlags(flags), match_pattern);
}
References v8::internal::JSRegExp::AsJSRegExpFlags(), v8::internal::Isolate::factory(), v8::internal::flags, and v8::internal::Factory::SetRegExpAtomData().
Referenced by v8::internal::RegExp::Compile().
AtomExec()
int v8::internal::RegExpImpl::AtomExec (Isolate * isolate, DirectHandle< AtomRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, int result_offsets_vector_length) [static]
Definition at line 512 of file regexp.cc.
                                                           {
  int res = AtomExecRaw(isolate, re_data, subject, index, result_offsets_vector,
                        result_offsets_vector_length);
  DCHECK(res == RegExp::RE_FAILURE || res == RegExp::RE_SUCCESS);
  return res;
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::RegExp::RE_FAILURE, and v8::internal::RegExp::RE_SUCCESS.
Referenced by v8::internal::RegExp::Exec().
AtomExecRaw() [1/2]
int v8::internal::RegExpImpl::AtomExecRaw (Isolate * isolate, const String::FlatContent & pattern, const String::FlatContent & subject, int index, RegExpFlags flags, int32_t * result_offsets_vector, int result_offsets_vector_length, const DisallowGarbageCollection & no_gc) [static]
Definition at line 458 of file regexp.cc.
                                                                    {
  DCHECK_GE(index, 0);
  DCHECK_LE(index, subject.length());
  CHECK_EQ(result_offsets_vector_length % JSRegExp::kAtomRegisterCount, 0);
  DCHECK(pattern.IsFlat());
  DCHECK(subject.IsFlat());
  return pattern.IsOneByte()
             ? (subject.IsOneByte()
                    ? AtomExecRawImpl(isolate, subject.ToOneByteVector(),
                                      pattern.ToOneByteVector(), index, flags,
                                      result_offsets_vector,
                                      result_offsets_vector_length, no_gc)
                    : AtomExecRawImpl(isolate, subject.ToUC16Vector(),
                                      pattern.ToOneByteVector(), index, flags,
                                      result_offsets_vector,
                                      result_offsets_vector_length, no_gc))
             : (subject.IsOneByte()
                    ? AtomExecRawImpl(isolate, subject.ToOneByteVector(),
                                      pattern.ToUC16Vector(), index, flags,
                                      result_offsets_vector,
                                      result_offsets_vector_length, no_gc)
                    : AtomExecRawImpl(isolate, subject.ToUC16Vector(),
                                      pattern.ToUC16Vector(), index, flags,
                                      result_offsets_vector,
                                      result_offsets_vector_length, no_gc));
}
References v8::internal::anonymous_namespace{regexp.cc}::AtomExecRawImpl(), CHECK_EQ, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::flags, v8::internal::index, v8::internal::String::FlatContent::IsFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::JSRegExp::kAtomRegisterCount, v8::internal::String::FlatContent::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
AtomExecRaw() [2/2]
int v8::internal::RegExpImpl::AtomExecRaw (Isolate * isolate, DirectHandle< AtomRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, int result_offsets_vector_length) [static]
Definition at line 440 of file regexp.cc.
                                                              {
  subject = String::Flatten(isolate, subject);
  DisallowGarbageCollection no_gc;
  Tagged<String> needle = regexp_data->pattern(isolate);
  RegExpFlags flags = JSRegExp::AsRegExpFlags(regexp_data->flags());
  String::FlatContent needle_content = needle->GetFlatContent(no_gc);
  String::FlatContent subject_content = subject->GetFlatContent(no_gc);
  return AtomExecRaw(isolate, needle_content, subject_content, index, flags,
                     result_offsets_vector, result_offsets_vector_length,
                     no_gc);
}
References v8::internal::JSRegExp::AsRegExpFlags(), v8::internal::flags, v8::internal::index, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::RegExp::AtomExecRaw(), and v8::internal::RegExpGlobalExecRunner::FetchNext().
Compile()
bool v8::internal::RegExpImpl::Compile (Isolate * isolate, Zone * zone, RegExpCompileData * input, RegExpFlags flags, DirectHandle< String > pattern, DirectHandle< String > sample_subject, bool is_one_byte, uint32_t & backtrack_limit) [static]
Definition at line 962 of file regexp.cc.
                                                    {
  if (JSRegExp::RegistersForCaptureCount(data->capture_count) >
      RegExpMacroAssembler::kMaxRegisterCount) {
    data->error = RegExpError::kTooLarge;
    return false;
  }
  RegExpCompiler compiler(isolate, zone, data->capture_count, flags,
                          is_one_byte);
  if (compiler.optimize()) {
    compiler.set_optimize(!TooMuchRegExpCode(isolate, pattern));
  }
  // Sample some characters from the middle of the string.
  static const int kSampleSize = 128;
  sample_subject = String::Flatten(isolate, sample_subject);
  uint32_t start, end;
  if (sample_subject->length() > kSampleSize) {
    start = (sample_subject->length() - kSampleSize) / 2;
    end = start + kSampleSize;
  } else {
    start = 0;
    end = sample_subject->length();
  }
  for (uint32_t i = start; i < end; i++) {
    compiler.frequency_collator()->CountCharacter(sample_subject->Get(i));
  }
  data->node = compiler.PreprocessRegExp(data, is_one_byte);
  if (data->error != RegExpError::kNone) {
    return false;
  }
  data->error = AnalyzeRegExp(isolate, is_one_byte, flags, data->node);
  if (data->error != RegExpError::kNone) {
    return false;
  }
  if (v8_flags.trace_regexp_graph) DotPrinter::DotPrint("Start", data->node);
  // Create the correct assembler for the architecture.
  std::unique_ptr<RegExpMacroAssembler> macro_assembler;
  if (data->compilation_target == RegExpCompilationTarget::kNative) {
    // Native regexp implementation.
    DCHECK(!v8_flags.jitless);
    NativeRegExpMacroAssembler::Mode mode =
        is_one_byte ? NativeRegExpMacroAssembler::LATIN1
                    : NativeRegExpMacroAssembler::UC16;
    const int output_register_count =
        JSRegExp::RegistersForCaptureCount(data->capture_count);
#if V8_TARGET_ARCH_IA32
    macro_assembler.reset(new RegExpMacroAssemblerIA32(isolate, zone, mode,
                                                       output_register_count));
#elif V8_TARGET_ARCH_X64
    macro_assembler.reset(new RegExpMacroAssemblerX64(isolate, zone, mode,
                                                      output_register_count));
#elif V8_TARGET_ARCH_ARM
    macro_assembler.reset(new RegExpMacroAssemblerARM(isolate, zone, mode,
                                                      output_register_count));
#elif V8_TARGET_ARCH_ARM64
    macro_assembler.reset(new RegExpMacroAssemblerARM64(isolate, zone, mode,
                                                        output_register_count));
#elif V8_TARGET_ARCH_S390X
    macro_assembler.reset(new RegExpMacroAssemblerS390(isolate, zone, mode,
                                                       output_register_count));
#elif V8_TARGET_ARCH_PPC64
    macro_assembler.reset(new RegExpMacroAssemblerPPC(isolate, zone, mode,
                                                      output_register_count));
#elif V8_TARGET_ARCH_MIPS64
    macro_assembler.reset(new RegExpMacroAssemblerMIPS(isolate, zone, mode,
                                                       output_register_count));
#elif V8_TARGET_ARCH_RISCV64
    macro_assembler.reset(new RegExpMacroAssemblerRISCV(isolate, zone, mode,
                                                        output_register_count));
#elif V8_TARGET_ARCH_RISCV32
    macro_assembler.reset(new RegExpMacroAssemblerRISCV(isolate, zone, mode,
                                                        output_register_count));
#elif V8_TARGET_ARCH_LOONG64
    macro_assembler.reset(new RegExpMacroAssemblerLOONG64(
        isolate, zone, mode, output_register_count));
#else
#error "Unsupported architecture"
#endif
  } else {
    DCHECK_EQ(data->compilation_target, RegExpCompilationTarget::kBytecode);
    // Interpreted regexp implementation.
    macro_assembler.reset(new RegExpBytecodeGenerator(isolate, zone));
  }
  macro_assembler->set_slow_safe(TooMuchRegExpCode(isolate, pattern));
  if (v8_flags.enable_experimental_regexp_engine_on_excessive_backtracks &&
      ExperimentalRegExp::CanBeHandled(data->tree, pattern, flags,
                                       data->capture_count)) {
    if (backtrack_limit == JSRegExp::kNoBacktrackLimit) {
      backtrack_limit = v8_flags.regexp_backtracks_before_fallback;
    } else {
      backtrack_limit = std::min(
          backtrack_limit, v8_flags.regexp_backtracks_before_fallback.value());
    }
    macro_assembler->set_backtrack_limit(backtrack_limit);
    macro_assembler->set_can_fallback(true);
  } else {
    macro_assembler->set_backtrack_limit(backtrack_limit);
    macro_assembler->set_can_fallback(false);
  }
  // Inserted here, instead of in Assembler, because it depends on information
  // in the AST that isn't replicated in the Node structure.
  bool is_end_anchored = data->tree->IsAnchoredAtEnd();
  bool is_start_anchored = data->tree->IsAnchoredAtStart();
  int max_length = data->tree->max_match();
  static const int kMaxBacksearchLimit = 1024;
  if (is_end_anchored && !is_start_anchored && !IsSticky(flags) &&
      max_length < kMaxBacksearchLimit) {
    macro_assembler->SetCurrentPositionFromEnd(max_length);
  }
  if (IsGlobal(flags)) {
    RegExpMacroAssembler::GlobalMode mode = RegExpMacroAssembler::GLOBAL;
    if (data->tree->min_match() > 0) {
      mode = RegExpMacroAssembler::GLOBAL_NO_ZERO_LENGTH_CHECK;
    } else if (IsEitherUnicode(flags)) {
      mode = RegExpMacroAssembler::GLOBAL_UNICODE;
    }
    macro_assembler->set_global_mode(mode);
  }
  RegExpMacroAssembler* macro_assembler_ptr = macro_assembler.get();
#ifdef DEBUG
  std::unique_ptr<RegExpMacroAssembler> tracer_macro_assembler;
  if (v8_flags.trace_regexp_assembler) {
    tracer_macro_assembler.reset(
        new RegExpMacroAssemblerTracer(isolate, macro_assembler_ptr));
    macro_assembler_ptr = tracer_macro_assembler.get();
  }
#endif
  RegExpCompiler::CompilationResult result = compiler.Assemble(
      isolate, macro_assembler_ptr, data->node, data->capture_count, pattern);
  // Code / bytecode printing.
  {
#ifdef ENABLE_DISASSEMBLER
    if (v8_flags.print_regexp_code &&
        data->compilation_target == RegExpCompilationTarget::kNative) {
      CodeTracer::Scope trace_scope(isolate->GetCodeTracer());
      OFStream os(trace_scope.file());
      auto code = Cast<Code>(result.code);
      std::unique_ptr<char[]> pattern_cstring = pattern->ToCString();
      code->Disassemble(pattern_cstring.get(), os, isolate);
    }
#endif
    if (v8_flags.print_regexp_bytecode &&
        data->compilation_target == RegExpCompilationTarget::kBytecode) {
      auto bytecode = Cast<TrustedByteArray>(result.code);
      std::unique_ptr<char[]> pattern_cstring = pattern->ToCString();
      RegExpBytecodeDisassemble(bytecode->begin(), bytecode->length(),
                                pattern_cstring.get());
    }
  }
  if (result.error != RegExpError::kNone) {
    if (v8_flags.correctness_fuzzer_suppressions &&
        result.error == RegExpError::kStackOverflow) {
      FATAL("Aborting on stack overflow");
    }
    data->error = result.error;
  }
  data->code = result.code;
  data->register_count = result.num_registers;
  return result.Succeeded();
}
References v8::internal::AnalyzeRegExp(), v8::internal::RegExpCompiler::Assemble(), v8::internal::ExperimentalRegExp::CanBeHandled(), v8::internal::RegExpCompileData::capture_count, code, v8::internal::RegExpCompileData::code, v8::internal::RegExpCompileData::compilation_target, v8::internal::FrequencyCollator::CountCharacter(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DotPrinter::DotPrint(), v8::internal::compiler::end(), v8::internal::RegExpCompileData::error, FATAL, v8::internal::CodeTracer::Scope::file(), v8::internal::flags, v8::internal::RegExpCompiler::frequency_collator(), v8::internal::Isolate::GetCodeTracer(), v8::internal::RegExpMacroAssembler::GLOBAL, v8::internal::RegExpMacroAssembler::GLOBAL_NO_ZERO_LENGTH_CHECK, v8::internal::RegExpMacroAssembler::GLOBAL_UNICODE, v8::internal::RegExpTree::IsAnchoredAtEnd(), v8::internal::RegExpTree::IsAnchoredAtStart(), v8::internal::IsEitherUnicode(), v8::internal::kBytecode, v8::internal::RegExpMacroAssembler::kMaxRegisterCount, v8::internal::kNative, v8::internal::JSRegExp::kNoBacktrackLimit, v8::internal::NativeRegExpMacroAssembler::LATIN1, v8::internal::RegExpTree::max_match(), v8::internal::RegExpTree::min_match(), mode(), v8::internal::RegExpCompileData::node, v8::internal::RegExpCompiler::optimize(), v8::internal::RegExpCompiler::PreprocessRegExp(), v8::internal::RegExpBytecodeDisassemble(), v8::internal::RegExpCompileData::register_count, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::base::internal::result, v8::internal::RegExpCompiler::set_optimize(), v8::internal::anonymous_namespace{regexp.cc}::TooMuchRegExpCode(), v8::internal::RegExpCompileData::tree, v8::internal::NativeRegExpMacroAssembler::UC16, and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::CompileForTesting().
CompileIrregexp()
bool v8::internal::RegExpImpl::CompileIrregexp (Isolate * isolate, DirectHandle< IrRegExpData > re_data, DirectHandle< String > sample_subject, bool is_one_byte) [static]
Definition at line 621 of file regexp.cc.
                                                   {
  // Since we can't abort gracefully during compilation, check for sufficient
  // stack space (including the additional gap as used for Turbofan
  // compilation) here in advance.
  StackLimitCheck check(isolate);
  if (check.JsHasOverflowed(kStackSpaceRequiredForCompilation * KB)) {
    if (v8_flags.correctness_fuzzer_suppressions) {
      FATAL("Aborting on stack overflow");
    }
    RegExp::ThrowRegExpException(isolate, re_data,
                                 RegExpError::kAnalysisStackOverflow);
    return false;
  }
  // Compile the RegExp.
  Zone zone(isolate->allocator(), ZONE_NAME);
  PostponeInterruptsScope postpone(isolate);
  DCHECK(RegExpCodeIsValidForPreCompilation(isolate, re_data, is_one_byte));
  RegExpFlags flags = JSRegExp::AsRegExpFlags(re_data->flags());
  DirectHandle<String> pattern(re_data->source(), isolate);
  pattern = String::Flatten(isolate, pattern);
  RegExpCompileData compile_data;
  if (!RegExpParser::ParseRegExpFromHeapString(isolate, &zone, pattern, flags,
                                               &compile_data)) {
    // Throw an exception if we fail to parse the pattern.
    // THIS SHOULD NOT HAPPEN. We already pre-parsed it successfully once.
    USE(RegExp::ThrowRegExpException(isolate, flags, pattern,
                                     compile_data.error));
    return false;
  }
  // The compilation target is a kBytecode if we're interpreting all regexp
  // objects, or if we're using the tier-up strategy but the tier-up hasn't
  // happened yet. The compilation target is a kNative if we're using the
  // tier-up strategy and we need to recompile to tier-up, or if we're producing
  // native code for all regexp objects.
  compile_data.compilation_target = re_data->ShouldProduceBytecode()
                                        ? RegExpCompilationTarget::kBytecode
                                        : RegExpCompilationTarget::kNative;
  uint32_t backtrack_limit = re_data->backtrack_limit();
  const bool compilation_succeeded =
      Compile(isolate, &zone, &compile_data, flags, pattern, sample_subject,
              is_one_byte, backtrack_limit);
  if (!compilation_succeeded) {
    DCHECK(compile_data.error != RegExpError::kNone);
    RegExp::ThrowRegExpException(isolate, re_data, compile_data.error);
    return false;
  }
  if (compile_data.compilation_target == RegExpCompilationTarget::kNative) {
    re_data->set_code(is_one_byte, Cast<Code>(*compile_data.code));
    // Reset bytecode to uninitialized. In case we use tier-up we know that
    // tier-up has happened this way.
    re_data->clear_bytecode(is_one_byte);
  } else {
    DCHECK_EQ(compile_data.compilation_target,
              RegExpCompilationTarget::kBytecode);
    // Store code generated by compiler in bytecode and trampoline to
    // interpreter in code.
    re_data->set_bytecode(is_one_byte,
                          Cast<TrustedByteArray>(*compile_data.code));
    DirectHandle<Code> trampoline =
        BUILTIN_CODE(isolate, RegExpInterpreterTrampoline);
    re_data->set_code(is_one_byte, *trampoline);
  }
  DirectHandle<FixedArray> capture_name_map =
      RegExp::CreateCaptureNameMap(isolate, compile_data.named_captures);
  re_data->set_capture_name_map(capture_name_map);
  int register_max = re_data->max_register_count();
  if (compile_data.register_count > register_max) {
    re_data->set_max_register_count(compile_data.register_count);
  }
  re_data->set_backtrack_limit(backtrack_limit);
  if (v8_flags.trace_regexp_tier_up) {
    PrintF("JSRegExp data object %p %s size: %d\n",
           reinterpret_cast<void*>(re_data->ptr()),
           re_data->ShouldProduceBytecode() ? "bytecode" : "native code",
           re_data->ShouldProduceBytecode()
               ? re_data->bytecode(is_one_byte)->AllocatedSize()
               : re_data->code(isolate, is_one_byte)->Size());
  }
  return true;
}
References v8::internal::Isolate::allocator(), v8::internal::JSRegExp::AsRegExpFlags(), BUILTIN_CODE, v8::internal::RegExpCompileData::code, v8::internal::RegExpCompileData::compilation_target, v8::anonymous_namespace{d8.cc}::Compile(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpCompileData::error, FATAL, v8::internal::flags, v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::KB, v8::internal::kBytecode, v8::internal::kNative, v8::internal::kStackSpaceRequiredForCompilation, v8::internal::RegExpCompileData::named_captures, v8::internal::RegExpParser::ParseRegExpFromHeapString(), v8::internal::PrintF(), v8::internal::RegExpCompileData::register_count, v8::internal::RegExp::ThrowRegExpException(), USE, v8::internal::v8_flags, and ZONE_NAME.
EnsureCompiledIrregexp()
bool v8::internal::RegExpImpl::EnsureCompiledIrregexp (Isolate * isolate, DirectHandle< IrRegExpData > re_data, DirectHandle< String > sample_subject, bool is_one_byte) [inline], [static]
Definition at line 531 of file regexp.cc.
                                                          {
  bool has_bytecode = re_data->has_bytecode(is_one_byte);
  bool needs_initial_compilation = !re_data->has_code(is_one_byte);
  // Recompile is needed when we're dealing with the first execution of the
  // regexp after the decision to tier up has been made. If the tiering up
  // strategy is not in use, this value is always false.
  bool needs_tier_up_compilation = re_data->MarkedForTierUp() && has_bytecode;
  if (v8_flags.trace_regexp_tier_up && needs_tier_up_compilation) {
    PrintF("JSRegExp object (data: %p) needs tier-up compilation\n",
           reinterpret_cast<void*>(re_data->ptr()));
  }
  if (!needs_initial_compilation && !needs_tier_up_compilation) {
    DCHECK(re_data->has_code(is_one_byte));
    DCHECK_IMPLIES(v8_flags.regexp_interpret_all, has_bytecode);
    return true;
  }
  DCHECK_IMPLIES(needs_tier_up_compilation, has_bytecode);
  return CompileIrregexp(isolate, re_data, sample_subject, is_one_byte);
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by IrregexpPrepare().
IrregexpExec()
std::optional< int > v8::internal::RegExpImpl::IrregexpExec (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length) [static]
Definition at line 816 of file regexp.cc.
                                                                           {
  subject = String::Flatten(isolate, subject);
#ifdef DEBUG
  if (v8_flags.trace_regexp_bytecodes && regexp_data->ShouldProduceBytecode()) {
    PrintF("\n\nRegexp match: /%s/\n\n",
           regexp_data->source()->ToCString().get());
    PrintF("\n\nSubject string: '%s'\n\n", subject->ToCString().get());
  }
#endif
  const int original_register_count =
      JSRegExp::RegistersForCaptureCount(regexp_data->capture_count());
  // Maybe force early tier up:
  if (v8_flags.regexp_tier_up) {
    if (subject->length() >= JSRegExp::kTierUpForSubjectLengthValue) {
      // For very long subject strings, the regexp interpreter is currently much
      // slower than the jitted code execution. If the tier-up strategy is
      // turned on, we want to avoid this performance penalty so we eagerly
      // tier-up if the subject string length is equal or greater than the given
      // heuristic value.
      regexp_data->MarkTierUpForNextExec();
      if (v8_flags.trace_regexp_tier_up) {
        PrintF(
            "Forcing tier-up for very long strings in "
            "RegExpImpl::IrregexpExec\n");
      }
    } else if (static_cast<uint32_t>(original_register_count) <
               result_offsets_vector_length) {
      // Tier up because the interpreter doesn't do global execution.
      Cast<IrRegExpData>(regexp_data)->MarkTierUpForNextExec();
      if (v8_flags.trace_regexp_tier_up) {
        PrintF(
            "Forcing tier-up of RegExpData object %p for global irregexp "
            "mode\n",
            reinterpret_cast<void*>(regexp_data->ptr()));
      }
    }
  }
  int output_register_count =
      RegExpImpl::IrregexpPrepare(isolate, regexp_data, subject);
  if (output_register_count < 0) {
    DCHECK(isolate->has_exception());
    return {};
  }
  // TODO(jgruber): Consider changing these into DCHECKs once we're convinced
  // the conditions hold.
  CHECK_EQ(original_register_count, output_register_count);
  CHECK_LE(static_cast<uint32_t>(output_register_count),
           result_offsets_vector_length);
  RegExpStackScope stack_scope(isolate);
  int res = RegExpImpl::IrregexpExecRaw(isolate, regexp_data, subject,
                                        previous_index, result_offsets_vector,
                                        result_offsets_vector_length);
  if (res >= RegExp::RE_SUCCESS) {
    DCHECK_LE(res * output_register_count, result_offsets_vector_length);
    return res;
  } else if (res == RegExp::RE_FALLBACK_TO_EXPERIMENTAL) {
    return ExperimentalRegExp::OneshotExec(
        isolate, regexp_data, subject, previous_index, result_offsets_vector,
        result_offsets_vector_length);
  } else if (res == RegExp::RE_EXCEPTION) {
    DCHECK(isolate->has_exception());
    return {};
  } else {
    DCHECK(res == RegExp::RE_FAILURE);
    return 0;
  }
}
References CHECK_EQ, CHECK_LE, v8::internal::DCHECK(), DCHECK_LE, v8::internal::Isolate::has_exception(), IrregexpExecRaw(), IrregexpPrepare(), v8::internal::JSRegExp::kTierUpForSubjectLengthValue, v8::internal::ExperimentalRegExp::OneshotExec(), v8::internal::PrintF(), v8::internal::RegExp::RE_EXCEPTION, v8::internal::RegExp::RE_FAILURE, v8::internal::RegExp::RE_FALLBACK_TO_EXPERIMENTAL, v8::internal::RegExp::RE_SUCCESS, v8::internal::JSRegExp::RegistersForCaptureCount(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::Exec().
IrregexpExecRaw()
int v8::internal::RegExpImpl::IrregexpExecRaw (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t * output, int output_size) [static]
Definition at line 741 of file regexp.cc.
                                                                  {
  DCHECK_LE(0, index);
  DCHECK_LE(index, subject->length());
  DCHECK(subject->IsFlat());
  DCHECK_GE(output_size,
            JSRegExp::RegistersForCaptureCount(regexp_data->capture_count()));
  bool is_one_byte = String::IsOneByteRepresentationUnderneath(*subject);
  if (!regexp_data->ShouldProduceBytecode()) {
    do {
      EnsureCompiledIrregexp(isolate, regexp_data, subject, is_one_byte);
      // The stack is used to allocate registers for the compiled regexp code.
      // This means that in case of failure, the output registers array is left
      // untouched and contains the capture results from the previous successful
      // match. We can use that to set the last match info lazily.
      int res = NativeRegExpMacroAssembler::Match(regexp_data, subject, output,
                                                  output_size, index, isolate);
      if (res != NativeRegExpMacroAssembler::RETRY) {
        DCHECK(res != NativeRegExpMacroAssembler::EXCEPTION ||
               isolate->has_exception());
        static_assert(static_cast<int>(NativeRegExpMacroAssembler::SUCCESS) ==
                      RegExp::RE_SUCCESS);
        static_assert(static_cast<int>(NativeRegExpMacroAssembler::FAILURE) ==
                      RegExp::RE_FAILURE);
        static_assert(static_cast<int>(NativeRegExpMacroAssembler::EXCEPTION) ==
                      RegExp::RE_EXCEPTION);
        return res;
      }
      // If result is RETRY, the string has changed representation, and we
      // must restart from scratch.
      // In this case, it means we must make sure we are prepared to handle
      // the, potentially, different subject (the string can switch between
      // being internal and external, and even between being Latin1 and
      // UC16, but the characters are always the same).
      is_one_byte = String::IsOneByteRepresentationUnderneath(*subject);
    } while (true);
    UNREACHABLE();
  } else {
    DCHECK(regexp_data->ShouldProduceBytecode());
    do {
      int result = IrregexpInterpreter::MatchForCallFromRuntime(
          isolate, regexp_data, subject, output, output_size, index);
      DCHECK_IMPLIES(result == IrregexpInterpreter::EXCEPTION,
                     isolate->has_exception());
      static_assert(IrregexpInterpreter::FAILURE == 0);
      static_assert(IrregexpInterpreter::SUCCESS == 1);
      static_assert(IrregexpInterpreter::FALLBACK_TO_EXPERIMENTAL < 0);
      static_assert(IrregexpInterpreter::EXCEPTION < 0);
      static_assert(IrregexpInterpreter::RETRY < 0);
      if (result >= IrregexpInterpreter::FAILURE) {
        return result;
      }
      if (result == IrregexpInterpreter::RETRY) {
        // The string has changed representation, and we must restart the
        // match. We need to reset the tier up to start over with compilation.
        if (v8_flags.regexp_tier_up) regexp_data->ResetLastTierUpTick();
        is_one_byte = String::IsOneByteRepresentationUnderneath(*subject);
        EnsureCompiledIrregexp(isolate, regexp_data, subject, is_one_byte);
      } else {
        DCHECK(result == IrregexpInterpreter::EXCEPTION ||
               result == IrregexpInterpreter::FALLBACK_TO_EXPERIMENTAL);
        return result;
      }
    } while (true);
    UNREACHABLE();
  }
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_IMPLIES, DCHECK_LE, v8::internal::IrregexpInterpreter::EXCEPTION, v8::internal::NativeRegExpMacroAssembler::EXCEPTION, v8::internal::IrregexpInterpreter::FAILURE, v8::internal::NativeRegExpMacroAssembler::FAILURE, v8::internal::IrregexpInterpreter::FALLBACK_TO_EXPERIMENTAL, v8::internal::Isolate::has_exception(), v8::internal::index, v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::NativeRegExpMacroAssembler::Match(), v8::internal::IrregexpInterpreter::MatchForCallFromRuntime(), v8::internal::RegExp::RE_EXCEPTION, v8::internal::RegExp::RE_FAILURE, v8::internal::RegExp::RE_SUCCESS, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::base::internal::result, v8::internal::IrregexpInterpreter::RETRY, v8::internal::NativeRegExpMacroAssembler::RETRY, v8::internal::IrregexpInterpreter::SUCCESS, v8::internal::NativeRegExpMacroAssembler::SUCCESS, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExpGlobalExecRunner::FetchNext(), and IrregexpExec().
IrregexpInitialize()
void v8::internal::RegExpImpl::IrregexpInitialize (Isolate * isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, int capture_count, uint32_t backtrack_limit) [static]
Definition at line 713 of file regexp.cc.
                                                              {
  // Initialize compiled code entries to null.
  isolate->factory()->SetRegExpIrregexpData(re, pattern,
                                            JSRegExp::AsJSRegExpFlags(flags),
                                            capture_count, backtrack_limit);
}
References v8::internal::JSRegExp::AsJSRegExpFlags(), v8::internal::Isolate::factory(), v8::internal::flags, and v8::internal::Factory::SetRegExpIrregexpData().
Referenced by v8::internal::RegExp::Compile().
IrregexpPrepare()
int v8::internal::RegExpImpl::IrregexpPrepare (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject) [static]
Definition at line 724 of file regexp.cc.
                                                              {
  DCHECK(subject->IsFlat());
  // Check representation of the underlying storage.
  bool is_one_byte = String::IsOneByteRepresentationUnderneath(*subject);
  if (!RegExpImpl::EnsureCompiledIrregexp(isolate, re_data, subject,
                                          is_one_byte)) {
    return -1;
  }
  // Only reserve room for output captures. Internal registers are allocated by
  // the engine.
  return JSRegExp::RegistersForCaptureCount(re_data->capture_count());
}
References v8::internal::DCHECK(), EnsureCompiledIrregexp(), v8::internal::String::IsOneByteRepresentationUnderneath(), and v8::internal::JSRegExp::RegistersForCaptureCount().
Referenced by v8::internal::RegExp::EnsureFullyCompiled(), IrregexpExec(), and v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner().
ToString()
static DirectHandle<String> v8::internal::RegExpImpl::ToString (DirectHandle< Object > value) [static]
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp.cc