v8::internal::maglev::ToString Class Reference
#include <maglev-ir.h>
Public Types
enum ConversionMode { kConvertSymbol
, kThrowOnSymbol
 }
Public Member Functions
ToString (uint64_t bitfield, ConversionMode mode)
Input & context ()
Input & value_input ()
ConversionMode mode () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, ToString >
using ConversionModeBitField = NextBitField< ConversionMode, 1 >
Additional Inherited Members
Detailed Description
Definition at line 5414 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ToString::Base = FixedInputValueNodeT<2, ToString> [private]
Definition at line 5415 of file maglev-ir.h.
ConversionModeBitField
using v8::internal::maglev::ToString::ConversionModeBitField = NextBitField<ConversionMode, 1> [private]
Definition at line 5439 of file maglev-ir.h.
Member Enumeration Documentation
ConversionMode
enum v8::internal::maglev::ToString::ConversionMode
Enumerator
kConvertSymbol
kThrowOnSymbol
Definition at line 5418 of file maglev-ir.h.
{ kConvertSymbol, kThrowOnSymbol };
Constructor & Destructor Documentation
ToString()
v8::internal::maglev::ToString::ToString (uint64_t bitfield, ConversionMode mode) [inline], [explicit]
Definition at line 5419 of file maglev-ir.h.
      : Base(ConversionModeBitField::update(bitfield, mode)) {}
Member Function Documentation
context()
Input& v8::internal::maglev::ToString::context () [inline]
Definition at line 5427 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::ToString::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ToString::MaxCallStackArgs () const
mode()
ConversionMode v8::internal::maglev::ToString::mode () const [inline]
Definition at line 5429 of file maglev-ir.h.
                              {
    return ConversionModeBitField::decode(bitfield());
  }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::ToString::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5436 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::ToString::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::ToString::value_input () [inline]
Definition at line 5428 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ToString::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 5424 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ToString::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 5423 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h