v8::CodeEventHandler Class Reference
Interface to listen to code creation and code relocation events.
#include <v8-profiler.h>
Public Member Functions
CodeEventHandler (Isolate *isolate)
Creates a new listener for the |isolate|.
virtual ~CodeEventHandler ()
virtual void Handle (CodeEvent *code_event)=0
Handle is called every time a code object is created or moved.
void Enable ()
Call Enable() to starts listening to code creation and code relocation events.
void Disable ()
Call Disable() to stop listening to code creation and code relocation events.
Private Member Functions
CodeEventHandler ()
CodeEventHandler (const CodeEventHandler &)
CodeEventHandler & operator= (const CodeEventHandler &)
Private Attributes
void * internal_listener_
Detailed Description
Interface to listen to code creation and code relocation events.
Definition at line 1313 of file v8-profiler.h.
Constructor & Destructor Documentation
CodeEventHandler() [1/3]
v8::CodeEventHandler::CodeEventHandler (Isolate * isolate) [explicit]
Creates a new listener for the |isolate|.
The isolate must be initialized. The listener object must be disposed after use by calling |Dispose| method. Multiple listeners can be created for the same isolate.
Definition at line 11580 of file api.cc.
                                                      {
  internal_listener_ = new i::ExternalLogEventListener(
      reinterpret_cast<i::Isolate*>(v8_isolate));
}
References internal_listener_.
 CodeEventHandler()
v8::CodeEventHandler::~CodeEventHandler () [virtual]
Definition at line 11585 of file api.cc.
                                    {
  delete reinterpret_cast<i::ExternalLogEventListener*>(internal_listener_);
}
References internal_listener_.
CodeEventHandler() [2/3]
v8::CodeEventHandler::CodeEventHandler () [private]
CodeEventHandler() [3/3]
v8::CodeEventHandler::CodeEventHandler (const CodeEventHandler &) [private]
Member Function Documentation
Disable()
void v8::CodeEventHandler::Disable ()
Call Disable() to stop listening to code creation and code relocation events.
Definition at line 11594 of file api.cc.
                               {
  reinterpret_cast<i::ExternalLogEventListener*>(internal_listener_)
      ->StopListening();
}
References internal_listener_.
Enable()
void v8::CodeEventHandler::Enable ()
Call Enable() to starts listening to code creation and code relocation events.
These events will be handled by Handle().
Definition at line 11589 of file api.cc.
                              {
  reinterpret_cast<i::ExternalLogEventListener*>(internal_listener_)
      ->StartListening(this);
}
References internal_listener_.
Handle()
virtual void v8::CodeEventHandler::Handle (CodeEvent * code_event) [pure virtual]
Handle is called every time a code object is created or moved.
Information about each code event will be available through the code_event parameter.
When the CodeEventType is kRelocationType, the code for this CodeEvent has moved from GetPreviousCodeStartAddress() to GetCodeStartAddress().
Referenced by v8::internal::ExternalLogEventListener::BytecodeMoveEvent(), v8::internal::ExternalLogEventListener::CodeCreateEvent(), v8::internal::ExternalLogEventListener::CodeMoveEvent(), and v8::internal::ExternalLogEventListener::RegExpCodeCreateEvent().
operator=()
CodeEventHandler& v8::CodeEventHandler::operator= (const CodeEventHandler &) [private]
Member Data Documentation
internal_listener_
void* v8::CodeEventHandler::internal_listener_ [private]
Definition at line 1349 of file v8-profiler.h.
Referenced by CodeEventHandler(), Disable(), Enable(), and ~CodeEventHandler().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc