v8::internal::wasm::WasmOpcodes Class Reference
#include <wasm-opcodes.h>
Static Public Member Functions
static constexpr const char * OpcodeName (WasmOpcode)
static constexpr const FunctionSig * Signature (WasmOpcode)
static constexpr const FunctionSig * SignatureForAtomicOp (WasmOpcode opcode, bool is_memory64)
static constexpr const FunctionSig * AsmjsSignature (WasmOpcode)
static constexpr bool IsPrefixOpcode (WasmOpcode)
static constexpr bool IsControlOpcode (WasmOpcode)
static constexpr bool IsExternRefOpcode (WasmOpcode)
static constexpr bool IsThrowingOpcode (WasmOpcode)
static constexpr bool IsRelaxedSimdOpcode (WasmOpcode)
static constexpr bool IsFP16SimdOpcode (WasmOpcode)
static constexpr bool IsUnconditionalJump (WasmOpcode)
static constexpr bool IsBreakable (WasmOpcode)
static constexpr MessageTemplate TrapReasonToMessageId (TrapReason)
static constexpr TrapReason MessageIdToTrapReason (MessageTemplate message)
static constexpr uint8_t ExtractPrefix (WasmOpcode)
static const char * TrapReasonMessage (TrapReason)
Detailed Description
Definition at line 973 of file wasm-opcodes.h.
Member Function Documentation
AsmjsSignature()
constexpr const FunctionSig * v8::internal::wasm::WasmOpcodes::AsmjsSignature (WasmOpcode opcode) [static], [constexpr]
Definition at line 291 of file wasm-opcodes-inl.h.
                                                                          {
  DCHECK_GT(impl::kSimpleAsmjsExprSigTable.size(), (opcode & 0xff));
  return impl::kCachedSigs[impl::kSimpleAsmjsExprSigTable[opcode & 0xff]];
}
References DCHECK_GT, v8::internal::wasm::impl::kCachedSigs, v8::internal::wasm::impl::kSimpleAsmjsExprSigTable, and size().
ExtractPrefix()
constexpr uint8_t v8::internal::wasm::WasmOpcodes::ExtractPrefix (WasmOpcode opcode) [static], [constexpr]
Definition at line 164 of file wasm-opcodes-inl.h.
                                                              {
  // See comment on {WasmOpcode} for the encoding.
  return (opcode > 0xffff) ? opcode >> 12 : opcode >> 8;
}
Referenced by Signature().
IsBreakable()
constexpr bool v8::internal::wasm::WasmOpcodes::IsBreakable (WasmOpcode opcode) [static], [constexpr]
Definition at line 89 of file wasm-opcodes-inl.h.
                                                         {
  switch (opcode) {
    case kExprBlock:
    case kExprTry:
    case kExprCatch:
    case kExprLoop:
    case kExprElse:
      return false;
    default:
      return true;
  }
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitDebuggingInfo(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), and v8::internal::WasmScript::GetPossibleBreakpoints().
IsControlOpcode()
constexpr bool v8::internal::wasm::WasmOpcodes::IsControlOpcode (WasmOpcode opcode) [static], [constexpr]
Definition at line 60 of file wasm-opcodes-inl.h.
                                                             {
  switch (opcode) {
#define CHECK_OPCODE(name, ...) case kExpr##name:
    FOREACH_CONTROL_OPCODE(CHECK_OPCODE)
#undef CHECK_OPCODE
    return true;
    default:
      return false;
  }
}
References CHECK_OPCODE, and FOREACH_CONTROL_OPCODE.
IsExternRefOpcode()
constexpr bool v8::internal::wasm::WasmOpcodes::IsExternRefOpcode (WasmOpcode opcode) [static], [constexpr]
Definition at line 103 of file wasm-opcodes-inl.h.
                                                               {
  switch (opcode) {
    case kExprRefNull:
    case kExprRefIsNull:
    case kExprRefFunc:
    case kExprRefAsNonNull:
      return true;
    default:
      return false;
  }
}
IsFP16SimdOpcode()
constexpr bool v8::internal::wasm::WasmOpcodes::IsFP16SimdOpcode (WasmOpcode opcode) [static], [constexpr]
Definition at line 142 of file wasm-opcodes-inl.h.
                                                              {
  return (opcode >= kExprF16x8Splat && opcode <= kExprF16x8ReplaceLane) ||
         (opcode >= kExprF16x8Abs && opcode <= kExprF16x8Qfms);
}
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE().
IsPrefixOpcode()
constexpr bool v8::internal::wasm::WasmOpcodes::IsPrefixOpcode (WasmOpcode opcode) [static], [constexpr]
Definition at line 48 of file wasm-opcodes-inl.h.
                                                            {
  switch (opcode) {
#define CHECK_PREFIX(name, opcode) case k##name##Prefix:
    FOREACH_PREFIX(CHECK_PREFIX)
#undef CHECK_PREFIX
    return true;
    default:
      return false;
  }
}
References CHECK_PREFIX, and FOREACH_PREFIX.
Referenced by v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::FunctionBodyDisassembler::GetOpcode(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::memop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NextInstruction(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SafeOpcodeNameAt().
IsRelaxedSimdOpcode()
constexpr bool v8::internal::wasm::WasmOpcodes::IsRelaxedSimdOpcode (WasmOpcode opcode) [static], [constexpr]
Definition at line 130 of file wasm-opcodes-inl.h.
                                                                 {
  // Relaxed SIMD opcodes have the SIMD prefix (0xfd) shifted by 12 bits, and
  // nibble 3 must be 0x1. I.e. their encoded opcode is in [0xfd100, 0xfd1ff].
  static_assert(kSimdPrefix == 0xfd);
#define CHECK_OPCODE(name, opcode, ...) \
  static_assert((opcode & 0xfff00) == 0xfd100);
  FOREACH_RELAXED_SIMD_OPCODE(CHECK_OPCODE)
#undef CHECK_OPCODE
  return (opcode & 0xfff00) == 0xfd100;
}
References CHECK_OPCODE, and FOREACH_RELAXED_SIMD_OPCODE.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmBytecodeGenerator::DecodeSimdOp(), and Signature().
IsThrowingOpcode()
constexpr bool v8::internal::wasm::WasmOpcodes::IsThrowingOpcode (WasmOpcode opcode) [static], [constexpr]
Definition at line 116 of file wasm-opcodes-inl.h.
                                                              {
  // TODO(8729): Trapping opcodes are not yet considered to be throwing.
  switch (opcode) {
    case kExprThrow:
    case kExprRethrow:
    case kExprCallFunction:
    case kExprCallIndirect:
      return true;
    default:
      return false;
  }
}
IsUnconditionalJump()
constexpr bool v8::internal::wasm::WasmOpcodes::IsUnconditionalJump (WasmOpcode opcode) [static], [constexpr]
Definition at line 72 of file wasm-opcodes-inl.h.
                                                                 {
  switch (opcode) {
    case kExprUnreachable:
    case kExprBr:
    case kExprBrTable:
    case kExprReturn:
    case kExprReturnCall:
    case kExprReturnCallIndirect:
    case kExprThrow:
    case kExprRethrow:
      return true;
    default:
      return false;
  }
}
MessageIdToTrapReason()
constexpr TrapReason v8::internal::wasm::WasmOpcodes::MessageIdToTrapReason (MessageTemplate message) [static], [constexpr]
Definition at line 309 of file wasm-opcodes-inl.h.
                             {
  switch (message) {
#define MESSAGE_TO_TRAPREASON(name) \
  case MessageTemplate::kWasm##name: \
    return k##name;
    FOREACH_WASM_TRAPREASON(MESSAGE_TO_TRAPREASON)
#undef MESSAGE_TO_TRAPREASON
    default:
      UNREACHABLE();
  }
}
References FOREACH_WASM_TRAPREASON, MESSAGE_TO_TRAPREASON, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmInterpreterThread::SetRuntimeLastWasmError().
OpcodeName()
constexpr const char * v8::internal::wasm::WasmOpcodes::OpcodeName (WasmOpcode opcode) [static], [constexpr]
Definition at line 26 of file wasm-opcodes-inl.h.
                                                               {
  switch (opcode) {
#define CASE(opcode, binary, sig, name, ...) \
  case kExpr##opcode: \
    return name;
    FOREACH_OPCODE(CASE)
#undef CASE
    case kNumericPrefix:
    case kSimdPrefix:
    case kAtomicPrefix:
    case kGCPrefix:
    case kAsmJsPrefix:
      return "unknown";
  }
  // Even though the switch above handles all well-defined enum values,
  // random modules (e.g. fuzzer generated) can call this function with
  // random (invalid) opcodes. Handle those here:
  return "invalid opcode";
}
References CASE, and FOREACH_OPCODE.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp(), v8::internal::wasm::FunctionBodyDisassembler::DecodeGlobalInitializer(), v8::internal::wasm::WasmBytecodeGenerator::DecodeNumericOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeSimdOp(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::NextInstruction(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::NonConstError(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SafeOpcodeNameAt().
Signature()
constexpr const FunctionSig * v8::internal::wasm::WasmOpcodes::Signature (WasmOpcode opcode) [static], [constexpr]
Definition at line 256 of file wasm-opcodes-inl.h.
                                                                     {
  switch (ExtractPrefix(opcode)) {
    case 0:
      DCHECK_GT(impl::kShortSigTable.size(), opcode);
      return impl::kCachedSigs[impl::kShortSigTable[opcode]];
    case kSimdPrefix: {
      // Handle SIMD MVP opcodes (in [0xfd00, 0xfdff]).
      if (opcode <= 0xfdff) {
        DCHECK_LE(0xfd00, opcode);
        return impl::kCachedSigs[impl::kSimdExprSigTable[opcode & 0xff]];
      }
      // Handle relaxed SIMD opcodes (in [0xfd100, 0xfd1ff]).
      if (IsRelaxedSimdOpcode(opcode)) {
        return impl::kCachedSigs[impl::kRelaxedSimdExprSigTable[opcode & 0xff]];
      }
      return nullptr;
    }
    case kNumericPrefix:
      return impl::kCachedSigs[impl::kNumericExprSigTable[opcode & 0xff]];
    case kAsmJsPrefix:
      return impl::kCachedSigs[impl::kSimpleAsmjsExprSigTable[opcode & 0xff]];
    default:
      UNREACHABLE(); // invalid prefix.
  }
}
References DCHECK_GT, DCHECK_LE, ExtractPrefix(), IsRelaxedSimdOpcode(), v8::internal::wasm::impl::kCachedSigs, v8::internal::wasm::impl::kNumericExprSigTable, v8::internal::wasm::impl::kRelaxedSimdExprSigTable, v8::internal::wasm::impl::kShortSigTable, v8::internal::wasm::impl::kSimdExprSigTable, v8::internal::wasm::impl::kSimpleAsmjsExprSigTable, size(), and v8::internal::UNREACHABLE().
SignatureForAtomicOp()
constexpr const FunctionSig * v8::internal::wasm::WasmOpcodes::SignatureForAtomicOp (WasmOpcode opcode, bool is_memory64) [static], [constexpr]
Definition at line 282 of file wasm-opcodes-inl.h.
                                         {
  if (is_memory64) {
    return impl::kCachedSigs[impl::kAtomicExprSigTableMem64[opcode & 0xff]];
  } else {
    return impl::kCachedSigs[impl::kAtomicExprSigTableMem32[opcode & 0xff]];
  }
}
References v8::internal::wasm::impl::kAtomicExprSigTableMem32, v8::internal::wasm::impl::kAtomicExprSigTableMem64, and v8::internal::wasm::impl::kCachedSigs.
TrapReasonMessage()
const char * v8::internal::wasm::WasmOpcodes::TrapReasonMessage (TrapReason reason) [inline], [static]
Definition at line 322 of file wasm-opcodes-inl.h.
                                                            {
  return MessageFormatter::TemplateString(TrapReasonToMessageId(reason));
}
References v8::internal::MessageFormatter::TemplateString(), and TrapReasonToMessageId().
TrapReasonToMessageId()
constexpr MessageTemplate v8::internal::wasm::WasmOpcodes::TrapReasonToMessageId (TrapReason reason) [static], [constexpr]
Definition at line 296 of file wasm-opcodes-inl.h.
                       {
  switch (reason) {
#define TRAPREASON_TO_MESSAGE(name) \
  case k##name: \
    return MessageTemplate::kWasm##name;
    FOREACH_WASM_TRAPREASON(TRAPREASON_TO_MESSAGE)
#undef TRAPREASON_TO_MESSAGE
    case kTrapCount:
      UNREACHABLE();
  }
}
References FOREACH_WASM_TRAPREASON, v8::internal::wasm::kTrapCount, TRAPREASON_TO_MESSAGE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), and TrapReasonMessage().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-opcodes.h
/mnt/V8SourceCode/src/wasm/wasm-opcodes-inl.h