v8::internal::wasm::CanonicalTypeNamesProvider Class Reference
#include <names-provider.h>
Public Member Functions
CanonicalTypeNamesProvider ()=default
void DecodeNameSections ()
void DecodeNames (NativeModule *native_module)
void PrintTypeName (StringBuilder &out, CanonicalTypeIndex type_index, NamesProvider::IndexAsComment index_as_comment=NamesProvider::kDontPrintIndex)
void PrintValueType (StringBuilder &out, CanonicalValueType type)
void PrintFieldName (StringBuilder &out, CanonicalTypeIndex struct_index, uint32_t field_index)
size_t EstimateCurrentMemoryConsumption () const
Private Types
using StringT = base::OwnedVector< char >
Private Member Functions
size_t DetectInlineStringThreshold ()
Private Attributes
std::vector< StringT > type_names_
std::map< uint32_t, std::vector< StringT > > field_names_
base::Mutex mutex_
size_t payload_size_estimate_ {0}
Detailed Description
Definition at line 105 of file names-provider.h.
Member Typedef Documentation
StringT
using v8::internal::wasm::CanonicalTypeNamesProvider::StringT = base::OwnedVector<char> [private]
Definition at line 124 of file names-provider.h.
Constructor & Destructor Documentation
CanonicalTypeNamesProvider()
v8::internal::wasm::CanonicalTypeNamesProvider::CanonicalTypeNamesProvider () [default]
Member Function Documentation
DecodeNames()
void v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNames (NativeModule * native_module)
Definition at line 472 of file names-provider.cc.
                                                                        {
  const WasmModule* module = native_module->module();
  if (module->canonical_typenames_decoded) return;
  module->canonical_typenames_decoded = true;
  base::Vector<const uint8_t> wire_bytes = native_module->wire_bytes();
  WireBytesRef name_section = module->name_section;
  if (name_section.is_empty()) return;
  size_t added_size = 0;
  DecodeCanonicalTypeNames(wire_bytes, module, type_names_, field_names_,
                           &added_size);
  payload_size_estimate_ += added_size;
}
References v8::internal::wasm::WasmModule::canonical_typenames_decoded, v8::internal::wasm::DecodeCanonicalTypeNames(), field_names_, v8::internal::wasm::WireBytesRef::is_empty(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WasmModule::name_section, payload_size_estimate_, type_names_, and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::internal::wasm::WasmEngine::DecodeAllNameSections().
DecodeNameSections()
void v8::internal::wasm::CanonicalTypeNamesProvider::DecodeNameSections ()
Definition at line 465 of file names-provider.cc.
                                                    {
  // TODO(jkummerow): We'll probably need to lock read accesses too.
  base::MutexGuard lock(&mutex_);
  type_names_.resize(GetTypeCanonicalizer()->GetCurrentNumberOfTypes());
  GetWasmEngine()->DecodeAllNameSections(this);
}
References v8::internal::wasm::WasmEngine::DecodeAllNameSections(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::wasm::GetWasmEngine(), mutex_, and type_names_.
Referenced by PrintFieldName(), and PrintTypeName().
DetectInlineStringThreshold()
size_t v8::internal::wasm::CanonicalTypeNamesProvider::DetectInlineStringThreshold () [private]
Definition at line 549 of file names-provider.cc.
                                                               {
  for (size_t i = 0; i < 32; i++) {
    std::string s(i, 'c');
    Address str = reinterpret_cast<Address>(&s);
    Address data = reinterpret_cast<Address>(s.data());
    if (data < str || data >= str + sizeof(s)) return i;
  }
  return 32;
}
References v8::internal::string.
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::CanonicalTypeNamesProvider::EstimateCurrentMemoryConsumption () const
Definition at line 451 of file names-provider.cc.
                                                                          {
  size_t result = sizeof(this) + payload_size_estimate_;
  result += type_names_.capacity() * sizeof(StringT);
  result += ContentSize(field_names_);
  for (const auto& entry : field_names_) {
    const std::vector<StringT>& vec = entry.second;
    result += vec.capacity() * sizeof(StringT);
  }
  if (v8_flags.trace_wasm_offheap_memory) {
    PrintF("CanonicalTypeNamesProvider: %zu\n", result);
  }
  return result;
}
References v8::internal::wasm::ContentSize(), field_names_, payload_size_estimate_, v8::internal::PrintF(), v8::base::internal::result, type_names_, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::EstimateCurrentMemoryConsumption().
PrintFieldName()
void v8::internal::wasm::CanonicalTypeNamesProvider::PrintFieldName (StringBuilder & out, CanonicalTypeIndex struct_index, uint32_t field_index)
Definition at line 527 of file names-provider.cc.
                                                                      {
  uint32_t index = struct_index.index;
  if (index > type_names_.size()) DecodeNameSections();
  auto per_type = field_names_.find(index);
  if (per_type != field_names_.end()) {
    std::vector<StringT>& field_names = per_type->second;
    if (field_index < field_names.size() && !field_names[field_index].empty()) {
      const StringT& name = field_names[field_index];
      out << '$';
      out.write(name.data(), name.size());
      return;
    }
  }
  out << "$field" << field_index;
}
References DecodeNameSections(), field_names_, v8::internal::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::name(), type_names_, and v8::internal::wasm::StringBuilder::write().
Referenced by v8::internal::StructProxy::GetName().
PrintTypeName()
void v8::internal::wasm::CanonicalTypeNamesProvider::PrintTypeName (StringBuilder & out, CanonicalTypeIndex type_index, NamesProvider::IndexAsComment index_as_comment = NamesProvider::kDontPrintIndex)
Definition at line 485 of file names-provider.cc.
                                                  {
  uint32_t index = type_index.index;
  if (index > type_names_.size() || type_names_[index].empty()) {
    DecodeNameSections();
  }
  // {index} should now always be in range, but let's be robust towards
  // invalid parameter values.
  if (index > type_names_.size() || type_names_[index].empty()) {
    out << "$canon" << index;
    return;
  }
  StringT& name = type_names_[index];
  out << '$';
  out.write(name.data(), name.size());
  MaybeAddComment(out, index, index_as_comment);
}
References DecodeNameSections(), v8::internal::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::anonymous_namespace{names-provider.cc}::MaybeAddComment(), v8::internal::wasm::name(), type_names_, and v8::internal::wasm::StringBuilder::write().
Referenced by v8::internal::V8HeapExplorer::AddEntry(), and PrintValueType().
PrintValueType()
void v8::internal::wasm::CanonicalTypeNamesProvider::PrintValueType (StringBuilder & out, CanonicalValueType type)
Definition at line 504 of file names-provider.cc.
                                                                         {
  switch (type.kind()) {
    case kRef:
    case kRefNull:
      if (type.encoding_needs_heap_type()) {
        out << (type.kind() == kRef ? "(ref " : "(ref null ");
        if (type.is_exact()) out << "exact ";
        if (type.has_index()) {
          PrintTypeName(out, type.ref_index());
        } else {
          out << type.name();
        }
        out << ')';
      } else {
        out << type.name();
      }
      break;
    default:
      out << wasm::name(type.kind());
  }
}
References v8::internal::kRef, v8::internal::kRefNull, v8::internal::wasm::name(), PrintTypeName(), and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetRefTypeName().
Member Data Documentation
field_names_
std::map<uint32_t, std::vector<StringT> > v8::internal::wasm::CanonicalTypeNamesProvider::field_names_ [private]
Definition at line 129 of file names-provider.h.
Referenced by DecodeNames(), EstimateCurrentMemoryConsumption(), and PrintFieldName().
mutex_
base::Mutex v8::internal::wasm::CanonicalTypeNamesProvider::mutex_ [mutable], [private]
Definition at line 130 of file names-provider.h.
Referenced by DecodeNameSections().
payload_size_estimate_
size_t v8::internal::wasm::CanonicalTypeNamesProvider::payload_size_estimate_ {0} [private]
Definition at line 131 of file names-provider.h.
Referenced by DecodeNames(), and EstimateCurrentMemoryConsumption().
type_names_
std::vector<StringT> v8::internal::wasm::CanonicalTypeNamesProvider::type_names_ [private]
Definition at line 128 of file names-provider.h.
Referenced by DecodeNames(), DecodeNameSections(), EstimateCurrentMemoryConsumption(), PrintFieldName(), and PrintTypeName().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/names-provider.h
/mnt/V8SourceCode/src/wasm/names-provider.cc