v8::internal::compiler::JSCallOrConstructNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSCallOrConstructNode (Node *node)
TNode< Object > Argument (int i) const
int LastArgumentIndex () const
TNode< Object > LastArgument () const
TNode< Object > ArgumentOr (int i, TNode< Object > default_value) const
TNode< Object > ArgumentOrUndefined (int i, JSGraph *jsgraph) const
virtual int ArgumentCount () const =0
int FeedbackVectorIndex () const
TNode< HeapObject > feedback_vector () const
Static Public Member Functions
static constexpr int ArityForArgc (int parameters)
static constexpr int FirstArgumentIndex ()
static constexpr int ArgumentIndex (int i)
static constexpr int FeedbackVectorIndexForArgc (int argc)
Static Public Attributes
static constexpr int kTargetInputCount = 1
static constexpr int kReceiverOrNewTargetInputCount = 1
static constexpr int kFeedbackVectorInputCount = 1
static constexpr int kExtraInputCount
static constexpr bool kFeedbackVectorIsLastInput = true
static constexpr bool kHaveIdenticalLayouts = true
Static Private Member Functions
static constexpr bool IsValidNode (Node *node)
Additional Inherited Members
Detailed Description
Definition at line 1357 of file js-operator.h.
Constructor & Destructor Documentation
JSCallOrConstructNode()
constexpr v8::internal::compiler::JSCallOrConstructNode::JSCallOrConstructNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1359 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK(IsValidNode(node));
  }
References v8::internal::DCHECK(), IsValidNode(), and v8::internal::compiler::NodeWrapper::node().
Member Function Documentation
Argument()
TNode<Object> v8::internal::compiler::JSCallOrConstructNode::Argument (int i) const [inline]
Definition at line 1402 of file js-operator.h.
                                      {
    DCHECK_LT(i, ArgumentCount());
    return TNode<Object>::UncheckedCast(
        NodeProperties::GetValueInput(node(), ArgumentIndex(i)));
  }
References ArgumentCount(), ArgumentIndex(), DCHECK_LT, v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by ArgumentOr(), LastArgument(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceBigIntAsN(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsFinite(), v8::internal::compiler::JSCallReducer::ReduceGlobalIsNaN(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducer::ReduceMathClz32(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::JSCallReducer::ReduceNumberIsFinite(), v8::internal::compiler::JSCallReducer::ReduceNumberIsInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberIsNaN(), v8::internal::compiler::JSCallReducer::ReduceNumberIsSafeInteger(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringFromCharCode(), v8::internal::compiler::JSCallReducer::ReduceStringFromCodePoint(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeConcat(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
ArgumentCount()
virtual int v8::internal::compiler::JSCallOrConstructNode::ArgumentCount () const [pure virtual]
Implemented in v8::internal::compiler::JSCallNodeBase< kOpcodes >, and v8::internal::compiler::JSConstructNodeBase< kOpcode >.
Referenced by Argument(), ArgumentOr(), FeedbackVectorIndex(), LastArgument(), and LastArgumentIndex().
ArgumentIndex()
static constexpr int v8::internal::compiler::JSCallOrConstructNode::ArgumentIndex (int i) [inline], [static], [constexpr]
Definition at line 1400 of file js-operator.h.
{ return FirstArgumentIndex() + i; }
References FirstArgumentIndex(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by Argument(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), FeedbackVectorIndexForArgc(), LastArgumentIndex(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), and v8::internal::compiler::JSCallReducer::ReduceReflectConstruct().
ArgumentOr()
TNode<Object> v8::internal::compiler::JSCallOrConstructNode::ArgumentOr (int i, TNode< Object > default_value) const [inline]
Definition at line 1415 of file js-operator.h.
                                                                     {
    return i < ArgumentCount() ? Argument(i) : default_value;
  }
References Argument(), and ArgumentCount().
Referenced by ArgumentOrUndefined(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceMathImul(), v8::internal::compiler::JSCallReducer::ReduceNumberConstructor(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), and v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCodePointAt().
ArgumentOrUndefined()
TNode<Object> v8::internal::compiler::JSCallOrConstructNode::ArgumentOrUndefined (int i, JSGraph * jsgraph) const [inline]
Definition at line 1418 of file js-operator.h.
                                                                   {
    return ArgumentOr(i, js_node_wrapper_utils::UndefinedConstant(jsgraph));
  }
References ArgumentOr(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceBooleanConstructor(), v8::internal::compiler::JSCallReducer::ReduceDataViewAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototypeOf(), v8::internal::compiler::JSCallReducer::ReduceObjectIs(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeThen(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceReflectGetPrototypeOf(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayConstructor().
ArityForArgc()
static constexpr int v8::internal::compiler::JSCallOrConstructNode::ArityForArgc (int parameters) [inline], [static], [constexpr]
Definition at line 1393 of file js-operator.h.
                                                    {
    return parameters + kExtraInputCount;
  }
References kExtraInputCount.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSOperatorBuilder::CallWithArrayLike(), v8::internal::compiler::JSOperatorBuilder::ConstructForwardAllArgs(), v8::internal::compiler::JSOperatorBuilder::ConstructWithArrayLike(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertySetterCall(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSIntrinsicLowering::ReduceCall(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), and v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally().
feedback_vector()
TNode<HeapObject> v8::internal::compiler::JSCallOrConstructNode::feedback_vector () const [inline]
Definition at line 1430 of file js-operator.h.
                                            {
    return TNode<HeapObject>::UncheckedCast(
        NodeProperties::GetValueInput(node(), FeedbackVectorIndex()));
  }
References FeedbackVectorIndex(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), and v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply().
FeedbackVectorIndex()
int v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndex () const [inline]
Definition at line 1427 of file js-operator.h.
                                  {
    return FeedbackVectorIndexForArgc(ArgumentCount());
  }
References ArgumentCount(), and FeedbackVectorIndexForArgc().
Referenced by feedback_vector(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), and v8::internal::compiler::JSTypedLowering::ReduceJSConstruct().
FeedbackVectorIndexForArgc()
static constexpr int v8::internal::compiler::JSCallOrConstructNode::FeedbackVectorIndexForArgc (int argc) [inline], [static], [constexpr]
Definition at line 1423 of file js-operator.h.
                                                            {
    static_assert(kFeedbackVectorIsLastInput);
    return ArgumentIndex(argc - 1) + 1;
  }
References ArgumentIndex(), and kFeedbackVectorIsLastInput.
Referenced by FeedbackVectorIndex(), and v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments().
FirstArgumentIndex()
static constexpr int v8::internal::compiler::JSCallOrConstructNode::FirstArgumentIndex () [inline], [static], [constexpr]
Definition at line 1397 of file js-operator.h.
                                            {
    return ReceiverOrNewTargetIndex() + 1;
  }
Referenced by ArgumentIndex(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), and v8::internal::compiler::JSCallReducer::ReduceReflectConstruct().
IsValidNode()
static constexpr bool v8::internal::compiler::JSCallOrConstructNode::IsValidNode (Node * node) [inline], [static], [constexpr], [private]
Definition at line 1436 of file js-operator.h.
                                                {
    return node->opcode() == IrOpcode::kJSCall ||
           node->opcode() == IrOpcode::kJSCallWithArrayLike ||
           node->opcode() == IrOpcode::kJSCallWithSpread ||
           node->opcode() == IrOpcode::kJSConstruct ||
           node->opcode() == IrOpcode::kJSConstructWithArrayLike ||
           node->opcode() == IrOpcode::kJSConstructWithSpread ||
           node->opcode() == IrOpcode::kJSConstructForwardAllArgs
#if V8_ENABLE_WEBASSEMBLY
           || node->opcode() == IrOpcode::kJSWasmCall
#endif // V8_ENABLE_WEBASSEMBLY
        ; // NOLINT(whitespace/semicolon)
  }
References v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Referenced by JSCallOrConstructNode().
LastArgument()
TNode<Object> v8::internal::compiler::JSCallOrConstructNode::LastArgument () const [inline]
Definition at line 1411 of file js-operator.h.
                                     {
    DCHECK_GT(ArgumentCount(), 0);
    return Argument(ArgumentCount() - 1);
  }
References Argument(), ArgumentCount(), and DCHECK_GT.
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
LastArgumentIndex()
int v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex () const [inline]
Definition at line 1407 of file js-operator.h.
                                {
    DCHECK_GT(ArgumentCount(), 0);
    return ArgumentIndex(ArgumentCount() - 1);
  }
References ArgumentCount(), ArgumentIndex(), and DCHECK_GT.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSCallWithSpread(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), and v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread().
Member Data Documentation
kExtraInputCount
constexpr int v8::internal::compiler::JSCallOrConstructNode::kExtraInputCount [static], [constexpr]
Initial value:
= kTargetInputCount +
                                          kReceiverOrNewTargetInputCount +
                                          kFeedbackVectorInputCount
Definition at line 1378 of file js-operator.h.
Referenced by ArityForArgc(), and v8::internal::compiler::JSInliner::InlineCall().
kFeedbackVectorInputCount
constexpr int v8::internal::compiler::JSCallOrConstructNode::kFeedbackVectorInputCount = 1 [static], [constexpr]
Definition at line 1377 of file js-operator.h.
Referenced by v8::internal::compiler::JSInliner::InlineCall().
kFeedbackVectorIsLastInput
constexpr bool v8::internal::compiler::JSCallOrConstructNode::kFeedbackVectorIsLastInput = true [static], [constexpr]
Definition at line 1386 of file js-operator.h.
Referenced by FeedbackVectorIndexForArgc(), v8::internal::compiler::JSIntrinsicLowering::ReduceCall(), and v8::internal::compiler::JSCallReducer::ReduceReflectConstruct().
kHaveIdenticalLayouts
constexpr bool v8::internal::compiler::JSCallOrConstructNode::kHaveIdenticalLayouts = true [static], [constexpr]
Definition at line 1390 of file js-operator.h.
Referenced by v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), and v8::internal::compiler::JSInliner::ReduceJSCall().
kReceiverOrNewTargetInputCount
constexpr int v8::internal::compiler::JSCallOrConstructNode::kReceiverOrNewTargetInputCount = 1 [static], [constexpr]
Definition at line 1376 of file js-operator.h.
Referenced by v8::internal::compiler::JSInliner::CreateArtificialFrameState().
kTargetInputCount
constexpr int v8::internal::compiler::JSCallOrConstructNode::kTargetInputCount = 1 [static], [constexpr]
Definition at line 1375 of file js-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h