v8::internal::maglev::RegisterInput Class Reference
#include <maglev-ir.h>
Public Member Functions
RegisterInput (uint64_t bitfield, Register input)
Register input () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::NotIdempotent()
Private Types
using Base = FixedInputValueNodeT< 0, RegisterInput >
Private Attributes
const Register input_
Additional Inherited Members
Detailed Description
Definition at line 5506 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::RegisterInput::Base = FixedInputValueNodeT<0, RegisterInput> [private]
Definition at line 5507 of file maglev-ir.h.
Constructor & Destructor Documentation
RegisterInput()
v8::internal::maglev::RegisterInput::RegisterInput (uint64_t bitfield, Register input) [inline], [explicit]
Definition at line 5510 of file maglev-ir.h.
      : Base(bitfield), input_(input) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::RegisterInput::GenerateCode (MaglevAssembler * , const ProcessingState &)
input()
Register v8::internal::maglev::RegisterInput::input () const [inline]
Definition at line 5513 of file maglev-ir.h.
{ return input_; }
References input_.
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::RegisterInput::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7957 of file maglev-ir.cc.
                                                                           {
  os << "(" << input() << ")";
}
References input().
SetValueLocationConstraints()
void v8::internal::maglev::RegisterInput::SetValueLocationConstraints ()
Member Data Documentation
input_
const Register v8::internal::maglev::RegisterInput::input_ [private]
Definition at line 5522 of file maglev-ir.h.
Referenced by input().
kProperties
constexpr OpProperties v8::internal::maglev::RegisterInput::kProperties = OpProperties::NotIdempotent() [static], [constexpr]
Definition at line 5515 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc