v8::internal::ReadOnlyHeapImageDeserializer Class Reference
Static Public Member Functions
static void Deserialize (Isolate *isolate, SnapshotByteSource *source)
Private Types
using Bytecode = ro::Bytecode
Private Member Functions
ReadOnlyHeapImageDeserializer (Isolate *isolate, SnapshotByteSource *source)
void DeserializeImpl ()
void AllocatePage (bool fixed_offset)
void DeserializeSegment ()
Address Decode (ro::EncodedTagged encoded) const
void DecodeTaggedSlots (Address segment_start, const ro::BitSet &tagged_slots)
ReadOnlyPageMetadata * PageAt (size_t index) const
void DeserializeReadOnlyRootsTable ()
ReadOnlySpace * ro_space () const
Private Attributes
SnapshotByteSource *const source_
Isolate *const isolate_
Detailed Description
Definition at line 20 of file read-only-deserializer.cc.
Member Typedef Documentation
Bytecode
using v8::internal::ReadOnlyHeapImageDeserializer::Bytecode = ro::Bytecode [private]
Definition at line 27 of file read-only-deserializer.cc.
Constructor & Destructor Documentation
ReadOnlyHeapImageDeserializer()
v8::internal::ReadOnlyHeapImageDeserializer::ReadOnlyHeapImageDeserializer (Isolate * isolate, SnapshotByteSource * source) [inline], [private]
Definition at line 29 of file read-only-deserializer.cc.
      : source_(source), isolate_(isolate) {}
Member Function Documentation
AllocatePage()
void v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage (bool fixed_offset) [inline], [private]
Definition at line 58 of file read-only-deserializer.cc.
                                       {
    CHECK_EQ(V8_STATIC_ROOTS_BOOL, fixed_offset);
    size_t expected_page_index = static_cast<size_t>(source_->GetUint30());
    size_t actual_page_index = static_cast<size_t>(-1);
    size_t area_size_in_bytes = static_cast<size_t>(source_->GetUint30());
    if (fixed_offset) {
#ifdef V8_COMPRESS_POINTERS
      uint32_t compressed_page_addr = source_->GetUint32();
      Address pos = isolate_->cage_base() + compressed_page_addr;
      actual_page_index = ro_space()->AllocateNextPageAt(pos);
#else
      UNREACHABLE();
#endif // V8_COMPRESS_POINTERS
    } else {
      actual_page_index = ro_space()->AllocateNextPage();
    }
    CHECK_EQ(actual_page_index, expected_page_index);
    ro_space()->InitializePageForDeserialization(PageAt(actual_page_index),
                                                 area_size_in_bytes);
  }
References v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), v8::internal::Isolate::cage_base(), CHECK_EQ, v8::internal::SnapshotByteSource::GetUint30(), v8::internal::SnapshotByteSource::GetUint32(), v8::internal::ReadOnlySpace::InitializePageForDeserialization(), isolate_, PageAt(), ro_space(), source_, v8::internal::UNREACHABLE(), and V8_STATIC_ROOTS_BOOL.
Referenced by DeserializeImpl().
Decode()
Address v8::internal::ReadOnlyHeapImageDeserializer::Decode (ro::EncodedTagged encoded) const [inline], [private]
Definition at line 102 of file read-only-deserializer.cc.
                                                {
    ReadOnlyPageMetadata* page = PageAt(encoded.page_index);
    return page->OffsetToAddress(encoded.offset * kTaggedSize);
  }
References v8::internal::kTaggedSize, v8::internal::ro::EncodedTagged::offset, v8::internal::ReadOnlyPageMetadata::OffsetToAddress(), v8::internal::ro::EncodedTagged::page_index, and PageAt().
Referenced by DecodeTaggedSlots(), and DeserializeReadOnlyRootsTable().
DecodeTaggedSlots()
void v8::internal::ReadOnlyHeapImageDeserializer::DecodeTaggedSlots (Address segment_start, const ro::BitSet & tagged_slots) [inline], [private]
Definition at line 107 of file read-only-deserializer.cc.
                                                       {
    DCHECK(!V8_STATIC_ROOTS_BOOL);
    for (size_t i = 0; i < tagged_slots.size_in_bits(); i++) {
      // TODO(jgruber): Depending on sparseness, different iteration methods
      // could be more efficient.
      if (!tagged_slots.contains(static_cast<int>(i))) continue;
      Address slot_addr = segment_start + i * kTaggedSize;
      Address obj_addr = Decode(ro::EncodedTagged::FromAddress(slot_addr));
      Address obj_ptr = obj_addr + kHeapObjectTag;
      Tagged_t* dst = reinterpret_cast<Tagged_t*>(slot_addr);
      *dst = COMPRESS_POINTERS_BOOL
                 ? V8HeapCompressionScheme::CompressObject(obj_ptr)
                 : static_cast<Tagged_t>(obj_ptr);
    }
  }
References COMPRESS_POINTERS_BOOL, v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::ro::BitSet::contains(), v8::internal::DCHECK(), Decode(), v8::internal::ro::EncodedTagged::FromAddress(), v8::internal::kHeapObjectTag, v8::internal::kTaggedSize, v8::internal::ro::BitSet::size_in_bits(), and V8_STATIC_ROOTS_BOOL.
Referenced by DeserializeSegment().
Deserialize()
static void v8::internal::ReadOnlyHeapImageDeserializer::Deserialize (Isolate * isolate, SnapshotByteSource * source) [inline], [static]
Definition at line 22 of file read-only-deserializer.cc.
                                                                        {
    ReadOnlyHeapImageDeserializer{isolate, source}.DeserializeImpl();
  }
Referenced by v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate().
DeserializeImpl()
void v8::internal::ReadOnlyHeapImageDeserializer::DeserializeImpl () [inline], [private]
Definition at line 32 of file read-only-deserializer.cc.
                         {
    while (true) {
      int bytecode_as_int = source_->Get();
      DCHECK_LT(bytecode_as_int, ro::kNumberOfBytecodes);
      switch (static_cast<Bytecode>(bytecode_as_int)) {
        case Bytecode::kAllocatePage:
          AllocatePage(false);
          break;
        case Bytecode::kAllocatePageAt:
          AllocatePage(true);
          break;
        case Bytecode::kSegment:
          DeserializeSegment();
          break;
        case Bytecode::kRelocateSegment:
          UNREACHABLE(); // Handled together with kSegment.
        case Bytecode::kReadOnlyRootsTable:
          DeserializeReadOnlyRootsTable();
          break;
        case Bytecode::kFinalizeReadOnlySpace:
          ro_space()->FinalizeSpaceForDeserialization();
          return;
      }
    }
  }
References AllocatePage(), DCHECK_LT, DeserializeReadOnlyRootsTable(), DeserializeSegment(), v8::internal::ReadOnlySpace::FinalizeSpaceForDeserialization(), v8::internal::SnapshotByteSource::Get(), v8::internal::ro::kAllocatePage, v8::internal::ro::kAllocatePageAt, v8::internal::ro::kFinalizeReadOnlySpace, v8::internal::ro::kNumberOfBytecodes, v8::internal::ro::kReadOnlyRootsTable, v8::internal::ro::kRelocateSegment, v8::internal::ro::kSegment, ro_space(), source_, and v8::internal::UNREACHABLE().
DeserializeReadOnlyRootsTable()
void v8::internal::ReadOnlyHeapImageDeserializer::DeserializeReadOnlyRootsTable () [inline], [private]
Definition at line 130 of file read-only-deserializer.cc.
                                       {
    ReadOnlyRoots roots(isolate_);
    if (V8_STATIC_ROOTS_BOOL) {
      roots.InitFromStaticRootsTable(isolate_->cage_base());
    } else {
      for (size_t i = 0; i < ReadOnlyRoots::kEntriesCount; i++) {
        uint32_t encoded_as_int = source_->GetUint32();
        Address rudolf = Decode(ro::EncodedTagged::FromUint32(encoded_as_int));
        roots.read_only_roots_[i] = rudolf + kHeapObjectTag;
      }
    }
  }
References v8::internal::Isolate::cage_base(), Decode(), v8::internal::ro::EncodedTagged::FromUint32(), v8::internal::SnapshotByteSource::GetUint32(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ReadOnlyRoots::InitFromStaticRootsTable(), isolate_, v8::internal::ReadOnlyRoots::kEntriesCount, v8::internal::kHeapObjectTag, v8::internal::ReadOnlyRoots::read_only_roots_, source_, and V8_STATIC_ROOTS_BOOL.
Referenced by DeserializeImpl().
DeserializeSegment()
void v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment () [inline], [private]
Definition at line 79 of file read-only-deserializer.cc.
                            {
    uint32_t page_index = source_->GetUint30();
    ReadOnlyPageMetadata* page = PageAt(page_index);
    // Copy over raw contents.
    Address start = page->area_start() + source_->GetUint30();
    int size_in_bytes = source_->GetUint30();
    CHECK_LE(start + size_in_bytes, page->area_end());
    source_->CopyRaw(reinterpret_cast<void*>(start), size_in_bytes);
    if (!V8_STATIC_ROOTS_BOOL) {
      uint8_t relocate_marker_bytecode = source_->Get();
      CHECK_EQ(relocate_marker_bytecode, Bytecode::kRelocateSegment);
      int tagged_slots_size_in_bits = size_in_bytes / kTaggedSize;
      // The const_cast is unfortunate, but we promise not to mutate data.
      uint8_t* data =
          const_cast<uint8_t*>(source_->data() + source_->position());
      ro::BitSet tagged_slots(data, tagged_slots_size_in_bits);
      DecodeTaggedSlots(start, tagged_slots);
      source_->Advance(static_cast<int>(tagged_slots.size_in_bytes()));
    }
  }
References v8::internal::SnapshotByteSource::Advance(), v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_start(), CHECK_EQ, CHECK_LE, v8::internal::SnapshotByteSource::CopyRaw(), v8::internal::SnapshotByteSource::data(), DecodeTaggedSlots(), v8::internal::SnapshotByteSource::Get(), v8::internal::SnapshotByteSource::GetUint30(), v8::internal::ro::kRelocateSegment, v8::internal::kTaggedSize, PageAt(), v8::internal::SnapshotByteSource::position(), v8::internal::ro::BitSet::size_in_bytes(), source_, and V8_STATIC_ROOTS_BOOL.
Referenced by DeserializeImpl().
PageAt()
ReadOnlyPageMetadata* v8::internal::ReadOnlyHeapImageDeserializer::PageAt (size_t index) const [inline], [private]
Definition at line 125 of file read-only-deserializer.cc.
                                                   {
    DCHECK_LT(index, ro_space()->pages().size());
    return ro_space()->pages()[index];
  }
References DCHECK_LT, v8::internal::index, v8::internal::ReadOnlySpace::pages(), ro_space(), and size().
Referenced by AllocatePage(), Decode(), and DeserializeSegment().
ro_space()
ReadOnlySpace* v8::internal::ReadOnlyHeapImageDeserializer::ro_space () const [inline], [private]
Definition at line 143 of file read-only-deserializer.cc.
                                  {
    return isolate_->read_only_heap()->read_only_space();
  }
References isolate_, v8::internal::Isolate::read_only_heap(), and v8::internal::ReadOnlyHeap::read_only_space().
Referenced by AllocatePage(), DeserializeImpl(), and PageAt().
Member Data Documentation
isolate_
Isolate* const v8::internal::ReadOnlyHeapImageDeserializer::isolate_ [private]
Definition at line 148 of file read-only-deserializer.cc.
Referenced by AllocatePage(), DeserializeReadOnlyRootsTable(), and ro_space().
source_
SnapshotByteSource* const v8::internal::ReadOnlyHeapImageDeserializer::source_ [private]
Definition at line 147 of file read-only-deserializer.cc.
Referenced by AllocatePage(), DeserializeImpl(), DeserializeReadOnlyRootsTable(), and DeserializeSegment().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-deserializer.cc