v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror Class Reference
Public Member Functions
FunctionMirror (v8::Local< v8::Function > value)
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< PropertyPreview > *result) const override
void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *preview) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Additional Inherited Members
Detailed Description
Definition at line 892 of file value-mirror.cc.
Constructor & Destructor Documentation
FunctionMirror()
v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::FunctionMirror (v8::Local< v8::Function > value) [inline], [explicit]
Definition at line 894 of file value-mirror.cc.
      : ValueMirrorBase(v8::Isolate::GetCurrent(), value) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 945 of file value-mirror.cc.
                                                                     {
    bool isKnown;
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    *result = duplicateTracker.LinkExistingOrCreate(value, &isKnown);
    if (isKnown) {
      return Response::Success();
    }
    (*result)->setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Function);
    return Response::Success();
  }
References v8::Isolate::GetCurrent(), v8_inspector::V8SerializationDuplicateTracker::LinkExistingOrCreate(), v8::base::internal::result, and v8::internal::value.
buildEntryPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * preview) const [inline], [override]
Definition at line 931 of file value-mirror.cc.
                                                            {
    v8::Local<v8::Function> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Function>();
    *preview =
        ObjectPreview::create()
            .setType(RemoteObject::TypeEnum::Function)
            .setDescription(descriptionForFunction(value))
            .setOverflow(false)
            .setProperties(std::make_unique<protocol::Array<PropertyPreview>>())
            .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForFunction(), v8::Isolate::GetCurrent(), and v8::internal::value.
buildPropertyPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< PropertyPreview > * result) const [inline], [override]
Definition at line 922 of file value-mirror.cc.
                                                             {
    *result = PropertyPreview::create()
                  .setName(name)
                  .setType(RemoteObject::TypeEnum::Function)
                  .setValue(String16())
                  .build();
  }
References name, and v8::base::internal::result.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::FunctionMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 897 of file value-mirror.cc.
                                                          {
    v8::Local<v8::Function> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Function>();
    // TODO(alph): drop this functionality.
    if (wrapOptions.mode == WrapMode::kJson) {
      std::unique_ptr<protocol::Value> protocolValue;
      Response response = toProtocolValue(context, value, &protocolValue);
      if (!response.IsSuccess()) return response;
      *result = RemoteObject::create()
                    .setType(RemoteObject::TypeEnum::Function)
                    .setValue(std::move(protocolValue))
                    .build();
    } else {
      *result = RemoteObject::create()
                    .setType(RemoteObject::TypeEnum::Function)
                    .setClassName(toProtocolStringWithTypeCheck(
                        v8::Isolate::GetCurrent(), value->GetConstructorName()))
                    .setDescription(descriptionForFunction(value))
                    .build();
    }
    return Response::Success();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForFunction(), v8::Isolate::GetCurrent(), v8_inspector::kJson, v8_inspector::WrapOptions::mode, v8::base::internal::result, v8_inspector::toProtocolStringWithTypeCheck(), v8_inspector::toProtocolValue(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc