v8::internal::compiler::FeedbackVectorRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< FeedbackVector > object () const
SharedFunctionInfoRef shared_function_info (JSHeapBroker *broker) const
FeedbackCellRef GetClosureFeedbackCell (JSHeapBroker *broker, int index) const
bool was_once_deoptimized () const
Detailed Description
Definition at line 852 of file heap-refs.h.
Member Function Documentation
GetClosureFeedbackCell()
FeedbackCellRef v8::internal::compiler::FeedbackVectorRef::GetClosureFeedbackCell (JSHeapBroker * broker, int index) const
Definition at line 1311 of file heap-refs.cc.
                                                                           {
  return MakeRefAssumeMemoryFence(broker,
                                  object()->closure_feedback_cell(index));
}
References broker(), v8::internal::index, and v8::internal::compiler::MakeRefAssumeMemoryFence().
object()
IndirectHandle<FeedbackVector> v8::internal::compiler::FeedbackVectorRef::object () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::maglev::MaglevCompiler::Compile(), and was_once_deoptimized().
shared_function_info()
SharedFunctionInfoRef v8::internal::compiler::FeedbackVectorRef::shared_function_info (JSHeapBroker * broker) const
Definition at line 2353 of file heap-refs.cc.
                                {
  // Immutable after initialization.
  return MakeRefAssumeMemoryFence(broker, object()->shared_function_info());
}
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
was_once_deoptimized()
bool v8::internal::compiler::FeedbackVectorRef::was_once_deoptimized () const
Definition at line 1792 of file heap-refs.cc.
                                                   {
  return object()->was_once_deoptimized();
}
References object().
Referenced by v8::internal::maglev::LoopOptimizationProcessor::LoopOptimizationProcessor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc