v8::platform::tracing::TracingController Class Reference
#include <v8-tracing.h>
Public Types
enum CategoryGroupEnabledFlags { ENABLED_FOR_RECORDING = 1 << 0
, ENABLED_FOR_EVENT_CALLBACK = 1 << 2
, ENABLED_FOR_ETW_EXPORT = 1 << 3
 }
Public Member Functions
TracingController ()
~TracingController () override
void Initialize (TraceBuffer *trace_buffer)
const uint8_t * GetCategoryGroupEnabled (const char *category_group) override
uint64_t AddTraceEvent (char phase, const uint8_t *category_enabled_flag, const char *name, const char *scope, uint64_t id, uint64_t bind_id, int32_t num_args, const char **arg_names, const uint8_t *arg_types, const uint64_t *arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > *arg_convertables, unsigned int flags) override
uint64_t AddTraceEventWithTimestamp (char phase, const uint8_t *category_enabled_flag, const char *name, const char *scope, uint64_t id, uint64_t bind_id, int32_t num_args, const char **arg_names, const uint8_t *arg_types, const uint64_t *arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > *arg_convertables, unsigned int flags, int64_t timestamp) override
void UpdateTraceEventDuration (const uint8_t *category_enabled_flag, const char *name, uint64_t handle) override
void AddTraceStateObserver (v8::TracingController::TraceStateObserver *observer) override
void RemoveTraceStateObserver (v8::TracingController::TraceStateObserver *observer) override
void StartTracing (TraceConfig *trace_config)
void StopTracing ()
Static Public Member Functions
static const char * GetCategoryGroupName (const uint8_t *category_enabled_flag)
Protected Member Functions
virtual int64_t CurrentTimestampMicroseconds ()
virtual int64_t CurrentCpuTimestampMicroseconds ()
Private Member Functions
void UpdateCategoryGroupEnabledFlag (size_t category_index)
void UpdateCategoryGroupEnabledFlags ()
TracingController (const TracingController &)=delete
void operator= (const TracingController &)=delete
Private Attributes
std::unique_ptr< base::Mutex > mutex_
std::unique_ptr< TraceConfig > trace_config_
std::atomic_bool recording_ {false}
std::unordered_set< v8::TracingController::TraceStateObserver * > observers_
std::unique_ptr< TraceBuffer > trace_buffer_
Detailed Description
Definition at line 234 of file v8-tracing.h.
Member Enumeration Documentation
CategoryGroupEnabledFlags
enum v8::platform::tracing::TracingController::CategoryGroupEnabledFlags
Enumerator
ENABLED_FOR_RECORDING
ENABLED_FOR_EVENT_CALLBACK
ENABLED_FOR_ETW_EXPORT
Definition at line 252 of file v8-tracing.h.
                                 {
    // Category group enabled for the recording mode.
    ENABLED_FOR_RECORDING = 1 << 0,
    // Category group enabled by SetEventCallbackEnabled().
    ENABLED_FOR_EVENT_CALLBACK = 1 << 2,
    // Category group enabled to export events to ETW.
    ENABLED_FOR_ETW_EXPORT = 1 << 3
  };
Constructor & Destructor Documentation
TracingController() [1/2]
v8::platform::tracing::TracingController::TracingController ()
Definition at line 72 of file tracing-controller.cc.
{ mutex_.reset(new base::Mutex()); }
References mutex_.
 TracingController()
v8::platform::tracing::TracingController::~TracingController () [override]
Definition at line 74 of file tracing-controller.cc.
                                      {
  StopTracing();
#if !defined(V8_USE_PERFETTO)
  {
    // Free memory for category group names allocated via strdup.
    base::MutexGuard lock(mutex_.get());
    for (size_t i = g_category_index - 1; i >= g_num_builtin_categories; --i) {
      const char* group = g_category_groups[i];
      g_category_groups[i] = nullptr;
      free(const_cast<char*>(group));
    }
    g_category_index = g_num_builtin_categories;
  }
#endif // !defined(V8_USE_PERFETTO)
}
References v8::platform::tracing::g_category_groups, v8::platform::tracing::g_category_index, v8::platform::tracing::g_num_builtin_categories, v8::internal::anonymous_namespace{json-stringifier.cc}::i, mutex_, and StopTracing().
TracingController() [2/2]
v8::platform::tracing::TracingController::TracingController (const TracingController &) [private], [delete]
Member Function Documentation
AddTraceEvent()
uint64_t v8::platform::tracing::TracingController::AddTraceEvent (char phase, const uint8_t * category_enabled_flag, const char * name, const char * scope, uint64_t id, uint64_t bind_id, int32_t num_args, const char ** arg_names, const uint8_t * arg_types, const uint64_t * arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > * arg_convertables, unsigned int flags) [override]
AddTraceEventWithTimestamp()
uint64_t v8::platform::tracing::TracingController::AddTraceEventWithTimestamp (char phase, const uint8_t * category_enabled_flag, const char * name, const char * scope, uint64_t id, uint64_t bind_id, int32_t num_args, const char ** arg_names, const uint8_t * arg_types, const uint64_t * arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > * arg_convertables, unsigned int flags, int64_t timestamp) [override]
AddTraceStateObserver()
void v8::platform::tracing::TracingController::AddTraceStateObserver (v8::TracingController::TraceStateObserver * observer) [override]
Definition at line 345 of file tracing-controller.cc.
                                                     {
  {
    base::MutexGuard lock(mutex_.get());
    observers_.insert(observer);
    if (!recording_.load(std::memory_order_acquire)) return;
  }
  // Fire the observer if recording is already in progress.
  observer->OnTraceEnabled();
}
References mutex_, observers_, v8::TracingController::TraceStateObserver::OnTraceEnabled(), and recording_.
CurrentCpuTimestampMicroseconds()
int64_t v8::platform::tracing::TracingController::CurrentCpuTimestampMicroseconds () [protected], [virtual]
Definition at line 111 of file tracing-controller.cc.
                                                           {
  return base::ThreadTicks::Now().ToInternalValue();
}
References v8::base::ThreadTicks::Now(), and v8::base::time_internal::TimeBase< TimeClass >::ToInternalValue().
Referenced by UpdateTraceEventDuration().
CurrentTimestampMicroseconds()
int64_t v8::platform::tracing::TracingController::CurrentTimestampMicroseconds () [protected], [virtual]
Definition at line 107 of file tracing-controller.cc.
                                                        {
  return base::TimeTicks::Now().ToInternalValue();
}
References v8::base::TimeTicks::Now(), and v8::base::time_internal::TimeBase< TimeClass >::ToInternalValue().
Referenced by UpdateTraceEventDuration().
GetCategoryGroupEnabled()
const uint8_t * v8::platform::tracing::TracingController::GetCategoryGroupEnabled (const char * category_group) [override]
Definition at line 294 of file tracing-controller.cc.
                                {
  // Check that category group does not contain double quote
  DCHECK(!strchr(category_group, '"'));
  // The g_category_groups is append only, avoid using a lock for the fast path.
  size_t category_index = base::Acquire_Load(&g_category_index);
  // Search for pre-existing category group.
  for (size_t i = 0; i < category_index; ++i) {
    if (strcmp(g_category_groups[i], category_group) == 0) {
      return &g_category_group_enabled[i];
    }
  }
  // Slow path. Grab the lock.
  base::MutexGuard lock(mutex_.get());
  // Check the list again with lock in hand.
  unsigned char* category_group_enabled = nullptr;
  category_index = base::Acquire_Load(&g_category_index);
  for (size_t i = 0; i < category_index; ++i) {
    if (strcmp(g_category_groups[i], category_group) == 0) {
      return &g_category_group_enabled[i];
    }
  }
  // Create a new category group.
  // Check that there is a slot for the new category_group.
  DCHECK(category_index < kMaxCategoryGroups);
  if (category_index < kMaxCategoryGroups) {
    // Don't hold on to the category_group pointer, so that we can create
    // category groups with strings not known at compile time (this is
    // required by SetWatchEvent).
    const char* new_group = strdup(category_group);
    g_category_groups[category_index] = new_group;
    DCHECK(!g_category_group_enabled[category_index]);
    // Note that if both included and excluded patterns in the
    // TraceConfig are empty, we exclude nothing,
    // thereby enabling this category group.
    UpdateCategoryGroupEnabledFlag(category_index);
    category_group_enabled = &g_category_group_enabled[category_index];
    // Update the max index now.
    base::Release_Store(&g_category_index, category_index + 1);
  } else {
    category_group_enabled =
        &g_category_group_enabled[g_category_categories_exhausted];
  }
  return category_group_enabled;
}
References v8::base::Acquire_Load(), DCHECK, v8::platform::tracing::g_category_categories_exhausted, v8::platform::tracing::g_category_group_enabled, v8::platform::tracing::g_category_groups, v8::platform::tracing::g_category_index, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::platform::tracing::kMaxCategoryGroups, mutex_, v8::base::Release_Store(), and UpdateCategoryGroupEnabledFlag().
GetCategoryGroupName()
const char * v8::platform::tracing::TracingController::GetCategoryGroupName (const uint8_t * category_enabled_flag) [static]
Definition at line 164 of file tracing-controller.cc.
                                           {
  // Calculate the index of the category group by finding
  // category_group_enabled in g_category_group_enabled array.
  uintptr_t category_begin =
      reinterpret_cast<uintptr_t>(g_category_group_enabled);
  uintptr_t category_ptr = reinterpret_cast<uintptr_t>(category_group_enabled);
  // Check for out of bounds category pointers.
  DCHECK(category_ptr >= category_begin &&
         category_ptr < reinterpret_cast<uintptr_t>(g_category_group_enabled +
                                                    kMaxCategoryGroups));
  uintptr_t category_index =
      (category_ptr - category_begin) / sizeof(g_category_group_enabled[0]);
  return g_category_groups[category_index];
}
References DCHECK, v8::platform::tracing::g_category_group_enabled, v8::platform::tracing::g_category_groups, and v8::platform::tracing::kMaxCategoryGroups.
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent().
Initialize()
void v8::platform::tracing::TracingController::Initialize (TraceBuffer * trace_buffer)
Definition at line 103 of file tracing-controller.cc.
                                                            {
  trace_buffer_.reset(trace_buffer);
}
References trace_buffer_.
Referenced by v8::platform::DefaultPlatform::DefaultPlatform().
operator=()
void v8::platform::tracing::TracingController::operator= (const TracingController &) [private], [delete]
RemoveTraceStateObserver()
void v8::platform::tracing::TracingController::RemoveTraceStateObserver (v8::TracingController::TraceStateObserver * observer) [override]
Definition at line 356 of file tracing-controller.cc.
                                                     {
  base::MutexGuard lock(mutex_.get());
  DCHECK(observers_.find(observer) != observers_.end());
  observers_.erase(observer);
}
References DCHECK, mutex_, and observers_.
StartTracing()
void v8::platform::tracing::TracingController::StartTracing (TraceConfig * trace_config)
Definition at line 181 of file tracing-controller.cc.
                                                              {
#ifdef V8_USE_PERFETTO
  DCHECK_NOT_NULL(output_stream_);
  DCHECK(output_stream_->good());
  perfetto::trace_processor::Config processor_config;
  trace_processor_ =
      perfetto::trace_processor::TraceProcessorStorage::CreateInstance(
          processor_config);
  ::perfetto::TraceConfig perfetto_trace_config;
  perfetto_trace_config.add_buffers()->set_size_kb(4096);
  auto ds_config = perfetto_trace_config.add_data_sources()->mutable_config();
  ds_config->set_name("track_event");
  perfetto::protos::gen::TrackEventConfig te_config;
  te_config.add_disabled_categories("*");
  for (const auto& category : trace_config->GetEnabledCategories())
    te_config.add_enabled_categories(category);
  ds_config->set_track_event_config_raw(te_config.SerializeAsString());
  tracing_session_ =
      perfetto::Tracing::NewTrace(perfetto::BackendType::kUnspecifiedBackend);
  tracing_session_->Setup(perfetto_trace_config);
  tracing_session_->StartBlocking();
#endif // V8_USE_PERFETTO
  trace_config_.reset(trace_config);
  recording_.store(true, std::memory_order_release);
#ifndef V8_USE_PERFETTO
  std::unordered_set<v8::TracingController::TraceStateObserver*> observers_copy;
  {
    base::MutexGuard lock(mutex_.get());
    UpdateCategoryGroupEnabledFlags();
    observers_copy = observers_;
  }
  for (auto o : observers_copy) {
    o->OnTraceEnabled();
  }
#endif
}
References DCHECK, DCHECK_NOT_NULL, v8::platform::tracing::TraceConfig::GetEnabledCategories(), mutex_, observers_, recording_, trace_config_, and UpdateCategoryGroupEnabledFlags().
Referenced by v8::Shell::Main().
StopTracing()
void v8::platform::tracing::TracingController::StopTracing ()
Definition at line 223 of file tracing-controller.cc.
                                    {
  bool expected = true;
  if (!recording_.compare_exchange_strong(expected, false)) {
    return;
  }
#ifndef V8_USE_PERFETTO
  UpdateCategoryGroupEnabledFlags();
  std::unordered_set<v8::TracingController::TraceStateObserver*> observers_copy;
  {
    base::MutexGuard lock(mutex_.get());
    observers_copy = observers_;
  }
  for (auto o : observers_copy) {
    o->OnTraceDisabled();
  }
#endif
#ifdef V8_USE_PERFETTO
  tracing_session_->StopBlocking();
  std::vector<char> trace = tracing_session_->ReadTraceBlocking();
  std::unique_ptr<uint8_t[]> trace_bytes(new uint8_t[trace.size()]);
  std::copy(&trace[0], &trace[0] + trace.size(), &trace_bytes[0]);
  trace_processor_->Parse(std::move(trace_bytes), trace.size());
  trace_processor_->NotifyEndOfFile();
  JsonOutputWriter output_writer(output_stream_);
  auto status = perfetto::trace_processor::json::ExportJson(
      trace_processor_.get(), &output_writer, nullptr, nullptr, nullptr);
  DCHECK(status.ok());
  if (listener_for_testing_) listener_for_testing_->ParseFromArray(trace);
  trace_processor_.reset();
#else
  {
    base::MutexGuard lock(mutex_.get());
    DCHECK(trace_buffer_);
    trace_buffer_->Flush();
  }
#endif // V8_USE_PERFETTO
}
References DCHECK, mutex_, observers_, recording_, v8::internal::status, trace_buffer_, and UpdateCategoryGroupEnabledFlags().
Referenced by v8::Shell::Main(), and ~TracingController().
UpdateCategoryGroupEnabledFlag()
void v8::platform::tracing::TracingController::UpdateCategoryGroupEnabledFlag (size_t category_index) [private]
Definition at line 267 of file tracing-controller.cc.
                                                                            {
  unsigned char enabled_flag = 0;
  const char* category_group = g_category_groups[category_index];
  if (recording_.load(std::memory_order_acquire) &&
      trace_config_->IsCategoryGroupEnabled(category_group)) {
    enabled_flag |= ENABLED_FOR_RECORDING;
  }
  // TODO(fmeawad): EventCallback and ETW modes are not yet supported in V8.
  // TODO(primiano): this is a temporary workaround for catapult:#2341,
  // to guarantee that metadata events are always added even if the category
  // filter is "-*". See crbug.com/618054 for more details and long-term fix.
  if (recording_.load(std::memory_order_acquire) &&
      !strcmp(category_group, "__metadata")) {
    enabled_flag |= ENABLED_FOR_RECORDING;
  }
  base::Relaxed_Store(reinterpret_cast<base::Atomic8*>(
                          g_category_group_enabled + category_index),
                      enabled_flag);
}
References ENABLED_FOR_RECORDING, v8::platform::tracing::g_category_group_enabled, v8::platform::tracing::g_category_groups, recording_, v8::base::Relaxed_Store(), and trace_config_.
Referenced by GetCategoryGroupEnabled(), and UpdateCategoryGroupEnabledFlags().
UpdateCategoryGroupEnabledFlags()
void v8::platform::tracing::TracingController::UpdateCategoryGroupEnabledFlags () [private]
Definition at line 289 of file tracing-controller.cc.
                                                        {
  size_t category_index = base::Acquire_Load(&g_category_index);
  for (size_t i = 0; i < category_index; i++) UpdateCategoryGroupEnabledFlag(i);
}
References v8::base::Acquire_Load(), v8::platform::tracing::g_category_index, and UpdateCategoryGroupEnabledFlag().
Referenced by StartTracing(), and StopTracing().
UpdateTraceEventDuration()
void v8::platform::tracing::TracingController::UpdateTraceEventDuration (const uint8_t * category_enabled_flag, const char * name, uint64_t handle) [override]
Definition at line 154 of file tracing-controller.cc.
                                                                             {
  int64_t now_us = CurrentTimestampMicroseconds();
  int64_t cpu_now_us = CurrentCpuTimestampMicroseconds();
  TraceObject* trace_object = trace_buffer_->GetEventByHandle(handle);
  if (!trace_object) return;
  trace_object->UpdateDuration(now_us, cpu_now_us);
}
References CurrentCpuTimestampMicroseconds(), CurrentTimestampMicroseconds(), v8::internal::handle(), trace_buffer_, and v8::platform::tracing::TraceObject::UpdateDuration().
Member Data Documentation
mutex_
std::unique_ptr<base::Mutex> v8::platform::tracing::TracingController::mutex_ [private]
Definition at line 306 of file v8-tracing.h.
Referenced by AddTraceStateObserver(), GetCategoryGroupEnabled(), RemoveTraceStateObserver(), StartTracing(), StopTracing(), TracingController(), and ~TracingController().
observers_
std::unordered_set<v8::TracingController::TraceStateObserver*> v8::platform::tracing::TracingController::observers_ [private]
Definition at line 317 of file v8-tracing.h.
Referenced by AddTraceStateObserver(), RemoveTraceStateObserver(), StartTracing(), and StopTracing().
recording_
std::atomic_bool v8::platform::tracing::TracingController::recording_ {false} [private]
Definition at line 308 of file v8-tracing.h.
Referenced by AddTraceStateObserver(), StartTracing(), StopTracing(), and UpdateCategoryGroupEnabledFlag().
trace_buffer_
std::unique_ptr<TraceBuffer> v8::platform::tracing::TracingController::trace_buffer_ [private]
Definition at line 318 of file v8-tracing.h.
Referenced by Initialize(), StopTracing(), and UpdateTraceEventDuration().
trace_config_
std::unique_ptr<TraceConfig> v8::platform::tracing::TracingController::trace_config_ [private]
Definition at line 307 of file v8-tracing.h.
Referenced by StartTracing(), and UpdateCategoryGroupEnabledFlag().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/libplatform/v8-tracing.h
/mnt/V8SourceCode/src/libplatform/tracing/tracing-controller.cc