v8::internal::compiler::turboshaft::CompareSequence Class Reference
Public Member Functions
void InitialCompare (OpIndex op, OpIndex l, OpIndex r, RegisterRepresentation rep)
bool HasCompare () const
OpIndex cmp () const
OpIndex left () const
OpIndex right () const
InstructionCode opcode () const
uint32_t num_ccmps () const
FlagsContinuation::compare_chain_t & ccmps ()
void AddConditionalCompare (RegisterRepresentation rep, FlagsCondition ccmp_condition, FlagsCondition default_flags, OpIndex ccmp_lhs, OpIndex ccmp_rhs)
bool IsFloatCmp () const
Private Member Functions
InstructionCode GetOpcode (RegisterRepresentation rep) const
Private Attributes
OpIndex cmp_
OpIndex left_
OpIndex right_
InstructionCode opcode_
FlagsContinuation::compare_chain_t ccmps_
uint32_t num_ccmps_ = 0
Detailed Description
Definition at line 1364 of file instruction-selector-arm64.cc.
Member Function Documentation
AddConditionalCompare()
void v8::internal::compiler::turboshaft::CompareSequence::AddConditionalCompare (RegisterRepresentation rep, FlagsCondition ccmp_condition, FlagsCondition default_flags, OpIndex ccmp_lhs, OpIndex ccmp_rhs) [inline]
Definition at line 1381 of file instruction-selector-arm64.cc.
                                               {
    InstructionCode code = GetOpcode(rep);
    ccmps_.at(num_ccmps_) = FlagsContinuation::ConditionalCompare{
        code, ccmp_condition, default_flags, ccmp_lhs, ccmp_rhs};
    ++num_ccmps_;
  }
References code.
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
ccmps()
FlagsContinuation::compare_chain_t& v8::internal::compiler::turboshaft::CompareSequence::ccmps () [inline]
Definition at line 1380 of file instruction-selector-arm64.cc.
{ return ccmps_; }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
cmp()
OpIndex v8::internal::compiler::turboshaft::CompareSequence::cmp () const [inline]
Definition at line 1375 of file instruction-selector-arm64.cc.
{ return cmp_; }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
GetOpcode()
InstructionCode v8::internal::compiler::turboshaft::CompareSequence::GetOpcode (RegisterRepresentation rep) const [inline], [private]
Definition at line 1395 of file instruction-selector-arm64.cc.
                                                              {
    switch (rep.MapTaggedToWord().value()) {
      case RegisterRepresentation::Word32():
        return kArm64Cmp32;
      case RegisterRepresentation::Word64():
        return kArm64Cmp;
      case RegisterRepresentation::Float32():
        return kArm64Float32Cmp;
      case RegisterRepresentation::Float64():
        return kArm64Float64Cmp;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::RegisterRepresentation::MapTaggedToWord(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::RegisterRepresentation::value(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
HasCompare()
bool v8::internal::compiler::turboshaft::CompareSequence::HasCompare () const [inline]
Definition at line 1374 of file instruction-selector-arm64.cc.
{ return cmp_.valid(); }
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
InitialCompare()
void v8::internal::compiler::turboshaft::CompareSequence::InitialCompare (OpIndex op, OpIndex l, OpIndex r, RegisterRepresentation rep) [inline]
Definition at line 1366 of file instruction-selector-arm64.cc.
                                                  {
    DCHECK(!HasCompare());
    cmp_ = op;
    left_ = l;
    right_ = r;
    opcode_ = GetOpcode(rep);
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::l.
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps().
IsFloatCmp()
bool v8::internal::compiler::turboshaft::CompareSequence::IsFloatCmp () const [inline]
Definition at line 1390 of file instruction-selector-arm64.cc.
                          {
    return opcode() == kArm64Float32Cmp || opcode() == kArm64Float64Cmp;
  }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
left()
OpIndex v8::internal::compiler::turboshaft::CompareSequence::left () const [inline]
Definition at line 1376 of file instruction-selector-arm64.cc.
{ return left_; }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
num_ccmps()
uint32_t v8::internal::compiler::turboshaft::CompareSequence::num_ccmps () const [inline]
Definition at line 1379 of file instruction-selector-arm64.cc.
{ return num_ccmps_; }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared().
opcode()
InstructionCode v8::internal::compiler::turboshaft::CompareSequence::opcode () const [inline]
Definition at line 1378 of file instruction-selector-arm64.cc.
{ return opcode_; }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
right()
OpIndex v8::internal::compiler::turboshaft::CompareSequence::right () const [inline]
Definition at line 1377 of file instruction-selector-arm64.cc.
{ return right_; }
Referenced by v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), and v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet().
Member Data Documentation
ccmps_
FlagsContinuation::compare_chain_t v8::internal::compiler::turboshaft::CompareSequence::ccmps_ [private]
Definition at line 1414 of file instruction-selector-arm64.cc.
cmp_
OpIndex v8::internal::compiler::turboshaft::CompareSequence::cmp_ [private]
Definition at line 1410 of file instruction-selector-arm64.cc.
left_
OpIndex v8::internal::compiler::turboshaft::CompareSequence::left_ [private]
Definition at line 1411 of file instruction-selector-arm64.cc.
num_ccmps_
uint32_t v8::internal::compiler::turboshaft::CompareSequence::num_ccmps_ = 0 [private]
Definition at line 1415 of file instruction-selector-arm64.cc.
opcode_
InstructionCode v8::internal::compiler::turboshaft::CompareSequence::opcode_ [private]
Definition at line 1413 of file instruction-selector-arm64.cc.
right_
OpIndex v8::internal::compiler::turboshaft::CompareSequence::right_ [private]
Definition at line 1412 of file instruction-selector-arm64.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-selector-arm64.cc