v8::internal::HashTableBase Class Reference
#include <hash-table.h>
Public Member Functions
uint32_t NumberOfElements () const
uint32_t NumberOfDeletedElements () const
uint32_t Capacity () const
InternalIndex::Range IterateEntries () const
void ElementAdded ()
void ElementRemoved ()
void ElementsRemoved (int n)
void SetInitialNumberOfElements (int nof)
Static Public Member Functions
static uint32_t ComputeCapacity (uint32_t at_least_space_for)
Static Public Attributes
static const int kNumberOfElementsIndex = 0
static const int kNumberOfDeletedElementsIndex = 1
static const int kCapacityIndex = 2
static const int kPrefixStartIndex = 3
static const uint32_t kMinCapacity = 4
Protected Member Functions
void SetNumberOfElements (int nof)
void SetNumberOfDeletedElements (int nod)
Static Protected Member Functions
static InternalIndex NextProbe (InternalIndex last, uint32_t number, uint32_t size)
Detailed Description
Definition at line 68 of file hash-table.h.
Member Function Documentation
Capacity()
uint32_t v8::internal::HashTableBase::Capacity () const [inline]
Definition at line 62 of file hash-table-inl.h.
                                       {
  return Cast<Smi>(get(kCapacityIndex)).value();
}
References kCapacityIndex.
Referenced by IterateEntries().
ComputeCapacity()
uint32_t v8::internal::HashTableBase::ComputeCapacity (uint32_t at_least_space_for) [inline], [static]
Definition at line 85 of file hash-table-inl.h.
                                                                   {
  // Add 50% slack to make slot collisions sufficiently unlikely.
  // See matching computation in HashTable::HasSufficientCapacityToAdd().
  // Must be kept in sync with CodeStubAssembler::HashTableComputeCapacity().
  uint32_t raw_cap = at_least_space_for + (at_least_space_for >> 1);
  uint32_t capacity = base::bits::RoundUpToPowerOfTwo32(raw_cap);
  return std::max({capacity, kMinCapacity});
}
References kMinCapacity.
ElementAdded()
void v8::internal::HashTableBase::ElementAdded () [inline]
Definition at line 70 of file hash-table-inl.h.
                                 {
  SetNumberOfElements(NumberOfElements() + 1);
}
References NumberOfElements(), and SetNumberOfElements().
ElementRemoved()
void v8::internal::HashTableBase::ElementRemoved () [inline]
Definition at line 74 of file hash-table-inl.h.
                                   {
  SetNumberOfElements(NumberOfElements() - 1);
  SetNumberOfDeletedElements(NumberOfDeletedElements() + 1);
}
References NumberOfDeletedElements(), NumberOfElements(), SetNumberOfDeletedElements(), and SetNumberOfElements().
ElementsRemoved()
void v8::internal::HashTableBase::ElementsRemoved (int n) [inline]
Definition at line 79 of file hash-table-inl.h.
                                         {
  SetNumberOfElements(NumberOfElements() - n);
  SetNumberOfDeletedElements(NumberOfDeletedElements() + n);
}
References NumberOfDeletedElements(), NumberOfElements(), SetNumberOfDeletedElements(), and SetNumberOfElements().
IterateEntries()
InternalIndex::Range v8::internal::HashTableBase::IterateEntries () const [inline]
Definition at line 66 of file hash-table-inl.h.
                                                       {
  return InternalIndex::Range(Capacity());
}
References Capacity(), and v8::internal::compiler::turboshaft::Range().
NextProbe()
static InternalIndex v8::internal::HashTableBase::NextProbe (InternalIndex last, uint32_t number, uint32_t size) [inline], [static], [protected]
Definition at line 118 of file hash-table.h.
                                                       {
    return InternalIndex((last.as_uint32() + number) & (size - 1));
  }
References v8::internal::InternalIndex::as_uint32(), and size().
NumberOfDeletedElements()
uint32_t v8::internal::HashTableBase::NumberOfDeletedElements () const [inline]
Definition at line 58 of file hash-table-inl.h.
                                                      {
  return Cast<Smi>(get(kNumberOfDeletedElementsIndex)).value();
}
References kNumberOfDeletedElementsIndex.
Referenced by ElementRemoved(), and ElementsRemoved().
NumberOfElements()
uint32_t v8::internal::HashTableBase::NumberOfElements () const [inline]
Definition at line 54 of file hash-table-inl.h.
                                               {
  return Cast<Smi>(get(kNumberOfElementsIndex)).value();
}
References kNumberOfElementsIndex.
Referenced by ElementAdded(), ElementRemoved(), ElementsRemoved(), and SetInitialNumberOfElements().
SetInitialNumberOfElements()
void v8::internal::HashTableBase::SetInitialNumberOfElements (int nof) [inline]
Definition at line 94 of file hash-table-inl.h.
                                                      {
  DCHECK_EQ(NumberOfElements(), 0);
  set(kNumberOfElementsIndex, Smi::FromInt(nof));
}
References DCHECK_EQ, v8::internal::Smi::FromInt(), kNumberOfElementsIndex, and NumberOfElements().
SetNumberOfDeletedElements()
void v8::internal::HashTableBase::SetNumberOfDeletedElements (int nod) [inline], [protected]
Definition at line 103 of file hash-table-inl.h.
                                                      {
  set(kNumberOfDeletedElementsIndex, Smi::FromInt(nod));
}
References v8::internal::Smi::FromInt(), and kNumberOfDeletedElementsIndex.
Referenced by ElementRemoved(), and ElementsRemoved().
SetNumberOfElements()
void v8::internal::HashTableBase::SetNumberOfElements (int nof) [inline], [protected]
Definition at line 99 of file hash-table-inl.h.
                                               {
  set(kNumberOfElementsIndex, Smi::FromInt(nof));
}
References v8::internal::Smi::FromInt(), and kNumberOfElementsIndex.
Referenced by ElementAdded(), ElementRemoved(), and ElementsRemoved().
Member Data Documentation
kCapacityIndex
const int v8::internal::HashTableBase::kCapacityIndex = 2 [static]
Definition at line 101 of file hash-table.h.
Referenced by Capacity(), and v8::internal::compiler::AccessBuilder::ForHashTableBaseCapacity().
kMinCapacity
const uint32_t v8::internal::HashTableBase::kMinCapacity = 4 [static]
Definition at line 105 of file hash-table.h.
Referenced by ComputeCapacity(), and v8::internal::CodeStubAssembler::HashTableComputeCapacity().
kNumberOfDeletedElementsIndex
const int v8::internal::HashTableBase::kNumberOfDeletedElementsIndex = 1 [static]
Definition at line 100 of file hash-table.h.
Referenced by v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfDeletedElement(), NumberOfDeletedElements(), and SetNumberOfDeletedElements().
kNumberOfElementsIndex
const int v8::internal::HashTableBase::kNumberOfElementsIndex = 0 [static]
Definition at line 99 of file hash-table.h.
Referenced by v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfElements(), NumberOfElements(), SetInitialNumberOfElements(), and SetNumberOfElements().
kPrefixStartIndex
const int v8::internal::HashTableBase::kPrefixStartIndex = 3 [static]
Definition at line 102 of file hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/hash-table.h
/mnt/V8SourceCode/src/objects/hash-table-inl.h