v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters Class Reference
Public Member Functions
TransitionAndStoreNumberElementParameters (MapRef double_map)
MapRef double_map () const
Private Attributes
MapRef const double_map_
Detailed Description
Definition at line 503 of file simplified-operator.cc.
Constructor & Destructor Documentation
TransitionAndStoreNumberElementParameters()
v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters::TransitionAndStoreNumberElementParameters (MapRef double_map) [explicit]
Definition at line 513 of file simplified-operator.cc.
    : double_map_(double_map) {}
Member Function Documentation
double_map()
MapRef v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters::double_map () const [inline]
Definition at line 507 of file simplified-operator.cc.
{ return double_map_; }
References double_map_.
Referenced by v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<<(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator==().
Member Data Documentation
double_map_
MapRef const v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNumberElementParameters::double_map_ [private]
Definition at line 510 of file simplified-operator.cc.
Referenced by double_map().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.cc