v8::base::AddressRegion Class Reference
#include <address-region.h>
Classes
struct StartAddressLess
Public Types
using Address = uintptr_t
Public Member Functions
constexpr AddressRegion ()=default
constexpr AddressRegion (Address address, size_t size)
Address begin () const
Address end () const
size_t size () const
void set_size (size_t size)
bool is_empty () const
bool contains (Address address) const
bool contains (Address address, size_t size) const
bool contains (AddressRegion region) const
base::AddressRegion GetOverlap (AddressRegion region) const
bool operator== (AddressRegion other) const
Private Attributes
Address address_ = 0
size_t size_ = 0
Detailed Description
Definition at line 16 of file address-region.h.
Member Typedef Documentation
Address
using v8::base::AddressRegion::Address = uintptr_t
Definition at line 26 of file address-region.h.
Constructor & Destructor Documentation
AddressRegion() [1/2]
constexpr v8::base::AddressRegion::AddressRegion () [constexpr], [default]
AddressRegion() [2/2]
constexpr v8::base::AddressRegion::AddressRegion (Address address, size_t size) [inline], [constexpr]
Definition at line 30 of file address-region.h.
      : address_(address), size_(size) {}
Member Function Documentation
begin()
Address v8::base::AddressRegion::begin () const [inline]
Definition at line 33 of file address-region.h.
{ return address_; }
References address_.
Referenced by v8::internal::VirtualMemory::address(), v8::base::RegionAllocator::AllocateAlignedRegion(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::DisjointAllocationPool::AllocateInRegion(), v8::base::RegionAllocator::AllocateRegion(), v8::base::RegionAllocator::AllocateRegionAt(), v8::internal::wasm::WasmCodeManager::AssignRange(), v8::base::RegionAllocator::CheckRegion(), v8::internal::wasm::WasmCodeManager::Commit(), contains(), v8::internal::wasm::WasmCodeManager::Decommit(), v8::internal::wasm::NativeModule::FindJumpTablesForRegionLocked(), v8::internal::VirtualMemory::Free(), v8::Isolate::GetCodeRange(), GetOverlap(), v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), v8::internal::VirtualMemoryCage::InitReservation(), v8::internal::CodeRange::InitReservation(), v8::internal::VirtualMemory::IsReserved(), v8::base::RegionAllocator::Merge(), v8::internal::wasm::DisjointAllocationPool::Merge(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::base::AddressRegion::StartAddressLess::operator()(), v8::base::RegionAllocator::SizeAddressOrder::operator()(), v8::base::operator<<(), v8::base::RegionAllocator::Region::Print(), v8::internal::VirtualMemory::Release(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::base::RegionAllocator::Split(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), v8::base::RegionAllocator::TrimRegion(), and v8::base::RegionAllocator::TryGrowRegion().
contains() [1/3]
bool v8::base::AddressRegion::contains (Address address) const [inline]
Definition at line 41 of file address-region.h.
                                       {
    static_assert(std::is_unsigned_v<Address>);
    return (address - begin()) < size();
  }
References begin(), and size().
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), contains(), v8::base::RegionAllocator::FindRegion(), v8::internal::TickSample::GetStackSample(), v8::internal::Isolate::InitializeIsShortBuiltinCallsEnabled(), v8::internal::VirtualMemory::InVM(), v8::internal::MacroAssemblerBase::IsAddressableThroughRootRegister(), v8::base::RegionAllocator::IsFree(), and v8::internal::CodeRange::RemapEmbeddedBuiltins().
contains() [2/3]
bool v8::base::AddressRegion::contains (Address address, size_t size) const [inline]
Definition at line 46 of file address-region.h.
                                                    {
    static_assert(std::is_unsigned_v<Address>);
    Address offset = address - begin();
    return (offset < size_) && (offset + size <= size_);
  }
References begin(), size(), and size_.
contains() [3/3]
bool v8::base::AddressRegion::contains (AddressRegion region) const [inline]
Definition at line 52 of file address-region.h.
                                            {
    return contains(region.address_, region.size_);
  }
References address_, contains(), and size_.
end()
Address v8::base::AddressRegion::end () const [inline]
Definition at line 34 of file address-region.h.
{ return address_ + size_; }
References address_, and size_.
Referenced by v8::base::RegionAllocator::AllocateAlignedRegion(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::DisjointAllocationPool::AllocateInRegion(), v8::base::RegionAllocator::AllocateRegionAt(), v8::internal::wasm::WasmCodeManager::AssignRange(), v8::internal::wasm::WasmCodeManager::Commit(), v8::internal::wasm::WasmCodeManager::Decommit(), v8::internal::VirtualMemory::end(), v8::internal::wasm::NativeModule::FindJumpTablesForRegionLocked(), GetOverlap(), v8::internal::CodeRange::InitReservation(), v8::base::RegionAllocator::Merge(), v8::internal::wasm::DisjointAllocationPool::Merge(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::base::RegionAllocator::AddressEndOrder::operator()(), v8::base::RegionAllocator::Region::Print(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), v8::base::RegionAllocator::TrimRegion(), and v8::base::RegionAllocator::TryGrowRegion().
GetOverlap()
base::AddressRegion v8::base::AddressRegion::GetOverlap (AddressRegion region) const [inline]
Definition at line 56 of file address-region.h.
                                                           {
    Address overlap_start = std::max(begin(), region.begin());
    Address overlap_end =
        std::max(overlap_start, std::min(end(), region.end()));
    return {overlap_start, overlap_end - overlap_start};
  }
References begin(), and end().
Referenced by v8::internal::wasm::DisjointAllocationPool::AllocateInRegion().
is_empty()
bool v8::base::AddressRegion::is_empty () const [inline]
Definition at line 39 of file address-region.h.
{ return size_ == 0; }
References size_.
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions(), v8::internal::VirtualMemoryCage::InitReservation(), and v8::internal::CodeRange::RemapEmbeddedBuiltins().
operator==()
bool v8::base::AddressRegion::operator== (AddressRegion other) const [inline]
Definition at line 63 of file address-region.h.
                                             {
    return address_ == other.address_ && size_ == other.size_;
  }
References address_, and size_.
set_size()
void v8::base::AddressRegion::set_size (size_t size) [inline]
Definition at line 37 of file address-region.h.
{ size_ = size; }
References size(), and size_.
Referenced by v8::base::RegionAllocator::Merge(), v8::internal::VirtualMemory::Release(), v8::internal::VirtualMemory::Resize(), and v8::base::RegionAllocator::Split().
size()
size_t v8::base::AddressRegion::size () const [inline]
Definition at line 36 of file address-region.h.
{ return size_; }
References size_.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::base::RegionAllocator::AllocateAlignedRegion(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::wasm::DisjointAllocationPool::AllocateInRegion(), v8::base::RegionAllocator::AllocateRegion(), v8::base::RegionAllocator::AllocateRegionAt(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions(), v8::base::RegionAllocator::CheckRegion(), v8::internal::wasm::WasmCodeManager::Commit(), contains(), v8::internal::wasm::WasmCodeManager::Decommit(), v8::internal::VirtualMemory::Free(), v8::base::RegionAllocator::FreeListAddRegion(), v8::base::RegionAllocator::FreeListFindLargestRegion(), v8::base::RegionAllocator::FreeListRemoveRegion(), v8::Isolate::GetCodeRange(), v8::internal::wasm::WasmCodeAllocator::InitializeCodeRange(), v8::internal::VirtualMemoryCage::InitReservation(), v8::base::RegionAllocator::Merge(), v8::internal::wasm::DisjointAllocationPool::Merge(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), v8::base::RegionAllocator::SizeAddressOrder::operator()(), v8::base::operator<<(), v8::base::RegionAllocator::Region::Print(), v8::internal::VirtualMemory::Release(), v8::internal::CodeRange::RemapEmbeddedBuiltins(), v8::internal::VirtualMemory::Resize(), set_size(), v8::internal::VirtualMemory::size(), v8::base::RegionAllocator::Split(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::SplitRangeByReservationsIfNeeded(), v8::base::RegionAllocator::TrimRegion(), and v8::base::RegionAllocator::TryGrowRegion().
Member Data Documentation
address_
Address v8::base::AddressRegion::address_ = 0 [private]
Definition at line 68 of file address-region.h.
Referenced by begin(), contains(), end(), and operator==().
size_
size_t v8::base::AddressRegion::size_ = 0 [private]
Definition at line 69 of file address-region.h.
Referenced by contains(), end(), is_empty(), operator==(), set_size(), and size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/address-region.h