v8::internal::CodeDataSourceIncrementalState Class Reference
#include <code-data-source.h>
Classes
struct Function
struct ScriptUniqueId
Public Member Functions
CodeDataSourceIncrementalState ()=default
void Init (const CodeDataSource::TraceContext &context)
bool has_buffered_interned_data () const
void FlushInternedData (CodeDataSource::TraceContext::TracePacketHandle &packet)
uint64_t InternIsolate (Isolate &isolate)
uint64_t InternJsScript (Isolate &isolate, Tagged< Script > script)
uint64_t InternJsFunction (Isolate &isolate, DirectHandle< SharedFunctionInfo > info, uint64_t v8_js_script_iid, int line_num, int column_num)
bool is_initialized () const
bool log_script_sources () const
bool log_instructions () const
Private Types
using JsFunctionNameIid = uint64_t
Private Member Functions
uint64_t InternJsFunctionName (Tagged< String > function_name)
uint64_t next_isolate_iid () const
uint64_t next_script_iid () const
uint64_t next_function_iid () const
uint64_t next_js_function_name_iid () const
Private Attributes
protozero::HeapBuffered< perfetto::protos::pbzero::InternedData > serialized_interned_data_
std::unordered_map< int, uint64_t > isolates_
std::unordered_map< ScriptUniqueId, uint64_t, ScriptUniqueId::Hash > scripts_
std::unordered_map< Function, uint64_t, Function::Hash > functions_
std::unordered_map< PerfettoV8String, uint64_t, PerfettoV8String::Hasher > js_function_names_
std::unordered_map< std::string, uint64_t > two_byte_function_names_
bool log_script_sources_ = false
bool log_instructions_ = false
bool initialized_ = false
Detailed Description
Definition at line 58 of file code-data-source.h.
Member Typedef Documentation
JsFunctionNameIid
using v8::internal::CodeDataSourceIncrementalState::JsFunctionNameIid = uint64_t [private]
Definition at line 88 of file code-data-source.h.
Constructor & Destructor Documentation
CodeDataSourceIncrementalState()
v8::internal::CodeDataSourceIncrementalState::CodeDataSourceIncrementalState () [default]
Member Function Documentation
FlushInternedData()
void v8::internal::CodeDataSourceIncrementalState::FlushInternedData (CodeDataSource::TraceContext::TracePacketHandle & packet)
Definition at line 135 of file code-data-source.cc.
                                                         {
  auto ranges = serialized_interned_data_.GetRanges();
  packet->AppendScatteredBytes(TracePacket::kInternedDataFieldNumber,
                               &ranges[0], ranges.size());
  serialized_interned_data_.Reset();
}
References serialized_interned_data_.
Referenced by v8::internal::CodeTraceContext::~CodeTraceContext().
has_buffered_interned_data()
bool v8::internal::CodeDataSourceIncrementalState::has_buffered_interned_data () const [inline]
Definition at line 63 of file code-data-source.h.
                                          {
    return !serialized_interned_data_.empty();
  }
References serialized_interned_data_.
Referenced by v8::internal::CodeTraceContext::~CodeTraceContext().
Init()
void v8::internal::CodeDataSourceIncrementalState::Init (const CodeDataSource::TraceContext & context)
Definition at line 125 of file code-data-source.cc.
                                               {
  if (auto ds = context.GetDataSourceLocked(); ds) {
    const V8Config& config = ds->config();
    log_script_sources_ = config.log_script_sources();
    log_instructions_ = config.log_instructions();
  }
  initialized_ = true;
}
References initialized_, log_instructions_, and log_script_sources_.
Referenced by v8::internal::anonymous_namespace{perfetto-logger.cc}::NewTracePacket().
InternIsolate()
uint64_t v8::internal::CodeDataSourceIncrementalState::InternIsolate (Isolate & isolate)
Definition at line 143 of file code-data-source.cc.
                                                                       {
  auto [it, was_inserted] = isolates_.emplace(isolate.id(), next_isolate_iid());
  uint64_t iid = it->second;
  if (!was_inserted) {
    return iid;
  }
  auto* isolate_proto = serialized_interned_data_->add_v8_isolate();
  isolate_proto->set_iid(iid);
  isolate_proto->set_isolate_id(isolate.id());
  isolate_proto->set_pid(base::OS::GetCurrentProcessId());
  isolate_proto->set_embedded_blob_code_start_address(
      reinterpret_cast<uint64_t>(isolate.embedded_blob_code()));
  isolate_proto->set_embedded_blob_code_size(isolate.embedded_blob_code_size());
  if (auto* code_range = isolate.heap()->code_range(); code_range != nullptr) {
    auto* v8_code_range = isolate_proto->set_code_range();
    v8_code_range->set_base_address(code_range->base());
    v8_code_range->set_size(code_range->size());
    if (code_range == IsolateGroup::current()->GetCodeRange()) {
      // FIXME(42204573): Belongs to isolate group, not process.
      v8_code_range->set_is_process_wide(true);
    }
    if (auto* embedded_builtins_start = code_range->embedded_blob_code_copy();
        embedded_builtins_start != nullptr) {
      v8_code_range->set_embedded_blob_code_copy_start_address(
          reinterpret_cast<uint64_t>(embedded_builtins_start));
    }
  }
  return iid;
}
References v8::internal::Heap::code_range(), v8::internal::IsolateGroup::current(), v8::internal::Isolate::embedded_blob_code(), v8::internal::Isolate::embedded_blob_code_size(), v8::base::OS::GetCurrentProcessId(), v8::internal::Isolate::heap(), v8::internal::Isolate::id(), isolates_, next_isolate_iid(), and serialized_interned_data_.
Referenced by v8::internal::CodeTraceContext::InternIsolate().
InternJsFunction()
uint64_t v8::internal::CodeDataSourceIncrementalState::InternJsFunction (Isolate & isolate, DirectHandle< SharedFunctionInfo > info, uint64_t v8_js_script_iid, int line_num, int column_num)
Definition at line 202 of file code-data-source.cc.
                                                             {
  DirectHandle<String> function_name =
      SharedFunctionInfo::DebugName(&isolate, info);
  uint64_t v8_js_function_name_iid = InternJsFunctionName(*function_name);
  auto [it, was_inserted] = functions_.emplace(
      CodeDataSourceIncrementalState::Function{
          v8_js_script_iid, info->is_toplevel(), info->StartPosition()},
      next_function_iid());
  const uint64_t iid = it->second;
  if (!was_inserted) {
    return iid;
  }
  auto* function_proto = serialized_interned_data_->add_v8_js_function();
  function_proto->set_iid(iid);
  function_proto->set_v8_js_function_name_iid(v8_js_function_name_iid);
  function_proto->set_v8_js_script_iid(v8_js_script_iid);
  function_proto->set_kind(GetJsFunctionKind(info->kind()));
  int32_t start_position = info->StartPosition();
  if (start_position >= 0) {
    function_proto->set_byte_offset(static_cast<uint32_t>(start_position));
  }
  if (line_num > 0 && column_num > 0) {
    function_proto->set_line(static_cast<uint32_t>(line_num));
    function_proto->set_column(static_cast<uint32_t>(column_num));
  }
  return iid;
}
References v8::internal::SharedFunctionInfo::DebugName(), functions_, v8::internal::anonymous_namespace{code-data-source.cc}::GetJsFunctionKind(), InternJsFunctionName(), next_function_iid(), and serialized_interned_data_.
Referenced by v8::internal::CodeTraceContext::InternJsFunction().
InternJsFunctionName()
uint64_t v8::internal::CodeDataSourceIncrementalState::InternJsFunctionName (Tagged< String > function_name) [private]
Definition at line 261 of file code-data-source.cc.
                                  {
  auto [it, was_inserted] = js_function_names_.emplace(
      PerfettoV8String(function_name), next_js_function_name_iid());
  uint64_t iid = it->second;
  if (!was_inserted) {
    return iid;
  }
  auto* v8_function_name = serialized_interned_data_->add_v8_js_function_name();
  v8_function_name->set_iid(iid);
  it->first.WriteToProto(*v8_function_name);
  return iid;
}
References js_function_names_, next_js_function_name_iid(), and serialized_interned_data_.
Referenced by InternJsFunction().
InternJsScript()
uint64_t v8::internal::CodeDataSourceIncrementalState::InternJsScript (Isolate & isolate, Tagged< Script > script)
Definition at line 175 of file code-data-source.cc.
                                                                               {
  auto [it, was_inserted] = scripts_.emplace(
      CodeDataSourceIncrementalState::ScriptUniqueId{isolate.id(),
                                                     script->id()},
      next_script_iid());
  uint64_t iid = it->second;
  if (!was_inserted) {
    return iid;
  }
  auto* proto = serialized_interned_data_->add_v8_js_script();
  proto->set_iid(iid);
  proto->set_script_id(script->id());
  proto->set_type(GetJsScriptType(script));
  if (IsString(script->name())) {
    PerfettoV8String(Cast<String>(script->name()))
        .WriteToProto(*proto->set_name());
  }
  if (log_script_sources() && IsString(script->source())) {
    PerfettoV8String(Cast<String>(script->source()))
        .WriteToProto(*proto->set_source());
  }
  return iid;
}
References v8::internal::anonymous_namespace{code-data-source.cc}::GetJsScriptType(), v8::internal::Isolate::id(), log_script_sources(), next_script_iid(), v8::internal::script, scripts_, serialized_interned_data_, and v8::internal::PerfettoV8String::WriteToProto().
Referenced by v8::internal::CodeTraceContext::InternJsScript().
is_initialized()
bool v8::internal::CodeDataSourceIncrementalState::is_initialized () const [inline]
Definition at line 83 of file code-data-source.h.
{ return initialized_; }
References initialized_.
Referenced by v8::internal::anonymous_namespace{perfetto-logger.cc}::NewTracePacket().
log_instructions()
bool v8::internal::CodeDataSourceIncrementalState::log_instructions () const [inline]
Definition at line 85 of file code-data-source.h.
{ return log_instructions_; }
References log_instructions_.
Referenced by v8::internal::CodeTraceContext::log_instructions().
log_script_sources()
bool v8::internal::CodeDataSourceIncrementalState::log_script_sources () const [inline]
Definition at line 84 of file code-data-source.h.
{ return log_script_sources_; }
References log_script_sources_.
Referenced by InternJsScript(), and v8::internal::CodeTraceContext::log_script_sources().
next_function_iid()
uint64_t v8::internal::CodeDataSourceIncrementalState::next_function_iid () const [inline], [private]
Definition at line 134 of file code-data-source.h.
{ return functions_.size() + 1; }
References functions_.
Referenced by InternJsFunction().
next_isolate_iid()
uint64_t v8::internal::CodeDataSourceIncrementalState::next_isolate_iid () const [inline], [private]
Definition at line 130 of file code-data-source.h.
{ return isolates_.size() + 1; }
References isolates_.
Referenced by InternIsolate().
next_js_function_name_iid()
uint64_t v8::internal::CodeDataSourceIncrementalState::next_js_function_name_iid () const [inline], [private]
Definition at line 136 of file code-data-source.h.
                                             {
    return js_function_names_.size() + 1;
  }
References js_function_names_.
Referenced by InternJsFunctionName().
next_script_iid()
uint64_t v8::internal::CodeDataSourceIncrementalState::next_script_iid () const [inline], [private]
Definition at line 132 of file code-data-source.h.
{ return scripts_.size() + 1; }
References scripts_.
Referenced by InternJsScript().
Member Data Documentation
functions_
std::unordered_map<Function, uint64_t, Function::Hash> v8::internal::CodeDataSourceIncrementalState::functions_ [private]
Definition at line 150 of file code-data-source.h.
Referenced by InternJsFunction(), and next_function_iid().
initialized_
bool v8::internal::CodeDataSourceIncrementalState::initialized_ = false [private]
Definition at line 157 of file code-data-source.h.
Referenced by Init(), and is_initialized().
isolates_
std::unordered_map<int, uint64_t> v8::internal::CodeDataSourceIncrementalState::isolates_ [private]
Definition at line 148 of file code-data-source.h.
Referenced by InternIsolate(), and next_isolate_iid().
js_function_names_
std::unordered_map<PerfettoV8String, uint64_t, PerfettoV8String::Hasher> v8::internal::CodeDataSourceIncrementalState::js_function_names_ [private]
Definition at line 152 of file code-data-source.h.
Referenced by InternJsFunctionName(), and next_js_function_name_iid().
log_instructions_
bool v8::internal::CodeDataSourceIncrementalState::log_instructions_ = false [private]
Definition at line 156 of file code-data-source.h.
Referenced by Init(), and log_instructions().
log_script_sources_
bool v8::internal::CodeDataSourceIncrementalState::log_script_sources_ = false [private]
Definition at line 155 of file code-data-source.h.
Referenced by Init(), and log_script_sources().
scripts_
std::unordered_map<ScriptUniqueId, uint64_t, ScriptUniqueId::Hash> v8::internal::CodeDataSourceIncrementalState::scripts_ [private]
Definition at line 149 of file code-data-source.h.
Referenced by InternJsScript(), and next_script_iid().
serialized_interned_data_
protozero::HeapBuffered<perfetto::protos::pbzero::InternedData> v8::internal::CodeDataSourceIncrementalState::serialized_interned_data_ [private]
Definition at line 146 of file code-data-source.h.
Referenced by FlushInternedData(), has_buffered_interned_data(), InternIsolate(), InternJsFunction(), InternJsFunctionName(), and InternJsScript().
two_byte_function_names_
std::unordered_map<std::string, uint64_t> v8::internal::CodeDataSourceIncrementalState::two_byte_function_names_ [private]
Definition at line 153 of file code-data-source.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tracing/code-data-source.h
/mnt/V8SourceCode/src/tracing/code-data-source.cc