v8::internal::compiler::LateEscapeAnalysis Class Reference
#include <late-escape-analysis.h>
Public Member Functions
LateEscapeAnalysis (Editor *editor, TFGraph *graph, CommonOperatorBuilder *common, Zone *zone)
const char * reducer_name () const override
Reduction Reduce (Node *node) final
void Finalize () override
Private Member Functions
bool IsEscaping (Node *node)
void RemoveAllocation (Node *node)
void RecordEscapingAllocation (Node *allocation)
void RemoveWitness (Node *allocation)
Node * dead () const
Private Attributes
Node * dead_
ZoneUnorderedSet< Node * > all_allocations_
ZoneUnorderedMap< Node *, int > escaping_allocations_
NodeDeque revisit_
Additional Inherited Members
Detailed Description
Definition at line 18 of file late-escape-analysis.h.
Constructor & Destructor Documentation
LateEscapeAnalysis()
v8::internal::compiler::LateEscapeAnalysis::LateEscapeAnalysis (Editor * editor, TFGraph * graph, CommonOperatorBuilder * common, Zone * zone)
Definition at line 16 of file late-escape-analysis.cc.
    : AdvancedReducer(editor),
      dead_(graph->NewNode(common->Dead())),
      all_allocations_(zone),
      escaping_allocations_(zone),
      revisit_(zone) {}
Member Function Documentation
dead()
Node* v8::internal::compiler::LateEscapeAnalysis::dead () const [inline], [private]
Definition at line 33 of file late-escape-analysis.h.
{ return dead_; }
References dead_.
Referenced by RemoveAllocation().
Finalize()
void v8::internal::compiler::LateEscapeAnalysis::Finalize () [override], [virtual]
Reimplemented from v8::internal::compiler::Reducer.
Definition at line 66 of file late-escape-analysis.cc.
                                  {
  for (Node* alloc : all_allocations_) {
    if (!IsEscaping(alloc)) {
      RemoveAllocation(alloc);
    }
  }
  while (!revisit_.empty()) {
    Node* alloc = revisit_.front();
    revisit_.pop_front();
    if (!IsEscaping(alloc) && !alloc->IsDead()) {
      RemoveAllocation(alloc);
    }
  }
}
References all_allocations_, v8::internal::compiler::Node::IsDead(), IsEscaping(), RemoveAllocation(), and revisit_.
IsEscaping()
bool v8::internal::compiler::LateEscapeAnalysis::IsEscaping (Node * node) [private]
Definition at line 104 of file late-escape-analysis.cc.
                                              {
  DCHECK_EQ(node->opcode(), IrOpcode::kAllocateRaw);
  auto escaping = escaping_allocations_.find(node);
  if (escaping == escaping_allocations_.end()) return false;
  return escaping->second != 0;
}
References DCHECK_EQ, escaping_allocations_, and v8::internal::compiler::Node::opcode().
Referenced by Finalize().
RecordEscapingAllocation()
void v8::internal::compiler::LateEscapeAnalysis::RecordEscapingAllocation (Node * allocation) [private]
Definition at line 135 of file late-escape-analysis.cc.
                                                                  {
  DCHECK_EQ(allocation->opcode(), IrOpcode::kAllocateRaw);
  escaping_allocations_[allocation]++;
}
References DCHECK_EQ, escaping_allocations_, and v8::internal::compiler::Node::opcode().
Referenced by Reduce().
Reduce()
Reduction v8::internal::compiler::LateEscapeAnalysis::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 51 of file late-escape-analysis.cc.
                                               {
  if (node->opcode() == IrOpcode::kAllocateRaw) {
    all_allocations_.insert(node);
    return NoChange();
  }
  for (Edge edge : node->input_edges()) {
    if (IsEscapingAllocationWitness(edge)) {
      RecordEscapingAllocation(edge.to());
    }
  }
  return NoChange();
}
References all_allocations_, v8::internal::compiler::Node::input_edges(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsEscapingAllocationWitness(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), and RecordEscapingAllocation().
reducer_name()
const char* v8::internal::compiler::LateEscapeAnalysis::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 23 of file late-escape-analysis.h.
{ return "LateEscapeAnalysis"; }
RemoveAllocation()
void v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation (Node * node) [private]
Definition at line 111 of file late-escape-analysis.cc.
                                                    {
  DCHECK_EQ(node->opcode(), IrOpcode::kAllocateRaw);
  for (Edge edge : node->use_edges()) {
    if (!NodeProperties::IsValueEdge(edge)) continue;
    Node* use = edge.from();
    if (use->IsDead()) continue;
    // The value stored by this Store node might be another allocation which has
    // no more uses. Affected allocations are revisited.
    if (std::optional<Node*> stored_value = TryGetStoredValue(use);
        stored_value.has_value() &&
        stored_value.value()->opcode() == IrOpcode::kAllocateRaw &&
        stored_value.value() != node) {
      RemoveWitness(stored_value.value());
      revisit_.push_back(stored_value.value());
    }
    ReplaceWithValue(use, dead());
    use->Kill();
  }
  // Remove the allocation from the effect and control chains.
  ReplaceWithValue(node, dead());
  node->Kill();
}
References DCHECK_EQ, dead(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::Node::opcode(), RemoveWitness(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), revisit_, v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::TryGetStoredValue(), use(), and v8::internal::compiler::Node::use_edges().
Referenced by Finalize().
RemoveWitness()
void v8::internal::compiler::LateEscapeAnalysis::RemoveWitness (Node * allocation) [private]
Definition at line 140 of file late-escape-analysis.cc.
                                                       {
  DCHECK_EQ(allocation->opcode(), IrOpcode::kAllocateRaw);
  DCHECK_GT(escaping_allocations_[allocation], 0);
  escaping_allocations_[allocation]--;
}
References DCHECK_EQ, DCHECK_GT, escaping_allocations_, and v8::internal::compiler::Node::opcode().
Referenced by RemoveAllocation().
Member Data Documentation
all_allocations_
ZoneUnorderedSet<Node*> v8::internal::compiler::LateEscapeAnalysis::all_allocations_ [private]
Definition at line 36 of file late-escape-analysis.h.
Referenced by Finalize(), and Reduce().
dead_
Node* v8::internal::compiler::LateEscapeAnalysis::dead_ [private]
Definition at line 35 of file late-escape-analysis.h.
Referenced by dead().
escaping_allocations_
ZoneUnorderedMap<Node*, int> v8::internal::compiler::LateEscapeAnalysis::escaping_allocations_ [private]
Definition at line 38 of file late-escape-analysis.h.
Referenced by IsEscaping(), RecordEscapingAllocation(), and RemoveWitness().
revisit_
NodeDeque v8::internal::compiler::LateEscapeAnalysis::revisit_ [private]
Definition at line 39 of file late-escape-analysis.h.
Referenced by Finalize(), and RemoveAllocation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/late-escape-analysis.h
/mnt/V8SourceCode/src/compiler/late-escape-analysis.cc