v8::internal::maglev::TaggedEqual Class Reference
#include <maglev-ir.h>
Public Member Functions
TaggedEqual (uint64_t bitfield)
Input & lhs ()
Input & rhs ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, TaggedEqual >
Additional Inherited Members
Detailed Description
Definition at line 4995 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TaggedEqual::Base = FixedInputValueNodeT<2, TaggedEqual> [private]
Definition at line 4996 of file maglev-ir.h.
Constructor & Destructor Documentation
TaggedEqual()
v8::internal::maglev::TaggedEqual::TaggedEqual (uint64_t bitfield) [inline], [explicit]
Definition at line 4999 of file maglev-ir.h.
: Base(bitfield) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::TaggedEqual::GenerateCode (MaglevAssembler * , const ProcessingState &)
lhs()
Input& v8::internal::maglev::TaggedEqual::lhs () [inline]
Definition at line 5004 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::TaggedEqual::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5015 of file maglev-ir.h.
{}
rhs()
Input& v8::internal::maglev::TaggedEqual::rhs () [inline]
Definition at line 5005 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::TaggedEqual::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TaggedEqual::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 5001 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h