v8::internal::maglev::ToBooleanLogicalNot Class Reference
#include <maglev-ir.h>
Public Member Functions
ToBooleanLogicalNot (uint64_t bitfield, CheckType check_type)
Input & value ()
CheckType check_type () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, ToBooleanLogicalNot >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Additional Inherited Members
Detailed Description
Definition at line 4939 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ToBooleanLogicalNot::Base = FixedInputValueNodeT<1, ToBooleanLogicalNot> [private]
Definition at line 4941 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::ToBooleanLogicalNot::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 4960 of file maglev-ir.h.
Constructor & Destructor Documentation
ToBooleanLogicalNot()
v8::internal::maglev::ToBooleanLogicalNot::ToBooleanLogicalNot (uint64_t bitfield, CheckType check_type) [inline], [explicit]
Definition at line 4944 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)) {}
Member Function Documentation
check_type()
CheckType v8::internal::maglev::ToBooleanLogicalNot::check_type () const [inline]
Definition at line 4951 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by options().
GenerateCode()
void v8::internal::maglev::ToBooleanLogicalNot::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::ToBooleanLogicalNot::options () const [inline]
Definition at line 4957 of file maglev-ir.h.
{ return std::tuple{check_type()}; }
References check_type().
PrintParams()
void v8::internal::maglev::ToBooleanLogicalNot::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 4955 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::ToBooleanLogicalNot::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::ToBooleanLogicalNot::value () [inline]
Definition at line 4950 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ToBooleanLogicalNot::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 4948 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h