v8::internal::wasm::ErrorThrower Class Reference
#include <wasm-result.h>
Public Member Functions
ErrorThrower (Isolate *isolate, const char *context)
ErrorThrower (const ErrorThrower &)=delete
ErrorThrower & operator= (const ErrorThrower &)=delete
~ErrorThrower ()
PRINTF_FORMAT (2, 3) void TypeError(const char *fmt
PRINTF_FORMAT (2, 3) void RangeError(const char *fmt
PRINTF_FORMAT (2, 3) void CompileError(const char *fmt
PRINTF_FORMAT (2, 3) void LinkError(const char *fmt
PRINTF_FORMAT (2, 3) void RuntimeError(const char *fmt
void CompileFailed (const WasmError &error)
V8_WARN_UNUSED_RESULT DirectHandle< JSObject > Reify ()
void Reset ()
bool error () const
bool wasm_error ()
const char * error_msg ()
Isolate * isolate () const
constexpr const char * context_name () const
Private Types
enum ErrorType {
kNone
, kTypeError
, kRangeError
, kCompileError
,
kLinkError
, kRuntimeError
, kFirstWasmError = kCompileError
 }
Private Member Functions
void Format (ErrorType error_type_, const char *fmt, va_list)
Private Attributes
Isolate *const isolate_
const char *const context_
ErrorType error_type_ = kNone
std::string error_msg_
Detailed Description
Definition at line 123 of file wasm-result.h.
Member Enumeration Documentation
ErrorType
enum v8::internal::wasm::ErrorThrower::ErrorType [private]
Enumerator
kNone
kTypeError
kRangeError
kCompileError
kLinkError
kRuntimeError
kFirstWasmError
Definition at line 158 of file wasm-result.h.
                 {
    kNone,
    // General errors.
    kTypeError,
    kRangeError,
    // Wasm errors.
    kCompileError,
    kLinkError,
    kRuntimeError,
    // Marker.
    kFirstWasmError = kCompileError
  };
Constructor & Destructor Documentation
ErrorThrower() [1/2]
v8::internal::wasm::ErrorThrower::ErrorThrower (Isolate * isolate, const char * context) [inline]
Definition at line 125 of file wasm-result.h.
      : isolate_(isolate), context_(context) {}
ErrorThrower() [2/2]
v8::internal::wasm::ErrorThrower::ErrorThrower (const ErrorThrower &) [delete]
 ErrorThrower()
v8::internal::wasm::ErrorThrower::~ErrorThrower ()
Definition at line 141 of file wasm-result.cc.
                            {
  if (!error() || isolate_->has_exception()) return;
  HandleScope handle_scope{isolate_};
  isolate_->Throw(*Reify());
}
References error(), v8::internal::Isolate::has_exception(), isolate_, Reify(), and v8::internal::Isolate::Throw().
Member Function Documentation
CompileFailed()
void v8::internal::wasm::ErrorThrower::CompileFailed (const WasmError & error) [inline]
Definition at line 138 of file wasm-result.h.
                                             {
    DCHECK(error.has_error());
    CompileError("%s @+%u", error.message().c_str(), error.offset());
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptions(), v8::internal::wasm::WasmEngine::SyncCompile(), and v8::internal::wasm::ThrowLazyCompilationError().
context_name()
constexpr const char* v8::internal::wasm::ErrorThrower::context_name () const [inline], [constexpr]
Definition at line 155 of file wasm-result.h.
{ return context_; }
error()
bool v8::internal::wasm::ErrorThrower::error () const [inline]
Definition at line 149 of file wasm-result.h.
{ return error_type_ != kNone; }
References v8::internal::kNone.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::wasm::InstanceBuilder::Build(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::InstanceBuilder::Build_Phase2(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileNativeModule(), v8::internal::wasm::InstanceBuilder::ConfigurePrototypes_Modular(), v8::internal::CreateWasmObject(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::wasm::SyncStreamingDecoder::Finish(), Format(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::wasm::InstantiateToInstanceObject(), v8::internal::wasm::InstanceBuilder::SanitizeImports(), and ~ErrorThrower().
error_msg()
const char* v8::internal::wasm::ErrorThrower::error_msg () [inline]
Definition at line 151 of file wasm-result.h.
{ return error_msg_.c_str(); }
Referenced by v8::internal::AsmJs::InstantiateAsmWasm().
Format()
void v8::internal::wasm::ErrorThrower::Format (ErrorType error_type_, const char * fmt, va_list args) [private]
Definition at line 58 of file wasm-result.cc.
                                                                          {
  DCHECK_NE(kNone, type);
  // Only report the first error.
  if (error()) return;
  size_t context_len = 0;
  if (context_) {
    PrintFToString(&error_msg_, 0, "%s: ", context_);
    context_len = error_msg_.size();
  }
  VPrintFToString(&error_msg_, context_len, format, args);
  error_type_ = type;
}
References v8::base::args, context_, DCHECK_NE, error(), error_msg_, error_type_, v8::internal::format, kNone, v8::internal::wasm::anonymous_namespace{wasm-result.cc}::PrintFToString(), v8::internal::tracing::type, and v8::internal::wasm::anonymous_namespace{wasm-result.cc}::VPrintFToString().
isolate()
Isolate* v8::internal::wasm::ErrorThrower::isolate () const [inline]
Definition at line 153 of file wasm-result.h.
{ return isolate_; }
operator=()
ErrorThrower& v8::internal::wasm::ErrorThrower::operator= (const ErrorThrower &) [delete]
PRINTF_FORMAT() [1/5]
v8::internal::wasm::ErrorThrower::PRINTF_FORMAT (2 , 3) const
PRINTF_FORMAT() [2/5]
v8::internal::wasm::ErrorThrower::PRINTF_FORMAT (2 , 3) const
PRINTF_FORMAT() [3/5]
v8::internal::wasm::ErrorThrower::PRINTF_FORMAT (2 , 3) const
PRINTF_FORMAT() [4/5]
v8::internal::wasm::ErrorThrower::PRINTF_FORMAT (2 , 3) const
PRINTF_FORMAT() [5/5]
v8::internal::wasm::ErrorThrower::PRINTF_FORMAT (2 , 3) const
Reify()
DirectHandle< JSObject > v8::internal::wasm::ErrorThrower::Reify ()
Definition at line 107 of file wasm-result.cc.
                                           {
  DirectHandle<JSFunction> constructor;
  switch (error_type_) {
    case kNone:
      UNREACHABLE();
    case kTypeError:
      constructor = isolate_->type_error_function();
      break;
    case kRangeError:
      constructor = isolate_->range_error_function();
      break;
    case kCompileError:
      constructor = isolate_->wasm_compile_error_function();
      break;
    case kLinkError:
      constructor = isolate_->wasm_link_error_function();
      break;
    case kRuntimeError:
      constructor = isolate_->wasm_runtime_error_function();
      break;
  }
  DirectHandle<String> message =
      isolate_->factory()
          ->NewStringFromUtf8(base::VectorOf(error_msg_))
          .ToHandleChecked();
  Reset();
  return isolate_->factory()->NewError(constructor, message);
}
References error_msg_, error_type_, v8::internal::Isolate::factory(), isolate_, kCompileError, kLinkError, kNone, kRangeError, kRuntimeError, kTypeError, v8::internal::Factory::NewError(), v8::internal::Factory::NewStringFromUtf8(), Reset(), v8::internal::UNREACHABLE(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::SyncStreamingDecoder::Finish(), and ~ErrorThrower().
Reset()
void v8::internal::wasm::ErrorThrower::Reset ()
Definition at line 136 of file wasm-result.cc.
                         {
  error_type_ = kNone;
  error_msg_.clear();
}
References error_msg_, error_type_, and kNone.
Referenced by v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::AsmJs::InstantiateAsmWasm(), and Reify().
wasm_error()
bool v8::internal::wasm::ErrorThrower::wasm_error () [inline]
Definition at line 150 of file wasm-result.h.
{ return error_type_ >= kFirstWasmError; }
Member Data Documentation
context_
const char* const v8::internal::wasm::ErrorThrower::context_ [private]
Definition at line 175 of file wasm-result.h.
Referenced by Format().
error_msg_
std::string v8::internal::wasm::ErrorThrower::error_msg_ [private]
Definition at line 177 of file wasm-result.h.
Referenced by Format(), Reify(), and Reset().
error_type_
ErrorType v8::internal::wasm::ErrorThrower::error_type_ = kNone [private]
Definition at line 176 of file wasm-result.h.
Referenced by Format(), Reify(), and Reset().
isolate_
Isolate* const v8::internal::wasm::ErrorThrower::isolate_ [private]
Definition at line 174 of file wasm-result.h.
Referenced by Reify(), and ~ErrorThrower().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-result.h
/mnt/V8SourceCode/src/wasm/wasm-result.cc