v8::internal::maglev::Call Class Reference
#include <maglev-ir.h>
Public Types
enum class TargetType { kJSFunction
, kAny
 }
Public Member Functions
Call (uint64_t bitfield, ConvertReceiverMode mode, TargetType target_type, ValueNode *function, ValueNode *context)
Input & function ()
const Input & function () const
Input & context ()
const Input & context () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
ConvertReceiverMode receiver_mode () const
TargetType target_type () const
Static Public Attributes
static constexpr int kFunctionIndex = 0
static constexpr int kContextIndex = 1
static constexpr int kFixedInputCount = 2
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< Call >
Private Attributes
ConvertReceiverMode receiver_mode_
TargetType target_type_
Additional Inherited Members
Detailed Description
Definition at line 9995 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::Call::Base = ValueNodeT<Call> [private]
Definition at line 9996 of file maglev-ir.h.
Member Enumeration Documentation
TargetType
enum v8::internal::maglev::Call::TargetType [strong]
Enumerator
kJSFunction
kAny
Definition at line 9999 of file maglev-ir.h.
{ kJSFunction, kAny };
Constructor & Destructor Documentation
Call()
v8::internal::maglev::Call::Call (uint64_t bitfield, ConvertReceiverMode mode, TargetType target_type, ValueNode * function, ValueNode * context) [inline]
Definition at line 10011 of file maglev-ir.h.
      : Base(bitfield), receiver_mode_(mode), target_type_(target_type) {
    set_input(kFunctionIndex, function);
    set_input(kContextIndex, context);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::Call::arg (int i) [inline]
Definition at line 10025 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args()
auto v8::internal::maglev::Call::args () [inline]
Definition at line 10029 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [1/2]
Input& v8::internal::maglev::Call::context () [inline]
Definition at line 10022 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::Call::context () const [inline]
Definition at line 10023 of file maglev-ir.h.
{ return input(kContextIndex); }
function() [1/2]
Input& v8::internal::maglev::Call::function () [inline]
Definition at line 10020 of file maglev-ir.h.
{ return input(kFunctionIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
function() [2/2]
const Input& v8::internal::maglev::Call::function () const [inline]
Definition at line 10021 of file maglev-ir.h.
{ return input(kFunctionIndex); }
GenerateCode()
void v8::internal::maglev::Call::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::Call::MaxCallStackArgs () const
num_args()
int v8::internal::maglev::Call::num_args () const [inline]
Definition at line 10024 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::Call::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8369 of file maglev-ir.cc.
                                                                  {
  os << "(" << receiver_mode_ << ", ";
  switch (target_type_) {
    case TargetType::kJSFunction:
      os << "JSFunction";
      break;
    case TargetType::kAny:
      os << "Any";
      break;
  }
  os << ")";
}
References kAny, kJSFunction, receiver_mode_, and target_type_.
receiver_mode()
ConvertReceiverMode v8::internal::maglev::Call::receiver_mode () const [inline]
Definition at line 10044 of file maglev-ir.h.
{ return receiver_mode_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
set_arg()
void v8::internal::maglev::Call::set_arg (int i, ValueNode * node) [inline]
Definition at line 10026 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
SetValueLocationConstraints()
void v8::internal::maglev::Call::SetValueLocationConstraints ()
target_type()
TargetType v8::internal::maglev::Call::target_type () const [inline]
Definition at line 10045 of file maglev-ir.h.
{ return target_type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
VerifyInputs()
void v8::internal::maglev::Call::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 921 of file maglev-ir.cc.
                                                                 {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
kContextIndex
constexpr int v8::internal::maglev::Call::kContextIndex = 1 [static], [constexpr]
Definition at line 10002 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::Call::kFixedInputCount = 2 [static], [constexpr]
Definition at line 10003 of file maglev-ir.h.
kFunctionIndex
constexpr int v8::internal::maglev::Call::kFunctionIndex = 0 [static], [constexpr]
Definition at line 10001 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::Call::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10018 of file maglev-ir.h.
receiver_mode_
ConvertReceiverMode v8::internal::maglev::Call::receiver_mode_ [private]
Definition at line 10048 of file maglev-ir.h.
Referenced by PrintParams().
target_type_
TargetType v8::internal::maglev::Call::target_type_ [private]
Definition at line 10049 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc