v8::internal::ConditionalChain Class Reference
#include <ast.h>
Classes
struct ConditionalChainEntry
Public Member Functions
Expression * condition_at (size_t index) const
Expression * then_expression_at (size_t index) const
int condition_position_at (size_t index) const
size_t conditional_chain_length () const
Expression * else_expression () const
void set_else_expression (Expression *s)
void AddChainEntry (Expression *cond, Expression *then, int pos)
Private Member Functions
ConditionalChain (Zone *zone, size_t initial_size, int pos)
Private Attributes
friend Zone
ZoneVector< ConditionalChainEntry > conditional_chain_entries_
Expression * else_expression_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2073 of file ast.h.
Constructor & Destructor Documentation
ConditionalChain()
v8::internal::ConditionalChain::ConditionalChain (Zone * zone, size_t initial_size, int pos) [inline], [private]
Definition at line 2098 of file ast.h.
      : Expression(pos, kConditionalChain),
        conditional_chain_entries_(zone),
        else_expression_(nullptr) {
    conditional_chain_entries_.reserve(initial_size);
  }
References conditional_chain_entries_.
Member Function Documentation
AddChainEntry()
void v8::internal::ConditionalChain::AddChainEntry (Expression * cond, Expression * then, int pos) [inline]
Definition at line 2090 of file ast.h.
                                                                  {
    conditional_chain_entries_.emplace_back(cond, then, pos);
  }
References conditional_chain_entries_.
Referenced by v8::internal::Parser::CollapseConditionalChain().
condition_at()
Expression* v8::internal::ConditionalChain::condition_at (size_t index) const [inline]
Definition at line 2075 of file ast.h.
                                               {
    return conditional_chain_entries_[index].condition;
  }
References conditional_chain_entries_, and v8::internal::index.
condition_position_at()
int v8::internal::ConditionalChain::condition_position_at (size_t index) const [inline]
Definition at line 2081 of file ast.h.
                                                {
    return conditional_chain_entries_[index].condition_position;
  }
References conditional_chain_entries_, and v8::internal::index.
conditional_chain_length()
size_t v8::internal::ConditionalChain::conditional_chain_length () const [inline]
Definition at line 2084 of file ast.h.
                                          {
    return conditional_chain_entries_.size();
  }
References conditional_chain_entries_.
Referenced by v8::internal::Parser::AppendConditionalChainSourceRange(), and v8::internal::Parser::CollapseConditionalChain().
else_expression()
Expression* v8::internal::ConditionalChain::else_expression () const [inline]
Definition at line 2087 of file ast.h.
{ return else_expression_; }
References else_expression_.
set_else_expression()
void v8::internal::ConditionalChain::set_else_expression (Expression * s) [inline]
Definition at line 2088 of file ast.h.
{ else_expression_ = s; }
References else_expression_.
Referenced by v8::internal::Parser::CollapseConditionalChain().
then_expression_at()
Expression* v8::internal::ConditionalChain::then_expression_at (size_t index) const [inline]
Definition at line 2078 of file ast.h.
                                                     {
    return conditional_chain_entries_[index].then_expression;
  }
References conditional_chain_entries_, and v8::internal::index.
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2095 of file ast.h.
Member Data Documentation
conditional_chain_entries_
ZoneVector<ConditionalChainEntry> v8::internal::ConditionalChain::conditional_chain_entries_ [private]
Definition at line 2140 of file ast.h.
Referenced by AddChainEntry(), condition_at(), condition_position_at(), conditional_chain_length(), ConditionalChain(), and then_expression_at().
else_expression_
Expression* v8::internal::ConditionalChain::else_expression_ [private]
Definition at line 2141 of file ast.h.
Referenced by else_expression(), and set_else_expression().
Zone
friend v8::internal::ConditionalChain::Zone [private]
Definition at line 2096 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h