v8::PersistentValueMapBase< K, V, Traits > Class Template Reference
A map wrapper that allows using Global as a mapped value.
#include <v8-util.h>
Classes
class PersistentValueReference
Helper class for GetReference/SetWithReference.
Public Member Functions
Isolate * GetIsolate ()
size_t Size ()
Return size of the map.
bool IsWeak ()
Return whether the map holds weak persistents.
Local< V > Get (const K &key)
Get value stored in map.
bool Contains (const K &key)
Check whether a value is contained in the map.
bool SetReturnValue (const K &key, ReturnValue< Value > returnValue)
Get value stored in map and set it in returnValue.
Global< V > Remove (const K &key)
Return value for key and remove it from the map.
void Clear ()
Traverses the map repeatedly, in case side effects of disposal cause insertions.
PersistentValueReference GetReference (const K &key)
Get a reference to a map value.
Protected Member Functions
PersistentValueMapBase (Isolate *isolate)
PersistentValueMapBase (Isolate *isolate, const char *label)
~PersistentValueMapBase ()
Isolate * isolate ()
Traits::Impl * impl ()
void RemoveWeak (const K &key)
void AnnotateStrongRetainer (Global< V > *persistent)
Static Protected Member Functions
static V * FromVal (PersistentContainerValue v)
static PersistentContainerValue ClearAndLeak (Global< V > *persistent)
static PersistentContainerValue Leak (Global< V > *persistent)
static Global< V > Release (PersistentContainerValue v)
Return a container value as Global and make sure the weak callback is properly disposed of.
Private Member Functions
PersistentValueMapBase (PersistentValueMapBase &)
void operator= (PersistentValueMapBase &)
Static Private Member Functions
static bool SetReturnValueFromVal (ReturnValue< Value > *returnValue, PersistentContainerValue value)
Private Attributes
Isolate * isolate_
Traits::Impl impl_
const char * label_
Detailed Description
template<typename K, typename V, typename Traits>
class v8::PersistentValueMapBase< K, V, Traits >
A map wrapper that allows using Global as a mapped value.
C++11 embedders don't need this class, as they can use Global directly in std containers.
The map relies on a backing map, whose type and accessors are described by the Traits class. The backing map will handle values of type PersistentContainerValue, with all conversion into and out of V8 handles being transparently handled by this class.
Definition at line 166 of file v8-util.h.
Constructor & Destructor Documentation
PersistentValueMapBase() [1/3]
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::PersistentValueMapBase (Isolate * isolate) [inline], [explicit], [protected]
Definition at line 291 of file v8-util.h.
      : isolate_(isolate), label_(nullptr) {}
PersistentValueMapBase() [2/3]
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::PersistentValueMapBase (Isolate * isolate, const char * label) [inline], [protected]
Definition at line 293 of file v8-util.h.
      : isolate_(isolate), label_(label) {}
 PersistentValueMapBase()
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::~PersistentValueMapBase () [inline], [protected]
Definition at line 296 of file v8-util.h.
{ Clear(); }
References v8::PersistentValueMapBase< K, V, Traits >::Clear().
PersistentValueMapBase() [3/3]
template<typename K , typename V , typename Traits >
v8::PersistentValueMapBase< K, V, Traits >::PersistentValueMapBase (PersistentValueMapBase< K, V, Traits > &) [private]
Member Function Documentation
AnnotateStrongRetainer()
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::AnnotateStrongRetainer (Global< V > * persistent) [inline], [protected]
Definition at line 338 of file v8-util.h.
                                                     {
    persistent->AnnotateStrongRetainer(label_);
  }
References v8::PersistentBase< T >::AnnotateStrongRetainer(), and v8::PersistentValueMapBase< K, V, Traits >::label_.
Referenced by v8::PersistentValueMap< K, V, Traits >::SetUnique(), and v8::GlobalValueMap< K, V, Traits >::SetUnique().
Clear()
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::Clear () [inline]
Traverses the map repeatedly, in case side effects of disposal cause insertions.
Definition at line 218 of file v8-util.h.
               {
    typedef typename Traits::Iterator It;
    HandleScope handle_scope(isolate_);
    // TODO(dcarney): figure out if this swap and loop is necessary.
    while (!Traits::Empty(&impl_)) {
      typename Traits::Impl impl;
      Traits::Swap(impl_, impl);
      for (It i = Traits::Begin(&impl); i != Traits::End(&impl); ++i) {
        Traits::Dispose(isolate_, Release(Traits::Value(i)).Pass(),
                        Traits::Key(i));
      }
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::PersistentValueMapBase< K, V, Traits >::impl(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::PersistentValueMapBase< K, V, Traits >::impl_, v8::PersistentValueMapBase< K, V, Traits >::isolate_, and v8::PersistentValueMapBase< K, V, Traits >::Release().
Referenced by v8::PersistentValueMapBase< K, V, Traits >::~PersistentValueMapBase().
ClearAndLeak()
template<typename K , typename V , typename Traits >
static PersistentContainerValue v8::PersistentValueMapBase< K, V, Traits >::ClearAndLeak (Global< V > * persistent) [inline], [static], [protected]
Definition at line 306 of file v8-util.h.
                                                                      {
    internal::Address* address = persistent->slot();
    persistent->Clear();
    return reinterpret_cast<PersistentContainerValue>(address);
  }
References v8::api_internal::IndirectHandleBase::Clear(), and v8::api_internal::IndirectHandleBase::slot().
Referenced by v8::PersistentValueMap< K, V, Traits >::SetUnique(), and v8::GlobalValueMap< K, V, Traits >::SetUnique().
Contains()
template<typename K , typename V , typename Traits >
bool v8::PersistentValueMapBase< K, V, Traits >::Contains (const K & key) [inline]
Check whether a value is contained in the map.
Definition at line 194 of file v8-util.h.
                              {
    return Traits::Get(&impl_, key) != kPersistentContainerNotFound;
  }
References v8::internal::compiler::turboshaft::Get(), v8::PersistentValueMapBase< K, V, Traits >::impl_, v8::internal::key, and v8::kPersistentContainerNotFound.
FromVal()
template<typename K , typename V , typename Traits >
static V* v8::PersistentValueMapBase< K, V, Traits >::FromVal (PersistentContainerValue v) [inline], [static], [protected]
Definition at line 301 of file v8-util.h.
                                                {
    return internal::ValueHelper::SlotAsValue<V>(
        reinterpret_cast<internal::Address*>(v));
  }
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Get().
Get()
template<typename K , typename V , typename Traits >
Local<V> v8::PersistentValueMapBase< K, V, Traits >::Get (const K & key) [inline]
Get value stored in map.
Definition at line 183 of file v8-util.h.
                             {
    V* p = FromVal(Traits::Get(&impl_, key));
#ifdef V8_ENABLE_DIRECT_HANDLE
    if (p == nullptr) return Local<V>();
#endif
    return Local<V>::New(isolate_, p);
  }
References v8::PersistentValueMapBase< K, V, Traits >::FromVal(), v8::internal::compiler::turboshaft::Get(), v8::PersistentValueMapBase< K, V, Traits >::impl_, v8::PersistentValueMapBase< K, V, Traits >::isolate_, v8::internal::key, v8::Local< T >::New(), and V.
GetIsolate()
template<typename K , typename V , typename Traits >
Isolate* v8::PersistentValueMapBase< K, V, Traits >::GetIsolate () [inline]
Definition at line 168 of file v8-util.h.
{ return isolate_; }
References v8::PersistentValueMapBase< K, V, Traits >::isolate_.
GetReference()
template<typename K , typename V , typename Traits >
PersistentValueReference v8::PersistentValueMapBase< K, V, Traits >::GetReference (const K & key) [inline]
Get a reference to a map value.
This enables fast, repeated access to a value stored in the map while the map remains unchanged.
Careful: This is potentially unsafe, so please use with care. The value will become invalid if the value for this key changes in the underlying map, as a result of Set or Remove for the same key; as a result of the weak callback for the same key; or as a result of calling Clear() or destruction of the map.
Definition at line 286 of file v8-util.h.
                                                      {
    return PersistentValueReference(Traits::Get(&impl_, key));
  }
References v8::internal::compiler::turboshaft::Get(), v8::PersistentValueMapBase< K, V, Traits >::impl_, and v8::internal::key.
impl()
template<typename K , typename V , typename Traits >
Traits::Impl* v8::PersistentValueMapBase< K, V, Traits >::impl () [inline], [protected]
Definition at line 299 of file v8-util.h.
{ return &impl_; }
References v8::PersistentValueMapBase< K, V, Traits >::impl_.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Clear(), v8::PersistentValueMap< K, V, Traits >::SetUnique(), and v8::GlobalValueMap< K, V, Traits >::SetUnique().
isolate()
template<typename K , typename V , typename Traits >
Isolate* v8::PersistentValueMapBase< K, V, Traits >::isolate () [inline], [protected]
Definition at line 298 of file v8-util.h.
{ return isolate_; }
References v8::PersistentValueMapBase< K, V, Traits >::isolate_.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::NewLocal(), v8::PersistentValueMap< K, V, Traits >::Set(), v8::GlobalValueMap< K, V, Traits >::Set(), v8::PersistentValueMap< K, V, Traits >::SetUnique(), and v8::GlobalValueMap< K, V, Traits >::SetUnique().
IsWeak()
template<typename K , typename V , typename Traits >
bool v8::PersistentValueMapBase< K, V, Traits >::IsWeak () [inline]
Return whether the map holds weak persistents.
Definition at line 178 of file v8-util.h.
{ return Traits::kCallbackType != kNotWeak; }
References v8::kNotWeak.
Leak()
template<typename K , typename V , typename Traits >
static PersistentContainerValue v8::PersistentValueMapBase< K, V, Traits >::Leak (Global< V > * persistent) [inline], [static], [protected]
Definition at line 312 of file v8-util.h.
                                                              {
    return reinterpret_cast<PersistentContainerValue>(persistent->slot());
  }
References v8::api_internal::IndirectHandleBase::slot().
Referenced by v8::PersistentValueMap< K, V, Traits >::Set(), and v8::GlobalValueMap< K, V, Traits >::Set().
operator=()
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::operator= (PersistentValueMapBase< K, V, Traits > &) [private]
Release()
template<typename K , typename V , typename Traits >
static Global<V> v8::PersistentValueMapBase< K, V, Traits >::Release (PersistentContainerValue v) [inline], [static], [protected]
Return a container value as Global and make sure the weak callback is properly disposed of.
All remove functionality should go through this.
Definition at line 321 of file v8-util.h.
                                                       {
    Global<V> p;
    p.slot() = reinterpret_cast<internal::Address*>(v);
    if (Traits::kCallbackType != kNotWeak && p.IsWeak()) {
      Traits::DisposeCallbackData(
          p.template ClearWeak<typename Traits::WeakCallbackDataType>());
    }
    return p.Pass();
  }
References v8::PersistentBase< T >::IsWeak(), v8::kNotWeak, v8::Global< T >::Pass(), and v8::api_internal::IndirectHandleBase::slot().
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Clear(), v8::PersistentValueMapBase< K, V, Traits >::Remove(), v8::PersistentValueMap< K, V, Traits >::SetUnique(), and v8::GlobalValueMap< K, V, Traits >::SetUnique().
Remove()
template<typename K , typename V , typename Traits >
Global<V> v8::PersistentValueMapBase< K, V, Traits >::Remove (const K & key) [inline]
Return value for key and remove it from the map.
Definition at line 210 of file v8-util.h.
                                 {
    return Release(Traits::Remove(&impl_, key)).Pass();
  }
References v8::PersistentValueMapBase< K, V, Traits >::impl_, v8::internal::key, and v8::PersistentValueMapBase< K, V, Traits >::Release().
Referenced by v8::PersistentValueMap< K, V, Traits >::WeakCallback().
RemoveWeak()
template<typename K , typename V , typename Traits >
void v8::PersistentValueMapBase< K, V, Traits >::RemoveWeak (const K & key) [inline], [protected]
Definition at line 331 of file v8-util.h.
                                {
    Global<V> p;
    p.slot() =
        reinterpret_cast<internal::Address*>(Traits::Remove(&impl_, key));
    p.Reset();
  }
References v8::PersistentValueMapBase< K, V, Traits >::impl_, v8::internal::key, v8::PersistentBase< T >::Reset(), and v8::api_internal::IndirectHandleBase::slot().
SetReturnValue()
template<typename K , typename V , typename Traits >
bool v8::PersistentValueMapBase< K, V, Traits >::SetReturnValue (const K & key, ReturnValue< Value > returnValue) [inline]
Get value stored in map and set it in returnValue.
Return true if a value was found.
Definition at line 202 of file v8-util.h.
                                      {
    return SetReturnValueFromVal(&returnValue, Traits::Get(&impl_, key));
  }
References v8::internal::compiler::turboshaft::Get(), v8::PersistentValueMapBase< K, V, Traits >::impl_, v8::internal::key, and v8::PersistentValueMapBase< K, V, Traits >::SetReturnValueFromVal().
SetReturnValueFromVal()
template<typename K , typename V , typename Traits >
static bool v8::PersistentValueMapBase< K, V, Traits >::SetReturnValueFromVal (ReturnValue< Value > * returnValue, PersistentContainerValue value) [inline], [static], [private]
Definition at line 346 of file v8-util.h.
                                                                    {
    bool hasValue = value != kPersistentContainerNotFound;
    if (hasValue) {
      returnValue->SetInternal(*reinterpret_cast<internal::Address*>(value));
    }
    return hasValue;
  }
References v8::kPersistentContainerNotFound, v8::ReturnValue< T >::SetInternal(), and v8::internal::value.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::SetReturnValue(), and v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::SetReturnValue().
Size()
template<typename K , typename V , typename Traits >
size_t v8::PersistentValueMapBase< K, V, Traits >::Size () [inline]
Return size of the map.
Definition at line 173 of file v8-util.h.
{ return Traits::Size(&impl_); }
References v8::PersistentValueMapBase< K, V, Traits >::impl_.
Member Data Documentation
impl_
template<typename K , typename V , typename Traits >
Traits::Impl v8::PersistentValueMapBase< K, V, Traits >::impl_ [private]
Definition at line 356 of file v8-util.h.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Clear(), v8::PersistentValueMapBase< K, V, Traits >::Contains(), v8::PersistentValueMapBase< K, V, Traits >::Get(), v8::PersistentValueMapBase< K, V, Traits >::GetReference(), v8::PersistentValueMapBase< K, V, Traits >::impl(), v8::PersistentValueMapBase< K, V, Traits >::Remove(), v8::PersistentValueMapBase< K, V, Traits >::RemoveWeak(), v8::PersistentValueMapBase< K, V, Traits >::SetReturnValue(), and v8::PersistentValueMapBase< K, V, Traits >::Size().
isolate_
template<typename K , typename V , typename Traits >
Isolate* v8::PersistentValueMapBase< K, V, Traits >::isolate_ [private]
Definition at line 355 of file v8-util.h.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Clear(), v8::PersistentValueMapBase< K, V, Traits >::Get(), v8::PersistentValueMapBase< K, V, Traits >::GetIsolate(), and v8::PersistentValueMapBase< K, V, Traits >::isolate().
label_
template<typename K , typename V , typename Traits >
const char* v8::PersistentValueMapBase< K, V, Traits >::label_ [private]
Definition at line 357 of file v8-util.h.
Referenced by v8::PersistentValueMapBase< K, V, Traits >::AnnotateStrongRetainer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-initialization.h
/mnt/V8SourceCode/include/v8-util.h