v8::internal::wasm::gdb_server::GdbServer::DebugDelegate Class Reference
Public Member Functions
DebugDelegate (Isolate *isolate, GdbServer *gdb_server)
~DebugDelegate ()
void ScriptCompiled (Local< debug::Script > script, bool is_live_edited, bool has_compile_error) override
void BreakProgramRequested (Local< v8::Context > paused_context, const std::vector< debug::BreakpointId > &inspector_break_points_hit, v8::debug::BreakReasons break_reasons) override
void ExceptionThrown (Local< v8::Context > paused_context, Local< Value > exception, Local< Value > promise, bool is_uncaught, debug::ExceptionType exception_type) override
bool IsFunctionBlackboxed (Local< debug::Script > script, const debug::Location &start, const debug::Location &end) override
Private Member Functions
uint32_t GetModuleId (uint32_t script_id) const
Private Attributes
Isolate * isolate_
uint32_t id_
GdbServer * gdb_server_
Static Private Attributes
static std::atomic< uint32_t > id_s
Additional Inherited Members
Detailed Description
Definition at line 145 of file gdb-server.h.
Constructor & Destructor Documentation
DebugDelegate()
v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::DebugDelegate (Isolate * isolate, GdbServer * gdb_server)
Definition at line 391 of file gdb-server.cc.
    : isolate_(isolate), id_(id_s++), gdb_server_(gdb_server) {
  isolate_->SetCaptureStackTraceForUncaughtExceptions(
      true, kMaxWasmCallStack, v8::StackTrace::kOverview);
  // Register the delegate
  isolate_->debug()->SetDebugDelegate(this);
  v8::debug::EnterDebuggingForIsolate((v8::Isolate*)isolate_);
  v8::debug::ChangeBreakOnException((v8::Isolate*)isolate_,
                                    v8::debug::BreakOnUncaughtException);
}
References v8::debug::BreakOnUncaughtException, v8::debug::ChangeBreakOnException(), v8::internal::Isolate::debug(), isolate_, v8::internal::wasm::gdb_server::kMaxWasmCallStack, v8::StackTrace::kOverview, v8::internal::Isolate::SetCaptureStackTraceForUncaughtExceptions(), and v8::internal::Debug::SetDebugDelegate().
 DebugDelegate()
v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::~DebugDelegate () [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 403 of file gdb-server.cc.
                                       {
  // Deregister the delegate
  isolate_->debug()->SetDebugDelegate(nullptr);
}
Member Function Documentation
BreakProgramRequested()
void v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::BreakProgramRequested (Local< v8::Context > paused_context, const std::vector< debug::BreakpointId > & inspector_break_points_hit, v8::debug::BreakReasons break_reasons) [override]
Definition at line 419 of file gdb-server.cc.
                                       {
  gdb_server_->GetTarget().OnProgramBreak(
      isolate_, WasmModuleDebug::GetCallStack(id_, isolate_));
  gdb_server_->RunMessageLoopOnPause();
}
References v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack().
ExceptionThrown()
void v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::ExceptionThrown (Local< v8::Context > paused_context, Local< Value > exception, Local< Value > promise, bool is_uncaught, debug::ExceptionType exception_type) [override], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 429 of file gdb-server.cc.
                                       {
  if (exception_type == v8::debug::kException && is_uncaught) {
    gdb_server_->GetTarget().OnException(
        isolate_, WasmModuleDebug::GetCallStack(id_, isolate_));
    gdb_server_->RunMessageLoopOnPause();
  }
}
References v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), and v8::debug::kException.
GetModuleId()
uint32_t v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::GetModuleId (uint32_t script_id) const [inline], [private]
Definition at line 171 of file gdb-server.h.
                                                   {
      DCHECK_LT(script_id, 0x10000);
      DCHECK_LT(id_, 0x10000);
      return id_ << 16 | script_id;
    }
References DCHECK_LT, and id_.
IsFunctionBlackboxed()
bool v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::IsFunctionBlackboxed (Local< debug::Script > script, const debug::Location & start, const debug::Location & end) [override], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 441 of file gdb-server.cc.
                              {
  return false;
}
ScriptCompiled()
void v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::ScriptCompiled (Local< debug::Script > script, bool is_live_edited, bool has_compile_error) [override], [virtual]
Reimplemented from v8::debug::DebugDelegate.
Definition at line 408 of file gdb-server.cc.
                                                                      {
  // Executed in the isolate thread.
  if (script->IsWasm()) {
    DCHECK_EQ(reinterpret_cast<v8::Isolate*>(isolate_), script->GetIsolate());
    gdb_server_->AddWasmModule(GetModuleId(script->Id()),
                               script.As<debug::WasmScript>());
  }
}
References DCHECK_EQ, and v8::internal::script.
Member Data Documentation
gdb_server_
GdbServer* v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::gdb_server_ [private]
Definition at line 179 of file gdb-server.h.
id_
uint32_t v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::id_ [private]
Definition at line 178 of file gdb-server.h.
Referenced by GetModuleId().
id_s
std::atomic< uint32_t > v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::id_s [static], [private]
Definition at line 181 of file gdb-server.h.
isolate_
Isolate* v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::isolate_ [private]
Definition at line 177 of file gdb-server.h.
Referenced by DebugDelegate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/gdb-server.cc