v8::bigint::ProcessorImpl Class Reference
#include <bigint-internal.h>
Public Member Functions
ProcessorImpl (Platform *platform)
~ProcessorImpl ()
Status get_and_clear_status ()
void Multiply (RWDigits Z, Digits X, Digits Y)
void MultiplySingle (RWDigits Z, Digits X, digit_t y)
void MultiplySchoolbook (RWDigits Z, Digits X, Digits Y)
void MultiplyKaratsuba (RWDigits Z, Digits X, Digits Y)
void KaratsubaStart (RWDigits Z, Digits X, Digits Y, RWDigits scratch, int k)
void KaratsubaChunk (RWDigits Z, Digits X, Digits Y, RWDigits scratch)
void KaratsubaMain (RWDigits Z, Digits X, Digits Y, RWDigits scratch, int n)
void Divide (RWDigits Q, Digits A, Digits B)
void DivideSingle (RWDigits Q, digit_t *remainder, Digits A, digit_t b)
void DivideSchoolbook (RWDigits Q, RWDigits R, Digits A, Digits B)
void DivideBurnikelZiegler (RWDigits Q, RWDigits R, Digits A, Digits B)
void Modulo (RWDigits R, Digits A, Digits B)
void ToString (char *out, uint32_t *out_length, Digits X, int radix, bool sign)
void ToStringImpl (char *out, uint32_t *out_length, Digits X, int radix, bool sign, bool use_fast_algorithm)
void FromString (RWDigits Z, FromStringAccumulator *accumulator)
void FromStringClassic (RWDigits Z, FromStringAccumulator *accumulator)
void FromStringLarge (RWDigits Z, FromStringAccumulator *accumulator)
void FromStringBasePowerOfTwo (RWDigits Z, FromStringAccumulator *accumulator)
bool should_terminate ()
void AddWorkEstimate (uintptr_t estimate)
Static Public Attributes
static const uintptr_t kWorkEstimateThreshold = 5000000
Private Attributes
uintptr_t work_estimate_ {0}
Status status_ {Status::kOk}
Platform * platform_
Additional Inherited Members
Detailed Description
Definition at line 27 of file bigint-internal.h.
Constructor & Destructor Documentation
ProcessorImpl()
v8::bigint::ProcessorImpl::ProcessorImpl (Platform * platform) [explicit]
Definition at line 19 of file bigint-internal.cc.
: platform_(platform) {}
 ProcessorImpl()
v8::bigint::ProcessorImpl::~ProcessorImpl ()
Definition at line 21 of file bigint-internal.cc.
{ delete platform_; }
References platform_.
Member Function Documentation
AddWorkEstimate()
void v8::bigint::ProcessorImpl::AddWorkEstimate (uintptr_t estimate) [inline]
Definition at line 86 of file bigint-internal.h.
                                           {
    work_estimate_ += estimate;
    if (work_estimate_ >= kWorkEstimateThreshold) {
      work_estimate_ = 0;
      if (platform_->InterruptRequested()) {
        status_ = Status::kInterrupted;
      }
    }
  }
References v8::bigint::Platform::InterruptRequested(), v8::bigint::kInterrupted, kWorkEstimateThreshold, platform_, status_, and work_estimate_.
Referenced by FromStringLarge(), MultiplySchoolbook(), and MultiplySingle().
Divide()
void v8::bigint::ProcessorImpl::Divide (RWDigits Q, Digits A, Digits B)
Definition at line 52 of file bigint-internal.cc.
                                                         {
  A.Normalize();
  B.Normalize();
  // While callers are not required to normalize inputs, they must not
  // provide divisors that normalize to zero.
  // This must be a Release-mode CHECK because it is load bearing for
  // security fuzzing: subsequent operations would perform illegal memory
  // accesses if they attempted to work with zero divisors.
  CHECK(B.len() > 0);
  int cmp = Compare(A, B);
  if (cmp < 0) return Q.Clear();
  if (cmp == 0) {
    Q[0] = 1;
    for (int i = 1; i < Q.len(); i++) Q[i] = 0;
    return;
  }
  if (B.len() == 1) {
    digit_t remainder;
    return DivideSingle(Q, &remainder, A, B[0]);
  }
  if (B.len() < kBurnikelThreshold) {
    return DivideSchoolbook(Q, RWDigits(nullptr, 0), A, B);
  }
#if !V8_ADVANCED_BIGINT_ALGORITHMS
  return DivideBurnikelZiegler(Q, RWDigits(nullptr, 0), A, B);
#else
  if (B.len() < kBarrettThreshold || A.len() == B.len()) {
    DivideBurnikelZiegler(Q, RWDigits(nullptr, 0), A, B);
  } else {
    ScratchDigits R(B.len());
    DivideBarrett(Q, R, A, B);
  }
#endif
}
References v8::internal::A, v8::internal::B, CHECK, v8::bigint::RWDigits::Clear(), v8::bigint::Compare(), DivideBurnikelZiegler(), DivideSchoolbook(), DivideSingle(), v8::bigint::kBarrettThreshold, v8::bigint::kBurnikelThreshold, and v8::bigint::Digits::len().
DivideBurnikelZiegler()
void v8::bigint::ProcessorImpl::DivideBurnikelZiegler (RWDigits Q, RWDigits R, Digits A, Digits B)
Definition at line 197 of file div-burnikel.cc.
                                                    {
  DCHECK(A.len() >= B.len());
  DCHECK(R.len() == 0 || R.len() >= B.len());
  DCHECK(Q.len() > A.len() - B.len());
  int r = A.len();
  int s = B.len();
  // The requirements are:
  // - n >= s, n as small as possible.
  // - m must be a power of two.
  // 1. Set m = min {2^k | 2^k * kBurnikelThreshold > s}.
  int m = 1 << BitLength(s / kBurnikelThreshold);
  // 2. Set j = roundup(s/m) and n = j * m.
  int j = DIV_CEIL(s, m);
  int n = j * m;
  // 3. Set sigma = max{tao | 2^tao * B < 2^(kDigitBits * n)}.
  int sigma = CountLeadingZeros(B[s - 1]);
  int digit_shift = n - s;
  // 4. Set B = B * 2^sigma to normalize B. Shift A by the same amount.
  ScratchDigits B_shifted(n);
  LeftShift(B_shifted + digit_shift, B, sigma);
  for (int i = 0; i < digit_shift; i++) B_shifted[i] = 0;
  B = B_shifted;
  // We need an extra digit if A's top digit does not have enough space for
  // the left-shift by {sigma}. Additionally, the top bit of A must be 0
  // (see "-1" in step 5 below), which combined with B being normalized (i.e.
  // B's top bit is 1) ensures the preconditions of the helper functions.
  int extra_digit = CountLeadingZeros(A[r - 1]) < (sigma + 1) ? 1 : 0;
  r = A.len() + digit_shift + extra_digit;
  ScratchDigits A_shifted(r);
  LeftShift(A_shifted + digit_shift, A, sigma);
  for (int i = 0; i < digit_shift; i++) A_shifted[i] = 0;
  A = A_shifted;
  // 5. Set t = min{t >= 2 | A < 2^(kDigitBits * t * n - 1)}.
  int t = std::max(DIV_CEIL(r, n), 2);
  // 6. Split A conceptually into t blocks.
  // 7. Set Z_(t-2) = [A_(t-1), A_(t-2)].
  int z_len = n * 2;
  ScratchDigits Z(z_len);
  PutAt(Z, A + n * (t - 2), z_len);
  // 8. For i from t-2 downto 0 do:
  BZ bz(this, n);
  ScratchDigits Ri(n);
  {
    // First iteration unrolled and specialized.
    // We might not have n digits at the top of Q, so use temporary storage
    // for Qi...
    ScratchDigits Qi(n);
    bz.D2n1n(Qi, Ri, Z, B);
    if (should_terminate()) return;
    // ...but there *will* be enough space for any non-zero result digits!
    Qi.Normalize();
    RWDigits target = Q + n * (t - 2);
    DCHECK(Qi.len() <= target.len());
    PutAt(target, Qi, target.len());
  }
  // Now loop over any remaining iterations.
  for (int i = t - 3; i >= 0; i--) {
    // 8b. If i > 0, set Z_(i-1) = [Ri, A_(i-1)].
    // (De-duped with unrolled first iteration, hence reading A_(i).)
    PutAt(Z + n, Ri, n);
    PutAt(Z, A + n * i, n);
    // 8a. Using algorithm D2n1n compute Qi, Ri such that Zi = B*Qi + Ri.
    RWDigits Qi(Q, i * n, n);
    bz.D2n1n(Qi, Ri, Z, B);
    if (should_terminate()) return;
  }
  // 9. Return Q = [Q_(t-2), ..., Q_0] and R = R_0 * 2^(-sigma).
#if DEBUG
  for (int i = 0; i < digit_shift; i++) {
    DCHECK(Ri[i] == 0);
  }
#endif
  if (R.len() != 0) {
    Digits Ri_part(Ri, digit_shift, Ri.len());
    Ri_part.Normalize();
    DCHECK(Ri_part.len() <= R.len());
    RightShift(R, Ri_part, sigma);
  }
}
References v8::internal::A, v8::internal::B, v8::bigint::BitLength(), v8::bigint::CountLeadingZeros(), DCHECK, DIV_CEIL, v8::bigint::kBurnikelThreshold, v8::bigint::LeftShift(), v8::bigint::Digits::len(), v8::bigint::Digits::Normalize(), v8::bigint::PutAt(), v8::bigint::RightShift(), and should_terminate().
Referenced by Divide(), and Modulo().
DivideSchoolbook()
void v8::bigint::ProcessorImpl::DivideSchoolbook (RWDigits Q, RWDigits R, Digits A, Digits B)
Definition at line 94 of file div-schoolbook.cc.
                                               {
  DCHECK(B.len() >= 2); // Use DivideSingle otherwise.
  DCHECK(A.len() >= B.len()); // No-op otherwise.
  DCHECK(Q.len() == 0 || QLengthOK(Q, A, B));
  DCHECK(R.len() == 0 || R.len() >= B.len());
  // The unusual variable names inside this function are consistent with
  // Knuth's book, as well as with Go's implementation of this algorithm.
  // Maintaining this consistency is probably more useful than trying to
  // come up with more descriptive names for them.
  const int n = B.len();
  const int m = A.len() - n;
  // In each iteration, {qhatv} holds {divisor} * {current quotient digit}.
  // "v" is the book's name for {divisor}, "qhat" the current quotient digit.
  ScratchDigits qhatv(n + 1);
  // D1.
  // Left-shift inputs so that the divisor's MSB is set. This is necessary
  // to prevent the digit-wise divisions (see digit_div call below) from
  // overflowing (they take a two digits wide input, and return a one digit
  // result).
  ShiftedDigits b_normalized(B);
  B = b_normalized;
  // U holds the (continuously updated) remaining part of the dividend, which
  // eventually becomes the remainder.
  ScratchDigits U(A.len() + 1);
  LeftShift(U, A, b_normalized.shift());
  // D2.
  // Iterate over the dividend's digits (like the "grad school" algorithm).
  // {vn1} is the divisor's most significant digit.
  digit_t vn1 = B[n - 1];
  for (int j = m; j >= 0; j--) {
    // D3.
    // Estimate the current iteration's quotient digit (see Knuth for details).
    // {qhat} is the current quotient digit.
    digit_t qhat = std::numeric_limits<digit_t>::max();
    // {ujn} is the dividend's most significant remaining digit.
    digit_t ujn = U[j + n];
    if (ujn != vn1) {
      // {rhat} is the current iteration's remainder.
      digit_t rhat = 0;
      // Estimate the current quotient digit by dividing the most significant
      // digits of dividend and divisor. The result will not be too small,
      // but could be a bit too large.
      qhat = digit_div(ujn, U[j + n - 1], vn1, &rhat);
      // Decrement the quotient estimate as needed by looking at the next
      // digit, i.e. by testing whether
      // qhat * v_{n-2} > (rhat << kDigitBits) + u_{j+n-2}.
      digit_t vn2 = B[n - 2];
      digit_t ujn2 = U[j + n - 2];
      while (ProductGreaterThan(qhat, vn2, rhat, ujn2)) {
        qhat--;
        digit_t prev_rhat = rhat;
        rhat += vn1;
        // v[n-1] >= 0, so this tests for overflow.
        if (rhat < prev_rhat) break;
      }
    }
    // D4.
    // Multiply the divisor with the current quotient digit, and subtract
    // it from the dividend. If there was "borrow", then the quotient digit
    // was one too high, so we must correct it and undo one subtraction of
    // the (shifted) divisor.
    if (qhat == 0) {
      qhatv.Clear();
    } else {
      MultiplySingle(qhatv, B, qhat);
    }
    digit_t c = InplaceSub(U + j, qhatv);
    if (c != 0) {
      c = InplaceAdd(U + j, B);
      U[j + n] = U[j + n] + c;
      qhat--;
    }
    if (Q.len() != 0) {
      if (j >= Q.len()) {
        DCHECK(qhat == 0);
      } else {
        Q[j] = qhat;
      }
    }
  }
  if (R.len() != 0) {
    RightShift(R, U, b_normalized.shift());
  }
  // If Q has extra storage, clear it.
  for (int i = m + 1; i < Q.len(); i++) Q[i] = 0;
}
References v8::internal::A, v8::internal::B, v8::bigint::RWDigits::Clear(), DCHECK, v8::bigint::digit_div(), v8::bigint::InplaceAdd(), v8::bigint::InplaceSub(), v8::bigint::LeftShift(), v8::bigint::Digits::len(), MultiplySingle(), v8::bigint::ProductGreaterThan(), v8::bigint::RightShift(), v8::bigint::ShiftedDigits::shift(), and v8::base::internal::U.
Referenced by Divide(), and Modulo().
DivideSingle()
void v8::bigint::ProcessorImpl::DivideSingle (RWDigits Q, digit_t * remainder, Digits A, digit_t b)
Definition at line 29 of file div-schoolbook.cc.
                                            {
  DCHECK(b != 0);
  DCHECK(A.len() > 0);
  *remainder = 0;
  int length = A.len();
  if (Q.len() != 0) {
    if (A[length - 1] >= b) {
      DCHECK(Q.len() >= A.len());
      for (int i = length - 1; i >= 0; i--) {
        Q[i] = digit_div(*remainder, A[i], b, remainder);
      }
      for (int i = length; i < Q.len(); i++) Q[i] = 0;
    } else {
      DCHECK(Q.len() >= A.len() - 1);
      *remainder = A[length - 1];
      for (int i = length - 2; i >= 0; i--) {
        Q[i] = digit_div(*remainder, A[i], b, remainder);
      }
      for (int i = length - 1; i < Q.len(); i++) Q[i] = 0;
    }
  } else {
    for (int i = length - 1; i >= 0; i--) {
      digit_div(*remainder, A[i], b, remainder);
    }
  }
}
References v8::internal::A, DCHECK, v8::bigint::digit_div(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), and v8::internal::length.
Referenced by Divide(), and Modulo().
FromString()
void v8::bigint::ProcessorImpl::FromString (RWDigits Z, FromStringAccumulator * accumulator)
Definition at line 306 of file fromstring.cc.
                                                                             {
  if (accumulator->inline_everything_) {
    int i = 0;
    for (; i < accumulator->stack_parts_used_; i++) {
      Z[i] = accumulator->stack_parts_[i];
    }
    for (; i < Z.len(); i++) Z[i] = 0;
  } else if (accumulator->stack_parts_used_ == 0) {
    for (int i = 0; i < Z.len(); i++) Z[i] = 0;
  } else if (IsPowerOfTwo(accumulator->radix_)) {
    FromStringBasePowerOfTwo(Z, accumulator);
  } else if (accumulator->ResultLength() < kFromStringLargeThreshold) {
    FromStringClassic(Z, accumulator);
  } else {
    FromStringLarge(Z, accumulator);
  }
}
References FromStringBasePowerOfTwo(), FromStringClassic(), FromStringLarge(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::FromStringAccumulator::inline_everything_, v8::bigint::IsPowerOfTwo(), v8::bigint::kFromStringLargeThreshold, v8::bigint::Digits::len(), v8::bigint::FromStringAccumulator::radix_, v8::bigint::FromStringAccumulator::ResultLength(), v8::bigint::FromStringAccumulator::stack_parts_, and v8::bigint::FromStringAccumulator::stack_parts_used_.
FromStringBasePowerOfTwo()
void v8::bigint::ProcessorImpl::FromStringBasePowerOfTwo (RWDigits Z, FromStringAccumulator * accumulator)
Definition at line 240 of file fromstring.cc.
                                                    {
  const int num_parts = accumulator->ResultLength();
  DCHECK(num_parts >= 1);
  DCHECK(Z.len() >= num_parts);
  Digits parts(accumulator->heap_parts_.empty()
                   ? accumulator->stack_parts_
                   : accumulator->heap_parts_.data(),
               num_parts);
  uint8_t radix = accumulator->radix_;
  DCHECK(radix == 2 || radix == 4 || radix == 8 || radix == 16 || radix == 32);
  const int char_bits = BitLength(radix - 1);
  const int unused_last_part_bits =
      static_cast<int>(accumulator->last_multiplier_);
  const int unused_part_bits = kDigitBits % char_bits;
  const int max_part_bits = kDigitBits - unused_part_bits;
  int z_index = 0;
  int part_index = num_parts - 1;
  // If the last part is fully populated, then all parts must be, and we can
  // simply copy them (in reversed order).
  if (unused_last_part_bits == 0) {
    DCHECK(kDigitBits % char_bits == 0);
    while (part_index >= 0) {
      Z[z_index++] = parts[part_index--];
    }
    for (; z_index < Z.len(); z_index++) Z[z_index] = 0;
    return;
  }
  // Otherwise we have to shift parts contents around as needed.
  // Holds the next Z digit that we want to store...
  digit_t digit = parts[part_index--];
  // ...and the number of bits (at the right end) we already know.
  int digit_bits = kDigitBits - unused_last_part_bits;
  while (part_index >= 0) {
    // Holds the last part that we read from {parts}...
    digit_t part;
    // ...and the number of bits (at the right end) that we haven't used yet.
    int part_bits;
    while (digit_bits < kDigitBits) {
      part = parts[part_index--];
      part_bits = max_part_bits;
      digit |= part << digit_bits;
      int part_shift = kDigitBits - digit_bits;
      if (part_shift > part_bits) {
        digit_bits += part_bits;
        part = 0;
        part_bits = 0;
        if (part_index < 0) break;
      } else {
        digit_bits = kDigitBits;
        part >>= part_shift;
        part_bits -= part_shift;
      }
    }
    Z[z_index++] = digit;
    digit = part;
    digit_bits = part_bits;
  }
  if (digit_bits > 0) {
    Z[z_index++] = digit;
  }
  for (; z_index < Z.len(); z_index++) Z[z_index] = 0;
}
References v8::bigint::BitLength(), DCHECK, v8::bigint::FromStringAccumulator::heap_parts_, v8::bigint::kDigitBits, v8::bigint::FromStringAccumulator::last_multiplier_, v8::bigint::Digits::len(), v8::bigint::FromStringAccumulator::radix_, v8::bigint::FromStringAccumulator::ResultLength(), and v8::bigint::FromStringAccumulator::stack_parts_.
Referenced by FromString().
FromStringClassic()
void v8::bigint::ProcessorImpl::FromStringClassic (RWDigits Z, FromStringAccumulator * accumulator)
Definition at line 13 of file fromstring.cc.
                                                                          {
  // We always have at least one part to process.
  DCHECK(accumulator->stack_parts_used_ > 0);
  Z[0] = accumulator->stack_parts_[0];
  RWDigits already_set(Z, 0, 1);
  for (int i = 1; i < Z.len(); i++) Z[i] = 0;
  // The {FromStringAccumulator} uses stack-allocated storage for the first
  // few parts; if heap storage is used at all then all parts are copied there.
  int num_stack_parts = accumulator->stack_parts_used_;
  if (num_stack_parts == 1) return;
  const std::vector<digit_t>& heap_parts = accumulator->heap_parts_;
  int num_heap_parts = static_cast<int>(heap_parts.size());
  // All multipliers are the same, except possibly for the last.
  const digit_t max_multiplier = accumulator->max_multiplier_;
  if (num_heap_parts == 0) {
    for (int i = 1; i < num_stack_parts - 1; i++) {
      MultiplySingle(Z, already_set, max_multiplier);
      Add(Z, accumulator->stack_parts_[i]);
      already_set.set_len(already_set.len() + 1);
    }
    MultiplySingle(Z, already_set, accumulator->last_multiplier_);
    Add(Z, accumulator->stack_parts_[num_stack_parts - 1]);
    return;
  }
  // Parts are stored on the heap.
  for (int i = 1; i < num_heap_parts - 1; i++) {
    MultiplySingle(Z, already_set, max_multiplier);
    Add(Z, accumulator->heap_parts_[i]);
    already_set.set_len(already_set.len() + 1);
  }
  MultiplySingle(Z, already_set, accumulator->last_multiplier_);
  Add(Z, accumulator->heap_parts_.back());
}
References v8::bigint::Add(), DCHECK, v8::bigint::FromStringAccumulator::heap_parts_, v8::bigint::FromStringAccumulator::last_multiplier_, v8::bigint::Digits::len(), v8::bigint::FromStringAccumulator::max_multiplier_, MultiplySingle(), v8::bigint::RWDigits::set_len(), v8::bigint::FromStringAccumulator::stack_parts_, and v8::bigint::FromStringAccumulator::stack_parts_used_.
Referenced by FromString().
FromStringLarge()
void v8::bigint::ProcessorImpl::FromStringLarge (RWDigits Z, FromStringAccumulator * accumulator)
Definition at line 89 of file fromstring.cc.
                                                                        {
  int num_parts = static_cast<int>(accumulator->heap_parts_.size());
  DCHECK(num_parts >= 2);
  DCHECK(Z.len() >= num_parts);
  RWDigits parts(accumulator->heap_parts_.data(), num_parts);
  Storage multipliers_storage(num_parts);
  RWDigits multipliers(multipliers_storage.get(), num_parts);
  RWDigits temp(Z, 0, num_parts);
  // Unrolled and specialized first iteration: part_len == 1, so instead of
  // Digits sub-vectors we have individual digit_t values, and the multipliers
  // are known up front.
  {
    digit_t max_multiplier = accumulator->max_multiplier_;
    digit_t last_multiplier = accumulator->last_multiplier_;
    RWDigits new_parts = temp;
    RWDigits new_multipliers = parts;
    int i = 0;
    for (; i + 1 < num_parts; i += 2) {
      digit_t p_in = parts[i];
      digit_t p_in2 = parts[i + 1];
      digit_t m_in = max_multiplier;
      digit_t m_in2 = i == num_parts - 2 ? last_multiplier : max_multiplier;
      // p[j] = p[i] * m[i+1] + p[i+1]
      digit_t p_high;
      digit_t p_low = digit_mul(p_in, m_in2, &p_high);
      digit_t carry;
      new_parts[i] = digit_add2(p_low, p_in2, &carry);
      new_parts[i + 1] = p_high + carry;
      // m[j] = m[i] * m[i+1]
      if (i > 0) {
        if (i > 2 && m_in2 != last_multiplier) {
          new_multipliers[i] = new_multipliers[i - 2];
          new_multipliers[i + 1] = new_multipliers[i - 1];
        } else {
          digit_t m_high;
          new_multipliers[i] = digit_mul(m_in, m_in2, &m_high);
          new_multipliers[i + 1] = m_high;
        }
      }
    }
    // Trailing last part (if {num_parts} was odd).
    if (i < num_parts) {
      new_parts[i] = parts[i];
      new_multipliers[i] = last_multiplier;
      i += 2;
    }
    num_parts = i >> 1;
    RWDigits new_temp = multipliers;
    parts = new_parts;
    multipliers = new_multipliers;
    temp = new_temp;
    AddWorkEstimate(num_parts);
  }
  int part_len = 2;
  // Remaining iterations.
  while (num_parts > 1) {
    RWDigits new_parts = temp;
    RWDigits new_multipliers = parts;
    int new_part_len = part_len * 2;
    int i = 0;
    for (; i + 1 < num_parts; i += 2) {
      int start = i * part_len;
      Digits p_in(parts, start, part_len);
      Digits p_in2(parts, start + part_len, part_len);
      Digits m_in(multipliers, start, part_len);
      Digits m_in2(multipliers, start + part_len, part_len);
      RWDigits p_out(new_parts, start, new_part_len);
      RWDigits m_out(new_multipliers, start, new_part_len);
      // p[j] = p[i] * m[i+1] + p[i+1]
      Multiply(p_out, p_in, m_in2);
      if (should_terminate()) return;
      digit_t overflow = AddAndReturnOverflow(p_out, p_in2);
      DCHECK(overflow == 0);
      USE(overflow);
      // m[j] = m[i] * m[i+1]
      if (i > 0) {
        bool copied = false;
        if (i > 2) {
          int prev_start = (i - 2) * part_len;
          Digits m_in_prev(multipliers, prev_start, part_len);
          Digits m_in2_prev(multipliers, prev_start + part_len, part_len);
          if (Compare(m_in, m_in_prev) == 0 &&
              Compare(m_in2, m_in2_prev) == 0) {
            copied = true;
            Digits m_out_prev(new_multipliers, prev_start, new_part_len);
            for (int k = 0; k < new_part_len; k++) m_out[k] = m_out_prev[k];
          }
        }
        if (!copied) {
          Multiply(m_out, m_in, m_in2);
          if (should_terminate()) return;
        }
      }
    }
    // Trailing last part (if {num_parts} was odd).
    if (i < num_parts) {
      Digits p_in(parts, i * part_len, part_len);
      Digits m_in(multipliers, i * part_len, part_len);
      RWDigits p_out(new_parts, i * part_len, new_part_len);
      RWDigits m_out(new_multipliers, i * part_len, new_part_len);
      int k = 0;
      for (; k < p_in.len(); k++) p_out[k] = p_in[k];
      for (; k < p_out.len(); k++) p_out[k] = 0;
      k = 0;
      for (; k < m_in.len(); k++) m_out[k] = m_in[k];
      for (; k < m_out.len(); k++) m_out[k] = 0;
      i += 2;
    }
    num_parts = i >> 1;
    part_len = new_part_len;
    RWDigits new_temp = multipliers;
    parts = new_parts;
    multipliers = new_multipliers;
    temp = new_temp;
  }
  // Copy the result to Z, if it doesn't happen to be there already.
  if (parts.digits() != Z.digits()) {
    int i = 0;
    for (; i < parts.len(); i++) Z[i] = parts[i];
    // Z might be bigger than we requested; be robust towards that.
    for (; i < Z.len(); i++) Z[i] = 0;
  }
}
References v8::bigint::AddAndReturnOverflow(), AddWorkEstimate(), v8::internal::carry, v8::bigint::Compare(), DCHECK, v8::bigint::digit_add2(), v8::bigint::digit_mul(), v8::bigint::RWDigits::digits(), v8::bigint::Storage::get(), v8::bigint::FromStringAccumulator::heap_parts_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::FromStringAccumulator::last_multiplier_, v8::bigint::Digits::len(), v8::bigint::FromStringAccumulator::max_multiplier_, Multiply(), v8::internal::overflow, should_terminate(), and USE.
Referenced by FromString().
get_and_clear_status()
Status v8::bigint::ProcessorImpl::get_and_clear_status ()
Definition at line 23 of file bigint-internal.cc.
                                           {
  Status result = status_;
  status_ = Status::kOk;
  return result;
}
References v8::bigint::kOk, v8::base::internal::result, and status_.
KaratsubaChunk()
void v8::bigint::ProcessorImpl::KaratsubaChunk (RWDigits Z, Digits X, Digits Y, RWDigits scratch)
Definition at line 137 of file mul-karatsuba.cc.
                                                     {
  X.Normalize();
  Y.Normalize();
  if (X.len() == 0 || Y.len() == 0) return Z.Clear();
  if (X.len() < Y.len()) std::swap(X, Y);
  if (Y.len() == 1) return MultiplySingle(Z, X, Y[0]);
  if (Y.len() < kKaratsubaThreshold) return MultiplySchoolbook(Z, X, Y);
  int k = KaratsubaLength(Y.len());
  DCHECK(scratch.len() >= 4 * k);
  return KaratsubaStart(Z, X, Y, scratch, k);
}
References v8::bigint::RWDigits::Clear(), DCHECK, v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaLength(), KaratsubaStart(), v8::bigint::kKaratsubaThreshold, v8::bigint::Digits::len(), MultiplySchoolbook(), MultiplySingle(), v8::bigint::Digits::Normalize(), and X().
Referenced by KaratsubaStart().
KaratsubaMain()
void v8::bigint::ProcessorImpl::KaratsubaMain (RWDigits Z, Digits X, Digits Y, RWDigits scratch, int n)
Definition at line 151 of file mul-karatsuba.cc.
                                                           {
  if (n < kKaratsubaThreshold) {
    X.Normalize();
    Y.Normalize();
    if (X.len() >= Y.len()) {
      return MultiplySchoolbook(RWDigits(Z, 0, 2 * n), X, Y);
    } else {
      return MultiplySchoolbook(RWDigits(Z, 0, 2 * n), Y, X);
    }
  }
  DCHECK(scratch.len() >= 4 * n);
  DCHECK((n & 1) == 0);
  int n2 = n >> 1;
  Digits X0(X, 0, n2);
  Digits X1(X, n2, n2);
  Digits Y0(Y, 0, n2);
  Digits Y1(Y, n2, n2);
  RWDigits scratch_for_recursion(scratch, 2 * n, 2 * n);
  RWDigits P0(scratch, 0, n);
  KaratsubaMain(P0, X0, Y0, scratch_for_recursion, n2);
  MAYBE_TERMINATE
  for (int i = 0; i < n; i++) Z[i] = P0[i];
  RWDigits P2(scratch, n, n);
  KaratsubaMain(P2, X1, Y1, scratch_for_recursion, n2);
  MAYBE_TERMINATE
  RWDigits Z2 = Z + n;
  int end = std::min(Z2.len(), P2.len());
  for (int i = 0; i < end; i++) Z2[i] = P2[i];
  for (int i = end; i < n; i++) {
    DCHECK(P2[i] == 0);
  }
  // The intermediate result can be one digit too large; the subtraction
  // below will fix this.
  digit_t overflow = AddAndReturnOverflow(Z + n2, P0);
  overflow += AddAndReturnOverflow(Z + n2, P2);
  RWDigits X_diff(scratch, 0, n2);
  RWDigits Y_diff(scratch, n2, n2);
  int sign = 1;
  KaratsubaSubtractionHelper(X_diff, X1, X0, &sign);
  KaratsubaSubtractionHelper(Y_diff, Y0, Y1, &sign);
  RWDigits P1(scratch, n, n);
  KaratsubaMain(P1, X_diff, Y_diff, scratch_for_recursion, n2);
  if (sign > 0) {
    overflow += AddAndReturnOverflow(Z + n2, P1);
  } else {
    overflow -= SubAndReturnBorrow(Z + n2, P1);
  }
  // The intermediate result may have been bigger, but the final result fits.
  DCHECK(overflow == 0);
  USE(overflow);
}
References v8::bigint::AddAndReturnOverflow(), DCHECK, v8::internal::compiler::end(), v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaSubtractionHelper(), v8::bigint::kKaratsubaThreshold, v8::bigint::Digits::len(), MAYBE_TERMINATE, MultiplySchoolbook(), v8::bigint::Digits::Normalize(), v8::internal::overflow, v8::internal::sign, v8::bigint::SubAndReturnBorrow(), USE, and X().
Referenced by KaratsubaStart().
KaratsubaStart()
void v8::bigint::ProcessorImpl::KaratsubaStart (RWDigits Z, Digits X, Digits Y, RWDigits scratch, int k)
Definition at line 103 of file mul-karatsuba.cc.
                                                            {
  KaratsubaMain(Z, X, Y, scratch, k);
  MAYBE_TERMINATE
  for (int i = 2 * k; i < Z.len(); i++) Z[i] = 0;
  if (k < Y.len() || X.len() != Y.len()) {
    ScratchDigits T(2 * k);
    // Add X0 * Y1 * b.
    Digits X0(X, 0, k);
    Digits Y1 = Y + std::min(k, Y.len());
    if (Y1.len() > 0) {
      KaratsubaChunk(T, X0, Y1, scratch);
      MAYBE_TERMINATE
      AddAndReturnOverflow(Z + k, T); // Can't overflow.
    }
    // Add Xi * Y0 << i and Xi * Y1 * b << (i + k).
    Digits Y0(Y, 0, k);
    for (int i = k; i < X.len(); i += k) {
      Digits Xi(X, i, k);
      KaratsubaChunk(T, Xi, Y0, scratch);
      MAYBE_TERMINATE
      AddAndReturnOverflow(Z + i, T); // Can't overflow.
      if (Y1.len() > 0) {
        KaratsubaChunk(T, Xi, Y1, scratch);
        MAYBE_TERMINATE
        AddAndReturnOverflow(Z + (i + k), T); // Can't overflow.
      }
    }
  }
}
References v8::bigint::AddAndReturnOverflow(), KaratsubaChunk(), KaratsubaMain(), v8::bigint::Digits::len(), MAYBE_TERMINATE, T, and X().
Referenced by KaratsubaChunk(), and MultiplyKaratsuba().
Modulo()
void v8::bigint::ProcessorImpl::Modulo (RWDigits R, Digits A, Digits B)
Definition at line 87 of file bigint-internal.cc.
                                                         {
  A.Normalize();
  B.Normalize();
  // While callers are not required to normalize inputs, they must not
  // provide divisors that normalize to zero.
  // This must be a Release-mode CHECK because it is load bearing for
  // security fuzzing: subsequent operations would perform illegal memory
  // accesses if they attempted to work with zero divisors.
  CHECK(B.len() > 0);
  int cmp = Compare(A, B);
  if (cmp < 0) {
    for (int i = 0; i < B.len(); i++) R[i] = B[i];
    for (int i = B.len(); i < R.len(); i++) R[i] = 0;
    return;
  }
  if (cmp == 0) return R.Clear();
  if (B.len() == 1) {
    digit_t remainder;
    DivideSingle(RWDigits(nullptr, 0), &remainder, A, B[0]);
    R[0] = remainder;
    for (int i = 1; i < R.len(); i++) R[i] = 0;
    return;
  }
  if (B.len() < kBurnikelThreshold) {
    return DivideSchoolbook(RWDigits(nullptr, 0), R, A, B);
  }
  int q_len = DivideResultLength(A, B);
  ScratchDigits Q(q_len);
#if !V8_ADVANCED_BIGINT_ALGORITHMS
  return DivideBurnikelZiegler(Q, R, A, B);
#else
  if (B.len() < kBarrettThreshold || A.len() == B.len()) {
    DivideBurnikelZiegler(Q, R, A, B);
  } else {
    DivideBarrett(Q, R, A, B);
  }
#endif
}
References v8::internal::A, v8::internal::B, CHECK, v8::bigint::RWDigits::Clear(), v8::bigint::Compare(), DivideBurnikelZiegler(), v8::bigint::DivideResultLength(), DivideSchoolbook(), DivideSingle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::kBarrettThreshold, v8::bigint::kBurnikelThreshold, and v8::bigint::Digits::len().
Multiply()
void v8::bigint::ProcessorImpl::Multiply (RWDigits Z, Digits X, Digits Y)
Definition at line 36 of file bigint-internal.cc.
                                                           {
  X.Normalize();
  Y.Normalize();
  if (X.len() == 0 || Y.len() == 0) return Z.Clear();
  if (X.len() < Y.len()) std::swap(X, Y);
  if (Y.len() == 1) return MultiplySingle(Z, X, Y[0]);
  if (Y.len() < kKaratsubaThreshold) return MultiplySchoolbook(Z, X, Y);
#if !V8_ADVANCED_BIGINT_ALGORITHMS
  return MultiplyKaratsuba(Z, X, Y);
#else
  if (Y.len() < kToomThreshold) return MultiplyKaratsuba(Z, X, Y);
  if (Y.len() < kFftThreshold) return MultiplyToomCook(Z, X, Y);
  return MultiplyFFT(Z, X, Y);
#endif
}
References v8::bigint::RWDigits::Clear(), v8::bigint::kFftThreshold, v8::bigint::kKaratsubaThreshold, v8::bigint::kToomThreshold, v8::bigint::Digits::len(), MultiplyKaratsuba(), MultiplySchoolbook(), MultiplySingle(), v8::bigint::Digits::Normalize(), and X().
Referenced by FromStringLarge().
MultiplyKaratsuba()
void v8::bigint::ProcessorImpl::MultiplyKaratsuba (RWDigits Z, Digits X, Digits Y)
Definition at line 91 of file mul-karatsuba.cc.
                                                                    {
  DCHECK(X.len() >= Y.len());
  DCHECK(Y.len() >= kKaratsubaThreshold);
  DCHECK(Z.len() >= X.len() + Y.len());
  int k = KaratsubaLength(Y.len());
  int scratch_len = 4 * k;
  ScratchDigits scratch(scratch_len);
  KaratsubaStart(Z, X, Y, scratch, k);
}
References DCHECK, v8::bigint::anonymous_namespace{mul-karatsuba.cc}::KaratsubaLength(), KaratsubaStart(), v8::bigint::kKaratsubaThreshold, v8::bigint::Digits::len(), and X().
Referenced by Multiply().
MultiplySchoolbook()
void v8::bigint::ProcessorImpl::MultiplySchoolbook (RWDigits Z, Digits X, Digits Y)
Definition at line 49 of file mul-schoolbook.cc.
                                                                     {
  DCHECK(IsDigitNormalized(X));
  DCHECK(IsDigitNormalized(Y));
  DCHECK(X.len() >= Y.len());
  DCHECK(Z.len() >= X.len() + Y.len());
  if (X.len() == 0 || Y.len() == 0) return Z.Clear();
  digit_t next, next_carry = 0, carry = 0;
  // Unrolled first iteration: it's trivial.
  Z[0] = digit_mul(X[0], Y[0], &next);
  int i = 1;
  // Unrolled second iteration: a little less setup.
  if (i < Y.len()) {
    digit_t zi = next;
    next = 0;
    BODY(0, 1);
    i++;
  }
  // Main part: since X.len() >= Y.len() > i, no bounds checks are needed.
  for (; i < Y.len(); i++) {
    digit_t zi = digit_add2(next, carry, &carry);
    next = next_carry + carry;
    carry = 0;
    next_carry = 0;
    BODY(0, i);
    AddWorkEstimate(i);
  }
  // Last part: i exceeds Y now, we have to be careful about bounds.
  int loop_end = X.len() + Y.len() - 2;
  for (; i <= loop_end; i++) {
    int max_x_index = std::min(i, X.len() - 1);
    int max_y_index = Y.len() - 1;
    int min_x_index = i - max_y_index;
    digit_t zi = digit_add2(next, carry, &carry);
    next = next_carry + carry;
    carry = 0;
    next_carry = 0;
    BODY(min_x_index, max_x_index);
    AddWorkEstimate(max_x_index - min_x_index);
  }
  // Write the last digit, and zero out any extra space in Z.
  Z[i++] = digit_add2(next, carry, &carry);
  DCHECK(carry == 0);
  for (; i < Z.len(); i++) Z[i] = 0;
}
References AddWorkEstimate(), BODY, v8::internal::carry, v8::bigint::RWDigits::Clear(), DCHECK, v8::bigint::digit_add2(), v8::bigint::digit_mul(), v8::bigint::IsDigitNormalized(), v8::bigint::Digits::len(), and X().
Referenced by KaratsubaChunk(), KaratsubaMain(), and Multiply().
MultiplySingle()
void v8::bigint::ProcessorImpl::MultiplySingle (RWDigits Z, Digits X, digit_t y)
Definition at line 13 of file mul-schoolbook.cc.
                                                                  {
  DCHECK(y != 0);
  digit_t carry = 0;
  digit_t high = 0;
  for (int i = 0; i < X.len(); i++) {
    digit_t new_high;
    digit_t low = digit_mul(X[i], y, &new_high);
    Z[i] = digit_add3(low, high, carry, &carry);
    high = new_high;
  }
  AddWorkEstimate(X.len());
  Z[X.len()] = carry + high;
  for (int i = X.len() + 1; i < Z.len(); i++) Z[i] = 0;
}
References AddWorkEstimate(), v8::internal::carry, DCHECK, v8::bigint::digit_add3(), v8::bigint::digit_mul(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::bigint::Digits::len(), X(), and v8::base::internal::y.
Referenced by DivideSchoolbook(), FromStringClassic(), KaratsubaChunk(), and Multiply().
should_terminate()
bool v8::bigint::ProcessorImpl::should_terminate () [inline]
Definition at line 77 of file bigint-internal.h.
{ return status_ == Status::kInterrupted; }
References v8::bigint::kInterrupted, and status_.
Referenced by DivideBurnikelZiegler(), FromStringLarge(), v8::bigint::anonymous_namespace{mul-fft.cc}::MultiplyFFT_Inner(), and ToStringImpl().
ToString()
void v8::bigint::ProcessorImpl::ToString (char * out, uint32_t * out_length, Digits X, int radix, bool sign)
Definition at line 558 of file tostring.cc.
                                                   {
  const bool use_fast_algorithm = X.len() >= kToStringFastThreshold;
  ToStringImpl(out, out_length, X, radix, sign, use_fast_algorithm);
}
References v8::bigint::kToStringFastThreshold, v8::internal::sign, ToStringImpl(), and X().
ToStringImpl()
void v8::bigint::ProcessorImpl::ToStringImpl (char * out, uint32_t * out_length, Digits X, int radix, bool sign, bool use_fast_algorithm)
Definition at line 565 of file tostring.cc.
                                                                  {
#if DEBUG
  for (uint32_t i = 0; i < *out_length; i++) out[i] = kStringZapValue;
#endif
  ToStringFormatter formatter(X, radix, sign, out, *out_length, this);
  if (IsPowerOfTwo(radix)) {
    formatter.BasePowerOfTwo();
#if V8_ADVANCED_BIGINT_ALGORITHMS
  } else if (fast) {
    formatter.Start();
    formatter.Fast();
    if (should_terminate()) return;
#else
    USE(fast);
#endif // V8_ADVANCED_BIGINT_ALGORITHMS
  } else {
    formatter.Start();
    formatter.Classic();
  }
  int excess = formatter.Finish();
  *out_length -= excess;
  memset(out + *out_length, 0, excess);
}
References v8::bigint::IsPowerOfTwo(), v8::bigint::kStringZapValue, should_terminate(), v8::internal::sign, USE, and X().
Referenced by ToString().
Member Data Documentation
kWorkEstimateThreshold
const uintptr_t v8::bigint::ProcessorImpl::kWorkEstimateThreshold = 5000000 [static]
Definition at line 84 of file bigint-internal.h.
Referenced by AddWorkEstimate().
platform_
Platform* v8::bigint::ProcessorImpl::platform_ [private]
Definition at line 99 of file bigint-internal.h.
Referenced by AddWorkEstimate(), and ~ProcessorImpl().
status_
Status v8::bigint::ProcessorImpl::status_ {Status::kOk} [private]
Definition at line 98 of file bigint-internal.h.
Referenced by AddWorkEstimate(), get_and_clear_status(), and should_terminate().
work_estimate_
uintptr_t v8::bigint::ProcessorImpl::work_estimate_ {0} [private]
Definition at line 97 of file bigint-internal.h.
Referenced by AddWorkEstimate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/bigint/bigint-internal.h
/mnt/V8SourceCode/src/bigint/bigint-internal.cc
/mnt/V8SourceCode/src/bigint/div-burnikel.cc
/mnt/V8SourceCode/src/bigint/div-schoolbook.cc
/mnt/V8SourceCode/src/bigint/fromstring.cc
/mnt/V8SourceCode/src/bigint/mul-karatsuba.cc
/mnt/V8SourceCode/src/bigint/mul-schoolbook.cc
/mnt/V8SourceCode/src/bigint/tostring.cc