v8::internal::torque::AggregateType Class Reference
#include <types.h>
Public Member Functions
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
virtual void Finalize () const =0
void SetFields (std::vector< Field > fields)
const std::vector< Field > & fields () const
bool HasField (const std::string &name) const
const Field & LookupField (const std::string &name) const
const std::string & name () const
Namespace * nspace () const
virtual const Field & RegisterField (Field field)
void RegisterMethod (Method *method)
const std::vector< Method * > & Methods () const
std::vector< Method * > Methods (const std::string &name) const
std::vector< const AggregateType * > GetHierarchy () const
std::vector< TypeChecker > GetTypeCheckers () const override
const Field & LastField () const
Protected Member Functions
AggregateType (Kind kind, const Type *parent, Namespace *nspace, const std::string &name, MaybeSpecializationKey specialized_from=std::nullopt)
void CheckForDuplicateFields () const
const Field & LookupFieldInternal (const std::string &name) const
std::string SimpleNameImpl () const override
Protected Attributes
bool is_finalized_
std::vector< Field > fields_
Private Attributes
Namespace * namespace_
std::string name_
std::vector< Method * > methods_
Additional Inherited Members
Detailed Description
Definition at line 547 of file types.h.
Constructor & Destructor Documentation
AggregateType()
v8::internal::torque::AggregateType::AggregateType (Kind kind, const Type * parent, Namespace * nspace, const std::string & name, MaybeSpecializationKey specialized_from = std::nullopt) [inline], [protected]
Definition at line 593 of file types.h.
      : Type(kind, parent, specialized_from),
        is_finalized_(false),
        namespace_(nspace),
        name_(name) {}
Member Function Documentation
CheckForDuplicateFields()
void v8::internal::torque::AggregateType::CheckForDuplicateFields () const [protected]
Definition at line 430 of file types.cc.
                                                  {
  // Check the aggregate hierarchy and currently defined class for duplicate
  // field declarations.
  auto hierarchy = GetHierarchy();
  std::map<std::string, const AggregateType*> field_names;
  for (const AggregateType* aggregate_type : hierarchy) {
    for (const Field& field : aggregate_type->fields()) {
      const std::string& field_name = field.name_and_type.name;
      auto i = field_names.find(field_name);
      if (i != field_names.end()) {
        CurrentSourcePosition::Scope current_source_position(field.pos);
        std::string aggregate_type_name =
            aggregate_type->IsClassType() ? "class" : "struct";
        if (i->second == this) {
          ReportError(aggregate_type_name, " '", name(),
                      "' declares a field with the name '", field_name,
                      "' more than once");
        } else {
          ReportError(aggregate_type_name, " '", name(),
                      "' declares a field with the name '", field_name,
                      "' that masks an inherited field from class '",
                      i->second->name(), "'");
        }
      }
      field_names[field_name] = aggregate_type;
    }
  }
}
References name, v8::internal::torque::ReportError(), and v8::internal::string.
Referenced by v8::internal::torque::StructType::Finalize(), and v8::internal::torque::ClassType::Finalize().
fields()
const std::vector<Field>& v8::internal::torque::AggregateType::fields () const [inline]
Definition at line 556 of file types.h.
                                         {
    if (!is_finalized_) Finalize();
    return fields_;
  }
References fields_, Finalize(), and is_finalized_.
Referenced by v8::internal::torque::StructType::AlignmentLog2(), v8::internal::torque::StructType::ClassifyContents(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CollectAllFields(), v8::internal::torque::ClassType::ComputeAllFields(), v8::internal::torque::ImplementationVisitor::GenerateCSATypes(), v8::internal::torque::ImplementationVisitor::InitializeClass(), LastField(), v8::internal::torque::StructType::PackedSize(), and SetFields().
Finalize()
virtual void v8::internal::torque::AggregateType::Finalize () const [pure virtual]
Implemented in v8::internal::torque::ClassType, and v8::internal::torque::StructType.
Referenced by fields(), and Methods().
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::AggregateType::GetGeneratedTNodeTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Reimplemented in v8::internal::torque::ClassType.
Definition at line 551 of file types.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::AggregateType::GetGeneratedTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Reimplemented in v8::internal::torque::ClassType, and v8::internal::torque::StructType.
Definition at line 550 of file types.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
GetHierarchy()
std::vector< const AggregateType * > v8::internal::torque::AggregateType::GetHierarchy () const
Definition at line 459 of file types.cc.
                                                                  {
  if (!is_finalized_) Finalize();
  std::vector<const AggregateType*> hierarchy;
  const AggregateType* current_container_type = this;
  while (current_container_type != nullptr) {
    hierarchy.push_back(current_container_type);
    current_container_type =
        current_container_type->IsClassType()
            ? ClassType::cast(current_container_type)->GetSuperClass()
            : nullptr;
  }
  std::reverse(hierarchy.begin(), hierarchy.end());
  return hierarchy;
}
References v8::internal::torque::TypeBase::IsClassType().
GetTypeCheckers()
std::vector<TypeChecker> v8::internal::torque::AggregateType::GetTypeCheckers () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 578 of file types.h.
                                                          {
    return {{name_, ""}};
  }
References name_.
HasField()
bool v8::internal::torque::AggregateType::HasField (const std::string & name) const
Definition at line 474 of file types.cc.
                                                        {
  if (!is_finalized_) Finalize();
  for (auto& field : fields_) {
    if (field.name_and_type.name == name) return true;
  }
  if (parent() != nullptr) {
    if (auto parent_class = ClassType::DynamicCast(parent())) {
      return parent_class->HasField(name);
    }
  }
  return false;
}
References name.
Referenced by v8::internal::torque::ExtractSimpleFieldArraySize().
LastField()
const Field& v8::internal::torque::AggregateType::LastField () const [inline]
Definition at line 582 of file types.h.
                                 {
    for (std::optional<const AggregateType*> current = this;
         current.has_value();
         current = (*current)->parent()->AggregateSupertype()) {
      const std::vector<Field>& fields = (*current)->fields_;
      if (!fields.empty()) return fields[fields.size() - 1];
    }
    ReportError("Can't get last field of empty aggregate type");
  }
References v8::internal::torque::Type::AggregateSupertype(), fields(), and v8::internal::torque::ReportError().
LookupField()
const Field & v8::internal::torque::AggregateType::LookupField (const std::string & name) const
Definition at line 499 of file types.cc.
                                                                   {
  if (!is_finalized_) Finalize();
  return LookupFieldInternal(name);
}
References name.
Referenced by v8::internal::torque::ExtractSimpleFieldArraySize(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitInitializerResults().
LookupFieldInternal()
const Field & v8::internal::torque::AggregateType::LookupFieldInternal (const std::string & name) const [protected]
Definition at line 487 of file types.cc.
                                                                           {
  for (auto& field : fields_) {
    if (field.name_and_type.name == name) return field;
  }
  if (parent() != nullptr) {
    if (auto parent_class = ClassType::DynamicCast(parent())) {
      return parent_class->LookupField(name);
    }
  }
  ReportError("no field ", name, " found in ", this->ToString());
}
References name, v8::internal::torque::ReportError(), and ToString().
Methods() [1/2]
const std::vector<Method*>& v8::internal::torque::AggregateType::Methods () const [inline]
Definition at line 571 of file types.h.
                                            {
    if (!is_finalized_) Finalize();
    return methods_;
  }
References Finalize(), is_finalized_, and methods_.
Referenced by v8::internal::torque::ImplementationVisitor::LookupMethod().
Methods() [2/2]
std::vector< Method * > v8::internal::torque::AggregateType::Methods (const std::string & name) const
Definition at line 586 of file types.cc.
                                                                     {
  if (!is_finalized_) Finalize();
  std::vector<Method*> result;
  std::copy_if(methods_.begin(), methods_.end(), std::back_inserter(result),
               [name](Macro* macro) { return macro->ReadableName() == name; });
  if (result.empty() && parent() != nullptr) {
    if (auto aggregate_parent = parent()->AggregateSupertype()) {
      return (*aggregate_parent)->Methods(name);
    }
  }
  return result;
}
References v8::internal::torque::Type::AggregateSupertype(), Finalize(), is_finalized_, methods_, name(), v8::internal::torque::Type::parent(), and v8::base::internal::result.
name()
const std::string& v8::internal::torque::AggregateType::name () const [inline]
Definition at line 562 of file types.h.
{ return name_; }
References name_.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::FirstFieldStart(), v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClassConstructors(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateClassDebugReader(), v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassExport(), v8::internal::torque::ImplementationVisitor::GenerateClassVerifiers(), v8::internal::torque::ImplementationVisitor::GeneratePrintDefinitions(), v8::internal::torque::ClassType::GetSliceMacroName(), Methods(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::CompareUnconstrainedTypes::operator()(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SelectOwnValues(), v8::internal::torque::StructType::StructType(), v8::internal::torque::StructType::ToExplicitString(), v8::internal::torque::ClassType::ToExplicitString(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::UpdateSection(), and v8::internal::torque::ImplementationVisitor::Visit().
nspace()
Namespace* v8::internal::torque::AggregateType::nspace () const [inline]
Definition at line 563 of file types.h.
{ return namespace_; }
References namespace_.
Referenced by v8::internal::torque::ClassType::AllowInstantiation(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::StructType::Finalize(), and v8::internal::torque::ImplementationVisitor::GenerateArrayLength().
RegisterField()
virtual const Field& v8::internal::torque::AggregateType::RegisterField (Field field) [inline], [virtual]
Reimplemented in v8::internal::torque::ClassType.
Definition at line 565 of file types.h.
                                                  {
    fields_.push_back(field);
    return fields_.back();
  }
References fields_.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::ClassType::RegisterField().
RegisterMethod()
void v8::internal::torque::AggregateType::RegisterMethod (Method * method) [inline]
Definition at line 570 of file types.h.
{ methods_.push_back(method); }
References methods_.
Referenced by v8::internal::torque::Declarations::CreateMethod().
SetFields()
void v8::internal::torque::AggregateType::SetFields (std::vector< Field > fields) [inline]
Definition at line 555 of file types.h.
{ fields_ = std::move(fields); }
References fields(), and fields_.
SimpleNameImpl()
std::string v8::internal::torque::AggregateType::SimpleNameImpl () const [inline], [override], [protected], [virtual]
Implements v8::internal::torque::Type.
Reimplemented in v8::internal::torque::StructType.
Definition at line 604 of file types.h.
{ return name_; }
References name_.
Member Data Documentation
fields_
std::vector<Field> v8::internal::torque::AggregateType::fields_ [protected]
Definition at line 608 of file types.h.
Referenced by fields(), v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ClassType::GenerateSliceAccessor(), v8::internal::torque::ClassType::GetClassDeclaringField(), v8::internal::torque::ClassType::GetFieldPreceding(), v8::internal::torque::ClassType::HasIndexedFieldsIncludingInParents(), RegisterField(), and SetFields().
is_finalized_
bool v8::internal::torque::AggregateType::is_finalized_ [mutable], [protected]
Definition at line 607 of file types.h.
Referenced by fields(), v8::internal::torque::StructType::Finalize(), v8::internal::torque::ClassType::Finalize(), v8::internal::torque::ClassType::header_size(), Methods(), and v8::internal::torque::ClassType::size().
methods_
std::vector<Method*> v8::internal::torque::AggregateType::methods_ [private]
Definition at line 613 of file types.h.
Referenced by Methods(), and RegisterMethod().
name_
std::string v8::internal::torque::AggregateType::name_ [private]
Definition at line 612 of file types.h.
Referenced by GetTypeCheckers(), name(), and SimpleNameImpl().
namespace_
Namespace* v8::internal::torque::AggregateType::namespace_ [private]
Definition at line 611 of file types.h.
Referenced by nspace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc