v8::internal::ReadOnlyHeap Class Reference
#include <read-only-heap.h>
Public Member Functions
ReadOnlyHeap (ReadOnlySpace *ro_space)
~ReadOnlyHeap ()
ReadOnlyHeap (const ReadOnlyHeap &)=delete
ReadOnlyHeap & operator= (const ReadOnlyHeap &)=delete
V8_EXPORT_PRIVATE void OnCreateHeapObjectsComplete (Isolate *isolate)
void OnCreateRootsComplete (Isolate *isolate)
ReadOnlySpace * read_only_space () const
void InitializeIsolateRoots (Isolate *isolate)
void InitializeFromIsolateRoots (Isolate *isolate)
bool roots_init_complete () const
Static Public Member Functions
static void SetUp (Isolate *isolate, SnapshotData *read_only_snapshot_data, bool can_rehash)
static void PopulateReadOnlySpaceStatistics (SharedMemoryStatistics *statistics)
static V8_EXPORT_PRIVATE bool Contains (Address address)
static V8_EXPORT_PRIVATE bool Contains (Tagged< HeapObject > object)
static V8_EXPORT_PRIVATE bool SandboxSafeContains (Tagged< HeapObject > object)
static V8_EXPORT_PRIVATE ReadOnlyRoots EarlyGetReadOnlyRoots (Tagged< HeapObject > object)
Static Public Attributes
static constexpr size_t kEntriesCount
Protected Member Functions
void DeserializeIntoIsolate (Isolate *isolate, SnapshotData *read_only_snapshot_data, bool can_rehash)
void InitFromIsolate (Isolate *isolate)
Static Protected Member Functions
static void CreateInitialHeapForBootstrapping (Isolate *isolate, ReadOnlyArtifacts *artifacts)
Protected Attributes
bool roots_init_complete_ = false
ReadOnlySpace * read_only_space_ = nullptr
Private Attributes
Address read_only_roots_ [kEntriesCount]
Friends
class ReadOnlyArtifacts
ReadOnlyRoots GetReadOnlyRoots ()
Detailed Description
Definition at line 35 of file read-only-heap.h.
Constructor & Destructor Documentation
ReadOnlyHeap() [1/2]
v8::internal::ReadOnlyHeap::ReadOnlyHeap (ReadOnlySpace * ro_space) [explicit]
Definition at line 169 of file read-only-heap.cc.
    : read_only_space_(ro_space) {
#ifdef V8_ENABLE_SANDBOX
  IsolateGroup::current()->code_pointer_table()->InitializeSpace(
      &code_pointer_space_);
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  jdt->InitializeSpace(&js_dispatch_table_space_);
  // To avoid marking trying to write to these read-only cells they are
  // allocated black. Target code objects in the read-only dispatch table are
  // read-only code objects.
  js_dispatch_table_space_.set_allocate_black(true);
#if V8_STATIC_DISPATCH_HANDLES_BOOL
  jdt->AttachSpaceToReadOnlySegments(&js_dispatch_table_space_);
  jdt->PreAllocateEntries(&js_dispatch_table_space_,
                          JSBuiltinDispatchHandleRoot::kCount, true);
#endif // V8_STATIC_DISPATCH_HANDLES_BOOL
#endif // V8_ENABLE_LEAPTIERING
}
References v8::internal::IsolateGroup::current().
Referenced by CreateInitialHeapForBootstrapping().
 ReadOnlyHeap()
v8::internal::ReadOnlyHeap::~ReadOnlyHeap ()
Definition at line 27 of file read-only-heap.cc.
                            {
#ifdef V8_ENABLE_SANDBOX
  IsolateGroup::current()->code_pointer_table()->TearDownSpace(
      &code_pointer_space_);
#endif
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
#if V8_STATIC_DISPATCH_HANDLES_BOOL
  jdt->DetachSpaceFromReadOnlySegments(&js_dispatch_table_space_);
#endif // V8_STATIC_DISPATCH_HANDLES_BOOL
  jdt->TearDownSpace(&js_dispatch_table_space_);
#endif
}
References v8::internal::IsolateGroup::current().
ReadOnlyHeap() [2/2]
v8::internal::ReadOnlyHeap::ReadOnlyHeap (const ReadOnlyHeap &) [delete]
Member Function Documentation
Contains() [1/2]
bool v8::internal::ReadOnlyHeap::Contains (Address address) [static]
Definition at line 207 of file read-only-heap.cc.
                                           {
  return MemoryChunk::FromAddress(address)->InReadOnlySpace();
}
References v8::internal::MemoryChunk::FromAddress(), and v8::internal::MemoryChunk::InReadOnlySpace().
Referenced by v8::internal::TaggedArrayBase< Derived, ShapeT, Super >::Allocate(), v8::internal::PrimitiveArrayBase< Derived, ShapeT, Super >::Allocate(), v8::internal::FactoryBase< Impl >::AllocateRawWithImmortalMap(), v8::internal::SharedHeapSerializer::CanBeInSharedOldSpace(), Contains(), v8::internal::Heap::Contains(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::SharedHeapSerializer::FinalizeSerialization(), v8::internal::SharedStringAccessGuardIfNeeded::GetIsolateIfNeeded(), v8::internal::anonymous_namespace{serializer.cc}::GetSnapshotSpace(), v8::internal::EmbedderDataSlot::Initialize(), v8::internal::Factory::InitializeMap(), v8::internal::Heap::InSpace(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::IsValidCodeObject(), v8::internal::IsValidHeapObject(), v8::internal::MarkCompactCollector::MarkObject(), v8::internal::MarkCompactCollector::MarkRootObject(), v8::internal::Heap::MustBeInSharedOldSpace(), v8::internal::compiler::ObjectData::ObjectData(), v8::internal::HeapObject::RehashBasedOnMap(), v8::internal::RUNTIME_FUNCTION(), SandboxSafeContains(), v8::internal::StartupSerializer::SerializeObjectImpl(), v8::internal::SharedHeapSerializer::SerializeObjectImpl(), and v8::internal::Serializer::SerializeReadOnlyObjectReference().
Contains() [2/2]
bool v8::internal::ReadOnlyHeap::Contains (Tagged< HeapObject > object) [static]
Definition at line 212 of file read-only-heap.cc.
                                                     {
  return Contains(object.address());
}
References Contains().
CreateInitialHeapForBootstrapping()
void v8::internal::ReadOnlyHeap::CreateInitialHeapForBootstrapping (Isolate * isolate, ReadOnlyArtifacts * artifacts) [static], [protected]
Definition at line 131 of file read-only-heap.cc.
                                                    {
  ReadOnlySpace* ro_space = new ReadOnlySpace(isolate->heap());
  std::unique_ptr<ReadOnlyHeap> shared_ro_heap(new ReadOnlyHeap(ro_space));
  isolate->isolate_group()->set_shared_read_only_heap(shared_ro_heap.get());
  artifacts->set_read_only_heap(std::move(shared_ro_heap));
  isolate->SetUpFromReadOnlyArtifacts(artifacts);
}
References v8::internal::Isolate::heap(), v8::internal::Isolate::isolate_group(), ReadOnlyHeap(), v8::internal::ReadOnlyArtifacts::set_read_only_heap(), v8::internal::IsolateGroup::set_shared_read_only_heap(), and v8::internal::Isolate::SetUpFromReadOnlyArtifacts().
Referenced by SetUp().
DeserializeIntoIsolate()
void v8::internal::ReadOnlyHeap::DeserializeIntoIsolate (Isolate * isolate, SnapshotData * read_only_snapshot_data, bool can_rehash) [protected]
Definition at line 83 of file read-only-heap.cc.
                                                           {
  DCHECK_NOT_NULL(read_only_snapshot_data);
  ReadOnlyDeserializer des(isolate, read_only_snapshot_data, can_rehash);
  des.DeserializeIntoIsolate();
  OnCreateRootsComplete(isolate);
  if (V8_UNLIKELY(v8_flags.extensible_ro_snapshot &&
                  isolate->serializer_enabled())) {
    // If this isolate will be serialized, leave RO space unfinalized and
    // allocatable s.t. it can be extended (e.g. by future Context::New calls).
    // We reach this scenario when creating custom snapshots - these initially
    // create the isolate from the default V8 snapshot, create new customized
    // contexts, and finally reserialize.
  } else {
    InitFromIsolate(isolate);
  }
}
References DCHECK_NOT_NULL, v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), InitFromIsolate(), OnCreateRootsComplete(), v8::internal::Isolate::serializer_enabled(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by SetUp().
EarlyGetReadOnlyRoots()
ReadOnlyRoots v8::internal::ReadOnlyHeap::EarlyGetReadOnlyRoots (Tagged< HeapObject > object) [inline], [static]
Definition at line 18 of file read-only-heap-inl.h.
                                                                           {
  ReadOnlyHeap* shared_ro_heap =
      IsolateGroup::current()->shared_read_only_heap();
  if (shared_ro_heap && shared_ro_heap->roots_init_complete()) {
    return ReadOnlyRoots(shared_ro_heap->read_only_roots_);
  }
  return ReadOnlyRoots(GetHeapFromWritableObject(object));
}
References v8::internal::IsolateGroup::current(), v8::internal::GetHeapFromWritableObject(), read_only_roots_, roots_init_complete(), and v8::internal::IsolateGroup::shared_read_only_heap().
Referenced by v8::internal::HeapObjectLayout::EarlyGetReadOnlyRoots(), and v8::internal::HeapObject::EarlyGetReadOnlyRoots().
InitFromIsolate()
void v8::internal::ReadOnlyHeap::InitFromIsolate (Isolate * isolate) [protected]
Definition at line 154 of file read-only-heap.cc.
                                                   {
  DCHECK(roots_init_complete_);
  read_only_space_->ShrinkPages();
  ReadOnlyArtifacts* artifacts =
      isolate->isolate_group()->read_only_artifacts();
  read_only_space()->DetachPagesAndAddToArtifacts(artifacts);
  artifacts->ReinstallReadOnlySpace(isolate);
  read_only_space_ = artifacts->shared_read_only_space();
#ifdef DEBUG
  artifacts->VerifyHeapAndSpaceRelationships(isolate);
#endif
}
References v8::internal::DCHECK(), v8::internal::ReadOnlySpace::DetachPagesAndAddToArtifacts(), v8::internal::Isolate::isolate_group(), v8::internal::IsolateGroup::read_only_artifacts(), read_only_space(), read_only_space_, v8::internal::ReadOnlyArtifacts::ReinstallReadOnlySpace(), roots_init_complete_, v8::internal::ReadOnlyArtifacts::shared_read_only_space(), v8::internal::ReadOnlySpace::ShrinkPages(), and v8::internal::ReadOnlyArtifacts::VerifyHeapAndSpaceRelationships().
Referenced by DeserializeIntoIsolate(), and OnCreateHeapObjectsComplete().
InitializeFromIsolateRoots()
void v8::internal::ReadOnlyHeap::InitializeFromIsolateRoots (Isolate * isolate)
Definition at line 147 of file read-only-heap.cc.
                                                              {
  void* const isolate_ro_roots =
      isolate->roots_table().read_only_roots_begin().location();
  std::memcpy(read_only_roots_, isolate_ro_roots,
              kEntriesCount * sizeof(Address));
}
References kEntriesCount, v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location(), read_only_roots_, v8::internal::RootsTable::read_only_roots_begin(), and v8::internal::Isolate::roots_table().
Referenced by OnCreateRootsComplete().
InitializeIsolateRoots()
void v8::internal::ReadOnlyHeap::InitializeIsolateRoots (Isolate * isolate)
Definition at line 140 of file read-only-heap.cc.
                                                          {
  void* const isolate_ro_roots =
      isolate->roots_table().read_only_roots_begin().location();
  std::memcpy(isolate_ro_roots, read_only_roots_,
              kEntriesCount * sizeof(Address));
}
References kEntriesCount, v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location(), read_only_roots_, v8::internal::RootsTable::read_only_roots_begin(), and v8::internal::Isolate::roots_table().
Referenced by SetUp().
OnCreateHeapObjectsComplete()
void v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete (Isolate * isolate)
Definition at line 111 of file read-only-heap.cc.
                                                               {
  DCHECK_NOT_NULL(isolate);
  // InitFromIsolate mutates MemoryChunk flags which would race with any
  // concurrently-running sweeper tasks. Ensure that sweeping has been
  // completed, i.e. no sweeper tasks are currently running.
  isolate->heap()->EnsureSweepingCompleted(
      Heap::SweepingForcedFinalizationMode::kV8Only);
  InitFromIsolate(isolate);
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    HeapVerifier::VerifyReadOnlyHeap(isolate->heap());
    HeapVerifier::VerifyHeap(isolate->heap());
  }
#endif
}
References DCHECK_NOT_NULL, v8::internal::Heap::EnsureSweepingCompleted(), v8::internal::Isolate::heap(), InitFromIsolate(), v8::internal::Heap::kV8Only, v8::internal::v8_flags, v8::internal::HeapVerifier::VerifyHeap(), and v8::internal::HeapVerifier::VerifyReadOnlyHeap().
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), and v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl().
OnCreateRootsComplete()
void v8::internal::ReadOnlyHeap::OnCreateRootsComplete (Isolate * isolate)
Definition at line 104 of file read-only-heap.cc.
                                                         {
  DCHECK_NOT_NULL(isolate);
  DCHECK(!roots_init_complete_);
  InitializeFromIsolateRoots(isolate);
  roots_init_complete_ = true;
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, InitializeFromIsolateRoots(), and roots_init_complete_.
Referenced by DeserializeIntoIsolate(), and v8::internal::SetupIsolateDelegate::SetupHeapInternal().
operator=()
ReadOnlyHeap& v8::internal::ReadOnlyHeap::operator= (const ReadOnlyHeap &) [delete]
PopulateReadOnlySpaceStatistics()
void v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics (SharedMemoryStatistics * statistics) [static]
Definition at line 191 of file read-only-heap.cc.
                                        {
  statistics->read_only_space_size_ = 0;
  statistics->read_only_space_used_size_ = 0;
  statistics->read_only_space_physical_size_ = 0;
  ReadOnlyArtifacts* artifacts = IsolateGroup::current()->read_only_artifacts();
  if (artifacts) {
    SharedReadOnlySpace* ro_space = artifacts->shared_read_only_space();
    statistics->read_only_space_size_ = ro_space->CommittedMemory();
    statistics->read_only_space_used_size_ = ro_space->Size();
    statistics->read_only_space_physical_size_ =
        ro_space->CommittedPhysicalMemory();
  }
}
References v8::internal::BaseSpace::CommittedMemory(), v8::internal::ReadOnlySpace::CommittedPhysicalMemory(), v8::internal::IsolateGroup::current(), v8::internal::IsolateGroup::read_only_artifacts(), v8::SharedMemoryStatistics::read_only_space_physical_size_, v8::SharedMemoryStatistics::read_only_space_size_, v8::SharedMemoryStatistics::read_only_space_used_size_, v8::internal::ReadOnlyArtifacts::shared_read_only_space(), and v8::internal::ReadOnlySpace::Size().
Referenced by v8::V8::GetSharedMemoryStatistics().
read_only_space()
ReadOnlySpace* v8::internal::ReadOnlyHeap::read_only_space () const [inline]
Definition at line 79 of file read-only-heap.h.
{ return read_only_space_; }
References read_only_space_.
Referenced by v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), InitFromIsolate(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::ReadOnlySegmentForSerialization(), v8::internal::ReadOnlyHeapImageDeserializer::ro_space(), SetUp(), and v8::internal::Heap::SetUpFromReadOnlyHeap().
roots_init_complete()
bool v8::internal::ReadOnlyHeap::roots_init_complete () const [inline]
Definition at line 93 of file read-only-heap.h.
{ return roots_init_complete_; }
References roots_init_complete_.
Referenced by EarlyGetReadOnlyRoots(), and v8::internal::SetupIsolateDelegate::SetupHeapInternal().
SandboxSafeContains()
bool v8::internal::ReadOnlyHeap::SandboxSafeContains (Tagged< HeapObject > object) [static]
Definition at line 217 of file read-only-heap.cc.
                                                                {
#ifdef V8_ENABLE_SANDBOX
  return MemoryChunk::FromHeapObject(object)->SandboxSafeInReadOnlySpace();
#else
  return Contains(object);
#endif
}
References Contains(), and v8::internal::MemoryChunk::FromHeapObject().
SetUp()
void v8::internal::ReadOnlyHeap::SetUp (Isolate * isolate, SnapshotData * read_only_snapshot_data, bool can_rehash) [static]
Definition at line 42 of file read-only-heap.cc.
                                          {
  DCHECK_NOT_NULL(isolate);
  IsolateGroup* group = isolate->isolate_group();
  group->mutex()->AssertHeld();
  if (read_only_snapshot_data != nullptr) {
    bool read_only_heap_created = false;
    ReadOnlyArtifacts* artifacts = group->read_only_artifacts();
    if (!artifacts) {
      artifacts = group->InitializeReadOnlyArtifacts();
      artifacts->InitializeChecksum(read_only_snapshot_data);
      CreateInitialHeapForBootstrapping(isolate, artifacts);
      artifacts->read_only_heap()->DeserializeIntoIsolate(
          isolate, read_only_snapshot_data, can_rehash);
      artifacts->set_initial_next_unique_sfi_id(isolate->next_unique_sfi_id());
      read_only_heap_created = true;
    } else {
      isolate->SetUpFromReadOnlyArtifacts(artifacts);
#ifdef V8_COMPRESS_POINTERS
      isolate->external_pointer_table().SetUpFromReadOnlyArtifacts(
          isolate->heap()->read_only_external_pointer_space(), artifacts);
#endif // V8_COMPRESS_POINTERS
    }
    artifacts->VerifyChecksum(read_only_snapshot_data, read_only_heap_created);
    artifacts->read_only_heap()->InitializeIsolateRoots(isolate);
  } else {
    // This path should only be taken in mksnapshot, should only be run once
    // before tearing down the Isolate that holds this ReadOnlyArtifacts and
    // is not thread-safe.
    ReadOnlyArtifacts* artifacts = group->read_only_artifacts();
    CHECK(!artifacts);
    artifacts = group->InitializeReadOnlyArtifacts();
    CreateInitialHeapForBootstrapping(isolate, artifacts);
    // Ensure the first read-only page ends up first in the cage.
    artifacts->read_only_heap()->read_only_space()->EnsurePage();
    artifacts->VerifyChecksum(read_only_snapshot_data, true);
  }
}
References v8::base::Mutex::AssertHeld(), CHECK, CreateInitialHeapForBootstrapping(), DCHECK_NOT_NULL, DeserializeIntoIsolate(), v8::internal::ReadOnlySpace::EnsurePage(), v8::internal::Isolate::heap(), v8::internal::ReadOnlyArtifacts::InitializeChecksum(), InitializeIsolateRoots(), v8::internal::IsolateGroup::InitializeReadOnlyArtifacts(), v8::internal::Isolate::isolate_group(), v8::internal::IsolateGroup::mutex(), v8::internal::Isolate::next_unique_sfi_id(), v8::internal::IsolateGroup::read_only_artifacts(), v8::internal::ReadOnlyArtifacts::read_only_heap(), read_only_space(), v8::internal::ReadOnlyArtifacts::set_initial_next_unique_sfi_id(), v8::internal::Isolate::SetUpFromReadOnlyArtifacts(), and v8::internal::ReadOnlyArtifacts::VerifyChecksum().
Referenced by v8::internal::IsolateGroup::SetupReadOnlyHeap().
Friends And Related Function Documentation
GetReadOnlyRoots
ReadOnlyRoots GetReadOnlyRoots () [friend]
Definition at line 82 of file roots-inl.h.
                                 {
  ReadOnlyHeap* shared_ro_heap =
      IsolateGroup::current()->shared_read_only_heap();
  // If this check fails in code that runs during initialization use
  // EarlyGetReadOnlyRoots instead.
  DCHECK(shared_ro_heap && shared_ro_heap->roots_init_complete());
  return ReadOnlyRoots(shared_ro_heap->read_only_roots_);
}
ReadOnlyArtifacts
friend class ReadOnlyArtifacts [friend]
Definition at line 96 of file read-only-heap.h.
Member Data Documentation
kEntriesCount
constexpr size_t v8::internal::ReadOnlyHeap::kEntriesCount [static], [constexpr]
Initial value:
=
      static_cast<size_t>(RootIndex::kReadOnlyRootsCount)
Definition at line 37 of file read-only-heap.h.
Referenced by InitializeFromIsolateRoots(), and InitializeIsolateRoots().
read_only_roots_
Address v8::internal::ReadOnlyHeap::read_only_roots_[kEntriesCount] [private]
Definition at line 127 of file read-only-heap.h.
Referenced by EarlyGetReadOnlyRoots(), InitializeFromIsolateRoots(), and InitializeIsolateRoots().
read_only_space_
ReadOnlySpace* v8::internal::ReadOnlyHeap::read_only_space_ = nullptr [protected]
Definition at line 114 of file read-only-heap.h.
Referenced by InitFromIsolate(), and read_only_space().
roots_init_complete_
bool v8::internal::ReadOnlyHeap::roots_init_complete_ = false [protected]
Definition at line 113 of file read-only-heap.h.
Referenced by InitFromIsolate(), OnCreateRootsComplete(), and roots_init_complete().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-heap.h
/mnt/V8SourceCode/src/heap/read-only-heap-inl.h
/mnt/V8SourceCode/src/heap/read-only-heap.cc