v8::internal::IfStatementSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
IfStatementSourceRanges (const SourceRange &then_range, const SourceRange &else_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
void RemoveContinuationRange () override
Private Attributes
SourceRange then_range_
SourceRange else_range_
bool has_continuation_ = true
Detailed Description
Definition at line 218 of file ast-source-ranges.h.
Constructor & Destructor Documentation
IfStatementSourceRanges()
v8::internal::IfStatementSourceRanges::IfStatementSourceRanges (const SourceRange & then_range, const SourceRange & else_range) [inline], [explicit]
Definition at line 220 of file ast-source-ranges.h.
      : then_range_(then_range), else_range_(else_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::IfStatementSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 224 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    switch (kind) {
      case SourceRangeKind::kElse:
        return else_range_;
      case SourceRangeKind::kThen:
        return then_range_;
      case SourceRangeKind::kContinuation: {
        if (!has_continuation_) return SourceRange::Empty();
        const SourceRange& trailing_range =
            else_range_.IsEmpty() ? then_range_ : else_range_;
        return SourceRange::ContinuationOf(trailing_range);
      }
      default:
        UNREACHABLE();
    }
  }
References v8::internal::SourceRange::ContinuationOf(), v8::internal::DCHECK(), else_range_, v8::internal::SourceRange::Empty(), has_continuation_, HasRange(), v8::internal::SourceRange::IsEmpty(), v8::internal::kContinuation, v8::internal::kElse, v8::internal::kThen, then_range_, and v8::internal::UNREACHABLE().
HasRange()
bool v8::internal::IfStatementSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 242 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kThen || kind == SourceRangeKind::kElse ||
           kind == SourceRangeKind::kContinuation;
  }
References v8::internal::kContinuation, v8::internal::kElse, and v8::internal::kThen.
Referenced by GetRange(), and RemoveContinuationRange().
RemoveContinuationRange()
void v8::internal::IfStatementSourceRanges::RemoveContinuationRange () [inline], [override], [virtual]
Reimplemented from v8::internal::AstNodeSourceRanges.
Definition at line 247 of file ast-source-ranges.h.
                                          {
    DCHECK(HasRange(SourceRangeKind::kContinuation));
    has_continuation_ = false;
  }
References v8::internal::DCHECK(), has_continuation_, HasRange(), and v8::internal::kContinuation.
Member Data Documentation
else_range_
SourceRange v8::internal::IfStatementSourceRanges::else_range_ [private]
Definition at line 254 of file ast-source-ranges.h.
Referenced by GetRange().
has_continuation_
bool v8::internal::IfStatementSourceRanges::has_continuation_ = true [private]
Definition at line 255 of file ast-source-ranges.h.
Referenced by GetRange(), and RemoveContinuationRange().
then_range_
SourceRange v8::internal::IfStatementSourceRanges::then_range_ [private]
Definition at line 253 of file ast-source-ranges.h.
Referenced by GetRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h