v8::internal::maglev::MaglevGraphLabeller Class Reference
#include <maglev-graph-labeller.h>
Classes
struct NodeInfo
struct Provenance
Public Member Functions
void RegisterNode (const NodeBase *node, const MaglevCompilationUnit *unit, BytecodeOffset bytecode_offset, SourcePosition position)
void RegisterNode (const NodeBase *node)
int NodeId (const NodeBase *node)
const Provenance & GetNodeProvenance (const NodeBase *node)
int max_node_id () const
void PrintNodeLabel (std::ostream &os, const NodeBase *node)
void PrintInput (std::ostream &os, const Input &input)
Private Attributes
std::map< const NodeBase *, NodeInfo > nodes_
int next_node_label_ = 1
Detailed Description
Definition at line 17 of file maglev-graph-labeller.h.
Member Function Documentation
GetNodeProvenance()
const Provenance& v8::internal::maglev::MaglevGraphLabeller::GetNodeProvenance (const NodeBase * node) [inline]
Definition at line 44 of file maglev-graph-labeller.h.
                                                            {
    return nodes_[node].provenance;
  }
References nodes_.
max_node_id()
int v8::internal::maglev::MaglevGraphLabeller::max_node_id () const [inline]
Definition at line 48 of file maglev-graph-labeller.h.
{ return next_node_label_ - 1; }
References next_node_label_.
NodeId()
int v8::internal::maglev::MaglevGraphLabeller::NodeId (const NodeBase * node) [inline]
Definition at line 43 of file maglev-graph-labeller.h.
{ return nodes_[node].label; }
References nodes_.
Referenced by v8::internal::maglev::CheckValueInputIs().
PrintInput()
void v8::internal::maglev::MaglevGraphLabeller::PrintInput (std::ostream & os, const Input & input) [inline]
Definition at line 71 of file maglev-graph-labeller.h.
                                                      {
    PrintNodeLabel(os, input.node());
    os << ":" << input.operand();
  }
References v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), and PrintNodeLabel().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintInputs().
PrintNodeLabel()
void v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel (std::ostream & os, const NodeBase * node) [inline]
Definition at line 50 of file maglev-graph-labeller.h.
                                                            {
    if (node != nullptr && node->Is<VirtualObject>()) {
      // VirtualObjects are unregisted nodes, since they are not attached to
      // the graph, but its inlined allocation is.
      const VirtualObject* vo = node->Cast<VirtualObject>();
      os << "VO{" << vo->id() << "}:";
      node = vo->allocation();
    }
    auto node_id_it = nodes_.find(node);
    if (node_id_it == nodes_.end()) {
      os << "<unregistered node " << node << ">";
      return;
    }
    if (node->has_id()) {
      os << "v" << node->id() << "/";
    }
    os << "n" << node_id_it->second.label;
  }
References v8::internal::maglev::VirtualObject::allocation(), v8::internal::maglev::NodeBase::Cast(), v8::internal::maglev::NodeBase::has_id(), v8::internal::maglev::NodeBase::id(), v8::internal::maglev::VirtualObject::id(), v8::internal::maglev::NodeBase::Is(), and nodes_.
Referenced by v8::internal::maglev::VirtualObjectList::Print(), PrintInput(), and v8::internal::maglev::ConstantGapMove::PrintParams().
RegisterNode() [1/2]
void v8::internal::maglev::MaglevGraphLabeller::RegisterNode (const NodeBase * node) [inline]
Definition at line 38 of file maglev-graph-labeller.h.
                                          {
    RegisterNode(node, nullptr, BytecodeOffset::None(),
                 SourcePosition::Unknown());
  }
References v8::internal::BytecodeOffset::None(), RegisterNode(), and v8::internal::SourcePosition::Unknown().
RegisterNode() [2/2]
void v8::internal::maglev::MaglevGraphLabeller::RegisterNode (const NodeBase * node, const MaglevCompilationUnit * unit, BytecodeOffset bytecode_offset, SourcePosition position) [inline]
Definition at line 29 of file maglev-graph-labeller.h.
                                                                             {
    if (nodes_
            .emplace(node, NodeInfo{next_node_label_,
                                    {unit, bytecode_offset, position}})
            .second) {
      next_node_label_++;
    }
  }
References next_node_label_, and nodes_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph(), v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::maglev::MaglevGraphBuilder::CreateNewConstantNode(), v8::internal::maglev::Graph::CreateNewConstantNode(), v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart(), v8::internal::maglev::MaglevPhiRepresentationSelector::RegisterNewNode(), RegisterNode(), v8::internal::maglev::MaglevInliner::RegisterNode(), v8::internal::maglev::MaglevCompilationUnit::RegisterNodeInGraphLabeller(), and v8::internal::maglev::MaglevGraphBuilder::RegisterPhisWithGraphLabeller().
Member Data Documentation
next_node_label_
int v8::internal::maglev::MaglevGraphLabeller::next_node_label_ = 1 [private]
Definition at line 78 of file maglev-graph-labeller.h.
Referenced by max_node_id(), and RegisterNode().
nodes_
std::map<const NodeBase*, NodeInfo> v8::internal::maglev::MaglevGraphLabeller::nodes_ [private]
Definition at line 77 of file maglev-graph-labeller.h.
Referenced by GetNodeProvenance(), NodeId(), PrintNodeLabel(), and RegisterNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-labeller.h