v8::internal::compiler::CheckFloat64HoleParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckFloat64HoleParameters (CheckFloat64HoleMode mode, FeedbackSource const &feedback)
CheckFloat64HoleMode mode () const
FeedbackSource const & feedback () const
Private Attributes
CheckFloat64HoleMode mode_
FeedbackSource feedback_
Detailed Description
Definition at line 349 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckFloat64HoleParameters()
v8::internal::compiler::CheckFloat64HoleParameters::CheckFloat64HoleParameters (CheckFloat64HoleMode mode, FeedbackSource const & feedback) [inline]
Definition at line 351 of file simplified-operator.h.
      : mode_(mode), feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::CheckFloat64HoleParameters::feedback () const [inline]
Definition at line 356 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
mode()
CheckFloat64HoleMode v8::internal::compiler::CheckFloat64HoleParameters::mode () const [inline]
Definition at line 355 of file simplified-operator.h.
{ return mode_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::CheckFloat64HoleParameters::feedback_ [private]
Definition at line 360 of file simplified-operator.h.
mode_
CheckFloat64HoleMode v8::internal::compiler::CheckFloat64HoleParameters::mode_ [private]
Definition at line 359 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h