v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency Class Reference
Public Member Functions
OwnConstantElementDependency (JSObjectRef holder, uint32_t index, ObjectRef element)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const JSObjectRef holder_
const uint32_t index_
const ObjectRef element_
Additional Inherited Members
Detailed Description
Definition at line 1080 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
OwnConstantElementDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::OwnConstantElementDependency (JSObjectRef holder, uint32_t index, ObjectRef element) [inline]
Definition at line 1082 of file compilation-dependencies.cc.
      : CompilationDependency(kOwnConstantElement),
        holder_(holder),
        index_(index),
        element_(element) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1108 of file compilation-dependencies.cc.
                                                                {
    const OwnConstantElementDependency* const zat =
        that->AsOwnConstantElement();
    return holder_.equals(zat->holder_) && index_ == zat->index_ &&
           element_.equals(zat->element_);
  }
References element_, holder_, and index_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1103 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(holder_), index_, h(element_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 1099 of file compilation-dependencies.cc.
                                                                               {
  }
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1089 of file compilation-dependencies.cc.
                                                    {
    DisallowGarbageCollection no_gc;
    Tagged<JSObject> holder = *holder_.object();
    std::optional<Tagged<Object>> maybe_element =
        holder_.GetOwnConstantElementFromHeap(
            broker, holder->elements(), holder->GetElementsKind(), index_);
    if (!maybe_element.has_value()) return false;
    return maybe_element.value() == *element_.object();
  }
References broker(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Member Data Documentation
element_
const ObjectRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::element_ [private]
Definition at line 1117 of file compilation-dependencies.cc.
Referenced by Equals().
holder_
const JSObjectRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::holder_ [private]
Definition at line 1115 of file compilation-dependencies.cc.
Referenced by Equals().
index_
const uint32_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantElementDependency::index_ [private]
Definition at line 1116 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc