v8::internal::ContinuationSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
ContinuationSourceRanges (int32_t continuation_position)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
void RemoveContinuationRange () override
Private Attributes
int32_t continuation_position_
Detailed Description
Definition at line 99 of file ast-source-ranges.h.
Constructor & Destructor Documentation
ContinuationSourceRanges()
v8::internal::ContinuationSourceRanges::ContinuationSourceRanges (int32_t continuation_position) [inline], [explicit]
Definition at line 101 of file ast-source-ranges.h.
      : continuation_position_(continuation_position) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::ContinuationSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 104 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    return SourceRange::OpenEnded(continuation_position_);
  }
References continuation_position_, v8::internal::DCHECK(), HasRange(), and v8::internal::SourceRange::OpenEnded().
HasRange()
bool v8::internal::ContinuationSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 109 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kContinuation;
  }
References v8::internal::kContinuation.
Referenced by GetRange(), and RemoveContinuationRange().
RemoveContinuationRange()
void v8::internal::ContinuationSourceRanges::RemoveContinuationRange () [inline], [override], [virtual]
Reimplemented from v8::internal::AstNodeSourceRanges.
Definition at line 113 of file ast-source-ranges.h.
                                          {
    DCHECK(HasRange(SourceRangeKind::kContinuation));
    continuation_position_ = kNoSourcePosition;
  }
References continuation_position_, v8::internal::DCHECK(), HasRange(), v8::internal::kContinuation, and v8::internal::kNoSourcePosition.
Member Data Documentation
continuation_position_
int32_t v8::internal::ContinuationSourceRanges::continuation_position_ [private]
Definition at line 119 of file ast-source-ranges.h.
Referenced by GetRange(), and RemoveContinuationRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h