v8::internal::PagedNewSpace Class Reference
#include <new-spaces.h>
Public Member Functions
PagedNewSpace (Heap *heap, size_t initial_capacity, size_t min_capacity, size_t max_capacity)
~PagedNewSpace () final
bool ContainsSlow (Address a) const final
void Grow (size_t new_capacity) final
bool StartShrinking (size_t new_target_capacity)
void FinishShrinking ()
size_t Size () const final
size_t SizeOfObjects () const final
size_t Capacity () const final
size_t TotalCapacity () const final
size_t CommittedMemory () const final
size_t MaximumCommittedMemory () const final
size_t CommittedPhysicalMemory () const final
size_t Available () const final
size_t ExternalBackingStoreBytes (ExternalBackingStoreType type) const final
size_t AllocatedSinceLastGC () const final
size_t MinimumCapacity () const final
size_t MaximumCapacity () const final
Address first_allocatable_address () const final
PageMetadata * first_page () final
PageMetadata * last_page () final
const PageMetadata * first_page () const final
const PageMetadata * last_page () const final
iterator begin () final
iterator end () final
const_iterator begin () const final
const_iterator end () const final
std::unique_ptr< ObjectIterator > GetObjectIterator (Heap *heap) final
void GarbageCollectionEpilogue () final
bool IsPromotionCandidate (const MutablePageMetadata *page) const final
void GrowToMaximumCapacityForTesting () final
PagedSpaceForNewSpace * paged_space ()
const PagedSpaceForNewSpace * paged_space () const
void MakeIterable () override
heap::List< MutablePageMetadata > & memory_chunk_list () final
bool ShouldReleaseEmptyPage ()
AllocatorPolicy * CreateAllocatorPolicy (MainAllocator *allocator) final
Static Public Member Functions
static PagedNewSpace * From (NewSpace *space)
Private Member Functions
void RemovePage (PageMetadata *page) final
Private Attributes
PagedSpaceForNewSpace paged_space_
Additional Inherited Members
Detailed Description
Definition at line 596 of file new-spaces.h.
Constructor & Destructor Documentation
PagedNewSpace()
v8::internal::PagedNewSpace::PagedNewSpace (Heap * heap, size_t initial_capacity, size_t min_capacity, size_t max_capacity)
Definition at line 975 of file new-spaces.cc.
    : NewSpace(heap),
      paged_space_(heap, initial_capacity, min_capacity, max_capacity) {}
 PagedNewSpace()
v8::internal::PagedNewSpace::~PagedNewSpace () [final]
Definition at line 980 of file new-spaces.cc.
                              {
  paged_space_.TearDown();
}
References paged_space_, and v8::internal::PagedSpaceForNewSpace::TearDown().
Member Function Documentation
AllocatedSinceLastGC()
size_t v8::internal::PagedNewSpace::AllocatedSinceLastGC () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 654 of file new-spaces.h.
                                            {
    return paged_space_.AllocatedSinceLastGC();
  }
Available()
size_t v8::internal::PagedNewSpace::Available () const [inline], [final]
Definition at line 648 of file new-spaces.h.
{ return paged_space_.Available(); }
begin() [1/2]
const_iterator v8::internal::PagedNewSpace::begin () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 699 of file new-spaces.h.
{ return paged_space_.begin(); }
begin() [2/2]
iterator v8::internal::PagedNewSpace::begin () [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 696 of file new-spaces.h.
{ return paged_space_.begin(); }
Capacity()
size_t v8::internal::PagedNewSpace::Capacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 627 of file new-spaces.h.
{ return paged_space_.Capacity(); }
CommittedMemory()
size_t v8::internal::PagedNewSpace::CommittedMemory () const [inline], [final]
Definition at line 634 of file new-spaces.h.
                                       {
    return paged_space_.CommittedMemory();
  }
CommittedPhysicalMemory()
size_t v8::internal::PagedNewSpace::CommittedPhysicalMemory () const [inline], [final]
Definition at line 643 of file new-spaces.h.
                                               {
    return paged_space_.CommittedPhysicalMemory();
  }
ContainsSlow()
bool v8::internal::PagedNewSpace::ContainsSlow (Address a) const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 608 of file new-spaces.h.
                                           {
    return paged_space_.ContainsSlow(a);
  }
References ContainsSlow().
Referenced by ContainsSlow().
CreateAllocatorPolicy()
AllocatorPolicy * v8::internal::PagedNewSpace::CreateAllocatorPolicy (MainAllocator * allocator) [final]
Definition at line 984 of file new-spaces.cc.
                              {
  return new PagedNewSpaceAllocatorPolicy(this, allocator);
}
end() [1/2]
const_iterator v8::internal::PagedNewSpace::end () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 700 of file new-spaces.h.
{ return paged_space_.end(); }
end() [2/2]
iterator v8::internal::PagedNewSpace::end () [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 697 of file new-spaces.h.
{ return paged_space_.end(); }
ExternalBackingStoreBytes()
size_t v8::internal::PagedNewSpace::ExternalBackingStoreBytes (ExternalBackingStoreType type) const [inline], [final]
Definition at line 650 of file new-spaces.h.
                                                                              {
    return paged_space_.ExternalBackingStoreBytes(type);
  }
References v8::internal::tracing::type.
FinishShrinking()
void v8::internal::PagedNewSpace::FinishShrinking () [inline]
Definition at line 619 of file new-spaces.h.
{ paged_space_.FinishShrinking(); }
Referenced by v8::internal::Heap::ReduceNewSpaceSize().
first_allocatable_address()
Address v8::internal::PagedNewSpace::first_allocatable_address () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 670 of file new-spaces.h.
                                                  {
    return paged_space_.first_allocatable_address();
  }
first_page() [1/2]
const PageMetadata* v8::internal::PagedNewSpace::first_page () const [inline], [final]
Definition at line 689 of file new-spaces.h.
                                               {
    return paged_space_.first_page();
  }
first_page() [2/2]
PageMetadata* v8::internal::PagedNewSpace::first_page () [inline], [final]
Definition at line 686 of file new-spaces.h.
{ return paged_space_.first_page(); }
From()
static PagedNewSpace* v8::internal::PagedNewSpace::From (NewSpace * space) [inline], [static]
Definition at line 598 of file new-spaces.h.
                                              {
    DCHECK(v8_flags.minor_ms);
    return static_cast<PagedNewSpace*>(space);
  }
References v8::internal::DCHECK(), space, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::paged_new_space(), and v8::internal::Sweeper::SweepEmptyNewSpacePage().
GarbageCollectionEpilogue()
void v8::internal::PagedNewSpace::GarbageCollectionEpilogue () [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 706 of file new-spaces.h.
                                         {
    paged_space_.GarbageCollectionEpilogue();
  }
GetObjectIterator()
std::unique_ptr<ObjectIterator> v8::internal::PagedNewSpace::GetObjectIterator (Heap * heap) [inline], [final]
Definition at line 702 of file new-spaces.h.
                                                                    {
    return paged_space_.GetObjectIterator(heap);
  }
Grow()
void v8::internal::PagedNewSpace::Grow (size_t new_capacity) [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 613 of file new-spaces.h.
{ paged_space_.Grow(new_capacity); }
GrowToMaximumCapacityForTesting()
void v8::internal::PagedNewSpace::GrowToMaximumCapacityForTesting () [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 714 of file new-spaces.h.
                                               {
    paged_space_.GrowToMaximumCapacityForTesting();
  }
IsPromotionCandidate()
bool v8::internal::PagedNewSpace::IsPromotionCandidate (const MutablePageMetadata * page) const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 710 of file new-spaces.h.
                                                                         {
    return paged_space_.IsPromotionCandidate(page);
  }
last_page() [1/2]
const PageMetadata* v8::internal::PagedNewSpace::last_page () const [inline], [final]
Definition at line 692 of file new-spaces.h.
                                              {
    return paged_space_.last_page();
  }
last_page() [2/2]
PageMetadata* v8::internal::PagedNewSpace::last_page () [inline], [final]
Definition at line 687 of file new-spaces.h.
{ return paged_space_.last_page(); }
MakeIterable()
void v8::internal::PagedNewSpace::MakeIterable () [inline], [override], [virtual]
Implements v8::internal::NewSpace.
Definition at line 721 of file new-spaces.h.
{ paged_space_.MakeIterable(); }
MaximumCapacity()
size_t v8::internal::PagedNewSpace::MaximumCapacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 664 of file new-spaces.h.
                                       {
    return paged_space_.MaximumCapacity();
  }
MaximumCommittedMemory()
size_t v8::internal::PagedNewSpace::MaximumCommittedMemory () const [inline], [final]
Definition at line 638 of file new-spaces.h.
                                              {
    return paged_space_.MaximumCommittedMemory();
  }
memory_chunk_list()
heap::List<MutablePageMetadata>& v8::internal::PagedNewSpace::memory_chunk_list () [inline], [final]
Definition at line 724 of file new-spaces.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
MinimumCapacity()
size_t v8::internal::PagedNewSpace::MinimumCapacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 659 of file new-spaces.h.
                                       {
    return paged_space_.MinimumCapacity();
  }
paged_space() [1/2]
PagedSpaceForNewSpace* v8::internal::PagedNewSpace::paged_space () [inline]
Definition at line 718 of file new-spaces.h.
{ return &paged_space_; }
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::Heap::EnsureSweepingCompleted(), v8::internal::Heap::EnsureYoungSweepingCompleted(), v8::internal::Sweeper::PrepareToBeSweptPage(), v8::internal::MinorMarkSweepCollector::StartMarking(), v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::MinorMarkSweepCollector::TraceFragmentation(), v8::internal::PagedNewSpaceAllocatorPolicy::TryAllocatePage(), v8::internal::MarkCompactCollector::VerifyMarking(), v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation(), and v8::internal::Heap::YoungGenerationWastedBytes().
paged_space() [2/2]
const PagedSpaceForNewSpace* v8::internal::PagedNewSpace::paged_space () const [inline]
Definition at line 719 of file new-spaces.h.
{ return &paged_space_; }
RemovePage()
void v8::internal::PagedNewSpace::RemovePage (PageMetadata * page) [inline], [final], [private], [virtual]
Implements v8::internal::NewSpace.
Definition at line 733 of file new-spaces.h.
{ paged_space_.RemovePage(page); }
ShouldReleaseEmptyPage()
bool v8::internal::PagedNewSpace::ShouldReleaseEmptyPage () [inline]
Definition at line 726 of file new-spaces.h.
                                {
    return paged_space_.ShouldReleaseEmptyPage();
  }
Size()
size_t v8::internal::PagedNewSpace::Size () const [inline], [final]
Definition at line 622 of file new-spaces.h.
{ return paged_space_.Size(); }
SizeOfObjects()
size_t v8::internal::PagedNewSpace::SizeOfObjects () const [inline], [final]
Definition at line 624 of file new-spaces.h.
{ return paged_space_.SizeOfObjects(); }
StartShrinking()
bool v8::internal::PagedNewSpace::StartShrinking (size_t new_target_capacity) [inline]
Definition at line 616 of file new-spaces.h.
                                                  {
    return paged_space_.StartShrinking(new_target_capacity);
  }
Referenced by v8::internal::Heap::StartResizeNewSpace().
TotalCapacity()
size_t v8::internal::PagedNewSpace::TotalCapacity () const [inline], [final], [virtual]
Implements v8::internal::NewSpace.
Definition at line 631 of file new-spaces.h.
{ return paged_space_.TotalCapacity(); }
Member Data Documentation
paged_space_
PagedSpaceForNewSpace v8::internal::PagedNewSpace::paged_space_ [private]
Definition at line 735 of file new-spaces.h.
Referenced by ~PagedNewSpace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/new-spaces.h
/mnt/V8SourceCode/src/heap/new-spaces.cc