v8::internal::compiler::DefineNamedOwnPropertyParameters Class Reference
#include <js-operator.h>
Public Member Functions
DefineNamedOwnPropertyParameters (NameRef name, FeedbackSource const &feedback)
NameRef name () const
FeedbackSource const & feedback () const
Private Attributes
const NameRef name_
FeedbackSource const feedback_
Friends
bool operator== (DefineNamedOwnPropertyParameters const &, DefineNamedOwnPropertyParameters const &)
bool operator!= (DefineNamedOwnPropertyParameters const &, DefineNamedOwnPropertyParameters const &)
size_t hash_value (DefineNamedOwnPropertyParameters const &)
std::ostream & operator<< (std::ostream &, DefineNamedOwnPropertyParameters const &)
Detailed Description
Definition at line 397 of file js-operator.h.
Constructor & Destructor Documentation
DefineNamedOwnPropertyParameters()
v8::internal::compiler::DefineNamedOwnPropertyParameters::DefineNamedOwnPropertyParameters (NameRef name, FeedbackSource const & feedback) [inline]
Definition at line 399 of file js-operator.h.
      : name_(name), feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::DefineNamedOwnPropertyParameters::feedback () const [inline]
Definition at line 403 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineNamedOwnProperty().
name()
NameRef v8::internal::compiler::DefineNamedOwnPropertyParameters::name () const [inline]
Definition at line 402 of file js-operator.h.
{ return name_; }
References name_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineNamedOwnProperty().
Friends And Related Function Documentation
hash_value
size_t hash_value (DefineNamedOwnPropertyParameters const & p) [friend]
Definition at line 235 of file js-operator.cc.
                                                             {
  return base::hash_combine(p.name_.object().location(),
                            FeedbackSource::Hash()(p.feedback()));
}
operator!=
bool operator!= (DefineNamedOwnPropertyParameters const & lhs, DefineNamedOwnPropertyParameters const & rhs) [friend]
Definition at line 230 of file js-operator.cc.
                                                             {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, DefineNamedOwnPropertyParameters const & p) [friend]
Definition at line 240 of file js-operator.cc.
                                                                    {
  return os << Brief(*p.name_.object());
}
operator==
bool operator== (DefineNamedOwnPropertyParameters const & lhs, DefineNamedOwnPropertyParameters const & rhs) [friend]
Definition at line 224 of file js-operator.cc.
                                                             {
  return lhs.name_.object().location() == rhs.name_.object().location() &&
         lhs.feedback() == rhs.feedback();
}
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::DefineNamedOwnPropertyParameters::feedback_ [private]
Definition at line 407 of file js-operator.h.
Referenced by feedback().
name_
const NameRef v8::internal::compiler::DefineNamedOwnPropertyParameters::name_ [private]
Definition at line 406 of file js-operator.h.
Referenced by name().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h