v8::internal::PagedSpaceObjectIterator Class Reference
#include <paged-spaces.h>
Public Member Functions
PagedSpaceObjectIterator (Heap *heap, const PagedSpaceBase *space)
Tagged< HeapObject > Next () override
Private Member Functions
bool AdvanceToNextPage ()
Private Attributes
HeapObjectRange::iterator cur_
HeapObjectRange::iterator end_
const PagedSpaceBase *const space_
ConstPageRange page_range_
ConstPageRange::iterator current_page_
Additional Inherited Members
Detailed Description
Definition at line 89 of file paged-spaces.h.
Constructor & Destructor Documentation
PagedSpaceObjectIterator()
v8::internal::PagedSpaceObjectIterator::PagedSpaceObjectIterator (Heap * heap, const PagedSpaceBase * space)
Definition at line 45 of file paged-spaces.cc.
    : space_(space),
      page_range_(space->first_page(), nullptr),
      current_page_(page_range_.begin()) {
  heap->MakeHeapIterable();
  USE(space_);
}
References space_, and USE.
Member Function Documentation
AdvanceToNextPage()
bool v8::internal::PagedSpaceObjectIterator::AdvanceToNextPage () [private]
Definition at line 56 of file paged-spaces.cc.
                                                 {
  if (current_page_ == page_range_.end()) return false;
  const PageMetadata* cur_page = *(current_page_++);
  HeapObjectRange heap_objects(cur_page);
  cur_ = heap_objects.begin();
  end_ = heap_objects.end();
  return true;
}
References v8::internal::HeapObjectRange::begin(), cur_, current_page_, v8::internal::HeapObjectRange::end(), v8::internal::ConstPageRange::end(), end_, and page_range_.
Next()
Tagged< HeapObject > v8::internal::PagedSpaceObjectIterator::Next () [inline], [override], [virtual]
Implements v8::internal::ObjectIterator.
Definition at line 69 of file paged-spaces-inl.h.
                                                  {
  do {
    if (cur_ != end_) {
      return *cur_++;
    }
  } while (AdvanceToNextPage());
  return Tagged<HeapObject>();
}
References v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::Heap::CollectAllAvailableGarbage(), and v8::internal::CodeStatistics::CollectCodeStatistics().
Member Data Documentation
cur_
HeapObjectRange::iterator v8::internal::PagedSpaceObjectIterator::cur_ [private]
Definition at line 104 of file paged-spaces.h.
Referenced by AdvanceToNextPage().
current_page_
ConstPageRange::iterator v8::internal::PagedSpaceObjectIterator::current_page_ [private]
Definition at line 108 of file paged-spaces.h.
Referenced by AdvanceToNextPage().
end_
HeapObjectRange::iterator v8::internal::PagedSpaceObjectIterator::end_ [private]
Definition at line 105 of file paged-spaces.h.
Referenced by AdvanceToNextPage().
page_range_
ConstPageRange v8::internal::PagedSpaceObjectIterator::page_range_ [private]
Definition at line 107 of file paged-spaces.h.
Referenced by AdvanceToNextPage().
space_
const PagedSpaceBase* const v8::internal::PagedSpaceObjectIterator::space_ [private]
Definition at line 106 of file paged-spaces.h.
Referenced by PagedSpaceObjectIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces-inl.h
/mnt/V8SourceCode/src/heap/paged-spaces.cc