v8::internal::compiler::ElementAccessInfo Class Reference
#include <access-info.h>
Public Member Functions
ElementAccessInfo (ZoneVector< MapRef > &&lookup_start_object_maps, ElementsKind elements_kind, Zone *zone)
ElementAccessInfo (MapRef map, ObjectRef accessor, ObjectRef target, bool string_keys, Zone *zone)
ElementsKind elements_kind () const
ZoneVector< MapRef > const & lookup_start_object_maps () const
ZoneVector< MapRef > const & transition_sources () const
void AddTransitionSource (MapRef map)
bool is_proxy_on_prototype () const
bool string_keys () const
OptionalObjectRef accessor () const
OptionalObjectRef target () const
Private Attributes
ElementsKind elements_kind_
bool string_keys_ {false}
ZoneVector< MapRef > lookup_start_object_maps_
ZoneVector< MapRef > transition_sources_
OptionalObjectRef accessor_
OptionalObjectRef target_
Detailed Description
Definition at line 33 of file access-info.h.
Constructor & Destructor Documentation
ElementAccessInfo() [1/2]
v8::internal::compiler::ElementAccessInfo::ElementAccessInfo (ZoneVector< MapRef > && lookup_start_object_maps, ElementsKind elements_kind, Zone * zone)
Definition at line 99 of file access-info.cc.
    : elements_kind_(elements_kind),
      lookup_start_object_maps_(lookup_start_object_maps),
      transition_sources_(zone) {
  CHECK(!lookup_start_object_maps.empty());
}
References CHECK, and lookup_start_object_maps().
ElementAccessInfo() [2/2]
v8::internal::compiler::ElementAccessInfo::ElementAccessInfo (MapRef map, ObjectRef accessor, ObjectRef target, bool string_keys, Zone * zone)
Definition at line 108 of file access-info.cc.
    : elements_kind_(map.elements_kind()),
      string_keys_(string_keys),
      lookup_start_object_maps_({map}, zone),
      transition_sources_(zone),
      accessor_(accessor),
      target_(target) {
  DCHECK(is_proxy_on_prototype());
}
Member Function Documentation
accessor()
OptionalObjectRef v8::internal::compiler::ElementAccessInfo::accessor () const [inline]
Definition at line 67 of file access-info.h.
{ return accessor_; }
References accessor_.
AddTransitionSource()
void v8::internal::compiler::ElementAccessInfo::AddTransitionSource (MapRef map) [inline]
Definition at line 49 of file access-info.h.
                                       {
    CHECK_EQ(lookup_start_object_maps_.size(), 1);
    transition_sources_.push_back(map);
  }
References CHECK_EQ, lookup_start_object_maps_, and transition_sources_.
elements_kind()
ElementsKind v8::internal::compiler::ElementAccessInfo::elements_kind () const [inline]
Definition at line 41 of file access-info.h.
{ return elements_kind_; }
References elements_kind_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess().
is_proxy_on_prototype()
bool v8::internal::compiler::ElementAccessInfo::is_proxy_on_prototype () const [inline]
Definition at line 57 of file access-info.h.
                                     {
    // Either both of {accessor_} and {target_} must be present, or neither.
    DCHECK_EQ(accessor_.has_value(), target_.has_value());
    DCHECK_IMPLIES(!accessor_.has_value(), !string_keys_);
    return accessor_.has_value();
  }
References accessor_, DCHECK_EQ, DCHECK_IMPLIES, string_keys_, and target_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject().
lookup_start_object_maps()
ZoneVector<MapRef> const& v8::internal::compiler::ElementAccessInfo::lookup_start_object_maps () const [inline]
Definition at line 42 of file access-info.h.
                                                             {
    return lookup_start_object_maps_;
  }
References lookup_start_object_maps_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), ElementAccessInfo(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess().
string_keys()
bool v8::internal::compiler::ElementAccessInfo::string_keys () const [inline]
Definition at line 66 of file access-info.h.
{ return string_keys_; }
References string_keys_.
target()
OptionalObjectRef v8::internal::compiler::ElementAccessInfo::target () const [inline]
Definition at line 68 of file access-info.h.
{ return target_; }
References target_.
transition_sources()
ZoneVector<MapRef> const& v8::internal::compiler::ElementAccessInfo::transition_sources () const [inline]
Definition at line 45 of file access-info.h.
                                                       {
    return transition_sources_;
  }
References transition_sources_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess().
Member Data Documentation
accessor_
OptionalObjectRef v8::internal::compiler::ElementAccessInfo::accessor_ [private]
Definition at line 75 of file access-info.h.
Referenced by accessor(), and is_proxy_on_prototype().
elements_kind_
ElementsKind v8::internal::compiler::ElementAccessInfo::elements_kind_ [private]
Definition at line 71 of file access-info.h.
Referenced by elements_kind().
lookup_start_object_maps_
ZoneVector<MapRef> v8::internal::compiler::ElementAccessInfo::lookup_start_object_maps_ [private]
Definition at line 73 of file access-info.h.
Referenced by AddTransitionSource(), and lookup_start_object_maps().
string_keys_
bool v8::internal::compiler::ElementAccessInfo::string_keys_ {false} [private]
Definition at line 72 of file access-info.h.
Referenced by is_proxy_on_prototype(), and string_keys().
target_
OptionalObjectRef v8::internal::compiler::ElementAccessInfo::target_ [private]
Definition at line 76 of file access-info.h.
Referenced by is_proxy_on_prototype(), and target().
transition_sources_
ZoneVector<MapRef> v8::internal::compiler::ElementAccessInfo::transition_sources_ [private]
Definition at line 74 of file access-info.h.
Referenced by AddTransitionSource(), and transition_sources().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/access-info.h
/mnt/V8SourceCode/src/compiler/access-info.cc