v8::internal::torque::TargetArchitecture Class Reference
#include <global-context.h>
Public Member Functions
TargetArchitecture (bool force_32bit)
Static Public Member Functions
static size_t TaggedSize ()
static size_t RawPtrSize ()
static size_t ExternalPointerSize ()
static size_t CppHeapPointerSize ()
static size_t TrustedPointerSize ()
static size_t ProtectedPointerSize ()
static size_t MaxHeapAlignment ()
static bool ArePointersCompressed ()
static int SmiTagAndShiftSize ()
Private Attributes
const size_t tagged_size_
const size_t raw_ptr_size_
const int smi_tag_and_shift_size_
const size_t external_ptr_size_
const size_t cppheap_ptr_size_
const size_t trusted_ptr_size_
Additional Inherited Members
Detailed Description
Definition at line 158 of file global-context.h.
Constructor & Destructor Documentation
TargetArchitecture()
v8::internal::torque::TargetArchitecture::TargetArchitecture (bool force_32bit) [explicit]
Definition at line 25 of file global-context.cc.
    : tagged_size_(force_32bit ? sizeof(int32_t) : kTaggedSize),
      raw_ptr_size_(force_32bit ? sizeof(int32_t) : kSystemPointerSize),
      smi_tag_and_shift_size_(
          kSmiTagSize + (force_32bit ? SmiTagging<kApiInt32Size>::kSmiShiftSize
                                     : kSmiShiftSize)),
      external_ptr_size_(force_32bit ? sizeof(int32_t)
                                     : kExternalPointerSlotSize),
      cppheap_ptr_size_(force_32bit ? sizeof(int32_t)
                                    : kCppHeapPointerSlotSize),
      trusted_ptr_size_(force_32bit ? sizeof(int32_t) : kTrustedPointerSize) {}
Member Function Documentation
ArePointersCompressed()
static bool v8::internal::torque::TargetArchitecture::ArePointersCompressed () [inline], [static]
Definition at line 169 of file global-context.h.
{ return TaggedSize() < RawPtrSize(); }
References RawPtrSize(), and TaggedSize().
CppHeapPointerSize()
static size_t v8::internal::torque::TargetArchitecture::CppHeapPointerSize () [inline], [static]
Definition at line 165 of file global-context.h.
{ return Get().cppheap_ptr_size_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
ExternalPointerSize()
static size_t v8::internal::torque::TargetArchitecture::ExternalPointerSize () [inline], [static]
Definition at line 164 of file global-context.h.
{ return Get().external_ptr_size_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
MaxHeapAlignment()
static size_t v8::internal::torque::TargetArchitecture::MaxHeapAlignment () [inline], [static]
Definition at line 168 of file global-context.h.
{ return TaggedSize(); }
References TaggedSize().
ProtectedPointerSize()
static size_t v8::internal::torque::TargetArchitecture::ProtectedPointerSize () [inline], [static]
Definition at line 167 of file global-context.h.
{ return TaggedSize(); }
References TaggedSize().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
RawPtrSize()
static size_t v8::internal::torque::TargetArchitecture::RawPtrSize () [inline], [static]
Definition at line 163 of file global-context.h.
{ return Get().raw_ptr_size_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), ArePointersCompressed(), and v8::internal::torque::SizeOf().
SmiTagAndShiftSize()
static int v8::internal::torque::TargetArchitecture::SmiTagAndShiftSize () [inline], [static]
Definition at line 170 of file global-context.h.
{ return Get().smi_tag_and_shift_size_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{csa-generator.cc}::GetBitFieldSpecialization(), and v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::ValueTypeFieldIterator::operator*().
TaggedSize()
static size_t v8::internal::torque::TargetArchitecture::TaggedSize () [inline], [static]
Definition at line 162 of file global-context.h.
{ return Get().tagged_size_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), ArePointersCompressed(), v8::internal::torque::BuildFlags::BuildFlags(), v8::internal::torque::ClassType::ComputeHeaderSlotKinds(), v8::internal::torque::anonymous_namespace{types.cc}::ComputeSlotKindsHelper(), v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), MaxHeapAlignment(), ProtectedPointerSize(), and v8::internal::torque::SizeOf().
TrustedPointerSize()
static size_t v8::internal::torque::TargetArchitecture::TrustedPointerSize () [inline], [static]
Definition at line 166 of file global-context.h.
{ return Get().trusted_ptr_size_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::AbstractType::AlignmentLog2(), and v8::internal::torque::SizeOf().
Member Data Documentation
cppheap_ptr_size_
const size_t v8::internal::torque::TargetArchitecture::cppheap_ptr_size_ [private]
Definition at line 177 of file global-context.h.
external_ptr_size_
const size_t v8::internal::torque::TargetArchitecture::external_ptr_size_ [private]
Definition at line 176 of file global-context.h.
raw_ptr_size_
const size_t v8::internal::torque::TargetArchitecture::raw_ptr_size_ [private]
Definition at line 174 of file global-context.h.
smi_tag_and_shift_size_
const int v8::internal::torque::TargetArchitecture::smi_tag_and_shift_size_ [private]
Definition at line 175 of file global-context.h.
tagged_size_
const size_t v8::internal::torque::TargetArchitecture::tagged_size_ [private]
Definition at line 173 of file global-context.h.
trusted_ptr_size_
const size_t v8::internal::torque::TargetArchitecture::trusted_ptr_size_ [private]
Definition at line 178 of file global-context.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/global-context.h
/mnt/V8SourceCode/src/torque/global-context.cc