v8::internal::StringStream Class Reference
#include <string-stream.h>
Classes
class FmtElm
Public Types
enum ObjectPrintMode { kPrintObjectConcise
, kPrintObjectVerbose
 }
Public Member Functions
StringStream (StringAllocator *allocator, ObjectPrintMode object_print_mode=kPrintObjectVerbose)
bool Put (char c)
bool Put (Tagged< String > str)
bool Put (Tagged< String > str, int start, int end)
void Add (const char *format)
void Add (base::Vector< const char > format)
template<typename... Args>
void Add (const char *format, Args... args)
template<typename... Args>
void Add (base::Vector< const char > format, Args... args)
void OutputToFile (FILE *out)
void OutputToStdOut ()
void Log (Isolate *isolate)
DirectHandle< String > ToString (Isolate *isolate)
std::unique_ptr< char[]> ToCString () const
int length () const
void PrintName (Tagged< Object > o)
void PrintFixedArray (Tagged< FixedArray > array, unsigned int limit)
void PrintByteArray (Tagged< ByteArray > ba)
void PrintUsingMap (Isolate *isolate, Tagged< JSObject > js_object)
void PrintPrototype (Isolate *isolate, Tagged< JSFunction > fun, Tagged< Object > receiver)
void PrintSecurityTokenIfChanged (Isolate *isolate, Tagged< JSFunction > function)
void PrintFunction (Isolate *isolate, Tagged< JSFunction > function, Tagged< Object > receiver)
void Reset ()
void PrintMentionedObjectCache (Isolate *isolate)
Static Public Member Functions
static V8_EXPORT_PRIVATE void ClearMentionedObjectCache (Isolate *isolate)
Static Public Attributes
static const int kInitialCapacity = 16
Private Member Functions
void Add (base::Vector< const char > format, base::Vector< FmtElm > elms)
void PrintObject (Tagged< Object > obj)
bool full () const
int space () const
DISALLOW_IMPLICIT_CONSTRUCTORS (StringStream)
Private Attributes
StringAllocator * allocator_
ObjectPrintMode object_print_mode_
unsigned capacity_
unsigned length_
char * buffer_
Detailed Description
Definition at line 91 of file string-stream.h.
Member Enumeration Documentation
ObjectPrintMode
enum v8::internal::StringStream::ObjectPrintMode
Enumerator
kPrintObjectConcise
kPrintObjectVerbose
Definition at line 142 of file string-stream.h.
{ kPrintObjectConcise, kPrintObjectVerbose };
Constructor & Destructor Documentation
StringStream()
v8::internal::StringStream::StringStream (StringAllocator * allocator, ObjectPrintMode object_print_mode = kPrintObjectVerbose) [inline], [explicit]
Definition at line 143 of file string-stream.h.
      : allocator_(allocator),
        object_print_mode_(object_print_mode),
        capacity_(kInitialCapacity),
        length_(0),
        buffer_(allocator_->allocate(kInitialCapacity)) {
    buffer_[0] = 0;
  }
References buffer_.
Member Function Documentation
Add() [1/5]
void v8::internal::StringStream::Add (base::Vector< const char > format) [inline]
Definition at line 157 of file string-stream.h.
                                          {
    Add(format, base::Vector<FmtElm>());
  }
References Add(), and v8::internal::format.
Add() [2/5]
template<typename... Args>
void v8::internal::StringStream::Add (base::Vector< const char > format, Args... args) [inline]
Definition at line 167 of file string-stream.h.
                                                        {
    FmtElm elems[]{args...};
    Add(format, base::ArrayVector(elems));
  }
References Add(), v8::base::args, v8::base::ArrayVector(), and v8::internal::format.
Add() [3/5]
void v8::internal::StringStream::Add (base::Vector< const char > format, base::Vector< FmtElm > elms) [private]
Definition at line 88 of file string-stream.cc.
                                                {
  // If we already ran out of space then return immediately.
  if (full()) return;
  int offset = 0;
  int elm = 0;
  while (offset < format.length()) {
    if (format[offset] != '%' || elm == elms.length()) {
      Put(format[offset]);
      offset++;
      continue;
    }
    // Read this formatting directive into a temporary buffer
    base::EmbeddedVector<char, 24> temp;
    int format_length = 0;
    // Skip over the whole control character sequence until the
    // format element type
    temp[format_length++] = format[offset++];
    while (offset < format.length() && IsControlChar(format[offset]))
      temp[format_length++] = format[offset++];
    if (offset >= format.length()) return;
    char type = format[offset];
    temp[format_length++] = type;
    temp[format_length] = '\0';
    offset++;
    FmtElm current = elms[elm++];
    switch (type) {
      case 's': {
        DCHECK_EQ(FmtElm::C_STR, current.type_);
        const char* value = current.data_.u_c_str_;
        Add(value);
        break;
      }
      case 'w': {
        DCHECK_EQ(FmtElm::LC_STR, current.type_);
        base::Vector<const base::uc16> value = *current.data_.u_lc_str_;
        for (int i = 0; i < value.length(); i++)
          Put(static_cast<char>(value[i]));
        break;
      }
      case 'o': {
        DCHECK_EQ(FmtElm::OBJ, current.type_);
        Tagged<Object> obj(current.data_.u_obj_);
        PrintObject(obj);
        break;
      }
      case 'k': {
        DCHECK_EQ(FmtElm::INT, current.type_);
        int value = current.data_.u_int_;
        if (0x20 <= value && value <= 0x7F) {
          Put(value);
        } else if (value <= 0xFF) {
          Add("\\x%02x", value);
        } else {
          Add("\\u%04x", value);
        }
        break;
      }
      case 'i':
      case 'd':
      case 'u':
      case 'x':
      case 'c':
      case 'X': {
        int value = current.data_.u_int_;
        base::EmbeddedVector<char, 24> formatted;
        int length = SNPrintF(formatted, temp.begin(), value);
        Add(base::Vector<const char>(formatted.begin(), length));
        break;
      }
      case 'f':
      case 'g':
      case 'G':
      case 'e':
      case 'E': {
        double value = current.data_.u_double_;
        int inf = std::isinf(value);
        if (inf == -1) {
          Add("-inf");
        } else if (inf == 1) {
          Add("inf");
        } else if (std::isnan(value)) {
          Add("nan");
        } else {
          base::EmbeddedVector<char, 28> formatted;
          SNPrintF(formatted, temp.begin(), value);
          Add(formatted.begin());
        }
        break;
      }
      case 'p': {
        void* value = current.data_.u_pointer_;
        base::EmbeddedVector<char, 20> formatted;
        SNPrintF(formatted, temp.begin(), value);
        Add(formatted.begin());
        break;
      }
      default:
        UNREACHABLE();
    }
  }
  // Verify that the buffer is 0-terminated
  DCHECK_EQ(buffer_[length_], '\0');
}
References Add(), v8::base::Vector< T >::begin(), buffer_, v8::internal::StringStream::FmtElm::C_STR, v8::internal::StringStream::FmtElm::data_, DCHECK_EQ, v8::internal::format, full(), v8::internal::StringStream::FmtElm::INT, v8::internal::IsControlChar(), v8::internal::StringStream::FmtElm::LC_STR, v8::base::Vector< T >::length(), length(), length_, v8::internal::StringStream::FmtElm::OBJ, PrintObject(), Put(), v8::base::SNPrintF(), v8::internal::tracing::type, v8::internal::StringStream::FmtElm::u_c_str_, v8::internal::StringStream::FmtElm::u_double_, v8::internal::StringStream::FmtElm::u_int_, v8::internal::StringStream::FmtElm::u_lc_str_, v8::internal::StringStream::FmtElm::u_obj_, v8::internal::StringStream::FmtElm::u_pointer_, v8::internal::UNREACHABLE(), and v8::internal::value.
Add() [4/5]
void v8::internal::StringStream::Add (const char * format) [inline]
Definition at line 156 of file string-stream.h.
{ Add(base::CStrVector(format)); }
References Add(), v8::base::CStrVector(), and v8::internal::format.
Referenced by Add(), v8::internal::anonymous_namespace{date.cc}::FormatDate(), v8::internal::JSObject::JSObjectShortPrint(), v8::internal::StackFrame::Print(), v8::internal::JavaScriptFrame::Print(), v8::internal::BuiltinExitFrame::Print(), v8::internal::ApiCallbackExitFrame::Print(), v8::internal::ApiAccessorExitFrame::Print(), PrintByteArray(), PrintFixedArray(), v8::internal::anonymous_namespace{frames.cc}::PrintFunctionSource(), v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), PrintMentionedObjectCache(), PrintName(), PrintObject(), PrintPrototype(), PrintSecurityTokenIfChanged(), v8::internal::Isolate::PrintStack(), v8::internal::String::PrintUC16(), PrintUsingMap(), v8::internal::ShortPrint(), and v8::internal::String::StringShortPrint().
Add() [5/5]
template<typename... Args>
void v8::internal::StringStream::Add (const char * format, Args... args) [inline]
Definition at line 162 of file string-stream.h.
                                             {
    Add(base::CStrVector(format), args...);
  }
References Add(), v8::base::args, v8::base::CStrVector(), and v8::internal::format.
ClearMentionedObjectCache()
void v8::internal::StringStream::ClearMentionedObjectCache (Isolate * isolate) [static]
Definition at line 256 of file string-stream.cc.
                                                             {
  isolate->set_string_stream_current_security_token(Tagged<Object>());
  if (isolate->string_stream_debug_object_cache() == nullptr) {
    isolate->set_string_stream_debug_object_cache(new DebugObjectCache());
  }
  isolate->string_stream_debug_object_cache()->clear();
}
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::Isolate::PrintStack(), and v8::internal::Isolate::StackTraceString().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::StringStream::DISALLOW_IMPLICIT_CONSTRUCTORS (StringStream) [private]
full()
bool v8::internal::StringStream::full () const [inline], [private]
Definition at line 217 of file string-stream.h.
{ return (capacity_ - length_) == 1; }
References capacity_, and length_.
Referenced by Add(), and Put().
length()
int v8::internal::StringStream::length () const [inline]
Definition at line 178 of file string-stream.h.
{ return length_; }
References length_.
Referenced by Add(), v8::internal::anonymous_namespace{date.cc}::FormatDate(), PrintMentionedObjectCache(), PrintObject(), and PrintPrototype().
Log()
void v8::internal::StringStream::Log (Isolate * isolate)
Definition at line 231 of file string-stream.cc.
                                       {
  LOG(isolate, StringEvent("StackDump", buffer_));
}
References buffer_, and LOG.
Referenced by v8::internal::Isolate::PrintStack().
OutputToFile()
void v8::internal::StringStream::OutputToFile (FILE * out)
Definition at line 235 of file string-stream.cc.
                                         {
  // Dump the output to stdout, but make sure to break it up into
  // manageable chunks to avoid losing parts of the output in the OS
  // printing code. This is a problem on Windows in particular; see
  // the VPrint() function implementations in platform-win32.cc.
  unsigned position = 0;
  for (unsigned next; (next = position + 2048) < length_; position = next) {
    char save = buffer_[next];
    buffer_[next] = '\0';
    internal::PrintF(out, "%s", &buffer_[position]);
    buffer_[next] = save;
  }
  internal::PrintF(out, "%s", &buffer_[position]);
}
References buffer_, length_, and v8::internal::PrintF().
Referenced by OutputToStdOut(), and v8::internal::Isolate::PrintStack().
OutputToStdOut()
void v8::internal::StringStream::OutputToStdOut () [inline]
Definition at line 174 of file string-stream.h.
{ OutputToFile(stdout); }
References OutputToFile().
Referenced by v8::internal::Isolate::StackTraceString().
PrintByteArray()
void v8::internal::StringStream::PrintByteArray (Tagged< ByteArray > ba)
Definition at line 346 of file string-stream.cc.
                                                              {
  unsigned int limit = byte_array->length();
  for (unsigned int i = 0; i < 10 && i < limit; i++) {
    uint8_t b = byte_array->get(i);
    Add(" %d: %3d 0x%02x", i, b, b);
    if (b >= ' ' && b <= '~') {
      Add(" '%c'", b);
    } else if (b == '\n') {
      Add(" '\n'");
    } else if (b == '\r') {
      Add(" '\r'");
    } else if (b >= 1 && b <= 26) {
      Add(" ^%c", b + 'A' - 1);
    }
    Add("\n");
  }
  if (limit >= 10) {
    Add(" ...\n");
  }
}
References Add().
Referenced by PrintMentionedObjectCache().
PrintFixedArray()
void v8::internal::StringStream::PrintFixedArray (Tagged< FixedArray > array, unsigned int limit)
Definition at line 330 of file string-stream.cc.
                                                       {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  for (unsigned int i = 0; i < 10 && i < limit; i++) {
    Tagged<Object> element = array->get(i);
    if (IsTheHole(element, roots)) continue;
    for (int len = 1; len < 18; len++) {
      Put(' ');
    }
    Add("%d: %o\n", i, array->get(i));
  }
  if (limit >= 10) {
    Add(" ...\n");
  }
}
References Add(), v8::internal::GetReadOnlyRoots(), and Put().
Referenced by PrintMentionedObjectCache().
PrintFunction()
void v8::internal::StringStream::PrintFunction (Isolate * isolate, Tagged< JSFunction > function, Tagged< Object > receiver)
Definition at line 413 of file string-stream.cc.
                                                          {
  PrintPrototype(isolate, fun, receiver);
}
References PrintPrototype().
Referenced by v8::internal::JavaScriptFrame::Print(), v8::internal::BuiltinExitFrame::Print(), and v8::internal::ApiCallbackExitFrame::Print().
PrintMentionedObjectCache()
void v8::internal::StringStream::PrintMentionedObjectCache (Isolate * isolate)
Definition at line 367 of file string-stream.cc.
                                                             {
  if (object_print_mode_ == kPrintObjectConcise) return;
  DebugObjectCache* debug_object_cache =
      isolate->string_stream_debug_object_cache();
  Add("-- ObjectCacheKey --\n\n");
  for (size_t i = 0; i < debug_object_cache->size(); i++) {
    Tagged<HeapObject> printee = *(*debug_object_cache)[i];
    Add(" #%d# %p: ", static_cast<int>(i),
        reinterpret_cast<void*>(printee.ptr()));
    ShortPrint(printee, this);
    Add("\n");
    if (IsJSObject(printee)) {
      if (IsJSPrimitiveWrapper(printee)) {
        Add(" value(): %o\n",
            Cast<JSPrimitiveWrapper>(printee)->value());
      }
      PrintUsingMap(isolate, Cast<JSObject>(printee));
      if (IsJSArray(printee)) {
        Tagged<JSArray> array = Cast<JSArray>(printee);
        if (array->HasObjectElements()) {
          unsigned int limit = Cast<FixedArray>(array->elements())->length();
          unsigned int length = static_cast<uint32_t>(
              Object::NumberValue(Cast<JSArray>(array)->length()));
          if (length < limit) limit = length;
          PrintFixedArray(Cast<FixedArray>(array->elements()), limit);
        }
      }
    } else if (IsByteArray(printee)) {
      PrintByteArray(Cast<ByteArray>(printee));
    } else if (IsFixedArray(printee)) {
      unsigned int limit = Cast<FixedArray>(printee)->length();
      PrintFixedArray(Cast<FixedArray>(printee), limit);
    }
  }
}
References Add(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kPrintObjectConcise, length(), v8::internal::Object::NumberValue(), object_print_mode_, PrintByteArray(), PrintFixedArray(), PrintUsingMap(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::ShortPrint(), and v8::internal::value.
Referenced by v8::internal::Isolate::PrintStack().
PrintName()
void v8::internal::StringStream::PrintName (Tagged< Object > o)
Definition at line 289 of file string-stream.cc.
                                                {
  if (IsString(name)) {
    Tagged<String> str = Cast<String>(name);
    if (str->length() > 0) {
      Put(str);
    } else {
      Add("/* anonymous */");
    }
  } else {
    Add("%o", name);
  }
}
References Add(), v8::internal::name, and Put().
Referenced by v8::internal::JavaScriptFrame::Print(), and PrintPrototype().
PrintObject()
void v8::internal::StringStream::PrintObject (Tagged< Object > obj) [private]
Definition at line 194 of file string-stream.cc.
                                               {
  ShortPrint(o, this);
  if (IsString(o)) {
    if (Cast<String>(o)->length() <= String::kMaxShortPrintLength) {
      return;
    }
  } else if (IsNumber(o) || IsOddball(o)) {
    return;
  }
  if (IsHeapObject(o) && object_print_mode_ == kPrintObjectVerbose) {
    // TODO(delphick): Consider whether we can get the isolate without using
    // TLS.
    Isolate* isolate = Isolate::Current();
    DebugObjectCache* debug_object_cache =
        isolate->string_stream_debug_object_cache();
    for (size_t i = 0; i < debug_object_cache->size(); i++) {
      if (*(*debug_object_cache)[i] == o) {
        Add("#%d#", static_cast<int>(i));
        return;
      }
    }
    if (debug_object_cache->size() < kMentionedObjectCacheMaxSize) {
      Add("#%d#", static_cast<int>(debug_object_cache->size()));
      debug_object_cache->push_back(handle(Cast<HeapObject>(o), isolate));
    } else {
      Add("@%p", o);
    }
  }
}
References Add(), v8::internal::Isolate::Current(), v8::internal::handle(), v8::internal::IsHeapObject(), v8::internal::IsNumber(), v8::internal::String::kMaxShortPrintLength, v8::internal::kMentionedObjectCacheMaxSize, kPrintObjectVerbose, length(), object_print_mode_, and v8::internal::ShortPrint().
Referenced by Add().
PrintPrototype()
void v8::internal::StringStream::PrintPrototype (Isolate * isolate, Tagged< JSFunction > fun, Tagged< Object > receiver)
Definition at line 418 of file string-stream.cc.
                                                           {
  Tagged<Object> name = fun->shared()->Name();
  bool print_name = false;
  if (IsNullOrUndefined(receiver, isolate) || IsTheHole(receiver, isolate) ||
      IsJSProxy(receiver) || IsWasmObject(receiver)) {
    print_name = true;
  } else if (!isolate->context().is_null()) {
    if (!IsJSObject(receiver)) {
      receiver =
          Object::GetPrototypeChainRootMap(receiver, isolate)->prototype();
    }
    for (PrototypeIterator iter(isolate, Cast<JSObject>(receiver),
                                kStartAtReceiver);
         !iter.IsAtEnd(); iter.Advance()) {
      if (!IsJSObject(iter.GetCurrent())) break;
      Tagged<Object> key = iter.GetCurrent<JSObject>()->SlowReverseLookup(fun);
      if (!IsUndefined(key, isolate)) {
        if (!IsString(name) || !IsString(key) ||
            !Cast<String>(name)->Equals(Cast<String>(key))) {
          print_name = true;
        }
        if (IsString(name) && Cast<String>(name)->length() == 0) {
          print_name = false;
        }
        name = key;
        break;
      }
    }
  }
  PrintName(name);
  // Also known as - if the name in the function doesn't match the name under
  // which it was looked up.
  if (print_name) {
    Add("(aka ");
    PrintName(fun->shared()->Name());
    Put(')');
  }
}
References Add(), v8::internal::Isolate::context(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::Object::GetPrototypeChainRootMap(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsNullOrUndefined(), v8::internal::IsWasmObject(), v8::internal::key, v8::internal::kStartAtReceiver, length(), v8::internal::name, PrintName(), and Put().
Referenced by PrintFunction().
PrintSecurityTokenIfChanged()
void v8::internal::StringStream::PrintSecurityTokenIfChanged (Isolate * isolate, Tagged< JSFunction > function)
Definition at line 403 of file string-stream.cc.
                                                                       {
  Tagged<Object> token = fun->native_context()->security_token();
  // Use SafeEquals because the cached token might be a stale pointer.
  if (token.SafeEquals(isolate->string_stream_current_security_token())) {
    Add("Security context: %o\n", token);
    isolate->set_string_stream_current_security_token(token);
  }
}
References Add(), and v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals().
Referenced by v8::internal::JavaScriptFrame::Print(), v8::internal::BuiltinExitFrame::Print(), and v8::internal::ApiCallbackExitFrame::Print().
PrintUsingMap()
void v8::internal::StringStream::PrintUsingMap (Isolate * isolate, Tagged< JSObject > js_object)
Definition at line 302 of file string-stream.cc.
                                                                             {
  Tagged<Map> map = js_object->map();
  Tagged<DescriptorArray> descs = map->instance_descriptors(isolate);
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    PropertyDetails details = descs->GetDetails(i);
    if (details.location() == PropertyLocation::kField) {
      DCHECK_EQ(PropertyKind::kData, details.kind());
      Tagged<Object> key = descs->GetKey(i);
      if (IsString(key) || IsNumber(key)) {
        int len = 3;
        if (IsString(key)) {
          len = Cast<String>(key)->length();
        }
        for (; len < 18; len++) Put(' ');
        if (IsString(key)) {
          Put(Cast<String>(key));
        } else {
          ShortPrint(key);
        }
        Add(": ");
        FieldIndex index = FieldIndex::ForDescriptor(map, i);
        Tagged<Object> value = js_object->RawFastPropertyAt(index);
        Add("%o\n", value);
      }
    }
  }
}
References Add(), DCHECK_EQ, v8::internal::FieldIndex::ForDescriptor(), v8::internal::index, v8::internal::IsNumber(), v8::internal::kData, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), Put(), v8::internal::ShortPrint(), and v8::internal::value.
Referenced by PrintMentionedObjectCache().
Put() [1/3]
bool v8::internal::StringStream::Put (char c)
Definition at line 36 of file string-stream.cc.
                             {
  if (full()) return false;
  DCHECK(length_ < capacity_);
  // Since the trailing '\0' is not accounted for in length_ fullness is
  // indicated by a difference of 1 between length_ and capacity_. Thus when
  // reaching a difference of 2 we need to grow the buffer.
  if (length_ == capacity_ - 2) {
    unsigned new_capacity = capacity_;
    char* new_buffer = allocator_->grow(&new_capacity);
    if (new_capacity > capacity_) {
      capacity_ = new_capacity;
      buffer_ = new_buffer;
    } else {
      // Reached the end of the available buffer.
      DCHECK_GE(capacity_, 5);
      length_ = capacity_ - 1; // Indicate fullness of the stream.
      buffer_[length_ - 4] = '.';
      buffer_[length_ - 3] = '.';
      buffer_[length_ - 2] = '.';
      buffer_[length_ - 1] = '\n';
      buffer_[length_] = '\0';
      return false;
    }
  }
  buffer_[length_] = c;
  buffer_[length_ + 1] = '\0';
  length_++;
  return true;
}
References allocator_, buffer_, capacity_, v8::internal::DCHECK(), DCHECK_GE, full(), v8::internal::StringAllocator::grow(), and length_.
Referenced by Add(), v8::internal::JSObject::JSObjectShortPrint(), PrintFixedArray(), PrintName(), PrintPrototype(), v8::internal::String::PrintUC16(), PrintUsingMap(), Put(), and v8::internal::String::StringShortPrint().
Put() [2/3]
bool v8::internal::StringStream::Put (Tagged< String > str)
Definition at line 271 of file string-stream.cc.
                                         {
  return Put(str, 0, str->length());
}
References Put().
Put() [3/3]
bool v8::internal::StringStream::Put (Tagged< String > str, int start, int end)
Definition at line 275 of file string-stream.cc.
                                                             {
  StringCharacterStream stream(str, start);
  for (int i = start; i < end && stream.HasMore(); i++) {
    uint16_t c = stream.GetNext();
    if (c >= 127 || c < 32) {
      c = '?';
    }
    if (!Put(static_cast<char>(c))) {
      return false; // Output was truncated.
    }
  }
  return true;
}
References v8::internal::compiler::end(), v8::internal::StringCharacterStream::GetNext(), v8::internal::StringCharacterStream::HasMore(), and Put().
Reset()
void v8::internal::StringStream::Reset () [inline]
Definition at line 193 of file string-stream.h.
               {
    length_ = 0;
    buffer_[0] = 0;
  }
References buffer_, and length_.
space()
int v8::internal::StringStream::space () const [inline], [private]
Definition at line 218 of file string-stream.h.
{ return capacity_ - length_; }
References capacity_, and length_.
ToCString()
std::unique_ptr< char[]> v8::internal::StringStream::ToCString () const
Definition at line 224 of file string-stream.cc.
                                                    {
  char* str = NewArray<char>(length_ + 1);
  MemCopy(str, buffer_, length_);
  str[length_] = '\0';
  return std::unique_ptr<char[]>(str);
}
References buffer_, length_, and v8::internal::MemCopy().
Referenced by _v8_internal_Expand_StackTrace(), and v8::internal::HeapObject::HeapObjectShortPrint().
ToString()
DirectHandle< String > v8::internal::StringStream::ToString (Isolate * isolate)
Definition at line 250 of file string-stream.cc.
                                                            {
  return isolate->factory()
      ->NewStringFromUtf8(base::Vector<const char>(buffer_, length_))
      .ToHandleChecked();
}
References buffer_, v8::internal::Isolate::factory(), length_, and v8::internal::Factory::NewStringFromUtf8().
Referenced by v8::internal::Isolate::StackTraceString().
Member Data Documentation
allocator_
StringAllocator* v8::internal::StringStream::allocator_ [private]
Definition at line 211 of file string-stream.h.
Referenced by Put().
buffer_
char* v8::internal::StringStream::buffer_ [private]
Definition at line 215 of file string-stream.h.
Referenced by Add(), Log(), OutputToFile(), Put(), Reset(), StringStream(), ToCString(), and ToString().
capacity_
unsigned v8::internal::StringStream::capacity_ [private]
Definition at line 213 of file string-stream.h.
Referenced by full(), Put(), and space().
kInitialCapacity
const int v8::internal::StringStream::kInitialCapacity = 16 [static]
Definition at line 205 of file string-stream.h.
length_
unsigned v8::internal::StringStream::length_ [private]
Definition at line 214 of file string-stream.h.
Referenced by Add(), full(), length(), OutputToFile(), Put(), Reset(), space(), ToCString(), and ToString().
object_print_mode_
ObjectPrintMode v8::internal::StringStream::object_print_mode_ [private]
Definition at line 212 of file string-stream.h.
Referenced by PrintMentionedObjectCache(), and PrintObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/string-stream.h
/mnt/V8SourceCode/src/strings/string-stream.cc