v8::internal::compiler::CallRuntimeParameters Class Reference
#include <js-operator.h>
Public Member Functions
CallRuntimeParameters (Runtime::FunctionId id, size_t arity)
Runtime::FunctionId id () const
size_t arity () const
Private Attributes
const Runtime::FunctionId id_
const size_t arity_
Detailed Description
Definition at line 311 of file js-operator.h.
Constructor & Destructor Documentation
CallRuntimeParameters()
v8::internal::compiler::CallRuntimeParameters::CallRuntimeParameters (Runtime::FunctionId id, size_t arity) [inline]
Definition at line 313 of file js-operator.h.
      : id_(id), arity_(arity) {}
Member Function Documentation
arity()
size_t v8::internal::compiler::CallRuntimeParameters::arity () const [inline]
Definition at line 317 of file js-operator.h.
{ return arity_; }
Referenced by v8::internal::compiler::JSOperatorBuilder::CallRuntime(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSIntrinsicLowering::ReduceCall(), and v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack().
id()
Runtime::FunctionId v8::internal::compiler::CallRuntimeParameters::id () const [inline]
Definition at line 316 of file js-operator.h.
{ return id_; }
Referenced by v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSIntrinsicLowering::Reduce().
Member Data Documentation
arity_
const size_t v8::internal::compiler::CallRuntimeParameters::arity_ [private]
Definition at line 321 of file js-operator.h.
id_
const Runtime::FunctionId v8::internal::compiler::CallRuntimeParameters::id_ [private]
Definition at line 320 of file js-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h