v8_inspector::PromiseHandlerTracker Class Reference
#include <injected-script.h>
Public Types
enum class DiscardReason { kFulfilled
, kPromiseCollected
, kTearDown
 }
using Id = int64_t
Public Member Functions
PromiseHandlerTracker ()
PromiseHandlerTracker (const PromiseHandlerTracker &)=delete
void operator= (const PromiseHandlerTracker &)=delete
~PromiseHandlerTracker ()
template<typename... Args>
Id create (Args &&... args)
void discard (Id id, DiscardReason reason)
InjectedScript::ProtocolPromiseHandler * get (Id id) const
Private Member Functions
void sendFailure (InjectedScript::ProtocolPromiseHandler *handler, const protocol::DispatchResponse &response) const
void discardAll ()
Private Attributes
std::map< Id, std::unique_ptr< InjectedScript::ProtocolPromiseHandler > > m_promiseHandlers
Id m_lastUsedId = 1
Detailed Description
Definition at line 279 of file injected-script.h.
Member Typedef Documentation
Id
using v8_inspector::PromiseHandlerTracker::Id = int64_t
Definition at line 295 of file injected-script.h.
Member Enumeration Documentation
DiscardReason
enum v8_inspector::PromiseHandlerTracker::DiscardReason [strong]
Enumerator
kFulfilled
kPromiseCollected
kTearDown
Definition at line 290 of file injected-script.h.
                           {
    kFulfilled,
    kPromiseCollected,
    kTearDown,
  };
Constructor & Destructor Documentation
PromiseHandlerTracker() [1/2]
v8_inspector::PromiseHandlerTracker::PromiseHandlerTracker () [default]
PromiseHandlerTracker() [2/2]
v8_inspector::PromiseHandlerTracker::PromiseHandlerTracker (const PromiseHandlerTracker &) [delete]
 PromiseHandlerTracker()
v8_inspector::PromiseHandlerTracker::~PromiseHandlerTracker ()
Definition at line 1187 of file injected-script.cc.
{ discardAll(); }
Member Function Documentation
create()
template<typename... Args>
PromiseHandlerTracker::Id v8_inspector::PromiseHandlerTracker::create (Args &&... args)
Definition at line 1190 of file injected-script.cc.
                                                                    {
  Id id = m_lastUsedId++;
  InjectedScript::ProtocolPromiseHandler* handler =
      new InjectedScript::ProtocolPromiseHandler(id,
                                                 std::forward<Args>(args)...);
  m_promiseHandlers.emplace(id, handler);
  return id;
}
References v8::base::args.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add().
discard()
void v8_inspector::PromiseHandlerTracker::discard (Id id, DiscardReason reason)
Definition at line 1199 of file injected-script.cc.
                                                               {
  auto iter = m_promiseHandlers.find(id);
  CHECK_NE(iter, m_promiseHandlers.end());
  InjectedScript::ProtocolPromiseHandler* handler = iter->second.get();
  switch (reason) {
    case DiscardReason::kPromiseCollected:
      sendFailure(handler, Response::ServerError("Promise was collected"));
      break;
    case DiscardReason::kTearDown:
      sendFailure(handler, Response::ServerError(
                               "Tearing down inspector/session/context"));
      break;
    case DiscardReason::kFulfilled:
      // Do nothing.
      break;
  }
  m_promiseHandlers.erase(id);
}
References CHECK_NE.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::cleanup(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
discardAll()
void v8_inspector::PromiseHandlerTracker::discardAll () [private]
Definition at line 1242 of file injected-script.cc.
                                       {
  while (!m_promiseHandlers.empty()) {
    discard(m_promiseHandlers.begin()->first, DiscardReason::kTearDown);
  }
  CHECK(m_promiseHandlers.empty());
}
References CHECK.
get()
InjectedScript::ProtocolPromiseHandler * v8_inspector::PromiseHandlerTracker::get (Id id) const
Definition at line 1220 of file injected-script.cc.
                 {
  auto iter = m_promiseHandlers.find(id);
  if (iter == m_promiseHandlers.end()) return nullptr;
  return iter->second.get();
}
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
operator=()
void v8_inspector::PromiseHandlerTracker::operator= (const PromiseHandlerTracker &) [delete]
sendFailure()
void v8_inspector::PromiseHandlerTracker::sendFailure (InjectedScript::ProtocolPromiseHandler * handler, const protocol::DispatchResponse & response) const [private]
Definition at line 1228 of file injected-script.cc.
                                                    {
  V8InspectorImpl* inspector = handler->m_inspector;
  V8InspectorSessionImpl* session =
      inspector->sessionById(handler->m_contextGroupId, handler->m_sessionId);
  if (!session) return;
  InjectedScript::ContextScope scope(session, handler->m_executionContextId);
  Response res = scope.initialize();
  if (!res.IsSuccess()) return;
  EvaluateCallback::sendFailure(handler->m_callback, scope.injectedScript(),
                                response);
}
References v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::injectedScript(), v8_inspector::InjectedScript::ProtocolPromiseHandler::m_callback, v8_inspector::InjectedScript::ProtocolPromiseHandler::m_contextGroupId, v8_inspector::InjectedScript::ProtocolPromiseHandler::m_executionContextId, v8_inspector::InjectedScript::ProtocolPromiseHandler::m_inspector, v8_inspector::InjectedScript::ProtocolPromiseHandler::m_sessionId, v8_inspector::EvaluateCallback::sendFailure(), and v8_inspector::V8InspectorImpl::sessionById().
Member Data Documentation
m_lastUsedId
Id v8_inspector::PromiseHandlerTracker::m_lastUsedId = 1 [private]
Definition at line 309 of file injected-script.h.
m_promiseHandlers
std::map<Id, std::unique_ptr<InjectedScript::ProtocolPromiseHandler> > v8_inspector::PromiseHandlerTracker::m_promiseHandlers [private]
Definition at line 308 of file injected-script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/injected-script.h
/mnt/V8SourceCode/src/inspector/injected-script.cc