v8::internal::ParkingConditionVariable Class Reference
#include <parked-scope.h>
Public Member Functions
ParkingConditionVariable ()=default
ParkingConditionVariable (const ParkingConditionVariable &)=delete
ParkingConditionVariable & operator= (const ParkingConditionVariable &)=delete
void ParkedWait (LocalIsolate *local_isolate, base::Mutex *mutex)
void ParkedWait (LocalHeap *local_heap, base::Mutex *mutex)
void ParkedWait (const ParkedScope &scope, base::Mutex *mutex)
bool ParkedWaitFor (LocalIsolate *local_isolate, base::Mutex *mutex, const base::TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
bool ParkedWaitFor (LocalHeap *local_heap, base::Mutex *mutex, const base::TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
bool ParkedWaitFor (const ParkedScope &scope, base::Mutex *mutex, const base::TimeDelta &rel_time) V8_WARN_UNUSED_RESULT
Detailed Description
Definition at line 130 of file parked-scope.h.
Constructor & Destructor Documentation
ParkingConditionVariable() [1/2]
v8::internal::ParkingConditionVariable::ParkingConditionVariable () [default]
ParkingConditionVariable() [2/2]
v8::internal::ParkingConditionVariable::ParkingConditionVariable (const ParkingConditionVariable &) [delete]
Member Function Documentation
operator=()
ParkingConditionVariable& v8::internal::ParkingConditionVariable::operator= (const ParkingConditionVariable &) [delete]
ParkedWait() [1/3]
void v8::internal::ParkingConditionVariable::ParkedWait (const ParkedScope & scope, base::Mutex * mutex) [inline]
Definition at line 140 of file parked-scope.h.
                                                              {
    USE(scope);
    Wait(mutex);
  }
References USE.
ParkedWait() [2/3]
void v8::internal::ParkingConditionVariable::ParkedWait (LocalHeap * local_heap, base::Mutex * mutex) [inline]
Definition at line 67 of file parked-scope-inl.h.
                                                                      {
  local_heap->ExecuteWhileParked(
      [this, mutex](const ParkedScope& parked) { ParkedWait(parked, mutex); });
}
References v8::internal::LocalHeap::ExecuteWhileParked(), and ParkedWait().
ParkedWait() [3/3]
void v8::internal::ParkingConditionVariable::ParkedWait (LocalIsolate * local_isolate, base::Mutex * mutex) [inline]
Definition at line 62 of file parked-scope-inl.h.
                                                                      {
  ParkedWait(local_isolate->heap(), mutex);
}
References v8::internal::LocalIsolate::heap().
Referenced by ParkedWait().
ParkedWaitFor() [1/3]
bool v8::internal::ParkingConditionVariable::ParkedWaitFor (const ParkedScope & scope, base::Mutex * mutex, const base::TimeDelta & rel_time) [inline]
Definition at line 152 of file parked-scope.h.
                                                                          {
    USE(scope);
    return WaitFor(mutex, rel_time);
  }
References USE.
ParkedWaitFor() [2/3]
bool v8::internal::ParkingConditionVariable::ParkedWaitFor (LocalHeap * local_heap, base::Mutex * mutex, const base::TimeDelta & rel_time) [inline]
Definition at line 79 of file parked-scope-inl.h.
                                   {
  bool result;
  local_heap->ExecuteWhileParked(
      [this, mutex, rel_time, &result](const ParkedScope& parked) {
        result = ParkedWaitFor(parked, mutex, rel_time);
      });
  return result;
}
References v8::internal::LocalHeap::ExecuteWhileParked(), ParkedWaitFor(), and v8::base::internal::result.
ParkedWaitFor() [3/3]
bool v8::internal::ParkingConditionVariable::ParkedWaitFor (LocalIsolate * local_isolate, base::Mutex * mutex, const base::TimeDelta & rel_time) [inline]
Definition at line 73 of file parked-scope-inl.h.
                                   {
  return ParkedWaitFor(local_isolate->heap(), mutex, rel_time);
}
References v8::internal::LocalIsolate::heap().
Referenced by ParkedWaitFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/parked-scope.h
/mnt/V8SourceCode/src/heap/parked-scope-inl.h