v8::internal::HeapProfiler Class Reference
#include <heap-profiler.h>
Public Types
typedef void(* InternalBuildEmbedderGraphCallback) (v8::Isolate *isolate, v8::EmbedderGraph *graph, void *data, UnorderedCppHeapExternalObjectSet &&cpp_heap_external_objects)
Public Member Functions
HeapProfiler (Heap *heap)
~HeapProfiler () override
HeapProfiler (const HeapProfiler &)=delete
HeapProfiler & operator= (const HeapProfiler &)=delete
HeapSnapshot * TakeSnapshot (const v8::HeapProfiler::HeapSnapshotOptions options)
void WriteSnapshotToDiskAfterGC (HeapSnapshotMode snapshot_mode=HeapSnapshotMode::kRegular)
void TakeSnapshotToFile (const v8::HeapProfiler::HeapSnapshotOptions options, std::string filename)
V8_EXPORT_PRIVATE std::string TakeSnapshotToString (const v8::HeapProfiler::HeapSnapshotOptions options)
bool StartSamplingHeapProfiler (uint64_t sample_interval, int stack_depth, v8::HeapProfiler::SamplingFlags)
void StopSamplingHeapProfiler ()
bool is_sampling_allocations ()
AllocationProfile * GetAllocationProfile ()
void StartHeapObjectsTracking (bool track_allocations)
void StopHeapObjectsTracking ()
AllocationTracker * allocation_tracker () const
HeapObjectsMap * heap_object_map () const
StringsStorage * names () const
SnapshotObjectId PushHeapObjectsStats (OutputStream *stream, int64_t *timestamp_us)
int GetSnapshotsCount () const
bool IsTakingSnapshot () const
HeapSnapshot * GetSnapshot (int index)
SnapshotObjectId GetSnapshotObjectId (DirectHandle< Object > obj)
SnapshotObjectId GetSnapshotObjectId (NativeObject obj)
void DeleteAllSnapshots ()
void RemoveSnapshot (HeapSnapshot *snapshot)
std::vector< v8::Local< v8::Value > > GetDetachedJSWrapperObjects ()
void ObjectMoveEvent (Address from, Address to, int size, bool is_native_object)
void AllocationEvent (Address addr, int size) override
void UpdateObjectSizeEvent (Address addr, int size) override
void AddBuildEmbedderGraphCallback (v8::HeapProfiler::BuildEmbedderGraphCallback callback, void *data)
void RemoveBuildEmbedderGraphCallback (v8::HeapProfiler::BuildEmbedderGraphCallback callback, void *data)
void BuildEmbedderGraph (Isolate *isolate, v8::EmbedderGraph *graph, UnorderedCppHeapExternalObjectSet &&cpp_heap_external_objects)
bool HasBuildEmbedderGraphCallback ()
void SetInternalBuildEmbedderGraphCallback (InternalBuildEmbedderGraphCallback callback, void *data)
void SetGetDetachednessCallback (v8::HeapProfiler::GetDetachednessCallback callback, void *data)
bool HasGetDetachednessCallback () const
v8::EmbedderGraph::Node::Detachedness GetDetachedness (const v8::Local< v8::Value > v8_value, uint16_t class_id)
const char * CopyNameForHeapSnapshot (const char *name)
bool is_tracking_object_moves () const
DirectHandle< HeapObject > FindHeapObjectById (SnapshotObjectId id)
void ClearHeapObjectMap ()
Isolate * isolate () const
void QueryObjects (DirectHandle< Context > context, QueryObjectPredicate *predicate, std::vector< v8::Global< v8::Object >> *objects)
void set_native_move_listener (std::unique_ptr< HeapProfilerNativeMoveListener > listener)
Private Types
using HeapSnapshotMode = v8::HeapProfiler::HeapSnapshotMode
Private Member Functions
void MaybeClearStringsStorage ()
Heap * heap () const
Private Attributes
std::unique_ptr< HeapObjectsMap > ids_
std::vector< std::unique_ptr< HeapSnapshot > > snapshots_
std::unique_ptr< StringsStorage > names_
std::unique_ptr< AllocationTracker > allocation_tracker_
bool is_tracking_object_moves_
bool is_taking_snapshot_
base::Mutex profiler_mutex_
std::unique_ptr< SamplingHeapProfiler > sampling_heap_profiler_
std::vector< std::pair< v8::HeapProfiler::BuildEmbedderGraphCallback, void * > > build_embedder_graph_callbacks_
std::pair< InternalBuildEmbedderGraphCallback, void * > internal_build_embedder_graph_callback_
std::pair< v8::HeapProfiler::GetDetachednessCallback, void * > get_detachedness_callback_
std::unique_ptr< HeapProfilerNativeMoveListener > native_move_listener_
Detailed Description
Definition at line 55 of file heap-profiler.h.
Member Typedef Documentation
HeapSnapshotMode
using v8::internal::HeapProfiler::HeapSnapshotMode = v8::HeapProfiler::HeapSnapshotMode [private]
Definition at line 56 of file heap-profiler.h.
InternalBuildEmbedderGraphCallback
typedef void(* v8::internal::HeapProfiler::InternalBuildEmbedderGraphCallback) (v8::Isolate *isolate, v8::EmbedderGraph *graph, void *data, UnorderedCppHeapExternalObjectSet &&cpp_heap_external_objects)
Definition at line 124 of file heap-profiler.h.
Constructor & Destructor Documentation
HeapProfiler() [1/2]
v8::internal::HeapProfiler::HeapProfiler (Heap * heap) [explicit]
Definition at line 27 of file heap-profiler.cc.
    : ids_(new HeapObjectsMap(heap)),
      names_(new StringsStorage()),
      is_tracking_object_moves_(false),
      is_taking_snapshot_(false) {}
 HeapProfiler()
v8::internal::HeapProfiler::~HeapProfiler () [override], [default]
HeapProfiler() [2/2]
v8::internal::HeapProfiler::HeapProfiler (const HeapProfiler &) [delete]
Member Function Documentation
AddBuildEmbedderGraphCallback()
void v8::internal::HeapProfiler::AddBuildEmbedderGraphCallback (v8::HeapProfiler::BuildEmbedderGraphCallback callback, void * data)
Definition at line 82 of file heap-profiler.cc.
                                                                   {
  build_embedder_graph_callbacks_.push_back({callback, data});
}
References build_embedder_graph_callbacks_.
allocation_tracker()
AllocationTracker* v8::internal::HeapProfiler::allocation_tracker () const [inline]
Definition at line 84 of file heap-profiler.h.
                                                {
    return allocation_tracker_.get();
  }
References allocation_tracker_.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNodeInfos(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceTree().
AllocationEvent()
void v8::internal::HeapProfiler::AllocationEvent (Address addr, int size) [override], [virtual]
Implements v8::internal::HeapObjectAllocationTracker.
Definition at line 297 of file heap-profiler.cc.
                                                         {
  DisallowGarbageCollection no_gc;
  if (allocation_tracker_) {
    allocation_tracker_->AllocationEvent(addr, size);
  }
}
References allocation_tracker_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
BuildEmbedderGraph()
void v8::internal::HeapProfiler::BuildEmbedderGraph (Isolate * isolate, v8::EmbedderGraph * graph, UnorderedCppHeapExternalObjectSet && cpp_heap_external_objects)
Definition at line 96 of file heap-profiler.cc.
                                                                   {
  if (internal_build_embedder_graph_callback_.first) {
    internal_build_embedder_graph_callback_.first(
        reinterpret_cast<v8::Isolate*>(isolate), graph,
        internal_build_embedder_graph_callback_.second,
        std::move(cpp_heap_external_objects));
  }
  for (const auto& cb : build_embedder_graph_callbacks_) {
    cb.first(reinterpret_cast<v8::Isolate*>(isolate), graph, cb.second);
  }
}
References build_embedder_graph_callbacks_, graph(), internal_build_embedder_graph_callback_, and isolate().
Referenced by v8::internal::NativeObjectsExplorer::IterateAndExtractReferences().
ClearHeapObjectMap()
void v8::internal::HeapProfiler::ClearHeapObjectMap ()
Definition at line 320 of file heap-profiler.cc.
                                      {
  ids_.reset(new HeapObjectsMap(heap()));
  if (!allocation_tracker_) {
    if (native_move_listener_) {
      native_move_listener_->StopListening();
    }
    is_tracking_object_moves_ = false;
    heap()->isolate()->UpdateLogObjectRelocation();
  }
}
References allocation_tracker_, heap(), ids_, is_tracking_object_moves_, v8::internal::Heap::isolate(), native_move_listener_, and v8::internal::Isolate::UpdateLogObjectRelocation().
CopyNameForHeapSnapshot()
const char * v8::internal::HeapProfiler::CopyNameForHeapSnapshot (const char * name)
Definition at line 128 of file heap-profiler.cc.
                                                                  {
  CHECK(is_taking_snapshot_);
  return names_->GetCopy(name);
}
References CHECK, is_taking_snapshot_, v8::internal::name, and names_.
DeleteAllSnapshots()
void v8::internal::HeapProfiler::DeleteAllSnapshots ()
Definition at line 35 of file heap-profiler.cc.
                                      {
  snapshots_.clear();
  MaybeClearStringsStorage();
}
References MaybeClearStringsStorage(), and snapshots_.
Referenced by v8::HeapSnapshot::Delete().
FindHeapObjectById()
DirectHandle< HeapObject > v8::internal::HeapProfiler::FindHeapObjectById (SnapshotObjectId id)
Definition at line 308 of file heap-profiler.cc.
                                                                             {
  CombinedHeapObjectIterator iterator(heap(),
                                      HeapObjectIterator::kFilterUnreachable);
  // Make sure that the object with the given id is still reachable.
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (ids_->FindEntry(obj.address()) == id)
      return DirectHandle<HeapObject>(obj, isolate());
  }
  return DirectHandle<HeapObject>();
}
References heap(), ids_, v8::internal::Tagged< HeapObject >::is_null(), isolate(), v8::internal::HeapObjectIterator::kFilterUnreachable, and v8::internal::CombinedHeapObjectIterator::Next().
GetAllocationProfile()
v8::AllocationProfile * v8::internal::HeapProfiler::GetAllocationProfile ()
Definition at line 221 of file heap-profiler.cc.
                                                        {
  if (sampling_heap_profiler_) {
    return sampling_heap_profiler_->GetAllocationProfile();
  } else {
    return nullptr;
  }
}
References sampling_heap_profiler_.
GetDetachedJSWrapperObjects()
std::vector< v8::Local< v8::Value > > v8::internal::HeapProfiler::GetDetachedJSWrapperObjects ()
Definition at line 55 of file heap-profiler.cc.
                                                                      {
  heap()->CollectAllAvailableGarbage(GarbageCollectionReason::kHeapProfiler);
  std::vector<v8::Local<v8::Value>> js_objects_found;
  HeapObjectIterator iterator(heap());
  for (Tagged<HeapObject> obj = iterator.Next(); !obj.is_null();
       obj = iterator.Next()) {
    if (HeapLayout::InCodeSpace(obj)) continue;
    if (!IsJSApiWrapperObject(obj)) continue;
    // Ensure object is wrappable, otherwise GetDetachedness() can crash
    CppHeapObjectWrapper wrapper = CppHeapObjectWrapper(Cast<JSObject>(obj));
    if (!wrapper.GetCppHeapWrappable(isolate(), kAnyCppHeapPointer)) continue;
    v8::Local<v8::Value> data(
        Utils::ToLocal(direct_handle(Cast<JSObject>(obj), isolate())));
    v8::EmbedderGraph::Node::Detachedness detachedness =
        GetDetachedness(data, 0);
    if (detachedness != v8::EmbedderGraph::Node::Detachedness::kDetached)
      continue;
    js_objects_found.push_back(data);
  }
  return js_objects_found;
}
References v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::direct_handle(), v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable(), GetDetachedness(), heap(), v8::internal::HeapLayout::InCodeSpace(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::InstanceTypeChecker::IsJSApiWrapperObject(), isolate(), v8::kAnyCppHeapPointer(), v8::EmbedderGraph::Node::kDetached, v8::internal::kHeapProfiler, and v8::internal::HeapObjectIterator::Next().
GetDetachedness()
v8::EmbedderGraph::Node::Detachedness v8::internal::HeapProfiler::GetDetachedness (const v8::Local< v8::Value > v8_value, uint16_t class_id)
Definition at line 120 of file heap-profiler.cc.
                                                        {
  DCHECK(HasGetDetachednessCallback());
  return get_detachedness_callback_.first(
      reinterpret_cast<v8::Isolate*>(heap()->isolate()), v8_value, class_id,
      get_detachedness_callback_.second);
}
References v8::internal::DCHECK(), get_detachedness_callback_, HasGetDetachednessCallback(), heap(), and isolate().
Referenced by GetDetachedJSWrapperObjects().
GetSnapshot()
HeapSnapshot * v8::internal::HeapProfiler::GetSnapshot (int index)
Definition at line 263 of file heap-profiler.cc.
                                                 {
  return snapshots_.at(index).get();
}
References v8::internal::index, and snapshots_.
GetSnapshotObjectId() [1/2]
SnapshotObjectId v8::internal::HeapProfiler::GetSnapshotObjectId (DirectHandle< Object > obj)
Definition at line 267 of file heap-profiler.cc.
                                                                           {
  if (!IsHeapObject(*obj)) return v8::HeapProfiler::kUnknownObjectId;
  return ids_->FindEntry(Cast<HeapObject>(*obj).address());
}
References ids_, v8::internal::IsHeapObject(), and v8::HeapProfiler::kUnknownObjectId.
GetSnapshotObjectId() [2/2]
SnapshotObjectId v8::internal::HeapProfiler::GetSnapshotObjectId (NativeObject obj)
Definition at line 272 of file heap-profiler.cc.
                                                                   {
  // Try to find id of regular native node first.
  SnapshotObjectId id = ids_->FindEntry(reinterpret_cast<Address>(obj));
  // In case no id has been found, check whether there exists an entry where the
  // native objects has been merged into a V8 entry.
  if (id == v8::HeapProfiler::kUnknownObjectId) {
    id = ids_->FindMergedNativeEntry(obj);
  }
  return id;
}
References ids_, and v8::HeapProfiler::kUnknownObjectId.
GetSnapshotsCount()
int v8::internal::HeapProfiler::GetSnapshotsCount () const
Definition at line 257 of file heap-profiler.cc.
                                          {
  return static_cast<int>(snapshots_.size());
}
References snapshots_.
Referenced by v8::HeapSnapshot::Delete().
HasBuildEmbedderGraphCallback()
bool v8::internal::HeapProfiler::HasBuildEmbedderGraphCallback () [inline]
Definition at line 116 of file heap-profiler.h.
                                       {
    return internal_build_embedder_graph_callback_.first != nullptr ||
           !build_embedder_graph_callbacks_.empty();
  }
References build_embedder_graph_callbacks_, and internal_build_embedder_graph_callback_.
Referenced by v8::internal::NativeObjectsExplorer::IterateAndExtractReferences().
HasGetDetachednessCallback()
bool v8::internal::HeapProfiler::HasGetDetachednessCallback () const [inline]
Definition at line 132 of file heap-profiler.h.
                                          {
    return get_detachedness_callback_.first != nullptr;
  }
References get_detachedness_callback_.
Referenced by GetDetachedness().
heap()
Heap * v8::internal::HeapProfiler::heap () const [private]
Definition at line 331 of file heap-profiler.cc.
{ return ids_->heap(); }
References ids_.
Referenced by ClearHeapObjectMap(), FindHeapObjectById(), GetDetachedJSWrapperObjects(), GetDetachedness(), isolate(), QueryObjects(), v8::internal::RUNTIME_FUNCTION(), StartHeapObjectsTracking(), StartSamplingHeapProfiler(), StopHeapObjectsTracking(), TakeSnapshot(), and WriteSnapshotToDiskAfterGC().
heap_object_map()
HeapObjectsMap* v8::internal::HeapProfiler::heap_object_map () const [inline]
Definition at line 87 of file heap-profiler.h.
{ return ids_.get(); }
References ids_.
Referenced by v8::internal::HeapSnapshot::RememberLastJSObjectId(), and v8::internal::HeapSnapshotJSONSerializer::SerializeSamples().
is_sampling_allocations()
bool v8::internal::HeapProfiler::is_sampling_allocations () [inline]
Definition at line 79 of file heap-profiler.h.
{ return !!sampling_heap_profiler_; }
References sampling_heap_profiler_.
is_tracking_object_moves()
bool v8::internal::HeapProfiler::is_tracking_object_moves () const [inline]
Definition at line 140 of file heap-profiler.h.
{ return is_tracking_object_moves_; }
References is_tracking_object_moves_.
Referenced by set_native_move_listener(), and v8::internal::Isolate::UpdateLogObjectRelocation().
isolate()
Isolate * v8::internal::HeapProfiler::isolate () const
Definition at line 333 of file heap-profiler.cc.
{ return heap()->isolate(); }
References heap(), and v8::internal::Heap::isolate().
Referenced by BuildEmbedderGraph(), FindHeapObjectById(), GetDetachedJSWrapperObjects(), GetDetachedness(), v8::internal::HeapEntry::isolate(), QueryObjects(), and v8::HeapProfiler::QueryObjects().
IsTakingSnapshot()
bool v8::internal::HeapProfiler::IsTakingSnapshot () const
Definition at line 261 of file heap-profiler.cc.
{ return is_taking_snapshot_; }
References is_taking_snapshot_.
Referenced by v8::HeapSnapshot::Delete().
MaybeClearStringsStorage()
void v8::internal::HeapProfiler::MaybeClearStringsStorage () [private]
Definition at line 40 of file heap-profiler.cc.
                                            {
  if (snapshots_.empty() && !sampling_heap_profiler_ && !allocation_tracker_ &&
      !is_taking_snapshot_) {
    names_.reset(new StringsStorage());
  }
}
References allocation_tracker_, is_taking_snapshot_, names_, sampling_heap_profiler_, and snapshots_.
Referenced by DeleteAllSnapshots(), StopHeapObjectsTracking(), and StopSamplingHeapProfiler().
names()
StringsStorage* v8::internal::HeapProfiler::names () const [inline]
Definition at line 88 of file heap-profiler.h.
{ return names_.get(); }
References names_.
ObjectMoveEvent()
void v8::internal::HeapProfiler::ObjectMoveEvent (Address from, Address to, int size, bool is_native_object)
Definition at line 288 of file heap-profiler.cc.
                                                          {
  base::MutexGuard guard(&profiler_mutex_);
  bool known_object = ids_->MoveObject(from, to, size);
  if (!known_object && allocation_tracker_ && !is_native_object) {
    allocation_tracker_->address_to_trace()->MoveObject(from, to, size);
  }
}
References allocation_tracker_, ids_, profiler_mutex_, and size().
Referenced by v8::internal::HeapProfilerNativeMoveListener::ObjectMoveEvent(), and v8::internal::Heap::OnMoveEvent().
operator=()
HeapProfiler& v8::internal::HeapProfiler::operator= (const HeapProfiler &) [delete]
PushHeapObjectsStats()
SnapshotObjectId v8::internal::HeapProfiler::PushHeapObjectsStats (OutputStream * stream, int64_t * timestamp_us)
Definition at line 243 of file heap-profiler.cc.
                                                                           {
  return ids_->PushHeapObjectsStats(stream, timestamp_us);
}
References ids_.
Referenced by v8::HeapProfiler::GetHeapStats().
QueryObjects()
void v8::internal::HeapProfiler::QueryObjects (DirectHandle< Context > context, v8::QueryObjectPredicate * predicate, std::vector< v8::Global< v8::Object >> * objects)
Definition at line 335 of file heap-profiler.cc.
                                                                        {
  // We need a stack marker here to allow deterministic passes over the stack.
  // The garbage collection and the two object heap iterators should scan the
  // same part of the stack.
  heap()->stack().SetMarkerIfNeededAndCallback([this, predicate, objects]() {
    {
      HandleScope handle_scope(isolate());
      std::vector<Handle<JSTypedArray>> on_heap_typed_arrays;
      CombinedHeapObjectIterator heap_iterator(
          heap(), HeapObjectIterator::kFilterUnreachable);
      for (Tagged<HeapObject> heap_obj = heap_iterator.Next();
           !heap_obj.is_null(); heap_obj = heap_iterator.Next()) {
        if (IsFeedbackVector(heap_obj)) {
          Cast<FeedbackVector>(heap_obj)->ClearSlots(isolate());
        } else if (IsJSTypedArray(heap_obj) &&
                   Cast<JSTypedArray>(heap_obj)->is_on_heap()) {
          // Cannot call typed_array->GetBuffer() here directly because it may
          // trigger GC. Defer that call by collecting the object in a vector.
          on_heap_typed_arrays.push_back(
              handle(Cast<JSTypedArray>(heap_obj), isolate()));
        }
      }
      for (auto& typed_array : on_heap_typed_arrays) {
        // Convert the on-heap typed array into off-heap typed array, so that
        // its ArrayBuffer becomes valid and can be returned in the result.
        typed_array->GetBuffer(isolate());
      }
    }
    // We should return accurate information about live objects, so we need to
    // collect all garbage first.
    heap()->CollectAllAvailableGarbage(GarbageCollectionReason::kHeapProfiler);
    CombinedHeapObjectIterator heap_iterator(
        heap(), HeapObjectIterator::kFilterUnreachable);
    PtrComprCageBase cage_base(isolate());
    for (Tagged<HeapObject> heap_obj = heap_iterator.Next();
         !heap_obj.is_null(); heap_obj = heap_iterator.Next()) {
      if (!IsJSObject(heap_obj, cage_base) ||
          IsJSExternalObject(heap_obj, cage_base))
        continue;
      v8::Local<v8::Object> v8_obj(
          Utils::ToLocal(direct_handle(Cast<JSObject>(heap_obj), isolate())));
      if (!predicate->Filter(v8_obj)) continue;
      objects->emplace_back(reinterpret_cast<v8::Isolate*>(isolate()), v8_obj);
    }
  });
}
References v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::direct_handle(), v8::QueryObjectPredicate::Filter(), v8::internal::handle(), heap(), v8::internal::Tagged< HeapObject >::is_null(), isolate(), v8::internal::HeapObjectIterator::kFilterUnreachable, v8::internal::kHeapProfiler, v8::internal::CombinedHeapObjectIterator::Next(), heap::base::Stack::SetMarkerIfNeededAndCallback(), and v8::internal::Heap::stack().
Referenced by v8::HeapProfiler::QueryObjects().
RemoveBuildEmbedderGraphCallback()
void v8::internal::HeapProfiler::RemoveBuildEmbedderGraphCallback (v8::HeapProfiler::BuildEmbedderGraphCallback callback, void * data)
Definition at line 87 of file heap-profiler.cc.
                                                                   {
  auto it = std::find(build_embedder_graph_callbacks_.begin(),
                      build_embedder_graph_callbacks_.end(),
                      std::make_pair(callback, data));
  if (it != build_embedder_graph_callbacks_.end())
    build_embedder_graph_callbacks_.erase(it);
}
References build_embedder_graph_callbacks_.
RemoveSnapshot()
void v8::internal::HeapProfiler::RemoveSnapshot (HeapSnapshot * snapshot)
Definition at line 47 of file heap-profiler.cc.
                                                        {
  snapshots_.erase(
      std::find_if(snapshots_.begin(), snapshots_.end(),
                   [&](const std::unique_ptr<HeapSnapshot>& entry) {
                     return entry.get() == snapshot;
                   }));
}
References snapshots_.
Referenced by v8::internal::HeapSnapshot::Delete().
set_native_move_listener()
void v8::internal::HeapProfiler::set_native_move_listener (std::unique_ptr< HeapProfilerNativeMoveListener > listener) [inline]
Definition at line 150 of file heap-profiler.h.
                                                              {
    native_move_listener_ = std::move(listener);
    if (is_tracking_object_moves() && native_move_listener_) {
      native_move_listener_->StartListening();
    }
  }
References is_tracking_object_moves(), and native_move_listener_.
SetGetDetachednessCallback()
void v8::internal::HeapProfiler::SetGetDetachednessCallback (v8::HeapProfiler::GetDetachednessCallback callback, void * data)
Definition at line 115 of file heap-profiler.cc.
                                                                {
  get_detachedness_callback_ = {callback, data};
}
References get_detachedness_callback_.
SetInternalBuildEmbedderGraphCallback()
void v8::internal::HeapProfiler::SetInternalBuildEmbedderGraphCallback (InternalBuildEmbedderGraphCallback callback, void * data)
Definition at line 110 of file heap-profiler.cc.
                                                             {
  internal_build_embedder_graph_callback_ = {callback, data};
}
References internal_build_embedder_graph_callback_.
StartHeapObjectsTracking()
void v8::internal::HeapProfiler::StartHeapObjectsTracking (bool track_allocations)
Definition at line 229 of file heap-profiler.cc.
                                                                  {
  ids_->UpdateHeapObjectsMap();
  if (native_move_listener_) {
    native_move_listener_->StartListening();
  }
  is_tracking_object_moves_ = true;
  heap()->isolate()->UpdateLogObjectRelocation();
  DCHECK(!allocation_tracker_);
  if (track_allocations) {
    allocation_tracker_.reset(new AllocationTracker(ids_.get(), names_.get()));
    heap()->AddHeapObjectAllocationTracker(this);
  }
}
References v8::internal::Heap::AddHeapObjectAllocationTracker(), allocation_tracker_, v8::internal::DCHECK(), heap(), ids_, is_tracking_object_moves_, v8::internal::Heap::isolate(), names_, native_move_listener_, and v8::internal::Isolate::UpdateLogObjectRelocation().
StartSamplingHeapProfiler()
bool v8::internal::HeapProfiler::StartSamplingHeapProfiler (uint64_t sample_interval, int stack_depth, v8::HeapProfiler::SamplingFlags flags)
Definition at line 207 of file heap-profiler.cc.
                                       {
  if (sampling_heap_profiler_) return false;
  sampling_heap_profiler_.reset(new SamplingHeapProfiler(
      heap(), names_.get(), sample_interval, stack_depth, flags));
  return true;
}
References v8::internal::flags, heap(), names_, and sampling_heap_profiler_.
Referenced by v8::internal::Isolate::Init().
StopHeapObjectsTracking()
void v8::internal::HeapProfiler::StopHeapObjectsTracking ()
Definition at line 248 of file heap-profiler.cc.
                                           {
  ids_->StopHeapObjectsTracking();
  if (allocation_tracker_) {
    allocation_tracker_.reset();
    MaybeClearStringsStorage();
    heap()->RemoveHeapObjectAllocationTracker(this);
  }
}
References allocation_tracker_, heap(), ids_, MaybeClearStringsStorage(), and v8::internal::Heap::RemoveHeapObjectAllocationTracker().
StopSamplingHeapProfiler()
void v8::internal::HeapProfiler::StopSamplingHeapProfiler ()
Definition at line 216 of file heap-profiler.cc.
                                            {
  sampling_heap_profiler_.reset();
  MaybeClearStringsStorage();
}
References MaybeClearStringsStorage(), and sampling_heap_profiler_.
Referenced by v8::internal::Isolate::Deinit().
TakeSnapshot()
HeapSnapshot * v8::internal::HeapProfiler::TakeSnapshot (const v8::HeapProfiler::HeapSnapshotOptions options)
Definition at line 133 of file heap-profiler.cc.
                                                     {
  is_taking_snapshot_ = true;
  HeapSnapshot* result =
      new HeapSnapshot(this, options.snapshot_mode, options.numerics_mode);
  // We need a stack marker here to allow deterministic passes over the stack.
  // The garbage collection and the filling of references in GenerateSnapshot
  // should scan the same part of the stack.
  heap()->stack().SetMarkerIfNeededAndCallback([this, &options, &result]() {
    std::optional<CppClassNamesAsHeapObjectNameScope> use_cpp_class_name;
    if (result->expose_internals() && heap()->cpp_heap()) {
      use_cpp_class_name.emplace(heap()->cpp_heap());
    }
    HeapSnapshotGenerator generator(result, options.control,
                                    options.global_object_name_resolver, heap(),
                                    options.stack_state);
    if (!generator.GenerateSnapshot()) {
      delete result;
      result = nullptr;
    } else {
      snapshots_.emplace_back(result);
    }
  });
  ids_->RemoveDeadEntries();
  if (native_move_listener_) {
    native_move_listener_->StartListening();
  }
  is_tracking_object_moves_ = true;
  heap()->isolate()->UpdateLogObjectRelocation();
  is_taking_snapshot_ = false;
  return result;
}
References v8::HeapProfiler::HeapSnapshotOptions::control, v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::HeapProfiler::HeapSnapshotOptions::global_object_name_resolver, heap(), ids_, is_taking_snapshot_, is_tracking_object_moves_, v8::internal::Heap::isolate(), native_move_listener_, v8::HeapProfiler::HeapSnapshotOptions::numerics_mode, v8::base::internal::result, heap::base::Stack::SetMarkerIfNeededAndCallback(), v8::HeapProfiler::HeapSnapshotOptions::snapshot_mode, snapshots_, v8::internal::Heap::stack(), v8::HeapProfiler::HeapSnapshotOptions::stack_state, and v8::internal::Isolate::UpdateLogObjectRelocation().
Referenced by TakeSnapshotToFile(), and TakeSnapshotToString().
TakeSnapshotToFile()
void v8::internal::HeapProfiler::TakeSnapshotToFile (const v8::HeapProfiler::HeapSnapshotOptions options, std::string filename)
Definition at line 190 of file heap-profiler.cc.
                                                                         {
  HeapSnapshot* snapshot = TakeSnapshot(options);
  FileOutputStream stream(filename.c_str());
  HeapSnapshotJSONSerializer serializer(snapshot);
  serializer.Serialize(&stream);
}
References v8::internal::HeapSnapshotJSONSerializer::Serialize(), and TakeSnapshot().
Referenced by v8::internal::anonymous_namespace{gc-extension.cc}::InvokeGC(), and v8::internal::RUNTIME_FUNCTION().
TakeSnapshotToString()
std::string v8::internal::HeapProfiler::TakeSnapshotToString (const v8::HeapProfiler::HeapSnapshotOptions options)
Definition at line 198 of file heap-profiler.cc.
                                                     {
  HeapSnapshot* snapshot = TakeSnapshot(options);
  StringOutputStream stream;
  HeapSnapshotJSONSerializer serializer(snapshot);
  serializer.Serialize(&stream);
  return stream.str();
}
References v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::StringOutputStream::str(), and TakeSnapshot().
UpdateObjectSizeEvent()
void v8::internal::HeapProfiler::UpdateObjectSizeEvent (Address addr, int size) [override], [virtual]
Reimplemented from v8::internal::HeapObjectAllocationTracker.
Definition at line 304 of file heap-profiler.cc.
                                                               {
  ids_->UpdateObjectSize(addr, size);
}
References ids_, and size().
WriteSnapshotToDiskAfterGC()
void v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC (HeapSnapshotMode snapshot_mode = HeapSnapshotMode::kRegular)
Definition at line 170 of file heap-profiler.cc.
                                                                            {
  // We need to set a stack marker for the stack walk performed by the
  // snapshot generator to work.
  heap()->stack().SetMarkerIfNeededAndCallback([this, snapshot_mode]() {
    int64_t time = V8::GetCurrentPlatform()->CurrentClockTimeMilliseconds();
    std::string filename = "v8-heap-" + std::to_string(time) + ".heapsnapshot";
    v8::HeapProfiler::HeapSnapshotOptions options;
    std::unique_ptr<HeapSnapshot> result(
        new HeapSnapshot(this, snapshot_mode, options.numerics_mode));
    HeapSnapshotGenerator generator(result.get(), options.control,
                                    options.global_object_name_resolver, heap(),
                                    options.stack_state);
    if (!generator.GenerateSnapshotAfterGC()) return;
    i::FileOutputStream stream(filename.c_str());
    HeapSnapshotJSONSerializer serializer(result.get());
    serializer.Serialize(&stream);
    PrintF("Wrote heap snapshot to %s.\n", filename.c_str());
  });
}
References v8::HeapProfiler::HeapSnapshotOptions::control, v8::Platform::CurrentClockTimeMilliseconds(), v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC(), v8::internal::V8::GetCurrentPlatform(), v8::HeapProfiler::HeapSnapshotOptions::global_object_name_resolver, heap(), v8::HeapProfiler::HeapSnapshotOptions::numerics_mode, v8::internal::PrintF(), v8::base::internal::result, v8::internal::HeapSnapshotJSONSerializer::Serialize(), heap::base::Stack::SetMarkerIfNeededAndCallback(), v8::internal::Heap::stack(), v8::HeapProfiler::HeapSnapshotOptions::stack_state, v8::internal::string, and v8::internal::time.
Referenced by v8::internal::Heap::CheckHeapLimitReached(), v8::internal::Heap::CheckIneffectiveMarkCompact(), v8::internal::Heap::CollectAllAvailableGarbage(), and v8::internal::Heap::CollectGarbage().
Member Data Documentation
allocation_tracker_
std::unique_ptr<AllocationTracker> v8::internal::HeapProfiler::allocation_tracker_ [private]
Definition at line 167 of file heap-profiler.h.
Referenced by allocation_tracker(), AllocationEvent(), ClearHeapObjectMap(), MaybeClearStringsStorage(), ObjectMoveEvent(), StartHeapObjectsTracking(), and StopHeapObjectsTracking().
build_embedder_graph_callbacks_
std::vector<std::pair<v8::HeapProfiler::BuildEmbedderGraphCallback, void*> > v8::internal::HeapProfiler::build_embedder_graph_callbacks_ [private]
Definition at line 173 of file heap-profiler.h.
Referenced by AddBuildEmbedderGraphCallback(), BuildEmbedderGraph(), HasBuildEmbedderGraphCallback(), and RemoveBuildEmbedderGraphCallback().
get_detachedness_callback_
std::pair<v8::HeapProfiler::GetDetachednessCallback, void*> v8::internal::HeapProfiler::get_detachedness_callback_ [private]
Definition at line 177 of file heap-profiler.h.
Referenced by GetDetachedness(), HasGetDetachednessCallback(), and SetGetDetachednessCallback().
ids_
std::unique_ptr<HeapObjectsMap> v8::internal::HeapProfiler::ids_ [private]
Definition at line 164 of file heap-profiler.h.
Referenced by ClearHeapObjectMap(), FindHeapObjectById(), GetSnapshotObjectId(), heap(), heap_object_map(), ObjectMoveEvent(), PushHeapObjectsStats(), StartHeapObjectsTracking(), StopHeapObjectsTracking(), TakeSnapshot(), and UpdateObjectSizeEvent().
internal_build_embedder_graph_callback_
std::pair<InternalBuildEmbedderGraphCallback, void*> v8::internal::HeapProfiler::internal_build_embedder_graph_callback_ [private]
Definition at line 175 of file heap-profiler.h.
Referenced by BuildEmbedderGraph(), HasBuildEmbedderGraphCallback(), and SetInternalBuildEmbedderGraphCallback().
is_taking_snapshot_
bool v8::internal::HeapProfiler::is_taking_snapshot_ [private]
Definition at line 169 of file heap-profiler.h.
Referenced by CopyNameForHeapSnapshot(), IsTakingSnapshot(), MaybeClearStringsStorage(), and TakeSnapshot().
is_tracking_object_moves_
bool v8::internal::HeapProfiler::is_tracking_object_moves_ [private]
Definition at line 168 of file heap-profiler.h.
Referenced by ClearHeapObjectMap(), is_tracking_object_moves(), StartHeapObjectsTracking(), and TakeSnapshot().
names_
std::unique_ptr<StringsStorage> v8::internal::HeapProfiler::names_ [private]
Definition at line 166 of file heap-profiler.h.
Referenced by CopyNameForHeapSnapshot(), MaybeClearStringsStorage(), names(), StartHeapObjectsTracking(), and StartSamplingHeapProfiler().
native_move_listener_
std::unique_ptr<HeapProfilerNativeMoveListener> v8::internal::HeapProfiler::native_move_listener_ [private]
Definition at line 178 of file heap-profiler.h.
Referenced by ClearHeapObjectMap(), set_native_move_listener(), StartHeapObjectsTracking(), and TakeSnapshot().
profiler_mutex_
base::Mutex v8::internal::HeapProfiler::profiler_mutex_ [private]
Definition at line 170 of file heap-profiler.h.
Referenced by ObjectMoveEvent().
sampling_heap_profiler_
std::unique_ptr<SamplingHeapProfiler> v8::internal::HeapProfiler::sampling_heap_profiler_ [private]
Definition at line 171 of file heap-profiler.h.
Referenced by GetAllocationProfile(), is_sampling_allocations(), MaybeClearStringsStorage(), StartSamplingHeapProfiler(), and StopSamplingHeapProfiler().
snapshots_
std::vector<std::unique_ptr<HeapSnapshot> > v8::internal::HeapProfiler::snapshots_ [private]
Definition at line 165 of file heap-profiler.h.
Referenced by DeleteAllSnapshots(), GetSnapshot(), GetSnapshotsCount(), MaybeClearStringsStorage(), RemoveSnapshot(), and TakeSnapshot().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-profiler.h
/mnt/V8SourceCode/src/profiler/heap-profiler.cc