v8::internal::GCExtension Class Reference
#include <gc-extension.h>
Public Member Functions
GCExtension (const char *fun_name)
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Public Member Functions
static void GC (const v8::FunctionCallbackInfo< v8::Value > &info)
Static Private Member Functions
static const char * BuildSource (char *buf, size_t size, const char *fun_name)
Private Attributes
char buffer_ [50]
Detailed Description
Definition at line 53 of file gc-extension.h.
Constructor & Destructor Documentation
GCExtension()
v8::internal::GCExtension::GCExtension (const char * fun_name) [inline], [explicit]
Definition at line 55 of file gc-extension.h.
      : v8::Extension("v8/gc",
                      BuildSource(buffer_, sizeof(buffer_), fun_name)) {}
Member Function Documentation
BuildSource()
static const char* v8::internal::GCExtension::BuildSource (char * buf, size_t size, const char * fun_name) [inline], [static], [private]
Definition at line 63 of file gc-extension.h.
                                                                               {
    base::SNPrintF(base::VectorOf(buf, size), "native function %s();",
                   fun_name);
    return buf;
  }
References size(), v8::base::SNPrintF(), and v8::base::VectorOf().
GC()
void v8::internal::GCExtension::GC (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 270 of file gc-extension.cc.
                                                                {
  DCHECK(ValidateCallbackInfo(info));
  v8::Isolate* isolate = info.GetIsolate();
  // Immediate bailout if no arguments are provided.
  if (info.Length() == 0) {
    InvokeGC(isolate, GCOptions::GetDefault());
    return;
  }
  GCOptions options;
  if (!Parse(isolate, info).To(&options)) {
    // Parsing ran into an exception. Just bail out without GC in this case.
    return;
  }
  switch (options.execution) {
    case ExecutionType::kSync:
      InvokeGC(isolate, options);
      break;
    case ExecutionType::kAsync: {
      v8::HandleScope scope(isolate);
      auto resolver = v8::Promise::Resolver::New(isolate->GetCurrentContext())
                          .ToLocalChecked();
      info.GetReturnValue().Set(resolver->GetPromise());
      auto task_runner =
          V8::GetCurrentPlatform()->GetForegroundTaskRunner(isolate);
      CHECK(task_runner->NonNestableTasksEnabled());
      task_runner->PostNonNestableTask(
          std::make_unique<AsyncGC>(isolate, resolver, options));
    } break;
  }
}
References CHECK, v8::internal::DCHECK(), v8::Isolate::GetCurrentContext(), v8::internal::V8::GetCurrentPlatform(), v8::Platform::GetForegroundTaskRunner(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::anonymous_namespace{gc-extension.cc}::InvokeGC(), v8::FunctionCallbackInfo< T >::Length(), v8::Promise::Resolver::New(), v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), and v8::internal::ValidateCallbackInfo().
Referenced by GetNativeFunctionTemplate().
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::GCExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 265 of file gc-extension.cc.
                                               {
  return v8::FunctionTemplate::New(isolate, GCExtension::GC);
}
References GC(), and v8::FunctionTemplate::New().
Member Data Documentation
buffer_
char v8::internal::GCExtension::buffer_[50] [private]
Definition at line 69 of file gc-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/gc-extension.h
/mnt/V8SourceCode/src/extensions/gc-extension.cc