v8::internal::torque::Rule Class Reference
#include <earley-parser.h>
Public Member Functions
Rule (std::vector< Symbol * > right_hand_side, Action action=DefaultAction)
Symbol * left () const
const std::vector< Symbol * > & right () const
void SetLeftHandSide (Symbol *left_hand_side)
V8_EXPORT_PRIVATE std::optional< ParseResult > RunAction (const Item *completed_item, const LexerResult &tokens) const
Private Attributes
Symbol * left_hand_side_ = nullptr
std::vector< Symbol * > right_hand_side_
Action action_
Detailed Description
Definition at line 213 of file earley-parser.h.
Constructor & Destructor Documentation
Rule()
v8::internal::torque::Rule::Rule (std::vector< Symbol * > right_hand_side, Action action = DefaultAction) [inline], [explicit]
Definition at line 215 of file earley-parser.h.
      : right_hand_side_(std::move(right_hand_side)), action_(action) {}
Member Function Documentation
left()
Symbol* v8::internal::torque::Rule::left () const [inline]
Definition at line 219 of file earley-parser.h.
                       {
    DCHECK_NOT_NULL(left_hand_side_);
    return left_hand_side_;
  }
References DCHECK_NOT_NULL, and left_hand_side_.
Referenced by v8::internal::torque::Item::left().
right()
const std::vector<Symbol*>& v8::internal::torque::Rule::right () const [inline]
Definition at line 223 of file earley-parser.h.
{ return right_hand_side_; }
References right_hand_side_.
Referenced by v8::internal::torque::Item::right(), and v8::internal::torque::RunEarleyAlgorithm().
RunAction()
std::optional< ParseResult > v8::internal::torque::Rule::RunAction (const Item * completed_item, const LexerResult & tokens) const
Definition at line 45 of file earley-parser.cc.
                                                                            {
  std::vector<ParseResult> results;
  for (const Item* child : completed_item->Children()) {
    if (!child) continue;
    std::optional<ParseResult> child_result =
        child->left()->RunAction(child, tokens);
    if (child_result) results.push_back(std::move(*child_result));
  }
  MatchedInput matched_input = completed_item->GetMatchedInput(tokens);
  CurrentSourcePosition::Scope pos_scope(matched_input.pos);
  ParseResultIterator iterator(std::move(results), matched_input);
  auto result = action_(&iterator);
  // Make sure the parse action consumed all the child results.
  CHECK(!iterator.HasNext());
  return result;
}
References action_, CHECK, v8::internal::torque::Item::Children(), v8::internal::torque::Item::GetMatchedInput(), v8::internal::torque::ParseResultIterator::HasNext(), v8::internal::torque::MatchedInput::pos, and v8::base::internal::result.
Referenced by v8::internal::torque::Symbol::RunAction().
SetLeftHandSide()
void v8::internal::torque::Rule::SetLeftHandSide (Symbol * left_hand_side) [inline]
Definition at line 225 of file earley-parser.h.
                                               {
    DCHECK_NULL(left_hand_side_);
    left_hand_side_ = left_hand_side;
  }
References DCHECK_NULL, and left_hand_side_.
Member Data Documentation
action_
Action v8::internal::torque::Rule::action_ [private]
Definition at line 236 of file earley-parser.h.
Referenced by RunAction().
left_hand_side_
Symbol* v8::internal::torque::Rule::left_hand_side_ = nullptr [private]
Definition at line 234 of file earley-parser.h.
Referenced by left(), and SetLeftHandSide().
right_hand_side_
std::vector<Symbol*> v8::internal::torque::Rule::right_hand_side_ [private]
Definition at line 235 of file earley-parser.h.
Referenced by right().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/earley-parser.h
/mnt/V8SourceCode/src/torque/earley-parser.cc