v8::internal::maglev::CallArguments Class Reference
Public Types
enum Mode { kDefault
, kWithSpread
, kWithArrayLike
 }
Public Member Functions
CallArguments (ConvertReceiverMode receiver_mode, interpreter::RegisterList reglist, const InterpreterFrameState &frame, Mode mode=kDefault)
CallArguments (ConvertReceiverMode receiver_mode)
CallArguments (ConvertReceiverMode receiver_mode, std::initializer_list< ValueNode * > args, Mode mode=kDefault)
CallArguments (ConvertReceiverMode receiver_mode, base::SmallVector< ValueNode *, 8 > &&args, Mode mode=kDefault)
ValueNode * receiver () const
void set_receiver (ValueNode *receiver)
ValueNode * array_like_argument ()
size_t count () const
size_t count_with_receiver () const
ValueNode * operator[] (size_t i) const
void set_arg (size_t i, ValueNode *node)
Mode mode () const
ConvertReceiverMode receiver_mode () const
void PopArrayLikeArgument ()
void PopReceiver (ConvertReceiverMode new_receiver_mode)
Private Member Functions
void CheckArgumentsAreNotConversionNodes ()
Private Attributes
ConvertReceiverMode receiver_mode_
base::SmallVector< ValueNode *, 8 > args_
Mode mode_
Detailed Description
Definition at line 187 of file maglev-graph-builder.cc.
Member Enumeration Documentation
Mode
enum v8::internal::maglev::CallArguments::Mode
Enumerator
kDefault
kWithSpread
kWithArrayLike
Definition at line 189 of file maglev-graph-builder.cc.
            {
    kDefault,
    kWithSpread,
    kWithArrayLike,
  };
Constructor & Destructor Documentation
CallArguments() [1/4]
v8::internal::maglev::CallArguments::CallArguments (ConvertReceiverMode receiver_mode, interpreter::RegisterList reglist, const InterpreterFrameState & frame, Mode mode = kDefault) [inline]
Definition at line 195 of file maglev-graph-builder.cc.
      : receiver_mode_(receiver_mode),
        args_(reglist.register_count()),
        mode_(mode) {
    for (int i = 0; i < reglist.register_count(); i++) {
      args_[i] = frame.get(reglist[i]);
    }
    DCHECK_IMPLIES(args_.size() == 0,
                   receiver_mode == ConvertReceiverMode::kNullOrUndefined);
    DCHECK_IMPLIES(mode != kDefault,
                   receiver_mode == ConvertReceiverMode::kAny);
    DCHECK_IMPLIES(mode == kWithArrayLike, args_.size() == 2);
  }
References args_, DCHECK_IMPLIES, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kAny, kDefault, v8::internal::kNullOrUndefined, kWithArrayLike, mode(), receiver_mode(), and v8::internal::interpreter::RegisterList::register_count().
CallArguments() [2/4]
v8::internal::maglev::CallArguments::CallArguments (ConvertReceiverMode receiver_mode) [inline], [explicit]
Definition at line 211 of file maglev-graph-builder.cc.
      : receiver_mode_(receiver_mode), args_(), mode_(kDefault) {
    DCHECK_EQ(receiver_mode, ConvertReceiverMode::kNullOrUndefined);
  }
References DCHECK_EQ, v8::internal::kNullOrUndefined, and receiver_mode().
CallArguments() [3/4]
v8::internal::maglev::CallArguments::CallArguments (ConvertReceiverMode receiver_mode, std::initializer_list< ValueNode * > args, Mode mode = kDefault) [inline]
Definition at line 216 of file maglev-graph-builder.cc.
      : receiver_mode_(receiver_mode), args_(args), mode_(mode) {
    DCHECK_IMPLIES(mode != kDefault,
                   receiver_mode == ConvertReceiverMode::kAny);
    DCHECK_IMPLIES(mode == kWithArrayLike, args_.size() == 2);
    CheckArgumentsAreNotConversionNodes();
  }
References args_, CheckArgumentsAreNotConversionNodes(), DCHECK_IMPLIES, v8::internal::kAny, kDefault, kWithArrayLike, mode(), and receiver_mode().
CallArguments() [4/4]
v8::internal::maglev::CallArguments::CallArguments (ConvertReceiverMode receiver_mode, base::SmallVector< ValueNode *, 8 > && args, Mode mode = kDefault) [inline]
Definition at line 225 of file maglev-graph-builder.cc.
      : receiver_mode_(receiver_mode), args_(std::move(args)), mode_(mode) {
    DCHECK_IMPLIES(mode != kDefault,
                   receiver_mode == ConvertReceiverMode::kAny);
    DCHECK_IMPLIES(mode == kWithArrayLike, args_.size() == 2);
    CheckArgumentsAreNotConversionNodes();
  }
References args_, CheckArgumentsAreNotConversionNodes(), DCHECK_IMPLIES, v8::internal::kAny, kDefault, kWithArrayLike, mode(), and receiver_mode().
Member Function Documentation
array_like_argument()
ValueNode* v8::internal::maglev::CallArguments::array_like_argument () [inline]
Definition at line 251 of file maglev-graph-builder.cc.
                                   {
    DCHECK_EQ(mode_, kWithArrayLike);
    DCHECK_GT(count(), 0);
    return args_[args_.size() - 1];
  }
References args_, count(), DCHECK_EQ, DCHECK_GT, kWithArrayLike, and mode_.
CheckArgumentsAreNotConversionNodes()
void v8::internal::maglev::CallArguments::CheckArgumentsAreNotConversionNodes () [inline], [private]
Definition at line 314 of file maglev-graph-builder.cc.
                                             {
#ifdef DEBUG
    // Arguments can leak to the interpreter frame if the call is inlined,
    // conversions should be stored in known_node_aspects/NodeInfo.
    for (ValueNode* arg : args_) {
      DCHECK(!arg->properties().is_conversion());
    }
#endif // DEBUG
  }
References args_, and v8::internal::DCHECK().
Referenced by CallArguments().
count()
size_t v8::internal::maglev::CallArguments::count () const [inline]
Definition at line 257 of file maglev-graph-builder.cc.
                       {
    if (receiver_mode_ == ConvertReceiverMode::kNullOrUndefined) {
      return args_.size();
    }
    return args_.size() - 1;
  }
References args_, v8::internal::kNullOrUndefined, and receiver_mode_.
Referenced by array_like_argument(), count_with_receiver(), and PopArrayLikeArgument().
count_with_receiver()
size_t v8::internal::maglev::CallArguments::count_with_receiver () const [inline]
Definition at line 264 of file maglev-graph-builder.cc.
{ return count() + 1; }
References count().
mode()
Mode v8::internal::maglev::CallArguments::mode () const [inline]
Definition at line 283 of file maglev-graph-builder.cc.
{ return mode_; }
References mode_.
Referenced by CallArguments().
operator[]()
ValueNode* v8::internal::maglev::CallArguments::operator[] (size_t i) const [inline]
Definition at line 266 of file maglev-graph-builder.cc.
                                        {
    if (receiver_mode_ != ConvertReceiverMode::kNullOrUndefined) {
      i++;
    }
    if (i >= args_.size()) return nullptr;
    return args_[i];
  }
References args_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNullOrUndefined, and receiver_mode_.
PopArrayLikeArgument()
void v8::internal::maglev::CallArguments::PopArrayLikeArgument () [inline]
Definition at line 287 of file maglev-graph-builder.cc.
                              {
    DCHECK_EQ(mode_, kWithArrayLike);
    DCHECK_GT(count(), 0);
    args_.pop_back();
  }
References args_, count(), DCHECK_EQ, DCHECK_GT, kWithArrayLike, and mode_.
PopReceiver()
void v8::internal::maglev::CallArguments::PopReceiver (ConvertReceiverMode new_receiver_mode) [inline]
Definition at line 293 of file maglev-graph-builder.cc.
                                                          {
    DCHECK_NE(receiver_mode_, ConvertReceiverMode::kNullOrUndefined);
    DCHECK_NE(new_receiver_mode, ConvertReceiverMode::kNullOrUndefined);
    DCHECK_GT(args_.size(), 0); // We have at least a receiver to pop!
    // TODO(victorgomes): Do this better!
    for (size_t i = 0; i < args_.size() - 1; i++) {
      args_[i] = args_[i + 1];
    }
    args_.pop_back();
    // If there is no non-receiver argument to become the new receiver,
    // consider the new receiver to be known undefined.
    receiver_mode_ = args_.empty() ? ConvertReceiverMode::kNullOrUndefined
                                   : new_receiver_mode;
  }
References args_, DCHECK_GT, DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNullOrUndefined, and receiver_mode_.
receiver()
ValueNode* v8::internal::maglev::CallArguments::receiver () const [inline]
Definition at line 234 of file maglev-graph-builder.cc.
                              {
    if (receiver_mode_ == ConvertReceiverMode::kNullOrUndefined) {
      return nullptr;
    }
    return args_[0];
  }
References args_, v8::internal::kNullOrUndefined, and receiver_mode_.
Referenced by set_receiver().
receiver_mode()
ConvertReceiverMode v8::internal::maglev::CallArguments::receiver_mode () const [inline]
Definition at line 285 of file maglev-graph-builder.cc.
{ return receiver_mode_; }
References receiver_mode_.
Referenced by CallArguments().
set_arg()
void v8::internal::maglev::CallArguments::set_arg (size_t i, ValueNode * node) [inline]
Definition at line 274 of file maglev-graph-builder.cc.
                                          {
    if (receiver_mode_ != ConvertReceiverMode::kNullOrUndefined) {
      i++;
    }
    DCHECK_LT(i, args_.size());
    DCHECK(!node->properties().is_conversion());
    args_[i] = node;
  }
References args_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::OpProperties::is_conversion(), v8::internal::kNullOrUndefined, v8::internal::maglev::NodeBase::properties(), and receiver_mode_.
set_receiver()
void v8::internal::maglev::CallArguments::set_receiver (ValueNode * receiver) [inline]
Definition at line 241 of file maglev-graph-builder.cc.
                                         {
    if (receiver_mode_ == ConvertReceiverMode::kNullOrUndefined) {
      args_.insert(args_.data(), receiver);
      receiver_mode_ = ConvertReceiverMode::kAny;
    } else {
      DCHECK(!receiver->properties().is_conversion());
      args_[0] = receiver;
    }
  }
References args_, v8::internal::DCHECK(), v8::internal::maglev::OpProperties::is_conversion(), v8::internal::kAny, v8::internal::kNullOrUndefined, v8::internal::maglev::NodeBase::properties(), receiver(), and receiver_mode_.
Member Data Documentation
args_
base::SmallVector<ValueNode*, 8> v8::internal::maglev::CallArguments::args_ [private]
Definition at line 311 of file maglev-graph-builder.cc.
Referenced by array_like_argument(), CallArguments(), CheckArgumentsAreNotConversionNodes(), count(), operator[](), PopArrayLikeArgument(), PopReceiver(), receiver(), set_arg(), and set_receiver().
mode_
Mode v8::internal::maglev::CallArguments::mode_ [private]
Definition at line 312 of file maglev-graph-builder.cc.
Referenced by array_like_argument(), mode(), and PopArrayLikeArgument().
receiver_mode_
ConvertReceiverMode v8::internal::maglev::CallArguments::receiver_mode_ [private]
Definition at line 310 of file maglev-graph-builder.cc.
Referenced by count(), operator[](), PopReceiver(), receiver(), receiver_mode(), set_arg(), and set_receiver().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc