v8::base::internal::RangeCheck Class Reference
#include <safe_conversions_impl.h>
Public Member Functions
constexpr RangeCheck ()=default
constexpr RangeCheck (bool is_in_lower_bound, bool is_in_upper_bound)
constexpr bool operator== (const RangeCheck &rhs) const =default
constexpr bool IsValid () const
constexpr bool IsInvalid () const
constexpr bool IsOverflow () const
constexpr bool IsUnderflow () const
constexpr bool IsOverflowFlagSet () const
constexpr bool IsUnderflowFlagSet () const
Private Attributes
const bool is_underflow_ = false
const bool is_overflow_ = false
Detailed Description
Definition at line 144 of file safe_conversions_impl.h.
Constructor & Destructor Documentation
RangeCheck() [1/2]
constexpr v8::base::internal::RangeCheck::RangeCheck () [constexpr], [default]
RangeCheck() [2/2]
constexpr v8::base::internal::RangeCheck::RangeCheck (bool is_in_lower_bound, bool is_in_upper_bound) [inline], [constexpr]
Definition at line 147 of file safe_conversions_impl.h.
      : is_underflow_(!is_in_lower_bound), is_overflow_(!is_in_upper_bound) {}
Member Function Documentation
IsInvalid()
constexpr bool v8::base::internal::RangeCheck::IsInvalid () const [inline], [constexpr]
Definition at line 153 of file safe_conversions_impl.h.
{ return is_overflow_ && is_underflow_; }
References is_overflow_, and is_underflow_.
IsOverflow()
constexpr bool v8::base::internal::RangeCheck::IsOverflow () const [inline], [constexpr]
Definition at line 154 of file safe_conversions_impl.h.
{ return is_overflow_ && !is_underflow_; }
References is_overflow_, and is_underflow_.
Referenced by v8::base::internal::IsLess< L, R >::Test(), v8::base::internal::IsLessOrEqual< L, R >::Test(), v8::base::internal::IsGreater< L, R >::Test(), and v8::base::internal::IsGreaterOrEqual< L, R >::Test().
IsOverflowFlagSet()
constexpr bool v8::base::internal::RangeCheck::IsOverflowFlagSet () const [inline], [constexpr]
Definition at line 156 of file safe_conversions_impl.h.
{ return is_overflow_; }
References is_overflow_.
Referenced by v8::base::internal::saturated_cast_impl().
IsUnderflow()
constexpr bool v8::base::internal::RangeCheck::IsUnderflow () const [inline], [constexpr]
Definition at line 155 of file safe_conversions_impl.h.
{ return !is_overflow_ && is_underflow_; }
References is_overflow_, and is_underflow_.
Referenced by v8::base::internal::IsLess< L, R >::Test(), v8::base::internal::IsLessOrEqual< L, R >::Test(), v8::base::internal::IsGreater< L, R >::Test(), and v8::base::internal::IsGreaterOrEqual< L, R >::Test().
IsUnderflowFlagSet()
constexpr bool v8::base::internal::RangeCheck::IsUnderflowFlagSet () const [inline], [constexpr]
Definition at line 157 of file safe_conversions_impl.h.
{ return is_underflow_; }
References is_underflow_.
Referenced by v8::base::internal::saturated_cast_impl().
IsValid()
constexpr bool v8::base::internal::RangeCheck::IsValid () const [inline], [constexpr]
Definition at line 152 of file safe_conversions_impl.h.
{ return !is_overflow_ && !is_underflow_; }
References is_overflow_, and is_underflow_.
operator==()
constexpr bool v8::base::internal::RangeCheck::operator== (const RangeCheck & rhs) const [constexpr], [default]
Member Data Documentation
is_overflow_
const bool v8::base::internal::RangeCheck::is_overflow_ = false [private]
Definition at line 163 of file safe_conversions_impl.h.
Referenced by IsInvalid(), IsOverflow(), IsOverflowFlagSet(), IsUnderflow(), and IsValid().
is_underflow_
const bool v8::base::internal::RangeCheck::is_underflow_ = false [private]
Definition at line 162 of file safe_conversions_impl.h.
Referenced by IsInvalid(), IsOverflow(), IsUnderflow(), IsUnderflowFlagSet(), and IsValid().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/numerics/safe_conversions_impl.h