v8::internal::interpreter::ConditionalControlFlowBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
ConditionalControlFlowBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, AstNode *node)
~ConditionalControlFlowBuilder () override
BytecodeLabels * then_labels ()
BytecodeLabels * else_labels ()
void Then ()
void Else ()
void JumpToEnd ()
Private Attributes
BytecodeLabels end_labels_
BytecodeLabels then_labels_
BytecodeLabels else_labels_
AstNode * node_
int block_coverage_then_slot_
int block_coverage_else_slot_
BlockCoverageBuilder * block_coverage_builder_
Additional Inherited Members
Detailed Description
Definition at line 339 of file control-flow-builders.h.
Constructor & Destructor Documentation
ConditionalControlFlowBuilder()
v8::internal::interpreter::ConditionalControlFlowBuilder::ConditionalControlFlowBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, AstNode * node) [inline]
Definition at line 342 of file control-flow-builders.h.
      : ControlFlowBuilder(builder),
        end_labels_(builder->zone()),
        then_labels_(builder->zone()),
        else_labels_(builder->zone()),
        node_(node),
        block_coverage_builder_(block_coverage_builder) {
    DCHECK(node->IsIfStatement() || node->IsConditional());
    if (block_coverage_builder != nullptr) {
      block_coverage_then_slot_ =
          block_coverage_builder->AllocateBlockCoverageSlot(
              node, SourceRangeKind::kThen);
      block_coverage_else_slot_ =
          block_coverage_builder->AllocateBlockCoverageSlot(
              node, SourceRangeKind::kElse);
    }
  }
References v8::internal::interpreter::BlockCoverageBuilder::AllocateBlockCoverageSlot(), v8::internal::DCHECK(), v8::internal::kElse, and v8::internal::kThen.
 ConditionalControlFlowBuilder()
v8::internal::interpreter::ConditionalControlFlowBuilder::~ConditionalControlFlowBuilder () [override]
Definition at line 250 of file control-flow-builders.cc.
                                                              {
  if (!else_labels_.is_bound()) else_labels_.Bind(builder());
  end_labels_.Bind(builder());
  DCHECK(end_labels_.empty() || end_labels_.is_bound());
  DCHECK(then_labels_.empty() || then_labels_.is_bound());
  DCHECK(else_labels_.empty() || else_labels_.is_bound());
  // IfStatement requires a continuation counter, Conditional does not (as it
  // can only contain expressions).
  if (block_coverage_builder_ != nullptr && node_->IsIfStatement()) {
    block_coverage_builder_->IncrementBlockCounter(
        node_, SourceRangeKind::kContinuation);
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), block_coverage_builder_, v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::DCHECK(), else_labels_, v8::internal::interpreter::BytecodeLabels::empty(), end_labels_, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::interpreter::BytecodeLabels::is_bound(), v8::internal::kContinuation, node_, and then_labels_.
Member Function Documentation
Else()
void v8::internal::interpreter::ConditionalControlFlowBuilder::Else ()
Definition at line 278 of file control-flow-builders.cc.
                                         {
  else_labels()->Bind(builder());
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(block_coverage_else_slot_);
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), block_coverage_builder_, block_coverage_else_slot_, v8::internal::interpreter::ControlFlowBuilder::builder(), else_labels(), and v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter().
else_labels()
BytecodeLabels* v8::internal::interpreter::ConditionalControlFlowBuilder::else_labels () [inline]
Definition at line 364 of file control-flow-builders.h.
{ return &else_labels_; }
Referenced by Else().
JumpToEnd()
void v8::internal::interpreter::ConditionalControlFlowBuilder::JumpToEnd ()
Definition at line 266 of file control-flow-builders.cc.
                                              {
  DCHECK(end_labels_.empty()); // May only be called once.
  builder()->Jump(end_labels_.New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeLabels::empty(), end_labels_, v8::internal::interpreter::BytecodeArrayBuilder::Jump(), and v8::internal::interpreter::BytecodeLabels::New().
Then()
void v8::internal::interpreter::ConditionalControlFlowBuilder::Then ()
Definition at line 271 of file control-flow-builders.cc.
                                         {
  then_labels()->Bind(builder());
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(block_coverage_then_slot_);
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), block_coverage_builder_, block_coverage_then_slot_, v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), and then_labels().
then_labels()
BytecodeLabels* v8::internal::interpreter::ConditionalControlFlowBuilder::then_labels () [inline]
Definition at line 363 of file control-flow-builders.h.
{ return &then_labels_; }
Referenced by Then().
Member Data Documentation
block_coverage_builder_
BlockCoverageBuilder* v8::internal::interpreter::ConditionalControlFlowBuilder::block_coverage_builder_ [private]
Definition at line 379 of file control-flow-builders.h.
Referenced by Else(), Then(), and ~ConditionalControlFlowBuilder().
block_coverage_else_slot_
int v8::internal::interpreter::ConditionalControlFlowBuilder::block_coverage_else_slot_ [private]
Definition at line 378 of file control-flow-builders.h.
Referenced by Else().
block_coverage_then_slot_
int v8::internal::interpreter::ConditionalControlFlowBuilder::block_coverage_then_slot_ [private]
Definition at line 377 of file control-flow-builders.h.
Referenced by Then().
else_labels_
BytecodeLabels v8::internal::interpreter::ConditionalControlFlowBuilder::else_labels_ [private]
Definition at line 374 of file control-flow-builders.h.
Referenced by ~ConditionalControlFlowBuilder().
end_labels_
BytecodeLabels v8::internal::interpreter::ConditionalControlFlowBuilder::end_labels_ [private]
Definition at line 372 of file control-flow-builders.h.
Referenced by JumpToEnd(), and ~ConditionalControlFlowBuilder().
node_
AstNode* v8::internal::interpreter::ConditionalControlFlowBuilder::node_ [private]
Definition at line 376 of file control-flow-builders.h.
Referenced by ~ConditionalControlFlowBuilder().
then_labels_
BytecodeLabels v8::internal::interpreter::ConditionalControlFlowBuilder::then_labels_ [private]
Definition at line 373 of file control-flow-builders.h.
Referenced by ~ConditionalControlFlowBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc