v8::internal::PersistentHandles Class Reference
#include <persistent-handles.h>
Public Member Functions
V8_EXPORT_PRIVATE PersistentHandles (Isolate *isolate)
V8_EXPORT_PRIVATE ~PersistentHandles ()
PersistentHandles (const PersistentHandles &)=delete
PersistentHandles & operator= (const PersistentHandles &)=delete
V8_EXPORT_PRIVATE void Iterate (RootVisitor *visitor)
template<typename T >
IndirectHandle< T > NewHandle (Tagged< T > obj)
template<typename T >
IndirectHandle< T > NewHandle (IndirectHandle< T > obj)
template<typename T >
IndirectHandle< T > NewHandle (DirectHandle< T > obj)
template<typename T >
IndirectHandle< T > NewHandle (T obj)
Isolate * isolate () const
Private Member Functions
void AddBlock ()
V8_EXPORT_PRIVATE Address * GetHandle (Address value)
void Attach (LocalHeap *)
void Detach ()
FRIEND_TEST (PersistentHandlesTest, OrderOfBlocks)
Private Attributes
Isolate * isolate_
std::vector< Address * > blocks_
Address * block_next_
Address * block_limit_
PersistentHandles * prev_
PersistentHandles * next_
Friends
class HandleScopeImplementer
class LocalHeap
class PersistentHandlesList
Detailed Description
Definition at line 25 of file persistent-handles.h.
Constructor & Destructor Documentation
PersistentHandles() [1/2]
v8::internal::PersistentHandles::PersistentHandles (Isolate * isolate) [explicit]
Definition at line 15 of file persistent-handles.cc.
    : isolate_(isolate),
      block_next_(nullptr),
      block_limit_(nullptr),
      prev_(nullptr),
      next_(nullptr) {
  isolate->persistent_handles_list()->Add(this);
}
References v8::internal::PersistentHandlesList::Add(), isolate(), and v8::internal::Isolate::persistent_handles_list().
 PersistentHandles()
v8::internal::PersistentHandles::~PersistentHandles ()
Definition at line 24 of file persistent-handles.cc.
                                      {
  isolate_->persistent_handles_list()->Remove(this);
  for (Address* block_start : blocks_) {
#if ENABLE_GLOBAL_HANDLE_ZAPPING
    HandleScope::ZapRange(block_start, block_start + kHandleBlockSize,
                          kPersistentHandleZapValue);
#endif
    DeleteArray(block_start);
  }
}
References blocks_, isolate_, v8::internal::kHandleBlockSize, v8::internal::kPersistentHandleZapValue, v8::internal::Isolate::persistent_handles_list(), and v8::internal::PersistentHandlesList::Remove().
PersistentHandles() [2/2]
v8::internal::PersistentHandles::PersistentHandles (const PersistentHandles &) [delete]
Member Function Documentation
AddBlock()
void v8::internal::PersistentHandles::AddBlock () [private]
Definition at line 65 of file persistent-handles.cc.
                                 {
  DCHECK_EQ(block_next_, block_limit_);
  Address* block_start = NewArray<Address>(kHandleBlockSize);
  blocks_.push_back(block_start);
  block_next_ = block_start;
  block_limit_ = block_start + kHandleBlockSize;
#ifdef DEBUG
  ordered_blocks_.insert(block_start);
#endif
}
References block_limit_, block_next_, blocks_, DCHECK_EQ, and v8::internal::kHandleBlockSize.
Referenced by GetHandle().
Attach()
void v8::internal::PersistentHandles::Attach (LocalHeap *) [inline], [private]
Definition at line 77 of file persistent-handles.h.
{}
Detach()
void v8::internal::PersistentHandles::Detach () [inline], [private]
Definition at line 78 of file persistent-handles.h.
{}
FRIEND_TEST()
v8::internal::PersistentHandles::FRIEND_TEST (PersistentHandlesTest , OrderOfBlocks) [private]
GetHandle()
Address * v8::internal::PersistentHandles::GetHandle (Address value) [private]
Definition at line 79 of file persistent-handles.cc.
                                                   {
  if (block_next_ == block_limit_) {
    AddBlock();
  }
  DCHECK_LT(block_next_, block_limit_);
  *block_next_ = value;
  return block_next_++;
}
References AddBlock(), block_limit_, block_next_, DCHECK_LT, and v8::internal::value.
Referenced by NewHandle().
isolate()
Isolate* v8::internal::PersistentHandles::isolate () const [inline]
Definition at line 59 of file persistent-handles.h.
{ return isolate_; }
References isolate_.
Referenced by PersistentHandles().
Iterate()
void v8::internal::PersistentHandles::Iterate (RootVisitor * visitor)
Definition at line 89 of file persistent-handles.cc.
                                                    {
  for (int i = 0; i < static_cast<int>(blocks_.size()) - 1; i++) {
    Address* block_start = blocks_[i];
    Address* block_end = block_start + kHandleBlockSize;
    visitor->VisitRootPointers(Root::kHandleScope, nullptr,
                               FullObjectSlot(block_start),
                               FullObjectSlot(block_end));
  }
  if (!blocks_.empty()) {
    Address* block_start = blocks_.back();
    visitor->VisitRootPointers(Root::kHandleScope, nullptr,
                               FullObjectSlot(block_start),
                               FullObjectSlot(block_next_));
  }
}
References block_next_, blocks_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kHandleBlockSize, and v8::internal::RootVisitor::VisitRootPointers().
NewHandle() [1/4]
template<typename T >
IndirectHandle<T> v8::internal::PersistentHandles::NewHandle (DirectHandle< T > obj) [inline]
Definition at line 49 of file persistent-handles.h.
                                                   {
    return NewHandle(*obj);
  }
References NewHandle().
NewHandle() [2/4]
template<typename T >
IndirectHandle<T> v8::internal::PersistentHandles::NewHandle (IndirectHandle< T > obj) [inline]
Definition at line 44 of file persistent-handles.h.
                                                     {
    return NewHandle(*obj);
  }
References NewHandle().
NewHandle() [3/4]
template<typename T >
IndirectHandle<T> v8::internal::PersistentHandles::NewHandle (T obj) [inline]
Definition at line 54 of file persistent-handles.h.
                                     {
    static_assert(kTaggedCanConvertToRawObjects);
    return NewHandle(Tagged<T>(obj));
  }
References v8::internal::kTaggedCanConvertToRawObjects, and NewHandle().
NewHandle() [4/4]
template<typename T >
IndirectHandle<T> v8::internal::PersistentHandles::NewHandle (Tagged< T > obj) [inline]
Definition at line 36 of file persistent-handles.h.
                                             {
#ifdef DEBUG
    CheckOwnerIsNotParked();
#endif
    return IndirectHandle<T>(GetHandle(obj.ptr()));
  }
References GetHandle(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by NewHandle().
operator=()
PersistentHandles& v8::internal::PersistentHandles::operator= (const PersistentHandles &) [delete]
Friends And Related Function Documentation
HandleScopeImplementer
friend class HandleScopeImplementer [friend]
Definition at line 94 of file persistent-handles.h.
LocalHeap
friend class LocalHeap [friend]
Definition at line 95 of file persistent-handles.h.
PersistentHandlesList
friend class PersistentHandlesList [friend]
Definition at line 96 of file persistent-handles.h.
Member Data Documentation
block_limit_
Address* v8::internal::PersistentHandles::block_limit_ [private]
Definition at line 85 of file persistent-handles.h.
Referenced by AddBlock(), and GetHandle().
block_next_
Address* v8::internal::PersistentHandles::block_next_ [private]
Definition at line 84 of file persistent-handles.h.
Referenced by AddBlock(), GetHandle(), and Iterate().
blocks_
std::vector<Address*> v8::internal::PersistentHandles::blocks_ [private]
Definition at line 82 of file persistent-handles.h.
Referenced by AddBlock(), Iterate(), and ~PersistentHandles().
isolate_
Isolate* v8::internal::PersistentHandles::isolate_ [private]
Definition at line 81 of file persistent-handles.h.
Referenced by isolate(), and ~PersistentHandles().
next_
PersistentHandles* v8::internal::PersistentHandles::next_ [private]
Definition at line 88 of file persistent-handles.h.
Referenced by v8::internal::PersistentHandlesList::Add(), v8::internal::PersistentHandlesList::Iterate(), and v8::internal::PersistentHandlesList::Remove().
prev_
PersistentHandles* v8::internal::PersistentHandles::prev_ [private]
Definition at line 87 of file persistent-handles.h.
Referenced by v8::internal::PersistentHandlesList::Add(), and v8::internal::PersistentHandlesList::Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/persistent-handles.h
/mnt/V8SourceCode/src/handles/persistent-handles.cc