v8::Message Class Reference
An error message.
#include <v8-message.h>
Public Member Functions
Local< String > Get () const
Use Isolate::GetCurrent () instead
Return the isolate to which the Message belongs.
V8_WARN_UNUSED_RESULT MaybeLocal< String > GetSource (Local< Context > context) const
V8_WARN_UNUSED_RESULT MaybeLocal< String > GetSourceLine (Local< Context > context) const
ScriptOrigin GetScriptOrigin () const
Returns the origin for the script from where the function causing the error originates.
Local< Value > GetScriptResourceName () const
Returns the resource name for the script from where the function causing the error originates.
Local< StackTrace > GetStackTrace () const
Exception stack trace.
V8_WARN_UNUSED_RESULT Maybe< int > GetLineNumber (Local< Context > context) const
Returns the number, 1-based, of the line where the error occurred.
int GetStartPosition () const
Returns the index within the script of the first character where the error occurred.
int GetEndPosition () const
Returns the index within the script of the last character where the error occurred.
int GetWasmFunctionIndex () const
Returns the Wasm function index where the error occurred.
int ErrorLevel () const
Returns the error level of the message.
int GetStartColumn () const
Returns the index within the line of the first character where the error occurred.
V8_WARN_UNUSED_RESULT Maybe< int > GetStartColumn (Local< Context > context) const
int GetEndColumn () const
Returns the index within the line of the last character where the error occurred.
V8_WARN_UNUSED_RESULT Maybe< int > GetEndColumn (Local< Context > context) const
bool IsSharedCrossOrigin () const
Passes on the value set by the embedder when it fed the script from which this Message was generated to V8.
bool IsOpaque () const
Static Public Member Functions
static void PrintCurrentStackTrace (Isolate *isolate, std::ostream &out, PrintCurrentStackTraceFilterCallback should_include_frame_callback=nullptr)
If provided, the callback can be used to selectively include or redact frames based on their script names.
Public Attributes
Use which is guaranteed to return the same isolate since https: Isolate* GetIsolate() const
Static Public Attributes
static const int kNoLineNumberInfo = 0
static const int kNoColumnInfo = 0
static const int kNoScriptIdInfo = 0
static const int kNoWasmFunctionIndexInfo = -1
Detailed Description
An error message.
Definition at line 107 of file v8-message.h.
Member Function Documentation
ErrorLevel()
int v8::Message::ErrorLevel () const
Returns the error level of the message.
Definition at line 2983 of file api.cc.
                              {
  auto self = Utils::OpenDirectHandle(this);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return self->error_level();
}
References v8::Utils::OpenDirectHandle().
Get()
Local< String > v8::Message::Get () const
Definition at line 2902 of file api.cc.
                                 {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  InternalEscapableScope scope(i_isolate);
  Local<String> result =
      Utils::ToLocal(i::MessageHandler::GetMessage(i_isolate, self));
  return scope.Escape(result);
}
References v8::internal::Isolate::Current(), v8::InternalEscapableScope::Escape(), v8::internal::MessageHandler::GetMessage(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
GetEndColumn() [1/2]
int v8::Message::GetEndColumn () const
Returns the index within the line of the last character where the error occurred.
Definition at line 3027 of file api.cc.
                                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  HandleScope handle_scope(reinterpret_cast<Isolate*>(i_isolate));
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  const int column_number = self->GetColumnNumber();
  if (column_number == -1) return -1;
  const int start = self->GetStartPosition();
  const int end = self->GetEndPosition();
  return column_number + (end - start);
}
References v8::internal::Isolate::Current(), v8::internal::compiler::end(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), and v8::Utils::OpenDirectHandle().
Referenced by GetEndColumn().
GetEndColumn() [2/2]
Maybe< int > v8::Message::GetEndColumn (Local< Context > context) const
Definition at line 3040 of file api.cc.
                                                             {
  return Just(GetEndColumn());
}
References GetEndColumn(), and v8::Just().
GetEndPosition()
int v8::Message::GetEndPosition () const
Returns the index within the script of the last character where the error occurred.
Definition at line 2974 of file api.cc.
                                  {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  HandleScope handle_scope(reinterpret_cast<Isolate*>(i_isolate));
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  return self->GetEndPosition();
}
References v8::internal::Isolate::Current(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), and v8::Utils::OpenDirectHandle().
GetLineNumber()
Maybe< int > v8::Message::GetLineNumber (Local< Context > context) const
Returns the number, 1-based, of the line where the error occurred.
Definition at line 2956 of file api.cc.
                                                              {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  HandleScope handle_scope(reinterpret_cast<Isolate*>(i_isolate));
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  return Just(self->GetLineNumber());
}
References v8::internal::Isolate::Current(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), v8::Just(), and v8::Utils::OpenDirectHandle().
GetScriptOrigin()
ScriptOrigin v8::Message::GetScriptOrigin () const
Returns the origin for the script from where the function causing the error originates.
Definition at line 2917 of file api.cc.
                                            {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Script> script(self->script(), i_isolate);
  return GetScriptOriginForScript(i_isolate, script);
}
References v8::internal::Isolate::Current(), v8::GetScriptOriginForScript(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
Referenced by GetScriptResourceName().
GetScriptResourceName()
v8::Local< Value > v8::Message::GetScriptResourceName () const
Returns the resource name for the script from where the function causing the error originates.
Definition at line 2939 of file api.cc.
                                                    {
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return GetScriptOrigin().ResourceName();
}
References GetScriptOrigin(), and v8::ScriptOrigin::ResourceName().
GetSource()
MaybeLocal< String > v8::Message::GetSource (Local< Context > context) const
Definition at line 3058 of file api.cc.
                                                                  {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  InternalEscapableScope handle_scope(i_isolate);
  return handle_scope.Escape(
      Utils::ToLocal(i::direct_handle(self->GetSource(), i_isolate)));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::InternalEscapableScope::Escape(), and v8::Utils::OpenDirectHandle().
GetSourceLine()
MaybeLocal< String > v8::Message::GetSourceLine (Local< Context > context) const
Definition at line 3067 of file api.cc.
                                                                      {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  InternalEscapableScope handle_scope(i_isolate);
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  return handle_scope.Escape(Utils::ToLocal(self->GetSourceLine()));
}
References v8::internal::Isolate::Current(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), v8::InternalEscapableScope::Escape(), and v8::Utils::OpenDirectHandle().
GetStackTrace()
v8::Local< v8::StackTrace > v8::Message::GetStackTrace () const
Exception stack trace.
By default stack traces are not captured for uncaught exceptions. SetCaptureStackTraceForUncaughtExceptions allows to change this option.
Definition at line 2945 of file api.cc.
                                                   {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  InternalEscapableScope scope(i_isolate);
  i::DirectHandle<i::Object> stack_trace(self->stack_trace(), i_isolate);
  if (!IsStackTraceInfo(*stack_trace)) return {};
  return scope.Escape(
      Utils::StackTraceToLocal(i::Cast<i::StackTraceInfo>(stack_trace)));
}
References v8::internal::Isolate::Current(), v8::InternalEscapableScope::Escape(), and v8::Utils::OpenDirectHandle().
GetStartColumn() [1/2]
int v8::Message::GetStartColumn () const
Returns the index within the line of the first character where the error occurred.
Definition at line 2990 of file api.cc.
                                  {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  HandleScope handle_scope(reinterpret_cast<Isolate*>(i_isolate));
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  return self->GetColumnNumber();
}
References v8::internal::Isolate::Current(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), and v8::Utils::OpenDirectHandle().
Referenced by GetStartColumn().
GetStartColumn() [2/2]
Maybe< int > v8::Message::GetStartColumn (Local< Context > context) const
Definition at line 3023 of file api.cc.
                                                               {
  return Just(GetStartColumn());
}
References GetStartColumn(), and v8::Just().
GetStartPosition()
int v8::Message::GetStartPosition () const
Returns the index within the script of the first character where the error occurred.
Definition at line 2965 of file api.cc.
                                    {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  HandleScope handle_scope(reinterpret_cast<Isolate*>(i_isolate));
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  return self->GetStartPosition();
}
References v8::internal::Isolate::Current(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), and v8::Utils::OpenDirectHandle().
GetWasmFunctionIndex()
int v8::Message::GetWasmFunctionIndex () const
Returns the Wasm function index where the error occurred.
Returns -1 if message is not from a Wasm script.
Definition at line 2999 of file api.cc.
                                        {
#if V8_ENABLE_WEBASSEMBLY
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  HandleScope handle_scope(reinterpret_cast<Isolate*>(i_isolate));
  i::JSMessageObject::EnsureSourcePositionsAvailable(i_isolate, self);
  int start_position = self->GetColumnNumber();
  if (start_position == -1) return Message::kNoWasmFunctionIndexInfo;
  i::DirectHandle<i::Script> script(self->script(), i_isolate);
  if (script->type() != i::Script::Type::kWasm) {
    return Message::kNoWasmFunctionIndexInfo;
  }
  auto debug_script = ToApiHandle<debug::Script>(script);
  return Local<debug::WasmScript>::Cast(debug_script)
      ->GetContainingFunction(start_position);
#else
  return Message::kNoWasmFunctionIndexInfo;
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::Local< T >::Cast(), v8::internal::Isolate::Current(), v8::internal::JSMessageObject::EnsureSourcePositionsAvailable(), kNoWasmFunctionIndexInfo, v8::Utils::OpenDirectHandle(), and v8::internal::script.
Isolate::GetCurrent()
Use v8::Message::Isolate::GetCurrent ()
Return the isolate to which the Message belongs.
IsOpaque()
bool v8::Message::IsOpaque () const
Definition at line 3051 of file api.cc.
                             {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return self->script()->origin_options().IsOpaque();
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
IsSharedCrossOrigin()
bool v8::Message::IsSharedCrossOrigin () const
Passes on the value set by the embedder when it fed the script from which this Message was generated to V8.
Definition at line 3044 of file api.cc.
                                        {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return self->script()->origin_options().IsSharedCrossOrigin();
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
PrintCurrentStackTrace()
void v8::Message::PrintCurrentStackTrace (Isolate * isolate, std::ostream & out, PrintCurrentStackTraceFilterCallback should_include_frame_callback = nullptr) [static]
If provided, the callback can be used to selectively include or redact frames based on their script names.
(true to include a frame)
Definition at line 3076 of file api.cc.
                                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i_isolate->PrintCurrentStackTrace(out, should_include_frame_callback);
}
References v8::internal::Isolate::PrintCurrentStackTrace().
Member Data Documentation
https
Use which is guaranteed to return the same isolate since v8::Message::https
Definition at line 116 of file v8-message.h.
kNoColumnInfo
const int v8::Message::kNoColumnInfo = 0 [static]
Definition at line 202 of file v8-message.h.
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), v8::internal::CallSiteInfo::GetColumnNumber(), v8::internal::CallSiteInfo::GetEnclosingColumnNumber(), and v8_inspector::StackFrame::StackFrame().
kNoLineNumberInfo
const int v8::Message::kNoLineNumberInfo = 0 [static]
Definition at line 201 of file v8-message.h.
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), v8::internal::CallSiteInfo::GetEnclosingLineNumber(), v8::internal::JSMessageObject::GetLineNumber(), v8::internal::CallSiteInfo::GetLineNumber(), and v8_inspector::StackFrame::StackFrame().
kNoScriptIdInfo
const int v8::Message::kNoScriptIdInfo = 0 [static]
Definition at line 203 of file v8-message.h.
Referenced by v8::internal::CallSiteInfo::GetScriptId().
kNoWasmFunctionIndexInfo
const int v8::Message::kNoWasmFunctionIndexInfo = -1 [static]
Definition at line 204 of file v8-message.h.
Referenced by GetWasmFunctionIndex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-message.h
/mnt/V8SourceCode/src/api/api.cc