v8::internal::interpreter::BytecodeSourceInfo Class Reference
#include <bytecode-source-info.h>
Public Member Functions
BytecodeSourceInfo ()
BytecodeSourceInfo (int source_position, bool is_statement, bool is_breakable=true)
void MakeStatementPosition (int source_position, bool is_breakable=true)
void MakeExpressionPosition (int source_position)
void ForceExpressionPosition (int source_position)
int source_position () const
bool is_statement () const
bool is_expression () const
bool is_valid () const
void set_invalid ()
bool is_breakable () const
bool operator== (const BytecodeSourceInfo &other) const
bool operator!= (const BytecodeSourceInfo &other) const
Static Public Attributes
static const int kUninitializedPosition = -1
Private Types
enum class PositionType : uint8_t { kNone
, kExpression
, kStatement
 }
Private Attributes
PositionType position_type_
int source_position_
bool is_breakable_
Detailed Description
Definition at line 15 of file bytecode-source-info.h.
Member Enumeration Documentation
PositionType
enum v8::internal::interpreter::BytecodeSourceInfo::PositionType : uint8_t [strong], [private]
Enumerator
kNone
kExpression
kStatement
Definition at line 92 of file bytecode-source-info.h.
: uint8_t { kNone, kExpression, kStatement };
Constructor & Destructor Documentation
BytecodeSourceInfo() [1/2]
v8::internal::interpreter::BytecodeSourceInfo::BytecodeSourceInfo () [inline]
Definition at line 19 of file bytecode-source-info.h.
      : position_type_(PositionType::kNone),
        source_position_(kUninitializedPosition),
        is_breakable_(true) {}
References v8::internal::kNone.
BytecodeSourceInfo() [2/2]
v8::internal::interpreter::BytecodeSourceInfo::BytecodeSourceInfo (int source_position, bool is_statement, bool is_breakable = true) [inline]
Definition at line 24 of file bytecode-source-info.h.
      : position_type_(is_statement ? PositionType::kStatement
                                    : PositionType::kExpression),
        source_position_(source_position),
        is_breakable_(is_breakable) {
    DCHECK_GE(source_position, 0);
  }
References DCHECK_GE, and source_position().
Member Function Documentation
ForceExpressionPosition()
void v8::internal::interpreter::BytecodeSourceInfo::ForceExpressionPosition (int source_position) [inline]
Definition at line 56 of file bytecode-source-info.h.
                                                    {
    position_type_ = PositionType::kExpression;
    source_position_ = source_position;
  }
References kExpression, position_type_, source_position(), and source_position_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::EmitFunctionStartSourcePosition(), and v8::internal::interpreter::BytecodeArrayBuilder::JumpLoop().
is_breakable()
bool v8::internal::interpreter::BytecodeSourceInfo::is_breakable () const [inline]
Definition at line 79 of file bytecode-source-info.h.
{ return is_breakable_; }
References is_breakable_.
Referenced by MakeStatementPosition(), and v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable().
is_expression()
bool v8::internal::interpreter::BytecodeSourceInfo::is_expression () const [inline]
Definition at line 69 of file bytecode-source-info.h.
                             {
    return position_type_ == PositionType::kExpression;
  }
References kExpression, and position_type_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo().
is_statement()
bool v8::internal::interpreter::BytecodeSourceInfo::is_statement () const [inline]
Definition at line 66 of file bytecode-source-info.h.
                            {
    return position_type_ == PositionType::kStatement;
  }
References kStatement, and position_type_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo(), MakeExpressionPosition(), v8::internal::interpreter::operator<<(), and v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable().
is_valid()
bool v8::internal::interpreter::BytecodeSourceInfo::is_valid () const [inline]
Definition at line 73 of file bytecode-source-info.h.
{ return position_type_ != PositionType::kNone; }
References kNone, and position_type_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo(), v8::internal::interpreter::operator<<(), v8::internal::interpreter::BytecodeNode::Print(), v8::internal::interpreter::BytecodeArrayBuilder::SetDeferredSourceInfo(), source_position(), v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable(), v8::internal::interpreter::BytecodeArrayWriter::WriteJump(), v8::internal::interpreter::BytecodeArrayWriter::WriteJumpLoop(), and v8::internal::interpreter::BytecodeArrayWriter::WriteSwitch().
MakeExpressionPosition()
void v8::internal::interpreter::BytecodeSourceInfo::MakeExpressionPosition (int source_position) [inline]
Definition at line 48 of file bytecode-source-info.h.
                                                   {
    DCHECK(!is_statement());
    position_type_ = PositionType::kExpression;
    source_position_ = source_position;
    is_breakable_ = true;
  }
References v8::internal::DCHECK(), is_breakable_, is_statement(), kExpression, position_type_, source_position(), and source_position_.
MakeStatementPosition()
void v8::internal::interpreter::BytecodeSourceInfo::MakeStatementPosition (int source_position, bool is_breakable = true) [inline]
Definition at line 34 of file bytecode-source-info.h.
                                                                            {
    // Statement positions can be replaced by other statement
    // positions. For example , "for (x = 0; x < 3; ++x) 7;" has a
    // statement position associated with 7 but no bytecode associated
    // with it. Then Next is emitted after the body and has
    // statement position and overrides the existing one.
    position_type_ = PositionType::kStatement;
    source_position_ = source_position;
    is_breakable_ = is_breakable;
  }
References is_breakable(), is_breakable_, kStatement, position_type_, source_position(), and source_position_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo().
operator!=()
bool v8::internal::interpreter::BytecodeSourceInfo::operator!= (const BytecodeSourceInfo & other) const [inline]
Definition at line 86 of file bytecode-source-info.h.
                                                         {
    return position_type_ != other.position_type_ ||
           source_position_ != other.source_position_;
  }
References position_type_, and source_position_.
operator==()
bool v8::internal::interpreter::BytecodeSourceInfo::operator== (const BytecodeSourceInfo & other) const [inline]
Definition at line 81 of file bytecode-source-info.h.
                                                         {
    return position_type_ == other.position_type_ &&
           source_position_ == other.source_position_;
  }
References position_type_, and source_position_.
set_invalid()
void v8::internal::interpreter::BytecodeSourceInfo::set_invalid () [inline]
Definition at line 74 of file bytecode-source-info.h.
                     {
    position_type_ = PositionType::kNone;
    source_position_ = kUninitializedPosition;
  }
References kNone, kUninitializedPosition, position_type_, and source_position_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo(), and v8::internal::interpreter::BytecodeArrayBuilder::MaybePopSourcePosition().
source_position()
int v8::internal::interpreter::BytecodeSourceInfo::source_position () const [inline]
Definition at line 61 of file bytecode-source-info.h.
                              {
    DCHECK(is_valid());
    return source_position_;
  }
References v8::internal::DCHECK(), is_valid(), and source_position_.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AttachOrEmitDeferredSourceInfo(), BytecodeSourceInfo(), ForceExpressionPosition(), MakeExpressionPosition(), MakeStatementPosition(), v8::internal::interpreter::operator<<(), and v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable().
Member Data Documentation
is_breakable_
bool v8::internal::interpreter::BytecodeSourceInfo::is_breakable_ [private]
Definition at line 96 of file bytecode-source-info.h.
Referenced by is_breakable(), MakeExpressionPosition(), and MakeStatementPosition().
kUninitializedPosition
const int v8::internal::interpreter::BytecodeSourceInfo::kUninitializedPosition = -1 [static]
Definition at line 17 of file bytecode-source-info.h.
Referenced by set_invalid().
position_type_
PositionType v8::internal::interpreter::BytecodeSourceInfo::position_type_ [private]
Definition at line 94 of file bytecode-source-info.h.
Referenced by ForceExpressionPosition(), is_expression(), is_statement(), is_valid(), MakeExpressionPosition(), MakeStatementPosition(), operator!=(), operator==(), and set_invalid().
source_position_
int v8::internal::interpreter::BytecodeSourceInfo::source_position_ [private]
Definition at line 95 of file bytecode-source-info.h.
Referenced by ForceExpressionPosition(), MakeExpressionPosition(), MakeStatementPosition(), operator!=(), operator==(), set_invalid(), and source_position().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-source-info.h