v8::internal::compiler::JSCreateLiteralOpNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSCreateLiteralOpNode (Node *node)
const CreateLiteralParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1253 of file js-operator.h.
Constructor & Destructor Documentation
JSCreateLiteralOpNode()
constexpr v8::internal::compiler::JSCreateLiteralOpNode::JSCreateLiteralOpNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1255 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK(node->opcode() == IrOpcode::kJSCreateLiteralArray ||
           node->opcode() == IrOpcode::kJSCreateLiteralObject ||
           node->opcode() == IrOpcode::kJSCreateLiteralRegExp);
  }
References v8::internal::DCHECK(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const CreateLiteralParameters& v8::internal::compiler::JSCreateLiteralOpNode::Parameters () const [inline]
Definition at line 1262 of file js-operator.h.
                                                    {
    return CreateLiteralParametersOf(node()->op());
  }
References v8::internal::compiler::CreateLiteralParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h