v8::internal::DescriptorLookupCache Class Reference
#include <lookup-cache.h>
Classes
struct Key
Public Member Functions
DescriptorLookupCache (const DescriptorLookupCache &)=delete
DescriptorLookupCache & operator= (const DescriptorLookupCache &)=delete
int Lookup (Tagged< Map > source, Tagged< Name > name)
void Update (Tagged< Map > source, Tagged< Name > name, int result)
void Clear ()
Static Public Attributes
static const int kAbsent = -2
Private Member Functions
DescriptorLookupCache ()
Static Private Member Functions
static int Hash (Tagged< Map > source, Tagged< Name > name)
Private Attributes
Key keys_ [kLength]
int results_ [kLength]
Static Private Attributes
static const int kLength = 64
Friends
class Isolate
Detailed Description
Definition at line 19 of file lookup-cache.h.
Constructor & Destructor Documentation
DescriptorLookupCache() [1/2]
v8::internal::DescriptorLookupCache::DescriptorLookupCache (const DescriptorLookupCache &) [delete]
DescriptorLookupCache() [2/2]
v8::internal::DescriptorLookupCache::DescriptorLookupCache () [inline], [private]
Definition at line 36 of file lookup-cache.h.
                          {
    for (int i = 0; i < kLength; ++i) {
      keys_[i].source = Tagged<Map>();
      keys_[i].name = Tagged<Name>();
      results_[i] = kAbsent;
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, kAbsent, keys_, kLength, v8::internal::DescriptorLookupCache::Key::name, results_, and v8::internal::DescriptorLookupCache::Key::source.
Member Function Documentation
Clear()
void v8::internal::DescriptorLookupCache::Clear ()
Definition at line 10 of file lookup-cache.cc.
                                  {
  for (int index = 0; index < kLength; index++) keys_[index].source = Map();
}
References v8::internal::index, keys_, kLength, and v8::internal::compiler::Map.
Referenced by v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::Heap::CreateInitialMutableObjects(), and v8::internal::Heap::MarkCompactPrologue().
Hash()
int v8::internal::DescriptorLookupCache::Hash (Tagged< Map > source, Tagged< Name > name) [inline], [static], [private]
Definition at line 18 of file lookup-cache-inl.h.
                                                                     {
  DCHECK(IsUniqueName(name));
  // Uses only lower 32 bits if pointers are larger.
  uint32_t source_hash = static_cast<uint32_t>(source.ptr()) >> kTaggedSizeLog2;
  uint32_t name_hash = name->hash();
  return (source_hash ^ name_hash) % kLength;
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), kLength, v8::internal::kTaggedSizeLog2, v8::internal::name, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by Lookup(), and Update().
Lookup()
int v8::internal::DescriptorLookupCache::Lookup (Tagged< Map > source, Tagged< Name > name) [inline]
Definition at line 26 of file lookup-cache-inl.h.
                                                                       {
  int index = Hash(source, name);
  Key& key = keys_[index];
  // Pointers in the table might be stale, so use SafeEquals.
  if (key.source.SafeEquals(source) && key.name.SafeEquals(name)) {
    return results_[index];
  }
  return kAbsent;
}
References Hash(), v8::internal::index, kAbsent, v8::internal::key, keys_, v8::internal::name, and results_.
Referenced by v8::internal::DescriptorArray::SearchWithCache().
operator=()
DescriptorLookupCache& v8::internal::DescriptorLookupCache::operator= (const DescriptorLookupCache &) [delete]
Update()
void v8::internal::DescriptorLookupCache::Update (Tagged< Map > source, Tagged< Name > name, int result) [inline]
Definition at line 36 of file lookup-cache-inl.h.
                                               {
  DCHECK_NE(result, kAbsent);
  int index = Hash(source, name);
  Key& key = keys_[index];
  key.source = source;
  key.name = name;
  results_[index] = result;
}
References DCHECK_NE, Hash(), v8::internal::index, kAbsent, v8::internal::key, keys_, v8::internal::name, v8::base::internal::result, and results_.
Referenced by v8::internal::DescriptorArray::SearchWithCache().
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 55 of file lookup-cache.h.
Member Data Documentation
kAbsent
const int v8::internal::DescriptorLookupCache::kAbsent = -2 [static]
Definition at line 33 of file lookup-cache.h.
Referenced by DescriptorLookupCache(), Lookup(), v8::internal::DescriptorArray::SearchWithCache(), and Update().
keys_
Key v8::internal::DescriptorLookupCache::keys_[kLength] [private]
Definition at line 52 of file lookup-cache.h.
Referenced by Clear(), DescriptorLookupCache(), Lookup(), and Update().
kLength
const int v8::internal::DescriptorLookupCache::kLength = 64 [static], [private]
Definition at line 46 of file lookup-cache.h.
Referenced by Clear(), DescriptorLookupCache(), and Hash().
results_
int v8::internal::DescriptorLookupCache::results_[kLength] [private]
Definition at line 53 of file lookup-cache.h.
Referenced by DescriptorLookupCache(), Lookup(), and Update().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/lookup-cache.h
/mnt/V8SourceCode/src/objects/lookup-cache-inl.h
/mnt/V8SourceCode/src/objects/lookup-cache.cc