v8::internal::RememberedSetOperations Class Reference
#include <remembered-set.h>
Static Public Member Functions
template<AccessMode access_mode>
static void Insert (SlotSet *slot_set, size_t slot_offset)
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
static int Iterate (SlotSet *slot_set, const MutablePageMetadata *chunk, Callback callback, SlotSet::EmptyBucketMode mode)
static void Remove (SlotSet *slot_set, MutablePageMetadata *chunk, Address slot_addr)
static void RemoveRange (SlotSet *slot_set, MutablePageMetadata *page, Address start, Address end, SlotSet::EmptyBucketMode mode)
static void CheckNoneInRange (SlotSet *slot_set, MemoryChunk *chunk, Address start, Address end)
Detailed Description
Definition at line 25 of file remembered-set.h.
Member Function Documentation
CheckNoneInRange()
static void v8::internal::RememberedSetOperations::CheckNoneInRange (SlotSet * slot_set, MemoryChunk * chunk, Address start, Address end) [inline], [static]
Definition at line 70 of file remembered-set.h.
                                                           {
    if (slot_set != nullptr) {
      size_t start_bucket = SlotSet::BucketForSlot(chunk->Offset(start));
      // Both 'end' and 'end_bucket' are exclusive limits, so do some index
      // juggling to make sure we get the right bucket even if the end address
      // is at the start of a bucket.
      size_t end_bucket = SlotSet::BucketForSlot(
                              chunk->OffsetMaybeOutOfRange(end) - kTaggedSize) +
                          1;
      slot_set->Iterate(
          chunk->address(), start_bucket, end_bucket,
          [start, end](MaybeObjectSlot slot) {
            CHECK(slot.address() < start || slot.address() >= end);
            return KEEP_SLOT;
          },
          SlotSet::KEEP_EMPTY_BUCKETS);
    }
  }
References v8::internal::MemoryChunk::address(), heap::base::BasicSlotSet< kTaggedSize >::BucketForSlot(), v8::internal::compiler::end(), v8::internal::SlotSet::Iterate(), heap::base::BasicSlotSet< kTaggedSize >::KEEP_EMPTY_BUCKETS, v8::internal::kTaggedSize, v8::internal::MemoryChunk::Offset(), and v8::internal::MemoryChunk::OffsetMaybeOutOfRange().
Referenced by v8::internal::RememberedSet< type >::CheckNoneInRange().
Insert()
template<AccessMode access_mode>
static void v8::internal::RememberedSetOperations::Insert (SlotSet * slot_set, size_t slot_offset) [inline], [static]
Definition at line 30 of file remembered-set.h.
                                                            {
    slot_set->Insert<access_mode == v8::internal::AccessMode::ATOMIC
                         ? v8::internal::SlotSet::AccessMode::ATOMIC
                         : v8::internal::SlotSet::AccessMode::NON_ATOMIC>(
        slot_offset);
  }
References v8::internal::ATOMIC, and heap::base::BasicSlotSet< SlotGranularity >::Insert().
Iterate()
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
static int v8::internal::RememberedSetOperations::Iterate (SlotSet * slot_set, const MutablePageMetadata * chunk, Callback callback, SlotSet::EmptyBucketMode mode) [inline], [static]
Definition at line 38 of file remembered-set.h.
                                                                     {
    int slots = 0;
    if (slot_set != nullptr) {
      slots += slot_set->Iterate<access_mode>(
          chunk->ChunkAddress(), 0, chunk->BucketsInSlotSet(), callback, mode);
    }
    return slots;
  }
References v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::SlotSet::Iterate(), and mode().
Remove()
static void v8::internal::RememberedSetOperations::Remove (SlotSet * slot_set, MutablePageMetadata * chunk, Address slot_addr) [inline], [static]
Definition at line 48 of file remembered-set.h.
                                        {
    if (slot_set != nullptr) {
      uintptr_t offset = chunk->Offset(slot_addr);
      slot_set->Remove(offset);
    }
  }
References v8::internal::MemoryChunkMetadata::Offset(), and heap::base::BasicSlotSet< SlotGranularity >::Remove().
Referenced by v8::internal::RememberedSet< type >::Remove().
RemoveRange()
static void v8::internal::RememberedSetOperations::RemoveRange (SlotSet * slot_set, MutablePageMetadata * page, Address start, Address end, SlotSet::EmptyBucketMode mode) [inline], [static]
Definition at line 56 of file remembered-set.h.
                                                       {
    if (slot_set != nullptr) {
      MemoryChunk* chunk = page->Chunk();
      uintptr_t start_offset = chunk->Offset(start);
      uintptr_t end_offset = chunk->OffsetMaybeOutOfRange(end);
      DCHECK_LE(start_offset, end_offset);
      slot_set->RemoveRange(static_cast<int>(start_offset),
                            static_cast<int>(end_offset),
                            page->BucketsInSlotSet(), mode);
    }
  }
References v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_LE, v8::internal::compiler::end(), mode(), v8::internal::MemoryChunk::Offset(), v8::internal::MemoryChunk::OffsetMaybeOutOfRange(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
Referenced by v8::internal::RememberedSet< type >::RemoveRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/remembered-set.h