v8::internal::NestedTimedHistogramScope Class Reference
#include <counters-scopes.h>
Public Member Functions
NestedTimedHistogramScope (NestedTimedHistogram *histogram, Isolate *isolate=nullptr)
~NestedTimedHistogramScope ()
Private Member Functions
void StartInteral ()
void StopInternal ()
void Start ()
void Stop ()
void Pause (base::TimeTicks now)
void Resume (base::TimeTicks now)
void RecordLongTaskTime (base::TimeDelta elapsed) const
NestedTimedHistogram * timed_histogram ()
Private Attributes
friend NestedTimedHistogram
friend PauseNestedTimedHistogramScope
NestedTimedHistogramScope * previous_scope_
Isolate * isolate_
Additional Inherited Members
Detailed Description
Definition at line 142 of file counters-scopes.h.
Constructor & Destructor Documentation
NestedTimedHistogramScope()
v8::internal::NestedTimedHistogramScope::NestedTimedHistogramScope (NestedTimedHistogram * histogram, Isolate * isolate = nullptr) [inline], [explicit]
Definition at line 144 of file counters-scopes.h.
      : BaseTimedHistogramScope(histogram), isolate_(isolate) {
    Start();
  }
 NestedTimedHistogramScope()
v8::internal::NestedTimedHistogramScope::~NestedTimedHistogramScope () [inline]
Definition at line 149 of file counters-scopes.h.
{ Stop(); }
Member Function Documentation
Pause()
void v8::internal::NestedTimedHistogramScope::Pause (base::TimeTicks now) [inline], [private]
Definition at line 186 of file counters-scopes.h.
                                {
    DCHECK(histogram_->Enabled());
    timer_.Pause(now);
  }
References v8::internal::DCHECK().
RecordLongTaskTime()
void v8::internal::NestedTimedHistogramScope::RecordLongTaskTime (base::TimeDelta elapsed) const [inline], [private]
Definition at line 196 of file counters-scopes.h.
                                                       {
    if (histogram_ == isolate_->counters()->execute()) {
      isolate_->GetCurrentLongTaskStats()->v8_execute_us +=
          elapsed.InMicroseconds();
    }
  }
References v8::base::TimeDelta::InMicroseconds().
Resume()
void v8::internal::NestedTimedHistogramScope::Resume (base::TimeTicks now) [inline], [private]
Definition at line 191 of file counters-scopes.h.
                                 {
    DCHECK(histogram_->Enabled());
    timer_.Resume(now);
  }
References v8::internal::DCHECK().
Start()
void v8::internal::NestedTimedHistogramScope::Start () [inline], [private]
Definition at line 176 of file counters-scopes.h.
                         {
    if (histogram_->Enabled()) StartInteral();
    LogStart(timed_histogram()->counters()->isolate());
  }
StartInteral()
void v8::internal::NestedTimedHistogramScope::StartInteral () [inline], [private]
Definition at line 155 of file counters-scopes.h.
                      {
    previous_scope_ = timed_histogram()->Enter(this);
    base::TimeTicks now = base::TimeTicks::Now();
    if (previous_scope_) previous_scope_->Pause(now);
    timer_.Start(now);
  }
References v8::base::TimeTicks::Now().
Stop()
void v8::internal::NestedTimedHistogramScope::Stop () [inline], [private]
Definition at line 181 of file counters-scopes.h.
                        {
    if (histogram_->Enabled()) StopInternal();
    LogEnd(timed_histogram()->counters()->isolate());
  }
StopInternal()
void v8::internal::NestedTimedHistogramScope::StopInternal () [inline], [private]
Definition at line 162 of file counters-scopes.h.
                      {
    timed_histogram()->Leave(previous_scope_);
    base::TimeTicks now = base::TimeTicks::Now();
    base::TimeDelta elapsed = timer_.Elapsed(now);
    histogram_->AddTimedSample(elapsed);
    if (isolate_) RecordLongTaskTime(elapsed);
#ifdef DEBUG
    // StopInternal() is called in the destructor and don't access timer_
    // after that.
    timer_.Stop();
#endif
    if (previous_scope_) previous_scope_->Resume(now);
  }
References v8::base::TimeTicks::Now().
timed_histogram()
NestedTimedHistogram* v8::internal::NestedTimedHistogramScope::timed_histogram () [inline], [private]
Definition at line 203 of file counters-scopes.h.
                                          {
    return static_cast<NestedTimedHistogram*>(histogram_);
  }
Member Data Documentation
isolate_
Isolate* v8::internal::NestedTimedHistogramScope::isolate_ [private]
Definition at line 208 of file counters-scopes.h.
NestedTimedHistogram
friend v8::internal::NestedTimedHistogramScope::NestedTimedHistogram [private]
Definition at line 152 of file counters-scopes.h.
PauseNestedTimedHistogramScope
friend v8::internal::NestedTimedHistogramScope::PauseNestedTimedHistogramScope [private]
Definition at line 153 of file counters-scopes.h.
previous_scope_
NestedTimedHistogramScope* v8::internal::NestedTimedHistogramScope::previous_scope_ [private]
Definition at line 207 of file counters-scopes.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/counters-scopes.h