v8::Object Class Reference
A JavaScript object (ECMA-262, 4.3.3)
#include <v8-object.h>
Classes
class Wrappable
struct WrapperTypeInfo
Public Member Functions
V8_WARN_UNUSED_RESULT Maybe< bool > Set (Local< Context > context, Local< Value > key, Local< Value > value)
Set only return Just(true) or Empty(), so if it should never fail, use result.Check().
V8_WARN_UNUSED_RESULT Maybe< bool > Set (Local< Context > context, Local< Value > key, Local< Value > value, MaybeLocal< Object > receiver)
V8_WARN_UNUSED_RESULT Maybe< bool > Set (Local< Context > context, uint32_t index, Local< Value > value)
V8_WARN_UNUSED_RESULT Maybe< bool > CreateDataProperty (Local< Context > context, Local< Name > key, Local< Value > value)
Implements CreateDataProperty(O, P, V), see https://tc39.es/ecma262/#sec-createdataproperty.
V8_WARN_UNUSED_RESULT Maybe< bool > CreateDataProperty (Local< Context > context, uint32_t index, Local< Value > value)
V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Local< Context > context, Local< Name > key, Local< Value > value, PropertyAttribute attributes=None)
Implements [[DefineOwnProperty]] for data property case, see https://tc39.es/ecma262/#table-essential-internal-methods.
V8_WARN_UNUSED_RESULT Maybe< bool > DefineProperty (Local< Context > context, Local< Name > key, PropertyDescriptor &descriptor)
Implements Object.defineProperty(O, P, Attributes), see https://tc39.es/ecma262/#sec-object.defineproperty.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Get (Local< Context > context, Local< Value > key)
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Get (Local< Context > context, Local< Value > key, MaybeLocal< Object > receiver)
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Get (Local< Context > context, uint32_t index)
V8_WARN_UNUSED_RESULT Maybe< PropertyAttribute > GetPropertyAttributes (Local< Context > context, Local< Value > key)
Gets the property attributes of a property which can be None or any combination of ReadOnly, DontEnum and DontDelete.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > GetOwnPropertyDescriptor (Local< Context > context, Local< Name > key)
Implements Object.getOwnPropertyDescriptor(O, P), see https://tc39.es/ecma262/#sec-object.getownpropertydescriptor.
V8_WARN_UNUSED_RESULT Maybe< bool > Has (Local< Context > context, Local< Value > key)
Object::Has() calls the abstract operation HasProperty(O, P), see https://tc39.es/ecma262/#sec-hasproperty.
V8_WARN_UNUSED_RESULT Maybe< bool > Delete (Local< Context > context, Local< Value > key)
V8_WARN_UNUSED_RESULT Maybe< bool > Has (Local< Context > context, uint32_t index)
V8_WARN_UNUSED_RESULT Maybe< bool > Delete (Local< Context > context, uint32_t index)
void SetAccessorProperty (Local< Name > name, Local< Function > getter, Local< Function > setter=Local< Function >(), PropertyAttribute attributes=None)
Sets an accessor property like Template::SetAccessorProperty, but this method sets on this object directly.
V8_WARN_UNUSED_RESULT Maybe< bool > SetNativeDataProperty (Local< Context > context, Local< Name > name, AccessorNameGetterCallback getter, AccessorNameSetterCallback setter=nullptr, Local< Value > data=Local< Value >(), PropertyAttribute attributes=None, SideEffectType getter_side_effect_type=SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type=SideEffectType::kHasSideEffect)
Sets a native data property like Template::SetNativeDataProperty, but this method sets on this object directly.
V8_WARN_UNUSED_RESULT Maybe< bool > SetLazyDataProperty (Local< Context > context, Local< Name > name, AccessorNameGetterCallback getter, Local< Value > data=Local< Value >(), PropertyAttribute attributes=None, SideEffectType getter_side_effect_type=SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type=SideEffectType::kHasSideEffect)
Attempts to create a property with the given name which behaves like a data property, except that the provided getter is invoked (and provided with the data value) to supply its value the first time it is read.
Maybe< bool > HasPrivate (Local< Context > context, Local< Private > key)
Functionality for private properties.
Maybe< bool > SetPrivate (Local< Context > context, Local< Private > key, Local< Value > value)
Maybe< bool > DeletePrivate (Local< Context > context, Local< Private > key)
MaybeLocal< Value > GetPrivate (Local< Context > context, Local< Private > key)
V8_WARN_UNUSED_RESULT MaybeLocal< Array > GetPropertyNames (Local< Context > context)
Returns an array containing the names of the enumerable properties of this object, including properties from prototype objects.
V8_WARN_UNUSED_RESULT MaybeLocal< Array > GetPropertyNames (Local< Context > context, KeyCollectionMode mode, PropertyFilter property_filter, IndexFilter index_filter, KeyConversionMode key_conversion=KeyConversionMode::kKeepNumbers)
V8_WARN_UNUSED_RESULT MaybeLocal< Array > GetOwnPropertyNames (Local< Context > context)
This function has the same functionality as GetPropertyNames but the returned array doesn't contain the names of properties from prototype objects.
V8_WARN_UNUSED_RESULT MaybeLocal< Array > GetOwnPropertyNames (Local< Context > context, PropertyFilter filter, KeyConversionMode key_conversion=KeyConversionMode::kKeepNumbers)
Returns an array containing the names of the filtered properties of this object, including properties from prototype objects.
V8 will stop providing access to hidden prototype(i.e. ` `JSGlobalObject). Use GetPrototypeV2() instead. ` `See http Local< Value > GetPrototypeV2 ()
Get the prototype object.
V8 will stop providing access to hidden prototype(i.e. ` `JSGlobalObject). Use SetPrototypeV2() instead. ` `See http V8_WARN_UNUSED_RESULT Maybe< bool > SetPrototypeV2 (Local< Context > context, Local< Value > prototype)
Set the prototype object.
Local< Object > FindInstanceInPrototypeChain (Local< FunctionTemplate > tmpl)
Finds an instance of the given function template in the prototype chain.
V8_WARN_UNUSED_RESULT MaybeLocal< String > ObjectProtoToString (Local< Context > context)
Call builtin Object.prototype.toString on this object.
Local< String > GetConstructorName ()
Returns the name of the function invoked as a constructor for this object.
Maybe< bool > SetIntegrityLevel (Local< Context > context, IntegrityLevel level)
Sets the integrity level of the object.
int InternalFieldCount () const
Gets the number of internal fields for this Object.
Local< Data > GetInternalField (int index)
Gets the data from an internal field.
void SetInternalField (int index, Local< Data > data)
Sets the data in an internal field.
void * GetAlignedPointerFromInternalField (int index)
Gets a 2-byte-aligned native pointer from an internal field.
void * GetAlignedPointerFromInternalField (v8::Isolate *isolate, int index)
void SetAlignedPointerInInternalField (int index, void *value)
Sets a 2-byte-aligned native pointer in an internal field.
void SetAlignedPointerInInternalFields (int argc, int indices[], void *values[])
V8_WARN_UNUSED_RESULT Maybe< bool > HasOwnProperty (Local< Context > context, Local< Name > key)
HasOwnProperty() is like JavaScript's Object.prototype.hasOwnProperty().
V8_WARN_UNUSED_RESULT Maybe< bool > HasOwnProperty (Local< Context > context, uint32_t index)
V8_WARN_UNUSED_RESULT Maybe< bool > HasRealNamedProperty (Local< Context > context, Local< Name > key)
Use HasRealNamedProperty() if you want to check if an object has an own property without causing side effects, i.e., without calling interceptors.
V8_WARN_UNUSED_RESULT Maybe< bool > HasRealIndexedProperty (Local< Context > context, uint32_t index)
V8_WARN_UNUSED_RESULT Maybe< bool > HasRealNamedCallbackProperty (Local< Context > context, Local< Name > key)
V8_WARN_UNUSED_RESULT MaybeLocal< Value > GetRealNamedPropertyInPrototypeChain (Local< Context > context, Local< Name > key)
If result.IsEmpty() no real property was located in the prototype chain.
V8_WARN_UNUSED_RESULT Maybe< PropertyAttribute > GetRealNamedPropertyAttributesInPrototypeChain (Local< Context > context, Local< Name > key)
Gets the property attributes of a real property in the prototype chain, which can be None or any combination of ReadOnly, DontEnum and DontDelete.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > GetRealNamedProperty (Local< Context > context, Local< Name > key)
If result.IsEmpty() no real property was located on the object or in the prototype chain.
V8_WARN_UNUSED_RESULT Maybe< PropertyAttribute > GetRealNamedPropertyAttributes (Local< Context > context, Local< Name > key)
Gets the property attributes of a real property which can be None or any combination of ReadOnly, DontEnum and DontDelete.
bool HasNamedLookupInterceptor () const
Tests for a named lookup interceptor.
bool HasIndexedLookupInterceptor () const
Tests for an index lookup interceptor.
int GetIdentityHash ()
Returns the identity hash for this object.
Local< Object > Clone (v8::Isolate *isolate)
Clone this object with a fast but shallow copy.
Local< Object > Clone ()
MaybeLocal< Context > GetCreationContext (v8::Isolate *isolate)
Returns the context in which the object was created.
Use the version with the isolate argument MaybeLocal< Context > GetCreationContext ()
Local< Context > GetCreationContextChecked (v8::Isolate *isolate)
Shortcut for GetCreationContext(...).ToLocalChecked().
Use the version with the isolate argument Local< Context > GetCreationContextChecked ()
void * GetAlignedPointerFromEmbedderDataInCreationContext (v8::Isolate *isolate, int index)
Gets the context in which the object was created (see GetCreationContext()) and if it's available reads respective embedder field value.
void * GetAlignedPointerFromEmbedderDataInCreationContext (int index)
bool IsCallable () const
Checks whether a callback is set by the ObjectTemplate::SetCallAsFunctionHandler method.
bool IsConstructor () const
True if this object is a constructor.
bool IsApiWrapper () const
Returns true if this object can be generally used to wrap object objects.
bool IsUndetectable () const
True if this object was created from an object template which was marked as undetectable.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > CallAsFunction (Local< Context > context, Local< Value > recv, int argc, Local< Value > argv[])
Call an Object as a function if a callback is set by the ObjectTemplate::SetCallAsFunctionHandler method.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > CallAsConstructor (Local< Context > context, int argc, Local< Value > argv[])
Call an Object as a constructor if a callback is set by the ObjectTemplate::SetCallAsFunctionHandler method.
Use Isolate::GetCurrent () instead
Return the isolate to which the Object belongs to.
Use Isolate::GetCurrent () instead
MaybeLocal< Array > PreviewEntries (bool *is_key_value)
If this object is a Set, Map, WeakSet or WeakMap, this returns a representation of the elements of this object as an array.
bool IsCodeLike (Isolate *isolate) const
Support for TC39 `dynamic code brand checks` proposal.
template<CppHeapPointerTag tag>
void Wrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper, void *wrappable)
template<CppHeapPointerTag tag>
void Wrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper, void *wrappable)
template<CppHeapPointerTag tag>
void Wrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper, void *wrappable)
Static Public Member Functions
static int InternalFieldCount (const PersistentBase< Object > &object)
Same as above, but works for PersistentBase.
static int InternalFieldCount (const BasicTracedReference< Object > &object)
Same as above, but works for BasicTracedReference.
static void * GetAlignedPointerFromInternalField (const PersistentBase< Object > &object, int index)
Same as above, but works for PersistentBase.
static void * GetAlignedPointerFromInternalField (const BasicTracedReference< Object > &object, int index)
Same as above, but works for TracedReference.
template<CppHeapPointerTag tag, typename T = void>
static T * Unwrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper)
Unwraps a JS wrapper object.
template<CppHeapPointerTag tag, typename T = void>
static T * Unwrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper)
template<CppHeapPointerTag tag, typename T = void>
static T * Unwrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper)
template<typename T = void>
static T * Unwrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper, CppHeapPointerTagRange tag_range)
template<typename T = void>
static T * Unwrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper, CppHeapPointerTagRange tag_range)
template<typename T = void>
static T * Unwrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper, CppHeapPointerTagRange tag_range)
template<CppHeapPointerTag tag>
Use Wrap with Wrappable *wrappable static instead void Wrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper, void *wrappable)
Wraps a JS wrapper with a C++ instance.
template<CppHeapPointerTag tag>
Use Wrap with Wrappable *wrappable static instead void Wrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper, void *wrappable)
template<CppHeapPointerTag tag>
Use Wrap with Wrappable *wrappable static instead void Wrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper, void *wrappable)
Use Wrap with Wrappable *wrappable static instead void Wrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper, void *wrappable, CppHeapPointerTag tag)
Use Wrap with Wrappable *wrappable static instead void Wrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper, void *wrappable, CppHeapPointerTag tag)
Use Wrap with Wrappable *wrappable static instead void Wrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper, void *wrappable, CppHeapPointerTag tag)
template<CppHeapPointerTag tag>
static void Wrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper, Wrappable *wrappable)
template<CppHeapPointerTag tag>
static void Wrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper, Wrappable *wrappable)
template<CppHeapPointerTag tag>
static void Wrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper, Wrappable *wrappable)
static void Wrap (v8::Isolate *isolate, const v8::Local< v8::Object > &wrapper, Wrappable *wrappable, CppHeapPointerTag tag)
static void Wrap (v8::Isolate *isolate, const PersistentBase< Object > &wrapper, Wrappable *wrappable, CppHeapPointerTag tag)
static void Wrap (v8::Isolate *isolate, const BasicTracedReference< Object > &wrapper, Wrappable *wrappable, CppHeapPointerTag tag)
static MaybeLocal< Context > GetCreationContext (v8::Isolate *isolate, const PersistentBase< Object > &object)
Same as above, but works for Persistents.
Use the version with the isolate static argument MaybeLocal< Context > GetCreationContext (const PersistentBase< Object > &object)
static Local< Object > New (Isolate *isolate)
static Local< Object > New (Isolate *isolate, Local< Value > prototype_or_null, Local< Name > *names, Local< Value > *values, size_t length)
Creates a JavaScript object with the given properties, and a the given prototype_or_null (which can be any JavaScript value, and if it's null, the newly created object won't have a prototype at all).
static Object * Cast (Value *obj)
Public Attributes
Use which is guaranteed to return the same isolate since https: Isolate* GetIsolate()
Private Member Functions
Object ()
Local< Data > SlowGetInternalField (int index)
void * SlowGetAlignedPointerFromInternalField (int index)
void * SlowGetAlignedPointerFromInternalField (v8::Isolate *isolate, int index)
Static Private Member Functions
static void * Unwrap (v8::Isolate *isolate, internal::Address wrapper_obj, CppHeapPointerTagRange tag_range)
static void Wrap (v8::Isolate *isolate, internal::Address wrapper_obj, CppHeapPointerTag tag, void *wrappable)
static void CheckCast (Value *obj)
Detailed Description
A JavaScript object (ECMA-262, 4.3.3)
Definition at line 235 of file v8-object.h.
Constructor & Destructor Documentation
Object()
v8::Object::Object () [private]
Member Function Documentation
CallAsConstructor()
MaybeLocal< Value > v8::Object::CallAsConstructor (Local< Context > context, int argc, Local< Value > argv[])
Call an Object as a constructor if a callback is set by the ObjectTemplate::SetCallAsFunctionHandler method.
Note: This method behaves like the Function::NewInstance method.
Definition at line 5282 of file api.cc.
                                                                 {
  auto i_isolate = i::Isolate::Current();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.Execute");
  EnterV8Scope<InternalEscapableScope> api_scope{
      i_isolate, context, RCCId::kAPI_Object_CallAsConstructor};
  i::TimerEventScope<i::TimerEventExecute> timer_scope(i_isolate);
  i::NestedTimedHistogramScope execute_timer(i_isolate->counters()->execute(),
                                             i_isolate);
  auto self = Utils::OpenDirectHandle(this);
  auto args = PrepareArguments(argc, argv);
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Execution::New(i_isolate, self, self, args)));
}
References v8::base::args, v8::internal::Isolate::counters(), v8::internal::Isolate::Current(), v8::internal::Execution::New(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::PrepareArguments(), v8::Utils::ToMaybeLocal(), and TRACE_EVENT_CALL_STATS_SCOPED.
CallAsFunction()
MaybeLocal< Value > v8::Object::CallAsFunction (Local< Context > context, Local< Value > recv, int argc, Local< Value > argv[])
Call an Object as a function if a callback is set by the ObjectTemplate::SetCallAsFunctionHandler method.
Definition at line 5265 of file api.cc.
                                                              {
  auto i_isolate = i::Isolate::Current();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.Execute");
  EnterV8Scope<InternalEscapableScope> api_scope{
      i_isolate, context, RCCId::kAPI_Object_CallAsFunction};
  i::TimerEventScope<i::TimerEventExecute> timer_scope(i_isolate);
  i::NestedTimedHistogramScope execute_timer(i_isolate->counters()->execute(),
                                             i_isolate);
  auto self = Utils::OpenDirectHandle(this);
  auto recv_obj = Utils::OpenDirectHandle(*recv);
  auto args = PrepareArguments(argc, argv);
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Execution::Call(i_isolate, self, recv_obj, args)));
}
References v8::base::args, v8::internal::Execution::Call(), v8::internal::Isolate::counters(), v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::PrepareArguments(), v8::Utils::ToMaybeLocal(), and TRACE_EVENT_CALL_STATS_SCOPED.
Cast()
Object * v8::Object::Cast (v8::Value * value) [inline], [static]
Definition at line 1178 of file v8-object.h.
                                   {
#ifdef V8_ENABLE_CHECKS
  CheckCast(value);
#endif
  return static_cast<Object*>(value);
}
References CheckCast(), and v8::internal::value.
CheckCast()
void v8::Object::CheckCast (Value * obj) [static], [private]
Definition at line 3863 of file api.cc.
                                    {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSReceiver(*obj), "v8::Object::Cast",
                  "Value is not an Object");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
Clone() [1/2]
Local< v8::Object > v8::Object::Clone ()
Definition at line 5117 of file api.cc.
                                {
  return Clone(reinterpret_cast<v8::Isolate*>(i::Isolate::Current()));
}
References v8::internal::Isolate::Current().
Clone() [2/2]
Local< v8::Object > v8::Object::Clone (v8::Isolate * isolate)
Clone this object with a fast but shallow copy.
Values will point to the same values as the original object.
Prefer using version with Isolate parameter.
Definition at line 5108 of file api.cc.
                                                {
  auto self = i::Cast<i::JSObject>(Utils::OpenDirectHandle(this));
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::JSObject> result =
      i_isolate->factory()->CopyJSObject(self);
  return Utils::ToLocal(result);
}
References v8::internal::Factory::CopyJSObject(), v8::internal::Isolate::factory(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
CreateDataProperty() [1/2]
Maybe< bool > v8::Object::CreateDataProperty (Local< Context > context, v8::Local< Name > key, v8::Local< Value > value)
Implements CreateDataProperty(O, P, V), see https://tc39.es/ecma262/#sec-createdataproperty.
Defines a configurable, writable, enumerable property with the given value on the object unless the property already exists and is not configurable or the object is not extensible.
Returns true on success.
Definition at line 4351 of file api.cc.
                                                                 {
  auto i_isolate = i::Isolate::Current();
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  auto value_obj = Utils::OpenDirectHandle(*value);
  i::PropertyKey lookup_key(i_isolate, key_obj);
  if (i::IsJSObject(*self)) {
    EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                     RCCId::kAPI_Object_CreateDataProperty};
    return i::JSObject::CreateDataProperty(
        i_isolate, i::Cast<i::JSObject>(self), lookup_key, value_obj,
        Just(i::kDontThrow));
  }
  // JSProxy or WasmObject or other non-JSObject.
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_CreateDataProperty};
  return i::JSReceiver::CreateDataProperty(i_isolate, self, lookup_key,
                                           value_obj, Just(i::kDontThrow));
}
References v8::internal::JSObject::CreateDataProperty(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::Isolate::Current(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8_inspector::createDataProperty(), and v8::Shell::HostInitializeImportMetaObject().
CreateDataProperty() [2/2]
Maybe< bool > v8::Object::CreateDataProperty (Local< Context > context, uint32_t index, v8::Local< Value > value)
Definition at line 4374 of file api.cc.
                                                                 {
  auto i_isolate = i::Isolate::Current();
  auto self = Utils::OpenDirectHandle(this);
  auto value_obj = Utils::OpenDirectHandle(*value);
  i::PropertyKey lookup_key(i_isolate, index);
  if (i::IsJSObject(*self)) {
    EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                     RCCId::kAPI_Object_CreateDataProperty};
    return i::JSObject::CreateDataProperty(
        i_isolate, i::Cast<i::JSObject>(self), lookup_key, value_obj,
        Just(i::kDontThrow));
  }
  // JSProxy or WasmObject or other non-JSObject.
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_CreateDataProperty};
  return i::JSReceiver::CreateDataProperty(i_isolate, self, lookup_key,
                                           value_obj, Just(i::kDontThrow));
}
References v8::internal::JSObject::CreateDataProperty(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::Isolate::Current(), v8::internal::index, v8::Just(), v8::internal::kDontThrow, v8::Utils::OpenDirectHandle(), and v8::internal::value.
DefineOwnProperty()
Maybe< bool > v8::Object::DefineOwnProperty (Local< Context > context, v8::Local< Name > key, v8::Local< Value > value, v8::PropertyAttribute attributes = None)
Implements [[DefineOwnProperty]] for data property case, see https://tc39.es/ecma262/#table-essential-internal-methods.
In general, CreateDataProperty will be faster, however, does not allow for specifying attributes.
Returns true on success.
Definition at line 4491 of file api.cc.
                                                                          {
  auto i_isolate = i::Isolate::Current();
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  auto value_obj = Utils::OpenDirectHandle(*value);
  i::PropertyDescriptor desc;
  desc.set_writable(!(attributes & v8::ReadOnly));
  desc.set_enumerable(!(attributes & v8::DontEnum));
  desc.set_configurable(!(attributes & v8::DontDelete));
  desc.set_value(i::Cast<i::JSAny>(value_obj));
  if (i::IsJSObject(*self)) {
    // If it's not a JSProxy, i::JSReceiver::DefineOwnProperty should never run
    // a script.
    EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                     RCCId::kAPI_Object_DefineOwnProperty};
    return i::JSReceiver::DefineOwnProperty(i_isolate, self, key_obj, &desc,
                                            Just(i::kDontThrow));
  }
  // JSProxy or WasmObject or other non-JSObject.
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_DefineOwnProperty};
  // Even though we said kDontThrow, there might be accessors that do throw.
  return i::JSReceiver::DefineOwnProperty(i_isolate, self, key_obj, &desc,
                                          Just(i::kDontThrow));
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::DefineOwnProperty(), v8::DontDelete, v8::DontEnum, v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::Utils::OpenDirectHandle(), v8::ReadOnly, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and v8::internal::value.
Referenced by v8::Shell::PerformanceMark(), and v8::Shell::PerformanceMeasure().
DefineProperty()
Maybe< bool > v8::Object::DefineProperty (Local< Context > context, v8::Local< Name > key, PropertyDescriptor & descriptor)
Implements Object.defineProperty(O, P, Attributes), see https://tc39.es/ecma262/#sec-object.defineproperty.
The defineProperty function is used to add an own property or update the attributes of an existing own property of an object.
Both data and accessor descriptors can be used.
In general, CreateDataProperty is faster, however, does not allow for specifying attributes or an accessor descriptor.
The PropertyDescriptor can change when redefining a property.
Returns true on success.
Definition at line 4522 of file api.cc.
                                                                       {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_DefineOwnProperty};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  return i::JSReceiver::DefineOwnProperty(i_isolate, self, key_obj,
                                          &descriptor.get_private()->desc,
                                          Just(i::kDontThrow));
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::DefineOwnProperty(), v8::PropertyDescriptor::PrivateData::desc, v8::PropertyDescriptor::get_private(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, and v8::Utils::OpenDirectHandle().
Delete() [1/2]
Maybe< bool > v8::Object::Delete (Local< Context > context, Local< Value > key)
Definition at line 4810 of file api.cc.
                                                                     {
  auto i_isolate = i::Isolate::Current();
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  if (i::IsJSProxy(*self)) {
    EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Delete};
    return i::Runtime::DeleteObjectProperty(i_isolate, self, key_obj,
                                            i::LanguageMode::kSloppy);
  } else {
    // If it's not a JSProxy, i::Runtime::DeleteObjectProperty should never run
    // a script.
    DCHECK(i::IsJSObject(*self) || i::IsWasmObject(*self));
    EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                     RCCId::kAPI_Object_Delete};
    return i::Runtime::DeleteObjectProperty(i_isolate, self, key_obj,
                                            i::LanguageMode::kSloppy);
  }
}
References v8::internal::Isolate::Current(), DCHECK, v8::internal::Runtime::DeleteObjectProperty(), v8::internal::IsWasmObject(), v8::internal::key, and v8::Utils::OpenDirectHandle().
Delete() [2/2]
Maybe< bool > v8::Object::Delete (Local< Context > context, uint32_t index)
Definition at line 4864 of file api.cc.
                                                                   {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Delete};
  auto self = Utils::OpenDirectHandle(this);
  return i::JSReceiver::DeleteElement(i_isolate, self, index);
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::DeleteElement(), v8::internal::index, and v8::Utils::OpenDirectHandle().
DeletePrivate()
Maybe< bool > v8::Object::DeletePrivate (Local< Context > context, Local< Private > key)
Definition at line 4829 of file api.cc.
                                                          {
  auto i_isolate = i::Isolate::Current();
  // In case of private symbols, i::Runtime::DeleteObjectProperty does not run
  // any author script.
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Object_Delete};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  return i::Runtime::DeleteObjectProperty(i_isolate, self, key_obj,
                                          i::LanguageMode::kSloppy);
}
References v8::internal::Isolate::Current(), v8::internal::Runtime::DeleteObjectProperty(), v8::internal::key, and v8::Utils::OpenDirectHandle().
FindInstanceInPrototypeChain()
Local< Object > v8::Object::FindInstanceInPrototypeChain (v8::Local< FunctionTemplate > tmpl)
Finds an instance of the given function template in the prototype chain.
Definition at line 4714 of file api.cc.
                                    {
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = i::Isolate::Current();
  i::PrototypeIterator iter(i_isolate, *self, i::kStartAtReceiver);
  i::Tagged<i::FunctionTemplateInfo> tmpl_info =
      *Utils::OpenDirectHandle(*tmpl);
  if (!IsJSObject(iter.GetCurrent())) return {};
  while (!tmpl_info->IsTemplateFor(iter.GetCurrent<i::JSObject>())) {
    iter.Advance();
    if (iter.IsAtEnd()) return {};
    if (!IsJSObject(iter.GetCurrent())) return {};
  }
  // IsTemplateFor() ensures that iter.GetCurrent() can't be a Proxy here.
  return Utils::ToLocal(
      i::direct_handle(iter.GetCurrent<i::JSObject>(), i_isolate));
}
References v8::internal::PrototypeIterator::Advance(), v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::kStartAtReceiver, and v8::Utils::OpenDirectHandle().
Get() [1/3]
MaybeLocal< Value > v8::Object::Get (Local< Context > context, Local< Value > key)
Definition at line 4568 of file api.cc.
                                                    {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_Get};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  return api_scope.EscapeMaybe(
      i::Runtime::GetObjectProperty(i_isolate, self, key_obj));
}
References v8::internal::Runtime::GetObjectProperty(), v8::internal::key, and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append(), v8_inspector::arrayToProtocolValue(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8::Shell::CreateEvaluationContext(), v8::Shell::DoHostImportModuleDynamically(), v8::Worker::ExecuteInThread(), v8_inspector::generateCustomPreview(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::getEntries(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::ValueMirror::getInternalProperties(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetOptionalAddressValue(), v8_inspector::ValueMirror::getProperties(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8_inspector::objectToProtocolValue(), v8::Shell::PerformanceMeasure(), v8::Worker::ProcessMessage(), v8_inspector::V8Console::queryObjectsCallback(), v8::InspectorClient::runMessageLoopOnPause(), v8::InspectorFrontend::Send(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8_inspector::V8Console::valuesCallback(), v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), and v8_inspector::InjectedScript::wrapTable().
Get() [2/3]
MaybeLocal< Value > v8::Object::Get (Local< Context > context, Local< Value > key, MaybeLocal< Object > receiver)
Definition at line 4578 of file api.cc.
                                                               {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_Get};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  i::DirectHandle<i::JSReceiver> receiver_obj;
  if (!receiver.IsEmpty()) {
    receiver_obj = Utils::OpenDirectHandle(*receiver.ToLocalChecked());
  }
  return api_scope.EscapeMaybe(
      i::Runtime::GetObjectProperty(i_isolate, self, key_obj, receiver_obj));
}
References v8::internal::Runtime::GetObjectProperty(), v8::MaybeLocal< T >::IsEmpty(), v8::internal::key, v8::Utils::OpenDirectHandle(), and v8::MaybeLocal< T >::ToLocalChecked().
Get() [3/3]
MaybeLocal< Value > v8::Object::Get (Local< Context > context, uint32_t index)
Definition at line 4592 of file api.cc.
                                                                      {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_Get};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  return api_scope.EscapeMaybe(
      i::JSReceiver::GetElement(i_isolate, self, index));
}
References v8::internal::JSReceiver::GetElement(), v8::internal::index, and v8::Utils::OpenDirectHandle().
GetAlignedPointerFromEmbedderDataInCreationContext() [1/2]
void * v8::Object::GetAlignedPointerFromEmbedderDataInCreationContext (int index)
Definition at line 5217 of file api.cc.
               {
  auto self = Utils::OpenDirectHandle(this);
  i::IsolateForSandbox isolate = i::GetCurrentIsolateForSandbox();
  return GetAlignedPointerFromEmbedderDataInCreationContextImpl(self, isolate,
                                                                index);
}
References v8::anonymous_namespace{api.cc}::GetAlignedPointerFromEmbedderDataInCreationContextImpl(), v8::internal::GetCurrentIsolateForSandbox(), v8::internal::index, and v8::Utils::OpenDirectHandle().
GetAlignedPointerFromEmbedderDataInCreationContext() [2/2]
void * v8::Object::GetAlignedPointerFromEmbedderDataInCreationContext (v8::Isolate * isolate, int index)
Gets the context in which the object was created (see GetCreationContext()) and if it's available reads respective embedder field value.
If the context can't be obtained nullptr is returned. Basically it's a shortcut for obj->GetCreationContext().GetAlignedPointerFromEmbedderData(index) which doesn't create a handle for Context object on the way and doesn't try to expand the embedder data attached to the context. In case the Local<Context> is already available because of other reasons, it's fine to keep using Context::GetAlignedPointerFromEmbedderData().
Prefer using version with Isolate parameter if you have an Isolate, otherwise use the other one.
Definition at line 5209 of file api.cc.
                                   {
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  return GetAlignedPointerFromEmbedderDataInCreationContextImpl(self, i_isolate,
                                                                index);
}
References v8::anonymous_namespace{api.cc}::GetAlignedPointerFromEmbedderDataInCreationContextImpl(), v8::internal::index, and v8::Utils::OpenDirectHandle().
GetAlignedPointerFromInternalField() [1/4]
static void* v8::Object::GetAlignedPointerFromInternalField (const BasicTracedReference< Object > & object, int index) [inline], [static]
Same as above, but works for TracedReference.
Definition at line 538 of file v8-object.h.
                                                             {
    return object.template value<Object>()->GetAlignedPointerFromInternalField(
        index);
  }
References v8::internal::index.
GetAlignedPointerFromInternalField() [2/4]
static void* v8::Object::GetAlignedPointerFromInternalField (const PersistentBase< Object > & object, int index) [inline], [static]
Same as above, but works for PersistentBase.
Definition at line 531 of file v8-object.h.
                                                       {
    return object.template value<Object>()->GetAlignedPointerFromInternalField(
        index);
  }
References v8::internal::index.
GetAlignedPointerFromInternalField() [3/4]
void * v8::Object::GetAlignedPointerFromInternalField (int index) [inline]
Gets a 2-byte-aligned native pointer from an internal field.
This field must have been set by SetAlignedPointerInInternalField, everything else leads to undefined behavior.
Definition at line 962 of file v8-object.h.
                                                          {
#if !defined(V8_ENABLE_CHECKS)
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  // Fast path: If the object is a plain JSObject, which is the common case, we
  // know where to find the internal fields and can return the value directly.
  auto instance_type = I::GetInstanceType(obj);
  if (V8_LIKELY(I::CanHaveInternalField(instance_type))) {
    int offset = I::kJSAPIObjectWithEmbedderSlotsHeaderSize +
                 (I::kEmbedderDataSlotSize * index) +
                 I::kEmbedderDataSlotExternalPointerOffset;
    Isolate* isolate = I::GetCurrentIsolateForSandbox();
    A value =
        I::ReadExternalPointerField<internal::kEmbedderDataSlotPayloadTag>(
            isolate, obj, offset);
    return reinterpret_cast<void*>(value);
  }
#endif
  return SlowGetAlignedPointerFromInternalField(index);
}
References v8::internal::A, v8::internal::GetCurrentIsolateForSandbox(), I, v8::internal::index, v8::internal::kEmbedderDataSlotSize, SlowGetAlignedPointerFromInternalField(), V8_LIKELY, v8::internal::value, and v8::internal::ValueHelper::ValueAsAddress().
GetAlignedPointerFromInternalField() [4/4]
void * v8::Object::GetAlignedPointerFromInternalField (v8::Isolate * isolate, int index) [inline]
Definition at line 940 of file v8-object.h.
                                                            {
#if !defined(V8_ENABLE_CHECKS)
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  // Fast path: If the object is a plain JSObject, which is the common case, we
  // know where to find the internal fields and can return the value directly.
  auto instance_type = I::GetInstanceType(obj);
  if (V8_LIKELY(I::CanHaveInternalField(instance_type))) {
    int offset = I::kJSAPIObjectWithEmbedderSlotsHeaderSize +
                 (I::kEmbedderDataSlotSize * index) +
                 I::kEmbedderDataSlotExternalPointerOffset;
    A value =
        I::ReadExternalPointerField<internal::kEmbedderDataSlotPayloadTag>(
            isolate, obj, offset);
    return reinterpret_cast<void*>(value);
  }
#endif
  return SlowGetAlignedPointerFromInternalField(isolate, index);
}
References v8::internal::A, I, v8::internal::index, v8::internal::kEmbedderDataSlotSize, SlowGetAlignedPointerFromInternalField(), V8_LIKELY, v8::internal::value, and v8::internal::ValueHelper::ValueAsAddress().
GetConstructorName()
Local< String > v8::Object::GetConstructorName ()
Returns the name of the function invoked as a constructor for this object.
Definition at line 4784 of file api.cc.
                                           {
  // TODO(v8:12547): Consider adding GetConstructorName(Local<Context>).
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate;
  if (i::HeapLayout::InWritableSharedSpace(*self)) {
    i_isolate = i::Isolate::Current();
  } else {
    i_isolate = i::Isolate::Current();
  }
  i::DirectHandle<i::String> name =
      i::JSReceiver::GetConstructorName(i_isolate, self);
  return Utils::ToLocal(name);
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::GetConstructorName(), v8::internal::HeapLayout::InWritableSharedSpace(), name, and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), and v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForObject().
GetCreationContext() [1/4]
MaybeLocal< v8::Context > v8::Object::GetCreationContext ()
Definition at line 5138 of file api.cc.
                                                   {
  auto self = Utils::OpenDirectHandle(this);
  return GetCreationContextImpl(self, i::Isolate::Current());
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::GetCreationContextImpl(), and v8::Utils::OpenDirectHandle().
GetCreationContext() [2/4]
MaybeLocal< v8::Context > v8::Object::GetCreationContext (const PersistentBase< Object > & object) [inline], [static]
Definition at line 5143 of file api.cc.
                                          {
  return object.template value<Object>()->GetCreationContext(
      Isolate::GetCurrent());
}
References v8::Isolate::GetCurrent().
GetCreationContext() [3/4]
MaybeLocal< v8::Context > v8::Object::GetCreationContext (v8::Isolate * isolate)
Returns the context in which the object was created.
Prefer using version with Isolate parameter.
Definition at line 5132 of file api.cc.
                                                                     {
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  return GetCreationContextImpl(self, i_isolate);
}
References v8::anonymous_namespace{api.cc}::GetCreationContextImpl(), and v8::Utils::OpenDirectHandle().
Referenced by v8::CreateFastCAPIObject(), v8_inspector::generateCustomPreview(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), and v8::Shell::RealmOwner().
GetCreationContext() [4/4]
static MaybeLocal<Context> v8::Object::GetCreationContext (v8::Isolate * isolate, const PersistentBase< Object > & object) [inline], [static]
Same as above, but works for Persistents.
Definition at line 773 of file v8-object.h.
                                                                {
    return object.template value<Object>()->GetCreationContext(isolate);
  }
GetCreationContextChecked() [1/2]
Local< v8::Context > v8::Object::GetCreationContextChecked ()
Definition at line 5166 of file api.cc.
                                                     {
  auto self = Utils::OpenDirectHandle(this);
  return GetCreationContextCheckedImpl(self, i::Isolate::Current());
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::GetCreationContextCheckedImpl(), and v8::Utils::OpenDirectHandle().
GetCreationContextChecked() [2/2]
Local< v8::Context > v8::Object::GetCreationContextChecked (v8::Isolate * isolate)
Shortcut for GetCreationContext(...).ToLocalChecked().
Prefer using version with Isolate parameter.
Definition at line 5160 of file api.cc.
                                                                       {
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  return GetCreationContextCheckedImpl(self, i_isolate);
}
References v8::anonymous_namespace{api.cc}::GetCreationContextCheckedImpl(), and v8::Utils::OpenDirectHandle().
GetIdentityHash()
int v8::Object::GetIdentityHash ()
Returns the identity hash for this object.
The current implementation uses a hidden property on the object to store the identity hash.
The return value will never be 0. Also, it is not guaranteed to be unique.
Definition at line 5225 of file api.cc.
                              {
  i::DisallowGarbageCollection no_gc;
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return self->GetOrCreateIdentityHash(i_isolate).value();
}
References v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
GetInternalField()
Local< Data > v8::Object::GetInternalField (int index) [inline]
Gets the data from an internal field.
To cast the return value into v8::Value subtypes, it needs to be casted to a v8::Value first. For example, to cast it into v8::External:
object->GetInternalField(index).As<v8::Value>().As<v8::External>();
The embedder should make sure that the internal field being retrieved using this method has already been set with SetInternalField() before.
Definition at line 915 of file v8-object.h.
                                              {
#ifndef V8_ENABLE_CHECKS
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  // Fast path: If the object is a plain JSObject, which is the common case, we
  // know where to find the internal fields and can return the value directly.
  int instance_type = I::GetInstanceType(obj);
  if (I::CanHaveInternalField(instance_type)) {
    int offset = I::kJSAPIObjectWithEmbedderSlotsHeaderSize +
                 (I::kEmbedderDataSlotSize * index);
    A value = I::ReadRawField<A>(obj, offset);
#ifdef V8_COMPRESS_POINTERS
    // We read the full pointer value and then decompress it in order to avoid
    // dealing with potential endiannes issues.
    value = I::DecompressTaggedField(obj, static_cast<uint32_t>(value));
#endif
    auto* isolate = I::GetCurrentIsolate();
    return Local<Data>::New(isolate, value);
  }
#endif
  return SlowGetInternalField(index);
}
References v8::internal::A, v8::internal::GetCurrentIsolate(), I, v8::internal::index, v8::internal::kEmbedderDataSlotSize, v8::Local< T >::New(), SlowGetInternalField(), v8::internal::value, and v8::internal::ValueHelper::ValueAsAddress().
Referenced by v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), and v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook().
GetOwnPropertyDescriptor()
MaybeLocal< Value > v8::Object::GetOwnPropertyDescriptor (Local< Context > context, Local< Name > key)
Implements Object.getOwnPropertyDescriptor(O, P), see https://tc39.es/ecma262/#sec-object.getownpropertydescriptor.
Definition at line 4624 of file api.cc.
                                                                        {
  PrepareForExecutionScope api_scope{
      context, RCCId::kAPI_Object_GetOwnPropertyDescriptor};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto obj = Utils::OpenDirectHandle(this);
  auto key_name = Utils::OpenDirectHandle(*key);
  i::PropertyDescriptor desc;
  Maybe<bool> found =
      i::JSReceiver::GetOwnPropertyDescriptor(i_isolate, obj, key_name, &desc);
  if (found.IsNothing()) return {};
  if (!found.FromJust()) {
    return v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
  }
  return api_scope.Escape(Utils::ToLocal(desc.ToObject(i_isolate)));
}
References v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::Maybe< T >::IsNothing(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::PropertyDescriptor::ToObject(), and v8::Undefined().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty().
GetOwnPropertyNames() [1/2]
MaybeLocal< Array > v8::Object::GetOwnPropertyNames (Local< Context > context)
This function has the same functionality as GetPropertyNames but the returned array doesn't contain the names of properties from prototype objects.
Definition at line 4763 of file api.cc.
                                                                      {
  return GetOwnPropertyNames(
      context, static_cast<v8::PropertyFilter>(ONLY_ENUMERABLE | SKIP_SYMBOLS));
}
References v8::ONLY_ENUMERABLE, and v8::SKIP_SYMBOLS.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8_inspector::V8Console::keysCallback(), v8_inspector::objectToProtocolValue(), and v8_inspector::V8Console::valuesCallback().
GetOwnPropertyNames() [2/2]
MaybeLocal< Array > v8::Object::GetOwnPropertyNames (Local< Context > context, PropertyFilter filter, KeyConversionMode key_conversion = KeyConversionMode::kKeepNumbers)
Returns an array containing the names of the filtered properties of this object, including properties from prototype objects.
The array returned by this method contains the same values as would be enumerated by a for-in statement over this object.
Definition at line 4768 of file api.cc.
                                      {
  return GetPropertyNames(context, KeyCollectionMode::kOwnOnly, filter,
                          v8::IndexFilter::kIncludeIndices, key_conversion);
}
References v8::kIncludeIndices, and v8::kOwnOnly.
GetPrivate()
MaybeLocal< Value > v8::Object::GetPrivate (Local< Context > context, Local< Private > key)
Definition at line 4600 of file api.cc.
                                                             {
  return Get(context, key.UnsafeAs<Value>());
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::key.
GetPropertyAttributes()
Maybe< PropertyAttribute > v8::Object::GetPropertyAttributes (Local< Context > context, Local< Value > key)
Gets the property attributes of a property which can be None or any combination of ReadOnly, DontEnum and DontDelete.
Returns None when the property doesn't exist.
Definition at line 4605 of file api.cc.
                                              {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_GetPropertyAttributes};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  if (!i::IsName(*key_obj)) {
    if (!i::Object::ToString(i_isolate, key_obj).ToHandle(&key_obj)) return {};
  }
  auto key_name = i::Cast<i::Name>(key_obj);
  auto result = i::JSReceiver::GetPropertyAttributes(i_isolate, self, key_name);
  if (result.IsNothing()) return {};
  if (result.FromJust() == i::ABSENT) {
    return Just(static_cast<PropertyAttribute>(i::NONE));
  }
  return Just(static_cast<PropertyAttribute>(result.FromJust()));
}
References v8::internal::ABSENT, v8::internal::Isolate::Current(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::Just(), v8::internal::key, v8::internal::NONE, v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::anonymous_namespace{api.cc}::ToHandle(), and ToString().
GetPropertyNames() [1/2]
MaybeLocal< Array > v8::Object::GetPropertyNames (Local< Context > context)
Returns an array containing the names of the enumerable properties of this object, including properties from prototype objects.
The array returned by this method contains the same values as would be enumerated by a for-in statement over this object.
Definition at line 4732 of file api.cc.
                                                                   {
  return GetPropertyNames(
      context, v8::KeyCollectionMode::kIncludePrototypes,
      static_cast<v8::PropertyFilter>(ONLY_ENUMERABLE | SKIP_SYMBOLS),
      v8::IndexFilter::kIncludeIndices);
}
References v8::kIncludeIndices, v8::kIncludePrototypes, v8::ONLY_ENUMERABLE, and v8::SKIP_SYMBOLS.
GetPropertyNames() [2/2]
MaybeLocal< Array > v8::Object::GetPropertyNames (Local< Context > context, KeyCollectionMode mode, PropertyFilter property_filter, IndexFilter index_filter, KeyConversionMode key_conversion = KeyConversionMode::kKeepNumbers)
Definition at line 4739 of file api.cc.
                                      {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_Object_GetPropertyNames};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::FixedArray> value;
  i::KeyAccumulator accumulator(
      i_isolate, static_cast<i::KeyCollectionMode>(mode),
      static_cast<i::PropertyFilter>(property_filter));
  accumulator.set_skip_indices(index_filter == IndexFilter::kSkipIndices);
  if (accumulator.CollectKeys(self, self).IsNothing()) return {};
  value =
      accumulator.GetKeys(static_cast<i::GetKeysConversion>(key_conversion));
  DCHECK(self->map()->EnumLength() == i::kInvalidEnumCacheSentinel ||
         self->map()->EnumLength() == 0 ||
         self->map()->instance_descriptors(i_isolate)->enum_cache()->keys() !=
             *value);
  auto result = i_isolate->factory()->NewJSArrayWithElements(value);
  return api_scope.Escape(Utils::ToLocal(result));
}
References v8::internal::KeyAccumulator::CollectKeys(), DCHECK, v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::kInvalidEnumCacheSentinel, v8::kSkipIndices, mode(), v8::internal::Factory::NewJSArrayWithElements(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, v8::internal::KeyAccumulator::set_skip_indices(), and v8::internal::value.
GetPrototypeV2()
Local< Value > v8::Object::GetPrototypeV2 ()
Get the prototype object.
This does not skip objects marked to be skipped by proto and it does not consult the security handler. Get the prototype object (same as getting proto property). This does not consult the security handler. TODO(333672197): rename back to GetPrototype() once the old version goes through the deprecation process and is removed.
Definition at line 4649 of file api.cc.
                                      {
  auto self = Utils::OpenDirectHandle(this);
  auto i_isolate = i::Isolate::Current();
  i::PrototypeIterator iter(i_isolate, self);
  if (i::IsJSGlobalProxy(*self)) {
    // Skip hidden prototype (i.e. JSGlobalObject).
    iter.Advance();
  }
  DCHECK(!i::IsJSGlobalObject(*i::PrototypeIterator::GetCurrent(iter)));
  return Utils::ToLocal(i::PrototypeIterator::GetCurrent(iter));
}
References v8::internal::PrototypeIterator::Advance(), v8::internal::Isolate::Current(), DCHECK, v8::internal::PrototypeIterator::GetCurrent(), and v8::Utils::OpenDirectHandle().
GetRealNamedProperty()
MaybeLocal< Value > v8::Object::GetRealNamedProperty (Local< Context > context, Local< Name > key)
If result.IsEmpty() no real property was located on the object or in the prototype chain.
This means interceptors in the prototype chain are not called.
Definition at line 5073 of file api.cc.
                                                                    {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_Object_GetRealNamedProperty};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  i::PropertyKey lookup_key(i_isolate, key_obj);
  i::LookupIterator it(i_isolate, self, lookup_key, self,
                       i::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  MaybeLocal<Value> result = Utils::ToMaybeLocal(i::Object::GetProperty(&it));
  if (!it.IsFound()) return {};
  return api_scope.EscapeMaybe(result);
}
References v8::internal::Object::GetProperty(), v8::internal::LookupIterator::IsFound(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, v8::base::internal::result, and v8::Utils::ToMaybeLocal().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethod(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScope(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), and v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback().
GetRealNamedPropertyAttributes()
Maybe< PropertyAttribute > v8::Object::GetRealNamedPropertyAttributes (Local< Context > context, Local< Name > key)
Gets the property attributes of a real property which can be None or any combination of ReadOnly, DontEnum and DontDelete.
Interceptors in the prototype chain are not called.
Definition at line 5088 of file api.cc.
                                             {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_GetRealNamedPropertyAttributes};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  i::PropertyKey lookup_key(i_isolate, key_obj);
  i::LookupIterator it(i_isolate, self, lookup_key, self,
                       i::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  auto result = i::JSReceiver::GetPropertyAttributes(&it);
  if (result.IsNothing()) return {};
  if (!it.IsFound()) return {};
  if (result.FromJust() == i::ABSENT) {
    return Just(static_cast<PropertyAttribute>(i::NONE));
  }
  return Just<PropertyAttribute>(
      static_cast<PropertyAttribute>(result.FromJust()));
}
References v8::internal::ABSENT, v8::internal::Isolate::Current(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::key, v8::internal::NONE, v8::Utils::OpenDirectHandle(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, and v8::base::internal::result.
GetRealNamedPropertyAttributesInPrototypeChain()
Maybe< PropertyAttribute > v8::Object::GetRealNamedPropertyAttributesInPrototypeChain (Local< Context > context, Local< Name > key)
Gets the property attributes of a real property in the prototype chain, which can be None or any combination of ReadOnly, DontEnum and DontDelete.
Interceptors in the prototype chain are not called.
Definition at line 5049 of file api.cc.
                                             {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{
      i_isolate, context,
      RCCId::kAPI_Object_GetRealNamedPropertyAttributesInPrototypeChain};
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return {};
  auto key_obj = Utils::OpenDirectHandle(*key);
  i::PrototypeIterator iter(i_isolate, self);
  if (iter.IsAtEnd()) return {};
  i::DirectHandle<i::JSReceiver> proto =
      i::PrototypeIterator::GetCurrent<i::JSReceiver>(iter);
  i::PropertyKey lookup_key(i_isolate, key_obj);
  i::LookupIterator it(i_isolate, self, lookup_key, proto,
                       i::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  Maybe<i::PropertyAttributes> result =
      i::JSReceiver::GetPropertyAttributes(&it);
  if (result.IsNothing()) return {};
  if (!it.IsFound()) return {};
  if (result.FromJust() == i::ABSENT) return Just(None);
  return Just(static_cast<PropertyAttribute>(result.FromJust()));
}
References v8::internal::ABSENT, v8::internal::Isolate::Current(), v8::internal::JSReceiver::GetPropertyAttributes(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::key, v8::None, v8::Utils::OpenDirectHandle(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, and v8::base::internal::result.
GetRealNamedPropertyInPrototypeChain()
MaybeLocal< Value > v8::Object::GetRealNamedPropertyInPrototypeChain (Local< Context > context, Local< Name > key)
If result.IsEmpty() no real property was located in the prototype chain.
This means interceptors in the prototype chain are not called.
Definition at line 5028 of file api.cc.
                                             {
  PrepareForExecutionScope api_scope{
      context, RCCId::kAPI_Object_GetRealNamedPropertyInPrototypeChain};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return {};
  auto key_obj = Utils::OpenDirectHandle(*key);
  i::PrototypeIterator iter(i_isolate, self);
  if (iter.IsAtEnd()) return {};
  i::DirectHandle<i::JSReceiver> proto =
      i::PrototypeIterator::GetCurrent<i::JSReceiver>(iter);
  i::PropertyKey lookup_key(i_isolate, key_obj);
  i::LookupIterator it(i_isolate, self, lookup_key, proto,
                       i::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  MaybeLocal<Value> result = Utils::ToMaybeLocal(i::Object::GetProperty(&it));
  if (!it.IsFound()) return {};
  return api_scope.EscapeMaybe(result);
}
References v8::internal::Object::GetProperty(), v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::LookupIterator::IsFound(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, v8::base::internal::result, and v8::Utils::ToMaybeLocal().
Has() [1/2]
Maybe< bool > v8::Object::Has (Local< Context > context, Local< Value > key)
Object::Has() calls the abstract operation HasProperty(O, P), see https://tc39.es/ecma262/#sec-hasproperty.
Has() returns true, if the object has the property, either own or on the prototype chain. Interceptors, i.e., PropertyQueryCallbacks, are called if present.
Has() has the same side effects as JavaScript's variable in object. For example, calling Has() on a revoked proxy will throw an exception.
Note
Has() converts the key to a name, which possibly calls back into JavaScript.
See also v8::Object::HasOwnProperty() and v8::Object::HasRealNamedProperty().
Definition at line 4842 of file api.cc.
                                                                  {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Has};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  // Check if the given key is an array index.
  uint32_t index = 0;
  if (i::Object::ToArrayIndex(*key_obj, &index)) {
    return i::JSReceiver::HasElement(i_isolate, self, index);
  }
  // Convert the key to a name - possibly by calling back into JavaScript.
  i::DirectHandle<i::Name> name;
  if (i::Object::ToName(i_isolate, key_obj).ToHandle(&name)) {
    return i::JSReceiver::HasProperty(i_isolate, self, name);
  }
  return {};
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::HasElement(), v8::internal::JSReceiver::HasProperty(), v8::internal::index, v8::internal::key, name, v8::Utils::OpenDirectHandle(), v8::internal::Object::ToArrayIndex(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope().
Has() [2/2]
Maybe< bool > v8::Object::Has (Local< Context > context, uint32_t index)
Definition at line 4871 of file api.cc.
                                                                {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Has};
  auto self = Utils::OpenDirectHandle(this);
  return i::JSReceiver::HasElement(i_isolate, self, index);
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::HasElement(), v8::internal::index, and v8::Utils::OpenDirectHandle().
HasIndexedLookupInterceptor()
bool v8::Object::HasIndexedLookupInterceptor () const
Tests for an index lookup interceptor.
Definition at line 5022 of file api.cc.
                                                 {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return false;
  return i::Cast<i::JSObject>(self)->HasIndexedInterceptor();
}
References v8::Utils::OpenDirectHandle().
HasNamedLookupInterceptor()
bool v8::Object::HasNamedLookupInterceptor () const
Tests for a named lookup interceptor.
Definition at line 5016 of file api.cc.
                                               {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return false;
  return i::Cast<i::JSObject>(self)->HasNamedInterceptor();
}
References v8::Utils::OpenDirectHandle().
HasOwnProperty() [1/2]
Maybe< bool > v8::Object::HasOwnProperty (Local< Context > context, Local< Name > key)
HasOwnProperty() is like JavaScript's Object.prototype.hasOwnProperty().
See also v8::Object::Has() and v8::Object::HasRealNamedProperty().
Definition at line 4963 of file api.cc.
                                                        {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_HasOwnProperty};
  auto self = Utils::OpenDirectHandle(this);
  auto key_val = Utils::OpenDirectHandle(*key);
  return i::JSReceiver::HasOwnProperty(i_isolate, self, key_val);
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::HasOwnProperty(), v8::internal::key, and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty().
HasOwnProperty() [2/2]
Maybe< bool > v8::Object::HasOwnProperty (Local< Context > context, uint32_t index)
Definition at line 4973 of file api.cc.
                                                                           {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_HasOwnProperty};
  auto self = Utils::OpenDirectHandle(this);
  return i::JSReceiver::HasOwnProperty(i_isolate, self, index);
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::HasOwnProperty(), v8::internal::index, and v8::Utils::OpenDirectHandle().
HasPrivate()
Maybe< bool > v8::Object::HasPrivate (Local< Context > context, Local< Private > key)
Functionality for private properties.
This is an experimental feature, use at your own risk. Note: Private properties are not inherited. Do not rely on this, since it may change.
Definition at line 4860 of file api.cc.
                                                                           {
  return HasOwnProperty(context, key.UnsafeAs<Name>());
}
References v8::internal::key.
HasRealIndexedProperty()
Maybe< bool > v8::Object::HasRealIndexedProperty (Local< Context > context, uint32_t index)
Definition at line 4993 of file api.cc.
                                                               {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Object_HasRealIndexedProperty};
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return Just(false);
  return i::JSObject::HasRealElementProperty(i_isolate,
                                             i::Cast<i::JSObject>(self), index);
}
References v8::internal::Isolate::Current(), v8::internal::JSObject::HasRealElementProperty(), v8::internal::index, v8::Just(), and v8::Utils::OpenDirectHandle().
HasRealNamedCallbackProperty()
Maybe< bool > v8::Object::HasRealNamedCallbackProperty (Local< Context > context, Local< Name > key)
Definition at line 5004 of file api.cc.
                                                                      {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{
      i_isolate, context, RCCId::kAPI_Object_HasRealNamedCallbackProperty};
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return Just(false);
  auto key_val = Utils::OpenDirectHandle(*key);
  return i::JSObject::HasRealNamedCallbackProperty(
      i_isolate, i::Cast<i::JSObject>(self), key_val);
}
References v8::internal::Isolate::Current(), v8::internal::JSObject::HasRealNamedCallbackProperty(), v8::Just(), v8::internal::key, and v8::Utils::OpenDirectHandle().
HasRealNamedProperty()
Maybe< bool > v8::Object::HasRealNamedProperty (Local< Context > context, Local< Name > key)
Use HasRealNamedProperty() if you want to check if an object has an own property without causing side effects, i.e., without calling interceptors.
This function is similar to v8::Object::HasOwnProperty(), but it does not call interceptors.
Note
Consider using non-masking interceptors, i.e., the interceptors are not called if the receiver has the real named property. See v8::PropertyHandlerFlags::kNonMasking.
See also v8::Object::Has().
Definition at line 4981 of file api.cc.
                                                              {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Object_HasRealNamedProperty};
  auto self = Utils::OpenDirectHandle(this);
  if (!IsJSObject(*self)) return Just(false);
  auto key_val = Utils::OpenDirectHandle(*key);
  return i::JSObject::HasRealNamedProperty(i_isolate,
                                           i::Cast<i::JSObject>(self), key_val);
}
References v8::internal::Isolate::Current(), v8::internal::JSObject::HasRealNamedProperty(), v8::Just(), v8::internal::key, and v8::Utils::OpenDirectHandle().
InternalFieldCount() [1/3]
int v8::Object::InternalFieldCount () const
Gets the number of internal fields for this Object.
Definition at line 6219 of file api.cc.
                                       {
  auto self = *Utils::OpenDirectHandle(this);
  if (!IsJSObject(self)) return 0;
  return i::Cast<i::JSObject>(self)->GetEmbedderFieldCount();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), and v8::anonymous_namespace{d8-test.cc}::FastCApiObject::UnwrapObject().
InternalFieldCount() [2/3]
static int v8::Object::InternalFieldCount (const BasicTracedReference< Object > & object) [inline], [static]
Same as above, but works for BasicTracedReference.
Definition at line 501 of file v8-object.h.
                                                  {
    return object.template value<Object>()->InternalFieldCount();
  }
InternalFieldCount() [3/3]
static int v8::Object::InternalFieldCount (const PersistentBase< Object > & object) [inline], [static]
Same as above, but works for PersistentBase.
Definition at line 495 of file v8-object.h.
                                            {
    return object.template value<Object>()->InternalFieldCount();
  }
IsApiWrapper()
bool v8::Object::IsApiWrapper () const
Returns true if this object can be generally used to wrap object objects.
This means that the object either follows the convention of using embedder fields to denote type/instance pointers or is using the Wrap()/Unwrap() APIs for the same purpose. Returns false otherwise.
Note that there may be other objects that use embedder fields but are not used as API wrapper objects. E.g., v8::Promise may in certain configuration use embedder fields but promises are not generally supported as API wrappers. The method will return false in those cases.
Definition at line 5242 of file api.cc.
                                  {
  auto self = Utils::OpenDirectHandle(this);
  // This checks whether an object of a given instance type can serve as API
  // object. It does not check whether the JS object is wrapped via embedder
  // fields or Wrap()/Unwrap() API.
  return IsJSApiWrapperObject(*self);
}
References v8::internal::InstanceTypeChecker::IsJSApiWrapperObject(), and v8::Utils::OpenDirectHandle().
IsCallable()
bool v8::Object::IsCallable () const
Checks whether a callback is set by the ObjectTemplate::SetCallAsFunctionHandler method.
When an Object is callable this method returns true.
Definition at line 5234 of file api.cc.
                                {
  return i::IsCallable(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsCodeLike()
bool v8::Object::IsCodeLike (v8::Isolate * v8_isolate) const
Support for TC39 `dynamic code brand checks` proposal.
This API allows to query whether an object was constructed from a `code like` ObjectTemplate.
See also: v8::ObjectTemplate::SetCodeLike
Definition at line 10980 of file api.cc.
                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Object_IsCodeLike);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  return Utils::OpenDirectHandle(this)->IsCodeLike(i_isolate);
}
References v8::Utils::OpenDirectHandle().
IsConstructor()
bool v8::Object::IsConstructor () const
True if this object is a constructor.
Definition at line 5238 of file api.cc.
                                   {
  return i::IsConstructor(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Isolate::GetCurrent() [1/2]
Use v8::Object::Isolate::GetCurrent ()
Return the isolate to which the Object belongs to.
Isolate::GetCurrent() [2/2]
Use v8::Object::Isolate::GetCurrent ()
References v8::internal::handle().
IsUndetectable()
bool v8::Object::IsUndetectable () const
True if this object was created from an object template which was marked as undetectable.
See v8::ObjectTemplate::MarkAsUndetectable for more information.
Definition at line 5250 of file api.cc.
                                    {
  auto self = Utils::OpenDirectHandle(this);
  return i::IsUndetectable(*self);
}
References v8::Utils::OpenDirectHandle().
New() [1/2]
Local< v8::Object > v8::Object::New (Isolate * isolate) [static]
Definition at line 7732 of file api.cc.
                                                 {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Object_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::JSObject> obj =
      i_isolate->factory()->NewJSObject(i_isolate->object_function());
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewJSObject().
Referenced by v8_inspector::V8InspectorImpl::associateExceptionData(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::createCommandLineAPI(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8_inspector::generateCustomPreview(), v8::internal::StatisticsExtension::GetCounters(), v8_inspector::V8Debugger::getTargetScopes(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::OnInstantiationSucceeded(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::parseAdditionalSerializationParameters(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8_inspector::V8Debugger::privateMethods(), v8::Worker::ProcessMessage(), and v8::OnMessageFromWorkerTask::Run().
New() [2/2]
Local< v8::Object > v8::Object::New (Isolate * isolate, Local< Value > prototype_or_null, Local< Name > * names, Local< Value > * values, size_t length) [static]
Creates a JavaScript object with the given properties, and a the given prototype_or_null (which can be any JavaScript value, and if it's null, the newly created object won't have a prototype at all).
This is similar to Object.create(). All properties will be created as enumerable, configurable and writable properties.
Definition at line 7805 of file api.cc.
                                                 {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DirectHandle<i::JSPrototype> proto;
  if (!Utils::ApiCheck(
          i::TryCast(Utils::OpenDirectHandle(*prototype_or_null), &proto),
          "v8::Object::New", "prototype must be null or object")) {
    return {};
  }
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Object_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::FixedArrayBase> elements =
      i_isolate->factory()->empty_fixed_array();
  // We assume that this API is mostly used to create objects with named
  // properties, and so we default to creating a properties backing store
  // large enough to hold all of them, while we start with no elements
  // (see http://bit.ly/v8-fast-object-create-cpp for the motivation).
  if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    i::DirectHandle<i::SwissNameDictionary> properties =
        i_isolate->factory()->NewSwissNameDictionary(static_cast<int>(length));
    AddPropertiesAndElementsToObject(i_isolate, properties, elements, names,
                                     values, length);
    i::DirectHandle<i::JSObject> obj =
        i_isolate->factory()->NewSlowJSObjectWithPropertiesAndElements(
            proto, properties, elements);
    return Utils::ToLocal(obj);
  } else {
    i::DirectHandle<i::NameDictionary> properties =
        i::NameDictionary::New(i_isolate, static_cast<int>(length));
    AddPropertiesAndElementsToObject(i_isolate, properties, elements, names,
                                     values, length);
    i::DirectHandle<i::JSObject> obj =
        i_isolate->factory()->NewSlowJSObjectWithPropertiesAndElements(
            proto, properties, elements);
    return Utils::ToLocal(obj);
  }
}
References v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8::Utils::ApiCheck(), v8::internal::Isolate::factory(), v8::internal::length, v8::internal::NameDictionary::New(), v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionary(), v8::Utils::OpenDirectHandle(), v8::internal::TryCast(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
ObjectProtoToString()
MaybeLocal< String > v8::Object::ObjectProtoToString (Local< Context > context)
Call builtin Object.prototype.toString on this object.
This is different from Value::ToString() that may call user-defined toString function. This one does not.
Definition at line 4775 of file api.cc.
                                                                       {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_Object_ObjectProtoToString};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  return api_scope.EscapeMaybe(i::Cast<i::String>(i::Execution::CallBuiltin(
      i_isolate, i_isolate->object_to_string(), self, {})));
}
References v8::internal::Execution::CallBuiltin(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append().
PreviewEntries()
v8::MaybeLocal< v8::Array > v8::Object::PreviewEntries (bool * is_key_value)
If this object is a Set, Map, WeakSet or WeakMap, this returns a representation of the elements of this object as an array.
If this object is a SetIterator or MapIterator, this returns all elements of the underlying collection, starting at the iterator's current position. For other types, this will return an empty MaybeLocal<Array> (without scheduling an exception).
Definition at line 11202 of file api.cc.
                                                                 {
  auto object = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  if (i_isolate->is_execution_terminating()) return {};
  if (IsMap()) {
    *is_key_value = true;
    return Map::Cast(this)->AsArray();
  }
  if (IsSet()) {
    *is_key_value = false;
    return Set::Cast(this)->AsArray();
  }
  Isolate* v8_isolate = reinterpret_cast<Isolate*>(i_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (i::IsJSWeakCollection(*object)) {
    *is_key_value = IsJSWeakMap(*object);
    return Utils::ToLocal(i::JSWeakCollection::GetEntries(
        i::Cast<i::JSWeakCollection>(object), 0));
  }
  if (i::IsJSMapIterator(*object)) {
    auto it = i::Cast<i::JSMapIterator>(object);
    MapAsArrayKind const kind =
        static_cast<MapAsArrayKind>(it->map()->instance_type());
    *is_key_value = kind == MapAsArrayKind::kEntries;
    if (!it->HasMore()) return v8::Array::New(v8_isolate);
    return Utils::ToLocal(
        MapAsArray(i_isolate, it->table(), i::Smi::ToInt(it->index()), kind));
  }
  if (i::IsJSSetIterator(*object)) {
    auto it = i::Cast<i::JSSetIterator>(object);
    SetAsArrayKind const kind =
        static_cast<SetAsArrayKind>(it->map()->instance_type());
    *is_key_value = kind == SetAsArrayKind::kEntries;
    if (!it->HasMore()) return v8::Array::New(v8_isolate);
    return Utils::ToLocal(
        SetAsArray(i_isolate, it->table(), i::Smi::ToInt(it->index()), kind));
  }
  return {};
}
References v8::Map::AsArray(), v8::Set::AsArray(), v8::Map::Cast(), v8::Set::Cast(), v8::internal::Isolate::Current(), v8::internal::JSWeakCollection::GetEntries(), v8::internal::Isolate::is_execution_terminating(), v8::Value::IsMap(), v8::Value::IsSet(), v8::anonymous_namespace{api.cc}::MapAsArray(), v8::Array::New(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::SetAsArray(), and v8::internal::Smi::ToInt().
Referenced by v8_inspector::V8Debugger::collectionsEntries(), and v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::getEntries().
Set() [1/3]
Maybe< bool > v8::Object::Set (Local< Context > context, v8::Local< Value > key, v8::Local< Value > value)
Set only return Just(true) or Empty(), so if it should never fail, use result.Check().
Definition at line 4300 of file api.cc.
                                                                      {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Set};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  auto value_obj = Utils::OpenDirectHandle(*value);
  if (i::Runtime::SetObjectProperty(i_isolate, self, key_obj, value_obj,
                                    i::StoreOrigin::kMaybeKeyed,
                                    Just(i::ShouldThrow::kDontThrow))
          .is_null()) {
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::Runtime::SetObjectProperty(), and v8::internal::value.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8::Shell::CreateEvaluationContext(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeGetter(), v8_inspector::anonymous_namespace{value-mirror.cc}::createNativeSetter(), v8::Worker::ExecuteInThread(), v8::InspectorClient::InspectorClient(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), and v8_inspector::V8ConsoleMessage::wrapArguments().
Set() [2/3]
Maybe< bool > v8::Object::Set (Local< Context > context, v8::Local< Value > key, v8::Local< Value > value, MaybeLocal< Object > receiver)
Definition at line 4316 of file api.cc.
                                                         {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Set};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(*key);
  auto value_obj = Utils::OpenDirectHandle(*value);
  i::MaybeDirectHandle<i::JSReceiver> receiver_obj;
  if (!receiver.IsEmpty()) {
    receiver_obj = Utils::OpenDirectHandle(*receiver.ToLocalChecked());
  }
  if (i::Runtime::SetObjectProperty(i_isolate, self, key_obj, value_obj,
                                    receiver_obj, i::StoreOrigin::kMaybeKeyed,
                                    Just(i::ShouldThrow::kDontThrow))
          .is_null()) {
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::MaybeLocal< T >::IsEmpty(), v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::Runtime::SetObjectProperty(), v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::value.
Set() [3/3]
Maybe< bool > v8::Object::Set (Local< Context > context, uint32_t index, v8::Local< Value > value)
Definition at line 4337 of file api.cc.
                                                  {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Object_Set};
  auto self = Utils::OpenDirectHandle(this);
  auto value_obj = Utils::OpenHandle(*value);
  if (i::Object::SetElement(i_isolate, self, index, value_obj,
                            i::ShouldThrow::kDontThrow)
          .is_null()) {
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::internal::index, v8::Just(), v8::internal::kDontThrow, v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::internal::Object::SetElement(), and v8::internal::value.
SetAccessorProperty()
void v8::Object::SetAccessorProperty (Local< Name > name, Local< Function > getter, Local< Function > setter = Local<Function>(), PropertyAttribute attributes = None)
Sets an accessor property like Template::SetAccessorProperty, but this method sets on this object directly.
Definition at line 4912 of file api.cc.
                                                               {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  if (!IsJSObject(*self)) return;
  i::DirectHandle<i::JSReceiver> getter_i =
      v8::Utils::OpenDirectHandle(*getter);
  i::DirectHandle<i::JSAny> setter_i =
      v8::Utils::OpenDirectHandle(*setter, true);
  if (setter_i.is_null()) setter_i = i_isolate->factory()->null_value();
  i::PropertyDescriptor desc;
  desc.set_enumerable(!(attributes & v8::DontEnum));
  desc.set_configurable(!(attributes & v8::DontDelete));
  desc.set_get(getter_i);
  desc.set_set(setter_i);
  auto name_i = v8::Utils::OpenDirectHandle(*name);
  // DefineOwnProperty might still throw if the receiver is a JSProxy and it
  // might fail if the receiver is non-extensible or already has this property
  // as non-configurable.
  Maybe<bool> success = i::JSReceiver::DefineOwnProperty(
      i_isolate, self, name_i, &desc, Just(i::kDontThrow));
  USE(success);
}
References v8::internal::Isolate::Current(), v8::internal::JSReceiver::DefineOwnProperty(), v8::DontDelete, v8::DontEnum, v8::internal::Isolate::factory(), v8::internal::DirectHandle< T >::is_null(), v8::Just(), v8::internal::kDontThrow, name, v8::Utils::OpenDirectHandle(), v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_get(), v8::internal::PropertyDescriptor::set_set(), v8::internal::setter, and USE.
Referenced by v8::CreateFastCAPIObject(), and v8_inspector::V8Console::installMemoryGetter().
SetAlignedPointerInInternalField()
void v8::Object::SetAlignedPointerInInternalField (int index, void * value)
Sets a 2-byte-aligned native pointer in an internal field.
To retrieve such a field, GetAlignedPointerFromInternalField must be used, everything else leads to undefined behavior.
Definition at line 6274 of file api.cc.
                                                                      {
  auto obj = Utils::OpenDirectHandle(this);
  const char* location = "v8::Object::SetAlignedPointerInInternalField()";
  if (!InternalFieldOK(obj, index, location)) return;
  i::DisallowGarbageCollection no_gc;
  Utils::ApiCheck(
      i::EmbedderDataSlot(i::Cast<i::JSObject>(*obj), index)
          .store_aligned_pointer(i::Isolate::Current(), *obj, value),
      location, "Unaligned pointer");
  DCHECK_EQ(value, GetAlignedPointerFromInternalField(index));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::index, v8::InternalFieldOK(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8::CreateFastCAPIObject().
SetAlignedPointerInInternalFields()
void v8::Object::SetAlignedPointerInInternalFields (int argc, int indices[], void * values[])
Definition at line 6287 of file api.cc.
                                                                   {
  auto obj = Utils::OpenDirectHandle(this);
  if (!IsJSObject(*obj)) return;
  i::DisallowGarbageCollection no_gc;
  const char* location = "v8::Object::SetAlignedPointerInInternalFields()";
  auto js_obj = i::Cast<i::JSObject>(*obj);
  int nof_embedder_fields = js_obj->GetEmbedderFieldCount();
  for (int i = 0; i < argc; i++) {
    int index = indices[i];
    if (!Utils::ApiCheck(index < nof_embedder_fields, location,
                         "Internal field out of bounds")) {
      return;
    }
    void* value = values[i];
    Utils::ApiCheck(
        i::EmbedderDataSlot(js_obj, index)
            .store_aligned_pointer(i::Isolate::Current(), *obj, value),
        location, "Unaligned pointer");
    DCHECK_EQ(value, GetAlignedPointerFromInternalField(index));
  }
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::value.
SetIntegrityLevel()
Maybe< bool > v8::Object::SetIntegrityLevel (Local< Context > context, IntegrityLevel level)
Sets the integrity level of the object.
Definition at line 4798 of file api.cc.
                                                                {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Object_SetIntegrityLevel};
  auto self = Utils::OpenDirectHandle(this);
  i::JSReceiver::IntegrityLevel i_level =
      level == IntegrityLevel::kFrozen ? i::FROZEN : i::SEALED;
  return i::JSReceiver::SetIntegrityLevel(i_isolate, self, i_level,
                                          i::kThrowOnError);
}
References v8::internal::Isolate::Current(), v8::internal::FROZEN, v8::kFrozen, v8::internal::kThrowOnError, v8::Utils::OpenDirectHandle(), v8::internal::SEALED, and v8::internal::JSReceiver::SetIntegrityLevel().
SetInternalField()
void v8::Object::SetInternalField (int index, v8::Local< Data > value)
Sets the data in an internal field.
Definition at line 6242 of file api.cc.
                                                              {
  auto obj = Utils::OpenDirectHandle(this);
  const char* location = "v8::Object::SetInternalField()";
  if (!InternalFieldOK(obj, index, location)) return;
  auto val = Utils::OpenDirectHandle(*value);
  i::Cast<i::JSObject>(obj)->SetEmbedderField(index, *val);
}
References v8::internal::index, v8::InternalFieldOK(), v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8::AsyncHooks::CreateHook(), and v8::Shell::WorkerNew().
SetLazyDataProperty()
Maybe< bool > v8::Object::SetLazyDataProperty (Local< Context > context, v8::Local< Name > name, AccessorNameGetterCallback getter, v8::Local< Value > data = Local<Value>(), PropertyAttribute attributes = None, SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type = SideEffectType::kHasSideEffect)
Attempts to create a property with the given name which behaves like a data property, except that the provided getter is invoked (and provided with the data value) to supply its value the first time it is read.
After the property is accessed once, it is replaced with an ordinary data property.
Analogous to Template::SetLazyDataProperty.
Definition at line 4952 of file api.cc.
                                            {
  return ObjectSetAccessor(context, this, name, getter,
                           static_cast<AccessorNameSetterCallback>(nullptr),
                           data, attributes, true, getter_side_effect_type,
                           setter_side_effect_type);
}
References v8::internal::getter_side_effect_type, name, and v8::ObjectSetAccessor().
SetNativeDataProperty()
Maybe< bool > v8::Object::SetNativeDataProperty (Local< Context > context, v8::Local< Name > name, AccessorNameGetterCallback getter, AccessorNameSetterCallback setter = nullptr, v8::Local< Value > data = Local<Value>(), PropertyAttribute attributes = None, SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type = SideEffectType::kHasSideEffect)
Sets a native data property like Template::SetNativeDataProperty, but this method sets on this object directly.
Definition at line 4941 of file api.cc.
                                            {
  return ObjectSetAccessor(context, this, name, getter, setter, data,
                           attributes, false, getter_side_effect_type,
                           setter_side_effect_type);
}
References v8::internal::getter_side_effect_type, name, v8::ObjectSetAccessor(), and v8::internal::setter.
SetPrivate()
Maybe< bool > v8::Object::SetPrivate (Local< Context > context, Local< Private > key, Local< Value > value)
Definition at line 4536 of file api.cc.
                                                       {
  auto i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_Object_SetPrivate};
  auto self = Utils::OpenDirectHandle(this);
  auto key_obj = Utils::OpenDirectHandle(reinterpret_cast<Name*>(*key));
  auto value_obj = Utils::OpenDirectHandle(*value);
  if (i::IsJSObject(*self)) {
    auto js_object = i::Cast<i::JSObject>(self);
    i::LookupIterator it(i_isolate, js_object, key_obj, js_object);
    if (i::JSObject::DefineOwnPropertyIgnoreAttributes(&it, value_obj,
                                                       i::DONT_ENUM)
            .is_null()) {
      return {};
    }
    return Just(true);
  }
  if (i::IsJSProxy(*self)) {
    i::PropertyDescriptor desc;
    desc.set_writable(true);
    desc.set_enumerable(false);
    desc.set_configurable(true);
    desc.set_value(i::Cast<i::JSAny>(value_obj));
    return i::JSProxy::SetPrivateSymbol(i_isolate, i::Cast<i::JSProxy>(self),
                                        i::Cast<i::Symbol>(key_obj), &desc,
                                        Just(i::kDontThrow));
  }
  // Wasm object, or other kind of special object not supported here.
  return Just(false);
}
References v8::internal::Isolate::Current(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::DONT_ENUM, v8::Just(), v8::internal::kDontThrow, v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::JSProxy::SetPrivateSymbol(), and v8::internal::value.
Referenced by v8_inspector::TaskInfo::TaskInfo().
SetPrototypeV2()
Maybe< bool > v8::Object::SetPrototypeV2 (Local< Context > context, Local< Value > prototype)
Set the prototype object.
This does not skip objects marked to be skipped by proto and it does not consult the security handler. Set the prototype object (same as setting proto property). This does does not consult the security handler. TODO(333672197): rename back to SetPrototype() once the old version goes through the deprecation process and is removed.
Definition at line 4708 of file api.cc.
                                                           {
  static constexpr bool from_javascript = true;
  return SetPrototypeImpl(this, context, value, from_javascript);
}
References v8::anonymous_namespace{api.cc}::SetPrototypeImpl(), and v8::internal::value.
Referenced by v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::createCommandLineAPI(), and v8_inspector::V8Debugger::privateMethods().
SlowGetAlignedPointerFromInternalField() [1/2]
void * v8::Object::SlowGetAlignedPointerFromInternalField (int index) [private]
Definition at line 6263 of file api.cc.
                                                                {
  auto obj = Utils::OpenDirectHandle(this);
  const char* location = "v8::Object::GetAlignedPointerFromInternalField()";
  if (!InternalFieldOK(obj, index, location)) return nullptr;
  void* result;
  Utils::ApiCheck(i::EmbedderDataSlot(i::Cast<i::JSObject>(*obj), index)
                      .ToAlignedPointer(i::Isolate::Current(), &result),
                  location, "Unaligned pointer");
  return result;
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::index, v8::InternalFieldOK(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Referenced by GetAlignedPointerFromInternalField().
SlowGetAlignedPointerFromInternalField() [2/2]
void * v8::Object::SlowGetAlignedPointerFromInternalField (v8::Isolate * isolate, int index) [private]
Definition at line 6250 of file api.cc.
                                                                    {
  auto obj = Utils::OpenDirectHandle(this);
  const char* location = "v8::Object::GetAlignedPointerFromInternalField()";
  if (!InternalFieldOK(obj, index, location)) return nullptr;
  void* result;
  Utils::ApiCheck(
      i::EmbedderDataSlot(i::Cast<i::JSObject>(*obj), index)
          .ToAlignedPointer(reinterpret_cast<i::Isolate*>(isolate), &result),
      location, "Unaligned pointer");
  return result;
}
References v8::Utils::ApiCheck(), v8::internal::index, v8::InternalFieldOK(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
SlowGetInternalField()
Local< Data > v8::Object::SlowGetInternalField (int index) [private]
Definition at line 6233 of file api.cc.
                                                    {
  auto obj = Utils::OpenDirectHandle(this);
  const char* location = "v8::Object::GetInternalField()";
  if (!InternalFieldOK(obj, index, location)) return {};
  i::Isolate* isolate = i::Isolate::Current();
  return ToApiHandle<Data>(i::direct_handle(
      i::Cast<i::JSObject>(*obj)->GetEmbedderField(index), isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::index, v8::InternalFieldOK(), and v8::Utils::OpenDirectHandle().
Referenced by GetInternalField().
Unwrap() [1/7]
template<CppHeapPointerTag tag, typename T >
T * v8::Object::Unwrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper) [inline], [static]
Definition at line 1013 of file v8-object.h.
                                                               {
  CppHeapPointerTagRange tag_range(tag, tag);
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
#if !defined(V8_ENABLE_CHECKS)
  return internal::ReadCppHeapPointerField<T>(
      isolate, obj, internal::Internals::kJSObjectHeaderSize, tag_range);
#else // defined(V8_ENABLE_CHECKS)
  return reinterpret_cast<T*>(Unwrap(isolate, obj, tag_range));
#endif // defined(V8_ENABLE_CHECKS)
}
References v8::internal::Internals::kJSObjectHeaderSize, Unwrap(), and v8::internal::ValueHelper::ValueAsAddress().
Unwrap() [2/7]
template<typename T >
T * v8::Object::Unwrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper, CppHeapPointerTagRange tag_range) [inline], [static]
Definition at line 1056 of file v8-object.h.
                                                    {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
#if !defined(V8_ENABLE_CHECKS)
  return internal::ReadCppHeapPointerField<T>(
      isolate, obj, internal::Internals::kJSObjectHeaderSize, tag_range);
#else // defined(V8_ENABLE_CHECKS)
  return reinterpret_cast<T*>(Unwrap(isolate, obj, tag_range));
#endif // defined(V8_ENABLE_CHECKS)
}
References v8::internal::Internals::kJSObjectHeaderSize, Unwrap(), and v8::internal::ValueHelper::ValueAsAddress().
Unwrap() [3/7]
template<CppHeapPointerTag tag, typename T >
T * v8::Object::Unwrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper) [inline], [static]
Definition at line 999 of file v8-object.h.
                                                                           {
  CppHeapPointerTagRange tag_range(tag, tag);
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
#if !defined(V8_ENABLE_CHECKS)
  return internal::ReadCppHeapPointerField<T>(
      isolate, obj, internal::Internals::kJSObjectHeaderSize, tag_range);
#else // defined(V8_ENABLE_CHECKS)
  return reinterpret_cast<T*>(Unwrap(isolate, obj, tag_range));
#endif // defined(V8_ENABLE_CHECKS)
}
References v8::internal::Internals::kJSObjectHeaderSize, Unwrap(), and v8::internal::ValueHelper::ValueAsAddress().
Unwrap() [4/7]
template<typename T >
T * v8::Object::Unwrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper, CppHeapPointerTagRange tag_range) [inline], [static]
Definition at line 1041 of file v8-object.h.
                                                    {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
#if !defined(V8_ENABLE_CHECKS)
  return internal::ReadCppHeapPointerField<T>(
      isolate, obj, internal::Internals::kJSObjectHeaderSize, tag_range);
#else // defined(V8_ENABLE_CHECKS)
  return reinterpret_cast<T*>(Unwrap(isolate, obj, tag_range));
#endif // defined(V8_ENABLE_CHECKS)
}
References v8::internal::Internals::kJSObjectHeaderSize, Unwrap(), and v8::internal::ValueHelper::ValueAsAddress().
Unwrap() [5/7]
template<CppHeapPointerTag tag, typename T >
T * v8::Object::Unwrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper) [inline], [static]
Unwraps a JS wrapper object.
Parameters
tag The tag for retrieving the wrappable instance. Must match the tag that has been used for a previous Wrap() operation.
isolate The Isolate for the wrapper object.
wrapper The JS wrapper object that should be unwrapped.
Returns
the C++ wrappable instance, or nullptr if the JS object has never been wrapped.
Definition at line 986 of file v8-object.h.
                                                                      {
  CppHeapPointerTagRange tag_range(tag, tag);
  auto obj = internal::ValueHelper::ValueAsAddress(*wrapper);
#if !defined(V8_ENABLE_CHECKS)
  return internal::ReadCppHeapPointerField<T>(
      isolate, obj, internal::Internals::kJSObjectHeaderSize, tag_range);
#else // defined(V8_ENABLE_CHECKS)
  return reinterpret_cast<T*>(Unwrap(isolate, obj, tag_range));
#endif // defined(V8_ENABLE_CHECKS)
}
References v8::internal::Internals::kJSObjectHeaderSize, and v8::internal::ValueHelper::ValueAsAddress().
Referenced by Unwrap().
Unwrap() [6/7]
template<typename T >
T * v8::Object::Unwrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper, CppHeapPointerTagRange tag_range) [inline], [static]
Definition at line 1028 of file v8-object.h.
                                                    {
  auto obj = internal::ValueHelper::ValueAsAddress(*wrapper);
#if !defined(V8_ENABLE_CHECKS)
  return internal::ReadCppHeapPointerField<T>(
      isolate, obj, internal::Internals::kJSObjectHeaderSize, tag_range);
#else // defined(V8_ENABLE_CHECKS)
  return reinterpret_cast<T*>(Unwrap(isolate, obj, tag_range));
#endif // defined(V8_ENABLE_CHECKS)
}
References v8::internal::Internals::kJSObjectHeaderSize, Unwrap(), and v8::internal::ValueHelper::ValueAsAddress().
Unwrap() [7/7]
void * v8::Object::Unwrap (v8::Isolate * isolate, internal::Address wrapper_obj, CppHeapPointerTagRange tag_range) [static], [private]
Definition at line 6311 of file api.cc.
                                                           {
  DCHECK_LE(tag_range.lower_bound, tag_range.upper_bound);
  return i::CppHeapObjectWrapper(
             i::Cast<i::JSObject>(i::Tagged<i::Object>(wrapper_obj)))
      .GetCppHeapWrappable(reinterpret_cast<i::Isolate*>(isolate), tag_range);
}
References DCHECK_LE, v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable(), v8::CppHeapPointerTagRange::lower_bound, and v8::CppHeapPointerTagRange::upper_bound.
Wrap() [1/16]
template<CppHeapPointerTag tag>
Use Wrap with Wrappable* wrappable static instead void v8::Object::Wrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper, void * wrappable) [inline], [static]
Wrap() [2/16]
template<CppHeapPointerTag tag>
void v8::Object::Wrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper, void * wrappable)
Definition at line 1088 of file v8-object.h.
                                   {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [3/16]
void v8::Object::Wrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper, void * wrappable, CppHeapPointerTag tag) [inline], [static]
Definition at line 1112 of file v8-object.h.
                                         {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [4/16]
template<CppHeapPointerTag tag>
void v8::Object::Wrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper, Wrappable * wrappable) [inline], [static]
Definition at line 1139 of file v8-object.h.
                                                {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [5/16]
void v8::Object::Wrap (v8::Isolate * isolate, const BasicTracedReference< Object > & wrapper, Wrappable * wrappable, CppHeapPointerTag tag) [inline], [static]
Definition at line 1163 of file v8-object.h.
                                                                       {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [6/16]
template<CppHeapPointerTag tag>
Use Wrap with Wrappable* wrappable static instead void v8::Object::Wrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper, void * wrappable) [inline], [static]
Wrap() [7/16]
template<CppHeapPointerTag tag>
void v8::Object::Wrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper, void * wrappable)
Definition at line 1079 of file v8-object.h.
                                   {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [8/16]
void v8::Object::Wrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper, void * wrappable, CppHeapPointerTag tag) [inline], [static]
Definition at line 1104 of file v8-object.h.
                                                          {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [9/16]
template<CppHeapPointerTag tag>
void v8::Object::Wrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper, Wrappable * wrappable) [inline], [static]
Definition at line 1130 of file v8-object.h.
                                                {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [10/16]
void v8::Object::Wrap (v8::Isolate * isolate, const PersistentBase< Object > & wrapper, Wrappable * wrappable, CppHeapPointerTag tag) [inline], [static]
Definition at line 1155 of file v8-object.h.
                                                                       {
  auto obj =
      internal::ValueHelper::ValueAsAddress(wrapper.template value<Object>());
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [11/16]
template<CppHeapPointerTag tag>
Use Wrap with Wrappable* wrappable static instead void v8::Object::Wrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper, void * wrappable) [inline], [static]
Wraps a JS wrapper with a C++ instance.
Parameters
tag The pointer tag that should be used for storing this object. Future Unwrap() operations must provide a matching tag.
isolate The Isolate for the wrapper object.
wrapper The JS wrapper object.
wrappable The C++ object instance that is wrapped by the JS object.
Referenced by Wrap().
Wrap() [12/16]
template<CppHeapPointerTag tag>
void v8::Object::Wrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper, void * wrappable)
Definition at line 1071 of file v8-object.h.
                                   {
  auto obj = internal::ValueHelper::ValueAsAddress(*wrapper);
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [13/16]
void v8::Object::Wrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper, void * wrappable, CppHeapPointerTag tag) [inline], [static]
Definition at line 1097 of file v8-object.h.
                                                          {
  auto obj = internal::ValueHelper::ValueAsAddress(*wrapper);
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [14/16]
template<CppHeapPointerTag tag>
void v8::Object::Wrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper, Wrappable * wrappable) [inline], [static]
Definition at line 1122 of file v8-object.h.
                                                {
  auto obj = internal::ValueHelper::ValueAsAddress(*wrapper);
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [15/16]
void v8::Object::Wrap (v8::Isolate * isolate, const v8::Local< v8::Object > & wrapper, Wrappable * wrappable, CppHeapPointerTag tag) [inline], [static]
Definition at line 1148 of file v8-object.h.
                                                                       {
  auto obj = internal::ValueHelper::ValueAsAddress(*wrapper);
  Wrap(isolate, obj, tag, wrappable);
}
References v8::internal::ValueHelper::ValueAsAddress(), and Wrap().
Wrap() [16/16]
void v8::Object::Wrap (v8::Isolate * isolate, internal::Address wrapper_obj, CppHeapPointerTag tag, void * wrappable) [static], [private]
Definition at line 6320 of file api.cc.
                                                              {
  return i::CppHeapObjectWrapper(
             i::Cast<i::JSObject>(i::Tagged<i::Object>(wrapper_obj)))
      .SetCppHeapWrappable(reinterpret_cast<i::Isolate*>(isolate), wrappable,
                           tag);
}
References v8::internal::CppHeapObjectWrapper::SetCppHeapWrappable().
Member Data Documentation
https
Use which is guaranteed to return the same isolate since v8::Object::https
Definition at line 853 of file v8-object.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-object.h
/mnt/V8SourceCode/src/api/api.cc