v8::internal::interpreter::BytecodeGenerator::ForInScope Class Reference
Public Member Functions
ForInScope (BytecodeGenerator *bytecode_generator, ForInStatement *stmt, Register enum_index, Register cache_type)
~ForInScope ()
ForInScope * GetForInScope (Variable *each)
Register enum_index ()
Register cache_type ()
Private Attributes
BytecodeGenerator *const bytecode_generator_
ForInScope *const parent_for_in_scope_
Variable * each_var_
Register enum_index_
Register cache_type_
Detailed Description
Definition at line 1271 of file bytecode-generator.cc.
Constructor & Destructor Documentation
ForInScope()
v8::internal::interpreter::BytecodeGenerator::ForInScope::ForInScope (BytecodeGenerator * bytecode_generator, ForInStatement * stmt, Register enum_index, Register cache_type) [inline], [explicit]
Definition at line 1273 of file bytecode-generator.cc.
      : bytecode_generator_(bytecode_generator),
        parent_for_in_scope_(bytecode_generator_->current_for_in_scope()),
        each_var_(nullptr),
        enum_index_(enum_index),
        cache_type_(cache_type) {
    if (v8_flags.enable_enumerated_keyed_access_bytecode) {
      Expression* each = stmt->each();
      if (each->IsVariableProxy()) {
        Variable* each_var = each->AsVariableProxy()->var();
        if (each_var->IsStackLocal()) {
          each_var_ = each_var;
          bytecode_generator_->SetVariableInRegister(
              each_var_,
              bytecode_generator_->builder()->Local(each_var_->index()));
        }
      }
      bytecode_generator_->set_current_for_in_scope(this);
    }
  }
References v8::internal::ForEachStatement::each(), and v8::internal::v8_flags.
 ForInScope()
v8::internal::interpreter::BytecodeGenerator::ForInScope::~ForInScope () [inline]
Definition at line 1296 of file bytecode-generator.cc.
                {
    if (v8_flags.enable_enumerated_keyed_access_bytecode) {
      bytecode_generator_->set_current_for_in_scope(parent_for_in_scope_);
    }
  }
References v8::internal::v8_flags.
Member Function Documentation
cache_type()
Register v8::internal::interpreter::BytecodeGenerator::ForInScope::cache_type () [inline]
Definition at line 1314 of file bytecode-generator.cc.
{ return cache_type_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLoadKeyedProperty().
enum_index()
Register v8::internal::interpreter::BytecodeGenerator::ForInScope::enum_index () [inline]
Definition at line 1313 of file bytecode-generator.cc.
{ return enum_index_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLoadKeyedProperty().
GetForInScope()
ForInScope* v8::internal::interpreter::BytecodeGenerator::ForInScope::GetForInScope (Variable * each) [inline]
Definition at line 1303 of file bytecode-generator.cc.
                                            {
    DCHECK(v8_flags.enable_enumerated_keyed_access_bytecode);
    ForInScope* scope = this;
    do {
      if (each == scope->each_var_) break;
      scope = scope->parent_for_in_scope_;
    } while (scope != nullptr);
    return scope;
  }
References v8::internal::DCHECK(), each_var_, parent_for_in_scope_, and v8::internal::v8_flags.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLoadKeyedProperty().
Member Data Documentation
bytecode_generator_
BytecodeGenerator* const v8::internal::interpreter::BytecodeGenerator::ForInScope::bytecode_generator_ [private]
Definition at line 1317 of file bytecode-generator.cc.
cache_type_
Register v8::internal::interpreter::BytecodeGenerator::ForInScope::cache_type_ [private]
Definition at line 1321 of file bytecode-generator.cc.
each_var_
Variable* v8::internal::interpreter::BytecodeGenerator::ForInScope::each_var_ [private]
Definition at line 1319 of file bytecode-generator.cc.
Referenced by GetForInScope().
enum_index_
Register v8::internal::interpreter::BytecodeGenerator::ForInScope::enum_index_ [private]
Definition at line 1320 of file bytecode-generator.cc.
parent_for_in_scope_
ForInScope* const v8::internal::interpreter::BytecodeGenerator::ForInScope::parent_for_in_scope_ [private]
Definition at line 1318 of file bytecode-generator.cc.
Referenced by GetForInScope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc