v8::internal::wasm::LiftoffAssembler Class Reference
#include <liftoff-assembler.h>
Classes
struct CacheState
struct ParallelRegisterMoveTuple
Public Types
enum JumpDirection { kForwardJump
, kBackwardJump
 }
enum SkipWriteBarrier : bool { kSkipWriteBarrier = true
, kNoSkipWriteBarrier = false
 }
enum SmiCheckMode { kJumpOnSmi
, kJumpOnNotSmi
 }
using ValueKindSig = Signature< ValueKind >
using VarState = LiftoffVarState
Public Member Functions
LiftoffAssembler (Zone *, std::unique_ptr< AssemblerBuffer >)
~LiftoffAssembler () override
Zone * zone () const
LiftoffRegister LoadToRegister (VarState slot, LiftoffRegList pinned)
V8_NOINLINE V8_PRESERVE_MOST LiftoffRegister LoadToRegister_Slow (VarState slot, LiftoffRegList pinned)
void LoadToFixedRegister (VarState slot, LiftoffRegister reg)
LiftoffRegister LoadToModifiableRegister (VarState slot, LiftoffRegList pinned)
VarState PopVarState ()
LiftoffRegister PopToRegister (LiftoffRegList pinned={})
void PopToFixedRegister (LiftoffRegister reg)
LiftoffRegister PopToModifiableRegister (LiftoffRegList pinned={})
LiftoffRegister PeekToRegister (int index, LiftoffRegList pinned)
void DropValues (int count)
void DropExceptionValueAtOffset (int offset)
void SpillLoopArgs (int num)
int NextSpillOffset (ValueKind kind)
int TopSpillOffset () const
void PushRegister (ValueKind kind, LiftoffRegister reg)
void PushException ()
void PushConstant (ValueKind kind, int32_t i32_const)
void PushStack (ValueKind kind)
V8_NOINLINE V8_PRESERVE_MOST void SpillRegister (LiftoffRegister)
uint32_t GetNumUses (LiftoffRegister reg) const
LiftoffRegister GetUnusedRegister (RegClass rc, std::initializer_list< LiftoffRegister > try_first, LiftoffRegList pinned)
LiftoffRegister GetUnusedRegister (RegClass rc, LiftoffRegList pinned)
LiftoffRegister GetUnusedRegister (LiftoffRegList candidates)
void PrepareForBranch (uint32_t arity, LiftoffRegList pinned)
CacheState MergeIntoNewState (uint32_t num_locals, uint32_t arity, uint32_t stack_depth)
void MergeFullStackWith (CacheState &target)
void MergeStackWith (CacheState &target, uint32_t arity, JumpDirection)
void Spill (VarState *slot)
void SpillLocals ()
void SpillAllRegisters ()
void LoadSpillAddress (Register dst, int offset, ValueKind kind)
void ClearRegister (Register reg, std::initializer_list< Register * > possible_uses, LiftoffRegList pinned)
template<typename... Regs>
void SpillRegisters (Regs... regs)
void RecordUsedSpillOffset (int offset)
void RecordOolSpillSpaceSize (int size)
void PrepareBuiltinCall (const ValueKindSig *sig, compiler::CallDescriptor *call_descriptor, std::initializer_list< VarState > params)
void PrepareCall (const ValueKindSig *, compiler::CallDescriptor *, Register *target=nullptr, Register target_instance=no_reg)
void FinishCall (const ValueKindSig *, compiler::CallDescriptor *)
void Move (LiftoffRegister dst, LiftoffRegister src, ValueKind)
void ParallelRegisterMove (base::Vector< const ParallelRegisterMoveTuple >)
void ParallelRegisterMove (std::initializer_list< ParallelRegisterMoveTuple > moves)
void MoveToReturnLocations (const FunctionSig *, compiler::CallDescriptor *)
V8_NOINLINE V8_PRESERVE_MOST void MoveToReturnLocationsMultiReturn (const FunctionSig *, compiler::CallDescriptor *)
void LoadFixedArrayLengthAsInt32 (LiftoffRegister dst, Register array, LiftoffRegList pinned)
void LoadSmiAsInt32 (LiftoffRegister dst, Register src_addr, int32_t offset)
int PrepareStackFrame ()
void CallFrameSetupStub (int declared_function_index)
void PrepareTailCall (int num_callee_stack_params, int stack_param_delta)
void AlignFrameSize ()
void PatchPrepareStackFrame (int offset, SafepointTableBuilder *, bool feedback_vector_slot, size_t stack_param_slots)
void FinishCode ()
void AbortCompilation ()
void CheckTierUp (int declared_func_index, int budget_used, Label *ool_label, const FreezeCacheState &frozen)
Register LoadOldFramePointer ()
void CheckStackShrink ()
void LoadConstant (LiftoffRegister, WasmValue)
void LoadInstanceDataFromFrame (Register dst)
void LoadTrustedPointer (Register dst, Register src_addr, int offset, IndirectPointerTag tag)
void LoadFromInstance (Register dst, Register instance, int offset, int size)
void LoadTaggedPointerFromInstance (Register dst, Register instance, int offset)
void SpillInstanceData (Register instance)
void ResetOSRTarget ()
void LoadTaggedPointer (Register dst, Register src_addr, Register offset_reg, int32_t offset_imm, uint32_t *protected_load_pc=nullptr, bool offset_reg_needs_shift=false)
void AtomicLoadTaggedPointer (Register dst, Register src_addr, Register offset_reg, int32_t offset_imm, AtomicMemoryOrder memory_order, uint32_t *protected_load_pc=nullptr, bool offset_reg_needs_shift=false)
void LoadProtectedPointer (Register dst, Register src_addr, int32_t offset)
void LoadFullPointer (Register dst, Register src_addr, int32_t offset_imm)
void LoadCodePointer (Register dst, Register src_addr, int32_t offset)
void EmitWriteBarrier (Register target_object, Operand store_location, Register stored_value, LiftoffRegList pinned)
void StoreTaggedPointer (Register dst_addr, Register offset_reg, int32_t offset_imm, Register src, LiftoffRegList pinned, uint32_t *protected_store_pc=nullptr, SkipWriteBarrier=kNoSkipWriteBarrier)
void AtomicStoreTaggedPointer (Register dst_addr, Register offset_reg, int32_t offset_imm, Register src, LiftoffRegList pinned, AtomicMemoryOrder memory_order, uint32_t *protected_store_pc=nullptr)
void IncrementSmi (LiftoffRegister dst, int offset)
void Load (LiftoffRegister dst, Register src_addr, Register offset_reg, uintptr_t offset_imm, LoadType type, uint32_t *protected_load_pc=nullptr, bool is_load_mem=false, bool i64_offset=false, bool needs_shift=false)
void Store (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister src, StoreType type, LiftoffRegList pinned, uint32_t *protected_store_pc=nullptr, bool is_store_mem=false, bool i64_offset=false)
void AtomicLoad (LiftoffRegister dst, Register src_addr, Register offset_reg, uintptr_t offset_imm, LoadType type, LiftoffRegList pinned, bool i64_offset)
void AtomicStore (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister src, StoreType type, LiftoffRegList pinned, bool i64_offset)
void AtomicAdd (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
void AtomicSub (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
void AtomicAnd (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
void AtomicOr (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
void AtomicXor (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
void AtomicExchange (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset)
void AtomicExchangeTaggedPointer (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, LiftoffRegList pinned)
void AtomicCompareExchange (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister expected, LiftoffRegister new_value, LiftoffRegister value, StoreType type, bool i64_offset)
void AtomicFence ()
void LoadCallerFrameSlot (LiftoffRegister, uint32_t caller_slot_idx, ValueKind)
void StoreCallerFrameSlot (LiftoffRegister, uint32_t caller_slot_idx, ValueKind, Register frame_pointer)
void LoadReturnStackSlot (LiftoffRegister, int offset, ValueKind)
void MoveStackValue (uint32_t dst_offset, uint32_t src_offset, ValueKind)
void Move (Register dst, Register src, ValueKind)
void Move (DoubleRegister dst, DoubleRegister src, ValueKind)
void Spill (int offset, LiftoffRegister, ValueKind)
void Spill (int offset, WasmValue)
void Fill (LiftoffRegister, int offset, ValueKind)
void FillI64Half (Register, int offset, RegPairHalf)
void FillStackSlotsWithZero (int start, int size)
void emit_trace_instruction (uint32_t markid)
void emit_i32_add (Register dst, Register lhs, Register rhs)
void emit_i32_addi (Register dst, Register lhs, int32_t imm)
void emit_i32_sub (Register dst, Register lhs, Register rhs)
void emit_i32_subi (Register dst, Register lhs, int32_t imm)
void emit_i32_mul (Register dst, Register lhs, Register rhs)
void emit_i32_muli (Register dst, Register lhs, int32_t imm)
void emit_i32_divs (Register dst, Register lhs, Register rhs, Label *trap_div_by_zero, Label *trap_div_unrepresentable)
void emit_i32_divu (Register dst, Register lhs, Register rhs, Label *trap_div_by_zero)
void emit_i32_rems (Register dst, Register lhs, Register rhs, Label *trap_rem_by_zero)
void emit_i32_remu (Register dst, Register lhs, Register rhs, Label *trap_rem_by_zero)
void emit_i32_and (Register dst, Register lhs, Register rhs)
void emit_i32_andi (Register dst, Register lhs, int32_t imm)
void emit_i32_or (Register dst, Register lhs, Register rhs)
void emit_i32_ori (Register dst, Register lhs, int32_t imm)
void emit_i32_xor (Register dst, Register lhs, Register rhs)
void emit_i32_xori (Register dst, Register lhs, int32_t imm)
void emit_i32_shl (Register dst, Register src, Register amount)
void emit_i32_shli (Register dst, Register src, int32_t amount)
void emit_i32_sar (Register dst, Register src, Register amount)
void emit_i32_sari (Register dst, Register src, int32_t amount)
void emit_i32_shr (Register dst, Register src, Register amount)
void emit_i32_shri (Register dst, Register src, int32_t amount)
void emit_i32_clz (Register dst, Register src)
void emit_i32_ctz (Register dst, Register src)
bool emit_i32_popcnt (Register dst, Register src)
void emit_i64_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64_addi (LiftoffRegister dst, LiftoffRegister lhs, int64_t imm)
void emit_i64_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64_muli (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm)
bool emit_i64_divs (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label *trap_div_by_zero, Label *trap_div_unrepresentable)
bool emit_i64_divu (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label *trap_div_by_zero)
bool emit_i64_rems (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label *trap_rem_by_zero)
bool emit_i64_remu (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label *trap_rem_by_zero)
void emit_i64_and (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64_andi (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm)
void emit_i64_or (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64_ori (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm)
void emit_i64_xor (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64_xori (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm)
void emit_i64_shl (LiftoffRegister dst, LiftoffRegister src, Register amount)
void emit_i64_shli (LiftoffRegister dst, LiftoffRegister src, int32_t amount)
void emit_i64_sar (LiftoffRegister dst, LiftoffRegister src, Register amount)
void emit_i64_sari (LiftoffRegister dst, LiftoffRegister src, int32_t amount)
void emit_i64_shr (LiftoffRegister dst, LiftoffRegister src, Register amount)
void emit_i64_shri (LiftoffRegister dst, LiftoffRegister src, int32_t amount)
void emit_i64_clz (LiftoffRegister dst, LiftoffRegister src)
void emit_i64_ctz (LiftoffRegister dst, LiftoffRegister src)
bool emit_i64_popcnt (LiftoffRegister dst, LiftoffRegister src)
void emit_u32_to_uintptr (Register dst, Register src)
void clear_i32_upper_half (Register dst)
void emit_ptrsize_add (Register dst, Register lhs, Register rhs)
void emit_ptrsize_sub (Register dst, Register lhs, Register rhs)
void emit_ptrsize_and (Register dst, Register lhs, Register rhs)
void emit_ptrsize_shri (Register dst, Register src, int amount)
void emit_ptrsize_addi (Register dst, Register lhs, intptr_t imm)
void emit_ptrsize_muli (Register dst, Register lhs, int32_t imm)
void emit_ptrsize_set_cond (Condition condition, Register dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32_add (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_sub (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_mul (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_div (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_min (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_max (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_copysign (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f32_abs (DoubleRegister dst, DoubleRegister src)
void emit_f32_neg (DoubleRegister dst, DoubleRegister src)
bool emit_f32_ceil (DoubleRegister dst, DoubleRegister src)
bool emit_f32_floor (DoubleRegister dst, DoubleRegister src)
bool emit_f32_trunc (DoubleRegister dst, DoubleRegister src)
bool emit_f32_nearest_int (DoubleRegister dst, DoubleRegister src)
void emit_f32_sqrt (DoubleRegister dst, DoubleRegister src)
void emit_f64_add (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_sub (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_mul (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_div (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_min (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_max (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_copysign (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_abs (DoubleRegister dst, DoubleRegister src)
void emit_f64_neg (DoubleRegister dst, DoubleRegister src)
bool emit_f64_ceil (DoubleRegister dst, DoubleRegister src)
bool emit_f64_floor (DoubleRegister dst, DoubleRegister src)
bool emit_f64_trunc (DoubleRegister dst, DoubleRegister src)
bool emit_f64_nearest_int (DoubleRegister dst, DoubleRegister src)
void emit_f64_sqrt (DoubleRegister dst, DoubleRegister src)
bool emit_type_conversion (WasmOpcode opcode, LiftoffRegister dst, LiftoffRegister src, Label *trap=nullptr)
void emit_i32_signextend_i8 (Register dst, Register src)
void emit_i32_signextend_i16 (Register dst, Register src)
void emit_i64_signextend_i8 (LiftoffRegister dst, LiftoffRegister src)
void emit_i64_signextend_i16 (LiftoffRegister dst, LiftoffRegister src)
void emit_i64_signextend_i32 (LiftoffRegister dst, LiftoffRegister src)
void emit_jump (Label *)
void emit_jump (Register)
void emit_cond_jump (Condition, Label *, ValueKind value, Register lhs, Register rhs, const FreezeCacheState &frozen)
void emit_i32_cond_jumpi (Condition, Label *, Register lhs, int imm, const FreezeCacheState &frozen)
void emit_ptrsize_cond_jumpi (Condition, Label *, Register lhs, int32_t imm, const FreezeCacheState &frozen)
void emit_i32_eqz (Register dst, Register src)
void emit_i32_set_cond (Condition, Register dst, Register lhs, Register rhs)
void emit_i64_eqz (Register dst, LiftoffRegister src)
void emit_i64_set_cond (Condition condition, Register dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32_set_cond (Condition condition, Register dst, DoubleRegister lhs, DoubleRegister rhs)
void emit_f64_set_cond (Condition condition, Register dst, DoubleRegister lhs, DoubleRegister rhs)
bool emit_select (LiftoffRegister dst, Register condition, LiftoffRegister true_value, LiftoffRegister false_value, ValueKind kind)
void emit_smi_check (Register obj, Label *target, SmiCheckMode mode, const FreezeCacheState &frozen)
void LoadTransform (LiftoffRegister dst, Register src_addr, Register offset_reg, uintptr_t offset_imm, LoadType type, LoadTransformationKind transform, uint32_t *protected_load_pc, bool i64_offset)
void LoadLane (LiftoffRegister dst, LiftoffRegister src, Register addr, Register offset_reg, uintptr_t offset_imm, LoadType type, uint8_t lane, uint32_t *protected_load_pc, bool i64_offset)
void StoreLane (Register dst, Register offset, uintptr_t offset_imm, LiftoffRegister src, StoreType type, uint8_t lane, uint32_t *protected_store_pc, bool i64_offset)
void emit_i8x16_shuffle (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, const uint8_t shuffle[16], bool is_swizzle)
void emit_i8x16_swizzle (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_relaxed_swizzle (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_relaxed_trunc_f32x4_s (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_relaxed_trunc_f32x4_u (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_relaxed_trunc_f64x2_s_zero (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_relaxed_trunc_f64x2_u_zero (LiftoffRegister dst, LiftoffRegister src)
void emit_s128_relaxed_laneselect (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister mask, int lane_width)
void emit_i8x16_popcnt (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_splat (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_splat (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_splat (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_splat (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_splat (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_splat (LiftoffRegister dst, LiftoffRegister src)
void emit_f64x2_splat (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_gt_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_ge_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_gt_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_ge_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_gt_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_ge_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_lt (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_le (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_lt (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_le (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_lt (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_le (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_s128_const (LiftoffRegister dst, const uint8_t imms[16])
void emit_s128_not (LiftoffRegister dst, LiftoffRegister src)
void emit_s128_and (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_s128_or (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_s128_xor (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_s128_select (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister mask)
void emit_i8x16_neg (LiftoffRegister dst, LiftoffRegister src)
void emit_v128_anytrue (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_alltrue (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_bitmask (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i8x16_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i8x16_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i8x16_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_add_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_add_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_sub_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_sub_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_min_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_min_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_max_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_max_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_neg (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_alltrue (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_bitmask (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i16x8_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i16x8_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i16x8_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_add_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_add_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_sub_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_sub_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_min_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_min_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_max_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_max_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_extadd_pairwise_i8x16_s (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_extadd_pairwise_i8x16_u (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_extmul_low_i8x16_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i16x8_extmul_low_i8x16_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i16x8_extmul_high_i8x16_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i16x8_extmul_high_i8x16_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i16x8_q15mulr_sat_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i16x8_relaxed_q15mulr_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i16x8_dot_i8x16_i7x16_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i32x4_dot_i8x16_i7x16_add_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister acc)
void emit_i32x4_neg (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_alltrue (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_bitmask (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i32x4_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i32x4_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i32x4_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_min_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_min_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_max_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_max_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_dot_i16x8_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i32x4_extadd_pairwise_i16x8_s (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_extadd_pairwise_i16x8_u (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_extmul_low_i16x8_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i32x4_extmul_low_i16x8_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i32x4_extmul_high_i16x8_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i32x4_extmul_high_i16x8_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i64x2_neg (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_alltrue (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i64x2_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i64x2_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs)
void emit_i64x2_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i64x2_extmul_low_i32x4_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i64x2_extmul_low_i32x4_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i64x2_extmul_high_i32x4_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i64x2_extmul_high_i32x4_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2)
void emit_i64x2_bitmask (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_sconvert_i32x4_low (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_sconvert_i32x4_high (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_uconvert_i32x4_low (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_uconvert_i32x4_high (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_abs (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_neg (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_sqrt (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_ceil (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_floor (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_trunc (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_nearest_int (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_div (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_pmin (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
bool emit_f16x8_pmax (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_abs (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_neg (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_sqrt (LiftoffRegister dst, LiftoffRegister src)
bool emit_f32x4_ceil (LiftoffRegister dst, LiftoffRegister src)
bool emit_f32x4_floor (LiftoffRegister dst, LiftoffRegister src)
bool emit_f32x4_trunc (LiftoffRegister dst, LiftoffRegister src)
bool emit_f32x4_nearest_int (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_div (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_pmin (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_pmax (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_relaxed_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f32x4_relaxed_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_abs (LiftoffRegister dst, LiftoffRegister src)
void emit_f64x2_neg (LiftoffRegister dst, LiftoffRegister src)
void emit_f64x2_sqrt (LiftoffRegister dst, LiftoffRegister src)
bool emit_f64x2_ceil (LiftoffRegister dst, LiftoffRegister src)
bool emit_f64x2_floor (LiftoffRegister dst, LiftoffRegister src)
bool emit_f64x2_trunc (LiftoffRegister dst, LiftoffRegister src)
bool emit_f64x2_nearest_int (LiftoffRegister dst, LiftoffRegister src)
void emit_f64x2_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_div (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_pmin (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_pmax (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_relaxed_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_relaxed_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_f64x2_convert_low_i32x4_s (LiftoffRegister dst, LiftoffRegister src)
void emit_f64x2_convert_low_i32x4_u (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_trunc_sat_f64x2_s_zero (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_trunc_sat_f64x2_u_zero (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_demote_f64x2_zero (LiftoffRegister dst, LiftoffRegister src)
void emit_f64x2_promote_low_f32x4 (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_sconvert_f32x4 (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_uconvert_f32x4 (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_sconvert_i32x4 (LiftoffRegister dst, LiftoffRegister src)
void emit_f32x4_uconvert_i32x4 (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_demote_f32x4_zero (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_demote_f64x2_zero (LiftoffRegister dst, LiftoffRegister src)
bool emit_f32x4_promote_low_f16x8 (LiftoffRegister dst, LiftoffRegister src)
bool emit_i16x8_sconvert_f16x8 (LiftoffRegister dst, LiftoffRegister src)
bool emit_i16x8_uconvert_f16x8 (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_sconvert_i16x8 (LiftoffRegister dst, LiftoffRegister src)
bool emit_f16x8_uconvert_i16x8 (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_sconvert_i16x8 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_uconvert_i16x8 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_sconvert_i32x4 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_uconvert_i32x4 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_sconvert_i8x16_low (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_sconvert_i8x16_high (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_uconvert_i8x16_low (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_uconvert_i8x16_high (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_sconvert_i16x8_low (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_sconvert_i16x8_high (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_uconvert_i16x8_low (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_uconvert_i16x8_high (LiftoffRegister dst, LiftoffRegister src)
void emit_s128_and_not (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_rounding_average_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i16x8_rounding_average_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs)
void emit_i8x16_abs (LiftoffRegister dst, LiftoffRegister src)
void emit_i16x8_abs (LiftoffRegister dst, LiftoffRegister src)
void emit_i32x4_abs (LiftoffRegister dst, LiftoffRegister src)
void emit_i64x2_abs (LiftoffRegister dst, LiftoffRegister src)
void emit_i8x16_extract_lane_s (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_i8x16_extract_lane_u (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_i16x8_extract_lane_s (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_i16x8_extract_lane_u (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_i32x4_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_i64x2_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
bool emit_f16x8_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_f32x4_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_f64x2_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx)
void emit_i8x16_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
void emit_i16x8_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
void emit_i32x4_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
void emit_i64x2_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
bool emit_f16x8_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
void emit_f32x4_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
void emit_f64x2_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx)
bool emit_f16x8_qfma (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3)
bool emit_f16x8_qfms (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3)
void emit_f32x4_qfma (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3)
void emit_f32x4_qfms (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3)
void emit_f64x2_qfma (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3)
void emit_f64x2_qfms (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3)
void set_trap_on_oob_mem64 (Register index, uint64_t max_index, Label *trap_label)
void emit_inc_i32_at (Address address)
void StackCheck (Label *ool_code)
void AssertUnreachable (AbortReason reason)
void PushRegisters (LiftoffRegList)
void PopRegisters (LiftoffRegList)
void RecordSpillsInSafepoint (SafepointTableBuilder::Safepoint &safepoint, LiftoffRegList all_spills, LiftoffRegList ref_spills, int spill_offset)
void DropStackSlotsAndRet (uint32_t num_stack_slots)
void CallCWithStackBuffer (const std::initializer_list< VarState > args, const LiftoffRegister *rets, ValueKind return_kind, ValueKind out_argument_kind, int stack_bytes, ExternalReference ext_ref)
void CallC (const std::initializer_list< VarState > args, ExternalReference ext_ref)
void CallNativeWasmCode (Address addr)
void TailCallNativeWasmCode (Address addr)
void CallIndirect (const ValueKindSig *sig, compiler::CallDescriptor *call_descriptor, Register target)
void TailCallIndirect (compiler::CallDescriptor *call_descriptor, Register target)
void CallBuiltin (Builtin builtin)
void AllocateStackSlot (Register addr, uint32_t size)
void DeallocateStackSlot (uint32_t size)
void MaybeOSR ()
void emit_store_nonzero_if_nan (Register dst, DoubleRegister src, ValueKind kind)
void emit_s128_store_nonzero_if_nan (Register dst, LiftoffRegister src, Register tmp_gp, LiftoffRegister tmp_s128, ValueKind lane_kind)
void emit_store_nonzero (Register dst)
bool supports_f16_mem_access ()
uint32_t num_locals () const
void set_num_locals (uint32_t num_locals)
int GetTotalFrameSlotCountForGC () const
int OolSpillCount () const
int GetTotalFrameSize () const
ValueKind local_kind (uint32_t index)
void set_local_kind (uint32_t index, ValueKind kind)
CacheState * cache_state ()
const CacheState * cache_state () const
bool did_bailout ()
LiftoffBailoutReason bailout_reason () const
const char * bailout_detail () const
void bailout (LiftoffBailoutReason reason, const char *detail)
Static Public Member Functions
static int NextSpillOffset (ValueKind kind, int top_spill_offset)
static constexpr int StaticStackFrameSize ()
static int SlotSizeForType (ValueKind kind)
static bool NeedsAlignment (ValueKind kind)
Static Public Attributes
static constexpr int kStackSlotSize = 8
static constexpr ValueKind kIntPtrKind
static constexpr ValueKind kSmiKind = kTaggedSize == kInt32Size ? kI32 : kI64
Private Member Functions
LiftoffRegister LoadI64HalfIntoRegister (VarState slot, RegPairHalf half, LiftoffRegList pinned)
V8_NOINLINE V8_PRESERVE_MOST LiftoffRegister SpillOneRegister (LiftoffRegList candidates)
LiftoffRegister SpillAdjacentFpRegisters (LiftoffRegList pinned)
Private Attributes
uint32_t num_locals_ = 0
xx xx xx xx xx xx xx xx xx
union {
 ValueKind local_kinds_ [kInlineLocalKinds]
 ValueKind * more_local_kinds_
};
CacheState cache_state_
int max_used_spill_offset_ = StaticStackFrameSize()
int ool_spill_space_size_ = 0
LiftoffBailoutReason bailout_reason_ = kSuccess
const char * bailout_detail_ = nullptr
Static Private Attributes
static constexpr uint32_t kInlineLocalKinds = 16
Additional Inherited Members
Detailed Description
Definition at line 99 of file liftoff-assembler.h.
Member Typedef Documentation
ValueKindSig
using v8::internal::wasm::LiftoffAssembler::ValueKindSig = Signature<ValueKind>
Definition at line 109 of file liftoff-assembler.h.
VarState
using v8::internal::wasm::LiftoffAssembler::VarState = LiftoffVarState
Definition at line 111 of file liftoff-assembler.h.
Member Enumeration Documentation
JumpDirection
enum v8::internal::wasm::LiftoffAssembler::JumpDirection
Enumerator
kForwardJump
kBackwardJump
Definition at line 568 of file liftoff-assembler.h.
{ kForwardJump, kBackwardJump };
SkipWriteBarrier
enum v8::internal::wasm::LiftoffAssembler::SkipWriteBarrier : bool
Enumerator
kSkipWriteBarrier
kNoSkipWriteBarrier
Definition at line 724 of file liftoff-assembler.h.
                        : bool {
    kSkipWriteBarrier = true,
    kNoSkipWriteBarrier = false
  };
SmiCheckMode
enum v8::internal::wasm::LiftoffAssembler::SmiCheckMode
Enumerator
kJumpOnSmi
kJumpOnNotSmi
Definition at line 1012 of file liftoff-assembler.h.
{ kJumpOnSmi, kJumpOnNotSmi };
Constructor & Destructor Documentation
LiftoffAssembler()
v8::internal::wasm::LiftoffAssembler::LiftoffAssembler (Zone * zone, std::unique_ptr< AssemblerBuffer > buffer) [explicit]
Definition at line 363 of file liftoff-assembler.cc.
    : MacroAssembler(zone, DefaultLiftoffOptions(), CodeObjectRequired::kNo,
                     std::move(buffer)),
      cache_state_(zone) {
  set_abort_hard(true); // Avoid calls to Abort.
}
References v8::internal::kNo, and v8::internal::MacroAssemblerBase::set_abort_hard().
 LiftoffAssembler()
v8::internal::wasm::LiftoffAssembler::~LiftoffAssembler () [override]
Definition at line 371 of file liftoff-assembler.cc.
                                    {
  if (num_locals_ > kInlineLocalKinds) {
    base::Free(more_local_kinds_);
  }
}
References v8::base::Free(), kInlineLocalKinds, more_local_kinds_, and num_locals_.
Member Function Documentation
AbortCompilation()
void v8::internal::wasm::LiftoffAssembler::AbortCompilation () [inline]
Definition at line 619 of file liftoff-assembler-arm-inl.h.
{ AbortedCodeGeneration(); }
References v8::internal::Assembler::AbortedCodeGeneration().
Referenced by bailout().
AlignFrameSize()
void v8::internal::wasm::LiftoffAssembler::AlignFrameSize () [inline]
Definition at line 524 of file liftoff-assembler-arm-inl.h.
{}
AllocateStackSlot()
void v8::internal::wasm::LiftoffAssembler::AllocateStackSlot (Register addr, uint32_t size) [inline]
Definition at line 4955 of file liftoff-assembler-arm-inl.h.
                                                                     {
  AllocateStackSpace(size);
  mov(addr, sp);
}
References v8::internal::MacroAssembler::AllocateStackSpace(), v8::internal::MacroAssembler::mov(), and size().
AssertUnreachable()
void v8::internal::wasm::LiftoffAssembler::AssertUnreachable (AbortReason reason) [inline]
Definition at line 4738 of file liftoff-assembler-arm-inl.h.
                                                           {
  // Asserts unreachable within the wasm code.
  MacroAssembler::AssertUnreachable(reason);
}
References v8::internal::MacroAssembler::AssertUnreachable().
AtomicAdd()
void v8::internal::wasm::LiftoffAssembler::AtomicAdd (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 1309 of file liftoff-assembler-arm-inl.h.
                                         {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, value, {result},
                        liftoff::I64Binop<&Assembler::add, &Assembler::adc>);
    return;
  }
  liftoff::AtomicBinop32(this, dst_addr, offset_reg, offset_imm, value, result,
                         type, &liftoff::Add);
}
References v8::internal::wasm::liftoff::Add(), v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::base::internal::result, v8::internal::tracing::type, and v8::internal::value.
AtomicAnd()
void v8::internal::wasm::LiftoffAssembler::AtomicAnd (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 1335 of file liftoff-assembler-arm-inl.h.
                                         {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, value, {result},
                        liftoff::I64Binop<&Assembler::and_, &Assembler::and_>);
    return;
  }
  liftoff::AtomicBinop32(this, dst_addr, offset_reg, offset_imm, value, result,
                         type, &liftoff::And);
}
References v8::internal::wasm::liftoff::And(), v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::base::internal::result, v8::internal::tracing::type, and v8::internal::value.
AtomicCompareExchange()
void v8::internal::wasm::LiftoffAssembler::AtomicCompareExchange (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister expected, LiftoffRegister new_value, LiftoffRegister value, StoreType type, bool i64_offset) [inline]
Definition at line 1490 of file liftoff-assembler-arm-inl.h.
                            {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicI64CompareExchange(this, dst_addr, offset_reg, offset_imm,
                                      expected, new_value, result);
    return;
  }
  // The other versions of CompareExchange can share code, but need special load
  // and store instructions.
  void (Assembler::*load)(Register, Register, Condition) = nullptr;
  void (Assembler::*store)(Register, Register, Register, Condition) = nullptr;
  LiftoffRegList pinned{dst_addr};
  if (offset_reg != no_reg) pinned.set(offset_reg);
  // We need to remember the high word of {result}, so we can set it to zero in
  // the end if necessary.
  Register result_high = no_reg;
  switch (type.value()) {
    case StoreType::kI64Store8:
      result_high = result.high_gp();
      result = result.low();
      new_value = new_value.low();
      expected = expected.low();
      [[fallthrough]];
    case StoreType::kI32Store8:
      load = &Assembler::ldrexb;
      store = &Assembler::strexb;
      // We have to clear the high bits of {expected}, as we can only do a
      // 32-bit comparison. If the {expected} register is used, we spill it
      // first.
      if (cache_state()->is_used(expected)) {
        SpillRegister(expected);
      }
      uxtb(expected.gp(), expected.gp());
      break;
    case StoreType::kI64Store16:
      result_high = result.high_gp();
      result = result.low();
      new_value = new_value.low();
      expected = expected.low();
      [[fallthrough]];
    case StoreType::kI32Store16:
      load = &Assembler::ldrexh;
      store = &Assembler::strexh;
      // We have to clear the high bits of {expected}, as we can only do a
      // 32-bit comparison. If the {expected} register is used, we spill it
      // first.
      if (cache_state()->is_used(expected)) {
        SpillRegister(expected);
      }
      uxth(expected.gp(), expected.gp());
      break;
    case StoreType::kI64Store32:
      result_high = result.high_gp();
      result = result.low();
      new_value = new_value.low();
      expected = expected.low();
      [[fallthrough]];
    case StoreType::kI32Store:
      load = &Assembler::ldrex;
      store = &Assembler::strex;
      break;
    default:
      UNREACHABLE();
  }
  pinned.set(new_value);
  pinned.set(expected);
  Register result_reg = result.gp();
  if (pinned.has(result)) {
    result_reg = GetUnusedRegister(kGpReg, pinned).gp();
  }
  pinned.set(LiftoffRegister(result));
  Register store_result = GetUnusedRegister(kGpReg, pinned).gp();
  UseScratchRegisterScope temps(this);
  Register actual_addr = liftoff::CalculateActualAddress(
      this, &temps, dst_addr, offset_reg, offset_imm);
  Label retry;
  Label done;
  dmb(ISH);
  bind(&retry);
  (this->*load)(result.gp(), actual_addr, al);
  cmp(result.gp(), expected.gp());
  b(ne, &done);
  (this->*store)(store_result, new_value.gp(), actual_addr, al);
  cmp(store_result, Operand(0));
  b(ne, &retry);
  dmb(ISH);
  bind(&done);
  if (result.gp() != result_reg) {
    mov(result.gp(), result_reg);
  }
  if (result_high != no_reg) {
    LoadConstant(LiftoffRegister(result_high), WasmValue(0));
  }
}
References v8::internal::al, v8::internal::wasm::liftoff::AtomicI64CompareExchange(), v8::internal::Assembler::b(), v8::internal::Assembler::bind(), cache_state(), v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::Assembler::cmp(), v8::internal::Assembler::dmb(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::ISH, v8::internal::wasm::kGpReg, v8::internal::Assembler::ldrex(), v8::internal::Assembler::ldrexb(), v8::internal::Assembler::ldrexh(), LoadConstant(), v8::internal::wasm::LiftoffRegister::low(), v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::no_reg, v8::internal::ETWJITInterface::Register(), v8::base::internal::result, v8::internal::wasm::LiftoffRegList::set(), SpillRegister(), store(), v8::internal::Assembler::strex(), v8::internal::Assembler::strexb(), v8::internal::Assembler::strexh(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), v8::internal::Assembler::uxtb(), v8::internal::Assembler::uxth(), and v8::internal::wasm::void().
AtomicExchange()
void v8::internal::wasm::LiftoffAssembler::AtomicExchange (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 1374 of file liftoff-assembler-arm-inl.h.
                                              {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, value, {result},
                        liftoff::I64Store);
    return;
  }
  liftoff::AtomicBinop32(this, dst_addr, offset_reg, offset_imm, value, result,
                         type, &liftoff::Exchange);
}
References v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::internal::wasm::liftoff::Exchange(), v8::internal::wasm::liftoff::I64Store(), v8::base::internal::result, v8::internal::tracing::type, and v8::internal::value.
AtomicExchangeTaggedPointer()
void v8::internal::wasm::LiftoffAssembler::AtomicExchangeTaggedPointer (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, LiftoffRegList pinned) [inline]
Definition at line 1388 of file liftoff-assembler-arm-inl.h.
                                                                          {
  liftoff::AtomicOp32(this, dst_addr, offset_reg, offset_imm, value, result,
                      pinned, &Assembler::ldrex, &Assembler::strex,
                      &liftoff::Exchange);
  if (v8_flags.disable_write_barriers) return;
  // Emit the write barrier.
  Label exit;
  CheckPageFlag(dst_addr, MemoryChunk::kPointersFromHereAreInterestingMask,
                kZero, &exit);
  JumpIfSmi(value.gp(), &exit);
  CheckPageFlag(value.gp(), MemoryChunk::kPointersToHereAreInterestingMask, eq,
                &exit);
  UseScratchRegisterScope temps{this};
  Register actual_offset_reg = offset_reg;
  if (offset_reg != no_reg && offset_imm != 0) {
    if (cache_state()->is_used(LiftoffRegister(offset_reg))) {
      // The code below only needs a scratch register if the {MemOperand} given
      // to {str} has an offset outside the uint12 range. After doing the
      // addition below we will not pass an immediate offset to {str} though, so
      // we can use the scratch register here.
      actual_offset_reg = temps.Acquire();
    }
    add(actual_offset_reg, offset_reg, Operand(offset_imm));
  }
  CallRecordWriteStubSaveRegisters(
      dst_addr,
      actual_offset_reg == no_reg ? Operand(offset_imm)
                                  : Operand(actual_offset_reg),
      SaveFPRegsMode::kSave, StubCallMode::kCallWasmRuntimeStub);
  bind(&exit);
}
References v8::internal::Assembler::add(), v8::internal::wasm::liftoff::AtomicOp32(), v8::internal::Assembler::bind(), cache_state(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::eq, v8::internal::wasm::liftoff::Exchange(), v8::internal::MacroAssembler::JumpIfSmi(), v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, v8::internal::MemoryChunk::kPointersToHereAreInterestingMask, v8::internal::kSave, v8::internal::kZero, v8::internal::Assembler::ldrex(), v8::internal::no_reg, v8::base::internal::result, v8::internal::Assembler::strex(), v8::internal::v8_flags, and v8::internal::value.
AtomicFence()
void v8::internal::wasm::LiftoffAssembler::AtomicFence () [inline]
Definition at line 1593 of file liftoff-assembler-arm-inl.h.
{ dmb(ISH); }
References v8::internal::Assembler::dmb(), and v8::internal::ISH.
AtomicLoad()
void v8::internal::wasm::LiftoffAssembler::AtomicLoad (LiftoffRegister dst, Register src_addr, Register offset_reg, uintptr_t offset_imm, LoadType type, LiftoffRegList pinned, bool i64_offset) [inline]
Definition at line 1256 of file liftoff-assembler-arm-inl.h.
                                          {
  if (type.value() != LoadType::kI64Load) {
    Load(dst, src_addr, offset_reg, offset_imm, type, nullptr, true);
    dmb(ISH);
    return;
  }
  // ldrexd loads a 64 bit word into two registers. The first register needs to
  // have an even index, e.g. r8, the second register needs to be the one with
  // the next higher index, e.g. r9 if the first register is r8. In the
  // following code we use the fixed register pair r8/r9 to make the code here
  // simpler, even though other register pairs would also be possible.
  constexpr Register dst_low = r8;
  constexpr Register dst_high = r9;
  SpillRegisters(dst_low, dst_high);
  {
    UseScratchRegisterScope temps(this);
    Register actual_addr = liftoff::CalculateActualAddress(
        this, &temps, src_addr, offset_reg, offset_imm);
    ldrexd(dst_low, dst_high, actual_addr);
    dmb(ISH);
  }
  ParallelRegisterMove(
      {{dst, LiftoffRegister::ForPair(dst_low, dst_high), kI64}});
}
References v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::Assembler::dmb(), v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::ISH, v8::internal::kI64, v8::internal::Assembler::ldrexd(), Load(), ParallelRegisterMove(), SpillRegisters(), and v8::internal::tracing::type.
Referenced by AtomicLoadTaggedPointer().
AtomicLoadTaggedPointer()
void v8::internal::wasm::LiftoffAssembler::AtomicLoadTaggedPointer (Register dst, Register src_addr, Register offset_reg, int32_t offset_imm, AtomicMemoryOrder memory_order, uint32_t * protected_load_pc = nullptr, bool offset_reg_needs_shift = false) [inline]
Definition at line 903 of file liftoff-assembler-arm-inl.h.
                                                                 {
  AtomicLoad(LiftoffRegister(dst), src_addr, offset_reg, offset_imm,
             LoadType::kI32Load, {}, false);
}
References AtomicLoad().
AtomicOr()
void v8::internal::wasm::LiftoffAssembler::AtomicOr (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 1348 of file liftoff-assembler-arm-inl.h.
                                        {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, value, {result},
                        liftoff::I64Binop<&Assembler::orr, &Assembler::orr>);
    return;
  }
  liftoff::AtomicBinop32(this, dst_addr, offset_reg, offset_imm, value, result,
                         type, &liftoff::Or);
}
References v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::internal::wasm::liftoff::Or(), v8::base::internal::result, v8::internal::tracing::type, and v8::internal::value.
AtomicStore()
void v8::internal::wasm::LiftoffAssembler::AtomicStore (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister src, StoreType type, LiftoffRegList pinned, bool i64_offset) [inline]
Definition at line 1285 of file liftoff-assembler-arm-inl.h.
                                           {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, src, {},
                        liftoff::I64Store);
    return;
  }
  dmb(ISH);
  Store(dst_addr, offset_reg, offset_imm, src, type, pinned, nullptr, true);
  dmb(ISH);
  return;
}
References v8::internal::wasm::liftoff::AtomicOp64(), v8::internal::Assembler::dmb(), v8::internal::wasm::liftoff::I64Store(), v8::internal::ISH, Store(), and v8::internal::tracing::type.
Referenced by AtomicStoreTaggedPointer().
AtomicStoreTaggedPointer()
void v8::internal::wasm::LiftoffAssembler::AtomicStoreTaggedPointer (Register dst_addr, Register offset_reg, int32_t offset_imm, Register src, LiftoffRegList pinned, AtomicMemoryOrder memory_order, uint32_t * protected_store_pc = nullptr) [inline]
Definition at line 1301 of file liftoff-assembler-arm-inl.h.
                                  {
  AtomicStore(dst_addr, offset_reg, offset_imm, LiftoffRegister(src),
              StoreType::kI32Store, pinned, false);
}
References AtomicStore().
AtomicSub()
void v8::internal::wasm::LiftoffAssembler::AtomicSub (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 1322 of file liftoff-assembler-arm-inl.h.
                                         {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, value, {result},
                        liftoff::I64Binop<&Assembler::sub, &Assembler::sbc>);
    return;
  }
  liftoff::AtomicBinop32(this, dst_addr, offset_reg, offset_imm, value, result,
                         type, &liftoff::Sub);
}
References v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::base::internal::result, v8::internal::wasm::liftoff::Sub(), v8::internal::tracing::type, and v8::internal::value.
AtomicXor()
void v8::internal::wasm::LiftoffAssembler::AtomicXor (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister value, LiftoffRegister result, StoreType type, bool i64_offset) [inline]
Definition at line 1361 of file liftoff-assembler-arm-inl.h.
                                         {
  if (type.value() == StoreType::kI64Store) {
    liftoff::AtomicOp64(this, dst_addr, offset_reg, offset_imm, value, {result},
                        liftoff::I64Binop<&Assembler::eor, &Assembler::eor>);
    return;
  }
  liftoff::AtomicBinop32(this, dst_addr, offset_reg, offset_imm, value, result,
                         type, &liftoff::Xor);
}
References v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::wasm::liftoff::AtomicOp64(), v8::base::internal::result, v8::internal::tracing::type, v8::internal::value, and v8::internal::wasm::liftoff::Xor().
bailout()
void v8::internal::wasm::LiftoffAssembler::bailout (LiftoffBailoutReason reason, const char * detail) [inline]
Definition at line 201 of file liftoff-assembler-inl.h.
                                                   {
  DCHECK_NE(kSuccess, reason);
  if (bailout_reason_ != kSuccess) return;
  AbortCompilation();
  bailout_reason_ = reason;
  bailout_detail_ = detail;
}
References AbortCompilation(), bailout_detail_, bailout_reason_, DCHECK_NE, and v8::internal::wasm::kSuccess.
Referenced by emit_i32_divs(), emit_i32_divu(), emit_i32_rems(), emit_i32_remu(), and PrepareStackFrame().
bailout_detail()
const char* v8::internal::wasm::LiftoffAssembler::bailout_detail () const [inline]
Definition at line 1630 of file liftoff-assembler.h.
{ return bailout_detail_; }
References bailout_detail_.
bailout_reason()
LiftoffBailoutReason v8::internal::wasm::LiftoffAssembler::bailout_reason () const [inline]
Definition at line 1629 of file liftoff-assembler.h.
{ return bailout_reason_; }
References bailout_reason_.
cache_state() [1/2]
CacheState* v8::internal::wasm::LiftoffAssembler::cache_state () [inline]
Definition at line 1625 of file liftoff-assembler.h.
{ return &cache_state_; }
References cache_state_.
Referenced by v8::internal::wasm::liftoff::CacheStatePreservingTempRegisters::Acquire(), AtomicCompareExchange(), AtomicExchangeTaggedPointer(), ClearRegister(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), emit_i16x8_bitmask(), emit_i32x4_bitmask(), emit_i64x2_mul(), emit_i8x16_bitmask(), v8::internal::wasm::liftoff::EmitShiftOperation(), LoadOldFramePointer(), LoadToModifiableRegister(), v8::internal::wasm::liftoff::MoveStackValue(), MoveToReturnLocationsMultiReturn(), and StoreTaggedPointer().
cache_state() [2/2]
const CacheState* v8::internal::wasm::LiftoffAssembler::cache_state () const [inline]
Definition at line 1626 of file liftoff-assembler.h.
{ return &cache_state_; }
References cache_state_.
CallBuiltin()
void v8::internal::wasm::LiftoffAssembler::CallBuiltin (Builtin builtin) [inline]
Definition at line 4949 of file liftoff-assembler-arm-inl.h.
                                                  {
  // A direct call to a builtin. Just encode the builtin index. This will be
  // patched at relocation.
  Call(static_cast<Address>(builtin), RelocInfo::WASM_STUB_CALL);
}
References v8::internal::MacroAssemblerBase::builtin(), v8::internal::MacroAssembler::Call(), and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by CallFrameSetupStub(), and PatchPrepareStackFrame().
CallC()
void v8::internal::wasm::LiftoffAssembler::CallC (const std::initializer_list< VarState > args, ExternalReference ext_ref) [inline]
Definition at line 4876 of file liftoff-assembler-arm-inl.h.
                                                        {
  // First, prepare the stack for the C call.
  int num_args = static_cast<int>(args.size());
  PrepareCallCFunction(num_args);
  // Then execute the parallel register move and also move values to parameter
  // stack slots.
  int reg_args = 0;
  int stack_args = 0;
  ParallelMove parallel_move{this};
  for (const VarState& arg : args) {
    if (needs_gp_reg_pair(arg.kind())) {
      // All i64 arguments (currently) fully fit in the register parameters.
      DCHECK_LE(reg_args + 2, arraysize(kCArgRegs));
      parallel_move.LoadIntoRegister(
          LiftoffRegister::ForPair(kCArgRegs[reg_args],
                                   kCArgRegs[reg_args + 1]),
          arg);
      reg_args += 2;
      continue;
    }
    if (reg_args < int{arraysize(kCArgRegs)}) {
      parallel_move.LoadIntoRegister(LiftoffRegister{kCArgRegs[reg_args]}, arg);
      ++reg_args;
      continue;
    }
    MemOperand dst{sp, stack_args * kSystemPointerSize};
    ++stack_args;
    if (arg.is_reg()) {
      liftoff::Store(this, arg.reg(), dst, arg.kind());
      continue;
    }
    UseScratchRegisterScope temps(this);
    Register scratch = temps.Acquire();
    if (arg.is_const()) {
      DCHECK_EQ(kI32, arg.kind());
      mov(scratch, Operand(arg.i32_const()));
      str(scratch, dst);
    } else {
      // Stack to stack move.
      MemOperand src = liftoff::GetStackSlot(arg.offset());
      ldr(scratch, src);
      str(scratch, dst);
    }
  }
  parallel_move.Execute();
  // Now call the C function.
  CallCFunction(ext_ref, num_args);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::base::args, arraysize, v8::internal::MacroAssembler::CallCFunction(), DCHECK_EQ, DCHECK_LE, v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::liftoff::GetStackSlot(), v8::internal::kCArgRegs, v8::internal::kI32, v8::internal::kSystemPointerSize, v8::internal::Assembler::ldr(), v8::internal::MacroAssembler::mov(), v8::internal::wasm::needs_gp_reg_pair(), v8::internal::MacroAssembler::PrepareCallCFunction(), v8::internal::wasm::liftoff::Store(), and v8::internal::Assembler::str().
CallCWithStackBuffer()
void v8::internal::wasm::LiftoffAssembler::CallCWithStackBuffer (const std::initializer_list< VarState > args, const LiftoffRegister * rets, ValueKind return_kind, ValueKind out_argument_kind, int stack_bytes, ExternalReference ext_ref) [inline]
Definition at line 4813 of file liftoff-assembler-arm-inl.h.
                               {
  // Arguments are passed by pushing them all to the stack and then passing
  // a pointer to them.
  DCHECK(IsAligned(stack_bytes, kSystemPointerSize));
  // Reserve space in the stack.
  AllocateStackSpace(stack_bytes);
  int arg_offset = 0;
  for (const VarState& arg : args) {
    MemOperand dst{sp, arg_offset};
    if (arg.is_reg()) {
      liftoff::Store(this, arg.reg(), dst, arg.kind());
    } else if (arg.is_const()) {
      DCHECK_EQ(kI32, arg.kind());
      UseScratchRegisterScope temps(this);
      Register src = temps.Acquire();
      mov(src, Operand(arg.i32_const()));
      str(src, dst);
    } else {
      // Stack to stack move.
      UseScratchRegisterScope temps(this);
      Register scratch = temps.Acquire();
      MemOperand src = liftoff::GetStackSlot(arg.offset());
      int words = SlotSizeForType(arg.kind()) / kSystemPointerSize;
      do {
        ldr(scratch, src);
        str(scratch, dst);
        src.set_offset(src.offset() + kSystemPointerSize);
        dst.set_offset(dst.offset() + kSystemPointerSize);
      } while (--words > 0);
    }
    arg_offset += value_kind_size(arg.kind());
  }
  DCHECK_LE(arg_offset, stack_bytes);
  // Pass a pointer to the buffer with the arguments to the C function.
  mov(r0, sp);
  // Now call the C function.
  constexpr int kNumCCallArgs = 1;
  PrepareCallCFunction(kNumCCallArgs);
  CallCFunction(ext_ref, kNumCCallArgs);
  // Move return value to the right register.
  const LiftoffRegister* result_reg = rets;
  if (return_kind != kVoid) {
    constexpr Register kReturnReg = r0;
    if (kReturnReg != rets->gp()) {
      Move(*rets, LiftoffRegister(kReturnReg), return_kind);
    }
    result_reg++;
  }
  // Load potential output value from the buffer on the stack.
  if (out_argument_kind != kVoid) {
    liftoff::Load(this, *result_reg, MemOperand{sp}, out_argument_kind);
  }
  add(sp, sp, Operand(stack_bytes));
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::add(), v8::internal::MacroAssembler::AllocateStackSpace(), v8::base::args, v8::internal::MacroAssembler::CallCFunction(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::wasm::liftoff::GetStackSlot(), v8::internal::wasm::LiftoffRegister::gp(), IsAligned(), v8::internal::kI32, v8::internal::kSystemPointerSize, v8::internal::Assembler::ldr(), v8::internal::wasm::liftoff::Load(), v8::internal::MacroAssembler::mov(), Move(), v8::internal::MemOperand::offset(), v8::internal::MacroAssembler::PrepareCallCFunction(), v8::internal::MemOperand::set_offset(), SlotSizeForType(), v8::internal::wasm::liftoff::Store(), v8::internal::Assembler::str(), and v8::internal::wasm::value_kind_size().
CallFrameSetupStub()
void v8::internal::wasm::LiftoffAssembler::CallFrameSetupStub (int declared_function_index) [inline]
Definition at line 478 of file liftoff-assembler-arm-inl.h.
                                                                     {
// The standard library used by gcc tryjobs does not consider `std::find` to be
// `constexpr`, so wrap it in a `#ifdef __clang__` block.
#ifdef __clang__
  static_assert(std::find(std::begin(wasm::kGpParamRegisters),
                          std::end(wasm::kGpParamRegisters),
                          kLiftoffFrameSetupFunctionReg) ==
                std::end(wasm::kGpParamRegisters));
#endif
  // On ARM, we must push at least {lr} before calling the stub, otherwise
  // it would get clobbered with no possibility to recover it.
  Register scratch = r7;
  mov(scratch, Operand(StackFrame::TypeToMarker(StackFrame::WASM)));
  PushCommonFrame(scratch);
  LoadConstant(LiftoffRegister(kLiftoffFrameSetupFunctionReg),
               WasmValue(declared_function_index));
  CallBuiltin(Builtin::kWasmLiftoffFrameSetup);
}
References v8::internal::compiler::begin(), CallBuiltin(), v8::internal::wasm::declared_function_index(), v8::internal::compiler::end(), v8::internal::wasm::kGpParamRegisters, LoadConstant(), v8::internal::MacroAssembler::mov(), v8::internal::MacroAssembler::PushCommonFrame(), and v8::internal::StackFrame::TypeToMarker().
CallIndirect()
void v8::internal::wasm::LiftoffAssembler::CallIndirect (const ValueKindSig * sig, compiler::CallDescriptor * call_descriptor, Register target) [inline]
Definition at line 4936 of file liftoff-assembler-arm-inl.h.
                                                     {
  DCHECK(target != no_reg);
  CallWasmCodePointer(target);
}
References v8::internal::DCHECK(), and v8::internal::no_reg.
CallNativeWasmCode()
void v8::internal::wasm::LiftoffAssembler::CallNativeWasmCode (Address addr) [inline]
Definition at line 4928 of file liftoff-assembler-arm-inl.h.
                                                      {
  Call(addr, RelocInfo::WASM_CALL);
}
References v8::internal::MacroAssembler::Call(), and v8::internal::RelocInfo::WASM_CALL.
CheckStackShrink()
void v8::internal::wasm::LiftoffAssembler::CheckStackShrink () [inline]
Definition at line 701 of file liftoff-assembler-arm-inl.h.
                                        {
  {
    UseScratchRegisterScope temps{this};
    Register scratch = temps.Acquire();
    ldr(scratch, MemOperand(fp, TypedFrameConstants::kFrameTypeOffset));
    cmp(scratch,
        Operand(StackFrame::TypeToMarker(StackFrame::WASM_SEGMENT_START)));
  }
  Label done;
  b(&done, ne);
  LiftoffRegList regs_to_save;
  for (auto reg : kGpReturnRegisters) regs_to_save.set(reg);
  for (auto reg : kFpReturnRegisters) regs_to_save.set(reg);
  PushRegisters(regs_to_save);
  MacroAssembler::Move(kCArgRegs[0], ExternalReference::isolate_address());
  PrepareCallCFunction(1);
  CallCFunction(ExternalReference::wasm_shrink_stack(), 1);
  // Restore old FP. We don't need to restore old SP explicitly, because
  // it will be restored from FP in LeaveFrame before return.
  mov(fp, kReturnRegister0);
  PopRegisters(regs_to_save);
  bind(&done);
}
References v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::MacroAssembler::CallCFunction(), v8::internal::Assembler::cmp(), v8::internal::ExternalReference::isolate_address(), v8::internal::kCArgRegs, v8::internal::wasm::kFpReturnRegisters, v8::internal::TypedFrameConstants::kFrameTypeOffset, v8::internal::wasm::kGpReturnRegisters, v8::internal::kReturnRegister0, v8::internal::Assembler::ldr(), v8::internal::MacroAssembler::mov(), v8::internal::MacroAssembler::Move(), v8::internal::ne, PopRegisters(), v8::internal::MacroAssembler::PrepareCallCFunction(), PushRegisters(), v8::internal::wasm::LiftoffRegList::set(), and v8::internal::StackFrame::TypeToMarker().
CheckTierUp()
void v8::internal::wasm::LiftoffAssembler::CheckTierUp (int declared_func_index, int budget_used, Label * ool_label, const FreezeCacheState & frozen) [inline]
Definition at line 639 of file liftoff-assembler-arm-inl.h.
                                                                   {
  {
    liftoff::CacheStatePreservingTempRegisters temps{this};
    Register budget_array = temps.Acquire();
    Register instance_data = cache_state_.cached_instance_data;
    if (instance_data == no_reg) {
      instance_data = budget_array; // Reuse the temp register.
      LoadInstanceDataFromFrame(instance_data);
    }
    constexpr int kArrayOffset = wasm::ObjectAccess::ToTagged(
        WasmTrustedInstanceData::kTieringBudgetArrayOffset);
    ldr(budget_array, MemOperand{instance_data, kArrayOffset});
    int budget_arr_offset = kInt32Size * declared_func_index;
    // If the offset cannot be used in the operand directly, add it once to the
    // budget array to avoid doing this multiple times below.
    if (!ImmediateFitsAddrMode2Instruction(budget_arr_offset)) {
      add(budget_array, budget_array, Operand{budget_arr_offset});
      budget_arr_offset = 0;
    }
    Register budget = temps.Acquire();
    MemOperand budget_addr{budget_array, budget_arr_offset};
    ldr(budget, budget_addr);
    sub(budget, budget, Operand{budget_used}, SetCC);
    str(budget, budget_addr);
  }
  b(ool_label, mi);
}
References v8::internal::Assembler::add(), v8::internal::Assembler::b(), cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data, v8::internal::Assembler::ImmediateFitsAddrMode2Instruction(), v8::internal::instance_data, v8::internal::kInt32Size, v8::internal::Assembler::ldr(), LoadInstanceDataFromFrame(), v8::internal::mi, v8::internal::no_reg, v8::internal::SetCC, v8::internal::Assembler::str(), v8::internal::Assembler::sub(), and v8::internal::wasm::ObjectAccess::ToTagged().
clear_i32_upper_half()
void v8::internal::wasm::LiftoffAssembler::clear_i32_upper_half (Register dst) [inline]
Definition at line 2015 of file liftoff-assembler-arm64-inl.h.
{ Uxtw(dst, dst); }
References v8::internal::MacroAssembler::Uxtw().
Referenced by FinishCall().
ClearRegister()
void v8::internal::wasm::LiftoffAssembler::ClearRegister (Register reg, std::initializer_list< Register * > possible_uses, LiftoffRegList pinned)
Definition at line 665 of file liftoff-assembler.cc.
                           {
  if (reg == cache_state()->cached_instance_data) {
    cache_state()->ClearCachedInstanceRegister();
    // We can return immediately. The instance is only used to load information
    // at the beginning of an instruction when values don't have to be in
    // specific registers yet. Therefore the instance should never be one of the
    // {possible_uses}.
#ifdef DEBUG
    for (Register* use : possible_uses) DCHECK_NE(reg, *use);
#endif
    return;
  } else if (reg == cache_state()->cached_mem_start) {
    cache_state()->ClearCachedMemStartRegister();
    // The memory start may be among the {possible_uses}, e.g. for an atomic
    // compare exchange. Therefore it is necessary to iterate over the
    // {possible_uses} below, and we cannot return early.
  } else if (cache_state()->is_used(LiftoffRegister(reg))) {
    SpillRegister(LiftoffRegister(reg));
  }
  Register replacement = no_reg;
  for (Register* use : possible_uses) {
    if (reg != *use) continue;
    if (replacement == no_reg) {
      replacement = GetUnusedRegister(kGpReg, pinned).gp();
      Move(replacement, reg, kIntPtrKind);
    }
    // We cannot leave this loop early. There may be multiple uses of {reg}.
    *use = replacement;
  }
}
References cache_state(), v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedInstanceRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedMemStartRegister(), DCHECK_NE, GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::kGpReg, kIntPtrKind, Move(), v8::internal::no_reg, SpillRegister(), and use().
DeallocateStackSlot()
void v8::internal::wasm::LiftoffAssembler::DeallocateStackSlot (uint32_t size) [inline]
Definition at line 4960 of file liftoff-assembler-arm-inl.h.
                                                        {
  add(sp, sp, Operand(size));
}
References v8::internal::Assembler::add(), and size().
did_bailout()
bool v8::internal::wasm::LiftoffAssembler::did_bailout () [inline]
Definition at line 1628 of file liftoff-assembler.h.
{ return bailout_reason_ != kSuccess; }
References bailout_reason_, and v8::internal::wasm::kSuccess.
DropExceptionValueAtOffset()
void v8::internal::wasm::LiftoffAssembler::DropExceptionValueAtOffset (int offset)
Definition at line 403 of file liftoff-assembler.cc.
                                                            {
  auto* dropped = cache_state_.stack_state.begin() + offset;
  if (dropped->is_reg()) {
    cache_state_.dec_used(dropped->reg());
  }
  // Compute the stack offset that the remaining slots are based on.
  int stack_offset =
      offset == 0 ? StaticStackFrameSize() : dropped[-1].offset();
  // Move remaining slots down.
  for (VarState *slot = dropped, *end = cache_state_.stack_state.end() - 1;
       slot != end; ++slot) {
    *slot = *(slot + 1);
    stack_offset = NextSpillOffset(slot->kind(), stack_offset);
    // Padding could cause some spill offsets to remain the same.
    if (slot->offset() != stack_offset) {
      if (slot->is_stack()) {
        MoveStackValue(stack_offset, slot->offset(), slot->kind());
      }
      slot->set_offset(stack_offset);
    }
  }
  cache_state_.stack_state.pop_back();
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::compiler::end(), MoveStackValue(), NextSpillOffset(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and StaticStackFrameSize().
DropStackSlotsAndRet()
void v8::internal::wasm::LiftoffAssembler::DropStackSlotsAndRet (uint32_t num_stack_slots) [inline]
Definition at line 4808 of file liftoff-assembler-arm-inl.h.
                                                                    {
  Drop(num_stack_slots);
  Ret();
}
References v8::internal::MacroAssembler::Drop(), and v8::internal::MacroAssembler::Ret().
DropValues()
void v8::internal::wasm::LiftoffAssembler::DropValues (int count) [inline]
Definition at line 469 of file liftoff-assembler.h.
                             {
    DCHECK_GE(cache_state_.stack_state.size(), count);
    for (VarState& slot :
         base::VectorOf(cache_state_.stack_state.end() - count, count)) {
      if (slot.is_reg()) {
        cache_state_.dec_used(slot.reg());
      }
    }
    cache_state_.stack_state.pop_back(count);
  }
References cache_state_, DCHECK_GE, v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and v8::base::VectorOf().
Referenced by PrepareCall().
emit_cond_jump()
void v8::internal::wasm::LiftoffAssembler::emit_cond_jump (Condition cond, Label * label, ValueKind value, Register lhs, Register rhs, const FreezeCacheState & frozen) [inline]
Definition at line 2557 of file liftoff-assembler-arm-inl.h.
                                                                      {
  if (rhs == no_reg) {
    DCHECK_EQ(kind, kI32);
    cmp(lhs, Operand(0));
  } else {
    DCHECK(kind == kI32 ||
           (is_reference(kind) && (cond == kEqual || cond == kNotEqual)));
    cmp(lhs, rhs);
  }
  b(label, cond);
}
References v8::internal::Assembler::b(), v8::internal::Assembler::cmp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::is_reference(), v8::internal::kEqual, v8::internal::kI32, v8::internal::kNotEqual, and v8::internal::no_reg.
emit_f16x8_abs()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4574 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_add()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4629 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_ceil()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_ceil (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4589 of file liftoff-assembler-arm-inl.h.
                                                            {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_demote_f32x4_zero()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_demote_f32x4_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4689 of file liftoff-assembler-arm-inl.h.
                                                                         {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_demote_f64x2_zero()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_demote_f64x2_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4699 of file liftoff-assembler-arm-inl.h.
                                                                         {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_div()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_div (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4644 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_eq()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4609 of file liftoff-assembler-arm-inl.h.
                                                          {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_extract_lane()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 4561 of file liftoff-assembler-arm-inl.h.
                                                                     {
  return false;
}
emit_f16x8_floor()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_floor (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4594 of file liftoff-assembler-arm-inl.h.
                                                             {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_le()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_le (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4624 of file liftoff-assembler-arm-inl.h.
                                                          {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_lt()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_lt (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4619 of file liftoff-assembler-arm-inl.h.
                                                          {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_max()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4654 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_min()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4649 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_mul()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4639 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_ne()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4614 of file liftoff-assembler-arm-inl.h.
                                                          {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_nearest_int()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_nearest_int (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4604 of file liftoff-assembler-arm-inl.h.
                                                                   {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_neg()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4579 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_pmax()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_pmax (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4664 of file liftoff-assembler-arm-inl.h.
                                                            {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_pmin()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_pmin (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4659 of file liftoff-assembler-arm-inl.h.
                                                            {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_qfma()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_qfma (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3) [inline]
Definition at line 4704 of file liftoff-assembler-arm-inl.h.
                                                             {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_qfms()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_qfms (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3) [inline]
Definition at line 4711 of file liftoff-assembler-arm-inl.h.
                                                             {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_replace_lane()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 4567 of file liftoff-assembler-arm-inl.h.
                                                                     {
  return false;
}
emit_f16x8_sconvert_i16x8()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_sconvert_i16x8 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4679 of file liftoff-assembler-arm-inl.h.
                                                                      {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_splat()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4556 of file liftoff-assembler-arm-inl.h.
                                                             {
  return false;
}
emit_f16x8_sqrt()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_sqrt (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4584 of file liftoff-assembler-arm-inl.h.
                                                            {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_sub()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4634 of file liftoff-assembler-arm-inl.h.
                                                           {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_trunc()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_trunc (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4599 of file liftoff-assembler-arm-inl.h.
                                                             {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f16x8_uconvert_i16x8()
bool v8::internal::wasm::LiftoffAssembler::emit_f16x8_uconvert_i16x8 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4684 of file liftoff-assembler-arm-inl.h.
                                                                      {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32_abs()
void v8::internal::wasm::LiftoffAssembler::emit_f32_abs (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 1873 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vabs(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vabs().
emit_f32_add()
void v8::internal::wasm::LiftoffAssembler::emit_f32_add (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1849 of file liftoff-assembler-arm-inl.h.
                                                        {
  vadd(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(lhs),
       liftoff::GetFloatRegister(rhs));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_ceil()
bool v8::internal::wasm::LiftoffAssembler::emit_f32_ceil (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2222 of file liftoff-assembler-arm-inl.h.
                                                                           {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintp(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
    return true;
  }
  return false;
}
References v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintp().
emit_f32_copysign()
void v8::internal::wasm::LiftoffAssembler::emit_f32_copysign (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2320 of file liftoff-assembler-arm-inl.h.
                                                             {
  constexpr uint32_t kF32SignBit = uint32_t{1} << 31;
  UseScratchRegisterScope temps(this);
  Register scratch = GetUnusedRegister(kGpReg, {}).gp();
  Register scratch2 = temps.Acquire();
  VmovLow(scratch, lhs);
  // Clear sign bit in {scratch}.
  bic(scratch, scratch, Operand(kF32SignBit));
  VmovLow(scratch2, rhs);
  // Isolate sign bit in {scratch2}.
  and_(scratch2, scratch2, Operand(kF32SignBit));
  // Combine {scratch2} into {scratch}.
  orr(scratch, scratch, scratch2);
  VmovLow(dst, scratch);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::and_(), v8::internal::Assembler::bic(), GetUnusedRegister(), v8::internal::wasm::kGpReg, v8::internal::Assembler::orr(), and v8::internal::MacroAssembler::VmovLow().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_div()
void v8::internal::wasm::LiftoffAssembler::emit_f32_div (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1867 of file liftoff-assembler-arm-inl.h.
                                                        {
  vdiv(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(lhs),
       liftoff::GetFloatRegister(rhs));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vdiv().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_floor()
bool v8::internal::wasm::LiftoffAssembler::emit_f32_floor (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2231 of file liftoff-assembler-arm-inl.h.
                                                                            {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintm(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
    return true;
  }
  return false;
}
References v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintm().
emit_f32_max()
void v8::internal::wasm::LiftoffAssembler::emit_f32_max (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2266 of file liftoff-assembler-arm-inl.h.
                                                        {
  liftoff::EmitFloatMinOrMax(
      this, liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(lhs),
      liftoff::GetFloatRegister(rhs), liftoff::MinOrMax::kMax);
}
References v8::internal::wasm::liftoff::EmitFloatMinOrMax(), v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::wasm::liftoff::kMax.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_min()
void v8::internal::wasm::LiftoffAssembler::emit_f32_min (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2259 of file liftoff-assembler-arm-inl.h.
                                                        {
  liftoff::EmitFloatMinOrMax(
      this, liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(lhs),
      liftoff::GetFloatRegister(rhs), liftoff::MinOrMax::kMin);
}
References v8::internal::wasm::liftoff::EmitFloatMinOrMax(), v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::wasm::liftoff::kMin.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_mul()
void v8::internal::wasm::LiftoffAssembler::emit_f32_mul (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1861 of file liftoff-assembler-arm-inl.h.
                                                        {
  vmul(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(lhs),
       liftoff::GetFloatRegister(rhs));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_nearest_int()
bool v8::internal::wasm::LiftoffAssembler::emit_f32_nearest_int (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2249 of file liftoff-assembler-arm-inl.h.
                                                                {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintn(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
    return true;
  }
  return false;
}
References v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintn().
emit_f32_neg()
void v8::internal::wasm::LiftoffAssembler::emit_f32_neg (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 1877 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vneg(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vneg().
emit_f32_set_cond()
void v8::internal::wasm::LiftoffAssembler::emit_f32_set_cond (Condition condition, Register dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2639 of file liftoff-assembler-arm-inl.h.
                                                             {
  VFPCompareAndSetFlags(liftoff::GetFloatRegister(lhs),
                        liftoff::GetFloatRegister(rhs));
  mov(dst, Operand(0), LeaveCC);
  mov(dst, Operand(1), LeaveCC, cond);
  if (cond != ne) {
    // If V flag set, at least one of the arguments was a Nan -> false.
    mov(dst, Operand(0), LeaveCC, vs);
  }
}
References v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::LeaveCC, v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::AssemblerRISCVV::vs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_sqrt()
void v8::internal::wasm::LiftoffAssembler::emit_f32_sqrt (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 1881 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vsqrt(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vsqrt().
emit_f32_sub()
void v8::internal::wasm::LiftoffAssembler::emit_f32_sub (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1855 of file liftoff-assembler-arm-inl.h.
                                                        {
  vsub(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(lhs),
       liftoff::GetFloatRegister(rhs));
}
References v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f32_trunc()
bool v8::internal::wasm::LiftoffAssembler::emit_f32_trunc (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2240 of file liftoff-assembler-arm-inl.h.
                                                                            {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintz(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
    return true;
  }
  return false;
}
References v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintz().
emit_f32x4_abs()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3050 of file liftoff-assembler-arm-inl.h.
                                                           {
  vabs(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vabs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_add()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3124 of file liftoff-assembler-arm-inl.h.
                                                           {
  vadd(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_ceil()
bool v8::internal::wasm::LiftoffAssembler::emit_f32x4_ceil (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3076 of file liftoff-assembler-arm-inl.h.
                                                            {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintp(NeonS32, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
  return true;
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::CpuFeatures::IsSupported(), v8::internal::NeonS32, and v8::internal::Assembler::vrintp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_demote_f64x2_zero()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_demote_f64x2_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4372 of file liftoff-assembler-arm-inl.h.
                                                                         {
  LowDwVfpRegister dst_d = LowDwVfpRegister::from_code(dst.low_fp().code());
  vcvt_f32_f64(dst_d.low(), src.low_fp());
  vcvt_f32_f64(dst_d.high(), src.high_fp());
  vmov(dst.high_fp(), 0);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::high(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LowDwVfpRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::Assembler::vcvt_f32_f64(), and v8::internal::Assembler::vmov().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_div()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_div (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3142 of file liftoff-assembler-arm-inl.h.
                                                           {
  // The list of d registers available to us is from d0 to d15, which always
  // maps to 2 s registers.
  LowDwVfpRegister dst_low = LowDwVfpRegister::from_code(dst.low_fp().code());
  LowDwVfpRegister lhs_low = LowDwVfpRegister::from_code(lhs.low_fp().code());
  LowDwVfpRegister rhs_low = LowDwVfpRegister::from_code(rhs.low_fp().code());
  LowDwVfpRegister dst_high = LowDwVfpRegister::from_code(dst.high_fp().code());
  LowDwVfpRegister lhs_high = LowDwVfpRegister::from_code(lhs.high_fp().code());
  LowDwVfpRegister rhs_high = LowDwVfpRegister::from_code(rhs.high_fp().code());
  vdiv(dst_low.low(), lhs_low.low(), rhs_low.low());
  vdiv(dst_low.high(), lhs_low.high(), rhs_low.high());
  vdiv(dst_high.low(), lhs_high.low(), rhs_high.low());
  vdiv(dst_high.high(), lhs_high.high(), rhs_high.high());
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::high(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LowDwVfpRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vdiv().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_eq()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4262 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vceq().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_extract_lane()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3034 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ExtractLane(liftoff::GetFloatRegister(dst.fp()),
              liftoff::GetSimd128Register(lhs), imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetFloatRegister(), and v8::internal::wasm::liftoff::GetSimd128Register().
emit_f32x4_floor()
bool v8::internal::wasm::LiftoffAssembler::emit_f32x4_floor (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3088 of file liftoff-assembler-arm-inl.h.
                                                             {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintm(NeonS32, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
  return true;
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::CpuFeatures::IsSupported(), v8::internal::NeonS32, and v8::internal::Assembler::vrintm().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_le()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_le (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4281 of file liftoff-assembler-arm-inl.h.
                                                          {
  vcge(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(rhs),
       liftoff::GetSimd128Register(lhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_lt()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_lt (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4275 of file liftoff-assembler-arm-inl.h.
                                                          {
  vcgt(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(rhs),
       liftoff::GetSimd128Register(lhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_max()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3166 of file liftoff-assembler-arm-inl.h.
                                                           {
  vmax(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_min()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3160 of file liftoff-assembler-arm-inl.h.
                                                           {
  vmin(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_mul()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3136 of file liftoff-assembler-arm-inl.h.
                                                           {
  vmul(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_ne()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4268 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
  vmvn(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(dst));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Assembler::vceq(), and v8::internal::Assembler::vmvn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_nearest_int()
bool v8::internal::wasm::LiftoffAssembler::emit_f32x4_nearest_int (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3112 of file liftoff-assembler-arm-inl.h.
                                                                   {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintn(NeonS32, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
  return true;
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::CpuFeatures::IsSupported(), v8::internal::NeonS32, and v8::internal::Assembler::vrintn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_neg()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3055 of file liftoff-assembler-arm-inl.h.
                                                           {
  vneg(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vneg().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_pmax()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_pmax (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3205 of file liftoff-assembler-arm-inl.h.
                                                            {
  UseScratchRegisterScope temps(this);
  QwNeonRegister tmp = liftoff::GetSimd128Register(dst);
  if (dst == lhs || dst == rhs) {
    tmp = temps.AcquireQ();
  }
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  vcgt(tmp, right, left);
  vbsl(tmp, right, left);
  if (dst == lhs || dst == rhs) {
    vmov(liftoff::GetSimd128Register(dst), tmp);
  }
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Assembler::vbsl(), v8::internal::Assembler::vcgt(), and v8::internal::Assembler::vmov().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_pmin()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_pmin (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3186 of file liftoff-assembler-arm-inl.h.
                                                            {
  UseScratchRegisterScope temps(this);
  QwNeonRegister tmp = liftoff::GetSimd128Register(dst);
  if (dst == lhs || dst == rhs) {
    tmp = temps.AcquireQ();
  }
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  vcgt(tmp, left, right);
  vbsl(tmp, right, left);
  if (dst == lhs || dst == rhs) {
    vmov(liftoff::GetSimd128Register(dst), tmp);
  }
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Assembler::vbsl(), v8::internal::Assembler::vcgt(), and v8::internal::Assembler::vmov().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_promote_low_f16x8()
bool v8::internal::wasm::LiftoffAssembler::emit_f32x4_promote_low_f16x8 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4694 of file liftoff-assembler-arm-inl.h.
                                                                         {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_qfma()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_qfma (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3) [inline]
Definition at line 4504 of file liftoff-assembler-arm-inl.h.
                                                             {
  UseScratchRegisterScope temps(this);
  Simd128Register scratch =
      dst == src3 ? temps.AcquireQ() : liftoff::GetSimd128Register(dst);
  vmul(scratch, liftoff::GetSimd128Register(src1),
       liftoff::GetSimd128Register(src2));
  vadd(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src3),
       scratch);
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Assembler::vadd(), and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_qfms()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_qfms (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3) [inline]
Definition at line 4517 of file liftoff-assembler-arm-inl.h.
                                                             {
  UseScratchRegisterScope temps(this);
  Simd128Register scratch =
      dst == src3 ? temps.AcquireQ() : liftoff::GetSimd128Register(dst);
  vmul(scratch, liftoff::GetSimd128Register(src1),
       liftoff::GetSimd128Register(src2));
  vsub(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src3),
       scratch);
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Assembler::vmul(), and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_relaxed_max()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_relaxed_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3179 of file liftoff-assembler-arm-inl.h.
                                                                   {
  vmax(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_relaxed_min()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_relaxed_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3172 of file liftoff-assembler-arm-inl.h.
                                                                   {
  vmin(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_replace_lane()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 3041 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ReplaceLane(liftoff::GetSimd128Register(dst),
              liftoff::GetSimd128Register(src1),
              liftoff::GetFloatRegister(src2.fp()), imm_lane_idx);
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::ReplaceLane().
emit_f32x4_sconvert_i32x4()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_sconvert_i32x4 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4360 of file liftoff-assembler-arm-inl.h.
                                                                      {
  vcvt_f32_s32(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcvt_f32_s32().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_splat()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3029 of file liftoff-assembler-arm-inl.h.
                                                             {
  vdup(Neon32, liftoff::GetSimd128Register(dst), src.fp(), 0);
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vdup().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_sqrt()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_sqrt (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3060 of file liftoff-assembler-arm-inl.h.
                                                            {
  // The list of d registers available to us is from d0 to d15, which always
  // maps to 2 s registers.
  LowDwVfpRegister dst_low = LowDwVfpRegister::from_code(dst.low_fp().code());
  LowDwVfpRegister src_low = LowDwVfpRegister::from_code(src.low_fp().code());
  LowDwVfpRegister dst_high = LowDwVfpRegister::from_code(dst.high_fp().code());
  LowDwVfpRegister src_high = LowDwVfpRegister::from_code(src.high_fp().code());
  vsqrt(dst_low.low(), src_low.low());
  vsqrt(dst_low.high(), src_low.high());
  vsqrt(dst_high.low(), src_high.low());
  vsqrt(dst_high.high(), src_high.high());
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::high(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LowDwVfpRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vsqrt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_sub()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3130 of file liftoff-assembler-arm-inl.h.
                                                           {
  vsub(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_trunc()
bool v8::internal::wasm::LiftoffAssembler::emit_f32x4_trunc (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3100 of file liftoff-assembler-arm-inl.h.
                                                             {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintz(NeonS32, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
  return true;
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::CpuFeatures::IsSupported(), v8::internal::NeonS32, and v8::internal::Assembler::vrintz().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f32x4_uconvert_i32x4()
void v8::internal::wasm::LiftoffAssembler::emit_f32x4_uconvert_i32x4 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4366 of file liftoff-assembler-arm-inl.h.
                                                                      {
  vcvt_f32_u32(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcvt_f32_u32().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64_abs()
void v8::internal::wasm::LiftoffAssembler::emit_f64_abs (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 1905 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vabs(dst, src);
}
References v8::internal::Assembler::vabs().
emit_f64_add()
void v8::internal::wasm::LiftoffAssembler::emit_f64_add (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1885 of file liftoff-assembler-arm-inl.h.
                                                        {
  vadd(dst, lhs, rhs);
}
References v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_ceil()
bool v8::internal::wasm::LiftoffAssembler::emit_f64_ceil (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2273 of file liftoff-assembler-arm-inl.h.
                                                                           {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintp(dst, src);
    return true;
  }
  return false;
}
References v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintp().
emit_f64_copysign()
void v8::internal::wasm::LiftoffAssembler::emit_f64_copysign (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2337 of file liftoff-assembler-arm-inl.h.
                                                             {
  constexpr uint32_t kF64SignBitHighWord = uint32_t{1} << 31;
  // On arm, we cannot hold the whole f64 value in a gp register, so we just
  // operate on the upper half (UH).
  UseScratchRegisterScope temps(this);
  Register scratch = GetUnusedRegister(kGpReg, {}).gp();
  Register scratch2 = temps.Acquire();
  VmovHigh(scratch, lhs);
  // Clear sign bit in {scratch}.
  bic(scratch, scratch, Operand(kF64SignBitHighWord));
  VmovHigh(scratch2, rhs);
  // Isolate sign bit in {scratch2}.
  and_(scratch2, scratch2, Operand(kF64SignBitHighWord));
  // Combine {scratch2} into {scratch}.
  orr(scratch, scratch, scratch2);
  vmov(dst, lhs);
  VmovHigh(dst, scratch);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::and_(), v8::internal::Assembler::bic(), GetUnusedRegister(), v8::internal::wasm::kGpReg, v8::internal::Assembler::orr(), v8::internal::Assembler::vmov(), and v8::internal::MacroAssembler::VmovHigh().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_div()
void v8::internal::wasm::LiftoffAssembler::emit_f64_div (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1900 of file liftoff-assembler-arm-inl.h.
                                                        {
  vdiv(dst, lhs, rhs);
}
References v8::internal::Assembler::vdiv().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_floor()
bool v8::internal::wasm::LiftoffAssembler::emit_f64_floor (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2282 of file liftoff-assembler-arm-inl.h.
                                                                            {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintm(dst, src);
    return true;
  }
  return false;
}
References v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintm().
emit_f64_max()
void v8::internal::wasm::LiftoffAssembler::emit_f64_max (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2315 of file liftoff-assembler-arm-inl.h.
                                                        {
  liftoff::EmitFloatMinOrMax(this, dst, lhs, rhs, liftoff::MinOrMax::kMax);
}
References v8::internal::wasm::liftoff::EmitFloatMinOrMax(), and v8::internal::wasm::liftoff::kMax.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_min()
void v8::internal::wasm::LiftoffAssembler::emit_f64_min (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2310 of file liftoff-assembler-arm-inl.h.
                                                        {
  liftoff::EmitFloatMinOrMax(this, dst, lhs, rhs, liftoff::MinOrMax::kMin);
}
References v8::internal::wasm::liftoff::EmitFloatMinOrMax(), and v8::internal::wasm::liftoff::kMin.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_mul()
void v8::internal::wasm::LiftoffAssembler::emit_f64_mul (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1895 of file liftoff-assembler-arm-inl.h.
                                                        {
  vmul(dst, lhs, rhs);
}
References v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_nearest_int()
bool v8::internal::wasm::LiftoffAssembler::emit_f64_nearest_int (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2300 of file liftoff-assembler-arm-inl.h.
                                                                {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintn(dst, src);
    return true;
  }
  return false;
}
References v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintn().
emit_f64_neg()
void v8::internal::wasm::LiftoffAssembler::emit_f64_neg (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 1909 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vneg(dst, src);
}
References v8::internal::Assembler::vneg().
emit_f64_set_cond()
void v8::internal::wasm::LiftoffAssembler::emit_f64_set_cond (Condition condition, Register dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 2652 of file liftoff-assembler-arm-inl.h.
                                                             {
  VFPCompareAndSetFlags(lhs, rhs);
  mov(dst, Operand(0), LeaveCC);
  mov(dst, Operand(1), LeaveCC, cond);
  if (cond != ne) {
    // If V flag set, at least one of the arguments was a Nan -> false.
    mov(dst, Operand(0), LeaveCC, vs);
  }
}
References v8::internal::LeaveCC, v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::AssemblerRISCVV::vs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_sqrt()
void v8::internal::wasm::LiftoffAssembler::emit_f64_sqrt (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 1913 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vsqrt(dst, src);
}
References v8::internal::Assembler::vsqrt().
emit_f64_sub()
void v8::internal::wasm::LiftoffAssembler::emit_f64_sub (DoubleRegister dst, DoubleRegister lhs, DoubleRegister rhs) [inline]
Definition at line 1890 of file liftoff-assembler-arm-inl.h.
                                                        {
  vsub(dst, lhs, rhs);
}
References v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_f64_trunc()
bool v8::internal::wasm::LiftoffAssembler::emit_f64_trunc (DoubleRegister dst, DoubleRegister src) [inline]
Definition at line 2291 of file liftoff-assembler-arm-inl.h.
                                                                            {
  if (CpuFeatures::IsSupported(ARMv8)) {
    CpuFeatureScope scope(this, ARMv8);
    vrintz(dst, src);
    return true;
  }
  return false;
}
References v8::internal::CpuFeatures::IsSupported(), and v8::internal::Assembler::vrintz().
emit_f64x2_abs()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2857 of file liftoff-assembler-arm-inl.h.
                                                           {
  vabs(dst.low_fp(), src.low_fp());
  vabs(dst.high_fp(), src.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vabs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_add()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2923 of file liftoff-assembler-arm-inl.h.
                                                           {
  vadd(dst.low_fp(), lhs.low_fp(), rhs.low_fp());
  vadd(dst.high_fp(), lhs.high_fp(), rhs.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_ceil()
bool v8::internal::wasm::LiftoffAssembler::emit_f64x2_ceil (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2875 of file liftoff-assembler-arm-inl.h.
                                                            {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintp(dst.low_fp(), src.low_fp());
  vrintp(dst.high_fp(), src.high_fp());
  return true;
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vrintp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_convert_low_i32x4_s()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_convert_low_i32x4_s (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3011 of file liftoff-assembler-arm-inl.h.
                                                                           {
  F64x2ConvertLowI32x4S(liftoff::GetSimd128Register(dst),
                        liftoff::GetSimd128Register(src));
}
References v8::internal::MacroAssembler::F64x2ConvertLowI32x4S(), and v8::internal::wasm::liftoff::GetSimd128Register().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_convert_low_i32x4_u()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_convert_low_i32x4_u (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3017 of file liftoff-assembler-arm-inl.h.
                                                                           {
  F64x2ConvertLowI32x4U(liftoff::GetSimd128Register(dst),
                        liftoff::GetSimd128Register(src));
}
References v8::internal::MacroAssembler::F64x2ConvertLowI32x4U(), and v8::internal::wasm::liftoff::GetSimd128Register().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_div()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_div (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2941 of file liftoff-assembler-arm-inl.h.
                                                           {
  vdiv(dst.low_fp(), lhs.low_fp(), rhs.low_fp());
  vdiv(dst.high_fp(), lhs.high_fp(), rhs.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vdiv().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_eq()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4287 of file liftoff-assembler-arm-inl.h.
                                                          {
  liftoff::F64x2Compare(this, dst, lhs, rhs, eq);
}
References v8::internal::eq, and v8::internal::wasm::liftoff::F64x2Compare().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_extract_lane()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 2843 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ExtractLane(dst.fp(), liftoff::GetSimd128Register(lhs), imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::LiftoffRegister::fp(), and v8::internal::wasm::liftoff::GetSimd128Register().
emit_f64x2_floor()
bool v8::internal::wasm::LiftoffAssembler::emit_f64x2_floor (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2887 of file liftoff-assembler-arm-inl.h.
                                                             {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintm(dst.low_fp(), src.low_fp());
  vrintm(dst.high_fp(), src.high_fp());
  return true;
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vrintm().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_le()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_le (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4302 of file liftoff-assembler-arm-inl.h.
                                                          {
  liftoff::F64x2Compare(this, dst, lhs, rhs, le);
}
References v8::internal::wasm::liftoff::F64x2Compare(), and v8::internal::le.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_lt()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_lt (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4297 of file liftoff-assembler-arm-inl.h.
                                                          {
  liftoff::F64x2Compare(this, dst, lhs, rhs, lt);
}
References v8::internal::wasm::liftoff::F64x2Compare(), and v8::internal::lt.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_max()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2959 of file liftoff-assembler-arm-inl.h.
                                                           {
  Simd128Register dest = liftoff::GetSimd128Register(dst);
  Simd128Register left = liftoff::GetSimd128Register(lhs);
  Simd128Register right = liftoff::GetSimd128Register(rhs);
  liftoff::EmitFloatMinOrMax(this, dest.low(), left.low(), right.low(),
                             liftoff::MinOrMax::kMax);
  liftoff::EmitFloatMinOrMax(this, dest.high(), left.high(), right.high(),
                             liftoff::MinOrMax::kMax);
}
References v8::internal::wasm::liftoff::EmitFloatMinOrMax(), v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::wasm::liftoff::kMax.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_min()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2947 of file liftoff-assembler-arm-inl.h.
                                                           {
  Simd128Register dest = liftoff::GetSimd128Register(dst);
  Simd128Register left = liftoff::GetSimd128Register(lhs);
  Simd128Register right = liftoff::GetSimd128Register(rhs);
  liftoff::EmitFloatMinOrMax(this, dest.low(), left.low(), right.low(),
                             liftoff::MinOrMax::kMin);
  liftoff::EmitFloatMinOrMax(this, dest.high(), left.high(), right.high(),
                             liftoff::MinOrMax::kMin);
}
References v8::internal::wasm::liftoff::EmitFloatMinOrMax(), v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::wasm::liftoff::kMin.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_mul()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2935 of file liftoff-assembler-arm-inl.h.
                                                           {
  vmul(dst.low_fp(), lhs.low_fp(), rhs.low_fp());
  vmul(dst.high_fp(), lhs.high_fp(), rhs.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_ne()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4292 of file liftoff-assembler-arm-inl.h.
                                                          {
  liftoff::F64x2Compare(this, dst, lhs, rhs, ne);
}
References v8::internal::wasm::liftoff::F64x2Compare(), and v8::internal::ne.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_nearest_int()
bool v8::internal::wasm::LiftoffAssembler::emit_f64x2_nearest_int (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2911 of file liftoff-assembler-arm-inl.h.
                                                                   {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintn(dst.low_fp(), src.low_fp());
  vrintn(dst.high_fp(), src.high_fp());
  return true;
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vrintn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_neg()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2863 of file liftoff-assembler-arm-inl.h.
                                                           {
  vneg(dst.low_fp(), src.low_fp());
  vneg(dst.high_fp(), src.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vneg().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_pmax()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmax (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2985 of file liftoff-assembler-arm-inl.h.
                                                            {
  QwNeonRegister dest = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  VFPCompareAndSetFlags(right.low(), left.low());
  if (dst != rhs) vmov(dest.low(), right.low(), gt);
  if (dst != lhs) vmov(dest.low(), left.low(), NegateCondition(gt));
  VFPCompareAndSetFlags(right.high(), left.high());
  if (dst != rhs) vmov(dest.high(), right.high(), gt);
  if (dst != lhs) vmov(dest.high(), left.high(), NegateCondition(gt));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::gt, v8::internal::QwNeonRegister::high(), v8::internal::QwNeonRegister::low(), v8::internal::NegateCondition(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::Assembler::vmov().
Referenced by emit_f64x2_relaxed_max(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_pmin()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmin (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2971 of file liftoff-assembler-arm-inl.h.
                                                            {
  QwNeonRegister dest = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  VFPCompareAndSetFlags(right.low(), left.low());
  if (dst != rhs) vmov(dest.low(), right.low(), mi);
  if (dst != lhs) vmov(dest.low(), left.low(), NegateCondition(mi));
  VFPCompareAndSetFlags(right.high(), left.high());
  if (dst != rhs) vmov(dest.high(), right.high(), mi);
  if (dst != lhs) vmov(dest.high(), left.high(), NegateCondition(mi));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::QwNeonRegister::high(), v8::internal::QwNeonRegister::low(), v8::internal::mi, v8::internal::NegateCondition(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), and v8::internal::Assembler::vmov().
Referenced by emit_f64x2_relaxed_min(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_promote_low_f32x4()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_promote_low_f32x4 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3023 of file liftoff-assembler-arm-inl.h.
                                                                         {
  F64x2PromoteLowF32x4(liftoff::GetSimd128Register(dst),
                       liftoff::GetSimd128Register(src));
}
References v8::internal::MacroAssembler::F64x2PromoteLowF32x4(), and v8::internal::wasm::liftoff::GetSimd128Register().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_qfma()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfma (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3) [inline]
Definition at line 4530 of file liftoff-assembler-arm-inl.h.
                                                             {
  UseScratchRegisterScope temps(this);
  Simd128Register scratch =
      dst == src3 ? temps.AcquireQ() : liftoff::GetSimd128Register(dst);
  vmul(scratch.low(), src1.low_fp(), src2.low_fp());
  vmul(scratch.high(), src1.high_fp(), src2.high_fp());
  vadd(dst.low_fp(), src3.low_fp(), scratch.low());
  vadd(dst.high_fp(), src3.high_fp(), scratch.high());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::Assembler::vadd(), and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_qfms()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_qfms (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister src3) [inline]
Definition at line 4543 of file liftoff-assembler-arm-inl.h.
                                                             {
  UseScratchRegisterScope temps(this);
  Simd128Register scratch =
      dst == src3 ? temps.AcquireQ() : liftoff::GetSimd128Register(dst);
  vmul(scratch.low(), src1.low_fp(), src2.low_fp());
  vmul(scratch.high(), src1.high_fp(), src2.high_fp());
  vsub(dst.low_fp(), src3.low_fp(), scratch.low());
  vsub(dst.high_fp(), src3.high_fp(), scratch.high());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::Assembler::vmul(), and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_relaxed_max()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_relaxed_max (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3005 of file liftoff-assembler-arm-inl.h.
                                                                   {
  emit_f64x2_pmax(dst, lhs, rhs);
}
References emit_f64x2_pmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_relaxed_min()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_relaxed_min (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2999 of file liftoff-assembler-arm-inl.h.
                                                                   {
  emit_f64x2_pmin(dst, lhs, rhs);
}
References emit_f64x2_pmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_replace_lane()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 2849 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ReplaceLane(liftoff::GetSimd128Register(dst),
              liftoff::GetSimd128Register(src1), src2.fp(), imm_lane_idx);
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::ReplaceLane().
emit_f64x2_splat()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2837 of file liftoff-assembler-arm-inl.h.
                                                             {
  MacroAssembler::Move(dst.low_fp(), src.fp());
  MacroAssembler::Move(dst.high_fp(), src.fp());
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::MacroAssembler::Move().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_sqrt()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_sqrt (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2869 of file liftoff-assembler-arm-inl.h.
                                                            {
  vsqrt(dst.low_fp(), src.low_fp());
  vsqrt(dst.high_fp(), src.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vsqrt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_sub()
void v8::internal::wasm::LiftoffAssembler::emit_f64x2_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2929 of file liftoff-assembler-arm-inl.h.
                                                           {
  vsub(dst.low_fp(), lhs.low_fp(), rhs.low_fp());
  vsub(dst.high_fp(), lhs.high_fp(), rhs.high_fp());
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_f64x2_trunc()
bool v8::internal::wasm::LiftoffAssembler::emit_f64x2_trunc (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2899 of file liftoff-assembler-arm-inl.h.
                                                             {
  if (!CpuFeatures::IsSupported(ARMv8)) {
    return false;
  }
  CpuFeatureScope scope(this, ARMv8);
  vrintz(dst.low_fp(), src.low_fp());
  vrintz(dst.high_fp(), src.high_fp());
  return true;
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vrintz().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_abs()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4487 of file liftoff-assembler-arm-inl.h.
                                                           {
  vabs(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, and v8::internal::Assembler::vabs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_add()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3696 of file liftoff-assembler-arm-inl.h.
                                                           {
  vadd(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_add_sat_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_add_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3702 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqadd(NeonS16, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vqadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_add_sat_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_add_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3735 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqadd(NeonU16, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vqadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_alltrue()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_alltrue (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3624 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  DwVfpRegister scratch = temps.AcquireD();
  vpmin(NeonU16, scratch, src.low_fp(), src.high_fp());
  vpmin(NeonU16, scratch, scratch, scratch);
  vpmin(NeonU16, scratch, scratch, scratch);
  ExtractLane(dst.gp(), scratch, NeonS16, 0);
  cmp(dst.gp(), Operand(0));
  mov(dst.gp(), Operand(1), LeaveCC, ne);
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::Assembler::cmp(), v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::NeonS16, v8::internal::NeonU16, and v8::internal::Assembler::vpmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_bitmask()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_bitmask (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3636 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  Simd128Register tmp = liftoff::GetSimd128Register(src);
  Simd128Register mask = temps.AcquireQ();
  if (cache_state()->is_used(src)) {
    // We only have 1 scratch Q register, so try and reuse src.
    LiftoffRegList pinned{src};
    LiftoffRegister unused_pair = GetUnusedRegister(kFpRegPair, pinned);
    mask = liftoff::GetSimd128Register(unused_pair);
  }
  vshr(NeonS16, tmp, liftoff::GetSimd128Register(src), 15);
  // Set i-th bit of each lane i. When AND with tmp, the lanes that
  // are signed will have i-th bit set, unsigned will be 0.
  vmov(mask.low(), base::Double((uint64_t)0x0008'0004'0002'0001));
  vmov(mask.high(), base::Double((uint64_t)0x0080'0040'0020'0010));
  vand(tmp, mask, tmp);
  vpadd(Neon16, tmp.low(), tmp.low(), tmp.high());
  vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
  vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
  vmov(NeonU16, dst.gp(), tmp.low(), 0);
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), cache_state(), v8::internal::wasm::liftoff::GetSimd128Register(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::kFpRegPair, v8::internal::Neon16, v8::internal::NeonS16, v8::internal::NeonU16, v8::internal::Assembler::vand(), v8::internal::Assembler::vmov(), v8::internal::Assembler::vpadd(), and v8::internal::Assembler::vshr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_dot_i8x16_i7x16_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_dot_i8x16_i7x16_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3847 of file liftoff-assembler-arm-inl.h.
                                                                         {
  QwNeonRegister dest = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  UseScratchRegisterScope temps(this);
  Simd128Register scratch = temps.AcquireQ();
  vmull(NeonS8, scratch, left.low(), right.low());
  vpadd(Neon16, dest.low(), scratch.low(), scratch.high());
  vmull(NeonS8, scratch, left.high(), right.high());
  vpadd(Neon16, dest.high(), scratch.low(), scratch.high());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::QwNeonRegister::high(), v8::internal::QwNeonRegister::low(), v8::internal::Neon16, v8::internal::NeonS8, v8::internal::Assembler::vmull(), and v8::internal::Assembler::vpadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_eq()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4164 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, and v8::internal::Assembler::vceq().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extadd_pairwise_i8x16_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extadd_pairwise_i8x16_s (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3793 of file liftoff-assembler-arm-inl.h.
                                                                               {
  vpaddl(NeonS8, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vpaddl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extadd_pairwise_i8x16_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extadd_pairwise_i8x16_u (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3799 of file liftoff-assembler-arm-inl.h.
                                                                               {
  vpaddl(NeonU8, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vpaddl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extmul_high_i8x16_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_high_i8x16_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3817 of file liftoff-assembler-arm-inl.h.
                                                                            {
  vmull(NeonS8, liftoff::GetSimd128Register(dst), src1.high_fp(),
        src2.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonS8, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extmul_high_i8x16_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_high_i8x16_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3824 of file liftoff-assembler-arm-inl.h.
                                                                            {
  vmull(NeonU8, liftoff::GetSimd128Register(dst), src1.high_fp(),
        src2.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonU8, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extmul_low_i8x16_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_low_i8x16_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3805 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmull(NeonS8, liftoff::GetSimd128Register(dst), src1.low_fp(), src2.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonS8, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extmul_low_i8x16_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extmul_low_i8x16_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3811 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmull(NeonU8, liftoff::GetSimd128Register(dst), src1.low_fp(), src2.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonU8, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_extract_lane_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extract_lane_s (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3777 of file liftoff-assembler-arm-inl.h.
                                                                       {
  ExtractLane(dst.gp(), liftoff::GetSimd128Register(lhs), NeonS16,
              imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::NeonS16.
emit_i16x8_extract_lane_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_extract_lane_u (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3770 of file liftoff-assembler-arm-inl.h.
                                                                       {
  ExtractLane(dst.gp(), liftoff::GetSimd128Register(lhs), NeonU16,
              imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::NeonU16.
emit_i16x8_ge_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4189 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcge(NeonS16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_ge_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_ge_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4195 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcge(NeonU16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_gt_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4177 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcgt(NeonS16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_gt_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_gt_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4183 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcgt(NeonU16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_max_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_max_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3756 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmax(NeonS16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_max_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_max_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3763 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmax(NeonU16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_min_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_min_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3742 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmin(NeonS16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_min_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_min_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3749 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmin(NeonU16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_mul()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3729 of file liftoff-assembler-arm-inl.h.
                                                           {
  vmul(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_ne()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4170 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
  vmvn(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(dst));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, v8::internal::Assembler::vceq(), and v8::internal::Assembler::vmvn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_neg()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3618 of file liftoff-assembler-arm-inl.h.
                                                           {
  vneg(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, and v8::internal::Assembler::vneg().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_q15mulr_sat_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_q15mulr_sat_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3831 of file liftoff-assembler-arm-inl.h.
                                                                      {
  vqrdmulh(NeonS16, liftoff::GetSimd128Register(dst),
           liftoff::GetSimd128Register(src1),
           liftoff::GetSimd128Register(src2));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vqrdmulh().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_relaxed_q15mulr_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_relaxed_q15mulr_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3839 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vqrdmulh(NeonS16, liftoff::GetSimd128Register(dst),
           liftoff::GetSimd128Register(src1),
           liftoff::GetSimd128Register(src2));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vqrdmulh().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_replace_lane()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 3784 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ReplaceLane(liftoff::GetSimd128Register(dst),
              liftoff::GetSimd128Register(src1), src2.gp(), NeonS16,
              imm_lane_idx);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::NeonS16, and v8::internal::MacroAssembler::ReplaceLane().
emit_i16x8_rounding_average_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_rounding_average_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4474 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vrhadd(NeonU16, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vrhadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sconvert_f16x8()
bool v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_f16x8 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4669 of file liftoff-assembler-arm-inl.h.
                                                                      {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sconvert_i32x4()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i32x4 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4392 of file liftoff-assembler-arm-inl.h.
                                                                      {
  liftoff::S128NarrowOp(this, NeonS16, NeonS16, dst, lhs, rhs);
}
References v8::internal::NeonS16, and v8::internal::wasm::liftoff::S128NarrowOp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sconvert_i8x16_high()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i8x16_high (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4409 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmovl(NeonS8, liftoff::GetSimd128Register(dst), src.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonS8, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sconvert_i8x16_low()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_sconvert_i8x16_low (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4404 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vmovl(NeonS8, liftoff::GetSimd128Register(dst), src.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonS8, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_shl()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3661 of file liftoff-assembler-arm-inl.h.
                                                           {
  liftoff::EmitSimdShift<liftoff::kLeft, NeonS16, Neon16>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_shli()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3666 of file liftoff-assembler-arm-inl.h.
                                                    {
  vshl(NeonS16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), rhs & 15);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vshl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_shr_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3672 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonS16, Neon16>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_shr_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3684 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonU16, Neon16>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_shri_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3678 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonS16>(this, dst, lhs,
                                                            rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_shri_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3690 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonU16>(this, dst, lhs,
                                                            rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_splat()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3613 of file liftoff-assembler-arm-inl.h.
                                                             {
  vdup(Neon16, liftoff::GetSimd128Register(dst), src.gp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::Neon16, and v8::internal::Assembler::vdup().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sub()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3709 of file liftoff-assembler-arm-inl.h.
                                                           {
  vsub(Neon16, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon16, and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sub_sat_s()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_sub_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3715 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqsub(NeonS16, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vqsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_sub_sat_u()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_sub_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3722 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqsub(NeonU16, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vqsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_uconvert_f16x8()
bool v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_f16x8 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4674 of file liftoff-assembler-arm-inl.h.
                                                                      {
  return false;
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_uconvert_i32x4()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i32x4 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4398 of file liftoff-assembler-arm-inl.h.
                                                                      {
  liftoff::S128NarrowOp(this, NeonU16, NeonS16, dst, lhs, rhs);
}
References v8::internal::NeonS16, v8::internal::NeonU16, and v8::internal::wasm::liftoff::S128NarrowOp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_uconvert_i8x16_high()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i8x16_high (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4419 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmovl(NeonU8, liftoff::GetSimd128Register(dst), src.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonU8, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i16x8_uconvert_i8x16_low()
void v8::internal::wasm::LiftoffAssembler::emit_i16x8_uconvert_i8x16_low (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4414 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vmovl(NeonU8, liftoff::GetSimd128Register(dst), src.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonU8, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32_add()
void v8::internal::wasm::LiftoffAssembler::emit_i32_add (Register dst, Register lhs, Register rhs) [inline]
Definition at line 1752 of file liftoff-assembler-arm-inl.h.
                                                                            {
  add(dst, lhs, rhs);
}
References v8::internal::Assembler::add().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_add().
emit_i32_addi()
void v8::internal::wasm::LiftoffAssembler::emit_i32_addi (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 1755 of file liftoff-assembler-arm-inl.h.
                                                                            {
  add(dst, lhs, Operand(imm));
}
References v8::internal::Assembler::add().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_addi().
emit_i32_and()
void v8::internal::wasm::LiftoffAssembler::emit_i32_and (Register dst, Register lhs, Register rhs) [inline]
Definition at line 1780 of file liftoff-assembler-arm-inl.h.
                                                                            {
  and_(dst, lhs, rhs);
}
References v8::internal::Assembler::and_().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_and().
emit_i32_andi()
void v8::internal::wasm::LiftoffAssembler::emit_i32_andi (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 1783 of file liftoff-assembler-arm-inl.h.
                                                                            {
  and_(dst, lhs, Operand(imm));
}
References v8::internal::Assembler::and_().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_clz()
void v8::internal::wasm::LiftoffAssembler::emit_i32_clz (Register dst, Register src) [inline]
Definition at line 1917 of file liftoff-assembler-arm-inl.h.
                                                              {
  clz(dst, src);
}
References v8::internal::Assembler::clz().
emit_i32_cond_jumpi()
void v8::internal::wasm::LiftoffAssembler::emit_i32_cond_jumpi (Condition cond, Label * label, Register lhs, int imm, const FreezeCacheState & frozen) [inline]
Definition at line 2572 of file liftoff-assembler-arm-inl.h.
                                                                           {
  cmp(lhs, Operand(imm));
  b(label, cond);
}
References v8::internal::Assembler::b(), and v8::internal::Assembler::cmp().
emit_i32_ctz()
void v8::internal::wasm::LiftoffAssembler::emit_i32_ctz (Register dst, Register src) [inline]
Definition at line 1921 of file liftoff-assembler-arm-inl.h.
                                                              {
  rbit(dst, src);
  clz(dst, dst);
}
References v8::internal::Assembler::clz(), and v8::internal::Assembler::rbit().
emit_i32_divs()
void v8::internal::wasm::LiftoffAssembler::emit_i32_divs (Register dst, Register lhs, Register rhs, Label * trap_div_by_zero, Label * trap_div_unrepresentable) [inline]
Definition at line 1959 of file liftoff-assembler-arm-inl.h.
                                                                      {
  if (!CpuFeatures::IsSupported(SUDIV)) {
    bailout(kMissingCPUFeature, "i32_divs");
    return;
  }
  CpuFeatureScope scope(this, SUDIV);
  // Issue division early so we can perform the trapping checks whilst it
  // completes.
  bool speculative_sdiv = dst != lhs && dst != rhs;
  if (speculative_sdiv) {
    sdiv(dst, lhs, rhs);
  }
  Label noTrap;
  // Check for division by zero.
  cmp(rhs, Operand(0));
  b(trap_div_by_zero, eq);
  // Check for kMinInt / -1. This is unrepresentable.
  cmp(rhs, Operand(-1));
  b(&noTrap, ne);
  cmp(lhs, Operand(kMinInt));
  b(trap_div_unrepresentable, eq);
  bind(&noTrap);
  if (!speculative_sdiv) {
    sdiv(dst, lhs, rhs);
  }
}
References v8::internal::Assembler::b(), bailout(), v8::internal::Assembler::bind(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::CpuFeatures::IsSupported(), v8::internal::kMinInt, v8::internal::wasm::kMissingCPUFeature, v8::internal::ne, and v8::internal::Assembler::sdiv().
emit_i32_divu()
void v8::internal::wasm::LiftoffAssembler::emit_i32_divu (Register dst, Register lhs, Register rhs, Label * trap_div_by_zero) [inline]
Definition at line 1988 of file liftoff-assembler-arm-inl.h.
                                                              {
  if (!CpuFeatures::IsSupported(SUDIV)) {
    bailout(kMissingCPUFeature, "i32_divu");
    return;
  }
  CpuFeatureScope scope(this, SUDIV);
  // Check for division by zero.
  cmp(rhs, Operand(0));
  b(trap_div_by_zero, eq);
  udiv(dst, lhs, rhs);
}
References v8::internal::Assembler::b(), bailout(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::kMissingCPUFeature, and v8::internal::Assembler::udiv().
emit_i32_eqz()
void v8::internal::wasm::LiftoffAssembler::emit_i32_eqz (Register dst, Register src) [inline]
Definition at line 2579 of file liftoff-assembler-arm-inl.h.
                                                              {
  clz(dst, src);
  mov(dst, Operand(dst, LSR, kRegSizeInBitsLog2));
}
References v8::internal::Assembler::clz(), v8::internal::kRegSizeInBitsLog2, v8::internal::LSR, and v8::internal::MacroAssembler::mov().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp().
emit_i32_mul()
void v8::internal::wasm::LiftoffAssembler::emit_i32_mul (Register dst, Register lhs, Register rhs) [inline]
Definition at line 1766 of file liftoff-assembler-arm-inl.h.
                                                                            {
  mul(dst, lhs, rhs);
}
References v8::internal::Assembler::mul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_muli()
void v8::internal::wasm::LiftoffAssembler::emit_i32_muli (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 1769 of file liftoff-assembler-arm-inl.h.
                                                                            {
  if (base::bits::IsPowerOfTwo(imm)) {
    emit_i32_shli(dst, lhs, base::bits::WhichPowerOfTwo(imm));
    return;
  }
  UseScratchRegisterScope temps{this};
  Register scratch = temps.Acquire();
  mov(scratch, Operand{imm});
  mul(dst, lhs, scratch);
}
References emit_i32_shli(), v8::base::bits::IsPowerOfTwo(), v8::internal::MacroAssembler::mov(), v8::internal::Assembler::mul(), and v8::base::bits::WhichPowerOfTwo().
Referenced by emit_ptrsize_muli().
emit_i32_or()
void v8::internal::wasm::LiftoffAssembler::emit_i32_or (Register dst, Register lhs, Register rhs) [inline]
Definition at line 1787 of file liftoff-assembler-arm-inl.h.
                                                                           {
  orr(dst, lhs, rhs);
}
References v8::internal::Assembler::orr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_ori()
void v8::internal::wasm::LiftoffAssembler::emit_i32_ori (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 1790 of file liftoff-assembler-arm-inl.h.
                                                                           {
  orr(dst, lhs, Operand(imm));
}
References v8::internal::Assembler::orr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_popcnt()
bool v8::internal::wasm::LiftoffAssembler::emit_i32_popcnt (Register dst, Register src) [inline]
Definition at line 1951 of file liftoff-assembler-arm-inl.h.
                                                                 {
  LiftoffRegList pinned{dst};
  Register scratch1 = pinned.set(GetUnusedRegister(kGpReg, pinned)).gp();
  Register scratch2 = GetUnusedRegister(kGpReg, pinned).gp();
  liftoff::GeneratePopCnt(this, dst, src, scratch1, scratch2);
  return true;
}
References v8::internal::wasm::liftoff::GeneratePopCnt(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::kGpReg, and v8::internal::wasm::LiftoffRegList::set().
emit_i32_rems()
void v8::internal::wasm::LiftoffAssembler::emit_i32_rems (Register dst, Register lhs, Register rhs, Label * trap_rem_by_zero) [inline]
Definition at line 2001 of file liftoff-assembler-arm-inl.h.
                                                              {
  if (!CpuFeatures::IsSupported(SUDIV)) {
    // When this case is handled, a check for ARMv7 is required to use mls.
    // Mls support is implied with SUDIV support.
    bailout(kMissingCPUFeature, "i32_rems");
    return;
  }
  CpuFeatureScope scope(this, SUDIV);
  // No need to check kMinInt / -1 because the result is kMinInt and then
  // kMinInt * -1 -> kMinInt. In this case, the Msub result is therefore 0.
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  sdiv(scratch, lhs, rhs);
  // Check for division by zero.
  cmp(rhs, Operand(0));
  b(trap_div_by_zero, eq);
  // Compute remainder.
  mls(dst, scratch, rhs, lhs);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::b(), bailout(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::kMissingCPUFeature, v8::internal::Assembler::mls(), and v8::internal::Assembler::sdiv().
emit_i32_remu()
void v8::internal::wasm::LiftoffAssembler::emit_i32_remu (Register dst, Register lhs, Register rhs, Label * trap_rem_by_zero) [inline]
Definition at line 2022 of file liftoff-assembler-arm-inl.h.
                                                              {
  if (!CpuFeatures::IsSupported(SUDIV)) {
    // When this case is handled, a check for ARMv7 is required to use mls.
    // Mls support is implied with SUDIV support.
    bailout(kMissingCPUFeature, "i32_remu");
    return;
  }
  CpuFeatureScope scope(this, SUDIV);
  // No need to check kMinInt / -1 because the result is kMinInt and then
  // kMinInt * -1 -> kMinInt. In this case, the Msub result is therefore 0.
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  udiv(scratch, lhs, rhs);
  // Check for division by zero.
  cmp(rhs, Operand(0));
  b(trap_div_by_zero, eq);
  // Compute remainder.
  mls(dst, scratch, rhs, lhs);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::b(), bailout(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::CpuFeatures::IsSupported(), v8::internal::wasm::kMissingCPUFeature, v8::internal::Assembler::mls(), and v8::internal::Assembler::udiv().
emit_i32_sar()
void v8::internal::wasm::LiftoffAssembler::emit_i32_sar (Register dst, Register src, Register amount) [inline]
Definition at line 1817 of file liftoff-assembler-arm-inl.h.
                                                     {
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  and_(scratch, amount, Operand(0x1f));
  asr(dst, src, Operand(scratch));
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::and_(), and v8::internal::Assembler::asr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_sari()
void v8::internal::wasm::LiftoffAssembler::emit_i32_sari (Register dst, Register src, int32_t amount) [inline]
Definition at line 1824 of file liftoff-assembler-arm-inl.h.
                                                     {
  if (V8_LIKELY((amount & 31) != 0)) {
    asr(dst, src, Operand(amount & 31));
  } else if (dst != src) {
    mov(dst, src);
  }
}
References v8::internal::Assembler::asr(), v8::internal::MacroAssembler::mov(), and V8_LIKELY.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and LoadSmiAsInt32().
emit_i32_set_cond()
void v8::internal::wasm::LiftoffAssembler::emit_i32_set_cond (Condition cond, Register dst, Register lhs, Register rhs) [inline]
Definition at line 2584 of file liftoff-assembler-arm-inl.h.
                                                                     {
  cmp(lhs, rhs);
  mov(dst, Operand(0), LeaveCC);
  mov(dst, Operand(1), LeaveCC, cond);
}
References v8::internal::Assembler::cmp(), v8::internal::LeaveCC, and v8::internal::MacroAssembler::mov().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), emit_ptrsize_set_cond(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitI32CmpOp().
emit_i32_shl()
void v8::internal::wasm::LiftoffAssembler::emit_i32_shl (Register dst, Register src, Register amount) [inline]
Definition at line 1801 of file liftoff-assembler-arm-inl.h.
                                                     {
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  and_(scratch, amount, Operand(0x1f));
  lsl(dst, src, Operand(scratch));
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::and_(), and v8::internal::Assembler::lsl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_shli()
void v8::internal::wasm::LiftoffAssembler::emit_i32_shli (Register dst, Register src, int32_t amount) [inline]
Definition at line 1808 of file liftoff-assembler-arm-inl.h.
                                                     {
  if (V8_LIKELY((amount & 31) != 0)) {
    lsl(dst, src, Operand(amount & 31));
  } else if (dst != src) {
    mov(dst, src);
  }
}
References v8::internal::Assembler::lsl(), v8::internal::MacroAssembler::mov(), and V8_LIKELY.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_i32_muli().
emit_i32_shr()
void v8::internal::wasm::LiftoffAssembler::emit_i32_shr (Register dst, Register src, Register amount) [inline]
Definition at line 1833 of file liftoff-assembler-arm-inl.h.
                                                     {
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  and_(scratch, amount, Operand(0x1f));
  lsr(dst, src, Operand(scratch));
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::and_(), and v8::internal::Assembler::lsr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_shri()
void v8::internal::wasm::LiftoffAssembler::emit_i32_shri (Register dst, Register src, int32_t amount) [inline]
Definition at line 1840 of file liftoff-assembler-arm-inl.h.
                                                     {
  if (V8_LIKELY((amount & 31) != 0)) {
    lsr(dst, src, Operand(amount & 31));
  } else if (dst != src) {
    mov(dst, src);
  }
}
References v8::internal::Assembler::lsr(), v8::internal::MacroAssembler::mov(), and V8_LIKELY.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_shri().
emit_i32_signextend_i16()
void v8::internal::wasm::LiftoffAssembler::emit_i32_signextend_i16 (Register dst, Register src) [inline]
Definition at line 2531 of file liftoff-assembler-arm-inl.h.
                                                                         {
  sxth(dst, src);
}
References v8::internal::Assembler::sxth().
Referenced by emit_i64_signextend_i16().
emit_i32_signextend_i8()
void v8::internal::wasm::LiftoffAssembler::emit_i32_signextend_i8 (Register dst, Register src) [inline]
Definition at line 2527 of file liftoff-assembler-arm-inl.h.
                                                                        {
  sxtb(dst, src);
}
References v8::internal::Assembler::sxtb().
Referenced by emit_i64_signextend_i8().
emit_i32_sub()
void v8::internal::wasm::LiftoffAssembler::emit_i32_sub (Register dst, Register lhs, Register rhs) [inline]
Definition at line 1759 of file liftoff-assembler-arm-inl.h.
                                                                            {
  sub(dst, lhs, rhs);
}
References v8::internal::Assembler::sub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_sub().
emit_i32_subi()
void v8::internal::wasm::LiftoffAssembler::emit_i32_subi (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 1762 of file liftoff-assembler-arm-inl.h.
                                                                            {
  sub(dst, lhs, Operand(imm));
}
References v8::internal::Assembler::sub().
emit_i32_xor()
void v8::internal::wasm::LiftoffAssembler::emit_i32_xor (Register dst, Register lhs, Register rhs) [inline]
Definition at line 1794 of file liftoff-assembler-arm-inl.h.
                                                                            {
  eor(dst, lhs, rhs);
}
References v8::internal::Assembler::eor().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32_xori()
void v8::internal::wasm::LiftoffAssembler::emit_i32_xori (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 1797 of file liftoff-assembler-arm-inl.h.
                                                                            {
  eor(dst, lhs, Operand(imm));
}
References v8::internal::Assembler::eor().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i32x4_abs()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4493 of file liftoff-assembler-arm-inl.h.
                                                           {
  vabs(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vabs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_add()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3510 of file liftoff-assembler-arm-inl.h.
                                                           {
  vadd(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_alltrue()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_alltrue (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3440 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  DwVfpRegister scratch = temps.AcquireD();
  vpmin(NeonU32, scratch, src.low_fp(), src.high_fp());
  vpmin(NeonU32, scratch, scratch, scratch);
  ExtractLane(dst.gp(), scratch, NeonS32, 0);
  cmp(dst.gp(), Operand(0));
  mov(dst.gp(), Operand(1), LeaveCC, ne);
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::Assembler::cmp(), v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::NeonS32, v8::internal::NeonU32, and v8::internal::Assembler::vpmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_bitmask()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_bitmask (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3451 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  Simd128Register tmp = liftoff::GetSimd128Register(src);
  Simd128Register mask = temps.AcquireQ();
  if (cache_state()->is_used(src)) {
    // We only have 1 scratch Q register, so try and reuse src.
    LiftoffRegList pinned{src};
    LiftoffRegister unused_pair = GetUnusedRegister(kFpRegPair, pinned);
    mask = liftoff::GetSimd128Register(unused_pair);
  }
  vshr(NeonS32, tmp, liftoff::GetSimd128Register(src), 31);
  // Set i-th bit of each lane i. When AND with tmp, the lanes that
  // are signed will have i-th bit set, unsigned will be 0.
  vmov(mask.low(), base::Double((uint64_t)0x0000'0002'0000'0001));
  vmov(mask.high(), base::Double((uint64_t)0x0000'0008'0000'0004));
  vand(tmp, mask, tmp);
  vpadd(Neon32, tmp.low(), tmp.low(), tmp.high());
  vpadd(Neon32, tmp.low(), tmp.low(), kDoubleRegZero);
  VmovLow(dst.gp(), tmp.low());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), cache_state(), v8::internal::wasm::liftoff::GetSimd128Register(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kDoubleRegZero, v8::internal::wasm::kFpRegPair, v8::internal::Neon32, v8::internal::NeonS32, v8::internal::Assembler::vand(), v8::internal::Assembler::vmov(), v8::internal::MacroAssembler::VmovLow(), v8::internal::Assembler::vpadd(), and v8::internal::Assembler::vshr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_dot_i16x8_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i16x8_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3556 of file liftoff-assembler-arm-inl.h.
                                                                   {
  QwNeonRegister dest = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  UseScratchRegisterScope temps(this);
  Simd128Register scratch = temps.AcquireQ();
  vmull(NeonS16, scratch, left.low(), right.low());
  vpadd(Neon32, dest.low(), scratch.low(), scratch.high());
  vmull(NeonS16, scratch, left.high(), right.high());
  vpadd(Neon32, dest.high(), scratch.low(), scratch.high());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::QwNeonRegister::high(), v8::internal::QwNeonRegister::low(), v8::internal::Neon32, v8::internal::NeonS16, v8::internal::Assembler::vmull(), and v8::internal::Assembler::vpadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_dot_i8x16_i7x16_add_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i8x16_i7x16_add_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister acc) [inline]
Definition at line 3864 of file liftoff-assembler-arm-inl.h.
                                                                             {
  DCHECK_NE(dst, acc);
  QwNeonRegister dest = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  QwNeonRegister accu = liftoff::GetSimd128Register(acc);
  UseScratchRegisterScope temps(this);
  Simd128Register scratch = temps.AcquireQ();
  vmull(NeonS8, scratch, left.low(), right.low());
  vpadd(Neon16, dest.low(), scratch.low(), scratch.high());
  vmull(NeonS8, scratch, left.high(), right.high());
  vpadd(Neon16, dest.high(), scratch.low(), scratch.high());
  vpaddl(NeonS16, dest, dest);
  vadd(Neon32, dest, dest, accu);
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), DCHECK_NE, v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::QwNeonRegister::high(), v8::internal::QwNeonRegister::low(), v8::internal::Neon16, v8::internal::Neon32, v8::internal::NeonS16, v8::internal::NeonS8, v8::internal::Assembler::vadd(), v8::internal::Assembler::vmull(), v8::internal::Assembler::vpadd(), and v8::internal::Assembler::vpaddl().
emit_i32x4_eq()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4201 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vceq().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::S128Const(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extadd_pairwise_i16x8_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extadd_pairwise_i16x8_s (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3573 of file liftoff-assembler-arm-inl.h.
                                                                               {
  vpaddl(NeonS16, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS16, and v8::internal::Assembler::vpaddl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extadd_pairwise_i16x8_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extadd_pairwise_i16x8_u (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3579 of file liftoff-assembler-arm-inl.h.
                                                                               {
  vpaddl(NeonU16, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU16, and v8::internal::Assembler::vpaddl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extmul_high_i16x8_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_high_i16x8_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3599 of file liftoff-assembler-arm-inl.h.
                                                                            {
  vmull(NeonS16, liftoff::GetSimd128Register(dst), src1.high_fp(),
        src2.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonS16, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extmul_high_i16x8_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_high_i16x8_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3606 of file liftoff-assembler-arm-inl.h.
                                                                            {
  vmull(NeonU16, liftoff::GetSimd128Register(dst), src1.high_fp(),
        src2.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonU16, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extmul_low_i16x8_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_low_i16x8_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3585 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmull(NeonS16, liftoff::GetSimd128Register(dst), src1.low_fp(),
        src2.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonS16, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extmul_low_i16x8_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extmul_low_i16x8_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3592 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmull(NeonU16, liftoff::GetSimd128Register(dst), src1.low_fp(),
        src2.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonU16, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_extract_lane()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3418 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ExtractLane(dst.gp(), liftoff::GetSimd128Register(lhs), NeonS32,
              imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::NeonS32.
emit_i32x4_ge_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4226 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcge(NeonS32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS32, and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_ge_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_ge_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4232 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcge(NeonU32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU32, and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_gt_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4214 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcgt(NeonS32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS32, and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_gt_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_gt_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4220 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcgt(NeonU32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU32, and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_max_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_max_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3542 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmax(NeonS32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS32, and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_max_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_max_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3549 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmax(NeonU32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU32, and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_min_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_min_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3528 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmin(NeonS32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS32, and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_min_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_min_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3535 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmin(NeonU32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU32, and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_mul()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3522 of file liftoff-assembler-arm-inl.h.
                                                           {
  vmul(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vmul().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_ne()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4207 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
  vmvn(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(dst));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, v8::internal::Assembler::vceq(), and v8::internal::Assembler::vmvn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_neg()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3434 of file liftoff-assembler-arm-inl.h.
                                                           {
  vneg(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vneg().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_relaxed_trunc_f32x4_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_relaxed_trunc_f32x4_s (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2806 of file liftoff-assembler-arm-inl.h.
                                                                             {
  vcvt_s32_f32(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcvt_s32_f32().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_relaxed_trunc_f32x4_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_relaxed_trunc_f32x4_u (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2812 of file liftoff-assembler-arm-inl.h.
                                                                             {
  vcvt_u32_f32(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcvt_u32_f32().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_relaxed_trunc_f64x2_s_zero()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_relaxed_trunc_f64x2_s_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2818 of file liftoff-assembler-arm-inl.h.
                                              {
  emit_i32x4_trunc_sat_f64x2_s_zero(dst, src);
}
References emit_i32x4_trunc_sat_f64x2_s_zero().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_relaxed_trunc_f64x2_u_zero()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_relaxed_trunc_f64x2_u_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2823 of file liftoff-assembler-arm-inl.h.
                                              {
  emit_i32x4_trunc_sat_f64x2_u_zero(dst, src);
}
References emit_i32x4_trunc_sat_f64x2_u_zero().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_replace_lane()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 3425 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ReplaceLane(liftoff::GetSimd128Register(dst),
              liftoff::GetSimd128Register(src1), src2.gp(), NeonS32,
              imm_lane_idx);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::NeonS32, and v8::internal::MacroAssembler::ReplaceLane().
emit_i32x4_sconvert_f32x4()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_f32x4 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4348 of file liftoff-assembler-arm-inl.h.
                                                                      {
  vcvt_s32_f32(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcvt_s32_f32().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_sconvert_i16x8_high()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_i16x8_high (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4429 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmovl(NeonS16, liftoff::GetSimd128Register(dst), src.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonS16, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_sconvert_i16x8_low()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_sconvert_i16x8_low (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4424 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vmovl(NeonS16, liftoff::GetSimd128Register(dst), src.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonS16, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_shl()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3475 of file liftoff-assembler-arm-inl.h.
                                                           {
  liftoff::EmitSimdShift<liftoff::kLeft, NeonS32, Neon32>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_shli()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3480 of file liftoff-assembler-arm-inl.h.
                                                    {
  vshl(NeonS32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), rhs & 31);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS32, and v8::internal::Assembler::vshl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_shr_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3486 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonS32, Neon32>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_shr_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3498 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonU32, Neon32>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_shri_s()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3492 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonS32>(this, dst, lhs,
                                                            rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_shri_u()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3504 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonU32>(this, dst, lhs,
                                                            rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_splat()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3413 of file liftoff-assembler-arm-inl.h.
                                                             {
  vdup(Neon32, liftoff::GetSimd128Register(dst), src.gp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::Neon32, and v8::internal::Assembler::vdup().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_sub()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3516 of file liftoff-assembler-arm-inl.h.
                                                           {
  vsub(Neon32, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon32, and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_trunc_sat_f64x2_s_zero()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_s_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4444 of file liftoff-assembler-arm-inl.h.
                                                                              {
  LowDwVfpRegister dst_d = LowDwVfpRegister::from_code(dst.low_fp().code());
  vcvt_s32_f64(dst_d.low(), src.low_fp());
  vcvt_s32_f64(dst_d.high(), src.high_fp());
  vmov(dst.high_fp(), 0);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::high(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LowDwVfpRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::Assembler::vcvt_s32_f64(), and v8::internal::Assembler::vmov().
Referenced by emit_i32x4_relaxed_trunc_f64x2_s_zero(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_trunc_sat_f64x2_u_zero()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_trunc_sat_f64x2_u_zero (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4452 of file liftoff-assembler-arm-inl.h.
                                                                              {
  LowDwVfpRegister dst_d = LowDwVfpRegister::from_code(dst.low_fp().code());
  vcvt_u32_f64(dst_d.low(), src.low_fp());
  vcvt_u32_f64(dst_d.high(), src.high_fp());
  vmov(dst.high_fp(), 0);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::LowDwVfpRegister::high(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LowDwVfpRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::Assembler::vcvt_u32_f64(), and v8::internal::Assembler::vmov().
Referenced by emit_i32x4_relaxed_trunc_f64x2_u_zero(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_uconvert_f32x4()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_f32x4 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4354 of file liftoff-assembler-arm-inl.h.
                                                                      {
  vcvt_u32_f32(liftoff::GetSimd128Register(dst),
               liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcvt_u32_f32().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_uconvert_i16x8_high()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_i16x8_high (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4439 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmovl(NeonU16, liftoff::GetSimd128Register(dst), src.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonU16, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i32x4_uconvert_i16x8_low()
void v8::internal::wasm::LiftoffAssembler::emit_i32x4_uconvert_i16x8_low (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4434 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vmovl(NeonU16, liftoff::GetSimd128Register(dst), src.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonU16, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64_add()
void v8::internal::wasm::LiftoffAssembler::emit_i64_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2043 of file liftoff-assembler-arm-inl.h.
                                                         {
  liftoff::I64Binop<&Assembler::add, &Assembler::adc>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_add().
emit_i64_addi()
void v8::internal::wasm::LiftoffAssembler::emit_i64_addi (LiftoffRegister dst, LiftoffRegister lhs, int64_t imm) [inline]
Definition at line 2048 of file liftoff-assembler-arm-inl.h.
                                                  {
  liftoff::I64BinopI<&Assembler::add, &Assembler::adc>(this, dst, lhs, imm);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_addi().
emit_i64_and()
void v8::internal::wasm::LiftoffAssembler::emit_i64_and (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 1646 of file liftoff-assembler-arm64-inl.h.
                                                         {
  And(dst.gp().X(), lhs.gp().X(), rhs.gp().X());
}
References v8::internal::MacroAssembler::And(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_and().
emit_i64_andi()
void v8::internal::wasm::LiftoffAssembler::emit_i64_andi (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm) [inline]
Definition at line 1650 of file liftoff-assembler-arm64-inl.h.
                                                  {
  And(dst.gp().X(), lhs.gp().X(), imm);
}
References v8::internal::MacroAssembler::And(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_clz()
void v8::internal::wasm::LiftoffAssembler::emit_i64_clz (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2148 of file liftoff-assembler-arm-inl.h.
                                                                            {
  // return high == 0 ? 32 + CLZ32(low) : CLZ32(high);
  Label done;
  Label high_is_zero;
  cmp(src.high_gp(), Operand(0));
  b(&high_is_zero, eq);
  clz(dst.low_gp(), src.high_gp());
  jmp(&done);
  bind(&high_is_zero);
  clz(dst.low_gp(), src.low_gp());
  add(dst.low_gp(), dst.low_gp(), Operand(32));
  bind(&done);
  mov(dst.high_gp(), Operand(0)); // High word of result is always 0.
}
References v8::internal::Assembler::add(), v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::Assembler::clz(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::MacroAssembler::jmp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::MacroAssembler::mov().
emit_i64_ctz()
void v8::internal::wasm::LiftoffAssembler::emit_i64_ctz (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2166 of file liftoff-assembler-arm-inl.h.
                                                                            {
  // return low == 0 ? 32 + CTZ32(high) : CTZ32(low);
  // CTZ32(x) = CLZ(RBIT(x))
  Label done;
  Label low_is_zero;
  cmp(src.low_gp(), Operand(0));
  b(&low_is_zero, eq);
  rbit(dst.low_gp(), src.low_gp());
  clz(dst.low_gp(), dst.low_gp());
  jmp(&done);
  bind(&low_is_zero);
  rbit(dst.low_gp(), src.high_gp());
  clz(dst.low_gp(), dst.low_gp());
  add(dst.low_gp(), dst.low_gp(), Operand(32));
  bind(&done);
  mov(dst.high_gp(), Operand(0)); // High word of result is always 0.
}
References v8::internal::Assembler::add(), v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::Assembler::clz(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::MacroAssembler::jmp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), and v8::internal::Assembler::rbit().
emit_i64_divs()
bool v8::internal::wasm::LiftoffAssembler::emit_i64_divs (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label * trap_div_by_zero, Label * trap_div_unrepresentable) [inline]
Definition at line 2078 of file liftoff-assembler-arm-inl.h.
                                                                      {
  return false;
}
emit_i64_divu()
bool v8::internal::wasm::LiftoffAssembler::emit_i64_divu (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label * trap_div_by_zero) [inline]
Definition at line 2085 of file liftoff-assembler-arm-inl.h.
                                                              {
  return false;
}
emit_i64_eqz()
void v8::internal::wasm::LiftoffAssembler::emit_i64_eqz (Register dst, LiftoffRegister src) [inline]
Definition at line 2591 of file liftoff-assembler-arm-inl.h.
                                                                     {
  orr(dst, src.low_gp(), src.high_gp());
  clz(dst, dst);
  mov(dst, Operand(dst, LSR, 5));
}
References v8::internal::Assembler::clz(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::LSR, v8::internal::MacroAssembler::mov(), and v8::internal::Assembler::orr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnOp().
emit_i64_mul()
void v8::internal::wasm::LiftoffAssembler::emit_i64_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2058 of file liftoff-assembler-arm-inl.h.
                                                         {
  // Idea:
  // [ lhs_hi | lhs_lo ] * [ rhs_hi | rhs_lo ]
  // = [ lhs_hi * rhs_lo | ] (32 bit mul, shift 32)
  // + [ lhs_lo * rhs_hi | ] (32 bit mul, shift 32)
  // + [ lhs_lo * rhs_lo ] (32x32->64 mul, shift 0)
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  // scratch = lhs_hi * rhs_lo
  mul(scratch, lhs.high_gp(), rhs.low_gp());
  // scratch += lhs_lo * rhs_hi
  mla(scratch, lhs.low_gp(), rhs.high_gp(), scratch);
  // TODO(arm): use umlal once implemented correctly in the simulator.
  // [dst_hi|dst_lo] = lhs_lo * rhs_lo
  umull(dst.low_gp(), dst.high_gp(), lhs.low_gp(), rhs.low_gp());
  // dst_hi += scratch
  add(dst.high_gp(), dst.high_gp(), scratch);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::add(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Assembler::mla(), v8::internal::Assembler::mul(), and v8::internal::Assembler::umull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_muli()
void v8::internal::wasm::LiftoffAssembler::emit_i64_muli (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm) [inline]
Definition at line 1634 of file liftoff-assembler-arm64-inl.h.
                                                  {
  if (base::bits::IsPowerOfTwo(imm)) {
    emit_i64_shli(dst, lhs, base::bits::WhichPowerOfTwo(imm));
    return;
  }
  UseScratchRegisterScope temps(this);
  Register scratch = temps.AcquireX();
  Mov(scratch, imm);
  Mul(dst.gp().X(), lhs.gp().X(), scratch);
}
References v8::internal::UseScratchRegisterScope::AcquireX(), emit_i64_shli(), v8::internal::wasm::LiftoffRegister::gp(), v8::base::bits::IsPowerOfTwo(), v8::internal::MacroAssembler::Mov(), v8::internal::MacroAssembler::Mul(), v8::base::bits::WhichPowerOfTwo(), and v8::internal::CPURegister::X().
Referenced by emit_ptrsize_muli().
emit_i64_or()
void v8::internal::wasm::LiftoffAssembler::emit_i64_or (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 1655 of file liftoff-assembler-arm64-inl.h.
                                                        {
  Orr(dst.gp().X(), lhs.gp().X(), rhs.gp().X());
}
References v8::internal::wasm::LiftoffRegister::gp(), v8::internal::MacroAssembler::Orr(), and v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_ori()
void v8::internal::wasm::LiftoffAssembler::emit_i64_ori (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm) [inline]
Definition at line 1659 of file liftoff-assembler-arm64-inl.h.
                                                 {
  Orr(dst.gp().X(), lhs.gp().X(), imm);
}
References v8::internal::wasm::LiftoffRegister::gp(), v8::internal::MacroAssembler::Orr(), and v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_popcnt()
bool v8::internal::wasm::LiftoffAssembler::emit_i64_popcnt (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2187 of file liftoff-assembler-arm-inl.h.
                                                            {
  // Produce partial popcnts in the two dst registers, making sure not to
  // overwrite the second src register before using it.
  Register src1 = src.high_gp() == dst.low_gp() ? src.high_gp() : src.low_gp();
  Register src2 = src.high_gp() == dst.low_gp() ? src.low_gp() : src.high_gp();
  LiftoffRegList pinned{dst, src2};
  Register scratch1 = pinned.set(GetUnusedRegister(kGpReg, pinned)).gp();
  Register scratch2 = GetUnusedRegister(kGpReg, pinned).gp();
  liftoff::GeneratePopCnt(this, dst.low_gp(), src1, scratch1, scratch2);
  liftoff::GeneratePopCnt(this, dst.high_gp(), src2, scratch1, scratch2);
  // Now add the two into the lower dst reg and clear the higher dst reg.
  add(dst.low_gp(), dst.low_gp(), dst.high_gp());
  mov(dst.high_gp(), Operand(0));
  return true;
}
References v8::internal::Assembler::add(), v8::internal::wasm::liftoff::GeneratePopCnt(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::kGpReg, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), and v8::internal::wasm::LiftoffRegList::set().
emit_i64_rems()
bool v8::internal::wasm::LiftoffAssembler::emit_i64_rems (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label * trap_rem_by_zero) [inline]
Definition at line 2091 of file liftoff-assembler-arm-inl.h.
                                                              {
  return false;
}
emit_i64_remu()
bool v8::internal::wasm::LiftoffAssembler::emit_i64_remu (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, Label * trap_rem_by_zero) [inline]
Definition at line 2097 of file liftoff-assembler-arm-inl.h.
                                                              {
  return false;
}
emit_i64_sar()
void v8::internal::wasm::LiftoffAssembler::emit_i64_sar (LiftoffRegister dst, LiftoffRegister src, Register amount) [inline]
Definition at line 2118 of file liftoff-assembler-arm-inl.h.
                                                     {
  liftoff::I64Shiftop<&MacroAssembler::AsrPair, false>(this, dst, src, amount);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_sari()
void v8::internal::wasm::LiftoffAssembler::emit_i64_sari (LiftoffRegister dst, LiftoffRegister src, int32_t amount) [inline]
Definition at line 2123 of file liftoff-assembler-arm-inl.h.
                                                     {
  UseScratchRegisterScope temps(this);
  // {src.high_gp()} will still be needed after writing {dst.low_gp()}.
  Register src_high =
      liftoff::EnsureNoAlias(this, src.high_gp(), dst.low_gp(), &temps);
  AsrPair(dst.low_gp(), dst.high_gp(), src.low_gp(), src_high, amount & 63);
}
References v8::internal::MacroAssembler::AsrPair(), v8::internal::wasm::liftoff::EnsureNoAlias(), v8::internal::wasm::LiftoffRegister::high_gp(), and v8::internal::wasm::LiftoffRegister::low_gp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_set_cond()
void v8::internal::wasm::LiftoffAssembler::emit_i64_set_cond (Condition condition, Register dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2597 of file liftoff-assembler-arm-inl.h.
                                                              {
  // For signed i64 comparisons, we still need to use unsigned comparison for
  // the low word (the only bit carrying signedness information is the MSB in
  // the high word).
  Condition unsigned_cond = liftoff::MakeUnsigned(cond);
  Label set_cond;
  Label cont;
  LiftoffRegister dest = LiftoffRegister(dst);
  bool speculative_move = !dest.overlaps(lhs) && !dest.overlaps(rhs);
  if (speculative_move) {
    mov(dst, Operand(0));
  }
  // Compare high word first. If it differs, use it for the set_cond. If it's
  // equal, compare the low word and use that for set_cond.
  cmp(lhs.high_gp(), rhs.high_gp());
  if (unsigned_cond == cond) {
    cmp(lhs.low_gp(), rhs.low_gp(), eq);
    if (!speculative_move) {
      mov(dst, Operand(0));
    }
    mov(dst, Operand(1), LeaveCC, cond);
  } else {
    // If the condition predicate for the low differs from that for the high
    // word, the conditional move instructions must be separated.
    b(ne, &set_cond);
    cmp(lhs.low_gp(), rhs.low_gp());
    if (!speculative_move) {
      mov(dst, Operand(0));
    }
    mov(dst, Operand(1), LeaveCC, unsigned_cond);
    b(&cont);
    bind(&set_cond);
    if (!speculative_move) {
      mov(dst, Operand(0));
    }
    mov(dst, Operand(1), LeaveCC, cond);
    bind(&cont);
  }
}
References v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::wasm::liftoff::MakeUnsigned(), v8::internal::MacroAssembler::mov(), v8::internal::ne, and v8::internal::wasm::LiftoffRegister::overlaps().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_set_cond().
emit_i64_shl()
void v8::internal::wasm::LiftoffAssembler::emit_i64_shl (LiftoffRegister dst, LiftoffRegister src, Register amount) [inline]
Definition at line 2103 of file liftoff-assembler-arm-inl.h.
                                                     {
  liftoff::I64Shiftop<&MacroAssembler::LslPair, true>(this, dst, src, amount);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_shli()
void v8::internal::wasm::LiftoffAssembler::emit_i64_shli (LiftoffRegister dst, LiftoffRegister src, int32_t amount) [inline]
Definition at line 2108 of file liftoff-assembler-arm-inl.h.
                                                     {
  UseScratchRegisterScope temps(this);
  // {src.low_gp()} will still be needed after writing {dst.high_gp()}.
  Register src_low =
      liftoff::EnsureNoAlias(this, src.low_gp(), dst.high_gp(), &temps);
  LslPair(dst.low_gp(), dst.high_gp(), src_low, src.high_gp(), amount & 63);
}
References v8::internal::wasm::liftoff::EnsureNoAlias(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::MacroAssembler::LslPair().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_i64_muli().
emit_i64_shr()
void v8::internal::wasm::LiftoffAssembler::emit_i64_shr (LiftoffRegister dst, LiftoffRegister src, Register amount) [inline]
Definition at line 2133 of file liftoff-assembler-arm-inl.h.
                                                     {
  liftoff::I64Shiftop<&MacroAssembler::LsrPair, false>(this, dst, src, amount);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_shri()
void v8::internal::wasm::LiftoffAssembler::emit_i64_shri (LiftoffRegister dst, LiftoffRegister src, int32_t amount) [inline]
Definition at line 2138 of file liftoff-assembler-arm-inl.h.
                                                     {
  UseScratchRegisterScope temps(this);
  // {src.high_gp()} will still be needed after writing {dst.low_gp()}.
  Register src_high =
      liftoff::EnsureNoAlias(this, src.high_gp(), dst.low_gp(), &temps);
  LsrPair(dst.low_gp(), dst.high_gp(), src.low_gp(), src_high, amount & 63);
}
References v8::internal::wasm::liftoff::EnsureNoAlias(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::MacroAssembler::LsrPair().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_shri().
emit_i64_signextend_i16()
void v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i16 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2541 of file liftoff-assembler-arm-inl.h.
                                                                    {
  emit_i32_signextend_i16(dst.low_gp(), src.low_gp());
  mov(dst.high_gp(), Operand(dst.low_gp(), ASR, 31));
}
References v8::internal::ASR, emit_i32_signextend_i16(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::MacroAssembler::mov().
emit_i64_signextend_i32()
void v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i32 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2547 of file liftoff-assembler-arm-inl.h.
                                                                    {
  MacroAssembler::Move(dst.low_gp(), src.low_gp());
  mov(dst.high_gp(), Operand(src.low_gp(), ASR, 31));
}
References v8::internal::ASR, v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::mov(), and v8::internal::MacroAssembler::Move().
emit_i64_signextend_i8()
void v8::internal::wasm::LiftoffAssembler::emit_i64_signextend_i8 (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 2535 of file liftoff-assembler-arm-inl.h.
                                                                   {
  emit_i32_signextend_i8(dst.low_gp(), src.low_gp());
  mov(dst.high_gp(), Operand(dst.low_gp(), ASR, 31));
}
References v8::internal::ASR, emit_i32_signextend_i8(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::MacroAssembler::mov().
emit_i64_sub()
void v8::internal::wasm::LiftoffAssembler::emit_i64_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2053 of file liftoff-assembler-arm-inl.h.
                                                         {
  liftoff::I64Binop<&Assembler::sub, &Assembler::sbc>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp(), and emit_ptrsize_sub().
emit_i64_xor()
void v8::internal::wasm::LiftoffAssembler::emit_i64_xor (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 1664 of file liftoff-assembler-arm64-inl.h.
                                                         {
  Eor(dst.gp().X(), lhs.gp().X(), rhs.gp().X());
}
References v8::internal::MacroAssembler::Eor(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64_xori()
void v8::internal::wasm::LiftoffAssembler::emit_i64_xori (LiftoffRegister dst, LiftoffRegister lhs, int32_t imm) [inline]
Definition at line 1668 of file liftoff-assembler-arm64-inl.h.
                                                  {
  Eor(dst.gp().X(), lhs.gp().X(), imm);
}
References v8::internal::MacroAssembler::Eor(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::CPURegister::X().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_i64x2_abs()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4499 of file liftoff-assembler-arm-inl.h.
                                                           {
  I64x2Abs(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::I64x2Abs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_add()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3302 of file liftoff-assembler-arm-inl.h.
                                                           {
  vadd(Neon64, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon64, and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_alltrue()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_alltrue (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3262 of file liftoff-assembler-arm-inl.h.
                                                               {
  I64x2AllTrue(dst.gp(), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::MacroAssembler::I64x2AllTrue().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_bitmask()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_bitmask (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3388 of file liftoff-assembler-arm-inl.h.
                                                               {
  I64x2BitMask(dst.gp(), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::MacroAssembler::I64x2BitMask().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_eq()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4238 of file liftoff-assembler-arm-inl.h.
                                                          {
  I64x2Eq(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
          liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::I64x2Eq().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_extmul_high_i32x4_s()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_high_i32x4_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3374 of file liftoff-assembler-arm-inl.h.
                                                                            {
  vmull(NeonS32, liftoff::GetSimd128Register(dst), src1.high_fp(),
        src2.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonS32, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_extmul_high_i32x4_u()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_high_i32x4_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3381 of file liftoff-assembler-arm-inl.h.
                                                                            {
  vmull(NeonU32, liftoff::GetSimd128Register(dst), src1.high_fp(),
        src2.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonU32, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_extmul_low_i32x4_s()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_low_i32x4_s (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3360 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmull(NeonS32, liftoff::GetSimd128Register(dst), src1.low_fp(),
        src2.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonS32, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_extmul_low_i32x4_u()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_extmul_low_i32x4_u (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2) [inline]
Definition at line 3367 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmull(NeonU32, liftoff::GetSimd128Register(dst), src1.low_fp(),
        src2.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonU32, and v8::internal::Assembler::vmull().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_extract_lane()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_extract_lane (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3232 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ExtractLane(dst.low_gp(), liftoff::GetSimd128Register(lhs), NeonS32,
              imm_lane_idx * 2);
  ExtractLane(dst.high_gp(), liftoff::GetSimd128Register(lhs), NeonS32,
              imm_lane_idx * 2 + 1);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), and v8::internal::NeonS32.
emit_i64x2_ge_s()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4256 of file liftoff-assembler-arm-inl.h.
                                                            {
  I64x2GeS(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
           liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::I64x2GeS().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_gt_s()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4250 of file liftoff-assembler-arm-inl.h.
                                                            {
  I64x2GtS(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
           liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::I64x2GtS().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_mul()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3314 of file liftoff-assembler-arm-inl.h.
                                                           {
  UseScratchRegisterScope temps(this);
  QwNeonRegister dst_neon = liftoff::GetSimd128Register(dst);
  QwNeonRegister left = liftoff::GetSimd128Register(lhs);
  QwNeonRegister right = liftoff::GetSimd128Register(rhs);
  // These temporary registers will be modified. We can directly modify lhs and
  // rhs if they are not uesd, saving on temporaries.
  QwNeonRegister tmp1 = left;
  QwNeonRegister tmp2 = right;
  LiftoffRegList used_plus_dst =
      cache_state()->used_registers | LiftoffRegList{dst};
  if (used_plus_dst.has(lhs) && used_plus_dst.has(rhs)) {
    tmp1 = temps.AcquireQ();
    // We only have 1 scratch Q register, so acquire another ourselves.
    LiftoffRegList pinned{dst};
    LiftoffRegister unused_pair = GetUnusedRegister(kFpRegPair, pinned);
    tmp2 = liftoff::GetSimd128Register(unused_pair);
  } else if (used_plus_dst.has(lhs)) {
    tmp1 = temps.AcquireQ();
  } else if (used_plus_dst.has(rhs)) {
    tmp2 = temps.AcquireQ();
  }
  // Algorithm from code-generator-arm.cc, refer to comments there for details.
  if (tmp1 != left) {
    vmov(tmp1, left);
  }
  if (tmp2 != right) {
    vmov(tmp2, right);
  }
  vtrn(Neon32, tmp1.low(), tmp1.high());
  vtrn(Neon32, tmp2.low(), tmp2.high());
  vmull(NeonU32, dst_neon, tmp1.low(), tmp2.high());
  vmlal(NeonU32, dst_neon, tmp1.high(), tmp2.low());
  vshl(NeonU64, dst_neon, dst_neon, 32);
  vmlal(NeonU32, dst_neon, tmp1.low(), tmp2.low());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), cache_state(), v8::internal::wasm::liftoff::GetSimd128Register(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::QwNeonRegister::high(), v8::internal::wasm::kFpRegPair, v8::internal::QwNeonRegister::low(), v8::internal::Neon32, v8::internal::NeonU32, v8::internal::NeonU64, v8::internal::wasm::LiftoffAssembler::CacheState::used_registers, v8::internal::Assembler::vmlal(), v8::internal::Assembler::vmov(), v8::internal::Assembler::vmull(), v8::internal::Assembler::vshl(), and v8::internal::Assembler::vtrn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_ne()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4244 of file liftoff-assembler-arm-inl.h.
                                                          {
  I64x2Ne(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
          liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::MacroAssembler::I64x2Ne().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_neg()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3252 of file liftoff-assembler-arm-inl.h.
                                                           {
  UseScratchRegisterScope temps(this);
  QwNeonRegister zero =
      dst == src ? temps.AcquireQ() : liftoff::GetSimd128Register(dst);
  vmov(zero, uint64_t{0});
  vsub(Neon64, liftoff::GetSimd128Register(dst), zero,
       liftoff::GetSimd128Register(src));
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon64, v8::internal::Assembler::vmov(), v8::internal::Assembler::vsub(), and v8::internal::zero.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_replace_lane()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 3241 of file liftoff-assembler-arm-inl.h.
                                                                     {
  Simd128Register dst_simd = liftoff::GetSimd128Register(dst);
  Simd128Register src1_simd = liftoff::GetSimd128Register(src1);
  ReplaceLane(dst_simd, src1_simd, src2.low_gp(), NeonS32, imm_lane_idx * 2);
  ReplaceLane(dst_simd, dst_simd, src2.high_gp(), NeonS32,
              imm_lane_idx * 2 + 1);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::NeonS32, and v8::internal::MacroAssembler::ReplaceLane().
emit_i64x2_sconvert_i32x4_high()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_sconvert_i32x4_high (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3398 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmovl(NeonS32, liftoff::GetSimd128Register(dst), src.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonS32, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_sconvert_i32x4_low()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_sconvert_i32x4_low (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3393 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vmovl(NeonS32, liftoff::GetSimd128Register(dst), src.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonS32, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_shl()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3267 of file liftoff-assembler-arm-inl.h.
                                                           {
  liftoff::EmitSimdShift<liftoff::kLeft, NeonS64, Neon32>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_shli()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3272 of file liftoff-assembler-arm-inl.h.
                                                    {
  vshl(NeonS64, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), rhs & 63);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS64, and v8::internal::Assembler::vshl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_shr_s()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3278 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonS64, Neon32>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_shr_u()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3290 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonU64, Neon32>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_shri_s()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3284 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonS64>(this, dst, lhs,
                                                            rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_shri_u()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 3296 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonU64>(this, dst, lhs,
                                                            rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_splat()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3224 of file liftoff-assembler-arm-inl.h.
                                                             {
  Simd128Register dst_simd = liftoff::GetSimd128Register(dst);
  vdup(Neon32, dst_simd, src.low_gp());
  ReplaceLane(dst_simd, dst_simd, src.high_gp(), NeonS32, 1);
  ReplaceLane(dst_simd, dst_simd, src.high_gp(), NeonS32, 3);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Neon32, v8::internal::NeonS32, v8::internal::MacroAssembler::ReplaceLane(), and v8::internal::Assembler::vdup().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_sub()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 3308 of file liftoff-assembler-arm-inl.h.
                                                           {
  vsub(Neon64, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon64, and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_uconvert_i32x4_high()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_uconvert_i32x4_high (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3408 of file liftoff-assembler-arm-inl.h.
                                                                           {
  vmovl(NeonU32, liftoff::GetSimd128Register(dst), src.high_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::NeonU32, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i64x2_uconvert_i32x4_low()
void v8::internal::wasm::LiftoffAssembler::emit_i64x2_uconvert_i32x4_low (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3403 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vmovl(NeonU32, liftoff::GetSimd128Register(dst), src.low_fp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::NeonU32, and v8::internal::Assembler::vmovl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_abs()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_abs (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4481 of file liftoff-assembler-arm-inl.h.
                                                           {
  vabs(Neon8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon8, and v8::internal::Assembler::vabs().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_add()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_add (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4059 of file liftoff-assembler-arm-inl.h.
                                                           {
  vadd(Neon8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon8, and v8::internal::Assembler::vadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_add_sat_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_add_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4065 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqadd(NeonS8, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vqadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_add_sat_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_add_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4092 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqadd(NeonU8, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vqadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_alltrue()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_alltrue (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3986 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  DwVfpRegister scratch = temps.AcquireD();
  vpmin(NeonU8, scratch, src.low_fp(), src.high_fp());
  vpmin(NeonU8, scratch, scratch, scratch);
  vpmin(NeonU8, scratch, scratch, scratch);
  vpmin(NeonU8, scratch, scratch, scratch);
  ExtractLane(dst.gp(), scratch, NeonS8, 0);
  cmp(dst.gp(), Operand(0));
  mov(dst.gp(), Operand(1), LeaveCC, ne);
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::Assembler::cmp(), v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LeaveCC, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::NeonS8, v8::internal::NeonU8, and v8::internal::Assembler::vpmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_bitmask()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_bitmask (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3999 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  Simd128Register tmp = liftoff::GetSimd128Register(src);
  Simd128Register mask = temps.AcquireQ();
  if (cache_state()->is_used(src)) {
    // We only have 1 scratch Q register, so try and reuse src.
    LiftoffRegList pinned{src};
    LiftoffRegister unused_pair = GetUnusedRegister(kFpRegPair, pinned);
    mask = liftoff::GetSimd128Register(unused_pair);
  }
  vshr(NeonS8, tmp, liftoff::GetSimd128Register(src), 7);
  // Set i-th bit of each lane i. When AND with tmp, the lanes that
  // are signed will have i-th bit set, unsigned will be 0.
  vmov(mask.low(), base::Double((uint64_t)0x8040'2010'0804'0201));
  vmov(mask.high(), base::Double((uint64_t)0x8040'2010'0804'0201));
  vand(tmp, mask, tmp);
  vext(mask, tmp, tmp, 8);
  vzip(Neon8, mask, tmp);
  vpadd(Neon16, tmp.low(), tmp.low(), tmp.high());
  vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
  vpadd(Neon16, tmp.low(), tmp.low(), tmp.low());
  vmov(NeonU16, dst.gp(), tmp.low(), 0);
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), cache_state(), v8::internal::wasm::liftoff::GetSimd128Register(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::kFpRegPair, v8::internal::Neon16, v8::internal::Neon8, v8::internal::NeonS8, v8::internal::NeonU16, v8::internal::Assembler::vand(), v8::internal::Assembler::vext(), v8::internal::Assembler::vmov(), v8::internal::Assembler::vpadd(), v8::internal::Assembler::vshr(), and v8::internal::Assembler::vzip().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_eq()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_eq (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4127 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(Neon8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon8, and v8::internal::Assembler::vceq().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_extract_lane_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_extract_lane_s (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3960 of file liftoff-assembler-arm-inl.h.
                                                                       {
  ExtractLane(dst.gp(), liftoff::GetSimd128Register(lhs), NeonS8, imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::NeonS8.
emit_i8x16_extract_lane_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_extract_lane_u (LiftoffRegister dst, LiftoffRegister lhs, uint8_t imm_lane_idx) [inline]
Definition at line 3954 of file liftoff-assembler-arm-inl.h.
                                                                       {
  ExtractLane(dst.gp(), liftoff::GetSimd128Register(lhs), NeonU8, imm_lane_idx);
}
References v8::internal::MacroAssembler::ExtractLane(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::NeonU8.
emit_i8x16_ge_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_ge_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4152 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcge(NeonS8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_ge_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_ge_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4158 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcge(NeonU8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vcge().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_gt_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_gt_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4140 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcgt(NeonS8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_gt_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_gt_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4146 of file liftoff-assembler-arm-inl.h.
                                                            {
  vcgt(NeonU8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vcgt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_max_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_max_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4113 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmax(NeonS8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_max_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_max_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4120 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmax(NeonU8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vmax().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_min_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_min_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4099 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmin(NeonS8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_min_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_min_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4106 of file liftoff-assembler-arm-inl.h.
                                                             {
  vmin(NeonU8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vmin().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_ne()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_ne (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4133 of file liftoff-assembler-arm-inl.h.
                                                          {
  vceq(Neon8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
  vmvn(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(dst));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon8, v8::internal::Assembler::vceq(), and v8::internal::Assembler::vmvn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_neg()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_neg (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3975 of file liftoff-assembler-arm-inl.h.
                                                           {
  vneg(Neon8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon8, and v8::internal::Assembler::vneg().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_popcnt()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_popcnt (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3944 of file liftoff-assembler-arm-inl.h.
                                                              {
  vcnt(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vcnt().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_relaxed_swizzle()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_relaxed_swizzle (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2800 of file liftoff-assembler-arm-inl.h.
                                                                       {
  emit_i8x16_swizzle(dst, lhs, rhs);
}
References emit_i8x16_swizzle().
emit_i8x16_replace_lane()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_replace_lane (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, uint8_t imm_lane_idx) [inline]
Definition at line 3966 of file liftoff-assembler-arm-inl.h.
                                                                     {
  ReplaceLane(liftoff::GetSimd128Register(dst),
              liftoff::GetSimd128Register(src1), src2.gp(), NeonS8,
              imm_lane_idx);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::NeonS8, and v8::internal::MacroAssembler::ReplaceLane().
emit_i8x16_rounding_average_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_rounding_average_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4467 of file liftoff-assembler-arm-inl.h.
                                                                          {
  vrhadd(NeonU8, liftoff::GetSimd128Register(dst),
         liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vrhadd().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_sconvert_i16x8()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_sconvert_i16x8 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4380 of file liftoff-assembler-arm-inl.h.
                                                                      {
  liftoff::S128NarrowOp(this, NeonS8, NeonS8, dst, lhs, rhs);
}
References v8::internal::NeonS8, and v8::internal::wasm::liftoff::S128NarrowOp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shl()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shl (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4026 of file liftoff-assembler-arm-inl.h.
                                                           {
  liftoff::EmitSimdShift<liftoff::kLeft, NeonS8, Neon8>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shli()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shli (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 4031 of file liftoff-assembler-arm-inl.h.
                                                    {
  vshl(NeonS8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), rhs & 7);
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vshl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shr_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shr_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4037 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonS8, Neon8>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shr_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shr_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4048 of file liftoff-assembler-arm-inl.h.
                                                             {
  liftoff::EmitSimdShift<liftoff::kRight, NeonU8, Neon8>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shri_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shri_s (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 4043 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonS8>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shri_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shri_u (LiftoffRegister dst, LiftoffRegister lhs, int32_t rhs) [inline]
Definition at line 4054 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::EmitSimdShiftImmediate<liftoff::kRight, NeonU8>(this, dst, lhs, rhs);
}
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_shuffle()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_shuffle (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs, const uint8_t shuffle[16], bool is_swizzle) [inline]
Definition at line 3887 of file liftoff-assembler-arm-inl.h.
                                                           {
  Simd128Register dest = liftoff::GetSimd128Register(dst);
  Simd128Register src1 = liftoff::GetSimd128Register(lhs);
  Simd128Register src2 = liftoff::GetSimd128Register(rhs);
  UseScratchRegisterScope temps(this);
  Simd128Register scratch = temps.AcquireQ();
  if ((src1 != src2) && src1.code() + 1 != src2.code()) {
    // vtbl requires the operands to be consecutive or the same.
    // If they are the same, we build a smaller list operand (table_size = 2).
    // If they are not the same, and not consecutive, we move the src1 and src2
    // to q14 and q15, which will be unused since they are not allocatable in
    // Liftoff. If the operands are the same, then we build a smaller list
    // operand below.
    static_assert(!kLiftoffAssemblerFpCacheRegs.has(d28),
                  "This only works if q14-q15 (d28-d31) are not used.");
    static_assert(!kLiftoffAssemblerFpCacheRegs.has(d29),
                  "This only works if q14-q15 (d28-d31) are not used.");
    static_assert(!kLiftoffAssemblerFpCacheRegs.has(d30),
                  "This only works if q14-q15 (d28-d31) are not used.");
    static_assert(!kLiftoffAssemblerFpCacheRegs.has(d31),
                  "This only works if q14-q15 (d28-d31) are not used.");
    vmov(q14, src1);
    src1 = q14;
    vmov(q15, src2);
    src2 = q15;
  }
  int table_size = src1 == src2 ? 2 : 4;
  int scratch_s_base = scratch.code() * 4;
  for (int j = 0; j < 4; j++) {
    uint32_t imm = 0;
    for (int i = 3; i >= 0; i--) {
      imm = (imm << 8) | shuffle[j * 4 + i];
    }
    DCHECK_EQ(0, imm & (table_size == 2 ? 0xF0F0F0F0 : 0xE0E0E0E0));
    // Ensure indices are in [0,15] if table_size is 2, or [0,31] if 4.
    vmov(SwVfpRegister::from_code(scratch_s_base + j), Float32::FromBits(imm));
  }
  DwVfpRegister table_base = src1.low();
  NeonListOperand table(table_base, table_size);
  if (dest != src1 && dest != src2) {
    vtbl(dest.low(), table, scratch.low());
    vtbl(dest.high(), table, scratch.high());
  } else {
    vtbl(scratch.low(), table, scratch.low());
    vtbl(scratch.high(), table, scratch.high());
    vmov(dest, scratch);
  }
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), DCHECK_EQ, v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code(), v8::internal::Float32::FromBits(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::Assembler::j(), v8::internal::wasm::kLiftoffAssemblerFpCacheRegs, v8::internal::Assembler::vmov(), and v8::internal::Assembler::vtbl().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Simd8x16ShuffleOp().
emit_i8x16_splat()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_splat (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3949 of file liftoff-assembler-arm-inl.h.
                                                             {
  vdup(Neon8, liftoff::GetSimd128Register(dst), src.gp());
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::Neon8, and v8::internal::Assembler::vdup().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_sub()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_sub (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4072 of file liftoff-assembler-arm-inl.h.
                                                           {
  vsub(Neon8, liftoff::GetSimd128Register(dst),
       liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Neon8, and v8::internal::Assembler::vsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_sub_sat_s()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_sub_sat_s (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4078 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqsub(NeonS8, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonS8, and v8::internal::Assembler::vqsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_sub_sat_u()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_sub_sat_u (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4085 of file liftoff-assembler-arm-inl.h.
                                                                 {
  vqsub(NeonU8, liftoff::GetSimd128Register(dst),
        liftoff::GetSimd128Register(lhs), liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::NeonU8, and v8::internal::Assembler::vqsub().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_i8x16_swizzle()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_swizzle (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 2783 of file liftoff-assembler-arm-inl.h.
                                                               {
  UseScratchRegisterScope temps(this);
  NeonListOperand table(liftoff::GetSimd128Register(lhs));
  if (dst == lhs) {
    // dst will be overwritten, so keep the table somewhere else.
    QwNeonRegister tbl = temps.AcquireQ();
    MacroAssembler::Move(tbl, liftoff::GetSimd128Register(lhs));
    table = NeonListOperand(tbl);
  }
  vtbl(dst.low_fp(), table, rhs.low_fp());
  vtbl(dst.high_fp(), table, rhs.high_fp());
}
References v8::internal::UseScratchRegisterScope::AcquireQ(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::MacroAssembler::Move(), v8::internal::Assembler::tbl(), and v8::internal::Assembler::vtbl().
Referenced by emit_i8x16_relaxed_swizzle().
emit_i8x16_uconvert_i16x8()
void v8::internal::wasm::LiftoffAssembler::emit_i8x16_uconvert_i16x8 (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4386 of file liftoff-assembler-arm-inl.h.
                                                                      {
  liftoff::S128NarrowOp(this, NeonU8, NeonS8, dst, lhs, rhs);
}
References v8::internal::NeonS8, v8::internal::NeonU8, and v8::internal::wasm::liftoff::S128NarrowOp().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_inc_i32_at()
void v8::internal::wasm::LiftoffAssembler::emit_inc_i32_at (Address address) [inline]
Definition at line 4720 of file liftoff-assembler-arm-inl.h.
                                                      {
  LiftoffRegList pinned;
  Register counter_addr = pinned.set(GetUnusedRegister(kGpReg, pinned)).gp();
  Register value = GetUnusedRegister(kGpReg, pinned).gp();
  mov(counter_addr, Operand(address));
  ldr(value, MemOperand(counter_addr, 0));
  add(value, value, Operand(1));
  str(value, MemOperand(counter_addr, 0));
}
References v8::internal::Assembler::add(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::kGpReg, v8::internal::Assembler::ldr(), v8::internal::MacroAssembler::mov(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::Assembler::str(), and v8::internal::value.
emit_jump() [1/2]
void v8::internal::wasm::LiftoffAssembler::emit_jump (Label * label) [inline]
Definition at line 2553 of file liftoff-assembler-arm-inl.h.
{ b(label); }
References v8::internal::Assembler::b().
emit_jump() [2/2]
void v8::internal::wasm::LiftoffAssembler::emit_jump (Register target) [inline]
Definition at line 2555 of file liftoff-assembler-arm-inl.h.
{ bx(target); }
References v8::internal::Assembler::bx().
emit_ptrsize_add()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_add (Register dst, Register lhs, Register rhs) [inline]
Definition at line 134 of file liftoff-assembler-inl.h.
                                                      {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_add(LiftoffRegister(dst), LiftoffRegister(lhs),
                 LiftoffRegister(rhs));
  } else {
    emit_i32_add(dst, lhs, rhs);
  }
}
References emit_i32_add(), emit_i64_add(), and v8::internal::kSystemPointerSize.
emit_ptrsize_addi()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_addi (Register dst, Register lhs, intptr_t imm) [inline]
Definition at line 173 of file liftoff-assembler-inl.h.
                                                       {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_addi(LiftoffRegister(dst), LiftoffRegister(lhs), imm);
  } else {
    emit_i32_addi(dst, lhs, static_cast<int32_t>(imm));
  }
}
References emit_i32_addi(), emit_i64_addi(), and v8::internal::kSystemPointerSize.
emit_ptrsize_and()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_and (Register dst, Register lhs, Register rhs) [inline]
Definition at line 154 of file liftoff-assembler-inl.h.
                                                      {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_and(LiftoffRegister(dst), LiftoffRegister(lhs),
                 LiftoffRegister(rhs));
  } else {
    emit_i32_and(dst, lhs, rhs);
  }
}
References emit_i32_and(), emit_i64_and(), and v8::internal::kSystemPointerSize.
emit_ptrsize_cond_jumpi()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_cond_jumpi (Condition cond, Label * label, Register lhs, int32_t imm, const FreezeCacheState & frozen) [inline]
Definition at line 2270 of file liftoff-assembler-arm64-inl.h.
                                                                               {
  Cmp(lhs.X(), Operand(imm));
  B(label, cond);
}
References v8::internal::MacroAssembler::B(), v8::internal::MacroAssembler::Cmp(), and v8::internal::CPURegister::X().
emit_ptrsize_muli()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_muli (Register dst, Register lhs, int32_t imm) [inline]
Definition at line 182 of file liftoff-assembler-inl.h.
                                                      {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_muli(LiftoffRegister(dst), LiftoffRegister(lhs), imm);
  } else {
    emit_i32_muli(dst, lhs, imm);
  }
}
References emit_i32_muli(), emit_i64_muli(), and v8::internal::kSystemPointerSize.
emit_ptrsize_set_cond()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_set_cond (Condition condition, Register dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 191 of file liftoff-assembler-inl.h.
                                                                  {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_set_cond(condition, dst, lhs, rhs);
  } else {
    emit_i32_set_cond(condition, dst, lhs.gp(), rhs.gp());
  }
}
References emit_i32_set_cond(), emit_i64_set_cond(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::kSystemPointerSize.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BinOp().
emit_ptrsize_shri()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_shri (Register dst, Register src, int amount) [inline]
Definition at line 164 of file liftoff-assembler-inl.h.
                                                     {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_shri(LiftoffRegister(dst), LiftoffRegister(src), amount);
  } else {
    emit_i32_shri(dst, src, amount);
  }
}
References emit_i32_shri(), emit_i64_shri(), and v8::internal::kSystemPointerSize.
emit_ptrsize_sub()
void v8::internal::wasm::LiftoffAssembler::emit_ptrsize_sub (Register dst, Register lhs, Register rhs) [inline]
Definition at line 144 of file liftoff-assembler-inl.h.
                                                      {
  if constexpr (kSystemPointerSize == 8) {
    emit_i64_sub(LiftoffRegister(dst), LiftoffRegister(lhs),
                 LiftoffRegister(rhs));
  } else {
    emit_i32_sub(dst, lhs, rhs);
  }
}
References emit_i32_sub(), emit_i64_sub(), and v8::internal::kSystemPointerSize.
emit_s128_and()
void v8::internal::wasm::LiftoffAssembler::emit_s128_and (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4319 of file liftoff-assembler-arm-inl.h.
                                                          {
  vand(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vand().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_s128_and_not()
void v8::internal::wasm::LiftoffAssembler::emit_s128_and_not (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4460 of file liftoff-assembler-arm-inl.h.
                                                              {
  vbic(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vbic().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_s128_const()
void v8::internal::wasm::LiftoffAssembler::emit_s128_const (LiftoffRegister dst, const uint8_t imms[16]) [inline]
Definition at line 4307 of file liftoff-assembler-arm-inl.h.
                                                               {
  uint64_t vals[2];
  memcpy(vals, imms, sizeof(vals));
  vmov(dst.low_fp(), base::Double(vals[0]));
  vmov(dst.high_fp(), base::Double(vals[1]));
}
References v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::wasm::LiftoffRegister::low_fp(), and v8::internal::Assembler::vmov().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::S128Const().
emit_s128_not()
void v8::internal::wasm::LiftoffAssembler::emit_s128_not (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 4315 of file liftoff-assembler-arm-inl.h.
                                                                             {
  vmvn(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vmvn().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_s128_or()
void v8::internal::wasm::LiftoffAssembler::emit_s128_or (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4325 of file liftoff-assembler-arm-inl.h.
                                                         {
  vorr(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::vorr().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_s128_relaxed_laneselect()
void v8::internal::wasm::LiftoffAssembler::emit_s128_relaxed_laneselect (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister mask, int lane_width) [inline]
Definition at line 2828 of file liftoff-assembler-arm-inl.h.
                                                                    {
  // ARM uses bytewise selection for all lane widths.
  emit_s128_select(dst, src1, src2, mask);
}
References emit_s128_select().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::EmitRelaxedLaneSelect().
emit_s128_select()
void v8::internal::wasm::LiftoffAssembler::emit_s128_select (LiftoffRegister dst, LiftoffRegister src1, LiftoffRegister src2, LiftoffRegister mask) [inline]
Definition at line 4337 of file liftoff-assembler-arm-inl.h.
                                                              {
  if (dst != mask) {
    vmov(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(mask));
  }
  vbsl(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src1),
       liftoff::GetSimd128Register(src2));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::Assembler::vbsl(), and v8::internal::Assembler::vmov().
Referenced by emit_s128_relaxed_laneselect(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_s128_store_nonzero_if_nan()
void v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan (Register dst, LiftoffRegister src, Register tmp_gp, LiftoffRegister tmp_s128, ValueKind lane_kind) [inline]
Definition at line 4981 of file liftoff-assembler-arm-inl.h.
                                                                           {
  QwNeonRegister src_q = liftoff::GetSimd128Register(src);
  QwNeonRegister tmp_q = liftoff::GetSimd128Register(tmp_s128);
  if (lane_kind == kF32) {
    vpadd(tmp_q.low(), src_q.low(), src_q.high());
    LowDwVfpRegister tmp_d =
        LowDwVfpRegister::from_code(tmp_s128.low_fp().code());
    vadd(tmp_d.low(), tmp_d.low(), tmp_d.high());
  } else {
    DCHECK_EQ(lane_kind, kF64);
    vadd(tmp_q.low(), src_q.low(), src_q.high());
  }
  emit_store_nonzero_if_nan(dst, tmp_q.low(), lane_kind);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), DCHECK_EQ, emit_store_nonzero_if_nan(), v8::internal::RegisterBase< LowDwVfpRegister, kDoubleCode_d16 >::from_code(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::LowDwVfpRegister::high(), v8::internal::QwNeonRegister::high(), v8::internal::kF32, v8::internal::kF64, v8::internal::LowDwVfpRegister::low(), v8::internal::QwNeonRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::Assembler::vadd(), and v8::internal::Assembler::vpadd().
emit_s128_xor()
void v8::internal::wasm::LiftoffAssembler::emit_s128_xor (LiftoffRegister dst, LiftoffRegister lhs, LiftoffRegister rhs) [inline]
Definition at line 4331 of file liftoff-assembler-arm-inl.h.
                                                          {
  veor(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(lhs),
       liftoff::GetSimd128Register(rhs));
}
References v8::internal::wasm::liftoff::GetSimd128Register(), and v8::internal::Assembler::veor().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::S128Const(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
emit_select()
bool v8::internal::wasm::LiftoffAssembler::emit_select (LiftoffRegister dst, Register condition, LiftoffRegister true_value, LiftoffRegister false_value, ValueKind kind) [inline]
Definition at line 2664 of file liftoff-assembler-arm-inl.h.
                                                   {
  return false;
}
emit_smi_check()
void v8::internal::wasm::LiftoffAssembler::emit_smi_check (Register obj, Label * target, SmiCheckMode mode, const FreezeCacheState & frozen) [inline]
Definition at line 2671 of file liftoff-assembler-arm-inl.h.
                                                                      {
  tst(obj, Operand(kSmiTagMask));
  Condition condition = mode == kJumpOnSmi ? eq : ne;
  b(condition, target);
}
References v8::internal::Assembler::b(), v8::internal::eq, kJumpOnSmi, v8::internal::kSmiTagMask, mode(), v8::internal::ne, and v8::internal::Assembler::tst().
emit_store_nonzero()
void v8::internal::wasm::LiftoffAssembler::emit_store_nonzero (Register dst) [inline]
Definition at line 5000 of file liftoff-assembler-arm-inl.h.
                                                      {
  str(dst, MemOperand(dst));
}
References v8::internal::Assembler::str().
emit_store_nonzero_if_nan()
void v8::internal::wasm::LiftoffAssembler::emit_store_nonzero_if_nan (Register dst, DoubleRegister src, ValueKind kind) [inline]
Definition at line 4966 of file liftoff-assembler-arm-inl.h.
                                                                 {
  if (kind == kF32) {
    FloatRegister src_f = liftoff::GetFloatRegister(src);
    VFPCompareAndSetFlags(src_f, src_f);
  } else {
    DCHECK_EQ(kind, kF64);
    VFPCompareAndSetFlags(src, src);
  }
  // Store a non-zero value if src is NaN.
  str(dst, MemOperand(dst), ne); // x != x iff isnan(x)
}
References DCHECK_EQ, v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::kF32, v8::internal::kF64, v8::internal::ne, v8::internal::Assembler::str(), and v8::internal::MacroAssembler::VFPCompareAndSetFlags().
Referenced by emit_s128_store_nonzero_if_nan().
emit_trace_instruction()
void v8::internal::wasm::LiftoffAssembler::emit_trace_instruction (uint32_t markid) [inline]
Definition at line 1215 of file liftoff-assembler-x64-inl.h.
                                                             {
  Assembler::emit_trace_instruction(Immediate(markid));
}
References v8::internal::Assembler::emit_trace_instruction().
emit_type_conversion()
bool v8::internal::wasm::LiftoffAssembler::emit_type_conversion (WasmOpcode opcode, LiftoffRegister dst, LiftoffRegister src, Label * trap = nullptr) [inline]
Definition at line 2357 of file liftoff-assembler-arm-inl.h.
                                                                              {
  switch (opcode) {
    case kExprI32ConvertI64:
      MacroAssembler::Move(dst.gp(), src.low_gp());
      return true;
    case kExprI32SConvertF32: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_s32_f32(
          scratch_f,
          liftoff::GetFloatRegister(src.fp())); // f32 -> i32 round to zero.
      vmov(dst.gp(), scratch_f);
      // Check underflow and NaN.
      vmov(scratch_f, Float32(static_cast<float>(INT32_MIN)));
      VFPCompareAndSetFlags(liftoff::GetFloatRegister(src.fp()), scratch_f);
      b(trap, lt);
      // Check overflow.
      cmp(dst.gp(), Operand(-1));
      b(trap, vs);
      return true;
    }
    case kExprI32UConvertF32: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_u32_f32(
          scratch_f,
          liftoff::GetFloatRegister(src.fp())); // f32 -> i32 round to zero.
      vmov(dst.gp(), scratch_f);
      // Check underflow and NaN.
      vmov(scratch_f, Float32(-1.0f));
      VFPCompareAndSetFlags(liftoff::GetFloatRegister(src.fp()), scratch_f);
      b(trap, le);
      // Check overflow.
      cmp(dst.gp(), Operand(-1));
      b(trap, eq);
      return true;
    }
    case kExprI32SConvertF64: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_s32_f64(scratch_f, src.fp()); // f64 -> i32 round to zero.
      vmov(dst.gp(), scratch_f);
      // Check underflow and NaN.
      DwVfpRegister scratch_d = temps.AcquireD();
      vmov(scratch_d, base::Double(static_cast<double>(INT32_MIN - 1.0)));
      VFPCompareAndSetFlags(src.fp(), scratch_d);
      b(trap, le);
      // Check overflow.
      vmov(scratch_d, base::Double(static_cast<double>(INT32_MAX + 1.0)));
      VFPCompareAndSetFlags(src.fp(), scratch_d);
      b(trap, ge);
      return true;
    }
    case kExprI32UConvertF64: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_u32_f64(scratch_f, src.fp()); // f64 -> i32 round to zero.
      vmov(dst.gp(), scratch_f);
      // Check underflow and NaN.
      DwVfpRegister scratch_d = temps.AcquireD();
      vmov(scratch_d, base::Double(static_cast<double>(-1.0)));
      VFPCompareAndSetFlags(src.fp(), scratch_d);
      b(trap, le);
      // Check overflow.
      vmov(scratch_d, base::Double(static_cast<double>(UINT32_MAX + 1.0)));
      VFPCompareAndSetFlags(src.fp(), scratch_d);
      b(trap, ge);
      return true;
    }
    case kExprI32SConvertSatF32: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_s32_f32(
          scratch_f,
          liftoff::GetFloatRegister(src.fp())); // f32 -> i32 round to zero.
      vmov(dst.gp(), scratch_f);
      return true;
    }
    case kExprI32UConvertSatF32: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_u32_f32(
          scratch_f,
          liftoff::GetFloatRegister(src.fp())); // f32 -> u32 round to zero.
      vmov(dst.gp(), scratch_f);
      return true;
    }
    case kExprI32SConvertSatF64: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_s32_f64(scratch_f, src.fp()); // f64 -> i32 round to zero.
      vmov(dst.gp(), scratch_f);
      return true;
    }
    case kExprI32UConvertSatF64: {
      UseScratchRegisterScope temps(this);
      SwVfpRegister scratch_f = temps.AcquireS();
      vcvt_u32_f64(scratch_f, src.fp()); // f64 -> u32 round to zero.
      vmov(dst.gp(), scratch_f);
      return true;
    }
    case kExprI32ReinterpretF32:
      vmov(dst.gp(), liftoff::GetFloatRegister(src.fp()));
      return true;
    case kExprI64SConvertI32:
      if (dst.low_gp() != src.gp()) mov(dst.low_gp(), src.gp());
      mov(dst.high_gp(), Operand(src.gp(), ASR, 31));
      return true;
    case kExprI64UConvertI32:
      if (dst.low_gp() != src.gp()) mov(dst.low_gp(), src.gp());
      mov(dst.high_gp(), Operand(0));
      return true;
    case kExprI64ReinterpretF64:
      vmov(dst.low_gp(), dst.high_gp(), src.fp());
      return true;
    case kExprF32SConvertI32: {
      SwVfpRegister dst_float = liftoff::GetFloatRegister(dst.fp());
      vmov(dst_float, src.gp());
      vcvt_f32_s32(dst_float, dst_float);
      return true;
    }
    case kExprF32UConvertI32: {
      SwVfpRegister dst_float = liftoff::GetFloatRegister(dst.fp());
      vmov(dst_float, src.gp());
      vcvt_f32_u32(dst_float, dst_float);
      return true;
    }
    case kExprF32ConvertF64:
      vcvt_f32_f64(liftoff::GetFloatRegister(dst.fp()), src.fp());
      return true;
    case kExprF32ReinterpretI32:
      vmov(liftoff::GetFloatRegister(dst.fp()), src.gp());
      return true;
    case kExprF64SConvertI32: {
      vmov(liftoff::GetFloatRegister(dst.fp()), src.gp());
      vcvt_f64_s32(dst.fp(), liftoff::GetFloatRegister(dst.fp()));
      return true;
    }
    case kExprF64UConvertI32: {
      vmov(liftoff::GetFloatRegister(dst.fp()), src.gp());
      vcvt_f64_u32(dst.fp(), liftoff::GetFloatRegister(dst.fp()));
      return true;
    }
    case kExprF64ConvertF32:
      vcvt_f64_f32(dst.fp(), liftoff::GetFloatRegister(src.fp()));
      return true;
    case kExprF64ReinterpretI64:
      vmov(dst.fp(), src.low_gp(), src.high_gp());
      return true;
    case kExprF64SConvertI64:
    case kExprF64UConvertI64:
    case kExprI64SConvertF32:
    case kExprI64UConvertF32:
    case kExprI64SConvertSatF32:
    case kExprI64UConvertSatF32:
    case kExprF32SConvertI64:
    case kExprF32UConvertI64:
    case kExprI64SConvertF64:
    case kExprI64UConvertF64:
    case kExprI64SConvertSatF64:
    case kExprI64UConvertSatF64:
      // These cases can be handled by the C fallback function.
      return false;
    default:
      UNREACHABLE();
  }
}
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::UseScratchRegisterScope::AcquireS(), v8::internal::ASR, v8::internal::Assembler::b(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::ge, v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::le, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::lt, v8::internal::MacroAssembler::mov(), v8::internal::MacroAssembler::Move(), v8::internal::UNREACHABLE(), v8::internal::Assembler::vcvt_f32_f64(), v8::internal::Assembler::vcvt_f32_s32(), v8::internal::Assembler::vcvt_f32_u32(), v8::internal::Assembler::vcvt_f64_f32(), v8::internal::Assembler::vcvt_f64_s32(), v8::internal::Assembler::vcvt_f64_u32(), v8::internal::Assembler::vcvt_s32_f32(), v8::internal::Assembler::vcvt_s32_f64(), v8::internal::Assembler::vcvt_u32_f32(), v8::internal::Assembler::vcvt_u32_f64(), v8::internal::MacroAssembler::VFPCompareAndSetFlags(), v8::internal::Assembler::vmov(), and v8::internal::AssemblerRISCVV::vs().
emit_u32_to_uintptr()
void v8::internal::wasm::LiftoffAssembler::emit_u32_to_uintptr (Register dst, Register src) [inline]
Definition at line 2011 of file liftoff-assembler-arm64-inl.h.
                                                                     {
  Uxtw(dst, src);
}
References v8::internal::MacroAssembler::Uxtw().
emit_v128_anytrue()
void v8::internal::wasm::LiftoffAssembler::emit_v128_anytrue (LiftoffRegister dst, LiftoffRegister src) [inline]
Definition at line 3981 of file liftoff-assembler-arm-inl.h.
                                                              {
  liftoff::EmitAnyTrue(this, dst, src);
}
References v8::internal::wasm::liftoff::EmitAnyTrue().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SimdOp().
EmitWriteBarrier()
void v8::internal::wasm::LiftoffAssembler::EmitWriteBarrier (Register target_object, Operand store_location, Register stored_value, LiftoffRegList pinned) [inline]
Definition at line 558 of file liftoff-assembler-ia32-inl.h.
                                                               {
  liftoff::CacheStatePreservingTempRegisters temps{this, pinned};
  Register scratch = temps.Acquire();
  Label exit;
  CheckPageFlag(target_object, scratch,
                MemoryChunk::kPointersFromHereAreInterestingMask, zero, &exit,
                Label::kNear);
  JumpIfSmi(stored_value, &exit, Label::kNear);
  CheckPageFlag(stored_value, scratch,
                MemoryChunk::kPointersToHereAreInterestingMask, zero, &exit,
                Label::kNear);
  lea(scratch, store_location);
  CallRecordWriteStubSaveRegisters(target_object, scratch,
                                   SaveFPRegsMode::kSave,
                                   StubCallMode::kCallWasmRuntimeStub);
  bind(&exit);
}
References v8::internal::Assembler::bind(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::MacroAssembler::JumpIfSmi(), v8::internal::Label::kNear, v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, v8::internal::MemoryChunk::kPointersToHereAreInterestingMask, v8::internal::kSave, v8::internal::Assembler::lea(), and v8::internal::zero.
Fill()
void v8::internal::wasm::LiftoffAssembler::Fill (LiftoffRegister reg, int offset, ValueKind kind) [inline]
Definition at line 1702 of file liftoff-assembler-arm-inl.h.
                                                                           {
  liftoff::Load(this, reg, liftoff::GetStackSlot(offset), kind);
}
References v8::internal::wasm::liftoff::GetStackSlot(), and v8::internal::wasm::liftoff::Load().
Referenced by v8::internal::wasm::ParallelMove::ExecuteLoads(), and LoadToFixedRegister().
FillI64Half()
void v8::internal::wasm::LiftoffAssembler::FillI64Half (Register reg, int offset, RegPairHalf half) [inline]
Definition at line 1706 of file liftoff-assembler-arm-inl.h.
                                                                             {
  ldr(reg, liftoff::GetHalfStackSlot(offset, half));
}
References v8::internal::wasm::liftoff::GetHalfStackSlot(), and v8::internal::Assembler::ldr().
Referenced by v8::internal::wasm::ParallelMove::ExecuteLoads(), and LoadI64HalfIntoRegister().
FillStackSlotsWithZero()
void v8::internal::wasm::LiftoffAssembler::FillStackSlotsWithZero (int start, int size) [inline]
Definition at line 1710 of file liftoff-assembler-arm-inl.h.
                                                                 {
  DCHECK_LT(0, size);
  DCHECK_EQ(0, size % 4);
  RecordUsedSpillOffset(start + size);
  // We need a zero reg. Always use r0 for that, and push it before to restore
  // its value afterwards.
  push(r0);
  mov(r0, Operand(0));
  if (size <= 36) {
    // Special straight-line code for up to 9 words. Generates one
    // instruction per word.
    for (int offset = 4; offset <= size; offset += 4) {
      str(r0, liftoff::GetHalfStackSlot(start + offset, kLowWord));
    }
  } else {
    // General case for bigger counts (9 instructions).
    // Use r1 for start address (inclusive), r2 for end address (exclusive).
    push(r1);
    push(r2);
    sub(r1, fp, Operand(start + size));
    sub(r2, fp, Operand(start));
    Label loop;
    bind(&loop);
    str(r0, MemOperand(r1, /* offset */ kSystemPointerSize, PostIndex));
    cmp(r1, r2);
    b(&loop, ne);
    pop(r2);
    pop(r1);
  }
  pop(r0);
}
References v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::Assembler::cmp(), DCHECK_EQ, DCHECK_LT, v8::internal::wasm::liftoff::GetHalfStackSlot(), v8::internal::wasm::kLowWord, v8::internal::kSystemPointerSize, v8::internal::MacroAssembler::mov(), v8::internal::ne, v8::internal::MacroAssembler::pop(), v8::internal::PostIndex, v8::internal::MacroAssembler::push(), RecordUsedSpillOffset(), size(), v8::internal::Assembler::str(), and v8::internal::Assembler::sub().
FinishCall()
void v8::internal::wasm::LiftoffAssembler::FinishCall (const ValueKindSig * sig, compiler::CallDescriptor * call_descriptor)
Definition at line 865 of file liftoff-assembler.cc.
                                                                           {
  int call_desc_return_idx = 0;
  for (ValueKind return_kind : sig->returns()) {
    DCHECK_LT(call_desc_return_idx, call_descriptor->ReturnCount());
    const bool needs_gp_pair = needs_gp_reg_pair(return_kind);
    const int num_lowered_params = 1 + needs_gp_pair;
    const ValueKind lowered_kind = needs_gp_pair ? kI32 : return_kind;
    const RegClass rc = reg_class_for(lowered_kind);
    // Initialize to anything, will be set in the loop and used afterwards.
    LiftoffRegister reg_pair[2] = {kGpCacheRegList.GetFirstRegSet(),
                                   kGpCacheRegList.GetFirstRegSet()};
    // Make sure not to clobber results in registers (which might not be the
    // first values to be processed) prematurely.
    LiftoffRegList pinned = AllReturnRegs();
    for (int pair_idx = 0; pair_idx < num_lowered_params; ++pair_idx) {
      LinkageLocation loc =
          call_descriptor->GetReturnLocation(call_desc_return_idx++);
      if (loc.IsRegister()) {
        DCHECK(!loc.IsAnyRegister());
        reg_pair[pair_idx] = LiftoffRegister::from_external_code(
            rc, lowered_kind, loc.AsRegister());
#if V8_TARGET_ARCH_64_BIT
        // See explanation in `LiftoffCompiler::ParameterProcessor`.
        if (return_kind == kI32) {
          DCHECK(!needs_gp_pair);
          clear_i32_upper_half(reg_pair[0].gp());
        }
#endif
      } else {
        DCHECK(loc.IsCallerFrameSlot());
        reg_pair[pair_idx] = GetUnusedRegister(rc, pinned);
        // Get slot offset relative to the stack pointer.
        int offset = call_descriptor->GetOffsetToReturns();
        int return_slot = -loc.GetLocation() - offset - 1;
        LoadReturnStackSlot(reg_pair[pair_idx],
                            return_slot * kSystemPointerSize, lowered_kind);
      }
      if (pair_idx == 0) {
        pinned.set(reg_pair[0]);
      }
    }
    if (num_lowered_params == 1) {
      PushRegister(return_kind, reg_pair[0]);
    } else {
      PushRegister(return_kind, LiftoffRegister::ForPair(reg_pair[0].gp(),
                                                         reg_pair[1].gp()));
    }
  }
  int return_slots = static_cast<int>(call_descriptor->ReturnSlotCount());
  RecordUsedSpillOffset(TopSpillOffset() + return_slots * kSystemPointerSize);
}
References v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::AllReturnRegs(), clear_i32_upper_half(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffRegister::from_external_code(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::compiler::CallDescriptor::GetOffsetToReturns(), v8::internal::compiler::CallDescriptor::GetReturnLocation(), GetUnusedRegister(), v8::internal::wasm::kGpCacheRegList, v8::internal::kI32, v8::internal::kSystemPointerSize, LoadReturnStackSlot(), v8::internal::loc, v8::internal::wasm::needs_gp_reg_pair(), PushRegister(), v8::internal::Assembler::rc, RecordUsedSpillOffset(), v8::internal::wasm::reg_class_for(), v8::internal::compiler::CallDescriptor::ReturnCount(), v8::internal::compiler::CallDescriptor::ReturnSlotCount(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::sig, and TopSpillOffset().
FinishCode()
void v8::internal::wasm::LiftoffAssembler::FinishCode () [inline]
Definition at line 617 of file liftoff-assembler-arm-inl.h.
{ CheckConstPool(true, false); }
References v8::internal::Assembler::CheckConstPool().
GetNumUses()
uint32_t v8::internal::wasm::LiftoffAssembler::GetNumUses (LiftoffRegister reg) const [inline]
Definition at line 506 of file liftoff-assembler.h.
                                                 {
    return cache_state_.get_use_count(reg);
  }
References cache_state_, and v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count().
GetTotalFrameSize()
int v8::internal::wasm::LiftoffAssembler::GetTotalFrameSize () const [inline]
Definition at line 1610 of file liftoff-assembler.h.
{ return max_used_spill_offset_; }
References max_used_spill_offset_.
Referenced by PatchPrepareStackFrame().
GetTotalFrameSlotCountForGC()
int v8::internal::wasm::LiftoffAssembler::GetTotalFrameSlotCountForGC () const
Definition at line 338 of file liftoff-assembler.cc.
                                                        {
  // The GC does not care about the actual number of spill slots, just about
  // the number of references that could be there in the spilling area. Note
  // that the offset of the first spill slot is kSystemPointerSize and not
  // '0'. Therefore we don't have to add '+1' here.
  return (max_used_spill_offset_ +
          StandardFrameConstants::kFixedFrameSizeAboveFp +
          ool_spill_space_size_) /
         kSystemPointerSize;
}
References v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kSystemPointerSize, max_used_spill_offset_, and ool_spill_space_size_.
GetUnusedRegister() [1/3]
LiftoffRegister v8::internal::wasm::LiftoffAssembler::GetUnusedRegister (LiftoffRegList candidates) [inline]
Definition at line 546 of file liftoff-assembler.h.
                                                               {
    DCHECK(!cache_state_.frozen);
    DCHECK(!candidates.is_empty());
    if (V8_LIKELY(cache_state_.has_unused_register(candidates))) {
      return cache_state_.unused_register(candidates);
    }
    return SpillOneRegister(candidates);
  }
References cache_state_, v8::internal::DCHECK(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::LiftoffRegList::is_empty(), SpillOneRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::unused_register(), and V8_LIKELY.
GetUnusedRegister() [2/3]
LiftoffRegister v8::internal::wasm::LiftoffAssembler::GetUnusedRegister (RegClass rc, LiftoffRegList pinned) [inline]
Definition at line 525 of file liftoff-assembler.h.
                                                                        {
    DCHECK(!cache_state_.frozen);
    if (kNeedI64RegPair && rc == kGpRegPair) {
      LiftoffRegList candidates = kGpCacheRegList.MaskOut(pinned);
      Register low = candidates.clear(GetUnusedRegister(candidates)).gp();
      Register high = GetUnusedRegister(candidates).gp();
      return LiftoffRegister::ForPair(low, high);
    } else if (kNeedS128RegPair && rc == kFpRegPair) {
      // kFpRegPair specific logic here because we need adjacent registers, not
      // just any two registers (like kGpRegPair).
      if (cache_state_.has_unused_register(rc, pinned)) {
        return cache_state_.unused_register(rc, pinned);
      }
      DoubleRegister low_fp = SpillAdjacentFpRegisters(pinned).fp();
      return LiftoffRegister::ForFpPair(low_fp);
    }
    LiftoffRegList candidates = GetCacheRegList(rc).MaskOut(pinned);
    return GetUnusedRegister(candidates);
  }
References cache_state_, v8::internal::wasm::LiftoffRegList::clear(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::ForFpPair(), v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::GetCacheRegList(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::kFpRegPair, v8::internal::wasm::kGpCacheRegList, v8::internal::wasm::kGpRegPair, v8::internal::wasm::kNeedI64RegPair, v8::internal::wasm::kNeedS128RegPair, v8::internal::wasm::LiftoffRegList::MaskOut(), v8::internal::Assembler::rc, SpillAdjacentFpRegisters(), and v8::internal::wasm::LiftoffAssembler::CacheState::unused_register().
GetUnusedRegister() [3/3]
LiftoffRegister v8::internal::wasm::LiftoffAssembler::GetUnusedRegister (RegClass rc, std::initializer_list< LiftoffRegister > try_first, LiftoffRegList pinned) [inline]
Definition at line 512 of file liftoff-assembler.h.
                             {
    DCHECK(!cache_state_.frozen);
    for (LiftoffRegister reg : try_first) {
      DCHECK_EQ(reg.reg_class(), rc);
      if (cache_state_.is_free(reg)) return reg;
    }
    return GetUnusedRegister(rc, pinned);
  }
References cache_state_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LiftoffAssembler::CacheState::is_free(), v8::internal::Assembler::rc, and v8::internal::wasm::LiftoffRegister::reg_class().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::TempRegisterScope::AddTempRegisters(), AtomicCompareExchange(), ClearRegister(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), emit_f32_copysign(), emit_f64_copysign(), emit_i16x8_bitmask(), emit_i32_popcnt(), emit_i32x4_bitmask(), emit_i64_popcnt(), emit_i64x2_mul(), emit_i8x16_bitmask(), emit_inc_i32_at(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::wasm::liftoff::EmitFloatMinOrMax(), v8::internal::wasm::liftoff::EmitInt32DivOrRem(), v8::internal::wasm::liftoff::EmitShiftOperation(), v8::internal::wasm::liftoff::EmitSimdShiftOp(), v8::internal::wasm::F16x8BinOpViaF32(), FinishCall(), v8::internal::wasm::liftoff::GetTmpByteRegister(), GetUnusedRegister(), v8::internal::wasm::liftoff::I64Binop(), v8::internal::wasm::liftoff::I64Shiftop(), LoadConstant(), LoadI64HalfIntoRegister(), LoadOldFramePointer(), LoadToModifiableRegister(), LoadToRegister_Slow(), v8::internal::wasm::liftoff::OpWithCarry(), and SpillAdjacentFpRegisters().
IncrementSmi()
void v8::internal::wasm::LiftoffAssembler::IncrementSmi (LiftoffRegister dst, int offset) [inline]
Definition at line 2204 of file liftoff-assembler-arm-inl.h.
                                                                   {
  if (!is_int12(offset)) {
    // For large offsets, ldr/str will need a scratch register, but we need
    // the single available scratch register here. So fold the offset into the
    // base address.
    // Note: if we ever want to use this function for callers that don't want
    // {dst} to get clobbered, we could spill it to the stack and restore it
    // later.
    add(dst.gp(), dst.gp(), Operand(offset));
    offset = 0;
  }
  UseScratchRegisterScope temps(this);
  Register scratch = temps.Acquire();
  ldr(scratch, MemOperand(dst.gp(), offset));
  add(scratch, scratch, Operand(Smi::FromInt(1)));
  str(scratch, MemOperand(dst.gp(), offset));
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::add(), v8::internal::Smi::FromInt(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::Assembler::ldr(), and v8::internal::Assembler::str().
Load()
void v8::internal::wasm::LiftoffAssembler::Load (LiftoffRegister dst, Register src_addr, Register offset_reg, uintptr_t offset_imm, LoadType type, uint32_t * protected_load_pc = nullptr, bool is_load_mem = false, bool i64_offset = false, bool needs_shift = false) [inline]
Definition at line 970 of file liftoff-assembler-arm-inl.h.
                                              {
  // Offsets >=2GB are statically OOB on 32-bit systems.
  DCHECK_LE(offset_imm, std::numeric_limits<int32_t>::max());
  liftoff::LoadInternal(this, dst, src_addr, offset_reg,
                        static_cast<int32_t>(offset_imm), type,
                        protected_load_pc, needs_shift);
}
References DCHECK_LE, v8::internal::wasm::liftoff::LoadInternal(), and v8::internal::tracing::type.
Referenced by AtomicLoad(), LoadCodePointer(), and LoadSmiAsInt32().
LoadCallerFrameSlot()
void v8::internal::wasm::LiftoffAssembler::LoadCallerFrameSlot (LiftoffRegister dst, uint32_t caller_slot_idx, ValueKind kind) [inline]
Definition at line 1595 of file liftoff-assembler-arm-inl.h.
                                                           {
  MemOperand src(fp, (caller_slot_idx + 1) * kSystemPointerSize);
  liftoff::Load(this, dst, src, kind);
}
References v8::internal::kSystemPointerSize, and v8::internal::wasm::liftoff::Load().
LoadCodePointer()
void v8::internal::wasm::LiftoffAssembler::LoadCodePointer (Register dst, Register src_addr, int32_t offset) [inline]
Definition at line 128 of file liftoff-assembler-inl.h.
                                                           {
    return Load(LiftoffRegister(dst), src_addr, no_reg, offset_imm,
                LoadType::kI32Load);
}
References Load(), and v8::internal::no_reg.
LoadConstant()
void v8::internal::wasm::LiftoffAssembler::LoadConstant (LiftoffRegister reg, WasmValue value) [inline]
Definition at line 725 of file liftoff-assembler-arm-inl.h.
                                                                        {
  switch (value.type().kind()) {
    case kI32:
      MacroAssembler::Move(reg.gp(), Operand(value.to_i32()));
      break;
    case kI64: {
      int32_t low_word = value.to_i64();
      int32_t high_word = value.to_i64() >> 32;
      MacroAssembler::Move(reg.low_gp(), Operand(low_word));
      MacroAssembler::Move(reg.high_gp(), Operand(high_word));
      break;
    }
    case kF32:
      vmov(liftoff::GetFloatRegister(reg.fp()), value.to_f32_boxed());
      break;
    case kF64: {
      Register extra_scratch = GetUnusedRegister(kGpReg, {}).gp();
      vmov(reg.fp(), base::Double(value.to_f64_boxed().get_bits()),
           extra_scratch);
      break;
    }
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetFloatRegister(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kF32, v8::internal::kF64, v8::internal::wasm::kGpReg, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::MacroAssembler::Move(), v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::Assembler::vmov().
Referenced by AtomicCompareExchange(), CallFrameSetupStub(), v8::internal::wasm::ParallelMove::ExecuteLoads(), LoadI64HalfIntoRegister(), LoadToFixedRegister(), and PrepareForBranch().
LoadFixedArrayLengthAsInt32()
void v8::internal::wasm::LiftoffAssembler::LoadFixedArrayLengthAsInt32 (LiftoffRegister dst, Register array, LiftoffRegList pinned) [inline]
Definition at line 106 of file liftoff-assembler-inl.h.
                                                                          {
  int offset = offsetof(FixedArray, length_) - kHeapObjectTag;
  LoadSmiAsInt32(dst, array, offset);
}
References v8::internal::kHeapObjectTag, and LoadSmiAsInt32().
LoadFromInstance()
void v8::internal::wasm::LiftoffAssembler::LoadFromInstance (Register dst, Register instance, int offset, int size) [inline]
Definition at line 762 of file liftoff-assembler-arm-inl.h.
                                                              {
  DCHECK_LE(0, offset);
  MemOperand src{instance, offset};
  switch (size) {
    case 1:
      ldrb(dst, src);
      break;
    case 4:
      ldr(dst, src);
      break;
    default:
      UNIMPLEMENTED();
  }
}
References DCHECK_LE, v8::internal::Assembler::ldr(), v8::internal::Assembler::ldrb(), size(), and v8::internal::UNIMPLEMENTED().
Referenced by MergeStackWith().
LoadFullPointer()
void v8::internal::wasm::LiftoffAssembler::LoadFullPointer (Register dst, Register src_addr, int32_t offset_imm) [inline]
Definition at line 919 of file liftoff-assembler-arm-inl.h.
                                                           {
  UseScratchRegisterScope temps(this);
  MemOperand src_op =
      liftoff::GetMemOp(this, &temps, src_addr, no_reg, offset_imm);
  ldr(dst, src_op);
}
References v8::internal::wasm::liftoff::GetMemOp(), v8::internal::Assembler::ldr(), and v8::internal::no_reg.
Referenced by MergeStackWith().
LoadI64HalfIntoRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::LoadI64HalfIntoRegister (VarState slot, RegPairHalf half, LiftoffRegList pinned) [private]
Definition at line 385 of file liftoff-assembler.cc.
                                                            {
  if (slot.is_reg()) {
    return half == kLowWord ? slot.reg().low() : slot.reg().high();
  }
  LiftoffRegister dst = GetUnusedRegister(kGpReg, pinned);
  if (slot.is_stack()) {
    FillI64Half(dst.gp(), slot.offset(), half);
    return dst;
  }
  DCHECK(slot.is_const());
  int32_t half_word =
      static_cast<int32_t>(half == kLowWord ? slot.constant().to_i64()
                                            : slot.constant().to_i64() >> 32);
  LoadConstant(dst, WasmValue(half_word));
  return dst;
}
References v8::internal::wasm::LiftoffVarState::constant(), v8::internal::DCHECK(), FillI64Half(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::wasm::kGpReg, v8::internal::wasm::kLowWord, LoadConstant(), v8::internal::wasm::LiftoffRegister::low(), v8::internal::wasm::LiftoffVarState::offset(), and v8::internal::wasm::LiftoffVarState::reg().
Referenced by MoveToReturnLocationsMultiReturn().
LoadInstanceDataFromFrame()
void v8::internal::wasm::LiftoffAssembler::LoadInstanceDataFromFrame (Register dst) [inline]
Definition at line 751 of file liftoff-assembler-arm-inl.h.
                                                             {
  ldr(dst, liftoff::GetInstanceDataOperand());
}
References v8::internal::wasm::liftoff::GetInstanceDataOperand(), and v8::internal::Assembler::ldr().
Referenced by CheckTierUp(), MergeStackWith(), and PrepareCall().
LoadLane()
void v8::internal::wasm::LiftoffAssembler::LoadLane (LiftoffRegister dst, LiftoffRegister src, Register addr, Register offset_reg, uintptr_t offset_imm, LoadType type, uint8_t lane, uint32_t * protected_load_pc, bool i64_offset) [inline]
Definition at line 2748 of file liftoff-assembler-arm-inl.h.
                                        {
  UseScratchRegisterScope temps(this);
  Register actual_src_addr = liftoff::CalculateActualAddress(
      this, &temps, addr, offset_reg, offset_imm);
  MacroAssembler::Move(liftoff::GetSimd128Register(dst),
                       liftoff::GetSimd128Register(src));
  *protected_load_pc = pc_offset();
  LoadStoreLaneParams load_params(type.mem_type().representation(), laneidx);
  NeonListOperand dst_op =
      NeonListOperand(load_params.low_op ? dst.low_fp() : dst.high_fp());
  MacroAssembler::LoadLane(load_params.sz, dst_op, load_params.laneidx,
                           NeonMemOperand(actual_src_addr));
}
References v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LoadStoreLaneParams::laneidx, v8::internal::MacroAssembler::LoadLane(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::LoadStoreLaneParams::low_op, v8::internal::MacroAssembler::Move(), v8::internal::AssemblerBase::pc_offset(), v8::internal::LoadStoreLaneParams::sz, and v8::internal::tracing::type.
LoadOldFramePointer()
Register v8::internal::wasm::LiftoffAssembler::LoadOldFramePointer () [inline]
Definition at line 673 of file liftoff-assembler-arm-inl.h.
                                               {
  if (!v8_flags.experimental_wasm_growable_stacks) {
    return fp;
  }
  LiftoffRegister old_fp = GetUnusedRegister(RegClass::kGpReg, {});
  Label done, call_runtime;
  ldr(old_fp.gp(), MemOperand(fp, TypedFrameConstants::kFrameTypeOffset));
  cmp(old_fp.gp(),
      Operand(StackFrame::TypeToMarker(StackFrame::WASM_SEGMENT_START)));
  b(&call_runtime, eq);
  mov(old_fp.gp(), fp);
  jmp(&done);
  bind(&call_runtime);
  LiftoffRegList regs_to_save = cache_state()->used_registers;
  PushRegisters(regs_to_save);
  MacroAssembler::Move(kCArgRegs[0], ExternalReference::isolate_address());
  PrepareCallCFunction(1);
  CallCFunction(ExternalReference::wasm_load_old_fp(), 1);
  if (old_fp.gp() != kReturnRegister0) {
    mov(old_fp.gp(), kReturnRegister0);
  }
  PopRegisters(regs_to_save);
  bind(&done);
  return old_fp.gp();
}
References v8::internal::Assembler::b(), v8::internal::Assembler::bind(), cache_state(), v8::internal::MacroAssembler::CallCFunction(), v8::internal::Assembler::cmp(), v8::internal::eq, GetUnusedRegister(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::ExternalReference::isolate_address(), v8::internal::MacroAssembler::jmp(), v8::internal::kCArgRegs, v8::internal::TypedFrameConstants::kFrameTypeOffset, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kGpReg, v8::internal::kReturnRegister0, v8::internal::Assembler::ldr(), v8::internal::MacroAssembler::mov(), v8::internal::MacroAssembler::Move(), PopRegisters(), v8::internal::MacroAssembler::PrepareCallCFunction(), PushRegisters(), v8::internal::StackFrame::TypeToMarker(), v8::internal::wasm::LiftoffAssembler::CacheState::used_registers, and v8::internal::v8_flags.
Referenced by MoveToReturnLocationsMultiReturn().
LoadProtectedPointer()
void v8::internal::wasm::LiftoffAssembler::LoadProtectedPointer (Register dst, Register src_addr, int32_t offset) [inline]
Definition at line 913 of file liftoff-assembler-arm-inl.h.
                                                            {
  static_assert(!V8_ENABLE_SANDBOX_BOOL);
  LoadTaggedPointer(dst, src_addr, no_reg, offset);
}
References LoadTaggedPointer(), v8::internal::no_reg, and V8_ENABLE_SANDBOX_BOOL.
Referenced by MergeStackWith().
LoadReturnStackSlot()
void v8::internal::wasm::LiftoffAssembler::LoadReturnStackSlot (LiftoffRegister dst, int offset, ValueKind kind) [inline]
Definition at line 1610 of file liftoff-assembler-arm-inl.h.
                                                           {
  MemOperand src(sp, offset);
  liftoff::Load(this, dst, src, kind);
}
References v8::internal::wasm::liftoff::Load().
Referenced by FinishCall().
LoadSmiAsInt32()
void v8::internal::wasm::LiftoffAssembler::LoadSmiAsInt32 (LiftoffRegister dst, Register src_addr, int32_t offset) [inline]
Definition at line 113 of file liftoff-assembler-inl.h.
                                                      {
  if constexpr (SmiValuesAre32Bits()) {
#if V8_TARGET_LITTLE_ENDIAN
    DCHECK_EQ(kSmiShiftSize + kSmiTagSize, 4 * kBitsPerByte);
    offset += 4;
#endif
    Load(dst, src_addr, no_reg, offset, LoadType::kI32Load);
  } else {
    DCHECK(SmiValuesAre31Bits());
    Load(dst, src_addr, no_reg, offset, LoadType::kI32Load);
    emit_i32_sari(dst.gp(), dst.gp(), kSmiTagSize);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, emit_i32_sari(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::kBitsPerByte, v8::internal::kSmiShiftSize, v8::internal::kSmiTagSize, Load(), v8::internal::no_reg, v8::internal::SmiValuesAre31Bits(), and v8::internal::SmiValuesAre32Bits().
Referenced by LoadFixedArrayLengthAsInt32().
LoadSpillAddress()
void v8::internal::wasm::LiftoffAssembler::LoadSpillAddress (Register dst, int offset, ValueKind kind) [inline]
Definition at line 1747 of file liftoff-assembler-arm-inl.h.
                                                     {
  sub(dst, fp, Operand(offset));
}
References v8::internal::Assembler::sub().
LoadTaggedPointer()
void v8::internal::wasm::LiftoffAssembler::LoadTaggedPointer (Register dst, Register src_addr, Register offset_reg, int32_t offset_imm, uint32_t * protected_load_pc = nullptr, bool offset_reg_needs_shift = false) [inline]
Definition at line 892 of file liftoff-assembler-arm-inl.h.
                                                           {
  static_assert(kTaggedSize == kInt32Size);
  liftoff::LoadInternal(this, LiftoffRegister(dst), src_addr, offset_reg,
                        offset_imm, LoadType::kI32Load, protected_load_pc,
                        needs_shift);
}
References v8::internal::kInt32Size, v8::internal::kTaggedSize, and v8::internal::wasm::liftoff::LoadInternal().
Referenced by LoadProtectedPointer().
LoadTaggedPointerFromInstance()
void v8::internal::wasm::LiftoffAssembler::LoadTaggedPointerFromInstance (Register dst, Register instance, int offset) [inline]
Definition at line 778 of file liftoff-assembler-arm-inl.h.
                                                                 {
  static_assert(kTaggedSize == kSystemPointerSize);
  ldr(dst, MemOperand{instance, offset});
}
References v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, and v8::internal::Assembler::ldr().
LoadToFixedRegister()
void v8::internal::wasm::LiftoffAssembler::LoadToFixedRegister (VarState slot, LiftoffRegister reg) [inline]
Definition at line 82 of file liftoff-assembler-inl.h.
                                                                             {
  DCHECK(slot.is_const() || slot.is_stack());
  if (slot.is_const()) {
    LoadConstant(reg, slot.constant());
  } else {
    Fill(reg, slot.offset(), slot.kind());
  }
}
References v8::internal::wasm::LiftoffVarState::constant(), v8::internal::DCHECK(), Fill(), v8::internal::wasm::LiftoffVarState::is_const(), v8::internal::wasm::LiftoffVarState::is_stack(), v8::internal::wasm::LiftoffVarState::kind(), LoadConstant(), and v8::internal::wasm::LiftoffVarState::offset().
Referenced by LoadToRegister_Slow(), MoveToReturnLocations(), and PopToFixedRegister().
LoadToModifiableRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::LoadToModifiableRegister (VarState slot, LiftoffRegList pinned) [inline]
Definition at line 408 of file liftoff-assembler.h.
                                                                  {
    LiftoffRegister reg = LoadToRegister(slot, pinned);
    // TODO(jkummerow): The following line is overly optimistic, as long as
    // we don't pop the VarState, the register will never be considered free.
    if (cache_state()->is_free(reg) && !pinned.has(reg)) return reg;
    LiftoffRegister new_reg = GetUnusedRegister(reg.reg_class(), pinned);
    // {new_reg} could be equal to {reg}, but it's unused by the stack now.
    // Also, {reg} still holds the previous value, even if it was spilled.
    if (new_reg != reg) Move(new_reg, reg, slot.kind());
    return new_reg;
  }
References cache_state(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffVarState::kind(), LoadToRegister(), Move(), and v8::internal::wasm::LiftoffRegister::reg_class().
LoadToRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::LoadToRegister (VarState slot, LiftoffRegList pinned) [inline]
Definition at line 393 of file liftoff-assembler.h.
                                                                  {
    if (V8_LIKELY(slot.is_reg())) return slot.reg();
    return LoadToRegister_Slow(slot, pinned);
  }
References v8::internal::wasm::LiftoffVarState::is_reg(), LoadToRegister_Slow(), v8::internal::wasm::LiftoffVarState::reg(), and V8_LIKELY.
Referenced by LoadToModifiableRegister(), MoveToReturnLocationsMultiReturn(), and PeekToRegister().
LoadToRegister_Slow()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::LoadToRegister_Slow (VarState slot, LiftoffRegList pinned)
Definition at line 377 of file liftoff-assembler.cc.
                                                                             {
  DCHECK(!slot.is_reg());
  LiftoffRegister reg = GetUnusedRegister(reg_class_for(slot.kind()), pinned);
  LoadToFixedRegister(slot, reg);
  return reg;
}
References v8::internal::DCHECK(), GetUnusedRegister(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::kind(), LoadToFixedRegister(), and v8::internal::wasm::reg_class_for().
Referenced by LoadToRegister().
LoadTransform()
void v8::internal::wasm::LiftoffAssembler::LoadTransform (LiftoffRegister dst, Register src_addr, Register offset_reg, uintptr_t offset_imm, LoadType type, LoadTransformationKind transform, uint32_t * protected_load_pc, bool i64_offset) [inline]
Definition at line 2679 of file liftoff-assembler-arm-inl.h.
                                                      {
  UseScratchRegisterScope temps(this);
  Register actual_src_addr = liftoff::CalculateActualAddress(
      this, &temps, src_addr, offset_reg, offset_imm);
  *protected_load_pc = pc_offset();
  MachineType memtype = type.mem_type();
  if (transform == LoadTransformationKind::kExtend) {
    if (memtype == MachineType::Int8()) {
      vld1(Neon8, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      vmovl(NeonS8, liftoff::GetSimd128Register(dst), dst.low_fp());
    } else if (memtype == MachineType::Uint8()) {
      vld1(Neon8, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      vmovl(NeonU8, liftoff::GetSimd128Register(dst), dst.low_fp());
    } else if (memtype == MachineType::Int16()) {
      vld1(Neon16, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      vmovl(NeonS16, liftoff::GetSimd128Register(dst), dst.low_fp());
    } else if (memtype == MachineType::Uint16()) {
      vld1(Neon16, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      vmovl(NeonU16, liftoff::GetSimd128Register(dst), dst.low_fp());
    } else if (memtype == MachineType::Int32()) {
      vld1(Neon32, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      vmovl(NeonS32, liftoff::GetSimd128Register(dst), dst.low_fp());
    } else if (memtype == MachineType::Uint32()) {
      vld1(Neon32, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      vmovl(NeonU32, liftoff::GetSimd128Register(dst), dst.low_fp());
    }
  } else if (transform == LoadTransformationKind::kZeroExtend) {
    Simd128Register dest = liftoff::GetSimd128Register(dst);
    if (memtype == MachineType::Int32()) {
      vmov(dest, 0);
      vld1s(Neon32, NeonListOperand(dst.low_fp()), 0,
            NeonMemOperand(actual_src_addr));
    } else {
      DCHECK_EQ(MachineType::Int64(), memtype);
      vmov(dest.high(), 0);
      vld1(Neon64, NeonListOperand(dest.low()),
           NeonMemOperand(actual_src_addr));
    }
  } else {
    DCHECK_EQ(LoadTransformationKind::kSplat, transform);
    if (memtype == MachineType::Int8()) {
      vld1r(Neon8, NeonListOperand(liftoff::GetSimd128Register(dst)),
            NeonMemOperand(actual_src_addr));
    } else if (memtype == MachineType::Int16()) {
      vld1r(Neon16, NeonListOperand(liftoff::GetSimd128Register(dst)),
            NeonMemOperand(actual_src_addr));
    } else if (memtype == MachineType::Int32()) {
      vld1r(Neon32, NeonListOperand(liftoff::GetSimd128Register(dst)),
            NeonMemOperand(actual_src_addr));
    } else if (memtype == MachineType::Int64()) {
      vld1(Neon32, NeonListOperand(dst.low_fp()),
           NeonMemOperand(actual_src_addr));
      MacroAssembler::Move(dst.high_fp(), dst.low_fp());
    }
  }
}
References v8::internal::wasm::liftoff::CalculateActualAddress(), DCHECK_EQ, v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::MachineType::Int16(), v8::internal::MachineType::Int32(), v8::internal::MachineType::Int64(), v8::internal::MachineType::Int8(), v8::internal::wasm::kExtend, v8::internal::wasm::kSplat, v8::internal::wasm::kZeroExtend, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::MacroAssembler::Move(), v8::internal::Neon16, v8::internal::Neon32, v8::internal::Neon64, v8::internal::Neon8, v8::internal::NeonS16, v8::internal::NeonS32, v8::internal::NeonS8, v8::internal::NeonU16, v8::internal::NeonU32, v8::internal::NeonU8, v8::internal::AssemblerBase::pc_offset(), v8::internal::tracing::type, v8::internal::MachineType::Uint16(), v8::internal::MachineType::Uint32(), v8::internal::MachineType::Uint8(), v8::internal::Assembler::vld1(), v8::internal::Assembler::vld1r(), v8::internal::Assembler::vld1s(), v8::internal::Assembler::vmov(), and v8::internal::Assembler::vmovl().
LoadTrustedPointer()
void v8::internal::wasm::LiftoffAssembler::LoadTrustedPointer (Register dst, Register src_addr, int offset, IndirectPointerTag tag) [inline]
Definition at line 755 of file liftoff-assembler-arm-inl.h.
                                                                              {
  static_assert(!V8_ENABLE_SANDBOX_BOOL);
  static_assert(!COMPRESS_POINTERS_BOOL);
  ldr(dst, MemOperand{src_addr, offset});
}
References COMPRESS_POINTERS_BOOL, v8::internal::Assembler::ldr(), and V8_ENABLE_SANDBOX_BOOL.
local_kind()
ValueKind v8::internal::wasm::LiftoffAssembler::local_kind (uint32_t index) [inline]
Definition at line 1612 of file liftoff-assembler.h.
                                       {
    DCHECK_GT(num_locals_, index);
    ValueKind* locals =
        num_locals_ <= kInlineLocalKinds ? local_kinds_ : more_local_kinds_;
    return locals[index];
  }
References DCHECK_GT, v8::internal::index, kInlineLocalKinds, local_kinds_, more_local_kinds_, and num_locals_.
MaybeOSR()
void v8::internal::wasm::LiftoffAssembler::MaybeOSR () [inline]
Definition at line 4964 of file liftoff-assembler-arm-inl.h.
{}
MergeFullStackWith()
void v8::internal::wasm::LiftoffAssembler::MergeFullStackWith (CacheState & target)
Definition at line 495 of file liftoff-assembler.cc.
                                                            {
  DCHECK_EQ(cache_state_.stack_height(), target.stack_height());
  // TODO(clemensb): Reuse the same ParallelMove object to save some
  // allocations.
  ParallelMove parallel_move{this};
  for (uint32_t i = 0, e = cache_state_.stack_height(); i < e; ++i) {
    parallel_move.Transfer(target.stack_state[i], cache_state_.stack_state[i]);
    DCHECK(!SlotInterference(target.stack_state[i],
                             base::VectorOf(cache_state_.stack_state) + i + 1));
  }
  // Full stack merging is only done for forward jumps, so we can just clear the
  // cache registers at the target in case of mismatch.
  if (cache_state_.cached_instance_data != target.cached_instance_data) {
    target.ClearCachedInstanceRegister();
  }
  if (cache_state_.cached_mem_index != target.cached_mem_index ||
      cache_state_.cached_mem_start != target.cached_mem_start) {
    target.ClearCachedMemStartRegister();
  }
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_index, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_start, v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedInstanceRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedMemStartRegister(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LiftoffAssembler::CacheState::stack_height(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, v8::internal::wasm::ParallelMove::Transfer(), and v8::base::VectorOf().
MergeIntoNewState()
LiftoffAssembler::CacheState v8::internal::wasm::LiftoffAssembler::MergeIntoNewState (uint32_t num_locals, uint32_t arity, uint32_t stack_depth)
Definition at line 152 of file liftoff-assembler.cc.
                                                               {
  CacheState target{zone()};
  // The source state looks like this:
  // |------locals------|---(stack prefix)---|--(discarded)--|----merge----|
  // <-- num_locals --> <-- stack_depth --> <-- arity -->
  //
  // We compute the following target state from it:
  // |------locals------|---(stack prefix)----|----merge----|
  // <-- num_locals --> <-- stack_depth --> <-- arity -->
  //
  // The target state will have dropped the "(discarded)" region, and the
  // "locals" and "merge" regions have been modified to avoid any constants and
  // avoid duplicate register uses. This ensures that later merges can
  // successfully transfer into the target state.
  // The "stack prefix" region will be identical for any source that merges into
  // that state.
  if (cache_state_.cached_instance_data != no_reg) {
    target.SetInstanceCacheRegister(cache_state_.cached_instance_data);
  }
  DCHECK_EQ(cache_state_.cached_mem_start == no_reg,
            cache_state_.cached_mem_index == CacheState::kNoCachedMemIndex);
  if (cache_state_.cached_mem_start != no_reg) {
    target.SetMemStartCacheRegister(cache_state_.cached_mem_start,
                                    cache_state_.cached_mem_index);
  }
  uint32_t target_height = num_locals + stack_depth + arity;
  target.stack_state.resize(target_height);
  const VarState* source_begin = cache_state_.stack_state.data();
  VarState* target_begin = target.stack_state.data();
  // Compute the starts of the different regions, for source and target (see
  // pictograms above).
  const VarState* locals_source = source_begin;
  const VarState* stack_prefix_source = source_begin + num_locals;
  const VarState* discarded_source = stack_prefix_source + stack_depth;
  const VarState* merge_source = cache_state_.stack_state.end() - arity;
  VarState* locals_target = target_begin;
  VarState* stack_prefix_target = target_begin + num_locals;
  VarState* merge_target = target_begin + num_locals + stack_depth;
  // Try to keep locals and the merge region in their registers. Registers used
  // multiple times need to be copied to another free register. Compute the list
  // of used registers.
  LiftoffRegList used_regs;
  for (auto& src : base::VectorOf(locals_source, num_locals)) {
    if (src.is_reg()) used_regs.set(src.reg());
  }
  // If there is more than one operand in the merge region, a stack-to-stack
  // move can interfere with a register reload, which would not be handled
  // correctly by the ParallelMove. To avoid this, spill all registers in
  // this region.
  MergeAllowRegisters allow_registers =
      arity <= 1 ? kRegistersAllowed : kRegistersNotAllowed;
  if (allow_registers) {
    for (auto& src : base::VectorOf(merge_source, arity)) {
      if (src.is_reg()) used_regs.set(src.reg());
    }
  }
  ParallelMove parallel_move{this};
  // The merge region is often empty, hence check for this before doing any
  // work (even though not needed for correctness).
  if (arity) {
    // Initialize the merge region. If this region moves, try to turn stack
    // slots into registers since we need to load the value anyways.
    MergeKeepStackSlots keep_merge_stack_slots =
        target_height == cache_state_.stack_height()
            ? kKeepStackSlots
            : kTurnStackSlotsIntoRegisters;
    // Shift spill offsets down to keep slots contiguous. We place the merge
    // region right after the "stack prefix", if it exists.
    int merge_region_stack_offset = discarded_source == source_begin
                                        ? StaticStackFrameSize()
                                        : discarded_source[-1].offset();
    InitMergeRegion(&target, merge_source, merge_target, arity,
                    keep_merge_stack_slots, kConstantsNotAllowed,
                    allow_registers, kNoReuseRegisters, used_regs,
                    merge_region_stack_offset, parallel_move);
  }
  // Initialize the locals region. Here, stack slots stay stack slots (because
  // they do not move). Try to keep register in registers, but avoid duplicates.
  if (num_locals) {
    InitMergeRegion(&target, locals_source, locals_target, num_locals,
                    kKeepStackSlots, kConstantsNotAllowed, kRegistersAllowed,
                    kNoReuseRegisters, used_regs, 0, parallel_move);
  }
  // Consistency check: All the {used_regs} are really in use now.
  DCHECK_EQ(used_regs, target.used_registers & used_regs);
  // Last, initialize the "stack prefix" region. Here, constants are allowed,
  // but registers which are already used for the merge region or locals must be
  // moved to other registers or spilled. If a register appears twice in the
  // source region, ensure to use the same register twice in the target region.
  if (stack_depth) {
    InitMergeRegion(&target, stack_prefix_source, stack_prefix_target,
                    stack_depth, kKeepStackSlots, kConstantsAllowed,
                    kRegistersAllowed, kReuseRegisters, used_regs, 0,
                    parallel_move);
  }
  return target;
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_index, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_start, DCHECK_EQ, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kConstantsAllowed, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kConstantsNotAllowed, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kKeepStackSlots, v8::internal::wasm::LiftoffAssembler::CacheState::kNoCachedMemIndex, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kNoReuseRegisters, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kRegistersAllowed, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kRegistersNotAllowed, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kReuseRegisters, v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::kTurnStackSlotsIntoRegisters, v8::internal::no_reg, num_locals(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_height(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, StaticStackFrameSize(), v8::base::VectorOf(), and zone().
MergeStackWith()
void v8::internal::wasm::LiftoffAssembler::MergeStackWith (CacheState & target, uint32_t arity, JumpDirection jump_direction)
Definition at line 517 of file liftoff-assembler.cc.
                                                                    {
  // Before: ----------------|----- (discarded) ----|--- arity ---|
  // ^target_stack_height ^stack_base ^stack_height
  // After: ----|-- arity --|
  // ^ ^target_stack_height
  // ^target_stack_base
  uint32_t stack_height = cache_state_.stack_height();
  uint32_t target_stack_height = target.stack_height();
  DCHECK_LE(target_stack_height, stack_height);
  DCHECK_LE(arity, target_stack_height);
  uint32_t stack_base = stack_height - arity;
  uint32_t target_stack_base = target_stack_height - arity;
  ParallelMove parallel_move{this};
  for (uint32_t i = 0; i < target_stack_base; ++i) {
    parallel_move.Transfer(target.stack_state[i], cache_state_.stack_state[i]);
    DCHECK(!SlotInterference(
        target.stack_state[i],
        base::VectorOf(cache_state_.stack_state.data() + i + 1,
                       target_stack_base - i - 1)));
    DCHECK(!SlotInterference(
        target.stack_state[i],
        base::VectorOf(cache_state_.stack_state.data() + stack_base, arity)));
  }
  for (uint32_t i = 0; i < arity; ++i) {
    parallel_move.Transfer(target.stack_state[target_stack_base + i],
                           cache_state_.stack_state[stack_base + i]);
    DCHECK(!SlotInterference(
        target.stack_state[target_stack_base + i],
        base::VectorOf(cache_state_.stack_state.data() + stack_base + i + 1,
                       arity - i - 1)));
  }
  // Check whether the cached instance and/or memory start need to be moved to
  // another register. Register moves are executed as part of the
  // {ParallelMove}. Remember whether the register content has to be
  // reloaded after executing the stack parallel_move.
  bool reload_instance_data = false;
  // If the instance cache registers match, or the destination has no instance
  // cache register, nothing needs to be done.
  if (cache_state_.cached_instance_data != target.cached_instance_data &&
      target.cached_instance_data != no_reg) {
    // On forward jumps, just reset the cached register in the target state.
    if (jump_direction == kForwardJump) {
      target.ClearCachedInstanceRegister();
    } else if (cache_state_.cached_instance_data != no_reg) {
      // If the source has the instance cached but in the wrong register,
      // execute a register move as part of the stack transfer.
      parallel_move.MoveRegister(
          LiftoffRegister{target.cached_instance_data},
          LiftoffRegister{cache_state_.cached_instance_data}, kIntPtrKind);
    } else {
      // Otherwise (the source state has no cached instance), we reload later.
      reload_instance_data = true;
    }
  }
  bool reload_mem_start = false;
  // If the cached memory start registers match, or the destination has no cache
  // register, nothing needs to be done.
  DCHECK_EQ(target.cached_mem_start == no_reg,
            target.cached_mem_index == CacheState::kNoCachedMemIndex);
  if ((cache_state_.cached_mem_start != target.cached_mem_start ||
       cache_state_.cached_mem_index != target.cached_mem_index) &&
      target.cached_mem_start != no_reg) {
    // On forward jumps, just reset the cached register in the target state.
    if (jump_direction == kForwardJump) {
      target.ClearCachedMemStartRegister();
    } else if (cache_state_.cached_mem_index == target.cached_mem_index) {
      DCHECK_NE(no_reg, cache_state_.cached_mem_start);
      // If the source has the content but in the wrong register, execute a
      // register move as part of the stack transfer.
      parallel_move.MoveRegister(LiftoffRegister{target.cached_mem_start},
                                 LiftoffRegister{cache_state_.cached_mem_start},
                                 kIntPtrKind);
    } else {
      // Otherwise (the source state has no cached content), we reload later.
      reload_mem_start = true;
    }
  }
  // Now execute stack transfers and register moves/loads.
  parallel_move.Execute();
  if (reload_instance_data) {
    LoadInstanceDataFromFrame(target.cached_instance_data);
  }
  if (reload_mem_start) {
    // {target.cached_instance_data} already got restored above, so we can use
    // it if it exists.
    Register instance_data = target.cached_instance_data;
    if (instance_data == no_reg) {
      // We don't have the instance data available yet. Store it into the target
      // mem_start, so that we can load the mem0_start from there.
      instance_data = target.cached_mem_start;
      LoadInstanceDataFromFrame(instance_data);
    }
    if (target.cached_mem_index == 0) {
      LoadFromInstance(
          target.cached_mem_start, instance_data,
          ObjectAccess::ToTagged(WasmTrustedInstanceData::kMemory0StartOffset),
          sizeof(size_t));
    } else {
      LoadProtectedPointer(
          target.cached_mem_start, instance_data,
          ObjectAccess::ToTagged(
              WasmTrustedInstanceData::kProtectedMemoryBasesAndSizesOffset));
      int buffer_offset =
          wasm::ObjectAccess::ToTagged(OFFSET_OF_DATA_START(ByteArray)) +
          kSystemPointerSize * target.cached_mem_index * 2;
      LoadFullPointer(target.cached_mem_start, target.cached_mem_start,
                      buffer_offset);
    }
  }
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_index, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_start, v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedInstanceRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedMemStartRegister(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_NE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::instance_data, kForwardJump, kIntPtrKind, v8::internal::wasm::LiftoffAssembler::CacheState::kNoCachedMemIndex, v8::internal::kSystemPointerSize, LoadFromInstance(), LoadFullPointer(), LoadInstanceDataFromFrame(), LoadProtectedPointer(), v8::internal::no_reg, OFFSET_OF_DATA_START, v8::internal::wasm::LiftoffAssembler::CacheState::stack_height(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, v8::internal::wasm::ObjectAccess::ToTagged(), v8::internal::wasm::ParallelMove::Transfer(), and v8::base::VectorOf().
Move() [1/3]
void v8::internal::wasm::LiftoffAssembler::Move (DoubleRegister dst, DoubleRegister src, ValueKind kind) [inline]
Definition at line 1645 of file liftoff-assembler-arm-inl.h.
                                            {
  DCHECK_NE(dst, src);
  if (kind == kF32) {
    vmov(liftoff::GetFloatRegister(dst), liftoff::GetFloatRegister(src));
  } else if (kind == kF64) {
    vmov(dst, src);
  } else {
    DCHECK_EQ(kS128, kind);
    vmov(liftoff::GetSimd128Register(dst), liftoff::GetSimd128Register(src));
  }
}
References DCHECK_EQ, DCHECK_NE, v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::wasm::liftoff::GetSimd128Register(), v8::internal::kF32, v8::internal::kF64, v8::internal::kS128, and v8::internal::Assembler::vmov().
Move() [2/3]
void v8::internal::wasm::LiftoffAssembler::Move (LiftoffRegister dst, LiftoffRegister src, ValueKind kind)
Definition at line 918 of file liftoff-assembler.cc.
                                            {
  DCHECK_EQ(dst.reg_class(), src.reg_class());
  DCHECK_NE(dst, src);
  if (kNeedI64RegPair && dst.is_gp_pair()) {
    // Use the {ParallelMove} to move pairs, as the registers in the
    // pairs might overlap.
    ParallelMove{this}.MoveRegister(dst, src, kind);
  } else if (kNeedS128RegPair && dst.is_fp_pair()) {
    // Calling low_fp is fine, Move will automatically check the kind and
    // convert this FP to its SIMD register, and use a SIMD move.
    Move(dst.low_fp(), src.low_fp(), kind);
  } else if (dst.is_gp()) {
    Move(dst.gp(), src.gp(), kind);
  } else {
    Move(dst.fp(), src.fp(), kind);
  }
}
References DCHECK_EQ, DCHECK_NE, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), v8::internal::wasm::LiftoffRegister::is_gp(), v8::internal::wasm::LiftoffRegister::is_gp_pair(), v8::internal::wasm::kNeedI64RegPair, v8::internal::wasm::kNeedS128RegPair, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::wasm::ParallelMove::MoveRegister(), and v8::internal::wasm::LiftoffRegister::reg_class().
Referenced by CallCWithStackBuffer(), ClearRegister(), v8::internal::wasm::ParallelMove::ExecuteMove(), LoadToModifiableRegister(), MoveToReturnLocations(), v8::internal::wasm::liftoff::OpWithCarry(), PopToFixedRegister(), and PrepareForBranch().
Move() [3/3]
void v8::internal::wasm::LiftoffAssembler::Move (Register dst, Register src, ValueKind kind) [inline]
Definition at line 1639 of file liftoff-assembler-arm-inl.h.
                                                                      {
  DCHECK_NE(dst, src);
  DCHECK(kind == kI32 || is_reference(kind));
  MacroAssembler::Move(dst, src);
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::wasm::is_reference(), v8::internal::kI32, and v8::internal::MacroAssembler::Move().
MoveStackValue()
void v8::internal::wasm::LiftoffAssembler::MoveStackValue (uint32_t dst_offset, uint32_t src_offset, ValueKind kind) [inline]
Definition at line 1616 of file liftoff-assembler-arm-inl.h.
                                                      {
  DCHECK_NE(dst_offset, src_offset);
  liftoff::CacheStatePreservingTempRegisters temps{this};
  Register scratch = temps.Acquire();
  const int kRegSize = 4;
  DCHECK_EQ(0, SlotSizeForType(kind) % kRegSize);
  int words = SlotSizeForType(kind) / kRegSize;
  if (src_offset < dst_offset) {
    do {
      ldr(scratch, liftoff::GetStackSlot(src_offset));
      str(scratch, liftoff::GetStackSlot(dst_offset));
      dst_offset -= kSystemPointerSize;
      src_offset -= kSystemPointerSize;
    } while (--words);
  } else {
    while (words--) {
      ldr(scratch, liftoff::GetStackSlot(src_offset - words * kRegSize));
      str(scratch, liftoff::GetStackSlot(dst_offset - words * kRegSize));
    }
  }
}
References DCHECK_EQ, DCHECK_NE, v8::internal::wasm::liftoff::GetStackSlot(), v8::internal::kSystemPointerSize, v8::internal::Assembler::ldr(), SlotSizeForType(), and v8::internal::Assembler::str().
Referenced by DropExceptionValueAtOffset(), and v8::internal::wasm::ParallelMove::TransferToStack().
MoveToReturnLocations()
void v8::internal::wasm::LiftoffAssembler::MoveToReturnLocations (const FunctionSig * sig, compiler::CallDescriptor * descriptor)
Definition at line 946 of file liftoff-assembler.cc.
                                                                {
  DCHECK_LT(0, sig->return_count());
  if (V8_UNLIKELY(sig->return_count() > 1)) {
    MoveToReturnLocationsMultiReturn(sig, descriptor);
    return;
  }
  ValueKind return_kind = sig->GetReturn(0).kind();
  // Defaults to a gp reg, will be set below if return kind is not gp.
  LiftoffRegister return_reg = LiftoffRegister(kGpReturnRegisters[0]);
  if (needs_gp_reg_pair(return_kind)) {
    return_reg =
        LiftoffRegister::ForPair(kGpReturnRegisters[0], kGpReturnRegisters[1]);
  } else if (needs_fp_reg_pair(return_kind)) {
    return_reg = LiftoffRegister::ForFpPair(kFpReturnRegisters[0]);
  } else if (reg_class_for(return_kind) == kFpReg) {
    return_reg = LiftoffRegister(kFpReturnRegisters[0]);
  } else {
    DCHECK_EQ(kGpReg, reg_class_for(return_kind));
  }
  VarState& slot = cache_state_.stack_state.back();
  if (V8_LIKELY(slot.is_reg())) {
    if (slot.reg() != return_reg) {
      Move(return_reg, slot.reg(), slot.kind());
    }
  } else {
    LoadToFixedRegister(cache_state_.stack_state.back(), return_reg);
  }
}
References cache_state_, DCHECK_EQ, DCHECK_LT, v8::internal::wasm::LiftoffRegister::ForFpPair(), v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::kFpReg, v8::internal::wasm::kFpReturnRegisters, v8::internal::wasm::kGpReg, v8::internal::wasm::kGpReturnRegisters, v8::internal::wasm::LiftoffVarState::kind(), LoadToFixedRegister(), Move(), MoveToReturnLocationsMultiReturn(), v8::internal::wasm::needs_fp_reg_pair(), v8::internal::wasm::needs_gp_reg_pair(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::wasm::reg_class_for(), v8::internal::sig, v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, V8_LIKELY, and V8_UNLIKELY.
MoveToReturnLocationsMultiReturn()
void v8::internal::wasm::LiftoffAssembler::MoveToReturnLocationsMultiReturn (const FunctionSig * sig, compiler::CallDescriptor * descriptor)
Definition at line 978 of file liftoff-assembler.cc.
                                                                {
  DCHECK_LT(1, sig->return_count());
  ParallelMove parallel_move{this};
  // We sometimes allocate a register to perform stack-to-stack moves, which can
  // cause a spill in the cache state. Conservatively save and restore the
  // original state in case it is needed after the current instruction
  // (conditional branch).
  CacheState saved_state{zone()};
#if DEBUG
  uint32_t saved_state_frozenness = cache_state_.frozen;
  cache_state_.frozen = 0;
#endif
  saved_state.Split(*cache_state());
  int call_desc_return_idx = 0;
  DCHECK_LE(sig->return_count(), cache_state_.stack_height());
  VarState* slots = cache_state_.stack_state.end() - sig->return_count();
  LiftoffRegList pinned;
  Register old_fp = LoadOldFramePointer();
  if (v8_flags.experimental_wasm_growable_stacks) {
    pinned.set(LiftoffRegister(old_fp));
  }
  // Fill return frame slots first to ensure that all potential spills happen
  // before we prepare the stack transfers.
  for (size_t i = 0; i < sig->return_count(); ++i) {
    ValueKind return_kind = sig->GetReturn(i).kind();
    bool needs_gp_pair = needs_gp_reg_pair(return_kind);
    int num_lowered_params = 1 + needs_gp_pair;
    for (int pair_idx = 0; pair_idx < num_lowered_params; ++pair_idx) {
      LinkageLocation loc =
          descriptor->GetReturnLocation(call_desc_return_idx++);
      if (loc.IsCallerFrameSlot()) {
        RegPairHalf half = pair_idx == 0 ? kLowWord : kHighWord;
        VarState& slot = slots[i];
        LiftoffRegister reg = needs_gp_pair
                                  ? LoadI64HalfIntoRegister(slot, half, pinned)
                                  : LoadToRegister(slot, pinned);
        ValueKind lowered_kind = needs_gp_pair ? kI32 : return_kind;
        StoreCallerFrameSlot(reg, -loc.AsCallerFrameSlot(), lowered_kind,
                             old_fp);
      }
    }
  }
  // Prepare and execute stack transfers.
  call_desc_return_idx = 0;
  for (size_t i = 0; i < sig->return_count(); ++i) {
    ValueKind return_kind = sig->GetReturn(i).kind();
    bool needs_gp_pair = needs_gp_reg_pair(return_kind);
    int num_lowered_params = 1 + needs_gp_pair;
    for (int pair_idx = 0; pair_idx < num_lowered_params; ++pair_idx) {
      RegPairHalf half = pair_idx == 0 ? kLowWord : kHighWord;
      LinkageLocation loc =
          descriptor->GetReturnLocation(call_desc_return_idx++);
      if (loc.IsRegister()) {
        DCHECK(!loc.IsAnyRegister());
        int reg_code = loc.AsRegister();
        ValueKind lowered_kind = needs_gp_pair ? kI32 : return_kind;
        RegClass rc = reg_class_for(lowered_kind);
        LiftoffRegister reg =
            LiftoffRegister::from_external_code(rc, return_kind, reg_code);
        VarState& slot = slots[i];
        if (needs_gp_pair) {
          parallel_move.LoadI64HalfIntoRegister(reg, slot, half);
        } else {
          parallel_move.LoadIntoRegister(reg, slot);
        }
      }
    }
  }
  cache_state()->Steal(saved_state);
#if DEBUG
  cache_state_.frozen = saved_state_frozenness;
#endif
}
References cache_state(), cache_state_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, v8::internal::wasm::LiftoffRegister::from_external_code(), v8::internal::compiler::CallDescriptor::GetReturnLocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kHighWord, v8::internal::kI32, v8::internal::wasm::kLowWord, LoadI64HalfIntoRegister(), LoadOldFramePointer(), LoadToRegister(), v8::internal::loc, v8::internal::wasm::needs_gp_reg_pair(), v8::internal::Assembler::rc, v8::internal::wasm::reg_class_for(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::sig, v8::internal::wasm::LiftoffAssembler::CacheState::Split(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_height(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, v8::internal::wasm::LiftoffAssembler::CacheState::Steal(), StoreCallerFrameSlot(), v8::internal::v8_flags, and zone().
Referenced by MoveToReturnLocations().
NeedsAlignment()
bool v8::internal::wasm::LiftoffAssembler::NeedsAlignment (ValueKind kind) [inline], [static]
Definition at line 635 of file liftoff-assembler-arm-inl.h.
                                                    {
  return kind == kS128 || is_reference(kind);
}
References v8::internal::wasm::is_reference(), and v8::internal::kS128.
Referenced by NextSpillOffset().
NextSpillOffset() [1/2]
int v8::internal::wasm::LiftoffAssembler::NextSpillOffset (ValueKind kind) [inline]
Definition at line 47 of file liftoff-assembler-inl.h.
                                                    {
  return NextSpillOffset(kind, TopSpillOffset());
}
References NextSpillOffset(), and TopSpillOffset().
NextSpillOffset() [2/2]
int v8::internal::wasm::LiftoffAssembler::NextSpillOffset (ValueKind kind, int top_spill_offset) [inline], [static]
Definition at line 39 of file liftoff-assembler-inl.h.
                                                                          {
  int offset = top_spill_offset + SlotSizeForType(kind);
  if (NeedsAlignment(kind)) {
    offset = RoundUp(offset, SlotSizeForType(kind));
  }
  return offset;
}
References NeedsAlignment(), RoundUp(), and SlotSizeForType().
Referenced by DropExceptionValueAtOffset(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion(), NextSpillOffset(), PushConstant(), PushException(), PushRegister(), and PushStack().
num_locals()
uint32_t v8::internal::wasm::LiftoffAssembler::num_locals () const [inline]
Definition at line 1604 of file liftoff-assembler.h.
{ return num_locals_; }
References num_locals_.
Referenced by MergeIntoNewState(), PrepareForBranch(), and set_num_locals().
OolSpillCount()
int v8::internal::wasm::LiftoffAssembler::OolSpillCount () const
Definition at line 349 of file liftoff-assembler.cc.
                                          {
  return ool_spill_space_size_ / kSystemPointerSize;
}
References v8::internal::kSystemPointerSize, and ool_spill_space_size_.
ParallelRegisterMove() [1/2]
void v8::internal::wasm::LiftoffAssembler::ParallelRegisterMove (base::Vector< const ParallelRegisterMoveTuple > tuples)
Definition at line 937 of file liftoff-assembler.cc.
                                                        {
  ParallelMove parallel_move{this};
  for (auto tuple : tuples) {
    if (tuple.dst == tuple.src) continue;
    parallel_move.MoveRegister(tuple.dst, tuple.src, tuple.kind);
  }
}
References v8::internal::wasm::ParallelMove::MoveRegister().
Referenced by AtomicLoad(), v8::internal::wasm::liftoff::Emit64BitShiftOperation(), and ParallelRegisterMove().
ParallelRegisterMove() [2/2]
void v8::internal::wasm::LiftoffAssembler::ParallelRegisterMove (std::initializer_list< ParallelRegisterMoveTuple > moves) [inline]
Definition at line 641 of file liftoff-assembler.h.
                                                            {
    ParallelRegisterMove(base::VectorOf(moves));
  }
References ParallelRegisterMove(), and v8::base::VectorOf().
PatchPrepareStackFrame()
void v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame (int offset, SafepointTableBuilder * safepoint_table_builder, bool feedback_vector_slot, size_t stack_param_slots) [inline]
Definition at line 526 of file liftoff-assembler-arm-inl.h.
                                                         {
  // The frame_size includes the frame marker and the instance slot. Both are
  // pushed as part of frame construction, so we don't need to allocate memory
  // for them anymore.
  int frame_size = GetTotalFrameSize() - 2 * kSystemPointerSize;
  // The frame setup builtin also pushes the feedback vector.
  if (feedback_vector_slot) {
    frame_size -= kSystemPointerSize;
  }
  PatchingAssembler patching_assembler(AssemblerOptions{},
                                       buffer_start_ + offset,
                                       liftoff::kPatchInstructionsRequired);
  if (V8_LIKELY(frame_size < 4 * KB)) {
    // This is the standard case for small frames: just subtract from SP and be
    // done with it.
    patching_assembler.sub(sp, sp, Operand(frame_size));
    patching_assembler.PadWithNops();
    return;
  }
  // The frame size is bigger than 4KB, so we might overflow the available stack
  // space if we first allocate the frame and then do the stack check (we will
  // need some remaining stack space for throwing the exception). That's why we
  // check the available stack space before we allocate the frame. To do this we
  // replace the {__ sub(sp, sp, framesize)} with a jump to OOL code that does
  // this "extended stack check".
  //
  // The OOL code can simply be generated here with the normal assembler,
  // because all other code generation, including OOL code, has already finished
  // when {PatchPrepareStackFrame} is called. The function prologue then jumps
  // to the current {pc_offset()} to execute the OOL code for allocating the
  // large frame.
  // Emit the unconditional branch in the function prologue (from {offset} to
  // {pc_offset()}).
  patching_assembler.b(pc_offset() - offset - Instruction::kPcLoadDelta);
  patching_assembler.PadWithNops();
  // If the frame is bigger than the stack, we throw the stack overflow
  // exception unconditionally. Thereby we can avoid the integer overflow
  // check in the condition code.
  RecordComment("OOL: stack check for large frame");
  Label continuation;
  if (frame_size < v8_flags.stack_size * 1024) {
    UseScratchRegisterScope temps(this);
    Register stack_limit = temps.Acquire();
    LoadStackLimit(stack_limit, StackLimitKind::kRealStackLimit);
    add(stack_limit, stack_limit, Operand(frame_size));
    cmp(sp, stack_limit);
    b(cs /* higher or same */, &continuation);
  }
  if (v8_flags.experimental_wasm_growable_stacks) {
    LiftoffRegList regs_to_save;
    regs_to_save.set(WasmHandleStackOverflowDescriptor::GapRegister());
    regs_to_save.set(WasmHandleStackOverflowDescriptor::FrameBaseRegister());
    for (auto reg : kGpParamRegisters) regs_to_save.set(reg);
    for (auto reg : kFpParamRegisters) regs_to_save.set(reg);
    PushRegisters(regs_to_save);
    mov(WasmHandleStackOverflowDescriptor::GapRegister(), Operand(frame_size));
    add(WasmHandleStackOverflowDescriptor::FrameBaseRegister(), fp,
        Operand(stack_param_slots * kSystemPointerSize +
                CommonFrameConstants::kFixedFrameSizeAboveFp));
    CallBuiltin(Builtin::kWasmHandleStackOverflow);
    safepoint_table_builder->DefineSafepoint(this);
    PopRegisters(regs_to_save);
  } else {
    Call(static_cast<Address>(Builtin::kWasmStackOverflow),
         RelocInfo::WASM_STUB_CALL);
    // The call will not return; just define an empty safepoint.
    safepoint_table_builder->DefineSafepoint(this);
    if (v8_flags.debug_code) stop();
  }
  bind(&continuation);
  // Now allocate the stack space. Note that this might do more than just
  // decrementing the SP; consult {MacroAssembler::AllocateStackSpace}.
  AllocateStackSpace(frame_size);
  // Jump back to the start of the function, from {pc_offset()} to
  // right after the reserved space for the {__ sub(sp, sp, framesize)} (which
  // is a branch now).
  int func_start_offset =
      offset + liftoff::kPatchInstructionsRequired * kInstrSize;
  b(func_start_offset - pc_offset() - Instruction::kPcLoadDelta);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::add(), v8::internal::MacroAssembler::AllocateStackSpace(), v8::internal::Assembler::b(), v8::internal::Assembler::bind(), v8::internal::AssemblerBase::buffer_start_, v8::internal::MacroAssembler::Call(), CallBuiltin(), v8::internal::Assembler::cmp(), v8::internal::cs, v8::internal::SafepointTableBuilder::DefineSafepoint(), v8::internal::WasmHandleStackOverflowDescriptor::GapRegister(), GetTotalFrameSize(), v8::internal::KB, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::wasm::kFpParamRegisters, v8::internal::wasm::kGpParamRegisters, v8::internal::kInstrSize, v8::internal::wasm::liftoff::kPatchInstructionsRequired, v8::internal::Instruction::kPcLoadDelta, v8::internal::kRealStackLimit, v8::internal::kSystemPointerSize, v8::internal::MacroAssembler::LoadStackLimit(), v8::internal::MacroAssembler::mov(), v8::internal::AssemblerBase::pc_offset(), PopRegisters(), PushRegisters(), v8::internal::AssemblerBase::RecordComment(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::Assembler::stop(), v8::internal::Assembler::sub(), v8::internal::v8_flags, V8_LIKELY, and v8::internal::RelocInfo::WASM_STUB_CALL.
PeekToRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::PeekToRegister (int index, LiftoffRegList pinned) [inline]
Definition at line 459 of file liftoff-assembler.h.
                                                                   {
    DCHECK_LT(index, cache_state_.stack_state.size());
    VarState& slot = cache_state_.stack_state.end()[-1 - index];
    if (V8_LIKELY(slot.is_reg())) return slot.reg();
    LiftoffRegister reg = LoadToRegister(slot, pinned);
    cache_state_.inc_used(reg);
    slot.MakeRegister(reg);
    return reg;
  }
References cache_state_, DCHECK_LT, v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::index, v8::internal::wasm::LiftoffVarState::is_reg(), LoadToRegister(), v8::internal::wasm::LiftoffVarState::MakeRegister(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and V8_LIKELY.
PopRegisters()
void v8::internal::wasm::LiftoffAssembler::PopRegisters (LiftoffRegList regs) [inline]
Definition at line 4767 of file liftoff-assembler-arm-inl.h.
                                                       {
  LiftoffRegList fp_regs = regs & kFpCacheRegList;
  while (!fp_regs.is_empty()) {
    LiftoffRegister reg = fp_regs.GetLastRegSet();
    DoubleRegister last = reg.fp();
    DoubleRegister first = last;
    fp_regs.clear(reg);
    while (!fp_regs.is_empty()) {
      LiftoffRegister reg = fp_regs.GetLastRegSet();
      int code = reg.fp().code();
      if ((code != first.code() - 1) || ((last.code() - code + 1) > 16)) break;
      first = reg.fp();
      fp_regs.clear(reg);
    }
    vldm(ia_w, sp, first, last);
  }
  RegList core_regs = regs.GetGpList();
  if (!core_regs.is_empty()) {
    ldm(ia_w, sp, core_regs);
  }
}
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), code, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegList::GetGpList(), v8::internal::wasm::LiftoffRegList::GetLastRegSet(), v8::internal::ia_w, v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::kFpCacheRegList, v8::internal::Assembler::ldm(), and v8::internal::Assembler::vldm().
Referenced by CheckStackShrink(), LoadOldFramePointer(), and PatchPrepareStackFrame().
PopToFixedRegister()
void v8::internal::wasm::LiftoffAssembler::PopToFixedRegister (LiftoffRegister reg) [inline]
Definition at line 91 of file liftoff-assembler-inl.h.
                                                             {
  DCHECK(!cache_state_.stack_state.empty());
  VarState slot = cache_state_.stack_state.back();
  cache_state_.stack_state.pop_back();
  if (V8_LIKELY(slot.is_reg())) {
    cache_state_.dec_used(slot.reg());
    if (slot.reg() == reg) return;
    if (cache_state_.is_used(reg)) SpillRegister(reg);
    Move(reg, slot.reg(), slot.kind());
    return;
  }
  if (cache_state_.is_used(reg)) SpillRegister(reg);
  LoadToFixedRegister(slot, reg);
}
References cache_state_, v8::internal::DCHECK(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::LiftoffVarState::kind(), LoadToFixedRegister(), Move(), v8::internal::wasm::LiftoffVarState::reg(), SpillRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and V8_LIKELY.
PopToModifiableRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::PopToModifiableRegister (LiftoffRegList pinned = {}) [inline]
Definition at line 440 of file liftoff-assembler.h.
                                                                  {}) {
    ValueKind kind = cache_state_.stack_state.back().kind();
    LiftoffRegister reg = PopToRegister(pinned);
    if (cache_state()->is_free(reg) && !pinned.has(reg)) return reg;
    LiftoffRegister new_reg = GetUnusedRegister(reg.reg_class(), pinned);
    // {new_reg} could be equal to {reg}, but it's unused by the stack now.
    // Also, {reg} still holds the previous value, even if it was spilled.
    if (new_reg != reg) Move(new_reg, reg, kind);
    return new_reg;
  }
PopToRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::PopToRegister (LiftoffRegList pinned = {}) [inline]
Definition at line 431 of file liftoff-assembler.h.
                                                                  {}) {
    VarState slot = PopVarState();
    return LoadToRegister(slot, pinned);
  }
PopVarState()
VarState v8::internal::wasm::LiftoffAssembler::PopVarState () [inline]
Definition at line 423 of file liftoff-assembler.h.
                                   {
    DCHECK(!cache_state_.stack_state.empty());
    VarState slot = cache_state_.stack_state.back();
    cache_state_.stack_state.pop_back();
    if (V8_LIKELY(slot.is_reg())) cache_state_.dec_used(slot.reg());
    return slot;
  }
References cache_state_, v8::internal::DCHECK(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and V8_LIKELY.
PrepareBuiltinCall()
void v8::internal::wasm::LiftoffAssembler::PrepareBuiltinCall (const ValueKindSig * sig, compiler::CallDescriptor * call_descriptor, std::initializer_list< VarState > params)
Definition at line 749 of file liftoff-assembler.cc.
                                          {
  LiftoffStackSlots stack_slots{this};
  ParallelMove parallel_move{this};
  LiftoffRegList param_regs;
  PrepareStackTransfers(sig, call_descriptor, params.begin(), &stack_slots,
                        &parallel_move, &param_regs);
  SpillAllRegisters();
  int param_slots = static_cast<int>(call_descriptor->ParameterSlotCount());
  if (param_slots > 0) {
    stack_slots.Construct(param_slots);
  }
  // Execute the stack transfers before filling the instance register.
  parallel_move.Execute();
  // Reset register use counters.
  cache_state_.reset_used_registers();
}
References cache_state_, v8::internal::compiler::CallDescriptor::ParameterSlotCount(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), v8::internal::wasm::LiftoffAssembler::CacheState::reset_used_registers(), v8::internal::sig, and SpillAllRegisters().
PrepareCall()
void v8::internal::wasm::LiftoffAssembler::PrepareCall (const ValueKindSig * sig, compiler::CallDescriptor * call_descriptor, Register * target = nullptr, Register target_instance = no_reg)
Definition at line 769 of file liftoff-assembler.cc.
                                                                  {
  ASM_CODE_COMMENT(this);
  uint32_t num_params = static_cast<uint32_t>(sig->parameter_count());
  LiftoffStackSlots stack_slots{this};
  ParallelMove parallel_move{this};
  LiftoffRegList param_regs;
  // Move the target instance (if supplied) into the correct instance register.
  Register instance_reg = wasm::kGpParamRegisters[0];
  // Check that the call descriptor agrees. Input 0 is the call target, 1 is the
  // instance.
  DCHECK_EQ(
      instance_reg,
      Register::from_code(call_descriptor->GetInputLocation(1).AsRegister()));
  param_regs.set(instance_reg);
  if (target_instance_data == no_reg) {
    target_instance_data = cache_state_.cached_instance_data;
  }
  if (target_instance_data != no_reg && target_instance_data != instance_reg) {
    parallel_move.MoveRegister(LiftoffRegister(instance_reg),
                               LiftoffRegister(target_instance_data),
                               kIntPtrKind);
  }
  int param_slots = static_cast<int>(call_descriptor->ParameterSlotCount());
  if (num_params) {
    uint32_t param_base = cache_state_.stack_height() - num_params;
    PrepareStackTransfers(sig, call_descriptor,
                          &cache_state_.stack_state[param_base], &stack_slots,
                          &parallel_move, &param_regs);
  }
  // If the target register overlaps with a parameter register, then move the
  // target to another free register, or spill to the stack.
  if (target && param_regs.has(LiftoffRegister(*target))) {
    // Try to find another free register.
    LiftoffRegList free_regs = kGpCacheRegList.MaskOut(param_regs);
    static_assert(sizeof(WasmCodePointer) == kUInt32Size);
    if (!free_regs.is_empty()) {
      LiftoffRegister new_target = free_regs.GetFirstRegSet();
      parallel_move.MoveRegister(new_target, LiftoffRegister(*target), kI32);
      *target = new_target.gp();
    } else {
      stack_slots.Add(VarState(kI32, LiftoffRegister(*target), 0), param_slots);
      param_slots++;
      *target = no_reg;
    }
  }
  // After figuring out all register and stack moves, drop the parameter slots
  // from the stack.
  DropValues(num_params);
  // Spill all remaining cache slots.
  cache_state_.ClearAllCacheRegisters();
  // Iterate backwards, spilling register slots until all registers are free.
  if (!cache_state_.used_registers.is_empty()) {
    for (auto* slot = cache_state_.stack_state.end() - 1;; --slot) {
      DCHECK_LE(cache_state_.stack_state.begin(), slot);
      if (!slot->is_reg()) continue;
      Spill(slot->offset(), slot->reg(), slot->kind());
      cache_state_.dec_used(slot->reg());
      slot->MakeStack();
      if (cache_state_.used_registers.is_empty()) break;
    }
  }
  // All slots are either spilled on the stack, or hold constants now.
  DCHECK(std::all_of(
      cache_state_.stack_state.begin(), cache_state_.stack_state.end(),
      [](const VarState& slot) { return slot.is_stack() || slot.is_const(); }));
  if (param_slots > 0) {
    stack_slots.Construct(param_slots);
  }
  // Execute the stack transfers before filling the instance register.
  parallel_move.Execute();
  // Reload the instance from the stack if we do not have it in a register.
  if (target_instance_data == no_reg) {
    LoadInstanceDataFromFrame(instance_reg);
  }
}
References v8::base::all_of(), ASM_CODE_COMMENT, v8::internal::LinkageLocation::AsRegister(), cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data, v8::internal::wasm::LiftoffAssembler::CacheState::ClearAllCacheRegisters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), DropValues(), v8::internal::Register::from_code(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::compiler::CallDescriptor::GetInputLocation(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::kGpCacheRegList, v8::internal::wasm::kGpParamRegisters, v8::internal::kI32, kIntPtrKind, v8::internal::kUInt32Size, LoadInstanceDataFromFrame(), v8::internal::wasm::LiftoffRegList::MaskOut(), v8::internal::no_reg, v8::internal::compiler::CallDescriptor::ParameterSlotCount(), v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::PrepareStackTransfers(), v8::internal::wasm::LiftoffRegList::set(), v8::internal::sig, Spill(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_height(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and v8::internal::wasm::LiftoffAssembler::CacheState::used_registers.
PrepareForBranch()
void v8::internal::wasm::LiftoffAssembler::PrepareForBranch (uint32_t arity, LiftoffRegList pinned)
Definition at line 434 of file liftoff-assembler.cc.
                                                                             {
  VarState* stack_base = cache_state_.stack_state.data();
  for (auto slots :
       {base::VectorOf(stack_base + cache_state_.stack_state.size() - arity,
                       arity),
        base::VectorOf(stack_base, num_locals())}) {
    for (VarState& slot : slots) {
      if (slot.is_reg()) {
        // Registers used more than once can't be used for merges.
        if (cache_state_.get_use_count(slot.reg()) > 1) {
          RegClass rc = reg_class_for(slot.kind());
          if (cache_state_.has_unused_register(rc, pinned)) {
            LiftoffRegister dst_reg = cache_state_.unused_register(rc, pinned);
            Move(dst_reg, slot.reg(), slot.kind());
            cache_state_.inc_used(dst_reg);
            cache_state_.dec_used(slot.reg());
            slot.MakeRegister(dst_reg);
          } else {
            Spill(slot.offset(), slot.reg(), slot.kind());
            cache_state_.dec_used(slot.reg());
            slot.MakeStack();
          }
        }
        continue;
      }
      // Materialize constants.
      if (!slot.is_const()) continue;
      RegClass rc = reg_class_for(slot.kind());
      if (cache_state_.has_unused_register(rc, pinned)) {
        LiftoffRegister reg = cache_state_.unused_register(rc, pinned);
        LoadConstant(reg, slot.constant());
        cache_state_.inc_used(reg);
        slot.MakeRegister(reg);
      } else {
        Spill(slot.offset(), slot.constant());
        slot.MakeStack();
      }
    }
  }
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count(), v8::internal::wasm::LiftoffAssembler::CacheState::has_unused_register(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), LoadConstant(), Move(), num_locals(), v8::internal::Assembler::rc, v8::internal::wasm::reg_class_for(), Spill(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, v8::internal::wasm::LiftoffAssembler::CacheState::unused_register(), and v8::base::VectorOf().
PrepareStackFrame()
int v8::internal::wasm::LiftoffAssembler::PrepareStackFrame () [inline]
Definition at line 461 of file liftoff-assembler-arm-inl.h.
                                        {
  if (!CpuFeatures::IsSupported(ARMv7)) {
    bailout(kUnsupportedArchitecture, "Liftoff needs ARMv7");
    return 0;
  }
  uint32_t offset = static_cast<uint32_t>(pc_offset());
  // PatchPrepareStackFrame will patch this in order to increase the stack
  // appropriately. Additional nops are required as the bytes operand might
  // require extra moves to encode.
  for (int i = 0; i < liftoff::kPatchInstructionsRequired; i++) {
    nop();
  }
  DCHECK_EQ(offset + liftoff::kPatchInstructionsRequired * kInstrSize,
            pc_offset());
  return offset;
}
References bailout(), DCHECK_EQ, v8::internal::CpuFeatures::IsSupported(), v8::internal::kInstrSize, v8::internal::wasm::liftoff::kPatchInstructionsRequired, v8::internal::wasm::kUnsupportedArchitecture, v8::internal::Assembler::nop(), and v8::internal::AssemblerBase::pc_offset().
PrepareTailCall()
void v8::internal::wasm::LiftoffAssembler::PrepareTailCall (int num_callee_stack_params, int stack_param_delta) [inline]
Definition at line 498 of file liftoff-assembler-arm-inl.h.
                                                              {
  {
    UseScratchRegisterScope temps(this);
    Register scratch = temps.Acquire();
    // Push the return address and frame pointer to complete the stack frame.
    sub(sp, sp, Operand(8));
    ldr(scratch, MemOperand(fp, 4));
    str(scratch, MemOperand(sp, 4));
    ldr(scratch, MemOperand(fp, 0));
    str(scratch, MemOperand(sp, 0));
    // Shift the whole frame upwards.
    int slot_count = num_callee_stack_params + 2;
    for (int i = slot_count - 1; i >= 0; --i) {
      ldr(scratch, MemOperand(sp, i * 4));
      str(scratch, MemOperand(fp, (i - stack_param_delta) * 4));
    }
  }
  // Set the new stack and frame pointer.
  sub(sp, fp, Operand(stack_param_delta * 4));
  Pop(lr, fp);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Assembler::ldr(), v8::internal::MacroAssembler::Pop(), v8::internal::Assembler::str(), and v8::internal::Assembler::sub().
PushConstant()
void v8::internal::wasm::LiftoffAssembler::PushConstant (ValueKind kind, int32_t i32_const) [inline]
Definition at line 73 of file liftoff-assembler-inl.h.
                                                                     {
  V8_ASSUME(kind == kI32 || kind == kI64);
  cache_state_.stack_state.emplace_back(kind, i32_const, NextSpillOffset(kind));
}
References cache_state_, v8::internal::kI32, v8::internal::kI64, NextSpillOffset(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and V8_ASSUME.
PushException()
void v8::internal::wasm::LiftoffAssembler::PushException () [inline]
Definition at line 65 of file liftoff-assembler-inl.h.
                                     {
  LiftoffRegister reg{kReturnRegister0};
  // This is used after a call, so {kReturnRegister0} is not used yet.
  DCHECK(cache_state_.is_free(reg));
  cache_state_.inc_used(reg);
  cache_state_.stack_state.emplace_back(kRef, reg, NextSpillOffset(kRef));
}
References cache_state_, v8::internal::DCHECK(), v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), v8::internal::wasm::LiftoffAssembler::CacheState::is_free(), v8::internal::kRef, v8::internal::kReturnRegister0, NextSpillOffset(), and v8::internal::wasm::LiftoffAssembler::CacheState::stack_state.
PushRegister()
void v8::internal::wasm::LiftoffAssembler::PushRegister (ValueKind kind, LiftoffRegister reg) [inline]
Definition at line 57 of file liftoff-assembler-inl.h.
                                                                       {
  DCHECK_EQ(reg_class_for(kind), reg.reg_class());
  cache_state_.inc_used(reg);
  cache_state_.stack_state.emplace_back(kind, reg, NextSpillOffset(kind));
}
References cache_state_, DCHECK_EQ, v8::internal::wasm::LiftoffAssembler::CacheState::inc_used(), NextSpillOffset(), v8::internal::wasm::LiftoffRegister::reg_class(), v8::internal::wasm::reg_class_for(), and v8::internal::wasm::LiftoffAssembler::CacheState::stack_state.
Referenced by FinishCall().
PushRegisters()
void v8::internal::wasm::LiftoffAssembler::PushRegisters (LiftoffRegList regs) [inline]
Definition at line 4743 of file liftoff-assembler-arm-inl.h.
                                                        {
  RegList core_regs = regs.GetGpList();
  if (!core_regs.is_empty()) {
    stm(db_w, sp, core_regs);
  }
  LiftoffRegList fp_regs = regs & kFpCacheRegList;
  while (!fp_regs.is_empty()) {
    LiftoffRegister reg = fp_regs.GetFirstRegSet();
    DoubleRegister first = reg.fp();
    DoubleRegister last = first;
    fp_regs.clear(reg);
    while (!fp_regs.is_empty()) {
      LiftoffRegister reg = fp_regs.GetFirstRegSet();
      int code = reg.fp().code();
      // vstm can not push more than 16 registers. We have to make sure the
      // condition is met.
      if ((code != last.code() + 1) || ((code - first.code() + 1) > 16)) break;
      last = reg.fp();
      fp_regs.clear(reg);
    }
    vstm(db_w, sp, first, last);
  }
}
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), code, v8::internal::db_w, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegList::GetFirstRegSet(), v8::internal::wasm::LiftoffRegList::GetGpList(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::kFpCacheRegList, v8::internal::Assembler::stm(), and v8::internal::Assembler::vstm().
Referenced by CheckStackShrink(), LoadOldFramePointer(), and PatchPrepareStackFrame().
PushStack()
void v8::internal::wasm::LiftoffAssembler::PushStack (ValueKind kind) [inline]
Definition at line 78 of file liftoff-assembler-inl.h.
                                               {
  cache_state_.stack_state.emplace_back(kind, NextSpillOffset(kind));
}
References cache_state_, NextSpillOffset(), and v8::internal::wasm::LiftoffAssembler::CacheState::stack_state.
RecordOolSpillSpaceSize()
void v8::internal::wasm::LiftoffAssembler::RecordOolSpillSpaceSize (int size) [inline]
Definition at line 606 of file liftoff-assembler.h.
                                         {
    if (size > ool_spill_space_size_) ool_spill_space_size_ = size;
  }
References ool_spill_space_size_, and size().
Referenced by RecordSpillsInSafepoint().
RecordSpillsInSafepoint()
void v8::internal::wasm::LiftoffAssembler::RecordSpillsInSafepoint (SafepointTableBuilder::Safepoint & safepoint, LiftoffRegList all_spills, LiftoffRegList ref_spills, int spill_offset) [inline]
Definition at line 4789 of file liftoff-assembler-arm-inl.h.
                                                 {
  LiftoffRegList fp_spills = all_spills & kFpCacheRegList;
  int spill_space_size = fp_spills.GetNumRegsSet() * kSimd128Size;
  LiftoffRegList gp_spills = all_spills & kGpCacheRegList;
  while (!gp_spills.is_empty()) {
    LiftoffRegister reg = gp_spills.GetLastRegSet();
    if (ref_spills.has(reg)) {
      safepoint.DefineTaggedStackSlot(spill_offset);
    }
    gp_spills.clear(reg);
    ++spill_offset;
    spill_space_size += kSystemPointerSize;
  }
  // Record the number of additional spill slots.
  RecordOolSpillSpaceSize(spill_space_size);
}
References v8::internal::wasm::LiftoffRegList::clear(), v8::internal::SafepointTableBuilder::Safepoint::DefineTaggedStackSlot(), v8::internal::wasm::LiftoffRegList::GetLastRegSet(), v8::internal::wasm::LiftoffRegList::GetNumRegsSet(), v8::internal::wasm::LiftoffRegList::has(), v8::internal::wasm::LiftoffRegList::is_empty(), v8::internal::wasm::kFpCacheRegList, v8::internal::wasm::kGpCacheRegList, v8::internal::kSimd128Size, v8::internal::kSystemPointerSize, and RecordOolSpillSpaceSize().
RecordUsedSpillOffset()
void v8::internal::wasm::LiftoffAssembler::RecordUsedSpillOffset (int offset) [inline]
Definition at line 602 of file liftoff-assembler.h.
                                         {
    if (offset >= max_used_spill_offset_) max_used_spill_offset_ = offset;
  }
References max_used_spill_offset_.
Referenced by FillStackSlotsWithZero(), FinishCall(), and Spill().
ResetOSRTarget()
void v8::internal::wasm::LiftoffAssembler::ResetOSRTarget () [inline]
Definition at line 789 of file liftoff-assembler-arm-inl.h.
{}
set_local_kind()
void v8::internal::wasm::LiftoffAssembler::set_local_kind (uint32_t index, ValueKind kind) [inline]
Definition at line 1619 of file liftoff-assembler.h.
                                                      {
    ValueKind* locals =
        num_locals_ <= kInlineLocalKinds ? local_kinds_ : more_local_kinds_;
    locals[index] = kind;
  }
References v8::internal::index, kInlineLocalKinds, local_kinds_, more_local_kinds_, and num_locals_.
set_num_locals()
void v8::internal::wasm::LiftoffAssembler::set_num_locals (uint32_t num_locals)
Definition at line 1193 of file liftoff-assembler.cc.
                                                         {
  DCHECK_EQ(0, num_locals_); // only call this once.
  num_locals_ = num_locals;
  if (num_locals > kInlineLocalKinds) {
    more_local_kinds_ = reinterpret_cast<ValueKind*>(
        base::Malloc(num_locals * sizeof(ValueKind)));
    DCHECK_NOT_NULL(more_local_kinds_);
  }
}
References DCHECK_EQ, DCHECK_NOT_NULL, kInlineLocalKinds, v8::base::Malloc(), more_local_kinds_, num_locals(), and num_locals_.
set_trap_on_oob_mem64()
void v8::internal::wasm::LiftoffAssembler::set_trap_on_oob_mem64 (Register index, uint64_t max_index, Label * trap_label) [inline]
Definition at line 4261 of file liftoff-assembler-arm64-inl.h.
                                                                {
  Cmp(index, max_index);
  B(trap_label, kUnsignedGreaterThanEqual);
}
References v8::internal::MacroAssembler::B(), v8::internal::MacroAssembler::Cmp(), v8::internal::index, and v8::internal::kUnsignedGreaterThanEqual.
SlotSizeForType()
int v8::internal::wasm::LiftoffAssembler::SlotSizeForType (ValueKind kind) [inline], [static]
Definition at line 626 of file liftoff-assembler-arm-inl.h.
                                                    {
  switch (kind) {
    case kS128:
      return value_kind_size(kind);
    default:
      return kStackSlotSize;
  }
}
References v8::internal::kS128, kStackSlotSize, and v8::internal::wasm::value_kind_size().
Referenced by CallCWithStackBuffer(), v8::internal::wasm::ParallelMove::ExecuteMoves(), MoveStackValue(), and NextSpillOffset().
Spill() [1/3]
void v8::internal::wasm::LiftoffAssembler::Spill (int offset, LiftoffRegister reg, ValueKind kind) [inline]
Definition at line 1658 of file liftoff-assembler-arm-inl.h.
                                                                            {
  // The {str} instruction needs a temp register when the immediate in the
  // provided MemOperand does not fit into 12 bits. This happens for large stack
  // frames. This DCHECK checks that the temp register is available when needed.
  DCHECK(UseScratchRegisterScope{this}.CanAcquire());
  DCHECK_LT(0, offset);
  RecordUsedSpillOffset(offset);
  MemOperand dst(fp, -offset);
  liftoff::Store(this, reg, dst, kind);
}
References v8::internal::UseScratchRegisterScope::CanAcquire(), v8::internal::DCHECK(), DCHECK_LT, RecordUsedSpillOffset(), and v8::internal::wasm::liftoff::Store().
Spill() [2/3]
void v8::internal::wasm::LiftoffAssembler::Spill (int offset, WasmValue value) [inline]
Definition at line 1669 of file liftoff-assembler-arm-inl.h.
                                                        {
  RecordUsedSpillOffset(offset);
  MemOperand dst = liftoff::GetStackSlot(offset);
  UseScratchRegisterScope assembler_temps(this);
  liftoff::CacheStatePreservingTempRegisters liftoff_temps{this};
  Register src = no_reg;
  // The scratch register will be required by str if multiple instructions
  // are required to encode the offset, and so we cannot use it in that case.
  if (!ImmediateFitsAddrMode2Instruction(dst.offset())) {
    src = liftoff_temps.Acquire();
  } else {
    src = assembler_temps.Acquire();
  }
  switch (value.type().kind()) {
    case kI32:
      mov(src, Operand(value.to_i32()));
      str(src, dst);
      break;
    case kI64: {
      int32_t low_word = value.to_i64();
      mov(src, Operand(low_word));
      str(src, liftoff::GetHalfStackSlot(offset, kLowWord));
      int32_t high_word = value.to_i64() >> 32;
      mov(src, Operand(high_word));
      str(src, liftoff::GetHalfStackSlot(offset, kHighWord));
      break;
    }
    default:
      // We do not track f32 and f64 constants, hence they are unreachable.
      UNREACHABLE();
  }
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::wasm::liftoff::GetHalfStackSlot(), v8::internal::wasm::liftoff::GetStackSlot(), v8::internal::Assembler::ImmediateFitsAddrMode2Instruction(), v8::internal::wasm::kHighWord, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::kLowWord, v8::internal::MacroAssembler::mov(), v8::internal::no_reg, v8::internal::MemOperand::offset(), RecordUsedSpillOffset(), v8::internal::Assembler::str(), v8::internal::UNREACHABLE(), and v8::internal::value.
Spill() [3/3]
void v8::internal::wasm::LiftoffAssembler::Spill (VarState * slot)
Definition at line 633 of file liftoff-assembler.cc.
                                           {
  switch (slot->loc()) {
    case VarState::kStack:
      return;
    case VarState::kRegister:
      Spill(slot->offset(), slot->reg(), slot->kind());
      cache_state_.dec_used(slot->reg());
      break;
    case VarState::kIntConst:
      Spill(slot->offset(), slot->constant());
      break;
  }
  slot->MakeStack();
}
References cache_state_, v8::internal::wasm::LiftoffVarState::constant(), v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::LiftoffVarState::kIntConst, v8::internal::wasm::LiftoffVarState::kRegister, v8::internal::wasm::LiftoffVarState::kStack, v8::internal::wasm::LiftoffVarState::loc(), v8::internal::wasm::LiftoffVarState::MakeStack(), v8::internal::wasm::LiftoffVarState::offset(), and v8::internal::wasm::LiftoffVarState::reg().
Referenced by v8::internal::wasm::ParallelMove::ExecuteMoves(), PrepareCall(), PrepareForBranch(), SpillAllRegisters(), SpillLocals(), SpillLoopArgs(), SpillRegister(), and v8::internal::wasm::ParallelMove::TransferToStack().
SpillAdjacentFpRegisters()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::SpillAdjacentFpRegisters (LiftoffRegList pinned) [private]
Definition at line 1119 of file liftoff-assembler.cc.
                           {
  // We end up in this call only when:
  // [1] kNeedS128RegPair, and
  // [2] there are no pair of adjacent FP registers that are free
  CHECK(kNeedS128RegPair);
  DCHECK(!kFpCacheRegList.MaskOut(pinned)
              .MaskOut(cache_state_.used_registers)
              .HasAdjacentFpRegsSet());
  // Special logic, if the top fp register is even, we might hit a case of an
  // invalid register in case 2.
  LiftoffRegister last_fp = kFpCacheRegList.GetLastRegSet();
  if (last_fp.fp().code() % 2 == 0) {
    pinned.set(last_fp);
  }
  // If half of an adjacent pair is pinned, consider the whole pair pinned.
  // Otherwise the code below would potentially spill the pinned register
  // (after first spilling the unpinned half of the pair).
  pinned = pinned.SpreadSetBitsToAdjacentFpRegs();
  // We can try to optimize the spilling here:
  // 1. Try to get a free fp register, either:
  // a. This register is already free, or
  // b. it had to be spilled.
  // 2. If 1a, the adjacent register is used (invariant [2]), spill it.
  // 3. If 1b, check the adjacent register:
  // a. If free, done!
  // b. If used, spill it.
  // We spill one register in 2 and 3a, and two registers in 3b.
  LiftoffRegister first_reg = GetUnusedRegister(kFpReg, pinned);
  LiftoffRegister second_reg = first_reg, low_reg = first_reg;
  if (first_reg.fp().code() % 2 == 0) {
    second_reg =
        LiftoffRegister::from_liftoff_code(first_reg.liftoff_code() + 1);
  } else {
    second_reg =
        LiftoffRegister::from_liftoff_code(first_reg.liftoff_code() - 1);
    low_reg = second_reg;
  }
  if (cache_state_.is_used(second_reg)) {
    SpillRegister(second_reg);
  }
  return low_reg;
}
References cache_state_, CHECK, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::LiftoffRegister::from_liftoff_code(), v8::internal::wasm::LiftoffRegList::GetLastRegSet(), GetUnusedRegister(), v8::internal::wasm::LiftoffRegList::HasAdjacentFpRegsSet(), v8::internal::wasm::LiftoffAssembler::CacheState::is_used(), v8::internal::wasm::kFpCacheRegList, v8::internal::wasm::kFpReg, v8::internal::wasm::kNeedS128RegPair, v8::internal::wasm::LiftoffRegister::liftoff_code(), v8::internal::wasm::LiftoffRegList::MaskOut(), v8::internal::wasm::LiftoffRegList::set(), SpillRegister(), v8::internal::wasm::LiftoffRegList::SpreadSetBitsToAdjacentFpRegs(), and v8::internal::wasm::LiftoffAssembler::CacheState::used_registers.
Referenced by GetUnusedRegister().
SpillAllRegisters()
void v8::internal::wasm::LiftoffAssembler::SpillAllRegisters ()
Definition at line 655 of file liftoff-assembler.cc.
                                         {
  for (VarState& slot : cache_state_.stack_state) {
    if (!slot.is_reg()) continue;
    Spill(slot.offset(), slot.reg(), slot.kind());
    slot.MakeStack();
  }
  cache_state_.ClearAllCacheRegisters();
  cache_state_.reset_used_registers();
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::ClearAllCacheRegisters(), v8::internal::wasm::LiftoffVarState::is_reg(), v8::internal::wasm::LiftoffVarState::kind(), v8::internal::wasm::LiftoffVarState::MakeStack(), v8::internal::wasm::LiftoffVarState::offset(), v8::internal::wasm::LiftoffVarState::reg(), v8::internal::wasm::LiftoffAssembler::CacheState::reset_used_registers(), Spill(), and v8::internal::wasm::LiftoffAssembler::CacheState::stack_state.
Referenced by PrepareBuiltinCall().
SpillInstanceData()
void v8::internal::wasm::LiftoffAssembler::SpillInstanceData (Register instance) [inline]
Definition at line 785 of file liftoff-assembler-arm-inl.h.
                                                          {
  str(instance, liftoff::GetInstanceDataOperand());
}
References v8::internal::wasm::liftoff::GetInstanceDataOperand(), and v8::internal::Assembler::str().
SpillLocals()
void v8::internal::wasm::LiftoffAssembler::SpillLocals ()
Definition at line 648 of file liftoff-assembler.cc.
                                   {
  for (VarState& local_slot :
       base::VectorOf(cache_state_.stack_state.data(), num_locals_)) {
    Spill(&local_slot);
  }
}
References cache_state_, num_locals_, Spill(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and v8::base::VectorOf().
SpillLoopArgs()
void v8::internal::wasm::LiftoffAssembler::SpillLoopArgs (int num)
Definition at line 427 of file liftoff-assembler.cc.
                                            {
  for (VarState& slot :
       base::VectorOf(cache_state_.stack_state.end() - num, num)) {
    Spill(&slot);
  }
}
References cache_state_, Spill(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and v8::base::VectorOf().
SpillOneRegister()
LiftoffRegister v8::internal::wasm::LiftoffAssembler::SpillOneRegister (LiftoffRegList candidates) [private]
Definition at line 1106 of file liftoff-assembler.cc.
                                                                            {
  // Before spilling a regular stack slot, try to drop a "volatile" register
  // (used for caching the memory start or the instance itself). Those can be
  // reloaded without requiring a spill here.
  if (cache_state_.has_volatile_register(candidates)) {
    return cache_state_.take_volatile_register(candidates);
  }
  LiftoffRegister spilled_reg = cache_state_.GetNextSpillReg(candidates);
  SpillRegister(spilled_reg);
  return spilled_reg;
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::GetNextSpillReg(), v8::internal::wasm::LiftoffAssembler::CacheState::has_volatile_register(), SpillRegister(), and v8::internal::wasm::LiftoffAssembler::CacheState::take_volatile_register().
Referenced by GetUnusedRegister().
SpillRegister()
void v8::internal::wasm::LiftoffAssembler::SpillRegister (LiftoffRegister reg)
Definition at line 1169 of file liftoff-assembler.cc.
                                                        {
  DCHECK(!cache_state_.frozen);
  int remaining_uses = cache_state_.get_use_count(reg);
  DCHECK_LT(0, remaining_uses);
  for (uint32_t idx = cache_state_.stack_height() - 1;; --idx) {
    DCHECK_GT(cache_state_.stack_height(), idx);
    auto* slot = &cache_state_.stack_state[idx];
    if (!slot->is_reg() || !slot->reg().overlaps(reg)) continue;
    if (slot->reg().is_pair()) {
      // Make sure to decrement *both* registers in a pair, because the
      // {clear_used} call below only clears one of them.
      cache_state_.dec_used(slot->reg().low());
      cache_state_.dec_used(slot->reg().high());
      cache_state_.last_spilled_regs.set(slot->reg().low());
      cache_state_.last_spilled_regs.set(slot->reg().high());
    }
    Spill(slot->offset(), slot->reg(), slot->kind());
    slot->MakeStack();
    if (--remaining_uses == 0) break;
  }
  cache_state_.clear_used(reg);
  cache_state_.last_spilled_regs.set(reg);
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::clear_used(), v8::internal::DCHECK(), DCHECK_GT, DCHECK_LT, v8::internal::wasm::LiftoffAssembler::CacheState::dec_used(), v8::internal::wasm::LiftoffAssembler::CacheState::get_use_count(), v8::internal::wasm::LiftoffAssembler::CacheState::last_spilled_regs, v8::internal::wasm::LiftoffRegList::set(), Spill(), v8::internal::wasm::LiftoffAssembler::CacheState::stack_height(), and v8::internal::wasm::LiftoffAssembler::CacheState::stack_state.
Referenced by AtomicCompareExchange(), ClearRegister(), PopToFixedRegister(), SpillAdjacentFpRegisters(), SpillOneRegister(), and SpillRegisters().
SpillRegisters()
template<typename... Regs>
void v8::internal::wasm::LiftoffAssembler::SpillRegisters (Regs... regs) [inline]
Definition at line 586 of file liftoff-assembler.h.
                                    {
    for (LiftoffRegister r : {LiftoffRegister(regs)...}) {
      if (cache_state_.is_free(r)) continue;
      if (r.is_gp() && cache_state_.cached_instance_data == r.gp()) {
        cache_state_.ClearCachedInstanceRegister();
      } else if (r.is_gp() && cache_state_.cached_mem_start == r.gp()) {
        V8_ASSUME(cache_state_.cached_mem_index >= 0);
        cache_state_.ClearCachedMemStartRegister();
      } else {
        SpillRegister(r);
      }
    }
  }
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::cached_instance_data, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_index, v8::internal::wasm::LiftoffAssembler::CacheState::cached_mem_start, v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedInstanceRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::ClearCachedMemStartRegister(), v8::internal::wasm::LiftoffAssembler::CacheState::is_free(), SpillRegister(), and V8_ASSUME.
Referenced by AtomicLoad(), v8::internal::wasm::liftoff::EmitInt32DivOrRem(), and v8::internal::wasm::liftoff::EmitIntDivOrRem().
StackCheck()
void v8::internal::wasm::LiftoffAssembler::StackCheck (Label * ool_code) [inline]
Definition at line 4730 of file liftoff-assembler-arm-inl.h.
                                                 {
  UseScratchRegisterScope temps(this);
  Register limit_address = temps.Acquire();
  LoadStackLimit(limit_address, StackLimitKind::kInterruptStackLimit);
  cmp(sp, limit_address);
  b(ool_code, ls);
}
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::Assembler::b(), v8::internal::Assembler::cmp(), v8::internal::kInterruptStackLimit, v8::internal::MacroAssembler::LoadStackLimit(), and v8::internal::ls.
StaticStackFrameSize()
constexpr int v8::internal::wasm::LiftoffAssembler::StaticStackFrameSize () [inline], [static], [constexpr]
Definition at line 622 of file liftoff-assembler-arm-inl.h.
                                                     {
  return WasmLiftoffFrameConstants::kFeedbackVectorOffset;
}
References v8::internal::WasmLiftoffFrameConstants::kFeedbackVectorOffset.
Referenced by DropExceptionValueAtOffset(), MergeIntoNewState(), and TopSpillOffset().
Store()
void v8::internal::wasm::LiftoffAssembler::Store (Register dst_addr, Register offset_reg, uintptr_t offset_imm, LiftoffRegister src, StoreType type, LiftoffRegList pinned, uint32_t * protected_store_pc = nullptr, bool is_store_mem = false, bool i64_offset = false) [inline]
Definition at line 982 of file liftoff-assembler-arm-inl.h.
                                             {
  // Offsets >=2GB are statically OOB on 32-bit systems.
  DCHECK_LE(offset_imm, std::numeric_limits<int32_t>::max());
  UseScratchRegisterScope temps{this};
  if (type.value() == StoreType::kF64Store) {
    Register actual_dst_addr = liftoff::CalculateActualAddress(
        this, &temps, dst_addr, offset_reg, offset_imm);
    // Armv6 is not supported so Neon can be used to avoid alignment issues.
    CpuFeatureScope scope(this, NEON);
    vst1(Neon64, NeonListOperand(src.fp()), NeonMemOperand(actual_dst_addr));
  } else if (type.value() == StoreType::kS128Store) {
    Register actual_dst_addr = liftoff::CalculateActualAddress(
        this, &temps, dst_addr, offset_reg, offset_imm);
    // Armv6 is not supported so Neon can be used to avoid alignment issues.
    CpuFeatureScope scope(this, NEON);
    vst1(Neon8, NeonListOperand(src.low_fp(), 2),
         NeonMemOperand(actual_dst_addr));
  } else if (type.value() == StoreType::kF32Store) {
    // TODO(arm): Use vst1 for f32 when implemented in simulator as used for
    // f64. It supports unaligned access.
    Register actual_dst_addr = liftoff::CalculateActualAddress(
        this, &temps, dst_addr, offset_reg, offset_imm);
    liftoff::CacheStatePreservingTempRegisters liftoff_temps{this, pinned};
    Register scratch =
        temps.CanAcquire() ? temps.Acquire() : liftoff_temps.Acquire();
    vmov(scratch, liftoff::GetFloatRegister(src.fp()));
    str(scratch, MemOperand(actual_dst_addr));
  } else {
    MemOperand dst_op =
        liftoff::GetMemOp(this, &temps, dst_addr, offset_reg, offset_imm);
    if (protected_store_pc) *protected_store_pc = pc_offset();
    switch (type.value()) {
      case StoreType::kI64Store8:
        src = src.low();
        [[fallthrough]];
      case StoreType::kI32Store8:
        strb(src.gp(), dst_op);
        break;
      case StoreType::kI64Store16:
        src = src.low();
        [[fallthrough]];
      case StoreType::kI32Store16:
        strh(src.gp(), dst_op);
        break;
      case StoreType::kI64Store32:
        src = src.low();
        [[fallthrough]];
      case StoreType::kI32Store:
        str(src.gp(), dst_op);
        break;
      case StoreType::kI64Store:
        str(src.low_gp(), dst_op);
        // GetMemOp may use a scratch register as the offset register, in which
        // case, calling GetMemOp again will fail due to the assembler having
        // ran out of scratch registers.
        if (temps.CanAcquire()) {
          dst_op = liftoff::GetMemOp(this, &temps, dst_addr, offset_reg,
                                     offset_imm + kSystemPointerSize);
        } else {
          add(dst_op.rm(), dst_op.rm(), Operand(kSystemPointerSize));
        }
        str(src.high_gp(), dst_op);
        break;
      default:
        UNREACHABLE();
    }
  }
}
References v8::internal::Assembler::add(), v8::internal::wasm::liftoff::CalculateActualAddress(), DCHECK_LE, v8::internal::wasm::LiftoffRegister::fp(), v8::internal::wasm::liftoff::GetFloatRegister(), v8::internal::wasm::liftoff::GetMemOp(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::kSystemPointerSize, v8::internal::wasm::LiftoffRegister::low(), v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Neon64, v8::internal::Neon8, v8::internal::AssemblerBase::pc_offset(), v8::internal::MemOperand::rm(), v8::internal::Assembler::str(), v8::internal::Assembler::strb(), v8::internal::Assembler::strh(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), v8::internal::Assembler::vmov(), and v8::internal::Assembler::vst1().
Referenced by AtomicStore().
StoreCallerFrameSlot()
void v8::internal::wasm::LiftoffAssembler::StoreCallerFrameSlot (LiftoffRegister src, uint32_t caller_slot_idx, ValueKind kind, Register frame_pointer) [inline]
Definition at line 1602 of file liftoff-assembler-arm-inl.h.
                                                                    {
  MemOperand dst(frame_pointer, (caller_slot_idx + 1) * kSystemPointerSize);
  liftoff::Store(this, src, dst, kind);
}
References v8::internal::kSystemPointerSize, and v8::internal::wasm::liftoff::Store().
Referenced by MoveToReturnLocationsMultiReturn().
StoreLane()
void v8::internal::wasm::LiftoffAssembler::StoreLane (Register dst, Register offset, uintptr_t offset_imm, LiftoffRegister src, StoreType type, uint8_t lane, uint32_t * protected_store_pc, bool i64_offset) [inline]
Definition at line 2766 of file liftoff-assembler-arm-inl.h.
                                         {
  UseScratchRegisterScope temps(this);
  Register actual_dst_addr =
      liftoff::CalculateActualAddress(this, &temps, dst, offset, offset_imm);
  *protected_store_pc = pc_offset();
  LoadStoreLaneParams store_params(type.mem_rep(), laneidx);
  NeonListOperand src_op =
      NeonListOperand(store_params.low_op ? src.low_fp() : src.high_fp());
  MacroAssembler::StoreLane(store_params.sz, src_op, store_params.laneidx,
                            NeonMemOperand(actual_dst_addr));
}
References v8::internal::wasm::liftoff::CalculateActualAddress(), v8::internal::wasm::LiftoffRegister::high_fp(), v8::internal::LoadStoreLaneParams::laneidx, v8::internal::wasm::LiftoffRegister::low_fp(), v8::internal::LoadStoreLaneParams::low_op, v8::internal::AssemblerBase::pc_offset(), v8::internal::MacroAssembler::StoreLane(), v8::internal::LoadStoreLaneParams::sz, and v8::internal::tracing::type.
StoreTaggedPointer()
void v8::internal::wasm::LiftoffAssembler::StoreTaggedPointer (Register dst_addr, Register offset_reg, int32_t offset_imm, Register src, LiftoffRegList pinned, uint32_t * protected_store_pc = nullptr, SkipWriteBarrier skip_write_barrier = kNoSkipWriteBarrier) [inline]
Definition at line 927 of file liftoff-assembler-arm-inl.h.
                                                                               {
  static_assert(kTaggedSize == kInt32Size);
  UseScratchRegisterScope temps{this};
  Register actual_offset_reg = offset_reg;
  if (offset_reg != no_reg && offset_imm != 0) {
    if (cache_state()->is_used(LiftoffRegister(offset_reg))) {
      // The code below only needs a scratch register if the {MemOperand} given
      // to {str} has an offset outside the uint12 range. After doing the
      // addition below we will not pass an immediate offset to {str} though, so
      // we can use the scratch register here.
      actual_offset_reg = temps.Acquire();
    }
    add(actual_offset_reg, offset_reg, Operand(offset_imm));
  }
  MemOperand dst_op = actual_offset_reg == no_reg
                          ? MemOperand(dst_addr, offset_imm)
                          : MemOperand(dst_addr, actual_offset_reg);
  if (protected_store_pc) *protected_store_pc = pc_offset();
  str(src, dst_op);
  if (skip_write_barrier || v8_flags.disable_write_barriers) return;
  // The write barrier.
  Label exit;
  CheckPageFlag(dst_addr, MemoryChunk::kPointersFromHereAreInterestingMask,
                kZero, &exit);
  JumpIfSmi(src, &exit);
  CheckPageFlag(src, MemoryChunk::kPointersToHereAreInterestingMask, eq, &exit);
  CallRecordWriteStubSaveRegisters(
      dst_addr,
      actual_offset_reg == no_reg ? Operand(offset_imm)
                                  : Operand(actual_offset_reg),
      SaveFPRegsMode::kSave, StubCallMode::kCallWasmRuntimeStub);
  bind(&exit);
}
References v8::internal::Assembler::add(), v8::internal::Assembler::bind(), cache_state(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), v8::internal::MacroAssembler::CheckPageFlag(), v8::internal::eq, v8::internal::MacroAssembler::JumpIfSmi(), v8::internal::kInt32Size, v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, v8::internal::MemoryChunk::kPointersToHereAreInterestingMask, v8::internal::kSave, v8::internal::kTaggedSize, v8::internal::kZero, v8::internal::no_reg, v8::internal::AssemblerBase::pc_offset(), v8::internal::Assembler::str(), and v8::internal::v8_flags.
supports_f16_mem_access()
bool v8::internal::wasm::LiftoffAssembler::supports_f16_mem_access () [inline]
Definition at line 4718 of file liftoff-assembler-arm-inl.h.
{ return false; }
TailCallIndirect()
void v8::internal::wasm::LiftoffAssembler::TailCallIndirect (compiler::CallDescriptor * call_descriptor, Register target) [inline]
Definition at line 4943 of file liftoff-assembler-arm-inl.h.
                                                              {
  DCHECK(target != no_reg);
  CallWasmCodePointer(target, CallJumpMode::kTailCall);
}
References v8::internal::DCHECK(), v8::internal::kTailCall, and v8::internal::no_reg.
TailCallNativeWasmCode()
void v8::internal::wasm::LiftoffAssembler::TailCallNativeWasmCode (Address addr) [inline]
Definition at line 4932 of file liftoff-assembler-arm-inl.h.
                                                          {
  Jump(addr, RelocInfo::WASM_CALL);
}
References v8::internal::MacroAssembler::Jump(), and v8::internal::RelocInfo::WASM_CALL.
TopSpillOffset()
int v8::internal::wasm::LiftoffAssembler::TopSpillOffset () const [inline]
Definition at line 51 of file liftoff-assembler-inl.h.
                                           {
  return cache_state_.stack_state.empty()
             ? StaticStackFrameSize()
             : cache_state_.stack_state.back().offset();
}
References cache_state_, v8::internal::wasm::LiftoffAssembler::CacheState::stack_state, and StaticStackFrameSize().
Referenced by FinishCall(), and NextSpillOffset().
zone()
Zone* v8::internal::wasm::LiftoffAssembler::zone () const [inline]
Definition at line 390 of file liftoff-assembler.h.
{ return cache_state_.stack_state.get_allocator().zone(); }
References cache_state_, and v8::internal::wasm::LiftoffAssembler::CacheState::stack_state.
Referenced by MergeIntoNewState(), and MoveToReturnLocationsMultiReturn().
Member Data Documentation
union { ... } [private]
bailout_detail_
const char* v8::internal::wasm::LiftoffAssembler::bailout_detail_ = nullptr [private]
Definition at line 1658 of file liftoff-assembler.h.
Referenced by bailout(), and bailout_detail().
bailout_reason_
LiftoffBailoutReason v8::internal::wasm::LiftoffAssembler::bailout_reason_ = kSuccess [private]
Definition at line 1657 of file liftoff-assembler.h.
Referenced by bailout(), bailout_reason(), and did_bailout().
cache_state_
CacheState v8::internal::wasm::LiftoffAssembler::cache_state_ [private]
Definition at line 1652 of file liftoff-assembler.h.
Referenced by cache_state(), CheckTierUp(), DropExceptionValueAtOffset(), DropValues(), GetNumUses(), GetUnusedRegister(), MergeFullStackWith(), MergeIntoNewState(), MergeStackWith(), MoveToReturnLocations(), MoveToReturnLocationsMultiReturn(), PeekToRegister(), PopToFixedRegister(), PopVarState(), PrepareBuiltinCall(), PrepareCall(), PrepareForBranch(), PushConstant(), PushException(), PushRegister(), PushStack(), Spill(), SpillAdjacentFpRegisters(), SpillAllRegisters(), SpillLocals(), SpillLoopArgs(), SpillOneRegister(), SpillRegister(), SpillRegisters(), TopSpillOffset(), and zone().
kInlineLocalKinds
constexpr uint32_t v8::internal::wasm::LiftoffAssembler::kInlineLocalKinds = 16 [static], [constexpr], [private]
Definition at line 1645 of file liftoff-assembler.h.
Referenced by local_kind(), set_local_kind(), set_num_locals(), and ~LiftoffAssembler().
kIntPtrKind
constexpr ValueKind v8::internal::wasm::LiftoffAssembler::kIntPtrKind [static], [constexpr]
Initial value:
=
      kSystemPointerSize == kInt32Size ? kI32 : kI64
Definition at line 104 of file liftoff-assembler.h.
Referenced by ClearRegister(), MergeStackWith(), and PrepareCall().
kSmiKind
constexpr ValueKind v8::internal::wasm::LiftoffAssembler::kSmiKind = kTaggedSize == kInt32Size ? kI32 : kI64 [static], [constexpr]
Definition at line 107 of file liftoff-assembler.h.
kStackSlotSize
constexpr int v8::internal::wasm::LiftoffAssembler::kStackSlotSize = 8 [static], [constexpr]
Definition at line 102 of file liftoff-assembler.h.
Referenced by v8::internal::wasm::liftoff::GetHalfStackSlot(), and SlotSizeForType().
local_kinds_
ValueKind v8::internal::wasm::LiftoffAssembler::local_kinds_[kInlineLocalKinds]
Definition at line 1647 of file liftoff-assembler.h.
Referenced by local_kind(), and set_local_kind().
max_used_spill_offset_
int v8::internal::wasm::LiftoffAssembler::max_used_spill_offset_ = StaticStackFrameSize() [private]
Definition at line 1654 of file liftoff-assembler.h.
Referenced by GetTotalFrameSize(), GetTotalFrameSlotCountForGC(), and RecordUsedSpillOffset().
more_local_kinds_
ValueKind* v8::internal::wasm::LiftoffAssembler::more_local_kinds_
Definition at line 1648 of file liftoff-assembler.h.
Referenced by local_kind(), set_local_kind(), set_num_locals(), and ~LiftoffAssembler().
num_locals_
uint32_t v8::internal::wasm::LiftoffAssembler::num_locals_ = 0 [private]
Definition at line 1644 of file liftoff-assembler.h.
Referenced by local_kind(), num_locals(), set_local_kind(), set_num_locals(), SpillLocals(), and ~LiftoffAssembler().
ool_spill_space_size_
int v8::internal::wasm::LiftoffAssembler::ool_spill_space_size_ = 0 [private]
Definition at line 1656 of file liftoff-assembler.h.
Referenced by GetTotalFrameSlotCountForGC(), OolSpillCount(), and RecordOolSpillSpaceSize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler.h
/mnt/V8SourceCode/src/wasm/baseline/arm/liftoff-assembler-arm-inl.h
/mnt/V8SourceCode/src/wasm/baseline/arm64/liftoff-assembler-arm64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/ia32/liftoff-assembler-ia32-inl.h
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler-inl.h
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler.cc
/mnt/V8SourceCode/src/wasm/baseline/loong64/liftoff-assembler-loong64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/mips64/liftoff-assembler-mips64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/ppc/liftoff-assembler-ppc-inl.h
/mnt/V8SourceCode/src/wasm/baseline/riscv/liftoff-assembler-riscv-inl.h
/mnt/V8SourceCode/src/wasm/baseline/riscv/liftoff-assembler-riscv32-inl.h
/mnt/V8SourceCode/src/wasm/baseline/riscv/liftoff-assembler-riscv64-inl.h
/mnt/V8SourceCode/src/wasm/baseline/s390/liftoff-assembler-s390-inl.h
/mnt/V8SourceCode/src/wasm/baseline/x64/liftoff-assembler-x64-inl.h