v8::internal::RegExpCapture Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpCapture (int index)
DECL_BOILERPLATE (Capture)
bool IsAnchoredAtStart () override
bool IsAnchoredAtEnd () override
Interval CaptureRegisters () override
int min_match () override
int max_match () override
RegExpTree * body ()
void set_body (RegExpTree *body)
int index () const
const ZoneVector< base::uc16 > * name () const
void set_name (const ZoneVector< base::uc16 > *name)
Static Public Member Functions
static RegExpNode * ToNode (RegExpTree *body, int index, RegExpCompiler *compiler, RegExpNode *on_success)
static int StartRegister (int index)
static int EndRegister (int index)
Private Attributes
RegExpTree * body_ = nullptr
int index_
int min_match_ = 0
int max_match_ = 0
const ZoneVector< base::uc16 > * name_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 597 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpCapture()
v8::internal::RegExpCapture::RegExpCapture (int index) [inline], [explicit]
Definition at line 599 of file regexp-ast.h.
      : body_(nullptr),
        index_(index),
        min_match_(0),
        max_match_(0),
        name_(nullptr) {}
Member Function Documentation
body()
RegExpTree* v8::internal::RegExpCapture::body () [inline]
Definition at line 615 of file regexp-ast.h.
{ return body_; }
References body_.
Referenced by CaptureRegisters(), IsAnchoredAtEnd(), IsAnchoredAtStart(), set_body(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitCapture(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitCapture(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitCapture().
CaptureRegisters()
Interval v8::internal::RegExpCapture::CaptureRegisters () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 58 of file regexp-ast.cc.
                                         {
  Interval self(StartRegister(index()), EndRegister(index()));
  return self.Union(body()->CaptureRegisters());
}
References body(), v8::internal::RegExpTree::CaptureRegisters(), EndRegister(), index(), StartRegister(), and v8::internal::Interval::Union().
DECL_BOILERPLATE()
v8::internal::RegExpCapture::DECL_BOILERPLATE (Capture)
EndRegister()
static int v8::internal::RegExpCapture::EndRegister (int index) [inline], [static]
Definition at line 625 of file regexp-ast.h.
{ return index * 2 + 1; }
References index().
Referenced by CaptureRegisters(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitCapture().
index()
int v8::internal::RegExpCapture::index () const [inline]
Definition at line 621 of file regexp-ast.h.
{ return index_; }
References index_.
Referenced by CaptureRegisters(), EndRegister(), v8::internal::anonymous_namespace{regexp.cc}::RegExpCaptureIndexLess::operator()(), StartRegister(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitCapture(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitCapture().
IsAnchoredAtEnd()
bool v8::internal::RegExpCapture::IsAnchoredAtEnd () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 135 of file regexp-ast.cc.
{ return body()->IsAnchoredAtEnd(); }
References body(), and v8::internal::RegExpTree::IsAnchoredAtEnd().
IsAnchoredAtStart()
bool v8::internal::RegExpCapture::IsAnchoredAtStart () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 132 of file regexp-ast.cc.
{ return body()->IsAnchoredAtStart(); }
References body(), and v8::internal::RegExpTree::IsAnchoredAtStart().
max_match()
int v8::internal::RegExpCapture::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 614 of file regexp-ast.h.
{ return max_match_; }
References max_match_.
min_match()
int v8::internal::RegExpCapture::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 613 of file regexp-ast.h.
{ return min_match_; }
References min_match_.
name()
const ZoneVector<base::uc16>* v8::internal::RegExpCapture::name () const [inline]
Definition at line 622 of file regexp-ast.h.
{ return name_; }
References name_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::RegExpCaptureNameLess::operator()(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences(), and set_name().
set_body()
void v8::internal::RegExpCapture::set_body (RegExpTree * body) [inline]
Definition at line 616 of file regexp-ast.h.
                                  {
    body_ = body;
    min_match_ = body->min_match();
    max_match_ = body->max_match();
  }
References body(), body_, v8::internal::RegExpTree::max_match(), max_match_, v8::internal::RegExpTree::min_match(), and min_match_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction().
set_name()
void v8::internal::RegExpCapture::set_name (const ZoneVector< base::uc16 > * name) [inline]
Definition at line 623 of file regexp-ast.h.
{ name_ = name; }
References name(), and name_.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::CreateNamedCaptureAtIndex(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::PatchNamedBackReferences().
StartRegister()
static int v8::internal::RegExpCapture::StartRegister (int index) [inline], [static]
Definition at line 624 of file regexp-ast.h.
{ return index * 2; }
References index().
Referenced by CaptureRegisters(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitCapture().
ToNode()
RegExpNode * v8::internal::RegExpCapture::ToNode (RegExpTree * body, int index, RegExpCompiler * compiler, RegExpNode * on_success) [static]
Definition at line 1276 of file regexp-compiler-tonode.cc.
                                                          {
  return ToNode(body(), index(), compiler, on_success);
}
References v8::internal::RegExpLookaround::body(), v8::internal::RegExpLookaround::index(), and v8::internal::RegExpTree::ToNode().
Referenced by v8::internal::RegExpCompiler::PreprocessRegExp().
Member Data Documentation
body_
RegExpTree* v8::internal::RegExpCapture::body_ = nullptr [private]
Definition at line 628 of file regexp-ast.h.
Referenced by body(), and set_body().
index_
int v8::internal::RegExpCapture::index_ [private]
Definition at line 629 of file regexp-ast.h.
Referenced by index().
max_match_
int v8::internal::RegExpCapture::max_match_ = 0 [private]
Definition at line 631 of file regexp-ast.h.
Referenced by max_match(), and set_body().
min_match_
int v8::internal::RegExpCapture::min_match_ = 0 [private]
Definition at line 630 of file regexp-ast.h.
Referenced by min_match(), and set_body().
name_
const ZoneVector<base::uc16>* v8::internal::RegExpCapture::name_ = nullptr [private]
Definition at line 632 of file regexp-ast.h.
Referenced by name(), and set_name().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc