v8::internal::wasm::WasmModuleBuilder::WasmElemSegment Class Reference
#include <wasm-module-builder.h>
Classes
struct Entry
Public Types
enum FunctionIndexingMode { kRelativeToImports
, kRelativeToDeclaredFunctions
 }
enum Status { kStatusActive
, kStatusPassive
, kStatusDeclarative
 }
Public Member Functions
WasmElemSegment (Zone *zone, ValueType type, uint32_t table_index, WasmInitExpr offset)
WasmElemSegment (Zone *zone, ValueType type, bool declarative, WasmInitExpr offset)
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (WasmElemSegment)
Public Attributes
ValueType type
uint32_t table_index
WasmInitExpr offset
FunctionIndexingMode indexing_mode = kRelativeToImports
ZoneVector< Entry > entries
Status status
Private Member Functions
bool IsValidOffsetKind (WasmInitExpr::Operator kind)
Detailed Description
Definition at line 265 of file wasm-module-builder.h.
Member Enumeration Documentation
FunctionIndexingMode
enum v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::FunctionIndexingMode
Enumerator
kRelativeToImports
kRelativeToDeclaredFunctions
Definition at line 269 of file wasm-module-builder.h.
                              {
      kRelativeToImports,
      kRelativeToDeclaredFunctions
    };
Status
enum v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Status
Enumerator
kStatusActive
kStatusPassive
kStatusDeclarative
Definition at line 273 of file wasm-module-builder.h.
                {
      kStatusActive, // copied automatically during instantiation.
      kStatusPassive, // copied explicitly after instantiation.
      kStatusDeclarative // purely declarative and never copied.
    };
Constructor & Destructor Documentation
WasmElemSegment() [1/2]
v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::WasmElemSegment (Zone * zone, ValueType type, uint32_t table_index, WasmInitExpr offset) [inline]
Definition at line 286 of file wasm-module-builder.h.
        : type(type),
          table_index(table_index),
          offset(offset),
          entries(zone),
          status(kStatusActive) {
      DCHECK(IsValidOffsetKind(offset.kind()));
    }
References v8::internal::DCHECK(), and v8::internal::wasm::WasmInitExpr::kind().
WasmElemSegment() [2/2]
v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::WasmElemSegment (Zone * zone, ValueType type, bool declarative, WasmInitExpr offset) [inline]
Definition at line 298 of file wasm-module-builder.h.
        : type(type),
          table_index(0),
          offset(offset),
          entries(zone),
          status(declarative ? kStatusDeclarative : kStatusPassive) {
      DCHECK(IsValidOffsetKind(offset.kind()));
    }
References v8::internal::DCHECK(), and v8::internal::wasm::WasmInitExpr::kind().
Member Function Documentation
IsValidOffsetKind()
bool v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::IsValidOffsetKind (WasmInitExpr::Operator kind) [inline], [private]
Definition at line 321 of file wasm-module-builder.h.
                                                      {
      return kind == WasmInitExpr::kI32Const ||
             kind == WasmInitExpr::kI64Const ||
             kind == WasmInitExpr::kGlobalGet ||
             kind == WasmInitExpr::kRefNullConst;
    }
References v8::internal::wasm::WasmInitExpr::kGlobalGet, v8::internal::wasm::WasmInitExpr::kI32Const, v8::internal::wasm::WasmInitExpr::kI64Const, and v8::internal::wasm::WasmInitExpr::kRefNullConst.
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (WasmElemSegment)
Member Data Documentation
entries
ZoneVector<Entry> v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::entries
Definition at line 314 of file wasm-module-builder.h.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomTables(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), and v8::internal::wasm::WasmModuleBuilder::SetIndirectFunction().
indexing_mode
FunctionIndexingMode v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::indexing_mode = kRelativeToImports
Definition at line 313 of file wasm-module-builder.h.
Referenced by v8::internal::wasm::WasmModuleBuilder::SetIndirectFunction().
offset
WasmInitExpr v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::offset
Definition at line 312 of file wasm-module-builder.h.
status
Status v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::status
Definition at line 315 of file wasm-module-builder.h.
table_index
uint32_t v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::table_index
Definition at line 311 of file wasm-module-builder.h.
type
ValueType v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::type
Definition at line 310 of file wasm-module-builder.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-module-builder.h