v8::internal::MachineType Class Reference
#include <machine-type.h>
Public Member Functions
constexpr MachineType ()
constexpr MachineType (MachineRepresentation representation, MachineSemantic semantic)
constexpr bool operator== (MachineType other) const
constexpr bool operator!= (MachineType other) const
constexpr MachineRepresentation representation () const
constexpr MachineSemantic semantic () const
constexpr bool IsNone () const
constexpr bool IsMapWord () const
constexpr bool IsSigned () const
constexpr bool IsUnsigned () const
constexpr bool IsTagged () const
constexpr bool IsTaggedSigned () const
constexpr bool IsTaggedPointer () const
constexpr bool IsCompressed () const
constexpr bool IsCompressedPointer () const
constexpr bool IsIndirectPointer () const
constexpr bool LessThanOrEqualPointerSize () const
constexpr uint8_t MemSize () const
Static Public Member Functions
constexpr static MachineRepresentation PointerRepresentation ()
constexpr static MachineType UintPtr ()
constexpr static MachineType IntPtr ()
constexpr static MachineType Int8 ()
constexpr static MachineType Uint8 ()
constexpr static MachineType Int16 ()
constexpr static MachineType Uint16 ()
constexpr static MachineType Int32 ()
constexpr static MachineType Uint32 ()
constexpr static MachineType Int64 ()
constexpr static MachineType Uint64 ()
constexpr static MachineType SignedBigInt64 ()
constexpr static MachineType UnsignedBigInt64 ()
constexpr static MachineType Float16 ()
constexpr static MachineType Float32 ()
constexpr static MachineType Float64 ()
constexpr static MachineType HoleyFloat64 ()
constexpr static MachineType Simd128 ()
constexpr static MachineType Simd256 ()
constexpr static MachineType Pointer ()
constexpr static MachineType TaggedPointer ()
constexpr static MachineType MapInHeader ()
constexpr static MachineType TaggedSigned ()
constexpr static MachineType AnyTagged ()
constexpr static MachineType CompressedPointer ()
constexpr static MachineType AnyCompressed ()
constexpr static MachineType SandboxedPointer ()
constexpr static MachineType ProtectedPointer ()
constexpr static MachineType IndirectPointer ()
constexpr static MachineType Bool ()
constexpr static MachineType None ()
static MachineType TypeForRepresentation (const MachineRepresentation &rep, bool isSigned=true)
static MachineType TypeForCType (const CTypeInfo &type)
Private Attributes
MachineRepresentation representation_
MachineSemantic semantic_
Detailed Description
Definition at line 109 of file machine-type.h.
Constructor & Destructor Documentation
MachineType() [1/2]
constexpr v8::internal::MachineType::MachineType () [inline], [constexpr]
Definition at line 111 of file machine-type.h.
      : representation_(MachineRepresentation::kNone),
        semantic_(MachineSemantic::kNone) {}
References v8::internal::kNone.
Referenced by AnyCompressed(), AnyTagged(), Bool(), CompressedPointer(), Float16(), Float32(), Float64(), HoleyFloat64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), MapInHeader(), None(), Pointer(), ProtectedPointer(), SandboxedPointer(), SignedBigInt64(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), and UnsignedBigInt64().
MachineType() [2/2]
constexpr v8::internal::MachineType::MachineType (MachineRepresentation representation, MachineSemantic semantic) [inline], [constexpr]
Definition at line 114 of file machine-type.h.
      : representation_(representation), semantic_(semantic) {}
Member Function Documentation
AnyCompressed()
constexpr static MachineType v8::internal::MachineType::AnyCompressed () [inline], [static], [constexpr]
Definition at line 257 of file machine-type.h.
                                               {
    return MachineType(MachineRepresentation::kCompressed,
                       MachineSemantic::kAny);
  }
References v8::internal::kAny, v8::internal::kCompressed, and MachineType().
Referenced by v8::internal::compiler::turboshaft::LoadOp::machine_type(), and TypeForRepresentation().
AnyTagged()
constexpr static MachineType v8::internal::MachineType::AnyTagged () [inline], [static], [constexpr]
Definition at line 250 of file machine-type.h.
                                           {
    return MachineType(MachineRepresentation::kTagged, MachineSemantic::kAny);
  }
References v8::internal::kAny, v8::internal::kTagged, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::StateValueDescriptor::ArgumentsElements(), v8::internal::compiler::StateValueDescriptor::ArgumentsLength(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyFastNumberJSArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsSlice(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemmove(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemset(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemmove(), v8::internal::CollectionsBuiltinsAssembler::CallGetHashRaw(), v8::internal::CollectionsBuiltinsAssembler::CallGetOrCreateHashRaw(), v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::CommonMachineType(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteAddAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteCompare(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteDivAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteModAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteMulAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteSubAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseAndPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseOrPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorNegNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosNegAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppBitwiseXorPosPosAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppLeftShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftResultLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::WeakCollectionsBuiltinsAssembler::CreateIdentityHash(), v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf(), v8::internal::compiler::StateValueDescriptor::Duplicate(), v8::internal::CodeStubAssembler::ExternalOneByteStringGetChars(), v8::internal::CodeStubAssembler::ExternalTwoByteStringGetChars(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::AccessBuilder::ForArgumentsCallee(), v8::internal::compiler::AccessBuilder::ForArgumentsLength(), v8::internal::compiler::AccessBuilder::ForCellValue(), v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::AccessBuilder::ForFeedbackVectorSlot(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorNextIndex(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectQueue(), v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundThis(), v8::internal::compiler::AccessBuilder::ForJSDateField(), v8::internal::compiler::AccessBuilder::ForJSForInCacheArrayElement(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(), v8::internal::compiler::AccessBuilder::ForJSIteratorResultDone(), v8::internal::compiler::AccessBuilder::ForJSIteratorResultValue(), v8::internal::compiler::AccessBuilder::ForJSObjectOffset(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash(), v8::internal::compiler::AccessBuilder::ForJSPrimitiveWrapperValue(), v8::internal::compiler::AccessBuilder::ForJSRegExpFlags(), v8::internal::compiler::AccessBuilder::ForJSRegExpLastIndex(), v8::internal::compiler::AccessBuilder::ForJSRegExpSource(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayBasePointer(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapEntryValue(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNextTable(), v8::internal::compiler::AccessBuilder::ForPropertyArraySlot(), v8::internal::LinkageLocation::ForSavedCallerConstantPool(), v8::internal::LinkageLocation::ForSavedCallerFunction(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsMappedEntry(), v8::internal::compiler::AccessBuilder::ForWeakFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForWeakFixedArraySlot(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::CodeStubAssembler::GetCoverageInfo(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::Linkage::GetOsrValueLocation(), v8::internal::compiler::Linkage::GetParameterSecondaryLocation(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::GetParameterType(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::CallInterfaceDescriptorData::InitializeTypes(), v8::internal::AccessorAssembler::InvalidateValidityCellIfPrototype(), v8::internal::WasmBuiltinsAssembler::LoadContextFromInstanceData(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElementAny(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadJSArrayElements(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::compiler::RawMachineAssembler::LoadProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadWeakFixedArrayElement(), v8::internal::wasm::ValueTypeBase::machine_type(), v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor(), v8::internal::maglev::detail::MoveArgumentsForBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::operator TNode< A >(), v8::internal::compiler::StateValueDescriptor::OptimizedOut(), v8::internal::compiler::StateValueDescriptor::Recursive(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::CodeStubAssembler::RefillMathRandom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::compiler::StateValueDescriptor::RestLength(), v8::internal::CodeStubAssembler::SmiLexicographicCompare(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::compiler::WasmGraphAssembler::StoreFixedArrayElementAny(), v8::internal::compiler::StateValueDescriptor::StringConcat(), v8::internal::WasmBuiltinsAssembler::StringToFloat64(), v8::internal::CodeStubAssembler::StringWriteToFlatOneByte(), v8::internal::CodeStubAssembler::StringWriteToFlatTwoByte(), v8::internal::TF_BUILTIN(), v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::AccessorAssembler::TryMonomorphicCase(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::compiler::StateValuesAccess::iterator::type(), v8::internal::compiler::RepresentationChanger::TypeForBasePointer(), TypeForCType(), TypeForRepresentation(), and v8::internal::maglev::CallBuiltin::VerifyInputs().
Bool()
constexpr static MachineType v8::internal::MachineType::Bool () [inline], [static], [constexpr]
Definition at line 273 of file machine-type.h.
                                      {
    return MachineType(MachineRepresentation::kBit, MachineSemantic::kBool);
  }
References v8::internal::kBit, v8::internal::kBool, and MachineType().
Referenced by TypeForCType(), TypeForRepresentation(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
CompressedPointer()
constexpr static MachineType v8::internal::MachineType::CompressedPointer () [inline], [static], [constexpr]
Definition at line 253 of file machine-type.h.
                                                   {
    return MachineType(MachineRepresentation::kCompressedPointer,
                       MachineSemantic::kAny);
  }
References v8::internal::kAny, v8::internal::kCompressedPointer, and MachineType().
Referenced by v8::internal::compiler::turboshaft::LoadOp::machine_type(), and TypeForRepresentation().
Float16()
constexpr static MachineType v8::internal::MachineType::Float16 () [inline], [static], [constexpr]
Definition at line 214 of file machine-type.h.
                                         {
    return MachineType(MachineRepresentation::kFloat16,
                       MachineSemantic::kNumber);
  }
References v8::internal::kFloat16, v8::internal::kNumber, and MachineType().
Referenced by v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), and TypeForRepresentation().
Float32()
constexpr static MachineType v8::internal::MachineType::Float32 () [inline], [static], [constexpr]
Definition at line 218 of file machine-type.h.
                                         {
    return MachineType(MachineRepresentation::kFloat32,
                       MachineSemantic::kNumber);
  }
References v8::internal::kFloat32, v8::internal::kNumber, and MachineType().
Referenced by v8::internal::compiler::InstructionSelector::EmitPrepareResults(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), TypeForCType(), and TypeForRepresentation().
Float64()
constexpr static MachineType v8::internal::MachineType::Float64 () [inline], [static], [constexpr]
Definition at line 222 of file machine-type.h.
                                         {
    return MachineType(MachineRepresentation::kFloat64,
                       MachineSemantic::kNumber);
  }
References v8::internal::kFloat64, v8::internal::kNumber, and MachineType().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::InstructionSelector::EmitPrepareResults(), v8::internal::CodeStubAssembler::ExtractFixedDoubleArrayFillingHoles(), v8::internal::compiler::AccessBuilder::ForContextCellFloat64Value(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedDoubleArrayElement(), v8::internal::compiler::AccessBuilder::ForHeapNumberValue(), v8::internal::compiler::AccessBuilder::ForJSDateValue(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::CodeStubAssembler::LoadElementAndPrepareForStore(), v8::internal::compiler::GraphAssembler::LoadHeapNumberValue(), v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::NewArray(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::WasmBuiltinsAssembler::StringToFloat64(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), TypeForCType(), and TypeForRepresentation().
HoleyFloat64()
constexpr static MachineType v8::internal::MachineType::HoleyFloat64 () [inline], [static], [constexpr]
Definition at line 226 of file machine-type.h.
                                              {
    return MachineType(MachineRepresentation::kFloat64,
                       MachineSemantic::kHoleyFloat64);
  }
References v8::internal::kFloat64, v8::internal::kHoleyFloat64, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), and v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor().
IndirectPointer()
constexpr static MachineType v8::internal::MachineType::IndirectPointer () [inline], [static], [constexpr]
Definition at line 269 of file machine-type.h.
                                                 {
    return MachineType(MachineRepresentation::kIndirectPointer,
                       MachineSemantic::kInt32);
  }
References v8::internal::kIndirectPointer, v8::internal::kInt32, and MachineType().
Referenced by v8::internal::compiler::RawMachineAssembler::OptimizedStoreIndirectPointerField(), v8::internal::compiler::AllocationBuilder::Store(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), and TypeForRepresentation().
Int16()
constexpr static MachineType v8::internal::MachineType::Int16 () [inline], [static], [constexpr]
Definition at line 185 of file machine-type.h.
                                       {
    return MachineType(MachineRepresentation::kWord16, MachineSemantic::kInt32);
  }
References v8::internal::kInt32, v8::internal::kWord16, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), and TypeForRepresentation().
Int32()
constexpr static MachineType v8::internal::MachineType::Int32 () [inline], [static], [constexpr]
Definition at line 192 of file machine-type.h.
                                       {
    return MachineType(MachineRepresentation::kWord32, MachineSemantic::kInt32);
  }
References v8::internal::kInt32, v8::internal::kWord32, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicNotify(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::compiler::WasmGraphBuilder::BuildModifyThreadInWasmFlagHelper(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildReceiverNode(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::CodeStubAssembler::ComputeSeededHash(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteCompare(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteDivAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteModAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppAbsoluteMulAndCanonicalize(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::compiler::AccessBuilder::ForContextCellInt32Value(), v8::internal::compiler::AccessBuilder::ForContextCellState(), v8::internal::compiler::AccessBuilder::ForFeedbackCellInterruptBudget(), v8::internal::compiler::AccessBuilder::ForFeedbackVectorInvocationCount(), v8::internal::compiler::turboshaft::AccessBuilderTS::ForFeedbackVectorLength(), v8::internal::compiler::AccessBuilder::ForMapBitField3(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::AccessorAssembler::HandleLoadICSmiHandlerCase(), v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters(), IntPtr(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::compiler::RawMachineAssembler::LoadProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadStringLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::CodeStubAssembler::StringWriteToFlatOneByte(), v8::internal::CodeStubAssembler::StringWriteToFlatTwoByte(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::CodeStubAssembler::TryToName(), TypeForCType(), and TypeForRepresentation().
Int64()
constexpr static MachineType v8::internal::MachineType::Int64 () [inline], [static], [constexpr]
Definition at line 199 of file machine-type.h.
                                       {
    return MachineType(MachineRepresentation::kWord64, MachineSemantic::kInt64);
  }
References v8::internal::kInt64, v8::internal::kWord64, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), IntPtr(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), TypeForCType(), TypeForRepresentation(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
Int8()
constexpr static MachineType v8::internal::MachineType::Int8 () [inline], [static], [constexpr]
Definition at line 179 of file machine-type.h.
                                      {
    return MachineType(MachineRepresentation::kWord8, MachineSemantic::kInt32);
  }
References v8::internal::kInt32, v8::internal::kWord8, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::DataViewBuiltinsAssembler::LoadInt8(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), and TypeForRepresentation().
IntPtr()
constexpr static MachineType v8::internal::MachineType::IntPtr () [inline], [static], [constexpr]
Definition at line 176 of file machine-type.h.
                                        {
    return (kSystemPointerSize == 4) ? Int32() : Int64();
  }
References Int32(), Int64(), and v8::internal::kSystemPointerSize.
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemset(), v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString(), v8::internal::StringBuiltinsAssembler::CallSearchStringRaw(), v8::internal::BigIntBuiltinsAssembler::CppLeftShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftResultLength(), v8::internal::AllocateDescriptor::DEFINE_RESULT_AND_PARAMETER_TYPES(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::compiler::AccessBuilder::ForExternalIntPtr(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::compiler::CodeAssembler::LoadPointerFromRootRegister(), v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), and v8::internal::TF_BUILTIN().
IsCompressed()
constexpr bool v8::internal::MachineType::IsCompressed () const [inline], [constexpr]
Definition at line 159 of file machine-type.h.
                                      {
    return representation() == MachineRepresentation::kCompressedPointer ||
           representation() == MachineRepresentation::kCompressed;
  }
References v8::internal::kCompressed, v8::internal::kCompressedPointer, and representation().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned().
IsCompressedPointer()
constexpr bool v8::internal::MachineType::IsCompressedPointer () const [inline], [constexpr]
Definition at line 163 of file machine-type.h.
                                             {
    return representation() == MachineRepresentation::kCompressedPointer;
  }
References v8::internal::kCompressedPointer, and representation().
IsIndirectPointer()
constexpr bool v8::internal::MachineType::IsIndirectPointer () const [inline], [constexpr]
Definition at line 166 of file machine-type.h.
                                           {
    return representation() == MachineRepresentation::kIndirectPointer;
  }
References v8::internal::kIndirectPointer, and representation().
IsMapWord()
constexpr bool v8::internal::MachineType::IsMapWord () const [inline], [constexpr]
Definition at line 136 of file machine-type.h.
                                   {
    return representation() == MachineRepresentation::kMapWord;
  }
References v8::internal::kMapWord, and representation().
Referenced by v8::internal::compiler::FieldAccess::FieldAccess(), v8::internal::compiler::MachineOperatorBuilder::Load(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), and v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl().
IsNone()
constexpr bool v8::internal::MachineType::IsNone () const [inline], [constexpr]
Definition at line 132 of file machine-type.h.
                                {
    return representation() == MachineRepresentation::kNone;
  }
References v8::internal::kNone, and representation().
Referenced by v8::internal::CodeStubAssembler::LoadDoubleWithUndefinedAndHoleCheck().
IsSigned()
constexpr bool v8::internal::MachineType::IsSigned () const [inline], [constexpr]
Definition at line 140 of file machine-type.h.
                                  {
    return semantic() == MachineSemantic::kInt32 ||
           semantic() == MachineSemantic::kInt64;
  }
References v8::internal::kInt32, v8::internal::kInt64, and semantic().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessLoad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad().
IsTagged()
constexpr bool v8::internal::MachineType::IsTagged () const [inline], [constexpr]
Definition at line 148 of file machine-type.h.
                                  {
    return representation() == MachineRepresentation::kTaggedPointer ||
           representation() == MachineRepresentation::kTaggedSigned ||
           representation() == MachineRepresentation::kTagged;
  }
References v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, and representation().
Referenced by v8::internal::CommonMachineType(), v8::internal::compiler::WasmGraphBuilder::GetSafeLoadOperator(), and v8::internal::compiler::CallDescriptor::GetTaggedParameterSlots().
IsTaggedPointer()
constexpr bool v8::internal::MachineType::IsTaggedPointer () const [inline], [constexpr]
Definition at line 156 of file machine-type.h.
                                         {
    return representation() == MachineRepresentation::kTaggedPointer;
  }
References v8::internal::kTaggedPointer, and representation().
IsTaggedSigned()
constexpr bool v8::internal::MachineType::IsTaggedSigned () const [inline], [constexpr]
Definition at line 153 of file machine-type.h.
                                        {
    return representation() == MachineRepresentation::kTaggedSigned;
  }
References v8::internal::kTaggedSigned, and representation().
IsUnsigned()
constexpr bool v8::internal::MachineType::IsUnsigned () const [inline], [constexpr]
Definition at line 144 of file machine-type.h.
                                    {
    return semantic() == MachineSemantic::kUint32 ||
           semantic() == MachineSemantic::kUint64;
  }
References v8::internal::kUint32, v8::internal::kUint64, and semantic().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), and v8::internal::compiler::InstructionSelector::VisitLoad().
LessThanOrEqualPointerSize()
constexpr bool v8::internal::MachineType::LessThanOrEqualPointerSize () const [inline], [constexpr]
Definition at line 358 of file machine-type.h.
                                                    {
    return ElementSizeLog2Of(this->representation()) <= kSystemPointerSizeLog2;
  }
References v8::internal::ElementSizeLog2Of(), v8::internal::kSystemPointerSizeLog2, and representation().
MapInHeader()
constexpr static MachineType v8::internal::MachineType::MapInHeader () [inline], [static], [constexpr]
Definition at line 243 of file machine-type.h.
                                             {
    return MachineType(MachineRepresentation::kMapWord, MachineSemantic::kAny);
  }
References v8::internal::kAny, v8::internal::kMapWord, and MachineType().
Referenced by v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::RawMachineAssembler::LoadFromObject(), and v8::internal::CodeStubAssembler::LoadObjectField().
MemSize()
constexpr uint8_t v8::internal::MachineType::MemSize () const [inline], [constexpr]
Definition at line 362 of file machine-type.h.
                                    {
    return 1 << i::ElementSizeLog2Of(this->representation());
  }
References v8::internal::ElementSizeLog2Of(), and representation().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode().
None()
constexpr static MachineType v8::internal::MachineType::None () [inline], [static], [constexpr]
Definition at line 276 of file machine-type.h.
                                      {
    return MachineType(MachineRepresentation::kNone, MachineSemantic::kNone);
  }
References v8::internal::kNone, and MachineType().
Referenced by v8::internal::CommonMachineType(), v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf(), v8::internal::AccessorAssembler::EmitElementLoad(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::wasm::ValueTypeBase::machine_type(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::operator<<(), v8::internal::KeyedStoreGenericAssembler::StoreElementWithCapacity(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryNarrowOpcodeSize(), and TypeForRepresentation().
operator!=()
constexpr bool v8::internal::MachineType::operator!= (MachineType other) const [inline], [constexpr]
Definition at line 123 of file machine-type.h.
                                                     {
    return !(*this == other);
  }
operator==()
constexpr bool v8::internal::MachineType::operator== (MachineType other) const [inline], [constexpr]
Definition at line 118 of file machine-type.h.
                                                     {
    return representation() == other.representation() &&
           semantic() == other.semantic();
  }
References representation(), and semantic().
Pointer()
constexpr static MachineType v8::internal::MachineType::Pointer () [inline], [static], [constexpr]
Definition at line 236 of file machine-type.h.
                                         {
    return MachineType(PointerRepresentation(), MachineSemantic::kNone);
  }
References v8::internal::kNone, MachineType(), and PointerRepresentation().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicNotify(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIntToFloatConversionInstruction(), v8::internal::compiler::WasmGraphAssembler::BuildLoadExternalPointerFromObject(), v8::internal::compiler::WasmGraphBuilder::BuildModifyThreadInWasmFlag(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchBackFromCentralStack(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchToTheCentralStack(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemmove(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemset(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemmove(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::CollectionsBuiltinsAssembler::CallGetHashRaw(), v8::internal::CollectionsBuiltinsAssembler::CallGetOrCreateHashRaw(), v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString(), v8::internal::StringBuiltinsAssembler::CallSearchStringRaw(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::CodeStubAssembler::ComputeSeededHash(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::WeakCollectionsBuiltinsAssembler::CreateIdentityHash(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::CodeStubAssembler::ExternalOneByteStringGetChars(), v8::internal::CodeStubAssembler::ExternalTwoByteStringGetChars(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::compiler::AccessBuilder::ForExternalStringResourceData(), v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::compiler::AccessBuilder::ForJSExternalObjectValue(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayExternalPointer(), v8::internal::LinkageLocation::ForSavedCallerFramePtr(), v8::internal::LinkageLocation::ForSavedCallerReturnAddress(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::CodeStubAssembler::GetCoverageInfo(), v8::internal::compiler::WasmGraphBuilder::GetSafeLoadOperator(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::GetWasmCallDescriptor(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet(), v8::internal::CodeStubAssembler::IsPageFlagReset(), v8::internal::CodeStubAssembler::IsPageFlagSet(), v8::internal::WriteBarrierCodeStubAssembler::LoadBucket(), v8::internal::CodeStubAssembler::LoadExternalPointerFromObject(), v8::internal::CodeStubAssembler::LoadMemoryChunkFlags(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::compiler::RawMachineAssembler::LoadProtectedPointerFromObject(), v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::compiler::WasmGCLowering::Null(), v8::internal::CodeStubAssembler::PerformStackCheck(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::CodeStubAssembler::RefillMathRandom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::StringBuiltinsAssembler::ReplaceUnpairedSurrogates(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), v8::internal::CodeStubAssembler::SmiLexicographicCompare(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::CodeStubAssembler::StringWriteToFlatOneByte(), v8::internal::CodeStubAssembler::StringWriteToFlatTwoByte(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryInternalizeString(), v8::internal::CodeStubAssembler::TryToName(), v8::internal::compiler::RepresentationChanger::TypeForBasePointer(), TypeForCType(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
PointerRepresentation()
constexpr static MachineRepresentation v8::internal::MachineType::PointerRepresentation () [inline], [static], [constexpr]
Definition at line 169 of file machine-type.h.
                                                                 {
    return (kSystemPointerSize == 4) ? MachineRepresentation::kWord32
                                     : MachineRepresentation::kWord64;
  }
References v8::internal::kSystemPointerSize, v8::internal::kWord32, and v8::internal::kWord64.
Referenced by v8::internal::compiler::GraphAssembler::AdaptLocalArgument(), v8::internal::CodeStubAssembler::AllocateRaw(), v8::internal::compiler::JSGraphAssembler::ArrayBufferViewByteLength(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCWasmEntry(), v8::internal::compiler::WasmGraphBuilder::BuildSafeStore(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::compiler::UseInfo::CheckedTaggedAsArrayIndex(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTaggedOrPointer(), v8::internal::compiler::CompileCWasmEntry(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::CreateCommonMachineGraph(), v8::internal::compiler::InstructionSequence::DefaultRepresentation(), v8::internal::MicrotaskQueueBuiltinsAssembler::EnterContext(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::maglev::ValueNode::GetMachineRepresentation(), v8::internal::compiler::RepresentationSelector::GetOutputInfoForPhi(), v8::internal::RegExpBuiltinsAssembler::GetStringPointers(), v8::internal::MicrotaskQueueBuiltinsAssembler::IncrementFinishedMicrotaskCount(), v8::internal::compiler::TFPipelineData::InitializeWithGraphZone(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Is32(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Is64(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::CodeStubAssembler::NumberDictionaryLookup(), Pointer(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::MicrotaskQueueBuiltinsAssembler::RewindEnteredContext(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueSize(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetMicrotaskQueueStart(), v8::internal::CodeStubAssembler::StoreExternalPointerToObject(), v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier(), v8::internal::TF_BUILTIN(), v8::internal::compiler::TFPipelineData::TFPipelineData(), v8::internal::interpreter::InterpreterAssembler::TraceBytecodeDispatch(), v8::internal::compiler::JSGraphAssembler::TypedArrayLength(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::UseInfo::Word(), and v8::internal::compiler::fast_api_call::FastApiCallBuilder::WrapFastCall().
ProtectedPointer()
constexpr static MachineType v8::internal::MachineType::ProtectedPointer () [inline], [static], [constexpr]
Definition at line 265 of file machine-type.h.
                                                  {
    return MachineType(MachineRepresentation::kProtectedPointer,
                       MachineSemantic::kAny);
  }
References v8::internal::kAny, v8::internal::kProtectedPointer, and MachineType().
Referenced by v8::internal::compiler::WasmGraphAssembler::LoadImmutableProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadProtectedPointerFromObject(), and v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType().
representation()
constexpr MachineRepresentation v8::internal::MachineType::representation () const [inline], [constexpr]
Definition at line 127 of file machine-type.h.
                                                         {
    return representation_;
  }
References representation_.
Referenced by v8::internal::compiler::RawMachineAssembler::AtomicLoad(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessLoad(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::CallInterfaceDescriptor::CheckFloatingPointParameters(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::compiler::MemoryLowering::ComputeIndex(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf(), v8::internal::compiler::LoadElimination::FieldIndexOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::GetLoadOpcode(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::GetLoadOpcode(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), IsCompressed(), IsCompressedPointer(), IsIndirectPointer(), IsMapWord(), IsNone(), v8::internal::compiler::IsNonTruncatingMachineTypeFor(), v8::internal::LinkageLocation::IsSameLocation(), IsTagged(), IsTaggedPointer(), IsTaggedSigned(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedStoreSupported(), LessThanOrEqualPointerSize(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::wasm::ValueTypeBase::machine_representation(), MemSize(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementAt(), operator==(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::LoadElimination::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::SelectLoadOpcode(), v8::internal::compiler::SelectLoadOpcode(), v8::internal::StringBuiltinsAssembler::StringEqual_Loop(), v8::internal::compiler::OperandGenerator::ToUnallocatedOperand(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryNarrowOpcodeSize(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryNarrowOpcodeSize(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::RepresentationSelector::VisitFastApiCall(), v8::internal::compiler::InstructionSelector::VisitLoad(), and v8::internal::compiler::RepresentationSelector::VisitNode().
SandboxedPointer()
constexpr static MachineType v8::internal::MachineType::SandboxedPointer () [inline], [static], [constexpr]
Definition at line 261 of file machine-type.h.
                                                  {
    return MachineType(MachineRepresentation::kSandboxedPointer,
                       MachineSemantic::kInt64);
  }
References v8::internal::kInt64, v8::internal::kSandboxedPointer, and MachineType().
Referenced by v8::internal::compiler::AccessBuilder::ForJSDataViewDataPointer(), v8::internal::compiler::AccessBuilder::ForJSTypedArrayExternalPointer(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), and TypeForRepresentation().
semantic()
constexpr MachineSemantic v8::internal::MachineType::semantic () const [inline], [constexpr]
Definition at line 130 of file machine-type.h.
{ return semantic_; }
References semantic_.
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf(), v8::internal::compiler::IsNonTruncatingMachineTypeFor(), IsSigned(), IsUnsigned(), operator==(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryNarrowOpcodeSize(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryNarrowOpcodeSize().
SignedBigInt64()
constexpr static MachineType v8::internal::MachineType::SignedBigInt64 () [inline], [static], [constexpr]
Definition at line 206 of file machine-type.h.
                                                {
    return MachineType(MachineRepresentation::kWord64,
                       MachineSemantic::kSignedBigInt64);
  }
References v8::internal::kSignedBigInt64, v8::internal::kWord64, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), and v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf().
Simd128()
constexpr static MachineType v8::internal::MachineType::Simd128 () [inline], [static], [constexpr]
Definition at line 230 of file machine-type.h.
                                         {
    return MachineType(MachineRepresentation::kSimd128, MachineSemantic::kNone);
  }
References v8::internal::kNone, v8::internal::kSimd128, and MachineType().
Referenced by v8::internal::compiler::InstructionSelector::EmitPrepareResults(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), and TypeForRepresentation().
Simd256()
constexpr static MachineType v8::internal::MachineType::Simd256 () [inline], [static], [constexpr]
Definition at line 233 of file machine-type.h.
                                         {
    return MachineType(MachineRepresentation::kSimd256, MachineSemantic::kNone);
  }
References v8::internal::kNone, v8::internal::kSimd256, and MachineType().
Referenced by v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), TypeForRepresentation(), and v8::internal::compiler::Revectorizer::VectorizeTree().
TaggedPointer()
constexpr static MachineType v8::internal::MachineType::TaggedPointer () [inline], [static], [constexpr]
Definition at line 239 of file machine-type.h.
                                               {
    return MachineType(MachineRepresentation::kTaggedPointer,
                       MachineSemantic::kAny);
  }
References v8::internal::kAny, v8::internal::kTaggedPointer, and MachineType().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSFastApiCallWrapper(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::AllocateDescriptor::DEFINE_RESULT_AND_PARAMETER_TYPES(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::ExceptionLocation(), v8::internal::compiler::AccessBuilder::ForConsStringFirst(), v8::internal::compiler::AccessBuilder::ForConsStringSecond(), v8::internal::compiler::AccessBuilder::ForContextSlotKnownPointer(), v8::internal::compiler::AccessBuilder::ForDescriptorArrayEnumCache(), v8::internal::compiler::AccessBuilder::ForEnumCacheIndices(), v8::internal::compiler::AccessBuilder::ForEnumCacheKeys(), v8::internal::compiler::AccessBuilder::ForFeedbackVectorClosureFeedbackCellArray(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorIteratedObject(), v8::internal::compiler::AccessBuilder::ForJSAsyncFunctionObjectPromise(), v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundArguments(), v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundTargetFunction(), v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorTable(), v8::internal::compiler::AccessBuilder::ForJSCollectionTable(), v8::internal::compiler::AccessBuilder::ForJSFunctionCode(), v8::internal::compiler::AccessBuilder::ForJSFunctionContext(), v8::internal::compiler::AccessBuilder::ForJSFunctionFeedbackCell(), v8::internal::compiler::AccessBuilder::ForJSFunctionPrototypeOrInitialMap(), v8::internal::compiler::AccessBuilder::ForJSFunctionSharedFunctionInfo(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContext(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectFunction(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectReceiver(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForJSRegExpData(), v8::internal::compiler::AccessBuilder::ForJSStringIteratorString(), v8::internal::compiler::AccessBuilder::ForMapDescriptors(), v8::internal::compiler::AccessBuilder::ForMapNativeContext(), v8::internal::compiler::AccessBuilder::ForMapPrototype(), v8::internal::compiler::AccessBuilder::ForModuleRegularExports(), v8::internal::compiler::AccessBuilder::ForModuleRegularImports(), v8::internal::compiler::AccessBuilder::ForSlicedStringParent(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsArguments(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsContext(), v8::internal::compiler::AccessBuilder::ForThinStringActual(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::CodeStubAssembler::GetCoverageInfo(), v8::internal::wasm::IterateSignatureImpl(), v8::internal::compiler::WasmGraphAssembler::LoadContextNoCellFromJSFunction(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElementPtr(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableTrustedPointerFromObject(), v8::internal::compiler::GraphAssembler::LoadMap(), v8::internal::compiler::WasmGraphAssembler::LoadMap(), v8::internal::compiler::WasmGraphAssembler::LoadSharedFunctionInfo(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObjectTrapOnNull(), v8::internal::compiler::WasmGraphAssembler::LoadWasmTypeInfo(), v8::internal::CodeStubAssembler::NameDictionaryLookupWithForwardIndex(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::compiler::WasmGCLowering::ReduceRttCanon(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl(), v8::internal::compiler::WasmGraphAssembler::StoreMap(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), and TypeForRepresentation().
TaggedSigned()
constexpr static MachineType v8::internal::MachineType::TaggedSigned () [inline], [static], [constexpr]
Definition at line 246 of file machine-type.h.
                                              {
    return MachineType(MachineRepresentation::kTaggedSigned,
                       MachineSemantic::kInt32);
  }
References v8::internal::kInt32, v8::internal::kTaggedSigned, and MachineType().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::AllocateDescriptor::DEFINE_RESULT_AND_PARAMETER_TYPES(), v8::internal::compiler::AccessBuilder::ForContextSlotSmi(), v8::internal::compiler::AccessBuilder::ForDictionaryNextEnumerationIndex(), v8::internal::compiler::AccessBuilder::ForDictionaryObjectHashIndex(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedArrayLength(), v8::internal::compiler::AccessBuilder::ForHashTableBaseCapacity(), v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfDeletedElement(), v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfElements(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorKind(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectIsAwaiting(), v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorIndex(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectResumeMode(), v8::internal::compiler::AccessBuilder::ForJSStringIteratorIndex(), v8::internal::compiler::AccessBuilder::ForNameDictionaryFlagsIndex(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfBuckets(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfDeletedElements(), v8::internal::compiler::AccessBuilder::ForOrderedHashMapOrSetNumberOfElements(), v8::internal::compiler::AccessBuilder::ForPropertyArrayLengthAndHash(), v8::internal::compiler::AccessBuilder::ForSlicedStringOffset(), v8::internal::compiler::AccessBuilder::ForWeakFixedArrayLength(), v8::internal::compiler::WasmGraphAssembler::LoadExportedFunctionIndexAsSmi(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElementSmi(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayLengthAsSmi(), v8::internal::compiler::CodeAssembler::CheckedNode< PreviousType, FromTyped >::operator TNode< A >(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGraphAssembler::StoreFixedArrayElementSmi(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), and TypeForRepresentation().
TypeForCType()
static MachineType v8::internal::MachineType::TypeForCType (const CTypeInfo & type) [inline], [static]
Definition at line 324 of file machine-type.h.
                                                         {
    switch (type.GetType()) {
      case CTypeInfo::Type::kVoid:
        return MachineType::AnyTagged();
      case CTypeInfo::Type::kBool:
        return MachineType::Bool();
      case CTypeInfo::Type::kUint8:
        return MachineType::Uint8();
      case CTypeInfo::Type::kInt32:
        return MachineType::Int32();
      case CTypeInfo::Type::kUint32:
        return MachineType::Uint32();
      case CTypeInfo::Type::kInt64:
        return MachineType::Int64();
      case CTypeInfo::Type::kAny:
        static_assert(
            sizeof(AnyCType) == kInt64Size,
            "CTypeInfo::Type::kAny is assumed to be of size 64 bits.");
        return MachineType::Int64();
      case CTypeInfo::Type::kUint64:
        return MachineType::Uint64();
      case CTypeInfo::Type::kFloat32:
        return MachineType::Float32();
      case CTypeInfo::Type::kFloat64:
        return MachineType::Float64();
      case CTypeInfo::Type::kPointer:
        return MachineType::Pointer();
      case CTypeInfo::Type::kV8Value:
      case CTypeInfo::Type::kSeqOneByteString:
      case CTypeInfo::Type::kApiObject:
        return MachineType::AnyTagged();
    }
  }
References AnyTagged(), Bool(), Float32(), Float64(), Int32(), Int64(), v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CTypeInfo::kBool, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::internal::kInt64Size, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, Pointer(), v8::internal::tracing::type, Uint32(), Uint64(), and Uint8().
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::turboshaft::RegisterRepresentation::FromCTypeInfo(), and v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::GetFunctionSigForFastApiImport().
TypeForRepresentation()
static MachineType v8::internal::MachineType::TypeForRepresentation (const MachineRepresentation & rep, bool isSigned = true) [inline], [static]
Definition at line 280 of file machine-type.h.
                                                                 {
    switch (rep) {
      case MachineRepresentation::kNone:
        return MachineType::None();
      case MachineRepresentation::kBit:
        return MachineType::Bool();
      case MachineRepresentation::kWord8:
        return isSigned ? MachineType::Int8() : MachineType::Uint8();
      case MachineRepresentation::kWord16:
        return isSigned ? MachineType::Int16() : MachineType::Uint16();
      case MachineRepresentation::kWord32:
        return isSigned ? MachineType::Int32() : MachineType::Uint32();
      case MachineRepresentation::kWord64:
        return isSigned ? MachineType::Int64() : MachineType::Uint64();
      case MachineRepresentation::kFloat16:
        return MachineType::Float16();
      case MachineRepresentation::kFloat32:
        return MachineType::Float32();
      case MachineRepresentation::kFloat64:
        return MachineType::Float64();
      case MachineRepresentation::kSimd128:
        return MachineType::Simd128();
      case MachineRepresentation::kSimd256:
        return MachineType::Simd256();
      case MachineRepresentation::kTagged:
        return MachineType::AnyTagged();
      case MachineRepresentation::kTaggedSigned:
        return MachineType::TaggedSigned();
      case MachineRepresentation::kTaggedPointer:
        return MachineType::TaggedPointer();
      case MachineRepresentation::kCompressed:
        return MachineType::AnyCompressed();
      case MachineRepresentation::kIndirectPointer:
        return MachineType::IndirectPointer();
      case MachineRepresentation::kCompressedPointer:
        return MachineType::CompressedPointer();
      case MachineRepresentation::kSandboxedPointer:
        return MachineType::SandboxedPointer();
      default:
        UNREACHABLE();
    }
  }
References AnyCompressed(), AnyTagged(), Bool(), CompressedPointer(), Float16(), Float32(), Float64(), IndirectPointer(), Int16(), Int32(), Int64(), Int8(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kNone, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, None(), SandboxedPointer(), Simd128(), Simd256(), TaggedPointer(), TaggedSigned(), Uint16(), Uint32(), Uint64(), Uint8(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::ForPropertyCellValue(), v8::internal::wasm::LinkageLocationAllocator::Next(), v8::internal::compiler::ObjectAccessForGCStores(), v8::internal::compiler::RawMachineAssembler::OptimizedStoreField(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), and v8::internal::compiler::RawMachineAssembler::StoreToObject().
Uint16()
constexpr static MachineType v8::internal::MachineType::Uint16 () [inline], [static], [constexpr]
Definition at line 188 of file machine-type.h.
                                        {
    return MachineType(MachineRepresentation::kWord16,
                       MachineSemantic::kUint32);
  }
References v8::internal::kUint32, v8::internal::kWord16, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::compiler::AccessBuilder::ForFeedbackVectorFlags(), v8::internal::compiler::AccessBuilder::ForMapInstanceType(), v8::internal::compiler::AccessBuilder::ForSeqTwoByteStringCharacter(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), v8::internal::compiler::WasmGraphAssembler::LoadInstanceType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), and TypeForRepresentation().
Uint32()
constexpr static MachineType v8::internal::MachineType::Uint32 () [inline], [static], [constexpr]
Definition at line 195 of file machine-type.h.
                                        {
    return MachineType(MachineRepresentation::kWord32,
                       MachineSemantic::kUint32);
  }
References v8::internal::kUint32, v8::internal::kWord32, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicNotify(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCallAndReturn(), v8::internal::compiler::WasmGraphAssembler::BuildLoadExternalPointerFromObject(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad(), v8::internal::CodeStubAssembler::ComputeSeededHash(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftAndCanonicalize(), v8::internal::BigIntBuiltinsAssembler::CppRightShiftResultLength(), v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp(), v8::internal::compiler::AccessBuilder::ForBigIntBitfield(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferBitField(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBitField(), v8::internal::compiler::AccessBuilder::ForNameRawHashField(), v8::internal::compiler::AccessBuilder::ForScopeInfoFlags(), v8::internal::compiler::AccessBuilder::ForStringLength(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), v8::internal::StringBuiltinsAssembler::HasUnpairedSurrogate(), v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableTrustedPointerFromObject(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObjectTrapOnNull(), v8::internal::compiler::turboshaft::anonymous_namespace{turbolev-graph-builder.cc}::MachineTypeFor(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringFromSingleCodePoint(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::CodeStubAssembler::TryToName(), TypeForCType(), TypeForRepresentation(), UintPtr(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl().
Uint64()
constexpr static MachineType v8::internal::MachineType::Uint64 () [inline], [static], [constexpr]
Definition at line 202 of file machine-type.h.
                                        {
    return MachineType(MachineRepresentation::kWord64,
                       MachineSemantic::kUint64);
  }
References v8::internal::kUint64, v8::internal::kWord64, and MachineType().
Referenced by v8::internal::compiler::RawMachineAssembler::AtomicCompareExchange64(), v8::internal::compiler::CodeAssembler::AtomicLoad64(), v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp(), v8::internal::compiler::AccessBuilder::ForBigIntLeastSignificantDigit64(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), TypeForCType(), TypeForRepresentation(), UintPtr(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
Uint8()
constexpr static MachineType v8::internal::MachineType::Uint8 () [inline], [static], [constexpr]
Definition at line 182 of file machine-type.h.
                                       {
    return MachineType(MachineRepresentation::kWord8, MachineSemantic::kUint32);
  }
References v8::internal::kUint32, v8::internal::kWord8, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::SharedArrayBufferBuiltinsAssembler::AtomicBinopBuiltinCommon(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchToTheCentralStackIfNeeded(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReadUnaligned(), v8::internal::StringBuiltinsAssembler::CopyStringCharacters(), v8::internal::compiler::AccessBuilder::ForMapBitField(), v8::internal::compiler::AccessBuilder::ForMapBitField2(), v8::internal::compiler::AccessBuilder::ForSeqOneByteStringCharacter(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), v8::internal::CodeStubAssembler::LoadRuntimeFlag(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTransform(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::DataViewBuiltinsAssembler::LoadUint8(), v8::internal::compiler::CodeAssembler::LoadUint8FromRootRegister(), v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::StringBuiltinsAssembler::StringEqual_FastLoop(), v8::internal::TF_BUILTIN(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType(), v8::internal::compiler::CsaLoadElimination::TruncateAndExtend(), TypeForCType(), and TypeForRepresentation().
UintPtr()
constexpr static MachineType v8::internal::MachineType::UintPtr () [inline], [static], [constexpr]
Definition at line 173 of file machine-type.h.
                                         {
    return (kSystemPointerSize == 4) ? Uint32() : Uint64();
  }
References v8::internal::kSystemPointerSize, Uint32(), and Uint64().
Referenced by v8::internal::TypedArrayBuiltinsAssembler::CallCCopyFastNumberJSArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsSlice(), v8::internal::TypedArrayBuiltinsAssembler::CallCCopyTypedArrayElementsToTypedArray(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemmove(), v8::internal::TypedArrayBuiltinsAssembler::CallCMemset(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemcpy(), v8::internal::TypedArrayBuiltinsAssembler::CallCRelaxedMemmove(), v8::internal::CodeStubAssembler::CopyElements(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), v8::internal::CodeStubAssembler::FillFixedArrayWithSmiZero(), v8::internal::CodeStubAssembler::FillFixedDoubleArrayWithZero(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteLength(), v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewByteOffset(), v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles(), v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), v8::internal::CodeStubAssembler::MoveElements(), v8::internal::StringBuiltinsAssembler::SearchOneByteInOneByteString(), and v8::internal::TF_BUILTIN().
UnsignedBigInt64()
constexpr static MachineType v8::internal::MachineType::UnsignedBigInt64 () [inline], [static], [constexpr]
Definition at line 210 of file machine-type.h.
                                                  {
    return MachineType(MachineRepresentation::kWord64,
                       MachineSemantic::kUnsignedBigInt64);
  }
References v8::internal::kUnsignedBigInt64, v8::internal::kWord64, and MachineType().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), and v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf().
Member Data Documentation
representation_
MachineRepresentation v8::internal::MachineType::representation_ [private]
Definition at line 367 of file machine-type.h.
Referenced by representation().
semantic_
MachineSemantic v8::internal::MachineType::semantic_ [private]
Definition at line 368 of file machine-type.h.
Referenced by semantic().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/machine-type.h