v8::internal::compiler::SpillRange Class Reference
#include <register-allocator.h>
Public Member Functions
SpillRange (TopLevelLiveRange *range, Zone *zone)
SpillRange (const SpillRange &)=delete
SpillRange & operator= (const SpillRange &)=delete
bool IsEmpty () const
bool TryMerge (SpillRange *other)
bool HasSlot () const
void set_assigned_slot (int index)
int assigned_slot () const
int byte_width () const
void Print () const
Static Public Attributes
static const int kUnassignedSlot = -1
Private Attributes
ZoneVector< TopLevelLiveRange * > ranges_
ZoneVector< UseInterval > intervals_
int assigned_slot_
int byte_width_
Detailed Description
Definition at line 1300 of file register-allocator.h.
Constructor & Destructor Documentation
SpillRange() [1/2]
v8::internal::compiler::SpillRange::SpillRange (TopLevelLiveRange * range, Zone * zone)
Definition at line 1031 of file register-allocator.cc.
    : ranges_(zone),
      intervals_(zone),
      assigned_slot_(kUnassignedSlot),
      byte_width_(ByteWidthForStackSlot(parent->representation())) {
  DCHECK(!parent->IsEmpty());
  // Spill ranges are created for top level. This is so that, when merging
  // decisions are made, we consider the full extent of the virtual register,
  // and avoid clobbering it.
  LifetimePosition last_end = LifetimePosition::MaxPosition();
  for (const LiveRange* range = parent; range != nullptr;
       range = range->next()) {
    // Deep copy the `UseInterval`s, since the `LiveRange`s are subsequently
    // modified, so just storing those has correctness issues.
    for (UseInterval interval : range->intervals()) {
      DCHECK_NE(LifetimePosition::MaxPosition(), interval.start());
      bool can_coalesce = last_end == interval.start();
      if (can_coalesce) {
        intervals_.back().set_end(interval.end());
      } else {
        intervals_.push_back(interval);
      }
      last_end = interval.end();
    }
  }
  ranges_.push_back(parent);
  parent->SetSpillRange(this);
}
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::UseInterval::end(), intervals_, v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::compiler::LifetimePosition::MaxPosition(), v8::internal::compiler::LiveRange::next(), ranges_, v8::internal::compiler::TopLevelLiveRange::SetSpillRange(), and v8::internal::compiler::UseInterval::start().
SpillRange() [2/2]
v8::internal::compiler::SpillRange::SpillRange (const SpillRange &) [delete]
Member Function Documentation
assigned_slot()
int v8::internal::compiler::SpillRange::assigned_slot () const [inline]
Definition at line 1316 of file register-allocator.h.
                            {
    DCHECK_NE(kUnassignedSlot, assigned_slot_);
    return assigned_slot_;
  }
References assigned_slot_, DCHECK_NE, and kUnassignedSlot.
Referenced by v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), and v8::internal::compiler::operator<<().
byte_width()
int v8::internal::compiler::SpillRange::byte_width () const [inline]
Definition at line 1322 of file register-allocator.h.
{ return byte_width_; }
References byte_width_.
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), and TryMerge().
HasSlot()
bool v8::internal::compiler::SpillRange::HasSlot () const [inline]
Definition at line 1310 of file register-allocator.h.
{ return assigned_slot_ != kUnassignedSlot; }
References assigned_slot_, and kUnassignedSlot.
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), and TryMerge().
IsEmpty()
bool v8::internal::compiler::SpillRange::IsEmpty () const [inline]
Definition at line 1308 of file register-allocator.h.
{ return ranges_.empty(); }
References ranges_.
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots().
operator=()
SpillRange& v8::internal::compiler::SpillRange::operator= (const SpillRange &) [delete]
Print()
void v8::internal::compiler::SpillRange::Print () const
Definition at line 1135 of file register-allocator.cc.
                             {
  StdoutStream os;
  os << "{" << std::endl;
  for (const TopLevelLiveRange* range : ranges_) {
    os << range->vreg() << " ";
  }
  os << std::endl;
  for (const UseInterval& interval : intervals_) {
    interval.PrettyPrint(os);
    os << std::endl;
  }
  os << "}" << std::endl;
}
References intervals_, v8::internal::compiler::UseInterval::PrettyPrint(), and ranges_.
set_assigned_slot()
void v8::internal::compiler::SpillRange::set_assigned_slot (int index) [inline]
Definition at line 1312 of file register-allocator.h.
                                    {
    DCHECK_EQ(kUnassignedSlot, assigned_slot_);
    assigned_slot_ = index;
  }
References assigned_slot_, DCHECK_EQ, v8::internal::index, and kUnassignedSlot.
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), and v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges().
TryMerge()
bool v8::internal::compiler::SpillRange::TryMerge (SpillRange * other)
Definition at line 1108 of file register-allocator.cc.
                                           {
  if (HasSlot() || other->HasSlot()) return false;
  if (byte_width() != other->byte_width()) return false;
  if (AreUseIntervalsIntersecting(intervals_, other->intervals_)) return false;
  // Merge vectors of `UseInterval`s.
  intervals_.reserve(intervals_.size() + other->intervals_.size());
  for (UseInterval interval : other->intervals_) {
    UseInterval* insert_it =
        std::lower_bound(intervals_.begin(), intervals_.end(), interval);
    // Since the intervals didn't intersect, they should also be unique.
    DCHECK_IMPLIES(insert_it != intervals_.end(), *insert_it != interval);
    intervals_.insert(insert_it, 1, interval);
  }
  other->intervals_.clear();
  // Merge vectors of `TopLevelLiveRange`s.
  for (TopLevelLiveRange* range : other->ranges_) {
    DCHECK(range->GetSpillRange() == other);
    range->SetSpillRange(this);
  }
  ranges_.insert(ranges_.end(), other->ranges_.begin(), other->ranges_.end());
  other->ranges_.clear();
  return true;
}
References v8::internal::compiler::AreUseIntervalsIntersecting(), byte_width(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::TopLevelLiveRange::GetSpillRange(), HasSlot(), intervals_, ranges_, and v8::internal::compiler::TopLevelLiveRange::SetSpillRange().
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), and v8::internal::compiler::LiveRangeBundle::MergeSpillRangesAndClear().
Member Data Documentation
assigned_slot_
int v8::internal::compiler::SpillRange::assigned_slot_ [private]
Definition at line 1331 of file register-allocator.h.
Referenced by assigned_slot(), HasSlot(), and set_assigned_slot().
byte_width_
int v8::internal::compiler::SpillRange::byte_width_ [private]
Definition at line 1332 of file register-allocator.h.
Referenced by byte_width().
intervals_
ZoneVector<UseInterval> v8::internal::compiler::SpillRange::intervals_ [private]
Definition at line 1329 of file register-allocator.h.
Referenced by Print(), SpillRange(), and TryMerge().
kUnassignedSlot
const int v8::internal::compiler::SpillRange::kUnassignedSlot = -1 [static]
Definition at line 1302 of file register-allocator.h.
Referenced by assigned_slot(), HasSlot(), and set_assigned_slot().
ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::SpillRange::ranges_ [private]
Definition at line 1327 of file register-allocator.h.
Referenced by IsEmpty(), Print(), SpillRange(), and TryMerge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc