v8::internal::compiler::ZoneStats::Scope Class Reference
#include <zone-stats.h>
Public Member Functions
Scope (ZoneStats *zone_stats, const char *zone_name, bool support_zone_compression=false)
~Scope ()
Scope (const Scope &)=delete
Scope (Scope &&other) V8_NOEXCEPT
Scope & operator= (const Scope &)=delete
Scope & operator= (Scope &&other) V8_NOEXCEPT
Zone * zone ()
void Destroy ()
ZoneStats * zone_stats () const
Private Attributes
const char * zone_name_
ZoneStats * zone_stats_
Zone * zone_
bool support_zone_compression_
Detailed Description
Definition at line 19 of file zone-stats.h.
Constructor & Destructor Documentation
Scope() [1/3]
v8::internal::compiler::ZoneStats::Scope::Scope (ZoneStats * zone_stats, const char * zone_name, bool support_zone_compression = false) [inline], [explicit]
Definition at line 21 of file zone-stats.h.
        : zone_name_(zone_name),
          zone_stats_(zone_stats),
          zone_(nullptr),
          support_zone_compression_(support_zone_compression) {}
 Scope()
v8::internal::compiler::ZoneStats::Scope::~Scope () [inline]
Definition at line 27 of file zone-stats.h.
{ Destroy(); }
Scope() [2/3]
v8::internal::compiler::ZoneStats::Scope::Scope (const Scope &) [delete]
Scope() [3/3]
v8::internal::compiler::ZoneStats::Scope::Scope (Scope && other) [inline]
Definition at line 30 of file zone-stats.h.
        : zone_name_(other.zone_name_),
          zone_stats_(other.zone_stats_),
          zone_(nullptr),
          support_zone_compression_(other.support_zone_compression_) {
      std::swap(zone_, other.zone_);
    }
Member Function Documentation
Destroy()
void v8::internal::compiler::ZoneStats::Scope::Destroy () [inline]
Definition at line 52 of file zone-stats.h.
                   {
      if (zone_ != nullptr) zone_stats_->ReturnZone(zone_);
      zone_ = nullptr;
    }
Referenced by v8::internal::compiler::TFPipelineData::DeleteCodegenZone(), v8::internal::compiler::TFPipelineData::DeleteInstructionZone(), v8::internal::compiler::TFPipelineData::DeleteRegisterAllocationZone(), and v8::internal::compiler::turboshaft::ZoneWithName< Name >::Destroy().
operator=() [1/2]
Scope& v8::internal::compiler::ZoneStats::Scope::operator= (const Scope &) [delete]
operator=() [2/2]
Scope& v8::internal::compiler::ZoneStats::Scope::operator= (Scope && other) [inline]
Definition at line 38 of file zone-stats.h.
                                                {
      Destroy();
      zone_name_ = other.zone_name_;
      zone_stats_ = other.zone_stats_;
      support_zone_compression_ = other.support_zone_compression_;
      DCHECK_NULL(zone_);
      std::swap(zone_, other.zone_);
      return *this;
    }
References DCHECK_NULL.
zone()
Zone* v8::internal::compiler::ZoneStats::Scope::zone () [inline]
Definition at line 48 of file zone-stats.h.
                 {
      if (zone_ == nullptr) zone_ = zone_stats_->NewEmptyZone(zone_name_);
      return zone_;
    }
Referenced by v8::internal::compiler::turboshaft::ZoneWithName< Name >::get().
zone_stats()
ZoneStats* v8::internal::compiler::ZoneStats::Scope::zone_stats () const [inline]
Definition at line 57 of file zone-stats.h.
{ return zone_stats_; }
Member Data Documentation
support_zone_compression_
bool v8::internal::compiler::ZoneStats::Scope::support_zone_compression_ [private]
Definition at line 63 of file zone-stats.h.
zone_
Zone* v8::internal::compiler::ZoneStats::Scope::zone_ [private]
Definition at line 62 of file zone-stats.h.
zone_name_
const char* v8::internal::compiler::ZoneStats::Scope::zone_name_ [private]
Definition at line 60 of file zone-stats.h.
zone_stats_
ZoneStats* v8::internal::compiler::ZoneStats::Scope::zone_stats_ [private]
Definition at line 61 of file zone-stats.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/zone-stats.h