v8::internal::wasm::gdb_server::Packet Class Reference
#include <packet.h>
Public Types
enum class ErrDef { None = 0
, BadFormat = 1
, BadArgs = 2
, Failed = 3
 }
Public Member Functions
Packet ()
void Clear ()
void Rewind ()
bool EndOfPacket () const
void AddRawChar (char ch)
void AddBlock (const void *ptr, uint32_t len)
void AddWord8 (uint8_t val)
void AddNumberSep (uint64_t val, char sep)
void AddString (const char *str)
void AddHexString (const char *str)
bool GetRawChar (char *ch)
bool GetBlock (void *ptr, uint32_t len)
bool GetWord8 (uint8_t *val)
bool GetNumberSep (uint64_t *val, char *sep)
bool GetString (std::string *str)
bool GetHexString (std::string *str)
const char * GetPayload () const
size_t GetPayloadSize () const
bool GetSequence (int32_t *seq) const
void ParseSequence ()
void SetSequence (int32_t seq)
void SetError (ErrDef)
std::string GetPacketData () const
Private Attributes
int32_t seq_
std::string data_
size_t read_index_
Detailed Description
Definition at line 17 of file packet.h.
Member Enumeration Documentation
ErrDef
enum v8::internal::wasm::gdb_server::Packet::ErrDef [strong]
Enumerator
None
BadFormat
BadArgs
Failed
Definition at line 85 of file packet.h.
{ None = 0, BadFormat = 1, BadArgs = 2, Failed = 3 };
Constructor & Destructor Documentation
Packet()
v8::internal::wasm::gdb_server::Packet::Packet ()
Definition at line 13 of file packet.cc.
               {
  seq_ = -1;
  Clear();
}
References Clear(), and seq_.
Member Function Documentation
AddBlock()
void v8::internal::wasm::gdb_server::Packet::AddBlock (const void * ptr, uint32_t len)
Definition at line 36 of file packet.cc.
                                                   {
  DCHECK(ptr);
  const char* p = (const char*)ptr;
  for (uint32_t offs = 0; offs < len; offs++) {
    AddWord8(p[offs]);
  }
}
References AddWord8(), and v8::internal::DCHECK().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket(), and v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
AddHexString()
void v8::internal::wasm::gdb_server::Packet::AddHexString (const char * str)
Definition at line 55 of file packet.cc.
                                         {
  DCHECK(str);
  while (*str) {
    AddWord8(*str);
    str++;
  }
}
References AddWord8(), and v8::internal::DCHECK().
AddNumberSep()
void v8::internal::wasm::gdb_server::Packet::AddNumberSep (uint64_t val, char sep)
Definition at line 64 of file packet.cc.
                                                {
  char out[sizeof(val) * 2];
  char temp[2];
  // Check for -1 optimization
  if (val == static_cast<uint64_t>(-1)) {
    AddRawChar('-');
    AddRawChar('1');
  } else {
    int nibbles = 0;
    // In the GDB remote protocol numbers are formatted as big-endian hex
    // strings. Leading zeros can be skipped.
    // For example the value 0x00001234 is formatted as "1234".
    for (size_t a = 0; a < sizeof(val); a++) {
      uint8_t byte = static_cast<uint8_t>(val & 0xFF);
      // Stream in with bytes reversed, starting with the least significant.
      // So if we have the value 0x00001234, we store 4, then 3, 2, 1.
      // Note that the characters are later reversed to be in big-endian order.
      UInt8ToHex(byte, temp);
      out[nibbles++] = temp[1];
      out[nibbles++] = temp[0];
      // Get the next 8 bits;
      val >>= 8;
      // Suppress leading zeros, so we are done when val hits zero
      if (val == 0) {
        break;
      }
    }
    // Strip the high zero for this byte if present.
    if ((nibbles > 1) && (out[nibbles - 1] == '0')) nibbles--;
    // Now write it out reverse to correct the order
    while (nibbles) {
      nibbles--;
      AddRawChar(out[nibbles]);
    }
  }
  // If we asked for a separator, insert it
  if (sep) AddRawChar(sep);
}
References AddRawChar(), and v8::internal::wasm::gdb_server::UInt8ToHex().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessQueryPacket(), and v8::internal::wasm::gdb_server::Target::SetStopReply().
AddRawChar()
void v8::internal::wasm::gdb_server::Packet::AddRawChar (char ch)
Definition at line 27 of file packet.cc.
{ data_.push_back(ch); }
References data_.
Referenced by AddNumberSep(), AddString(), AddWord8(), v8::internal::wasm::gdb_server::Session::GetPayload(), v8::internal::wasm::gdb_server::Target::ProcessPacket(), SetError(), and v8::internal::wasm::gdb_server::Target::SetStopReply().
AddString()
void v8::internal::wasm::gdb_server::Packet::AddString (const char * str)
Definition at line 46 of file packet.cc.
                                      {
  DCHECK(str);
  while (*str) {
    AddRawChar(*str);
    str++;
  }
}
References AddRawChar(), and v8::internal::DCHECK().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket(), v8::internal::wasm::gdb_server::Target::ProcessQueryPacket(), and v8::internal::wasm::gdb_server::Target::SetStopReply().
AddWord8()
void v8::internal::wasm::gdb_server::Packet::AddWord8 (uint8_t val)
Definition at line 29 of file packet.cc.
                                  {
  char seq[2];
  UInt8ToHex(byte, seq);
  AddRawChar(seq[0]);
  AddRawChar(seq[1]);
}
References AddRawChar(), and v8::internal::wasm::gdb_server::UInt8ToHex().
Referenced by AddBlock(), AddHexString(), v8::internal::wasm::gdb_server::Target::ProcessPacket(), SetError(), and v8::internal::wasm::gdb_server::Target::SetStopReply().
Clear()
void v8::internal::wasm::gdb_server::Packet::Clear ()
Definition at line 18 of file packet.cc.
                   {
  data_.clear();
  read_index_ = 0;
}
References data_, and read_index_.
Referenced by v8::internal::wasm::gdb_server::Session::GetPayload(), Packet(), v8::internal::wasm::gdb_server::Target::ProcessCommands(), v8::internal::wasm::gdb_server::Target::ProcessPacket(), and SetError().
EndOfPacket()
bool v8::internal::wasm::gdb_server::Packet::EndOfPacket () const
Definition at line 25 of file packet.cc.
{ return (read_index_ >= GetPayloadSize()); }
References GetPayloadSize(), and read_index_.
Referenced by GetHexString(), and GetString().
GetBlock()
bool v8::internal::wasm::gdb_server::Packet::GetBlock (void * ptr, uint32_t len)
Definition at line 232 of file packet.cc.
                                             {
  DCHECK(ptr);
  uint8_t* p = reinterpret_cast<uint8_t*>(ptr);
  bool res = true;
  for (uint32_t offs = 0; offs < len; offs++) {
    res = GetWord8(&p[offs]);
    if (false == res) {
      break;
    }
  }
  return res;
}
References v8::internal::DCHECK(), and GetWord8().
GetHexString()
bool v8::internal::wasm::gdb_server::Packet::GetHexString (std::string * str)
Definition at line 258 of file packet.cc.
                                        {
  // Decode a string encoded as a series of 2-hex digit pairs.
  if (EndOfPacket()) {
    return false;
  }
  // Pull values until we hit a separator
  str->clear();
  char ch1;
  while (GetRawChar(&ch1)) {
    uint8_t nib1;
    if (!NibbleToUInt8(ch1, &nib1)) {
      read_index_--;
      break;
    }
    char ch2;
    uint8_t nib2;
    if (!GetRawChar(&ch2) || !NibbleToUInt8(ch2, &nib2)) {
      return false;
    }
    *str += static_cast<char>((nib1 << 4) + nib2);
  }
  return true;
}
References EndOfPacket(), GetRawChar(), v8::internal::wasm::gdb_server::NibbleToUInt8(), and read_index_.
GetNumberSep()
bool v8::internal::wasm::gdb_server::Packet::GetNumberSep (uint64_t * val, char * sep)
Definition at line 111 of file packet.cc.
                                                  {
  uint64_t out = 0;
  char ch;
  if (!GetRawChar(&ch)) {
    return false;
  }
  // Numbers are formatted as a big-endian hex strings.
  // The literals "0" and "-1" as special cases.
  // Check for -1
  if (ch == '-') {
    if (!GetRawChar(&ch)) {
      return false;
    }
    if (ch == '1') {
      *val = (uint64_t)-1;
      ch = 0;
      GetRawChar(&ch);
      if (sep) {
        *sep = ch;
      }
      return true;
    }
    return false;
  }
  do {
    uint8_t nib;
    // Check for separator
    if (!NibbleToUInt8(ch, &nib)) {
      break;
    }
    // Add this nibble.
    out = (out << 4) + nib;
    // Get the next character (if availible)
    ch = 0;
    if (!GetRawChar(&ch)) {
      break;
    }
  } while (1);
  // Set the value;
  *val = out;
  // Add the separator if the user wants it...
  if (sep != nullptr) *sep = ch;
  return true;
}
References GetRawChar(), and v8::internal::wasm::gdb_server::NibbleToUInt8().
Referenced by v8::internal::wasm::gdb_server::Target::ProcessPacket().
GetPacketData()
std::string v8::internal::wasm::gdb_server::Packet::GetPacketData () const
Definition at line 321 of file packet.cc.
                                      {
  char chars[2];
  const char* ptr = GetPayload();
  size_t size = GetPayloadSize();
  std::stringstream outstr;
  // Signal start of response
  outstr << '$';
  char run_xsum = 0;
  // If there is a sequence, send as two nibble 8bit value + ':'
  int32_t seq;
  if (GetSequence(&seq)) {
    UInt8ToHex(seq, chars);
    outstr << chars[0];
    run_xsum += chars[0];
    outstr << chars[1];
    run_xsum += chars[1];
    outstr << ':';
    run_xsum += ':';
  }
  // Send the main payload
  for (size_t offs = 0; offs < size; ++offs) {
    outstr << ptr[offs];
    run_xsum += ptr[offs];
  }
  // Send XSUM as two nibble 8bit value preceeded by '#'
  outstr << '#';
  UInt8ToHex(run_xsum, chars);
  outstr << chars[0];
  outstr << chars[1];
  return outstr.str();
}
References GetPayload(), GetPayloadSize(), GetSequence(), size(), and v8::internal::wasm::gdb_server::UInt8ToHex().
Referenced by v8::internal::wasm::gdb_server::Session::SendPacket().
GetPayload()
const char * v8::internal::wasm::gdb_server::Packet::GetPayload () const
Definition at line 284 of file packet.cc.
{ return data_.c_str(); }
References data_.
Referenced by v8::internal::wasm::gdb_server::Session::GetPacket(), GetPacketData(), v8::internal::wasm::gdb_server::Target::ProcessPacket(), and v8::internal::wasm::gdb_server::Target::ProcessQueryPacket().
GetPayloadSize()
size_t v8::internal::wasm::gdb_server::Packet::GetPayloadSize () const
Definition at line 286 of file packet.cc.
{ return data_.size(); }
References data_.
Referenced by EndOfPacket(), GetPacketData(), GetRawChar(), and GetString().
GetRawChar()
bool v8::internal::wasm::gdb_server::Packet::GetRawChar (char * ch)
Definition at line 167 of file packet.cc.
                                {
  DCHECK(ch != nullptr);
  if (read_index_ >= GetPayloadSize()) return false;
  *ch = data_[read_index_++];
  // Check for RLE X*N, where X is the value, N is the reps.
  if (*ch == '*') {
    if (read_index_ < 2) {
      TRACE_GDB_REMOTE("Unexpected RLE at start of packet.\n");
      return false;
    }
    if (read_index_ >= GetPayloadSize()) {
      TRACE_GDB_REMOTE("Unexpected EoP during RLE.\n");
      return false;
    }
    // GDB does not use "CTRL" characters in the stream, so the
    // number of reps is encoded as the ASCII value beyond 28
    // (which when you add a min rep size of 4, forces the rep
    // character to be ' ' (32) or greater).
    int32_t cnt = (data_[read_index_] - 28);
    if (cnt < 3) {
      TRACE_GDB_REMOTE("Unexpected RLE length.\n");
      return false;
    }
    // We have just read '*' and incremented the read pointer,
    // so here is the old state, and expected new state.
    //
    // Assume N = 5, we grow by N - size of encoding (3).
    //
    // OldP: R W
    // OldD: 012X*N89 = 8 chars
    // Size: 012X*N89__ = 10 chars
    // Move: 012X*__N89 = 10 chars
    // Fill: 012XXXXX89 = 10 chars
    // NewP: R W (shifted 5 - 3)
    // First, store the remaining characters to the right into a temp string.
    std::string right = data_.substr(read_index_ + 1);
    // Discard the '*' we just read
    data_.erase(read_index_ - 1);
    // Append (N-1) 'X' chars
    *ch = data_[read_index_ - 2];
    data_.append(cnt - 1, *ch);
    // Finally, append the remaining characters
    data_.append(right);
  }
  return true;
}
References data_, v8::internal::DCHECK(), GetPayloadSize(), read_index_, v8::internal::string, and TRACE_GDB_REMOTE.
Referenced by GetHexString(), GetNumberSep(), GetWord8(), ParseSequence(), and v8::internal::wasm::gdb_server::Target::ProcessPacket().
GetSequence()
bool v8::internal::wasm::gdb_server::Packet::GetSequence (int32_t * seq) const
Definition at line 288 of file packet.cc.
                                          {
  DCHECK(ch);
  if (seq_ != -1) {
    *ch = seq_;
    return true;
  }
  return false;
}
References v8::internal::DCHECK(), and seq_.
Referenced by v8::internal::wasm::gdb_server::Session::GetPacket(), GetPacketData(), and v8::internal::wasm::gdb_server::Target::ProcessPacket().
GetString()
bool v8::internal::wasm::gdb_server::Packet::GetString (std::string * str)
Definition at line 248 of file packet.cc.
                                     {
  if (EndOfPacket()) {
    return false;
  }
  *str = data_.substr(read_index_);
  read_index_ = GetPayloadSize();
  return true;
}
References data_, EndOfPacket(), GetPayloadSize(), and read_index_.
GetWord8()
bool v8::internal::wasm::gdb_server::Packet::GetWord8 (uint8_t * val)
Definition at line 221 of file packet.cc.
                                    {
  DCHECK(value);
  // Get two ASCII hex values and convert them to ints
  char seq[2];
  if (!GetRawChar(&seq[0]) || !GetRawChar(&seq[1])) {
    return false;
  }
  return HexToUInt8(seq, value);
}
References v8::internal::DCHECK(), GetRawChar(), v8::internal::wasm::gdb_server::HexToUInt8(), and v8::internal::value.
Referenced by GetBlock(), and ParseSequence().
ParseSequence()
void v8::internal::wasm::gdb_server::Packet::ParseSequence ()
Definition at line 299 of file packet.cc.
                           {
  size_t saved_read_index = read_index_;
  unsigned char seq;
  char ch;
  if (GetWord8(&seq) && GetRawChar(&ch)) {
    if (ch == ':') {
      SetSequence(seq);
      return;
    }
  }
  // No sequence number present, so reset to original position.
  read_index_ = saved_read_index;
}
References GetRawChar(), GetWord8(), read_index_, and SetSequence().
Referenced by v8::internal::wasm::gdb_server::Session::GetPacket().
Rewind()
void v8::internal::wasm::gdb_server::Packet::Rewind ()
Definition at line 23 of file packet.cc.
{ read_index_ = 0; }
References read_index_.
SetError()
void v8::internal::wasm::gdb_server::Packet::SetError (ErrDef error)
Definition at line 315 of file packet.cc.
                                  {
  Clear();
  AddRawChar('E');
  AddWord8(static_cast<uint8_t>(error));
}
References AddRawChar(), AddWord8(), and Clear().
SetSequence()
void v8::internal::wasm::gdb_server::Packet::SetSequence (int32_t seq)
Definition at line 313 of file packet.cc.
{ seq_ = val; }
References seq_.
Referenced by ParseSequence(), and v8::internal::wasm::gdb_server::Target::ProcessPacket().
Member Data Documentation
data_
std::string v8::internal::wasm::gdb_server::Packet::data_ [private]
Definition at line 96 of file packet.h.
Referenced by AddRawChar(), Clear(), GetPayload(), GetPayloadSize(), GetRawChar(), and GetString().
read_index_
size_t v8::internal::wasm::gdb_server::Packet::read_index_ [private]
Definition at line 97 of file packet.h.
Referenced by Clear(), EndOfPacket(), GetHexString(), GetRawChar(), GetString(), ParseSequence(), and Rewind().
seq_
int32_t v8::internal::wasm::gdb_server::Packet::seq_ [private]
Definition at line 95 of file packet.h.
Referenced by GetSequence(), Packet(), and SetSequence().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/packet.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/packet.cc