v8::internal::ConstructEntryFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< HeapObject > unchecked_code () const override
Static Public Member Functions
static ConstructEntryFrame * cast (StackFrame *frame)
Protected Member Functions
ConstructEntryFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 878 of file frames.h.
Constructor & Destructor Documentation
ConstructEntryFrame()
v8::internal::ConstructEntryFrame::ConstructEntryFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 133 of file frames-inl.h.
    : EntryFrame(iterator) {}
Member Function Documentation
cast()
static ConstructEntryFrame* v8::internal::ConstructEntryFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 884 of file frames.h.
                                                      {
    DCHECK(frame->is_construct_entry());
    return static_cast<ConstructEntryFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_construct_entry().
type()
Type v8::internal::ConstructEntryFrame::type () const [inline], [override], [virtual]
Reimplemented from v8::internal::EntryFrame.
Definition at line 880 of file frames.h.
{ return CONSTRUCT_ENTRY; }
References CONSTRUCT_ENTRY.
unchecked_code()
Tagged< HeapObject > v8::internal::ConstructEntryFrame::unchecked_code () const [override], [virtual]
Reimplemented from v8::internal::EntryFrame.
Definition at line 1129 of file frames.cc.
                                                             {
  return isolate()->builtins()->code(Builtin::kJSConstructEntry);
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), and v8::internal::StackFrame::isolate().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 893 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc