cppgc::internal::FreeList::Entry Class Reference
Public Member Functions
Entry * Next () const
void SetNext (Entry *next)
void Link (Entry **previous_next)
void Unlink (Entry **previous_next)
Static Public Member Functions
static Entry & CreateAt (void *memory, size_t size)
Private Member Functions
Entry (size_t size)
Private Attributes
Entry * next_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 25 of file free-list.cc.
Constructor & Destructor Documentation
Entry()
cppgc::internal::FreeList::Entry::Entry (size_t size) [inline], [explicit], [private]
Definition at line 47 of file free-list.cc.
                              : HeapObjectHeader(size, kFreeListGCInfoIndex) {
    static_assert(sizeof(Entry) == kFreeListEntrySize, "Sizes must match");
  }
References cppgc::internal::kFreeListEntrySize.
Referenced by CreateAt().
Member Function Documentation
CreateAt()
static Entry& cppgc::internal::FreeList::Entry::CreateAt (void * memory, size_t size) [inline], [static]
Definition at line 27 of file free-list.cc.
                                                    {
    // Make sure the freelist header is writable. SET_MEMORY_ACCESSIBLE is not
    // needed as we write the whole payload of Entry.
    ASAN_UNPOISON_MEMORY_REGION(memory, sizeof(Entry));
    return *new (memory) Entry(size);
  }
References ASAN_UNPOISON_MEMORY_REGION, Entry(), and size().
Referenced by cppgc::internal::FreeList::AddReturningUnusedBounds().
Link()
void cppgc::internal::FreeList::Entry::Link (Entry ** previous_next) [inline]
Definition at line 37 of file free-list.cc.
                                   {
    next_ = *previous_next;
    *previous_next = this;
  }
References next_.
Referenced by cppgc::internal::FreeList::AddReturningUnusedBounds().
Next()
Entry* cppgc::internal::FreeList::Entry::Next () const [inline]
Definition at line 34 of file free-list.cc.
{ return next_; }
References next_.
Referenced by cppgc::internal::FreeList::AddReturningUnusedBounds(), cppgc::internal::FreeList::Allocate(), and cppgc::internal::FreeList::ContainsForTesting().
SetNext()
void cppgc::internal::FreeList::Entry::SetNext (Entry * next) [inline]
Definition at line 35 of file free-list.cc.
{ next_ = next; }
References next_.
Referenced by cppgc::internal::FreeList::Append().
Unlink()
void cppgc::internal::FreeList::Entry::Unlink (Entry ** previous_next) [inline]
Definition at line 41 of file free-list.cc.
                                     {
    *previous_next = next_;
    next_ = nullptr;
  }
References next_.
Referenced by cppgc::internal::FreeList::Allocate().
Member Data Documentation
next_
Entry* cppgc::internal::FreeList::Entry::next_ = nullptr [private]
Definition at line 51 of file free-list.cc.
Referenced by Link(), Next(), SetNext(), and Unlink().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/free-list.cc