v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency Class Reference
Public Member Functions
ElementsKindDependency (AllocationSiteRef site, ElementsKind kind)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const AllocationSiteRef site_
const ElementsKind kind_
Additional Inherited Members
Detailed Description
Definition at line 1042 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
ElementsKindDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::ElementsKindDependency (AllocationSiteRef site, ElementsKind kind) [inline]
Definition at line 1044 of file compilation-dependencies.cc.
      : CompilationDependency(kElementsKind), site_(site), kind_(kind) {
    DCHECK(AllocationSite::ShouldTrack(kind_));
  }
References v8::internal::DCHECK(), and v8::internal::AllocationSite::ShouldTrack().
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1069 of file compilation-dependencies.cc.
                                                                {
    const ElementsKindDependency* const zat = that->AsElementsKind();
    return site_.equals(zat->site_) && kind_ == zat->kind_;
  }
References kind_, and site_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1064 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(site_), static_cast<int>(kind_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 1057 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(site_.object(),
                   DependentCode::kAllocationSiteTransitionChangedGroup);
  }
References broker(), v8::internal::DependentCode::kAllocationSiteTransitionChangedGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1049 of file compilation-dependencies.cc.
                                                    {
    DirectHandle<AllocationSite> site = site_.object();
    ElementsKind kind =
        site->PointsToLiteral()
            ? site->boilerplate(kAcquireLoad)->map()->elements_kind()
            : site->GetElementsKind();
    return kind_ == kind;
  }
References v8::kAcquireLoad.
Member Data Documentation
kind_
const ElementsKind v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::kind_ [private]
Definition at line 1075 of file compilation-dependencies.cc.
Referenced by Equals().
site_
const AllocationSiteRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ElementsKindDependency::site_ [private]
Definition at line 1074 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc