v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator Class Reference
Static Public Member Functions
static void VisitText (TextNode *that)
static void VisitAction (ActionNode *that)
static void VisitChoice (ChoiceNode *that, int i)
static void VisitLoopChoiceContinueNode (LoopChoiceNode *that)
static void VisitLoopChoiceLoopNode (LoopChoiceNode *that)
static void VisitNegativeLookaroundChoiceLookaroundNode (NegativeLookaroundChoiceNode *that)
static void VisitNegativeLookaroundChoiceContinueNode (NegativeLookaroundChoiceNode *that)
static void VisitBackReference (BackReferenceNode *that)
static void VisitAssertion (AssertionNode *that)
Detailed Description
Definition at line 3645 of file regexp-compiler.cc.
Member Function Documentation
VisitAction()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitAction (ActionNode * that) [inline], [static]
Definition at line 3649 of file regexp-compiler.cc.
                                            {
    // If the next node is interested in what it follows then this node
    // has to be interested too so it can pass the information on.
    that->info()->AddFromFollowing(that->on_success()->info());
  }
References v8::internal::NodeInfo::AddFromFollowing(), v8::internal::RegExpNode::info(), and v8::internal::SeqRegExpNode::on_success().
VisitAssertion()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitAssertion (AssertionNode * that) [inline], [static]
Definition at line 3681 of file regexp-compiler.cc.
{}
VisitBackReference()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitBackReference (BackReferenceNode * that) [inline], [static]
Definition at line 3679 of file regexp-compiler.cc.
{}
VisitChoice()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitChoice (ChoiceNode * that, int i) [inline], [static]
Definition at line 3655 of file regexp-compiler.cc.
                                                   {
    // Anything the following nodes need to know has to be known by
    // this node also, so it can pass it on.
    that->info()->AddFromFollowing(that->alternatives()->at(i).node()->info());
  }
References v8::internal::NodeInfo::AddFromFollowing(), v8::internal::ChoiceNode::alternatives(), and v8::internal::RegExpNode::info().
VisitLoopChoiceContinueNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitLoopChoiceContinueNode (LoopChoiceNode * that) [inline], [static]
Definition at line 3661 of file regexp-compiler.cc.
                                                                {
    that->info()->AddFromFollowing(that->continue_node()->info());
  }
References v8::internal::NodeInfo::AddFromFollowing(), v8::internal::LoopChoiceNode::continue_node(), and v8::internal::RegExpNode::info().
VisitLoopChoiceLoopNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitLoopChoiceLoopNode (LoopChoiceNode * that) [inline], [static]
Definition at line 3665 of file regexp-compiler.cc.
                                                            {
    that->info()->AddFromFollowing(that->loop_node()->info());
  }
References v8::internal::NodeInfo::AddFromFollowing(), v8::internal::RegExpNode::info(), and v8::internal::LoopChoiceNode::loop_node().
VisitNegativeLookaroundChoiceContinueNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitNegativeLookaroundChoiceContinueNode (NegativeLookaroundChoiceNode * that) [inline], [static]
Definition at line 3674 of file regexp-compiler.cc.
                                          {
    VisitChoice(that, NegativeLookaroundChoiceNode::kContinueIndex);
  }
References v8::internal::NegativeLookaroundChoiceNode::kContinueIndex.
VisitNegativeLookaroundChoiceLookaroundNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitNegativeLookaroundChoiceLookaroundNode (NegativeLookaroundChoiceNode * that) [inline], [static]
Definition at line 3669 of file regexp-compiler.cc.
                                          {
    VisitChoice(that, NegativeLookaroundChoiceNode::kLookaroundIndex);
  }
References v8::internal::NegativeLookaroundChoiceNode::kLookaroundIndex.
VisitText()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitText (TextNode * that) [inline], [static]
Definition at line 3647 of file regexp-compiler.cc.
{}
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc