v8::internal::maglev::LazyDeoptInfo Class Reference
#include <maglev-ir.h>
Public Member Functions
LazyDeoptInfo (Zone *zone, const DeoptFrame top_frame, interpreter::Register result_location, int result_size, compiler::FeedbackSource feedback_to_update)
interpreter::Register result_location () const
int result_size () const
bool IsResultRegister (interpreter::Register reg) const
bool HasResultLocation () const
const InterpretedDeoptFrame & GetFrameForExceptionHandler (const ExceptionHandlerInfo *handler_info)
int deopting_call_return_pc () const
void set_deopting_call_return_pc (int pc)
template<typename Function >
void ForEachInput (Function &&f)
template<typename Function >
void ForEachInput (Function &&f) const
Static Public Member Functions
static bool InReturnValues (interpreter::Register reg, interpreter::Register result_location, int result_size)
Private Types
using DeoptingCallReturnPcField = base::BitField< unsigned int, 0, 30 >
using ResultSizeField = DeoptingCallReturnPcField::Next< unsigned int, 2 >
Private Attributes
interpreter::Register result_location_
uint32_t bitfield_
Static Private Attributes
static constexpr int kMaxCodeSize = 512 * MB
static constexpr unsigned int kUninitializedCallReturnPc
Additional Inherited Members
Detailed Description
Definition at line 1885 of file maglev-ir.h.
Member Typedef Documentation
DeoptingCallReturnPcField
using v8::internal::maglev::LazyDeoptInfo::DeoptingCallReturnPcField = base::BitField<unsigned int, 0, 30> [private]
Definition at line 1960 of file maglev-ir.h.
ResultSizeField
using v8::internal::maglev::LazyDeoptInfo::ResultSizeField = DeoptingCallReturnPcField::Next<unsigned int, 2> [private]
Definition at line 1961 of file maglev-ir.h.
Constructor & Destructor Documentation
LazyDeoptInfo()
v8::internal::maglev::LazyDeoptInfo::LazyDeoptInfo (Zone * zone, const DeoptFrame top_frame, interpreter::Register result_location, int result_size, compiler::FeedbackSource feedback_to_update) [inline]
Definition at line 1887 of file maglev-ir.h.
      : DeoptInfo(zone, top_frame, feedback_to_update),
        result_location_(result_location),
        bitfield_(
            DeoptingCallReturnPcField::encode(kUninitializedCallReturnPc) |
            ResultSizeField::encode(result_size)) {}
Member Function Documentation
deopting_call_return_pc()
int v8::internal::maglev::LazyDeoptInfo::deopting_call_return_pc () const [inline]
Definition at line 1914 of file maglev-ir.h.
                                      {
    DCHECK_NE(DeoptingCallReturnPcField::decode(bitfield_),
              kUninitializedCallReturnPc);
    return DeoptingCallReturnPcField::decode(bitfield_);
  }
References bitfield_, DCHECK_NE, v8::base::BitField< T, shift, size, U >::decode(), and kUninitializedCallReturnPc.
ForEachInput() [1/2]
template<typename Function >
void v8::internal::maglev::LazyDeoptInfo::ForEachInput (Function && f)
Definition at line 123 of file maglev-deopt-frame-visitor.h.
                                             {
  DeoptInfoVisitor<LazyDeoptInfo>::ForLazy(this, f);
}
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateLazyDeopt(), and v8::internal::maglev::SweepIdentityNodes::Process().
ForEachInput() [2/2]
template<typename Function >
void v8::internal::maglev::LazyDeoptInfo::ForEachInput (Function && f) const
Definition at line 128 of file maglev-deopt-frame-visitor.h.
                                                   {
  DeoptInfoVisitor<const LazyDeoptInfo>::ForLazy(this, f);
}
GetFrameForExceptionHandler()
const InterpretedDeoptFrame & v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler (const ExceptionHandlerInfo * handler_info)
Definition at line 436 of file maglev-ir.cc.
                                              {
  const DeoptFrame* target_frame = &top_frame();
  for (int i = 0;; i++) {
    while (target_frame->type() != DeoptFrame::FrameType::kInterpretedFrame) {
      target_frame = target_frame->parent();
    }
    if (i == handler_info->depth()) break;
    target_frame = target_frame->parent();
  }
  return target_frame->as_interpreted();
}
References v8::internal::maglev::DeoptFrame::as_interpreted(), v8::internal::maglev::ExceptionHandlerInfo::depth(), v8::internal::maglev::DeoptFrame::kInterpretedFrame, v8::internal::maglev::DeoptFrame::parent(), v8::internal::maglev::DeoptInfo::top_frame(), and v8::internal::maglev::DeoptFrame::type().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
HasResultLocation()
bool v8::internal::maglev::LazyDeoptInfo::HasResultLocation () const [inline]
Definition at line 1906 of file maglev-ir.h.
                                 {
    DCHECK(IsConsideredForResultLocation());
    return result_location_.is_valid();
  }
References v8::internal::DCHECK(), v8::internal::interpreter::Register::is_valid(), and result_location_.
InReturnValues()
bool v8::internal::maglev::LazyDeoptInfo::InReturnValues (interpreter::Register reg, interpreter::Register result_location, int result_size) [static]
Definition at line 403 of file maglev-ir.cc.
                                                    {
  if (result_size == 0 || !result_location.is_valid()) {
    return false;
  }
  return base::IsInRange(reg.index(), result_location.index(),
                         result_location.index() + result_size - 1);
}
References v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_valid(), result_location(), and result_size().
IsResultRegister()
bool v8::internal::maglev::LazyDeoptInfo::IsResultRegister (interpreter::Register reg) const
Definition at line 388 of file maglev-ir.cc.
                                                                  {
  if (top_frame().type() == DeoptFrame::FrameType::kConstructInvokeStubFrame) {
    return reg == interpreter::Register::virtual_accumulator();
  }
  if (V8_LIKELY(result_size() == 1)) {
    return reg == result_location_;
  }
  if (result_size() == 0) {
    return false;
  }
  DCHECK_EQ(result_size(), 2);
  return reg == result_location_ ||
         reg == interpreter::Register(result_location_.index() + 1);
}
References DCHECK_EQ, v8::internal::interpreter::Register::index(), v8::internal::maglev::DeoptFrame::kConstructInvokeStubFrame, v8::internal::ETWJITInterface::Register(), result_location_, result_size(), v8::internal::maglev::DeoptInfo::top_frame(), v8::internal::tracing::type, V8_LIKELY, and v8::internal::interpreter::Register::virtual_accumulator().
result_location()
interpreter::Register v8::internal::maglev::LazyDeoptInfo::result_location () const [inline]
Definition at line 1896 of file maglev-ir.h.
                                              {
    DCHECK(IsConsideredForResultLocation());
    return result_location_;
  }
References v8::internal::DCHECK(), and result_location_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), and InReturnValues().
result_size()
int v8::internal::maglev::LazyDeoptInfo::result_size () const [inline]
Definition at line 1900 of file maglev-ir.h.
                          {
    DCHECK(IsConsideredForResultLocation());
    return ResultSizeField::decode(bitfield_);
  }
References bitfield_, v8::internal::DCHECK(), and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt(), InReturnValues(), and IsResultRegister().
set_deopting_call_return_pc()
void v8::internal::maglev::LazyDeoptInfo::set_deopting_call_return_pc (int pc) [inline]
Definition at line 1919 of file maglev-ir.h.
                                           {
    DCHECK_EQ(DeoptingCallReturnPcField::decode(bitfield_),
              kUninitializedCallReturnPc);
    bitfield_ = DeoptingCallReturnPcField::update(bitfield_, pc);
  }
References bitfield_, DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), kUninitializedCallReturnPc, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::maglev::MaglevAssembler::DefineLazyDeoptPoint(), and v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt().
Member Data Documentation
bitfield_
uint32_t v8::internal::maglev::LazyDeoptInfo::bitfield_ [private]
Definition at line 1977 of file maglev-ir.h.
Referenced by deopting_call_return_pc(), result_size(), and set_deopting_call_return_pc().
kMaxCodeSize
constexpr int v8::internal::maglev::LazyDeoptInfo::kMaxCodeSize = 512 * MB [static], [constexpr], [private]
Definition at line 1966 of file maglev-ir.h.
kUninitializedCallReturnPc
constexpr unsigned int v8::internal::maglev::LazyDeoptInfo::kUninitializedCallReturnPc [static], [constexpr], [private]
Initial value:
=
      DeoptingCallReturnPcField::kMax
Definition at line 1967 of file maglev-ir.h.
Referenced by deopting_call_return_pc(), and set_deopting_call_return_pc().
result_location_
interpreter::Register v8::internal::maglev::LazyDeoptInfo::result_location_ [private]
Definition at line 1976 of file maglev-ir.h.
Referenced by HasResultLocation(), IsResultRegister(), and result_location().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-deopt-frame-visitor.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc