v8::internal::Evacuator Class Reference
Public Types
enum EvacuationMode { kObjectsNewToOld
, kPageNewToOld
, kObjectsOldToOld
 }
Public Member Functions
Evacuator (Heap *heap)
void EvacuatePage (MutablePageMetadata *chunk)
void AddObserver (MigrationObserver *observer)
void Finalize ()
Static Public Member Functions
static const char * EvacuationModeName (EvacuationMode mode)
static EvacuationMode ComputeEvacuationMode (MemoryChunk *chunk)
Private Member Functions
bool RawEvacuatePage (MutablePageMetadata *chunk)
Heap * heap ()
void ReportCompactionProgress (double duration, intptr_t bytes_compacted)
Private Attributes
Heap * heap_
PretenuringHandler::PretenuringFeedbackMap local_pretenuring_feedback_
EvacuationAllocator local_allocator_
RecordMigratedSlotVisitor record_visitor_
EvacuateNewSpaceVisitor new_space_visitor_
EvacuateNewToOldSpacePageVisitor new_to_old_page_visitor_
EvacuateOldSpaceVisitor old_space_visitor_
double duration_
intptr_t bytes_compacted_
Detailed Description
Definition at line 4471 of file mark-compact.cc.
Member Enumeration Documentation
EvacuationMode
enum v8::internal::Evacuator::EvacuationMode
Enumerator
kObjectsNewToOld
kPageNewToOld
kObjectsOldToOld
Definition at line 4473 of file mark-compact.cc.
                      {
    kObjectsNewToOld,
    kPageNewToOld,
    kObjectsOldToOld,
  };
Constructor & Destructor Documentation
Evacuator()
v8::internal::Evacuator::Evacuator (Heap * heap) [inline], [explicit]
Definition at line 4498 of file mark-compact.cc.
      : heap_(heap),
        local_pretenuring_feedback_(
            PretenuringHandler::kInitialFeedbackCapacity),
        local_allocator_(heap_,
                         CompactionSpaceKind::kCompactionSpaceForMarkCompact),
        record_visitor_(heap_),
        new_space_visitor_(heap_, &local_allocator_, &record_visitor_,
                           &local_pretenuring_feedback_),
        new_to_old_page_visitor_(heap_, &record_visitor_,
                                 &local_pretenuring_feedback_),
        old_space_visitor_(heap_, &local_allocator_, &record_visitor_),
        duration_(0.0),
        bytes_compacted_(0) {}
References v8::internal::kCompactionSpaceForMarkCompact.
Member Function Documentation
AddObserver()
void v8::internal::Evacuator::AddObserver (MigrationObserver * observer) [inline]
Definition at line 4516 of file mark-compact.cc.
                                                {
    new_space_visitor_.AddObserver(observer);
    old_space_visitor_.AddObserver(observer);
  }
ComputeEvacuationMode()
static EvacuationMode v8::internal::Evacuator::ComputeEvacuationMode (MemoryChunk * chunk) [inline], [static]
Definition at line 4490 of file mark-compact.cc.
                                                                         {
    // Note: The order of checks is important in this function.
    if (chunk->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION))
      return kPageNewToOld;
    if (chunk->InYoungGeneration()) return kObjectsNewToOld;
    return kObjectsOldToOld;
  }
References v8::internal::MemoryChunk::InYoungGeneration(), and v8::internal::MemoryChunk::IsFlagSet().
EvacuatePage()
void v8::internal::Evacuator::EvacuatePage (MutablePageMetadata * chunk)
Definition at line 4555 of file mark-compact.cc.
                                                      {
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"), "Evacuator::EvacuatePage");
  DCHECK(page->SweepingDone());
  intptr_t saved_live_bytes = page->live_bytes();
  double evacuation_time = 0.0;
  bool success = false;
  {
    TimedScope timed_scope(&evacuation_time);
    success = RawEvacuatePage(page);
  }
  ReportCompactionProgress(evacuation_time, saved_live_bytes);
  if (v8_flags.trace_evacuation) {
    MemoryChunk* chunk = page->Chunk();
    PrintIsolate(heap_->isolate(),
                 "evacuation[%p]: page=%p new_space=%d "
                 "page_evacuation=%d executable=%d can_promote=%d "
                 "live_bytes=%" V8PRIdPTR " time=%f success=%d\n",
                 static_cast<void*>(this), static_cast<void*>(page),
                 chunk->InNewSpace(),
                 chunk->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION),
                 chunk->IsFlagSet(MemoryChunk::IS_EXECUTABLE),
                 heap_->new_space()->IsPromotionCandidate(page),
                 saved_live_bytes, evacuation_time, success);
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK, v8::internal::MemoryChunk::InNewSpace(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::PrintIsolate(), v8::internal::MutablePageMetadata::SweepingDone(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, v8::internal::v8_flags, and V8PRIdPTR.
Referenced by v8::internal::PageEvacuationJob::ProcessItems().
EvacuationModeName()
static const char* v8::internal::Evacuator::EvacuationModeName (EvacuationMode mode) [inline], [static]
Definition at line 4479 of file mark-compact.cc.
                                                             {
    switch (mode) {
      case kObjectsNewToOld:
        return "objects-new-to-old";
      case kPageNewToOld:
        return "page-new-to-old";
      case kObjectsOldToOld:
        return "objects-old-to-old";
    }
  }
References mode().
Finalize()
void v8::internal::Evacuator::Finalize ()
Definition at line 4581 of file mark-compact.cc.
                         {
  local_allocator_.Finalize();
  heap_->tracer()->AddCompactionEvent(duration_, bytes_compacted_);
  heap_->IncrementPromotedObjectsSize(new_space_visitor_.promoted_size() +
                                      new_to_old_page_visitor_.moved_bytes());
  heap_->IncrementYoungSurvivorsCounter(
      new_space_visitor_.promoted_size() +
      new_to_old_page_visitor_.moved_bytes());
  heap_->pretenuring_handler()->MergeAllocationSitePretenuringFeedback(
      local_pretenuring_feedback_);
}
heap()
Heap* v8::internal::Evacuator::heap () [inline], [private]
Definition at line 4529 of file mark-compact.cc.
{ return heap_; }
RawEvacuatePage()
bool v8::internal::Evacuator::RawEvacuatePage (MutablePageMetadata * chunk) [private]
Definition at line 4638 of file mark-compact.cc.
                                                         {
  MemoryChunk* chunk = page->Chunk();
  const EvacuationMode evacuation_mode = ComputeEvacuationMode(chunk);
  TRACE_EVENT2(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
               "FullEvacuator::RawEvacuatePage", "evacuation_mode",
               EvacuationModeName(evacuation_mode), "live_bytes",
               page->live_bytes());
  switch (evacuation_mode) {
    case kObjectsNewToOld:
#if DEBUG
      new_space_visitor_.DisableAbortEvacuationAtAddress(page);
#endif // DEBUG
      LiveObjectVisitor::VisitMarkedObjectsNoFail(PageMetadata::cast(page),
                                                  &new_space_visitor_);
      page->ClearLiveness();
      break;
    case kPageNewToOld:
      if (chunk->IsLargePage()) {
        auto object = LargePageMetadata::cast(page)->GetObject();
        bool success = new_to_old_page_visitor_.Visit(object, object->Size());
        USE(success);
        DCHECK(success);
      } else {
        LiveObjectVisitor::VisitMarkedObjectsNoFail(PageMetadata::cast(page),
                                                    &new_to_old_page_visitor_);
      }
      new_to_old_page_visitor_.account_moved_bytes(page->live_bytes());
      break;
    case kObjectsOldToOld: {
#if DEBUG
      old_space_visitor_.SetUpAbortEvacuationAtAddress(page);
#endif // DEBUG
      Tagged<HeapObject> failed_object;
      if (LiveObjectVisitor::VisitMarkedObjects(
              PageMetadata::cast(page), &old_space_visitor_, &failed_object)) {
        page->ClearLiveness();
      } else {
        // Aborted compaction page. Actual processing happens on the main
        // thread for simplicity reasons.
        heap_->mark_compact_collector()
            ->ReportAbortedEvacuationCandidateDueToOOM(
                failed_object.address(), static_cast<PageMetadata*>(page));
        return false;
      }
      break;
    }
  }
  return true;
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::ClearLiveness(), DCHECK, v8::internal::MemoryChunk::IsLargePage(), v8::internal::MutablePageMetadata::live_bytes(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT2, and USE.
ReportCompactionProgress()
void v8::internal::Evacuator::ReportCompactionProgress (double duration, intptr_t bytes_compacted) [inline], [private]
Definition at line 4531 of file mark-compact.cc.
                                                                           {
    duration_ += duration;
    bytes_compacted_ += bytes_compacted;
  }
References v8::internal::duration.
Member Data Documentation
bytes_compacted_
intptr_t v8::internal::Evacuator::bytes_compacted_ [private]
Definition at line 4552 of file mark-compact.cc.
duration_
double v8::internal::Evacuator::duration_ [private]
Definition at line 4551 of file mark-compact.cc.
heap_
Heap* v8::internal::Evacuator::heap_ [private]
Definition at line 4536 of file mark-compact.cc.
local_allocator_
EvacuationAllocator v8::internal::Evacuator::local_allocator_ [private]
Definition at line 4541 of file mark-compact.cc.
local_pretenuring_feedback_
PretenuringHandler::PretenuringFeedbackMap v8::internal::Evacuator::local_pretenuring_feedback_ [private]
Definition at line 4538 of file mark-compact.cc.
new_space_visitor_
EvacuateNewSpaceVisitor v8::internal::Evacuator::new_space_visitor_ [private]
Definition at line 4546 of file mark-compact.cc.
new_to_old_page_visitor_
EvacuateNewToOldSpacePageVisitor v8::internal::Evacuator::new_to_old_page_visitor_ [private]
Definition at line 4547 of file mark-compact.cc.
old_space_visitor_
EvacuateOldSpaceVisitor v8::internal::Evacuator::old_space_visitor_ [private]
Definition at line 4548 of file mark-compact.cc.
record_visitor_
RecordMigratedSlotVisitor v8::internal::Evacuator::record_visitor_ [private]
Definition at line 4543 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc