v8::internal::Token Class Reference
#include <token.h>
Public Types
enum Value : uint8_t { TOKEN_LIST =(T, T) kNumTokens
 }
using IsKeywordBits = base::BitField8< bool, 0, 1 >
using IsPropertyNameBits = IsKeywordBits::Next< bool, 1 >
Static Public Member Functions
static const char * Name (Value token)
static bool IsKeyword (Value token)
static bool IsPropertyName (Value token)
static bool IsValidIdentifier (Value token, LanguageMode language_mode, bool is_generator, bool disallow_await)
static bool IsCallable (Value token)
static bool IsAutoSemicolon (Value token)
static bool IsAnyIdentifier (Value token)
static bool IsStrictReservedWord (Value token)
static bool IsLiteral (Value token)
static bool IsTemplate (Value token)
static bool IsMember (Value token)
static bool IsProperty (Value token)
static bool IsPropertyOrCall (Value token)
static bool IsArrowOrAssignmentOp (Value token)
static bool IsAssignmentOp (Value token)
static bool IsLogicalAssignmentOp (Value token)
static bool IsBinaryOp (Value op)
static bool IsCompareOp (Value op)
static bool IsOrderedRelationalCompareOp (Value op)
static bool IsEqualityOp (Value op)
static Value BinaryOpForAssignment (Value op)
static bool IsBitOp (Value op)
static bool IsUnaryOp (Value op)
static bool IsCountOp (Value op)
static bool IsUnaryOrCountOp (Value op)
static bool IsShiftOp (Value op)
static const char * String (Value token)
static uint8_t StringLength (Value token)
static int Precedence (Value token, bool accept_IN)
Static Private Attributes
static const char *const name_ [kNumTokens] = {TOKEN_LIST(T, T)}
static const char *const string_ [kNumTokens] = {TOKEN_LIST(T, T)}
static const uint8_t string_length_ [kNumTokens] = {TOKEN_LIST(T, T)}
static const int8_t precedence_ [2][kNumTokens]
static const uint8_t token_flags [kNumTokens] = {TOKEN_LIST(KT, KK)}
Detailed Description
Definition at line 211 of file token.h.
Member Typedef Documentation
IsKeywordBits
using v8::internal::Token::IsKeywordBits = base::BitField8<bool, 0, 1>
Definition at line 225 of file token.h.
IsPropertyNameBits
using v8::internal::Token::IsPropertyNameBits = IsKeywordBits::Next<bool, 1>
Definition at line 226 of file token.h.
Member Enumeration Documentation
Value
enum v8::internal::Token::Value : uint8_t
Enumerator
TOKEN_LIST
Definition at line 215 of file token.h.
: uint8_t { TOKEN_LIST(T, T) kNumTokens };
Member Function Documentation
BinaryOpForAssignment()
static Value v8::internal::Token::BinaryOpForAssignment (Value op) [inline], [static]
Definition at line 307 of file token.h.
                                               {
    DCHECK(base::IsInRange(op, kAssignNullish, kAssignSub));
    Value result = static_cast<Value>(op - kAssignNullish + kNullish);
    DCHECK(IsBinaryOp(result));
    return result;
References v8::internal::DCHECK(), and v8::base::internal::result.
Referenced by v8::internal::AstNodeFactory::NewAssignment().
IsAnyIdentifier()
static bool v8::internal::Token::IsAnyIdentifier (Value token) [inline], [static]
Definition at line 255 of file token.h.
                                           {
    return base::IsInRange(token, kIdentifier, kEscapedStrictReservedWord);
Referenced by v8::internal::ParserBase< Impl >::ParseBindingPattern(), v8::internal::ParserBase< Impl >::ParsePrimaryExpression(), v8::internal::ParserBase< Impl >::ParseStatementListItem(), v8::internal::ParserBase< Impl >::ParseVariableDeclarations(), and v8::internal::ParserBase< Impl >::peek_any_identifier().
IsArrowOrAssignmentOp()
static bool v8::internal::Token::IsArrowOrAssignmentOp (Value token) [inline], [static]
Definition at line 283 of file token.h.
                                                 {
    return base::IsInRange(token, kArrow, kAssignSub);
Referenced by v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammar(), and v8::internal::ParserBase< Impl >::ParseConditionalChainAssignmentExpressionCoverGrammar().
IsAssignmentOp()
static bool v8::internal::Token::IsAssignmentOp (Value token) [inline], [static]
Definition at line 287 of file token.h.
                                          {
    return base::IsInRange(token, kInit, kAssignSub);
References v8::kInit.
Referenced by v8::internal::AstNodeFactory::NewAssignment().
IsAutoSemicolon()
static bool v8::internal::Token::IsAutoSemicolon (Value token) [inline], [static]
Definition at line 251 of file token.h.
                                           {
    return base::IsInRange(token, kSemicolon, kEos);
Referenced by v8::internal::ParserBase< Impl >::ExpectSemicolon(), v8::internal::ParserBase< Impl >::ParseBreakStatement(), v8::internal::ParserBase< Impl >::ParseContinueStatement(), and v8::internal::ParserBase< Impl >::ParseReturnStatement().
IsBinaryOp()
static bool v8::internal::Token::IsBinaryOp (Value op) [inline], [static]
Definition at line 295 of file token.h.
{ return base::IsInRange(op, kComma, kSub); }
Referenced by v8::internal::BinaryOperation::BinaryOperation(), v8::internal::Parser::CollapseNaryExpression(), and v8::internal::NaryOperation::NaryOperation().
IsBitOp()
static bool v8::internal::Token::IsBitOp (Value op) [inline], [static]
Definition at line 314 of file token.h.
                                {
    return base::IsInRange(op, kBitOr, kShr) || op == kBitNot;
IsCallable()
static bool v8::internal::Token::IsCallable (Value token) [inline], [static]
Definition at line 247 of file token.h.
                                      {
    return base::IsInRange(token, kSuper, kEscapedStrictReservedWord);
Referenced by v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation().
IsCompareOp()
static bool v8::internal::Token::IsCompareOp (Value op) [inline], [static]
Definition at line 297 of file token.h.
{ return base::IsInRange(op, kEq, kIn); }
Referenced by v8::internal::CompareOperation::CompareOperation(), and v8::internal::ParserBase< Impl >::ParseBinaryContinuation().
IsCountOp()
static bool v8::internal::Token::IsCountOp (Value op) [inline], [static]
Definition at line 319 of file token.h.
{ return base::IsInRange(op, kAdd, kVoid); }
Referenced by v8::internal::ParserBase< Impl >::ParsePostfixExpression(), and v8::internal::ParserBase< Impl >::ParseUnaryOrPrefixExpression().
IsEqualityOp()
static bool v8::internal::Token::IsEqualityOp (Value op) [inline], [static]
Definition at line 303 of file token.h.
                                     {
    return base::IsInRange(op, kEq, kEqStrict);
Referenced by v8::internal::interpreter::IsLiteralCompareTypeof(), v8::internal::MatchLiteralCompareEqualVariable(), v8::internal::MatchLiteralCompareNull(), and v8::internal::MatchLiteralCompareUndefined().
IsKeyword()
static bool v8::internal::Token::IsKeyword (Value token) [inline], [static]
Definition at line 229 of file token.h.
                                     {
    return IsKeywordBits::decode(token_flags[token]);
Referenced by v8::internal::Scanner::CurrentMatches(), v8::internal::Scanner::is_literal_one_byte(), v8::internal::Scanner::literal_one_byte_string(), and v8::internal::Scanner::literal_two_byte_string().
IsLiteral()
static bool v8::internal::Token::IsLiteral (Value token) [inline], [static]
Definition at line 263 of file token.h.
                                     {
    return base::IsInRange(token, kNullLiteral, kString);
References v8::internal::kString.
Referenced by v8::internal::ParserBase< Impl >::ParsePrimaryExpression().
IsLogicalAssignmentOp()
static bool v8::internal::Token::IsLogicalAssignmentOp (Value token) [inline], [static]
Definition at line 291 of file token.h.
                                                 {
    return base::IsInRange(token, kAssignNullish, kAssignAnd);
Referenced by v8::internal::ParserBase< Impl >::ParseAssignmentExpressionCoverGrammarContinuation().
IsMember()
static bool v8::internal::Token::IsMember (Value token) [inline], [static]
Definition at line 271 of file token.h.
                                    {
    return base::IsInRange(token, kTemplateSpan, kLeftBracket);
Referenced by v8::internal::ParserBase< Impl >::DoParseMemberExpressionContinuation(), and v8::internal::ParserBase< Impl >::ParseMemberExpressionContinuation().
IsOrderedRelationalCompareOp()
static bool v8::internal::Token::IsOrderedRelationalCompareOp (Value op) [inline], [static]
Definition at line 299 of file token.h.
                                                     {
    return base::IsInRange(op, kLessThan, kGreaterThanEq);
References v8::internal::kLessThan.
IsProperty()
static bool v8::internal::Token::IsProperty (Value token) [inline], [static]
Definition at line 275 of file token.h.
                                      {
    return base::IsInRange(token, kPeriod, kLeftBracket);
Referenced by v8::internal::ParserBase< Impl >::ParseSuperExpression().
IsPropertyName()
static bool v8::internal::Token::IsPropertyName (Value token) [inline], [static]
Definition at line 233 of file token.h.
                                          {
    return IsPropertyNameBits::decode(token_flags[token]);
Referenced by v8::internal::Parser::ParseExportSpecifierName(), v8::internal::ParserBase< Impl >::ParsePropertyName(), and v8::internal::ParserBase< Impl >::ParsePropertyOrPrivatePropertyName().
IsPropertyOrCall()
static bool v8::internal::Token::IsPropertyOrCall (Value token) [inline], [static]
Definition at line 279 of file token.h.
                                            {
    return base::IsInRange(token, kTemplateSpan, kLeftParen);
Referenced by v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation(), and v8::internal::ParserBase< Impl >::ParseLeftHandSideExpression().
IsShiftOp()
static bool v8::internal::Token::IsShiftOp (Value op) [inline], [static]
Definition at line 323 of file token.h.
{ return base::IsInRange(op, kShl, kShr); }
IsStrictReservedWord()
static bool v8::internal::Token::IsStrictReservedWord (Value token) [inline], [static]
Definition at line 259 of file token.h.
                                                {
    return base::IsInRange(token, kYield, kEscapedStrictReservedWord);
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kYield.
Referenced by v8::internal::ParserBase< Impl >::ParseAndClassifyIdentifier(), v8::internal::ParserBase< Impl >::ParseAsyncFunctionLiteral(), v8::internal::ParserBase< Impl >::ParseClassDeclaration(), v8::internal::ParserBase< Impl >::ParseClassExpression(), v8::internal::ParserBase< Impl >::ParseFunctionExpression(), and v8::internal::ParserBase< Impl >::ParseHoistableDeclaration().
IsTemplate()
static bool v8::internal::Token::IsTemplate (Value token) [inline], [static]
Definition at line 267 of file token.h.
                                      {
    return base::IsInRange(token, kTemplateSpan, kTemplateTail);
Referenced by v8::internal::ParserBase< Impl >::CheckTemplateEscapes(), v8::internal::ParserBase< Impl >::DoParseMemberExpressionContinuation(), and v8::internal::ParserBase< Impl >::ParseLeftHandSideContinuation().
IsUnaryOp()
static bool v8::internal::Token::IsUnaryOp (Value op) [inline], [static]
Definition at line 318 of file token.h.
{ return base::IsInRange(op, kAdd, kVoid); }
Referenced by v8::internal::ParserBase< Impl >::ParseUnaryOrPrefixExpression(), and v8::internal::UnaryOperation::UnaryOperation().
IsUnaryOrCountOp()
static bool v8::internal::Token::IsUnaryOrCountOp (Value op) [inline], [static]
Definition at line 320 of file token.h.
                                  { return base::IsInRange(op, kInc, kDec); }
  static bool IsUnaryOrCountOp(Value op) {
    return base::IsInRange(op, kAdd, kDec);
Referenced by v8::internal::ParserBase< Impl >::ParseUnaryExpression().
IsValidIdentifier()
static bool v8::internal::Token::IsValidIdentifier (Value token, LanguageMode language_mode, bool is_generator, bool disallow_await) [inline], [static]
Definition at line 237 of file token.h.
                                                               {
    if (V8_LIKELY(base::IsInRange(token, kIdentifier, kAsync))) return true;
    if (token == kAwait) return !disallow_await;
    if (token == kYield) return !is_generator && is_sloppy(language_mode);
    return IsStrictReservedWord(token) && is_sloppy(language_mode);
References v8::internal::is_sloppy(), v8::internal::kAsync, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kYield, and V8_LIKELY.
Referenced by v8::internal::ParserBase< Impl >::ClassifyPropertyIdentifier(), v8::internal::ParserBase< Impl >::ParseAndClassifyIdentifier(), v8::internal::Parser::ParseExportClause(), v8::internal::ParserBase< Impl >::ParseIdentifier(), and v8::internal::Parser::ParseNamedImports().
Name()
static const char* v8::internal::Token::Name (Value token) [inline], [static]
Definition at line 220 of file token.h.
                                       {
    DCHECK_GT(kNumTokens, token); // token is unsigned
    return name_[token];
References DCHECK_GT.
Precedence()
static int v8::internal::Token::Precedence (Value token, bool accept_IN) [inline], [static]
Definition at line 340 of file token.h.
                                                     {
    DCHECK_GT(kNumTokens, token); // token is unsigned
    return precedence_[accept_IN][token];
References DCHECK_GT.
Referenced by v8::internal::ParserBase< Impl >::ParseBinaryContinuation(), v8::internal::ParserBase< Impl >::ParseBinaryExpression(), and v8::internal::ParserBase< Impl >::ParseLogicalExpression().
String()
static const char* v8::internal::Token::String (Value token) [inline], [static]
Definition at line 328 of file token.h.
                                         {
    DCHECK_GT(kNumTokens, token); // token is unsigned
    return string_[token];
References DCHECK_GT.
Referenced by v8::internal::Parser::ReportUnexpectedTokenAt().
StringLength()
static uint8_t v8::internal::Token::StringLength (Value token) [inline], [static]
Definition at line 333 of file token.h.
                                           {
    DCHECK_GT(kNumTokens, token); // token is unsigned
    return string_length_[token];
References DCHECK_GT.
Member Data Documentation
name_
const char *const v8::internal::Token::name_ = {TOKEN_LIST(T, T)} [static], [private]
Definition at line 346 of file token.h.
precedence_
const int8_t v8::internal::Token::precedence_ [static], [private]
Initial value:
= {{TOKEN_LIST(T1, T1)},
                                                  {TOKEN_LIST(T2, T2)}}
Definition at line 349 of file token.h.
string_
const char *const v8::internal::Token::string_ = {TOKEN_LIST(T, T)} [static], [private]
Definition at line 347 of file token.h.
string_length_
const uint8_t v8::internal::Token::string_length_ = {TOKEN_LIST(T, T)} [static], [private]
Definition at line 348 of file token.h.
token_flags
const uint8_t v8::internal::Token::token_flags = {TOKEN_LIST(KT, KK)} [static], [private]
Definition at line 350 of file token.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/token.h
/mnt/V8SourceCode/src/parsing/token.cc