v8::internal::Arguments< arguments_type > Class Template Reference
#include <arguments.h>
Classes
class ChangeValueScope
Public Member Functions
Arguments (int length, Address *arguments)
Tagged< Object > operator[] (int index) const
template<class S = Object>
Handle< S > at (int index) const
FullObjectSlot slot_from_address_at (int index, int offset) const
int smi_value_at (int index) const
uint32_t positive_smi_value_at (int index) const
int tagged_index_value_at (int index) const
double number_value_at (int index) const
Handle< Object > atOrUndefined (Isolate *isolate, int index) const
Address * address_of_arg_at (int index) const
int length () const
Private Attributes
intptr_t length_
Address * arguments_
Detailed Description
template<ArgumentsType arguments_type>
class v8::internal::Arguments< arguments_type >
Definition at line 36 of file arguments.h.
Constructor & Destructor Documentation
Arguments()
template<ArgumentsType arguments_type>
v8::internal::Arguments< arguments_type >::Arguments (int length, Address * arguments) [inline]
Definition at line 50 of file arguments.h.
      : length_(length), arguments_(arguments) {
    DCHECK_GE(length_, 0);
  }
References DCHECK_GE, and v8::internal::Arguments< arguments_type >::length_.
Member Function Documentation
address_of_arg_at()
template<ArgumentsType arguments_type>
Address* v8::internal::Arguments< arguments_type >::address_of_arg_at (int index) const [inline]
Definition at line 73 of file arguments.h.
                                                        {
    // Corruption of certain heap objects (see e.g. crbug.com/1507223) can lead
    // to OOB arguments access, and therefore OOB stack access. This SBXCHECK
    // defends against that.
    // Note: "LE" is intentional: it's okay to compute the address of the
    // first nonexistent entry.
    SBXCHECK_LE(static_cast<uint32_t>(index), static_cast<uint32_t>(length_));
    uintptr_t offset = index * kSystemPointerSize;
    if (arguments_type == ArgumentsType::kJS) {
      offset = (length_ - index - 1) * kSystemPointerSize;
    }
    return reinterpret_cast<Address*>(reinterpret_cast<Address>(arguments_) -
                                      offset);
  }
References v8::internal::Arguments< arguments_type >::arguments_, v8::internal::index, v8::internal::kJS, v8::internal::kSystemPointerSize, v8::internal::Arguments< arguments_type >::length_, and SBXCHECK_LE.
Referenced by v8::internal::BuiltinArguments::address_of_first_argument(), v8::internal::BuiltinArguments::at(), v8::internal::BuiltinArguments::new_target(), v8::internal::BuiltinArguments::operator[](), v8::internal::Arguments< arguments_type >::operator[](), v8::internal::BuiltinArguments::receiver(), v8::internal::BuiltinArguments::set_at(), and v8::internal::BuiltinArguments::target().
at()
template<ArgumentsType T>
template<class S >
Handle< S > v8::internal::Arguments< T >::at (int index) const [inline]
Definition at line 98 of file arguments.h.
                                          {
  Handle<Object> obj = Handle<Object>(address_of_arg_at(index));
  return Cast<S>(obj);
}
References v8::internal::index.
Referenced by v8::internal::RUNTIME_FUNCTION().
atOrUndefined()
template<ArgumentsType T>
Handle< Object > v8::internal::Arguments< T >::atOrUndefined (Isolate * isolate, int index) const [inline]
Definition at line 53 of file arguments-inl.h.
                                                                            {
  if (index >= length_) {
    return Cast<Object>(isolate->factory()->undefined_value());
  }
  return at<Object>(index);
}
References v8::internal::Isolate::factory(), v8::internal::index, and v8::internal::Arguments< arguments_type >::length_.
length()
template<ArgumentsType arguments_type>
int v8::internal::Arguments< arguments_type >::length () const [inline]
Definition at line 89 of file arguments.h.
{ return static_cast<int>(length_); }
References v8::internal::Arguments< arguments_type >::length_.
Referenced by v8::internal::BuiltinArguments::length(), and v8::internal::RUNTIME_FUNCTION().
number_value_at()
template<ArgumentsType T>
double v8::internal::Arguments< T >::number_value_at (int index) const [inline]
Definition at line 48 of file arguments-inl.h.
                                                    {
  return Object::NumberValue((*this)[index]);
}
References v8::internal::index, and v8::internal::Object::NumberValue().
operator[]()
template<ArgumentsType arguments_type>
Tagged<Object> v8::internal::Arguments< arguments_type >::operator[] (int index) const [inline]
Definition at line 55 of file arguments.h.
                                                       {
    return Tagged<Object>(*address_of_arg_at(index));
  }
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), v8::internal::index, and v8::internal::Tagged< Object >.
positive_smi_value_at()
template<ArgumentsType T>
uint32_t v8::internal::Arguments< T >::positive_smi_value_at (int index) const [inline]
Definition at line 36 of file arguments-inl.h.
                                                            {
  int value = smi_value_at(index);
  DCHECK_LE(0, value);
  return value;
}
References DCHECK_LE, v8::internal::index, v8::internal::Arguments< arguments_type >::smi_value_at(), and v8::internal::value.
slot_from_address_at()
template<ArgumentsType T>
FullObjectSlot v8::internal::Arguments< T >::slot_from_address_at (int index, int offset) const [inline]
Definition at line 104 of file arguments.h.
                                                                             {
  Address* location = *reinterpret_cast<Address**>(address_of_arg_at(index));
  return FullObjectSlot(location + offset);
}
References v8::internal::index.
smi_value_at()
template<ArgumentsType T>
int v8::internal::Arguments< T >::smi_value_at (int index) const [inline]
Definition at line 28 of file arguments-inl.h.
                                              {
  Tagged<Object> obj = (*this)[index];
  int value = Smi::ToInt(obj);
  DCHECK_IMPLIES(IsTaggedIndex(obj), value == tagged_index_value_at(index));
  return value;
}
References DCHECK_IMPLIES, v8::internal::index, v8::internal::IsTaggedIndex(), v8::internal::Arguments< arguments_type >::tagged_index_value_at(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8::internal::Arguments< arguments_type >::positive_smi_value_at().
tagged_index_value_at()
template<ArgumentsType T>
int v8::internal::Arguments< T >::tagged_index_value_at (int index) const [inline]
Definition at line 43 of file arguments-inl.h.
                                                       {
  return static_cast<int>(Cast<TaggedIndex>((*this)[index]).value());
}
References v8::internal::index.
Referenced by v8::internal::Arguments< arguments_type >::smi_value_at().
Member Data Documentation
arguments_
template<ArgumentsType arguments_type>
Address* v8::internal::Arguments< arguments_type >::arguments_ [private]
Definition at line 93 of file arguments.h.
Referenced by v8::internal::Arguments< arguments_type >::address_of_arg_at().
length_
template<ArgumentsType arguments_type>
intptr_t v8::internal::Arguments< arguments_type >::length_ [private]
Definition at line 92 of file arguments.h.
Referenced by v8::internal::Arguments< arguments_type >::address_of_arg_at(), v8::internal::Arguments< arguments_type >::Arguments(), v8::internal::Arguments< arguments_type >::atOrUndefined(), and v8::internal::Arguments< arguments_type >::length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/execution/arguments.h
/mnt/V8SourceCode/src/execution/arguments-inl.h