v8::internal::SwissNameDictionary::IndexIterator Class Reference
#include <swiss-name-dictionary.h>
Public Member Functions
IndexIterator (DirectHandle< SwissNameDictionary > dict, int start)
IndexIterator & operator++ ()
bool operator== (const IndexIterator &b) const
bool operator!= (const IndexIterator &b) const
InternalIndex operator* ()
Private Attributes
int used_capacity_
int enum_index_
DirectHandle< SwissNameDictionary > dict_
Detailed Description
Definition at line 160 of file swiss-name-dictionary.h.
Constructor & Destructor Documentation
IndexIterator()
v8::internal::SwissNameDictionary::IndexIterator::IndexIterator (DirectHandle< SwissNameDictionary > dict, int start) [inline]
Definition at line 590 of file swiss-name-dictionary-inl.h.
    : enum_index_{start}, dict_{dict} {
  if (dict.is_null()) {
    used_capacity_ = 0;
  } else {
    used_capacity_ = dict->UsedCapacity();
  }
}
References v8::internal::DirectHandle< T >::is_null(), and used_capacity_.
Member Function Documentation
operator!=()
bool v8::internal::SwissNameDictionary::IndexIterator::operator!= (const IndexIterator & b) const [inline]
Definition at line 616 of file swiss-name-dictionary-inl.h.
                                  {
  return !(*this == b);
}
operator*()
InternalIndex v8::internal::SwissNameDictionary::IndexIterator::operator* () [inline]
Definition at line 621 of file swiss-name-dictionary-inl.h.
                                                          {
  DCHECK_LE(enum_index_, used_capacity_);
  if (enum_index_ == used_capacity_) return InternalIndex::NotFound();
  return InternalIndex(dict_->EntryForEnumerationIndex(enum_index_));
}
References DCHECK_LE, and v8::internal::InternalIndex::NotFound().
operator++()
SwissNameDictionary::IndexIterator & v8::internal::SwissNameDictionary::IndexIterator::operator++ () [inline]
Definition at line 601 of file swiss-name-dictionary-inl.h.
                                             {
  DCHECK_LT(enum_index_, used_capacity_);
  ++enum_index_;
  return *this;
}
References DCHECK_LT.
operator==()
bool v8::internal::SwissNameDictionary::IndexIterator::operator== (const IndexIterator & b) const [inline]
Definition at line 607 of file swiss-name-dictionary-inl.h.
                                                     {
  DCHECK_LE(enum_index_, used_capacity_);
  DCHECK_LE(b.enum_index_, used_capacity_);
  DCHECK(dict_.equals(b.dict_));
  return this->enum_index_ == b.enum_index_;
}
References v8::internal::DCHECK(), DCHECK_LE, dict_, and enum_index_.
Member Data Documentation
dict_
DirectHandle<SwissNameDictionary> v8::internal::SwissNameDictionary::IndexIterator::dict_ [private]
Definition at line 177 of file swiss-name-dictionary.h.
Referenced by operator==().
enum_index_
int v8::internal::SwissNameDictionary::IndexIterator::enum_index_ [private]
Definition at line 173 of file swiss-name-dictionary.h.
Referenced by operator==().
used_capacity_
int v8::internal::SwissNameDictionary::IndexIterator::used_capacity_ [private]
Definition at line 172 of file swiss-name-dictionary.h.
Referenced by IndexIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/swiss-name-dictionary.h
/mnt/V8SourceCode/src/objects/swiss-name-dictionary-inl.h