unibrow::Predicate< T, size >::CacheEntry Class Reference
Public Member Functions
CacheEntry ()
CacheEntry (uchar code_point, bool value)
uchar code_point () const
bool value () const
Private Types
using CodePointField = v8::base::BitField< uchar, 0, 21 >
using ValueField = v8::base::BitField< bool, 21, 1 >
Private Attributes
uint32_t bit_field_
Detailed Description
template<class T, int size = 256>
class unibrow::Predicate< T, size >::CacheEntry
Definition at line 39 of file unicode.h.
Member Typedef Documentation
CodePointField
template<class T , int size = 256>
using unibrow::Predicate< T, size >::CacheEntry::CodePointField = v8::base::BitField<uchar, 0, 21> [private]
Definition at line 55 of file unicode.h.
ValueField
template<class T , int size = 256>
using unibrow::Predicate< T, size >::CacheEntry::ValueField = v8::base::BitField<bool, 21, 1> [private]
Definition at line 56 of file unicode.h.
Constructor & Destructor Documentation
CacheEntry() [1/2]
template<class T , int size = 256>
unibrow::Predicate< T, size >::CacheEntry::CacheEntry () [inline]
Definition at line 41 of file unicode.h.
        : bit_field_(CodePointField::encode(0) | ValueField::encode(0)) {}
CacheEntry() [2/2]
template<class T , int size = 256>
unibrow::Predicate< T, size >::CacheEntry::CacheEntry (uchar code_point, bool value) [inline]
Definition at line 43 of file unicode.h.
        : bit_field_(
              CodePointField::encode(CodePointField::kMask & code_point) |
              ValueField::encode(value)) {
      DCHECK_IMPLIES((CodePointField::kMask & code_point) != code_point,
                     code_point == static_cast<uchar>(-1));
    }
References unibrow::Predicate< T, size >::CacheEntry::code_point(), DCHECK_IMPLIES, and v8::base::BitField< T, shift, size, U >::kMask.
Member Function Documentation
code_point()
template<class T , int size = 256>
uchar unibrow::Predicate< T, size >::CacheEntry::code_point () const [inline]
Definition at line 51 of file unicode.h.
{ return CodePointField::decode(bit_field_); }
References unibrow::Predicate< T, size >::CacheEntry::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by unibrow::Predicate< T, size >::CacheEntry::CacheEntry(), and unibrow::Predicate< T, size >::get().
value()
template<class T , int size = 256>
bool unibrow::Predicate< T, size >::CacheEntry::value () const [inline]
Definition at line 52 of file unicode.h.
{ return ValueField::decode(bit_field_); }
References unibrow::Predicate< T, size >::CacheEntry::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by unibrow::Predicate< T, size >::get().
Member Data Documentation
bit_field_
template<class T , int size = 256>
uint32_t unibrow::Predicate< T, size >::CacheEntry::bit_field_ [private]
Definition at line 58 of file unicode.h.
Referenced by unibrow::Predicate< T, size >::CacheEntry::code_point(), and unibrow::Predicate< T, size >::CacheEntry::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/strings/unicode.h