v8::internal::CompilationCacheEval Class Reference
#include <compilation-cache.h>
Public Member Functions
CompilationCacheEval (Isolate *isolate)
InfoCellPair Lookup (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< NativeContext > native_context, LanguageMode language_mode, int position)
void UpdateEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, LanguageMode language_mode, int position)
void Put (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, int position)
void Age ()
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheEval)
Additional Inherited Members
Detailed Description
Definition at line 79 of file compilation-cache.h.
Constructor & Destructor Documentation
CompilationCacheEval()
v8::internal::CompilationCacheEval::CompilationCacheEval (Isolate * isolate) [inline], [explicit]
Definition at line 81 of file compilation-cache.h.
      : CompilationCacheEvalOrScript(isolate) {}
Member Function Documentation
Age()
void v8::internal::CompilationCacheEval::Age ()
Definition at line 89 of file compilation-cache.cc.
                               {
  DisallowGarbageCollection no_gc;
  if (IsUndefined(table_, isolate())) return;
  Tagged<CompilationCacheTable> table = Cast<CompilationCacheTable>(table_);
  for (InternalIndex entry : table->IterateEntries()) {
    Tagged<Object> key;
    if (!table->ToKey(isolate(), entry, &key)) continue;
    DCHECK(IsFixedArray(key));
    // The ageing mechanism for eval caches.
    Tagged<SharedFunctionInfo> info =
        Cast<SharedFunctionInfo>(table->PrimaryValueAt(entry));
    // Clear entries after Bytecode was flushed from SFI.
    if (!info->HasBytecodeArray()) {
      table->RemoveEntry(entry);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::CompilationCacheEvalOrScript::isolate(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::CompilationCacheEvalOrScript::table_.
Referenced by v8::internal::CompilationCache::MarkCompactPrologue().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::CompilationCacheEval::DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheEval) [private]
Lookup()
InfoCellPair v8::internal::CompilationCacheEval::Lookup (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< NativeContext > native_context, LanguageMode language_mode, int position)
Definition at line 172 of file compilation-cache.cc.
                  {
  InfoCellPair result;
  DirectHandle<CompilationCacheTable> table = GetTable();
  result = CompilationCacheTable::LookupEval(
      table, source, outer_info, native_context, language_mode, position);
  if (result.has_shared()) {
    isolate()->counters()->compilation_cache_hits()->Increment();
  } else {
    isolate()->counters()->compilation_cache_misses()->Increment();
  }
  return result;
}
References v8::internal::Isolate::counters(), v8::internal::CompilationCacheEvalOrScript::GetTable(), v8::internal::CompilationCacheEvalOrScript::isolate(), v8::internal::CompilationCacheTable::LookupEval(), v8::internal::native_context, and v8::base::internal::result.
Referenced by v8::internal::CompilationCache::LookupEval().
Put()
void v8::internal::CompilationCacheEval::Put (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, int position)
Definition at line 188 of file compilation-cache.cc.
                                             {
  DirectHandle<CompilationCacheTable> table = GetTable();
  table_ = *CompilationCacheTable::PutEval(table, source, outer_info,
                                           js_function, position);
}
References v8::internal::CompilationCacheEvalOrScript::GetTable(), v8::internal::CompilationCacheTable::PutEval(), and v8::internal::CompilationCacheEvalOrScript::table_.
Referenced by v8::internal::CompilationCache::PutEval().
UpdateEval()
void v8::internal::CompilationCacheEval::UpdateEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, LanguageMode language_mode, int position)
Definition at line 163 of file compilation-cache.cc.
                  {
  DirectHandle<CompilationCacheTable> table = GetTable();
  CompilationCacheTable::UpdateEval(table, source, outer_info, js_function,
                                    language_mode, position);
}
References v8::internal::CompilationCacheEvalOrScript::GetTable(), and v8::internal::CompilationCacheTable::UpdateEval().
Referenced by v8::internal::CompilationCache::UpdateEval().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compilation-cache.h
/mnt/V8SourceCode/src/codegen/compilation-cache.cc