v8::internal::TemplateObjectDescription Class Reference
#include <template-objects.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Static Public Member Functions
static DirectHandle< JSArray > GetTemplateObject (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateObjectDescription > description, DirectHandle< SharedFunctionInfo > shared_info, int slot_id)
Detailed Description
Definition at line 26 of file template-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::TemplateObjectDescription::BodyDescriptor = StructBodyDescriptor
Definition at line 35 of file template-objects.h.
Member Function Documentation
GetTemplateObject()
DirectHandle< JSArray > v8::internal::TemplateObjectDescription::GetTemplateObject (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< TemplateObjectDescription > description, DirectHandle< SharedFunctionInfo > shared_info, int slot_id) [static]
Definition at line 48 of file template-objects.cc.
                                                               {
  int function_literal_id = shared_info->function_literal_id(kRelaxedLoad);
  // Check the template weakmap to see if the template object already exists.
  DirectHandle<Script> script(Cast<Script>(shared_info->script(isolate)),
                              isolate);
  int32_t hash =
      EphemeronHashTable::TodoShape::Hash(ReadOnlyRoots(isolate), script);
  MaybeDirectHandle<ArrayList> maybe_cached_templates;
  if (!IsUndefined(native_context->template_weakmap(), isolate)) {
    DisallowGarbageCollection no_gc;
    // The no_gc keeps this safe, and gcmole is confused because
    // CachedTemplateMatches calls JSReceiver::GetDataProperty.
    DisableGCMole no_gcmole;
    ReadOnlyRoots roots(isolate);
    Tagged<EphemeronHashTable> template_weakmap =
        Cast<EphemeronHashTable>(native_context->template_weakmap());
    Tagged<Object> cached_templates_lookup =
        template_weakmap->Lookup(isolate, script, hash);
    if (!IsTheHole(cached_templates_lookup, roots)) {
      Tagged<ArrayList> cached_templates =
          Cast<ArrayList>(cached_templates_lookup);
      maybe_cached_templates = direct_handle(cached_templates, isolate);
      // Linear search over the cached template array list for a template
      // object matching the given function_literal_id + slot_id.
      // TODO(leszeks): Consider keeping this list sorted for faster lookup.
      for (int i = 0; i < cached_templates->length(); i++) {
        Tagged<JSArray> template_object =
            Cast<JSArray>(cached_templates->get(i));
        if (CachedTemplateMatches(isolate, *native_context, template_object,
                                  function_literal_id, slot_id, no_gc)) {
          return direct_handle(template_object, isolate);
        }
      }
    }
  }
  // Create the raw object from the {raw_strings}.
  DirectHandle<FixedArray> raw_strings(description->raw_strings(), isolate);
  DirectHandle<FixedArray> cooked_strings(description->cooked_strings(),
                                          isolate);
  DirectHandle<JSArray> template_object =
      isolate->factory()->NewJSArrayForTemplateLiteralArray(
          cooked_strings, raw_strings, function_literal_id, slot_id);
  // Insert the template object into the cached template array list.
  DirectHandle<ArrayList> cached_templates;
  if (!maybe_cached_templates.ToHandle(&cached_templates)) {
    cached_templates = isolate->factory()->NewArrayList(1);
  }
  cached_templates = ArrayList::Add(isolate, cached_templates, template_object);
  // Compare the cached_templates to the original maybe_cached_templates loaded
  // from the weakmap -- if it doesn't match, we need to update the weakmap.
  DirectHandle<ArrayList> old_cached_templates;
  if (!maybe_cached_templates.ToHandle(&old_cached_templates) ||
      *old_cached_templates != *cached_templates) {
    Tagged<HeapObject> maybe_template_weakmap =
        native_context->template_weakmap();
    Handle<EphemeronHashTable> template_weakmap;
    if (IsUndefined(maybe_template_weakmap)) {
      template_weakmap = EphemeronHashTable::New(isolate, 1);
    } else {
      template_weakmap =
          handle(Cast<EphemeronHashTable>(maybe_template_weakmap), isolate);
    }
    template_weakmap = EphemeronHashTable::Put(isolate, template_weakmap,
                                               script, cached_templates, hash);
    native_context->set_template_weakmap(*template_weakmap);
  }
  // Check that the list is in the appropriate location on the weakmap, and
  // that the appropriate entry is in the right location in this list.
  DCHECK_EQ(Cast<EphemeronHashTable>(native_context->template_weakmap())
                ->Lookup(isolate, script, hash),
            *cached_templates);
  DCHECK_EQ(cached_templates->get(cached_templates->length() - 1),
            *template_object);
  return template_object;
}
References v8::internal::ArrayList::Add(), v8::internal::anonymous_namespace{template-objects.cc}::CachedTemplateMatches(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::function_literal_id, v8::internal::handle(), v8::internal::Hash(), v8::kRelaxedLoad, v8::internal::native_context, v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::FactoryBase< Impl >::NewArrayList(), v8::internal::Factory::NewJSArrayForTemplateLiteralArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::script, and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::RUNTIME_FUNCTION().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/template-objects.h
/mnt/V8SourceCode/src/objects/template-objects.cc