v8::internal::MaglevFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
void Iterate (RootVisitor *v) const override
int FindReturnPCForTrampoline (Tagged< Code > code, int trampoline_pc) const override
DirectHandle< JSFunction > GetInnermostFunction () const
BytecodeOffset GetBytecodeOffsetForOSR () const
Static Public Member Functions
static MaglevFrame * cast (StackFrame *frame)
static intptr_t StackGuardFrameSize (int register_input_count)
Protected Member Functions
MaglevFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1191 of file frames.h.
Constructor & Destructor Documentation
MaglevFrame()
v8::internal::MaglevFrame::MaglevFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 315 of file frames-inl.h.
    : OptimizedJSFrame(iterator) {}
Member Function Documentation
cast()
static MaglevFrame* v8::internal::MaglevFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1195 of file frames.h.
                                              {
    DCHECK(frame->is_maglev());
    return static_cast<MaglevFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_maglev().
Referenced by v8::internal::RUNTIME_FUNCTION().
FindReturnPCForTrampoline()
int v8::internal::MaglevFrame::FindReturnPCForTrampoline (Tagged< Code > code, int trampoline_pc) const [override], [virtual]
Implements v8::internal::OptimizedJSFrame.
Definition at line 3189 of file frames.cc.
                                                                    {
  DCHECK_EQ(code->kind(), CodeKind::MAGLEV);
  DCHECK(code->marked_for_deoptimization());
  MaglevSafepointTable safepoints(isolate(), pc(), code);
  return safepoints.find_return_pc(trampoline_pc);
}
References code, v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::MaglevSafepointTable::find_return_pc().
GetBytecodeOffsetForOSR()
BytecodeOffset v8::internal::MaglevFrame::GetBytecodeOffsetForOSR () const
Definition at line 2207 of file frames.cc.
                                                          {
  int deopt_index = SafepointEntry::kNoDeoptIndex;
  Tagged<Code> code = LookupCode();
  const Tagged<DeoptimizationData> data =
      GetDeoptimizationData(code, &deopt_index);
  if (deopt_index == SafepointEntry::kNoDeoptIndex) {
    CHECK(data.is_null());
    FATAL(
        "Missing deoptimization information for OptimizedJSFrame::Summarize.");
  }
  DeoptimizationFrameTranslation::Iterator it(
      data->FrameTranslation(), data->TranslationIndex(deopt_index).value());
  // Search the innermost interpreter frame and get its bailout id. The
  // translation stores frames bottom up.
  int js_frames = it.EnterBeginOpcode().js_frame_count;
  DCHECK_GT(js_frames, 0);
  BytecodeOffset offset = BytecodeOffset::None();
  while (js_frames > 0) {
    TranslationOpcode frame = it.SeekNextJSFrame();
    --js_frames;
    if (IsTranslationInterpreterFrameOpcode(frame)) {
      offset = BytecodeOffset(it.NextOperand());
      it.SkipOperands(TranslationOpcodeOperandCount(frame) - 1);
    } else {
      it.SkipOperands(TranslationOpcodeOperandCount(frame));
    }
  }
  return offset;
}
References CHECK, code, DCHECK_GT, v8::internal::DeoptTranslationIterator::EnterBeginOpcode(), FATAL, v8::internal::OptimizedJSFrame::GetDeoptimizationData(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsTranslationInterpreterFrameOpcode(), v8::internal::DeoptimizationFrameTranslation::FrameCount::js_frame_count, v8::internal::SafepointEntryBase::kNoDeoptIndex, v8::internal::StackFrame::LookupCode(), v8::internal::DeoptTranslationIterator::NextOperand(), v8::internal::BytecodeOffset::None(), v8::internal::DeoptTranslationIterator::SeekNextJSFrame(), v8::internal::DeoptTranslationIterator::SkipOperands(), and v8::internal::TranslationOpcodeOperandCount().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetInnermostFunction()
DirectHandle< JSFunction > v8::internal::MaglevFrame::GetInnermostFunction () const
Definition at line 2203 of file frames.cc.
                                                                 {
  return Summarize().frames.back().AsJavaScript().function();
}
References v8::internal::FrameSummaries::frames, and v8::internal::OptimizedJSFrame::Summarize().
Referenced by v8::internal::RUNTIME_FUNCTION().
Iterate()
void v8::internal::MaglevFrame::Iterate (RootVisitor * v) const [override], [virtual]
Reimplemented from v8::internal::JavaScriptFrame.
Definition at line 2096 of file frames.cc.
                                              {
  DCHECK(!iterator_->IsStackFrameIteratorForProfiler());
  // === MaglevFrame ===
  // +-----------------+-----------------------------------------
  // | out_param n | <-- parameters_base / sp
  // | ... |
  // | out_param 0 |
  // +-----------------+-----------------------------------------
  // | pushed_double n | <-- parameters_limit ^
  // | ... | |
  // | pushed_double 0 | |
  // +- - - - - - - - -+ num_extra_spill_slots
  // | pushed_reg n | |
  // | ... | |
  // | pushed_reg 0 | <-- pushed_register_base v
  // +-----------------+-----------------------------------------
  // | untagged_slot n | ^
  // | ... | |
  // | untagged_slot 0 | |
  // +- - - - - - - - -+ spill_slot_count
  // | tagged_slot n | |
  // | ... | |
  // | tagged_slot 0 | v
  // +-----------------+-----------------------------------------
  // | argc | <-- frame_header_base ^
  // |- - - - - - - - -| |
  // | JSFunction | |
  // |- - - - - - - - -| |
  // | Context | |
  // |- - - - - - - - -| kFixedSlotCount
  // | [Constant Pool] | |
  // |- - - - - - - - -| |
  // | saved frame ptr | <-- fp |
  // |- - - - - - - - -| |
  // | return addr | v
  // +-----------------+-----------------------------------------
  // Find the code and compute the safepoint information.
  Address inner_pointer = pc();
  InnerPointerToCodeCache::InnerPointerToCodeCacheEntry* entry =
      isolate()->inner_pointer_to_code_cache()->GetCacheEntry(inner_pointer);
  CHECK(entry->code.has_value());
  Tagged<GcSafeCode> code = entry->code.value();
  DCHECK(code->is_maglevved());
  MaglevSafepointEntry maglev_safepoint_entry =
      GetMaglevSafepointEntryFromCodeCache(isolate(), inner_pointer, entry);
#ifdef DEBUG
  // Assert that it is a JS frame and it has a context.
  intptr_t marker =
      Memory<intptr_t>(fp() + CommonFrameConstants::kContextOrFrameTypeOffset);
  DCHECK(!StackFrame::IsTypeMarker(marker));
#endif // DEBUG
  // Fixed frame slots.
  FullObjectSlot frame_header_base(
      &Memory<Address>(fp() - StandardFrameConstants::kFixedFrameSizeFromFp));
  FullObjectSlot frame_header_limit(
      &Memory<Address>(fp() - StandardFrameConstants::kCPSlotSize));
  // Determine spill slot area count.
  uint32_t tagged_slot_count = maglev_safepoint_entry.num_tagged_slots();
  uint32_t spill_slot_count =
      code->stack_slots() - StandardFrameConstants::kFixedSlotCount;
  // Visit the outgoing parameters if they are tagged.
  DCHECK(code->has_tagged_outgoing_params());
  FullObjectSlot parameters_base(&Memory<Address>(sp()));
  FullObjectSlot parameters_limit =
      frame_header_base - spill_slot_count -
      maglev_safepoint_entry.num_extra_spill_slots();
  v->VisitRootPointers(Root::kStackRoots, nullptr, parameters_base,
                       parameters_limit);
  // Maglev can also spill registers, tagged and untagged, just before making
  // a call. These are distinct from normal spill slots and live between the
  // normal spill slots and the pushed parameters. Some of these are tagged,
  // as indicated by the tagged register indexes, and should be visited too.
  if (maglev_safepoint_entry.num_extra_spill_slots() > 0) {
    FullObjectSlot pushed_register_base =
        frame_header_base - spill_slot_count - 1;
    uint32_t tagged_register_indexes =
        maglev_safepoint_entry.tagged_register_indexes();
    while (tagged_register_indexes != 0) {
      int index = base::bits::CountTrailingZeros(tagged_register_indexes);
      tagged_register_indexes &= ~(1 << index);
      FullObjectSlot spill_slot = pushed_register_base - index;
      VisitSpillSlot(isolate(), v, spill_slot);
    }
  }
  // Visit tagged spill slots.
  for (uint32_t i = 0; i < tagged_slot_count; ++i) {
    FullObjectSlot spill_slot = frame_header_base - 1 - i;
    VisitSpillSlot(isolate(), v, spill_slot);
  }
  // Visit fixed header region (the context and JSFunction), skipping the
  // argument count since it is stored untagged.
  v->VisitRootPointers(Root::kStackRoots, nullptr, frame_header_base + 1,
                       frame_header_limit);
  // Visit the return address in the callee and incoming arguments.
  IteratePc(v, constant_pool_address(), code);
}
References CHECK, v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, code, v8::internal::StackFrame::constant_pool_address(), v8::base::bits::CountTrailingZeros(), v8::internal::DCHECK(), v8::internal::StackFrame::fp(), v8::internal::InnerPointerToCodeCache::GetCacheEntry(), v8::internal::anonymous_namespace{frames.cc}::GetMaglevSafepointEntryFromCodeCache(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Isolate::inner_pointer_to_code_cache(), v8::internal::StackFrame::isolate(), v8::internal::StackFrame::IsTypeMarker(), v8::internal::StackFrame::IteratePc(), v8::internal::StackFrame::iterator_, v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::CommonFrameConstants::kCPSlotSize, v8::internal::StandardFrameConstants::kFixedFrameSizeFromFp, v8::internal::StandardFrameConstants::kFixedSlotCount, v8::internal::MaglevSafepointEntry::num_extra_spill_slots(), v8::internal::MaglevSafepointEntry::num_tagged_slots(), v8::internal::StackFrame::pc(), v8::internal::StackFrame::sp(), v8::internal::MaglevSafepointEntry::tagged_register_indexes(), v8::internal::RootVisitor::VisitRootPointers(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
StackGuardFrameSize()
intptr_t v8::internal::MaglevFrame::StackGuardFrameSize (int register_input_count) [static]
Definition at line 27 of file frame-constants-riscv.cc.
                                                                  {
  USE(register_input_count);
  UNREACHABLE();
}
References v8::internal::UNREACHABLE(), and USE.
type()
Type v8::internal::MaglevFrame::type () const [inline], [override], [virtual]
Implements v8::internal::JavaScriptFrame.
Definition at line 1193 of file frames.h.
{ return MAGLEV; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1214 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc
/mnt/V8SourceCode/src/execution/riscv/frame-constants-riscv.cc