v8::internal::compiler::RepresentationChanger Class Reference
#include <representation-change.h>
Public Member Functions
RepresentationChanger (JSGraph *jsgraph, JSHeapBroker *broker, SimplifiedLoweringVerifier *verifier)
Node * GetRepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
const Operator * Int32OperatorFor (IrOpcode::Value opcode)
const Operator * Int32OverflowOperatorFor (IrOpcode::Value opcode)
const Operator * AdditiveSafeIntegerOverflowOperatorFor (IrOpcode::Value opcode)
const Operator * Int64OperatorFor (IrOpcode::Value opcode)
const Operator * Int64OverflowOperatorFor (IrOpcode::Value opcode)
const Operator * BigIntOperatorFor (IrOpcode::Value opcode)
const Operator * TaggedSignedOperatorFor (IrOpcode::Value opcode)
const Operator * Uint32OperatorFor (IrOpcode::Value opcode)
const Operator * Uint32OverflowOperatorFor (IrOpcode::Value opcode)
const Operator * Float64OperatorFor (IrOpcode::Value opcode)
MachineType TypeForBasePointer (const FieldAccess &access)
MachineType TypeForBasePointer (const ElementAccess &access)
bool verification_enabled () const
Private Member Functions
Node * GetTaggedSignedRepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
Node * GetTaggedPointerRepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
Node * GetTaggedRepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Truncation truncation)
Node * GetFloat16RawBitsRepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
Node * GetFloat32RepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Truncation truncation)
Node * GetFloat64RepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
Node * GetWord32RepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
Node * GetBitRepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type)
Node * GetWord64RepresentationFor (Node *node, MachineRepresentation output_rep, Type output_type, Node *use_node, UseInfo use_info)
Node * TypeError (Node *node, MachineRepresentation output_rep, Type output_type, MachineRepresentation use)
Node * MakeTruncatedInt32Constant (double value)
Node * InsertChangeBitToTagged (Node *node)
Node * InsertChangeFloat32ToFloat64 (Node *node)
Node * InsertChangeFloat64ToInt32 (Node *node)
Node * InsertChangeFloat64ToUint32 (Node *node)
Node * InsertChangeInt32ToFloat64 (Node *node)
Node * InsertChangeTaggedSignedToInt32 (Node *node)
Node * InsertChangeTaggedToFloat64 (Node *node)
Node * InsertChangeUint32ToFloat64 (Node *node)
Node * InsertCheckedFloat64ToInt32 (Node *node, CheckForMinusZeroMode check, const FeedbackSource &feedback, Node *use_node)
Node * InsertChangeFloat16RawBitsToFloat64Fallback (Node *node)
Node * InsertTruncateFloat64ToFloat16RawBitsFallback (Node *node)
Node * InsertConversion (Node *node, const Operator *op, Node *use_node)
Node * InsertTruncateInt64ToInt32 (Node *node)
Node * InsertUnconditionalDeopt (Node *node, DeoptimizeReason reason, const FeedbackSource &feedback={})
Node * InsertTypeOverrideForVerifier (const Type &type, Node *node)
Node * Ieee754Fp16RawBitsToFp32RawBitsCode ()
Node * Ieee754Fp64ToFp16RawBitsCode ()
Operator const * Ieee754Fp16RawBitsToFp32RawBitsOperator ()
Operator const * Ieee754Fp64ToFp16RawBitsOperator ()
JSGraph * jsgraph () const
Isolate * isolate () const
Factory * factory () const
SimplifiedOperatorBuilder * simplified ()
MachineOperatorBuilder * machine ()
Private Attributes
TypeCache const * cache_
JSGraph * jsgraph_
JSHeapBroker * broker_
SimplifiedLoweringVerifier * verifier_
bool testing_type_errors_
bool type_error_
SetOncePointer< Node > ieee754_fp16_raw_bits_to_fp32_raw_bits_code_
SetOncePointer< Node > ieee754_fp64_to_fp16_raw_bits_code_
SetOncePointer< Operator const > ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_
SetOncePointer< Operator const > ieee754_fp64_to_fp16_raw_bits_operator_
Friends
class RepresentationChangerTester
Detailed Description
Definition at line 24 of file representation-change.h.
Constructor & Destructor Documentation
RepresentationChanger()
v8::internal::compiler::RepresentationChanger::RepresentationChanger (JSGraph * jsgraph, JSHeapBroker * broker, SimplifiedLoweringVerifier * verifier)
Definition at line 168 of file representation-change.cc.
    : cache_(TypeCache::Get()),
      jsgraph_(jsgraph),
      broker_(broker),
      verifier_(verifier),
      testing_type_errors_(false),
      type_error_(false) {}
Member Function Documentation
AdditiveSafeIntegerOverflowOperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::AdditiveSafeIntegerOverflowOperatorFor (IrOpcode::Value opcode)
Definition at line 1573 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeAdditiveSafeIntegerAdd:
      return simplified()->CheckedAdditiveSafeIntegerAdd();
    case IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract:
      return simplified()->CheckedAdditiveSafeIntegerSub();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::SimplifiedOperatorBuilder::CheckedAdditiveSafeIntegerAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedAdditiveSafeIntegerSub(), simplified(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::AdditiveSafeIntegerOverflowOp().
BigIntOperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::BigIntOperatorFor (IrOpcode::Value opcode)
Definition at line 1635 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeBigIntAdd:
      return simplified()->BigIntAdd();
    case IrOpcode::kSpeculativeBigIntSubtract:
      return simplified()->BigIntSubtract();
    case IrOpcode::kSpeculativeBigIntMultiply:
      return simplified()->BigIntMultiply();
    case IrOpcode::kSpeculativeBigIntDivide:
      return simplified()->BigIntDivide();
    case IrOpcode::kSpeculativeBigIntModulus:
      return simplified()->BigIntModulus();
    case IrOpcode::kSpeculativeBigIntBitwiseAnd:
      return simplified()->BigIntBitwiseAnd();
    case IrOpcode::kSpeculativeBigIntBitwiseOr:
      return simplified()->BigIntBitwiseOr();
    case IrOpcode::kSpeculativeBigIntBitwiseXor:
      return simplified()->BigIntBitwiseXor();
    case IrOpcode::kSpeculativeBigIntShiftLeft:
      return simplified()->BigIntShiftLeft();
    case IrOpcode::kSpeculativeBigIntShiftRight:
      return simplified()->BigIntShiftRight();
    case IrOpcode::kSpeculativeBigIntEqual:
      return simplified()->BigIntEqual();
    case IrOpcode::kSpeculativeBigIntLessThan:
      return simplified()->BigIntLessThan();
    case IrOpcode::kSpeculativeBigIntLessThanOrEqual:
      return simplified()->BigIntLessThanOrEqual();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::SimplifiedOperatorBuilder::BigIntAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntBitwiseAnd(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntBitwiseOr(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntBitwiseXor(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntDivide(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntLessThanOrEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntModulus(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntMultiply(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntShiftLeft(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntShiftRight(), v8::internal::compiler::SimplifiedOperatorBuilder::BigIntSubtract(), simplified(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::BigIntOp().
factory()
Factory* v8::internal::compiler::RepresentationChanger::factory () const [inline], [private]
Definition at line 135 of file representation-change.h.
{ return isolate()->factory(); }
Referenced by GetBitRepresentationFor().
Float64OperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Float64OperatorFor (IrOpcode::Value opcode)
Definition at line 1735 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeNumberAdd:
    case IrOpcode::kSpeculativeAdditiveSafeIntegerAdd:
    case IrOpcode::kSpeculativeSmallIntegerAdd:
    case IrOpcode::kNumberAdd:
      return machine()->Float64Add();
    case IrOpcode::kSpeculativeNumberSubtract:
    case IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract:
    case IrOpcode::kSpeculativeSmallIntegerSubtract:
    case IrOpcode::kNumberSubtract:
      return machine()->Float64Sub();
    case IrOpcode::kSpeculativeNumberMultiply:
    case IrOpcode::kNumberMultiply:
      return machine()->Float64Mul();
    case IrOpcode::kSpeculativeNumberDivide:
    case IrOpcode::kNumberDivide:
      return machine()->Float64Div();
    case IrOpcode::kSpeculativeNumberModulus:
    case IrOpcode::kNumberModulus:
      return machine()->Float64Mod();
    case IrOpcode::kNumberEqual:
    case IrOpcode::kSpeculativeNumberEqual:
      return machine()->Float64Equal();
    case IrOpcode::kNumberLessThan:
    case IrOpcode::kSpeculativeNumberLessThan:
      return machine()->Float64LessThan();
    case IrOpcode::kNumberLessThanOrEqual:
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return machine()->Float64LessThanOrEqual();
    case IrOpcode::kNumberAbs:
      return machine()->Float64Abs();
    case IrOpcode::kNumberAcos:
      return machine()->Float64Acos();
    case IrOpcode::kNumberAcosh:
      return machine()->Float64Acosh();
    case IrOpcode::kNumberAsin:
      return machine()->Float64Asin();
    case IrOpcode::kNumberAsinh:
      return machine()->Float64Asinh();
    case IrOpcode::kNumberAtan:
      return machine()->Float64Atan();
    case IrOpcode::kNumberAtanh:
      return machine()->Float64Atanh();
    case IrOpcode::kNumberAtan2:
      return machine()->Float64Atan2();
    case IrOpcode::kNumberCbrt:
      return machine()->Float64Cbrt();
    case IrOpcode::kNumberCeil:
      return machine()->Float64RoundUp().placeholder();
    case IrOpcode::kNumberCos:
      return machine()->Float64Cos();
    case IrOpcode::kNumberCosh:
      return machine()->Float64Cosh();
    case IrOpcode::kNumberExp:
      return machine()->Float64Exp();
    case IrOpcode::kNumberExpm1:
      return machine()->Float64Expm1();
    case IrOpcode::kNumberFloor:
      return machine()->Float64RoundDown().placeholder();
    case IrOpcode::kNumberFround:
      return machine()->TruncateFloat64ToFloat32();
    case IrOpcode::kNumberLog:
      return machine()->Float64Log();
    case IrOpcode::kNumberLog1p:
      return machine()->Float64Log1p();
    case IrOpcode::kNumberLog2:
      return machine()->Float64Log2();
    case IrOpcode::kNumberLog10:
      return machine()->Float64Log10();
    case IrOpcode::kNumberMax:
      return machine()->Float64Max();
    case IrOpcode::kNumberMin:
      return machine()->Float64Min();
    case IrOpcode::kSpeculativeNumberPow:
    case IrOpcode::kNumberPow:
      return machine()->Float64Pow();
    case IrOpcode::kNumberSin:
      return machine()->Float64Sin();
    case IrOpcode::kNumberSinh:
      return machine()->Float64Sinh();
    case IrOpcode::kNumberSqrt:
      return machine()->Float64Sqrt();
    case IrOpcode::kNumberTan:
      return machine()->Float64Tan();
    case IrOpcode::kNumberTanh:
      return machine()->Float64Tanh();
    case IrOpcode::kNumberTrunc:
      return machine()->Float64RoundTruncate().placeholder();
    case IrOpcode::kNumberSilenceNaN:
      return machine()->Float64SilenceNaN();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::MachineOperatorBuilder::Float64Abs(), v8::internal::compiler::MachineOperatorBuilder::Float64Acos(), v8::internal::compiler::MachineOperatorBuilder::Float64Acosh(), v8::internal::compiler::MachineOperatorBuilder::Float64Add(), v8::internal::compiler::MachineOperatorBuilder::Float64Asin(), v8::internal::compiler::MachineOperatorBuilder::Float64Asinh(), v8::internal::compiler::MachineOperatorBuilder::Float64Atan(), v8::internal::compiler::MachineOperatorBuilder::Float64Atan2(), v8::internal::compiler::MachineOperatorBuilder::Float64Atanh(), v8::internal::compiler::MachineOperatorBuilder::Float64Cbrt(), v8::internal::compiler::MachineOperatorBuilder::Float64Cos(), v8::internal::compiler::MachineOperatorBuilder::Float64Cosh(), v8::internal::compiler::MachineOperatorBuilder::Float64Div(), v8::internal::compiler::MachineOperatorBuilder::Float64Equal(), v8::internal::compiler::MachineOperatorBuilder::Float64Exp(), v8::internal::compiler::MachineOperatorBuilder::Float64Expm1(), v8::internal::compiler::MachineOperatorBuilder::Float64LessThan(), v8::internal::compiler::MachineOperatorBuilder::Float64LessThanOrEqual(), v8::internal::compiler::MachineOperatorBuilder::Float64Log(), v8::internal::compiler::MachineOperatorBuilder::Float64Log10(), v8::internal::compiler::MachineOperatorBuilder::Float64Log1p(), v8::internal::compiler::MachineOperatorBuilder::Float64Log2(), v8::internal::compiler::MachineOperatorBuilder::Float64Max(), v8::internal::compiler::MachineOperatorBuilder::Float64Min(), v8::internal::compiler::MachineOperatorBuilder::Float64Mod(), v8::internal::compiler::MachineOperatorBuilder::Float64Mul(), v8::internal::compiler::MachineOperatorBuilder::Float64Pow(), v8::internal::compiler::MachineOperatorBuilder::Float64RoundDown(), v8::internal::compiler::MachineOperatorBuilder::Float64RoundTruncate(), v8::internal::compiler::MachineOperatorBuilder::Float64RoundUp(), v8::internal::compiler::MachineOperatorBuilder::Float64SilenceNaN(), v8::internal::compiler::MachineOperatorBuilder::Float64Sin(), v8::internal::compiler::MachineOperatorBuilder::Float64Sinh(), v8::internal::compiler::MachineOperatorBuilder::Float64Sqrt(), v8::internal::compiler::MachineOperatorBuilder::Float64Sub(), v8::internal::compiler::MachineOperatorBuilder::Float64Tan(), v8::internal::compiler::MachineOperatorBuilder::Float64Tanh(), machine(), v8::internal::compiler::OptionalOperator::placeholder(), v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToFloat32(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::Float64Op().
GetBitRepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type) [private]
Definition at line 1177 of file representation-change.cc.
                                                                    {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kHeapConstant: {
      HeapObjectMatcher m(node);
      if (m.Is(factory()->false_value())) {
        return InsertTypeOverrideForVerifier(
            Type::Constant(broker_, broker_->false_value(), jsgraph()->zone()),
            jsgraph()->Int32Constant(0));
      } else if (m.Is(factory()->true_value())) {
        return InsertTypeOverrideForVerifier(
            Type::Constant(broker_, broker_->true_value(), jsgraph()->zone()),
            jsgraph()->Int32Constant(1));
      }
      break;
    }
    default:
      break;
  }
  // Select the correct X -> Bit operator.
  const Operator* op;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kBit), node);
  } else if (output_rep == MachineRepresentation::kTagged ||
             output_rep == MachineRepresentation::kTaggedPointer) {
    if (output_type.Is(Type::BooleanOrNullOrUndefined())) {
      // true is the only trueish Oddball.
      op = simplified()->ChangeTaggedToBit();
    } else {
      if (output_rep == MachineRepresentation::kTagged &&
          output_type.Maybe(Type::SignedSmall())) {
        op = simplified()->TruncateTaggedToBit();
      } else {
        // The {output_type} either doesn't include the Smi range,
        // or the {output_rep} is known to be TaggedPointer.
        op = simplified()->TruncateTaggedPointerToBit();
      }
    }
  } else if (output_rep == MachineRepresentation::kTaggedSigned) {
    if (COMPRESS_POINTERS_BOOL) {
      node = jsgraph()->graph()->NewNode(machine()->Word32Equal(), node,
                                         jsgraph()->Int32Constant(0));
    } else {
      node = jsgraph()->graph()->NewNode(machine()->WordEqual(), node,
                                         jsgraph()->IntPtrConstant(0));
    }
    return jsgraph()->graph()->NewNode(machine()->Word32Equal(), node,
                                       jsgraph()->Int32Constant(0));
  } else if (IsWord(output_rep)) {
    node = jsgraph()->graph()->NewNode(machine()->Word32Equal(), node,
                                       jsgraph()->Int32Constant(0));
    return jsgraph()->graph()->NewNode(machine()->Word32Equal(), node,
                                       jsgraph()->Int32Constant(0));
  } else if (output_rep == MachineRepresentation::kWord64) {
    node = jsgraph()->graph()->NewNode(machine()->Word64Equal(), node,
                                       jsgraph()->Int64Constant(0));
    return jsgraph()->graph()->NewNode(machine()->Word32Equal(), node,
                                       jsgraph()->Int32Constant(0));
  } else if (output_rep == MachineRepresentation::kFloat32) {
    node = jsgraph()->graph()->NewNode(machine()->Float32Abs(), node);
    return jsgraph()->graph()->NewNode(machine()->Float32LessThan(),
                                       jsgraph()->Float32Constant(0.0), node);
  } else if (output_rep == MachineRepresentation::kFloat64) {
    node = jsgraph()->graph()->NewNode(machine()->Float64Abs(), node);
    return jsgraph()->graph()->NewNode(machine()->Float64LessThan(),
                                       jsgraph()->Float64Constant(0.0), node);
  } else {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kBit);
  }
  return jsgraph()->graph()->NewNode(op, node);
}
References broker_, v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToBit(), COMPRESS_POINTERS_BOOL, v8::internal::compiler::Type::Constant(), factory(), v8::internal::compiler::MachineGraph::graph(), InsertTypeOverrideForVerifier(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Is(), v8::internal::compiler::Type::Is(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::kBit, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord64, machine(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Type::SignedSmall(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateTaggedPointerToBit(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateTaggedToBit(), TypeError(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by GetRepresentationFor().
GetFloat16RawBitsRepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info) [private]
Definition at line 689 of file representation-change.cc.
                                      {
  if (output_rep != MachineRepresentation::kFloat64) {
    node = GetFloat64RepresentationFor(node, output_rep, output_type, use_node,
                                       use_info);
  }
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kFloat64Constant:
      return jsgraph()->Uint32Constant(
          DoubleToFloat16(OpParameter<double>(node->op())));
    case IrOpcode::kNumberConstant:
    case IrOpcode::kInt32Constant:
    case IrOpcode::kFloat32Constant:
      UNREACHABLE();
    default:
      break;
  }
  // This is an impossible value; it should not be used at runtime.
  if (output_type.Is(Type::None())) {
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kFloat16RawBits),
        node);
  }
  // Insert a float64 -> float16 node.
  if (machine()->TruncateFloat64ToFloat16RawBits().IsSupported()) {
    return jsgraph()->graph()->NewNode(
        machine()->TruncateFloat64ToFloat16RawBits().op(), node);
  } else {
    return InsertTruncateFloat64ToFloat16RawBitsFallback(node);
  }
}
References v8::internal::DoubleToFloat16(), GetFloat64RepresentationFor(), v8::internal::compiler::MachineGraph::graph(), InsertTruncateFloat64ToFloat16RawBitsFallback(), v8::internal::compiler::Type::Is(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), jsgraph(), v8::internal::kFloat16RawBits, v8::internal::kFloat64, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::MachineGraph::Uint32Constant(), and v8::internal::UNREACHABLE().
Referenced by GetRepresentationFor().
GetFloat32RepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Truncation truncation) [private]
Definition at line 726 of file representation-change.cc.
                           {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kNumberConstant:
      return jsgraph()->Float32Constant(
          DoubleToFloat32(OpParameter<double>(node->op())));
    case IrOpcode::kInt32Constant:
    case IrOpcode::kFloat64Constant:
    case IrOpcode::kFloat32Constant:
      UNREACHABLE();
    default:
      break;
  }
  // Select the correct X -> Float32 operator.
  const Operator* op = nullptr;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kFloat32), node);
  } else if (IsWord(output_rep)) {
    if (output_type.Is(Type::Signed32())) {
      // int32 -> float64 -> float32
      op = machine()->ChangeInt32ToFloat64();
      node = jsgraph()->graph()->NewNode(op, node);
      op = machine()->TruncateFloat64ToFloat32();
    } else if (output_type.Is(Type::Unsigned32()) ||
               truncation.IsUsedAsWord32()) {
      // Either the output is uint32 or the uses only care about the
      // low 32 bits (so we can pick uint32 safely).
      // uint32 -> float64 -> float32
      op = machine()->ChangeUint32ToFloat64();
      node = jsgraph()->graph()->NewNode(op, node);
      op = machine()->TruncateFloat64ToFloat32();
    }
  } else if (IsAnyTagged(output_rep)) {
    if (output_type.Is(Type::NumberOrOddball())) {
      // tagged -> float64 -> float32
      if (output_type.Is(Type::Number())) {
        op = simplified()->ChangeTaggedToFloat64();
      } else {
        op = simplified()->TruncateTaggedToFloat64();
      }
      node = jsgraph()->graph()->NewNode(op, node);
      op = machine()->TruncateFloat64ToFloat32();
    }
  } else if (output_rep == MachineRepresentation::kFloat64) {
    op = machine()->TruncateFloat64ToFloat32();
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (output_type.Is(cache_->kSafeInteger)) {
      // int64 -> float64 -> float32
      op = machine()->ChangeInt64ToFloat64();
      node = jsgraph()->graph()->NewNode(op, node);
      op = machine()->TruncateFloat64ToFloat32();
    }
  }
  if (op == nullptr) {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kFloat32);
  }
  return jsgraph()->graph()->NewNode(op, node);
}
References cache_, v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToFloat64(), v8::internal::compiler::MachineOperatorBuilder::ChangeInt64ToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToFloat64(), v8::internal::compiler::MachineOperatorBuilder::ChangeUint32ToFloat64(), v8::internal::DoubleToFloat32(), v8::internal::compiler::MachineGraph::Float32Constant(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::Type::Is(), v8::internal::IsAnyTagged(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::kWord64, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToFloat32(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateTaggedToFloat64(), TypeError(), and v8::internal::UNREACHABLE().
Referenced by GetRepresentationFor().
GetFloat64RepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info) [private]
Definition at line 791 of file representation-change.cc.
                                      {
  NumberMatcher m(node);
  if (m.HasResolvedValue()) {
    // BigInts are not used as number constants.
    DCHECK(!TypeCheckIsBigInt(use_info.type_check()));
    switch (use_info.type_check()) {
      case TypeCheckKind::kNone:
      case TypeCheckKind::kNumber:
      case TypeCheckKind::kNumberOrBoolean:
      case TypeCheckKind::kNumberOrOddball:
        return jsgraph()->Float64Constant(m.ResolvedValue());
      case TypeCheckKind::kBigInt:
      case TypeCheckKind::kBigInt64:
      case TypeCheckKind::kHeapObject:
      case TypeCheckKind::kSigned32:
      case TypeCheckKind::kSigned64:
      case TypeCheckKind::kSignedSmall:
      case TypeCheckKind::kArrayIndex:
      case TypeCheckKind::kAdditiveSafeInteger:
        break;
    }
  }
  // Select the correct X -> Float64 operator.
  const Operator* op = nullptr;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kFloat64), node);
  } else if (IsWord(output_rep)) {
    if (output_type.Is(Type::Signed32()) ||
        (output_type.Is(Type::Signed32OrMinusZero()) &&
         use_info.truncation().IdentifiesZeroAndMinusZero())) {
      op = machine()->ChangeInt32ToFloat64();
    } else if (output_type.Is(Type::Unsigned32()) ||
               (output_type.Is(Type::Unsigned32OrMinusZero()) &&
                use_info.truncation().IdentifiesZeroAndMinusZero()) ||
               use_info.truncation().IsUsedAsWord32()) {
      // Either the output is uint32 or the uses only care about the
      // low 32 bits (so we can pick uint32 safely).
      op = machine()->ChangeUint32ToFloat64();
    }
  } else if (output_rep == MachineRepresentation::kBit) {
    CHECK(output_type.Is(Type::Boolean()));
    if (use_info.truncation().TruncatesOddballAndBigIntToNumber() ||
        use_info.type_check() == TypeCheckKind::kNumberOrBoolean ||
        use_info.type_check() == TypeCheckKind::kNumberOrOddball) {
      op = machine()->ChangeUint32ToFloat64();
    } else {
      CHECK_NE(use_info.type_check(), TypeCheckKind::kNone);
      Node* unreachable =
          InsertUnconditionalDeopt(use_node, DeoptimizeReason::kNotAHeapNumber);
      return jsgraph()->graph()->NewNode(
          jsgraph()->common()->DeadValue(MachineRepresentation::kFloat64),
          unreachable);
    }
  } else if (IsAnyTagged(output_rep)) {
    if (output_type.Is(Type::Undefined())) {
      if (use_info.type_check() == TypeCheckKind::kNumberOrOddball ||
          (use_info.type_check() == TypeCheckKind::kNone &&
           use_info.truncation().TruncatesOddballAndBigIntToNumber())) {
        return jsgraph()->Float64Constant(
            std::numeric_limits<double>::quiet_NaN());
      } else if (use_info.truncation()
                     .TruncatesBooleanAndNullAndBigIntToNumber()) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        return jsgraph()->Float64Constant(UndefinedNan());
#else
        UNREACHABLE();
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      } else {
        DCHECK(use_info.type_check() == TypeCheckKind::kNone ||
               use_info.type_check() == TypeCheckKind::kNumber ||
               use_info.type_check() == TypeCheckKind::kNumberOrBoolean);
        Node* unreachable = InsertUnconditionalDeopt(
            use_node, use_info.type_check() == TypeCheckKind::kNumber
                          ? DeoptimizeReason::kNotANumber
                          : DeoptimizeReason::kNotANumberOrBoolean);
        return jsgraph()->graph()->NewNode(
            jsgraph()->common()->DeadValue(MachineRepresentation::kFloat64),
            unreachable);
      }
    } else if (output_rep == MachineRepresentation::kTaggedSigned) {
      node = InsertChangeTaggedSignedToInt32(node);
      op = machine()->ChangeInt32ToFloat64();
    } else if (output_type.Is(Type::Number())) {
      op = simplified()->ChangeTaggedToFloat64();
    } else if ((output_type.Is(Type::NumberOrOddball()) &&
                use_info.truncation().TruncatesOddballAndBigIntToNumber()) ||
               output_type.Is(Type::NumberOrHole())) {
      // JavaScript 'null' is an Oddball that results in +0 when truncated to
      // Number. In a context like -0 == null, which must evaluate to false,
      // this truncation must not happen. For this reason we restrict this
      // case to when either the user explicitly requested a float (and thus
      // wants +0 if null is the input) or we know from the types that the
      // input can only be Number | Hole. The latter is necessary to handle
      // the operator CheckFloat64Hole. We did not put in the type (Number |
      // Oddball \ Null) to discover more bugs related to this conversion via
      // crashes.
      op = simplified()->TruncateTaggedToFloat64();
    } else if (output_type.Is(Type::NumberOrUndefined()) &&
               use_info.truncation()
                   .TruncatesBooleanAndNullAndBigIntToNumber()) {
      op = simplified()->TruncateTaggedToFloat64PreserveUndefined();
    } else if (use_info.type_check() == TypeCheckKind::kNumber ||
               (use_info.type_check() == TypeCheckKind::kNumberOrOddball &&
                !output_type.Maybe(Type::BooleanOrNullOrNumber()))) {
      op = simplified()->CheckedTaggedToFloat64(CheckTaggedInputMode::kNumber,
                                                use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kNumberOrBoolean) {
      op = simplified()->CheckedTaggedToFloat64(
          CheckTaggedInputMode::kNumberOrBoolean, use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kNumberOrOddball) {
      op = simplified()->CheckedTaggedToFloat64(
          CheckTaggedInputMode::kNumberOrOddball, use_info.feedback());
    }
  } else if (output_rep == MachineRepresentation::kFloat32) {
    op = machine()->ChangeFloat32ToFloat64();
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (output_type.Is(cache_->kSafeInteger)) {
      op = machine()->ChangeInt64ToFloat64();
    }
  }
  if (op == nullptr) {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kFloat64);
  }
  return InsertConversion(node, op, use_node);
}
References cache_, v8::internal::compiler::MachineOperatorBuilder::ChangeFloat32ToFloat64(), v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToFloat64(), v8::internal::compiler::MachineOperatorBuilder::ChangeInt64ToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToFloat64(), v8::internal::compiler::MachineOperatorBuilder::ChangeUint32ToFloat64(), CHECK, CHECK_NE, v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToFloat64(), v8::internal::DCHECK(), v8::internal::compiler::UseInfo::feedback(), v8::internal::compiler::MachineGraph::Float64Constant(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), InsertChangeTaggedSignedToInt32(), InsertConversion(), InsertUnconditionalDeopt(), v8::internal::compiler::Type::Is(), v8::internal::IsAnyTagged(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kArrayIndex, v8::internal::compiler::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBit, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::kHeapObject, v8::internal::compiler::kNone, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::compiler::kSigned32, v8::internal::compiler::kSigned64, v8::internal::compiler::kSignedSmall, v8::internal::kTaggedSigned, v8::internal::kWord64, machine(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), simplified(), v8::internal::compiler::Truncation::TruncatesBooleanAndNullAndBigIntToNumber(), v8::internal::compiler::Truncation::TruncatesOddballAndBigIntToNumber(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateTaggedToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateTaggedToFloat64PreserveUndefined(), v8::internal::compiler::UseInfo::truncation(), v8::internal::compiler::UseInfo::type_check(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::TypeCheckIsBigInt(), TypeError(), v8::internal::compiler::Undefined, and v8::internal::UNREACHABLE().
Referenced by GetFloat16RawBitsRepresentationFor(), and GetRepresentationFor().
GetRepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetRepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info)
Definition at line 182 of file representation-change.cc.
                                      {
  // We are currently not inserting conversions in machine graphs.
  // We might add that, though.
  DCHECK_IMPLIES(!output_type.IsNone(), !output_type.Is(Type::Machine()));
  if (output_rep == MachineRepresentation::kNone && !output_type.IsNone()) {
    // The output representation should be set if the type is inhabited (i.e.,
    // if the value is possible).
    return TypeError(node, output_rep, output_type, use_info.representation());
  }
  if (output_type.Is(Type::BigInt()) &&
      output_rep == MachineRepresentation::kWord64 &&
      !TypeCheckIsBigInt(use_info.type_check())) {
    // Rematerialize any truncated BigInt if user is not expecting a BigInt.
    if (output_type.Is(Type::UnsignedBigInt64())) {
      node = InsertConversion(node, simplified()->ChangeUint64ToBigInt(),
                              use_node);
    } else {
      node =
          InsertConversion(node, simplified()->ChangeInt64ToBigInt(), use_node);
    }
    output_rep = MachineRepresentation::kTaggedPointer;
  } else if (output_rep == MachineRepresentation::kFloat16RawBits) {
    // Float16Array elements are loaded as raw bits in a word16 then converted
    // to float64, since architectures have spotty support for fp16.
    DCHECK(output_type.Is(Type::Number()));
    if (machine()->ChangeFloat16RawBitsToFloat64().IsSupported()) {
      node = jsgraph()->graph()->NewNode(
          machine()->ChangeFloat16RawBitsToFloat64().op(), node);
    } else {
      node = InsertChangeFloat16RawBitsToFloat64Fallback(node);
    }
    output_rep = MachineRepresentation::kFloat64;
  }
  // Handle the no-op shortcuts when no checking is necessary.
  if (use_info.type_check() == TypeCheckKind::kNone ||
      // TODO(nicohartmann@, chromium:1077804): Ignoring {use_info.type_check()}
      // in case the representation already matches is not correct. For now,
      // this behavior is disabled only for TypeCheckKind::kBigInt, but should
      // be fixed for all other type checks.
      (output_rep != MachineRepresentation::kWord32 &&
       (use_info.type_check() != TypeCheckKind::kAdditiveSafeInteger &&
        !TypeCheckIsBigInt(use_info.type_check())))) {
    if (use_info.representation() == output_rep) {
      // Representations are the same. That's a no-op.
      return node;
    }
    if (IsWord(use_info.representation()) && IsWord(output_rep)) {
      // Both are words less than or equal to 32-bits.
      // Since loads of integers from memory implicitly sign or zero extend the
      // value to the full machine word size and stores implicitly truncate,
      // no representation change is necessary.
      return node;
    }
  }
  switch (use_info.representation()) {
    case MachineRepresentation::kTaggedSigned:
      DCHECK(use_info.type_check() == TypeCheckKind::kNone ||
             use_info.type_check() == TypeCheckKind::kSignedSmall);
      return GetTaggedSignedRepresentationFor(node, output_rep, output_type,
                                              use_node, use_info);
    case MachineRepresentation::kTaggedPointer:
      DCHECK(use_info.type_check() == TypeCheckKind::kNone ||
             use_info.type_check() == TypeCheckKind::kHeapObject ||
             use_info.type_check() == TypeCheckKind::kBigInt);
      return GetTaggedPointerRepresentationFor(node, output_rep, output_type,
                                               use_node, use_info);
    case MachineRepresentation::kTagged:
      DCHECK_EQ(TypeCheckKind::kNone, use_info.type_check());
      return GetTaggedRepresentationFor(node, output_rep, output_type,
                                        use_info.truncation());
    case MachineRepresentation::kFloat16RawBits:
      DCHECK_EQ(TypeCheckKind::kNone, use_info.type_check());
      return GetFloat16RawBitsRepresentationFor(node, output_rep, output_type,
                                                use_node, use_info);
    case MachineRepresentation::kFloat32:
      DCHECK_EQ(TypeCheckKind::kNone, use_info.type_check());
      return GetFloat32RepresentationFor(node, output_rep, output_type,
                                         use_info.truncation());
    case MachineRepresentation::kFloat64:
      DCHECK(use_info.type_check() == TypeCheckKind::kNone ||
             use_info.type_check() == TypeCheckKind::kNumber ||
             use_info.type_check() == TypeCheckKind::kNumberOrBoolean ||
             use_info.type_check() == TypeCheckKind::kNumberOrOddball);
      return GetFloat64RepresentationFor(node, output_rep, output_type,
                                         use_node, use_info);
    case MachineRepresentation::kBit:
      DCHECK_EQ(TypeCheckKind::kNone, use_info.type_check());
      return GetBitRepresentationFor(node, output_rep, output_type);
    case MachineRepresentation::kWord8:
    case MachineRepresentation::kWord16:
    case MachineRepresentation::kWord32:
      return GetWord32RepresentationFor(node, output_rep, output_type, use_node,
                                        use_info);
    case MachineRepresentation::kWord64:
      DCHECK(use_info.type_check() == TypeCheckKind::kNone ||
             use_info.type_check() == TypeCheckKind::kSigned64 ||
             use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger ||
             TypeCheckIsBigInt(use_info.type_check()) ||
             use_info.type_check() == TypeCheckKind::kArrayIndex);
      return GetWord64RepresentationFor(node, output_rep, output_type, use_node,
                                        use_info);
    case MachineRepresentation::kSimd128:
    case MachineRepresentation::kSimd256:
    case MachineRepresentation::kNone:
      return node;
    case MachineRepresentation::kFloat16:
    case MachineRepresentation::kCompressed:
    case MachineRepresentation::kCompressedPointer:
    case MachineRepresentation::kSandboxedPointer:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kMapWord:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, GetBitRepresentationFor(), GetFloat16RawBitsRepresentationFor(), GetFloat32RepresentationFor(), GetFloat64RepresentationFor(), GetTaggedPointerRepresentationFor(), GetTaggedRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), GetWord64RepresentationFor(), v8::internal::compiler::MachineGraph::graph(), InsertChangeFloat16RawBitsToFloat64Fallback(), InsertConversion(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsNone(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kArrayIndex, v8::internal::compiler::kBigInt, v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::kHeapObject, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::compiler::kNone, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::compiler::kSigned64, v8::internal::compiler::kSignedSmall, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::UseInfo::representation(), simplified(), v8::internal::compiler::UseInfo::truncation(), v8::internal::compiler::UseInfo::type_check(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::TypeCheckIsBigInt(), TypeError(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::ConvertInput().
GetTaggedPointerRepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info) [private]
Definition at line 446 of file representation-change.cc.
                                      {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kHeapConstant:
      if (TypeCheckIsBigInt(use_info.type_check())) break;
      return node; // No change necessary.
    case IrOpcode::kInt32Constant:
    case IrOpcode::kFloat64Constant:
    case IrOpcode::kFloat32Constant:
      UNREACHABLE();
    default:
      break;
  }
  // Select the correct X -> TaggedPointer operator.
  Operator const* op;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kTaggedPointer),
        node);
  }
  if (TypeCheckIsBigInt(use_info.type_check()) &&
      !output_type.Is(Type::BigInt())) {
    // BigInt checks can only be performed on tagged representations. Note that
    // a corresponding check is inserted down below.
    if (!CanBeTaggedPointer(output_rep)) {
      Node* unreachable =
          InsertUnconditionalDeopt(use_node, DeoptimizeReason::kNotABigInt);
      return jsgraph()->graph()->NewNode(
          jsgraph()->common()->DeadValue(MachineRepresentation::kTaggedPointer),
          unreachable);
    }
  }
  if (output_rep == MachineRepresentation::kBit) {
    if (output_type.Is(Type::Boolean())) {
      op = simplified()->ChangeBitToTagged();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTagged);
    }
  } else if (IsWord(output_rep)) {
    if (output_type.Is(Type::Unsigned32())) {
      // uint32 -> float64 -> tagged
      node = InsertChangeUint32ToFloat64(node);
    } else if (output_type.Is(Type::Signed32())) {
      // int32 -> float64 -> tagged
      node = InsertChangeInt32ToFloat64(node);
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedPointer);
    }
    op = simplified()->ChangeFloat64ToTaggedPointer();
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (output_type.Is(cache_->kSafeInteger)) {
      // int64 -> float64 -> tagged pointer
      op = machine()->ChangeInt64ToFloat64();
      node = jsgraph()->graph()->NewNode(op, node);
      op = simplified()->ChangeFloat64ToTaggedPointer();
    } else if (output_type.Is(Type::SignedBigInt64()) &&
               use_info.type_check() == TypeCheckKind::kBigInt) {
      op = simplified()->ChangeInt64ToBigInt();
    } else if (output_type.Is(Type::UnsignedBigInt64()) &&
               use_info.type_check() == TypeCheckKind::kBigInt) {
      op = simplified()->ChangeUint64ToBigInt();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedPointer);
    }
  } else if (output_rep == MachineRepresentation::kFloat32) {
    if (output_type.Is(Type::Number())) {
      // float32 -> float64 -> tagged
      node = InsertChangeFloat32ToFloat64(node);
      op = simplified()->ChangeFloat64ToTaggedPointer();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedPointer);
    }
  } else if (output_rep == MachineRepresentation::kFloat64) {
    if (output_type.Is(Type::Number())) {
      // float64 -> tagged
      op = simplified()->ChangeFloat64ToTaggedPointer();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedPointer);
    }
  } else if (IsAnyTagged(output_rep)) {
    if (use_info.type_check() == TypeCheckKind::kBigInt) {
      if (output_type.Is(Type::BigInt())) {
        DCHECK_NE(output_rep, MachineRepresentation::kTaggedSigned);
        return node;
      }
      op = simplified()->CheckBigInt(use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kBigInt64) {
      if (output_type.Is(Type::SignedBigInt64())) {
        DCHECK_NE(output_rep, MachineRepresentation::kTaggedSigned);
        return node;
      }
      if (!output_type.Is(Type::BigInt())) {
        node = InsertConversion(
            node, simplified()->CheckBigInt(use_info.feedback()), use_node);
      }
      op = simplified()->CheckedBigIntToBigInt64(use_info.feedback());
    } else if (output_rep == MachineRepresentation::kTaggedPointer ||
               !output_type.Maybe(Type::SignedSmall())) {
      DCHECK_NE(output_rep, MachineRepresentation::kTaggedSigned);
      return node;
    } else {
      op = simplified()->CheckedTaggedToTaggedPointer(use_info.feedback());
    }
  } else {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kTaggedPointer);
  }
  return InsertConversion(node, op, use_node);
}
References cache_, v8::internal::CanBeTaggedPointer(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeBitToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeFloat64ToTaggedPointer(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt64ToBigInt(), v8::internal::compiler::MachineOperatorBuilder::ChangeInt64ToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeUint64ToBigInt(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckBigInt(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedBigIntToBigInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToTaggedPointer(), DCHECK_NE, v8::internal::compiler::UseInfo::feedback(), v8::internal::compiler::MachineGraph::graph(), InsertChangeFloat32ToFloat64(), InsertChangeInt32ToFloat64(), InsertChangeUint32ToFloat64(), InsertConversion(), InsertUnconditionalDeopt(), v8::internal::compiler::Type::Is(), v8::internal::IsAnyTagged(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::compiler::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBit, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord64, machine(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Type::SignedSmall(), simplified(), v8::internal::compiler::UseInfo::type_check(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::TypeCheckIsBigInt(), TypeError(), and v8::internal::UNREACHABLE().
Referenced by GetRepresentationFor(), and GetWord64RepresentationFor().
GetTaggedRepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Truncation truncation) [private]
Definition at line 566 of file representation-change.cc.
                           {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kNumberConstant:
    case IrOpcode::kHeapConstant:
      return node; // No change necessary.
    case IrOpcode::kInt32Constant:
    case IrOpcode::kFloat64Constant:
    case IrOpcode::kFloat32Constant:
      UNREACHABLE();
    default:
      break;
  }
  if (output_rep == MachineRepresentation::kTaggedSigned ||
      output_rep == MachineRepresentation::kTaggedPointer ||
      output_rep == MachineRepresentation::kMapWord) {
    // this is a no-op.
    return node;
  }
  // Select the correct X -> Tagged operator.
  const Operator* op;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kTagged), node);
  } else if (output_rep == MachineRepresentation::kBit) {
    if (output_type.Is(Type::Boolean())) {
      op = simplified()->ChangeBitToTagged();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTagged);
    }
  } else if (IsWord(output_rep)) {
    if (output_type.Is(Type::Signed31())) {
      op = simplified()->ChangeInt31ToTaggedSigned();
    } else if (output_type.Is(Type::Signed32()) ||
               (output_type.Is(Type::Signed32OrMinusZero()) &&
                truncation.IdentifiesZeroAndMinusZero())) {
      op = simplified()->ChangeInt32ToTagged();
    } else if (output_type.Is(Type::Unsigned32()) ||
               (output_type.Is(Type::Unsigned32OrMinusZero()) &&
                truncation.IdentifiesZeroAndMinusZero()) ||
               truncation.IsUsedAsWord32()) {
      // Either the output is uint32 or the uses only care about the
      // low 32 bits (so we can pick uint32 safely).
      op = simplified()->ChangeUint32ToTagged();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTagged);
    }
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (output_type.Is(Type::Signed31())) {
      // int64 -> int32 -> tagged signed
      node = InsertTruncateInt64ToInt32(node);
      op = simplified()->ChangeInt31ToTaggedSigned();
    } else if (output_type.Is(Type::Signed32())) {
      // int64 -> int32 -> tagged
      node = InsertTruncateInt64ToInt32(node);
      op = simplified()->ChangeInt32ToTagged();
    } else if (output_type.Is(Type::Unsigned32())) {
      // int64 -> uint32 -> tagged
      node = InsertTruncateInt64ToInt32(node);
      op = simplified()->ChangeUint32ToTagged();
    } else if (output_type.Is(cache_->kPositiveSafeInteger)) {
      // uint64 -> tagged
      op = simplified()->ChangeUint64ToTagged();
    } else if (output_type.Is(cache_->kSafeInteger)) {
      // int64 -> tagged
      op = simplified()->ChangeInt64ToTagged();
    } else if (output_type.Is(Type::SignedBigInt64())) {
      // int64 -> BigInt
      op = simplified()->ChangeInt64ToBigInt();
    } else if (output_type.Is(Type::UnsignedBigInt64())) {
      // uint64 -> BigInt
      op = simplified()->ChangeUint64ToBigInt();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTagged);
    }
  } else if (output_rep ==
             MachineRepresentation::kFloat32) { // float32 -> float64 -> tagged
    node = InsertChangeFloat32ToFloat64(node);
    op = simplified()->ChangeFloat64ToTagged(
        output_type.Maybe(Type::MinusZero())
            ? CheckForMinusZeroMode::kCheckForMinusZero
            : CheckForMinusZeroMode::kDontCheckForMinusZero);
  } else if (output_rep == MachineRepresentation::kFloat64) {
    if (output_type.Is(Type::Signed31())) { // float64 -> int32 -> tagged
      node = InsertChangeFloat64ToInt32(node);
      op = simplified()->ChangeInt31ToTaggedSigned();
    } else if (output_type.Is(
                   Type::Signed32())) { // float64 -> int32 -> tagged
      node = InsertChangeFloat64ToInt32(node);
      op = simplified()->ChangeInt32ToTagged();
    } else if (output_type.Is(
                   Type::Unsigned32())) { // float64 -> uint32 -> tagged
      node = InsertChangeFloat64ToUint32(node);
      op = simplified()->ChangeUint32ToTagged();
    } else if (output_type.Is(Type::Number()) ||
               (output_type.Is(Type::NumberOrOddball()) &&
                truncation.TruncatesOddballAndBigIntToNumber())) {
      op = simplified()->ChangeFloat64ToTagged(
          output_type.Maybe(Type::MinusZero())
              ? CheckForMinusZeroMode::kCheckForMinusZero
              : CheckForMinusZeroMode::kDontCheckForMinusZero);
    } else if (output_type.Is(Type::NumberOrUndefined())) {
      op = simplified()->ChangeFloat64OrUndefinedToTagged(
          output_type.Maybe(Type::MinusZero())
              ? CheckForMinusZeroMode::kCheckForMinusZero
              : CheckForMinusZeroMode::kDontCheckForMinusZero);
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTagged);
    }
  } else {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kTagged);
  }
  return jsgraph()->graph()->NewNode(op, node);
}
References cache_, v8::internal::compiler::SimplifiedOperatorBuilder::ChangeBitToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeFloat64OrUndefinedToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeFloat64ToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt31ToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt32ToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt64ToBigInt(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt64ToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeUint32ToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeUint64ToBigInt(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeUint64ToTagged(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), InsertChangeFloat32ToFloat64(), InsertChangeFloat64ToInt32(), InsertChangeFloat64ToUint32(), InsertTruncateInt64ToInt32(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::kBit, v8::internal::compiler::kCheckForMinusZero, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kMapWord, v8::internal::compiler::TypeCache::kPositiveSafeInteger, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord64, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::opcode(), simplified(), v8::internal::compiler::Truncation::TruncatesOddballAndBigIntToNumber(), TypeError(), and v8::internal::UNREACHABLE().
Referenced by GetRepresentationFor().
GetTaggedSignedRepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info) [private]
Definition at line 304 of file representation-change.cc.
                                      {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kNumberConstant:
      if (output_type.Is(Type::SignedSmall())) {
        return node;
      }
      break;
    default:
      break;
  }
  // Select the correct X -> Tagged operator.
  const Operator* op;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kTaggedSigned),
        node);
  } else if (IsWord(output_rep)) {
    if (output_type.Is(Type::Signed31())) {
      op = simplified()->ChangeInt31ToTaggedSigned();
    } else if (output_type.Is(Type::Signed32())) {
      if (SmiValuesAre32Bits()) {
        op = simplified()->ChangeInt32ToTagged();
      } else if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
        op = simplified()->CheckedInt32ToTaggedSigned(use_info.feedback());
      } else {
        return TypeError(node, output_rep, output_type,
                         MachineRepresentation::kTaggedSigned);
      }
    } else if (output_type.Is(Type::Unsigned32()) &&
               use_info.type_check() == TypeCheckKind::kSignedSmall) {
      op = simplified()->CheckedUint32ToTaggedSigned(use_info.feedback());
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedSigned);
    }
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (output_type.Is(Type::Signed31())) {
      // int64 -> int32 -> tagged signed
      node = InsertTruncateInt64ToInt32(node);
      op = simplified()->ChangeInt31ToTaggedSigned();
    } else if (output_type.Is(Type::Signed32()) && SmiValuesAre32Bits()) {
      // int64 -> int32 -> tagged signed
      node = InsertTruncateInt64ToInt32(node);
      op = simplified()->ChangeInt32ToTagged();
    } else if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
      if (output_type.Is(cache_->kPositiveSafeInteger)) {
        op = simplified()->CheckedUint64ToTaggedSigned(use_info.feedback());
      } else if (output_type.Is(cache_->kSafeInteger)) {
        op = simplified()->CheckedInt64ToTaggedSigned(use_info.feedback());
      } else {
        return TypeError(node, output_rep, output_type,
                         MachineRepresentation::kTaggedSigned);
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedSigned);
    }
  } else if (output_rep == MachineRepresentation::kFloat64) {
    if (output_type.Is(Type::Signed31())) {
      // float64 -> int32 -> tagged signed
      node = InsertChangeFloat64ToInt32(node);
      op = simplified()->ChangeInt31ToTaggedSigned();
    } else if (output_type.Is(Type::Signed32())) {
      // float64 -> int32 -> tagged signed
      node = InsertChangeFloat64ToInt32(node);
      if (SmiValuesAre32Bits()) {
        op = simplified()->ChangeInt32ToTagged();
      } else if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
        op = simplified()->CheckedInt32ToTaggedSigned(use_info.feedback());
      } else {
        return TypeError(node, output_rep, output_type,
                         MachineRepresentation::kTaggedSigned);
      }
    } else if (output_type.Is(Type::Unsigned32()) &&
               use_info.type_check() == TypeCheckKind::kSignedSmall) {
      // float64 -> uint32 -> tagged signed
      node = InsertChangeFloat64ToUint32(node);
      op = simplified()->CheckedUint32ToTaggedSigned(use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
      node = InsertCheckedFloat64ToInt32(
          node,
          output_type.Maybe(Type::MinusZero())
              ? CheckForMinusZeroMode::kCheckForMinusZero
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback(), use_node);
      if (SmiValuesAre32Bits()) {
        op = simplified()->ChangeInt32ToTagged();
      } else {
        op = simplified()->CheckedInt32ToTaggedSigned(use_info.feedback());
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedSigned);
    }
  } else if (output_rep == MachineRepresentation::kFloat32) {
    if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
      node = InsertChangeFloat32ToFloat64(node);
      node = InsertCheckedFloat64ToInt32(
          node,
          output_type.Maybe(Type::MinusZero())
              ? CheckForMinusZeroMode::kCheckForMinusZero
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback(), use_node);
      if (SmiValuesAre32Bits()) {
        op = simplified()->ChangeInt32ToTagged();
      } else {
        op = simplified()->CheckedInt32ToTaggedSigned(use_info.feedback());
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedSigned);
    }
  } else if (CanBeTaggedPointer(output_rep)) {
    if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
      op = simplified()->CheckedTaggedToTaggedSigned(use_info.feedback());
    } else if (output_type.Is(Type::SignedSmall())) {
      op = simplified()->ChangeTaggedToTaggedSigned();
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedSigned);
    }
  } else if (output_rep == MachineRepresentation::kBit) {
    if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
      // TODO(turbofan): Consider adding a Bailout operator that just deopts.
      // Also use that for MachineRepresentation::kPointer case above.
      node = InsertChangeBitToTagged(node);
      op = simplified()->CheckedTaggedToTaggedSigned(use_info.feedback());
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kTaggedSigned);
    }
  } else {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kTaggedSigned);
  }
  return InsertConversion(node, op, use_node);
}
References cache_, v8::internal::CanBeTaggedPointer(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt31ToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeInt32ToTagged(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt32ToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64ToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint32ToTaggedSigned(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint64ToTaggedSigned(), v8::internal::compiler::UseInfo::feedback(), v8::internal::compiler::MachineGraph::graph(), InsertChangeBitToTagged(), InsertChangeFloat32ToFloat64(), InsertChangeFloat64ToInt32(), InsertChangeFloat64ToUint32(), InsertCheckedFloat64ToInt32(), InsertConversion(), InsertTruncateInt64ToInt32(), v8::internal::compiler::Type::Is(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::kBit, v8::internal::compiler::kCheckForMinusZero, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::TypeCache::kPositiveSafeInteger, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::compiler::kSignedSmall, v8::internal::kTaggedSigned, v8::internal::kWord64, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Type::SignedSmall(), simplified(), v8::internal::SmiValuesAre32Bits(), v8::internal::compiler::UseInfo::type_check(), and TypeError().
Referenced by GetRepresentationFor().
GetWord32RepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info) [private]
Definition at line 940 of file representation-change.cc.
                                      {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kInt32Constant:
    case IrOpcode::kInt64Constant:
    case IrOpcode::kFloat32Constant:
    case IrOpcode::kFloat64Constant:
      UNREACHABLE();
    case IrOpcode::kNumberConstant: {
      double const fv = OpParameter<double>(node->op());
      if (use_info.type_check() == TypeCheckKind::kNone ||
          ((use_info.type_check() == TypeCheckKind::kSignedSmall ||
            use_info.type_check() == TypeCheckKind::kSigned32 ||
            use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger ||
            use_info.type_check() == TypeCheckKind::kNumber ||
            use_info.type_check() == TypeCheckKind::kNumberOrOddball ||
            use_info.type_check() == TypeCheckKind::kArrayIndex) &&
           IsInt32Double(fv))) {
        return InsertTypeOverrideForVerifier(NodeProperties::GetType(node),
                                             MakeTruncatedInt32Constant(fv));
      }
      break;
    }
    default:
      break;
  }
  // Select the correct X -> Word32 operator.
  const Operator* op = nullptr;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kWord32), node);
  } else if (output_rep == MachineRepresentation::kBit) {
    CHECK(output_type.Is(Type::Boolean()));
    if (use_info.truncation().IsUsedAsWord32()) {
      return node;
    } else {
      CHECK(Truncation::Any(kIdentifyZeros)
                .IsLessGeneralThan(use_info.truncation()));
      CHECK_NE(use_info.type_check(), TypeCheckKind::kNone);
      CHECK_NE(use_info.type_check(), TypeCheckKind::kNumberOrOddball);
      Node* unreachable =
          InsertUnconditionalDeopt(use_node, DeoptimizeReason::kNotASmi);
      return jsgraph()->graph()->NewNode(
          jsgraph()->common()->DeadValue(MachineRepresentation::kWord32),
          unreachable);
    }
  } else if (output_rep == MachineRepresentation::kFloat64) {
    if (output_type.Is(Type::Signed32())) {
      op = machine()->ChangeFloat64ToInt32();
    } else if (use_info.type_check() == TypeCheckKind::kSignedSmall ||
               use_info.type_check() == TypeCheckKind::kSigned32 ||
               use_info.type_check() == TypeCheckKind::kArrayIndex) {
      op = simplified()->CheckedFloat64ToInt32(
          output_type.Maybe(Type::MinusZero())
              ? use_info.minus_zero_check()
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback());
    } else if (output_type.Is(Type::Unsigned32())) {
      op = machine()->ChangeFloat64ToUint32();
    } else if (use_info.truncation().IsUsedAsWord32()) {
      if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
        if (output_type.Is(cache_->kAdditiveSafeInteger)) {
          op = machine()->TruncateFloat64ToWord32();
        } else {
          op = simplified()->CheckedFloat64ToAdditiveSafeInteger(
              output_type.Maybe(Type::MinusZero())
                  ? use_info.minus_zero_check()
                  : CheckForMinusZeroMode::kDontCheckForMinusZero,
              use_info.feedback());
          node = InsertConversion(node, op, use_node);
          op = machine()->TruncateInt64ToInt32();
        }
      } else {
        op = machine()->TruncateFloat64ToWord32();
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord32);
    }
  } else if (output_rep == MachineRepresentation::kFloat32) {
    node = InsertChangeFloat32ToFloat64(node); // float32 -> float64 -> int32
    if (output_type.Is(Type::Signed32())) {
      op = machine()->ChangeFloat64ToInt32();
    } else if (use_info.type_check() == TypeCheckKind::kSignedSmall ||
               use_info.type_check() == TypeCheckKind::kSigned32 ||
               use_info.type_check() == TypeCheckKind::kArrayIndex) {
      op = simplified()->CheckedFloat64ToInt32(
          output_type.Maybe(Type::MinusZero())
              ? use_info.minus_zero_check()
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback());
    } else if (output_type.Is(Type::Unsigned32())) {
      op = machine()->ChangeFloat64ToUint32();
    } else if (use_info.truncation().IsUsedAsWord32()) {
      if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
        if (output_type.Is(cache_->kAdditiveSafeInteger)) {
          op = machine()->TruncateFloat64ToWord32();
        } else {
          op = simplified()->CheckedFloat64ToAdditiveSafeInteger(
              output_type.Maybe(Type::MinusZero())
                  ? use_info.minus_zero_check()
                  : CheckForMinusZeroMode::kDontCheckForMinusZero,
              use_info.feedback());
          node = InsertConversion(node, op, use_node);
          op = machine()->TruncateInt64ToInt32();
        }
      } else {
        op = machine()->TruncateFloat64ToWord32();
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord32);
    }
  } else if (IsAnyTagged(output_rep)) {
    if (output_rep == MachineRepresentation::kTaggedSigned &&
        output_type.Is(Type::SignedSmall())) {
      op = simplified()->ChangeTaggedSignedToInt32();
    } else if (output_type.Is(Type::Signed32())) {
      op = simplified()->ChangeTaggedToInt32();
    } else if (use_info.type_check() == TypeCheckKind::kSignedSmall) {
      op = simplified()->CheckedTaggedSignedToInt32(use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kSigned32) {
      op = simplified()->CheckedTaggedToInt32(
          output_type.Maybe(Type::MinusZero())
              ? use_info.minus_zero_check()
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kArrayIndex) {
      op = simplified()->CheckedTaggedToArrayIndex(use_info.feedback());
    } else if (output_type.Is(Type::Unsigned32())) {
      op = simplified()->ChangeTaggedToUint32();
    } else if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
      op = simplified()->CheckedTruncateTaggedToWord32(
          CheckTaggedInputMode::kAdditiveSafeInteger, use_info.feedback());
    } else if (use_info.truncation().IsUsedAsWord32()) {
      if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
        if (output_type.Is(cache_->kAdditiveSafeInteger)) {
          op = simplified()->TruncateTaggedToWord32();
        } else {
          op = simplified()->CheckedTruncateTaggedToWord32(
              CheckTaggedInputMode::kAdditiveSafeInteger, use_info.feedback());
        }
      } else if (output_type.Is(Type::NumberOrOddballOrHole())) {
        op = simplified()->TruncateTaggedToWord32();
      } else if (use_info.type_check() == TypeCheckKind::kNumber) {
        op = simplified()->CheckedTruncateTaggedToWord32(
            CheckTaggedInputMode::kNumber, use_info.feedback());
      } else if (use_info.type_check() == TypeCheckKind::kNumberOrOddball) {
        op = simplified()->CheckedTruncateTaggedToWord32(
            CheckTaggedInputMode::kNumberOrOddball, use_info.feedback());
      } else {
        return TypeError(node, output_rep, output_type,
                         MachineRepresentation::kWord32);
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord32);
    }
  } else if (output_rep == MachineRepresentation::kWord32) {
    // Only the checked case should get here, the non-checked case is
    // handled in GetRepresentationFor.
    if (use_info.type_check() == TypeCheckKind::kSignedSmall ||
        use_info.type_check() == TypeCheckKind::kSigned32 ||
        use_info.type_check() == TypeCheckKind::kArrayIndex) {
      bool identify_zeros = use_info.truncation().IdentifiesZeroAndMinusZero();
      if (output_type.Is(Type::Signed32()) ||
          (identify_zeros && output_type.Is(Type::Signed32OrMinusZero()))) {
        return node;
      } else if (output_type.Is(Type::Unsigned32()) ||
                 (identify_zeros &&
                  output_type.Is(Type::Unsigned32OrMinusZero()))) {
        op = simplified()->CheckedUint32ToInt32(use_info.feedback());
      } else {
        return TypeError(node, output_rep, output_type,
                         MachineRepresentation::kWord32);
      }
    } else if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger ||
               use_info.type_check() == TypeCheckKind::kNumber ||
               use_info.type_check() == TypeCheckKind::kNumberOrOddball) {
      return node;
    }
  } else if (output_rep == MachineRepresentation::kWord8 ||
             output_rep == MachineRepresentation::kWord16) {
    DCHECK_EQ(MachineRepresentation::kWord32, use_info.representation());
    DCHECK(use_info.type_check() == TypeCheckKind::kSignedSmall ||
           use_info.type_check() == TypeCheckKind::kSigned32 ||
           use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger);
    return node;
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (output_type.Is(Type::Signed32()) ||
        (output_type.Is(Type::Unsigned32()) &&
         use_info.type_check() == TypeCheckKind::kNone) ||
        (output_type.Is(cache_->kSafeInteger) &&
         use_info.truncation().IsUsedAsWord32())) {
      op = machine()->TruncateInt64ToInt32();
    } else if (use_info.type_check() == TypeCheckKind::kSignedSmall ||
               use_info.type_check() == TypeCheckKind::kSigned32 ||
               use_info.type_check() == TypeCheckKind::kArrayIndex) {
      if (output_type.Is(cache_->kPositiveSafeInteger)) {
        op = simplified()->CheckedUint64ToInt32(use_info.feedback());
      } else if (output_type.Is(cache_->kSafeInteger)) {
        op = simplified()->CheckedInt64ToInt32(use_info.feedback());
      } else {
        return TypeError(node, output_rep, output_type,
                         MachineRepresentation::kWord32);
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord32);
    }
  }
  if (op == nullptr) {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kWord32);
  }
  return InsertConversion(node, op, use_node);
}
References v8::internal::compiler::Truncation::Any(), cache_, v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToInt32(), v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToUint32(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedSignedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToUint32(), CHECK, CHECK_NE, v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedSignedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToArrayIndex(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTruncateTaggedToWord32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint32ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint64ToInt32(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::UseInfo::feedback(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), InsertChangeFloat32ToFloat64(), InsertConversion(), InsertTypeOverrideForVerifier(), InsertUnconditionalDeopt(), v8::internal::compiler::Type::Is(), v8::internal::IsAnyTagged(), v8::internal::IsInt32Double(), v8::internal::compiler::Truncation::IsUsedAsWord32(), jsgraph(), v8::internal::compiler::TypeCache::kAdditiveSafeInteger, v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kArrayIndex, v8::internal::kBit, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::kIdentifyZeros, v8::internal::compiler::kNone, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TypeCache::kPositiveSafeInteger, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::compiler::kSigned32, v8::internal::compiler::kSignedSmall, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, machine(), MakeTruncatedInt32Constant(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::UseInfo::minus_zero_check(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::UseInfo::representation(), v8::internal::compiler::Type::SignedSmall(), simplified(), v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToWord32(), v8::internal::compiler::MachineOperatorBuilder::TruncateInt64ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateTaggedToWord32(), v8::internal::compiler::UseInfo::truncation(), v8::internal::compiler::UseInfo::type_check(), TypeError(), and v8::internal::UNREACHABLE().
Referenced by GetRepresentationFor().
GetWord64RepresentationFor()
Node * v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor (Node * node, MachineRepresentation output_rep, Type output_type, Node * use_node, UseInfo use_info) [private]
Definition at line 1253 of file representation-change.cc.
                                      {
  // Eagerly fold representation changes for constants.
  switch (node->opcode()) {
    case IrOpcode::kInt32Constant:
    case IrOpcode::kInt64Constant:
    case IrOpcode::kFloat32Constant:
    case IrOpcode::kFloat64Constant:
      UNREACHABLE();
    case IrOpcode::kNumberConstant: {
      if (!TypeCheckIsBigInt(use_info.type_check())) {
        double const fv = OpParameter<double>(node->op());
        if (base::IsValueInRangeForNumericType<int64_t>(fv)) {
          int64_t const iv = static_cast<int64_t>(fv);
          if (static_cast<double>(iv) == fv) {
            if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
              if (iv < kMinAdditiveSafeInteger ||
                  kMaxAdditiveSafeInteger < iv ||
                  (iv == 0 && std::signbit(fv))) {
                Node* unreachable = InsertUnconditionalDeopt(
                    use_node, DeoptimizeReason::kNotAdditiveSafeInteger,
                    use_info.feedback());
                return jsgraph()->graph()->NewNode(
                    jsgraph()->common()->DeadValue(
                        MachineRepresentation::kWord64),
                    unreachable);
              }
            }
            return InsertTypeOverrideForVerifier(NodeProperties::GetType(node),
                                                 jsgraph()->Int64Constant(iv));
          }
        }
      }
      break;
    }
    case IrOpcode::kHeapConstant: {
      HeapObjectMatcher m(node);
      if (m.HasResolvedValue() && m.Ref(broker_).IsBigInt() &&
          (Is64() && use_info.truncation().IsUsedAsWord64())) {
        BigIntRef bigint = m.Ref(broker_).AsBigInt();
        return InsertTypeOverrideForVerifier(
            NodeProperties::GetType(node),
            jsgraph()->Int64Constant(static_cast<int64_t>(bigint.AsUint64())));
      }
      break;
    }
    default:
      break;
  }
  if (TypeCheckIsBigInt(use_info.type_check())) {
    // BigInts are only represented as tagged pointer and word64.
    if (!CanBeTaggedPointer(output_rep) &&
        output_rep != MachineRepresentation::kWord64) {
      DCHECK(!output_type.Equals(Type::BigInt()));
      Node* unreachable = InsertUnconditionalDeopt(
          use_node, DeoptimizeReason::kNotABigInt, use_info.feedback());
      return jsgraph()->graph()->NewNode(
          jsgraph()->common()->DeadValue(MachineRepresentation::kWord64),
          unreachable);
    }
  }
  // Select the correct X -> Word64 operator.
  const Operator* op;
  if (output_type.Is(Type::None())) {
    // This is an impossible value; it should not be used at runtime.
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kWord64), node);
  } else if (output_rep == MachineRepresentation::kBit) {
    CHECK(output_type.Is(Type::Boolean()));
    CHECK_NE(use_info.type_check(), TypeCheckKind::kNone);
    CHECK_NE(use_info.type_check(), TypeCheckKind::kNumberOrOddball);
    CHECK_NE(use_info.type_check(), TypeCheckKind::kBigInt);
    CHECK_NE(use_info.type_check(), TypeCheckKind::kBigInt64);
    Node* unreachable =
        InsertUnconditionalDeopt(use_node, DeoptimizeReason::kNotASmi);
    return jsgraph()->graph()->NewNode(
        jsgraph()->common()->DeadValue(MachineRepresentation::kWord64),
        unreachable);
  } else if (IsWord(output_rep)) {
    if (output_type.Is(Type::Unsigned32OrMinusZero())) {
      // uint32 -> uint64
      CHECK_IMPLIES(output_type.Maybe(Type::MinusZero()),
                    use_info.truncation().IdentifiesZeroAndMinusZero());
      op = machine()->ChangeUint32ToUint64();
    } else if (output_type.Is(Type::Signed32OrMinusZero())) {
      // int32 -> int64
      CHECK_IMPLIES(output_type.Maybe(Type::MinusZero()),
                    use_info.truncation().IdentifiesZeroAndMinusZero());
      op = machine()->ChangeInt32ToInt64();
    } else if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
      // If it is a word representation, but not word32 type, then it is not an
      // integer.
      Node* unreachable = InsertUnconditionalDeopt(
          use_node, DeoptimizeReason::kNotAdditiveSafeInteger,
          use_info.feedback());
      return jsgraph()->graph()->NewNode(
          jsgraph()->common()->DeadValue(output_rep), unreachable);
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else if (output_rep == MachineRepresentation::kFloat32) {
    if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
      // float32 -> float64 -> int64
      node = InsertChangeFloat32ToFloat64(node);
      if (output_type.Is(cache_->kAdditiveSafeInteger)) {
        op = machine()->ChangeFloat64ToInt64();
      } else {
        op = simplified()->CheckedFloat64ToAdditiveSafeInteger(
            output_type.Maybe(Type::MinusZero())
                ? use_info.minus_zero_check()
                : CheckForMinusZeroMode::kDontCheckForMinusZero,
            use_info.feedback());
      }
    } else if (output_type.Is(cache_->kDoubleRepresentableInt64) ||
               (output_type.Is(cache_->kDoubleRepresentableInt64OrMinusZero) &&
                use_info.truncation().IdentifiesZeroAndMinusZero())) {
      // float32 -> float64 -> int64
      node = InsertChangeFloat32ToFloat64(node);
      op = machine()->ChangeFloat64ToInt64();
    } else if (output_type.Is(cache_->kDoubleRepresentableUint64)) {
      // float32 -> float64 -> uint64
      node = InsertChangeFloat32ToFloat64(node);
      op = machine()->ChangeFloat64ToUint64();
    } else if (use_info.type_check() == TypeCheckKind::kSigned64 ||
               use_info.type_check() == TypeCheckKind::kArrayIndex) {
      // float32 -> float64 -> int64
      node = InsertChangeFloat32ToFloat64(node);
      op = simplified()->CheckedFloat64ToInt64(
          output_type.Maybe(Type::MinusZero())
              ? use_info.minus_zero_check()
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback());
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else if (output_rep == MachineRepresentation::kFloat64) {
    if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
      if (output_type.Is(cache_->kAdditiveSafeInteger)) {
        op = machine()->ChangeFloat64ToInt64();
      } else {
        op = simplified()->CheckedFloat64ToAdditiveSafeInteger(
            output_type.Maybe(Type::MinusZero())
                ? use_info.minus_zero_check()
                : CheckForMinusZeroMode::kDontCheckForMinusZero,
            use_info.feedback());
      }
    } else if (output_type.Is(cache_->kDoubleRepresentableInt64) ||
               (output_type.Is(cache_->kDoubleRepresentableInt64OrMinusZero) &&
                use_info.truncation().IdentifiesZeroAndMinusZero())) {
      op = machine()->ChangeFloat64ToInt64();
    } else if (output_type.Is(cache_->kDoubleRepresentableUint64)) {
      op = machine()->ChangeFloat64ToUint64();
    } else if (use_info.type_check() == TypeCheckKind::kSigned64 ||
               use_info.type_check() == TypeCheckKind::kArrayIndex) {
      op = simplified()->CheckedFloat64ToInt64(
          output_type.Maybe(Type::MinusZero())
              ? use_info.minus_zero_check()
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback());
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else if (output_rep == MachineRepresentation::kTaggedSigned) {
    if (output_type.Is(Type::SignedSmall())) {
      if (output_type.IsRange() && output_type.AsRange()->Min() >= 0) {
        node = InsertChangeTaggedSignedToInt32(node);
        op = machine()->ChangeUint32ToUint64();
      } else {
        op = simplified()->ChangeTaggedSignedToInt64();
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else if (IsAnyTagged(output_rep) &&
             ((Is64() && use_info.truncation().IsUsedAsWord64() &&
               (use_info.type_check() == TypeCheckKind::kBigInt ||
                output_type.Is(Type::BigInt()))) ||
              use_info.type_check() == TypeCheckKind::kBigInt64)) {
    node = GetTaggedPointerRepresentationFor(node, output_rep, output_type,
                                             use_node, use_info);
    op = simplified()->TruncateBigIntToWord64();
  } else if (CanBeTaggedPointer(output_rep)) {
    if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
      if (output_type.Is(cache_->kAdditiveSafeInteger)) {
        op = simplified()->ChangeTaggedToInt64();
      } else {
        op = simplified()->CheckedTaggedToAdditiveSafeInteger(
            output_type.Maybe(Type::MinusZero())
                ? use_info.minus_zero_check()
                : CheckForMinusZeroMode::kDontCheckForMinusZero,
            use_info.feedback());
      }
    } else if (output_type.Is(cache_->kDoubleRepresentableInt64) ||
               (output_type.Is(cache_->kDoubleRepresentableInt64OrMinusZero) &&
                use_info.truncation().IdentifiesZeroAndMinusZero())) {
      op = simplified()->ChangeTaggedToInt64();
    } else if (use_info.type_check() == TypeCheckKind::kSigned64) {
      op = simplified()->CheckedTaggedToInt64(
          output_type.Maybe(Type::MinusZero())
              ? use_info.minus_zero_check()
              : CheckForMinusZeroMode::kDontCheckForMinusZero,
          use_info.feedback());
    } else if (use_info.type_check() == TypeCheckKind::kArrayIndex) {
      op = simplified()->CheckedTaggedToArrayIndex(use_info.feedback());
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else if (output_rep == MachineRepresentation::kWord64) {
    if (use_info.type_check() == TypeCheckKind::kAdditiveSafeInteger) {
      if (output_type.Is(cache_->kAdditiveSafeInteger)) {
        return node;
      } else {
        op = simplified()->CheckedInt64ToAdditiveSafeInteger(
            use_info.feedback());
      }
    } else if (TypeCheckIsBigInt(use_info.type_check())) {
      if (output_type.Is(Type::UnsignedBigInt64()) &&
          use_info.type_check() == TypeCheckKind::kBigInt64) {
        op = simplified()->CheckedUint64ToInt64(use_info.feedback());
      } else if ((output_type.Is(Type::BigInt()) &&
                  use_info.type_check() == TypeCheckKind::kBigInt) ||
                 (output_type.Is(Type::SignedBigInt64()) &&
                  use_info.type_check() == TypeCheckKind::kBigInt64)) {
        return node;
      } else {
        DCHECK(output_type != Type::BigInt() ||
               use_info.type_check() != TypeCheckKind::kBigInt64);
        Node* unreachable = InsertUnconditionalDeopt(
            use_node, DeoptimizeReason::kNotABigInt, use_info.feedback());
        return jsgraph()->graph()->NewNode(
            jsgraph()->common()->DeadValue(MachineRepresentation::kWord64),
            unreachable);
      }
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else if (output_rep == MachineRepresentation::kSandboxedPointer) {
    if (output_type.Is(Type::SandboxedPointer())) {
      return node;
    } else {
      return TypeError(node, output_rep, output_type,
                       MachineRepresentation::kWord64);
    }
  } else {
    return TypeError(node, output_rep, output_type,
                     MachineRepresentation::kWord64);
  }
  return InsertConversion(node, op, use_node);
}
References v8::internal::compiler::Type::AsRange(), v8::internal::compiler::BigIntRef::AsUint64(), broker_, cache_, v8::internal::CanBeTaggedPointer(), v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToInt64(), v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToUint64(), v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedSignedToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::ChangeTaggedToInt64(), v8::internal::compiler::MachineOperatorBuilder::ChangeUint32ToUint64(), CHECK, CHECK_IMPLIES, CHECK_NE, v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64ToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToArrayIndex(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint64ToInt64(), v8::internal::DCHECK(), v8::internal::compiler::Type::Equals(), v8::internal::compiler::UseInfo::feedback(), GetTaggedPointerRepresentationFor(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), InsertChangeFloat32ToFloat64(), InsertChangeTaggedSignedToInt32(), InsertConversion(), InsertTypeOverrideForVerifier(), InsertUnconditionalDeopt(), v8::internal::compiler::Type::Is(), v8::internal::Is64(), v8::internal::IsAnyTagged(), v8::internal::compiler::Type::IsRange(), v8::internal::compiler::Truncation::IsUsedAsWord64(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::IsWord(), jsgraph(), v8::internal::compiler::TypeCache::kAdditiveSafeInteger, v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kArrayIndex, v8::internal::compiler::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBit, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::compiler::TypeCache::kDoubleRepresentableInt64, v8::internal::compiler::TypeCache::kDoubleRepresentableInt64OrMinusZero, v8::internal::compiler::TypeCache::kDoubleRepresentableUint64, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kMaxAdditiveSafeInteger, v8::internal::kMinAdditiveSafeInteger, v8::internal::compiler::kNone, v8::internal::compiler::kNumberOrOddball, v8::internal::kSandboxedPointer, v8::internal::compiler::kSigned64, v8::internal::kTaggedSigned, v8::internal::kWord64, machine(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::RangeType::Min(), v8::internal::compiler::UseInfo::minus_zero_check(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::internal::compiler::Type::SignedSmall(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::TruncateBigIntToWord64(), v8::internal::compiler::UseInfo::truncation(), v8::internal::compiler::UseInfo::type_check(), v8::internal::compiler::anonymous_namespace{representation-change.cc}::TypeCheckIsBigInt(), TypeError(), and v8::internal::UNREACHABLE().
Referenced by GetRepresentationFor().
Ieee754Fp16RawBitsToFp32RawBitsCode()
Node * v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsCode () [private]
Definition at line 1900 of file representation-change.cc.
                                                                 {
  if (!ieee754_fp16_raw_bits_to_fp32_raw_bits_code_.is_set()) {
    ieee754_fp16_raw_bits_to_fp32_raw_bits_code_.set(
        jsgraph()->ExternalConstant(
            ExternalReference::ieee754_fp16_raw_bits_to_fp32_raw_bits()));
  }
  return ieee754_fp16_raw_bits_to_fp32_raw_bits_code_.get();
}
References ieee754_fp16_raw_bits_to_fp32_raw_bits_code_, and jsgraph().
Referenced by InsertChangeFloat16RawBitsToFloat64Fallback().
Ieee754Fp16RawBitsToFp32RawBitsOperator()
Operator const * v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator () [private]
Definition at line 1924 of file representation-change.cc.
                                                               {
  if (!ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_.is_set()) {
    Zone* graph_zone = jsgraph()->zone();
    MachineSignature::Builder builder(graph_zone, 1, 1);
    builder.AddReturn(MachineType::Uint32());
    builder.AddParam(MachineType::Uint32());
    auto desc = Linkage::GetSimplifiedCDescriptor(
        graph_zone, builder.Get(), CallDescriptor::kNoFlags, Operator::kPure);
    ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_.set(
        jsgraph()->common()->Call(desc));
  }
  return ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_.get();
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_, jsgraph(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kPure, v8::internal::MachineType::Uint32(), and v8::internal::compiler::MachineGraph::zone().
Referenced by InsertChangeFloat16RawBitsToFloat64Fallback().
Ieee754Fp64ToFp16RawBitsCode()
Node * v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsCode () [private]
Definition at line 1909 of file representation-change.cc.
                                                          {
  if (!ieee754_fp64_to_fp16_raw_bits_code_.is_set()) {
    if constexpr (SupportsFpParamsInCLinkage()) {
      ieee754_fp64_to_fp16_raw_bits_code_.set(jsgraph()->ExternalConstant(
          ExternalReference::ieee754_fp64_to_fp16_raw_bits()));
    } else {
      ieee754_fp64_to_fp16_raw_bits_code_.set(jsgraph()->ExternalConstant(
          ExternalReference::
              ieee754_fp64_raw_bits_to_fp16_raw_bits_for_32bit_arch()));
    }
  }
  return ieee754_fp64_to_fp16_raw_bits_code_.get();
}
References ieee754_fp64_to_fp16_raw_bits_code_, jsgraph(), and v8::internal::compiler::anonymous_namespace{representation-change.cc}::SupportsFpParamsInCLinkage().
Referenced by InsertTruncateFloat64ToFloat16RawBitsFallback().
Ieee754Fp64ToFp16RawBitsOperator()
Operator const * v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator () [private]
Definition at line 1938 of file representation-change.cc.
                                                                        {
  if (!ieee754_fp64_to_fp16_raw_bits_operator_.is_set()) {
    Zone* graph_zone = jsgraph()->zone();
    CallDescriptor* desc;
    if constexpr (SupportsFpParamsInCLinkage()) {
      MachineSignature::Builder builder(graph_zone, 1, 1);
      builder.AddReturn(MachineType::Uint32());
      builder.AddParam(MachineType::Float64());
      desc = Linkage::GetSimplifiedCDescriptor(
          graph_zone, builder.Get(), CallDescriptor::kNoFlags, Operator::kPure);
    } else {
      MachineSignature::Builder builder(graph_zone, 1, 2);
      builder.AddReturn(MachineType::Uint32());
      builder.AddParam(MachineType::Uint32());
      builder.AddParam(MachineType::Uint32());
      desc = Linkage::GetSimplifiedCDescriptor(
          graph_zone, builder.Get(), CallDescriptor::kNoFlags, Operator::kPure);
    }
    ieee754_fp64_to_fp16_raw_bits_operator_.set(
        jsgraph()->common()->Call(desc));
  }
  return ieee754_fp64_to_fp16_raw_bits_operator_.get();
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::MachineType::Float64(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), ieee754_fp64_to_fp16_raw_bits_operator_, jsgraph(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kPure, v8::internal::compiler::anonymous_namespace{representation-change.cc}::SupportsFpParamsInCLinkage(), v8::internal::MachineType::Uint32(), and v8::internal::compiler::MachineGraph::zone().
Referenced by InsertTruncateFloat64ToFloat16RawBitsFallback().
InsertChangeBitToTagged()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeBitToTagged (Node * node) [private]
Definition at line 1855 of file representation-change.cc.
                                                               {
  return jsgraph()->graph()->NewNode(simplified()->ChangeBitToTagged(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by GetTaggedSignedRepresentationFor().
InsertChangeFloat16RawBitsToFloat64Fallback()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeFloat16RawBitsToFloat64Fallback (Node * node) [private]
Definition at line 1962 of file representation-change.cc.
                {
  // Replace the op directly if the underlying architecture has support.
  DCHECK(!machine()->ChangeFloat16RawBitsToFloat64().IsSupported());
  DCHECK_EQ(0, Ieee754Fp16RawBitsToFp32RawBitsOperator()->ControlInputCount());
  // On architectures that don't have fp16 support, Float16Array elements are
  // loaded as raw bits in a word16, converted to float32 in software, then
  // converted to float64.
  Node* float32_raw_bits =
      jsgraph()->graph()->NewNode(Ieee754Fp16RawBitsToFp32RawBitsOperator(),
                                  Ieee754Fp16RawBitsToFp32RawBitsCode(), node);
  return InsertChangeFloat32ToFloat64(jsgraph()->graph()->NewNode(
      machine()->BitcastInt32ToFloat32(), float32_raw_bits));
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::MachineGraph::graph(), graph(), Ieee754Fp16RawBitsToFp32RawBitsCode(), Ieee754Fp16RawBitsToFp32RawBitsOperator(), InsertChangeFloat32ToFloat64(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetRepresentationFor().
InsertChangeFloat32ToFloat64()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeFloat32ToFloat64 (Node * node) [private]
Definition at line 1859 of file representation-change.cc.
                                                                    {
  return jsgraph()->graph()->NewNode(machine()->ChangeFloat32ToFloat64(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetTaggedPointerRepresentationFor(), GetTaggedRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), GetWord64RepresentationFor(), and InsertChangeFloat16RawBitsToFloat64Fallback().
InsertChangeFloat64ToInt32()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeFloat64ToInt32 (Node * node) [private]
Definition at line 1867 of file representation-change.cc.
                                                                  {
  return jsgraph()->graph()->NewNode(machine()->ChangeFloat64ToInt32(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetTaggedRepresentationFor(), and GetTaggedSignedRepresentationFor().
InsertChangeFloat64ToUint32()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeFloat64ToUint32 (Node * node) [private]
Definition at line 1863 of file representation-change.cc.
                                                                   {
  return jsgraph()->graph()->NewNode(machine()->ChangeFloat64ToUint32(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetTaggedRepresentationFor(), and GetTaggedSignedRepresentationFor().
InsertChangeInt32ToFloat64()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeInt32ToFloat64 (Node * node) [private]
Definition at line 1871 of file representation-change.cc.
                                                                  {
  return jsgraph()->graph()->NewNode(machine()->ChangeInt32ToFloat64(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetTaggedPointerRepresentationFor().
InsertChangeTaggedSignedToInt32()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeTaggedSignedToInt32 (Node * node) [private]
Definition at line 1875 of file representation-change.cc.
                                                                       {
  return jsgraph()->graph()->NewNode(simplified()->ChangeTaggedSignedToInt32(),
                                     node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
Referenced by GetFloat64RepresentationFor(), and GetWord64RepresentationFor().
InsertChangeTaggedToFloat64()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeTaggedToFloat64 (Node * node) [private]
Definition at line 1880 of file representation-change.cc.
                                                                   {
  return jsgraph()->graph()->NewNode(simplified()->ChangeTaggedToFloat64(),
                                     node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and simplified().
InsertChangeUint32ToFloat64()
Node * v8::internal::compiler::RepresentationChanger::InsertChangeUint32ToFloat64 (Node * node) [private]
Definition at line 1885 of file representation-change.cc.
                                                                   {
  return jsgraph()->graph()->NewNode(machine()->ChangeUint32ToFloat64(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetTaggedPointerRepresentationFor().
InsertCheckedFloat64ToInt32()
Node * v8::internal::compiler::RepresentationChanger::InsertCheckedFloat64ToInt32 (Node * node, CheckForMinusZeroMode check, const FeedbackSource & feedback, Node * use_node) [private]
Definition at line 1893 of file representation-change.cc.
                    {
  return InsertConversion(
      node, simplified()->CheckedFloat64ToInt32(check, feedback), use_node);
}
References InsertConversion(), and simplified().
Referenced by GetTaggedSignedRepresentationFor().
InsertConversion()
Node * v8::internal::compiler::RepresentationChanger::InsertConversion (Node * node, const Operator * op, Node * use_node) [private]
Definition at line 1163 of file representation-change.cc.
                                                              {
  if (op->ControlInputCount() > 0) {
    // If the operator can deoptimize (which means it has control
    // input), we need to connect it to the effect and control chains.
    Node* effect = NodeProperties::GetEffectInput(use_node);
    Node* control = NodeProperties::GetControlInput(use_node);
    Node* conversion = jsgraph()->graph()->NewNode(op, node, effect, control);
    NodeProperties::ReplaceEffectInput(use_node, conversion);
    return conversion;
  }
  return jsgraph()->graph()->NewNode(op, node);
}
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MachineGraph::graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::compiler::NodeProperties::ReplaceEffectInput().
Referenced by GetFloat64RepresentationFor(), GetRepresentationFor(), GetTaggedPointerRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), GetWord64RepresentationFor(), and InsertCheckedFloat64ToInt32().
InsertTruncateFloat64ToFloat16RawBitsFallback()
Node * v8::internal::compiler::RepresentationChanger::InsertTruncateFloat64ToFloat16RawBitsFallback (Node * node) [private]
Definition at line 1977 of file representation-change.cc.
                {
  // Use the op directly if the underlying architecture has support.
  DCHECK(!machine()->TruncateFloat64ToFloat16RawBits().IsSupported());
  DCHECK_EQ(0, Ieee754Fp64ToFp16RawBitsOperator()->ControlInputCount());
  // On architectures that don't have fp16 support, the input to be stored in
  // Float16Array elements are converted from float64 to float16 in software.
  if constexpr (SupportsFpParamsInCLinkage()) {
    return jsgraph()->graph()->NewNode(Ieee754Fp64ToFp16RawBitsOperator(),
                                       Ieee754Fp64ToFp16RawBitsCode(), node);
  } else {
    Node* hi = jsgraph()->graph()->NewNode(
        machine()->Float64ExtractHighWord32(), node);
    Node* lo =
        jsgraph()->graph()->NewNode(machine()->Float64ExtractLowWord32(), node);
    return jsgraph()->graph()->NewNode(Ieee754Fp64ToFp16RawBitsOperator(),
                                       Ieee754Fp64ToFp16RawBitsCode(), hi, lo);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::MachineGraph::graph(), v8::internal::hi, Ieee754Fp64ToFp16RawBitsCode(), Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), jsgraph(), v8::internal::lo, machine(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::compiler::anonymous_namespace{representation-change.cc}::SupportsFpParamsInCLinkage().
Referenced by GetFloat16RawBitsRepresentationFor().
InsertTruncateInt64ToInt32()
Node * v8::internal::compiler::RepresentationChanger::InsertTruncateInt64ToInt32 (Node * node) [private]
Definition at line 1889 of file representation-change.cc.
                                                                  {
  return jsgraph()->graph()->NewNode(machine()->TruncateInt64ToInt32(), node);
}
References v8::internal::compiler::MachineGraph::graph(), jsgraph(), machine(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GetTaggedRepresentationFor(), and GetTaggedSignedRepresentationFor().
InsertTypeOverrideForVerifier()
Node * v8::internal::compiler::RepresentationChanger::InsertTypeOverrideForVerifier (const Type & type, Node * node) [private]
Definition at line 1997 of file representation-change.cc.
                                                                       {
  if (verification_enabled()) {
    DCHECK(!type.IsInvalid());
    node = jsgraph()->graph()->NewNode(
        jsgraph()->common()->SLVerifierHint(nullptr, type), node);
    verifier_->RecordHint(node);
  }
  return node;
}
References v8::internal::DCHECK(), v8::internal::compiler::MachineGraph::graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordHint(), v8::internal::tracing::type, verification_enabled(), and verifier_.
Referenced by GetBitRepresentationFor(), GetWord32RepresentationFor(), and GetWord64RepresentationFor().
InsertUnconditionalDeopt()
Node * v8::internal::compiler::RepresentationChanger::InsertUnconditionalDeopt (Node * node, DeoptimizeReason reason, const FeedbackSource & feedback = {}) [private]
Definition at line 927 of file representation-change.cc.
                                                                         {
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  effect =
      jsgraph()->graph()->NewNode(simplified()->CheckIf(reason, feedback),
                                  jsgraph()->Int32Constant(0), effect, control);
  Node* unreachable = effect = jsgraph()->graph()->NewNode(
      jsgraph()->common()->Unreachable(), effect, control);
  NodeProperties::ReplaceEffectInput(node, effect);
  return unreachable;
}
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MachineGraph::graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), and simplified().
Referenced by GetFloat64RepresentationFor(), GetTaggedPointerRepresentationFor(), GetWord32RepresentationFor(), and GetWord64RepresentationFor().
Int32OperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Int32OperatorFor (IrOpcode::Value opcode)
Definition at line 1512 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeNumberAdd: // Fall through.
    case IrOpcode::kSpeculativeAdditiveSafeIntegerAdd:
    case IrOpcode::kSpeculativeSmallIntegerAdd:
    case IrOpcode::kNumberAdd:
      return machine()->Int32Add();
    case IrOpcode::kSpeculativeNumberSubtract: // Fall through.
    case IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract:
    case IrOpcode::kSpeculativeSmallIntegerSubtract:
    case IrOpcode::kNumberSubtract:
      return machine()->Int32Sub();
    case IrOpcode::kSpeculativeNumberMultiply:
    case IrOpcode::kNumberMultiply:
      return machine()->Int32Mul();
    case IrOpcode::kSpeculativeNumberDivide:
    case IrOpcode::kNumberDivide:
      return machine()->Int32Div();
    case IrOpcode::kSpeculativeNumberModulus:
    case IrOpcode::kNumberModulus:
      return machine()->Int32Mod();
    case IrOpcode::kSpeculativeNumberBitwiseOr: // Fall through.
    case IrOpcode::kNumberBitwiseOr:
      return machine()->Word32Or();
    case IrOpcode::kSpeculativeNumberBitwiseXor: // Fall through.
    case IrOpcode::kNumberBitwiseXor:
      return machine()->Word32Xor();
    case IrOpcode::kSpeculativeNumberBitwiseAnd: // Fall through.
    case IrOpcode::kNumberBitwiseAnd:
      return machine()->Word32And();
    case IrOpcode::kNumberEqual:
    case IrOpcode::kSpeculativeNumberEqual:
      return machine()->Word32Equal();
    case IrOpcode::kNumberLessThan:
    case IrOpcode::kSpeculativeNumberLessThan:
      return machine()->Int32LessThan();
    case IrOpcode::kNumberLessThanOrEqual:
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return machine()->Int32LessThanOrEqual();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::MachineOperatorBuilder::Int32Add(), v8::internal::compiler::MachineOperatorBuilder::Int32Div(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThanOrEqual(), v8::internal::compiler::MachineOperatorBuilder::Int32Mod(), v8::internal::compiler::MachineOperatorBuilder::Int32Mul(), v8::internal::compiler::MachineOperatorBuilder::Int32Sub(), machine(), v8::internal::UNREACHABLE(), v8::internal::compiler::MachineOperatorBuilder::Word32And(), v8::internal::compiler::MachineOperatorBuilder::Word32Equal(), v8::internal::compiler::MachineOperatorBuilder::Word32Or(), and v8::internal::compiler::MachineOperatorBuilder::Word32Xor().
Referenced by v8::internal::compiler::RepresentationSelector::Int32Op().
Int32OverflowOperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Int32OverflowOperatorFor (IrOpcode::Value opcode)
Definition at line 1557 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeSmallIntegerAdd:
      return simplified()->CheckedInt32Add();
    case IrOpcode::kSpeculativeSmallIntegerSubtract:
      return simplified()->CheckedInt32Sub();
    case IrOpcode::kSpeculativeNumberDivide:
      return simplified()->CheckedInt32Div();
    case IrOpcode::kSpeculativeNumberModulus:
      return simplified()->CheckedInt32Mod();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt32Add(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt32Div(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt32Mod(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt32Sub(), simplified(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::Int32OverflowOp().
Int64OperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Int64OperatorFor (IrOpcode::Value opcode)
Definition at line 1585 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeNumberAdd: // Fall through.
    case IrOpcode::kSpeculativeSmallIntegerAdd:
    case IrOpcode::kNumberAdd:
    case IrOpcode::kSpeculativeBigIntAdd:
      return machine()->Int64Add();
    case IrOpcode::kSpeculativeNumberSubtract: // Fall through.
    case IrOpcode::kSpeculativeSmallIntegerSubtract:
    case IrOpcode::kNumberSubtract:
    case IrOpcode::kSpeculativeBigIntSubtract:
      return machine()->Int64Sub();
    case IrOpcode::kSpeculativeBigIntMultiply:
      return machine()->Int64Mul();
    case IrOpcode::kSpeculativeBigIntBitwiseAnd:
      return machine()->Word64And();
    case IrOpcode::kSpeculativeBigIntBitwiseOr:
      return machine()->Word64Or();
    case IrOpcode::kSpeculativeBigIntBitwiseXor:
      return machine()->Word64Xor();
    case IrOpcode::kSpeculativeBigIntEqual:
      return machine()->Word64Equal();
    case IrOpcode::kSpeculativeBigIntLessThan:
      return machine()->Int64LessThan();
    case IrOpcode::kSpeculativeBigIntLessThanOrEqual:
      return machine()->Int64LessThanOrEqual();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::MachineOperatorBuilder::Int64Add(), v8::internal::compiler::MachineOperatorBuilder::Int64LessThan(), v8::internal::compiler::MachineOperatorBuilder::Int64LessThanOrEqual(), v8::internal::compiler::MachineOperatorBuilder::Int64Mul(), v8::internal::compiler::MachineOperatorBuilder::Int64Sub(), machine(), v8::internal::UNREACHABLE(), v8::internal::compiler::MachineOperatorBuilder::Word64And(), v8::internal::compiler::MachineOperatorBuilder::Word64Equal(), v8::internal::compiler::MachineOperatorBuilder::Word64Or(), and v8::internal::compiler::MachineOperatorBuilder::Word64Xor().
Referenced by v8::internal::compiler::RepresentationSelector::Int64Op().
Int64OverflowOperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Int64OverflowOperatorFor (IrOpcode::Value opcode)
Definition at line 1617 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeBigIntAdd:
      return simplified()->CheckedInt64Add();
    case IrOpcode::kSpeculativeBigIntSubtract:
      return simplified()->CheckedInt64Sub();
    case IrOpcode::kSpeculativeBigIntMultiply:
      return simplified()->CheckedInt64Mul();
    case IrOpcode::kSpeculativeBigIntDivide:
      return simplified()->CheckedInt64Div();
    case IrOpcode::kSpeculativeBigIntModulus:
      return simplified()->CheckedInt64Mod();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64Add(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64Div(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64Mod(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64Mul(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedInt64Sub(), simplified(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::Int64OverflowOp().
isolate()
Isolate * v8::internal::compiler::RepresentationChanger::isolate () const [private]
Definition at line 2008 of file representation-change.cc.
{ return broker_->isolate(); }
References broker_, and v8::internal::compiler::JSHeapBroker::isolate().
jsgraph()
JSGraph* v8::internal::compiler::RepresentationChanger::jsgraph () const [inline], [private]
Definition at line 133 of file representation-change.h.
{ return jsgraph_; }
Referenced by GetBitRepresentationFor(), GetFloat16RawBitsRepresentationFor(), GetFloat32RepresentationFor(), GetFloat64RepresentationFor(), GetRepresentationFor(), GetTaggedPointerRepresentationFor(), GetTaggedRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), GetWord64RepresentationFor(), Ieee754Fp16RawBitsToFp32RawBitsCode(), Ieee754Fp16RawBitsToFp32RawBitsOperator(), Ieee754Fp64ToFp16RawBitsCode(), Ieee754Fp64ToFp16RawBitsOperator(), InsertChangeBitToTagged(), InsertChangeFloat16RawBitsToFloat64Fallback(), InsertChangeFloat32ToFloat64(), InsertChangeFloat64ToInt32(), InsertChangeFloat64ToUint32(), InsertChangeInt32ToFloat64(), InsertChangeTaggedSignedToInt32(), InsertChangeTaggedToFloat64(), InsertChangeUint32ToFloat64(), InsertConversion(), InsertTruncateFloat64ToFloat16RawBitsFallback(), InsertTruncateInt64ToInt32(), InsertTypeOverrideForVerifier(), InsertUnconditionalDeopt(), and MakeTruncatedInt32Constant().
machine()
MachineOperatorBuilder* v8::internal::compiler::RepresentationChanger::machine () [inline], [private]
Definition at line 137 of file representation-change.h.
{ return jsgraph()->machine(); }
References v8::internal::compiler::MachineGraph::machine().
Referenced by Float64OperatorFor(), GetBitRepresentationFor(), GetFloat16RawBitsRepresentationFor(), GetFloat32RepresentationFor(), GetFloat64RepresentationFor(), GetRepresentationFor(), GetTaggedPointerRepresentationFor(), GetWord32RepresentationFor(), GetWord64RepresentationFor(), InsertChangeFloat16RawBitsToFloat64Fallback(), InsertChangeFloat32ToFloat64(), InsertChangeFloat64ToInt32(), InsertChangeFloat64ToUint32(), InsertChangeInt32ToFloat64(), InsertChangeUint32ToFloat64(), InsertTruncateFloat64ToFloat16RawBitsFallback(), InsertTruncateInt64ToInt32(), Int32OperatorFor(), Int64OperatorFor(), TaggedSignedOperatorFor(), and Uint32OperatorFor().
MakeTruncatedInt32Constant()
Node * v8::internal::compiler::RepresentationChanger::MakeTruncatedInt32Constant (double value) [private]
Definition at line 923 of file representation-change.cc.
                                                                    {
  return jsgraph()->Int32Constant(DoubleToInt32(value));
}
References v8::internal::DoubleToInt32(), v8::internal::compiler::MachineGraph::Int32Constant(), jsgraph(), and v8::internal::value.
Referenced by GetWord32RepresentationFor().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::RepresentationChanger::simplified () [inline], [private]
Definition at line 136 of file representation-change.h.
{ return jsgraph()->simplified(); }
References v8::internal::compiler::JSGraph::simplified().
Referenced by AdditiveSafeIntegerOverflowOperatorFor(), BigIntOperatorFor(), GetBitRepresentationFor(), GetFloat32RepresentationFor(), GetFloat64RepresentationFor(), GetRepresentationFor(), GetTaggedPointerRepresentationFor(), GetTaggedRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), GetWord64RepresentationFor(), InsertChangeBitToTagged(), InsertChangeTaggedSignedToInt32(), InsertChangeTaggedToFloat64(), InsertCheckedFloat64ToInt32(), InsertUnconditionalDeopt(), Int32OverflowOperatorFor(), Int64OverflowOperatorFor(), and Uint32OverflowOperatorFor().
TaggedSignedOperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor (IrOpcode::Value opcode)
Definition at line 1669 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeNumberLessThan:
      return (COMPRESS_POINTERS_BOOL || machine()->Is32())
                 ? machine()->Int32LessThan()
                 : machine()->Int64LessThan();
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return (COMPRESS_POINTERS_BOOL || machine()->Is32())
                 ? machine()->Int32LessThanOrEqual()
                 : machine()->Int64LessThanOrEqual();
    case IrOpcode::kSpeculativeNumberEqual:
      return (COMPRESS_POINTERS_BOOL || machine()->Is32())
                 ? machine()->Word32Equal()
                 : machine()->Word64Equal();
    default:
      UNREACHABLE();
  }
}
References COMPRESS_POINTERS_BOOL, v8::internal::compiler::MachineOperatorBuilder::Int32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThanOrEqual(), v8::internal::compiler::MachineOperatorBuilder::Int64LessThan(), v8::internal::compiler::MachineOperatorBuilder::Int64LessThanOrEqual(), machine(), v8::internal::UNREACHABLE(), v8::internal::compiler::MachineOperatorBuilder::Word32Equal(), and v8::internal::compiler::MachineOperatorBuilder::Word64Equal().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
TypeError()
Node * v8::internal::compiler::RepresentationChanger::TypeError (Node * node, MachineRepresentation output_rep, Type output_type, MachineRepresentation use) [private]
Definition at line 1832 of file representation-change.cc.
                                                                  {
  type_error_ = true;
  if (!testing_type_errors_) {
    std::ostringstream out_str;
    out_str << output_rep << " (";
    output_type.PrintTo(out_str);
    out_str << ")";
    std::ostringstream use_str;
    use_str << use;
    FATAL(
        "RepresentationChangerError: node #%d:%s of "
        "%s cannot be changed to %s",
        node->id(), node->op()->mnemonic(), out_str.str().c_str(),
        use_str.str().c_str());
  }
  return node;
}
References FATAL, v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Type::PrintTo(), testing_type_errors_, type_error_, and use().
Referenced by GetBitRepresentationFor(), GetFloat32RepresentationFor(), GetFloat64RepresentationFor(), GetRepresentationFor(), GetTaggedPointerRepresentationFor(), GetTaggedRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), and GetWord64RepresentationFor().
TypeForBasePointer() [1/2]
MachineType v8::internal::compiler::RepresentationChanger::TypeForBasePointer (const ElementAccess & access) [inline]
Definition at line 53 of file representation-change.h.
                                                              {
    return access.tag() != 0 ? MachineType::AnyTagged()
                             : MachineType::Pointer();
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::MachineType::Pointer(), and v8::internal::compiler::ElementAccess::tag().
TypeForBasePointer() [2/2]
MachineType v8::internal::compiler::RepresentationChanger::TypeForBasePointer (const FieldAccess & access) [inline]
Definition at line 48 of file representation-change.h.
                                                            {
    return access.tag() != 0 ? MachineType::AnyTagged()
                             : MachineType::Pointer();
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::MachineType::Pointer(), and v8::internal::compiler::FieldAccess::tag().
Uint32OperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Uint32OperatorFor (IrOpcode::Value opcode)
Definition at line 1689 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kNumberAdd:
      return machine()->Int32Add();
    case IrOpcode::kNumberSubtract:
      return machine()->Int32Sub();
    case IrOpcode::kSpeculativeNumberMultiply:
    case IrOpcode::kNumberMultiply:
      return machine()->Int32Mul();
    case IrOpcode::kSpeculativeNumberDivide:
    case IrOpcode::kNumberDivide:
      return machine()->Uint32Div();
    case IrOpcode::kSpeculativeNumberModulus:
    case IrOpcode::kNumberModulus:
      return machine()->Uint32Mod();
    case IrOpcode::kNumberEqual:
    case IrOpcode::kSpeculativeNumberEqual:
      return machine()->Word32Equal();
    case IrOpcode::kNumberLessThan:
    case IrOpcode::kSpeculativeNumberLessThan:
      return machine()->Uint32LessThan();
    case IrOpcode::kNumberLessThanOrEqual:
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return machine()->Uint32LessThanOrEqual();
    case IrOpcode::kNumberClz32:
      return machine()->Word32Clz();
    case IrOpcode::kNumberImul:
      return machine()->Int32Mul();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::MachineOperatorBuilder::Int32Add(), v8::internal::compiler::MachineOperatorBuilder::Int32Mul(), v8::internal::compiler::MachineOperatorBuilder::Int32Sub(), machine(), v8::internal::compiler::MachineOperatorBuilder::Uint32Div(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThan(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThanOrEqual(), v8::internal::compiler::MachineOperatorBuilder::Uint32Mod(), v8::internal::UNREACHABLE(), v8::internal::compiler::MachineOperatorBuilder::Word32Clz(), and v8::internal::compiler::MachineOperatorBuilder::Word32Equal().
Referenced by v8::internal::compiler::RepresentationSelector::Uint32Op().
Uint32OverflowOperatorFor()
const Operator * v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor (IrOpcode::Value opcode)
Definition at line 1723 of file representation-change.cc.
                          {
  switch (opcode) {
    case IrOpcode::kSpeculativeNumberDivide:
      return simplified()->CheckedUint32Div();
    case IrOpcode::kSpeculativeNumberModulus:
      return simplified()->CheckedUint32Mod();
    default:
      UNREACHABLE();
  }
}
References v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint32Div(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedUint32Mod(), simplified(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::RepresentationSelector::Uint32OverflowOp().
verification_enabled()
bool v8::internal::compiler::RepresentationChanger::verification_enabled () const [inline]
Definition at line 58 of file representation-change.h.
{ return verifier_ != nullptr; }
Referenced by InsertTypeOverrideForVerifier().
Friends And Related Function Documentation
RepresentationChangerTester
friend class RepresentationChangerTester [friend]
Definition at line 66 of file representation-change.h.
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::RepresentationChanger::broker_ [private]
Definition at line 63 of file representation-change.h.
Referenced by GetBitRepresentationFor(), GetWord64RepresentationFor(), and isolate().
cache_
TypeCache const* v8::internal::compiler::RepresentationChanger::cache_ [private]
Definition at line 61 of file representation-change.h.
Referenced by GetFloat32RepresentationFor(), GetFloat64RepresentationFor(), GetTaggedPointerRepresentationFor(), GetTaggedRepresentationFor(), GetTaggedSignedRepresentationFor(), GetWord32RepresentationFor(), and GetWord64RepresentationFor().
ieee754_fp16_raw_bits_to_fp32_raw_bits_code_
SetOncePointer<Node> v8::internal::compiler::RepresentationChanger::ieee754_fp16_raw_bits_to_fp32_raw_bits_code_ [private]
Definition at line 71 of file representation-change.h.
Referenced by Ieee754Fp16RawBitsToFp32RawBitsCode().
ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_
SetOncePointer<Operator const> v8::internal::compiler::RepresentationChanger::ieee754_fp16_raw_bits_to_fp32_raw_bits_operator_ [private]
Definition at line 74 of file representation-change.h.
Referenced by Ieee754Fp16RawBitsToFp32RawBitsOperator().
ieee754_fp64_to_fp16_raw_bits_code_
SetOncePointer<Node> v8::internal::compiler::RepresentationChanger::ieee754_fp64_to_fp16_raw_bits_code_ [private]
Definition at line 72 of file representation-change.h.
Referenced by Ieee754Fp64ToFp16RawBitsCode().
ieee754_fp64_to_fp16_raw_bits_operator_
SetOncePointer<Operator const> v8::internal::compiler::RepresentationChanger::ieee754_fp64_to_fp16_raw_bits_operator_ [private]
Definition at line 75 of file representation-change.h.
Referenced by Ieee754Fp64ToFp16RawBitsOperator().
jsgraph_
JSGraph* v8::internal::compiler::RepresentationChanger::jsgraph_ [private]
Definition at line 62 of file representation-change.h.
testing_type_errors_
bool v8::internal::compiler::RepresentationChanger::testing_type_errors_ [private]
Definition at line 68 of file representation-change.h.
Referenced by TypeError().
type_error_
bool v8::internal::compiler::RepresentationChanger::type_error_ [private]
Definition at line 69 of file representation-change.h.
Referenced by TypeError().
verifier_
SimplifiedLoweringVerifier* v8::internal::compiler::RepresentationChanger::verifier_ [private]
Definition at line 64 of file representation-change.h.
Referenced by InsertTypeOverrideForVerifier().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/representation-change.h
/mnt/V8SourceCode/src/compiler/representation-change.cc