v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer Class Reference
Public Member Functions
SectionBuffer (uint32_t module_offset, uint8_t id, size_t payload_length, base::Vector< const uint8_t > length_bytes)
SectionCode section_code () const
base::Vector< const uint8_t > GetCode (WireBytesRef ref) const final
std::optional< ModuleWireBytes > GetModuleBytes () const final
uint32_t module_offset () const
base::Vector< uint8_t > bytes () const
base::Vector< uint8_t > payload () const
size_t length () const
size_t payload_offset () const
Private Attributes
const uint32_t module_offset_
const base::OwnedVector< uint8_t > bytes_
const size_t payload_offset_
Detailed Description
Definition at line 51 of file streaming-decoder.cc.
Constructor & Destructor Documentation
SectionBuffer()
v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::SectionBuffer (uint32_t module_offset, uint8_t id, size_t payload_length, base::Vector< const uint8_t > length_bytes) [inline]
Definition at line 56 of file streaming-decoder.cc.
        : // ID + length + payload
          module_offset_(module_offset),
          bytes_(base::OwnedVector<uint8_t>::NewForOverwrite(
              1 + length_bytes.length() + payload_length)),
          payload_offset_(1 + length_bytes.length()) {
      bytes_.begin()[0] = id;
      memcpy(bytes_.begin() + 1, &length_bytes.first(), length_bytes.length());
    }
References v8::base::Vector< T >::first(), and v8::base::Vector< T >::length().
Member Function Documentation
bytes()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::bytes () const [inline]
Definition at line 81 of file streaming-decoder.cc.
{ return bytes_.as_vector(); }
GetCode()
base::Vector<const uint8_t> v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::GetCode (WireBytesRef ref) const [inline], [final], [virtual]
Implements v8::internal::wasm::WireBytesStorage.
Definition at line 71 of file streaming-decoder.cc.
                                                                    {
      DCHECK_LE(module_offset_, ref.offset());
      uint32_t offset_in_code_buffer = ref.offset() - module_offset_;
      return bytes().SubVector(offset_in_code_buffer,
                               offset_in_code_buffer + ref.length());
    }
References DCHECK_LE.
GetModuleBytes()
std::optional<ModuleWireBytes> v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::GetModuleBytes () const [inline], [final], [virtual]
Implements v8::internal::wasm::WireBytesStorage.
Definition at line 78 of file streaming-decoder.cc.
{ return {}; }
length()
size_t v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::length () const [inline]
Definition at line 83 of file streaming-decoder.cc.
{ return bytes_.size(); }
module_offset()
uint32_t v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::module_offset () const [inline]
Definition at line 80 of file streaming-decoder.cc.
{ return module_offset_; }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::ProcessSection().
payload()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::payload () const [inline]
Definition at line 82 of file streaming-decoder.cc.
{ return bytes() + payload_offset_; }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::ProcessSection().
payload_offset()
size_t v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::payload_offset () const [inline]
Definition at line 84 of file streaming-decoder.cc.
{ return payload_offset_; }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::ProcessSection().
section_code()
SectionCode v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::section_code () const [inline]
Definition at line 67 of file streaming-decoder.cc.
                                     {
      return static_cast<SectionCode>(bytes_.begin()[0]);
    }
Referenced by v8::internal::wasm::AsyncStreamingDecoder::ProcessSection().
Member Data Documentation
bytes_
const base::OwnedVector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::bytes_ [private]
Definition at line 88 of file streaming-decoder.cc.
module_offset_
const uint32_t v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::module_offset_ [private]
Definition at line 87 of file streaming-decoder.cc.
payload_offset_
const size_t v8::internal::wasm::AsyncStreamingDecoder::SectionBuffer::payload_offset_ [private]
Definition at line 89 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc