v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator Class Reference
Public Member Functions
CoverageBlockIterator (CoverageFunction *function)
~CoverageBlockIterator ()
bool HasNext () const
bool Next ()
CoverageBlock & GetBlock ()
CoverageBlock & GetNextBlock ()
CoverageBlock & GetPreviousBlock ()
CoverageBlock & GetParent ()
bool HasSiblingOrChild ()
CoverageBlock & GetSiblingOrChild ()
bool IsTopLevel () const
void DeleteBlock ()
Private Member Functions
void MaybeWriteCurrent ()
void Finalize ()
bool IsActive () const
Private Attributes
CoverageFunction * function_
std::vector< CoverageBlock > nesting_stack_
bool ended_ = false
bool delete_current_ = false
int read_index_ = -1
int write_index_ = -1
Detailed Description
Definition at line 105 of file debug-coverage.cc.
Constructor & Destructor Documentation
CoverageBlockIterator()
v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::CoverageBlockIterator (CoverageFunction * function) [inline], [explicit]
Definition at line 107 of file debug-coverage.cc.
      : function_(function) {
    DCHECK(std::is_sorted(function_->blocks.begin(), function_->blocks.end(),
                          CompareCoverageBlock));
  }
References v8::internal::anonymous_namespace{debug-coverage.cc}::CompareCoverageBlock(), and v8::internal::DCHECK().
 CoverageBlockIterator()
v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::~CoverageBlockIterator () [inline]
Definition at line 113 of file debug-coverage.cc.
                           {
    Finalize();
    DCHECK(std::is_sorted(function_->blocks.begin(), function_->blocks.end(),
                          CompareCoverageBlock));
  }
References v8::internal::anonymous_namespace{debug-coverage.cc}::CompareCoverageBlock(), and v8::internal::DCHECK().
Member Function Documentation
DeleteBlock()
void v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::DeleteBlock () [inline]
Definition at line 198 of file debug-coverage.cc.
                     {
    DCHECK(!delete_current_);
    DCHECK(IsActive());
    delete_current_ = true;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterEmptyRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterUncoveredRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeConsecutiveRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeDuplicateRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeNestedRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::RewriteFunctionScopeCounter(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
Finalize()
void v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Finalize () [inline], [private]
Definition at line 213 of file debug-coverage.cc.
                  {
    while (Next()) {
      // Just iterate to the end.
    }
    function_->blocks.resize(write_index_);
  }
References v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
GetBlock()
CoverageBlock& v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetBlock () [inline]
Definition at line 161 of file debug-coverage.cc.
                            {
    DCHECK(IsActive());
    return function_->blocks[read_index_];
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::ClampToBinary(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterEmptyRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterUncoveredRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeConsecutiveRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeDuplicateRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeNestedRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::RewriteFunctionScopeCounter(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
GetNextBlock()
CoverageBlock& v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetNextBlock () [inline]
Definition at line 166 of file debug-coverage.cc.
                                {
    DCHECK(IsActive());
    DCHECK(HasNext());
    return function_->blocks[read_index_ + 1];
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons(), and v8::internal::anonymous_namespace{debug-coverage.cc}::MergeDuplicateRanges().
GetParent()
CoverageBlock& v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetParent () [inline]
Definition at line 178 of file debug-coverage.cc.
                             {
    DCHECK(IsActive());
    return nesting_stack_.back();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::FilterUncoveredRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeNestedRanges(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
GetPreviousBlock()
CoverageBlock& v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetPreviousBlock () [inline]
Definition at line 172 of file debug-coverage.cc.
                                    {
    DCHECK(IsActive());
    DCHECK_GT(read_index_, 0);
    return function_->blocks[read_index_ - 1];
  }
References v8::internal::DCHECK(), and DCHECK_GT.
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons().
GetSiblingOrChild()
CoverageBlock& v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::GetSiblingOrChild () [inline]
Definition at line 188 of file debug-coverage.cc.
                                     {
    DCHECK(HasSiblingOrChild());
    DCHECK(IsActive());
    return GetNextBlock();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::MergeConsecutiveRanges(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
HasNext()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::HasNext () const [inline]
Definition at line 119 of file debug-coverage.cc.
                       {
    return read_index_ + 1 < static_cast<int>(function_->blocks.size());
  }
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons(), and v8::internal::anonymous_namespace{debug-coverage.cc}::MergeDuplicateRanges().
HasSiblingOrChild()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::HasSiblingOrChild () [inline]
Definition at line 183 of file debug-coverage.cc.
                           {
    DCHECK(IsActive());
    return HasNext() && GetNextBlock().start < GetParent().end;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::MergeConsecutiveRanges(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
IsActive()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::IsActive () const [inline], [private]
Definition at line 220 of file debug-coverage.cc.
{ return read_index_ >= 0 && !ended_; }
IsTopLevel()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::IsTopLevel () const [inline]
Definition at line 196 of file debug-coverage.cc.
{ return nesting_stack_.size() == 1; }
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::RewriteFunctionScopeCounter(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
MaybeWriteCurrent()
void v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::MaybeWriteCurrent () [inline], [private]
Definition at line 205 of file debug-coverage.cc.
                           {
    if (delete_current_) return;
    if (read_index_ >= 0 && write_index_ != read_index_) {
      function_->blocks[write_index_] = function_->blocks[read_index_];
    }
    write_index_++;
  }
Next()
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::Next () [inline]
Definition at line 123 of file debug-coverage.cc.
              {
    if (!HasNext()) {
      if (!ended_) MaybeWriteCurrent();
      ended_ = true;
      return false;
    }
    // If a block has been deleted, subsequent iteration moves trailing blocks
    // to their updated position within the array.
    MaybeWriteCurrent();
    if (read_index_ == -1) {
      // Initialize the nesting stack with the function range.
      nesting_stack_.emplace_back(function_->start, function_->end,
                                  function_->count);
    } else if (!delete_current_) {
      nesting_stack_.emplace_back(GetBlock());
    }
    delete_current_ = false;
    read_index_++;
    DCHECK(IsActive());
    CoverageBlock& block = GetBlock();
    while (nesting_stack_.size() > 1 &&
           nesting_stack_.back().end <= block.start) {
      nesting_stack_.pop_back();
    }
    DCHECK_IMPLIES(block.start >= function_->end,
                   block.end == kNoSourcePosition);
    DCHECK_NE(block.start, kNoSourcePosition);
    DCHECK_LE(block.end, GetParent().end);
    return true;
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_LE, DCHECK_NE, v8::internal::compiler::end(), v8::internal::CoverageBlock::end, v8::internal::kNoSourcePosition, and v8::internal::CoverageBlock::start.
Referenced by v8::internal::anonymous_namespace{debug-coverage.cc}::ClampToBinary(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterAliasedSingletons(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterEmptyRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::FilterUncoveredRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeConsecutiveRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeDuplicateRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::MergeNestedRanges(), v8::internal::anonymous_namespace{debug-coverage.cc}::RewriteFunctionScopeCounter(), and v8::internal::anonymous_namespace{debug-coverage.cc}::RewritePositionSingletonsToRanges().
Member Data Documentation
delete_current_
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::delete_current_ = false [private]
Definition at line 225 of file debug-coverage.cc.
ended_
bool v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::ended_ = false [private]
Definition at line 224 of file debug-coverage.cc.
function_
CoverageFunction* v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::function_ [private]
Definition at line 222 of file debug-coverage.cc.
nesting_stack_
std::vector<CoverageBlock> v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::nesting_stack_ [private]
Definition at line 223 of file debug-coverage.cc.
read_index_
int v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::read_index_ = -1 [private]
Definition at line 226 of file debug-coverage.cc.
write_index_
int v8::internal::anonymous_namespace{debug-coverage.cc}::CoverageBlockIterator::write_index_ = -1 [private]
Definition at line 227 of file debug-coverage.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-coverage.cc