v8::internal::interpreter::BytecodeLabels Class Reference
#include <bytecode-label.h>
Public Member Functions
BytecodeLabels (Zone *zone)
BytecodeLabels (const BytecodeLabels &)=delete
BytecodeLabels & operator= (const BytecodeLabels &)=delete
BytecodeLabel * New ()
void Bind (BytecodeArrayBuilder *builder)
bool is_bound () const
bool empty () const
Private Attributes
ZoneLinkedList< BytecodeLabel > labels_
bool is_bound_
Detailed Description
Definition at line 84 of file bytecode-label.h.
Constructor & Destructor Documentation
BytecodeLabels() [1/2]
v8::internal::interpreter::BytecodeLabels::BytecodeLabels (Zone * zone) [inline], [explicit]
Definition at line 86 of file bytecode-label.h.
: labels_(zone), is_bound_(false) {}
BytecodeLabels() [2/2]
v8::internal::interpreter::BytecodeLabels::BytecodeLabels (const BytecodeLabels &) [delete]
Member Function Documentation
Bind()
void v8::internal::interpreter::BytecodeLabels::Bind (BytecodeArrayBuilder * builder)
Definition at line 20 of file bytecode-label.cc.
                                                       {
  DCHECK(!is_bound_);
  is_bound_ = true;
  for (auto& label : labels_) {
    builder->Bind(&label);
  }
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::DCHECK(), is_bound_, and labels_.
Referenced by v8::internal::interpreter::TryFinallyBuilder::BeginFinally(), v8::internal::interpreter::BreakableControlFlowBuilder::BindBreakTarget(), v8::internal::interpreter::LoopBuilder::BindContinueTarget(), v8::internal::interpreter::SwitchBuilder::BindDefault(), v8::internal::interpreter::LoopBuilder::BindLoopEnd(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildOptionalChain(), v8::internal::interpreter::ConditionalControlFlowBuilder::Else(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ElseAt(), v8::internal::interpreter::SwitchBuilder::EmitJumpTableIfExists(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), v8::internal::interpreter::ConditionalControlFlowBuilder::Then(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ThenAt(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalTestSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::~ConditionalChainControlFlowBuilder(), and v8::internal::interpreter::ConditionalControlFlowBuilder::~ConditionalControlFlowBuilder().
empty()
bool v8::internal::interpreter::BytecodeLabels::empty () const [inline]
Definition at line 103 of file bytecode-label.h.
{ return labels_.empty(); }
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), v8::internal::interpreter::ConditionalControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::LoopBuilder::LoopHeader(), v8::internal::interpreter::BreakableControlFlowBuilder::~BreakableControlFlowBuilder(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::~ConditionalChainControlFlowBuilder(), v8::internal::interpreter::ConditionalControlFlowBuilder::~ConditionalControlFlowBuilder(), and v8::internal::interpreter::LoopBuilder::~LoopBuilder().
is_bound()
bool v8::internal::interpreter::BytecodeLabels::is_bound () const [inline]
Definition at line 94 of file bytecode-label.h.
                        {
    DCHECK_IMPLIES(
        is_bound_,
        std::all_of(labels_.begin(), labels_.end(), [](const BytecodeLabel& l) {
          return !l.has_referrer_jump() || l.is_bound();
        }));
    return is_bound_;
  }
References v8::base::all_of(), DCHECK_IMPLIES, and v8::internal::compiler::turboshaft::l.
Referenced by New(), v8::internal::interpreter::BreakableControlFlowBuilder::~BreakableControlFlowBuilder(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::~ConditionalChainControlFlowBuilder(), v8::internal::interpreter::ConditionalControlFlowBuilder::~ConditionalControlFlowBuilder(), and v8::internal::interpreter::LoopBuilder::~LoopBuilder().
New()
BytecodeLabel * v8::internal::interpreter::BytecodeLabels::New ()
Definition at line 14 of file bytecode-label.cc.
                                   {
  DCHECK(!is_bound());
  labels_.emplace_back(BytecodeLabel());
  return &labels_.back();
}
References v8::internal::DCHECK(), is_bound(), and labels_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration(), v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose(), v8::internal::interpreter::BytecodeGenerator::BuildTest(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJump(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfFalse(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfForInDone(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfTrue(), v8::internal::interpreter::BreakableControlFlowBuilder::EmitJumpIfUndefined(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::ConditionalControlFlowBuilder::JumpToEnd(), v8::internal::interpreter::TryFinallyBuilder::LeaveTry(), v8::internal::interpreter::BytecodeGenerator::VisitDelete(), v8::internal::interpreter::BytecodeGenerator::VisitForNullishTest(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrSubExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad().
operator=()
BytecodeLabels& v8::internal::interpreter::BytecodeLabels::operator= (const BytecodeLabels &) [delete]
Member Data Documentation
is_bound_
bool v8::internal::interpreter::BytecodeLabels::is_bound_ [private]
Definition at line 107 of file bytecode-label.h.
Referenced by Bind().
labels_
ZoneLinkedList<BytecodeLabel> v8::internal::interpreter::BytecodeLabels::labels_ [private]
Definition at line 106 of file bytecode-label.h.
Referenced by Bind(), and New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-label.h
/mnt/V8SourceCode/src/interpreter/bytecode-label.cc