v8::internal::maglev::MaglevGraphBuilder Class Reference
#include <maglev-graph-builder.h>
Classes
class BranchBuilder
struct ContinuationOffsets
class DeoptFrameScope
struct ForInState
struct HandlerTableEntry
class LazyDeoptResultLocationScope
class MaglevSubGraphBuilder
class SaveCallSpeculationScope
Public Member Functions
MaglevGraphBuilder (LocalIsolate *local_isolate, MaglevCompilationUnit *compilation_unit, Graph *graph, MaglevCallerDetails *caller_details=nullptr)
void Build ()
ReduceResult BuildInlineFunction (SourcePosition call_site_position, ValueNode *context, ValueNode *function, ValueNode *new_target)
void StartPrologue ()
void SetArgument (int i, ValueNode *value)
void InitializeRegister (interpreter::Register reg, ValueNode *value)
ValueNode * GetArgument (int i)
ValueNode * GetInlinedArgument (int i)
void BuildRegisterFrameInitialization (ValueNode *context=nullptr, ValueNode *closure=nullptr, ValueNode *new_target=nullptr)
void BuildMergeStates ()
BasicBlock * EndPrologue ()
void PeelLoop ()
void BuildLoopForPeeling ()
void OsrAnalyzePrequel ()
void BuildBody ()
SmiConstant * GetSmiConstant (int constant) const
TaggedIndexConstant * GetTaggedIndexConstant (int constant)
Int32Constant * GetInt32Constant (int32_t constant)
IntPtrConstant * GetIntPtrConstant (intptr_t constant)
Uint32Constant * GetUint32Constant (int constant)
Float64Constant * GetFloat64Constant (double constant)
Float64Constant * GetFloat64Constant (Float64 constant)
RootConstant * GetRootConstant (RootIndex index)
RootConstant * GetBooleanConstant (bool value)
ValueNode * GetConstant (compiler::ObjectRef ref)
ValueNode * GetTrustedConstant (compiler::HeapObjectRef ref, IndirectPointerTag tag)
ValueNode * GetNumberConstant (double constant)
Graph * graph () const
Zone * zone () const
MaglevCompilationUnit * compilation_unit () const
const InterpreterFrameState & current_interpreter_frame () const
MaglevCallerDetails * caller_details () const
const DeoptFrameScope * current_deopt_scope () const
compiler::JSHeapBroker * broker () const
LocalIsolate * local_isolate () const
bool has_graph_labeller () const
MaglevGraphLabeller * graph_labeller () const
bool is_inline () const
int inlining_depth () const
bool is_eager_inline () const
DeoptFrame GetLatestCheckpointedFrame ()
bool need_checkpointed_loop_entry ()
bool TopLevelFunctionPassMaglevPrintFilter ()
void RecordUseReprHint (Phi *phi, UseRepresentationSet reprs)
void RecordUseReprHint (Phi *phi, UseRepresentation repr)
void RecordUseReprHintIfPhi (ValueNode *node, UseRepresentation repr)
void set_current_block (BasicBlock *block)
BasicBlock * FinishInlinedBlockForCaller (ControlNode *control_node, ZoneVector< Node * > rem_nodes_in_call_block)
ZoneVector< Node * > & node_buffer ()
uint32_t NewObjectId ()
bool is_turbolev () const
bool is_non_eager_inlining_enabled () const
int max_inlined_bytecode_size ()
int max_inlined_bytecode_size_small ()
float min_inlining_frequency ()
int max_inlined_bytecode_size_cumulative ()
int max_inline_depth ()
DeoptFrame * AddInlinedArgumentsToDeoptFrame (DeoptFrame *deopt_frame, const MaglevCompilationUnit *unit, ValueNode *closure, base::Vector< ValueNode * > args)
Private Types
enum ContextSlotMutability { kImmutable
, kMutable
 }
enum class StringAtOOBMode { kElement
, kCharAt
 }
enum class TrackObjectMode { kLoad
, kStore
 }
enum InferHasInPrototypeChainResult { kMayBeInPrototypeChain
, kIsInPrototypeChain
, kIsNotInPrototypeChain
 }
enum class BranchType { kBranchIfTrue
, kBranchIfFalse
 }
enum class BranchSpecializationMode { kDefault
, kAlwaysBoolean
 }
enum class BranchResult { kDefault
, kAlwaysTrue
, kAlwaysFalse
 }
using InitialCallback = std::function< ReduceResult(ValueNode *)>
using ProcessElementCallback = std::function< void(ValueNode *, ValueNode *)>
using GetDeoptScopeCallback = std::function< DeoptFrameScope(compiler::JSFunctionRef, ValueNode *, ValueNode *, ValueNode *, ValueNode *, ValueNode *, ValueNode *)>
using TypeOfLiteralFlag = interpreter::TestTypeOfFlags::LiteralFlag
Private Member Functions
bool CheckType (ValueNode *node, NodeType type, NodeType *old=nullptr)
NodeType CheckTypes (ValueNode *node, std::initializer_list< NodeType > types)
bool EnsureType (ValueNode *node, NodeType type, NodeType *old=nullptr)
template<typename Function >
bool EnsureType (ValueNode *node, NodeType type, Function ensure_new_type)
NodeType GetType (ValueNode *node)
NodeInfo * GetOrCreateInfoFor (ValueNode *node)
bool HaveDisjointTypes (ValueNode *lhs, ValueNode *rhs)
bool HasDisjointType (ValueNode *lhs, NodeType rhs_type)
void SetKnownValue (ValueNode *node, compiler::ObjectRef constant, NodeType new_node_type)
bool ShouldEmitInterruptBudgetChecks ()
bool ShouldEmitOsrInterruptBudgetChecks ()
bool MaglevIsTopTier () const
BasicBlock * CreateEdgeSplitBlock (BasicBlockRef &jump_targets, BasicBlock *predecessor)
void ProcessMergePointAtExceptionHandlerStart (int offset)
void ProcessMergePoint (int offset, bool preserve_known_node_aspects)
void ProcessMergePointPredecessors (MergePointInterpreterFrameState &merge_state, BasicBlockRef &jump_targets)
void RegisterPhisWithGraphLabeller (MergePointInterpreterFrameState &merge_state)
bool IsOffsetAMergePoint (int offset)
ValueNode * GetContextAtDepth (ValueNode *context, size_t depth)
bool CheckContextExtensions (size_t depth)
ReduceResult EmitUnconditionalDeopt (DeoptimizeReason reason)
void KillPeeledLoopTargets (int peelings)
void MarkBytecodeDead ()
void UpdateSourceAndBytecodePosition (int offset)
void PrintVirtualObjects ()
void VisitSingleBytecode ()
void AddInitializedNodeToGraph (Node *node)
template<typename NodeT , typename Function , typename... Args>
NodeT * AddNewNode (size_t input_count, Function &&post_create_input_initializer, Args &&... args)
template<typename NodeT , typename... Args>
NodeT * AddNewNodeOrGetEquivalent (std::initializer_list< ValueNode * > raw_inputs, Args &&... args)
template<typename NodeT , typename... Args>
NodeT * AddNewNode (std::initializer_list< ValueNode * > inputs, Args &&... args)
template<typename NodeT , typename... Args>
NodeT * CreateNewConstantNode (Args &&... args) const
template<typename NodeT >
NodeT * AttachExtraInfoAndAddToGraph (NodeT *node)
template<typename NodeT >
void AttachDeoptCheckpoint (NodeT *node)
template<typename NodeT >
void AttachEagerDeoptInfo (NodeT *node)
template<typename NodeT >
void AttachLazyDeoptInfo (NodeT *node)
template<typename NodeT >
void AttachExceptionHandlerInfo (NodeT *node)
bool IsInsideTryBlock () const
MergePointInterpreterFrameState * GetCatchBlockFrameState ()
CatchBlockDetails GetCurrentTryCatchBlock ()
CatchBlockDetails GetTryCatchBlockForNonEagerInlining (ExceptionHandlerInfo *info)
bool ContextMayAlias (ValueNode *context, compiler::OptionalScopeInfoRef scope_info)
bool TrySpecializeLoadContextSlotToFunctionContext (ValueNode *context, int slot_index, ContextSlotMutability slot_mutability)
ValueNode * TrySpecializeLoadContextSlot (ValueNode *context, int index)
ValueNode * LoadAndCacheContextSlot (ValueNode *context, int offset, ContextSlotMutability slot_mutability, ContextMode context_mode)
MaybeReduceResult TrySpecializeStoreContextSlot (ValueNode *context, int index, ValueNode *value, Node **store)
ReduceResult StoreAndCacheContextSlot (ValueNode *context, int index, ValueNode *value, ContextMode context_mode)
ValueNode * TryGetParentContext (ValueNode *node)
void MinimizeContextChainDepth (ValueNode **context, size_t *depth)
void EscapeContext ()
void BuildLoadContextSlot (ValueNode *context, size_t depth, int slot_index, ContextSlotMutability slot_mutability, ContextMode context_mode)
ReduceResult BuildStoreContextSlot (ValueNode *context, size_t depth, int slot_index, ValueNode *value, ContextMode context_mode)
void BuildStoreMap (ValueNode *object, compiler::MapRef map, StoreMap::Kind kind)
ValueNode * BuildExtendPropertiesBackingStore (compiler::MapRef map, ValueNode *receiver, ValueNode *property_array)
template<Builtin kBuiltin>
CallBuiltin * BuildCallBuiltin (std::initializer_list< ValueNode * > inputs)
template<Builtin kBuiltin>
CallBuiltin * BuildCallBuiltin (std::initializer_list< ValueNode * > inputs, compiler::FeedbackSource const &feedback, CallBuiltin::FeedbackSlotType slot_type=CallBuiltin::kTaggedIndex)
CallCPPBuiltin * BuildCallCPPBuiltin (Builtin builtin, ValueNode *target, ValueNode *new_target, std::initializer_list< ValueNode * > inputs)
ReduceResult BuildLoadGlobal (compiler::NameRef name, compiler::FeedbackSource &feedback_source, TypeofMode typeof_mode)
ValueNode * BuildToString (ValueNode *value, ToString::ConversionMode mode)
constexpr bool RuntimeFunctionCanThrow (Runtime::FunctionId function_id)
ReduceResult BuildCallRuntime (Runtime::FunctionId function_id, std::initializer_list< ValueNode * > inputs)
ReduceResult BuildAbort (AbortReason reason)
void Print (const char *str)
void Print (ValueNode *value)
void Print (const char *str, ValueNode *value)
ValueNode * GetFeedbackCell ()
ValueNode * GetClosure () const
ValueNode * GetContext () const
void SetContext (ValueNode *context)
FeedbackSlot GetSlotOperand (int operand_index) const
uint32_t GetFlag8Operand (int operand_index) const
uint32_t GetFlag16Operand (int operand_index) const
template<class T >
compiler::ref_traits< T >::ref_type GetRefOperand (int operand_index) requires(is_taggable_v< T >)
MaybeReduceResult GetConstantSingleCharacterStringFromCode (uint16_t)
ValueNode * GetRegisterInput (Register reg)
void MoveNodeBetweenRegisters (interpreter::Register src, interpreter::Register dst)
ValueNode * GetTaggedValue (ValueNode *value, UseReprHintRecording record_use_repr_hint=UseReprHintRecording::kRecord)
ReduceResult GetSmiValue (ValueNode *value, UseReprHintRecording record_use_repr_hint=UseReprHintRecording::kRecord)
MaybeReduceResult GetSmiValue (interpreter::Register reg, UseReprHintRecording record_use_repr_hint=UseReprHintRecording::kRecord)
ValueNode * GetTaggedValue (interpreter::Register reg, UseReprHintRecording record_use_repr_hint=UseReprHintRecording::kRecord)
ValueNode * GetInternalizedString (interpreter::Register reg)
ValueNode * GetTruncatedInt32ForToNumber (ValueNode *value, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetTruncatedInt32ForToNumber (interpreter::Register reg, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetUint8ClampedForToNumber (ValueNode *value)
ValueNode * GetUint8ClampedForToNumber (interpreter::Register reg)
std::optional< int32_t > TryGetInt32Constant (ValueNode *value)
std::optional< uint32_t > TryGetUint32Constant (ValueNode *value)
ValueNode * GetInt32 (ValueNode *value, bool can_be_heap_number=false)
void EnsureInt32 (ValueNode *value, bool can_be_heap_number=false)
void EnsureInt32 (interpreter::Register reg)
std::optional< double > TryGetFloat64Constant (ValueNode *value, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetFloat64 (ValueNode *value)
ValueNode * GetFloat64 (interpreter::Register reg)
ValueNode * GetHoleyFloat64 (ValueNode *value, bool convert_hole_to_undefined)
ValueNode * GetFloat64ForToNumber (ValueNode *value, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetFloat64ForToNumber (interpreter::Register reg, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetHoleyFloat64ForToNumber (ValueNode *value, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetHoleyFloat64ForToNumber (interpreter::Register reg, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetAccumulator ()
MaybeReduceResult GetAccumulatorSmi (UseReprHintRecording record_use_repr_hint=UseReprHintRecording::kRecord)
ValueNode * GetAccumulatorTruncatedInt32ForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetAccumulatorUint8ClampedForToNumber ()
ValueNode * GetAccumulatorHoleyFloat64ForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ValueNode * GetSilencedNaN (ValueNode *value)
bool IsRegisterEqualToAccumulator (int operand_index)
ValueNode * LoadRegister (int operand_index)
ValueNode * LoadRegisterHoleyFloat64ForToNumber (int operand_index, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<typename NodeT >
void SetAccumulator (NodeT *node)
void ClobberAccumulator ()
ValueNode * GetSecondValue (ValueNode *result)
template<typename NodeT >
void StoreRegister (interpreter::Register target, NodeT *value)
void SetAccumulatorInBranch (ValueNode *value)
template<typename NodeT >
void StoreRegisterPair (std::pair< interpreter::Register, interpreter::Register > target, NodeT *value)
std::pair< interpreter::Register, int > GetResultLocationAndSize () const
DeoptFrame * GetCallerDeoptFrame ()
DeoptFrame * GetDeoptFrameForEagerCall (const MaglevCompilationUnit *unit, ValueNode *closure, base::Vector< ValueNode * > args)
DeoptFrame GetDeoptFrameForLazyDeopt (interpreter::Register result_location, int result_size)
DeoptFrame GetDeoptFrameForLazyDeoptHelper (interpreter::Register result_location, int result_size, DeoptFrameScope *scope, bool mark_accumulator_dead)
InterpretedDeoptFrame GetDeoptFrameForEntryStackCheck ()
template<typename NodeT >
void MarkPossibleSideEffect (NodeT *node)
template<bool is_possible_map_change = true>
void ResetBuilderCachedState ()
int next_offset () const
const compiler::BytecodeLivenessState * GetInLiveness () const
const compiler::BytecodeLivenessState * GetInLivenessFor (int offset) const
const compiler::BytecodeLivenessState * GetOutLiveness () const
const compiler::BytecodeLivenessState * GetOutLivenessFor (int offset) const
void StartNewBlock (int offset, BasicBlock *predecessor)
void StartNewBlock (BasicBlock *predecessor, MergePointInterpreterFrameState *merge_state, BasicBlockRef &refs_to_block)
template<UseReprHintRecording hint = UseReprHintRecording::kRecord>
ValueNode * ConvertInputTo (ValueNode *input, ValueRepresentation expected)
template<typename NodeT >
void SetNodeInputs (NodeT *node, std::initializer_list< ValueNode * > inputs)
void FlushNodesToBlock ()
template<typename ControlNodeT , typename... Args>
BasicBlock * FinishBlock (std::initializer_list< ValueNode * > control_inputs, Args &&... args)
void StartFallthroughBlock (int next_block_offset, BasicBlock *predecessor)
ValueNode * GetValueOrUndefined (ValueNode *maybe_value)
ValueNode * GetConvertReceiver (compiler::SharedFunctionInfoRef shared, const CallArguments &args)
base::Vector< ValueNode * > GetArgumentsAsArrayOfValueNodes (compiler::SharedFunctionInfoRef shared, const CallArguments &args)
compiler::OptionalHeapObjectRef TryGetConstant (ValueNode *node, ValueNode **constant_node=nullptr)
std::optional< ValueNode * > TryGetConstantAlternative (ValueNode *node)
template<typename LoadNode >
MaybeReduceResult TryBuildLoadDataView (const CallArguments &args, ExternalArrayType type)
template<typename StoreNode , typename Function >
MaybeReduceResult TryBuildStoreDataView (const CallArguments &args, ExternalArrayType type, Function &&getValue)
MaybeReduceResult TryReduceDatePrototypeGetField (compiler::JSFunctionRef target, CallArguments &args, JSDate::FieldIndex field)
MaybeReduceResult TryReduceArrayIteratingBuiltin (const char *name, compiler::JSFunctionRef target, CallArguments &args, GetDeoptScopeCallback get_eager_deopt_scope, GetDeoptScopeCallback get_lazy_deopt_scope, const std::optional< InitialCallback > &initial_callback={}, const std::optional< ProcessElementCallback > &process_element_callback={})
MaybeReduceResult TryReduceConstantStringAt (ValueNode *object, ValueNode *index, StringAtOOBMode oob_mode)
MaybeReduceResult TryReduceGetProto (ValueNode *node)
template<typename MapKindsT , typename IndexToElementsKindFunc , typename BuildKindSpecificFunc >
MaybeReduceResult BuildJSArrayBuiltinMapSwitchOnElementsKind (ValueNode *receiver, const MapKindsT &map_kinds, MaglevSubGraphBuilder &sub_graph, std::optional< MaglevSubGraphBuilder::Label > &do_return, int unique_kind_count, IndexToElementsKindFunc &&index_to_elements_kind, BuildKindSpecificFunc &&build_kind_specific)
MaybeReduceResult DoTryReduceMathRound (CallArguments &args, Float64Round::Kind kind)
template<typename CallNode , typename... Args>
CallNode * AddNewCallNode (const CallArguments &args, Args &&... extra_args)
MaybeReduceResult TryReduceGetIterator (ValueNode *receiver, int load_slot, int call_slot)
ValueNode * BuildCallSelf (ValueNode *context, ValueNode *function, ValueNode *new_target, compiler::SharedFunctionInfoRef shared, CallArguments &args)
MaybeReduceResult TryReduceBuiltin (compiler::JSFunctionRef target, compiler::SharedFunctionInfoRef shared, CallArguments &args, const compiler::FeedbackSource &feedback_source)
bool TargetIsCurrentCompilingUnit (compiler::JSFunctionRef target)
CallKnownJSFunction * BuildCallKnownJSFunction (ValueNode *context, ValueNode *function, ValueNode *new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments &args, const compiler::FeedbackSource &feedback_source)
CallKnownJSFunction * BuildCallKnownJSFunction (ValueNode *context, ValueNode *function, ValueNode *new_target, compiler::SharedFunctionInfoRef shared, base::Vector< ValueNode * > arguments)
MaybeReduceResult TryBuildCallKnownJSFunction (compiler::JSFunctionRef function, ValueNode *new_target, CallArguments &args, const compiler::FeedbackSource &feedback_source)
MaybeReduceResult TryBuildCallKnownJSFunction (ValueNode *context, ValueNode *function, ValueNode *new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments &args, const compiler::FeedbackSource &feedback_source)
bool CanInlineCall (compiler::SharedFunctionInfoRef shared, float call_frequency)
bool ShouldEagerInlineCall (compiler::SharedFunctionInfoRef shared)
ReduceResult BuildEagerInlineCall (ValueNode *context, ValueNode *function, ValueNode *new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments &args, float call_frequency)
MaybeReduceResult TryBuildInlineCall (ValueNode *context, ValueNode *function, ValueNode *new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments &args, const compiler::FeedbackSource &feedback_source)
ValueNode * BuildGenericCall (ValueNode *target, Call::TargetType target_type, const CallArguments &args)
MaybeReduceResult TryReduceCallForConstant (compiler::JSFunctionRef target, CallArguments &args, const compiler::FeedbackSource &feedback_source=compiler::FeedbackSource())
MaybeReduceResult TryReduceCallForTarget (ValueNode *target_node, compiler::JSFunctionRef target, CallArguments &args, const compiler::FeedbackSource &feedback_source)
MaybeReduceResult TryReduceCallForNewClosure (ValueNode *target_node, ValueNode *target_context, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments &args, const compiler::FeedbackSource &feedback_source)
MaybeReduceResult TryBuildCallKnownApiFunction (compiler::JSFunctionRef function, compiler::SharedFunctionInfoRef shared, CallArguments &args)
compiler::HolderLookupResult TryInferApiHolderValue (compiler::FunctionTemplateInfoRef function_template_info, ValueNode *receiver)
MaybeReduceResult TryReduceCallForApiFunction (compiler::FunctionTemplateInfoRef api_callback, compiler::OptionalSharedFunctionInfoRef maybe_shared, CallArguments &args)
MaybeReduceResult TryReduceFunctionPrototypeApplyCallWithReceiver (compiler::OptionalHeapObjectRef maybe_receiver, CallArguments &args, const compiler::FeedbackSource &feedback_source)
ReduceResult ReduceCallWithArrayLikeForArgumentsObject (ValueNode *target_node, CallArguments &args, VirtualObject *arguments_object, const compiler::FeedbackSource &feedback_source)
ReduceResult ReduceCallWithArrayLike (ValueNode *target_node, CallArguments &args, const compiler::FeedbackSource &feedback_source)
ReduceResult ReduceCall (ValueNode *target_node, CallArguments &args, const compiler::FeedbackSource &feedback_source=compiler::FeedbackSource())
ReduceResult BuildCallWithFeedback (ValueNode *target_node, CallArguments &args, const compiler::FeedbackSource &feedback_source)
ReduceResult BuildCallFromRegisterList (ConvertReceiverMode receiver_mode)
ReduceResult BuildCallFromRegisters (int argc_count, ConvertReceiverMode receiver_mode)
ValueNode * BuildElementsArray (int length)
ReduceResult BuildAndAllocateKeyValueArray (ValueNode *key, ValueNode *value)
ReduceResult BuildAndAllocateJSArray (compiler::MapRef map, ValueNode *length, ValueNode *elements, const compiler::SlackTrackingPrediction &slack_tracking_prediction, AllocationType allocation_type)
ValueNode * BuildAndAllocateJSArrayIterator (ValueNode *array, IterationKind iteration_kind)
MaybeReduceResult TryBuildAndAllocateJSGeneratorObject (ValueNode *closure, ValueNode *receiver)
ValueNode * BuildGenericConstruct (ValueNode *target, ValueNode *new_target, ValueNode *context, const CallArguments &args, const compiler::FeedbackSource &feedback_source=compiler::FeedbackSource())
MaybeReduceResult TryReduceConstructArrayConstructor (compiler::JSFunctionRef array_function, CallArguments &args, compiler::OptionalAllocationSiteRef maybe_allocation_site={})
MaybeReduceResult TryReduceConstructBuiltin (compiler::JSFunctionRef builtin, compiler::SharedFunctionInfoRef shared_function_info, ValueNode *target, CallArguments &args)
MaybeReduceResult TryReduceConstructGeneric (compiler::JSFunctionRef function, compiler::SharedFunctionInfoRef shared_function_info, ValueNode *target, ValueNode *new_target, CallArguments &args, compiler::FeedbackSource &feedback_source)
MaybeReduceResult TryReduceConstruct (compiler::HeapObjectRef feedback_target, ValueNode *target, ValueNode *new_target, CallArguments &args, compiler::FeedbackSource &feedback_source)
ReduceResult BuildConstruct (ValueNode *target, ValueNode *new_target, CallArguments &args, compiler::FeedbackSource &feedback_source)
MaybeReduceResult TryBuildScriptContextStore (const compiler::GlobalAccessFeedback &global_access_feedback)
MaybeReduceResult TryBuildPropertyCellStore (const compiler::GlobalAccessFeedback &global_access_feedback)
MaybeReduceResult TryBuildGlobalStore (const compiler::GlobalAccessFeedback &global_access_feedback)
MaybeReduceResult TryBuildScriptContextConstantLoad (const compiler::GlobalAccessFeedback &global_access_feedback)
MaybeReduceResult TryBuildScriptContextLoad (const compiler::GlobalAccessFeedback &global_access_feedback)
MaybeReduceResult TryBuildPropertyCellLoad (const compiler::GlobalAccessFeedback &global_access_feedback)
MaybeReduceResult TryBuildGlobalLoad (const compiler::GlobalAccessFeedback &global_access_feedback)
bool TryBuildFindNonDefaultConstructorOrConstruct (ValueNode *this_function, ValueNode *new_target, std::pair< interpreter::Register, interpreter::Register > result)
ValueNode * BuildSmiUntag (ValueNode *node)
ValueNode * BuildNumberOrOddballToFloat64 (ValueNode *node, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
ReduceResult BuildCheckSmi (ValueNode *object, bool elidable=true)
ReduceResult BuildCheckNumber (ValueNode *object)
ReduceResult BuildCheckHeapObject (ValueNode *object)
ReduceResult BuildCheckJSFunction (ValueNode *object)
ReduceResult BuildCheckJSReceiver (ValueNode *object)
ReduceResult BuildCheckJSReceiverOrNullOrUndefined (ValueNode *object)
ReduceResult BuildCheckSeqOneByteString (ValueNode *object)
ReduceResult BuildCheckString (ValueNode *object)
ReduceResult BuildCheckStringOrStringWrapper (ValueNode *object)
ReduceResult BuildCheckStringOrOddball (ValueNode *object)
ReduceResult BuildCheckSymbol (ValueNode *object)
ReduceResult BuildCheckMaps (ValueNode *object, base::Vector< const compiler::MapRef > maps, std::optional< ValueNode * > map={}, bool has_deprecated_map_without_migration_target=false, bool migration_done_outside=false)
ReduceResult BuildTransitionElementsKindOrCheckMap (ValueNode *heap_object, ValueNode *object_map, const ZoneVector< compiler::MapRef > &transition_sources, compiler::MapRef transition_target)
ReduceResult BuildCompareMaps (ValueNode *heap_object, ValueNode *object_map, base::Vector< const compiler::MapRef > maps, MaglevSubGraphBuilder *sub_graph, std::optional< MaglevSubGraphBuilder::Label > &if_not_matched)
ReduceResult BuildTransitionElementsKindAndCompareMaps (ValueNode *heap_object, ValueNode *object_map, const ZoneVector< compiler::MapRef > &transition_sources, compiler::MapRef transition_target, MaglevSubGraphBuilder *sub_graph, std::optional< MaglevSubGraphBuilder::Label > &if_not_matched)
ReduceResult BuildCheckInternalizedStringValueOrByReference (ValueNode *node, compiler::HeapObjectRef ref, DeoptimizeReason reason)
ReduceResult BuildCheckNumericalValueOrByReference (ValueNode *node, compiler::ObjectRef ref, DeoptimizeReason reason)
ReduceResult BuildCheckValueByReference (ValueNode *node, compiler::HeapObjectRef ref, DeoptimizeReason reason)
ReduceResult BuildCheckNumericalValue (ValueNode *node, compiler::ObjectRef ref, DeoptimizeReason reason)
ValueNode * BuildConvertHoleToUndefined (ValueNode *node)
ReduceResult BuildCheckNotHole (ValueNode *node)
template<bool flip = false>
ValueNode * BuildToBoolean (ValueNode *node)
ValueNode * BuildLogicalNot (ValueNode *value)
ValueNode * BuildTestUndetectable (ValueNode *value)
ReduceResult BuildToNumberOrToNumeric (Object::Conversion mode)
bool CanTrackObjectChanges (ValueNode *object, TrackObjectMode mode)
bool CanElideWriteBarrier (ValueNode *object, ValueNode *value)
void BuildInitializeStore (InlinedAllocation *alloc, ValueNode *value, int offset)
void TryBuildStoreTaggedFieldToAllocation (ValueNode *object, ValueNode *value, int offset)
template<typename Instruction = LoadTaggedField, typename... Args>
ValueNode * BuildLoadTaggedField (ValueNode *object, uint32_t offset, Args &&... args)
Node * BuildStoreTaggedField (ValueNode *object, ValueNode *value, int offset, StoreTaggedMode store_mode)
Node * BuildStoreTaggedFieldNoWriteBarrier (ValueNode *object, ValueNode *value, int offset, StoreTaggedMode store_mode)
void BuildStoreTrustedPointerField (ValueNode *object, ValueNode *value, int offset, IndirectPointerTag tag, StoreTaggedMode store_mode)
ValueNode * BuildLoadFixedArrayElement (ValueNode *elements, int index)
ValueNode * BuildLoadFixedArrayElement (ValueNode *elements, ValueNode *index)
void BuildStoreFixedArrayElement (ValueNode *elements, ValueNode *index, ValueNode *value)
ValueNode * BuildLoadFixedDoubleArrayElement (ValueNode *elements, int index)
ValueNode * BuildLoadFixedDoubleArrayElement (ValueNode *elements, ValueNode *index)
void BuildStoreFixedDoubleArrayElement (ValueNode *elements, ValueNode *index, ValueNode *value)
ValueNode * BuildLoadHoleyFixedDoubleArrayElement (ValueNode *elements, ValueNode *index, bool convert_hole)
ValueNode * GetInt32ElementIndex (interpreter::Register reg)
ValueNode * GetInt32ElementIndex (ValueNode *index_object)
ReduceResult GetUint32ElementIndex (interpreter::Register reg)
ReduceResult GetUint32ElementIndex (ValueNode *index_object)
bool CanTreatHoleAsUndefined (base::Vector< const compiler::MapRef > const &receiver_maps)
compiler::OptionalObjectRef TryFoldLoadDictPrototypeConstant (compiler::PropertyAccessInfo const &access_info)
compiler::OptionalJSObjectRef TryGetConstantDataFieldHolder (compiler::PropertyAccessInfo const &access_info, ValueNode *lookup_start_object)
compiler::OptionalObjectRef TryFoldLoadConstantDataField (compiler::JSObjectRef holder, compiler::PropertyAccessInfo const &access_info)
std::optional< Float64 > TryFoldLoadConstantDoubleField (compiler::JSObjectRef holder, compiler::PropertyAccessInfo const &access_info)
ValueNode * BuildLoadField (compiler::PropertyAccessInfo const &access_info, ValueNode *lookup_start_object, compiler::NameRef name)
MaybeReduceResult TryBuildStoreField (compiler::PropertyAccessInfo const &access_info, ValueNode *receiver, compiler::AccessMode access_mode)
MaybeReduceResult TryBuildPropertyGetterCall (compiler::PropertyAccessInfo const &access_info, ValueNode *receiver, ValueNode *lookup_start_object)
MaybeReduceResult TryBuildPropertySetterCall (compiler::PropertyAccessInfo const &access_info, ValueNode *receiver, ValueNode *lookup_start_object, ValueNode *value)
MaybeReduceResult TryBuildGetKeyedPropertyWithEnumeratedKey (ValueNode *object, const compiler::FeedbackSource &feedback_source, const compiler::ProcessedFeedback &processed_feedback)
ReduceResult BuildGetKeyedProperty (ValueNode *object, const compiler::FeedbackSource &feedback_source, const compiler::ProcessedFeedback &processed_feedback)
ValueNode * BuildLoadFixedArrayLength (ValueNode *fixed_array)
ValueNode * BuildLoadJSArrayLength (ValueNode *js_array, NodeType length_type=NodeType::kSmi)
ValueNode * BuildLoadElements (ValueNode *object)
ValueNode * BuildLoadJSFunctionFeedbackCell (ValueNode *closure)
ValueNode * BuildLoadJSFunctionContext (ValueNode *closure)
MaybeReduceResult TryBuildCheckInt32Condition (ValueNode *lhs, ValueNode *rhs, AssertCondition condition, DeoptimizeReason reason, bool allow_unconditional_deopt=true)
MaybeReduceResult TryBuildPropertyLoad (ValueNode *receiver, ValueNode *lookup_start_object, compiler::NameRef name, compiler::PropertyAccessInfo const &access_info)
MaybeReduceResult TryBuildPropertyStore (ValueNode *receiver, ValueNode *lookup_start_object, compiler::NameRef name, compiler::PropertyAccessInfo const &access_info, compiler::AccessMode access_mode)
MaybeReduceResult TryBuildPropertyAccess (ValueNode *receiver, ValueNode *lookup_start_object, compiler::NameRef name, compiler::PropertyAccessInfo const &access_info, compiler::AccessMode access_mode)
template<typename GenericAccessFunc >
MaybeReduceResult TryBuildNamedAccess (ValueNode *receiver, ValueNode *lookup_start_object, compiler::NamedAccessFeedback const &feedback, compiler::FeedbackSource const &feedback_source, compiler::AccessMode access_mode, GenericAccessFunc &&build_generic_access)
template<typename GenericAccessFunc >
MaybeReduceResult TryBuildLoadNamedProperty (ValueNode *receiver, ValueNode *lookup_start_object, compiler::NameRef name, compiler::FeedbackSource &feedback_source, GenericAccessFunc &&build_generic_access)
MaybeReduceResult TryBuildLoadNamedProperty (ValueNode *receiver, compiler::NameRef name, compiler::FeedbackSource &feedback_source)
ReduceResult BuildLoadTypedArrayLength (ValueNode *object, ElementsKind elements_kind)
ValueNode * BuildLoadTypedArrayElement (ValueNode *object, ValueNode *index, ElementsKind elements_kind)
ValueNode * BuildLoadConstantTypedArrayElement (compiler::JSTypedArrayRef typed_array, ValueNode *index, ElementsKind elements_kind)
void BuildStoreTypedArrayElement (ValueNode *object, ValueNode *index, ElementsKind elements_kind)
void BuildStoreConstantTypedArrayElement (compiler::JSTypedArrayRef typed_array, ValueNode *index, ElementsKind elements_kind)
MaybeReduceResult TryBuildElementAccessOnString (ValueNode *object, ValueNode *index, const compiler::ElementAccessFeedback &access_info, compiler::KeyedAccessMode const &keyed_mode)
MaybeReduceResult TryBuildElementAccessOnTypedArray (ValueNode *object, ValueNode *index, const compiler::ElementAccessInfo &access_info, compiler::KeyedAccessMode const &keyed_mode)
MaybeReduceResult TryBuildElementLoadOnJSArrayOrJSObject (ValueNode *object, ValueNode *index, base::Vector< const compiler::MapRef > maps, ElementsKind kind, KeyedAccessLoadMode load_mode)
MaybeReduceResult TryBuildElementStoreOnJSArrayOrJSObject (ValueNode *object, ValueNode *index_object, ValueNode *value, base::Vector< const compiler::MapRef > maps, ElementsKind kind, const compiler::KeyedAccessMode &keyed_mode)
MaybeReduceResult TryBuildElementAccessOnJSArrayOrJSObject (ValueNode *object, ValueNode *index, const compiler::ElementAccessInfo &access_info, compiler::KeyedAccessMode const &keyed_mode)
template<typename GenericAccessFunc >
MaybeReduceResult TryBuildElementAccess (ValueNode *object, ValueNode *index, compiler::ElementAccessFeedback const &feedback, compiler::FeedbackSource const &feedback_source, GenericAccessFunc &&build_generic_access)
template<typename GenericAccessFunc >
MaybeReduceResult TryBuildPolymorphicElementAccess (ValueNode *object, ValueNode *index, const compiler::KeyedAccessMode &keyed_mode, const ZoneVector< compiler::ElementAccessInfo > &access_infos, GenericAccessFunc &&build_generic_access)
template<typename GenericAccessFunc >
MaybeReduceResult TryBuildPolymorphicPropertyAccess (ValueNode *receiver, ValueNode *lookup_start_object, compiler::NamedAccessFeedback const &feedback, compiler::AccessMode access_mode, const ZoneVector< compiler::PropertyAccessInfo > &access_infos, GenericAccessFunc &&build_generic_access)
std::optional< ContinuationOffsets > FindContinuationForPolymorphicPropertyLoad ()
void BuildContinuationForPolymorphicPropertyLoad (const ContinuationOffsets &offsets)
void RecordKnownProperty (ValueNode *lookup_start_object, KnownNodeAspects::LoadedPropertyMapKey key, ValueNode *value, bool is_const, compiler::AccessMode access_mode)
MaybeReduceResult TryReuseKnownPropertyLoad (ValueNode *lookup_start_object, compiler::NameRef name)
ValueNode * BuildLoadStringLength (ValueNode *string)
ReduceResult ConvertForStoring (ValueNode *node, ElementsKind kind)
InferHasInPrototypeChainResult InferHasInPrototypeChain (ValueNode *receiver, compiler::HeapObjectRef prototype)
MaybeReduceResult TryBuildFastHasInPrototypeChain (ValueNode *object, compiler::HeapObjectRef prototype)
ReduceResult BuildHasInPrototypeChain (ValueNode *object, compiler::HeapObjectRef prototype)
MaybeReduceResult TryBuildFastOrdinaryHasInstance (ValueNode *object, compiler::JSObjectRef callable, ValueNode *callable_node)
ReduceResult BuildOrdinaryHasInstance (ValueNode *object, compiler::JSObjectRef callable, ValueNode *callable_node)
MaybeReduceResult TryBuildFastInstanceOf (ValueNode *object, compiler::JSObjectRef callable_ref, ValueNode *callable_node)
MaybeReduceResult TryBuildFastInstanceOfWithFeedback (ValueNode *object, ValueNode *callable, compiler::FeedbackSource feedback_source)
VirtualObject * GetObjectFromAllocation (InlinedAllocation *allocation)
VirtualObject * GetModifiableObjectFromAllocation (InlinedAllocation *allocation)
VirtualObject * DeepCopyVirtualObject (VirtualObject *vobj)
VirtualObject * CreateVirtualObject (compiler::MapRef map, uint32_t slot_count_including_map)
VirtualObject * CreateHeapNumber (Float64 value)
VirtualObject * CreateDoubleFixedArray (uint32_t elements_length, compiler::FixedDoubleArrayRef elements)
VirtualObject * CreateJSObject (compiler::MapRef map)
VirtualObject * CreateConsString (ValueNode *map, ValueNode *length, ValueNode *first, ValueNode *second)
ReduceResult CreateJSArray (compiler::MapRef map, int instance_size, ValueNode *length)
VirtualObject * CreateJSArrayIterator (compiler::MapRef map, ValueNode *iterated_object, IterationKind kind)
VirtualObject * CreateJSConstructor (compiler::JSFunctionRef constructor)
VirtualObject * CreateFixedArray (compiler::MapRef map, int length)
VirtualObject * CreateContext (compiler::MapRef map, int length, compiler::ScopeInfoRef scope_info, ValueNode *previous_context, std::optional< ValueNode * > extension={})
VirtualObject * CreateArgumentsObject (compiler::MapRef map, ValueNode *length, ValueNode *elements, std::optional< ValueNode * > callee={})
VirtualObject * CreateMappedArgumentsElements (compiler::MapRef map, int mapped_count, ValueNode *context, ValueNode *unmapped_elements)
VirtualObject * CreateRegExpLiteralObject (compiler::MapRef map, compiler::RegExpBoilerplateDescriptionRef literal)
VirtualObject * CreateJSGeneratorObject (compiler::MapRef map, int instance_size, ValueNode *context, ValueNode *closure, ValueNode *receiver, ValueNode *register_file)
VirtualObject * CreateJSIteratorResult (compiler::MapRef map, ValueNode *value, ValueNode *done)
VirtualObject * CreateJSStringIterator (compiler::MapRef map, ValueNode *string)
InlinedAllocation * ExtendOrReallocateCurrentAllocationBlock (AllocationType allocation_type, VirtualObject *value)
void ClearCurrentAllocationBlock ()
void AddDeoptUse (ValueNode *node)
void AddDeoptUse (VirtualObject *alloc)
void AddNonEscapingUses (InlinedAllocation *allocation, int use_count)
std::optional< VirtualObject * > TryGetNonEscapingArgumentsObject (ValueNode *value)
MaybeReduceResult TryBuildFastCreateObjectOrArrayLiteral (const compiler::LiteralFeedback &feedback)
std::optional< VirtualObject * > TryReadBoilerplateForFastLiteral (compiler::JSObjectRef boilerplate, AllocationType allocation, int max_depth, int *max_properties)
InlinedAllocation * BuildInlinedAllocationForConsString (VirtualObject *object, AllocationType allocation)
InlinedAllocation * BuildInlinedAllocationForHeapNumber (VirtualObject *object, AllocationType allocation)
InlinedAllocation * BuildInlinedAllocationForDoubleFixedArray (VirtualObject *object, AllocationType allocation)
InlinedAllocation * BuildInlinedAllocation (VirtualObject *object, AllocationType allocation)
ValueNode * BuildInlinedArgumentsElements (int start_index, int length)
ValueNode * BuildInlinedUnmappedArgumentsElements (int mapped_count)
template<CreateArgumentsType type>
VirtualObject * BuildVirtualArgumentsObject ()
template<CreateArgumentsType type>
ValueNode * BuildAndAllocateArgumentsObject ()
bool CanAllocateSloppyArgumentElements ()
bool CanAllocateInlinedArgumentElements ()
MaybeReduceResult TryBuildInlinedAllocatedContext (compiler::MapRef map, compiler::ScopeInfoRef scope, int context_length)
template<Operation kOperation>
void BuildGenericUnaryOperationNode ()
template<Operation kOperation>
void BuildGenericBinaryOperationNode ()
template<Operation kOperation>
void BuildGenericBinarySmiOperationNode ()
template<Operation kOperation>
bool TryReduceCompareEqualAgainstConstant ()
template<Operation kOperation>
MaybeReduceResult TryFoldInt32UnaryOperation (ValueNode *value)
template<Operation kOperation>
MaybeReduceResult TryFoldInt32BinaryOperation (ValueNode *left, ValueNode *right)
template<Operation kOperation>
MaybeReduceResult TryFoldInt32BinaryOperation (ValueNode *left, int32_t cst_right)
template<Operation kOperation>
ReduceResult BuildInt32UnaryOperationNode ()
ReduceResult BuildTruncatingInt32BitwiseNotForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<Operation kOperation>
ReduceResult BuildInt32BinaryOperationNode ()
template<Operation kOperation>
ReduceResult BuildInt32BinarySmiOperationNode ()
template<Operation kOperation>
ReduceResult BuildTruncatingInt32BinaryOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<Operation kOperation>
ReduceResult BuildTruncatingInt32BinarySmiOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<Operation kOperation>
MaybeReduceResult TryFoldFloat64UnaryOperationForToNumber (TaggedToFloat64ConversionType conversion_type, ValueNode *value)
template<Operation kOperation>
MaybeReduceResult TryFoldFloat64BinaryOperationForToNumber (TaggedToFloat64ConversionType conversion_type, ValueNode *left, ValueNode *right)
template<Operation kOperation>
MaybeReduceResult TryFoldFloat64BinaryOperationForToNumber (TaggedToFloat64ConversionType conversion_type, ValueNode *left, double cst_right)
template<Operation kOperation>
ReduceResult BuildFloat64UnaryOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<Operation kOperation>
ReduceResult BuildFloat64BinaryOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<Operation kOperation>
ReduceResult BuildFloat64BinarySmiOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type)
template<Operation kOperation>
ReduceResult VisitUnaryOperation ()
template<Operation kOperation>
ReduceResult VisitBinaryOperation ()
template<Operation kOperation>
ReduceResult VisitBinarySmiOperation ()
ValueNode * BuildUnwrapStringWrapper (ValueNode *input)
ReduceResult BuildStringConcat (ValueNode *left, ValueNode *right)
ValueNode * BuildNewConsStringMap (ValueNode *left, ValueNode *right)
size_t StringLengthStaticLowerBound (ValueNode *string, int max_depth=2)
MaybeReduceResult TryBuildNewConsString (ValueNode *left, ValueNode *right, AllocationType allocation_type=AllocationType::kYoung)
template<Operation kOperation>
ReduceResult VisitCompareOperation ()
template<typename Function >
MaybeReduceResult TryReduceTypeOf (ValueNode *value, const Function &GetResult)
MaybeReduceResult TryReduceTypeOf (ValueNode *value)
void BeginLoopEffects (int loop_header)
void EndLoopEffects (int loop_header)
void MergeIntoFrameState (BasicBlock *block, int target)
void MergeDeadIntoFrameState (int target)
void MergeDeadLoopIntoFrameState (int target)
void MergeIntoInlinedReturnFrameState (BasicBlock *block)
bool HasValidInitialMap (compiler::JSFunctionRef new_target, compiler::JSFunctionRef constructor)
ValueNode * BuildTaggedEqual (ValueNode *lhs, ValueNode *rhs)
ValueNode * BuildTaggedEqual (ValueNode *lhs, RootIndex rhs_index)
BranchBuilder CreateBranchBuilder (BranchType jump_type=BranchType::kBranchIfTrue)
BranchBuilder CreateBranchBuilder (MaglevSubGraphBuilder *subgraph, MaglevSubGraphBuilder::Label *jump_label, BranchType jump_type=BranchType::kBranchIfTrue)
BranchResult BuildBranchIfRootConstant (BranchBuilder &builder, ValueNode *node, RootIndex root_index)
BranchResult BuildBranchIfToBooleanTrue (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfInt32ToBooleanTrue (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfIntPtrToBooleanTrue (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfFloat64ToBooleanTrue (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfFloat64IsHole (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfReferenceEqual (BranchBuilder &builder, ValueNode *lhs, ValueNode *rhs)
BranchResult BuildBranchIfInt32Compare (BranchBuilder &builder, Operation op, ValueNode *lhs, ValueNode *rhs)
BranchResult BuildBranchIfUint32Compare (BranchBuilder &builder, Operation op, ValueNode *lhs, ValueNode *rhs)
BranchResult BuildBranchIfUndefinedOrNull (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfUndetectable (BranchBuilder &builder, ValueNode *value)
BranchResult BuildBranchIfJSReceiver (BranchBuilder &builder, ValueNode *value)
BranchResult BuildBranchIfTrue (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfNull (BranchBuilder &builder, ValueNode *node)
BranchResult BuildBranchIfUndefined (BranchBuilder &builder, ValueNode *node)
BasicBlock * BuildBranchIfReferenceEqual (ValueNode *lhs, ValueNode *rhs, BasicBlockRef *true_target, BasicBlockRef *false_target)
template<typename FCond , typename FTrue , typename FFalse >
ValueNode * Select (FCond cond, FTrue if_true, FFalse if_false)
template<typename FCond , typename FTrue , typename FFalse >
MaybeReduceResult SelectReduction (FCond cond, FTrue if_true, FFalse if_false)
void MarkBranchDeadAndJumpIfNeeded (bool is_jump_taken)
void CalculatePredecessorCounts ()
compiler::FeedbackVectorRef feedback () const
const FeedbackNexus FeedbackNexusForOperand (int slot_operand_index) const
const FeedbackNexus FeedbackNexusForSlot (FeedbackSlot slot) const
compiler::BytecodeArrayRef bytecode () const
const compiler::BytecodeAnalysis & bytecode_analysis () const
int parameter_count () const
int parameter_count_without_receiver () const
int register_count () const
KnownNodeAspects & known_node_aspects ()
float GetCurrentCallFrequency ()
int argument_count () const
int argument_count_without_receiver () const
bool IsInsideLoop () const
int inline_exit_offset () const
void DecrementDeadPredecessorAndAccountForPeeling (uint32_t offset)
void InitializePredecessorCount (uint32_t offset, int amount)
void UpdatePredecessorCount (uint32_t offset, int diff)
uint32_t predecessor_count (uint32_t offset)
bool in_peeled_iteration () const
bool in_optimistic_peeling_iteration () const
bool is_loop_effect_tracking_enabled ()
bool is_loop_effect_tracking ()
int bailout_for_entrypoint ()
bool CanSpeculateCall () const
bool CanSpeculateCall (std::initializer_list< SpeculationMode > supported_modes) const
void MarkNodeDead (Node *node)
Static Private Member Functions
template<typename NodeT >
static constexpr UseReprHintRecording ShouldRecordUseReprHint ()
static BranchType NegateBranchType (BranchType jump_type)
static size_t fast_hash_combine (size_t seed, size_t h)
template<typename T >
static size_t gvn_hash_value (const T &in)
static size_t gvn_hash_value (const compiler::MapRef &map)
static size_t gvn_hash_value (const interpreter::Register &reg)
static size_t gvn_hash_value (const Representation &rep)
static size_t gvn_hash_value (const ExternalReference &ref)
static size_t gvn_hash_value (const PolymorphicAccessInfo &access_info)
template<typename T >
static size_t gvn_hash_value (const v8::internal::ZoneCompactSet< T > &vector)
template<typename T >
static size_t gvn_hash_value (const v8::internal::ZoneVector< T > &vector)
Private Attributes
LocalIsolate *const local_isolate_
MaglevCompilationUnit *const compilation_unit_
MaglevCallerDetails * caller_details_
compiler::JSHeapBroker * broker_ = compilation_unit_->broker()
Graph *const graph_
compiler::BytecodeAnalysis bytecode_analysis_
interpreter::BytecodeArrayIterator iterator_
SourcePositionTableIterator source_position_iterator_
uint32_t * predecessor_count_
int peeled_iteration_count_ = 0
bool any_peeled_loop_ = false
bool allow_loop_peeling_
LoopEffects * loop_effects_ = nullptr
ZoneDeque< LoopEffects * > loop_effects_stack_
ZoneVector< int > decremented_predecessor_offsets_
BitVector loop_headers_to_peel_
bool in_prologue_ = true
BasicBlock * current_block_ = nullptr
std::optional< InterpretedDeoptFrame > entry_stack_check_frame_
std::optional< DeoptFrame > latest_checkpointed_frame_
SourcePosition current_source_position_
ForInState current_for_in_state = ForInState()
AllocationBlock * current_allocation_block_ = nullptr
BasicBlockRef * jump_targets_
MergePointInterpreterFrameState ** merge_states_
InterpreterFrameState current_interpreter_frame_
compiler::FeedbackSource current_speculation_feedback_
SpeculationMode current_speculation_mode_
ValueNode * inlined_new_target_ = nullptr
bool is_turbolev_ = false
int entrypoint_
int inlining_id_ = SourcePosition::kNotInlined
int next_handler_table_index_ = 0
DeoptFrameScope * current_deopt_scope_ = nullptr
LazyDeoptResultLocationScope * lazy_deopt_result_location_scope_ = nullptr
ZoneStack< HandlerTableEntry > catch_block_stack_
ZoneUnorderedMap< KnownNodeAspects::LoadedContextSlotsKey, Node * > unobserved_context_slot_stores_
Static Private Attributes
static constexpr bool kLoopsMustBeEnteredThroughHeader = true
Detailed Description
Definition at line 202 of file maglev-graph-builder.h.
Member Typedef Documentation
GetDeoptScopeCallback
using v8::internal::maglev::MaglevGraphBuilder::GetDeoptScopeCallback = std::function<DeoptFrameScope(compiler::JSFunctionRef, ValueNode*, ValueNode*, ValueNode*, ValueNode*, ValueNode*, ValueNode*)> [private]
Definition at line 2133 of file maglev-graph-builder.h.
InitialCallback
using v8::internal::maglev::MaglevGraphBuilder::InitialCallback = std::function<ReduceResult(ValueNode*)> [private]
Definition at line 2131 of file maglev-graph-builder.h.
ProcessElementCallback
using v8::internal::maglev::MaglevGraphBuilder::ProcessElementCallback = std::function<void(ValueNode*, ValueNode*)> [private]
Definition at line 2132 of file maglev-graph-builder.h.
TypeOfLiteralFlag
using v8::internal::maglev::MaglevGraphBuilder::TypeOfLiteralFlag = interpreter::TestTypeOfFlags::LiteralFlag [private]
Definition at line 2820 of file maglev-graph-builder.h.
Member Enumeration Documentation
BranchResult
enum v8::internal::maglev::MaglevGraphBuilder::BranchResult [strong], [private]
Enumerator
kDefault
kAlwaysTrue
kAlwaysFalse
Definition at line 2843 of file maglev-graph-builder.h.
                          {
    kDefault,
    kAlwaysTrue,
    kAlwaysFalse,
  };
BranchSpecializationMode
enum v8::internal::maglev::MaglevGraphBuilder::BranchSpecializationMode [strong], [private]
Enumerator
kDefault
kAlwaysBoolean
Definition at line 2842 of file maglev-graph-builder.h.
{ kDefault, kAlwaysBoolean };
BranchType
enum v8::internal::maglev::MaglevGraphBuilder::BranchType [strong], [private]
Enumerator
kBranchIfTrue
kBranchIfFalse
Definition at line 2841 of file maglev-graph-builder.h.
{ kBranchIfTrue, kBranchIfFalse };
ContextSlotMutability
enum v8::internal::maglev::MaglevGraphBuilder::ContextSlotMutability [private]
Enumerator
kImmutable
kMutable
Definition at line 1294 of file maglev-graph-builder.h.
{ kImmutable, kMutable };
InferHasInPrototypeChainResult
enum v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChainResult [private]
Enumerator
kMayBeInPrototypeChain
kIsInPrototypeChain
kIsNotInPrototypeChain
Definition at line 2615 of file maglev-graph-builder.h.
                                      {
    kMayBeInPrototypeChain,
    kIsInPrototypeChain,
    kIsNotInPrototypeChain
  };
StringAtOOBMode
enum v8::internal::maglev::MaglevGraphBuilder::StringAtOOBMode [strong], [private]
Enumerator
kElement
kCharAt
Definition at line 2152 of file maglev-graph-builder.h.
{ kElement, kCharAt };
TrackObjectMode
enum v8::internal::maglev::MaglevGraphBuilder::TrackObjectMode [strong], [private]
Enumerator
kLoad
kStore
Definition at line 2390 of file maglev-graph-builder.h.
{ kLoad, kStore };
Constructor & Destructor Documentation
MaglevGraphBuilder()
v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder (LocalIsolate * local_isolate, MaglevCompilationUnit * compilation_unit, Graph * graph, MaglevCallerDetails * caller_details = nullptr) [explicit]
Definition at line 951 of file maglev-graph-builder.cc.
    : local_isolate_(local_isolate),
      compilation_unit_(compilation_unit),
      caller_details_(caller_details),
      graph_(graph),
      bytecode_analysis_(bytecode().object(), zone(),
                         compilation_unit->osr_offset(), true),
      iterator_(bytecode().object()),
      source_position_iterator_(bytecode().SourcePositionTable(broker())),
      allow_loop_peeling_(v8_flags.maglev_loop_peeling),
      loop_effects_stack_(zone()),
      decremented_predecessor_offsets_(zone()),
      loop_headers_to_peel_(bytecode().length(), zone()),
      current_source_position_(),
      // Add an extra jump_target slot for the inline exit if needed.
      jump_targets_(zone()->AllocateArray<BasicBlockRef>(
          bytecode().length() + (is_inline() ? 1 : 0))),
      // Overallocate merge_states_ by one to allow always looking up the
      // next offset. This overallocated slot can also be used for the inline
      // exit when needed.
      merge_states_(zone()->AllocateArray<MergePointInterpreterFrameState*>(
          bytecode().length() + 1)),
      current_interpreter_frame_(
          *compilation_unit_,
          is_inline() ? caller_details->known_node_aspects
                      : compilation_unit_->zone()->New<KnownNodeAspects>(
                            compilation_unit_->zone()),
          is_inline() ? caller_details->deopt_frame->GetVirtualObjects()
                      : VirtualObjectList()),
      is_turbolev_(compilation_unit->info()->is_turbolev()),
      entrypoint_(compilation_unit->is_osr()
                      ? bytecode_analysis_.osr_entry_point()
                      : 0),
      catch_block_stack_(zone()),
      unobserved_context_slot_stores_(zone()) {
  memset(merge_states_, 0,
         (bytecode().length() + 1) * sizeof(InterpreterFrameState*));
  // Default construct basic block refs.
  // TODO(leszeks): This could be a memset of nullptr to ..._jump_targets_.
  for (int i = 0; i < bytecode().length(); ++i) {
    new (&jump_targets_[i]) BasicBlockRef();
  }
  if (is_inline()) {
    DCHECK_NOT_NULL(caller_details);
    DCHECK_GT(compilation_unit->inlining_depth(), 0);
    // The allocation/initialisation logic here relies on inline_exit_offset
    // being the offset one past the end of the bytecode.
    DCHECK_EQ(inline_exit_offset(), bytecode().length());
    merge_states_[inline_exit_offset()] = nullptr;
    new (&jump_targets_[inline_exit_offset()]) BasicBlockRef();
    if (caller_details->loop_effects) {
      loop_effects_ = caller_details->loop_effects;
      loop_effects_stack_.push_back(loop_effects_);
    }
    unobserved_context_slot_stores_ =
        caller_details->unobserved_context_slot_stores;
  }
  CHECK_IMPLIES(compilation_unit_->is_osr(), graph_->is_osr());
  CHECK_EQ(compilation_unit_->info()->toplevel_osr_offset() !=
               BytecodeOffset::None(),
           graph_->is_osr());
  if (compilation_unit_->is_osr()) {
    CHECK(!is_inline());
    // Make sure that we're at a valid OSR entrypoint.
    //
    // This is also a defense-in-depth check to make sure that we're not
    // compiling invalid bytecode if the OSR offset is wrong (e.g. because it
    // belongs to different bytecode).
    //
    // OSR'ing into the middle of a loop is currently not supported. There
    // should not be any issue with OSR'ing outside of loops, just we currently
    // dont do it...
    interpreter::BytecodeArrayIterator it(bytecode().object());
    it.AdvanceTo(compilation_unit_->osr_offset().ToInt());
    CHECK(it.CurrentBytecodeIsValidOSREntry());
    CHECK_EQ(entrypoint_, it.GetJumpTargetOffset());
    iterator_.AdvanceTo(entrypoint_);
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << "- Non-standard entrypoint @" << entrypoint_
                << " by OSR from @" << compilation_unit_->osr_offset().ToInt()
                << std::endl;
    }
  }
  CHECK_IMPLIES(!compilation_unit_->is_osr(), entrypoint_ == 0);
  CalculatePredecessorCounts();
}
References v8::internal::interpreter::BytecodeArrayIterator::AdvanceTo(), bytecode(), CalculatePredecessorCounts(), caller_details(), CHECK, CHECK_EQ, CHECK_IMPLIES, compilation_unit(), compilation_unit_, v8::internal::interpreter::BytecodeArrayIterator::CurrentBytecodeIsValidOSREntry(), DCHECK_EQ, DCHECK_GT, DCHECK_NOT_NULL, entrypoint_, v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::MaglevCompilationUnit::info(), inline_exit_offset(), v8::internal::maglev::MaglevCompilationUnit::inlining_depth(), is_inline(), v8::internal::maglev::MaglevCompilationUnit::is_osr(), v8::internal::maglev::Graph::is_osr(), iterator_, jump_targets_, v8::internal::length, v8::internal::compiler::BytecodeArrayRef::length(), v8::internal::maglev::MaglevCallerDetails::loop_effects, loop_effects_, loop_effects_stack_, merge_states_, v8::internal::BytecodeOffset::None(), v8::internal::maglev::MaglevCompilationUnit::osr_offset(), v8::internal::BytecodeOffset::ToInt(), v8::internal::maglev::MaglevCompilationInfo::toplevel_osr_offset(), v8::internal::maglev::MaglevCallerDetails::unobserved_context_slot_stores, unobserved_context_slot_stores_, and v8::internal::v8_flags.
Member Function Documentation
AddDeoptUse() [1/2]
void v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse (ValueNode * node) [inline], [private]
Definition at line 2687 of file maglev-graph-builder.h.
                                           {
    if (node == nullptr) return;
    DCHECK(!node->Is<VirtualObject>());
    if (InlinedAllocation* alloc = node->TryCast<InlinedAllocation>()) {
      VirtualObject* vobject =
          current_interpreter_frame_.virtual_objects().FindAllocatedWith(alloc);
      if (vobject) {
        CHECK_NOT_NULL(vobject);
        AddDeoptUse(vobject);
        // Add an escaping use for the allocation.
        AddNonEscapingUses(alloc, 1);
      } else {
        DCHECK(alloc->is_returned_value_from_inline_call());
      }
      alloc->add_use();
    } else {
      node->add_use();
    }
  }
References v8::internal::maglev::ValueNode::add_use(), CHECK_NOT_NULL, DCHECK, v8::internal::maglev::NodeBase::Is(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by AddInlinedArgumentsToDeoptFrame(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), and GetLatestCheckpointedFrame().
AddDeoptUse() [2/2]
void v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse (VirtualObject * alloc) [private]
Definition at line 13672 of file maglev-graph-builder.cc.
                                                           {
  vobject->ForEachInput([&](ValueNode* value) {
    if (InlinedAllocation* nested_allocation =
            value->TryCast<InlinedAllocation>()) {
      VirtualObject* nested_object =
          current_interpreter_frame_.virtual_objects().FindAllocatedWith(
              nested_allocation);
      CHECK_NOT_NULL(nested_object);
      AddDeoptUse(nested_object);
    } else if (!IsConstantNode(value->opcode()) &&
               value->opcode() != Opcode::kArgumentsElements &&
               value->opcode() != Opcode::kArgumentsLength &&
               value->opcode() != Opcode::kRestLength) {
      AddDeoptUse(value);
    }
  });
}
References v8::internal::maglev::VirtualObject::ForEachInput(), v8::internal::if(), v8::internal::maglev::IsConstantNode(), and v8::internal::value.
AddInitializedNodeToGraph()
void v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph (Node * node) [inline], [private]
Definition at line 978 of file maglev-graph-builder.h.
                                             {
    // VirtualObjects should never be add to the Maglev graph.
    DCHECK(!node->Is<VirtualObject>());
    node_buffer().push_back(node);
    node->set_owner(current_block_);
    if (has_graph_labeller())
      graph_labeller()->RegisterNode(node, compilation_unit_,
                                     BytecodeOffset(iterator_.current_offset()),
                                     current_source_position_);
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " " << node << " "
                << PrintNodeLabel(graph_labeller(), node) << ": "
                << PrintNode(graph_labeller(), node) << std::endl;
    }
#ifdef DEBUG
    new_nodes_.insert(node);
#endif
  }
References compilation_unit_, current_block_, v8::internal::interpreter::BytecodeArrayIterator::current_offset(), current_source_position_, v8::internal::DCHECK(), graph_labeller(), has_graph_labeller(), v8::internal::maglev::NodeBase::Is(), iterator_, node_buffer(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), v8::internal::maglev::NodeBase::set_owner(), and v8::internal::v8_flags.
Referenced by AttachExtraInfoAndAddToGraph(), and Build().
AddInlinedArgumentsToDeoptFrame()
DeoptFrame * v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame (DeoptFrame * deopt_frame, const MaglevCompilationUnit * unit, ValueNode * closure, base::Vector< ValueNode * > args)
Definition at line 1324 of file maglev-graph-builder.cc.
                                                     {
  // Only create InlinedArgumentsDeoptFrame if we have a mismatch between
  // formal parameter and arguments count.
  if (static_cast<int>(args.size()) != unit->parameter_count()) {
    deopt_frame = zone()->New<InlinedArgumentsDeoptFrame>(
        *unit, BytecodeOffset(iterator_.current_offset()), closure, args,
        deopt_frame);
    AddDeoptUse(closure);
    for (ValueNode* arg : deopt_frame->as_inlined_arguments().arguments()) {
      AddDeoptUse(arg);
    }
  }
  return deopt_frame;
}
References AddDeoptUse(), v8::base::args, v8::internal::maglev::InlinedArgumentsDeoptFrame::arguments(), v8::internal::maglev::DeoptFrame::as_inlined_arguments(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), iterator_, v8::internal::Zone::New(), v8::internal::maglev::MaglevCompilationUnit::parameter_count(), and zone().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), and GetDeoptFrameForEagerCall().
AddNewCallNode()
template<typename CallNode , typename... Args>
CallNode * v8::internal::maglev::MaglevGraphBuilder::AddNewCallNode (const CallArguments & args, Args &&... extra_args) [private]
Definition at line 10908 of file maglev-graph-builder.cc.
                                                                   {
  size_t input_count = args.count_with_receiver() + CallNode::kFixedInputCount;
  return AddNewNode<CallNode>(
      input_count,
      [&](CallNode* call) {
        int arg_index = 0;
        call->set_arg(arg_index++,
                      GetTaggedValue(GetValueOrUndefined(args.receiver())));
        for (size_t i = 0; i < args.count(); ++i) {
          call->set_arg(arg_index++, GetTaggedValue(args[i]));
        }
      },
      std::forward<Args>(extra_args)...);
}
References v8::base::args, v8::internal::anonymous_namespace{json-stringifier.cc}::for(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::turboshaft::detail::input_count().
AddNewNode() [1/2]
template<typename NodeT , typename Function , typename... Args>
NodeT* v8::internal::maglev::MaglevGraphBuilder::AddNewNode (size_t input_count, Function && post_create_input_initializer, Args &&... args) [inline], [private]
Definition at line 1001 of file maglev-graph-builder.h.
                                                                              {
    NodeT* node =
        NodeBase::New<NodeT>(zone(), input_count, std::forward<Args>(args)...);
    post_create_input_initializer(node);
    return AttachExtraInfoAndAddToGraph(node);
  }
References v8::base::args, AttachExtraInfoAndAddToGraph(), v8::internal::compiler::turboshaft::detail::input_count(), and zone().
Referenced by BuildFloat64BinaryOperationNodeForToNumber(), BuildFloat64BinarySmiOperationNodeForToNumber(), BuildGenericBinaryOperationNode(), BuildGenericBinarySmiOperationNode(), BuildGenericUnaryOperationNode(), BuildTruncatingInt32BinaryOperationNodeForToNumber(), and BuildTruncatingInt32BinarySmiOperationNodeForToNumber().
AddNewNode() [2/2]
template<typename NodeT , typename... Args>
NodeT* v8::internal::maglev::MaglevGraphBuilder::AddNewNode (std::initializer_list< ValueNode * > inputs, Args &&... args) [inline], [private]
Definition at line 1109 of file maglev-graph-builder.h.
                                                                            {
    static_assert(IsFixedInputNode<NodeT>());
    if constexpr (Node::participate_in_cse(Node::opcode_of<NodeT>)) {
      if (v8_flags.maglev_cse) {
        return AddNewNodeOrGetEquivalent<NodeT>(inputs,
                                                std::forward<Args>(args)...);
      }
    }
    NodeT* node = NodeBase::New<NodeT>(zone(), inputs.size(),
                                       std::forward<Args>(args)...);
    SetNodeInputs(node, inputs);
    return AttachExtraInfoAndAddToGraph(node);
  }
References v8::base::args, AttachExtraInfoAndAddToGraph(), v8::internal::maglev::Node::participate_in_cse(), SetNodeInputs(), v8::internal::v8_flags, and zone().
AddNewNodeOrGetEquivalent()
template<typename NodeT , typename... Args>
NodeT* v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent (std::initializer_list< ValueNode * > raw_inputs, Args &&... args) [inline], [private]
Definition at line 1010 of file maglev-graph-builder.h.
                                                   {
    DCHECK(v8_flags.maglev_cse);
    static constexpr Opcode op = Node::opcode_of<NodeT>;
    static_assert(Node::participate_in_cse(op));
    using options_result =
        std::invoke_result_t<decltype(&NodeT::options), const NodeT>;
    static_assert(std::is_assignable_v<options_result, std::tuple<Args...>>,
                  "Instruction participating in CSE needs options() returning "
                  "a tuple matching the constructor arguments");
    static_assert(IsFixedInputNode<NodeT>());
    static_assert(NodeT::kInputCount <= 3);
    std::array<ValueNode*, NodeT::kInputCount> inputs;
    // Nodes with zero input count don't have kInputTypes defined.
    if constexpr (NodeT::kInputCount > 0) {
      int i = 0;
      constexpr UseReprHintRecording hint = ShouldRecordUseReprHint<NodeT>();
      for (ValueNode* raw_input : raw_inputs) {
        // TODO(marja): Here we might already have the empty type for the
        // node. Generate a deopt and make callers handle it.
        inputs[i] = ConvertInputTo<hint>(raw_input, NodeT::kInputTypes[i]);
        i++;
      }
      if constexpr (IsCommutativeNode(Node::opcode_of<NodeT>)) {
        static_assert(NodeT::kInputCount == 2);
        if ((IsConstantNode(inputs[0]->opcode()) || inputs[0] > inputs[1]) &&
            !IsConstantNode(inputs[1]->opcode())) {
          std::swap(inputs[0], inputs[1]);
        }
      }
    }
    uint32_t value_number;
    {
      size_t tmp_value_number = base::hash_value(op);
      (
          [&] {
            tmp_value_number =
                fast_hash_combine(tmp_value_number, gvn_hash_value(args));
          }(),
          ...);
      for (const auto& inp : inputs) {
        tmp_value_number =
            fast_hash_combine(tmp_value_number, base::hash_value(inp));
      }
      value_number = static_cast<uint32_t>(tmp_value_number);
    }
    auto exists = known_node_aspects().available_expressions.find(value_number);
    if (exists != known_node_aspects().available_expressions.end()) {
      auto candidate = exists->second.node;
      const bool sanity_check =
          candidate->Is<NodeT>() &&
          static_cast<size_t>(candidate->input_count()) == inputs.size();
      DCHECK_IMPLIES(sanity_check,
                     (StaticPropertiesForOpcode(op) &
                      candidate->properties()) == candidate->properties());
      const bool epoch_check =
          !Node::needs_epoch_check(op) ||
          known_node_aspects().effect_epoch() <= exists->second.effect_epoch;
      if (sanity_check && epoch_check) {
        if (static_cast<NodeT*>(candidate)->options() ==
            std::tuple{std::forward<Args>(args)...}) {
          int i = 0;
          for (const auto& inp : inputs) {
            if (inp != candidate->input(i).node()) {
              break;
            }
            i++;
          }
          if (static_cast<size_t>(i) == inputs.size()) {
            return static_cast<NodeT*>(candidate);
          }
        }
      }
      if (!epoch_check) {
        known_node_aspects().available_expressions.erase(exists);
      }
    }
    NodeT* node = NodeBase::New<NodeT>(zone(), inputs.size(),
                                       std::forward<Args>(args)...);
    int i = 0;
    for (ValueNode* input : inputs) {
      DCHECK_NOT_NULL(input);
      node->set_input(i++, input);
    }
    DCHECK_EQ(node->options(), std::tuple{std::forward<Args>(args)...});
    uint32_t epoch = Node::needs_epoch_check(op)
                         ? known_node_aspects().effect_epoch()
                         : KnownNodeAspects::kEffectEpochForPureInstructions;
    if (epoch != KnownNodeAspects::kEffectEpochOverflow) {
      known_node_aspects().available_expressions[value_number] = {node, epoch};
    }
    return AttachExtraInfoAndAddToGraph(node);
  }
References v8::base::args, AttachExtraInfoAndAddToGraph(), v8::internal::maglev::KnownNodeAspects::available_expressions, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::maglev::KnownNodeAspects::effect_epoch(), fast_hash_combine(), gvn_hash_value(), v8::base::hash_value(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::IsCommutativeNode(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::KnownNodeAspects::kEffectEpochForPureInstructions, v8::internal::maglev::KnownNodeAspects::kEffectEpochOverflow, known_node_aspects(), v8::internal::maglev::Node::needs_epoch_check(), v8::internal::maglev::Node::participate_in_cse(), v8::internal::maglev::StaticPropertiesForOpcode(), v8::internal::v8_flags, and zone().
AddNonEscapingUses()
void v8::internal::maglev::MaglevGraphBuilder::AddNonEscapingUses (InlinedAllocation * allocation, int use_count) [private]
Definition at line 13666 of file maglev-graph-builder.cc.
                                                           {
  if (!v8_flags.maglev_escape_analysis) return;
  allocation->AddNonEscapingUses(use_count);
}
References v8::internal::maglev::InlinedAllocation::AddNonEscapingUses(), and v8::internal::v8_flags.
Referenced by TryBuildStoreTaggedFieldToAllocation().
argument_count()
int v8::internal::maglev::MaglevGraphBuilder::argument_count () const [inline], [private]
Definition at line 3139 of file maglev-graph-builder.h.
                             {
    DCHECK(is_inline());
    return static_cast<int>(caller_details_->arguments.size());
  }
References DCHECK.
Referenced by GetInlinedArgument().
argument_count_without_receiver()
int v8::internal::maglev::MaglevGraphBuilder::argument_count_without_receiver () const [inline], [private]
Definition at line 3143 of file maglev-graph-builder.h.
{ return argument_count() - 1; }
AttachDeoptCheckpoint()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::AttachDeoptCheckpoint (NodeT * node) [inline], [private]
Definition at line 1156 of file maglev-graph-builder.h.
                                          {
    if constexpr (NodeT::kProperties.is_deopt_checkpoint()) {
      node->SetEagerDeoptInfo(zone(), GetLatestCheckpointedFrame());
    }
  }
References GetLatestCheckpointedFrame(), and zone().
Referenced by AttachExtraInfoAndAddToGraph().
AttachEagerDeoptInfo()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::AttachEagerDeoptInfo (NodeT * node) [inline], [private]
Definition at line 1163 of file maglev-graph-builder.h.
                                         {
    if constexpr (NodeT::kProperties.can_eager_deopt()) {
      node->SetEagerDeoptInfo(zone(), GetLatestCheckpointedFrame(),
                              current_speculation_feedback_);
    }
  }
References current_speculation_feedback_, GetLatestCheckpointedFrame(), and zone().
Referenced by AttachExtraInfoAndAddToGraph().
AttachExceptionHandlerInfo()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::AttachExceptionHandlerInfo (NodeT * node) [inline], [private]
Definition at line 1188 of file maglev-graph-builder.h.
                                               {
    if constexpr (NodeT::kProperties.can_throw()) {
      CatchBlockDetails catch_block = GetCurrentTryCatchBlock();
      if (catch_block.ref) {
        if (!catch_block.exception_handler_was_used) {
          // Attach an empty live exception handler to mark that there's a
          // matching catch but we'll lazy deopt if we ever throw.
          new (node->exception_handler_info())
              ExceptionHandlerInfo(ExceptionHandlerInfo::kLazyDeopt);
          DCHECK(node->exception_handler_info()->HasExceptionHandler());
          DCHECK(node->exception_handler_info()->ShouldLazyDeopt());
          if constexpr (std ::is_same_v<NodeT, CallKnownJSFunction>) {
            if (is_non_eager_inlining_enabled()) {
              // Ensure that we always have the handler of inline call
              // candidates.
              current_block_->AddExceptionHandler(
                  node->exception_handler_info());
            }
          }
          return;
        }
        DCHECK_IMPLIES(!IsInsideTryBlock(), is_inline());
        if (catch_block.block_already_exists) {
          DCHECK(!IsInsideTryBlock());
          // If we are inlining a function non-eagerly and we are not inside a
          // try block, then the catch block already exists.
          new (node->exception_handler_info()) ExceptionHandlerInfo(
              catch_block.ref->block_ptr(), catch_block.deopt_frame_distance);
        } else {
          // If we are inside a try block for the current builder or if we are
          // inside an eager inlined call inside a try block, the catch basic
          // block doesn't exist yet, use the ref-list mechanism.
          new (node->exception_handler_info()) ExceptionHandlerInfo(
              catch_block.ref, catch_block.deopt_frame_distance);
        }
        DCHECK(node->exception_handler_info()->HasExceptionHandler());
        DCHECK(!node->exception_handler_info()->ShouldLazyDeopt());
        current_block_->AddExceptionHandler(node->exception_handler_info());
        if (IsInsideTryBlock()) {
          // Merge the current state into the handler state.
          auto state = GetCatchBlockFrameState();
          DCHECK_NOT_NULL(state);
          state->MergeThrow(this, compilation_unit_,
                            *current_interpreter_frame_.known_node_aspects(),
                            current_interpreter_frame_.virtual_objects());
        }
      } else {
        // Patch no exception handler marker.
        // TODO(victorgomes): Avoid allocating exception handler data in this
        // case.
        new (node->exception_handler_info()) ExceptionHandlerInfo();
        DCHECK(!node->exception_handler_info()->HasExceptionHandler());
        if constexpr (std ::is_same_v<NodeT, CallKnownJSFunction>) {
          if (is_non_eager_inlining_enabled()) {
            // Ensure that we always have the handler of inline call candidates.
            current_block_->AddExceptionHandler(node->exception_handler_info());
          }
        }
      }
    }
  }
References v8::internal::maglev::BasicBlock::AddExceptionHandler(), v8::internal::maglev::CatchBlockDetails::block_already_exists, v8::internal::maglev::BasicBlockRef::block_ptr(), compilation_unit_, current_block_, current_interpreter_frame_, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::maglev::CatchBlockDetails::deopt_frame_distance, v8::internal::maglev::CatchBlockDetails::exception_handler_was_used, GetCatchBlockFrameState(), GetCurrentTryCatchBlock(), is_inline(), is_non_eager_inlining_enabled(), IsInsideTryBlock(), v8::internal::maglev::ExceptionHandlerInfo::kLazyDeopt, v8::internal::maglev::InterpreterFrameState::known_node_aspects(), v8::internal::maglev::CatchBlockDetails::ref, and v8::internal::maglev::InterpreterFrameState::virtual_objects().
Referenced by AttachExtraInfoAndAddToGraph().
AttachExtraInfoAndAddToGraph()
template<typename NodeT >
NodeT* v8::internal::maglev::MaglevGraphBuilder::AttachExtraInfoAndAddToGraph (NodeT * node) [inline], [private]
Definition at line 1141 of file maglev-graph-builder.h.
                                                   {
    static_assert(NodeT::kProperties.is_deopt_checkpoint() +
                      NodeT::kProperties.can_eager_deopt() +
                      NodeT::kProperties.can_lazy_deopt() <=
                  1);
    AttachDeoptCheckpoint(node);
    AttachEagerDeoptInfo(node);
    AttachLazyDeoptInfo(node);
    AttachExceptionHandlerInfo(node);
    AddInitializedNodeToGraph(node);
    MarkPossibleSideEffect(node);
    return node;
  }
References AddInitializedNodeToGraph(), AttachDeoptCheckpoint(), AttachEagerDeoptInfo(), AttachExceptionHandlerInfo(), AttachLazyDeoptInfo(), and MarkPossibleSideEffect().
Referenced by AddNewNode(), and AddNewNodeOrGetEquivalent().
AttachLazyDeoptInfo()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::AttachLazyDeoptInfo (NodeT * node) [inline], [private]
Definition at line 1171 of file maglev-graph-builder.h.
                                        {
    if constexpr (NodeT::kProperties.can_lazy_deopt()) {
      interpreter::Register result_location;
      int result_size;
      if (lazy_deopt_result_location_scope_) {
        result_location = lazy_deopt_result_location_scope_->result_location();
        result_size = lazy_deopt_result_location_scope_->result_size();
      } else {
        std::tie(result_location, result_size) = GetResultLocationAndSize();
      }
      new (node->lazy_deopt_info()) LazyDeoptInfo(
          zone(), GetDeoptFrameForLazyDeopt(result_location, result_size),
          result_location, result_size, current_speculation_feedback_);
    }
  }
References current_speculation_feedback_, GetDeoptFrameForLazyDeopt(), GetResultLocationAndSize(), lazy_deopt_result_location_scope_, v8::internal::maglev::MaglevGraphBuilder::LazyDeoptResultLocationScope::result_location(), v8::internal::maglev::MaglevGraphBuilder::LazyDeoptResultLocationScope::result_size(), and zone().
Referenced by AttachExtraInfoAndAddToGraph().
bailout_for_entrypoint()
int v8::internal::maglev::MaglevGraphBuilder::bailout_for_entrypoint () [inline], [private]
Definition at line 3287 of file maglev-graph-builder.h.
                               {
    if (!graph_->is_osr()) return kFunctionEntryBytecodeOffset;
    return bytecode_analysis_.osr_bailout_id().ToInt();
  }
References v8::internal::maglev::Graph::is_osr(), v8::internal::kFunctionEntryBytecodeOffset, v8::internal::compiler::BytecodeAnalysis::osr_bailout_id(), and v8::internal::BytecodeOffset::ToInt().
Referenced by GetDeoptFrameForEntryStackCheck().
BeginLoopEffects()
void v8::internal::maglev::MaglevGraphBuilder::BeginLoopEffects (int loop_header) [private]
Definition at line 14428 of file maglev-graph-builder.cc.
                                                         {
  loop_effects_stack_.push_back(zone()->New<LoopEffects>(loop_header, zone()));
  loop_effects_ = loop_effects_stack_.back();
}
Referenced by VisitSingleBytecode().
broker()
compiler::JSHeapBroker* v8::internal::maglev::MaglevGraphBuilder::broker () const [inline]
Definition at line 366 of file maglev-graph-builder.h.
{ return broker_; }
References broker_.
Referenced by Build(), BuildCheckMaps(), BuildCheckSmi(), BuildCompareMaps(), BuildLoadField(), BuildLoadFixedArrayElement(), BuildLoadJSArrayLength(), BuildLoadJSFunctionContext(), BuildLoadJSFunctionFeedbackCell(), BuildNewConsStringMap(), BuildRegisterFrameInitialization(), BuildStoreMap(), BuildTestUndetectable(), BuildTransitionElementsKindAndCompareMaps(), BuildTransitionElementsKindOrCheckMap(), CanTreatHoleAsUndefined(), CheckContextExtensions(), CheckType(), CheckTypes(), EnsureType(), GetOrCreateInfoFor(), GetType(), HasDisjointType(), HaveDisjointTypes(), LoadAndCacheContextSlot(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoopValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), SetKnownValue(), StoreAndCacheContextSlot(), StringLengthStaticLowerBound(), TryBuildNamedAccess(), TryBuildPropertyCellLoad(), TryBuildPropertyCellStore(), TryBuildPropertyGetterCall(), TryBuildPropertyLoad(), TryBuildPropertyStore(), TryBuildScriptContextConstantLoad(), TryBuildStoreField(), TryFoldLoadConstantDataField(), TryFoldLoadConstantDoubleField(), TryFoldLoadDictPrototypeConstant(), TryGetConstant(), v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop(), TryReduceCompareEqualAgainstConstant(), TrySpecializeLoadContextSlot(), TrySpecializeLoadContextSlotToFunctionContext(), TrySpecializeStoreContextSlot(), and VisitBinaryOperation().
Build()
void v8::internal::maglev::MaglevGraphBuilder::Build () [inline]
Definition at line 229 of file maglev-graph-builder.h.
               {
    DCHECK(!is_inline());
    DCHECK_EQ(inlining_id_, SourcePosition::kNotInlined);
    current_source_position_ = SourcePosition(
        compilation_unit_->shared_function_info().StartPosition(),
        inlining_id_);
    StartPrologue();
    for (int i = 0; i < parameter_count(); i++) {
      // TODO(v8:7700): Consider creating InitialValue nodes lazily.
      InitialValue* v = AddNewNode<InitialValue>(
          {}, interpreter::Register::FromParameterIndex(i));
      DCHECK_EQ(graph()->parameters().size(), static_cast<size_t>(i));
      graph()->parameters().push_back(v);
      SetArgument(i, v);
    }
    BuildRegisterFrameInitialization();
    // Don't use the AddNewNode helper for the function entry stack check, so
    // that we can set a custom deopt frame on it.
    FunctionEntryStackCheck* function_entry_stack_check =
        NodeBase::New<FunctionEntryStackCheck>(zone(), 0);
    new (function_entry_stack_check->lazy_deopt_info()) LazyDeoptInfo(
        zone(), GetDeoptFrameForEntryStackCheck(),
        interpreter::Register::invalid_value(), 0, compiler::FeedbackSource());
    AddInitializedNodeToGraph(function_entry_stack_check);
    BuildMergeStates();
    EndPrologue();
    in_prologue_ = false;
    compiler::ScopeInfoRef scope_info =
        compilation_unit_->shared_function_info().scope_info(broker());
    if (scope_info.HasOuterScopeInfo()) {
      scope_info = scope_info.OuterScopeInfo(broker());
      CHECK(scope_info.HasContext());
      graph()->record_scope_info(GetContext(), scope_info);
    }
    if (compilation_unit_->is_osr()) {
      OsrAnalyzePrequel();
    }
    BuildBody();
  }
References AddInitializedNodeToGraph(), broker(), BuildBody(), BuildMergeStates(), BuildRegisterFrameInitialization(), CHECK, compilation_unit_, current_source_position_, v8::internal::DCHECK(), DCHECK_EQ, EndPrologue(), v8::internal::interpreter::Register::FromParameterIndex(), GetContext(), GetDeoptFrameForEntryStackCheck(), graph(), v8::internal::compiler::ScopeInfoRef::HasContext(), v8::internal::compiler::ScopeInfoRef::HasOuterScopeInfo(), in_prologue_, inlining_id_, v8::internal::interpreter::Register::invalid_value(), is_inline(), v8::internal::maglev::MaglevCompilationUnit::is_osr(), v8::internal::SourcePosition::kNotInlined, OsrAnalyzePrequel(), v8::internal::compiler::ScopeInfoRef::OuterScopeInfo(), parameter_count(), v8::internal::maglev::Graph::parameters(), v8::internal::maglev::Graph::record_scope_info(), v8::internal::compiler::SharedFunctionInfoRef::scope_info(), SetArgument(), v8::internal::maglev::MaglevCompilationUnit::shared_function_info(), size(), StartPrologue(), and zone().
Referenced by v8::internal::maglev::MaglevCompiler::Compile().
BuildAbort()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildAbort (AbortReason reason) [inline], [private]
Definition at line 1422 of file maglev-graph-builder.h.
                                              {
    // Create a block rather than calling finish, since we don't yet know the
    // next block's offset before the loop skipping the rest of the bytecodes.
    FinishBlock<Abort>({}, reason);
    return ReduceResult::DoneWithAbort();
  }
BuildAndAllocateArgumentsObject()
template<CreateArgumentsType type>
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateArgumentsObject [private]
Definition at line 13968 of file maglev-graph-builder.cc.
                                                               {
  auto arguments = BuildVirtualArgumentsObject<type>();
  ValueNode* allocation =
      BuildInlinedAllocation(arguments, AllocationType::kYoung);
  return allocation;
}
References v8::internal::kYoung.
BuildAndAllocateJSArray()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArray (compiler::MapRef map, ValueNode * length, ValueNode * elements, const compiler::SlackTrackingPrediction & slack_tracking_prediction, AllocationType allocation_type) [private]
Definition at line 12105 of file maglev-graph-builder.cc.
                                    {
  VirtualObject* array;
  GET_VALUE_OR_ABORT(
      array,
      CreateJSArray(map, slack_tracking_prediction.instance_size(), length));
  array->set(JSArray::kElementsOffset, elements);
  for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
       i++) {
    array->set(map.GetInObjectPropertyOffset(i),
               GetRootConstant(RootIndex::kUndefinedValue));
  }
  array->ClearSlots(map.GetInObjectPropertyOffset(
                        slack_tracking_prediction.inobject_property_count()),
                    GetRootConstant(RootIndex::kOnePointerFillerMap));
  ValueNode* allocation = BuildInlinedAllocation(array, allocation_type);
  return allocation;
}
References v8::internal::maglev::VirtualObject::ClearSlots(), GET_VALUE_OR_ABORT, v8::internal::compiler::MapRef::GetInObjectPropertyOffset(), v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::length, and v8::internal::maglev::VirtualObject::set().
BuildAndAllocateJSArrayIterator()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArrayIterator (ValueNode * array, IterationKind iteration_kind) [private]
Definition at line 12126 of file maglev-graph-builder.cc.
                                                    {
  compiler::MapRef map =
      broker()->target_native_context().initial_array_iterator_map(broker());
  VirtualObject* iterator = CreateJSArrayIterator(map, array, iteration_kind);
  ValueNode* allocation =
      BuildInlinedAllocation(iterator, AllocationType::kYoung);
  return allocation;
}
References broker(), and v8::internal::kYoung.
BuildAndAllocateKeyValueArray()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateKeyValueArray (ValueNode * key, ValueNode * value) [private]
Definition at line 12090 of file maglev-graph-builder.cc.
                                      {
  VirtualObject* elements = CreateFixedArray(broker()->fixed_array_map(), 2);
  elements->set(FixedArray::OffsetOfElementAt(0), key);
  elements->set(FixedArray::OffsetOfElementAt(1), value);
  compiler::MapRef map =
      broker()->target_native_context().js_array_packed_elements_map(broker());
  VirtualObject* array;
  GET_VALUE_OR_ABORT(
      array, CreateJSArray(map, map.instance_size(), GetInt32Constant(2)));
  array->set(JSArray::kElementsOffset, elements);
  ValueNode* allocation = BuildInlinedAllocation(array, AllocationType::kYoung);
  return allocation;
}
References broker(), GET_VALUE_OR_ABORT, v8::internal::compiler::MapRef::instance_size(), v8::internal::key, v8::internal::kYoung, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::maglev::VirtualObject::set(), and v8::internal::value.
BuildBody()
void v8::internal::maglev::MaglevGraphBuilder::BuildBody () [inline]
Definition at line 295 of file maglev-graph-builder.h.
                   {
    while (!source_position_iterator_.done() &&
           source_position_iterator_.code_offset() < entrypoint_) {
      current_source_position_ = SourcePosition(
          source_position_iterator_.source_position().ScriptOffset(),
          inlining_id_);
      source_position_iterator_.Advance();
    }
    for (iterator_.SetOffset(entrypoint_); !iterator_.done();
         iterator_.Advance()) {
      local_isolate_->heap()->Safepoint();
      if (V8_UNLIKELY(
              loop_headers_to_peel_.Contains(iterator_.current_offset()))) {
        PeelLoop();
        DCHECK_EQ(iterator_.current_bytecode(),
                  interpreter::Bytecode::kJumpLoop);
        continue;
      }
      VisitSingleBytecode();
    }
    DCHECK_EQ(loop_effects_stack_.size(),
              is_inline() && caller_details_->loop_effects ? 1 : 0);
  }
References v8::internal::SourcePositionTableIterator::Advance(), v8::internal::interpreter::BytecodeArrayIterator::Advance(), caller_details_, v8::internal::SourcePositionTableIterator::code_offset(), v8::internal::BitVector::Contains(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), current_source_position_, DCHECK_EQ, v8::internal::SourcePositionTableIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::done(), entrypoint_, v8::internal::LocalIsolate::heap(), inlining_id_, is_inline(), iterator_, local_isolate_, v8::internal::maglev::MaglevCallerDetails::loop_effects, loop_effects_stack_, loop_headers_to_peel_, PeelLoop(), v8::internal::LocalHeap::Safepoint(), v8::internal::SourcePosition::ScriptOffset(), v8::internal::interpreter::BytecodeArrayIterator::SetOffset(), v8::internal::SourcePositionTableIterator::source_position(), source_position_iterator_, V8_UNLIKELY, and VisitSingleBytecode().
Referenced by Build().
BuildBranchIfFloat64IsHole()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfFloat64IsHole (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14931 of file maglev-graph-builder.cc.
                                             {
  // TODO(victorgomes): Optimize.
  return builder.Build<BranchIfFloat64IsHole>({node});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build().
Referenced by BuildBranchIfUndetectable().
BuildBranchIfFloat64ToBooleanTrue()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfFloat64ToBooleanTrue (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14925 of file maglev-graph-builder.cc.
                                                                       {
  // TODO(victorgomes): Optimize.
  return builder.Build<BranchIfFloat64ToBooleanTrue>({node});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build().
BuildBranchIfInt32Compare()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfInt32Compare (BranchBuilder & builder, Operation op, ValueNode * lhs, ValueNode * rhs) [private]
Definition at line 14997 of file maglev-graph-builder.cc.
                                                                          {
  auto lhs_const = TryGetInt32Constant(lhs);
  if (lhs_const) {
    auto rhs_const = TryGetInt32Constant(rhs);
    if (rhs_const) {
      return builder.FromBool(
          CompareInt32(lhs_const.value(), rhs_const.value(), op));
    }
  }
  return builder.Build<BranchIfInt32Compare>({lhs, rhs}, op);
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CompareInt32(), and v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool().
Referenced by TryBuildNewConsString().
BuildBranchIfInt32ToBooleanTrue()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfInt32ToBooleanTrue (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14911 of file maglev-graph-builder.cc.
                                                                     {
  // TODO(victorgomes): Optimize.
  return builder.Build<BranchIfInt32ToBooleanTrue>({node});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build().
BuildBranchIfIntPtrToBooleanTrue()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfIntPtrToBooleanTrue (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14918 of file maglev-graph-builder.cc.
                                                                      {
  // TODO(victorgomes): Optimize.
  return builder.Build<BranchIfIntPtrToBooleanTrue>({node});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build().
BuildBranchIfJSReceiver()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfJSReceiver (BranchBuilder & builder, ValueNode * value) [private]
Definition at line 14983 of file maglev-graph-builder.cc.
                                              {
  if (!value->is_tagged() && value->properties().value_representation() !=
                                 ValueRepresentation::kHoleyFloat64) {
    return builder.AlwaysFalse();
  }
  if (CheckType(value, NodeType::kJSReceiver)) {
    return builder.AlwaysTrue();
  } else if (HasDisjointType(value, NodeType::kJSReceiver)) {
    return builder.AlwaysFalse();
  }
  return builder.Build<BranchIfJSReceiver>({value});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysFalse(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysTrue(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), and v8::internal::value.
BuildBranchIfNull()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfNull (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14789 of file maglev-graph-builder.cc.
                                             {
  return BuildBranchIfRootConstant(builder, node, RootIndex::kNullValue);
}
BuildBranchIfReferenceEqual() [1/2]
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfReferenceEqual (BranchBuilder & builder, ValueNode * lhs, ValueNode * rhs) [private]
Definition at line 14630 of file maglev-graph-builder.cc.
                                                                {
  if (RootConstant* root_constant = rhs->TryCast<RootConstant>()) {
    return builder.Build<BranchIfRootConstant>({lhs}, root_constant->index());
  }
  if (RootConstant* root_constant = lhs->TryCast<RootConstant>()) {
    return builder.Build<BranchIfRootConstant>({rhs}, root_constant->index());
  }
  if (InlinedAllocation* alloc_lhs = lhs->TryCast<InlinedAllocation>()) {
    if (InlinedAllocation* alloc_rhs = rhs->TryCast<InlinedAllocation>()) {
      return builder.FromBool(alloc_lhs == alloc_rhs);
    }
  }
  return builder.Build<BranchIfReferenceEqual>({lhs, rhs});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool(), and v8::internal::maglev::NodeBase::TryCast().
BuildBranchIfReferenceEqual() [2/2]
BasicBlock* v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfReferenceEqual (ValueNode * lhs, ValueNode * rhs, BasicBlockRef * true_target, BasicBlockRef * false_target) [private]
BuildBranchIfRootConstant()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant (BranchBuilder & builder, ValueNode * node, RootIndex root_index) [private]
Definition at line 14675 of file maglev-graph-builder.cc.
                                                                   {
  // We assume that Maglev never emits a comparison to a root number.
  DCHECK(!IsNumberRootConstant(root_index));
  // If the node we're checking is in the accumulator, swap it in the branch
  // with the checked value. Cache whether we want to swap, since after we've
  // swapped the accumulator isn't the original node anymore.
  BranchBuilder::PatchAccumulatorInBranchScope scope(builder, node, root_index);
  if (node->properties().value_representation() ==
      ValueRepresentation::kHoleyFloat64) {
    if (root_index == RootIndex::kUndefinedValue) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      return builder.Build<BranchIfFloat64IsUndefinedOrHole>({node});
#else
      return builder.Build<BranchIfFloat64IsHole>({node});
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    }
    return builder.AlwaysFalse();
  }
  if (CheckType(node, NodeType::kNumber)) {
    return builder.AlwaysFalse();
  }
  CHECK(node->is_tagged());
  if (root_index != RootIndex::kTrueValue &&
      root_index != RootIndex::kFalseValue &&
      CheckType(node, NodeType::kBoolean)) {
    return builder.AlwaysFalse();
  }
  while (LogicalNot* logical_not = node->TryCast<LogicalNot>()) {
    // Bypassing logical not(s) on the input and swapping true/false
    // destinations.
    node = logical_not->value().node();
    builder.SwapTargets();
  }
  if (RootConstant* constant = node->TryCast<RootConstant>()) {
    return builder.FromBool(constant->index() == root_index);
  }
  if (root_index == RootIndex::kUndefinedValue) {
    if (Constant* constant = node->TryCast<Constant>()) {
      return builder.FromBool(constant->object().IsUndefined());
    }
  }
  if (root_index != RootIndex::kTrueValue &&
      root_index != RootIndex::kFalseValue) {
    return builder.Build<BranchIfRootConstant>({node}, root_index);
  }
  if (root_index == RootIndex::kFalseValue) {
    builder.SwapTargets();
  }
  switch (node->opcode()) {
    case Opcode::kTaggedEqual:
      return BuildBranchIfReferenceEqual(
          builder, node->Cast<TaggedEqual>()->lhs().node(),
          node->Cast<TaggedEqual>()->rhs().node());
    case Opcode::kTaggedNotEqual:
      // Swapped true and false targets.
      builder.SwapTargets();
      return BuildBranchIfReferenceEqual(
          builder, node->Cast<TaggedNotEqual>()->lhs().node(),
          node->Cast<TaggedNotEqual>()->rhs().node());
    case Opcode::kInt32Compare:
      return builder.Build<BranchIfInt32Compare>(
          {node->Cast<Int32Compare>()->left_input().node(),
           node->Cast<Int32Compare>()->right_input().node()},
          node->Cast<Int32Compare>()->operation());
    case Opcode::kFloat64Compare:
      return builder.Build<BranchIfFloat64Compare>(
          {node->Cast<Float64Compare>()->left_input().node(),
           node->Cast<Float64Compare>()->right_input().node()},
          node->Cast<Float64Compare>()->operation());
    case Opcode::kInt32ToBoolean:
      if (node->Cast<Int32ToBoolean>()->flip()) {
        builder.SwapTargets();
      }
      return builder.Build<BranchIfInt32ToBooleanTrue>(
          {node->Cast<Int32ToBoolean>()->value().node()});
    case Opcode::kIntPtrToBoolean:
      if (node->Cast<IntPtrToBoolean>()->flip()) {
        builder.SwapTargets();
      }
      return builder.Build<BranchIfIntPtrToBooleanTrue>(
          {node->Cast<IntPtrToBoolean>()->value().node()});
    case Opcode::kFloat64ToBoolean:
      if (node->Cast<Float64ToBoolean>()->flip()) {
        builder.SwapTargets();
      }
      return builder.Build<BranchIfFloat64ToBooleanTrue>(
          {node->Cast<Float64ToBoolean>()->value().node()});
    case Opcode::kTestUndetectable:
      return builder.Build<BranchIfUndetectable>(
          {node->Cast<TestUndetectable>()->value().node()},
          node->Cast<TestUndetectable>()->check_type());
    case Opcode::kHoleyFloat64IsHole:
      return builder.Build<BranchIfFloat64IsHole>(
          {node->Cast<HoleyFloat64IsHole>()->input().node()});
    default:
      return builder.Build<BranchIfRootConstant>({node}, RootIndex::kTrueValue);
  }
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysFalse(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::maglev::NodeBase::Cast(), CHECK, v8::internal::DCHECK(), v8::internal::maglev::Int32ToBoolean::flip(), v8::internal::maglev::IntPtrToBoolean::flip(), v8::internal::maglev::Float64ToBoolean::flip(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool(), v8::internal::maglev::ValueNode::is_tagged(), v8::internal::maglev::TaggedEqual::lhs(), v8::internal::maglev::TaggedNotEqual::lhs(), v8::internal::maglev::Input::node(), v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::TaggedEqual::rhs(), v8::internal::maglev::TaggedNotEqual::rhs(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SwapTargets(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::value, and v8::internal::maglev::OpProperties::value_representation().
BuildBranchIfToBooleanTrue()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14819 of file maglev-graph-builder.cc.
                                             {
  // If this is a known boolean, use the non-ToBoolean version.
  if (CheckType(node, NodeType::kBoolean)) {
    return BuildBranchIfTrue(builder, node);
  }
  // There shouldn't be any LogicalNots here, for swapping true/false, since
  // these are known to be boolean and should have gone throught the
  // non-ToBoolean path.
  DCHECK(!node->Is<LogicalNot>());
  bool known_to_boolean_value = false;
  bool direction_is_true = true;
  if (IsConstantNode(node->opcode())) {
    known_to_boolean_value = true;
    direction_is_true = FromConstantToBool(local_isolate(), node);
  } else {
    // TODO(victorgomes): Unify this with TestUndetectable?
    // JSReceivers are true iff they are not marked as undetectable. Check if
    // all maps have the same detectability, and if yes, the boolean value is
    // known.
    NodeInfo* node_info = known_node_aspects().TryGetInfoFor(node);
    if (node_info && NodeTypeIs(node_info->type(), NodeType::kJSReceiver) &&
        node_info->possible_maps_are_known()) {
      bool all_detectable = true;
      bool all_undetectable = true;
      for (compiler::MapRef map : node_info->possible_maps()) {
        bool is_undetectable = map.is_undetectable();
        all_detectable &= !is_undetectable;
        all_undetectable &= is_undetectable;
      }
      if (all_detectable || all_undetectable) {
        known_to_boolean_value = true;
        direction_is_true = all_detectable;
      }
    }
  }
  if (known_to_boolean_value) {
    return builder.FromBool(direction_is_true);
  }
  switch (node->value_representation()) {
    // The ToBoolean of both the_hole and NaN is false, so we can use the
    // same operation for HoleyFloat64 and Float64.
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      return BuildBranchIfFloat64ToBooleanTrue(builder, node);
    case ValueRepresentation::kUint32:
      // Uint32 has the same logic as Int32 when converting ToBoolean, namely
      // comparison against zero, so we can cast it and ignore the signedness.
      node = AddNewNode<TruncateUint32ToInt32>({node});
      [[fallthrough]];
    case ValueRepresentation::kInt32:
      return BuildBranchIfInt32ToBooleanTrue(builder, node);
    case ValueRepresentation::kIntPtr:
      return BuildBranchIfIntPtrToBooleanTrue(builder, node);
    case ValueRepresentation::kTagged:
      break;
  }
  NodeInfo* node_info = known_node_aspects().TryGetInfoFor(node);
  if (node_info) {
    if (ValueNode* as_int32 = node_info->alternative().int32()) {
      return BuildBranchIfInt32ToBooleanTrue(builder, as_int32);
    }
    if (ValueNode* as_float64 = node_info->alternative().float64()) {
      return BuildBranchIfFloat64ToBooleanTrue(builder, as_float64);
    }
  }
  NodeType old_type;
  if (CheckType(node, NodeType::kBoolean, &old_type)) {
    return builder.Build<BranchIfRootConstant>({node}, RootIndex::kTrueValue);
  }
  if (CheckType(node, NodeType::kSmi)) {
    builder.SwapTargets();
    return builder.Build<BranchIfReferenceEqual>({node, GetSmiConstant(0)});
  }
  if (CheckType(node, NodeType::kString)) {
    builder.SwapTargets();
    return builder.Build<BranchIfRootConstant>({node},
                                               RootIndex::kempty_string);
  }
  // TODO(verwaest): Number or oddball.
  return builder.Build<BranchIfToBooleanTrue>({node}, GetCheckType(old_type));
}
References v8::internal::maglev::NodeInfo::alternative(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::DCHECK(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool(), v8::internal::maglev::FromConstantToBool(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), v8::internal::maglev::NodeBase::Is(), v8::internal::is_undetectable, v8::internal::maglev::IsConstantNode(), v8::internal::anonymous_namespace{ic.cc}::kIntPtr, v8::internal::compiler::kSmi, v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SwapTargets(), v8::internal::maglev::NodeInfo::type(), and v8::internal::maglev::ValueNode::value_representation().
BuildBranchIfTrue()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfTrue (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14783 of file maglev-graph-builder.cc.
                                             {
  builder.SetBranchSpecializationMode(BranchSpecializationMode::kAlwaysBoolean);
  return BuildBranchIfRootConstant(builder, node, RootIndex::kTrueValue);
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::SetBranchSpecializationMode().
BuildBranchIfUint32Compare()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUint32Compare (BranchBuilder & builder, Operation op, ValueNode * lhs, ValueNode * rhs) [private]
Definition at line 15010 of file maglev-graph-builder.cc.
                                                                          {
  auto lhs_const = TryGetUint32Constant(lhs);
  if (lhs_const) {
    auto rhs_const = TryGetUint32Constant(rhs);
    if (rhs_const) {
      return builder.FromBool(
          CompareUint32(lhs_const.value(), rhs_const.value(), op));
    }
  }
  return builder.Build<BranchIfUint32Compare>({lhs, rhs}, op);
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CompareUint32(), and v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool().
BuildBranchIfUndefined()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefined (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14794 of file maglev-graph-builder.cc.
                                             {
  return BuildBranchIfRootConstant(builder, node, RootIndex::kUndefinedValue);
}
BuildBranchIfUndefinedOrNull()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull (BranchBuilder & builder, ValueNode * node) [private]
Definition at line 14800 of file maglev-graph-builder.cc.
                                                                  {
  compiler::OptionalHeapObjectRef maybe_constant = TryGetConstant(node);
  if (maybe_constant.has_value()) {
    return builder.FromBool(maybe_constant->IsNullOrUndefined());
  }
  if (!node->is_tagged()) {
    if (node->properties().value_representation() ==
        ValueRepresentation::kHoleyFloat64) {
      return BuildBranchIfFloat64IsHole(builder, node);
    }
    return builder.AlwaysFalse();
  }
  if (HasDisjointType(node, NodeType::kOddball)) {
    return builder.AlwaysFalse();
  }
  return builder.Build<BranchIfUndefinedOrNull>({node});
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysFalse(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::FromBool(), v8::internal::maglev::ValueNode::is_tagged(), v8::internal::maglev::NodeBase::properties(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), and v8::internal::maglev::OpProperties::value_representation().
BuildBranchIfUndetectable()
MaglevGraphBuilder::BranchResult v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndetectable (BranchBuilder & builder, ValueNode * value) [private]
Definition at line 3990 of file maglev-graph-builder.cc.
                                              {
  ValueNode* result = BuildTestUndetectable(value);
  switch (result->opcode()) {
    case Opcode::kRootConstant:
      switch (result->Cast<RootConstant>()->index()) {
        case RootIndex::kTrueValue:
        case RootIndex::kUndefinedValue:
        case RootIndex::kNullValue:
          return builder.AlwaysTrue();
        default:
          return builder.AlwaysFalse();
      }
    case Opcode::kHoleyFloat64IsHole:
      return BuildBranchIfFloat64IsHole(
          builder, result->Cast<HoleyFloat64IsHole>()->input().node());
    case Opcode::kTestUndetectable:
      return builder.Build<BranchIfUndetectable>(
          {result->Cast<TestUndetectable>()->value().node()},
          result->Cast<TestUndetectable>()->check_type());
    default:
      UNREACHABLE();
  }
}
References v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysFalse(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::AlwaysTrue(), v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build(), BuildBranchIfFloat64IsHole(), BuildTestUndetectable(), v8::internal::maglev::RootConstant::index(), v8::internal::maglev::HoleyFloat64IsHole::input(), v8::internal::maglev::Input::node(), v8::base::internal::result, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by TryReduceTypeOf().
BuildCallBuiltin() [1/2]
template<Builtin kBuiltin>
CallBuiltin* v8::internal::maglev::MaglevGraphBuilder::BuildCallBuiltin (std::initializer_list< ValueNode * > inputs) [inline], [private]
Definition at line 1326 of file maglev-graph-builder.h.
                                                                        {
    using Descriptor = typename CallInterfaceDescriptorFor<kBuiltin>::type;
    if constexpr (Descriptor::HasContextParameter()) {
      return AddNewNode<CallBuiltin>(
          inputs.size() + 1,
          [&](CallBuiltin* call_builtin) {
            int arg_index = 0;
            for (auto* input : inputs) {
              call_builtin->set_arg(arg_index++, input);
            }
          },
          kBuiltin, GetContext());
    } else {
      return AddNewNode<CallBuiltin>(
          inputs.size(),
          [&](CallBuiltin* call_builtin) {
            int arg_index = 0;
            for (auto* input : inputs) {
              call_builtin->set_arg(arg_index++, input);
            }
          },
          kBuiltin);
    }
  }
References GetContext().
BuildCallBuiltin() [2/2]
template<Builtin kBuiltin>
CallBuiltin* v8::internal::maglev::MaglevGraphBuilder::BuildCallBuiltin (std::initializer_list< ValueNode * > inputs, compiler::FeedbackSource const & feedback, CallBuiltin::FeedbackSlotType slot_type = CallBuiltin::kTaggedIndex) [inline], [private]
Definition at line 1352 of file maglev-graph-builder.h.
                                                                       {
    CallBuiltin* call_builtin = BuildCallBuiltin<kBuiltin>(inputs);
    call_builtin->set_feedback(feedback, slot_type);
#ifdef DEBUG
    // Check that the last parameters are kSlot and kVector.
    using Descriptor = typename CallInterfaceDescriptorFor<kBuiltin>::type;
    int slot_index = call_builtin->InputCountWithoutContext();
    int vector_index = slot_index + 1;
    DCHECK_EQ(slot_index, Descriptor::kSlot);
    // TODO(victorgomes): Rename all kFeedbackVector parameters in the builtins
    // to kVector.
    DCHECK_EQ(vector_index, Descriptor::kVector);
#endif // DEBUG
    return call_builtin;
  }
References DCHECK_EQ, v8::internal::maglev::CallBuiltin::InputCountWithoutContext(), and v8::internal::maglev::CallBuiltin::set_feedback().
BuildCallCPPBuiltin()
CallCPPBuiltin* v8::internal::maglev::MaglevGraphBuilder::BuildCallCPPBuiltin (Builtin builtin, ValueNode * target, ValueNode * new_target, std::initializer_list< ValueNode * > inputs) [inline], [private]
Definition at line 1371 of file maglev-graph-builder.h.
                                              {
    DCHECK(Builtins::IsCpp(builtin));
    const size_t input_count = inputs.size() + CallCPPBuiltin::kFixedInputCount;
    return AddNewNode<CallCPPBuiltin>(
        input_count,
        [&](CallCPPBuiltin* call_builtin) {
          int arg_index = 0;
          for (auto* input : inputs) {
            call_builtin->set_arg(arg_index++, input);
          }
        },
        builtin, GetTaggedValue(target), GetTaggedValue(new_target),
        GetTaggedValue(GetContext()));
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::Builtins::IsCpp(), and v8::internal::maglev::CallCPPBuiltin::set_arg().
BuildCallFromRegisterList()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCallFromRegisterList (ConvertReceiverMode receiver_mode) [private]
Definition at line 11759 of file maglev-graph-builder.cc.
                                       {
  ValueNode* target = LoadRegister(0);
  interpreter::RegisterList reg_list = iterator_.GetRegisterListOperand(1);
  FeedbackSlot slot = GetSlotOperand(3);
  compiler::FeedbackSource feedback_source(feedback(), slot);
  CallArguments args(receiver_mode, reg_list, current_interpreter_frame_);
  return BuildCallWithFeedback(target, args, feedback_source);
}
References v8::base::args.
BuildCallFromRegisters()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCallFromRegisters (int argc_count, ConvertReceiverMode receiver_mode) [private]
Definition at line 11769 of file maglev-graph-builder.cc.
                                                      {
  ValueNode* target = LoadRegister(0);
  const int receiver_count =
      (receiver_mode == ConvertReceiverMode::kNullOrUndefined) ? 0 : 1;
  const int reg_count = arg_count + receiver_count;
  FeedbackSlot slot = GetSlotOperand(reg_count + 1);
  compiler::FeedbackSource feedback_source(feedback(), slot);
  switch (reg_count) {
    case 0: {
      DCHECK_EQ(receiver_mode, ConvertReceiverMode::kNullOrUndefined);
      CallArguments args(receiver_mode);
      return BuildCallWithFeedback(target, args, feedback_source);
    }
    case 1: {
      CallArguments args(receiver_mode, {LoadRegister(1)});
      return BuildCallWithFeedback(target, args, feedback_source);
    }
    case 2: {
      CallArguments args(receiver_mode, {LoadRegister(1), LoadRegister(2)});
      return BuildCallWithFeedback(target, args, feedback_source);
    }
    case 3: {
      CallArguments args(receiver_mode,
                         {LoadRegister(1), LoadRegister(2), LoadRegister(3)});
      return BuildCallWithFeedback(target, args, feedback_source);
    }
    default:
      UNREACHABLE();
  }
}
References v8::base::args, DCHECK_EQ, v8::internal::kNullOrUndefined, and v8::internal::UNREACHABLE().
BuildCallKnownJSFunction() [1/2]
CallKnownJSFunction * v8::internal::maglev::MaglevGraphBuilder::BuildCallKnownJSFunction (ValueNode * context, ValueNode * function, ValueNode * new_target, compiler::SharedFunctionInfoRef shared, base::Vector< ValueNode * > arguments) [private]
Definition at line 11169 of file maglev-graph-builder.cc.
                                      {
  DCHECK_GT(arguments.size(), 0);
  constexpr int kSkipReceiver = 1;
  int argcount_without_receiver =
      static_cast<int>(arguments.size()) - kSkipReceiver;
  size_t input_count =
      argcount_without_receiver + CallKnownJSFunction::kFixedInputCount;
  return AddNewNode<CallKnownJSFunction>(
      input_count,
      [&](CallKnownJSFunction* call) {
        for (int i = 0; i < argcount_without_receiver; i++) {
          call->set_arg(i, GetTaggedValue(arguments[i + kSkipReceiver]));
        }
      },
#ifdef V8_ENABLE_LEAPTIERING
      dispatch_handle,
#endif
      shared, GetTaggedValue(function), GetTaggedValue(context),
      GetTaggedValue(arguments[0]), GetTaggedValue(new_target));
}
References DCHECK_GT, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::maglev::CallKnownJSFunction::set_arg(), and v8::base::Vector< T >::size().
BuildCallKnownJSFunction() [2/2]
CallKnownJSFunction * v8::internal::maglev::MaglevGraphBuilder::BuildCallKnownJSFunction (ValueNode * context, ValueNode * function, ValueNode * new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11145 of file maglev-graph-builder.cc.
                                                   {
  ValueNode* receiver = GetConvertReceiver(shared, args);
  size_t input_count = args.count() + CallKnownJSFunction::kFixedInputCount;
  return AddNewNode<CallKnownJSFunction>(
      input_count,
      [&](CallKnownJSFunction* call) {
        for (int i = 0; i < static_cast<int>(args.count()); i++) {
          call->set_arg(i, GetTaggedValue(args[i]));
        }
      },
#ifdef V8_ENABLE_LEAPTIERING
      dispatch_handle,
#endif
      shared, GetTaggedValue(function), GetTaggedValue(context),
      GetTaggedValue(receiver), GetTaggedValue(new_target));
}
References v8::base::args, v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::CallKnownJSFunction::set_arg().
BuildCallRuntime()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCallRuntime (Runtime::FunctionId function_id, std::initializer_list< ValueNode * > inputs) [inline], [private]
Definition at line 1404 of file maglev-graph-builder.h.
                                                                        {
    CallRuntime* result = AddNewNode<CallRuntime>(
        inputs.size() + CallRuntime::kFixedInputCount,
        [&](CallRuntime* call_runtime) {
          int arg_index = 0;
          for (auto* input : inputs) {
            call_runtime->set_arg(arg_index++, GetTaggedValue(input));
          }
        },
        function_id, GetContext());
    if (RuntimeFunctionCanThrow(function_id)) {
      return BuildAbort(AbortReason::kUnexpectedReturnFromThrow);
    }
    return result;
  }
References v8::base::internal::result.
BuildCallSelf()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildCallSelf (ValueNode * context, ValueNode * function, ValueNode * new_target, compiler::SharedFunctionInfoRef shared, CallArguments & args) [private]
Definition at line 10950 of file maglev-graph-builder.cc.
                                                               {
  ValueNode* receiver = GetConvertReceiver(shared, args);
  size_t input_count = args.count() + CallSelf::kFixedInputCount;
  graph()->set_has_recursive_calls(true);
  DCHECK_EQ(
      compilation_unit_->info()->toplevel_compilation_unit()->parameter_count(),
      shared.internal_formal_parameter_count_with_receiver_deprecated());
  return AddNewNode<CallSelf>(
      input_count,
      [&](CallSelf* call) {
        for (int i = 0; i < static_cast<int>(args.count()); i++) {
          call->set_arg(i, GetTaggedValue(args[i]));
        }
      },
      compilation_unit_->info()->toplevel_compilation_unit()->parameter_count(),
      GetTaggedValue(function), GetTaggedValue(context),
      GetTaggedValue(receiver), GetTaggedValue(new_target));
}
References v8::base::args, DCHECK_EQ, graph(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_with_receiver_deprecated(), and v8::internal::maglev::CallSelf::set_arg().
BuildCallWithFeedback()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCallWithFeedback (ValueNode * target_node, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11502 of file maglev-graph-builder.cc.
                                                   {
  const compiler::ProcessedFeedback& processed_feedback =
      broker()->GetFeedbackForCall(feedback_source);
  if (processed_feedback.IsInsufficient()) {
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kInsufficientTypeFeedbackForCall);
  }
  DCHECK_EQ(processed_feedback.kind(), compiler::ProcessedFeedback::kCall);
  const compiler::CallFeedback& call_feedback = processed_feedback.AsCall();
  if (call_feedback.target().has_value()) {
    if (call_feedback.target()->IsJSFunction()) {
      CallFeedbackContent content = call_feedback.call_feedback_content();
      compiler::JSFunctionRef feedback_target =
          call_feedback.target()->AsJSFunction();
      if (content == CallFeedbackContent::kReceiver) {
        compiler::NativeContextRef native_context =
            broker()->target_native_context();
        compiler::JSFunctionRef apply_function =
            native_context.function_prototype_apply(broker());
        RETURN_IF_ABORT(BuildCheckValueByReference(
            target_node, apply_function, DeoptimizeReason::kWrongCallTarget));
        PROCESS_AND_RETURN_IF_DONE(
            TryReduceFunctionPrototypeApplyCallWithReceiver(
                feedback_target, args, feedback_source),
            SetAccumulator);
        feedback_target = apply_function;
      } else {
        DCHECK_EQ(CallFeedbackContent::kTarget, content);
      }
      RETURN_IF_ABORT(BuildCheckValueByReference(
          target_node, feedback_target, DeoptimizeReason::kWrongCallTarget));
    } else if (call_feedback.target()->IsFeedbackCell() &&
               args.mode() == CallArguments::kDefault) {
      compiler::FeedbackCellRef feedback_cell =
          call_feedback.target()->AsFeedbackCell();
      compiler::OptionalSharedFunctionInfoRef shared =
          feedback_cell.shared_function_info(broker());
      if (shared.has_value() && !shared->HasBreakInfo(broker())) {
        RETURN_IF_ABORT(BuildCheckJSFunction(target_node));
        ValueNode* target_feedback_cell =
            BuildLoadJSFunctionFeedbackCell(target_node);
        RETURN_IF_ABORT(
            BuildCheckValueByReference(target_feedback_cell, feedback_cell,
                                       DeoptimizeReason::kWrongFeedbackCell));
        if (IsClassConstructor(shared->kind())) {
          // If we have a class constructor, we should raise an exception.
          return BuildCallRuntime(Runtime::kThrowConstructorNonCallableError,
                                  {target_node});
        }
        ValueNode* context = BuildLoadJSFunctionContext(target_node);
        compiler::ScopeInfoRef scope_info = shared->scope_info(broker());
        if (scope_info.HasOuterScopeInfo()) {
          scope_info = scope_info.OuterScopeInfo(broker());
          CHECK(scope_info.HasContext());
          graph()->record_scope_info(context, scope_info);
        }
        PROCESS_AND_RETURN_IF_DONE(
            TryBuildCallKnownJSFunction(
                context, target_node,
                GetRootConstant(RootIndex::kUndefinedValue),
#ifdef V8_ENABLE_LEAPTIERING
                feedback_cell.dispatch_handle(),
#endif
                shared.value(), feedback_cell, args, feedback_source),
            SetAccumulator);
        UNREACHABLE();
      }
    }
  }
  PROCESS_AND_RETURN_IF_DONE(ReduceCall(target_node, args, feedback_source),
                             SetAccumulator);
  UNREACHABLE();
}
References v8::base::args, v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::CallFeedback::call_feedback_content(), CHECK, DCHECK_EQ, graph(), v8::internal::compiler::ScopeInfoRef::HasContext(), v8::internal::compiler::ScopeInfoRef::HasOuterScopeInfo(), v8::internal::IsClassConstructor(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::ProcessedFeedback::kCall, v8::internal::compiler::ProcessedFeedback::kind(), v8::internal::kReceiver, v8::internal::kTarget, v8::internal::native_context, v8::internal::compiler::ScopeInfoRef::OuterScopeInfo(), PROCESS_AND_RETURN_IF_DONE, RETURN_IF_ABORT, v8::internal::compiler::FeedbackCellRef::shared_function_info(), v8::internal::compiler::CallFeedback::target(), v8::internal::UNREACHABLE(), and v8::internal::compiler::FeedbackCellRef::value().
BuildCheckHeapObject()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckHeapObject (ValueNode * object) [private]
Definition at line 4591 of file maglev-graph-builder.cc.
                                                                       {
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(
          IntersectType(GetType(object), NodeType::kAnyHeapObject))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kSmi);
  }
  if (EnsureType(object, NodeType::kAnyHeapObject)) return ReduceResult::Done();
  AddNewNode<CheckHeapObject>({object});
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), GetType(), v8::internal::maglev::IntersectType(), v8::internal::maglev::IsEmptyNodeType(), and v8::internal::compiler::kSmi.
Referenced by TryBuildPropertyCellStore(), and TryBuildStoreField().
BuildCheckInternalizedStringValueOrByReference()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckInternalizedStringValueOrByReference (ValueNode * node, compiler::HeapObjectRef ref, DeoptimizeReason reason) [private]
Definition at line 11247 of file maglev-graph-builder.cc.
                                                                         {
  if (!IsConstantNode(node->opcode()) && ref.IsInternalizedString()) {
    if (!IsInstanceOfNodeType(ref.map(broker()), GetType(node), broker())) {
      return EmitUnconditionalDeopt(reason);
    }
    AddNewNode<CheckValueEqualsString>({node}, ref.AsInternalizedString(),
                                       reason);
    SetKnownValue(node, ref, NodeType::kString);
    return ReduceResult::Done();
  }
  return BuildCheckValueByReference(node, ref, reason);
}
References broker(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::IsInstanceOfNodeType(), v8::internal::compiler::HeapObjectRef::map(), and v8::internal::maglev::NodeBase::opcode().
BuildCheckJSFunction()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSFunction (ValueNode * object) [private]
Definition at line 4686 of file maglev-graph-builder.cc.
                                                                       {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object), NodeType::kJSFunction))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongInstanceType);
  }
  if (EnsureType(object, NodeType::kJSFunction, &known_type))
    return ReduceResult::Done();
  AddNewNode<CheckInstanceType>({object}, GetCheckType(known_type),
                                FIRST_JS_FUNCTION_TYPE, LAST_JS_FUNCTION_TYPE);
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
BuildCheckJSReceiver()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiver (ValueNode * object) [private]
Definition at line 4700 of file maglev-graph-builder.cc.
                                                                       {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object), NodeType::kJSReceiver))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongInstanceType);
  }
  if (EnsureType(object, NodeType::kJSReceiver, &known_type))
    return ReduceResult::Done();
  AddNewNode<CheckInstanceType>({object}, GetCheckType(known_type),
                                FIRST_JS_RECEIVER_TYPE, LAST_JS_RECEIVER_TYPE);
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by VisitCompareOperation().
BuildCheckJSReceiverOrNullOrUndefined()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckJSReceiverOrNullOrUndefined (ValueNode * object) [private]
Definition at line 4714 of file maglev-graph-builder.cc.
                       {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object),
                                    NodeType::kJSReceiverOrNullOrUndefined))) {
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kNotAJavaScriptObjectOrNullOrUndefined);
  }
  if (EnsureType(object, NodeType::kJSReceiverOrNullOrUndefined, &known_type)) {
    return ReduceResult::Done();
  }
  AddNewNode<CheckJSReceiverOrNullOrUndefined>({object},
                                               GetCheckType(known_type));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by VisitCompareOperation().
BuildCheckMaps()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps (ValueNode * object, base::Vector< const compiler::MapRef > maps, std::optional< ValueNode * > map = {}, bool has_deprecated_map_without_migration_target = false, bool migration_done_outside = false) [private]
Definition at line 4858 of file maglev-graph-builder.cc.
                                 {
  // TODO(verwaest): Support other objects with possible known stable maps as
  // well.
  if (compiler::OptionalHeapObjectRef constant = TryGetConstant(object)) {
    // For constants with stable maps that match one of the desired maps, we
    // don't need to emit a map check, and can use the dependency -- we
    // can't do this for unstable maps because the constant could migrate
    // during compilation.
    compiler::MapRef constant_map = constant.value().map(broker());
    if (std::find(maps.begin(), maps.end(), constant_map) != maps.end()) {
      if (constant_map.is_stable()) {
        broker()->dependencies()->DependOnStableMap(constant_map);
        return ReduceResult::Done();
      }
      // TODO(verwaest): Reduce maps to the constant map.
    } else {
      // TODO(leszeks): Insert an unconditional deopt if the constant map
      // doesn't match the required map.
    }
  }
  NodeInfo* known_info = GetOrCreateInfoFor(object);
  // Calculates if known maps are a subset of maps, their map intersection and
  // whether we should emit check with migration.
  KnownMapsMerger merger(broker(), zone(), maps);
  merger.IntersectWithKnownNodeAspects(object, known_node_aspects());
  if (IsEmptyNodeType(IntersectType(merger.node_type(), GetType(object)))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongMap);
  }
  // If the known maps are the subset of the maps to check, we are done.
  if (merger.known_maps_are_subset_of_requested_maps()) {
    // The node type of known_info can get out of sync with the possible maps.
    // For instance after merging with an effectively dead branch (i.e., check
    // contradicting all possible maps).
    // TODO(olivf) Try to combine node_info and possible maps and ensure that
    // narrowing the type also clears impossible possible_maps.
    if (!NodeTypeIs(known_info->type(), merger.node_type())) {
      known_info->UnionType(merger.node_type());
    }
#ifdef DEBUG
    // Double check that, for every possible map, it's one of the maps we'd
    // want to check.
    for (compiler::MapRef possible_map :
         known_node_aspects().TryGetInfoFor(object)->possible_maps()) {
      DCHECK_NE(std::find(maps.begin(), maps.end(), possible_map), maps.end());
    }
#endif
    return ReduceResult::Done();
  }
  if (merger.intersect_set().is_empty()) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongMap);
  }
  // TODO(v8:7700): Check if the {maps} - {known_maps} size is smaller than
  // {maps} \intersect {known_maps}, we can emit CheckNotMaps instead.
  // Emit checks.
  if (merger.emit_check_with_migration() && !migration_done_outside) {
    AddNewNode<CheckMapsWithMigration>({object}, merger.intersect_set(),
                                       GetCheckType(known_info->type()));
  } else if (has_deprecated_map_without_migration_target &&
             !migration_done_outside) {
    AddNewNode<CheckMapsWithMigrationAndDeopt>(
        {object}, merger.intersect_set(), GetCheckType(known_info->type()));
  } else if (map) {
    AddNewNode<CheckMapsWithAlreadyLoadedMap>({object, *map},
                                              merger.intersect_set());
  } else {
    AddNewNode<CheckMaps>({object}, merger.intersect_set(),
                          GetCheckType(known_info->type()));
  }
  merger.UpdateKnownNodeAspects(object, known_node_aspects());
  return ReduceResult::Done();
}
References v8::base::Vector< T >::begin(), broker(), DCHECK_NE, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), v8::base::Vector< T >::end(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetOrCreateInfoFor(), GetType(), v8::internal::maglev::IntersectType(), v8::internal::compiler::MapRef::is_stable(), v8::internal::maglev::IsEmptyNodeType(), known_node_aspects(), v8::internal::maglev::NodeTypeIs(), TryGetConstant(), v8::internal::maglev::NodeInfo::type(), v8::internal::maglev::NodeInfo::UnionType(), and zone().
Referenced by TryBuildNamedAccess(), TryBuildPropertyCellStore(), and TryBuildStoreField().
BuildCheckNotHole()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckNotHole (ValueNode * node) [private]
Definition at line 11325 of file maglev-graph-builder.cc.
                                                                  {
  if (!node->is_tagged()) return ReduceResult::Done();
  compiler::OptionalHeapObjectRef maybe_constant = TryGetConstant(node);
  if (maybe_constant) {
    if (maybe_constant.value().IsTheHole()) {
      return EmitUnconditionalDeopt(DeoptimizeReason::kHole);
    }
    return ReduceResult::Done();
  }
  AddNewNode<CheckNotHole>({node});
  return ReduceResult::Done();
}
References v8::internal::maglev::ValueNode::is_tagged(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
BuildCheckNumber()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumber (ValueNode * object) [private]
Definition at line 4662 of file maglev-graph-builder.cc.
                                                                   {
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object), NodeType::kNumber))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotANumber);
  }
  if (EnsureType(object, NodeType::kNumber)) return ReduceResult::Done();
  AddNewNode<CheckNumber>({object}, Object::Conversion::kToNumber);
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), GetType(), v8::internal::maglev::IntersectType(), v8::internal::maglev::IsEmptyNodeType(), and v8::internal::Object::kToNumber.
Referenced by TryBuildNamedAccess(), and TrySpecializeStoreContextSlot().
BuildCheckNumericalValue()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValue (ValueNode * node, compiler::ObjectRef ref, DeoptimizeReason reason) [private]
Definition at line 11261 of file maglev-graph-builder.cc.
                                                                     {
  DCHECK(ref.IsSmi() || ref.IsHeapNumber());
  if (ref.IsSmi()) {
    int ref_value = ref.AsSmi();
    if (IsConstantNode(node->opcode())) {
      if (node->Is<SmiConstant>() &&
          node->Cast<SmiConstant>()->value().value() == ref_value) {
        return ReduceResult::Done();
      }
      if (node->Is<Int32Constant>() &&
          node->Cast<Int32Constant>()->value() == ref_value) {
        return ReduceResult::Done();
      }
      return EmitUnconditionalDeopt(reason);
    }
    if (NodeTypeIs(GetType(node), NodeType::kAnyHeapObject)) {
      return EmitUnconditionalDeopt(reason);
    }
    AddNewNode<CheckValueEqualsInt32>({node}, ref_value, reason);
  } else {
    DCHECK(ref.IsHeapNumber());
    Float64 ref_value = Float64::FromBits(ref.AsHeapNumber().value_as_bits());
    DCHECK(!ref_value.is_hole_nan());
    if (node->Is<Float64Constant>()) {
      Float64 f64 = node->Cast<Float64Constant>()->value();
      DCHECK(!f64.is_hole_nan());
      if (f64 == ref_value) {
        return ReduceResult::Done();
      }
      return EmitUnconditionalDeopt(reason);
    } else if (compiler::OptionalHeapObjectRef constant =
                   TryGetConstant(node)) {
      if (constant.value().IsHeapNumber()) {
        Float64 f64 =
            Float64::FromBits(constant.value().AsHeapNumber().value_as_bits());
        DCHECK(!f64.is_hole_nan());
        if (f64 == ref_value) {
          return ReduceResult::Done();
        }
      }
      return EmitUnconditionalDeopt(reason);
    }
    if (!NodeTypeIs(NodeType::kNumber, GetType(node))) {
      return EmitUnconditionalDeopt(reason);
    }
    AddNewNode<CheckFloat64SameValue>({node}, ref_value, reason);
  }
  SetKnownValue(node, ref, NodeType::kNumber);
  return ReduceResult::Done();
}
References v8::internal::maglev::NodeBase::Cast(), v8::internal::DCHECK(), v8::internal::Float64::FromBits(), v8::internal::maglev::NodeBase::Is(), v8::internal::Float64::is_hole_nan(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeBase::opcode(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), v8::internal::maglev::Int32Constant::value(), v8::internal::maglev::SmiConstant::value(), v8::internal::value, and v8::internal::Tagged< Smi >::value().
BuildCheckNumericalValueOrByReference()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckNumericalValueOrByReference (ValueNode * node, compiler::ObjectRef ref, DeoptimizeReason reason) [private]
Definition at line 11239 of file maglev-graph-builder.cc.
                                                                     {
  if (ref.IsHeapObject() && !ref.IsHeapNumber()) {
    return BuildCheckValueByReference(node, ref.AsHeapObject(), reason);
  }
  return BuildCheckNumericalValue(node, ref, reason);
}
Referenced by TryBuildPropertyCellStore(), and TrySpecializeStoreContextSlot().
BuildCheckSeqOneByteString()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckSeqOneByteString (ValueNode * object) [private]
Definition at line 4603 of file maglev-graph-builder.cc.
                                                                             {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(
          IntersectType(GetType(object), NodeType::kSeqOneByteString))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotASeqOneByteString);
  }
  if (EnsureType(object, NodeType::kSeqOneByteString, &known_type)) {
    return ReduceResult::Done();
  }
  AddNewNode<CheckSeqOneByteString>({object}, GetCheckType(known_type));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by TryBuildNamedAccess().
BuildCheckSmi()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckSmi (ValueNode * object, bool elidable = true) [private]
Definition at line 4559 of file maglev-graph-builder.cc.
                                                              {
  if (object->StaticTypeIs(broker(), NodeType::kSmi)) return object;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object), NodeType::kSmi))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kSmi);
  }
  if (EnsureType(object, NodeType::kSmi) && elidable) return object;
  switch (object->value_representation()) {
    case ValueRepresentation::kInt32:
      if (!SmiValuesAre32Bits()) {
        AddNewNode<CheckInt32IsSmi>({object});
      }
      break;
    case ValueRepresentation::kUint32:
      AddNewNode<CheckUint32IsSmi>({object});
      break;
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      AddNewNode<CheckHoleyFloat64IsSmi>({object});
      break;
    case ValueRepresentation::kTagged:
      AddNewNode<CheckSmi>({object});
      break;
    case ValueRepresentation::kIntPtr:
      AddNewNode<CheckIntPtrIsSmi>({object});
      break;
  }
  return object;
}
References broker(), EmitUnconditionalDeopt(), EnsureType(), GetType(), v8::internal::maglev::IntersectType(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::SmiValuesAre32Bits(), v8::internal::maglev::ValueNode::StaticTypeIs(), and v8::internal::maglev::ValueNode::value_representation().
Referenced by GetSmiValue(), and TrySpecializeStoreContextSlot().
BuildCheckString()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckString (ValueNode * object) [private]
Definition at line 4618 of file maglev-graph-builder.cc.
                                                                   {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object), NodeType::kString))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotAString);
  }
  if (EnsureType(object, NodeType::kString, &known_type)) {
    return ReduceResult::Done();
  }
  AddNewNode<CheckString>({object}, GetCheckType(known_type));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by BuildStringConcat(), TryBuildNamedAccess(), and VisitCompareOperation().
BuildCheckStringOrOddball()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrOddball (ValueNode * object) [private]
Definition at line 4647 of file maglev-graph-builder.cc.
                                                                            {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(
          IntersectType(GetType(object), NodeType::kStringOrOddball))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotAStringOrOddball);
  }
  if (EnsureType(object, NodeType::kStringOrOddball, &known_type)) {
    return ReduceResult::Done();
  }
  AddNewNode<CheckStringOrOddball>({object}, GetCheckType(known_type));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by VisitCompareOperation().
BuildCheckStringOrStringWrapper()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckStringOrStringWrapper (ValueNode * object) [private]
Definition at line 4632 of file maglev-graph-builder.cc.
                       {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(
          IntersectType(GetType(object), NodeType::kStringOrStringWrapper))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotAStringOrStringWrapper);
  }
  if (EnsureType(object, NodeType::kStringOrStringWrapper, &known_type))
    return ReduceResult::Done();
  AddNewNode<CheckStringOrStringWrapper>({object}, GetCheckType(known_type));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by VisitBinaryOperation().
BuildCheckSymbol()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckSymbol (ValueNode * object) [private]
Definition at line 4673 of file maglev-graph-builder.cc.
                                                                   {
  NodeType known_type;
  // Check for the empty type first so that we catch the case where
  // GetType(object) is already empty.
  if (IsEmptyNodeType(IntersectType(GetType(object), NodeType::kSymbol))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotASymbol);
  }
  if (EnsureType(object, NodeType::kSymbol, &known_type))
    return ReduceResult::Done();
  AddNewNode<CheckSymbol>({object}, GetCheckType(known_type));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetType(), v8::internal::maglev::IntersectType(), and v8::internal::maglev::IsEmptyNodeType().
Referenced by VisitCompareOperation().
BuildCheckValueByReference()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCheckValueByReference (ValueNode * node, compiler::HeapObjectRef ref, DeoptimizeReason reason) [private]
Definition at line 11219 of file maglev-graph-builder.cc.
                                                                         {
  DCHECK(!ref.IsSmi());
  DCHECK(!ref.IsHeapNumber());
  if (!IsInstanceOfNodeType(ref.map(broker()), GetType(node), broker())) {
    return EmitUnconditionalDeopt(reason);
  }
  if (compiler::OptionalHeapObjectRef maybe_constant = TryGetConstant(node)) {
    if (maybe_constant.value().equals(ref)) {
      return ReduceResult::Done();
    }
    return EmitUnconditionalDeopt(reason);
  }
  AddNewNode<CheckValue>({node}, ref, reason);
  SetKnownValue(node, ref, StaticTypeForConstant(broker(), ref));
  return ReduceResult::Done();
}
References broker(), v8::internal::DCHECK(), v8::internal::maglev::IsInstanceOfNodeType(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::maglev::StaticTypeForConstant(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
BuildCompareMaps()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildCompareMaps (ValueNode * heap_object, ValueNode * object_map, base::Vector< const compiler::MapRef > maps, MaglevSubGraphBuilder * sub_graph, std::optional< MaglevSubGraphBuilder::Label > & if_not_matched) [private]
Definition at line 4974 of file maglev-graph-builder.cc.
                                                             {
  GetOrCreateInfoFor(heap_object);
  KnownMapsMerger merger(broker(), zone(), maps);
  merger.IntersectWithKnownNodeAspects(heap_object, known_node_aspects());
  if (merger.intersect_set().is_empty()) {
    return ReduceResult::DoneWithAbort();
  }
  // TODO(pthier): Support map packing.
  DCHECK(!V8_MAP_PACKING_BOOL);
  // TODO(pthier): Handle map migrations.
  std::optional<MaglevSubGraphBuilder::Label> map_matched;
  const compiler::ZoneRefSet<Map>& relevant_maps = merger.intersect_set();
  if (relevant_maps.size() > 1) {
    map_matched.emplace(sub_graph, static_cast<int>(relevant_maps.size()));
    for (size_t map_index = 1; map_index < relevant_maps.size(); map_index++) {
      sub_graph->GotoIfTrue<BranchIfReferenceEqual>(
          &*map_matched,
          {object_map, GetConstant(relevant_maps.at(map_index))});
    }
  }
  if_not_matched.emplace(sub_graph, 1);
  sub_graph->GotoIfFalse<BranchIfReferenceEqual>(
      &*if_not_matched, {object_map, GetConstant(relevant_maps.at(0))});
  if (map_matched.has_value()) {
    sub_graph->Goto(&*map_matched);
    sub_graph->Bind(&*map_matched);
  }
  merger.UpdateKnownNodeAspects(heap_object, known_node_aspects());
  return ReduceResult::Done();
}
References v8::internal::ZoneCompactSet< T >::at(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), broker(), v8::internal::DCHECK(), v8::internal::maglev::ReduceResult::Done(), v8::internal::maglev::ReduceResult::DoneWithAbort(), GetConstant(), GetOrCreateInfoFor(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Goto(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue(), known_node_aspects(), v8::internal::ZoneCompactSet< T >::size(), V8_MAP_PACKING_BOOL, and zone().
BuildConstruct()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildConstruct (ValueNode * target, ValueNode * new_target, CallArguments & args, compiler::FeedbackSource & feedback_source) [private]
Definition at line 12447 of file maglev-graph-builder.cc.
                                             {
  compiler::ProcessedFeedback const& processed_feedback =
      broker()->GetFeedbackForCall(feedback_source);
  if (processed_feedback.IsInsufficient()) {
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kInsufficientTypeFeedbackForConstruct);
  }
  DCHECK_EQ(processed_feedback.kind(), compiler::ProcessedFeedback::kCall);
  compiler::OptionalHeapObjectRef feedback_target =
      processed_feedback.AsCall().target();
  if (feedback_target.has_value() && feedback_target->IsAllocationSite()) {
    // The feedback is an AllocationSite, which means we have called the
    // Array function and collected transition (and pretenuring) feedback
    // for the resulting arrays.
    compiler::JSFunctionRef array_function =
        broker()->target_native_context().array_function(broker());
    RETURN_IF_ABORT(BuildCheckValueByReference(
        target, array_function, DeoptimizeReason::kWrongConstructor));
    PROCESS_AND_RETURN_IF_DONE(
        TryReduceConstructArrayConstructor(array_function, args,
                                           feedback_target->AsAllocationSite()),
        SetAccumulator);
  } else {
    if (feedback_target.has_value()) {
      PROCESS_AND_RETURN_IF_DONE(
          TryReduceConstruct(feedback_target.value(), target, new_target, args,
                             feedback_source),
          SetAccumulator);
    }
    if (compiler::OptionalHeapObjectRef maybe_constant =
            TryGetConstant(target)) {
      PROCESS_AND_RETURN_IF_DONE(
          TryReduceConstruct(maybe_constant.value(), target, new_target, args,
                             feedback_source),
          SetAccumulator);
    }
  }
  ValueNode* context = GetContext();
  SetAccumulator(BuildGenericConstruct(target, new_target, context, args,
                                       feedback_source));
  return ReduceResult::Done();
}
References v8::base::args, v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), DCHECK_EQ, v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::ProcessedFeedback::kCall, v8::internal::compiler::ProcessedFeedback::kind(), PROCESS_AND_RETURN_IF_DONE, RETURN_IF_ABORT, v8::internal::compiler::CallFeedback::target(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
BuildContinuationForPolymorphicPropertyLoad()
void v8::internal::maglev::MaglevGraphBuilder::BuildContinuationForPolymorphicPropertyLoad (const ContinuationOffsets & offsets) [private]
Definition at line 7343 of file maglev-graph-builder.cc.
                                             {
  while (iterator_.current_offset() < continuation.last_continuation) {
    iterator_.Advance();
    VisitSingleBytecode();
  }
}
References v8::internal::maglev::MaglevGraphBuilder::ContinuationOffsets::last_continuation.
BuildConvertHoleToUndefined()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildConvertHoleToUndefined (ValueNode * node) [private]
Definition at line 11314 of file maglev-graph-builder.cc.
                                                                          {
  if (!node->is_tagged()) return node;
  compiler::OptionalHeapObjectRef maybe_constant = TryGetConstant(node);
  if (maybe_constant) {
    return maybe_constant.value().IsTheHole()
               ? GetRootConstant(RootIndex::kUndefinedValue)
               : node;
  }
  return AddNewNode<ConvertHoleToUndefined>({node});
}
References v8::internal::maglev::ValueNode::is_tagged(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
BuildEagerInlineCall()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildEagerInlineCall (ValueNode * context, ValueNode * function, ValueNode * new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments & args, float call_frequency) [private]
Definition at line 8579 of file maglev-graph-builder.cc.
                          {
  DCHECK_EQ(args.mode(), CallArguments::kDefault);
  // Merge catch block state if needed.
  CatchBlockDetails catch_block_details = GetCurrentTryCatchBlock();
  if (catch_block_details.ref &&
      catch_block_details.exception_handler_was_used) {
    if (IsInsideTryBlock()) {
      // Merge the current state into the handler state.
      GetCatchBlockFrameState()->MergeThrow(
          this, compilation_unit_,
          *current_interpreter_frame_.known_node_aspects(),
          current_interpreter_frame_.virtual_objects());
    }
    catch_block_details.deopt_frame_distance++;
  }
  // Create a new compilation unit.
  MaglevCompilationUnit* inner_unit = MaglevCompilationUnit::NewInner(
      zone(), compilation_unit_, shared, feedback_cell);
  // Propagate details.
  auto arguments_vector = GetArgumentsAsArrayOfValueNodes(shared, args);
  DeoptFrame* deopt_frame =
      GetDeoptFrameForEagerCall(inner_unit, function, arguments_vector);
  MaglevCallerDetails* caller_details = zone()->New<MaglevCallerDetails>(
      arguments_vector, deopt_frame,
      current_interpreter_frame_.known_node_aspects(), loop_effects_,
      unobserved_context_slot_stores_, catch_block_details, IsInsideLoop(),
      /* is_eager_inline */ true, call_frequency);
  // Create a new graph builder for the inlined function.
  MaglevGraphBuilder inner_graph_builder(local_isolate_, inner_unit, graph_,
                                         caller_details);
  // Set the inner graph builder to build in the current block.
  inner_graph_builder.current_block_ = current_block_;
  // Build inline function.
  ReduceResult result = inner_graph_builder.BuildInlineFunction(
      current_source_position_, context, function, new_target);
  // Prapagate back (or reset) builder state.
  unobserved_context_slot_stores_ =
      inner_graph_builder.unobserved_context_slot_stores_;
  latest_checkpointed_frame_.reset();
  ClearCurrentAllocationBlock();
  if (result.IsDoneWithAbort()) {
    DCHECK_NULL(inner_graph_builder.current_block_);
    current_block_ = nullptr;
    return ReduceResult::DoneWithAbort();
  }
  // Propagate frame information back to the caller.
  current_interpreter_frame_.set_known_node_aspects(
      inner_graph_builder.current_interpreter_frame_.known_node_aspects());
  current_interpreter_frame_.set_virtual_objects(
      inner_graph_builder.current_interpreter_frame_.virtual_objects());
  current_for_in_state.receiver_needs_map_check =
      inner_graph_builder.current_for_in_state.receiver_needs_map_check;
  // Resume execution using the final block of the inner builder.
  current_block_ = inner_graph_builder.current_block_;
  DCHECK(result.IsDoneWithValue());
  return result;
}
References v8::base::args, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, v8::internal::maglev::CatchBlockDetails::deopt_frame_distance, v8::internal::maglev::CatchBlockDetails::exception_handler_was_used, v8::internal::maglev::CatchBlockDetails::ref, and v8::base::internal::result.
BuildElementsArray()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildElementsArray (int length) [private]
Definition at line 12200 of file maglev-graph-builder.cc.
                                                            {
  if (length == 0) {
    return GetRootConstant(RootIndex::kEmptyFixedArray);
  }
  VirtualObject* elements =
      CreateFixedArray(broker()->fixed_array_map(), length);
  auto hole = GetRootConstant(RootIndex::kTheHoleValue);
  for (int i = 0; i < length; i++) {
    elements->set(FixedArray::OffsetOfElementAt(i), hole);
  }
  return elements;
}
References broker(), v8::internal::length, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), and v8::internal::maglev::VirtualObject::set().
BuildExtendPropertiesBackingStore()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildExtendPropertiesBackingStore (compiler::MapRef map, ValueNode * receiver, ValueNode * property_array) [private]
Definition at line 5662 of file maglev-graph-builder.cc.
                                                                        {
  int length = map.NextFreePropertyIndex() - map.GetInObjectProperties();
  // Under normal circumstances, NextFreePropertyIndex() will always be larger
  // than GetInObjectProperties(). However, an attacker able to corrupt heap
  // memory can break this invariant, in which case we'll get confused here,
  // potentially causing a sandbox violation. This CHECK defends against that.
  SBXCHECK_GE(length, 0);
  return AddNewNode<ExtendPropertiesBackingStore>({property_array, receiver},
                                                  length);
}
References v8::internal::compiler::MapRef::GetInObjectProperties(), v8::internal::length, v8::internal::compiler::MapRef::NextFreePropertyIndex(), and SBXCHECK_GE.
Referenced by TryBuildStoreField().
BuildFloat64BinaryOperationNodeForToNumber()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildFloat64BinaryOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2618 of file maglev-graph-builder.cc.
                                                   {
  // TODO(v8:7700): Do constant identity folding. Make sure to normalize
  // HoleyFloat64 nodes if folded.
  ValueNode* left = LoadRegisterHoleyFloat64ForToNumber(0, allowed_input_type,
                                                        conversion_type);
  ValueNode* right = GetAccumulatorHoleyFloat64ForToNumber(allowed_input_type,
                                                           conversion_type);
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldFloat64BinaryOperationForToNumber<kOperation>(conversion_type,
                                                           left, right),
      SetAccumulator);
  SetAccumulator(AddNewNode<Float64NodeFor<kOperation>>({left, right}));
  return ReduceResult::Done();
}
References AddNewNode(), v8::internal::maglev::ReduceResult::Done(), GetAccumulatorHoleyFloat64ForToNumber(), LoadRegisterHoleyFloat64ForToNumber(), PROCESS_AND_RETURN_IF_DONE, and SetAccumulator().
BuildFloat64BinarySmiOperationNodeForToNumber()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildFloat64BinarySmiOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2571 of file maglev-graph-builder.cc.
                                                   {
  // TODO(v8:7700): Do constant identity folding. Make sure to normalize
  // HoleyFloat64 nodes if folded.
  ValueNode* left = GetAccumulatorHoleyFloat64ForToNumber(allowed_input_type,
                                                          conversion_type);
  double constant = static_cast<double>(iterator_.GetImmediateOperand(0));
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldFloat64BinaryOperationForToNumber<kOperation>(conversion_type,
                                                           left, constant),
      SetAccumulator);
  ValueNode* right = GetFloat64Constant(constant);
  SetAccumulator(AddNewNode<Float64NodeFor<kOperation>>({left, right}));
  return ReduceResult::Done();
}
References AddNewNode(), v8::internal::maglev::ReduceResult::Done(), GetAccumulatorHoleyFloat64ForToNumber(), GetFloat64Constant(), v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), iterator_, PROCESS_AND_RETURN_IF_DONE, and SetAccumulator().
BuildFloat64UnaryOperationNodeForToNumber()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildFloat64UnaryOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2589 of file maglev-graph-builder.cc.
                                                   {
  // TODO(v8:7700): Do constant identity folding. Make sure to normalize
  // HoleyFloat64 nodes if folded.
  ValueNode* value = GetAccumulatorHoleyFloat64ForToNumber(allowed_input_type,
                                                           conversion_type);
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldFloat64UnaryOperationForToNumber<kOperation>(conversion_type,
                                                          value),
      SetAccumulator);
  switch (kOperation) {
    case Operation::kNegate:
      SetAccumulator(AddNewNode<Float64Negate>({value}));
      break;
    case Operation::kIncrement:
      SetAccumulator(AddNewNode<Float64Add>({value, GetFloat64Constant(1)}));
      break;
    case Operation::kDecrement:
      SetAccumulator(
          AddNewNode<Float64Subtract>({value, GetFloat64Constant(1)}));
      break;
    default:
      UNREACHABLE();
  }
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), GetAccumulatorHoleyFloat64ForToNumber(), GetFloat64Constant(), v8::kOperation, PROCESS_AND_RETURN_IF_DONE, SetAccumulator(), v8::internal::UNREACHABLE(), and v8::internal::value.
BuildGenericBinaryOperationNode()
template<Operation kOperation>
void v8::internal::maglev::MaglevGraphBuilder::BuildGenericBinaryOperationNode [private]
Definition at line 2284 of file maglev-graph-builder.cc.
                                                         {
  ValueNode* left = LoadRegister(0);
  ValueNode* right = GetAccumulator();
  FeedbackSlot slot_index = GetSlotOperand(1);
  SetAccumulator(AddNewNode<GenericNodeForOperation<kOperation>>(
      {left, right}, compiler::FeedbackSource{feedback(), slot_index}));
}
References AddNewNode(), feedback(), GetAccumulator(), GetSlotOperand(), LoadRegister(), and SetAccumulator().
BuildGenericBinarySmiOperationNode()
template<Operation kOperation>
void v8::internal::maglev::MaglevGraphBuilder::BuildGenericBinarySmiOperationNode [private]
Definition at line 2293 of file maglev-graph-builder.cc.
                                                            {
  ValueNode* left = GetAccumulator();
  int constant = iterator_.GetImmediateOperand(0);
  ValueNode* right = GetSmiConstant(constant);
  FeedbackSlot slot_index = GetSlotOperand(1);
  SetAccumulator(AddNewNode<GenericNodeForOperation<kOperation>>(
      {left, right}, compiler::FeedbackSource{feedback(), slot_index}));
}
References AddNewNode(), feedback(), GetAccumulator(), v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), GetSlotOperand(), GetSmiConstant(), iterator_, and SetAccumulator().
BuildGenericCall()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildGenericCall (ValueNode * target, Call::TargetType target_type, const CallArguments & args) [private]
Definition at line 10924 of file maglev-graph-builder.cc.
                                                                           {
  // TODO(victorgomes): We do not collect call feedback from optimized/inlined
  // calls. In order to be consistent, we don't pass the feedback_source to the
  // IR, so that we avoid collecting for generic calls as well. We might want to
  // revisit this in the future.
  switch (args.mode()) {
    case CallArguments::kDefault:
      return AddNewCallNode<Call>(args, args.receiver_mode(), target_type,
                                  GetTaggedValue(target),
                                  GetTaggedValue(GetContext()));
    case CallArguments::kWithSpread:
      DCHECK_EQ(args.receiver_mode(), ConvertReceiverMode::kAny);
      return AddNewCallNode<CallWithSpread>(args, GetTaggedValue(target),
                                            GetTaggedValue(GetContext()));
    case CallArguments::kWithArrayLike:
      DCHECK_EQ(args.receiver_mode(), ConvertReceiverMode::kAny);
      // We don't use AddNewCallNode here, because the number of required
      // arguments is known statically.
      return AddNewNode<CallWithArrayLike>(
          {target, GetValueOrUndefined(args.receiver()), args[0],
           GetContext()});
  }
}
References v8::base::args, DCHECK_EQ, and v8::internal::kAny.
BuildGenericConstruct()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildGenericConstruct (ValueNode * target, ValueNode * new_target, ValueNode * context, const CallArguments & args, const compiler::FeedbackSource & feedback_source = compiler::FeedbackSource()) [private]
Definition at line 12069 of file maglev-graph-builder.cc.
                                                   {
  size_t input_count = args.count_with_receiver() + Construct::kFixedInputCount;
  DCHECK_EQ(args.receiver_mode(), ConvertReceiverMode::kNullOrUndefined);
  return AddNewNode<Construct>(
      input_count,
      [&](Construct* construct) {
        int arg_index = 0;
        // Add undefined receiver.
        construct->set_arg(arg_index++,
                           GetRootConstant(RootIndex::kUndefinedValue));
        for (size_t i = 0; i < args.count(); i++) {
          construct->set_arg(arg_index++, GetTaggedValue(args[i]));
        }
      },
      feedback_source, GetTaggedValue(target), GetTaggedValue(new_target),
      GetTaggedValue(context));
}
References v8::base::args, DCHECK_EQ, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::kNullOrUndefined, and v8::internal::maglev::Construct::set_arg().
BuildGenericUnaryOperationNode()
template<Operation kOperation>
void v8::internal::maglev::MaglevGraphBuilder::BuildGenericUnaryOperationNode [private]
Definition at line 2276 of file maglev-graph-builder.cc.
                                                        {
  FeedbackSlot slot_index = GetSlotOperand(0);
  ValueNode* value = GetAccumulator();
  SetAccumulator(AddNewNode<GenericNodeForOperation<kOperation>>(
      {value}, compiler::FeedbackSource{feedback(), slot_index}));
}
References AddNewNode(), feedback(), GetAccumulator(), GetSlotOperand(), SetAccumulator(), and v8::internal::value.
BuildGetKeyedProperty()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildGetKeyedProperty (ValueNode * object, const compiler::FeedbackSource & feedback_source, const compiler::ProcessedFeedback & processed_feedback) [private]
Definition at line 7616 of file maglev-graph-builder.cc.
                                                         {
  RETURN_IF_DONE(TryBuildGetKeyedPropertyWithEnumeratedKey(
      object, feedback_source, processed_feedback));
  auto build_generic_access = [this, object, &feedback_source]() {
    ValueNode* context = GetContext();
    ValueNode* key = GetAccumulator();
    return AddNewNode<GetKeyedGeneric>({context, object, key}, feedback_source);
  };
  switch (processed_feedback.kind()) {
    case compiler::ProcessedFeedback::kInsufficient:
      return EmitUnconditionalDeopt(
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericKeyedAccess);
    case compiler::ProcessedFeedback::kElementAccess: {
      // Get the accumulator without conversion. TryBuildElementAccess
      // will try to pick the best representation.
      ValueNode* index = current_interpreter_frame_.accumulator();
      MaybeReduceResult result = TryBuildElementAccess(
          object, index, processed_feedback.AsElementAccess(), feedback_source,
          build_generic_access);
      PROCESS_AND_RETURN_IF_DONE(result, SetAccumulator);
      break;
    }
    case compiler::ProcessedFeedback::kNamedAccess: {
      ValueNode* key = GetAccumulator();
      compiler::NameRef name = processed_feedback.AsNamedAccess().name();
      RETURN_IF_ABORT(BuildCheckInternalizedStringValueOrByReference(
          key, name, DeoptimizeReason::kKeyedAccessChanged));
      MaybeReduceResult result = TryReuseKnownPropertyLoad(object, name);
      PROCESS_AND_RETURN_IF_DONE(result, SetAccumulator);
      result = TryBuildNamedAccess(
          object, object, processed_feedback.AsNamedAccess(), feedback_source,
          compiler::AccessMode::kLoad, build_generic_access);
      PROCESS_AND_RETURN_IF_DONE(result, SetAccumulator);
      break;
    }
    default:
      break;
  }
  // Create a generic load in the fallthrough.
  SetAccumulator(build_generic_access());
  return ReduceResult::Done();
}
References v8::internal::compiler::ProcessedFeedback::AsElementAccess(), v8::internal::compiler::ProcessedFeedback::AsNamedAccess(), v8::internal::index, v8::internal::compiler::ProcessedFeedback::kElementAccess, v8::internal::key, v8::internal::compiler::ProcessedFeedback::kind(), v8::internal::compiler::ProcessedFeedback::kInsufficient, v8::internal::compiler::kLoad, v8::internal::compiler::ProcessedFeedback::kNamedAccess, v8::internal::compiler::NamedAccessFeedback::name(), v8::internal::name, PROCESS_AND_RETURN_IF_DONE, v8::base::internal::result, RETURN_IF_ABORT, and RETURN_IF_DONE.
BuildHasInPrototypeChain()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildHasInPrototypeChain (ValueNode * object, compiler::HeapObjectRef prototype) [private]
Definition at line 12662 of file maglev-graph-builder.cc.
                                                        {
  RETURN_IF_DONE(TryBuildFastHasInPrototypeChain(object, prototype));
  return AddNewNode<HasInPrototypeChain>({object}, prototype);
}
References v8::internal::prototype, and RETURN_IF_DONE.
BuildInitializeStore()
void v8::internal::maglev::MaglevGraphBuilder::BuildInitializeStore (InlinedAllocation * alloc, ValueNode * value, int offset) [private]
Definition at line 5087 of file maglev-graph-builder.cc.
                                                                            {
  const bool value_is_trusted = value->Is<TrustedConstant>();
  DCHECK(value->is_tagged());
  if (InlinedAllocation* inlined_value = value->TryCast<InlinedAllocation>()) {
    // Add to the escape set.
    auto escape_deps = graph()->allocations_escape_map().find(object);
    CHECK(escape_deps != graph()->allocations_escape_map().end());
    escape_deps->second.push_back(inlined_value);
    // Add to the elided set.
    auto& elided_map = graph()->allocations_elide_map();
    auto elided_deps = elided_map.try_emplace(inlined_value, zone()).first;
    elided_deps->second.push_back(object);
    inlined_value->AddNonEscapingUses();
  }
  if (value_is_trusted) {
    BuildStoreTrustedPointerField(object, value, offset,
                                  value->Cast<TrustedConstant>()->tag(),
                                  StoreTaggedMode::kInitializing);
  } else {
    BuildStoreTaggedField(object, value, offset,
                          StoreTaggedMode::kInitializing);
  }
}
References v8::internal::maglev::Graph::allocations_elide_map(), v8::internal::maglev::Graph::allocations_escape_map(), BuildStoreTaggedField(), BuildStoreTrustedPointerField(), CHECK, v8::internal::DCHECK(), v8::internal::compiler::end(), graph(), v8::internal::maglev::kInitializing, v8::internal::maglev::TrustedConstant::tag(), v8::internal::value, and zone().
BuildInlinedAllocation()
InlinedAllocation * v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation (VirtualObject * object, AllocationType allocation) [private]
Definition at line 13752 of file maglev-graph-builder.cc.
                                                            {
  current_interpreter_frame_.add_object(vobject);
  InlinedAllocation* allocation;
  switch (vobject->type()) {
    case VirtualObject::kHeapNumber:
      allocation =
          BuildInlinedAllocationForHeapNumber(vobject, allocation_type);
      break;
    case VirtualObject::kFixedDoubleArray:
      allocation =
          BuildInlinedAllocationForDoubleFixedArray(vobject, allocation_type);
      break;
    case VirtualObject::kConsString:
      allocation =
          BuildInlinedAllocationForConsString(vobject, allocation_type);
      break;
    case VirtualObject::kDefault: {
      SmallZoneVector<ValueNode*, 8> values(zone());
      vobject->ForEachInput([&](ValueNode*& node) {
        ValueNode* value_to_push;
        if (node->Is<VirtualObject>()) {
          VirtualObject* nested = node->Cast<VirtualObject>();
          node = BuildInlinedAllocation(nested, allocation_type);
          value_to_push = node;
        } else if (node->Is<Float64Constant>()) {
          value_to_push = BuildInlinedAllocationForHeapNumber(
              CreateHeapNumber(node->Cast<Float64Constant>()->value()),
              allocation_type);
        } else {
          value_to_push = GetTaggedValue(node);
        }
        values.push_back(value_to_push);
      });
      allocation =
          ExtendOrReallocateCurrentAllocationBlock(allocation_type, vobject);
      AddNonEscapingUses(allocation, static_cast<int>(values.size()));
      if (vobject->has_static_map()) {
        AddNonEscapingUses(allocation, 1);
        BuildStoreMap(allocation, vobject->map(),
                      StoreMap::Kind::kInlinedAllocation);
      }
      for (uint32_t i = 0; i < values.size(); i++) {
        BuildInitializeStore(allocation, values[i], (i + 1) * kTaggedSize);
      }
      if (is_loop_effect_tracking()) {
        loop_effects_->allocations.insert(allocation);
      }
      break;
    }
  }
  if (v8_flags.maglev_allocation_folding < 2) {
    ClearCurrentAllocationBlock();
  }
  return allocation;
}
References v8::internal::maglev::VirtualObject::ForEachInput(), v8::internal::maglev::VirtualObject::has_static_map(), v8::internal::if(), v8::internal::maglev::NodeBase::Is(), v8::internal::kTaggedSize, v8::internal::maglev::VirtualObject::map(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::maglev::VirtualObject::type(), and v8::internal::v8_flags.
Referenced by TryBuildNewConsString().
BuildInlinedAllocationForConsString()
InlinedAllocation * v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForConsString (VirtualObject * object, AllocationType allocation) [private]
Definition at line 13690 of file maglev-graph-builder.cc.
                                                            {
  InlinedAllocation* allocation =
      ExtendOrReallocateCurrentAllocationBlock(allocation_type, vobject);
  DCHECK_EQ(vobject->size(), sizeof(ConsString));
  DCHECK_EQ(vobject->cons_string().length->value_representation(),
            ValueRepresentation::kInt32);
  AddNonEscapingUses(allocation, 5);
  BuildInitializeStore(allocation, vobject->cons_string().map,
                       HeapObject::kMapOffset);
  AddNewNode<StoreInt32>(
      {allocation, GetInt32Constant(Name::kEmptyHashField)},
      static_cast<int>(offsetof(ConsString, raw_hash_field_)));
  AddNewNode<StoreInt32>({allocation, vobject->cons_string().length},
                         static_cast<int>(offsetof(ConsString, length_)));
  BuildInitializeStore(allocation, vobject->cons_string().first(),
                       offsetof(ConsString, first_));
  BuildInitializeStore(allocation, vobject->cons_string().second(),
                       offsetof(ConsString, second_));
  if (is_loop_effect_tracking()) {
    loop_effects_->allocations.insert(allocation);
  }
  return allocation;
}
References v8::internal::maglev::VirtualObject::cons_string(), DCHECK_EQ, v8::internal::maglev::VirtualObject::VirtualConsString::first(), v8::internal::Name::kEmptyHashField, v8::internal::HeapObject::kMapOffset, v8::internal::length, v8::internal::maglev::VirtualObject::VirtualConsString::length, v8::internal::maglev::VirtualObject::VirtualConsString::map, v8::internal::maglev::VirtualObject::VirtualConsString::second(), v8::internal::maglev::VirtualObject::size(), and v8::internal::maglev::ValueNode::value_representation().
BuildInlinedAllocationForDoubleFixedArray()
InlinedAllocation * v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForDoubleFixedArray (VirtualObject * object, AllocationType allocation) [private]
Definition at line 13729 of file maglev-graph-builder.cc.
                                                            {
  DCHECK(vobject->map().IsFixedDoubleArrayMap());
  InlinedAllocation* allocation =
      ExtendOrReallocateCurrentAllocationBlock(allocation_type, vobject);
  int length = vobject->double_elements_length();
  AddNonEscapingUses(allocation, length + 2);
  BuildStoreMap(allocation, broker()->fixed_double_array_map(),
                StoreMap::Kind::kInlinedAllocation);
  AddNewNode<StoreTaggedFieldNoWriteBarrier>(
      {allocation, GetSmiConstant(length)},
      static_cast<int>(offsetof(FixedDoubleArray, length_)),
      StoreTaggedMode::kDefault);
  for (int i = 0; i < length; ++i) {
    AddNewNode<StoreFloat64>(
        {allocation,
         GetFloat64Constant(
             vobject->double_elements().GetFromImmutableFixedDoubleArray(i))},
        FixedDoubleArray::OffsetOfElementAt(i));
  }
  return allocation;
}
References broker(), v8::internal::DCHECK(), v8::internal::maglev::VirtualObject::double_elements(), v8::internal::maglev::VirtualObject::double_elements_length(), v8::internal::compiler::FixedDoubleArrayRef::GetFromImmutableFixedDoubleArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::length, v8::internal::maglev::VirtualObject::map(), and v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::OffsetOfElementAt().
BuildInlinedAllocationForHeapNumber()
InlinedAllocation * v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForHeapNumber (VirtualObject * object, AllocationType allocation) [private]
Definition at line 13715 of file maglev-graph-builder.cc.
                                                            {
  DCHECK(vobject->map().IsHeapNumberMap());
  InlinedAllocation* allocation =
      ExtendOrReallocateCurrentAllocationBlock(allocation_type, vobject);
  AddNonEscapingUses(allocation, 2);
  BuildStoreMap(allocation, broker()->heap_number_map(),
                StoreMap::Kind::kInlinedAllocation);
  AddNewNode<StoreFloat64>({allocation, GetFloat64Constant(vobject->number())},
                           static_cast<int>(offsetof(HeapNumber, value_)));
  return allocation;
}
References broker(), v8::internal::DCHECK(), v8::internal::maglev::VirtualObject::map(), and v8::internal::maglev::VirtualObject::number().
BuildInlinedArgumentsElements()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildInlinedArgumentsElements (int start_index, int length) [private]
Definition at line 13809 of file maglev-graph-builder.cc.
                                                                         {
  DCHECK(is_inline());
  if (length == 0) {
    return GetRootConstant(RootIndex::kEmptyFixedArray);
  }
  VirtualObject* elements =
      CreateFixedArray(broker()->fixed_array_map(), length);
  for (int i = 0; i < length; i++) {
    elements->set(FixedArray::OffsetOfElementAt(i),
                  caller_details_->arguments[i + start_index + 1]);
  }
  return elements;
}
References broker(), v8::internal::DCHECK(), v8::internal::length, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), and v8::internal::maglev::VirtualObject::set().
BuildInlinedUnmappedArgumentsElements()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildInlinedUnmappedArgumentsElements (int mapped_count) [private]
Definition at line 13824 of file maglev-graph-builder.cc.
                      {
  int length = argument_count_without_receiver();
  if (length == 0) {
    return GetRootConstant(RootIndex::kEmptyFixedArray);
  }
  VirtualObject* unmapped_elements =
      CreateFixedArray(broker()->fixed_array_map(), length);
  int i = 0;
  for (; i < mapped_count; i++) {
    unmapped_elements->set(FixedArray::OffsetOfElementAt(i),
                           GetRootConstant(RootIndex::kTheHoleValue));
  }
  for (; i < length; i++) {
    unmapped_elements->set(FixedArray::OffsetOfElementAt(i),
                           caller_details_->arguments[i + 1]);
  }
  return unmapped_elements;
}
References broker(), v8::internal::length, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), and v8::internal::maglev::VirtualObject::set().
BuildInlineFunction()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction (SourcePosition call_site_position, ValueNode * context, ValueNode * function, ValueNode * new_target)
Definition at line 8324 of file maglev-graph-builder.cc.
                           {
  DCHECK(is_inline());
  DCHECK_GT(caller_details_->arguments.size(), 0);
  compiler::SharedFunctionInfoRef shared =
      compilation_unit_->shared_function_info();
  compiler::BytecodeArrayRef bytecode = compilation_unit_->bytecode();
  compiler::FeedbackVectorRef feedback = compilation_unit_->feedback();
  if (v8_flags.maglev_print_inlined &&
      TopLevelFunctionPassMaglevPrintFilter() &&
      (v8_flags.print_maglev_code || v8_flags.print_maglev_graph ||
       v8_flags.print_maglev_graphs ||
       v8_flags.trace_maglev_inlining_verbose)) {
    std::cout << "== Inlining " << Brief(*shared.object()) << std::endl;
    BytecodeArray::Disassemble(bytecode.object(), std::cout);
    if (v8_flags.maglev_print_feedback) {
      i::Print(*feedback.object(), std::cout);
    }
  } else if (v8_flags.trace_maglev_graph_building ||
             v8_flags.trace_maglev_inlining) {
    std::cout << "== Inlining " << shared.object() << std::endl;
  }
  graph()->inlined_functions().push_back(
      OptimizedCompilationInfo::InlinedFunctionHolder(
          shared.object(), bytecode.object(), call_site_position));
  if (feedback.object()->invocation_count_before_stable(kRelaxedLoad) >
      v8_flags.invocation_count_for_early_optimization) {
    compilation_unit_->info()->set_could_not_inline_all_candidates();
  }
  inlining_id_ = static_cast<int>(graph()->inlined_functions().size() - 1);
  DCHECK_NE(inlining_id_, SourcePosition::kNotInlined);
  current_source_position_ = SourcePosition(
      compilation_unit_->shared_function_info().StartPosition(), inlining_id_);
  // Manually create the prologue of the inner function graph, so that we
  // can manually set up the arguments.
  DCHECK_NOT_NULL(current_block_);
  // Set receiver.
  SetArgument(0, caller_details_->arguments[0]);
  // The inlined function could call a builtin that iterates the frame, the
  // receiver needs to have been materialized.
  // TODO(victorgomes): Can we relax this requirement? Maybe we can allocate the
  // object lazily? This is also only required if the inlined function is not a
  // leaf (ie. it calls other functions).
  ForceEscapeIfAllocation(caller_details_->arguments[0]);
  // Set remaining arguments.
  RootConstant* undefined_constant =
      GetRootConstant(RootIndex::kUndefinedValue);
  int args_count = static_cast<int>(caller_details_->arguments.size()) - 1;
  int formal_parameter_count = compilation_unit_->parameter_count() - 1;
  for (int i = 0; i < formal_parameter_count; i++) {
    ValueNode* arg_value =
        i < args_count ? caller_details_->arguments[i + 1] : undefined_constant;
    SetArgument(i + 1, arg_value);
  }
  inlined_new_target_ = new_target;
  BuildRegisterFrameInitialization(context, function, new_target);
  BuildMergeStates();
  EndPrologue();
  in_prologue_ = false;
  // Build the inlined function body.
  BuildBody();
  // All returns in the inlined body jump to a merge point one past the bytecode
  // length (i.e. at offset bytecode.length()). If there isn't one already,
  // create a block at this fake offset and have it jump out of the inlined
  // function, into a new block that we create which resumes execution of the
  // outer function.
  if (!current_block_) {
    // If we don't have a merge state at the inline_exit_offset, then there is
    // no control flow that reaches the end of the inlined function, either
    // because of infinite loops or deopts
    if (merge_states_[inline_exit_offset()] == nullptr) {
      if (v8_flags.trace_maglev_graph_building) {
        std::cout << "== Finished inlining (abort) " << shared.object()
                  << std::endl;
      }
      return ReduceResult::DoneWithAbort();
    }
    ProcessMergePoint(inline_exit_offset(), /*preserve_kna*/ false);
    StartNewBlock(inline_exit_offset(), /*predecessor*/ nullptr);
  }
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << "== Finished inlining " << shared.object() << std::endl;
  }
  // Pull the returned accumulator value out of the inlined function's final
  // merged return state.
  return current_interpreter_frame_.accumulator();
}
References v8::internal::DCHECK(), DCHECK_GT, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::BytecodeArray::Disassemble(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::ForceEscapeIfAllocation(), graph(), v8::internal::SourcePosition::kNotInlined, v8::kRelaxedLoad, v8::internal::compiler::FeedbackVectorRef::object(), v8::internal::compiler::BytecodeArrayRef::object(), v8::internal::compiler::SharedFunctionInfoRef::object(), v8::internal::Print(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
BuildInt32BinaryOperationNode()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildInt32BinaryOperationNode [private]
Definition at line 2424 of file maglev-graph-builder.cc.
                                                               {
  // Use BuildTruncatingInt32BinaryOperationNodeForToNumber with Smi input hint
  // for truncating operations.
  static_assert(!BinaryOperationIsBitwiseInt32<kOperation>());
  ValueNode* left = LoadRegister(0);
  ValueNode* right = GetAccumulator();
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldInt32BinaryOperation<kOperation>(left, right), SetAccumulator);
  using OpNodeT = Int32NodeFor<kOperation>;
  SetAccumulator(AddNewNode<OpNodeT>({left, right}));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), GetAccumulator(), LoadRegister(), PROCESS_AND_RETURN_IF_DONE, and SetAccumulator().
BuildInt32BinarySmiOperationNode()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildInt32BinarySmiOperationNode [private]
Definition at line 2464 of file maglev-graph-builder.cc.
                                                                  {
  // Truncating Int32 nodes treat their input as a signed int32 regardless
  // of whether it's really signed or not, so we allow Uint32 by loading a
  // TruncatedInt32 value.
  static_assert(!BinaryOperationIsBitwiseInt32<kOperation>());
  ValueNode* left = GetAccumulator();
  int32_t constant = iterator_.GetImmediateOperand(0);
  if (std::optional<int>(constant) == Int32Identity<kOperation>()) {
    // Deopt if {left} is not an Int32.
    EnsureInt32(left);
    // If the constant is the unit of the operation, it already has the right
    // value, so just return.
    return ReduceResult::Done();
  }
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldInt32BinaryOperation<kOperation>(left, constant), SetAccumulator);
  ValueNode* right = GetInt32Constant(constant);
  using OpNodeT = Int32NodeFor<kOperation>;
  SetAccumulator(AddNewNode<OpNodeT>({left, right}));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), EnsureInt32(), GetAccumulator(), v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), GetInt32Constant(), iterator_, PROCESS_AND_RETURN_IF_DONE, and SetAccumulator().
BuildInt32UnaryOperationNode()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildInt32UnaryOperationNode [private]
Definition at line 2334 of file maglev-graph-builder.cc.
                                                              {
  // Use BuildTruncatingInt32BitwiseNotForToNumber with Smi input hint
  // for truncating operations.
  static_assert(!BinaryOperationIsBitwiseInt32<kOperation>());
  ValueNode* value = GetAccumulator();
  PROCESS_AND_RETURN_IF_DONE(TryFoldInt32UnaryOperation<kOperation>(value),
                             SetAccumulator);
  using OpNodeT = Int32NodeFor<kOperation>;
  SetAccumulator(AddNewNode<OpNodeT>({value}));
  return ReduceResult::Done();
}
References v8::internal::maglev::ReduceResult::Done(), GetAccumulator(), PROCESS_AND_RETURN_IF_DONE, SetAccumulator(), and v8::internal::value.
BuildJSArrayBuiltinMapSwitchOnElementsKind()
template<typename MapKindsT , typename IndexToElementsKindFunc , typename BuildKindSpecificFunc >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildJSArrayBuiltinMapSwitchOnElementsKind (ValueNode * receiver, const MapKindsT & map_kinds, MaglevSubGraphBuilder & sub_graph, std::optional< MaglevSubGraphBuilder::Label > & do_return, int unique_kind_count, IndexToElementsKindFunc && index_to_elements_kind, BuildKindSpecificFunc && build_kind_specific) [private]
Definition at line 9948 of file maglev-graph-builder.cc.
                                                 {
  // TODO(pthier): Support map packing.
  DCHECK(!V8_MAP_PACKING_BOOL);
  ValueNode* receiver_map =
      BuildLoadTaggedField(receiver, HeapObject::kMapOffset);
  int emitted_kind_checks = 0;
  bool any_successful = false;
  for (size_t kind_index = 0; kind_index < map_kinds.size(); kind_index++) {
    const auto& maps = map_kinds[kind_index];
    // Skip kinds we haven't observed.
    if (maps.empty()) continue;
    ElementsKind kind = index_to_elements_kind(kind_index);
    // Create branches for all but the last elements kind. We don't need
    // to check the maps of the last kind, as all possible maps have already
    // been checked when the property (builtin name) was loaded.
    if (++emitted_kind_checks < unique_kind_count) {
      MaglevSubGraphBuilder::Label check_next_map(&sub_graph, 1);
      std::optional<MaglevSubGraphBuilder::Label> do_push;
      if (maps.size() > 1) {
        do_push.emplace(&sub_graph, static_cast<int>(maps.size()));
        for (size_t map_index = 1; map_index < maps.size(); map_index++) {
          sub_graph.GotoIfTrue<BranchIfReferenceEqual>(
              &*do_push, {receiver_map, GetConstant(maps[map_index])});
        }
      }
      sub_graph.GotoIfFalse<BranchIfReferenceEqual>(
          &check_next_map, {receiver_map, GetConstant(maps[0])});
      if (do_push.has_value()) {
        sub_graph.Goto(&*do_push);
        sub_graph.Bind(&*do_push);
      }
      if (!build_kind_specific(kind).IsDoneWithAbort()) {
        any_successful = true;
      }
      DCHECK(do_return.has_value());
      sub_graph.GotoOrTrim(&*do_return);
      sub_graph.Bind(&check_next_map);
    } else {
      if (!build_kind_specific(kind).IsDoneWithAbort()) {
        any_successful = true;
      }
      if (do_return.has_value()) {
        sub_graph.GotoOrTrim(&*do_return);
      }
    }
  }
  DCHECK_IMPLIES(!any_successful, !current_block_);
  return any_successful ? ReduceResult::Done() : ReduceResult::DoneWithAbort();
}
References v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Goto(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoOrTrim(), v8::internal::HeapObject::kMapOffset, and V8_MAP_PACKING_BOOL.
BuildLoadConstantTypedArrayElement()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadConstantTypedArrayElement (compiler::JSTypedArrayRef typed_array, ValueNode * index, ElementsKind elements_kind) [private]
Definition at line 6370 of file maglev-graph-builder.cc.
                                {
#define BUILD_AND_RETURN_LOAD_CONSTANT_TYPED_ARRAY(Type) \
  return AddNewNode<Load##Type##ConstantTypedArrayElement>(\
      {index}, typed_array, elements_kind);
  switch (elements_kind) {
    case INT8_ELEMENTS:
    case INT16_ELEMENTS:
    case INT32_ELEMENTS:
      BUILD_AND_RETURN_LOAD_CONSTANT_TYPED_ARRAY(SignedInt);
    case UINT8_CLAMPED_ELEMENTS:
    case UINT8_ELEMENTS:
    case UINT16_ELEMENTS:
    case UINT32_ELEMENTS:
      BUILD_AND_RETURN_LOAD_CONSTANT_TYPED_ARRAY(UnsignedInt);
    case FLOAT32_ELEMENTS:
    case FLOAT64_ELEMENTS:
      BUILD_AND_RETURN_LOAD_CONSTANT_TYPED_ARRAY(Double);
    default:
      UNREACHABLE();
  }
#undef BUILD_AND_RETURN_LOAD_CONSTANTTYPED_ARRAY
}
References BUILD_AND_RETURN_LOAD_CONSTANT_TYPED_ARRAY, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, and v8::internal::UNREACHABLE().
BuildLoadContextSlot()
void v8::internal::maglev::MaglevGraphBuilder::BuildLoadContextSlot (ValueNode * context, size_t depth, int slot_index, ContextSlotMutability slot_mutability, ContextMode context_mode) [private]
Definition at line 3781 of file maglev-graph-builder.cc.
                                                                     {
  context = GetContextAtDepth(context, depth);
  if (compilation_unit_->info()->specialize_to_function_context() &&
      TrySpecializeLoadContextSlotToFunctionContext(context, slot_index,
                                                    slot_mutability)) {
    return; // Our work here is done.
  }
  // Always load the slot here as if it were mutable. Immutable slots have a
  // narrow range of mutability if the context escapes before the slot is
  // initialized, so we can't safely assume that the load can be cached in case
  // it's a load before initialization (e.g. var a = a + 42).
  current_interpreter_frame_.set_accumulator(
      LoadAndCacheContextSlot(context, slot_index, kMutable, context_mode));
}
References compilation_unit_, current_interpreter_frame_, GetContextAtDepth(), v8::internal::maglev::MaglevCompilationUnit::info(), kMutable, LoadAndCacheContextSlot(), v8::internal::maglev::InterpreterFrameState::set_accumulator(), v8::internal::maglev::MaglevCompilationInfo::specialize_to_function_context(), and TrySpecializeLoadContextSlotToFunctionContext().
BuildLoadElements()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadElements (ValueNode * object) [private]
Definition at line 6285 of file maglev-graph-builder.cc.
                                                                  {
  MaybeReduceResult known_elements =
      TryFindLoadedProperty(known_node_aspects().loaded_properties, object,
                            KnownNodeAspects::LoadedPropertyMapKey::Elements());
  if (known_elements.IsDone()) {
    DCHECK(known_elements.IsDoneWithValue());
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " * Reusing non-constant [Elements] "
                << PrintNodeLabel(graph_labeller(), known_elements.value())
                << ": " << PrintNode(graph_labeller(), known_elements.value())
                << std::endl;
    }
    return known_elements.value();
  }
  DCHECK_EQ(JSObject::kElementsOffset, JSArray::kElementsOffset);
  ValueNode* elements = BuildLoadTaggedField(object, JSObject::kElementsOffset);
  RecordKnownProperty(object,
                      KnownNodeAspects::LoadedPropertyMapKey::Elements(),
                      elements, false, compiler::AccessMode::kLoad);
  return elements;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::maglev::MaybeReduceResult::IsDoneWithValue(), v8::internal::compiler::kLoad, v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::TryFindLoadedProperty(), v8::internal::v8_flags, and v8::internal::maglev::MaybeReduceResult::value().
BuildLoadField()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadField (compiler::PropertyAccessInfo const & access_info, ValueNode * lookup_start_object, compiler::NameRef name) [private]
Definition at line 5533 of file maglev-graph-builder.cc.
                                                          {
  compiler::OptionalJSObjectRef constant_holder =
      TryGetConstantDataFieldHolder(access_info, lookup_start_object);
  if (constant_holder) {
    if (access_info.field_representation().IsDouble()) {
      std::optional<Float64> constant =
          TryFoldLoadConstantDoubleField(constant_holder.value(), access_info);
      if (constant.has_value()) {
        return GetFloat64Constant(constant.value());
      }
    } else {
      compiler::OptionalObjectRef constant =
          TryFoldLoadConstantDataField(constant_holder.value(), access_info);
      if (constant.has_value()) {
        return GetConstant(constant.value());
      }
    }
  }
  // Resolve property holder.
  ValueNode* load_source;
  if (access_info.holder().has_value()) {
    load_source = GetConstant(access_info.holder().value());
  } else {
    load_source = lookup_start_object;
  }
  FieldIndex field_index = access_info.field_index();
  if (!field_index.is_inobject()) {
    // The field is in the property array, first load it from there.
    load_source =
        BuildLoadTaggedField(load_source, JSReceiver::kPropertiesOrHashOffset);
  }
  // Do the load.
  if (field_index.is_double()) {
    return AddNewNode<LoadDoubleField>({load_source}, field_index.offset());
  }
  ValueNode* value = BuildLoadTaggedField<LoadTaggedFieldForProperty>(
      load_source, field_index.offset(), name);
  // Insert stable field information if present.
  if (access_info.field_representation().IsSmi()) {
    NodeInfo* known_info = GetOrCreateInfoFor(value);
    known_info->IntersectType(NodeType::kSmi);
  } else if (access_info.field_representation().IsHeapObject()) {
    NodeInfo* known_info = GetOrCreateInfoFor(value);
    if (access_info.field_map().has_value() &&
        access_info.field_map().value().is_stable()) {
      DCHECK(access_info.field_map().value().IsJSReceiverMap());
      auto map = access_info.field_map().value();
      known_info->SetPossibleMaps(PossibleMaps{map}, false,
                                  StaticTypeForMap(map, broker()), broker());
      broker()->dependencies()->DependOnStableMap(map);
    } else {
      known_info->IntersectType(NodeType::kAnyHeapObject);
    }
  }
  return value;
}
References broker(), BuildLoadTaggedField(), v8::internal::DCHECK(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_map(), v8::internal::compiler::PropertyAccessInfo::field_representation(), GetConstant(), GetFloat64Constant(), GetOrCreateInfoFor(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::maglev::NodeInfo::IntersectType(), v8::internal::FieldIndex::is_double(), v8::internal::FieldIndex::is_inobject(), v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), v8::internal::Representation::IsSmi(), v8::internal::compiler::kSmi, v8::internal::name, v8::internal::FieldIndex::offset(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), v8::internal::maglev::StaticTypeForMap(), TryFoldLoadConstantDataField(), TryFoldLoadConstantDoubleField(), TryGetConstantDataFieldHolder(), and v8::internal::value.
Referenced by TryBuildPropertyLoad().
BuildLoadFixedArrayElement() [1/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement (ValueNode * elements, int index) [private]
Definition at line 5294 of file maglev-graph-builder.cc.
                                                                     {
  compiler::OptionalHeapObjectRef maybe_constant;
  if ((maybe_constant = TryGetConstant(elements)) &&
      maybe_constant.value().IsFixedArray()) {
    compiler::FixedArrayRef fixed_array_ref =
        maybe_constant.value().AsFixedArray();
    if (index >= 0 && static_cast<uint32_t>(index) < fixed_array_ref.length()) {
      compiler::OptionalObjectRef maybe_value =
          fixed_array_ref.TryGet(broker(), index);
      if (maybe_value) return GetConstant(*maybe_value);
    } else {
      return GetRootConstant(RootIndex::kTheHoleValue);
    }
  }
  if (CanTrackObjectChanges(elements, TrackObjectMode::kLoad)) {
    VirtualObject* vobject =
        GetObjectFromAllocation(elements->Cast<InlinedAllocation>());
    CHECK_EQ(vobject->type(), VirtualObject::kDefault);
    DCHECK(vobject->map().IsFixedArrayMap());
    ValueNode* length_node = vobject->get(offsetof(FixedArray, length_));
    if (auto length = TryGetInt32Constant(length_node)) {
      if (index >= 0 && index < length.value()) {
        return vobject->get(FixedArray::OffsetOfElementAt(index));
      } else {
        return GetRootConstant(RootIndex::kTheHoleValue);
      }
    }
  }
  if (index < 0 || index >= FixedArray::kMaxLength) {
    return GetRootConstant(RootIndex::kTheHoleValue);
  }
  return AddNewNode<LoadTaggedField>({elements},
                                     FixedArray::OffsetOfElementAt(index));
}
References broker(), CanTrackObjectChanges(), v8::internal::maglev::NodeBase::Cast(), CHECK_EQ, v8::internal::DCHECK(), v8::internal::maglev::VirtualObject::get(), GetConstant(), GetObjectFromAllocation(), GetRootConstant(), v8::internal::index, v8::internal::maglev::VirtualObject::kDefault, kLoad, v8::internal::FixedArray::kMaxLength, v8::internal::length, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::maglev::VirtualObject::map(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::FixedArrayRef::TryGet(), TryGetConstant(), TryGetInt32Constant(), and v8::internal::maglev::VirtualObject::type().
Referenced by BuildLoadFixedArrayElement().
BuildLoadFixedArrayElement() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement (ValueNode * elements, ValueNode * index) [private]
Definition at line 5330 of file maglev-graph-builder.cc.
                                                                            {
  if (auto constant = TryGetInt32Constant(index)) {
    return BuildLoadFixedArrayElement(elements, constant.value());
  }
  return AddNewNode<LoadFixedArrayElement>({elements, index});
}
References BuildLoadFixedArrayElement(), v8::internal::index, and TryGetInt32Constant().
BuildLoadFixedArrayLength()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayLength (ValueNode * fixed_array) [private]
Definition at line 5594 of file maglev-graph-builder.cc.
                            {
  ValueNode* length =
      BuildLoadTaggedField(fixed_array, offsetof(FixedArray, length_));
  EnsureType(length, NodeType::kSmi);
  return length;
}
References BuildLoadTaggedField(), EnsureType(), v8::internal::compiler::kSmi, and v8::internal::length.
BuildLoadFixedDoubleArrayElement() [1/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedDoubleArrayElement (ValueNode * elements, int index) [private]
Definition at line 5352 of file maglev-graph-builder.cc.
                                    {
  if (CanTrackObjectChanges(elements, TrackObjectMode::kLoad)) {
    VirtualObject* vobject =
        GetObjectFromAllocation(elements->Cast<InlinedAllocation>());
    compiler::FixedDoubleArrayRef elements_array = vobject->double_elements();
    if (index >= 0 && static_cast<uint32_t>(index) < elements_array.length()) {
      Float64 value = elements_array.GetFromImmutableFixedDoubleArray(index);
      return GetFloat64Constant(value.get_scalar());
    } else {
      return GetRootConstant(RootIndex::kTheHoleValue);
    }
  }
  if (index < 0 || index >= FixedArray::kMaxLength) {
    return GetRootConstant(RootIndex::kTheHoleValue);
  }
  return AddNewNode<LoadFixedDoubleArrayElement>(
      {elements, GetInt32Constant(index)});
}
References CanTrackObjectChanges(), v8::internal::maglev::NodeBase::Cast(), v8::internal::maglev::VirtualObject::double_elements(), GetFloat64Constant(), v8::internal::compiler::FixedDoubleArrayRef::GetFromImmutableFixedDoubleArray(), GetInt32Constant(), GetObjectFromAllocation(), GetRootConstant(), v8::internal::index, kLoad, v8::internal::FixedArray::kMaxLength, v8::internal::compiler::FixedArrayBaseRef::length(), and v8::internal::value.
Referenced by BuildLoadFixedDoubleArrayElement().
BuildLoadFixedDoubleArrayElement() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedDoubleArrayElement (ValueNode * elements, ValueNode * index) [private]
Definition at line 5372 of file maglev-graph-builder.cc.
                                           {
  if (auto constant = TryGetInt32Constant(index)) {
    return BuildLoadFixedDoubleArrayElement(elements, constant.value());
  }
  return AddNewNode<LoadFixedDoubleArrayElement>({elements, index});
}
References BuildLoadFixedDoubleArrayElement(), v8::internal::index, and TryGetInt32Constant().
BuildLoadGlobal()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildLoadGlobal (compiler::NameRef name, compiler::FeedbackSource & feedback_source, TypeofMode typeof_mode) [private]
Definition at line 7782 of file maglev-graph-builder.cc.
                            {
  const compiler::ProcessedFeedback& access_feedback =
      broker()->GetFeedbackForGlobalAccess(feedback_source);
  if (access_feedback.IsInsufficient()) {
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kInsufficientTypeFeedbackForGenericGlobalAccess);
  }
  const compiler::GlobalAccessFeedback& global_access_feedback =
      access_feedback.AsGlobalAccess();
  PROCESS_AND_RETURN_IF_DONE(TryBuildGlobalLoad(global_access_feedback),
                             SetAccumulator);
  ValueNode* context = GetContext();
  SetAccumulator(
      AddNewNode<LoadGlobal>({context}, name, feedback_source, typeof_mode));
  return ReduceResult::Done();
}
References v8::internal::compiler::ProcessedFeedback::AsGlobalAccess(), broker(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::name, and PROCESS_AND_RETURN_IF_DONE.
BuildLoadHoleyFixedDoubleArrayElement()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadHoleyFixedDoubleArrayElement (ValueNode * elements, ValueNode * index, bool convert_hole) [private]
Definition at line 5387 of file maglev-graph-builder.cc.
                                                              {
  if (convert_hole) {
    return AddNewNode<LoadHoleyFixedDoubleArrayElement>({elements, index});
  } else {
    return AddNewNode<LoadHoleyFixedDoubleArrayElementCheckedNotHole>(
        {elements, index});
  }
}
References v8::internal::index.
BuildLoadJSArrayLength()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSArrayLength (ValueNode * js_array, NodeType length_type = NodeType::kSmi) [private]
Definition at line 5602 of file maglev-graph-builder.cc.
                                                                            {
  // TODO(leszeks): JSArray.length is known to be non-constant, don't bother
  // searching the constant values.
  MaybeReduceResult known_length =
      TryReuseKnownPropertyLoad(js_array, broker()->length_string());
  if (known_length.IsDone()) {
    DCHECK(known_length.IsDoneWithValue());
    return known_length.value();
  }
  ValueNode* length = BuildLoadTaggedField<LoadTaggedFieldForProperty>(
      js_array, JSArray::kLengthOffset, broker()->length_string());
  GetOrCreateInfoFor(length)->IntersectType(length_type);
  RecordKnownProperty(js_array, broker()->length_string(), length, false,
                      compiler::AccessMode::kLoad);
  return length;
}
References broker(), v8::internal::DCHECK(), GetOrCreateInfoFor(), v8::internal::maglev::NodeInfo::IntersectType(), v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::maglev::MaybeReduceResult::IsDoneWithValue(), v8::internal::compiler::kLoad, v8::internal::length, RecordKnownProperty(), TryReuseKnownPropertyLoad(), and v8::internal::maglev::MaybeReduceResult::value().
BuildLoadJSFunctionContext()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionContext (ValueNode * closure) [private]
Definition at line 5635 of file maglev-graph-builder.cc.
                                                                            {
  DCHECK(NodeTypeIs(GetType(closure), NodeType::kJSFunction));
  if (auto constant = closure->TryGetConstant(broker())) {
    if (constant->IsJSFunction()) {
      return GetConstant(constant->AsJSFunction().context(broker()));
    }
  }
  ValueNode* context =
      BuildLoadTaggedField(closure, JSFunction::kContextOffset);
  EnsureType(context, NodeType::kContext);
  return context;
}
References broker(), BuildLoadTaggedField(), v8::internal::DCHECK(), EnsureType(), GetConstant(), GetType(), v8::internal::maglev::NodeTypeIs(), and v8::internal::maglev::ValueNode::TryGetConstant().
BuildLoadJSFunctionFeedbackCell()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionFeedbackCell (ValueNode * closure) [private]
Definition at line 5621 of file maglev-graph-builder.cc.
                        {
  DCHECK(NodeTypeIs(GetType(closure), NodeType::kJSFunction));
  if (auto constant = closure->TryGetConstant(broker())) {
    if (constant->IsJSFunction()) {
      return GetConstant(constant->AsJSFunction().raw_feedback_cell(broker()));
    }
  }
  if (auto fast_closure = closure->TryCast<FastCreateClosure>()) {
    return GetConstant(fast_closure->feedback_cell());
  }
  return BuildLoadTaggedField(closure, JSFunction::kFeedbackCellOffset);
}
References broker(), BuildLoadTaggedField(), v8::internal::DCHECK(), GetConstant(), GetType(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::NodeBase::TryCast(), and v8::internal::maglev::ValueNode::TryGetConstant().
BuildLoadStringLength()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadStringLength (ValueNode * string) [private]
Definition at line 7456 of file maglev-graph-builder.cc.
                                                                      {
  DCHECK(NodeTypeIs(GetType(string), NodeType::kString));
  if (auto vo_string = string->TryCast<InlinedAllocation>()) {
    if (vo_string->object()->type() == VirtualObject::kConsString) {
      return vo_string->object()->string_length();
    }
  }
  if (auto const_string = string->TryGetConstant(broker())) {
    if (const_string->IsString()) {
      return GetInt32Constant(const_string->AsString().length());
    }
  }
  if (MaybeReduceResult result = TryFindLoadedProperty(
          known_node_aspects().loaded_constant_properties, string,
          KnownNodeAspects::LoadedPropertyMapKey::StringLength());
      result.IsDone()) {
    if (v8_flags.trace_maglev_graph_building && result.IsDoneWithValue()) {
      std::cout << " * Reusing constant [String length]"
                << PrintNodeLabel(graph_labeller(), result.value()) << ": "
                << PrintNode(graph_labeller(), result.value()) << std::endl;
    }
    return result.value();
  }
  ValueNode* result = AddNewNode<StringLength>({string});
  RecordKnownProperty(string,
                      KnownNodeAspects::LoadedPropertyMapKey::StringLength(),
                      result, true, compiler::AccessMode::kLoad);
  return result;
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::kLoad, v8::internal::maglev::NodeTypeIs(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::base::internal::result, v8::internal::string, v8::anonymous_namespace{api.cc}::StringLength(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::TryFindLoadedProperty(), and v8::internal::v8_flags.
Referenced by TryBuildNewConsString(), and TryBuildPropertyLoad().
BuildLoadTaggedField()
template<typename Instruction = LoadTaggedField, typename... Args>
ValueNode* v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField (ValueNode * object, uint32_t offset, Args &&... args) [inline], [private]
Definition at line 2399 of file maglev-graph-builder.h.
                                                  {
    if (offset != HeapObject::kMapOffset &&
        CanTrackObjectChanges(object, TrackObjectMode::kLoad)) {
      VirtualObject* vobject =
          GetObjectFromAllocation(object->Cast<InlinedAllocation>());
      ValueNode* value;
      CHECK_NE(vobject->type(), VirtualObject::kHeapNumber);
      if (vobject->type() == VirtualObject::kDefault) {
        value = vobject->get(offset);
      } else {
        DCHECK_EQ(vobject->type(), VirtualObject::kFixedDoubleArray);
        // The only offset we're allowed to read from the a FixedDoubleArray as
        // tagged field is the length.
        CHECK_EQ(offset, offsetof(FixedDoubleArray, length_));
        value = GetInt32Constant(vobject->double_elements_length());
      }
      if (v8_flags.trace_maglev_object_tracking) {
        std::cout << " * Reusing value in virtual object "
                  << PrintNodeLabel(graph_labeller(), vobject) << "[" << offset
                  << "]: " << PrintNode(graph_labeller(), value) << std::endl;
      }
      return value;
    }
    return AddNewNode<Instruction>({object}, offset,
                                   std::forward<Args>(args)...);
  }
References v8::base::args, v8::internal::maglev::NodeBase::Cast(), CHECK_EQ, CHECK_NE, DCHECK_EQ, v8::internal::maglev::VirtualObject::double_elements_length(), v8::internal::maglev::VirtualObject::get(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::VirtualObject::type(), v8::internal::v8_flags, and v8::internal::value.
Referenced by BuildLoadField(), BuildLoadFixedArrayLength(), BuildLoadJSFunctionContext(), BuildLoadJSFunctionFeedbackCell(), BuildNewConsStringMap(), TryBuildPropertyCellLoad(), TryBuildPropertyLoad(), TryBuildStoreField(), and TrySpecializeLoadContextSlot().
BuildLoadTypedArrayElement()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayElement (ValueNode * object, ValueNode * index, ElementsKind elements_kind) [private]
Definition at line 6345 of file maglev-graph-builder.cc.
                                                                     {
#define BUILD_AND_RETURN_LOAD_TYPED_ARRAY(Type) \
  return AddNewNode<Load##Type##TypedArrayElement>({object, index}, \
                                                   elements_kind);
  switch (elements_kind) {
    case INT8_ELEMENTS:
    case INT16_ELEMENTS:
    case INT32_ELEMENTS:
      BUILD_AND_RETURN_LOAD_TYPED_ARRAY(SignedInt);
    case UINT8_CLAMPED_ELEMENTS:
    case UINT8_ELEMENTS:
    case UINT16_ELEMENTS:
    case UINT32_ELEMENTS:
      BUILD_AND_RETURN_LOAD_TYPED_ARRAY(UnsignedInt);
    case FLOAT32_ELEMENTS:
    case FLOAT64_ELEMENTS:
      BUILD_AND_RETURN_LOAD_TYPED_ARRAY(Double);
    default:
      UNREACHABLE();
  }
#undef BUILD_AND_RETURN_LOAD_TYPED_ARRAY
}
References BUILD_AND_RETURN_LOAD_TYPED_ARRAY, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, and v8::internal::UNREACHABLE().
BuildLoadTypedArrayLength()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayLength (ValueNode * object, ElementsKind elements_kind) [private]
Definition at line 6308 of file maglev-graph-builder.cc.
                                                   {
  DCHECK(IsTypedArrayOrRabGsabTypedArrayElementsKind(elements_kind));
  bool is_variable_length = IsRabGsabTypedArrayElementsKind(elements_kind);
  if (!is_variable_length) {
    if (auto const_object = object->TryGetConstant(broker())) {
      // TODO(marja): Add TryGetConstant<JSTypedArray>().
      if (const_object->IsJSTypedArray()) {
        auto const_typed_array = const_object->AsJSTypedArray();
        if (!const_typed_array.is_on_heap() &&
            !IsRabGsabTypedArrayElementsKind(
                const_typed_array.elements_kind(broker()))) {
          size_t length = const_typed_array.length(broker());
          static_assert(ArrayBuffer::kMaxByteLength <=
                        std::numeric_limits<intptr_t>::max());
          return GetIntPtrConstant(static_cast<intptr_t>(length));
        }
      }
    }
    // Note: We can't use broker()->length_string() here, because it could
    // conflict with redefinitions of the TypedArray length property.
    RETURN_IF_DONE(TryFindLoadedProperty(
        known_node_aspects().loaded_constant_properties, object,
        KnownNodeAspects::LoadedPropertyMapKey::TypedArrayLength()));
  }
  ValueNode* result = AddNewNode<LoadTypedArrayLength>({object}, elements_kind);
  if (!is_variable_length) {
    RecordKnownProperty(
        object, KnownNodeAspects::LoadedPropertyMapKey::TypedArrayLength(),
        result, true, compiler::AccessMode::kLoad);
  }
  return result;
}
References broker(), v8::internal::DCHECK(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), v8::internal::compiler::kLoad, v8::ArrayBuffer::kMaxByteLength, v8::internal::length, v8::base::internal::result, RETURN_IF_DONE, v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::TryFindLoadedProperty(), and v8::internal::maglev::ValueNode::TryGetConstant().
Referenced by TryBuildPropertyLoad().
BuildLogicalNot()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildLogicalNot (ValueNode * value) [private]
Definition at line 8117 of file maglev-graph-builder.cc.
                                                               {
  // TODO(victorgomes): Use NodeInfo to add more type optimizations here.
  switch (value->opcode()) {
#define CASE(Name) \
  case Opcode::k##Name: { \
    return GetBooleanConstant(\
        !value->Cast<Name>()->ToBoolean(local_isolate())); \
  }
    CONSTANT_VALUE_NODE_LIST(CASE)
#undef CASE
    default:
      return AddNewNode<LogicalNot>({value});
  }
}
References CASE, CONSTANT_VALUE_NODE_LIST, and v8::internal::value.
BuildLoopForPeeling()
void v8::internal::maglev::MaglevGraphBuilder::BuildLoopForPeeling ()
Definition at line 14300 of file maglev-graph-builder.cc.
                                             {
  int loop_header = iterator_.current_offset();
  DCHECK(loop_headers_to_peel_.Contains(loop_header));
  // Since peeled loops do not start with a loop merge state, we need to
  // explicitly enter e loop effect tracking scope for the peeled iteration.
  bool track_peeled_effects =
      v8_flags.maglev_optimistic_peeled_loops && peeled_iteration_count_ == 2;
  if (track_peeled_effects) {
    BeginLoopEffects(loop_header);
  }
#ifdef DEBUG
  bool was_in_peeled_iteration = in_peeled_iteration();
#endif // DEBUG
  while (iterator_.current_bytecode() != interpreter::Bytecode::kJumpLoop) {
    local_isolate_->heap()->Safepoint();
    VisitSingleBytecode();
    iterator_.Advance();
  }
  VisitSingleBytecode(); // VisitJumpLoop
  DCHECK_EQ(was_in_peeled_iteration, in_peeled_iteration());
  if (!in_peeled_iteration()) {
    return;
  }
  // In case the peeled iteration was mergeable (see TryMergeLoop) or the
  // JumpLoop was dead, we are done.
  if (!current_block_) {
    decremented_predecessor_offsets_.clear();
    KillPeeledLoopTargets(peeled_iteration_count_);
    peeled_iteration_count_ = 0;
    if (track_peeled_effects) {
      EndLoopEffects(loop_header);
    }
    return;
  }
  peeled_iteration_count_--;
  // After processing the peeled iteration and reaching the `JumpLoop`, we
  // re-process the loop body. For this, we need to reset the graph building
  // state roughly as if we didn't process it yet.
  // Reset position in exception handler table to before the loop.
  HandlerTable table(*bytecode().object());
  while (next_handler_table_index_ > 0) {
    next_handler_table_index_--;
    int start = table.GetRangeStart(next_handler_table_index_);
    if (start < loop_header) break;
  }
  // Re-create catch handler merge states.
  for (int offset = loop_header; offset <= iterator_.current_offset();
       ++offset) {
    if (auto& merge_state = merge_states_[offset]) {
      if (merge_state->is_exception_handler()) {
        merge_state = MergePointInterpreterFrameState::NewForCatchBlock(
            *compilation_unit_, merge_state->frame_state().liveness(), offset,
            merge_state->exception_handler_was_used(),
            merge_state->catch_block_context_register(), graph_);
      } else {
        // We only peel innermost loops.
        DCHECK(!merge_state->is_loop());
        merge_state = nullptr;
      }
    }
    new (&jump_targets_[offset]) BasicBlockRef();
  }
  // Reset predecessors as if the loop body had not been visited.
  for (int offset : decremented_predecessor_offsets_) {
    DCHECK_GE(offset, loop_header);
    if (offset <= iterator_.current_offset()) {
      UpdatePredecessorCount(offset, 1);
    }
  }
  decremented_predecessor_offsets_.clear();
  DCHECK(current_block_);
  // After resetting, the actual loop header always has exactly 2
  // predecessors: the two copies of `JumpLoop`.
  InitializePredecessorCount(loop_header, 2);
  merge_states_[loop_header] = MergePointInterpreterFrameState::NewForLoop(
      current_interpreter_frame_, graph_, *compilation_unit_, loop_header, 2,
      GetInLivenessFor(loop_header),
      &bytecode_analysis_.GetLoopInfoFor(loop_header),
      /* has_been_peeled */ true);
  BasicBlock* block = FinishBlock<Jump>({}, &jump_targets_[loop_header]);
  // If we ever want more peelings, we should ensure that only the last one
  // creates a loop header.
  DCHECK_LE(peeled_iteration_count_, 1);
  DCHECK_IMPLIES(in_peeled_iteration(),
                 v8_flags.maglev_optimistic_peeled_loops);
  merge_states_[loop_header]->InitializeLoop(
      this, *compilation_unit_, current_interpreter_frame_, block,
      in_peeled_iteration(), loop_effects_);
  if (track_peeled_effects) {
    EndLoopEffects(loop_header);
  }
  DCHECK_NE(iterator_.current_offset(), loop_header);
  iterator_.SetOffset(loop_header);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, DCHECK_LE, DCHECK_NE, v8::internal::HandlerTable::GetRangeStart(), and v8::internal::v8_flags.
BuildMergeStates()
void v8::internal::maglev::MaglevGraphBuilder::BuildMergeStates ()
Definition at line 1137 of file maglev-graph-builder.cc.
                                          {
  auto offset_and_info = bytecode_analysis().GetLoopInfos().begin();
  auto end = bytecode_analysis().GetLoopInfos().end();
  while (offset_and_info != end && offset_and_info->first < entrypoint_) {
    ++offset_and_info;
  }
  for (; offset_and_info != end; ++offset_and_info) {
    int offset = offset_and_info->first;
    const compiler::LoopInfo& loop_info = offset_and_info->second;
    if (loop_headers_to_peel_.Contains(offset)) {
      // Peeled loops are treated like normal merges at first. We will construct
      // the proper loop header merge state when reaching the `JumpLoop` of the
      // peeled iteration.
      continue;
    }
    const compiler::BytecodeLivenessState* liveness = GetInLivenessFor(offset);
    DCHECK_NULL(merge_states_[offset]);
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << "- Creating loop merge state at @" << offset << std::endl;
    }
    merge_states_[offset] = MergePointInterpreterFrameState::NewForLoop(
        current_interpreter_frame_, graph_, *compilation_unit_, offset,
        predecessor_count(offset), liveness, &loop_info);
  }
  if (bytecode().handler_table_size() > 0) {
    HandlerTable table(*bytecode().object());
    for (int i = 0; i < table.NumberOfRangeEntries(); i++) {
      const int offset = table.GetRangeHandler(i);
      const bool was_used = table.HandlerWasUsed(i);
      const interpreter::Register context_reg(table.GetRangeData(i));
      const compiler::BytecodeLivenessState* liveness =
          GetInLivenessFor(offset);
      DCHECK_EQ(predecessor_count(offset), 0);
      DCHECK_NULL(merge_states_[offset]);
      if (v8_flags.trace_maglev_graph_building) {
        std::cout << "- Creating exception merge state at @" << offset
                  << (was_used ? "" : " (never used)") << ", context register r"
                  << context_reg.index() << std::endl;
      }
      merge_states_[offset] = MergePointInterpreterFrameState::NewForCatchBlock(
          *compilation_unit_, liveness, offset, was_used, context_reg, graph_);
    }
  }
}
References bytecode(), bytecode_analysis(), compilation_unit_, v8::internal::BitVector::Contains(), current_interpreter_frame_, DCHECK_EQ, DCHECK_NULL, v8::internal::compiler::end(), entrypoint_, GetInLivenessFor(), v8::internal::compiler::BytecodeAnalysis::GetLoopInfos(), v8::internal::HandlerTable::GetRangeData(), v8::internal::HandlerTable::GetRangeHandler(), graph_, v8::internal::HandlerTable::HandlerWasUsed(), v8::internal::interpreter::Register::index(), loop_headers_to_peel_, merge_states_, v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::HandlerTable::NumberOfRangeEntries(), predecessor_count(), and v8::internal::v8_flags.
Referenced by Build().
BuildNewConsStringMap()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap (ValueNode * left, ValueNode * right) [private]
Definition at line 2699 of file maglev-graph-builder.cc.
                                                                       {
  struct Result {
    bool static_map;
    bool is_two_byte;
    // The result map if the other map is known to be one byte.
    ValueNode* result_map;
  };
  // If either is a two byte map, then the result is the kConsTwoByteStringMap.
  // If both are non-two byte maps, then the result is the
  // kConsOneByteStringMap.
  auto GetIsTwoByteAndMap = [&](ValueNode* input) -> Result {
    if (auto maybe_constant = input->TryGetConstant(broker())) {
      bool two_byte = maybe_constant->map(broker()).IsTwoByteStringMap();
      return {true, two_byte,
              GetRootConstant(two_byte ? RootIndex::kConsTwoByteStringMap
                                       : RootIndex::kConsOneByteStringMap)};
    }
    switch (input->opcode()) {
      case Opcode::kNumberToString:
        return {true, false, GetRootConstant(RootIndex::kConsOneByteStringMap)};
      case Opcode::kInlinedAllocation: {
        VirtualObject* cons = input->Cast<InlinedAllocation>()->object();
        if (cons->type() == VirtualObject::kConsString) {
          ValueNode* map = cons->cons_string().map;
          if (auto cons_map = map->TryGetConstant(broker())) {
            return {true, cons_map->AsMap().IsTwoByteStringMap(), map};
          }
          return {false, false, map};
        }
        break;
      }
      default:
        break;
    }
    return {false, false, nullptr};
  };
  auto left_info = GetIsTwoByteAndMap(left);
  auto right_info = GetIsTwoByteAndMap(right);
  if (left_info.static_map) {
    if (left_info.is_two_byte) {
      return GetRootConstant(RootIndex::kConsTwoByteStringMap);
    }
    // If left is known non-twobyte, then the result only depends on right.
    if (right_info.static_map) {
      if (right_info.is_two_byte) {
        return GetRootConstant(RootIndex::kConsTwoByteStringMap);
      } else {
        return GetRootConstant(RootIndex::kConsOneByteStringMap);
      }
    }
    if (right_info.result_map) {
      return right_info.result_map;
    }
  } else if (left_info.result_map) {
    // Left is not constant, but we have a value for the map.
    // If right is known non-twobyte, then the result only depends on left.
    if (right_info.static_map && !right_info.is_two_byte) {
      return left_info.result_map;
    }
  }
  // Since ConsStringMap only cares about the two-byte-ness of its inputs we
  // might as well pass the result map instead if we have one.
  ValueNode* left_map =
      left_info.result_map ? left_info.result_map
                           : BuildLoadTaggedField(left, HeapObject::kMapOffset);
  ValueNode* right_map =
      right_info.result_map
          ? right_info.result_map
          : BuildLoadTaggedField(right, HeapObject::kMapOffset);
  // Sort inputs for CSE. Move constants to the left since the instruction
  // reuses the lhs input.
  if (IsConstantNode(right_map->opcode()) ||
      (!IsConstantNode(left_map->opcode()) && left > right)) {
    std::swap(left, right);
  }
  // TODO(olivf): Evaluate if using maglev controlflow to select the map could
  // be faster here.
  return AddNewNode<ConsStringMap>({left_map, right_map});
}
References broker(), BuildLoadTaggedField(), v8::internal::maglev::VirtualObject::cons_string(), GetRootConstant(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::VirtualObject::kConsString, v8::internal::HeapObject::kMapOffset, v8::internal::maglev::VirtualObject::VirtualConsString::map, v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::ValueNode::TryGetConstant(), and v8::internal::maglev::VirtualObject::type().
Referenced by TryBuildNewConsString().
BuildNumberOrOddballToFloat64()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildNumberOrOddballToFloat64 (ValueNode * node, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 4543 of file maglev-graph-builder.cc.
                                                   {
  NodeType old_type;
  if (EnsureType(node, allowed_input_type, &old_type)) {
    if (old_type == NodeType::kSmi) {
      ValueNode* untagged_smi = BuildSmiUntag(node);
      return AddNewNode<ChangeInt32ToFloat64>({untagged_smi});
    }
    return AddNewNode<UncheckedNumberOrOddballToFloat64>({node},
                                                         conversion_type);
  } else {
    return AddNewNode<CheckedNumberOrOddballToFloat64>({node}, conversion_type);
  }
}
References BuildSmiUntag(), EnsureType(), and v8::internal::compiler::kSmi.
Referenced by GetFloat64ForToNumber().
BuildOrdinaryHasInstance()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildOrdinaryHasInstance (ValueNode * object, compiler::JSObjectRef callable, ValueNode * callable_node) [private]
Definition at line 12712 of file maglev-graph-builder.cc.
                                              {
  RETURN_IF_DONE(TryBuildFastOrdinaryHasInstance(
      object, callable, callable_node_if_not_constant));
  return BuildCallBuiltin<Builtin::kOrdinaryHasInstance>(
      {callable_node_if_not_constant
           ? GetTaggedValue(callable_node_if_not_constant)
           : GetConstant(callable),
       GetTaggedValue(object)});
}
References RETURN_IF_DONE.
BuildRegisterFrameInitialization()
void v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization (ValueNode * context = nullptr, ValueNode * closure = nullptr, ValueNode * new_target = nullptr)
Definition at line 1087 of file maglev-graph-builder.cc.
                                                                   {
  if (closure == nullptr &&
      compilation_unit_->info()->specialize_to_function_context()) {
    compiler::JSFunctionRef function = compiler::MakeRefAssumeMemoryFence(
        broker(), broker()->CanonicalPersistentHandle(
                      compilation_unit_->info()->toplevel_function()));
    closure = GetConstant(function);
    context = GetConstant(function.context(broker()));
  }
  InitializeRegister(interpreter::Register::current_context(), context);
  InitializeRegister(interpreter::Register::function_closure(), closure);
  EnsureType(GetContext(), NodeType::kContext);
  EnsureType(GetClosure(), NodeType::kJSFunction);
  interpreter::Register new_target_or_generator_register =
      bytecode().incoming_new_target_or_generator_register();
  int register_index = 0;
  if (compilation_unit_->is_osr()) {
    for (; register_index < register_count(); register_index++) {
      auto val =
          AddNewNode<InitialValue>({}, interpreter::Register(register_index));
      InitializeRegister(interpreter::Register(register_index), val);
      graph_->osr_values().push_back(val);
    }
    return;
  }
  // TODO(leszeks): Don't emit if not needed.
  ValueNode* undefined_value = GetRootConstant(RootIndex::kUndefinedValue);
  if (new_target_or_generator_register.is_valid()) {
    int new_target_index = new_target_or_generator_register.index();
    for (; register_index < new_target_index; register_index++) {
      current_interpreter_frame_.set(interpreter::Register(register_index),
                                     undefined_value);
    }
    current_interpreter_frame_.set(
        new_target_or_generator_register,
        new_target ? new_target
                   : GetRegisterInput(kJavaScriptCallNewTargetRegister));
    register_index++;
  }
  for (; register_index < register_count(); register_index++) {
    InitializeRegister(interpreter::Register(register_index), undefined_value);
  }
}
References broker(), bytecode(), compilation_unit_, v8::internal::interpreter::Register::current_context(), current_interpreter_frame_, EnsureType(), v8::internal::interpreter::Register::function_closure(), GetClosure(), GetConstant(), GetContext(), GetRegisterInput(), GetRootConstant(), graph_, v8::internal::compiler::BytecodeArrayRef::incoming_new_target_or_generator_register(), v8::internal::interpreter::Register::index(), v8::internal::maglev::MaglevCompilationUnit::info(), InitializeRegister(), v8::internal::maglev::MaglevCompilationUnit::is_osr(), v8::internal::interpreter::Register::is_valid(), v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::maglev::Graph::osr_values(), v8::internal::ETWJITInterface::Register(), register_count(), v8::internal::maglev::InterpreterFrameState::set(), v8::internal::maglev::MaglevCompilationInfo::specialize_to_function_context(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_function().
Referenced by Build().
BuildSmiUntag()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildSmiUntag (ValueNode * node) [private]
Definition at line 4525 of file maglev-graph-builder.cc.
                                                            {
  // This is called when converting inputs in AddNewNode. We might already have
  // an empty type for `node` here. Make sure we don't add unsafe conversion
  // nodes in that case by checking for the empty node type explicitly.
  // TODO(marja): The checks can be removed after we're able to bail out
  // earlier.
  if (!IsEmptyNodeType(GetType(node)) && EnsureType(node, NodeType::kSmi)) {
    if (SmiValuesAre31Bits()) {
      if (auto phi = node->TryCast<Phi>()) {
        phi->SetUseRequires31BitValue();
      }
    }
    return AddNewNode<UnsafeSmiUntag>({node});
  } else {
    return AddNewNode<CheckedSmiUntag>({node});
  }
}
References EnsureType(), GetType(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::compiler::kSmi, v8::internal::SmiValuesAre31Bits(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by BuildNumberOrOddballToFloat64(), GetInt32(), GetInt32ElementIndex(), and GetTruncatedInt32ForToNumber().
BuildStoreConstantTypedArrayElement()
void v8::internal::maglev::MaglevGraphBuilder::BuildStoreConstantTypedArrayElement (compiler::JSTypedArrayRef typed_array, ValueNode * index, ElementsKind elements_kind) [private]
Definition at line 6434 of file maglev-graph-builder.cc.
                                {
#define BUILD_STORE_CONSTANT_TYPED_ARRAY(Type, value) \
  AddNewNode<Store##Type##ConstantTypedArrayElement>(\
      {index, (value)}, typed_array, elements_kind);
  // TODO(leszeks): These operations have a deopt loop when the ToNumber
  // conversion sees a type other than number or oddball. Turbofan has the same
  // deopt loop, but ideally we'd avoid it.
  switch (elements_kind) {
    case UINT8_CLAMPED_ELEMENTS: {
      BUILD_STORE_CONSTANT_TYPED_ARRAY(Int,
                                       GetAccumulatorUint8ClampedForToNumber())
      break;
    }
    case INT8_ELEMENTS:
    case INT16_ELEMENTS:
    case INT32_ELEMENTS:
    case UINT8_ELEMENTS:
    case UINT16_ELEMENTS:
    case UINT32_ELEMENTS:
      BUILD_STORE_CONSTANT_TYPED_ARRAY(
          Int, GetAccumulatorTruncatedInt32ForToNumber(
                   NodeType::kNumberOrOddball,
                   TaggedToFloat64ConversionType::kNumberOrOddball))
      break;
    case FLOAT32_ELEMENTS:
    case FLOAT64_ELEMENTS:
      BUILD_STORE_CONSTANT_TYPED_ARRAY(
          Double, GetAccumulatorHoleyFloat64ForToNumber(
                      NodeType::kNumberOrOddball,
                      TaggedToFloat64ConversionType::kNumberOrOddball))
      break;
    default:
      UNREACHABLE();
  }
#undef BUILD_STORE_CONSTANT_TYPED_ARRAY
}
References BUILD_STORE_CONSTANT_TYPED_ARRAY, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, and v8::internal::UNREACHABLE().
BuildStoreContextSlot()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildStoreContextSlot (ValueNode * context, size_t depth, int slot_index, ValueNode * value, ContextMode context_mode) [private]
Definition at line 3799 of file maglev-graph-builder.cc.
                              {
  context = GetContextAtDepth(context, depth);
  return StoreAndCacheContextSlot(context, slot_index, value, context_mode);
}
References GetContextAtDepth(), StoreAndCacheContextSlot(), and v8::internal::value.
BuildStoreFixedArrayElement()
void v8::internal::maglev::MaglevGraphBuilder::BuildStoreFixedArrayElement (ValueNode * elements, ValueNode * index, ValueNode * value) [private]
Definition at line 5338 of file maglev-graph-builder.cc.
                                                                       {
  // TODO(victorgomes): Support storing element to a virtual object. If we
  // modify the elements array, we need to modify the original object to point
  // to the new elements array.
  if (CanElideWriteBarrier(elements, value)) {
    AddNewNode<StoreFixedArrayElementNoWriteBarrier>({elements, index, value});
  } else {
    AddNewNode<StoreFixedArrayElementWithWriteBarrier>(
        {elements, index, value});
  }
}
References CanElideWriteBarrier(), v8::internal::index, and v8::internal::value.
BuildStoreFixedDoubleArrayElement()
void v8::internal::maglev::MaglevGraphBuilder::BuildStoreFixedDoubleArrayElement (ValueNode * elements, ValueNode * index, ValueNode * value) [private]
Definition at line 5380 of file maglev-graph-builder.cc.
                                                                             {
  // TODO(victorgomes): Support storing double element to a virtual object.
  AddNewNode<StoreFixedDoubleArrayElement>({elements, index, value});
}
References v8::internal::index, and v8::internal::value.
BuildStoreMap()
void v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap (ValueNode * object, compiler::MapRef map, StoreMap::Kind kind) [private]
Definition at line 5648 of file maglev-graph-builder.cc.
                                                          {
  AddNewNode<StoreMap>({object}, map, kind);
  NodeType object_type = StaticTypeForMap(map, broker());
  NodeInfo* node_info = GetOrCreateInfoFor(object);
  if (map.is_stable()) {
    node_info->SetPossibleMaps(PossibleMaps{map}, false, object_type, broker());
    broker()->dependencies()->DependOnStableMap(map);
  } else {
    node_info->SetPossibleMaps(PossibleMaps{map}, true, object_type, broker());
    known_node_aspects().any_map_for_any_node_is_unstable = true;
  }
}
References v8::internal::maglev::KnownNodeAspects::any_map_for_any_node_is_unstable, broker(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), GetOrCreateInfoFor(), v8::internal::compiler::MapRef::is_stable(), known_node_aspects(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), and v8::internal::maglev::StaticTypeForMap().
Referenced by TryBuildStoreField().
BuildStoreTaggedField()
Node * v8::internal::maglev::MaglevGraphBuilder::BuildStoreTaggedField (ValueNode * object, ValueNode * value, int offset, StoreTaggedMode store_mode) [private]
Definition at line 5233 of file maglev-graph-builder.cc.
                                                                            {
  // The value may be used to initialize a VO, which can leak to IFS.
  // It should NOT be a conversion node, UNLESS it's an initializing value.
  // Initializing values are tagged before allocation, since conversion nodes
  // may allocate, and are not used to set a VO.
  DCHECK_IMPLIES(store_mode != StoreTaggedMode::kInitializing,
                 !value->properties().is_conversion());
  // TODO(marja): Bail out if `value` has the empty type. This requires that
  // BuildInlinedAllocation can bail out.
  if (store_mode != StoreTaggedMode::kInitializing) {
    TryBuildStoreTaggedFieldToAllocation(object, value, offset);
  }
  if (CanElideWriteBarrier(object, value)) {
    return AddNewNode<StoreTaggedFieldNoWriteBarrier>({object, value}, offset,
                                                      store_mode);
  } else {
    // Detect stores that would create old-to-new references and pretenure the
    // value.
    if (v8_flags.maglev_pretenure_store_values) {
      if (auto alloc = object->TryCast<InlinedAllocation>()) {
        if (alloc->allocation_block()->allocation_type() ==
            AllocationType::kOld) {
          alloc->allocation_block()->TryPretenure(value);
        }
      }
    }
    return AddNewNode<StoreTaggedFieldWithWriteBarrier>({object, value}, offset,
                                                        store_mode);
  }
}
References CanElideWriteBarrier(), DCHECK_IMPLIES, v8::internal::maglev::kInitializing, v8::internal::kOld, TryBuildStoreTaggedFieldToAllocation(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::v8_flags, and v8::internal::value.
Referenced by BuildInitializeStore(), BuildStoreTrustedPointerField(), StoreAndCacheContextSlot(), TryBuildPropertyCellStore(), TryBuildStoreField(), and TrySpecializeStoreContextSlot().
BuildStoreTaggedFieldNoWriteBarrier()
Node * v8::internal::maglev::MaglevGraphBuilder::BuildStoreTaggedFieldNoWriteBarrier (ValueNode * object, ValueNode * value, int offset, StoreTaggedMode store_mode) [private]
Definition at line 5266 of file maglev-graph-builder.cc.
                                {
  // The value may be used to initialize a VO, which can leak to IFS.
  // It should NOT be a conversion node, UNLESS it's an initializing value.
  // Initializing values are tagged before allocation, since conversion nodes
  // may allocate, and are not used to set a VO.
  DCHECK_IMPLIES(store_mode != StoreTaggedMode::kInitializing,
                 !value->properties().is_conversion());
  DCHECK(CanElideWriteBarrier(object, value));
  if (store_mode != StoreTaggedMode::kInitializing) {
    TryBuildStoreTaggedFieldToAllocation(object, value, offset);
  }
  return AddNewNode<StoreTaggedFieldNoWriteBarrier>({object, value}, offset,
                                                    store_mode);
}
References CanElideWriteBarrier(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::maglev::kInitializing, TryBuildStoreTaggedFieldToAllocation(), and v8::internal::value.
Referenced by TryBuildStoreField(), and TrySpecializeStoreContextSlot().
BuildStoreTrustedPointerField()
void v8::internal::maglev::MaglevGraphBuilder::BuildStoreTrustedPointerField (ValueNode * object, ValueNode * value, int offset, IndirectPointerTag tag, StoreTaggedMode store_mode) [private]
Definition at line 5283 of file maglev-graph-builder.cc.
                                {
#ifdef V8_ENABLE_SANDBOX
  AddNewNode<StoreTrustedPointerFieldWithWriteBarrier>({object, value}, offset,
                                                       tag, store_mode);
#else
  BuildStoreTaggedField(object, value, offset, store_mode);
#endif // V8_ENABLE_SANDBOX
}
References BuildStoreTaggedField(), and v8::internal::value.
Referenced by BuildInitializeStore().
BuildStoreTypedArrayElement()
void v8::internal::maglev::MaglevGraphBuilder::BuildStoreTypedArrayElement (ValueNode * object, ValueNode * index, ElementsKind elements_kind) [private]
Definition at line 6396 of file maglev-graph-builder.cc.
                                                                     {
#define BUILD_STORE_TYPED_ARRAY(Type, value) \
  AddNewNode<Store##Type##TypedArrayElement>({object, index, (value)}, \
                                             elements_kind);
  // TODO(leszeks): These operations have a deopt loop when the ToNumber
  // conversion sees a type other than number or oddball. Turbofan has the same
  // deopt loop, but ideally we'd avoid it.
  switch (elements_kind) {
    case UINT8_CLAMPED_ELEMENTS: {
      BUILD_STORE_TYPED_ARRAY(Int, GetAccumulatorUint8ClampedForToNumber())
      break;
    }
    case INT8_ELEMENTS:
    case INT16_ELEMENTS:
    case INT32_ELEMENTS:
    case UINT8_ELEMENTS:
    case UINT16_ELEMENTS:
    case UINT32_ELEMENTS:
      BUILD_STORE_TYPED_ARRAY(
          Int, GetAccumulatorTruncatedInt32ForToNumber(
                   NodeType::kNumberOrOddball,
                   TaggedToFloat64ConversionType::kNumberOrOddball))
      break;
    case FLOAT32_ELEMENTS:
    case FLOAT64_ELEMENTS:
      BUILD_STORE_TYPED_ARRAY(
          Double, GetAccumulatorHoleyFloat64ForToNumber(
                      NodeType::kNumberOrOddball,
                      TaggedToFloat64ConversionType::kNumberOrOddball))
      break;
    default:
      UNREACHABLE();
  }
#undef BUILD_STORE_TYPED_ARRAY
}
References BUILD_STORE_TYPED_ARRAY, v8::internal::maglev::FLOAT32_ELEMENTS, v8::internal::maglev::INT16_ELEMENTS, v8::internal::maglev::INT8_ELEMENTS, v8::internal::maglev::UINT16_ELEMENTS, v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::maglev::UINT8_ELEMENTS, and v8::internal::UNREACHABLE().
BuildStringConcat()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildStringConcat (ValueNode * left, ValueNode * right) [private]
Definition at line 2913 of file maglev-graph-builder.cc.
                                                                     {
  if (RootConstant* root_constant = left->TryCast<RootConstant>()) {
    if (root_constant->index() == RootIndex::kempty_string) {
      RETURN_IF_ABORT(BuildCheckString(right));
      SetAccumulator(right);
      return ReduceResult::Done();
    }
  }
  if (RootConstant* root_constant = right->TryCast<RootConstant>()) {
    if (root_constant->index() == RootIndex::kempty_string) {
      RETURN_IF_ABORT(BuildCheckString(left));
      SetAccumulator(left);
      return ReduceResult::Done();
    }
  }
  RETURN_IF_ABORT(BuildCheckString(left));
  RETURN_IF_ABORT(BuildCheckString(right));
  PROCESS_AND_RETURN_IF_DONE(TryBuildNewConsString(left, right),
                             SetAccumulator);
  SetAccumulator(AddNewNode<StringConcat>({left, right}));
  return ReduceResult::Done();
}
References BuildCheckString(), v8::internal::maglev::ReduceResult::Done(), PROCESS_AND_RETURN_IF_DONE, RETURN_IF_ABORT, SetAccumulator(), TryBuildNewConsString(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by VisitBinaryOperation().
BuildTaggedEqual() [1/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildTaggedEqual (ValueNode * lhs, RootIndex rhs_index) [private]
Definition at line 3935 of file maglev-graph-builder.cc.
                                                                     {
  return BuildTaggedEqual(lhs, GetRootConstant(rhs_index));
}
References BuildTaggedEqual(), and GetRootConstant().
BuildTaggedEqual() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildTaggedEqual (ValueNode * lhs, ValueNode * rhs) [private]
Definition at line 3914 of file maglev-graph-builder.cc.
                                                                {
  ValueNode* tagged_lhs = GetTaggedValue(lhs);
  ValueNode* tagged_rhs = GetTaggedValue(rhs);
  if (tagged_lhs == tagged_rhs) {
    return GetBooleanConstant(true);
  }
  if (HaveDisjointTypes(tagged_lhs, tagged_rhs)) {
    return GetBooleanConstant(false);
  }
  // TODO(victorgomes): We could retrieve the HeapObjectRef in Constant and
  // compare them.
  if (IsConstantNode(tagged_lhs->opcode()) && !tagged_lhs->Is<Constant>() &&
      tagged_lhs->opcode() == tagged_rhs->opcode()) {
    // Constants nodes are canonicalized, except for the node holding
    // HeapObjectRef, so equal constants should have been handled above.
    return GetBooleanConstant(false);
  }
  return AddNewNode<TaggedEqual>({tagged_lhs, tagged_rhs});
}
References GetBooleanConstant(), GetTaggedValue(), HaveDisjointTypes(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::IsConstantNode(), and v8::internal::maglev::NodeBase::opcode().
Referenced by BuildTaggedEqual(), TryReduceCompareEqualAgainstConstant(), and VisitCompareOperation().
BuildTestUndetectable()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable (ValueNode * value) [private]
Definition at line 3947 of file maglev-graph-builder.cc.
                                                                     {
  if (value->properties().value_representation() ==
      ValueRepresentation::kHoleyFloat64) {
    return AddNewNode<HoleyFloat64IsHole>({value});
  } else if (value->properties().value_representation() !=
             ValueRepresentation::kTagged) {
    return GetBooleanConstant(false);
  }
  if (auto maybe_constant = TryGetConstant(value)) {
    auto map = maybe_constant.value().map(broker());
    return GetBooleanConstant(map.is_undetectable());
  }
  NodeType node_type;
  if (CheckType(value, NodeType::kSmi, &node_type)) {
    return GetBooleanConstant(false);
  }
  auto it = known_node_aspects().FindInfo(value);
  if (known_node_aspects().IsValid(it)) {
    NodeInfo& info = it->second;
    if (info.possible_maps_are_known()) {
      // We check if all the possible maps have the same undetectable bit value.
      DCHECK_GT(info.possible_maps().size(), 0);
      bool first_is_undetectable = info.possible_maps()[0].is_undetectable();
      bool all_the_same_value =
          std::all_of(info.possible_maps().begin(), info.possible_maps().end(),
                      [first_is_undetectable](compiler::MapRef map) {
                        bool is_undetectable = map.is_undetectable();
                        return (first_is_undetectable && is_undetectable) ||
                               (!first_is_undetectable && !is_undetectable);
                      });
      if (all_the_same_value) {
        return GetBooleanConstant(first_is_undetectable);
      }
    }
  }
  enum CheckType type = GetCheckType(node_type);
  return AddNewNode<TestUndetectable>({value}, type);
}
References v8::base::all_of(), v8::internal::ZoneCompactSet< T >::begin(), broker(), CheckType(), DCHECK_GT, v8::internal::ZoneCompactSet< T >::end(), v8::internal::maglev::KnownNodeAspects::FindInfo(), GetBooleanConstant(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), v8::internal::maglev::kHoleyFloat64, known_node_aspects(), v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), v8::internal::ZoneCompactSet< T >::size(), TryGetConstant(), v8::internal::tracing::type, and v8::internal::value.
Referenced by BuildBranchIfUndetectable().
BuildToBoolean()
template<bool flip>
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildToBoolean (ValueNode * node) [private]
Definition at line 12846 of file maglev-graph-builder.cc.
                                                              {
  if (IsConstantNode(value->opcode())) {
    return GetBooleanConstant(FromConstantToBool(local_isolate(), value) ^
                              flip);
  }
  switch (value->value_representation()) {
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      // The ToBoolean of both the_hole and NaN is false, so we can use the
      // same operation for HoleyFloat64 and Float64.
      return AddNewNode<Float64ToBoolean>({value}, flip);
    case ValueRepresentation::kUint32:
      // Uint32 has the same logic as Int32 when converting ToBoolean, namely
      // comparison against zero, so we can cast it and ignore the signedness.
      value = AddNewNode<TruncateUint32ToInt32>({value});
      [[fallthrough]];
    case ValueRepresentation::kInt32:
      return AddNewNode<Int32ToBoolean>({value}, flip);
    case ValueRepresentation::kIntPtr:
      return AddNewNode<IntPtrToBoolean>({value}, flip);
    case ValueRepresentation::kTagged:
      break;
  }
  NodeInfo* node_info = known_node_aspects().TryGetInfoFor(value);
  if (node_info) {
    if (ValueNode* as_int32 = node_info->alternative().int32()) {
      return AddNewNode<Int32ToBoolean>({as_int32}, flip);
    }
    if (ValueNode* as_float64 = node_info->alternative().float64()) {
      return AddNewNode<Float64ToBoolean>({as_float64}, flip);
    }
  }
  NodeType value_type;
  if (CheckType(value, NodeType::kJSReceiver, &value_type)) {
    ValueNode* result = BuildTestUndetectable(value);
    // TODO(victorgomes): Check if it is worth to create
    // TestUndetectableLogicalNot or to remove ToBooleanLogicalNot, since we
    // already optimize LogicalNots by swapping the branches.
    if constexpr (!flip) {
      result = BuildLogicalNot(result);
    }
    return result;
  }
  ValueNode* falsy_value = nullptr;
  if (CheckType(value, NodeType::kString)) {
    falsy_value = GetRootConstant(RootIndex::kempty_string);
  } else if (CheckType(value, NodeType::kSmi)) {
    falsy_value = GetSmiConstant(0);
  }
  if (falsy_value != nullptr) {
    return AddNewNode<std::conditional_t<flip, TaggedEqual, TaggedNotEqual>>(
        {value, falsy_value});
  }
  if (CheckType(value, NodeType::kBoolean)) {
    if constexpr (flip) {
      value = BuildLogicalNot(value);
    }
    return value;
  }
  return AddNewNode<std::conditional_t<flip, ToBooleanLogicalNot, ToBoolean>>(
      {value}, GetCheckType(value_type));
}
References v8::internal::maglev::NodeInfo::alternative(), v8::internal::maglev::FromConstantToBool(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), v8::internal::maglev::IsConstantNode(), v8::internal::anonymous_namespace{ic.cc}::kIntPtr, v8::internal::compiler::kSmi, v8::base::internal::result, v8::internal::value, and v8::internal::wasm::value_type().
BuildToNumberOrToNumeric()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildToNumberOrToNumeric (Object::Conversion mode) [private]
Definition at line 12995 of file maglev-graph-builder.cc.
                           {
  ValueNode* value = GetAccumulator();
  switch (value->value_representation()) {
    case ValueRepresentation::kInt32:
    case ValueRepresentation::kUint32:
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kIntPtr:
      return ReduceResult::Done();
    case ValueRepresentation::kHoleyFloat64: {
      SetAccumulator(AddNewNode<HoleyFloat64ToMaybeNanFloat64>({value}));
      return ReduceResult::Done();
    }
    case ValueRepresentation::kTagged:
      // We'll insert the required checks depending on the feedback.
      break;
  }
  FeedbackSlot slot = GetSlotOperand(0);
  switch (broker()->GetFeedbackForBinaryOperation(
      compiler::FeedbackSource(feedback(), slot))) {
    case BinaryOperationHint::kSignedSmall:
      RETURN_IF_ABORT(BuildCheckSmi(value));
      break;
    case BinaryOperationHint::kSignedSmallInputs:
    case BinaryOperationHint::kAdditiveSafeInteger:
      UNREACHABLE();
    case BinaryOperationHint::kNumber:
    case BinaryOperationHint::kBigInt:
    case BinaryOperationHint::kBigInt64:
      if (mode == Object::Conversion::kToNumber &&
          EnsureType(value, NodeType::kNumber)) {
        return ReduceResult::Done();
      }
      AddNewNode<CheckNumber>({value}, mode);
      break;
    case BinaryOperationHint::kNone:
    // TODO(leszeks): Faster ToNumber for kNumberOrOddball
    case BinaryOperationHint::kNumberOrOddball:
    case BinaryOperationHint::kString:
    case BinaryOperationHint::kStringOrStringWrapper:
    case BinaryOperationHint::kAny:
      if (CheckType(value, NodeType::kNumber)) return ReduceResult::Done();
      SetAccumulator(AddNewNode<ToNumberOrNumeric>({value}, mode));
      break;
  }
  return ReduceResult::Done();
}
References broker(), v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::anonymous_namespace{ic.cc}::kIntPtr, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrOddball, v8::internal::kSignedSmall, v8::internal::kSignedSmallInputs, v8::internal::kString, v8::internal::kStringOrStringWrapper, v8::internal::Object::kToNumber, mode(), RETURN_IF_ABORT, v8::internal::UNREACHABLE(), and v8::internal::value.
BuildToString()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildToString (ValueNode * value, ToString::ConversionMode mode) [private]
Definition at line 12984 of file maglev-graph-builder.cc.
                                                                          {
  if (CheckType(value, NodeType::kString)) return value;
  // TODO(victorgomes): Add fast path for constant primitives.
  if (CheckType(value, NodeType::kNumber)) {
    // TODO(verwaest): Float64ToString if float.
    return AddNewNode<NumberToString>({value});
  }
  return AddNewNode<ToString>({GetContext(), value}, mode);
}
References mode(), and v8::internal::value.
BuildTransitionElementsKindAndCompareMaps()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps (ValueNode * heap_object, ValueNode * object_map, const ZoneVector< compiler::MapRef > & transition_sources, compiler::MapRef transition_target, MaglevSubGraphBuilder * sub_graph, std::optional< MaglevSubGraphBuilder::Label > & if_not_matched) [private]
Definition at line 5011 of file maglev-graph-builder.cc.
                                                             {
  DCHECK(!transition_target.is_migration_target());
  NodeInfo* known_info = GetOrCreateInfoFor(heap_object);
  // TODO(pthier): Calculate and use the intersection of known maps with
  // (transition_sources union transition_target).
  ValueNode* new_map = AddNewNode<TransitionElementsKind>(
      {heap_object, object_map}, transition_sources, transition_target);
  // TODO(pthier): Support map packing.
  DCHECK(!V8_MAP_PACKING_BOOL);
  if_not_matched.emplace(sub_graph, 1);
  sub_graph->GotoIfFalse<BranchIfReferenceEqual>(
      &*if_not_matched, {new_map, GetConstant(transition_target)});
  // After the branch, object's map is transition_target.
  DCHECK(transition_target.IsJSReceiverMap());
  known_info->SetPossibleMaps(
      PossibleMaps{transition_target}, !transition_target.is_stable(),
      StaticTypeForMap(transition_target, broker()), broker());
  if (!transition_target.is_stable()) {
    known_node_aspects().any_map_for_any_node_is_unstable = true;
  } else {
    broker()->dependencies()->DependOnStableMap(transition_target);
  }
  return ReduceResult::Done();
}
References v8::internal::maglev::KnownNodeAspects::any_map_for_any_node_is_unstable, broker(), v8::internal::DCHECK(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::maglev::ReduceResult::Done(), GetConstant(), GetOrCreateInfoFor(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse(), v8::internal::compiler::MapRef::is_migration_target(), v8::internal::compiler::MapRef::is_stable(), known_node_aspects(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), v8::internal::maglev::StaticTypeForMap(), and V8_MAP_PACKING_BOOL.
BuildTransitionElementsKindOrCheckMap()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap (ValueNode * heap_object, ValueNode * object_map, const ZoneVector< compiler::MapRef > & transition_sources, compiler::MapRef transition_target) [private]
Definition at line 4942 of file maglev-graph-builder.cc.
                                      {
  // TODO(marja): Optimizations based on what we know about the intersection of
  // known maps and transition sources or transition target.
  // TransitionElementsKind doesn't happen in cases where we'd need to do
  // CheckMapsWithMigration instead of CheckMaps.
  CHECK(!transition_target.is_migration_target());
  for (const compiler::MapRef transition_source : transition_sources) {
    CHECK(!transition_source.is_migration_target());
  }
  NodeInfo* known_info = GetOrCreateInfoFor(heap_object);
  AddNewNode<TransitionElementsKindOrCheckMap>(
      {heap_object, object_map}, transition_sources, transition_target);
  // After this operation, heap_object's map is transition_target (or we
  // deopted).
  known_info->SetPossibleMaps(
      PossibleMaps{transition_target}, !transition_target.is_stable(),
      StaticTypeForMap(transition_target, broker()), broker());
  DCHECK(transition_target.IsJSReceiverMap());
  if (!transition_target.is_stable()) {
    known_node_aspects().any_map_for_any_node_is_unstable = true;
  } else {
    broker()->dependencies()->DependOnStableMap(transition_target);
  }
  return ReduceResult::Done();
}
References v8::internal::maglev::KnownNodeAspects::any_map_for_any_node_is_unstable, broker(), CHECK, v8::internal::DCHECK(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::maglev::ReduceResult::Done(), GetOrCreateInfoFor(), v8::internal::compiler::MapRef::is_migration_target(), v8::internal::compiler::MapRef::is_stable(), known_node_aspects(), v8::internal::maglev::NodeInfo::SetPossibleMaps(), and v8::internal::maglev::StaticTypeForMap().
BuildTruncatingInt32BinaryOperationNodeForToNumber()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinaryOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2439 of file maglev-graph-builder.cc.
                                                   {
  static_assert(BinaryOperationIsBitwiseInt32<kOperation>());
  ValueNode* left;
  ValueNode* right;
  if (IsRegisterEqualToAccumulator(0)) {
    left = right = GetTruncatedInt32ForToNumber(
        current_interpreter_frame_.get(iterator_.GetRegisterOperand(0)),
        allowed_input_type, conversion_type);
  } else {
    left = GetTruncatedInt32ForToNumber(
        current_interpreter_frame_.get(iterator_.GetRegisterOperand(0)),
        allowed_input_type, conversion_type);
    right =
        GetTruncatedInt32ForToNumber(current_interpreter_frame_.accumulator(),
                                     allowed_input_type, conversion_type);
  }
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldInt32BinaryOperation<kOperation>(left, right), SetAccumulator);
  SetAccumulator(AddNewNode<Int32NodeFor<kOperation>>({left, right}));
  return ReduceResult::Done();
}
References v8::internal::maglev::InterpreterFrameState::accumulator(), AddNewNode(), current_interpreter_frame_, v8::internal::maglev::ReduceResult::Done(), v8::internal::maglev::InterpreterFrameState::get(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), GetTruncatedInt32ForToNumber(), IsRegisterEqualToAccumulator(), iterator_, PROCESS_AND_RETURN_IF_DONE, and SetAccumulator().
BuildTruncatingInt32BinarySmiOperationNodeForToNumber()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2488 of file maglev-graph-builder.cc.
                                                   {
  static_assert(BinaryOperationIsBitwiseInt32<kOperation>());
  ValueNode* left =
      GetTruncatedInt32ForToNumber(current_interpreter_frame_.accumulator(),
                                   allowed_input_type, conversion_type);
  int32_t constant = iterator_.GetImmediateOperand(0);
  if (std::optional<int>(constant) == Int32Identity<kOperation>()) {
    // If the constant is the unit of the operation, it already has the right
    // value, so use the truncated value (if not just a conversion) and return.
    if (!left->properties().is_conversion()) {
      current_interpreter_frame_.set_accumulator(left);
    }
    return ReduceResult::Done();
  }
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldInt32BinaryOperation<kOperation>(left, constant), SetAccumulator);
  ValueNode* right = GetInt32Constant(constant);
  SetAccumulator(AddNewNode<Int32NodeFor<kOperation>>({left, right}));
  return ReduceResult::Done();
}
References v8::internal::maglev::InterpreterFrameState::accumulator(), AddNewNode(), current_interpreter_frame_, v8::internal::maglev::ReduceResult::Done(), v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), GetInt32Constant(), GetTruncatedInt32ForToNumber(), v8::internal::maglev::OpProperties::is_conversion(), iterator_, PROCESS_AND_RETURN_IF_DONE, v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::InterpreterFrameState::set_accumulator(), and SetAccumulator().
Referenced by VisitBinarySmiOperation().
BuildTruncatingInt32BitwiseNotForToNumber()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BitwiseNotForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2346 of file maglev-graph-builder.cc.
                                                   {
  ValueNode* value =
      GetTruncatedInt32ForToNumber(current_interpreter_frame_.accumulator(),
                                   allowed_input_type, conversion_type);
  PROCESS_AND_RETURN_IF_DONE(
      TryFoldInt32UnaryOperation<Operation::kBitwiseNot>(value),
      SetAccumulator);
  SetAccumulator(AddNewNode<Int32BitwiseNot>({value}));
  return ReduceResult::Done();
}
References v8::internal::maglev::InterpreterFrameState::accumulator(), current_interpreter_frame_, v8::internal::maglev::ReduceResult::Done(), GetTruncatedInt32ForToNumber(), PROCESS_AND_RETURN_IF_DONE, SetAccumulator(), and v8::internal::value.
Referenced by VisitUnaryOperation().
BuildUnwrapStringWrapper()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::BuildUnwrapStringWrapper (ValueNode * input) [private]
Definition at line 2907 of file maglev-graph-builder.cc.
                                                                        {
  DCHECK(NodeTypeIs(GetType(input), NodeType::kStringOrStringWrapper));
  if (NodeTypeIs(GetType(input), NodeType::kString)) return input;
  return AddNewNode<UnwrapStringWrapper>({input});
}
References v8::internal::DCHECK(), GetType(), and v8::internal::maglev::NodeTypeIs().
Referenced by VisitBinaryOperation().
BuildVirtualArgumentsObject()
template<CreateArgumentsType type>
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::BuildVirtualArgumentsObject [private]
Definition at line 13845 of file maglev-graph-builder.cc.
                                                               {
  switch (type) {
    case CreateArgumentsType::kMappedArguments:
      if (parameter_count_without_receiver() == 0) {
        // If there is no aliasing, the arguments object elements are not
        // special in any way, we can just return an unmapped backing store.
        if (is_inline()) {
          int length = argument_count_without_receiver();
          ValueNode* elements = BuildInlinedArgumentsElements(0, length);
          return CreateArgumentsObject(
              broker()->target_native_context().sloppy_arguments_map(broker()),
              GetInt32Constant(length), elements, GetClosure());
        } else {
          ArgumentsLength* length = AddNewNode<ArgumentsLength>({});
          EnsureType(length, NodeType::kSmi);
          ArgumentsElements* elements = AddNewNode<ArgumentsElements>(
              {length}, CreateArgumentsType::kUnmappedArguments,
              parameter_count_without_receiver());
          return CreateArgumentsObject(
              broker()->target_native_context().sloppy_arguments_map(broker()),
              length, elements, GetClosure());
        }
      } else {
        // If the parameter count is zero, we should have used the unmapped
        // backing store.
        int param_count = parameter_count_without_receiver();
        DCHECK_GT(param_count, 0);
        DCHECK(CanAllocateSloppyArgumentElements());
        int param_idx_in_ctxt = compilation_unit_->shared_function_info()
                                    .context_parameters_start() +
                                param_count - 1;
        // The {unmapped_elements} correspond to the extra arguments
        // (overapplication) that do not need be "mapped" to the actual
        // arguments. Mapped arguments are accessed via the context, whereas
        // unmapped arguments are simply accessed via this fixed array. See
        // SloppyArgumentsElements in src/object/arguments.h.
        if (is_inline()) {
          int length = argument_count_without_receiver();
          int mapped_count = std::min(param_count, length);
          ValueNode* unmapped_elements =
              BuildInlinedUnmappedArgumentsElements(mapped_count);
          VirtualObject* elements = CreateMappedArgumentsElements(
              broker()->sloppy_arguments_elements_map(), mapped_count,
              GetContext(), unmapped_elements);
          for (int i = 0; i < mapped_count; i++, param_idx_in_ctxt--) {
            elements->set(SloppyArgumentsElements::OffsetOfElementAt(i),
                          GetInt32Constant(param_idx_in_ctxt));
          }
          return CreateArgumentsObject(
              broker()->target_native_context().fast_aliased_arguments_map(
                  broker()),
              GetInt32Constant(length), elements, GetClosure());
        } else {
          ArgumentsLength* length = AddNewNode<ArgumentsLength>({});
          EnsureType(length, NodeType::kSmi);
          ArgumentsElements* unmapped_elements = AddNewNode<ArgumentsElements>(
              {length}, CreateArgumentsType::kMappedArguments, param_count);
          VirtualObject* elements = CreateMappedArgumentsElements(
              broker()->sloppy_arguments_elements_map(), param_count,
              GetContext(), unmapped_elements);
          ValueNode* the_hole_value = GetConstant(broker()->the_hole_value());
          for (int i = 0; i < param_count; i++, param_idx_in_ctxt--) {
            ValueNode* value = Select(
                [&](auto& builder) {
                  return BuildBranchIfInt32Compare(builder,
                                                   Operation::kLessThan,
                                                   GetInt32Constant(i), length);
                },
                [&] { return GetSmiConstant(param_idx_in_ctxt); },
                [&] { return the_hole_value; });
            elements->set(SloppyArgumentsElements::OffsetOfElementAt(i), value);
          }
          return CreateArgumentsObject(
              broker()->target_native_context().fast_aliased_arguments_map(
                  broker()),
              length, elements, GetClosure());
        }
      }
    case CreateArgumentsType::kUnmappedArguments:
      if (is_inline()) {
        int length = argument_count_without_receiver();
        ValueNode* elements = BuildInlinedArgumentsElements(0, length);
        return CreateArgumentsObject(
            broker()->target_native_context().strict_arguments_map(broker()),
            GetInt32Constant(length), elements);
      } else {
        ArgumentsLength* length = AddNewNode<ArgumentsLength>({});
        EnsureType(length, NodeType::kSmi);
        ArgumentsElements* elements = AddNewNode<ArgumentsElements>(
            {length}, CreateArgumentsType::kUnmappedArguments,
            parameter_count_without_receiver());
        return CreateArgumentsObject(
            broker()->target_native_context().strict_arguments_map(broker()),
            length, elements);
      }
    case CreateArgumentsType::kRestParameter:
      if (is_inline()) {
        int start_index = parameter_count_without_receiver();
        int length =
            std::max(0, argument_count_without_receiver() - start_index);
        ValueNode* elements =
            BuildInlinedArgumentsElements(start_index, length);
        return CreateArgumentsObject(
            broker()->target_native_context().js_array_packed_elements_map(
                broker()),
            GetInt32Constant(length), elements);
      } else {
        ArgumentsLength* length = AddNewNode<ArgumentsLength>({});
        EnsureType(length, NodeType::kSmi);
        ArgumentsElements* elements = AddNewNode<ArgumentsElements>(
            {length}, CreateArgumentsType::kRestParameter,
            parameter_count_without_receiver());
        RestLength* rest_length =
            AddNewNode<RestLength>({}, parameter_count_without_receiver());
        return CreateArgumentsObject(
            broker()->target_native_context().js_array_packed_elements_map(
                broker()),
            rest_length, elements);
      }
  }
}
References broker(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::kLessThan, v8::internal::kMappedArguments, v8::internal::kRestParameter, v8::internal::compiler::kSmi, v8::internal::kUnmappedArguments, v8::internal::length, v8::internal::TaggedArrayBase< SloppyArgumentsElements, SloppyArgumentsElementsShape >::OffsetOfElementAt(), v8::internal::maglev::VirtualObject::set(), v8::internal::tracing::type, and v8::internal::value.
bytecode()
compiler::BytecodeArrayRef v8::internal::maglev::MaglevGraphBuilder::bytecode () const [inline], [private]
Definition at line 3121 of file maglev-graph-builder.h.
                                            {
    return compilation_unit_->bytecode();
  }
Referenced by BuildMergeStates(), BuildRegisterFrameInitialization(), GetResultLocationAndSize(), KillPeeledLoopTargets(), MaglevGraphBuilder(), MarkBytecodeDead(), and VisitSingleBytecode().
bytecode_analysis()
const compiler::BytecodeAnalysis& v8::internal::maglev::MaglevGraphBuilder::bytecode_analysis () const [inline], [private]
Definition at line 3124 of file maglev-graph-builder.h.
                                                            {
    return bytecode_analysis_;
  }
Referenced by BuildMergeStates(), and VisitSingleBytecode().
CalculatePredecessorCounts()
void v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts () [inline], [private]
Definition at line 3022 of file maglev-graph-builder.h.
                                    {
    // Add 1 after the end of the bytecode so we can always write to the offset
    // after the last bytecode.
    uint32_t array_length = bytecode().length() + 1;
    predecessor_count_ = zone()->AllocateArray<uint32_t>(array_length);
    MemsetUint32(predecessor_count_, 0, entrypoint_);
    MemsetUint32(predecessor_count_ + entrypoint_, 1,
                 array_length - entrypoint_);
    const int max_peelings = v8_flags.maglev_optimistic_peeled_loops ? 2 : 1;
    // We count jumps from peeled loops to outside of the loop twice.
    bool is_loop_peeling_iteration = false;
    std::optional<int> peeled_loop_end;
    interpreter::BytecodeArrayIterator iterator(bytecode().object());
    for (iterator.AdvanceTo(entrypoint_); !iterator.done();
         iterator.Advance()) {
      interpreter::Bytecode bytecode = iterator.current_bytecode();
      if (allow_loop_peeling_ &&
          bytecode_analysis().IsLoopHeader(iterator.current_offset())) {
        const compiler::LoopInfo& loop_info =
            bytecode_analysis().GetLoopInfoFor(iterator.current_offset());
        // Generators use irreducible control flow, which makes loop peeling too
        // complicated.
        int size = loop_info.loop_end() - loop_info.loop_start();
        if (loop_info.innermost() && !loop_info.resumable() &&
            iterator.next_offset() < loop_info.loop_end() &&
            size < v8_flags.maglev_loop_peeling_max_size &&
            size + graph_->total_peeled_bytecode_size() <
                v8_flags.maglev_loop_peeling_max_size_cumulative) {
          DCHECK(!is_loop_peeling_iteration);
          graph_->add_peeled_bytecode_size(size);
          is_loop_peeling_iteration = true;
          loop_headers_to_peel_.Add(iterator.current_offset());
          peeled_loop_end = bytecode_analysis().GetLoopEndOffsetForInnermost(
              iterator.current_offset());
        }
      }
      if (interpreter::Bytecodes::IsJump(bytecode)) {
        if (is_loop_peeling_iteration &&
            bytecode == interpreter::Bytecode::kJumpLoop) {
          DCHECK_EQ(iterator.next_offset(), peeled_loop_end);
          is_loop_peeling_iteration = false;
          peeled_loop_end = {};
        }
        if (iterator.GetJumpTargetOffset() < entrypoint_) {
          static_assert(kLoopsMustBeEnteredThroughHeader);
          if (predecessor_count(iterator.GetJumpTargetOffset()) == 1) {
            // We encountered a JumpLoop whose loop header is not reachable
            // otherwise. This loop is either dead or the JumpLoop will bail
            // with DeoptimizeReason::kOSREarlyExit.
            InitializePredecessorCount(iterator.GetJumpTargetOffset(), 0);
          }
        } else {
          UpdatePredecessorCount(iterator.GetJumpTargetOffset(), 1);
        }
        if (is_loop_peeling_iteration &&
            iterator.GetJumpTargetOffset() >= *peeled_loop_end) {
          // Jumps from within the peeled loop to outside need to be counted
          // twice, once for the peeled and once for the regular loop body.
          UpdatePredecessorCount(iterator.GetJumpTargetOffset(), max_peelings);
        }
        if (!interpreter::Bytecodes::IsConditionalJump(bytecode)) {
          UpdatePredecessorCount(iterator.next_offset(), -1);
        }
      } else if (interpreter::Bytecodes::IsSwitch(bytecode)) {
        for (auto offset : iterator.GetJumpTableTargetOffsets()) {
          UpdatePredecessorCount(offset.target_offset, 1);
        }
      } else if (interpreter::Bytecodes::Returns(bytecode) ||
                 interpreter::Bytecodes::UnconditionallyThrows(bytecode)) {
        UpdatePredecessorCount(iterator.next_offset(), -1);
        // Collect inline return jumps in the slot after the last bytecode.
        if (is_inline() && interpreter::Bytecodes::Returns(bytecode)) {
          UpdatePredecessorCount(array_length - 1, 1);
          if (is_loop_peeling_iteration) {
            UpdatePredecessorCount(array_length - 1, max_peelings);
          }
        }
      }
      // TODO(leszeks): Also consider handler entries (the bytecode analysis)
      // will do this automatically I guess if we merge this into that.
    }
    if (!is_inline()) {
      DCHECK_EQ(0, predecessor_count(bytecode().length()));
    }
  }
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::interpreter::BytecodeArrayIterator::AdvanceTo(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), DCHECK, DCHECK_EQ, v8::internal::interpreter::BytecodeArrayIterator::done(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTableTargetOffsets(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::compiler::LoopInfo::innermost(), v8::internal::length, v8::internal::compiler::LoopInfo::loop_end(), v8::internal::compiler::LoopInfo::loop_start(), v8::internal::MemsetUint32(), v8::internal::interpreter::BytecodeArrayIterator::next_offset(), v8::internal::compiler::LoopInfo::resumable(), size(), and v8::internal::v8_flags.
Referenced by MaglevGraphBuilder().
caller_details()
MaglevCallerDetails* v8::internal::maglev::MaglevGraphBuilder::caller_details () const [inline]
Definition at line 362 of file maglev-graph-builder.h.
{ return caller_details_; }
References caller_details_.
Referenced by MaglevGraphBuilder().
CanAllocateInlinedArgumentElements()
bool v8::internal::maglev::MaglevGraphBuilder::CanAllocateInlinedArgumentElements () [private]
Definition at line 14207 of file maglev-graph-builder.cc.
                                                            {
  DCHECK(is_inline());
  return FixedArray::SizeFor(argument_count_without_receiver()) <=
         kMaxRegularHeapObjectSize;
}
References v8::internal::DCHECK(), v8::internal::kMaxRegularHeapObjectSize, and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor().
CanAllocateSloppyArgumentElements()
bool v8::internal::maglev::MaglevGraphBuilder::CanAllocateSloppyArgumentElements () [private]
Definition at line 14202 of file maglev-graph-builder.cc.
                                                           {
  return SloppyArgumentsElements::SizeFor(parameter_count()) <=
         kMaxRegularHeapObjectSize;
}
References v8::internal::kMaxRegularHeapObjectSize, and v8::internal::TaggedArrayBase< SloppyArgumentsElements, SloppyArgumentsElementsShape >::SizeFor().
CanElideWriteBarrier()
bool v8::internal::maglev::MaglevGraphBuilder::CanElideWriteBarrier (ValueNode * object, ValueNode * value) [private]
Definition at line 5056 of file maglev-graph-builder.cc.
                                                                {
  if (value->Is<RootConstant>() || value->Is<ConsStringMap>()) return true;
  if (!IsEmptyNodeType(GetType(value)) && CheckType(value, NodeType::kSmi)) {
    RecordUseReprHintIfPhi(value, UseRepresentation::kTagged);
    return true;
  }
  // No need for a write barrier if both object and value are part of the same
  // folded young allocation.
  AllocationBlock* allocation = GetAllocation(object);
  if (allocation != nullptr && current_allocation_block_ == allocation &&
      allocation->allocation_type() == AllocationType::kYoung &&
      allocation == GetAllocation(value)) {
    allocation->set_elided_write_barriers_depend_on_type();
    return true;
  }
  // If tagged and not Smi, we cannot elide write barrier.
  if (value->is_tagged()) return false;
  // If its alternative conversion node is Smi, {value} will be converted to
  // a Smi when tagged.
  NodeInfo* node_info = GetOrCreateInfoFor(value);
  if (ValueNode* tagged_alt = node_info->alternative().tagged()) {
    DCHECK(tagged_alt->properties().is_conversion());
    return CheckType(tagged_alt, NodeType::kSmi);
  }
  return false;
}
References v8::internal::maglev::AllocationBlock::allocation_type(), v8::internal::maglev::NodeInfo::alternative(), CheckType(), current_allocation_block_, v8::internal::DCHECK(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetAllocation(), GetOrCreateInfoFor(), GetType(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::kYoung, RecordUseReprHintIfPhi(), v8::internal::maglev::AllocationBlock::set_elided_write_barriers_depend_on_type(), and v8::internal::value.
Referenced by BuildStoreFixedArrayElement(), BuildStoreTaggedField(), and BuildStoreTaggedFieldNoWriteBarrier().
CanInlineCall()
bool v8::internal::maglev::MaglevGraphBuilder::CanInlineCall (compiler::SharedFunctionInfoRef shared, float call_frequency) [private]
Definition at line 8437 of file maglev-graph-builder.cc.
                                                             {
  if (graph()->total_inlined_bytecode_size() >
      max_inlined_bytecode_size_cumulative()) {
    compilation_unit_->info()->set_could_not_inline_all_candidates();
    TRACE_CANNOT_INLINE("maximum inlined bytecode size");
    return false;
  }
  // TODO(olivf): This is a temporary stopgap to prevent infinite recursion when
  // inlining, because we currently excempt small functions from some of the
  // negative heuristics. We should refactor these heuristics and make sure they
  // make sense in the presence of (mutually) recursive inlining. Please do
  // *not* return true before this check.
  if (inlining_depth() > v8_flags.max_maglev_hard_inline_depth) {
    TRACE_CANNOT_INLINE("inlining depth ("
                        << inlining_depth() << ") >= hard-max-depth ("
                        << v8_flags.max_maglev_hard_inline_depth << ")");
    return false;
  }
  if (compilation_unit_->shared_function_info().equals(shared)) {
    TRACE_CANNOT_INLINE("direct recursion");
    return false;
  }
  SharedFunctionInfo::Inlineability inlineability =
      shared.GetInlineability(CodeKind::MAGLEV, broker());
  if (inlineability != SharedFunctionInfo::Inlineability::kIsInlineable) {
    TRACE_CANNOT_INLINE(inlineability);
    return false;
  }
  // TODO(victorgomes): Support NewTarget/RegisterInput in inlined functions.
  compiler::BytecodeArrayRef bytecode = shared.GetBytecodeArray(broker());
  if (bytecode.incoming_new_target_or_generator_register().is_valid()) {
    TRACE_CANNOT_INLINE("use unsupported NewTargetOrGenerator register");
    return false;
  }
  if (call_frequency < min_inlining_frequency()) {
    TRACE_CANNOT_INLINE("call frequency (" << call_frequency
                                           << ") < minimum threshold ("
                                           << min_inlining_frequency() << ")");
    return false;
  }
  if (bytecode.length() > max_inlined_bytecode_size()) {
    TRACE_CANNOT_INLINE("big function, size ("
                        << bytecode.length() << ") >= max-size ("
                        << max_inlined_bytecode_size() << ")");
    return false;
  }
  return true;
}
References broker(), v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::compiler::SharedFunctionInfoRef::GetInlineability(), graph(), v8::internal::compiler::BytecodeArrayRef::incoming_new_target_or_generator_register(), v8::internal::interpreter::Register::is_valid(), v8::internal::compiler::BytecodeArrayRef::length(), TRACE_CANNOT_INLINE, and v8::internal::v8_flags.
CanSpeculateCall() [1/2]
bool v8::internal::maglev::MaglevGraphBuilder::CanSpeculateCall () const [inline], [private]
Definition at line 3362 of file maglev-graph-builder.h.
                                {
    return current_speculation_mode_ == SpeculationMode::kAllowSpeculation;
  }
CanSpeculateCall() [2/2]
bool v8::internal::maglev::MaglevGraphBuilder::CanSpeculateCall (std::initializer_list< SpeculationMode > supported_modes) const [inline], [private]
Definition at line 3366 of file maglev-graph-builder.h.
                                                                  {
    return CanSpeculateCall() ||
           std::find(supported_modes.begin(), supported_modes.end(),
                     current_speculation_mode_) != supported_modes.end();
  }
CanTrackObjectChanges()
bool v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges (ValueNode * object, TrackObjectMode mode) [private]
Definition at line 5146 of file maglev-graph-builder.cc.
                                                                     {
  DCHECK(!receiver->Is<VirtualObject>());
  if (!v8_flags.maglev_object_tracking) return false;
  if (!receiver->Is<InlinedAllocation>()) return false;
  InlinedAllocation* alloc = receiver->Cast<InlinedAllocation>();
  if (mode == TrackObjectMode::kStore) {
    // If we have two objects A and B, such that A points to B (it contains B in
    // one of its field), we cannot change B without also changing A, even if
    // both can be elided. For now, we escape both objects instead.
    if (graph_->allocations_elide_map().find(alloc) !=
        graph_->allocations_elide_map().end()) {
      return false;
    }
    if (alloc->IsEscaping()) return false;
    // Ensure object is escaped if we are within a try-catch block. This is
    // crucial because a deoptimization point inside the catch handler could
    // re-materialize objects differently, depending on whether the throw
    // occurred before or after this store. We could potentially relax this
    // requirement by verifying that no throwable nodes have been emitted since
    // the try-block started, but for now, err on the side of caution and
    // always escape.
    if (IsInsideTryBlock()) return false;
  } else {
    DCHECK_EQ(mode, TrackObjectMode::kLoad);
    if (IsEscaping(graph_, alloc)) return false;
  }
  // We don't support loop phis inside VirtualObjects, so any access inside a
  // loop should escape the object, except for objects that were created since
  // the last loop header.
  if (IsInsideLoop()) {
    if (!is_loop_effect_tracking() ||
        !loop_effects_->allocations.contains(alloc)) {
      return false;
    }
  }
  // Iterate all live objects to be sure that the allocation is not escaping.
  SLOW_DCHECK(
      VerifyIsNotEscaping(current_interpreter_frame_.virtual_objects(), alloc));
  return true;
}
References v8::internal::maglev::LoopEffects::allocations, v8::internal::maglev::Graph::allocations_elide_map(), v8::internal::maglev::NodeBase::Cast(), current_interpreter_frame_, v8::internal::DCHECK(), DCHECK_EQ, graph_, v8::internal::maglev::NodeBase::Is(), is_loop_effect_tracking(), v8::internal::maglev::InlinedAllocation::IsEscaping(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsEscaping(), IsInsideLoop(), IsInsideTryBlock(), kLoad, kStore, loop_effects_, mode(), SLOW_DCHECK, v8::internal::v8_flags, v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::VerifyIsNotEscaping(), and v8::internal::maglev::InterpreterFrameState::virtual_objects().
Referenced by BuildLoadFixedArrayElement(), BuildLoadFixedDoubleArrayElement(), and TryBuildStoreTaggedFieldToAllocation().
CanTreatHoleAsUndefined()
bool v8::internal::maglev::MaglevGraphBuilder::CanTreatHoleAsUndefined (base::Vector< const compiler::MapRef > const & receiver_maps) [private]
Definition at line 5397 of file maglev-graph-builder.cc.
                                                           {
  // Check if all {receiver_maps} have one of the initial Array.prototype
  // or Object.prototype objects as their prototype (in any of the current
  // native contexts, as the global Array protector works isolate-wide).
  for (compiler::MapRef receiver_map : receiver_maps) {
    compiler::ObjectRef receiver_prototype = receiver_map.prototype(broker());
    if (!receiver_prototype.IsJSObject() ||
        !broker()->IsArrayOrObjectPrototype(receiver_prototype.AsJSObject())) {
      return false;
    }
  }
  // Check if the array prototype chain is intact.
  return broker()->dependencies()->DependOnNoElementsProtector();
}
References broker(), v8::internal::compiler::JSHeapBroker::dependencies(), and v8::internal::compiler::CompilationDependencies::DependOnNoElementsProtector().
CheckContextExtensions()
bool v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions (size_t depth) [private]
Definition at line 4363 of file maglev-graph-builder.cc.
                                                            {
  compiler::OptionalScopeInfoRef maybe_scope_info =
      graph()->TryGetScopeInfo(GetContext());
  if (!maybe_scope_info.has_value()) return false;
  compiler::ScopeInfoRef scope_info = maybe_scope_info.value();
  for (uint32_t d = 0; d < depth; d++) {
    CHECK_NE(scope_info.scope_type(), ScopeType::SCRIPT_SCOPE);
    CHECK_NE(scope_info.scope_type(), ScopeType::REPL_MODE_SCOPE);
    if (scope_info.HasContextExtensionSlot() &&
        !broker()->dependencies()->DependOnEmptyContextExtension(scope_info)) {
      // Using EmptyContextExtension dependency is not possible for this
      // scope_info, so generate dynamic checks.
      ValueNode* context = GetContextAtDepth(GetContext(), d);
      // Only support known contexts so that we can check that there's no
      // extension at compile time. Otherwise we could end up in a deopt loop
      // once we do get an extension.
      compiler::OptionalHeapObjectRef maybe_ref = TryGetConstant(context);
      if (!maybe_ref) return false;
      compiler::ContextRef context_ref = maybe_ref.value().AsContext();
      compiler::OptionalObjectRef extension_ref =
          context_ref.get(broker(), Context::EXTENSION_INDEX);
      // The extension may be concurrently installed while we're checking the
      // context, in which case it may still be uninitialized. This still
      // means an extension is about to appear, so we should block this
      // optimization.
      if (!extension_ref) return false;
      if (!extension_ref->IsUndefined()) return false;
      ValueNode* extension =
          LoadAndCacheContextSlot(context, Context::EXTENSION_INDEX, kMutable,
                                  ContextMode::kNoContextCells);
      AddNewNode<CheckValue>({extension}, broker()->undefined_value(),
                             DeoptimizeReason::kUnexpectedContextExtension);
    }
    CHECK_IMPLIES(!scope_info.HasOuterScopeInfo(), d + 1 == depth);
    if (scope_info.HasOuterScopeInfo()) {
      scope_info = scope_info.OuterScopeInfo(broker());
    }
  }
  return true;
}
References broker(), CHECK_IMPLIES, CHECK_NE, v8::internal::Context::EXTENSION_INDEX, v8::internal::compiler::ContextRef::get(), GetContext(), GetContextAtDepth(), graph(), v8::internal::compiler::ScopeInfoRef::HasContextExtensionSlot(), v8::internal::compiler::ScopeInfoRef::HasOuterScopeInfo(), kMutable, v8::internal::kNoContextCells, LoadAndCacheContextSlot(), v8::internal::compiler::ScopeInfoRef::OuterScopeInfo(), v8::internal::REPL_MODE_SCOPE, v8::internal::compiler::ScopeInfoRef::scope_type(), v8::internal::SCRIPT_SCOPE, TryGetConstant(), and v8::internal::maglev::Graph::TryGetScopeInfo().
CheckType()
bool v8::internal::maglev::MaglevGraphBuilder::CheckType (ValueNode * node, NodeType type, NodeType * old = nullptr) [inline], [private]
Definition at line 528 of file maglev-graph-builder.h.
                                                                          {
    return known_node_aspects().CheckType(broker(), node, type, old);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::CheckType(), known_node_aspects(), and v8::internal::tracing::type.
Referenced by BuildTestUndetectable(), CanElideWriteBarrier(), GetInt32(), GetInt32ElementIndex(), GetInternalizedString(), TryReduceCompareEqualAgainstConstant(), and VisitCompareOperation().
CheckTypes()
NodeType v8::internal::maglev::MaglevGraphBuilder::CheckTypes (ValueNode * node, std::initializer_list< NodeType > types) [inline], [private]
Definition at line 531 of file maglev-graph-builder.h.
                                                                            {
    return known_node_aspects().CheckTypes(broker(), node, types);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::CheckTypes(), and known_node_aspects().
Referenced by TryReduceTypeOf().
ClearCurrentAllocationBlock()
void v8::internal::maglev::MaglevGraphBuilder::ClearCurrentAllocationBlock () [private]
Definition at line 13662 of file maglev-graph-builder.cc.
                                                     {
  current_allocation_block_ = nullptr;
}
ClobberAccumulator()
void v8::internal::maglev::MaglevGraphBuilder::ClobberAccumulator () [inline], [private]
Definition at line 1725 of file maglev-graph-builder.h.
                            {
    DCHECK(interpreter::Bytecodes::ClobbersAccumulator(
        iterator_.current_bytecode()));
    current_interpreter_frame_.set_accumulator(
        graph()->GetRootConstant(RootIndex::kOptimizedOut));
  }
References DCHECK, and graph().
compilation_unit()
MaglevCompilationUnit* v8::internal::maglev::MaglevGraphBuilder::compilation_unit () const [inline]
Definition at line 358 of file maglev-graph-builder.h.
{ return compilation_unit_; }
References compilation_unit_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromHoleyFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromIntPtrToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromUint32ToTagged(), MaglevGraphBuilder(), v8::internal::maglev::MergePointInterpreterFrameState::Merge(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop(), and VisitSingleBytecode().
ContextMayAlias()
bool v8::internal::maglev::MaglevGraphBuilder::ContextMayAlias (ValueNode * context, compiler::OptionalScopeInfoRef scope_info) [private]
Definition at line 3601 of file maglev-graph-builder.cc.
                                                                 {
  // Distinguishing contexts by their scope info only works if scope infos are
  // guaranteed to be unique.
  // TODO(crbug.com/401059828): reenable when crashes are gone.
  if ((true) || !v8_flags.reuse_scope_infos) return true;
  if (!scope_info.has_value()) {
    return true;
  }
  auto other = graph()->TryGetScopeInfo(context);
  if (!other.has_value()) {
    return true;
  }
  return scope_info->equals(*other);
}
References graph(), v8::internal::maglev::Graph::TryGetScopeInfo(), and v8::internal::v8_flags.
Referenced by StoreAndCacheContextSlot().
ConvertForStoring()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::ConvertForStoring (ValueNode * node, ElementsKind kind) [private]
Definition at line 6607 of file maglev-graph-builder.cc.
                                                                      {
  if (IsDoubleElementsKind(kind)) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    if (kind == ElementsKind::HOLEY_DOUBLE_ELEMENTS) {
        RecordUseReprHintIfPhi(value, UseRepresentation::kHoleyFloat64);
        const bool convert_hole_to_undefined = true;
        return GetHoleyFloat64(value, convert_hole_to_undefined);
    }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    // Make sure we do not store signalling NaNs into double arrays.
    // TODO(leszeks): Consider making this a bit on StoreFixedDoubleArrayElement
    // rather than a separate node.
    return GetSilencedNaN(GetFloat64(value));
  }
  if (IsSmiElementsKind(kind)) return GetSmiValue(value);
  return value;
}
References v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::IsDoubleElementsKind(), v8::internal::IsSmiElementsKind(), and v8::internal::value.
ConvertInputTo()
template<UseReprHintRecording hint = UseReprHintRecording::kRecord>
ValueNode* v8::internal::maglev::MaglevGraphBuilder::ConvertInputTo (ValueNode * input, ValueRepresentation expected) [inline], [private]
Definition at line 1921 of file maglev-graph-builder.h.
                                                                            {
    ValueRepresentation repr = input->properties().value_representation();
    if (repr == expected) return input;
    switch (expected) {
      case ValueRepresentation::kTagged:
        return GetTaggedValue(input, hint);
      case ValueRepresentation::kInt32:
        return GetInt32(input);
      case ValueRepresentation::kFloat64:
      case ValueRepresentation::kHoleyFloat64:
        return GetFloat64(input);
      case ValueRepresentation::kUint32:
      case ValueRepresentation::kIntPtr:
        // These conversion should be explicitly done beforehand.
        UNREACHABLE();
    }
  }
References v8::internal::anonymous_namespace{ic.cc}::kIntPtr, v8::internal::maglev::NodeBase::properties(), UNREACHABLE, and v8::internal::maglev::OpProperties::value_representation().
CreateArgumentsObject()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateArgumentsObject (compiler::MapRef map, ValueNode * length, ValueNode * elements, std::optional< ValueNode * > callee = {}) [private]
Definition at line 13523 of file maglev-graph-builder.cc.
                                    {
  DCHECK_EQ(JSSloppyArgumentsObject::kLengthOffset, JSArray::kLengthOffset);
  DCHECK_EQ(JSStrictArgumentsObject::kLengthOffset, JSArray::kLengthOffset);
  int slot_count = map.instance_size() / kTaggedSize;
  SBXCHECK_EQ(slot_count, callee.has_value() ? 5 : 4);
  VirtualObject* arguments = CreateVirtualObject(map, slot_count);
  arguments->set(JSArray::kPropertiesOrHashOffset,
                 GetRootConstant(RootIndex::kEmptyFixedArray));
  arguments->set(JSArray::kElementsOffset, elements);
  CHECK(length->Is<Int32Constant>() || length->Is<ArgumentsLength>() ||
        length->Is<RestLength>());
  arguments->set(JSArray::kLengthOffset, length);
  if (callee.has_value()) {
    arguments->set(JSSloppyArgumentsObject::kCalleeOffset, callee.value());
  }
  DCHECK(arguments->map().IsJSArgumentsObjectMap() ||
         arguments->map().IsJSArrayMap());
  return arguments;
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::MapRef::instance_size(), v8::internal::kTaggedSize, v8::internal::length, v8::internal::maglev::VirtualObject::map(), SBXCHECK_EQ, and v8::internal::maglev::VirtualObject::set().
CreateBranchBuilder() [1/2]
BranchBuilder v8::internal::maglev::MaglevGraphBuilder::CreateBranchBuilder (BranchType jump_type = BranchType::kBranchIfTrue) [inline], [private]
Definition at line 2972 of file maglev-graph-builder.h.
                                                      {
    return BranchBuilder(this, jump_type);
  }
CreateBranchBuilder() [2/2]
BranchBuilder v8::internal::maglev::MaglevGraphBuilder::CreateBranchBuilder (MaglevSubGraphBuilder * subgraph, MaglevSubGraphBuilder::Label * jump_label, BranchType jump_type = BranchType::kBranchIfTrue) [inline], [private]
Definition at line 2976 of file maglev-graph-builder.h.
                                                      {
    return BranchBuilder(this, subgraph, jump_type, jump_label);
  }
CreateConsString()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateConsString (ValueNode * map, ValueNode * length, ValueNode * first, ValueNode * second) [private]
Definition at line 13412 of file maglev-graph-builder.cc.
                                                                       {
  return NodeBase::New<VirtualObject>(
      zone(), 0, NewObjectId(),
      VirtualObject::VirtualConsString{map, length, {first, second}});
}
References v8::internal::length.
Referenced by TryBuildNewConsString().
CreateContext()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateContext (compiler::MapRef map, int length, compiler::ScopeInfoRef scope_info, ValueNode * previous_context, std::optional< ValueNode * > extension = {}) [private]
Definition at line 13499 of file maglev-graph-builder.cc.
                                                                    {
  int slot_count = FixedArray::SizeFor(length) / kTaggedSize;
  VirtualObject* context = CreateVirtualObject(map, slot_count);
  context->set(Context::kLengthOffset, GetInt32Constant(length));
  context->set(Context::OffsetOfElementAt(Context::SCOPE_INFO_INDEX),
               GetConstant(scope_info));
  context->set(Context::OffsetOfElementAt(Context::PREVIOUS_INDEX),
               previous_context);
  int index = Context::PREVIOUS_INDEX + 1;
  if (extension.has_value()) {
    context->set(Context::OffsetOfElementAt(Context::EXTENSION_INDEX),
                 extension.value());
    index++;
  }
  for (; index < length; index++) {
    context->set(Context::OffsetOfElementAt(index),
                 GetRootConstant(RootIndex::kUndefinedValue));
  }
  EnsureType(context, NodeType::kContext);
  return context;
}
References v8::internal::Context::EXTENSION_INDEX, v8::internal::index, v8::internal::kTaggedSize, v8::internal::length, v8::internal::Context::OffsetOfElementAt(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::maglev::VirtualObject::set(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor().
CreateDoubleFixedArray()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateDoubleFixedArray (uint32_t elements_length, compiler::FixedDoubleArrayRef elements) [private]
Definition at line 13403 of file maglev-graph-builder.cc.
                                                                    {
  // VirtualObjects are not added to the Maglev graph.
  VirtualObject* vobject = NodeBase::New<VirtualObject>(
      zone(), 0, broker()->fixed_double_array_map(), NewObjectId(),
      elements_length, elements);
  return vobject;
}
References broker().
CreateEdgeSplitBlock()
BasicBlock* v8::internal::maglev::MaglevGraphBuilder::CreateEdgeSplitBlock (BasicBlockRef & jump_targets, BasicBlock * predecessor) [inline], [private]
Definition at line 592 of file maglev-graph-builder.h.
                                                            {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << "== New empty block ==" << std::endl;
      PrintVirtualObjects();
    }
    DCHECK_NULL(current_block_);
    current_block_ = zone()->New<BasicBlock>(nullptr, zone());
    BasicBlock* result = FinishBlock<Jump>({}, &jump_targets);
    result->set_edge_split_block(predecessor);
#ifdef DEBUG
    new_nodes_.clear();
#endif
    return result;
  }
References current_block_, DCHECK_NULL, v8::internal::Zone::New(), PrintVirtualObjects(), v8::base::internal::result, v8::internal::v8_flags, and zone().
Referenced by ProcessMergePointPredecessors().
CreateFixedArray()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateFixedArray (compiler::MapRef map, int length) [private]
Definition at line 13489 of file maglev-graph-builder.cc.
                                                                {
  int slot_count = FixedArray::SizeFor(length) / kTaggedSize;
  VirtualObject* array = CreateVirtualObject(map, slot_count);
  array->set(offsetof(FixedArray, length_), GetInt32Constant(length));
  array->ClearSlots(offsetof(FixedArray, length_),
                    GetRootConstant(RootIndex::kOnePointerFillerMap));
  return array;
}
References v8::internal::maglev::VirtualObject::ClearSlots(), v8::internal::kTaggedSize, v8::internal::length, v8::internal::maglev::VirtualObject::set(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor().
CreateHeapNumber()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateHeapNumber (Float64 value) [private]
Definition at line 13396 of file maglev-graph-builder.cc.
                                                                 {
  // VirtualObjects are not added to the Maglev graph.
  VirtualObject* vobject = NodeBase::New<VirtualObject>(
      zone(), 0, broker()->heap_number_map(), NewObjectId(), value);
  return vobject;
}
References broker(), and v8::internal::value.
CreateJSArray()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::CreateJSArray (compiler::MapRef map, int instance_size, ValueNode * length) [private]
Definition at line 13436 of file maglev-graph-builder.cc.
                                                                  {
  int slot_count = instance_size / kTaggedSize;
  SBXCHECK_GE(slot_count, 4);
  VirtualObject* object = CreateVirtualObject(map, slot_count);
  object->set(JSArray::kPropertiesOrHashOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  // Either the value is a Smi already, or we force a conversion to Smi and
  // cache the value in its alternative representation node.
  RETURN_IF_ABORT(GetSmiValue(length));
  object->set(JSArray::kElementsOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSArray::kLengthOffset, length);
  object->ClearSlots(JSArray::kLengthOffset,
                     GetRootConstant(RootIndex::kOnePointerFillerMap));
  return object;
}
References v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue(), v8::internal::kTaggedSize, v8::internal::length, RETURN_IF_ABORT, and SBXCHECK_GE.
CreateJSArrayIterator()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateJSArrayIterator (compiler::MapRef map, ValueNode * iterated_object, IterationKind kind) [private]
Definition at line 13455 of file maglev-graph-builder.cc.
                                                                        {
  int slot_count = map.instance_size() / kTaggedSize;
  SBXCHECK_EQ(slot_count, 6);
  VirtualObject* object = CreateVirtualObject(map, slot_count);
  object->set(JSArrayIterator::kPropertiesOrHashOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSArrayIterator::kElementsOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSArrayIterator::kIteratedObjectOffset, iterated_object);
  object->set(JSArrayIterator::kNextIndexOffset, GetInt32Constant(0));
  object->set(JSArrayIterator::kKindOffset,
              GetInt32Constant(static_cast<int>(kind)));
  return object;
}
References v8::internal::compiler::MapRef::instance_size(), v8::internal::kTaggedSize, and SBXCHECK_EQ.
CreateJSConstructor()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateJSConstructor (compiler::JSFunctionRef constructor) [private]
Definition at line 13471 of file maglev-graph-builder.cc.
                                       {
  compiler::SlackTrackingPrediction prediction =
      broker()->dependencies()->DependOnInitialMapInstanceSizePrediction(
          constructor);
  int slot_count = prediction.instance_size() / kTaggedSize;
  VirtualObject* object =
      CreateVirtualObject(constructor.initial_map(broker()), slot_count);
  SBXCHECK_GE(slot_count, 3);
  object->set(JSObject::kPropertiesOrHashOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSObject::kElementsOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->ClearSlots(JSObject::kElementsOffset,
                     GetRootConstant(RootIndex::kOnePointerFillerMap));
  return object;
}
References broker(), v8::internal::compiler::JSFunctionRef::initial_map(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::kTaggedSize, and SBXCHECK_GE.
CreateJSGeneratorObject()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateJSGeneratorObject (compiler::MapRef map, int instance_size, ValueNode * context, ValueNode * closure, ValueNode * receiver, ValueNode * register_file) [private]
Definition at line 13577 of file maglev-graph-builder.cc.
                                                                       {
  int slot_count = instance_size / kTaggedSize;
  InstanceType instance_type = map.instance_type();
  DCHECK(instance_type == JS_GENERATOR_OBJECT_TYPE ||
         instance_type == JS_ASYNC_GENERATOR_OBJECT_TYPE);
  SBXCHECK_GE(slot_count, instance_type == JS_GENERATOR_OBJECT_TYPE ? 10 : 12);
  VirtualObject* object = CreateVirtualObject(map, slot_count);
  object->set(JSGeneratorObject::kPropertiesOrHashOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSGeneratorObject::kElementsOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSGeneratorObject::kContextOffset, context);
  object->set(JSGeneratorObject::kFunctionOffset, closure);
  object->set(JSGeneratorObject::kReceiverOffset, receiver);
  object->set(JSGeneratorObject::kInputOrDebugPosOffset,
              GetRootConstant(RootIndex::kUndefinedValue));
  object->set(JSGeneratorObject::kResumeModeOffset,
              GetInt32Constant(JSGeneratorObject::kNext));
  object->set(JSGeneratorObject::kContinuationOffset,
              GetInt32Constant(JSGeneratorObject::kGeneratorExecuting));
  object->set(JSGeneratorObject::kParametersAndRegistersOffset, register_file);
  if (instance_type == JS_ASYNC_GENERATOR_OBJECT_TYPE) {
    object->set(JSAsyncGeneratorObject::kQueueOffset,
                GetRootConstant(RootIndex::kUndefinedValue));
    object->set(JSAsyncGeneratorObject::kIsAwaitingOffset, GetInt32Constant(0));
  }
  return object;
}
References v8::internal::DCHECK(), v8::internal::compiler::MapRef::instance_type(), v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::JSGeneratorObject::kNext, v8::internal::kTaggedSize, and SBXCHECK_GE.
CreateJSIteratorResult()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateJSIteratorResult (compiler::MapRef map, ValueNode * value, ValueNode * done) [private]
Definition at line 13608 of file maglev-graph-builder.cc.
                                                                           {
  static_assert(JSIteratorResult::kSize == 5 * kTaggedSize);
  int slot_count = JSIteratorResult::kSize / kTaggedSize;
  VirtualObject* iter_result = CreateVirtualObject(map, slot_count);
  iter_result->set(JSIteratorResult::kPropertiesOrHashOffset,
                   GetRootConstant(RootIndex::kEmptyFixedArray));
  iter_result->set(JSIteratorResult::kElementsOffset,
                   GetRootConstant(RootIndex::kEmptyFixedArray));
  iter_result->set(JSIteratorResult::kValueOffset, value);
  iter_result->set(JSIteratorResult::kDoneOffset, done);
  return iter_result;
}
References v8::internal::kTaggedSize, v8::internal::maglev::VirtualObject::set(), and v8::internal::value.
CreateJSObject()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateJSObject (compiler::MapRef map) [private]
Definition at line 13421 of file maglev-graph-builder.cc.
                                                                    {
  DCHECK(!map.is_dictionary_map());
  DCHECK(!map.IsInobjectSlackTrackingInProgress());
  int slot_count = map.instance_size() / kTaggedSize;
  SBXCHECK_GE(slot_count, 3);
  VirtualObject* object = CreateVirtualObject(map, slot_count);
  object->set(JSObject::kPropertiesOrHashOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->set(JSObject::kElementsOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  object->ClearSlots(JSObject::kElementsOffset,
                     GetRootConstant(RootIndex::kOnePointerFillerMap));
  return object;
}
References v8::internal::DCHECK(), v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress(), v8::internal::kTaggedSize, and SBXCHECK_GE.
CreateJSStringIterator()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateJSStringIterator (compiler::MapRef map, ValueNode * string) [private]
Definition at line 13623 of file maglev-graph-builder.cc.
                                                                             {
  static_assert(JSStringIterator::kHeaderSize == 5 * kTaggedSize);
  int slot_count = JSStringIterator::kHeaderSize / kTaggedSize;
  VirtualObject* string_iter = CreateVirtualObject(map, slot_count);
  string_iter->set(JSStringIterator::kPropertiesOrHashOffset,
                   GetRootConstant(RootIndex::kEmptyFixedArray));
  string_iter->set(JSStringIterator::kElementsOffset,
                   GetRootConstant(RootIndex::kEmptyFixedArray));
  string_iter->set(JSStringIterator::kStringOffset, string);
  string_iter->set(JSStringIterator::kIndexOffset, GetInt32Constant(0));
  return string_iter;
}
References v8::internal::kTaggedSize, and v8::internal::maglev::VirtualObject::set().
CreateMappedArgumentsElements()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateMappedArgumentsElements (compiler::MapRef map, int mapped_count, ValueNode * context, ValueNode * unmapped_elements) [private]
Definition at line 13545 of file maglev-graph-builder.cc.
                                  {
  int slot_count = SloppyArgumentsElements::SizeFor(mapped_count) / kTaggedSize;
  VirtualObject* elements = CreateVirtualObject(map, slot_count);
  elements->set(offsetof(SloppyArgumentsElements, length_),
                GetInt32Constant(mapped_count));
  elements->set(offsetof(SloppyArgumentsElements, context_), context);
  elements->set(offsetof(SloppyArgumentsElements, arguments_),
                unmapped_elements);
  return elements;
}
References v8::internal::kTaggedSize, v8::internal::maglev::VirtualObject::set(), and v8::internal::TaggedArrayBase< SloppyArgumentsElements, SloppyArgumentsElementsShape >::SizeFor().
CreateNewConstantNode()
template<typename NodeT , typename... Args>
NodeT* v8::internal::maglev::MaglevGraphBuilder::CreateNewConstantNode (Args &&... args) const [inline], [private]
Definition at line 1124 of file maglev-graph-builder.h.
                                                     {
    static_assert(IsConstantNode(Node::opcode_of<NodeT>));
    NodeT* node = NodeBase::New<NodeT>(zone(), std::forward<Args>(args)...);
    static_assert(!NodeT::kProperties.can_eager_deopt());
    static_assert(!NodeT::kProperties.can_lazy_deopt());
    static_assert(!NodeT::kProperties.can_throw());
    static_assert(!NodeT::kProperties.can_write());
    if (has_graph_labeller()) graph_labeller()->RegisterNode(node);
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " " << node << " "
                << PrintNodeLabel(graph_labeller(), node) << ": "
                << PrintNode(graph_labeller(), node) << std::endl;
    }
    return node;
  }
References v8::base::args, graph_labeller(), has_graph_labeller(), v8::internal::maglev::IsConstantNode(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), v8::internal::v8_flags, and zone().
CreateRegExpLiteralObject()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject (compiler::MapRef map, compiler::RegExpBoilerplateDescriptionRef literal) [private]
Definition at line 13558 of file maglev-graph-builder.cc.
                                                                         {
  DCHECK_EQ(JSRegExp::Size(), JSRegExp::kLastIndexOffset + kTaggedSize);
  int slot_count = JSRegExp::Size() / kTaggedSize;
  VirtualObject* regexp = CreateVirtualObject(map, slot_count);
  regexp->set(JSRegExp::kPropertiesOrHashOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  regexp->set(JSRegExp::kElementsOffset,
              GetRootConstant(RootIndex::kEmptyFixedArray));
  regexp->set(JSRegExp::kDataOffset,
              GetTrustedConstant(literal.data(broker()),
                                 kRegExpDataIndirectPointerTag));
  regexp->set(JSRegExp::kSourceOffset, GetConstant(literal.source(broker())));
  regexp->set(JSRegExp::kFlagsOffset, GetInt32Constant(literal.flags()));
  regexp->set(JSRegExp::kLastIndexOffset,
              GetInt32Constant(JSRegExp::kInitialLastIndexValue));
  return regexp;
}
References broker(), v8::internal::compiler::RegExpBoilerplateDescriptionRef::data(), DCHECK_EQ, v8::internal::compiler::RegExpBoilerplateDescriptionRef::flags(), v8::internal::JSRegExp::kInitialLastIndexValue, v8::internal::JSRegExp::kLastIndexOffset, v8::internal::kTaggedSize, v8::internal::maglev::VirtualObject::set(), v8::internal::JSRegExp::Size(), and v8::internal::compiler::RegExpBoilerplateDescriptionRef::source().
CreateVirtualObject()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::CreateVirtualObject (compiler::MapRef map, uint32_t slot_count_including_map) [private]
Definition at line 13383 of file maglev-graph-builder.cc.
                                                           {
  // VirtualObjects are not added to the Maglev graph.
  DCHECK_GT(slot_count_including_map, 0);
  uint32_t slot_count = slot_count_including_map - 1;
  ValueNode** slots = zone()->AllocateArray<ValueNode*>(slot_count);
  VirtualObject* vobject = NodeBase::New<VirtualObject>(
      zone(), 0, map, NewObjectId(), slot_count, slots);
  std::fill_n(slots, slot_count,
              GetRootConstant(RootIndex::kOnePointerFillerMap));
  return vobject;
}
References DCHECK_GT.
current_deopt_scope()
const DeoptFrameScope* v8::internal::maglev::MaglevGraphBuilder::current_deopt_scope () const [inline]
Definition at line 363 of file maglev-graph-builder.h.
                                                     {
    return current_deopt_scope_;
  }
References current_deopt_scope_.
current_interpreter_frame()
const InterpreterFrameState& v8::internal::maglev::MaglevGraphBuilder::current_interpreter_frame () const [inline]
Definition at line 359 of file maglev-graph-builder.h.
                                                                 {
    return current_interpreter_frame_;
  }
References current_interpreter_frame_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MaglevSubGraphBuilder(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow().
DecrementDeadPredecessorAndAccountForPeeling()
void v8::internal::maglev::MaglevGraphBuilder::DecrementDeadPredecessorAndAccountForPeeling (uint32_t offset) [inline], [private]
Definition at line 3184 of file maglev-graph-builder.h.
                                                                     {
    DCHECK_LE(offset, bytecode().length());
    DCHECK_GT(predecessor_count_[offset], 0);
    DCHECK_IMPLIES(merge_states_[offset],
                   merge_states_[offset]->predecessor_count() ==
                       predecessor_count_[offset] - 1);
    predecessor_count_[offset]--;
    if (in_peeled_iteration()) {
      decremented_predecessor_offsets_.push_back(offset);
    } else {
      DCHECK(decremented_predecessor_offsets_.empty());
    }
  }
References DCHECK, DCHECK_GT, DCHECK_IMPLIES, DCHECK_LE, and v8::internal::length.
DeepCopyVirtualObject()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::DeepCopyVirtualObject (VirtualObject * vobj) [private]
Definition at line 13375 of file maglev-graph-builder.cc.
                                                                           {
  CHECK_EQ(old->type(), VirtualObject::kDefault);
  VirtualObject* vobject = old->Clone(NewObjectId(), zone());
  current_interpreter_frame_.add_object(vobject);
  old->allocation()->UpdateObject(vobject);
  return vobject;
}
References v8::internal::maglev::VirtualObject::allocation(), CHECK_EQ, v8::internal::maglev::VirtualObject::Clone(), v8::internal::maglev::VirtualObject::type(), and v8::internal::maglev::InlinedAllocation::UpdateObject().
Referenced by GetModifiableObjectFromAllocation().
DoTryReduceMathRound()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::DoTryReduceMathRound (CallArguments & args, Float64Round::Kind kind) [private]
Definition at line 10697 of file maglev-graph-builder.cc.
                                                {
  if (args.count() == 0) {
    return GetRootConstant(RootIndex::kNanValue);
  }
  ValueNode* arg = args[0];
  auto arg_repr = arg->value_representation();
  if (arg_repr == ValueRepresentation::kInt32 ||
      arg_repr == ValueRepresentation::kUint32 ||
      arg_repr == ValueRepresentation::kIntPtr) {
    return arg;
  }
  if (CheckType(arg, NodeType::kSmi)) return arg;
  if (!IsSupported(CpuOperation::kFloat64Round)) {
    return {};
  }
  if (arg_repr == ValueRepresentation::kFloat64 ||
      arg_repr == ValueRepresentation::kHoleyFloat64) {
    return AddNewNode<Float64Round>({arg}, kind);
  }
  DCHECK_EQ(arg_repr, ValueRepresentation::kTagged);
  if (CheckType(arg, NodeType::kNumberOrOddball)) {
    return AddNewNode<Float64Round>(
        {GetHoleyFloat64ForToNumber(
            arg, NodeType::kNumberOrOddball,
            TaggedToFloat64ConversionType::kNumberOrOddball)},
        kind);
  }
  if (!CanSpeculateCall()) return {};
  DeoptFrameScope continuation_scope(this, Float64Round::continuation(kind));
  ToNumberOrNumeric* conversion =
      AddNewNode<ToNumberOrNumeric>({arg}, Object::Conversion::kToNumber);
  ValueNode* float64_value = AddNewNode<UncheckedNumberOrOddballToFloat64>(
      {conversion}, TaggedToFloat64ConversionType::kOnlyNumber);
  return AddNewNode<Float64Round>({float64_value}, kind);
}
References v8::base::args, DCHECK_EQ, v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), v8::internal::anonymous_namespace{ic.cc}::kIntPtr, v8::internal::compiler::kSmi, v8::internal::Object::kToNumber, and v8::internal::maglev::ValueNode::value_representation().
EmitUnconditionalDeopt()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::EmitUnconditionalDeopt (DeoptimizeReason reason) [inline], [private]
Definition at line 728 of file maglev-graph-builder.h.
                                                               {
    current_block_->set_deferred(true);
    // Create a block rather than calling finish, since we don't yet know the
    // next block's offset before the loop skipping the rest of the bytecodes.
    FinishBlock<Deopt>({}, reason);
    return ReduceResult::DoneWithAbort();
  }
References current_block_, v8::internal::maglev::ReduceResult::DoneWithAbort(), and v8::internal::maglev::BasicBlock::set_deferred().
Referenced by BuildCheckHeapObject(), BuildCheckJSFunction(), BuildCheckJSReceiver(), BuildCheckJSReceiverOrNullOrUndefined(), BuildCheckMaps(), BuildCheckNumber(), BuildCheckSeqOneByteString(), BuildCheckSmi(), BuildCheckString(), BuildCheckStringOrOddball(), BuildCheckStringOrStringWrapper(), BuildCheckSymbol(), GetUint32ElementIndex(), TryBuildNamedAccess(), TryBuildPropertyCellLoad(), TryBuildPropertyCellStore(), TryBuildPropertyLoad(), TryBuildStoreField(), TrySpecializeStoreContextSlot(), VisitBinaryOperation(), VisitBinarySmiOperation(), VisitCompareOperation(), VisitSingleBytecode(), and VisitUnaryOperation().
EndLoopEffects()
void v8::internal::maglev::MaglevGraphBuilder::EndLoopEffects (int loop_header) [private]
Definition at line 14433 of file maglev-graph-builder.cc.
                                                       {
  DCHECK_EQ(loop_effects_, loop_effects_stack_.back());
  DCHECK_EQ(loop_effects_->loop_header, loop_header);
  // TODO(olivf): Update merge states dominated by the loop header with
  // information we know to be unaffected by the loop.
  if (merge_states_[loop_header] && merge_states_[loop_header]->is_loop()) {
    merge_states_[loop_header]->set_loop_effects(loop_effects_);
  }
  if (loop_effects_stack_.size() > 1) {
    LoopEffects* inner_effects = loop_effects_;
    loop_effects_ = *(loop_effects_stack_.end() - 2);
    loop_effects_->Merge(inner_effects);
  } else {
    loop_effects_ = nullptr;
  }
  loop_effects_stack_.pop_back();
}
References DCHECK_EQ, and v8::internal::maglev::LoopEffects::Merge().
EndPrologue()
BasicBlock * v8::internal::maglev::MaglevGraphBuilder::EndPrologue ()
Definition at line 1051 of file maglev-graph-builder.cc.
                                            {
  BasicBlock* first_block;
  if (!is_inline() &&
      (v8_flags.maglev_hoist_osr_value_phi_untagging && graph_->is_osr())) {
    first_block =
        FinishBlock<CheckpointedJump>({}, &jump_targets_[entrypoint_]);
  } else {
    first_block = FinishBlock<Jump>({}, &jump_targets_[entrypoint_]);
  }
  MergeIntoFrameState(first_block, entrypoint_);
  return first_block;
}
References entrypoint_, graph_, is_inline(), v8::internal::maglev::Graph::is_osr(), jump_targets_, MergeIntoFrameState(), and v8::internal::v8_flags.
Referenced by Build().
EnsureInt32() [1/2]
void v8::internal::maglev::MaglevGraphBuilder::EnsureInt32 (interpreter::Register reg) [inline], [private]
Definition at line 1587 of file maglev-graph-builder.h.
                                            {
    EnsureInt32(current_interpreter_frame_.get(reg));
  }
EnsureInt32() [2/2]
void v8::internal::maglev::MaglevGraphBuilder::EnsureInt32 (ValueNode * value, bool can_be_heap_number = false) [inline], [private]
Definition at line 1581 of file maglev-graph-builder.h.
                                                                      {
    // Either the value is Int32 already, or we force a conversion to Int32 and
    // cache the value in its alternative representation node.
    GetInt32(value, can_be_heap_number);
  }
References v8::internal::value.
Referenced by BuildInt32BinarySmiOperationNode(), and TrySpecializeStoreContextSlot().
EnsureType() [1/2]
template<typename Function >
bool v8::internal::maglev::MaglevGraphBuilder::EnsureType (ValueNode * node, NodeType type, Function ensure_new_type) [inline], [private]
Definition at line 538 of file maglev-graph-builder.h.
                                                                            {
    return known_node_aspects().EnsureType<Function>(broker(), node, type,
                                                     ensure_new_type);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::EnsureType(), known_node_aspects(), and v8::internal::tracing::type.
EnsureType() [2/2]
bool v8::internal::maglev::MaglevGraphBuilder::EnsureType (ValueNode * node, NodeType type, NodeType * old = nullptr) [inline], [private]
Definition at line 534 of file maglev-graph-builder.h.
                                                                           {
    return known_node_aspects().EnsureType(broker(), node, type, old);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::EnsureType(), known_node_aspects(), and v8::internal::tracing::type.
Referenced by BuildCheckHeapObject(), BuildCheckJSFunction(), BuildCheckJSReceiver(), BuildCheckJSReceiverOrNullOrUndefined(), BuildCheckNumber(), BuildCheckSeqOneByteString(), BuildCheckSmi(), BuildCheckString(), BuildCheckStringOrOddball(), BuildCheckStringOrStringWrapper(), BuildCheckSymbol(), BuildLoadFixedArrayLength(), BuildLoadJSFunctionContext(), BuildNumberOrOddballToFloat64(), BuildRegisterFrameInitialization(), BuildSmiUntag(), GetTruncatedInt32ForToNumber(), and TrySpecializeLoadContextSlot().
EscapeContext()
void v8::internal::maglev::MaglevGraphBuilder::EscapeContext () [private]
Definition at line 180 of file maglev-graph-builder.cc.
                                       {
  ValueNode* context = GetContext();
  if (InlinedAllocation* alloc = context->TryCast<InlinedAllocation>()) {
    alloc->ForceEscaping();
  }
}
References GetContext(), and v8::internal::maglev::NodeBase::TryCast().
ExtendOrReallocateCurrentAllocationBlock()
InlinedAllocation * v8::internal::maglev::MaglevGraphBuilder::ExtendOrReallocateCurrentAllocationBlock (AllocationType allocation_type, VirtualObject * value) [private]
Definition at line 13637 of file maglev-graph-builder.cc.
                                                            {
  DCHECK_LE(vobject->size(), kMaxRegularHeapObjectSize);
  if (!current_allocation_block_ || v8_flags.maglev_allocation_folding == 0 ||
      current_allocation_block_->allocation_type() != allocation_type ||
      !v8_flags.inline_new || is_turbolev()) {
    current_allocation_block_ =
        AddNewNode<AllocationBlock>({}, allocation_type);
  }
  int current_size = current_allocation_block_->size();
  if (current_size + vobject->size() > kMaxRegularHeapObjectSize) {
    current_allocation_block_ =
        AddNewNode<AllocationBlock>({}, allocation_type);
  }
  DCHECK_GE(current_size, 0);
  InlinedAllocation* allocation =
      AddNewNode<InlinedAllocation>({current_allocation_block_}, vobject);
  graph()->allocations_escape_map().emplace(allocation, zone());
  current_allocation_block_->Add(allocation);
  vobject->set_allocation(allocation);
  return allocation;
}
References DCHECK_GE, DCHECK_LE, graph(), v8::internal::kMaxRegularHeapObjectSize, v8::internal::maglev::VirtualObject::set_allocation(), v8::internal::maglev::VirtualObject::size(), and v8::internal::v8_flags.
fast_hash_combine()
static size_t v8::internal::maglev::MaglevGraphBuilder::fast_hash_combine (size_t seed, size_t h) [inline], [static], [private]
Definition at line 3314 of file maglev-graph-builder.h.
                                                         {
    // Implementation from boost. Good enough for GVN.
    return h + 0x9e3779b9 + (seed << 6) + (seed >> 2);
  }
References h().
Referenced by AddNewNodeOrGetEquivalent().
feedback()
compiler::FeedbackVectorRef v8::internal::maglev::MaglevGraphBuilder::feedback () const [inline], [private]
Definition at line 3109 of file maglev-graph-builder.h.
                                             {
    return compilation_unit_->feedback();
  }
Referenced by BuildGenericBinaryOperationNode(), BuildGenericBinarySmiOperationNode(), BuildGenericUnaryOperationNode(), and TryBuildNamedAccess().
FeedbackNexusForOperand()
const FeedbackNexus v8::internal::maglev::MaglevGraphBuilder::FeedbackNexusForOperand (int slot_operand_index) const [inline], [private]
Definition at line 3112 of file maglev-graph-builder.h.
                                                                            {
    return FeedbackNexus(feedback().object(),
                         GetSlotOperand(slot_operand_index),
                         broker()->feedback_nexus_config());
  }
References broker().
Referenced by VisitBinaryOperation(), VisitBinarySmiOperation(), VisitCompareOperation(), and VisitUnaryOperation().
FeedbackNexusForSlot()
const FeedbackNexus v8::internal::maglev::MaglevGraphBuilder::FeedbackNexusForSlot (FeedbackSlot slot) const [inline], [private]
Definition at line 3117 of file maglev-graph-builder.h.
                                                                    {
    return FeedbackNexus(feedback().object(), slot,
                         broker()->feedback_nexus_config());
  }
References broker().
FindContinuationForPolymorphicPropertyLoad()
std::optional< MaglevGraphBuilder::ContinuationOffsets > v8::internal::maglev::MaglevGraphBuilder::FindContinuationForPolymorphicPropertyLoad () [private]
Definition at line 7285 of file maglev-graph-builder.cc.
                                                               {
  if (!v8_flags.maglev_poly_calls) {
    return {};
  }
  if (iterator_.current_bytecode() !=
      interpreter::Bytecode::kGetNamedProperty) {
    return {};
  }
  interpreter::Register loaded_property_register =
      interpreter::Register::virtual_accumulator();
  // For now, we only generate the continuation for this pattern:
  // GeNamedProperty ...
  // Sta-REG
  // CallProperty REG ...
  iterator_.Advance();
  switch (iterator_.current_bytecode()) {
#define CASE(Name, ...) \
  case interpreter::Bytecode::k##Name: \
    loaded_property_register = \
        interpreter::Register::FromShortStar(interpreter::Bytecode::k##Name); \
    break;
    SHORT_STAR_BYTECODE_LIST(CASE)
#undef CASE
    default:
      return {};
  }
  iterator_.Advance();
  switch (iterator_.current_bytecode()) {
#define CASE(Name, ...) \
  case interpreter::Bytecode::k##Name: \
    if (iterator_.GetRegisterOperand(0) == loaded_property_register) { \
      return ContinuationOffsets{iterator_.current_offset(), \
                                 iterator_.next_offset()}; \
    } \
    break;
    CALL_PROPERTY_BYTECODES(CASE)
#undef CASE
    default:
      break;
  }
  return {};
  // TODO(marja): Add other possible continuations.
  // Restriction: the bytecodes which can end the continuation must write
  // their result in the accumulator.
  // TODO(marja): Remove this restriction. To do that, VisitGetNamedProperty
  // can't assume it should call SetAccumulator after TryBuildLoadNamedProperty.
}
References CALL_PROPERTY_BYTECODES, CASE, SHORT_STAR_BYTECODE_LIST, v8::internal::v8_flags, and v8::internal::interpreter::Register::virtual_accumulator().
FinishBlock()
template<typename ControlNodeT , typename... Args>
BasicBlock* v8::internal::maglev::MaglevGraphBuilder::FinishBlock (std::initializer_list< ValueNode * > control_inputs, Args &&... args) [inline], [private]
Definition at line 1976 of file maglev-graph-builder.h.
                                          {
    ControlNodeT* control_node = NodeBase::New<ControlNodeT>(
        zone(), control_inputs.size(), std::forward<Args>(args)...);
    SetNodeInputs(control_node, control_inputs);
    AttachEagerDeoptInfo(control_node);
    AttachDeoptCheckpoint(control_node);
    static_assert(!ControlNodeT::kProperties.can_lazy_deopt());
    static_assert(!ControlNodeT::kProperties.can_throw());
    static_assert(!ControlNodeT::kProperties.can_write());
    control_node->set_owner(current_block_);
    current_block_->set_control_node(control_node);
    // Clear unobserved context slot stores when there is any controlflow.
    // TODO(olivf): More precision could be achieved by tracking dominating
    // stores within known_node_aspects. For this we could use a stack of
    // stores, which we push on split and pop on merge.
    unobserved_context_slot_stores_.clear();
    // TODO(olivf): Support allocation folding across control flow.
    ClearCurrentAllocationBlock();
    BasicBlock* block = current_block_;
    FlushNodesToBlock();
    current_block_ = nullptr;
    graph()->Add(block);
    if (has_graph_labeller()) {
      graph_labeller()->RegisterNode(control_node, compilation_unit_,
                                     BytecodeOffset(iterator_.current_offset()),
                                     current_source_position_);
      if (v8_flags.trace_maglev_graph_building) {
        bool kSkipTargets = true;
        std::cout << " " << control_node << " "
                  << PrintNodeLabel(graph_labeller(), control_node) << ": "
                  << PrintNode(graph_labeller(), control_node, kSkipTargets)
                  << std::endl;
      }
    }
    return block;
  }
References v8::base::args, graph(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), and v8::internal::v8_flags.
FinishInlinedBlockForCaller()
BasicBlock * v8::internal::maglev::MaglevGraphBuilder::FinishInlinedBlockForCaller (ControlNode * control_node, ZoneVector< Node * > rem_nodes_in_call_block)
Definition at line 14280 of file maglev-graph-builder.cc.
                                                                          {
  BasicBlock* result = current_block_;
  result->nodes().reserve(node_buffer().size() +
                          rem_nodes_in_call_block.size());
  FlushNodesToBlock();
  current_block_ = nullptr;
  for (Node* n : rem_nodes_in_call_block) {
    n->set_owner(result);
    result->nodes().push_back(n);
  }
  control_node->set_owner(result);
  CHECK_NULL(result->control_node());
  result->set_control_node(control_node);
  // Add the final block to the graph.
  graph_->Add(result);
  return result;
}
References CHECK_NULL, v8::base::internal::result, v8::internal::maglev::NodeBase::set_owner(), v8::internal::ZoneVector< T >::size(), and size().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
FlushNodesToBlock()
void v8::internal::maglev::MaglevGraphBuilder::FlushNodesToBlock () [inline], [private]
Definition at line 1966 of file maglev-graph-builder.h.
                           {
    ZoneVector<Node*>& nodes = current_block_->nodes();
    size_t old_size = nodes.size();
    nodes.resize(old_size + node_buffer().size());
    std::copy(node_buffer().begin(), node_buffer().end(),
              nodes.begin() + old_size);
    node_buffer().clear();
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and size().
GetAccumulator()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetAccumulator () [inline], [private]
Definition at line 1638 of file maglev-graph-builder.h.
                              {
    return current_interpreter_frame_.get(
        interpreter::Register::virtual_accumulator());
  }
Referenced by BuildGenericBinaryOperationNode(), BuildGenericBinarySmiOperationNode(), BuildGenericUnaryOperationNode(), BuildInt32BinaryOperationNode(), BuildInt32BinarySmiOperationNode(), BuildInt32UnaryOperationNode(), TryBuildNamedAccess(), TryBuildPropertyCellStore(), TryBuildPropertyStore(), TryBuildScriptContextStore(), TryBuildStoreField(), TryReduceCompareEqualAgainstConstant(), VisitBinaryOperation(), and VisitCompareOperation().
GetAccumulatorHoleyFloat64ForToNumber()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetAccumulatorHoleyFloat64ForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [inline], [private]
Definition at line 1663 of file maglev-graph-builder.h.
                                                     {
    return GetHoleyFloat64ForToNumber(
        interpreter::Register::virtual_accumulator(), allowed_input_type,
        conversion_type);
  }
Referenced by BuildFloat64BinaryOperationNodeForToNumber(), BuildFloat64BinarySmiOperationNodeForToNumber(), and BuildFloat64UnaryOperationNodeForToNumber().
GetAccumulatorSmi()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::GetAccumulatorSmi (UseReprHintRecording record_use_repr_hint = UseReprHintRecording::kRecord) [inline], [private]
Definition at line 1643 of file maglev-graph-builder.h.
                                       {
    return GetSmiValue(interpreter::Register::virtual_accumulator(),
                       record_use_repr_hint);
  }
References v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue().
Referenced by TryBuildStoreField().
GetAccumulatorTruncatedInt32ForToNumber()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetAccumulatorTruncatedInt32ForToNumber (NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [inline], [private]
Definition at line 1650 of file maglev-graph-builder.h.
                                                     {
    return GetTruncatedInt32ForToNumber(
        interpreter::Register::virtual_accumulator(), allowed_input_type,
        conversion_type);
  }
GetAccumulatorUint8ClampedForToNumber()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetAccumulatorUint8ClampedForToNumber () [inline], [private]
Definition at line 1658 of file maglev-graph-builder.h.
                                                     {
    return GetUint8ClampedForToNumber(
        interpreter::Register::virtual_accumulator());
  }
GetArgument()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetArgument (int i)
Definition at line 1069 of file maglev-graph-builder.cc.
                                                {
  DCHECK_LT(i, parameter_count());
  interpreter::Register reg = interpreter::Register::FromParameterIndex(i);
  return current_interpreter_frame_.get(reg);
}
References current_interpreter_frame_, DCHECK_LT, v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::maglev::InterpreterFrameState::get(), and parameter_count().
GetArgumentsAsArrayOfValueNodes()
base::Vector< ValueNode * > v8::internal::maglev::MaglevGraphBuilder::GetArgumentsAsArrayOfValueNodes (compiler::SharedFunctionInfoRef shared, const CallArguments & args) [private]
Definition at line 10895 of file maglev-graph-builder.cc.
                                                                     {
  // TODO(victorgomes): Investigate if we can avoid this copy.
  int arg_count = static_cast<int>(args.count());
  auto arguments = zone()->AllocateVector<ValueNode*>(arg_count + 1);
  arguments[0] = GetConvertReceiver(shared, args);
  for (int i = 0; i < arg_count; i++) {
    arguments[i + 1] = args[i];
  }
  return arguments;
}
References v8::base::args, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
GetBooleanConstant()
RootConstant* v8::internal::maglev::MaglevGraphBuilder::GetBooleanConstant (bool value) [inline]
Definition at line 343 of file maglev-graph-builder.h.
                                               {
    return graph()->GetBooleanConstant(value);
  }
References v8::internal::maglev::Graph::GetBooleanConstant(), graph(), and v8::internal::value.
Referenced by BuildTaggedEqual(), BuildTestUndetectable(), TryReduceCompareEqualAgainstConstant(), and VisitCompareOperation().
GetCallerDeoptFrame()
DeoptFrame * v8::internal::maglev::MaglevGraphBuilder::GetCallerDeoptFrame () [private]
Definition at line 1362 of file maglev-graph-builder.cc.
                                                    {
  if (!is_inline()) return nullptr;
  return caller_details_->deopt_frame;
}
References caller_details_, v8::internal::maglev::MaglevCallerDetails::deopt_frame, and is_inline().
Referenced by GetDeoptFrameForLazyDeoptHelper(), and GetLatestCheckpointedFrame().
GetCatchBlockFrameState()
MergePointInterpreterFrameState* v8::internal::maglev::MaglevGraphBuilder::GetCatchBlockFrameState () [inline], [private]
Definition at line 1258 of file maglev-graph-builder.h.
                                                             {
    DCHECK(IsInsideTryBlock());
    return merge_states_[catch_block_stack_.top().handler];
  }
References catch_block_stack_, v8::internal::DCHECK(), IsInsideTryBlock(), and merge_states_.
Referenced by AttachExceptionHandlerInfo().
GetClosure()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetClosure () const [inline], [private]
Definition at line 1452 of file maglev-graph-builder.h.
                                {
    return current_interpreter_frame_.get(
        interpreter::Register::function_closure());
  }
Referenced by BuildRegisterFrameInitialization(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), and GetLatestCheckpointedFrame().
GetConstant()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetConstant (compiler::ObjectRef ref) [inline]
Definition at line 346 of file maglev-graph-builder.h.
                                                {
    return graph()->GetConstant(ref);
  }
References v8::internal::maglev::Graph::GetConstant(), and graph().
Referenced by BuildCompareMaps(), BuildLoadField(), BuildLoadFixedArrayElement(), BuildLoadJSFunctionContext(), BuildLoadJSFunctionFeedbackCell(), BuildRegisterFrameInitialization(), BuildTransitionElementsKindAndCompareMaps(), SetKnownValue(), TryBuildNamedAccess(), TryBuildPropertyCellLoad(), TryBuildPropertyCellStore(), TryBuildPropertyLoad(), TryBuildScriptContextConstantLoad(), TryBuildScriptContextLoad(), TryBuildScriptContextStore(), TrySpecializeLoadContextSlot(), TrySpecializeLoadContextSlotToFunctionContext(), and TrySpecializeStoreContextSlot().
GetConstantSingleCharacterStringFromCode()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::GetConstantSingleCharacterStringFromCode (uint16_t code) [private]
Definition at line 7536 of file maglev-graph-builder.cc.
                   {
  // Only handle the one-byte character case, which accesses roots.
  if (code <= String::kMaxOneByteCharCode) {
    return GetRootConstant(RootsTable::SingleCharacterStringIndex(code));
  }
  return {};
}
References code, v8::internal::String::kMaxOneByteCharCode, and v8::internal::RootsTable::SingleCharacterStringIndex().
GetContext()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetContext () const [inline], [private]
Definition at line 1457 of file maglev-graph-builder.h.
                                {
    return current_interpreter_frame_.get(
        interpreter::Register::current_context());
  }
Referenced by Build(), BuildCallBuiltin(), BuildRegisterFrameInitialization(), CheckContextExtensions(), and EscapeContext().
GetContextAtDepth()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetContextAtDepth (ValueNode * context, size_t depth) [private]
Definition at line 7735 of file maglev-graph-builder.cc.
                                                               {
  MinimizeContextChainDepth(&context, &depth);
  if (compilation_unit_->info()->specialize_to_function_context()) {
    compiler::OptionalContextRef maybe_ref =
        FunctionContextSpecialization::TryToRef(compilation_unit_, context,
                                                &depth);
    if (maybe_ref.has_value()) {
      context = GetConstant(maybe_ref.value());
    }
  }
  for (size_t i = 0; i < depth; i++) {
    context = LoadAndCacheContextSlot(context, Context::PREVIOUS_INDEX,
                                      kImmutable, ContextMode::kNoContextCells);
    EnsureType(context, NodeType::kContext);
  }
  return context;
}
References v8::internal::kNoContextCells, and v8::internal::Context::PREVIOUS_INDEX.
Referenced by BuildLoadContextSlot(), BuildStoreContextSlot(), and CheckContextExtensions().
GetConvertReceiver()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetConvertReceiver (compiler::SharedFunctionInfoRef shared, const CallArguments & args) [private]
Definition at line 10868 of file maglev-graph-builder.cc.
                                                                     {
  if (shared.native() || shared.language_mode() == LanguageMode::kStrict) {
    if (args.receiver_mode() == ConvertReceiverMode::kNullOrUndefined) {
      return GetRootConstant(RootIndex::kUndefinedValue);
    } else {
      return args.receiver();
    }
  }
  if (args.receiver_mode() == ConvertReceiverMode::kNullOrUndefined) {
    return GetConstant(
        broker()->target_native_context().global_proxy_object(broker()));
  }
  ValueNode* receiver = args.receiver();
  if (CheckType(receiver, NodeType::kJSReceiver)) return receiver;
  if (compiler::OptionalHeapObjectRef maybe_constant =
          TryGetConstant(receiver)) {
    compiler::HeapObjectRef constant = maybe_constant.value();
    if (constant.IsNullOrUndefined()) {
      return GetConstant(
          broker()->target_native_context().global_proxy_object(broker()));
    }
  }
  return AddNewNode<ConvertReceiver>(
      {receiver}, broker()->target_native_context(), args.receiver_mode());
}
References v8::base::args, broker(), v8::internal::kNullOrUndefined, v8::internal::kStrict, and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
GetCurrentCallFrequency()
float v8::internal::maglev::MaglevGraphBuilder::GetCurrentCallFrequency () [inline], [private]
Definition at line 3134 of file maglev-graph-builder.h.
                                  {
    if (!is_inline()) return 1.0f;
    return caller_details_->call_frequency;
  }
GetCurrentTryCatchBlock()
CatchBlockDetails v8::internal::maglev::MaglevGraphBuilder::GetCurrentTryCatchBlock () [inline], [private]
Definition at line 1263 of file maglev-graph-builder.h.
                                              {
    if (IsInsideTryBlock()) {
      // Inside a try-block.
      int offset = catch_block_stack_.top().handler;
      return {&jump_targets_[offset],
              merge_states_[offset]->exception_handler_was_used(), false, 0};
    }
    if (!is_inline()) {
      return CatchBlockDetails{};
    }
    return caller_details_->catch_block;
  }
References caller_details_, v8::internal::maglev::MaglevCallerDetails::catch_block, catch_block_stack_, v8::internal::maglev::MergePointInterpreterFrameState::exception_handler_was_used(), is_inline(), IsInsideTryBlock(), jump_targets_, and merge_states_.
Referenced by AttachExceptionHandlerInfo().
GetDeoptFrameForEagerCall()
DeoptFrame * v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall (const MaglevCompilationUnit * unit, ValueNode * closure, base::Vector< ValueNode * > args) [private]
Definition at line 1341 of file maglev-graph-builder.cc.
                                 {
  // The parent resumes after the call, which is roughly equivalent to a lazy
  // deopt. Use the helper function directly so that we can mark the
  // accumulator as dead (since it'll be overwritten by this function's
  // return value anyway).
  // TODO(leszeks): This is true for our current set of
  // inlinings/continuations, but there might be cases in the future where it
  // isn't. We may need to store the relevant overwritten register in
  // LazyDeoptFrameScope.
  DCHECK(
      interpreter::Bytecodes::WritesAccumulator(iterator_.current_bytecode()) ||
      interpreter::Bytecodes::ClobbersAccumulator(
          iterator_.current_bytecode()));
  DeoptFrame* deopt_frame = zone()->New<DeoptFrame>(
      GetDeoptFrameForLazyDeoptHelper(interpreter::Register::invalid_value(), 0,
                                      current_deopt_scope_, true));
  return AddInlinedArgumentsToDeoptFrame(deopt_frame, unit, closure, args);
}
References AddInlinedArgumentsToDeoptFrame(), v8::base::args, v8::internal::interpreter::Bytecodes::ClobbersAccumulator(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), current_deopt_scope_, v8::internal::DCHECK(), GetDeoptFrameForLazyDeoptHelper(), v8::internal::interpreter::Register::invalid_value(), iterator_, v8::internal::Zone::New(), v8::internal::interpreter::Bytecodes::WritesAccumulator(), and zone().
GetDeoptFrameForEntryStackCheck()
InterpretedDeoptFrame v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEntryStackCheck () [private]
Definition at line 1510 of file maglev-graph-builder.cc.
                                                                          {
  if (entry_stack_check_frame_) return *entry_stack_check_frame_;
  DCHECK_EQ(iterator_.current_offset(), entrypoint_);
  DCHECK(!is_inline());
  entry_stack_check_frame_.emplace(
      *compilation_unit_,
      zone()->New<CompactInterpreterFrameState>(
          *compilation_unit_,
          GetInLivenessFor(graph_->is_osr() ? bailout_for_entrypoint() : 0),
          current_interpreter_frame_),
      GetClosure(), BytecodeOffset(bailout_for_entrypoint()),
      current_source_position_, nullptr);
  (*entry_stack_check_frame_)
      .frame_state()
      ->ForEachValue(
          *compilation_unit_,
          [&](ValueNode* node, interpreter::Register) { AddDeoptUse(node); });
  AddDeoptUse((*entry_stack_check_frame_).closure());
  return *entry_stack_check_frame_;
}
References AddDeoptUse(), bailout_for_entrypoint(), compilation_unit_, current_interpreter_frame_, v8::internal::interpreter::BytecodeArrayIterator::current_offset(), current_source_position_, v8::internal::DCHECK(), DCHECK_EQ, entry_stack_check_frame_, entrypoint_, GetClosure(), GetInLivenessFor(), graph_, is_inline(), v8::internal::maglev::Graph::is_osr(), iterator_, and zone().
Referenced by Build(), and GetLatestCheckpointedFrame().
GetDeoptFrameForLazyDeopt()
DeoptFrame v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeopt (interpreter::Register result_location, int result_size) [private]
Definition at line 1424 of file maglev-graph-builder.cc.
                                                          {
  return GetDeoptFrameForLazyDeoptHelper(result_location, result_size,
                                         current_deopt_scope_, false);
}
References current_deopt_scope_, and GetDeoptFrameForLazyDeoptHelper().
Referenced by AttachLazyDeoptInfo().
GetDeoptFrameForLazyDeoptHelper()
DeoptFrame v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper (interpreter::Register result_location, int result_size, DeoptFrameScope * scope, bool mark_accumulator_dead) [private]
Definition at line 1430 of file maglev-graph-builder.cc.
                                                        {
  if (scope == nullptr) {
    compiler::BytecodeLivenessState* liveness =
        zone()->New<compiler::BytecodeLivenessState>(*GetOutLiveness(), zone());
    // Remove result locations from liveness.
    if (result_location == interpreter::Register::virtual_accumulator()) {
      DCHECK_EQ(result_size, 1);
      liveness->MarkAccumulatorDead();
      mark_accumulator_dead = false;
    } else {
      DCHECK(!result_location.is_parameter());
      for (int i = 0; i < result_size; i++) {
        liveness->MarkRegisterDead(result_location.index() + i);
      }
    }
    // Explicitly drop the accumulator if needed.
    if (mark_accumulator_dead && liveness->AccumulatorIsLive()) {
      liveness->MarkAccumulatorDead();
    }
    current_interpreter_frame_.virtual_objects().Snapshot();
    InterpretedDeoptFrame ret(
        *compilation_unit_,
        zone()->New<CompactInterpreterFrameState>(*compilation_unit_, liveness,
                                                  current_interpreter_frame_),
        GetClosure(), BytecodeOffset(iterator_.current_offset()),
        current_source_position_, GetCallerDeoptFrame());
    ret.frame_state()->ForEachValue(
        *compilation_unit_, [this](ValueNode* node, interpreter::Register reg) {
          // Receiver and closure values have to be materialized, even if
          // they don't otherwise escape.
          if (reg == interpreter::Register::receiver() ||
              reg == interpreter::Register::function_closure()) {
            node->add_use();
          } else {
            AddDeoptUse(node);
          }
        });
    AddDeoptUse(ret.closure());
    return ret;
  }
  // Currently only support builtin continuations for bytecodes that write to
  // the accumulator
  DCHECK(interpreter::Bytecodes::WritesOrClobbersAccumulator(
      iterator_.current_bytecode()));
#ifdef DEBUG
  if (scope->data().tag() == DeoptFrame::FrameType::kBuiltinContinuationFrame) {
    const DeoptFrame::BuiltinContinuationFrameData& frame =
        current_deopt_scope_->data()
            .get<DeoptFrame::BuiltinContinuationFrameData>();
    if (frame.maybe_js_target) {
      int stack_parameter_count =
          Builtins::GetStackParameterCount(frame.builtin_id);
      // The deopt input value is passed by the deoptimizer, so shouldn't be a
      // parameter here.
      DCHECK_EQ(stack_parameter_count, frame.parameters.length() + 1);
    } else {
      CallInterfaceDescriptor descriptor =
          Builtins::CallInterfaceDescriptorFor(frame.builtin_id);
      // The deopt input value is passed by the deoptimizer, so shouldn't be a
      // parameter here.
      DCHECK_EQ(descriptor.GetParameterCount(), frame.parameters.length() + 1);
      // The deopt input value is passed on the stack.
      DCHECK_GT(descriptor.GetStackParameterCount(), 0);
    }
  }
#endif
  // Mark the accumulator dead in parent frames since we know that the
  // continuation will write it.
  return DeoptFrame(scope->data(),
                    zone()->New<DeoptFrame>(GetDeoptFrameForLazyDeoptHelper(
                        result_location, result_size, scope->parent(),
                        scope->data().tag() ==
                            DeoptFrame::FrameType::kBuiltinContinuationFrame)));
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::maglev::ValueNode::add_use(), AddDeoptUse(), v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::builtin_id, v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::maglev::InterpretedDeoptFrame::closure(), compilation_unit_, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), current_deopt_scope_, current_interpreter_frame_, v8::internal::interpreter::BytecodeArrayIterator::current_offset(), current_source_position_, v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::maglev::CompactInterpreterFrameState::ForEachValue(), v8::internal::maglev::InterpretedDeoptFrame::frame_state(), v8::internal::interpreter::Register::function_closure(), v8::base::DiscriminatedUnion< TagEnum, Ts >::get(), GetCallerDeoptFrame(), GetClosure(), GetOutLiveness(), v8::internal::CallInterfaceDescriptor::GetParameterCount(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::Builtins::GetStackParameterCount(), v8::internal::interpreter::Register::index(), v8::internal::interpreter::Register::is_parameter(), iterator_, v8::internal::maglev::DeoptFrame::kBuiltinContinuationFrame, v8::internal::compiler::BytecodeLivenessState::MarkAccumulatorDead(), v8::internal::compiler::BytecodeLivenessState::MarkRegisterDead(), v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::maybe_js_target, v8::internal::Zone::New(), v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::parameters, v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::parent(), v8::internal::interpreter::Register::receiver(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::base::DiscriminatedUnion< TagEnum, Ts >::tag(), v8::internal::interpreter::Register::virtual_accumulator(), v8::internal::maglev::InterpreterFrameState::virtual_objects(), v8::internal::interpreter::Bytecodes::WritesOrClobbersAccumulator(), and zone().
Referenced by GetDeoptFrameForEagerCall(), and GetDeoptFrameForLazyDeopt().
GetFeedbackCell()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetFeedbackCell () [inline], [private]
Definition at line 1447 of file maglev-graph-builder.h.
                               {
    return graph()->GetConstant(
        compilation_unit_->GetTopLevelCompilationUnit()->feedback_cell());
  }
References graph().
GetFlag16Operand()
uint32_t v8::internal::maglev::MaglevGraphBuilder::GetFlag16Operand (int operand_index) const [inline], [private]
Definition at line 1475 of file maglev-graph-builder.h.
                                                     {
    return iterator_.GetFlag16Operand(operand_index);
  }
GetFlag8Operand()
uint32_t v8::internal::maglev::MaglevGraphBuilder::GetFlag8Operand (int operand_index) const [inline], [private]
Definition at line 1471 of file maglev-graph-builder.h.
                                                    {
    return iterator_.GetFlag8Operand(operand_index);
  }
GetFloat64() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetFloat64 (interpreter::Register reg) [inline], [private]
Definition at line 1604 of file maglev-graph-builder.h.
                                                 {
    return GetFloat64(current_interpreter_frame_.get(reg));
  }
GetFloat64() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetFloat64 (ValueNode * value) [private]
Definition at line 1970 of file maglev-graph-builder.cc.
                                                          {
  RecordUseReprHintIfPhi(value, UseRepresentation::kFloat64);
  return GetFloat64ForToNumber(value, NodeType::kNumber,
                               TaggedToFloat64ConversionType::kOnlyNumber);
}
References GetFloat64ForToNumber(), v8::internal::maglev::kFloat64, v8::internal::maglev::kOnlyNumber, RecordUseReprHintIfPhi(), and v8::internal::value.
Referenced by GetFloat64ForToNumber().
GetFloat64Constant() [1/2]
Float64Constant* v8::internal::maglev::MaglevGraphBuilder::GetFloat64Constant (double constant) [inline]
Definition at line 334 of file maglev-graph-builder.h.
                                                       {
    return graph()->GetFloat64Constant(constant);
  }
References v8::internal::maglev::Graph::GetFloat64Constant(), and graph().
Referenced by BuildFloat64BinarySmiOperationNodeForToNumber(), BuildFloat64UnaryOperationNodeForToNumber(), BuildLoadField(), BuildLoadFixedDoubleArrayElement(), GetFloat64ForToNumber(), and GetNumberConstant().
GetFloat64Constant() [2/2]
Float64Constant* v8::internal::maglev::MaglevGraphBuilder::GetFloat64Constant (Float64 constant) [inline]
Definition at line 337 of file maglev-graph-builder.h.
                                                        {
    return graph()->GetFloat64Constant(constant);
  }
References v8::internal::maglev::Graph::GetFloat64Constant(), and graph().
GetFloat64ForToNumber() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber (interpreter::Register reg, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [inline], [private]
Definition at line 1620 of file maglev-graph-builder.h.
                                                     {
    return GetFloat64ForToNumber(current_interpreter_frame_.get(reg),
                                 allowed_input_type, conversion_type);
  }
GetFloat64ForToNumber() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber (ValueNode * value, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2016 of file maglev-graph-builder.cc.
                                                   {
  ValueRepresentation representation =
      value->properties().value_representation();
  if (representation == ValueRepresentation::kFloat64) return value;
  // Process constants first to avoid allocating NodeInfo for them.
  if (auto cst = TryGetFloat64Constant(value, conversion_type)) {
    return GetFloat64Constant(cst.value());
  }
  // We could emit unconditional eager deopts for other kinds of constant, but
  // it's not necessary, the appropriate checking conversion nodes will deopt.
  NodeInfo* node_info = GetOrCreateInfoFor(value);
  auto& alternative = node_info->alternative();
  if (ValueNode* alt = alternative.float64()) {
    return alt;
  }
  // This is called when converting inputs in AddNewNode. We might already have
  // an empty type for `value` here. Make sure we don't add unsafe conversion
  // nodes in that case by checking for the empty node type explicitly.
  // TODO(marja): The checks can be removed after we're able to bail out
  // earlier.
  switch (representation) {
    case ValueRepresentation::kTagged: {
      auto combined_type = IntersectType(allowed_input_type, node_info->type());
      if (!IsEmptyNodeType(node_info->type()) &&
          NodeTypeIs(combined_type, NodeType::kSmi)) {
        // Get the float64 value of a Smi value its int32 representation.
        return GetFloat64(GetInt32(value));
      }
      if (!IsEmptyNodeType(node_info->type()) &&
          NodeTypeIs(combined_type, NodeType::kNumber)) {
        // Number->Float64 conversions are exact alternatives, so they can
        // also become the canonical float64_alternative.
        return alternative.set_float64(BuildNumberOrOddballToFloat64(
            value, NodeType::kNumber,
            TaggedToFloat64ConversionType::kOnlyNumber));
      }
      if (!IsEmptyNodeType(node_info->type()) &&
          NodeTypeIs(combined_type, NodeType::kNumberOrOddball)) {
        // NumberOrOddball->Float64 conversions are not exact alternatives,
        // since they lose the information that this is an oddball, so they
        // can only become the canonical float64_alternative if they are a
        // known number (and therefore not oddball).
        return BuildNumberOrOddballToFloat64(value, combined_type,
                                             conversion_type);
      }
      // The type is impossible. We could generate an unconditional deopt here,
      // but it's too invasive. So we just generate a check which will always
      // deopt.
      return BuildNumberOrOddballToFloat64(value, allowed_input_type,
                                           conversion_type);
    }
    case ValueRepresentation::kInt32:
      return alternative.set_float64(AddNewNode<ChangeInt32ToFloat64>({value}));
    case ValueRepresentation::kUint32:
      return alternative.set_float64(
          AddNewNode<ChangeUint32ToFloat64>({value}));
    case ValueRepresentation::kHoleyFloat64: {
      switch (allowed_input_type) {
        case NodeType::kSmi:
        case NodeType::kNumber:
        case NodeType::kNumberOrBoolean:
          // Number->Float64 conversions are exact alternatives, so they can
          // also become the canonical float64_alternative. The HoleyFloat64
          // representation can represent undefined but no other oddballs, so
          // booleans cannot occur here and kNumberOrBoolean can be grouped with
          // kNumber.
          return alternative.set_float64(
              AddNewNode<CheckedHoleyFloat64ToFloat64>({value}));
        case NodeType::kNumberOrOddball:
          // NumberOrOddball->Float64 conversions are not exact alternatives,
          // since they lose the information that this is an oddball, so they
          // cannot become the canonical float64_alternative.
          return AddNewNode<HoleyFloat64ToMaybeNanFloat64>({value});
        default:
          UNREACHABLE();
      }
    }
    case ValueRepresentation::kIntPtr:
      return alternative.set_float64(
          AddNewNode<ChangeIntPtrToFloat64>({value}));
    case ValueRepresentation::kFloat64:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::maglev::NodeInfo::alternative(), BuildNumberOrOddballToFloat64(), GetFloat64(), GetFloat64Constant(), GetInt32(), GetOrCreateInfoFor(), v8::internal::maglev::IntersectType(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kOnlyNumber, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::NodeTypeIs(), TryGetFloat64Constant(), v8::internal::maglev::NodeInfo::type(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by GetFloat64(), GetHoleyFloat64ForToNumber(), and VisitCompareOperation().
GetHoleyFloat64()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetHoleyFloat64 (ValueNode * value, bool convert_hole_to_undefined) [private]
GetHoleyFloat64ForToNumber() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetHoleyFloat64ForToNumber (interpreter::Register reg, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [inline], [private]
Definition at line 1631 of file maglev-graph-builder.h.
                                                     {
    return GetHoleyFloat64ForToNumber(current_interpreter_frame_.get(reg),
                                      allowed_input_type, conversion_type);
  }
GetHoleyFloat64ForToNumber() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetHoleyFloat64ForToNumber (ValueNode * value, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 2108 of file maglev-graph-builder.cc.
                                                   {
  RecordUseReprHintIfPhi(value, UseRepresentation::kHoleyFloat64);
  ValueRepresentation representation =
      value->properties().value_representation();
  // Ignore the hint for
  if (representation == ValueRepresentation::kHoleyFloat64) return value;
  return GetFloat64ForToNumber(value, allowed_input_type, conversion_type);
}
References GetFloat64ForToNumber(), v8::internal::maglev::kHoleyFloat64, RecordUseReprHintIfPhi(), and v8::internal::value.
GetInlinedArgument()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetInlinedArgument (int i)
Definition at line 1075 of file maglev-graph-builder.cc.
                                                       {
  DCHECK(is_inline());
  DCHECK_LT(i, argument_count());
  return caller_details_->arguments[i];
}
References argument_count(), v8::internal::maglev::MaglevCallerDetails::arguments, caller_details_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and is_inline().
GetInLiveness()
const compiler::BytecodeLivenessState* v8::internal::maglev::MaglevGraphBuilder::GetInLiveness () const [inline], [private]
Definition at line 1889 of file maglev-graph-builder.h.
                                                             {
    return GetInLivenessFor(iterator_.current_offset());
  }
Referenced by GetLatestCheckpointedFrame().
GetInLivenessFor()
const compiler::BytecodeLivenessState* v8::internal::maglev::MaglevGraphBuilder::GetInLivenessFor (int offset) const [inline], [private]
Definition at line 1892 of file maglev-graph-builder.h.
                                                                          {
    return bytecode_analysis().GetInLivenessFor(offset);
  }
Referenced by BuildMergeStates(), and GetDeoptFrameForEntryStackCheck().
GetInt32()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetInt32 (ValueNode * value, bool can_be_heap_number = false) [private]
Definition at line 1851 of file maglev-graph-builder.cc.
                                                                 {
  RecordUseReprHintIfPhi(value, UseRepresentation::kInt32);
  ValueRepresentation representation =
      value->properties().value_representation();
  if (representation == ValueRepresentation::kInt32) return value;
  // Process constants first to avoid allocating NodeInfo for them.
  if (auto cst = TryGetInt32Constant(value)) {
    return GetInt32Constant(cst.value());
  }
  // We could emit unconditional eager deopts for other kinds of constant, but
  // it's not necessary, the appropriate checking conversion nodes will deopt.
  NodeInfo* node_info = GetOrCreateInfoFor(value);
  auto& alternative = node_info->alternative();
  if (ValueNode* alt = alternative.int32()) {
    return alt;
  }
  switch (representation) {
    case ValueRepresentation::kTagged: {
      if (can_be_heap_number && !CheckType(value, NodeType::kSmi)) {
        return alternative.set_int32(AddNewNode<CheckedNumberToInt32>({value}));
      }
      return alternative.set_int32(BuildSmiUntag(value));
    }
    case ValueRepresentation::kUint32: {
      if (!IsEmptyNodeType(GetType(value)) && node_info->is_smi()) {
        return alternative.set_int32(
            AddNewNode<TruncateUint32ToInt32>({value}));
      }
      return alternative.set_int32(AddNewNode<CheckedUint32ToInt32>({value}));
    }
    case ValueRepresentation::kFloat64:
    // The check here will also work for the hole NaN, so we can treat
    // HoleyFloat64 as Float64.
    case ValueRepresentation::kHoleyFloat64: {
      return alternative.set_int32(
          AddNewNode<CheckedTruncateFloat64ToInt32>({value}));
    }
    case ValueRepresentation::kIntPtr:
      return alternative.set_int32(AddNewNode<CheckedIntPtrToInt32>({value}));
    case ValueRepresentation::kInt32:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::maglev::NodeInfo::alternative(), BuildSmiUntag(), CheckType(), GetInt32Constant(), GetOrCreateInfoFor(), GetType(), v8::internal::maglev::NodeInfo::is_smi(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, RecordUseReprHintIfPhi(), TryGetInt32Constant(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by GetFloat64ForToNumber(), GetInt32ElementIndex(), and VisitCompareOperation().
GetInt32Constant()
Int32Constant* v8::internal::maglev::MaglevGraphBuilder::GetInt32Constant (int32_t constant) [inline]
Definition at line 325 of file maglev-graph-builder.h.
                                                    {
    return graph()->GetInt32Constant(constant);
  }
References v8::internal::maglev::Graph::GetInt32Constant(), and graph().
Referenced by BuildInt32BinarySmiOperationNode(), BuildLoadFixedDoubleArrayElement(), BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), GetInt32(), GetInt32ElementIndex(), GetNumberConstant(), GetTruncatedInt32ForToNumber(), GetUint8ClampedForToNumber(), TryBuildNewConsString(), TryFoldInt32BinaryOperation(), and TryFoldInt32UnaryOperation().
GetInt32ElementIndex() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex (interpreter::Register reg) [inline], [private]
Definition at line 2451 of file maglev-graph-builder.h.
                                                           {
    ValueNode* index_object = current_interpreter_frame_.get(reg);
    return GetInt32ElementIndex(index_object);
  }
Referenced by GetUint32ElementIndex().
GetInt32ElementIndex() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex (ValueNode * index_object) [private]
Definition at line 6055 of file maglev-graph-builder.cc.
                                                                     {
  RecordUseReprHintIfPhi(object, UseRepresentation::kInt32);
  switch (object->properties().value_representation()) {
    case ValueRepresentation::kIntPtr:
      return AddNewNode<CheckedIntPtrToInt32>({object});
    case ValueRepresentation::kTagged:
      NodeType old_type;
      if (SmiConstant* constant = object->TryCast<SmiConstant>()) {
        return GetInt32Constant(constant->value().value());
      } else if (CheckType(object, NodeType::kSmi, &old_type)) {
        auto& alternative = GetOrCreateInfoFor(object)->alternative();
        return alternative.get_or_set_int32(
            [&]() { return BuildSmiUntag(object); });
      } else {
        // TODO(leszeks): Cache this knowledge/converted value somehow on
        // the node info.
        return AddNewNode<CheckedObjectToIndex>({object},
                                                GetCheckType(old_type));
      }
    case ValueRepresentation::kInt32:
      // Already good.
      return object;
    case ValueRepresentation::kUint32:
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      return GetInt32(object);
  }
}
References v8::internal::maglev::NodeInfo::alternative(), BuildSmiUntag(), CheckType(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetInt32(), GetInt32Constant(), GetOrCreateInfoFor(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::NodeBase::properties(), RecordUseReprHintIfPhi(), v8::internal::maglev::NodeBase::TryCast(), and v8::internal::maglev::OpProperties::value_representation().
GetInternalizedString()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString (interpreter::Register reg) [private]
Definition at line 1659 of file maglev-graph-builder.cc.
                             {
  ValueNode* node = current_interpreter_frame_.get(reg);
  NodeType old_type;
  if (CheckType(node, NodeType::kInternalizedString, &old_type)) return node;
  NodeInfo* known_info = GetOrCreateInfoFor(node);
  if (known_info->alternative().checked_value()) {
    node = known_info->alternative().checked_value();
    if (CheckType(node, NodeType::kInternalizedString, &old_type)) return node;
  }
  if (!NodeTypeIs(old_type, NodeType::kString)) {
    known_info->IntersectType(NodeType::kString);
  }
  // This node may unwrap ThinStrings.
  ValueNode* maybe_unwrapping_node =
      AddNewNode<CheckedInternalizedString>({node}, GetCheckType(old_type));
  known_info->alternative().set_checked_value(maybe_unwrapping_node);
  current_interpreter_frame_.set(reg, maybe_unwrapping_node);
  return maybe_unwrapping_node;
}
References v8::internal::maglev::NodeInfo::alternative(), CheckType(), current_interpreter_frame_, v8::internal::maglev::InterpreterFrameState::get(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetCheckType(), GetOrCreateInfoFor(), v8::internal::maglev::NodeInfo::IntersectType(), v8::internal::maglev::NodeTypeIs(), and v8::internal::maglev::InterpreterFrameState::set().
Referenced by VisitCompareOperation().
GetIntPtrConstant()
IntPtrConstant* v8::internal::maglev::MaglevGraphBuilder::GetIntPtrConstant (intptr_t constant) [inline]
Definition at line 328 of file maglev-graph-builder.h.
                                                       {
    return graph()->GetIntPtrConstant(constant);
  }
References v8::internal::maglev::Graph::GetIntPtrConstant(), and graph().
GetLatestCheckpointedFrame()
DeoptFrame v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame ()
Definition at line 1367 of file maglev-graph-builder.cc.
                                                          {
  if (in_prologue_) {
    return GetDeoptFrameForEntryStackCheck();
  }
  if (!latest_checkpointed_frame_) {
    current_interpreter_frame_.virtual_objects().Snapshot();
    latest_checkpointed_frame_.emplace(InterpretedDeoptFrame(
        *compilation_unit_,
        zone()->New<CompactInterpreterFrameState>(
            *compilation_unit_, GetInLiveness(), current_interpreter_frame_),
        GetClosure(), BytecodeOffset(iterator_.current_offset()),
        current_source_position_, GetCallerDeoptFrame()));
    latest_checkpointed_frame_->as_interpreted().frame_state()->ForEachValue(
        *compilation_unit_,
        [&](ValueNode* node, interpreter::Register) { AddDeoptUse(node); });
    AddDeoptUse(latest_checkpointed_frame_->as_interpreted().closure());
    // Skip lazy deopt builtin continuations.
    const DeoptFrameScope* deopt_scope = current_deopt_scope_;
    while (deopt_scope != nullptr &&
           deopt_scope->IsLazyDeoptContinuationFrame()) {
      deopt_scope = deopt_scope->parent();
    }
    if (deopt_scope != nullptr) {
      // Support exactly one eager deopt builtin continuation. This can be
      // expanded in the future if necessary.
      DCHECK_NULL(deopt_scope->parent());
      DCHECK_EQ(deopt_scope->data().tag(),
                DeoptFrame::FrameType::kBuiltinContinuationFrame);
#ifdef DEBUG
      if (deopt_scope->data().tag() ==
          DeoptFrame::FrameType::kBuiltinContinuationFrame) {
        const DeoptFrame::BuiltinContinuationFrameData& frame =
            deopt_scope->data().get<DeoptFrame::BuiltinContinuationFrameData>();
        if (frame.maybe_js_target) {
          int stack_parameter_count =
              Builtins::GetStackParameterCount(frame.builtin_id);
          DCHECK_EQ(stack_parameter_count, frame.parameters.length());
        } else {
          CallInterfaceDescriptor descriptor =
              Builtins::CallInterfaceDescriptorFor(frame.builtin_id);
          DCHECK_EQ(descriptor.GetParameterCount(), frame.parameters.length());
        }
      }
#endif
      // Wrap the above frame in the scope frame.
      latest_checkpointed_frame_.emplace(
          deopt_scope->data(),
          zone()->New<DeoptFrame>(*latest_checkpointed_frame_));
    }
  }
  return *latest_checkpointed_frame_;
}
References AddDeoptUse(), v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::builtin_id, v8::internal::Builtins::CallInterfaceDescriptorFor(), compilation_unit_, current_deopt_scope_, current_interpreter_frame_, v8::internal::interpreter::BytecodeArrayIterator::current_offset(), current_source_position_, v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::data(), DCHECK_EQ, DCHECK_NULL, v8::base::DiscriminatedUnion< TagEnum, Ts >::get(), GetCallerDeoptFrame(), GetClosure(), GetDeoptFrameForEntryStackCheck(), GetInLiveness(), v8::internal::CallInterfaceDescriptor::GetParameterCount(), v8::internal::Builtins::GetStackParameterCount(), in_prologue_, v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::IsLazyDeoptContinuationFrame(), iterator_, v8::internal::maglev::DeoptFrame::kBuiltinContinuationFrame, latest_checkpointed_frame_, v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::maybe_js_target, v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::parameters, v8::internal::maglev::MaglevGraphBuilder::DeoptFrameScope::parent(), v8::internal::maglev::VirtualObjectList::Snapshot(), v8::base::DiscriminatedUnion< TagEnum, Ts >::tag(), v8::internal::maglev::InterpreterFrameState::virtual_objects(), and zone().
Referenced by AttachDeoptCheckpoint(), AttachEagerDeoptInfo(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
GetModifiableObjectFromAllocation()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::GetModifiableObjectFromAllocation (InlinedAllocation * allocation) [private]
Definition at line 5200 of file maglev-graph-builder.cc.
                                   {
  VirtualObject* vobject = allocation->object();
  // If it hasn't be snapshotted yet, it is the latest created version of this
  // object and we can still modify it, we don't need to copy it.
  if (vobject->IsSnapshot()) {
    return DeepCopyVirtualObject(
        current_interpreter_frame_.virtual_objects().FindAllocatedWith(
            allocation));
  }
  return vobject;
}
References current_interpreter_frame_, DeepCopyVirtualObject(), v8::internal::maglev::VirtualObjectList::FindAllocatedWith(), v8::internal::maglev::VirtualObject::IsSnapshot(), v8::internal::maglev::InlinedAllocation::object(), and v8::internal::maglev::InterpreterFrameState::virtual_objects().
Referenced by TryBuildStoreTaggedFieldToAllocation().
GetNumberConstant()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetNumberConstant (double constant)
Definition at line 2511 of file maglev-graph-builder.cc.
                                                                {
  if (IsSmiDouble(constant)) {
    return GetInt32Constant(FastD2I(constant));
  }
  return GetFloat64Constant(constant);
}
References v8::internal::FastD2I(), GetFloat64Constant(), GetInt32Constant(), and v8::internal::IsSmiDouble().
Referenced by TryFoldFloat64BinaryOperationForToNumber(), and TryFoldFloat64UnaryOperationForToNumber().
GetObjectFromAllocation()
VirtualObject * v8::internal::maglev::MaglevGraphBuilder::GetObjectFromAllocation (InlinedAllocation * allocation) [private]
Definition at line 5188 of file maglev-graph-builder.cc.
                                   {
  VirtualObject* vobject = allocation->object();
  // If it hasn't be snapshotted yet, it is the latest created version of this
  // object, we don't need to search for it.
  if (vobject->IsSnapshot()) {
    vobject = current_interpreter_frame_.virtual_objects().FindAllocatedWith(
        allocation);
  }
  return vobject;
}
References current_interpreter_frame_, v8::internal::maglev::VirtualObjectList::FindAllocatedWith(), v8::internal::maglev::VirtualObject::IsSnapshot(), v8::internal::maglev::InlinedAllocation::object(), and v8::internal::maglev::InterpreterFrameState::virtual_objects().
Referenced by BuildLoadFixedArrayElement(), and BuildLoadFixedDoubleArrayElement().
GetOrCreateInfoFor()
NodeInfo* v8::internal::maglev::MaglevGraphBuilder::GetOrCreateInfoFor (ValueNode * node) [inline], [private]
Definition at line 545 of file maglev-graph-builder.h.
                                                {
    return known_node_aspects().GetOrCreateInfoFor(broker(), node);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::GetOrCreateInfoFor(), and known_node_aspects().
Referenced by BuildCheckMaps(), BuildCompareMaps(), BuildLoadField(), BuildLoadJSArrayLength(), BuildStoreMap(), BuildTransitionElementsKindAndCompareMaps(), BuildTransitionElementsKindOrCheckMap(), CanElideWriteBarrier(), GetFloat64ForToNumber(), GetInt32(), GetInt32ElementIndex(), GetInternalizedString(), GetSmiValue(), GetTaggedValue(), GetTruncatedInt32ForToNumber(), and SetKnownValue().
GetOutLiveness()
const compiler::BytecodeLivenessState* v8::internal::maglev::MaglevGraphBuilder::GetOutLiveness () const [inline], [private]
Definition at line 1895 of file maglev-graph-builder.h.
                                                              {
    return GetOutLivenessFor(iterator_.current_offset());
  }
Referenced by GetDeoptFrameForLazyDeoptHelper().
GetOutLivenessFor()
const compiler::BytecodeLivenessState* v8::internal::maglev::MaglevGraphBuilder::GetOutLivenessFor (int offset) const [inline], [private]
Definition at line 1898 of file maglev-graph-builder.h.
                                                                           {
    return bytecode_analysis().GetOutLivenessFor(offset);
  }
GetRefOperand()
template<class T >
compiler::ref_traits<T>::ref_type v8::internal::maglev::MaglevGraphBuilder::GetRefOperand (int operand_index) [inline], [private]
Definition at line 1480 of file maglev-graph-builder.h.
  {
    // The BytecodeArray itself was fetched by using a barrier so all reads
    // from the constant pool are safe.
    return MakeRefAssumeMemoryFence(
        broker(), broker()->CanonicalPersistentHandle(
                      Cast<T>(iterator_.GetConstantForIndexOperand(
                          operand_index, local_isolate()))));
  }
References broker(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
GetRegisterInput()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetRegisterInput (Register reg) [inline], [private]
Definition at line 1493 of file maglev-graph-builder.h.
                                            {
    DCHECK(!graph_->register_inputs().has(reg));
    graph_->register_inputs().set(reg);
    return AddNewNode<RegisterInput>({}, reg);
  }
References DCHECK.
Referenced by BuildRegisterFrameInitialization().
GetResultLocationAndSize()
std::pair< interpreter::Register, int > v8::internal::maglev::MaglevGraphBuilder::GetResultLocationAndSize () const [private]
Definition at line 1286 of file maglev-graph-builder.cc.
                                                   {
  using Bytecode = interpreter::Bytecode;
  using OperandType = interpreter::OperandType;
  using ImplicitRegisterUse = interpreter::ImplicitRegisterUse;
  Bytecode bytecode = iterator_.current_bytecode();
  // TODO(leszeks): Only emit these cases for bytecodes we know can lazy deopt.
  switch (bytecode) {
#define CASE(Name, ...) \
  case Bytecode::k##Name: \
    return GetResultLocationAndSizeForBytecode<Bytecode::k##Name, \
                                               __VA_ARGS__>(iterator_);
    BYTECODE_LIST(CASE, CASE)
#undef CASE
  }
  UNREACHABLE();
}
References bytecode(), BYTECODE_LIST, CASE, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), iterator_, and v8::internal::UNREACHABLE().
Referenced by AttachLazyDeoptInfo().
GetRootConstant()
RootConstant* v8::internal::maglev::MaglevGraphBuilder::GetRootConstant (RootIndex index) [inline]
Definition at line 340 of file maglev-graph-builder.h.
                                                 {
    return graph()->GetRootConstant(index);
  }
References v8::internal::maglev::Graph::GetRootConstant(), graph(), and v8::internal::index.
Referenced by BuildLoadFixedArrayElement(), BuildLoadFixedDoubleArrayElement(), BuildNewConsStringMap(), BuildRegisterFrameInitialization(), BuildTaggedEqual(), TryBuildPropertyLoad(), TryReduceTypeOf(), and VisitCompareOperation().
GetSecondValue()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetSecondValue (ValueNode * result) [inline], [private]
Definition at line 1732 of file maglev-graph-builder.h.
                                               {
    // GetSecondReturnedValue must be added just after a node that calls a
    // builtin that expects 2 returned values. It simply binds kReturnRegister1
    // to a value node. Since the previous node must have been a builtin
    // call, the register is available in the register allocator. No gap moves
    // would be emitted between these two nodes.
    if (result->opcode() == Opcode::kCallRuntime) {
      DCHECK_EQ(result->Cast<CallRuntime>()->ReturnCount(), 2);
    } else if (result->opcode() == Opcode::kCallBuiltin) {
      DCHECK_EQ(result->Cast<CallBuiltin>()->ReturnCount(), 2);
    } else {
      DCHECK_EQ(result->opcode(), Opcode::kForInPrepare);
    }
    // {result} must be the last node in the current block.
    DCHECK_EQ(node_buffer().back(), result);
    return AddNewNode<GetSecondReturnedValue>({});
  }
References DCHECK_EQ, v8::base::internal::result, v8::internal::maglev::CallBuiltin::ReturnCount(), and v8::internal::maglev::CallRuntime::ReturnCount().
GetSilencedNaN()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetSilencedNaN (ValueNode * value) [inline], [private]
Definition at line 1671 of file maglev-graph-builder.h.
                                              {
    DCHECK_EQ(value->properties().value_representation(),
              ValueRepresentation::kFloat64);
    // We only need to check for silenced NaN in non-conversion nodes or
    // conversion from tagged, since they can't be signalling NaNs.
    if (value->properties().is_conversion()) {
      // A conversion node should have at least one input.
      DCHECK_GE(value->input_count(), 1);
      // If the conversion node is tagged, we could be reading a fabricated sNaN
      // value (built using a BufferArray for example).
      if (!value->input(0).node()->properties().is_tagged()) {
        return value;
      }
    }
    // Special case constants, since we know what they are.
    Float64Constant* constant = value->TryCast<Float64Constant>();
    if (constant) {
      constexpr double quiet_NaN = std::numeric_limits<double>::quiet_NaN();
      if (!constant->value().is_nan()) return constant;
      return GetFloat64Constant(quiet_NaN);
    }
    // Silence all other values.
    return AddNewNode<HoleyFloat64ToMaybeNanFloat64>({value});
  }
References DCHECK_EQ, DCHECK_GE, v8::internal::Float64::is_nan(), v8::internal::maglev::Float64Constant::value(), and v8::internal::value.
GetSlotOperand()
FeedbackSlot v8::internal::maglev::MaglevGraphBuilder::GetSlotOperand (int operand_index) const [inline], [private]
Definition at line 1467 of file maglev-graph-builder.h.
                                                       {
    return iterator_.GetSlotOperand(operand_index);
  }
Referenced by BuildGenericBinaryOperationNode(), BuildGenericBinarySmiOperationNode(), and BuildGenericUnaryOperationNode().
GetSmiConstant()
SmiConstant* v8::internal::maglev::MaglevGraphBuilder::GetSmiConstant (int constant) const [inline]
Definition at line 319 of file maglev-graph-builder.h.
                                                  {
    return graph()->GetSmiConstant(constant);
  }
References v8::internal::maglev::Graph::GetSmiConstant(), and graph().
Referenced by BuildGenericBinarySmiOperationNode(), and GetTaggedValue().
GetSmiValue() [1/2]
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::GetSmiValue (interpreter::Register reg, UseReprHintRecording record_use_repr_hint = UseReprHintRecording::kRecord) [inline], [private]
Definition at line 1527 of file maglev-graph-builder.h.
                                                                 {
    ValueNode* value = current_interpreter_frame_.get(reg);
    return GetSmiValue(value, record_use_repr_hint);
  }
References v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue(), and v8::internal::value.
GetSmiValue() [2/2]
ReduceResult v8::internal::maglev::MaglevGraphBuilder::GetSmiValue (ValueNode * value, UseReprHintRecording record_use_repr_hint = UseReprHintRecording::kRecord) [private]
Definition at line 1596 of file maglev-graph-builder.cc.
                                                                 {
  if (V8_LIKELY(record_use_repr_hint == UseReprHintRecording::kRecord)) {
    RecordUseReprHintIfPhi(value, UseRepresentation::kTagged);
  }
  NodeInfo* node_info = GetOrCreateInfoFor(value);
  ValueRepresentation representation =
      value->properties().value_representation();
  if (representation == ValueRepresentation::kTagged) {
    return BuildCheckSmi(value, !value->Is<Phi>());
  }
  auto& alternative = node_info->alternative();
  if (ValueNode* alt = alternative.tagged()) {
    // HoleyFloat64ToTagged does not canonicalize Smis by default, since it can
    // be expensive. If we are reading a Smi value, we should try to
    // canonicalize now.
    if (HoleyFloat64ToTagged* conversion_node =
            alt->TryCast<HoleyFloat64ToTagged>()) {
      conversion_node->SetMode(
          HoleyFloat64ToTagged::ConversionMode::kCanonicalizeSmi);
    }
    return BuildCheckSmi(alt, !value->Is<Phi>());
  }
  switch (representation) {
    case ValueRepresentation::kInt32: {
      if (NodeTypeIsSmi(node_info->type())) {
        return alternative.set_tagged(AddNewNode<UnsafeSmiTagInt32>({value}));
      }
      return alternative.set_tagged(AddNewNode<CheckedSmiTagInt32>({value}));
    }
    case ValueRepresentation::kUint32: {
      if (NodeTypeIsSmi(node_info->type())) {
        return alternative.set_tagged(AddNewNode<UnsafeSmiTagUint32>({value}));
      }
      return alternative.set_tagged(AddNewNode<CheckedSmiTagUint32>({value}));
    }
    case ValueRepresentation::kFloat64: {
      return alternative.set_tagged(AddNewNode<CheckedSmiTagFloat64>({value}));
    }
    case ValueRepresentation::kHoleyFloat64: {
      return alternative.set_tagged(AddNewNode<CheckedSmiTagFloat64>({value}));
    }
    case ValueRepresentation::kIntPtr:
      return alternative.set_tagged(AddNewNode<CheckedSmiTagIntPtr>({value}));
    case ValueRepresentation::kTagged:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::maglev::NodeInfo::alternative(), BuildCheckSmi(), GetOrCreateInfoFor(), v8::internal::maglev::HoleyFloat64ToTagged::kCanonicalizeSmi, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kRecord, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, RecordUseReprHintIfPhi(), v8::internal::maglev::NodeInfo::type(), v8::internal::UNREACHABLE(), V8_LIKELY, and v8::internal::value.
Referenced by TryBuildPropertyCellStore().
GetTaggedIndexConstant()
TaggedIndexConstant* v8::internal::maglev::MaglevGraphBuilder::GetTaggedIndexConstant (int constant) [inline]
Definition at line 322 of file maglev-graph-builder.h.
                                                            {
    return graph()->GetTaggedIndexConstant(constant);
  }
References v8::internal::maglev::Graph::GetTaggedIndexConstant(), and graph().
GetTaggedValue() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetTaggedValue (interpreter::Register reg, UseReprHintRecording record_use_repr_hint = UseReprHintRecording::kRecord) [inline], [private]
Definition at line 1534 of file maglev-graph-builder.h.
                                                             {
    ValueNode* value = current_interpreter_frame_.get(reg);
    return GetTaggedValue(value, record_use_repr_hint);
  }
References v8::internal::value.
GetTaggedValue() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetTaggedValue (ValueNode * value, UseReprHintRecording record_use_repr_hint = UseReprHintRecording::kRecord) [private]
Definition at line 1532 of file maglev-graph-builder.cc.
                                                                 {
  if (V8_LIKELY(record_use_repr_hint == UseReprHintRecording::kRecord)) {
    RecordUseReprHintIfPhi(value, UseRepresentation::kTagged);
  }
  ValueRepresentation representation =
      value->properties().value_representation();
  if (representation == ValueRepresentation::kTagged) return value;
  if (Int32Constant* as_int32_constant = value->TryCast<Int32Constant>();
      as_int32_constant && Smi::IsValid(as_int32_constant->value())) {
    return GetSmiConstant(as_int32_constant->value());
  }
  NodeInfo* node_info = GetOrCreateInfoFor(value);
  auto& alternative = node_info->alternative();
  if (ValueNode* alt = alternative.tagged()) {
    return alt;
  }
  // This is called when converting inputs in AddNewNode. We might already have
  // an empty type for `value` here. Make sure we don't add unsafe conversion
  // nodes in that case by checking for the empty node type explicitly.
  // TODO(marja): The checks can be removed after we're able to bail out
  // earlier.
  switch (representation) {
    case ValueRepresentation::kInt32: {
      if (!IsEmptyNodeType(node_info->type()) &&
          NodeTypeIsSmi(node_info->type())) {
        return alternative.set_tagged(AddNewNode<UnsafeSmiTagInt32>({value}));
      }
      return alternative.set_tagged(AddNewNode<Int32ToNumber>({value}));
    }
    case ValueRepresentation::kUint32: {
      if (!IsEmptyNodeType(node_info->type()) &&
          NodeTypeIsSmi(node_info->type())) {
        return alternative.set_tagged(AddNewNode<UnsafeSmiTagUint32>({value}));
      }
      return alternative.set_tagged(AddNewNode<Uint32ToNumber>({value}));
    }
    case ValueRepresentation::kFloat64: {
      return alternative.set_tagged(AddNewNode<Float64ToTagged>(
          {value}, Float64ToTagged::ConversionMode::kCanonicalizeSmi));
    }
    case ValueRepresentation::kHoleyFloat64: {
      return alternative.set_tagged(AddNewNode<HoleyFloat64ToTagged>(
          {value}, HoleyFloat64ToTagged::ConversionMode::kForceHeapNumber));
    }
    case ValueRepresentation::kIntPtr:
      if (!IsEmptyNodeType(node_info->type()) &&
          NodeTypeIsSmi(node_info->type())) {
        return alternative.set_tagged(AddNewNode<UnsafeSmiTagIntPtr>({value}));
      }
      return alternative.set_tagged(AddNewNode<IntPtrToNumber>({value}));
    case ValueRepresentation::kTagged:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::maglev::NodeInfo::alternative(), GetOrCreateInfoFor(), GetSmiConstant(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::Smi::IsValid(), v8::internal::maglev::Float64ToTagged::kCanonicalizeSmi, v8::internal::maglev::kFloat64, v8::internal::maglev::HoleyFloat64ToTagged::kForceHeapNumber, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kRecord, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, RecordUseReprHintIfPhi(), v8::internal::maglev::NodeInfo::type(), v8::internal::UNREACHABLE(), V8_LIKELY, and v8::internal::value.
Referenced by BuildTaggedEqual(), TryBuildNamedAccess(), and VisitCompareOperation().
GetTruncatedInt32ForToNumber() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber (interpreter::Register reg, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [inline], [private]
Definition at line 1553 of file maglev-graph-builder.h.
                                                     {
    return GetTruncatedInt32ForToNumber(current_interpreter_frame_.get(reg),
                                        allowed_input_type, conversion_type);
  }
GetTruncatedInt32ForToNumber() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber (ValueNode * value, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 1683 of file maglev-graph-builder.cc.
                                                   {
  RecordUseReprHintIfPhi(value, UseRepresentation::kTruncatedInt32);
  ValueRepresentation representation =
      value->properties().value_representation();
  if (representation == ValueRepresentation::kInt32) return value;
  if (representation == ValueRepresentation::kUint32) {
    // This node is cheap (no code gen, just a bitcast), so don't cache it.
    return AddNewNode<TruncateUint32ToInt32>({value});
  }
  // Process constants first to avoid allocating NodeInfo for them.
  switch (value->opcode()) {
    case Opcode::kConstant: {
      compiler::ObjectRef object = value->Cast<Constant>()->object();
      if (!object.IsHeapNumber()) break;
      int32_t truncated_value = DoubleToInt32(object.AsHeapNumber().value());
      if (!Smi::IsValid(truncated_value)) break;
      return GetInt32Constant(truncated_value);
    }
    case Opcode::kSmiConstant:
      return GetInt32Constant(value->Cast<SmiConstant>()->value().value());
    case Opcode::kRootConstant: {
      Tagged<Object> root_object =
          local_isolate_->root(value->Cast<RootConstant>()->index());
      if (!IsOddball(root_object, local_isolate_)) break;
      int32_t truncated_value =
          DoubleToInt32(Cast<Oddball>(root_object)->to_number_raw());
      // All oddball ToNumber truncations are valid Smis.
      DCHECK(Smi::IsValid(truncated_value));
      return GetInt32Constant(truncated_value);
    }
    case Opcode::kFloat64Constant: {
      int32_t truncated_value =
          DoubleToInt32(value->Cast<Float64Constant>()->value().get_scalar());
      if (!Smi::IsValid(truncated_value)) break;
      return GetInt32Constant(truncated_value);
    }
    // We could emit unconditional eager deopts for other kinds of constant, but
    // it's not necessary, the appropriate checking conversion nodes will deopt.
    default:
      break;
  }
  NodeInfo* node_info = GetOrCreateInfoFor(value);
  auto& alternative = node_info->alternative();
  // If there is an int32_alternative, then that works as a truncated value
  // too.
  if (ValueNode* alt = alternative.int32()) {
    return alt;
  }
  if (ValueNode* alt = alternative.truncated_int32_to_number()) {
    return alt;
  }
  switch (representation) {
    case ValueRepresentation::kTagged: {
      NodeType old_type;
      EnsureType(value, allowed_input_type, &old_type);
      if (NodeTypeIsSmi(old_type)) {
        // Smi untagging can be cached as an int32 alternative, not just a
        // truncated alternative.
        return alternative.set_int32(BuildSmiUntag(value));
      }
      if (allowed_input_type == NodeType::kSmi) {
        return alternative.set_int32(AddNewNode<CheckedSmiUntag>({value}));
      }
      if (NodeTypeIs(old_type, allowed_input_type)) {
        return alternative.set_truncated_int32_to_number(
            AddNewNode<TruncateNumberOrOddballToInt32>({value},
                                                       conversion_type));
      }
      return alternative.set_truncated_int32_to_number(
          AddNewNode<CheckedTruncateNumberOrOddballToInt32>({value},
                                                            conversion_type));
    }
    case ValueRepresentation::kFloat64:
    // Ignore conversion_type for HoleyFloat64, and treat them like Float64.
    // ToNumber of undefined is anyway a NaN, so we'll simply truncate away
    // the NaN-ness of the hole, and don't need to do extra oddball checks so
    // we can ignore the hint (though we'll miss updating the feedback).
    case ValueRepresentation::kHoleyFloat64: {
      return alternative.set_truncated_int32_to_number(
          AddNewNode<TruncateFloat64ToInt32>({value}));
    }
    case ValueRepresentation::kIntPtr: {
      // This is not an efficient implementation, but this only happens in
      // corner cases.
      ValueNode* value_to_number = AddNewNode<IntPtrToNumber>({value});
      return alternative.set_truncated_int32_to_number(
          AddNewNode<TruncateNumberOrOddballToInt32>(
              {value_to_number}, TaggedToFloat64ConversionType::kOnlyNumber));
    }
    case ValueRepresentation::kInt32:
    case ValueRepresentation::kUint32:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::maglev::NodeInfo::alternative(), BuildSmiUntag(), v8::internal::DCHECK(), v8::internal::DoubleToInt32(), EnsureType(), v8::internal::Float64::get_scalar(), GetInt32Constant(), GetOrCreateInfoFor(), v8::internal::maglev::RootConstant::index(), v8::internal::Smi::IsValid(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kOnlyNumber, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kTruncatedInt32, v8::internal::maglev::kUint32, local_isolate_, v8::internal::maglev::NodeTypeIs(), RecordUseReprHintIfPhi(), v8::internal::LocalIsolate::root(), v8::internal::UNREACHABLE(), v8::internal::maglev::Float64Constant::value(), v8::internal::maglev::SmiConstant::value(), v8::internal::value, and v8::internal::Tagged< Smi >::value().
Referenced by BuildTruncatingInt32BinaryOperationNodeForToNumber(), BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), and BuildTruncatingInt32BitwiseNotForToNumber().
GetTrustedConstant()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetTrustedConstant (compiler::HeapObjectRef ref, IndirectPointerTag tag) [inline]
Definition at line 349 of file maglev-graph-builder.h.
                                                        {
    return graph()->GetTrustedConstant(ref, tag);
  }
References v8::internal::maglev::Graph::GetTrustedConstant(), and graph().
GetTryCatchBlockForNonEagerInlining()
CatchBlockDetails v8::internal::maglev::MaglevGraphBuilder::GetTryCatchBlockForNonEagerInlining (ExceptionHandlerInfo * info) [inline], [private]
Definition at line 1276 of file maglev-graph-builder.h.
                                  {
    if (IsInsideTryBlock()) {
      return {info->catch_block_ref_address(), !info->ShouldLazyDeopt(), true,
              0};
    }
    if (!is_inline()) {
      return CatchBlockDetails{};
    }
    // Since this CatchBlockDetails is stored in a non-eager call site,
    // the catch block will already exist by the time inlining is attempted.
    CatchBlockDetails catch_details = caller_details_->catch_block;
    catch_details.block_already_exists = true;
    return catch_details;
  }
References v8::internal::maglev::CatchBlockDetails::block_already_exists, caller_details_, v8::internal::maglev::MaglevCallerDetails::catch_block, v8::internal::maglev::ExceptionHandlerInfo::catch_block_ref_address(), is_inline(), IsInsideTryBlock(), and v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt().
GetType()
NodeType v8::internal::maglev::MaglevGraphBuilder::GetType (ValueNode * node) [inline], [private]
Definition at line 542 of file maglev-graph-builder.h.
                                    {
    return known_node_aspects().GetType(broker(), node);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::GetType(), and known_node_aspects().
Referenced by BuildCheckHeapObject(), BuildCheckJSFunction(), BuildCheckJSReceiver(), BuildCheckJSReceiverOrNullOrUndefined(), BuildCheckMaps(), BuildCheckNumber(), BuildCheckSeqOneByteString(), BuildCheckSmi(), BuildCheckString(), BuildCheckStringOrOddball(), BuildCheckStringOrStringWrapper(), BuildCheckSymbol(), BuildLoadJSFunctionContext(), BuildLoadJSFunctionFeedbackCell(), BuildSmiUntag(), BuildUnwrapStringWrapper(), CanElideWriteBarrier(), GetInt32(), TryBuildNewConsString(), TryBuildStoreField(), and TrySpecializeStoreContextSlot().
GetUint32Constant()
Uint32Constant* v8::internal::maglev::MaglevGraphBuilder::GetUint32Constant (int constant) [inline]
Definition at line 331 of file maglev-graph-builder.h.
                                                  {
    return graph()->GetUint32Constant(constant);
  }
References v8::internal::maglev::Graph::GetUint32Constant(), and graph().
Referenced by GetUint32ElementIndex(), and TryFoldInt32BinaryOperation().
GetUint32ElementIndex() [1/2]
ReduceResult v8::internal::maglev::MaglevGraphBuilder::GetUint32ElementIndex (interpreter::Register reg) [inline], [private]
Definition at line 2457 of file maglev-graph-builder.h.
                                                              {
    ValueNode* index_object = current_interpreter_frame_.get(reg);
    return GetUint32ElementIndex(index_object);
  }
GetUint32ElementIndex() [2/2]
ReduceResult v8::internal::maglev::MaglevGraphBuilder::GetUint32ElementIndex (ValueNode * index_object) [private]
Definition at line 6087 of file maglev-graph-builder.cc.
                                                                        {
  // Don't record a Uint32 Phi use here, since the tagged path goes via
  // GetInt32ElementIndex, making this an Int32 Phi use.
  switch (object->properties().value_representation()) {
    case ValueRepresentation::kIntPtr:
      return AddNewNode<CheckedIntPtrToUint32>({object});
    case ValueRepresentation::kTagged:
      // TODO(victorgomes): Consider creating a CheckedObjectToUnsignedIndex.
      if (SmiConstant* constant = object->TryCast<SmiConstant>()) {
        int32_t value = constant->value().value();
        if (value < 0) {
          return EmitUnconditionalDeopt(DeoptimizeReason::kNotUint32);
        }
        return GetUint32Constant(value);
      }
      return AddNewNode<CheckedInt32ToUint32>({GetInt32ElementIndex(object)});
    case ValueRepresentation::kInt32:
      if (Int32Constant* constant = object->TryCast<Int32Constant>()) {
        int32_t value = constant->value();
        if (value < 0) {
          return EmitUnconditionalDeopt(DeoptimizeReason::kNotUint32);
        }
        return GetUint32Constant(value);
      }
      return AddNewNode<CheckedInt32ToUint32>({object});
    case ValueRepresentation::kUint32:
      return object;
    case ValueRepresentation::kFloat64:
      if (Float64Constant* constant = object->TryCast<Float64Constant>()) {
        double value = constant->value().get_scalar();
        uint32_t uint32_value;
        if (!DoubleToUint32IfEqualToSelf(value, &uint32_value)) {
          return EmitUnconditionalDeopt(DeoptimizeReason::kNotUint32);
        }
        if (Smi::IsValid(uint32_value)) {
          return GetUint32Constant(uint32_value);
        }
      }
      [[fallthrough]];
    case ValueRepresentation::kHoleyFloat64: {
      // CheckedTruncateFloat64ToUint32 will gracefully deopt on holes.
      return AddNewNode<CheckedTruncateFloat64ToUint32>({object});
    }
  }
}
References v8::internal::DoubleToUint32IfEqualToSelf(), EmitUnconditionalDeopt(), GetInt32ElementIndex(), GetUint32Constant(), v8::internal::Smi::IsValid(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::value, and v8::internal::maglev::OpProperties::value_representation().
GetUint8ClampedForToNumber() [1/2]
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetUint8ClampedForToNumber (interpreter::Register reg) [inline], [private]
Definition at line 1568 of file maglev-graph-builder.h.
                                                                 {
    return GetUint8ClampedForToNumber(current_interpreter_frame_.get(reg));
  }
GetUint8ClampedForToNumber() [2/2]
ValueNode * v8::internal::maglev::MaglevGraphBuilder::GetUint8ClampedForToNumber (ValueNode * value) [private]
Definition at line 2127 of file maglev-graph-builder.cc.
                                                                          {
  switch (value->properties().value_representation()) {
    case ValueRepresentation::kIntPtr:
      // This is not an efficient implementation, but this only happens in
      // corner cases.
      return AddNewNode<CheckedNumberToUint8Clamped>(
          {AddNewNode<IntPtrToNumber>({value})});
    case ValueRepresentation::kTagged: {
      if (SmiConstant* constant = value->TryCast<SmiConstant>()) {
        return GetInt32Constant(ClampToUint8(constant->value().value()));
      }
      NodeInfo* info = known_node_aspects().TryGetInfoFor(value);
      if (info && info->alternative().int32()) {
        return AddNewNode<Int32ToUint8Clamped>({info->alternative().int32()});
      }
      return AddNewNode<CheckedNumberToUint8Clamped>({value});
    }
    // HoleyFloat64 is treated like Float64. ToNumber of undefined is anyway a
    // NaN, so we'll simply truncate away the NaN-ness of the hole, and don't
    // need to do extra oddball checks (though we'll miss updating the
    // feedback).
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      // TODO(leszeks): Handle Float64Constant, which requires the correct
      // rounding for clamping.
      return AddNewNode<Float64ToUint8Clamped>({value});
    case ValueRepresentation::kInt32:
      if (Int32Constant* constant = value->TryCast<Int32Constant>()) {
        return GetInt32Constant(ClampToUint8(constant->value()));
      }
      return AddNewNode<Int32ToUint8Clamped>({value});
    case ValueRepresentation::kUint32:
      return AddNewNode<Uint32ToUint8Clamped>({value});
  }
  UNREACHABLE();
}
References v8::internal::maglev::NodeInfo::alternative(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::ClampToUint8(), GetInt32Constant(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, known_node_aspects(), v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), v8::internal::UNREACHABLE(), and v8::internal::value.
GetValueOrUndefined()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::GetValueOrUndefined (ValueNode * maybe_value) [inline], [private]
Definition at line 2037 of file maglev-graph-builder.h.
                                                         {
    if (maybe_value == nullptr) {
      return GetRootConstant(RootIndex::kUndefinedValue);
    }
    return maybe_value;
  }
graph()
Graph* v8::internal::maglev::MaglevGraphBuilder::graph () const [inline]
Definition at line 356 of file maglev-graph-builder.h.
{ return graph_; }
References graph_.
Referenced by Build(), BuildInitializeStore(), CheckContextExtensions(), ContextMayAlias(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), GetBooleanConstant(), GetConstant(), GetFloat64Constant(), GetInt32Constant(), GetIntPtrConstant(), GetRootConstant(), GetSmiConstant(), GetTaggedIndexConstant(), GetTrustedConstant(), GetUint32Constant(), and StoreAndCacheContextSlot().
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::MaglevGraphBuilder::graph_labeller () const [inline]
Definition at line 370 of file maglev-graph-builder.h.
                                              {
    if (graph_->has_graph_labeller()) return graph_->graph_labeller();
    return nullptr;
  }
References graph_, v8::internal::maglev::Graph::graph_labeller(), and v8::internal::maglev::Graph::has_graph_labeller().
Referenced by AddInitializedNodeToGraph(), CreateNewConstantNode(), LoadAndCacheContextSlot(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergePhis(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), PrintVirtualObjects(), ProcessMergePointAtExceptionHandlerStart(), v8::internal::maglev::MaglevInliner::RegisterNode(), RegisterPhisWithGraphLabeller(), StoreAndCacheContextSlot(), TryBuildStoreTaggedFieldToAllocation(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
gvn_hash_value() [1/8]
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const compiler::MapRef & map) [inline], [static], [private]
Definition at line 3324 of file maglev-graph-builder.h.
                                                          {
    return map.hash_value();
  }
gvn_hash_value() [2/8]
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const ExternalReference & ref) [inline], [static], [private]
Definition at line 3336 of file maglev-graph-builder.h.
                                                             {
    return base::hash_value(ref.address());
  }
References v8::internal::ExternalReference::address(), and v8::base::hash_value().
gvn_hash_value() [3/8]
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const interpreter::Register & reg) [inline], [static], [private]
Definition at line 3328 of file maglev-graph-builder.h.
                                                               {
    return base::hash_value(reg.index());
  }
References v8::base::hash_value(), and v8::internal::interpreter::Register::index().
gvn_hash_value() [4/8]
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const PolymorphicAccessInfo & access_info) [inline], [static], [private]
Definition at line 3340 of file maglev-graph-builder.h.
                                                                         {
    return access_info.hash_value();
  }
References v8::internal::maglev::PolymorphicAccessInfo::hash_value().
gvn_hash_value() [5/8]
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const Representation & rep) [inline], [static], [private]
Definition at line 3332 of file maglev-graph-builder.h.
                                                          {
    return base::hash_value(rep.kind());
  }
References v8::base::hash_value(), and v8::internal::Representation::kind().
gvn_hash_value() [6/8]
template<typename T >
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const T & in) [inline], [static], [private]
Definition at line 3320 of file maglev-graph-builder.h.
                                            {
    return base::hash_value(in);
  }
References v8::base::hash_value().
Referenced by AddNewNodeOrGetEquivalent().
gvn_hash_value() [7/8]
template<typename T >
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const v8::internal::ZoneCompactSet< T > & vector) [inline], [static], [private]
Definition at line 3345 of file maglev-graph-builder.h.
                                                                          {
    size_t hash = base::hash_value(vector.size());
    for (auto e : vector) {
      hash = fast_hash_combine(hash, gvn_hash_value(e));
    }
    return hash;
  }
References v8::internal::compiler::turboshaft::fast_hash_combine(), v8::base::hash_value(), and v8::internal::ZoneCompactSet< T >::size().
gvn_hash_value() [8/8]
template<typename T >
static size_t v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value (const v8::internal::ZoneVector< T > & vector) [inline], [static], [private]
Definition at line 3354 of file maglev-graph-builder.h.
                                                                      {
    size_t hash = base::hash_value(vector.size());
    for (auto e : vector) {
      hash = fast_hash_combine(hash, gvn_hash_value(e));
    }
    return hash;
  }
References v8::internal::compiler::turboshaft::fast_hash_combine(), v8::base::hash_value(), and v8::internal::ZoneVector< T >::size().
has_graph_labeller()
bool v8::internal::maglev::MaglevGraphBuilder::has_graph_labeller () const [inline]
Definition at line 369 of file maglev-graph-builder.h.
{ return graph_->has_graph_labeller(); }
References graph_, and v8::internal::maglev::Graph::has_graph_labeller().
Referenced by AddInitializedNodeToGraph(), CreateNewConstantNode(), ProcessMergePointAtExceptionHandlerStart(), v8::internal::maglev::MaglevInliner::RegisterNode(), and RegisterPhisWithGraphLabeller().
HasDisjointType()
bool v8::internal::maglev::MaglevGraphBuilder::HasDisjointType (ValueNode * lhs, NodeType rhs_type) [inline], [private]
Definition at line 553 of file maglev-graph-builder.h.
                                                          {
    return known_node_aspects().HasDisjointType(broker(), lhs, rhs_type);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::HasDisjointType(), and known_node_aspects().
HasValidInitialMap()
bool v8::internal::maglev::MaglevGraphBuilder::HasValidInitialMap (compiler::JSFunctionRef new_target, compiler::JSFunctionRef constructor) [private]
Definition at line 8209 of file maglev-graph-builder.cc.
                                                                         {
  if (!new_target.map(broker()).has_prototype_slot()) return false;
  if (!new_target.has_initial_map(broker())) return false;
  compiler::MapRef initial_map = new_target.initial_map(broker());
  return initial_map.GetConstructor(broker()).equals(constructor);
}
References broker(), v8::internal::compiler::JSFunctionRef::has_initial_map(), v8::internal::has_prototype_slot, v8::internal::compiler::initial_map, v8::internal::compiler::JSFunctionRef::initial_map(), and v8::internal::compiler::HeapObjectRef::map().
HaveDisjointTypes()
bool v8::internal::maglev::MaglevGraphBuilder::HaveDisjointTypes (ValueNode * lhs, ValueNode * rhs) [inline], [private]
Definition at line 550 of file maglev-graph-builder.h.
                                                         {
    return known_node_aspects().HaveDisjointTypes(broker(), lhs, rhs);
  }
References broker(), v8::internal::maglev::KnownNodeAspects::HaveDisjointTypes(), and known_node_aspects().
Referenced by BuildTaggedEqual().
in_optimistic_peeling_iteration()
bool v8::internal::maglev::MaglevGraphBuilder::in_optimistic_peeling_iteration () const [inline], [private]
Definition at line 3235 of file maglev-graph-builder.h.
                                               {
    return v8_flags.maglev_optimistic_peeled_loops &&
           peeled_iteration_count_ == 1;
  }
References v8::internal::v8_flags.
Referenced by MarkBytecodeDead(), and VisitSingleBytecode().
in_peeled_iteration()
bool v8::internal::maglev::MaglevGraphBuilder::in_peeled_iteration () const [inline], [private]
Definition at line 3226 of file maglev-graph-builder.h.
                                   {
    DCHECK_GE(peeled_iteration_count_, 0);
    return peeled_iteration_count_ > 0;
  }
References DCHECK_GE.
Referenced by MarkBytecodeDead().
InferHasInPrototypeChain()
MaglevGraphBuilder::InferHasInPrototypeChainResult v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain (ValueNode * receiver, compiler::HeapObjectRef prototype) [private]
Definition at line 12576 of file maglev-graph-builder.cc.
                                                          {
  auto node_info = known_node_aspects().TryGetInfoFor(receiver);
  // If the map set is not found, then we don't know anything about the map of
  // the receiver, so bail.
  if (!node_info || !node_info->possible_maps_are_known()) {
    return kMayBeInPrototypeChain;
  }
  // If the set of possible maps is empty, then there's no possible map for this
  // receiver, therefore this path is unreachable at runtime. We're unlikely to
  // ever hit this case, BuildCheckMaps should already unconditionally deopt,
  // but check it in case another checking operation fails to statically
  // unconditionally deopt.
  if (node_info->possible_maps().is_empty()) {
    // TODO(leszeks): Add an unreachable assert here.
    return kIsNotInPrototypeChain;
  }
  ZoneVector<compiler::MapRef> receiver_map_refs(zone());
  // Try to determine either that all of the {receiver_maps} have the given
  // {prototype} in their chain, or that none do. If we can't tell, return
  // kMayBeInPrototypeChain.
  bool all = true;
  bool none = true;
  for (compiler::MapRef map : node_info->possible_maps()) {
    receiver_map_refs.push_back(map);
    while (true) {
      if (IsSpecialReceiverInstanceType(map.instance_type())) {
        return kMayBeInPrototypeChain;
      }
      if (!map.IsJSObjectMap()) {
        all = false;
        break;
      }
      compiler::HeapObjectRef map_prototype = map.prototype(broker());
      if (map_prototype.equals(prototype)) {
        none = false;
        break;
      }
      map = map_prototype.map(broker());
      // TODO(v8:11457) Support dictionary mode protoypes here.
      if (!map.is_stable() || map.is_dictionary_map()) {
        return kMayBeInPrototypeChain;
      }
      if (map.oddball_type(broker()) == compiler::OddballType::kNull) {
        all = false;
        break;
      }
    }
  }
  DCHECK(!receiver_map_refs.empty());
  DCHECK_IMPLIES(all, !none);
  if (!all && !none) return kMayBeInPrototypeChain;
  {
    compiler::OptionalJSObjectRef last_prototype;
    if (all) {
      // We don't need to protect the full chain if we found the prototype, we
      // can stop at {prototype}. In fact we could stop at the one before
      // {prototype} but since we're dealing with multiple receiver maps this
      // might be a different object each time, so it's much simpler to include
      // {prototype}. That does, however, mean that we must check {prototype}'s
      // map stability.
      if (!prototype.IsJSObject() || !prototype.map(broker()).is_stable()) {
        return kMayBeInPrototypeChain;
      }
      last_prototype = prototype.AsJSObject();
    }
    broker()->dependencies()->DependOnStablePrototypeChains(
        receiver_map_refs, kStartAtPrototype, last_prototype);
  }
  DCHECK_EQ(all, !none);
  return all ? kIsInPrototypeChain : kIsNotInPrototypeChain;
}
References all, broker(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::ZoneVector< T >::empty(), v8::internal::IsSpecialReceiverInstanceType(), v8::internal::compiler::kNull, v8::internal::kStartAtPrototype, v8::internal::compiler::HeapObjectRef::map(), none, v8::internal::prototype, and v8::internal::ZoneVector< T >::push_back().
InitializePredecessorCount()
void v8::internal::maglev::MaglevGraphBuilder::InitializePredecessorCount (uint32_t offset, int amount) [inline], [private]
Definition at line 3198 of file maglev-graph-builder.h.
                                                               {
    DCHECK_LE(offset, bytecode().length());
    DCHECK_NULL(merge_states_[offset]);
    predecessor_count_[offset] = amount;
  }
References DCHECK_LE, DCHECK_NULL, and v8::internal::length.
InitializeRegister()
void v8::internal::maglev::MaglevGraphBuilder::InitializeRegister (interpreter::Register reg, ValueNode * value)
Definition at line 1081 of file maglev-graph-builder.cc.
                                                              {
  current_interpreter_frame_.set(
      reg, value ? value : AddNewNode<InitialValue>({}, reg));
}
References current_interpreter_frame_, v8::internal::maglev::InterpreterFrameState::set(), and v8::internal::value.
Referenced by BuildRegisterFrameInitialization().
inline_exit_offset()
int v8::internal::maglev::MaglevGraphBuilder::inline_exit_offset () const [inline], [private]
Definition at line 3163 of file maglev-graph-builder.h.
                                 {
    DCHECK(is_inline());
    return bytecode().length();
  }
References DCHECK.
Referenced by KillPeeledLoopTargets(), MaglevGraphBuilder(), and MarkBytecodeDead().
inlining_depth()
int v8::internal::maglev::MaglevGraphBuilder::inlining_depth () const [inline]
Definition at line 378 of file maglev-graph-builder.h.
{ return compilation_unit_->inlining_depth(); }
References compilation_unit_, and v8::internal::maglev::MaglevCompilationUnit::inlining_depth().
is_eager_inline()
bool v8::internal::maglev::MaglevGraphBuilder::is_eager_inline () const [inline]
Definition at line 380 of file maglev-graph-builder.h.
                               {
    DCHECK(is_inline());
    DCHECK_IMPLIES(!caller_details_->is_eager_inline,
                   v8_flags.maglev_non_eager_inlining ||
                       v8_flags.turbolev_non_eager_inlining);
    return caller_details_->is_eager_inline;
  }
References caller_details_, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::maglev::MaglevCallerDetails::is_eager_inline, is_inline(), and v8::internal::v8_flags.
is_inline()
bool v8::internal::maglev::MaglevGraphBuilder::is_inline () const [inline]
Definition at line 377 of file maglev-graph-builder.h.
{ return caller_details_ != nullptr; }
References caller_details_.
Referenced by AttachExceptionHandlerInfo(), Build(), BuildBody(), EndPrologue(), GetCallerDeoptFrame(), GetCurrentTryCatchBlock(), GetDeoptFrameForEntryStackCheck(), GetInlinedArgument(), GetTryCatchBlockForNonEagerInlining(), is_eager_inline(), KillPeeledLoopTargets(), MaglevGraphBuilder(), MarkBytecodeDead(), ShouldEmitInterruptBudgetChecks(), and ShouldEmitOsrInterruptBudgetChecks().
is_loop_effect_tracking()
bool v8::internal::maglev::MaglevGraphBuilder::is_loop_effect_tracking () [inline], [private]
Definition at line 3242 of file maglev-graph-builder.h.
{ return loop_effects_; }
Referenced by CanTrackObjectChanges(), and StoreAndCacheContextSlot().
is_loop_effect_tracking_enabled()
bool v8::internal::maglev::MaglevGraphBuilder::is_loop_effect_tracking_enabled () [inline], [private]
Definition at line 3239 of file maglev-graph-builder.h.
                                         {
    return v8_flags.maglev_escape_analysis || v8_flags.maglev_licm;
  }
References v8::internal::v8_flags.
Referenced by VisitSingleBytecode().
is_non_eager_inlining_enabled()
bool v8::internal::maglev::MaglevGraphBuilder::is_non_eager_inlining_enabled () const [inline]
Definition at line 419 of file maglev-graph-builder.h.
                                             {
    if (is_turbolev()) {
      return v8_flags.turbolev_non_eager_inlining;
    }
    return v8_flags.maglev_non_eager_inlining;
  }
References is_turbolev(), and v8::internal::v8_flags.
Referenced by AttachExceptionHandlerInfo().
is_turbolev()
bool v8::internal::maglev::MaglevGraphBuilder::is_turbolev () const [inline]
Definition at line 417 of file maglev-graph-builder.h.
{ return is_turbolev_; }
References is_turbolev_.
Referenced by is_non_eager_inlining_enabled(), max_inline_depth(), max_inlined_bytecode_size(), max_inlined_bytecode_size_cumulative(), max_inlined_bytecode_size_small(), min_inlining_frequency(), ShouldEmitInterruptBudgetChecks(), and TryBuildNewConsString().
IsInsideLoop()
bool v8::internal::maglev::MaglevGraphBuilder::IsInsideLoop () const [inline], [private]
Definition at line 3145 of file maglev-graph-builder.h.
                            {
    if (is_inline() && caller_details()->is_inside_loop) return true;
    int loop_header_offset =
        bytecode_analysis().GetLoopOffsetFor(iterator_.current_offset());
    if (loop_header_offset != -1) {
      const compiler::LoopInfo& loop_info =
          bytecode_analysis().GetLoopInfoFor(loop_header_offset);
      if (loop_info.parent_offset() == -1) {
        // This is the outmost loop, if we're actually inside the peel, we are
        // not really in a loop.
        return !in_peeled_iteration() || in_optimistic_peeling_iteration();
      }
      return true;
    }
    return false;
  }
References v8::internal::compiler::LoopInfo::parent_offset().
Referenced by CanTrackObjectChanges().
IsInsideTryBlock()
bool v8::internal::maglev::MaglevGraphBuilder::IsInsideTryBlock () const [inline], [private]
Definition at line 1256 of file maglev-graph-builder.h.
{ return catch_block_stack_.size() > 0; }
References catch_block_stack_.
Referenced by AttachExceptionHandlerInfo(), CanTrackObjectChanges(), GetCatchBlockFrameState(), GetCurrentTryCatchBlock(), GetTryCatchBlockForNonEagerInlining(), and VisitSingleBytecode().
IsOffsetAMergePoint()
bool v8::internal::maglev::MaglevGraphBuilder::IsOffsetAMergePoint (int offset) [inline], [private]
Definition at line 720 of file maglev-graph-builder.h.
                                       {
    return merge_states_[offset] != nullptr;
  }
References merge_states_.
IsRegisterEqualToAccumulator()
bool v8::internal::maglev::MaglevGraphBuilder::IsRegisterEqualToAccumulator (int operand_index) [inline], [private]
Definition at line 1699 of file maglev-graph-builder.h.
                                                       {
    interpreter::Register source = iterator_.GetRegisterOperand(operand_index);
    return current_interpreter_frame_.get(source) ==
           current_interpreter_frame_.accumulator();
  }
Referenced by BuildTruncatingInt32BinaryOperationNodeForToNumber(), and VisitCompareOperation().
KillPeeledLoopTargets()
void v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets (int peelings) [inline], [private]
Definition at line 736 of file maglev-graph-builder.h.
                                           {
    DCHECK_EQ(iterator_.current_bytecode(), interpreter::Bytecode::kJumpLoop);
    int target = iterator_.GetJumpTargetOffset();
    // Since we ended up not peeling we must kill all the doubly accounted
    // jumps out of the loop.
    interpreter::BytecodeArrayIterator iterator(bytecode().object());
    for (iterator.SetOffset(target);
         iterator.current_offset() < iterator_.current_offset();
         iterator.Advance()) {
      interpreter::Bytecode bc = iterator.current_bytecode();
      DCHECK_NE(bc, interpreter::Bytecode::kJumpLoop);
      int kill = -1;
      if (interpreter::Bytecodes::IsJump(bc) &&
          iterator.GetJumpTargetOffset() > iterator_.current_offset()) {
        kill = iterator.GetJumpTargetOffset();
      } else if (is_inline() && interpreter::Bytecodes::Returns(bc)) {
        kill = inline_exit_offset();
      }
      if (kill != -1) {
        if (merge_states_[kill]) {
          for (int i = 0; i < peelings; ++i) {
            merge_states_[kill]->MergeDead(*compilation_unit_);
          }
        }
        UpdatePredecessorCount(kill, -peelings);
      }
    }
  }
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), bytecode(), compilation_unit_, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), DCHECK_EQ, DCHECK_NE, v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, inline_exit_offset(), is_inline(), v8::internal::interpreter::Bytecodes::IsJump(), iterator_, merge_states_, v8::internal::maglev::MergePointInterpreterFrameState::MergeDead(), v8::internal::interpreter::Bytecodes::Returns(), v8::internal::interpreter::BytecodeArrayIterator::SetOffset(), and UpdatePredecessorCount().
known_node_aspects()
KnownNodeAspects& v8::internal::maglev::MaglevGraphBuilder::known_node_aspects () [inline], [private]
Definition at line 3130 of file maglev-graph-builder.h.
                                         {
    return *current_interpreter_frame_.known_node_aspects();
  }
Referenced by AddNewNodeOrGetEquivalent(), BuildCheckMaps(), BuildCompareMaps(), BuildStoreMap(), BuildTestUndetectable(), BuildTransitionElementsKindAndCompareMaps(), BuildTransitionElementsKindOrCheckMap(), CheckType(), CheckTypes(), EnsureType(), GetOrCreateInfoFor(), GetType(), GetUint8ClampedForToNumber(), HasDisjointType(), HaveDisjointTypes(), LoadAndCacheContextSlot(), StoreAndCacheContextSlot(), TryBuildNamedAccess(), and TryGetConstantAlternative().
LoadAndCacheContextSlot()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::LoadAndCacheContextSlot (ValueNode * context, int offset, ContextSlotMutability slot_mutability, ContextMode context_mode) [private]
Definition at line 3565 of file maglev-graph-builder.cc.
                              {
  int offset = Context::OffsetOfElementAt(index);
  ValueNode*& cached_value =
      slot_mutability == kMutable
          ? known_node_aspects().loaded_context_slots[{context, offset}]
          : known_node_aspects().loaded_context_constants[{context, offset}];
  if (cached_value) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " * Reusing cached context slot "
                << PrintNodeLabel(graph_labeller(), context) << "[" << offset
                << "]: " << PrintNode(graph_labeller(), cached_value)
                << std::endl;
    }
    return cached_value;
  }
  if (slot_mutability == kMutable &&
      !known_node_aspects().loaded_context_slots.empty()) {
    known_node_aspects().UpdateMayHaveAliasingContexts(
        broker(), local_isolate(), context);
  }
  if (context_mode == ContextMode::kHasContextCells &&
      (v8_flags.script_context_cells || v8_flags.function_context_cells) &&
      slot_mutability == kMutable) {
    // We collect feedback only for mutable context slots.
    cached_value = TrySpecializeLoadContextSlot(context, index);
    if (cached_value) return cached_value;
    return cached_value = BuildLoadTaggedField<LoadTaggedFieldForContextSlot>(
               context, offset);
  }
  return cached_value =
             BuildLoadTaggedField<LoadTaggedFieldForContextSlotNoCells>(context,
                                                                        offset);
}
References broker(), graph_labeller(), v8::internal::index, v8::internal::kHasContextCells, kMutable, known_node_aspects(), v8::internal::maglev::KnownNodeAspects::loaded_context_constants, v8::internal::maglev::KnownNodeAspects::loaded_context_slots, local_isolate(), v8::internal::Context::OffsetOfElementAt(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), TrySpecializeLoadContextSlot(), v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), and v8::internal::v8_flags.
Referenced by BuildLoadContextSlot(), CheckContextExtensions(), and TryBuildScriptContextLoad().
LoadRegister()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::LoadRegister (int operand_index) [inline], [private]
Definition at line 1705 of file maglev-graph-builder.h.
                                             {
    return current_interpreter_frame_.get(
        iterator_.GetRegisterOperand(operand_index));
  }
Referenced by BuildGenericBinaryOperationNode(), BuildInt32BinaryOperationNode(), TryReduceCompareEqualAgainstConstant(), VisitBinaryOperation(), and VisitCompareOperation().
LoadRegisterHoleyFloat64ForToNumber()
ValueNode* v8::internal::maglev::MaglevGraphBuilder::LoadRegisterHoleyFloat64ForToNumber (int operand_index, NodeType allowed_input_type, TaggedToFloat64ConversionType conversion_type) [inline], [private]
Definition at line 1710 of file maglev-graph-builder.h.
                                                     {
    return GetHoleyFloat64ForToNumber(
        iterator_.GetRegisterOperand(operand_index), allowed_input_type,
        conversion_type);
  }
Referenced by BuildFloat64BinaryOperationNodeForToNumber().
local_isolate()
LocalIsolate* v8::internal::maglev::MaglevGraphBuilder::local_isolate () const [inline]
Definition at line 367 of file maglev-graph-builder.h.
{ return local_isolate_; }
References local_isolate_.
Referenced by LoadAndCacheContextSlot(), and StoreAndCacheContextSlot().
MaglevIsTopTier()
bool v8::internal::maglev::MaglevGraphBuilder::MaglevIsTopTier () const [inline], [private]
Definition at line 591 of file maglev-graph-builder.h.
{ return !v8_flags.turbofan && v8_flags.maglev; }
References v8::internal::v8_flags.
MarkBranchDeadAndJumpIfNeeded()
void v8::internal::maglev::MaglevGraphBuilder::MarkBranchDeadAndJumpIfNeeded (bool is_jump_taken) [private]
Definition at line 14648 of file maglev-graph-builder.cc.
                                                                         {
  int jump_offset = iterator_.GetJumpTargetOffset();
  if (is_jump_taken) {
    BasicBlock* block = FinishBlock<Jump>({}, &jump_targets_[jump_offset]);
    MergeDeadIntoFrameState(next_offset());
    MergeIntoFrameState(block, jump_offset);
  } else {
    MergeDeadIntoFrameState(jump_offset);
  }
}
MarkBytecodeDead()
void v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead () [inline], [private]
Definition at line 765 of file maglev-graph-builder.h.
                          {
    DCHECK_NULL(current_block_);
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << "== Dead ==\n"
                << std::setw(4) << iterator_.current_offset() << " : ";
      interpreter::BytecodeDecoder::Decode(std::cout,
                                           iterator_.current_address());
      std::cout << std::endl;
    }
    // If the current bytecode is a jump to elsewhere, then this jump is
    // also dead and we should make sure to merge it as a dead predecessor.
    interpreter::Bytecode bytecode = iterator_.current_bytecode();
    if (interpreter::Bytecodes::IsForwardJump(bytecode)) {
      // Jumps merge into their target, and conditional jumps also merge into
      // the fallthrough.
      MergeDeadIntoFrameState(iterator_.GetJumpTargetOffset());
      if (interpreter::Bytecodes::IsConditionalJump(bytecode)) {
        MergeDeadIntoFrameState(iterator_.next_offset());
      }
    } else if (bytecode == interpreter::Bytecode::kJumpLoop) {
      // JumpLoop merges into its loop header, which has to be treated
      // specially by the merge.
      if (!in_peeled_iteration() || in_optimistic_peeling_iteration()) {
        MergeDeadLoopIntoFrameState(iterator_.GetJumpTargetOffset());
      }
    } else if (interpreter::Bytecodes::IsSwitch(bytecode)) {
      // Switches merge into their targets, and into the fallthrough.
      for (auto offset : iterator_.GetJumpTableTargetOffsets()) {
        MergeDeadIntoFrameState(offset.target_offset);
      }
      MergeDeadIntoFrameState(iterator_.next_offset());
    } else if (!interpreter::Bytecodes::Returns(bytecode) &&
               !interpreter::Bytecodes::UnconditionallyThrows(bytecode)) {
      // Any other bytecode that doesn't return or throw will merge into the
      // fallthrough.
      MergeDeadIntoFrameState(iterator_.next_offset());
    } else if (interpreter::Bytecodes::Returns(bytecode) && is_inline()) {
      MergeDeadIntoFrameState(inline_exit_offset());
    }
    // TODO(leszeks): We could now continue iterating the bytecode
  }
References bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_address(), current_block_, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), DCHECK_NULL, v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTableTargetOffsets(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), in_optimistic_peeling_iteration(), in_peeled_iteration(), inline_exit_offset(), is_inline(), v8::internal::interpreter::Bytecodes::IsConditionalJump(), v8::internal::interpreter::Bytecodes::IsForwardJump(), v8::internal::interpreter::Bytecodes::IsSwitch(), iterator_, MergeDeadIntoFrameState(), MergeDeadLoopIntoFrameState(), v8::internal::interpreter::BytecodeArrayIterator::next_offset(), v8::internal::interpreter::Bytecodes::Returns(), v8::internal::interpreter::Bytecodes::UnconditionallyThrows(), and v8::internal::v8_flags.
Referenced by VisitSingleBytecode().
MarkNodeDead()
void v8::internal::maglev::MaglevGraphBuilder::MarkNodeDead (Node * node) [inline], [private]
Definition at line 3373 of file maglev-graph-builder.h.
                                       {
    for (int i = 0; i < node->input_count(); ++i) {
      node->input(i).clear();
    }
    node->OverwriteWith(Opcode::kDead);
  }
References v8::internal::maglev::Input::clear(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), and v8::internal::maglev::NodeBase::OverwriteWith().
Referenced by StoreAndCacheContextSlot().
MarkPossibleSideEffect()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::MarkPossibleSideEffect (NodeT * node) [inline], [private]
Definition at line 1821 of file maglev-graph-builder.h.
                                           {
    if constexpr (NodeT::kProperties.can_read() ||
                  NodeT::kProperties.can_deopt() ||
                  NodeT::kProperties.can_throw()) {
      unobserved_context_slot_stores_.clear();
    }
    if constexpr (Node::opcode_of<NodeT> != Opcode::kAllocationBlock &&
                  (NodeT::kProperties.can_deopt() ||
                   NodeT::kProperties.can_throw() ||
                   NodeT::kProperties.can_allocate())) {
      ClearCurrentAllocationBlock();
    }
    // Don't do anything for nodes without side effects.
    if constexpr (!NodeT::kProperties.can_write()) return;
    if (v8_flags.maglev_cse) {
      known_node_aspects().increment_effect_epoch();
    }
    // We only need to clear unstable node aspects on the current builder, not
    // the parent, since we'll anyway copy the known_node_aspects to the parent
    // once we finish the inlined function.
    if constexpr (IsElementsArrayWrite(Node::opcode_of<NodeT>)) {
      node->ClearElementsProperties(known_node_aspects());
      if (is_loop_effect_tracking()) {
        loop_effects_->keys_cleared.insert(
            KnownNodeAspects::LoadedPropertyMapKey::Elements());
      }
    } else if constexpr (!IsSimpleFieldStore(Node::opcode_of<NodeT>) &&
                         !IsTypedArrayStore(Node::opcode_of<NodeT>)) {
      // Don't change known node aspects for simple field stores. The only
      // relevant side effect on these is writes to objects which invalidate
      // loaded properties and context slots, and we invalidate these already as
      // part of emitting the store.
      node->ClearUnstableNodeAspects(known_node_aspects());
      if (is_loop_effect_tracking()) {
        loop_effects_->unstable_aspects_cleared = true;
      }
    }
    // Simple field stores can't possibly change or migrate the map.
    static constexpr bool is_possible_map_change =
        !IsSimpleFieldStore(Node::opcode_of<NodeT>);
    // All user-observable side effects need to clear state that is cached on
    // the builder. This reset has to be propagated up through the parents.
    // TODO(leszeks): What side effects aren't observable? Maybe migrations?
    ResetBuilderCachedState<is_possible_map_change>();
  }
References v8::internal::maglev::IsElementsArrayWrite(), v8::internal::maglev::IsSimpleFieldStore(), v8::internal::maglev::IsTypedArrayStore(), and v8::internal::v8_flags.
Referenced by AttachExtraInfoAndAddToGraph().
max_inline_depth()
int v8::internal::maglev::MaglevGraphBuilder::max_inline_depth () [inline]
Definition at line 456 of file maglev-graph-builder.h.
                         {
    if (is_turbolev()) {
      // This is just to avoid some corner cases, especially since we allow
      // recursive inlining.
      constexpr int kMaxDepthForInlining = 50;
      return kMaxDepthForInlining;
    } else {
      return v8_flags.max_maglev_inline_depth;
    }
  }
References is_turbolev(), v8::internal::compiler::anonymous_namespace{js-inlining.cc}::kMaxDepthForInlining, and v8::internal::v8_flags.
max_inlined_bytecode_size()
int v8::internal::maglev::MaglevGraphBuilder::max_inlined_bytecode_size () [inline]
Definition at line 428 of file maglev-graph-builder.h.
                                  {
    if (is_turbolev()) {
      return v8_flags.max_inlined_bytecode_size;
    } else {
      return v8_flags.max_maglev_inlined_bytecode_size;
    }
  }
References is_turbolev(), and v8::internal::v8_flags.
max_inlined_bytecode_size_cumulative()
int v8::internal::maglev::MaglevGraphBuilder::max_inlined_bytecode_size_cumulative () [inline]
Definition at line 449 of file maglev-graph-builder.h.
                                             {
    if (is_turbolev()) {
      return v8_flags.max_inlined_bytecode_size_cumulative;
    } else {
      return v8_flags.max_maglev_inlined_bytecode_size_cumulative;
    }
  }
References is_turbolev(), and v8::internal::v8_flags.
max_inlined_bytecode_size_small()
int v8::internal::maglev::MaglevGraphBuilder::max_inlined_bytecode_size_small () [inline]
Definition at line 435 of file maglev-graph-builder.h.
                                        {
    if (is_turbolev()) {
      return v8_flags.max_inlined_bytecode_size_small;
    } else {
      return v8_flags.max_maglev_inlined_bytecode_size_small;
    }
  }
References is_turbolev(), and v8::internal::v8_flags.
MergeDeadIntoFrameState()
void v8::internal::maglev::MaglevGraphBuilder::MergeDeadIntoFrameState (int target) [private]
Definition at line 14566 of file maglev-graph-builder.cc.
                                                           {
  // If there already is a frame state, merge.
  if (merge_states_[target]) {
    DCHECK_EQ(merge_states_[target]->predecessor_count(),
              predecessor_count(target));
    merge_states_[target]->MergeDead(*compilation_unit_);
    // If this merge is the last one which kills a loop merge, remove that
    // merge state.
    if (merge_states_[target]->is_unmerged_unreachable_loop()) {
      if (v8_flags.trace_maglev_graph_building) {
        std::cout << "! Killing loop merge state at @" << target << std::endl;
      }
      merge_states_[target] = nullptr;
    }
  }
  // If there is no merge state yet, don't create one, but just reduce the
  // number of possible predecessors to zero.
  DecrementDeadPredecessorAndAccountForPeeling(target);
}
References DCHECK_EQ, and v8::internal::v8_flags.
Referenced by MarkBytecodeDead().
MergeDeadLoopIntoFrameState()
void v8::internal::maglev::MaglevGraphBuilder::MergeDeadLoopIntoFrameState (int target) [private]
Definition at line 14586 of file maglev-graph-builder.cc.
                                                               {
  // Check if the Loop entry is dead already (e.g. an outer loop from OSR).
  if (V8_UNLIKELY(!merge_states_[target]) && predecessor_count(target) == 0) {
    static_assert(kLoopsMustBeEnteredThroughHeader);
    return;
  }
  // If there already is a frame state, merge.
  if (V8_LIKELY(merge_states_[target])) {
    DCHECK_EQ(merge_states_[target]->predecessor_count(),
              predecessor_count(target));
    if (is_loop_effect_tracking_enabled() &&
        !merge_states_[target]->is_unmerged_unreachable_loop()) {
      EndLoopEffects(target);
    }
    merge_states_[target]->MergeDeadLoop(*compilation_unit_);
  }
  // If there is no merge state yet, don't create one, but just reduce the
  // number of possible predecessors to zero.
  DecrementDeadPredecessorAndAccountForPeeling(target);
}
References DCHECK_EQ, V8_LIKELY, and V8_UNLIKELY.
Referenced by MarkBytecodeDead().
MergeIntoFrameState()
void v8::internal::maglev::MaglevGraphBuilder::MergeIntoFrameState (BasicBlock * block, int target) [private]
Definition at line 14545 of file maglev-graph-builder.cc.
                                                         {
  if (merge_states_[target] == nullptr) {
    bool jumping_to_peeled_iteration = bytecode_analysis().IsLoopHeader(target);
    DCHECK_EQ(jumping_to_peeled_iteration,
              loop_headers_to_peel_.Contains(target));
    const compiler::BytecodeLivenessState* liveness = GetInLivenessFor(target);
    if (jumping_to_peeled_iteration) {
      // The peeled iteration is missing the backedge.
      DecrementDeadPredecessorAndAccountForPeeling(target);
    }
    // If there's no target frame state, allocate a new one.
    merge_states_[target] = MergePointInterpreterFrameState::New(
        *compilation_unit_, current_interpreter_frame_, target,
        predecessor_count(target), predecessor, liveness);
  } else {
    // If there already is a frame state, merge.
    merge_states_[target]->Merge(this, current_interpreter_frame_, predecessor);
  }
}
References DCHECK_EQ, and v8::internal::anonymous_namespace{intl-objects.cc}::New().
Referenced by EndPrologue().
MergeIntoInlinedReturnFrameState()
void v8::internal::maglev::MaglevGraphBuilder::MergeIntoInlinedReturnFrameState (BasicBlock * block) [private]
Definition at line 14607 of file maglev-graph-builder.cc.
                             {
  int target = inline_exit_offset();
  if (merge_states_[target] == nullptr) {
    // All returns should have the same liveness, which is that only the
    // accumulator is live.
    const compiler::BytecodeLivenessState* liveness = GetInLiveness();
    DCHECK(liveness->AccumulatorIsLive());
    DCHECK_EQ(liveness->live_value_count(), 1);
    // If there's no target frame state, allocate a new one.
    merge_states_[target] = MergePointInterpreterFrameState::New(
        *compilation_unit_, current_interpreter_frame_, target,
        predecessor_count(target), predecessor, liveness);
  } else {
    // Again, all returns should have the same liveness, so double check this.
    DCHECK(GetInLiveness()->Equals(
        *merge_states_[target]->frame_state().liveness()));
    merge_states_[target]->Merge(this, current_interpreter_frame_, predecessor);
  }
}
References v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), v8::internal::compiler::BytecodeLivenessState::live_value_count(), and v8::internal::anonymous_namespace{intl-objects.cc}::New().
min_inlining_frequency()
float v8::internal::maglev::MaglevGraphBuilder::min_inlining_frequency () [inline]
Definition at line 442 of file maglev-graph-builder.h.
                                 {
    if (is_turbolev()) {
      return v8_flags.min_inlining_frequency;
    } else {
      return v8_flags.min_maglev_inlining_frequency;
    }
  }
References is_turbolev(), and v8::internal::v8_flags.
MinimizeContextChainDepth()
void v8::internal::maglev::MaglevGraphBuilder::MinimizeContextChainDepth (ValueNode ** context, size_t * depth) [private]
Definition at line 170 of file maglev-graph-builder.cc.
                                                                  {
  while (*depth > 0) {
    ValueNode* parent_context = TryGetParentContext(*context);
    if (parent_context == nullptr) return;
    *context = parent_context;
    (*depth)--;
  }
}
References TryGetParentContext().
MoveNodeBetweenRegisters()
void v8::internal::maglev::MaglevGraphBuilder::MoveNodeBetweenRegisters (interpreter::Register src, interpreter::Register dst) [inline], [private]
Definition at line 1511 of file maglev-graph-builder.h.
                                                         {
    // We shouldn't be moving newly created nodes between registers.
    DCHECK(!IsNodeCreatedForThisBytecode(current_interpreter_frame_.get(src)));
    DCHECK_NOT_NULL(current_interpreter_frame_.get(src));
    current_interpreter_frame_.set(dst, current_interpreter_frame_.get(src));
  }
References DCHECK, and DCHECK_NOT_NULL.
need_checkpointed_loop_entry()
bool v8::internal::maglev::MaglevGraphBuilder::need_checkpointed_loop_entry () [inline]
Definition at line 390 of file maglev-graph-builder.h.
                                      {
    return v8_flags.maglev_speculative_hoist_phi_untagging ||
           v8_flags.maglev_licm;
  }
References v8::internal::v8_flags.
Referenced by VisitSingleBytecode().
NegateBranchType()
static BranchType v8::internal::maglev::MaglevGraphBuilder::NegateBranchType (BranchType jump_type) [inline], [static], [private]
Definition at line 2849 of file maglev-graph-builder.h.
                                                                  {
    switch (jump_type) {
      case BranchType::kBranchIfTrue:
        return BranchType::kBranchIfFalse;
      case BranchType::kBranchIfFalse:
        return BranchType::kBranchIfTrue;
    }
  }
NewObjectId()
uint32_t v8::internal::maglev::MaglevGraphBuilder::NewObjectId () [inline]
Definition at line 415 of file maglev-graph-builder.h.
{ return graph_->NewObjectId(); }
References graph_, and v8::internal::maglev::Graph::NewObjectId().
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject().
next_offset()
int v8::internal::maglev::MaglevGraphBuilder::next_offset () const [inline], [private]
Definition at line 1886 of file maglev-graph-builder.h.
                          {
    return iterator_.current_offset() + iterator_.current_bytecode_size();
  }
node_buffer()
ZoneVector<Node*>& v8::internal::maglev::MaglevGraphBuilder::node_buffer () [inline]
Definition at line 413 of file maglev-graph-builder.h.
{ return graph_->node_buffer(); }
References graph_, and v8::internal::maglev::Graph::node_buffer().
Referenced by AddInitializedNodeToGraph(), and v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd().
OsrAnalyzePrequel()
void v8::internal::maglev::MaglevGraphBuilder::OsrAnalyzePrequel ()
Definition at line 14409 of file maglev-graph-builder.cc.
                                           {
  DCHECK_EQ(compilation_unit_->info()->toplevel_compilation_unit(),
            compilation_unit_);
  // TODO(olivf) We might want to start collecting known_node_aspects_ here.
  for (iterator_.SetOffset(0); iterator_.current_offset() != entrypoint_;
       iterator_.Advance()) {
    switch (iterator_.current_bytecode()) {
      case interpreter::Bytecode::kPushContext: {
        graph()->record_scope_info(GetContext(), {});
        // Nothing left to analyze...
        return;
      }
      default:
        continue;
    }
  }
}
References DCHECK_EQ, and graph().
Referenced by Build().
parameter_count()
int v8::internal::maglev::MaglevGraphBuilder::parameter_count () const [inline], [private]
Definition at line 3127 of file maglev-graph-builder.h.
{ return compilation_unit_->parameter_count(); }
Referenced by Build(), and GetArgument().
parameter_count_without_receiver()
int v8::internal::maglev::MaglevGraphBuilder::parameter_count_without_receiver () const [inline], [private]
Definition at line 3128 of file maglev-graph-builder.h.
{ return parameter_count() - 1; }
PeelLoop()
void v8::internal::maglev::MaglevGraphBuilder::PeelLoop ()
Definition at line 14258 of file maglev-graph-builder.cc.
                                  {
  int loop_header = iterator_.current_offset();
  DCHECK(loop_headers_to_peel_.Contains(loop_header));
  DCHECK(!in_peeled_iteration());
  peeled_iteration_count_ = v8_flags.maglev_optimistic_peeled_loops ? 2 : 1;
  any_peeled_loop_ = true;
  allow_loop_peeling_ = false;
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " * Begin loop peeling...." << std::endl;
  }
  while (in_peeled_iteration()) {
    BuildLoopForPeeling();
  }
  // Emit the actual (not peeled) loop if needed.
  if (loop_header == iterator_.current_offset()) {
    BuildLoopForPeeling();
  }
  allow_loop_peeling_ = true;
}
References v8::internal::DCHECK(), and v8::internal::v8_flags.
Referenced by BuildBody().
predecessor_count()
uint32_t v8::internal::maglev::MaglevGraphBuilder::predecessor_count (uint32_t offset) [inline], [private]
Definition at line 3211 of file maglev-graph-builder.h.
                                              {
    DCHECK_LE(offset, bytecode().length());
    DCHECK_IMPLIES(!decremented_predecessor_offsets_.empty(),
                   in_peeled_iteration());
    uint32_t actual = predecessor_count_[offset];
    DCHECK_IMPLIES(merge_states_[offset],
                   merge_states_[offset]->predecessor_count() == actual);
    return actual;
  }
References DCHECK_IMPLIES, DCHECK_LE, and v8::internal::length.
Referenced by BuildMergeStates(), and VisitSingleBytecode().
Print() [1/3]
void v8::internal::maglev::MaglevGraphBuilder::Print (const char * str) [inline], [private]
Definition at line 1429 of file maglev-graph-builder.h.
                              {
    Handle<String> string_handle =
        local_isolate()->factory()->NewStringFromAsciiChecked(
            str, AllocationType::kOld);
    ValueNode* string_node = graph()->GetConstant(MakeRefAssumeMemoryFence(
        broker(), broker()->CanonicalPersistentHandle(string_handle)));
    CHECK(BuildCallRuntime(Runtime::kGlobalPrint, {string_node}).IsDone());
  }
References broker(), CHECK, graph(), and v8::internal::compiler::MakeRefAssumeMemoryFence().
Print() [2/3]
void v8::internal::maglev::MaglevGraphBuilder::Print (const char * str, ValueNode * value) [inline], [private]
Definition at line 1442 of file maglev-graph-builder.h.
                                                {
    Print(str);
    Print(value);
  }
References v8::internal::Print(), and v8::internal::value.
Print() [3/3]
void v8::internal::maglev::MaglevGraphBuilder::Print (ValueNode * value) [inline], [private]
Definition at line 1438 of file maglev-graph-builder.h.
                               {
    CHECK(BuildCallRuntime(Runtime::kDebugPrint, {value}).IsDone());
  }
References CHECK, and v8::internal::value.
PrintVirtualObjects()
void v8::internal::maglev::MaglevGraphBuilder::PrintVirtualObjects () [inline], [private]
Definition at line 821 of file maglev-graph-builder.h.
                             {
    if (!v8_flags.trace_maglev_graph_building) return;
    current_interpreter_frame_.virtual_objects().Print(
        std::cout, "* VOs (Interpreter Frame State): ", graph_labeller());
  }
References current_interpreter_frame_, graph_labeller(), v8::internal::maglev::VirtualObjectList::Print(), v8::internal::v8_flags, and v8::internal::maglev::InterpreterFrameState::virtual_objects().
Referenced by CreateEdgeSplitBlock(), and VisitSingleBytecode().
ProcessMergePoint()
void v8::internal::maglev::MaglevGraphBuilder::ProcessMergePoint (int offset, bool preserve_known_node_aspects) [inline], [private]
Definition at line 640 of file maglev-graph-builder.h.
                                                                       {
    // First copy the merge state to be the current state.
    MergePointInterpreterFrameState& merge_state = *merge_states_[offset];
    current_interpreter_frame_.CopyFrom(*compilation_unit_, merge_state,
                                        preserve_known_node_aspects, zone());
    ProcessMergePointPredecessors(merge_state, jump_targets_[offset]);
  }
References compilation_unit_, v8::internal::maglev::InterpreterFrameState::CopyFrom(), current_interpreter_frame_, jump_targets_, merge_states_, ProcessMergePointPredecessors(), and zone().
Referenced by VisitSingleBytecode().
ProcessMergePointAtExceptionHandlerStart()
void v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointAtExceptionHandlerStart (int offset) [inline], [private]
Definition at line 608 of file maglev-graph-builder.h.
                                                            {
    DCHECK_EQ(current_allocation_block_, nullptr);
    MergePointInterpreterFrameState& merge_state = *merge_states_[offset];
    DCHECK_EQ(merge_state.predecessor_count(), 0);
    // Copy state.
    current_interpreter_frame_.CopyFrom(*compilation_unit_, merge_state);
    // Expressions would have to be explicitly preserved across exceptions.
    // However, at this point we do not know which ones might be used.
    current_interpreter_frame_.known_node_aspects()
        ->ClearAvailableExpressions();
    // Merges aren't simple fallthroughs, so we should reset the checkpoint
    // validity.
    ResetBuilderCachedState();
    // Register exception phis.
    if (has_graph_labeller()) {
      for (Phi* phi : *merge_states_[offset]->phis()) {
        graph_labeller()->RegisterNode(phi, compilation_unit_,
                                       BytecodeOffset(offset),
                                       current_source_position_);
        if (v8_flags.trace_maglev_graph_building) {
          std::cout << " " << phi << " "
                    << PrintNodeLabel(graph_labeller(), phi) << ": "
                    << PrintNode(graph_labeller(), phi) << std::endl;
        }
      }
    }
  }
References v8::internal::maglev::KnownNodeAspects::ClearAvailableExpressions(), compilation_unit_, v8::internal::maglev::InterpreterFrameState::CopyFrom(), current_allocation_block_, current_interpreter_frame_, current_source_position_, DCHECK_EQ, graph_labeller(), has_graph_labeller(), v8::internal::maglev::InterpreterFrameState::known_node_aspects(), merge_states_, v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), ResetBuilderCachedState(), and v8::internal::v8_flags.
Referenced by VisitSingleBytecode().
ProcessMergePointPredecessors()
void v8::internal::maglev::MaglevGraphBuilder::ProcessMergePointPredecessors (MergePointInterpreterFrameState & merge_state, BasicBlockRef & jump_targets) [inline], [private]
Definition at line 650 of file maglev-graph-builder.h.
                                   {
    // TODO(olivf): Support allocation folding across control flow.
    DCHECK_EQ(current_allocation_block_, nullptr);
    // Merges aren't simple fallthroughs, so we should reset state which is
    // cached directly on the builder instead of on the merge states.
    ResetBuilderCachedState();
    if (merge_state.is_loop()) {
      DCHECK_EQ(merge_state.predecessors_so_far(),
                merge_state.predecessor_count() - 1);
    } else {
      DCHECK_EQ(merge_state.predecessors_so_far(),
                merge_state.predecessor_count());
    }
    if (merge_state.predecessor_count() == 1) return;
    // Set up edge-split.
    int predecessor_index = merge_state.predecessor_count() - 1;
    if (merge_state.is_loop()) {
      // For loops, the JumpLoop block hasn't been generated yet, and so isn't
      // in the list of jump targets. IT's the last predecessor, so drop the
      // index by one.
      DCHECK(merge_state.is_unmerged_loop());
      predecessor_index--;
    }
    BasicBlockRef* old_jump_targets = jump_targets.Reset();
    while (old_jump_targets != nullptr) {
      BasicBlock* predecessor = merge_state.predecessor_at(predecessor_index);
      CHECK(predecessor);
      ControlNode* control = predecessor->control_node();
      if (control->Is<ConditionalControlNode>()) {
        // CreateEmptyBlock automatically registers itself with the offset.
        predecessor = CreateEdgeSplitBlock(jump_targets, predecessor);
        // Set the old predecessor's (the conditional block) reference to
        // point to the new empty predecessor block.
        old_jump_targets =
            old_jump_targets->SetToBlockAndReturnNext(predecessor);
        merge_state.set_predecessor_at(predecessor_index, predecessor);
      } else {
        // Re-register the block in the offset's ref list.
        old_jump_targets = old_jump_targets->MoveToRefList(&jump_targets);
      }
      // We only set the predecessor id after splitting critical edges, to make
      // sure the edge split blocks pick up the correct predecessor index.
      predecessor->set_predecessor_id(predecessor_index--);
    }
    DCHECK_EQ(predecessor_index, -1);
    RegisterPhisWithGraphLabeller(merge_state);
  }
References CHECK, v8::internal::maglev::BasicBlock::control_node(), CreateEdgeSplitBlock(), current_allocation_block_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop(), v8::internal::maglev::MergePointInterpreterFrameState::is_unmerged_loop(), v8::internal::maglev::BasicBlockRef::MoveToRefList(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_at(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count(), v8::internal::maglev::MergePointInterpreterFrameState::predecessors_so_far(), RegisterPhisWithGraphLabeller(), v8::internal::maglev::BasicBlockRef::Reset(), ResetBuilderCachedState(), v8::internal::maglev::MergePointInterpreterFrameState::set_predecessor_at(), v8::internal::maglev::BasicBlock::set_predecessor_id(), and v8::internal::maglev::BasicBlockRef::SetToBlockAndReturnNext().
Referenced by ProcessMergePoint().
RecordKnownProperty()
void v8::internal::maglev::MaglevGraphBuilder::RecordKnownProperty (ValueNode * lookup_start_object, KnownNodeAspects::LoadedPropertyMapKey key, ValueNode * value, bool is_const, compiler::AccessMode access_mode) [private]
Definition at line 7351 of file maglev-graph-builder.cc.
                                                                     {
  DCHECK(!value->properties().is_conversion());
  KnownNodeAspects::LoadedPropertyMap& loaded_properties =
      is_const ? known_node_aspects().loaded_constant_properties
               : known_node_aspects().loaded_properties;
  // Try to get loaded_properties[key] if it already exists, otherwise
  // construct loaded_properties[key] = ZoneMap{zone()}.
  auto& props_for_key =
      loaded_properties.try_emplace(key, zone()).first->second;
  if (!is_const && IsAnyStore(access_mode)) {
    if (is_loop_effect_tracking()) {
      loop_effects_->keys_cleared.insert(key);
    }
    // We don't do any aliasing analysis, so stores clobber all other cached
    // loads of a property with that key. We only need to do this for
    // non-constant properties, since constant properties are known not to
    // change and therefore can't be clobbered.
    // TODO(leszeks): Do some light aliasing analysis here, e.g. checking
    // whether there's an intersection of known maps.
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " * Removing all non-constant cached ";
      switch (key.type()) {
        case KnownNodeAspects::LoadedPropertyMapKey::kName:
          std::cout << "properties with name " << *key.name().object();
          break;
        case KnownNodeAspects::LoadedPropertyMapKey::kElements:
          std::cout << "Elements";
          break;
        case KnownNodeAspects::LoadedPropertyMapKey::kTypedArrayLength:
          std::cout << "TypedArray length";
          break;
        case KnownNodeAspects::LoadedPropertyMapKey::kStringLength:
          std::cout << "String length";
          break;
      }
      std::cout << std::endl;
    }
    props_for_key.clear();
  }
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " * Recording " << (is_const ? "constant" : "non-constant")
              << " known property "
              << PrintNodeLabel(graph_labeller(), lookup_start_object) << ": "
              << PrintNode(graph_labeller(), lookup_start_object) << " [";
    switch (key.type()) {
      case KnownNodeAspects::LoadedPropertyMapKey::kName:
        std::cout << *key.name().object();
        break;
      case KnownNodeAspects::LoadedPropertyMapKey::kElements:
        std::cout << "Elements";
        break;
      case KnownNodeAspects::LoadedPropertyMapKey::kTypedArrayLength:
        std::cout << "TypedArray length";
        break;
      case KnownNodeAspects::LoadedPropertyMapKey::kStringLength:
        std::cout << "String length";
        break;
    }
    std::cout << "] = " << PrintNodeLabel(graph_labeller(), value) << ": "
              << PrintNode(graph_labeller(), value) << std::endl;
  }
  if (IsAnyStore(access_mode) && !is_const && is_loop_effect_tracking()) {
    auto updated = props_for_key.emplace(lookup_start_object, value);
    if (updated.second) {
      loop_effects_->objects_written.insert(lookup_start_object);
    } else if (updated.first->second != value) {
      updated.first->second = value;
      loop_effects_->objects_written.insert(lookup_start_object);
    }
  } else {
    props_for_key[lookup_start_object] = value;
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::IsAnyStore(), v8::internal::key, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::v8_flags, and v8::internal::value.
Referenced by BuildLoadJSArrayLength(), TryBuildPropertyLoad(), and TryBuildPropertyStore().
RecordUseReprHint() [1/2]
void v8::internal::maglev::MaglevGraphBuilder::RecordUseReprHint (Phi * phi, UseRepresentation repr) [inline]
Definition at line 400 of file maglev-graph-builder.h.
                                                           {
    RecordUseReprHint(phi, UseRepresentationSet{repr});
  }
References RecordUseReprHint().
RecordUseReprHint() [2/2]
void v8::internal::maglev::MaglevGraphBuilder::RecordUseReprHint (Phi * phi, UseRepresentationSet reprs) [inline]
Definition at line 397 of file maglev-graph-builder.h.
                                                               {
    phi->RecordUseReprHint(reprs);
  }
References v8::internal::maglev::Phi::RecordUseReprHint().
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeLoopValue(), RecordUseReprHint(), and RecordUseReprHintIfPhi().
RecordUseReprHintIfPhi()
void v8::internal::maglev::MaglevGraphBuilder::RecordUseReprHintIfPhi (ValueNode * node, UseRepresentation repr) [inline]
Definition at line 403 of file maglev-graph-builder.h.
                                                                       {
    if (Phi* phi = node->TryCast<Phi>()) {
      RecordUseReprHint(phi, repr);
    }
  }
References RecordUseReprHint(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by CanElideWriteBarrier(), GetFloat64(), GetHoleyFloat64ForToNumber(), GetInt32(), GetInt32ElementIndex(), GetSmiValue(), GetTaggedValue(), and GetTruncatedInt32ForToNumber().
ReduceCall()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::ReduceCall (ValueNode * target_node, CallArguments & args, const compiler::FeedbackSource & feedback_source = compiler::FeedbackSource()) [private]
Definition at line 11718 of file maglev-graph-builder.cc.
                                                   {
  if (compiler::OptionalHeapObjectRef maybe_constant =
          TryGetConstant(target_node)) {
    if (maybe_constant->IsJSFunction()) {
      MaybeReduceResult result = TryReduceCallForTarget(
          target_node, maybe_constant->AsJSFunction(), args, feedback_source);
      RETURN_IF_DONE(result);
    }
  }
  // If the implementation here becomes more complex, we could probably
  // deduplicate the code for FastCreateClosure and CreateClosure by using
  // templates or giving them a shared base class.
  if (FastCreateClosure* fast_create_closure =
          target_node->TryCast<FastCreateClosure>()) {
    MaybeReduceResult result = TryReduceCallForNewClosure(
        fast_create_closure, fast_create_closure->context().node(),
#ifdef V8_ENABLE_LEAPTIERING
        fast_create_closure->feedback_cell().dispatch_handle(),
#endif
        fast_create_closure->shared_function_info(),
        fast_create_closure->feedback_cell(), args, feedback_source);
    RETURN_IF_DONE(result);
  } else if (CreateClosure* create_closure =
                 target_node->TryCast<CreateClosure>()) {
    MaybeReduceResult result = TryReduceCallForNewClosure(
        create_closure, create_closure->context().node(),
#ifdef V8_ENABLE_LEAPTIERING
        create_closure->feedback_cell().dispatch_handle(),
#endif
        create_closure->shared_function_info(), create_closure->feedback_cell(),
        args, feedback_source);
    RETURN_IF_DONE(result);
  }
  // On fallthrough, create a generic call.
  return BuildGenericCall(target_node, Call::TargetType::kAny, args);
}
References v8::base::args, v8::base::internal::result, RETURN_IF_DONE, v8::internal::maglev::NodeBase::TryCast(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
ReduceCallWithArrayLike()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLike (ValueNode * target_node, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11702 of file maglev-graph-builder.cc.
                                                   {
  DCHECK_EQ(args.mode(), CallArguments::kWithArrayLike);
  // TODO(victorgomes): Add the case for JSArrays and Rest parameter.
  if (std::optional<VirtualObject*> arguments_object =
          TryGetNonEscapingArgumentsObject(args.array_like_argument())) {
    RETURN_IF_DONE(ReduceCallWithArrayLikeForArgumentsObject(
        target_node, args, *arguments_object, feedback_source));
  }
  // On fallthrough, create a generic call.
  return BuildGenericCall(target_node, Call::TargetType::kAny, args);
}
References v8::base::args, DCHECK_EQ, and RETURN_IF_DONE.
ReduceCallWithArrayLikeForArgumentsObject()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject (ValueNode * target_node, CallArguments & args, VirtualObject * arguments_object, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11580 of file maglev-graph-builder.cc.
                                                   {
  DCHECK_EQ(args.mode(), CallArguments::kWithArrayLike);
  DCHECK(arguments_object->map().IsJSArgumentsObjectMap() ||
         arguments_object->map().IsJSArrayMap());
  args.PopArrayLikeArgument();
  ValueNode* elements_value =
      arguments_object->get(JSArgumentsObject::kElementsOffset);
  if (elements_value->Is<ArgumentsElements>()) {
    Call::TargetType target_type = Call::TargetType::kAny;
    // TODO(victorgomes): Add JSFunction node type in KNA and use the info here.
    if (compiler::OptionalHeapObjectRef maybe_constant =
            TryGetConstant(target_node)) {
      if (maybe_constant->IsJSFunction()) {
        compiler::SharedFunctionInfoRef shared =
            maybe_constant->AsJSFunction().shared(broker());
        if (!IsClassConstructor(shared.kind())) {
          target_type = Call::TargetType::kJSFunction;
        }
      }
    }
    int start_index = 0;
    if (elements_value->Cast<ArgumentsElements>()->type() ==
        CreateArgumentsType::kRestParameter) {
      start_index =
          elements_value->Cast<ArgumentsElements>()->formal_parameter_count();
    }
    return AddNewCallNode<CallForwardVarargs>(args, GetTaggedValue(target_node),
                                              GetTaggedValue(GetContext()),
                                              start_index, target_type);
  }
  if (elements_value->Is<RootConstant>()) {
    // It is a RootConstant, Elements can only be the empty fixed array.
    DCHECK_EQ(elements_value->Cast<RootConstant>()->index(),
              RootIndex::kEmptyFixedArray);
    CallArguments new_args(ConvertReceiverMode::kAny, {args.receiver()});
    return ReduceCall(target_node, new_args, feedback_source);
  }
  if (Constant* constant_value = elements_value->TryCast<Constant>()) {
    DCHECK(constant_value->object().IsFixedArray());
    compiler::FixedArrayRef elements = constant_value->object().AsFixedArray();
    base::SmallVector<ValueNode*, 8> arg_list;
    DCHECK_NOT_NULL(args.receiver());
    arg_list.push_back(args.receiver());
    for (int i = 0; i < static_cast<int>(args.count()); i++) {
      arg_list.push_back(args[i]);
    }
    for (uint32_t i = 0; i < elements.length(); i++) {
      arg_list.push_back(GetConstant(*elements.TryGet(broker(), i)));
    }
    CallArguments new_args(ConvertReceiverMode::kAny, std::move(arg_list));
    return ReduceCall(target_node, new_args, feedback_source);
  }
  DCHECK(elements_value->Is<InlinedAllocation>());
  InlinedAllocation* allocation = elements_value->Cast<InlinedAllocation>();
  VirtualObject* elements = allocation->object();
  base::SmallVector<ValueNode*, 8> arg_list;
  DCHECK_NOT_NULL(args.receiver());
  arg_list.push_back(args.receiver());
  for (int i = 0; i < static_cast<int>(args.count()); i++) {
    arg_list.push_back(args[i]);
  }
  DCHECK(elements->get(offsetof(FixedArray, length_))->Is<Int32Constant>());
  int length = elements->get(offsetof(FixedArray, length_))
                   ->Cast<Int32Constant>()
                   ->value();
  for (int i = 0; i < length; i++) {
    arg_list.push_back(elements->get(FixedArray::OffsetOfElementAt(i)));
  }
  CallArguments new_args(ConvertReceiverMode::kAny, std::move(arg_list));
  return ReduceCall(target_node, new_args, feedback_source);
}
References v8::base::args, broker(), v8::internal::maglev::NodeBase::Cast(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::maglev::VirtualObject::get(), v8::internal::maglev::RootConstant::index(), v8::internal::maglev::NodeBase::Is(), v8::internal::IsClassConstructor(), v8::internal::kAny, v8::internal::kRestParameter, v8::internal::length, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::maglev::VirtualObject::map(), v8::internal::compiler::FixedArrayRef::object(), v8::internal::maglev::InlinedAllocation::object(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::compiler::FixedArrayRef::TryGet(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), v8::internal::maglev::ArgumentsElements::type(), and v8::internal::value.
register_count()
int v8::internal::maglev::MaglevGraphBuilder::register_count () const [inline], [private]
Definition at line 3129 of file maglev-graph-builder.h.
{ return compilation_unit_->register_count(); }
Referenced by BuildRegisterFrameInitialization().
RegisterPhisWithGraphLabeller()
void v8::internal::maglev::MaglevGraphBuilder::RegisterPhisWithGraphLabeller (MergePointInterpreterFrameState & merge_state) [inline], [private]
Definition at line 704 of file maglev-graph-builder.h.
                                                    {
    if (!has_graph_labeller()) return;
    for (Phi* phi : *merge_state.phis()) {
      graph_labeller()->RegisterNode(phi);
      if (v8_flags.trace_maglev_graph_building) {
        std::cout << " " << phi << " "
                  << PrintNodeLabel(graph_labeller(), phi) << ": "
                  << PrintNode(graph_labeller(), phi) << std::endl;
      }
    }
  }
References graph_labeller(), has_graph_labeller(), v8::internal::maglev::MergePointInterpreterFrameState::phis(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), and v8::internal::v8_flags.
Referenced by ProcessMergePointPredecessors().
ResetBuilderCachedState()
template<bool is_possible_map_change = true>
void v8::internal::maglev::MaglevGraphBuilder::ResetBuilderCachedState () [inline], [private]
Definition at line 1875 of file maglev-graph-builder.h.
                                 {
    latest_checkpointed_frame_.reset();
    // If a map might have changed, then we need to re-check it for for-in.
    // TODO(leszeks): Track this on merge states / known node aspects, rather
    // than on the graph, so that it can survive control flow.
    if constexpr (is_possible_map_change) {
      current_for_in_state.receiver_needs_map_check = true;
    }
  }
Referenced by ProcessMergePointAtExceptionHandlerStart(), and ProcessMergePointPredecessors().
RuntimeFunctionCanThrow()
constexpr bool v8::internal::maglev::MaglevGraphBuilder::RuntimeFunctionCanThrow (Runtime::FunctionId function_id) [inline], [constexpr], [private]
Definition at line 1394 of file maglev-graph-builder.h.
                                                                        {
#define BAILOUT(name, ...) \
  if (function_id == Runtime::k##name) { \
    return true; \
  }
    FOR_EACH_THROWING_INTRINSIC(BAILOUT)
#undef BAILOUT
    return false;
  }
References BAILOUT, and FOR_EACH_THROWING_INTRINSIC.
Select()
template<typename FCond , typename FTrue , typename FFalse >
ValueNode * v8::internal::maglev::MaglevGraphBuilder::Select (FCond cond, FTrue if_true, FFalse if_false) [private]
Definition at line 847 of file maglev-graph-builder.cc.
                                                       {
  MaglevSubGraphBuilder subgraph(this, 1);
  MaglevSubGraphBuilder::Label else_branch(&subgraph, 1);
  BranchBuilder builder(this, &subgraph, BranchType::kBranchIfFalse,
                        &else_branch);
  BranchResult branch_result = cond(builder);
  if (branch_result == BranchResult::kAlwaysTrue) {
    return if_true();
  }
  if (branch_result == BranchResult::kAlwaysFalse) {
    return if_false();
  }
  DCHECK(branch_result == BranchResult::kDefault);
  MaglevSubGraphBuilder::Variable ret_val(0);
  MaglevSubGraphBuilder::Label done(&subgraph, 2, {&ret_val});
  subgraph.set(ret_val, if_true());
  subgraph.Goto(&done);
  subgraph.Bind(&else_branch);
  subgraph.set(ret_val, if_false());
  subgraph.Goto(&done);
  subgraph.Bind(&done);
  return subgraph.get(ret_val);
}
References v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), v8::internal::DCHECK(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::get(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Goto(), kAlwaysFalse, kAlwaysTrue, kBranchIfFalse, kDefault, and v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::set().
Referenced by TryBuildNewConsString(), and TryReduceTypeOf().
SelectReduction()
template<typename FCond , typename FTrue , typename FFalse >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::SelectReduction (FCond cond, FTrue if_true, FFalse if_false) [private]
Definition at line 873 of file maglev-graph-builder.cc.
                                                                       {
  MaglevSubGraphBuilder subgraph(this, 1);
  MaglevSubGraphBuilder::Label else_branch(&subgraph, 1);
  BranchBuilder builder(this, &subgraph, BranchType::kBranchIfFalse,
                        &else_branch);
  BranchResult branch_result = cond(builder);
  if (branch_result == BranchResult::kAlwaysTrue) {
    return if_true();
  }
  if (branch_result == BranchResult::kAlwaysFalse) {
    return if_false();
  }
  DCHECK(branch_result == BranchResult::kDefault);
  MaglevSubGraphBuilder::Variable ret_val(0);
  MaglevSubGraphBuilder::Label done(&subgraph, 2, {&ret_val});
  MaybeReduceResult result_if_true = if_true();
  CHECK(result_if_true.IsDone());
  if (result_if_true.IsDoneWithValue()) {
    subgraph.set(ret_val, result_if_true.value());
  }
  subgraph.GotoOrTrim(&done);
  subgraph.Bind(&else_branch);
  MaybeReduceResult result_if_false = if_false();
  CHECK(result_if_false.IsDone());
  if (result_if_true.IsDoneWithAbort() && result_if_false.IsDoneWithAbort()) {
    return ReduceResult::DoneWithAbort();
  }
  if (result_if_false.IsDoneWithValue()) {
    subgraph.set(ret_val, result_if_false.value());
  }
  subgraph.GotoOrTrim(&done);
  subgraph.Bind(&done);
  return subgraph.get(ret_val);
}
References v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), CHECK, v8::internal::DCHECK(), v8::internal::maglev::ReduceResult::DoneWithAbort(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::get(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoOrTrim(), v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort(), v8::internal::maglev::MaybeReduceResult::IsDoneWithValue(), kAlwaysFalse, kAlwaysTrue, kBranchIfFalse, kDefault, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::set(), and v8::internal::maglev::MaybeReduceResult::value().
set_current_block()
void v8::internal::maglev::MaglevGraphBuilder::set_current_block (BasicBlock * block) [inline]
Definition at line 409 of file maglev-graph-builder.h.
{ current_block_ = block; }
References current_block_.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
SetAccumulator()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::SetAccumulator (NodeT * node) [inline], [private]
Definition at line 1719 of file maglev-graph-builder.h.
                                   {
    // Accumulator stores are equivalent to stores to the virtual accumulator
    // register.
    StoreRegister(interpreter::Register::virtual_accumulator(), node);
  }
Referenced by BuildFloat64BinaryOperationNodeForToNumber(), BuildFloat64BinarySmiOperationNodeForToNumber(), BuildFloat64UnaryOperationNodeForToNumber(), BuildGenericBinaryOperationNode(), BuildGenericBinarySmiOperationNode(), BuildGenericUnaryOperationNode(), BuildInt32BinaryOperationNode(), BuildInt32BinarySmiOperationNode(), BuildInt32UnaryOperationNode(), BuildStringConcat(), BuildTruncatingInt32BinaryOperationNodeForToNumber(), BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), BuildTruncatingInt32BitwiseNotForToNumber(), TryReduceCompareEqualAgainstConstant(), TrySpecializeLoadContextSlotToFunctionContext(), and VisitCompareOperation().
SetAccumulatorInBranch()
void v8::internal::maglev::MaglevGraphBuilder::SetAccumulatorInBranch (ValueNode * value) [inline], [private]
Definition at line 1763 of file maglev-graph-builder.h.
                                                {
    DCHECK_IMPLIES(value->properties().can_lazy_deopt(),
                   !IsNodeCreatedForThisBytecode(value));
    current_interpreter_frame_.set(interpreter::Register::virtual_accumulator(),
                                   value);
  }
References DCHECK_IMPLIES, and v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::StartFallthroughBlock().
SetArgument()
void v8::internal::maglev::MaglevGraphBuilder::SetArgument (int i, ValueNode * value)
Definition at line 1064 of file maglev-graph-builder.cc.
                                                            {
  interpreter::Register reg = interpreter::Register::FromParameterIndex(i);
  current_interpreter_frame_.set(reg, value);
}
References current_interpreter_frame_, v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::maglev::InterpreterFrameState::set(), and v8::internal::value.
Referenced by Build().
SetContext()
void v8::internal::maglev::MaglevGraphBuilder::SetContext (ValueNode * context) [inline], [private]
Definition at line 1462 of file maglev-graph-builder.h.
                                      {
    current_interpreter_frame_.set(interpreter::Register::current_context(),
                                   context);
  }
SetKnownValue()
void v8::internal::maglev::MaglevGraphBuilder::SetKnownValue (ValueNode * node, compiler::ObjectRef constant, NodeType new_node_type) [private]
Definition at line 4508 of file maglev-graph-builder.cc.
                                                               {
  DCHECK(!node->Is<Constant>());
  DCHECK(!node->Is<RootConstant>());
  NodeInfo* known_info = GetOrCreateInfoFor(node);
  // ref type should be compatible with type.
  DCHECK(NodeTypeIs(StaticTypeForConstant(broker(), ref), new_node_type));
  if (ref.IsHeapObject()) {
    DCHECK(IsInstanceOfNodeType(ref.AsHeapObject().map(broker()),
                                known_info->type(), broker()));
  } else {
    DCHECK(!NodeTypeIs(known_info->type(), NodeType::kAnyHeapObject));
  }
  known_info->IntersectType(new_node_type);
  known_info->alternative().set_checked_value(GetConstant(ref));
}
References v8::internal::maglev::NodeInfo::alternative(), broker(), v8::internal::DCHECK(), GetConstant(), GetOrCreateInfoFor(), v8::internal::maglev::NodeInfo::IntersectType(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::IsInstanceOfNodeType(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::StaticTypeForConstant(), and v8::internal::maglev::NodeInfo::type().
SetNodeInputs()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::SetNodeInputs (NodeT * node, std::initializer_list< ValueNode * > inputs) [inline], [private]
Definition at line 1953 of file maglev-graph-builder.h.
                                                                          {
    // Nodes with zero input count don't have kInputTypes defined.
    if constexpr (NodeT::kInputCount > 0) {
      constexpr UseReprHintRecording hint = ShouldRecordUseReprHint<NodeT>();
      int i = 0;
      for (ValueNode* input : inputs) {
        DCHECK_NOT_NULL(input);
        node->set_input(i, ConvertInputTo<hint>(input, NodeT::kInputTypes[i]));
        i++;
      }
    }
  }
References DCHECK_NOT_NULL.
Referenced by AddNewNode().
ShouldEagerInlineCall()
bool v8::internal::maglev::MaglevGraphBuilder::ShouldEagerInlineCall (compiler::SharedFunctionInfoRef shared) [private]
Definition at line 8494 of file maglev-graph-builder.cc.
                                          {
  compiler::BytecodeArrayRef bytecode = shared.GetBytecodeArray(broker());
  if (bytecode.length() < max_inlined_bytecode_size_small()) {
    TRACE_INLINING(" greedy inlining "
                   << shared << ": small function, skipping max-depth");
    return true;
  }
  return false;
}
References broker(), v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::compiler::BytecodeArrayRef::length(), and TRACE_INLINING.
ShouldEmitInterruptBudgetChecks()
bool v8::internal::maglev::MaglevGraphBuilder::ShouldEmitInterruptBudgetChecks () [inline], [private]
Definition at line 559 of file maglev-graph-builder.h.
                                         {
    if (is_inline()) {
      return false;
    }
    if (is_turbolev()) {
      // As the top-tier compiler, Turboshaft doesn't need interrupt budget
      // checks.
      return false;
    }
    return v8_flags.force_emit_interrupt_budget_checks || v8_flags.turbofan;
  }
References is_inline(), is_turbolev(), and v8::internal::v8_flags.
ShouldEmitOsrInterruptBudgetChecks()
bool v8::internal::maglev::MaglevGraphBuilder::ShouldEmitOsrInterruptBudgetChecks () [inline], [private]
Definition at line 570 of file maglev-graph-builder.h.
                                            {
    if (!v8_flags.turbofan || !v8_flags.use_osr || !v8_flags.osr_from_maglev)
      return false;
    if (!graph_->is_osr() && !v8_flags.always_osr_from_maglev) {
      return false;
    }
    // TODO(olivf) OSR from maglev requires lazy recompilation (see
    // CompileOptimizedOSRFromMaglev for details). Without this we end up in
    // deopt loops, e.g., in chromium content_unittests.
    if (!OptimizingCompileDispatcher::Enabled()) {
      return false;
    }
    // TODO(olivf) OSR'ing from inlined loops is something we might want, but
    // can't with our current osr-from-maglev implementation. The reason is that
    // we OSR up by first going down to the interpreter. For inlined loops this
    // means we would deoptimize to the caller and then probably end up in the
    // same maglev osr code again, before reaching the turbofan OSR code in the
    // callee. The solution is to support osr from maglev without
    // deoptimization.
    return !is_inline();
  }
References v8::internal::OptimizingCompileDispatcher::Enabled(), graph_, is_inline(), v8::internal::maglev::Graph::is_osr(), and v8::internal::v8_flags.
ShouldRecordUseReprHint()
template<typename NodeT >
static constexpr UseReprHintRecording v8::internal::maglev::MaglevGraphBuilder::ShouldRecordUseReprHint () [inline], [static], [constexpr], [private]
Definition at line 1940 of file maglev-graph-builder.h.
                                                                  {
    // We do not record a Tagged use on Return, since they are never on the hot
    // path, and will lead to a maximum of one additional Tagging operation in
    // the worst case. This allows loop accumulator to be untagged even if they
    // are later returned.
    if constexpr (std::is_same_v<NodeT, Return>) {
      return UseReprHintRecording::kDoNotRecord;
    } else {
      return UseReprHintRecording::kRecord;
    }
  }
StartFallthroughBlock()
void v8::internal::maglev::MaglevGraphBuilder::StartFallthroughBlock (int next_block_offset, BasicBlock * predecessor) [inline], [private]
Definition at line 2017 of file maglev-graph-builder.h.
                                                                             {
    // Start a new block for the fallthrough path, unless it's a merge point, in
    // which case we merge our state into it. That merge-point could also be a
    // loop header, in which case the merge state might not exist yet (if the
    // only predecessors are this path and the JumpLoop).
    DCHECK_NULL(current_block_);
    if (predecessor_count(next_block_offset) == 1) {
      if (v8_flags.trace_maglev_graph_building) {
        std::cout << "== New block (single fallthrough) at "
                  << *compilation_unit_->shared_function_info().object()
                  << "==" << std::endl;
        PrintVirtualObjects();
      }
      StartNewBlock(next_block_offset, predecessor);
    } else {
      MergeIntoFrameState(predecessor, next_block_offset);
    }
  }
References DCHECK_NULL, and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BranchBuilder::Build().
StartNewBlock() [1/2]
void v8::internal::maglev::MaglevGraphBuilder::StartNewBlock (BasicBlock * predecessor, MergePointInterpreterFrameState * merge_state, BasicBlockRef & refs_to_block) [inline], [private]
Definition at line 1906 of file maglev-graph-builder.h.
                                                   {
    DCHECK_NULL(current_block_);
    current_block_ = zone()->New<BasicBlock>(merge_state, zone());
    if (merge_state == nullptr) {
      DCHECK_NOT_NULL(predecessor);
      current_block_->set_predecessor(predecessor);
    } else {
      merge_state->InitializeWithBasicBlock(current_block_);
    }
    refs_to_block.Bind(current_block_);
  }
References v8::internal::maglev::BasicBlockRef::Bind(), DCHECK_NOT_NULL, DCHECK_NULL, and v8::internal::maglev::MergePointInterpreterFrameState::InitializeWithBasicBlock().
StartNewBlock() [2/2]
void v8::internal::maglev::MaglevGraphBuilder::StartNewBlock (int offset, BasicBlock * predecessor) [inline], [private]
Definition at line 1902 of file maglev-graph-builder.h.
                                                          {
    StartNewBlock(predecessor, merge_states_[offset], jump_targets_[offset]);
  }
Referenced by VisitSingleBytecode().
StartPrologue()
void v8::internal::maglev::MaglevGraphBuilder::StartPrologue ()
Definition at line 1047 of file maglev-graph-builder.cc.
                                       {
  current_block_ = zone()->New<BasicBlock>(nullptr, zone());
}
References current_block_, v8::internal::Zone::New(), and zone().
Referenced by Build().
StoreAndCacheContextSlot()
ReduceResult v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot (ValueNode * context, int index, ValueNode * value, ContextMode context_mode) [private]
Definition at line 3692 of file maglev-graph-builder.cc.
                                                                               {
  int offset = Context::OffsetOfElementAt(index);
  DCHECK_EQ(
      known_node_aspects().loaded_context_constants.count({context, offset}),
      0);
  Node* store = nullptr;
  if ((v8_flags.script_context_cells || v8_flags.function_context_cells) &&
      context_mode == ContextMode::kHasContextCells) {
    MaybeReduceResult result =
        TrySpecializeStoreContextSlot(context, index, value, &store);
    RETURN_IF_ABORT(result);
    if (!store && result.IsDone()) {
      // If we didn't need to emit any store, there is nothing to cache.
      return result.Checked();
    }
  }
  if (!store) {
    store = BuildStoreTaggedField(context, value, offset,
                                  StoreTaggedMode::kDefault);
  }
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " * Recording context slot store "
              << PrintNodeLabel(graph_labeller(), context) << "[" << offset
              << "]: " << PrintNode(graph_labeller(), value) << std::endl;
  }
  KnownNodeAspects::LoadedContextSlots& loaded_context_slots =
      known_node_aspects().loaded_context_slots;
  if (!loaded_context_slots.empty()) {
    known_node_aspects().UpdateMayHaveAliasingContexts(
        broker(), local_isolate(), context);
  }
  if (known_node_aspects().may_have_aliasing_contexts() ==
      KnownNodeAspects::ContextSlotLoadsAlias::kYes) {
    compiler::OptionalScopeInfoRef scope_info =
        graph()->TryGetScopeInfo(context);
    for (auto& cache : loaded_context_slots) {
      if (std::get<int>(cache.first) == offset &&
          std::get<ValueNode*>(cache.first) != context) {
        if (ContextMayAlias(std::get<ValueNode*>(cache.first), scope_info) &&
            cache.second != value) {
          if (v8_flags.trace_maglev_graph_building) {
            std::cout << " * Clearing probably aliasing value "
                      << PrintNodeLabel(graph_labeller(),
                                        std::get<ValueNode*>(cache.first))
                      << "[" << offset
                      << "]: " << PrintNode(graph_labeller(), value)
                      << std::endl;
          }
          cache.second = nullptr;
          if (is_loop_effect_tracking()) {
            loop_effects_->context_slot_written.insert(cache.first);
            loop_effects_->may_have_aliasing_contexts = true;
          }
        }
      }
    }
  }
  KnownNodeAspects::LoadedContextSlotsKey key{context, offset};
  auto updated = loaded_context_slots.emplace(key, value);
  if (updated.second) {
    if (is_loop_effect_tracking()) {
      loop_effects_->context_slot_written.insert(key);
    }
    unobserved_context_slot_stores_[key] = store;
  } else {
    if (updated.first->second != value) {
      updated.first->second = value;
      if (is_loop_effect_tracking()) {
        loop_effects_->context_slot_written.insert(key);
      }
    }
    if (known_node_aspects().may_have_aliasing_contexts() !=
        KnownNodeAspects::ContextSlotLoadsAlias::kYes) {
      auto last_store = unobserved_context_slot_stores_.find(key);
      if (last_store != unobserved_context_slot_stores_.end()) {
        MarkNodeDead(last_store->second);
        last_store->second = store;
      } else {
        unobserved_context_slot_stores_[key] = store;
      }
    }
  }
  return ReduceResult::Done();
}
References broker(), BuildStoreTaggedField(), v8::internal::maglev::LoopEffects::context_slot_written, ContextMayAlias(), DCHECK_EQ, v8::internal::maglev::ReduceResult::Done(), graph(), graph_labeller(), v8::internal::index, is_loop_effect_tracking(), v8::internal::maglev::kDefault, v8::internal::key, v8::internal::kHasContextCells, known_node_aspects(), v8::internal::maglev::KnownNodeAspects::kYes, v8::internal::maglev::KnownNodeAspects::loaded_context_slots, local_isolate(), loop_effects_, MarkNodeDead(), v8::internal::maglev::LoopEffects::may_have_aliasing_contexts, v8::internal::Context::OffsetOfElementAt(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::base::internal::result, RETURN_IF_ABORT, store(), v8::internal::maglev::Graph::TryGetScopeInfo(), TrySpecializeStoreContextSlot(), unobserved_context_slot_stores_, v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts(), v8::internal::v8_flags, and v8::internal::value.
Referenced by BuildStoreContextSlot(), and TryBuildScriptContextStore().
StoreRegister()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::StoreRegister (interpreter::Register target, NodeT * value) [inline], [private]
Definition at line 1751 of file maglev-graph-builder.h.
                                                               {
    static_assert(std::is_base_of_v<ValueNode, NodeT>);
    DCHECK(HasOutputRegister(target));
    current_interpreter_frame_.set(target, value);
    // Make sure the lazy deopt info of this value, if any, is registered as
    // mutating this register.
    DCHECK_IMPLIES(value->properties().can_lazy_deopt() &&
                       IsNodeCreatedForThisBytecode(value),
                   value->lazy_deopt_info()->IsResultRegister(target));
  }
References DCHECK, DCHECK_IMPLIES, and v8::internal::value.
StoreRegisterPair()
template<typename NodeT >
void v8::internal::maglev::MaglevGraphBuilder::StoreRegisterPair (std::pair< interpreter::Register, interpreter::Register > target, NodeT * value) [inline], [private]
Definition at line 1771 of file maglev-graph-builder.h.
                    {
    const interpreter::Register target0 = target.first;
    const interpreter::Register target1 = target.second;
    DCHECK_EQ(interpreter::Register(target0.index() + 1), target1);
    DCHECK_EQ(value->ReturnCount(), 2);
    if (!v8_flags.maglev_cse) {
      // TODO(olivf): CSE might deduplicate this value and the one below.
      DCHECK_NE(0, new_nodes_.count(value));
    }
    DCHECK(HasOutputRegister(target0));
    current_interpreter_frame_.set(target0, value);
    ValueNode* second_value = GetSecondValue(value);
    if (!v8_flags.maglev_cse) {
      DCHECK_NE(0, new_nodes_.count(second_value));
    }
    DCHECK(HasOutputRegister(target1));
    current_interpreter_frame_.set(target1, second_value);
    // Make sure the lazy deopt info of this value, if any, is registered as
    // mutating these registers.
    DCHECK_IMPLIES(value->properties().can_lazy_deopt() &&
                       IsNodeCreatedForThisBytecode(value),
                   value->lazy_deopt_info()->IsResultRegister(target0));
    DCHECK_IMPLIES(value->properties().can_lazy_deopt() &&
                       IsNodeCreatedForThisBytecode(value),
                   value->lazy_deopt_info()->IsResultRegister(target1));
  }
References DCHECK, DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::interpreter::Register::index(), v8::internal::v8_flags, and v8::internal::value.
StringLengthStaticLowerBound()
size_t v8::internal::maglev::MaglevGraphBuilder::StringLengthStaticLowerBound (ValueNode * string, int max_depth = 2) [private]
Definition at line 2782 of file maglev-graph-builder.cc.
                                                                       {
  if (auto maybe_constant = string->TryGetConstant(broker())) {
    if (maybe_constant->IsString()) {
      return maybe_constant->AsString().length();
    }
  }
  switch (string->opcode()) {
    case Opcode::kNumberToString:
      return 1;
    case Opcode::kInlinedAllocation:
      // TODO(olivf): Add a NodeType::kConsString instead of this check.
      if (string->Cast<InlinedAllocation>()->object()->type() ==
          VirtualObject::kConsString) {
        return ConsString::kMinLength;
      }
      break;
    case Opcode::kStringConcat:
      if (max_depth == 0) return 0;
      return StringLengthStaticLowerBound(string->input(0).node(),
                                          max_depth - 1) +
             StringLengthStaticLowerBound(string->input(1).node(),
                                          max_depth - 1);
    case Opcode::kPhi: {
      // For the builder pattern where the inputs are cons strings, we will see
      // a phi from the Select that compares against the empty string. We
      // can refine the min_length by checking the phi strings. This might
      // help us elide the Select.
      if (max_depth == 0) return 0;
      auto phi = string->Cast<Phi>();
      if (phi->input_count() == 0 ||
          (phi->is_loop_phi() && phi->is_unmerged_loop_phi())) {
        return 0;
      }
      size_t overall_min_length =
          StringLengthStaticLowerBound(phi->input(0).node(), max_depth - 1);
      for (int i = 1; i < phi->input_count(); ++i) {
        size_t min =
            StringLengthStaticLowerBound(phi->input(i).node(), max_depth - 1);
        if (min < overall_min_length) {
          overall_min_length = min;
        }
      }
      return overall_min_length;
    }
    default:
      break;
  }
  return 0;
}
References broker(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::VirtualObject::kConsString, v8::internal::ConsString::kMinLength, v8::internal::maglev::InlinedAllocation::object(), v8::internal::string, and v8::internal::maglev::VirtualObject::type().
Referenced by TryBuildNewConsString().
TargetIsCurrentCompilingUnit()
bool v8::internal::maglev::MaglevGraphBuilder::TargetIsCurrentCompilingUnit (compiler::JSFunctionRef target) [private]
Definition at line 10971 of file maglev-graph-builder.cc.
                                  {
  if (compilation_unit_->info()->specialize_to_function_context()) {
    return target.object().equals(
        compilation_unit_->info()->toplevel_function());
  }
  return target.object()->shared() ==
         compilation_unit_->info()->toplevel_function()->shared();
}
References v8::internal::compiler::JSFunctionRef::object().
TopLevelFunctionPassMaglevPrintFilter()
bool v8::internal::maglev::MaglevGraphBuilder::TopLevelFunctionPassMaglevPrintFilter ()
Definition at line 8487 of file maglev-graph-builder.cc.
                                                               {
  return compilation_unit_->GetTopLevelCompilationUnit()
      ->shared_function_info()
      .object()
      ->PassesFilter(v8_flags.maglev_print_filter);
}
References v8::internal::v8_flags.
TryBuildAndAllocateJSGeneratorObject()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject (ValueNode * closure, ValueNode * receiver) [private]
Definition at line 12136 of file maglev-graph-builder.cc.
                                             {
  compiler::OptionalHeapObjectRef maybe_constant = TryGetConstant(closure);
  if (!maybe_constant.has_value()) return {};
  if (!maybe_constant->IsJSFunction()) return {};
  compiler::JSFunctionRef function = maybe_constant->AsJSFunction();
  if (!function.has_initial_map(broker())) return {};
  // Create the register file.
  compiler::SharedFunctionInfoRef shared = function.shared(broker());
  DCHECK(shared.HasBytecodeArray());
  compiler::BytecodeArrayRef bytecode_array = shared.GetBytecodeArray(broker());
  int parameter_count_no_receiver = bytecode_array.parameter_count() - 1;
  int length = parameter_count_no_receiver + bytecode_array.register_count();
  if (FixedArray::SizeFor(length) > kMaxRegularHeapObjectSize) {
    return {};
  }
  auto undefined = GetRootConstant(RootIndex::kUndefinedValue);
  VirtualObject* register_file =
      CreateFixedArray(broker()->fixed_array_map(), length);
  for (int i = 0; i < length; i++) {
    register_file->set(FixedArray::OffsetOfElementAt(i), undefined);
  }
  // Create the JS[Async]GeneratorObject instance.
  compiler::SlackTrackingPrediction slack_tracking_prediction =
      broker()->dependencies()->DependOnInitialMapInstanceSizePrediction(
          function);
  compiler::MapRef initial_map = function.initial_map(broker());
  VirtualObject* generator = CreateJSGeneratorObject(
      initial_map, slack_tracking_prediction.instance_size(), GetContext(),
      closure, receiver, register_file);
  // Handle in-object properties.
  for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
       i++) {
    generator->set(initial_map.GetInObjectPropertyOffset(i), undefined);
  }
  generator->ClearSlots(
      initial_map.GetInObjectPropertyOffset(
          slack_tracking_prediction.inobject_property_count()),
      GetRootConstant(RootIndex::kOnePointerFillerMap));
  ValueNode* allocation =
      BuildInlinedAllocation(generator, AllocationType::kYoung);
  return allocation;
}
References broker(), v8::internal::maglev::VirtualObject::ClearSlots(), v8::internal::DCHECK(), v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::compiler::initial_map, v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::kMaxRegularHeapObjectSize, v8::internal::kYoung, v8::internal::length, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::compiler::BytecodeArrayRef::parameter_count(), v8::internal::compiler::BytecodeArrayRef::register_count(), v8::internal::maglev::VirtualObject::set(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), and v8::internal::undefined.
TryBuildCallKnownApiFunction()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownApiFunction (compiler::JSFunctionRef function, compiler::SharedFunctionInfoRef shared, CallArguments & args) [private]
Definition at line 11025 of file maglev-graph-builder.cc.
                         {
  compiler::OptionalFunctionTemplateInfoRef maybe_function_template_info =
      shared.function_template_info(broker());
  if (!maybe_function_template_info.has_value()) {
    // Not an Api function.
    return {};
  }
  // See if we can optimize this API call.
  compiler::FunctionTemplateInfoRef function_template_info =
      maybe_function_template_info.value();
  compiler::HolderLookupResult api_holder;
  if (function_template_info.accept_any_receiver() &&
      function_template_info.is_signature_undefined(broker())) {
    // We might be able to optimize the API call depending on the
    // {function_template_info}.
    // If the API function accepts any kind of {receiver}, we only need to
    // ensure that the {receiver} is actually a JSReceiver at this point,
    // and also pass that as the {holder}. There are two independent bits
    // here:
    //
    // a. When the "accept any receiver" bit is set, it means we don't
    // need to perform access checks, even if the {receiver}'s map
    // has the "needs access check" bit set.
    // b. When the {function_template_info} has no signature, we don't
    // need to do the compatible receiver check, since all receivers
    // are considered compatible at that point, and the {receiver}
    // will be pass as the {holder}.
    api_holder =
        compiler::HolderLookupResult{CallOptimization::kHolderIsReceiver};
  } else {
    // Try to infer API holder from the known aspects of the {receiver}.
    api_holder =
        TryInferApiHolderValue(function_template_info, args.receiver());
  }
  switch (api_holder.lookup) {
    case CallOptimization::kHolderIsReceiver:
    case CallOptimization::kHolderFound:
      return TryReduceCallForApiFunction(function_template_info, shared, args);
    case CallOptimization::kHolderNotFound:
      break;
  }
  // We don't have enough information to eliminate the access check
  // and/or the compatible receiver check, so use the generic builtin
  // that does those checks dynamically. This is still significantly
  // faster than the generic call sequence.
  Builtin builtin_name;
  // TODO(ishell): create no-profiling versions of kCallFunctionTemplate
  // builtins and use them here based on DependOnNoProfilingProtector()
  // dependency state.
  if (function_template_info.accept_any_receiver()) {
    DCHECK(!function_template_info.is_signature_undefined(broker()));
    builtin_name = Builtin::kCallFunctionTemplate_CheckCompatibleReceiver;
  } else if (function_template_info.is_signature_undefined(broker())) {
    builtin_name = Builtin::kCallFunctionTemplate_CheckAccess;
  } else {
    builtin_name =
        Builtin::kCallFunctionTemplate_CheckAccessAndCompatibleReceiver;
  }
  // The CallFunctionTemplate builtin requires the {receiver} to be
  // an actual JSReceiver, so make sure we do the proper conversion
  // first if necessary.
  ValueNode* receiver = GetConvertReceiver(shared, args);
  int kContext = 1;
  int kFunctionTemplateInfo = 1;
  int kArgc = 1;
  return AddNewNode<CallBuiltin>(
      kFunctionTemplateInfo + kArgc + kContext + args.count_with_receiver(),
      [&](CallBuiltin* call_builtin) {
        int arg_index = 0;
        call_builtin->set_arg(arg_index++, GetConstant(function_template_info));
        call_builtin->set_arg(
            arg_index++,
            GetInt32Constant(JSParameterCount(static_cast<int>(args.count()))));
        call_builtin->set_arg(arg_index++, GetTaggedValue(receiver));
        for (int i = 0; i < static_cast<int>(args.count()); i++) {
          call_builtin->set_arg(arg_index++, GetTaggedValue(args[i]));
        }
      },
      builtin_name, GetTaggedValue(GetContext()));
}
References v8::internal::compiler::FunctionTemplateInfoRef::accept_any_receiver(), v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::compiler::SharedFunctionInfoRef::function_template_info(), v8::internal::compiler::FunctionTemplateInfoRef::is_signature_undefined(), v8::internal::CallOptimization::kHolderFound, v8::internal::CallOptimization::kHolderIsReceiver, v8::internal::CallOptimization::kHolderNotFound, and v8::internal::compiler::HolderLookupResult::lookup.
TryBuildCallKnownJSFunction() [1/2]
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownJSFunction (compiler::JSFunctionRef function, ValueNode * new_target, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11116 of file maglev-graph-builder.cc.
                                                                        {
  // Don't inline CallFunction stub across native contexts.
  if (function.native_context(broker()) != broker()->target_native_context()) {
    return {};
  }
  compiler::SharedFunctionInfoRef shared = function.shared(broker());
  RETURN_IF_DONE(TryBuildCallKnownApiFunction(function, shared, args));
  ValueNode* closure = GetConstant(function);
  compiler::ContextRef context = function.context(broker());
  ValueNode* context_node = GetConstant(context);
  MaybeReduceResult res;
  if (MaglevIsTopTier() && TargetIsCurrentCompilingUnit(function) &&
      !graph_->is_osr()) {
    DCHECK(!shared.HasBuiltinId());
    res = BuildCallSelf(context_node, closure, new_target, shared, args);
  } else {
    res = TryBuildCallKnownJSFunction(
        context_node, closure, new_target,
#ifdef V8_ENABLE_LEAPTIERING
        function.dispatch_handle(),
#endif
        shared, function.raw_feedback_cell(broker()), args, feedback_source);
  }
  return res;
}
References v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::native_context, v8::internal::raw_feedback_cell, and RETURN_IF_DONE.
TryBuildCallKnownJSFunction() [2/2]
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownJSFunction (ValueNode * context, ValueNode * function, ValueNode * new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11196 of file maglev-graph-builder.cc.
                                                   {
  if (v8_flags.maglev_inlining) {
    RETURN_IF_DONE(TryBuildInlineCall(context, function, new_target,
#ifdef V8_ENABLE_LEAPTIERING
                                      dispatch_handle,
#endif
                                      shared, feedback_cell, args,
                                      feedback_source));
  }
  return BuildCallKnownJSFunction(context, function, new_target,
#ifdef V8_ENABLE_LEAPTIERING
                                  dispatch_handle,
#endif
                                  shared, feedback_cell, args, feedback_source);
}
References v8::base::args, RETURN_IF_DONE, and v8::internal::v8_flags.
TryBuildCheckInt32Condition()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildCheckInt32Condition (ValueNode * lhs, ValueNode * rhs, AssertCondition condition, DeoptimizeReason reason, bool allow_unconditional_deopt = true) [private]
Definition at line 6266 of file maglev-graph-builder.cc.
                                                             {
  auto lhs_const = TryGetInt32Constant(lhs);
  if (lhs_const) {
    auto rhs_const = TryGetInt32Constant(rhs);
    if (rhs_const) {
      if (CheckConditionIn32(lhs_const.value(), rhs_const.value(), condition)) {
        return ReduceResult::Done();
      }
      if (allow_unconditional_deopt) {
        return EmitUnconditionalDeopt(reason);
      }
    }
  }
  AddNewNode<CheckInt32Condition>({lhs, rhs}, condition, reason);
  return ReduceResult::Done();
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CheckConditionIn32().
Referenced by TryBuildNewConsString().
TryBuildElementAccess()
template<typename GenericAccessFunc >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess (ValueNode * object, ValueNode * index, compiler::ElementAccessFeedback const & feedback, compiler::FeedbackSource const & feedback_source, GenericAccessFunc && build_generic_access) [private]
Definition at line 6772 of file maglev-graph-builder.cc.
                                              {
  const compiler::KeyedAccessMode& keyed_mode = feedback.keyed_mode();
  // Check for the megamorphic case.
  if (feedback.transition_groups().empty()) {
    if (keyed_mode.access_mode() == compiler::AccessMode::kLoad) {
      return BuildCallBuiltin<Builtin::kKeyedLoadIC_Megamorphic>(
          {GetTaggedValue(object), GetTaggedValue(index_object)},
          feedback_source);
    } else if (keyed_mode.access_mode() == compiler::AccessMode::kStore) {
      return BuildCallBuiltin<Builtin::kKeyedStoreIC_Megamorphic>(
          {GetTaggedValue(object), GetTaggedValue(index_object),
           GetTaggedValue(GetAccumulator())},
          feedback_source);
    }
    return {};
  }
  NodeInfo* object_info = known_node_aspects().TryGetInfoFor(object);
  compiler::ElementAccessFeedback refined_feedback =
      object_info && object_info->possible_maps_are_known()
          ? feedback.Refine(broker(), object_info->possible_maps())
          : feedback;
  if (refined_feedback.HasOnlyStringMaps(broker())) {
    return TryBuildElementAccessOnString(object, index_object, refined_feedback,
                                         keyed_mode);
  }
  compiler::AccessInfoFactory access_info_factory(broker(), zone());
  ZoneVector<compiler::ElementAccessInfo> access_infos(zone());
  if (!access_info_factory.ComputeElementAccessInfos(refined_feedback,
                                                     &access_infos) ||
      access_infos.empty()) {
    return {};
  }
  // TODO(leszeks): This is copied without changes from TurboFan's native
  // context specialization. We should figure out a way to share this code.
  //
  // For holey stores or growing stores, we need to check that the prototype
  // chain contains no setters for elements, and we need to guard those checks
  // via code dependencies on the relevant prototype maps.
  if (keyed_mode.access_mode() == compiler::AccessMode::kStore) {
    // TODO(v8:7700): We could have a fast path here, that checks for the
    // common case of Array or Object prototype only and therefore avoids
    // the zone allocation of this vector.
    ZoneVector<compiler::MapRef> prototype_maps(zone());
    for (compiler::ElementAccessInfo const& access_info : access_infos) {
      for (compiler::MapRef receiver_map :
           access_info.lookup_start_object_maps()) {
        // If the {receiver_map} has a prototype and its elements backing
        // store is either holey, or we have a potentially growing store,
        // then we need to check that all prototypes have stable maps with
        // with no element accessors and no throwing behavior for elements (and
        // we need to guard against changes to that below).
        if ((IsHoleyOrDictionaryElementsKind(receiver_map.elements_kind()) ||
             StoreModeCanGrow(refined_feedback.keyed_mode().store_mode())) &&
            !receiver_map.PrototypesElementsDoNotHaveAccessorsOrThrow(
                broker(), &prototype_maps)) {
          return {};
        }
        // TODO(v8:12547): Support writing to objects in shared space, which
        // need a write barrier that calls Object::Share to ensure the RHS is
        // shared.
        if (InstanceTypeChecker::IsAlwaysSharedSpaceJSObject(
                receiver_map.instance_type())) {
          return {};
        }
      }
    }
    for (compiler::MapRef prototype_map : prototype_maps) {
      broker()->dependencies()->DependOnStableMap(prototype_map);
    }
  }
  // Check for monomorphic case.
  if (access_infos.size() == 1) {
    compiler::ElementAccessInfo const& access_info = access_infos.front();
    // TODO(victorgomes): Support RAB/GSAB backed typed arrays.
    if (IsRabGsabTypedArrayElementsKind(access_info.elements_kind())) {
      return {};
    }
    if (!access_info.transition_sources().empty()) {
      compiler::MapRef transition_target =
          access_info.lookup_start_object_maps().front();
      const ZoneVector<compiler::MapRef>& transition_sources =
          access_info.transition_sources();
      // There are no transitions in heap number maps. If `object` is a SMI, we
      // would anyway fail the transition and deopt later.
      DCHECK_NE(transition_target.instance_type(),
                InstanceType::HEAP_NUMBER_TYPE);
#ifdef DEBUG
      for (auto& transition_source : transition_sources) {
        DCHECK_NE(transition_source.instance_type(),
                  InstanceType::HEAP_NUMBER_TYPE);
      }
#endif // DEBUG
      RETURN_IF_ABORT(BuildCheckHeapObject(object));
      ValueNode* object_map =
          BuildLoadTaggedField(object, HeapObject::kMapOffset);
      RETURN_IF_ABORT(BuildTransitionElementsKindOrCheckMap(
          object, object_map, transition_sources, transition_target));
    } else {
      RETURN_IF_ABORT(BuildCheckMaps(
          object, base::VectorOf(access_info.lookup_start_object_maps())));
    }
    if (IsTypedArrayElementsKind(access_info.elements_kind())) {
      return TryBuildElementAccessOnTypedArray(object, index_object,
                                               access_info, keyed_mode);
    }
    return TryBuildElementAccessOnJSArrayOrJSObject(object, index_object,
                                                    access_info, keyed_mode);
  } else {
    return TryBuildPolymorphicElementAccess(object, index_object, keyed_mode,
                                            access_infos, build_generic_access);
  }
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), broker(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfos(), DCHECK_NE, v8::internal::compiler::ElementAccessInfo::elements_kind(), v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::ElementAccessFeedback::HasOnlyStringMaps(), v8::internal::compiler::MapRef::instance_type(), v8::internal::IsHoleyOrDictionaryElementsKind(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::IsTypedArrayElementsKind(), v8::internal::compiler::ElementAccessFeedback::keyed_mode(), v8::internal::compiler::kLoad, v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kStore, v8::internal::compiler::ElementAccessInfo::lookup_start_object_maps(), v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), v8::internal::compiler::ElementAccessFeedback::Refine(), RETURN_IF_ABORT, v8::internal::ZoneVector< T >::size(), v8::internal::compiler::KeyedAccessMode::store_mode(), v8::internal::StoreModeCanGrow(), v8::internal::compiler::ElementAccessFeedback::transition_groups(), v8::internal::compiler::ElementAccessInfo::transition_sources(), and v8::base::VectorOf().
TryBuildElementAccessOnJSArrayOrJSObject()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject (ValueNode * object, ValueNode * index, const compiler::ElementAccessInfo & access_info, compiler::KeyedAccessMode const & keyed_mode) [private]
Definition at line 6739 of file maglev-graph-builder.cc.
                                               {
  if (!IsFastElementsKind(access_info.elements_kind())) {
    return {};
  }
  if (access_info.is_proxy_on_prototype()) {
    // TODO(jkummerow): Implement support.
    return {};
  }
  switch (keyed_mode.access_mode()) {
    case compiler::AccessMode::kLoad:
      return TryBuildElementLoadOnJSArrayOrJSObject(
          object, index_object,
          base::VectorOf(access_info.lookup_start_object_maps()),
          access_info.elements_kind(), keyed_mode.load_mode());
    case compiler::AccessMode::kStoreInLiteral:
    case compiler::AccessMode::kStore: {
      base::Vector<const compiler::MapRef> maps =
          base::VectorOf(access_info.lookup_start_object_maps());
      ElementsKind elements_kind = access_info.elements_kind();
      return TryBuildElementStoreOnJSArrayOrJSObject(object, index_object,
                                                     GetAccumulator(), maps,
                                                     elements_kind, keyed_mode);
    }
    default:
      // TODO(victorgomes): Implement more access types.
      return {};
  }
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), v8::internal::compiler::ElementAccessInfo::elements_kind(), v8::internal::compiler::ElementAccessInfo::is_proxy_on_prototype(), v8::internal::IsFastElementsKind(), v8::internal::compiler::kLoad, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::compiler::KeyedAccessMode::load_mode(), v8::internal::compiler::ElementAccessInfo::lookup_start_object_maps(), and v8::base::VectorOf().
TryBuildElementAccessOnString()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnString (ValueNode * object, ValueNode * index, const compiler::ElementAccessFeedback & access_info, compiler::KeyedAccessMode const & keyed_mode) [private]
Definition at line 6134 of file maglev-graph-builder.cc.
                                               {
  // Strings are immutable and `in` cannot be used on strings
  if (keyed_mode.access_mode() != compiler::AccessMode::kLoad) {
    return {};
  }
  RETURN_IF_DONE(TryReduceConstantStringAt(object, index_object,
                                           StringAtOOBMode::kElement));
  // Ensure that {object} is actually a String.
  bool is_one_byte_seq_string =
      v8_flags.specialize_code_for_one_byte_seq_strings &&
      base::all_of(access_feedback.transition_groups(), [](const auto& group) {
        return base::all_of(group, [](compiler::MapRef map) {
          return map.IsSeqStringMap() && map.IsOneByteStringMap();
        });
      });
  if (is_one_byte_seq_string) {
    RETURN_IF_ABORT(BuildCheckSeqOneByteString(object));
  } else {
    RETURN_IF_ABORT(BuildCheckString(object));
  }
  ValueNode* length = BuildLoadStringLength(object);
  ValueNode* index = GetInt32ElementIndex(index_object);
  auto emit_load = [&]() -> ValueNode* {
    if (is_one_byte_seq_string) {
      return AddNewNode<SeqOneByteStringAt>({object, index});
    } else {
      return AddNewNode<StringAt>({object, index});
    }
  };
  if (LoadModeHandlesOOB(keyed_mode.load_mode()) &&
      broker()->dependencies()->DependOnNoElementsProtector()) {
    ValueNode* positive_index;
    GET_VALUE_OR_ABORT(positive_index, GetUint32ElementIndex(index));
    ValueNode* uint32_length = AddNewNode<UnsafeInt32ToUint32>({length});
    return Select(
        [&](auto& builder) {
          return BuildBranchIfUint32Compare(builder, Operation::kLessThan,
                                            positive_index, uint32_length);
        },
        emit_load, [&] { return GetRootConstant(RootIndex::kUndefinedValue); });
  } else {
    RETURN_IF_ABORT(TryBuildCheckInt32Condition(
        index, length, AssertCondition::kUnsignedLessThan,
        DeoptimizeReason::kOutOfBounds));
    return emit_load();
  }
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), v8::base::all_of(), kElement, v8::internal::compiler::kLoad, RETURN_IF_DONE, v8::internal::compiler::ElementAccessFeedback::transition_groups(), TryReduceConstantStringAt(), and v8::internal::v8_flags.
TryBuildElementAccessOnTypedArray()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray (ValueNode * object, ValueNode * index, const compiler::ElementAccessInfo & access_info, compiler::KeyedAccessMode const & keyed_mode) [private]
Definition at line 6474 of file maglev-graph-builder.cc.
                                               {
  DCHECK(HasOnlyJSTypedArrayMaps(
      base::VectorOf(access_info.lookup_start_object_maps())));
  ElementsKind elements_kind = access_info.elements_kind();
  if (elements_kind == FLOAT16_ELEMENTS ||
      elements_kind == BIGUINT64_ELEMENTS ||
      elements_kind == BIGINT64_ELEMENTS) {
    return {};
  }
  if (keyed_mode.access_mode() == compiler::AccessMode::kLoad &&
      LoadModeHandlesOOB(keyed_mode.load_mode())) {
    // TODO(victorgomes): Handle OOB mode.
    return {};
  }
  if (keyed_mode.access_mode() == compiler::AccessMode::kStore &&
      StoreModeIgnoresTypeArrayOOB(keyed_mode.store_mode())) {
    // TODO(victorgomes): Handle OOB mode.
    return {};
  }
  if (keyed_mode.access_mode() == compiler::AccessMode::kStore &&
      elements_kind == UINT8_CLAMPED_ELEMENTS &&
      !IsSupported(CpuOperation::kFloat64Round)) {
    // TODO(victorgomes): Technically we still support if value (in the
    // accumulator) is of type int32. It would be nice to have a roll back
    // mechanism instead, so that we do not need to check this early.
    return {};
  }
  if (!broker()->dependencies()->DependOnArrayBufferDetachingProtector()) {
    // TODO(leszeks): Eliminate this check.
    AddNewNode<CheckTypedArrayNotDetached>({object});
  }
  ValueNode* index;
  ValueNode* length;
  GET_VALUE_OR_ABORT(index, GetUint32ElementIndex(index_object));
  GET_VALUE_OR_ABORT(length, BuildLoadTypedArrayLength(object, elements_kind));
  AddNewNode<CheckTypedArrayBounds>({index, length});
  switch (keyed_mode.access_mode()) {
    case compiler::AccessMode::kLoad:
      DCHECK(!LoadModeHandlesOOB(keyed_mode.load_mode()));
      if (auto constant = object->TryCast<Constant>()) {
        compiler::HeapObjectRef constant_object = constant->object();
        if (constant_object.IsJSTypedArray() &&
            constant_object.AsJSTypedArray().is_off_heap_non_rab_gsab(
                broker())) {
          return BuildLoadConstantTypedArrayElement(
              constant_object.AsJSTypedArray(), index, elements_kind);
        }
      }
      return BuildLoadTypedArrayElement(object, index, elements_kind);
    case compiler::AccessMode::kStore:
      DCHECK(StoreModeIsInBounds(keyed_mode.store_mode()));
      if (auto constant = object->TryCast<Constant>()) {
        compiler::HeapObjectRef constant_object = constant->object();
        if (constant_object.IsJSTypedArray() &&
            constant_object.AsJSTypedArray().is_off_heap_non_rab_gsab(
                broker())) {
          BuildStoreConstantTypedArrayElement(constant_object.AsJSTypedArray(),
                                              index, elements_kind);
          return ReduceResult::Done();
        }
      }
      BuildStoreTypedArrayElement(object, index, elements_kind);
      return ReduceResult::Done();
    case compiler::AccessMode::kHas:
      // TODO(victorgomes): Implement has element access.
      return {};
    case compiler::AccessMode::kStoreInLiteral:
    case compiler::AccessMode::kDefine:
      UNREACHABLE();
  }
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), broker(), v8::internal::DCHECK(), v8::internal::compiler::ElementAccessInfo::elements_kind(), GET_VALUE_OR_ABORT, v8::internal::maglev::HasOnlyJSTypedArrayMaps(), v8::internal::index, v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), v8::internal::compiler::kDefine, v8::internal::compiler::kHas, v8::internal::compiler::kLoad, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::length, v8::internal::compiler::KeyedAccessMode::load_mode(), v8::internal::LoadModeHandlesOOB(), v8::internal::compiler::ElementAccessInfo::lookup_start_object_maps(), v8::internal::compiler::KeyedAccessMode::store_mode(), v8::internal::StoreModeIgnoresTypeArrayOOB(), v8::internal::StoreModeIsInBounds(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::UINT8_CLAMPED_ELEMENTS, v8::internal::UNREACHABLE(), and v8::base::VectorOf().
TryBuildElementLoadOnJSArrayOrJSObject()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildElementLoadOnJSArrayOrJSObject (ValueNode * object, ValueNode * index, base::Vector< const compiler::MapRef > maps, ElementsKind kind, KeyedAccessLoadMode load_mode) [private]
Definition at line 6549 of file maglev-graph-builder.cc.
                                   {
  DCHECK(IsFastElementsKind(elements_kind));
  bool is_jsarray = HasOnlyJSArrayMaps(maps);
  DCHECK(is_jsarray || HasOnlyJSObjectMaps(maps));
  ValueNode* elements_array = BuildLoadElements(object);
  ValueNode* index = GetInt32ElementIndex(index_object);
  ValueNode* length = is_jsarray ? GetInt32(BuildLoadJSArrayLength(object))
                                 : BuildLoadFixedArrayLength(elements_array);
  auto emit_load = [&]() -> MaybeReduceResult {
    ValueNode* result;
    if (elements_kind == HOLEY_DOUBLE_ELEMENTS) {
      result = BuildLoadHoleyFixedDoubleArrayElement(
          elements_array, index,
          CanTreatHoleAsUndefined(maps) && LoadModeHandlesHoles(load_mode));
    } else if (elements_kind == PACKED_DOUBLE_ELEMENTS) {
      result = BuildLoadFixedDoubleArrayElement(elements_array, index);
    } else {
      DCHECK(!IsDoubleElementsKind(elements_kind));
      result = BuildLoadFixedArrayElement(elements_array, index);
      if (IsHoleyElementsKind(elements_kind)) {
        if (CanTreatHoleAsUndefined(maps) && LoadModeHandlesHoles(load_mode)) {
          result = BuildConvertHoleToUndefined(result);
        } else {
          RETURN_IF_ABORT(BuildCheckNotHole(result));
          if (IsSmiElementsKind(elements_kind)) {
            EnsureType(result, NodeType::kSmi);
          }
        }
      } else if (IsSmiElementsKind(elements_kind)) {
        EnsureType(result, NodeType::kSmi);
      }
    }
    return result;
  };
  if (CanTreatHoleAsUndefined(maps) && LoadModeHandlesOOB(load_mode)) {
    ValueNode* positive_index;
    GET_VALUE_OR_ABORT(positive_index, GetUint32ElementIndex(index));
    ValueNode* uint32_length = AddNewNode<UnsafeInt32ToUint32>({length});
    return SelectReduction(
        [&](auto& builder) {
          return BuildBranchIfUint32Compare(builder, Operation::kLessThan,
                                            positive_index, uint32_length);
        },
        emit_load, [&] { return GetRootConstant(RootIndex::kUndefinedValue); });
  } else {
    RETURN_IF_ABORT(TryBuildCheckInt32Condition(
        index, length, AssertCondition::kUnsignedLessThan,
        DeoptimizeReason::kOutOfBounds));
    return emit_load();
  }
}
References v8::internal::DCHECK(), GET_VALUE_OR_ABORT, v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::HasOnlyJSArrayMaps(), v8::internal::maglev::HasOnlyJSObjectMaps(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::index, v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiElementsKind(), v8::internal::kLessThan, v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, v8::internal::compiler::kSmi, v8::internal::kUnsignedLessThan, v8::internal::length, v8::internal::LoadModeHandlesHoles(), v8::internal::LoadModeHandlesOOB(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::base::internal::result, and RETURN_IF_ABORT.
TryBuildElementStoreOnJSArrayOrJSObject()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject (ValueNode * object, ValueNode * index_object, ValueNode * value, base::Vector< const compiler::MapRef > maps, ElementsKind kind, const compiler::KeyedAccessMode & keyed_mode) [private]
Definition at line 6626 of file maglev-graph-builder.cc.
                                               {
  DCHECK(IsFastElementsKind(elements_kind));
  const bool is_jsarray = HasOnlyJSArrayMaps(maps);
  DCHECK(is_jsarray || HasOnlyJSObjectMaps(maps));
  // Get the elements array.
  ValueNode* elements_array = BuildLoadElements(object);
  GET_VALUE_OR_ABORT(value, ConvertForStoring(value, elements_kind));
  ValueNode* index;
  // TODO(verwaest): Loop peeling will turn the first iteration index of spread
  // literals into smi constants as well, breaking the assumption that we'll
  // have preallocated the space if we see known indices. Turn off this
  // optimization if loop peeling is on.
  if (keyed_mode.access_mode() == compiler::AccessMode::kStoreInLiteral &&
      index_object->Is<SmiConstant>() && is_jsarray && !any_peeled_loop_) {
    index = GetInt32ElementIndex(index_object);
  } else {
    // Check boundaries.
    ValueNode* elements_array_length = nullptr;
    ValueNode* length;
    if (is_jsarray) {
      length = GetInt32(BuildLoadJSArrayLength(object));
    } else {
      length = elements_array_length =
          BuildLoadFixedArrayLength(elements_array);
    }
    index = GetInt32ElementIndex(index_object);
    if (keyed_mode.store_mode() == KeyedAccessStoreMode::kGrowAndHandleCOW) {
      if (elements_array_length == nullptr) {
        elements_array_length = BuildLoadFixedArrayLength(elements_array);
      }
      // Validate the {index} depending on holeyness:
      //
      // For HOLEY_*_ELEMENTS the {index} must not exceed the {elements}
      // backing store capacity plus the maximum allowed gap, as otherwise
      // the (potential) backing store growth would normalize and thus
      // the elements kind of the {receiver} would change to slow mode.
      //
      // For JSArray PACKED_*_ELEMENTS the {index} must be within the range
      // [0,length+1[ to be valid. In case {index} equals {length},
      // the {receiver} will be extended, but kept packed.
      //
      // Non-JSArray PACKED_*_ELEMENTS always grow by adding holes because they
      // lack the magical length property, which requires a map transition.
      // So we can assume that this did not happen if we did not see this map.
      ValueNode* limit =
          IsHoleyElementsKind(elements_kind)
              ? AddNewNode<Int32AddWithOverflow>(
                    {elements_array_length,
                     GetInt32Constant(JSObject::kMaxGap)})
          : is_jsarray
              ? AddNewNode<Int32AddWithOverflow>({length, GetInt32Constant(1)})
              : elements_array_length;
      RETURN_IF_ABORT(TryBuildCheckInt32Condition(
          index, limit, AssertCondition::kUnsignedLessThan,
          DeoptimizeReason::kOutOfBounds));
      // Grow backing store if necessary and handle COW.
      elements_array = AddNewNode<MaybeGrowFastElements>(
          {elements_array, object, index, elements_array_length},
          elements_kind);
      // If we didn't grow {elements}, it might still be COW, in which case we
      // copy it now.
      if (IsSmiOrObjectElementsKind(elements_kind)) {
        DCHECK_EQ(keyed_mode.store_mode(),
                  KeyedAccessStoreMode::kGrowAndHandleCOW);
        elements_array =
            AddNewNode<EnsureWritableFastElements>({elements_array, object});
      }
      // Update length if necessary.
      if (is_jsarray) {
        ValueNode* new_length =
            AddNewNode<UpdateJSArrayLength>({length, object, index});
        RecordKnownProperty(object, broker()->length_string(), new_length,
                            false, compiler::AccessMode::kStore);
      }
    } else {
      RETURN_IF_ABORT(TryBuildCheckInt32Condition(
          index, length, AssertCondition::kUnsignedLessThan,
          DeoptimizeReason::kOutOfBounds));
      // Handle COW if needed.
      if (IsSmiOrObjectElementsKind(elements_kind)) {
        if (keyed_mode.store_mode() == KeyedAccessStoreMode::kHandleCOW) {
          elements_array =
              AddNewNode<EnsureWritableFastElements>({elements_array, object});
        } else {
          // Ensure that this is not a COW FixedArray.
          RETURN_IF_ABORT(BuildCheckMaps(
              elements_array, base::VectorOf({broker()->fixed_array_map()})));
        }
      }
    }
  }
  // Do the store.
  if (IsDoubleElementsKind(elements_kind)) {
    BuildStoreFixedDoubleArrayElement(elements_array, index, value);
  } else {
    BuildStoreFixedArrayElement(elements_array, index, value);
  }
  return ReduceResult::Done();
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), broker(), v8::internal::DCHECK(), DCHECK_EQ, GET_VALUE_OR_ABORT, v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::HasOnlyJSArrayMaps(), v8::internal::maglev::HasOnlyJSObjectMaps(), v8::internal::index, v8::internal::maglev::NodeBase::Is(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::kGrowAndHandleCOW, v8::internal::kHandleCOW, v8::internal::JSObject::kMaxGap, v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::kUnsignedLessThan, v8::internal::length, RETURN_IF_ABORT, v8::internal::compiler::KeyedAccessMode::store_mode(), v8::internal::value, and v8::base::VectorOf().
TryBuildFastCreateObjectOrArrayLiteral()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildFastCreateObjectOrArrayLiteral (const compiler::LiteralFeedback & feedback) [private]
Definition at line 13975 of file maglev-graph-builder.cc.
                                             {
  compiler::AllocationSiteRef site = feedback.value();
  if (!site.boilerplate(broker()).has_value()) return {};
  AllocationType allocation_type =
      broker()->dependencies()->DependOnPretenureMode(site);
  // First try to extract out the shape and values of the boilerplate, bailing
  // out on complex boilerplates.
  int max_properties = compiler::kMaxFastLiteralProperties;
  std::optional<VirtualObject*> maybe_value = TryReadBoilerplateForFastLiteral(
      *site.boilerplate(broker()), allocation_type,
      compiler::kMaxFastLiteralDepth, &max_properties);
  if (!maybe_value.has_value()) return {};
  // Then, use the collected information to actually create nodes in the graph.
  // TODO(leszeks): Add support for unwinding graph modifications, so that we
  // can get rid of this two pass approach.
  broker()->dependencies()->DependOnElementsKinds(site);
  MaybeReduceResult result =
      BuildInlinedAllocation(*maybe_value, allocation_type);
  return result;
}
References v8::internal::compiler::AllocationSiteRef::boilerplate(), broker(), v8::internal::compiler::kMaxFastLiteralDepth, v8::internal::compiler::kMaxFastLiteralProperties, v8::base::internal::result, and v8::internal::compiler::SingleValueFeedback< T, K >::value().
TryBuildFastHasInPrototypeChain()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildFastHasInPrototypeChain (ValueNode * object, compiler::HeapObjectRef prototype) [private]
Definition at line 12654 of file maglev-graph-builder.cc.
                                                        {
  auto in_prototype_chain = InferHasInPrototypeChain(object, prototype);
  if (in_prototype_chain == kMayBeInPrototypeChain) return {};
  return GetBooleanConstant(in_prototype_chain == kIsInPrototypeChain);
}
References v8::internal::prototype.
TryBuildFastInstanceOf()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf (ValueNode * object, compiler::JSObjectRef callable_ref, ValueNode * callable_node) [private]
Definition at line 12725 of file maglev-graph-builder.cc.
                                              {
  compiler::MapRef receiver_map = callable.map(broker());
  compiler::NameRef name = broker()->has_instance_symbol();
  compiler::PropertyAccessInfo access_info = broker()->GetPropertyAccessInfo(
      receiver_map, name, compiler::AccessMode::kLoad);
  // TODO(v8:11457) Support dictionary mode holders here.
  if (access_info.IsInvalid() || access_info.HasDictionaryHolder()) {
    return {};
  }
  access_info.RecordDependencies(broker()->dependencies());
  if (access_info.IsNotFound()) {
    // If there's no @@hasInstance handler, the OrdinaryHasInstance operation
    // takes over, but that requires the constructor to be callable.
    if (!receiver_map.is_callable()) return {};
    broker()->dependencies()->DependOnStablePrototypeChains(
        access_info.lookup_start_object_maps(), kStartAtPrototype);
    // Monomorphic property access.
    if (callable_node_if_not_constant) {
      RETURN_IF_ABORT(BuildCheckMaps(
          callable_node_if_not_constant,
          base::VectorOf(access_info.lookup_start_object_maps())));
    } else {
      // Even if we have a constant receiver, we still have to make sure its
      // map is correct, in case it migrates.
      if (receiver_map.is_stable()) {
        broker()->dependencies()->DependOnStableMap(receiver_map);
      } else {
        RETURN_IF_ABORT(BuildCheckMaps(
            GetConstant(callable),
            base::VectorOf(access_info.lookup_start_object_maps())));
      }
    }
    return BuildOrdinaryHasInstance(object, callable,
                                    callable_node_if_not_constant);
  }
  if (access_info.IsFastDataConstant()) {
    compiler::OptionalJSObjectRef holder = access_info.holder();
    bool found_on_proto = holder.has_value();
    compiler::JSObjectRef holder_ref =
        found_on_proto ? holder.value() : callable;
    if (access_info.field_representation().IsDouble()) return {};
    compiler::OptionalObjectRef has_instance_field =
        holder_ref.GetOwnFastConstantDataProperty(
            broker(), access_info.field_representation(),
            access_info.field_index(), broker()->dependencies());
    if (!has_instance_field.has_value() ||
        !has_instance_field->IsHeapObject() ||
        !has_instance_field->AsHeapObject().map(broker()).is_callable()) {
      return {};
    }
    if (found_on_proto) {
      broker()->dependencies()->DependOnStablePrototypeChains(
          access_info.lookup_start_object_maps(), kStartAtPrototype,
          holder.value());
    }
    ValueNode* callable_node;
    if (callable_node_if_not_constant) {
      // Check that {callable_node_if_not_constant} is actually {callable}.
      RETURN_IF_ABORT(
          BuildCheckValueByReference(callable_node_if_not_constant, callable,
                                     DeoptimizeReason::kWrongValue));
      callable_node = callable_node_if_not_constant;
    } else {
      callable_node = GetConstant(callable);
    }
    RETURN_IF_ABORT(BuildCheckMaps(
        callable_node, base::VectorOf(access_info.lookup_start_object_maps())));
    // Special case the common case, where @@hasInstance is
    // Function.p.hasInstance. In this case we don't need to call ToBoolean (or
    // use the continuation), since OrdinaryHasInstance is guaranteed to return
    // a boolean.
    if (has_instance_field->IsJSFunction()) {
      compiler::SharedFunctionInfoRef shared =
          has_instance_field->AsJSFunction().shared(broker());
      if (shared.HasBuiltinId() &&
          shared.builtin_id() == Builtin::kFunctionPrototypeHasInstance) {
        return BuildOrdinaryHasInstance(object, callable,
                                        callable_node_if_not_constant);
      }
    }
    // Call @@hasInstance
    CallArguments args(ConvertReceiverMode::kNotNullOrUndefined,
                       {callable_node, object});
    ValueNode* call_result;
    {
      // Make sure that a lazy deopt after the @@hasInstance call also performs
      // ToBoolean before returning to the interpreter.
      DeoptFrameScope continuation_scope(
          this, Builtin::kToBooleanLazyDeoptContinuation);
      if (has_instance_field->IsJSFunction()) {
        SaveCallSpeculationScope saved(this);
        GET_VALUE_OR_ABORT(
            call_result,
            TryReduceCallForConstant(has_instance_field->AsJSFunction(), args));
      } else {
        call_result = BuildGenericCall(GetConstant(*has_instance_field),
                                       Call::TargetType::kAny, args);
      }
      // TODO(victorgomes): Propagate the case if we need to soft deopt.
    }
    return BuildToBoolean(call_result);
  }
  return {};
}
References v8::base::args, broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_representation(), GET_VALUE_OR_ABORT, v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), v8::internal::compiler::PropertyAccessInfo::HasDictionaryHolder(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::compiler::MapRef::is_callable(), v8::internal::compiler::MapRef::is_stable(), v8::internal::Representation::IsDouble(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), v8::internal::compiler::PropertyAccessInfo::IsInvalid(), v8::internal::compiler::PropertyAccessInfo::IsNotFound(), v8::internal::compiler::kLoad, v8::internal::kNotNullOrUndefined, v8::internal::kStartAtPrototype, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::name, v8::internal::compiler::PropertyAccessInfo::RecordDependencies(), RETURN_IF_ABORT, and v8::base::VectorOf().
TryBuildFastInstanceOfWithFeedback()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOfWithFeedback (ValueNode * object, ValueNode * callable, compiler::FeedbackSource feedback_source) [private]
Definition at line 12915 of file maglev-graph-builder.cc.
                                            {
  compiler::ProcessedFeedback const& feedback =
      broker()->GetFeedbackForInstanceOf(feedback_source);
  if (feedback.IsInsufficient()) {
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kInsufficientTypeFeedbackForInstanceOf);
  }
  // Check if the right hand side is a known receiver, or
  // we have feedback from the InstanceOfIC.
  compiler::OptionalHeapObjectRef maybe_constant;
  if ((maybe_constant = TryGetConstant(callable)) &&
      maybe_constant.value().IsJSObject()) {
    compiler::JSObjectRef callable_ref = maybe_constant.value().AsJSObject();
    return TryBuildFastInstanceOf(object, callable_ref, nullptr);
  }
  if (feedback_source.IsValid()) {
    compiler::OptionalJSObjectRef callable_from_feedback =
        feedback.AsInstanceOf().value();
    if (callable_from_feedback) {
      return TryBuildFastInstanceOf(object, *callable_from_feedback, callable);
    }
  }
  return {};
}
References v8::internal::compiler::ProcessedFeedback::AsInstanceOf(), broker(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), and v8::internal::compiler::SingleValueFeedback< T, K >::value().
TryBuildFastOrdinaryHasInstance()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildFastOrdinaryHasInstance (ValueNode * object, compiler::JSObjectRef callable, ValueNode * callable_node) [private]
Definition at line 12668 of file maglev-graph-builder.cc.
                                              {
  const bool is_constant = callable_node_if_not_constant == nullptr;
  if (!is_constant) return {};
  if (callable.IsJSBoundFunction()) {
    // OrdinaryHasInstance on bound functions turns into a recursive
    // invocation of the instanceof operator again.
    compiler::JSBoundFunctionRef function = callable.AsJSBoundFunction();
    compiler::JSReceiverRef bound_target_function =
        function.bound_target_function(broker());
    if (bound_target_function.IsJSObject()) {
      RETURN_IF_DONE(TryBuildFastInstanceOf(
          object, bound_target_function.AsJSObject(), nullptr));
    }
    // If we can't build a fast instance-of, build a slow one with the
    // partial optimisation of using the bound target function constant.
    return BuildCallBuiltin<Builtin::kInstanceOf>(
        {GetTaggedValue(object), GetConstant(bound_target_function)});
  }
  if (callable.IsJSFunction()) {
    // Optimize if we currently know the "prototype" property.
    compiler::JSFunctionRef function = callable.AsJSFunction();
    // TODO(v8:7700): Remove the has_prototype_slot condition once the broker
    // is always enabled.
    if (!function.map(broker()).has_prototype_slot() ||
        !function.has_instance_prototype(broker()) ||
        function.PrototypeRequiresRuntimeLookup(broker())) {
      return {};
    }
    compiler::HeapObjectRef prototype =
        broker()->dependencies()->DependOnPrototypeProperty(function);
    return BuildHasInPrototypeChain(object, prototype);
  }
  return {};
}
References broker(), v8::internal::prototype, and RETURN_IF_DONE.
TryBuildFindNonDefaultConstructorOrConstruct()
bool v8::internal::maglev::MaglevGraphBuilder::TryBuildFindNonDefaultConstructorOrConstruct (ValueNode * this_function, ValueNode * new_target, std::pair< interpreter::Register, interpreter::Register > result) [private]
Definition at line 8217 of file maglev-graph-builder.cc.
                                                              {
  // See also:
  // JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct
  compiler::OptionalHeapObjectRef maybe_constant =
      TryGetConstant(this_function);
  if (!maybe_constant) return false;
  compiler::MapRef function_map = maybe_constant->map(broker());
  compiler::HeapObjectRef current = function_map.prototype(broker());
  // TODO(v8:13091): Don't produce incomplete stack traces when debug is active.
  // We already deopt when a breakpoint is set. But it would be even nicer to
  // avoid producting incomplete stack traces when when debug is active, even if
  // there are no breakpoints - then a user inspecting stack traces via Dev
  // Tools would always see the full stack trace.
  while (true) {
    if (!current.IsJSFunction()) return false;
    compiler::JSFunctionRef current_function = current.AsJSFunction();
    // If there are class fields, bail out. TODO(v8:13091): Handle them here.
    if (current_function.shared(broker())
            .requires_instance_members_initializer()) {
      return false;
    }
    // If there are private methods, bail out. TODO(v8:13091): Handle them here.
    if (current_function.context(broker())
            .scope_info(broker())
            .ClassScopeHasPrivateBrand()) {
      return false;
    }
    FunctionKind kind = current_function.shared(broker()).kind();
    if (kind != FunctionKind::kDefaultDerivedConstructor) {
      // The hierarchy walk will end here; this is the last change to bail out
      // before creating new nodes.
      if (!broker()->dependencies()->DependOnArrayIteratorProtector()) {
        return false;
      }
      compiler::OptionalHeapObjectRef new_target_function =
          TryGetConstant(new_target);
      if (kind == FunctionKind::kDefaultBaseConstructor) {
        // Store the result register first, so that a lazy deopt in
        // `FastNewObject` writes `true` to this register.
        StoreRegister(result.first, GetBooleanConstant(true));
        ValueNode* object;
        if (new_target_function && new_target_function->IsJSFunction() &&
            HasValidInitialMap(new_target_function->AsJSFunction(),
                               current_function)) {
          object = BuildInlinedAllocation(
              CreateJSConstructor(new_target_function->AsJSFunction()),
              AllocationType::kYoung);
        } else {
          // We've already stored "true" into result.first, so a deopt here just
          // has to store result.second.
          LazyDeoptResultLocationScope new_location(this, result.second, 1);
          object = BuildCallBuiltin<Builtin::kFastNewObject>(
              {GetConstant(current_function), GetTaggedValue(new_target)});
        }
        StoreRegister(result.second, object);
      } else {
        StoreRegister(result.first, GetBooleanConstant(false));
        StoreRegister(result.second, GetConstant(current));
      }
      broker()->dependencies()->DependOnStablePrototypeChain(
          function_map, WhereToStart::kStartAtReceiver, current_function);
      return true;
    }
    // Keep walking up the class tree.
    current = current_function.map(broker()).prototype(broker());
  }
}
References broker(), v8::internal::compiler::JSFunctionRef::context(), v8::internal::libvtune::function_map, v8::internal::kDefaultBaseConstructor, v8::internal::kDefaultDerivedConstructor, v8::internal::kStartAtReceiver, v8::internal::kYoung, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::MapRef::prototype(), v8::internal::requires_instance_members_initializer, v8::base::internal::result, v8::internal::compiler::JSFunctionRef::shared(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
TryBuildGetKeyedPropertyWithEnumeratedKey()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildGetKeyedPropertyWithEnumeratedKey (ValueNode * object, const compiler::FeedbackSource & feedback_source, const compiler::ProcessedFeedback & processed_feedback) [private]
Definition at line 7574 of file maglev-graph-builder.cc.
                                                         {
  if (current_for_in_state.index != nullptr &&
      current_for_in_state.enum_cache_indices != nullptr &&
      current_for_in_state.key == current_interpreter_frame_.accumulator()) {
    bool speculating_receiver_map_matches = false;
    if (current_for_in_state.receiver != object) {
      // When the feedback is uninitialized, it is either a keyed load which
      // always hits the enum cache, or a keyed load that had never been
      // reached. In either case, we can check the map of the receiver and use
      // the enum cache if the map match the {cache_type}.
      if (processed_feedback.kind() !=
          compiler::ProcessedFeedback::kInsufficient) {
        return MaybeReduceResult::Fail();
      }
      if (BuildCheckHeapObject(object).IsDoneWithAbort()) {
        return ReduceResult::DoneWithAbort();
      }
      speculating_receiver_map_matches = true;
    }
    if (current_for_in_state.receiver_needs_map_check ||
        speculating_receiver_map_matches) {
      auto* receiver_map = BuildLoadTaggedField(object, HeapObject::kMapOffset);
      AddNewNode<CheckDynamicValue>(
          {receiver_map, current_for_in_state.cache_type},
          DeoptimizeReason::kWrongMapDynamic);
      if (current_for_in_state.receiver == object) {
        current_for_in_state.receiver_needs_map_check = false;
      }
    }
    // TODO(leszeks): Cache the field index per iteration.
    auto* field_index = BuildLoadFixedArrayElement(
        current_for_in_state.enum_cache_indices, current_for_in_state.index);
    SetAccumulator(
        AddNewNode<LoadTaggedFieldByFieldIndex>({object, field_index}));
    return ReduceResult::Done();
  }
  return MaybeReduceResult::Fail();
}
References v8::internal::compiler::ProcessedFeedback::kind(), v8::internal::compiler::ProcessedFeedback::kInsufficient, and v8::internal::HeapObject::kMapOffset.
TryBuildGlobalLoad()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalLoad (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4274 of file maglev-graph-builder.cc.
                                                                {
  if (global_access_feedback.IsScriptContextSlot()) {
    return TryBuildScriptContextLoad(global_access_feedback);
  } else if (global_access_feedback.IsPropertyCell()) {
    return TryBuildPropertyCellLoad(global_access_feedback);
  } else {
    DCHECK(global_access_feedback.IsMegamorphic());
    return {};
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::GlobalAccessFeedback::IsMegamorphic(), v8::internal::compiler::GlobalAccessFeedback::IsPropertyCell(), v8::internal::compiler::GlobalAccessFeedback::IsScriptContextSlot(), TryBuildPropertyCellLoad(), and TryBuildScriptContextLoad().
TryBuildGlobalStore()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalStore (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4262 of file maglev-graph-builder.cc.
                                                                {
  if (global_access_feedback.IsScriptContextSlot()) {
    return TryBuildScriptContextStore(global_access_feedback);
  } else if (global_access_feedback.IsPropertyCell()) {
    return TryBuildPropertyCellStore(global_access_feedback);
  } else {
    DCHECK(global_access_feedback.IsMegamorphic());
    return {};
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::GlobalAccessFeedback::IsMegamorphic(), v8::internal::compiler::GlobalAccessFeedback::IsPropertyCell(), v8::internal::compiler::GlobalAccessFeedback::IsScriptContextSlot(), TryBuildPropertyCellStore(), and TryBuildScriptContextStore().
TryBuildInlineCall()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall (ValueNode * context, ValueNode * function, ValueNode * new_target, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 8505 of file maglev-graph-builder.cc.
                                                   {
  DCHECK_EQ(args.mode(), CallArguments::kDefault);
  if (!feedback_cell.feedback_vector(broker())) {
    // TODO(verwaest): Soft deopt instead?
    TRACE_CANNOT_INLINE("it has not been compiled/run with feedback yet");
    return {};
  }
  float feedback_frequency = 0.0f;
  if (feedback_source.IsValid()) {
    compiler::ProcessedFeedback const& feedback =
        broker()->GetFeedbackForCall(feedback_source);
    feedback_frequency =
        feedback.IsInsufficient() ? 0.0f : feedback.AsCall().frequency();
  }
  float call_frequency = feedback_frequency * GetCurrentCallFrequency();
  if (!CanInlineCall(shared, call_frequency)) return {};
  if (ShouldEagerInlineCall(shared)) {
    return BuildEagerInlineCall(context, function, new_target, shared,
                                feedback_cell, args, call_frequency);
  }
  // Should we inline call?
  if (inlining_depth() > max_inline_depth()) {
    TRACE_CANNOT_INLINE("inlining depth (" << inlining_depth()
                                           << ") >= max-depth ("
                                           << max_inline_depth() << ")");
    return {};
  }
  compiler::BytecodeArrayRef bytecode = shared.GetBytecodeArray(broker());
  if (!is_non_eager_inlining_enabled()) {
    graph()->add_inlined_bytecode_size(bytecode.length());
    return BuildEagerInlineCall(context, function, new_target, shared,
                                feedback_cell, args, call_frequency);
  }
  TRACE_INLINING(" considering " << shared << " for inlining");
  auto arguments = GetArgumentsAsArrayOfValueNodes(shared, args);
  auto generic_call = BuildCallKnownJSFunction(context, function, new_target,
#ifdef V8_ENABLE_LEAPTIERING
                                               dispatch_handle,
#endif
                                               shared, arguments);
  // Note: We point to the generic call exception handler instead of
  // jump_targets_ because the former contains a BasicBlockRef that is
  // guaranteed to be updated correctly upon exception block creation.
  // BuildLoopForPeeling might reset the BasicBlockRef in jump_targets_. If this
  // happens, inlined calls within the peeled loop would incorrectly point to
  // the loop's exception handler instead of the original call's.
  CatchBlockDetails catch_details = GetTryCatchBlockForNonEagerInlining(
      generic_call->exception_handler_info());
  catch_details.deopt_frame_distance++;
  float score = call_frequency / bytecode.length();
  MaglevCallSiteInfo* call_site = zone()->New<MaglevCallSiteInfo>(
      MaglevCallerDetails{
          arguments, &generic_call->lazy_deopt_info()->top_frame(),
          known_node_aspects().Clone(zone()), loop_effects_,
          unobserved_context_slot_stores_, catch_details, IsInsideLoop(),
          /* is_eager_inline */ false, call_frequency},
      generic_call, feedback_cell, score);
  graph()->inlineable_calls().push_back(call_site);
  return generic_call;
}
References v8::base::args, v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), DCHECK_EQ, v8::internal::maglev::CatchBlockDetails::deopt_frame_distance, v8::internal::compiler::FeedbackCellRef::feedback_vector(), v8::internal::compiler::CallFeedback::frequency(), graph(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::compiler::BytecodeArrayRef::length(), TRACE_CANNOT_INLINE, and TRACE_INLINING.
TryBuildInlinedAllocatedContext()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildInlinedAllocatedContext (compiler::MapRef map, compiler::ScopeInfoRef scope, int context_length) [private]
Definition at line 14097 of file maglev-graph-builder.cc.
                                                                        {
  const int kContextAllocationLimit = 16;
  if (context_length > kContextAllocationLimit) return {};
  DCHECK_GE(context_length, Context::MIN_CONTEXT_SLOTS);
  auto context = CreateContext(map, context_length, scope, GetContext());
  ValueNode* result = BuildInlinedAllocation(context, AllocationType::kYoung);
  return result;
}
References DCHECK_GE, v8::internal::kYoung, v8::internal::Context::MIN_CONTEXT_SLOTS, and v8::base::internal::result.
TryBuildLoadDataView()
template<typename LoadNode >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadDataView (const CallArguments & args, ExternalArrayType type) [private]
Definition at line 9676 of file maglev-graph-builder.cc.
                                                       {
  if (!CanSpeculateCall()) return {};
  if (!broker()->dependencies()->DependOnArrayBufferDetachingProtector()) {
    // TODO(victorgomes): Add checks whether the array has been detached.
    return {};
  }
  // TODO(victorgomes): Add data view to known types.
  ValueNode* receiver = GetValueOrUndefined(args.receiver());
  AddNewNode<CheckInstanceType>({receiver}, CheckType::kCheckHeapObject,
                                JS_DATA_VIEW_TYPE, JS_DATA_VIEW_TYPE);
  // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
  ValueNode* offset =
      args[0] ? GetInt32ElementIndex(args[0]) : GetInt32Constant(0);
  AddNewNode<CheckJSDataViewBounds>({receiver, offset}, type);
  ValueNode* is_little_endian = args[1] ? args[1] : GetBooleanConstant(false);
  return AddNewNode<LoadNode>({receiver, offset, is_little_endian}, type);
}
References v8::base::args, broker(), and v8::internal::tracing::type.
TryBuildLoadNamedProperty() [1/2]
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadNamedProperty (ValueNode * receiver, compiler::NameRef name, compiler::FeedbackSource & feedback_source) [private]
Definition at line 7509 of file maglev-graph-builder.cc.
                                             {
  auto build_generic_access = [this, &receiver, &name, &feedback_source]() {
    ValueNode* context = GetContext();
    return AddNewNode<LoadNamedGeneric>({context, receiver}, name,
                                        feedback_source);
  };
  return TryBuildLoadNamedProperty(receiver, receiver, name, feedback_source,
                                   build_generic_access);
}
References v8::internal::name.
TryBuildLoadNamedProperty() [2/2]
template<typename GenericAccessFunc >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildLoadNamedProperty (ValueNode * receiver, ValueNode * lookup_start_object, compiler::NameRef name, compiler::FeedbackSource & feedback_source, GenericAccessFunc && build_generic_access) [private]
Definition at line 7487 of file maglev-graph-builder.cc.
                                              {
  const compiler::ProcessedFeedback& processed_feedback =
      broker()->GetFeedbackForPropertyAccess(feedback_source,
                                             compiler::AccessMode::kLoad, name);
  switch (processed_feedback.kind()) {
    case compiler::ProcessedFeedback::kInsufficient:
      return EmitUnconditionalDeopt(
          DeoptimizeReason::kInsufficientTypeFeedbackForGenericNamedAccess);
    case compiler::ProcessedFeedback::kNamedAccess: {
      RETURN_IF_DONE(TryReuseKnownPropertyLoad(lookup_start_object, name));
      return TryBuildNamedAccess(
          receiver, lookup_start_object, processed_feedback.AsNamedAccess(),
          feedback_source, compiler::AccessMode::kLoad, build_generic_access);
    }
    default:
      return {};
  }
}
References v8::internal::compiler::ProcessedFeedback::AsNamedAccess(), broker(), v8::internal::compiler::ProcessedFeedback::kind(), v8::internal::compiler::ProcessedFeedback::kInsufficient, v8::internal::compiler::kLoad, v8::internal::compiler::ProcessedFeedback::kNamedAccess, v8::internal::name, and RETURN_IF_DONE.
TryBuildNamedAccess()
template<typename GenericAccessFunc >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess (ValueNode * receiver, ValueNode * lookup_start_object, compiler::NamedAccessFeedback const & feedback, compiler::FeedbackSource const & feedback_source, compiler::AccessMode access_mode, GenericAccessFunc && build_generic_access) [private]
Definition at line 5922 of file maglev-graph-builder.cc.
                                              {
  compiler::ZoneRefSet<Map> inferred_maps;
  bool has_deprecated_map_without_migration_target = false;
  if (compiler::OptionalHeapObjectRef c = TryGetConstant(lookup_start_object)) {
    compiler::MapRef constant_map = c.value().map(broker());
    if (c.value().IsJSFunction() &&
        feedback.name().equals(broker()->prototype_string())) {
      compiler::JSFunctionRef function = c.value().AsJSFunction();
      if (!constant_map.has_prototype_slot() ||
          !function.has_instance_prototype(broker()) ||
          function.PrototypeRequiresRuntimeLookup(broker()) ||
          access_mode != compiler::AccessMode::kLoad) {
        return {};
      }
      compiler::HeapObjectRef prototype =
          broker()->dependencies()->DependOnPrototypeProperty(function);
      return GetConstant(prototype);
    }
    inferred_maps = compiler::ZoneRefSet<Map>(constant_map);
  } else if (feedback.maps().empty()) {
    // The IC is megamorphic.
    // We can't do megamorphic loads for lookups where the lookup start isn't
    // the receiver (e.g. load from super).
    if (receiver != lookup_start_object) return {};
    // Use known possible maps if we have any.
    NodeInfo* object_info =
        known_node_aspects().TryGetInfoFor(lookup_start_object);
    if (object_info && object_info->possible_maps_are_known()) {
      inferred_maps = object_info->possible_maps();
    } else {
      // If we have no known maps, make the access megamorphic.
      switch (access_mode) {
        case compiler::AccessMode::kLoad:
          return BuildCallBuiltin<Builtin::kLoadIC_Megamorphic>(
              {GetTaggedValue(receiver), GetConstant(feedback.name())},
              feedback_source);
        case compiler::AccessMode::kStore:
          return BuildCallBuiltin<Builtin::kStoreIC_Megamorphic>(
              {GetTaggedValue(receiver), GetConstant(feedback.name()),
               GetTaggedValue(GetAccumulator())},
              feedback_source);
        case compiler::AccessMode::kDefine:
          return {};
        case compiler::AccessMode::kHas:
        case compiler::AccessMode::kStoreInLiteral:
          UNREACHABLE();
      }
    }
  } else {
    // TODO(leszeks): This is doing duplicate work with BuildCheckMaps,
    // consider passing the merger into there.
    KnownMapsMerger merger(broker(), zone(), base::VectorOf(feedback.maps()));
    merger.IntersectWithKnownNodeAspects(lookup_start_object,
                                         known_node_aspects());
    inferred_maps = merger.intersect_set();
    has_deprecated_map_without_migration_target =
        feedback.has_deprecated_map_without_migration_target();
  }
  if (inferred_maps.is_empty()) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongMap);
  }
  ZoneVector<compiler::PropertyAccessInfo> access_infos(zone());
  ZoneVector<compiler::PropertyAccessInfo> access_infos_for_feedback(zone());
  for (compiler::MapRef map : inferred_maps) {
    if (map.is_deprecated()) continue;
    // TODO(v8:12547): Support writing to objects in shared space, which
    // need a write barrier that calls Object::Share to ensure the RHS is
    // shared.
    if (InstanceTypeChecker::IsAlwaysSharedSpaceJSObject(map.instance_type()) &&
        access_mode == compiler::AccessMode::kStore) {
      return {};
    }
    compiler::PropertyAccessInfo access_info =
        broker()->GetPropertyAccessInfo(map, feedback.name(), access_mode);
    access_infos_for_feedback.push_back(access_info);
  }
  compiler::AccessInfoFactory access_info_factory(broker(), zone());
  if (!access_info_factory.FinalizePropertyAccessInfos(
          access_infos_for_feedback, access_mode, &access_infos)) {
    return {};
  }
  // Check for monomorphic case.
  if (access_infos.size() == 1) {
    compiler::PropertyAccessInfo const& access_info = access_infos.front();
    base::Vector<const compiler::MapRef> maps =
        base::VectorOf(access_info.lookup_start_object_maps());
    if (HasOnlyStringMaps(maps)) {
      // Check for string maps before checking if we need to do an access
      // check. Primitive strings always get the prototype from the native
      // context they're operated on, so they don't need the access check.
      if (v8_flags.specialize_code_for_one_byte_seq_strings &&
          base::all_of(maps, [](compiler::MapRef map) {
            return map.IsSeqStringMap() && map.IsOneByteStringMap();
          })) {
        RETURN_IF_ABORT(BuildCheckSeqOneByteString(lookup_start_object));
      } else {
        RETURN_IF_ABORT(BuildCheckString(lookup_start_object));
      }
    } else if (HasOnlyNumberMaps(maps)) {
      RETURN_IF_ABORT(BuildCheckNumber(lookup_start_object));
    } else {
      RETURN_IF_ABORT(
          BuildCheckMaps(lookup_start_object, maps, {},
                         has_deprecated_map_without_migration_target));
    }
    // Generate the actual property
    return TryBuildPropertyAccess(receiver, lookup_start_object,
                                  feedback.name(), access_info, access_mode);
  } else {
    // TODO(victorgomes): Unify control flow logic with
    // TryBuildPolymorphicElementAccess.
    return TryBuildPolymorphicPropertyAccess(
        receiver, lookup_start_object, feedback, access_mode, access_infos,
        build_generic_access);
  }
}
References v8::base::all_of(), broker(), BuildCheckMaps(), BuildCheckNumber(), BuildCheckSeqOneByteString(), BuildCheckString(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnPrototypeProperty(), EmitUnconditionalDeopt(), feedback(), v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfos(), v8::internal::ZoneVector< T >::front(), GetAccumulator(), GetConstant(), v8::internal::compiler::JSHeapBroker::GetPropertyAccessInfo(), GetTaggedValue(), v8::internal::compiler::MapRef::has_prototype_slot(), v8::internal::maglev::HasOnlyNumberMaps(), v8::internal::maglev::HasOnlyStringMaps(), v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::compiler::kDefine, v8::internal::compiler::kHas, v8::internal::compiler::kLoad, known_node_aspects(), v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), v8::internal::prototype, v8::internal::ZoneVector< T >::push_back(), RETURN_IF_ABORT, v8::internal::ZoneVector< T >::size(), TryBuildPolymorphicPropertyAccess(), TryBuildPropertyAccess(), TryGetConstant(), v8::internal::maglev::KnownNodeAspects::TryGetInfoFor(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, v8::base::VectorOf(), and zone().
TryBuildNewConsString()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildNewConsString (ValueNode * left, ValueNode * right, AllocationType allocation_type = AllocationType::kYoung) [private]
Definition at line 2833 of file maglev-graph-builder.cc.
                                                                       {
  // This optimization is also done by Turboshaft.
  if (is_turbolev()) {
    return ReduceResult::Fail();
  }
  if (!v8_flags.maglev_cons_string_elision) {
    return ReduceResult::Fail();
  }
  DCHECK(NodeTypeIs(GetType(left), NodeType::kString));
  DCHECK(NodeTypeIs(GetType(right), NodeType::kString));
  size_t left_min_length = StringLengthStaticLowerBound(left);
  size_t right_min_length = StringLengthStaticLowerBound(right);
  bool result_is_cons_string =
      left_min_length + right_min_length >= ConsString::kMinLength;
  // TODO(olivf): Support the fast case with a non-cons string fallback.
  if (!result_is_cons_string) {
    return MaybeReduceResult::Fail();
  }
  ValueNode* left_length = BuildLoadStringLength(left);
  ValueNode* right_length = BuildLoadStringLength(right);
  auto BuildConsString = [&]() {
    ValueNode* new_length;
    MaybeReduceResult folded =
        TryFoldInt32BinaryOperation<Operation::kAdd>(left_length, right_length);
    if (folded.HasValue()) {
      new_length = folded.value();
    } else {
      new_length =
          AddNewNode<Int32AddWithOverflow>({left_length, right_length});
    }
    // TODO(olivf): Add unconditional deopt support to the Select builder
    // instead of disabling unconditional deopt it here.
    MaybeReduceResult too_long = TryBuildCheckInt32Condition(
        new_length, GetInt32Constant(String::kMaxLength),
        AssertCondition::kUnsignedLessThanEqual,
        DeoptimizeReason::kStringTooLarge,
        /* allow_unconditional_deopt */ false);
    CHECK(!too_long.IsDoneWithAbort());
    ValueNode* new_map = BuildNewConsStringMap(left, right);
    VirtualObject* cons_string =
        CreateConsString(new_map, new_length, left, right);
    ValueNode* allocation =
        BuildInlinedAllocation(cons_string, allocation_type);
    return allocation;
  };
  return Select(
      [&](auto& builder) {
        if (left_min_length > 0) return BranchResult::kAlwaysFalse;
        return BuildBranchIfInt32Compare(builder, Operation::kEqual,
                                         left_length, GetInt32Constant(0));
      },
      [&] { return right; },
      [&] {
        return Select(
            [&](auto& builder) {
              if (right_min_length > 0) return BranchResult::kAlwaysFalse;
              return BuildBranchIfInt32Compare(builder, Operation::kEqual,
                                               right_length,
                                               GetInt32Constant(0));
            },
            [&] { return left; }, [&] { return BuildConsString(); });
      });
}
References BuildBranchIfInt32Compare(), BuildInlinedAllocation(), BuildLoadStringLength(), BuildNewConsStringMap(), CHECK, CreateConsString(), v8::internal::DCHECK(), v8::internal::maglev::MaybeReduceResult::Fail(), GetInt32Constant(), GetType(), v8::internal::maglev::MaybeReduceResult::HasValue(), is_turbolev(), v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort(), kAlwaysFalse, v8::internal::kEqual, v8::internal::String::kMaxLength, v8::internal::ConsString::kMinLength, v8::internal::kUnsignedLessThanEqual, v8::internal::maglev::NodeTypeIs(), Select(), StringLengthStaticLowerBound(), TryBuildCheckInt32Condition(), v8::internal::v8_flags, and v8::internal::maglev::MaybeReduceResult::value().
Referenced by BuildStringConcat().
TryBuildPolymorphicElementAccess()
template<typename GenericAccessFunc >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess (ValueNode * object, ValueNode * index, const compiler::KeyedAccessMode & keyed_mode, const ZoneVector< compiler::ElementAccessInfo > & access_infos, GenericAccessFunc && build_generic_access) [private]
Definition at line 6900 of file maglev-graph-builder.cc.
                                              {
  if (keyed_mode.access_mode() == compiler::AccessMode::kLoad &&
      LoadModeHandlesOOB(keyed_mode.load_mode())) {
    // TODO(victorgomes): Handle OOB mode.
    return {};
  }
  const bool is_any_store = compiler::IsAnyStore(keyed_mode.access_mode());
  const int access_info_count = static_cast<int>(access_infos.size());
  // Stores don't return a value, so we don't need a variable for the result.
  MaglevSubGraphBuilder sub_graph(this, is_any_store ? 0 : 1);
  std::optional<MaglevSubGraphBuilder::Variable> ret_val;
  std::optional<MaglevSubGraphBuilder::Label> done;
  std::optional<MaglevSubGraphBuilder::Label> generic_access;
  RETURN_IF_ABORT(BuildCheckHeapObject(object));
  ValueNode* object_map = BuildLoadTaggedField(object, HeapObject::kMapOffset);
  // TODO(pthier): We could do better here than just emitting code for each map,
  // as many different maps can produce the exact samce code (e.g. TypedArray
  // access for Uint16/Uint32/Int16/Int32/...).
  for (int i = 0; i < access_info_count; i++) {
    compiler::ElementAccessInfo const& access_info = access_infos[i];
    std::optional<MaglevSubGraphBuilder::Label> check_next_map;
    const bool handle_transitions = !access_info.transition_sources().empty();
    MaybeReduceResult map_check_result;
    if (i == access_info_count - 1) {
      if (handle_transitions) {
        compiler::MapRef transition_target =
            access_info.lookup_start_object_maps().front();
        map_check_result = BuildTransitionElementsKindOrCheckMap(
            object, object_map, access_info.transition_sources(),
            transition_target);
      } else {
        map_check_result = BuildCheckMaps(
            object, base::VectorOf(access_info.lookup_start_object_maps()),
            object_map);
      }
    } else {
      if (handle_transitions) {
        compiler::MapRef transition_target =
            access_info.lookup_start_object_maps().front();
        map_check_result = BuildTransitionElementsKindAndCompareMaps(
            object, object_map, access_info.transition_sources(),
            transition_target, &sub_graph, check_next_map);
      } else {
        map_check_result = BuildCompareMaps(
            object, object_map,
            base::VectorOf(access_info.lookup_start_object_maps()), &sub_graph,
            check_next_map);
      }
    }
    if (map_check_result.IsDoneWithAbort()) {
      // We know from known possible maps that this branch is not reachable,
      // so don't emit any code for it.
      continue;
    }
    MaybeReduceResult result;
    // TODO(victorgomes): Support RAB/GSAB backed typed arrays.
    if (IsRabGsabTypedArrayElementsKind(access_info.elements_kind())) {
      result = MaybeReduceResult::Fail();
    } else if (IsTypedArrayElementsKind(access_info.elements_kind())) {
      result = TryBuildElementAccessOnTypedArray(object, index_object,
                                                 access_info, keyed_mode);
    } else {
      result = TryBuildElementAccessOnJSArrayOrJSObject(
          object, index_object, access_info, keyed_mode);
    }
    switch (result.kind()) {
      case MaybeReduceResult::kDoneWithValue:
      case MaybeReduceResult::kDoneWithoutValue:
        DCHECK_EQ(result.HasValue(), !is_any_store);
        if (!done.has_value()) {
          // We initialize the label {done} lazily on the first possible path.
          // If no possible path exists, it is guaranteed that BuildCheckMaps
          // emitted an unconditional deopt and we return DoneWithAbort at the
          // end. We need one extra predecessor to jump from the generic case.
          const int possible_predecessors = access_info_count - i + 1;
          if (is_any_store) {
            done.emplace(&sub_graph, possible_predecessors);
          } else {
            ret_val.emplace(0);
            done.emplace(
                &sub_graph, possible_predecessors,
                std::initializer_list<MaglevSubGraphBuilder::Variable*>{
                    &*ret_val});
          }
        }
        if (!is_any_store) {
          sub_graph.set(*ret_val, result.value());
        }
        sub_graph.Goto(&*done);
        break;
      case MaybeReduceResult::kFail:
        if (!generic_access.has_value()) {
          // Conservatively assume that all remaining branches can go into the
          // generic path, as we have to initialize the predecessors upfront.
          // TODO(pthier): Find a better way to do that.
          generic_access.emplace(&sub_graph, access_info_count - i);
        }
        sub_graph.Goto(&*generic_access);
        break;
      case MaybeReduceResult::kDoneWithAbort:
        break;
    }
    if (check_next_map.has_value()) {
      sub_graph.Bind(&*check_next_map);
    }
  }
  if (generic_access.has_value() &&
      !sub_graph.TrimPredecessorsAndBind(&*generic_access).IsDoneWithAbort()) {
    MaybeReduceResult generic_result = build_generic_access();
    DCHECK(generic_result.IsDone());
    DCHECK_EQ(generic_result.IsDoneWithValue(), !is_any_store);
    if (!done.has_value()) {
      return is_any_store ? ReduceResult::Done() : generic_result.value();
    }
    if (!is_any_store) {
      sub_graph.set(*ret_val, generic_result.value());
    }
    sub_graph.Goto(&*done);
  }
  if (done.has_value()) {
    RETURN_IF_ABORT(sub_graph.TrimPredecessorsAndBind(&*done));
    return is_any_store ? ReduceResult::Done() : sub_graph.get(*ret_val);
  } else {
    return ReduceResult::DoneWithAbort();
  }
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::ElementAccessInfo::elements_kind(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::get(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Goto(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::IsAnyStore(), v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort(), v8::internal::maglev::MaybeReduceResult::IsDoneWithValue(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::IsTypedArrayElementsKind(), v8::internal::compiler::kLoad, v8::internal::HeapObject::kMapOffset, v8::internal::compiler::KeyedAccessMode::load_mode(), v8::internal::LoadModeHandlesOOB(), v8::internal::compiler::ElementAccessInfo::lookup_start_object_maps(), v8::base::internal::result, RETURN_IF_ABORT, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::set(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::ElementAccessInfo::transition_sources(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TrimPredecessorsAndBind(), v8::internal::maglev::MaybeReduceResult::value(), and v8::base::VectorOf().
TryBuildPolymorphicPropertyAccess()
template<typename GenericAccessFunc >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess (ValueNode * receiver, ValueNode * lookup_start_object, compiler::NamedAccessFeedback const & feedback, compiler::AccessMode access_mode, const ZoneVector< compiler::PropertyAccessInfo > & access_infos, GenericAccessFunc && build_generic_access) [private]
Definition at line 7036 of file maglev-graph-builder.cc.
                                              {
  const bool is_any_store = compiler::IsAnyStore(access_mode);
  const int access_info_count = static_cast<int>(access_infos.size());
  int number_map_index_for_smi = -1;
  bool needs_migration = false;
  bool has_deprecated_map_without_migration_target =
      feedback.has_deprecated_map_without_migration_target();
  for (int i = 0; i < access_info_count; i++) {
    compiler::PropertyAccessInfo const& access_info = access_infos[i];
    DCHECK(!access_info.IsInvalid());
    for (compiler::MapRef map : access_info.lookup_start_object_maps()) {
      if (map.is_migration_target()) {
        needs_migration = true;
      }
      if (map.IsHeapNumberMap()) {
        GetOrCreateInfoFor(lookup_start_object);
        base::SmallVector<compiler::MapRef, 1> known_maps = {map};
        KnownMapsMerger merger(broker(), zone(), base::VectorOf(known_maps));
        merger.IntersectWithKnownNodeAspects(lookup_start_object,
                                             known_node_aspects());
        if (!merger.intersect_set().is_empty() &&
            !IsEmptyNodeType(
                IntersectType(GetType(lookup_start_object), NodeType::kSmi))) {
          DCHECK_EQ(number_map_index_for_smi, -1);
          number_map_index_for_smi = i;
        }
      }
    }
  }
  // Stores don't return a value, so we don't need a variable for the result.
  MaglevSubGraphBuilder sub_graph(this, is_any_store ? 0 : 1);
  std::optional<MaglevSubGraphBuilder::Variable> ret_val;
  std::optional<MaglevSubGraphBuilder::Label> done;
  std::optional<MaglevSubGraphBuilder::Label> is_number;
  std::optional<MaglevSubGraphBuilder::Label> generic_access;
  if (number_map_index_for_smi >= 0) {
    is_number.emplace(&sub_graph, 2);
    sub_graph.GotoIfTrue<BranchIfSmi>(&*is_number, {lookup_start_object});
  } else {
    RETURN_IF_ABORT(BuildCheckHeapObject(lookup_start_object));
  }
  ValueNode* lookup_start_object_map =
      BuildLoadTaggedField(lookup_start_object, HeapObject::kMapOffset);
  if (needs_migration) {
    // TODO(marja, v8:7700): Try migrating only if all comparisons failed.
    // TODO(marja, v8:7700): Investigate making polymorphic map comparison (with
    // migration) a control node (like switch).
    lookup_start_object_map = AddNewNode<MigrateMapIfNeeded>(
        {lookup_start_object_map, lookup_start_object});
  }
  int start_offset = iterator_.current_offset();
  SourcePositionTableIterator::IndexAndPositionState
      start_source_position_iterator_state =
          source_position_iterator_.GetState();
  std::optional<ContinuationOffsets> continuation;
  if (!is_any_store && !in_peeled_iteration()) {
    // TODO(marja): enable continuations inside peeled iterations. Predecessor
    // tracking (decremented_predecessor_offsets_ etc) needs to be adapted to
    // make that work.
    continuation = FindContinuationForPolymorphicPropertyLoad();
  }
  for (int i = 0; i < access_info_count; i++) {
    // Reset the state before generating the next polymorphic arm, in case
    // FindContinuationForPolymorphicPropertyLoad or a continuation in the
    // previous arm changed it.
    iterator_.SetOffset(start_offset);
    source_position_iterator_.RestoreState(
        start_source_position_iterator_state);
    compiler::PropertyAccessInfo const& access_info = access_infos[i];
    std::optional<MaglevSubGraphBuilder::Label> check_next_map;
    MaybeReduceResult map_check_result;
    const auto& maps = access_info.lookup_start_object_maps();
    if (i == access_info_count - 1) {
      map_check_result = BuildCheckMaps(
          lookup_start_object, base::VectorOf(maps), {},
          has_deprecated_map_without_migration_target, needs_migration);
    } else {
      map_check_result =
          BuildCompareMaps(lookup_start_object, lookup_start_object_map,
                           base::VectorOf(maps), &sub_graph, check_next_map);
    }
    if (map_check_result.IsDoneWithAbort()) {
      DCHECK_NE(i, number_map_index_for_smi);
      // We know from known possible maps that this branch is not reachable,
      // so don't emit any code for it.
      if (continuation) {
        // Also don't generate any code for the continuation, just advance
        // through it.
        while (iterator_.current_offset() < continuation->last_continuation) {
          iterator_.Advance();
          UpdateSourceAndBytecodePosition(iterator_.current_offset());
        }
      }
      continue;
    }
    if (i == number_map_index_for_smi) {
      DCHECK(is_number.has_value());
      sub_graph.Goto(&*is_number);
      sub_graph.Bind(&*is_number);
    }
    MaybeReduceResult result;
    if (is_any_store) {
      result = TryBuildPropertyStore(receiver, lookup_start_object,
                                     feedback.name(), access_info, access_mode);
    } else {
      result = TryBuildPropertyLoad(receiver, lookup_start_object,
                                    feedback.name(), access_info);
    }
    switch (result.kind()) {
      case MaybeReduceResult::kDoneWithValue:
      case MaybeReduceResult::kDoneWithoutValue: {
        DCHECK_EQ(result.HasValue(), !is_any_store);
        if (!done.has_value()) {
          // We initialize the label {done} lazily on the first possible path.
          // If no possible path exists, it is guaranteed that BuildCheckMaps
          // emitted an unconditional deopt and we return DoneWithAbort at the
          // end. We need one extra predecessor to jump from the generic case.
          const int possible_predecessors = access_info_count - i + 1;
          if (is_any_store) {
            done.emplace(&sub_graph, possible_predecessors);
          } else {
            ret_val.emplace(0);
            done.emplace(
                &sub_graph, possible_predecessors,
                std::initializer_list<MaglevSubGraphBuilder::Variable*>{
                    &*ret_val});
          }
        }
#ifdef DEBUG
        int predecessor_count_for_offset_after_continuation =
            continuation ? predecessor_count_[continuation->after_continuation]
                         : 0;
#endif
        if (!is_any_store) {
          if (continuation) {
            // Generate code for further bytecodes inside the polymorphic
            // branch.
            // First save the result of the property load in the accumulator.
            SetAccumulator(result.value());
            BuildContinuationForPolymorphicPropertyLoad(*continuation);
            // The continuation stored its value into the accumulator. Take that
            // value as our value.
            sub_graph.set(*ret_val,
                          current_interpreter_frame_.get(
                              interpreter::Register::virtual_accumulator()));
          } else {
            sub_graph.set(*ret_val, result.value());
          }
        }
        if (current_block_) {
          sub_graph.Goto(&*done);
#ifdef DEBUG
          if (continuation) {
            DCHECK_EQ(predecessor_count_[continuation->after_continuation],
                      predecessor_count_for_offset_after_continuation);
          }
#endif
        } else {
          // The continuation is dead. Marking it dead decreased the predecessor
          // count of continuation->after_continuation. Correct for that.
#ifdef DEBUG
          DCHECK_EQ(predecessor_count_[continuation->after_continuation],
                    predecessor_count_for_offset_after_continuation - 1);
#endif
          ++predecessor_count_[continuation->after_continuation];
        }
        break;
      }
      case MaybeReduceResult::kDoneWithAbort:
        break;
      case MaybeReduceResult::kFail:
        if (!generic_access.has_value()) {
          // Conservatively assume that all remaining branches can go into the
          // generic path, as we have to initialize the predecessors upfront.
          // TODO(pthier): Find a better way to do that.
          generic_access.emplace(&sub_graph, access_info_count - i);
        }
        sub_graph.Goto(&*generic_access);
        break;
      default:
        UNREACHABLE();
    }
    if (check_next_map.has_value()) {
      sub_graph.Bind(&*check_next_map);
    }
  }
  if (generic_access.has_value() &&
      !sub_graph.TrimPredecessorsAndBind(&*generic_access).IsDoneWithAbort()) {
    MaybeReduceResult generic_result = build_generic_access();
    DCHECK(generic_result.IsDone());
    DCHECK_EQ(generic_result.IsDoneWithValue(), !is_any_store);
    if (continuation) {
      DCHECK(!is_any_store);
      SetAccumulator(generic_result.value());
      BuildContinuationForPolymorphicPropertyLoad(*continuation);
      if (!done.has_value()) {
        return current_interpreter_frame_.get(
            interpreter::Register::virtual_accumulator());
      }
      sub_graph.set(*ret_val,
                    current_interpreter_frame_.get(
                        interpreter::Register::virtual_accumulator()));
    } else {
      if (!done.has_value()) {
        return is_any_store ? ReduceResult::Done() : generic_result.value();
      }
      if (!is_any_store) {
        sub_graph.set(*ret_val, generic_result.value());
      }
    }
    sub_graph.Goto(&*done);
  }
  if (done.has_value()) {
    if (continuation) {
      DCHECK_EQ(iterator_.current_offset(), continuation->last_continuation);
    }
    RETURN_IF_ABORT(sub_graph.TrimPredecessorsAndBind(&*done));
    return is_any_store ? ReduceResult::Done() : sub_graph.get(*ret_val);
  } else {
    iterator_.SetOffset(start_offset);
    source_position_iterator_.RestoreState(
        start_source_position_iterator_state);
    return ReduceResult::DoneWithAbort();
  }
}
References v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), broker(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::get(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Goto(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue(), v8::internal::compiler::NamedAccessFeedback::has_deprecated_map_without_migration_target(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::IntersectType(), v8::internal::compiler::IsAnyStore(), v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort(), v8::internal::maglev::MaybeReduceResult::IsDoneWithValue(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::compiler::PropertyAccessInfo::IsInvalid(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kSmi, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::NamedAccessFeedback::name(), v8::base::internal::result, RETURN_IF_ABORT, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::set(), v8::internal::ZoneVector< T >::size(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::TrimPredecessorsAndBind(), v8::internal::UNREACHABLE(), v8::internal::maglev::MaybeReduceResult::value(), v8::base::VectorOf(), and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by TryBuildNamedAccess().
TryBuildPropertyAccess()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyAccess (ValueNode * receiver, ValueNode * lookup_start_object, compiler::NameRef name, compiler::PropertyAccessInfo const & access_info, compiler::AccessMode access_mode) [private]
Definition at line 5901 of file maglev-graph-builder.cc.
                                    {
  switch (access_mode) {
    case compiler::AccessMode::kLoad:
      return TryBuildPropertyLoad(receiver, lookup_start_object, name,
                                  access_info);
    case compiler::AccessMode::kStore:
    case compiler::AccessMode::kStoreInLiteral:
    case compiler::AccessMode::kDefine:
      DCHECK_EQ(receiver, lookup_start_object);
      return TryBuildPropertyStore(receiver, lookup_start_object, name,
                                   access_info, access_mode);
    case compiler::AccessMode::kHas:
      // TODO(victorgomes): BuildPropertyTest.
      return {};
  }
}
References DCHECK_EQ, v8::internal::compiler::kDefine, v8::internal::compiler::kHas, v8::internal::compiler::kLoad, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::name, TryBuildPropertyLoad(), and TryBuildPropertyStore().
Referenced by TryBuildNamedAccess().
TryBuildPropertyCellLoad()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4218 of file maglev-graph-builder.cc.
                                                                {
  // TODO(leszeks): A bunch of this is copied from
  // js-native-context-specialization.cc -- I wonder if we can unify it
  // somehow.
  DCHECK(global_access_feedback.IsPropertyCell());
  compiler::PropertyCellRef property_cell =
      global_access_feedback.property_cell();
  if (!property_cell.Cache(broker())) return {};
  compiler::ObjectRef property_cell_value = property_cell.value(broker());
  if (property_cell_value.IsPropertyCellHole()) {
    // The property cell is no longer valid.
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kInsufficientTypeFeedbackForGenericNamedAccess);
  }
  PropertyDetails property_details = property_cell.property_details();
  PropertyCellType property_cell_type = property_details.cell_type();
  DCHECK_EQ(PropertyKind::kData, property_details.kind());
  if (!property_details.IsConfigurable() && property_details.IsReadOnly()) {
    return GetConstant(property_cell_value);
  }
  // Record a code dependency on the cell if we can benefit from the
  // additional feedback, or the global property is configurable (i.e.
  // can be deleted or reconfigured to an accessor property).
  if (property_cell_type != PropertyCellType::kMutable ||
      property_details.IsConfigurable()) {
    broker()->dependencies()->DependOnGlobalProperty(property_cell);
  }
  // Load from constant/undefined global property can be constant-folded.
  if (property_cell_type == PropertyCellType::kConstant ||
      property_cell_type == PropertyCellType::kUndefined) {
    return GetConstant(property_cell_value);
  }
  ValueNode* property_cell_node = GetConstant(property_cell.AsHeapObject());
  return BuildLoadTaggedField(property_cell_node, PropertyCell::kValueOffset);
}
References broker(), BuildLoadTaggedField(), v8::internal::compiler::PropertyCellRef::Cache(), v8::internal::PropertyDetails::cell_type(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty(), EmitUnconditionalDeopt(), GetConstant(), v8::internal::PropertyDetails::IsConfigurable(), v8::internal::compiler::GlobalAccessFeedback::IsPropertyCell(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::kConstant, v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::kMutable, v8::internal::kUndefined, v8::internal::compiler::GlobalAccessFeedback::property_cell(), v8::internal::compiler::PropertyCellRef::property_details(), and v8::internal::compiler::PropertyCellRef::value().
Referenced by TryBuildGlobalLoad().
TryBuildPropertyCellStore()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4116 of file maglev-graph-builder.cc.
                                                                {
  DCHECK(global_access_feedback.IsPropertyCell());
  compiler::PropertyCellRef property_cell =
      global_access_feedback.property_cell();
  if (!property_cell.Cache(broker())) return {};
  compiler::ObjectRef property_cell_value = property_cell.value(broker());
  if (property_cell_value.IsPropertyCellHole()) {
    // The property cell is no longer valid.
    return EmitUnconditionalDeopt(
        DeoptimizeReason::kInsufficientTypeFeedbackForGenericNamedAccess);
  }
  PropertyDetails property_details = property_cell.property_details();
  DCHECK_EQ(PropertyKind::kData, property_details.kind());
  if (property_details.IsReadOnly()) {
    // Don't even bother trying to lower stores to read-only data
    // properties.
    // TODO(neis): We could generate code that checks if the new value
    // equals the old one and then does nothing or deopts, respectively.
    return {};
  }
  switch (property_details.cell_type()) {
    case PropertyCellType::kUndefined:
      return {};
    case PropertyCellType::kConstant: {
      // Record a code dependency on the cell, and just deoptimize if the new
      // value doesn't match the previous value stored inside the cell.
      broker()->dependencies()->DependOnGlobalProperty(property_cell);
      ValueNode* value = GetAccumulator();
      return BuildCheckNumericalValueOrByReference(
          value, property_cell_value, DeoptimizeReason::kStoreToConstant);
    }
    case PropertyCellType::kConstantType: {
      // We rely on stability further below.
      if (property_cell_value.IsHeapObject() &&
          !property_cell_value.AsHeapObject().map(broker()).is_stable()) {
        return {};
      }
      // Record a code dependency on the cell, and just deoptimize if the new
      // value's type doesn't match the type of the previous value in the cell.
      broker()->dependencies()->DependOnGlobalProperty(property_cell);
      ValueNode* value = GetAccumulator();
      if (property_cell_value.IsHeapObject()) {
        compiler::MapRef property_cell_value_map =
            property_cell_value.AsHeapObject().map(broker());
        broker()->dependencies()->DependOnStableMap(property_cell_value_map);
        RETURN_IF_ABORT(BuildCheckHeapObject(value));
        RETURN_IF_ABORT(
            BuildCheckMaps(value, base::VectorOf({property_cell_value_map})));
      } else {
        RETURN_IF_ABORT(GetSmiValue(value));
      }
      ValueNode* property_cell_node = GetConstant(property_cell.AsHeapObject());
      BuildStoreTaggedField(property_cell_node, value,
                            PropertyCell::kValueOffset,
                            StoreTaggedMode::kDefault);
      break;
    }
    case PropertyCellType::kMutable: {
      // Record a code dependency on the cell, and just deoptimize if the
      // property ever becomes read-only.
      broker()->dependencies()->DependOnGlobalProperty(property_cell);
      ValueNode* property_cell_node = GetConstant(property_cell.AsHeapObject());
      BuildStoreTaggedField(property_cell_node, GetAccumulator(),
                            PropertyCell::kValueOffset,
                            StoreTaggedMode::kDefault);
      break;
    }
    case PropertyCellType::kInTransition:
      UNREACHABLE();
  }
  return ReduceResult::Done();
}
References broker(), BuildCheckHeapObject(), BuildCheckMaps(), BuildCheckNumericalValueOrByReference(), BuildStoreTaggedField(), v8::internal::compiler::PropertyCellRef::Cache(), v8::internal::PropertyDetails::cell_type(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), GetAccumulator(), GetConstant(), GetSmiValue(), v8::internal::compiler::GlobalAccessFeedback::IsPropertyCell(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::kConstant, v8::internal::kConstantType, v8::internal::kData, v8::internal::maglev::kDefault, v8::internal::PropertyDetails::kind(), v8::internal::kInTransition, v8::internal::kMutable, v8::internal::kUndefined, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::GlobalAccessFeedback::property_cell(), v8::internal::compiler::PropertyCellRef::property_details(), RETURN_IF_ABORT, v8::internal::UNREACHABLE(), v8::internal::compiler::PropertyCellRef::value(), v8::internal::value, and v8::base::VectorOf().
Referenced by TryBuildGlobalStore().
TryBuildPropertyGetterCall()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall (compiler::PropertyAccessInfo const & access_info, ValueNode * receiver, ValueNode * lookup_start_object) [private]
Definition at line 5481 of file maglev-graph-builder.cc.
                                    {
  compiler::ObjectRef constant = access_info.constant().value();
  if (access_info.IsDictionaryProtoAccessorConstant()) {
    // For fast mode holders we recorded dependencies in BuildPropertyLoad.
    for (const compiler::MapRef map : access_info.lookup_start_object_maps()) {
      broker()->dependencies()->DependOnConstantInDictionaryPrototypeChain(
          map, access_info.name(), constant, PropertyKind::kAccessor);
    }
  }
  // Introduce the call to the getter function.
  if (constant.IsJSFunction()) {
    ConvertReceiverMode receiver_mode =
        receiver == lookup_start_object
            ? ConvertReceiverMode::kNotNullOrUndefined
            : ConvertReceiverMode::kAny;
    CallArguments args(receiver_mode, {receiver});
    return TryReduceCallForConstant(constant.AsJSFunction(), args);
  } else {
    // Disable optimizations for super ICs using API getters, so that we get
    // the correct receiver checks.
    if (receiver != lookup_start_object) return {};
    compiler::FunctionTemplateInfoRef templ = constant.AsFunctionTemplateInfo();
    CallArguments args(ConvertReceiverMode::kNotNullOrUndefined, {receiver});
    return TryReduceCallForApiFunction(templ, {}, args);
  }
}
References v8::base::args, broker(), v8::internal::compiler::PropertyAccessInfo::constant(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnConstantInDictionaryPrototypeChain(), v8::internal::compiler::PropertyAccessInfo::IsDictionaryProtoAccessorConstant(), v8::internal::kAccessor, v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::PropertyAccessInfo::name(), TryReduceCallForApiFunction(), and TryReduceCallForConstant().
Referenced by TryBuildPropertyLoad().
TryBuildPropertyLoad()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad (ValueNode * receiver, ValueNode * lookup_start_object, compiler::NameRef name, compiler::PropertyAccessInfo const & access_info) [private]
Definition at line 5794 of file maglev-graph-builder.cc.
                                                   {
  if (access_info.holder().has_value() && !access_info.HasDictionaryHolder()) {
    broker()->dependencies()->DependOnStablePrototypeChains(
        access_info.lookup_start_object_maps(), kStartAtPrototype,
        access_info.holder().value());
  }
  switch (access_info.kind()) {
    case compiler::PropertyAccessInfo::kInvalid:
      UNREACHABLE();
    case compiler::PropertyAccessInfo::kNotFound:
      return GetRootConstant(RootIndex::kUndefinedValue);
    case compiler::PropertyAccessInfo::kDataField:
    case compiler::PropertyAccessInfo::kFastDataConstant: {
      ValueNode* result =
          BuildLoadField(access_info, lookup_start_object, name);
      RecordKnownProperty(lookup_start_object, name, result,
                          AccessInfoGuaranteedConst(access_info),
                          compiler::AccessMode::kLoad);
      return result;
    }
    case compiler::PropertyAccessInfo::kDictionaryProtoDataConstant: {
      compiler::OptionalObjectRef constant =
          TryFoldLoadDictPrototypeConstant(access_info);
      if (!constant.has_value()) return {};
      return GetConstant(constant.value());
    }
    case compiler::PropertyAccessInfo::kFastAccessorConstant:
    case compiler::PropertyAccessInfo::kDictionaryProtoAccessorConstant:
      return TryBuildPropertyGetterCall(access_info, receiver,
                                        lookup_start_object);
    case compiler::PropertyAccessInfo::kModuleExport: {
      ValueNode* cell = GetConstant(access_info.constant().value().AsCell());
      return BuildLoadTaggedField<LoadTaggedFieldForProperty>(
          cell, Cell::kValueOffset, name);
    }
    case compiler::PropertyAccessInfo::kStringLength: {
      DCHECK_EQ(receiver, lookup_start_object);
      ValueNode* result = BuildLoadStringLength(receiver);
      RecordKnownProperty(lookup_start_object, name, result,
                          AccessInfoGuaranteedConst(access_info),
                          compiler::AccessMode::kLoad);
      return result;
    }
    case compiler::PropertyAccessInfo::kStringWrapperLength: {
      // TODO(dmercadier): update KnownNodeInfo.
      ValueNode* string = BuildLoadTaggedField(
          lookup_start_object, JSPrimitiveWrapper::kValueOffset);
      return AddNewNode<StringLength>({string});
    }
    case compiler::PropertyAccessInfo::kTypedArrayLength: {
      CHECK(!IsRabGsabTypedArrayElementsKind(access_info.elements_kind()));
      if (receiver != lookup_start_object) {
        // We're accessing the TypedArray length via a prototype (a TypedArray
        // object in the prototype chain, objects below it not having a "length"
        // property, reading via super.length). That will throw a TypeError.
        // This should never occur in any realistic code, so we can deopt here
        // instead of implementing special handling for it.
        return EmitUnconditionalDeopt(DeoptimizeReason::kWrongMap);
      }
      return BuildLoadTypedArrayLength(lookup_start_object,
                                       access_info.elements_kind());
    }
  }
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AccessInfoGuaranteedConst(), broker(), BuildLoadField(), BuildLoadStringLength(), BuildLoadTaggedField(), BuildLoadTypedArrayLength(), CHECK, v8::internal::compiler::PropertyAccessInfo::constant(), DCHECK_EQ, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChains(), v8::internal::compiler::PropertyAccessInfo::elements_kind(), EmitUnconditionalDeopt(), GetConstant(), GetRootConstant(), v8::internal::compiler::PropertyAccessInfo::HasDictionaryHolder(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::compiler::PropertyAccessInfo::kDataField, v8::internal::compiler::PropertyAccessInfo::kDictionaryProtoAccessorConstant, v8::internal::compiler::PropertyAccessInfo::kDictionaryProtoDataConstant, v8::internal::compiler::PropertyAccessInfo::kFastAccessorConstant, v8::internal::compiler::PropertyAccessInfo::kFastDataConstant, v8::internal::compiler::PropertyAccessInfo::kind(), v8::internal::compiler::PropertyAccessInfo::kInvalid, v8::internal::compiler::kLoad, v8::internal::compiler::PropertyAccessInfo::kModuleExport, v8::internal::compiler::PropertyAccessInfo::kNotFound, v8::internal::kStartAtPrototype, v8::internal::compiler::PropertyAccessInfo::kStringLength, v8::internal::compiler::PropertyAccessInfo::kStringWrapperLength, v8::internal::compiler::PropertyAccessInfo::kTypedArrayLength, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::name, RecordKnownProperty(), v8::base::internal::result, TryBuildPropertyGetterCall(), TryFoldLoadDictPrototypeConstant(), and v8::internal::UNREACHABLE().
Referenced by TryBuildPropertyAccess().
TryBuildPropertySetterCall()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertySetterCall (compiler::PropertyAccessInfo const & access_info, ValueNode * receiver, ValueNode * lookup_start_object, ValueNode * value) [private]
Definition at line 5513 of file maglev-graph-builder.cc.
                                                      {
  // Setting super properties shouldn't end up here.
  DCHECK_EQ(receiver, lookup_start_object);
  compiler::ObjectRef constant = access_info.constant().value();
  if (constant.IsJSFunction()) {
    CallArguments args(ConvertReceiverMode::kNotNullOrUndefined,
                       {receiver, value});
    RETURN_IF_ABORT(TryReduceCallForConstant(constant.AsJSFunction(), args));
  } else {
    compiler::FunctionTemplateInfoRef templ = constant.AsFunctionTemplateInfo();
    CallArguments args(ConvertReceiverMode::kNotNullOrUndefined,
                       {receiver, value});
    RETURN_IF_ABORT(TryReduceCallForApiFunction(templ, {}, args));
  }
  // Ignore the return value of the setter call.
  return ReduceResult::Done();
}
References v8::base::args, v8::internal::compiler::PropertyAccessInfo::constant(), DCHECK_EQ, v8::internal::maglev::ReduceResult::Done(), v8::internal::kNotNullOrUndefined, RETURN_IF_ABORT, TryReduceCallForApiFunction(), TryReduceCallForConstant(), and v8::internal::value.
Referenced by TryBuildPropertyStore().
TryBuildPropertyStore()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore (ValueNode * receiver, ValueNode * lookup_start_object, compiler::NameRef name, compiler::PropertyAccessInfo const & access_info, compiler::AccessMode access_mode) [private]
Definition at line 5862 of file maglev-graph-builder.cc.
                                    {
  if (access_info.holder().has_value()) {
    broker()->dependencies()->DependOnStablePrototypeChains(
        access_info.lookup_start_object_maps(), kStartAtPrototype,
        access_info.holder().value());
  }
  switch (access_info.kind()) {
    case compiler::PropertyAccessInfo::kFastAccessorConstant: {
      return TryBuildPropertySetterCall(access_info, receiver,
                                        lookup_start_object, GetAccumulator());
    }
    case compiler::PropertyAccessInfo::kDataField:
    case compiler::PropertyAccessInfo::kFastDataConstant: {
      MaybeReduceResult res =
          TryBuildStoreField(access_info, receiver, access_mode);
      if (res.IsDone()) {
        RecordKnownProperty(
            receiver, name, current_interpreter_frame_.accumulator(),
            AccessInfoGuaranteedConst(access_info), access_mode);
        return res;
      }
      return {};
    }
    case compiler::PropertyAccessInfo::kInvalid:
    case compiler::PropertyAccessInfo::kNotFound:
    case compiler::PropertyAccessInfo::kDictionaryProtoDataConstant:
    case compiler::PropertyAccessInfo::kDictionaryProtoAccessorConstant:
    case compiler::PropertyAccessInfo::kModuleExport:
    case compiler::PropertyAccessInfo::kStringLength:
    case compiler::PropertyAccessInfo::kStringWrapperLength:
    case compiler::PropertyAccessInfo::kTypedArrayLength:
      UNREACHABLE();
  }
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AccessInfoGuaranteedConst(), v8::internal::maglev::InterpreterFrameState::accumulator(), broker(), current_interpreter_frame_, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChains(), GetAccumulator(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::maglev::MaybeReduceResult::IsDone(), v8::internal::compiler::PropertyAccessInfo::kDataField, v8::internal::compiler::PropertyAccessInfo::kDictionaryProtoAccessorConstant, v8::internal::compiler::PropertyAccessInfo::kDictionaryProtoDataConstant, v8::internal::compiler::PropertyAccessInfo::kFastAccessorConstant, v8::internal::compiler::PropertyAccessInfo::kFastDataConstant, v8::internal::compiler::PropertyAccessInfo::kind(), v8::internal::compiler::PropertyAccessInfo::kInvalid, v8::internal::compiler::PropertyAccessInfo::kModuleExport, v8::internal::compiler::PropertyAccessInfo::kNotFound, v8::internal::kStartAtPrototype, v8::internal::compiler::PropertyAccessInfo::kStringLength, v8::internal::compiler::PropertyAccessInfo::kStringWrapperLength, v8::internal::compiler::PropertyAccessInfo::kTypedArrayLength, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::name, RecordKnownProperty(), TryBuildPropertySetterCall(), TryBuildStoreField(), and v8::internal::UNREACHABLE().
Referenced by TryBuildPropertyAccess().
TryBuildScriptContextConstantLoad()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextConstantLoad (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4195 of file maglev-graph-builder.cc.
                                                                {
  DCHECK(global_access_feedback.IsScriptContextSlot());
  if (!global_access_feedback.immutable()) return {};
  compiler::OptionalObjectRef maybe_slot_value =
      global_access_feedback.script_context().get(
          broker(), global_access_feedback.slot_index());
  if (!maybe_slot_value) return {};
  return GetConstant(maybe_slot_value.value());
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::ContextRef::get(), GetConstant(), v8::internal::compiler::GlobalAccessFeedback::immutable(), v8::internal::compiler::GlobalAccessFeedback::IsScriptContextSlot(), v8::internal::compiler::GlobalAccessFeedback::script_context(), and v8::internal::compiler::GlobalAccessFeedback::slot_index().
Referenced by TryBuildScriptContextLoad().
TryBuildScriptContextLoad()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextLoad (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4206 of file maglev-graph-builder.cc.
                                                                {
  DCHECK(global_access_feedback.IsScriptContextSlot());
  RETURN_IF_DONE(TryBuildScriptContextConstantLoad(global_access_feedback));
  auto script_context = GetConstant(global_access_feedback.script_context());
  ContextSlotMutability mutability =
      global_access_feedback.immutable() ? kImmutable : kMutable;
  return LoadAndCacheContextSlot(script_context,
                                 global_access_feedback.slot_index(),
                                 mutability, ContextMode::kHasContextCells);
}
References v8::internal::DCHECK(), GetConstant(), v8::internal::compiler::GlobalAccessFeedback::immutable(), v8::internal::compiler::GlobalAccessFeedback::IsScriptContextSlot(), v8::internal::kHasContextCells, kImmutable, kMutable, LoadAndCacheContextSlot(), RETURN_IF_DONE, v8::internal::compiler::GlobalAccessFeedback::script_context(), v8::internal::compiler::GlobalAccessFeedback::slot_index(), and TryBuildScriptContextConstantLoad().
Referenced by TryBuildGlobalLoad().
TryBuildScriptContextStore()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextStore (const compiler::GlobalAccessFeedback & global_access_feedback) [private]
Definition at line 4106 of file maglev-graph-builder.cc.
                                                                {
  DCHECK(global_access_feedback.IsScriptContextSlot());
  if (global_access_feedback.immutable()) return {};
  auto script_context = GetConstant(global_access_feedback.script_context());
  return StoreAndCacheContextSlot(
      script_context, global_access_feedback.slot_index(), GetAccumulator(),
      ContextMode::kHasContextCells);
}
References v8::internal::DCHECK(), GetAccumulator(), GetConstant(), v8::internal::compiler::GlobalAccessFeedback::immutable(), v8::internal::compiler::GlobalAccessFeedback::IsScriptContextSlot(), v8::internal::kHasContextCells, v8::internal::compiler::GlobalAccessFeedback::script_context(), v8::internal::compiler::GlobalAccessFeedback::slot_index(), and StoreAndCacheContextSlot().
Referenced by TryBuildGlobalStore().
TryBuildStoreDataView()
template<typename StoreNode , typename Function >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreDataView (const CallArguments & args, ExternalArrayType type, Function && getValue) [private]
Definition at line 9696 of file maglev-graph-builder.cc.
                                                                            {
  if (!CanSpeculateCall()) return {};
  if (!broker()->dependencies()->DependOnArrayBufferDetachingProtector()) {
    // TODO(victorgomes): Add checks whether the array has been detached.
    return {};
  }
  // TODO(victorgomes): Add data view to known types.
  ValueNode* receiver = GetValueOrUndefined(args.receiver());
  AddNewNode<CheckInstanceType>({receiver}, CheckType::kCheckHeapObject,
                                JS_DATA_VIEW_TYPE, JS_DATA_VIEW_TYPE);
  // TODO(v8:11111): Optimize for JS_RAB_GSAB_DATA_VIEW_TYPE too.
  ValueNode* offset =
      args[0] ? GetInt32ElementIndex(args[0]) : GetInt32Constant(0);
  AddNewNode<CheckJSDataViewBounds>({receiver, offset},
                                    ExternalArrayType::kExternalFloat64Array);
  ValueNode* value = getValue(args[1]);
  ValueNode* is_little_endian = args[2] ? args[2] : GetBooleanConstant(false);
  AddNewNode<StoreNode>({receiver, offset, value, is_little_endian}, type);
  return GetRootConstant(RootIndex::kUndefinedValue);
}
References v8::base::args, broker(), v8::internal::kExternalFloat64Array, v8::internal::tracing::type, and v8::internal::value.
TryBuildStoreField()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField (compiler::PropertyAccessInfo const & access_info, ValueNode * receiver, compiler::AccessMode access_mode) [private]
Definition at line 5674 of file maglev-graph-builder.cc.
                                    {
  FieldIndex field_index = access_info.field_index();
  Representation field_representation = access_info.field_representation();
  compiler::OptionalMapRef original_map;
  if (access_info.HasTransitionMap()) {
    compiler::MapRef transition = access_info.transition_map().value();
    original_map = transition.GetBackPointer(broker()).AsMap();
    if (original_map->UnusedPropertyFields() == 0) {
      DCHECK(!field_index.is_inobject());
    }
    if (!field_index.is_inobject()) {
      // If slack tracking ends after this compilation started but before it's
      // finished, then {original_map} could be out-of-sync with {transition}.
      // In particular, its UnusedPropertyFields could be non-zero, which would
      // lead us to not extend the property backing store, while the underlying
      // Map has actually zero UnusedPropertyFields. Thus, we install a
      // dependency on {orininal_map} now, so that if such a situation happens,
      // we'll throw away the code.
      broker()->dependencies()->DependOnNoSlackTrackingChange(*original_map);
    }
  } else if (access_info.IsFastDataConstant() &&
             access_mode == compiler::AccessMode::kStore) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kStoreToConstant);
  }
  ValueNode* value = GetAccumulator();
  if (IsEmptyNodeType(GetType(value))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongValue);
  }
  if (field_representation.IsSmi()) {
    RETURN_IF_ABORT(GetAccumulatorSmi());
  } else {
    if (field_representation.IsHeapObject()) {
      // Emit a map check for the field type, if needed, otherwise just a
      // HeapObject check.
      if (access_info.field_map().has_value()) {
        RETURN_IF_ABORT(BuildCheckMaps(
            value, base::VectorOf({access_info.field_map().value()})));
      } else {
        RETURN_IF_ABORT(BuildCheckHeapObject(value));
      }
    }
  }
  ValueNode* store_target;
  if (field_index.is_inobject()) {
    store_target = receiver;
  } else {
    // The field is in the property array, first load it from there.
    store_target =
        BuildLoadTaggedField(receiver, JSReceiver::kPropertiesOrHashOffset);
    if (original_map && original_map->UnusedPropertyFields() == 0) {
      store_target = BuildExtendPropertiesBackingStore(*original_map, receiver,
                                                       store_target);
    }
  }
  if (field_representation.IsDouble()) {
    if (access_info.HasTransitionMap()) {
      // Allocate the mutable double box owned by the field.
      ValueNode* heapnumber_value =
          AddNewNode<Float64ToHeapNumberForField>({value});
      BuildStoreTaggedField(store_target, heapnumber_value,
                            field_index.offset(),
                            StoreTaggedMode::kTransitioning);
      BuildStoreMap(receiver, access_info.transition_map().value(),
                    StoreMap::Kind::kTransitioning);
    } else {
      AddNewNode<StoreDoubleField>({store_target, value}, field_index.offset());
    }
    return ReduceResult::Done();
  }
  StoreTaggedMode store_mode = access_info.HasTransitionMap()
                                   ? StoreTaggedMode::kTransitioning
                                   : StoreTaggedMode::kDefault;
  if (field_representation.IsSmi()) {
    BuildStoreTaggedFieldNoWriteBarrier(store_target, value,
                                        field_index.offset(), store_mode);
  } else {
    DCHECK(field_representation.IsHeapObject() ||
           field_representation.IsTagged());
    BuildStoreTaggedField(store_target, value, field_index.offset(),
                          store_mode);
  }
  if (access_info.HasTransitionMap()) {
    BuildStoreMap(receiver, access_info.transition_map().value(),
                  StoreMap::Kind::kTransitioning);
  }
  return ReduceResult::Done();
}
References broker(), BuildCheckHeapObject(), BuildCheckMaps(), BuildExtendPropertiesBackingStore(), BuildLoadTaggedField(), BuildStoreMap(), BuildStoreTaggedField(), BuildStoreTaggedFieldNoWriteBarrier(), v8::internal::DCHECK(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnNoSlackTrackingChange(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_map(), v8::internal::compiler::PropertyAccessInfo::field_representation(), GetAccumulator(), GetAccumulatorSmi(), v8::internal::compiler::MapRef::GetBackPointer(), GetType(), v8::internal::compiler::PropertyAccessInfo::HasTransitionMap(), v8::internal::FieldIndex::is_inobject(), v8::internal::Representation::IsDouble(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), v8::internal::Representation::IsHeapObject(), v8::internal::Representation::IsSmi(), v8::internal::Representation::IsTagged(), v8::internal::maglev::kDefault, v8::internal::compiler::kStore, v8::internal::maglev::kTransitioning, v8::internal::maglev::StoreMap::kTransitioning, v8::internal::FieldIndex::offset(), RETURN_IF_ABORT, v8::internal::compiler::PropertyAccessInfo::transition_map(), v8::internal::value, and v8::base::VectorOf().
Referenced by TryBuildPropertyStore().
TryBuildStoreTaggedFieldToAllocation()
void v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreTaggedFieldToAllocation (ValueNode * object, ValueNode * value, int offset) [private]
Definition at line 5213 of file maglev-graph-builder.cc.
                                                                          {
  if (offset == HeapObject::kMapOffset) return;
  if (!CanTrackObjectChanges(object, TrackObjectMode::kStore)) return;
  // This avoids loop in the object graph.
  if (value->Is<InlinedAllocation>()) return;
  InlinedAllocation* allocation = object->Cast<InlinedAllocation>();
  VirtualObject* vobject = GetModifiableObjectFromAllocation(allocation);
  CHECK_EQ(vobject->type(), VirtualObject::kDefault);
  CHECK_NOT_NULL(vobject);
  vobject->set(offset, value);
  AddNonEscapingUses(allocation, 1);
  if (v8_flags.trace_maglev_object_tracking) {
    std::cout << " * Setting value in virtual object "
              << PrintNodeLabel(graph_labeller(), vobject) << "[" << offset
              << "]: " << PrintNode(graph_labeller(), value) << std::endl;
  }
}
References AddNonEscapingUses(), CanTrackObjectChanges(), CHECK_EQ, CHECK_NOT_NULL, GetModifiableObjectFromAllocation(), graph_labeller(), v8::internal::maglev::VirtualObject::kDefault, v8::internal::HeapObject::kMapOffset, kStore, v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::v8_flags, and v8::internal::value.
Referenced by BuildStoreTaggedField(), and BuildStoreTaggedFieldNoWriteBarrier().
TryFoldFloat64BinaryOperationForToNumber() [1/2]
template<Operation kOperation>
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryFoldFloat64BinaryOperationForToNumber (TaggedToFloat64ConversionType conversion_type, ValueNode * left, double cst_right) [private]
Definition at line 2546 of file maglev-graph-builder.cc.
                      {
  auto cst_left = TryGetFloat64Constant(left, conversion_type);
  if (!cst_left.has_value()) return {};
  switch (kOperation) {
    case Operation::kAdd:
      return GetNumberConstant(cst_left.value() + cst_right);
    case Operation::kSubtract:
      return GetNumberConstant(cst_left.value() - cst_right);
    case Operation::kMultiply:
      return GetNumberConstant(cst_left.value() * cst_right);
    case Operation::kDivide:
      return GetNumberConstant(cst_left.value() / cst_right);
    case Operation::kModulus:
      // TODO(v8:7700): Constant fold mod.
      return {};
    case Operation::kExponentiate:
      return GetNumberConstant(math::pow(cst_left.value(), cst_right));
    default:
      UNREACHABLE();
  }
}
References GetNumberConstant(), v8::kOperation, v8::internal::math::pow(), TryGetFloat64Constant(), and v8::internal::UNREACHABLE().
TryFoldFloat64BinaryOperationForToNumber() [2/2]
template<Operation kOperation>
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryFoldFloat64BinaryOperationForToNumber (TaggedToFloat64ConversionType conversion_type, ValueNode * left, ValueNode * right) [private]
Definition at line 2536 of file maglev-graph-builder.cc.
                      {
  auto cst_right = TryGetFloat64Constant(right, conversion_type);
  if (!cst_right.has_value()) return {};
  return TryFoldFloat64BinaryOperationForToNumber<kOperation>(
      conversion_type, left, cst_right.value());
}
References TryGetFloat64Constant().
TryFoldFloat64UnaryOperationForToNumber()
template<Operation kOperation>
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryFoldFloat64UnaryOperationForToNumber (TaggedToFloat64ConversionType conversion_type, ValueNode * value) [private]
Definition at line 2519 of file maglev-graph-builder.cc.
                                                                     {
  auto cst = TryGetFloat64Constant(value, conversion_type);
  if (!cst.has_value()) return {};
  switch (kOperation) {
    case Operation::kNegate:
      return GetNumberConstant(-cst.value());
    case Operation::kIncrement:
      return GetNumberConstant(cst.value() + 1);
    case Operation::kDecrement:
      return GetNumberConstant(cst.value() - 1);
    default:
      UNREACHABLE();
  }
}
References GetNumberConstant(), v8::kOperation, TryGetFloat64Constant(), v8::internal::UNREACHABLE(), and v8::internal::value.
TryFoldInt32BinaryOperation() [1/2]
template<Operation kOperation>
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryFoldInt32BinaryOperation (ValueNode * left, int32_t cst_right) [private]
Definition at line 2368 of file maglev-graph-builder.cc.
                                        {
  auto cst_left = TryGetInt32Constant(left);
  if (!cst_left.has_value()) return {};
  switch (kOperation) {
    case Operation::kAdd: {
      int64_t result = static_cast<int64_t>(cst_left.value()) +
                       static_cast<int64_t>(cst_right);
      if (result >= INT32_MIN && result <= INT32_MAX) {
        return GetInt32Constant(static_cast<int32_t>(result));
      }
      return {};
    }
    case Operation::kSubtract: {
      int64_t result = static_cast<int64_t>(cst_left.value()) -
                       static_cast<int64_t>(cst_right);
      if (result >= INT32_MIN && result <= INT32_MAX) {
        return GetInt32Constant(static_cast<int32_t>(result));
      }
      return {};
    }
    case Operation::kMultiply: {
      int64_t result = static_cast<int64_t>(cst_left.value()) *
                       static_cast<int64_t>(cst_right);
      if (result >= INT32_MIN && result <= INT32_MAX) {
        return GetInt32Constant(static_cast<int32_t>(result));
      }
      return {};
    }
    case Operation::kModulus:
      // TODO(v8:7700): Constant fold mod.
      return {};
    case Operation::kDivide:
      // TODO(v8:7700): Constant fold division.
      return {};
    case Operation::kBitwiseAnd:
      return GetInt32Constant(cst_left.value() & cst_right);
    case Operation::kBitwiseOr:
      return GetInt32Constant(cst_left.value() | cst_right);
    case Operation::kBitwiseXor:
      return GetInt32Constant(cst_left.value() ^ cst_right);
    case Operation::kShiftLeft:
      return GetInt32Constant(cst_left.value()
                              << (static_cast<uint32_t>(cst_right) % 32));
    case Operation::kShiftRight:
      return GetInt32Constant(cst_left.value() >>
                              (static_cast<uint32_t>(cst_right) % 32));
    case Operation::kShiftRightLogical:
      return GetUint32Constant(static_cast<uint32_t>(cst_left.value()) >>
                               (static_cast<uint32_t>(cst_right) % 32));
    default:
      UNREACHABLE();
  }
}
References GetInt32Constant(), GetUint32Constant(), v8::kOperation, v8::base::internal::result, TryGetInt32Constant(), and v8::internal::UNREACHABLE().
TryFoldInt32BinaryOperation() [2/2]
template<Operation kOperation>
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryFoldInt32BinaryOperation (ValueNode * left, ValueNode * right) [private]
Definition at line 2360 of file maglev-graph-builder.cc.
                                       {
  auto cst_right = TryGetInt32Constant(right);
  if (!cst_right.has_value()) return {};
  return TryFoldInt32BinaryOperation<kOperation>(left, cst_right.value());
}
References TryGetInt32Constant().
TryFoldInt32UnaryOperation()
template<Operation kOperation>
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryFoldInt32UnaryOperation (ValueNode * value) [private]
Definition at line 2303 of file maglev-graph-builder.cc.
                     {
  auto cst = TryGetInt32Constant(node);
  if (!cst.has_value()) return {};
  switch (kOperation) {
    case Operation::kBitwiseNot:
      return GetInt32Constant(~cst.value());
    case Operation::kIncrement:
      if (cst.value() < INT32_MAX) {
        return GetInt32Constant(cst.value() + 1);
      }
      return {};
    case Operation::kDecrement:
      if (cst.value() > INT32_MIN) {
        return GetInt32Constant(cst.value() - 1);
      }
      return {};
    case Operation::kNegate:
      if (cst.value() == 0) {
        return {};
      }
      if (cst.value() != INT32_MIN) {
        return GetInt32Constant(-cst.value());
      }
      return {};
    default:
      UNREACHABLE();
  }
}
References GetInt32Constant(), v8::kOperation, TryGetInt32Constant(), and v8::internal::UNREACHABLE().
TryFoldLoadConstantDataField()
compiler::OptionalObjectRef v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDataField (compiler::JSObjectRef holder, compiler::PropertyAccessInfo const & access_info) [private]
Definition at line 5464 of file maglev-graph-builder.cc.
                                                   {
  DCHECK(!access_info.field_representation().IsDouble());
  return holder.GetOwnFastConstantDataProperty(
      broker(), access_info.field_representation(), access_info.field_index(),
      broker()->dependencies());
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_representation(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), and v8::internal::Representation::IsDouble().
Referenced by BuildLoadField().
TryFoldLoadConstantDoubleField()
std::optional< Float64 > v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDoubleField (compiler::JSObjectRef holder, compiler::PropertyAccessInfo const & access_info) [private]
Definition at line 5473 of file maglev-graph-builder.cc.
                                                   {
  DCHECK(access_info.field_representation().IsDouble());
  return holder.GetOwnFastConstantDoubleProperty(
      broker(), access_info.field_index(), broker()->dependencies());
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_representation(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDoubleProperty(), and v8::internal::Representation::IsDouble().
Referenced by BuildLoadField().
TryFoldLoadDictPrototypeConstant()
compiler::OptionalObjectRef v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant (compiler::PropertyAccessInfo const & access_info) [private]
Definition at line 5415 of file maglev-graph-builder.cc.
                                                   {
  DCHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
  DCHECK(access_info.IsDictionaryProtoDataConstant());
  DCHECK(access_info.holder().has_value());
  compiler::OptionalObjectRef constant =
      access_info.holder()->GetOwnDictionaryProperty(
          broker(), access_info.dictionary_index(), broker()->dependencies());
  if (!constant.has_value()) return {};
  for (compiler::MapRef map : access_info.lookup_start_object_maps()) {
    DirectHandle<Map> map_handle = map.object();
    // Non-JSReceivers that passed AccessInfoFactory::ComputePropertyAccessInfo
    // must have different lookup start map.
    if (!IsJSReceiverMap(*map_handle)) {
      // Perform the implicit ToObject for primitives here.
      // Implemented according to ES6 section 7.3.2 GetV (V, P).
      Tagged<JSFunction> constructor =
          Map::GetConstructorFunction(
              *map_handle, *broker()->target_native_context().object())
              .value();
      // {constructor.initial_map()} is loaded/stored with acquire-release
      // semantics for constructors.
      map = MakeRefAssumeMemoryFence(broker(), constructor->initial_map());
      DCHECK(IsJSObjectMap(*map.object()));
    }
    broker()->dependencies()->DependOnConstantInDictionaryPrototypeChain(
        map, access_info.name(), constant.value(), PropertyKind::kData);
  }
  return constant;
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnConstantInDictionaryPrototypeChain(), v8::internal::compiler::PropertyAccessInfo::dictionary_index(), v8::internal::Map::GetConstructorFunction(), v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::compiler::PropertyAccessInfo::IsDictionaryProtoDataConstant(), v8::internal::kData, v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps(), v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::compiler::PropertyAccessInfo::name(), and V8_DICT_PROPERTY_CONST_TRACKING_BOOL.
Referenced by TryBuildPropertyLoad().
TryGetConstant()
compiler::OptionalHeapObjectRef v8::internal::maglev::MaglevGraphBuilder::TryGetConstant (ValueNode * node, ValueNode ** constant_node = nullptr) [private]
Definition at line 3060 of file maglev-graph-builder.cc.
                                                {
  if (auto result = node->TryGetConstant(broker())) {
    if (constant_node) *constant_node = node;
    return result;
  }
  if (auto c = TryGetConstantAlternative(node)) {
    return TryGetConstant(*c, constant_node);
  }
  return {};
}
References broker(), v8::base::internal::result, v8::internal::maglev::ValueNode::TryGetConstant(), and TryGetConstantAlternative().
Referenced by BuildCheckMaps(), BuildLoadFixedArrayElement(), BuildTestUndetectable(), CheckContextExtensions(), TryBuildNamedAccess(), TryGetConstantDataFieldHolder(), TryReduceCompareEqualAgainstConstant(), and TrySpecializeLoadContextSlotToFunctionContext().
TryGetConstantAlternative()
std::optional< ValueNode * > v8::internal::maglev::MaglevGraphBuilder::TryGetConstantAlternative (ValueNode * node) [private]
Definition at line 3072 of file maglev-graph-builder.cc.
                     {
  const NodeInfo* info = known_node_aspects().TryGetInfoFor(node);
  if (info) {
    if (auto c = info->alternative().checked_value()) {
      if (IsConstantNode(c->opcode())) {
        return c;
      }
    }
  }
  return {};
}
References v8::internal::maglev::NodeInfo::alternative(), v8::internal::maglev::IsConstantNode(), known_node_aspects(), and v8::internal::maglev::KnownNodeAspects::TryGetInfoFor().
Referenced by TryGetConstant(), TryGetFloat64Constant(), TryGetInt32Constant(), and TryGetUint32Constant().
TryGetConstantDataFieldHolder()
compiler::OptionalJSObjectRef v8::internal::maglev::MaglevGraphBuilder::TryGetConstantDataFieldHolder (compiler::PropertyAccessInfo const & access_info, ValueNode * lookup_start_object) [private]
Definition at line 5449 of file maglev-graph-builder.cc.
                                    {
  if (!access_info.IsFastDataConstant()) return {};
  if (access_info.holder().has_value()) {
    return access_info.holder();
  }
  if (compiler::OptionalHeapObjectRef c = TryGetConstant(lookup_start_object)) {
    if (c.value().IsJSObject()) {
      return c.value().AsJSObject();
    }
  }
  return {};
}
References v8::internal::compiler::PropertyAccessInfo::holder(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), and TryGetConstant().
Referenced by BuildLoadField().
TryGetFloat64Constant()
std::optional< double > v8::internal::maglev::MaglevGraphBuilder::TryGetFloat64Constant (ValueNode * value, TaggedToFloat64ConversionType conversion_type) [private]
Definition at line 1919 of file maglev-graph-builder.cc.
                                                                     {
  switch (value->opcode()) {
    case Opcode::kConstant: {
      compiler::ObjectRef object = value->Cast<Constant>()->object();
      if (object.IsHeapNumber()) {
        return object.AsHeapNumber().value();
      }
      // Oddballs should be RootConstants.
      DCHECK(!IsOddball(*object.object()));
      return {};
    }
    case Opcode::kInt32Constant:
      return value->Cast<Int32Constant>()->value();
    case Opcode::kSmiConstant:
      return value->Cast<SmiConstant>()->value().value();
    case Opcode::kFloat64Constant:
      return value->Cast<Float64Constant>()->value().get_scalar();
    case Opcode::kRootConstant: {
      Tagged<Object> root_object =
          local_isolate_->root(value->Cast<RootConstant>()->index());
      if (conversion_type == TaggedToFloat64ConversionType::kNumberOrBoolean &&
          IsBoolean(root_object)) {
        return Cast<Oddball>(root_object)->to_number_raw();
      }
      if (conversion_type == TaggedToFloat64ConversionType::kNumberOrOddball &&
          IsOddball(root_object)) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        if (IsUndefined(root_object)) {
          // We use the undefined nan and silence it to produce the same result
          // as a computation from non-constants would.
          auto ud = Float64::FromBits(kUndefinedNanInt64);
          return ud.to_quiet_nan().get_scalar();
        }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
        return Cast<Oddball>(root_object)->to_number_raw();
      }
      if (IsHeapNumber(root_object)) {
        return Cast<HeapNumber>(root_object)->value();
      }
      return {};
    }
    default:
      break;
  }
  if (auto c = TryGetConstantAlternative(value)) {
    return TryGetFloat64Constant(*c, conversion_type);
  }
  return {};
}
References v8::internal::DCHECK(), v8::internal::Float64::FromBits(), v8::internal::maglev::RootConstant::index(), v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::maglev::kNumberOrBoolean, v8::internal::maglev::kNumberOrOddball, local_isolate_, v8::internal::LocalIsolate::root(), TryGetConstantAlternative(), and v8::internal::value.
Referenced by GetFloat64ForToNumber(), TryFoldFloat64BinaryOperationForToNumber(), and TryFoldFloat64UnaryOperationForToNumber().
TryGetInt32Constant()
std::optional< int32_t > v8::internal::maglev::MaglevGraphBuilder::TryGetInt32Constant (ValueNode * value) [private]
Definition at line 1788 of file maglev-graph-builder.cc.
                      {
  switch (value->opcode()) {
    case Opcode::kInt32Constant:
      return value->Cast<Int32Constant>()->value();
    case Opcode::kUint32Constant: {
      uint32_t uint32_value = value->Cast<Uint32Constant>()->value();
      if (uint32_value <= INT32_MAX) {
        return static_cast<int32_t>(uint32_value);
      }
      return {};
    }
    case Opcode::kSmiConstant:
      return value->Cast<SmiConstant>()->value().value();
    case Opcode::kFloat64Constant: {
      double double_value =
          value->Cast<Float64Constant>()->value().get_scalar();
      if (!IsInt32Double(double_value)) return {};
      return FastD2I(value->Cast<Float64Constant>()->value().get_scalar());
    }
    default:
      break;
  }
  if (auto c = TryGetConstantAlternative(value)) {
    return TryGetInt32Constant(*c);
  }
  return {};
}
References v8::internal::FastD2I(), v8::internal::Float64::get_scalar(), v8::internal::IsInt32Double(), TryGetConstantAlternative(), v8::internal::maglev::Float64Constant::value(), and v8::internal::value.
Referenced by BuildLoadFixedArrayElement(), BuildLoadFixedDoubleArrayElement(), GetInt32(), TryFoldInt32BinaryOperation(), and TryFoldInt32UnaryOperation().
TryGetNonEscapingArgumentsObject()
std::optional< VirtualObject * > v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject (ValueNode * value) [private]
Definition at line 11669 of file maglev-graph-builder.cc.
                                                                     {
  if (!value->Is<InlinedAllocation>()) return {};
  InlinedAllocation* alloc = value->Cast<InlinedAllocation>();
  // Although the arguments object has not been changed so far, since it is not
  // escaping, it could be modified after this bytecode if it is inside a loop.
  if (IsInsideLoop()) {
    if (!is_loop_effect_tracking() ||
        !loop_effects_->allocations.contains(alloc)) {
      return {};
    }
  }
  // TODO(victorgomes): We can probably loosen the IsNotEscaping requirement if
  // we keep track of the arguments object changes so far.
  if (alloc->IsEscaping()) return {};
  VirtualObject* object = alloc->object();
  if (!object->has_static_map()) return {};
  // TODO(victorgomes): Support simple JSArray forwarding.
  compiler::MapRef map = object->map();
  // It is a rest parameter, if it is an array with ArgumentsElements node as
  // the elements array.
  if (map.IsJSArrayMap() && object->get(JSArgumentsObject::kElementsOffset)
                                ->Is<ArgumentsElements>()) {
    return object;
  }
  // TODO(victorgomes): We can loosen the IsSloppyMappedArgumentsObject
  // requirement if there is no stores to the mapped arguments.
  if (map.IsJSArgumentsObjectMap() &&
      !IsSloppyMappedArgumentsObject(broker(), map)) {
    return object;
  }
  return {};
}
References broker(), v8::internal::maglev::VirtualObject::has_static_map(), v8::internal::maglev::InlinedAllocation::IsEscaping(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSloppyMappedArgumentsObject(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::maglev::InlinedAllocation::object(), and v8::internal::value.
TryGetParentContext()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::TryGetParentContext (ValueNode * node) [private]
Definition at line 144 of file maglev-graph-builder.cc.
                                                                  {
  if (CreateFunctionContext* n = node->TryCast<CreateFunctionContext>()) {
    return n->context().node();
  }
  if (InlinedAllocation* alloc = node->TryCast<InlinedAllocation>()) {
    return alloc->object()->get(
        Context::OffsetOfElementAt(Context::PREVIOUS_INDEX));
  }
  if (CallRuntime* n = node->TryCast<CallRuntime>()) {
    switch (n->function_id()) {
      case Runtime::kPushBlockContext:
      case Runtime::kPushCatchContext:
      case Runtime::kNewFunctionContext:
        return n->context().node();
      default:
        break;
    }
  }
  return nullptr;
}
References v8::internal::Context::OffsetOfElementAt(), v8::internal::Context::PREVIOUS_INDEX, and v8::internal::maglev::NodeBase::TryCast().
Referenced by MinimizeContextChainDepth().
TryGetUint32Constant()
std::optional< uint32_t > v8::internal::maglev::MaglevGraphBuilder::TryGetUint32Constant (ValueNode * value) [private]
Definition at line 1817 of file maglev-graph-builder.cc.
                      {
  switch (value->opcode()) {
    case Opcode::kInt32Constant: {
      int32_t int32_value = value->Cast<Int32Constant>()->value();
      if (int32_value >= 0) {
        return static_cast<uint32_t>(int32_value);
      }
      return {};
    }
    case Opcode::kUint32Constant:
      return value->Cast<Uint32Constant>()->value();
    case Opcode::kSmiConstant: {
      int32_t smi_value = value->Cast<SmiConstant>()->value().value();
      if (smi_value >= 0) {
        return static_cast<uint32_t>(smi_value);
      }
      return {};
    }
    case Opcode::kFloat64Constant: {
      double double_value =
          value->Cast<Float64Constant>()->value().get_scalar();
      if (!IsUint32Double(double_value)) return {};
      return FastD2UI(value->Cast<Float64Constant>()->value().get_scalar());
    }
    default:
      break;
  }
  if (auto c = TryGetConstantAlternative(value)) {
    return TryGetUint32Constant(*c);
  }
  return {};
}
References v8::internal::FastD2UI(), v8::internal::Float64::get_scalar(), v8::internal::IsUint32Double(), TryGetConstantAlternative(), v8::internal::maglev::Float64Constant::value(), and v8::internal::value.
TryInferApiHolderValue()
compiler::HolderLookupResult v8::internal::maglev::MaglevGraphBuilder::TryInferApiHolderValue (compiler::FunctionTemplateInfoRef function_template_info, ValueNode * receiver) [private]
Definition at line 11364 of file maglev-graph-builder.cc.
                         {
  const compiler::HolderLookupResult not_found;
  auto receiver_info = known_node_aspects().TryGetInfoFor(receiver);
  if (!receiver_info || !receiver_info->possible_maps_are_known()) {
    // No info about receiver, can't infer API holder.
    return not_found;
  }
  DCHECK(!receiver_info->possible_maps().is_empty());
  compiler::MapRef first_receiver_map = receiver_info->possible_maps()[0];
  // See if we can constant-fold the compatible receiver checks.
  compiler::HolderLookupResult api_holder =
      function_template_info.LookupHolderOfExpectedType(broker(),
                                                        first_receiver_map);
  if (api_holder.lookup == CallOptimization::kHolderNotFound) {
    // Can't infer API holder.
    return not_found;
  }
  // Check that all {receiver_maps} are actually JSReceiver maps and
  // that the {function_template_info} accepts them without access
  // checks (even if "access check needed" is set for {receiver}).
  //
  // API holder might be a receivers's hidden prototype (i.e. the receiver is
  // a global proxy), so in this case the map check or stability dependency on
  // the receiver guard us from detaching a global object from global proxy.
  CHECK(first_receiver_map.IsJSReceiverMap());
  CHECK(!first_receiver_map.is_access_check_needed() ||
        function_template_info.accept_any_receiver());
  for (compiler::MapRef receiver_map : receiver_info->possible_maps()) {
    compiler::HolderLookupResult holder_i =
        function_template_info.LookupHolderOfExpectedType(broker(),
                                                          receiver_map);
    if (api_holder.lookup != holder_i.lookup) {
      // Different API holders, dynamic lookup is required.
      return not_found;
    }
    DCHECK(holder_i.lookup == CallOptimization::kHolderFound ||
           holder_i.lookup == CallOptimization::kHolderIsReceiver);
    if (holder_i.lookup == CallOptimization::kHolderFound) {
      DCHECK(api_holder.holder.has_value() && holder_i.holder.has_value());
      if (!api_holder.holder->equals(*holder_i.holder)) {
        // Different API holders, dynamic lookup is required.
        return not_found;
      }
    }
    CHECK(receiver_map.IsJSReceiverMap());
    CHECK(!receiver_map.is_access_check_needed() ||
          function_template_info.accept_any_receiver());
  }
  return api_holder;
}
References v8::internal::compiler::FunctionTemplateInfoRef::accept_any_receiver(), broker(), CHECK, v8::internal::DCHECK(), v8::internal::compiler::HolderLookupResult::holder, v8::internal::compiler::MapRef::is_access_check_needed(), v8::internal::CallOptimization::kHolderFound, v8::internal::CallOptimization::kHolderIsReceiver, v8::internal::CallOptimization::kHolderNotFound, v8::internal::compiler::HolderLookupResult::lookup, and v8::internal::compiler::FunctionTemplateInfoRef::LookupHolderOfExpectedType().
TryReadBoilerplateForFastLiteral()
std::optional< VirtualObject * > v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral (compiler::JSObjectRef boilerplate, AllocationType allocation, int max_depth, int * max_properties) [private]
Definition at line 13171 of file maglev-graph-builder.cc.
                         {
  DCHECK_GE(max_depth, 0);
  DCHECK_GE(*max_properties, 0);
  if (max_depth == 0) return {};
  // Prevent concurrent migrations of boilerplate objects.
  compiler::JSHeapBroker::BoilerplateMigrationGuardIfNeeded
      boilerplate_access_guard(broker());
  // Now that we hold the migration lock, get the current map.
  compiler::MapRef boilerplate_map = boilerplate.map(broker());
  // Protect against concurrent changes to the boilerplate object by checking
  // for an identical value at the end of the compilation.
  broker()->dependencies()->DependOnObjectSlotValue(
      boilerplate, HeapObject::kMapOffset, boilerplate_map);
  {
    compiler::OptionalMapRef current_boilerplate_map =
        boilerplate.map_direct_read(broker());
    if (!current_boilerplate_map.has_value() ||
        !current_boilerplate_map->equals(boilerplate_map)) {
      // TODO(leszeks): Emit an eager deopt for this case, so that we can
      // re-learn the boilerplate. This will be easier once we get rid of the
      // two-pass approach, since we'll be able to create the eager deopt here
      // and return a ReduceResult::DoneWithAbort().
      return {};
    }
  }
  // Bail out if the boilerplate map has been deprecated. The map could of
  // course be deprecated at some point after the line below, but it's not a
  // correctness issue -- it only means the literal won't be created with the
  // most up to date map(s).
  if (boilerplate_map.is_deprecated()) return {};
  // We currently only support in-object properties.
  if (boilerplate.map(broker()).elements_kind() == DICTIONARY_ELEMENTS ||
      boilerplate.map(broker()).is_dictionary_map() ||
      !boilerplate.raw_properties_or_hash(broker()).has_value()) {
    return {};
  }
  {
    compiler::ObjectRef properties =
        *boilerplate.raw_properties_or_hash(broker());
    bool const empty =
        properties.IsSmi() ||
        properties.equals(MakeRef(
            broker(), local_isolate()->factory()->empty_fixed_array())) ||
        properties.equals(MakeRef(
            broker(),
            Cast<Object>(local_isolate()->factory()->empty_property_array())));
    if (!empty) return {};
  }
  compiler::OptionalFixedArrayBaseRef maybe_elements =
      boilerplate.elements(broker(), kRelaxedLoad);
  if (!maybe_elements.has_value()) return {};
  compiler::FixedArrayBaseRef boilerplate_elements = maybe_elements.value();
  broker()->dependencies()->DependOnObjectSlotValue(
      boilerplate, JSObject::kElementsOffset, boilerplate_elements);
  const uint32_t elements_length = boilerplate_elements.length();
  VirtualObject* fast_literal;
  if (boilerplate_map.IsJSArrayMap()) {
    MaybeReduceResult fast_array = CreateJSArray(
        boilerplate_map, boilerplate_map.instance_size(),
        GetConstant(boilerplate.AsJSArray().GetBoilerplateLength(broker())));
    CHECK(fast_array.HasValue());
    fast_literal = fast_array.value()->Cast<VirtualObject>();
  } else {
    fast_literal = CreateJSObject(boilerplate_map);
  }
  int inobject_properties = boilerplate_map.GetInObjectProperties();
  // Compute the in-object properties to store first.
  int index = 0;
  for (InternalIndex i :
       InternalIndex::Range(boilerplate_map.NumberOfOwnDescriptors())) {
    PropertyDetails const property_details =
        boilerplate_map.GetPropertyDetails(broker(), i);
    if (property_details.location() != PropertyLocation::kField) continue;
    DCHECK_EQ(PropertyKind::kData, property_details.kind());
    if ((*max_properties)-- == 0) return {};
    int offset = boilerplate_map.GetInObjectPropertyOffset(index);
#ifdef DEBUG
    FieldIndex field_index =
        FieldIndex::ForDetails(*boilerplate_map.object(), property_details);
    DCHECK(field_index.is_inobject());
    DCHECK_EQ(index, field_index.property_index());
    DCHECK_EQ(field_index.offset(), offset);
#endif
    // The index is derived from the in-sandbox `NumberOfOwnDescriptors` value,
    // but the access is out-of-sandbox fast_literal fields.
    SBXCHECK_LT(index, inobject_properties);
    // Note: the use of RawInobjectPropertyAt (vs. the higher-level
    // GetOwnFastConstantDataProperty) here is necessary, since the underlying
    // value may be `uninitialized`, which the latter explicitly does not
    // support.
    compiler::OptionalObjectRef maybe_boilerplate_value =
        boilerplate.RawInobjectPropertyAt(
            broker(),
            FieldIndex::ForInObjectOffset(offset, FieldIndex::kTagged));
    if (!maybe_boilerplate_value.has_value()) return {};
    // Note: We don't need to take a compilation dependency verifying the value
    // of `boilerplate_value`, since boilerplate properties are constant after
    // initialization modulo map migration. We protect against concurrent map
    // migrations (other than elements kind transition, which don't affect us)
    // via the boilerplate_migration_access lock.
    compiler::ObjectRef boilerplate_value = maybe_boilerplate_value.value();
    if (boilerplate_value.IsJSObject()) {
      compiler::JSObjectRef boilerplate_object = boilerplate_value.AsJSObject();
      std::optional<VirtualObject*> maybe_object_value =
          TryReadBoilerplateForFastLiteral(boilerplate_object, allocation,
                                           max_depth - 1, max_properties);
      if (!maybe_object_value.has_value()) return {};
      fast_literal->set(offset, maybe_object_value.value());
    } else if (property_details.representation().IsDouble()) {
      fast_literal->set(offset,
                        CreateHeapNumber(Float64::FromBits(
                            boilerplate_value.AsHeapNumber().value_as_bits())));
    } else {
      // It's fine to store the 'uninitialized' Oddball into a Smi field since
      // it will get overwritten anyway.
      DCHECK_IMPLIES(property_details.representation().IsSmi() &&
                         !boilerplate_value.IsSmi(),
                     IsUninitialized(*boilerplate_value.object()));
      fast_literal->set(offset, GetConstant(boilerplate_value));
    }
    index++;
  }
  // Fill slack at the end of the boilerplate object with filler maps.
  for (; index < inobject_properties; ++index) {
    DCHECK(!V8_MAP_PACKING_BOOL);
    // TODO(wenyuzhao): Fix incorrect MachineType when V8_MAP_PACKING is
    // enabled.
    int offset = boilerplate_map.GetInObjectPropertyOffset(index);
    fast_literal->set(offset, GetRootConstant(RootIndex::kOnePointerFillerMap));
  }
  DCHECK_EQ(JSObject::kElementsOffset, JSArray::kElementsOffset);
  // Empty or copy-on-write elements just store a constant.
  compiler::MapRef elements_map = boilerplate_elements.map(broker());
  // Protect against concurrent changes to the boilerplate object by checking
  // for an identical value at the end of the compilation.
  broker()->dependencies()->DependOnObjectSlotValue(
      boilerplate_elements, HeapObject::kMapOffset, elements_map);
  if (boilerplate_elements.length() == 0 ||
      elements_map.IsFixedCowArrayMap(broker())) {
    if (allocation == AllocationType::kOld &&
        !boilerplate.IsElementsTenured(boilerplate_elements)) {
      return {};
    }
    fast_literal->set(JSObject::kElementsOffset,
                      GetConstant(boilerplate_elements));
  } else {
    // Compute the elements to store first (might have effects).
    if (boilerplate_elements.IsFixedDoubleArray()) {
      int const size = FixedDoubleArray::SizeFor(elements_length);
      if (size > kMaxRegularHeapObjectSize) return {};
      fast_literal->set(
          JSObject::kElementsOffset,
          CreateDoubleFixedArray(elements_length,
                                 boilerplate_elements.AsFixedDoubleArray()));
    } else {
      int const size = FixedArray::SizeFor(elements_length);
      if (size > kMaxRegularHeapObjectSize) return {};
      VirtualObject* elements =
          CreateFixedArray(broker()->fixed_array_map(), elements_length);
      compiler::FixedArrayRef boilerplate_elements_as_fixed_array =
          boilerplate_elements.AsFixedArray();
      for (uint32_t i = 0; i < elements_length; ++i) {
        if ((*max_properties)-- == 0) return {};
        compiler::OptionalObjectRef element_value =
            boilerplate_elements_as_fixed_array.TryGet(broker(), i);
        if (!element_value.has_value()) return {};
        if (element_value->IsJSObject()) {
          std::optional<VirtualObject*> object =
              TryReadBoilerplateForFastLiteral(element_value->AsJSObject(),
                                               allocation, max_depth - 1,
                                               max_properties);
          if (!object.has_value()) return {};
          elements->set(FixedArray::OffsetOfElementAt(i), *object);
        } else {
          elements->set(FixedArray::OffsetOfElementAt(i),
                        GetConstant(*element_value));
        }
      }
      fast_literal->set(JSObject::kElementsOffset, elements);
    }
  }
  return fast_literal;
}
References broker(), v8::internal::maglev::NodeBase::Cast(), CHECK, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, v8::internal::DICTIONARY_ELEMENTS, v8::internal::compiler::JSObjectRef::elements(), v8::internal::FieldIndex::ForDetails(), v8::internal::FieldIndex::ForInObjectOffset(), v8::internal::Float64::FromBits(), v8::internal::compiler::MapRef::GetInObjectProperties(), v8::internal::compiler::MapRef::GetInObjectPropertyOffset(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::maglev::MaybeReduceResult::HasValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::MapRef::is_deprecated(), v8::internal::FieldIndex::is_inobject(), v8::internal::Representation::IsDouble(), v8::internal::compiler::JSObjectRef::IsElementsTenured(), v8::internal::compiler::MapRef::IsFixedCowArrayMap(), v8::internal::Representation::IsSmi(), v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::HeapObject::kMapOffset, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kOld, v8::kRelaxedLoad, v8::internal::FieldIndex::kTagged, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::PropertyDetails::location(), v8::internal::compiler::MakeRef(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::HeapObjectRef::map_direct_read(), v8::internal::compiler::MapRef::NumberOfOwnDescriptors(), v8::internal::compiler::MapRef::object(), v8::internal::FieldIndex::offset(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt(), v8::internal::FieldIndex::property_index(), v8::internal::compiler::JSObjectRef::raw_properties_or_hash(), v8::internal::compiler::JSObjectRef::RawInobjectPropertyAt(), v8::internal::PropertyDetails::representation(), SBXCHECK_LT, v8::internal::maglev::VirtualObject::set(), size(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::SizeFor(), v8::internal::compiler::FixedArrayRef::TryGet(), V8_MAP_PACKING_BOOL, and v8::internal::maglev::MaybeReduceResult::value().
TryReduceArrayIteratingBuiltin()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin (const char * name, compiler::JSFunctionRef target, CallArguments & args, GetDeoptScopeCallback get_eager_deopt_scope, GetDeoptScopeCallback get_lazy_deopt_scope, const std::optional< InitialCallback > & initial_callback = {}, const std::optional< ProcessElementCallback > & process_element_callback = {}) [private]
Definition at line 8888 of file maglev-graph-builder.cc.
                                                                         {
  DCHECK_EQ(initial_callback.has_value(), process_element_callback.has_value());
  if (!CanSpeculateCall()) return {};
  ValueNode* receiver = args.receiver();
  if (!receiver) return {};
  if (args.count() < 1) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce " << name << " - not enough arguments"
                << std::endl;
    }
    return {};
  }
  auto node_info = known_node_aspects().TryGetInfoFor(receiver);
  if (!node_info || !node_info->possible_maps_are_known()) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce " << name
                << " - receiver map is unknown" << std::endl;
    }
    return {};
  }
  ElementsKind elements_kind;
  if (!CanInlineArrayIteratingBuiltin(broker(), node_info->possible_maps(),
                                      &elements_kind)) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce " << name
                << " - doesn't support fast array iteration or incompatible"
                << " maps" << std::endl;
    }
    return {};
  }
  // TODO(leszeks): May only be needed for holey elements kinds.
  if (!broker()->dependencies()->DependOnNoElementsProtector()) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce " << name
                << " - invalidated no elements protector" << std::endl;
    }
    return {};
  }
  ValueNode* callback = args[0];
  if (!callback->is_tagged()) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce " << name
                << " - callback is untagged value" << std::endl;
    }
    return {};
  }
  ValueNode* this_arg =
      args.count() > 1 ? args[1] : GetRootConstant(RootIndex::kUndefinedValue);
  ValueNode* original_length = BuildLoadJSArrayLength(receiver);
  if (initial_callback) {
    RETURN_IF_ABORT((*initial_callback)(original_length));
  }
  // Elide the callable check if the node is known callable.
  EnsureType(callback, NodeType::kCallable, [&](NodeType old_type) {
    // ThrowIfNotCallable is wrapped in a lazy_deopt_scope to make sure the
    // exception has the right call stack.
    const DeoptFrameScope& lazy_deopt_scope = get_lazy_deopt_scope(
        target, receiver, callback, this_arg, GetSmiConstant(0),
        GetSmiConstant(0), original_length);
    AddNewNode<ThrowIfNotCallable>({callback});
  });
  ValueNode* original_length_int32 = GetInt32(original_length);
  // Remember the receiver map set before entering the loop the call.
  bool receiver_maps_were_unstable = node_info->possible_maps_are_unstable();
  PossibleMaps receiver_maps_before_loop(node_info->possible_maps());
  // Create a sub graph builder with two variables (index and length).
  MaglevSubGraphBuilder sub_builder(this, 2);
  MaglevSubGraphBuilder::Variable var_index(0);
  MaglevSubGraphBuilder::Variable var_length(1);
  MaglevSubGraphBuilder::Label loop_end(&sub_builder, 1);
  // ```
  // index = 0
  // bind loop_header
  // ```
  sub_builder.set(var_index, GetSmiConstant(0));
  sub_builder.set(var_length, original_length);
  MaglevSubGraphBuilder::LoopLabel loop_header =
      sub_builder.BeginLoop({&var_index, &var_length});
  // Reset known state that is cleared by BeginLoop, but is known to be true on
  // the first iteration, and will be re-checked at the end of the loop.
  // Reset the known receiver maps if necessary.
  if (receiver_maps_were_unstable) {
    node_info->SetPossibleMaps(receiver_maps_before_loop,
                               receiver_maps_were_unstable,
                               // Node type is monotonic, no need to reset it.
                               NodeType::kUnknown, broker());
    known_node_aspects().any_map_for_any_node_is_unstable = true;
  } else {
    DCHECK_EQ(node_info->possible_maps().size(),
              receiver_maps_before_loop.size());
  }
  // Reset the cached loaded array length to the length var.
  RecordKnownProperty(receiver, broker()->length_string(),
                      sub_builder.get(var_length), false,
                      compiler::AccessMode::kLoad);
  // ```
  // if (index_int32 < length_int32)
  // fallthrough
  // else
  // goto end
  // ```
  Phi* index_tagged = sub_builder.get(var_index)->Cast<Phi>();
  EnsureType(index_tagged, NodeType::kSmi);
  ValueNode* index_int32 = GetInt32(index_tagged);
  sub_builder.GotoIfFalse<BranchIfInt32Compare>(
      &loop_end, {index_int32, original_length_int32}, Operation::kLessThan);
  // ```
  // next_index = index + 1
  // ```
  ValueNode* next_index_int32 = nullptr;
  {
    // Eager deopt scope for index increment overflow.
    // TODO(pthier): In practice this increment can never overflow, as the max
    // possible array length is less than int32 max value. Add a new
    // Int32Increment that asserts no overflow instead of deopting.
    DeoptFrameScope eager_deopt_scope =
        get_eager_deopt_scope(target, receiver, callback, this_arg, index_int32,
                              index_int32, original_length);
    next_index_int32 = AddNewNode<Int32IncrementWithOverflow>({index_int32});
    EnsureType(next_index_int32, NodeType::kSmi);
  }
  // TODO(leszeks): Assert Smi.
  // ```
  // element = array.elements[index]
  // ```
  ValueNode* elements = BuildLoadElements(receiver);
  ValueNode* element;
  if (IsDoubleElementsKind(elements_kind)) {
    element = BuildLoadFixedDoubleArrayElement(elements, index_int32);
  } else {
    element = BuildLoadFixedArrayElement(elements, index_int32);
  }
  std::optional<MaglevSubGraphBuilder::Label> skip_call;
  if (IsHoleyElementsKind(elements_kind)) {
    // ```
    // if (element is hole) goto skip_call
    // ```
    skip_call.emplace(
        &sub_builder, 2,
        std::initializer_list<MaglevSubGraphBuilder::Variable*>{&var_length});
    if (elements_kind == HOLEY_DOUBLE_ELEMENTS) {
      sub_builder.GotoIfTrue<BranchIfFloat64IsHole>(&*skip_call, {element});
    } else {
      sub_builder.GotoIfTrue<BranchIfRootConstant>(&*skip_call, {element},
                                                   RootIndex::kTheHoleValue);
    }
  }
  // ```
  // callback(this_arg, element, array)
  // ```
  MaybeReduceResult result;
  {
    const DeoptFrameScope& lazy_deopt_scope =
        get_lazy_deopt_scope(target, receiver, callback, this_arg, index_int32,
                             next_index_int32, original_length);
    CallArguments call_args =
        args.count() < 2
            ? CallArguments(ConvertReceiverMode::kNullOrUndefined,
                            {element, index_tagged, receiver})
            : CallArguments(ConvertReceiverMode::kAny,
                            {this_arg, element, index_tagged, receiver});
    SaveCallSpeculationScope saved(this);
    result = ReduceCall(callback, call_args, saved.value());
  }
  // ```
  // index = next_index
  // jump loop_header
  // ```
  DCHECK_IMPLIES(result.IsDoneWithAbort(), current_block_ == nullptr);
  // No need to finish the loop if this code is unreachable.
  if (!result.IsDoneWithAbort()) {
    if (process_element_callback) {
      ValueNode* value = result.value();
      (*process_element_callback)(index_int32, value);
    }
    // If any of the receiver's maps were unstable maps, we have to re-check the
    // maps on each iteration, in case the callback changed them. That said, we
    // know that the maps are valid on the first iteration, so we can rotate the
    // check to _after_ the callback, and then elide it if the receiver maps are
    // still known to be valid (i.e. the known maps after the call are contained
    // inside the known maps before the call).
    bool recheck_maps_after_call = receiver_maps_were_unstable;
    if (recheck_maps_after_call) {
      // No need to recheck maps if there are known maps...
      if (auto receiver_info_after_call =
              known_node_aspects().TryGetInfoFor(receiver)) {
        // ... and those known maps are equal to, or a subset of, the maps
        // before the call.
        if (receiver_info_after_call &&
            receiver_info_after_call->possible_maps_are_known()) {
          recheck_maps_after_call = !receiver_maps_before_loop.contains(
              receiver_info_after_call->possible_maps());
        }
      }
    }
    // Make sure to finish the loop if we eager deopt in the map check or index
    // check.
    const DeoptFrameScope& eager_deopt_scope =
        get_eager_deopt_scope(target, receiver, callback, this_arg, index_int32,
                              next_index_int32, original_length);
    if (recheck_maps_after_call) {
      // Build the CheckMap manually, since we're doing it with already known
      // maps rather than feedback, and we don't need to update known node
      // aspects or types since we're at the end of the loop anyway.
      bool emit_check_with_migration = std::any_of(
          receiver_maps_before_loop.begin(), receiver_maps_before_loop.end(),
          [](compiler::MapRef map) { return map.is_migration_target(); });
      if (emit_check_with_migration) {
        AddNewNode<CheckMapsWithMigration>({receiver},
                                           receiver_maps_before_loop,
                                           CheckType::kOmitHeapObjectCheck);
      } else {
        AddNewNode<CheckMaps>({receiver}, receiver_maps_before_loop,
                              CheckType::kOmitHeapObjectCheck);
      }
    }
    // Check if the index is still in bounds, in case the callback changed the
    // length.
    ValueNode* current_length = BuildLoadJSArrayLength(receiver);
    sub_builder.set(var_length, current_length);
    // Reference compare the loaded length against the original length. If this
    // is the same value node, then we didn't have any side effects and didn't
    // clear the cached length.
    if (current_length != original_length) {
      RETURN_IF_ABORT(
          TryBuildCheckInt32Condition(original_length_int32, current_length,
                                      AssertCondition::kUnsignedLessThanEqual,
                                      DeoptimizeReason::kArrayLengthChanged));
    }
  }
  if (skip_call.has_value()) {
    sub_builder.GotoOrTrim(&*skip_call);
    sub_builder.Bind(&*skip_call);
  }
  sub_builder.set(var_index, next_index_int32);
  sub_builder.EndLoop(&loop_header);
  // ```
  // bind end
  // ```
  sub_builder.Bind(&loop_end);
  return ReduceResult::Done();
}
References v8::base::any_of(), v8::base::args, v8::internal::ZoneCompactSet< T >::begin(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), broker(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::CanInlineArrayIteratingBuiltin(), v8::internal::maglev::NodeBase::Cast(), v8::internal::ZoneCompactSet< T >::contains(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::ZoneCompactSet< T >::end(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::get(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfFalse(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoIfTrue(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::GotoOrTrim(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::maglev::ValueNode::is_tagged(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::kAny, v8::internal::kLessThan, v8::internal::compiler::kLoad, v8::internal::kNullOrUndefined, v8::internal::compiler::kSmi, v8::internal::kUnsignedLessThanEqual, v8::internal::name, v8::base::internal::result, RETURN_IF_ABORT, v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::set(), v8::internal::ZoneCompactSet< T >::size(), v8::internal::v8_flags, and v8::internal::value.
TryReduceBuiltin()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceBuiltin (compiler::JSFunctionRef target, compiler::SharedFunctionInfoRef shared, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 10842 of file maglev-graph-builder.cc.
                                                                        {
  if (args.mode() != CallArguments::kDefault) {
    // TODO(victorgomes): Maybe inline the spread stub? Or call known function
    // directly if arguments list is an array.
    return {};
  }
  SaveCallSpeculationScope speculate(this, feedback_source);
  if (!shared.HasBuiltinId()) return {};
  if (v8_flags.trace_maglev_graph_building) {
    std::cout << " ! Trying to reduce builtin "
              << Builtins::name(shared.builtin_id()) << std::endl;
  }
  switch (shared.builtin_id()) {
#define CASE(Name, ...) \
  case Builtin::k##Name: \
    return TryReduce##Name(target, args);
    MAGLEV_REDUCED_BUILTIN(CASE)
#undef CASE
    default:
      // TODO(v8:7700): Inline more builtins.
      return {};
  }
}
References v8::base::args, v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), CASE, MAGLEV_REDUCED_BUILTIN, v8::internal::Builtins::name(), and v8::internal::v8_flags.
TryReduceCallForApiFunction()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForApiFunction (compiler::FunctionTemplateInfoRef api_callback, compiler::OptionalSharedFunctionInfoRef maybe_shared, CallArguments & args) [private]
Definition at line 10981 of file maglev-graph-builder.cc.
                                                                             {
  if (args.mode() != CallArguments::kDefault) {
    // TODO(victorgomes): Maybe inline the spread stub? Or call known function
    // directly if arguments list is an array.
    return {};
  }
  // Check if the function has an associated C++ code to execute.
  compiler::OptionalObjectRef maybe_callback_data =
      api_callback.callback_data(broker());
  if (!maybe_callback_data.has_value()) {
    // TODO(ishell): consider generating "return undefined" for empty function
    // instead of failing.
    return {};
  }
  size_t input_count = args.count() + CallKnownApiFunction::kFixedInputCount;
  ValueNode* receiver;
  if (maybe_shared.has_value()) {
    receiver = GetConvertReceiver(maybe_shared.value(), args);
  } else {
    receiver = args.receiver();
    CHECK_NOT_NULL(receiver);
  }
  CallKnownApiFunction::Mode mode =
      broker()->dependencies()->DependOnNoProfilingProtector()
          ? (v8_flags.maglev_inline_api_calls
                 ? CallKnownApiFunction::kNoProfilingInlined
                 : CallKnownApiFunction::kNoProfiling)
          : CallKnownApiFunction::kGeneric;
  return AddNewNode<CallKnownApiFunction>(
      input_count,
      [&](CallKnownApiFunction* call) {
        for (int i = 0; i < static_cast<int>(args.count()); i++) {
          call->set_arg(i, GetTaggedValue(args[i]));
        }
      },
      mode, api_callback, GetTaggedValue(GetContext()),
      GetTaggedValue(receiver));
}
References v8::base::args, broker(), v8::internal::compiler::FunctionTemplateInfoRef::callback_data(), CHECK_NOT_NULL, v8::internal::compiler::turboshaft::detail::input_count(), mode(), v8::internal::maglev::CallKnownApiFunction::set_arg(), and v8::internal::v8_flags.
Referenced by TryBuildPropertyGetterCall(), and TryBuildPropertySetterCall().
TryReduceCallForConstant()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForConstant (compiler::JSFunctionRef target, CallArguments & args, const compiler::FeedbackSource & feedback_source = compiler::FeedbackSource()) [private]
Definition at line 11338 of file maglev-graph-builder.cc.
                                                   {
  if (args.mode() != CallArguments::kDefault) {
    // TODO(victorgomes): Maybe inline the spread stub? Or call known function
    // directly if arguments list is an array.
    return {};
  }
  compiler::SharedFunctionInfoRef shared = target.shared(broker());
  ValueNode* target_node = GetConstant(target);
  // Do not reduce calls to functions with break points.
  if (!shared.HasBreakInfo(broker())) {
    if (IsClassConstructor(shared.kind())) {
      // If we have a class constructor, we should raise an exception.
      return BuildCallRuntime(Runtime::kThrowConstructorNonCallableError,
                              {target_node});
    }
    DCHECK(IsCallable(*target.object()));
    RETURN_IF_DONE(TryReduceBuiltin(target, shared, args, feedback_source));
    RETURN_IF_DONE(TryBuildCallKnownJSFunction(
        target, GetRootConstant(RootIndex::kUndefinedValue), args,
        feedback_source));
  }
  return BuildGenericCall(target_node, Call::TargetType::kJSFunction, args);
}
References v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo(), v8::internal::IsClassConstructor(), v8::internal::compiler::JSFunctionRef::object(), RETURN_IF_DONE, and v8::internal::compiler::JSFunctionRef::shared().
Referenced by TryBuildPropertyGetterCall(), and TryBuildPropertySetterCall().
TryReduceCallForNewClosure()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForNewClosure (ValueNode * target_node, ValueNode * target_context, compiler::SharedFunctionInfoRef shared, compiler::FeedbackCellRef feedback_cell, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11431 of file maglev-graph-builder.cc.
                                                   {
  // Do not reduce calls to functions with break points.
  if (args.mode() != CallArguments::kDefault) {
    // TODO(victorgomes): Maybe inline the spread stub? Or call known function
    // directly if arguments list is an array.
    return {};
  }
  if (!shared.HasBreakInfo(broker())) {
    if (IsClassConstructor(shared.kind())) {
      // If we have a class constructor, we should raise an exception.
      return BuildCallRuntime(Runtime::kThrowConstructorNonCallableError,
                              {target_node});
    }
    RETURN_IF_DONE(TryBuildCallKnownJSFunction(
        target_context, target_node,
        GetRootConstant(RootIndex::kUndefinedValue),
#ifdef V8_ENABLE_LEAPTIERING
        dispatch_handle,
#endif
        shared, feedback_cell, args, feedback_source));
  }
  return BuildGenericCall(target_node, Call::TargetType::kJSFunction, args);
}
References v8::base::args, broker(), v8::internal::IsClassConstructor(), and RETURN_IF_DONE.
TryReduceCallForTarget()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForTarget (ValueNode * target_node, compiler::JSFunctionRef target, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11423 of file maglev-graph-builder.cc.
                                                   {
  RETURN_IF_ABORT(BuildCheckValueByReference(
      target_node, target, DeoptimizeReason::kWrongCallTarget));
  return TryReduceCallForConstant(target, args, feedback_source);
}
References v8::base::args, and RETURN_IF_ABORT.
TryReduceCompareEqualAgainstConstant()
template<Operation kOperation>
bool v8::internal::maglev::MaglevGraphBuilder::TryReduceCompareEqualAgainstConstant [private]
Definition at line 3086 of file maglev-graph-builder.cc.
                                                              {
  if (kOperation != Operation::kStrictEqual && kOperation != Operation::kEqual)
    return false;
  ValueNode* left = LoadRegister(0);
  ValueNode* right = GetAccumulator();
  ValueNode* other = right;
  compiler::OptionalHeapObjectRef maybe_constant = TryGetConstant(left);
  if (!maybe_constant) {
    maybe_constant = TryGetConstant(right);
    other = left;
  }
  if (!maybe_constant) return false;
  if (CheckType(other, NodeType::kBoolean)) {
    auto CompareOtherWith = [&](bool constant) {
      compiler::OptionalHeapObjectRef const_other = TryGetConstant(other);
      if (const_other) {
        auto bool_other = const_other->TryGetBooleanValue(broker());
        if (bool_other.has_value()) {
          SetAccumulator(GetBooleanConstant(constant == *bool_other));
          return;
        }
      }
      if (constant) {
        SetAccumulator(other);
      } else {
        SetAccumulator(AddNewNode<LogicalNot>({other}));
      }
    };
    if (maybe_constant.equals(broker_->true_value())) {
      CompareOtherWith(true);
      return true;
    } else if (maybe_constant.equals(broker_->false_value())) {
      CompareOtherWith(false);
      return true;
    } else if (kOperation == Operation::kEqual) {
      // For `bool == num` we can convert the actual comparison `ToNumber(bool)
      // == num` into `(num == 1) ? bool : ((num == 0) ? !bool : false)`,
      std::optional<double> val = {};
      if (maybe_constant.value().IsSmi()) {
        val = maybe_constant.value().AsSmi();
      } else if (maybe_constant.value().IsHeapNumber()) {
        val = maybe_constant.value().AsHeapNumber().value();
      }
      if (val) {
        if (*val == 0) {
          CompareOtherWith(false);
        } else if (*val == 1) {
          CompareOtherWith(true);
        } else {
          // The constant number is neither equal to `ToNumber(true)` nor
          // `ToNumber(false)`.
          SetAccumulator(GetBooleanConstant(false));
        }
        return true;
      }
    }
  }
  if (kOperation != Operation::kStrictEqual) return false;
  InstanceType type = maybe_constant.value().map(broker()).instance_type();
  if (!InstanceTypeChecker::IsReferenceComparable(type)) return false;
  // If the constant is the undefined value, we can compare it
  // against holey floats.
  if (maybe_constant->IsUndefined()) {
    ValueNode* holey_float = nullptr;
    if (left->properties().value_representation() ==
        ValueRepresentation::kHoleyFloat64) {
      holey_float = left;
    } else if (right->properties().value_representation() ==
               ValueRepresentation::kHoleyFloat64) {
      holey_float = right;
    }
    if (holey_float) {
      SetAccumulator(AddNewNode<HoleyFloat64IsHole>({holey_float}));
      return true;
    }
  }
  if (left->properties().value_representation() !=
          ValueRepresentation::kTagged ||
      right->properties().value_representation() !=
          ValueRepresentation::kTagged) {
    SetAccumulator(GetBooleanConstant(false));
  } else {
    SetAccumulator(BuildTaggedEqual(left, right));
  }
  return true;
}
References broker(), broker_, BuildTaggedEqual(), CheckType(), GetAccumulator(), GetBooleanConstant(), v8::internal::InstanceTypeChecker::IsReferenceComparable(), v8::internal::kEqual, v8::internal::maglev::kHoleyFloat64, v8::kOperation, v8::internal::maglev::kTagged, LoadRegister(), v8::internal::maglev::NodeBase::properties(), SetAccumulator(), TryGetConstant(), v8::internal::tracing::type, and v8::internal::maglev::OpProperties::value_representation().
TryReduceConstantStringAt()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceConstantStringAt (ValueNode * object, ValueNode * index, StringAtOOBMode oob_mode) [private]
Definition at line 9362 of file maglev-graph-builder.cc.
                                                                     {
  auto constant_receiver = TryGetConstant(receiver);
  if (!constant_receiver) return {};
  if (!constant_receiver->IsString()) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kNotAString);
  }
  compiler::StringRef string = constant_receiver->AsString();
  auto maybe_constant_index = TryGetInt32Constant(index);
  if (!maybe_constant_index) return {};
  int32_t constant_index = *maybe_constant_index;
  if (static_cast<uint32_t>(constant_index) >= string.length()) {
    switch (oob_mode) {
      case StringAtOOBMode::kElement:
        // For element access, a negative index triggers a named lookup rather
        // than an element lookup; when this is the case, we shouldn't be trying
        // to optimize an elements access at all, so deopt.
        if (constant_index < 0) {
          return EmitUnconditionalDeopt(DeoptimizeReason::kOutOfBounds);
        }
        // Otherwise, this is hole-like access, so guard against elements on the
        // prototype to return undefined.
        if (broker()->dependencies()->DependOnNoElementsProtector()) {
          return GetRootConstant(RootIndex::kUndefinedValue);
        }
        // If the no elements protector is invalidated, unconditionally deopt.
        // This shouldn't trigger a deopt look because the feedback should
        // transition to megamorphic.
        return EmitUnconditionalDeopt(DeoptimizeReason::kOutOfBounds);
      case StringAtOOBMode::kCharAt: {
        // OOB for charAt is always the empty string.
        return GetRootConstant(RootIndex::kempty_string);
      }
    }
    UNREACHABLE();
  }
  if (std::optional<uint16_t> value =
          string.GetChar(broker(), constant_index)) {
    return GetConstantSingleCharacterStringFromCode(*value);
  }
  return {};
}
References broker(), v8::internal::index, v8::internal::wasm::anonymous_namespace{wasm-external-refs.cc}::kOutOfBounds, v8::internal::length, v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by TryBuildElementAccessOnString().
TryReduceConstruct()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceConstruct (compiler::HeapObjectRef feedback_target, ValueNode * target, ValueNode * new_target, CallArguments & args, compiler::FeedbackSource & feedback_source) [private]
Definition at line 12399 of file maglev-graph-builder.cc.
                                             {
  DCHECK(!feedback_target.IsAllocationSite());
  if (!feedback_target.map(broker()).is_constructor()) {
    // TODO(victorgomes): Deal the case where target is not a constructor.
    return {};
  }
  if (target != new_target) return {};
  // TODO(v8:7700): Add fast paths for other callables.
  if (!feedback_target.IsJSFunction()) return {};
  compiler::JSFunctionRef function = feedback_target.AsJSFunction();
  // Do not inline constructors with break points.
  compiler::SharedFunctionInfoRef shared_function_info =
      function.shared(broker());
  if (shared_function_info.HasBreakInfo(broker())) {
    return {};
  }
  // Do not inline cross natives context.
  if (function.native_context(broker()) != broker()->target_native_context()) {
    return {};
  }
  if (args.mode() != CallArguments::kDefault) {
    // TODO(victorgomes): Maybe inline the spread stub? Or call known
    // function directly if arguments list is an array.
    return {};
  }
  if (shared_function_info.HasBuiltinId()) {
    RETURN_IF_DONE(TryReduceConstructBuiltin(function, shared_function_info,
                                             target, args));
  }
  if (shared_function_info.construct_as_builtin()) {
    // TODO(victorgomes): Inline JSBuiltinsConstructStub.
    return {};
  }
  return TryReduceConstructGeneric(function, shared_function_info, target,
                                   new_target, args, feedback_source);
}
References v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo(), v8::internal::is_constructor, v8::internal::compiler::HeapObjectRef::map(), v8::internal::native_context, and RETURN_IF_DONE.
TryReduceConstructArrayConstructor()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructArrayConstructor (compiler::JSFunctionRef array_function, CallArguments & args, compiler::OptionalAllocationSiteRef maybe_allocation_site = {}) [private]
Definition at line 12213 of file maglev-graph-builder.cc.
                                                             {
  ElementsKind elements_kind =
      maybe_allocation_site.has_value()
          ? maybe_allocation_site->GetElementsKind()
          : array_function.initial_map(broker()).elements_kind();
  // TODO(victorgomes): Support double elements array.
  if (IsDoubleElementsKind(elements_kind)) return {};
  DCHECK(IsFastElementsKind(elements_kind));
  std::optional<int> maybe_length;
  if (args.count() == 1) {
    maybe_length = TryGetInt32Constant(args[0]);
  }
  compiler::OptionalMapRef maybe_initial_map = GetArrayConstructorInitialMap(
      broker(), array_function, elements_kind, args.count(), maybe_length);
  if (!maybe_initial_map.has_value()) return {};
  compiler::MapRef initial_map = maybe_initial_map.value();
  compiler::SlackTrackingPrediction slack_tracking_prediction =
      broker()->dependencies()->DependOnInitialMapInstanceSizePrediction(
          array_function);
  // Tells whether we are protected by either the {site} or a
  // call speculation bit to do certain speculative optimizations.
  bool can_inline_call = false;
  AllocationType allocation_type = AllocationType::kYoung;
  if (maybe_allocation_site) {
    can_inline_call = maybe_allocation_site->CanInlineCall();
    allocation_type =
        broker()->dependencies()->DependOnPretenureMode(*maybe_allocation_site);
    broker()->dependencies()->DependOnElementsKind(*maybe_allocation_site);
  } else {
    can_inline_call = CanSpeculateCall();
  }
  if (args.count() == 0) {
    return BuildAndAllocateJSArray(
        initial_map, GetSmiConstant(0),
        BuildElementsArray(JSArray::kPreallocatedArrayElements),
        slack_tracking_prediction, allocation_type);
  }
  if (maybe_length.has_value() && *maybe_length >= 0 &&
      *maybe_length < JSArray::kInitialMaxFastElementArray) {
    return BuildAndAllocateJSArray(initial_map, GetSmiConstant(*maybe_length),
                                   BuildElementsArray(*maybe_length),
                                   slack_tracking_prediction, allocation_type);
  }
  // TODO(victorgomes): If we know the argument cannot be a number, we should
  // allocate an array with one element.
  // We don't know anything about the length, so we rely on the allocation
  // site to avoid deopt loops.
  if (args.count() == 1 && can_inline_call) {
    return SelectReduction(
        [&](auto& builder) {
          return BuildBranchIfInt32Compare(builder,
                                           Operation::kGreaterThanOrEqual,
                                           args[0], GetInt32Constant(0));
        },
        [&] {
          ValueNode* elements =
              AddNewNode<AllocateElementsArray>({args[0]}, allocation_type);
          return BuildAndAllocateJSArray(initial_map, args[0], elements,
                                         slack_tracking_prediction,
                                         allocation_type);
        },
        [&] {
          ValueNode* error = GetSmiConstant(
              static_cast<int>(MessageTemplate::kInvalidArrayLength));
          return BuildCallRuntime(Runtime::kThrowRangeError, {error});
        });
  }
  // TODO(victorgomes): Support the constructor with argument count larger
  // than 1.
  return {};
}
References v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetArrayConstructorInitialMap(), v8::internal::compiler::initial_map, v8::internal::compiler::JSFunctionRef::initial_map(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::JSArray::kPreallocatedArrayElements, and v8::internal::kYoung.
TryReduceConstructBuiltin()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructBuiltin (compiler::JSFunctionRef builtin, compiler::SharedFunctionInfoRef shared_function_info, ValueNode * target, CallArguments & args) [private]
Definition at line 12294 of file maglev-graph-builder.cc.
                         {
  // TODO(victorgomes): specialize more known constants builtin targets.
  switch (shared_function_info.builtin_id()) {
    case Builtin::kArrayConstructor: {
      RETURN_IF_DONE(TryReduceConstructArrayConstructor(builtin, args));
      break;
    }
    case Builtin::kObjectConstructor: {
      // If no value is passed, we can immediately lower to a simple
      // constructor.
      if (args.count() == 0) {
        RETURN_IF_ABORT(BuildCheckValueByReference(
            target, builtin, DeoptimizeReason::kWrongConstructor));
        ValueNode* result = BuildInlinedAllocation(CreateJSConstructor(builtin),
                                                   AllocationType::kYoung);
        return result;
      }
      break;
    }
    default:
      break;
  }
  return {};
}
References v8::base::args, v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::kYoung, v8::base::internal::result, RETURN_IF_ABORT, and RETURN_IF_DONE.
TryReduceConstructGeneric()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric (compiler::JSFunctionRef function, compiler::SharedFunctionInfoRef shared_function_info, ValueNode * target, ValueNode * new_target, CallArguments & args, compiler::FeedbackSource & feedback_source) [private]
Definition at line 12322 of file maglev-graph-builder.cc.
                                             {
  RETURN_IF_ABORT(BuildCheckValueByReference(
      target, function, DeoptimizeReason::kWrongConstructor));
  int construct_arg_count = static_cast<int>(args.count());
  base::Vector<ValueNode*> construct_arguments_without_receiver =
      zone()->AllocateVector<ValueNode*>(construct_arg_count);
  for (int i = 0; i < construct_arg_count; i++) {
    construct_arguments_without_receiver[i] = args[i];
  }
  if (IsDerivedConstructor(shared_function_info.kind())) {
    ValueNode* implicit_receiver = GetRootConstant(RootIndex::kTheHoleValue);
    args.set_receiver(implicit_receiver);
    ValueNode* call_result;
    {
      DeoptFrameScope construct(this, implicit_receiver);
      MaybeReduceResult result = TryBuildCallKnownJSFunction(
          function, new_target, args, feedback_source);
      RETURN_IF_ABORT(result);
      call_result = result.value();
    }
    if (CheckType(call_result, NodeType::kJSReceiver)) return call_result;
    ValueNode* constant_node;
    if (compiler::OptionalHeapObjectRef maybe_constant =
            TryGetConstant(call_result, &constant_node)) {
      compiler::HeapObjectRef constant = maybe_constant.value();
      if (constant.IsJSReceiver()) return constant_node;
    }
    if (!call_result->properties().is_tagged()) {
      return BuildCallRuntime(Runtime::kThrowConstructorReturnedNonObject, {});
    }
    return AddNewNode<CheckDerivedConstructResult>({call_result});
  }
  // We do not create a construct stub lazy deopt frame, since
  // FastNewObject cannot fail if target is a JSFunction.
  ValueNode* implicit_receiver = nullptr;
  if (function.has_initial_map(broker())) {
    compiler::MapRef map = function.initial_map(broker());
    if (map.GetConstructor(broker()).equals(function)) {
      implicit_receiver = BuildInlinedAllocation(CreateJSConstructor(function),
                                                 AllocationType::kYoung);
    }
  }
  if (implicit_receiver == nullptr) {
    implicit_receiver = BuildCallBuiltin<Builtin::kFastNewObject>(
        {GetTaggedValue(target), GetTaggedValue(new_target)});
  }
  EnsureType(implicit_receiver, NodeType::kJSReceiver);
  args.set_receiver(implicit_receiver);
  ValueNode* call_result;
  {
    DeoptFrameScope construct(this, implicit_receiver);
    MaybeReduceResult result = TryBuildCallKnownJSFunction(
        function, new_target, args, feedback_source);
    RETURN_IF_ABORT(result);
    call_result = result.value();
  }
  if (CheckType(call_result, NodeType::kJSReceiver)) return call_result;
  if (!call_result->properties().is_tagged()) return implicit_receiver;
  ValueNode* constant_node;
  if (compiler::OptionalHeapObjectRef maybe_constant =
          TryGetConstant(call_result, &constant_node)) {
    compiler::HeapObjectRef constant = maybe_constant.value();
    DCHECK(CheckType(implicit_receiver, NodeType::kJSReceiver));
    if (constant.IsJSReceiver()) return constant_node;
    return implicit_receiver;
  }
  return AddNewNode<CheckConstructResult>({call_result, implicit_receiver});
}
References v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::GetConstructor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::OpProperties::is_tagged(), v8::internal::IsDerivedConstructor(), v8::internal::kYoung, v8::internal::maglev::NodeBase::properties(), v8::base::internal::result, RETURN_IF_ABORT, and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
TryReduceDatePrototypeGetField()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField (compiler::JSFunctionRef target, CallArguments & args, JSDate::FieldIndex field) [private]
Definition at line 9789 of file maglev-graph-builder.cc.
                                  {
  DCHECK_LT(field_index, JSDate::kFirstUncachedField);
  if (!v8_flags.maglev_inline_date_accessors) return {};
  if (!CanSpeculateCall()) return {};
  if (args.receiver_mode() == ConvertReceiverMode::kNullOrUndefined) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce Date.prototype.GetXXX - no receiver"
                << std::endl;
    }
    return {};
  }
  ValueNode* receiver = GetValueOrUndefined(args.receiver());
  const NodeInfo* receiver_info = known_node_aspects().TryGetInfoFor(receiver);
  // If the map set is not found, then we don't know anything about the map of
  // the receiver, so bail.
  if (!receiver_info || !receiver_info->possible_maps_are_known()) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout
          << " ! Failed to reduce Date.prototype.GetXXX - unknown receiver map"
          << std::endl;
    }
    return {};
  }
  const PossibleMaps& possible_receiver_maps = receiver_info->possible_maps();
  // If the set of possible maps is empty, then there's no possible map for this
  // receiver, therefore this path is unreachable at runtime. We're unlikely to
  // ever hit this case, BuildCheckMaps should already unconditionally deopt,
  // but check it in case another checking operation fails to statically
  // unconditionally deopt.
  if (possible_receiver_maps.is_empty()) {
    // TODO(leszeks): Add an unreachable assert here.
    return ReduceResult::DoneWithAbort();
  }
  if (!AllOfInstanceTypesAre(possible_receiver_maps, JS_DATE_TYPE)) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout
          << " ! Failed to reduce Date.prototype.GetXXX - wrong receiver maps "
          << std::endl;
    }
    return {};
  }
  if (!broker()
           ->dependencies()
           ->DependOnNoDateTimeConfigurationChangeProtector()) {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " ! Failed to reduce Date.prototype.GetXXX - "
                   "NoDateTimeConfigurationChangeProtector invalidated"
                << std::endl;
    }
    return {};
  }
  int field_offset = JSDate::kYearOffset + field_index * kTaggedSize;
  ValueNode* field_value = BuildLoadTaggedField(receiver, field_offset);
  return field_value;
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AllOfInstanceTypesAre(), v8::base::args, broker(), DCHECK_LT, v8::internal::ZoneCompactSet< T >::is_empty(), v8::internal::JSDate::kFirstUncachedField, v8::internal::kNullOrUndefined, v8::internal::kTaggedSize, v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), and v8::internal::v8_flags.
TryReduceFunctionPrototypeApplyCallWithReceiver()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceFunctionPrototypeApplyCallWithReceiver (compiler::OptionalHeapObjectRef maybe_receiver, CallArguments & args, const compiler::FeedbackSource & feedback_source) [private]
Definition at line 11463 of file maglev-graph-builder.cc.
                                                   {
  if (args.mode() != CallArguments::kDefault) return {};
  ValueNode* function = GetValueOrUndefined(args.receiver());
  if (maybe_receiver.has_value()) {
    RETURN_IF_ABORT(BuildCheckValueByReference(
        function, maybe_receiver.value(), DeoptimizeReason::kWrongCallTarget));
    function = GetConstant(maybe_receiver.value());
  }
  SaveCallSpeculationScope saved(this);
  if (args.count() == 0) {
    CallArguments empty_args(ConvertReceiverMode::kNullOrUndefined);
    return ReduceCall(function, empty_args, feedback_source);
  }
  auto build_call_only_with_new_receiver = [&] {
    CallArguments new_args(ConvertReceiverMode::kAny, {args[0]});
    return ReduceCall(function, new_args, feedback_source);
  };
  if (args.count() == 1 || IsNullValue(args[1]) || IsUndefinedValue(args[1])) {
    return build_call_only_with_new_receiver();
  }
  auto build_call_with_array_like = [&] {
    CallArguments new_args(ConvertReceiverMode::kAny, {args[0], args[1]},
                           CallArguments::kWithArrayLike);
    return ReduceCallWithArrayLike(function, new_args, feedback_source);
  };
  if (!known_node_aspects().MayBeNullOrUndefined(broker(), args[1])) {
    return build_call_with_array_like();
  }
  return SelectReduction(
      [&](auto& builder) {
        return BuildBranchIfUndefinedOrNull(builder, args[1]);
      },
      build_call_only_with_new_receiver, build_call_with_array_like);
}
References v8::base::args, broker(), v8::internal::kAny, v8::internal::kNullOrUndefined, and RETURN_IF_ABORT.
TryReduceGetIterator()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator (ValueNode * receiver, int load_slot, int call_slot) [private]
Definition at line 15486 of file maglev-graph-builder.cc.
                                                                   {
  // Load iterator method property.
  FeedbackSlot load_slot = FeedbackVector::ToSlot(load_slot_index);
  compiler::FeedbackSource load_feedback{feedback(), load_slot};
  compiler::NameRef iterator_symbol = broker()->iterator_symbol();
  ValueNode* iterator_method;
  {
    DeoptFrameScope deopt_continuation(
        this, Builtin::kGetIteratorWithFeedbackLazyDeoptContinuation, {},
        base::VectorOf<ValueNode*>({receiver, GetSmiConstant(call_slot_index),
                                    GetConstant(feedback())}));
    MaybeReduceResult result_load =
        TryBuildLoadNamedProperty(receiver, iterator_symbol, load_feedback);
    if (result_load.IsDoneWithAbort() || result_load.IsFail()) {
      return result_load;
    }
    DCHECK(result_load.IsDoneWithValue());
    iterator_method = result_load.value();
  }
  auto throw_iterator_error = [&] {
    return BuildCallRuntime(Runtime::kThrowIteratorError, {receiver});
  };
  if (!iterator_method->is_tagged()) {
    return throw_iterator_error();
  }
  auto throw_symbol_iterator_invalid = [&] {
    return BuildCallRuntime(Runtime::kThrowSymbolIteratorInvalid, {});
  };
  auto call_iterator_method = [&] {
    DeoptFrameScope deopt_continuation(
        this, Builtin::kCallIteratorWithFeedbackLazyDeoptContinuation);
    FeedbackSlot call_slot = FeedbackVector::ToSlot(call_slot_index);
    compiler::FeedbackSource call_feedback{feedback(), call_slot};
    CallArguments args(ConvertReceiverMode::kAny, {receiver});
    MaybeReduceResult result_call =
        ReduceCall(iterator_method, args, call_feedback);
    if (result_call.IsDoneWithAbort()) return result_call;
    DCHECK(result_call.IsDoneWithValue());
    return SelectReduction(
        [&](auto& builder) {
          return BuildBranchIfJSReceiver(builder, result_call.value());
        },
        [&] { return result_call; }, throw_symbol_iterator_invalid);
  };
  // Check if the iterator_method is undefined and call the method otherwise.
  return SelectReduction(
      [&](auto& builder) {
        return BuildBranchIfUndefined(builder, iterator_method);
      },
      throw_iterator_error, call_iterator_method);
}
References v8::base::args, broker(), v8::internal::DCHECK(), v8::internal::maglev::ValueNode::is_tagged(), v8::internal::maglev::MaybeReduceResult::IsDoneWithAbort(), v8::internal::maglev::MaybeReduceResult::IsDoneWithValue(), v8::internal::maglev::MaybeReduceResult::IsFail(), v8::internal::kAny, v8::internal::FeedbackVector::ToSlot(), and v8::internal::maglev::MaybeReduceResult::value().
TryReduceGetProto()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto (ValueNode * node) [private]
Definition at line 10560 of file maglev-graph-builder.cc.
                                                                         {
  NodeInfo* info = known_node_aspects().TryGetInfoFor(object);
  if (!info || !info->possible_maps_are_known()) {
    return {};
  }
  auto& possible_maps = info->possible_maps();
  if (possible_maps.is_empty()) {
    return ReduceResult::DoneWithAbort();
  }
  auto it = possible_maps.begin();
  compiler::MapRef map = *it;
  if (IsSpecialReceiverInstanceType(map.instance_type())) {
    return {};
  }
  DCHECK(!map.IsPrimitiveMap() && map.IsJSReceiverMap());
  compiler::HeapObjectRef proto = map.prototype(broker());
  ++it;
  for (; it != possible_maps.end(); ++it) {
    map = *it;
    if (IsSpecialReceiverInstanceType(map.instance_type()) ||
        !proto.equals(map.prototype(broker()))) {
      return {};
    }
    DCHECK(!map.IsPrimitiveMap() && map.IsJSReceiverMap());
  }
  return GetConstant(proto);
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::IsPrimitiveMap(), v8::internal::IsSpecialReceiverInstanceType(), v8::internal::maglev::NodeInfo::possible_maps(), v8::internal::maglev::NodeInfo::possible_maps_are_known(), and v8::internal::compiler::MapRef::prototype().
TryReduceTypeOf() [1/2]
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceTypeOf (ValueNode * value) [private]
Definition at line 4079 of file maglev-graph-builder.cc.
                                                                      {
  return TryReduceTypeOf(value,
                         [&](TypeOfLiteralFlag _, RootIndex idx) -> ValueNode* {
                           return GetRootConstant(idx);
                         });
}
References _, GetRootConstant(), TryReduceTypeOf(), and v8::internal::value.
TryReduceTypeOf() [2/2]
template<typename Function >
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReduceTypeOf (ValueNode * value, const Function & GetResult) [private]
Definition at line 4033 of file maglev-graph-builder.cc.
                                                 {
  // Similar to TF, we assume that all undetectable receiver objects are also
  // callables. In practice, there is only one: document.all.
  switch (CheckTypes(
      value, {NodeType::kBoolean, NodeType::kNumber, NodeType::kString,
              NodeType::kSymbol, NodeType::kCallable, NodeType::kJSArray})) {
    case NodeType::kBoolean:
      return GetResult(TypeOfLiteralFlag::kBoolean, RootIndex::kboolean_string);
    case NodeType::kNumber:
      return GetResult(TypeOfLiteralFlag::kNumber, RootIndex::knumber_string);
    case NodeType::kString:
      return GetResult(TypeOfLiteralFlag::kString, RootIndex::kstring_string);
    case NodeType::kSymbol:
      return GetResult(TypeOfLiteralFlag::kSymbol, RootIndex::ksymbol_string);
    case NodeType::kCallable:
      return Select(
          [&](auto& builder) {
            return BuildBranchIfUndetectable(builder, value);
          },
          [&] {
            return GetResult(TypeOfLiteralFlag::kUndefined,
                             RootIndex::kundefined_string);
          },
          [&] {
            return GetResult(TypeOfLiteralFlag::kFunction,
                             RootIndex::kfunction_string);
          });
    case NodeType::kJSArray:
      // TODO(victorgomes): Track JSReceiver, non-callable types in Maglev.
      return GetResult(TypeOfLiteralFlag::kObject, RootIndex::kobject_string);
    default:
      break;
  }
  if (IsNullValue(value)) {
    return GetResult(TypeOfLiteralFlag::kObject, RootIndex::kobject_string);
  }
  if (IsUndefinedValue(value)) {
    return GetResult(TypeOfLiteralFlag::kUndefined,
                     RootIndex::kundefined_string);
  }
  return {};
}
References BuildBranchIfUndetectable(), CheckTypes(), v8::internal::torque::ls::kFunction, Select(), and v8::internal::value.
Referenced by TryReduceTypeOf().
TryReuseKnownPropertyLoad()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TryReuseKnownPropertyLoad (ValueNode * lookup_start_object, compiler::NameRef name) [private]
Definition at line 7430 of file maglev-graph-builder.cc.
                                                          {
  if (MaybeReduceResult result = TryFindLoadedProperty(
          known_node_aspects().loaded_properties, lookup_start_object, name);
      result.IsDone()) {
    if (v8_flags.trace_maglev_graph_building && result.IsDoneWithValue()) {
      std::cout << " * Reusing non-constant loaded property "
                << PrintNodeLabel(graph_labeller(), result.value()) << ": "
                << PrintNode(graph_labeller(), result.value()) << std::endl;
    }
    return result;
  }
  if (MaybeReduceResult result =
          TryFindLoadedProperty(known_node_aspects().loaded_constant_properties,
                                lookup_start_object, name);
      result.IsDone()) {
    if (v8_flags.trace_maglev_graph_building && result.IsDoneWithValue()) {
      std::cout << " * Reusing constant loaded property "
                << PrintNodeLabel(graph_labeller(), result.value()) << ": "
                << PrintNode(graph_labeller(), result.value()) << std::endl;
    }
    return result;
  }
  return {};
}
References v8::internal::name, v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::base::internal::result, v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::TryFindLoadedProperty(), and v8::internal::v8_flags.
Referenced by BuildLoadJSArrayLength().
TrySpecializeLoadContextSlot()
ValueNode * v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot (ValueNode * context, int index) [private]
Definition at line 3513 of file maglev-graph-builder.cc.
                                        {
  if (!context_node->Is<Constant>()) return {};
  compiler::ContextRef context =
      context_node->Cast<Constant>()->ref().AsContext();
  auto maybe_value = context.get(broker(), index);
  if (!maybe_value || maybe_value->IsTheHole() ||
      maybe_value->IsUndefinedContextCell()) {
    return {};
  }
  int offset = Context::OffsetOfElementAt(index);
  if (!maybe_value->IsContextCell()) {
    // No need to check for context cells anymore.
    return BuildLoadTaggedField<LoadTaggedFieldForContextSlotNoCells>(
        context_node, offset);
  }
  compiler::ContextCellRef slot_ref = maybe_value->AsContextCell();
  ContextCell::State state = slot_ref.state();
  switch (state) {
    case ContextCell::kConst: {
      auto constant = slot_ref.tagged_value(broker());
      if (!constant.has_value()) {
        return BuildLoadTaggedField<LoadTaggedFieldForContextSlotNoCells>(
            context_node, offset);
      }
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      return GetConstant(*constant);
    }
    case ContextCell::kSmi: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      ValueNode* value = BuildLoadTaggedField(
          GetConstant(slot_ref), offsetof(ContextCell, tagged_value_));
      EnsureType(value, NodeType::kSmi);
      return value;
    }
    case ContextCell::kInt32:
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      return AddNewNode<LoadInt32>(
          {GetConstant(slot_ref)},
          static_cast<int>(offsetof(ContextCell, double_value_)));
    case ContextCell::kFloat64:
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      return AddNewNode<LoadFloat64>(
          {GetConstant(slot_ref)},
          static_cast<int>(offsetof(ContextCell, double_value_)));
    case ContextCell::kDetached:
      return BuildLoadTaggedField<LoadTaggedFieldForContextSlotNoCells>(
          context_node, offset);
  }
  UNREACHABLE();
}
References broker(), BuildLoadTaggedField(), v8::internal::maglev::NodeBase::Cast(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), EnsureType(), v8::internal::compiler::ContextRef::get(), GetConstant(), v8::internal::index, v8::internal::maglev::NodeBase::Is(), v8::internal::ContextCell::kConst, v8::internal::ContextCell::kDetached, v8::internal::ContextCell::kFloat64, v8::internal::ContextCell::kInt32, v8::internal::compiler::kSmi, v8::internal::ContextCell::kSmi, v8::internal::Context::OffsetOfElementAt(), v8::internal::compiler::ContextCellRef::state(), v8::internal::compiler::ContextCellRef::tagged_value(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by LoadAndCacheContextSlot().
TrySpecializeLoadContextSlotToFunctionContext()
bool v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlotToFunctionContext (ValueNode * context, int slot_index, ContextSlotMutability slot_mutability) [private]
Definition at line 3475 of file maglev-graph-builder.cc.
                                                                               {
  DCHECK(compilation_unit_->info()->specialize_to_function_context());
  if (slot_mutability == kMutable) return false;
  auto constant = TryGetConstant(context);
  if (!constant) return false;
  compiler::ContextRef context_ref = constant.value().AsContext();
  compiler::OptionalObjectRef maybe_slot_value =
      context_ref.get(broker(), slot_index);
  if (!maybe_slot_value.has_value()) return false;
  compiler::ObjectRef slot_value = maybe_slot_value.value();
  if (slot_value.IsHeapObject()) {
    // Even though the context slot is immutable, the context might have escaped
    // before the function to which it belongs has initialized the slot. We
    // must be conservative and check if the value in the slot is currently the
    // hole or undefined. Only if it is neither of these, can we be sure that it
    // won't change anymore.
    //
    // See also: JSContextSpecialization::ReduceJSLoadContext.
    compiler::OddballType oddball_type =
        slot_value.AsHeapObject().map(broker()).oddball_type(broker());
    if (oddball_type == compiler::OddballType::kUndefined ||
        slot_value.IsTheHole()) {
      return false;
    }
  }
  // Fold the load of the immutable slot.
  SetAccumulator(GetConstant(slot_value));
  return true;
}
References broker(), compilation_unit_, v8::internal::DCHECK(), v8::internal::compiler::ContextRef::get(), GetConstant(), v8::internal::maglev::MaglevCompilationUnit::info(), kMutable, v8::internal::compiler::kUndefined, SetAccumulator(), v8::internal::maglev::MaglevCompilationInfo::specialize_to_function_context(), and TryGetConstant().
Referenced by BuildLoadContextSlot().
TrySpecializeStoreContextSlot()
MaybeReduceResult v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot (ValueNode * context, int index, ValueNode * value, Node ** store) [private]
Definition at line 3617 of file maglev-graph-builder.cc.
                                                                   {
  DCHECK_NOT_NULL(store);
  DCHECK(v8_flags.script_context_cells || v8_flags.function_context_cells);
  if (!context->Is<Constant>()) {
    *store =
        AddNewNode<StoreContextSlotWithWriteBarrier>({context, value}, index);
    return ReduceResult::Done();
  }
  if (IsEmptyNodeType(GetType(value))) {
    return EmitUnconditionalDeopt(DeoptimizeReason::kWrongValue);
  }
  compiler::ContextRef context_ref =
      context->Cast<Constant>()->ref().AsContext();
  auto maybe_value = context_ref.get(broker(), index);
  if (!maybe_value || maybe_value->IsTheHole() ||
      maybe_value->IsUndefinedContextCell()) {
    *store =
        AddNewNode<StoreContextSlotWithWriteBarrier>({context, value}, index);
    return ReduceResult::Done();
  }
  int offset = Context::OffsetOfElementAt(index);
  if (!maybe_value->IsContextCell()) {
    *store = BuildStoreTaggedField(context, value, offset,
                                   StoreTaggedMode::kDefault);
    return ReduceResult::Done();
  }
  compiler::ContextCellRef slot_ref = maybe_value->AsContextCell();
  ContextCell::State state = slot_ref.state();
  switch (state) {
    case ContextCell::kConst: {
      auto constant = slot_ref.tagged_value(broker());
      if (!constant.has_value() ||
          (constant->IsString() && !constant->IsInternalizedString())) {
        *store = AddNewNode<StoreContextSlotWithWriteBarrier>({context, value},
                                                              index);
        return ReduceResult::Done();
      }
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      return BuildCheckNumericalValueOrByReference(
          value, *constant, DeoptimizeReason::kStoreToConstant);
    }
    case ContextCell::kSmi:
      RETURN_IF_ABORT(BuildCheckSmi(value));
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      *store = BuildStoreTaggedFieldNoWriteBarrier(
          GetConstant(slot_ref), value, offsetof(ContextCell, tagged_value_),
          StoreTaggedMode::kDefault);
      return ReduceResult::Done();
    case ContextCell::kInt32:
      EnsureInt32(value, true);
      *store = AddNewNode<StoreInt32>(
          {GetConstant(slot_ref), value},
          static_cast<int>(offsetof(ContextCell, double_value_)));
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      return ReduceResult::Done();
    case ContextCell::kFloat64:
      RETURN_IF_ABORT(BuildCheckNumber(value));
      *store = AddNewNode<StoreFloat64>(
          {GetConstant(slot_ref), value},
          static_cast<int>(offsetof(ContextCell, double_value_)));
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      return ReduceResult::Done();
    case ContextCell::kDetached:
      *store = BuildStoreTaggedField(context, value, offset,
                                     StoreTaggedMode::kDefault);
      return ReduceResult::Done();
  }
  UNREACHABLE();
}
References broker(), BuildCheckNumber(), BuildCheckNumericalValueOrByReference(), BuildCheckSmi(), BuildStoreTaggedField(), BuildStoreTaggedFieldNoWriteBarrier(), v8::internal::maglev::NodeBase::Cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), EnsureInt32(), v8::internal::compiler::ContextRef::get(), GetConstant(), GetType(), v8::internal::index, v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::IsEmptyNodeType(), v8::internal::ContextCell::kConst, v8::internal::maglev::kDefault, v8::internal::ContextCell::kDetached, v8::internal::ContextCell::kFloat64, v8::internal::ContextCell::kInt32, v8::internal::ContextCell::kSmi, v8::internal::Context::OffsetOfElementAt(), RETURN_IF_ABORT, v8::internal::compiler::ContextCellRef::state(), store(), v8::internal::compiler::ContextCellRef::tagged_value(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::value.
Referenced by StoreAndCacheContextSlot().
UpdatePredecessorCount()
void v8::internal::maglev::MaglevGraphBuilder::UpdatePredecessorCount (uint32_t offset, int diff) [inline], [private]
Definition at line 3203 of file maglev-graph-builder.h.
                                                         {
    DCHECK_LE(offset, bytecode().length());
    DCHECK_LE(0, static_cast<int64_t>(predecessor_count_[offset]) + diff);
    DCHECK_IMPLIES(merge_states_[offset],
                   merge_states_[offset]->predecessor_count() ==
                       predecessor_count_[offset] + diff);
    predecessor_count_[offset] += diff;
  }
References DCHECK_IMPLIES, DCHECK_LE, and v8::internal::length.
Referenced by KillPeeledLoopTargets().
UpdateSourceAndBytecodePosition()
void v8::internal::maglev::MaglevGraphBuilder::UpdateSourceAndBytecodePosition (int offset) [inline], [private]
Definition at line 809 of file maglev-graph-builder.h.
                                                   {
    if (source_position_iterator_.done()) return;
    if (source_position_iterator_.code_offset() == offset) {
      current_source_position_ = SourcePosition(
          source_position_iterator_.source_position().ScriptOffset(),
          inlining_id_);
      source_position_iterator_.Advance();
    } else {
      DCHECK_GT(source_position_iterator_.code_offset(), offset);
    }
  }
References v8::internal::SourcePositionTableIterator::Advance(), v8::internal::SourcePositionTableIterator::code_offset(), current_source_position_, DCHECK_GT, v8::internal::SourcePositionTableIterator::done(), inlining_id_, v8::internal::SourcePosition::ScriptOffset(), v8::internal::SourcePositionTableIterator::source_position(), and source_position_iterator_.
Referenced by VisitSingleBytecode().
VisitBinaryOperation()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::VisitBinaryOperation [private]
Definition at line 2938 of file maglev-graph-builder.cc.
                                                      {
  FeedbackNexus nexus = FeedbackNexusForOperand(1);
  BinaryOperationHint feedback_hint = nexus.GetBinaryOperationFeedback();
  switch (feedback_hint) {
    case BinaryOperationHint::kNone:
      return EmitUnconditionalDeopt(
          DeoptimizeReason::kInsufficientTypeFeedbackForBinaryOperation);
    case BinaryOperationHint::kSignedSmall:
    case BinaryOperationHint::kSignedSmallInputs:
    case BinaryOperationHint::kAdditiveSafeInteger:
    case BinaryOperationHint::kNumber:
    case BinaryOperationHint::kNumberOrOddball: {
      auto [allowed_input_type, conversion_type] =
          BinopHintToNodeTypeAndConversionType(feedback_hint);
      if constexpr (BinaryOperationIsBitwiseInt32<kOperation>()) {
        return BuildTruncatingInt32BinaryOperationNodeForToNumber<kOperation>(
            allowed_input_type, conversion_type);
      } else if (feedback_hint == BinaryOperationHint::kSignedSmall) {
        if constexpr (kOperation == Operation::kExponentiate) {
          // Exponentiate never updates the feedback to be a Smi.
          UNREACHABLE();
        } else {
          return BuildInt32BinaryOperationNode<kOperation>();
        }
      } else {
        return BuildFloat64BinaryOperationNodeForToNumber<kOperation>(
            allowed_input_type, conversion_type);
      }
      break;
    }
    case BinaryOperationHint::kString:
      if constexpr (kOperation == Operation::kAdd) {
        ValueNode* left = LoadRegister(0);
        ValueNode* right = GetAccumulator();
        return BuildStringConcat(left, right);
      }
      break;
    case BinaryOperationHint::kStringOrStringWrapper:
      if constexpr (kOperation == Operation::kAdd) {
        if (broker()
                ->dependencies()
                ->DependOnStringWrapperToPrimitiveProtector()) {
          ValueNode* left = LoadRegister(0);
          ValueNode* right = GetAccumulator();
          RETURN_IF_ABORT(BuildCheckStringOrStringWrapper(left));
          RETURN_IF_ABORT(BuildCheckStringOrStringWrapper(right));
          left = BuildUnwrapStringWrapper(left);
          right = BuildUnwrapStringWrapper(right);
          return BuildStringConcat(left, right);
        }
      }
      [[fallthrough]];
    case BinaryOperationHint::kBigInt:
    case BinaryOperationHint::kBigInt64:
    case BinaryOperationHint::kAny:
      // Fallback to generic node.
      break;
  }
  BuildGenericBinaryOperationNode<kOperation>();
  return ReduceResult::Done();
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::BinopHintToNodeTypeAndConversionType(), broker(), BuildCheckStringOrStringWrapper(), BuildStringConcat(), BuildUnwrapStringWrapper(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), FeedbackNexusForOperand(), GetAccumulator(), v8::internal::FeedbackNexus::GetBinaryOperationFeedback(), v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrOddball, v8::kOperation, v8::internal::kSignedSmall, v8::internal::kSignedSmallInputs, v8::internal::kString, v8::internal::kStringOrStringWrapper, LoadRegister(), RETURN_IF_ABORT, and v8::internal::UNREACHABLE().
VisitBinarySmiOperation()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::VisitBinarySmiOperation [private]
Definition at line 3001 of file maglev-graph-builder.cc.
                                                         {
  FeedbackNexus nexus = FeedbackNexusForOperand(1);
  BinaryOperationHint feedback_hint = nexus.GetBinaryOperationFeedback();
  switch (feedback_hint) {
    case BinaryOperationHint::kNone:
      return EmitUnconditionalDeopt(
          DeoptimizeReason::kInsufficientTypeFeedbackForBinaryOperation);
    case BinaryOperationHint::kSignedSmall:
    case BinaryOperationHint::kSignedSmallInputs:
    case BinaryOperationHint::kAdditiveSafeInteger:
    case BinaryOperationHint::kNumber:
    case BinaryOperationHint::kNumberOrOddball: {
      const auto [allowed_input_type, conversion_type] =
          BinopHintToNodeTypeAndConversionType(feedback_hint);
      if constexpr (BinaryOperationIsBitwiseInt32<kOperation>()) {
        return BuildTruncatingInt32BinarySmiOperationNodeForToNumber<
            kOperation>(allowed_input_type, conversion_type);
      } else if (feedback_hint == BinaryOperationHint::kSignedSmall) {
        if constexpr (kOperation == Operation::kExponentiate) {
          // Exponentiate never updates the feedback to be a Smi.
          UNREACHABLE();
        } else {
          return BuildInt32BinarySmiOperationNode<kOperation>();
        }
      } else {
        return BuildFloat64BinarySmiOperationNodeForToNumber<kOperation>(
            allowed_input_type, conversion_type);
      }
      break;
    }
    case BinaryOperationHint::kString:
    case BinaryOperationHint::kStringOrStringWrapper:
    case BinaryOperationHint::kBigInt:
    case BinaryOperationHint::kBigInt64:
    case BinaryOperationHint::kAny:
      // Fallback to generic node.
      break;
  }
  BuildGenericBinarySmiOperationNode<kOperation>();
  return ReduceResult::Done();
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::BinopHintToNodeTypeAndConversionType(), BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), FeedbackNexusForOperand(), v8::internal::FeedbackNexus::GetBinaryOperationFeedback(), v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrOddball, v8::kOperation, v8::internal::kSignedSmall, v8::internal::kSignedSmallInputs, v8::internal::kString, v8::internal::kStringOrStringWrapper, and v8::internal::UNREACHABLE().
VisitCompareOperation()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation [private]
Definition at line 3182 of file maglev-graph-builder.cc.
                                                       {
  if (TryReduceCompareEqualAgainstConstant<kOperation>())
    return ReduceResult::Done();
  // Compare opcodes are not always commutative. We sort the ones which are for
  // better CSE coverage.
  auto SortCommute = [](ValueNode*& left, ValueNode*& right) {
    if (!v8_flags.maglev_cse) return;
    if (kOperation != Operation::kEqual &&
        kOperation != Operation::kStrictEqual) {
      return;
    }
    if (left > right) {
      std::swap(left, right);
    }
  };
  auto TryConstantFoldInt32 = [&](ValueNode* left, ValueNode* right) {
    if (left->Is<Int32Constant>() && right->Is<Int32Constant>()) {
      int left_value = left->Cast<Int32Constant>()->value();
      int right_value = right->Cast<Int32Constant>()->value();
      SetAccumulator(GetBooleanConstant(
          OperationValue<kOperation>(left_value, right_value)));
      return true;
    }
    return false;
  };
  auto TryConstantFoldEqual = [&](ValueNode* left, ValueNode* right) {
    if (left == right) {
      SetAccumulator(
          GetBooleanConstant(kOperation == Operation::kEqual ||
                             kOperation == Operation::kStrictEqual ||
                             kOperation == Operation::kLessThanOrEqual ||
                             kOperation == Operation::kGreaterThanOrEqual));
      return true;
    }
    return false;
  };
  auto MaybeOddballs = [&]() {
    auto MaybeOddball = [&](ValueNode* value) {
      ValueRepresentation rep = value->value_representation();
      switch (rep) {
        case ValueRepresentation::kInt32:
        case ValueRepresentation::kUint32:
        case ValueRepresentation::kFloat64:
          return false;
        default:
          break;
      }
      return !CheckType(value, NodeType::kNumber);
    };
    return MaybeOddball(LoadRegister(0)) || MaybeOddball(GetAccumulator());
  };
  // TODO(victorgomes): Investigate if we can just propagate one of the types
  // instead.
  auto GetConversionType = [](CompareOperationHint hint) {
    switch (hint) {
      case CompareOperationHint::kNumber:
        return std::make_pair(NodeType::kNumber,
                              TaggedToFloat64ConversionType::kOnlyNumber);
      case CompareOperationHint::kNumberOrBoolean:
        return std::make_pair(NodeType::kNumberOrBoolean,
                              TaggedToFloat64ConversionType::kNumberOrBoolean);
      case CompareOperationHint::kNumberOrOddball:
        return std::make_pair(NodeType::kNumberOrOddball,
                              TaggedToFloat64ConversionType::kNumberOrOddball);
      default:
        UNREACHABLE();
    }
  };
  FeedbackNexus nexus = FeedbackNexusForOperand(1);
  switch (nexus.GetCompareOperationFeedback()) {
    case CompareOperationHint::kNone:
      return EmitUnconditionalDeopt(
          DeoptimizeReason::kInsufficientTypeFeedbackForCompareOperation);
    case CompareOperationHint::kSignedSmall: {
      // TODO(victorgomes): Add a smart equality operator, that compares for
      // constants in different representations.
      ValueNode* left = GetInt32(LoadRegister(0));
      ValueNode* right = GetInt32(GetAccumulator());
      if (TryConstantFoldEqual(left, right)) return ReduceResult::Done();
      if (TryConstantFoldInt32(left, right)) return ReduceResult::Done();
      SortCommute(left, right);
      SetAccumulator(AddNewNode<Int32Compare>({left, right}, kOperation));
      return ReduceResult::Done();
    }
    case CompareOperationHint::kNumberOrOddball:
      // Equality and strict equality don't perform ToNumber conversions on
      // Oddballs.
      if ((kOperation == Operation::kEqual ||
           kOperation == Operation::kStrictEqual) &&
          MaybeOddballs()) {
        break;
      }
      [[fallthrough]];
    case CompareOperationHint::kNumberOrBoolean:
      if (kOperation == Operation::kStrictEqual && MaybeOddballs()) {
        break;
      }
      [[fallthrough]];
    case CompareOperationHint::kNumber: {
      ValueNode* left = LoadRegister(0);
      ValueNode* right = GetAccumulator();
      if (left->value_representation() == ValueRepresentation::kInt32 &&
          right->value_representation() == ValueRepresentation::kInt32) {
        if (TryConstantFoldEqual(left, right)) return ReduceResult::Done();
        if (TryConstantFoldInt32(left, right)) return ReduceResult::Done();
        SortCommute(left, right);
        SetAccumulator(AddNewNode<Int32Compare>({left, right}, kOperation));
        return ReduceResult::Done();
      }
      auto [allowed_input_type, conversion_type] =
          GetConversionType(nexus.GetCompareOperationFeedback());
      left = GetFloat64ForToNumber(left, allowed_input_type, conversion_type);
      right = GetFloat64ForToNumber(right, allowed_input_type, conversion_type);
      if (left->Is<Float64Constant>() && right->Is<Float64Constant>()) {
        double left_value = left->Cast<Float64Constant>()->value().get_scalar();
        double right_value =
            right->Cast<Float64Constant>()->value().get_scalar();
        SetAccumulator(GetBooleanConstant(
            OperationValue<kOperation>(left_value, right_value)));
        return ReduceResult::Done();
      }
      SortCommute(left, right);
      SetAccumulator(AddNewNode<Float64Compare>({left, right}, kOperation));
      return ReduceResult::Done();
    }
    case CompareOperationHint::kInternalizedString: {
      DCHECK(kOperation == Operation::kEqual ||
             kOperation == Operation::kStrictEqual);
      ValueNode *left, *right;
      if (IsRegisterEqualToAccumulator(0)) {
        left = right = GetInternalizedString(iterator_.GetRegisterOperand(0));
        SetAccumulator(GetRootConstant(RootIndex::kTrueValue));
        return ReduceResult::Done();
      }
      left = GetInternalizedString(iterator_.GetRegisterOperand(0));
      right =
          GetInternalizedString(interpreter::Register::virtual_accumulator());
      if (TryConstantFoldEqual(left, right)) return ReduceResult::Done();
      SetAccumulator(BuildTaggedEqual(left, right));
      return ReduceResult::Done();
    }
    case CompareOperationHint::kSymbol: {
      DCHECK(kOperation == Operation::kEqual ||
             kOperation == Operation::kStrictEqual);
      ValueNode* left = LoadRegister(0);
      ValueNode* right = GetAccumulator();
      RETURN_IF_ABORT(BuildCheckSymbol(left));
      RETURN_IF_ABORT(BuildCheckSymbol(right));
      if (TryConstantFoldEqual(left, right)) return ReduceResult::Done();
      SetAccumulator(BuildTaggedEqual(left, right));
      return ReduceResult::Done();
    }
    case CompareOperationHint::kString: {
      ValueNode* left = LoadRegister(0);
      ValueNode* right = GetAccumulator();
      RETURN_IF_ABORT(BuildCheckString(left));
      RETURN_IF_ABORT(BuildCheckString(right));
      ValueNode* result;
      if (TryConstantFoldEqual(left, right)) return ReduceResult::Done();
      ValueNode* tagged_left = GetTaggedValue(left);
      ValueNode* tagged_right = GetTaggedValue(right);
      switch (kOperation) {
        case Operation::kEqual:
        case Operation::kStrictEqual: {
          result = AddNewNode<StringEqual>({tagged_left, tagged_right},
                                           StringEqualInputs::kOnlyStrings);
          break;
        }
        case Operation::kLessThan:
          result = BuildCallBuiltin<Builtin::kStringLessThan>(
              {tagged_left, tagged_right});
          break;
        case Operation::kLessThanOrEqual:
          result = BuildCallBuiltin<Builtin::kStringLessThanOrEqual>(
              {tagged_left, tagged_right});
          break;
        case Operation::kGreaterThan:
          result = BuildCallBuiltin<Builtin::kStringGreaterThan>(
              {tagged_left, tagged_right});
          break;
        case Operation::kGreaterThanOrEqual:
          result = BuildCallBuiltin<Builtin::kStringGreaterThanOrEqual>(
              {tagged_left, tagged_right});
          break;
      }
      SetAccumulator(result);
      return ReduceResult::Done();
    }
    case CompareOperationHint::kStringOrOddball: {
      if (kOperation == Operation::kStrictEqual) {
        ValueNode* left = LoadRegister(0);
        ValueNode* right = GetAccumulator();
        RETURN_IF_ABORT(BuildCheckStringOrOddball(left));
        RETURN_IF_ABORT(BuildCheckStringOrOddball(right));
        if (TryConstantFoldEqual(left, right)) return ReduceResult::Done();
        // TODO(marja): If one of the sides is constant, we can generate better
        // code (e.g., don't need to check its type at run time).
        ValueNode* tagged_left = GetTaggedValue(left);
        ValueNode* tagged_right = GetTaggedValue(right);
        ValueNode* result = AddNewNode<StringEqual>(
            {tagged_left, tagged_right}, StringEqualInputs::kStringsOrOddballs);
        SetAccumulator(result);
        return ReduceResult::Done();
      }
      break;
    }
    case CompareOperationHint::kAny:
    case CompareOperationHint::kBigInt64:
    case CompareOperationHint::kBigInt:
      break;
    case CompareOperationHint::kReceiverOrNullOrUndefined: {
      if (kOperation == Operation::kEqual) {
        break;
      }
      DCHECK_EQ(kOperation, Operation::kStrictEqual);
      ValueNode* left = LoadRegister(0);
      ValueNode* right = GetAccumulator();
      RETURN_IF_ABORT(BuildCheckJSReceiverOrNullOrUndefined(left));
      RETURN_IF_ABORT(BuildCheckJSReceiverOrNullOrUndefined(right));
      SetAccumulator(BuildTaggedEqual(left, right));
      return ReduceResult::Done();
    }
    case CompareOperationHint::kReceiver: {
      DCHECK(kOperation == Operation::kEqual ||
             kOperation == Operation::kStrictEqual);
      ValueNode* left = LoadRegister(0);
      ValueNode* right = GetAccumulator();
      RETURN_IF_ABORT(BuildCheckJSReceiver(left));
      RETURN_IF_ABORT(BuildCheckJSReceiver(right));
      SetAccumulator(BuildTaggedEqual(left, right));
      return ReduceResult::Done();
    }
  }
  BuildGenericBinaryOperationNode<kOperation>();
  return ReduceResult::Done();
}
References BuildCheckJSReceiver(), BuildCheckJSReceiverOrNullOrUndefined(), BuildCheckString(), BuildCheckStringOrOddball(), BuildCheckSymbol(), BuildTaggedEqual(), v8::internal::maglev::NodeBase::Cast(), CheckType(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), FeedbackNexusForOperand(), GetAccumulator(), GetBooleanConstant(), v8::internal::FeedbackNexus::GetCompareOperationFeedback(), GetFloat64ForToNumber(), GetInt32(), GetInternalizedString(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), GetRootConstant(), GetTaggedValue(), v8::internal::maglev::NodeBase::Is(), IsRegisterEqualToAccumulator(), iterator_, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kEqual, v8::internal::maglev::kFloat64, v8::internal::kGreaterThan, v8::internal::maglev::kInt32, v8::internal::kInternalizedString, v8::internal::kLessThan, v8::internal::kNone, v8::internal::kNumber, v8::internal::maglev::kNumberOrBoolean, v8::internal::kNumberOrBoolean, v8::internal::maglev::kNumberOrOddball, v8::internal::kNumberOrOddball, v8::internal::maglev::kOnlyNumber, v8::internal::maglev::kOnlyStrings, v8::kOperation, v8::internal::kReceiver, v8::internal::kReceiverOrNullOrUndefined, v8::internal::kSignedSmall, v8::internal::kString, v8::internal::kStringOrOddball, v8::internal::maglev::kStringsOrOddballs, v8::internal::kSymbol, v8::internal::maglev::kUint32, LoadRegister(), v8::base::internal::result, RETURN_IF_ABORT, SetAccumulator(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, v8::internal::value, v8::internal::maglev::ValueNode::value_representation(), and v8::internal::interpreter::Register::virtual_accumulator().
VisitSingleBytecode()
void v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode () [inline], [private]
Definition at line 827 of file maglev-graph-builder.h.
                             {
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << std::setw(4) << iterator_.current_offset() << " : ";
      interpreter::BytecodeDecoder::Decode(std::cout,
                                           iterator_.current_address());
      std::cout << std::endl;
    }
    int offset = iterator_.current_offset();
    UpdateSourceAndBytecodePosition(offset);
    MergePointInterpreterFrameState* merge_state = merge_states_[offset];
    if (V8_UNLIKELY(merge_state != nullptr)) {
      bool preserve_known_node_aspects = in_optimistic_peeling_iteration() &&
                                         loop_headers_to_peel_.Contains(offset);
      if (merge_state->is_resumable_loop()) {
        current_for_in_state.enum_cache_indices = nullptr;
      }
      if (current_block_ != nullptr) {
        DCHECK(!preserve_known_node_aspects);
        // TODO(leszeks): Re-evaluate this DCHECK, we might hit it if the only
        // bytecodes in this basic block were only register juggling.
        // DCHECK(!node_buffer().empty());
        BasicBlock* predecessor;
        if (merge_state->is_loop() && !merge_state->is_resumable_loop() &&
            need_checkpointed_loop_entry()) {
          predecessor =
              FinishBlock<CheckpointedJump>({}, &jump_targets_[offset]);
        } else {
          predecessor = FinishBlock<Jump>({}, &jump_targets_[offset]);
        }
        merge_state->Merge(this, *compilation_unit_, current_interpreter_frame_,
                           predecessor);
      }
      if (v8_flags.trace_maglev_graph_building) {
        auto detail = merge_state->is_exception_handler() ? "exception handler"
                      : merge_state->is_loop() ? "loop header"
                                                          : "merge";
        std::cout << "== New block (" << detail << " @" << merge_state
                  << ") at "
                  << compilation_unit()->shared_function_info().object()
                  << "==" << std::endl;
        PrintVirtualObjects();
      }
      if (V8_UNLIKELY(merge_state->is_exception_handler())) {
        CHECK_EQ(predecessor_count(offset), 0);
        // If we have no reference to this block, then the exception handler is
        // dead.
        if (!jump_targets_[offset].has_ref() ||
            !merge_state->exception_handler_was_used()) {
          MarkBytecodeDead();
          return;
        }
        ProcessMergePointAtExceptionHandlerStart(offset);
      } else if (merge_state->is_unmerged_unreachable_loop()) {
        // We encountered a loop header that is only reachable by the JumpLoop
        // back-edge, but the bytecode_analysis didn't notice upfront. This can
        // e.g. be a loop that is entered on a dead fall-through.
        static_assert(kLoopsMustBeEnteredThroughHeader);
        MarkBytecodeDead();
        return;
      } else {
        ProcessMergePoint(offset, preserve_known_node_aspects);
      }
      if (is_loop_effect_tracking_enabled() && merge_state->is_loop()) {
        BeginLoopEffects(offset);
      }
      // We pass nullptr for the `predecessor` argument of StartNewBlock because
      // this block is guaranteed to have a merge_state_, and hence to not have
      // a `predecessor_` field.
      StartNewBlock(offset, /*predecessor*/ nullptr);
    } else if (V8_UNLIKELY(current_block_ == nullptr)) {
      // If we don't have a current block, the bytecode must be dead (because of
      // some earlier deopt). Mark this bytecode dead too and return.
      // TODO(leszeks): Merge these two conditions by marking dead states with
      // a sentinel value.
      if (predecessor_count(offset) == 1) {
        CHECK_NULL(merge_state);
        CHECK(bytecode_analysis().IsLoopHeader(offset));
      } else {
        CHECK_EQ(predecessor_count(offset), 0);
      }
      MarkBytecodeDead();
      return;
    }
    // Handle exceptions if we have a table.
    if (bytecode().handler_table_size() > 0) {
      // Pop all entries where offset >= end.
      while (IsInsideTryBlock()) {
        HandlerTableEntry& entry = catch_block_stack_.top();
        if (offset < entry.end) break;
        catch_block_stack_.pop();
      }
      // Push new entries from interpreter handler table where offset >= start
      // && offset < end.
      HandlerTable table(*bytecode().object());
      while (next_handler_table_index_ < table.NumberOfRangeEntries()) {
        int start = table.GetRangeStart(next_handler_table_index_);
        if (offset < start) break;
        int end = table.GetRangeEnd(next_handler_table_index_);
        if (offset >= end) {
          next_handler_table_index_++;
          continue;
        }
        int handler = table.GetRangeHandler(next_handler_table_index_);
        catch_block_stack_.push({end, handler});
        DCHECK_NOT_NULL(merge_states_[handler]);
        next_handler_table_index_++;
      }
    }
    DCHECK_NOT_NULL(current_block_);
#ifdef DEBUG
    // Clear new nodes for the next VisitFoo
    new_nodes_.clear();
#endif
    if (iterator_.current_bytecode() == interpreter::Bytecode::kJumpLoop &&
        iterator_.GetJumpTargetOffset() < entrypoint_) {
      static_assert(kLoopsMustBeEnteredThroughHeader);
      CHECK(EmitUnconditionalDeopt(DeoptimizeReason::kOSREarlyExit)
                .IsDoneWithAbort());
      MarkBytecodeDead();
      return;
    }
    switch (iterator_.current_bytecode()) {
#define BYTECODE_CASE(name, ...) \
  case interpreter::Bytecode::k##name: { \
    if (Visit##name().IsDoneWithAbort()) { \
      MarkBytecodeDead(); \
    } \
    break; \
  }
      BYTECODE_LIST(BYTECODE_CASE, BYTECODE_CASE)
#undef BYTECODE_CASE
    }
  }
References BeginLoopEffects(), bytecode(), bytecode_analysis(), BYTECODE_CASE, BYTECODE_LIST, catch_block_stack_, CHECK, CHECK_EQ, CHECK_NULL, compilation_unit(), compilation_unit_, v8::internal::BitVector::Contains(), v8::internal::interpreter::BytecodeArrayIterator::current_address(), current_block_, v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), current_for_in_state, current_interpreter_frame_, v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::interpreter::BytecodeDecoder::Decode(), EmitUnconditionalDeopt(), v8::internal::compiler::end(), v8::internal::maglev::MaglevGraphBuilder::HandlerTableEntry::end, entrypoint_, v8::internal::maglev::MaglevGraphBuilder::ForInState::enum_cache_indices, v8::internal::maglev::MergePointInterpreterFrameState::exception_handler_was_used(), v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset(), v8::internal::HandlerTable::GetRangeEnd(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::HandlerTable::GetRangeStart(), in_optimistic_peeling_iteration(), v8::internal::maglev::MergePointInterpreterFrameState::is_exception_handler(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop(), is_loop_effect_tracking_enabled(), v8::internal::maglev::MergePointInterpreterFrameState::is_resumable_loop(), v8::internal::maglev::MergePointInterpreterFrameState::is_unmerged_unreachable_loop(), IsInsideTryBlock(), iterator_, jump_targets_, kLoopsMustBeEnteredThroughHeader, loop_headers_to_peel_, MarkBytecodeDead(), v8::internal::maglev::MergePointInterpreterFrameState::Merge(), merge_states_, need_checkpointed_loop_entry(), next_handler_table_index_, v8::internal::HandlerTable::NumberOfRangeEntries(), v8::internal::compiler::SharedFunctionInfoRef::object(), predecessor_count(), PrintVirtualObjects(), ProcessMergePoint(), ProcessMergePointAtExceptionHandlerStart(), v8::internal::maglev::MaglevCompilationUnit::shared_function_info(), StartNewBlock(), UpdateSourceAndBytecodePosition(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by BuildBody().
VisitUnaryOperation()
template<Operation kOperation>
ReduceResult v8::internal::maglev::MaglevGraphBuilder::VisitUnaryOperation [private]
Definition at line 2662 of file maglev-graph-builder.cc.
                                                     {
  FeedbackNexus nexus = FeedbackNexusForOperand(0);
  BinaryOperationHint feedback_hint = nexus.GetBinaryOperationFeedback();
  switch (feedback_hint) {
    case BinaryOperationHint::kNone:
      return EmitUnconditionalDeopt(
          DeoptimizeReason::kInsufficientTypeFeedbackForBinaryOperation);
    case BinaryOperationHint::kSignedSmall:
    case BinaryOperationHint::kSignedSmallInputs:
    case BinaryOperationHint::kAdditiveSafeInteger:
    case BinaryOperationHint::kNumber:
    case BinaryOperationHint::kNumberOrOddball: {
      auto [allowed_input_type, conversion_type] =
          BinopHintToNodeTypeAndConversionType(feedback_hint);
      if constexpr (BinaryOperationIsBitwiseInt32<kOperation>()) {
        static_assert(kOperation == Operation::kBitwiseNot);
        return BuildTruncatingInt32BitwiseNotForToNumber(allowed_input_type,
                                                         conversion_type);
      } else if (feedback_hint == BinaryOperationHint::kSignedSmall) {
        return BuildInt32UnaryOperationNode<kOperation>();
      }
      return BuildFloat64UnaryOperationNodeForToNumber<kOperation>(
          allowed_input_type, conversion_type);
      break;
    }
    case BinaryOperationHint::kString:
    case BinaryOperationHint::kStringOrStringWrapper:
    case BinaryOperationHint::kBigInt:
    case BinaryOperationHint::kBigInt64:
    case BinaryOperationHint::kAny:
      // Fallback to generic node.
      break;
  }
  BuildGenericUnaryOperationNode<kOperation>();
  return ReduceResult::Done();
}
References v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::BinopHintToNodeTypeAndConversionType(), BuildTruncatingInt32BitwiseNotForToNumber(), v8::internal::maglev::ReduceResult::Done(), EmitUnconditionalDeopt(), FeedbackNexusForOperand(), v8::internal::FeedbackNexus::GetBinaryOperationFeedback(), v8::internal::kAdditiveSafeInteger, v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrOddball, v8::kOperation, v8::internal::kSignedSmall, v8::internal::kSignedSmallInputs, v8::internal::kString, and v8::internal::kStringOrStringWrapper.
zone()
Zone* v8::internal::maglev::MaglevGraphBuilder::zone () const [inline]
Definition at line 357 of file maglev-graph-builder.h.
{ return compilation_unit_->zone(); }
References compilation_unit_, and v8::internal::maglev::MaglevCompilationUnit::zone().
Referenced by AddInlinedArgumentsToDeoptFrame(), AddNewNode(), AddNewNodeOrGetEquivalent(), AttachDeoptCheckpoint(), AttachEagerDeoptInfo(), AttachLazyDeoptInfo(), Build(), BuildCheckMaps(), BuildCompareMaps(), BuildInitializeStore(), CreateEdgeSplitBlock(), CreateNewConstantNode(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromHoleyFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromIntPtrToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromUint32ToTagged(), GetDeoptFrameForEagerCall(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), GetLatestCheckpointedFrame(), v8::internal::maglev::MergePointInterpreterFrameState::InitializeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::Merge(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergeThrow(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjects(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), ProcessMergePoint(), StartPrologue(), TryBuildNamedAccess(), and v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop().
Member Data Documentation
allow_loop_peeling_
bool v8::internal::maglev::MaglevGraphBuilder::allow_loop_peeling_ [private]
Definition at line 3224 of file maglev-graph-builder.h.
any_peeled_loop_
bool v8::internal::maglev::MaglevGraphBuilder::any_peeled_loop_ = false [private]
Definition at line 3223 of file maglev-graph-builder.h.
broker_
compiler::JSHeapBroker* v8::internal::maglev::MaglevGraphBuilder::broker_ = compilation_unit_->broker() [private]
Definition at line 3173 of file maglev-graph-builder.h.
Referenced by broker(), and TryReduceCompareEqualAgainstConstant().
bytecode_analysis_
compiler::BytecodeAnalysis v8::internal::maglev::MaglevGraphBuilder::bytecode_analysis_ [private]
Definition at line 3176 of file maglev-graph-builder.h.
caller_details_
MaglevCallerDetails* v8::internal::maglev::MaglevGraphBuilder::caller_details_ [private]
Definition at line 3170 of file maglev-graph-builder.h.
Referenced by BuildBody(), caller_details(), GetCallerDeoptFrame(), GetCurrentTryCatchBlock(), GetInlinedArgument(), GetTryCatchBlockForNonEagerInlining(), is_eager_inline(), and is_inline().
catch_block_stack_
ZoneStack<HandlerTableEntry> v8::internal::maglev::MaglevGraphBuilder::catch_block_stack_ [private]
Definition at line 3302 of file maglev-graph-builder.h.
Referenced by GetCatchBlockFrameState(), GetCurrentTryCatchBlock(), IsInsideTryBlock(), and VisitSingleBytecode().
compilation_unit_
MaglevCompilationUnit* const v8::internal::maglev::MaglevGraphBuilder::compilation_unit_ [private]
Definition at line 3169 of file maglev-graph-builder.h.
Referenced by AddInitializedNodeToGraph(), AttachExceptionHandlerInfo(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::BeginLoop(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::Bind(), Build(), BuildLoadContextSlot(), BuildMergeStates(), BuildRegisterFrameInitialization(), compilation_unit(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::EndLoop(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), GetLatestCheckpointedFrame(), inlining_depth(), KillPeeledLoopTargets(), MaglevGraphBuilder(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::MergeIntoLabel(), ProcessMergePoint(), ProcessMergePointAtExceptionHandlerStart(), v8::internal::maglev::MaglevGraphBuilder::MaglevSubGraphBuilder::ReducePredecessorCount(), TrySpecializeLoadContextSlotToFunctionContext(), VisitSingleBytecode(), and zone().
current_allocation_block_
AllocationBlock* v8::internal::maglev::MaglevGraphBuilder::current_allocation_block_ = nullptr [private]
Definition at line 3271 of file maglev-graph-builder.h.
Referenced by CanElideWriteBarrier(), ProcessMergePointAtExceptionHandlerStart(), and ProcessMergePointPredecessors().
current_block_
BasicBlock* v8::internal::maglev::MaglevGraphBuilder::current_block_ = nullptr [private]
Definition at line 3256 of file maglev-graph-builder.h.
Referenced by AddInitializedNodeToGraph(), AttachExceptionHandlerInfo(), CreateEdgeSplitBlock(), EmitUnconditionalDeopt(), MarkBytecodeDead(), set_current_block(), StartPrologue(), and VisitSingleBytecode().
current_deopt_scope_
DeoptFrameScope* v8::internal::maglev::MaglevGraphBuilder::current_deopt_scope_ = nullptr [private]
Definition at line 3295 of file maglev-graph-builder.h.
Referenced by current_deopt_scope(), GetDeoptFrameForEagerCall(), GetDeoptFrameForLazyDeopt(), GetDeoptFrameForLazyDeoptHelper(), and GetLatestCheckpointedFrame().
current_for_in_state
ForInState v8::internal::maglev::MaglevGraphBuilder::current_for_in_state = ForInState() [private]
Definition at line 3269 of file maglev-graph-builder.h.
Referenced by VisitSingleBytecode().
current_interpreter_frame_
InterpreterFrameState v8::internal::maglev::MaglevGraphBuilder::current_interpreter_frame_ [private]
Definition at line 3276 of file maglev-graph-builder.h.
Referenced by AttachExceptionHandlerInfo(), BuildLoadContextSlot(), BuildMergeStates(), BuildRegisterFrameInitialization(), BuildTruncatingInt32BinaryOperationNodeForToNumber(), BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), BuildTruncatingInt32BitwiseNotForToNumber(), CanTrackObjectChanges(), current_interpreter_frame(), GetArgument(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), GetInternalizedString(), GetLatestCheckpointedFrame(), GetModifiableObjectFromAllocation(), GetObjectFromAllocation(), InitializeRegister(), PrintVirtualObjects(), ProcessMergePoint(), ProcessMergePointAtExceptionHandlerStart(), SetArgument(), TryBuildPropertyStore(), and VisitSingleBytecode().
current_source_position_
SourcePosition v8::internal::maglev::MaglevGraphBuilder::current_source_position_ [private]
Definition at line 3259 of file maglev-graph-builder.h.
Referenced by AddInitializedNodeToGraph(), Build(), BuildBody(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), GetLatestCheckpointedFrame(), ProcessMergePointAtExceptionHandlerStart(), and UpdateSourceAndBytecodePosition().
current_speculation_feedback_
compiler::FeedbackSource v8::internal::maglev::MaglevGraphBuilder::current_speculation_feedback_ [private]
Definition at line 3277 of file maglev-graph-builder.h.
Referenced by AttachEagerDeoptInfo(), AttachLazyDeoptInfo(), and v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::SaveCallSpeculationScope().
current_speculation_mode_
SpeculationMode v8::internal::maglev::MaglevGraphBuilder::current_speculation_mode_ [private]
Initial value:
=
      SpeculationMode::kDisallowSpeculation
Definition at line 3278 of file maglev-graph-builder.h.
decremented_predecessor_offsets_
ZoneVector<int> v8::internal::maglev::MaglevGraphBuilder::decremented_predecessor_offsets_ [private]
Definition at line 3250 of file maglev-graph-builder.h.
entry_stack_check_frame_
std::optional<InterpretedDeoptFrame> v8::internal::maglev::MaglevGraphBuilder::entry_stack_check_frame_ [private]
Definition at line 3257 of file maglev-graph-builder.h.
Referenced by GetDeoptFrameForEntryStackCheck().
entrypoint_
int v8::internal::maglev::MaglevGraphBuilder::entrypoint_ [private]
Definition at line 3286 of file maglev-graph-builder.h.
Referenced by BuildBody(), BuildMergeStates(), EndPrologue(), GetDeoptFrameForEntryStackCheck(), MaglevGraphBuilder(), and VisitSingleBytecode().
graph_
Graph* const v8::internal::maglev::MaglevGraphBuilder::graph_ [private]
Definition at line 3175 of file maglev-graph-builder.h.
Referenced by BuildMergeStates(), BuildRegisterFrameInitialization(), CanTrackObjectChanges(), EndPrologue(), GetDeoptFrameForEntryStackCheck(), graph(), graph_labeller(), has_graph_labeller(), MaglevGraphBuilder(), NewObjectId(), node_buffer(), and ShouldEmitOsrInterruptBudgetChecks().
in_prologue_
bool v8::internal::maglev::MaglevGraphBuilder::in_prologue_ = true [private]
Definition at line 3255 of file maglev-graph-builder.h.
Referenced by Build(), and GetLatestCheckpointedFrame().
inlined_new_target_
ValueNode* v8::internal::maglev::MaglevGraphBuilder::inlined_new_target_ = nullptr [private]
Definition at line 3281 of file maglev-graph-builder.h.
inlining_id_
int v8::internal::maglev::MaglevGraphBuilder::inlining_id_ = SourcePosition::kNotInlined [private]
Definition at line 3292 of file maglev-graph-builder.h.
Referenced by Build(), BuildBody(), and UpdateSourceAndBytecodePosition().
is_turbolev_
bool v8::internal::maglev::MaglevGraphBuilder::is_turbolev_ = false [private]
Definition at line 3283 of file maglev-graph-builder.h.
Referenced by is_turbolev().
iterator_
interpreter::BytecodeArrayIterator v8::internal::maglev::MaglevGraphBuilder::iterator_ [private]
Definition at line 3177 of file maglev-graph-builder.h.
Referenced by AddInitializedNodeToGraph(), AddInlinedArgumentsToDeoptFrame(), BuildBody(), BuildFloat64BinarySmiOperationNodeForToNumber(), BuildGenericBinarySmiOperationNode(), BuildInt32BinarySmiOperationNode(), BuildTruncatingInt32BinaryOperationNodeForToNumber(), BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), GetDeoptFrameForEagerCall(), GetDeoptFrameForEntryStackCheck(), GetDeoptFrameForLazyDeoptHelper(), GetLatestCheckpointedFrame(), GetResultLocationAndSize(), KillPeeledLoopTargets(), MaglevGraphBuilder(), MarkBytecodeDead(), VisitCompareOperation(), and VisitSingleBytecode().
jump_targets_
BasicBlockRef* v8::internal::maglev::MaglevGraphBuilder::jump_targets_ [private]
Definition at line 3273 of file maglev-graph-builder.h.
Referenced by EndPrologue(), GetCurrentTryCatchBlock(), MaglevGraphBuilder(), ProcessMergePoint(), and VisitSingleBytecode().
kLoopsMustBeEnteredThroughHeader
constexpr bool v8::internal::maglev::MaglevGraphBuilder::kLoopsMustBeEnteredThroughHeader = true [static], [constexpr], [private]
Definition at line 523 of file maglev-graph-builder.h.
Referenced by VisitSingleBytecode().
latest_checkpointed_frame_
std::optional<DeoptFrame> v8::internal::maglev::MaglevGraphBuilder::latest_checkpointed_frame_ [private]
Definition at line 3258 of file maglev-graph-builder.h.
Referenced by GetLatestCheckpointedFrame().
lazy_deopt_result_location_scope_
LazyDeoptResultLocationScope* v8::internal::maglev::MaglevGraphBuilder::lazy_deopt_result_location_scope_ = nullptr [private]
Definition at line 3296 of file maglev-graph-builder.h.
Referenced by AttachLazyDeoptInfo(), and v8::internal::maglev::MaglevGraphBuilder::LazyDeoptResultLocationScope::LazyDeoptResultLocationScope().
local_isolate_
LocalIsolate* const v8::internal::maglev::MaglevGraphBuilder::local_isolate_ [private]
Definition at line 3168 of file maglev-graph-builder.h.
Referenced by BuildBody(), GetTruncatedInt32ForToNumber(), local_isolate(), and TryGetFloat64Constant().
loop_effects_
LoopEffects* v8::internal::maglev::MaglevGraphBuilder::loop_effects_ = nullptr [private]
Definition at line 3243 of file maglev-graph-builder.h.
Referenced by CanTrackObjectChanges(), MaglevGraphBuilder(), and StoreAndCacheContextSlot().
loop_effects_stack_
ZoneDeque<LoopEffects*> v8::internal::maglev::MaglevGraphBuilder::loop_effects_stack_ [private]
Definition at line 3244 of file maglev-graph-builder.h.
Referenced by BuildBody(), and MaglevGraphBuilder().
loop_headers_to_peel_
BitVector v8::internal::maglev::MaglevGraphBuilder::loop_headers_to_peel_ [private]
Definition at line 3252 of file maglev-graph-builder.h.
Referenced by BuildBody(), BuildMergeStates(), and VisitSingleBytecode().
merge_states_
MergePointInterpreterFrameState** v8::internal::maglev::MaglevGraphBuilder::merge_states_ [private]
Definition at line 3274 of file maglev-graph-builder.h.
Referenced by BuildMergeStates(), GetCatchBlockFrameState(), GetCurrentTryCatchBlock(), IsOffsetAMergePoint(), KillPeeledLoopTargets(), MaglevGraphBuilder(), ProcessMergePoint(), ProcessMergePointAtExceptionHandlerStart(), and VisitSingleBytecode().
next_handler_table_index_
int v8::internal::maglev::MaglevGraphBuilder::next_handler_table_index_ = 0 [private]
Definition at line 3293 of file maglev-graph-builder.h.
Referenced by VisitSingleBytecode().
peeled_iteration_count_
int v8::internal::maglev::MaglevGraphBuilder::peeled_iteration_count_ = 0 [private]
Definition at line 3222 of file maglev-graph-builder.h.
predecessor_count_
uint32_t* v8::internal::maglev::MaglevGraphBuilder::predecessor_count_ [private]
Definition at line 3220 of file maglev-graph-builder.h.
source_position_iterator_
SourcePositionTableIterator v8::internal::maglev::MaglevGraphBuilder::source_position_iterator_ [private]
Definition at line 3178 of file maglev-graph-builder.h.
Referenced by BuildBody(), and UpdateSourceAndBytecodePosition().
unobserved_context_slot_stores_
ZoneUnorderedMap<KnownNodeAspects::LoadedContextSlotsKey, Node*> v8::internal::maglev::MaglevGraphBuilder::unobserved_context_slot_stores_ [private]
Definition at line 3381 of file maglev-graph-builder.h.
Referenced by MaglevGraphBuilder(), and StoreAndCacheContextSlot().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.h
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc