v8::internal::WasmGlobalObject Class Reference
#include <wasm-objects.h>
Public Member Functions
int type_size () const
int32_t GetI32 ()
int64_t GetI64 ()
float GetF32 ()
double GetF64 ()
uint8_t * GetS128RawBytes ()
DirectHandle< Object > GetRef ()
void SetI32 (int32_t value)
void SetI64 (int64_t value)
void SetF32 (float value)
void SetF64 (double value)
void SetRef (DirectHandle< Object > value)
Static Public Member Functions
static V8_EXPORT_PRIVATE MaybeDirectHandle< WasmGlobalObject > New (Isolate *isolate, DirectHandle< WasmTrustedInstanceData > instance_object, MaybeDirectHandle< JSArrayBuffer > maybe_untagged_buffer, MaybeDirectHandle< FixedArray > maybe_tagged_buffer, wasm::ValueType type, int32_t offset, bool is_mutable)
Private Member Functions
Address address () const
Detailed Description
Definition at line 433 of file wasm-objects.h.
Member Function Documentation
address()
Address v8::internal::WasmGlobalObject::address () const [inline], [private]
Definition at line 134 of file wasm-objects-inl.h.
                                        {
  DCHECK(!type().is_reference());
  DCHECK_LE(offset() + type_size(), untagged_buffer()->byte_length());
  return reinterpret_cast<Address>(untagged_buffer()->backing_store()) +
         offset();
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::wasm::is_reference(), v8::internal::tracing::type, and type_size().
Referenced by GetF32(), GetF64(), GetI32(), GetI64(), GetS128RawBytes(), SetF32(), SetF64(), SetI32(), and SetI64().
GetF32()
float v8::internal::WasmGlobalObject::GetF32 () [inline]
Definition at line 149 of file wasm-objects-inl.h.
                               {
  return base::ReadUnalignedValue<float>(address());
}
References address().
GetF64()
double v8::internal::WasmGlobalObject::GetF64 () [inline]
Definition at line 153 of file wasm-objects-inl.h.
                                {
  return base::ReadUnalignedValue<double>(address());
}
References address().
GetI32()
int32_t v8::internal::WasmGlobalObject::GetI32 () [inline]
Definition at line 141 of file wasm-objects-inl.h.
                                 {
  return base::ReadUnalignedValue<int32_t>(address());
}
References address().
GetI64()
int64_t v8::internal::WasmGlobalObject::GetI64 () [inline]
Definition at line 145 of file wasm-objects-inl.h.
                                 {
  return base::ReadUnalignedValue<int64_t>(address());
}
References address().
GetRef()
DirectHandle< Object > v8::internal::WasmGlobalObject::GetRef () [inline]
Definition at line 161 of file wasm-objects-inl.h.
                                              {
  // We use this getter for externref, funcref, and stringref.
  DCHECK(type().is_reference());
  return direct_handle(tagged_buffer()->get(offset()), Isolate::Current());
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::wasm::is_reference(), v8::internal::tagged_buffer, and v8::internal::tracing::type.
GetS128RawBytes()
uint8_t * v8::internal::WasmGlobalObject::GetS128RawBytes () [inline]
Definition at line 157 of file wasm-objects-inl.h.
                                           {
  return reinterpret_cast<uint8_t*>(address());
}
References address().
New()
MaybeDirectHandle< WasmGlobalObject > v8::internal::WasmGlobalObject::New (Isolate * isolate, DirectHandle< WasmTrustedInstanceData > instance_object, MaybeDirectHandle< JSArrayBuffer > maybe_untagged_buffer, MaybeDirectHandle< FixedArray > maybe_tagged_buffer, wasm::ValueType type, int32_t offset, bool is_mutable) [static]
Definition at line 1429 of file wasm-objects.cc.
                                     {
  DirectHandle<JSFunction> global_ctor(
      isolate->native_context()->wasm_global_constructor(), isolate);
  auto global_obj =
      Cast<WasmGlobalObject>(isolate->factory()->NewJSObject(global_ctor));
  {
    // Disallow GC until all fields have acceptable types.
    DisallowGarbageCollection no_gc;
    if (!trusted_data.is_null()) {
      global_obj->set_trusted_data(*trusted_data);
    } else {
      global_obj->clear_trusted_data();
    }
    global_obj->set_type(type);
    global_obj->set_offset(offset);
    global_obj->set_is_mutable(is_mutable);
  }
  if (type.is_reference()) {
    DCHECK(maybe_untagged_buffer.is_null());
    DirectHandle<FixedArray> tagged_buffer;
    if (!maybe_tagged_buffer.ToHandle(&tagged_buffer)) {
      // If no buffer was provided, create one.
      tagged_buffer =
          isolate->factory()->NewFixedArray(1, AllocationType::kOld);
      CHECK_EQ(offset, 0);
    }
    global_obj->set_tagged_buffer(*tagged_buffer);
  } else {
    DCHECK(maybe_tagged_buffer.is_null());
    uint32_t type_size = type.value_kind_size();
    DirectHandle<JSArrayBuffer> untagged_buffer;
    if (!maybe_untagged_buffer.ToHandle(&untagged_buffer)) {
      MaybeDirectHandle<JSArrayBuffer> result =
          isolate->factory()->NewJSArrayBufferAndBackingStore(
              offset + type_size, InitializedFlag::kZeroInitialized);
      if (!result.ToHandle(&untagged_buffer)) {
        isolate->Throw(*isolate->factory()->NewRangeError(
            MessageTemplate::kOutOfMemory,
            isolate->factory()->NewStringFromAsciiChecked(
                "WebAssembly.Global")));
        return {};
      }
    }
    // Check that the offset is in bounds.
    CHECK_LE(offset + type_size, untagged_buffer->GetByteLength());
    global_obj->set_untagged_buffer(*untagged_buffer);
  }
  return global_obj;
}
References CHECK_EQ, CHECK_LE, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::DirectHandle< T >::is_null(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::kOld, v8::internal::kZeroInitialized, v8::internal::Isolate::native_context(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::tagged_buffer, v8::internal::Isolate::Throw(), v8::internal::MaybeDirectHandle< T >::ToHandle(), v8::internal::tracing::type, and type_size().
Referenced by v8::internal::wasm::InstanceBuilder::ProcessExports(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl().
SetF32()
void v8::internal::WasmGlobalObject::SetF32 (float value) [inline]
Definition at line 175 of file wasm-objects-inl.h.
                                         {
  base::WriteUnalignedValue(address(), value);
}
References address(), v8::internal::value, and v8::base::WriteUnalignedValue().
SetF64()
void v8::internal::WasmGlobalObject::SetF64 (double value) [inline]
Definition at line 179 of file wasm-objects-inl.h.
                                          {
  base::WriteUnalignedValue(address(), value);
}
References address(), v8::internal::value, and v8::base::WriteUnalignedValue().
SetI32()
void v8::internal::WasmGlobalObject::SetI32 (int32_t value) [inline]
Definition at line 167 of file wasm-objects-inl.h.
                                           {
  base::WriteUnalignedValue(address(), value);
}
References address(), v8::internal::value, and v8::base::WriteUnalignedValue().
SetI64()
void v8::internal::WasmGlobalObject::SetI64 (int64_t value) [inline]
Definition at line 171 of file wasm-objects-inl.h.
                                           {
  base::WriteUnalignedValue(address(), value);
}
References address(), v8::internal::value, and v8::base::WriteUnalignedValue().
SetRef()
void v8::internal::WasmGlobalObject::SetRef (DirectHandle< Object > value) [inline]
Definition at line 183 of file wasm-objects-inl.h.
                                                        {
  DCHECK(type().is_object_reference());
  tagged_buffer()->set(offset(), *value);
}
References v8::internal::DCHECK(), v8::internal::wasm::is_object_reference(), v8::internal::tagged_buffer, v8::internal::tracing::type, and v8::internal::value.
type_size()
int v8::internal::WasmGlobalObject::type_size () const [inline]
Definition at line 132 of file wasm-objects-inl.h.
{ return type().value_kind_size(); }
References v8::internal::tracing::type.
Referenced by address(), and New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc