v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor Class Reference
Public Member Functions
ParameterProcessor (LiftoffCompiler *compiler, uint32_t num_params)
void Process ()
Private Member Functions
bool NextParam ()
void NextLocation ()
LiftoffRegister CurrentRegister ()
void MaybeCollectRegister ()
LiftoffRegister LoadToReg (LiftoffRegList pinned)
Private Attributes
LiftoffCompiler * compiler_
const uint32_t num_params_
uint32_t param_idx_ {0}
uint32_t input_idx_ {kFirstInputIdx}
ValueKind kind_
bool needs_gp_pair_
ValueKind reg_kind_
RegClass rc_
LinkageLocation location_ {LinkageLocation::ForAnyRegister()}
LiftoffRegList param_regs_
Static Private Attributes
static constexpr uint32_t kFirstInputIdx = 2
Detailed Description
Definition at line 766 of file liftoff-compiler.cc.
Constructor & Destructor Documentation
ParameterProcessor()
v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::ParameterProcessor (LiftoffCompiler * compiler, uint32_t num_params) [inline]
Definition at line 768 of file liftoff-compiler.cc.
        : compiler_(compiler), num_params_(num_params) {}
Member Function Documentation
CurrentRegister()
LiftoffRegister v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::CurrentRegister () [inline], [private]
Definition at line 827 of file liftoff-compiler.cc.
                                      {
      DCHECK(!location_.IsAnyRegister());
      return LiftoffRegister::from_external_code(rc_, reg_kind_,
                                                 location_.AsRegister());
    }
References v8::internal::DCHECK(), and v8::internal::wasm::LiftoffRegister::from_external_code().
LoadToReg()
LiftoffRegister v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::LoadToReg (LiftoffRegList pinned) [inline], [private]
Definition at line 839 of file liftoff-compiler.cc.
                                                     {
      if (location_.IsRegister()) {
        LiftoffRegister reg = CurrentRegister();
        DCHECK(compiler_->asm_.cache_state()->is_free(reg));
        // Unpin the register, to avoid depending on the set of allocatable
        // registers being larger than the set of parameter registers.
        param_regs_.clear(reg);
        return reg;
      }
      DCHECK(location_.IsCallerFrameSlot());
      LiftoffRegister reg = compiler_->asm_.GetUnusedRegister(rc_, pinned);
      compiler_->asm_.LoadCallerFrameSlot(reg, -location_.AsCallerFrameSlot(),
                                          reg_kind_);
      return reg;
    }
References v8::internal::DCHECK().
MaybeCollectRegister()
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::MaybeCollectRegister () [inline], [private]
Definition at line 833 of file liftoff-compiler.cc.
                                {
      if (!location_.IsRegister()) return;
      DCHECK(!param_regs_.has(CurrentRegister()));
      param_regs_.set(CurrentRegister());
    }
References v8::internal::DCHECK().
NextLocation()
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::NextLocation () [inline], [private]
Definition at line 823 of file liftoff-compiler.cc.
                        {
      location_ = compiler_->descriptor_->GetInputLocation(input_idx_++);
    }
NextParam()
bool v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::NextParam () [inline], [private]
Definition at line 810 of file liftoff-compiler.cc.
                     {
      if (param_idx_ >= num_params_) {
        DCHECK_EQ(input_idx_, compiler_->descriptor_->InputCount());
        return false;
      }
      kind_ = compiler_->asm_.local_kind(param_idx_++);
      needs_gp_pair_ = needs_gp_reg_pair(kind_);
      reg_kind_ = needs_gp_pair_ ? kI32 : kind_;
      rc_ = reg_class_for(reg_kind_);
      NextLocation();
      return true;
    }
References DCHECK_EQ, v8::internal::kI32, v8::internal::wasm::needs_gp_reg_pair(), and v8::internal::wasm::reg_class_for().
Process()
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::Process () [inline]
Definition at line 771 of file liftoff-compiler.cc.
                   {
      // First pass: collect parameter registers.
      while (NextParam()) {
        MaybeCollectRegister();
        if (needs_gp_pair_) {
          NextLocation();
          MaybeCollectRegister();
        }
      }
      // Second pass: allocate parameters.
      param_idx_ = 0;
      input_idx_ = kFirstInputIdx;
      while (NextParam()) {
        LiftoffRegister reg = LoadToReg(param_regs_);
        // The sandbox's function signature checks don't care to distinguish
        // i32 and i64 primitives. That's usually fine, but in a few cases
        // i32 parameters with non-zero upper halves can violate security-
        // relevant invariants, so we explicitly clear them here.
        // 'clear_i32_upper_half' is empty on LoongArch64, MIPS64 and riscv64,
        // because they will explicitly zero-extend their lower halves before
        // using them for memory accesses anyway.
        // In addition, the generic js-to-wasm wrapper does a sign-extension
        // of i32 parameters, so clearing the upper half is required for
        // correctness in this case.
#if V8_TARGET_ARCH_64_BIT
        if (kind_ == kI32 && location_.IsRegister()) {
          compiler_->asm_.clear_i32_upper_half(reg.gp());
        }
#endif
        if (needs_gp_pair_) {
          NextLocation();
          LiftoffRegister reg2 = LoadToReg(param_regs_ | LiftoffRegList{reg});
          reg = LiftoffRegister::ForPair(reg.gp(), reg2.gp());
        }
        compiler_->asm_.PushRegister(kind_, reg);
      }
    }
References v8::internal::wasm::LiftoffRegister::ForPair(), v8::internal::wasm::LiftoffRegister::gp(), and v8::internal::kI32.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody().
Member Data Documentation
compiler_
LiftoffCompiler* v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::compiler_ [private]
Definition at line 858 of file liftoff-compiler.cc.
input_idx_
uint32_t v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::input_idx_ {kFirstInputIdx} [private]
Definition at line 861 of file liftoff-compiler.cc.
kFirstInputIdx
constexpr uint32_t v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::kFirstInputIdx = 2 [static], [constexpr], [private]
Definition at line 856 of file liftoff-compiler.cc.
kind_
ValueKind v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::kind_ [private]
Definition at line 862 of file liftoff-compiler.cc.
location_
LinkageLocation v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::location_ {LinkageLocation::ForAnyRegister()} [private]
Definition at line 866 of file liftoff-compiler.cc.
needs_gp_pair_
bool v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::needs_gp_pair_ [private]
Definition at line 863 of file liftoff-compiler.cc.
num_params_
const uint32_t v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::num_params_ [private]
Definition at line 859 of file liftoff-compiler.cc.
param_idx_
uint32_t v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::param_idx_ {0} [private]
Definition at line 860 of file liftoff-compiler.cc.
param_regs_
LiftoffRegList v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::param_regs_ [private]
Definition at line 867 of file liftoff-compiler.cc.
rc_
RegClass v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::rc_ [private]
Definition at line 865 of file liftoff-compiler.cc.
reg_kind_
ValueKind v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ParameterProcessor::reg_kind_ [private]
Definition at line 864 of file liftoff-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-compiler.cc