v8::internal::InstructionStream::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, ObjectVisitor *v)
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Static Public Attributes
static constexpr int kRelocModeMask
Additional Inherited Members
Detailed Description
Definition at line 1303 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody() [1/2]
template<typename ObjectVisitor >
static void v8::internal::InstructionStream::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 1335 of file objects-body-descriptors-inl.h.
                                                                    {
    IterateBody(map, obj, v);
  }
References IterateBody().
IterateBody() [2/2]
template<typename ObjectVisitor >
static void v8::internal::InstructionStream::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, ObjectVisitor * v) [inline], [static]
Definition at line 1322 of file objects-body-descriptors-inl.h.
                                                   {
    IterateProtectedPointer(obj, kCodeOffset, v);
    IterateProtectedPointer(obj, kRelocationInfoOffset, v);
    Tagged<InstructionStream> istream = UncheckedCast<InstructionStream>(obj);
    if (istream->IsFullyInitialized()) {
      RelocIterator it(istream, kRelocModeMask);
      v->VisitRelocInfo(istream, &it);
    }
  }
References v8::internal::BodyDescriptorBase::IterateProtectedPointer(), kRelocModeMask, and v8::internal::ObjectVisitor::VisitRelocInfo().
Referenced by IterateBody().
SizeOf()
static int v8::internal::InstructionStream::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 1340 of file objects-body-descriptors-inl.h.
                                                                       {
    return UncheckedCast<InstructionStream>(object)->Size();
  }
Member Data Documentation
kRelocModeMask
constexpr int v8::internal::InstructionStream::BodyDescriptor::kRelocModeMask [static], [constexpr]
Initial value:
=
      RelocInfo::ModeMask(RelocInfo::CODE_TARGET) |
      RelocInfo::ModeMask(RelocInfo::RELATIVE_CODE_TARGET) |
      RelocInfo::ModeMask(RelocInfo::FULL_EMBEDDED_OBJECT) |
      RelocInfo::ModeMask(RelocInfo::COMPRESSED_EMBEDDED_OBJECT) |
      RelocInfo::ModeMask(RelocInfo::EXTERNAL_REFERENCE) |
      RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE) |
      RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE_ENCODED) |
      RelocInfo::ModeMask(RelocInfo::OFF_HEAP_TARGET) |
      RelocInfo::ModeMask(RelocInfo::WASM_STUB_CALL)
Definition at line 1310 of file objects-body-descriptors-inl.h.
Referenced by IterateBody().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h