v8::internal::DateParser::TimeComposer Class Reference
Public Member Functions
TimeComposer ()
bool IsEmpty () const
bool IsExpecting (int n) const
bool Add (int n)
bool AddFinal (int n)
void SetHourOffset (int n)
bool Write (double *output)
Static Public Member Functions
static bool IsMinute (int x)
static bool IsHour (int x)
static bool IsSecond (int x)
Static Private Member Functions
static bool IsHour12 (int x)
static bool IsMillisecond (int x)
Private Attributes
int comp_ [kSize]
int index_
int hour_offset_
Static Private Attributes
static const int kSize = 4
Detailed Description
Definition at line 294 of file dateparser.h.
Constructor & Destructor Documentation
TimeComposer()
v8::internal::DateParser::TimeComposer::TimeComposer () [inline]
Definition at line 296 of file dateparser.h.
: index_(0), hour_offset_(kNone) {}
Member Function Documentation
Add()
bool v8::internal::DateParser::TimeComposer::Add (int n) [inline]
Definition at line 302 of file dateparser.h.
                    {
      return index_ < kSize ? (comp_[index_++] = n, true) : false;
    }
References comp_, index_, and kSize.
Referenced by AddFinal().
AddFinal()
bool v8::internal::DateParser::TimeComposer::AddFinal (int n) [inline]
Definition at line 305 of file dateparser.h.
                         {
      if (!Add(n)) return false;
      while (index_ < kSize) comp_[index_++] = 0;
      return true;
    }
References Add(), comp_, index_, and kSize.
IsEmpty()
bool v8::internal::DateParser::TimeComposer::IsEmpty () const [inline]
Definition at line 297 of file dateparser.h.
{ return index_ == 0; }
References index_.
IsExpecting()
bool v8::internal::DateParser::TimeComposer::IsExpecting (int n) const [inline]
Definition at line 298 of file dateparser.h.
                                  {
      return (index_ == 1 && IsMinute(n)) || (index_ == 2 && IsSecond(n)) ||
             (index_ == 3 && IsMillisecond(n));
    }
References index_, IsMillisecond(), IsMinute(), and IsSecond().
IsHour()
static bool v8::internal::DateParser::TimeComposer::IsHour (int x) [inline], [static]
Definition at line 314 of file dateparser.h.
{ return Between(x, 0, 23); }
References v8::internal::DateParser::Between().
Referenced by v8::internal::DateParser::ParseES5DateTime().
IsHour12()
static bool v8::internal::DateParser::TimeComposer::IsHour12 (int x) [inline], [static], [private]
Definition at line 318 of file dateparser.h.
{ return Between(x, 0, 12); }
References v8::internal::DateParser::Between().
IsMillisecond()
static bool v8::internal::DateParser::TimeComposer::IsMillisecond (int x) [inline], [static], [private]
Definition at line 319 of file dateparser.h.
{ return Between(x, 0, 999); }
References v8::internal::DateParser::Between().
Referenced by IsExpecting().
IsMinute()
static bool v8::internal::DateParser::TimeComposer::IsMinute (int x) [inline], [static]
Definition at line 313 of file dateparser.h.
{ return Between(x, 0, 59); }
References v8::internal::DateParser::Between().
Referenced by v8::internal::DateParser::TimeZoneComposer::IsExpecting(), IsExpecting(), and v8::internal::DateParser::ParseES5DateTime().
IsSecond()
static bool v8::internal::DateParser::TimeComposer::IsSecond (int x) [inline], [static]
Definition at line 315 of file dateparser.h.
{ return Between(x, 0, 59); }
References v8::internal::DateParser::Between().
Referenced by IsExpecting(), and v8::internal::DateParser::ParseES5DateTime().
SetHourOffset()
void v8::internal::DateParser::TimeComposer::SetHourOffset (int n) [inline]
Definition at line 310 of file dateparser.h.
{ hour_offset_ = n; }
References hour_offset_.
Write()
bool v8::internal::DateParser::TimeComposer::Write (double * output)
Definition at line 67 of file dateparser.cc.
                                                 {
  // All time slots default to 0
  while (index_ < kSize) {
    comp_[index_++] = 0;
  }
  int& hour = comp_[0];
  int& minute = comp_[1];
  int& second = comp_[2];
  int& millisecond = comp_[3];
  if (hour_offset_ != kNone) {
    if (!IsHour12(hour)) return false;
    hour %= 12;
    hour += hour_offset_;
  }
  if (!IsHour(hour) || !IsMinute(minute) || !IsSecond(second) ||
      !IsMillisecond(millisecond)) {
    // A 24th hour is allowed if minutes, seconds, and milliseconds are 0
    if (hour != 24 || minute != 0 || second != 0 || millisecond != 0) {
      return false;
    }
  }
  output[HOUR] = hour;
  output[MINUTE] = minute;
  output[SECOND] = second;
  output[MILLISECOND] = millisecond;
  return true;
}
References v8::internal::DateParser::HOUR, v8::internal::DateParser::kNone, v8::internal::DateParser::MILLISECOND, v8::internal::DateParser::MINUTE, and v8::internal::DateParser::SECOND.
Member Data Documentation
comp_
int v8::internal::DateParser::TimeComposer::comp_[kSize] [private]
Definition at line 322 of file dateparser.h.
Referenced by Add(), and AddFinal().
hour_offset_
int v8::internal::DateParser::TimeComposer::hour_offset_ [private]
Definition at line 324 of file dateparser.h.
Referenced by SetHourOffset().
index_
int v8::internal::DateParser::TimeComposer::index_ [private]
Definition at line 323 of file dateparser.h.
Referenced by Add(), AddFinal(), IsEmpty(), and IsExpecting().
kSize
const int v8::internal::DateParser::TimeComposer::kSize = 4 [static], [private]
Definition at line 321 of file dateparser.h.
Referenced by Add(), and AddFinal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/date/dateparser.h
/mnt/V8SourceCode/src/date/dateparser.cc