v8::base::AsAtomicImpl< TAtomicStorageType > Class Template Reference
#include <atomic-utils.h>
Classes
struct cast_helper
struct cast_helper< base::StrongAlias< T, U > >
struct cast_helper< U * >
Public Types
using AtomicStorageType = TAtomicStorageType
Static Public Member Functions
template<typename T >
static T SeqCst_Load (T *addr)
template<typename T >
static T Acquire_Load (T *addr)
template<typename T >
static T Relaxed_Load (T *addr)
template<typename T >
static void SeqCst_Store (T *addr, std::remove_reference_t< T > new_value)
template<typename T >
static void Release_Store (T *addr, std::remove_reference_t< T > new_value)
template<typename T >
static void Relaxed_Store (T *addr, std::remove_reference_t< T > new_value)
template<typename T >
static T SeqCst_Swap (T *addr, std::remove_reference_t< T > new_value)
template<typename T >
static T Release_CompareAndSwap (T *addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value)
template<typename T >
static T Relaxed_CompareAndSwap (T *addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value)
template<typename T >
static T AcquireRelease_CompareAndSwap (T *addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value)
template<typename T >
static T SeqCst_CompareAndSwap (T *addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value)
template<typename T >
static bool Release_SetBits (T *addr, T bits, T mask)
template<typename T >
static bool Relaxed_SetBits (T *addr, T bits, T mask)
Static Private Member Functions
template<typename T >
static AtomicStorageType * to_storage_addr (T *value)
template<typename T >
static const AtomicStorageType * to_storage_addr (const T *value)
Detailed Description
template<typename TAtomicStorageType>
class v8::base::AsAtomicImpl< TAtomicStorageType >
Definition at line 66 of file atomic-utils.h.
Member Typedef Documentation
AtomicStorageType
template<typename TAtomicStorageType >
using v8::base::AsAtomicImpl< TAtomicStorageType >::AtomicStorageType = TAtomicStorageType
Definition at line 68 of file atomic-utils.h.
Member Function Documentation
Acquire_Load()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load (T * addr) [inline], [static]
Definition at line 78 of file atomic-utils.h.
                                 {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(
        base::Acquire_Load(to_storage_addr(addr)));
  }
References v8::base::Acquire_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::FullObjectSlot::Acquire_Load(), v8::internal::TaggedMember< T, CompressionScheme >::Acquire_Load(), v8::internal::IndirectPointerSlot::Acquire_LoadHandle(), v8::internal::StringForwardingTable::Record::ExternalResourceAddress(), v8::internal::String::length(), v8::internal::StringForwardingTable::BlockVector::LoadBlock(), heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell(), v8::internal::ReadIndirectPointerField(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::MutablePageMetadata::typed_slot_set().
AcquireRelease_CompareAndSwap()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::AcquireRelease_CompareAndSwap (T * addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 138 of file atomic-utils.h.
                                                                             {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(base::AcquireRelease_CompareAndSwap(
        to_storage_addr(addr), cast_helper<T>::to_storage_type(old_value),
        cast_helper<T>::to_storage_type(new_value)));
  }
References v8::base::AcquireRelease_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::MutablePageMetadata::AllocateSlotSet(), and v8::internal::StringForwardingTable::Record::TryUpdateExternalResource().
Relaxed_CompareAndSwap()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap (T * addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 129 of file atomic-utils.h.
                                                                      {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(base::Relaxed_CompareAndSwap(
        to_storage_addr(addr), cast_helper<T>::to_storage_type(old_value),
        cast_helper<T>::to_storage_type(new_value)));
  }
References v8::base::Relaxed_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::SharedFunctionInfo::CompareExchangeAge(), v8::internal::FullObjectSlot::Relaxed_CompareAndSwap(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_SetBits().
Relaxed_Load()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load (T * addr) [inline], [static]
Definition at line 85 of file atomic-utils.h.
                                 {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(
        base::Relaxed_Load(to_storage_addr(addr)));
  }
References v8::base::Relaxed_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::SemiSpace::current_capacity_safe(), v8::internal::JSSynchronizationPrimitive::DestructivelyGetWaiterQueueHead(), v8::internal::HeapObject::IsLazilyInitializedExternalPointerFieldInitialized(), v8::internal::TypedSlotSet::LoadHead(), v8::internal::TypedSlotSet::LoadNext(), v8::internal::MarkBit::Get< AccessMode::ATOMIC >(), v8::internal::EmbedderDataSlot::MustClearDuringSerialization(), v8::internal::AtomicSlot::Reference::operator Tagged_t(), v8::internal::AtomicSlot::Reference::operator=(), v8::internal::ReadCodeEntrypointViaCodePointerField(), v8::internal::ReadExternalPointerField(), v8::internal::FullObjectSlot::Relaxed_ContainsMapValue(), v8::internal::FullObjectSlot::Relaxed_Load(), v8::internal::FullMaybeObjectSlot::Relaxed_Load(), v8::internal::TaggedMember< T, CompressionScheme >::Relaxed_Load(), v8::internal::FullObjectSlot::Relaxed_Load_Raw(), v8::internal::FullMaybeObjectSlot::Relaxed_Load_Raw(), v8::internal::IndirectPointerSlot::Relaxed_LoadHandle(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_SetBits(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_SetBits(), v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead(), v8::internal::CppHeapPointerSlot::try_load(), v8::internal::AtomicSlot::Reference::value(), v8::internal::WriteCodeEntrypointViaCodePointerField(), v8::internal::WriteExternalPointerField(), and v8::internal::HeapObject::WriteLazilyInitializedExternalPointerField().
Relaxed_SetBits()
template<typename TAtomicStorageType >
template<typename T >
static bool v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_SetBits (T * addr, T bits, T mask) [inline], [static]
Definition at line 176 of file atomic-utils.h.
                                                       {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    DCHECK_EQ(bits & ~mask, static_cast<T>(0));
    T old_value = Relaxed_Load(addr);
    T new_value, old_value_before_cas;
    do {
      if ((old_value & mask) == bits) return false;
      new_value = (old_value & ~mask) | bits;
      old_value_before_cas = old_value;
      old_value = Relaxed_CompareAndSwap(addr, old_value, new_value);
    } while (old_value != old_value_before_cas);
    return true;
  }
References DCHECK_EQ, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by v8::internal::MarkBit::Set< AccessMode::ATOMIC >(), v8::internal::MarkingBitmap::ClearBitsInCell< AccessMode::ATOMIC >(), and v8::internal::MarkingBitmap::SetBitsInCell< AccessMode::ATOMIC >().
Relaxed_Store()
template<typename TAtomicStorageType >
template<typename T >
static void v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store (T * addr, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 106 of file atomic-utils.h.
                                                                         {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    base::Relaxed_Store(to_storage_addr(addr),
                        cast_helper<T>::to_storage_type(new_value));
  }
References v8::base::Relaxed_Store(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::SemiSpace::AdvancePage(), v8::internal::EmbedderDataSlot::gc_safe_store(), v8::internal::AtomicSlot::Reference::operator=(), v8::internal::FullMaybeObjectSlot::Relaxed_Store(), v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::TaggedMember< T, CompressionScheme >::Relaxed_Store_no_write_barrier(), v8::internal::IndirectPointerSlot::Relaxed_StoreHandle(), v8::internal::String::set_length(), v8::internal::JSSynchronizationPrimitive::SetNullWaiterQueueHead(), v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead(), v8::internal::CppHeapPointerSlot::store(), v8::internal::TypedSlotSet::StoreHead(), v8::internal::TypedSlotSet::StoreNext(), and v8::internal::AtomicSlot::Reference::swap().
Release_CompareAndSwap()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap (T * addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 120 of file atomic-utils.h.
                                                                      {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(base::Release_CompareAndSwap(
        to_storage_addr(addr), cast_helper<T>::to_storage_type(old_value),
        cast_helper<T>::to_storage_type(new_value)));
  }
References v8::base::Release_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::MutablePageMetadata::AllocateTypedSlotSet(), v8::internal::FullMaybeObjectSlot::Release_CompareAndSwap(), v8::internal::FullObjectSlot::Release_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_SetBits(), v8::internal::StringForwardingTable::Record::set_raw_hash_if_empty(), and heap::base::BasicSlotSet< SlotGranularity >::SwapInNewBucket().
Release_SetBits()
template<typename TAtomicStorageType >
template<typename T >
static bool v8::base::AsAtomicImpl< TAtomicStorageType >::Release_SetBits (T * addr, T bits, T mask) [inline], [static]
Definition at line 159 of file atomic-utils.h.
                                                       {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    DCHECK_EQ(bits & ~mask, static_cast<T>(0));
    T old_value = Relaxed_Load(addr);
    T new_value, old_value_before_cas;
    do {
      if ((old_value & mask) == bits) return false;
      new_value = (old_value & ~mask) | bits;
      old_value_before_cas = old_value;
      old_value = Release_CompareAndSwap(addr, old_value, new_value);
    } while (old_value != old_value_before_cas);
    return true;
  }
References DCHECK_EQ, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Bucket::ClearCellBits(), and heap::base::BasicSlotSet< SlotGranularity >::Bucket::SetCellBits().
Release_Store()
template<typename TAtomicStorageType >
template<typename T >
static void v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store (T * addr, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 99 of file atomic-utils.h.
                                                                         {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    base::Release_Store(to_storage_addr(addr),
                        cast_helper<T>::to_storage_type(new_value));
  }
References v8::base::Release_Store(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::StringForwardingTable::BlockVector::AddBlock(), v8::internal::HeapObject::AllocateAndInstallJSDispatchHandle(), v8::internal::CppHeapPointerSlot::init(), v8::internal::JSArrayBuffer::init_extension(), v8::internal::InitExternalPointerField(), v8::internal::InitSelfIndirectPointerField(), v8::internal::FullObjectSlot::Release_Store(), v8::internal::TaggedMember< T, CompressionScheme >::Release_Store_no_write_barrier(), v8::internal::IndirectPointerSlot::Release_StoreHandle(), v8::internal::StringForwardingTable::Record::set_external_resource(), v8::internal::String::set_length(), v8::internal::MutablePageMetadata::set_slot_set(), v8::internal::MutablePageMetadata::set_typed_slot_set(), v8::internal::HeapObject::SetupLazilyInitializedExternalPointerField(), v8::internal::JSSynchronizationPrimitive::SetWaiterQueueHead(), heap::base::BasicSlotSet< SlotGranularity >::StoreBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::StoreCell(), v8::internal::WriteIndirectPointerField(), and v8::internal::HeapObject::WriteLazilyInitializedExternalPointerField().
SeqCst_CompareAndSwap()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_CompareAndSwap (T * addr, std::remove_reference_t< T > old_value, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 148 of file atomic-utils.h.
                                                                     {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(base::SeqCst_CompareAndSwap(
        to_storage_addr(addr), cast_helper<T>::to_storage_type(old_value),
        cast_helper<T>::to_storage_type(new_value)));
  }
References v8::base::SeqCst_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_CompareAndSwap().
SeqCst_Load()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Load (T * addr) [inline], [static]
Definition at line 71 of file atomic-utils.h.
                                {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return cast_helper<T>::to_return_type(
        base::SeqCst_Load(to_storage_addr(addr)));
  }
References v8::base::SeqCst_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::cast_helper< U >::to_return_type(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Load().
SeqCst_Store()
template<typename TAtomicStorageType >
template<typename T >
static void v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Store (T * addr, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 92 of file atomic-utils.h.
                                                                        {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    base::SeqCst_Store(to_storage_addr(addr),
                       cast_helper<T>::to_storage_type(new_value));
  }
References v8::base::SeqCst_Store(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Store_no_write_barrier().
SeqCst_Swap()
template<typename TAtomicStorageType >
template<typename T >
static T v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Swap (T * addr, std::remove_reference_t< T > new_value) [inline], [static]
Definition at line 113 of file atomic-utils.h.
                                                                    {
    static_assert(sizeof(T) <= sizeof(AtomicStorageType));
    return base::SeqCst_AtomicExchange(
        to_storage_addr(addr), cast_helper<T>::to_storage_type(new_value));
  }
References v8::base::SeqCst_AtomicExchange(), and v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr().
Referenced by v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Swap().
to_storage_addr() [1/2]
template<typename TAtomicStorageType >
template<typename T >
static const AtomicStorageType* v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr (const T * value) [inline], [static], [private]
Definition at line 225 of file atomic-utils.h.
                                                                  {
    return reinterpret_cast<const AtomicStorageType*>(value);
  }
References v8::internal::value.
to_storage_addr() [2/2]
template<typename TAtomicStorageType >
template<typename T >
static AtomicStorageType* v8::base::AsAtomicImpl< TAtomicStorageType >::to_storage_addr (T * value) [inline], [static], [private]
Definition at line 221 of file atomic-utils.h.
                                                      {
    return reinterpret_cast<AtomicStorageType*>(value);
  }
References v8::internal::value.
Referenced by v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::AcquireRelease_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_CompareAndSwap(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Load(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Store(), and v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Swap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/atomic-utils.h