v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next > Class Template Reference
#include <stack-check-lowering-reducer.h>
Public Member Functions
V< None > REDUCE() JSStackCheck (V< Context > context, OptionalV< FrameState > frame_state, JSStackCheckOp::Kind kind)
Private Member Functions
Isolate * isolate ()
Private Attributes
Isolate * isolate_ = nullptr
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >
Definition at line 22 of file stack-check-lowering-reducer.h.
Member Function Documentation
isolate()
template<class Next >
Isolate* v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::isolate () [inline], [private]
Definition at line 121 of file stack-check-lowering-reducer.h.
                     {
    if (!isolate_) isolate_ = __ data() -> isolate();
    return isolate_;
  }
References __, and v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::isolate_.
Referenced by v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck().
JSStackCheck()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck (V< Context > context, OptionalV< FrameState > frame_state, JSStackCheckOp::Kind kind) [inline]
Definition at line 26 of file stack-check-lowering-reducer.h.
                                                        {
    switch (kind) {
      case JSStackCheckOp::Kind::kFunctionEntry: {
        // Loads of the stack limit should not be load-eliminated as it can be
        // modified by another thread.
        V<WordPtr> limit =
            __ Load(__ ExternalConstant(
                        ExternalReference::address_of_jslimit(isolate())),
                    LoadOp::Kind::RawAligned().NotLoadEliminable(),
                    MemoryRepresentation::UintPtr());
        IF_NOT (LIKELY(__ StackPointerGreaterThan(
                    limit, StackCheckKind::kJSFunctionEntry))) {
          __ CallRuntime_StackGuardWithGap(isolate(), frame_state.value(),
                                           context, __ StackCheckOffset());
        }
        break;
      }
      case JSStackCheckOp::Kind::kBuiltinEntry: {
        V<WordPtr> stack_limit = __ LoadOffHeap(
            __ ExternalConstant(
                ExternalReference::address_of_jslimit(isolate())),
            MemoryRepresentation::UintPtr());
        IF_NOT (LIKELY(__ StackPointerGreaterThan(
                    stack_limit, StackCheckKind::kCodeStubAssembler))) {
          __ CallRuntime_StackGuard(isolate(), context);
        }
        break;
      }
      case JSStackCheckOp::Kind::kLoop: {
        V<Word32> limit = __ Load(
            __ ExternalConstant(
                ExternalReference::address_of_no_heap_write_interrupt_request(
                    isolate())),
            LoadOp::Kind::RawAligned().NotLoadEliminable(),
            MemoryRepresentation::Uint8());
        IF_NOT (LIKELY(__ Word32Equal(limit, 0))) {
          __ CallRuntime_HandleNoHeapWritesInterrupts(
              isolate(), frame_state.value(), context);
        }
        break;
      }
    }
    return V<None>::Invalid();
  }
References __, v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::isolate(), v8::internal::compiler::turboshaft::JSStackCheckOp::kBuiltinEntry, v8::internal::compiler::kCodeStubAssembler, v8::internal::compiler::turboshaft::JSStackCheckOp::kFunctionEntry, v8::internal::compiler::kJSFunctionEntry, v8::internal::compiler::turboshaft::JSStackCheckOp::kLoop, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Member Data Documentation
isolate_
template<class Next >
Isolate* v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::isolate_ = nullptr [private]
Definition at line 126 of file stack-check-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::isolate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/stack-check-lowering-reducer.h