v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache Class Reference
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeHandle< Code > Get (Isolate *isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, CodeKind code_kind)
static void Insert (Isolate *isolate, Tagged< JSFunction > function, BytecodeOffset osr_offset, Tagged< Code > code, bool is_function_context_specializing)
Detailed Description
Definition at line 981 of file compiler.cc.
Member Function Documentation
Get()
static V8_WARN_UNUSED_RESULT MaybeHandle<Code> v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Get (Isolate * isolate, DirectHandle< JSFunction > function, BytecodeOffset osr_offset, CodeKind code_kind) [inline], [static]
Definition at line 983 of file compiler.cc.
                                                     {
    DCHECK_IMPLIES(V8_ENABLE_LEAPTIERING_BOOL, IsOSR(osr_offset));
    if (!CodeKindIsStoredInOptimizedCodeCache(code_kind)) return {};
    if (!function->has_feedback_vector()) return {};
    DisallowGarbageCollection no_gc;
    Tagged<SharedFunctionInfo> shared = function->shared();
    RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileGetFromOptimizedCodeMap);
    Tagged<Code> code;
    Tagged<FeedbackVector> feedback_vector = function->feedback_vector();
    if (IsOSR(osr_offset)) {
      Handle<BytecodeArray> bytecode(shared->GetBytecodeArray(isolate),
                                     isolate);
      interpreter::BytecodeArrayIterator it(bytecode, osr_offset.ToInt());
      // Bytecode may be different, so make sure we're at a valid OSR entry.
      SBXCHECK(it.CurrentBytecodeIsValidOSREntry());
      std::optional<Tagged<Code>> maybe_code =
          feedback_vector->GetOptimizedOsrCode(isolate, bytecode,
                                               it.GetSlotOperand(2));
      if (maybe_code.has_value()) code = maybe_code.value();
    } else {
#ifdef V8_ENABLE_LEAPTIERING
      UNREACHABLE();
#else
      feedback_vector->EvictOptimizedCodeMarkedForDeoptimization(
          isolate, shared, "OptimizedCodeCache::Get");
      code = feedback_vector->optimized_code(isolate);
#endif // V8_ENABLE_LEAPTIERING
    }
    // Normal tierup should never request a code-kind we already have. In case
    // of OSR it can happen that we OSR from ignition to turbofan. This is
    // explicitly allowed here by reusing any larger-kinded than requested
    // code.
    DCHECK_IMPLIES(!code.is_null() && code->kind() > code_kind,
                   IsOSR(osr_offset));
    if (code.is_null() || code->kind() < code_kind) return {};
    DCHECK(!code->marked_for_deoptimization());
    DCHECK(shared->is_compiled());
    DCHECK(CodeKindIsStoredInOptimizedCodeCache(code->kind()));
    DCHECK_IMPLIES(IsOSR(osr_offset), CodeKindCanOSR(code->kind()));
    CompilerTracer::TraceOptimizedCodeCacheHit(isolate, function, osr_offset,
                                               code_kind);
    return handle(code, isolate);
  }
References code, v8::internal::CodeKindCanOSR(), v8::internal::CodeKindIsStoredInOptimizedCodeCache(), v8::internal::interpreter::BytecodeArrayIterator::CurrentBytecodeIsValidOSREntry(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::interpreter::BytecodeArrayIterator::GetSlotOperand(), v8::internal::handle(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RCS_SCOPE, SBXCHECK, v8::internal::BytecodeOffset::ToInt(), v8::internal::UNREACHABLE(), and V8_ENABLE_LEAPTIERING_BOOL.
Insert()
static void v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Insert (Isolate * isolate, Tagged< JSFunction > function, BytecodeOffset osr_offset, Tagged< Code > code, bool is_function_context_specializing) [inline], [static]
Definition at line 1034 of file compiler.cc.
                                                            {
    DCHECK_IMPLIES(V8_ENABLE_LEAPTIERING_BOOL, IsOSR(osr_offset));
    const CodeKind kind = code->kind();
    if (!CodeKindIsStoredInOptimizedCodeCache(kind)) return;
    Tagged<FeedbackVector> feedback_vector = function->feedback_vector();
    if (IsOSR(osr_offset)) {
      DCHECK(CodeKindCanOSR(kind));
      DCHECK(!is_function_context_specializing);
      Tagged<SharedFunctionInfo> shared = function->shared();
      Handle<BytecodeArray> bytecode(shared->GetBytecodeArray(isolate),
                                     isolate);
      interpreter::BytecodeArrayIterator it(bytecode, osr_offset.ToInt());
      // Bytecode may be different, so make sure we're at a valid OSR entry.
      SBXCHECK(it.CurrentBytecodeIsValidOSREntry());
      feedback_vector->SetOptimizedOsrCode(isolate, it.GetSlotOperand(2), code);
      return;
    }
#ifdef V8_ENABLE_LEAPTIERING
    UNREACHABLE();
#else
    DCHECK(!IsOSR(osr_offset));
    if (is_function_context_specializing) {
      // Function context specialization folds-in the function context, so no
      // sharing can occur. Make sure the optimized code cache is cleared.
      // Only do so if the specialized code's kind matches the cached code kind.
      if (feedback_vector->has_optimized_code() &&
          feedback_vector->optimized_code(isolate)->kind() == code->kind()) {
        feedback_vector->ClearOptimizedCode();
      }
      return;
    }
    function->shared()->set_function_context_independent_compiled(true);
    feedback_vector->SetOptimizedCode(isolate, code);
#endif // V8_ENABLE_LEAPTIERING
  }
References code, v8::internal::CodeKindCanOSR(), v8::internal::CodeKindIsStoredInOptimizedCodeCache(), v8::internal::interpreter::BytecodeArrayIterator::CurrentBytecodeIsValidOSREntry(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::interpreter::BytecodeArrayIterator::GetSlotOperand(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), SBXCHECK, v8::internal::BytecodeOffset::ToInt(), v8::internal::UNREACHABLE(), and V8_ENABLE_LEAPTIERING_BOOL.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/compiler.cc