v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived > Class Template Reference
#include <graph.h>
Public Member Functions
void SetDominator (Derived *dominator)
void SetAsDominatorRoot ()
Derived * GetDominator () const
Derived * GetCommonDominator (RandomAccessStackDominatorNode< Derived > *other) const
bool IsDominatedBy (const Derived *other) const
int Depth () const
Private Attributes
int jmp_len_ = 0
int len_ = 0
Derived * nxt_ = nullptr
Derived * jmp_ = nullptr
Friends
class DominatorForwardTreeNode< Derived >
Detailed Description
template<class Derived>
class v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >
Definition at line 233 of file graph.h.
Member Function Documentation
Depth()
template<class Derived >
int v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::Depth () const [inline]
Definition at line 255 of file graph.h.
{ return len_; }
References v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::len_.
Referenced by v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ResetToBlock(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ResetToBlock().
GetCommonDominator()
template<class Derived >
Derived * v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator (RandomAccessStackDominatorNode< Derived > * other) const [inline]
Definition at line 1352 of file graph.h.
                                                          {
  const RandomAccessStackDominatorNode* a = this;
  const RandomAccessStackDominatorNode* b = other;
  if (b->len_ > a->len_) {
    // Swapping |a| and |b| so that |a| always has a greater length.
    std::swap(a, b);
  }
  DCHECK_GE(a->len_, 0);
  DCHECK_GE(b->len_, 0);
  // Going up the dominators of |a| in order to reach the level of |b|.
  while (a->len_ != b->len_) {
    DCHECK_GE(a->len_, 0);
    if (a->jmp_len_ >= b->len_) {
      a = a->jmp_;
    } else {
      a = a->nxt_;
    }
  }
  // Going up the dominators of |a| and |b| simultaneously until |a| == |b|
  while (a != b) {
    DCHECK_EQ(a->len_, b->len_);
    DCHECK_GE(a->len_, 0);
    if (a->jmp_ == b->jmp_) {
      // We found a common dominator, but we actually want to find the smallest
      // one, so we go down in the current subtree.
      a = a->nxt_;
      b = b->nxt_;
    } else {
      a = a->jmp_;
      b = b->jmp_;
    }
  }
  return static_cast<Derived*>(
      const_cast<RandomAccessStackDominatorNode<Derived>*>(a));
}
References DCHECK_EQ, DCHECK_GE, v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::jmp_, v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::jmp_len_, v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::len_, and v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::nxt_.
Referenced by v8::internal::compiler::turboshaft::Block::ComputeDominator(), and v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::IsDominatedBy().
GetDominator()
template<class Derived >
Derived* v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetDominator () const [inline]
Definition at line 243 of file graph.h.
{ return nxt_; }
References v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::nxt_.
Referenced by v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ReplayMissingPredecessors(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::ResetToBlock(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ResetToBlock().
IsDominatedBy()
template<class Derived >
bool v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::IsDominatedBy (const Derived * other) const [inline]
Definition at line 249 of file graph.h.
                                                 {
    // TODO(dmercadier): we don't have to call GetCommonDominator and could
    // determine quicker that {this} isn't dominated by {other}.
    return GetCommonDominator(other) == other;
  }
References v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator().
SetAsDominatorRoot()
template<class Derived >
void v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::SetAsDominatorRoot [inline]
Definition at line 1323 of file graph.h.
                                                                        {
  jmp_ = static_cast<Derived*>(this);
  nxt_ = nullptr;
  len_ = 0;
  jmp_len_ = 0;
}
SetDominator()
template<class Derived >
void v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::SetDominator (Derived * dominator) [inline]
Definition at line 1331 of file graph.h.
                        {
  DCHECK_NOT_NULL(dominator);
  DCHECK_NULL(static_cast<Block*>(this)->neighboring_child_);
  DCHECK_NULL(static_cast<Block*>(this)->last_child_);
  // Determining the jmp pointer
  Derived* t = dominator->jmp_;
  if (dominator->len_ - t->len_ == t->len_ - t->jmp_len_) {
    t = t->jmp_;
  } else {
    t = dominator;
  }
  // Initializing fields
  nxt_ = dominator;
  jmp_ = t;
  len_ = dominator->len_ + 1;
  jmp_len_ = jmp_->len_;
  dominator->AddChild(static_cast<Derived*>(this));
}
References DCHECK_NOT_NULL, and DCHECK_NULL.
Friends And Related Function Documentation
DominatorForwardTreeNode< Derived >
template<class Derived >
friend class DominatorForwardTreeNode< Derived > [friend]
Definition at line 255 of file graph.h.
Member Data Documentation
jmp_
template<class Derived >
Derived* v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::jmp_ = nullptr [private]
Definition at line 270 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator().
jmp_len_
template<class Derived >
int v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::jmp_len_ = 0 [private]
Definition at line 266 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator().
len_
template<class Derived >
int v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::len_ = 0 [private]
Definition at line 268 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::Depth(), and v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator().
nxt_
template<class Derived >
Derived* v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::nxt_ = nullptr [private]
Definition at line 269 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetCommonDominator(), and v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetDominator().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/graph.h