v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32 Class Reference
Public Member Functions
DecodeVarInt32 (size_t max_value, const char *field_name)
base::Vector< uint8_t > buffer () override
size_t ReadBytes (AsyncStreamingDecoder *streaming, base::Vector< const uint8_t > bytes) override
std::unique_ptr< DecodingState > Next (AsyncStreamingDecoder *streaming) override
virtual std::unique_ptr< DecodingState > NextWithValue (AsyncStreamingDecoder *streaming)=0
Protected Attributes
uint8_t byte_buffer_ [kMaxVarInt32Size]
const size_t max_value_
const char *const field_name_
size_t value_ = 0
size_t bytes_consumed_ = 0
Detailed Description
Definition at line 406 of file streaming-decoder.cc.
Constructor & Destructor Documentation
DecodeVarInt32()
v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::DecodeVarInt32 (size_t max_value, const char * field_name) [inline], [explicit]
Definition at line 408 of file streaming-decoder.cc.
      : max_value_(max_value), field_name_(field_name) {}
Member Function Documentation
buffer()
base::Vector<uint8_t> v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::buffer () [inline], [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 411 of file streaming-decoder.cc.
                                        {
    return base::ArrayVector(byte_buffer_);
  }
References v8::base::ArrayVector().
Next()
std::unique_ptr< AsyncStreamingDecoder::DecodingState > v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::Next (AsyncStreamingDecoder * streaming) [override], [virtual]
Implements v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 599 of file streaming-decoder.cc.
                                                                          {
  if (!streaming->ok()) return nullptr;
  if (value_ > max_value_) return streaming->ToErrorState();
  return NextWithValue(streaming);
}
References v8::internal::wasm::AsyncStreamingDecoder::ok(), and v8::internal::wasm::AsyncStreamingDecoder::ToErrorState().
NextWithValue()
virtual std::unique_ptr<DecodingState> v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::NextWithValue (AsyncStreamingDecoder * streaming) [pure virtual]
Implemented in v8::internal::wasm::AsyncStreamingDecoder::DecodeFunctionLength, v8::internal::wasm::AsyncStreamingDecoder::DecodeNumberOfFunctions, and v8::internal::wasm::AsyncStreamingDecoder::DecodeSectionLength.
ReadBytes()
size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::ReadBytes (AsyncStreamingDecoder * streaming, base::Vector< const uint8_t > bytes) [override], [virtual]
Reimplemented from v8::internal::wasm::AsyncStreamingDecoder::DecodingState.
Definition at line 563 of file streaming-decoder.cc.
                                                                       {
  base::Vector<uint8_t> buf = buffer();
  base::Vector<uint8_t> remaining_buf = buf + offset();
  size_t new_bytes = std::min(bytes.size(), remaining_buf.size());
  TRACE_STREAMING("ReadBytes of a VarInt\n");
  memcpy(remaining_buf.begin(), &bytes.first(), new_bytes);
  buf.Truncate(offset() + new_bytes);
  Decoder decoder(buf,
                  streaming->module_offset() - static_cast<uint32_t>(offset()));
  value_ = decoder.consume_u32v(field_name_);
  if (decoder.failed()) {
    if (new_bytes == remaining_buf.size()) {
      // We only report an error if we read all bytes.
      streaming->Fail();
    }
    set_offset(offset() + new_bytes);
    return new_bytes;
  }
  // The number of bytes we actually needed to read.
  DCHECK_GT(decoder.pc(), buffer().begin());
  bytes_consumed_ = static_cast<size_t>(decoder.pc() - buf.begin());
  TRACE_STREAMING(" ==> %zu bytes consumed\n", bytes_consumed_);
  // We read all the bytes we needed.
  DCHECK_GT(bytes_consumed_, offset());
  new_bytes = bytes_consumed_ - offset();
  // Set the offset to the buffer size to signal that we are at the end of this
  // section.
  set_offset(buffer().size());
  return new_bytes;
}
References v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), v8::internal::wasm::Decoder::consume_u32v(), DCHECK_GT, v8::internal::wasm::AsyncStreamingDecoder::Fail(), v8::internal::wasm::Decoder::failed(), v8::base::Vector< T >::first(), v8::internal::wasm::AsyncStreamingDecoder::module_offset(), v8::internal::wasm::Decoder::pc(), v8::base::Vector< T >::size(), size(), TRACE_STREAMING, and v8::base::Vector< T >::Truncate().
Member Data Documentation
byte_buffer_
uint8_t v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::byte_buffer_[kMaxVarInt32Size] [protected]
Definition at line 425 of file streaming-decoder.cc.
bytes_consumed_
size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::bytes_consumed_ = 0 [protected]
Definition at line 431 of file streaming-decoder.cc.
field_name_
const char* const v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::field_name_ [protected]
Definition at line 429 of file streaming-decoder.cc.
max_value_
const size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::max_value_ [protected]
Definition at line 428 of file streaming-decoder.cc.
value_
size_t v8::internal::wasm::AsyncStreamingDecoder::DecodeVarInt32::value_ = 0 [protected]
Definition at line 430 of file streaming-decoder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/streaming-decoder.cc