v8::internal::ByteArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Public Types
using Shape = ByteArrayShape
Public Member Functions
uint32_t get_int (int offset) const
void set_int (int offset, uint32_t value)
Static Public Member Functions
template<class IsolateT >
static Handle< ByteArray > New (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static constexpr int LengthFor (int size_in_bytes)
Private Types
using Super = PrimitiveArrayBase< ByteArray, ByteArrayShape >
Additional Inherited Members
Detailed Description
Definition at line 764 of file fixed-array.h.
Member Typedef Documentation
Shape
using v8::internal::ByteArray::Shape = ByteArrayShape
Definition at line 769 of file fixed-array.h.
Super
using v8::internal::ByteArray::Super = PrimitiveArrayBase<ByteArray, ByteArrayShape> [private]
Definition at line 766 of file fixed-array.h.
Member Function Documentation
get_int()
uint32_t v8::internal::ByteArray::get_int (int offset) const [inline]
Definition at line 769 of file fixed-array-inl.h.
                                            {
  DCHECK(IsInBounds(offset));
  DCHECK_LE(offset + sizeof(uint32_t), length());
  return base::ReadUnalignedValue<uint32_t>(
      reinterpret_cast<Address>(&values()[offset]));
}
References v8::internal::DCHECK(), DCHECK_LE, and v8::internal::length.
LengthFor()
static constexpr int v8::internal::ByteArray::LengthFor (int size_in_bytes) [inline], [static], [constexpr]
Definition at line 781 of file fixed-array.h.
                                                    {
    DCHECK(IsAligned(size_in_bytes, kTaggedSize));
    DCHECK_GE(size_in_bytes, sizeof(Header));
    return size_in_bytes - sizeof(Header);
  }
References v8::internal::DCHECK(), DCHECK_GE, IsAligned(), and v8::internal::kTaggedSize.
Referenced by v8::internal::TranslatedState::AllocateStorageFor(), and v8::internal::RUNTIME_FUNCTION().
New()
template<class IsolateT >
Handle< ByteArray > v8::internal::ByteArray::New (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [inline], [static]
Definition at line 751 of file fixed-array-inl.h.
                                                            {
  if (V8_UNLIKELY(static_cast<unsigned>(length) > kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d", length);
  } else if (V8_UNLIKELY(length == 0)) {
    return isolate->factory()->empty_byte_array();
  }
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<ByteArray> result =
      Cast<ByteArray>(Allocate(isolate, length, &no_gc, allocation));
  int padding_size = SizeFor(length) - OffsetOfElementAt(length);
  memset(&result->values()[length], 0, padding_size);
  return result;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), FATAL, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::WeakArrayList::OffsetOfElementAt(), v8::base::internal::result, and V8_UNLIKELY.
set_int()
void v8::internal::ByteArray::set_int (int offset, uint32_t value) [inline]
Definition at line 776 of file fixed-array-inl.h.
                                                  {
  DCHECK(IsInBounds(offset));
  DCHECK_LE(offset + sizeof(uint32_t), length());
  base::WriteUnalignedValue<uint32_t>(
      reinterpret_cast<Address>(&values()[offset]), value);
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::length, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h