cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category > Class Template Reference
Public Member Functions
template<typename... Args>
InternalScope (StatsCollector *stats_collector, ScopeIdType scope_id, Args... args)
~InternalScope ()
InternalScope (const InternalScope &)=delete
InternalScope & operator= (const InternalScope &)=delete
void DecreaseStartTimeForTesting (v8::base::TimeDelta delta)
Private Types
using ScopeIdType = std::conditional_t< scope_category==kMutatorThread, ScopeId, ConcurrentScopeId >
Private Member Functions
void * operator new (size_t, void *)=delete
void * operator new (size_t)=delete
template<typename... Args>
void StartTrace (Args... args)
void StopTrace ()
void StartTraceImpl ()
template<typename Value1 >
void StartTraceImpl (const char *k1, Value1 v1)
template<typename Value1 , typename Value2 >
void StartTraceImpl (const char *k1, Value1 v1, const char *k2, Value2 v2)
void StopTraceImpl ()
void IncreaseScopeTime ()
Static Private Member Functions
constexpr static const char * TraceCategory ()
Private Attributes
StatsCollector *const stats_collector_
v8::base::TimeTicks start_time_
const ScopeIdType scope_id_
Detailed Description
template<TraceCategory trace_category, ScopeContext scope_category>
class cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >
Definition at line 175 of file stats-collector.h.
Member Typedef Documentation
ScopeIdType
template<TraceCategory trace_category, ScopeContext scope_category>
using cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::ScopeIdType = std::conditional_t<scope_category == kMutatorThread, ScopeId, ConcurrentScopeId> [private]
Definition at line 176 of file stats-collector.h.
Constructor & Destructor Documentation
InternalScope() [1/2]
template<TraceCategory trace_category, ScopeContext scope_category>
template<typename... Args>
cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::InternalScope (StatsCollector * stats_collector, ScopeIdType scope_id, Args... args) [inline]
Definition at line 181 of file stats-collector.h.
        : stats_collector_(stats_collector),
          start_time_(v8::base::TimeTicks::Now()),
          scope_id_(scope_id) {
      DCHECK_LE(0, scope_id_);
      DCHECK_LT(static_cast<int>(scope_id_),
                scope_category == kMutatorThread
                    ? static_cast<int>(kNumScopeIds)
                    : static_cast<int>(kNumConcurrentScopeIds));
      DCHECK_NE(static_cast<int>(scope_id_),
                scope_category == kMutatorThread
                    ? static_cast<int>(kNumHistogramScopeIds)
                    : static_cast<int>(kNumHistogramConcurrentScopeIds));
      StartTrace(args...);
    }
References v8::base::args, DCHECK_LE, DCHECK_LT, and DCHECK_NE.
 InternalScope()
template<TraceCategory trace_category, ScopeContext scope_category>
cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::~InternalScope () [inline]
Definition at line 198 of file stats-collector.h.
                     {
      StopTrace();
      IncreaseScopeTime();
    }
InternalScope() [2/2]
template<TraceCategory trace_category, ScopeContext scope_category>
cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::InternalScope (const InternalScope< trace_category, scope_category > &) [delete]
Member Function Documentation
DecreaseStartTimeForTesting()
template<TraceCategory trace_category, ScopeContext scope_category>
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::DecreaseStartTimeForTesting (v8::base::TimeDelta delta) [inline]
Definition at line 206 of file stats-collector.h.
                                                            {
      start_time_ -= delta;
    }
IncreaseScopeTime()
template<TraceCategory trace_category, ScopeContext scope_category>
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::IncreaseScopeTime () [inline], [private]
Definition at line 498 of file stats-collector.h.
                                                                      {
  DCHECK_NE(GarbageCollectionState::kNotRunning, stats_collector_->gc_state_);
  // Only record top level scopes.
  if (static_cast<int>(scope_id_) >=
      (scope_category == kMutatorThread
           ? static_cast<int>(kNumHistogramScopeIds)
           : static_cast<int>(kNumHistogramConcurrentScopeIds)))
    return;
  v8::base::TimeDelta time = v8::base::TimeTicks::Now() - start_time_;
  if (scope_category == StatsCollector::ScopeContext::kMutatorThread) {
    stats_collector_->current_.scope_data[scope_id_] += time;
    if (stats_collector_->metric_recorder_)
      stats_collector_->RecordHistogramSample(scope_id_, time);
    return;
  }
  // scope_category == StatsCollector::ScopeContext::kConcurrentThread
  using AtomicWord = v8::base::AtomicWord;
  const int64_t us = time.InMicroseconds();
  v8::base::Relaxed_AtomicIncrement(
      &stats_collector_->current_.concurrent_scope_data[scope_id_],
      static_cast<AtomicWord>(us));
}
References DCHECK_NE, v8::base::TimeTicks::Now(), v8::base::Relaxed_AtomicIncrement(), and time().
operator new() [1/2]
template<TraceCategory trace_category, ScopeContext scope_category>
void* cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::operator new (size_t) [private], [delete]
operator new() [2/2]
template<TraceCategory trace_category, ScopeContext scope_category>
void* cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::operator new (size_t , void *) [private], [delete]
operator=()
template<TraceCategory trace_category, ScopeContext scope_category>
InternalScope& cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::operator= (const InternalScope< trace_category, scope_category > &) [delete]
StartTrace()
template<TraceCategory trace_category, ScopeContext scope_category>
template<typename... Args>
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StartTrace (Args... args) [inline], [private]
Definition at line 434 of file stats-collector.h.
                  {
  // Top level scopes that contribute to histogram should always be enabled.
  DCHECK_IMPLIES(static_cast<int>(scope_id_) <
                     (scope_category == kMutatorThread
                          ? static_cast<int>(kNumHistogramScopeIds)
                          : static_cast<int>(kNumHistogramConcurrentScopeIds)),
                 trace_category == StatsCollector::TraceCategory::kEnabled);
  StartTraceImpl(args...);
}
References v8::base::args, and DCHECK_IMPLIES.
StartTraceImpl() [1/3]
template<TraceCategory trace_category, ScopeContext scope_category>
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StartTraceImpl () [inline], [private]
Definition at line 455 of file stats-collector.h.
                                                                   {
  TRACE_EVENT_BEGIN0(
      TraceCategory(),
      GetScopeName(scope_id_, stats_collector_->current_.collection_type));
}
References TRACE_EVENT_BEGIN0.
StartTraceImpl() [2/3]
template<TraceCategory trace_category, ScopeContext scope_category>
template<typename Value1 >
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StartTraceImpl (const char * k1, Value1 v1) [inline], [private]
Definition at line 465 of file stats-collector.h.
                                                                             {
  TRACE_EVENT_BEGIN1(
      TraceCategory(),
      GetScopeName(scope_id_, stats_collector_->current_.collection_type), k1,
      v1);
}
References TRACE_EVENT_BEGIN1.
StartTraceImpl() [3/3]
template<TraceCategory trace_category, ScopeContext scope_category>
template<typename Value1 , typename Value2 >
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StartTraceImpl (const char * k1, Value1 v1, const char * k2, Value2 v2) [inline], [private]
Definition at line 476 of file stats-collector.h.
                                                                               {
  TRACE_EVENT_BEGIN2(
      TraceCategory(),
      GetScopeName(scope_id_, stats_collector_->current_.collection_type), k1,
      v1, k2, v2);
}
References TRACE_EVENT_BEGIN2.
StopTrace()
template<TraceCategory trace_category, ScopeContext scope_category>
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StopTrace () [inline], [private]
Definition at line 448 of file stats-collector.h.
                                                              {
  StopTraceImpl();
}
StopTraceImpl()
template<TraceCategory trace_category, ScopeContext scope_category>
void cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::StopTraceImpl () [inline], [private]
Definition at line 487 of file stats-collector.h.
                                                                  {
  TRACE_EVENT_END2(
      TraceCategory(),
      GetScopeName(scope_id_, stats_collector_->current_.collection_type),
      "epoch", stats_collector_->current_.epoch, "forced",
      stats_collector_->current_.is_forced_gc == IsForcedGC::kForced);
}
References TRACE_EVENT_END2.
TraceCategory()
template<TraceCategory trace_category, ScopeContext scope_category>
constexpr const char * cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::TraceCategory () [inline], [static], [constexpr], [private]
Definition at line 422 of file stats-collector.h.
                                                                           {
  switch (trace_category) {
    case kEnabled:
      return "cppgc";
    case kDisabled:
      return TRACE_DISABLED_BY_DEFAULT("cppgc");
  }
}
References cppgc::internal::kDisabled, cppgc::internal::kEnabled, and TRACE_DISABLED_BY_DEFAULT.
Member Data Documentation
scope_id_
template<TraceCategory trace_category, ScopeContext scope_category>
const ScopeIdType cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::scope_id_ [private]
Definition at line 232 of file stats-collector.h.
start_time_
template<TraceCategory trace_category, ScopeContext scope_category>
v8::base::TimeTicks cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::start_time_ [private]
Definition at line 231 of file stats-collector.h.
stats_collector_
template<TraceCategory trace_category, ScopeContext scope_category>
StatsCollector* const cppgc::internal::StatsCollector::InternalScope< trace_category, scope_category >::stats_collector_ [private]
Definition at line 230 of file stats-collector.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/stats-collector.h