v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency Class Reference
Public Member Functions
TransitionDependency (MapRef map)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef map_
Additional Inherited Members
Detailed Description
Definition at line 660 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
TransitionDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::TransitionDependency (MapRef map) [inline], [explicit]
Definition at line 662 of file compilation-dependencies.cc.
      : CompilationDependency(kTransition), map_(map) {
    DCHECK(map_.CanBeDeprecated());
  }
References v8::internal::DCHECK().
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 682 of file compilation-dependencies.cc.
                                                                {
    const TransitionDependency* const zat = that->AsTransition();
    return map_.equals(zat->map_);
  }
References map_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 677 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(map_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 671 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(map_.object(), DependentCode::kTransitionGroup);
  }
References broker(), v8::internal::DependentCode::kTransitionGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 667 of file compilation-dependencies.cc.
                                                    {
    return !map_.object()->is_deprecated();
  }
Member Data Documentation
map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::TransitionDependency::map_ [private]
Definition at line 687 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc