heap::base::Worklist< EntryType, MinSegmentSize >::Local Class Reference
#include <worklist.h>
Public Types
using ItemType = EntryType
Public Member Functions
Local (Worklist< EntryType, MinSegmentSize > &worklist)
~Local ()
Local (Local &&other) V8_NOEXCEPT
Local & operator= (Local &&) V8_NOEXCEPT=delete
Local (const Local &)=delete
Local & operator= (const Local &other)=delete
void Push (EntryType entry)
bool Pop (EntryType *entry)
bool IsLocalAndGlobalEmpty () const
bool IsLocalEmpty () const
bool IsGlobalEmpty () const
size_t PushSegmentSize () const
void Publish ()
void Merge (Worklist< EntryType, MinSegmentSize >::Local &other)
void Clear ()
Private Member Functions
void PublishPushSegment ()
void PublishPopSegment ()
bool StealPopSegment ()
Segment * NewSegment () const
void DeleteSegment (internal::SegmentBase *segment) const
Segment * push_segment ()
const Segment * push_segment () const
Segment * pop_segment ()
const Segment * pop_segment () const
Private Attributes
Worklist< EntryType, MinSegmentSize > & worklist_
internal::SegmentBase * push_segment_ = nullptr
internal::SegmentBase * pop_segment_ = nullptr
Detailed Description
template<typename EntryType, uint16_t MinSegmentSize>
class heap::base::Worklist< EntryType, MinSegmentSize >::Local
Definition at line 304 of file worklist.h.
Member Typedef Documentation
ItemType
template<typename EntryType , uint16_t MinSegmentSize>
using heap::base::Worklist< EntryType, MinSegmentSize >::Local::ItemType = EntryType
Definition at line 306 of file worklist.h.
Constructor & Destructor Documentation
Local() [1/3]
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::Local::Local (Worklist< EntryType, MinSegmentSize > & worklist) [explicit]
Definition at line 378 of file worklist.h.
    : worklist_(worklist),
      push_segment_(internal::SegmentBase::GetSentinelSegmentAddress()),
      pop_segment_(internal::SegmentBase::GetSentinelSegmentAddress()) {}
 Local()
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::Local::~Local
Definition at line 385 of file worklist.h.
                                                 {
  CHECK_IMPLIES(push_segment_, push_segment_->IsEmpty());
  CHECK_IMPLIES(pop_segment_, pop_segment_->IsEmpty());
  DeleteSegment(push_segment_);
  DeleteSegment(pop_segment_);
}
References CHECK_IMPLIES.
Local() [2/3]
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::Local::Local (Local && other) [inline]
Definition at line 313 of file worklist.h.
                                   : worklist_(other.worklist_) {
    std::swap(push_segment_, other.push_segment_);
    std::swap(pop_segment_, other.pop_segment_);
  }
Local() [3/3]
template<typename EntryType , uint16_t MinSegmentSize>
heap::base::Worklist< EntryType, MinSegmentSize >::Local::Local (const Local &) [delete]
Member Function Documentation
Clear()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::Clear
Definition at line 472 of file worklist.h.
                                                     {
  push_segment_->Clear();
  pop_segment_->Clear();
}
DeleteSegment()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::DeleteSegment (internal::SegmentBase * segment) const [inline], [private]
Definition at line 347 of file worklist.h.
                                                         {
    if (segment == internal::SegmentBase::GetSentinelSegmentAddress()) return;
    Segment::Delete(static_cast<Segment*>(segment));
  }
References heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Delete(), and heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
IsGlobalEmpty()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::Local::IsGlobalEmpty
Definition at line 425 of file worklist.h.
                                                                   {
  return worklist_.IsEmpty();
}
Referenced by v8::internal::Scavenger::Process().
IsLocalAndGlobalEmpty()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::Local::IsLocalAndGlobalEmpty
Definition at line 415 of file worklist.h.
                                                                           {
  return IsLocalEmpty() && IsGlobalEmpty();
}
IsLocalEmpty()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::Local::IsLocalEmpty
Definition at line 420 of file worklist.h.
                                                                  {
  return push_segment_->IsEmpty() && pop_segment_->IsEmpty();
}
Referenced by v8::internal::Scavenger::Process().
Merge()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::Merge (Worklist< EntryType, MinSegmentSize >::Local & other)
Definition at line 442 of file worklist.h.
                                                     {
  worklist_.Merge(other.worklist_);
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Local::worklist_.
NewSegment()
template<typename EntryType , uint16_t MinSegmentSize>
Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Local::NewSegment () const [inline], [private]
Definition at line 343 of file worklist.h.
                              {
    // Bottleneck for filtering in crash dumps.
    return Segment::Create(MinSegmentSize);
  }
References heap::base::Worklist< EntryType, MinSegmentSize >::Segment::Create().
operator=() [1/2]
template<typename EntryType , uint16_t MinSegmentSize>
Local& heap::base::Worklist< EntryType, MinSegmentSize >::Local::operator= (const Local & other) [delete]
operator=() [2/2]
template<typename EntryType , uint16_t MinSegmentSize>
Local& heap::base::Worklist< EntryType, MinSegmentSize >::Local::operator= (Local &&) [delete]
Pop()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::Local::Pop (EntryType * entry) [inline]
Definition at line 402 of file worklist.h.
                                                                   {
  if (pop_segment_->IsEmpty()) {
    if (!push_segment_->IsEmpty()) {
      std::swap(push_segment_, pop_segment_);
    } else if (!StealPopSegment()) {
      return false;
    }
  }
  pop_segment()->Pop(entry);
  return true;
}
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::MarkCompactCollector::ClearWeakReferences(), and v8::internal::Scavenger::Process().
pop_segment() [1/2]
template<typename EntryType , uint16_t MinSegmentSize>
Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Local::pop_segment () [inline], [private]
Definition at line 363 of file worklist.h.
                                {
    DCHECK_NE(internal::SegmentBase::GetSentinelSegmentAddress(), pop_segment_);
    return static_cast<Segment*>(pop_segment_);
  }
References DCHECK_NE, and heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
pop_segment() [2/2]
template<typename EntryType , uint16_t MinSegmentSize>
const Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Local::pop_segment () const [inline], [private]
Definition at line 367 of file worklist.h.
                                            {
    DCHECK_NE(internal::SegmentBase::GetSentinelSegmentAddress(), pop_segment_);
    return static_cast<const Segment*>(pop_segment_);
  }
References DCHECK_NE, and heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
Publish()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::Publish
Definition at line 430 of file worklist.h.
                                                       {
  if (!push_segment_->IsEmpty()) {
    PublishPushSegment();
    push_segment_ = internal::SegmentBase::GetSentinelSegmentAddress();
  }
  if (!pop_segment_->IsEmpty()) {
    PublishPopSegment();
    pop_segment_ = internal::SegmentBase::GetSentinelSegmentAddress();
  }
}
References heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
Referenced by v8::internal::YoungGenerationMarkingVisitor< marking_mode >::PublishWorklists().
PublishPopSegment()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::PublishPopSegment [private]
Definition at line 454 of file worklist.h.
                                                                 {
  if (pop_segment_ != internal::SegmentBase::GetSentinelSegmentAddress())
    worklist_.Push(pop_segment());
}
References heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
PublishPushSegment()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::PublishPushSegment [private]
Definition at line 448 of file worklist.h.
                                                                  {
  if (push_segment_ != internal::SegmentBase::GetSentinelSegmentAddress())
    worklist_.Push(push_segment());
}
References heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
Push()
template<typename EntryType , uint16_t MinSegmentSize>
void heap::base::Worklist< EntryType, MinSegmentSize >::Local::Push (EntryType entry) [inline]
Definition at line 393 of file worklist.h.
                                                                   {
  if (V8_UNLIKELY(push_segment_->IsFull())) {
    PublishPushSegment();
    push_segment_ = NewSegment();
  }
  push_segment()->Push(entry);
}
References V8_UNLIKELY.
Referenced by v8::internal::Scavenger::HandleLargeObject(), v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets(), v8::internal::Scavenger::PromoteObject(), and v8::internal::Scavenger::SemiSpaceCopyObject().
push_segment() [1/2]
template<typename EntryType , uint16_t MinSegmentSize>
Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Local::push_segment () [inline], [private]
Definition at line 352 of file worklist.h.
                                 {
    DCHECK_NE(internal::SegmentBase::GetSentinelSegmentAddress(),
              push_segment_);
    return static_cast<Segment*>(push_segment_);
  }
References DCHECK_NE, and heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
push_segment() [2/2]
template<typename EntryType , uint16_t MinSegmentSize>
const Segment* heap::base::Worklist< EntryType, MinSegmentSize >::Local::push_segment () const [inline], [private]
Definition at line 357 of file worklist.h.
                                             {
    DCHECK_NE(internal::SegmentBase::GetSentinelSegmentAddress(),
              push_segment_);
    return static_cast<const Segment*>(push_segment_);
  }
References DCHECK_NE, and heap::base::internal::SegmentBase::GetSentinelSegmentAddress().
PushSegmentSize()
template<typename EntryType , uint16_t MinSegmentSize>
size_t heap::base::Worklist< EntryType, MinSegmentSize >::Local::PushSegmentSize () const [inline]
Definition at line 330 of file worklist.h.
{ return push_segment_->Size(); }
Referenced by v8::internal::Scavenger::ShouldEagerlyProcessPromotedList().
StealPopSegment()
template<typename EntryType , uint16_t MinSegmentSize>
bool heap::base::Worklist< EntryType, MinSegmentSize >::Local::StealPopSegment [private]
Definition at line 460 of file worklist.h.
                                                               {
  if (worklist_.IsEmpty()) return false;
  Segment* new_segment = nullptr;
  if (worklist_.Pop(&new_segment)) {
    DeleteSegment(pop_segment_);
    pop_segment_ = new_segment;
    return true;
  }
  return false;
}
Member Data Documentation
pop_segment_
template<typename EntryType , uint16_t MinSegmentSize>
internal::SegmentBase* heap::base::Worklist< EntryType, MinSegmentSize >::Local::pop_segment_ = nullptr [private]
Definition at line 374 of file worklist.h.
push_segment_
template<typename EntryType , uint16_t MinSegmentSize>
internal::SegmentBase* heap::base::Worklist< EntryType, MinSegmentSize >::Local::push_segment_ = nullptr [private]
Definition at line 373 of file worklist.h.
worklist_
template<typename EntryType , uint16_t MinSegmentSize>
Worklist<EntryType, MinSegmentSize>& heap::base::Worklist< EntryType, MinSegmentSize >::Local::worklist_ [private]
Definition at line 372 of file worklist.h.
Referenced by heap::base::Worklist< EntryType, MinSegmentSize >::Local::Merge().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base/worklist.h