v8::internal::compiler::AtomicStoreParameters Class Reference
#include <machine-operator.h>
Public Member Functions
AtomicStoreParameters (MachineRepresentation representation, WriteBarrierKind write_barrier_kind, AtomicMemoryOrder order, MemoryAccessKind kind=MemoryAccessKind::kNormal)
MachineRepresentation representation () const
WriteBarrierKind write_barrier_kind () const
AtomicMemoryOrder order () const
MemoryAccessKind kind () const
StoreRepresentation store_representation () const
Private Attributes
StoreRepresentation store_representation_
AtomicMemoryOrder order_
MemoryAccessKind kind_
Detailed Description
Definition at line 214 of file machine-operator.h.
Constructor & Destructor Documentation
AtomicStoreParameters()
v8::internal::compiler::AtomicStoreParameters::AtomicStoreParameters (MachineRepresentation representation, WriteBarrierKind write_barrier_kind, AtomicMemoryOrder order, MemoryAccessKind kind = MemoryAccessKind::kNormal) [inline]
Definition at line 216 of file machine-operator.h.
      : store_representation_(representation, write_barrier_kind),
        order_(order), kind_(kind) {}
Member Function Documentation
kind()
MemoryAccessKind v8::internal::compiler::AtomicStoreParameters::kind () const [inline]
Definition at line 230 of file machine-operator.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore().
order()
AtomicMemoryOrder v8::internal::compiler::AtomicStoreParameters::order () const [inline]
Definition at line 229 of file machine-operator.h.
{ return order_; }
References order_.
Referenced by v8::internal::compiler::RawMachineAssembler::AtomicStore64(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
representation()
MachineRepresentation v8::internal::compiler::AtomicStoreParameters::representation () const [inline]
Definition at line 223 of file machine-operator.h.
                                               {
    return store_representation_.representation();
  }
References v8::internal::compiler::StoreRepresentation::representation(), and store_representation_.
Referenced by v8::internal::compiler::RawMachineAssembler::AtomicStore(), v8::internal::compiler::RawMachineAssembler::AtomicStore64(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore().
store_representation()
StoreRepresentation v8::internal::compiler::AtomicStoreParameters::store_representation () const [inline]
Definition at line 232 of file machine-operator.h.
                                                   {
    return store_representation_;
  }
References store_representation_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
write_barrier_kind()
WriteBarrierKind v8::internal::compiler::AtomicStoreParameters::write_barrier_kind () const [inline]
Definition at line 226 of file machine-operator.h.
                                              {
    return store_representation_.write_barrier_kind();
  }
References store_representation_, and v8::internal::compiler::StoreRepresentation::write_barrier_kind().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore().
Member Data Documentation
kind_
MemoryAccessKind v8::internal::compiler::AtomicStoreParameters::kind_ [private]
Definition at line 239 of file machine-operator.h.
Referenced by kind().
order_
AtomicMemoryOrder v8::internal::compiler::AtomicStoreParameters::order_ [private]
Definition at line 238 of file machine-operator.h.
Referenced by order().
store_representation_
StoreRepresentation v8::internal::compiler::AtomicStoreParameters::store_representation_ [private]
Definition at line 237 of file machine-operator.h.
Referenced by representation(), store_representation(), and write_barrier_kind().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator.h