v8::internal::GrowableFixedArray Class Reference
#include <growable-fixed-array-gen.h>
Public Member Functions
GrowableFixedArray (compiler::CodeAssemblerState *state)
TNode< IntPtrT > length () const
TVariable< FixedArray > * var_array ()
TVariable< IntPtrT > * var_length ()
TVariable< IntPtrT > * var_capacity ()
void Reserve (TNode< IntPtrT > required_capacity)
void Push (const TNode< Object > value)
TNode< FixedArray > ToFixedArray ()
TNode< JSArray > ToJSArray (const TNode< Context > context)
Private Member Functions
TNode< IntPtrT > NewCapacity (TNode< IntPtrT > current_capacity)
TNode< FixedArray > ResizeFixedArray (const TNode< IntPtrT > element_count, const TNode< IntPtrT > new_capacity)
Private Attributes
TVariable< FixedArray > var_array_
TVariable< IntPtrT > var_length_
TVariable< IntPtrT > var_capacity_
Additional Inherited Members
Detailed Description
Definition at line 15 of file growable-fixed-array-gen.h.
Constructor & Destructor Documentation
GrowableFixedArray()
v8::internal::GrowableFixedArray::GrowableFixedArray (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 17 of file growable-fixed-array-gen.h.
      : CodeStubAssembler(state),
        var_array_(this),
        var_length_(this),
        var_capacity_(this) {
    var_array_ = EmptyFixedArrayConstant();
    var_capacity_ = IntPtrConstant(0);
    var_length_ = IntPtrConstant(0);
  }
References v8::internal::compiler::CodeAssembler::IntPtrConstant(), var_array_, var_capacity_, and var_length_.
Member Function Documentation
length()
TNode<IntPtrT> v8::internal::GrowableFixedArray::length () const [inline]
Definition at line 27 of file growable-fixed-array-gen.h.
{ return var_length_.value(); }
References var_length_.
Referenced by Push(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), ToFixedArray(), and ToJSArray().
NewCapacity()
TNode< IntPtrT > v8::internal::GrowableFixedArray::NewCapacity (TNode< IntPtrT > current_capacity) [private]
Definition at line 98 of file growable-fixed-array-gen.cc.
                                     {
  CSA_DCHECK(this,
             IntPtrGreaterThanOrEqual(current_capacity, IntPtrConstant(0)));
  // Growth rate is analog to JSObject::NewElementsCapacity:
  // new_capacity = (current_capacity + (current_capacity >> 1)) + 16.
  const TNode<IntPtrT> new_capacity =
      IntPtrAdd(IntPtrAdd(current_capacity, WordShr(current_capacity, 1)),
                IntPtrConstant(16));
  return new_capacity;
}
References v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, and v8::internal::compiler::CodeAssembler::WordShr().
Referenced by Push(), and Reserve().
Push()
void v8::internal::GrowableFixedArray::Push (const TNode< Object > value)
Definition at line 42 of file growable-fixed-array-gen.cc.
                                                       {
  const TNode<IntPtrT> length = var_length_.value();
  const TNode<IntPtrT> capacity = var_capacity_.value();
  Label grow(this), store(this);
  Branch(IntPtrEqual(capacity, length), &grow, &store);
  BIND(&grow);
  {
    var_capacity_ = NewCapacity(capacity);
    var_array_ = ResizeFixedArray(length, var_capacity_.value());
    Goto(&store);
  }
  BIND(&store);
  {
    const TNode<FixedArray> array = var_array_.value();
    UnsafeStoreFixedArrayElement(array, length, value);
    var_length_ = IntPtrAdd(length, IntPtrConstant(1));
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), length(), NewCapacity(), ResizeFixedArray(), store(), v8::internal::CodeStubAssembler::UnsafeStoreFixedArrayElement(), v8::internal::value, var_array_, var_capacity_, and var_length_.
Referenced by v8::internal::IteratorBuiltinsAssembler::FillFixedArrayFromIterable(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), and v8::internal::IteratorBuiltinsAssembler::StringListFromIterable().
Reserve()
void v8::internal::GrowableFixedArray::Reserve (TNode< IntPtrT > required_capacity)
Definition at line 16 of file growable-fixed-array-gen.cc.
                                                                 {
  Label out(this);
  GotoIf(IntPtrGreaterThanOrEqual(var_capacity_.value(), required_capacity),
         &out);
  // Gotta grow.
  TVARIABLE(IntPtrT, var_new_capacity, var_capacity_.value());
  Label loop(this, &var_new_capacity);
  Goto(&loop);
  // First find the new capacity.
  BIND(&loop);
  {
    var_new_capacity = NewCapacity(var_new_capacity.value());
    GotoIf(IntPtrLessThan(var_new_capacity.value(), required_capacity), &loop);
  }
  // Now grow.
  var_capacity_ = var_new_capacity.value();
  var_array_ = ResizeFixedArray(var_length_.value(), var_capacity_.value());
  Goto(&out);
  BIND(&out);
}
References v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), NewCapacity(), ResizeFixedArray(), var_array_, var_capacity_, and var_length_.
Referenced by v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal().
ResizeFixedArray()
TNode< FixedArray > v8::internal::GrowableFixedArray::ResizeFixedArray (const TNode< IntPtrT > element_count, const TNode< IntPtrT > new_capacity) [private]
Definition at line 113 of file growable-fixed-array-gen.cc.
                                                                           {
  CSA_DCHECK(this, IntPtrGreaterThanOrEqual(element_count, IntPtrConstant(0)));
  CSA_DCHECK(this, IntPtrGreaterThanOrEqual(new_capacity, IntPtrConstant(0)));
  CSA_DCHECK(this, IntPtrGreaterThanOrEqual(new_capacity, element_count));
  const TNode<FixedArray> from_array = var_array_.value();
  CodeStubAssembler::ExtractFixedArrayFlags flags;
  flags |= CodeStubAssembler::ExtractFixedArrayFlag::kFixedArrays;
  TNode<FixedArray> to_array = CAST(
      ExtractFixedArray(from_array, std::optional<TNode<IntPtrT>>(std::nullopt),
                        std::optional<TNode<IntPtrT>>(element_count),
                        std::optional<TNode<IntPtrT>>(new_capacity), flags));
  return to_array;
}
References CAST, v8::internal::CodeStubAssembler::ExtractFixedArray(), v8::internal::flags, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, v8::internal::CodeStubAssembler::kFixedArrays, v8::to_array(), and var_array_.
Referenced by Push(), Reserve(), ToFixedArray(), and ToJSArray().
ToFixedArray()
TNode< FixedArray > v8::internal::GrowableFixedArray::ToFixedArray ()
Definition at line 66 of file growable-fixed-array-gen.cc.
                                                   {
  return ResizeFixedArray(length(), length());
}
References length(), and ResizeFixedArray().
Referenced by v8::internal::IteratorBuiltinsAssembler::IterableToFixedArray(), and v8::internal::IteratorBuiltinsAssembler::StringListFromIterable().
ToJSArray()
TNode< JSArray > v8::internal::GrowableFixedArray::ToJSArray (const TNode< Context > context)
Definition at line 70 of file growable-fixed-array-gen.cc.
                                                                         {
  const ElementsKind kind = PACKED_ELEMENTS;
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<Map> array_map = LoadJSArrayElementsMap(kind, native_context);
  // Shrink to fit if necessary.
  {
    Label next(this);
    const TNode<IntPtrT> length = var_length_.value();
    const TNode<IntPtrT> capacity = var_capacity_.value();
    GotoIf(WordEqual(length, capacity), &next);
    var_array_ = ResizeFixedArray(length, length);
    var_capacity_ = length;
    Goto(&next);
    BIND(&next);
  }
  const TNode<Smi> result_length = SmiTag(length());
  const TNode<JSArray> result =
      AllocateJSArray(array_map, var_array_.value(), result_length);
  return result;
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), length(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::PACKED_ELEMENTS, ResizeFixedArray(), v8::base::internal::result, v8::internal::CodeStubAssembler::SmiTag(), var_array_, var_capacity_, var_length_, and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by v8::internal::IteratorBuiltinsAssembler::IterableToList(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), and v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody().
var_array()
TVariable<FixedArray>* v8::internal::GrowableFixedArray::var_array () [inline]
Definition at line 29 of file growable-fixed-array-gen.h.
{ return &var_array_; }
References var_array_.
Referenced by v8::internal::IteratorBuiltinsAssembler::FillFixedArrayFromIterable(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), and v8::internal::IteratorBuiltinsAssembler::StringListFromIterable().
var_capacity()
TVariable<IntPtrT>* v8::internal::GrowableFixedArray::var_capacity () [inline]
Definition at line 31 of file growable-fixed-array-gen.h.
{ return &var_capacity_; }
References var_capacity_.
Referenced by v8::internal::IteratorBuiltinsAssembler::FillFixedArrayFromIterable(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), and v8::internal::IteratorBuiltinsAssembler::StringListFromIterable().
var_length()
TVariable<IntPtrT>* v8::internal::GrowableFixedArray::var_length () [inline]
Definition at line 30 of file growable-fixed-array-gen.h.
{ return &var_length_; }
References var_length_.
Referenced by v8::internal::IteratorBuiltinsAssembler::FillFixedArrayFromIterable(), v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal(), v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody(), and v8::internal::IteratorBuiltinsAssembler::StringListFromIterable().
Member Data Documentation
var_array_
TVariable<FixedArray> v8::internal::GrowableFixedArray::var_array_ [private]
Definition at line 49 of file growable-fixed-array-gen.h.
Referenced by GrowableFixedArray(), Push(), Reserve(), ResizeFixedArray(), ToJSArray(), and var_array().
var_capacity_
TVariable<IntPtrT> v8::internal::GrowableFixedArray::var_capacity_ [private]
Definition at line 51 of file growable-fixed-array-gen.h.
Referenced by GrowableFixedArray(), Push(), Reserve(), ToJSArray(), and var_capacity().
var_length_
TVariable<IntPtrT> v8::internal::GrowableFixedArray::var_length_ [private]
Definition at line 50 of file growable-fixed-array-gen.h.
Referenced by GrowableFixedArray(), length(), Push(), Reserve(), ToJSArray(), and var_length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/growable-fixed-array-gen.h
/mnt/V8SourceCode/src/builtins/growable-fixed-array-gen.cc