v8::internal::ParameterDeclarationParsingScope< Types > Class Template Reference
#include <expression-scope.h>
Public Types
using ParserT = typename Types::Impl
using ExpressionScopeT = ExpressionScope< Types >
using ScopeType = typename ExpressionScopeT::ScopeType
Public Member Functions
ParameterDeclarationParsingScope (ParserT *parser)
ParameterDeclarationParsingScope (const ParameterDeclarationParsingScope &)=delete
ParameterDeclarationParsingScope & operator= (const ParameterDeclarationParsingScope &)=delete
Variable * Declare (const AstRawString *name, int pos)
bool has_duplicate () const
const Scanner::Location & duplicate_location () const
Private Attributes
Scanner::Location duplicate_loc_ = Scanner::Location::invalid()
Additional Inherited Members
Detailed Description
template<typename Types>
class v8::internal::ParameterDeclarationParsingScope< Types >
Definition at line 425 of file expression-scope.h.
Member Typedef Documentation
ExpressionScopeT
template<typename Types >
using v8::internal::ParameterDeclarationParsingScope< Types >::ExpressionScopeT = ExpressionScope<Types>
Definition at line 428 of file expression-scope.h.
ParserT
template<typename Types >
using v8::internal::ParameterDeclarationParsingScope< Types >::ParserT = typename Types::Impl
Definition at line 427 of file expression-scope.h.
ScopeType
template<typename Types >
using v8::internal::ParameterDeclarationParsingScope< Types >::ScopeType = typename ExpressionScopeT::ScopeType
Definition at line 429 of file expression-scope.h.
Constructor & Destructor Documentation
ParameterDeclarationParsingScope() [1/2]
template<typename Types >
v8::internal::ParameterDeclarationParsingScope< Types >::ParameterDeclarationParsingScope (ParserT * parser) [inline], [explicit]
Definition at line 431 of file expression-scope.h.
      : ExpressionScopeT(parser, ExpressionScopeT::kParameterDeclaration) {}
ParameterDeclarationParsingScope() [2/2]
template<typename Types >
v8::internal::ParameterDeclarationParsingScope< Types >::ParameterDeclarationParsingScope (const ParameterDeclarationParsingScope< Types > &) [delete]
Member Function Documentation
Declare()
template<typename Types >
Variable* v8::internal::ParameterDeclarationParsingScope< Types >::Declare (const AstRawString * name, int pos) [inline]
Definition at line 439 of file expression-scope.h.
                                                       {
    VariableKind kind = PARAMETER_VARIABLE;
    VariableMode mode = VariableMode::kVar;
    bool was_added;
    Variable* var = this->parser()->DeclareVariable(
        name, kind, mode, Variable::DefaultInitializationFlag(mode),
        this->parser()->scope(), &was_added, pos);
    if (!has_duplicate() && !was_added) {
      duplicate_loc_ = Scanner::Location(pos, pos + name->length());
    }
    return var;
  }
References v8::internal::Variable::DefaultInitializationFlag(), v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_loc_, v8::internal::ParameterDeclarationParsingScope< Types >::has_duplicate(), v8::internal::kVar, mode(), v8::internal::name, v8::internal::PARAMETER_VARIABLE, and v8::internal::ExpressionScope< Types >::parser().
duplicate_location()
template<typename Types >
const Scanner::Location& v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_location () const [inline]
Definition at line 454 of file expression-scope.h.
{ return duplicate_loc_; }
References v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_loc_.
Referenced by v8::internal::Parser::DoParseFunction(), and v8::internal::Parser::ParseFunction().
has_duplicate()
template<typename Types >
bool v8::internal::ParameterDeclarationParsingScope< Types >::has_duplicate () const [inline]
Definition at line 452 of file expression-scope.h.
{ return duplicate_loc_.IsValid(); }
References v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_loc_, and v8::internal::Scanner::Location::IsValid().
Referenced by v8::internal::ParameterDeclarationParsingScope< Types >::Declare().
operator=()
template<typename Types >
ParameterDeclarationParsingScope& v8::internal::ParameterDeclarationParsingScope< Types >::operator= (const ParameterDeclarationParsingScope< Types > &) [delete]
Member Data Documentation
duplicate_loc_
template<typename Types >
Scanner::Location v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_loc_ = Scanner::Location::invalid() [private]
Definition at line 457 of file expression-scope.h.
Referenced by v8::internal::ParameterDeclarationParsingScope< Types >::Declare(), v8::internal::ParameterDeclarationParsingScope< Types >::duplicate_location(), and v8::internal::ParameterDeclarationParsingScope< Types >::has_duplicate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/expression-scope.h