v8::internal::ParseInfo Class Reference
#include <parse-info.h>
Public Member Functions
ParseInfo (Isolate *isolate, const UnoptimizedCompileFlags flags, UnoptimizedCompileState *state, ReusableUnoptimizedCompileState *reusable_state)
ParseInfo (LocalIsolate *isolate, const UnoptimizedCompileFlags flags, UnoptimizedCompileState *state, ReusableUnoptimizedCompileState *reusable_state, uintptr_t stack_limit)
~ParseInfo ()
template<typename IsolateT >
Handle< Script > CreateScript (IsolateT *isolate, DirectHandle< String > source, MaybeDirectHandle< FixedArray > maybe_wrapped_arguments, ScriptOriginOptions origin_options, NativesFlag natives=NOT_NATIVES_CODE)
Zone * zone () const
const UnoptimizedCompileFlags & flags () const
uint64_t hash_seed () const
AccountingAllocator * allocator () const
const AstStringConstants * ast_string_constants () const
V8FileLogger * v8_file_logger () const
LazyCompileDispatcher * dispatcher () const
const UnoptimizedCompileState * state () const
PendingCompilationErrorHandler * pending_error_handler ()
uintptr_t stack_limit () const
RuntimeCallStats * runtime_call_stats () const
bool allow_eval_cache () const
void set_allow_eval_cache (bool value)
LanguageMode language_mode () const
void set_language_mode (LanguageMode value)
Utf16CharacterStream * character_stream () const
void set_character_stream (std::unique_ptr< Utf16CharacterStream > character_stream)
void ResetCharacterStream ()
v8::Extension * extension () const
void set_extension (v8::Extension *extension)
void set_consumed_preparse_data (std::unique_ptr< ConsumedPreparseData > data)
ConsumedPreparseData * consumed_preparse_data ()
DeclarationScope * script_scope () const
void set_script_scope (DeclarationScope *script_scope)
AstValueFactory * ast_value_factory () const
const AstRawString * function_name () const
void set_function_name (const AstRawString *function_name)
FunctionLiteral * literal () const
void set_literal (FunctionLiteral *literal)
DeclarationScope * scope () const
int parameters_end_pos () const
void set_parameters_end_pos (int parameters_end_pos)
bool is_wrapped_as_function () const
int max_info_id () const
void set_max_info_id (int max_info_id)
void AllocateSourceRangeMap ()
SourceRangeMap * source_range_map () const
void set_source_range_map (SourceRangeMap *source_range_map)
void CheckFlagsForFunctionFromScript (Tagged< Script > script)
bool is_background_compilation () const
void set_is_background_compilation ()
bool is_streaming_compilation () const
void set_is_streaming_compilation ()
bool has_module_in_scope_chain () const
void set_has_module_in_scope_chain ()
void SetCompileHintCallbackAndData (CompileHintCallback callback, void *data)
CompileHintCallback compile_hint_callback () const
void * compile_hint_callback_data () const
Private Member Functions
ParseInfo (const UnoptimizedCompileFlags flags, UnoptimizedCompileState *state, ReusableUnoptimizedCompileState *reusable_state, uintptr_t stack_limit, RuntimeCallStats *runtime_call_stats)
void CheckFlagsForToplevelCompileFromScript (Tagged< Script > script)
Private Attributes
const UnoptimizedCompileFlags flags_
UnoptimizedCompileState * state_
ReusableUnoptimizedCompileState * reusable_state_
v8::Extension * extension_
DeclarationScope * script_scope_
uintptr_t stack_limit_
int parameters_end_pos_
int max_info_id_
v8::CompileHintCallback compile_hint_callback_ = nullptr
void * compile_hint_callback_data_ = nullptr
std::unique_ptr< Utf16CharacterStream > character_stream_
std::unique_ptr< ConsumedPreparseData > consumed_preparse_data_
const AstRawString * function_name_
RuntimeCallStats * runtime_call_stats_
SourceRangeMap * source_range_map_
FunctionLiteral * literal_
bool allow_eval_cache_: 1
LanguageMode language_mode_: 1
bool is_background_compilation_: 1
bool is_streaming_compilation_: 1
bool has_module_in_scope_chain_: 1
Detailed Description
Definition at line 227 of file parse-info.h.
Constructor & Destructor Documentation
ParseInfo() [1/3]
v8::internal::ParseInfo::ParseInfo (Isolate * isolate, const UnoptimizedCompileFlags flags, UnoptimizedCompileState * state, ReusableUnoptimizedCompileState * reusable_state)
Definition at line 220 of file parse-info.cc.
    : ParseInfo(flags, state, reusable_state,
                isolate->stack_guard()->real_climit(),
                isolate->counters()->runtime_call_stats()) {}
ParseInfo() [2/3]
v8::internal::ParseInfo::ParseInfo (LocalIsolate * isolate, const UnoptimizedCompileFlags flags, UnoptimizedCompileState * state, ReusableUnoptimizedCompileState * reusable_state, uintptr_t stack_limit)
Definition at line 227 of file parse-info.cc.
    : ParseInfo(flags, state, reusable_state, stack_limit,
                isolate->runtime_call_stats()) {}
 ParseInfo()
v8::internal::ParseInfo::~ParseInfo ()
Definition at line 234 of file parse-info.cc.
{ reusable_state_->NotifySingleParseCompleted(); }
References v8::internal::ReusableUnoptimizedCompileState::NotifySingleParseCompleted(), and reusable_state_.
ParseInfo() [3/3]
v8::internal::ParseInfo::ParseInfo (const UnoptimizedCompileFlags flags, UnoptimizedCompileState * state, ReusableUnoptimizedCompileState * reusable_state, uintptr_t stack_limit, RuntimeCallStats * runtime_call_stats) [private]
Definition at line 189 of file parse-info.cc.
    : flags_(flags),
      state_(state),
      reusable_state_(reusable_state),
      extension_(nullptr),
      script_scope_(nullptr),
      stack_limit_(stack_limit),
      parameters_end_pos_(kNoSourcePosition),
      max_info_id_(kInvalidInfoId),
      character_stream_(nullptr),
      function_name_(nullptr),
      runtime_call_stats_(runtime_call_stats),
      source_range_map_(nullptr),
      literal_(nullptr),
      allow_eval_cache_(false),
#if V8_ENABLE_WEBASSEMBLY
      contains_asm_module_(false),
#endif // V8_ENABLE_WEBASSEMBLY
      language_mode_(flags.outer_language_mode()),
      is_background_compilation_(false),
      is_streaming_compilation_(false),
      has_module_in_scope_chain_(flags.is_module()) {
  if (flags.block_coverage_enabled()) {
    AllocateSourceRangeMap();
  }
}
References AllocateSourceRangeMap(), and flags().
Member Function Documentation
AllocateSourceRangeMap()
void v8::internal::ParseInfo::AllocateSourceRangeMap ()
Referenced by ParseInfo().
allocator()
AccountingAllocator* v8::internal::ParseInfo::allocator () const [inline]
Definition at line 253 of file parse-info.h.
                                         {
    return reusable_state_->allocator();
  }
allow_eval_cache()
bool v8::internal::ParseInfo::allow_eval_cache () const [inline]
Definition at line 277 of file parse-info.h.
{ return allow_eval_cache_; }
Referenced by v8::internal::Compiler::GetFunctionFromEval().
ast_string_constants()
const AstStringConstants* v8::internal::ParseInfo::ast_string_constants () const [inline]
Definition at line 256 of file parse-info.h.
                                                         {
    return reusable_state_->ast_string_constants();
  }
ast_value_factory()
AstValueFactory* v8::internal::ParseInfo::ast_value_factory () const [inline]
Definition at line 310 of file parse-info.h.
                                             {
    return reusable_state_->ast_value_factory();
  }
Referenced by v8::internal::DeclarationScope::Analyze(), v8::internal::Parser::DoParseProgram(), v8::Shell::ExecuteString(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8::internal::Parser::PostProcessParseResult(), v8::internal::anonymous_namespace{compiler.cc}::PrepareException(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::Rewriter::RewriteBody(), v8::internal::BackgroundCompileTask::Run(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
character_stream()
Utf16CharacterStream* v8::internal::ParseInfo::character_stream () const [inline]
Definition at line 288 of file parse-info.h.
                                                 {
    return character_stream_.get();
  }
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::Parser::Parser(), v8::internal::BackgroundCompileTask::Run(), and set_character_stream().
CheckFlagsForFunctionFromScript()
void v8::internal::ParseInfo::CheckFlagsForFunctionFromScript (Tagged< Script > script)
Definition at line 318 of file parse-info.cc.
                                                                     {
  DCHECK_EQ(flags().script_id(), script->id());
  // We set "is_eval" for wrapped scripts to get an outer declaration scope.
  // This is a bit hacky, but ok since we can't be both eval and wrapped.
  DCHECK_EQ(flags().is_eval() && !script->is_wrapped(),
            script->compilation_type() == Script::CompilationType::kEval);
  DCHECK_EQ(flags().is_module(), script->origin_options().IsModule());
  DCHECK_IMPLIES(flags().block_coverage_enabled() && script->IsUserJavaScript(),
                 source_range_map() != nullptr);
}
References DCHECK_EQ, DCHECK_IMPLIES, flags(), v8::internal::Script::kEval, v8::internal::script, and source_range_map().
Referenced by CheckFlagsForToplevelCompileFromScript(), and v8::internal::BackgroundCompileTask::Run().
CheckFlagsForToplevelCompileFromScript()
void v8::internal::ParseInfo::CheckFlagsForToplevelCompileFromScript (Tagged< Script > script) [private]
Definition at line 308 of file parse-info.cc.
                                                                            {
  CheckFlagsForFunctionFromScript(script);
  DCHECK(flags().is_toplevel());
  DCHECK_EQ(flags().is_repl_mode(), script->is_repl_mode());
  if (script->is_wrapped()) {
    DCHECK_EQ(flags().function_syntax_kind(), FunctionSyntaxKind::kWrapped);
  }
}
References CheckFlagsForFunctionFromScript(), v8::internal::DCHECK(), DCHECK_EQ, flags(), v8::internal::kWrapped, and v8::internal::script.
Referenced by CreateScript().
compile_hint_callback()
CompileHintCallback v8::internal::ParseInfo::compile_hint_callback () const [inline]
Definition at line 362 of file parse-info.h.
                                                    {
    return compile_hint_callback_;
  }
compile_hint_callback_data()
void* v8::internal::ParseInfo::compile_hint_callback_data () const [inline]
Definition at line 366 of file parse-info.h.
                                           {
    return compile_hint_callback_data_;
  }
consumed_preparse_data()
ConsumedPreparseData* v8::internal::ParseInfo::consumed_preparse_data () [inline]
Definition at line 301 of file parse-info.h.
                                                 {
    return consumed_preparse_data_.get();
  }
Referenced by v8::internal::DeclarationScope::Analyze().
CreateScript()
template<typename IsolateT >
Handle< Script > v8::internal::ParseInfo::CreateScript (IsolateT * isolate, DirectHandle< String > source, MaybeDirectHandle< FixedArray > maybe_wrapped_arguments, ScriptOriginOptions origin_options, NativesFlag natives = NOT_NATIVES_CODE)
Definition at line 239 of file parse-info.cc.
                                                             {
  // Create a script object describing the script to be compiled.
  DCHECK(flags().script_id() >= 0 ||
         flags().script_id() == Script::kTemporaryScriptId);
  auto event = ScriptEventType::kCreate;
  if (is_streaming_compilation()) {
    event = is_background_compilation()
                ? ScriptEventType::kStreamingCompileBackground
                : ScriptEventType::kStreamingCompileForeground;
  } else if (is_background_compilation()) {
    event = ScriptEventType::kBackgroundCompile;
  }
  Handle<Script> script =
      isolate->factory()->NewScriptWithId(source, flags().script_id(), event);
  DisallowGarbageCollection no_gc;
  Tagged<Script> raw_script = *script;
  switch (natives) {
    case EXTENSION_CODE:
      raw_script->set_type(Script::Type::kExtension);
      break;
    case INSPECTOR_CODE:
      raw_script->set_type(Script::Type::kInspector);
      break;
    case NOT_NATIVES_CODE:
      break;
  }
  raw_script->set_origin_options(origin_options);
  raw_script->set_is_repl_mode(flags().is_repl_mode());
  DCHECK_EQ(is_wrapped_as_function(), !maybe_wrapped_arguments.is_null());
  if (is_wrapped_as_function()) {
    raw_script->set_wrapped_arguments(
        *maybe_wrapped_arguments.ToHandleChecked());
  } else if (flags().is_eval()) {
    raw_script->set_compilation_type(Script::CompilationType::kEval);
  }
  CheckFlagsForToplevelCompileFromScript(raw_script);
  return script;
}
References CheckFlagsForToplevelCompileFromScript(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::EXTENSION_CODE, flags(), v8::internal::INSPECTOR_CODE, is_background_compilation(), v8::internal::MaybeDirectHandle< T >::is_null(), is_streaming_compilation(), is_wrapped_as_function(), v8::internal::kBackgroundCompile, v8::internal::kCreate, v8::internal::Script::kEval, v8::internal::Script::kExtension, v8::internal::Script::kInspector, v8::internal::kStreamingCompileBackground, v8::internal::kStreamingCompileForeground, v8::internal::Script::kTemporaryScriptId, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NOT_NATIVES_CODE, v8::internal::script, and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::Shell::ExecuteString(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::anonymous_namespace{compiler.cc}::NewScript(), and v8::internal::BackgroundCompileTask::Run().
dispatcher()
LazyCompileDispatcher* v8::internal::ParseInfo::dispatcher () const [inline]
Definition at line 262 of file parse-info.h.
                                            {
    return reusable_state_->dispatcher();
  }
Referenced by v8::internal::Parser::ParseFunctionLiteral().
extension()
v8::Extension* v8::internal::ParseInfo::extension () const [inline]
Definition at line 295 of file parse-info.h.
{ return extension_; }
Referenced by v8::internal::Parser::Parser().
flags()
const UnoptimizedCompileFlags& v8::internal::ParseInfo::flags () const [inline]
Definition at line 249 of file parse-info.h.
{ return flags_; }
Referenced by CheckFlagsForFunctionFromScript(), CheckFlagsForToplevelCompileFromScript(), v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnMainThread(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), CreateScript(), v8::internal::anonymous_namespace{compiler.cc}::EnsureInfosArrayOnScript(), v8::internal::anonymous_namespace{compiler.cc}::ExecuteSingleUnoptimizedCompilationJob(), v8::internal::parsing::ParseAny(), v8::internal::parsing::ParseFunction(), v8::internal::Parser::ParseFunctionLiteral(), ParseInfo(), v8::internal::parsing::ParseProgram(), v8::internal::Parser::PostProcessParseResult(), v8::internal::ClassScope::ResolvePrivateNames(), v8::internal::Rewriter::RewriteBody(), and v8::internal::BackgroundCompileTask::Run().
function_name()
const AstRawString* v8::internal::ParseInfo::function_name () const [inline]
Definition at line 314 of file parse-info.h.
{ return function_name_; }
Referenced by v8::internal::Parser::ParseFunction(), and v8::internal::Parser::ParseOnBackground().
has_module_in_scope_chain()
bool v8::internal::ParseInfo::has_module_in_scope_chain () const [inline]
Definition at line 352 of file parse-info.h.
{ return has_module_in_scope_chain_; }
Referenced by v8::internal::Parser::DeserializeScopeChain().
hash_seed()
uint64_t v8::internal::ParseInfo::hash_seed () const [inline]
Definition at line 252 of file parse-info.h.
{ return reusable_state_->hash_seed(); }
is_background_compilation()
bool v8::internal::ParseInfo::is_background_compilation () const [inline]
Definition at line 344 of file parse-info.h.
{ return is_background_compilation_; }
Referenced by CreateScript().
is_streaming_compilation()
bool v8::internal::ParseInfo::is_streaming_compilation () const [inline]
Definition at line 348 of file parse-info.h.
{ return is_streaming_compilation_; }
Referenced by CreateScript().
is_wrapped_as_function()
bool v8::internal::ParseInfo::is_wrapped_as_function () const [inline]
Definition at line 329 of file parse-info.h.
                                      {
    return flags().function_syntax_kind() == FunctionSyntaxKind::kWrapped;
  }
References v8::internal::flags, and v8::internal::kWrapped.
Referenced by CreateScript(), v8::internal::Parser::DoParseFunction(), v8::internal::Parser::DoParseProgram(), v8::internal::Parser::ParseProgram(), and v8::internal::Parser::ParseWrapped().
language_mode()
LanguageMode v8::internal::ParseInfo::language_mode () const [inline]
Definition at line 285 of file parse-info.h.
{ return language_mode_; }
Referenced by v8::internal::Parser::DoParseFunction(), v8::internal::Parser::DoParseProgram(), and v8::internal::Parser::ParseREPLProgram().
literal()
FunctionLiteral* v8::internal::ParseInfo::literal () const [inline]
Definition at line 319 of file parse-info.h.
{ return literal_; }
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::DeclarationScope::Analyze(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::Compile(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::anonymous_namespace{compiler.cc}::CreateTopLevelSharedFunctionInfo(), v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCreateTopLevelSharedFunctionInfo(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::parsing::ParseFunction(), v8::internal::Parser::ParseOnBackground(), v8::internal::parsing::ParseProgram(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::Rewriter::Rewrite(), v8::internal::BackgroundCompileTask::Run(), scope(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), and v8::internal::ErrorUtils::ThrowSpreadArgError().
max_info_id()
int v8::internal::ParseInfo::max_info_id () const [inline]
Definition at line 333 of file parse-info.h.
{ return max_info_id_; }
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), and v8::internal::anonymous_namespace{compiler.cc}::EnsureInfosArrayOnScript().
parameters_end_pos()
int v8::internal::ParseInfo::parameters_end_pos () const [inline]
Definition at line 324 of file parse-info.h.
{ return parameters_end_pos_; }
pending_error_handler()
PendingCompilationErrorHandler* v8::internal::ParseInfo::pending_error_handler () [inline]
Definition at line 268 of file parse-info.h.
                                                          {
    return state_->pending_error_handler();
  }
Referenced by v8::internal::DeclarationScope::AllocateVariables(), v8::Shell::ExecuteString(), v8::internal::anonymous_namespace{compiler.cc}::FailWithException(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::Parser::ParseREPLProgram(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8::internal::anonymous_namespace{compiler.cc}::PrepareException(), v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationFailure(), and v8::internal::ClassScope::ResolvePrivateNames().
ResetCharacterStream()
void v8::internal::ParseInfo::ResetCharacterStream ()
Definition at line 300 of file parse-info.cc.
{ character_stream_.reset(); }
References character_stream_.
Referenced by v8::internal::Compiler::CollectSourcePositions(), and v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel().
runtime_call_stats()
RuntimeCallStats* v8::internal::ParseInfo::runtime_call_stats () const [inline]
Definition at line 274 of file parse-info.h.
{ return runtime_call_stats_; }
Referenced by v8::internal::DeclarationScope::Analyze(), v8::internal::Parser::PostProcessParseResult(), v8::internal::Rewriter::Rewrite(), and v8::internal::BackgroundCompileTask::Run().
scope()
DeclarationScope * v8::internal::ParseInfo::scope () const
Definition at line 236 of file parse-info.cc.
{ return literal()->scope(); }
References literal(), and v8::internal::FunctionLiteral::scope().
Referenced by v8::internal::DeclarationScope::AllocateVariables().
script_scope()
DeclarationScope* v8::internal::ParseInfo::script_scope () const [inline]
Definition at line 305 of file parse-info.h.
{ return script_scope_; }
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::Parser::DeserializeScopeChain(), v8::internal::Parser::DoParseProgram(), and v8::internal::Parser::InitializeEmptyScopeChain().
set_allow_eval_cache()
void v8::internal::ParseInfo::set_allow_eval_cache (bool value) [inline]
Definition at line 278 of file parse-info.h.
{ allow_eval_cache_ = value; }
References v8::internal::value.
Referenced by v8::internal::Parser::PostProcessParseResult().
set_character_stream()
void v8::internal::ParseInfo::set_character_stream (std::unique_ptr< Utf16CharacterStream > character_stream)
Definition at line 302 of file parse-info.cc.
                                                          {
  DCHECK_NULL(character_stream_);
  character_stream_.swap(character_stream);
}
References character_stream(), character_stream_, and DCHECK_NULL.
Referenced by v8::internal::parsing::ParseFunction(), v8::internal::parsing::ParseProgram(), and v8::internal::BackgroundCompileTask::Run().
set_consumed_preparse_data()
void v8::internal::ParseInfo::set_consumed_preparse_data (std::unique_ptr< ConsumedPreparseData > data) [inline]
Definition at line 298 of file parse-info.h.
                                                                            {
    consumed_preparse_data_.swap(data);
  }
Referenced by v8::internal::Compiler::Compile(), and v8::internal::BackgroundCompileTask::Run().
set_extension()
void v8::internal::ParseInfo::set_extension (v8::Extension * extension) [inline]
Definition at line 296 of file parse-info.h.
{ extension_ = extension; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnMainThread().
set_function_name()
void v8::internal::ParseInfo::set_function_name (const AstRawString * function_name) [inline]
Definition at line 315 of file parse-info.h.
                                                            {
    function_name_ = function_name;
  }
Referenced by v8::internal::Parser::ParseFunction(), and v8::internal::BackgroundCompileTask::Run().
set_has_module_in_scope_chain()
void v8::internal::ParseInfo::set_has_module_in_scope_chain () [inline]
Definition at line 353 of file parse-info.h.
{ has_module_in_scope_chain_ = true; }
Referenced by v8::internal::Scope::DeserializeScopeChain().
set_is_background_compilation()
void v8::internal::ParseInfo::set_is_background_compilation () [inline]
Definition at line 346 of file parse-info.h.
{ is_background_compilation_ = true; }
set_is_streaming_compilation()
void v8::internal::ParseInfo::set_is_streaming_compilation () [inline]
Definition at line 350 of file parse-info.h.
{ is_streaming_compilation_ = true; }
Referenced by v8::internal::BackgroundCompileTask::Run().
set_language_mode()
void v8::internal::ParseInfo::set_language_mode (LanguageMode value) [inline]
Definition at line 286 of file parse-info.h.
{ language_mode_ = value; }
References v8::internal::value.
Referenced by v8::internal::Parser::PostProcessParseResult().
set_literal()
void v8::internal::ParseInfo::set_literal (FunctionLiteral * literal) [inline]
Definition at line 320 of file parse-info.h.
{ literal_ = literal; }
Referenced by v8::internal::Parser::PostProcessParseResult().
set_max_info_id()
void v8::internal::ParseInfo::set_max_info_id (int max_info_id) [inline]
Definition at line 334 of file parse-info.h.
{ max_info_id_ = max_info_id; }
Referenced by v8::internal::Parser::DoParseFunction(), v8::internal::Parser::DoParseProgram(), and v8::internal::Parser::ParseFunction().
set_parameters_end_pos()
void v8::internal::ParseInfo::set_parameters_end_pos (int parameters_end_pos) [inline]
Definition at line 325 of file parse-info.h.
                                                      {
    parameters_end_pos_ = parameters_end_pos;
  }
Referenced by v8::internal::Compiler::GetFunctionFromEval().
set_script_scope()
void v8::internal::ParseInfo::set_script_scope (DeclarationScope * script_scope) [inline]
Definition at line 306 of file parse-info.h.
                                                        {
    script_scope_ = script_scope;
  }
Referenced by v8::internal::Parser::InitializeEmptyScopeChain().
set_source_range_map()
void v8::internal::ParseInfo::set_source_range_map (SourceRangeMap * source_range_map) [inline]
Definition at line 338 of file parse-info.h.
                                                              {
    source_range_map_ = source_range_map;
  }
SetCompileHintCallbackAndData()
void v8::internal::ParseInfo::SetCompileHintCallbackAndData (CompileHintCallback callback, void * data) [inline]
Definition at line 355 of file parse-info.h.
                                                                               {
    DCHECK_NULL(compile_hint_callback_);
    DCHECK_NULL(compile_hint_callback_data_);
    compile_hint_callback_ = callback;
    compile_hint_callback_data_ = data;
  }
References DCHECK_NULL.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnMainThread(), and v8::internal::BackgroundCompileTask::Run().
source_range_map()
SourceRangeMap* v8::internal::ParseInfo::source_range_map () const [inline]
Definition at line 337 of file parse-info.h.
{ return source_range_map_; }
Referenced by CheckFlagsForFunctionFromScript(), v8::internal::anonymous_namespace{parser.cc}::MaybeProcessSourceRanges(), and v8::internal::UnoptimizedCompilationInfo::UnoptimizedCompilationInfo().
stack_limit()
uintptr_t v8::internal::ParseInfo::stack_limit () const [inline]
Definition at line 273 of file parse-info.h.
{ return stack_limit_; }
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter.cc}::MaybePrintAst(), and v8::internal::Rewriter::RewriteBody().
state()
const UnoptimizedCompileState* v8::internal::ParseInfo::state () const [inline]
Definition at line 265 of file parse-info.h.
{ return state_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel().
v8_file_logger()
V8FileLogger* v8::internal::ParseInfo::v8_file_logger () const [inline]
Definition at line 259 of file parse-info.h.
                                       {
    return reusable_state_->v8_file_logger();
  }
zone()
Zone* v8::internal::ParseInfo::zone () const [inline]
Definition at line 247 of file parse-info.h.
{ return reusable_state_->single_parse_zone(); }
Referenced by v8::internal::DeclarationScope::Analyze(), v8::internal::Parser::ParseFunction(), and v8::internal::Rewriter::RewriteBody().
Member Data Documentation
allow_eval_cache_
bool v8::internal::ParseInfo::allow_eval_cache_ [private]
Definition at line 400 of file parse-info.h.
character_stream_
std::unique_ptr<Utf16CharacterStream> v8::internal::ParseInfo::character_stream_ [private]
Definition at line 392 of file parse-info.h.
Referenced by ResetCharacterStream(), and set_character_stream().
compile_hint_callback_
v8::CompileHintCallback v8::internal::ParseInfo::compile_hint_callback_ = nullptr [private]
Definition at line 388 of file parse-info.h.
compile_hint_callback_data_
void* v8::internal::ParseInfo::compile_hint_callback_data_ = nullptr [private]
Definition at line 389 of file parse-info.h.
consumed_preparse_data_
std::unique_ptr<ConsumedPreparseData> v8::internal::ParseInfo::consumed_preparse_data_ [private]
Definition at line 393 of file parse-info.h.
extension_
v8::Extension* v8::internal::ParseInfo::extension_ [private]
Definition at line 382 of file parse-info.h.
flags_
const UnoptimizedCompileFlags v8::internal::ParseInfo::flags_ [private]
Definition at line 378 of file parse-info.h.
function_name_
const AstRawString* v8::internal::ParseInfo::function_name_ [private]
Definition at line 394 of file parse-info.h.
has_module_in_scope_chain_
bool v8::internal::ParseInfo::has_module_in_scope_chain_ [private]
Definition at line 407 of file parse-info.h.
is_background_compilation_
bool v8::internal::ParseInfo::is_background_compilation_ [private]
Definition at line 405 of file parse-info.h.
is_streaming_compilation_
bool v8::internal::ParseInfo::is_streaming_compilation_ [private]
Definition at line 406 of file parse-info.h.
language_mode_
LanguageMode v8::internal::ParseInfo::language_mode_ [private]
Definition at line 404 of file parse-info.h.
literal_
FunctionLiteral* v8::internal::ParseInfo::literal_ [private]
Definition at line 399 of file parse-info.h.
max_info_id_
int v8::internal::ParseInfo::max_info_id_ [private]
Definition at line 386 of file parse-info.h.
parameters_end_pos_
int v8::internal::ParseInfo::parameters_end_pos_ [private]
Definition at line 385 of file parse-info.h.
reusable_state_
ReusableUnoptimizedCompileState* v8::internal::ParseInfo::reusable_state_ [private]
Definition at line 380 of file parse-info.h.
Referenced by ~ParseInfo().
runtime_call_stats_
RuntimeCallStats* v8::internal::ParseInfo::runtime_call_stats_ [private]
Definition at line 395 of file parse-info.h.
script_scope_
DeclarationScope* v8::internal::ParseInfo::script_scope_ [private]
Definition at line 383 of file parse-info.h.
source_range_map_
SourceRangeMap* v8::internal::ParseInfo::source_range_map_ [private]
Definition at line 396 of file parse-info.h.
stack_limit_
uintptr_t v8::internal::ParseInfo::stack_limit_ [private]
Definition at line 384 of file parse-info.h.
state_
UnoptimizedCompileState* v8::internal::ParseInfo::state_ [private]
Definition at line 379 of file parse-info.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/parse-info.h
/mnt/V8SourceCode/src/parsing/parse-info.cc