v8::internal::compiler::ArmOperandGenerator Class Reference
Public Member Functions
ArmOperandGenerator (InstructionSelector *selector)
bool CanBeImmediate (int32_t value) const
bool CanBeImmediate (uint32_t value) const
bool CanBeImmediate (OpIndex node, InstructionCode opcode)
Additional Inherited Members
Detailed Description
Definition at line 25 of file instruction-selector-arm.cc.
Constructor & Destructor Documentation
ArmOperandGenerator()
v8::internal::compiler::ArmOperandGenerator::ArmOperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 27 of file instruction-selector-arm.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeImmediate() [1/3]
bool v8::internal::compiler::ArmOperandGenerator::CanBeImmediate (int32_t value) const [inline]
Definition at line 30 of file instruction-selector-arm.cc.
                                           {
    return internal::Assembler::ImmediateFitsAddrMode1Instruction(value);
  }
References v8::internal::Assembler::ImmediateFitsAddrMode1Instruction(), and v8::internal::value.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchImmediateOrShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon().
CanBeImmediate() [2/3]
bool v8::internal::compiler::ArmOperandGenerator::CanBeImmediate (OpIndex node, InstructionCode opcode) [inline]
Definition at line 38 of file instruction-selector-arm.cc.
                                                            {
    int64_t value64;
    if (!selector()->MatchSignedIntegralConstant(node, &value64)) return false;
    DCHECK(base::IsInRange(value64, std::numeric_limits<int32_t>::min(),
                           std::numeric_limits<int32_t>::max()));
    int32_t value = static_cast<int32_t>(value64);
    switch (ArchOpcodeField::decode(opcode)) {
      case kArmAnd:
      case kArmMov:
      case kArmMvn:
      case kArmBic:
        return CanBeImmediate(value) || CanBeImmediate(~value);
      case kArmAdd:
      case kArmSub:
      case kArmCmp:
      case kArmCmn:
        return CanBeImmediate(value) || CanBeImmediate(-value);
      case kArmTst:
      case kArmTeq:
      case kArmOrr:
      case kArmEor:
      case kArmRsb:
        return CanBeImmediate(value);
      case kArmVldrF32:
      case kArmVstrF32:
      case kArmVldrF64:
      case kArmVstrF64:
        return value >= -1020 && value <= 1020 && (value % 4) == 0;
      case kArmLdrb:
      case kArmLdrsb:
      case kArmStrb:
      case kArmLdr:
      case kArmStr:
        return value >= -4095 && value <= 4095;
      case kArmLdrh:
      case kArmLdrsh:
      case kArmStrh:
        return value >= -255 && value <= 255;
      default:
        break;
    }
    return false;
  }
References v8::internal::compiler::CanBeImmediate(), v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::value.
CanBeImmediate() [3/3]
bool v8::internal::compiler::ArmOperandGenerator::CanBeImmediate (uint32_t value) const [inline]
Definition at line 34 of file instruction-selector-arm.cc.
                                            {
    return CanBeImmediate(base::bit_cast<int32_t>(value));
  }
References v8::internal::compiler::CanBeImmediate(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm/instruction-selector-arm.cc