v8::internal::DefineKeyedOwnDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned(), MachineType::TaggedSigned()) static const expr inline Register FlagsRegister()
Static Public Member Functions
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1292 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::DefineKeyedOwnDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned() , MachineType::TaggedSigned()) const
registers()
constexpr auto v8::internal::DefineKeyedOwnDescriptor::registers () [static], [constexpr]
Definition at line 445 of file interface-descriptors-inl.h.
                                                   {
  return RegisterArray(StoreDescriptor::ReceiverRegister(),
                       StoreDescriptor::NameRegister(),
                       StoreDescriptor::ValueRegister(),
                       DefineKeyedOwnDescriptor::FlagsRegister(),
                       StoreDescriptor::SlotRegister());
}
References v8::internal::StoreDescriptor::NameRegister(), v8::internal::RegisterArray(), v8::internal::StoreDescriptor::SlotRegister(), and v8::internal::StoreDescriptor::ValueRegister().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h