v8::internal::maglev::MaybeGrowFastElements Class Reference
#include <maglev-ir.h>
Public Member Functions
MaybeGrowFastElements (uint64_t bitfield, ElementsKind elements_kind)
Input & elements_input ()
Input & object_input ()
Input & index_input ()
Input & elements_length_input ()
ElementsKind elements_kind () const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kElementsIndex = 0
static constexpr int kObjectIndex = 1
static constexpr int kIndexIndex = 2
static constexpr int kElementsLengthIndex = 3
Private Types
using Base = FixedInputValueNodeT< 4, MaybeGrowFastElements >
Private Attributes
const ElementsKind elements_kind_
Additional Inherited Members
Detailed Description
Definition at line 8392 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::MaybeGrowFastElements::Base = FixedInputValueNodeT<4, MaybeGrowFastElements> [private]
Definition at line 8394 of file maglev-ir.h.
Constructor & Destructor Documentation
MaybeGrowFastElements()
v8::internal::maglev::MaybeGrowFastElements::MaybeGrowFastElements (uint64_t bitfield, ElementsKind elements_kind) [inline], [explicit]
Definition at line 8397 of file maglev-ir.h.
      : Base(bitfield), elements_kind_(elements_kind) {}
Member Function Documentation
elements_input()
Input& v8::internal::maglev::MaybeGrowFastElements::elements_input () [inline]
Definition at line 8411 of file maglev-ir.h.
{ return input(kElementsIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
elements_kind()
ElementsKind v8::internal::maglev::MaybeGrowFastElements::elements_kind () const [inline]
Definition at line 8416 of file maglev-ir.h.
{ return elements_kind_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
elements_length_input()
Input& v8::internal::maglev::MaybeGrowFastElements::elements_length_input () [inline]
Definition at line 8414 of file maglev-ir.h.
{ return input(kElementsLengthIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::MaybeGrowFastElements::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::MaybeGrowFastElements::index_input () [inline]
Definition at line 8413 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::MaybeGrowFastElements::MaxCallStackArgs () const [inline]
Definition at line 8418 of file maglev-ir.h.
{ return 0; }
object_input()
Input& v8::internal::maglev::MaybeGrowFastElements::object_input () [inline]
Definition at line 8412 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::MaybeGrowFastElements::options () const [inline]
Definition at line 8423 of file maglev-ir.h.
{ return std::tuple{elements_kind()}; }
PrintParams()
void v8::internal::maglev::MaybeGrowFastElements::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 8421 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::MaybeGrowFastElements::SetValueLocationConstraints ()
Member Data Documentation
elements_kind_
const ElementsKind v8::internal::maglev::MaybeGrowFastElements::elements_kind_ [private]
Definition at line 8426 of file maglev-ir.h.
kElementsIndex
constexpr int v8::internal::maglev::MaybeGrowFastElements::kElementsIndex = 0 [static], [constexpr]
Definition at line 8407 of file maglev-ir.h.
kElementsLengthIndex
constexpr int v8::internal::maglev::MaybeGrowFastElements::kElementsLengthIndex = 3 [static], [constexpr]
Definition at line 8410 of file maglev-ir.h.
kIndexIndex
constexpr int v8::internal::maglev::MaybeGrowFastElements::kIndexIndex = 2 [static], [constexpr]
Definition at line 8409 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::MaybeGrowFastElements::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kInt32, ValueRepresentation::kInt32}
Definition at line 8403 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::MaybeGrowFastElements::kObjectIndex = 1 [static], [constexpr]
Definition at line 8408 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::MaybeGrowFastElements::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanAllocate() | OpProperties::DeferredCall() |
      OpProperties::CanWrite() | OpProperties::EagerDeopt()
Definition at line 8400 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h