v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::FunctionContextSpecialization Class Reference
Static Public Member Functions
static compiler::OptionalContextRef TryToRef (const MaglevCompilationUnit *unit, ValueNode *context, size_t *depth)
Detailed Description
Definition at line 130 of file maglev-graph-builder.cc.
Member Function Documentation
TryToRef()
static compiler::OptionalContextRef v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::FunctionContextSpecialization::TryToRef (const MaglevCompilationUnit * unit, ValueNode * context, size_t * depth) [inline], [static]
Definition at line 132 of file maglev-graph-builder.cc.
                                                                            {
    DCHECK(unit->info()->specialize_to_function_context());
    if (Constant* n = context->TryCast<Constant>()) {
      return n->ref().AsContext().previous(unit->broker(), depth);
    }
    return {};
  }
References v8::internal::maglev::MaglevCompilationUnit::broker(), v8::internal::DCHECK(), v8::internal::maglev::MaglevCompilationUnit::info(), v8::internal::maglev::MaglevCompilationInfo::specialize_to_function_context(), and v8::internal::maglev::NodeBase::TryCast().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc