v8::internal::maglev::CheckFloat64SameValue Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckFloat64SameValue (uint64_t bitfield, Float64 value, DeoptimizeReason reason)
Float64 value () const
Input & target_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::EagerDeopt()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kFloat64}
static constexpr int kTargetIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckFloat64SameValue >
Private Attributes
const Float64 value_
Additional Inherited Members
Detailed Description
Definition at line 6962 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckFloat64SameValue::Base = FixedInputNodeT<1, CheckFloat64SameValue> [private]
Definition at line 6963 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckFloat64SameValue()
v8::internal::maglev::CheckFloat64SameValue::CheckFloat64SameValue (uint64_t bitfield, Float64 value, DeoptimizeReason reason) [inline], [explicit]
Definition at line 6966 of file maglev-ir.h.
      : Base(bitfield | ReasonField::encode(reason)), value_(value) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::CheckFloat64SameValue::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 180 of file maglev-ir-arm.cc.
                                                                       {
  Label* fail = __ GetDeoptLabel(this, deoptimize_reason());
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  DoubleRegister double_scratch = temps.AcquireScratchDouble();
  DoubleRegister target = ToDoubleRegister(target_input());
  if (value().is_nan()) {
    __ JumpIfNotNan(target, fail);
  } else {
    __ Move(double_scratch, value());
    __ CompareFloat64AndJumpIf(double_scratch, target, kNotEqual, fail, fail);
    if (value().get_scalar() == 0) { // If value is +0.0 or -0.0.
      Register scratch = temps.AcquireScratch();
      __ VmovHigh(scratch, target);
      __ cmp(scratch, Operand(0));
      __ JumpIf(value().get_bits() == 0 ? kNotEqual : kEqual, fail);
    }
  }
}
References __, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble(), v8::internal::kEqual, v8::internal::kNotEqual, target_input(), v8::internal::maglev::ToDoubleRegister(), and value().
options()
auto v8::internal::maglev::CheckFloat64SameValue::options () const [inline]
Definition at line 6983 of file maglev-ir.h.
{ return std::tuple{value_, deoptimize_reason()}; }
PrintParams()
void v8::internal::maglev::CheckFloat64SameValue::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8101 of file maglev-ir.cc.
                                                               {
  os << "(" << value().get_scalar() << ", "
     << DeoptimizeReasonToString(deoptimize_reason()) << ")";
}
References v8::internal::DeoptimizeReasonToString(), v8::internal::Float64::get_scalar(), and value().
SetValueLocationConstraints()
void v8::internal::maglev::CheckFloat64SameValue::SetValueLocationConstraints ()
Definition at line 175 of file maglev-ir-arm.cc.
                                                        {
  UseRegister(target_input());
  set_temporaries_needed((value().get_scalar() == 0) ? 1 : 0);
  set_double_temporaries_needed(value().is_nan() ? 0 : 1);
}
References target_input(), v8::internal::maglev::UseRegister(), and value().
target_input()
Input& v8::internal::maglev::CheckFloat64SameValue::target_input () [inline]
Definition at line 6977 of file maglev-ir.h.
{ return input(kTargetIndex); }
Referenced by GenerateCode(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and SetValueLocationConstraints().
value()
Float64 v8::internal::maglev::CheckFloat64SameValue::value () const [inline]
Definition at line 6974 of file maglev-ir.h.
{ return value_; }
Referenced by GenerateCode(), PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and SetValueLocationConstraints().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckFloat64SameValue::kInputTypes {ValueRepresentation::kFloat64} [static], [constexpr]
Definition at line 6972 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckFloat64SameValue::kProperties = OpProperties::EagerDeopt() [static], [constexpr]
Definition at line 6970 of file maglev-ir.h.
kTargetIndex
constexpr int v8::internal::maglev::CheckFloat64SameValue::kTargetIndex = 0 [static], [constexpr]
Definition at line 6976 of file maglev-ir.h.
value_
const Float64 v8::internal::maglev::CheckFloat64SameValue::value_ [private]
Definition at line 6988 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/maglev-ir.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc