v8::internal::TranslatedState Class Reference
#include <translated-state.h>
Classes
struct ObjectPosition
Public Types
using iterator = std::vector< TranslatedFrame >::iterator
using const_iterator = std::vector< TranslatedFrame >::const_iterator
Public Member Functions
TranslatedState ()
TranslatedState (const JavaScriptFrame *frame)
void Prepare (Address stack_frame_pointer)
void StoreMaterializedValuesAndDeopt (JavaScriptFrame *frame)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::vector< TranslatedFrame > & frames ()
TranslatedFrame * GetFrameFromJSFrameIndex (int jsframe_index)
TranslatedFrame * GetArgumentsInfoFromJSFrameIndex (int jsframe_index, int *arguments_count)
Isolate * isolate ()
void Init (Isolate *isolate, Address input_frame_pointer, Address stack_frame_pointer, DeoptTranslationIterator *iterator, Tagged< ProtectedDeoptimizationLiteralArray > protected_literal_array, const DeoptimizationLiteralProvider &literal_array, RegisterValues *registers, FILE *trace_file, int parameter_count, int actual_argument_count)
void VerifyMaterializedObjects ()
bool DoUpdateFeedback (DeoptimizeReason reason)
Private Types
enum Purpose { kDeoptimization
, kFrameInspection
 }
Private Member Functions
TranslatedFrame CreateNextTranslatedFrame (DeoptTranslationIterator *iterator, Tagged< ProtectedDeoptimizationLiteralArray > protected_literal_array, const DeoptimizationLiteralProvider &literal_array, Address fp, FILE *trace_file)
int CreateNextTranslatedValue (int frame_index, DeoptTranslationIterator *iterator, const DeoptimizationLiteralProvider &literal_array, Address fp, RegisterValues *registers, FILE *trace_file)
Address DecompressIfNeeded (intptr_t value)
void CreateArgumentsElementsTranslatedValues (int frame_index, Address input_frame_pointer, CreateArgumentsType type, FILE *trace_file)
void UpdateFromPreviouslyMaterializedObjects ()
void MaterializeFixedDoubleArray (TranslatedFrame *frame, int *value_index, TranslatedValue *slot, DirectHandle< Map > map)
void MaterializeHeapNumber (TranslatedFrame *frame, int *value_index, TranslatedValue *slot)
void EnsureObjectAllocatedAt (TranslatedValue *slot)
void SkipSlots (int slots_to_skip, TranslatedFrame *frame, int *value_index)
Handle< ByteArray > AllocateStorageFor (TranslatedValue *slot)
void EnsureJSObjectAllocated (TranslatedValue *slot, DirectHandle< Map > map)
void EnsurePropertiesAllocatedAndMarked (TranslatedValue *properties_slot, DirectHandle< Map > map)
void EnsureChildrenAllocated (int count, TranslatedFrame *frame, int *value_index, std::stack< int > *worklist)
void EnsureCapturedObjectAllocatedAt (int object_index, std::stack< int > *worklist)
Handle< HeapObject > InitializeObjectAt (TranslatedValue *slot)
void InitializeCapturedObjectAt (int object_index, std::stack< int > *worklist, const DisallowGarbageCollection &no_gc)
void InitializeJSObjectAt (TranslatedFrame *frame, int *value_index, TranslatedValue *slot, DirectHandle< Map > map, const DisallowGarbageCollection &no_gc)
void InitializeObjectWithTaggedFieldsAt (TranslatedFrame *frame, int *value_index, TranslatedValue *slot, DirectHandle< Map > map, const DisallowGarbageCollection &no_gc)
Handle< HeapObject > ResolveStringConcat (TranslatedValue *slot)
void ReadUpdateFeedback (DeoptTranslationIterator *iterator, Tagged< DeoptimizationLiteralArray > literal_array, FILE *trace_file)
TranslatedValue * ResolveCapturedObject (TranslatedValue *slot)
TranslatedValue * GetValueByObjectIndex (int object_index)
DirectHandle< Object > GetValueAndAdvance (TranslatedFrame *frame, int *value_index)
TranslatedValue * GetResolvedSlot (TranslatedFrame *frame, int value_index)
TranslatedValue * GetResolvedSlotAndAdvance (TranslatedFrame *frame, int *value_index)
Static Private Member Functions
static uint32_t GetUInt32Slot (Address fp, int slot_index)
static uint64_t GetUInt64Slot (Address fp, int slot_index)
static Float32 GetFloatSlot (Address fp, int slot_index)
static Float64 GetDoubleSlot (Address fp, int slot_index)
static Simd128 getSimd128Slot (Address fp, int slot_index)
Private Attributes
friend TranslatedValue
Purpose const purpose_
std::vector< TranslatedFrame > frames_
Isolate * isolate_ = nullptr
Address stack_frame_pointer_ = kNullAddress
int formal_parameter_count_
int actual_argument_count_
std::deque< ObjectPosition > object_positions_
Handle< FeedbackVector > feedback_vector_handle_
Tagged< FeedbackVector > feedback_vector_
FeedbackSlot feedback_slot_
Detailed Description
Definition at line 455 of file translated-state.h.
Member Typedef Documentation
const_iterator
using v8::internal::TranslatedState::const_iterator = std::vector<TranslatedFrame>::const_iterator
Definition at line 477 of file translated-state.h.
iterator
using v8::internal::TranslatedState::iterator = std::vector<TranslatedFrame>::iterator
Definition at line 473 of file translated-state.h.
Member Enumeration Documentation
Purpose
enum v8::internal::TranslatedState::Purpose [private]
Enumerator
kDeoptimization
kFrameInspection
Definition at line 506 of file translated-state.h.
{ kDeoptimization, kFrameInspection };
Constructor & Destructor Documentation
TranslatedState() [1/2]
v8::internal::TranslatedState::TranslatedState () [inline]
Definition at line 462 of file translated-state.h.
: purpose_(kDeoptimization) {}
TranslatedState() [2/2]
v8::internal::TranslatedState::TranslatedState (const JavaScriptFrame * frame) [explicit]
Definition at line 1895 of file translated-state.cc.
    : purpose_(kFrameInspection) {
  int deopt_index = SafepointEntry::kNoDeoptIndex;
  Tagged<Code> code = frame->LookupCode();
  Tagged<DeoptimizationData> data =
      static_cast<const OptimizedJSFrame*>(frame)->GetDeoptimizationData(
          code, &deopt_index);
  DCHECK(!data.is_null() && deopt_index != SafepointEntry::kNoDeoptIndex);
  DeoptimizationFrameTranslation::Iterator it(
      data->FrameTranslation(), data->TranslationIndex(deopt_index).value());
  int actual_argc = frame->GetActualArgumentCount();
  DeoptimizationLiteralProvider literals(data->LiteralArray());
  Init(frame->isolate(), frame->fp(), frame->fp(), &it,
       data->ProtectedLiteralArray(), literals, nullptr /* registers */,
       nullptr /* trace file */, code->parameter_count_without_receiver(),
       actual_argc);
}
References code, v8::internal::DCHECK(), v8::internal::StackFrame::fp(), v8::internal::JavaScriptFrame::GetActualArgumentCount(), Init(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::StackFrame::isolate(), v8::internal::SafepointEntryBase::kNoDeoptIndex, and v8::internal::StackFrame::LookupCode().
Member Function Documentation
AllocateStorageFor()
Handle< ByteArray > v8::internal::TranslatedState::AllocateStorageFor (TranslatedValue * slot) [private]
Definition at line 2445 of file translated-state.cc.
                                                                           {
  int allocate_size =
      ByteArray::LengthFor(slot->GetChildrenCount() * kTaggedSize);
  // It is important to allocate all the objects tenured so that the marker
  // does not visit them.
  Handle<ByteArray> object_storage =
      isolate()->factory()->NewByteArray(allocate_size, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  Tagged<ByteArray> raw_object_storage = *object_storage;
  for (int i = 0; i < object_storage->length(); i++) {
    raw_object_storage->set(i, kStoreTagged);
  }
  return object_storage;
}
References v8::internal::Isolate::factory(), v8::internal::TranslatedValue::GetChildrenCount(), isolate(), v8::internal::kOld, v8::internal::anonymous_namespace{translated-state.cc}::kStoreTagged, v8::internal::kTaggedSize, v8::internal::ByteArray::LengthFor(), v8::internal::FactoryBase< Impl >::NewByteArray(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by EnsureCapturedObjectAllocatedAt(), EnsureJSObjectAllocated(), and EnsurePropertiesAllocatedAndMarked().
begin() [1/2]
iterator v8::internal::TranslatedState::begin () [inline]
Definition at line 474 of file translated-state.h.
{ return frames_.begin(); }
References frames_.
Referenced by v8::internal::Deoptimizer::DebuggerInspectableFrame(), and v8::internal::OptimizedJSFrame::Summarize().
begin() [2/2]
const_iterator v8::internal::TranslatedState::begin () const [inline]
Definition at line 478 of file translated-state.h.
{ return frames_.begin(); }
References frames_.
CreateArgumentsElementsTranslatedValues()
void v8::internal::TranslatedState::CreateArgumentsElementsTranslatedValues (int frame_index, Address input_frame_pointer, CreateArgumentsType type, FILE * trace_file) [private]
Definition at line 1276 of file translated-state.cc.
                      {
  TranslatedFrame& frame = frames_[frame_index];
  int length =
      type == CreateArgumentsType::kRestParameter
          ? std::max(0, actual_argument_count_ - formal_parameter_count_)
          : actual_argument_count_;
  int object_index = static_cast<int>(object_positions_.size());
  int value_index = static_cast<int>(frame.values_.size());
  if (trace_file != nullptr) {
    PrintF(trace_file, "arguments elements object #%d (type = %d, length = %d)",
           object_index, static_cast<uint8_t>(type), length);
  }
  object_positions_.push_back({frame_index, value_index});
  frame.Add(TranslatedValue::NewDeferredObject(
      this, length + OFFSET_OF_DATA_START(FixedArray) / kTaggedSize,
      object_index));
  ReadOnlyRoots roots(isolate_);
  frame.Add(TranslatedValue::NewTagged(this, roots.fixed_array_map()));
  frame.Add(TranslatedValue::NewInt32(this, length));
  int number_of_holes = 0;
  if (type == CreateArgumentsType::kMappedArguments) {
    // If the actual number of arguments is less than the number of formal
    // parameters, we have fewer holes to fill to not overshoot the length.
    number_of_holes = std::min(formal_parameter_count_, length);
  }
  for (int i = 0; i < number_of_holes; ++i) {
    frame.Add(TranslatedValue::NewTagged(this, roots.the_hole_value()));
  }
  int argc = length - number_of_holes;
  int start_index = number_of_holes;
  if (type == CreateArgumentsType::kRestParameter) {
    start_index = std::max(0, formal_parameter_count_);
  }
  for (int i = 0; i < argc; i++) {
    // Skip the receiver.
    int offset = i + start_index + 1;
    Address arguments_frame = offset > formal_parameter_count_
                                  ? stack_frame_pointer_
                                  : input_frame_pointer;
    Address argument_slot = arguments_frame +
                            CommonFrameConstants::kFixedFrameSizeAboveFp +
                            offset * kSystemPointerSize;
    frame.Add(TranslatedValue::NewTagged(this, *FullObjectSlot(argument_slot)));
  }
}
References actual_argument_count_, v8::internal::TranslatedFrame::Add(), formal_parameter_count_, frames_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kMappedArguments, v8::internal::kRestParameter, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::length, v8::internal::TranslatedValue::NewDeferredObject(), v8::internal::TranslatedValue::NewInt32(), v8::internal::TranslatedValue::NewTagged(), object_positions_, OFFSET_OF_DATA_START, v8::internal::PrintF(), stack_frame_pointer_, v8::internal::tracing::type, and v8::internal::TranslatedFrame::values_.
Referenced by CreateNextTranslatedValue().
CreateNextTranslatedFrame()
TranslatedFrame v8::internal::TranslatedState::CreateNextTranslatedFrame (DeoptTranslationIterator * iterator, Tagged< ProtectedDeoptimizationLiteralArray > protected_literal_array, const DeoptimizationLiteralProvider & literal_array, Address fp, FILE * trace_file) [private]
Definition at line 1039 of file translated-state.cc.
                      {
  TranslationOpcode opcode = iterator->NextOpcode();
  switch (opcode) {
    case TranslationOpcode::INTERPRETED_FRAME_WITH_RETURN:
    case TranslationOpcode::INTERPRETED_FRAME_WITHOUT_RETURN: {
      BytecodeOffset bytecode_offset = BytecodeOffset(iterator->NextOperand());
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      Tagged<BytecodeArray> bytecode_array = Cast<BytecodeArray>(
          protected_literal_array->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      int return_value_offset = 0;
      int return_value_count = 0;
      if (opcode == TranslationOpcode::INTERPRETED_FRAME_WITH_RETURN) {
        return_value_offset = iterator->NextOperand();
        return_value_count = iterator->NextOperand();
      }
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file, " reading input frame %s", name.get());
        int arg_count = bytecode_array->parameter_count();
        PrintF(trace_file,
               " => bytecode_offset=%d, args=%d, height=%u, retval=%i(#%i); "
               "inputs:\n",
               bytecode_offset.ToInt(), arg_count, height, return_value_offset,
               return_value_count);
      }
      return TranslatedFrame::UnoptimizedJSFrame(
          bytecode_offset, shared_info, bytecode_array, height,
          return_value_offset, return_value_count);
    }
    case TranslationOpcode::INLINED_EXTRA_ARGUMENTS: {
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      uint32_t parameter_count = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file, " reading inlined arguments frame %s", name.get());
        PrintF(trace_file, " => height=%u, parameter_count=%u; inputs:\n",
               height, parameter_count);
      }
      return TranslatedFrame::InlinedExtraArguments(shared_info, height,
                                                    parameter_count);
    }
    case TranslationOpcode::CONSTRUCT_CREATE_STUB_FRAME: {
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file,
               " reading construct create stub frame %s => height = %d; "
               "inputs:\n",
               name.get(), height);
      }
      return TranslatedFrame::ConstructCreateStubFrame(shared_info, height);
    }
    case TranslationOpcode::CONSTRUCT_INVOKE_STUB_FRAME: {
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file,
               " reading construct invoke stub frame %s, inputs:\n",
               name.get());
      }
      return TranslatedFrame::ConstructInvokeStubFrame(shared_info);
    }
    case TranslationOpcode::BUILTIN_CONTINUATION_FRAME: {
      BytecodeOffset bytecode_offset = BytecodeOffset(iterator->NextOperand());
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file, " reading builtin continuation frame %s",
               name.get());
        PrintF(trace_file, " => bytecode_offset=%d, height=%u; inputs:\n",
               bytecode_offset.ToInt(), height);
      }
      return TranslatedFrame::BuiltinContinuationFrame(bytecode_offset,
                                                       shared_info, height);
    }
#if V8_ENABLE_WEBASSEMBLY
    case TranslationOpcode::WASM_INLINED_INTO_JS_FRAME: {
      BytecodeOffset bailout_id = BytecodeOffset(iterator->NextOperand());
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file, " reading Wasm inlined into JS frame %s",
               name.get());
        PrintF(trace_file, " => bailout_id=%d, height=%u ; inputs:\n",
               bailout_id.ToInt(), height);
      }
      return TranslatedFrame::WasmInlinedIntoJSFrame(bailout_id, shared_info,
                                                     height);
    }
    case TranslationOpcode::JS_TO_WASM_BUILTIN_CONTINUATION_FRAME: {
      BytecodeOffset bailout_id = BytecodeOffset(iterator->NextOperand());
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      int return_kind_code = iterator->NextOperand();
      std::optional<wasm::ValueKind> return_kind;
      if (return_kind_code != kNoWasmReturnKind) {
        return_kind = static_cast<wasm::ValueKind>(return_kind_code);
      }
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file, " reading JS to Wasm builtin continuation frame %s",
               name.get());
        PrintF(trace_file,
               " => bailout_id=%d, height=%u return_type=%d; inputs:\n",
               bailout_id.ToInt(), height,
               return_kind.has_value() ? return_kind.value() : -1);
      }
      return TranslatedFrame::JSToWasmBuiltinContinuationFrame(
          bailout_id, shared_info, height, return_kind);
    }
    case TranslationOpcode::LIFTOFF_FRAME: {
      BytecodeOffset bailout_id = BytecodeOffset(iterator->NextOperand());
      uint32_t height = iterator->NextOperandUnsigned();
      uint32_t function_id = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        PrintF(trace_file, " reading input for liftoff frame");
        PrintF(trace_file,
               " => bailout_id=%d, height=%u, function_id=%u ; inputs:\n",
               bailout_id.ToInt(), height, function_id);
      }
      return TranslatedFrame::LiftoffFrame(bailout_id, height, function_id);
    }
#endif // V8_ENABLE_WEBASSEMBLY
    case TranslationOpcode::JAVASCRIPT_BUILTIN_CONTINUATION_FRAME: {
      BytecodeOffset bytecode_offset = BytecodeOffset(iterator->NextOperand());
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file, " reading JavaScript builtin continuation frame %s",
               name.get());
        PrintF(trace_file, " => bytecode_offset=%d, height=%u; inputs:\n",
               bytecode_offset.ToInt(), height);
      }
      return TranslatedFrame::JavaScriptBuiltinContinuationFrame(
          bytecode_offset, shared_info, height);
    }
    case TranslationOpcode::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH_FRAME: {
      BytecodeOffset bytecode_offset = BytecodeOffset(iterator->NextOperand());
      Tagged<SharedFunctionInfo> shared_info = Cast<SharedFunctionInfo>(
          literal_array.get_on_heap_literals()->get(iterator->NextOperand()));
      uint32_t height = iterator->NextOperandUnsigned();
      if (trace_file != nullptr) {
        std::unique_ptr<char[]> name = shared_info->DebugNameCStr();
        PrintF(trace_file,
               " reading JavaScript builtin continuation frame with catch %s",
               name.get());
        PrintF(trace_file, " => bytecode_offset=%d, height=%u; inputs:\n",
               bytecode_offset.ToInt(), height);
      }
      return TranslatedFrame::JavaScriptBuiltinContinuationWithCatchFrame(
          bytecode_offset, shared_info, height);
    }
    case TranslationOpcode::UPDATE_FEEDBACK:
    case TranslationOpcode::BEGIN_WITH_FEEDBACK:
    case TranslationOpcode::BEGIN_WITHOUT_FEEDBACK:
    case TranslationOpcode::DUPLICATED_OBJECT:
    case TranslationOpcode::ARGUMENTS_ELEMENTS:
    case TranslationOpcode::ARGUMENTS_LENGTH:
    case TranslationOpcode::REST_LENGTH:
    case TranslationOpcode::CAPTURED_OBJECT:
    case TranslationOpcode::STRING_CONCAT:
    case TranslationOpcode::REGISTER:
    case TranslationOpcode::INT32_REGISTER:
    case TranslationOpcode::INT64_REGISTER:
    case TranslationOpcode::SIGNED_BIGINT64_REGISTER:
    case TranslationOpcode::UNSIGNED_BIGINT64_REGISTER:
    case TranslationOpcode::UINT32_REGISTER:
    case TranslationOpcode::BOOL_REGISTER:
    case TranslationOpcode::FLOAT_REGISTER:
    case TranslationOpcode::DOUBLE_REGISTER:
    case TranslationOpcode::HOLEY_DOUBLE_REGISTER:
    case TranslationOpcode::SIMD128_REGISTER:
    case TranslationOpcode::TAGGED_STACK_SLOT:
    case TranslationOpcode::INT32_STACK_SLOT:
    case TranslationOpcode::INT64_STACK_SLOT:
    case TranslationOpcode::SIGNED_BIGINT64_STACK_SLOT:
    case TranslationOpcode::UNSIGNED_BIGINT64_STACK_SLOT:
    case TranslationOpcode::UINT32_STACK_SLOT:
    case TranslationOpcode::BOOL_STACK_SLOT:
    case TranslationOpcode::FLOAT_STACK_SLOT:
    case TranslationOpcode::DOUBLE_STACK_SLOT:
    case TranslationOpcode::SIMD128_STACK_SLOT:
    case TranslationOpcode::HOLEY_DOUBLE_STACK_SLOT:
    case TranslationOpcode::LITERAL:
    case TranslationOpcode::OPTIMIZED_OUT:
    case TranslationOpcode::MATCH_PREVIOUS_TRANSLATION:
      break;
  }
  UNREACHABLE();
}
References v8::internal::TranslatedFrame::BuiltinContinuationFrame(), v8::internal::TranslatedFrame::ConstructCreateStubFrame(), v8::internal::TranslatedFrame::ConstructInvokeStubFrame(), v8::internal::DeoptimizationLiteralProvider::get_on_heap_literals(), v8::internal::TranslatedFrame::InlinedExtraArguments(), v8::internal::TranslatedFrame::JavaScriptBuiltinContinuationFrame(), v8::internal::TranslatedFrame::JavaScriptBuiltinContinuationWithCatchFrame(), v8::internal::kNoWasmReturnKind, v8::internal::name, v8::internal::PrintF(), v8::internal::BytecodeOffset::ToInt(), v8::internal::TranslatedFrame::UnoptimizedJSFrame(), and v8::internal::UNREACHABLE().
Referenced by Init().
CreateNextTranslatedValue()
int v8::internal::TranslatedState::CreateNextTranslatedValue (int frame_index, DeoptTranslationIterator * iterator, const DeoptimizationLiteralProvider & literal_array, Address fp, RegisterValues * registers, FILE * trace_file) [private]
Definition at line 1337 of file translated-state.cc.
                                                 {
  disasm::NameConverter converter;
  TranslatedFrame& frame = frames_[frame_index];
  int value_index = static_cast<int>(frame.values_.size());
  TranslationOpcode opcode = iterator->NextOpcode();
  switch (opcode) {
    case TranslationOpcode::BEGIN_WITH_FEEDBACK:
    case TranslationOpcode::BEGIN_WITHOUT_FEEDBACK:
    case TranslationOpcode::INTERPRETED_FRAME_WITH_RETURN:
    case TranslationOpcode::INTERPRETED_FRAME_WITHOUT_RETURN:
    case TranslationOpcode::INLINED_EXTRA_ARGUMENTS:
    case TranslationOpcode::CONSTRUCT_CREATE_STUB_FRAME:
    case TranslationOpcode::CONSTRUCT_INVOKE_STUB_FRAME:
    case TranslationOpcode::JAVASCRIPT_BUILTIN_CONTINUATION_FRAME:
    case TranslationOpcode::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH_FRAME:
    case TranslationOpcode::BUILTIN_CONTINUATION_FRAME:
#if V8_ENABLE_WEBASSEMBLY
    case TranslationOpcode::WASM_INLINED_INTO_JS_FRAME:
    case TranslationOpcode::JS_TO_WASM_BUILTIN_CONTINUATION_FRAME:
    case TranslationOpcode::LIFTOFF_FRAME:
#endif // V8_ENABLE_WEBASSEMBLY
    case TranslationOpcode::UPDATE_FEEDBACK:
    case TranslationOpcode::MATCH_PREVIOUS_TRANSLATION:
      // Peeled off before getting here.
      break;
    case TranslationOpcode::DUPLICATED_OBJECT: {
      int object_id = iterator->NextOperand();
      if (trace_file != nullptr) {
        PrintF(trace_file, "duplicated object #%d", object_id);
      }
      object_positions_.push_back(object_positions_[object_id]);
      TranslatedValue translated_value =
          TranslatedValue::NewDuplicateObject(this, object_id);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::ARGUMENTS_ELEMENTS: {
      CreateArgumentsType arguments_type =
          static_cast<CreateArgumentsType>(iterator->NextOperand());
      CreateArgumentsElementsTranslatedValues(frame_index, fp, arguments_type,
                                              trace_file);
      return 0;
    }
    case TranslationOpcode::ARGUMENTS_LENGTH: {
      if (trace_file != nullptr) {
        PrintF(trace_file, "arguments length field (length = %d)",
               actual_argument_count_);
      }
      frame.Add(TranslatedValue::NewInt32(this, actual_argument_count_));
      return 0;
    }
    case TranslationOpcode::REST_LENGTH: {
      int rest_length =
          std::max(0, actual_argument_count_ - formal_parameter_count_);
      if (trace_file != nullptr) {
        PrintF(trace_file, "rest length field (length = %d)", rest_length);
      }
      frame.Add(TranslatedValue::NewInt32(this, rest_length));
      return 0;
    }
    case TranslationOpcode::CAPTURED_OBJECT: {
      int field_count = iterator->NextOperand();
      int object_index = static_cast<int>(object_positions_.size());
      if (trace_file != nullptr) {
        PrintF(trace_file, "captured object #%d (length = %d)", object_index,
               field_count);
      }
      object_positions_.push_back({frame_index, value_index});
      TranslatedValue translated_value =
          TranslatedValue::NewDeferredObject(this, field_count, object_index);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::STRING_CONCAT: {
      int object_index = static_cast<int>(object_positions_.size());
      if (trace_file != nullptr) {
        PrintF(trace_file, "string concatenation #%d", object_index);
      }
      object_positions_.push_back({frame_index, value_index});
      TranslatedValue translated_value =
          TranslatedValue::NewStringConcat(this, object_index);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      Address uncompressed_value = DecompressIfNeeded(value);
      if (trace_file != nullptr) {
        // Need temporary access to in-sandbox memory for printing the object.
        AllowSandboxAccess temporary_sandbox_access;
        PrintF(trace_file, V8PRIxPTR_FMT " ; %s ", uncompressed_value,
               converter.NameOfCPURegister(input_reg));
        ShortPrint(Tagged<Object>(uncompressed_value), trace_file);
      }
      TranslatedValue translated_value =
          TranslatedValue::NewTagged(this, Tagged<Object>(uncompressed_value));
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::INT32_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; %s (int32)", value,
               converter.NameOfCPURegister(input_reg));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewInt32(this, static_cast<int32_t>(value));
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::INT64_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; %s (int64)", value,
               converter.NameOfCPURegister(input_reg));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewInt64(this, static_cast<int64_t>(value));
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::SIGNED_BIGINT64_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; %s (signed bigint64)", value,
               converter.NameOfCPURegister(input_reg));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewInt64ToBigInt(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::UNSIGNED_BIGINT64_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; %s (unsigned bigint64)", value,
               converter.NameOfCPURegister(input_reg));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewUint64ToBigInt(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::UINT32_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIuPTR " ; %s (uint32)", value,
               converter.NameOfCPURegister(input_reg));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewUint32(this, static_cast<uint32_t>(value));
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::BOOL_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      intptr_t value = registers->GetRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; %s (bool)", value,
               converter.NameOfCPURegister(input_reg));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewBool(this, static_cast<uint32_t>(value));
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::FLOAT_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      Float32 value = registers->GetFloatRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%e ; %s (float)", value.get_scalar(),
               RegisterName(FloatRegister::from_code(input_reg)));
      }
      TranslatedValue translated_value = TranslatedValue::NewFloat(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::DOUBLE_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      Float64 value = registers->GetDoubleRegister(input_reg);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%e ; %s (double)", value.get_scalar(),
               RegisterName(DoubleRegister::from_code(input_reg)));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewDouble(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::HOLEY_DOUBLE_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      Float64 value = registers->GetDoubleRegister(input_reg);
      if (trace_file != nullptr) {
        if (value.is_hole_nan()) {
          PrintF(trace_file, "the hole");
        } else {
          PrintF(trace_file, "%e", value.get_scalar());
        }
        PrintF(trace_file, " ; %s (holey double)",
               RegisterName(DoubleRegister::from_code(input_reg)));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewHoleyDouble(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::SIMD128_REGISTER: {
      int input_reg = iterator->NextOperandUnsigned();
      if (registers == nullptr) {
        TranslatedValue translated_value = TranslatedValue::NewInvalid(this);
        frame.Add(translated_value);
        return translated_value.GetChildrenCount();
      }
      Simd128 value = registers->GetSimd128Register(input_reg);
      if (trace_file != nullptr) {
        int8x16 val = value.to_i8x16();
        PrintF(trace_file,
               "%02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x "
               "%02x %02x %02x %02x ; %s (Simd128)",
               val.val[0], val.val[1], val.val[2], val.val[3], val.val[4],
               val.val[5], val.val[6], val.val[7], val.val[8], val.val[9],
               val.val[10], val.val[11], val.val[12], val.val[13], val.val[14],
               val.val[15], RegisterName(DoubleRegister::from_code(input_reg)));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewSimd128(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::TAGGED_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      intptr_t value = *(reinterpret_cast<intptr_t*>(fp + slot_offset));
      Address uncompressed_value = DecompressIfNeeded(value);
      if (trace_file != nullptr) {
        // Need temporary access to in-sandbox memory for printing the object.
        AllowSandboxAccess temporary_sandbox_access;
        PrintF(trace_file, V8PRIxPTR_FMT " ; [fp %c %3d] ",
               uncompressed_value, slot_offset < 0 ? '-' : '+',
               std::abs(slot_offset));
        ShortPrint(Tagged<Object>(uncompressed_value), trace_file);
      }
      TranslatedValue translated_value =
          TranslatedValue::NewTagged(this, Tagged<Object>(uncompressed_value));
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::INT32_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      uint32_t value = GetUInt32Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%d ; (int32) [fp %c %3d] ",
               static_cast<int32_t>(value), slot_offset < 0 ? '-' : '+',
               std::abs(slot_offset));
      }
      TranslatedValue translated_value = TranslatedValue::NewInt32(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::INT64_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      uint64_t value = GetUInt64Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; (int64) [fp %c %3d] ",
               static_cast<intptr_t>(value), slot_offset < 0 ? '-' : '+',
               std::abs(slot_offset));
      }
      TranslatedValue translated_value = TranslatedValue::NewInt64(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::SIGNED_BIGINT64_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      uint64_t value = GetUInt64Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; (signed bigint64) [fp %c %3d] ",
               static_cast<intptr_t>(value), slot_offset < 0 ? '-' : '+',
               std::abs(slot_offset));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewInt64ToBigInt(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::UNSIGNED_BIGINT64_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      uint64_t value = GetUInt64Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%" V8PRIdPTR " ; (unsigned bigint64) [fp %c %3d] ",
               static_cast<intptr_t>(value), slot_offset < 0 ? '-' : '+',
               std::abs(slot_offset));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewUint64ToBigInt(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::UINT32_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      uint32_t value = GetUInt32Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%u ; (uint32) [fp %c %3d] ", value,
               slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewUint32(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::BOOL_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      uint32_t value = GetUInt32Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%u ; (bool) [fp %c %3d] ", value,
               slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
      }
      TranslatedValue translated_value = TranslatedValue::NewBool(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::FLOAT_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      Float32 value = GetFloatSlot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%e ; (float) [fp %c %3d] ", value.get_scalar(),
               slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
      }
      TranslatedValue translated_value = TranslatedValue::NewFloat(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::DOUBLE_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      Float64 value = GetDoubleSlot(fp, slot_offset);
      if (trace_file != nullptr) {
        PrintF(trace_file, "%e ; (double) [fp %c %d] ", value.get_scalar(),
               slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewDouble(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::SIMD128_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      Simd128 value = getSimd128Slot(fp, slot_offset);
      if (trace_file != nullptr) {
        int8x16 val = value.to_i8x16();
        PrintF(trace_file,
               "%02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x "
               "%02x %02x %02x %02x ; (Simd128) [fp %c %d]",
               val.val[0], val.val[1], val.val[2], val.val[3], val.val[4],
               val.val[5], val.val[6], val.val[7], val.val[8], val.val[9],
               val.val[10], val.val[11], val.val[12], val.val[13], val.val[14],
               val.val[15], slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewSimd128(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::HOLEY_DOUBLE_STACK_SLOT: {
      int slot_offset = OptimizedJSFrame::StackSlotOffsetRelativeToFp(
          iterator->NextOperand());
      Float64 value = GetDoubleSlot(fp, slot_offset);
      if (trace_file != nullptr) {
        if (value.is_hole_nan()) {
          PrintF(trace_file, "the hole");
        } else {
          PrintF(trace_file, "%e", value.get_scalar());
        }
        PrintF(trace_file, " ; (holey double) [fp %c %d] ",
               slot_offset < 0 ? '-' : '+', std::abs(slot_offset));
      }
      TranslatedValue translated_value =
          TranslatedValue::NewHoleyDouble(this, value);
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::LITERAL: {
      int literal_index = iterator->NextOperand();
      TranslatedValue translated_value = literal_array.Get(this, literal_index);
      if (trace_file != nullptr) {
        if (translated_value.kind() == TranslatedValue::Kind::kTagged) {
          PrintF(trace_file, V8PRIxPTR_FMT " ; (literal %2d) ",
                 translated_value.raw_literal().ptr(), literal_index);
          ShortPrint(translated_value.raw_literal(), trace_file);
        } else {
          switch (translated_value.kind()) {
            case TranslatedValue::Kind::kDouble:
              if (translated_value.double_value().is_nan()) {
                PrintF(trace_file, "(wasm double literal %f 0x%" PRIx64 ")",
                       translated_value.double_value().get_scalar(),
                       translated_value.double_value().get_bits());
              } else {
                PrintF(trace_file, "(wasm double literal %f)",
                       translated_value.double_value().get_scalar());
              }
              break;
            case TranslatedValue::Kind::kFloat:
              if (translated_value.float_value().is_nan()) {
                PrintF(trace_file, "(wasm float literal %f 0x%x)",
                       translated_value.float_value().get_scalar(),
                       translated_value.float_value().get_bits());
              } else {
                PrintF(trace_file, "(wasm float literal %f)",
                       translated_value.float_value().get_scalar());
              }
              break;
            case TranslatedValue::Kind::kInt64:
              PrintF(trace_file, "(wasm int64 literal %" PRId64 ")",
                     translated_value.int64_value());
              break;
            case TranslatedValue::Kind::kInt32:
              PrintF(trace_file, "(wasm int32 literal %d)",
                     translated_value.int32_value());
              break;
            default:
              PrintF(trace_file, " (wasm literal) ");
              break;
          }
        }
      }
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
    case TranslationOpcode::OPTIMIZED_OUT: {
      if (trace_file != nullptr) {
        PrintF(trace_file, "(optimized out)");
      }
      TranslatedValue translated_value = TranslatedValue::NewTagged(
          this, ReadOnlyRoots(isolate_).optimized_out());
      frame.Add(translated_value);
      return translated_value.GetChildrenCount();
    }
  }
  FATAL("We should never get here - unexpected deopt info.");
}
References actual_argument_count_, v8::internal::TranslatedFrame::Add(), CreateArgumentsElementsTranslatedValues(), DecompressIfNeeded(), v8::internal::TranslatedValue::double_value(), FATAL, v8::internal::TranslatedValue::float_value(), formal_parameter_count_, frames_, v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::from_code(), v8::internal::DeoptimizationLiteralProvider::Get(), v8::internal::Float32::get_bits(), v8::internal::Float64::get_bits(), v8::internal::Float32::get_scalar(), v8::internal::Float64::get_scalar(), v8::internal::TranslatedValue::GetChildrenCount(), v8::internal::RegisterValues::GetDoubleRegister(), GetDoubleSlot(), v8::internal::RegisterValues::GetFloatRegister(), GetFloatSlot(), v8::internal::RegisterValues::GetRegister(), v8::internal::RegisterValues::GetSimd128Register(), getSimd128Slot(), GetUInt32Slot(), GetUInt64Slot(), v8::internal::TranslatedValue::int32_value(), v8::internal::TranslatedValue::int64_value(), v8::internal::Float32::is_nan(), v8::internal::Float64::is_nan(), isolate_, v8::internal::TranslatedValue::kind(), disasm::NameConverter::NameOfCPURegister(), v8::internal::TranslatedValue::NewBool(), v8::internal::TranslatedValue::NewDeferredObject(), v8::internal::TranslatedValue::NewDouble(), v8::internal::TranslatedValue::NewDuplicateObject(), v8::internal::TranslatedValue::NewFloat(), v8::internal::TranslatedValue::NewHoleyDouble(), v8::internal::TranslatedValue::NewInt32(), v8::internal::TranslatedValue::NewInt64(), v8::internal::TranslatedValue::NewInt64ToBigInt(), v8::internal::TranslatedValue::NewInvalid(), v8::internal::TranslatedValue::NewSimd128(), v8::internal::TranslatedValue::NewStringConcat(), v8::internal::TranslatedValue::NewTagged(), v8::internal::TranslatedValue::NewUint32(), v8::internal::TranslatedValue::NewUint64ToBigInt(), object_positions_, v8::internal::PrintF(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::TranslatedValue::raw_literal(), v8::internal::ShortPrint(), v8::internal::OptimizedJSFrame::StackSlotOffsetRelativeToFp(), V8PRIdPTR, V8PRIuPTR, V8PRIxPTR_FMT, v8::internal::value, and v8::internal::TranslatedFrame::values_.
Referenced by Init().
DecompressIfNeeded()
Address v8::internal::TranslatedState::DecompressIfNeeded (intptr_t value) [private]
Definition at line 1879 of file translated-state.cc.
                                                          {
  if (COMPRESS_POINTERS_BOOL &&
#ifdef V8_TARGET_ARCH_LOONG64
      // The 32-bit compressed values are supposed to be sign-extended on
      // loongarch64.
      is_int32(value)) {
#else
      static_cast<uintptr_t>(value) <= std::numeric_limits<uint32_t>::max()) {
#endif
    return V8HeapCompressionScheme::DecompressTagged(
        static_cast<uint32_t>(value));
  } else {
    return value;
  }
}
References COMPRESS_POINTERS_BOOL, v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), and v8::internal::value.
Referenced by CreateNextTranslatedValue().
DoUpdateFeedback()
bool v8::internal::TranslatedState::DoUpdateFeedback (DeoptimizeReason reason)
Definition at line 2859 of file translated-state.cc.
                                                              {
  if (!feedback_vector_handle_.is_null()) {
    CHECK(!feedback_slot_.IsInvalid());
    isolate()->CountUsage(v8::Isolate::kDeoptimizerDisableSpeculation);
    FeedbackNexus nexus(isolate(), feedback_vector_handle_, feedback_slot_);
    switch (reason) {
#define CASE(name, _, speculation_mode) \
  case DeoptimizeReason::k##name: \
    nexus.NextSpeculationMode(speculation_mode); \
    break;
      DEOPTIMIZE_IN_BUILTIN_REASON_LIST(CASE)
#undef CASE
      default:
        nexus.SetSpeculationMode(SpeculationMode::kDisallowSpeculation);
    }
    return true;
  }
  return false;
}
References CASE, CHECK, v8::internal::Isolate::CountUsage(), DEOPTIMIZE_IN_BUILTIN_REASON_LIST, feedback_slot_, feedback_vector_handle_, v8::internal::FeedbackSlot::IsInvalid(), isolate(), v8::Isolate::kDeoptimizerDisableSpeculation, v8::internal::kDisallowSpeculation, and v8::internal::FeedbackNexus::SetSpeculationMode().
Referenced by v8::internal::Deoptimizer::ProcessDeoptReason().
end() [1/2]
iterator v8::internal::TranslatedState::end () [inline]
Definition at line 475 of file translated-state.h.
{ return frames_.end(); }
References frames_.
Referenced by v8::internal::Deoptimizer::DebuggerInspectableFrame(), and v8::internal::OptimizedJSFrame::Summarize().
end() [2/2]
const_iterator v8::internal::TranslatedState::end () const [inline]
Definition at line 479 of file translated-state.h.
{ return frames_.end(); }
References frames_.
EnsureCapturedObjectAllocatedAt()
void v8::internal::TranslatedState::EnsureCapturedObjectAllocatedAt (int object_index, std::stack< int > * worklist) [private]
Definition at line 2235 of file translated-state.cc.
                                               {
  CHECK_LT(static_cast<size_t>(object_index), object_positions_.size());
  TranslatedState::ObjectPosition pos = object_positions_[object_index];
  int value_index = pos.value_index_;
  TranslatedFrame* frame = &(frames_[pos.frame_index_]);
  TranslatedValue* slot = &(frame->values_[value_index]);
  value_index++;
  CHECK_EQ(TranslatedValue::kAllocated, slot->materialization_state());
  CHECK_EQ(TranslatedValue::kCapturedObject, slot->kind());
  // Read the map.
  // The map should never be materialized, so let us check we already have
  // an existing object here.
  CHECK_EQ(frame->values_[value_index].kind(), TranslatedValue::kTagged);
  auto map = Cast<Map>(frame->values_[value_index].GetValue());
  CHECK(IsMap(*map));
  value_index++;
  // Handle the special cases.
  switch (map->instance_type()) {
    case FIXED_DOUBLE_ARRAY_TYPE:
      // Materialize (i.e. allocate&initialize) the array and return since
      // there is no need to process the children.
      return MaterializeFixedDoubleArray(frame, &value_index, slot, map);
    case HEAP_NUMBER_TYPE:
      // Materialize (i.e. allocate&initialize) the heap number and return.
      // There is no need to process the children.
      return MaterializeHeapNumber(frame, &value_index, slot);
    case FIXED_ARRAY_TYPE:
    case SCRIPT_CONTEXT_TABLE_TYPE:
    case AWAIT_CONTEXT_TYPE:
    case BLOCK_CONTEXT_TYPE:
    case CATCH_CONTEXT_TYPE:
    case DEBUG_EVALUATE_CONTEXT_TYPE:
    case EVAL_CONTEXT_TYPE:
    case FUNCTION_CONTEXT_TYPE:
    case MODULE_CONTEXT_TYPE:
    case NATIVE_CONTEXT_TYPE:
    case SCRIPT_CONTEXT_TYPE:
    case WITH_CONTEXT_TYPE:
    case HASH_TABLE_TYPE:
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
    case NAME_DICTIONARY_TYPE:
    case GLOBAL_DICTIONARY_TYPE:
    case NUMBER_DICTIONARY_TYPE:
    case SIMPLE_NUMBER_DICTIONARY_TYPE: {
      // Check we have the right size.
      int array_length = frame->values_[value_index].GetSmiValue();
      int instance_size = FixedArray::SizeFor(array_length);
      CHECK_EQ(instance_size, slot->GetChildrenCount() * kTaggedSize);
      // Canonicalize empty fixed array.
      if (*map == ReadOnlyRoots(isolate()).empty_fixed_array()->map() &&
          array_length == 0) {
        slot->set_storage(isolate()->factory()->empty_fixed_array());
      } else {
        slot->set_storage(AllocateStorageFor(slot));
      }
      // Make sure all the remaining children (after the map) are allocated.
      return EnsureChildrenAllocated(slot->GetChildrenCount() - 1, frame,
                                     &value_index, worklist);
    }
    case SLOPPY_ARGUMENTS_ELEMENTS_TYPE: {
      // Verify that the arguments size is correct.
      int args_length = frame->values_[value_index].GetSmiValue();
      int args_size = SloppyArgumentsElements::SizeFor(args_length);
      CHECK_EQ(args_size, slot->GetChildrenCount() * kTaggedSize);
      slot->set_storage(AllocateStorageFor(slot));
      // Make sure all the remaining children (after the map) are allocated.
      return EnsureChildrenAllocated(slot->GetChildrenCount() - 1, frame,
                                     &value_index, worklist);
    }
    case PROPERTY_ARRAY_TYPE: {
      // Check we have the right size.
      int length_or_hash = frame->values_[value_index].GetSmiValue();
      int array_length = PropertyArray::LengthField::decode(length_or_hash);
      int instance_size = PropertyArray::SizeFor(array_length);
      CHECK_EQ(instance_size, slot->GetChildrenCount() * kTaggedSize);
      slot->set_storage(AllocateStorageFor(slot));
      // Make sure all the remaining children (after the map) are allocated.
      return EnsureChildrenAllocated(slot->GetChildrenCount() - 1, frame,
                                     &value_index, worklist);
    }
    default:
      EnsureJSObjectAllocated(slot, map);
      int remaining_children_count = slot->GetChildrenCount() - 1;
      TranslatedValue* properties_slot = frame->ValueAt(value_index);
      value_index++, remaining_children_count--;
      if (properties_slot->kind() == TranslatedValue::kCapturedObject) {
        // We are materializing the property array, so make sure we put the
        // mutable heap numbers at the right places.
        EnsurePropertiesAllocatedAndMarked(properties_slot, map);
        EnsureChildrenAllocated(properties_slot->GetChildrenCount(), frame,
                                &value_index, worklist);
      } else {
        CHECK_EQ(properties_slot->kind(), TranslatedValue::kTagged);
      }
      TranslatedValue* elements_slot = frame->ValueAt(value_index);
      value_index++, remaining_children_count--;
      if (elements_slot->kind() == TranslatedValue::kCapturedObject ||
          !IsJSArrayMap(*map)) {
        // Handle this case with the other remaining children below.
        value_index--, remaining_children_count++;
      } else {
        CHECK_EQ(elements_slot->kind(), TranslatedValue::kTagged);
        elements_slot->GetValue();
        if (purpose_ == kFrameInspection) {
          // We are materializing a JSArray for the purpose of frame inspection.
          // If we were to construct it with the above elements value then an
          // actual deopt later on might create another JSArray instance with
          // the same elements store. That would violate the key assumption
          // behind left-trimming.
          elements_slot->ReplaceElementsArrayWithCopy();
        }
      }
      // Make sure all the remaining children (after the map, properties store,
      // and possibly elements store) are allocated.
      return EnsureChildrenAllocated(remaining_children_count, frame,
                                     &value_index, worklist);
  }
  UNREACHABLE();
}
References AllocateStorageFor(), CHECK, CHECK_EQ, CHECK_LT, v8::base::BitField< T, shift, size, U >::decode(), EnsureChildrenAllocated(), EnsureJSObjectAllocated(), EnsurePropertiesAllocatedAndMarked(), v8::internal::TranslatedState::ObjectPosition::frame_index_, frames_, v8::internal::TranslatedValue::GetChildrenCount(), v8::internal::TranslatedValue::GetValue(), isolate(), v8::internal::TranslatedValue::kAllocated, v8::internal::TranslatedValue::kCapturedObject, kFrameInspection, v8::internal::TranslatedValue::kind(), v8::internal::TranslatedValue::kTagged, v8::internal::kTaggedSize, v8::internal::TranslatedValue::materialization_state(), MaterializeFixedDoubleArray(), MaterializeHeapNumber(), object_positions_, purpose_, v8::internal::TranslatedValue::ReplaceElementsArrayWithCopy(), v8::internal::TranslatedValue::set_storage(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::TaggedArrayBase< SloppyArgumentsElements, SloppyArgumentsElementsShape >::SizeFor(), v8::internal::PropertyArray::SizeFor(), v8::internal::UNREACHABLE(), v8::internal::TranslatedState::ObjectPosition::value_index_, v8::internal::TranslatedFrame::ValueAt(), and v8::internal::TranslatedFrame::values_.
Referenced by EnsureObjectAllocatedAt().
EnsureChildrenAllocated()
void v8::internal::TranslatedState::EnsureChildrenAllocated (int count, TranslatedFrame * frame, int * value_index, std::stack< int > * worklist) [private]
Definition at line 2390 of file translated-state.cc.
                                                                       {
  // Ensure all children are allocated.
  for (int i = 0; i < count; i++) {
    // If the field is an object that has not been allocated yet, queue it
    // for initialization (and mark it as such).
    TranslatedValue* child_slot = frame->ValueAt(*value_index);
    if (child_slot->kind() == TranslatedValue::kCapturedObject ||
        child_slot->kind() == TranslatedValue::kDuplicatedObject) {
      child_slot = ResolveCapturedObject(child_slot);
      if (child_slot->kind() == TranslatedValue::kCapturedStringConcat) {
        ResolveStringConcat(child_slot);
      } else if (child_slot->materialization_state() ==
                 TranslatedValue::kUninitialized) {
        worklist->push(child_slot->object_index());
        child_slot->mark_allocated();
      }
    } else {
      // Make sure the simple values (heap numbers, etc.) are properly
      // initialized.
      child_slot->GetValue();
    }
    SkipSlots(1, frame, value_index);
  }
}
References v8::internal::TranslatedValue::GetValue(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kCapturedStringConcat, v8::internal::TranslatedValue::kDuplicatedObject, v8::internal::TranslatedValue::kind(), v8::internal::TranslatedValue::kUninitialized, v8::internal::TranslatedValue::mark_allocated(), v8::internal::TranslatedValue::materialization_state(), v8::internal::TranslatedValue::object_index(), ResolveCapturedObject(), ResolveStringConcat(), SkipSlots(), and v8::internal::TranslatedFrame::ValueAt().
Referenced by EnsureCapturedObjectAllocatedAt().
EnsureJSObjectAllocated()
void v8::internal::TranslatedState::EnsureJSObjectAllocated (TranslatedValue * slot, DirectHandle< Map > map) [private]
Definition at line 2460 of file translated-state.cc.
                                                                     {
  CHECK(IsJSObjectMap(*map));
  CHECK_EQ(map->instance_size(), slot->GetChildrenCount() * kTaggedSize);
  Handle<ByteArray> object_storage = AllocateStorageFor(slot);
  // Now we handle the interesting (JSObject) case.
  DisallowGarbageCollection no_gc;
  Tagged<Map> raw_map = *map;
  Tagged<ByteArray> raw_object_storage = *object_storage;
  Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate());
  // Set markers for in-object properties.
  for (InternalIndex i : raw_map->IterateOwnDescriptors()) {
    FieldIndex index = FieldIndex::ForDescriptor(raw_map, i);
    Representation representation = descriptors->GetDetails(i).representation();
    if (index.is_inobject() &&
        (representation.IsDouble() || representation.IsHeapObject())) {
      CHECK_GE(index.index(), OFFSET_OF_DATA_START(FixedArray) / kTaggedSize);
      int array_index =
          index.index() * kTaggedSize - OFFSET_OF_DATA_START(FixedArray);
      raw_object_storage->set(array_index, kStoreHeapObject);
    }
  }
  slot->set_storage(object_storage);
}
References AllocateStorageFor(), CHECK, CHECK_EQ, CHECK_GE, v8::internal::FieldIndex::ForDescriptor(), v8::internal::TranslatedValue::GetChildrenCount(), v8::internal::index, v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), isolate(), v8::internal::anonymous_namespace{translated-state.cc}::kStoreHeapObject, v8::internal::kTaggedSize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, OFFSET_OF_DATA_START, and v8::internal::TranslatedValue::set_storage().
Referenced by EnsureCapturedObjectAllocatedAt().
EnsureObjectAllocatedAt()
void v8::internal::TranslatedState::EnsureObjectAllocatedAt (TranslatedValue * slot) [private]
Definition at line 2151 of file translated-state.cc.
                                                                   {
  slot = ResolveCapturedObject(slot);
  if (slot->kind() == TranslatedValue::kCapturedStringConcat) {
    ResolveStringConcat(slot);
    return;
  }
  if (slot->materialization_state() == TranslatedValue::kUninitialized) {
    std::stack<int> worklist;
    worklist.push(slot->object_index());
    slot->mark_allocated();
    while (!worklist.empty()) {
      int index = worklist.top();
      worklist.pop();
      EnsureCapturedObjectAllocatedAt(index, &worklist);
    }
  }
}
References EnsureCapturedObjectAllocatedAt(), v8::internal::index, v8::internal::TranslatedValue::kCapturedStringConcat, v8::internal::TranslatedValue::kind(), v8::internal::TranslatedValue::kUninitialized, v8::internal::TranslatedValue::mark_allocated(), v8::internal::TranslatedValue::materialization_state(), v8::internal::TranslatedValue::object_index(), ResolveCapturedObject(), and ResolveStringConcat().
Referenced by v8::internal::TranslatedValue::GetValue().
EnsurePropertiesAllocatedAndMarked()
void v8::internal::TranslatedState::EnsurePropertiesAllocatedAndMarked (TranslatedValue * properties_slot, DirectHandle< Map > map) [private]
Definition at line 2418 of file translated-state.cc.
                                                             {
  CHECK_EQ(TranslatedValue::kUninitialized,
           properties_slot->materialization_state());
  Handle<ByteArray> object_storage = AllocateStorageFor(properties_slot);
  properties_slot->mark_allocated();
  properties_slot->set_storage(object_storage);
  DisallowGarbageCollection no_gc;
  Tagged<Map> raw_map = *map;
  Tagged<ByteArray> raw_object_storage = *object_storage;
  // Set markers for out-of-object properties.
  Tagged<DescriptorArray> descriptors = map->instance_descriptors(isolate());
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    FieldIndex index = FieldIndex::ForDescriptor(raw_map, i);
    Representation representation = descriptors->GetDetails(i).representation();
    if (!index.is_inobject() &&
        (representation.IsDouble() || representation.IsHeapObject())) {
      int outobject_index = index.outobject_array_index();
      int array_index = outobject_index * kTaggedSize;
      raw_object_storage->set(array_index, kStoreHeapObject);
    }
  }
}
References AllocateStorageFor(), CHECK_EQ, v8::internal::FieldIndex::ForDescriptor(), v8::internal::index, v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), isolate(), v8::internal::anonymous_namespace{translated-state.cc}::kStoreHeapObject, v8::internal::kTaggedSize, v8::internal::TranslatedValue::kUninitialized, v8::internal::TranslatedValue::mark_allocated(), v8::internal::TranslatedValue::materialization_state(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::TranslatedValue::set_storage().
Referenced by EnsureCapturedObjectAllocatedAt().
frames()
std::vector<TranslatedFrame>& v8::internal::TranslatedState::frames () [inline]
Definition at line 481 of file translated-state.h.
{ return frames_; }
References frames_.
Referenced by v8::internal::Deoptimizer::DoComputeOutputFrames(), and v8::internal::Deoptimizer::DoComputeUnoptimizedFrame().
GetArgumentsInfoFromJSFrameIndex()
TranslatedFrame * v8::internal::TranslatedState::GetArgumentsInfoFromJSFrameIndex (int jsframe_index, int * arguments_count)
Definition at line 2692 of file translated-state.cc.
                                        {
  for (size_t i = 0; i < frames_.size(); i++) {
    if (frames_[i].kind() == TranslatedFrame::kUnoptimizedFunction ||
        frames_[i].kind() == TranslatedFrame::kJavaScriptBuiltinContinuation ||
        frames_[i].kind() ==
            TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch) {
      if (jsframe_index > 0) {
        jsframe_index--;
      } else {
        // We have the JS function frame, now check if it has arguments
        // adaptor.
        if (i > 0 &&
            frames_[i - 1].kind() == TranslatedFrame::kInlinedExtraArguments) {
          *args_count = frames_[i - 1].height();
          return &(frames_[i - 1]);
        }
        // JavaScriptBuiltinContinuation frames that are not preceded by
        // a arguments adapter frame are currently only used by C++ API calls
        // from TurboFan. Calls to C++ API functions from TurboFan need
        // a special marker frame state, otherwise the API call wouldn't
        // be shown in a stack trace.
        if (frames_[i].kind() ==
            TranslatedFrame::kJavaScriptBuiltinContinuation) {
          DCHECK(frames_[i].shared_info()->IsApiFunction());
          // The argument count for this special case is always the second
          // to last value in the TranslatedFrame. It should also always be
          // {1}, as the GenericLazyDeoptContinuation builtin has one explicit
          // argument (the result).
          static constexpr int kTheContext = 1;
          const uint32_t height = frames_[i].height() + kTheContext;
          *args_count = frames_[i].ValueAt(height - 1)->GetSmiValue();
          DCHECK_EQ(*args_count, JSParameterCount(1));
          return &(frames_[i]);
        }
        DCHECK_EQ(frames_[i].kind(), TranslatedFrame::kUnoptimizedFunction);
        *args_count = frames_[i].bytecode_array()->parameter_count();
        return &(frames_[i]);
      }
    }
  }
  return nullptr;
}
References v8::internal::DCHECK(), DCHECK_EQ, frames_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::JSParameterCount(), v8::internal::TranslatedFrame::kInlinedExtraArguments, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuation, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch, and v8::internal::TranslatedFrame::kUnoptimizedFunction.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), and v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments().
GetDoubleSlot()
Float64 v8::internal::TranslatedState::GetDoubleSlot (Address fp, int slot_index) [static], [private]
Definition at line 841 of file translated-state.cc.
                                                                  {
  return Float64::FromBits(GetUInt64Slot(fp, slot_offset));
}
References v8::internal::Float64::FromBits(), and GetUInt64Slot().
Referenced by CreateNextTranslatedValue().
GetFloatSlot()
Float32 v8::internal::TranslatedState::GetFloatSlot (Address fp, int slot_index) [static], [private]
Definition at line 833 of file translated-state.cc.
                                                                 {
#if !V8_TARGET_ARCH_S390X && !V8_TARGET_ARCH_PPC64
  return Float32::FromBits(GetUInt32Slot(fp, slot_offset));
#else
  return Float32::FromBits(Memory<uint32_t>(fp + slot_offset));
#endif
}
References v8::internal::Float32::FromBits(), and GetUInt32Slot().
Referenced by CreateNextTranslatedValue().
GetFrameFromJSFrameIndex()
TranslatedFrame * v8::internal::TranslatedState::GetFrameFromJSFrameIndex (int jsframe_index)
Definition at line 2676 of file translated-state.cc.
                                                                            {
  for (size_t i = 0; i < frames_.size(); i++) {
    if (frames_[i].kind() == TranslatedFrame::kUnoptimizedFunction ||
        frames_[i].kind() == TranslatedFrame::kJavaScriptBuiltinContinuation ||
        frames_[i].kind() ==
            TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch) {
      if (jsframe_index > 0) {
        jsframe_index--;
      } else {
        return &(frames_[i]);
      }
    }
  }
  return nullptr;
}
References frames_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuation, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch, and v8::internal::TranslatedFrame::kUnoptimizedFunction.
Referenced by v8::internal::FrameFunctionIterator::MaterializeFunction().
GetResolvedSlot()
TranslatedValue * v8::internal::TranslatedState::GetResolvedSlot (TranslatedFrame * frame, int value_index) [private]
Definition at line 2488 of file translated-state.cc.
                                                                   {
  TranslatedValue* slot = frame->ValueAt(value_index);
  if (slot->kind() == TranslatedValue::kDuplicatedObject) {
    slot = ResolveCapturedObject(slot);
  }
  CHECK_NE(slot->materialization_state(), TranslatedValue::kUninitialized);
  return slot;
}
References CHECK_NE, v8::internal::TranslatedValue::kDuplicatedObject, v8::internal::TranslatedValue::kind(), v8::internal::TranslatedValue::kUninitialized, v8::internal::TranslatedValue::materialization_state(), ResolveCapturedObject(), and v8::internal::TranslatedFrame::ValueAt().
Referenced by GetResolvedSlotAndAdvance(), and GetValueAndAdvance().
GetResolvedSlotAndAdvance()
TranslatedValue * v8::internal::TranslatedState::GetResolvedSlotAndAdvance (TranslatedFrame * frame, int * value_index) [private]
Definition at line 2498 of file translated-state.cc.
                                              {
  TranslatedValue* slot = GetResolvedSlot(frame, *value_index);
  SkipSlots(1, frame, value_index);
  return slot;
}
References GetResolvedSlot(), and SkipSlots().
Referenced by InitializeJSObjectAt(), and InitializeObjectWithTaggedFieldsAt().
getSimd128Slot()
Simd128 v8::internal::TranslatedState::getSimd128Slot (Address fp, int slot_index) [static], [private]
Definition at line 845 of file translated-state.cc.
                                                                   {
  return base::ReadUnalignedValue<Simd128>(fp + slot_offset);
}
Referenced by CreateNextTranslatedValue().
GetUInt32Slot()
uint32_t v8::internal::TranslatedState::GetUInt32Slot (Address fp, int slot_index) [static], [private]
Definition at line 824 of file translated-state.cc.
                                                                   {
  Address address = fp + slot_offset;
#if V8_TARGET_BIG_ENDIAN && V8_HOST_ARCH_64_BIT
  return Memory<uint32_t>(address + kIntSize);
#else
  return Memory<uint32_t>(address);
#endif
}
References v8::internal::kIntSize.
Referenced by CreateNextTranslatedValue(), and GetFloatSlot().
GetUInt64Slot()
uint64_t v8::internal::TranslatedState::GetUInt64Slot (Address fp, int slot_index) [static], [private]
Definition at line 816 of file translated-state.cc.
                                                                   {
#if V8_TARGET_ARCH_32_BIT
  return ReadUnalignedValue<uint64_t>(fp + slot_offset);
#else
  return Memory<uint64_t>(fp + slot_offset);
#endif
}
Referenced by CreateNextTranslatedValue(), and GetDoubleSlot().
GetValueAndAdvance()
DirectHandle< Object > v8::internal::TranslatedState::GetValueAndAdvance (TranslatedFrame * frame, int * value_index) [private]
Definition at line 2505 of file translated-state.cc.
                                                                           {
  TranslatedValue* slot = GetResolvedSlot(frame, *value_index);
  SkipSlots(1, frame, value_index);
  return slot->GetValue();
}
References GetResolvedSlot(), v8::internal::TranslatedValue::GetValue(), and SkipSlots().
Referenced by InitializeJSObjectAt(), and InitializeObjectWithTaggedFieldsAt().
GetValueByObjectIndex()
TranslatedValue * v8::internal::TranslatedState::GetValueByObjectIndex (int object_index) [private]
Definition at line 2007 of file translated-state.cc.
                                                                        {
  CHECK_LT(static_cast<size_t>(object_index), object_positions_.size());
  TranslatedState::ObjectPosition pos = object_positions_[object_index];
  return &(frames_[pos.frame_index_].values_[pos.value_index_]);
}
References CHECK_LT, v8::internal::TranslatedState::ObjectPosition::frame_index_, frames_, object_positions_, and v8::internal::TranslatedState::ObjectPosition::value_index_.
Referenced by ResolveCapturedObject(), and VerifyMaterializedObjects().
Init()
void v8::internal::TranslatedState::Init (Isolate * isolate, Address input_frame_pointer, Address stack_frame_pointer, DeoptTranslationIterator * iterator, Tagged< ProtectedDeoptimizationLiteralArray > protected_literal_array, const DeoptimizationLiteralProvider & literal_array, RegisterValues * registers, FILE * trace_file, int parameter_count, int actual_argument_count)
Definition at line 1913 of file translated-state.cc.
                               {
  DCHECK(frames_.empty());
  stack_frame_pointer_ = stack_frame_pointer;
  formal_parameter_count_ = formal_parameter_count;
  actual_argument_count_ = actual_argument_count;
  isolate_ = isolate;
  // Read out the 'header' translation.
  TranslationOpcode opcode = iterator->NextOpcode();
  CHECK(TranslationOpcodeIsBegin(opcode));
  iterator->NextOperand(); // Skip the lookback distance.
  int count = iterator->NextOperand();
  frames_.reserve(count);
  iterator->NextOperand(); // Drop JS frames count.
  if (opcode == TranslationOpcode::BEGIN_WITH_FEEDBACK) {
    ReadUpdateFeedback(iterator, literal_array.get_on_heap_literals(),
                       trace_file);
  }
  std::stack<int> nested_counts;
  // Read the frames
  for (int frame_index = 0; frame_index < count; frame_index++) {
    // Read the frame descriptor.
    frames_.push_back(CreateNextTranslatedFrame(
        iterator, protected_literal_array, literal_array, input_frame_pointer,
        trace_file));
    TranslatedFrame& frame = frames_.back();
    // Read the values.
    int values_to_process = frame.GetValueCount();
    while (values_to_process > 0 || !nested_counts.empty()) {
      if (trace_file != nullptr) {
        if (nested_counts.empty()) {
          // For top level values, print the value number.
          PrintF(trace_file,
                 " %3i: ", frame.GetValueCount() - values_to_process);
        } else {
          // Take care of indenting for nested values.
          PrintF(trace_file, " ");
          for (size_t j = 0; j < nested_counts.size(); j++) {
            PrintF(trace_file, " ");
          }
        }
      }
      int nested_count =
          CreateNextTranslatedValue(frame_index, iterator, literal_array,
                                    input_frame_pointer, registers, trace_file);
      if (trace_file != nullptr) {
        PrintF(trace_file, "\n");
      }
      // Update the value count and resolve the nesting.
      values_to_process--;
      if (nested_count > 0) {
        nested_counts.push(values_to_process);
        values_to_process = nested_count;
      } else {
        while (values_to_process == 0 && !nested_counts.empty()) {
          values_to_process = nested_counts.top();
          nested_counts.pop();
        }
      }
    }
  }
  CHECK(!iterator->HasNextOpcode() ||
        TranslationOpcodeIsBegin(iterator->NextOpcode()));
}
References actual_argument_count_, CHECK, CreateNextTranslatedFrame(), CreateNextTranslatedValue(), v8::internal::DCHECK(), formal_parameter_count_, frames_, v8::internal::DeoptimizationLiteralProvider::get_on_heap_literals(), v8::internal::TranslatedFrame::GetValueCount(), isolate(), isolate_, v8::internal::PrintF(), ReadUpdateFeedback(), stack_frame_pointer_, and v8::internal::TranslationOpcodeIsBegin().
Referenced by v8::internal::Deoptimizer::DoComputeOutputFrames(), and TranslatedState().
InitializeCapturedObjectAt()
void v8::internal::TranslatedState::InitializeCapturedObjectAt (int object_index, std::stack< int > * worklist, const DisallowGarbageCollection & no_gc) [private]
Definition at line 2068 of file translated-state.cc.
                                            {
  CHECK_LT(static_cast<size_t>(object_index), object_positions_.size());
  TranslatedState::ObjectPosition pos = object_positions_[object_index];
  int value_index = pos.value_index_;
  TranslatedFrame* frame = &(frames_[pos.frame_index_]);
  TranslatedValue* slot = &(frame->values_[value_index]);
  value_index++;
  // Note that we cannot reach this point with kCapturedStringConcats slots,
  // since they have been already finalized in EnsureObjectAllocatedAt and
  // EnsureCapturedObjectAllocatedAt.
  CHECK_EQ(TranslatedValue::kFinished, slot->materialization_state());
  CHECK_EQ(TranslatedValue::kCapturedObject, slot->kind());
  // Ensure all fields are initialized.
  int children_init_index = value_index;
  for (int i = 0; i < slot->GetChildrenCount(); i++) {
    // If the field is an object that has not been initialized yet, queue it
    // for initialization (and mark it as such).
    TranslatedValue* child_slot = frame->ValueAt(children_init_index);
    if (child_slot->kind() == TranslatedValue::kCapturedObject ||
        child_slot->kind() == TranslatedValue::kDuplicatedObject) {
      child_slot = ResolveCapturedObject(child_slot);
      if (child_slot->materialization_state() != TranslatedValue::kFinished) {
        CHECK_EQ(TranslatedValue::kAllocated,
                 child_slot->materialization_state());
        worklist->push(child_slot->object_index());
        child_slot->mark_finished();
      }
    }
    SkipSlots(1, frame, &children_init_index);
  }
  // Read the map.
  // The map should never be materialized, so let us check we already have
  // an existing object here.
  CHECK_EQ(frame->values_[value_index].kind(), TranslatedValue::kTagged);
  auto map = Cast<Map>(frame->values_[value_index].GetValue());
  CHECK(IsMap(*map));
  value_index++;
  // Handle the special cases.
  switch (map->instance_type()) {
    case HEAP_NUMBER_TYPE:
    case FIXED_DOUBLE_ARRAY_TYPE:
      return;
    case FIXED_ARRAY_TYPE:
    case AWAIT_CONTEXT_TYPE:
    case BLOCK_CONTEXT_TYPE:
    case CATCH_CONTEXT_TYPE:
    case DEBUG_EVALUATE_CONTEXT_TYPE:
    case EVAL_CONTEXT_TYPE:
    case FUNCTION_CONTEXT_TYPE:
    case MODULE_CONTEXT_TYPE:
    case NATIVE_CONTEXT_TYPE:
    case SCRIPT_CONTEXT_TYPE:
    case WITH_CONTEXT_TYPE:
    case OBJECT_BOILERPLATE_DESCRIPTION_TYPE:
    case HASH_TABLE_TYPE:
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
    case NAME_DICTIONARY_TYPE:
    case GLOBAL_DICTIONARY_TYPE:
    case NUMBER_DICTIONARY_TYPE:
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
    case PROPERTY_ARRAY_TYPE:
    case SCRIPT_CONTEXT_TABLE_TYPE:
    case SLOPPY_ARGUMENTS_ELEMENTS_TYPE:
      InitializeObjectWithTaggedFieldsAt(frame, &value_index, slot, map, no_gc);
      break;
    default:
      CHECK(IsJSObjectMap(*map));
      InitializeJSObjectAt(frame, &value_index, slot, map, no_gc);
      break;
  }
  CHECK_EQ(value_index, children_init_index);
}
References CHECK, CHECK_EQ, CHECK_LT, v8::internal::TranslatedState::ObjectPosition::frame_index_, frames_, v8::internal::TranslatedValue::GetChildrenCount(), InitializeJSObjectAt(), InitializeObjectWithTaggedFieldsAt(), v8::internal::TranslatedValue::kAllocated, v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kDuplicatedObject, v8::internal::TranslatedValue::kFinished, v8::internal::TranslatedValue::kind(), v8::internal::TranslatedValue::kTagged, v8::internal::TranslatedValue::mark_finished(), v8::internal::TranslatedValue::materialization_state(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TranslatedValue::object_index(), object_positions_, ResolveCapturedObject(), SkipSlots(), v8::internal::TranslatedState::ObjectPosition::value_index_, v8::internal::TranslatedFrame::ValueAt(), and v8::internal::TranslatedFrame::values_.
Referenced by InitializeObjectAt().
InitializeJSObjectAt()
void v8::internal::TranslatedState::InitializeJSObjectAt (TranslatedFrame * frame, int * value_index, TranslatedValue * slot, DirectHandle< Map > map, const DisallowGarbageCollection & no_gc) [private]
Definition at line 2512 of file translated-state.cc.
                                                                   {
  auto object_storage = Cast<HeapObject>(slot->storage_);
  DCHECK_EQ(TranslatedValue::kCapturedObject, slot->kind());
  int children_count = slot->GetChildrenCount();
  // The object should have at least a map and some payload.
  CHECK_GE(children_count, 2);
#if DEBUG
  // No need to invalidate slots in object because no slot was recorded yet.
  // Verify this here.
  Address object_start = object_storage->address();
  Address object_end = object_start + children_count * kTaggedSize;
  isolate()->heap()->VerifySlotRangeHasNoRecordedSlots(object_start,
                                                       object_end);
#endif // DEBUG
  // Notify the concurrent marker about the layout change.
  isolate()->heap()->NotifyObjectLayoutChange(
      *object_storage, no_gc, InvalidateRecordedSlots::kNo,
      InvalidateExternalPointerSlots::kNo);
  // Finish any sweeping so that it becomes safe to overwrite the ByteArray
  // headers. See chromium:1228036.
  isolate()->heap()->EnsureSweepingCompletedForObject(*object_storage);
  // Fill the property array field.
  {
    DirectHandle<Object> properties = GetValueAndAdvance(frame, value_index);
    WRITE_FIELD(*object_storage, JSObject::kPropertiesOrHashOffset,
                *properties);
    WRITE_BARRIER(*object_storage, JSObject::kPropertiesOrHashOffset,
                  *properties);
  }
  // For all the other fields we first look at the fixed array and check the
  // marker to see if we store an unboxed double.
  DCHECK_EQ(kTaggedSize, JSObject::kPropertiesOrHashOffset);
  for (int i = 2; i < children_count; i++) {
    slot = GetResolvedSlotAndAdvance(frame, value_index);
    // Read out the marker and ensure the field is consistent with
    // what the markers in the storage say (note that all heap numbers
    // should be fully initialized by now).
    int offset = i * kTaggedSize;
    uint8_t marker = object_storage->ReadField<uint8_t>(offset);
    InstanceType instance_type = map->instance_type();
    USE(instance_type);
#ifdef V8_ENABLE_LEAPTIERING
    if (InstanceTypeChecker::IsJSFunction(instance_type) &&
        offset == JSFunction::kDispatchHandleOffset) {
      // The JSDispatchHandle will be materialized as a number, but we need
      // the raw value here. TODO(saelo): can we implement "proper" support
      // for JSDispatchHandles in the deoptimizer?
      DirectHandle<Object> field_value = slot->GetValue();
      CHECK(IsNumber(*field_value));
      JSDispatchHandle handle(Object::NumberValue(Cast<Number>(*field_value)));
      object_storage->WriteField<JSDispatchHandle::underlying_type>(
          JSFunction::kDispatchHandleOffset, handle.value());
      continue;
    }
#endif // V8_ENABLE_LEAPTIERING
#ifdef V8_ENABLE_SANDBOX
    if (InstanceTypeChecker::IsJSRegExp(instance_type) &&
        offset == JSRegExp::kDataOffset) {
      DirectHandle<HeapObject> field_value = slot->storage();
      // If the value comes from the DeoptimizationLiteralArray, it is a
      // RegExpDataWrapper as we can't store TrustedSpace values in a FixedArray
      // directly.
      Tagged<RegExpData> value;
      if (Is<RegExpDataWrapper>(*field_value)) {
        value = Cast<RegExpDataWrapper>(*field_value)->data(isolate());
      } else {
        CHECK(IsRegExpData(*field_value));
        value = Cast<RegExpData>(*field_value);
      }
      object_storage
          ->RawIndirectPointerField(offset, kRegExpDataIndirectPointerTag)
          .Relaxed_Store(value);
      INDIRECT_POINTER_WRITE_BARRIER(*object_storage, offset,
                                     kRegExpDataIndirectPointerTag, value);
      continue;
    }
#endif // V8_ENABLE_SANDBOX
    if (marker == kStoreHeapObject) {
      DirectHandle<HeapObject> field_value = slot->storage();
      WRITE_FIELD(*object_storage, offset, *field_value);
      WRITE_BARRIER(*object_storage, offset, *field_value);
      continue;
    }
    CHECK_EQ(kStoreTagged, marker);
    DirectHandle<Object> field_value = slot->GetValue();
    DCHECK_IMPLIES(IsHeapNumber(*field_value),
                   !IsSmiDouble(Object::NumberValue(*field_value)));
    WRITE_FIELD(*object_storage, offset, *field_value);
    WRITE_BARRIER(*object_storage, offset, *field_value);
  }
  object_storage->set_map(isolate(), *map, kReleaseStore);
}
References CHECK, CHECK_EQ, CHECK_GE, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::TranslatedValue::GetChildrenCount(), GetResolvedSlotAndAdvance(), v8::internal::TranslatedValue::GetValue(), GetValueAndAdvance(), v8::internal::handle(), v8::internal::Isolate::heap(), INDIRECT_POINTER_WRITE_BARRIER, v8::internal::IsNumber(), isolate(), v8::internal::IsSmiDouble(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kind(), v8::internal::kNo, v8::kReleaseStore, v8::internal::anonymous_namespace{translated-state.cc}::kStoreHeapObject, v8::internal::anonymous_namespace{translated-state.cc}::kStoreTagged, v8::internal::kTaggedSize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::NotifyObjectLayoutChange(), v8::internal::Object::NumberValue(), v8::internal::TranslatedValue::storage(), v8::internal::TranslatedValue::storage_, USE, v8::internal::value, WRITE_BARRIER, and WRITE_FIELD.
Referenced by InitializeCapturedObjectAt().
InitializeObjectAt()
Handle< HeapObject > v8::internal::TranslatedState::InitializeObjectAt (TranslatedValue * slot) [private]
Definition at line 2050 of file translated-state.cc.
                                                                            {
  DisallowGarbageCollection no_gc;
  slot = ResolveCapturedObject(slot);
  if (slot->materialization_state() != TranslatedValue::kFinished) {
    std::stack<int> worklist;
    worklist.push(slot->object_index());
    slot->mark_finished();
    while (!worklist.empty()) {
      int index = worklist.top();
      worklist.pop();
      InitializeCapturedObjectAt(index, &worklist, no_gc);
    }
  }
  return slot->storage();
}
References v8::internal::index, InitializeCapturedObjectAt(), v8::internal::TranslatedValue::kFinished, v8::internal::TranslatedValue::mark_finished(), v8::internal::TranslatedValue::materialization_state(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TranslatedValue::object_index(), ResolveCapturedObject(), and v8::internal::TranslatedValue::storage().
Referenced by v8::internal::TranslatedValue::GetValue().
InitializeObjectWithTaggedFieldsAt()
void v8::internal::TranslatedState::InitializeObjectWithTaggedFieldsAt (TranslatedFrame * frame, int * value_index, TranslatedValue * slot, DirectHandle< Map > map, const DisallowGarbageCollection & no_gc) [private]
Definition at line 2614 of file translated-state.cc.
                                                                   {
  auto object_storage = Cast<HeapObject>(slot->storage_);
  int children_count = slot->GetChildrenCount();
  // Skip the writes if we already have the canonical empty fixed array.
  if (*object_storage == ReadOnlyRoots(isolate()).empty_fixed_array()) {
    CHECK_EQ(2, children_count);
    DirectHandle<Object> length_value = GetValueAndAdvance(frame, value_index);
    CHECK_EQ(*length_value, Smi::FromInt(0));
    return;
  }
#if DEBUG
  // No need to invalidate slots in object because no slot was recorded yet.
  // Verify this here.
  Address object_start = object_storage->address();
  Address object_end = object_start + children_count * kTaggedSize;
  isolate()->heap()->VerifySlotRangeHasNoRecordedSlots(object_start,
                                                       object_end);
#endif // DEBUG
  // Notify the concurrent marker about the layout change.
  isolate()->heap()->NotifyObjectLayoutChange(
      *object_storage, no_gc, InvalidateRecordedSlots::kNo,
      InvalidateExternalPointerSlots::kNo);
  // Finish any sweeping so that it becomes safe to overwrite the ByteArray
  // headers. See chromium:1228036.
  isolate()->heap()->EnsureSweepingCompletedForObject(*object_storage);
  // Write the fields to the object.
  for (int i = 1; i < children_count; i++) {
    slot = GetResolvedSlotAndAdvance(frame, value_index);
    int offset = i * kTaggedSize;
    uint8_t marker = object_storage->ReadField<uint8_t>(offset);
    DirectHandle<Object> field_value;
    if (i > 1 && marker == kStoreHeapObject) {
      field_value = slot->storage();
    } else {
      CHECK(marker == kStoreTagged || i == 1);
      field_value = slot->GetValue();
      DCHECK_IMPLIES(IsHeapNumber(*field_value),
                     !IsSmiDouble(Object::NumberValue(*field_value)));
    }
    WRITE_FIELD(*object_storage, offset, *field_value);
    WRITE_BARRIER(*object_storage, offset, *field_value);
  }
  object_storage->set_map(isolate(), *map, kReleaseStore);
}
References CHECK, CHECK_EQ, DCHECK_IMPLIES, v8::internal::Heap::EnsureSweepingCompletedForObject(), v8::internal::Smi::FromInt(), v8::internal::TranslatedValue::GetChildrenCount(), GetResolvedSlotAndAdvance(), v8::internal::TranslatedValue::GetValue(), GetValueAndAdvance(), v8::internal::Isolate::heap(), isolate(), v8::internal::IsSmiDouble(), v8::internal::kNo, v8::kReleaseStore, v8::internal::anonymous_namespace{translated-state.cc}::kStoreHeapObject, v8::internal::anonymous_namespace{translated-state.cc}::kStoreTagged, v8::internal::kTaggedSize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::NotifyObjectLayoutChange(), v8::internal::Object::NumberValue(), v8::internal::TranslatedValue::storage(), v8::internal::TranslatedValue::storage_, WRITE_BARRIER, and WRITE_FIELD.
Referenced by InitializeCapturedObjectAt().
isolate()
Isolate* v8::internal::TranslatedState::isolate () [inline]
Definition at line 487 of file translated-state.h.
{ return isolate_; }
References isolate_.
Referenced by AllocateStorageFor(), DoUpdateFeedback(), EnsureCapturedObjectAllocatedAt(), EnsureJSObjectAllocated(), EnsurePropertiesAllocatedAndMarked(), Init(), InitializeJSObjectAt(), InitializeObjectWithTaggedFieldsAt(), v8::internal::TranslatedValue::isolate(), MaterializeFixedDoubleArray(), MaterializeHeapNumber(), Prepare(), ResolveStringConcat(), StoreMaterializedValuesAndDeopt(), and VerifyMaterializedObjects().
MaterializeFixedDoubleArray()
void v8::internal::TranslatedState::MaterializeFixedDoubleArray (TranslatedFrame * frame, int * value_index, TranslatedValue * slot, DirectHandle< Map > map) [private]
Definition at line 2178 of file translated-state.cc.
                                                                         {
  int length = frame->values_[*value_index].GetSmiValue();
  (*value_index)++;
  Handle<FixedDoubleArray> array =
      Cast<FixedDoubleArray>(isolate()->factory()->NewFixedDoubleArray(length));
  CHECK_GT(length, 0);
  for (int i = 0; i < length; i++) {
    CHECK_NE(TranslatedValue::kCapturedObject,
             frame->values_[*value_index].kind());
    DirectHandle<Object> value = frame->values_[*value_index].GetValue();
    if (IsNumber(*value)) {
      array->set(i, Object::NumberValue(*value));
    } else {
      CHECK(value.is_identical_to(isolate()->factory()->the_hole_value()));
      array->set_the_hole(isolate(), i);
    }
    (*value_index)++;
  }
  slot->set_storage(array);
}
References CHECK, CHECK_GT, CHECK_NE, v8::internal::IsNumber(), isolate(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::length, v8::internal::Object::NumberValue(), v8::internal::TranslatedValue::set_storage(), v8::internal::value, and v8::internal::TranslatedFrame::values_.
Referenced by EnsureCapturedObjectAllocatedAt().
MaterializeHeapNumber()
void v8::internal::TranslatedState::MaterializeHeapNumber (TranslatedFrame * frame, int * value_index, TranslatedValue * slot) [private]
Definition at line 2202 of file translated-state.cc.
                                                                   {
  CHECK_NE(TranslatedValue::kCapturedObject,
           frame->values_[*value_index].kind());
  DirectHandle<Object> value = frame->values_[*value_index].GetValue();
  CHECK(IsNumber(*value));
  Handle<HeapNumber> box =
      isolate()->factory()->NewHeapNumber(Object::NumberValue(*value));
  (*value_index)++;
  slot->set_storage(box);
}
References CHECK, CHECK_NE, v8::internal::Isolate::factory(), v8::internal::IsNumber(), isolate(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::Object::NumberValue(), v8::internal::TranslatedValue::set_storage(), v8::internal::value, and v8::internal::TranslatedFrame::values_.
Referenced by EnsureCapturedObjectAllocatedAt().
Prepare()
void v8::internal::TranslatedState::Prepare (Address stack_frame_pointer)
Definition at line 1993 of file translated-state.cc.
                                                         {
  for (auto& frame : frames_) {
    frame.Handlify(isolate());
  }
  if (!feedback_vector_.is_null()) {
    feedback_vector_handle_ = handle(feedback_vector_, isolate());
    feedback_vector_ = FeedbackVector();
  }
  stack_frame_pointer_ = stack_frame_pointer;
  UpdateFromPreviouslyMaterializedObjects();
}
References feedback_vector_, feedback_vector_handle_, frames_, v8::internal::handle(), isolate(), stack_frame_pointer_, and UpdateFromPreviouslyMaterializedObjects().
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::Deoptimizer::DebuggerInspectableFrame(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::FrameFunctionIterator::MaterializeFunction(), v8::internal::Deoptimizer::MaterializeHeapObjects(), and v8::internal::OptimizedJSFrame::Summarize().
ReadUpdateFeedback()
void v8::internal::TranslatedState::ReadUpdateFeedback (DeoptTranslationIterator * iterator, Tagged< DeoptimizationLiteralArray > literal_array, FILE * trace_file) [private]
Definition at line 2879 of file translated-state.cc.
                                                                        {
  CHECK_EQ(TranslationOpcode::UPDATE_FEEDBACK, iterator->NextOpcode());
  feedback_vector_ =
      Cast<FeedbackVector>(literal_array->get(iterator->NextOperand()));
  feedback_slot_ = FeedbackSlot(iterator->NextOperand());
  if (trace_file != nullptr) {
    PrintF(trace_file, " reading FeedbackVector (slot %d)\n",
           feedback_slot_.ToInt());
  }
}
References CHECK_EQ, feedback_slot_, feedback_vector_, v8::internal::PrintF(), and v8::internal::FeedbackSlot::ToInt().
Referenced by Init().
ResolveCapturedObject()
TranslatedValue * v8::internal::TranslatedState::ResolveCapturedObject (TranslatedValue * slot) [private]
Definition at line 2667 of file translated-state.cc.
                                                                             {
  while (slot->kind() == TranslatedValue::kDuplicatedObject) {
    slot = GetValueByObjectIndex(slot->object_index());
  }
  CHECK(slot->kind() == TranslatedValue::kCapturedObject ||
        slot->kind() == TranslatedValue::kCapturedStringConcat);
  return slot;
}
References CHECK, GetValueByObjectIndex(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kCapturedStringConcat, v8::internal::TranslatedValue::kDuplicatedObject, v8::internal::TranslatedValue::kind(), and v8::internal::TranslatedValue::object_index().
Referenced by EnsureChildrenAllocated(), EnsureObjectAllocatedAt(), GetResolvedSlot(), InitializeCapturedObjectAt(), and InitializeObjectAt().
ResolveStringConcat()
Handle< HeapObject > v8::internal::TranslatedState::ResolveStringConcat (TranslatedValue * slot) [private]
Definition at line 2013 of file translated-state.cc.
                                                                             {
  if (slot->materialization_state() == TranslatedValue::kFinished) {
    return slot->storage();
  }
  CHECK_EQ(TranslatedValue::kUninitialized, slot->materialization_state());
  int index = slot->object_index();
  TranslatedState::ObjectPosition pos = object_positions_[index];
  int value_index = pos.value_index_;
  TranslatedFrame* frame = &(frames_[pos.frame_index_]);
  CHECK_EQ(slot, &(frame->values_[value_index]));
  // TODO(dmercadier): try to avoid the recursive GetValue call.
  value_index++;
  TranslatedValue* left_slot = &(frame->values_[value_index]);
  Handle<Object> left = left_slot->GetValue();
  // Skipping the left input that we've just processed. Note that we can't just
  // do `value_index++`, because the left input could itself be a dematerialized
  // string concatenation, in which case it will occupy multiple slots.
  SkipSlots(1, frame, &value_index);
  TranslatedValue* right_slot = &(frame->values_[value_index]);
  Handle<Object> right = right_slot->GetValue();
  Handle<String> result =
      isolate()
          ->factory()
          ->NewConsString(Cast<String>(left), Cast<String>(right))
          .ToHandleChecked();
  slot->set_initialized_storage(result);
  return result;
}
References CHECK_EQ, v8::internal::Isolate::factory(), v8::internal::TranslatedState::ObjectPosition::frame_index_, frames_, v8::internal::TranslatedValue::GetValue(), v8::internal::index, isolate(), v8::internal::TranslatedValue::kFinished, v8::internal::TranslatedValue::kUninitialized, v8::internal::TranslatedValue::materialization_state(), v8::internal::FactoryBase< Impl >::NewConsString(), v8::internal::TranslatedValue::object_index(), object_positions_, v8::base::internal::result, v8::internal::TranslatedValue::set_initialized_storage(), SkipSlots(), v8::internal::TranslatedValue::storage(), v8::internal::TranslatedState::ObjectPosition::value_index_, and v8::internal::TranslatedFrame::values_.
Referenced by EnsureChildrenAllocated(), EnsureObjectAllocatedAt(), and v8::internal::TranslatedValue::GetValue().
SkipSlots()
void v8::internal::TranslatedState::SkipSlots (int slots_to_skip, TranslatedFrame * frame, int * value_index) [private]
Definition at line 2221 of file translated-state.cc.
                                                  {
  while (slots_to_skip > 0) {
    TranslatedValue* slot = &(frame->values_[*value_index]);
    (*value_index)++;
    slots_to_skip--;
    if (slot->kind() == TranslatedValue::kCapturedObject ||
        slot->kind() == TranslatedValue::kCapturedStringConcat) {
      slots_to_skip += slot->GetChildrenCount();
    }
  }
}
References v8::internal::TranslatedValue::GetChildrenCount(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kCapturedStringConcat, v8::internal::TranslatedValue::kind(), and v8::internal::TranslatedFrame::values_.
Referenced by EnsureChildrenAllocated(), GetResolvedSlotAndAdvance(), GetValueAndAdvance(), InitializeCapturedObjectAt(), and ResolveStringConcat().
StoreMaterializedValuesAndDeopt()
void v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt (JavaScriptFrame * frame)
Definition at line 2739 of file translated-state.cc.
                                                                            {
  MaterializedObjectStore* materialized_store =
      isolate_->materialized_object_store();
  DirectHandle<FixedArray> previously_materialized_objects =
      materialized_store->Get(stack_frame_pointer_);
  Handle<Object> marker = isolate_->factory()->arguments_marker();
  int length = static_cast<int>(object_positions_.size());
  bool new_store = false;
  if (previously_materialized_objects.is_null()) {
    previously_materialized_objects =
        isolate_->factory()->NewFixedArray(length, AllocationType::kOld);
    for (int i = 0; i < length; i++) {
      previously_materialized_objects->set(i, *marker);
    }
    new_store = true;
  }
  CHECK_EQ(length, previously_materialized_objects->length());
  bool value_changed = false;
  for (int i = 0; i < length; i++) {
    TranslatedState::ObjectPosition pos = object_positions_[i];
    TranslatedValue* value_info =
        &(frames_[pos.frame_index_].values_[pos.value_index_]);
    CHECK(value_info->IsMaterializedObject());
    // Skip duplicate objects (i.e., those that point to some other object id).
    if (value_info->object_index() != i) continue;
    DirectHandle<Object> previous_value(previously_materialized_objects->get(i),
                                        isolate_);
    DirectHandle<Object> value(value_info->GetRawValue(), isolate_);
    if (value.is_identical_to(marker)) {
      DCHECK_EQ(*previous_value, *marker);
    } else {
      if (*previous_value == *marker) {
        if (IsSmi(*value)) {
          value =
              isolate()->factory()->NewHeapNumber(Object::NumberValue(*value));
        }
        previously_materialized_objects->set(i, *value);
        value_changed = true;
      } else {
        CHECK(*previous_value == *value ||
              (IsHeapNumber(*previous_value) && IsSmi(*value) &&
               Object::NumberValue(*previous_value) ==
                   Object::NumberValue(*value)));
      }
    }
  }
  if (new_store && value_changed) {
    materialized_store->Set(stack_frame_pointer_,
                            previously_materialized_objects);
    CHECK_EQ(frames_[0].kind(), TranslatedFrame::kUnoptimizedFunction);
    CHECK_EQ(frame->function(), frames_[0].front().GetRawValue());
    Deoptimizer::DeoptimizeFunction(
        frame->function(), LazyDeoptimizeReason::kFrameValueMaterialized,
        frame->LookupCode());
  }
}
References CHECK, CHECK_EQ, DCHECK_EQ, v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::Isolate::factory(), v8::internal::TranslatedState::ObjectPosition::frame_index_, frames_, v8::internal::JavaScriptFrame::function(), v8::internal::MaterializedObjectStore::Get(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::DirectHandle< T >::is_null(), v8::internal::TranslatedValue::IsMaterializedObject(), isolate(), isolate_, v8::internal::IsSmi(), v8::internal::kOld, v8::internal::TranslatedFrame::kUnoptimizedFunction, v8::internal::length, v8::internal::StackFrame::LookupCode(), v8::internal::Isolate::materialized_object_store(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewHeapNumber(), v8::internal::Object::NumberValue(), v8::internal::TranslatedValue::object_index(), object_positions_, v8::internal::MaterializedObjectStore::Set(), stack_frame_pointer_, v8::internal::value, and v8::internal::TranslatedState::ObjectPosition::value_index_.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), and v8::internal::FrameFunctionIterator::MaterializeFunction().
UpdateFromPreviouslyMaterializedObjects()
void v8::internal::TranslatedState::UpdateFromPreviouslyMaterializedObjects () [private]
Definition at line 2805 of file translated-state.cc.
                                                              {
  MaterializedObjectStore* materialized_store =
      isolate_->materialized_object_store();
  DirectHandle<FixedArray> previously_materialized_objects =
      materialized_store->Get(stack_frame_pointer_);
  // If we have no previously materialized objects, there is nothing to do.
  if (previously_materialized_objects.is_null()) return;
  DirectHandle<Object> marker = isolate_->factory()->arguments_marker();
  int length = static_cast<int>(object_positions_.size());
  CHECK_EQ(length, previously_materialized_objects->length());
  for (int i = 0; i < length; i++) {
    // For a previously materialized objects, inject their value into the
    // translated values.
    if (previously_materialized_objects->get(i) != *marker) {
      TranslatedState::ObjectPosition pos = object_positions_[i];
      TranslatedValue* value_info =
          &(frames_[pos.frame_index_].values_[pos.value_index_]);
      CHECK(value_info->IsMaterializedObject());
      if (value_info->kind() == TranslatedValue::kCapturedObject ||
          value_info->kind() == TranslatedValue::kCapturedStringConcat) {
        Handle<Object> object(previously_materialized_objects->get(i),
                              isolate_);
        CHECK(IsHeapObject(*object));
        value_info->set_initialized_storage(Cast<HeapObject>(object));
      }
    }
  }
}
References CHECK, CHECK_EQ, v8::internal::Isolate::factory(), v8::internal::TranslatedState::ObjectPosition::frame_index_, frames_, v8::internal::MaterializedObjectStore::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::DirectHandle< T >::is_null(), v8::internal::IsHeapObject(), v8::internal::TranslatedValue::IsMaterializedObject(), isolate_, v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kCapturedStringConcat, v8::internal::TranslatedValue::kind(), v8::internal::length, v8::internal::Isolate::materialized_object_store(), object_positions_, v8::internal::TranslatedValue::set_initialized_storage(), stack_frame_pointer_, and v8::internal::TranslatedState::ObjectPosition::value_index_.
Referenced by Prepare().
VerifyMaterializedObjects()
void v8::internal::TranslatedState::VerifyMaterializedObjects ()
Definition at line 2839 of file translated-state.cc.
                                                {
#if VERIFY_HEAP
  if (!v8_flags.verify_heap) return;
  int length = static_cast<int>(object_positions_.size());
  for (int i = 0; i < length; i++) {
    TranslatedValue* slot = GetValueByObjectIndex(i);
    if (slot->kind() == TranslatedValue::kCapturedObject ||
        slot->kind() == TranslatedValue::kCapturedStringConcat) {
      CHECK_EQ(slot, GetValueByObjectIndex(slot->object_index()));
      if (slot->materialization_state() == TranslatedValue::kFinished) {
        Object::ObjectVerify(*slot->storage(), isolate());
      } else {
        CHECK_EQ(slot->materialization_state(),
                 TranslatedValue::kUninitialized);
      }
    }
  }
#endif
}
References CHECK_EQ, GetValueByObjectIndex(), isolate(), v8::internal::TranslatedValue::kCapturedObject, v8::internal::TranslatedValue::kCapturedStringConcat, v8::internal::TranslatedValue::kFinished, v8::internal::TranslatedValue::kind(), v8::internal::TranslatedValue::kUninitialized, v8::internal::length, v8::internal::TranslatedValue::materialization_state(), v8::internal::TranslatedValue::object_index(), object_positions_, v8::internal::TranslatedValue::storage(), and v8::internal::v8_flags.
Referenced by v8::internal::Deoptimizer::MaterializeHeapObjects().
Member Data Documentation
actual_argument_count_
int v8::internal::TranslatedState::actual_argument_count_ [private]
Definition at line 577 of file translated-state.h.
Referenced by CreateArgumentsElementsTranslatedValues(), CreateNextTranslatedValue(), and Init().
feedback_slot_
FeedbackSlot v8::internal::TranslatedState::feedback_slot_ [private]
Definition at line 586 of file translated-state.h.
Referenced by DoUpdateFeedback(), and ReadUpdateFeedback().
feedback_vector_
Tagged<FeedbackVector> v8::internal::TranslatedState::feedback_vector_ [private]
Definition at line 585 of file translated-state.h.
Referenced by Prepare(), and ReadUpdateFeedback().
feedback_vector_handle_
Handle<FeedbackVector> v8::internal::TranslatedState::feedback_vector_handle_ [private]
Definition at line 584 of file translated-state.h.
Referenced by DoUpdateFeedback(), and Prepare().
formal_parameter_count_
int v8::internal::TranslatedState::formal_parameter_count_ [private]
Definition at line 576 of file translated-state.h.
Referenced by CreateArgumentsElementsTranslatedValues(), CreateNextTranslatedValue(), and Init().
frames_
std::vector<TranslatedFrame> v8::internal::TranslatedState::frames_ [private]
Definition at line 573 of file translated-state.h.
Referenced by begin(), CreateArgumentsElementsTranslatedValues(), CreateNextTranslatedValue(), end(), EnsureCapturedObjectAllocatedAt(), frames(), GetArgumentsInfoFromJSFrameIndex(), GetFrameFromJSFrameIndex(), GetValueByObjectIndex(), Init(), InitializeCapturedObjectAt(), Prepare(), ResolveStringConcat(), StoreMaterializedValuesAndDeopt(), and UpdateFromPreviouslyMaterializedObjects().
isolate_
Isolate* v8::internal::TranslatedState::isolate_ = nullptr [private]
Definition at line 574 of file translated-state.h.
Referenced by CreateArgumentsElementsTranslatedValues(), CreateNextTranslatedValue(), Init(), isolate(), StoreMaterializedValuesAndDeopt(), and UpdateFromPreviouslyMaterializedObjects().
object_positions_
std::deque<ObjectPosition> v8::internal::TranslatedState::object_positions_ [private]
Definition at line 583 of file translated-state.h.
Referenced by CreateArgumentsElementsTranslatedValues(), CreateNextTranslatedValue(), EnsureCapturedObjectAllocatedAt(), GetValueByObjectIndex(), InitializeCapturedObjectAt(), ResolveStringConcat(), StoreMaterializedValuesAndDeopt(), UpdateFromPreviouslyMaterializedObjects(), and VerifyMaterializedObjects().
purpose_
Purpose const v8::internal::TranslatedState::purpose_ [private]
Definition at line 572 of file translated-state.h.
Referenced by EnsureCapturedObjectAllocatedAt().
stack_frame_pointer_
Address v8::internal::TranslatedState::stack_frame_pointer_ = kNullAddress [private]
Definition at line 575 of file translated-state.h.
Referenced by CreateArgumentsElementsTranslatedValues(), Init(), Prepare(), StoreMaterializedValuesAndDeopt(), and UpdateFromPreviouslyMaterializedObjects().
TranslatedValue
friend v8::internal::TranslatedState::TranslatedValue [private]
Definition at line 500 of file translated-state.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/translated-state.h
/mnt/V8SourceCode/src/deoptimizer/translated-state.cc