v8::internal::compiler::BranchParameters Class Reference
#include <common-operator.h>
Public Member Functions
BranchParameters (BranchSemantics semantics, BranchHint hint)
BranchSemantics semantics () const
BranchHint hint () const
Private Attributes
const BranchSemantics semantics_
const BranchHint hint_
Detailed Description
Definition at line 77 of file common-operator.h.
Constructor & Destructor Documentation
BranchParameters()
v8::internal::compiler::BranchParameters::BranchParameters (BranchSemantics semantics, BranchHint hint) [inline]
Definition at line 79 of file common-operator.h.
      : semantics_(semantics), hint_(hint) {}
Member Function Documentation
hint()
BranchHint v8::internal::compiler::BranchParameters::hint () const [inline]
Definition at line 83 of file common-operator.h.
{ return hint_; }
References hint_.
Referenced by v8::internal::compiler::BranchHintOf(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
semantics()
BranchSemantics v8::internal::compiler::BranchParameters::semantics () const [inline]
Definition at line 82 of file common-operator.h.
{ return semantics_; }
References semantics_.
Referenced by v8::internal::compiler::CommonOperatorReducer::BranchSemanticsOf(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
Member Data Documentation
hint_
const BranchHint v8::internal::compiler::BranchParameters::hint_ [private]
Definition at line 87 of file common-operator.h.
Referenced by hint().
semantics_
const BranchSemantics v8::internal::compiler::BranchParameters::semantics_ [private]
Definition at line 86 of file common-operator.h.
Referenced by semantics().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h