v8::internal::DataHandler::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 1360 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::DataHandler::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 1363 of file objects-body-descriptors-inl.h.
                                                                    {
    static_assert(
        offsetof(DataHandler, smi_handler_) < OFFSET_OF_DATA_START(DataHandler),
        "Field order must be in sync with this iteration code");
    IteratePointers(obj, offsetof(DataHandler, smi_handler_),
                    OFFSET_OF_DATA_START(DataHandler), v);
    IterateMaybeWeakPointers(obj, OFFSET_OF_DATA_START(DataHandler),
                             object_size, v);
  }
References v8::internal::BodyDescriptorBase::IterateMaybeWeakPointers(), v8::internal::BodyDescriptorBase::IteratePointers(), OFFSET_OF_DATA_START, and v8::internal::DataHandler::smi_handler_.
SizeOf()
static int v8::internal::DataHandler::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 1374 of file objects-body-descriptors-inl.h.
                                                                       {
    return object->SizeFromMap(map);
  }
References v8::internal::HeapObjectLayout::map().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h