v8::Name Class Reference
A superclass for symbols and strings.
#include <v8-primitive.h>
Public Member Functions
int GetIdentityHash ()
Returns the identity hash for this object.
Static Public Member Functions
static Name * Cast (Data *data)
Static Private Member Functions
static void CheckCast (Data *that)
Detailed Description
A superclass for symbols and strings.
Definition at line 79 of file v8-primitive.h.
Member Function Documentation
Cast()
static Name* v8::Name::Cast (Data * data) [inline], [static]
Definition at line 90 of file v8-primitive.h.
                                          {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Name*>(data);
  }
CheckCast()
void v8::Name::CheckCast (v8::Data * that) [static], [private]
Definition at line 3881 of file api.cc.
                                   {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsName(*obj), "v8::Name::Cast", "Value is not a Name");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
GetIdentityHash()
int v8::Name::GetIdentityHash ()
Returns the identity hash for this object.
The current implementation uses an inline property on the object to store the identity hash.
The return value will never be 0. Also, it is not guaranteed to be unique.
Definition at line 5555 of file api.cc.
                          {
  return static_cast<int>(Utils::OpenDirectHandle(this)->EnsureHash());
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc