v8::internal::SharedHeapDeserializer Class Reference
#include <shared-heap-deserializer.h>
Public Member Functions
SharedHeapDeserializer (Isolate *isolate, const SnapshotData *shared_heap_data, bool can_rehash)
void DeserializeIntoIsolate ()
Private Member Functions
void DeserializeStringTable ()
Additional Inherited Members
Detailed Description
Definition at line 16 of file shared-heap-deserializer.h.
Constructor & Destructor Documentation
SharedHeapDeserializer()
v8::internal::SharedHeapDeserializer::SharedHeapDeserializer (Isolate * isolate, const SnapshotData * shared_heap_data, bool can_rehash) [inline], [explicit]
Definition at line 18 of file shared-heap-deserializer.h.
      : Deserializer(isolate, shared_heap_data->Payload(),
                     shared_heap_data->GetMagicNumber(), false, can_rehash) {}
Member Function Documentation
DeserializeIntoIsolate()
void v8::internal::SharedHeapDeserializer::DeserializeIntoIsolate ()
Definition at line 12 of file shared-heap-deserializer.cc.
                                                    {
  // Don't deserialize into isolates that don't own their string table. If there
  // are client Isolates, the shared heap object cache should already be
  // populated.
  // TODO(372493838): The shared heap object cache can only contain strings.
  // Update name to reflect this.
  if (!isolate()->OwnsStringTables()) {
    DCHECK(!isolate()->shared_heap_object_cache()->empty());
    return;
  }
  DCHECK(isolate()->shared_heap_object_cache()->empty());
  HandleScope scope(isolate());
  IterateSharedHeapObjectCache(isolate(), this);
  DeserializeStringTable();
  DeserializeDeferredObjects();
  if (should_rehash()) {
    // The hash seed has already been initialized in ReadOnlyDeserializer, thus
    // there is no need to call `isolate()->heap()->InitializeHashSeed();`.
    Rehash();
  }
}
References v8::internal::DCHECK(), v8::internal::Deserializer< Isolate >::DeserializeDeferredObjects(), DeserializeStringTable(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::SerializerDeserializer::IterateSharedHeapObjectCache(), v8::internal::Deserializer< Isolate >::Rehash(), and v8::internal::Deserializer< Isolate >::should_rehash().
Referenced by v8::internal::Isolate::Init().
DeserializeStringTable()
void v8::internal::SharedHeapDeserializer::DeserializeStringTable () [private]
Definition at line 37 of file shared-heap-deserializer.cc.
                                                    {
  // See SharedHeapSerializer::SerializeStringTable.
  DCHECK(isolate()->OwnsStringTables());
  // Get the string table size.
  const int length = source()->GetUint30();
  // .. and the contents.
  DirectHandleVector<String> strings(isolate());
  strings.reserve(length);
  for (int i = 0; i < length; ++i) {
    strings.emplace_back(Cast<String>(ReadObject()));
  }
  StringTable* t = isolate()->string_table();
  DCHECK_EQ(t->NumberOfElements(), 0);
  t->InsertForIsolateDeserialization(
      isolate(), base::VectorOf(strings.data(), strings.size()));
  DCHECK_EQ(t->NumberOfElements(), length);
}
References v8::internal::DirectHandleVector< T >::data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DirectHandleVector< T >::emplace_back(), v8::internal::SnapshotByteSource::GetUint30(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::StringTable::InsertForIsolateDeserialization(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::length, v8::internal::StringTable::NumberOfElements(), v8::internal::Deserializer< Isolate >::ReadObject(), v8::internal::DirectHandleVector< T >::reserve(), v8::internal::DirectHandleVector< T >::size(), v8::internal::Deserializer< Isolate >::source(), v8::internal::Isolate::string_table(), and v8::base::VectorOf().
Referenced by DeserializeIntoIsolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/shared-heap-deserializer.h
/mnt/V8SourceCode/src/snapshot/shared-heap-deserializer.cc