v8::internal::compiler::turboshaft::WasmRevecReducer< Next > Class Template Reference
#include <wasm-revec-reducer.h>
Public Types
using Adapter = UniformReducerAdapter< WasmRevecReducer, Next >
Public Member Functions
OpIndex GetExtractOpIfNeeded (const PackNode *pnode, OpIndex ig_index, OpIndex og_index)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Constant (V< Simd128 > ig_index, const Simd128ConstantOp &constant_op)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128LoadTransform (V< Simd128 > ig_index, const Simd128LoadTransformOp &load_transform)
OpIndex REDUCE_INPUT_GRAPH() Load (OpIndex ig_index, const LoadOp &load)
OpIndex REDUCE_INPUT_GRAPH() Store (OpIndex ig_index, const StoreOp &store)
OpIndex REDUCE_INPUT_GRAPH() Phi (OpIndex ig_index, const PhiOp &phi)
void FixLoopPhi (const PhiOp &input_phi, OpIndex output_index, Block *output_graph_loop)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Unary (V< Simd128 > ig_index, const Simd128UnaryOp &unary)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Binop (V< Simd128 > ig_index, const Simd128BinopOp &op)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Shift (V< Simd128 > ig_index, const Simd128ShiftOp &op)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Ternary (V< Simd128 > ig_index, const Simd128TernaryOp &ternary)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Splat (V< Simd128 > ig_index, const Simd128SplatOp &op)
V< Simd128 > REDUCE_INPUT_GRAPH() Simd128Shuffle (V< Simd128 > ig_index, const Simd128ShuffleOp &op)
OpIndex REDUCE_INPUT_GRAPH() Simd128ReplaceLane (OpIndex ig_index, const Simd128ReplaceLaneOp &replace)
void ReduceInputsOfOp (OpIndex cur_index, OpIndex op_index)
template<typename Op , typename Continuation >
void ReduceForceOrIntersectPackNode (PackNode *pnode, const OpIndex ig_index, OpIndex *og_index)
template<typename Op , typename Continuation >
OpIndex ReduceInputGraphOperation (OpIndex ig_index, const Op &op)
Static Private Member Functions
static Simd256UnaryOp::Kind GetSimd256UnaryKind (Simd128UnaryOp::Kind simd128_kind)
static Simd256BinopOp::Kind GetSimd256BinOpKind (Simd128BinopOp::Kind kind)
static Simd256ShiftOp::Kind GetSimd256ShiftOpKind (Simd128ShiftOp::Kind kind)
static Simd256TernaryOp::Kind GetSimd256TernaryKind (Simd128TernaryOp::Kind simd128_kind)
static Simd256LoadTransformOp::TransformKind Get256LoadTransformKindFrom128 (Simd128LoadTransformOp::TransformKind simd128_kind)
static Simd256SplatOp::Kind Get256SplatOpKindFrom128 (Simd128SplatOp::Kind kind)
Private Attributes
const wasm::WasmModule * module_ = __ data() -> wasm_module()
WasmRevecAnalyzer analyzer_ = *__ data() -> wasm_revec_analyzer()
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::WasmRevecReducer< Next >
Definition at line 660 of file wasm-revec-reducer.h.
Member Typedef Documentation
Adapter
template<class Next >
using v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Adapter = UniformReducerAdapter<WasmRevecReducer, Next>
Definition at line 663 of file wasm-revec-reducer.h.
Member Function Documentation
FixLoopPhi()
template<class Next >
void v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi (const PhiOp & input_phi, OpIndex output_index, Block * output_graph_loop) [inline]
Definition at line 854 of file wasm-revec-reducer.h.
                                            {
    if (input_phi.rep == RegisterRepresentation::Simd128()) {
      OpIndex phi_index = __ input_graph().Index(input_phi);
      DCHECK(phi_index.valid());
      if (auto* pnode = analyzer_.GetPackNode(phi_index)) {
        auto pending_index = pnode->RevectorizedNode();
        DCHECK(pending_index.valid());
        if (pending_index.valid() &&
            output_graph_loop->Contains(pending_index)) {
          // Need skip replaced op
          if (auto* pending_phi = __ output_graph()
                                      .Get(pending_index)
                                      .template TryCast<PendingLoopPhiOp>()) {
            __ output_graph().template Replace<PhiOp>(
                pending_index,
                base::VectorOf({pending_phi -> first(),
                                analyzer_.GetReducedInput(pnode, 1)}),
                RegisterRepresentation::Simd256());
            return;
          }
        }
      }
    }
    return Adapter::FixLoopPhi(input_phi, output_index, output_graph_loop);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::Block::Contains(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::PhiOp::rep, v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::base::VectorOf().
Get256LoadTransformKindFrom128()
template<class Next >
static Simd256LoadTransformOp::TransformKind v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Get256LoadTransformKindFrom128 (Simd128LoadTransformOp::TransformKind simd128_kind) [inline], [static], [private]
Definition at line 1350 of file wasm-revec-reducer.h.
                                                        {
    switch (simd128_kind) {
#define TRANSFORM_KIND_MAPPING(from, to) \
  case Simd128LoadTransformOp::TransformKind::k##from: \
    return Simd256LoadTransformOp::TransformKind::k##to;
      SIMD256_LOADTRANSFORM_OP(TRANSFORM_KIND_MAPPING)
#undef TRANSFORM_KIND_MAPPING
      default:
        UNREACHABLE();
    }
  }
References SIMD256_LOADTRANSFORM_OP, TRANSFORM_KIND_MAPPING, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform().
Get256SplatOpKindFrom128()
template<class Next >
static Simd256SplatOp::Kind v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Get256SplatOpKindFrom128 (Simd128SplatOp::Kind kind) [inline], [static], [private]
Definition at line 1363 of file wasm-revec-reducer.h.
                               {
    switch (kind) {
#define SPLAT_KIND_MAPPING(from, to) \
  case Simd128SplatOp::Kind::k##from: \
    return Simd256SplatOp::Kind::k##to;
      SIMD256_SPLAT_OP(SPLAT_KIND_MAPPING)
      default:
        UNREACHABLE();
    }
  }
References SIMD256_SPLAT_OP, SPLAT_KIND_MAPPING, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat().
GetExtractOpIfNeeded()
template<class Next >
OpIndex v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded (const PackNode * pnode, OpIndex ig_index, OpIndex og_index) [inline]
Definition at line 665 of file wasm-revec-reducer.h.
                                                 {
    if (__ template MapToNewGraph<true>(ig_index).valid()) {
      // The op is already emitted during emitting force pack node input trees.
      return OpIndex::Invalid();
    }
    const auto lane = base::checked_cast<uint8_t>(
        std::find(pnode->nodes().begin(), pnode->nodes().end(), ig_index) -
        pnode->nodes().begin());
    // Force PackNode has a dedicated use in SimdPack128To256Op.
    if (pnode->is_force_packing()) {
      SimdPack128To256Op& op = __ output_graph()
                                   .Get(pnode -> RevectorizedNode())
                                   .template Cast<SimdPack128To256Op>();
      return lane == 0 ? op.left() : op.right();
    }
    for (auto use : analyzer_.uses(ig_index)) {
      // Extract128 is needed for the additional Simd128 store before
      // Simd256 store in case of OOB trap at the higher 128-bit
      // address.
      auto use_pnode = analyzer_.GetPackNode(use);
      if (use_pnode != nullptr && !use_pnode->is_force_packing()) {
        DCHECK_GE(use_pnode->nodes().size(), 2);
        if (__ input_graph().Get(use).opcode != Opcode::kStore ||
            use_pnode->nodes()[0] != use ||
            use_pnode->nodes()[0] > use_pnode->nodes()[1])
          continue;
      }
      return __ Simd256Extract128Lane(og_index, lane);
    }
    return OpIndex::Invalid();
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, DCHECK_GE, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), use(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::uses().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary().
GetSimd256BinOpKind()
template<class Next >
static Simd256BinopOp::Kind v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256BinOpKind (Simd128BinopOp::Kind kind) [inline], [static], [private]
Definition at line 1305 of file wasm-revec-reducer.h.
                                                                         {
    switch (kind) {
#define BINOP_KIND_MAPPING(from, to) \
  case Simd128BinopOp::Kind::k##from: \
    return Simd256BinopOp::Kind::k##to;
      SIMD256_BINOP_SIMPLE_OP(BINOP_KIND_MAPPING)
#undef BINOP_KIND_MAPPING
#define SIGN_EXTENSION_BINOP_KIND_MAPPING(from_1, to, from_2) \
  case Simd128BinopOp::Kind::k##from_1: \
    return Simd256BinopOp::Kind::k##to; \
  case Simd128BinopOp::Kind::k##from_2: \
    return Simd256BinopOp::Kind::k##to;
      SIMD256_BINOP_SIGN_EXTENSION_OP(SIGN_EXTENSION_BINOP_KIND_MAPPING)
#undef SIGN_EXTENSION_UNOP_KIND_MAPPING
      default:
        UNIMPLEMENTED();
    }
  }
References BINOP_KIND_MAPPING, SIGN_EXTENSION_BINOP_KIND_MAPPING, SIMD256_BINOP_SIGN_EXTENSION_OP, SIMD256_BINOP_SIMPLE_OP, and v8::internal::compiler::UNIMPLEMENTED().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop().
GetSimd256ShiftOpKind()
template<class Next >
static Simd256ShiftOp::Kind v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256ShiftOpKind (Simd128ShiftOp::Kind kind) [inline], [static], [private]
Definition at line 1325 of file wasm-revec-reducer.h.
                                                                           {
    switch (kind) {
#define SHIFT_KIND_MAPPING(from, to) \
  case Simd128ShiftOp::Kind::k##from: \
    return Simd256ShiftOp::Kind::k##to;
      SIMD256_SHIFT_OP(SHIFT_KIND_MAPPING)
#undef SHIFT_KIND_MAPPING
      default:
        UNIMPLEMENTED();
    }
  }
References SHIFT_KIND_MAPPING, SIMD256_SHIFT_OP, and v8::internal::compiler::UNIMPLEMENTED().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift().
GetSimd256TernaryKind()
template<class Next >
static Simd256TernaryOp::Kind v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256TernaryKind (Simd128TernaryOp::Kind simd128_kind) [inline], [static], [private]
Definition at line 1337 of file wasm-revec-reducer.h.
                                         {
    switch (simd128_kind) {
#define TERNARY_KIND_MAPPING(from, to) \
  case Simd128TernaryOp::Kind::k##from: \
    return Simd256TernaryOp::Kind::k##to;
      SIMD256_TERNARY_OP(TERNARY_KIND_MAPPING)
#undef TERNARY_KIND_MAPPING
      default:
        UNIMPLEMENTED();
    }
  }
References SIMD256_TERNARY_OP, TERNARY_KIND_MAPPING, and v8::internal::compiler::UNIMPLEMENTED().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary().
GetSimd256UnaryKind()
template<class Next >
static Simd256UnaryOp::Kind v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256UnaryKind (Simd128UnaryOp::Kind simd128_kind) [inline], [static], [private]
Definition at line 1284 of file wasm-revec-reducer.h.
                                       {
    switch (simd128_kind) {
#define UNOP_KIND_MAPPING(from, to) \
  case Simd128UnaryOp::Kind::k##from: \
    return Simd256UnaryOp::Kind::k##to;
      SIMD256_UNARY_SIMPLE_OP(UNOP_KIND_MAPPING)
#undef UNOP_KIND_MAPPING
#define SIGN_EXTENSION_UNOP_KIND_MAPPING(from_1, to, from_2) \
  case Simd128UnaryOp::Kind::k##from_1: \
    return Simd256UnaryOp::Kind::k##to; \
  case Simd128UnaryOp::Kind::k##from_2: \
    return Simd256UnaryOp::Kind::k##to;
      SIMD256_UNARY_SIGN_EXTENSION_OP(SIGN_EXTENSION_UNOP_KIND_MAPPING)
#undef SIGN_EXTENSION_UNOP_KIND_MAPPING
      default:
        UNIMPLEMENTED();
    }
  }
References SIGN_EXTENSION_UNOP_KIND_MAPPING, SIMD256_UNARY_SIGN_EXTENSION_OP, SIMD256_UNARY_SIMPLE_OP, v8::internal::compiler::UNIMPLEMENTED(), and UNOP_KIND_MAPPING.
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary().
Load()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load (OpIndex ig_index, const LoadOp & load) [inline]
Definition at line 753 of file wasm-revec-reducer.h.
                                                                         {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode || !pnode->IsDefaultPackNode()) {
      return Adapter::ReduceInputGraphLoad(ig_index, load);
    }
    OpIndex og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      const LoadOp& start = analyzer_.GetStartOperation(pnode, ig_index, load)
                                .template Cast<LoadOp>();
      DCHECK_EQ(start.base(), load.base());
      auto base = __ MapToNewGraph(load.base());
      // We need to use load's index here due to there would be different
      // ChangeOps from the same index. If start is not load, it's possible
      // that the ChangeOp of start index is not visited yet.
      auto index = __ MapToNewGraph(load.index());
      og_index = __ Load(base, index, load.kind,
                         MemoryRepresentation::Simd256(), start.offset);
      pnode->SetRevectorizedNode(og_index);
    }
    // Emit extract op if needed.
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::LoadOp::base(), DCHECK_EQ, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetStartOperation(), v8::internal::index, v8::internal::compiler::turboshaft::PackNode::IsDefaultPackNode(), v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Phi()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi (OpIndex ig_index, const PhiOp & phi) [inline]
Definition at line 821 of file wasm-revec-reducer.h.
                                                                      {
    if (phi.rep == RegisterRepresentation::Simd128()) {
      if (auto pnode = analyzer_.GetPackNode(ig_index)) {
        OpIndex og_index = pnode->RevectorizedNode();
        // Don't reduce revectorized node.
        if (!og_index.valid()) {
          base::SmallVector<OpIndex, 16> elements;
          og_index = __ ResolvePhi(
              phi,
              [&](OpIndex ind, int block_id, int old_block_id = 0) {
                return analyzer_.GetReducedInput(pnode, old_block_id);
              },
              RegisterRepresentation::Simd256());
          pnode->SetRevectorizedNode(og_index);
        }
        OpIndex extract_op_index =
            GetExtractOpIfNeeded(pnode, ig_index, og_index);
        // If phis are not be mapped to anything in the new graph,
        // they will be skipped in FixLoopPhis in copying-phase.
        // return og_index to create the mapping.
        if (extract_op_index == OpIndex::Invalid()) {
          return og_index;
        } else {
          return extract_op_index;
        }
      }
    }
    return Adapter::ReduceInputGraphPhi(ig_index, phi);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Simd256(), and v8::internal::compiler::turboshaft::OpIndex::valid().
ReduceForceOrIntersectPackNode()
template<class Next >
template<typename Op , typename Continuation >
void v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceForceOrIntersectPackNode (PackNode * pnode, const OpIndex ig_index, OpIndex * og_index) [inline]
Definition at line 1190 of file wasm-revec-reducer.h.
                                                         {
    std::array<OpIndex, 2> v;
    DCHECK_EQ(pnode->nodes().size(), 2);
    // The operation order in pnode is determined by the store or reduce
    // seed when build the SLPTree. It is not quaranteed to align with
    // the visiting order in each basic block from input graph. E.g. we
    // can have a block including {a1, a2, b1, b2} operations, and the
    // SLPTree can be pnode1: (a2, a1), pnode2: (b1, b2) if a2 is input
    // of b1, and a1 is input of b2.
    for (int i = 0; i < static_cast<int>(pnode->nodes().size()); i++) {
      OpIndex cur_index = pnode->nodes()[i];
      if ((*og_index).valid() && cur_index == ig_index) {
        v[i] = *og_index;
      } else {
        // The current index maybe already reduced by the IntersectPackNode.
        v[i] = __ template MapToNewGraph<true>(cur_index);
      }
      if (v[i].valid()) continue;
      if (cur_index != ig_index) {
        ReduceInputsOfOp(ig_index, cur_index);
      }
      const Op& op = Asm().input_graph().Get(cur_index).template Cast<Op>();
      v[i] = Continuation{this}.ReduceInputGraph(cur_index, op);
      if (cur_index == ig_index) {
        *og_index = v[i];
      } else {
        // We have to create the mapping as cur_index may exist in other
        // IntersectPackNode and reduce again.
        __ CreateOldToNewMapping(cur_index, v[i]);
      }
    }
    OpIndex revec_index = __ SimdPack128To256(v[0], v[1]);
    pnode->SetRevectorizedNode(revec_index);
  }
References __, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::PackNode::nodes(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputsOfOp(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::NodeGroup::size().
ReduceInputGraphOperation()
template<class Next >
template<typename Op , typename Continuation >
OpIndex v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation (OpIndex ig_index, const Op & op) [inline]
Definition at line 1231 of file wasm-revec-reducer.h.
                                                                    {
    OpIndex og_index;
    // Reduce ForcePackNode
    if (PackNode* p = analyzer_.GetPackNode(ig_index);
        p && p->IsForcePackNode()) {
      // Handle force packing nodes.
      ForcePackNode* pnode = p->AsForcePackNode();
      if (!pnode->RevectorizedNode().valid()) {
        switch (pnode->force_pack_type()) {
          case ForcePackNode::kSplat: {
            // The og_index maybe already reduced by the IntersectPackNode.
            OpIndex reduced_index = __ template MapToNewGraph<true>(ig_index);
            if (!reduced_index.valid()) {
              og_index = reduced_index =
                  Continuation{this}.ReduceInputGraph(ig_index, op);
            }
            OpIndex revec_index =
                __ SimdPack128To256(reduced_index, reduced_index);
            pnode->SetRevectorizedNode(revec_index);
            break;
          }
          case ForcePackNode::kGeneral: {
            ReduceForceOrIntersectPackNode<Op, Continuation>(pnode, ig_index,
                                                             &og_index);
            break;
          }
        }
      }
    }
    // Reduce IntersectPackNode
    if (auto intersect_packnodes = analyzer_.GetIntersectPackNodes(ig_index)) {
      for (PackNode* pnode : *intersect_packnodes) {
        if (!(pnode->RevectorizedNode()).valid()) {
          ReduceForceOrIntersectPackNode<Op, Continuation>(pnode, ig_index,
                                                           &og_index);
        }
      }
    }
    if (og_index.valid()) {
      return og_index;
    }
    if (__ template MapToNewGraph<true>(ig_index).valid()) {
      // The op is already emitted during emitting force pack node input trees.
      return OpIndex::Invalid();
    }
    return Continuation{this}.ReduceInputGraph(ig_index, op);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::PackNode::AsForcePackNode(), v8::internal::compiler::turboshaft::ForcePackNode::force_pack_type(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetIntersectPackNodes(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::PackNode::IsForcePackNode(), v8::internal::compiler::turboshaft::ForcePackNode::kGeneral, v8::internal::compiler::turboshaft::ForcePackNode::kSplat, v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
ReduceInputsOfOp()
template<class Next >
void v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputsOfOp (OpIndex cur_index, OpIndex op_index) [inline]
Definition at line 1151 of file wasm-revec-reducer.h.
                                                             {
    // Reduce all the operations of op_index's input tree, which should be
    // bigger than the cur_index. The traversal is done in a DFS manner
    // to make sure all inputs are emitted before the use.
    const Block* current_input_block = Asm().current_input_block();
    std::stack<OpIndex> inputs;
    ZoneUnorderedSet<OpIndex> visited(Asm().phase_zone());
    inputs.push(op_index);
    while (!inputs.empty()) {
      OpIndex idx = inputs.top();
      if (visited.find(idx) != visited.end()) {
        inputs.pop();
        continue;
      }
      const Operation& op = __ input_graph().Get(idx);
      bool has_unvisited_inputs = false;
      for (OpIndex input : op.inputs()) {
        if (input > cur_index && visited.find(input) == visited.end()) {
          inputs.push(input);
          has_unvisited_inputs = true;
        }
      }
      if (!has_unvisited_inputs) {
        inputs.pop();
        visited.insert(idx);
        // op_index will be reduced later.
        if (idx == op_index) continue;
        DCHECK(!Asm().input_graph().Get(idx).template Is<PhiOp>());
        Asm().template VisitOpAndUpdateMapping<false>(idx, current_input_block);
      }
    }
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Get(), and v8::internal::compiler::turboshaft::Operation::inputs().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceForceOrIntersectPackNode().
Simd128Binop()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop (V< Simd128 > ig_index, const Simd128BinopOp & op) [inline]
Definition at line 904 of file wasm-revec-reducer.h.
                                                                        {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode || !pnode->IsDefaultPackNode()) {
      return Adapter::ReduceInputGraphSimd128Binop(ig_index, op);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      if (pnode->GetOperandsSize() < 2) {
        V<Simd128> left = __ MapToNewGraph(op.left());
        V<Simd128> right = __ MapToNewGraph(op.right());
        og_index = __ Simd256Binop(left, right, GetSimd256BinOpKind(op.kind));
      } else {
        V<Simd256> left = analyzer_.GetReducedInput(pnode, 0);
        V<Simd256> right = analyzer_.GetReducedInput(pnode, 1);
        og_index = __ Simd256Binop(left, right, GetSimd256BinOpKind(op.kind));
      }
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::PackNode::GetOperandsSize(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256BinOpKind(), v8::internal::compiler::turboshaft::PackNode::IsDefaultPackNode(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Simd128Constant()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant (V< Simd128 > ig_index, const Simd128ConstantOp & constant_op) [inline]
Definition at line 702 of file wasm-revec-reducer.h.
                                                                 {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode) {
      return Adapter::ReduceInputGraphSimd128Constant(ig_index, constant_op);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      NodeGroup inputs = pnode->nodes();
      const Simd128ConstantOp& op0 =
          __ input_graph().Get(inputs[0]).template Cast<Simd128ConstantOp>();
      const Simd128ConstantOp& op1 =
          __ input_graph().Get(inputs[1]).template Cast<Simd128ConstantOp>();
      uint8_t value[kSimd256Size] = {};
      memcpy(value, op0.value, kSimd128Size);
      memcpy(value + kSimd128Size, op1.value, kSimd128Size);
      og_index = __ Simd256Constant(value);
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::kSimd128Size, v8::internal::kSimd256Size, v8::internal::compiler::turboshaft::PackNode::nodes(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::value.
Simd128LoadTransform()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform (V< Simd128 > ig_index, const Simd128LoadTransformOp & load_transform) [inline]
Definition at line 728 of file wasm-revec-reducer.h.
                                                                         {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode || !pnode->IsDefaultPackNode()) {
      return Adapter::ReduceInputGraphSimd128LoadTransform(ig_index,
                                                           load_transform);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      auto base = __ MapToNewGraph(load_transform.base());
      auto index = __ MapToNewGraph(load_transform.index());
      auto offset = load_transform.offset;
      DCHECK_EQ(load_transform.offset, 0);
      og_index = __ Simd256LoadTransform(
          base, index, load_transform.load_kind,
          Get256LoadTransformKindFrom128(load_transform.transform_kind),
          offset);
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, DCHECK_EQ, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Get256LoadTransformKindFrom128(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::index, v8::internal::compiler::turboshaft::PackNode::IsDefaultPackNode(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Simd128ReplaceLane()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane (OpIndex ig_index, const Simd128ReplaceLaneOp & replace) [inline]
Definition at line 1096 of file wasm-revec-reducer.h.
                                                             {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode || !pnode->IsBundlePackNode()) {
      return Adapter::ReduceInputGraphSimd128ReplaceLane(ig_index, replace);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Don't reduce revectorized node.
    if (!og_index.valid()) {
      const BundlePackNode* bundle_pnode = pnode->AsBundlePackNode();
      V<Simd128> base_index = __ MapToNewGraph(bundle_pnode->base());
      V<Simd128> i16x8_index = base_index;
      V<Simd256> i32x8_index;
      if (bundle_pnode->is_sign_extract()) {
        if (bundle_pnode->lane_size() == 1) {
          if (bundle_pnode->offset() == 0) {
            i16x8_index = __ Simd128Unary(
                base_index, Simd128UnaryOp::Kind::kI16x8SConvertI8x16Low);
          } else {
            DCHECK_EQ(bundle_pnode->offset(), 8);
            i16x8_index = __ Simd128Unary(
                base_index, Simd128UnaryOp::Kind::kI16x8SConvertI8x16High);
          }
        }
        i32x8_index = __ Simd256Unary(
            i16x8_index, Simd256UnaryOp::Kind::kI32x8SConvertI16x8);
      } else {
        if (bundle_pnode->lane_size() == 1) {
          if (bundle_pnode->offset() == 0) {
            i16x8_index = __ Simd128Unary(
                base_index, Simd128UnaryOp::Kind::kI16x8UConvertI8x16Low);
          } else {
            DCHECK_EQ(bundle_pnode->offset(), 8);
            i16x8_index = __ Simd128Unary(
                base_index, Simd128UnaryOp::Kind::kI16x8UConvertI8x16High);
          }
        }
        i32x8_index = __ Simd256Unary(
            i16x8_index, Simd256UnaryOp::Kind::kI32x8UConvertI16x8);
      }
      if (bundle_pnode->is_sign_convert()) {
        og_index = __ Simd256Unary(i32x8_index,
                                   Simd256UnaryOp::Kind::kF32x8SConvertI32x8);
      } else {
        og_index = __ Simd256Unary(i32x8_index,
                                   Simd256UnaryOp::Kind::kF32x8UConvertI32x8);
      }
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::PackNode::AsBundlePackNode(), v8::internal::compiler::turboshaft::BundlePackNode::base(), DCHECK_EQ, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::BundlePackNode::is_sign_convert(), v8::internal::compiler::turboshaft::BundlePackNode::is_sign_extract(), v8::internal::compiler::turboshaft::PackNode::IsBundlePackNode(), v8::internal::compiler::turboshaft::BundlePackNode::lane_size(), v8::internal::compiler::turboshaft::BundlePackNode::offset(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Simd128Shift()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift (V< Simd128 > ig_index, const Simd128ShiftOp & op) [inline]
Definition at line 928 of file wasm-revec-reducer.h.
                                                                        {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode) {
      return Adapter::ReduceInputGraphSimd128Shift(ig_index, op);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      V<Simd256> input = analyzer_.GetReducedInput(pnode);
      DCHECK(input.valid());
      V<Word32> shift = __ MapToNewGraph(op.shift());
      og_index = __ Simd256Shift(input, shift, GetSimd256ShiftOpKind(op.kind));
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256ShiftOpKind(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Simd128Shuffle()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle (V< Simd128 > ig_index, const Simd128ShuffleOp & op) [inline]
Definition at line 987 of file wasm-revec-reducer.h.
                                                                            {
    PackNode* p = analyzer_.GetPackNode(ig_index);
    if (!p) {
      return Adapter::ReduceInputGraphSimd128Shuffle(ig_index, op);
    }
    DCHECK_EQ(op.kind, Simd128ShuffleOp::Kind::kI8x16);
    ShufflePackNode* pnode = p->AsShufflePackNode();
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      const ShufflePackNode::SpecificInfo::Kind kind = pnode->info().kind();
      switch (kind) {
        case ShufflePackNode::SpecificInfo::Kind::kS256Load32Transform:
        case ShufflePackNode::SpecificInfo::Kind::kS256Load64Transform: {
          const bool is_32 =
              kind == ShufflePackNode::SpecificInfo::Kind::kS256Load32Transform;
          const OpIndex load_index =
              op.input(pnode->info().splat_index() >> (is_32 ? 2 : 1));
          const LoadOp& load =
              __ input_graph().Get(load_index).template Cast<LoadOp>();
          const int bytes_per_lane = is_32 ? 4 : 8;
          const int splat_index = pnode->info().splat_index() * bytes_per_lane;
          const int offset = splat_index + load.offset;
          V<WordPtr> base = __ WordPtrAdd(__ MapToNewGraph(load.base()),
                                          __ IntPtrConstant(offset));
          V<WordPtr> index = load.index().has_value()
                                 ? __ MapToNewGraph(load.index().value())
                                 : __ IntPtrConstant(0);
          const Simd256LoadTransformOp::TransformKind transform_kind =
              is_32 ? Simd256LoadTransformOp::TransformKind::k32Splat
                    : Simd256LoadTransformOp::TransformKind::k64Splat;
          og_index = __ Simd256LoadTransform(base, index, load.kind,
                                             transform_kind, 0);
          pnode->SetRevectorizedNode(og_index);
          break;
        }
        case ShufflePackNode::SpecificInfo::Kind::kS256Load8x8U: {
          const Simd128ShuffleOp& op0 = __ input_graph()
                                            .Get(pnode -> nodes()[0])
                                            .template Cast<Simd128ShuffleOp>();
          V<Simd128> load_transform_idx =
              __ input_graph()
                      .Get(op0.left())
                      .template Is<Simd128LoadTransformOp>()
                  ? op0.left()
                  : op0.right();
          const Simd128LoadTransformOp& load_transform =
              __ input_graph()
                  .Get(load_transform_idx)
                  .template Cast<Simd128LoadTransformOp>();
          DCHECK_EQ(load_transform.transform_kind,
                    Simd128LoadTransformOp::TransformKind::k64Zero);
          V<WordPtr> base = __ MapToNewGraph(load_transform.base());
          V<WordPtr> index = __ MapToNewGraph(load_transform.index());
          og_index = __ Simd256LoadTransform(
              base, index, load_transform.load_kind,
              Simd256LoadTransformOp::TransformKind::k8x8U,
              load_transform.offset);
          pnode->SetRevectorizedNode(og_index);
          break;
        }
#ifdef V8_TARGET_ARCH_X64
        case ShufflePackNode::SpecificInfo::Kind::kShufd: {
          V<Simd256> og_left = analyzer_.GetReducedInput(pnode, 0);
          DCHECK_EQ(og_left, analyzer_.GetReducedInput(pnode, 1));
          og_index = __ Simd256Shufd(og_left, pnode->info().shufd_control());
          pnode->SetRevectorizedNode(og_index);
          break;
        }
        case ShufflePackNode::SpecificInfo::Kind::kShufps: {
          V<Simd256> og_left = analyzer_.GetReducedInput(pnode, 0);
          V<Simd256> og_right = analyzer_.GetReducedInput(pnode, 1);
          og_index = __ Simd256Shufps(og_left, og_right,
                                      pnode->info().shufps_control());
          pnode->SetRevectorizedNode(og_index);
          break;
        }
        case ShufflePackNode::SpecificInfo::Kind::kS32x8UnpackLow: {
          V<Simd256> og_left = analyzer_.GetReducedInput(pnode, 0);
          V<Simd256> og_right = analyzer_.GetReducedInput(pnode, 1);
          og_index = __ Simd256Unpack(og_left, og_right,
                                      Simd256UnpackOp::Kind::k32x8Low);
          pnode->SetRevectorizedNode(og_index);
          break;
        }
        case ShufflePackNode::SpecificInfo::Kind::kS32x8UnpackHigh: {
          V<Simd256> og_left = analyzer_.GetReducedInput(pnode, 0);
          V<Simd256> og_right = analyzer_.GetReducedInput(pnode, 1);
          og_index = __ Simd256Unpack(og_left, og_right,
                                      Simd256UnpackOp::Kind::k32x8High);
          pnode->SetRevectorizedNode(og_index);
          break;
        }
#endif // V8_TARGET_ARCH_X64
        default:
          UNREACHABLE();
      }
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::PackNode::AsShufflePackNode(), v8::internal::compiler::turboshaft::LoadOp::base(), DCHECK_EQ, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::index, v8::internal::compiler::turboshaft::ShufflePackNode::info(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::LoadOp::kind, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kind(), v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kS256Load32Transform, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kS256Load64Transform, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kS256Load8x8U, v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::splat_index(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Simd128Splat()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat (V< Simd128 > ig_index, const Simd128SplatOp & op) [inline]
Definition at line 969 of file wasm-revec-reducer.h.
                                                                        {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode) {
      return Adapter::ReduceInputGraphSimd128Splat(ig_index, op);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      og_index = __ Simd256Splat(__ MapToNewGraph(op.input()),
                                 Get256SplatOpKindFrom128(op.kind));
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Get256SplatOpKindFrom128(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Simd128Ternary()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary (V< Simd128 > ig_index, const Simd128TernaryOp & ternary) [inline]
Definition at line 947 of file wasm-revec-reducer.h.
                                                            {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode) {
      return Adapter::ReduceInputGraphSimd128Ternary(ig_index, ternary);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      V<Simd256> first = analyzer_.GetReducedInput(pnode, 0);
      V<Simd256> second = analyzer_.GetReducedInput(pnode, 1);
      V<Simd256> third = analyzer_.GetReducedInput(pnode, 2);
      og_index = __ Simd256Ternary(first, second, third,
                                   GetSimd256TernaryKind(ternary.kind));
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256TernaryKind(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Simd128Unary()
template<class Next >
V<Simd128> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary (V< Simd128 > ig_index, const Simd128UnaryOp & unary) [inline]
Definition at line 882 of file wasm-revec-reducer.h.
                                                                           {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode || !pnode->IsDefaultPackNode()) {
      return Adapter::ReduceInputGraphSimd128Unary(ig_index, unary);
    }
    V<Simd256> og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      V<Simd256> input = analyzer_.GetReducedInput(pnode);
      if (!input.valid()) {
        V<Simd128> input_128 = __ MapToNewGraph(unary.input());
        og_index = __ Simd256Unary(input_128, GetSimd256UnaryKind(unary.kind));
      } else {
        og_index = __ Simd256Unary(input, GetSimd256UnaryKind(unary.kind));
      }
      pnode->SetRevectorizedNode(og_index);
    }
    return GetExtractOpIfNeeded(pnode, ig_index, og_index);
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetSimd256UnaryKind(), v8::internal::compiler::turboshaft::PackNode::IsDefaultPackNode(), v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane().
Store()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store (OpIndex ig_index, const StoreOp & store) [inline]
Definition at line 780 of file wasm-revec-reducer.h.
                                                                            {
    PackNode* pnode = analyzer_.GetPackNode(ig_index);
    if (!pnode) {
      return Adapter::ReduceInputGraphStore(ig_index, store);
    }
    OpIndex og_index = pnode->RevectorizedNode();
    // Skip revectorized node.
    if (!og_index.valid()) {
      const StoreOp& start =
          (analyzer_.GetStartOperation(pnode, ig_index, store))
              .template Cast<StoreOp>();
      DCHECK_EQ(start.base(), store.base());
      // It's possible that an OOB is trapped at the higher 128-bit address
      // after the lower 128-bit store is executed. To ensure a consistent
      // memory state before and after revectorization, emit the first 128-bit
      // store before the 256-bit revectorized store.
      if (ig_index == pnode->nodes()[0]) {
        Adapter::ReduceInputGraphStore(ig_index, store);
      }
      auto base = __ MapToNewGraph(store.base());
      // We need to use store's index here due to there would be different
      // ChangeOps from the same index. If start is not store, it's possible
      // that the ChangeOp of start index is not visited yet.
      auto index = __ MapToNewGraph(store.index());
      V<Simd256> value = analyzer_.GetReducedInput(pnode);
      DCHECK(value.valid());
      __ Store(base, index, value, store.kind, MemoryRepresentation::Simd256(),
               store.write_barrier, start.offset);
      // Set an arbitrary valid opindex here to skip reduce later.
      pnode->SetRevectorizedNode(ig_index);
    }
    // No extract op needed for Store.
    return OpIndex::Invalid();
  }
References __, v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::StoreOp::base(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetReducedInput(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetStartOperation(), v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::PackNode::nodes(), v8::internal::compiler::turboshaft::StoreOp::offset, v8::internal::compiler::turboshaft::PackNode::RevectorizedNode(), v8::internal::compiler::turboshaft::PackNode::SetRevectorizedNode(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd256(), store(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::value.
Member Data Documentation
analyzer_
template<class Next >
WasmRevecAnalyzer v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::analyzer_ = *__ data() -> wasm_revec_analyzer() [private]
Definition at line 1376 of file wasm-revec-reducer.h.
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::FixLoopPhi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::GetExtractOpIfNeeded(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Load(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Phi(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::ReduceInputGraphOperation(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Binop(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Constant(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128LoadTransform(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shift(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Ternary(), v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Unary(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Store().
module_
template<class Next >
const wasm::WasmModule* v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::module_ = __ data() -> wasm_module() [private]
Definition at line 1375 of file wasm-revec-reducer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/copying-phase.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h