v8::internal::compiler::turboshaft::StringView Class Reference
#include <string-view.h>
Public Types
using value_type = V< Word32 >
using iterator_type = V< WordPtr >
Public Member Functions
StringView (const DisallowGarbageCollection &can_rely_on_no_gc, V< String > string, String::Encoding encoding, ConstOrV< WordPtr > start_index=0, ConstOrV< WordPtr > character_count=V< WordPtr >::Invalid())
StringView (V< String > string, String::Encoding encoding, ConstOrV< WordPtr > start_index=0, ConstOrV< WordPtr > character_count=V< WordPtr >::Invalid())
template<typename A >
iterator_type Begin (A &assembler)
template<typename A >
OptionalV< Word32 > IsEnd (A &assembler, iterator_type current_iterator) const
template<typename A >
iterator_type Advance (A &assembler, iterator_type current_iterator) const
template<typename A >
value_type Dereference (A &assembler, iterator_type current_iterator) const
Private Attributes
V< String > string_
String::Encoding encoding_
ConstOrV< WordPtr > start_index_
ConstOrV< WordPtr > character_count_
V< WordPtr > end_offset_
const DisallowGarbageCollection * can_rely_on_no_gc_
Detailed Description
Definition at line 14 of file string-view.h.
Member Typedef Documentation
iterator_type
using v8::internal::compiler::turboshaft::StringView::iterator_type = V<WordPtr>
Definition at line 17 of file string-view.h.
value_type
using v8::internal::compiler::turboshaft::StringView::value_type = V<Word32>
Definition at line 16 of file string-view.h.
Constructor & Destructor Documentation
StringView() [1/2]
v8::internal::compiler::turboshaft::StringView::StringView (const DisallowGarbageCollection & can_rely_on_no_gc, V< String > string, String::Encoding encoding, ConstOrV< WordPtr > start_index = 0, ConstOrV< WordPtr > character_count = V<WordPtr>::Invalid()) [inline]
Definition at line 19 of file string-view.h.
      : string_(string),
        encoding_(encoding),
        start_index_(start_index),
        character_count_(character_count),
        can_rely_on_no_gc_(&can_rely_on_no_gc) {}
StringView() [2/2]
v8::internal::compiler::turboshaft::StringView::StringView (V< String > string, String::Encoding encoding, ConstOrV< WordPtr > start_index = 0, ConstOrV< WordPtr > character_count = V<WordPtr>::Invalid()) [inline]
Definition at line 29 of file string-view.h.
      : string_(string),
        encoding_(encoding),
        start_index_(start_index),
        character_count_(character_count),
        can_rely_on_no_gc_(nullptr) {}
Member Function Documentation
Advance()
template<typename A >
iterator_type v8::internal::compiler::turboshaft::StringView::Advance (A & assembler, iterator_type current_iterator) const [inline]
Definition at line 75 of file string-view.h.
                                                                            {
    const int stride = (encoding_ == String::ONE_BYTE_ENCODING ? 1 : 2);
    return assembler.WordPtrAdd(current_iterator, stride);
  }
References encoding_, v8::internal::String::ONE_BYTE_ENCODING, and v8::internal::anonymous_namespace{json-stringifier.cc}::stride.
Begin()
template<typename A >
iterator_type v8::internal::compiler::turboshaft::StringView::Begin (A & assembler) [inline]
Definition at line 39 of file string-view.h.
                                    {
    static_assert(OFFSET_OF_DATA_START(SeqOneByteString) ==
                  OFFSET_OF_DATA_START(SeqTwoByteString));
    const size_t data_offset = OFFSET_OF_DATA_START(SeqOneByteString);
    const int stride = (encoding_ == String::ONE_BYTE_ENCODING ? 1 : 2);
    if (can_rely_on_no_gc_ == nullptr) {
      // TODO(nicohartmann): If we cannot rely on no GC happening during
      // iteration, we cannot operate on raw inner pointers but have to
      // recompute the character address from the base on each dereferencing.
      UNIMPLEMENTED();
    }
    V<WordPtr> begin_offset = assembler.WordPtrAdd(
        assembler.BitcastTaggedToWordPtr(string_),
        assembler.WordPtrAdd(
            data_offset - kHeapObjectTag,
            assembler.WordPtrMul(assembler.resolve(start_index_), stride)));
    V<WordPtr> count;
    if (character_count_.is_constant()) {
      count = assembler.resolve(character_count_);
    } else if (character_count_.value().valid()) {
      count = character_count_.value();
    } else {
      // TODO(nicohartmann): Load from string.
      UNIMPLEMENTED();
    }
    end_offset_ =
        assembler.WordPtrAdd(begin_offset, assembler.WordPtrMul(count, stride));
    return begin_offset;
  }
References can_rely_on_no_gc_, character_count_, encoding_, end_offset_, v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), v8::internal::kHeapObjectTag, OFFSET_OF_DATA_START, v8::internal::String::ONE_BYTE_ENCODING, start_index_, v8::internal::anonymous_namespace{json-stringifier.cc}::stride, string_, v8::internal::compiler::UNIMPLEMENTED(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
Dereference()
template<typename A >
value_type v8::internal::compiler::turboshaft::StringView::Dereference (A & assembler, iterator_type current_iterator) const [inline]
Definition at line 81 of file string-view.h.
                                                                             {
    const auto loaded_rep = encoding_ == String::ONE_BYTE_ENCODING
                                ? MemoryRepresentation::Uint8()
                                : MemoryRepresentation::Uint16();
    return assembler.Load(current_iterator, LoadOp::Kind::RawAligned(),
                          loaded_rep);
  }
References encoding_, v8::internal::String::ONE_BYTE_ENCODING, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), and v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8().
IsEnd()
template<typename A >
OptionalV<Word32> v8::internal::compiler::turboshaft::StringView::IsEnd (A & assembler, iterator_type current_iterator) const [inline]
Definition at line 70 of file string-view.h.
                                                                              {
    return assembler.UintPtrLessThanOrEqual(end_offset_, current_iterator);
  }
References end_offset_.
Member Data Documentation
can_rely_on_no_gc_
const DisallowGarbageCollection* v8::internal::compiler::turboshaft::StringView::can_rely_on_no_gc_ [private]
Definition at line 95 of file string-view.h.
Referenced by Begin().
character_count_
ConstOrV<WordPtr> v8::internal::compiler::turboshaft::StringView::character_count_ [private]
Definition at line 93 of file string-view.h.
Referenced by Begin().
encoding_
String::Encoding v8::internal::compiler::turboshaft::StringView::encoding_ [private]
Definition at line 91 of file string-view.h.
Referenced by Advance(), Begin(), and Dereference().
end_offset_
V<WordPtr> v8::internal::compiler::turboshaft::StringView::end_offset_ [private]
Definition at line 94 of file string-view.h.
Referenced by Begin(), and IsEnd().
start_index_
ConstOrV<WordPtr> v8::internal::compiler::turboshaft::StringView::start_index_ [private]
Definition at line 92 of file string-view.h.
Referenced by Begin().
string_
V<String> v8::internal::compiler::turboshaft::StringView::string_ [private]
Definition at line 90 of file string-view.h.
Referenced by Begin().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/string-view.h