v8::internal::KeyedHasICWithVectorDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned(), MachineType::AnyTagged()) static const expr inline Register VectorRegister()
Static Public Member Functions
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1470 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::KeyedHasICWithVectorDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned() , MachineType::AnyTagged()) const
registers()
constexpr auto v8::internal::KeyedHasICWithVectorDescriptor::registers () [static], [constexpr]
Definition at line 686 of file interface-descriptors-inl.h.
                                                         {
  return RegisterArray(KeyedHasICBaselineDescriptor::ReceiverRegister(),
                       KeyedHasICBaselineDescriptor::NameRegister(),
                       KeyedHasICBaselineDescriptor::SlotRegister(),
                       VectorRegister());
}
References v8::internal::KeyedHasICBaselineDescriptor::NameRegister(), v8::internal::RegisterArray(), and v8::internal::KeyedHasICBaselineDescriptor::SlotRegister().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h