v8::internal::Intl Class Reference
#include <intl-objects.h>
Classes
class AvailableLocales
class FormatRangeSourceTracker
struct NumberFormatDigitOptions
struct ResolvedLocale
struct SkipResourceCheck
Public Types
enum class BoundFunctionContextSlot { kBoundFunction = Context::MIN_CONTEXT_SLOTS
, kLength
 }
enum class FormatRangeSource { kShared
, kStartRange
, kEndRange
 }
enum class CompareStringsOptions { kNone
, kTryFastPath
 }
enum class RoundingPriority { kAuto
, kMorePrecision
, kLessPrecision
 }
enum class RoundingType { kFractionDigits
, kSignificantDigits
, kMorePrecision
, kLessPrecision
 }
enum class RoundingMode {
kCeil
, kFloor
, kExpand
, kTrunc
,
kHalfCeil
, kHalfFloor
, kHalfExpand
, kHalfTrunc
,
kHalfEven
 }
enum class TrailingZeroDisplay { kAuto
, kStripIfInteger
 }
enum class MatcherOption { kBestFit
, kLookup
 }
enum class Transition { kNext
, kPrevious
 }
Public Member Functions
template<class IsolateT >
Intl::CompareStringsOptions CompareStringsOptionsFor (IsolateT *isolate, DirectHandle< Object > locales, DirectHandle< Object > options)
Static Public Member Functions
static DirectHandle< String > SourceString (Isolate *isolate, FormatRangeSource source)
static std::set< std::string > BuildLocaleSet (const std::vector< std::string > &locales, const char *path, const char *validate_key)
static Maybe< std::string > ToLanguageTag (const icu::Locale &locale)
static Maybe< std::string > ValidateAndCanonicalizeUnicodeLocaleId (Isolate *isolate, std::string_view locale)
static std::string GetNumberingSystem (const icu::Locale &icu_locale)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSObject > SupportedLocalesOf (Isolate *isolate, const char *method_name, const std::set< std::string > &available_locales, DirectHandle< Object > locales_in, DirectHandle< Object > options_in)
static Maybe< std::vector< std::string > > CanonicalizeLocaleList (Isolate *isolate, DirectHandle< Object > locales, bool only_return_one_result=false)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > GetCanonicalLocales (Isolate *isolate, DirectHandle< Object > locales)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > SupportedValuesOf (Isolate *isolate, DirectHandle< Object > key)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > StringLocaleConvertCase (Isolate *isolate, DirectHandle< String > s, bool is_upper, DirectHandle< Object > locales)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ConvertToUpper (Isolate *isolate, DirectHandle< String > s)
static V8_WARN_UNUSED_RESULT MaybeHandle< String > ConvertToLower (Isolate *isolate, DirectHandle< String > s)
static V8_WARN_UNUSED_RESULT std::optional< int > StringLocaleCompare (Isolate *isolate, DirectHandle< String > s1, DirectHandle< String > s2, DirectHandle< Object > locales, DirectHandle< Object > options, const char *method_name)
template<class IsolateT >
static V8_EXPORT_PRIVATE CompareStringsOptions CompareStringsOptionsFor (IsolateT *isolate, DirectHandle< Object > locales, DirectHandle< Object > options)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT int CompareStrings (Isolate *isolate, const icu::Collator &collator, DirectHandle< String > s1, DirectHandle< String > s2, CompareStringsOptions compare_strings_options=CompareStringsOptions::kNone)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > NumberToLocaleString (Isolate *isolate, Handle< Object > num, DirectHandle< Object > locales, DirectHandle< Object > options, const char *method_name)
static V8_WARN_UNUSED_RESULT Maybe< NumberFormatDigitOptions > SetNumberFormatDigitOptions (Isolate *isolate, DirectHandle< JSReceiver > options, int mnfd_default, int mxfd_default, bool notation_is_compact, const char *service)
static V8_WARN_UNUSED_RESULT MaybeHandle< String > ToString (Isolate *isolate, const icu::UnicodeString &string)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ToString (Isolate *isolate, const icu::UnicodeString &string, int32_t begin, int32_t end)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > FormattedToString (Isolate *isolate, const icu::FormattedValue &formatted)
static DirectHandle< String > NumberFieldToType (Isolate *isolate, const NumberFormatSpan &part, const icu::UnicodeString &text, bool is_nan)
static void AddElement (Isolate *isolate, DirectHandle< JSArray > array, int index, DirectHandle< String > field_type_string, DirectHandle< String > value)
static void AddElement (Isolate *isolate, DirectHandle< JSArray > array, int index, DirectHandle< String > field_type_string, DirectHandle< String > value, DirectHandle< String > additional_property_name, DirectHandle< String > additional_property_value)
static Maybe< int > AddNumberElements (Isolate *isolate, const icu::FormattedValue &formatted, DirectHandle< JSArray > result, int start_index, DirectHandle< String > unit)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > LegacyUnwrapReceiver (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< JSFunction > constructor, bool has_initialized_slot)
static V8_WARN_UNUSED_RESULT Maybe< MatcherOption > GetLocaleMatcher (Isolate *isolate, DirectHandle< JSReceiver > options, const char *method_name)
static V8_WARN_UNUSED_RESULT Maybe< bool > GetNumberingSystem (Isolate *isolate, DirectHandle< JSReceiver > options, const char *method_name, std::string &result)
static bool IsValidCalendar (const icu::Locale &locale, const std::string &value)
static bool IsValidCollation (const icu::Locale &locale, const std::string &value)
static bool IsValidNumberingSystem (const std::string &value)
static bool IsWellFormedCalendar (std::string_view value)
static bool IsWellFormedCurrency (std::string_view value)
static Maybe< ResolvedLocale > ResolveLocale (Isolate *isolate, const std::set< std::string > &available_locales, const std::vector< std::string > &requested_locales, MatcherOption options, const std::set< std::string > &relevant_extension_keys)
static DirectHandle< Managed< icu::UnicodeString > > SetTextToBreakIterator (Isolate *isolate, DirectHandle< String > text, icu::BreakIterator *break_iterator)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > Normalize (Isolate *isolate, DirectHandle< String > string, DirectHandle< Object > form_input)
static base::TimezoneCache * CreateTimeZoneCache ()
static icu::UnicodeString ToICUUnicodeString (Isolate *isolate, DirectHandle< String > string, int offset=0)
static const uint8_t * ToLatin1LowerTable ()
static const uint8_t * AsciiCollationWeightsL1 ()
static const uint8_t * AsciiCollationWeightsL3 ()
static Tagged< String > ConvertOneByteToLower (Tagged< String > src, Tagged< String > dst)
static const std::set< std::string > & GetAvailableLocales ()
static const std::set< std::string > & GetAvailableLocalesForDateFormat ()
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > ToJSArray (Isolate *isolate, const char *unicode_key, icu::StringEnumeration *enumeration, const std::function< bool(const char *)> &removes, bool sort)
static bool RemoveCollation (const char *collation)
static std::set< std::string > SanctionedSimpleUnits ()
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > AvailableCalendars (Isolate *isolate)
static V8_WARN_UNUSED_RESULT bool IsValidTimeZoneName (const icu::TimeZone &tz)
static V8_WARN_UNUSED_RESULT bool IsValidTimeZoneName (Isolate *isolate, const std::string &id)
static V8_WARN_UNUSED_RESULT bool IsValidTimeZoneName (Isolate *isolate, DirectHandle< String > id)
static V8_WARN_UNUSED_RESULT std::string TimeZoneIdFromIndex (int32_t index)
static int32_t GetTimeZoneIndex (Isolate *isolate, DirectHandle< String > identifier)
static DirectHandle< Object > GetTimeZoneOffsetTransitionNanoseconds (Isolate *isolate, int32_t time_zone_index, DirectHandle< BigInt > nanosecond_epoch, Transition transition)
static int64_t GetTimeZoneOffsetNanoseconds (Isolate *isolate, int32_t time_zone_index, DirectHandle< BigInt > nanosecond_epoch)
static DirectHandleVector< BigInt > GetTimeZonePossibleOffsetNanoseconds (Isolate *isolate, int32_t time_zone_index, DirectHandle< BigInt > nanosecond_epoch)
static DirectHandle< String > DefaultTimeZone (Isolate *isolate)
static V8_WARN_UNUSED_RESULT MaybeHandle< String > CanonicalizeTimeZoneName (Isolate *isolate, DirectHandle< String > identifier)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > CoerceOptionsToObject (Isolate *isolate, DirectHandle< Object > options, const char *service)
Static Public Attributes
static const int kAsciiCollationWeightsLength = kCollationWeightsLength
Detailed Description
Definition at line 76 of file intl-objects.h.
Member Enumeration Documentation
BoundFunctionContextSlot
enum v8::internal::Intl::BoundFunctionContextSlot [strong]
Enumerator
kBoundFunction
kLength
Definition at line 78 of file intl-objects.h.
                                      {
    kBoundFunction = Context::MIN_CONTEXT_SLOTS,
    kLength
  };
CompareStringsOptions
enum v8::internal::Intl::CompareStringsOptions [strong]
Enumerator
kNone
kTryFastPath
Definition at line 159 of file intl-objects.h.
                                   {
    kNone,
    kTryFastPath,
  };
FormatRangeSource
enum v8::internal::Intl::FormatRangeSource [strong]
Enumerator
kShared
kStartRange
kEndRange
Definition at line 83 of file intl-objects.h.
{ kShared, kStartRange, kEndRange };
MatcherOption
enum v8::internal::Intl::MatcherOption [strong]
Enumerator
kBestFit
kLookup
Definition at line 293 of file intl-objects.h.
{ kBestFit, kLookup };
RoundingMode
enum v8::internal::Intl::RoundingMode [strong]
Enumerator
kCeil
kFloor
kExpand
kTrunc
kHalfCeil
kHalfFloor
kHalfExpand
kHalfTrunc
kHalfEven
Definition at line 196 of file intl-objects.h.
                          {
    kCeil,
    kFloor,
    kExpand,
    kTrunc,
    kHalfCeil,
    kHalfFloor,
    kHalfExpand,
    kHalfTrunc,
    kHalfEven,
  };
RoundingPriority
enum v8::internal::Intl::RoundingPriority [strong]
Enumerator
kAuto
kMorePrecision
kLessPrecision
Definition at line 180 of file intl-objects.h.
                              {
    kAuto,
    kMorePrecision,
    kLessPrecision,
  };
RoundingType
enum v8::internal::Intl::RoundingType [strong]
Enumerator
kFractionDigits
kSignificantDigits
kMorePrecision
kLessPrecision
Definition at line 186 of file intl-objects.h.
                          {
    kFractionDigits,
    kSignificantDigits,
    kMorePrecision,
    kLessPrecision,
  };
TrailingZeroDisplay
enum v8::internal::Intl::TrailingZeroDisplay [strong]
Enumerator
kAuto
kStripIfInteger
Definition at line 211 of file intl-objects.h.
                                 {
    kAuto,
    kStripIfInteger,
  };
Transition
enum v8::internal::Intl::Transition [strong]
Enumerator
kNext
kPrevious
Definition at line 432 of file intl-objects.h.
{ kNext, kPrevious };
Member Function Documentation
AddElement() [1/2]
void v8::internal::Intl::AddElement (Isolate * isolate, DirectHandle< JSArray > array, int index, DirectHandle< String > field_type_string, DirectHandle< String > value) [static]
Definition at line 546 of file intl-objects.cc.
                                                  {
  // Same as $array[$index] = {type: $field_type_string, value: $value};
  InnerAddElement(isolate, array, index, field_type_string, value);
}
References v8::internal::index, v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddLiteral(), v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddUnit(), v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FieldPositionIteratorToArray(), v8::internal::anonymous_namespace{js-list-format.cc}::FormattedListToJSArray(), and v8::internal::FormattedListToJSArray().
AddElement() [2/2]
void v8::internal::Intl::AddElement (Isolate * isolate, DirectHandle< JSArray > array, int index, DirectHandle< String > field_type_string, DirectHandle< String > value, DirectHandle< String > additional_property_name, DirectHandle< String > additional_property_value) [static]
Definition at line 553 of file intl-objects.cc.
                                                                      {
  // Same as $array[$index] = {
  // type: $field_type_string, value: $value,
  // $additional_property_name: $additional_property_value
  // }
  DirectHandle<JSObject> element =
      InnerAddElement(isolate, array, index, field_type_string, value);
  JSObject::AddProperty(isolate, element, additional_property_name,
                        additional_property_value, NONE);
}
References v8::internal::JSObject::AddProperty(), v8::internal::index, v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement(), v8::internal::NONE, and v8::internal::value.
AddNumberElements()
Maybe< int > v8::internal::Intl::AddNumberElements (Isolate * isolate, const icu::FormattedValue & formatted, DirectHandle< JSArray > result, int start_index, DirectHandle< String > unit) [static]
Definition at line 2009 of file js-number-format.cc.
                                                                               {
  return ConstructParts(isolate, formatted, result, start_index, true, false,
                        false, true, unit);
}
References v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), and v8::base::internal::result.
Referenced by v8::internal::FormattedListToJSArray().
AsciiCollationWeightsL1()
const uint8_t * v8::internal::Intl::AsciiCollationWeightsL1 () [static]
Definition at line 1437 of file intl-objects.cc.
                                             {
  return &kCollationWeightsL1[0];
}
References v8::internal::anonymous_namespace{intl-objects.cc}::kCollationWeightsL1.
AsciiCollationWeightsL3()
const uint8_t * v8::internal::Intl::AsciiCollationWeightsL3 () [static]
Definition at line 1442 of file intl-objects.cc.
                                             {
  return &kCollationWeightsL3[0];
}
References v8::internal::anonymous_namespace{intl-objects.cc}::kCollationWeightsL3.
AvailableCalendars()
MaybeDirectHandle< JSArray > v8::internal::Intl::AvailableCalendars (Isolate * isolate) [static]
Definition at line 558 of file js-locale.cc.
                                                                    {
  icu::Locale icu_locale("und");
  return CalendarsForLocale(isolate, icu_locale, false, true);
}
References v8::internal::anonymous_namespace{js-locale.cc}::CalendarsForLocale().
Referenced by SupportedValuesOf().
BuildLocaleSet()
std::set< std::string > v8::internal::Intl::BuildLocaleSet (const std::vector< std::string > & locales, const char * path, const char * validate_key) [static]
Definition at line 624 of file intl-objects.cc.
                              {
  std::set<std::string> locales;
  for (const std::string& locale : icu_available_locales) {
    if (path != nullptr || validate_key != nullptr) {
      if (!ValidateResource(icu::Locale(locale.c_str()), path, validate_key)) {
        // FIXME(chromium:1215606) Find a better fix for nb->no fallback
        if (locale != "nb") {
          continue;
        }
        // Try no for nb
        if (!ValidateResource(icu::Locale("no"), path, validate_key)) {
          continue;
        }
      }
    }
    locales.insert(locale);
    std::string shortened_locale;
    if (RemoveLocaleScriptTag(locale, &shortened_locale)) {
      std::replace(shortened_locale.begin(), shortened_locale.end(), '_', '-');
      locales.insert(shortened_locale);
    }
  }
  return locales;
}
References v8::internal::anonymous_namespace{intl-objects.cc}::RemoveLocaleScriptTag(), v8::internal::string, and v8::internal::anonymous_namespace{intl-objects.cc}::ValidateResource().
Referenced by v8::internal::Intl::AvailableLocales< C >::AvailableLocales(), and v8::internal::anonymous_namespace{js-collator.cc}::CollatorAvailableLocales::CollatorAvailableLocales().
CanonicalizeLocaleList()
Maybe< std::vector< std::string > > v8::internal::Intl::CanonicalizeLocaleList (Isolate * isolate, DirectHandle< Object > locales, bool only_return_one_result = false) [static]
Definition at line 808 of file intl-objects.cc.
                                 {
  // 1. If locales is undefined, then
  if (IsUndefined(*locales, isolate)) {
    // 1a. Return a new empty List.
    return Just(std::vector<std::string>());
  }
  // 2. Let seen be a new empty List.
  std::vector<std::string> seen;
  // 3. If Type(locales) is String or locales has an [[InitializedLocale]]
  // internal slot, then
  if (IsJSLocale(*locales)) {
    // Since this value came from JSLocale, which is already went though the
    // CanonializeLanguageTag process once, therefore there are no need to
    // call CanonializeLanguageTag again.
    seen.push_back(JSLocale::ToString(Cast<JSLocale>(locales)));
    return Just(seen);
  }
  if (IsString(*locales)) {
    // 3a. Let O be CreateArrayFromList(locales).
    // Instead of creating a one-element array and then iterating over it,
    // we inline the body of the iteration:
    std::string canonicalized_tag;
    if (!CanonicalizeLanguageTag(isolate, locales).To(&canonicalized_tag)) {
      return Nothing<std::vector<std::string>>();
    }
    seen.push_back(canonicalized_tag);
    return Just(seen);
  }
  // 4. Else,
  // 4a. Let O be ? ToObject(locales).
  DirectHandle<JSReceiver> o;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, o,
                                   Object::ToObject(isolate, locales),
                                   Nothing<std::vector<std::string>>());
  // 5. Let len be ? ToLength(? Get(O, "length")).
  DirectHandle<Object> length_obj;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, length_obj,
                                   Object::GetLengthFromArrayLike(isolate, o),
                                   Nothing<std::vector<std::string>>());
  // TODO(jkummerow): Spec violation: strictly speaking, we have to iterate
  // up to 2^53-1 if {length_obj} says so. Since cases above 2^32 probably
  // don't happen in practice (and would be very slow if they do), we'll keep
  // the code simple for now by using a saturating to-uint32 conversion.
  double raw_length = Object::NumberValue(*length_obj);
  uint32_t len =
      raw_length >= kMaxUInt32 ? kMaxUInt32 : static_cast<uint32_t>(raw_length);
  // 6. Let k be 0.
  // 7. Repeat, while k < len
  for (uint32_t k = 0; k < len; k++) {
    // 7a. Let Pk be ToString(k).
    // 7b. Let kPresent be ? HasProperty(O, Pk).
    LookupIterator it(isolate, o, k);
    Maybe<bool> maybe_found = JSReceiver::HasProperty(&it);
    MAYBE_RETURN(maybe_found, Nothing<std::vector<std::string>>());
    // 7c. If kPresent is true, then
    if (!maybe_found.FromJust()) continue;
    // 7c i. Let kValue be ? Get(O, Pk).
    DirectHandle<Object> k_value;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, k_value, Object::GetProperty(&it),
                                     Nothing<std::vector<std::string>>());
    // 7c ii. If Type(kValue) is not String or Object, throw a TypeError
    // exception.
    // 7c iii. If Type(kValue) is Object and kValue has an [[InitializedLocale]]
    // internal slot, then
    std::string canonicalized_tag;
    if (IsJSLocale(*k_value)) {
      // 7c iii. 1. Let tag be kValue.[[Locale]].
      canonicalized_tag = JSLocale::ToString(Cast<JSLocale>(k_value));
      // 7c iv. Else,
    } else {
      // 7c iv 1. Let tag be ? ToString(kValue).
      // 7c v. If IsStructurallyValidLanguageTag(tag) is false, throw a
      // RangeError exception.
      // 7c vi. Let canonicalizedTag be CanonicalizeLanguageTag(tag).
      if (!CanonicalizeLanguageTag(isolate, k_value).To(&canonicalized_tag)) {
        return Nothing<std::vector<std::string>>();
      }
    }
    // 7c vi. If canonicalizedTag is not an element of seen, append
    // canonicalizedTag as the last element of seen.
    if (std::find(seen.begin(), seen.end(), canonicalized_tag) == seen.end()) {
      seen.push_back(canonicalized_tag);
    }
    // 7d. Increase k by 1. (See loop header.)
    // Optimization: some callers only need one result.
    if (only_return_one_result) return Just(seen);
  }
  // 8. Return seen.
  return Just(seen);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::anonymous_namespace{intl-objects.cc}::CanonicalizeLanguageTag(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::Object::GetProperty(), v8::internal::JSReceiver::HasProperty(), v8::Just(), v8::internal::kMaxUInt32, MAYBE_RETURN, v8::Nothing(), v8::internal::Object::NumberValue(), v8::internal::string, v8::Value::ToObject(), and v8::internal::JSLocale::ToString().
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), GetCanonicalLocales(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSDurationFormat::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), StringLocaleConvertCase(), and SupportedLocalesOf().
CanonicalizeTimeZoneName()
static V8_WARN_UNUSED_RESULT MaybeHandle<String> v8::internal::Intl::CanonicalizeTimeZoneName (Isolate * isolate, DirectHandle< String > identifier) [static]
CoerceOptionsToObject()
static V8_WARN_UNUSED_RESULT MaybeDirectHandle<JSReceiver> v8::internal::Intl::CoerceOptionsToObject (Isolate * isolate, DirectHandle< Object > options, const char * service) [static]
CompareStrings()
int v8::internal::Intl::CompareStrings (Isolate * isolate, const icu::Collator & collator, DirectHandle< String > s1, DirectHandle< String > s2, CompareStringsOptions compare_strings_options = CompareStringsOptions::kNone) [static]
Definition at line 1450 of file intl-objects.cc.
                                                                        {
  // Early return for identical strings.
  if (string1.is_identical_to(string2)) {
    return UCollationResult::UCOL_EQUAL;
  }
  // We cannot return early for 0-length strings because of Unicode
  // ignorable characters. See also crbug.com/1347690.
  string1 = String::Flatten(isolate, string1);
  string2 = String::Flatten(isolate, string2);
  int processed_until = 0;
  if (compare_strings_options == CompareStringsOptions::kTryFastPath) {
    std::optional<int> maybe_result = TryFastCompareStrings(
        isolate, icu_collator, string1, string2, &processed_until);
    if (maybe_result.has_value()) return maybe_result.value();
  }
  UCollationResult result;
  UErrorCode status = U_ZERO_ERROR;
  icu::StringPiece string_piece1 =
      ToICUStringPiece(isolate, string1, processed_until);
  if (!string_piece1.empty()) {
    icu::StringPiece string_piece2 =
        ToICUStringPiece(isolate, string2, processed_until);
    if (!string_piece2.empty()) {
      result = icu_collator.compareUTF8(string_piece1, string_piece2, status);
      DCHECK(U_SUCCESS(status));
      return result;
    }
  }
  icu::UnicodeString string_val1 =
      Intl::ToICUUnicodeString(isolate, string1, processed_until);
  icu::UnicodeString string_val2 =
      Intl::ToICUUnicodeString(isolate, string2, processed_until);
  result = icu_collator.compare(string_val1, string_val2, status);
  DCHECK(U_SUCCESS(status));
  return result;
}
References v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_identical_to(), kTryFastPath, v8::base::internal::result, v8::internal::status, v8::internal::anonymous_namespace{intl-objects.cc}::ToICUStringPiece(), ToICUUnicodeString(), and v8::internal::anonymous_namespace{intl-objects.cc}::TryFastCompareStrings().
Referenced by v8::internal::BUILTIN(), and StringLocaleCompare().
CompareStringsOptionsFor() [1/2]
template<class IsolateT >
Intl::CompareStringsOptions v8::internal::Intl::CompareStringsOptionsFor (IsolateT * isolate, DirectHandle< Object > locales, DirectHandle< Object > options)
Definition at line 949 of file intl-objects.cc.
                                  {
  if (!IsUndefined(*options, isolate)) {
    return CompareStringsOptions::kNone;
  }
  // Lists all of the available locales that are statically known to fulfill
  // fast path conditions. See the StringLocaleCompareFastPath test as a
  // starting point to update this list.
  //
  // Locale entries are roughly sorted s.t. common locales come first.
  //
  // The actual conditions are verified in debug builds in
  // CollatorAllowsFastComparison.
  static const char* const kFastLocales[] = {
      "en-US", "en", "fr", "es", "de", "pt", "it", "ca",
      "de-AT", "fi", "id", "id-ID", "ms", "nl", "pl", "ro",
      "sl", "sv", "sw", "vi", "en-DE", "en-GB",
  };
  if (IsUndefined(*locales, isolate)) {
    const std::string& default_locale = isolate->DefaultLocale();
    for (const char* fast_locale : kFastLocales) {
      if (strcmp(fast_locale, default_locale.c_str()) == 0) {
        return CompareStringsOptions::kTryFastPath;
      }
    }
    return CompareStringsOptions::kNone;
  }
  if (!IsString(*locales)) return CompareStringsOptions::kNone;
  auto locales_string = Cast<String>(locales);
  for (const char* fast_locale : kFastLocales) {
    if (locales_string->IsEqualTo(base::CStrVector(fast_locale), isolate)) {
      return CompareStringsOptions::kTryFastPath;
    }
  }
  return CompareStringsOptions::kNone;
}
References v8::base::CStrVector(), kNone, kTryFastPath, and v8::internal::string.
CompareStringsOptionsFor() [2/2]
template<class IsolateT >
static V8_EXPORT_PRIVATE CompareStringsOptions v8::internal::Intl::CompareStringsOptionsFor (IsolateT * isolate, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Referenced by StringLocaleCompare().
ConvertOneByteToLower()
Tagged< String > v8::internal::Intl::ConvertOneByteToLower (Tagged< String > src, Tagged< String > dst) [static]
Definition at line 319 of file intl-objects.cc.
                                                               {
  DCHECK_EQ(src->length(), dst->length());
  DCHECK(src->IsOneByteRepresentation());
  DCHECK(src->IsFlat());
  DCHECK(IsSeqOneByteString(dst));
  DisallowGarbageCollection no_gc;
  const int length = src->length();
  String::FlatContent src_flat = src->GetFlatContent(no_gc);
  uint8_t* dst_data = Cast<SeqOneByteString>(dst)->GetChars(no_gc);
  if (src_flat.IsOneByte()) {
    const uint8_t* src_data = src_flat.ToOneByteVector().begin();
    int ascii_prefix_length = FastAsciiConvert<unibrow::ToLowercase>(
        reinterpret_cast<char*>(dst_data),
        reinterpret_cast<const char*>(src_data), length);
    if (ascii_prefix_length == length) return dst;
    // If not ASCII, we keep the result up to index_to_first_unprocessed and
    // process the rest.
    for (int index = ascii_prefix_length; index < length; ++index) {
      dst_data[index] = ToLatin1Lower(src_data[index]);
    }
  } else {
    DCHECK(src_flat.IsTwoByte());
    int index_to_first_unprocessed = FindFirstUpperOrNonAscii(src, length);
    if (index_to_first_unprocessed == length) return src;
    const uint16_t* src_data = src_flat.ToUC16Vector().begin();
    CopyChars(dst_data, src_data, index_to_first_unprocessed);
    for (int index = index_to_first_unprocessed; index < length; ++index) {
      // Truncating cast of two-byte src character to one-byte value. For valid
      // cases (where a one-byte sliced string points to a two-byte parent) this
      // will not lose any information, but we need to truncate anyway to
      // avoid undefined behavior if the parent string is corrupted.
      dst_data[index] = ToLatin1Lower(AsOneByte(src_data[index]));
    }
  }
  return dst;
}
References v8::internal::anonymous_namespace{intl-objects.cc}::AsOneByte(), v8::base::Vector< T >::begin(), v8::internal::CopyChars(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{intl-objects.cc}::FindFirstUpperOrNonAscii(), v8::internal::index, v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{intl-objects.cc}::ToLatin1Lower(), v8::internal::String::FlatContent::ToOneByteVector(), and v8::internal::String::FlatContent::ToUC16Vector().
Referenced by ConvertToLower(), and v8::internal::FUNCTION_REFERENCE().
ConvertToLower()
MaybeHandle< String > v8::internal::Intl::ConvertToLower (Isolate * isolate, DirectHandle< String > s) [static]
Definition at line 365 of file intl-objects.cc.
                                                                 {
  if (!s->IsOneByteRepresentation()) {
    // Use a slower implementation for strings with characters beyond U+00FF.
    return LocaleConvertCase(isolate, s, false, "");
  }
  int length = s->length();
  // We depend here on the invariant that the length of a Latin1
  // string is invariant under ToLowerCase, and the result always
  // fits in the Latin1 range in the *root locale*. It does not hold
  // for ToUpperCase even in the root locale.
  // Scan the string for uppercase and non-ASCII characters for strings
  // shorter than a machine-word without any memory allocation overhead.
  // TODO(jshin): Apply this to a longer input by breaking FastAsciiConvert()
  // to two parts, one for scanning the prefix with no change and the other for
  // handling ASCII-only characters.
  bool is_short = length < static_cast<int>(sizeof(uintptr_t));
  if (is_short) {
    bool is_lower_ascii = FindFirstUpperOrNonAscii(*s, length) == length;
    if (is_lower_ascii) return indirect_handle(s, isolate);
  }
  DirectHandle<SeqOneByteString> result =
      isolate->factory()->NewRawOneByteString(length).ToHandleChecked();
  return handle(Intl::ConvertOneByteToLower(*s, *result), isolate);
}
References ConvertOneByteToLower(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{intl-objects.cc}::FindFirstUpperOrNonAscii(), v8::internal::handle(), v8::internal::indirect_handle(), v8::internal::length, v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), and v8::base::internal::result.
Referenced by v8::internal::RUNTIME_FUNCTION(), and StringLocaleConvertCase().
ConvertToUpper()
MaybeDirectHandle< String > v8::internal::Intl::ConvertToUpper (Isolate * isolate, DirectHandle< String > s) [static]
Definition at line 397 of file intl-objects.cc.
                                                                       {
  uint32_t length = s->length();
  if (s->IsOneByteRepresentation() && length > 0) {
    uint32_t prefix;
    {
      DisallowGarbageCollection no_gc;
      String::FlatContent flat = s->GetFlatContent(no_gc);
      prefix = FastAsciiCasePrefixLength<unibrow::ToUppercase>(
          reinterpret_cast<const char*>(flat.ToOneByteVector().begin()),
          length);
      if (prefix == length) {
        return indirect_handle(s, isolate);
      }
    }
    Handle<SeqOneByteString> result =
        isolate->factory()->NewRawOneByteString(length).ToHandleChecked();
    DCHECK(s->IsFlat());
    int sharp_s_count;
    bool is_result_single_byte;
    {
      DisallowGarbageCollection no_gc;
      String::FlatContent flat = s->GetFlatContent(no_gc);
      uint8_t* dest = result->GetChars(no_gc);
      if (flat.IsOneByte()) {
        base::Vector<const uint8_t> src = flat.ToOneByteVector();
        std::memcpy(result->GetChars(no_gc), src.begin(), prefix);
        uint32_t ascii_prefix_length =
            FastAsciiConvert<unibrow::ToUppercase>(
                reinterpret_cast<char*>(result->GetChars(no_gc)) + prefix,
                reinterpret_cast<const char*>(src.begin()) + prefix,
                length - prefix) +
            prefix;
        if (ascii_prefix_length == length) return result;
        // If not ASCII, we keep the result up to index_to_first_unprocessed and
        // process the rest.
        is_result_single_byte =
            ToUpperOneByte(src.SubVector(ascii_prefix_length, length),
                           dest + ascii_prefix_length, &sharp_s_count);
      } else {
        DCHECK(flat.IsTwoByte());
        base::Vector<const uint16_t> src = flat.ToUC16Vector();
        if (ToUpperFastASCII(src, result)) return result;
        is_result_single_byte = ToUpperOneByte(src, dest, &sharp_s_count);
      }
    }
    // Go to the full Unicode path if there are characters whose uppercase
    // is beyond the Latin-1 range (cannot be represented in OneByteString).
    if (V8_UNLIKELY(!is_result_single_byte)) {
      return LocaleConvertCase(isolate, s, true, "");
    }
    if (sharp_s_count == 0) return result;
    // We have sharp_s_count sharp-s characters, but the result is still
    // in the Latin-1 range.
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, result,
        isolate->factory()->NewRawOneByteString(length + sharp_s_count));
    DisallowGarbageCollection no_gc;
    String::FlatContent flat = s->GetFlatContent(no_gc);
    if (flat.IsOneByte()) {
      ToUpperWithSharpS(flat.ToOneByteVector(), result);
    } else {
      ToUpperWithSharpS(flat.ToUC16Vector(), result);
    }
    return result;
  }
  return LocaleConvertCase(isolate, s, true, "");
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::indirect_handle(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::length, v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::base::Vector< T >::SubVector(), v8::internal::String::FlatContent::ToOneByteVector(), v8::internal::String::FlatContent::ToUC16Vector(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperFastASCII(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperOneByte(), v8::internal::anonymous_namespace{intl-objects.cc}::ToUpperWithSharpS(), and V8_UNLIKELY.
Referenced by v8::internal::BUILTIN(), v8::internal::RUNTIME_FUNCTION(), and StringLocaleConvertCase().
CreateTimeZoneCache()
base::TimezoneCache * v8::internal::Intl::CreateTimeZoneCache () [static]
Definition at line 2770 of file intl-objects.cc.
                                             {
  return v8_flags.icu_timezone_data ? new ICUTimezoneCache()
                                    : base::OS::CreateTimezoneCache();
}
References v8::base::OS::CreateTimezoneCache(), and v8::internal::v8_flags.
DefaultTimeZone()
DirectHandle< String > v8::internal::Intl::DefaultTimeZone (Isolate * isolate) [static]
Definition at line 3056 of file intl-objects.cc.
                                                           {
  icu::UnicodeString id;
  {
    std::unique_ptr<icu::TimeZone> tz(icu::TimeZone::createDefault());
    tz->getID(id);
  }
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString canonical;
  icu::TimeZone::getCanonicalID(id, canonical, status);
  DCHECK(U_SUCCESS(status));
  return JSDateTimeFormat::TimeZoneIdToString(isolate, canonical)
      .ToHandleChecked();
}
References v8::internal::DCHECK(), v8::internal::status, and v8::internal::JSDateTimeFormat::TimeZoneIdToString().
FormattedToString()
MaybeDirectHandle< String > v8::internal::Intl::FormattedToString (Isolate * isolate, const icu::FormattedValue & formatted) [static]
Definition at line 2887 of file intl-objects.cc.
                                                          {
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString result = formatted.toString(status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return Intl::ToString(isolate, result);
}
References v8::base::internal::result, v8::internal::status, THROW_NEW_ERROR, and ToString().
Referenced by v8::internal::JSListFormat::FormatList(), and v8::internal::FormattedToString().
GetAvailableLocales()
const std::set< std::string > & v8::internal::Intl::GetAvailableLocales () [static]
Definition at line 2808 of file intl-objects.cc.
                                                   {
  static base::LazyInstance<Intl::AvailableLocales<>>::type available_locales =
      LAZY_INSTANCE_INITIALIZER;
  return available_locales.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER, and v8::internal::tracing::type.
Referenced by v8::internal::JSV8BreakIterator::GetAvailableLocales(), and v8::internal::JSSegmenter::GetAvailableLocales().
GetAvailableLocalesForDateFormat()
const std::set< std::string > & v8::internal::Intl::GetAvailableLocalesForDateFormat () [static]
Definition at line 2823 of file intl-objects.cc.
                                                                {
  static base::LazyInstance<Intl::AvailableLocales<CheckCalendar>>::type
      available_locales = LAZY_INSTANCE_INITIALIZER;
  return available_locales.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER, and v8::internal::tracing::type.
Referenced by v8::internal::JSDateTimeFormat::GetAvailableLocales(), and v8::internal::JSRelativeTimeFormat::GetAvailableLocales().
GetCanonicalLocales()
MaybeDirectHandle< JSArray > v8::internal::Intl::GetCanonicalLocales (Isolate * isolate, DirectHandle< Object > locales) [static]
Definition at line 2162 of file intl-objects.cc.
                                                    {
  // 1. Let ll be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_ll =
      CanonicalizeLocaleList(isolate, locales, false);
  MAYBE_RETURN(maybe_ll, {});
  // 2. Return CreateArrayFromList(ll).
  return CreateArrayFromList(isolate, maybe_ll.FromJust(),
                             PropertyAttributes::NONE);
}
References CanonicalizeLocaleList(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList(), v8::Maybe< T >::FromJust(), MAYBE_RETURN, and v8::internal::NONE.
Referenced by v8::internal::BUILTIN().
GetLocaleMatcher()
Maybe< Intl::MatcherOption > v8::internal::Intl::GetLocaleMatcher (Isolate * isolate, DirectHandle< JSReceiver > options, const char * method_name) [static]
Definition at line 2775 of file intl-objects.cc.
                             {
  return GetStringOption<Intl::MatcherOption>(
      isolate, options, "localeMatcher", method_name,
      std::to_array<const std::string_view>({"best fit", "lookup"}),
      std::array{Intl::MatcherOption::kBestFit, Intl::MatcherOption::kLookup},
      Intl::MatcherOption::kBestFit);
}
References kBestFit, and kLookup.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSDurationFormat::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), and v8::internal::anonymous_namespace{intl-objects.cc}::SupportedLocales().
GetNumberingSystem() [1/2]
std::string v8::internal::Intl::GetNumberingSystem (const icu::Locale & icu_locale) [static]
Definition at line 472 of file intl-objects.cc.
                                                              {
  // Ugly hack. ICU doesn't expose numbering system in any way, so we have
  // to assume that for given locale NumberingSystem constructor produces the
  // same digits as NumberFormat/Calendar would.
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::NumberingSystem> numbering_system(
      icu::NumberingSystem::createInstance(icu_locale, status));
  if (U_SUCCESS(status) && !numbering_system->isAlgorithmic()) {
    return numbering_system->getName();
  }
  return "latn";
}
References v8::internal::status.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::JSLocale::GetNumberingSystems(), v8::internal::JSDurationFormat::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSNumberFormat::New(), and v8::internal::JSDateTimeFormat::ResolvedOptions().
GetNumberingSystem() [2/2]
Maybe< bool > v8::internal::Intl::GetNumberingSystem (Isolate * isolate, DirectHandle< JSReceiver > options, const char * method_name, std::string & result) [static]
Definition at line 2785 of file intl-objects.cc.
                                                        {
  DirectHandle<String> output;
  Maybe<bool> maybe =
      GetStringOption(isolate, options, "numberingSystem",
                      std::span<std::string_view>(), method_name, &output);
  MAYBE_RETURN(maybe, Nothing<bool>());
  if (maybe.FromJust()) {
    result = output->ToStdString();
    if (!IsWellFormedNumberingSystem(result)) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate,
          NewRangeError(MessageTemplate::kInvalid,
                        isolate->factory()->numberingSystem_string(), output),
          Nothing<bool>());
    }
    return Just(true);
  }
  return Just(false);
}
References v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::GetStringOption(), v8::internal::anonymous_namespace{intl-objects.cc}::IsWellFormedNumberingSystem(), v8::Just(), v8::internal::anonymous_namespace{isolate.cc}::kInvalid, MAYBE_RETURN, v8::base::internal::result, and THROW_NEW_ERROR_RETURN_VALUE.
GetTimeZoneIndex()
int32_t v8::internal::Intl::GetTimeZoneIndex (Isolate * isolate, DirectHandle< String > identifier) [static]
Definition at line 2984 of file intl-objects.cc.
                                                                {
  if (identifier->Equals(*isolate->factory()->UTC_string())) {
    return 0;
  }
  std::string identifier_str(identifier->ToCString().get());
  std::unique_ptr<icu::TimeZone> tz(
      icu::TimeZone::createTimeZone(identifier_str.c_str()));
  if (!IsValidTimeZoneName(*tz)) {
    return -1;
  }
  std::unique_ptr<icu::StringEnumeration> enumeration(
      icu::TimeZone::createEnumeration());
  int32_t curr = 0;
  const char* id;
  UErrorCode status = U_ZERO_ERROR;
  while (U_SUCCESS(status) &&
         (id = enumeration->next(nullptr, status)) != nullptr) {
    curr++;
    if (identifier_str == id) {
      return curr;
    }
  }
  CHECK(U_SUCCESS(status));
  // We should not reach here, the !IsValidTimeZoneName should return earlier
  UNREACHABLE();
}
References CHECK, v8::internal::Isolate::factory(), IsValidTimeZoneName(), v8::internal::status, v8::internal::string, and v8::internal::UNREACHABLE().
GetTimeZoneOffsetNanoseconds()
int64_t v8::internal::Intl::GetTimeZoneOffsetNanoseconds (Isolate * isolate, int32_t time_zone_index, DirectHandle< BigInt > nanosecond_epoch) [static]
Definition at line 3216 of file intl-objects.cc.
                                           {
  std::unique_ptr<const icu::BasicTimeZone> basic_time_zone(
      CreateBasicTimeZoneFromIndex(time_zone_index));
  int64_t time_ms = ApproximateMillisecondEpoch(isolate, nanosecond_epoch);
  int32_t raw_offset;
  int32_t dst_offset;
  UErrorCode status = U_ZERO_ERROR;
  basic_time_zone->getOffset(time_ms, false, raw_offset, dst_offset, status);
  DCHECK(U_SUCCESS(status));
  // Turn ms into ns
  return static_cast<int64_t>(raw_offset + dst_offset) * 1000000;
}
References v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateBasicTimeZoneFromIndex(), v8::internal::DCHECK(), and v8::internal::status.
GetTimeZoneOffsetTransitionNanoseconds()
DirectHandle< Object > v8::internal::Intl::GetTimeZoneOffsetTransitionNanoseconds (Isolate * isolate, int32_t time_zone_index, DirectHandle< BigInt > nanosecond_epoch, Intl::Transition transition) [static]
Definition at line 3126 of file intl-objects.cc.
                                                                      {
  std::unique_ptr<const icu::BasicTimeZone> basic_time_zone(
      CreateBasicTimeZoneFromIndex(time_zone_index));
  icu::TimeZoneTransition icu_transition;
  UBool has_transition;
  switch (transition) {
    case Intl::Transition::kNext:
      has_transition = basic_time_zone->getNextTransition(
          ApproximateMillisecondEpoch(isolate, nanosecond_epoch), false,
          icu_transition);
      break;
    case Intl::Transition::kPrevious:
      has_transition = basic_time_zone->getPreviousTransition(
          ApproximateMillisecondEpoch(isolate, nanosecond_epoch,
                                      Direction::kFuture),
          false, icu_transition);
      break;
  }
  if (!has_transition) {
    return isolate->factory()->null_value();
  }
  // #sec-temporal-getianatimezonenexttransition and
  // #sec-temporal-getianatimezoneprevioustransition states:
  // "The operation returns null if no such transition exists for which t
  // (nsMaxInstant)." and "The operation returns null if no such transition
  // exists for which t (nsMinInstant)."
  //
  // nsMinInstant = -nsMaxInstant = -8.64 10^21 => msMinInstant = -8.64 x
  // 10^15
  constexpr int64_t kMsMinInstant = -8.64e15;
  // nsMaxInstant = 10^8 nsPerDay = 8.64 10^21 => msMaxInstant = 8.64 x
  // 10^15
  constexpr int64_t kMsMaxInstant = 8.64e15;
  int64_t time_ms = static_cast<int64_t>(icu_transition.getTime());
  if (time_ms < kMsMinInstant || time_ms > kMsMaxInstant) {
    return isolate->factory()->null_value();
  }
  return MillisecondToNanosecond(isolate, time_ms);
}
References v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateBasicTimeZoneFromIndex(), v8::internal::Isolate::factory(), kNext, kPrevious, and v8::internal::anonymous_namespace{intl-objects.cc}::MillisecondToNanosecond().
GetTimeZonePossibleOffsetNanoseconds()
DirectHandleVector< BigInt > v8::internal::Intl::GetTimeZonePossibleOffsetNanoseconds (Isolate * isolate, int32_t time_zone_index, DirectHandle< BigInt > nanosecond_epoch) [static]
Definition at line 3170 of file intl-objects.cc.
                                           {
  std::unique_ptr<const icu::BasicTimeZone> basic_time_zone(
      CreateBasicTimeZoneFromIndex(time_zone_index));
  int64_t time_ms = ApproximateMillisecondEpoch(isolate, nanosecond_epoch);
  int32_t raw_offset;
  int32_t dst_offset;
  UErrorCode status = U_ZERO_ERROR;
  basic_time_zone->getOffsetFromLocal(time_ms, UCAL_TZ_LOCAL_FORMER,
                                      UCAL_TZ_LOCAL_FORMER, raw_offset,
                                      dst_offset, status);
  DCHECK(U_SUCCESS(status));
  // offset for time_ms interpreted as before a time zone
  // transition
  int64_t offset_former = raw_offset + dst_offset;
  basic_time_zone->getOffsetFromLocal(time_ms, UCAL_TZ_LOCAL_LATTER,
                                      UCAL_TZ_LOCAL_LATTER, raw_offset,
                                      dst_offset, status);
  DCHECK(U_SUCCESS(status));
  // offset for time_ms interpreted as after a time zone
  // transition
  int64_t offset_latter = raw_offset + dst_offset;
  DirectHandleVector<BigInt> result(isolate);
  if (offset_former == offset_latter) {
    // For most of the time, when either interpretation are the same, we are not
    // in a moment of offset transition based on rule changing: Just return that
    // value.
    result.push_back(MillisecondToNanosecond(isolate, offset_former));
  } else if (offset_former > offset_latter) {
    // When the input represents a local time repeating multiple times at a
    // negative time zone transition (e.g. when the daylight saving time ends
    // or the time zone offset is decreased due to a time zone rule change).
    result.push_back(MillisecondToNanosecond(isolate, offset_former));
    result.push_back(MillisecondToNanosecond(isolate, offset_latter));
  } else {
    // If the offset after the transition is greater than the offset before the
    // transition, that mean it is in the moment the time "skip" an hour, or two
    // (or six in a Time Zone in south pole) in that case there are no possible
    // Time Zone offset for that moment and nothing will be added to the result.
  }
  return result;
}
References v8::internal::anonymous_namespace{intl-objects.cc}::ApproximateMillisecondEpoch(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateBasicTimeZoneFromIndex(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{intl-objects.cc}::MillisecondToNanosecond(), v8::base::internal::result, and v8::internal::status.
IsValidCalendar()
bool v8::internal::Intl::IsValidCalendar (const icu::Locale & locale, const std::string & value) [static]
Definition at line 2413 of file intl-objects.cc.
                                                   {
  return IsValidExtension<icu::Calendar>(locale, "calendar", value);
}
References v8::internal::value.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), and v8::internal::anonymous_namespace{intl-objects.cc}::LookupAndValidateUnicodeExtensions().
IsValidCollation()
bool v8::internal::Intl::IsValidCollation (const icu::Locale & locale, const std::string & value) [static]
Definition at line 2397 of file intl-objects.cc.
                                                    {
  std::set<std::string> invalid_values = {"standard", "search"};
  if (invalid_values.find(value) != invalid_values.end()) return false;
  return IsValidExtension<icu::Collator>(locale, "collation", value);
}
References v8::internal::value.
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::LookupAndValidateUnicodeExtensions(), and v8::internal::JSCollator::New().
IsValidNumberingSystem()
bool v8::internal::Intl::IsValidNumberingSystem (const std::string & value) [static]
Definition at line 2418 of file intl-objects.cc.
                                                        {
  std::set<std::string> invalid_values = {"native", "traditio", "finance"};
  if (invalid_values.find(value) != invalid_values.end()) return false;
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::NumberingSystem> numbering_system(
      icu::NumberingSystem::createInstanceByName(value.c_str(), status));
  return U_SUCCESS(status) && numbering_system != nullptr &&
         !numbering_system->isAlgorithmic();
}
References v8::internal::status, and v8::internal::value.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::anonymous_namespace{intl-objects.cc}::LookupAndValidateUnicodeExtensions(), v8::internal::JSDurationFormat::New(), v8::internal::JSRelativeTimeFormat::New(), and v8::internal::JSNumberFormat::New().
IsValidTimeZoneName() [1/3]
bool v8::internal::Intl::IsValidTimeZoneName (const icu::TimeZone & tz) [static]
Definition at line 2953 of file intl-objects.cc.
                                                    {
  icu::UnicodeString id;
  tz.getID(id);
  return IsUnicodeStringValidTimeZoneName(id);
}
References v8::internal::anonymous_namespace{intl-objects.cc}::IsUnicodeStringValidTimeZoneName().
Referenced by v8::internal::JSDateTimeFormat::CreateTimeZone(), and GetTimeZoneIndex().
IsValidTimeZoneName() [2/3]
static V8_WARN_UNUSED_RESULT bool v8::internal::Intl::IsValidTimeZoneName (Isolate * isolate, const std::string & id) [static]
IsValidTimeZoneName() [3/3]
static V8_WARN_UNUSED_RESULT bool v8::internal::Intl::IsValidTimeZoneName (Isolate * isolate, DirectHandle< String > id) [static]
IsWellFormedCalendar()
bool v8::internal::Intl::IsWellFormedCalendar (std::string_view value) [static]
Definition at line 2404 of file intl-objects.cc.
                                                    {
  return JSLocale::Is38AlphaNumList(value);
}
References v8::internal::JSLocale::Is38AlphaNumList(), and v8::internal::value.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), and v8::internal::anonymous_namespace{js-display-names.cc}::CalendarNames::of().
IsWellFormedCurrency()
bool v8::internal::Intl::IsWellFormedCurrency (std::string_view value) [static]
Definition at line 2409 of file intl-objects.cc.
                                                       {
  return JSLocale::Is3Alpha(currency);
}
References v8::internal::JSLocale::Is3Alpha().
Referenced by v8::internal::anonymous_namespace{js-display-names.cc}::CurrencyNames::of().
LegacyUnwrapReceiver()
MaybeDirectHandle< Object > v8::internal::Intl::LegacyUnwrapReceiver (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< JSFunction > constructor, bool has_initialized_slot) [static]
Definition at line 662 of file intl-objects.cc.
                                                                     {
  DirectHandle<Object> obj_ordinary_has_instance;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, obj_ordinary_has_instance,
      Object::OrdinaryHasInstance(isolate, constructor, receiver));
  bool ordinary_has_instance =
      Object::BooleanValue(*obj_ordinary_has_instance, isolate);
  // 2. If receiver does not have an [[Initialized...]] internal slot
  // and ? OrdinaryHasInstance(constructor, receiver) is true, then
  if (!has_initialized_slot && ordinary_has_instance) {
    // 2. a. Let new_receiver be ? Get(receiver, %Intl%.[[FallbackSymbol]]).
    DirectHandle<Object> new_receiver;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, new_receiver,
        JSReceiver::GetProperty(isolate, receiver,
                                isolate->factory()->intl_fallback_symbol()));
    return new_receiver;
  }
  return receiver;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Object::BooleanValue(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetProperty(), and v8::internal::Object::OrdinaryHasInstance().
Referenced by v8::internal::JSDateTimeFormat::UnwrapDateTimeFormat(), and v8::internal::JSNumberFormat::UnwrapNumberFormat().
Normalize()
MaybeDirectHandle< String > v8::internal::Intl::Normalize (Isolate * isolate, DirectHandle< String > string, DirectHandle< Object > form_input) [static]
Definition at line 2614 of file intl-objects.cc.
                                                                           {
  const char* form_name;
  UNormalization2Mode form_mode;
  if (IsUndefined(*form_input, isolate)) {
    // default is FNC
    form_name = "nfc";
    form_mode = UNORM2_COMPOSE;
  } else {
    DirectHandle<String> form;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, form,
                               Object::ToString(isolate, form_input));
    if (String::Equals(isolate, form, isolate->factory()->NFC_string())) {
      form_name = "nfc";
      form_mode = UNORM2_COMPOSE;
    } else if (String::Equals(isolate, form,
                              isolate->factory()->NFD_string())) {
      form_name = "nfc";
      form_mode = UNORM2_DECOMPOSE;
    } else if (String::Equals(isolate, form,
                              isolate->factory()->NFKC_string())) {
      form_name = "nfkc";
      form_mode = UNORM2_COMPOSE;
    } else if (String::Equals(isolate, form,
                              isolate->factory()->NFKD_string())) {
      form_name = "nfkc";
      form_mode = UNORM2_DECOMPOSE;
    } else {
      DirectHandle<String> valid_forms =
          isolate->factory()->NewStringFromStaticChars("NFC, NFD, NFKC, NFKD");
      THROW_NEW_ERROR(
          isolate,
          NewRangeError(MessageTemplate::kNormalizationForm, valid_forms));
    }
  }
  uint32_t length = string->length();
  string = String::Flatten(isolate, string);
  icu::UnicodeString result;
  std::unique_ptr<base::uc16[]> sap;
  UErrorCode status = U_ZERO_ERROR;
  icu::UnicodeString input = ToICUUnicodeString(isolate, string);
  // Getting a singleton. Should not free it.
  const icu::Normalizer2* normalizer =
      icu::Normalizer2::getInstance(nullptr, form_name, form_mode, status);
  DCHECK(U_SUCCESS(status));
  DCHECK_NOT_NULL(normalizer);
  uint32_t normalized_prefix_length =
      normalizer->spanQuickCheckYes(input, status);
  // Quick return if the input is already normalized.
  if (length == normalized_prefix_length) return string;
  icu::UnicodeString unnormalized =
      input.tempSubString(normalized_prefix_length);
  // Read-only alias of the normalized prefix.
  result.setTo(false, input.getBuffer(), normalized_prefix_length);
  // copy-on-write; normalize the suffix and append to |result|.
  normalizer->normalizeSecondAndAppend(result, unnormalized, status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR(isolate, NewTypeError(MessageTemplate::kIcuError));
  }
  return Intl::ToString(isolate, result);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::String::Equals(), v8::internal::Isolate::factory(), v8::internal::length, v8::internal::Factory::NewStringFromStaticChars(), v8::base::internal::result, v8::internal::status, v8::internal::string, THROW_NEW_ERROR, ToICUUnicodeString(), ToString(), and v8::Value::ToString().
Referenced by v8::internal::BUILTIN().
NumberFieldToType()
DirectHandle< String > v8::internal::Intl::NumberFieldToType (Isolate * isolate, const NumberFormatSpan & part, const icu::UnicodeString & text, bool is_nan) [static]
Definition at line 2831 of file intl-objects.cc.
                                                          {
  switch (static_cast<UNumberFormatFields>(part.field_id)) {
    case UNUM_INTEGER_FIELD:
      if (is_nan) return isolate->factory()->nan_string();
      if (text.charAt(part.begin_pos) == kInfinityChar ||
          // en-US-POSIX output "INF" for Infinity
          (part.end_pos - part.begin_pos == 3 &&
           text.tempSubString(part.begin_pos, 3) == "INF")) {
        return isolate->factory()->infinity_string();
      }
      return isolate->factory()->integer_string();
    case UNUM_FRACTION_FIELD:
      return isolate->factory()->fraction_string();
    case UNUM_DECIMAL_SEPARATOR_FIELD:
      return isolate->factory()->decimal_string();
    case UNUM_GROUPING_SEPARATOR_FIELD:
      return isolate->factory()->group_string();
    case UNUM_CURRENCY_FIELD:
      return isolate->factory()->currency_string();
    case UNUM_PERCENT_FIELD:
      return isolate->factory()->percentSign_string();
    case UNUM_SIGN_FIELD:
      return (text.charAt(part.begin_pos) == '+')
                 ? isolate->factory()->plusSign_string()
                 : isolate->factory()->minusSign_string();
    case UNUM_EXPONENT_SYMBOL_FIELD:
      return isolate->factory()->exponentSeparator_string();
    case UNUM_EXPONENT_SIGN_FIELD:
      return isolate->factory()->exponentMinusSign_string();
    case UNUM_EXPONENT_FIELD:
      return isolate->factory()->exponentInteger_string();
    case UNUM_PERMILL_FIELD:
      // We're not creating any permill formatter, and it's not even clear how
      // that would be possible with the ICU API.
      UNREACHABLE();
    case UNUM_COMPACT_FIELD:
      return isolate->factory()->compact_string();
    case UNUM_MEASURE_UNIT_FIELD:
      return isolate->factory()->unit_string();
    case UNUM_APPROXIMATELY_SIGN_FIELD:
      return isolate->factory()->approximatelySign_string();
    default:
      UNREACHABLE();
  }
}
References v8::internal::NumberFormatSpan::begin_pos, v8::internal::NumberFormatSpan::end_pos, v8::internal::Isolate::factory(), v8::internal::NumberFormatSpan::field_id, v8::internal::kInfinityChar, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddUnit(), and v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts().
NumberToLocaleString()
MaybeDirectHandle< String > v8::internal::Intl::NumberToLocaleString (Isolate * isolate, Handle< Object > num, DirectHandle< Object > locales, DirectHandle< Object > options, const char * method_name) [static]
Definition at line 1496 of file intl-objects.cc.
                                                           {
  Handle<Object> numeric_obj;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, numeric_obj,
                             Object::ToNumeric(isolate, num));
  // We only cache the instance when locales is a string/undefined and
  // options is undefined, as that is the only case when the specified
  // side-effects of examining those arguments are unobservable.
  bool can_cache = (IsString(*locales) || IsUndefined(*locales, isolate)) &&
                   IsUndefined(*options, isolate);
  if (can_cache) {
    icu::number::LocalizedNumberFormatter* cached_number_format =
        static_cast<icu::number::LocalizedNumberFormatter*>(
            isolate->get_cached_icu_object(
                Isolate::ICUObjectCacheType::kDefaultNumberFormat, locales));
    // We may use the cached icu::NumberFormat for a fast path.
    if (cached_number_format != nullptr) {
      return JSNumberFormat::FormatNumeric(isolate, *cached_number_format,
                                           numeric_obj);
    }
  }
  DirectHandle<JSFunction> constructor(
      Cast<JSFunction>(
          isolate->context()->native_context()->intl_number_format_function()),
      isolate);
  DirectHandle<JSNumberFormat> number_format;
  // 2. Let numberFormat be ? Construct(%NumberFormat%, locales, options).
  StackLimitCheck stack_check(isolate);
  // New<JSNumberFormat>() requires a lot of stack space.
  const int kStackSpaceRequiredForNewJSNumberFormat = 16 * KB;
  if (stack_check.JsHasOverflowed(kStackSpaceRequiredForNewJSNumberFormat)) {
    isolate->StackOverflow();
    return {};
  }
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, number_format,
      New<JSNumberFormat>(isolate, constructor, locales, options, method_name));
  if (can_cache) {
    isolate->set_icu_object_in_cache(
        Isolate::ICUObjectCacheType::kDefaultNumberFormat, locales,
        std::static_pointer_cast<icu::UMemory>(
            number_format->icu_number_formatter()->get()));
  }
  // Return FormatNumber(numberFormat, x).
  icu::number::LocalizedNumberFormatter* icu_number_format =
      number_format->icu_number_formatter()->raw();
  return JSNumberFormat::FormatNumeric(isolate, *icu_number_format,
                                       numeric_obj);
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::context(), v8::internal::JSNumberFormat::FormatNumeric(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::KB, v8::internal::Isolate::StackOverflow(), and v8::Value::ToNumeric().
Referenced by v8::internal::BUILTIN().
RemoveCollation()
bool v8::internal::Intl::RemoveCollation (const char * collation) [static]
Definition at line 2920 of file intl-objects.cc.
                                                {
  return strcmp("standard", collation) == 0 || strcmp("search", collation) == 0;
}
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::AvailableCollations(), and v8::internal::JSLocale::GetCollations().
ResolveLocale()
Maybe< Intl::ResolvedLocale > v8::internal::Intl::ResolveLocale (Isolate * isolate, const std::set< std::string > & available_locales, const std::vector< std::string > & requested_locales, MatcherOption options, const std::set< std::string > & relevant_extension_keys) [static]
Definition at line 2573 of file intl-objects.cc.
                                                      {
  std::string locale;
  if (matcher == Intl::MatcherOption::kBestFit &&
      v8_flags.harmony_intl_best_fit_matcher) {
    locale = BestFitMatcher(isolate, available_locales, requested_locales);
  } else {
    locale = LookupMatcher(isolate, available_locales, requested_locales);
  }
  Maybe<icu::Locale> maybe_icu_locale = CreateICULocale(locale);
  MAYBE_RETURN(maybe_icu_locale, Nothing<Intl::ResolvedLocale>());
  icu::Locale icu_locale = maybe_icu_locale.FromJust();
  std::map<std::string, std::string> extensions =
      LookupAndValidateUnicodeExtensions(&icu_locale, relevant_extension_keys);
  std::string canonicalized_locale = Intl::ToLanguageTag(icu_locale).FromJust();
  // TODO(gsathya): Remove privateuse subtags from extensions.
  return Just(
      Intl::ResolvedLocale{canonicalized_locale, icu_locale, extensions});
}
References v8::internal::anonymous_namespace{intl-objects.cc}::BestFitMatcher(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateICULocale(), v8::Maybe< T >::FromJust(), v8::Just(), kBestFit, v8::internal::anonymous_namespace{intl-objects.cc}::LookupAndValidateUnicodeExtensions(), v8::internal::anonymous_namespace{intl-objects.cc}::LookupMatcher(), MAYBE_RETURN, v8::internal::string, ToLanguageTag(), and v8::internal::v8_flags.
Referenced by v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSDurationFormat::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), and v8::internal::JSNumberFormat::New().
SanctionedSimpleUnits()
std::set< std::string > v8::internal::Intl::SanctionedSimpleUnits () [static]
Definition at line 2925 of file intl-objects.cc.
                                              {
  return std::set<std::string>(
      {"acre", "bit", "byte", "celsius",
       "centimeter", "day", "degree", "fahrenheit",
       "fluid-ounce", "foot", "gallon", "gigabit",
       "gigabyte", "gram", "hectare", "hour",
       "inch", "kilobit", "kilobyte", "kilogram",
       "kilometer", "liter", "megabit", "megabyte",
       "meter", "microsecond", "mile", "mile-scandinavian",
       "millimeter", "milliliter", "millisecond", "minute",
       "month", "nanosecond", "ounce", "percent",
       "petabyte", "pound", "second", "stone",
       "terabit", "terabyte", "week", "yard",
       "year"});
}
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits(), and v8::internal::anonymous_namespace{js-number-format.cc}::CreateUnitMap().
SetNumberFormatDigitOptions()
Maybe< Intl::NumberFormatDigitOptions > v8::internal::Intl::SetNumberFormatDigitOptions (Isolate * isolate, DirectHandle< JSReceiver > options, int mnfd_default, int mxfd_default, bool notation_is_compact, const char * service) [static]
Definition at line 1580 of file intl-objects.cc.
                                                                     {
  Factory* factory = isolate->factory();
  Intl::NumberFormatDigitOptions digit_options;
  // 1. Let mnid be ? GetNumberOption(options, "minimumIntegerDigits,", 1, 21,
  // 1).
  int mnid = 1;
  if (!GetNumberOption(isolate, options, factory->minimumIntegerDigits_string(),
                       1, 21, 1)
           .To(&mnid)) {
    return Nothing<NumberFormatDigitOptions>();
  }
  // 2. Let mnfd be ? Get(options, "minimumFractionDigits").
  DirectHandle<Object> mnfd_obj;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, mnfd_obj,
      JSReceiver::GetProperty(isolate, options,
                              factory->minimumFractionDigits_string()),
      Nothing<NumberFormatDigitOptions>());
  // 3. Let mxfd be ? Get(options, "maximumFractionDigits").
  DirectHandle<Object> mxfd_obj;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, mxfd_obj,
      JSReceiver::GetProperty(isolate, options,
                              factory->maximumFractionDigits_string()),
      Nothing<NumberFormatDigitOptions>());
  // 4. Let mnsd be ? Get(options, "minimumSignificantDigits").
  DirectHandle<Object> mnsd_obj;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, mnsd_obj,
      JSReceiver::GetProperty(isolate, options,
                              factory->minimumSignificantDigits_string()),
      Nothing<NumberFormatDigitOptions>());
  // 5. Let mxsd be ? Get(options, "maximumSignificantDigits").
  DirectHandle<Object> mxsd_obj;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, mxsd_obj,
      JSReceiver::GetProperty(isolate, options,
                              factory->maximumSignificantDigits_string()),
      Nothing<NumberFormatDigitOptions>());
  digit_options.rounding_priority = RoundingPriority::kAuto;
  digit_options.minimum_significant_digits = 0;
  digit_options.maximum_significant_digits = 0;
  // 6. Set intlObj.[[MinimumIntegerDigits]] to mnid.
  digit_options.minimum_integer_digits = mnid;
  // 7. Let roundingIncrement be ? GetNumberOption(options, "roundingIncrement",
  // 1, 5000, 1).
  Maybe<int> maybe_rounding_increment = GetNumberOption(
      isolate, options, factory->roundingIncrement_string(), 1, 5000, 1);
  if (!maybe_rounding_increment.To(&digit_options.rounding_increment)) {
    return Nothing<NumberFormatDigitOptions>();
  }
  // 8. If roundingIncrement is not in 1, 2, 5, 10, 20, 25, 50, 100, 200, 250,
  // 500, 1000, 2000, 2500, 5000 , throw a RangeError exception.
  if (!IsValidRoundingIncrement(digit_options.rounding_increment)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kPropertyValueOutOfRange,
                      factory->roundingIncrement_string()),
        Nothing<NumberFormatDigitOptions>());
  }
  // 9. Let roundingMode be ? GetOption(options, "roundingMode", string,
  // "ceil", "floor", "expand", "trunc", "halfCeil", "halfFloor", "halfExpand",
  // "halfTrunc", "halfEven" , "halfExpand").
  Maybe<RoundingMode> maybe_rounding_mode = GetStringOption<RoundingMode>(
      isolate, options, "roundingMode", service,
      std::to_array<const std::string_view>(
          {"ceil", "floor", "expand", "trunc", "halfCeil", "halfFloor",
           "halfExpand", "halfTrunc", "halfEven"}),
      std::array{RoundingMode::kCeil, RoundingMode::kFloor,
                 RoundingMode::kExpand, RoundingMode::kTrunc,
                 RoundingMode::kHalfCeil, RoundingMode::kHalfFloor,
                 RoundingMode::kHalfExpand, RoundingMode::kHalfTrunc,
                 RoundingMode::kHalfEven},
      RoundingMode::kHalfExpand);
  MAYBE_RETURN(maybe_rounding_mode, Nothing<NumberFormatDigitOptions>());
  digit_options.rounding_mode = maybe_rounding_mode.FromJust();
  // 10. Let roundingPriority be ? GetOption(options, "roundingPriority",
  // "string", "auto", "morePrecision", "lessPrecision" , "auto").
  Maybe<RoundingPriority> maybe_rounding_priority =
      GetStringOption<RoundingPriority>(
          isolate, options, "roundingPriority", service,
          std::to_array<const std::string_view>(
              {"auto", "morePrecision", "lessPrecision"}),
          std::array{RoundingPriority::kAuto, RoundingPriority::kMorePrecision,
                     RoundingPriority::kLessPrecision},
          RoundingPriority::kAuto);
  MAYBE_RETURN(maybe_rounding_priority, Nothing<NumberFormatDigitOptions>());
  digit_options.rounding_priority = maybe_rounding_priority.FromJust();
  // 11. Let trailingZeroDisplay be ? GetOption(options, "trailingZeroDisplay",
  // string, "auto", "stripIfInteger" , "auto").
  Maybe<TrailingZeroDisplay> maybe_trailing_zero_display =
      GetStringOption<TrailingZeroDisplay>(
          isolate, options, "trailingZeroDisplay", service,
          std::to_array<const std::string_view>({"auto", "stripIfInteger"}),
          std::array{TrailingZeroDisplay::kAuto,
                     TrailingZeroDisplay::kStripIfInteger},
          TrailingZeroDisplay::kAuto);
  MAYBE_RETURN(maybe_trailing_zero_display,
               Nothing<NumberFormatDigitOptions>());
  digit_options.trailing_zero_display = maybe_trailing_zero_display.FromJust();
  // 12. NOTE: All fields required by SetNumberFormatDigitOptions have now been
  // read from options. The remainder of this AO interprets the options and may
  // throw exceptions.
  // 17. If mnsd is not undefined or mxsd is not undefined, then
  // a. Set hasSd to true.
  // 18. Else,
  // a. Set hasSd to false.
  bool has_sd =
      (!IsUndefined(*mnsd_obj, isolate)) || (!IsUndefined(*mxsd_obj, isolate));
  // 19. If mnfd is not undefined or mxfd is not undefined, then
  // a. Set hasFd to true.
  // 22. Else,
  // a. Set hasFd to false.
  bool has_fd =
      (!IsUndefined(*mnfd_obj, isolate)) || (!IsUndefined(*mxfd_obj, isolate));
  // 21. Let needSd be true.
  bool need_sd = true;
  // 22. Let needFd be true.
  bool need_fd = true;
  // 23. If roundingPriority is "auto", then
  if (RoundingPriority::kAuto == digit_options.rounding_priority) {
    // a. Set needSd to hasSd.
    need_sd = has_sd;
    // b. If needSd is true, or hasFd is false and notation is "compact", then
    if (need_sd || ((!has_fd) && notation_is_compact)) {
      // i. Set needFd to false.
      need_fd = false;
    }
  }
  // 24. If needSd is true, then
  if (need_sd) {
    // 24.a If hasSd is true, then
    if (has_sd) {
      // i. Set intlObj.[[MinimumSignificantDigits]] to ?
      // DefaultNumberOption(mnsd, 1, 21, 1).
      int mnsd;
      if (!DefaultNumberOption(isolate, mnsd_obj, 1, 21, 1,
                               factory->minimumSignificantDigits_string())
               .To(&mnsd)) {
        return Nothing<NumberFormatDigitOptions>();
      }
      digit_options.minimum_significant_digits = mnsd;
      // ii. Set intlObj.[[MaximumSignificantDigits]] to ?
      // DefaultNumberOption(mxsd, intlObj.[[MinimumSignificantDigits]], 21,
      // 21).
      int mxsd;
      if (!DefaultNumberOption(isolate, mxsd_obj, mnsd, 21, 21,
                               factory->maximumSignificantDigits_string())
               .To(&mxsd)) {
        return Nothing<NumberFormatDigitOptions>();
      }
      digit_options.maximum_significant_digits = mxsd;
    } else {
      // 24.b Else
      // 24.b.i Set intlObj.[[MinimumSignificantDigits]] to 1.
      digit_options.minimum_significant_digits = 1;
      // 24.b.ii Set intlObj.[[MaximumSignificantDigits]] to 21.
      digit_options.maximum_significant_digits = 21;
    }
  }
  DirectHandle<String> mxfd_str = factory->maximumFractionDigits_string();
  // 25. If needFd is true, then
  if (need_fd) {
    // a. If hasFd is true, then
    if (has_fd) {
      DirectHandle<String> mnfd_str = factory->minimumFractionDigits_string();
      // i. Let mnfd be ? DefaultNumberOption(mnfd, 0, 100, undefined).
      int mnfd;
      if (!DefaultNumberOption(isolate, mnfd_obj, 0, 100, -1, mnfd_str)
               .To(&mnfd)) {
        return Nothing<NumberFormatDigitOptions>();
      }
      // ii. Let mxfd be ? DefaultNumberOption(mxfd, 0, 100, undefined).
      int mxfd;
      if (!DefaultNumberOption(isolate, mxfd_obj, 0, 100, -1, mxfd_str)
               .To(&mxfd)) {
        return Nothing<NumberFormatDigitOptions>();
      }
      // iii. If mnfd is undefined, set mnfd to min(mnfdDefault, mxfd).
      if (IsUndefined(*mnfd_obj, isolate)) {
        mnfd = std::min(mnfd_default, mxfd);
      } else if (IsUndefined(*mxfd_obj, isolate)) {
        // iv. Else if mxfd is undefined, set mxfd to max(mxfdDefault,
        // mnfd).
        mxfd = std::max(mxfd_default, mnfd);
      } else if (mnfd > mxfd) {
        // v. Else if mnfd is greater than mxfd, throw a RangeError
        // exception.
        THROW_NEW_ERROR_RETURN_VALUE(
            isolate,
            NewRangeError(MessageTemplate::kPropertyValueOutOfRange, mxfd_str),
            Nothing<NumberFormatDigitOptions>());
      }
      // vi. Set intlObj.[[MinimumFractionDigits]] to mnfd.
      digit_options.minimum_fraction_digits = mnfd;
      // vii. Set intlObj.[[MaximumFractionDigits]] to mxfd.
      digit_options.maximum_fraction_digits = mxfd;
    } else { // b. Else
      // i. Set intlObj.[[MinimumFractionDigits]] to mnfdDefault.
      digit_options.minimum_fraction_digits = mnfd_default;
      // ii. Set intlObj.[[MaximumFractionDigits]] to mxfdDefault.
      digit_options.maximum_fraction_digits = mxfd_default;
    }
  }
  // 26. If needSd is false and needFd is false, then
  if ((!need_sd) && (!need_fd)) {
    // a. Set intlObj.[[MinimumFractionDigits]] to 0.
    digit_options.minimum_fraction_digits = 0;
    // b. Set intlObj.[[MaximumFractionDigits]] to 0.
    digit_options.maximum_fraction_digits = 0;
    // c. Set intlObj.[[MinimumSignificantDigits]] to 1.
    digit_options.minimum_significant_digits = 1;
    // d. Set intlObj.[[MaximumSignificantDigits]] to 2.
    digit_options.maximum_significant_digits = 2;
    // e. Set intlObj.[[RoundingType]] to morePrecision.
    digit_options.rounding_type = RoundingType::kMorePrecision;
    // 27. Else if roundingPriority is "morePrecision", then
  } else if (digit_options.rounding_priority ==
             RoundingPriority::kMorePrecision) {
    // i. Set intlObj.[[RoundingType]] to morePrecision.
    digit_options.rounding_type = RoundingType::kMorePrecision;
    // 28. Else if roundingPriority is "lessPrecision", then
  } else if (digit_options.rounding_priority ==
             RoundingPriority::kLessPrecision) {
    // i. Set intlObj.[[RoundingType]] to lessPrecision.
    digit_options.rounding_type = RoundingType::kLessPrecision;
    // 29. Else if hasSd, then
  } else if (has_sd) {
    // i. Set intlObj.[[RoundingType]] to significantDigits.
    digit_options.rounding_type = RoundingType::kSignificantDigits;
    // 30. Else,
  } else {
    // i.Set intlObj.[[RoundingType]] to fractionDigits.
    digit_options.rounding_type = RoundingType::kFractionDigits;
  }
  // 31. If roundingIncrement is not 1, then
  if (digit_options.rounding_increment != 1) {
    // a. If intlObj.[[RoundingType]] is not fractionDigits, throw a TypeError
    // exception.
    if (digit_options.rounding_type != RoundingType::kFractionDigits) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate, NewTypeError(MessageTemplate::kBadRoundingType),
          Nothing<NumberFormatDigitOptions>());
    }
    // b. If intlObj.[[MaximumFractionDigits]] is not equal to
    // intlObj.[[MinimumFractionDigits]], throw a RangeError exception.
    if (digit_options.maximum_fraction_digits !=
        digit_options.minimum_fraction_digits) {
      THROW_NEW_ERROR_RETURN_VALUE(
          isolate,
          NewRangeError(MessageTemplate::kPropertyValueOutOfRange, mxfd_str),
          Nothing<NumberFormatDigitOptions>());
    }
  }
  return Just(digit_options);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DefaultNumberOption(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::GetNumberOption(), v8::internal::JSReceiver::GetProperty(), v8::internal::anonymous_namespace{intl-objects.cc}::IsValidRoundingIncrement(), v8::Just(), kAuto, kCeil, kExpand, kFloor, kFractionDigits, kHalfCeil, kHalfEven, kHalfExpand, kHalfFloor, kHalfTrunc, kLessPrecision, kMorePrecision, kSignificantDigits, kStripIfInteger, kTrunc, v8::internal::Intl::NumberFormatDigitOptions::maximum_fraction_digits, v8::internal::Intl::NumberFormatDigitOptions::maximum_significant_digits, MAYBE_RETURN, v8::internal::Intl::NumberFormatDigitOptions::minimum_fraction_digits, v8::internal::Intl::NumberFormatDigitOptions::minimum_integer_digits, v8::internal::Intl::NumberFormatDigitOptions::minimum_significant_digits, v8::internal::Intl::NumberFormatDigitOptions::rounding_increment, v8::internal::Intl::NumberFormatDigitOptions::rounding_mode, v8::internal::Intl::NumberFormatDigitOptions::rounding_priority, v8::internal::Intl::NumberFormatDigitOptions::rounding_type, THROW_NEW_ERROR_RETURN_VALUE, v8::Maybe< T >::To(), and v8::internal::Intl::NumberFormatDigitOptions::trailing_zero_display.
Referenced by v8::internal::JSPluralRules::New(), and v8::internal::JSNumberFormat::New().
SetTextToBreakIterator()
DirectHandle< Managed< icu::UnicodeString > > v8::internal::Intl::SetTextToBreakIterator (Isolate * isolate, DirectHandle< String > text, icu::BreakIterator * break_iterator) [static]
Definition at line 2599 of file intl-objects.cc.
                                      {
  text = String::Flatten(isolate, text);
  std::shared_ptr<icu::UnicodeString> u_text{static_cast<icu::UnicodeString*>(
      Intl::ToICUUnicodeString(isolate, text).clone())};
  DirectHandle<Managed<icu::UnicodeString>> new_u_text =
      Managed<icu::UnicodeString>::From(isolate, 0, u_text);
  break_iterator->setText(*u_text);
  return new_u_text;
}
References v8::internal::Managed< CppType >::From(), and ToICUUnicodeString().
Referenced by v8::internal::JSV8BreakIterator::AdoptText(), and v8::internal::JSSegments::Create().
SourceString()
DirectHandle< String > v8::internal::Intl::SourceString (Isolate * isolate, FormatRangeSource source) [static]
Definition at line 3044 of file intl-objects.cc.
                                                                  {
  switch (source) {
    case FormatRangeSource::kShared:
      return isolate->factory()->shared_string();
    case FormatRangeSource::kStartRange:
      return isolate->factory()->startRange_string();
    case FormatRangeSource::kEndRange:
      return isolate->factory()->endRange_string();
  }
}
References v8::internal::Isolate::factory(), kEndRange, kShared, and kStartRange.
Referenced by v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange(), and v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts().
StringLocaleCompare()
std::optional< int > v8::internal::Intl::StringLocaleCompare (Isolate * isolate, DirectHandle< String > s1, DirectHandle< String > s2, DirectHandle< Object > locales, DirectHandle< Object > options, const char * method_name) [static]
Definition at line 999 of file intl-objects.cc.
                                                                      {
  // We only cache the instance when locales is a string/undefined and
  // options is undefined, as that is the only case when the specified
  // side-effects of examining those arguments are unobservable.
  const bool can_cache =
      (IsString(*locales) || IsUndefined(*locales, isolate)) &&
      IsUndefined(*options, isolate);
  // We may be able to take the fast path, depending on the `locales` and
  // `options` arguments.
  const CompareStringsOptions compare_strings_options =
      CompareStringsOptionsFor(isolate, locales, options);
  if (can_cache) {
    // Both locales and options are undefined, check the cache.
    icu::Collator* cached_icu_collator =
        static_cast<icu::Collator*>(isolate->get_cached_icu_object(
            Isolate::ICUObjectCacheType::kDefaultCollator, locales));
    // We may use the cached icu::Collator for a fast path.
    if (cached_icu_collator != nullptr) {
      return Intl::CompareStrings(isolate, *cached_icu_collator, string1,
                                  string2, compare_strings_options);
    }
  }
  DirectHandle<JSFunction> constructor(
      Cast<JSFunction>(
          isolate->context()->native_context()->intl_collator_function()),
      isolate);
  DirectHandle<JSCollator> collator;
  MaybeDirectHandle<JSCollator> maybe_collator =
      New<JSCollator>(isolate, constructor, locales, options, method_name);
  if (!maybe_collator.ToHandle(&collator)) return {};
  if (can_cache) {
    isolate->set_icu_object_in_cache(
        Isolate::ICUObjectCacheType::kDefaultCollator, locales,
        std::static_pointer_cast<icu::UMemory>(
            collator->icu_collator()->get()));
  }
  icu::Collator* icu_collator = collator->icu_collator()->raw();
  return Intl::CompareStrings(isolate, *icu_collator, string1, string2,
                              compare_strings_options);
}
References CompareStrings(), CompareStringsOptionsFor(), v8::internal::Isolate::context(), and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::BUILTIN().
StringLocaleConvertCase()
MaybeDirectHandle< String > v8::internal::Intl::StringLocaleConvertCase (Isolate * isolate, DirectHandle< String > s, bool is_upper, DirectHandle< Object > locales) [static]
Definition at line 903 of file intl-objects.cc.
                                  {
  std::vector<std::string> requested_locales;
  if (!CanonicalizeLocaleList(isolate, locales, true).To(&requested_locales))
    return {};
  std::string requested_locale = requested_locales.empty()
                                     ? isolate->DefaultLocale()
                                     : requested_locales[0];
  size_t dash = requested_locale.find('-');
  if (dash != std::string::npos) {
    requested_locale = requested_locale.substr(0, dash);
  }
  // Primary language tag can be up to 8 characters long in theory.
  // https://tools.ietf.org/html/bcp47#section-2.2.1
  DCHECK_LE(requested_locale.length(), 8);
  s = String::Flatten(isolate, s);
  // All the languages requiring special-handling have two-letter codes.
  // Note that we have to check for '!= 2' here because private-use language
  // tags (x-foo) or grandfathered irregular tags (e.g. i-enochian) would have
  // only 'x' or 'i' when they get here.
  if (V8_UNLIKELY(requested_locale.length() != 2)) {
    if (to_upper) {
      return ConvertToUpper(isolate, s);
    }
    return ConvertToLower(isolate, s);
  }
  // TODO(jshin): Consider adding a fast path for ASCII or Latin-1. The fastpath
  // in the root locale needs to be adjusted for az, lt and tr because even case
  // mapping of ASCII range characters are different in those locales.
  // Greek (el) does not require any adjustment.
  if (V8_UNLIKELY((requested_locale == "tr") || (requested_locale == "el") ||
                  (requested_locale == "lt") || (requested_locale == "az"))) {
    return LocaleConvertCase(isolate, s, to_upper, requested_locale.c_str());
  } else {
    if (to_upper) {
      return ConvertToUpper(isolate, s);
    }
    return ConvertToLower(isolate, s);
  }
}
References CanonicalizeLocaleList(), ConvertToLower(), ConvertToUpper(), DCHECK_LE, v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase(), v8::internal::string, and V8_UNLIKELY.
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
SupportedLocalesOf()
MaybeDirectHandle< JSObject > v8::internal::Intl::SupportedLocalesOf (Isolate * isolate, const char * method_name, const std::set< std::string > & available_locales, DirectHandle< Object > locales_in, DirectHandle< Object > options_in) [static]
Definition at line 2352 of file intl-objects.cc.
                                                                {
  // Let availableLocales be %Collator%.[[AvailableLocales]].
  // Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> requested_locales =
      CanonicalizeLocaleList(isolate, locales, false);
  MAYBE_RETURN(requested_locales, {});
  // Return ? SupportedLocales(availableLocales, requestedLocales, options).
  return SupportedLocales(isolate, method_name, available_locales,
                          requested_locales.FromJust(), options);
}
References CanonicalizeLocaleList(), v8::Maybe< T >::FromJust(), MAYBE_RETURN, and v8::internal::anonymous_namespace{intl-objects.cc}::SupportedLocales().
Referenced by v8::internal::BUILTIN().
SupportedValuesOf()
MaybeDirectHandle< JSArray > v8::internal::Intl::SupportedValuesOf (Isolate * isolate, DirectHandle< Object > key) [static]
Definition at line 2304 of file intl-objects.cc.
                                                    {
  Factory* factory = isolate->factory();
  // 1. 1. Let key be ? ToString(key).
  DirectHandle<String> key_str;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, key_str,
                             Object::ToString(isolate, key_obj));
  // 2. If key is "calendar", then
  if (factory->calendar_string()->Equals(*key_str)) {
    // a. Let list be ! AvailableCalendars().
    return Intl::AvailableCalendars(isolate);
  }
  // 3. Else if key is "collation", then
  if (factory->collation_string()->Equals(*key_str)) {
    // a. Let list be ! AvailableCollations().
    return AvailableCollations(isolate);
  }
  // 4. Else if key is "currency", then
  if (factory->currency_string()->Equals(*key_str)) {
    // a. Let list be ! AvailableCurrencies().
    return AvailableCurrencies(isolate);
  }
  // 5. Else if key is "numberingSystem", then
  if (factory->numberingSystem_string()->Equals(*key_str)) {
    // a. Let list be ! AvailableNumberingSystems().
    return AvailableNumberingSystems(isolate);
  }
  // 6. Else if key is "timeZone", then
  if (factory->timeZone_string()->Equals(*key_str)) {
    // a. Let list be ! AvailableTimeZones().
    return AvailableTimeZones(isolate);
  }
  // 7. Else if key is "unit", then
  if (factory->unit_string()->Equals(*key_str)) {
    // a. Let list be ! AvailableUnits().
    return AvailableUnits(isolate);
  }
  // 8. Else,
  // a. Throw a RangeError exception.
  // 9. Return ! CreateArrayFromList(list).
  THROW_NEW_ERROR(
      isolate,
      NewRangeError(MessageTemplate::kInvalid,
                    factory->NewStringFromStaticChars("key"), key_str));
}
References ASSIGN_RETURN_ON_EXCEPTION, AvailableCalendars(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableCollations(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableCurrencies(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableNumberingSystems(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableTimeZones(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{isolate.cc}::kInvalid, v8::internal::Factory::NewStringFromStaticChars(), THROW_NEW_ERROR, and v8::Value::ToString().
Referenced by v8::internal::BUILTIN().
TimeZoneIdFromIndex()
std::string v8::internal::Intl::TimeZoneIdFromIndex (int32_t index) [static]
Definition at line 2960 of file intl-objects.cc.
                                                 {
#ifdef V8_TEMPORAL_SUPPORT
  // UTC index is 0
  // TODO(b/401065166) Potentially store constant somewhere
  if (index == 0) {
    return "UTC";
  }
#endif // V8_TEMPORAL_SUPPORT
  std::unique_ptr<icu::StringEnumeration> enumeration(
      icu::TimeZone::createEnumeration());
  int32_t curr = 0;
  const char* id;
  UErrorCode status = U_ZERO_ERROR;
  while (U_SUCCESS(status) && curr < index &&
         ((id = enumeration->next(nullptr, status)) != nullptr)) {
    CHECK(U_SUCCESS(status));
    curr++;
  }
  CHECK(U_SUCCESS(status));
  CHECK(id != nullptr);
  return id;
}
References CHECK, v8::internal::index, and v8::internal::status.
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::CreateBasicTimeZoneFromIndex().
ToICUUnicodeString()
icu::UnicodeString v8::internal::Intl::ToICUUnicodeString (Isolate * isolate, DirectHandle< String > string, int offset = 0) [static]
Definition at line 219 of file intl-objects.cc.
                                                        {
  DCHECK(string->IsFlat());
  DisallowGarbageCollection no_gc;
  std::unique_ptr<base::uc16[]> sap;
  // Short one-byte strings can be expanded on the stack to avoid allocating a
  // temporary buffer.
  constexpr unsigned int kShortStringSize = 80;
  UChar short_string_buffer[kShortStringSize];
  const UChar* uchar_buffer = nullptr;
  const String::FlatContent& flat = string->GetFlatContent(no_gc);
  // We read the length from the heap, so it may be untrusted (in the sandbox
  // attacker model) and we therefore need to use an unsigned int here when
  // comparing it against the kShortStringSize.
  uint32_t length = string->length();
  // As the length is untrusted, we should also double-check the offset here.
  // Technically it's fine for the offset to go out-of-bounds since it will
  // only cause an OOB read (not write) outside the sandbox, but we still want
  // to avoid these issues. An alternative would be for this function to
  // allocate temporary buffers inside the sandbox, then there would be no need
  // for additional bounds checks here (since we're using 32-bit sizes/offsets).
  SBXCHECK_LE(offset, length);
  if (flat.IsOneByte() && length <= kShortStringSize) {
    CopyChars(short_string_buffer, flat.ToOneByteVector().begin(), length);
    uchar_buffer = short_string_buffer;
  } else {
    uchar_buffer = GetUCharBufferFromFlat(flat, &sap, length);
  }
  return icu::UnicodeString(uchar_buffer + offset, length - offset);
}
References v8::base::Vector< T >::begin(), v8::internal::CopyChars(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{intl-objects.cc}::GetUCharBufferFromFlat(), v8::internal::String::FlatContent::IsOneByte(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SBXCHECK_LE, v8::internal::string, and v8::internal::String::FlatContent::ToOneByteVector().
Referenced by CompareStrings(), Normalize(), SetTextToBreakIterator(), and v8::internal::anonymous_namespace{js-list-format.cc}::ToUnicodeStringArray().
ToJSArray()
MaybeDirectHandle< JSArray > v8::internal::Intl::ToJSArray (Isolate * isolate, const char * unicode_key, icu::StringEnumeration * enumeration, const std::function< bool(const char *)> & removes, bool sort) [static]
Definition at line 2897 of file intl-objects.cc.
                                                              {
  UErrorCode status = U_ZERO_ERROR;
  std::vector<std::string> array;
  for (const char* item = enumeration->next(nullptr, status);
       U_SUCCESS(status) && item != nullptr;
       item = enumeration->next(nullptr, status)) {
    if (unicode_key != nullptr) {
      item = uloc_toUnicodeLocaleType(unicode_key, item);
    }
    if (removes == nullptr || !(removes)(item)) {
      array.push_back(item);
    }
  }
  if (sort) {
    std::sort(array.begin(), array.end());
  }
  return VectorToJSArray(isolate, array);
}
References v8::base::sort(), v8::internal::status, and v8::internal::anonymous_namespace{intl-objects.cc}::VectorToJSArray().
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::AvailableCollations(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableNumberingSystems(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableTimeZones(), v8::internal::GetKeywordValuesFromLocale(), and v8::internal::JSLocale::GetTimeZones().
ToLanguageTag()
Maybe< std::string > v8::internal::Intl::ToLanguageTag (const icu::Locale & locale) [static]
Definition at line 651 of file intl-objects.cc.
                                                            {
  UErrorCode status = U_ZERO_ERROR;
  std::string res = locale.toLanguageTag<std::string>(status);
  if (U_FAILURE(status)) {
    return Nothing<std::string>();
  }
  DCHECK(U_SUCCESS(status));
  return Just(res);
}
References v8::internal::DCHECK(), v8::Just(), v8::internal::status, and v8::internal::string.
Referenced by v8::internal::JSLocale::BaseName(), v8::internal::anonymous_namespace{js-collator.cc}::CollatorAvailableLocales::CollatorAvailableLocales(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSNumberFormat::New(), v8::internal::JSCollator::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::JSDurationFormat::ResolvedOptions(), ResolveLocale(), v8::internal::JSLocale::ToString(), and ValidateAndCanonicalizeUnicodeLocaleId().
ToLatin1LowerTable()
const uint8_t * v8::internal::Intl::ToLatin1LowerTable () [static]
Definition at line 217 of file intl-objects.cc.
{ return &kToLower[0]; }
References v8::internal::anonymous_namespace{intl-objects.cc}::kToLower.
ToString() [1/2]
MaybeHandle< String > v8::internal::Intl::ToString (Isolate * isolate, const icu::UnicodeString & string) [static]
Definition at line 505 of file intl-objects.cc.
                                                                   {
  return isolate->factory()->NewStringFromTwoByte(base::Vector<const uint16_t>(
      reinterpret_cast<const uint16_t*>(string.getBuffer()), string.length()));
}
References v8::internal::Isolate::factory(), v8::internal::length, and v8::internal::Factory::NewStringFromTwoByte().
Referenced by v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddLiteral(), v8::internal::anonymous_namespace{js-date-time-format.cc}::AddPartForFormatRange(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::AddUnit(), v8::internal::anonymous_namespace{js-number-format.cc}::ConstructParts(), v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FieldPositionIteratorToArray(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatDateTime(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatMillisecondsByKindToString(), v8::internal::anonymous_namespace{js-list-format.cc}::FormattedListToJSArray(), v8::internal::FormattedListToJSArray(), FormattedToString(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedToString(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToString(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatToString(), v8::internal::JSNumberFormat::New(), Normalize(), v8::internal::JSDisplayNames::Of(), v8::internal::JSDurationFormat::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::JSPluralRules::ResolvePlural(), v8::internal::JSPluralRules::ResolvePluralRange(), v8::internal::JSDateTimeFormat::TimeZoneIdToString(), and ToString().
ToString() [2/2]
MaybeDirectHandle< String > v8::internal::Intl::ToString (Isolate * isolate, const icu::UnicodeString & string, int32_t begin, int32_t end) [static]
Definition at line 511 of file intl-objects.cc.
                                                                     {
  return Intl::ToString(isolate, string.tempSubStringBetween(begin, end));
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), and ToString().
ValidateAndCanonicalizeUnicodeLocaleId()
Maybe< std::string > v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId (Isolate * isolate, std::string_view locale) [static]
Definition at line 735 of file intl-objects.cc.
                                                {
  if (!IsStructurallyValidLanguageTag(locale_in)) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kInvalidLanguageTag,
                      isolate->factory()->NewStringFromAsciiChecked(locale_in)),
        Nothing<std::string>());
  }
  std::string locale(locale_in);
  // Optimize for the most common case: a 2-letter language code in the
  // canonical form/lowercase that is not one of the deprecated codes
  // (in, iw, ji, jw). Don't check for ~70 of 3-letter deprecated language
  // codes. Instead, let them be handled by ICU in the slow path. However,
  // fast-track 'fil' (3-letter canonical code).
  if ((IsTwoLetterLanguage(locale) && !IsDeprecatedOrLegacyLanguage(locale)) ||
      locale == "fil") {
    return Just(locale);
  }
  // Because per BCP 47 2.1.1 language tags are case-insensitive, lowercase
  // the input before any more check.
  std::transform(locale.begin(), locale.end(), locale.begin(), ToAsciiLower);
  // // ECMA 402 6.2.3
  // TODO(jshin): uloc_{for,to}LanguageTag can fail even for a structurally
  // valid language tag if it's too long (much longer than 100 chars). Even if
  // we allocate a longer buffer, ICU will still fail if it's too long. Either
  // propose to Ecma 402 to put a limit on the locale length or change ICU to
  // handle long locale names better. See
  // https://unicode-org.atlassian.net/browse/ICU-13417
  UErrorCode error = U_ZERO_ERROR;
  // uloc_forLanguageTag checks the structural validity. If the input BCP47
  // language tag is parsed all the way to the end, it indicates that the input
  // is structurally valid. Due to a couple of bugs, we can't use it
  // without Chromium patches or ICU 62 or earlier.
  icu::Locale icu_locale = icu::Locale::forLanguageTag(locale.c_str(), error);
  if (U_FAILURE(error) || icu_locale.isBogus()) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(
            MessageTemplate::kInvalidLanguageTag,
            isolate->factory()->NewStringFromAsciiChecked(locale.c_str())),
        Nothing<std::string>());
  }
  // Use LocaleBuilder to validate locale.
  icu_locale = icu::LocaleBuilder().setLocale(icu_locale).build(error);
  icu_locale.canonicalize(error);
  if (U_FAILURE(error) || icu_locale.isBogus()) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(
            MessageTemplate::kInvalidLanguageTag,
            isolate->factory()->NewStringFromAsciiChecked(locale.c_str())),
        Nothing<std::string>());
  }
  Maybe<std::string> maybe_to_language_tag = Intl::ToLanguageTag(icu_locale);
  if (maybe_to_language_tag.IsNothing()) {
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(
            MessageTemplate::kInvalidLanguageTag,
            isolate->factory()->NewStringFromAsciiChecked(locale.c_str())),
        Nothing<std::string>());
  }
  return maybe_to_language_tag;
}
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{intl-objects.cc}::IsDeprecatedOrLegacyLanguage(), v8::Maybe< T >::IsNothing(), v8::internal::anonymous_namespace{intl-objects.cc}::IsStructurallyValidLanguageTag(), v8::internal::anonymous_namespace{intl-objects.cc}::IsTwoLetterLanguage(), v8::Just(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::string, THROW_NEW_ERROR_RETURN_VALUE, v8::internal::ToAsciiLower(), and ToLanguageTag().
Referenced by v8::internal::anonymous_namespace{intl-objects.cc}::CanonicalizeLanguageTag(), and v8::Isolate::ValidateAndCanonicalizeUnicodeLocaleId().
Member Data Documentation
kAsciiCollationWeightsLength
const int v8::internal::Intl::kAsciiCollationWeightsLength = kCollationWeightsLength [static]
Definition at line 395 of file intl-objects.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/intl-objects.h
/mnt/V8SourceCode/src/objects/intl-objects.cc
/mnt/V8SourceCode/src/objects/js-locale.cc
/mnt/V8SourceCode/src/objects/js-number-format.cc