v8::internal::compiler::turboshaft::Zip< Iterables > Class Template Reference
#include <assembler.h>
Public Types
using value_type = std::tuple< typename Iterables::value_type... >
using iterator_type = std::tuple< typename Iterables::iterator_type... >
Public Member Functions
Zip (Iterables... iterables)
template<typename A >
iterator_type Begin (A &assembler)
template<typename A >
OptionalV< Word32 > IsEnd (A &assembler, iterator_type current_iterator)
template<typename A >
iterator_type Advance (A &assembler, iterator_type current_iterator)
template<typename A >
value_type Dereference (A &assembler, iterator_type current_iterator)
Private Attributes
std::tuple< Iterables... > iterables_
Detailed Description
template<typename... Iterables>
class v8::internal::compiler::turboshaft::Zip< Iterables >
Definition at line 276 of file assembler.h.
Member Typedef Documentation
iterator_type
template<typename... Iterables>
using v8::internal::compiler::turboshaft::Zip< Iterables >::iterator_type = std::tuple<typename Iterables::iterator_type...>
Definition at line 279 of file assembler.h.
value_type
template<typename... Iterables>
using v8::internal::compiler::turboshaft::Zip< Iterables >::value_type = std::tuple<typename Iterables::value_type...>
Definition at line 278 of file assembler.h.
Constructor & Destructor Documentation
Zip()
template<typename... Iterables>
v8::internal::compiler::turboshaft::Zip< Iterables >::Zip (Iterables... iterables) [inline], [explicit]
Definition at line 281 of file assembler.h.
: iterables_(std::move(iterables)...) {}
Member Function Documentation
Advance()
template<typename... Iterables>
template<typename A >
iterator_type v8::internal::compiler::turboshaft::Zip< Iterables >::Advance (A & assembler, iterator_type current_iterator) [inline]
Definition at line 309 of file assembler.h.
                                                                      {
    return base::tuple_map2(iterables_, current_iterator,
                            [&assembler](auto& it, auto current) {
                              return it.Advance(assembler, current);
                            });
  }
References v8::base::tuple_map2().
Begin()
template<typename... Iterables>
template<typename A >
iterator_type v8::internal::compiler::turboshaft::Zip< Iterables >::Begin (A & assembler) [inline]
Definition at line 284 of file assembler.h.
                                    {
    return base::tuple_map(
        iterables_, [&assembler](auto& it) { return it.Begin(assembler); });
  }
References v8::base::tuple_map().
Dereference()
template<typename... Iterables>
template<typename A >
value_type v8::internal::compiler::turboshaft::Zip< Iterables >::Dereference (A & assembler, iterator_type current_iterator) [inline]
Definition at line 317 of file assembler.h.
                                                                       {
    return base::tuple_map2(iterables_, current_iterator,
                            [&assembler](auto& it, auto current) {
                              return it.Dereference(assembler, current);
                            });
  }
References v8::base::tuple_map2().
IsEnd()
template<typename... Iterables>
template<typename A >
OptionalV<Word32> v8::internal::compiler::turboshaft::Zip< Iterables >::IsEnd (A & assembler, iterator_type current_iterator) [inline]
Definition at line 290 of file assembler.h.
                                                                        {
    // TODO(nicohartmann): Currently we don't short-circuit the disjunction here
    // because that's slightly more difficult to do with the current `IsEnd`
    // predicate. We can consider making this more powerful if we see use cases.
    auto results = base::tuple_map2(iterables_, current_iterator,
                                    [&assembler](auto& it, auto current) {
                                      return it.IsEnd(assembler, current);
                                    });
    return base::tuple_fold(
        OptionalV<Word32>::Nullopt(), results,
        [&assembler](OptionalV<Word32> acc, OptionalV<Word32> next) {
          if (!next.has_value()) return acc;
          if (!acc.has_value()) return next;
          return OptionalV(
              assembler.Word32BitwiseOr(acc.value(), next.value()));
        });
  }
References v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), v8::internal::if(), v8::base::tuple_fold(), v8::base::tuple_map2(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Member Data Documentation
iterables_
template<typename... Iterables>
std::tuple<Iterables...> v8::internal::compiler::turboshaft::Zip< Iterables >::iterables_ [private]
Definition at line 325 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h