v8::internal::SamplingCircularQueue< T, Length > Class Template Reference
#include <circular-queue.h>
Classes
struct Entry
Public Member Functions
SamplingCircularQueue ()
~SamplingCircularQueue ()
SamplingCircularQueue (const SamplingCircularQueue &)=delete
SamplingCircularQueue & operator= (const SamplingCircularQueue &)=delete
T * StartEnqueue ()
void FinishEnqueue ()
T * Peek ()
void Remove ()
Private Types
enum { kEmpty
, kFull
 }
Private Member Functions
Entry * Next (Entry *entry)
Private Attributes
Entry buffer_ [Length]
Entry * enqueue_pos_
Entry * dequeue_pos_
Detailed Description
template<typename T, unsigned Length>
class v8::internal::SamplingCircularQueue< T, Length >
Definition at line 21 of file circular-queue.h.
Member Enumeration Documentation
anonymous enum
template<typename T , unsigned Length>
anonymous enum [private]
Enumerator
kEmpty
kFull
Definition at line 45 of file circular-queue.h.
       {
    kEmpty, // Marks clean (processed) entries.
    kFull // Marks entries already filled by the producer but not yet
             // completely processed by the consumer.
  };
Constructor & Destructor Documentation
SamplingCircularQueue() [1/2]
template<typename T , unsigned L>
v8::internal::SamplingCircularQueue< T, L >::SamplingCircularQueue
Definition at line 15 of file circular-queue-inl.h.
    : enqueue_pos_(buffer_),
      dequeue_pos_(buffer_) {
}
 SamplingCircularQueue()
template<typename T , unsigned L>
v8::internal::SamplingCircularQueue< T, L >::~SamplingCircularQueue () [default]
SamplingCircularQueue() [2/2]
template<typename T , unsigned Length>
v8::internal::SamplingCircularQueue< T, Length >::SamplingCircularQueue (const SamplingCircularQueue< T, Length > &) [delete]
Member Function Documentation
FinishEnqueue()
template<typename T , unsigned L>
void v8::internal::SamplingCircularQueue< T, L >::FinishEnqueue
Definition at line 51 of file circular-queue-inl.h.
                                                {
  base::Release_Store(&enqueue_pos_->marker, kFull);
  enqueue_pos_ = Next(enqueue_pos_);
}
References v8::internal::kFull, v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next(), and v8::base::Release_Store().
Next()
template<typename T , unsigned L>
SamplingCircularQueue< T, L >::Entry * v8::internal::SamplingCircularQueue< T, L >::Next (Entry * entry) [private]
Definition at line 58 of file circular-queue-inl.h.
                  {
  Entry* next = entry + 1;
  if (next == &buffer_[L]) return buffer_;
  return next;
}
References v8::internal::L.
operator=()
template<typename T , unsigned Length>
SamplingCircularQueue& v8::internal::SamplingCircularQueue< T, Length >::operator= (const SamplingCircularQueue< T, Length > &) [delete]
Peek()
template<typename T , unsigned L>
T * v8::internal::SamplingCircularQueue< T, L >::Peek
Definition at line 24 of file circular-queue-inl.h.
                                     {
  base::SeqCst_MemoryFence();
  if (base::Acquire_Load(&dequeue_pos_->marker) == kFull) {
    return &dequeue_pos_->record;
  }
  return nullptr;
}
References v8::base::Acquire_Load(), v8::internal::kFull, and v8::base::SeqCst_MemoryFence().
Remove()
template<typename T , unsigned L>
void v8::internal::SamplingCircularQueue< T, L >::Remove
Definition at line 34 of file circular-queue-inl.h.
                                         {
  base::Release_Store(&dequeue_pos_->marker, kEmpty);
  dequeue_pos_ = Next(dequeue_pos_);
}
StartEnqueue()
template<typename T , unsigned L>
T * v8::internal::SamplingCircularQueue< T, L >::StartEnqueue
Definition at line 41 of file circular-queue-inl.h.
                                             {
  base::SeqCst_MemoryFence();
  if (base::Acquire_Load(&enqueue_pos_->marker) == kEmpty) {
    return &enqueue_pos_->record;
  }
  return nullptr;
}
Member Data Documentation
buffer_
template<typename T , unsigned Length>
Entry v8::internal::SamplingCircularQueue< T, Length >::buffer_[Length] [private]
Definition at line 59 of file circular-queue.h.
dequeue_pos_
template<typename T , unsigned Length>
Entry* v8::internal::SamplingCircularQueue< T, Length >::dequeue_pos_ [private]
Definition at line 61 of file circular-queue.h.
enqueue_pos_
template<typename T , unsigned Length>
Entry* v8::internal::SamplingCircularQueue< T, Length >::enqueue_pos_ [private]
Definition at line 60 of file circular-queue.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/circular-queue.h
/mnt/V8SourceCode/src/profiler/circular-queue-inl.h