v8::internal::FastConstructStubFrameInfo Class Reference
#include <frames.h>
Public Member Functions
uint32_t frame_size_in_bytes_without_fixed () const
uint32_t frame_size_in_bytes () const
Static Public Member Functions
static FastConstructStubFrameInfo Precise (bool is_topmost)
static FastConstructStubFrameInfo Conservative ()
Private Member Functions
FastConstructStubFrameInfo (bool is_topmost)
Private Attributes
uint32_t frame_size_in_bytes_without_fixed_
uint32_t frame_size_in_bytes_
Detailed Description
Definition at line 1950 of file frames.h.
Constructor & Destructor Documentation
FastConstructStubFrameInfo()
v8::internal::FastConstructStubFrameInfo::FastConstructStubFrameInfo (bool is_topmost) [explicit], [private]
Definition at line 4263 of file frames.cc.
                                                                      {
  // If the construct frame appears to be topmost we should ensure that the
  // value of result register is preserved during continuation execution.
  // We do this here by "pushing" the result of the constructor function to
  // the top of the reconstructed stack and popping it in
  // {Builtin::kNotifyDeoptimized}.
  static constexpr int kTopOfStackPadding = TopOfStackRegisterPaddingSlots();
  static constexpr int kTheResult = 1;
  const int adjusted_height =
      ArgumentPaddingSlots(1) +
      (is_topmost ? kTheResult + kTopOfStackPadding : 0);
  frame_size_in_bytes_without_fixed_ = adjusted_height * kSystemPointerSize;
  frame_size_in_bytes_ = frame_size_in_bytes_without_fixed_ +
                         FastConstructFrameConstants::kFixedFrameSize;
}
References v8::internal::ArgumentPaddingSlots(), v8::internal::TypedFrameConstants::kFixedFrameSize, v8::internal::kSystemPointerSize, and v8::internal::anonymous_namespace{frames.cc}::TopOfStackRegisterPaddingSlots().
Referenced by Conservative(), and Precise().
Member Function Documentation
Conservative()
static FastConstructStubFrameInfo v8::internal::FastConstructStubFrameInfo::Conservative () [inline], [static]
Definition at line 1956 of file frames.h.
                                                   {
    // Assume it is the top most frame when conservative.
    return FastConstructStubFrameInfo(true);
  }
References FastConstructStubFrameInfo().
Referenced by v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), and v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes().
frame_size_in_bytes()
uint32_t v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes () const [inline]
Definition at line 1964 of file frames.h.
{ return frame_size_in_bytes_; }
References frame_size_in_bytes_.
Referenced by v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), and v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes().
frame_size_in_bytes_without_fixed()
uint32_t v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes_without_fixed () const [inline]
Definition at line 1961 of file frames.h.
                                                     {
    return frame_size_in_bytes_without_fixed_;
  }
References frame_size_in_bytes_without_fixed_.
Referenced by v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame().
Precise()
static FastConstructStubFrameInfo v8::internal::FastConstructStubFrameInfo::Precise (bool is_topmost) [inline], [static]
Definition at line 1952 of file frames.h.
                                                             {
    return FastConstructStubFrameInfo(is_topmost);
  }
References FastConstructStubFrameInfo().
Referenced by v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame().
Member Data Documentation
frame_size_in_bytes_
uint32_t v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes_ [private]
Definition at line 1970 of file frames.h.
Referenced by frame_size_in_bytes().
frame_size_in_bytes_without_fixed_
uint32_t v8::internal::FastConstructStubFrameInfo::frame_size_in_bytes_without_fixed_ [private]
Definition at line 1969 of file frames.h.
Referenced by frame_size_in_bytes_without_fixed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc