v8::internal::maglev::LoadDoubleField Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadDoubleField (uint64_t bitfield, int offset)
int offset () const
Input & object_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kObjectIndex = 0
Private Types
using Base = FixedInputValueNodeT< 1, LoadDoubleField >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 8203 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadDoubleField::Base = FixedInputValueNodeT<1, LoadDoubleField> [private]
Definition at line 8204 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadDoubleField()
v8::internal::maglev::LoadDoubleField::LoadDoubleField (uint64_t bitfield, int offset) [inline], [explicit]
Definition at line 8207 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::LoadDoubleField::GenerateCode (MaglevAssembler * , const ProcessingState &)
object_input()
Input& v8::internal::maglev::LoadDoubleField::object_input () [inline]
Definition at line 8218 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::LoadDoubleField::offset () const [inline]
Definition at line 8215 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::LoadDoubleField::options () const [inline]
Definition at line 8224 of file maglev-ir.h.
{ return std::tuple{offset()}; }
PrintParams()
void v8::internal::maglev::LoadDoubleField::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8191 of file maglev-ir.cc.
                                                                             {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::LoadDoubleField::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadDoubleField::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 8213 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::LoadDoubleField::kObjectIndex = 0 [static], [constexpr]
Definition at line 8217 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadDoubleField::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanRead() | OpProperties::Float64()
Definition at line 8210 of file maglev-ir.h.
offset_
const int v8::internal::maglev::LoadDoubleField::offset_ [private]
Definition at line 8227 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc