v8::Unwinder Class Reference
Various helpers for skipping over V8 frames in a given stack.
#include <v8-unwinder.h>
Static Public Member Functions
static bool TryUnwindV8Frames (const JSEntryStubs &entry_stubs, size_t code_pages_length, const MemoryRange *code_pages, RegisterState *register_state, const void *stack_base)
Attempt to unwind the stack to the most recent C++ frame.
static bool PCIsInV8 (size_t code_pages_length, const MemoryRange *code_pages, void *pc)
Whether the PC is within the V8 code range represented by code_pages.
Detailed Description
Various helpers for skipping over V8 frames in a given stack.
The unwinder API is only supported on the x64, ARM64 and ARM32 architectures.
Definition at line 80 of file v8-unwinder.h.
Member Function Documentation
PCIsInV8()
bool v8::Unwinder::PCIsInV8 (size_t code_pages_length, const MemoryRange * code_pages, void * pc) [static]
Whether the PC is within the V8 code range represented by code_pages.
If this returns false, then calling UnwindV8Frames() with the same PC and unwind_state will always fail. If it returns true, then unwinding may (but not necessarily) be successful.
Available on x64, ARM64 and ARM32
Definition at line 163 of file unwinder.cc.
                                  {
  return pc && PCIsInCodePages(code_pages_length, code_pages, pc);
}
References v8::anonymous_namespace{unwinder.cc}::PCIsInCodePages().
Referenced by TryUnwindV8Frames().
TryUnwindV8Frames()
bool v8::Unwinder::TryUnwindV8Frames (const JSEntryStubs & entry_stubs, size_t code_pages_length, const MemoryRange * code_pages, RegisterState * register_state, const void * stack_base) [static]
Attempt to unwind the stack to the most recent C++ frame.
This function is signal-safe and does not access any V8 state and thus doesn't require an Isolate.
The unwinder needs to know the location of the JS Entry Stub (a piece of code that is run when C++ code calls into generated JS code). This is used for edge cases where the current frame is being constructed or torn down when the stack sample occurs.
The unwinder also needs the virtual memory range of all possible V8 code objects. There are two ranges required - the heap code range and the range for code embedded in the binary.
Available on x64, ARM64 and ARM32.
Parameters
code_pages A list of all of the ranges in which V8 has allocated executable code. The caller should obtain this list by calling Isolate::CopyCodePages() during the same interrupt/thread suspension that captures the stack.
register_state The current registers. This is an in-out param that will be overwritten with the register values after unwinding, on success.
stack_base The resulting stack pointer and frame pointer values are bounds-checked against the stack_base and the original stack pointer value to ensure that they are valid locations in the given stack. If these values or any intermediate frame pointer values used during unwinding are ever out of these bounds, unwinding will fail.
Returns
True on success.
Definition at line 116 of file unwinder.cc.
                                                         {
  const void* stack_top = register_state->sp;
  void* pc = register_state->pc;
  if (PCIsInV8(code_pages_length, code_pages, pc) &&
      !IsInUnsafeJSEntryRange(entry_stubs, pc)) {
    void* current_fp = register_state->fp;
    if (!AddressIsInStack(current_fp, stack_base, stack_top)) return false;
    // Peek at the return address that the caller pushed. If it's in V8, then we
    // assume the caller frame is a JS frame and continue to unwind.
    void* next_pc = GetReturnAddressFromFP(current_fp, pc, entry_stubs);
    while (PCIsInV8(code_pages_length, code_pages, next_pc)) {
      current_fp = GetCallerFPFromFP(current_fp, pc, entry_stubs);
      if (!AddressIsInStack(current_fp, stack_base, stack_top)) return false;
      pc = next_pc;
      next_pc = GetReturnAddressFromFP(current_fp, pc, entry_stubs);
    }
    void* final_sp = GetCallerSPFromFP(current_fp, pc, entry_stubs);
    if (!AddressIsInStack(final_sp, stack_base, stack_top)) return false;
    register_state->sp = final_sp;
    // We don't check that the final FP value is within the stack bounds because
    // this is just the rbp value that JSEntryStub pushed. On platforms like
    // Win64 this is not used as a dedicated FP register, and could contain
    // anything.
    void* final_fp = GetCallerFPFromFP(current_fp, pc, entry_stubs);
    register_state->fp = final_fp;
    register_state->pc = next_pc;
    // Link register no longer valid after unwinding.
    register_state->lr = nullptr;
    if (IsInJSEntryRange(entry_stubs, pc)) {
      GetCalleeSavedRegistersFromEntryFrame(current_fp, register_state);
    }
    return true;
  }
  return false;
}
References v8::anonymous_namespace{unwinder.cc}::AddressIsInStack(), v8::RegisterState::fp, v8::GetCalleeSavedRegistersFromEntryFrame(), v8::anonymous_namespace{unwinder.cc}::GetCallerFPFromFP(), v8::anonymous_namespace{unwinder.cc}::GetCallerSPFromFP(), v8::anonymous_namespace{unwinder.cc}::GetReturnAddressFromFP(), v8::anonymous_namespace{unwinder.cc}::IsInJSEntryRange(), v8::anonymous_namespace{unwinder.cc}::IsInUnsafeJSEntryRange(), v8::RegisterState::lr, v8::RegisterState::pc, PCIsInV8(), and v8::RegisterState::sp.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-unwinder.h
/mnt/V8SourceCode/src/diagnostics/unwinder.cc