v8::internal::maglev::NodeInfo Class Reference
#include <maglev-interpreter-frame-state.h>
Classes
class AlternativeNodes
struct ClearUnstableMapsOnCopy
Public Member Functions
NodeInfo ()=default
NodeInfo (ClearUnstableMapsOnCopy other) V8_NOEXCEPT
NodeType type () const
NodeType IntersectType (NodeType other)
NodeType UnionType (NodeType other)
const AlternativeNodes & alternative () const
AlternativeNodes & alternative ()
bool no_info_available () const
bool is_smi () const
bool is_any_heap_object () const
bool is_string () const
bool is_internalized_string () const
bool is_symbol () const
void MergeWith (const NodeInfo &other, Zone *zone, bool &any_merged_map_is_unstable)
bool possible_maps_are_unstable () const
void ClearUnstableMaps ()
template<typename Function >
void ClearUnstableMapsIfAny (const Function &condition)
bool possible_maps_are_known () const
const PossibleMaps & possible_maps () const
void SetPossibleMaps (const PossibleMaps &possible_maps, bool any_map_is_unstable, NodeType possible_type, compiler::JSHeapBroker *broker)
bool any_map_is_unstable () const
void set_node_type_is_unstable ()
Private Attributes
NodeType type_ = NodeType::kUnknown
bool any_map_is_unstable_ = false
bool possible_maps_are_known_ = false
PossibleMaps possible_maps_
AlternativeNodes alternative_
Detailed Description
Definition at line 73 of file maglev-interpreter-frame-state.h.
Constructor & Destructor Documentation
NodeInfo() [1/2]
v8::internal::maglev::NodeInfo::NodeInfo () [default]
NodeInfo() [2/2]
v8::internal::maglev::NodeInfo::NodeInfo (ClearUnstableMapsOnCopy other) [inline], [explicit]
Definition at line 80 of file maglev-interpreter-frame-state.h.
                                                               {
    type_ = other.val.type_;
    alternative_ = other.val.alternative_;
    if (other.val.possible_maps_are_known_ && !other.val.any_map_is_unstable_) {
      possible_maps_ = other.val.possible_maps_;
      possible_maps_are_known_ = true;
    }
  }
References alternative_, possible_maps_, possible_maps_are_known_, and type_.
Member Function Documentation
alternative() [1/2]
AlternativeNodes& v8::internal::maglev::NodeInfo::alternative () [inline]
Definition at line 154 of file maglev-interpreter-frame-state.h.
{ return alternative_; }
References alternative_.
alternative() [2/2]
const AlternativeNodes& v8::internal::maglev::NodeInfo::alternative () const [inline]
Definition at line 153 of file maglev-interpreter-frame-state.h.
{ return alternative_; }
References alternative_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildToBoolean(), v8::internal::maglev::MaglevGraphBuilder::CanElideWriteBarrier(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber(), v8::internal::maglev::MaglevGraphBuilder::GetInt32(), v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex(), v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString(), v8::internal::maglev::MaglevGraphBuilder::GetSmiValue(), v8::internal::maglev::MaglevGraphBuilder::GetTaggedValue(), v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), v8::internal::maglev::MaglevGraphBuilder::GetUint8ClampedForToNumber(), v8::internal::maglev::MaglevGraphBuilder::SetKnownValue(), and v8::internal::maglev::MaglevGraphBuilder::TryGetConstantAlternative().
any_map_is_unstable()
bool v8::internal::maglev::NodeInfo::any_map_is_unstable () const [inline]
Definition at line 245 of file maglev-interpreter-frame-state.h.
{ return any_map_is_unstable_; }
References any_map_is_unstable_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), and SetPossibleMaps().
ClearUnstableMaps()
void v8::internal::maglev::NodeInfo::ClearUnstableMaps () [inline]
Definition at line 195 of file maglev-interpreter-frame-state.h.
                           {
    if (!any_map_is_unstable_) return;
    possible_maps_.clear();
    possible_maps_are_known_ = false;
    type_ = MakeTypeStable(type_);
    any_map_is_unstable_ = false;
  }
References any_map_is_unstable_, v8::internal::ZoneCompactSet< T >::clear(), v8::internal::maglev::MakeTypeStable(), possible_maps_, possible_maps_are_known_, and type_.
Referenced by ClearUnstableMapsIfAny().
ClearUnstableMapsIfAny()
template<typename Function >
void v8::internal::maglev::NodeInfo::ClearUnstableMapsIfAny (const Function & condition) [inline]
Definition at line 204 of file maglev-interpreter-frame-state.h.
                                                         {
    if (!any_map_is_unstable_) return;
    for (auto map : possible_maps_) {
      if (condition(map)) {
        ClearUnstableMaps();
        return;
      }
    }
  }
References any_map_is_unstable_, ClearUnstableMaps(), and possible_maps_.
IntersectType()
NodeType v8::internal::maglev::NodeInfo::IntersectType (NodeType other) [inline]
Definition at line 90 of file maglev-interpreter-frame-state.h.
                                         {
    return type_ = maglev::IntersectType(type_, other);
  }
References v8::internal::maglev::IntersectType(), and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSArrayLength(), v8::internal::maglev::KnownNodeAspects::EnsureType(), v8::internal::maglev::MaglevGraphBuilder::GetInternalizedString(), v8::internal::maglev::MaglevGraphBuilder::SetKnownValue(), and SetPossibleMaps().
is_any_heap_object()
bool v8::internal::maglev::NodeInfo::is_any_heap_object () const [inline]
Definition at line 162 of file maglev-interpreter-frame-state.h.
{ return NodeTypeIsAnyHeapObject(type_); }
References type_.
is_internalized_string()
bool v8::internal::maglev::NodeInfo::is_internalized_string () const [inline]
Definition at line 164 of file maglev-interpreter-frame-state.h.
                                      {
    return NodeTypeIsInternalizedString(type_);
  }
References type_.
is_smi()
bool v8::internal::maglev::NodeInfo::is_smi () const [inline]
Definition at line 161 of file maglev-interpreter-frame-state.h.
{ return NodeTypeIsSmi(type_); }
References type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetInt32().
is_string()
bool v8::internal::maglev::NodeInfo::is_string () const [inline]
Definition at line 163 of file maglev-interpreter-frame-state.h.
{ return NodeTypeIsString(type_); }
References type_.
is_symbol()
bool v8::internal::maglev::NodeInfo::is_symbol () const [inline]
Definition at line 167 of file maglev-interpreter-frame-state.h.
{ return NodeTypeIsSymbol(type_); }
References type_.
MergeWith()
void v8::internal::maglev::NodeInfo::MergeWith (const NodeInfo & other, Zone * zone, bool & any_merged_map_is_unstable) [inline]
Definition at line 171 of file maglev-interpreter-frame-state.h.
                                                   {
    UnionType(other.type_);
    alternative_.MergeWith(other.alternative_);
    if (possible_maps_are_known_) {
      if (other.possible_maps_are_known_) {
        // Map sets are the set of _possible_ maps, so on a merge we need to
        // _union_ them together (i.e. intersect the set of impossible maps).
        // Remember whether _any_ of these merges observed unstable maps.
        possible_maps_.Union(other.possible_maps_, zone);
      } else {
        possible_maps_.clear();
        possible_maps_are_known_ = false;
      }
    }
    any_map_is_unstable_ = possible_maps_are_known_ &&
                           (any_map_is_unstable_ || other.any_map_is_unstable_);
    any_merged_map_is_unstable =
        any_merged_map_is_unstable || any_map_is_unstable_;
  }
References alternative_, any_map_is_unstable_, v8::internal::ZoneCompactSet< T >::clear(), v8::internal::maglev::NodeInfo::AlternativeNodes::MergeWith(), possible_maps_, possible_maps_are_known_, type_, v8::internal::ZoneCompactSet< T >::Union(), and UnionType().
no_info_available()
bool v8::internal::maglev::NodeInfo::no_info_available () const [inline]
Definition at line 156 of file maglev-interpreter-frame-state.h.
                                 {
    return type_ == NodeType::kUnknown && alternative_.has_none() &&
           !possible_maps_are_known_;
  }
References alternative_, v8::internal::maglev::NodeInfo::AlternativeNodes::has_none(), possible_maps_are_known_, and type_.
possible_maps()
const PossibleMaps& v8::internal::maglev::NodeInfo::possible_maps () const [inline]
Definition at line 216 of file maglev-interpreter-frame-state.h.
                                            {
    // If !possible_maps_are_known_ then every map is possible and using the
    // (probably empty) possible_maps_ set is definetly wrong.
    CHECK(possible_maps_are_known_);
    return possible_maps_;
  }
References CHECK, possible_maps_, and possible_maps_are_known_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), SetPossibleMaps(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto().
possible_maps_are_known()
bool v8::internal::maglev::NodeInfo::possible_maps_are_known () const [inline]
Definition at line 214 of file maglev-interpreter-frame-state.h.
{ return possible_maps_are_known_; }
References possible_maps_are_known_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildTestUndetectable(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIsEmpty(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryReduceDatePrototypeGetField(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetProto().
possible_maps_are_unstable()
bool v8::internal::maglev::NodeInfo::possible_maps_are_unstable () const [inline]
Definition at line 193 of file maglev-interpreter-frame-state.h.
{ return any_map_is_unstable_; }
References any_map_is_unstable_.
set_node_type_is_unstable()
void v8::internal::maglev::NodeInfo::set_node_type_is_unstable () [inline]
Definition at line 247 of file maglev-interpreter-frame-state.h.
                                   {
    // Re-use any_map_is_unstable to signal that the node type is unstable.
    any_map_is_unstable_ = true;
  }
References any_map_is_unstable_.
Referenced by v8::internal::maglev::KnownNodeAspects::EnsureType().
SetPossibleMaps()
void v8::internal::maglev::NodeInfo::SetPossibleMaps (const PossibleMaps & possible_maps, bool any_map_is_unstable, NodeType possible_type, compiler::JSHeapBroker * broker) [inline]
Definition at line 223 of file maglev-interpreter-frame-state.h.
                                                     {
    possible_maps_ = possible_maps;
    possible_maps_are_known_ = true;
    any_map_is_unstable_ = any_map_is_unstable;
#ifdef DEBUG
    if (possible_maps.size()) {
      NodeType expected = StaticTypeForMap(*possible_maps.begin(), broker);
      for (auto map : possible_maps) {
        expected = maglev::UnionType(StaticTypeForMap(map, broker), expected);
      }
      // Ensure the claimed type is not narrower than what can be learned from
      // the map checks.
      DCHECK(NodeTypeIs(expected, possible_type));
    } else {
      DCHECK_EQ(possible_type, NodeType::kUnknown);
    }
#endif
    IntersectType(possible_type);
  }
References any_map_is_unstable(), any_map_is_unstable_, v8::internal::ZoneCompactSet< T >::begin(), broker(), v8::internal::DCHECK(), DCHECK_EQ, IntersectType(), v8::internal::maglev::NodeTypeIs(), possible_maps(), possible_maps_, possible_maps_are_known_, v8::internal::ZoneCompactSet< T >::size(), v8::internal::maglev::StaticTypeForMap(), and v8::internal::maglev::UnionType().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::maglev::MaglevGraphBuilder::BuildStoreMap(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindAndCompareMaps(), v8::internal::maglev::MaglevGraphBuilder::BuildTransitionElementsKindOrCheckMap(), and v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::UpdateKnownNodeAspects().
type()
NodeType v8::internal::maglev::NodeInfo::type () const [inline]
Definition at line 89 of file maglev-interpreter-frame-state.h.
{ return type_; }
References type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::EnsureTagged(), v8::internal::maglev::KnownNodeAspects::EnsureType(), v8::internal::maglev::MaglevGraphBuilder::GetFloat64ForToNumber(), v8::internal::maglev::MaglevGraphBuilder::GetSmiValue(), v8::internal::maglev::MaglevGraphBuilder::GetTaggedValue(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIncludes(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoIsEmpty(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::NodeInfoTypeIs(), and v8::internal::maglev::MaglevGraphBuilder::SetKnownValue().
UnionType()
NodeType v8::internal::maglev::NodeInfo::UnionType (NodeType other) [inline]
Definition at line 93 of file maglev-interpreter-frame-state.h.
                                     {
    return type_ = maglev::UnionType(type_, other);
  }
References type_, and v8::internal::maglev::UnionType().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckMaps(), and MergeWith().
Member Data Documentation
alternative_
AlternativeNodes v8::internal::maglev::NodeInfo::alternative_ [private]
Definition at line 264 of file maglev-interpreter-frame-state.h.
Referenced by alternative(), MergeWith(), no_info_available(), and NodeInfo().
any_map_is_unstable_
bool v8::internal::maglev::NodeInfo::any_map_is_unstable_ = false [private]
Definition at line 255 of file maglev-interpreter-frame-state.h.
Referenced by any_map_is_unstable(), ClearUnstableMaps(), ClearUnstableMapsIfAny(), MergeWith(), possible_maps_are_unstable(), set_node_type_is_unstable(), and SetPossibleMaps().
possible_maps_
PossibleMaps v8::internal::maglev::NodeInfo::possible_maps_ [private]
Definition at line 262 of file maglev-interpreter-frame-state.h.
Referenced by ClearUnstableMaps(), ClearUnstableMapsIfAny(), MergeWith(), NodeInfo(), possible_maps(), and SetPossibleMaps().
possible_maps_are_known_
bool v8::internal::maglev::NodeInfo::possible_maps_are_known_ = false [private]
Definition at line 261 of file maglev-interpreter-frame-state.h.
Referenced by ClearUnstableMaps(), MergeWith(), no_info_available(), NodeInfo(), possible_maps(), possible_maps_are_known(), and SetPossibleMaps().
type_
NodeType v8::internal::maglev::NodeInfo::type_ = NodeType::kUnknown [private]
Definition at line 253 of file maglev-interpreter-frame-state.h.
Referenced by ClearUnstableMaps(), IntersectType(), is_any_heap_object(), is_internalized_string(), is_smi(), is_string(), is_symbol(), MergeWith(), no_info_available(), NodeInfo(), type(), and UnionType().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h