v8::internal::JsonStringifier::NoExtendBuilder< DestChar > Class Template Reference
Public Member Functions
NoExtendBuilder (DestChar *start, size_t *current_index)
~NoExtendBuilder ()
void Append (DestChar c)
void AppendCString (const char *s)
void AppendString (std::string_view str)
void AppendChars (base::Vector< const uint8_t > chars, size_t length)
template<typename SrcChar >
void AppendSubstring (const SrcChar *src, size_t from, size_t to)
Private Attributes
size_t * current_index_
DestChar * start_
DestChar * cursor_
Detailed Description
template<typename DestChar>
class v8::internal::JsonStringifier::NoExtendBuilder< DestChar >
Definition at line 283 of file json-stringifier.cc.
Constructor & Destructor Documentation
NoExtendBuilder()
template<typename DestChar >
v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::NoExtendBuilder (DestChar * start, size_t * current_index) [inline]
Definition at line 285 of file json-stringifier.cc.
        : current_index_(current_index), start_(start), cursor_(start) {}
 NoExtendBuilder()
template<typename DestChar >
v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::~NoExtendBuilder () [inline]
Definition at line 287 of file json-stringifier.cc.
{ *current_index_ += cursor_ - start_; }
References v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::current_index_, v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::cursor_, and v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::start_.
Member Function Documentation
Append()
template<typename DestChar >
void v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::Append (DestChar c) [inline]
Definition at line 289 of file json-stringifier.cc.
{ *(cursor_++) = c; }
References v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::cursor_.
Referenced by v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendCString(), v8::internal::JsonStringifier::SerializeStringUnchecked_(), and v8::internal::JsonStringifier::TrySerializeSimplePropertyKey().
AppendChars()
template<typename DestChar >
void v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendChars (base::Vector< const uint8_t > chars, size_t length) [inline]
Definition at line 304 of file json-stringifier.cc.
                                              {
      DCHECK_GE(chars.size(), length);
      CopyChars(cursor_, chars.begin(), chars.size());
      cursor_ += length;
    }
References v8::base::Vector< T >::begin(), v8::internal::CopyChars(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::cursor_, DCHECK_GE, v8::internal::length, and v8::base::Vector< T >::size().
Referenced by v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendString(), and v8::internal::JsonStringifier::TrySerializeSimplePropertyKey().
AppendCString()
template<typename DestChar >
void v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendCString (const char * s) [inline]
Definition at line 290 of file json-stringifier.cc.
                                                {
      const uint8_t* u = reinterpret_cast<const uint8_t*>(s);
      while (*u != '\0') Append(*(u++));
    }
References v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::Append().
Referenced by v8::internal::JsonStringifier::SerializeStringUnchecked_().
AppendString()
template<typename DestChar >
void v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendString (std::string_view str) [inline]
Definition at line 294 of file json-stringifier.cc.
                                                    {
      AppendChars(
          base::Vector<const uint8_t>(
              reinterpret_cast<const uint8_t*>(str.data()), str.length()),
          str.length());
    }
References v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendChars(), and v8::base::Vector< T >::length().
Referenced by v8::internal::JsonStringifier::SerializeStringUnchecked_().
AppendSubstring()
template<typename DestChar >
template<typename SrcChar >
void v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendSubstring (const SrcChar * src, size_t from, size_t to) [inline]
Definition at line 312 of file json-stringifier.cc.
                                                                               {
      if (from == to) return;
      DCHECK_LT(from, to);
      size_t count = to - from;
      CopyChars(cursor_, src + from, count);
      cursor_ += count;
    }
References v8::internal::CopyChars(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::cursor_, and DCHECK_LT.
Referenced by v8::internal::JsonStringifier::SerializeStringUnchecked_().
Member Data Documentation
current_index_
template<typename DestChar >
size_t* v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::current_index_ [private]
Definition at line 321 of file json-stringifier.cc.
Referenced by v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::~NoExtendBuilder().
cursor_
template<typename DestChar >
DestChar* v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::cursor_ [private]
Definition at line 323 of file json-stringifier.cc.
Referenced by v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::Append(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendChars(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendSubstring(), and v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::~NoExtendBuilder().
start_
template<typename DestChar >
DestChar* v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::start_ [private]
Definition at line 322 of file json-stringifier.cc.
Referenced by v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::~NoExtendBuilder().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc