v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope Class Reference
Public Member Functions
SanitizeNativeContextScope (Isolate *isolate, Tagged< NativeContext > native_context, bool allow_active_isolate_for_testing, const DisallowGarbageCollection &no_gc)
~SanitizeNativeContextScope ()
Private Attributes
Tagged< NativeContext > native_context_
ExternalPointerSlot::RawContent microtask_queue_external_pointer_
const DisallowGarbageCollection & no_gc_
Detailed Description
Definition at line 27 of file context-serializer.cc.
Constructor & Destructor Documentation
SanitizeNativeContextScope()
v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::SanitizeNativeContextScope (Isolate * isolate, Tagged< NativeContext > native_context, bool allow_active_isolate_for_testing, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 29 of file context-serializer.cc.
      : native_context_(native_context), no_gc_(no_gc) {
#ifdef DEBUG
    if (!allow_active_isolate_for_testing) {
      // Microtasks.
      MicrotaskQueue* microtask_queue = native_context_->microtask_queue();
      DCHECK_EQ(0, microtask_queue->size());
      DCHECK(!microtask_queue->HasMicrotasksSuppressions());
      DCHECK_EQ(0, microtask_queue->GetMicrotasksScopeDepth());
      DCHECK(microtask_queue->DebugMicrotasksScopeDepthIsZero());
    }
#endif
    microtask_queue_external_pointer_ =
        native_context
            ->RawExternalPointerField(NativeContext::kMicrotaskQueueOffset,
                                      kNativeContextMicrotaskQueueTag)
            .GetAndClearContentForSerialization(no_gc);
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth(), v8::internal::MicrotaskQueue::HasMicrotasksSuppressions(), v8::internal::kNativeContextMicrotaskQueueTag, v8::internal::native_context, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::MicrotaskQueue::size().
 SanitizeNativeContextScope()
v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::~SanitizeNativeContextScope () [inline]
Definition at line 51 of file context-serializer.cc.
                                {
    // Restore saved fields.
    native_context_
        ->RawExternalPointerField(NativeContext::kMicrotaskQueueOffset,
                                  kNativeContextMicrotaskQueueTag)
        .RestoreContentAfterSerialization(microtask_queue_external_pointer_,
                                          no_gc_);
  }
References v8::internal::kNativeContextMicrotaskQueueTag.
Member Data Documentation
microtask_queue_external_pointer_
ExternalPointerSlot::RawContent v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::microtask_queue_external_pointer_ [private]
Definition at line 62 of file context-serializer.cc.
native_context_
Tagged<NativeContext> v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::native_context_ [private]
Definition at line 61 of file context-serializer.cc.
no_gc_
const DisallowGarbageCollection& v8::internal::anonymous_namespace{context-serializer.cc}::SanitizeNativeContextScope::no_gc_ [private]
Definition at line 63 of file context-serializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/context-serializer.cc