v8::base::LsanVirtualAddressSpace Class Reference
#include <lsan-virtual-address-space.h>
Public Member Functions
LsanVirtualAddressSpace (std::unique_ptr< v8::VirtualAddressSpace > vas)
~LsanVirtualAddressSpace () override=default
void SetRandomSeed (int64_t seed) override
Sets the random seed so that GetRandomPageAddress() will generate repeatable sequences of random addresses.
Address RandomPageAddress () override
Returns a random address inside this address space, suitable for page allocations hints.
Address AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) override
void FreePages (Address address, size_t size) override
Frees previously allocated pages.
Address AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) override
Allocates shared memory pages with the given permissions.
void FreeSharedPages (Address address, size_t size) override
Frees previously allocated shared pages.
bool SetPagePermissions (Address address, size_t size, PagePermissions permissions) override
Sets permissions of all allocated pages in the given range.
bool RecommitPages (Address address, size_t size, PagePermissions permissions) override
Recommits discarded pages in the given range with given permissions.
bool AllocateGuardRegion (Address address, size_t size) override
Creates a guard region at the specified address.
void FreeGuardRegion (Address address, size_t size) override
Frees an existing guard region.
bool CanAllocateSubspaces () override
Whether this instance can allocate subspaces or not.
std::unique_ptr< VirtualAddressSpace > AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) override
bool DiscardSystemPages (Address address, size_t size) override
Frees memory in the given [address, address + size) range.
bool DecommitPages (Address address, size_t size) override
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
Private Attributes
std::unique_ptr< v8::VirtualAddressSpace > vas_
Additional Inherited Members
Detailed Description
Definition at line 20 of file lsan-virtual-address-space.h.
Constructor & Destructor Documentation
LsanVirtualAddressSpace()
v8::base::LsanVirtualAddressSpace::LsanVirtualAddressSpace (std::unique_ptr< v8::VirtualAddressSpace > vas) [explicit]
Definition at line 17 of file lsan-virtual-address-space.cc.
    : VirtualAddressSpace(vas->page_size(), vas->allocation_granularity(),
                          vas->base(), vas->size(),
                          vas->max_page_permissions()),
      vas_(std::move(vas)) {
  DCHECK_NOT_NULL(vas_);
}
References DCHECK_NOT_NULL, and vas_.
 LsanVirtualAddressSpace()
v8::base::LsanVirtualAddressSpace::~LsanVirtualAddressSpace () [override], [default]
Member Function Documentation
AllocateGuardRegion()
bool v8::base::LsanVirtualAddressSpace::AllocateGuardRegion (Address address, size_t size) [inline], [override], [virtual]
Creates a guard region at the specified address.
Guard regions are guaranteed to cause a fault when accessed and generally do not count towards any memory consumption limits. Further, allocating guard regions can usually not fail in subspaces if the region does not overlap with another region, subspace, or page allocation.
Parameters
address The start address of the guard region. Must be aligned to the allocation_granularity().
size The size of the guard region in bytes. Must be a multiple of the allocation_granularity().
Returns
true on success, false otherwise.
Implements v8::VirtualAddressSpace.
Definition at line 55 of file lsan-virtual-address-space.h.
                                                                  {
    return vas_->AllocateGuardRegion(address, size);
  }
References size().
AllocatePages()
Address v8::base::LsanVirtualAddressSpace::AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) [override], [virtual]
Implements v8::VirtualAddressSpace.
Definition at line 26 of file lsan-virtual-address-space.cc.
                                                                            {
  Address result = vas_->AllocatePages(hint, size, alignment, permissions);
#if defined(LEAK_SANITIZER)
  if (result) {
    __lsan_register_root_region(reinterpret_cast<void*>(result), size);
  }
#endif // defined(LEAK_SANITIZER)
  return result;
}
References v8::base::internal::result, v8::VirtualAddressSpace::size(), and vas_.
AllocateSharedPages()
Address v8::base::LsanVirtualAddressSpace::AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) [override], [virtual]
Allocates shared memory pages with the given permissions.
Parameters
hint Placement hint. See AllocatePages.
size The size of the allocation in bytes. Must be a multiple of the allocation_granularity().
permissions The page permissions of the newly allocated pages.
handle A platform-specific handle to a shared memory object. See the SharedMemoryHandleFromX routines above for ways to obtain these.
offset The offset in the shared memory object at which the mapping should start. Must be a multiple of the allocation_granularity().
Returns
the start address of the allocated pages on success, zero on failure.
Implements v8::VirtualAddressSpace.
Definition at line 45 of file lsan-virtual-address-space.cc.
                                                        {
  Address result =
      vas_->AllocateSharedPages(hint, size, permissions, handle, offset);
#if defined(LEAK_SANITIZER)
  if (result) {
    __lsan_register_root_region(reinterpret_cast<void*>(result), size);
  }
#endif // defined(LEAK_SANITIZER)
  return result;
}
References v8::internal::handle(), v8::base::internal::result, v8::VirtualAddressSpace::size(), and vas_.
AllocateSubspace()
std::unique_ptr< VirtualAddressSpace > v8::base::LsanVirtualAddressSpace::AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) [override], [virtual]
Implements v8::VirtualAddressSpace.
Definition at line 65 of file lsan-virtual-address-space.cc.
                                          {
  auto subspace =
      vas_->AllocateSubspace(hint, size, alignment, max_page_permissions);
#if defined(LEAK_SANITIZER)
  if (subspace) {
    subspace = std::make_unique<LsanVirtualAddressSpace>(std::move(subspace));
  }
#endif // defined(LEAK_SANITIZER)
  return subspace;
}
References v8::VirtualAddressSpace::max_page_permissions(), v8::VirtualAddressSpace::size(), and vas_.
CanAllocateSubspaces()
bool v8::base::LsanVirtualAddressSpace::CanAllocateSubspaces () [inline], [override], [virtual]
Whether this instance can allocate subspaces or not.
Returns
true if subspaces can be allocated, false if not.
Implements v8::VirtualAddressSpace.
Definition at line 63 of file lsan-virtual-address-space.h.
{ return vas_->CanAllocateSubspaces(); }
DecommitPages()
bool v8::base::LsanVirtualAddressSpace::DecommitPages (Address address, size_t size) [inline], [override], [virtual]
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
The address range stays reserved and can be accessed again later by changing its permissions. However, in that case the memory content is guaranteed to be zero-initialized again. The memory must have been previously allocated by a call to AllocatePages.
Returns
true on success, false otherwise.
Implements v8::VirtualAddressSpace.
Definition at line 73 of file lsan-virtual-address-space.h.
                                                            {
    return vas_->DecommitPages(address, size);
  }
References size().
DiscardSystemPages()
bool v8::base::LsanVirtualAddressSpace::DiscardSystemPages (Address address, size_t size) [inline], [override], [virtual]
Frees memory in the given [address, address + size) range.
address and size should be aligned to the page_size(). The next write to this memory area brings the memory transparently back. This should be treated as a hint to the OS that the pages are no longer needed. It does not guarantee that the pages will be discarded immediately or at all.
Returns
true on success, false otherwise. Since this method is only a hint, a successful invocation does not imply that pages have been removed.
Reimplemented from v8::VirtualAddressSpace.
Definition at line 69 of file lsan-virtual-address-space.h.
                                                                 {
    return vas_->DiscardSystemPages(address, size);
  }
References size().
FreeGuardRegion()
void v8::base::LsanVirtualAddressSpace::FreeGuardRegion (Address address, size_t size) [inline], [override], [virtual]
Frees an existing guard region.
This function will terminate the process on failure as this implies a bug in the client. As such, there is no return value.
Parameters
address The start address of the guard region to free. This address must have previously been used as address parameter in a successful invocation of AllocateGuardRegion.
size The size in bytes of the guard region to free. This must match the size passed to AllocateGuardRegion when the region was created.
Implements v8::VirtualAddressSpace.
Definition at line 59 of file lsan-virtual-address-space.h.
                                                              {
    vas_->FreeGuardRegion(address, size);
  }
References size().
FreePages()
void v8::base::LsanVirtualAddressSpace::FreePages (Address address, size_t size) [override], [virtual]
Frees previously allocated pages.
This function will terminate the process on failure as this implies a bug in the client. As such, there is no return value.
Parameters
address The start address of the pages to free. This address must have been obtained through a call to AllocatePages.
size The size in bytes of the region to free. This must match the size passed to AllocatePages when the pages were allocated.
Implements v8::VirtualAddressSpace.
Definition at line 38 of file lsan-virtual-address-space.cc.
                                                                    {
  vas_->FreePages(address, size);
#if defined(LEAK_SANITIZER)
  __lsan_unregister_root_region(reinterpret_cast<void*>(address), size);
#endif // defined(LEAK_SANITIZER)
}
References v8::VirtualAddressSpace::size(), and vas_.
FreeSharedPages()
void v8::base::LsanVirtualAddressSpace::FreeSharedPages (Address address, size_t size) [override], [virtual]
Frees previously allocated shared pages.
This function will terminate the process on failure as this implies a bug in the client. As such, there is no return value.
Parameters
address The start address of the pages to free. This address must have been obtained through a call to AllocateSharedPages.
size The size in bytes of the region to free. This must match the size passed to AllocateSharedPages when the pages were allocated.
Implements v8::VirtualAddressSpace.
Definition at line 58 of file lsan-virtual-address-space.cc.
                                                                          {
  vas_->FreeSharedPages(address, size);
#if defined(LEAK_SANITIZER)
  __lsan_unregister_root_region(reinterpret_cast<void*>(address), size);
#endif // defined(LEAK_SANITIZER)
}
References v8::VirtualAddressSpace::size(), and vas_.
RandomPageAddress()
Address v8::base::LsanVirtualAddressSpace::RandomPageAddress () [inline], [override], [virtual]
Returns a random address inside this address space, suitable for page allocations hints.
Returns
a random address aligned to allocation_granularity().
Implements v8::VirtualAddressSpace.
Definition at line 31 of file lsan-virtual-address-space.h.
{ return vas_->RandomPageAddress(); }
RecommitPages()
bool v8::base::LsanVirtualAddressSpace::RecommitPages (Address address, size_t size, PagePermissions permissions) [inline], [override], [virtual]
Recommits discarded pages in the given range with given permissions.
Discarded pages must be recommitted with their original permissions before they are used again.
Parameters
address The start address of the range. Must be aligned to page_size().
size The size in bytes of the range. Must be a multiple of page_size().
permissions The permissions for the range that the pages must have.
Returns
true on success, false otherwise.
Implements v8::VirtualAddressSpace.
Definition at line 50 of file lsan-virtual-address-space.h.
                                                           {
    return vas_->RecommitPages(address, size, permissions);
  }
References size().
SetPagePermissions()
bool v8::base::LsanVirtualAddressSpace::SetPagePermissions (Address address, size_t size, PagePermissions permissions) [inline], [override], [virtual]
Sets permissions of all allocated pages in the given range.
This operation can fail due to OOM, in which case false is returned. If the operation fails for a reason other than OOM, this function will terminate the process as this implies a bug in the client.
Parameters
address The start address of the range. Must be aligned to page_size().
size The size in bytes of the range. Must be a multiple of page_size().
permissions The new permissions for the range.
Returns
true on success, false on OOM.
Implements v8::VirtualAddressSpace.
Definition at line 45 of file lsan-virtual-address-space.h.
                                                                {
    return vas_->SetPagePermissions(address, size, permissions);
  }
References size().
SetRandomSeed()
void v8::base::LsanVirtualAddressSpace::SetRandomSeed (int64_t seed) [inline], [override], [virtual]
Sets the random seed so that GetRandomPageAddress() will generate repeatable sequences of random addresses.
Parameters
The seed for the PRNG.
Implements v8::VirtualAddressSpace.
Definition at line 27 of file lsan-virtual-address-space.h.
                                            {
    return vas_->SetRandomSeed(seed);
  }
Member Data Documentation
vas_
std::unique_ptr<v8::VirtualAddressSpace> v8::base::LsanVirtualAddressSpace::vas_ [private]
Definition at line 78 of file lsan-virtual-address-space.h.
Referenced by AllocatePages(), AllocateSharedPages(), AllocateSubspace(), FreePages(), FreeSharedPages(), and LsanVirtualAddressSpace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/sanitizer/lsan-virtual-address-space.h
/mnt/V8SourceCode/src/base/sanitizer/lsan-virtual-address-space.cc