v8::internal::compiler::turboshaft::LabelBase< loop, Ts > Class Template Reference
#include <assembler.h>
Classes
struct BlockData
Public Types
using values_t = std::tuple< V< Ts >... >
using const_or_values_t = std::tuple< maybe_const_or_v_t< Ts >... >
using recorded_values_t = std::tuple< base::SmallVector< V< Ts >, 2 >... >
Public Member Functions
Block * block ()
bool has_incoming_jump () const
template<typename A >
void Goto (A &assembler, const values_t &values)
template<typename A >
void GotoIf (A &assembler, OpIndex condition, BranchHint hint, const values_t &values)
template<typename A >
void GotoIfNot (A &assembler, OpIndex condition, BranchHint hint, const values_t &values)
template<typename A >
base::prepend_tuple_type< bool, values_t > Bind (A &assembler)
Static Public Attributes
static constexpr bool is_loop = loop
Protected Member Functions
LabelBase (const LabelBase &)=delete
LabelBase & operator= (const LabelBase &)=delete
LabelBase (Block *block)
LabelBase (LabelBase &&other) V8_NOEXCEPT
template<typename A >
values_t MaterializePhis (A &assembler)
Static Protected Member Functions
static void RecordValues (Block *source, BlockData &data, const values_t &values)
template<size_t... indices>
static void RecordValuesImpl (BlockData &data, Block *source, const values_t &values, std::index_sequence< indices... >)
template<typename A , size_t... indices>
static values_t MaterializePhisImpl (A &assembler, BlockData &data, std::index_sequence< indices... >)
Protected Attributes
BlockData data_
bool has_incoming_jump_ = false
Static Protected Attributes
static constexpr size_t size = sizeof...(Ts)
Detailed Description
template<bool loop, typename... Ts>
class v8::internal::compiler::turboshaft::LabelBase< loop, Ts >
Definition at line 386 of file assembler.h.
Member Typedef Documentation
const_or_values_t
template<bool loop, typename... Ts>
using v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::const_or_values_t = std::tuple<maybe_const_or_v_t<Ts>...>
Definition at line 396 of file assembler.h.
recorded_values_t
template<bool loop, typename... Ts>
using v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::recorded_values_t = std::tuple<base::SmallVector<V<Ts>, 2>...>
Definition at line 397 of file assembler.h.
values_t
template<bool loop, typename... Ts>
using v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::values_t = std::tuple<V<Ts>...>
Definition at line 395 of file assembler.h.
Constructor & Destructor Documentation
LabelBase() [1/3]
template<bool loop, typename... Ts>
v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::LabelBase (const LabelBase< loop, Ts > &) [protected], [delete]
LabelBase() [2/3]
template<bool loop, typename... Ts>
v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::LabelBase (Block * block) [inline], [explicit], [protected]
Definition at line 458 of file assembler.h.
                                   : data_(block) {
    DCHECK_NOT_NULL(data_.block);
  }
References DCHECK_NOT_NULL.
LabelBase() [3/3]
template<bool loop, typename... Ts>
v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::LabelBase (LabelBase< loop, Ts > && other) [inline], [protected]
Definition at line 462 of file assembler.h.
      : data_(std::move(other.data_)),
        has_incoming_jump_(other.has_incoming_jump_) {}
Member Function Documentation
Bind()
template<bool loop, typename... Ts>
template<typename A >
base::prepend_tuple_type<bool, values_t> v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::Bind (A & assembler) [inline]
Definition at line 440 of file assembler.h.
                                                            {
    DCHECK(!data_.block->IsBound());
    if (!assembler.Bind(data_.block)) {
      return std::tuple_cat(std::tuple{false}, values_t{});
    }
    DCHECK_EQ(data_.block, assembler.current_block());
    return std::tuple_cat(std::tuple{true}, MaterializePhis(assembler));
  }
References v8::internal::DCHECK(), and DCHECK_EQ.
block()
template<bool loop, typename... Ts>
Block* v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::block () [inline]
Definition at line 399 of file assembler.h.
{ return data_.block; }
Goto()
template<bool loop, typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::Goto (A & assembler, const values_t & values) [inline]
Definition at line 404 of file assembler.h.
                                                  {
    if (assembler.generating_unreachable_operations()) return;
    has_incoming_jump_ = true;
    Block* current_block = assembler.current_block();
    DCHECK_NOT_NULL(current_block);
    assembler.Goto(data_.block);
    RecordValues(current_block, data_, values);
  }
References DCHECK_NOT_NULL.
GotoIf()
template<bool loop, typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::GotoIf (A & assembler, OpIndex condition, BranchHint hint, const values_t & values) [inline]
Definition at line 414 of file assembler.h.
                                      {
    if (assembler.generating_unreachable_operations()) return;
    has_incoming_jump_ = true;
    Block* current_block = assembler.current_block();
    DCHECK_NOT_NULL(current_block);
    if (assembler.GotoIf(condition, data_.block, hint) &
        ConditionalGotoStatus::kGotoDestination) {
      RecordValues(current_block, data_, values);
    }
  }
References DCHECK_NOT_NULL, and v8::internal::compiler::turboshaft::kGotoDestination.
GotoIfNot()
template<bool loop, typename... Ts>
template<typename A >
void v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::GotoIfNot (A & assembler, OpIndex condition, BranchHint hint, const values_t & values) [inline]
Definition at line 427 of file assembler.h.
                                         {
    if (assembler.generating_unreachable_operations()) return;
    has_incoming_jump_ = true;
    Block* current_block = assembler.current_block();
    DCHECK_NOT_NULL(current_block);
    if (assembler.GotoIfNot(condition, data_.block, hint) &
        ConditionalGotoStatus::kGotoDestination) {
      RecordValues(current_block, data_, values);
    }
  }
References DCHECK_NOT_NULL, and v8::internal::compiler::turboshaft::kGotoDestination.
has_incoming_jump()
template<bool loop, typename... Ts>
bool v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::has_incoming_jump () const [inline]
Definition at line 401 of file assembler.h.
{ return has_incoming_jump_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::CheckMaps().
MaterializePhis()
template<bool loop, typename... Ts>
template<typename A >
values_t v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::MaterializePhis (A & assembler) [inline], [protected]
Definition at line 499 of file assembler.h.
                                         {
    return MaterializePhisImpl(assembler, data_,
                               std::make_index_sequence<size>());
  }
MaterializePhisImpl()
template<bool loop, typename... Ts>
template<typename A , size_t... indices>
static values_t v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::MaterializePhisImpl (A & assembler, BlockData & data, std::index_sequence< indices... >) [inline], [static], [protected]
Definition at line 505 of file assembler.h.
                                                                     {
    size_t predecessor_count = data.block->PredecessorCount();
    DCHECK_EQ(data.predecessors.size(), predecessor_count);
    // If this label has no values, we don't need any Phis.
    if constexpr (size == 0) return values_t{};
    // If this block does not have any predecessors, we shouldn't call this.
    DCHECK_LT(0, predecessor_count);
    // With 1 predecessor, we don't need any Phis.
    if (predecessor_count == 1) {
      return values_t{std::get<indices>(data.recorded_values)[0]...};
    }
    DCHECK_LT(1, predecessor_count);
    // Construct Phis.
    return values_t{assembler.Phi(
        base::VectorOf(std::get<indices>(data.recorded_values)))...};
  }
References v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::block, DCHECK_EQ, DCHECK_LT, v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::predecessors, v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::recorded_values, size(), and v8::base::VectorOf().
operator=()
template<bool loop, typename... Ts>
LabelBase& v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::operator= (const LabelBase< loop, Ts > &) [protected], [delete]
RecordValues()
template<bool loop, typename... Ts>
static void v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::RecordValues (Block * source, BlockData & data, const values_t & values) [inline], [static], [protected]
Definition at line 466 of file assembler.h.
                                                   {
    DCHECK_NOT_NULL(source);
    if (data.block->IsBound()) {
      // Cannot `Goto` to a bound block. If you are trying to construct a
      // loop, use a `LoopLabel` instead!
      UNREACHABLE();
    }
    RecordValuesImpl(data, source, values, std::make_index_sequence<size>());
  }
References v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::block, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::Block::IsBound(), and v8::internal::UNREACHABLE().
RecordValuesImpl()
template<bool loop, typename... Ts>
template<size_t... indices>
static void v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::RecordValuesImpl (BlockData & data, Block * source, const values_t & values, std::index_sequence< indices... >) [inline], [static], [protected]
Definition at line 478 of file assembler.h.
                                                              {
#ifdef DEBUG
    std::initializer_list<size_t> sizes{
        std::get<indices>(data.recorded_values).size()...};
    // There a -1 on the PredecessorCounts below, because we've emitted the
    // Goto/Branch before calling RecordValues (which we do because the
    // condition of the Goto might have been constant-folded, resulting in the
    // destination not actually being reachable).
    DCHECK(base::all_equal(
        sizes, static_cast<size_t>(data.block->PredecessorCount() - 1)));
    DCHECK_EQ(data.block->PredecessorCount() - 1, data.predecessors.size());
#endif
    (std::get<indices>(data.recorded_values)
         .push_back(std::get<indices>(values)),
     ...);
    data.predecessors.push_back(source);
  }
References v8::base::all_equal(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::block, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::predecessors, and v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::BlockData::recorded_values.
Member Data Documentation
data_
template<bool loop, typename... Ts>
BlockData v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::data_ [protected]
Definition at line 525 of file assembler.h.
has_incoming_jump_
template<bool loop, typename... Ts>
bool v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::has_incoming_jump_ = false [protected]
Definition at line 526 of file assembler.h.
is_loop
template<bool loop, typename... Ts>
constexpr bool v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::is_loop = loop [static], [constexpr]
Definition at line 394 of file assembler.h.
size
template<bool loop, typename... Ts>
constexpr size_t v8::internal::compiler::turboshaft::LabelBase< loop, Ts >::size = sizeof...(Ts) [static], [constexpr], [protected]
Definition at line 388 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h