v8::internal::PrototypeIterator Class Reference
A class to uniformly access the prototype of any Object and walk its prototype chain.
#include <prototype.h>
Public Types
enum WhereToEnd { END_AT_NULL
, END_AT_NON_HIDDEN
 }
Public Member Functions
PrototypeIterator (Isolate *isolate, DirectHandle< JSReceiver > receiver, WhereToStart where_to_start=kStartAtPrototype, WhereToEnd where_to_end=END_AT_NULL)
PrototypeIterator (Isolate *isolate, Tagged< JSReceiver > receiver, WhereToStart where_to_start=kStartAtPrototype, WhereToEnd where_to_end=END_AT_NULL)
PrototypeIterator (Isolate *isolate, Tagged< Map > receiver_map, WhereToEnd where_to_end=END_AT_NULL)
PrototypeIterator (Isolate *isolate, DirectHandle< Map > receiver_map, WhereToEnd where_to_end=END_AT_NULL)
~PrototypeIterator ()=default
PrototypeIterator (const PrototypeIterator &)=delete
PrototypeIterator & operator= (const PrototypeIterator &)=delete
bool HasAccess () const
template<typename T = JSPrototype>
Tagged< T > GetCurrent () const
void Advance ()
void AdvanceIgnoringProxies ()
V8_WARN_UNUSED_RESULT bool AdvanceFollowingProxies ()
V8_WARN_UNUSED_RESULT bool AdvanceFollowingProxiesIgnoringAccessChecks ()
bool IsAtEnd () const
Isolate * isolate () const
Static Public Member Functions
template<typename T = JSPrototype>
static DirectHandle< T > GetCurrent (const PrototypeIterator &iterator)
Private Attributes
Isolate * isolate_
Tagged< JSPrototype > object_ = {}
IndirectHandle< JSPrototype > handle_
WhereToEnd where_to_end_
bool is_at_end_
int seen_proxies_
Detailed Description
A class to uniformly access the prototype of any Object and walk its prototype chain.
The PrototypeIterator can either start at the prototype (default), or include the receiver itself. If a PrototypeIterator is constructed for a Map, it will always start at the prototype.
The PrototypeIterator can either run to the null_value(), the first non-hidden prototype, or a given object.
Definition at line 26 of file prototype.h.
Member Enumeration Documentation
WhereToEnd
enum v8::internal::PrototypeIterator::WhereToEnd
Enumerator
END_AT_NULL
END_AT_NON_HIDDEN
Definition at line 28 of file prototype.h.
{ END_AT_NULL, END_AT_NON_HIDDEN };
Constructor & Destructor Documentation
PrototypeIterator() [1/5]
v8::internal::PrototypeIterator::PrototypeIterator (Isolate * isolate, DirectHandle< JSReceiver > receiver, WhereToStart where_to_start = kStartAtPrototype, WhereToEnd where_to_end = END_AT_NULL) [inline]
Definition at line 18 of file prototype-inl.h.
    : isolate_(isolate),
      handle_(indirect_handle(receiver, isolate)),
      where_to_end_(where_to_end),
      is_at_end_(false),
      seen_proxies_(0) {
  CHECK(!handle_.is_null());
  if (where_to_start == kStartAtPrototype) Advance();
}
References Advance(), CHECK, handle_, and v8::internal::kStartAtPrototype.
PrototypeIterator() [2/5]
v8::internal::PrototypeIterator::PrototypeIterator (Isolate * isolate, Tagged< JSReceiver > receiver, WhereToStart where_to_start = kStartAtPrototype, WhereToEnd where_to_end = END_AT_NULL) [inline]
Definition at line 31 of file prototype-inl.h.
    : isolate_(isolate),
      object_(receiver),
      where_to_end_(where_to_end),
      is_at_end_(false),
      seen_proxies_(0) {
  if (where_to_start == kStartAtPrototype) Advance();
}
References Advance(), and v8::internal::kStartAtPrototype.
PrototypeIterator() [3/5]
v8::internal::PrototypeIterator::PrototypeIterator (Isolate * isolate, Tagged< Map > receiver_map, WhereToEnd where_to_end = END_AT_NULL) [inline], [explicit]
Definition at line 43 of file prototype-inl.h.
    : isolate_(isolate),
      object_(receiver_map->GetPrototypeChainRootMap(isolate_)->prototype()),
      where_to_end_(where_to_end),
      is_at_end_(IsNull(object_, isolate_)),
      seen_proxies_(0) {
  if (!is_at_end_ && where_to_end_ == END_AT_NON_HIDDEN) {
    DCHECK(IsJSReceiver(object_));
    Tagged<Map> map = Cast<JSReceiver>(object_)->map();
    is_at_end_ = !IsJSGlobalProxyMap(map);
  }
}
References v8::internal::DCHECK(), END_AT_NON_HIDDEN, is_at_end_, object_, and where_to_end_.
PrototypeIterator() [4/5]
v8::internal::PrototypeIterator::PrototypeIterator (Isolate * isolate, DirectHandle< Map > receiver_map, WhereToEnd where_to_end = END_AT_NULL) [inline], [explicit]
Definition at line 57 of file prototype-inl.h.
    : isolate_(isolate),
      handle_(receiver_map->GetPrototypeChainRootMap(isolate_)->prototype(),
              isolate_),
      where_to_end_(where_to_end),
      is_at_end_(IsNull(*handle_, isolate_)),
      seen_proxies_(0) {
  if (!is_at_end_ && where_to_end_ == END_AT_NON_HIDDEN) {
    DCHECK(IsJSReceiver(*handle_));
    Tagged<Map> map = Cast<JSReceiver>(*handle_)->map();
    is_at_end_ = !IsJSGlobalProxyMap(map);
  }
}
References v8::internal::DCHECK(), END_AT_NON_HIDDEN, handle_, is_at_end_, and where_to_end_.
 PrototypeIterator()
v8::internal::PrototypeIterator::~PrototypeIterator () [default]
PrototypeIterator() [5/5]
v8::internal::PrototypeIterator::PrototypeIterator (const PrototypeIterator &) [delete]
Member Function Documentation
Advance()
void v8::internal::PrototypeIterator::Advance () [inline]
Definition at line 84 of file prototype-inl.h.
                                {
  if (handle_.is_null() && IsJSProxy(object_)) {
    is_at_end_ = true;
    object_ = ReadOnlyRoots(isolate_).null_value();
    return;
  } else if (!handle_.is_null() && IsJSProxy(*handle_)) {
    is_at_end_ = true;
    handle_ = isolate_->factory()->null_value();
    return;
  }
  AdvanceIgnoringProxies();
}
References AdvanceIgnoringProxies(), v8::internal::Isolate::factory(), handle_, is_at_end_, isolate_, and object_.
Referenced by v8::Object::FindInstanceInPrototypeChain(), v8::internal::Runtime::GetInternalProperties(), v8::Object::GetPrototypeV2(), v8::internal::anonymous_namespace{builtins-array.cc}::HasOnlySimpleElements(), PrototypeIterator(), and v8::internal::JSObject::SetPrototype().
AdvanceFollowingProxies()
V8_WARN_UNUSED_RESULT bool v8::internal::PrototypeIterator::AdvanceFollowingProxies () [inline]
Definition at line 112 of file prototype-inl.h.
                                                                      {
  DCHECK(!(handle_.is_null() && IsJSProxy(object_)));
  if (!HasAccess()) {
    // Abort the lookup if we do not have access to the current object.
    handle_ = isolate_->factory()->null_value();
    is_at_end_ = true;
    return true;
  }
  return AdvanceFollowingProxiesIgnoringAccessChecks();
}
References AdvanceFollowingProxiesIgnoringAccessChecks(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), handle_, HasAccess(), is_at_end_, isolate_, and object_.
Referenced by v8::internal::JSReceiver::GetPrototype(), v8::internal::JSReceiver::HasInPrototypeChain(), and v8::internal::AlwaysSharedSpaceJSObject::HasInstance().
AdvanceFollowingProxiesIgnoringAccessChecks()
V8_WARN_UNUSED_RESULT bool v8::internal::PrototypeIterator::AdvanceFollowingProxiesIgnoringAccessChecks () [inline]
Definition at line 124 of file prototype-inl.h.
                                                               {
  if (handle_.is_null() || !IsJSProxy(*handle_)) {
    AdvanceIgnoringProxies();
    return true;
  }
  // Due to possible __proto__ recursion limit the number of Proxies
  // we visit to an arbitrarily chosen large number.
  seen_proxies_++;
  if (seen_proxies_ > JSProxy::kMaxIterationLimit) {
    isolate_->StackOverflow();
    return false;
  }
  MaybeDirectHandle<JSPrototype> proto =
      JSProxy::GetPrototype(Cast<JSProxy>(handle_));
  // TODO(372390038): This can be again simplified when handle_ migrates to a
  // direct handle.
  DirectHandle<JSPrototype> proto_direct_handle;
  bool ok = proto.ToHandle(&proto_direct_handle);
  handle_ = indirect_handle(proto_direct_handle, isolate_);
  if (!ok) return false;
  is_at_end_ = where_to_end_ == END_AT_NON_HIDDEN || IsNull(*handle_, isolate_);
  return true;
}
References AdvanceIgnoringProxies(), END_AT_NON_HIDDEN, v8::internal::JSProxy::GetPrototype(), handle_, v8::internal::indirect_handle(), is_at_end_, v8::internal::IsNull(), isolate_, v8::internal::JSProxy::kMaxIterationLimit, seen_proxies_, v8::internal::Isolate::StackOverflow(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and where_to_end_.
Referenced by AdvanceFollowingProxies().
AdvanceIgnoringProxies()
void v8::internal::PrototypeIterator::AdvanceIgnoringProxies () [inline]
Definition at line 97 of file prototype-inl.h.
                                               {
  Tagged<JSPrototype> object = handle_.is_null() ? object_ : *handle_;
  Tagged<Map> map = object->map();
  Tagged<JSPrototype> prototype = map->prototype();
  is_at_end_ = IsNull(prototype, isolate_) ||
               (where_to_end_ == END_AT_NON_HIDDEN && !IsJSGlobalProxyMap(map));
  if (handle_.is_null()) {
    object_ = prototype;
  } else {
    handle_ = handle(prototype, isolate_);
  }
}
References END_AT_NON_HIDDEN, v8::internal::handle(), handle_, is_at_end_, v8::internal::IsNull(), isolate_, object_, v8::internal::prototype, and where_to_end_.
Referenced by Advance(), AdvanceFollowingProxiesIgnoringAccessChecks(), and v8::internal::DebugPropertyIterator::AdvanceToPrototype().
GetCurrent() [1/2]
template<typename T = JSPrototype>
Tagged<T> v8::internal::PrototypeIterator::GetCurrent () const [inline]
Definition at line 52 of file prototype.h.
                               {
    DCHECK(handle_.is_null());
    return Cast<T>(object_);
  }
References v8::internal::DCHECK(), handle_, and object_.
Referenced by v8::internal::V8HeapExplorer::ExtractJSObjectReferences(), v8::Object::FindInstanceInPrototypeChain(), v8::internal::GetHomeObjectPrototype(), v8::internal::Runtime::GetInternalProperties(), v8::Object::GetPrototypeV2(), v8::internal::JSReceiver::HasInPrototypeChain(), v8::internal::AlwaysSharedSpaceJSObject::HasInstance(), v8::FunctionTemplate::HasInstance(), v8::internal::anonymous_namespace{builtins-array.cc}::HasOnlySimpleElements(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::JSGlobalProxy::IsDetachedFrom(), v8::internal::JSObject::IsExtensible(), v8::internal::JSObject::LazyRegisterPrototypeUser(), v8::internal::StoreIC::LookupForWrite(), v8::internal::JSObject::MakePrototypesFast(), v8::internal::JSObject::PreventExtensions(), and v8::internal::JSObject::PreventExtensionsWithTransition().
GetCurrent() [2/2]
template<typename T = JSPrototype>
static DirectHandle<T> v8::internal::PrototypeIterator::GetCurrent (const PrototypeIterator & iterator) [inline], [static]
Definition at line 58 of file prototype.h.
                                                                       {
    DCHECK(!iterator.handle_.is_null());
    DCHECK_EQ(iterator.object_, Tagged<HeapObject>());
    return Cast<T>(iterator.handle_);
  }
References v8::internal::DCHECK(), DCHECK_EQ, handle_, and object_.
HasAccess()
bool v8::internal::PrototypeIterator::HasAccess () const [inline]
Definition at line 73 of file prototype-inl.h.
                                        {
  // We can only perform access check in the handlified version of the
  // PrototypeIterator.
  DCHECK(!handle_.is_null());
  if (IsAccessCheckNeeded(*handle_)) {
    return isolate_->MayAccess(isolate_->native_context(),
                               Cast<JSObject>(handle_));
  }
  return true;
}
References v8::internal::DCHECK(), handle_, isolate_, v8::internal::Isolate::MayAccess(), and v8::internal::Isolate::native_context().
Referenced by AdvanceFollowingProxies(), v8::internal::DebugPropertyIterator::AdvanceToPrototype(), and v8::internal::Runtime::GetInternalProperties().
IsAtEnd()
bool v8::internal::PrototypeIterator::IsAtEnd () const [inline]
Definition at line 74 of file prototype.h.
{ return is_at_end_; }
References is_at_end_.
Referenced by v8::internal::DebugPropertyIterator::AdvanceToPrototype(), v8::internal::JSFunction::CalculateExpectedNofProperties(), v8::internal::anonymous_namespace{builtins-array.cc}::CollectElementIndices(), v8::internal::KeyAccumulator::CollectKeys(), v8::Object::FindInstanceInPrototypeChain(), v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper(), v8::internal::Runtime::GetInternalProperties(), v8::internal::JSReceiver::GetPrototype(), v8::Object::GetRealNamedPropertyAttributesInPrototypeChain(), v8::Object::GetRealNamedPropertyInPrototypeChain(), v8::internal::JSReceiver::HasInPrototypeChain(), v8::internal::AlwaysSharedSpaceJSObject::HasInstance(), v8::FunctionTemplate::HasInstance(), v8::internal::anonymous_namespace{builtins-array.cc}::HasOnlySimpleElements(), v8::internal::JSReceiver::HasProxyInPrototype(), v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodName(), v8::internal::JSObject::IsExtensible(), v8::internal::JSObject::LazyRegisterPrototypeUser(), v8::internal::JSObject::MakePrototypesFast(), v8::internal::MayHaveInterestingProperties(), v8::internal::anonymous_namespace{ic.cc}::MayHaveTypedArrayInPrototypeChain(), v8::internal::FastKeyAccumulator::Prepare(), v8::internal::JSObject::PreventExtensions(), v8::internal::JSObject::PreventExtensionsWithTransition(), v8::internal::StringStream::PrintPrototype(), v8::internal::JSObject::SetPrototype(), and v8::internal::Map::ShouldCheckForReadOnlyElementsInPrototypeChain().
isolate()
Isolate* v8::internal::PrototypeIterator::isolate () const [inline]
Definition at line 75 of file prototype.h.
{ return isolate_; }
References isolate_.
operator=()
PrototypeIterator& v8::internal::PrototypeIterator::operator= (const PrototypeIterator &) [delete]
Member Data Documentation
handle_
IndirectHandle<JSPrototype> v8::internal::PrototypeIterator::handle_ [private]
Definition at line 83 of file prototype.h.
Referenced by Advance(), AdvanceFollowingProxies(), AdvanceFollowingProxiesIgnoringAccessChecks(), AdvanceIgnoringProxies(), GetCurrent(), HasAccess(), and PrototypeIterator().
is_at_end_
bool v8::internal::PrototypeIterator::is_at_end_ [private]
Definition at line 85 of file prototype.h.
Referenced by Advance(), AdvanceFollowingProxies(), AdvanceFollowingProxiesIgnoringAccessChecks(), AdvanceIgnoringProxies(), IsAtEnd(), and PrototypeIterator().
isolate_
Isolate* v8::internal::PrototypeIterator::isolate_ [private]
Definition at line 78 of file prototype.h.
Referenced by Advance(), AdvanceFollowingProxies(), AdvanceFollowingProxiesIgnoringAccessChecks(), AdvanceIgnoringProxies(), HasAccess(), and isolate().
object_
Tagged<JSPrototype> v8::internal::PrototypeIterator::object_ = {} [private]
Definition at line 79 of file prototype.h.
Referenced by Advance(), AdvanceFollowingProxies(), AdvanceIgnoringProxies(), GetCurrent(), and PrototypeIterator().
seen_proxies_
int v8::internal::PrototypeIterator::seen_proxies_ [private]
Definition at line 86 of file prototype.h.
Referenced by AdvanceFollowingProxiesIgnoringAccessChecks().
where_to_end_
WhereToEnd v8::internal::PrototypeIterator::where_to_end_ [private]
Definition at line 84 of file prototype.h.
Referenced by AdvanceFollowingProxiesIgnoringAccessChecks(), AdvanceIgnoringProxies(), and PrototypeIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/prototype.h
/mnt/V8SourceCode/src/objects/prototype-inl.h