v8::internal::wasm::BuiltinLookup Class Reference
#include <wasm-builtin-list.h>
Static Public Member Functions
static constexpr int JumptableIndexForBuiltin (Builtin builtin)
static constexpr Builtin BuiltinForJumptableIndex (int index)
static constexpr int BuiltinCount ()
static bool IsWasmBuiltinId (Builtin id)
Static Private Attributes
static constexpr int kBuiltinCount
static constexpr auto kFarJumpTableIndexToBuiltin
static constexpr auto kBuiltinToFarJumpTableIndex
Detailed Description
Definition at line 189 of file wasm-builtin-list.h.
Member Function Documentation
BuiltinCount()
static constexpr int v8::internal::wasm::BuiltinLookup::BuiltinCount () [inline], [static], [constexpr]
Definition at line 203 of file wasm-builtin-list.h.
{ return kBuiltinCount; }
References kBuiltinCount.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize(), v8::internal::wasm::NativeModule::GetBuiltinInJumptableSlot(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::OverheadPerCodeSpace(), and v8::internal::wasm::NativeModule::PatchJumpTableLocked().
BuiltinForJumptableIndex()
static constexpr Builtin v8::internal::wasm::BuiltinLookup::BuiltinForJumptableIndex (int index) [inline], [static], [constexpr]
Definition at line 197 of file wasm-builtin-list.h.
                                                               {
    Builtin result = kFarJumpTableIndexToBuiltin[index];
    DCHECK_EQ(index, kBuiltinToFarJumpTableIndex[static_cast<int>(result)]);
    return result;
  }
References DCHECK_EQ, v8::internal::index, kBuiltinToFarJumpTableIndex, kFarJumpTableIndexToBuiltin, and v8::base::internal::result.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), and v8::internal::wasm::NativeModule::GetBuiltinInJumptableSlot().
IsWasmBuiltinId()
static bool v8::internal::wasm::BuiltinLookup::IsWasmBuiltinId (Builtin id) [inline], [static]
Definition at line 205 of file wasm-builtin-list.h.
                                          {
    switch (id) {
#define BUILTIN_ID(Name) \
  case Builtin::k##Name: \
    return true;
#define BUILTIN_ID_TRAP(Name) \
  case Builtin::kThrowWasm##Name: \
    return true;
      WASM_BUILTIN_LIST(BUILTIN_ID, BUILTIN_ID_TRAP)
      default:
        return false;
    }
  }
References BUILTIN_ID, BUILTIN_ID_TRAP, and WASM_BUILTIN_LIST.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuiltinAssemblerOptions(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallJS(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallJSBuiltin(), and v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl().
JumptableIndexForBuiltin()
static constexpr int v8::internal::wasm::BuiltinLookup::JumptableIndexForBuiltin (Builtin builtin) [inline], [static], [constexpr]
Definition at line 191 of file wasm-builtin-list.h.
                                                                 {
    int result = kBuiltinToFarJumpTableIndex[static_cast<int>(builtin)];
    DCHECK_EQ(builtin, kFarJumpTableIndexToBuiltin[result]);
    return result;
  }
References DCHECK_EQ, kBuiltinToFarJumpTableIndex, kFarJumpTableIndexToBuiltin, and v8::base::internal::result.
Referenced by v8::internal::wasm::NativeModule::GetJumpTableEntryForBuiltin(), and v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation().
Member Data Documentation
kBuiltinCount
constexpr int v8::internal::wasm::BuiltinLookup::kBuiltinCount [static], [constexpr], [private]
Initial value:
=
      0 WASM_BUILTINS_WITH_JUMP_TABLE_SLOT(BUILTIN_COUNTER, BUILTIN_COUNTER)
Definition at line 221 of file wasm-builtin-list.h.
Referenced by BuiltinCount().
kBuiltinToFarJumpTableIndex
constexpr auto v8::internal::wasm::BuiltinLookup::kBuiltinToFarJumpTableIndex [static], [constexpr], [private]
Initial value:
=
      detail::InitBuiltinToFarJumpTableIndex()
Definition at line 241 of file wasm-builtin-list.h.
Referenced by BuiltinForJumptableIndex(), and JumptableIndexForBuiltin().
kFarJumpTableIndexToBuiltin
constexpr auto v8::internal::wasm::BuiltinLookup::kFarJumpTableIndexToBuiltin [static], [constexpr], [private]
Initial value:
=
      base::make_array<static_cast<int>(kBuiltinCount)>([](size_t index) {
        size_t next_index = 0;
#define DEF_INIT_LOOKUP(NAME)
#define DEF_INIT_LOOKUP_TRAP(NAME)
        WASM_BUILTINS_WITH_JUMP_TABLE_SLOT(DEF_INIT_LOOKUP,
                                           DEF_INIT_LOOKUP_TRAP)
        return Builtin::kNoBuiltinId;
      })
Definition at line 225 of file wasm-builtin-list.h.
Referenced by BuiltinForJumptableIndex(), and JumptableIndexForBuiltin().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-builtin-list.h