v8::internal::compiler::FrameStateFunctionInfo Class Reference
#include <frame-states.h>
Public Member Functions
FrameStateFunctionInfo (FrameStateType type, uint16_t parameter_count, uint16_t max_arguments, int local_count, IndirectHandle< SharedFunctionInfo > shared_info, MaybeIndirectHandle< BytecodeArray > bytecode_array, uint32_t wasm_liftoff_frame_size=0, uint32_t wasm_function_index=-1)
int local_count () const
uint16_t parameter_count () const
uint16_t parameter_count_without_receiver () const
uint16_t max_arguments () const
IndirectHandle< SharedFunctionInfo > shared_info () const
MaybeIndirectHandle< BytecodeArray > bytecode_array () const
FrameStateType type () const
uint32_t wasm_liftoff_frame_size () const
uint32_t wasm_function_index () const
Static Public Member Functions
static bool IsJSFunctionType (FrameStateType type)
Private Attributes
const FrameStateType type_
const uint16_t parameter_count_
const uint16_t max_arguments_
const int local_count_
const IndirectHandle< SharedFunctionInfo > shared_info_
const MaybeIndirectHandle< BytecodeArray > bytecode_array_
Static Private Attributes
static constexpr uint32_t wasm_liftoff_frame_size_ = 0
static constexpr uint32_t wasm_function_index_ = -1
Detailed Description
Definition at line 91 of file frame-states.h.
Constructor & Destructor Documentation
FrameStateFunctionInfo()
v8::internal::compiler::FrameStateFunctionInfo::FrameStateFunctionInfo (FrameStateType type, uint16_t parameter_count, uint16_t max_arguments, int local_count, IndirectHandle< SharedFunctionInfo > shared_info, MaybeIndirectHandle< BytecodeArray > bytecode_array, uint32_t wasm_liftoff_frame_size = 0, uint32_t wasm_function_index = -1) [inline]
Definition at line 93 of file frame-states.h.
      : type_(type),
        parameter_count_(parameter_count),
        max_arguments_(max_arguments),
        local_count_(local_count),
#if V8_ENABLE_WEBASSEMBLY
        wasm_liftoff_frame_size_(wasm_liftoff_frame_size),
        wasm_function_index_(wasm_function_index),
#endif
        shared_info_(shared_info),
        bytecode_array_(bytecode_array) {
  }
Member Function Documentation
bytecode_array()
MaybeIndirectHandle<BytecodeArray> v8::internal::compiler::FrameStateFunctionInfo::bytecode_array () const [inline]
Definition at line 121 of file frame-states.h.
                                                            {
    return bytecode_array_;
  }
References bytecode_array_.
Referenced by v8::internal::compiler::FrameStateInfo::bytecode_array(), and v8::internal::compiler::operator==().
IsJSFunctionType()
static bool v8::internal::compiler::FrameStateFunctionInfo::IsJSFunctionType (FrameStateType type) [inline], [static]
Definition at line 130 of file frame-states.h.
                                                    {
    // This must be in sync with TRANSLATION_JS_FRAME_OPCODE_LIST in
    // translation-opcode.h or bad things happen.
    return type == FrameStateType::kUnoptimizedFunction ||
           type == FrameStateType::kJavaScriptBuiltinContinuation ||
           type == FrameStateType::kJavaScriptBuiltinContinuationWithCatch;
  }
References v8::internal::compiler::kJavaScriptBuiltinContinuation, v8::internal::compiler::kJavaScriptBuiltinContinuationWithCatch, v8::internal::compiler::kUnoptimizedFunction, and type().
Referenced by v8::internal::compiler::FrameStateDescriptor::GetJSFrameCount(), and v8::internal::compiler::FrameStateDescriptor::HasContext().
local_count()
int v8::internal::compiler::FrameStateFunctionInfo::local_count () const [inline]
Definition at line 111 of file frame-states.h.
{ return local_count_; }
References local_count_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::FrameStateInfo::local_count(), and v8::internal::compiler::operator==().
max_arguments()
uint16_t v8::internal::compiler::FrameStateFunctionInfo::max_arguments () const [inline]
Definition at line 117 of file frame-states.h.
{ return max_arguments_; }
References max_arguments_.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::FrameStateInfo::max_arguments(), and v8::internal::compiler::operator==().
parameter_count()
uint16_t v8::internal::compiler::FrameStateFunctionInfo::parameter_count () const [inline]
Definition at line 112 of file frame-states.h.
{ return parameter_count_; }
References parameter_count_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::operator==(), and v8::internal::compiler::FrameStateInfo::parameter_count().
parameter_count_without_receiver()
uint16_t v8::internal::compiler::FrameStateFunctionInfo::parameter_count_without_receiver () const [inline]
Definition at line 113 of file frame-states.h.
                                                    {
    DCHECK_GT(parameter_count_, 0);
    return parameter_count_ - 1;
  }
References DCHECK_GT, and parameter_count_.
Referenced by v8::internal::compiler::FrameStateInfo::parameter_count_without_receiver().
shared_info()
IndirectHandle<SharedFunctionInfo> v8::internal::compiler::FrameStateFunctionInfo::shared_info () const [inline]
Definition at line 118 of file frame-states.h.
                                                         {
    return shared_info_;
  }
References shared_info_.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::operator==(), and v8::internal::compiler::FrameStateInfo::shared_info().
type()
FrameStateType v8::internal::compiler::FrameStateFunctionInfo::type () const [inline]
Definition at line 124 of file frame-states.h.
{ return type_; }
References type_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), IsJSFunctionType(), v8::internal::compiler::operator==(), and v8::internal::compiler::FrameStateInfo::type().
wasm_function_index()
uint32_t v8::internal::compiler::FrameStateFunctionInfo::wasm_function_index () const [inline]
Definition at line 128 of file frame-states.h.
{ return wasm_function_index_; }
References wasm_function_index_.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), and v8::internal::compiler::operator==().
wasm_liftoff_frame_size()
uint32_t v8::internal::compiler::FrameStateFunctionInfo::wasm_liftoff_frame_size () const [inline]
Definition at line 125 of file frame-states.h.
                                           {
    return wasm_liftoff_frame_size_;
  }
References wasm_liftoff_frame_size_.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), and v8::internal::compiler::operator==().
Member Data Documentation
bytecode_array_
const MaybeIndirectHandle<BytecodeArray> v8::internal::compiler::FrameStateFunctionInfo::bytecode_array_ [private]
Definition at line 151 of file frame-states.h.
Referenced by bytecode_array().
local_count_
const int v8::internal::compiler::FrameStateFunctionInfo::local_count_ [private]
Definition at line 142 of file frame-states.h.
Referenced by local_count().
max_arguments_
const uint16_t v8::internal::compiler::FrameStateFunctionInfo::max_arguments_ [private]
Definition at line 141 of file frame-states.h.
Referenced by max_arguments().
parameter_count_
const uint16_t v8::internal::compiler::FrameStateFunctionInfo::parameter_count_ [private]
Definition at line 140 of file frame-states.h.
Referenced by parameter_count(), and parameter_count_without_receiver().
shared_info_
const IndirectHandle<SharedFunctionInfo> v8::internal::compiler::FrameStateFunctionInfo::shared_info_ [private]
Definition at line 150 of file frame-states.h.
Referenced by shared_info().
type_
const FrameStateType v8::internal::compiler::FrameStateFunctionInfo::type_ [private]
Definition at line 139 of file frame-states.h.
Referenced by type().
wasm_function_index_
constexpr uint32_t v8::internal::compiler::FrameStateFunctionInfo::wasm_function_index_ = -1 [static], [constexpr], [private]
Definition at line 148 of file frame-states.h.
Referenced by wasm_function_index().
wasm_liftoff_frame_size_
constexpr uint32_t v8::internal::compiler::FrameStateFunctionInfo::wasm_liftoff_frame_size_ = 0 [static], [constexpr], [private]
Definition at line 147 of file frame-states.h.
Referenced by wasm_liftoff_frame_size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/frame-states.h