v8::internal::compiler::ParameterInfo Class Reference
#include <common-operator.h>
Public Member Functions
ParameterInfo (int index, const char *debug_name)
int index () const
const char * debug_name () const
Static Public Attributes
static constexpr int kMinIndex = Linkage::kJSCallClosureParamIndex
Private Attributes
int index_
const char * debug_name_
Detailed Description
Definition at line 202 of file common-operator.h.
Constructor & Destructor Documentation
ParameterInfo()
v8::internal::compiler::ParameterInfo::ParameterInfo (int index, const char * debug_name) [inline]
Definition at line 206 of file common-operator.h.
      : index_(index), debug_name_(debug_name) {
    DCHECK_LE(kMinIndex, index);
  }
References DCHECK_LE, index(), and kMinIndex.
Member Function Documentation
debug_name()
const char* v8::internal::compiler::ParameterInfo::debug_name () const [inline]
Definition at line 212 of file common-operator.h.
{ return debug_name_; }
References debug_name_.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
index()
int v8::internal::compiler::ParameterInfo::index () const [inline]
Definition at line 211 of file common-operator.h.
{ return index_; }
References index_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator==(), ParameterInfo(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
debug_name_
const char* v8::internal::compiler::ParameterInfo::debug_name_ [private]
Definition at line 216 of file common-operator.h.
Referenced by debug_name().
index_
int v8::internal::compiler::ParameterInfo::index_ [private]
Definition at line 215 of file common-operator.h.
Referenced by index().
kMinIndex
constexpr int v8::internal::compiler::ParameterInfo::kMinIndex = Linkage::kJSCallClosureParamIndex [static], [constexpr]
Definition at line 204 of file common-operator.h.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::GetParameter(), and ParameterInfo().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h