v8::internal::wasm::DecodedNameSection Class Reference
#include <module-decoder.h>
Public Member Functions
DecodedNameSection (base::Vector< const uint8_t > wire_bytes, WireBytesRef name_section)
Private Attributes
IndirectNameMap local_names_
IndirectNameMap label_names_
NameMap type_names_
NameMap table_names_
NameMap memory_names_
NameMap global_names_
NameMap element_segment_names_
NameMap data_segment_names_
IndirectNameMap field_names_
NameMap tag_names_
Friends
class NamesProvider
Detailed Description
Definition at line 59 of file module-decoder.h.
Constructor & Destructor Documentation
DecodedNameSection()
v8::internal::wasm::DecodedNameSection::DecodedNameSection (base::Vector< const uint8_t > wire_bytes, WireBytesRef name_section) [explicit]
Definition at line 680 of file module-decoder.cc.
                                                                  {
  if (name_section.is_empty()) return; // No name section.
  Decoder decoder(wire_bytes.begin() + name_section.offset(),
                  wire_bytes.begin() + name_section.end_offset(),
                  name_section.offset());
  while (decoder.ok() && decoder.more()) {
    uint8_t name_type = decoder.consume_u8("name type");
    if (name_type & 0x80) break; // no varuint7
    uint32_t name_payload_len = decoder.consume_u32v("name payload length");
    if (!decoder.checkAvailable(name_payload_len)) break;
    switch (name_type) {
      case kModuleCode:
      case kFunctionCode:
        // Already handled elsewhere.
        decoder.consume_bytes(name_payload_len);
        break;
      case kLocalCode:
        static_assert(kV8MaxWasmTotalFunctions <= IndirectNameMap::kMaxKey);
        static_assert(kV8MaxWasmFunctionLocals <= NameMap::kMaxKey);
        DecodeIndirectNameMap(local_names_, decoder, name_payload_len);
        break;
      case kLabelCode:
        static_assert(kV8MaxWasmTotalFunctions <= IndirectNameMap::kMaxKey);
        static_assert(kV8MaxWasmFunctionSize <= NameMap::kMaxKey);
        DecodeIndirectNameMap(label_names_, decoder, name_payload_len);
        break;
      case kTypeCode:
        static_assert(kV8MaxWasmTypes <= NameMap::kMaxKey);
        DecodeNameMap(type_names_, decoder, name_payload_len);
        break;
      case kTableCode:
        static_assert(kV8MaxWasmTables <= NameMap::kMaxKey);
        DecodeNameMap(table_names_, decoder, name_payload_len);
        break;
      case kMemoryCode:
        static_assert(kV8MaxWasmMemories <= NameMap::kMaxKey);
        DecodeNameMap(memory_names_, decoder, name_payload_len);
        break;
      case kGlobalCode:
        static_assert(kV8MaxWasmGlobals <= NameMap::kMaxKey);
        DecodeNameMap(global_names_, decoder, name_payload_len);
        break;
      case kElementSegmentCode:
        static_assert(kV8MaxWasmTableInitEntries <= NameMap::kMaxKey);
        DecodeNameMap(element_segment_names_, decoder, name_payload_len);
        break;
      case kDataSegmentCode:
        static_assert(kV8MaxWasmDataSegments <= NameMap::kMaxKey);
        DecodeNameMap(data_segment_names_, decoder, name_payload_len);
        break;
      case kFieldCode:
        static_assert(kV8MaxWasmTypes <= IndirectNameMap::kMaxKey);
        static_assert(kV8MaxWasmStructFields <= NameMap::kMaxKey);
        DecodeIndirectNameMap(field_names_, decoder, name_payload_len);
        break;
      case kTagCode:
        static_assert(kV8MaxWasmTags <= NameMap::kMaxKey);
        DecodeNameMap(tag_names_, decoder, name_payload_len);
        break;
    }
  }
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::Decoder::checkAvailable(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), data_segment_names_, v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMap(), element_segment_names_, v8::internal::wasm::WireBytesRef::end_offset(), field_names_, global_names_, v8::internal::wasm::WireBytesRef::is_empty(), v8::internal::wasm::kDataSegmentCode, v8::internal::wasm::kElementSegmentCode, v8::internal::wasm::kFieldCode, v8::internal::wasm::kFunctionCode, v8::internal::wasm::kGlobalCode, v8::internal::wasm::kLabelCode, v8::internal::wasm::kLocalCode, v8::internal::wasm::AdaptiveMap< AdaptiveMap< WireBytesRef > >::kMaxKey, v8::internal::wasm::AdaptiveMap< WireBytesRef >::kMaxKey, v8::internal::wasm::kMemoryCode, v8::internal::wasm::kModuleCode, v8::internal::wasm::kTableCode, v8::internal::wasm::kTagCode, v8::internal::wasm::kTypeCode, v8::internal::wasm::kV8MaxWasmDataSegments, v8::internal::wasm::kV8MaxWasmFunctionLocals, v8::internal::wasm::kV8MaxWasmFunctionSize, v8::internal::wasm::kV8MaxWasmGlobals, v8::internal::wasm::kV8MaxWasmMemories, v8::internal::wasm::kV8MaxWasmStructFields, v8::internal::wasm::kV8MaxWasmTableInitEntries, v8::internal::wasm::kV8MaxWasmTables, v8::internal::wasm::kV8MaxWasmTags, v8::internal::wasm::kV8MaxWasmTotalFunctions, v8::internal::wasm::kV8MaxWasmTypes, label_names_, local_names_, memory_names_, v8::internal::wasm::Decoder::more(), v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::Decoder::ok(), table_names_, tag_names_, and type_names_.
Friends And Related Function Documentation
NamesProvider
friend class NamesProvider [friend]
Definition at line 65 of file module-decoder.h.
Member Data Documentation
data_segment_names_
NameMap v8::internal::wasm::DecodedNameSection::data_segment_names_ [private]
Definition at line 74 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
element_segment_names_
NameMap v8::internal::wasm::DecodedNameSection::element_segment_names_ [private]
Definition at line 73 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
field_names_
IndirectNameMap v8::internal::wasm::DecodedNameSection::field_names_ [private]
Definition at line 75 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
global_names_
NameMap v8::internal::wasm::DecodedNameSection::global_names_ [private]
Definition at line 72 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
label_names_
IndirectNameMap v8::internal::wasm::DecodedNameSection::label_names_ [private]
Definition at line 68 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
local_names_
IndirectNameMap v8::internal::wasm::DecodedNameSection::local_names_ [private]
Definition at line 67 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
memory_names_
NameMap v8::internal::wasm::DecodedNameSection::memory_names_ [private]
Definition at line 71 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
table_names_
NameMap v8::internal::wasm::DecodedNameSection::table_names_ [private]
Definition at line 70 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
tag_names_
NameMap v8::internal::wasm::DecodedNameSection::tag_names_ [private]
Definition at line 76 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
type_names_
NameMap v8::internal::wasm::DecodedNameSection::type_names_ [private]
Definition at line 69 of file module-decoder.h.
Referenced by DecodedNameSection(), and v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/module-decoder.h
/mnt/V8SourceCode/src/wasm/module-decoder.cc