v8::internal::maglev::PolymorphicAccessInfo Class Reference
#include <maglev-ir.h>
Public Types
enum Kind {
kNotFound
, kConstant
, kConstantDouble
, kDataLoad
,
kModuleExport
, kStringLength
 }
Public Member Functions
Kind kind () const
const ZoneVector< compiler::MapRef > & maps () const
DirectHandle< Object > constant () const
double constant_double () const
DirectHandle< Cell > cell () const
compiler::OptionalJSObjectRef holder () const
FieldIndex field_index () const
Representation field_representation () const
bool operator== (const PolymorphicAccessInfo &other) const
size_t hash_value () const
Static Public Member Functions
static PolymorphicAccessInfo NotFound (const ZoneVector< compiler::MapRef > &maps)
static PolymorphicAccessInfo Constant (const ZoneVector< compiler::MapRef > &maps, compiler::ObjectRef constant)
static PolymorphicAccessInfo ConstantDouble (const ZoneVector< compiler::MapRef > &maps, Float64 constant)
static PolymorphicAccessInfo DataLoad (const ZoneVector< compiler::MapRef > &maps, Representation representation, compiler::OptionalJSObjectRef holder, FieldIndex field_index)
static PolymorphicAccessInfo ModuleExport (const ZoneVector< compiler::MapRef > &maps, compiler::CellRef cell)
static PolymorphicAccessInfo StringLength (const ZoneVector< compiler::MapRef > &maps)
Private Member Functions
PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > &maps, Representation representation)
PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > &maps, Representation representation, compiler::ObjectRef constant)
PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > &maps, Float64 constant)
PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > &maps, Representation representation, compiler::OptionalJSObjectRef holder, FieldIndex field_index)
Private Attributes
const Kind kind_
const ZoneVector< compiler::MapRef > maps_
const Representation representation_
xx xx xx xx xx xx xx xx xx
union {
 const compiler::ObjectRef constant_
 const Float64 constant_double_
 struct {
  const compiler::OptionalJSObjectRef holder_
  const FieldIndex field_index_
 } data_load_
};
Detailed Description
Definition at line 7928 of file maglev-ir.h.
Member Enumeration Documentation
Kind
enum v8::internal::maglev::PolymorphicAccessInfo::Kind
Enumerator
kNotFound
kConstant
kConstantDouble
kDataLoad
kModuleExport
kStringLength
Definition at line 7930 of file maglev-ir.h.
            {
    kNotFound,
    kConstant,
    kConstantDouble,
    kDataLoad,
    kModuleExport,
    kStringLength,
  };
Constructor & Destructor Documentation
PolymorphicAccessInfo() [1/4]
v8::internal::maglev::PolymorphicAccessInfo::PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > & maps, Representation representation) [inline], [explicit], [private]
Definition at line 8054 of file maglev-ir.h.
      : kind_(kind), maps_(maps), representation_(representation) {
    DCHECK(kind == kNotFound || kind == kStringLength);
  }
References DCHECK, and v8::internal::kNotFound.
PolymorphicAccessInfo() [2/4]
v8::internal::maglev::PolymorphicAccessInfo::PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > & maps, Representation representation, compiler::ObjectRef constant) [inline], [private]
Definition at line 8061 of file maglev-ir.h.
      : kind_(kind),
        maps_(maps),
        representation_(representation),
        constant_(constant) {
    DCHECK(kind == kConstant || kind == kModuleExport);
  }
References DCHECK.
PolymorphicAccessInfo() [3/4]
v8::internal::maglev::PolymorphicAccessInfo::PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > & maps, Float64 constant) [inline], [private]
Definition at line 8071 of file maglev-ir.h.
      : kind_(kind),
        maps_(maps),
        representation_(Representation::Double()),
        constant_double_(constant) {
    DCHECK_EQ(kind, kConstantDouble);
  }
References DCHECK_EQ.
PolymorphicAccessInfo() [4/4]
v8::internal::maglev::PolymorphicAccessInfo::PolymorphicAccessInfo (Kind kind, const ZoneVector< compiler::MapRef > & maps, Representation representation, compiler::OptionalJSObjectRef holder, FieldIndex field_index) [inline], [private]
Definition at line 8080 of file maglev-ir.h.
      : kind_(kind),
        maps_(maps),
        representation_(representation),
        data_load_{holder, field_index} {
    DCHECK_EQ(kind, kDataLoad);
  }
References DCHECK_EQ.
Member Function Documentation
cell()
DirectHandle<Cell> v8::internal::maglev::PolymorphicAccessInfo::cell () const [inline]
Definition at line 7982 of file maglev-ir.h.
                                  {
    DCHECK_EQ(kind_, kModuleExport);
    return constant_.AsCell().object();
  }
References DCHECK_EQ.
constant()
DirectHandle<Object> v8::internal::maglev::PolymorphicAccessInfo::constant () const [inline]
Definition at line 7972 of file maglev-ir.h.
                                        {
    DCHECK_EQ(kind_, kConstant);
    return constant_.object();
  }
References DCHECK_EQ.
Constant()
static PolymorphicAccessInfo v8::internal::maglev::PolymorphicAccessInfo::Constant (const ZoneVector< compiler::MapRef > & maps, compiler::ObjectRef constant) [inline], [static]
Definition at line 7943 of file maglev-ir.h.
                                                                          {
    return PolymorphicAccessInfo(kConstant, maps, Representation::Tagged(),
                                 constant);
  }
References v8::internal::Tagged().
constant_double()
double v8::internal::maglev::PolymorphicAccessInfo::constant_double () const [inline]
Definition at line 7977 of file maglev-ir.h.
                                 {
    DCHECK_EQ(kind_, kConstantDouble);
    return constant_double_.get_scalar();
  }
References DCHECK_EQ.
ConstantDouble()
static PolymorphicAccessInfo v8::internal::maglev::PolymorphicAccessInfo::ConstantDouble (const ZoneVector< compiler::MapRef > & maps, Float64 constant) [inline], [static]
Definition at line 7948 of file maglev-ir.h.
                                                                {
    return PolymorphicAccessInfo(kConstantDouble, maps, constant);
  }
DataLoad()
static PolymorphicAccessInfo v8::internal::maglev::PolymorphicAccessInfo::DataLoad (const ZoneVector< compiler::MapRef > & maps, Representation representation, compiler::OptionalJSObjectRef holder, FieldIndex field_index) [inline], [static]
Definition at line 7952 of file maglev-ir.h.
                                                                  {
    return PolymorphicAccessInfo(kDataLoad, maps, representation, holder,
                                 field_index);
  }
field_index()
FieldIndex v8::internal::maglev::PolymorphicAccessInfo::field_index () const [inline]
Definition at line 7992 of file maglev-ir.h.
                                 {
    DCHECK_EQ(kind_, kDataLoad);
    return data_load_.field_index_;
  }
References DCHECK_EQ.
Referenced by v8::internal::maglev::MaglevAssembler::LoadDataField().
field_representation()
Representation v8::internal::maglev::PolymorphicAccessInfo::field_representation () const [inline]
Definition at line 7997 of file maglev-ir.h.
{ return representation_; }
hash_value()
size_t v8::internal::maglev::PolymorphicAccessInfo::hash_value () const [inline]
Definition at line 8026 of file maglev-ir.h.
                            {
    size_t hash = base::hash_value(kind_);
    hash = base::hash_combine(hash, base::hash_value(representation_.kind()));
    for (auto map : maps()) {
      hash = base::hash_combine(hash, map.hash_value());
    }
    switch (kind_) {
      case kNotFound:
      case kStringLength:
        break;
      case kModuleExport:
      case kConstant:
        hash = base::hash_combine(hash, constant_.hash_value());
        break;
      case kConstantDouble:
        hash = base::hash_combine(hash, base::hash_value(constant_double_));
        break;
      case kDataLoad:
        hash = base::hash_combine(
            hash, base::hash_value(data_load_.holder_.hash_value()));
        hash = base::hash_combine(
            hash, base::hash_value(data_load_.field_index_.index()));
        break;
    }
    return hash;
  }
References v8::base::hash_combine(), v8::base::hash_value(), and v8::internal::kNotFound.
Referenced by v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value().
holder()
compiler::OptionalJSObjectRef v8::internal::maglev::PolymorphicAccessInfo::holder () const [inline]
Definition at line 7987 of file maglev-ir.h.
                                             {
    DCHECK_EQ(kind_, kDataLoad);
    return data_load_.holder_;
  }
References DCHECK_EQ.
Referenced by v8::internal::maglev::MaglevAssembler::LoadDataField().
kind()
Kind v8::internal::maglev::PolymorphicAccessInfo::kind () const [inline]
Definition at line 7968 of file maglev-ir.h.
{ return kind_; }
maps()
const ZoneVector<compiler::MapRef>& v8::internal::maglev::PolymorphicAccessInfo::maps () const [inline]
Definition at line 7970 of file maglev-ir.h.
{ return maps_; }
ModuleExport()
static PolymorphicAccessInfo v8::internal::maglev::PolymorphicAccessInfo::ModuleExport (const ZoneVector< compiler::MapRef > & maps, compiler::CellRef cell) [inline], [static]
Definition at line 7958 of file maglev-ir.h.
                                                                    {
    return PolymorphicAccessInfo(kModuleExport, maps, Representation::Tagged(),
                                 cell);
  }
References v8::internal::Tagged().
NotFound()
static PolymorphicAccessInfo v8::internal::maglev::PolymorphicAccessInfo::NotFound (const ZoneVector< compiler::MapRef > & maps) [inline], [static]
Definition at line 7939 of file maglev-ir.h.
                                              {
    return PolymorphicAccessInfo(kNotFound, maps, Representation::Tagged());
  }
References v8::internal::kNotFound, and v8::internal::Tagged().
operator==()
bool v8::internal::maglev::PolymorphicAccessInfo::operator== (const PolymorphicAccessInfo & other) const [inline]
Definition at line 7999 of file maglev-ir.h.
                                                            {
    if (kind_ != other.kind_ || !(representation_ == other.representation_)) {
      return false;
    }
    if (maps_.size() != other.maps_.size()) {
      return false;
    }
    for (size_t i = 0; i < maps_.size(); ++i) {
      if (maps_[i] != other.maps_[i]) {
        return false;
      }
    }
    switch (kind_) {
      case kNotFound:
      case kStringLength:
        return true;
      case kModuleExport:
      case kConstant:
        return constant_.equals(other.constant_);
      case kConstantDouble:
        return constant_double_ == other.constant_double_;
      case kDataLoad:
        return data_load_.holder_.equals(other.data_load_.holder_) &&
               data_load_.field_index_ == other.data_load_.field_index_;
    }
  }
References constant_, constant_double_, data_load_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kind_, v8::internal::kNotFound, maps_, and representation_.
StringLength()
static PolymorphicAccessInfo v8::internal::maglev::PolymorphicAccessInfo::StringLength (const ZoneVector< compiler::MapRef > & maps) [inline], [static]
Definition at line 7963 of file maglev-ir.h.
                                              {
    return PolymorphicAccessInfo(kStringLength, maps, Representation::Smi());
  }
Member Data Documentation
union { ... } [private]
constant_
const compiler::ObjectRef v8::internal::maglev::PolymorphicAccessInfo::constant_
Definition at line 8096 of file maglev-ir.h.
Referenced by operator==().
constant_double_
const Float64 v8::internal::maglev::PolymorphicAccessInfo::constant_double_
Definition at line 8097 of file maglev-ir.h.
Referenced by operator==().
struct { ... } v8::internal::maglev::PolymorphicAccessInfo::data_load_
Referenced by operator==().
field_index_
const FieldIndex v8::internal::maglev::PolymorphicAccessInfo::field_index_
Definition at line 8100 of file maglev-ir.h.
holder_
const compiler::OptionalJSObjectRef v8::internal::maglev::PolymorphicAccessInfo::holder_
Definition at line 8099 of file maglev-ir.h.
kind_
const Kind v8::internal::maglev::PolymorphicAccessInfo::kind_ [private]
Definition at line 8091 of file maglev-ir.h.
Referenced by operator==().
maps_
const ZoneVector<compiler::MapRef> v8::internal::maglev::PolymorphicAccessInfo::maps_ [private]
Definition at line 8093 of file maglev-ir.h.
Referenced by operator==().
representation_
const Representation v8::internal::maglev::PolymorphicAccessInfo::representation_ [private]
Definition at line 8094 of file maglev-ir.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h