v8::internal::SnapshotData Class Reference
#include <snapshot-data.h>
Public Member Functions
SnapshotData (const Serializer *serializer)
SnapshotData (const base::Vector< const uint8_t > snapshot)
virtual base::Vector< const uint8_t > Payload () const
base::Vector< const uint8_t > RawData () const
Protected Member Functions
SnapshotData ()
void Resize (uint32_t size)
Static Protected Attributes
static const uint32_t kPayloadLengthOffset = kMagicNumberOffset + kUInt32Size
static const uint32_t kHeaderSize = kPayloadLengthOffset + kUInt32Size
Friends
class SnapshotCompression
Additional Inherited Members
Detailed Description
Definition at line 70 of file snapshot-data.h.
Constructor & Destructor Documentation
SnapshotData() [1/3]
v8::internal::SnapshotData::SnapshotData (const Serializer * serializer) [explicit]
Definition at line 23 of file snapshot-data.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  const std::vector<uint8_t>* payload = serializer->Payload();
  // Calculate sizes.
  uint32_t size = kHeaderSize + static_cast<uint32_t>(payload->size());
  // Allocate backing store and create result data.
  AllocateData(size);
  // Zero out pre-payload data. Part of that is only used for padding.
  memset(data_, 0, kHeaderSize);
  // Set header values.
  SetMagicNumber();
  SetHeaderValue(kPayloadLengthOffset, static_cast<int>(payload->size()));
  // Copy serialized data.
  CopyBytes(data_ + kHeaderSize, payload->data(),
            static_cast<size_t>(payload->size()));
}
References v8::internal::SerializedData::AllocateData(), v8::internal::CopyBytes(), v8::internal::SerializedData::data_, kHeaderSize, kPayloadLengthOffset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::Payload(), v8::internal::SerializedData::SetHeaderValue(), v8::internal::SerializedData::SetMagicNumber(), and size().
SnapshotData() [2/3]
v8::internal::SnapshotData::SnapshotData (const base::Vector< const uint8_t > snapshot) [inline], [explicit]
Definition at line 76 of file snapshot-data.h.
      : SerializedData(const_cast<uint8_t*>(snapshot.begin()),
                       snapshot.length()) {}
SnapshotData() [3/3]
v8::internal::SnapshotData::SnapshotData () [inline], [protected]
Definition at line 89 of file snapshot-data.h.
: SerializedData() {}
Member Function Documentation
Payload()
base::Vector< const uint8_t > v8::internal::SnapshotData::Payload () const [virtual]
Definition at line 45 of file snapshot-data.cc.
                                                      {
  const uint8_t* payload = data_ + kHeaderSize;
  uint32_t length = GetHeaderValue(kPayloadLengthOffset);
  DCHECK_EQ(data_ + size_, payload + length);
  return base::Vector<const uint8_t>(payload, length);
}
References v8::internal::SerializedData::data_, DCHECK_EQ, v8::internal::SerializedData::GetHeaderValue(), kHeaderSize, kPayloadLengthOffset, v8::internal::length, and v8::internal::SerializedData::size_.
Referenced by v8::internal::ReadOnlyArtifacts::InitializeChecksum(), and v8::internal::ReadOnlyArtifacts::VerifyChecksum().
RawData()
base::Vector<const uint8_t> v8::internal::SnapshotData::RawData () const [inline]
Definition at line 82 of file snapshot-data.h.
                                            {
    return base::Vector<const uint8_t>(data_, size_);
  }
Referenced by v8::internal::SnapshotCompression::Compress(), v8::internal::anonymous_namespace{snapshot.cc}::SnapshotImpl::CreateSnapshotBlob(), v8::internal::SnapshotCompression::Decompress(), and v8::internal::ContextDeserializer::DeserializeContext().
Resize()
void v8::internal::SnapshotData::Resize (uint32_t size) [inline], [protected]
Definition at line 94 of file snapshot-data.h.
{ size_ = size; }
References size().
Referenced by v8::internal::SnapshotCompression::Compress().
Friends And Related Function Documentation
SnapshotCompression
friend class SnapshotCompression [friend]
Definition at line 90 of file snapshot-data.h.
Member Data Documentation
kHeaderSize
const uint32_t v8::internal::SnapshotData::kHeaderSize = kPayloadLengthOffset + kUInt32Size [static], [protected]
Definition at line 101 of file snapshot-data.h.
Referenced by Payload(), and SnapshotData().
kPayloadLengthOffset
const uint32_t v8::internal::SnapshotData::kPayloadLengthOffset = kMagicNumberOffset + kUInt32Size [static], [protected]
Definition at line 100 of file snapshot-data.h.
Referenced by Payload(), and SnapshotData().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot-data.h
/mnt/V8SourceCode/src/snapshot/snapshot-data.cc