v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope Class Reference
Public Member Functions
BlockScope (BodyGen *gen, WasmOpcode block_type, base::Vector< const ValueType > param_types, base::Vector< const ValueType > result_types, base::Vector< const ValueType > br_types, bool emit_end=true)
~BlockScope ()
Private Attributes
BodyGen *const gen_
bool emit_end_
Detailed Description
Definition at line 419 of file random-module-generation.cc.
Constructor & Destructor Documentation
BlockScope()
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope (BodyGen * gen, WasmOpcode block_type, base::Vector< const ValueType > param_types, base::Vector< const ValueType > result_types, base::Vector< const ValueType > br_types, bool emit_end = true) [inline]
Definition at line 421 of file random-module-generation.cc.
        : gen_(gen), emit_end_(emit_end) {
      gen->blocks_.emplace_back(br_types.begin(), br_types.end());
      gen->builder_->EmitByte(block_type);
      if (param_types.size() == 0 && result_types.size() == 0) {
        gen->builder_->EmitValueType(kWasmVoid);
        return;
      }
      if (param_types.size() == 0 && result_types.size() == 1) {
        gen->builder_->EmitValueType(result_types[0]);
        return;
      }
      // Multi-value block.
      Zone* zone = gen->builder_->builder()->zone();
      FunctionSig::Builder builder(zone, result_types.size(),
                                   param_types.size());
      for (auto& type : param_types) {
        DCHECK_NE(type, kWasmVoid);
        builder.AddParam(type);
      }
      for (auto& type : result_types) {
        DCHECK_NE(type, kWasmVoid);
        builder.AddReturn(type);
      }
      FunctionSig* sig = builder.Get();
      const bool is_final = true;
      ModuleTypeIndex sig_id =
          gen->builder_->builder()->AddSignature(sig, is_final);
      gen->builder_->EmitI32V(sig_id);
    }
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::wasm::WasmModuleBuilder::AddSignature(), v8::base::Vector< T >::begin(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::blocks_, v8::internal::wasm::WasmFunctionBuilder::builder(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::builder_, DCHECK_NE, v8::internal::wasm::WasmFunctionBuilder::EmitByte(), v8::internal::wasm::WasmFunctionBuilder::EmitI32V(), v8::internal::wasm::WasmFunctionBuilder::EmitValueType(), v8::base::Vector< T >::end(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::wasm::kWasmVoid, v8::internal::sig, v8::base::Vector< T >::size(), v8::internal::tracing::type, and v8::internal::wasm::WasmModuleBuilder::zone().
 BlockScope()
v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::~BlockScope () [inline]
Definition at line 456 of file random-module-generation.cc.
                  {
      if (emit_end_) gen_->builder_->Emit(kExprEnd);
      gen_->blocks_.pop_back();
    }
Member Data Documentation
emit_end_
bool v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::emit_end_ [private]
Definition at line 463 of file random-module-generation.cc.
gen_
BodyGen* const v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::gen_ [private]
Definition at line 462 of file random-module-generation.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/fuzzing/random-module-generation.cc