v8::internal::compiler::fast_api_call::FastApiCallBuilder Class Reference
Public Member Functions
FastApiCallBuilder (Isolate *isolate, TFGraph *graph, GraphAssembler *graph_assembler, const GetParameter &get_parameter, const ConvertReturnValue &convert_return_value, const InitializeOptions &initialize_options, const GenerateSlowApiCall &generate_slow_api_call)
Node * Build (FastApiCallFunction c_function, Node *data_argument)
Private Member Functions
Node * WrapFastCall (const CallDescriptor *call_descriptor, int inputs_size, Node **inputs, Node *target, const CFunctionInfo *c_signature, int c_arg_count, Node *stack_slot)
void PropagateException ()
Isolate * isolate () const
TFGraph * graph () const
GraphAssembler * gasm () const
Private Attributes
Isolate * isolate_
TFGraph * graph_
GraphAssembler * graph_assembler_
const GetParameter & get_parameter_
const ConvertReturnValue & convert_return_value_
const InitializeOptions & initialize_options_
const GenerateSlowApiCall & generate_slow_api_call_
Detailed Description
Definition at line 136 of file fast-api-calls.cc.
Constructor & Destructor Documentation
FastApiCallBuilder()
v8::internal::compiler::fast_api_call::FastApiCallBuilder::FastApiCallBuilder (Isolate * isolate, TFGraph * graph, GraphAssembler * graph_assembler, const GetParameter & get_parameter, const ConvertReturnValue & convert_return_value, const InitializeOptions & initialize_options, const GenerateSlowApiCall & generate_slow_api_call) [inline]
Definition at line 138 of file fast-api-calls.cc.
      : isolate_(isolate),
        graph_(graph),
        graph_assembler_(graph_assembler),
        get_parameter_(get_parameter),
        convert_return_value_(convert_return_value),
        initialize_options_(initialize_options),
        generate_slow_api_call_(generate_slow_api_call) {}
Member Function Documentation
Build()
Node * v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build (FastApiCallFunction c_function, Node * data_argument)
Definition at line 233 of file fast-api-calls.cc.
                                                     {
  const CFunctionInfo* c_signature = c_function.signature;
  const int c_arg_count = c_signature->ArgumentCount();
  // Hint to fast path.
  auto if_success = __ MakeLabel();
  auto if_error = __ MakeDeferredLabel();
  // Generate fast call.
  const int kFastTargetAddressInputIndex = 0;
  const int kFastTargetAddressInputCount = 1;
  const int kEffectAndControlInputCount = 2;
  int extra_input_count =
      kEffectAndControlInputCount + (c_signature->HasOptions() ? 1 : 0);
  Node** const inputs = graph()->zone()->AllocateArray<Node*>(
      kFastTargetAddressInputCount + c_arg_count + extra_input_count);
  ExternalReference::Type ref_type = ExternalReference::FAST_C_CALL;
  // The inputs to {Call} node for the fast call look like:
  // [fast callee, receiver, ... C arguments, [optional Options], effect,
  // control].
  //
  // The first input node represents the target address for the fast call.
  // If the function is not overloaded (c_functions.size() == 1) this is the
  // address associated to the first and only element in the c_functions vector.
  // If there are multiple overloads the value of this input will be set later
  // with a Phi node created by AdaptOverloadedFastCallArgument.
  inputs[kFastTargetAddressInputIndex] = __ ExternalConstant(
      ExternalReference::Create(c_function.address, ref_type));
  for (int i = 0; i < c_arg_count; ++i) {
    inputs[i + kFastTargetAddressInputCount] = get_parameter_(i, &if_error);
  }
  DCHECK_NOT_NULL(inputs[kFastTargetAddressInputIndex]);
  MachineSignature::Builder builder(
      graph()->zone(), 1, c_arg_count + (c_signature->HasOptions() ? 1 : 0));
  MachineType return_type =
      MachineType::TypeForCType(c_signature->ReturnInfo());
  builder.AddReturn(return_type);
  for (int i = 0; i < c_arg_count; ++i) {
    CTypeInfo type = c_signature->ArgumentInfo(i);
    START_ALLOW_USE_DEPRECATED()
    MachineType machine_type =
        type.GetSequenceType() == CTypeInfo::SequenceType::kScalar
            ? MachineType::TypeForCType(type)
            : MachineType::AnyTagged();
    END_ALLOW_USE_DEPRECATED()
    builder.AddParam(machine_type);
  }
  Node* stack_slot = nullptr;
  if (c_signature->HasOptions()) {
    const int kAlign = alignof(v8::FastApiCallbackOptions);
    const int kSize = sizeof(v8::FastApiCallbackOptions);
    // If this check fails, you've probably added new fields to
    // v8::FastApiCallbackOptions, which means you'll need to write code
    // that initializes and reads from them too.
    static_assert(kSize == sizeof(uintptr_t) * 2);
    stack_slot = __ StackSlot(kSize, kAlign);
    __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                                 kNoWriteBarrier),
             stack_slot,
             static_cast<int>(offsetof(v8::FastApiCallbackOptions, isolate)),
             __ ExternalConstant(ExternalReference::isolate_address()));
    Node* data_argument_to_pass = __ AdaptLocalArgument(data_argument);
    __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                                 kNoWriteBarrier),
             stack_slot,
             static_cast<int>(offsetof(v8::FastApiCallbackOptions, data)),
             data_argument_to_pass);
    initialize_options_(stack_slot);
    builder.AddParam(MachineType::Pointer()); // stack_slot
  }
  CallDescriptor* call_descriptor =
      Linkage::GetSimplifiedCDescriptor(graph()->zone(), builder.Get());
  Node* c_call_result =
      WrapFastCall(call_descriptor, c_arg_count + extra_input_count + 1, inputs,
                   inputs[0], c_signature, c_arg_count, stack_slot);
  Node* exception = __ Load(MachineType::IntPtr(),
                            __ ExternalConstant(ExternalReference::Create(
                                IsolateAddressId::kExceptionAddress, isolate_)),
                            0);
  Node* the_hole =
      __ Load(MachineType::IntPtr(), __ LoadRootRegister(),
              IsolateData::root_slot_offset(RootIndex::kTheHoleValue));
  auto throw_label = __ MakeDeferredLabel();
  auto done = __ MakeLabel();
  __ GotoIfNot(__ IntPtrEqual(exception, the_hole), &throw_label);
  __ Goto(&done);
  __ Bind(&throw_label);
  PropagateException();
  __ Unreachable();
  __ Bind(&done);
  Node* fast_call_result = convert_return_value_(c_signature, c_call_result);
  auto merge = __ MakeLabel(MachineRepresentation::kTagged);
  __ Goto(&if_success);
  // We need to generate a fallback (both fast and slow call) in case
  // the generated code might fail, in case e.g. a Smi was passed where
  // a JSObject was expected and an error must be thrown
  if (if_error.IsUsed()) {
    // Generate direct slow call.
    __ Bind(&if_error);
    {
      Node* slow_call_result = generate_slow_api_call_();
      __ Goto(&merge, slow_call_result);
    }
  }
  __ Bind(&if_success);
  __ Goto(&merge, fast_call_result);
  __ Bind(&merge);
  return merge.PhiAt(0);
}
References __, v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::compiler::FastApiCallFunction::address, v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::Zone::AllocateArray(), v8::internal::MachineType::AnyTagged(), v8::CFunctionInfo::ArgumentCount(), v8::CFunctionInfo::ArgumentInfo(), convert_return_value_, v8::internal::ExternalReference::Create(), DCHECK_NOT_NULL, END_ALLOW_USE_DEPRECATED, v8::internal::ExternalReference::FAST_C_CALL, generate_slow_api_call_, v8::internal::SignatureBuilder< SigT, T >::Get(), get_parameter_, v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), graph(), v8::CFunctionInfo::HasOptions(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, initialize_options_, v8::internal::MachineType::IntPtr(), isolate(), isolate_, v8::internal::ExternalReference::isolate_address(), v8::internal::compiler::kNoWriteBarrier, v8::internal::kTagged, v8::Load(), v8::internal::wasm::machine_type(), v8::internal::MachineType::Pointer(), v8::internal::MachineType::PointerRepresentation(), PropagateException(), v8::CFunctionInfo::ReturnInfo(), v8::internal::IsolateData::root_slot_offset(), v8::internal::compiler::FastApiCallFunction::signature, START_ALLOW_USE_DEPRECATED, v8::internal::wasm::liftoff::Store(), v8::internal::tracing::type, v8::internal::MachineType::TypeForCType(), WrapFastCall(), and v8::internal::compiler::TFGraph::zone().
Referenced by v8::internal::compiler::fast_api_call::BuildFastApiCall().
gasm()
GraphAssembler* v8::internal::compiler::fast_api_call::FastApiCallBuilder::gasm () const [inline], [private]
Definition at line 163 of file fast-api-calls.cc.
{ return graph_assembler_; }
References graph_assembler_.
graph()
TFGraph* v8::internal::compiler::fast_api_call::FastApiCallBuilder::graph () const [inline], [private]
Definition at line 162 of file fast-api-calls.cc.
{ return graph_; }
References graph_.
Referenced by Build(), and PropagateException().
isolate()
Isolate* v8::internal::compiler::fast_api_call::FastApiCallBuilder::isolate () const [inline], [private]
Definition at line 161 of file fast-api-calls.cc.
{ return isolate_; }
References isolate_.
Referenced by Build().
PropagateException()
void v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException () [private]
Definition at line 205 of file fast-api-calls.cc.
                                            {
  Runtime::FunctionId fun_id = Runtime::FunctionId::kPropagateException;
  const Runtime::Function* fun = Runtime::FunctionForId(fun_id);
  auto call_descriptor = Linkage::GetRuntimeCallDescriptor(
      graph()->zone(), fun_id, fun->nargs, Operator::kNoProperties,
      CallDescriptor::kNoFlags);
  // The CEntryStub is loaded from the IsolateRoot so that generated code is
  // Isolate independent. At the moment this is only done for CEntryStub(1).
  Node* isolate_root = __ LoadRootRegister();
  DCHECK_EQ(1, fun->result_size);
  auto centry_id = Builtin::kWasmCEntry;
  int builtin_slot_offset = IsolateData::BuiltinSlotOffset(centry_id);
  Node* centry_stub =
      __ Load(MachineType::Pointer(), isolate_root, builtin_slot_offset);
  const int kInputCount = 6;
  Node* inputs[kInputCount];
  int count = 0;
  inputs[count++] = centry_stub;
  inputs[count++] = __ ExternalConstant(ExternalReference::Create(fun_id));
  inputs[count++] = __ Int32Constant(fun->nargs);
  inputs[count++] = __ IntPtrConstant(0);
  inputs[count++] = __ effect();
  inputs[count++] = __ control();
  DCHECK_EQ(kInputCount, count);
  __ Call(call_descriptor, count, inputs);
}
References __, v8::internal::IsolateData::BuiltinSlotOffset(), v8::internal::ExternalReference::Create(), DCHECK_EQ, v8::internal::Runtime::FunctionForId(), v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), graph(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::Load(), v8::internal::Runtime::Function::nargs, v8::internal::MachineType::Pointer(), and v8::internal::Runtime::Function::result_size.
Referenced by Build().
WrapFastCall()
Node * v8::internal::compiler::fast_api_call::FastApiCallBuilder::WrapFastCall (const CallDescriptor * call_descriptor, int inputs_size, Node ** inputs, Node * target, const CFunctionInfo * c_signature, int c_arg_count, Node * stack_slot) [private]
Definition at line 173 of file fast-api-calls.cc.
                                                                          {
  // CPU profiler support
  Node* target_address = __ IsolateField(IsolateFieldId::kFastApiCallTarget);
  __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                               kNoWriteBarrier),
           target_address, 0, __ BitcastTaggedToWord(target));
  // Update effect and control
  if (stack_slot != nullptr) {
    inputs[c_arg_count + 1] = stack_slot;
    inputs[c_arg_count + 2] = __ effect();
    inputs[c_arg_count + 3] = __ control();
  } else {
    inputs[c_arg_count + 1] = __ effect();
    inputs[c_arg_count + 2] = __ control();
  }
  // Create the fast call
  Node* call = __ Call(call_descriptor, inputs_size, inputs);
  // Reset the CPU profiler target address.
  __ Store(StoreRepresentation(MachineType::PointerRepresentation(),
                               kNoWriteBarrier),
           target_address, 0, __ IntPtrConstant(0));
  return call;
}
References __, v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::kNoWriteBarrier, v8::internal::MachineType::PointerRepresentation(), and v8::internal::wasm::liftoff::Store().
Referenced by Build().
Member Data Documentation
convert_return_value_
const ConvertReturnValue& v8::internal::compiler::fast_api_call::FastApiCallBuilder::convert_return_value_ [private]
Definition at line 168 of file fast-api-calls.cc.
Referenced by Build().
generate_slow_api_call_
const GenerateSlowApiCall& v8::internal::compiler::fast_api_call::FastApiCallBuilder::generate_slow_api_call_ [private]
Definition at line 170 of file fast-api-calls.cc.
Referenced by Build().
get_parameter_
const GetParameter& v8::internal::compiler::fast_api_call::FastApiCallBuilder::get_parameter_ [private]
Definition at line 167 of file fast-api-calls.cc.
Referenced by Build().
graph_
TFGraph* v8::internal::compiler::fast_api_call::FastApiCallBuilder::graph_ [private]
Definition at line 165 of file fast-api-calls.cc.
Referenced by graph().
graph_assembler_
GraphAssembler* v8::internal::compiler::fast_api_call::FastApiCallBuilder::graph_assembler_ [private]
Definition at line 166 of file fast-api-calls.cc.
Referenced by gasm().
initialize_options_
const InitializeOptions& v8::internal::compiler::fast_api_call::FastApiCallBuilder::initialize_options_ [private]
Definition at line 169 of file fast-api-calls.cc.
Referenced by Build().
isolate_
Isolate* v8::internal::compiler::fast_api_call::FastApiCallBuilder::isolate_ [private]
Definition at line 164 of file fast-api-calls.cc.
Referenced by Build(), and isolate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/fast-api-calls.cc