v8::internal::interpreter::RegisterList Class Reference
#include <bytecode-register.h>
Public Member Functions
RegisterList ()
RegisterList (Register r)
const RegisterList Truncate (int new_count)
const RegisterList PopLeft () const
const Register operator[] (size_t i) const
const Register first_register () const
const Register last_register () const
int register_count () const
Private Member Functions
RegisterList (int first_reg_index, int register_count)
void IncrementRegisterCount ()
Private Attributes
int first_reg_index_
int register_count_
Friends
class BytecodeRegisterAllocator
class BytecodeDecoder
class InterpreterTester
class BytecodeUtils
class BytecodeArrayIterator
class CallArguments
Detailed Description
Definition at line 149 of file bytecode-register.h.
Constructor & Destructor Documentation
RegisterList() [1/3]
v8::internal::interpreter::RegisterList::RegisterList () [inline]
Definition at line 151 of file bytecode-register.h.
      : first_reg_index_(Register::invalid_value().index()),
        register_count_(0) {}
RegisterList() [2/3]
v8::internal::interpreter::RegisterList::RegisterList (Register r) [inline], [explicit]
Definition at line 154 of file bytecode-register.h.
: RegisterList(r.index(), 1) {}
RegisterList() [3/3]
v8::internal::interpreter::RegisterList::RegisterList (int first_reg_index, int register_count) [inline], [private]
Definition at line 191 of file bytecode-register.h.
      : first_reg_index_(first_reg_index), register_count_(register_count) {}
Member Function Documentation
first_register()
const Register v8::internal::interpreter::RegisterList::first_register () const [inline]
Definition at line 173 of file bytecode-register.h.
                                        {
    return (register_count() == 0) ? Register(0) : (*this)[0];
  }
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegisterList(), v8::internal::interpreter::BytecodeArrayBuilder::GetInputRegisterListOperand(), v8::internal::interpreter::BytecodeArrayBuilder::GetOutputRegisterListOperand(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >::GetResultLocationAndSize(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegisterList(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListAllocateEvent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListFreeEvent(), and v8::internal::interpreter::BytecodeArrayBuilder::RegisterListIsValid().
IncrementRegisterCount()
void v8::internal::interpreter::RegisterList::IncrementRegisterCount () [inline], [private]
Definition at line 195 of file bytecode-register.h.
{ register_count_++; }
Referenced by v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList().
last_register()
const Register v8::internal::interpreter::RegisterList::last_register () const [inline]
Definition at line 177 of file bytecode-register.h.
                                       {
    return (register_count() == 0) ? Register(0) : (*this)[register_count_ - 1];
  }
References v8::internal::ETWJITInterface::Register().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode(), and v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList().
operator[]()
const Register v8::internal::interpreter::RegisterList::operator[] (size_t i) const [inline]
Definition at line 168 of file bytecode-register.h.
                                            {
    DCHECK_LT(static_cast<int>(i), register_count_);
    return Register(first_reg_index_ + static_cast<int>(i));
  }
References DCHECK_LT, and v8::internal::ETWJITInterface::Register().
PopLeft()
const RegisterList v8::internal::interpreter::RegisterList::PopLeft () const [inline]
Definition at line 163 of file bytecode-register.h.
                                     {
    DCHECK_GE(register_count_, 0);
    return RegisterList(first_reg_index_ + 1, register_count_ - 1);
  }
References DCHECK_GE.
Referenced by v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >::Push(), and v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >::PushReverse().
register_count()
int v8::internal::interpreter::RegisterList::register_count () const [inline]
Definition at line 181 of file bytecode-register.h.
{ return register_count_; }
Referenced by v8::internal::maglev::CallArguments::CallArguments(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntimeForPair(), v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegPair >::Convert(), v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegOutPair >::Convert(), v8::internal::interpreter::anonymous_namespace{bytecode-array-builder.cc}::OperandHelper< OperandType::kRegOutTriple >::Convert(), v8::internal::baseline::detail::CountPushHelper< interpreter::RegisterList, Args... >::Count(), v8::internal::interpreter::BytecodeArrayBuilder::ForInNext(), v8::internal::interpreter::BytecodeArrayBuilder::ForInPrepare(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetInputRegisterList(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >::GetResultLocationAndSize(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareOutputRegisterList(), v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >::Push(), v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::Push(), v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::Push(), v8::internal::baseline::detail::PushAllHelper< Arg, interpreter::RegisterList >::PushReverse(), v8::internal::baseline::detail::PushAllHelper< interpreter::RegisterList >::PushReverse(), v8::internal::baseline::detail::PushHelper< interpreter::RegisterList >::PushReverse(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListAllocateEvent(), v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterListFreeEvent(), v8::internal::interpreter::BytecodeArrayBuilder::RegisterListIsValid(), v8::internal::interpreter::BytecodeArrayBuilder::ResumeGenerator(), v8::internal::baseline::detail::ArgumentSettingHelper< Descriptor, ArgIndex, true, interpreter::RegisterList >::Set(), and v8::internal::interpreter::BytecodeArrayBuilder::SuspendGenerator().
Truncate()
const RegisterList v8::internal::interpreter::RegisterList::Truncate (int new_count) [inline]
Definition at line 158 of file bytecode-register.h.
                                             {
    DCHECK_GE(new_count, 0);
    DCHECK_LT(new_count, register_count_);
    return RegisterList(first_reg_index_, new_count);
  }
References DCHECK_GE, and DCHECK_LT.
Friends And Related Function Documentation
BytecodeArrayIterator
friend class BytecodeArrayIterator [friend]
Definition at line 188 of file bytecode-register.h.
BytecodeDecoder
friend class BytecodeDecoder [friend]
Definition at line 185 of file bytecode-register.h.
BytecodeRegisterAllocator
friend class BytecodeRegisterAllocator [friend]
Definition at line 184 of file bytecode-register.h.
BytecodeUtils
friend class BytecodeUtils [friend]
Definition at line 187 of file bytecode-register.h.
CallArguments
friend class CallArguments [friend]
Definition at line 189 of file bytecode-register.h.
InterpreterTester
friend class InterpreterTester [friend]
Definition at line 186 of file bytecode-register.h.
Member Data Documentation
first_reg_index_
int v8::internal::interpreter::RegisterList::first_reg_index_ [private]
Definition at line 197 of file bytecode-register.h.
register_count_
int v8::internal::interpreter::RegisterList::register_count_ [private]
Definition at line 198 of file bytecode-register.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-register.h