v8::internal::RegExpResultVectorScope Class Reference
#include <regexp-result-vector.h>
Public Member Functions
RegExpResultVectorScope (Isolate *isolate)
RegExpResultVectorScope (Isolate *isolate, int size)
~RegExpResultVectorScope ()
int32_t * Initialize (int size)
int32_t * value () const
Private Attributes
Isolate *const isolate_
bool is_dynamic_ = false
int32_t * value_ = nullptr
Detailed Description
Definition at line 14 of file regexp-result-vector.h.
Constructor & Destructor Documentation
RegExpResultVectorScope() [1/2]
v8::internal::RegExpResultVectorScope::RegExpResultVectorScope (Isolate * isolate) [explicit]
Definition at line 12 of file regexp-result-vector.cc.
    : isolate_(isolate) {}
RegExpResultVectorScope() [2/2]
v8::internal::RegExpResultVectorScope::RegExpResultVectorScope (Isolate * isolate, int size)
Definition at line 15 of file regexp-result-vector.cc.
    : isolate_(isolate) {
  Initialize(size);
}
References Initialize(), and size().
 RegExpResultVectorScope()
v8::internal::RegExpResultVectorScope::~RegExpResultVectorScope ()
Definition at line 20 of file regexp-result-vector.cc.
                                                  {
  if (is_dynamic_) {
    RegExpResultVector::Free(isolate_, value_);
  } else if (value_ != nullptr) {
    // Return ownership of the static vector.
    isolate_->set_regexp_static_result_offsets_vector(value_);
  } else {
    // The scope was created but Initialize never called. Nothing to do.
  }
}
References v8::internal::RegExpResultVector::Free(), is_dynamic_, isolate_, v8::internal::Isolate::set_regexp_static_result_offsets_vector(), and value_.
Member Function Documentation
Initialize()
int32_t * v8::internal::RegExpResultVectorScope::Initialize (int size)
Definition at line 31 of file regexp-result-vector.cc.
                                                     {
  DCHECK_NULL(value_);
  int32_t* static_vector_or_null =
      isolate_->regexp_static_result_offsets_vector();
  if (size > Isolate::kJSRegexpStaticOffsetsVectorSize ||
      static_vector_or_null == nullptr) {
    is_dynamic_ = true;
    value_ = RegExpResultVector::Allocate(isolate_, size);
  } else {
    value_ = static_vector_or_null;
    // Take ownership of the static vector. See also:
    // RegExpBuiltinsAssembler::TryLoadStaticRegExpResultVector.
    isolate_->set_regexp_static_result_offsets_vector(nullptr);
  }
  DCHECK_NOT_NULL(value_);
  return value_;
}
References v8::internal::RegExpResultVector::Allocate(), DCHECK_NOT_NULL, DCHECK_NULL, is_dynamic_, isolate_, v8::internal::Isolate::kJSRegexpStaticOffsetsVectorSize, v8::internal::Isolate::regexp_static_result_offsets_vector(), v8::internal::Isolate::set_regexp_static_result_offsets_vector(), size(), and value_.
Referenced by v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner(), and RegExpResultVectorScope().
value()
int32_t* v8::internal::RegExpResultVectorScope::value () const [inline]
Definition at line 22 of file regexp-result-vector.h.
                         {
    DCHECK_NOT_NULL(value_);
    return value_;
  }
References DCHECK_NOT_NULL, and value_.
Referenced by v8::internal::RegExp::Exec_Single().
Member Data Documentation
is_dynamic_
bool v8::internal::RegExpResultVectorScope::is_dynamic_ = false [private]
Definition at line 29 of file regexp-result-vector.h.
Referenced by Initialize(), and ~RegExpResultVectorScope().
isolate_
Isolate* const v8::internal::RegExpResultVectorScope::isolate_ [private]
Definition at line 28 of file regexp-result-vector.h.
Referenced by Initialize(), and ~RegExpResultVectorScope().
value_
int32_t* v8::internal::RegExpResultVectorScope::value_ = nullptr [private]
Definition at line 30 of file regexp-result-vector.h.
Referenced by Initialize(), value(), and ~RegExpResultVectorScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-result-vector.h
/mnt/V8SourceCode/src/regexp/regexp-result-vector.cc