v8::internal::compiler::EscapeAnalysisResult Class Reference
#include <escape-analysis.h>
Public Member Functions
EscapeAnalysisResult (EscapeAnalysisTracker *tracker)
const VirtualObject * GetVirtualObject (Node *node)
Node * GetVirtualObjectField (const VirtualObject *vobject, int field, Node *effect)
Node * GetReplacementOf (Node *node)
Private Attributes
EscapeAnalysisTracker * tracker_
Detailed Description
Definition at line 162 of file escape-analysis.h.
Constructor & Destructor Documentation
EscapeAnalysisResult()
v8::internal::compiler::EscapeAnalysisResult::EscapeAnalysisResult (EscapeAnalysisTracker * tracker) [inline], [explicit]
Definition at line 164 of file escape-analysis.h.
      : tracker_(tracker) {}
Member Function Documentation
GetReplacementOf()
Node* v8::internal::compiler::EscapeAnalysisResult::GetReplacementOf (Node * node)
GetVirtualObject()
const VirtualObject* v8::internal::compiler::EscapeAnalysisResult::GetVirtualObject (Node * node)
Referenced by v8::internal::compiler::EscapeAnalysisReducer::Reduce(), and v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode().
GetVirtualObjectField()
Node* v8::internal::compiler::EscapeAnalysisResult::GetVirtualObjectField (const VirtualObject * vobject, int field, Node * effect)
Referenced by v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState().
Member Data Documentation
tracker_
EscapeAnalysisTracker* v8::internal::compiler::EscapeAnalysisResult::tracker_ [private]
Definition at line 173 of file escape-analysis.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.h