v8::internal::Instruction Class Reference
#include <constants-arm.h>
Public Types
enum CheckAlignment { NO_CHECK
, CHECK_ALIGNMENT
 }
enum OpcodeFormatType { ONE_BYTE_OPCODE
, TWO_BYTE_OPCODE
, TWO_BYTE_DISJOINT_OPCODE
, THREE_NIBBLE_OPCODE
 }
Public Member Functions
Instr InstructionBits () const
V8_EXPORT_PRIVATE void SetInstructionBits (Instr value, WritableJitAllocation *jit_allocation=nullptr)
int Bit (int nr) const
int Bits (int hi, int lo) const
int BitField (int hi, int lo) const
int ConditionValue () const
Condition ConditionField () const
int TypeValue () const
int SpecialValue () const
int RnValue () const
int RdValue () const
int CoprocessorValue () const
int VnValue () const
int VmValue () const
int VdValue () const
int NValue () const
int MValue () const
int DValue () const
int RtValue () const
int PValue () const
int UValue () const
int Opc1Value () const
int Opc2Value () const
int Opc3Value () const
int SzValue () const
int VLValue () const
int VCValue () const
int VAValue () const
int VBValue () const
int VFPNRegValue (VFPRegPrecision pre)
int VFPMRegValue (VFPRegPrecision pre)
int VFPDRegValue (VFPRegPrecision pre)
int OpcodeValue () const
Opcode OpcodeField () const
int SValue () const
int RmValue () const
int ShiftValue () const
ShiftOp ShiftField () const
int RegShiftValue () const
int RsValue () const
int ShiftAmountValue () const
int RotateValue () const
int Immed8Value () const
int Immed4Value () const
int ImmedMovwMovtValue () const
int PUValue () const
int PUField () const
int BValue () const
int WValue () const
int LValue () const
int Offset12Value () const
int RlistValue () const
int SignValue () const
int HValue () const
int ImmedHValue () const
int ImmedLValue () const
int LinkValue () const
int SImmed24Value () const
bool IsBranch ()
int GetBranchOffset ()
void SetBranchOffset (int32_t branch_offset, WritableJitAllocation *jit_allocation)
SoftwareInterruptCodes SvcValue () const
bool IsSpecialType0 () const
bool IsMiscType0 () const
bool IsNopLikeType1 () const
bool IsStop () const
bool HasS () const
bool HasB () const
bool HasW () const
bool HasL () const
bool HasU () const
bool HasSign () const
bool HasH () const
bool HasLink () const
Float64 DoubleImmedVmov () const
Instr InstructionBits () const
V8_EXPORT_PRIVATE void SetInstructionBits (Instr new_instr, WritableJitAllocation *jit_allocation=nullptr)
int Bit (int pos) const
uint32_t Bits (int msb, int lsb) const
int32_t SignedBits (int msb, int lsb) const
Instr Mask (uint32_t mask) const
const Instruction * following (int count=1) const
Instruction * following (int count=1)
const Instruction * preceding (int count=1) const
Instruction * preceding (int count=1)
int ImmPCRel () const
uint64_t ImmLogical ()
unsigned ImmNEONabcdefgh () const
float ImmFP32 ()
double ImmFP64 ()
float ImmNEONFP32 () const
double ImmNEONFP64 () const
unsigned SizeLS () const
unsigned SizeLSPair () const
int NEONLSIndex (int access_size_shift) const
bool IsCondBranchImm () const
bool IsUncondBranchImm () const
bool IsCompareBranch () const
bool IsTestBranch () const
bool IsImmBranch () const
bool IsLdrLiteral () const
bool IsLdrLiteralX () const
bool IsLdrLiteralW () const
bool IsPCRelAddressing () const
bool IsAdr () const
bool IsBrk () const
bool IsUnresolvedInternalReference () const
bool IsLogicalImmediate () const
bool IsAddSubImmediate () const
bool IsAddSubShifted () const
bool IsAddSubExtended () const
bool IsLoadOrStore () const
bool IsLoad () const
bool IsStore () const
Reg31Mode RdMode () const
Reg31Mode RnMode () const
ImmBranchType BranchType () const
int ImmBranch () const
int ImmUnresolvedInternalReference () const
bool IsUnconditionalBranch () const
bool IsBranchAndLink () const
bool IsBranchAndLinkToRegister () const
bool IsMovz () const
bool IsMovk () const
bool IsMovn () const
bool IsException () const
bool IsPAuth () const
bool IsBti () const
bool IsNop (int n)
V8_EXPORT_PRIVATE int64_t ImmPCOffset ()
V8_EXPORT_PRIVATE Instruction * ImmPCOffsetTarget ()
bool IsTargetInImmPCOffsetRange (Instruction *target)
void SetImmPCOffsetTarget (Zone *zone, AssemblerOptions options, Instruction *target)
void SetUnresolvedInternalReferenceImmTarget (Zone *zone, AssemblerOptions options, Instruction *target)
void SetImmLLiteral (Instruction *source)
uintptr_t LiteralAddress ()
const Instruction * InstructionAtOffset (int64_t offset, CheckAlignment check=CHECK_ALIGNMENT) const
Instruction * InstructionAtOffset (int64_t offset, CheckAlignment check=CHECK_ALIGNMENT)
ptrdiff_t DistanceTo (Instruction *target)
void SetPCRelImmTarget (Zone *zone, AssemblerOptions options, Instruction *target)
template<ImmBranchType branch_type>
void SetBranchImmTarget (Instruction *target, WritableJitAllocation *jit_allocation=nullptr)
Instr InstructionBits () const
V8_EXPORT_PRIVATE void SetInstructionBits (Instr value, WritableJitAllocation *jit_allocation=nullptr)
int Bit (int nr) const
int Bits (int hi, int lo) const
uint32_t BitField (int hi, int lo) const
int RSValue () const
int RTValue () const
int RAValue () const
int RBValue () const
int RCValue () const
int OpcodeValue () const
uint32_t OpcodeField () const
uint32_t PrefixOpcodeField () const
Opcode OpcodeBase () const
SoftwareInterruptCodes SvcValue () const
template<typename T >
T InstructionBits () const
Instr InstructionBits () const
template<typename T >
void SetInstructionBits (T value, WritableJitAllocation *jit_allocation=nullptr) const
V8_EXPORT_PRIVATE void SetInstructionBits (Instr value, WritableJitAllocation *jit_allocation=nullptr)
int Bit (int nr) const
int Bits (int hi, int lo) const
template<typename T , typename U >
U Bits (int hi, int lo) const
int BitField (int hi, int lo) const
int InstructionLength ()
Opcode S390OpcodeValue ()
SoftwareInterruptCodes SvcValue () const
Static Public Member Functions
static Instruction * At (Address pc)
static float Imm8ToFP32 (uint32_t imm8)
static double Imm8ToFP64 (uint32_t imm8)
static constexpr int ImmBranchRangeBitwidth (ImmBranchType branch_type)
static constexpr int32_t ImmBranchRange (ImmBranchType branch_type)
static constexpr bool IsValidImmPCOffset (ImmBranchType branch_type, ptrdiff_t offset)
template<typename T >
static Instruction * Cast (T src)
static bool IsValidPCRelOffset (ptrdiff_t offset)
static Instruction * At (uint8_t *pc)
static Instruction * At (uint8_t *pc)
static int Bit (Instr instr, int nr)
static int Bits (Instr instr, int hi, int lo)
static uint32_t BitField (Instr instr, int hi, int lo)
static Instruction * At (uint8_t *pc)
static Instruction * At (uint8_t *pc)
static int Bit (Instr instr, int nr)
static int Bits (Instr instr, int hi, int lo)
static int BitField (Instr instr, int hi, int lo)
static int InstructionLength (const uint8_t *instr)
static uint64_t InstructionBits (const uint8_t *instr)
template<typename T >
static T InstructionBits (const uint8_t *instr)
template<typename T >
static void SetInstructionBits (uint8_t *instr, T value, WritableJitAllocation *jit_allocation=nullptr)
static OpcodeFormatType getOpcodeFormatType (const uint8_t *instr)
static Opcode S390OpcodeValue (const uint8_t *instr)
static Instruction * At (uint8_t *pc)
Static Public Attributes
static constexpr int kPcLoadDelta = 8
static const int ImmPCRelRangeBitwidth = 21
static OpcodeFormatType OpcodeFormatTable [256]
Private Member Functions
int VFPGlueRegValue (VFPRegPrecision pre, int four_bit, int one_bit)
DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction)
DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction)
DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction)
DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction)
DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction)
DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction)
Additional Inherited Members
Detailed Description
Definition at line 451 of file constants-arm.h.
Member Enumeration Documentation
CheckAlignment
enum v8::internal::Instruction::CheckAlignment
Enumerator
NO_CHECK
CHECK_ALIGNMENT
Definition at line 441 of file instructions-arm64.h.
{ NO_CHECK, CHECK_ALIGNMENT };
OpcodeFormatType
enum v8::internal::Instruction::OpcodeFormatType
Enumerator
ONE_BYTE_OPCODE
TWO_BYTE_OPCODE
TWO_BYTE_DISJOINT_OPCODE
THREE_NIBBLE_OPCODE
Definition at line 1941 of file constants-s390.h.
                        {
    ONE_BYTE_OPCODE, // One Byte - Bits 0 to 7
    TWO_BYTE_OPCODE, // Two Bytes - Bits 0 to 15
    TWO_BYTE_DISJOINT_OPCODE, // Two Bytes - Bits 0 to 7, 40 to 47
    THREE_NIBBLE_OPCODE // Three Nibbles - Bits 0 to 7, 12 to 15
  };
Member Function Documentation
At() [1/6]
static Instruction* v8::internal::Instruction::At (Address pc) [inline], [static]
Definition at line 657 of file constants-arm.h.
                                     {
    return reinterpret_cast<Instruction*>(pc);
  }
Referenced by v8::internal::WritableRelocInfo::apply(), v8::internal::Decoder< V >::InstructionDecode(), v8::internal::Assembler::relative_code_target_object_handle_at(), v8::internal::Assembler::set_target_address_at(), v8::internal::Assembler::set_target_constant32_at(), v8::internal::Assembler::target_address_at(), v8::internal::Assembler::target_at(), v8::internal::Assembler::target_at_put(), and v8::internal::Assembler::target_constant32_at().
At() [2/6]
static Instruction* v8::internal::Instruction::At (uint8_t * pc) [inline], [static]
Definition at line 923 of file constants-loong64.h.
                                      {
    return reinterpret_cast<Instruction*>(pc);
  }
At() [3/6]
static Instruction* v8::internal::Instruction::At (uint8_t * pc) [inline], [static]
Definition at line 1750 of file constants-mips64.h.
                                      {
    return reinterpret_cast<Instruction*>(pc);
  }
At() [4/6]
static Instruction* v8::internal::Instruction::At (uint8_t * pc) [inline], [static]
Definition at line 3222 of file constants-ppc.h.
                                      {
At() [5/6]
static Instruction* v8::internal::Instruction::At (uint8_t * pc) [inline], [static]
Definition at line 1265 of file base-constants-riscv.h.
                                      {
    return reinterpret_cast<Instruction*>(pc);
  }
At() [6/6]
static Instruction* v8::internal::Instruction::At (uint8_t * pc) [inline], [static]
Definition at line 2178 of file constants-s390.h.
                                      {
    return reinterpret_cast<Instruction*>(pc);
  }
Bit() [1/6]
static int v8::internal::Instruction::Bit (Instr instr, int nr) [inline], [static]
Definition at line 3033 of file constants-ppc.h.
{ return (instr >> nr) & 1; }
Bit() [2/6]
static int v8::internal::Instruction::Bit (Instr instr, int nr) [inline], [static]
Definition at line 2002 of file constants-s390.h.
{ return (instr >> nr) & 1; }
Bit() [3/6]
int v8::internal::Instruction::Bit (int nr) const [inline]
Definition at line 478 of file constants-arm.h.
{ return (InstructionBits() >> nr) & 1; }
References InstructionBits().
Referenced by BValue(), v8::internal::Decoder< V >::DecodeAddSubImmediate(), v8::internal::Decoder< V >::DecodeBitfieldExtract(), v8::internal::Decoder< V >::DecodeBranchSystemException(), v8::internal::Decoder< V >::DecodeDataProcessing(), v8::internal::Decoder< V >::DecodeFP(), v8::internal::Decoder< V >::DecodeLoadStore(), v8::internal::Decoder< V >::DecodeLogical(), v8::internal::Decoder< V >::DecodeNEONLoadStore(), v8::internal::Decoder< V >::DecodeNEONScalarDataProcessing(), v8::internal::Decoder< V >::DecodeNEONVectorDataProcessing(), v8::internal::Decoder< V >::DecodePCRelAddressing(), DValue(), HValue(), IsBranch(), IsMiscType0(), IsSpecialType0(), IsStop(), LinkValue(), LValue(), MValue(), NValue(), Opc1Value(), PValue(), RegShiftValue(), SignValue(), SValue(), SzValue(), UValue(), VCValue(), VFPGlueRegValue(), VLValue(), and WValue().
Bit() [4/6]
int v8::internal::Instruction::Bit (int nr) const [inline]
Definition at line 3018 of file constants-ppc.h.
{ return (InstructionBits() >> nr) & 1; }
References InstructionBits().
Bit() [5/6]
int v8::internal::Instruction::Bit (int nr) const [inline]
Definition at line 1971 of file constants-s390.h.
{ return (InstructionBits() >> nr) & 1; }
References InstructionBits().
Bit() [6/6]
int v8::internal::Instruction::Bit (int pos) const [inline]
Definition at line 95 of file instructions-arm64.h.
{ return (InstructionBits() >> pos) & 1; }
References InstructionBits().
BitField() [1/5]
static uint32_t v8::internal::Instruction::BitField (Instr instr, int hi, int lo) [inline], [static]
Definition at line 3041 of file constants-ppc.h.
                                                               {
References v8::internal::hi, and v8::internal::lo.
BitField() [2/5]
static int v8::internal::Instruction::BitField (Instr instr, int hi, int lo) [inline], [static]
Definition at line 2010 of file constants-s390.h.
                                                          {
    return instr & (((2 << (hi - lo)) - 1) << lo);
  }
References v8::internal::hi, and v8::internal::lo.
BitField() [3/5]
int v8::internal::Instruction::BitField (int hi, int lo) const [inline]
Definition at line 487 of file constants-arm.h.
                                            {
    return InstructionBits() & (((2 << (hi - lo)) - 1) << lo);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Referenced by ConditionField(), OpcodeBase(), OpcodeField(), PUField(), and ShiftField().
BitField() [4/5]
uint32_t v8::internal::Instruction::BitField (int hi, int lo) const [inline]
Definition at line 3026 of file constants-ppc.h.
                                                 {
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
BitField() [5/5]
int v8::internal::Instruction::BitField (int hi, int lo) const [inline]
Definition at line 1985 of file constants-s390.h.
                                            {
    return InstructionBits() & (((2 << (hi - lo)) - 1) << lo);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Bits() [1/7]
static int v8::internal::Instruction::Bits (Instr instr, int hi, int lo) [inline], [static]
Definition at line 3036 of file constants-ppc.h.
                                                      {
References v8::internal::hi, and v8::internal::lo.
Bits() [2/7]
static int v8::internal::Instruction::Bits (Instr instr, int hi, int lo) [inline], [static]
Definition at line 2005 of file constants-s390.h.
                                                      {
    return (instr >> lo) & ((2 << (hi - lo)) - 1);
  }
References v8::internal::hi, and v8::internal::lo.
Bits() [3/7]
int v8::internal::Instruction::Bits (int hi, int lo) const [inline]
Definition at line 482 of file constants-arm.h.
                                        {
    return (InstructionBits() >> lo) & ((2 << (hi - lo)) - 1);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Referenced by ConditionValue(), CoprocessorValue(), v8::internal::Decoder< V >::Decode(), v8::internal::Decoder< V >::DecodeAddSubImmediate(), v8::internal::Decoder< V >::DecodeBitfieldExtract(), v8::internal::Decoder< V >::DecodeBranchSystemException(), v8::internal::Decoder< V >::DecodeDataProcessing(), v8::internal::Decoder< V >::DecodeFP(), v8::internal::Decoder< V >::DecodeLoadStore(), v8::internal::Decoder< V >::DecodeLogical(), v8::internal::Decoder< V >::DecodeNEONLoadStore(), v8::internal::Decoder< V >::DecodeNEONScalarDataProcessing(), v8::internal::Decoder< V >::DecodeNEONVectorDataProcessing(), v8::internal::Decoder< V >::DecodePCRelAddressing(), Immed4Value(), Immed8Value(), ImmedHValue(), ImmedLValue(), IsNopLikeType1(), Offset12Value(), Opc1Value(), Opc2Value(), Opc3Value(), OpcodeField(), OpcodeValue(), PUValue(), RAValue(), RBValue(), RCValue(), RdValue(), RlistValue(), RmValue(), RnValue(), RotateValue(), RsValue(), RtValue(), ShiftAmountValue(), ShiftValue(), SpecialValue(), SvcValue(), TypeValue(), VAValue(), VBValue(), VdValue(), VFPGlueRegValue(), VmValue(), and VnValue().
Bits() [4/7]
int v8::internal::Instruction::Bits (int hi, int lo) const [inline]
Definition at line 3021 of file constants-ppc.h.
                                        {
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Bits() [5/7]
int v8::internal::Instruction::Bits (int hi, int lo) const [inline]
Definition at line 1974 of file constants-s390.h.
                                        {
    return (InstructionBits() >> lo) & ((2 << (hi - lo)) - 1);
  }
References v8::internal::hi, InstructionBits(), and v8::internal::lo.
Bits() [6/7]
template<typename T , typename U >
U v8::internal::Instruction::Bits (int hi, int lo) const [inline]
Definition at line 1980 of file constants-s390.h.
                                      {
    return (InstructionBits<T>() >> lo) & ((2 << (hi - lo)) - 1);
  }
References v8::internal::hi, and v8::internal::lo.
Bits() [7/7]
uint32_t v8::internal::Instruction::Bits (int msb, int lsb) const [inline]
Definition at line 97 of file instructions-arm64.h.
                                        {
    return unsigned_bitextract_32(msb, lsb, InstructionBits());
  }
References InstructionBits(), and v8::internal::unsigned_bitextract_32().
BranchType()
ImmBranchType v8::internal::Instruction::BranchType () const [inline]
Definition at line 297 of file instructions-arm64.h.
                                   {
    if (IsCondBranchImm()) {
      return CondBranchType;
    } else if (IsUncondBranchImm()) {
      return UncondBranchType;
    } else if (IsCompareBranch()) {
      return CompareBranchType;
    } else if (IsTestBranch()) {
      return TestBranchType;
    } else {
      return UnknownBranchType;
    }
  }
References v8::internal::CompareBranchType, v8::internal::CondBranchType, IsCompareBranch(), IsCondBranchImm(), IsTestBranch(), IsUncondBranchImm(), v8::internal::TestBranchType, v8::internal::UncondBranchType, and v8::internal::UnknownBranchType.
Referenced by ImmBranch(), and IsImmBranch().
BValue()
int v8::internal::Instruction::BValue () const [inline]
Definition at line 579 of file constants-arm.h.
{ return Bit(22); }
References Bit().
Referenced by HasB().
Cast()
template<typename T >
static Instruction* v8::internal::Instruction::Cast (T src) [inline], [static]
Definition at line 458 of file instructions-arm64.h.
                                            {
    return reinterpret_cast<Instruction*>(src);
  }
Referenced by v8::internal::Assembler::pc().
ConditionField()
Condition v8::internal::Instruction::ConditionField () const [inline]
Definition at line 505 of file constants-arm.h.
                                          {
    return static_cast<Condition>(BitField(31, 28));
  }
References BitField().
ConditionValue()
int v8::internal::Instruction::ConditionValue () const [inline]
Definition at line 504 of file constants-arm.h.
{ return Bits(31, 28); }
References Bits().
CoprocessorValue()
int v8::internal::Instruction::CoprocessorValue () const [inline]
Definition at line 519 of file constants-arm.h.
{ return Bits(11, 8); }
References Bits().
DISALLOW_IMPLICIT_CONSTRUCTORS() [1/6]
v8::internal::Instruction::DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction) [private]
DISALLOW_IMPLICIT_CONSTRUCTORS() [2/6]
v8::internal::Instruction::DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction) [private]
DISALLOW_IMPLICIT_CONSTRUCTORS() [3/6]
v8::internal::Instruction::DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction) [private]
DISALLOW_IMPLICIT_CONSTRUCTORS() [4/6]
v8::internal::Instruction::DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction) [private]
DISALLOW_IMPLICIT_CONSTRUCTORS() [5/6]
v8::internal::Instruction::DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction) [private]
DISALLOW_IMPLICIT_CONSTRUCTORS() [6/6]
v8::internal::Instruction::DISALLOW_IMPLICIT_CONSTRUCTORS (Instruction) [private]
DistanceTo()
ptrdiff_t v8::internal::Instruction::DistanceTo (Instruction * target) [inline]
Definition at line 462 of file instructions-arm64.h.
                                                      {
    return reinterpret_cast<Address>(target) - reinterpret_cast<Address>(this);
  }
Referenced by SetBranchImmTarget().
DoubleImmedVmov()
Float64 v8::internal::Instruction::DoubleImmedVmov () const
DValue()
int v8::internal::Instruction::DValue () const [inline]
Definition at line 527 of file constants-arm.h.
{ return Bit(22); }
References Bit().
following() [1/2]
Instruction* v8::internal::Instruction::following (int count = 1) [inline]
Definition at line 114 of file instructions-arm64.h.
                                                  {
    return InstructionAtOffset(count * static_cast<int>(kInstrSize));
  }
References InstructionAtOffset(), and v8::internal::kInstrSize.
following() [2/2]
const Instruction* v8::internal::Instruction::following (int count = 1) const [inline]
Definition at line 110 of file instructions-arm64.h.
                                                              {
    return InstructionAtOffset(count * static_cast<int>(kInstrSize));
  }
References InstructionAtOffset(), and v8::internal::kInstrSize.
Referenced by ImmUnresolvedInternalReference(), IsUnresolvedInternalReference(), and preceding().
GetBranchOffset()
int v8::internal::Instruction::GetBranchOffset () [inline]
Definition at line 601 of file constants-arm.h.
                        {
    DCHECK(IsBranch());
    return SImmed24Value() * kInstrSize;
  }
References v8::internal::DCHECK(), IsBranch(), v8::internal::kInstrSize, and SImmed24Value().
Referenced by v8::internal::WritableRelocInfo::apply(), v8::internal::Assembler::relative_code_target_object_handle_at(), and v8::internal::Assembler::target_address_at().
getOpcodeFormatType()
static OpcodeFormatType v8::internal::Instruction::getOpcodeFormatType (const uint8_t * instr) [inline], [static]
Definition at line 2138 of file constants-s390.h.
                                                                    {
    const uint8_t firstByte = *instr;
    return OpcodeFormatTable[firstByte];
  }
References OpcodeFormatTable.
Referenced by S390OpcodeValue().
HasB()
bool v8::internal::Instruction::HasB () const [inline]
Definition at line 642 of file constants-arm.h.
{ return BValue() == 1; }
References BValue().
HasH()
bool v8::internal::Instruction::HasH () const [inline]
Definition at line 647 of file constants-arm.h.
{ return HValue() == 1; }
References HValue().
HasL()
bool v8::internal::Instruction::HasL () const [inline]
Definition at line 644 of file constants-arm.h.
{ return LValue() == 1; }
References LValue().
HasLink()
bool v8::internal::Instruction::HasLink () const [inline]
Definition at line 648 of file constants-arm.h.
{ return LinkValue() == 1; }
References LinkValue().
HasS()
bool v8::internal::Instruction::HasS () const [inline]
Definition at line 641 of file constants-arm.h.
{ return SValue() == 1; }
References SValue().
HasSign()
bool v8::internal::Instruction::HasSign () const [inline]
Definition at line 646 of file constants-arm.h.
{ return SignValue() == 1; }
References SignValue().
HasU()
bool v8::internal::Instruction::HasU () const [inline]
Definition at line 645 of file constants-arm.h.
{ return UValue() == 1; }
References UValue().
HasW()
bool v8::internal::Instruction::HasW () const [inline]
Definition at line 643 of file constants-arm.h.
{ return WValue() == 1; }
References WValue().
HValue()
int v8::internal::Instruction::HValue () const [inline]
Definition at line 589 of file constants-arm.h.
{ return Bit(5); }
References Bit().
Referenced by HasH().
Imm8ToFP32()
static float v8::internal::Instruction::Imm8ToFP32 (uint32_t imm8) [inline], [static]
Definition at line 180 of file instructions-arm64.h.
                                         {
    // Imm8: abcdefgh (8 bits)
    // Single: aBbb.bbbc.defg.h000.0000.0000.0000.0000 (32 bits)
    // where B is b ^ 1
    uint32_t bits = imm8;
    uint32_t bit7 = (bits >> 7) & 0x1;
    uint32_t bit6 = (bits >> 6) & 0x1;
    uint32_t bit5_to_0 = bits & 0x3f;
    uint32_t result = (bit7 << 31) | ((32 - bit6) << 25) | (bit5_to_0 << 19);
    return base::bit_cast<float>(result);
  }
References v8::base::internal::result.
Imm8ToFP64()
static double v8::internal::Instruction::Imm8ToFP64 (uint32_t imm8) [inline], [static]
Definition at line 193 of file instructions-arm64.h.
                                          {
    // Imm8: abcdefgh (8 bits)
    // Double: aBbb.bbbb.bbcd.efgh.0000.0000.0000.0000
    // 0000.0000.0000.0000.0000.0000.0000.0000 (64 bits)
    // where B is b ^ 1
    uint32_t bits = imm8;
    uint64_t bit7 = (bits >> 7) & 0x1;
    uint64_t bit6 = (bits >> 6) & 0x1;
    uint64_t bit5_to_0 = bits & 0x3f;
    uint64_t result = (bit7 << 63) | ((256 - bit6) << 54) | (bit5_to_0 << 48);
    return base::bit_cast<double>(result);
  }
References v8::base::internal::result.
ImmBranch()
int v8::internal::Instruction::ImmBranch () const [inline]
Definition at line 332 of file instructions-arm64.h.
                        {
    switch (BranchType()) {
      case CondBranchType:
        return ImmCondBranch();
      case UncondBranchType:
        return ImmUncondBranch();
      case CompareBranchType:
        return ImmCmpBranch();
      case TestBranchType:
        return ImmTestBranch();
      default:
        UNREACHABLE();
    }
    return 0;
  }
References BranchType(), v8::internal::CompareBranchType, v8::internal::CondBranchType, v8::internal::TestBranchType, v8::internal::UncondBranchType, and v8::internal::UNREACHABLE().
ImmBranchRange()
static constexpr int32_t v8::internal::Instruction::ImmBranchRange (ImmBranchType branch_type) [inline], [static], [constexpr]
Definition at line 327 of file instructions-arm64.h.
                                                                     {
    return (1 << (ImmBranchRangeBitwidth(branch_type) + kInstrSizeLog2)) / 2 -
           kInstrSize;
  }
References ImmBranchRangeBitwidth(), v8::internal::kInstrSize, and v8::internal::kInstrSizeLog2.
Referenced by v8::internal::MacroAssembler::NeedExtraInstructionsOrRegisterBranch().
ImmBranchRangeBitwidth()
static constexpr int v8::internal::Instruction::ImmBranchRangeBitwidth (ImmBranchType branch_type) [inline], [static], [constexpr]
Definition at line 311 of file instructions-arm64.h.
                                                                         {
    switch (branch_type) {
      case UncondBranchType:
        return ImmUncondBranch_width;
      case CondBranchType:
        return ImmCondBranch_width;
      case CompareBranchType:
        return ImmCmpBranch_width;
      case TestBranchType:
        return ImmTestBranch_width;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::CompareBranchType, v8::internal::CondBranchType, v8::internal::TestBranchType, v8::internal::UncondBranchType, and v8::internal::UNREACHABLE().
Referenced by ImmBranchRange(), and IsValidImmPCOffset().
Immed4Value()
int v8::internal::Instruction::Immed4Value () const [inline]
Definition at line 570 of file constants-arm.h.
{ return Bits(19, 16); }
References Bits().
Referenced by ImmedMovwMovtValue().
Immed8Value()
int v8::internal::Instruction::Immed8Value () const [inline]
Definition at line 568 of file constants-arm.h.
{ return Bits(7, 0); }
References Bits().
ImmedHValue()
int v8::internal::Instruction::ImmedHValue () const [inline]
Definition at line 590 of file constants-arm.h.
{ return Bits(11, 8); }
References Bits().
ImmedLValue()
int v8::internal::Instruction::ImmedLValue () const [inline]
Definition at line 591 of file constants-arm.h.
{ return Bits(3, 0); }
References Bits().
ImmedMovwMovtValue()
int v8::internal::Instruction::ImmedMovwMovtValue () const [inline]
Definition at line 571 of file constants-arm.h.
                                        {
    return Immed4Value() << 12 | Offset12Value();
  }
References Immed4Value(), and Offset12Value().
Referenced by v8::internal::Assembler::target_address_at().
ImmFP32()
float v8::internal::Instruction::ImmFP32 ()
ImmFP64()
double v8::internal::Instruction::ImmFP64 ()
ImmLogical()
uint64_t v8::internal::Instruction::ImmLogical ()
ImmNEONabcdefgh()
unsigned v8::internal::Instruction::ImmNEONabcdefgh () const
ImmNEONFP32()
float v8::internal::Instruction::ImmNEONFP32 () const
ImmNEONFP64()
double v8::internal::Instruction::ImmNEONFP64 () const
ImmPCOffset()
V8_EXPORT_PRIVATE int64_t v8::internal::Instruction::ImmPCOffset ()
Referenced by v8::internal::Assembler::code_target_object_handle_at(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), and v8::internal::Assembler::target_builtin_at().
ImmPCOffsetTarget()
V8_EXPORT_PRIVATE Instruction* v8::internal::Instruction::ImmPCOffsetTarget ()
Referenced by v8::internal::Assembler::target_pointer_address_at().
ImmPCRel()
int v8::internal::Instruction::ImmPCRel () const [inline]
Definition at line 131 of file instructions-arm64.h.
                       {
    DCHECK(IsPCRelAddressing());
    int offset = (static_cast<uint32_t>(ImmPCRelHi()) << ImmPCRelLo_width) |
                 ImmPCRelLo();
    int width = ImmPCRelLo_width + ImmPCRelHi_width;
    return signed_bitextract_32(width - 1, 0, offset);
  }
References v8::internal::DCHECK(), IsPCRelAddressing(), and v8::internal::signed_bitextract_32().
ImmUnresolvedInternalReference()
int v8::internal::Instruction::ImmUnresolvedInternalReference () const [inline]
Definition at line 348 of file instructions-arm64.h.
                                             {
    DCHECK(IsUnresolvedInternalReference());
    // Unresolved references are encoded as two consecutive brk instructions.
    // The associated immediate is made of the two 16-bit payloads.
    int32_t high16 = ImmException();
    int32_t low16 = following()->ImmException();
    return (high16 << 16) | low16;
  }
References v8::internal::DCHECK(), following(), and IsUnresolvedInternalReference().
InstructionAtOffset() [1/2]
Instruction* v8::internal::Instruction::InstructionAtOffset (int64_t offset, CheckAlignment check = CHECK_ALIGNMENT) [inline]
Definition at line 450 of file instructions-arm64.h.
                                                              {
    // The FUZZ_disasm test relies on no check being done.
    DCHECK(check == NO_CHECK || IsAligned(offset, kInstrSize));
    return this + offset;
  }
References v8::internal::DCHECK(), IsAligned(), v8::internal::kInstrSize, and NO_CHECK.
InstructionAtOffset() [2/2]
const Instruction* v8::internal::Instruction::InstructionAtOffset (int64_t offset, CheckAlignment check = CHECK_ALIGNMENT) const [inline]
Definition at line 443 of file instructions-arm64.h.
                                                                    {
    // The FUZZ_disasm test relies on no check being done.
    DCHECK(check == NO_CHECK || IsAligned(offset, kInstrSize));
    return this + offset;
  }
References v8::internal::DCHECK(), IsAligned(), v8::internal::kInstrSize, and NO_CHECK.
Referenced by following().
InstructionBits() [1/7]
Instr v8::internal::Instruction::InstructionBits () const [inline]
Definition at line 468 of file constants-arm.h.
                                       {
    return *reinterpret_cast<const Instr*>(this);
  }
Referenced by Bit(), BitField(), Bits(), v8::internal::Decoder< V >::DecodeBType(), v8::internal::Decoder< V >::DecodeCAType(), v8::internal::Decoder< V >::DecodeIType(), v8::internal::Decoder< V >::DecodeR4Type(), v8::internal::Decoder< V >::DecodeRAType(), v8::internal::Decoder< V >::DecodeRFPType(), v8::internal::Decoder< V >::DecodeRType(), v8::internal::Decoder< V >::DecodeRvvFVF(), v8::internal::Decoder< V >::DecodeRvvFVV(), v8::internal::Decoder< V >::DecodeRvvIVI(), v8::internal::Decoder< V >::DecodeRvvIVV(), v8::internal::Decoder< V >::DecodeRvvIVX(), v8::internal::Decoder< V >::DecodeRvvMVV(), v8::internal::Decoder< V >::DecodeRvvMVX(), v8::internal::Decoder< V >::DecodeRvvVL(), v8::internal::Decoder< V >::DecodeRvvVS(), v8::internal::Decoder< V >::DecodeSType(), v8::internal::Decoder< V >::DecodeVType(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::Assembler::instr_at(), v8::internal::Decoder< V >::InstructionDecode(), Mask(), v8::internal::Decoder< V >::PrintTarget(), v8::internal::Assembler::set_target_constant32_at(), SetBranchOffset(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), SImmed24Value(), v8::internal::Decoder< V >::switch_nf(), v8::internal::Decoder< V >::switch_sew(), v8::internal::Assembler::target_at(), and v8::internal::Assembler::target_at_put().
InstructionBits() [2/7]
Instr v8::internal::Instruction::InstructionBits () const [inline]
Definition at line 87 of file instructions-arm64.h.
                                          {
    // Usually this is aligned, but when de/serializing that's not guaranteed.
    return base::ReadUnalignedValue<Instr>(reinterpret_cast<Address>(this));
  }
InstructionBits() [3/7]
Instr v8::internal::Instruction::InstructionBits () const [inline]
Definition at line 3009 of file constants-ppc.h.
                                       {
InstructionBits() [4/7]
template<typename T >
T v8::internal::Instruction::InstructionBits () const [inline]
Definition at line 1952 of file constants-s390.h.
                                   {
    return Instruction::InstructionBits<T>(
        reinterpret_cast<const uint8_t*>(this));
  }
InstructionBits() [5/7]
Instr v8::internal::Instruction::InstructionBits () const [inline]
Definition at line 1956 of file constants-s390.h.
                                       {
    return *reinterpret_cast<const Instr*>(this);
  }
InstructionBits() [6/7]
static uint64_t v8::internal::Instruction::InstructionBits (const uint8_t * instr) [inline], [static]
Definition at line 2029 of file constants-s390.h.
                                                               {
    int length = InstructionLength(instr);
    if (2 == length)
      return static_cast<uint64_t>(InstructionBits<TwoByteInstr>(instr));
    else if (4 == length)
      return static_cast<uint64_t>(InstructionBits<FourByteInstr>(instr));
    else
      return InstructionBits<SixByteInstr>(instr);
  }
References InstructionLength(), and v8::internal::length.
InstructionBits() [7/7]
template<typename T >
static T v8::internal::Instruction::InstructionBits (const uint8_t * instr) [inline], [static]
Definition at line 2041 of file constants-s390.h.
                                                        {
#if !V8_TARGET_LITTLE_ENDIAN
    if (sizeof(T) <= 4) {
      return *reinterpret_cast<const T*>(instr);
    } else {
      // We cannot read 8-byte instructon address directly, because for a
      // six-byte instruction, the extra 2-byte address might not be
      // allocated.
      uint64_t fourBytes = *reinterpret_cast<const uint32_t*>(instr);
      uint16_t twoBytes = *reinterpret_cast<const uint16_t*>(instr + 4);
      return (fourBytes << 16 | twoBytes);
    }
#else
    // Even on little endian hosts (simulation), the instructions
    // are stored as big-endian in order to decode the opcode and
    // instruction length.
    T instr_bits = 0;
    // 6-byte instrs are represented by uint64_t
    uint32_t size = (sizeof(T) == 8) ? 6 : sizeof(T);
    for (T i = 0; i < size; i++) {
      instr_bits <<= 8;
      instr_bits |= *(instr + i);
    }
    return instr_bits;
#endif
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, size(), and T.
InstructionLength() [1/2]
int v8::internal::Instruction::InstructionLength () [inline]
Definition at line 1990 of file constants-s390.h.
                                 {
    return Instruction::InstructionLength(
        reinterpret_cast<const uint8_t*>(this));
  }
Referenced by v8::internal::Assembler::instr_length_at(), and InstructionBits().
InstructionLength() [2/2]
static int v8::internal::Instruction::InstructionLength (const uint8_t * instr) [inline], [static]
Definition at line 2015 of file constants-s390.h.
                                                            {
    // Length can be determined by the first nibble.
    // 0x0 to 0x3 => 2-bytes
    // 0x4 to 0xB => 4-bytes
    // 0xC to 0xF => 6-bytes
    uint8_t topNibble = (*instr >> 4) & 0xF;
    if (topNibble <= 3)
      return 2;
    else if (topNibble <= 0xB)
      return 4;
    return 6;
  }
IsAddSubExtended()
bool v8::internal::Instruction::IsAddSubExtended () const [inline]
Definition at line 240 of file instructions-arm64.h.
                                {
    return Mask(AddSubExtendedFMask) == AddSubExtendedFixed;
  }
References v8::internal::AddSubExtendedFixed, v8::internal::AddSubExtendedFMask, and Mask().
Referenced by RdMode(), and RnMode().
IsAddSubImmediate()
bool v8::internal::Instruction::IsAddSubImmediate () const [inline]
Definition at line 232 of file instructions-arm64.h.
                                 {
    return Mask(AddSubImmediateFMask) == AddSubImmediateFixed;
  }
References v8::internal::AddSubImmediateFixed, v8::internal::AddSubImmediateFMask, and Mask().
Referenced by RdMode(), and RnMode().
IsAddSubShifted()
bool v8::internal::Instruction::IsAddSubShifted () const [inline]
Definition at line 236 of file instructions-arm64.h.
                               {
    return Mask(AddSubShiftedFMask) == AddSubShiftedFixed;
  }
References v8::internal::AddSubShiftedFixed, v8::internal::AddSubShiftedFMask, and Mask().
IsAdr()
bool v8::internal::Instruction::IsAdr () const [inline]
Definition at line 218 of file instructions-arm64.h.
{ return Mask(PCRelAddressingMask) == ADR; }
References v8::internal::ADR, Mask(), and v8::internal::PCRelAddressingMask.
IsBranch()
bool v8::internal::Instruction::IsBranch () [inline]
Definition at line 599 of file constants-arm.h.
{ return Bit(27) == 1 && Bit(25) == 1; }
References Bit().
Referenced by GetBranchOffset(), and SetBranchOffset().
IsBranchAndLink()
bool v8::internal::Instruction::IsBranchAndLink () const [inline]
Definition at line 361 of file instructions-arm64.h.
{ return Mask(UnconditionalBranchMask) == BL; }
References v8::internal::BL, Mask(), and v8::internal::UnconditionalBranchMask.
Referenced by v8::internal::Assembler::code_target_object_handle_at(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and v8::internal::Assembler::target_builtin_at().
IsBranchAndLinkToRegister()
bool v8::internal::Instruction::IsBranchAndLinkToRegister () const [inline]
Definition at line 363 of file instructions-arm64.h.
                                         {
    return Mask(UnconditionalBranchToRegisterMask) == BLR;
  }
References v8::internal::BLR, Mask(), and v8::internal::UnconditionalBranchToRegisterMask.
IsBrk()
bool v8::internal::Instruction::IsBrk () const [inline]
Definition at line 220 of file instructions-arm64.h.
{ return Mask(ExceptionMask) == BRK; }
References v8::internal::BRK, v8::internal::ExceptionMask, and Mask().
Referenced by IsUnresolvedInternalReference().
IsBti()
bool v8::internal::Instruction::IsBti () const [inline]
Definition at line 386 of file instructions-arm64.h.
                     {
    if (Mask(SystemHintFMask) == SystemHintFixed) {
      int imm_hint = ImmHint();
      switch (imm_hint) {
        case BTI:
        case BTI_c:
        case BTI_j:
        case BTI_jc:
          return true;
      }
    }
    return false;
  }
References v8::internal::BTI, v8::internal::BTI_c, v8::internal::BTI_j, v8::internal::BTI_jc, Mask(), v8::internal::SystemHintFixed, and v8::internal::SystemHintFMask.
IsCompareBranch()
bool v8::internal::Instruction::IsCompareBranch () const [inline]
Definition at line 172 of file instructions-arm64.h.
                               {
    return Mask(CompareBranchFMask) == CompareBranchFixed;
  }
References v8::internal::CompareBranchFixed, v8::internal::CompareBranchFMask, and Mask().
Referenced by BranchType().
IsCondBranchImm()
bool v8::internal::Instruction::IsCondBranchImm () const [inline]
Definition at line 164 of file instructions-arm64.h.
                               {
    return Mask(ConditionalBranchFMask) == ConditionalBranchFixed;
  }
References v8::internal::ConditionalBranchFixed, v8::internal::ConditionalBranchFMask, and Mask().
Referenced by BranchType().
IsException()
bool v8::internal::Instruction::IsException () const [inline]
Definition at line 382 of file instructions-arm64.h.
{ return Mask(ExceptionFMask) == ExceptionFixed; }
References v8::internal::ExceptionFixed, v8::internal::ExceptionFMask, and Mask().
IsImmBranch()
bool v8::internal::Instruction::IsImmBranch () const [inline]
Definition at line 178 of file instructions-arm64.h.
{ return BranchType() != UnknownBranchType; }
References BranchType(), and v8::internal::UnknownBranchType.
IsLdrLiteral()
bool v8::internal::Instruction::IsLdrLiteral () const [inline]
Definition at line 207 of file instructions-arm64.h.
                            {
    return Mask(LoadLiteralFMask) == LoadLiteralFixed;
  }
References v8::internal::LoadLiteralFixed, v8::internal::LoadLiteralFMask, and Mask().
IsLdrLiteralW()
bool v8::internal::Instruction::IsLdrLiteralW () const [inline]
Definition at line 212 of file instructions-arm64.h.
{ return Mask(LoadLiteralMask) == LDR_w_lit; }
References v8::internal::LDR_w_lit, v8::internal::LoadLiteralMask, and Mask().
Referenced by v8::internal::Assembler::embedded_object_index_referenced_from(), v8::internal::Assembler::set_embedded_object_index_referenced_from(), v8::internal::Assembler::set_target_compressed_address_at(), v8::internal::Assembler::target_compressed_address_at(), and v8::internal::Assembler::target_pointer_address_at().
IsLdrLiteralX()
bool v8::internal::Instruction::IsLdrLiteralX () const [inline]
Definition at line 211 of file instructions-arm64.h.
{ return Mask(LoadLiteralMask) == LDR_x_lit; }
References v8::internal::LDR_x_lit, v8::internal::LoadLiteralMask, and Mask().
Referenced by v8::internal::Assembler::code_target_object_handle_at(), v8::internal::Assembler::embedded_object_index_referenced_from(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::Assembler::set_embedded_object_index_referenced_from(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and v8::internal::Assembler::target_pointer_address_at().
IsLoad()
bool v8::internal::Instruction::IsLoad () const
Referenced by v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction().
IsLoadOrStore()
bool v8::internal::Instruction::IsLoadOrStore () const [inline]
Definition at line 245 of file instructions-arm64.h.
                             {
    return Mask(LoadStoreAnyFMask) == LoadStoreAnyFixed;
  }
References v8::internal::LoadStoreAnyFixed, v8::internal::LoadStoreAnyFMask, and Mask().
Referenced by RnMode().
IsLogicalImmediate()
bool v8::internal::Instruction::IsLogicalImmediate () const [inline]
Definition at line 228 of file instructions-arm64.h.
                                  {
    return Mask(LogicalImmediateFMask) == LogicalImmediateFixed;
  }
References v8::internal::LogicalImmediateFixed, v8::internal::LogicalImmediateFMask, and Mask().
Referenced by RdMode().
IsMiscType0()
bool v8::internal::Instruction::IsMiscType0 () const [inline]
Definition at line 627 of file constants-arm.h.
                                  {
    return (Bit(24) == 1) && (Bit(23) == 0) && (Bit(20) == 0) &&
           ((Bit(7) == 0));
  }
References Bit().
IsMovk()
bool v8::internal::Instruction::IsMovk () const [inline]
Definition at line 372 of file instructions-arm64.h.
                      {
    return (Mask(MoveWideImmediateMask) == MOVK_x) ||
           (Mask(MoveWideImmediateMask) == MOVK_w);
  }
References Mask(), v8::internal::MoveWideImmediateMask, v8::internal::MOVK_w, and v8::internal::MOVK_x.
IsMovn()
bool v8::internal::Instruction::IsMovn () const [inline]
Definition at line 377 of file instructions-arm64.h.
                      {
    return (Mask(MoveWideImmediateMask) == MOVN_x) ||
           (Mask(MoveWideImmediateMask) == MOVN_w);
  }
References Mask(), v8::internal::MoveWideImmediateMask, v8::internal::MOVN_w, and v8::internal::MOVN_x.
IsMovz()
bool v8::internal::Instruction::IsMovz () const [inline]
Definition at line 367 of file instructions-arm64.h.
                      {
    return (Mask(MoveWideImmediateMask) == MOVZ_x) ||
           (Mask(MoveWideImmediateMask) == MOVZ_w);
  }
References Mask(), v8::internal::MoveWideImmediateMask, v8::internal::MOVZ_w, and v8::internal::MOVZ_x.
IsNop()
bool v8::internal::Instruction::IsNop (int n) [inline]
Definition at line 400 of file instructions-arm64.h.
                    {
    // A marking nop is an instruction
    // mov r<n>, r<n>
    // which is encoded as
    // orr r<n>, xzr, r<n>
    return (Mask(LogicalShiftedMask) == ORR_x) && (Rd() == Rm()) && (Rd() == n);
  }
References v8::internal::LogicalShiftedMask, Mask(), and v8::internal::ORR_x.
IsNopLikeType1()
bool v8::internal::Instruction::IsNopLikeType1 () const [inline]
Definition at line 633 of file constants-arm.h.
{ return Bits(24, 8) == 0x120F0; }
References Bits().
IsPAuth()
bool v8::internal::Instruction::IsPAuth () const [inline]
Definition at line 384 of file instructions-arm64.h.
{ return Mask(SystemPAuthFMask) == SystemPAuthFixed; }
References Mask(), v8::internal::SystemPAuthFixed, and v8::internal::SystemPAuthFMask.
IsPCRelAddressing()
bool v8::internal::Instruction::IsPCRelAddressing () const [inline]
Definition at line 214 of file instructions-arm64.h.
                                 {
    return Mask(PCRelAddressingFMask) == PCRelAddressingFixed;
  }
References Mask(), v8::internal::PCRelAddressingFixed, and v8::internal::PCRelAddressingFMask.
Referenced by ImmPCRel().
IsSpecialType0()
bool v8::internal::Instruction::IsSpecialType0 () const [inline]
Definition at line 624 of file constants-arm.h.
{ return (Bit(7) == 1) && (Bit(4) == 1); }
References Bit().
IsStop()
bool v8::internal::Instruction::IsStop () const [inline]
Definition at line 636 of file constants-arm.h.
                             {
    return (TypeValue() == 7) && (Bit(24) == 1) && (SvcValue() >= kStopCode);
  }
References Bit(), v8::internal::kStopCode, SvcValue(), and TypeValue().
IsStore()
bool v8::internal::Instruction::IsStore () const
Referenced by v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction().
IsTargetInImmPCOffsetRange()
bool v8::internal::Instruction::IsTargetInImmPCOffsetRange (Instruction * target)
IsTestBranch()
bool v8::internal::Instruction::IsTestBranch () const [inline]
Definition at line 176 of file instructions-arm64.h.
{ return Mask(TestBranchFMask) == TestBranchFixed; }
References Mask(), v8::internal::TestBranchFixed, and v8::internal::TestBranchFMask.
Referenced by BranchType().
IsUncondBranchImm()
bool v8::internal::Instruction::IsUncondBranchImm () const [inline]
Definition at line 168 of file instructions-arm64.h.
                                 {
    return Mask(UnconditionalBranchFMask) == UnconditionalBranchFixed;
  }
References Mask(), v8::internal::UnconditionalBranchFixed, and v8::internal::UnconditionalBranchFMask.
Referenced by BranchType().
IsUnconditionalBranch()
bool v8::internal::Instruction::IsUnconditionalBranch () const [inline]
Definition at line 357 of file instructions-arm64.h.
                                     {
    return Mask(UnconditionalBranchMask) == B;
  }
References v8::internal::B, Mask(), and v8::internal::UnconditionalBranchMask.
Referenced by v8::internal::Assembler::code_target_object_handle_at(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::GetWasmCalleeTag(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and v8::internal::Assembler::target_builtin_at().
IsUnresolvedInternalReference()
bool v8::internal::Instruction::IsUnresolvedInternalReference () const [inline]
Definition at line 222 of file instructions-arm64.h.
                                             {
    // Unresolved internal references are encoded as two consecutive brk
    // instructions.
    return IsBrk() && following()->IsBrk();
  }
References following(), and IsBrk().
Referenced by ImmUnresolvedInternalReference().
IsValidImmPCOffset()
static constexpr bool v8::internal::Instruction::IsValidImmPCOffset (ImmBranchType branch_type, ptrdiff_t offset) [inline], [static], [constexpr]
Definition at line 419 of file instructions-arm64.h.
                                                             {
    DCHECK_EQ(offset % kInstrSize, 0);
    return is_intn(offset / kInstrSize, ImmBranchRangeBitwidth(branch_type));
  }
References DCHECK_EQ, ImmBranchRangeBitwidth(), v8::internal::is_intn(), and v8::internal::kInstrSize.
Referenced by v8::internal::MacroAssembler::NeedExtraInstructionsOrRegisterBranch(), and SetBranchImmTarget().
IsValidPCRelOffset()
static bool v8::internal::Instruction::IsValidPCRelOffset (ptrdiff_t offset) [inline], [static]
Definition at line 467 of file instructions-arm64.h.
{ return is_int21(offset); }
LinkValue()
int v8::internal::Instruction::LinkValue () const [inline]
Definition at line 594 of file constants-arm.h.
{ return Bit(24); }
References Bit().
Referenced by HasLink().
LiteralAddress()
uintptr_t v8::internal::Instruction::LiteralAddress () [inline]
Definition at line 436 of file instructions-arm64.h.
                             {
    int offset = ImmLLiteral() * kLoadLiteralScale;
    return reinterpret_cast<uintptr_t>(this) + offset;
  }
References v8::internal::kLoadLiteralScale.
LValue()
int v8::internal::Instruction::LValue () const [inline]
Definition at line 581 of file constants-arm.h.
{ return Bit(20); }
References Bit().
Referenced by HasL().
Mask()
Instr v8::internal::Instruction::Mask (uint32_t mask) const [inline]
Definition at line 108 of file instructions-arm64.h.
{ return InstructionBits() & mask; }
References InstructionBits().
Referenced by v8::internal::Decoder< V >::DecodeBitfieldExtract(), v8::internal::Decoder< V >::DecodeBranchSystemException(), v8::internal::Decoder< V >::DecodeDataProcessing(), v8::internal::Decoder< V >::DecodeFP(), v8::internal::Decoder< V >::DecodeLoadStore(), v8::internal::Decoder< V >::DecodeLogical(), IsAddSubExtended(), IsAddSubImmediate(), IsAddSubShifted(), IsAdr(), IsBranchAndLink(), IsBranchAndLinkToRegister(), IsBrk(), IsBti(), IsCompareBranch(), IsCondBranchImm(), IsException(), IsLdrLiteral(), IsLdrLiteralW(), IsLdrLiteralX(), IsLoadOrStore(), IsLogicalImmediate(), IsMovk(), IsMovn(), IsMovz(), IsNop(), IsPAuth(), IsPCRelAddressing(), IsTestBranch(), IsUncondBranchImm(), IsUnconditionalBranch(), RdMode(), SetBranchImmTarget(), SizeLS(), and SizeLSPair().
MValue()
int v8::internal::Instruction::MValue () const [inline]
Definition at line 526 of file constants-arm.h.
{ return Bit(5); }
References Bit().
NEONLSIndex()
int v8::internal::Instruction::NEONLSIndex (int access_size_shift) const [inline]
Definition at line 155 of file instructions-arm64.h.
                                               {
    int q = NEONQ();
    int s = NEONS();
    int size = NEONLSSize();
    int index = (q << 3) | (s << 2) | size;
    return index >> access_size_shift;
  }
References v8::internal::index, and size().
NValue()
int v8::internal::Instruction::NValue () const [inline]
Definition at line 525 of file constants-arm.h.
{ return Bit(7); }
References Bit().
Offset12Value()
int v8::internal::Instruction::Offset12Value () const [inline]
Definition at line 584 of file constants-arm.h.
{ return Bits(11, 0); }
References Bits().
Referenced by ImmedMovwMovtValue().
Opc1Value()
int v8::internal::Instruction::Opc1Value () const [inline]
Definition at line 531 of file constants-arm.h.
{ return (Bit(23) << 2) | Bits(21, 20); }
References Bit(), and Bits().
Opc2Value()
int v8::internal::Instruction::Opc2Value () const [inline]
Definition at line 532 of file constants-arm.h.
{ return Bits(19, 16); }
References Bits().
Opc3Value()
int v8::internal::Instruction::Opc3Value () const [inline]
Definition at line 533 of file constants-arm.h.
{ return Bits(7, 6); }
References Bits().
OpcodeBase()
Opcode v8::internal::Instruction::OpcodeBase () const [inline]
Definition at line 3064 of file constants-ppc.h.
                                                                      :
  inline Opcode OpcodeBase() const {
    uint32_t opcode = PrefixOpcodeField();
    uint32_t extcode = PrefixOpcodeField();
    // Check for prefix.
    switch (opcode) {
      PPC_PREFIX_OPCODE_TYPE_00_LIST(OPCODE_CASES)
      PPC_PREFIX_OPCODE_TYPE_10_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = OpcodeField();
    extcode = OpcodeField();
    // Check for suffix.
    switch (opcode) {
      PPC_PREFIX_OPCODE_TYPE_00_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    switch (opcode) {
      PPC_D_OPCODE_LIST(OPCODE_CASES)
      PPC_I_OPCODE_LIST(OPCODE_CASES)
      PPC_B_OPCODE_LIST(OPCODE_CASES)
      PPC_M_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(5, 0);
    switch (opcode) {
      PPC_VA_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    // Some VX opcodes have integers hard coded in the middle, handle those
    // first.
    opcode = extcode | BitField(20, 16) | BitField(10, 0);
    switch (opcode) {
      PPC_VX_OPCODE_D_FORM_LIST(OPCODE_CASES)
      PPC_VX_OPCODE_F_FORM_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(10, 0);
    switch (opcode) {
      PPC_VX_OPCODE_A_FORM_LIST(OPCODE_CASES)
      PPC_VX_OPCODE_B_FORM_LIST(OPCODE_CASES)
      PPC_VX_OPCODE_C_FORM_LIST(OPCODE_CASES)
      PPC_VX_OPCODE_E_FORM_LIST(OPCODE_CASES)
      PPC_VX_OPCODE_G_FORM_LIST(OPCODE_CASES)
      PPC_VX_OPCODE_UNUSED_LIST(OPCODE_CASES)
      PPC_X_OPCODE_EH_S_FORM_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(9, 0);
    switch (opcode) {
      PPC_VC_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(10, 1) | BitField(20, 20);
    switch (opcode) {
      PPC_XFX_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    // Some XX2 opcodes have integers hard coded in the middle, handle those
    // first.
    opcode = extcode | BitField(20, 16) | BitField(10, 2);
    switch (opcode) {
      PPC_XX2_OPCODE_B_FORM_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(10, 2);
    switch (opcode) {
      PPC_XX2_OPCODE_VECTOR_A_FORM_LIST(OPCODE_CASES)
      PPC_XX2_OPCODE_SCALAR_A_FORM_LIST(OPCODE_CASES)
      PPC_XX2_OPCODE_UNUSED_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(10, 1);
    switch (opcode) {
      PPC_X_OPCODE_LIST(OPCODE_CASES)
      PPC_XL_OPCODE_LIST(OPCODE_CASES)
      PPC_XFL_OPCODE_LIST(OPCODE_CASES)
      PPC_XX1_OPCODE_LIST(OPCODE_CASES)
      PPC_EVX_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(9, 1);
    switch (opcode) {
      PPC_XO_OPCODE_LIST(OPCODE_CASES)
      PPC_Z22_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(10, 2);
    switch (opcode) {
      PPC_XS_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(9, 3);
    switch (opcode) {
      PPC_XX3_OPCODE_VECTOR_A_FORM_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(10, 3);
    switch (opcode) {
      PPC_EVS_OPCODE_LIST(OPCODE_CASES)
      PPC_XX3_OPCODE_VECTOR_B_FORM_LIST(OPCODE_CASES)
      PPC_XX3_OPCODE_SCALAR_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(8, 1);
    switch (opcode) {
      PPC_Z23_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(5, 1);
    switch (opcode) {
      PPC_A_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(4, 1);
    switch (opcode) {
      PPC_MDS_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(4, 2);
    switch (opcode) {
      PPC_MD_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(5, 4);
    switch (opcode) {
      PPC_XX4_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(2, 0);
    switch (opcode) {
      PPC_DQ_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(1, 0);
    switch (opcode) {
      PPC_DS_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    opcode = extcode | BitField(1, 1);
    switch (opcode) {
      PPC_SC_OPCODE_LIST(OPCODE_CASES)
      return static_cast<Opcode>(opcode);
    }
    UNIMPLEMENTED();
References BitField(), OPCODE_CASES, OpcodeField(), PPC_A_OPCODE_LIST, PPC_B_OPCODE_LIST, PPC_D_OPCODE_LIST, PPC_DQ_OPCODE_LIST, PPC_DS_OPCODE_LIST, PPC_EVS_OPCODE_LIST, PPC_EVX_OPCODE_LIST, PPC_I_OPCODE_LIST, PPC_M_OPCODE_LIST, PPC_MD_OPCODE_LIST, PPC_MDS_OPCODE_LIST, PPC_PREFIX_OPCODE_TYPE_00_LIST, PPC_PREFIX_OPCODE_TYPE_10_LIST, PPC_SC_OPCODE_LIST, PPC_VA_OPCODE_LIST, PPC_VC_OPCODE_LIST, PPC_VX_OPCODE_A_FORM_LIST, PPC_VX_OPCODE_B_FORM_LIST, PPC_VX_OPCODE_C_FORM_LIST, PPC_VX_OPCODE_D_FORM_LIST, PPC_VX_OPCODE_E_FORM_LIST, PPC_VX_OPCODE_F_FORM_LIST, PPC_VX_OPCODE_G_FORM_LIST, PPC_VX_OPCODE_UNUSED_LIST, PPC_X_OPCODE_EH_S_FORM_LIST, PPC_X_OPCODE_LIST, PPC_XFL_OPCODE_LIST, PPC_XFX_OPCODE_LIST, PPC_XL_OPCODE_LIST, PPC_XO_OPCODE_LIST, PPC_XS_OPCODE_LIST, PPC_XX1_OPCODE_LIST, PPC_XX2_OPCODE_B_FORM_LIST, PPC_XX2_OPCODE_SCALAR_A_FORM_LIST, PPC_XX2_OPCODE_UNUSED_LIST, PPC_XX2_OPCODE_VECTOR_A_FORM_LIST, PPC_XX3_OPCODE_SCALAR_LIST, PPC_XX3_OPCODE_VECTOR_A_FORM_LIST, PPC_XX3_OPCODE_VECTOR_B_FORM_LIST, PPC_XX4_OPCODE_LIST, PPC_Z22_OPCODE_LIST, PPC_Z23_OPCODE_LIST, PrefixOpcodeField(), and v8::internal::UNIMPLEMENTED().
OpcodeField() [1/2]
Opcode v8::internal::Instruction::OpcodeField () const [inline]
Definition at line 551 of file constants-arm.h.
                                    {
    return static_cast<Opcode>(BitField(24, 21));
  }
References BitField().
Referenced by OpcodeBase().
OpcodeField() [2/2]
uint32_t v8::internal::Instruction::OpcodeField () const [inline]
Definition at line 3055 of file constants-ppc.h.
                                 { return static_cast<Opcode>(Bits(31, 26)); }
  inline uint32_t OpcodeField() const {
References Bits().
OpcodeValue() [1/2]
int v8::internal::Instruction::OpcodeValue () const [inline]
Definition at line 550 of file constants-arm.h.
{ return static_cast<Opcode>(Bits(24, 21)); }
References Bits().
OpcodeValue() [2/2]
int v8::internal::Instruction::OpcodeValue () const [inline]
Definition at line 3054 of file constants-ppc.h.
{ return static_cast<Opcode>(Bits(31, 26)); }
preceding() [1/2]
Instruction* v8::internal::Instruction::preceding (int count = 1) [inline]
Definition at line 122 of file instructions-arm64.h.
{ return following(-count); }
References following().
preceding() [2/2]
const Instruction* v8::internal::Instruction::preceding (int count = 1) const [inline]
Definition at line 118 of file instructions-arm64.h.
                                                              {
    return following(-count);
  }
References following().
PrefixOpcodeField()
uint32_t v8::internal::Instruction::PrefixOpcodeField () const [inline]
Definition at line 3058 of file constants-ppc.h.
                                            {
Referenced by OpcodeBase().
PUField()
int v8::internal::Instruction::PUField () const [inline]
Definition at line 578 of file constants-arm.h.
{ return BitField(24, 23); }
References BitField().
PUValue()
int v8::internal::Instruction::PUValue () const [inline]
Definition at line 577 of file constants-arm.h.
{ return Bits(24, 23); }
References Bits().
PValue()
int v8::internal::Instruction::PValue () const [inline]
Definition at line 529 of file constants-arm.h.
{ return Bit(24); }
References Bit().
RAValue()
int v8::internal::Instruction::RAValue () const [inline]
Definition at line 3047 of file constants-ppc.h.
{ return Bits(25, 21); }
References Bits().
RBValue()
int v8::internal::Instruction::RBValue () const [inline]
Definition at line 3049 of file constants-ppc.h.
{ return Bits(20, 16); }
References Bits().
RCValue()
int v8::internal::Instruction::RCValue () const [inline]
Definition at line 3051 of file constants-ppc.h.
{ return Bits(15, 11); }
References Bits().
RdMode()
Reg31Mode v8::internal::Instruction::RdMode () const [inline]
Definition at line 256 of file instructions-arm64.h.
                           {
    // The following instructions use sp or wsp as Rd:
    // Add/sub (immediate) when not setting the flags.
    // Add/sub (extended) when not setting the flags.
    // Logical (immediate) when not setting the flags.
    // Otherwise, r31 is the zero register.
    if (IsAddSubImmediate() || IsAddSubExtended()) {
      if (Mask(AddSubSetFlagsBit)) {
        return Reg31IsZeroRegister;
      } else {
        return Reg31IsStackPointer;
      }
    }
    if (IsLogicalImmediate()) {
      // Of the logical (immediate) instructions, only ANDS (and its aliases)
      // can set the flags. The others can all write into sp.
      // Note that some logical operations are not available to
      // immediate-operand instructions, so we have to combine two masks here.
      if (Mask(LogicalImmediateMask & LogicalOpMask) == ANDS) {
        return Reg31IsZeroRegister;
      } else {
        return Reg31IsStackPointer;
      }
    }
    return Reg31IsZeroRegister;
  }
References v8::internal::AddSubSetFlagsBit, v8::internal::ANDS, IsAddSubExtended(), IsAddSubImmediate(), IsLogicalImmediate(), v8::internal::LogicalImmediateMask, v8::internal::LogicalOpMask, Mask(), v8::internal::Reg31IsStackPointer, and v8::internal::Reg31IsZeroRegister.
RdValue()
int v8::internal::Instruction::RdValue () const [inline]
Definition at line 516 of file constants-arm.h.
{ return Bits(15, 12); }
References Bits().
Referenced by v8::internal::Decoder< V >::DecodeIType(), v8::internal::Decoder< V >::DecodeJType(), v8::internal::Decoder< V >::FormatFPURegisterOrRoundMode(), v8::internal::Decoder< V >::FormatRegister(), v8::internal::Assembler::IsConstantPoolAt(), v8::internal::Decoder< V >::PrintFRd(), v8::internal::Decoder< V >::PrintRd(), and v8::internal::Assembler::target_at_put().
RegShiftValue()
int v8::internal::Instruction::RegShiftValue () const [inline]
Definition at line 562 of file constants-arm.h.
{ return Bit(4); }
References Bit().
RlistValue()
int v8::internal::Instruction::RlistValue () const [inline]
Definition at line 586 of file constants-arm.h.
{ return Bits(15, 0); }
References Bits().
RmValue()
int v8::internal::Instruction::RmValue () const [inline]
Definition at line 556 of file constants-arm.h.
{ return Bits(3, 0); }
References Bits().
RnMode()
Reg31Mode v8::internal::Instruction::RnMode () const [inline]
Definition at line 285 of file instructions-arm64.h.
                           {
    // The following instructions use sp or wsp as Rn:
    // All loads and stores.
    // Add/sub (immediate).
    // Add/sub (extended).
    // Otherwise, r31 is the zero register.
    if (IsLoadOrStore() || IsAddSubImmediate() || IsAddSubExtended()) {
      return Reg31IsStackPointer;
    }
    return Reg31IsZeroRegister;
  }
References IsAddSubExtended(), IsAddSubImmediate(), IsLoadOrStore(), v8::internal::Reg31IsStackPointer, and v8::internal::Reg31IsZeroRegister.
RnValue()
int v8::internal::Instruction::RnValue () const [inline]
Definition at line 514 of file constants-arm.h.
{ return Bits(19, 16); }
References Bits().
RotateValue()
int v8::internal::Instruction::RotateValue () const [inline]
Definition at line 566 of file constants-arm.h.
{ return Bits(11, 8); }
References Bits().
RsValue()
int v8::internal::Instruction::RsValue () const [inline]
Definition at line 563 of file constants-arm.h.
{ return Bits(11, 8); }
References Bits().
RSValue()
int v8::internal::Instruction::RSValue () const [inline]
Definition at line 3045 of file constants-ppc.h.
{ return Bits(25, 21); }
RtValue()
int v8::internal::Instruction::RtValue () const [inline]
Definition at line 528 of file constants-arm.h.
{ return Bits(15, 12); }
References Bits().
RTValue()
int v8::internal::Instruction::RTValue () const [inline]
Definition at line 3046 of file constants-ppc.h.
{ return Bits(25, 21); }
S390OpcodeValue() [1/2]
Opcode v8::internal::Instruction::S390OpcodeValue () [inline]
Definition at line 1995 of file constants-s390.h.
                                  {
    return Instruction::S390OpcodeValue(reinterpret_cast<const uint8_t*>(this));
  }
S390OpcodeValue() [2/2]
static Opcode v8::internal::Instruction::S390OpcodeValue (const uint8_t * instr) [inline], [static]
Definition at line 2144 of file constants-s390.h.
                                                             {
    OpcodeFormatType opcodeType = getOpcodeFormatType(instr);
    // The native instructions are encoded in big-endian format
    // even if running on little-endian host. Hence, we need
    // to ensure we use uint8_t* based bit-wise logic.
    switch (opcodeType) {
      case ONE_BYTE_OPCODE:
        // One Byte - Bits 0 to 7
        return static_cast<Opcode>(*instr);
      case TWO_BYTE_OPCODE:
        // Two Bytes - Bits 0 to 15
        return static_cast<Opcode>((*instr << 8) | (*(instr + 1)));
      case TWO_BYTE_DISJOINT_OPCODE:
        // Two Bytes - Bits 0 to 7, 40 to 47
        return static_cast<Opcode>((*instr << 8) | (*(instr + 5) & 0xFF));
      default:
        // case THREE_NIBBLE_OPCODE:
        // Three Nibbles - Bits 0 to 7, 12 to 15
        return static_cast<Opcode>((*instr << 4) | (*(instr + 1) & 0xF));
    }
    UNREACHABLE();
  }
References getOpcodeFormatType(), ONE_BYTE_OPCODE, TWO_BYTE_DISJOINT_OPCODE, TWO_BYTE_OPCODE, and v8::internal::UNREACHABLE().
SetBranchImmTarget()
template<ImmBranchType branch_type>
void v8::internal::Instruction::SetBranchImmTarget (Instruction * target, WritableJitAllocation * jit_allocation = nullptr) [inline]
Definition at line 472 of file instructions-arm64.h.
                                                                           {
    DCHECK(IsAligned(DistanceTo(target), kInstrSize));
    DCHECK(IsValidImmPCOffset(branch_type, DistanceTo(target)));
    int offset = static_cast<int>(DistanceTo(target) >> kInstrSizeLog2);
    Instr branch_imm = 0;
    uint32_t imm_mask = 0;
    switch (branch_type) {
      case CondBranchType:
      case CompareBranchType:
        static_assert(ImmCondBranch_mask == ImmCmpBranch_mask);
        static_assert(ImmCondBranch_offset == ImmCmpBranch_offset);
        // We use a checked truncation here to catch certain bugs where we fail
        // to check whether a veneer is required. See e.g. crbug.com/1485829.
        branch_imm = checked_truncate_to_int19(offset) << ImmCondBranch_offset;
        imm_mask = ImmCondBranch_mask;
        break;
      case UncondBranchType:
        branch_imm = checked_truncate_to_int26(offset)
                     << ImmUncondBranch_offset;
        imm_mask = ImmUncondBranch_mask;
        break;
      case TestBranchType:
        branch_imm = checked_truncate_to_int14(offset) << ImmTestBranch_offset;
        imm_mask = ImmTestBranch_mask;
        break;
      default:
        UNREACHABLE();
    }
    SetInstructionBits(Mask(~imm_mask) | branch_imm, jit_allocation);
  }
References v8::internal::CompareBranchType, v8::internal::CondBranchType, v8::internal::DCHECK(), DistanceTo(), IsAligned(), IsValidImmPCOffset(), v8::internal::kInstrSize, v8::internal::kInstrSizeLog2, Mask(), SetInstructionBits(), v8::internal::TestBranchType, v8::internal::UncondBranchType, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
SetBranchOffset()
void v8::internal::Instruction::SetBranchOffset (int32_t branch_offset, WritableJitAllocation * jit_allocation) [inline]
Definition at line 606 of file constants-arm.h.
                                                                     {
    DCHECK(IsBranch());
    DCHECK_EQ(branch_offset % kInstrSize, 0);
    int32_t new_imm24 = branch_offset / kInstrSize;
    CHECK(is_int24(new_imm24));
    SetInstructionBits(
        (InstructionBits() & ~(kImm24Mask)) | (new_imm24 & kImm24Mask),
        jit_allocation);
  }
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, InstructionBits(), IsBranch(), v8::internal::kImm24Mask, v8::internal::kInstrSize, and SetInstructionBits().
Referenced by v8::internal::WritableRelocInfo::apply(), and v8::internal::Assembler::set_target_address_at().
SetImmLLiteral()
void v8::internal::Instruction::SetImmLLiteral (Instruction * source)
SetImmPCOffsetTarget()
void v8::internal::Instruction::SetImmPCOffsetTarget (Zone * zone, AssemblerOptions options, Instruction * target)
SetInstructionBits() [1/6]
V8_EXPORT_PRIVATE void v8::internal::Instruction::SetInstructionBits (Instr new_instr, WritableJitAllocation * jit_allocation = nullptr)
SetInstructionBits() [2/6]
V8_EXPORT_PRIVATE void v8::internal::Instruction::SetInstructionBits (Instr value, WritableJitAllocation * jit_allocation = nullptr)
Referenced by SetBranchImmTarget(), and SetBranchOffset().
SetInstructionBits() [3/6]
V8_EXPORT_PRIVATE void v8::internal::Instruction::SetInstructionBits (Instr value, WritableJitAllocation * jit_allocation = nullptr)
SetInstructionBits() [4/6]
V8_EXPORT_PRIVATE void v8::internal::Instruction::SetInstructionBits (Instr value, WritableJitAllocation * jit_allocation = nullptr)
SetInstructionBits() [5/6]
template<typename T >
void v8::internal::Instruction::SetInstructionBits (T value, WritableJitAllocation * jit_allocation = nullptr) const [inline]
Definition at line 1962 of file constants-s390.h.
                                                                      {
    Instruction::SetInstructionBits<T>(reinterpret_cast<const uint8_t*>(this),
                                       value, jit_allocation);
  }
References v8::internal::value.
SetInstructionBits() [6/6]
template<typename T >
static void v8::internal::Instruction::SetInstructionBits (uint8_t * instr, T value, WritableJitAllocation * jit_allocation = nullptr) [inline], [static]
Definition at line 2072 of file constants-s390.h.
                                                       {
#if V8_TARGET_LITTLE_ENDIAN
    // The instruction bits are stored in big endian format even on little
    // endian hosts, in order to decode instruction length and opcode.
    // The following code will reverse the bytes so that the stores later
    // (which are in native endianess) will effectively save the instruction
    // in big endian.
    if (sizeof(T) == 2) {
      // Two Byte Instruction
      value = ((value & 0x00FF) << 8) | ((value & 0xFF00) >> 8);
    } else if (sizeof(T) == 4) {
      // Four Byte Instruction
      value = ((value & 0x000000FF) << 24) | ((value & 0x0000FF00) << 8) |
              ((value & 0x00FF0000) >> 8) | ((value & 0xFF000000) >> 24);
    } else if (sizeof(T) == 8) {
      // Six Byte Instruction
      uint64_t orig_value = static_cast<uint64_t>(value);
      value = (static_cast<uint64_t>(orig_value & 0xFF) << 40) |
              (static_cast<uint64_t>((orig_value >> 8) & 0xFF) << 32) |
              (static_cast<uint64_t>((orig_value >> 16) & 0xFF) << 24) |
              (static_cast<uint64_t>((orig_value >> 24) & 0xFF) << 16) |
              (static_cast<uint64_t>((orig_value >> 32) & 0xFF) << 8) |
              (static_cast<uint64_t>((orig_value >> 40) & 0xFF));
    }
#endif
    if (sizeof(T) <= 4) {
      if (jit_allocation) {
        jit_allocation->WriteUnalignedValue(reinterpret_cast<Address>(instr),
                                            value);
      } else {
        *reinterpret_cast<T*>(instr) = value;
      }
    } else {
#if V8_TARGET_LITTLE_ENDIAN
      uint64_t orig_value = static_cast<uint64_t>(value);
      if (jit_allocation) {
        jit_allocation->WriteUnalignedValue(reinterpret_cast<Address>(instr),
                                            static_cast<uint32_t>(value));
        jit_allocation->WriteUnalignedValue(
            reinterpret_cast<Address>(instr + 4),
            static_cast<uint16_t>((orig_value >> 32) & 0xFFFF));
      } else {
        *reinterpret_cast<uint32_t*>(instr) = static_cast<uint32_t>(value);
        *reinterpret_cast<uint16_t*>(instr + 4) =
            static_cast<uint16_t>((orig_value >> 32) & 0xFFFF);
      }
#else
      if (jit_allocation) {
        jit_allocation->WriteUnalignedValue(reinterpret_cast<Address>(instr),
                                            static_cast<uint32_t>(value >> 16));
        jit_allocation->WriteUnalignedValue(
            reinterpret_cast<Address>(instr + 4),
            static_cast<uint16_t>(value & 0xFFFF));
      } else {
        *reinterpret_cast<uint32_t*>(instr) =
            static_cast<uint32_t>(value >> 16);
        *reinterpret_cast<uint16_t*>(instr + 4) =
            static_cast<uint16_t>(value & 0xFFFF);
      }
#endif
    }
  }
References v8::internal::value.
SetPCRelImmTarget()
void v8::internal::Instruction::SetPCRelImmTarget (Zone * zone, AssemblerOptions options, Instruction * target)
SetUnresolvedInternalReferenceImmTarget()
void v8::internal::Instruction::SetUnresolvedInternalReferenceImmTarget (Zone * zone, AssemblerOptions options, Instruction * target)
ShiftAmountValue()
int v8::internal::Instruction::ShiftAmountValue () const [inline]
Definition at line 564 of file constants-arm.h.
{ return Bits(11, 7); }
References Bits().
ShiftField()
ShiftOp v8::internal::Instruction::ShiftField () const [inline]
Definition at line 559 of file constants-arm.h.
                                    {
    return static_cast<ShiftOp>(BitField(6, 5));
  }
References BitField().
ShiftValue()
int v8::internal::Instruction::ShiftValue () const [inline]
Definition at line 558 of file constants-arm.h.
{ return static_cast<ShiftOp>(Bits(6, 5)); }
References Bits().
SignedBits()
int32_t v8::internal::Instruction::SignedBits (int msb, int lsb) const [inline]
Definition at line 101 of file instructions-arm64.h.
                                             {
    // Usually this is aligned, but when de/serializing that's not guaranteed.
    int32_t bits =
        base::ReadUnalignedValue<int32_t>(reinterpret_cast<Address>(this));
    return signed_bitextract_32(msb, lsb, bits);
  }
References v8::internal::signed_bitextract_32().
SignValue()
int v8::internal::Instruction::SignValue () const [inline]
Definition at line 588 of file constants-arm.h.
{ return Bit(6); }
References Bit().
Referenced by HasSign().
SImmed24Value()
int v8::internal::Instruction::SImmed24Value () const [inline]
Definition at line 595 of file constants-arm.h.
                                   {
    return signed_bitextract_32(23, 0, InstructionBits());
  }
References InstructionBits(), and v8::internal::signed_bitextract_32().
Referenced by GetBranchOffset().
SizeLS()
unsigned v8::internal::Instruction::SizeLS () const [inline]
Definition at line 146 of file instructions-arm64.h.
                          {
    return CalcLSDataSizeLog2(static_cast<LoadStoreOp>(Mask(LoadStoreMask)));
  }
References v8::internal::CalcLSDataSizeLog2(), v8::internal::LoadStoreMask, and Mask().
SizeLSPair()
unsigned v8::internal::Instruction::SizeLSPair () const [inline]
Definition at line 150 of file instructions-arm64.h.
                              {
    return CalcLSPairDataSize(
        static_cast<LoadStorePairOp>(Mask(LoadStorePairMask)));
  }
References v8::internal::CalcLSPairDataSize(), v8::internal::LoadStorePairMask, and Mask().
SpecialValue()
int v8::internal::Instruction::SpecialValue () const [inline]
Definition at line 512 of file constants-arm.h.
{ return Bits(27, 23); }
References Bits().
SValue()
int v8::internal::Instruction::SValue () const [inline]
Definition at line 554 of file constants-arm.h.
{ return Bit(20); }
References Bit().
Referenced by HasS().
SvcValue() [1/3]
SoftwareInterruptCodes v8::internal::Instruction::SvcValue () const [inline]
Definition at line 618 of file constants-arm.h.
                                                 {
    return static_cast<SoftwareInterruptCodes>(Bits(23, 0));
  }
References Bits().
Referenced by IsStop().
SvcValue() [2/3]
SoftwareInterruptCodes v8::internal::Instruction::SvcValue () const [inline]
Definition at line 3214 of file constants-ppc.h.
                                                 {
References Bits().
SvcValue() [3/3]
SoftwareInterruptCodes v8::internal::Instruction::SvcValue () const [inline]
Definition at line 2170 of file constants-s390.h.
                                                 {
    return static_cast<SoftwareInterruptCodes>(Bits<FourByteInstr, int>(15, 0));
  }
SzValue()
int v8::internal::Instruction::SzValue () const [inline]
Definition at line 534 of file constants-arm.h.
{ return Bit(8); }
References Bit().
TypeValue()
int v8::internal::Instruction::TypeValue () const [inline]
Definition at line 511 of file constants-arm.h.
{ return Bits(27, 25); }
References Bits().
Referenced by IsStop().
UValue()
int v8::internal::Instruction::UValue () const [inline]
Definition at line 530 of file constants-arm.h.
{ return Bit(23); }
References Bit().
Referenced by HasU().
VAValue()
int v8::internal::Instruction::VAValue () const [inline]
Definition at line 537 of file constants-arm.h.
{ return Bits(23, 21); }
References Bits().
VBValue()
int v8::internal::Instruction::VBValue () const [inline]
Definition at line 538 of file constants-arm.h.
{ return Bits(6, 5); }
References Bits().
VCValue()
int v8::internal::Instruction::VCValue () const [inline]
Definition at line 536 of file constants-arm.h.
{ return Bit(8); }
References Bit().
VdValue()
int v8::internal::Instruction::VdValue () const [inline]
Definition at line 524 of file constants-arm.h.
{ return Bits(15, 12); }
References Bits().
Referenced by v8::internal::Decoder< V >::PrintVd().
VFPDRegValue()
int v8::internal::Instruction::VFPDRegValue (VFPRegPrecision pre) [inline]
Definition at line 545 of file constants-arm.h.
                                               {
    return VFPGlueRegValue(pre, 12, 22);
  }
References VFPGlueRegValue().
VFPGlueRegValue()
int v8::internal::Instruction::VFPGlueRegValue (VFPRegPrecision pre, int four_bit, int one_bit) [inline], [private]
Definition at line 666 of file constants-arm.h.
                                                                             {
    if (pre == kSinglePrecision) {
      return (Bits(four_bit + 3, four_bit) << 1) | Bit(one_bit);
    } else {
      int reg_num = (Bit(one_bit) << 4) | Bits(four_bit + 3, four_bit);
      if (pre == kDoublePrecision) {
        return reg_num;
      }
      DCHECK_EQ(kSimd128Precision, pre);
      DCHECK_EQ(reg_num & 1, 0);
      return reg_num / 2;
    }
  }
References Bit(), Bits(), DCHECK_EQ, v8::internal::kDoublePrecision, v8::internal::kSimd128Precision, and v8::internal::kSinglePrecision.
Referenced by VFPDRegValue(), VFPMRegValue(), and VFPNRegValue().
VFPMRegValue()
int v8::internal::Instruction::VFPMRegValue (VFPRegPrecision pre) [inline]
Definition at line 542 of file constants-arm.h.
                                               {
    return VFPGlueRegValue(pre, 0, 5);
  }
References VFPGlueRegValue().
VFPNRegValue()
int v8::internal::Instruction::VFPNRegValue (VFPRegPrecision pre) [inline]
Definition at line 539 of file constants-arm.h.
                                               {
    return VFPGlueRegValue(pre, 16, 7);
  }
References VFPGlueRegValue().
VLValue()
int v8::internal::Instruction::VLValue () const [inline]
Definition at line 535 of file constants-arm.h.
{ return Bit(20); }
References Bit().
VmValue()
int v8::internal::Instruction::VmValue () const [inline]
Definition at line 523 of file constants-arm.h.
{ return Bits(3, 0); }
References Bits().
VnValue()
int v8::internal::Instruction::VnValue () const [inline]
Definition at line 522 of file constants-arm.h.
{ return Bits(19, 16); }
References Bits().
WValue()
int v8::internal::Instruction::WValue () const [inline]
Definition at line 580 of file constants-arm.h.
{ return Bit(21); }
References Bit().
Referenced by HasW().
Member Data Documentation
ImmPCRelRangeBitwidth
const int v8::internal::Instruction::ImmPCRelRangeBitwidth = 21 [static]
Definition at line 466 of file instructions-arm64.h.
kPcLoadDelta
constexpr int v8::internal::Instruction::kPcLoadDelta = 8 [static], [constexpr]
Definition at line 455 of file constants-arm.h.
Referenced by v8::internal::Assembler::constant_pool_entry_address(), v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), v8::internal::Deoptimizer::PatchToJump(), v8::internal::Assembler::set_target_address_at(), and v8::internal::Assembler::target_address_at().
OpcodeFormatTable
OpcodeFormatType v8::internal::Instruction::OpcodeFormatTable[256] [static]
Definition at line 1948 of file constants-s390.h.
Referenced by getOpcodeFormatType().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm/constants-arm.h
/mnt/V8SourceCode/src/codegen/arm64/instructions-arm64.h
/mnt/V8SourceCode/src/codegen/s390/constants-s390.h
/mnt/V8SourceCode/src/codegen/loong64/constants-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/constants-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/constants-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/base-constants-riscv.h