v8::internal::compiler::ObserveNodeManager Class Reference
#include <node-observer.h>
Public Member Functions
ObserveNodeManager (Zone *zone)
void StartObserving (Node *node, NodeObserver *observer)
void OnNodeChanged (const char *reducer_name, const Node *old_node, const Node *new_node)
Private Attributes
Zone * zone_
ZoneMap< NodeId, NodeObservation * > observations_
Detailed Description
Definition at line 97 of file node-observer.h.
Constructor & Destructor Documentation
ObserveNodeManager()
v8::internal::compiler::ObserveNodeManager::ObserveNodeManager (Zone * zone) [inline], [explicit]
Definition at line 99 of file node-observer.h.
: zone_(zone), observations_(zone) {}
Member Function Documentation
OnNodeChanged()
void v8::internal::compiler::ObserveNodeManager::OnNodeChanged (const char * reducer_name, const Node * old_node, const Node * new_node)
Definition at line 33 of file node-observer.cc.
                                                             {
  const auto it = observations_.find(old_node->id());
  if (it == observations_.end()) return;
  ObservableNodeState new_state{new_node, zone_};
  NodeObservation* observation = it->second;
  if (observation->state == new_state) return;
  ObservableNodeState old_state = observation->state;
  observation->state = new_state;
  NodeObserver::Observation result =
      observation->observer->OnNodeChanged(reducer_name, new_node, old_state);
  if (result == NodeObserver::Observation::kStop) {
    observations_.erase(old_node->id());
  } else {
    DCHECK_EQ(result, NodeObserver::Observation::kContinue);
    if (old_node != new_node) {
      observations_.erase(old_node->id());
      observations_[new_node->id()] = observation;
    }
  }
}
References DCHECK_EQ, v8::internal::compiler::Node::id(), v8::internal::compiler::NodeObserver::kContinue, v8::internal::compiler::NodeObserver::kStop, observations_, v8::internal::compiler::NodeObservation::observer, v8::internal::compiler::NodeObserver::OnNodeChanged(), v8::base::internal::result, v8::internal::compiler::NodeObservation::state, and zone_.
Referenced by v8::internal::compiler::RepresentationSelector::ChangeOp(), v8::internal::compiler::SimplifiedLowering::ChangeOp(), v8::internal::compiler::RepresentationSelector::NotifyNodeReplaced(), and v8::internal::compiler::Reducer::Reduce().
StartObserving()
void v8::internal::compiler::ObserveNodeManager::StartObserving (Node * node, NodeObserver * observer)
Definition at line 18 of file node-observer.cc.
                                                                          {
  DCHECK_NOT_NULL(node);
  DCHECK_NOT_NULL(observer);
  DCHECK(observations_.find(node->id()) == observations_.end());
  observer->set_has_observed_changes();
  NodeObserver::Observation observation = observer->OnNodeCreated(node);
  if (observation == NodeObserver::Observation::kContinue) {
    observations_[node->id()] =
        zone_->New<NodeObservation>(observer, node, zone_);
  } else {
    DCHECK_EQ(observation, NodeObserver::Observation::kStop);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::Node::id(), v8::internal::compiler::NodeObserver::kContinue, v8::internal::compiler::NodeObserver::kStop, v8::internal::Zone::New(), observations_, v8::internal::compiler::NodeObserver::OnNodeCreated(), v8::internal::compiler::NodeObserver::set_has_observed_changes(), and zone_.
Referenced by v8::internal::compiler::ObserveNodeInfo::StartObserving().
Member Data Documentation
observations_
ZoneMap<NodeId, NodeObservation*> v8::internal::compiler::ObserveNodeManager::observations_ [private]
Definition at line 107 of file node-observer.h.
Referenced by OnNodeChanged(), and StartObserving().
zone_
Zone* v8::internal::compiler::ObserveNodeManager::zone_ [private]
Definition at line 106 of file node-observer.h.
Referenced by OnNodeChanged(), and StartObserving().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-observer.h
/mnt/V8SourceCode/src/compiler/node-observer.cc