v8::internal::maglev::OpProperties Class Reference
#include <maglev-ir.h>
Public Member Functions
constexpr bool is_call () const
constexpr bool is_any_call () const
constexpr bool can_eager_deopt () const
constexpr bool can_lazy_deopt () const
constexpr bool is_deopt_checkpoint () const
constexpr bool can_deopt () const
constexpr bool can_throw () const
constexpr bool can_read () const
constexpr bool can_write () const
constexpr bool can_allocate () const
constexpr bool not_idempotent () const
constexpr ValueRepresentation value_representation () const
constexpr bool is_tagged () const
constexpr bool is_conversion () const
constexpr bool needs_register_snapshot () const
constexpr bool is_pure () const
constexpr bool is_required_when_unused () const
constexpr bool can_participate_in_cse () const
constexpr OpProperties operator| (const OpProperties &that)
constexpr OpProperties (uint32_t bitfield)
operator uint32_t () const
OpProperties WithNewValueRepresentation (ValueRepresentation new_repr) const
OpProperties WithoutDeopt () const
constexpr bool is_deferred_call () const
Static Public Member Functions
static constexpr OpProperties Pure ()
static constexpr OpProperties Call ()
static constexpr OpProperties EagerDeopt ()
static constexpr OpProperties LazyDeopt ()
static constexpr OpProperties DeoptCheckpoint ()
static constexpr OpProperties CanThrow ()
static constexpr OpProperties CanRead ()
static constexpr OpProperties CanWrite ()
static constexpr OpProperties CanAllocate ()
static constexpr OpProperties NotIdempotent ()
static constexpr OpProperties TaggedValue ()
static constexpr OpProperties ExternalReference ()
static constexpr OpProperties Int32 ()
static constexpr OpProperties Uint32 ()
static constexpr OpProperties Float64 ()
static constexpr OpProperties HoleyFloat64 ()
static constexpr OpProperties IntPtr ()
static constexpr OpProperties TrustedPointer ()
static constexpr OpProperties ForValueRepresentation (ValueRepresentation repr)
static constexpr OpProperties ConversionNode ()
static constexpr OpProperties CanCallUserCode ()
static constexpr OpProperties GenericRuntimeOrBuiltinCall ()
static constexpr OpProperties JSCall ()
static constexpr OpProperties AnySideEffects ()
static constexpr OpProperties DeferredCall ()
Static Public Attributes
static const size_t kSize = kNeedsRegisterSnapshotBit::kLastUsedBit + 1
Private Types
enum class AttachedDeoptInfo { kNone
, kEager
, kLazy
, kCheckpoint
 }
using kIsCallBit = base::BitField< bool, 0, 1 >
using kAttachedDeoptInfoBits = kIsCallBit::Next< AttachedDeoptInfo, 2 >
using kCanThrowBit = kAttachedDeoptInfoBits::Next< bool, 1 >
using kCanReadBit = kCanThrowBit::Next< bool, 1 >
using kCanWriteBit = kCanReadBit::Next< bool, 1 >
using kCanAllocateBit = kCanWriteBit::Next< bool, 1 >
using kNotIdempotentBit = kCanAllocateBit::Next< bool, 1 >
using kValueRepresentationBits = kNotIdempotentBit::Next< ValueRepresentation, 3 >
using kIsConversionBit = kValueRepresentationBits::Next< bool, 1 >
using kNeedsRegisterSnapshotBit = kIsConversionBit::Next< bool, 1 >
Static Private Member Functions
static constexpr OpProperties NeedsRegisterSnapshot ()
Private Attributes
const uint32_t bitfield_
Static Private Attributes
static const uint32_t kPureMask
static const uint32_t kPureValue
Detailed Description
Definition at line 1207 of file maglev-ir.h.
Member Typedef Documentation
kAttachedDeoptInfoBits
using v8::internal::maglev::OpProperties::kAttachedDeoptInfoBits = kIsCallBit::Next<AttachedDeoptInfo, 2> [private]
Definition at line 1388 of file maglev-ir.h.
kCanAllocateBit
using v8::internal::maglev::OpProperties::kCanAllocateBit = kCanWriteBit::Next<bool, 1> [private]
Definition at line 1392 of file maglev-ir.h.
kCanReadBit
using v8::internal::maglev::OpProperties::kCanReadBit = kCanThrowBit::Next<bool, 1> [private]
Definition at line 1390 of file maglev-ir.h.
kCanThrowBit
using v8::internal::maglev::OpProperties::kCanThrowBit = kAttachedDeoptInfoBits::Next<bool, 1> [private]
Definition at line 1389 of file maglev-ir.h.
kCanWriteBit
using v8::internal::maglev::OpProperties::kCanWriteBit = kCanReadBit::Next<bool, 1> [private]
Definition at line 1391 of file maglev-ir.h.
kIsCallBit
using v8::internal::maglev::OpProperties::kIsCallBit = base::BitField<bool, 0, 1> [private]
Definition at line 1387 of file maglev-ir.h.
kIsConversionBit
using v8::internal::maglev::OpProperties::kIsConversionBit = kValueRepresentationBits::Next<bool, 1> [private]
Definition at line 1396 of file maglev-ir.h.
kNeedsRegisterSnapshotBit
using v8::internal::maglev::OpProperties::kNeedsRegisterSnapshotBit = kIsConversionBit::Next<bool, 1> [private]
Definition at line 1397 of file maglev-ir.h.
kNotIdempotentBit
using v8::internal::maglev::OpProperties::kNotIdempotentBit = kCanAllocateBit::Next<bool, 1> [private]
Definition at line 1393 of file maglev-ir.h.
kValueRepresentationBits
using v8::internal::maglev::OpProperties::kValueRepresentationBits = kNotIdempotentBit::Next<ValueRepresentation, 3> [private]
Definition at line 1394 of file maglev-ir.h.
Member Enumeration Documentation
AttachedDeoptInfo
enum v8::internal::maglev::OpProperties::AttachedDeoptInfo [strong], [private]
Enumerator
kNone
kEager
kLazy
kCheckpoint
Definition at line 1386 of file maglev-ir.h.
{ kNone, kEager, kLazy, kCheckpoint };
Constructor & Destructor Documentation
OpProperties()
constexpr v8::internal::maglev::OpProperties::OpProperties (uint32_t bitfield) [inline], [explicit], [constexpr]
Definition at line 1373 of file maglev-ir.h.
: bitfield_(bitfield) {}
Referenced by Call(), CanAllocate(), CanRead(), CanThrow(), CanWrite(), ConversionNode(), DeoptCheckpoint(), EagerDeopt(), ExternalReference(), Float64(), ForValueRepresentation(), HoleyFloat64(), Int32(), IntPtr(), LazyDeopt(), NeedsRegisterSnapshot(), NotIdempotent(), operator|(), Pure(), TaggedValue(), TrustedPointer(), Uint32(), WithNewValueRepresentation(), and WithoutDeopt().
Member Function Documentation
AnySideEffects()
static constexpr OpProperties v8::internal::maglev::OpProperties::AnySideEffects () [inline], [static], [constexpr]
Definition at line 1363 of file maglev-ir.h.
                                                 {
    return CanRead() | CanWrite() | CanAllocate();
  }
References CanAllocate(), CanRead(), and CanWrite().
Referenced by CanCallUserCode().
Call()
static constexpr OpProperties v8::internal::maglev::OpProperties::Call () [inline], [static], [constexpr]
Definition at line 1281 of file maglev-ir.h.
                                       {
    return OpProperties(kIsCallBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), GenericRuntimeOrBuiltinCall(), and JSCall().
can_allocate()
constexpr bool v8::internal::maglev::OpProperties::can_allocate () const [inline], [constexpr]
Definition at line 1237 of file maglev-ir.h.
                                      {
    return kCanAllocateBit::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process().
can_deopt()
constexpr bool v8::internal::maglev::OpProperties::can_deopt () const [inline], [constexpr]
Definition at line 1227 of file maglev-ir.h.
                                   {
    return can_eager_deopt() || can_lazy_deopt();
  }
References can_eager_deopt(), and can_lazy_deopt().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), is_required_when_unused(), and v8::internal::maglev::LoopOptimizationProcessor::ProcessNamedLoad().
can_eager_deopt()
constexpr bool v8::internal::maglev::OpProperties::can_eager_deopt () const [inline], [constexpr]
Definition at line 1215 of file maglev-ir.h.
                                         {
    return kAttachedDeoptInfoBits::decode(bitfield_) ==
           AttachedDeoptInfo::kEager;
  }
References bitfield_, v8::base::BitField< T, shift, size, U >::decode(), and kEager.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::AddNode(), v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), can_deopt(), v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), v8::internal::maglev::NodeBase::EagerDeoptInfoSize(), v8::internal::maglev::SweepIdentityNodes::Process(), v8::internal::maglev::LoopOptimizationProcessor::Process(), and v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot().
can_lazy_deopt()
constexpr bool v8::internal::maglev::OpProperties::can_lazy_deopt () const [inline], [constexpr]
Definition at line 1219 of file maglev-ir.h.
                                        {
    return kAttachedDeoptInfoBits::decode(bitfield_) ==
           AttachedDeoptInfo::kLazy;
  }
References bitfield_, v8::base::BitField< T, shift, size, U >::decode(), and kLazy.
Referenced by v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), can_deopt(), can_throw(), v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), v8::internal::maglev::NodeBase::LazyDeoptInfoSize(), and v8::internal::maglev::SweepIdentityNodes::Process().
can_participate_in_cse()
constexpr bool v8::internal::maglev::OpProperties::can_participate_in_cse () const [inline], [constexpr]
Definition at line 1272 of file maglev-ir.h.
                                                {
    return !can_write() && !not_idempotent();
  }
References can_write(), and not_idempotent().
Referenced by v8::internal::maglev::Node::participate_in_cse().
can_read()
constexpr bool v8::internal::maglev::OpProperties::can_read () const [inline], [constexpr]
Definition at line 1235 of file maglev-ir.h.
{ return kCanReadBit::decode(bitfield_); }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::Node::needs_epoch_check().
can_throw()
constexpr bool v8::internal::maglev::OpProperties::can_throw () const [inline], [constexpr]
Definition at line 1230 of file maglev-ir.h.
                                   {
    return kCanThrowBit::decode(bitfield_) && can_lazy_deopt();
  }
References bitfield_, can_lazy_deopt(), and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), v8::internal::maglev::NodeBase::ExceptionHandlerInfoSize(), is_required_when_unused(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::NoThrowingScopeRequired::NoThrowingScopeRequired(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
can_write()
constexpr bool v8::internal::maglev::OpProperties::can_write () const [inline], [constexpr]
Definition at line 1236 of file maglev-ir.h.
{ return kCanWriteBit::decode(bitfield_); }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by can_participate_in_cse(), and is_required_when_unused().
CanAllocate()
static constexpr OpProperties v8::internal::maglev::OpProperties::CanAllocate () [inline], [static], [constexpr]
Definition at line 1306 of file maglev-ir.h.
                                              {
    return OpProperties(kCanAllocateBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
Referenced by AnySideEffects(), and CanThrow().
CanCallUserCode()
static constexpr OpProperties v8::internal::maglev::OpProperties::CanCallUserCode () [inline], [static], [constexpr]
Definition at line 1351 of file maglev-ir.h.
                                                  {
    return AnySideEffects() | LazyDeopt() | CanThrow();
  }
References AnySideEffects(), CanThrow(), and LazyDeopt().
Referenced by GenericRuntimeOrBuiltinCall(), and JSCall().
CanRead()
static constexpr OpProperties v8::internal::maglev::OpProperties::CanRead () [inline], [static], [constexpr]
Definition at line 1300 of file maglev-ir.h.
                                          {
    return OpProperties(kCanReadBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
Referenced by AnySideEffects().
CanThrow()
static constexpr OpProperties v8::internal::maglev::OpProperties::CanThrow () [inline], [static], [constexpr]
Definition at line 1296 of file maglev-ir.h.
                                           {
    return OpProperties(kCanThrowBit::encode(true)) | LazyDeopt() |
           CanAllocate();
  }
References CanAllocate(), v8::base::BitField< T, shift, size, U >::encode(), LazyDeopt(), and OpProperties().
Referenced by CanCallUserCode().
CanWrite()
v8::internal::maglev::OpProperties::CanWrite () [inline], [static], [constexpr]
Definition at line 1303 of file maglev-ir.h.
                                           {
    return OpProperties(kCanWriteBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
Referenced by AnySideEffects().
ConversionNode()
static constexpr OpProperties v8::internal::maglev::OpProperties::ConversionNode () [inline], [static], [constexpr]
Definition at line 1348 of file maglev-ir.h.
                                                 {
    return OpProperties(kIsConversionBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
DeferredCall()
static constexpr OpProperties v8::internal::maglev::OpProperties::DeferredCall () [inline], [static], [constexpr]
Definition at line 1366 of file maglev-ir.h.
                                               {
    // Operations with a deferred call need a snapshot of register state,
    // because they need to be able to push registers to save them, and annotate
    // the safepoint with information about which registers are tagged.
    return NeedsRegisterSnapshot();
  }
References NeedsRegisterSnapshot().
Referenced by is_deferred_call().
DeoptCheckpoint()
static constexpr OpProperties v8::internal::maglev::OpProperties::DeoptCheckpoint () [inline], [static], [constexpr]
Definition at line 1292 of file maglev-ir.h.
                                                  {
    return OpProperties(
        kAttachedDeoptInfoBits::encode(AttachedDeoptInfo::kCheckpoint));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kCheckpoint, and OpProperties().
EagerDeopt()
static constexpr OpProperties v8::internal::maglev::OpProperties::EagerDeopt () [inline], [static], [constexpr]
Definition at line 1284 of file maglev-ir.h.
                                             {
    return OpProperties(
        kAttachedDeoptInfoBits::encode(AttachedDeoptInfo::kEager));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kEager, and OpProperties().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode().
ExternalReference()
static constexpr OpProperties v8::internal::maglev::OpProperties::ExternalReference () [inline], [static], [constexpr]
Definition at line 1316 of file maglev-ir.h.
                                                    {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kIntPtr));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kIntPtr, and OpProperties().
Float64()
UINT32_ELEMENTS INT32_ELEMENTS v8::internal::maglev::OpProperties::Float64 () [inline], [static], [constexpr]
Definition at line 1328 of file maglev-ir.h.
                                          {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kFloat64));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kFloat64, and OpProperties().
ForValueRepresentation()
static constexpr OpProperties v8::internal::maglev::OpProperties::ForValueRepresentation (ValueRepresentation repr) [inline], [static], [constexpr]
Definition at line 1344 of file maglev-ir.h.
                                {
    return OpProperties(kValueRepresentationBits::encode(repr));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
GenericRuntimeOrBuiltinCall()
static constexpr OpProperties v8::internal::maglev::OpProperties::GenericRuntimeOrBuiltinCall () [inline], [static], [constexpr]
Definition at line 1359 of file maglev-ir.h.
                                                              {
    return Call() | CanCallUserCode() | NotIdempotent();
  }
References Call(), CanCallUserCode(), and NotIdempotent().
HoleyFloat64()
static constexpr OpProperties v8::internal::maglev::OpProperties::HoleyFloat64 () [inline], [static], [constexpr]
Definition at line 1332 of file maglev-ir.h.
                                               {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kHoleyFloat64));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kHoleyFloat64, and OpProperties().
Int32()
UINT32_ELEMENTS v8::internal::maglev::OpProperties::Int32 () [inline], [static], [constexpr]
Definition at line 1320 of file maglev-ir.h.
                                        {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kInt32));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kInt32, and OpProperties().
IntPtr()
static constexpr OpProperties v8::internal::maglev::OpProperties::IntPtr () [inline], [static], [constexpr]
Definition at line 1336 of file maglev-ir.h.
                                         {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kIntPtr));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kIntPtr, and OpProperties().
is_any_call()
constexpr bool v8::internal::maglev::OpProperties::is_any_call () const [inline], [constexpr]
Definition at line 1214 of file maglev-ir.h.
{ return is_call() || is_deferred_call(); }
References is_call(), and is_deferred_call().
Referenced by is_required_when_unused().
is_call()
constexpr bool v8::internal::maglev::OpProperties::is_call () const [inline], [constexpr]
Definition at line 1209 of file maglev-ir.h.
                                 {
    // Only returns true for non-deferred calls. Use `is_any_call` to check
    // deferred calls as well.
    return kIsCallBit::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), is_any_call(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::Process().
is_conversion()
constexpr bool v8::internal::maglev::OpProperties::is_conversion () const [inline], [constexpr]
Definition at line 1253 of file maglev-ir.h.
                                       {
    return kIsConversionBit::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), is_required_when_unused(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::CallArguments::set_arg(), v8::internal::maglev::CallArguments::set_receiver(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
is_deferred_call()
constexpr bool v8::internal::maglev::OpProperties::is_deferred_call () const [inline], [constexpr]
Definition at line 1418 of file maglev-ir.h.
                                          {
    // Currently, there is no kDeferredCall bit, but DeferredCall only sets a
    // single bit: kNeedsRegisterSnapShot. If this static assert breaks, it
    // means that you added additional properties to DeferredCall, and you
    // should update this function accordingly.
    static_assert(DeferredCall().bitfield_ ==
                  kNeedsRegisterSnapshotBit::encode(true));
    return needs_register_snapshot();
  }
References bitfield_, DeferredCall(), v8::base::BitField< T, shift, size, U >::encode(), and needs_register_snapshot().
Referenced by is_any_call(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process().
is_deopt_checkpoint()
constexpr bool v8::internal::maglev::OpProperties::is_deopt_checkpoint () const [inline], [constexpr]
Definition at line 1223 of file maglev-ir.h.
                                             {
    return kAttachedDeoptInfoBits::decode(bitfield_) ==
           AttachedDeoptInfo::kCheckpoint;
  }
References bitfield_, v8::base::BitField< T, shift, size, U >::decode(), and kCheckpoint.
Referenced by v8::internal::maglev::NodeBase::EagerDeoptInfoSize().
is_pure()
constexpr bool v8::internal::maglev::OpProperties::is_pure () const [inline], [constexpr]
Definition at line 1259 of file maglev-ir.h.
                                 {
    return (bitfield_ & kPureMask) == kPureValue;
  }
References bitfield_, kPureMask, and kPureValue.
is_required_when_unused()
constexpr bool v8::internal::maglev::OpProperties::is_required_when_unused () const [inline], [constexpr]
Definition at line 1262 of file maglev-ir.h.
                                                 {
    if (is_conversion()) {
      // Calls in conversions are not counted as a side-effect as far as
      // is_required_when_unused is concerned, since they should always be to
      // the Allocate builtin.
      return can_write() || can_throw() || can_deopt();
    } else {
      return can_write() || can_throw() || can_deopt() || is_any_call();
    }
  }
References can_deopt(), can_throw(), can_write(), is_any_call(), and is_conversion().
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult().
is_tagged()
constexpr bool v8::internal::maglev::OpProperties::is_tagged () const [inline], [constexpr]
Definition at line 1250 of file maglev-ir.h.
                                   {
    return value_representation() == ValueRepresentation::kTagged;
  }
References v8::internal::maglev::kTagged, and value_representation().
Referenced by v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructGeneric().
JSCall()
static constexpr OpProperties v8::internal::maglev::OpProperties::JSCall () [inline], [static], [constexpr]
Definition at line 1362 of file maglev-ir.h.
{ return Call() | CanCallUserCode(); }
References Call(), and CanCallUserCode().
LazyDeopt()
static constexpr OpProperties v8::internal::maglev::OpProperties::LazyDeopt () [inline], [static], [constexpr]
Definition at line 1288 of file maglev-ir.h.
                                            {
    return OpProperties(
        kAttachedDeoptInfoBits::encode(AttachedDeoptInfo::kLazy));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kLazy, and OpProperties().
Referenced by CanCallUserCode(), and CanThrow().
needs_register_snapshot()
constexpr bool v8::internal::maglev::OpProperties::needs_register_snapshot () const [inline], [constexpr]
Definition at line 1256 of file maglev-ir.h.
                                                 {
    return kNeedsRegisterSnapshotBit::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), is_deferred_call(), and v8::internal::maglev::NodeBase::RegisterSnapshotSize().
NeedsRegisterSnapshot()
static constexpr OpProperties v8::internal::maglev::OpProperties::NeedsRegisterSnapshot () [inline], [static], [constexpr], [private]
Definition at line 1409 of file maglev-ir.h.
                                                        {
    return OpProperties(kNeedsRegisterSnapshotBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
Referenced by DeferredCall().
not_idempotent()
constexpr bool v8::internal::maglev::OpProperties::not_idempotent () const [inline], [constexpr]
Definition at line 1244 of file maglev-ir.h.
                                        {
    return kNotIdempotentBit::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by can_participate_in_cse().
NotIdempotent()
static constexpr OpProperties v8::internal::maglev::OpProperties::NotIdempotent () [inline], [static], [constexpr]
Definition at line 1309 of file maglev-ir.h.
                                                {
    return OpProperties(kNotIdempotentBit::encode(true));
  }
References v8::base::BitField< T, shift, size, U >::encode(), and OpProperties().
Referenced by GenericRuntimeOrBuiltinCall().
operator uint32_t()
v8::internal::maglev::OpProperties::operator uint32_t () const [inline]
Definition at line 1374 of file maglev-ir.h.
{ return bitfield_; }
References bitfield_.
operator|()
constexpr OpProperties v8::internal::maglev::OpProperties::operator| (const OpProperties & that) [inline], [constexpr]
Definition at line 1276 of file maglev-ir.h.
                                                             {
    return OpProperties(bitfield_ | that.bitfield_);
  }
References bitfield_, and OpProperties().
Pure()
static constexpr OpProperties v8::internal::maglev::OpProperties::Pure () [inline], [static], [constexpr]
Definition at line 1280 of file maglev-ir.h.
{ return OpProperties(kPureValue); }
References kPureValue, and OpProperties().
Referenced by v8::internal::maglev::NodeBase::OverwriteWithIdentityTo().
TaggedValue()
static constexpr OpProperties v8::internal::maglev::OpProperties::TaggedValue () [inline], [static], [constexpr]
Definition at line 1312 of file maglev-ir.h.
                                              {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kTagged));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kTagged, and OpProperties().
TrustedPointer()
static constexpr OpProperties v8::internal::maglev::OpProperties::TrustedPointer () [inline], [static], [constexpr]
Definition at line 1340 of file maglev-ir.h.
                                                 {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kTagged));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kTagged, and OpProperties().
Uint32()
v8::internal::maglev::OpProperties::Uint32 () [inline], [static], [constexpr]
Definition at line 1324 of file maglev-ir.h.
                                         {
    return OpProperties(
        kValueRepresentationBits::encode(ValueRepresentation::kUint32));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::maglev::kUint32, and OpProperties().
value_representation()
constexpr ValueRepresentation v8::internal::maglev::OpProperties::value_representation () const [inline], [constexpr]
Definition at line 1247 of file maglev-ir.h.
                                                             {
    return kValueRepresentationBits::decode(bitfield_);
  }
References bitfield_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull(), v8::internal::maglev::CheckValueInputIs(), v8::internal::maglev::MaglevGraphBuilder::ConvertInputTo(), v8::internal::maglev::MaglevGraphBuilder::GetInt32ElementIndex(), v8::internal::maglev::MaglevGraphBuilder::GetUint32ElementIndex(), is_tagged(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves(), v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCompareEqualAgainstConstant(), v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse(), and v8::internal::maglev::ValueNode::value_representation().
WithNewValueRepresentation()
OpProperties v8::internal::maglev::OpProperties::WithNewValueRepresentation (ValueRepresentation new_repr) const [inline]
Definition at line 1376 of file maglev-ir.h.
                                                                              {
    return OpProperties(kValueRepresentationBits::update(bitfield_, new_repr));
  }
References bitfield_, OpProperties(), and v8::base::BitField< T, shift, size, U >::update().
WithoutDeopt()
OpProperties v8::internal::maglev::OpProperties::WithoutDeopt () const [inline]
Definition at line 1380 of file maglev-ir.h.
                                    {
    return OpProperties(
        kAttachedDeoptInfoBits::update(bitfield_, AttachedDeoptInfo::kNone));
  }
References bitfield_, kNone, OpProperties(), and v8::base::BitField< T, shift, size, U >::update().
Member Data Documentation
bitfield_
const uint32_t v8::internal::maglev::OpProperties::bitfield_ [private]
Definition at line 1413 of file maglev-ir.h.
Referenced by can_allocate(), can_eager_deopt(), can_lazy_deopt(), can_read(), can_throw(), can_write(), is_call(), is_conversion(), is_deferred_call(), is_deopt_checkpoint(), is_pure(), needs_register_snapshot(), not_idempotent(), operator uint32_t(), operator|(), value_representation(), WithNewValueRepresentation(), and WithoutDeopt().
kPureMask
const uint32_t v8::internal::maglev::OpProperties::kPureMask [static], [private]
Initial value:
=
      kCanReadBit::kMask | kCanWriteBit::kMask | kCanAllocateBit::kMask
Definition at line 1399 of file maglev-ir.h.
Referenced by is_pure().
kPureValue
const uint32_t v8::internal::maglev::OpProperties::kPureValue [static], [private]
Initial value:
= kCanReadBit::encode(false) |
                                     kCanWriteBit::encode(false) |
                                     kCanAllocateBit::encode(false)
Definition at line 1401 of file maglev-ir.h.
Referenced by is_pure(), and Pure().
kSize
const size_t v8::internal::maglev::OpProperties::kSize = kNeedsRegisterSnapshotBit::kLastUsedBit + 1 [static]
Definition at line 1416 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h