v8::internal::compiler::FastApiCallReducerAssembler Class Reference
Public Member Functions
FastApiCallReducerAssembler (JSCallReducer *reducer, Node *node, const FunctionTemplateInfoRef function_template_info, FastApiCallFunction c_function, Node *receiver, const SharedFunctionInfoRef shared, Node *target, const int arity, Node *effect)
TNode< Object > ReduceFastApiCall ()
Private Member Functions
TNode< Object > FastApiCall (CallDescriptor *descriptor, Node **inputs, size_t inputs_size)
Private Attributes
FastApiCallFunction c_function_
const FunctionTemplateInfoRef function_template_info_
Node *const receiver_
const SharedFunctionInfoRef shared_
Node *const target_
const int arity_
Static Private Attributes
static constexpr int kEffectAndControl = 2
static constexpr int kSlowBuiltinParams = 4
static constexpr int kReceiver = 1
static constexpr int kInlineSize = 16
Additional Inherited Members
Detailed Description
Definition at line 636 of file js-call-reducer.cc.
Constructor & Destructor Documentation
FastApiCallReducerAssembler()
v8::internal::compiler::FastApiCallReducerAssembler::FastApiCallReducerAssembler (JSCallReducer * reducer, Node * node, const FunctionTemplateInfoRef function_template_info, FastApiCallFunction c_function, Node * receiver, const SharedFunctionInfoRef shared, Node * target, const int arity, Node * effect) [inline]
Definition at line 638 of file js-call-reducer.cc.
      : JSCallReducerAssembler(reducer, node),
        c_function_(c_function),
        function_template_info_(function_template_info),
        receiver_(receiver),
        shared_(shared),
        target_(target),
        arity_(arity) {
    DCHECK_EQ(IrOpcode::kJSCall, node->opcode());
    InitializeEffectControl(effect, NodeProperties::GetControlInput(node));
  }
References DCHECK_EQ, v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
FastApiCall()
TNode<Object> v8::internal::compiler::FastApiCallReducerAssembler::FastApiCall (CallDescriptor * descriptor, Node ** inputs, size_t inputs_size) [inline], [private]
Definition at line 775 of file js-call-reducer.cc.
                                                {
    return AddNode<Object>(graph()->NewNode(
        simplified()->FastApiCall(c_function_, feedback(), descriptor),
        static_cast<int>(inputs_size), inputs));
  }
References c_function_, v8::internal::compiler::JSCallReducerAssembler::feedback(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::JSGraphAssembler::simplified().
Referenced by ReduceFastApiCall().
ReduceFastApiCall()
TNode<Object> v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall () [inline]
Definition at line 655 of file js-call-reducer.cc.
                                    {
    JSCallNode n(node_ptr());
    // C arguments include the receiver at index 0. Thus C index 1 corresponds
    // to the JS argument 0, etc.
    // All functions in c_candidate_functions_ have the same number of
    // arguments, so extract c_argument_count from the first function.
    const int c_argument_count =
        static_cast<int>(c_function_.signature->ArgumentCount());
    CHECK_GE(c_argument_count, kReceiver);
    const int slow_arg_count =
        // Arguments for CallApiCallbackOptimizedXXX builtin including
        // context, see CallApiCallbackOptimizedDescriptor.
        kSlowBuiltinParams +
        // JS arguments.
        kReceiver + arity_;
    const int value_input_count =
        FastApiCallNode::ArityForArgc(c_argument_count, slow_arg_count);
    base::SmallVector<Node*, kInlineSize> inputs(value_input_count +
                                                 kEffectAndControl);
    int cursor = 0;
    inputs[cursor++] = n.receiver();
    // TODO(turbofan): Consider refactoring CFunctionInfo to distinguish
    // between receiver and arguments, simplifying this (and related) spots.
    int js_args_count = c_argument_count - kReceiver;
    for (int i = 0; i < js_args_count; ++i) {
      if (i < n.ArgumentCount()) {
        inputs[cursor++] = n.Argument(i);
      } else {
        inputs[cursor++] = UndefinedConstant();
      }
    }
    // Here we add the arguments for the slow call, which will be
    // reconstructed at a later phase. Those are effectively the same
    // arguments as for the fast call, but we want to have them as
    // separate inputs, so that SimplifiedLowering can provide the best
    // possible UseInfos for each of them. The inputs to FastApiCall
    // look like:
    // [receiver, ... C arguments, callback data,
    // slow call code, external constant for function, argc,
    // FunctionTemplateInfo, holder, receiver, ... JS arguments,
    // context, new frame state].
    bool no_profiling =
        broker()->dependencies()->DependOnNoProfilingProtector();
    Callable call_api_callback = Builtins::CallableFor(
        isolate(), no_profiling ? Builtin::kCallApiCallbackOptimizedNoProfiling
                                : Builtin::kCallApiCallbackOptimized);
    CallInterfaceDescriptor cid = call_api_callback.descriptor();
    DCHECK_EQ(cid.GetParameterCount() + (cid.HasContextParameter() ? 1 : 0),
              kSlowBuiltinParams);
    CallDescriptor* call_descriptor =
        Linkage::GetStubCallDescriptor(graph()->zone(), cid, arity_ + kReceiver,
                                       CallDescriptor::kNeedsFrameState);
    ApiFunction api_function(function_template_info_.callback(broker()));
    ExternalReference function_reference = ExternalReference::Create(
        isolate(), &api_function, ExternalReference::DIRECT_API_CALL,
        function_template_info_.c_functions(broker()).data(),
        function_template_info_.c_signatures(broker()).data(),
        static_cast<unsigned>(
            function_template_info_.c_functions(broker()).size()));
    // LINT.IfChange
    // TODO(crbug.com/418936518): Support deopt for functions with return value.
    Node* error_message = jsgraph()->SmiConstant(
        static_cast<int>(AbortReason::kUnsupportedDeopt));
    Node* continuation_frame_state =
        c_function_.signature->ReturnInfo().GetType() == CTypeInfo::Type::kVoid
            ? CreateInlinedApiFunctionFrameState(jsgraph(), shared_, target_,
                                                 ContextInput(), receiver_,
                                                 FrameStateInput())
            : CreateStubBuiltinContinuationFrameState(
                  jsgraph(), Builtin::kAbort, ContextInput(), &error_message, 1,
                  FrameStateInput(), ContinuationFrameStateMode::LAZY);
    // The `DeoptimizationEntry_LazyAfterFastCall` builtin currently sets the
    // return value unconditionally to `undefined`. If a continuation builtin is
    // set up here, then the entry builtin should not overwrite the return
    // value.
    // LINT.ThenChange(/src/builtins/x64/builtins-x64.cc:DeoptAfterFastCallSetReturnValue)
    // Callback data value for fast Api calls. Unlike slow Api calls, the fast
    // variant passes callback data directly.
    inputs[cursor++] =
        Constant(function_template_info_.callback_data(broker()).value());
    inputs[cursor++] = HeapConstant(call_api_callback.code());
    inputs[cursor++] = ExternalConstant(function_reference);
    inputs[cursor++] = NumberConstant(arity_);
    inputs[cursor++] = HeapConstant(function_template_info_.object());
    inputs[cursor++] = receiver_;
    for (int i = 0; i < arity_; ++i) {
      inputs[cursor++] = Argument(i);
    }
    inputs[cursor++] = ContextInput();
    inputs[cursor++] = continuation_frame_state;
    inputs[cursor++] = effect();
    inputs[cursor++] = control();
    DCHECK_EQ(cursor, value_input_count + kEffectAndControl);
    return FastApiCall(call_descriptor, inputs.begin(), inputs.size());
  }
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSCallReducerAssembler::Argument(), v8::CFunctionInfo::ArgumentCount(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::ArgumentCount(), arity_, v8::internal::compiler::FastApiCallNode::ArityForArgc(), v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::compiler::JSGraphAssembler::broker(), c_function_, v8::internal::compiler::FunctionTemplateInfoRef::c_functions(), v8::internal::compiler::FunctionTemplateInfoRef::c_signatures(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::FunctionTemplateInfoRef::callback(), v8::internal::compiler::FunctionTemplateInfoRef::callback_data(), CHECK_GE, v8::internal::Callable::code(), v8::internal::compiler::JSGraphAssembler::Constant(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::GraphAssembler::control(), v8::internal::ExternalReference::Create(), v8::internal::compiler::CreateInlinedApiFunctionFrameState(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), DCHECK_EQ, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnNoProfilingProtector(), v8::internal::Callable::descriptor(), v8::internal::ExternalReference::DIRECT_API_CALL, v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::ExternalConstant(), FastApiCall(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), function_template_info_, v8::internal::CallInterfaceDescriptor::GetParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::CTypeInfo::GetType(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::CallInterfaceDescriptor::HasContextParameter(), v8::internal::compiler::JSGraphAssembler::HeapConstant(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::JSGraphAssembler::isolate(), v8::internal::compiler::JSGraphAssembler::jsgraph(), kEffectAndControl, v8::internal::compiler::CallDescriptor::kNeedsFrameState, kReceiver, kSlowBuiltinParams, v8::CTypeInfo::kVoid, v8::internal::compiler::LAZY, v8::internal::compiler::JSCallReducerAssembler::node_ptr(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::compiler::FunctionTemplateInfoRef::object(), receiver_, v8::CFunctionInfo::ReturnInfo(), shared_, v8::internal::compiler::FastApiCallFunction::signature, v8::base::SmallVector< T, kSize, Allocator >::size(), size(), v8::internal::compiler::JSGraph::SmiConstant(), target_, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallApiFunction().
Member Data Documentation
arity_
const int v8::internal::compiler::FastApiCallReducerAssembler::arity_ [private]
Definition at line 787 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
c_function_
FastApiCallFunction v8::internal::compiler::FastApiCallReducerAssembler::c_function_ [private]
Definition at line 782 of file js-call-reducer.cc.
Referenced by FastApiCall(), and ReduceFastApiCall().
function_template_info_
const FunctionTemplateInfoRef v8::internal::compiler::FastApiCallReducerAssembler::function_template_info_ [private]
Definition at line 783 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
kEffectAndControl
constexpr int v8::internal::compiler::FastApiCallReducerAssembler::kEffectAndControl = 2 [static], [constexpr], [private]
Definition at line 765 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
kInlineSize
constexpr int v8::internal::compiler::FastApiCallReducerAssembler::kInlineSize = 16 [static], [constexpr], [private]
Definition at line 773 of file js-call-reducer.cc.
kReceiver
constexpr int v8::internal::compiler::FastApiCallReducerAssembler::kReceiver = 1 [static], [constexpr], [private]
Definition at line 770 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
kSlowBuiltinParams
constexpr int v8::internal::compiler::FastApiCallReducerAssembler::kSlowBuiltinParams = 4 [static], [constexpr], [private]
Definition at line 769 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
receiver_
Node* const v8::internal::compiler::FastApiCallReducerAssembler::receiver_ [private]
Definition at line 784 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
shared_
const SharedFunctionInfoRef v8::internal::compiler::FastApiCallReducerAssembler::shared_ [private]
Definition at line 785 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
target_
Node* const v8::internal::compiler::FastApiCallReducerAssembler::target_ [private]
Definition at line 786 of file js-call-reducer.cc.
Referenced by ReduceFastApiCall().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc