v8::internal::ContextSerializer Class Reference
#include <context-serializer.h>
Public Member Functions
ContextSerializer (Isolate *isolate, Snapshot::SerializerFlags flags, StartupSerializer *startup_serializer, SerializeEmbedderFieldsCallback callback)
~ContextSerializer () override
ContextSerializer (const ContextSerializer &)=delete
ContextSerializer & operator= (const ContextSerializer &)=delete
void Serialize (Tagged< Context > *o, const DisallowGarbageCollection &no_gc)
bool can_be_rehashed () const
Private Member Functions
void SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) override
bool ShouldBeInTheStartupObjectCache (Tagged< HeapObject > o)
bool ShouldBeInTheSharedObjectCache (Tagged< HeapObject > o)
void CheckRehashability (Tagged< HeapObject > obj)
template<typename V8Type , typename UserSerializerWrapper , typename UserCallback , typename ApiObjectType >
void SerializeObjectWithEmbedderFields (Handle< V8Type > data_holder, int embedder_fields_count, UserSerializerWrapper wrapper, UserCallback user_callback, ApiObjectType api_obj)
void SerializeApiWrapperFields (DirectHandle< JSObject > js_object)
Private Attributes
StartupSerializer * startup_serializer_
SerializeEmbedderFieldsCallback serialize_embedder_fields_
bool can_be_rehashed_
Tagged< Context > context_
SnapshotByteSink embedder_fields_sink_
SnapshotByteSink api_wrapper_sink_
Additional Inherited Members
Detailed Description
Definition at line 17 of file context-serializer.h.
Constructor & Destructor Documentation
ContextSerializer() [1/2]
v8::internal::ContextSerializer::ContextSerializer (Isolate * isolate, Snapshot::SerializerFlags flags, StartupSerializer * startup_serializer, SerializeEmbedderFieldsCallback callback)
Definition at line 68 of file context-serializer.cc.
    : Serializer(isolate, flags),
      startup_serializer_(startup_serializer),
      serialize_embedder_fields_(callback),
      can_be_rehashed_(true) {
  InitializeCodeAddressMap();
}
References v8::internal::Serializer::InitializeCodeAddressMap().
 ContextSerializer()
v8::internal::ContextSerializer::~ContextSerializer () [override]
Definition at line 79 of file context-serializer.cc.
                                      {
  OutputStatistics("ContextSerializer");
}
References v8::internal::Serializer::OutputStatistics().
ContextSerializer() [2/2]
v8::internal::ContextSerializer::ContextSerializer (const ContextSerializer &) [delete]
Member Function Documentation
can_be_rehashed()
bool v8::internal::ContextSerializer::can_be_rehashed () const [inline]
Definition at line 30 of file context-serializer.h.
{ return can_be_rehashed_; }
Referenced by v8::internal::Snapshot::Create().
CheckRehashability()
void v8::internal::ContextSerializer::CheckRehashability (Tagged< HeapObject > obj) [private]
Definition at line 405 of file context-serializer.cc.
                                                                 {
  if (!can_be_rehashed_) return;
  if (!obj->NeedsRehashing(cage_base())) return;
  if (obj->CanBeRehashed(cage_base())) return;
  can_be_rehashed_ = false;
}
References v8::internal::Serializer::cage_base(), and can_be_rehashed_.
Referenced by SerializeObjectImpl().
operator=()
ContextSerializer& v8::internal::ContextSerializer::operator= (const ContextSerializer &) [delete]
Serialize()
void v8::internal::ContextSerializer::Serialize (Tagged< Context > * o, const DisallowGarbageCollection & no_gc)
Definition at line 83 of file context-serializer.cc.
                                                                          {
  context_ = *o;
  DCHECK(IsNativeContext(context_));
  // Upon deserialization, references to the global proxy and its map will be
  // replaced.
  reference_map()->AddAttachedReference(context_->global_proxy());
  reference_map()->AddAttachedReference(context_->global_proxy()->map());
  // The bootstrap snapshot has a code-stub context. When serializing the
  // context snapshot, it is chained into the weak context list on the isolate
  // and it's next context pointer may point to the code-stub context. Clear
  // it before serializing, it will get re-added to the context list
  // explicitly when it's loaded.
  // TODO(v8:10416): These mutations should not observably affect the running
  // context.
  context_->SetNoCell(Context::NEXT_CONTEXT_LINK,
                      ReadOnlyRoots(isolate()).undefined_value());
  DCHECK(!IsUndefined(context_->global_object()));
  // Reset math random cache to get fresh random numbers.
  MathRandom::ResetContext(context_);
  SanitizeNativeContextScope sanitize_native_context(
      isolate(), context_->native_context(), allow_active_isolate_for_testing(),
      no_gc);
  VisitRootPointer(Root::kStartupObjectCache, nullptr, FullObjectSlot(o));
  SerializeDeferredObjects();
  // Add section for embedder-serialized embedder fields.
  if (!embedder_fields_sink_.data()->empty()) {
    sink_.Put(kEmbedderFieldsData, "embedder fields data");
    sink_.Append(embedder_fields_sink_);
    sink_.Put(kSynchronize, "Finished with embedder fields data");
  }
  // Add section for embedder-serializer API wrappers.
  if (!api_wrapper_sink_.data()->empty()) {
    sink_.Put(kApiWrapperFieldsData, "api wrapper fields data");
    sink_.Append(api_wrapper_sink_);
    sink_.Put(kSynchronize, "Finished with api wrapper fields data");
  }
  Pad();
}
References v8::internal::SerializerReferenceMap::AddAttachedReference(), v8::internal::Serializer::allow_active_isolate_for_testing(), api_wrapper_sink_, v8::internal::SnapshotByteSink::Append(), context_, v8::internal::SnapshotByteSink::data(), v8::internal::DCHECK(), embedder_fields_sink_, v8::internal::Serializer::isolate(), v8::internal::SerializerDeserializer::kApiWrapperFieldsData, v8::internal::SerializerDeserializer::kEmbedderFieldsData, v8::internal::SerializerDeserializer::kSynchronize, v8::internal::Context::NEXT_CONTEXT_LINK, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::Pad(), v8::internal::SnapshotByteSink::Put(), v8::internal::Serializer::reference_map(), v8::internal::MathRandom::ResetContext(), v8::internal::Serializer::SerializeDeferredObjects(), v8::internal::Serializer::sink_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Snapshot::Create().
SerializeApiWrapperFields()
void v8::internal::ContextSerializer::SerializeApiWrapperFields (DirectHandle< JSObject > js_object) [private]
Definition at line 288 of file context-serializer.cc.
                                      {
  DCHECK(IsJSApiWrapperObject(*js_object));
  auto* cpp_heap_pointer =
      CppHeapObjectWrapper(*js_object)
          .GetCppHeapWrappable(isolate(), kAnyCppHeapPointer);
  const auto& callback_data = serialize_embedder_fields_.api_wrapper_callback;
  if (callback_data.callback == nullptr && cpp_heap_pointer == nullptr) {
    // No need to serialize anything as empty handles or handles pointing to
    // null objects will be preserved.
    return;
  }
  DCHECK_NOT_NULL(callback_data.callback);
  const auto data = callback_data.callback(
      v8::Utils::ToLocal(js_object), cpp_heap_pointer, callback_data.data);
  if (DataIsEmpty(data)) {
    return;
  }
  const SerializerReference* reference =
      reference_map()->LookupReference(*js_object);
  DCHECK_NOT_NULL(reference);
  DCHECK(reference->is_back_reference());
  api_wrapper_sink_.Put(kNewObject, "api wrapper field holder");
  api_wrapper_sink_.PutUint30(reference->back_ref_index(), "BackRefIndex");
  api_wrapper_sink_.PutUint30(data.raw_size, "api wrapper raw field data size");
  api_wrapper_sink_.PutRaw(reinterpret_cast<const uint8_t*>(data.data),
                           data.raw_size, "api wrapper raw field data");
}
References v8::internal::SerializeEmbedderFieldsCallback::api_wrapper_callback, api_wrapper_sink_, v8::internal::SerializerReference::back_ref_index(), v8::internal::anonymous_namespace{context-serializer.cc}::DataIsEmpty(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable(), v8::internal::SerializerReference::is_back_reference(), v8::internal::InstanceTypeChecker::IsJSApiWrapperObject(), v8::internal::Serializer::isolate(), v8::kAnyCppHeapPointer(), v8::internal::SerializerDeserializer::kNewObject, v8::internal::SerializerReferenceMap::LookupReference(), v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::Serializer::reference_map(), and serialize_embedder_fields_.
Referenced by SerializeObjectImpl().
SerializeObjectImpl()
void v8::internal::ContextSerializer::SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) [override], [private], [virtual]
Implements v8::internal::Serializer.
Definition at line 159 of file context-serializer.cc.
                                                                {
  DCHECK(!ObjectIsBytecodeHandler(*obj)); // Only referenced in dispatch table.
  if (!allow_active_isolate_for_testing()) {
    // When serializing a snapshot intended for real use, we should not end up
    // at another native context.
    // But in test scenarios there is no way to avoid this. Since we only
    // serialize a single context in these cases, and this context does not
    // have to be executable, we can simply ignore this.
    DCHECK_IMPLIES(IsNativeContext(*obj), *obj == context_);
  }
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> raw = *obj;
    if (SerializeHotObject(raw)) return;
    if (SerializeRoot(raw)) return;
    if (SerializeBackReference(raw)) return;
    if (SerializeReadOnlyObjectReference(raw, &sink_)) return;
  }
  if (startup_serializer_->SerializeUsingSharedHeapObjectCache(&sink_, obj)) {
    return;
  }
  if (ShouldBeInTheStartupObjectCache(*obj)) {
    startup_serializer_->SerializeUsingStartupObjectCache(&sink_, obj);
    return;
  }
  // Pointers from the context snapshot to the objects in the startup snapshot
  // should go through the root array or through the startup object cache.
  // If this is not the case you may have to add something to the root array.
  DCHECK(!startup_serializer_->ReferenceMapContains(obj));
  // All the internalized strings that the context snapshot needs should be
  // either in the root table or in the shared heap object cache.
  DCHECK(!IsInternalizedString(*obj));
  // Function and object templates are not context specific.
  DCHECK(!IsTemplateInfo(*obj));
  InstanceType instance_type = obj->map()->instance_type();
  if (InstanceTypeChecker::IsFeedbackVector(instance_type)) {
    // Clear literal boilerplates and feedback.
    Cast<FeedbackVector>(obj)->ClearSlots(isolate());
  } else if (InstanceTypeChecker::IsJSObject(instance_type)) {
    Handle<JSObject> js_obj = Cast<JSObject>(obj);
    int embedder_fields_count = js_obj->GetEmbedderFieldCount();
    if (embedder_fields_count > 0) {
      DCHECK(!js_obj->NeedsRehashing(cage_base()));
      v8::Local<v8::Object> api_obj = v8::Utils::ToLocal(js_obj);
      v8::SerializeInternalFieldsCallback user_callback =
          serialize_embedder_fields_.js_object_callback;
      SerializeObjectWithEmbedderFields(js_obj, embedder_fields_count,
                                        InternalFieldSerializeWrapper,
                                        user_callback, api_obj);
      if (IsJSApiWrapperObject(*js_obj)) {
        SerializeApiWrapperFields(js_obj);
      }
      return;
    }
    if (InstanceTypeChecker::IsJSFunction(instance_type)) {
      DisallowGarbageCollection no_gc;
      // Unconditionally reset the JSFunction to its SFI's code, since we can't
      // serialize optimized code anyway.
      Tagged<JSFunction> closure = Cast<JSFunction>(*obj);
      if (closure->shared()->HasBytecodeArray()) {
        closure->SetInterruptBudget(isolate(), BudgetModification::kReset);
      }
      closure->ResetIfCodeFlushed(isolate());
      if (closure->is_compiled(isolate())) {
        if (closure->shared()->HasBaselineCode()) {
          closure->shared()->FlushBaselineCode();
        }
        Tagged<Code> sfi_code = closure->shared()->GetCode(isolate());
        if (!sfi_code.SafeEquals(closure->code(isolate()))) {
          closure->UpdateCode(isolate(), sfi_code);
        }
      }
    }
  } else if (InstanceTypeChecker::IsEmbedderDataArray(instance_type) &&
             !allow_active_isolate_for_testing()) {
    DCHECK_EQ(*obj, context_->embedder_data());
    Handle<EmbedderDataArray> embedder_data = Cast<EmbedderDataArray>(obj);
    int embedder_fields_count = embedder_data->length();
    if (embedder_data->length() > 0) {
      DirectHandle<Context> context_handle(context_, isolate());
      v8::Local<v8::Context> api_obj =
          v8::Utils::ToLocal(Cast<NativeContext>(context_handle));
      v8::SerializeContextDataCallback user_callback =
          serialize_embedder_fields_.context_callback;
      SerializeObjectWithEmbedderFields(embedder_data, embedder_fields_count,
                                        ContextDataSerializeWrapper,
                                        user_callback, api_obj);
      return;
    }
  }
  CheckRehashability(*obj);
  // Object has not yet been serialized. Serialize it here.
  ObjectSerializer serializer(this, obj, &sink_);
  serializer.Serialize(slot_type);
  if (InstanceTypeChecker::IsJSApiWrapperObject(instance_type)) {
    SerializeApiWrapperFields(Cast<JSObject>(obj));
  }
}
References v8::internal::Serializer::allow_active_isolate_for_testing(), v8::internal::Serializer::cage_base(), CheckRehashability(), context_, v8::internal::SerializeEmbedderFieldsCallback::context_callback, v8::internal::ContextDataSerializeWrapper(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::InternalFieldSerializeWrapper(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::InstanceTypeChecker::IsJSApiWrapperObject(), v8::internal::Serializer::isolate(), v8::internal::SerializeEmbedderFieldsCallback::js_object_callback, v8::internal::kReset, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::ObjectIsBytecodeHandler(), v8::internal::Serializer::ReferenceMapContains(), v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals(), v8::internal::Serializer::ObjectSerializer::Serialize(), serialize_embedder_fields_, SerializeApiWrapperFields(), v8::internal::Serializer::SerializeBackReference(), v8::internal::Serializer::SerializeHotObject(), SerializeObjectWithEmbedderFields(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::Serializer::SerializeRoot(), v8::internal::StartupSerializer::SerializeUsingSharedHeapObjectCache(), v8::internal::StartupSerializer::SerializeUsingStartupObjectCache(), ShouldBeInTheStartupObjectCache(), v8::internal::Serializer::sink_, and startup_serializer_.
SerializeObjectWithEmbedderFields()
template<typename V8Type , typename UserSerializerWrapper , typename UserCallback , typename ApiObjectType >
void v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields (Handle< V8Type > data_holder, int embedder_fields_count, UserSerializerWrapper wrapper, UserCallback user_callback, ApiObjectType api_obj) [private]
Definition at line 319 of file context-serializer.cc.
                           {
  DisallowGarbageCollection no_gc;
  CHECK_GT(embedder_fields_count, 0);
  DisallowJavascriptExecution no_js(isolate());
  DisallowCompilation no_compile(isolate());
  auto raw_obj = *data_holder;
  std::vector<EmbedderDataSlot::RawData> original_embedder_values;
  std::vector<StartupData> serialized_data;
  std::vector<bool> should_clear_slot;
  // 1) Iterate embedder fields. Hold onto the original value of the fields.
  // Ignore references to heap objects since these are to be handled by the
  // serializer. For aligned pointers, call the serialize callback. Hold
  // onto the result.
  for (int i = 0; i < embedder_fields_count; i++) {
    EmbedderDataSlot slot(raw_obj, i);
    original_embedder_values.emplace_back(slot.load_raw(isolate(), no_gc));
    Tagged<Object> object = slot.load_tagged();
    if (IsHeapObject(object)) {
      DCHECK(IsValidHeapObject(isolate()->heap(), Cast<HeapObject>(object)));
      serialized_data.push_back({nullptr, 0});
      should_clear_slot.push_back(false);
    } else {
      StartupData data =
          wrapper(i, object == Smi::zero(), user_callback, api_obj);
      serialized_data.push_back(data);
      bool clear_slot =
          !DataIsEmpty(data) || slot.MustClearDuringSerialization(no_gc);
      should_clear_slot.push_back(clear_slot);
    }
  }
  // 2) Prevent embedder fields that are not V8 objects from ending up in the
  // blob. This is done separately to step 1 so as to not interleave with
  // embedder callbacks.
  for (int i = 0; i < embedder_fields_count; i++) {
    if (should_clear_slot[i]) {
      EmbedderDataSlot(raw_obj, i).store_raw(isolate(), kNullAddress, no_gc);
    }
  }
  // 3) Serialize the object. References from embedder fields to heap objects or
  // smis are serialized regularly.
  {
    AllowGarbageCollection allow_gc;
    ObjectSerializer(this, data_holder, &sink_).Serialize(SlotType::kAnySlot);
    // Reload raw pointer.
    raw_obj = *data_holder;
  }
  // 4) Obtain back reference for the serialized object.
  const SerializerReference* reference =
      reference_map()->LookupReference(raw_obj);
  DCHECK_NOT_NULL(reference);
  DCHECK(reference->is_back_reference());
  // 5) Write data returned by the embedder callbacks into a separate sink,
  // headed by the back reference. Restore the original embedder fields.
  for (int i = 0; i < embedder_fields_count; i++) {
    StartupData data = serialized_data[i];
    if (!should_clear_slot[i]) continue;
    // Restore original values from cleared fields.
    EmbedderDataSlot(raw_obj, i)
        .store_raw(isolate(), original_embedder_values[i], no_gc);
    if (DataIsEmpty(data)) continue;
    embedder_fields_sink_.Put(kNewObject, "embedder field holder");
    embedder_fields_sink_.PutUint30(reference->back_ref_index(),
                                    "BackRefIndex");
    embedder_fields_sink_.PutUint30(i, "embedder field index");
    embedder_fields_sink_.PutUint30(data.raw_size, "embedder fields data size");
    embedder_fields_sink_.PutRaw(reinterpret_cast<const uint8_t*>(data.data),
                                 data.raw_size, "embedder fields data");
    delete[] data.data;
  }
  // 6) The content of the separate sink is appended eventually to the default
  // sink. The ensures that during deserialization, we call the deserializer
  // callback at the end, and can guarantee that the deserialized objects are
  // in a consistent state. See ContextSerializer::Serialize.
}
References v8::internal::SerializerReference::back_ref_index(), CHECK_GT, v8::StartupData::data, v8::internal::anonymous_namespace{context-serializer.cc}::DataIsEmpty(), v8::internal::DCHECK(), DCHECK_NOT_NULL, embedder_fields_sink_, heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::SerializerReference::is_back_reference(), v8::internal::IsHeapObject(), v8::internal::Serializer::isolate(), v8::internal::IsValidHeapObject(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SerializerDeserializer::kNewObject, v8::internal::kNullAddress, v8::internal::EmbedderDataSlot::load_raw(), v8::internal::EmbedderDataSlot::load_tagged(), v8::internal::SerializerReferenceMap::LookupReference(), v8::internal::EmbedderDataSlot::MustClearDuringSerialization(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), v8::internal::SnapshotByteSink::PutUint30(), v8::StartupData::raw_size, v8::internal::Serializer::reference_map(), v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::Serializer::sink_, v8::internal::EmbedderDataSlot::store_raw(), and v8::internal::Smi::zero().
Referenced by SerializeObjectImpl().
ShouldBeInTheSharedObjectCache()
bool v8::internal::ContextSerializer::ShouldBeInTheSharedObjectCache (Tagged< HeapObject > o) [private]
Definition at line 278 of file context-serializer.cc.
                                                                           {
  // v8_flags.shared_string_table may be true during deserialization, so put
  // internalized strings into the shared object snapshot.
  return IsInternalizedString(o);
}
References v8::internal::InstanceTypeChecker::IsInternalizedString().
ShouldBeInTheStartupObjectCache()
bool v8::internal::ContextSerializer::ShouldBeInTheStartupObjectCache (Tagged< HeapObject > o) [private]
Definition at line 267 of file context-serializer.cc.
                                                                            {
  // We can't allow scripts to be part of the context snapshot because they
  // contain a unique ID, and deserializing several context snapshots containing
  // script would cause dupes.
  return IsName(o) || IsScript(o) || IsSharedFunctionInfo(o) ||
         IsHeapNumber(o) || IsCode(o) || IsInstructionStream(o) ||
         IsScopeInfo(o) || IsAccessorInfo(o) || IsTemplateInfo(o) ||
         IsClassPositions(o) ||
         o->map() == ReadOnlyRoots(isolate()).fixed_cow_array_map();
}
References v8::internal::Serializer::isolate().
Referenced by SerializeObjectImpl().
Member Data Documentation
api_wrapper_sink_
SnapshotByteSink v8::internal::ContextSerializer::api_wrapper_sink_ [private]
Definition at line 60 of file context-serializer.h.
Referenced by Serialize(), and SerializeApiWrapperFields().
can_be_rehashed_
bool v8::internal::ContextSerializer::can_be_rehashed_ [private]
Definition at line 54 of file context-serializer.h.
Referenced by CheckRehashability().
context_
Tagged<Context> v8::internal::ContextSerializer::context_ [private]
Definition at line 55 of file context-serializer.h.
Referenced by Serialize(), and SerializeObjectImpl().
embedder_fields_sink_
SnapshotByteSink v8::internal::ContextSerializer::embedder_fields_sink_ [private]
Definition at line 58 of file context-serializer.h.
Referenced by Serialize(), and SerializeObjectWithEmbedderFields().
serialize_embedder_fields_
SerializeEmbedderFieldsCallback v8::internal::ContextSerializer::serialize_embedder_fields_ [private]
Definition at line 51 of file context-serializer.h.
Referenced by SerializeApiWrapperFields(), and SerializeObjectImpl().
startup_serializer_
StartupSerializer* v8::internal::ContextSerializer::startup_serializer_ [private]
Definition at line 50 of file context-serializer.h.
Referenced by SerializeObjectImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/context-serializer.h
/mnt/V8SourceCode/src/snapshot/context-serializer.cc