v8::internal::ro::BitSet Class Reference
#include <read-only-serializer-deserializer.h>
Public Member Functions
BitSet (size_t size_in_bits)
BitSet (uint8_t *data, size_t size_in_bits)
~BitSet ()
bool contains (int i) const
void set (int i)
size_t size_in_bits () const
size_t size_in_bytes () const
const uint8_t * data () const
Static Private Member Functions
static constexpr int chunk_index (int i)
static constexpr int bit_index (int i)
static constexpr uint32_t bit_mask (int i)
Private Attributes
const size_t size_in_bits_
uint8_t *const data_
const bool owns_data_
Static Private Attributes
static constexpr int kBitsPerChunk = kUInt8Size * kBitsPerByte
Detailed Description
Definition at line 48 of file read-only-serializer-deserializer.h.
Constructor & Destructor Documentation
BitSet() [1/2]
v8::internal::ro::BitSet::BitSet (size_t size_in_bits) [inline], [explicit]
Definition at line 50 of file read-only-serializer-deserializer.h.
      : size_in_bits_(size_in_bits),
        data_(new uint8_t[size_in_bytes()]()),
        owns_data_(true) {}
BitSet() [2/2]
v8::internal::ro::BitSet::BitSet (uint8_t * data, size_t size_in_bits) [inline], [explicit]
Definition at line 55 of file read-only-serializer-deserializer.h.
      : size_in_bits_(size_in_bits), data_(data), owns_data_(false) {}
 BitSet()
v8::internal::ro::BitSet::~BitSet () [inline]
Definition at line 58 of file read-only-serializer-deserializer.h.
            {
    if (owns_data_) delete[] data_;
  }
References data_, and owns_data_.
Member Function Documentation
bit_index()
static constexpr int v8::internal::ro::BitSet::bit_index (int i) [inline], [static], [constexpr], [private]
Definition at line 82 of file read-only-serializer-deserializer.h.
{ return i % kBitsPerChunk; }
References kBitsPerChunk.
Referenced by bit_mask().
bit_mask()
static constexpr uint32_t v8::internal::ro::BitSet::bit_mask (int i) [inline], [static], [constexpr], [private]
Definition at line 83 of file read-only-serializer-deserializer.h.
{ return 1 << bit_index(i); }
References bit_index().
Referenced by contains(), and set().
chunk_index()
static constexpr int v8::internal::ro::BitSet::chunk_index (int i) [inline], [static], [constexpr], [private]
Definition at line 81 of file read-only-serializer-deserializer.h.
{ return i / kBitsPerChunk; }
References kBitsPerChunk.
Referenced by contains(), and set().
contains()
bool v8::internal::ro::BitSet::contains (int i) const [inline]
Definition at line 62 of file read-only-serializer-deserializer.h.
                             {
    DCHECK(0 <= i && i < static_cast<int>(size_in_bits_));
    return (data_[chunk_index(i)] & bit_mask(i)) != 0;
  }
References bit_mask(), chunk_index(), data_, v8::internal::DCHECK(), and size_in_bits_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DecodeTaggedSlots().
data()
const uint8_t* v8::internal::ro::BitSet::data () const [inline]
Definition at line 77 of file read-only-serializer-deserializer.h.
{ return data_; }
References data_.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
set()
void v8::internal::ro::BitSet::set (int i) [inline]
Definition at line 67 of file read-only-serializer-deserializer.h.
                  {
    DCHECK(0 <= i && i < static_cast<int>(size_in_bits_));
    data_[chunk_index(i)] |= bit_mask(i);
  }
References bit_mask(), chunk_index(), data_, v8::internal::DCHECK(), and size_in_bits_.
size_in_bits()
size_t v8::internal::ro::BitSet::size_in_bits () const [inline]
Definition at line 72 of file read-only-serializer-deserializer.h.
{ return size_in_bits_; }
References size_in_bits_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DecodeTaggedSlots().
size_in_bytes()
size_t v8::internal::ro::BitSet::size_in_bytes () const [inline]
Definition at line 73 of file read-only-serializer-deserializer.h.
                               {
    return RoundUp<kBitsPerByte>(size_in_bits_) / kBitsPerByte;
  }
References v8::internal::kBitsPerByte, and size_in_bits_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment().
Member Data Documentation
data_
uint8_t* const v8::internal::ro::BitSet::data_ [private]
Definition at line 86 of file read-only-serializer-deserializer.h.
Referenced by contains(), data(), set(), and ~BitSet().
kBitsPerChunk
constexpr int v8::internal::ro::BitSet::kBitsPerChunk = kUInt8Size * kBitsPerByte [static], [constexpr], [private]
Definition at line 80 of file read-only-serializer-deserializer.h.
Referenced by bit_index(), and chunk_index().
owns_data_
const bool v8::internal::ro::BitSet::owns_data_ [private]
Definition at line 87 of file read-only-serializer-deserializer.h.
Referenced by ~BitSet().
size_in_bits_
const size_t v8::internal::ro::BitSet::size_in_bits_ [private]
Definition at line 85 of file read-only-serializer-deserializer.h.
Referenced by contains(), set(), size_in_bits(), and size_in_bytes().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-serializer-deserializer.h