v8::internal::maglev::StraightForwardRegisterAllocator Class Reference
#include <maglev-regalloc.h>
Classes
struct BlockPatch
struct SpillSlotInfo
struct SpillSlots
Public Member Functions
StraightForwardRegisterAllocator (MaglevCompilationInfo *compilation_info, Graph *graph, RegallocInfo *regalloc_info)
~StraightForwardRegisterAllocator ()
Private Member Functions
void ComputePostDominatingHoles ()
void AllocateRegisters ()
void PrintLiveRegs () const
void UpdateUse (Input *input)
void UpdateUse (ValueNode *node, InputLocation *input_location)
void MarkAsClobbered (ValueNode *node, const compiler::AllocatedOperand &location)
void AllocateControlNode (ControlNode *node, BasicBlock *block)
void AllocateNode (Node *node)
void AllocateNodeResult (ValueNode *node)
void AllocateEagerDeopt (const EagerDeoptInfo &deopt_info)
void AllocateLazyDeopt (const LazyDeoptInfo &deopt_info)
void AssignFixedInput (Input &input)
void AssignArbitraryRegisterInput (NodeBase *result_node, Input &input)
void AssignAnyInput (Input &input)
void AssignInputs (NodeBase *node)
template<typename RegisterT >
void AssignFixedTemporaries (RegisterFrameState< RegisterT > &registers, NodeBase *node)
void AssignFixedTemporaries (NodeBase *node)
template<typename RegisterT >
void AssignArbitraryTemporaries (RegisterFrameState< RegisterT > &registers, NodeBase *node)
void AssignArbitraryTemporaries (NodeBase *node)
template<typename RegisterT >
void SetLoopPhiRegisterHint (Phi *phi, RegisterT reg)
void TryAllocateToInput (Phi *phi)
void VerifyInputs (NodeBase *node)
void VerifyRegisterState ()
void AddMoveBeforeCurrentNode (ValueNode *node, compiler::InstructionOperand source, compiler::AllocatedOperand target)
void AllocateSpillSlot (ValueNode *node)
void Spill (ValueNode *node)
void SpillRegisters ()
template<typename RegisterT >
void SpillAndClearRegisters (RegisterFrameState< RegisterT > &registers)
void SpillAndClearRegisters ()
void SaveRegisterSnapshot (NodeBase *node)
void FreeRegistersUsedBy (ValueNode *node)
template<typename RegisterT >
RegisterT FreeUnblockedRegister (RegListBase< RegisterT > reserved=RegListBase< RegisterT >())
template<typename RegisterT >
RegisterT PickRegisterToFree (RegListBase< RegisterT > reserved)
template<typename RegisterT >
RegisterFrameState< RegisterT > & GetRegisterFrameState ()
template<typename RegisterT >
void DropRegisterValueAtEnd (RegisterT reg, bool force_spill=false)
bool IsCurrentNodeLastUseOf (ValueNode *node)
template<typename RegisterT >
void EnsureFreeRegisterAtEnd (const compiler::InstructionOperand &hint=compiler::InstructionOperand())
compiler::AllocatedOperand AllocateRegisterAtEnd (ValueNode *node)
template<typename RegisterT >
void DropRegisterValue (RegisterFrameState< RegisterT > &registers, RegisterT reg, bool force_spill=false)
void DropRegisterValue (Register reg)
void DropRegisterValue (DoubleRegister reg)
compiler::AllocatedOperand AllocateRegister (ValueNode *node, const compiler::InstructionOperand &hint=compiler::InstructionOperand())
template<typename RegisterT >
compiler::AllocatedOperand ForceAllocate (RegisterFrameState< RegisterT > &registers, RegisterT reg, ValueNode *node)
compiler::AllocatedOperand ForceAllocate (Register reg, ValueNode *node)
compiler::AllocatedOperand ForceAllocate (DoubleRegister reg, ValueNode *node)
compiler::AllocatedOperand ForceAllocate (const Input &input, ValueNode *node)
template<typename Function >
void ForEachMergePointRegisterState (MergePointRegisterState &merge_point_state, Function &&f)
void ClearRegisterValues ()
void InitializeRegisterValues (MergePointRegisterState &target_state)
template<typename RegisterT >
void HoistLoopReloads (BasicBlock *target, RegisterFrameState< RegisterT > &registers)
void HoistLoopSpills (BasicBlock *target)
void InitializeBranchTargetRegisterValues (ControlNode *source, BasicBlock *target)
void InitializeEmptyBlockRegisterValues (ControlNode *source, BasicBlock *target)
void InitializeBranchTargetPhis (int predecessor_id, BasicBlock *target)
void InitializeConditionalBranchTarget (ConditionalControlNode *source, BasicBlock *target)
void MergeRegisterValues (ControlNode *control, BasicBlock *target, int predecessor_id)
void ApplyPatches (BasicBlock *block)
bool has_graph_labeller () const
MaglevGraphLabeller * graph_labeller () const
Private Attributes
RegisterFrameState< Register > general_registers_
RegisterFrameState< DoubleRegister > double_registers_
SpillSlots untagged_
SpillSlots tagged_
MaglevCompilationInfo * compilation_info_
std::unique_ptr< MaglevPrintingVisitor > printing_visitor_
Graph * graph_
ZoneVector< BlockPatch > patches_
BlockConstIterator block_it_
NodeIterator node_it_
NodeBase * current_node_
RegallocInfo * regalloc_info_
Detailed Description
Definition at line 154 of file maglev-regalloc.h.
Constructor & Destructor Documentation
StraightForwardRegisterAllocator()
v8::internal::maglev::StraightForwardRegisterAllocator::StraightForwardRegisterAllocator (MaglevCompilationInfo * compilation_info, Graph * graph, RegallocInfo * regalloc_info)
Definition at line 202 of file maglev-regalloc.cc.
    : compilation_info_(compilation_info),
      graph_(graph),
      patches_(compilation_info_->zone()),
      regalloc_info_(regalloc_info) {
  ComputePostDominatingHoles();
  AllocateRegisters();
  uint32_t tagged_stack_slots = tagged_.top;
  uint32_t untagged_stack_slots = untagged_.top;
  if (graph_->is_osr()) {
    // Fix our stack frame to be compatible with the source stack frame of this
    // OSR transition:
    // 1) Ensure the section with tagged slots is big enough to receive all
    // live OSR-in values.
    for (auto val : graph_->osr_values()) {
      if (val->result().operand().IsAllocated() &&
          val->stack_slot() >= tagged_stack_slots) {
        tagged_stack_slots = val->stack_slot() + 1;
      }
    }
    // 2) Ensure we never have to shrink stack frames when OSR'ing into Maglev.
    // We don't grow tagged slots or they might end up being uninitialized.
    uint32_t source_frame_size =
        graph_->min_maglev_stackslots_for_unoptimized_frame_size();
    uint32_t target_frame_size = tagged_stack_slots + untagged_stack_slots;
    if (source_frame_size > target_frame_size) {
      untagged_stack_slots += source_frame_size - target_frame_size;
    }
  }
#ifdef V8_TARGET_ARCH_ARM64
  // Due to alignment constraints, we add one untagged slot if
  // stack_slots + fixed_slot_count is odd.
  static_assert(StandardFrameConstants::kFixedSlotCount % 2 == 1);
  if ((tagged_stack_slots + untagged_stack_slots) % 2 == 0) {
    untagged_stack_slots++;
  }
#endif // V8_TARGET_ARCH_ARM64
  graph_->set_tagged_stack_slots(tagged_stack_slots);
  graph_->set_untagged_stack_slots(untagged_stack_slots);
}
References AllocateRegisters(), ComputePostDominatingHoles(), graph_, v8::internal::maglev::Graph::is_osr(), v8::internal::StandardFrameConstants::kFixedSlotCount, v8::internal::maglev::Graph::min_maglev_stackslots_for_unoptimized_frame_size(), v8::internal::maglev::Graph::osr_values(), v8::internal::maglev::Graph::set_tagged_stack_slots(), v8::internal::maglev::Graph::set_untagged_stack_slots(), tagged_, v8::internal::maglev::StraightForwardRegisterAllocator::SpillSlots::top, and untagged_.
 StraightForwardRegisterAllocator()
v8::internal::maglev::StraightForwardRegisterAllocator::~StraightForwardRegisterAllocator () [default]
Member Function Documentation
AddMoveBeforeCurrentNode()
void v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode (ValueNode * node, compiler::InstructionOperand source, compiler::AllocatedOperand target) [private]
Definition at line 1193 of file maglev-regalloc.cc.
                                     {
  Node* gap_move;
  if (source.IsConstant()) {
    DCHECK(IsConstantNode(node->opcode()));
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os()
          << " constant gap move: " << target << " ← "
          << PrintNodeLabel(graph_labeller(), node) << std::endl;
    }
    gap_move =
        Node::New<ConstantGapMove>(compilation_info_->zone(), 0, node, target);
  } else {
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os() << " gap move: " << target << " ← "
                              << PrintNodeLabel(graph_labeller(), node) << ":"
                              << source << std::endl;
    }
    gap_move =
        Node::New<GapMove>(compilation_info_->zone(), 0,
                           compiler::AllocatedOperand::cast(source), target);
  }
  gap_move->InitTemporaries();
  if (compilation_info_->has_graph_labeller()) {
    graph_labeller()->RegisterNode(gap_move);
  }
  BasicBlock* block = *block_it_;
  if (node_it_ == block->nodes().end()) {
    DCHECK(current_node_->Is<ControlNode>());
    // We're at the control node, so append instead.
    block->nodes().push_back(gap_move);
    node_it_ = block->nodes().end();
  } else {
    // We should not add any gap move before a GetSecondReturnedValue.
    patches_.emplace_back(node_it_ - block->nodes().begin(), gap_move);
  }
}
References v8::internal::ZoneVector< T >::begin(), block_it_, v8::internal::compiler::LocationOperand::cast(), compilation_info_, current_node_, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), graph_labeller(), v8::internal::maglev::MaglevCompilationInfo::has_graph_labeller(), v8::internal::maglev::NodeBase::InitTemporaries(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::IsConstantNode(), node_it_, v8::internal::maglev::BasicBlock::nodes(), v8::internal::maglev::NodeBase::opcode(), patches_, printing_visitor_, v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), v8::internal::v8_flags, and v8::internal::maglev::MaglevCompilationInfo::zone().
Referenced by AssignArbitraryRegisterInput(), AssignFixedInput(), and DropRegisterValue().
AllocateControlNode()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateControlNode (ControlNode * node, BasicBlock * block) [private]
Definition at line 1031 of file maglev-regalloc.cc.
                                                                              {
  current_node_ = node;
  // Control nodes can't lazy deopt at the moment.
  DCHECK(!node->properties().can_lazy_deopt());
  if (node->Is<Abort>()) {
    // Do nothing.
    DCHECK(node->general_temporaries().is_empty());
    DCHECK(node->double_temporaries().is_empty());
    DCHECK_EQ(node->num_temporaries_needed<Register>(), 0);
    DCHECK_EQ(node->num_temporaries_needed<DoubleRegister>(), 0);
    DCHECK_EQ(node->input_count(), 0);
    // Either there are no special properties, or there's a call but it doesn't
    // matter because we'll abort anyway.
    DCHECK_IMPLIES(
        node->properties() != OpProperties(0),
        node->properties() == OpProperties::Call() && node->Is<Abort>());
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->Process(node, ProcessingState(block_it_));
    }
  } else if (node->Is<Deopt>()) {
    // No temporaries.
    DCHECK(node->general_temporaries().is_empty());
    DCHECK(node->double_temporaries().is_empty());
    DCHECK_EQ(node->num_temporaries_needed<Register>(), 0);
    DCHECK_EQ(node->num_temporaries_needed<DoubleRegister>(), 0);
    DCHECK_EQ(node->input_count(), 0);
    DCHECK_EQ(node->properties(), OpProperties::EagerDeopt());
    AllocateEagerDeopt(*node->eager_deopt_info());
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->Process(node, ProcessingState(block_it_));
    }
  } else if (auto unconditional = node->TryCast<UnconditionalControlNode>()) {
    // No temporaries.
    DCHECK(node->general_temporaries().is_empty());
    DCHECK(node->double_temporaries().is_empty());
    DCHECK_EQ(node->num_temporaries_needed<Register>(), 0);
    DCHECK_EQ(node->num_temporaries_needed<DoubleRegister>(), 0);
    DCHECK_EQ(node->input_count(), 0);
    DCHECK(!node->properties().can_eager_deopt());
    DCHECK(!node->properties().can_lazy_deopt());
    DCHECK(!node->properties().needs_register_snapshot());
    DCHECK(!node->properties().is_call());
    auto predecessor_id = block->predecessor_id();
    auto target = unconditional->target();
    InitializeBranchTargetPhis(predecessor_id, target);
    MergeRegisterValues(unconditional, target, predecessor_id);
    if (target->has_phi()) {
      for (Phi* phi : *target->phis()) {
        UpdateUse(&phi->input(predecessor_id));
      }
    }
    // For JumpLoops, now update the uses of any node used in, but not defined
    // in the loop. This makes sure that such nodes' lifetimes are extended to
    // the entire body of the loop. This must be after phi initialisation so
    // that value dropping in the phi initialisation doesn't think these
    // extended lifetime nodes are dead.
    if (auto jump_loop = node->TryCast<JumpLoop>()) {
      for (Input& input : jump_loop->used_nodes()) {
        if (!input.node()->has_register() && !input.node()->is_loadable()) {
          // If the value isn't loadable by the end of a loop (this can happen
          // e.g. when a deferred throw doesn't spill it, and an exception
          // handler drops the value)
          Spill(input.node());
        }
        UpdateUse(&input);
      }
    }
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->Process(node, ProcessingState(block_it_));
    }
  } else {
    DCHECK(node->Is<ConditionalControlNode>() || node->Is<Return>());
    AssignInputs(node);
    VerifyInputs(node);
    DCHECK(!node->properties().can_eager_deopt());
    DCHECK(!node->properties().can_lazy_deopt());
    if (node->properties().is_call()) SpillAndClearRegisters();
    DCHECK(!node->properties().needs_register_snapshot());
    DCHECK_EQ(general_registers_.free() | node->general_temporaries(),
              general_registers_.free());
    DCHECK_EQ(double_registers_.free() | node->double_temporaries(),
              double_registers_.free());
    general_registers_.clear_blocked();
    double_registers_.clear_blocked();
    VerifyRegisterState();
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->Process(node, ProcessingState(block_it_));
    }
    // Finally, initialize the merge states of branch targets, including the
    // fallthrough, with the final state after all allocation
    if (auto conditional = node->TryCast<BranchControlNode>()) {
      InitializeConditionalBranchTarget(conditional, conditional->if_true());
      InitializeConditionalBranchTarget(conditional, conditional->if_false());
    } else if (Switch* control_node = node->TryCast<Switch>()) {
      const BasicBlockRef* targets = control_node->targets();
      for (int i = 0; i < control_node->size(); i++) {
        InitializeConditionalBranchTarget(control_node, targets[i].block_ptr());
      }
      if (control_node->has_fallthrough()) {
        InitializeConditionalBranchTarget(control_node,
                                          control_node->fallthrough());
      }
    }
  }
  VerifyRegisterState();
}
References AllocateEagerDeopt(), AssignInputs(), block_it_, v8::internal::maglev::OpProperties::Call(), v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::can_lazy_deopt(), current_node_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, double_registers_, v8::internal::maglev::NodeBase::double_temporaries(), v8::internal::maglev::NodeBase::eager_deopt_info(), v8::internal::maglev::OpProperties::EagerDeopt(), general_registers_, v8::internal::maglev::NodeBase::general_temporaries(), InitializeBranchTargetPhis(), InitializeConditionalBranchTarget(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::OpProperties::is_call(), v8::internal::RegListBase< RegisterT >::is_empty(), MergeRegisterValues(), v8::internal::maglev::OpProperties::needs_register_snapshot(), v8::internal::maglev::NodeBase::num_temporaries_needed(), v8::internal::maglev::BasicBlock::predecessor_id(), printing_visitor_, v8::internal::maglev::NodeBase::properties(), Spill(), SpillAndClearRegisters(), v8::internal::maglev::NodeBase::TryCast(), UpdateUse(), v8::internal::v8_flags, VerifyInputs(), and VerifyRegisterState().
Referenced by AllocateRegisters().
AllocateEagerDeopt()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt (const EagerDeoptInfo & deopt_info) [private]
Definition at line 673 of file maglev-regalloc.cc.
                                      {
  InputLocation* input = deopt_info.input_locations();
  deopt_info.ForEachInput([&](ValueNode* node) {
    DCHECK(!node->Is<Identity>());
    // We might have dropped this node without spilling it. Spill it now.
    if (!node->has_register() && !node->is_loadable()) {
      Spill(node);
    }
    input->InjectLocation(node->allocation());
    UpdateUse(node, input);
    input++;
  });
}
References v8::internal::maglev::ValueNode::allocation(), v8::internal::DCHECK(), v8::internal::maglev::EagerDeoptInfo::ForEachInput(), v8::internal::maglev::ValueNode::has_register(), v8::internal::maglev::ValueLocation::InjectLocation(), v8::internal::maglev::DeoptInfo::input_locations(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::ValueNode::is_loadable(), Spill(), and UpdateUse().
Referenced by AllocateControlNode(), and AllocateNode().
AllocateLazyDeopt()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateLazyDeopt (const LazyDeoptInfo & deopt_info) [private]
Definition at line 688 of file maglev-regalloc.cc.
                                     {
  InputLocation* input = deopt_info.input_locations();
  deopt_info.ForEachInput([&](ValueNode* node) {
    DCHECK(!node->Is<Identity>());
    // Lazy deopts always need spilling, and should
    // always be loaded from their loadable slot.
    Spill(node);
    input->InjectLocation(node->loadable_slot());
    UpdateUse(node, input);
    input++;
  });
}
References v8::internal::DCHECK(), v8::internal::maglev::LazyDeoptInfo::ForEachInput(), v8::internal::maglev::ValueLocation::InjectLocation(), v8::internal::maglev::DeoptInfo::input_locations(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::ValueNode::loadable_slot(), Spill(), and UpdateUse().
Referenced by AllocateNode().
AllocateNode()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode (Node * node) [private]
Definition at line 719 of file maglev-regalloc.cc.
                                                              {
  // We shouldn't be visiting any gap moves during allocation, we should only
  // have inserted gap moves in past visits.
  DCHECK(!node->Is<GapMove>());
  DCHECK(!node->Is<ConstantGapMove>());
  current_node_ = node;
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << "Allocating " << PrintNodeLabel(graph_labeller(), node)
        << " inputs...\n";
  }
  AssignInputs(node);
  VerifyInputs(node);
  if (node->properties().is_call()) SpillAndClearRegisters();
  // Allocate node output.
  if (node->Is<ValueNode>()) {
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os() << "Allocating result...\n";
    }
    AllocateNodeResult(node->Cast<ValueNode>());
  }
  // Eager deopts might happen after the node result has been set, so allocate
  // them after result allocation.
  if (node->properties().can_eager_deopt()) {
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os() << "Allocating eager deopt inputs...\n";
    }
    AllocateEagerDeopt(*node->eager_deopt_info());
  }
  // Lazy deopts are semantically after the node, so allocate them last.
  if (node->properties().can_lazy_deopt()) {
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os() << "Allocating lazy deopt inputs...\n";
    }
    // Ensure all values live from a throwing node across its catch block are
    // spilled so they can properly be merged after the catch block.
    if (node->properties().can_throw()) {
      ExceptionHandlerInfo* info = node->exception_handler_info();
      if (info->HasExceptionHandler() && !info->ShouldLazyDeopt() &&
          !node->properties().is_call()) {
        BasicBlock* block = info->catch_block();
        auto spill = [&](auto reg, ValueNode* node) {
          if (node->live_range().end < block->first_id()) return;
          Spill(node);
        };
        general_registers_.ForEachUsedRegister(spill);
        double_registers_.ForEachUsedRegister(spill);
      }
    }
    AllocateLazyDeopt(*node->lazy_deopt_info());
  }
  // Make sure to save snapshot after allocate eager deopt registers.
  if (node->properties().needs_register_snapshot()) SaveRegisterSnapshot(node);
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->Process(node, ProcessingState(block_it_));
    printing_visitor_->os() << "live regs: ";
    PrintLiveRegs();
    printing_visitor_->os() << "\n";
  }
  // Result register should not be in temporaries.
  DCHECK_IMPLIES(GetNodeResultRegister(node) != Register::no_reg(),
                 !node->general_temporaries().has(GetNodeResultRegister(node)));
  DCHECK_IMPLIES(
      GetNodeResultDoubleRegister(node) != DoubleRegister::no_reg(),
      !node->double_temporaries().has(GetNodeResultDoubleRegister(node)));
  // All the temporaries should be free by the end.
  DCHECK_EQ(general_registers_.free() | node->general_temporaries(),
            general_registers_.free());
  DCHECK_EQ(double_registers_.free() | node->double_temporaries(),
            double_registers_.free());
  general_registers_.clear_blocked();
  double_registers_.clear_blocked();
  VerifyRegisterState();
}
References AllocateEagerDeopt(), AllocateLazyDeopt(), AllocateNodeResult(), AssignInputs(), block_it_, v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::maglev::OpProperties::can_lazy_deopt(), v8::internal::maglev::OpProperties::can_throw(), v8::internal::maglev::NodeBase::Cast(), v8::internal::maglev::ExceptionHandlerInfo::catch_block(), current_node_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, double_registers_, v8::internal::maglev::NodeBase::double_temporaries(), v8::internal::maglev::NodeBase::eager_deopt_info(), v8::internal::maglev::NodeBase::end(), v8::internal::maglev::NodeBase::exception_handler_info(), v8::internal::maglev::BasicBlock::first_id(), general_registers_, v8::internal::maglev::NodeBase::general_temporaries(), graph_labeller(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::maglev::ExceptionHandlerInfo::HasExceptionHandler(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::OpProperties::is_call(), v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::OpProperties::needs_register_snapshot(), v8::internal::Register::no_reg(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::no_reg(), printing_visitor_, PrintLiveRegs(), v8::internal::maglev::NodeBase::properties(), SaveRegisterSnapshot(), v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt(), Spill(), SpillAndClearRegisters(), v8::internal::v8_flags, VerifyInputs(), and VerifyRegisterState().
Referenced by AllocateRegisters().
AllocateNodeResult()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult (ValueNode * node) [private]
Definition at line 821 of file maglev-regalloc.cc.
                                                                         {
  DCHECK(!node->Is<Phi>());
  node->SetNoSpill();
  compiler::UnallocatedOperand operand =
      compiler::UnallocatedOperand::cast(node->result().operand());
  if (operand.basic_policy() == compiler::UnallocatedOperand::FIXED_SLOT) {
    DCHECK(node->Is<InitialValue>());
    DCHECK_IMPLIES(!graph_->is_osr(), operand.fixed_slot_index() < 0);
    // Set the stack slot to exactly where the value is.
    compiler::AllocatedOperand location(compiler::AllocatedOperand::STACK_SLOT,
                                        node->GetMachineRepresentation(),
                                        operand.fixed_slot_index());
    node->result().SetAllocated(location);
    node->Spill(location);
    int idx = operand.fixed_slot_index();
    if (idx > 0) {
      // Reserve this slot by increasing the top and also marking slots below as
      // free. Assumes slots are processed in increasing order.
      CHECK(node->is_tagged());
      CHECK_GE(idx, tagged_.top);
      for (int i = tagged_.top; i < idx; ++i) {
        bool double_slot =
            IsDoubleRepresentation(node->properties().value_representation());
        tagged_.free_slots.emplace_back(i, node->live_range().start,
                                        double_slot);
      }
      tagged_.top = idx + 1;
    }
    return;
  }
  switch (operand.extended_policy()) {
    case compiler::UnallocatedOperand::FIXED_REGISTER: {
      Register r = Register::from_code(operand.fixed_register_index());
      DropRegisterValueAtEnd(r);
      node->result().SetAllocated(ForceAllocate(r, node));
      break;
    }
    case compiler::UnallocatedOperand::MUST_HAVE_REGISTER:
      node->result().SetAllocated(AllocateRegisterAtEnd(node));
      break;
    case compiler::UnallocatedOperand::SAME_AS_INPUT: {
      Input& input = node->input(operand.input_index());
      node->result().SetAllocated(ForceAllocate(input, node));
      // Clear any hint that (probably) comes from this constraint.
      if (node->has_hint()) input.node()->ClearHint();
      break;
    }
    case compiler::UnallocatedOperand::FIXED_FP_REGISTER: {
      DoubleRegister r =
          DoubleRegister::from_code(operand.fixed_register_index());
      DropRegisterValueAtEnd(r);
      node->result().SetAllocated(ForceAllocate(r, node));
      break;
    }
    case compiler::UnallocatedOperand::NONE:
      DCHECK(IsConstantNode(node->opcode()));
      break;
    case compiler::UnallocatedOperand::MUST_HAVE_SLOT:
    case compiler::UnallocatedOperand::REGISTER_OR_SLOT:
    case compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT:
      UNREACHABLE();
  }
  // Immediately kill the register use if the node doesn't have a valid
  // live-range.
  // TODO(verwaest): Remove once we can avoid allocating such registers.
  if (!node->has_valid_live_range() &&
      node->result().operand().IsAnyRegister()) {
    DCHECK(node->has_register());
    FreeRegistersUsedBy(node);
    DCHECK(!node->has_register());
    DCHECK(node->has_no_more_uses());
  }
}
References AllocateRegisterAtEnd(), v8::internal::compiler::UnallocatedOperand::basic_policy(), CHECK, CHECK_GE, v8::internal::maglev::ValueNode::ClearHint(), v8::internal::DCHECK(), DCHECK_IMPLIES, DropRegisterValueAtEnd(), v8::internal::compiler::UnallocatedOperand::extended_policy(), v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, v8::internal::compiler::UnallocatedOperand::fixed_register_index(), v8::internal::compiler::UnallocatedOperand::FIXED_SLOT, v8::internal::compiler::UnallocatedOperand::fixed_slot_index(), ForceAllocate(), v8::internal::maglev::StraightForwardRegisterAllocator::SpillSlots::free_slots, FreeRegistersUsedBy(), v8::internal::Register::from_code(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), v8::internal::maglev::ValueNode::GetMachineRepresentation(), graph_, v8::internal::maglev::ValueNode::has_hint(), v8::internal::maglev::ValueNode::has_no_more_uses(), v8::internal::maglev::ValueNode::has_register(), v8::internal::maglev::ValueNode::has_valid_live_range(), v8::internal::maglev::NodeBase::input(), v8::internal::compiler::UnallocatedOperand::input_index(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::Graph::is_osr(), v8::internal::maglev::ValueNode::is_tagged(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::IsDoubleRepresentation(), v8::internal::maglev::ValueNode::live_range(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_SLOT, v8::internal::maglev::Input::node(), v8::internal::compiler::UnallocatedOperand::NONE, v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::ValueLocation::operand(), v8::internal::maglev::NodeBase::properties(), v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, v8::internal::maglev::ValueNode::result(), v8::internal::compiler::UnallocatedOperand::SAME_AS_INPUT, v8::internal::maglev::ValueLocation::SetAllocated(), v8::internal::maglev::ValueNode::SetNoSpill(), v8::internal::maglev::ValueNode::Spill(), v8::internal::compiler::LocationOperand::STACK_SLOT, v8::internal::maglev::ValueNode::LiveRange::start, tagged_, v8::internal::maglev::StraightForwardRegisterAllocator::SpillSlots::top, v8::internal::UNREACHABLE(), and v8::internal::maglev::OpProperties::value_representation().
Referenced by AllocateNode().
AllocateRegister()
compiler::AllocatedOperand v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegister (ValueNode * node, const compiler::InstructionOperand & hint = compiler::InstructionOperand()) [private]
Definition at line 1758 of file maglev-regalloc.cc.
                                                             {
  compiler::InstructionOperand allocation;
  if (node->use_double_register()) {
    if (double_registers_.UnblockedFreeIsEmpty()) {
      FreeUnblockedRegister<DoubleRegister>();
    }
    return double_registers_.AllocateRegister(node, hint);
  } else {
    if (general_registers_.UnblockedFreeIsEmpty()) {
      FreeUnblockedRegister<Register>();
    }
    return general_registers_.AllocateRegister(node, hint);
  }
}
References v8::internal::maglev::ValueNode::use_double_register().
Referenced by AssignArbitraryRegisterInput().
AllocateRegisterAtEnd()
compiler::AllocatedOperand v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisterAtEnd (ValueNode * node) [private]
Definition at line 1821 of file maglev-regalloc.cc.
                                                                       {
  if (node->use_double_register()) {
    EnsureFreeRegisterAtEnd<DoubleRegister>(node->hint());
    return double_registers_.AllocateRegister(node, node->hint());
  } else {
    EnsureFreeRegisterAtEnd<Register>(node->hint());
    return general_registers_.AllocateRegister(node, node->hint());
  }
}
References v8::internal::maglev::ValueNode::hint(), and v8::internal::maglev::ValueNode::use_double_register().
Referenced by AllocateNodeResult().
AllocateRegisters()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters () [private]
Definition at line 364 of file maglev-regalloc.cc.
                                                         {
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_.reset(
        new MaglevPrintingVisitor(graph_labeller(), std::cout));
    printing_visitor_->PreProcessGraph(graph_);
  }
  for (const auto& [ref, constant] : graph_->constants()) {
    constant->SetConstantLocation();
    USE(ref);
  }
  for (const auto& [index, constant] : graph_->root()) {
    constant->SetConstantLocation();
    USE(index);
  }
  for (const auto& [value, constant] : graph_->smi()) {
    constant->SetConstantLocation();
    USE(value);
  }
  for (const auto& [value, constant] : graph_->tagged_index()) {
    constant->SetConstantLocation();
    USE(value);
  }
  for (const auto& [value, constant] : graph_->int32()) {
    constant->SetConstantLocation();
    USE(value);
  }
  for (const auto& [value, constant] : graph_->uint32()) {
    constant->SetConstantLocation();
    USE(value);
  }
  for (const auto& [value, constant] : graph_->intptr()) {
    constant->SetConstantLocation();
    USE(value);
  }
  for (const auto& [value, constant] : graph_->float64()) {
    constant->SetConstantLocation();
    USE(value);
  }
  for (const auto& [ref, constant] : graph_->trusted_constants()) {
    constant->SetConstantLocation();
    USE(ref);
  }
  for (block_it_ = graph_->begin(); block_it_ != graph_->end(); ++block_it_) {
    BasicBlock* block = *block_it_;
    DCHECK(!block->is_dead());
    current_node_ = nullptr;
    // Restore mergepoint state.
    if (block->has_state()) {
      if (block->state()->is_exception_handler() ||
          block->state()->IsUnreachableByForwardEdge()) {
        // Exceptions and loops only reachable from a JumpLoop (i.e., resumable
        // loops with no fall-through edge) start with a blank state of register
        // values.
        ClearRegisterValues();
      } else {
        InitializeRegisterValues(block->state()->register_state());
      }
    } else if (block->is_edge_split_block()) {
      InitializeRegisterValues(block->edge_split_block_register_state());
    }
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->PreProcessBasicBlock(block);
      printing_visitor_->os() << "live regs: ";
      PrintLiveRegs();
      ControlNode* control = NearestPostDominatingHole(block->control_node());
      if (!control->Is<JumpLoop>()) {
        printing_visitor_->os() << "\n[holes:";
        while (true) {
          if (control->Is<JumpLoop>()) {
            printing_visitor_->os() << " " << control->id() << "↰";
            break;
          } else if (control->Is<UnconditionalControlNode>()) {
            BasicBlock* target =
                control->Cast<UnconditionalControlNode>()->target();
            printing_visitor_->os()
                << " " << control->id() << "-" << target->first_id();
            control = control->next_post_dominating_hole();
            DCHECK_NOT_NULL(control);
            continue;
          } else if (control->Is<Switch>()) {
            Switch* _switch = control->Cast<Switch>();
            DCHECK(!_switch->has_fallthrough());
            DCHECK_GE(_switch->size(), 1);
            BasicBlock* first_target = _switch->targets()[0].block_ptr();
            printing_visitor_->os()
                << " " << control->id() << "-" << first_target->first_id();
            control = control->next_post_dominating_hole();
            DCHECK_NOT_NULL(control);
            continue;
          } else if (control->Is<Return>()) {
            printing_visitor_->os() << " " << control->id() << ".";
            break;
          } else if (control->Is<Deopt>() || control->Is<Abort>()) {
            printing_visitor_->os() << " " << control->id() << "✖️";
            break;
          }
          UNREACHABLE();
        }
        printing_visitor_->os() << "]";
      }
      printing_visitor_->os() << std::endl;
    }
    // Activate phis.
    if (block->has_phi()) {
      Phi::List& phis = *block->phis();
      // Firstly, make the phi live, and try to assign it to an input
      // location.
      for (auto phi_it = phis.begin(); phi_it != phis.end();) {
        Phi* phi = *phi_it;
        if (!phi->has_valid_live_range()) {
          // We might still have left over dead Phis, due to phis being kept
          // alive by deopts that the representation analysis dropped. Clear
          // them out now.
          phi_it = phis.RemoveAt(phi_it);
        } else {
          DCHECK(phi->has_valid_live_range());
          phi->SetNoSpill();
          TryAllocateToInput(phi);
          ++phi_it;
        }
      }
      if (block->is_exception_handler_block()) {
        // If we are in exception handler block, then we find the ExceptionPhi
        // (the first one by default) that is marked with the
        // virtual_accumulator and force kReturnRegister0. This corresponds to
        // the exception message object.
        for (Phi* phi : phis) {
          DCHECK_EQ(phi->input_count(), 0);
          DCHECK(phi->is_exception_phi());
          if (phi->owner() == interpreter::Register::virtual_accumulator()) {
            if (!phi->has_no_more_uses()) {
              phi->result().SetAllocated(ForceAllocate(kReturnRegister0, phi));
              if (v8_flags.trace_maglev_regalloc) {
                printing_visitor_->Process(phi, ProcessingState(block_it_));
                printing_visitor_->os() << "phi (exception message object) "
                                        << phi->result().operand() << std::endl;
              }
            }
          } else if (phi->owner().is_parameter() &&
                     phi->owner().is_receiver()) {
            // The receiver is a special case for a fairly silly reason:
            // OptimizedJSFrame::Summarize requires the receiver (and the
            // function) to be in a stack slot, since its value must be
            // available even though we're not deoptimizing (and thus register
            // states are not available).
            //
            // TODO(leszeks):
            // For inlined functions / nested graph generation, this a) doesn't
            // work (there's no receiver stack slot); and b) isn't necessary
            // (Summarize only looks at noninlined functions).
            phi->Spill(compiler::AllocatedOperand(
                compiler::AllocatedOperand::STACK_SLOT,
                MachineRepresentation::kTagged,
                (StandardFrameConstants::kExpressionsOffset -
                 UnoptimizedFrameConstants::kRegisterFileFromFp) /
                        kSystemPointerSize +
                    interpreter::Register::receiver().index()));
            phi->result().SetAllocated(phi->spill_slot());
            // Break once both accumulator and receiver have been processed.
            break;
          }
        }
      }
      // Secondly try to assign the phi to a free register.
      for (Phi* phi : phis) {
        DCHECK(phi->has_valid_live_range());
        if (phi->result().operand().IsAllocated()) continue;
        if (phi->use_double_register()) {
          if (!double_registers_.UnblockedFreeIsEmpty()) {
            compiler::AllocatedOperand allocation =
                double_registers_.AllocateRegister(phi, phi->hint());
            phi->result().SetAllocated(allocation);
            SetLoopPhiRegisterHint(phi, allocation.GetDoubleRegister());
            if (v8_flags.trace_maglev_regalloc) {
              printing_visitor_->Process(phi, ProcessingState(block_it_));
              printing_visitor_->os()
                  << "phi (new reg) " << phi->result().operand() << std::endl;
            }
          }
        } else {
          // We'll use a general purpose register for this Phi.
          if (!general_registers_.UnblockedFreeIsEmpty()) {
            compiler::AllocatedOperand allocation =
                general_registers_.AllocateRegister(phi, phi->hint());
            phi->result().SetAllocated(allocation);
            SetLoopPhiRegisterHint(phi, allocation.GetRegister());
            if (v8_flags.trace_maglev_regalloc) {
              printing_visitor_->Process(phi, ProcessingState(block_it_));
              printing_visitor_->os()
                  << "phi (new reg) " << phi->result().operand() << std::endl;
            }
          }
        }
      }
      // Finally just use a stack slot.
      for (Phi* phi : phis) {
        DCHECK(phi->has_valid_live_range());
        if (phi->result().operand().IsAllocated()) continue;
        AllocateSpillSlot(phi);
        // TODO(verwaest): Will this be used at all?
        phi->result().SetAllocated(phi->spill_slot());
        if (v8_flags.trace_maglev_regalloc) {
          printing_visitor_->Process(phi, ProcessingState(block_it_));
          printing_visitor_->os()
              << "phi (stack) " << phi->result().operand() << std::endl;
        }
      }
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os() << "live regs: ";
        PrintLiveRegs();
        printing_visitor_->os() << std::endl;
      }
      general_registers_.clear_blocked();
      double_registers_.clear_blocked();
    }
    DCHECK(AllUsedRegistersLiveAt(block));
    VerifyRegisterState();
    node_it_ = block->nodes().begin();
    for (; node_it_ != block->nodes().end(); ++node_it_) {
      Node* node = *node_it_;
      if (node == nullptr) continue;
      if (IsDeadNodeToSkip(node)) {
        // We remove unused pure nodes.
        if (v8_flags.trace_maglev_regalloc) {
          printing_visitor_->os()
              << "Removing unused node "
              << PrintNodeLabel(graph_labeller(), node) << "\n";
        }
        if (!node->Is<Identity>()) {
          // Updating the uses of the inputs in order to free dead input
          // registers. We don't do this for Identity nodes, because they were
          // skipped during use marking, and their inputs are thus not aware
          // that they were used by this node.
          DCHECK(!node->properties().can_deopt());
          node->ForAllInputsInRegallocAssignmentOrder(
              [&](NodeBase::InputAllocationPolicy, Input* input) {
                UpdateUse(input);
              });
        }
        *node_it_ = nullptr;
        continue;
      }
      AllocateNode(node);
    }
    AllocateControlNode(block->control_node(), block);
    ApplyPatches(block);
  }
}
References AllocateControlNode(), AllocateNode(), AllocateSpillSlot(), ApplyPatches(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::internal::maglev::Graph::begin(), v8::internal::ZoneVector< T >::begin(), block_it_, v8::internal::maglev::BasicBlockRef::block_ptr(), v8::internal::maglev::OpProperties::can_deopt(), v8::internal::maglev::NodeBase::Cast(), ClearRegisterValues(), v8::internal::maglev::Graph::constants(), v8::internal::maglev::BasicBlock::control_node(), current_node_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_NOT_NULL, double_registers_, v8::internal::maglev::BasicBlock::edge_split_block_register_state(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::internal::maglev::Graph::end(), v8::internal::compiler::end(), v8::internal::maglev::BasicBlock::first_id(), v8::internal::maglev::Graph::float64(), v8::internal::maglev::NodeBase::ForAllInputsInRegallocAssignmentOrder(), ForceAllocate(), general_registers_, v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::LocationOperand::GetRegister(), graph_, graph_labeller(), v8::internal::maglev::Switch::has_fallthrough(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::BasicBlock::has_state(), v8::internal::maglev::NodeBase::id(), v8::internal::index, InitializeRegisterValues(), v8::internal::maglev::Graph::int32(), v8::internal::maglev::Graph::intptr(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::BasicBlock::is_dead(), v8::internal::maglev::BasicBlock::is_edge_split_block(), v8::internal::maglev::MergePointInterpreterFrameState::is_exception_handler(), v8::internal::maglev::BasicBlock::is_exception_handler_block(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsDeadNodeToSkip(), v8::internal::maglev::MergePointInterpreterFrameState::IsUnreachableByForwardEdge(), v8::internal::StandardFrameConstants::kExpressionsOffset, v8::internal::UnoptimizedFrameConstants::kRegisterFileFromFp, v8::internal::kReturnRegister0, v8::internal::kSystemPointerSize, v8::internal::kTagged, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole(), v8::internal::maglev::ControlNode::next_post_dominating_hole(), node_it_, v8::internal::maglev::BasicBlock::nodes(), v8::internal::maglev::BasicBlock::phis(), printing_visitor_, PrintLiveRegs(), v8::internal::maglev::NodeBase::properties(), v8::internal::interpreter::Register::receiver(), v8::internal::maglev::MergePointInterpreterFrameState::register_state(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt(), v8::internal::maglev::Graph::root(), SetLoopPhiRegisterHint(), v8::internal::maglev::Switch::size(), v8::internal::maglev::Graph::smi(), v8::internal::compiler::LocationOperand::STACK_SLOT, v8::internal::maglev::BasicBlock::state(), v8::internal::maglev::Graph::tagged_index(), v8::internal::maglev::Switch::targets(), v8::internal::maglev::Graph::trusted_constants(), TryAllocateToInput(), v8::internal::maglev::Graph::uint32(), v8::internal::UNREACHABLE(), UpdateUse(), USE, v8::internal::v8_flags, v8::internal::value, VerifyRegisterState(), and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by StraightForwardRegisterAllocator().
AllocateSpillSlot()
void v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot (ValueNode * node) [private]
Definition at line 1659 of file maglev-regalloc.cc.
                                                                        {
  DCHECK(!node->is_loadable());
  uint32_t free_slot;
  bool is_tagged = (node->properties().value_representation() ==
                    ValueRepresentation::kTagged);
  uint32_t slot_size = 1;
  bool double_slot =
      IsDoubleRepresentation(node->properties().value_representation());
  if constexpr (kDoubleSize != kSystemPointerSize) {
    if (double_slot) {
      slot_size = kDoubleSize / kSystemPointerSize;
    }
  }
  SpillSlots& slots = is_tagged ? tagged_ : untagged_;
  MachineRepresentation representation = node->GetMachineRepresentation();
  // TODO(victorgomes): We don't currently reuse double slots on arm.
  if (!v8_flags.maglev_reuse_stack_slots || slot_size > 1 ||
      slots.free_slots.empty()) {
    free_slot = slots.top + slot_size - 1;
    slots.top += slot_size;
  } else {
    NodeIdT start = node->live_range().start;
    auto it =
        std::upper_bound(slots.free_slots.begin(), slots.free_slots.end(),
                         start, [](NodeIdT s, const SpillSlotInfo& slot_info) {
                           return slot_info.freed_at_position >= s;
                         });
    // {it} points to the first invalid slot. Decrement it to get to the last
    // valid slot freed before {start}.
    if (it != slots.free_slots.begin()) {
      --it;
    }
    // TODO(olivf): Currently we cannot mix double and normal stack slots since
    // the gap resolver treats them independently and cannot detect cycles via
    // shared slots.
    while (it != slots.free_slots.begin()) {
      if (it->double_slot == double_slot) break;
      --it;
    }
    if (it != slots.free_slots.begin()) {
      CHECK_EQ(double_slot, it->double_slot);
      CHECK_GT(start, it->freed_at_position);
      free_slot = it->slot_index;
      slots.free_slots.erase(it);
    } else {
      free_slot = slots.top++;
    }
  }
  node->Spill(compiler::AllocatedOperand(compiler::AllocatedOperand::STACK_SLOT,
                                         representation, free_slot));
}
References CHECK_EQ, CHECK_GT, DCHECK, v8::internal::maglev::StraightForwardRegisterAllocator::SpillSlots::free_slots, v8::internal::maglev::ValueNode::GetMachineRepresentation(), v8::internal::maglev::ValueNode::is_loadable(), v8::internal::maglev::IsDoubleRepresentation(), v8::internal::kDoubleSize, v8::internal::kSystemPointerSize, v8::internal::maglev::ValueNode::live_range(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::ValueNode::Spill(), v8::internal::maglev::ValueNode::LiveRange::start, v8::internal::maglev::StraightForwardRegisterAllocator::SpillSlots::top, v8::internal::v8_flags, and v8::internal::maglev::OpProperties::value_representation().
Referenced by AllocateRegisters(), and Spill().
ApplyPatches()
void v8::internal::maglev::StraightForwardRegisterAllocator::ApplyPatches (BasicBlock * block) [private]
Definition at line 179 of file maglev-regalloc.cc.
                                                                     {
  // TODO(verwaest): Perhaps don't actually merge these in but let the code
  // generator pick up the gap moves from a separate list.
  size_t diff = patches_.size();
  if (diff == 0) return;
  block->nodes().resize(block->nodes().size() + diff);
  auto patches_it = patches_.end() - 1;
  for (auto node_it = block->nodes().end() - 1 - diff;
       node_it >= block->nodes().begin(); --node_it) {
    *(node_it + diff) = *node_it;
    for (; patches_it->diff == (node_it - block->nodes().begin());
         --patches_it) {
      --diff;
      *(node_it + diff) = patches_it->new_node;
      if (diff == 0) {
        patches_.resize(0);
        return;
      }
    }
  }
  UNREACHABLE();
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::end(), v8::internal::if(), v8::internal::maglev::BasicBlock::nodes(), patches_, v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and v8::internal::UNREACHABLE().
Referenced by AllocateRegisters().
AssignAnyInput()
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput (Input & input) [private]
Definition at line 1436 of file maglev-regalloc.cc.
                                                                  {
  // Already assigned in AssignFixedInput or AssignArbitraryRegisterInput.
  if (!input.operand().IsUnallocated()) return;
  DCHECK_EQ(
      compiler::UnallocatedOperand::cast(input.operand()).extended_policy(),
      compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT);
  ValueNode* node = input.node();
  compiler::InstructionOperand location = node->allocation();
  input.InjectLocation(location);
  if (location.IsAnyRegister()) {
    compiler::AllocatedOperand allocation =
        compiler::AllocatedOperand::cast(location);
    if (allocation.IsDoubleRegister()) {
      double_registers_.block(allocation.GetDoubleRegister());
    } else {
      general_registers_.block(allocation.GetRegister());
    }
  }
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << "- " << PrintNodeLabel(graph_labeller(), input.node())
        << " in original " << location << "\n";
  }
  UpdateUse(&input);
}
References v8::internal::maglev::ValueNode::allocation(), v8::internal::compiler::LocationOperand::cast(), DCHECK_EQ, double_registers_, general_registers_, v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::LocationOperand::GetRegister(), graph_labeller(), v8::internal::maglev::ValueLocation::InjectLocation(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionOperand::IsDoubleRegister(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), printing_visitor_, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, UpdateUse(), and v8::internal::v8_flags.
Referenced by AssignInputs().
AssignArbitraryRegisterInput()
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput (NodeBase * result_node, Input & input) [private]
Definition at line 1354 of file maglev-regalloc.cc.
                                         {
  // Already assigned in AssignFixedInput
  if (!input.operand().IsUnallocated()) return;
  compiler::UnallocatedOperand operand =
      compiler::UnallocatedOperand::cast(input.operand());
  if (operand.extended_policy() ==
      compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT) {
    // Allocated in AssignAnyInput.
    return;
  }
  DCHECK_EQ(operand.extended_policy(),
            compiler::UnallocatedOperand::MUST_HAVE_REGISTER);
  ValueNode* node = input.node();
  bool is_clobbered = input.Cloberred();
  compiler::AllocatedOperand location = ([&] {
    compiler::InstructionOperand existing_register_location;
    auto hint = InputHint(result_node, input);
    if (is_clobbered) {
      // For clobbered inputs, we want to pick a different register than
      // non-clobbered inputs, so that we don't clobber those.
      existing_register_location =
          node->use_double_register()
              ? double_registers_.TryChooseUnblockedInputRegister(node)
              : general_registers_.TryChooseUnblockedInputRegister(node);
    } else {
      ValueNode* value_node = result_node->TryCast<ValueNode>();
      // Only use the hint if it helps with the result's allocation due to
      // same-as-input policy. Otherwise this doesn't affect regalloc.
      auto result_hint = value_node && SameAsInput(value_node, input)
                             ? value_node->hint()
                             : compiler::InstructionOperand();
      existing_register_location =
          node->use_double_register()
              ? double_registers_.TryChooseInputRegister(node, result_hint)
              : general_registers_.TryChooseInputRegister(node, result_hint);
    }
    // Reuse an existing register if possible.
    if (existing_register_location.IsAnyLocationOperand()) {
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os()
            << "- " << PrintNodeLabel(graph_labeller(), input.node()) << " in "
            << (is_clobbered ? "clobbered " : "") << existing_register_location
            << "\n";
      }
      return compiler::AllocatedOperand::cast(existing_register_location);
    }
    // Otherwise, allocate a register for the node and load it in from there.
    compiler::InstructionOperand existing_location = node->allocation();
    compiler::AllocatedOperand allocation = AllocateRegister(node, hint);
    DCHECK_NE(existing_location, allocation);
    AddMoveBeforeCurrentNode(node, existing_location, allocation);
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os()
          << "- " << PrintNodeLabel(graph_labeller(), input.node()) << " in "
          << (is_clobbered ? "clobbered " : "") << allocation << " ← "
          << node->allocation() << "\n";
    }
    return allocation;
  })();
  input.SetAllocated(location);
  UpdateUse(&input);
  // Only need to mark the location as clobbered if the node wasn't already
  // killed by UpdateUse.
  if (is_clobbered && !node->has_no_more_uses()) {
    MarkAsClobbered(node, location);
  }
  // Clobbered inputs should no longer be in the allocated location, as far as
  // the register allocator is concerned. This will happen either via
  // clobbering, or via this being the last use.
  DCHECK_IMPLIES(is_clobbered, !IsInRegisterLocation(node, location));
}
References AddMoveBeforeCurrentNode(), AllocateRegister(), v8::internal::maglev::ValueNode::allocation(), v8::internal::compiler::LocationOperand::cast(), v8::internal::maglev::ValueLocation::Cloberred(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, double_registers_, v8::internal::compiler::UnallocatedOperand::extended_policy(), general_registers_, graph_labeller(), v8::internal::maglev::ValueNode::has_no_more_uses(), v8::internal::maglev::ValueNode::hint(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint(), v8::internal::compiler::InstructionOperand::IsAnyLocationOperand(), MarkAsClobbered(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), printing_visitor_, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::SameAsInput(), v8::internal::maglev::ValueLocation::SetAllocated(), v8::internal::maglev::NodeBase::TryCast(), UpdateUse(), v8::internal::maglev::ValueNode::use_double_register(), and v8::internal::v8_flags.
Referenced by AssignInputs().
AssignArbitraryTemporaries() [1/2]
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries (NodeBase * node) [private]
Definition at line 2050 of file maglev-regalloc.cc.
                    {
  AssignArbitraryTemporaries(general_registers_, node);
  AssignArbitraryTemporaries(double_registers_, node);
}
AssignArbitraryTemporaries() [2/2]
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryTemporaries (RegisterFrameState< RegisterT > & registers, NodeBase * node) [private]
Definition at line 2009 of file maglev-regalloc.cc.
                                                              {
  int num_temporaries_needed = node->num_temporaries_needed<RegisterT>();
  if (num_temporaries_needed == 0) return;
  DCHECK_GT(num_temporaries_needed, 0);
  RegListBase<RegisterT> temporaries = node->temporaries<RegisterT>();
  DCHECK(temporaries.is_empty());
  int remaining_temporaries_needed = num_temporaries_needed;
  // If the node is a ValueNode with a fixed result register, we should not
  // assign a temporary to the result register, nor its hint.
  RegListBase<RegisterT> reserved = GetReservedRegisters<RegisterT>(node);
  for (RegisterT reg : (registers.unblocked_free() - reserved)) {
    registers.block(reg);
    DCHECK(!temporaries.has(reg));
    temporaries.set(reg);
    if (--remaining_temporaries_needed == 0) break;
  }
  // Free extra registers if necessary.
  for (int i = 0; i < remaining_temporaries_needed; ++i) {
    DCHECK((registers.unblocked_free() - reserved).is_empty());
    RegisterT reg = FreeUnblockedRegister<RegisterT>(reserved);
    registers.block(reg);
    DCHECK(!temporaries.has(reg));
    temporaries.set(reg);
  }
  DCHECK_GE(temporaries.Count(), num_temporaries_needed);
  node->assign_temporaries(temporaries);
  if (v8_flags.trace_maglev_regalloc) {
    if constexpr (std::is_same_v<RegisterT, Register>) {
      printing_visitor_->os() << "Temporaries: " << temporaries << "\n";
    } else {
      printing_visitor_->os() << "Double Temporaries: " << temporaries << "\n";
    }
  }
}
References v8::internal::maglev::NodeBase::assign_temporaries(), v8::internal::maglev::RegisterFrameState< RegisterT >::block(), v8::internal::RegListBase< RegisterT >::Count(), DCHECK, DCHECK_GE, DCHECK_GT, v8::internal::RegListBase< RegisterT >::has(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::maglev::NodeBase::num_temporaries_needed(), v8::internal::RegListBase< RegisterT >::set(), v8::internal::maglev::NodeBase::temporaries(), v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free(), and v8::internal::v8_flags.
Referenced by AssignInputs().
AssignFixedInput()
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput (Input & input) [private]
Definition at line 1242 of file maglev-regalloc.cc.
                                                                    {
  compiler::UnallocatedOperand operand =
      compiler::UnallocatedOperand::cast(input.operand());
  ValueNode* node = input.node();
  compiler::InstructionOperand location = node->allocation();
  switch (operand.extended_policy()) {
    case compiler::UnallocatedOperand::MUST_HAVE_REGISTER:
      // Allocated in AssignArbitraryRegisterInput.
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os()
            << "- " << PrintNodeLabel(graph_labeller(), input.node())
            << " has arbitrary register\n";
      }
      return;
    case compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT:
      // Allocated in AssignAnyInput.
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os()
            << "- " << PrintNodeLabel(graph_labeller(), input.node())
            << " has arbitrary location\n";
      }
      return;
    case compiler::UnallocatedOperand::FIXED_REGISTER: {
      Register reg = Register::from_code(operand.fixed_register_index());
      input.SetAllocated(ForceAllocate(reg, node));
      break;
    }
    case compiler::UnallocatedOperand::FIXED_FP_REGISTER: {
      DoubleRegister reg =
          DoubleRegister::from_code(operand.fixed_register_index());
      input.SetAllocated(ForceAllocate(reg, node));
      break;
    }
    case compiler::UnallocatedOperand::REGISTER_OR_SLOT:
    case compiler::UnallocatedOperand::SAME_AS_INPUT:
    case compiler::UnallocatedOperand::NONE:
    case compiler::UnallocatedOperand::MUST_HAVE_SLOT:
      UNREACHABLE();
  }
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << "- " << PrintNodeLabel(graph_labeller(), input.node())
        << " in forced " << input.operand() << "\n";
  }
  compiler::AllocatedOperand allocated =
      compiler::AllocatedOperand::cast(input.operand());
  if (location != allocated) {
    AddMoveBeforeCurrentNode(node, location, allocated);
  }
  UpdateUse(&input);
  // Clear any hint that (probably) comes from this fixed use.
  input.node()->ClearHint();
}
References AddMoveBeforeCurrentNode(), v8::internal::maglev::ValueNode::allocation(), v8::internal::compiler::LocationOperand::cast(), v8::internal::maglev::ValueNode::ClearHint(), v8::internal::compiler::UnallocatedOperand::extended_policy(), v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, v8::internal::compiler::UnallocatedOperand::fixed_register_index(), ForceAllocate(), v8::internal::Register::from_code(), v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::from_code(), graph_labeller(), v8::internal::compiler::UnallocatedOperand::MUST_HAVE_REGISTER, v8::internal::compiler::UnallocatedOperand::MUST_HAVE_SLOT, v8::internal::maglev::Input::node(), v8::internal::compiler::UnallocatedOperand::NONE, v8::internal::maglev::ValueLocation::operand(), printing_visitor_, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT, v8::internal::compiler::UnallocatedOperand::REGISTER_OR_SLOT_OR_CONSTANT, v8::internal::compiler::UnallocatedOperand::SAME_AS_INPUT, v8::internal::maglev::ValueLocation::SetAllocated(), v8::internal::UNREACHABLE(), UpdateUse(), and v8::internal::v8_flags.
Referenced by AssignInputs().
AssignFixedTemporaries() [1/2]
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries (NodeBase * node) [private]
Definition at line 1975 of file maglev-regalloc.cc.
                                                                            {
  AssignFixedTemporaries(general_registers_, node);
  AssignFixedTemporaries(double_registers_, node);
}
AssignFixedTemporaries() [2/2]
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedTemporaries (RegisterFrameState< RegisterT > & registers, NodeBase * node) [private]
Definition at line 1945 of file maglev-regalloc.cc.
                                                              {
  RegListBase<RegisterT> fixed_temporaries = node->temporaries<RegisterT>();
  // Make sure that any initially set temporaries are definitely free.
  for (RegisterT reg : fixed_temporaries) {
    DCHECK(!registers.is_blocked(reg));
    if (!registers.free().has(reg)) {
      DropRegisterValue(registers, reg);
      registers.AddToFree(reg);
    }
    registers.block(reg);
  }
  if (v8_flags.trace_maglev_regalloc && !fixed_temporaries.is_empty()) {
    if constexpr (std::is_same_v<RegisterT, Register>) {
      printing_visitor_->os()
          << "Fixed Temporaries: " << fixed_temporaries << "\n";
    } else {
      printing_visitor_->os()
          << "Fixed Double Temporaries: " << fixed_temporaries << "\n";
    }
  }
  // After allocating the specific/fixed temporary registers, we empty the node
  // set, so that it is used to allocate only the arbitrary/available temporary
  // register that is going to be inserted in the scratch scope.
  node->temporaries<RegisterT>() = {};
}
References v8::internal::maglev::RegisterFrameState< RegisterT >::AddToFree(), v8::internal::maglev::RegisterFrameState< RegisterT >::block(), DCHECK, v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::RegisterFrameState< RegisterT >::is_blocked(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::maglev::NodeBase::temporaries(), and v8::internal::v8_flags.
Referenced by AssignInputs().
AssignInputs()
void v8::internal::maglev::StraightForwardRegisterAllocator::AssignInputs (NodeBase * node) [private]
Definition at line 1465 of file maglev-regalloc.cc.
                                                                  {
  // We allocate arbitrary register inputs after fixed inputs, since the fixed
  // inputs may clobber the arbitrarily chosen ones. Finally we assign the
  // location for the remaining inputs. Since inputs can alias a node, one of
  // the inputs could be assigned a register in AssignArbitraryRegisterInput
  // (and respectivelly its node location), therefore we wait until all
  // registers are allocated before assigning any location for these inputs.
  // TODO(dmercadier): consider using `ForAllInputsInRegallocAssignmentOrder` to
  // iterate the inputs. Since UseMarkingProcessor uses this helper to iterate
  // inputs, and it has to iterate them in the same order as this function,
  // using the iteration helper in both places would be better.
  for (Input& input : *node) AssignFixedInput(input);
  AssignFixedTemporaries(node);
  for (Input& input : *node) AssignArbitraryRegisterInput(node, input);
  AssignArbitraryTemporaries(node);
  for (Input& input : *node) AssignAnyInput(input);
}
References AssignAnyInput(), AssignArbitraryRegisterInput(), AssignArbitraryTemporaries(), AssignFixedInput(), and AssignFixedTemporaries().
Referenced by AllocateControlNode(), and AllocateNode().
ClearRegisterValues()
void v8::internal::maglev::StraightForwardRegisterAllocator::ClearRegisterValues () [private]
Definition at line 2069 of file maglev-regalloc.cc.
                                                           {
  auto ClearRegisterState = [&](auto& registers) {
    while (!registers.used().is_empty()) {
      auto reg = registers.used().first();
      ValueNode* node = registers.GetValue(reg);
      registers.FreeRegistersUsedBy(node);
      DCHECK(!registers.used().has(reg));
    }
  };
  ClearRegisterState(general_registers_);
  ClearRegisterState(double_registers_);
  // All registers should be free by now.
  DCHECK_EQ(general_registers_.unblocked_free(),
            MaglevAssembler::GetAllocatableRegisters());
  DCHECK_EQ(double_registers_.unblocked_free(),
            MaglevAssembler::GetAllocatableDoubleRegisters());
}
References DCHECK, and DCHECK_EQ.
Referenced by AllocateRegisters().
ComputePostDominatingHoles()
void v8::internal::maglev::StraightForwardRegisterAllocator::ComputePostDominatingHoles () [private]
Definition at line 306 of file maglev-regalloc.cc.
                                                                  {
  // For all blocks, find the list of jumps that jump over code unreachable from
  // the block. Such a list of jumps terminates in return or jumploop.
  for (BasicBlock* block : base::Reversed(*graph_)) {
    ControlNode* control = block->control_node();
    if (auto unconditional_control =
            control->TryCast<UnconditionalControlNode>()) {
      // If the current control node is a jump, prepend it to the list of jumps
      // at the target.
      control->set_next_post_dominating_hole(NearestPostDominatingHole(
          unconditional_control->target()->control_node()));
    } else if (auto branch = control->TryCast<BranchControlNode>()) {
      ControlNode* first =
          NearestPostDominatingHole(branch->if_true()->control_node());
      ControlNode* second =
          NearestPostDominatingHole(branch->if_false()->control_node());
      control->set_next_post_dominating_hole(
          HighestPostDominatingHole(first, second));
    } else if (auto switch_node = control->TryCast<Switch>()) {
      int num_targets =
          switch_node->size() + (switch_node->has_fallthrough() ? 1 : 0);
      if (num_targets == 1) {
        // If we have a single target, the next post dominating hole
        // is the same one as the target.
        DCHECK(!switch_node->has_fallthrough());
        control->set_next_post_dominating_hole(NearestPostDominatingHole(
            switch_node->targets()[0].block_ptr()->control_node()));
        continue;
      }
      // Calculate the post dominating hole for each target.
      base::SmallVector<ControlNode*, 16> holes(num_targets);
      for (int i = 0; i < switch_node->size(); i++) {
        holes[i] = NearestPostDominatingHole(
            switch_node->targets()[i].block_ptr()->control_node());
      }
      if (switch_node->has_fallthrough()) {
        holes[switch_node->size()] = NearestPostDominatingHole(
            switch_node->fallthrough()->control_node());
      }
      control->set_next_post_dominating_hole(HighestPostDominatingHole(holes));
    }
  }
}
References v8::internal::DCHECK(), graph_, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole(), v8::base::Reversed(), v8::internal::maglev::ControlNode::set_next_post_dominating_hole(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by StraightForwardRegisterAllocator().
DropRegisterValue() [1/3]
void v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue (DoubleRegister reg) [private]
Definition at line 953 of file maglev-regalloc.cc.
                                                                           {
  DropRegisterValue<DoubleRegister>(double_registers_, reg);
}
References double_registers_.
DropRegisterValue() [2/3]
void v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue (Register reg) [private]
Definition at line 949 of file maglev-regalloc.cc.
                                                                     {
  DropRegisterValue<Register>(general_registers_, reg);
}
References general_registers_.
DropRegisterValue() [3/3]
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue (RegisterFrameState< RegisterT > & registers, RegisterT reg, bool force_spill = false) [private]
Definition at line 907 of file maglev-regalloc.cc.
                                                                               {
  // The register should not already be free.
  DCHECK(!registers.free().has(reg));
  ValueNode* node = registers.GetValue(reg);
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os() << " dropping " << reg << " value "
                            << PrintNodeLabel(graph_labeller(), node) << "\n";
  }
  MachineRepresentation mach_repr = node->GetMachineRepresentation();
  // Remove the register from the node's list.
  node->RemoveRegister(reg);
  // Return if the removed value already has another register or is loadable
  // from memory.
  if (node->has_register() || node->is_loadable()) return;
  // Try to move the value to another register. Do so without blocking that
  // register, as we may still want to use it elsewhere.
  if (!registers.UnblockedFreeIsEmpty() && !force_spill) {
    RegisterT target_reg = registers.unblocked_free().first();
    RegisterT hint_reg = node->GetRegisterHint<RegisterT>();
    if (hint_reg.is_valid() && registers.unblocked_free().has(hint_reg)) {
      target_reg = hint_reg;
    }
    registers.RemoveFromFree(target_reg);
    registers.SetValueWithoutBlocking(target_reg, node);
    // Emit a gapmove.
    compiler::AllocatedOperand source(compiler::LocationOperand::REGISTER,
                                      mach_repr, reg.code());
    compiler::AllocatedOperand target(compiler::LocationOperand::REGISTER,
                                      mach_repr, target_reg.code());
    AddMoveBeforeCurrentNode(node, source, target);
    return;
  }
  // If all else fails, spill the value.
  Spill(node);
}
References AddMoveBeforeCurrentNode(), v8::internal::DCHECK(), v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::ValueNode::GetMachineRepresentation(), v8::internal::maglev::ValueNode::GetRegisterHint(), v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), graph_labeller(), v8::internal::maglev::ValueNode::has_register(), v8::internal::maglev::ValueNode::is_loadable(), printing_visitor_, v8::internal::compiler::LocationOperand::REGISTER, v8::internal::maglev::RegisterFrameState< RegisterT >::RemoveFromFree(), v8::internal::maglev::ValueNode::RemoveRegister(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking(), Spill(), v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free(), v8::internal::maglev::RegisterFrameState< RegisterT >::UnblockedFreeIsEmpty(), and v8::internal::v8_flags.
Referenced by DropRegisterValueAtEnd(), and MarkAsClobbered().
DropRegisterValueAtEnd()
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValueAtEnd (RegisterT reg, bool force_spill = false) [private]
Definition at line 804 of file maglev-regalloc.cc.
                                     {
  RegisterFrameState<RegisterT>& list = GetRegisterFrameState<RegisterT>();
  list.unblock(reg);
  if (!list.free().has(reg)) {
    ValueNode* node = list.GetValue(reg);
    // If the register is not live after the current node, just remove its
    // value.
    if (IsCurrentNodeLastUseOf(node)) {
      node->RemoveRegister(reg);
    } else {
      DropRegisterValue(list, reg, force_spill);
    }
    list.AddToFree(reg);
  }
}
References v8::internal::maglev::RegisterFrameState< RegisterT >::AddToFree(), DropRegisterValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), IsCurrentNodeLastUseOf(), v8::internal::maglev::ValueNode::RemoveRegister(), and v8::internal::maglev::RegisterFrameState< RegisterT >::unblock().
Referenced by AllocateNodeResult().
EnsureFreeRegisterAtEnd()
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::EnsureFreeRegisterAtEnd (const compiler::InstructionOperand & hint = compiler::InstructionOperand()) [private]
Definition at line 1790 of file maglev-regalloc.cc.
                                            {
  RegisterFrameState<RegisterT>& registers = GetRegisterFrameState<RegisterT>();
  // If we still have free registers, pick one of those.
  if (!registers.unblocked_free().is_empty()) return;
  // If the current node is a last use of an input, pick a register containing
  // the input. Prefer the hint register if available.
  RegisterT hint_reg = GetRegisterHint<RegisterT>(hint);
  if (!registers.free().has(hint_reg) && registers.blocked().has(hint_reg) &&
      IsCurrentNodeLastUseOf(registers.GetValue(hint_reg))) {
    DropRegisterValueAtEnd(hint_reg);
    return;
  }
  // Only search in the used-blocked list, since we don't want to assign the
  // result register to a temporary (free + blocked).
  for (RegisterT reg : (registers.blocked() - registers.free())) {
    if (IsCurrentNodeLastUseOf(registers.GetValue(reg))) {
      DropRegisterValueAtEnd(reg);
      return;
    }
  }
  // Pick any input-blocked register based on regular heuristics.
  RegisterT reg = hint.IsInvalid()
                      ? PickRegisterToFree<RegisterT>(registers.empty())
                      : GetRegisterHint<RegisterT>(hint);
  DropRegisterValueAtEnd(reg);
}
References v8::internal::maglev::RegisterFrameState< RegisterT >::blocked(), v8::internal::maglev::RegisterFrameState< RegisterT >::empty(), v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), and v8::internal::maglev::RegisterFrameState< RegisterT >::unblocked_free().
ForceAllocate() [1/4]
compiler::AllocatedOperand v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate (const Input & input, ValueNode * node) [private]
Definition at line 1872 of file maglev-regalloc.cc.
                                         {
  if (input.IsDoubleRegister()) {
    DoubleRegister reg = input.AssignedDoubleRegister();
    DropRegisterValueAtEnd(reg);
    return ForceAllocate(reg, node);
  } else {
    Register reg = input.AssignedGeneralRegister();
    DropRegisterValueAtEnd(reg);
    return ForceAllocate(reg, node);
  }
}
References v8::internal::maglev::ValueLocation::AssignedDoubleRegister(), v8::internal::maglev::ValueLocation::AssignedGeneralRegister(), and v8::internal::maglev::ValueLocation::IsDoubleRegister().
ForceAllocate() [2/4]
compiler::AllocatedOperand v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate (DoubleRegister reg, ValueNode * node) [private]
Definition at line 1866 of file maglev-regalloc.cc.
                                         {
  DCHECK(node->use_double_register());
  return ForceAllocate<DoubleRegister>(double_registers_, reg, node);
}
References DCHECK, and v8::internal::maglev::ValueNode::use_double_register().
ForceAllocate() [3/4]
compiler::AllocatedOperand v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate (Register reg, ValueNode * node) [private]
Definition at line 1860 of file maglev-regalloc.cc.
                                   {
  DCHECK(!node->use_double_register());
  return ForceAllocate<Register>(general_registers_, reg, node);
}
References DCHECK, and v8::internal::maglev::ValueNode::use_double_register().
ForceAllocate() [4/4]
template<typename RegisterT >
compiler::AllocatedOperand v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate (RegisterFrameState< RegisterT > & registers, RegisterT reg, ValueNode * node) [private]
Definition at line 1832 of file maglev-regalloc.cc.
                                                                              {
  DCHECK(!registers.is_blocked(reg));
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << " forcing " << reg << " to "
        << PrintNodeLabel(graph_labeller(), node) << "...\n";
  }
  if (registers.free().has(reg)) {
    // If it's already free, remove it from the free list.
    registers.RemoveFromFree(reg);
  } else if (registers.GetValue(reg) == node) {
    registers.block(reg);
    return compiler::AllocatedOperand(compiler::LocationOperand::REGISTER,
                                      node->GetMachineRepresentation(),
                                      reg.code());
  } else {
    DCHECK(!registers.is_blocked(reg));
    DropRegisterValue(registers, reg);
  }
  DCHECK(!registers.free().has(reg));
  registers.unblock(reg);
  registers.SetValue(reg, node);
  return compiler::AllocatedOperand(compiler::LocationOperand::REGISTER,
                                    node->GetMachineRepresentation(),
                                    reg.code());
}
References v8::internal::maglev::RegisterFrameState< RegisterT >::block(), DCHECK, v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::ValueNode::GetMachineRepresentation(), v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::is_blocked(), v8::internal::maglev::RegisterFrameState< RegisterT >::RemoveFromFree(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue(), v8::internal::maglev::RegisterFrameState< RegisterT >::unblock(), and v8::internal::v8_flags.
Referenced by AllocateNodeResult(), AllocateRegisters(), AssignFixedInput(), and TryAllocateToInput().
ForEachMergePointRegisterState()
template<typename Function >
void v8::internal::maglev::StraightForwardRegisterAllocator::ForEachMergePointRegisterState (MergePointRegisterState & merge_point_state, Function && f) [private]
Definition at line 2057 of file maglev-regalloc.cc.
                                                              {
  merge_point_state.ForEachGeneralRegister(
      [&](Register reg, RegisterState& state) {
        f(general_registers_, reg, state);
      });
  merge_point_state.ForEachDoubleRegister(
      [&](DoubleRegister reg, RegisterState& state) {
        f(double_registers_, reg, state);
      });
}
FreeRegistersUsedBy()
void v8::internal::maglev::StraightForwardRegisterAllocator::FreeRegistersUsedBy (ValueNode * node) [private]
Definition at line 625 of file maglev-regalloc.cc.
                                                                          {
  if (node->use_double_register()) {
    double_registers_.FreeRegistersUsedBy(node);
  } else {
    general_registers_.FreeRegistersUsedBy(node);
  }
}
References double_registers_, general_registers_, and v8::internal::maglev::ValueNode::use_double_register().
Referenced by AllocateNodeResult(), and UpdateUse().
FreeUnblockedRegister()
template<typename RegisterT >
RegisterT v8::internal::maglev::StraightForwardRegisterAllocator::FreeUnblockedRegister (RegListBase< RegisterT > reserved = RegListBase<RegisterT>()) [private]
Definition at line 1746 of file maglev-regalloc.cc.
                                     {
  RegisterFrameState<RegisterT>& registers = GetRegisterFrameState<RegisterT>();
  RegisterT best =
      PickRegisterToFree<RegisterT>(registers.blocked() | reserved);
  DCHECK(best.is_valid());
  DCHECK(!registers.is_blocked(best));
  DropRegisterValue(registers, best);
  registers.AddToFree(best);
  return best;
}
References v8::internal::maglev::RegisterFrameState< RegisterT >::AddToFree(), v8::internal::maglev::RegisterFrameState< RegisterT >::blocked(), DCHECK, and v8::internal::maglev::RegisterFrameState< RegisterT >::is_blocked().
GetRegisterFrameState()
template<typename RegisterT >
RegisterFrameState<RegisterT>& v8::internal::maglev::StraightForwardRegisterAllocator::GetRegisterFrameState () [inline], [private]
Definition at line 240 of file maglev-regalloc.h.
                                                         {
    if constexpr (std::is_same_v<RegisterT, Register>) {
      return general_registers_;
    } else {
      return double_registers_;
    }
  }
References double_registers_, and general_registers_.
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::StraightForwardRegisterAllocator::graph_labeller () const [inline], [private]
Definition at line 306 of file maglev-regalloc.h.
                                              {
    return graph_->graph_labeller();
  }
References graph_, and v8::internal::maglev::Graph::graph_labeller().
Referenced by AddMoveBeforeCurrentNode(), AllocateNode(), AllocateRegisters(), AssignAnyInput(), AssignArbitraryRegisterInput(), AssignFixedInput(), DropRegisterValue(), Spill(), SpillAndClearRegisters(), UpdateUse(), VerifyInputs(), and VerifyRegisterState().
has_graph_labeller()
bool v8::internal::maglev::StraightForwardRegisterAllocator::has_graph_labeller () const [inline], [private]
Definition at line 304 of file maglev-regalloc.h.
{ return graph_->has_graph_labeller(); }
References graph_, and v8::internal::maglev::Graph::has_graph_labeller().
Referenced by VerifyRegisterState().
HoistLoopReloads()
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads (BasicBlock * target, RegisterFrameState< RegisterT > & registers) [private]
Definition at line 2169 of file maglev-regalloc.cc.
                                                                  {
  auto info = regalloc_info_->loop_info_.find(target->id());
  if (info == regalloc_info_->loop_info_.end()) return;
  for (ValueNode* node : info->second.reload_hints_) {
    DCHECK(general_registers_.blocked().is_empty());
    if (registers.free().is_empty()) break;
    if (node->has_register()) continue;
    // The value is in a liveness hole, don't try to reload it.
    if (!node->is_loadable()) continue;
    if ((node->use_double_register() && std::is_same_v<RegisterT, Register>) ||
        (!node->use_double_register() &&
         std::is_same_v<RegisterT, DoubleRegister>)) {
      continue;
    }
    RegisterT target_reg = node->GetRegisterHint<RegisterT>();
    if (!registers.free().has(target_reg)) {
      target_reg = registers.free().first();
    }
    compiler::AllocatedOperand target_operand(
        compiler::LocationOperand::REGISTER, node->GetMachineRepresentation(),
        target_reg.code());
    registers.RemoveFromFree(target_reg);
    registers.SetValueWithoutBlocking(target_reg, node);
    AddMoveBeforeCurrentNode(node, node->loadable_slot(), target_operand);
  }
}
References DCHECK, v8::internal::maglev::RegisterFrameState< RegisterT >::free(), v8::internal::maglev::ValueNode::GetMachineRepresentation(), v8::internal::maglev::ValueNode::GetRegisterHint(), v8::internal::maglev::ValueNode::has_register(), v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::ValueNode::is_loadable(), v8::internal::maglev::ValueNode::loadable_slot(), v8::internal::maglev::RegisterFrameState< RegisterT >::RemoveFromFree(), v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking(), and v8::internal::maglev::ValueNode::use_double_register().
HoistLoopSpills()
void v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopSpills (BasicBlock * target) [private]
Definition at line 2200 of file maglev-regalloc.cc.
                                                                         {
  auto info = regalloc_info_->loop_info_.find(target->id());
  if (info == regalloc_info_->loop_info_.end()) return;
  for (ValueNode* node : info->second.spill_hints_) {
    if (!node->has_register()) continue;
    // Do not move to a different register, the goal is to keep the value
    // spilled on the back-edge.
    const bool kForceSpill = true;
    if (node->use_double_register()) {
      for (DoubleRegister reg : node->result_registers<DoubleRegister>()) {
        DropRegisterValueAtEnd(reg, kForceSpill);
      }
    } else {
      for (Register reg : node->result_registers<Register>()) {
        DropRegisterValueAtEnd(reg, kForceSpill);
      }
    }
  }
}
References v8::internal::maglev::ValueNode::has_register(), v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::ValueNode::result_registers(), and v8::internal::maglev::ValueNode::use_double_register().
InitializeBranchTargetPhis()
void v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis (int predecessor_id, BasicBlock * target) [private]
Definition at line 957 of file maglev-regalloc.cc.
                                            {
  DCHECK(!target->is_edge_split_block());
  if (!target->has_phi()) return;
  // Phi moves are emitted by resolving all phi moves as a single parallel move,
  // which means we shouldn't update register state as we go (as if we were
  // emitting a series of serialised moves) but rather take 'old' register
  // state as the phi input.
  Phi::List& phis = *target->phis();
  for (auto phi_it = phis.begin(); phi_it != phis.end();) {
    Phi* phi = *phi_it;
    if (!phi->has_valid_live_range()) {
      // We might still have left over dead Phis, due to phis being kept
      // alive by deopts that the representation analysis dropped. Clear
      // them out now.
      phi_it = phis.RemoveAt(phi_it);
    } else {
      Input& input = phi->input(predecessor_id);
      input.InjectLocation(input.node()->allocation());
      ++phi_it;
    }
  }
}
References v8::internal::maglev::ValueNode::allocation(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), v8::internal::DCHECK(), v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::end(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::ValueLocation::InjectLocation(), v8::internal::maglev::BasicBlock::is_edge_split_block(), v8::internal::maglev::Input::node(), v8::internal::maglev::BasicBlock::phis(), and v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::RemoveAt().
Referenced by AllocateControlNode().
InitializeBranchTargetRegisterValues()
void v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetRegisterValues (ControlNode * source, BasicBlock * target) [private]
Definition at line 2220 of file maglev-regalloc.cc.
                                             {
  MergePointRegisterState& target_state = target->state()->register_state();
  DCHECK(!target_state.is_initialized());
  auto init = [&](auto& registers, auto reg, RegisterState& state) {
    ValueNode* node = nullptr;
    DCHECK(registers.blocked().is_empty());
    if (!registers.free().has(reg)) {
      node = registers.GetValue(reg);
      if (!IsLiveAtTarget(node, source, target)) node = nullptr;
    }
    state = {node, initialized_node};
  };
  HoistLoopReloads(target, general_registers_);
  HoistLoopReloads(target, double_registers_);
  HoistLoopSpills(target);
  ForEachMergePointRegisterState(target_state, init);
}
References DCHECK, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::initialized_node, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::MergePointInterpreterFrameState::register_state(), and v8::internal::maglev::BasicBlock::state().
Referenced by InitializeConditionalBranchTarget().
InitializeConditionalBranchTarget()
void v8::internal::maglev::StraightForwardRegisterAllocator::InitializeConditionalBranchTarget (ConditionalControlNode * source, BasicBlock * target) [private]
Definition at line 1015 of file maglev-regalloc.cc.
                                                              {
  DCHECK(!target->has_phi());
  if (target->has_state()) {
    // Not a fall-through branch, copy the state over.
    return InitializeBranchTargetRegisterValues(control_node, target);
  }
  if (target->is_edge_split_block()) {
    return InitializeEmptyBlockRegisterValues(control_node, target);
  }
  DCHECK_EQ(control_node->id() + 1, target->first_id());
  DCHECK(AllUsedRegistersLiveAt(control_node, target));
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::maglev::BasicBlock::first_id(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::BasicBlock::has_state(), v8::internal::maglev::NodeBase::id(), InitializeBranchTargetRegisterValues(), InitializeEmptyBlockRegisterValues(), and v8::internal::maglev::BasicBlock::is_edge_split_block().
Referenced by AllocateControlNode().
InitializeEmptyBlockRegisterValues()
void v8::internal::maglev::StraightForwardRegisterAllocator::InitializeEmptyBlockRegisterValues (ControlNode * source, BasicBlock * target) [private]
Definition at line 2239 of file maglev-regalloc.cc.
                                             {
  DCHECK(target->is_edge_split_block());
  MergePointRegisterState* register_state =
      compilation_info_->zone()->New<MergePointRegisterState>();
  DCHECK(!register_state->is_initialized());
  auto init = [&](auto& registers, auto reg, RegisterState& state) {
    ValueNode* node = nullptr;
    DCHECK(registers.blocked().is_empty());
    if (!registers.free().has(reg)) {
      node = registers.GetValue(reg);
      if (!IsLiveAtTarget(node, source, target)) node = nullptr;
    }
    state = {node, initialized_node};
  };
  ForEachMergePointRegisterState(*register_state, init);
  target->set_edge_split_block_register_state(register_state);
}
References DCHECK, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::initialized_node, v8::internal::maglev::BasicBlock::is_edge_split_block(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), and v8::internal::maglev::BasicBlock::set_edge_split_block_register_state().
Referenced by InitializeConditionalBranchTarget().
InitializeRegisterValues()
void v8::internal::maglev::StraightForwardRegisterAllocator::InitializeRegisterValues (MergePointRegisterState & target_state) [private]
Definition at line 2089 of file maglev-regalloc.cc.
                                           {
  // First clear the register state.
  ClearRegisterValues();
  // Then fill it in with target information.
  auto fill = [&](auto& registers, auto reg, RegisterState& state) {
    ValueNode* node;
    RegisterMerge* merge;
    LoadMergeState(state, &node, &merge);
    if (node != nullptr) {
      registers.RemoveFromFree(reg);
      registers.SetValue(reg, node);
    } else {
      DCHECK(!state.GetPayload().is_merge);
    }
  };
  ForEachMergePointRegisterState(target_state, fill);
  // SetValue will have blocked registers, unblock them.
  general_registers_.clear_blocked();
  double_registers_.clear_blocked();
}
References DCHECK, and v8::internal::maglev::LoadMergeState().
Referenced by AllocateRegisters().
IsCurrentNodeLastUseOf()
bool v8::internal::maglev::StraightForwardRegisterAllocator::IsCurrentNodeLastUseOf (ValueNode * node) [private]
Definition at line 1785 of file maglev-regalloc.cc.
                                                                             {
  return node->live_range().end == current_node_->id();
}
References v8::internal::maglev::ValueNode::LiveRange::end, and v8::internal::maglev::ValueNode::live_range().
Referenced by DropRegisterValueAtEnd().
MarkAsClobbered()
void v8::internal::maglev::StraightForwardRegisterAllocator::MarkAsClobbered (ValueNode * node, const compiler::AllocatedOperand & location) [private]
Definition at line 1302 of file maglev-regalloc.cc.
                                                               {
  if (node->use_double_register()) {
    DoubleRegister reg = location.GetDoubleRegister();
    DCHECK(double_registers_.is_blocked(reg));
    DropRegisterValue(reg);
    double_registers_.AddToFree(reg);
  } else {
    Register reg = location.GetRegister();
    DCHECK(general_registers_.is_blocked(reg));
    DropRegisterValue(reg);
    general_registers_.AddToFree(reg);
  }
}
References v8::internal::DCHECK(), double_registers_, DropRegisterValue(), general_registers_, v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::LocationOperand::GetRegister(), and v8::internal::maglev::ValueNode::use_double_register().
Referenced by AssignArbitraryRegisterInput().
MergeRegisterValues()
void v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues (ControlNode * control, BasicBlock * target, int predecessor_id) [private]
Definition at line 2260 of file maglev-regalloc.cc.
                                                                               {
  if (target->is_edge_split_block()) {
    return InitializeEmptyBlockRegisterValues(control, target);
  }
  MergePointRegisterState& target_state = target->state()->register_state();
  if (!target_state.is_initialized()) {
    // This is the first block we're merging, initialize the values.
    return InitializeBranchTargetRegisterValues(control, target);
  }
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os() << "Merging registers...\n";
  }
  int predecessor_count = target->state()->predecessor_count();
  auto merge = [&](auto& registers, auto reg, RegisterState& state) {
    ValueNode* node;
    RegisterMerge* merge;
    LoadMergeState(state, &node, &merge);
    // This isn't quite the right machine representation for Int32 nodes, but
    // those are stored in the same registers as Tagged nodes so in this case it
    // doesn't matter.
    MachineRepresentation mach_repr = std::is_same_v<decltype(reg), Register>
                                          ? MachineRepresentation::kTagged
                                          : MachineRepresentation::kFloat64;
    compiler::AllocatedOperand register_info = {
        compiler::LocationOperand::REGISTER, mach_repr, reg.code()};
    ValueNode* incoming = nullptr;
    DCHECK(registers.blocked().is_empty());
    if (!registers.free().has(reg)) {
      incoming = registers.GetValue(reg);
      if (!IsLiveAtTarget(incoming, control, target)) {
        if (v8_flags.trace_maglev_regalloc) {
          printing_visitor_->os() << " " << reg << " - incoming node "
                                  << PrintNodeLabel(graph_labeller(), incoming)
                                  << " dead at target\n";
        }
        incoming = nullptr;
      }
    }
    if (incoming == node) {
      // We're using the same register as the target already has. If registers
      // are merged, add input information.
      if (v8_flags.trace_maglev_regalloc) {
        if (node) {
          printing_visitor_->os()
              << " " << reg << " - incoming node same as node: "
              << PrintNodeLabel(graph_labeller(), node) << "\n";
        }
      }
      if (merge) merge->operand(predecessor_id) = register_info;
      return;
    }
    if (node == nullptr) {
      // Don't load new nodes at loop headers.
      if (control->Is<JumpLoop>()) return;
    } else if (!node->is_loadable() && !node->has_register()) {
      // If we have a node already, but can't load it here, we must be in a
      // liveness hole for it, so nuke the merge state.
      // This can only happen for conversion nodes, as they can split and take
      // over the liveness of the node they are converting.
      // TODO(v8:7700): Overeager DCHECK.
      // DCHECK(node->properties().is_conversion());
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os() << " " << reg << " - can't load "
                                << PrintNodeLabel(graph_labeller(), node)
                                << ", dropping the merge\n";
      }
      // We always need to be able to restore values on JumpLoop since the value
      // is definitely live at the loop header.
      CHECK(!control->Is<JumpLoop>());
      state = {nullptr, initialized_node};
      return;
    }
    if (merge) {
      // The register is already occupied with a different node. Figure out
      // where that node is allocated on the incoming branch.
      merge->operand(predecessor_id) = node->allocation();
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os() << " " << reg << " - merge: loading "
                                << PrintNodeLabel(graph_labeller(), node)
                                << " from " << node->allocation() << " \n";
      }
      if (incoming != nullptr) {
        // If {incoming} isn't loadable or available in a register, then we are
        // in a liveness hole, and none of its uses should be reachable from
        // {target} (for simplicity/speed, we only check the first and last use
        // though).
        DCHECK_IMPLIES(
            !incoming->is_loadable() && !IsInRegister(target_state, incoming),
            !IsForwardReachable(target, incoming->current_next_use(),
                                incoming->live_range().end));
      }
      return;
    }
    DCHECK_IMPLIES(node == nullptr, incoming != nullptr);
    if (node == nullptr && !incoming->is_loadable()) {
      // If the register is unallocated at the merge point, and the incoming
      // value isn't spilled, that means we must have seen it already in a
      // different register.
      // This maybe not be true for conversion nodes, as they can split and take
      // over the liveness of the node they are converting.
      // TODO(v8:7700): This DCHECK is overeager, {incoming} can be a Phi node
      // containing conversion nodes.
      // DCHECK_IMPLIES(!IsInRegister(target_state, incoming),
      // incoming->properties().is_conversion());
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os()
            << " " << reg << " - can't load incoming "
            << PrintNodeLabel(graph_labeller(), incoming) << ", bailing out\n";
      }
      return;
    }
    const size_t size = sizeof(RegisterMerge) +
                        predecessor_count * sizeof(compiler::AllocatedOperand);
    void* buffer = compilation_info_->zone()->Allocate<void*>(size);
    merge = new (buffer) RegisterMerge();
    merge->node = node == nullptr ? incoming : node;
    // If the register is unallocated at the merge point, allocation so far
    // is the loadable slot for the incoming value. Otherwise all incoming
    // branches agree that the current node is in the register info.
    compiler::InstructionOperand info_so_far =
        node == nullptr ? incoming->loadable_slot() : register_info;
    // Initialize the entire array with info_so_far since we don't know in
    // which order we've seen the predecessors so far. Predecessors we
    // haven't seen yet will simply overwrite their entry later.
    for (int i = 0; i < predecessor_count; i++) {
      merge->operand(i) = info_so_far;
    }
    // If the register is unallocated at the merge point, fill in the
    // incoming value. Otherwise find the merge-point node in the incoming
    // state.
    if (node == nullptr) {
      merge->operand(predecessor_id) = register_info;
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os() << " " << reg << " - new merge: loading new "
                                << PrintNodeLabel(graph_labeller(), incoming)
                                << " from " << register_info << " \n";
      }
    } else {
      merge->operand(predecessor_id) = node->allocation();
      if (v8_flags.trace_maglev_regalloc) {
        printing_visitor_->os() << " " << reg << " - new merge: loading "
                                << PrintNodeLabel(graph_labeller(), node)
                                << " from " << node->allocation() << " \n";
      }
    }
    state = {merge, initialized_merge};
  };
  ForEachMergePointRegisterState(target_state, merge);
}
References v8::internal::maglev::ValueNode::allocation(), CHECK, v8::internal::maglev::ValueNode::current_next_use(), DCHECK, DCHECK_IMPLIES, v8::internal::maglev::ValueNode::LiveRange::end, v8::internal::maglev::ValueNode::has_register(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::initialized_merge, v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::initialized_node, v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::BasicBlock::is_edge_split_block(), v8::internal::maglev::ValueNode::is_loadable(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::ValueNode::live_range(), v8::internal::maglev::ValueNode::loadable_slot(), v8::internal::maglev::LoadMergeState(), v8::internal::maglev::RegisterMerge::node, v8::internal::maglev::RegisterMerge::operand(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_count(), v8::internal::maglev::MergePointInterpreterFrameState::register_state(), size(), v8::internal::maglev::BasicBlock::state(), and v8::internal::v8_flags.
Referenced by AllocateControlNode().
PickRegisterToFree()
template<typename RegisterT >
RegisterT v8::internal::maglev::StraightForwardRegisterAllocator::PickRegisterToFree (RegListBase< RegisterT > reserved) [private]
Definition at line 1714 of file maglev-regalloc.cc.
                                     {
  RegisterFrameState<RegisterT>& registers = GetRegisterFrameState<RegisterT>();
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os() << " need to free a register... ";
  }
  int furthest_use = 0;
  RegisterT best = RegisterT::no_reg();
  for (RegisterT reg : (registers.used() - reserved)) {
    ValueNode* value = registers.GetValue(reg);
    // The cheapest register to clear is a register containing a value that's
    // contained in another register as well. Since we found the register while
    // looping over unblocked registers, we can simply use this register.
    if (value->num_registers() > 1) {
      best = reg;
      break;
    }
    int use = value->current_next_use();
    if (use > furthest_use) {
      furthest_use = use;
      best = reg;
    }
  }
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << " chose " << best << " with next use " << furthest_use << "\n";
  }
  return best;
}
References v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), v8::internal::no_reg, use(), v8::internal::maglev::RegisterFrameState< RegisterT >::used(), v8::internal::v8_flags, and v8::internal::value.
PrintLiveRegs()
void v8::internal::maglev::StraightForwardRegisterAllocator::PrintLiveRegs () const [private]
Definition at line 350 of file maglev-regalloc.cc.
                                                           {
  bool first = true;
  auto print = [&](auto reg, ValueNode* node) {
    if (first) {
      first = false;
    } else {
      printing_visitor_->os() << ", ";
    }
    printing_visitor_->os() << reg << "=v" << node->id();
  };
  general_registers_.ForEachUsedRegister(print);
  double_registers_.ForEachUsedRegister(print);
}
References double_registers_, general_registers_, and printing_visitor_.
Referenced by AllocateNode(), and AllocateRegisters().
SaveRegisterSnapshot()
void v8::internal::maglev::StraightForwardRegisterAllocator::SaveRegisterSnapshot (NodeBase * node) [private]
Definition at line 1614 of file maglev-regalloc.cc.
                                                                          {
  RegisterSnapshot snapshot;
  general_registers_.ForEachUsedRegister([&](Register reg, ValueNode* node) {
    if (node->properties().value_representation() ==
        ValueRepresentation::kTagged) {
      snapshot.live_tagged_registers.set(reg);
    }
  });
  snapshot.live_registers = general_registers_.used();
  snapshot.live_double_registers = double_registers_.used();
  // If a value node, then the result register is removed from the snapshot.
  if (ValueNode* value_node = node->TryCast<ValueNode>()) {
    if (value_node->use_double_register()) {
      snapshot.live_double_registers.clear(
          ToDoubleRegister(value_node->result()));
    } else {
      Register reg = ToRegister(value_node->result());
      snapshot.live_registers.clear(reg);
      snapshot.live_tagged_registers.clear(reg);
    }
  }
  if (node->properties().can_eager_deopt()) {
    // If we eagerly deopt after a deferred call, the registers saved by the
    // runtime call might not include the inputs into the eager deopt. Here, we
    // make sure that all the eager deopt registers are included in the
    // snapshot.
    InputLocation* input = node->eager_deopt_info()->input_locations();
    node->eager_deopt_info()->ForEachInput([&](ValueNode* node) {
      if (input->IsAnyRegister()) {
        if (input->IsDoubleRegister()) {
          snapshot.live_double_registers.set(input->AssignedDoubleRegister());
        } else {
          snapshot.live_registers.set(input->AssignedGeneralRegister());
          if (node->is_tagged()) {
            snapshot.live_tagged_registers.set(
                input->AssignedGeneralRegister());
          }
        }
      }
      input++;
    });
  }
  node->set_register_snapshot(snapshot);
}
References v8::internal::maglev::OpProperties::can_eager_deopt(), v8::internal::RegListBase< RegisterT >::clear(), double_registers_, v8::internal::maglev::NodeBase::eager_deopt_info(), v8::internal::maglev::EagerDeoptInfo::ForEachInput(), general_registers_, v8::internal::maglev::DeoptInfo::input_locations(), v8::internal::maglev::ValueLocation::IsAnyRegister(), v8::internal::maglev::kTagged, v8::internal::maglev::RegisterSnapshot::live_double_registers, v8::internal::maglev::RegisterSnapshot::live_registers, v8::internal::maglev::RegisterSnapshot::live_tagged_registers, v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::ToDoubleRegister(), v8::internal::maglev::ToRegister(), v8::internal::maglev::NodeBase::TryCast(), and v8::internal::maglev::OpProperties::value_representation().
Referenced by AllocateNode().
SetLoopPhiRegisterHint()
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::SetLoopPhiRegisterHint (Phi * phi, RegisterT reg) [private]
Definition at line 1157 of file maglev-regalloc.cc.
                                                                             {
  compiler::UnallocatedOperand hint(
      std::is_same_v<RegisterT, Register>
          ? compiler::UnallocatedOperand::FIXED_REGISTER
          : compiler::UnallocatedOperand::FIXED_FP_REGISTER,
      reg.code(), kNoVreg);
  for (Input& input : *phi) {
    if (input.node()->id() > phi->id()) {
      input.node()->SetHint(hint);
    }
  }
}
References v8::internal::compiler::UnallocatedOperand::FIXED_FP_REGISTER, v8::internal::compiler::UnallocatedOperand::FIXED_REGISTER, and v8::internal::maglev::kNoVreg.
Referenced by AllocateRegisters(), and TryAllocateToInput().
Spill()
void v8::internal::maglev::StraightForwardRegisterAllocator::Spill (ValueNode * node) [private]
Definition at line 1232 of file maglev-regalloc.cc.
                                                            {
  if (node->is_loadable()) return;
  AllocateSpillSlot(node);
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << " spill: " << node->spill_slot() << " ← "
        << PrintNodeLabel(graph_labeller(), node) << std::endl;
  }
}
References AllocateSpillSlot(), graph_labeller(), v8::internal::maglev::ValueNode::is_loadable(), printing_visitor_, v8::internal::maglev::ValueNode::spill_slot(), and v8::internal::v8_flags.
Referenced by AllocateControlNode(), AllocateEagerDeopt(), AllocateLazyDeopt(), AllocateNode(), DropRegisterValue(), SpillAndClearRegisters(), and SpillRegisters().
SpillAndClearRegisters() [1/2]
void v8::internal::maglev::StraightForwardRegisterAllocator::SpillAndClearRegisters () [private]
Definition at line 1609 of file maglev-regalloc.cc.
                                                              {
  SpillAndClearRegisters(general_registers_);
  SpillAndClearRegisters(double_registers_);
}
References double_registers_, and general_registers_.
Referenced by AllocateControlNode(), and AllocateNode().
SpillAndClearRegisters() [2/2]
template<typename RegisterT >
void v8::internal::maglev::StraightForwardRegisterAllocator::SpillAndClearRegisters (RegisterFrameState< RegisterT > & registers) [private]
Definition at line 1594 of file maglev-regalloc.cc.
                                              {
  while (registers.used() != registers.empty()) {
    RegisterT reg = registers.used().first();
    ValueNode* node = registers.GetValue(reg);
    if (v8_flags.trace_maglev_regalloc) {
      printing_visitor_->os() << " clearing registers with "
                              << PrintNodeLabel(graph_labeller(), node) << "\n";
    }
    Spill(node);
    registers.FreeRegistersUsedBy(node);
    DCHECK(!registers.used().has(reg));
  }
}
References v8::internal::DCHECK(), v8::internal::maglev::RegisterFrameState< RegisterT >::empty(), v8::internal::maglev::RegisterFrameState< RegisterT >::FreeRegistersUsedBy(), v8::internal::maglev::RegisterFrameState< RegisterT >::GetValue(), graph_labeller(), printing_visitor_, Spill(), v8::internal::maglev::RegisterFrameState< RegisterT >::used(), and v8::internal::v8_flags.
SpillRegisters()
void v8::internal::maglev::StraightForwardRegisterAllocator::SpillRegisters () [private]
Definition at line 1587 of file maglev-regalloc.cc.
                                                      {
  auto spill = [&](auto reg, ValueNode* node) { Spill(node); };
  general_registers_.ForEachUsedRegister(spill);
  double_registers_.ForEachUsedRegister(spill);
}
References double_registers_, general_registers_, and Spill().
TryAllocateToInput()
void v8::internal::maglev::StraightForwardRegisterAllocator::TryAllocateToInput (Phi * phi) [private]
Definition at line 1171 of file maglev-regalloc.cc.
                                                                  {
  // Try allocate phis to a register used by any of the inputs.
  for (Input& input : *phi) {
    if (input.operand().IsRegister()) {
      // We assume Phi nodes only point to tagged values, and so they use a
      // general register.
      Register reg = input.AssignedGeneralRegister();
      if (general_registers_.unblocked_free().has(reg)) {
        phi->result().SetAllocated(ForceAllocate(reg, phi));
        SetLoopPhiRegisterHint(phi, reg);
        DCHECK_EQ(general_registers_.GetValue(reg), phi);
        if (v8_flags.trace_maglev_regalloc) {
          printing_visitor_->Process(phi, ProcessingState(block_it_));
          printing_visitor_->os()
              << "phi (reuse) " << input.operand() << std::endl;
        }
        return;
      }
    }
  }
}
References block_it_, DCHECK_EQ, ForceAllocate(), general_registers_, printing_visitor_, SetLoopPhiRegisterHint(), and v8::internal::v8_flags.
Referenced by AllocateRegisters().
UpdateUse() [1/2]
void v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse (Input * input) [inline], [private]
Definition at line 188 of file maglev-regalloc.h.
{ return UpdateUse(input->node(), input); }
References v8::internal::maglev::Input::node(), and UpdateUse().
Referenced by AllocateControlNode(), AllocateEagerDeopt(), AllocateLazyDeopt(), AllocateRegisters(), AssignAnyInput(), AssignArbitraryRegisterInput(), AssignFixedInput(), and UpdateUse().
UpdateUse() [2/2]
void v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse (ValueNode * node, InputLocation * input_location) [private]
Definition at line 633 of file maglev-regalloc.cc.
                                                    {
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << "Using " << PrintNodeLabel(graph_labeller(), node) << "...\n";
  }
  DCHECK(!node->has_no_more_uses());
  // Update the next use.
  node->advance_next_use(input_location->next_use_id());
  if (!node->has_no_more_uses()) return;
  if (v8_flags.trace_maglev_regalloc) {
    printing_visitor_->os()
        << " freeing " << PrintNodeLabel(graph_labeller(), node) << "\n";
  }
  // If a value is dead, make sure it's cleared.
  FreeRegistersUsedBy(node);
  // If the stack slot is a local slot, free it so it can be reused.
  if (node->is_spilled()) {
    compiler::AllocatedOperand slot = node->spill_slot();
    if (slot.index() > 0) {
      SpillSlots& slots =
          slot.representation() == MachineRepresentation::kTagged ? tagged_
                                                                  : untagged_;
      DCHECK_IMPLIES(
          slots.free_slots.size() > 0,
          slots.free_slots.back().freed_at_position <= node->live_range().end);
      bool double_slot =
          IsDoubleRepresentation(node->properties().value_representation());
      slots.free_slots.emplace_back(slot.index(), node->live_range().end,
                                    double_slot);
    }
  }
}
References v8::internal::maglev::ValueNode::advance_next_use(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::maglev::ValueNode::LiveRange::end, v8::internal::maglev::StraightForwardRegisterAllocator::SpillSlots::free_slots, FreeRegistersUsedBy(), graph_labeller(), v8::internal::maglev::ValueNode::has_no_more_uses(), v8::internal::compiler::LocationOperand::index(), v8::internal::maglev::ValueNode::is_spilled(), v8::internal::maglev::IsDoubleRepresentation(), v8::internal::kTagged, v8::internal::maglev::ValueNode::live_range(), v8::internal::maglev::InputLocation::next_use_id(), printing_visitor_, v8::internal::maglev::NodeBase::properties(), v8::internal::compiler::LocationOperand::representation(), v8::internal::maglev::ValueNode::spill_slot(), tagged_, untagged_, v8::internal::v8_flags, and v8::internal::maglev::OpProperties::value_representation().
VerifyInputs()
void v8::internal::maglev::StraightForwardRegisterAllocator::VerifyInputs (NodeBase * node) [private]
Definition at line 1483 of file maglev-regalloc.cc.
                                                                  {
#ifdef DEBUG
  for (Input& input : *node) {
    if (input.operand().IsRegister()) {
      Register reg =
          compiler::AllocatedOperand::cast(input.operand()).GetRegister();
      if (general_registers_.GetValueMaybeFreeButBlocked(reg) != input.node()) {
        FATAL("Input node n%d is not in expected register %s",
              graph_labeller()->NodeId(input.node()), RegisterName(reg));
      }
    } else if (input.operand().IsDoubleRegister()) {
      DoubleRegister reg =
          compiler::AllocatedOperand::cast(input.operand()).GetDoubleRegister();
      if (double_registers_.GetValueMaybeFreeButBlocked(reg) != input.node()) {
        FATAL("Input node n%d is not in expected register %s",
              graph_labeller()->NodeId(input.node()), RegisterName(reg));
      }
    } else {
      if (input.operand() != input.node()->allocation()) {
        std::stringstream ss;
        ss << input.operand();
        FATAL("Input node n%d is not in operand %s",
              graph_labeller()->NodeId(input.node()), ss.str().c_str());
      }
    }
  }
#endif
}
References v8::internal::compiler::LocationOperand::cast(), double_registers_, FATAL, general_registers_, v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::LocationOperand::GetRegister(), and graph_labeller().
Referenced by AllocateControlNode(), and AllocateNode().
VerifyRegisterState()
void v8::internal::maglev::StraightForwardRegisterAllocator::VerifyRegisterState () [private]
Definition at line 1512 of file maglev-regalloc.cc.
                                                           {
#ifdef DEBUG
  // We shouldn't have any blocked registers by now.
  DCHECK(general_registers_.blocked().is_empty());
  DCHECK(double_registers_.blocked().is_empty());
  auto NodeNameForFatal = [&](ValueNode* node) {
    std::stringstream ss;
    if (has_graph_labeller()) {
      ss << PrintNodeLabel(graph_labeller(), node);
    } else {
      ss << "<" << node << ">";
    }
    return ss.str();
  };
  for (Register reg : general_registers_.used()) {
    ValueNode* node = general_registers_.GetValue(reg);
    if (!node->is_in_register(reg)) {
      FATAL("Node %s doesn't think it is in register %s",
            NodeNameForFatal(node).c_str(), RegisterName(reg));
    }
  }
  for (DoubleRegister reg : double_registers_.used()) {
    ValueNode* node = double_registers_.GetValue(reg);
    if (!node->is_in_register(reg)) {
      FATAL("Node %s doesn't think it is in register %s",
            NodeNameForFatal(node).c_str(), RegisterName(reg));
    }
  }
  auto ValidateValueNode = [this, NodeNameForFatal](ValueNode* node) {
    if (node->use_double_register()) {
      for (DoubleRegister reg : node->result_registers<DoubleRegister>()) {
        if (double_registers_.unblocked_free().has(reg)) {
          FATAL("Node %s thinks it's in register %s but it's free",
                NodeNameForFatal(node).c_str(), RegisterName(reg));
        } else if (double_registers_.GetValue(reg) != node) {
          FATAL("Node %s thinks it's in register %s but it contains %s",
                NodeNameForFatal(node).c_str(), RegisterName(reg),
                NodeNameForFatal(double_registers_.GetValue(reg)).c_str());
        }
      }
    } else {
      for (Register reg : node->result_registers<Register>()) {
        if (general_registers_.unblocked_free().has(reg)) {
          FATAL("Node %s thinks it's in register %s but it's free",
                NodeNameForFatal(node).c_str(), RegisterName(reg));
        } else if (general_registers_.GetValue(reg) != node) {
          FATAL("Node %s thinks it's in register %s but it contains %s",
                NodeNameForFatal(node).c_str(), RegisterName(reg),
                NodeNameForFatal(general_registers_.GetValue(reg)).c_str());
        }
      }
    }
  };
  for (BasicBlock* block : *graph_) {
    if (block->has_phi()) {
      for (Phi* phi : *block->phis()) {
        ValidateValueNode(phi);
      }
    }
    for (Node* node : block->nodes()) {
      if (node == nullptr) continue;
      if (ValueNode* value_node = node->TryCast<ValueNode>()) {
        if (node->Is<Identity>()) continue;
        ValidateValueNode(value_node);
      }
    }
  }
#endif
}
References v8::internal::DCHECK(), double_registers_, FATAL, general_registers_, graph_, graph_labeller(), has_graph_labeller(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::ValueNode::is_in_register(), v8::internal::maglev::ValueNode::result_registers(), v8::internal::maglev::NodeBase::TryCast(), and v8::internal::maglev::ValueNode::use_double_register().
Referenced by AllocateControlNode(), AllocateNode(), and AllocateRegisters().
Member Data Documentation
block_it_
BlockConstIterator v8::internal::maglev::StraightForwardRegisterAllocator::block_it_ [private]
Definition at line 319 of file maglev-regalloc.h.
Referenced by AddMoveBeforeCurrentNode(), AllocateControlNode(), AllocateNode(), AllocateRegisters(), and TryAllocateToInput().
compilation_info_
MaglevCompilationInfo* v8::internal::maglev::StraightForwardRegisterAllocator::compilation_info_ [private]
Definition at line 310 of file maglev-regalloc.h.
Referenced by AddMoveBeforeCurrentNode().
current_node_
NodeBase* v8::internal::maglev::StraightForwardRegisterAllocator::current_node_ [private]
Definition at line 322 of file maglev-regalloc.h.
Referenced by AddMoveBeforeCurrentNode(), AllocateControlNode(), AllocateNode(), and AllocateRegisters().
double_registers_
RegisterFrameState<DoubleRegister> v8::internal::maglev::StraightForwardRegisterAllocator::double_registers_ [private]
Definition at line 162 of file maglev-regalloc.h.
Referenced by AllocateControlNode(), AllocateNode(), AllocateRegisters(), AssignAnyInput(), AssignArbitraryRegisterInput(), DropRegisterValue(), FreeRegistersUsedBy(), GetRegisterFrameState(), MarkAsClobbered(), PrintLiveRegs(), SaveRegisterSnapshot(), SpillAndClearRegisters(), SpillRegisters(), VerifyInputs(), and VerifyRegisterState().
general_registers_
RegisterFrameState<Register> v8::internal::maglev::StraightForwardRegisterAllocator::general_registers_ [private]
Definition at line 161 of file maglev-regalloc.h.
Referenced by AllocateControlNode(), AllocateNode(), AllocateRegisters(), AssignAnyInput(), AssignArbitraryRegisterInput(), DropRegisterValue(), FreeRegistersUsedBy(), GetRegisterFrameState(), MarkAsClobbered(), PrintLiveRegs(), SaveRegisterSnapshot(), SpillAndClearRegisters(), SpillRegisters(), TryAllocateToInput(), VerifyInputs(), and VerifyRegisterState().
graph_
Graph* v8::internal::maglev::StraightForwardRegisterAllocator::graph_ [private]
Definition at line 312 of file maglev-regalloc.h.
Referenced by AllocateNodeResult(), AllocateRegisters(), ComputePostDominatingHoles(), graph_labeller(), has_graph_labeller(), StraightForwardRegisterAllocator(), and VerifyRegisterState().
node_it_
NodeIterator v8::internal::maglev::StraightForwardRegisterAllocator::node_it_ [private]
Definition at line 320 of file maglev-regalloc.h.
Referenced by AddMoveBeforeCurrentNode(), and AllocateRegisters().
patches_
ZoneVector<BlockPatch> v8::internal::maglev::StraightForwardRegisterAllocator::patches_ [private]
Definition at line 317 of file maglev-regalloc.h.
Referenced by AddMoveBeforeCurrentNode(), and ApplyPatches().
printing_visitor_
std::unique_ptr<MaglevPrintingVisitor> v8::internal::maglev::StraightForwardRegisterAllocator::printing_visitor_ [private]
Definition at line 311 of file maglev-regalloc.h.
Referenced by AddMoveBeforeCurrentNode(), AllocateControlNode(), AllocateNode(), AllocateRegisters(), AssignAnyInput(), AssignArbitraryRegisterInput(), AssignFixedInput(), DropRegisterValue(), PrintLiveRegs(), Spill(), SpillAndClearRegisters(), TryAllocateToInput(), and UpdateUse().
regalloc_info_
RegallocInfo* v8::internal::maglev::StraightForwardRegisterAllocator::regalloc_info_ [private]
Definition at line 323 of file maglev-regalloc.h.
tagged_
SpillSlots v8::internal::maglev::StraightForwardRegisterAllocator::tagged_ [private]
Definition at line 181 of file maglev-regalloc.h.
Referenced by AllocateNodeResult(), StraightForwardRegisterAllocator(), and UpdateUse().
untagged_
SpillSlots v8::internal::maglev::StraightForwardRegisterAllocator::untagged_ [private]
Definition at line 180 of file maglev-regalloc.h.
Referenced by StraightForwardRegisterAllocator(), and UpdateUse().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-regalloc.h
/mnt/V8SourceCode/src/maglev/maglev-regalloc.cc