v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator Class Reference
Static Public Member Functions
static void VisitText (TextNode *that)
static void VisitAction (ActionNode *that)
static void VisitChoice (ChoiceNode *that, int i)
static void VisitLoopChoiceContinueNode (LoopChoiceNode *that)
static void VisitLoopChoiceLoopNode (LoopChoiceNode *that)
static void VisitNegativeLookaroundChoiceLookaroundNode (NegativeLookaroundChoiceNode *that)
static void VisitNegativeLookaroundChoiceContinueNode (NegativeLookaroundChoiceNode *that)
static void VisitBackReference (BackReferenceNode *that)
static void VisitAssertion (AssertionNode *that)
Detailed Description
Definition at line 3687 of file regexp-compiler.cc.
Member Function Documentation
VisitAction()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction (ActionNode * that) [inline], [static]
Definition at line 3702 of file regexp-compiler.cc.
                                            {
    switch (that->action_type()) {
      case ActionNode::BEGIN_POSITIVE_SUBMATCH: {
        // For a begin positive submatch we propagate the eats_at_least
        // data from the successor of the success node, ignoring the body of
        // the lookahead, which eats nothing, since it is a zero-width
        // assertion.
        // TODO(chromium:42201836) This is better than discarding all
        // information when there is a positive lookahead, but it loses some
        // information that could be useful, since the body of the lookahead
        // could tell us something about how close to the end of the string we
        // are.
        that->set_eats_at_least_info(
            *that->success_node()->on_success()->eats_at_least_info());
        break;
      }
      case ActionNode::POSITIVE_SUBMATCH_SUCCESS:
        // We do not propagate eats_at_least data through positive submatch
        // success because it rewinds input.
        DCHECK(that->eats_at_least_info()->IsZero());
        break;
      case ActionNode::SET_REGISTER_FOR_LOOP:
        // SET_REGISTER_FOR_LOOP indicates a loop entry point, which means the
        // loop body will run at least the minimum number of times before the
        // continuation case can run.
        that->set_eats_at_least_info(
            that->on_success()->EatsAtLeastFromLoopEntry());
        break;
      case ActionNode::BEGIN_NEGATIVE_SUBMATCH:
      default:
        // Otherwise, the current node eats at least as much as its successor.
        // Note: we can propagate eats_at_least data for BEGIN_NEGATIVE_SUBMATCH
        // because NegativeLookaroundChoiceNode ignores its lookaround successor
        // when computing eats-at-least and quick check information.
        that->set_eats_at_least_info(*that->on_success()->eats_at_least_info());
        break;
    }
  }
References v8::internal::ActionNode::action_type(), v8::internal::ActionNode::BEGIN_NEGATIVE_SUBMATCH, v8::internal::ActionNode::BEGIN_POSITIVE_SUBMATCH, v8::internal::DCHECK(), v8::internal::RegExpNode::eats_at_least_info(), v8::internal::RegExpNode::EatsAtLeastFromLoopEntry(), v8::internal::EatsAtLeastInfo::IsZero(), v8::internal::SeqRegExpNode::on_success(), v8::internal::ActionNode::POSITIVE_SUBMATCH_SUCCESS, v8::internal::RegExpNode::set_eats_at_least_info(), v8::internal::ActionNode::SET_REGISTER_FOR_LOOP, and v8::internal::ActionNode::success_node.
VisitAssertion()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAssertion (AssertionNode * that) [inline], [static]
Definition at line 3774 of file regexp-compiler.cc.
                                                  {
    EatsAtLeastInfo eats_at_least = *that->on_success()->eats_at_least_info();
    if (that->assertion_type() == AssertionNode::AT_START) {
      // If we know we are not at the start and we are asked "how many
      // characters will you match if you succeed?" then we can answer anything
      // since false implies false. So let's just set the max answer
      // (UINT8_MAX) since that won't prevent us from preloading a lot of
      // characters for the other branches in the node graph.
      eats_at_least.eats_at_least_from_not_start = UINT8_MAX;
    }
    that->set_eats_at_least_info(eats_at_least);
  }
References v8::internal::AssertionNode::assertion_type(), v8::internal::AssertionNode::AT_START, v8::internal::EatsAtLeastInfo::eats_at_least_from_not_start, v8::internal::RegExpNode::eats_at_least_info(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::set_eats_at_least_info().
VisitBackReference()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitBackReference (BackReferenceNode * that) [inline], [static]
Definition at line 3768 of file regexp-compiler.cc.
                                                          {
    if (!that->read_backward()) {
      that->set_eats_at_least_info(*that->on_success()->eats_at_least_info());
    }
  }
References v8::internal::RegExpNode::eats_at_least_info(), v8::internal::SeqRegExpNode::on_success(), v8::internal::BackReferenceNode::read_backward(), and v8::internal::RegExpNode::set_eats_at_least_info().
VisitChoice()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitChoice (ChoiceNode * that, int i) [inline], [static]
Definition at line 3741 of file regexp-compiler.cc.
                                                   {
    // The minimum possible match from a choice node is the minimum of its
    // successors.
    EatsAtLeastInfo eats_at_least =
        i == 0 ? EatsAtLeastInfo(UINT8_MAX) : *that->eats_at_least_info();
    eats_at_least.SetMin(
        *that->alternatives()->at(i).node()->eats_at_least_info());
    that->set_eats_at_least_info(eats_at_least);
  }
References v8::internal::ChoiceNode::alternatives(), v8::internal::RegExpNode::eats_at_least_info(), v8::internal::RegExpNode::set_eats_at_least_info(), and v8::internal::EatsAtLeastInfo::SetMin().
VisitLoopChoiceContinueNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitLoopChoiceContinueNode (LoopChoiceNode * that) [inline], [static]
Definition at line 3751 of file regexp-compiler.cc.
                                                                {
    if (!that->read_backward()) {
      that->set_eats_at_least_info(
          *that->continue_node()->eats_at_least_info());
    }
  }
References v8::internal::LoopChoiceNode::continue_node(), v8::internal::RegExpNode::eats_at_least_info(), v8::internal::LoopChoiceNode::read_backward(), and v8::internal::RegExpNode::set_eats_at_least_info().
VisitLoopChoiceLoopNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitLoopChoiceLoopNode (LoopChoiceNode * that) [inline], [static]
Definition at line 3758 of file regexp-compiler.cc.
{}
VisitNegativeLookaroundChoiceContinueNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitNegativeLookaroundChoiceContinueNode (NegativeLookaroundChoiceNode * that) [inline], [static]
Definition at line 3763 of file regexp-compiler.cc.
                                          {
    that->set_eats_at_least_info(*that->continue_node()->eats_at_least_info());
  }
References v8::internal::NegativeLookaroundChoiceNode::continue_node(), v8::internal::RegExpNode::eats_at_least_info(), and v8::internal::RegExpNode::set_eats_at_least_info().
VisitNegativeLookaroundChoiceLookaroundNode()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitNegativeLookaroundChoiceLookaroundNode (NegativeLookaroundChoiceNode * that) [inline], [static]
Definition at line 3760 of file regexp-compiler.cc.
                                          {}
VisitText()
static void v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitText (TextNode * that) [inline], [static]
Definition at line 3689 of file regexp-compiler.cc.
                                        {
    // The eats_at_least value is not used if reading backward.
    if (!that->read_backward()) {
      // We are not at the start after this node, and thus we can use the
      // successor's eats_at_least_from_not_start value.
      uint8_t eats_at_least = base::saturated_cast<uint8_t>(
          that->Length() + that->on_success()
                               ->eats_at_least_info()
                               ->eats_at_least_from_not_start);
      that->set_eats_at_least_info(EatsAtLeastInfo(eats_at_least));
    }
  }
References v8::internal::EatsAtLeastInfo::eats_at_least_from_not_start, v8::internal::RegExpNode::eats_at_least_info(), v8::internal::TextNode::Length(), v8::internal::SeqRegExpNode::on_success(), v8::internal::TextNode::read_backward(), and v8::internal::RegExpNode::set_eats_at_least_info().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc