v8::internal::SlicedString Class Reference
#include <string.h>
Public Member Functions
Tagged< String > parent () const
void set_parent (Tagged< String > parent, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
int32_t offset () const
void set_offset (int32_t offset)
V8_EXPORT_PRIVATE uint16_t Get (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
Static Public Attributes
static const uint32_t kMinLength = 13
Private Attributes
TaggedMember< String > parent_
TaggedMember< Smi > offset_
Friends
struct ObjectTraits< SlicedString >
struct OffsetsForDebug
class V8HeapExplorer
class CodeStubAssembler
class SandboxTesting
class ToDirectStringAssembler
class maglev::MaglevAssembler
class compiler::AccessBuilder
class TorqueGeneratedSlicedStringAsserts
Tagged< String > String::GetUnderlying () const
Additional Inherited Members
Detailed Description
Definition at line 1129 of file string.h.
Member Function Documentation
Get()
uint16_t v8::internal::SlicedString::Get (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const
Definition at line 2058 of file string.cc.
                                                                               {
  return parent()->Get(offset() + index, access_guard);
}
References v8::internal::index.
offset()
int32_t v8::internal::SlicedString::offset () const [inline]
Definition at line 1396 of file string-inl.h.
{ return offset_.load().value(); }
parent()
Tagged< String > v8::internal::SlicedString::parent () const [inline]
Definition at line 1389 of file string-inl.h.
{ return parent_.load(); }
set_offset()
void v8::internal::SlicedString::set_offset (int32_t offset) [inline]
Definition at line 1398 of file string-inl.h.
                                           {
  offset_.store(this, Smi::FromInt(value), SKIP_WRITE_BARRIER);
}
References v8::internal::Smi::FromInt(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
set_parent()
void v8::internal::SlicedString::set_parent (Tagged< String > parent, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1391 of file string-inl.h.
                                                                          {
  DCHECK(IsSeqString(parent) || IsExternalString(parent));
  parent_.store(this, parent, mode);
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsSeqString(), and mode().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 1151 of file string.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 1155 of file string.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 1154 of file string.h.
ObjectTraits< SlicedString >
friend struct ObjectTraits< SlicedString > [friend]
Definition at line 1144 of file string.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 1149 of file string.h.
SandboxTesting
friend class SandboxTesting [friend]
Definition at line 1152 of file string.h.
String::GetUnderlying
Tagged<String> String::GetUnderlying () const [friend]
ToDirectStringAssembler
friend class ToDirectStringAssembler [friend]
Definition at line 1153 of file string.h.
TorqueGeneratedSlicedStringAsserts
friend class TorqueGeneratedSlicedStringAsserts [friend]
Definition at line 1156 of file string.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 1150 of file string.h.
Member Data Documentation
kMinLength
const uint32_t v8::internal::SlicedString::kMinLength = 13 [static]
Definition at line 1144 of file string.h.
Referenced by v8::internal::TranslatedValue::GetRawValue(), v8::internal::Factory::NewProperSubString(), v8::internal::requires(), and v8::internal::StringBuiltinsAssembler::SubString().
offset_
TaggedMember<Smi> v8::internal::SlicedString::offset_ [private]
Definition at line 1161 of file string.h.
parent_
TaggedMember<String> v8::internal::SlicedString::parent_ [private]
Definition at line 1160 of file string.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc