v8::Data Class Reference
The superclass of objects that can reside on V8's heap.
#include <v8-data.h>
Public Member Functions
bool IsValue () const
Returns true if this data is a |v8::Value|.
bool IsModule () const
Returns true if this data is a |v8::Module|.
bool IsModuleRequest () const
Returns true if this data is a |v8::ModuleRequest|.
bool IsFixedArray () const
Returns tru if this data is a |v8::FixedArray|.
bool IsPrivate () const
Returns true if this data is a |v8::Private|.
bool IsObjectTemplate () const
Returns true if this data is a |v8::ObjectTemplate|.
bool IsFunctionTemplate () const
Returns true if this data is a |v8::FunctionTemplate|.
bool IsContext () const
Returns true if this data is a |v8::Context|.
bool IsCppHeapExternal () const
Returns true if this value is a CppHeapExternal object.
Private Member Functions
Data ()=delete
Detailed Description
The superclass of objects that can reside on V8's heap.
Definition at line 18 of file v8-data.h.
Constructor & Destructor Documentation
Data()
v8::Data::Data () [private], [delete]
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArrayFastCallback(), and v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringFastCallback().
Member Function Documentation
IsContext()
bool v8::Data::IsContext () const
Returns true if this data is a |v8::Context|.
Definition at line 823 of file api.cc.
                           {
  return i::IsContext(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsCppHeapExternal()
bool v8::Data::IsCppHeapExternal () const
Returns true if this value is a CppHeapExternal object.
Definition at line 827 of file api.cc.
                                   {
  return IsCppHeapExternalObject(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::CppHeapExternal::CheckCast().
IsFixedArray()
bool v8::Data::IsFixedArray () const
Returns tru if this data is a |v8::FixedArray|.
Definition at line 795 of file api.cc.
                              {
  return i::IsFixedArray(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsFunctionTemplate()
bool v8::Data::IsFunctionTemplate () const
Returns true if this data is a |v8::FunctionTemplate|.
Definition at line 819 of file api.cc.
                                    {
  return i::IsFunctionTemplateInfo(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsModule()
bool v8::Data::IsModule () const
Returns true if this data is a |v8::Module|.
Definition at line 787 of file api.cc.
                          {
  return i::IsModule(*Utils::OpenDirectHandle(this));
}
References v8::internal::IsModule(), and v8::Utils::OpenDirectHandle().
IsModuleRequest()
bool v8::Data::IsModuleRequest () const
Returns true if this data is a |v8::ModuleRequest|.
Definition at line 791 of file api.cc.
                                 {
  return i::IsModuleRequest(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsObjectTemplate()
bool v8::Data::IsObjectTemplate () const
Returns true if this data is a |v8::ObjectTemplate|.
Definition at line 815 of file api.cc.
                                  {
  return i::IsObjectTemplateInfo(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsPrivate()
bool v8::Data::IsPrivate () const
Returns true if this data is a |v8::Private|.
Definition at line 811 of file api.cc.
                           {
  return i::IsPrivateSymbol(*Utils::OpenDirectHandle(this));
}
References v8::internal::IsPrivateSymbol(), and v8::Utils::OpenDirectHandle().
IsValue()
bool v8::Data::IsValue () const
Returns true if this data is a |v8::Value|.
Definition at line 799 of file api.cc.
                         {
  i::DisallowGarbageCollection no_gc;
  i::Tagged<i::Object> self = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(self)) return true;
  i::Tagged<i::HeapObject> heap_object = i::Cast<i::HeapObject>(self);
  DCHECK(!IsTheHole(heap_object));
  if (i::IsSymbol(heap_object)) {
    return !i::Cast<i::Symbol>(heap_object)->is_private();
  }
  return IsPrimitiveHeapObject(heap_object) || IsJSReceiver(heap_object);
}
References DCHECK, v8::internal::IsSmi(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8::Value::CheckCast(), v8::internal::ExtractEmbedderDataBackref(), and v8::EmbedderGraph::V8Node().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-data.h
/mnt/V8SourceCode/src/api/api.cc