v8::internal::UpdateTypedSlotHelper Class Reference
#include <remembered-set.h>
Static Public Member Functions
template<typename Callback >
static SlotCallbackResult UpdateTypedSlot (WritableJitAllocation &jit_allocation, Heap *heap, SlotType slot_type, Address addr, Callback callback)
static Tagged< HeapObject > GetTargetObject (Heap *heap, SlotType slot_type, Address addr)
Static Private Member Functions
template<typename Callback >
static SlotCallbackResult UpdateCodeEntry (Address entry_address, Callback callback)
template<typename Callback >
static SlotCallbackResult UpdateCodeTarget (WritableRelocInfo *rinfo, Callback callback)
template<typename Callback >
static SlotCallbackResult UpdateEmbeddedPointer (Heap *heap, WritableRelocInfo *rinfo, Callback callback)
Detailed Description
Definition at line 305 of file remembered-set.h.
Member Function Documentation
GetTargetObject()
Tagged< HeapObject > v8::internal::UpdateTypedSlotHelper::GetTargetObject (Heap * heap, SlotType slot_type, Address addr) [inline], [static]
Definition at line 69 of file remembered-set-inl.h.
                                                                        {
  switch (slot_type) {
    case SlotType::kCodeEntry: {
      RelocInfo rinfo(addr, RelocInfo::CODE_TARGET);
      return InstructionStream::FromTargetAddress(rinfo.target_address());
    }
    case SlotType::kConstPoolCodeEntry: {
      return InstructionStream::FromEntryAddress(addr);
    }
    case SlotType::kEmbeddedObjectCompressed: {
      RelocInfo rinfo(addr, RelocInfo::COMPRESSED_EMBEDDED_OBJECT);
      return rinfo.target_object(heap->isolate());
    }
    case SlotType::kEmbeddedObjectFull: {
      RelocInfo rinfo(addr, RelocInfo::FULL_EMBEDDED_OBJECT);
      return rinfo.target_object(heap->isolate());
    }
    case SlotType::kConstPoolEmbeddedObjectCompressed: {
      Address full = V8HeapCompressionScheme::DecompressTagged(
          base::Memory<Tagged_t>(addr));
      return Cast<HeapObject>(Tagged<Object>(full));
    }
    case SlotType::kConstPoolEmbeddedObjectFull: {
      FullHeapObjectSlot slot(addr);
      return (*slot).GetHeapObjectAssumeStrong(heap->isolate());
    }
    case SlotType::kCleared:
      break;
  }
  UNREACHABLE();
}
References v8::internal::RelocInfo::CODE_TARGET, v8::internal::RelocInfo::COMPRESSED_EMBEDDED_OBJECT, v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::InstructionStream::FromEntryAddress(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::kCleared, v8::internal::kCodeEntry, v8::internal::kConstPoolCodeEntry, v8::internal::kConstPoolEmbeddedObjectCompressed, v8::internal::kConstPoolEmbeddedObjectFull, v8::internal::kEmbeddedObjectCompressed, v8::internal::kEmbeddedObjectFull, v8::internal::RelocInfo::target_address(), v8::internal::RelocInfo::target_object(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkTypedPointers(), and v8::internal::Scavenger::ScavengePage().
UpdateCodeEntry()
template<typename Callback >
static SlotCallbackResult v8::internal::UpdateTypedSlotHelper::UpdateCodeEntry (Address entry_address, Callback callback) [inline], [static], [private]
Definition at line 325 of file remembered-set.h.
                                                               {
    Tagged<InstructionStream> code =
        InstructionStream::FromEntryAddress(entry_address);
    Tagged<InstructionStream> old_code = code;
    SlotCallbackResult result = callback(FullMaybeObjectSlot(&code));
    DCHECK(!HasWeakHeapObjectTag(code));
    if (code != old_code) {
      base::Memory<Address>(entry_address) = code->instruction_start();
    }
    return result;
  }
References code, v8::internal::DCHECK(), v8::internal::InstructionStream::FromEntryAddress(), v8::internal::HasWeakHeapObjectTag(), and v8::base::internal::result.
Referenced by UpdateTypedSlot().
UpdateCodeTarget()
template<typename Callback >
static SlotCallbackResult v8::internal::UpdateTypedSlotHelper::UpdateCodeTarget (WritableRelocInfo * rinfo, Callback callback) [inline], [static], [private]
Definition at line 341 of file remembered-set.h.
                                                                {
    DCHECK(RelocInfo::IsCodeTargetMode(rinfo->rmode()));
    Tagged<InstructionStream> old_target =
        InstructionStream::FromTargetAddress(rinfo->target_address());
    Tagged<InstructionStream> new_target = old_target;
    SlotCallbackResult result = callback(FullMaybeObjectSlot(&new_target));
    DCHECK(!HasWeakHeapObjectTag(new_target));
    if (new_target != old_target) {
      rinfo->set_target_address(
          Cast<InstructionStream>(new_target)->instruction_start());
    }
    return result;
  }
References v8::internal::DCHECK(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::HasWeakHeapObjectTag(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::base::internal::result, v8::internal::RelocInfo::rmode(), v8::internal::WritableRelocInfo::set_target_address(), and v8::internal::RelocInfo::target_address().
Referenced by UpdateTypedSlot().
UpdateEmbeddedPointer()
template<typename Callback >
static SlotCallbackResult v8::internal::UpdateTypedSlotHelper::UpdateEmbeddedPointer (Heap * heap, WritableRelocInfo * rinfo, Callback callback) [inline], [static], [private]
Definition at line 359 of file remembered-set.h.
                                                                     {
    DCHECK(RelocInfo::IsEmbeddedObjectMode(rinfo->rmode()));
    Tagged<HeapObject> old_target = rinfo->target_object(heap->isolate());
    Tagged<HeapObject> new_target = old_target;
    SlotCallbackResult result = callback(FullMaybeObjectSlot(&new_target));
    DCHECK(!HasWeakHeapObjectTag(new_target));
    if (new_target != old_target) {
      rinfo->set_target_object(Cast<HeapObject>(new_target));
    }
    return result;
  }
References v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::base::internal::result, v8::internal::RelocInfo::rmode(), v8::internal::WritableRelocInfo::set_target_object(), and v8::internal::RelocInfo::target_object().
Referenced by UpdateTypedSlot().
UpdateTypedSlot()
template<typename Callback >
SlotCallbackResult v8::internal::UpdateTypedSlotHelper::UpdateTypedSlot (WritableJitAllocation & jit_allocation, Heap * heap, SlotType slot_type, Address addr, Callback callback) [static]
Definition at line 19 of file remembered-set-inl.h.
                                     {
  switch (slot_type) {
    case SlotType::kCodeEntry: {
      WritableRelocInfo rinfo(jit_allocation, addr, RelocInfo::CODE_TARGET);
      return UpdateCodeTarget(&rinfo, callback);
    }
    case SlotType::kConstPoolCodeEntry: {
      return UpdateCodeEntry(addr, callback);
    }
    case SlotType::kEmbeddedObjectCompressed: {
      WritableRelocInfo rinfo(jit_allocation, addr,
                              RelocInfo::COMPRESSED_EMBEDDED_OBJECT);
      return UpdateEmbeddedPointer(heap, &rinfo, callback);
    }
    case SlotType::kEmbeddedObjectFull: {
      WritableRelocInfo rinfo(jit_allocation, addr,
                              RelocInfo::FULL_EMBEDDED_OBJECT);
      return UpdateEmbeddedPointer(heap, &rinfo, callback);
    }
    case SlotType::kConstPoolEmbeddedObjectCompressed: {
      Tagged<HeapObject> old_target = Cast<HeapObject>(
          Tagged<Object>(V8HeapCompressionScheme::DecompressTagged(
              base::Memory<Tagged_t>(addr))));
      Tagged<HeapObject> new_target = old_target;
      SlotCallbackResult result = callback(FullMaybeObjectSlot(&new_target));
      DCHECK(!HasWeakHeapObjectTag(new_target));
      if (new_target != old_target) {
        jit_allocation.WriteValue<Tagged_t>(
            addr, V8HeapCompressionScheme::CompressObject(new_target.ptr()));
      }
      return result;
    }
    case SlotType::kConstPoolEmbeddedObjectFull: {
      Tagged<HeapObject> old_target =
          Cast<HeapObject>(Tagged<Object>(base::Memory<Address>(addr)));
      Tagged<HeapObject> new_target = old_target;
      SlotCallbackResult result = callback(FullMaybeObjectSlot(&new_target));
      if (new_target != old_target) {
        jit_allocation.WriteValue(addr, new_target.ptr());
      }
      return result;
    }
    case SlotType::kCleared:
      break;
  }
  UNREACHABLE();
}
References v8::internal::RelocInfo::CODE_TARGET, v8::internal::RelocInfo::COMPRESSED_EMBEDDED_OBJECT, v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::DCHECK(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::HasWeakHeapObjectTag(), v8::internal::kCleared, v8::internal::kCodeEntry, v8::internal::kConstPoolCodeEntry, v8::internal::kConstPoolEmbeddedObjectCompressed, v8::internal::kConstPoolEmbeddedObjectFull, v8::internal::kEmbeddedObjectCompressed, v8::internal::kEmbeddedObjectFull, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::internal::result, v8::internal::UNREACHABLE(), UpdateCodeEntry(), UpdateCodeTarget(), UpdateEmbeddedPointer(), and v8::internal::WritableJitAllocation::WriteValue().
Referenced by v8::internal::Scavenger::ScavengePage().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/remembered-set.h
/mnt/V8SourceCode/src/heap/remembered-set-inl.h