v8::internal::interpreter::InterpreterAssembler::RegListNodePair Class Reference
#include <interpreter-assembler.h>
Public Member Functions
RegListNodePair (TNode< IntPtrT > base_reg_location, TNode< Word32T > reg_count)
TNode< Word32T > reg_count () const
TNode< IntPtrT > base_reg_location () const
Private Attributes
TNode< IntPtrT > base_reg_location_
TNode< Word32T > reg_count_
Detailed Description
Definition at line 89 of file interpreter-assembler.h.
Constructor & Destructor Documentation
RegListNodePair()
v8::internal::interpreter::InterpreterAssembler::RegListNodePair::RegListNodePair (TNode< IntPtrT > base_reg_location, TNode< Word32T > reg_count) [inline]
Definition at line 91 of file interpreter-assembler.h.
        : base_reg_location_(base_reg_location), reg_count_(reg_count) {}
Member Function Documentation
base_reg_location()
TNode<IntPtrT> v8::internal::interpreter::InterpreterAssembler::RegListNodePair::base_reg_location () const [inline]
Definition at line 95 of file interpreter-assembler.h.
{ return base_reg_location_; }
Referenced by v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), and v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList().
reg_count()
TNode<Word32T> v8::internal::interpreter::InterpreterAssembler::RegListNodePair::reg_count () const [inline]
Definition at line 94 of file interpreter-assembler.h.
{ return reg_count_; }
Referenced by v8::internal::interpreter::InterpreterAssembler::ExportParametersAndRegisterFile(), v8::internal::interpreter::InterpreterAssembler::ImportRegisterFile(), and v8::internal::interpreter::InterpreterAssembler::RegisterLocationInRegisterList().
Member Data Documentation
base_reg_location_
TNode<IntPtrT> v8::internal::interpreter::InterpreterAssembler::RegListNodePair::base_reg_location_ [private]
Definition at line 98 of file interpreter-assembler.h.
reg_count_
TNode<Word32T> v8::internal::interpreter::InterpreterAssembler::RegListNodePair::reg_count_ [private]
Definition at line 99 of file interpreter-assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/interpreter-assembler.h