v8::internal::compiler::RedundancyElimination Class Reference
#include <redundancy-elimination.h>
Classes
struct Check
class EffectPathChecks
class PathChecksForEffectNodes
Public Member Functions
RedundancyElimination (Editor *editor, JSGraph *jsgraph, Zone *zone)
~RedundancyElimination () final
RedundancyElimination (const RedundancyElimination &)=delete
RedundancyElimination & operator= (const RedundancyElimination &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceCheckNode (Node *node)
Reduction ReduceEffectPhi (Node *node)
Reduction ReduceSpeculativeNumberComparison (Node *node)
Reduction ReduceSpeculativeNumberOperation (Node *node)
Reduction ReduceStart (Node *node)
Reduction ReduceOtherNode (Node *node)
Reduction TakeChecksFromFirstEffect (Node *node)
Reduction UpdateChecks (Node *node, EffectPathChecks const *checks)
Zone * zone () const
Private Attributes
PathChecksForEffectNodes node_checks_
JSGraph * jsgraph_
Zone *const zone_
Additional Inherited Members
Detailed Description
Definition at line 17 of file redundancy-elimination.h.
Constructor & Destructor Documentation
RedundancyElimination() [1/2]
v8::internal::compiler::RedundancyElimination::RedundancyElimination (Editor * editor, JSGraph * jsgraph, Zone * zone)
Definition at line 16 of file redundancy-elimination.cc.
    : AdvancedReducer(editor),
      node_checks_(zone),
      jsgraph_(jsgraph),
      zone_(zone) {}
 RedundancyElimination()
v8::internal::compiler::RedundancyElimination::~RedundancyElimination () [final], [default]
RedundancyElimination() [2/2]
v8::internal::compiler::RedundancyElimination::RedundancyElimination (const RedundancyElimination &) [delete]
Member Function Documentation
operator=()
RedundancyElimination& v8::internal::compiler::RedundancyElimination::operator= (const RedundancyElimination &) [delete]
Reduce()
Reduction v8::internal::compiler::RedundancyElimination::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 25 of file redundancy-elimination.cc.
                                                  {
  if (node_checks_.Get(node)) return NoChange();
  switch (node->opcode()) {
    case IrOpcode::kCheckBigInt:
    case IrOpcode::kCheckedBigIntToBigInt64:
    case IrOpcode::kCheckBounds:
    case IrOpcode::kCheckClosure:
    case IrOpcode::kCheckEqualsInternalizedString:
    case IrOpcode::kCheckEqualsSymbol:
    case IrOpcode::kCheckFloat64Hole:
    case IrOpcode::kCheckHeapObject:
    case IrOpcode::kCheckIf:
    case IrOpcode::kCheckInternalizedString:
    case IrOpcode::kCheckNotTaggedHole:
    case IrOpcode::kCheckNumber:
    case IrOpcode::kCheckNumberFitsInt32:
    case IrOpcode::kCheckReceiver:
    case IrOpcode::kCheckReceiverOrNullOrUndefined:
    case IrOpcode::kCheckSmi:
    case IrOpcode::kCheckString:
    case IrOpcode::kCheckStringOrStringWrapper:
    case IrOpcode::kCheckSymbol:
    case IrOpcode::kTypeGuard:
    // These are not really check nodes, but behave the same in that they can be
    // folded together if repeated with identical inputs.
    case IrOpcode::kStringCharCodeAt:
    case IrOpcode::kStringCodePointAt:
    case IrOpcode::kStringFromCodePointAt:
    case IrOpcode::kStringSubstring:
#define SIMPLIFIED_OP(Opcode) case IrOpcode::k##Opcode:
      SIMPLIFIED_CHECKED_OP_LIST(SIMPLIFIED_OP)
      SIMPLIFIED_BIGINT_BINOP_LIST(SIMPLIFIED_OP)
#undef SIMPLIFIED_OP
      return ReduceCheckNode(node);
    case IrOpcode::kSpeculativeNumberEqual:
    case IrOpcode::kSpeculativeNumberLessThan:
    case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      return ReduceSpeculativeNumberComparison(node);
    case IrOpcode::kSpeculativeNumberAdd:
    case IrOpcode::kSpeculativeNumberSubtract:
    case IrOpcode::kSpeculativeAdditiveSafeIntegerAdd:
    case IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract:
    case IrOpcode::kSpeculativeSmallIntegerAdd:
    case IrOpcode::kSpeculativeSmallIntegerSubtract:
    case IrOpcode::kSpeculativeToNumber:
      return ReduceSpeculativeNumberOperation(node);
    case IrOpcode::kEffectPhi:
      return ReduceEffectPhi(node);
    case IrOpcode::kDead:
      break;
    case IrOpcode::kStart:
      return ReduceStart(node);
    default:
      return ReduceOtherNode(node);
  }
  return NoChange();
}
References v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::kStart, v8::internal::compiler::Reducer::NoChange(), node_checks_, v8::internal::compiler::Node::opcode(), ReduceCheckNode(), ReduceEffectPhi(), ReduceOtherNode(), ReduceSpeculativeNumberComparison(), ReduceSpeculativeNumberOperation(), ReduceStart(), SIMPLIFIED_BIGINT_BINOP_LIST, SIMPLIFIED_CHECKED_OP_LIST, and SIMPLIFIED_OP.
ReduceCheckNode()
Reduction v8::internal::compiler::RedundancyElimination::ReduceCheckNode (Node * node) [private]
Definition at line 363 of file redundancy-elimination.cc.
                                                           {
  Node* const effect = NodeProperties::GetEffectInput(node);
  EffectPathChecks const* checks = node_checks_.Get(effect);
  // If we do not know anything about the predecessor, do not propagate just yet
  // because we will have to recompute anyway once we compute the predecessor.
  if (checks == nullptr) return NoChange();
  // See if we have another check that dominates us.
  if (Node* check = checks->LookupCheck(node, jsgraph_)) {
    ReplaceWithValue(node, check);
    return Replace(check);
  }
  // Learn from this check.
  return UpdateChecks(node, checks->AddCheck(zone(), node));
}
References v8::internal::compiler::RedundancyElimination::EffectPathChecks::AddCheck(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), jsgraph_, v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupCheck(), v8::internal::compiler::Reducer::NoChange(), node_checks_, v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), UpdateChecks(), and zone().
Referenced by Reduce().
ReduceEffectPhi()
Reduction v8::internal::compiler::RedundancyElimination::ReduceEffectPhi (Node * node) [private]
Definition at line 379 of file redundancy-elimination.cc.
                                                           {
  Node* const control = NodeProperties::GetControlInput(node);
  if (control->opcode() == IrOpcode::kLoop) {
    // Here we rely on having only reducible loops:
    // The loop entry edge always dominates the header, so we can just use
    // the information from the loop entry edge.
    return TakeChecksFromFirstEffect(node);
  }
  DCHECK_EQ(IrOpcode::kMerge, control->opcode());
  // Shortcut for the case when we do not know anything about some input.
  int const input_count = node->op()->EffectInputCount();
  for (int i = 0; i < input_count; ++i) {
    Node* const effect = NodeProperties::GetEffectInput(node, i);
    if (node_checks_.Get(effect) == nullptr) return NoChange();
  }
  // Make a copy of the first input's checks and merge with the checks
  // from other inputs.
  EffectPathChecks* checks = EffectPathChecks::Copy(
      zone(), node_checks_.Get(NodeProperties::GetEffectInput(node, 0)));
  for (int i = 1; i < input_count; ++i) {
    Node* const input = NodeProperties::GetEffectInput(node, i);
    checks->Merge(node_checks_.Get(input));
  }
  return UpdateChecks(node, checks);
}
References v8::internal::compiler::RedundancyElimination::EffectPathChecks::Copy(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::Merge(), v8::internal::compiler::Reducer::NoChange(), node_checks_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), TakeChecksFromFirstEffect(), UpdateChecks(), and zone().
Referenced by Reduce().
ReduceOtherNode()
Reduction v8::internal::compiler::RedundancyElimination::ReduceOtherNode (Node * node) [private]
Definition at line 504 of file redundancy-elimination.cc.
                                                           {
  if (node->op()->EffectInputCount() == 1) {
    if (node->op()->EffectOutputCount() == 1) {
      return TakeChecksFromFirstEffect(node);
    } else {
      // Effect terminators should be handled specially.
      return NoChange();
    }
  }
  DCHECK_EQ(0, node->op()->EffectInputCount());
  DCHECK_EQ(0, node->op()->EffectOutputCount());
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), and TakeChecksFromFirstEffect().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::RedundancyElimination::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 24 of file redundancy-elimination.h.
{ return "RedundancyElimination"; }
ReduceSpeculativeNumberComparison()
Reduction v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison (Node * node) [private]
Definition at line 407 of file redundancy-elimination.cc.
                                                                             {
  NumberOperationHint const hint = NumberOperationHintOf(node->op());
  Node* const first = NodeProperties::GetValueInput(node, 0);
  Type const first_type = NodeProperties::GetType(first);
  Node* const second = NodeProperties::GetValueInput(node, 1);
  Type const second_type = NodeProperties::GetType(second);
  Node* const effect = NodeProperties::GetEffectInput(node);
  EffectPathChecks const* checks = node_checks_.Get(effect);
  // If we do not know anything about the predecessor, do not propagate just yet
  // because we will have to recompute anyway once we compute the predecessor.
  if (checks == nullptr) return NoChange();
  // Avoid the potentially expensive lookups below if the {node}
  // has seen non-Smi inputs in the past, which is a clear signal
  // that the comparison is probably not performed on a value that
  // already passed an array bounds check.
  if (hint == NumberOperationHint::kSignedSmall) {
    // Don't bother trying to find a CheckBounds for the {first} input
    // if it's type is already in UnsignedSmall range, since the bounds
    // check is only going to narrow that range further, but the result
    // is not going to make the representation selection any better.
    if (!first_type.Is(Type::UnsignedSmall())) {
      if (Node* check = checks->LookupBoundsCheckFor(first)) {
        if (!first_type.Is(NodeProperties::GetType(check))) {
          // Replace the {first} input with the {check}. This is safe,
          // despite the fact that {check} can truncate -0 to 0, because
          // the regular Number comparisons in JavaScript also identify
          // 0 and -0 (unlike special comparisons as Object.is).
          NodeProperties::ReplaceValueInput(node, check, 0);
          return Changed(node).FollowedBy(
              ReduceSpeculativeNumberComparison(node));
        }
      }
    }
    // Don't bother trying to find a CheckBounds for the {second} input
    // if it's type is already in UnsignedSmall range, since the bounds
    // check is only going to narrow that range further, but the result
    // is not going to make the representation selection any better.
    if (!second_type.Is(Type::UnsignedSmall())) {
      if (Node* check = checks->LookupBoundsCheckFor(second)) {
        if (!second_type.Is(NodeProperties::GetType(check))) {
          // Replace the {second} input with the {check}. This is safe,
          // despite the fact that {check} can truncate -0 to 0, because
          // the regular Number comparisons in JavaScript also identify
          // 0 and -0 (unlike special comparisons as Object.is).
          NodeProperties::ReplaceValueInput(node, check, 1);
          return Changed(node).FollowedBy(
              ReduceSpeculativeNumberComparison(node));
        }
      }
    }
  }
  return UpdateChecks(node, checks);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::Reduction::FollowedBy(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Type::Is(), v8::internal::compiler::kSignedSmall, v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupBoundsCheckFor(), v8::internal::compiler::Reducer::NoChange(), node_checks_, v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::Type::UnsignedSmall(), and UpdateChecks().
Referenced by Reduce().
ReduceSpeculativeNumberOperation()
Reduction v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation (Node * node) [private]
Definition at line 465 of file redundancy-elimination.cc.
                                                                            {
  DCHECK(node->opcode() == IrOpcode::kSpeculativeNumberAdd ||
         node->opcode() == IrOpcode::kSpeculativeNumberSubtract ||
         node->opcode() == IrOpcode::kSpeculativeAdditiveSafeIntegerAdd ||
         node->opcode() == IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract ||
         node->opcode() == IrOpcode::kSpeculativeSmallIntegerAdd ||
         node->opcode() == IrOpcode::kSpeculativeSmallIntegerSubtract ||
         node->opcode() == IrOpcode::kSpeculativeToNumber);
  DCHECK_EQ(1, node->op()->EffectInputCount());
  DCHECK_EQ(1, node->op()->EffectOutputCount());
  Node* const first = NodeProperties::GetValueInput(node, 0);
  Node* const effect = NodeProperties::GetEffectInput(node);
  EffectPathChecks const* checks = node_checks_.Get(effect);
  // If we do not know anything about the predecessor, do not propagate just yet
  // because we will have to recompute anyway once we compute the predecessor.
  if (checks == nullptr) return NoChange();
  // Check if there's a CheckBounds operation on {first}
  // in the graph already, which we might be able to
  // reuse here to improve the representation selection
  // for the {node} later on.
  if (Node* check = checks->LookupBoundsCheckFor(first)) {
    // Only use the bounds {check} if its type is better
    // than the type of the {first} node, otherwise we
    // would end up replacing NumberConstant inputs with
    // CheckBounds operations, which is kind of pointless.
    if (!NodeProperties::GetType(first).Is(NodeProperties::GetType(check))) {
      NodeProperties::ReplaceValueInput(node, check, 0);
    }
  }
  return UpdateChecks(node, checks);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::Is(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::LookupBoundsCheckFor(), v8::internal::compiler::Reducer::NoChange(), node_checks_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), and UpdateChecks().
Referenced by Reduce().
ReduceStart()
Reduction v8::internal::compiler::RedundancyElimination::ReduceStart (Node * node) [private]
Definition at line 500 of file redundancy-elimination.cc.
                                                       {
  return UpdateChecks(node, EffectPathChecks::Empty(zone()));
}
References v8::internal::compiler::RedundancyElimination::EffectPathChecks::Empty(), UpdateChecks(), and zone().
Referenced by Reduce().
TakeChecksFromFirstEffect()
Reduction v8::internal::compiler::RedundancyElimination::TakeChecksFromFirstEffect (Node * node) [private]
Definition at line 518 of file redundancy-elimination.cc.
                                                                     {
  DCHECK_EQ(1, node->op()->EffectOutputCount());
  Node* const effect = NodeProperties::GetEffectInput(node);
  EffectPathChecks const* checks = node_checks_.Get(effect);
  // If we do not know anything about the predecessor, do not propagate just yet
  // because we will have to recompute anyway once we compute the predecessor.
  if (checks == nullptr) return NoChange();
  // We just propagate the information from the effect input (ideally,
  // we would only revisit effect uses if there is change).
  return UpdateChecks(node, checks);
}
References DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Reducer::NoChange(), node_checks_, v8::internal::compiler::Node::op(), and UpdateChecks().
Referenced by ReduceEffectPhi(), and ReduceOtherNode().
UpdateChecks()
Reduction v8::internal::compiler::RedundancyElimination::UpdateChecks (Node * node, EffectPathChecks const * checks) [private]
Definition at line 530 of file redundancy-elimination.cc.
                                                                              {
  EffectPathChecks const* original = node_checks_.Get(node);
  // Only signal that the {node} has Changed, if the information about {checks}
  // has changed wrt. the {original}.
  if (checks != original) {
    if (original == nullptr || !checks->Equals(original)) {
      node_checks_.Set(node, checks);
      return Changed(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::Equals(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::Reducer::NoChange(), node_checks_, and v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Set().
Referenced by ReduceCheckNode(), ReduceEffectPhi(), ReduceSpeculativeNumberComparison(), ReduceSpeculativeNumberOperation(), ReduceStart(), and TakeChecksFromFirstEffect().
zone()
Zone* v8::internal::compiler::RedundancyElimination::zone () const [inline], [private]
Definition at line 77 of file redundancy-elimination.h.
{ return zone_; }
Referenced by v8::internal::compiler::RedundancyElimination::EffectPathChecks::AddCheck(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::Copy(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::Empty(), ReduceCheckNode(), ReduceEffectPhi(), and ReduceStart().
Member Data Documentation
jsgraph_
JSGraph* v8::internal::compiler::RedundancyElimination::jsgraph_ [private]
Definition at line 80 of file redundancy-elimination.h.
Referenced by ReduceCheckNode().
node_checks_
PathChecksForEffectNodes v8::internal::compiler::RedundancyElimination::node_checks_ [private]
Definition at line 79 of file redundancy-elimination.h.
Referenced by Reduce(), ReduceCheckNode(), ReduceEffectPhi(), ReduceSpeculativeNumberComparison(), ReduceSpeculativeNumberOperation(), TakeChecksFromFirstEffect(), and UpdateChecks().
zone_
Zone* const v8::internal::compiler::RedundancyElimination::zone_ [private]
Definition at line 81 of file redundancy-elimination.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/redundancy-elimination.h
/mnt/V8SourceCode/src/compiler/redundancy-elimination.cc