v8::internal::RegExpAtom Class Reference
#include <regexp-ast.h>
Public Member Functions
RegExpAtom (base::Vector< const base::uc16 > data)
DECL_BOILERPLATE (Atom)
bool IsTextElement () override
int min_match () override
int max_match () override
void AppendToText (RegExpText *text, Zone *zone) override
base::Vector< const base::uc16 > data () const
int length () const
Private Attributes
base::Vector< const base::uc16 > data_
Additional Inherited Members
Detailed Description
Definition at line 472 of file regexp-ast.h.
Constructor & Destructor Documentation
RegExpAtom()
v8::internal::RegExpAtom::RegExpAtom (base::Vector< const base::uc16 > data) [inline], [explicit]
Definition at line 474 of file regexp-ast.h.
: data_(data) {}
Member Function Documentation
AppendToText()
void v8::internal::RegExpAtom::AppendToText (RegExpText * text, Zone * zone) [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 197 of file regexp-compiler.cc.
                                                          {
  text->AddElement(TextElement::Atom(this), zone);
}
References v8::internal::RegExpText::AddElement(), and v8::internal::TextElement::Atom().
data()
base::Vector<const base::uc16> v8::internal::RegExpAtom::data () const [inline]
Definition at line 483 of file regexp-ast.h.
{ return data_; }
References data_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CharAtEquals(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstChar(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareFirstCharCaseInsensitive(), v8::internal::RegExp::Compile(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::TextNode::TextEmitPass(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAtom().
DECL_BOILERPLATE()
v8::internal::RegExpAtom::DECL_BOILERPLATE (Atom)
IsTextElement()
bool v8::internal::RegExpAtom::IsTextElement () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 478 of file regexp-ast.h.
{ return true; }
length()
int v8::internal::RegExpAtom::length () const [inline]
Definition at line 484 of file regexp-ast.h.
{ return data_.length(); }
References data_, and v8::base::Vector< T >::length().
Referenced by v8::internal::TextNode::FillInBMInfo(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), and v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms().
max_match()
int v8::internal::RegExpAtom::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 480 of file regexp-ast.h.
{ return data_.length(); }
References data_, and v8::base::Vector< T >::length().
min_match()
int v8::internal::RegExpAtom::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 479 of file regexp-ast.h.
{ return data_.length(); }
References data_, and v8::base::Vector< T >::length().
Member Data Documentation
data_
base::Vector<const base::uc16> v8::internal::RegExpAtom::data_ [private]
Definition at line 487 of file regexp-ast.h.
Referenced by data(), length(), max_match(), and min_match().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc