v8::internal::compiler::CreateBoundFunctionParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateBoundFunctionParameters (size_t arity, MapRef map)
size_t arity () const
MapRef map () const
Private Attributes
size_t const arity_
const MapRef map_
Friends
bool operator== (CreateBoundFunctionParameters const &, CreateBoundFunctionParameters const &)
bool operator!= (CreateBoundFunctionParameters const &, CreateBoundFunctionParameters const &)
size_t hash_value (CreateBoundFunctionParameters const &)
std::ostream & operator<< (std::ostream &, CreateBoundFunctionParameters const &)
Detailed Description
Definition at line 648 of file js-operator.h.
Constructor & Destructor Documentation
CreateBoundFunctionParameters()
v8::internal::compiler::CreateBoundFunctionParameters::CreateBoundFunctionParameters (size_t arity, MapRef map) [inline]
Definition at line 650 of file js-operator.h.
      : arity_(arity), map_(map) {}
Member Function Documentation
arity()
size_t v8::internal::compiler::CreateBoundFunctionParameters::arity () const [inline]
Definition at line 653 of file js-operator.h.
{ return arity_; }
References arity_.
Referenced by v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction().
map()
MapRef v8::internal::compiler::CreateBoundFunctionParameters::map () const [inline]
Definition at line 654 of file js-operator.h.
{ return map_; }
References map_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction().
Friends And Related Function Documentation
hash_value
size_t hash_value (CreateBoundFunctionParameters const & p) [friend]
Definition at line 504 of file js-operator.cc.
                                                          {
  return base::hash_combine(p.arity(), p.map_.object().location());
}
operator!=
bool operator!= (CreateBoundFunctionParameters const & lhs, CreateBoundFunctionParameters const & rhs) [friend]
Definition at line 499 of file js-operator.cc.
                                                          {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, CreateBoundFunctionParameters const & p) [friend]
Definition at line 508 of file js-operator.cc.
                                                                 {
  os << p.arity();
  if (!p.map_.object().is_null()) os << ", " << Brief(*p.map_.object());
  return os;
}
operator==
bool operator== (CreateBoundFunctionParameters const & lhs, CreateBoundFunctionParameters const & rhs) [friend]
Definition at line 493 of file js-operator.cc.
                                                          {
  return lhs.arity() == rhs.arity() &&
         lhs.map_.object().location() == rhs.map_.object().location();
}
Member Data Documentation
arity_
size_t const v8::internal::compiler::CreateBoundFunctionParameters::arity_ [private]
Definition at line 657 of file js-operator.h.
Referenced by arity().
map_
const MapRef v8::internal::compiler::CreateBoundFunctionParameters::map_ [private]
Definition at line 658 of file js-operator.h.
Referenced by map().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h