v8::Isolate::SuppressMicrotaskExecutionScope Class Reference
Do not run microtasks while this scope is active, even if microtasks are automatically executed otherwise.
#include <v8-isolate.h>
Public Member Functions
SuppressMicrotaskExecutionScope (Isolate *isolate, MicrotaskQueue *microtask_queue=nullptr)
~SuppressMicrotaskExecutionScope ()
SuppressMicrotaskExecutionScope (const SuppressMicrotaskExecutionScope &)=delete
SuppressMicrotaskExecutionScope & operator= (const SuppressMicrotaskExecutionScope &)=delete
Private Attributes
internal::Isolate *const i_isolate_
internal::MicrotaskQueue *const microtask_queue_
internal::Address previous_stack_height_
Friends
class internal::ThreadLocalTop
Detailed Description
Do not run microtasks while this scope is active, even if microtasks are automatically executed otherwise.
Definition at line 442 of file v8-isolate.h.
Constructor & Destructor Documentation
SuppressMicrotaskExecutionScope() [1/2]
v8::Isolate::SuppressMicrotaskExecutionScope::SuppressMicrotaskExecutionScope (Isolate * isolate, MicrotaskQueue * microtask_queue = nullptr) [explicit]
Definition at line 10209 of file api.cc.
    : i_isolate_(reinterpret_cast<i::Isolate*>(v8_isolate)),
      microtask_queue_(microtask_queue
                           ? static_cast<i::MicrotaskQueue*>(microtask_queue)
                           : i_isolate_->default_microtask_queue()) {
  i_isolate_->thread_local_top()->IncrementCallDepth<true>(this);
  microtask_queue_->IncrementMicrotasksSuppressions();
}
References i_isolate_, v8::internal::ThreadLocalTop::IncrementCallDepth(), v8::internal::MicrotaskQueue::IncrementMicrotasksSuppressions(), microtask_queue_, and v8::internal::Isolate::thread_local_top().
 SuppressMicrotaskExecutionScope()
v8::Isolate::SuppressMicrotaskExecutionScope::~SuppressMicrotaskExecutionScope ()
Definition at line 10219 of file api.cc.
                                                                         {
  microtask_queue_->DecrementMicrotasksSuppressions();
  i_isolate_->thread_local_top()->DecrementCallDepth(this);
}
SuppressMicrotaskExecutionScope() [2/2]
v8::Isolate::SuppressMicrotaskExecutionScope::SuppressMicrotaskExecutionScope (const SuppressMicrotaskExecutionScope &) [delete]
Member Function Documentation
operator=()
SuppressMicrotaskExecutionScope& v8::Isolate::SuppressMicrotaskExecutionScope::operator= (const SuppressMicrotaskExecutionScope &) [delete]
Friends And Related Function Documentation
internal::ThreadLocalTop
friend class internal::ThreadLocalTop [friend]
Definition at line 459 of file v8-isolate.h.
Member Data Documentation
i_isolate_
internal::Isolate* const v8::Isolate::SuppressMicrotaskExecutionScope::i_isolate_ [private]
Definition at line 455 of file v8-isolate.h.
Referenced by SuppressMicrotaskExecutionScope().
microtask_queue_
internal::MicrotaskQueue* const v8::Isolate::SuppressMicrotaskExecutionScope::microtask_queue_ [private]
Definition at line 456 of file v8-isolate.h.
Referenced by SuppressMicrotaskExecutionScope().
previous_stack_height_
internal::Address v8::Isolate::SuppressMicrotaskExecutionScope::previous_stack_height_ [private]
Definition at line 457 of file v8-isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-isolate.h
/mnt/V8SourceCode/src/api/api.cc