v8::internal::wasm::gdb_server::SocketTransport Class Reference
#include <transport.h>
Public Member Functions
SocketTransport (SocketHandle s)
~SocketTransport () override
SocketTransport (const SocketTransport &)=delete
SocketTransport & operator= (const SocketTransport &)=delete
bool AcceptConnection () override
void WaitForDebugStubEvent () override
bool SignalThreadEvent () override
Private Member Functions
bool ReadSomeData () override
Private Attributes
int faulted_thread_fd_read_
int faulted_thread_fd_write_
Additional Inherited Members
Detailed Description
Definition at line 166 of file transport.h.
Constructor & Destructor Documentation
SocketTransport() [1/2]
v8::internal::wasm::gdb_server::SocketTransport::SocketTransport (SocketHandle s) [explicit]
Definition at line 340 of file transport.cc.
                                               : Transport(s) {
  int fds[2];
#if defined(__linux__)
  int ret = pipe2(fds, O_CLOEXEC);
#else
  int ret = pipe(fds);
#endif
  if (ret < 0) {
    TRACE_GDB_REMOTE(
        "SocketTransport::SocketTransport: Failed to allocate pipe for faulted "
        "thread\n");
  }
  faulted_thread_fd_read_ = fds[0];
  faulted_thread_fd_write_ = fds[1];
}
References faulted_thread_fd_read_, faulted_thread_fd_write_, and TRACE_GDB_REMOTE.
 SocketTransport()
v8::internal::wasm::gdb_server::SocketTransport::~SocketTransport () [override]
Definition at line 356 of file transport.cc.
                                  {
  if (close(faulted_thread_fd_read_) != 0) {
    TRACE_GDB_REMOTE(
        "SocketTransport::~SocketTransport: Failed to close "
        "event\n");
  }
  if (close(faulted_thread_fd_write_) != 0) {
    TRACE_GDB_REMOTE(
        "SocketTransport::~SocketTransport: Failed to close "
        "event\n");
  }
}
References faulted_thread_fd_read_, faulted_thread_fd_write_, and TRACE_GDB_REMOTE.
SocketTransport() [2/2]
v8::internal::wasm::gdb_server::SocketTransport::SocketTransport (const SocketTransport &) [delete]
Member Function Documentation
AcceptConnection()
bool v8::internal::wasm::gdb_server::SocketTransport::AcceptConnection () [override], [virtual]
Implements v8::internal::wasm::gdb_server::TransportBase.
Definition at line 369 of file transport.cc.
                                       {
  CHECK(handle_accept_ == InvalidSocket);
  handle_accept_ = ::accept(handle_bind_, NULL, 0);
  if (handle_accept_ != InvalidSocket) {
    DisableNagleAlgorithm(handle_accept_);
    return true;
  }
  return false;
}
References CHECK, v8::internal::wasm::gdb_server::DisableNagleAlgorithm(), v8::internal::wasm::gdb_server::Transport::handle_accept_, v8::internal::wasm::gdb_server::Transport::handle_bind_, and InvalidSocket.
operator=()
SocketTransport& v8::internal::wasm::gdb_server::SocketTransport::operator= (const SocketTransport &) [delete]
ReadSomeData()
bool v8::internal::wasm::gdb_server::SocketTransport::ReadSomeData () [override], [private], [virtual]
Implements v8::internal::wasm::gdb_server::Transport.
Definition at line 379 of file transport.cc.
                                   {
  while (true) {
    ssize_t result =
        ::recv(handle_accept_, buf_.get() + size_, kBufSize - size_, 0);
    if (result > 0) {
      size_ += result;
      return true;
    }
    if (result == 0) {
      return false; // The connection was gracefully closed.
    }
    if (SocketGetLastError() != kErrInterrupt) {
      return false;
    }
  }
}
References v8::internal::wasm::gdb_server::Transport::buf_, v8::internal::wasm::gdb_server::Transport::handle_accept_, v8::internal::wasm::gdb_server::Transport::kBufSize, kErrInterrupt, v8::base::internal::result, v8::internal::wasm::gdb_server::Transport::size_, and SocketGetLastError.
Referenced by WaitForDebugStubEvent().
SignalThreadEvent()
bool v8::internal::wasm::gdb_server::SocketTransport::SignalThreadEvent () [override], [virtual]
Implements v8::internal::wasm::gdb_server::TransportBase.
Definition at line 439 of file transport.cc.
                                        {
  // Notify the debug stub by marking the thread as faulted.
  char buf = 0;
  if (write(faulted_thread_fd_write_, &buf, sizeof(buf)) != sizeof(buf)) {
    TRACE_GDB_REMOTE(
        "SocketTransport:SignalThreadEvent: Can't send debug stub "
        "event\n");
    return false;
  }
  return true;
}
References faulted_thread_fd_write_, and TRACE_GDB_REMOTE.
WaitForDebugStubEvent()
void v8::internal::wasm::gdb_server::SocketTransport::WaitForDebugStubEvent () [override], [virtual]
Implements v8::internal::wasm::gdb_server::TransportBase.
Definition at line 396 of file transport.cc.
                                            {
  // Don't wait if we already have data to read.
  bool wait = !(pos_ < size_);
  fd_set fds;
  FD_ZERO(&fds);
  FD_SET(faulted_thread_fd_read_, &fds);
  int max_fd = faulted_thread_fd_read_;
  if (size_ < kBufSize) {
    FD_SET(handle_accept_, &fds);
    max_fd = std::max(max_fd, handle_accept_);
  }
  int ret;
  // We don't need sleep-polling on Linux now, so we set either zero or infinite
  // timeout.
  if (wait) {
    ret = select(max_fd + 1, &fds, NULL, NULL, NULL);
  } else {
    struct timeval timeout;
    timeout.tv_sec = 0;
    timeout.tv_usec = 0;
    ret = select(max_fd + 1, &fds, NULL, NULL, &timeout);
  }
  if (ret < 0) {
    TRACE_GDB_REMOTE(
        "SocketTransport::WaitForDebugStubEvent: Failed to wait for "
        "debug stub event\n");
  }
  if (ret > 0) {
    if (FD_ISSET(faulted_thread_fd_read_, &fds)) {
      char buf[16];
      if (read(faulted_thread_fd_read_, &buf, sizeof(buf)) < 0) {
        TRACE_GDB_REMOTE(
            "SocketTransport::WaitForDebugStubEvent: Failed to read from "
            "debug stub event pipe fd\n");
      }
    }
    if (FD_ISSET(handle_accept_, &fds)) ReadSomeData();
  }
}
References faulted_thread_fd_read_, v8::internal::wasm::gdb_server::Transport::handle_accept_, v8::internal::wasm::gdb_server::Transport::kBufSize, v8::internal::wasm::gdb_server::Transport::pos_, ReadSomeData(), v8::internal::wasm::gdb_server::Transport::size_, and TRACE_GDB_REMOTE.
Member Data Documentation
faulted_thread_fd_read_
int v8::internal::wasm::gdb_server::SocketTransport::faulted_thread_fd_read_ [private]
Definition at line 181 of file transport.h.
Referenced by SocketTransport(), WaitForDebugStubEvent(), and ~SocketTransport().
faulted_thread_fd_write_
int v8::internal::wasm::gdb_server::SocketTransport::faulted_thread_fd_write_ [private]
Definition at line 182 of file transport.h.
Referenced by SignalThreadEvent(), SocketTransport(), and ~SocketTransport().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/transport.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/transport.cc