v8::internal::IndexedReferencesExtractor Class Reference
Public Member Functions
IndexedReferencesExtractor (V8HeapExplorer *generator, Tagged< HeapObject > parent_obj, HeapEntry *parent)
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitMapPointer (Tagged< HeapObject > object) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) override
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) override
void VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) override
Private Member Functions
template<typename TIsolateOrCageBase , typename TSlot >
void VisitSlotImpl (TIsolateOrCageBase isolate_or_cage_base, TSlot slot)
void VisitHeapObjectImpl (Tagged< HeapObject > heap_object, int field_index)
Private Attributes
V8HeapExplorer * generator_
Tagged< HeapObject > parent_obj_
MaybeObjectSlot parent_start_
MaybeObjectSlot parent_end_
HeapEntry * parent_
int next_index_
Detailed Description
Definition at line 1233 of file heap-snapshot-generator.cc.
Constructor & Destructor Documentation
IndexedReferencesExtractor()
v8::internal::IndexedReferencesExtractor::IndexedReferencesExtractor (V8HeapExplorer * generator, Tagged< HeapObject > parent_obj, HeapEntry * parent) [inline]
Definition at line 1235 of file heap-snapshot-generator.cc.
      : ObjectVisitorWithCageBases(generator->isolate()),
        generator_(generator),
        parent_obj_(parent_obj),
        parent_start_(parent_obj_->RawMaybeWeakField(0)),
        parent_end_(
            parent_obj_->RawMaybeWeakField(parent_obj_->Size(cage_base()))),
        parent_(parent),
        next_index_(0) {}
Member Function Documentation
VisitCodeTarget()
void v8::internal::IndexedReferencesExtractor::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1268 of file heap-snapshot-generator.cc.
                                                  {
    Tagged<InstructionStream> target =
        InstructionStream::FromTargetAddress(rinfo->target_address());
    VisitHeapObjectImpl(target, -1);
  }
References v8::internal::InstructionStream::FromTargetAddress(), v8::internal::RelocInfo::target_address(), and VisitHeapObjectImpl().
VisitEmbeddedPointer()
void v8::internal::IndexedReferencesExtractor::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1275 of file heap-snapshot-generator.cc.
                                                       {
    Tagged<HeapObject> object = rinfo->target_object(cage_base());
    Tagged<Code> code = UncheckedCast<Code>(host->raw_code(kAcquireLoad));
    if (code->IsWeakObject(object)) {
      generator_->SetWeakReference(parent_, next_index_++, object, {});
    } else {
      VisitHeapObjectImpl(object, -1);
    }
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), code, generator_, v8::kAcquireLoad, next_index_, parent_, v8::internal::V8HeapExplorer::SetWeakReference(), v8::internal::RelocInfo::target_object(), and VisitHeapObjectImpl().
VisitHeapObjectImpl()
void v8::internal::IndexedReferencesExtractor::VisitHeapObjectImpl (Tagged< HeapObject > heap_object, int field_index) [inline], [private]
Definition at line 1351 of file heap-snapshot-generator.cc.
                                                      {
    DCHECK_LE(-1, field_index);
    // The last parameter {field_offset} is only used to check some well-known
    // skipped references, so passing -1 * kTaggedSize for objects embedded
    // into code is fine.
    generator_->SetHiddenReference(parent_obj_, parent_, next_index_++,
                                   heap_object, field_index * kTaggedSize);
  }
References DCHECK_LE, generator_, v8::internal::kTaggedSize, next_index_, parent_, parent_obj_, and v8::internal::V8HeapExplorer::SetHiddenReference().
Referenced by VisitCodeTarget(), VisitEmbeddedPointer(), and VisitSlotImpl().
VisitIndirectPointer()
void v8::internal::IndexedReferencesExtractor::VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1286 of file heap-snapshot-generator.cc.
                                                               {
    VisitSlotImpl(generator_->isolate(), slot);
  }
References generator_, v8::internal::V8HeapExplorer::isolate(), and VisitSlotImpl().
VisitInstructionStreamPointer()
void v8::internal::IndexedReferencesExtractor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1263 of file heap-snapshot-generator.cc.
                                                                          {
    VisitSlotImpl(code_cage_base(), slot);
  }
References v8::internal::ObjectVisitorWithCageBases::code_cage_base(), and VisitSlotImpl().
VisitJSDispatchTableEntry()
void v8::internal::IndexedReferencesExtractor::VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1309 of file heap-snapshot-generator.cc.
                                                                   {
#ifdef V8_ENABLE_LEAPTIERING
    // TODO(saelo): implement proper support for these fields here, similar to
    // how we handle indirect pointer or protected pointer fields.
    // Currently we only expect to see FeedbackCells or JSFunctions here.
    if (IsJSFunction(host)) {
      int field_index = JSFunction::kDispatchHandleOffset / kTaggedSize;
      CHECK(generator_->visited_fields_[field_index]);
      generator_->visited_fields_[field_index] = false;
    } else if (IsCode(host) || IsFeedbackCell(host)) {
      // Nothing to do: the Code object is tracked as part of the JSFunction.
    } else {
      UNREACHABLE();
    }
#endif // V8_ENABLE_LEAPTIERING
  }
References CHECK, generator_, v8::internal::kTaggedSize, v8::internal::UNREACHABLE(), and v8::internal::V8HeapExplorer::visited_fields_.
VisitMapPointer()
void v8::internal::IndexedReferencesExtractor::VisitMapPointer (Tagged< HeapObject > object) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1249 of file heap-snapshot-generator.cc.
                                                           {
    VisitSlotImpl(cage_base(), object->map_slot());
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and VisitSlotImpl().
VisitPointers() [1/2]
void v8::internal::IndexedReferencesExtractor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1252 of file heap-snapshot-generator.cc.
                                                   {
    // [start,end) must be a sub-region of [parent_start_, parent_end), i.e.
    // all the slots must point inside the object.
    CHECK_LE(parent_start_, start);
    CHECK_LE(end, parent_end_);
    for (MaybeObjectSlot slot = start; slot < end; ++slot) {
      VisitSlotImpl(cage_base(), slot);
    }
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), CHECK_LE, v8::internal::compiler::end(), parent_end_, parent_start_, and VisitSlotImpl().
VisitPointers() [2/2]
void v8::internal::IndexedReferencesExtractor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1245 of file heap-snapshot-generator.cc.
                                              {
    VisitPointers(host, MaybeObjectSlot(start), MaybeObjectSlot(end));
  }
References v8::internal::compiler::end().
VisitProtectedPointer() [1/2]
void v8::internal::IndexedReferencesExtractor::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1300 of file heap-snapshot-generator.cc.
                                                                     {
    // TODO(saelo): the cage base doesn't currently matter as it isn't used,
    // but technically we should either use the trusted cage base here or
    // remove the cage_base parameter.
    const PtrComprCageBase unused_cage_base(kNullAddress);
    VisitSlotImpl(unused_cage_base, slot);
  }
References v8::internal::kNullAddress, and VisitSlotImpl().
VisitProtectedPointer() [2/2]
void v8::internal::IndexedReferencesExtractor::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1291 of file heap-snapshot-generator.cc.
                                                                 {
    // TODO(saelo): the cage base doesn't currently matter as it isn't used,
    // but technically we should either use the trusted cage base here or
    // remove the cage_base parameter.
    const PtrComprCageBase unused_cage_base(kNullAddress);
    VisitSlotImpl(unused_cage_base, slot);
  }
References v8::internal::kNullAddress, and VisitSlotImpl().
VisitSlotImpl()
template<typename TIsolateOrCageBase , typename TSlot >
void v8::internal::IndexedReferencesExtractor::VisitSlotImpl (TIsolateOrCageBase isolate_or_cage_base, TSlot slot) [inline], [private]
Definition at line 1329 of file heap-snapshot-generator.cc.
                                           {
    int field_index =
        static_cast<int>(slot.address() - parent_start_.address()) /
        TSlot::kSlotDataSize;
#ifdef V8_TARGET_BIG_ENDIAN
    field_index += AdjustEmbedderFieldIndex(parent_obj_, field_index);
#endif
    DCHECK_GE(field_index, 0);
    if (generator_->visited_fields_[field_index]) {
      generator_->visited_fields_[field_index] = false;
    } else {
      Tagged<HeapObject> heap_object;
      auto loaded_value = slot.load(isolate_or_cage_base);
      if (loaded_value.GetHeapObjectIfStrong(&heap_object)) {
        VisitHeapObjectImpl(heap_object, field_index);
      } else if (loaded_value.GetHeapObjectIfWeak(&heap_object)) {
        generator_->SetWeakReference(parent_, next_index_++, heap_object, {});
      }
    }
  }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), DCHECK_GE, generator_, next_index_, parent_, parent_obj_, parent_start_, v8::internal::V8HeapExplorer::SetWeakReference(), v8::internal::V8HeapExplorer::visited_fields_, and VisitHeapObjectImpl().
Referenced by VisitIndirectPointer(), VisitInstructionStreamPointer(), VisitMapPointer(), VisitPointers(), and VisitProtectedPointer().
Member Data Documentation
generator_
V8HeapExplorer* v8::internal::IndexedReferencesExtractor::generator_ [private]
Definition at line 1361 of file heap-snapshot-generator.cc.
Referenced by VisitEmbeddedPointer(), VisitHeapObjectImpl(), VisitIndirectPointer(), VisitJSDispatchTableEntry(), and VisitSlotImpl().
next_index_
int v8::internal::IndexedReferencesExtractor::next_index_ [private]
Definition at line 1366 of file heap-snapshot-generator.cc.
Referenced by VisitEmbeddedPointer(), VisitHeapObjectImpl(), and VisitSlotImpl().
parent_
HeapEntry* v8::internal::IndexedReferencesExtractor::parent_ [private]
Definition at line 1365 of file heap-snapshot-generator.cc.
Referenced by VisitEmbeddedPointer(), VisitHeapObjectImpl(), and VisitSlotImpl().
parent_end_
MaybeObjectSlot v8::internal::IndexedReferencesExtractor::parent_end_ [private]
Definition at line 1364 of file heap-snapshot-generator.cc.
Referenced by VisitPointers().
parent_obj_
Tagged<HeapObject> v8::internal::IndexedReferencesExtractor::parent_obj_ [private]
Definition at line 1362 of file heap-snapshot-generator.cc.
Referenced by VisitHeapObjectImpl(), and VisitSlotImpl().
parent_start_
MaybeObjectSlot v8::internal::IndexedReferencesExtractor::parent_start_ [private]
Definition at line 1363 of file heap-snapshot-generator.cc.
Referenced by VisitPointers(), and VisitSlotImpl().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc