v8::internal::compiler::VariableTracker::State Class Reference
Public Types
using Map = PersistentMap< Variable, Node * >
Public Member Functions
State (Zone *zone)
Node * Get (Variable var) const
void Set (Variable var, Node *node)
Map::iterator begin () const
Map::iterator end () const
bool operator!= (const State &other) const
Private Attributes
Map map_
Detailed Description
Definition at line 101 of file escape-analysis.cc.
Member Typedef Documentation
Map
using v8::internal::compiler::VariableTracker::State::Map = PersistentMap<Variable, Node*>
Definition at line 103 of file escape-analysis.cc.
Constructor & Destructor Documentation
State()
v8::internal::compiler::VariableTracker::State::State (Zone * zone) [inline], [explicit]
Definition at line 105 of file escape-analysis.cc.
: map_(zone) {}
Member Function Documentation
begin()
Map::iterator v8::internal::compiler::VariableTracker::State::begin () const [inline]
Definition at line 114 of file escape-analysis.cc.
{ return map_.begin(); }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::begin(), and map_.
end()
Map::iterator v8::internal::compiler::VariableTracker::State::end () const [inline]
Definition at line 115 of file escape-analysis.cc.
{ return map_.end(); }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::end(), and map_.
Get()
Node* v8::internal::compiler::VariableTracker::State::Get (Variable var) const [inline]
Definition at line 106 of file escape-analysis.cc.
                                  {
      CHECK(var != Variable::Invalid());
      return map_.Get(var);
    }
References CHECK, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get(), v8::internal::compiler::Variable::Invalid(), and map_.
operator!=()
bool v8::internal::compiler::VariableTracker::State::operator!= (const State & other) const [inline]
Definition at line 116 of file escape-analysis.cc.
{ return map_ != other.map_; }
References map_.
Set()
void v8::internal::compiler::VariableTracker::State::Set (Variable var, Node * node) [inline]
Definition at line 110 of file escape-analysis.cc.
                                       {
      CHECK(var != Variable::Invalid());
      return map_.Set(var, node);
    }
References CHECK, v8::internal::compiler::Variable::Invalid(), map_, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set().
Member Data Documentation
map_
Map v8::internal::compiler::VariableTracker::State::map_ [private]
Definition at line 119 of file escape-analysis.cc.
Referenced by begin(), end(), Get(), operator!=(), and Set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.cc