v8::Map Class Reference
An instance of the built-in Map constructor (ECMA-262, 6th Edition, 23.1.1).
#include <v8-container.h>
Public Member Functions
size_t Size () const
void Clear ()
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Get (Local< Context > context, Local< Value > key)
V8_WARN_UNUSED_RESULT MaybeLocal< Map > Set (Local< Context > context, Local< Value > key, Local< Value > value)
V8_WARN_UNUSED_RESULT Maybe< bool > Has (Local< Context > context, Local< Value > key)
V8_WARN_UNUSED_RESULT Maybe< bool > Delete (Local< Context > context, Local< Value > key)
Local< Array > AsArray () const
Returns an array of length Size() * 2, where index N is the Nth key and index N + 1 is the Nth value.
Static Public Member Functions
static Local< Map > New (Isolate *isolate)
Creates a new empty Map.
static Map * Cast (Value *value)
Private Member Functions
Map ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in Map constructor (ECMA-262, 6th Edition, 23.1.1).
Definition at line 108 of file v8-container.h.
Constructor & Destructor Documentation
Map()
v8::Map::Map () [private]
Member Function Documentation
AsArray()
Local< Array > v8::Map::AsArray () const
Returns an array of length Size() * 2, where index N is the Nth key and index N + 1 is the Nth value.
Definition at line 8499 of file api.cc.
                                {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Map_AsArray);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return Utils::ToLocal(
      MapAsArray(i_isolate, obj->table(), 0, MapAsArrayKind::kEntries));
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::MapAsArray(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Object::PreviewEntries().
Cast()
static Map* v8::Map::Cast (Value * value) [inline], [static]
Definition at line 133 of file v8-container.h.
                                           {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Map*>(value);
  }
References v8::internal::value.
Referenced by v8::Object::PreviewEntries().
CheckCast()
void v8::Map::CheckCast (Value * obj) [static], [private]
Definition at line 3967 of file api.cc.
                                 {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSMap(*obj), "v8::Map::Cast", "Value is not a Map");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Clear()
void v8::Map::Clear ()
Definition at line 8394 of file api.cc.
                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Map_Clear);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::JSMap::Clear(i_isolate, self);
}
References v8::internal::JSMap::Clear(), v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
Delete()
Maybe< bool > v8::Map::Delete (Local< Context > context, Local< Value > key)
Definition at line 8436 of file api.cc.
                                                                {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Map_Delete};
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> result;
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key)};
  if (!i::Execution::CallBuiltin(i_isolate, i_isolate->map_delete(), self,
                                 base::VectorOf(args))
           .ToHandle(&result)) {
    return {};
  }
  return Just(i::IsTrue(*result, i_isolate));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::Isolate::Current(), v8::Just(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::base::internal::result, and v8::base::VectorOf().
Get()
MaybeLocal< Value > v8::Map::Get (Local< Context > context, Local< Value > key)
Definition at line 8402 of file api.cc.
                                                                   {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Map_Get};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key)};
  return api_scope.EscapeMaybe(i::Execution::CallBuiltin(
      i_isolate, i_isolate->map_get(), self, base::VectorOf(args)));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::key, v8::Utils::OpenDirectHandle(), and v8::base::VectorOf().
Referenced by v8_inspector::V8SerializationDuplicateTracker::FindKnownSerializedValue().
Has()
Maybe< bool > v8::Map::Has (Local< Context > context, Local< Value > key)
Definition at line 8422 of file api.cc.
                                                             {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Map_Has};
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> result;
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key)};
  if (!i::Execution::CallBuiltin(i_isolate, i_isolate->map_has(), self,
                                 base::VectorOf(args))
           .ToHandle(&result)) {
    return {};
  }
  return Just(i::IsTrue(*result, i_isolate));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::Isolate::Current(), v8::Just(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::base::internal::result, and v8::base::VectorOf().
New()
Local< v8::Map > v8::Map::New (Isolate * isolate) [static]
Creates a new empty Map.
Definition at line 8381 of file api.cc.
                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Map_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::JSMap> obj = i_isolate->factory()->NewJSMap();
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewJSMap().
Set()
MaybeLocal< Map > v8::Map::Set (Local< Context > context, Local< Value > key, Local< Value > value)
Definition at line 8411 of file api.cc.
                                             {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Map_Set};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  i::DirectHandle<i::Object> args[] = {Utils::OpenDirectHandle(*key),
                                       Utils::OpenDirectHandle(*value)};
  return api_scope.EscapeMaybe(i::Cast<i::JSMap>(i::Execution::CallBuiltin(
      i_isolate, i_isolate->map_set(), self, base::VectorOf(args))));
}
References v8::base::args, v8::internal::Execution::CallBuiltin(), v8::internal::key, v8::Utils::OpenDirectHandle(), v8::internal::value, and v8::base::VectorOf().
Referenced by v8_inspector::V8SerializationDuplicateTracker::SetKnownSerializedValue().
Size()
size_t v8::Map::Size () const
Definition at line 8389 of file api.cc.
                         {
  auto obj = Utils::OpenDirectHandle(this);
  return i::Cast<i::OrderedHashMap>(obj->table())->NumberOfElements();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-container.h
/mnt/V8SourceCode/src/api/api.cc