v8::internal::SnapshotByteSink Class Reference
Sink to write snapshot files to.
#include <snapshot-source-sink.h>
Public Member Functions
SnapshotByteSink ()=default
SnapshotByteSink (int initial_size)
~SnapshotByteSink ()=default
void Put (uint8_t b, const char *description)
void PutN (int number_of_bytes, const uint8_t v, const char *description)
void PutUint30 (uint32_t integer, const char *description)
void PutUint32 (uint32_t integer, const char *description)
void PutRaw (const uint8_t *data, int number_of_bytes, const char *description)
void Append (const SnapshotByteSink &other)
int Position () const
const std::vector< uint8_t > * data () const
Private Attributes
std::vector< uint8_t > data_
Detailed Description
Sink to write snapshot files to.
Users must implement actual storage or i/o.
Definition at line 128 of file snapshot-source-sink.h.
Constructor & Destructor Documentation
SnapshotByteSink() [1/2]
v8::internal::SnapshotByteSink::SnapshotByteSink () [default]
SnapshotByteSink() [2/2]
v8::internal::SnapshotByteSink::SnapshotByteSink (int initial_size) [inline], [explicit]
Definition at line 131 of file snapshot-source-sink.h.
: data_(initial_size) {}
 SnapshotByteSink()
v8::internal::SnapshotByteSink::~SnapshotByteSink () [default]
Member Function Documentation
Append()
void v8::internal::SnapshotByteSink::Append (const SnapshotByteSink & other)
Definition at line 43 of file snapshot-source-sink.cc.
                                                           {
  data_.insert(data_.end(), other.data_.begin(), other.data_.end());
}
References data_.
Referenced by v8::internal::ContextSerializer::Serialize().
data()
const std::vector<uint8_t>* v8::internal::SnapshotByteSink::data () const [inline]
Definition at line 149 of file snapshot-source-sink.h.
{ return &data_; }
References data_.
Referenced by v8::internal::Serializer::Payload(), PutRaw(), v8::internal::ContextSerializer::Serialize(), and v8::internal::CodeSerializer::SerializeSharedFunctionInfo().
Position()
int v8::internal::SnapshotByteSink::Position () const [inline]
Definition at line 147 of file snapshot-source-sink.h.
{ return static_cast<int>(data_.size()); }
References data_.
Referenced by v8::internal::Serializer::Pad(), and v8::internal::Serializer::ObjectSerializer::SerializePrologue().
Put()
void v8::internal::SnapshotByteSink::Put (uint8_t b, const char * description) [inline]
Definition at line 135 of file snapshot-source-sink.h.
{ data_.push_back(b); }
References data_.
Referenced by v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::Serializer::Pad(), v8::internal::Serializer::PutAttachedReference(), v8::internal::Serializer::PutPendingForwardReference(), v8::internal::Serializer::PutRepeatRoot(), v8::internal::Serializer::PutRoot(), v8::internal::Serializer::PutSmiRoot(), PutUint30(), v8::internal::Serializer::ResolvePendingForwardReference(), v8::internal::ContextSerializer::Serialize(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::Serializer::ObjectSerializer::SerializeBackingStore(), v8::internal::Serializer::SerializeBackReference(), v8::internal::Serializer::SerializeDeferredObjects(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::Serializer::SerializeHotObject(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache(), v8::internal::StartupSerializer::SerializeUsingStartupObjectCache(), v8::internal::RootsSerializer::Synchronize(), v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer(), v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer(), v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry(), v8::internal::Serializer::ObjectSerializer::VisitPointers(), and v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer().
PutN()
void v8::internal::SnapshotByteSink::PutN (int number_of_bytes, const uint8_t v, const char * description)
Definition at line 16 of file snapshot-source-sink.cc.
                                                     {
  data_.insert(data_.end(), number_of_bytes, v);
}
References data_.
Referenced by v8::internal::Serializer::ObjectSerializer::OutputRawData().
PutRaw()
void v8::internal::SnapshotByteSink::PutRaw (const uint8_t * data, int number_of_bytes, const char * description)
Definition at line 35 of file snapshot-source-sink.cc.
                                                       {
#ifdef MEMORY_SANITIZER
  __msan_check_mem_is_initialized(data, number_of_bytes);
#endif
  data_.insert(data_.end(), data, data + number_of_bytes);
}
References data(), and data_.
Referenced by v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::anonymous_namespace{serializer.cc}::OutputRawWithCustomField(), v8::internal::Serializer::PutSmiRoot(), PutUint32(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::Serializer::ObjectSerializer::SerializeBackingStore(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), and v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer().
PutUint30()
void v8::internal::SnapshotByteSink::PutUint30 (uint32_t integer, const char * description)
Definition at line 21 of file snapshot-source-sink.cc.
                                                                          {
  CHECK_LT(integer, 1UL << 30);
  integer <<= 2;
  int bytes = 1;
  if (integer > 0xFF) bytes = 2;
  if (integer > 0xFFFF) bytes = 3;
  if (integer > 0xFFFFFF) bytes = 4;
  integer |= (bytes - 1);
  Put(static_cast<uint8_t>(integer & 0xFF), "IntPart1");
  if (bytes > 1) Put(static_cast<uint8_t>((integer >> 8) & 0xFF), "IntPart2");
  if (bytes > 2) Put(static_cast<uint8_t>((integer >> 16) & 0xFF), "IntPart3");
  if (bytes > 3) Put(static_cast<uint8_t>((integer >> 24) & 0xFF), "IntPart4");
}
References CHECK_LT, and Put().
Referenced by v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), v8::internal::Serializer::ObjectSerializer::OutputRawData(), v8::internal::Serializer::PutAttachedReference(), v8::internal::Serializer::PutBackReference(), v8::internal::Serializer::PutRepeatRoot(), v8::internal::Serializer::PutRoot(), v8::internal::Serializer::ResolvePendingForwardReference(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields(), v8::internal::Serializer::ObjectSerializer::SerializePrologue(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::SharedHeapSerializer::SerializeStringTable(), v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache(), v8::internal::StartupSerializer::SerializeUsingStartupObjectCache(), v8::internal::StartupSerializer::StartupSerializer(), and v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry().
PutUint32()
void v8::internal::SnapshotByteSink::PutUint32 (uint32_t integer, const char * description) [inline]
Definition at line 140 of file snapshot-source-sink.h.
                                                            {
    PutRaw(reinterpret_cast<uint8_t*>(&integer), sizeof(integer), description);
  }
References PutRaw().
Referenced by v8::internal::Serializer::ObjectSerializer::SerializeBackingStore().
Member Data Documentation
data_
std::vector<uint8_t> v8::internal::SnapshotByteSink::data_ [private]
Definition at line 152 of file snapshot-source-sink.h.
Referenced by Append(), data(), Position(), Put(), PutN(), and PutRaw().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/snapshot-source-sink.h
/mnt/V8SourceCode/src/snapshot/snapshot-source-sink.cc