v8::internal::compiler::GraphAssembler Class Reference
#include <graph-assembler.h>
Classes
class BlockInlineReduction
class LoopScope
class RestoreEffectControlScope
Public Member Functions
GraphAssembler (MachineGraph *jsgraph, Zone *zone, BranchSemantics default_branch_semantics, std::optional< NodeChangedCallback > node_changed_callback=std::nullopt, bool mark_loop_exits=false)
virtual ~GraphAssembler ()
virtual SimplifiedOperatorBuilder * simplified ()
void Reset ()
void InitializeEffectControl (Node *effect, Node *control)
template<typename... Reps>
detail::GraphAssemblerLabelForReps< Reps... > MakeLabelFor (GraphAssemblerLabelType type, Reps... reps)
GraphAssemblerDynamicLabel MakeLabelFor (GraphAssemblerLabelType type, base::SmallVector< MachineRepresentation, 4 > reps)
template<typename... Reps>
detail::GraphAssemblerLabelForReps< Reps... > MakeLabel (Reps... reps)
template<typename... Reps>
detail::GraphAssemblerLabelForReps< Reps... > MakeLoopLabel (Reps... reps)
template<typename... Reps>
detail::GraphAssemblerLabelForReps< Reps... > MakeDeferredLabel (Reps... reps)
Node * IntPtrConstant (intptr_t value)
TNode< UintPtrT > UintPtrConstant (uintptr_t value)
Node * Int32Constant (int32_t value)
TNode< Uint32T > Uint32Constant (uint32_t value)
Node * Int64Constant (int64_t value)
Node * Uint64Constant (uint64_t value)
Node * UniqueIntPtrConstant (intptr_t value)
Node * Float64Constant (double value)
Node * ExternalConstant (ExternalReference ref)
Node * IsolateField (IsolateFieldId id)
Node * Projection (int index, Node *value, Node *ctrl=nullptr)
Node * Parameter (int index)
Node * LoadFramePointer ()
Node * LoadRootRegister ()
Node * LoadHeapNumberValue (Node *heap_number)
TNode< BoolT > UintPtrLessThan (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< BoolT > UintPtrLessThanOrEqual (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< UintPtrT > UintPtrAdd (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< UintPtrT > UintPtrSub (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< UintPtrT > UintPtrDiv (TNode< UintPtrT > left, TNode< UintPtrT > right)
TNode< UintPtrT > ChangeUint32ToUintPtr (SloppyTNode< Uint32T > value)
TNode< Map > LoadMap (Node *object)
Node * DebugBreak ()
Node * Unreachable ()
Node * UnreachableWithoutConnectToEnd ()
Node * IntPtrEqual (Node *left, Node *right)
Node * TaggedEqual (Node *left, Node *right)
Node * SmiSub (Node *left, Node *right)
Node * SmiLessThan (Node *left, Node *right)
Node * Float64RoundDown (Node *value)
Node * Float64RoundTruncate (Node *value)
Node * TruncateFloat64ToInt64 (Node *value, TruncateKind kind)
Node * BitcastWordToTagged (Node *value)
Node * BitcastWordToTaggedSigned (Node *value)
Node * BitcastTaggedToWord (Node *value)
Node * BitcastTaggedToWordForTagAndSmiBits (Node *value)
Node * BitcastMaybeObjectToWord (Node *value)
Node * TypeGuard (Type type, Node *value)
template<typename T >
TNode< T > TypeGuard (Type type, TNode< T > value)
Node * Checkpoint (FrameState frame_state)
TNode< RawPtrT > StackSlot (int size, int alignment, bool is_tagged=false)
Node * AdaptLocalArgument (Node *argument)
Node * Store (StoreRepresentation rep, Node *object, Node *offset, Node *value)
Node * Store (StoreRepresentation rep, Node *object, int offset, Node *value)
Node * Load (MachineType type, Node *object, Node *offset)
Node * Load (MachineType type, Node *object, int offset)
Node * StoreUnaligned (MachineRepresentation rep, Node *object, Node *offset, Node *value)
Node * LoadUnaligned (MachineType type, Node *object, Node *offset)
Node * ProtectedStore (MachineRepresentation rep, Node *object, Node *offset, Node *value)
Node * ProtectedLoad (MachineType type, Node *object, Node *offset)
Node * LoadTrapOnNull (MachineType type, Node *object, Node *offset)
Node * StoreTrapOnNull (StoreRepresentation rep, Node *object, Node *offset, Node *value)
Node * Retain (Node *buffer)
Node * IntPtrAdd (Node *a, Node *b)
Node * IntPtrSub (Node *a, Node *b)
Node * DeoptimizeIf (DeoptimizeReason reason, FeedbackSource const &feedback, Node *condition, Node *frame_state)
Node * DeoptimizeIfNot (DeoptimizeReason reason, FeedbackSource const &feedback, Node *condition, Node *frame_state)
TNode< Object > Call (const CallDescriptor *call_descriptor, int inputs_size, Node **inputs)
TNode< Object > Call (const Operator *op, int inputs_size, Node **inputs)
template<typename... Args>
TNode< Object > Call (const CallDescriptor *call_descriptor, Node *first_arg, Args... args)
template<typename... Args>
TNode< Object > Call (const Operator *op, Node *first_arg, Args... args)
void TailCall (const CallDescriptor *call_descriptor, int inputs_size, Node **inputs)
template<size_t VarCount>
void Bind (GraphAssemblerLabel< VarCount > *label)
template<typename... Vars>
void Goto (detail::GraphAssemblerLabelForVars< Vars... > *label, Vars...)
void BranchWithCriticalSafetyCheck (Node *condition, GraphAssemblerLabel< 0u > *if_true, GraphAssemblerLabel< 0u > *if_false)
template<typename... Vars>
void Branch (Node *condition, detail::GraphAssemblerLabelForVars< Vars... > *if_true, detail::GraphAssemblerLabelForVars< Vars... > *if_false, Vars...)
template<typename... Vars>
void BranchWithHint (Node *condition, detail::GraphAssemblerLabelForVars< Vars... > *if_true, detail::GraphAssemblerLabelForVars< Vars... > *if_false, BranchHint hint, Vars...)
template<typename... Vars>
void MachineBranch (TNode< Word32T > condition, GraphAssemblerLabel< sizeof...(Vars)> *if_true, GraphAssemblerLabel< sizeof...(Vars)> *if_false, BranchHint hint, Vars...)
template<typename... Vars>
void JSBranch (TNode< Boolean > condition, GraphAssemblerLabel< sizeof...(Vars)> *if_true, GraphAssemblerLabel< sizeof...(Vars)> *if_false, BranchHint hint, Vars...)
template<typename... Vars>
void GotoIf (Node *condition, detail::GraphAssemblerLabelForVars< Vars... > *label, BranchHint hint, Vars...)
template<typename... Vars>
void GotoIfNot (Node *condition, detail::GraphAssemblerLabelForVars< Vars... > *label, BranchHint hint, Vars...)
template<typename... Vars>
void GotoIf (Node *condition, detail::GraphAssemblerLabelForVars< Vars... > *label, Vars...)
template<typename... Vars>
void GotoIfNot (Node *condition, detail::GraphAssemblerLabelForVars< Vars... > *label, Vars...)
void RuntimeAbort (AbortReason reason)
bool HasActiveBlock () const
void UpdateEffectControlWith (Node *node)
Node * AddNode (Node *node)
template<typename T >
TNode< T > AddNode (Node *node)
void ConnectUnreachableToEnd ()
void AddInlineReducer (Reducer *reducer)
Control control () const
Effect effect () const
Node * start () const
Protected Member Functions
constexpr bool Is64 () const
template<typename... Vars>
void MergeState (detail::GraphAssemblerLabelForVars< Vars... > *label, Vars... vars)
Node * AddClonedNode (Node *node)
MachineGraph * mcgraph () const
TFGraph * graph () const
Zone * temp_zone () const
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
Private Member Functions
template<typename... Vars>
void BranchImpl (BranchSemantics semantics, Node *condition, GraphAssemblerLabel< sizeof...(Vars)> *if_true, GraphAssemblerLabel< sizeof...(Vars)> *if_false, BranchHint hint, Vars...)
Private Attributes
Zone * temp_zone_
MachineGraph * mcgraph_
BranchSemantics default_branch_semantics_
Node * effect_
Node * control_
std::optional< NodeChangedCallback > node_changed_callback_
ZoneVector< Reducer * > inline_reducers_
bool inline_reductions_blocked_
int loop_nesting_level_ = 0
ZoneVector< Node ** > loop_headers_
const bool mark_loop_exits_
Detailed Description
Definition at line 278 of file graph-assembler.h.
Constructor & Destructor Documentation
GraphAssembler()
v8::internal::compiler::GraphAssembler::GraphAssembler (MachineGraph * jsgraph, Zone * zone, BranchSemantics default_branch_semantics, std::optional< NodeChangedCallback > node_changed_callback = std::nullopt, bool mark_loop_exits = false)
Definition at line 48 of file graph-assembler.cc.
    : temp_zone_(zone),
      mcgraph_(mcgraph),
      default_branch_semantics_(default_branch_semantics),
      effect_(nullptr),
      control_(nullptr),
      node_changed_callback_(node_changed_callback),
      inline_reducers_(zone),
      inline_reductions_blocked_(false),
      loop_headers_(zone),
      mark_loop_exits_(mark_loop_exits) {
  DCHECK_NE(default_branch_semantics_, BranchSemantics::kUnspecified);
}
References DCHECK_NE, default_branch_semantics_, and v8::internal::compiler::kUnspecified.
 GraphAssembler()
v8::internal::compiler::GraphAssembler::~GraphAssembler () [virtual]
Definition at line 65 of file graph-assembler.cc.
{ DCHECK_EQ(loop_nesting_level_, 0); }
References DCHECK_EQ, and loop_nesting_level_.
Member Function Documentation
AdaptLocalArgument()
Node * v8::internal::compiler::GraphAssembler::AdaptLocalArgument (Node * argument)
Definition at line 1109 of file graph-assembler.cc.
                                                       {
#ifdef V8_ENABLE_DIRECT_HANDLE
  // With direct locals, the argument can be passed directly.
  return BitcastTaggedToWord(argument);
#else
  // With indirect locals, the argument has to be stored on the stack and the
  // slot address is passed.
  Node* stack_slot = StackSlot(sizeof(uintptr_t), alignof(uintptr_t), true);
  Store(StoreRepresentation(MachineType::PointerRepresentation(),
                            kNoWriteBarrier),
        stack_slot, 0, BitcastTaggedToWord(argument));
  return stack_slot;
#endif
}
References BitcastTaggedToWord(), v8::internal::compiler::kNoWriteBarrier, v8::internal::MachineType::PointerRepresentation(), StackSlot(), and Store().
AddClonedNode()
Node * v8::internal::compiler::GraphAssembler::AddClonedNode (Node * node) [inline], [protected]
Definition at line 1304 of file graph-assembler.cc.
                                              {
  DCHECK(node->op()->HasProperty(Operator::kPure));
  UpdateEffectControlWith(node);
  return node;
}
References v8::internal::DCHECK(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Operator::kPure, v8::internal::compiler::Node::op(), and UpdateEffectControlWith().
Referenced by v8::internal::compiler::JSGraphAssembler::CEntryStubConstant(), v8::internal::compiler::JSGraphAssembler::Constant(), ExternalConstant(), Float64Constant(), v8::internal::compiler::JSGraphAssembler::HeapConstant(), Int32Constant(), Int64Constant(), IntPtrConstant(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::compiler::JSGraphAssembler::SmiConstant(), and Uint64Constant().
AddInlineReducer()
void v8::internal::compiler::GraphAssembler::AddInlineReducer (Reducer * reducer) [inline]
Definition at line 547 of file graph-assembler.h.
                                          {
    inline_reducers_.push_back(reducer);
  }
AddNode() [1/2]
Node * v8::internal::compiler::GraphAssembler::AddNode (Node * node)
Definition at line 1310 of file graph-assembler.cc.
                                        {
  if (!inline_reducers_.empty() && !inline_reductions_blocked_) {
    // Reducers may add new nodes to the graph using this graph assembler,
    // however they should never introduce nodes that need further reduction,
    // so block reduction
    BlockInlineReduction scope(this);
    Reduction reduction;
    for (auto reducer : inline_reducers_) {
      reduction = reducer->Reduce(node, nullptr);
      if (reduction.Changed()) break;
    }
    if (reduction.Changed()) {
      Node* replacement = reduction.replacement();
      if (replacement != node) {
        // Replace all uses of node and kill the node to make sure we don't
        // leave dangling dead uses.
        NodeProperties::ReplaceUses(node, replacement, effect(), control());
        node->Kill();
        return replacement;
      }
    }
  }
  if (node->opcode() == IrOpcode::kTerminate) {
    return node;
  }
  UpdateEffectControlWith(node);
  return node;
}
References v8::internal::compiler::Reduction::Changed(), control(), effect(), inline_reducers_, inline_reductions_blocked_, v8::internal::compiler::Node::Kill(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Reduction::replacement(), v8::internal::compiler::NodeProperties::ReplaceUses(), and UpdateEffectControlWith().
Referenced by v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::ArrayGet(), v8::internal::compiler::WasmGraphAssembler::ArrayInitializeLength(), v8::internal::compiler::WasmGraphAssembler::ArrayLength(), v8::internal::compiler::WasmGraphAssembler::ArraySet(), v8::internal::compiler::JSGraphAssembler::Assert(), v8::internal::compiler::WasmGraphAssembler::AssertNotNull(), Bind(), BitcastMaybeObjectToWord(), BitcastTaggedToWord(), BitcastTaggedToWordForTagAndSmiBits(), BitcastWordToTagged(), BitcastWordToTaggedSigned(), v8::internal::compiler::JSGraphAssembler::BooleanNot(), v8::internal::compiler::JSGraphAssembler::Chained(), v8::internal::compiler::JSGraphAssembler::CheckIf(), v8::internal::compiler::JSGraphAssembler::CheckNumber(), v8::internal::compiler::JSGraphAssembler::CheckNumberFitsInt32(), Checkpoint(), v8::internal::compiler::JSGraphAssembler::CheckSmi(), v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), DebugBreak(), DeoptimizeIf(), DeoptimizeIfNot(), Float64RoundDown(), Float64RoundTruncate(), GotoIf(), GotoIfNot(), v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject(), IntPtrAdd(), IntPtrSub(), v8::internal::compiler::WasmGraphAssembler::IsNotNull(), v8::internal::compiler::WasmGraphAssembler::IsNull(), Load(), v8::internal::compiler::JSGraphAssembler::LoadElement(), v8::internal::compiler::JSGraphAssembler::LoadField(), LoadFramePointer(), v8::internal::compiler::WasmGraphAssembler::LoadFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadImmutable(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject(), LoadRootRegister(), LoadTrapOnNull(), LoadUnaligned(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), MergeState(), v8::internal::compiler::WasmGraphAssembler::Null(), Parameter(), Projection(), ProtectedLoad(), ProtectedStore(), Retain(), RuntimeAbort(), Store(), v8::internal::compiler::JSGraphAssembler::StoreElement(), v8::internal::compiler::JSGraphAssembler::StoreField(), v8::internal::compiler::WasmGraphAssembler::StoreToObject(), StoreTrapOnNull(), StoreUnaligned(), v8::internal::compiler::WasmGraphAssembler::StringAsWtf16(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::WasmGraphAssembler::StringPrepareForGetCodeunit(), v8::internal::compiler::WasmGraphAssembler::StructGet(), v8::internal::compiler::WasmGraphAssembler::StructSet(), TailCall(), v8::internal::compiler::JSGraphAssembler::TransitionAndStoreElement(), v8::internal::compiler::WasmGraphAssembler::TrapIf(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), TruncateFloat64ToInt64(), TypeGuard(), UniqueIntPtrConstant(), UnreachableWithoutConnectToEnd(), v8::internal::compiler::WasmGraphAssembler::WasmAnyConvertExtern(), v8::internal::compiler::WasmGraphAssembler::WasmExternConvertAny(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCast(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCastAbstract(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCheck(), and v8::internal::compiler::WasmGraphAssembler::WasmTypeCheckAbstract().
AddNode() [2/2]
template<typename T >
TNode<T> v8::internal::compiler::GraphAssembler::AddNode (Node * node) [inline]
Definition at line 535 of file graph-assembler.h.
                               {
    return TNode<T>::UncheckedCast(AddNode(node));
  }
References v8::internal::TNode< T >::UncheckedCast().
Bind()
template<size_t VarCount>
void v8::internal::compiler::GraphAssembler::Bind (GraphAssemblerLabel< VarCount > * label)
Definition at line 800 of file graph-assembler.h.
                                                              {
  DCHECK_NULL(control());
  DCHECK_NULL(effect());
  DCHECK_LT(0, label->merged_count_);
  DCHECK_EQ(label->loop_nesting_level_, loop_nesting_level_);
  control_ = label->control_;
  effect_ = label->effect_;
  label->SetBound();
  if (label->merged_count_ > 1 || label->IsLoop()) {
    AddNode(label->control_);
    AddNode(label->effect_);
    for (size_t i = 0; i < label->Count(); i++) {
      AddNode(label->bindings_[i]);
    }
  } else {
    // If the basic block does not have a control node, insert a dummy
    // Merge node, so that other passes have a control node to start from.
    control_ = AddNode(graph()->NewNode(common()->Merge(1), control()));
  }
}
References AddNode(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::bindings_, common(), control(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::control_, control_, v8::internal::compiler::GraphAssemblerLabel< VarCount >::Count(), DCHECK_EQ, DCHECK_LT, DCHECK_NULL, effect(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::effect_, effect_, graph(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsLoop(), v8::internal::compiler::GraphAssemblerLabel< VarCount >::loop_nesting_level_, loop_nesting_level_, v8::internal::compiler::GraphAssemblerLabel< VarCount >::merged_count_, and v8::internal::compiler::GraphAssemblerLabel< VarCount >::SetBound().
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::MaybeSkipHole(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), and v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value().
BitcastMaybeObjectToWord()
Node * v8::internal::compiler::GraphAssembler::BitcastMaybeObjectToWord (Node * value)
Definition at line 1229 of file graph-assembler.cc.
                                                          {
  return AddNode(graph()->NewNode(machine()->BitcastMaybeObjectToWord(), value,
                                  effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::value.
BitcastTaggedToWord()
Node * v8::internal::compiler::GraphAssembler::BitcastTaggedToWord (Node * value)
Definition at line 1219 of file graph-assembler.cc.
                                                     {
  return AddNode(graph()->NewNode(machine()->BitcastTaggedToWord(), value,
                                  effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::value.
Referenced by AdaptLocalArgument().
BitcastTaggedToWordForTagAndSmiBits()
Node * v8::internal::compiler::GraphAssembler::BitcastTaggedToWordForTagAndSmiBits (Node * value)
Definition at line 1224 of file graph-assembler.cc.
                                                                     {
  return AddNode(graph()->NewNode(
      machine()->BitcastTaggedToWordForTagAndSmiBits(), value));
}
References AddNode(), graph(), machine(), and v8::internal::value.
BitcastWordToTagged()
Node * v8::internal::compiler::GraphAssembler::BitcastWordToTagged (Node * value)
Definition at line 1214 of file graph-assembler.cc.
                                                     {
  return AddNode(graph()->NewNode(machine()->BitcastWordToTagged(), value,
                                  effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer().
BitcastWordToTaggedSigned()
Node * v8::internal::compiler::GraphAssembler::BitcastWordToTaggedSigned (Node * value)
Definition at line 1209 of file graph-assembler.cc.
                                                           {
  return AddNode(
      graph()->NewNode(machine()->BitcastWordToTaggedSigned(), value));
}
References AddNode(), graph(), machine(), and v8::internal::value.
Branch()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::Branch (Node * condition, detail::GraphAssemblerLabelForVars< Vars... > * if_true, detail::GraphAssemblerLabelForVars< Vars... > * if_false, Vars... vars)
Definition at line 825 of file graph-assembler.h.
                                                                       {
  BranchHint hint = BranchHint::kNone;
  if (if_true->IsDeferred() != if_false->IsDeferred()) {
    hint = if_false->IsDeferred() ? BranchHint::kTrue : BranchHint::kFalse;
  }
  BranchImpl(default_branch_semantics_, condition, if_true, if_false, hint,
             vars...);
}
References BranchImpl(), default_branch_semantics_, v8::internal::kFalse, v8::internal::kNone, and v8::internal::kTrue.
Referenced by BranchImpl(), GotoIf(), GotoIfNot(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt().
BranchImpl()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::BranchImpl (BranchSemantics semantics, Node * condition, GraphAssemblerLabel< sizeof...(Vars)> * if_true, GraphAssemblerLabel< sizeof...(Vars)> * if_false, BranchHint hint, Vars... vars) [private]
Definition at line 864 of file graph-assembler.h.
                                                               {
  DCHECK_NOT_NULL(control());
  Node* branch =
      graph()->NewNode(common()->Branch(hint, semantics), condition, control());
  control_ = graph()->NewNode(common()->IfTrue(), branch);
  MergeState(if_true, vars...);
  control_ = graph()->NewNode(common()->IfFalse(), branch);
  MergeState(if_false, vars...);
  control_ = nullptr;
  effect_ = nullptr;
}
References Branch(), common(), control(), control_, DCHECK_NOT_NULL, effect_, graph(), MergeState(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by Branch(), BranchWithCriticalSafetyCheck(), BranchWithHint(), JSBranch(), and MachineBranch().
BranchWithCriticalSafetyCheck()
void v8::internal::compiler::GraphAssembler::BranchWithCriticalSafetyCheck (Node * condition, GraphAssemblerLabel< 0u > * if_true, GraphAssemblerLabel< 0u > * if_false)
Definition at line 1279 of file graph-assembler.cc.
                                       {
  BranchHint hint = BranchHint::kNone;
  if (if_true->IsDeferred() != if_false->IsDeferred()) {
    hint = if_false->IsDeferred() ? BranchHint::kTrue : BranchHint::kFalse;
  }
  BranchImpl(default_branch_semantics_, condition, if_true, if_false, hint);
}
References BranchImpl(), default_branch_semantics_, v8::internal::compiler::GraphAssemblerLabel< VarCount >::IsDeferred(), v8::internal::kFalse, v8::internal::kNone, and v8::internal::kTrue.
BranchWithHint()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::BranchWithHint (Node * condition, detail::GraphAssemblerLabelForVars< Vars... > * if_true, detail::GraphAssemblerLabelForVars< Vars... > * if_false, BranchHint hint, Vars... vars)
Definition at line 838 of file graph-assembler.h.
                  {
  BranchImpl(default_branch_semantics_, condition, if_true, if_false, hint,
             vars...);
}
References BranchImpl(), and default_branch_semantics_.
Referenced by v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::MaybeSkipHole(), and v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value().
Call() [1/4]
TNode< Object > v8::internal::compiler::GraphAssembler::Call (const CallDescriptor * call_descriptor, int inputs_size, Node ** inputs)
Definition at line 1248 of file graph-assembler.cc.
                                                                   {
  return Call(common()->Call(call_descriptor), inputs_size, inputs);
}
References common().
Referenced by Call(), v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinImpl(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinThroughJumptable(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), and v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
Call() [2/4]
template<typename... Args>
TNode< Object > v8::internal::compiler::GraphAssembler::Call (const CallDescriptor * call_descriptor, Node * first_arg, Args... args)
Definition at line 938 of file graph-assembler.h.
                                                                  {
  const Operator* op = common()->Call(call_descriptor);
  return Call(op, first_arg, args...);
}
References v8::base::args, v8::internal::compiler::CommonOperatorBuilder::Call(), Call(), and common().
Call() [3/4]
TNode< Object > v8::internal::compiler::GraphAssembler::Call (const Operator * op, int inputs_size, Node ** inputs)
Definition at line 1253 of file graph-assembler.cc.
                                                  {
  DCHECK_EQ(IrOpcode::kCall, op->opcode());
  return AddNode<Object>(graph()->NewNode(op, inputs_size, inputs));
}
References DCHECK_EQ, graph(), and v8::internal::compiler::Operator::opcode().
Call() [4/4]
template<typename... Args>
TNode< Object > v8::internal::compiler::GraphAssembler::Call (const Operator * op, Node * first_arg, Args... args)
Definition at line 945 of file graph-assembler.h.
                                                 {
  Node* args_array[] = {first_arg, args..., effect(), control()};
  int size = static_cast<int>(1 + sizeof...(args)) + op->EffectInputCount() +
             op->ControlInputCount();
  return Call(op, size, args_array);
}
References v8::base::args, Call(), control(), v8::internal::compiler::Operator::ControlInputCount(), effect(), v8::internal::compiler::Operator::EffectInputCount(), and size().
ChangeUint32ToUintPtr()
TNode< UintPtrT > v8::internal::compiler::GraphAssembler::ChangeUint32ToUintPtr (SloppyTNode< Uint32T > value)
Definition at line 237 of file graph-assembler.cc.
                                {
  return kSystemPointerSize == 8
             ? TNode<UintPtrT>::UncheckedCast(ChangeUint32ToUint64(value))
             : TNode<UintPtrT>::UncheckedCast(value);
}
References v8::internal::kSystemPointerSize, v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind(), and v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
Checkpoint()
Node * v8::internal::compiler::GraphAssembler::Checkpoint (FrameState frame_state)
Definition at line 1081 of file graph-assembler.cc.
                                                       {
  return AddNode(graph()->NewNode(common()->Checkpoint(), frame_state, effect(),
                                  control()));
}
References AddNode(), common(), control(), effect(), and graph().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
common()
CommonOperatorBuilder* v8::internal::compiler::GraphAssembler::common () const [inline], [protected]
Definition at line 568 of file graph-assembler.h.
{ return mcgraph()->common(); }
Referenced by v8::internal::compiler::JSGraphAssembler::Assert(), Bind(), v8::internal::compiler::WasmGraphAssembler::Branch(), BranchImpl(), v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation(), Call(), v8::internal::compiler::JSGraphAssembler::Chained(), Checkpoint(), ConnectUnreachableToEnd(), DeoptimizeIf(), DeoptimizeIfNot(), v8::internal::compiler::JSCallReducerAssembler::EnterMachineGraph(), v8::internal::compiler::JSCallReducerAssembler::ExitMachineGraph(), GotoIf(), GotoIfNot(), v8::internal::compiler::WasmGraphAssembler::MergeControlToEnd(), MergeState(), v8::internal::compiler::WasmGraphAssembler::NumberConstant(), Parameter(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), Projection(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), Retain(), TailCall(), v8::internal::compiler::WasmGraphAssembler::TrapIf(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), TypeGuard(), UniqueIntPtrConstant(), and UnreachableWithoutConnectToEnd().
ConnectUnreachableToEnd()
void v8::internal::compiler::GraphAssembler::ConnectUnreachableToEnd ()
Definition at line 1294 of file graph-assembler.cc.
                                             {
  DCHECK_EQ(effect()->opcode(), IrOpcode::kUnreachable);
  Node* throw_node = graph()->NewNode(common()->Throw(), effect(), control());
  NodeProperties::MergeControlToEnd(graph(), common(), throw_node);
  if (node_changed_callback_.has_value()) {
    (*node_changed_callback_)(graph()->end());
  }
  effect_ = control_ = mcgraph()->Dead();
}
References common(), control(), control_, DCHECK_EQ, v8::internal::compiler::MachineGraph::Dead(), effect(), effect_, v8::internal::compiler::TFGraph::end(), graph(), v8::internal::wasm::kUnreachable, mcgraph(), v8::internal::compiler::NodeProperties::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), and node_changed_callback_.
Referenced by Unreachable().
control()
Control v8::internal::compiler::GraphAssembler::control () const [inline]
Definition at line 551 of file graph-assembler.h.
{ return Control(control_); }
Referenced by AddNode(), v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::WasmGraphAssembler::ArrayGet(), v8::internal::compiler::WasmGraphAssembler::ArrayInitializeLength(), v8::internal::compiler::WasmGraphAssembler::ArrayLength(), v8::internal::compiler::WasmGraphAssembler::ArraySet(), v8::internal::compiler::JSGraphAssembler::Assert(), v8::internal::compiler::WasmGraphAssembler::AssertNotNull(), Bind(), BitcastMaybeObjectToWord(), BitcastTaggedToWord(), BitcastWordToTagged(), v8::internal::compiler::WasmGraphAssembler::Branch(), BranchImpl(), v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation(), Call(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSGraphAssembler::Chained(), v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), v8::internal::compiler::JSGraphAssembler::CheckIf(), v8::internal::compiler::JSGraphAssembler::CheckNumber(), v8::internal::compiler::JSCallReducerAssembler::CheckNumber(), v8::internal::compiler::JSGraphAssembler::CheckNumberFitsInt32(), Checkpoint(), v8::internal::compiler::JSGraphAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckString(), v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), ConnectUnreachableToEnd(), v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateFunctionContext(), DebugBreak(), DeoptimizeIf(), DeoptimizeIfNot(), v8::internal::compiler::JSGraphAssembler::DetachContextCell(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMax(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMin(), Goto(), GotoIf(), GotoIfNot(), InitializeEffectControl(), v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject(), v8::internal::compiler::WasmGraphAssembler::IsNotNull(), v8::internal::compiler::WasmGraphAssembler::IsNull(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSGraphAssembler::JSCallRuntime2(), Load(), v8::internal::compiler::JSGraphAssembler::LoadElement(), v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::WasmGraphAssembler::LoadFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject(), LoadTrapOnNull(), LoadUnaligned(), v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), v8::internal::compiler::WasmGraphAssembler::MergeControlToEnd(), MergeState(), Projection(), ProtectedLoad(), ProtectedStore(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::JSNativeContextSpecialization::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::MemoryOptimizer::ReplaceUsesAndKillNode(), v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph(), v8::internal::compiler::JSCallReducerAssembler::SpeculativeToNumber(), Store(), v8::internal::compiler::JSGraphAssembler::StoreElement(), v8::internal::compiler::JSGraphAssembler::StoreField(), v8::internal::compiler::WasmGraphAssembler::StoreToObject(), StoreTrapOnNull(), StoreUnaligned(), v8::internal::compiler::WasmGraphAssembler::StringAsWtf16(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::WasmGraphAssembler::StringPrepareForGetCodeunit(), v8::internal::compiler::JSGraphAssembler::StringSubstring(), v8::internal::compiler::WasmGraphAssembler::StructGet(), v8::internal::compiler::WasmGraphAssembler::StructSet(), v8::internal::compiler::JSGraphAssembler::TransitionAndStoreElement(), v8::internal::compiler::WasmGraphAssembler::TrapIf(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), TypeGuard(), UnreachableWithoutConnectToEnd(), v8::internal::compiler::WasmGraphAssembler::WasmAnyConvertExtern(), v8::internal::compiler::WasmGraphAssembler::WasmExternConvertAny(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCast(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCastAbstract(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCheck(), and v8::internal::compiler::WasmGraphAssembler::WasmTypeCheckAbstract().
DebugBreak()
Node * v8::internal::compiler::GraphAssembler::DebugBreak ()
Definition at line 1086 of file graph-assembler.cc.
                                 {
  return AddNode(
      graph()->NewNode(machine()->DebugBreak(), effect(), control()));
}
References AddNode(), control(), effect(), graph(), and machine().
DeoptimizeIf()
Node * v8::internal::compiler::GraphAssembler::DeoptimizeIf (DeoptimizeReason reason, FeedbackSource const & feedback, Node * condition, Node * frame_state)
Definition at line 1234 of file graph-assembler.cc.
                                                                       {
  return AddNode(graph()->NewNode(common()->DeoptimizeIf(reason, feedback),
                                  condition, frame_state, effect(), control()));
}
References AddNode(), common(), control(), effect(), and graph().
DeoptimizeIfNot()
Node * v8::internal::compiler::GraphAssembler::DeoptimizeIfNot (DeoptimizeReason reason, FeedbackSource const & feedback, Node * condition, Node * frame_state)
Definition at line 1241 of file graph-assembler.cc.
                                                                          {
  return AddNode(graph()->NewNode(common()->DeoptimizeUnless(reason, feedback),
                                  condition, frame_state, effect(), control()));
}
References AddNode(), common(), control(), effect(), and graph().
effect()
Effect v8::internal::compiler::GraphAssembler::effect () const [inline]
Definition at line 552 of file graph-assembler.h.
{ return Effect(effect_); }
Referenced by AddNode(), v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::WasmGraphAssembler::ArrayGet(), v8::internal::compiler::WasmGraphAssembler::ArrayInitializeLength(), v8::internal::compiler::WasmGraphAssembler::ArrayLength(), v8::internal::compiler::WasmGraphAssembler::ArraySet(), v8::internal::compiler::JSGraphAssembler::Assert(), v8::internal::compiler::WasmGraphAssembler::AssertNotNull(), Bind(), BitcastMaybeObjectToWord(), BitcastTaggedToWord(), BitcastWordToTagged(), Call(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSGraphAssembler::Chained(), v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), v8::internal::compiler::JSGraphAssembler::CheckIf(), v8::internal::compiler::JSGraphAssembler::CheckNumber(), v8::internal::compiler::JSCallReducerAssembler::CheckNumber(), v8::internal::compiler::JSGraphAssembler::CheckNumberFitsInt32(), Checkpoint(), v8::internal::compiler::JSGraphAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckString(), v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), ConnectUnreachableToEnd(), v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateFunctionContext(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreatePromise(), DebugBreak(), DeoptimizeIf(), DeoptimizeIfNot(), v8::internal::compiler::JSGraphAssembler::DetachContextCell(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMax(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMin(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCallReducerAssembler(), Goto(), InitializeEffectControl(), v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSGraphAssembler::JSCallRuntime2(), Load(), v8::internal::compiler::JSGraphAssembler::LoadElement(), v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::WasmGraphAssembler::LoadFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject(), LoadTrapOnNull(), LoadUnaligned(), v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), MergeState(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumber(), ProtectedLoad(), ProtectedStore(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::JSNativeContextSpecialization::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::MemoryOptimizer::ReplaceUsesAndKillNode(), v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph(), Retain(), v8::internal::compiler::JSCallReducerAssembler::SpeculativeToNumber(), Store(), v8::internal::compiler::JSGraphAssembler::StoreElement(), v8::internal::compiler::JSGraphAssembler::StoreField(), v8::internal::compiler::WasmGraphAssembler::StoreToObject(), StoreTrapOnNull(), StoreUnaligned(), v8::internal::compiler::WasmGraphAssembler::StringAsWtf16(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::WasmGraphAssembler::StringPrepareForGetCodeunit(), v8::internal::compiler::JSGraphAssembler::StringSubstring(), v8::internal::compiler::WasmGraphAssembler::StructGet(), v8::internal::compiler::WasmGraphAssembler::StructSet(), v8::internal::compiler::JSGraphAssembler::TransitionAndStoreElement(), v8::internal::compiler::WasmGraphAssembler::TrapIf(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), TypeGuard(), UnreachableWithoutConnectToEnd(), v8::internal::compiler::WasmGraphAssembler::WasmAnyConvertExtern(), v8::internal::compiler::WasmGraphAssembler::WasmExternConvertAny(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCast(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCastAbstract(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCheck(), and v8::internal::compiler::WasmGraphAssembler::WasmTypeCheckAbstract().
ExternalConstant()
Node * v8::internal::compiler::GraphAssembler::ExternalConstant (ExternalReference ref)
Definition at line 122 of file graph-assembler.cc.
                                                            {
  return AddClonedNode(mcgraph()->ExternalConstant(ref));
}
References AddClonedNode(), and mcgraph().
Referenced by v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), IsolateField(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
Float64Constant()
Node * v8::internal::compiler::GraphAssembler::Float64Constant (double value)
Definition at line 103 of file graph-assembler.cc.
                                                  {
  return AddClonedNode(mcgraph()->Float64Constant(value));
}
References AddClonedNode(), mcgraph(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern().
Float64RoundDown()
Node * v8::internal::compiler::GraphAssembler::Float64RoundDown (Node * value)
Definition at line 280 of file graph-assembler.cc.
                                                  {
  CHECK(machine()->Float64RoundDown().IsSupported());
  return AddNode(graph()->NewNode(machine()->Float64RoundDown().op(), value));
}
References AddNode(), CHECK, graph(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), machine(), and v8::internal::value.
Float64RoundTruncate()
Node * v8::internal::compiler::GraphAssembler::Float64RoundTruncate (Node * value)
Definition at line 285 of file graph-assembler.cc.
                                                      {
  CHECK(machine()->Float64RoundTruncate().IsSupported());
  return AddNode(
      graph()->NewNode(machine()->Float64RoundTruncate().op(), value));
}
References AddNode(), CHECK, graph(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::IsSupported(), machine(), and v8::internal::value.
Goto()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::Goto (detail::GraphAssemblerLabelForVars< Vars... > * label, Vars... vars)
Definition at line 884 of file graph-assembler.h.
                                        {
  DCHECK_NOT_NULL(control());
  DCHECK_NOT_NULL(effect());
  MergeState(label, vars...);
  control_ = nullptr;
  effect_ = nullptr;
}
References control(), control_, DCHECK_NOT_NULL, effect(), effect_, and MergeState().
Referenced by v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), and v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value().
GotoIf() [1/2]
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::GotoIf (Node * condition, detail::GraphAssemblerLabelForVars< Vars... > * label, BranchHint hint, Vars... vars)
Definition at line 895 of file graph-assembler.h.
                                                           {
  Node* branch = graph()->NewNode(
      common()->Branch(hint, default_branch_semantics_), condition, control());
  control_ = graph()->NewNode(common()->IfTrue(), branch);
  MergeState(label, vars...);
  control_ = AddNode(graph()->NewNode(common()->IfFalse(), branch));
}
References AddNode(), Branch(), common(), control(), control_, default_branch_semantics_, graph(), MergeState(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), GotoIf(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
GotoIf() [2/2]
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::GotoIf (Node * condition, detail::GraphAssemblerLabelForVars< Vars... > * label, Vars... vars)
Definition at line 921 of file graph-assembler.h.
                                          {
  BranchHint hint =
      label->IsDeferred() ? BranchHint::kFalse : BranchHint::kNone;
  return GotoIf(condition, label, hint, vars...);
}
References GotoIf(), v8::internal::kFalse, and v8::internal::kNone.
GotoIfNot() [1/2]
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::GotoIfNot (Node * condition, detail::GraphAssemblerLabelForVars< Vars... > * label, BranchHint hint, Vars... vars)
Definition at line 908 of file graph-assembler.h.
                                   {
  Node* branch = graph()->NewNode(
      common()->Branch(hint, default_branch_semantics_), condition, control());
  control_ = graph()->NewNode(common()->IfFalse(), branch);
  MergeState(label, vars...);
  control_ = AddNode(graph()->NewNode(common()->IfTrue(), branch));
}
References AddNode(), Branch(), common(), control(), control_, default_branch_semantics_, graph(), MergeState(), and v8::internal::compiler::TFGraph::NewNode().
Referenced by GotoIfNot(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck().
GotoIfNot() [2/2]
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::GotoIfNot (Node * condition, detail::GraphAssemblerLabelForVars< Vars... > * label, Vars... vars)
Definition at line 930 of file graph-assembler.h.
                  {
  BranchHint hint = label->IsDeferred() ? BranchHint::kTrue : BranchHint::kNone;
  return GotoIfNot(condition, label, hint, vars...);
}
References GotoIfNot(), v8::internal::kNone, and v8::internal::kTrue.
graph()
TFGraph* v8::internal::compiler::GraphAssembler::graph () const [inline], [protected]
Definition at line 566 of file graph-assembler.h.
{ return mcgraph_->graph(); }
Referenced by v8::internal::compiler::JSGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::ArrayGet(), v8::internal::compiler::WasmGraphAssembler::ArrayInitializeLength(), v8::internal::compiler::WasmGraphAssembler::ArrayLength(), v8::internal::compiler::WasmGraphAssembler::ArraySet(), v8::internal::compiler::JSGraphAssembler::Assert(), v8::internal::compiler::WasmGraphAssembler::AssertNotNull(), Bind(), BitcastMaybeObjectToWord(), BitcastTaggedToWord(), BitcastTaggedToWordForTagAndSmiBits(), BitcastWordToTagged(), BitcastWordToTaggedSigned(), v8::internal::compiler::JSGraphAssembler::BooleanNot(), v8::internal::compiler::WasmGraphAssembler::Branch(), BranchImpl(), v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation(), Call(), v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSGraphAssembler::Chained(), v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), v8::internal::compiler::JSGraphAssembler::CheckIf(), v8::internal::compiler::JSGraphAssembler::CheckNumber(), v8::internal::compiler::JSCallReducerAssembler::CheckNumber(), v8::internal::compiler::JSGraphAssembler::CheckNumberFitsInt32(), Checkpoint(), v8::internal::compiler::JSGraphAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckString(), v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), ConnectUnreachableToEnd(), v8::internal::compiler::JSCallReducerAssembler::ConvertHoleToUndefined(), v8::internal::compiler::JSGraphAssembler::ConvertTaggedHoleToUndefined(), v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateFunctionContext(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreatePromise(), DebugBreak(), DeoptimizeIf(), DeoptimizeIfNot(), v8::internal::compiler::JSGraphAssembler::DetachContextCell(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMax(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMin(), v8::internal::compiler::JSCallReducerAssembler::EnterMachineGraph(), v8::internal::compiler::JSCallReducerAssembler::ExitMachineGraph(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCall(), Float64RoundDown(), Float64RoundTruncate(), GotoIf(), GotoIfNot(), v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject(), IntPtrAdd(), IntPtrSub(), v8::internal::compiler::WasmGraphAssembler::IsNotNull(), v8::internal::compiler::WasmGraphAssembler::IsNull(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), v8::internal::compiler::JSGraphAssembler::JSCallRuntime2(), Load(), v8::internal::compiler::JSGraphAssembler::LoadElement(), v8::internal::compiler::JSGraphAssembler::LoadField(), LoadFramePointer(), v8::internal::compiler::WasmGraphAssembler::LoadFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadImmutable(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject(), LoadRootRegister(), LoadTrapOnNull(), LoadUnaligned(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements(), v8::internal::compiler::WasmGraphAssembler::MergeControlToEnd(), MergeState(), v8::internal::compiler::WasmGraphAssembler::Null(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberBitwiseAnd(), v8::internal::compiler::JSGraphAssembler::NumberBitwiseOr(), v8::internal::compiler::WasmGraphAssembler::NumberConstant(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSGraphAssembler::NumberIsFloat64Hole(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberLessThanOrEqual(), v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), v8::internal::compiler::JSGraphAssembler::NumberShiftRightLogical(), v8::internal::compiler::JSGraphAssembler::NumberSubtract(), v8::internal::compiler::JSGraphAssembler::ObjectIsCallable(), v8::internal::compiler::JSGraphAssembler::ObjectIsSmi(), v8::internal::compiler::JSGraphAssembler::ObjectIsUndetectable(), Parameter(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumber(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), Projection(), ProtectedLoad(), ProtectedStore(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceMathBinary(), v8::internal::compiler::JSCallReducerAssembler::ReduceMathUnary(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSGraphAssembler::ReferenceEqual(), Retain(), RuntimeAbort(), v8::internal::compiler::JSCallReducerAssembler::SpeculativeToNumber(), StackSlot(), Store(), v8::internal::compiler::JSGraphAssembler::StoreElement(), v8::internal::compiler::JSGraphAssembler::StoreField(), v8::internal::compiler::WasmGraphAssembler::StoreToObject(), StoreTrapOnNull(), StoreUnaligned(), v8::internal::compiler::WasmGraphAssembler::StringAsWtf16(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringFromSingleCharCode(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::WasmGraphAssembler::StringPrepareForGetCodeunit(), v8::internal::compiler::JSGraphAssembler::StringSubstring(), v8::internal::compiler::WasmGraphAssembler::StructGet(), v8::internal::compiler::WasmGraphAssembler::StructSet(), TailCall(), v8::internal::compiler::JSGraphAssembler::ToBoolean(), v8::internal::compiler::JSGraphAssembler::TransitionAndStoreElement(), v8::internal::compiler::WasmGraphAssembler::TrapIf(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), TruncateFloat64ToInt64(), TypeGuard(), UniqueIntPtrConstant(), UnreachableWithoutConnectToEnd(), v8::internal::compiler::WasmGraphAssembler::WasmAnyConvertExtern(), v8::internal::compiler::WasmGraphAssembler::WasmExternConvertAny(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCast(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCastAbstract(), v8::internal::compiler::WasmGraphAssembler::WasmTypeCheck(), and v8::internal::compiler::WasmGraphAssembler::WasmTypeCheckAbstract().
HasActiveBlock()
bool v8::internal::compiler::GraphAssembler::HasActiveBlock () const [inline]
Definition at line 513 of file graph-assembler.h.
                              {
    // This is false if the current block has been terminated (e.g. by a Goto or
    // Unreachable). In that case, a new label must be bound before we can
    // continue emitting nodes.
    return control() != nullptr;
  }
InitializeEffectControl()
void v8::internal::compiler::GraphAssembler::InitializeEffectControl (Node * effect, Node * control)
Definition at line 1346 of file graph-assembler.cc.
                                                                        {
  effect_ = effect;
  control_ = control;
}
References control(), control_, effect(), and effect_.
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCallReducerAssembler(), v8::internal::compiler::SelectLowering::LowerSelect(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayEvery(), v8::internal::compiler::JSCallReducer::ReduceArrayFilter(), v8::internal::compiler::JSCallReducer::ReduceArrayFind(), v8::internal::compiler::JSCallReducer::ReduceArrayFindIndex(), v8::internal::compiler::JSCallReducer::ReduceArrayForEach(), v8::internal::compiler::JSCallReducer::ReduceArrayIncludes(), v8::internal::compiler::JSCallReducer::ReduceArrayIndexOf(), v8::internal::compiler::JSCallReducer::ReduceArrayMap(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducer::ReduceArrayReduce(), v8::internal::compiler::JSCallReducer::ReduceArrayReduceRight(), v8::internal::compiler::JSCallReducer::ReduceArraySome(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), TailCall(), and Unreachable().
Int32Constant()
Node * v8::internal::compiler::GraphAssembler::Int32Constant (int32_t value)
Definition at line 75 of file graph-assembler.cc.
                                                 {
  return AddClonedNode(mcgraph()->Int32Constant(value));
}
References AddClonedNode(), mcgraph(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::Allocate(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer(), v8::internal::compiler::WasmGraphAssembler::BuildSmiShiftBitsConstant32(), v8::internal::compiler::WasmGraphAssembler::HasInstanceType(), v8::internal::compiler::WasmGraphAssembler::IsDataRefMap(), v8::internal::compiler::WasmGraphAssembler::IsSmi(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::WasmGCLowering::ReduceIsNotNull(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGraphAssembler::SmiConstant(), and UniqueIntPtrConstant().
Int64Constant()
Node * v8::internal::compiler::GraphAssembler::Int64Constant (int64_t value)
Definition at line 83 of file graph-assembler.cc.
                                                 {
  return AddClonedNode(mcgraph()->Int64Constant(value));
}
References AddClonedNode(), mcgraph(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGraphAssembler::SmiConstant(), and UniqueIntPtrConstant().
IntPtrAdd()
Node * v8::internal::compiler::GraphAssembler::IntPtrAdd (Node * a, Node * b)
Definition at line 1193 of file graph-assembler.cc.
                                                {
  return AddNode(graph()->NewNode(
      machine()->Is64() ? machine()->Int64Add() : machine()->Int32Add(), a, b));
}
References AddNode(), graph(), Is64(), and machine().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
IntPtrConstant()
Node * v8::internal::compiler::GraphAssembler::IntPtrConstant (intptr_t value)
Definition at line 67 of file graph-assembler.cc.
                                                   {
  return AddClonedNode(mcgraph()->IntPtrConstant(value));
}
References AddClonedNode(), mcgraph(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer(), v8::internal::compiler::WasmGraphAssembler::BuildSmiShiftBitsConstant(), v8::internal::compiler::WasmGraphAssembler::FieldOffset(), v8::internal::compiler::WasmGraphAssembler::InitializeImmutableInObject(), v8::internal::compiler::WasmGraphAssembler::IsSmi(), Load(), v8::internal::compiler::WasmGraphAssembler::LoadByteArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadFixedArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadFromObject(), LoadHeapNumberValue(), v8::internal::compiler::WasmGraphAssembler::LoadImmutable(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFixedArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadImmutableTrustedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadProtectedFixedArrayElement(), v8::internal::compiler::WasmGraphAssembler::LoadProtectedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObject(), v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObjectTrapOnNull(), v8::internal::compiler::WasmGraphAssembler::LoadWeakFixedArrayElement(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), Store(), v8::internal::compiler::WasmGraphAssembler::StoreToObject(), and v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset().
IntPtrEqual()
Node * v8::internal::compiler::GraphAssembler::IntPtrEqual (Node * left, Node * right)
Definition at line 252 of file graph-assembler.cc.
                                                         {
  return WordEqual(left, right);
}
IntPtrSub()
Node * v8::internal::compiler::GraphAssembler::IntPtrSub (Node * a, Node * b)
Definition at line 1198 of file graph-assembler.cc.
                                                {
  return AddNode(graph()->NewNode(
      machine()->Is64() ? machine()->Int64Sub() : machine()->Int32Sub(), a, b));
}
References AddNode(), graph(), Is64(), and machine().
Is64()
constexpr bool v8::internal::compiler::GraphAssembler::Is64 () const [inline], [constexpr], [protected]
Definition at line 557 of file graph-assembler.h.
{ return kSystemPointerSize == 8; }
References v8::internal::kSystemPointerSize.
Referenced by IntPtrAdd(), IntPtrSub(), and UniqueIntPtrConstant().
IsolateField()
Node * v8::internal::compiler::GraphAssembler::IsolateField (IsolateFieldId id)
Definition at line 126 of file graph-assembler.cc.
                                                    {
  return ExternalConstant(ExternalReference::Create(id));
}
References v8::internal::ExternalReference::Create(), and ExternalConstant().
JSBranch()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::JSBranch (TNode< Boolean > condition, GraphAssemblerLabel< sizeof...(Vars)> * if_true, GraphAssemblerLabel< sizeof...(Vars)> * if_false, BranchHint hint, Vars... vars)
Definition at line 856 of file graph-assembler.h.
                                                             {
  BranchImpl(BranchSemantics::kJS, condition, if_true, if_false, hint, vars...);
}
References BranchImpl(), and v8::internal::compiler::kJS.
Load() [1/2]
Node * v8::internal::compiler::GraphAssembler::Load (MachineType type, Node * object, int offset)
Definition at line 1140 of file graph-assembler.cc.
                                                                     {
  return Load(type, object, IntPtrConstant(offset));
}
References IntPtrConstant(), Load(), and v8::internal::tracing::type.
Load() [2/2]
Node * v8::internal::compiler::GraphAssembler::Load (MachineType type, Node * object, Node * offset)
Definition at line 1135 of file graph-assembler.cc.
                                                                       {
  return AddNode(graph()->NewNode(machine()->Load(type), object, offset,
                                  effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer(), Load(), LoadHeapNumberValue(), LoadMap(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind(), and v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope().
LoadFramePointer()
Node * v8::internal::compiler::GraphAssembler::LoadFramePointer ()
Definition at line 139 of file graph-assembler.cc.
                                       {
  return AddNode(graph()->NewNode(machine()->LoadFramePointer()));
}
References AddNode(), graph(), and machine().
LoadHeapNumberValue()
Node * v8::internal::compiler::GraphAssembler::LoadHeapNumberValue (Node * heap_number)
Definition at line 158 of file graph-assembler.cc.
                                                           {
  return Load(MachineType::Float64(), heap_number,
              IntPtrConstant(offsetof(HeapNumber, value_) - kHeapObjectTag));
}
References v8::internal::MachineType::Float64(), IntPtrConstant(), v8::internal::kHeapObjectTag, and Load().
LoadMap()
TNode< Map > v8::internal::compiler::GraphAssembler::LoadMap (Node * object)
Definition at line 362 of file graph-assembler.cc.
                                               {
  Node* map_word = Load(MachineType::TaggedPointer(), object,
                        HeapObject::kMapOffset - kHeapObjectTag);
#ifdef V8_MAP_PACKING
  return UnpackMapWord(map_word);
#else
  return TNode<Map>::UncheckedCast(map_word);
#endif
}
References v8::internal::kHeapObjectTag, v8::internal::HeapObject::kMapOffset, Load(), v8::internal::MachineType::TaggedPointer(), and v8::internal::TNode< T >::UncheckedCast().
LoadRootRegister()
Node * v8::internal::compiler::GraphAssembler::LoadRootRegister ()
Definition at line 143 of file graph-assembler.cc.
                                       {
  return AddNode(graph()->NewNode(machine()->LoadRootRegister()));
}
References AddNode(), graph(), and machine().
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeTrustedPointer(), v8::internal::compiler::WasmGCLowering::Null(), and v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
LoadTrapOnNull()
Node * v8::internal::compiler::GraphAssembler::LoadTrapOnNull (MachineType type, Node * object, Node * offset)
Definition at line 1177 of file graph-assembler.cc.
                                                   {
  return AddNode(graph()->NewNode(machine()->LoadTrapOnNull(type), object,
                                  offset, effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::WasmGraphAssembler::LoadTrustedPointerFromObjectTrapOnNull(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), and v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet().
LoadUnaligned()
Node * v8::internal::compiler::GraphAssembler::LoadUnaligned (MachineType type, Node * object, Node * offset)
Definition at line 1155 of file graph-assembler.cc.
                                                  {
  Operator const* const op =
      (type.representation() == MachineRepresentation::kWord8 ||
       machine()->UnalignedLoadSupported(type.representation()))
          ? machine()->Load(type)
          : machine()->UnalignedLoad(type);
  return AddNode(graph()->NewNode(op, object, offset, effect(), control()));
}
References AddNode(), control(), effect(), graph(), v8::internal::kWord8, v8::internal::compiler::MachineOperatorBuilder::Load(), machine(), v8::internal::tracing::type, v8::internal::compiler::MachineOperatorBuilder::UnalignedLoad(), and v8::internal::compiler::MachineOperatorBuilder::UnalignedLoadSupported().
machine()
MachineOperatorBuilder* v8::internal::compiler::GraphAssembler::machine () const [inline], [protected]
Definition at line 569 of file graph-assembler.h.
{ return mcgraph()->machine(); }
Referenced by BitcastMaybeObjectToWord(), BitcastTaggedToWord(), BitcastTaggedToWordForTagAndSmiBits(), BitcastWordToTagged(), BitcastWordToTaggedSigned(), v8::internal::compiler::WasmGraphAssembler::BuildChangeUint32ToUintPtr(), DebugBreak(), Float64RoundDown(), Float64RoundTruncate(), IntPtrAdd(), IntPtrSub(), Load(), LoadFramePointer(), v8::internal::compiler::WasmGraphAssembler::LoadImmutable(), LoadRootRegister(), LoadTrapOnNull(), LoadUnaligned(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), ProtectedLoad(), ProtectedStore(), StackSlot(), Store(), StoreTrapOnNull(), StoreUnaligned(), TruncateFloat64ToInt64(), and UniqueIntPtrConstant().
MachineBranch()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::MachineBranch (TNode< Word32T > condition, GraphAssemblerLabel< sizeof...(Vars)> * if_true, GraphAssemblerLabel< sizeof...(Vars)> * if_false, BranchHint hint, Vars... vars)
Definition at line 847 of file graph-assembler.h.
                  {
  BranchImpl(BranchSemantics::kMachine, condition, if_true, if_false, hint,
             vars...);
}
References BranchImpl(), and v8::internal::compiler::kMachine.
MakeDeferredLabel()
template<typename... Reps>
detail::GraphAssemblerLabelForReps<Reps...> v8::internal::compiler::GraphAssembler::MakeDeferredLabel (Reps... reps) [inline]
Definition at line 322 of file graph-assembler.h.
                                                                            {
    return MakeLabelFor(GraphAssemblerLabelType::kDeferred, reps...);
  }
References v8::internal::compiler::kDeferred.
Referenced by v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value().
MakeLabel()
template<typename... Reps>
detail::GraphAssemblerLabelForReps<Reps...> v8::internal::compiler::GraphAssembler::MakeLabel (Reps... reps) [inline]
Definition at line 310 of file graph-assembler.h.
                                                                    {
    return MakeLabelFor(GraphAssemblerLabelType::kNonDeferred, reps...);
  }
References v8::internal::compiler::kNonDeferred.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::MaybeSkipHole(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
MakeLabelFor() [1/2]
GraphAssemblerDynamicLabel v8::internal::compiler::GraphAssembler::MakeLabelFor (GraphAssemblerLabelType type, base::SmallVector< MachineRepresentation, 4 > reps) [inline]
Definition at line 301 of file graph-assembler.h.
                                                      {
    return GraphAssemblerDynamicLabel(type, loop_nesting_level_,
                                      std::move(reps));
  }
References v8::internal::tracing::type.
MakeLabelFor() [2/2]
template<typename... Reps>
detail::GraphAssemblerLabelForReps<Reps...> v8::internal::compiler::GraphAssembler::MakeLabelFor (GraphAssemblerLabelType type, Reps... reps) [inline]
Definition at line 295 of file graph-assembler.h.
                                                  {
    std::array<MachineRepresentation, sizeof...(Reps)> reps_array = {reps...};
    return detail::GraphAssemblerLabelForReps<Reps...>(
        type, loop_nesting_level_, std::move(reps_array));
  }
References v8::internal::tracing::type.
MakeLoopLabel()
template<typename... Reps>
detail::GraphAssemblerLabelForReps<Reps...> v8::internal::compiler::GraphAssembler::MakeLoopLabel (Reps... reps) [inline]
Definition at line 316 of file graph-assembler.h.
                                                                        {
    return MakeLabelFor(GraphAssemblerLabelType::kLoop, reps...);
  }
References v8::internal::compiler::kLoop.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit().
mcgraph()
MachineGraph* v8::internal::compiler::GraphAssembler::mcgraph () const [inline], [protected]
Definition at line 565 of file graph-assembler.h.
{ return mcgraph_; }
Referenced by v8::internal::compiler::WasmGraphAssembler::Branch(), v8::internal::compiler::WasmGraphAssembler::BuildChangeInt32ToIntPtr(), v8::internal::compiler::WasmGraphAssembler::BuildChangeIntPtrToInt64(), v8::internal::compiler::WasmGraphAssembler::BuildChangeUint32ToUintPtr(), v8::internal::compiler::WasmGraphAssembler::BuildConvertUint32ToSmiWithSaturation(), v8::internal::compiler::WasmGraphAssembler::BuildTruncateIntPtrToInt32(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinThroughJumptable(), ConnectUnreachableToEnd(), ExternalConstant(), Float64Constant(), Int32Constant(), Int64Constant(), IntPtrConstant(), v8::internal::compiler::WasmGraphAssembler::LoadImmutable(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), v8::internal::compiler::WasmGraphAssembler::NumberConstant(), v8::internal::compiler::WasmGraphAssembler::TrapIf(), v8::internal::compiler::WasmGraphAssembler::TrapUnless(), Uint32Constant(), Uint64Constant(), UintPtrConstant(), and v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset().
MergeState()
template<typename... Vars>
void v8::internal::compiler::GraphAssembler::MergeState (detail::GraphAssemblerLabelForVars< Vars... > * label, Vars... vars) [protected]
Definition at line 686 of file graph-assembler.h.
                                                                    {
  using NodeArray = typename detail::GraphAssemblerLabelForVars<
      Vars...>::template Array<Node*>;
  RestoreEffectControlScope restore_effect_control_scope(this);
  const int merged_count = static_cast<int>(label->merged_count_);
  const size_t var_count = label->Count();
  NodeArray var_array{vars...};
  const bool is_loop_exit = label->loop_nesting_level_ != loop_nesting_level_;
  if (is_loop_exit) {
    // This feature may only be used if it has been enabled.
    USE(mark_loop_exits_);
    DCHECK(mark_loop_exits_);
    // Jumping from loops to loops not supported.
    DCHECK(!label->IsLoop());
    // Currently only the simple case of jumping one level is supported.
    DCHECK_EQ(label->loop_nesting_level_, loop_nesting_level_ - 1);
    DCHECK(!loop_headers_.empty());
    DCHECK_NOT_NULL(*loop_headers_.back());
    // Mark this exit to enable loop peeling.
    AddNode(graph()->NewNode(common()->LoopExit(), control(),
                             *loop_headers_.back()));
    AddNode(graph()->NewNode(common()->LoopExitEffect(), effect(), control()));
    for (size_t i = 0; i < var_count; i++) {
      var_array[i] = AddNode(graph()->NewNode(
          common()->LoopExitValue(MachineRepresentation::kTagged), var_array[i],
          control()));
    }
  }
  if (label->IsLoop()) {
    if (merged_count == 0) {
      DCHECK(!label->IsBound());
      label->control_ =
          graph()->NewNode(common()->Loop(2), control(), control());
      label->effect_ = graph()->NewNode(common()->EffectPhi(2), effect(),
                                        effect(), label->control_);
      Node* terminate = graph()->NewNode(common()->Terminate(), label->effect_,
                                         label->control_);
      NodeProperties::MergeControlToEnd(graph(), common(), terminate);
      for (size_t i = 0; i < var_count; i++) {
        label->bindings_[i] =
            graph()->NewNode(common()->Phi(label->representations_[i], 2),
                             var_array[i], var_array[i], label->control_);
      }
    } else {
      DCHECK(label->IsBound());
      DCHECK_EQ(1, merged_count);
      label->control_->ReplaceInput(1, control());
      label->effect_->ReplaceInput(1, effect());
      for (size_t i = 0; i < var_count; i++) {
        label->bindings_[i]->ReplaceInput(1, var_array[i]);
        CHECK(!NodeProperties::IsTyped(var_array[i])); // Unsupported.
      }
    }
  } else {
    DCHECK(!label->IsLoop());
    DCHECK(!label->IsBound());
    if (merged_count == 0) {
      // Just set the control, effect and variables directly.
      label->control_ = control();
      label->effect_ = effect();
      for (size_t i = 0; i < var_count; i++) {
        label->bindings_[i] = var_array[i];
      }
    } else if (merged_count == 1) {
      // Create merge, effect phi and a phi for each variable.
      label->control_ =
          graph()->NewNode(common()->Merge(2), label->control_, control());
      label->effect_ = graph()->NewNode(common()->EffectPhi(2), label->effect_,
                                        effect(), label->control_);
      for (size_t i = 0; i < var_count; i++) {
        label->bindings_[i] = graph()->NewNode(
            common()->Phi(label->representations_[i], 2), label->bindings_[i],
            var_array[i], label->control_);
      }
    } else {
      // Append to the merge, effect phi and phis.
      DCHECK_EQ(IrOpcode::kMerge, label->control_->opcode());
      label->control_->AppendInput(graph()->zone(), control());
      NodeProperties::ChangeOp(label->control_,
                               common()->Merge(merged_count + 1));
      DCHECK_EQ(IrOpcode::kEffectPhi, label->effect_->opcode());
      label->effect_->ReplaceInput(merged_count, effect());
      label->effect_->AppendInput(graph()->zone(), label->control_);
      NodeProperties::ChangeOp(label->effect_,
                               common()->EffectPhi(merged_count + 1));
      for (size_t i = 0; i < var_count; i++) {
        DCHECK_EQ(IrOpcode::kPhi, label->bindings_[i]->opcode());
        label->bindings_[i]->ReplaceInput(merged_count, var_array[i]);
        label->bindings_[i]->AppendInput(graph()->zone(), label->control_);
        NodeProperties::ChangeOp(
            label->bindings_[i],
            common()->Phi(label->representations_[i], merged_count + 1));
        if (NodeProperties::IsTyped(label->bindings_[i])) {
          CHECK(NodeProperties::IsTyped(var_array[i]));
          Type old_type = NodeProperties::GetType(label->bindings_[i]);
          Type new_type = Type::Union(
              old_type, NodeProperties::GetType(var_array[i]), graph()->zone());
          NodeProperties::SetType(label->bindings_[i], new_type);
        }
      }
    }
  }
  label->merged_count_++;
}
References AddNode(), v8::internal::compiler::NodeProperties::ChangeOp(), CHECK, common(), control(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, effect(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::kTagged, loop_headers_, loop_nesting_level_, mark_loop_exits_, v8::internal::compiler::NodeProperties::MergeControlToEnd(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::Terminate(), v8::internal::compiler::Type::Union(), and USE.
Referenced by BranchImpl(), Goto(), GotoIf(), and GotoIfNot().
Parameter()
Node * v8::internal::compiler::GraphAssembler::Parameter (int index)
Definition at line 130 of file graph-assembler.cc.
                                         {
  return AddNode(
      graph()->NewNode(common()->Parameter(index), graph()->start()));
}
References AddNode(), common(), graph(), v8::internal::index, and start().
Projection()
Node * v8::internal::compiler::GraphAssembler::Projection (int index, Node * value, Node * ctrl = nullptr)
Definition at line 296 of file graph-assembler.cc.
                                                                   {
  return AddNode(graph()->NewNode(common()->Projection(index), value,
                                  ctrl ? ctrl : control()));
}
References AddNode(), common(), control(), graph(), v8::internal::index, and v8::internal::value.
ProtectedLoad()
Node * v8::internal::compiler::GraphAssembler::ProtectedLoad (MachineType type, Node * object, Node * offset)
Definition at line 1171 of file graph-assembler.cc.
                                                  {
  return AddNode(graph()->NewNode(machine()->ProtectedLoad(type), object,
                                  offset, effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::tracing::type.
ProtectedStore()
Node * v8::internal::compiler::GraphAssembler::ProtectedStore (MachineRepresentation rep, Node * object, Node * offset, Node * value)
Definition at line 1165 of file graph-assembler.cc.
                                                                {
  return AddNode(graph()->NewNode(machine()->ProtectedStore(rep), object,
                                  offset, value, effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::value.
Reset()
void v8::internal::compiler::GraphAssembler::Reset ()
Definition at line 1341 of file graph-assembler.cc.
                           {
  effect_ = nullptr;
  control_ = nullptr;
}
References control_, and effect_.
Referenced by v8::internal::compiler::SelectLowering::LowerSelect().
Retain()
Node * v8::internal::compiler::GraphAssembler::Retain (Node * buffer)
Definition at line 1189 of file graph-assembler.cc.
                                         {
  return AddNode(graph()->NewNode(common()->Retain(), buffer, effect()));
}
References AddNode(), common(), effect(), and graph().
RuntimeAbort()
void v8::internal::compiler::GraphAssembler::RuntimeAbort (AbortReason reason)
Definition at line 1290 of file graph-assembler.cc.
                                                    {
  AddNode(graph()->NewNode(simplified()->RuntimeAbort(reason)));
}
References AddNode(), graph(), and simplified().
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer().
simplified()
virtual SimplifiedOperatorBuilder* v8::internal::compiler::GraphAssembler::simplified () [inline], [virtual]
Reimplemented in v8::internal::compiler::WasmGraphAssembler, and v8::internal::compiler::JSGraphAssembler.
Definition at line 288 of file graph-assembler.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Referenced by RuntimeAbort().
SmiLessThan()
Node * v8::internal::compiler::GraphAssembler::SmiLessThan (Node * left, Node * right)
Definition at line 272 of file graph-assembler.cc.
                                                         {
  if (COMPRESS_POINTERS_BOOL) {
    return Int32LessThan(left, right);
  } else {
    return IntLessThan(left, right);
  }
}
References COMPRESS_POINTERS_BOOL.
SmiSub()
Node * v8::internal::compiler::GraphAssembler::SmiSub (Node * left, Node * right)
Definition at line 264 of file graph-assembler.cc.
                                                    {
  if (COMPRESS_POINTERS_BOOL) {
    return BitcastWord32ToWord64(Int32Sub(left, right));
  } else {
    return IntSub(left, right);
  }
}
References COMPRESS_POINTERS_BOOL.
StackSlot()
TNode< RawPtrT > v8::internal::compiler::GraphAssembler::StackSlot (int size, int alignment, bool is_tagged = false)
Definition at line 1103 of file graph-assembler.cc.
                                                         {
  return AddNode<RawPtrT>(
      graph()->NewNode(machine()->StackSlot(size, alignment, is_tagged)));
}
References graph(), machine(), and size().
Referenced by AdaptLocalArgument().
start()
Node* v8::internal::compiler::GraphAssembler::start () const [inline]
Definition at line 554 of file graph-assembler.h.
{ return graph()->start(); }
References graph().
Referenced by Parameter(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring().
Store() [1/2]
Node * v8::internal::compiler::GraphAssembler::Store (StoreRepresentation rep, Node * object, int offset, Node * value)
Definition at line 1130 of file graph-assembler.cc.
                                         {
  return Store(rep, object, IntPtrConstant(offset), value);
}
References IntPtrConstant(), Store(), and v8::internal::value.
Store() [2/2]
Node * v8::internal::compiler::GraphAssembler::Store (StoreRepresentation rep, Node * object, Node * offset, Node * value)
Definition at line 1124 of file graph-assembler.cc.
                                         {
  return AddNode(graph()->NewNode(machine()->Store(rep), object, offset, value,
                                  effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::value.
Referenced by AdaptLocalArgument(), and Store().
StoreTrapOnNull()
Node * v8::internal::compiler::GraphAssembler::StoreTrapOnNull (StoreRepresentation rep, Node * object, Node * offset, Node * value)
Definition at line 1183 of file graph-assembler.cc.
                                                                 {
  return AddNode(graph()->NewNode(machine()->StoreTrapOnNull(rep), object,
                                  offset, value, effect(), control()));
}
References AddNode(), control(), effect(), graph(), machine(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet().
StoreUnaligned()
Node * v8::internal::compiler::GraphAssembler::StoreUnaligned (MachineRepresentation rep, Node * object, Node * offset, Node * value)
Definition at line 1144 of file graph-assembler.cc.
                                                                {
  Operator const* const op =
      (rep == MachineRepresentation::kWord8 ||
       machine()->UnalignedStoreSupported(rep))
          ? machine()->Store(StoreRepresentation(rep, kNoWriteBarrier))
          : machine()->UnalignedStore(rep);
  return AddNode(
      graph()->NewNode(op, object, offset, value, effect(), control()));
}
References AddNode(), control(), effect(), graph(), v8::internal::compiler::kNoWriteBarrier, v8::internal::kWord8, machine(), v8::internal::compiler::MachineOperatorBuilder::Store(), v8::internal::compiler::MachineOperatorBuilder::UnalignedStore(), v8::internal::compiler::MachineOperatorBuilder::UnalignedStoreSupported(), and v8::internal::value.
TaggedEqual()
Node * v8::internal::compiler::GraphAssembler::TaggedEqual (Node * left, Node * right)
Definition at line 256 of file graph-assembler.cc.
                                                         {
  if (COMPRESS_POINTERS_BOOL) {
    return Word32Equal(left, right);
  } else {
    return WordEqual(left, right);
  }
}
References COMPRESS_POINTERS_BOOL, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::WasmGCLowering::IsNull(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck().
TailCall()
void v8::internal::compiler::GraphAssembler::TailCall (const CallDescriptor * call_descriptor, int inputs_size, Node ** inputs)
Definition at line 1259 of file graph-assembler.cc.
                                                              {
#ifdef DEBUG
  static constexpr int kTargetEffectControl = 3;
  DCHECK_EQ(inputs_size,
            call_descriptor->ParameterCount() + kTargetEffectControl);
#endif // DEBUG
  Node* node = AddNode(graph()->NewNode(common()->TailCall(call_descriptor),
                                        inputs_size, inputs));
  // Unlike ConnectUnreachableToEnd, the TailCall node terminates a block; to
  // keep it live, it *must* be connected to End (also in Turboprop schedules).
  NodeProperties::MergeControlToEnd(graph(), common(), node);
  // Setting effect, control to nullptr effectively terminates the current block
  // by disallowing the addition of new nodes until a new label has been bound.
  InitializeEffectControl(nullptr, nullptr);
}
References AddNode(), common(), DCHECK_EQ, graph(), InitializeEffectControl(), v8::internal::compiler::NodeProperties::MergeControlToEnd(), and v8::internal::compiler::CallDescriptor::ParameterCount().
temp_zone()
Zone* v8::internal::compiler::GraphAssembler::temp_zone () const [inline], [protected]
Definition at line 567 of file graph-assembler.h.
{ return temp_zone_; }
Referenced by v8::internal::compiler::WasmGraphAssembler::CallBuiltinImpl(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinThroughJumptable(), and v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch().
TruncateFloat64ToInt64()
Node * v8::internal::compiler::GraphAssembler::TruncateFloat64ToInt64 (Node * value, TruncateKind kind)
Definition at line 291 of file graph-assembler.cc.
                                                                           {
  return AddNode(
      graph()->NewNode(machine()->TruncateFloat64ToInt64(kind), value));
}
References AddNode(), graph(), machine(), and v8::internal::value.
TypeGuard() [1/2]
Node * v8::internal::compiler::GraphAssembler::TypeGuard (Type type, Node * value)
Definition at line 1076 of file graph-assembler.cc.
                                                      {
  return AddNode(
      graph()->NewNode(common()->TypeGuard(type), value, effect(), control()));
}
References AddNode(), common(), control(), effect(), graph(), v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardFixedArrayLength(), v8::internal::compiler::JSCallReducerAssembler::TypeGuardNonInternal(), and v8::internal::compiler::JSCallReducerAssembler::TypeGuardUnsignedSmall().
TypeGuard() [2/2]
template<typename T >
TNode<T> v8::internal::compiler::GraphAssembler::TypeGuard (Type type, TNode< T > value) [inline]
Definition at line 404 of file graph-assembler.h.
                                                {
    return TNode<T>::UncheckedCast(TypeGuard(type, static_cast<Node*>(value)));
  }
References v8::internal::tracing::type, v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Uint32Constant()
TNode< Uint32T > v8::internal::compiler::GraphAssembler::Uint32Constant (uint32_t value)
Definition at line 79 of file graph-assembler.cc.
                                                            {
  return TNode<Uint32T>::UncheckedCast(mcgraph()->Uint32Constant(value));
}
References mcgraph(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::JSGraphAssembler::ArrayBufferDetachedBit(), v8::internal::compiler::JSGraphAssembler::CheckIfTypedArrayWasDetachedOrOutOfBounds(), v8::internal::compiler::JSGraphAssembler::LoadElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind(), v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), and v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract().
Uint64Constant()
Node * v8::internal::compiler::GraphAssembler::Uint64Constant (uint64_t value)
Definition at line 87 of file graph-assembler.cc.
                                                   {
  return AddClonedNode(mcgraph()->Uint64Constant(value));
}
References AddClonedNode(), mcgraph(), and v8::internal::value.
UintPtrAdd()
TNode< UintPtrT > v8::internal::compiler::GraphAssembler::UintPtrAdd (TNode< UintPtrT > left, TNode< UintPtrT > right)
Definition at line 217 of file graph-assembler.cc.
                                                                  {
  return kSystemPointerSize == 8
             ? TNode<UintPtrT>::UncheckedCast(Int64Add(left, right))
             : TNode<UintPtrT>::UncheckedCast(Int32Add(left, right));
}
References v8::internal::kSystemPointerSize, and v8::internal::TNode< T >::UncheckedCast().
UintPtrConstant()
TNode< UintPtrT > v8::internal::compiler::GraphAssembler::UintPtrConstant (uintptr_t value)
Definition at line 71 of file graph-assembler.cc.
                                                               {
  return TNode<UintPtrT>::UncheckedCast(mcgraph()->UintPtrConstant(value));
}
References mcgraph(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildDecodeSandboxedExternalPointer(), v8::internal::compiler::WasmGCLowering::IsNull(), v8::internal::compiler::WasmGraphAssembler::LoadWasmCodePointer(), and v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
UintPtrDiv()
TNode< UintPtrT > v8::internal::compiler::GraphAssembler::UintPtrDiv (TNode< UintPtrT > left, TNode< UintPtrT > right)
Definition at line 230 of file graph-assembler.cc.
                                                                  {
  return kSystemPointerSize == 8
             ? TNode<UintPtrT>::UncheckedCast(Uint64Div(left, right))
             : TNode<UintPtrT>::UncheckedCast(Uint32Div(left, right));
}
References v8::internal::kSystemPointerSize, and v8::internal::TNode< T >::UncheckedCast().
UintPtrLessThan()
TNode< BoolT > v8::internal::compiler::GraphAssembler::UintPtrLessThan (TNode< UintPtrT > left, TNode< UintPtrT > right)
Definition at line 199 of file graph-assembler.cc.
                                                                    {
  return kSystemPointerSize == 8
             ? Uint64LessThan(TNode<Uint64T>::UncheckedCast(left),
                              TNode<Uint64T>::UncheckedCast(right))
             : Uint32LessThan(TNode<Uint32T>::UncheckedCast(left),
                              TNode<Uint32T>::UncheckedCast(right));
}
References v8::internal::kSystemPointerSize.
UintPtrLessThanOrEqual()
TNode< BoolT > v8::internal::compiler::GraphAssembler::UintPtrLessThanOrEqual (TNode< UintPtrT > left, TNode< UintPtrT > right)
Definition at line 208 of file graph-assembler.cc.
                                                                           {
  return kSystemPointerSize == 8
             ? Uint64LessThanOrEqual(TNode<Uint64T>::UncheckedCast(left),
                                     TNode<Uint64T>::UncheckedCast(right))
             : Uint32LessThanOrEqual(TNode<Uint32T>::UncheckedCast(left),
                                     TNode<Uint32T>::UncheckedCast(right));
}
References v8::internal::kSystemPointerSize.
UintPtrSub()
TNode< UintPtrT > v8::internal::compiler::GraphAssembler::UintPtrSub (TNode< UintPtrT > left, TNode< UintPtrT > right)
Definition at line 223 of file graph-assembler.cc.
                                                                  {
  return kSystemPointerSize == 8
             ? TNode<UintPtrT>::UncheckedCast(Int64Sub(left, right))
             : TNode<UintPtrT>::UncheckedCast(Int32Sub(left, right));
}
References v8::internal::kSystemPointerSize, and v8::internal::TNode< T >::UncheckedCast().
UniqueIntPtrConstant()
Node * v8::internal::compiler::GraphAssembler::UniqueIntPtrConstant (intptr_t value)
Definition at line 91 of file graph-assembler.cc.
                                                         {
  return AddNode(graph()->NewNode(
      machine()->Is64()
          ? common()->Int64Constant(value)
          : common()->Int32Constant(static_cast<int32_t>(value))));
}
References AddNode(), common(), graph(), Int32Constant(), Int64Constant(), Is64(), machine(), and v8::internal::value.
Unreachable()
Node * v8::internal::compiler::GraphAssembler::Unreachable ()
Definition at line 1091 of file graph-assembler.cc.
                                  {
  Node* result = UnreachableWithoutConnectToEnd();
  ConnectUnreachableToEnd();
  InitializeEffectControl(nullptr, nullptr);
  return result;
}
References ConnectUnreachableToEnd(), InitializeEffectControl(), v8::base::internal::result, and UnreachableWithoutConnectToEnd().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable(), and UnreachableWithoutConnectToEnd().
UnreachableWithoutConnectToEnd()
Node * v8::internal::compiler::GraphAssembler::UnreachableWithoutConnectToEnd ()
Definition at line 1098 of file graph-assembler.cc.
                                                     {
  return AddNode(
      graph()->NewNode(common()->Unreachable(), effect(), control()));
}
References AddNode(), common(), control(), effect(), graph(), and Unreachable().
Referenced by Unreachable().
UpdateEffectControlWith()
void v8::internal::compiler::GraphAssembler::UpdateEffectControlWith (Node * node) [inline]
Definition at line 521 of file graph-assembler.h.
                                                     {
    if (node->op()->EffectOutputCount() > 0) {
      effect_ = node;
    }
    if (node->op()->ControlOutputCount() > 0) {
      control_ = node;
    }
  }
References v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::compiler::Operator::EffectOutputCount(), and v8::internal::compiler::Node::op().
Referenced by AddClonedNode(), and AddNode().
Member Data Documentation
control_
Node* v8::internal::compiler::GraphAssembler::control_ [private]
Definition at line 657 of file graph-assembler.h.
Referenced by Bind(), BranchImpl(), ConnectUnreachableToEnd(), Goto(), GotoIf(), GotoIfNot(), InitializeEffectControl(), and Reset().
default_branch_semantics_
BranchSemantics v8::internal::compiler::GraphAssembler::default_branch_semantics_ [private]
Definition at line 655 of file graph-assembler.h.
Referenced by Branch(), BranchWithCriticalSafetyCheck(), BranchWithHint(), GotoIf(), GotoIfNot(), and GraphAssembler().
effect_
Node* v8::internal::compiler::GraphAssembler::effect_ [private]
Definition at line 656 of file graph-assembler.h.
Referenced by Bind(), BranchImpl(), ConnectUnreachableToEnd(), Goto(), InitializeEffectControl(), and Reset().
inline_reducers_
ZoneVector<Reducer*> v8::internal::compiler::GraphAssembler::inline_reducers_ [private]
Definition at line 664 of file graph-assembler.h.
Referenced by AddNode().
inline_reductions_blocked_
bool v8::internal::compiler::GraphAssembler::inline_reductions_blocked_ [private]
Definition at line 665 of file graph-assembler.h.
Referenced by AddNode().
loop_headers_
ZoneVector<Node**> v8::internal::compiler::GraphAssembler::loop_headers_ [private]
Definition at line 671 of file graph-assembler.h.
Referenced by v8::internal::compiler::GraphAssembler::LoopScope< Reps >::LoopScope(), and MergeState().
loop_nesting_level_
int v8::internal::compiler::GraphAssembler::loop_nesting_level_ = 0 [private]
Definition at line 670 of file graph-assembler.h.
Referenced by Bind(), v8::internal::compiler::GraphAssembler::LoopScope< Reps >::LoopScopeInternal::LoopScopeInternal(), MergeState(), and ~GraphAssembler().
mark_loop_exits_
const bool v8::internal::compiler::GraphAssembler::mark_loop_exits_ [private]
Definition at line 675 of file graph-assembler.h.
Referenced by MergeState().
mcgraph_
MachineGraph* v8::internal::compiler::GraphAssembler::mcgraph_ [private]
Definition at line 654 of file graph-assembler.h.
node_changed_callback_
std::optional<NodeChangedCallback> v8::internal::compiler::GraphAssembler::node_changed_callback_ [private]
Definition at line 660 of file graph-assembler.h.
Referenced by ConnectUnreachableToEnd().
temp_zone_
Zone* v8::internal::compiler::GraphAssembler::temp_zone_ [private]
Definition at line 653 of file graph-assembler.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/graph-assembler.h
/mnt/V8SourceCode/src/compiler/graph-assembler.cc