v8::internal::maglev::TestTypeOf Class Reference
#include <maglev-ir.h>
Public Member Functions
TestTypeOf (uint64_t bitfield, interpreter::TestTypeOfFlags::LiteralFlag literal)
Input & value ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
interpreter::TestTypeOfFlags::LiteralFlag literal () const
Static Public Attributes
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, TestTypeOf >
Private Attributes
interpreter::TestTypeOfFlags::LiteralFlag literal_
Additional Inherited Members
Detailed Description
Definition at line 5092 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::TestTypeOf::Base = FixedInputValueNodeT<1, TestTypeOf> [private]
Definition at line 5093 of file maglev-ir.h.
Constructor & Destructor Documentation
TestTypeOf()
v8::internal::maglev::TestTypeOf::TestTypeOf (uint64_t bitfield, interpreter::TestTypeOfFlags::LiteralFlag literal) [inline], [explicit]
Definition at line 5096 of file maglev-ir.h.
      : Base(bitfield), literal_(literal) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::TestTypeOf::GenerateCode (MaglevAssembler * , const ProcessingState &)
literal()
interpreter::TestTypeOfFlags::LiteralFlag v8::internal::maglev::TestTypeOf::literal () const [inline]
Definition at line 5111 of file maglev-ir.h.
{ return literal_; }
References literal_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::TestTypeOf::options () const [inline]
Definition at line 5109 of file maglev-ir.h.
{ return std::tuple{literal_}; }
References literal_.
PrintParams()
void v8::internal::maglev::TestTypeOf::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8428 of file maglev-ir.cc.
                                                                        {
  os << "(" << interpreter::TestTypeOfFlags::ToString(literal_) << ")";
}
References literal_, and v8::internal::interpreter::TestTypeOfFlags::ToString().
SetValueLocationConstraints()
void v8::internal::maglev::TestTypeOf::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::TestTypeOf::value () [inline]
Definition at line 5103 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::TestTypeOf::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 5101 of file maglev-ir.h.
literal_
interpreter::TestTypeOfFlags::LiteralFlag v8::internal::maglev::TestTypeOf::literal_ [private]
Definition at line 5114 of file maglev-ir.h.
Referenced by literal(), options(), and PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc