v8::internal::TransitionsAccessor Class Reference
#include <transitions.h>
Public Types
using TraverseCallback = std::function< void(Tagged< Map >)>
Public Member Functions
TransitionsAccessor (Isolate *isolate, Tagged< Map > map, bool concurrent_access=false)
Tagged< Map > SearchTransition (Tagged< Name > name, PropertyKind kind, PropertyAttributes attributes)
Tagged< Map > SearchSpecial (Tagged< Symbol > name)
MaybeHandle< Map > FindTransitionToField (DirectHandle< String > name)
void ForEachTransitionTo (Tagged< Name > name, const ForEachTransitionCallback &callback, DisallowGarbageCollection *no_gc)
template<typename Char >
bool IsExpectedTransition (Tagged< Name > transition_name, Tagged< Map > transition_target, base::Vector< const Char > key_chars)
template<typename Char >
std::pair< Handle< String >, Handle< Map > > ExpectedTransition (base::Vector< const Char > key_chars)
template<typename Callback , typename ProtoCallback , typename SideStepCallback >
void ForEachTransition (DisallowGarbageCollection *no_gc, Callback callback, ProtoCallback proto_transition_callback, SideStepCallback side_step_transition_callback)
template<typename Callback , typename ProtoCallback , typename SideStepCallback , bool with_key = true>
void ForEachTransitionWithKey (DisallowGarbageCollection *no_gc, Callback callback, ProtoCallback proto_transition_callback, SideStepCallback side_step_transition_callback)
int NumberOfTransitions ()
Tagged< Name > GetKey (int transition_number)
Tagged< Map > GetTarget (int transition_number)
bool HasIntegrityLevelTransitionTo (Tagged< Map > to, Tagged< Symbol > *out_symbol=nullptr, PropertyAttributes *out_integrity_level=nullptr)
void TraverseTransitionTree (const TraverseCallback &callback)
bool HasPrototypeTransitions ()
Tagged< Map > GetMigrationTarget ()
bool HasSideStepTransitions ()
Tagged< Object > GetSideStepTransition (SideStepTransition::Kind i)
void SetSideStepTransition (SideStepTransition::Kind i, Tagged< Object > target)
Static Public Member Functions
static void Insert (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Map > target, TransitionKindFlag flag)
static void InsertNoneSentinel (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name)
static MaybeHandle< Map > SearchTransition (Isolate *isolate, DirectHandle< Map > map, Tagged< Name > name, PropertyKind kind, PropertyAttributes attributes)
static MaybeHandle< Map > SearchSpecial (Isolate *isolate, DirectHandle< Map > map, Tagged< Symbol > name)
static bool IsSpecialTransition (ReadOnlyRoots roots, Tagged< Name > name)
static PropertyDetails GetTargetDetails (Tagged< Name > name, Tagged< Map > target)
static bool CanHaveMoreTransitions (Isolate *isolate, DirectHandle< Map > map)
static bool IsMatchingMap (Tagged< Map > target, Tagged< Name > name, PropertyKind kind, PropertyAttributes attributes)
static bool PutPrototypeTransition (Isolate *isolate, DirectHandle< Map >, DirectHandle< Object > prototype, DirectHandle< Map > target_map)
static std::optional< Tagged< Map > > GetPrototypeTransition (Isolate *isolate, Tagged< Map > map, Tagged< Object > prototype)
static void SetMigrationTarget (Isolate *isolate, DirectHandle< Map > map, Tagged< Map > migration_target)
static void EnsureHasSideStepTransitions (Isolate *isolate, DirectHandle< Map > map)
Static Public Attributes
static const int kMaxNumberOfTransitions = 1024 + 512
Protected Types
enum Encoding {
kPrototypeInfo
, kUninitialized
, kMigrationTarget
, kWeakRef
,
kFullTransitionArray
 }
Protected Member Functions
Encoding encoding ()
int Capacity ()
Tagged< TransitionArray > transitions ()
Private Member Functions
PropertyDetails GetSimpleTargetDetails (Tagged< Map > transition)
bool HasSimpleTransitionTo (Tagged< Map > map)
Tagged< Map > GetTargetMapFromWeakRef ()
void TraverseTransitionTreeInternal (const TraverseCallback &callback, DisallowGarbageCollection *no_gc)
DISALLOW_IMPLICIT_CONSTRUCTORS (TransitionsAccessor)
Static Private Member Functions
static Encoding GetEncoding (Isolate *isolate, Tagged< MaybeObject > raw_transitions)
static Encoding GetEncoding (Isolate *isolate, Tagged< TransitionArray > array)
static Encoding GetEncoding (Isolate *isolate, DirectHandle< Map > map)
static Tagged< TransitionArray > GetTransitionArray (Isolate *isolate, Tagged< MaybeObject > raw_transitions)
static Tagged< TransitionArray > GetTransitionArray (Isolate *isolate, DirectHandle< Map > map)
static Tagged< Map > GetSimpleTransition (Isolate *isolate, DirectHandle< Map > map)
static Tagged< Name > GetSimpleTransitionKey (Tagged< Map > transition)
static Tagged< Map > GetTargetFromRaw (Tagged< MaybeObject > raw)
static void EnsureHasFullTransitionArray (Isolate *isolate, DirectHandle< Map > map)
static void SetPrototypeTransitions (Isolate *isolate, DirectHandle< Map > map, DirectHandle< WeakFixedArray > proto_transitions)
static Tagged< WeakFixedArray > GetPrototypeTransitions (Isolate *isolate, Tagged< Map > map)
static void InsertHelper (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Map > target, TransitionKindFlag flag)
static void ReplaceTransitions (Isolate *isolate, DirectHandle< Map > map, Tagged< UnionOf< TransitionArray, MaybeWeak< Map >>> new_transitions)
static void ReplaceTransitions (Isolate *isolate, DirectHandle< Map > map, DirectHandle< TransitionArray > new_transitions)
Private Attributes
Isolate * isolate_
Tagged< Map > map_
Tagged< MaybeObject > raw_transitions_
Encoding encoding_
bool concurrent_access_
Friends
class MarkCompactCollector
class TransitionArray
Detailed Description
Definition at line 75 of file transitions.h.
Member Typedef Documentation
TraverseCallback
using v8::internal::TransitionsAccessor::TraverseCallback = std::function<void(Tagged<Map>)>
Definition at line 169 of file transitions.h.
Member Enumeration Documentation
Encoding
enum v8::internal::TransitionsAccessor::Encoding [protected]
Enumerator
kPrototypeInfo
kUninitialized
kMigrationTarget
kWeakRef
kFullTransitionArray
Definition at line 230 of file transitions.h.
                {
    kPrototypeInfo,
    kUninitialized,
    kMigrationTarget,
    kWeakRef,
    kFullTransitionArray,
  };
Constructor & Destructor Documentation
TransitionsAccessor()
v8::internal::TransitionsAccessor::TransitionsAccessor (Isolate * isolate, Tagged< Map > map, bool concurrent_access = false) [inline]
Definition at line 342 of file transitions-inl.h.
    : isolate_(isolate),
      map_(map),
      raw_transitions_(map->raw_transitions(isolate_, kAcquireLoad)),
      encoding_(GetEncoding(isolate_, raw_transitions_)),
      concurrent_access_(concurrent_access) {
  DCHECK_IMPLIES(encoding_ == kMigrationTarget, map_->is_deprecated());
}
References DCHECK_IMPLIES, encoding_, kMigrationTarget, and map_.
Referenced by SearchSpecial(), and SearchTransition().
Member Function Documentation
CanHaveMoreTransitions()
bool v8::internal::TransitionsAccessor::CanHaveMoreTransitions (Isolate * isolate, DirectHandle< Map > map) [static]
Definition at line 316 of file transitions.cc.
                                                                        {
  if (map->is_dictionary_map()) return false;
  Tagged<MaybeObject> raw_transitions =
      map->raw_transitions(isolate, kAcquireLoad);
  if (GetEncoding(isolate, raw_transitions) == kFullTransitionArray) {
    return GetTransitionArray(isolate, raw_transitions)
               ->number_of_transitions() < kMaxNumberOfTransitions;
  }
  return true;
}
References GetEncoding(), GetTransitionArray(), v8::kAcquireLoad, kFullTransitionArray, kMaxNumberOfTransitions, and v8::internal::raw_transitions.
Referenced by v8::internal::Map::AsLanguageMode(), v8::internal::MapUpdater::ConstructNewMap(), v8::internal::MapUpdater::ConstructNewMapWithIntegrityLevelTransition(), v8::internal::Map::CopyAddDescriptor(), v8::internal::Map::CopyAsElementsKind(), v8::internal::Map::CopyReplaceDescriptors(), v8::internal::JSObject::PreventExtensionsWithTransition(), and v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue().
Capacity()
int v8::internal::TransitionsAccessor::Capacity () [inline], [protected]
Definition at line 352 of file transitions-inl.h.
{ return transitions()->Capacity(); }
References transitions().
Referenced by InsertHelper().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::TransitionsAccessor::DISALLOW_IMPLICIT_CONSTRUCTORS (TransitionsAccessor) [private]
encoding()
Encoding v8::internal::TransitionsAccessor::encoding () [inline], [protected]
Definition at line 238 of file transitions.h.
{ return encoding_; }
Referenced by EnsureHasFullTransitionArray(), ExpectedTransition(), ForEachTransitionTo(), ForEachTransitionWithKey(), GetKey(), GetMigrationTarget(), GetTarget(), HasPrototypeTransitions(), HasSideStepTransitions(), HasSimpleTransitionTo(), InsertHelper(), NumberOfTransitions(), SearchSpecial(), SearchTransition(), and TraverseTransitionTreeInternal().
EnsureHasFullTransitionArray()
void v8::internal::TransitionsAccessor::EnsureHasFullTransitionArray (Isolate * isolate, DirectHandle< Map > map) [static], [private]
Definition at line 581 of file transitions.cc.
                                                                              {
  Encoding encoding =
      GetEncoding(isolate, map->raw_transitions(isolate, kAcquireLoad));
  if (encoding == kFullTransitionArray) return;
  int nof =
      (encoding == kUninitialized || encoding == kMigrationTarget) ? 0 : 1;
  DirectHandle<TransitionArray> result =
      isolate->factory()->NewTransitionArray(nof);
  // Reload encoding after possible GC.
  encoding = GetEncoding(isolate, map->raw_transitions(isolate, kAcquireLoad));
  if (nof == 1) {
    if (encoding == kUninitialized) {
      // If allocation caused GC and cleared the target, trim the new array.
      result->SetNumberOfTransitions(0);
    } else {
      // Otherwise populate the new array.
      Tagged<Map> target = GetSimpleTransition(isolate, map);
      Tagged<Name> key = GetSimpleTransitionKey(target);
      result->Set(0, key, MakeWeak(target));
    }
  }
  ReplaceTransitions(isolate, map, result);
}
References encoding(), v8::internal::Isolate::factory(), GetEncoding(), GetSimpleTransition(), GetSimpleTransitionKey(), v8::kAcquireLoad, v8::internal::key, kFullTransitionArray, kMigrationTarget, kUninitialized, v8::internal::MakeWeak(), v8::internal::Factory::NewTransitionArray(), ReplaceTransitions(), and v8::base::internal::result.
Referenced by EnsureHasSideStepTransitions(), and SetPrototypeTransitions().
EnsureHasSideStepTransitions()
void v8::internal::TransitionsAccessor::EnsureHasSideStepTransitions (Isolate * isolate, DirectHandle< Map > map) [static]
Definition at line 845 of file transitions.cc.
                                                                              {
  EnsureHasFullTransitionArray(isolate, map);
  Tagged<TransitionArray> transitions =
      GetTransitionArray(isolate, map->raw_transitions());
  if (transitions->HasSideStepTransitions()) return;
  TransitionArray::CreateSideStepTransitions(
      isolate, direct_handle(transitions, isolate));
}
References v8::internal::TransitionArray::CreateSideStepTransitions(), v8::internal::direct_handle(), EnsureHasFullTransitionArray(), GetTransitionArray(), and transitions().
Referenced by v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMap(), and v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMapUnsupported().
ExpectedTransition()
template<typename Char >
std::pair< Handle< String >, Handle< Map > > v8::internal::TransitionsAccessor::ExpectedTransition (base::Vector< const Char > key_chars) [inline]
Definition at line 486 of file transitions-inl.h.
                                      {
  DisallowGarbageCollection no_gc;
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      return {Handle<String>::null(), Handle<Map>::null()};
    case kWeakRef: {
      Tagged<Map> target =
          Cast<Map>(raw_transitions_.GetHeapObjectAssumeWeak());
      Tagged<Name> name = GetSimpleTransitionKey(target);
      if (IsExpectedTransition(name, target, key_chars)) {
        return {handle(Cast<String>(name), isolate_), handle(target, isolate_)};
      }
      return {Handle<String>::null(), Handle<Map>::null()};
    }
    case kFullTransitionArray: {
      Tagged<TransitionArray> array =
          Cast<TransitionArray>(raw_transitions_.GetHeapObjectAssumeStrong());
      int entries = array->number_of_transitions();
      // Do linear search for small entries.
      const int kMaxEntriesForLinearSearch = 8;
      if (entries > kMaxEntriesForLinearSearch)
        return {Handle<String>::null(), Handle<Map>::null()};
      for (int i = entries - 1; i >= 0; i--) {
        Tagged<Name> name = array->GetKey(i);
        Tagged<Map> target = array->GetTarget(i);
        if (IsExpectedTransition(name, target, key_chars)) {
          return {handle(Cast<String>(name), isolate_),
                  handle(GetTarget(i), isolate_)};
        }
      }
      return {Handle<String>::null(), Handle<Map>::null()};
    }
  }
  UNREACHABLE();
}
References encoding(), GetSimpleTransitionKey(), GetTarget(), v8::internal::handle(), IsExpectedTransition(), isolate_, kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Handle< T >::null(), raw_transitions_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::JSDataObjectBuilder::TryFastTransitionToPropertyKey().
FindTransitionToField()
MaybeHandle< Map > v8::internal::TransitionsAccessor::FindTransitionToField (DirectHandle< String > name)
Definition at line 270 of file transitions.cc.
                               {
  DCHECK(IsInternalizedString(*name));
  DisallowGarbageCollection no_gc;
  Tagged<Map> target = SearchTransition(*name, PropertyKind::kData, NONE);
  if (target.is_null()) return MaybeHandle<Map>();
#ifdef DEBUG
  PropertyDetails details = target->GetLastDescriptorDetails(isolate_);
  DCHECK_EQ(NONE, details.attributes());
  DCHECK_EQ(PropertyKind::kData, details.kind());
  DCHECK_EQ(PropertyLocation::kField, details.location());
#endif
  return Handle<Map>(target, isolate_);
}
References v8::internal::PropertyDetails::attributes(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::InstanceTypeChecker::IsInternalizedString(), isolate_, v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, and SearchTransition().
Referenced by v8::internal::ValueDeserializer::ReadJSObjectProperties(), and v8::internal::JSDataObjectBuilder::TryFastTransitionToPropertyKey().
ForEachTransition()
template<typename Callback , typename ProtoCallback , typename SideStepCallback >
void v8::internal::TransitionsAccessor::ForEachTransition (DisallowGarbageCollection * no_gc, Callback callback, ProtoCallback proto_transition_callback, SideStepCallback side_step_transition_callback) [inline]
Definition at line 134 of file transitions.h.
                                                                         {
    ForEachTransitionWithKey<Callback, ProtoCallback, SideStepCallback, false>(
        no_gc, callback, proto_transition_callback,
        side_step_transition_callback);
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Map::DeprecateTransitionTree(), and v8::internal::MapUpdater::UpdateFieldType().
ForEachTransitionTo()
void v8::internal::TransitionsAccessor::ForEachTransitionTo (Tagged< Name > name, const ForEachTransitionCallback & callback, DisallowGarbageCollection * no_gc)
Definition at line 285 of file transitions.cc.
                                      {
  DCHECK(IsUniqueName(name));
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      return;
    case kWeakRef: {
      Tagged<Map> target =
          Cast<Map>(raw_transitions_.GetHeapObjectAssumeWeak());
      InternalIndex descriptor = target->LastAdded();
      Tagged<DescriptorArray> descriptors =
          target->instance_descriptors(kRelaxedLoad);
      Tagged<Name> key = descriptors->GetKey(descriptor);
      if (key == name) {
        callback(target);
      }
      return;
    }
    case kFullTransitionArray: {
      base::MutexGuardIf guard(isolate_->full_transition_array_access(),
                               concurrent_access_);
      return transitions()->ForEachTransitionTo(name, callback);
    }
  }
  UNREACHABLE();
}
References concurrent_access_, v8::internal::DCHECK(), encoding(), v8::internal::Isolate::full_transition_array_access(), isolate_, v8::internal::IsUniqueName(), v8::internal::key, kFullTransitionArray, kMigrationTarget, kPrototypeInfo, v8::kRelaxedLoad, kUninitialized, kWeakRef, v8::internal::name, raw_transitions_, transitions(), and v8::internal::UNREACHABLE().
ForEachTransitionWithKey()
template<typename Callback , typename ProtoCallback , typename SideStepCallback , bool with_key>
void v8::internal::TransitionsAccessor::ForEachTransitionWithKey (DisallowGarbageCollection * no_gc, Callback callback, ProtoCallback proto_transition_callback, SideStepCallback side_step_transition_callback)
Definition at line 527 of file transitions-inl.h.
                                                    {
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      return;
    case kWeakRef: {
      Tagged<Map> target =
          Cast<Map>(raw_transitions_.GetHeapObjectAssumeWeak());
      if constexpr (with_key) {
        callback(GetSimpleTransitionKey(target), target);
      } else {
        callback(target);
      }
      return;
    }
    case kFullTransitionArray: {
      base::MutexGuardIf scope(isolate_->full_transition_array_access(),
                               concurrent_access_);
      Tagged<TransitionArray> transition_array = transitions();
      int num_transitions = transition_array->number_of_transitions();
      ReadOnlyRoots roots(isolate_);
      for (int i = 0; i < num_transitions; ++i) {
        if constexpr (with_key) {
          Tagged<Name> key = transition_array->GetKey(i);
          callback(key, GetTarget(i));
        } else {
          callback(GetTarget(i));
        }
      }
      if constexpr (!std::is_same_v<ProtoCallback, std::nullptr_t>) {
        if (transitions()->HasPrototypeTransitions()) {
          Tagged<WeakFixedArray> cache =
              transitions()->GetPrototypeTransitions();
          int length = TransitionArray::NumberOfPrototypeTransitions(cache);
          for (int i = 0; i < length; i++) {
            Tagged<MaybeObject> target =
                cache->get(TransitionArray::kProtoTransitionHeaderSize + i);
            Tagged<HeapObject> heap_object;
            if (target.GetHeapObjectIfWeak(&heap_object)) {
              proto_transition_callback(Cast<Map>(heap_object));
            }
          }
        }
      }
      if constexpr (!std::is_same_v<SideStepCallback, std::nullptr_t>) {
        if (transitions()->HasSideStepTransitions()) {
          Tagged<WeakFixedArray> cache =
              transitions()->GetSideStepTransitions();
          for (uint32_t i = SideStepTransition::kFirstMapIdx;
               i <= SideStepTransition::kLastMapIdx; i++) {
            Tagged<MaybeObject> target = cache->get(i);
            if (target.IsWeak() || target == SideStepTransition::Unreachable) {
              if constexpr (with_key) {
                side_step_transition_callback(
                    static_cast<SideStepTransition::Kind>(i),
                    target.GetHeapObjectOrSmi());
              } else {
                side_step_transition_callback(target.GetHeapObjectOrSmi());
              }
            }
          }
        }
      }
      return;
    }
  }
  UNREACHABLE();
}
References concurrent_access_, encoding(), v8::internal::Isolate::full_transition_array_access(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectOrSmi(), GetSimpleTransitionKey(), GetTarget(), HasPrototypeTransitions(), HasSideStepTransitions(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::key, v8::internal::SideStepTransition::kFirstMapIdx, kFullTransitionArray, v8::internal::SideStepTransition::kLastMapIdx, kMigrationTarget, v8::internal::TransitionArray::kProtoTransitionHeaderSize, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::length, v8::internal::TransitionArray::NumberOfPrototypeTransitions(), raw_transitions_, transitions(), v8::internal::UNREACHABLE(), and v8::internal::SideStepTransition::Unreachable.
GetEncoding() [1/3]
TransitionsAccessor::Encoding v8::internal::TransitionsAccessor::GetEncoding (Isolate * isolate, DirectHandle< Map > map) [inline], [static], [private]
Definition at line 385 of file transitions-inl.h.
                                             {
  Tagged<MaybeObject> raw_transitions =
      map->raw_transitions(isolate, kAcquireLoad);
  return GetEncoding(isolate, raw_transitions);
}
References GetEncoding(), v8::kAcquireLoad, and v8::internal::raw_transitions.
GetEncoding() [2/3]
TransitionsAccessor::Encoding v8::internal::TransitionsAccessor::GetEncoding (Isolate * isolate, Tagged< MaybeObject > raw_transitions) [inline], [static], [private]
Definition at line 355 of file transitions-inl.h.
                                                           {
  Tagged<HeapObject> heap_object;
  if (raw_transitions.IsSmi() || raw_transitions.IsCleared()) {
    return kUninitialized;
  } else if (raw_transitions.IsWeak()) {
    return kWeakRef;
  } else if (raw_transitions.GetHeapObjectIfStrong(isolate, &heap_object)) {
    if (IsTransitionArray(heap_object)) {
      return kFullTransitionArray;
    } else if (IsPrototypeInfo(heap_object)) {
      return kPrototypeInfo;
    } else {
      DCHECK(IsMap(heap_object));
      return kMigrationTarget;
    }
  } else {
    UNREACHABLE();
  }
}
References v8::internal::DCHECK(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::raw_transitions, and v8::internal::UNREACHABLE().
Referenced by CanHaveMoreTransitions(), EnsureHasFullTransitionArray(), GetEncoding(), GetPrototypeTransitions(), GetSimpleTransition(), GetTransitionArray(), InsertHelper(), ReplaceTransitions(), SetMigrationTarget(), and TraverseTransitionTreeInternal().
GetEncoding() [3/3]
TransitionsAccessor::Encoding v8::internal::TransitionsAccessor::GetEncoding (Isolate * isolate, Tagged< TransitionArray > array) [inline], [static], [private]
Definition at line 377 of file transitions-inl.h.
                                                     {
  DCHECK_EQ(GetEncoding(isolate, Tagged<MaybeObject>(array)),
            kFullTransitionArray);
  return kFullTransitionArray;
}
References DCHECK_EQ, GetEncoding(), and kFullTransitionArray.
GetKey()
Tagged< Name > v8::internal::TransitionsAccessor::GetKey (int transition_number) [inline]
Definition at line 135 of file transitions-inl.h.
                                                              {
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      UNREACHABLE();
      return Tagged<Name>();
    case kWeakRef: {
      Tagged<Map> map = Cast<Map>(raw_transitions_.GetHeapObjectAssumeWeak());
      return GetSimpleTransitionKey(map);
    }
    case kFullTransitionArray:
      return transitions()->GetKey(transition_number);
  }
  UNREACHABLE();
}
References encoding(), GetSimpleTransitionKey(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, raw_transitions_, transitions(), and v8::internal::UNREACHABLE().
GetMigrationTarget()
Tagged< Map > v8::internal::TransitionsAccessor::GetMigrationTarget ()
Definition at line 541 of file transitions.cc.
                                                    {
  if (encoding() == kMigrationTarget) {
    return Cast<Map>(map_->raw_transitions(kAcquireLoad));
  }
  return Tagged<Map>();
}
References encoding(), v8::kAcquireLoad, kMigrationTarget, and map_.
Referenced by v8::internal::anonymous_namespace{map.cc}::SearchMigrationTarget().
GetPrototypeTransition()
std::optional< Tagged< Map > > v8::internal::TransitionsAccessor::GetPrototypeTransition (Isolate * isolate, Tagged< Map > map, Tagged< Object > prototype) [static]
Definition at line 459 of file transitions.cc.
                                                                 {
  DisallowGarbageCollection no_gc;
  Tagged<WeakFixedArray> cache = GetPrototypeTransitions(isolate, map);
  int length = TransitionArray::NumberOfPrototypeTransitions(cache);
  for (int i = 0; i < length; i++) {
    Tagged<MaybeObject> target =
        cache->get(TransitionArray::kProtoTransitionHeaderSize + i);
    DCHECK(target.IsWeakOrCleared());
    Tagged<HeapObject> heap_object;
    if (target.GetHeapObjectIfWeak(&heap_object)) {
      Tagged<Map> target_map = Cast<Map>(heap_object);
      if (target_map->prototype() == prototype) {
        return target_map;
      }
    }
  }
  return {};
}
References v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), GetPrototypeTransitions(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), v8::internal::TransitionArray::kProtoTransitionHeaderSize, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TransitionArray::NumberOfPrototypeTransitions(), and v8::internal::prototype.
Referenced by v8::internal::Map::TransitionToUpdatePrototype(), and v8::internal::MapUpdater::TryUpdateNoLock().
GetPrototypeTransitions()
Tagged< WeakFixedArray > v8::internal::TransitionsAccessor::GetPrototypeTransitions (Isolate * isolate, Tagged< Map > map) [static], [private]
Definition at line 480 of file transitions.cc.
                                       {
  Tagged<MaybeObject> raw_transitions =
      map->raw_transitions(isolate, kAcquireLoad);
  if (GetEncoding(isolate, raw_transitions) != kFullTransitionArray) {
    return ReadOnlyRoots(isolate).empty_weak_fixed_array();
  }
  Tagged<TransitionArray> transition_array =
      GetTransitionArray(isolate, raw_transitions);
  if (!transition_array->HasPrototypeTransitions()) {
    return ReadOnlyRoots(isolate).empty_weak_fixed_array();
  }
  return transition_array->GetPrototypeTransitions();
}
References GetEncoding(), GetTransitionArray(), v8::kAcquireLoad, kFullTransitionArray, and v8::internal::raw_transitions.
Referenced by GetPrototypeTransition(), and PutPrototypeTransition().
GetSideStepTransition()
Tagged< Object > v8::internal::TransitionsAccessor::GetSideStepTransition (SideStepTransition::Kind i) [inline]
Definition at line 67 of file transitions-inl.h.
                                 {
  DCHECK(HasSideStepTransitions());
  auto res = transitions()->GetSideStepTransitions()->get(
      SideStepTransition::index_of(kind));
  if (res.IsSmi()) {
    DCHECK(res == SideStepTransition::Empty ||
           res == SideStepTransition::Unreachable);
    return res.ToSmi();
  }
  Tagged<HeapObject> target;
  if (res.GetHeapObjectIfWeak(&target)) return target;
  DCHECK(res.IsCleared());
  return SideStepTransition::Empty;
}
References v8::internal::DCHECK(), v8::internal::SideStepTransition::Empty, HasSideStepTransitions(), v8::internal::SideStepTransition::index_of(), transitions(), and v8::internal::SideStepTransition::Unreachable.
Referenced by v8::internal::anonymous_namespace{ic.cc}::GetCloneTargetMap().
GetSimpleTargetDetails()
PropertyDetails v8::internal::TransitionsAccessor::GetSimpleTargetDetails (Tagged< Map > transition) [inline], [private]
Definition at line 174 of file transitions-inl.h.
                            {
  return transition->GetLastDescriptorDetails(isolate_);
}
References isolate_.
Referenced by IsExpectedTransition().
GetSimpleTransition()
Tagged< Map > v8::internal::TransitionsAccessor::GetSimpleTransition (Isolate * isolate, DirectHandle< Map > map) [inline], [static], [private]
Definition at line 17 of file transitions.cc.
                                                                            {
  Tagged<MaybeObject> raw_transitions =
      map->raw_transitions(isolate, kAcquireLoad);
  switch (GetEncoding(isolate, raw_transitions)) {
    case kWeakRef:
      return Cast<Map>(raw_transitions.GetHeapObjectAssumeWeak());
    default:
      return Tagged<Map>();
  }
}
References GetEncoding(), v8::kAcquireLoad, kWeakRef, and v8::internal::raw_transitions.
Referenced by EnsureHasFullTransitionArray(), and InsertHelper().
GetSimpleTransitionKey()
Tagged< Name > v8::internal::TransitionsAccessor::GetSimpleTransitionKey (Tagged< Map > transition) [inline], [static], [private]
Definition at line 180 of file transitions-inl.h.
                            {
  InternalIndex descriptor = transition->LastAdded();
  return transition->instance_descriptors()->GetKey(descriptor);
}
Referenced by EnsureHasFullTransitionArray(), ExpectedTransition(), ForEachTransitionWithKey(), GetKey(), and InsertHelper().
GetTarget()
Tagged< Map > v8::internal::TransitionsAccessor::GetTarget (int transition_number) [inline]
Definition at line 201 of file transitions-inl.h.
                                                                {
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      UNREACHABLE();
      return Map();
    case kWeakRef:
      return Cast<Map>(raw_transitions_.GetHeapObjectAssumeWeak());
    case kFullTransitionArray:
      return transitions()->GetTarget(transition_number);
  }
  UNREACHABLE();
}
References encoding(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::compiler::Map, raw_transitions_, transitions(), and v8::internal::UNREACHABLE().
Referenced by ExpectedTransition(), and ForEachTransitionWithKey().
GetTargetDetails()
PropertyDetails v8::internal::TransitionsAccessor::GetTargetDetails (Tagged< Name > name, Tagged< Map > target) [inline], [static]
Definition at line 163 of file transitions-inl.h.
                                                                          {
  DCHECK(!IsSpecialTransition(GetReadOnlyRoots(), name));
  InternalIndex descriptor = target->LastAdded();
  Tagged<DescriptorArray> descriptors =
      target->instance_descriptors(kRelaxedLoad);
  // Transitions are allowed only for the last added property.
  DCHECK(descriptors->GetKey(descriptor)->Equals(name));
  return descriptors->GetDetails(descriptor);
}
References v8::internal::DCHECK(), v8::internal::GetReadOnlyRoots(), IsSpecialTransition(), v8::kRelaxedLoad, and v8::internal::name.
Referenced by InsertHelper(), v8::internal::TransitionArray::SearchDetails(), v8::internal::TransitionArray::SearchDetailsAndGetTarget(), and v8::internal::TransitionArray::Sort().
GetTargetFromRaw()
Tagged< Map > v8::internal::TransitionsAccessor::GetTargetFromRaw (Tagged< MaybeObject > raw) [inline], [static], [private]
Definition at line 187 of file transitions-inl.h.
                                                                         {
  return Cast<Map>(raw.GetHeapObjectAssumeWeak());
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak().
Referenced by v8::internal::TransitionArray::GetTarget(), v8::internal::TransitionArray::GetTargetIfExists(), and v8::internal::TransitionArray::Sort().
GetTargetMapFromWeakRef()
Tagged<Map> v8::internal::TransitionsAccessor::GetTargetMapFromWeakRef () [inline], [private]
GetTransitionArray() [1/2]
Tagged< TransitionArray > v8::internal::TransitionsAccessor::GetTransitionArray (Isolate * isolate, DirectHandle< Map > map) [inline], [static], [private]
Definition at line 34 of file transitions-inl.h.
                                             {
  Tagged<MaybeObject> raw_transitions =
      map->raw_transitions(isolate, kAcquireLoad);
  return GetTransitionArray(isolate, raw_transitions);
}
References GetTransitionArray(), v8::kAcquireLoad, and v8::internal::raw_transitions.
GetTransitionArray() [2/2]
Tagged< TransitionArray > v8::internal::TransitionsAccessor::GetTransitionArray (Isolate * isolate, Tagged< MaybeObject > raw_transitions) [inline], [static], [private]
Definition at line 26 of file transitions-inl.h.
                                                           {
  DCHECK_EQ(kFullTransitionArray, GetEncoding(isolate, raw_transitions));
  USE(isolate);
  return Cast<TransitionArray>(raw_transitions.GetHeapObjectAssumeStrong());
}
References DCHECK_EQ, GetEncoding(), kFullTransitionArray, v8::internal::raw_transitions, and USE.
Referenced by CanHaveMoreTransitions(), EnsureHasSideStepTransitions(), GetPrototypeTransitions(), GetTransitionArray(), InsertHelper(), ReplaceTransitions(), SetPrototypeTransitions(), and transitions().
HasIntegrityLevelTransitionTo()
bool v8::internal::TransitionsAccessor::HasIntegrityLevelTransitionTo (Tagged< Map > to, Tagged< Symbol > * out_symbol = nullptr, PropertyAttributes * out_integrity_level = nullptr)
Definition at line 825 of file transitions.cc.
                                             {
  ReadOnlyRoots roots(isolate_);
  if (SearchSpecial(roots.frozen_symbol()) == to) {
    if (out_integrity_level) *out_integrity_level = FROZEN;
    if (out_symbol) *out_symbol = roots.frozen_symbol();
  } else if (SearchSpecial(roots.sealed_symbol()) == to) {
    if (out_integrity_level) *out_integrity_level = SEALED;
    if (out_symbol) *out_symbol = roots.sealed_symbol();
  } else if (SearchSpecial(roots.nonextensible_symbol()) == to) {
    if (out_integrity_level) *out_integrity_level = NONE;
    if (out_symbol) *out_symbol = roots.nonextensible_symbol();
  } else {
    return false;
  }
  return true;
}
References v8::internal::FROZEN, isolate_, v8::internal::NONE, v8::internal::SEALED, and SearchSpecial().
Referenced by v8::internal::anonymous_namespace{map-updater.cc}::DetectIntegrityLevelTransitions(), and v8::internal::MapUpdater::TrySaveIntegrityLevelTransitions().
HasPrototypeTransitions()
bool v8::internal::TransitionsAccessor::HasPrototypeTransitions ()
Definition at line 517 of file transitions.cc.
                                                  {
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
    case kWeakRef:
      return false;
    case kFullTransitionArray:
      return transitions()->HasPrototypeTransitions();
  }
  UNREACHABLE();
}
References encoding(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, transitions(), and v8::internal::UNREACHABLE().
Referenced by ForEachTransitionWithKey(), and v8::internal::Map::MapPrint().
HasSideStepTransitions()
bool v8::internal::TransitionsAccessor::HasSideStepTransitions () [inline]
Definition at line 60 of file transitions-inl.h.
                                                 {
  if (encoding() != kFullTransitionArray) {
    return false;
  }
  return transitions()->HasSideStepTransitions();
}
References encoding(), kFullTransitionArray, and transitions().
Referenced by ForEachTransitionWithKey(), v8::internal::anonymous_namespace{ic.cc}::GetCloneTargetMap(), GetSideStepTransition(), v8::internal::Map::MapPrint(), and SetSideStepTransition().
HasSimpleTransitionTo()
bool v8::internal::TransitionsAccessor::HasSimpleTransitionTo (Tagged< Map > map) [private]
Definition at line 29 of file transitions.cc.
                                                               {
  switch (encoding()) {
    case kWeakRef:
      return raw_transitions_.GetHeapObjectAssumeWeak() == map;
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
    case kFullTransitionArray:
      return false;
  }
  UNREACHABLE();
}
References encoding(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, raw_transitions_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::MarkCompactCollector::ClearPotentialSimpleMapTransition().
Insert()
static void v8::internal::TransitionsAccessor::Insert (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Map > target, TransitionKindFlag flag) [inline], [static]
Definition at line 85 of file transitions.h.
                                              {
    InsertHelper(isolate, map, name, DirectHandle<Map>(target), flag);
  }
References v8::internal::name.
Referenced by v8::internal::Map::ConnectTransition().
InsertHelper()
void v8::internal::TransitionsAccessor::InsertHelper (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name, DirectHandle< Map > target, TransitionKindFlag flag) [static], [private]
Definition at line 43 of file transitions.cc.
                                                                {
  DCHECK_NE(flag, PROTOTYPE_TRANSITION);
  Encoding encoding = GetEncoding(isolate, map);
  DCHECK_NE(kPrototypeInfo, encoding);
  ReadOnlyRoots roots(isolate);
  (*target)->SetBackPointer(*map);
  // If the map doesn't have any transitions at all yet, install the new one.
  if (encoding == kUninitialized || encoding == kMigrationTarget) {
    if (flag == SIMPLE_PROPERTY_TRANSITION) {
      ReplaceTransitions(isolate, map, MakeWeak(*target));
      return;
    }
    // If the flag requires a full TransitionArray, allocate one.
    DirectHandle<TransitionArray> result =
        isolate->factory()->NewTransitionArray(1, 0);
    result->Set(0, *name, MakeWeak(*target));
    ReplaceTransitions(isolate, map, result);
    DCHECK_EQ(kFullTransitionArray, GetEncoding(isolate, *result));
    return;
  }
  if (encoding == kWeakRef) {
    Tagged<Map> simple_transition = GetSimpleTransition(isolate, map);
    DCHECK(!simple_transition.is_null());
    if (flag == SIMPLE_PROPERTY_TRANSITION) {
      Tagged<Name> key = GetSimpleTransitionKey(simple_transition);
      PropertyDetails old_details =
          simple_transition->GetLastDescriptorDetails(isolate);
      PropertyDetails new_details = GetTargetDetails(*name, **target);
      if (key->Equals(*name) && old_details.kind() == new_details.kind() &&
          old_details.attributes() == new_details.attributes()) {
        ReplaceTransitions(isolate, map, MakeWeak(*target));
        return;
      }
    }
    // Otherwise allocate a full TransitionArray with slack for a new entry.
    DirectHandle<TransitionArray> result =
        isolate->factory()->NewTransitionArray(1, 1);
    // Reload `simple_transition`. Allocations might have caused it to be
    // cleared.
    simple_transition = GetSimpleTransition(isolate, map);
    if (simple_transition.is_null()) {
      result->Set(0, *name, MakeWeak(*target));
      ReplaceTransitions(isolate, map, result);
      DCHECK_EQ(kFullTransitionArray, GetEncoding(isolate, *result));
      return;
    }
    // Insert the original transition in index 0.
    result->Set(0, GetSimpleTransitionKey(simple_transition),
                MakeWeak(simple_transition));
    // Search for the correct index to insert the new transition.
    int insertion_index;
    int index;
    if (flag == SPECIAL_TRANSITION) {
      index =
          result->SearchSpecial(Cast<Symbol>(*name), false, &insertion_index);
    } else {
      PropertyDetails details = GetTargetDetails(*name, **target);
      index = result->Search(details.kind(), *name, details.attributes(),
                             &insertion_index);
    }
    DCHECK_EQ(index, kNotFound);
    USE(index);
    result->SetNumberOfTransitions(2);
    if (insertion_index == 0) {
      // If the new transition will be inserted in index 0, move the original
      // transition to index 1.
      result->Set(1, GetSimpleTransitionKey(simple_transition),
                  MakeWeak(simple_transition));
    }
    result->SetKey(insertion_index, *name);
    result->SetRawTarget(insertion_index, MakeWeak(*target));
    SLOW_DCHECK(result->IsSortedNoDuplicates());
    ReplaceTransitions(isolate, map, result);
    DCHECK_EQ(kFullTransitionArray, GetEncoding(isolate, *result));
    return;
  }
  // At this point, we know that the map has a full TransitionArray.
  DCHECK_EQ(kFullTransitionArray, encoding);
  int number_of_transitions = 0;
  int new_nof = 0;
  int insertion_index = kNotFound;
  const bool is_special_transition = flag == SPECIAL_TRANSITION;
  DCHECK_EQ(is_special_transition, IsSpecialTransition(roots, *name));
  PropertyDetails details = is_special_transition
                                ? PropertyDetails::Empty()
                                : GetTargetDetails(*name, **target);
  {
    DisallowGarbageCollection no_gc;
    Tagged<TransitionArray> array = GetTransitionArray(isolate, map);
    number_of_transitions = array->number_of_transitions();
    int index =
        is_special_transition
            ? array->SearchSpecial(Cast<Symbol>(*name), false, &insertion_index)
            : array->Search(details.kind(), *name, details.attributes(),
                            &insertion_index);
    // If an existing entry was found, overwrite it and return.
    if (index != kNotFound) {
      base::MutexGuard mutex_guard(isolate->full_transition_array_access());
      array->SetRawTarget(index, MakeWeak(*target));
      return;
    }
    new_nof = number_of_transitions + 1;
    CHECK_LE(new_nof, kMaxNumberOfTransitions);
    DCHECK_GE(insertion_index, 0);
    DCHECK_LE(insertion_index, number_of_transitions);
    // If there is enough capacity, insert new entry into the existing array.
    if (new_nof <= array->Capacity()) {
      base::MutexGuard mutex_guard(isolate->full_transition_array_access());
      array->SetNumberOfTransitions(new_nof);
      for (int i = number_of_transitions; i > insertion_index; --i) {
        array->SetKey(i, array->GetKey(i - 1));
        array->SetRawTarget(i, array->GetRawTarget(i - 1));
      }
      array->SetKey(insertion_index, *name);
      array->SetRawTarget(insertion_index, MakeWeak(*target));
      SLOW_DCHECK(array->IsSortedNoDuplicates());
      return;
    }
  }
  // We're gonna need a bigger TransitionArray.
  DirectHandle<TransitionArray> result = isolate->factory()->NewTransitionArray(
      new_nof,
      Map::SlackForArraySize(number_of_transitions, kMaxNumberOfTransitions));
  // The map's transition array may have shrunk during the allocation above as
  // it was weakly traversed, though it is guaranteed not to disappear. Trim the
  // result copy if needed, and recompute variables.
  DisallowGarbageCollection no_gc;
  Tagged<TransitionArray> array = GetTransitionArray(isolate, map);
  if (array->number_of_transitions() != number_of_transitions) {
    DCHECK_LT(array->number_of_transitions(), number_of_transitions);
    int index =
        is_special_transition
            ? array->SearchSpecial(Cast<Symbol>(*name), false, &insertion_index)
            : array->Search(details.kind(), *name, details.attributes(),
                            &insertion_index);
    CHECK_EQ(index, kNotFound);
    USE(index);
    DCHECK_GE(insertion_index, 0);
    DCHECK_LE(insertion_index, number_of_transitions);
    number_of_transitions = array->number_of_transitions();
    new_nof = number_of_transitions + 1;
    result->SetNumberOfTransitions(new_nof);
  }
  if (array->HasPrototypeTransitions()) {
    result->SetPrototypeTransitions(array->GetPrototypeTransitions());
  }
  if (array->HasSideStepTransitions()) {
    result->SetSideStepTransitions(array->GetSideStepTransitions());
  }
  DCHECK_NE(kNotFound, insertion_index);
  for (int i = 0; i < insertion_index; ++i) {
    result->Set(i, array->GetKey(i), array->GetRawTarget(i));
  }
  result->Set(insertion_index, *name, MakeWeak(*target));
  for (int i = insertion_index; i < number_of_transitions; ++i) {
    result->Set(i + 1, array->GetKey(i), array->GetRawTarget(i));
  }
  SLOW_DCHECK(result->IsSortedNoDuplicates());
  ReplaceTransitions(isolate, map, result);
}
References v8::internal::PropertyDetails::attributes(), Capacity(), CHECK_EQ, CHECK_LE, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_LT, DCHECK_NE, v8::internal::PropertyDetails::Empty(), encoding(), v8::internal::Isolate::factory(), v8::internal::Isolate::full_transition_array_access(), GetEncoding(), GetSimpleTransition(), GetSimpleTransitionKey(), GetTargetDetails(), GetTransitionArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Tagged< HeapObject >::is_null(), IsSpecialTransition(), v8::internal::key, kFullTransitionArray, v8::internal::PropertyDetails::kind(), kMaxNumberOfTransitions, kMigrationTarget, v8::internal::kNotFound, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::MakeWeak(), v8::internal::name, v8::internal::Factory::NewTransitionArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PROTOTYPE_TRANSITION, ReplaceTransitions(), v8::base::internal::result, v8::internal::SIMPLE_PROPERTY_TRANSITION, v8::internal::Map::SlackForArraySize(), SLOW_DCHECK, v8::internal::SPECIAL_TRANSITION, and USE.
InsertNoneSentinel()
static void v8::internal::TransitionsAccessor::InsertNoneSentinel (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Name > name) [inline], [static]
Definition at line 90 of file transitions.h.
                                                          {
    InsertHelper(isolate, map, name, DirectHandle<Map>(),
                 TransitionKindFlag::SPECIAL_TRANSITION);
  }
References v8::internal::name, and v8::internal::SPECIAL_TRANSITION.
IsExpectedTransition()
template<typename Char >
bool v8::internal::TransitionsAccessor::IsExpectedTransition (Tagged< Name > transition_name, Tagged< Map > transition_target, base::Vector< const Char > key_chars) [inline]
Definition at line 472 of file transitions-inl.h.
                                      {
  if (transition_target->NumberOfOwnDescriptors() == 0) return false;
  PropertyDetails details = GetSimpleTargetDetails(transition_target);
  if (details.location() != PropertyLocation::kField) return false;
  DCHECK_EQ(PropertyKind::kData, details.kind());
  if (details.attributes() != NONE) return false;
  if (!IsString(transition_name)) return false;
  if (!Cast<String>(transition_name)->IsEqualTo(key_chars)) return false;
  return true;
}
References v8::internal::PropertyDetails::attributes(), DCHECK_EQ, GetSimpleTargetDetails(), v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), and v8::internal::NONE.
Referenced by ExpectedTransition().
IsMatchingMap()
bool v8::internal::TransitionsAccessor::IsMatchingMap (Tagged< Map > target, Tagged< Name > name, PropertyKind kind, PropertyAttributes attributes) [static]
Definition at line 329 of file transitions.cc.
                                                                       {
  InternalIndex descriptor = target->LastAdded();
  Tagged<DescriptorArray> descriptors =
      target->instance_descriptors(kRelaxedLoad);
  Tagged<Name> key = descriptors->GetKey(descriptor);
  if (key != name) return false;
  return descriptors->GetDetails(descriptor)
      .HasKindAndAttributes(kind, attributes);
}
References v8::internal::key, v8::kRelaxedLoad, and v8::internal::name.
Referenced by SearchTransition().
IsSpecialTransition()
bool v8::internal::TransitionsAccessor::IsSpecialTransition (ReadOnlyRoots roots, Tagged< Name > name) [static]
Definition at line 261 of file transitions.cc.
                                                                 {
  if (!IsSymbol(name)) return false;
  return name == roots.nonextensible_symbol() ||
         name == roots.sealed_symbol() || name == roots.frozen_symbol() ||
         name == roots.elements_transition_symbol() ||
         name == roots.strict_function_transition_symbol();
}
References v8::internal::name.
Referenced by GetTargetDetails(), InsertHelper(), and v8::internal::TransitionArray::Sort().
NumberOfTransitions()
int v8::internal::TransitionsAccessor::NumberOfTransitions ()
Definition at line 503 of file transitions.cc.
                                             {
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      return 0;
    case kWeakRef:
      return 1;
    case kFullTransitionArray:
      return transitions()->number_of_transitions();
  }
  UNREACHABLE();
}
References encoding(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, transitions(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::Map::MapPrint().
PutPrototypeTransition()
bool v8::internal::TransitionsAccessor::PutPrototypeTransition (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > prototype, DirectHandle< Map > target_map) [static]
Definition at line 392 of file transitions.cc.
                                                                               {
  DCHECK_IMPLIES(v8_flags.move_prototype_transitions_first,
                 IsUndefined(map->GetBackPointer()));
  DCHECK(IsMap(Cast<HeapObject>(*prototype)->map()));
  // Only the main thread should write to transition arrays.
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  // It's OK to read the transition array without holding the
  // full_transition_array_access lock in read mode, since this is only called
  // in the main thread, and the main thread is the only writer. In addition, we
  // shouldn't GC while holding the lock, because it will cause a deadlock if a
  // background thread is waiting for the shared mutex outside of a safepoint.
  // Don't cache prototype transition if this map is either shared, or a map of
  // a prototype.
  if (map->is_prototype_map()) return false;
  if (map->is_dictionary_map() || !v8_flags.cache_prototype_transitions)
    return false;
  const int header = TransitionArray::kProtoTransitionHeaderSize;
  DirectHandle<WeakFixedArray> cache(GetPrototypeTransitions(isolate, *map),
                                     isolate);
  int capacity = cache->length() - header;
  int transitions = TransitionArray::NumberOfPrototypeTransitions(*cache) + 1;
  if (transitions > capacity) {
    // Grow the array if compacting it doesn't free space.
    bool compacted;
    {
      base::MutexGuard guard(isolate->full_transition_array_access());
      DisallowGarbageCollection no_gc;
      compacted =
          TransitionArray::CompactPrototypeTransitionArray(isolate, *cache);
    }
    if (!compacted) {
      if (capacity == TransitionArray::kMaxCachedPrototypeTransitions)
        return false;
      cache = TransitionArray::GrowPrototypeTransitionArray(
          cache, 2 * transitions, isolate);
      SetPrototypeTransitions(isolate, map, cache);
    }
  }
  if (v8_flags.move_prototype_transitions_first) {
    target_map->SetBackPointer(*map);
  }
  // Reload number of transitions as they might have been compacted.
  int last = TransitionArray::NumberOfPrototypeTransitions(*cache);
  int entry = header + last;
  {
    base::MutexGuard guard(isolate->full_transition_array_access());
    DisallowGarbageCollection no_gc;
    cache->set(entry, MakeWeak(*target_map));
    TransitionArray::SetNumberOfPrototypeTransitions(*cache, last + 1);
  }
  return true;
}
References v8::internal::TransitionArray::CompactPrototypeTransitionArray(), v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Isolate::full_transition_array_access(), GetPrototypeTransitions(), v8::internal::TransitionArray::GrowPrototypeTransitionArray(), v8::internal::TransitionArray::kMaxCachedPrototypeTransitions, v8::internal::TransitionArray::kProtoTransitionHeaderSize, v8::internal::MakeWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TransitionArray::NumberOfPrototypeTransitions(), v8::internal::TransitionArray::SetNumberOfPrototypeTransitions(), SetPrototypeTransitions(), v8::internal::Isolate::thread_id(), transitions(), and v8::internal::v8_flags.
Referenced by v8::internal::Map::TransitionToUpdatePrototype().
ReplaceTransitions() [1/2]
void v8::internal::TransitionsAccessor::ReplaceTransitions (Isolate * isolate, DirectHandle< Map > map, DirectHandle< TransitionArray > new_transitions) [inline], [static], [private]
Definition at line 565 of file transitions.cc.
                                                   {
  ReplaceTransitions(isolate, map, *new_transitions);
}
References ReplaceTransitions().
ReplaceTransitions() [2/2]
void v8::internal::TransitionsAccessor::ReplaceTransitions (Isolate * isolate, DirectHandle< Map > map, Tagged< UnionOf< TransitionArray, MaybeWeak< Map >>> new_transitions) [inline], [static], [private]
Definition at line 549 of file transitions.cc.
                                                                      {
#if DEBUG
  if (GetEncoding(isolate, map) == kFullTransitionArray) {
    CheckNewTransitionsAreConsistent(
        isolate, map, new_transitions.GetHeapObjectAssumeStrong());
    DCHECK_NE(GetTransitionArray(isolate, map),
              new_transitions.GetHeapObjectAssumeStrong());
  }
#endif
  map->set_raw_transitions(new_transitions, kReleaseStore);
  USE(isolate);
}
References DCHECK_NE, GetEncoding(), GetTransitionArray(), kFullTransitionArray, v8::kReleaseStore, and USE.
Referenced by EnsureHasFullTransitionArray(), InsertHelper(), and ReplaceTransitions().
SearchSpecial() [1/2]
MaybeHandle< Map > v8::internal::TransitionsAccessor::SearchSpecial (Isolate * isolate, DirectHandle< Map > map, Tagged< Symbol > name) [inline], [static]
Definition at line 403 of file transitions-inl.h.
                                                                         {
  Tagged<Map> result = TransitionsAccessor(isolate, *map).SearchSpecial(name);
  if (result.is_null()) return {};
  return MaybeHandle<Map>(result, isolate);
}
References v8::internal::name, v8::base::internal::result, and TransitionsAccessor().
SearchSpecial() [2/2]
Tagged< Map > v8::internal::TransitionsAccessor::SearchSpecial (Tagged< Symbol > name)
Definition at line 251 of file transitions.cc.
                                                                  {
  if (encoding() != kFullTransitionArray) return {};
  base::MutexGuardIf guard(isolate_->full_transition_array_access(),
                           concurrent_access_);
  int transition = transitions()->SearchSpecial(name, concurrent_access_);
  if (transition == kNotFound) return {};
  return transitions()->GetTarget(transition);
}
References concurrent_access_, encoding(), v8::internal::Isolate::full_transition_array_access(), isolate_, kFullTransitionArray, v8::internal::kNotFound, v8::internal::name, and transitions().
Referenced by v8::internal::Map::AsLanguageMode(), v8::internal::Map::ElementsTransitionMap(), v8::internal::MapUpdater::FindTargetMap(), HasIntegrityLevelTransitionTo(), v8::internal::JSObject::PreventExtensionsWithTransition(), and v8::internal::MapUpdater::TryUpdateNoLock().
SearchTransition() [1/2]
MaybeHandle< Map > v8::internal::TransitionsAccessor::SearchTransition (Isolate * isolate, DirectHandle< Map > map, Tagged< Name > name, PropertyKind kind, PropertyAttributes attributes) [inline], [static]
Definition at line 393 of file transitions-inl.h.
                                                      {
  Tagged<Map> result = TransitionsAccessor(isolate, *map)
                           .SearchTransition(name, kind, attributes);
  if (result.is_null()) return MaybeHandle<Map>();
  return MaybeHandle<Map>(result, isolate);
}
References v8::internal::name, v8::base::internal::result, and TransitionsAccessor().
SearchTransition() [2/2]
Tagged< Map > v8::internal::TransitionsAccessor::SearchTransition (Tagged< Name > name, PropertyKind kind, PropertyAttributes attributes)
Definition at line 229 of file transitions.cc.
                                                                         {
  DCHECK(IsUniqueName(name));
  switch (encoding()) {
    case kPrototypeInfo:
    case kUninitialized:
    case kMigrationTarget:
      return Tagged<Map>();
    case kWeakRef: {
      Tagged<Map> map = Cast<Map>(raw_transitions_.GetHeapObjectAssumeWeak());
      if (!IsMatchingMap(map, name, kind, attributes)) return Tagged<Map>();
      return map;
    }
    case kFullTransitionArray: {
      base::MutexGuardIf guard(isolate_->full_transition_array_access(),
                               concurrent_access_);
      return transitions()->SearchAndGetTarget(kind, name, attributes);
    }
  }
  UNREACHABLE();
}
References concurrent_access_, v8::internal::DCHECK(), encoding(), v8::internal::Isolate::full_transition_array_access(), IsMatchingMap(), isolate_, v8::internal::IsUniqueName(), kFullTransitionArray, kMigrationTarget, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::name, raw_transitions_, transitions(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::MapUpdater::ConstructNewMap(), v8::internal::MapUpdater::FindSplitMap(), v8::internal::MapUpdater::FindTargetMap(), FindTransitionToField(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::Map::TransitionToAccessorProperty(), v8::internal::Map::TransitionToDataProperty(), v8::internal::anonymous_namespace{js-objects.cc}::TryFastAddDataProperty(), and v8::internal::Map::TryReplayPropertyTransitions().
SetMigrationTarget()
void v8::internal::TransitionsAccessor::SetMigrationTarget (Isolate * isolate, DirectHandle< Map > map, Tagged< Map > migration_target) [static]
Definition at line 531 of file transitions.cc.
                                                                           {
  // We only cache the migration target for maps with empty transitions for GC's
  // sake.
  if (GetEncoding(isolate, map) != kUninitialized) return;
  DCHECK(map->is_deprecated());
  map->set_raw_transitions(migration_target, kReleaseStore);
}
References v8::internal::DCHECK(), GetEncoding(), v8::kReleaseStore, and kUninitialized.
Referenced by v8::internal::Map::TryUpdate(), and v8::internal::MapUpdater::UpdateImpl().
SetPrototypeTransitions()
void v8::internal::TransitionsAccessor::SetPrototypeTransitions (Isolate * isolate, DirectHandle< Map > map, DirectHandle< WeakFixedArray > proto_transitions) [static], [private]
Definition at line 572 of file transitions.cc.
                                                    {
  EnsureHasFullTransitionArray(isolate, map);
  GetTransitionArray(isolate, map->raw_transitions(isolate, kAcquireLoad))
      ->SetPrototypeTransitions(*proto_transitions);
}
References EnsureHasFullTransitionArray(), GetTransitionArray(), and v8::kAcquireLoad.
Referenced by PutPrototypeTransition().
SetSideStepTransition()
void v8::internal::TransitionsAccessor::SetSideStepTransition (SideStepTransition::Kind i, Tagged< Object > target) [inline]
Definition at line 83 of file transitions-inl.h.
                                                                       {
  DCHECK(HasSideStepTransitions());
  DCHECK(object == SideStepTransition::Unreachable || IsMap(object) ||
         IsCell(object));
  DCHECK_IMPLIES(IsCell(object),
                 kind == SideStepTransition::Kind::kObjectAssignValidityCell);
  DCHECK_LT(SideStepTransition::index_of(kind), SideStepTransition::kSize);
  DCHECK_GE(SideStepTransition::index_of(kind), 0);
  transitions()->GetSideStepTransitions()->set(
      SideStepTransition::index_of(kind),
      object.IsSmi() ? object : MakeWeak(object));
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_IMPLIES, DCHECK_LT, HasSideStepTransitions(), v8::internal::SideStepTransition::index_of(), v8::internal::IsSmi(), v8::internal::SideStepTransition::kObjectAssignValidityCell, v8::internal::SideStepTransition::kSize, v8::internal::MakeWeak(), transitions(), and v8::internal::SideStepTransition::Unreachable.
Referenced by v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMap(), and v8::internal::anonymous_namespace{ic.cc}::SetCloneTargetMapUnsupported().
transitions()
Tagged< TransitionArray > v8::internal::TransitionsAccessor::transitions () [inline], [protected]
Definition at line 41 of file transitions-inl.h.
                                                         {
  return GetTransitionArray(isolate_, raw_transitions_);
}
References GetTransitionArray(), isolate_, and raw_transitions_.
Referenced by Capacity(), EnsureHasSideStepTransitions(), ForEachTransitionTo(), ForEachTransitionWithKey(), GetKey(), GetSideStepTransition(), GetTarget(), HasPrototypeTransitions(), HasSideStepTransitions(), NumberOfTransitions(), PutPrototypeTransition(), SearchSpecial(), SearchTransition(), SetSideStepTransition(), and TraverseTransitionTreeInternal().
TraverseTransitionTree()
void v8::internal::TransitionsAccessor::TraverseTransitionTree (const TraverseCallback & callback) [inline]
Definition at line 172 of file transitions.h.
                                                                {
    // Make sure that we do not allocate in the callback.
    DisallowGarbageCollection no_gc;
    base::MutexGuardIf mutex_guard(isolate_->full_transition_array_access(),
                                   concurrent_access_);
    TraverseTransitionTreeInternal(callback, &no_gc);
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::MapUpdater::CompleteInobjectSlackTracking(), v8::internal::Map::ComputeMinObjectSlack(), and v8::internal::compiler::anonymous_namespace{heap-refs.cc}::InstanceSizeWithMinSlack().
TraverseTransitionTreeInternal()
void v8::internal::TransitionsAccessor::TraverseTransitionTreeInternal (const TraverseCallback & callback, DisallowGarbageCollection * no_gc) [private]
Definition at line 606 of file transitions.cc.
                                                                        {
  // Mostly arbitrary but more than enough to run the test suite in static
  // memory.
  static constexpr int kStaticStackSize = 16;
  base::SmallVector<Tagged<Map>, kStaticStackSize> stack;
  stack.emplace_back(map_);
  // Pre-order iterative depth-first-search.
  while (!stack.empty()) {
    Tagged<Map> current_map = stack.back();
    stack.pop_back();
    callback(current_map);
    Tagged<MaybeObject> raw_transitions =
        current_map->raw_transitions(isolate_, kAcquireLoad);
    Encoding encoding = GetEncoding(isolate_, raw_transitions);
    switch (encoding) {
      case kPrototypeInfo:
      case kUninitialized:
      case kMigrationTarget:
        break;
      case kWeakRef: {
        stack.emplace_back(
            Cast<Map>(raw_transitions.GetHeapObjectAssumeWeak()));
        break;
      }
      case kFullTransitionArray: {
        Tagged<TransitionArray> transitions =
            Cast<TransitionArray>(raw_transitions.GetHeapObjectAssumeStrong());
        if (transitions->HasPrototypeTransitions()) {
          Tagged<WeakFixedArray> proto_trans =
              transitions->GetPrototypeTransitions();
          int length =
              TransitionArray::NumberOfPrototypeTransitions(proto_trans);
          for (int i = 0; i < length; ++i) {
            int index = TransitionArray::kProtoTransitionHeaderSize + i;
            Tagged<MaybeObject> target = proto_trans->get(index);
            Tagged<HeapObject> heap_object;
            if (target.GetHeapObjectIfWeak(&heap_object)) {
              stack.emplace_back(Cast<Map>(heap_object));
            } else {
              DCHECK(target.IsCleared());
            }
          }
        }
        ReadOnlyRoots roots(isolate_);
        for (int i = 0; i < transitions->number_of_transitions(); ++i) {
          stack.emplace_back(transitions->GetTarget(i));
        }
        break;
      }
    }
  }
}
References v8::internal::DCHECK(), encoding(), GetEncoding(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), isolate_, v8::kAcquireLoad, kFullTransitionArray, kMigrationTarget, v8::internal::TransitionArray::kProtoTransitionHeaderSize, kPrototypeInfo, kUninitialized, kWeakRef, v8::internal::length, map_, v8::internal::TransitionArray::NumberOfPrototypeTransitions(), v8::internal::raw_transitions, v8::internal::stack, and transitions().
Friends And Related Function Documentation
MarkCompactCollector
friend class MarkCompactCollector [friend]
Definition at line 247 of file transitions.h.
TransitionArray
friend class TransitionArray [friend]
Definition at line 248 of file transitions.h.
Member Data Documentation
concurrent_access_
bool v8::internal::TransitionsAccessor::concurrent_access_ [private]
Definition at line 298 of file transitions.h.
Referenced by ForEachTransitionTo(), ForEachTransitionWithKey(), SearchSpecial(), and SearchTransition().
encoding_
Encoding v8::internal::TransitionsAccessor::encoding_ [private]
Definition at line 297 of file transitions.h.
Referenced by TransitionsAccessor().
isolate_
Isolate* v8::internal::TransitionsAccessor::isolate_ [private]
Definition at line 294 of file transitions.h.
Referenced by ExpectedTransition(), FindTransitionToField(), ForEachTransitionTo(), ForEachTransitionWithKey(), GetSimpleTargetDetails(), HasIntegrityLevelTransitionTo(), SearchSpecial(), SearchTransition(), transitions(), and TraverseTransitionTreeInternal().
kMaxNumberOfTransitions
const int v8::internal::TransitionsAccessor::kMaxNumberOfTransitions = 1024 + 512 [static]
Definition at line 153 of file transitions.h.
Referenced by CanHaveMoreTransitions(), InsertHelper(), and v8::internal::CodeStubAssembler::MaxNumberOfEntries().
map_
Tagged<Map> v8::internal::TransitionsAccessor::map_ [private]
Definition at line 295 of file transitions.h.
Referenced by GetMigrationTarget(), TransitionsAccessor(), and TraverseTransitionTreeInternal().
raw_transitions_
Tagged<MaybeObject> v8::internal::TransitionsAccessor::raw_transitions_ [private]
Definition at line 296 of file transitions.h.
Referenced by ExpectedTransition(), ForEachTransitionTo(), ForEachTransitionWithKey(), GetKey(), GetTarget(), HasSimpleTransitionTo(), SearchTransition(), and transitions().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/transitions.h
/mnt/V8SourceCode/src/objects/transitions-inl.h
/mnt/V8SourceCode/src/objects/transitions.cc