v8::Template Class Reference
The superclass of object and function templates.
#include <v8-template.h>
Public Member Functions
void Set (Local< Name > name, Local< Data > value, PropertyAttribute attributes=None)
Adds a property to each instance created by this template.
void SetPrivate (Local< Private > name, Local< Data > value, PropertyAttribute attributes=None)
void Set (Isolate *isolate, const char *name, Local< Data > value, PropertyAttribute attributes=None)
void SetAccessorProperty (Local< Name > name, Local< FunctionTemplate > getter=Local< FunctionTemplate >(), Local< FunctionTemplate > setter=Local< FunctionTemplate >(), PropertyAttribute attribute=None)
Sets an `accessor property` on the object template, see https://tc39.es/ecma262/#sec-object-type.
void SetNativeDataProperty (Local< Name > name, AccessorNameGetterCallback getter, AccessorNameSetterCallback setter=nullptr, Local< Value > data=Local< Value >(), PropertyAttribute attribute=None, SideEffectType getter_side_effect_type=SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type=SideEffectType::kHasSideEffect)
Sets a `data property` on the object template, see https://tc39.es/ecma262/#sec-object-type.
void SetLazyDataProperty (Local< Name > name, AccessorNameGetterCallback getter, Local< Value > data=Local< Value >(), PropertyAttribute attribute=None, SideEffectType getter_side_effect_type=SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type=SideEffectType::kHasSideEffect)
Like SetNativeDataProperty, but V8 will replace the native data property with a real data property on first access.
void SetIntrinsicDataProperty (Local< Name > name, Intrinsic intrinsic, PropertyAttribute attribute=None)
During template instantiation, sets the value with the intrinsic property from the correct context.
Private Member Functions
Template ()
Friends
class ObjectTemplate
class FunctionTemplate
Detailed Description
The superclass of object and function templates.
Definition at line 50 of file v8-template.h.
Constructor & Destructor Documentation
Template()
v8::Template::Template () [private]
Member Function Documentation
Set() [1/2]
void v8::Template::Set (Isolate * isolate, const char * name, Local< Data > value, PropertyAttribute attributes = None) [inline]
Definition at line 1130 of file v8-template.h.
                                                 {
  Set(String::NewFromUtf8(isolate, name, NewStringType::kInternalized)
          .ToLocalChecked(),
      value, attributes);
}
References v8::kInternalized, name, v8::String::NewFromUtf8(), Set(), and v8::internal::value.
Set() [2/2]
void v8::Template::Set (v8::Local< Name > name, v8::Local< Data > value, v8::PropertyAttribute attribute = None)
Adds a property to each instance created by this template.
The property must be defined either as a primitive value, or a template.
Definition at line 967 of file api.cc.
                                                  {
  auto templ = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = templ->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto value_obj = Utils::OpenDirectHandle(*value);
  Utils::ApiCheck(!IsJSReceiver(*value_obj) || IsTemplateInfo(*value_obj),
                  "v8::Template::Set",
                  "Invalid value, must be a primitive or a Template");
  // The template cache only performs shallow clones, if we set an
  // ObjectTemplate as a property value then we can not cache the receiver
  // template.
  if (i::IsObjectTemplateInfo(*value_obj)) {
    templ->set_is_cacheable(false);
  }
  i::ApiNatives::AddDataProperty(i_isolate, templ,
                                 Utils::OpenDirectHandle(*name), value_obj,
                                 static_cast<i::PropertyAttributes>(attribute));
}
References v8::internal::ApiNatives::AddDataProperty(), v8::Utils::ApiCheck(), name, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by Set().
SetAccessorProperty()
void v8::Template::SetAccessorProperty (Local< Name > name, v8::Local< FunctionTemplate > getter = Local<FunctionTemplate>(), v8::Local< FunctionTemplate > setter = Local<FunctionTemplate>(), v8::PropertyAttribute attribute = None)
Sets an `accessor property` on the object template, see https://tc39.es/ecma262/#sec-object-type.
Whenever the property with the given name is accessed on objects created from this ObjectTemplate the getter and setter functions are called.
Parameters
name The name of the property for which an accessor is added.
getter The callback to invoke when getting the property.
setter The callback to invoke when setting the property.
attribute The attributes of the property for which an accessor is added.
Definition at line 996 of file api.cc.
                                                                  {
  auto templ = Utils::OpenDirectHandle(this);
  auto i_isolate = templ->GetIsolateChecked();
  i::DirectHandle<i::FunctionTemplateInfo> i_getter;
  if (!getter.IsEmpty()) {
    i_getter = Utils::OpenDirectHandle(*getter);
    Utils::ApiCheck(i_getter->has_callback(i_isolate),
                    "v8::Template::SetAccessorProperty",
                    "Getter must have a call handler");
  }
  i::DirectHandle<i::FunctionTemplateInfo> i_setter;
  if (!setter.IsEmpty()) {
    i_setter = Utils::OpenDirectHandle(*setter);
    Utils::ApiCheck(i_setter->has_callback(i_isolate),
                    "v8::Template::SetAccessorProperty",
                    "Setter must have a call handler");
  }
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  DCHECK(!name.IsEmpty());
  DCHECK(!getter.IsEmpty() || !setter.IsEmpty());
  i::HandleScope scope(i_isolate);
  i::ApiNatives::AddAccessorProperty(
      i_isolate, templ, Utils::OpenDirectHandle(*name), i_getter, i_setter,
      static_cast<i::PropertyAttributes>(attribute));
}
References v8::internal::ApiNatives::AddAccessorProperty(), v8::Utils::ApiCheck(), DCHECK, v8::api_internal::IndirectHandleBase::IsEmpty(), name, v8::Utils::OpenDirectHandle(), and v8::internal::setter.
SetIntrinsicDataProperty()
void v8::Template::SetIntrinsicDataProperty (Local< Name > name, Intrinsic intrinsic, PropertyAttribute attribute = None)
During template instantiation, sets the value with the intrinsic property from the correct context.
Definition at line 1471 of file api.cc.
                                                                     {
  auto templ = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = templ->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  i::ApiNatives::AddDataProperty(i_isolate, templ,
                                 Utils::OpenDirectHandle(*name), intrinsic,
                                 static_cast<i::PropertyAttributes>(attribute));
}
References v8::internal::ApiNatives::AddDataProperty(), name, and v8::Utils::OpenDirectHandle().
SetLazyDataProperty()
void v8::Template::SetLazyDataProperty (v8::Local< Name > name, AccessorNameGetterCallback getter, v8::Local< Value > data = Local<Value>(), PropertyAttribute attribute = None, SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type = SideEffectType::kHasSideEffect)
Like SetNativeDataProperty, but V8 will replace the native data property with a real data property on first access.
Definition at line 1460 of file api.cc.
                                                                           {
  TemplateSetAccessor(
      this, name, getter, static_cast<AccessorNameSetterCallback>(nullptr),
      data, attribute, true, getter_side_effect_type, setter_side_effect_type);
}
References v8::internal::getter_side_effect_type, name, and v8::anonymous_namespace{api.cc}::TemplateSetAccessor().
SetNativeDataProperty()
void v8::Template::SetNativeDataProperty (v8::Local< Name > name, AccessorNameGetterCallback getter, AccessorNameSetterCallback setter = nullptr, v8::Local< Value > data = Local<Value>(), PropertyAttribute attribute = None, SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect, SideEffectType setter_side_effect_type = SideEffectType::kHasSideEffect)
Sets a `data property` on the object template, see https://tc39.es/ecma262/#sec-object-type.
Whenever the property with the given name is accessed on objects created from this Template the getter and setter callbacks are called instead of getting and setting the property directly on the JavaScript object. Note that in case a property is written via a `child` object, the setter will not be called according to the JavaScript specification. See https://tc39.es/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-set-p-v-receiver.
Parameters
name The name of the data property for which an accessor is added.
getter The callback to invoke when getting the property.
setter The callback to invoke when setting the property.
data A piece of data that will be passed to the getter and setter callbacks whenever they are invoked.
attribute The attributes of the property for which an accessor is added.
Definition at line 1449 of file api.cc.
                                                                             {
  TemplateSetAccessor(this, name, getter, setter, data, attribute, false,
                      getter_side_effect_type, setter_side_effect_type);
}
References v8::internal::getter_side_effect_type, name, v8::internal::setter, and v8::anonymous_namespace{api.cc}::TemplateSetAccessor().
SetPrivate()
void v8::Template::SetPrivate (v8::Local< Private > name, v8::Local< Data > value, v8::PropertyAttribute attribute = None)
Definition at line 991 of file api.cc.
                                                         {
  Set(Local<Name>::Cast(name), value, attribute);
}
References name, and v8::internal::value.
Friends And Related Function Documentation
FunctionTemplate
friend class FunctionTemplate [friend]
Definition at line 132 of file v8-template.h.
ObjectTemplate
friend class ObjectTemplate [friend]
Definition at line 131 of file v8-template.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-template.h
/mnt/V8SourceCode/src/api/api.cc