v8::internal::StoreIC Class Reference
#include <ic.h>
Public Member Functions
StoreIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Store (Handle< JSAny > object, Handle< Name > name, DirectHandle< Object > value, StoreOrigin store_origin=StoreOrigin::kNamed)
bool LookupForWrite (LookupIterator *it, DirectHandle< Object > value, StoreOrigin store_origin)
Protected Member Functions
void UpdateCaches (LookupIterator *lookup, DirectHandle< Object > value, StoreOrigin store_origin)
Private Member Functions
MaybeObjectHandle ComputeHandler (LookupIterator *lookup)
Friends
class IC
Additional Inherited Members
Detailed Description
Definition at line 264 of file ic.h.
Constructor & Destructor Documentation
StoreIC()
v8::internal::StoreIC::StoreIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind) [inline]
Definition at line 266 of file ic.h.
      : IC(isolate, vector, slot, kind) {
    DCHECK(IsAnyStore());
  }
References v8::internal::DCHECK(), and v8::internal::IC::IsAnyStore().
Member Function Documentation
ComputeHandler()
MaybeObjectHandle v8::internal::StoreIC::ComputeHandler (LookupIterator * lookup) [private]
Definition at line 2006 of file ic.cc.
                                                                {
  switch (lookup->state()) {
    case LookupIterator::TRANSITION: {
      DirectHandle<JSObject> store_target = lookup->GetStoreTarget<JSObject>();
      if (IsJSGlobalObject(*store_target)) {
        TRACE_HANDLER_STATS(isolate(), StoreIC_StoreGlobalTransitionDH);
        if (IsJSGlobalObject(*lookup_start_object_map())) {
          DCHECK(IsStoreGlobalIC());
#ifdef DEBUG
          DirectHandle<JSObject> holder = lookup->GetHolder<JSObject>();
          DCHECK_EQ(*lookup->GetReceiver(), *holder);
          DCHECK_EQ(*store_target, *holder);
#endif
          return StoreHandler::StoreGlobal(
              indirect_handle(lookup->transition_cell(), isolate()));
        }
        if (IsDefineKeyedOwnIC()) {
          // Private field can't be deleted from this global object and can't
          // be overwritten, so install slow handler in order to make store IC
          // throw if a private name already exists.
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        }
        DirectHandle<Smi> smi_handler =
            StoreHandler::StoreGlobalProxy(isolate());
        Handle<Object> handler = StoreHandler::StoreThroughPrototype(
            isolate(), lookup_start_object_map(), store_target, *smi_handler,
            MaybeObjectDirectHandle::Weak(lookup->transition_cell()));
        return MaybeObjectHandle(handler);
      }
      // Dictionary-to-fast transitions are not expected and not supported.
      DCHECK_IMPLIES(!lookup->transition_map()->is_dictionary_map(),
                     !lookup_start_object_map()->is_dictionary_map());
      DCHECK(lookup->IsCacheableTransition());
      if (IsAnyDefineOwn()) {
        return StoreHandler::StoreOwnTransition(
            isolate(), indirect_handle(lookup->transition_map(), isolate()));
      }
      return StoreHandler::StoreTransition(
          isolate(), indirect_handle(lookup->transition_map(), isolate()));
    }
    case LookupIterator::INTERCEPTOR: {
      DirectHandle<JSObject> holder = lookup->GetHolder<JSObject>();
      Tagged<InterceptorInfo> info = holder->GetNamedInterceptor();
      // If the interceptor is on the receiver...
      if (lookup->HolderIsReceiverOrHiddenPrototype() && !info->non_masking()) {
        // ...return a store interceptor Smi handler if there is a setter
        // interceptor and it's not DefineNamedOwnIC or DefineKeyedOwnIC
        // (which should call the definer)...
        if (info->has_setter() && !IsAnyDefineOwn()) {
          return MaybeObjectHandle(StoreHandler::StoreInterceptor(isolate()));
        }
        // ...otherwise return a slow-case Smi handler, which invokes the
        // definer for DefineNamedOwnIC.
        return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
      }
      // If the interceptor is a getter/query interceptor on the prototype
      // chain, return an invalidatable slow handler so it can turn fast if the
      // interceptor is masked by a regular property later.
      DCHECK(info->has_getter() || info->has_query());
      Handle<Object> handler = StoreHandler::StoreThroughPrototype(
          isolate(), lookup_start_object_map(), holder,
          *StoreHandler::StoreSlow(isolate()));
      return MaybeObjectHandle(handler);
    }
    case LookupIterator::ACCESSOR: {
      // This is currently guaranteed by checks in StoreIC::Store.
      DirectHandle<JSReceiver> receiver =
          Cast<JSReceiver>(lookup->GetReceiver());
      Handle<JSObject> holder =
          indirect_handle(lookup->GetHolder<JSObject>(), isolate());
      DCHECK(!IsAccessCheckNeeded(*receiver) || lookup->name()->IsPrivate());
      if (IsAnyDefineOwn()) {
        set_slow_stub_reason("define own with existing accessor");
        TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
        return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
      }
      if (!holder->HasFastProperties()) {
        set_slow_stub_reason("accessor on slow map");
        TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
        MaybeObjectHandle handler =
            MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        return handler;
      }
      DirectHandle<Object> accessors = lookup->GetAccessors();
      if (IsAccessorInfo(*accessors)) {
        DirectHandle<AccessorInfo> info = Cast<AccessorInfo>(accessors);
        if (!info->has_setter(isolate())) {
          set_slow_stub_reason("setter == kNullAddress");
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        }
        if (!lookup->HolderIsReceiverOrHiddenPrototype()) {
          set_slow_stub_reason("native data property in prototype chain");
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        }
        Handle<Smi> smi_handler = StoreHandler::StoreNativeDataProperty(
            isolate(), lookup->GetAccessorIndex());
        TRACE_HANDLER_STATS(isolate(), StoreIC_StoreNativeDataPropertyDH);
        if (receiver.is_identical_to(holder)) {
          return MaybeObjectHandle(smi_handler);
        }
        TRACE_HANDLER_STATS(isolate(),
                            StoreIC_StoreNativeDataPropertyOnPrototypeDH);
        return MaybeObjectHandle(StoreHandler::StoreThroughPrototype(
            isolate(), lookup_start_object_map(), holder, *smi_handler));
      } else if (IsAccessorPair(*accessors)) {
        DirectHandle<AccessorPair> accessor_pair =
            Cast<AccessorPair>(accessors);
        Handle<Object> setter(accessor_pair->setter(), isolate());
        if (!IsCallableJSFunction(*setter) &&
            !IsFunctionTemplateInfo(*setter)) {
          set_slow_stub_reason("setter not a function");
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        }
        if ((IsFunctionTemplateInfo(*setter) &&
             Cast<FunctionTemplateInfo>(*setter)->BreakAtEntry(isolate())) ||
            (IsJSFunction(*setter) &&
             Cast<JSFunction>(*setter)->shared()->BreakAtEntry(isolate()))) {
          // Do not install an IC if the api function has a breakpoint.
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        }
        CallOptimization call_optimization(isolate(), setter);
        if (call_optimization.is_simple_api_call()) {
          CallOptimization::HolderLookup holder_lookup;
          DirectHandle<JSObject> api_holder =
              call_optimization.LookupHolderOfExpectedType(
                  isolate(), lookup_start_object_map(), &holder_lookup);
          if (call_optimization.IsCompatibleReceiverMap(api_holder, holder,
                                                        holder_lookup)) {
            DirectHandle<Smi> smi_handler =
                StoreHandler::StoreApiSetter(isolate());
            DirectHandle<NativeContext> accessor_context =
                GetAccessorContext(call_optimization, holder->map(), isolate());
            TRACE_HANDLER_STATS(isolate(), StoreIC_StoreApiSetterOnPrototypeDH);
            return MaybeObjectHandle(StoreHandler::StoreThroughPrototype(
                isolate(), lookup_start_object_map(), holder, *smi_handler,
                MaybeObjectDirectHandle::Weak(
                    call_optimization.api_call_info()),
                MaybeObjectDirectHandle::Weak(accessor_context)));
          }
          set_slow_stub_reason("incompatible receiver");
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        } else if (IsFunctionTemplateInfo(*setter)) {
          set_slow_stub_reason("setter non-simple template");
          TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
          return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
        }
        DCHECK(IsCallableJSFunction(*setter));
        if (receiver.is_identical_to(holder)) {
          TRACE_HANDLER_STATS(isolate(), StoreIC_StoreAccessorDH);
          return MaybeObjectHandle::Weak(
              indirect_handle(accessor_pair, isolate()));
        }
        TRACE_HANDLER_STATS(isolate(), StoreIC_StoreAccessorOnPrototypeDH);
        return MaybeObjectHandle(StoreHandler::StoreThroughPrototype(
            isolate(), lookup_start_object_map(), holder,
            *StoreHandler::StoreAccessorFromPrototype(isolate()),
            MaybeObjectDirectHandle::Weak(setter)));
      }
      TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
      return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
    }
    case LookupIterator::DATA: {
      // This is currently guaranteed by checks in StoreIC::Store.
      DirectHandle<JSObject> receiver = Cast<JSObject>(lookup->GetReceiver());
      USE(receiver);
      DirectHandle<JSObject> holder = lookup->GetHolder<JSObject>();
      DCHECK(!IsAccessCheckNeeded(*receiver) || lookup->name()->IsPrivate());
      DCHECK_EQ(PropertyKind::kData, lookup->property_details().kind());
      if (lookup->is_dictionary_holder()) {
        if (IsJSGlobalObject(*holder)) {
          TRACE_HANDLER_STATS(isolate(), StoreIC_StoreGlobalDH);
          return MaybeObjectHandle(StoreHandler::StoreGlobal(
              indirect_handle(lookup->GetPropertyCell(), isolate())));
        }
        TRACE_HANDLER_STATS(isolate(), StoreIC_StoreNormalDH);
        DCHECK(holder.is_identical_to(receiver));
        DCHECK_IMPLIES(!V8_DICT_PROPERTY_CONST_TRACKING_BOOL,
                       lookup->constness() == PropertyConstness::kMutable);
        Handle<Smi> handler = StoreHandler::StoreNormal(isolate());
        return MaybeObjectHandle(handler);
      }
      // -------------- Elements (for TypedArrays) -------------
      if (lookup->IsElement(*holder)) {
        TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
        return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
      }
      // -------------- Fields --------------
      if (lookup->property_details().location() == PropertyLocation::kField) {
        TRACE_HANDLER_STATS(isolate(), StoreIC_StoreFieldDH);
        int descriptor = lookup->GetFieldDescriptorIndex();
        FieldIndex index = lookup->GetFieldIndex();
        if (V8_UNLIKELY(IsJSSharedStruct(*holder))) {
          return MaybeObjectHandle(StoreHandler::StoreSharedStructField(
              isolate(), descriptor, index, lookup->representation()));
        }
        PropertyConstness constness = lookup->constness();
        if (constness == PropertyConstness::kConst &&
            IsDefineNamedOwnICKind(nexus()->kind())) {
          // DefineNamedOwnICs are used for initializing object literals
          // therefore we must store the value unconditionally even to
          // VariableMode::kConst fields.
          constness = PropertyConstness::kMutable;
        }
        return MaybeObjectHandle(StoreHandler::StoreField(
            isolate(), descriptor, index, constness, lookup->representation()));
      }
      // -------------- Constant properties --------------
      DCHECK_EQ(PropertyLocation::kDescriptor,
                lookup->property_details().location());
      set_slow_stub_reason("constant property");
      TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
      return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
    }
    case LookupIterator::JSPROXY: {
      DirectHandle<JSReceiver> receiver =
          Cast<JSReceiver>(lookup->GetReceiver());
      Handle<JSProxy> holder =
          indirect_handle(lookup->GetHolder<JSProxy>(), isolate());
      // IsDefineNamedOwnIC() is true when we are defining public fields on a
      // Proxy. IsDefineKeyedOwnIC() is true when we are defining computed
      // fields in a Proxy. In these cases use the slow stub to invoke the
      // define trap.
      if (IsDefineNamedOwnIC() || IsDefineKeyedOwnIC()) {
        TRACE_HANDLER_STATS(isolate(), StoreIC_SlowStub);
        return MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
      }
      return MaybeObjectHandle(StoreHandler::StoreProxy(
          isolate(), lookup_start_object_map(), holder, receiver));
    }
    case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
    case LookupIterator::ACCESS_CHECK:
    case LookupIterator::NOT_FOUND:
    case LookupIterator::WASM_OBJECT:
    case LookupIterator::STRING_LOOKUP_START_OBJECT:
      UNREACHABLE();
  }
  return MaybeObjectHandle();
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::CallOptimization::api_call_info(), v8::internal::LookupIterator::constness(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::anonymous_namespace{ic.cc}::GetAccessorContext(), v8::internal::LookupIterator::GetAccessorIndex(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetFieldDescriptorIndex(), v8::internal::LookupIterator::GetFieldIndex(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetPropertyCell(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::GetStoreTarget(), v8::internal::LookupIterator::HolderIsReceiverOrHiddenPrototype(), v8::internal::index, v8::internal::indirect_handle(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::is_dictionary_holder(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::CallOptimization::is_simple_api_call(), v8::internal::IC::IsAnyDefineOwn(), v8::internal::LookupIterator::IsCacheableTransition(), v8::internal::CallOptimization::IsCompatibleReceiverMap(), v8::internal::IC::IsDefineKeyedOwnIC(), v8::internal::IC::IsDefineNamedOwnIC(), v8::internal::IsDefineNamedOwnICKind(), v8::internal::LookupIterator::IsElement(), v8::internal::IC::isolate(), v8::internal::IC::IsStoreGlobalIC(), v8::internal::LookupIterator::JSPROXY, v8::internal::kConst, v8::internal::kData, v8::internal::kDescriptor, v8::internal::kField, v8::internal::IC::kind(), v8::internal::PropertyDetails::kind(), v8::internal::kMutable, v8::internal::PropertyDetails::location(), v8::internal::IC::lookup_start_object_map(), v8::internal::CallOptimization::LookupHolderOfExpectedType(), v8::internal::LookupIterator::name(), v8::internal::IC::nexus(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::property_details(), v8::internal::LookupIterator::representation(), v8::internal::IC::set_slow_stub_reason(), v8::internal::setter, v8::internal::LookupIterator::state(), v8::internal::StoreHandler::StoreAccessorFromPrototype(), v8::internal::StoreHandler::StoreApiSetter(), v8::internal::StoreHandler::StoreField(), v8::internal::StoreHandler::StoreGlobal(), v8::internal::StoreHandler::StoreGlobalProxy(), v8::internal::StoreHandler::StoreInterceptor(), v8::internal::StoreHandler::StoreNativeDataProperty(), v8::internal::StoreHandler::StoreNormal(), v8::internal::StoreHandler::StoreOwnTransition(), v8::internal::StoreHandler::StoreProxy(), v8::internal::StoreHandler::StoreSharedStructField(), v8::internal::StoreHandler::StoreSlow(), v8::internal::StoreHandler::StoreThroughPrototype(), v8::internal::StoreHandler::StoreTransition(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, TRACE_HANDLER_STATS, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::transition_cell(), v8::internal::LookupIterator::transition_map(), v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), USE, V8_DICT_PROPERTY_CONST_TRACKING_BOOL, V8_UNLIKELY, v8::internal::LookupIterator::WASM_OBJECT, v8::internal::MaybeObjectHandle::Weak(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by UpdateCaches().
LookupForWrite()
bool v8::internal::StoreIC::LookupForWrite (LookupIterator * it, DirectHandle< Object > value, StoreOrigin store_origin)
Definition at line 1638 of file ic.cc.
                                                       {
  // Disable ICs for non-JSObjects for now.
  DirectHandle<Object> object = it->GetReceiver();
  if (IsJSProxy(*object)) return true;
  if (!IsJSObject(*object) && !IsWasmObject(*object)) return false;
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(object);
  DCHECK(!receiver->map()->is_deprecated());
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::TRANSITION:
        UNREACHABLE();
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::JSPROXY:
        return true;
      case LookupIterator::INTERCEPTOR: {
        DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
        Tagged<InterceptorInfo> info = holder->GetNamedInterceptor();
        if (it->HolderIsReceiverOrHiddenPrototype() || info->has_getter() ||
            info->has_query()) {
          return true;
        }
        continue;
      }
      case LookupIterator::ACCESS_CHECK:
        if (IsAccessCheckNeeded(*it->GetHolder<JSObject>())) return false;
        continue;
      case LookupIterator::ACCESSOR:
        return !it->IsReadOnly();
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return false;
      case LookupIterator::DATA: {
        if (it->IsReadOnly()) return false;
        if (IsAnyDefineOwn() && it->property_attributes() != NONE) {
          // IC doesn't support reconfiguration of property attributes,
          // so just bail out to the slow handler.
          return false;
        }
        DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
        if (receiver.is_identical_to(holder)) {
          it->PrepareForDataProperty(value);
          // The previous receiver map might just have been deprecated,
          // so reload it.
          update_lookup_start_object_map(receiver);
          return true;
        }
        // Receiver != holder.
        if (IsJSGlobalProxy(*receiver)) {
          PrototypeIterator iter(isolate(), receiver);
          return it->GetHolder<Object>().is_identical_to(
              PrototypeIterator::GetCurrent(iter));
        }
        if (it->HolderIsReceiverOrHiddenPrototype()) return false;
        if (it->ExtendingNonExtensible(receiver)) return false;
        it->PrepareTransitionToDataProperty(receiver, value, NONE,
                                            store_origin);
        return it->IsCacheableTransition();
      }
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::NOT_FOUND:
        // If we are in StoreGlobal then check if we should throw on
        // non-existent properties.
        if (IsStoreGlobalIC() &&
            (GetShouldThrow(it->isolate(), Nothing<ShouldThrow>()) ==
             ShouldThrow::kThrowOnError)) {
          // ICs typically does the store in two steps: prepare receiver for the
          // transition followed by the actual store. For global objects we
          // create a property cell when preparing for transition and install
          // this cell in the handler. In strict mode, we throw and never
          // initialize this property cell. The IC handler assumes that the
          // property cell it is holding is for a property that is existing.
          // This case violates this assumption. If we happen to invalidate this
          // property cell later, it leads to incorrect behaviour. For now just
          // use a slow stub and don't install the property cell for these
          // cases. Hopefully these cases are not frequent enough to impact
          // performance.
          //
          // TODO(mythria): If we find this to be happening often, we could
          // install a new kind of handler for non-existent properties. These
          // handlers can then miss to runtime if the value is not hole (i.e.
          // cell got invalidated) and handle these stores correctly.
          return false;
        }
        receiver = it->GetStoreTarget<JSReceiver>();
        if (it->ExtendingNonExtensible(receiver)) return false;
        it->PrepareTransitionToDataProperty(receiver, value, NONE,
                                            store_origin);
        return it->IsCacheableTransition();
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), v8::internal::LookupIterator::ExtendingNonExtensible(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), v8::internal::LookupIterator::GetStoreTarget(), v8::internal::LookupIterator::HolderIsReceiverOrHiddenPrototype(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::IC::IsAnyDefineOwn(), v8::internal::LookupIterator::IsCacheableTransition(), v8::internal::IC::isolate(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::IsReadOnly(), v8::internal::IC::IsStoreGlobalIC(), v8::internal::IsWasmObject(), v8::internal::LookupIterator::JSPROXY, v8::internal::kThrowOnError, v8::internal::LookupIterator::Next(), v8::internal::NONE, v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::PrepareForDataProperty(), v8::internal::LookupIterator::PrepareTransitionToDataProperty(), v8::internal::LookupIterator::property_attributes(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::IC::update_lookup_start_object_map(), v8::internal::value, and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by UpdateCaches().
Store()
MaybeDirectHandle< Object > v8::internal::StoreIC::Store (Handle< JSAny > object, Handle< Name > name, DirectHandle< Object > value, StoreOrigin store_origin = StoreOrigin::kNamed)
Definition at line 1864 of file ic.cc.
                                                                   {
  // TODO(verwaest): Let SetProperty do the migration, since storing a property
  // might deprecate the current map again, if value does not fit.
  if (MigrateDeprecated(isolate(), object)) {
    // KeyedStoreIC should handle DefineKeyedOwnIC with deprecated maps directly
    // instead of reusing this method.
    DCHECK(!IsDefineKeyedOwnIC());
    DCHECK(!name->IsPrivateName());
    PropertyKey key(isolate(), name);
    if (IsDefineNamedOwnIC()) {
      MAYBE_RETURN_NULL(JSReceiver::CreateDataProperty(
          isolate(), object, key, value, Nothing<ShouldThrow>()));
    } else {
      LookupIterator it(isolate(), object, key, LookupIterator::DEFAULT);
      MAYBE_RETURN_NULL(Object::SetProperty(&it, value, StoreOrigin::kNamed));
    }
    return value;
  }
  bool use_ic = (state() != NO_FEEDBACK) && v8_flags.use_ic;
  // If the object is undefined or null it's illegal to try to set any
  // properties on it; throw a TypeError in that case.
  if (IsNullOrUndefined(*object, isolate())) {
    if (use_ic) {
      // Ensure the IC state progresses.
      TRACE_HANDLER_STATS(isolate(), StoreIC_NonReceiver);
      update_lookup_start_object_map(object);
      SetCache(name, StoreHandler::StoreSlow(isolate()));
      TraceIC("StoreIC", name);
    }
    return TypeError(MessageTemplate::kNonObjectPropertyStoreWithProperty, name,
                     object);
  }
  JSObject::MakePrototypesFast(object, kStartAtPrototype, isolate());
  PropertyKey key(isolate(), name);
  LookupIterator it(
      isolate(), object, key,
      IsAnyDefineOwn() ? LookupIterator::OWN : LookupIterator::DEFAULT);
  if (name->IsPrivate()) {
    if (name->IsPrivateName()) {
      DCHECK(!IsDefineNamedOwnIC());
      Maybe<bool> can_store =
          JSReceiver::CheckPrivateNameStore(&it, IsDefineKeyedOwnIC());
      MAYBE_RETURN_NULL(can_store);
      if (!can_store.FromJust()) {
        return isolate()->factory()->undefined_value();
      }
    }
    // IC handling of private fields/symbols stores on JSProxy is not
    // supported.
    if (IsJSProxy(*object)) {
      use_ic = false;
    }
  }
  // For IsAnyDefineOwn(), we can't simply do CreateDataProperty below
  // because we need to check the attributes before UpdateCaches updates
  // the state of the LookupIterator.
  LookupIterator::State original_state = it.state();
  // We'll defer the check for JSProxy and objects with named interceptors,
  // because the defineProperty traps need to be called first if they are
  // present. We can also skip this for private names since they are not
  // bound by configurability or extensibility checks, and errors would've
  // been thrown if the private field already exists in the object.
  if (IsAnyDefineOwn() && !name->IsPrivateName() && IsJSObject(*object) &&
      !Cast<JSObject>(object)->HasNamedInterceptor()) {
    Maybe<bool> can_define = JSObject::CheckIfCanDefineAsConfigurable(
        isolate(), &it, value, Nothing<ShouldThrow>());
    MAYBE_RETURN_NULL(can_define);
    if (!can_define.FromJust()) {
      return isolate()->factory()->undefined_value();
    }
    // Restart the lookup iterator updated by CheckIfCanDefineAsConfigurable()
    // for UpdateCaches() to handle access checks.
    if (use_ic && IsAccessCheckNeeded(*object)) {
      it.Restart();
    }
  }
  if (use_ic) {
    UpdateCaches(&it, value, store_origin);
  } else if (state() == NO_FEEDBACK) {
    // Tracing IC Stats for No Feedback State.
    IsStoreGlobalIC() ? TraceIC("StoreGlobalIC", name)
                      : TraceIC("StoreIC", name);
  }
  // TODO(v8:12548): refactor DefinedNamedOwnIC and SetNamedIC as subclasses
  // of StoreIC so their logic doesn't get mixed here.
  // ES #sec-definefield
  // ES #sec-runtime-semantics-propertydefinitionevaluation
  // IsAnyDefineOwn() can be true when this method is reused by KeyedStoreIC.
  if (IsAnyDefineOwn()) {
    if (name->IsPrivateName()) {
      // We should define private fields without triggering traps or checking
      // extensibility.
      MAYBE_RETURN_NULL(
          JSReceiver::AddPrivateField(&it, value, Nothing<ShouldThrow>()));
    } else {
      MAYBE_RETURN_NULL(
          DefineOwnDataProperty(&it, original_state, Cast<JSAny>(value),
                                Nothing<ShouldThrow>(), store_origin));
    }
  } else {
    MAYBE_RETURN_NULL(Object::SetProperty(&it, value, store_origin));
  }
  return value;
}
References v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSObject::CheckIfCanDefineAsConfigurable(), v8::internal::JSReceiver::CheckPrivateNameStore(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), v8::internal::LookupIterator::DEFAULT, v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::if(), v8::internal::IC::IsAnyDefineOwn(), v8::internal::IC::IsDefineKeyedOwnIC(), v8::internal::IC::IsDefineNamedOwnIC(), v8::internal::IsNullOrUndefined(), v8::internal::IC::isolate(), v8::internal::IC::IsStoreGlobalIC(), v8::internal::key, v8::internal::kNamed, v8::internal::kStartAtPrototype, v8::internal::JSObject::MakePrototypesFast(), MAYBE_RETURN_NULL, v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated(), v8::internal::name, v8::internal::NO_FEEDBACK, v8::internal::LookupIterator::OWN, v8::internal::LookupIterator::Restart(), v8::internal::IC::SetCache(), v8::internal::Object::SetProperty(), v8::internal::IC::state(), v8::internal::LookupIterator::state(), v8::internal::StoreHandler::StoreSlow(), TRACE_HANDLER_STATS, v8::internal::IC::TraceIC(), v8::internal::IC::TypeError(), v8::internal::IC::update_lookup_start_object_map(), UpdateCaches(), v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::KeyedStoreIC::Store(), and v8::internal::StoreGlobalIC::Store().
UpdateCaches()
void v8::internal::StoreIC::UpdateCaches (LookupIterator * lookup, DirectHandle< Object > value, StoreOrigin store_origin) [protected]
Definition at line 1980 of file ic.cc.
                                                     {
  MaybeObjectHandle handler;
  if (LookupForWrite(lookup, value, store_origin)) {
    if (IsStoreGlobalIC()) {
      if (lookup->state() == LookupIterator::DATA &&
          lookup->GetReceiver().is_identical_to(lookup->GetHolder<Object>())) {
        DCHECK(IsJSGlobalObject(*lookup->GetReceiver()));
        // Now update the cell in the feedback vector.
        nexus()->ConfigurePropertyCellMode(lookup->GetPropertyCell());
        TraceIC("StoreGlobalIC", lookup->GetName());
        return;
      }
    }
    handler = ComputeHandler(lookup);
  } else {
    set_slow_stub_reason("LookupForWrite said 'false'");
    handler = MaybeObjectHandle(StoreHandler::StoreSlow(isolate()));
  }
  // Can't use {lookup->name()} because the LookupIterator might be in
  // "elements" mode for keys that are strings representing integers above
  // JSArray::kMaxIndex.
  SetCache(lookup->GetName(), handler);
  TraceIC("StoreIC", lookup->GetName());
}
References ComputeHandler(), v8::internal::FeedbackNexus::ConfigurePropertyCellMode(), v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetPropertyCell(), v8::internal::LookupIterator::GetReceiver(), v8::internal::IC::isolate(), v8::internal::IC::IsStoreGlobalIC(), LookupForWrite(), v8::internal::IC::nexus(), v8::internal::IC::set_slow_stub_reason(), v8::internal::IC::SetCache(), v8::internal::LookupIterator::state(), v8::internal::StoreHandler::StoreSlow(), v8::internal::IC::TraceIC(), and v8::internal::value.
Referenced by Store().
Friends And Related Function Documentation
IC
friend class IC [friend]
Definition at line 289 of file ic.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc