v8::internal::maglev::CheckMaps Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckMaps (uint64_t bitfield, const compiler::ZoneRefSet< Map > &maps, CheckType check_type)
CheckMaps (uint64_t bitfield, base::Vector< const compiler::MapRef > maps, CheckType check_type, Zone *zone)
const compiler::ZoneRefSet< Map > & maps () const
CheckType check_type () const
Input & receiver_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kReceiverIndex = 0
Private Types
using Base = FixedInputNodeT< 1, CheckMaps >
using CheckTypeBitField = NextBitField< CheckType, 1 >
Private Attributes
const compiler::ZoneRefSet< Map > maps_
Additional Inherited Members
Detailed Description
Definition at line 6790 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckMaps::Base = FixedInputNodeT<1, CheckMaps> [private]
Definition at line 6791 of file maglev-ir.h.
CheckTypeBitField
using v8::internal::maglev::CheckMaps::CheckTypeBitField = NextBitField<CheckType, 1> [private]
Definition at line 6821 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckMaps() [1/2]
v8::internal::maglev::CheckMaps::CheckMaps (uint64_t bitfield, const compiler::ZoneRefSet< Map > & maps, CheckType check_type) [inline], [explicit]
Definition at line 6794 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)), maps_(maps) {}
CheckMaps() [2/2]
v8::internal::maglev::CheckMaps::CheckMaps (uint64_t bitfield, base::Vector< const compiler::MapRef > maps, CheckType check_type, Zone * zone) [inline], [explicit]
Definition at line 6797 of file maglev-ir.h.
      : Base(CheckTypeBitField::update(bitfield, check_type)),
        maps_(maps.begin(), maps.end(), zone) {}
Member Function Documentation
check_type()
CheckType v8::internal::maglev::CheckMaps::check_type () const [inline]
Definition at line 6809 of file maglev-ir.h.
{ return CheckTypeBitField::decode(bitfield()); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CheckMaps::GenerateCode (MaglevAssembler * , const ProcessingState &)
maps()
const compiler::ZoneRefSet<Map>& v8::internal::maglev::CheckMaps::maps () const [inline]
Definition at line 6808 of file maglev-ir.h.
{ return maps_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::CheckMaps::options () const [inline]
Definition at line 6818 of file maglev-ir.h.
{ return std::tuple{maps_, check_type()}; }
PrintParams()
void v8::internal::maglev::CheckMaps::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8029 of file maglev-ir.cc.
                                                                       {
  os << "(";
  bool first = true;
  for (compiler::MapRef map : maps()) {
    if (first) {
      first = false;
    } else {
      os << ", ";
    }
    os << *map.object();
  }
  os << ")";
}
References maps().
receiver_input()
Input& v8::internal::maglev::CheckMaps::receiver_input () [inline]
Definition at line 6812 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::maglev::LoopOptimizationProcessor::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CheckMaps::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckMaps::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6806 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckMaps::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::EagerDeopt() | OpProperties::CanRead()
Definition at line 6803 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CheckMaps::kReceiverIndex = 0 [static], [constexpr]
Definition at line 6811 of file maglev-ir.h.
maps_
const compiler::ZoneRefSet<Map> v8::internal::maglev::CheckMaps::maps_ [private]
Definition at line 6822 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc