v8::internal::PreParserBlock Class Reference
#include <preparser.h>
Public Member Functions
void set_scope (Scope *scope)
Scope * scope () const
PreParserBlock * operator-> ()
Static Public Member Functions
static PreParserBlock Default ()
static PreParserBlock Null ()
Private Member Functions
PreParserBlock (PreParserStatement::Type type)
Private Attributes
Scope * scope_
Additional Inherited Members
Detailed Description
Definition at line 444 of file preparser.h.
Constructor & Destructor Documentation
PreParserBlock()
v8::internal::PreParserBlock::PreParserBlock (PreParserStatement::Type type) [inline], [explicit], [private]
Definition at line 459 of file preparser.h.
      : PreParserStatement(type), scope_(nullptr) {}
Referenced by Default(), and Null().
Member Function Documentation
Default()
static PreParserBlock v8::internal::PreParserBlock::Default () [inline], [static]
Definition at line 448 of file preparser.h.
                                  {
    return PreParserBlock(PreParserStatement::kUnknownStatement);
  }
References v8::internal::PreParserStatement::kUnknownStatement, and PreParserBlock().
Referenced by v8::internal::PreParser::BuildParameterInitializationBlock(), v8::internal::PreParser::CreateForEachStatementTDZ(), v8::internal::PreParserFactory::NewBlock(), and v8::internal::PreParser::RewriteCatchPattern().
Null()
static PreParserBlock v8::internal::PreParserBlock::Null () [inline], [static]
Definition at line 451 of file preparser.h.
                               {
    return PreParserBlock(PreParserStatement::kNullStatement);
  }
References v8::internal::PreParserStatement::kNullStatement, and PreParserBlock().
Referenced by v8::internal::PreParser::NullBlock(), and v8::internal::PreParser::RewriteForVarInLegacy().
operator->()
PreParserBlock* v8::internal::PreParserBlock::operator-> () [inline]
Definition at line 456 of file preparser.h.
{ return this; }
scope()
Scope* v8::internal::PreParserBlock::scope () const [inline]
Definition at line 447 of file preparser.h.
{ return scope_; }
References scope_.
Referenced by set_scope().
set_scope()
void v8::internal::PreParserBlock::set_scope (Scope * scope) [inline]
Definition at line 446 of file preparser.h.
{ scope_ = scope; }
References scope(), and scope_.
Member Data Documentation
scope_
Scope* v8::internal::PreParserBlock::scope_ [private]
Definition at line 461 of file preparser.h.
Referenced by scope(), and set_scope().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser.h