v8::internal::compiler::ConstantFoldingReducer Class Reference
#include <constant-folding-reducer.h>
Public Member Functions
ConstantFoldingReducer (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker)
~ConstantFoldingReducer () final
ConstantFoldingReducer (const ConstantFoldingReducer &)=delete
ConstantFoldingReducer & operator= (const ConstantFoldingReducer &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
JSGraph * jsgraph () const
JSHeapBroker * broker () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
Detailed Description
Definition at line 17 of file constant-folding-reducer.h.
Constructor & Destructor Documentation
ConstantFoldingReducer() [1/2]
v8::internal::compiler::ConstantFoldingReducer::ConstantFoldingReducer (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker)
Definition at line 44 of file constant-folding-reducer.cc.
    : AdvancedReducer(editor), jsgraph_(jsgraph), broker_(broker) {}
 ConstantFoldingReducer()
v8::internal::compiler::ConstantFoldingReducer::~ConstantFoldingReducer () [final], [default]
ConstantFoldingReducer() [2/2]
v8::internal::compiler::ConstantFoldingReducer::ConstantFoldingReducer (const ConstantFoldingReducer &) [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::ConstantFoldingReducer::broker () const [inline], [private]
Definition at line 32 of file constant-folding-reducer.h.
{ return broker_; }
Referenced by Reduce().
jsgraph()
JSGraph* v8::internal::compiler::ConstantFoldingReducer::jsgraph () const [inline], [private]
Definition at line 31 of file constant-folding-reducer.h.
{ return jsgraph_; }
Referenced by Reduce().
operator=()
ConstantFoldingReducer& v8::internal::compiler::ConstantFoldingReducer::operator= (const ConstantFoldingReducer &) [delete]
Reduce()
Reduction v8::internal::compiler::ConstantFoldingReducer::Reduce (Node * node) [final]
Definition at line 50 of file constant-folding-reducer.cc.
                                                   {
  if (!NodeProperties::IsConstant(node) && NodeProperties::IsTyped(node) &&
      node->op()->HasProperty(Operator::kEliminatable) &&
      node->opcode() != IrOpcode::kFinishRegion &&
      node->opcode() != IrOpcode::kTypeGuard) {
    Node* constant = TryGetConstant(jsgraph(), node, broker());
    if (constant != nullptr) {
      DCHECK(NodeProperties::IsTyped(constant));
      DCHECK_EQ(node->op()->ControlOutputCount(), 0);
      ReplaceWithValue(node, constant);
      return Replace(constant);
    }
  }
  return NoChange();
}
References broker(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::NodeProperties::IsConstant(), v8::internal::compiler::NodeProperties::IsTyped(), jsgraph(), v8::internal::compiler::Operator::kEliminatable, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), and v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant().
reducer_name()
const char* v8::internal::compiler::ConstantFoldingReducer::reducer_name () const [inline], [override]
Definition at line 26 of file constant-folding-reducer.h.
{ return "ConstantFoldingReducer"; }
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::ConstantFoldingReducer::broker_ [private]
Definition at line 35 of file constant-folding-reducer.h.
jsgraph_
JSGraph* const v8::internal::compiler::ConstantFoldingReducer::jsgraph_ [private]
Definition at line 34 of file constant-folding-reducer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/constant-folding-reducer.h
/mnt/V8SourceCode/src/compiler/constant-folding-reducer.cc