cppgc::internal::MarkingWorklists::ExternalMarkingWorklist Class Reference
Classes
struct ConditionalMutexGuard
struct ConditionalMutexGuard< AccessMode::kAtomic >
struct ConditionalMutexGuard< AccessMode::kNonAtomic >
Public Member Functions
template<AccessMode = AccessMode::kNonAtomic>
void Push (HeapObjectHeader *)
template<AccessMode = AccessMode::kNonAtomic>
bool Contains (HeapObjectHeader *)
template<AccessMode = AccessMode::kNonAtomic>
std::unordered_set< HeapObjectHeader * > Extract ()
template<AccessMode = AccessMode::kNonAtomic>
void Clear ()
template<AccessMode = AccessMode::kNonAtomic>
bool IsEmpty ()
~ExternalMarkingWorklist ()
Private Member Functions
void * operator new (size_t)=delete
void * operator new[] (size_t)=delete
void operator delete (void *)=delete
void operator delete[] (void *)=delete
Private Attributes
v8::base::Mutex lock_
std::unordered_set< HeapObjectHeader * > objects_
Detailed Description
Definition at line 20 of file marking-worklists.h.
Constructor & Destructor Documentation
 ExternalMarkingWorklist()
cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::~ExternalMarkingWorklist ()
Definition at line 27 of file marking-worklists.cc.
                                                                  {
  DCHECK(IsEmpty());
}
References DCHECK, and IsEmpty().
Member Function Documentation
Clear()
template<AccessMode = AccessMode::kNonAtomic>
void cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Clear ()
Definition at line 194 of file marking-worklists.h.
                                                    {
  ConditionalMutexGuard<mode> guard(&lock_);
  objects_.clear();
}
Referenced by cppgc::internal::MarkingWorklists::ClearForTesting(), and cppgc::internal::MarkerBase::~MarkerBase().
Contains()
template<AccessMode = AccessMode::kNonAtomic>
bool cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Contains (HeapObjectHeader * object)
Definition at line 177 of file marking-worklists.h.
                              {
  ConditionalMutexGuard<mode> guard(&lock_);
  return objects_.find(object) != objects_.end();
}
Referenced by cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer(), and cppgc::internal::MutatorMarkingState::ReTraceMarkedWeakContainer().
Extract()
template<AccessMode = AccessMode::kNonAtomic>
std::unordered_set< HeapObjectHeader * > cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Extract ()
Definition at line 185 of file marking-worklists.h.
                                                 {
  ConditionalMutexGuard<mode> guard(&lock_);
  std::unordered_set<HeapObjectHeader*> extracted;
  std::swap(extracted, objects_);
  DCHECK(objects_.empty());
  return extracted;
}
References DCHECK.
Referenced by cppgc::internal::MutatorMarkingState::FlushNotFullyConstructedObjects(), cppgc::internal::MarkerBase::MarkNotFullyConstructedObjects(), and cppgc::internal::MarkerBase::~MarkerBase().
IsEmpty()
template<AccessMode = AccessMode::kNonAtomic>
bool cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::IsEmpty ()
Definition at line 200 of file marking-worklists.h.
                                                      {
  ConditionalMutexGuard<mode> guard(&lock_);
  return objects_.empty();
}
Referenced by cppgc::internal::MarkerBase::JoinConcurrentMarkingIfNeeded(), ~ExternalMarkingWorklist(), and cppgc::internal::MarkerBase::~MarkerBase().
operator delete()
void cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::operator delete (void *) [private], [delete]
operator delete[]()
void cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::operator delete[] (void *) [private], [delete]
operator new()
void* cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::operator new (size_t) [private], [delete]
operator new[]()
void* cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::operator new[] (size_t) [private], [delete]
Push()
template<AccessMode = AccessMode::kNonAtomic>
void cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Push (HeapObjectHeader * object)
Definition at line 170 of file marking-worklists.h.
                                                                           {
  DCHECK_NOT_NULL(object);
  ConditionalMutexGuard<mode> guard(&lock_);
  objects_.insert(object);
}
References DCHECK_NOT_NULL, lock_, and objects_.
Referenced by cppgc::internal::MarkingStateBase::MarkAndPush(), cppgc::internal::BasicMarkingState::ProcessWeakContainer(), cppgc::internal::BasicMarkingState::RegisterWeakContainer(), and cppgc::internal::MarkerBase::WriteBarrierForObject().
Member Data Documentation
lock_
v8::base::Mutex cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::lock_ [private]
Definition at line 44 of file marking-worklists.h.
Referenced by Push().
objects_
std::unordered_set<HeapObjectHeader*> cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::objects_ [private]
Definition at line 45 of file marking-worklists.h.
Referenced by Push().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-worklists.h
/mnt/V8SourceCode/src/heap/cppgc/marking-worklists.cc