v8::internal::compiler::JSBinopReduction Class Reference
Public Member Functions
JSBinopReduction (JSTypedLowering *lowering, Node *node)
bool GetCompareNumberOperationHint (NumberOperationHint *hint)
bool GetCompareBigIntOperationHint (BigIntOperationHint *hint)
bool IsInternalizedStringCompareOperation ()
bool IsReceiverCompareOperation ()
bool IsReceiverOrNullOrUndefinedCompareOperation ()
bool IsStringCompareOperation ()
bool IsStringOrOddballCompareOperation ()
bool IsSymbolCompareOperation ()
bool ShouldCreateConsString ()
void CheckLeftInputToReceiver ()
void CheckLeftInputToReceiverOrNullOrUndefined ()
void CheckInputsToReceiver ()
void CheckInputsToReceiverOrNullOrUndefined ()
void CheckLeftInputToSymbol ()
void CheckInputsToSymbol ()
void CheckInputsToString ()
void CheckInputsToStringOrOddball ()
void CheckInputsToStringOrStringWrapper ()
void CheckInputsToInternalizedString ()
void ConvertInputsToNumber ()
void ConvertInputsToUI32 (Signedness left_signedness, Signedness right_signedness)
void SwapInputs ()
Reduction ChangeToPureOperator (const Operator *op, Type type=Type::Any())
Reduction ChangeToSpeculativeOperator (const Operator *op, Type upper_bound)
const Operator * NumberOp ()
bool LeftInputIs (Type t)
bool RightInputIs (Type t)
bool OneInputIs (Type t)
bool BothInputsAre (Type t)
bool BothInputsMaybe (Type t)
bool OneInputCannotBe (Type t)
bool NeitherInputCanBe (Type t)
BinaryOperationHint GetBinaryOperationHint (Node *node) const
Node * effect ()
Node * control ()
Node * context ()
Node * left ()
Node * right ()
Type left_type ()
Type right_type ()
Type type ()
SimplifiedOperatorBuilder * simplified ()
TFGraph * graph () const
JSGraph * jsgraph ()
Isolate * isolate ()
JSOperatorBuilder * javascript ()
CommonOperatorBuilder * common ()
Zone * zone () const
Private Member Functions
Node * ConvertPlainPrimitiveToNumber (Node *node)
Node * ConvertToUI32 (Node *node, Signedness signedness)
CompareOperationHint GetCompareOperationHint (Node *node) const
void update_effect (Node *effect)
Private Attributes
JSTypedLowering * lowering_
Node * node_
Detailed Description
Definition at line 54 of file js-typed-lowering.cc.
Constructor & Destructor Documentation
JSBinopReduction()
v8::internal::compiler::JSBinopReduction::JSBinopReduction (JSTypedLowering * lowering, Node * node) [inline]
Definition at line 56 of file js-typed-lowering.cc.
      : lowering_(lowering), node_(node) {}
Member Function Documentation
BothInputsAre()
bool v8::internal::compiler::JSBinopReduction::BothInputsAre (Type t) [inline]
Definition at line 464 of file js-typed-lowering.cc.
{ return LeftInputIs(t) && RightInputIs(t); }
References LeftInputIs(), and RightInputIs().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceInt32Binop(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSComparison(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), v8::internal::compiler::JSTypedLowering::ReduceNumberBinop(), v8::internal::compiler::JSTypedLowering::ReduceUI32Shift(), and ShouldCreateConsString().
BothInputsMaybe()
bool v8::internal::compiler::JSBinopReduction::BothInputsMaybe (Type t) [inline]
Definition at line 466 of file js-typed-lowering.cc.
                               {
    return left_type().Maybe(t) && right_type().Maybe(t);
  }
References left_type(), v8::internal::compiler::Type::Maybe(), and right_type().
Referenced by IsInternalizedStringCompareOperation(), IsReceiverCompareOperation(), IsReceiverOrNullOrUndefinedCompareOperation(), IsStringCompareOperation(), IsStringOrOddballCompareOperation(), and IsSymbolCompareOperation().
ChangeToPureOperator()
Reduction v8::internal::compiler::JSBinopReduction::ChangeToPureOperator (const Operator * op, Type type = Type::Any()) [inline]
Definition at line 361 of file js-typed-lowering.cc.
                                                                            {
    DCHECK_EQ(0, op->EffectInputCount());
    DCHECK_EQ(false, OperatorProperties::HasContextInput(op));
    DCHECK_EQ(0, op->ControlInputCount());
    DCHECK_EQ(2, op->ValueInputCount());
    // Remove the effects from the node, and update its effect/control usages.
    if (node_->op()->EffectInputCount() > 0) {
      lowering_->RelaxEffectsAndControls(node_);
    }
    // Remove the inputs corresponding to context, effect, and control.
    NodeProperties::RemoveNonValueInputs(node_);
    // Remove the feedback vector input, if applicable.
    if (JSOperator::IsBinaryWithFeedback(node_->opcode())) {
      node_->RemoveInput(JSBinaryOpNode::FeedbackVectorIndex());
    }
    // Finally, update the operator to the new one.
    NodeProperties::ChangeOp(node_, op);
    // TODO(jarin): Replace the explicit typing hack with a call to some method
    // that encapsulates changing the operator and re-typing.
    Type node_type = NodeProperties::GetType(node_);
    NodeProperties::SetType(node_, Type::Intersect(node_type, type, zone()));
    return lowering_->Changed(node_);
  }
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Operator::ControlInputCount(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::JSOperator::IsBinaryWithFeedback(), lowering_, node_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::RemoveNonValueInputs(), v8::internal::compiler::NodeProperties::SetType(), type(), v8::internal::compiler::Operator::ValueInputCount(), and zone().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceInt32Binop(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSTypedLowering::ReduceJSComparison(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), v8::internal::compiler::JSTypedLowering::ReduceNumberBinop(), and v8::internal::compiler::JSTypedLowering::ReduceUI32Shift().
ChangeToSpeculativeOperator()
Reduction v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator (const Operator * op, Type upper_bound) [inline]
Definition at line 388 of file js-typed-lowering.cc.
                                                                              {
    DCHECK_EQ(1, op->EffectInputCount());
    DCHECK_EQ(1, op->EffectOutputCount());
    DCHECK_EQ(false, OperatorProperties::HasContextInput(op));
    DCHECK_EQ(1, op->ControlInputCount());
    DCHECK_EQ(0, op->ControlOutputCount());
    DCHECK_EQ(0, OperatorProperties::GetFrameStateInputCount(op));
    DCHECK_EQ(2, op->ValueInputCount());
    DCHECK_EQ(1, node_->op()->EffectInputCount());
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    DCHECK_EQ(1, node_->op()->ControlInputCount());
    // Reconnect the control output to bypass the IfSuccess node and
    // possibly disconnect from the IfException node.
    lowering_->RelaxControls(node_);
    // Remove the frame state and the context.
    if (OperatorProperties::HasFrameStateInput(node_->op())) {
      node_->RemoveInput(NodeProperties::FirstFrameStateIndex(node_));
    }
    node_->RemoveInput(NodeProperties::FirstContextIndex(node_));
    // Remove the feedback vector input, if applicable.
    if (JSOperator::IsBinaryWithFeedback(node_->opcode())) {
      node_->RemoveInput(JSBinaryOpNode::FeedbackVectorIndex());
    }
    // Finally, update the operator to the new one.
    NodeProperties::ChangeOp(node_, op);
    // Update the type to number.
    Type node_type = NodeProperties::GetType(node_);
    NodeProperties::SetType(node_,
                            Type::Intersect(node_type, upper_bound, zone()));
    return lowering_->Changed(node_);
  }
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::NodeProperties::FirstContextIndex(), v8::internal::compiler::NodeProperties::FirstFrameStateIndex(), v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::JSOperator::IsBinaryWithFeedback(), lowering_, node_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::compiler::Operator::ValueInputCount(), and zone().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
CheckInputsToInternalizedString()
void v8::internal::compiler::JSBinopReduction::CheckInputsToInternalizedString () [inline]
Definition at line 323 of file js-typed-lowering.cc.
                                         {
    if (!left_type().Is(Type::UniqueName())) {
      Node* left_input = graph()->NewNode(
          simplified()->CheckInternalizedString(), left(), effect(), control());
      node_->ReplaceInput(0, left_input);
      update_effect(left_input);
    }
    if (!right_type().Is(Type::UniqueName())) {
      Node* right_input =
          graph()->NewNode(simplified()->CheckInternalizedString(), right(),
                           effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References control(), effect(), graph(), v8::internal::Is(), left(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
CheckInputsToReceiver()
void v8::internal::compiler::JSBinopReduction::CheckInputsToReceiver () [inline]
Definition at line 212 of file js-typed-lowering.cc.
                               {
    if (!left_type().Is(Type::Receiver())) {
      CheckLeftInputToReceiver();
    }
    if (!right_type().Is(Type::Receiver())) {
      Node* right_input = graph()->NewNode(simplified()->CheckReceiver(),
                                           right(), effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References CheckLeftInputToReceiver(), control(), effect(), graph(), v8::internal::Is(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual().
CheckInputsToReceiverOrNullOrUndefined()
void v8::internal::compiler::JSBinopReduction::CheckInputsToReceiverOrNullOrUndefined () [inline]
Definition at line 227 of file js-typed-lowering.cc.
                                                {
    if (!left_type().Is(Type::ReceiverOrNullOrUndefined())) {
      CheckLeftInputToReceiverOrNullOrUndefined();
    }
    if (!right_type().Is(Type::ReceiverOrNullOrUndefined())) {
      Node* right_input =
          graph()->NewNode(simplified()->CheckReceiverOrNullOrUndefined(),
                           right(), effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References CheckLeftInputToReceiverOrNullOrUndefined(), control(), effect(), graph(), v8::internal::Is(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual().
CheckInputsToString()
void v8::internal::compiler::JSBinopReduction::CheckInputsToString () [inline]
Definition at line 266 of file js-typed-lowering.cc.
                             {
    if (!left_type().Is(Type::String())) {
      Node* left_input =
          graph()->NewNode(simplified()->CheckString(FeedbackSource()), left(),
                           effect(), control());
      node_->ReplaceInput(0, left_input);
      update_effect(left_input);
    }
    if (!right_type().Is(Type::String())) {
      Node* right_input =
          graph()->NewNode(simplified()->CheckString(FeedbackSource()), right(),
                           effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References control(), effect(), graph(), v8::internal::Is(), left(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSComparison(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
CheckInputsToStringOrOddball()
void v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrOddball () [inline]
Definition at line 283 of file js-typed-lowering.cc.
                                      {
    if (!left_type().Is(Type::StringOrOddball())) {
      Node* left_input =
          graph()->NewNode(simplified()->CheckStringOrOddball(FeedbackSource()),
                           left(), effect(), control());
      node_->ReplaceInput(0, left_input);
      update_effect(left_input);
    }
    if (!right_type().Is(Type::StringOrOddball())) {
      Node* right_input =
          graph()->NewNode(simplified()->CheckStringOrOddball(FeedbackSource()),
                           right(), effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References control(), effect(), graph(), v8::internal::Is(), left(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
CheckInputsToStringOrStringWrapper()
void v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrStringWrapper () [inline]
Definition at line 303 of file js-typed-lowering.cc.
                                            {
    if (!left_type().Is(Type::StringOrStringWrapper())) {
      Node* left_input = graph()->NewNode(
          simplified()->CheckStringOrStringWrapper(FeedbackSource()), left(),
          effect(), control());
      node_->ReplaceInput(0, left_input);
      update_effect(left_input);
    }
    if (!right_type().Is(Type::StringOrStringWrapper())) {
      Node* right_input = graph()->NewNode(
          simplified()->CheckStringOrStringWrapper(FeedbackSource()), right(),
          effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References control(), effect(), graph(), v8::internal::Is(), left(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
CheckInputsToSymbol()
void v8::internal::compiler::JSBinopReduction::CheckInputsToSymbol () [inline]
Definition at line 251 of file js-typed-lowering.cc.
                             {
    if (!left_type().Is(Type::Symbol())) {
      CheckLeftInputToSymbol();
    }
    if (!right_type().Is(Type::Symbol())) {
      Node* right_input = graph()->NewNode(simplified()->CheckSymbol(), right(),
                                           effect(), control());
      node_->ReplaceInput(1, right_input);
      update_effect(right_input);
    }
  }
References CheckLeftInputToSymbol(), control(), effect(), graph(), v8::internal::Is(), left_type(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), right_type(), simplified(), and update_effect().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual().
CheckLeftInputToReceiver()
void v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiver () [inline]
Definition at line 193 of file js-typed-lowering.cc.
                                  {
    Node* left_input = graph()->NewNode(simplified()->CheckReceiver(), left(),
                                        effect(), control());
    node_->ReplaceInput(0, left_input);
    update_effect(left_input);
  }
References control(), effect(), graph(), left(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), simplified(), and update_effect().
Referenced by CheckInputsToReceiver(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
CheckLeftInputToReceiverOrNullOrUndefined()
void v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiverOrNullOrUndefined () [inline]
Definition at line 201 of file js-typed-lowering.cc.
                                                   {
    Node* left_input =
        graph()->NewNode(simplified()->CheckReceiverOrNullOrUndefined(), left(),
                         effect(), control());
    node_->ReplaceInput(0, left_input);
    update_effect(left_input);
  }
References control(), effect(), graph(), left(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), simplified(), and update_effect().
Referenced by CheckInputsToReceiverOrNullOrUndefined(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
CheckLeftInputToSymbol()
void v8::internal::compiler::JSBinopReduction::CheckLeftInputToSymbol () [inline]
Definition at line 241 of file js-typed-lowering.cc.
                                {
    Node* left_input = graph()->NewNode(simplified()->CheckSymbol(), left(),
                                        effect(), control());
    node_->ReplaceInput(0, left_input);
    update_effect(left_input);
  }
References control(), effect(), graph(), left(), v8::internal::compiler::TFGraph::NewNode(), node_, v8::internal::compiler::Node::ReplaceInput(), simplified(), and update_effect().
Referenced by CheckInputsToSymbol(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
common()
CommonOperatorBuilder* v8::internal::compiler::JSBinopReduction::common () [inline]
Definition at line 497 of file js-typed-lowering.cc.
{ return jsgraph()->common(); }
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
context()
Node* v8::internal::compiler::JSBinopReduction::context () [inline]
Definition at line 485 of file js-typed-lowering.cc.
{ return NodeProperties::GetContextInput(node_); }
References v8::internal::compiler::NodeProperties::GetContextInput(), and node_.
control()
Node* v8::internal::compiler::JSBinopReduction::control () [inline]
Definition at line 484 of file js-typed-lowering.cc.
{ return NodeProperties::GetControlInput(node_); }
References v8::internal::compiler::NodeProperties::GetControlInput(), and node_.
Referenced by CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), CheckLeftInputToSymbol(), and v8::internal::compiler::JSTypedLowering::ReduceJSEqual().
ConvertInputsToNumber()
void v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber () [inline]
Definition at line 339 of file js-typed-lowering.cc.
                               {
    DCHECK(left_type().Is(Type::PlainPrimitive()));
    DCHECK(right_type().Is(Type::PlainPrimitive()));
    node_->ReplaceInput(0, ConvertPlainPrimitiveToNumber(left()));
    node_->ReplaceInput(1, ConvertPlainPrimitiveToNumber(right()));
  }
References ConvertPlainPrimitiveToNumber(), v8::internal::DCHECK(), v8::internal::Is(), left(), left_type(), node_, v8::internal::compiler::Node::ReplaceInput(), right(), and right_type().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceInt32Binop(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSTypedLowering::ReduceJSComparison(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSTypedLowering::ReduceNumberBinop(), and v8::internal::compiler::JSTypedLowering::ReduceUI32Shift().
ConvertInputsToUI32()
void v8::internal::compiler::JSBinopReduction::ConvertInputsToUI32 (Signedness left_signedness, Signedness right_signedness) [inline]
Definition at line 346 of file js-typed-lowering.cc.
                                                        {
    node_->ReplaceInput(0, ConvertToUI32(left(), left_signedness));
    node_->ReplaceInput(1, ConvertToUI32(right(), right_signedness));
  }
References ConvertToUI32(), left(), node_, v8::internal::compiler::Node::ReplaceInput(), and right().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceInt32Binop(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), and v8::internal::compiler::JSTypedLowering::ReduceUI32Shift().
ConvertPlainPrimitiveToNumber()
Node* v8::internal::compiler::JSBinopReduction::ConvertPlainPrimitiveToNumber (Node * node) [inline], [private]
Definition at line 504 of file js-typed-lowering.cc.
                                                  {
    DCHECK(NodeProperties::GetType(node).Is(Type::PlainPrimitive()));
    // Avoid inserting too many eager ToNumber() operations.
    Reduction const reduction = lowering_->ReduceJSToNumberInput(node);
    if (reduction.Changed()) return reduction.replacement();
    if (NodeProperties::GetType(node).Is(Type::Number())) {
      return node;
    }
    return graph()->NewNode(simplified()->PlainPrimitiveToNumber(), node);
  }
References v8::internal::compiler::Reduction::Changed(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::Is(), lowering_, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::Reduction::replacement(), and simplified().
Referenced by ConvertInputsToNumber().
ConvertToUI32()
Node* v8::internal::compiler::JSBinopReduction::ConvertToUI32 (Node * node, Signedness signedness) [inline], [private]
Definition at line 515 of file js-typed-lowering.cc.
                                                         {
    // Avoid introducing too many eager NumberToXXnt32() operations.
    Type type = NodeProperties::GetType(node);
    if (signedness == kSigned) {
      if (!type.Is(Type::Signed32())) {
        node = graph()->NewNode(simplified()->NumberToInt32(), node);
      }
    } else {
      DCHECK_EQ(kUnsigned, signedness);
      if (!type.Is(Type::Unsigned32())) {
        node = graph()->NewNode(simplified()->NumberToUint32(), node);
      }
    }
    return node;
  }
References DCHECK_EQ, v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::compiler::Type::Is(), v8::internal::compiler::kSigned, v8::internal::compiler::kUnsigned, v8::internal::compiler::TFGraph::NewNode(), v8::internal::NumberToInt32(), v8::internal::NumberToUint32(), simplified(), and type().
Referenced by ConvertInputsToUI32().
effect()
Node* v8::internal::compiler::JSBinopReduction::effect () [inline]
Definition at line 483 of file js-typed-lowering.cc.
{ return NodeProperties::GetEffectInput(node_); }
References v8::internal::compiler::NodeProperties::GetEffectInput(), and node_.
Referenced by CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), CheckLeftInputToSymbol(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and update_effect().
GetBinaryOperationHint()
BinaryOperationHint v8::internal::compiler::JSBinopReduction::GetBinaryOperationHint (Node * node) const [inline]
Definition at line 478 of file js-typed-lowering.cc.
                                                               {
    const FeedbackParameter& p = FeedbackParameterOf(node->op());
    return lowering_->broker()->GetFeedbackForBinaryOperation(p.feedback());
  }
References v8::internal::compiler::JSTypedLowering::broker(), v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::JSHeapBroker::GetFeedbackForBinaryOperation(), lowering_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), and ShouldCreateConsString().
GetCompareBigIntOperationHint()
bool v8::internal::compiler::JSBinopReduction::GetCompareBigIntOperationHint (BigIntOperationHint * hint) [inline]
Definition at line 89 of file js-typed-lowering.cc.
                                                                {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    switch (GetCompareOperationHint(node_)) {
      case CompareOperationHint::kSignedSmall:
      case CompareOperationHint::kNumber:
      case CompareOperationHint::kNumberOrBoolean:
      case CompareOperationHint::kNumberOrOddball:
      case CompareOperationHint::kAny:
      case CompareOperationHint::kNone:
      case CompareOperationHint::kString:
      case CompareOperationHint::kSymbol:
      case CompareOperationHint::kReceiver:
      case CompareOperationHint::kReceiverOrNullOrUndefined:
      case CompareOperationHint::kStringOrOddball:
      case CompareOperationHint::kInternalizedString:
        return false;
      case CompareOperationHint::kBigInt:
        *hint = BigIntOperationHint::kBigInt;
        return true;
      case CompareOperationHint::kBigInt64:
        *hint = BigIntOperationHint::kBigInt64;
        return true;
    }
    UNREACHABLE();
  }
References DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kAny, v8::internal::compiler::kBigInt, v8::internal::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBigInt64, v8::internal::kInternalizedString, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrBoolean, v8::internal::kNumberOrOddball, v8::internal::kReceiver, v8::internal::kReceiverOrNullOrUndefined, v8::internal::kSignedSmall, v8::internal::kString, v8::internal::kStringOrOddball, v8::internal::kSymbol, node_, v8::internal::compiler::Node::op(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
GetCompareNumberOperationHint()
bool v8::internal::compiler::JSBinopReduction::GetCompareNumberOperationHint (NumberOperationHint * hint) [inline]
Definition at line 59 of file js-typed-lowering.cc.
                                                                {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    switch (GetCompareOperationHint(node_)) {
      case CompareOperationHint::kSignedSmall:
        *hint = NumberOperationHint::kSignedSmall;
        return true;
      case CompareOperationHint::kNumber:
        *hint = NumberOperationHint::kNumber;
        return true;
      case CompareOperationHint::kNumberOrBoolean:
        *hint = NumberOperationHint::kNumberOrBoolean;
        return true;
      case CompareOperationHint::kNumberOrOddball:
        *hint = NumberOperationHint::kNumberOrOddball;
        return true;
      case CompareOperationHint::kAny:
      case CompareOperationHint::kNone:
      case CompareOperationHint::kString:
      case CompareOperationHint::kSymbol:
      case CompareOperationHint::kBigInt:
      case CompareOperationHint::kBigInt64:
      case CompareOperationHint::kReceiver:
      case CompareOperationHint::kReceiverOrNullOrUndefined:
      case CompareOperationHint::kStringOrOddball:
      case CompareOperationHint::kInternalizedString:
        break;
    }
    return false;
  }
References DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kInternalizedString, v8::internal::kNone, v8::internal::compiler::kNumber, v8::internal::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::kNumberOrOddball, v8::internal::kReceiver, v8::internal::kReceiverOrNullOrUndefined, v8::internal::compiler::kSignedSmall, v8::internal::kSignedSmall, v8::internal::kString, v8::internal::kStringOrOddball, v8::internal::kSymbol, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
GetCompareOperationHint()
CompareOperationHint v8::internal::compiler::JSBinopReduction::GetCompareOperationHint (Node * node) const [inline], [private]
Definition at line 531 of file js-typed-lowering.cc.
                                                                 {
    const FeedbackParameter& p = FeedbackParameterOf(node->op());
    return lowering_->broker()->GetFeedbackForCompareOperation(p.feedback());
  }
References v8::internal::compiler::JSTypedLowering::broker(), v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::FeedbackParameterOf(), v8::internal::compiler::JSHeapBroker::GetFeedbackForCompareOperation(), lowering_, and v8::internal::compiler::Node::op().
Referenced by GetCompareBigIntOperationHint(), GetCompareNumberOperationHint(), IsInternalizedStringCompareOperation(), IsReceiverCompareOperation(), IsReceiverOrNullOrUndefinedCompareOperation(), IsStringCompareOperation(), IsStringOrOddballCompareOperation(), and IsSymbolCompareOperation().
graph()
TFGraph* v8::internal::compiler::JSBinopReduction::graph () const [inline]
Definition at line 493 of file js-typed-lowering.cc.
{ return lowering_->graph(); }
References v8::internal::compiler::JSTypedLowering::graph(), and lowering_.
Referenced by CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), CheckLeftInputToSymbol(), ConvertPlainPrimitiveToNumber(), ConvertToUI32(), and zone().
IsInternalizedStringCompareOperation()
bool v8::internal::compiler::JSBinopReduction::IsInternalizedStringCompareOperation () [inline]
Definition at line 115 of file js-typed-lowering.cc.
                                              {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    return (GetCompareOperationHint(node_) ==
            CompareOperationHint::kInternalizedString) &&
           BothInputsMaybe(Type::InternalizedString());
  }
References BothInputsMaybe(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kInternalizedString, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
isolate()
Isolate* v8::internal::compiler::JSBinopReduction::isolate () [inline]
Definition at line 495 of file js-typed-lowering.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
IsReceiverCompareOperation()
bool v8::internal::compiler::JSBinopReduction::IsReceiverCompareOperation () [inline]
Definition at line 122 of file js-typed-lowering.cc.
                                    {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    return (GetCompareOperationHint(node_) ==
            CompareOperationHint::kReceiver) &&
           BothInputsMaybe(Type::Receiver());
  }
References BothInputsMaybe(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kReceiver, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
IsReceiverOrNullOrUndefinedCompareOperation()
bool v8::internal::compiler::JSBinopReduction::IsReceiverOrNullOrUndefinedCompareOperation () [inline]
Definition at line 129 of file js-typed-lowering.cc.
                                                     {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    return (GetCompareOperationHint(node_) ==
            CompareOperationHint::kReceiverOrNullOrUndefined) &&
           BothInputsMaybe(Type::ReceiverOrNullOrUndefined());
  }
References BothInputsMaybe(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kReceiverOrNullOrUndefined, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
IsStringCompareOperation()
bool v8::internal::compiler::JSBinopReduction::IsStringCompareOperation () [inline]
Definition at line 136 of file js-typed-lowering.cc.
                                  {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    return (GetCompareOperationHint(node_) == CompareOperationHint::kString) &&
           BothInputsMaybe(Type::String());
  }
References BothInputsMaybe(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kString, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSComparison(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
IsStringOrOddballCompareOperation()
bool v8::internal::compiler::JSBinopReduction::IsStringOrOddballCompareOperation () [inline]
Definition at line 142 of file js-typed-lowering.cc.
                                           {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    return (GetCompareOperationHint(node_) ==
            CompareOperationHint::kStringOrOddball) &&
           BothInputsMaybe(Type::StringOrOddball());
  }
References BothInputsMaybe(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kStringOrOddball, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
IsSymbolCompareOperation()
bool v8::internal::compiler::JSBinopReduction::IsSymbolCompareOperation () [inline]
Definition at line 149 of file js-typed-lowering.cc.
                                  {
    DCHECK_EQ(1, node_->op()->EffectOutputCount());
    return (GetCompareOperationHint(node_) == CompareOperationHint::kSymbol) &&
           BothInputsMaybe(Type::Symbol());
  }
References BothInputsMaybe(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), GetCompareOperationHint(), v8::internal::kSymbol, node_, and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
javascript()
JSOperatorBuilder* v8::internal::compiler::JSBinopReduction::javascript () [inline]
Definition at line 496 of file js-typed-lowering.cc.
{ return lowering_->javascript(); }
References v8::internal::compiler::JSTypedLowering::javascript(), and lowering_.
jsgraph()
JSGraph* v8::internal::compiler::JSBinopReduction::jsgraph () [inline]
Definition at line 494 of file js-typed-lowering.cc.
{ return lowering_->jsgraph(); }
References v8::internal::compiler::JSTypedLowering::jsgraph(), and lowering_.
Referenced by common(), and isolate().
left()
Node* v8::internal::compiler::JSBinopReduction::left () [inline]
Definition at line 486 of file js-typed-lowering.cc.
{ return NodeProperties::GetValueInput(node_, 0); }
References v8::internal::compiler::NodeProperties::GetValueInput(), and node_.
Referenced by CheckInputsToInternalizedString(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), CheckLeftInputToSymbol(), ConvertInputsToNumber(), ConvertInputsToUI32(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), and SwapInputs().
left_type()
Type v8::internal::compiler::JSBinopReduction::left_type () [inline]
Definition at line 488 of file js-typed-lowering.cc.
{ return NodeProperties::GetType(node_->InputAt(0)); }
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), and node_.
Referenced by BothInputsMaybe(), CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), ConvertInputsToNumber(), LeftInputIs(), NeitherInputCanBe(), and OneInputCannotBe().
LeftInputIs()
bool v8::internal::compiler::JSBinopReduction::LeftInputIs (Type t) [inline]
Definition at line 458 of file js-typed-lowering.cc.
{ return left_type().Is(t); }
References v8::internal::compiler::Type::Is(), and left_type().
Referenced by BothInputsAre(), OneInputIs(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), and v8::internal::compiler::JSTypedLowering::ReduceJSEqual().
NeitherInputCanBe()
bool v8::internal::compiler::JSBinopReduction::NeitherInputCanBe (Type t) [inline]
Definition at line 474 of file js-typed-lowering.cc.
                                 {
    return !left_type().Maybe(t) && !right_type().Maybe(t);
  }
References left_type(), v8::internal::compiler::Type::Maybe(), and right_type().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
NumberOp()
const Operator* v8::internal::compiler::JSBinopReduction::NumberOp () [inline]
Definition at line 426 of file js-typed-lowering.cc.
                             {
    switch (node_->opcode()) {
      case IrOpcode::kJSAdd:
        return simplified()->NumberAdd();
      case IrOpcode::kJSSubtract:
        return simplified()->NumberSubtract();
      case IrOpcode::kJSMultiply:
        return simplified()->NumberMultiply();
      case IrOpcode::kJSDivide:
        return simplified()->NumberDivide();
      case IrOpcode::kJSModulus:
        return simplified()->NumberModulus();
      case IrOpcode::kJSExponentiate:
        return simplified()->NumberPow();
      case IrOpcode::kJSBitwiseAnd:
        return simplified()->NumberBitwiseAnd();
      case IrOpcode::kJSBitwiseOr:
        return simplified()->NumberBitwiseOr();
      case IrOpcode::kJSBitwiseXor:
        return simplified()->NumberBitwiseXor();
      case IrOpcode::kJSShiftLeft:
        return simplified()->NumberShiftLeft();
      case IrOpcode::kJSShiftRight:
        return simplified()->NumberShiftRight();
      case IrOpcode::kJSShiftRightLogical:
        return simplified()->NumberShiftRightLogical();
      default:
        break;
    }
    UNREACHABLE();
  }
References node_, v8::internal::compiler::SimplifiedOperatorBuilder::NumberAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberBitwiseAnd(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberBitwiseOr(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberBitwiseXor(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberDivide(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberModulus(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberMultiply(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberPow(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberShiftLeft(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberShiftRight(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberShiftRightLogical(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberSubtract(), v8::internal::compiler::Node::opcode(), simplified(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceInt32Binop(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSTypedLowering::ReduceNumberBinop(), and v8::internal::compiler::JSTypedLowering::ReduceUI32Shift().
OneInputCannotBe()
bool v8::internal::compiler::JSBinopReduction::OneInputCannotBe (Type t) [inline]
Definition at line 470 of file js-typed-lowering.cc.
                                {
    return !left_type().Maybe(t) || !right_type().Maybe(t);
  }
References left_type(), v8::internal::compiler::Type::Maybe(), and right_type().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSComparison().
OneInputIs()
bool v8::internal::compiler::JSBinopReduction::OneInputIs (Type t) [inline]
Definition at line 462 of file js-typed-lowering.cc.
{ return LeftInputIs(t) || RightInputIs(t); }
References LeftInputIs(), and RightInputIs().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), and ShouldCreateConsString().
right()
Node* v8::internal::compiler::JSBinopReduction::right () [inline]
Definition at line 487 of file js-typed-lowering.cc.
{ return NodeProperties::GetValueInput(node_, 1); }
References v8::internal::compiler::NodeProperties::GetValueInput(), and node_.
Referenced by CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), ConvertInputsToNumber(), ConvertInputsToUI32(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), and SwapInputs().
right_type()
Type v8::internal::compiler::JSBinopReduction::right_type () [inline]
Definition at line 489 of file js-typed-lowering.cc.
{ return NodeProperties::GetType(node_->InputAt(1)); }
References v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::InputAt(), and node_.
Referenced by BothInputsMaybe(), CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), ConvertInputsToNumber(), NeitherInputCanBe(), OneInputCannotBe(), and RightInputIs().
RightInputIs()
bool v8::internal::compiler::JSBinopReduction::RightInputIs (Type t) [inline]
Definition at line 460 of file js-typed-lowering.cc.
{ return right_type().Is(t); }
References v8::internal::compiler::Type::Is(), and right_type().
Referenced by BothInputsAre(), OneInputIs(), and v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
ShouldCreateConsString()
bool v8::internal::compiler::JSBinopReduction::ShouldCreateConsString () [inline]
Definition at line 158 of file js-typed-lowering.cc.
                                {
    DCHECK_EQ(IrOpcode::kJSAdd, node_->opcode());
    DCHECK(OneInputIs(Type::String()));
    if (node_->InputAt(1)->opcode() == IrOpcode::kNewConsString) {
      // If the right hand side is a ConsString, then we can create a
      // ConsString. This doesn't work with the left hand side, since the right
      // hand side of a ConsString cannot be the empty string except when the
      // left hand side is a SeqString or External string, but we don't know
      // that here.
      return true;
    }
    if (BothInputsAre(Type::String()) ||
        GetBinaryOperationHint(node_) == BinaryOperationHint::kString) {
      HeapObjectBinopMatcher m(node_);
      JSHeapBroker* broker = lowering_->broker();
      if (m.right().HasResolvedValue() && m.right().Ref(broker).IsString()) {
        StringRef right_string = m.right().Ref(broker).AsString();
        if (right_string.length() >= ConsString::kMinLength) return true;
      }
      if (m.left().HasResolvedValue() && m.left().Ref(broker).IsString()) {
        StringRef left_string = m.left().Ref(broker).AsString();
        if (left_string.length() >= ConsString::kMinLength) {
          // The invariant for ConsString requires the left hand side to be
          // a sequential or external string if the right hand side is the
          // empty string. Since we don't know anything about the right hand
          // side here, we must ensure that the left hand side satisfy the
          // constraints independent of the right hand side.
          return left_string.IsSeqString() || left_string.IsExternalString();
        }
      }
    }
    return false;
  }
References BothInputsAre(), v8::internal::compiler::JSTypedLowering::broker(), broker(), v8::internal::DCHECK(), DCHECK_EQ, GetBinaryOperationHint(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::StringRef::IsExternalString(), v8::internal::compiler::StringRef::IsSeqString(), v8::internal::ConsString::kMinLength, v8::internal::kString, v8::internal::compiler::BinopMatcher< Left, Right, rep >::left(), v8::internal::compiler::StringRef::length(), lowering_, node_, OneInputIs(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::BinopMatcher< Left, Right, rep >::right().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSAdd().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::JSBinopReduction::simplified () [inline]
Definition at line 492 of file js-typed-lowering.cc.
{ return lowering_->simplified(); }
References lowering_, and v8::internal::compiler::JSTypedLowering::simplified().
Referenced by CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), CheckLeftInputToSymbol(), ConvertPlainPrimitiveToNumber(), ConvertToUI32(), and NumberOp().
SwapInputs()
void v8::internal::compiler::JSBinopReduction::SwapInputs () [inline]
Definition at line 352 of file js-typed-lowering.cc.
                    {
    Node* l = left();
    Node* r = right();
    node_->ReplaceInput(0, r);
    node_->ReplaceInput(1, l);
  }
References v8::internal::compiler::turboshaft::l, left(), node_, v8::internal::compiler::Node::ReplaceInput(), and right().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSComparison().
type()
Type v8::internal::compiler::JSBinopReduction::type () [inline]
Definition at line 490 of file js-typed-lowering.cc.
{ return NodeProperties::GetType(node_); }
References v8::internal::compiler::NodeProperties::GetType(), and node_.
Referenced by ChangeToPureOperator(), ConvertToUI32(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), and v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual().
update_effect()
void v8::internal::compiler::JSBinopReduction::update_effect (Node * effect) [inline], [private]
Definition at line 536 of file js-typed-lowering.cc.
                                   {
    NodeProperties::ReplaceEffectInput(node_, effect);
  }
References effect(), node_, and v8::internal::compiler::NodeProperties::ReplaceEffectInput().
Referenced by CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), and CheckLeftInputToSymbol().
zone()
Zone* v8::internal::compiler::JSBinopReduction::zone () const [inline]
Definition at line 498 of file js-typed-lowering.cc.
{ return graph()->zone(); }
References graph(), and v8::internal::compiler::TFGraph::zone().
Referenced by ChangeToPureOperator(), and ChangeToSpeculativeOperator().
Member Data Documentation
lowering_
JSTypedLowering* v8::internal::compiler::JSBinopReduction::lowering_ [private]
Definition at line 501 of file js-typed-lowering.cc.
Referenced by ChangeToPureOperator(), ChangeToSpeculativeOperator(), ConvertPlainPrimitiveToNumber(), GetBinaryOperationHint(), GetCompareOperationHint(), graph(), javascript(), jsgraph(), ShouldCreateConsString(), and simplified().
node_
Node* v8::internal::compiler::JSBinopReduction::node_ [private]
Definition at line 502 of file js-typed-lowering.cc.
Referenced by ChangeToPureOperator(), ChangeToSpeculativeOperator(), CheckInputsToInternalizedString(), CheckInputsToReceiver(), CheckInputsToReceiverOrNullOrUndefined(), CheckInputsToString(), CheckInputsToStringOrOddball(), CheckInputsToStringOrStringWrapper(), CheckInputsToSymbol(), CheckLeftInputToReceiver(), CheckLeftInputToReceiverOrNullOrUndefined(), CheckLeftInputToSymbol(), context(), control(), ConvertInputsToNumber(), ConvertInputsToUI32(), effect(), GetCompareBigIntOperationHint(), GetCompareNumberOperationHint(), IsInternalizedStringCompareOperation(), IsReceiverCompareOperation(), IsReceiverOrNullOrUndefinedCompareOperation(), IsStringCompareOperation(), IsStringOrOddballCompareOperation(), IsSymbolCompareOperation(), left(), left_type(), NumberOp(), right(), right_type(), ShouldCreateConsString(), SwapInputs(), type(), and update_effect().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-typed-lowering.cc