cppgc::LivenessBroker Class Reference
The broker is passed to weak callbacks to allow (temporarily) querying the liveness state of an object.
#include <liveness-broker.h>
Public Member Functions
template<typename T >
bool IsHeapObjectAlive (const T *object) const
template<typename T >
bool IsHeapObjectAlive (const WeakMember< T > &weak_member) const
template<typename T >
bool IsHeapObjectAlive (const UntracedMember< T > &untraced_member) const
Private Member Functions
LivenessBroker ()=default
bool IsHeapObjectAliveImpl (const void *) const
Friends
class internal::LivenessBrokerFactory
Detailed Description
The broker is passed to weak callbacks to allow (temporarily) querying the liveness state of an object.
References to non-live objects must be cleared when IsHeapObjectAlive() returns false.
class GCedWithCustomWeakCallback final
  : public GarbageCollected<GCedWithCustomWeakCallback> {
 public:
  UntracedMember<Bar> bar;
  void CustomWeakCallbackMethod(const LivenessBroker& broker) {
    if (!broker.IsHeapObjectAlive(bar))
      bar = nullptr;
  }
  void Trace(cppgc::Visitor* visitor) const {
    visitor->RegisterWeakCallbackMethod<
        GCedWithCustomWeakCallback,
        &GCedWithCustomWeakCallback::CustomWeakCallbackMethod>(this);
  }
};
Definition at line 44 of file liveness-broker.h.
Constructor & Destructor Documentation
LivenessBroker()
cppgc::LivenessBroker::LivenessBroker () [private], [default]
Member Function Documentation
IsHeapObjectAlive() [1/3]
template<typename T >
bool cppgc::LivenessBroker::IsHeapObjectAlive (const T * object) const [inline]
Definition at line 47 of file liveness-broker.h.
                                                {
    // - nullptr objects are considered alive to allow weakness to be used from
    // stack while running into a conservative GC. Treating nullptr as dead
    // would mean that e.g. custom collections could not be strongified on
    // stack.
    // - Sentinel pointers are also preserved in weakness and not cleared.
    return !object || object == kSentinelPointer ||
           IsHeapObjectAliveImpl(
               TraceTrait<T>::GetTraceDescriptor(object).base_object_payload);
  }
References cppgc::kSentinelPointer.
Referenced by cppgc::Visitor::HandleWeak(), and cppgc::internal::RootVisitor::HandleWeak().
IsHeapObjectAlive() [2/3]
template<typename T >
bool cppgc::LivenessBroker::IsHeapObjectAlive (const UntracedMember< T > & untraced_member) const [inline]
Definition at line 64 of file liveness-broker.h.
                                                                         {
    return IsHeapObjectAlive<T>(untraced_member.Get());
  }
IsHeapObjectAlive() [3/3]
template<typename T >
bool cppgc::LivenessBroker::IsHeapObjectAlive (const WeakMember< T > & weak_member) const [inline]
Definition at line 59 of file liveness-broker.h.
                                                                 {
    return IsHeapObjectAlive<T>(weak_member.Get());
  }
IsHeapObjectAliveImpl()
bool cppgc::LivenessBroker::IsHeapObjectAliveImpl (const void * payload) const [private]
Definition at line 11 of file liveness-broker.cc.
                                                                    {
  return internal::HeapObjectHeader::FromObject(payload).IsMarked();
}
References cppgc::internal::HeapObjectHeader::FromObject(), and cppgc::internal::HeapObjectHeader::IsMarked().
Friends And Related Function Documentation
internal::LivenessBrokerFactory
friend class internal::LivenessBrokerFactory [friend]
Definition at line 73 of file liveness-broker.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/liveness-broker.h
/mnt/V8SourceCode/src/heap/cppgc/liveness-broker.cc