v8::internal::maglev::MaglevPhiRepresentationSelector Class Reference
#include <maglev-phi-representation-selector.h>
Public Types
enum ProcessPhiResult { kNone
, kRetryOnChange
, kChanged
 }
Public Member Functions
MaglevPhiRepresentationSelector (Graph *graph)
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
ProcessPhiResult ProcessPhi (Phi *node)
ProcessResult Process (Phi *node, const ProcessingState &)
ProcessResult Process (JumpLoop *node, const ProcessingState &)
ProcessResult Process (Dead *node, const ProcessingState &)
template<class NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
Private Types
enum class HoistType : uint8_t { kNone
, kLoopEntry
, kLoopEntryUnchecked
, kPrologue
 }
enum class NewNodePosition { kBeginingOfCurrentBlock
, kEndOfBlock
 }
template<class Value >
using SnapshotTable = compiler::turboshaft::SnapshotTable< Value >
using Key = SnapshotTable< ValueNode * >::Key
using Snapshot = SnapshotTable< ValueNode * >::Snapshot
using HoistTypeList = base::SmallVector< HoistType, 8 >
Private Member Functions
void ConvertTaggedPhiTo (Phi *phi, ValueRepresentation repr, const HoistTypeList &hoist_untagging)
template<class NodeT >
ValueNode * GetReplacementForPhiInputConversion (ValueNode *conversion_node, Phi *phi, uint32_t input_index)
template<class NodeT >
ProcessResult UpdateNodeInputs (NodeT *n, const ProcessingState *state)
template<class NodeT >
ProcessResult UpdateNonUntaggingNodeInputs (NodeT *n, const ProcessingState *state)
ProcessResult UpdateNodePhiInput (CheckSmi *node, Phi *phi, int input_index, const ProcessingState *state)
ProcessResult UpdateNodePhiInput (CheckNumber *node, Phi *phi, int input_index, const ProcessingState *state)
ProcessResult UpdateNodePhiInput (StoreTaggedFieldNoWriteBarrier *node, Phi *phi, int input_index, const ProcessingState *state)
ProcessResult UpdateNodePhiInput (StoreFixedArrayElementNoWriteBarrier *node, Phi *phi, int input_index, const ProcessingState *state)
ProcessResult UpdateNodePhiInput (BranchIfToBooleanTrue *node, Phi *phi, int input_index, const ProcessingState *state)
ProcessResult UpdateNodePhiInput (NodeBase *node, Phi *phi, int input_index, const ProcessingState *state)
void EnsurePhiInputsTagged (Phi *phi)
bool IsUntagging (Opcode op)
void UpdateUntaggingOfPhi (Phi *phi, ValueNode *old_untagging)
ValueNode * EnsurePhiTagged (Phi *phi, BasicBlock *block, NewNodePosition pos, const ProcessingState *state, std::optional< int > predecessor_index=std::nullopt)
ValueNode * AddNodeAtBlockEnd (ValueNode *new_node, BasicBlock *block, DeoptFrame *deopt_frame=nullptr)
ValueNode * AddNode (ValueNode *node, BasicBlock *block, NewNodePosition pos, const ProcessingState *state, DeoptFrame *deopt_frame=nullptr)
void RegisterNewNode (ValueNode *node)
void FixLoopPhisBackedge (BasicBlock *block)
void PreparePhiTaggings (BasicBlock *old_block, const BasicBlock *new_block)
MaglevGraphLabeller * graph_labeller () const
bool CanHoistUntaggingTo (BasicBlock *block)
Zone * zone () const
Private Attributes
Graph * graph_
BasicBlock * current_block_ = nullptr
SnapshotTable< ValueNode * > phi_taggings_
ZoneVector< Snapshot > predecessors_
ZoneVector< Node * > new_nodes_at_start_
absl::flat_hash_map< BasicBlock::Id, Snapshot > snapshots_
Detailed Description
Definition at line 23 of file maglev-phi-representation-selector.h.
Member Typedef Documentation
HoistTypeList
using v8::internal::maglev::MaglevPhiRepresentationSelector::HoistTypeList = base::SmallVector<HoistType, 8> [private]
Definition at line 81 of file maglev-phi-representation-selector.h.
Key
using v8::internal::maglev::MaglevPhiRepresentationSelector::Key = SnapshotTable<ValueNode*>::Key [private]
Definition at line 26 of file maglev-phi-representation-selector.h.
Snapshot
using v8::internal::maglev::MaglevPhiRepresentationSelector::Snapshot = SnapshotTable<ValueNode*>::Snapshot [private]
Definition at line 27 of file maglev-phi-representation-selector.h.
SnapshotTable
template<class Value >
using v8::internal::maglev::MaglevPhiRepresentationSelector::SnapshotTable = compiler::turboshaft::SnapshotTable<Value> [private]
Definition at line 25 of file maglev-phi-representation-selector.h.
Member Enumeration Documentation
HoistType
enum v8::internal::maglev::MaglevPhiRepresentationSelector::HoistType : uint8_t [strong], [private]
Enumerator
kNone
kLoopEntry
kLoopEntryUnchecked
kPrologue
Definition at line 75 of file maglev-phi-representation-selector.h.
                       : uint8_t {
    kNone,
    kLoopEntry,
    kLoopEntryUnchecked,
    kPrologue,
  };
NewNodePosition
enum v8::internal::maglev::MaglevPhiRepresentationSelector::NewNodePosition [strong], [private]
Enumerator
kBeginingOfCurrentBlock
kEndOfBlock
Definition at line 174 of file maglev-phi-representation-selector.h.
{ kBeginingOfCurrentBlock, kEndOfBlock };
ProcessPhiResult
enum v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhiResult
Enumerator
kNone
kRetryOnChange
kChanged
Definition at line 51 of file maglev-phi-representation-selector.h.
{ kNone, kRetryOnChange, kChanged };
Constructor & Destructor Documentation
MaglevPhiRepresentationSelector()
v8::internal::maglev::MaglevPhiRepresentationSelector::MaglevPhiRepresentationSelector (Graph * graph) [inline], [explicit]
Definition at line 30 of file maglev-phi-representation-selector.h.
      : graph_(graph),
        phi_taggings_(zone()),
        predecessors_(zone()),
        new_nodes_at_start_(zone()) {}
Member Function Documentation
AddNode()
ValueNode * v8::internal::maglev::MaglevPhiRepresentationSelector::AddNode (ValueNode * node, BasicBlock * block, NewNodePosition pos, const ProcessingState * state, DeoptFrame * deopt_frame = nullptr) [private]
Definition at line 1118 of file maglev-phi-representation-selector.cc.
                                                           {
  if (node->properties().can_eager_deopt()) {
    DCHECK_NOT_NULL(deopt_frame);
    node->SetEagerDeoptInfo(zone(), *deopt_frame);
  }
  if (pos == NewNodePosition::kBeginingOfCurrentBlock) {
    DCHECK_EQ(block, current_block_);
    DCHECK_NOT_NULL(state);
    // If the node iterator is currently on the 1st node of the block, we need
    // to use `InsertBefore` to insert a new node. Otherwise, we can use
    // `AddFront`.
    new_nodes_at_start_.push_back(node);
  } else {
    block->nodes().push_back(node);
  }
  RegisterNewNode(node);
  return node;
}
References v8::internal::maglev::OpProperties::can_eager_deopt(), current_block_, DCHECK_EQ, DCHECK_NOT_NULL, kBeginingOfCurrentBlock, new_nodes_at_start_, v8::internal::maglev::BasicBlock::nodes(), v8::internal::maglev::NodeBase::properties(), v8::internal::ZoneVector< T >::push_back(), RegisterNewNode(), v8::internal::maglev::NodeBase::SetEagerDeoptInfo(), and zone().
Referenced by AddNodeAtBlockEnd(), and EnsurePhiTagged().
AddNodeAtBlockEnd()
ValueNode * v8::internal::maglev::MaglevPhiRepresentationSelector::AddNodeAtBlockEnd (ValueNode * new_node, BasicBlock * block, DeoptFrame * deopt_frame = nullptr) [private]
Definition at line 1112 of file maglev-phi-representation-selector.cc.
                                                                 {
  return AddNode(node, block, NewNodePosition::kEndOfBlock, nullptr,
                 deopt_frame);
}
References AddNode(), and kEndOfBlock.
Referenced by ConvertTaggedPhiTo(), and GetReplacementForPhiInputConversion().
CanHoistUntaggingTo()
bool v8::internal::maglev::MaglevPhiRepresentationSelector::CanHoistUntaggingTo (BasicBlock * block) [private]
Definition at line 70 of file maglev-phi-representation-selector.cc.
                                                                           {
  if (block->successors().size() != 1) return false;
  BasicBlock* next = block->successors()[0];
  // To be able to hoist above resumable loops we would have to be able to
  // convert during resumption.
  return !next->state()->is_resumable_loop();
}
References v8::internal::maglev::MergePointInterpreterFrameState::is_resumable_loop(), v8::internal::maglev::BasicBlock::state(), and v8::internal::maglev::BasicBlock::successors().
Referenced by ProcessPhi().
ConvertTaggedPhiTo()
void v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo (Phi * phi, ValueRepresentation repr, const HoistTypeList & hoist_untagging) [private]
Definition at line 449 of file maglev-phi-representation-selector.cc.
                                                                              {
  // We currently only support Int32, Float64, and HoleyFloat64 untagged phis.
  DCHECK(repr == ValueRepresentation::kInt32 ||
         repr == ValueRepresentation::kFloat64 ||
         repr == ValueRepresentation::kHoleyFloat64);
  phi->change_representation(repr);
  // Re-initialise register data, since we might have changed from integer
  // registers to floating registers.
  phi->InitializeRegisterData();
  for (int input_index = 0; input_index < phi->input_count(); input_index++) {
    ValueNode* input = phi->input(input_index).node();
#define TRACE_INPUT_LABEL \
  " @ Input " << input_index << " (" \
                 << PrintNodeLabel(graph_labeller(), input) << ")"
    if (input->Is<SmiConstant>()) {
      switch (repr) {
        case ValueRepresentation::kInt32:
          TRACE_UNTAGGING(TRACE_INPUT_LABEL << ": Making Int32 instead of Smi");
          phi->change_input(input_index,
                            graph_->GetInt32Constant(
                                input->Cast<SmiConstant>()->value().value()));
          break;
        case ValueRepresentation::kFloat64:
        case ValueRepresentation::kHoleyFloat64:
          TRACE_UNTAGGING(TRACE_INPUT_LABEL
                          << ": Making Float64 instead of Smi");
          phi->change_input(input_index,
                            graph_->GetFloat64Constant(
                                input->Cast<SmiConstant>()->value().value()));
          break;
        case ValueRepresentation::kUint32:
          UNIMPLEMENTED();
        default:
          UNREACHABLE();
      }
    } else if (Constant* constant = input->TryCast<Constant>()) {
      TRACE_UNTAGGING(TRACE_INPUT_LABEL
                      << ": Making Float64 instead of Constant");
      DCHECK(constant->object().IsHeapNumber());
      DCHECK(repr == ValueRepresentation::kFloat64 ||
             repr == ValueRepresentation::kHoleyFloat64);
      phi->change_input(input_index,
                        graph_->GetFloat64Constant(
                            constant->object().AsHeapNumber().value()));
    } else if (input->properties().is_conversion()) {
      // Unwrapping the conversion.
      DCHECK_EQ(input->value_representation(), ValueRepresentation::kTagged);
      // Needs to insert a new conversion.
      ValueNode* bypassed_input = input->input(0).node();
      ValueRepresentation from_repr = bypassed_input->value_representation();
      ValueNode* new_input;
      if (from_repr == repr) {
        TRACE_UNTAGGING(TRACE_INPUT_LABEL << ": Bypassing conversion");
        new_input = bypassed_input;
      } else {
        Opcode conv_opcode =
            GetOpcodeForConversion(from_repr, repr, /*truncating*/ false);
        switch (conv_opcode) {
          case Opcode::kChangeInt32ToFloat64: {
            new_input =
                GetReplacementForPhiInputConversion<ChangeInt32ToFloat64>(
                    input, phi, input_index);
            break;
          }
          case Opcode::kChangeUint32ToFloat64: {
            new_input =
                GetReplacementForPhiInputConversion<ChangeUint32ToFloat64>(
                    input, phi, input_index);
            break;
          }
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
          case Opcode::kFloat64ToHoleyFloat64: {
            new_input =
                GetReplacementForPhiInputConversion<Float64ToHoleyFloat64>(
                    input, phi, input_index);
            break;
          }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
          case Opcode::kIdentity:
            TRACE_UNTAGGING(TRACE_INPUT_LABEL << ": Bypassing conversion");
            new_input = bypassed_input;
            break;
          default:
            UNREACHABLE();
        }
      }
      phi->change_input(input_index, new_input);
    } else if (Phi* input_phi = input->TryCast<Phi>()) {
      ValueRepresentation from_repr = input_phi->value_representation();
      if (from_repr == ValueRepresentation::kTagged) {
        // We allow speculative untagging of the backedge for loop phis from
        // loops that have been peeled.
        // This can lead to deopt loops (eg, if after the last iteration of a
        // loop, a loop Phi has a specific representation that it never has in
        // the loop), but this case should (hopefully) be rare.
        // We know that we are on the backedge input of a peeled loop, because
        // if it wasn't the case, then Process(Phi*) would not have decided to
        // untag this Phi, and this function would not have been called (because
        // except for backedges of peeled loops, tagged inputs prevent phi
        // untagging).
        DCHECK(phi->merge_state()->is_loop_with_peeled_iteration());
        DCHECK(phi->is_backedge_offset(input_index));
        DeoptFrame* deopt_frame = phi->merge_state()->backedge_deopt_frame();
        switch (repr) {
          case ValueRepresentation::kInt32: {
            phi->change_input(
                input_index,
                AddNodeAtBlockEnd(
                    NodeBase::New<CheckedSmiUntag>(zone(), {input_phi}),
                    phi->predecessor_at(input_index), deopt_frame));
            break;
          }
          case ValueRepresentation::kFloat64: {
            phi->change_input(
                input_index,
                AddNodeAtBlockEnd(
                    NodeBase::New<CheckedNumberOrOddballToFloat64>(
                        zone(), {input_phi},
                        TaggedToFloat64ConversionType::kOnlyNumber),
                    phi->predecessor_at(input_index), deopt_frame));
            break;
          }
          case ValueRepresentation::kHoleyFloat64: {
            phi->change_input(
                input_index,
                AddNodeAtBlockEnd(
                    NodeBase::New<CheckedNumberOrOddballToHoleyFloat64>(
                        zone(), {input_phi}),
                    phi->predecessor_at(input_index), deopt_frame));
            break;
          }
          case ValueRepresentation::kTagged:
          case ValueRepresentation::kIntPtr:
          case ValueRepresentation::kUint32:
            UNREACHABLE();
        }
        TRACE_UNTAGGING(TRACE_INPUT_LABEL
                        << ": Eagerly untagging Phi on backedge");
      } else if (from_repr != repr &&
                 from_repr == ValueRepresentation::kInt32) {
        // We allow widening of Int32 inputs to Float64, which can lead to the
        // current Phi having a Float64 representation but having some Int32
        // inputs, which will require an Int32ToFloat64 conversion.
        DCHECK(repr == ValueRepresentation::kFloat64 ||
               repr == ValueRepresentation::kHoleyFloat64);
        phi->change_input(input_index,
                          AddNodeAtBlockEnd(NodeBase::New<ChangeInt32ToFloat64>(
                                                zone(), {input_phi}),
                                            phi->predecessor_at(input_index)));
        TRACE_UNTAGGING(
            TRACE_INPUT_LABEL
            << ": Converting phi input with a ChangeInt32ToFloat64");
      } else {
        // We allow Float64 to silently be used as HoleyFloat64.
        DCHECK_IMPLIES(from_repr != repr,
                       from_repr == ValueRepresentation::kFloat64 &&
                           repr == ValueRepresentation::kHoleyFloat64);
        TRACE_UNTAGGING(TRACE_INPUT_LABEL
                        << ": Keeping untagged Phi input as-is");
      }
    } else if (hoist_untagging[input_index] != HoistType::kNone) {
      CHECK_EQ(input->value_representation(), ValueRepresentation::kTagged);
      BasicBlock* block;
      DeoptFrame* deopt_frame;
      auto GetDeoptFrame = [](BasicBlock* block) {
        return &block->control_node()
                    ->Cast<CheckpointedJump>()
                    ->eager_deopt_info()
                    ->top_frame();
      };
      switch (hoist_untagging[input_index]) {
        case HoistType::kLoopEntryUnchecked:
          block = phi->merge_state()->predecessor_at(input_index);
          deopt_frame = nullptr;
          break;
        case HoistType::kLoopEntry:
          block = phi->merge_state()->predecessor_at(input_index);
          deopt_frame = GetDeoptFrame(block);
          break;
        case HoistType::kPrologue:
          block = *graph_->begin();
          deopt_frame = GetDeoptFrame(block);
          break;
        case HoistType::kNone:
          UNREACHABLE();
      }
      // Ensure the hoisted value is actually live at the hoist location.
      CHECK(input->Is<InitialValue>() ||
            (phi->is_loop_phi() && !phi->is_backedge_offset(input_index)));
      ValueNode* untagged;
      switch (repr) {
        case ValueRepresentation::kInt32:
          if (!deopt_frame) {
            DCHECK(NodeTypeIs(input->GetStaticType(graph_->broker()),
                              NodeType::kSmi));
            untagged = AddNodeAtBlockEnd(
                NodeBase::New<UnsafeSmiUntag>(zone(), {input}), block);
          } else {
            untagged = AddNodeAtBlockEnd(
                NodeBase::New<CheckedNumberOrOddballToFloat64>(
                    zone(), {input},
                    TaggedToFloat64ConversionType::kOnlyNumber),
                block, deopt_frame);
            untagged =
                AddNodeAtBlockEnd(NodeBase::New<CheckedTruncateFloat64ToInt32>(
                                      zone(), {untagged}),
                                  block, deopt_frame);
          }
          break;
        case ValueRepresentation::kFloat64:
        case ValueRepresentation::kHoleyFloat64:
          if (!deopt_frame) {
            DCHECK(NodeTypeIs(input->GetStaticType(graph_->broker()),
                              NodeType::kNumber));
            untagged = AddNodeAtBlockEnd(
                NodeBase::New<UncheckedNumberOrOddballToFloat64>(
                    zone(), {input},
                    TaggedToFloat64ConversionType::kOnlyNumber),
                block);
          } else {
            DCHECK(!phi->uses_require_31_bit_value());
            untagged = AddNodeAtBlockEnd(
                NodeBase::New<CheckedNumberOrOddballToFloat64>(
                    zone(), {input},
                    TaggedToFloat64ConversionType::kOnlyNumber),
                block, deopt_frame);
            if (repr != ValueRepresentation::kHoleyFloat64) {
              untagged =
                  AddNodeAtBlockEnd(NodeBase::New<CheckedHoleyFloat64ToFloat64>(
                                        zone(), {untagged}),
                                    block, deopt_frame);
            }
          }
          break;
        case ValueRepresentation::kTagged:
        case ValueRepresentation::kUint32:
        case ValueRepresentation::kIntPtr:
          UNREACHABLE();
      }
      phi->change_input(input_index, untagged);
    } else {
      TRACE_UNTAGGING(TRACE_INPUT_LABEL << ": Invalid input for untagged phi");
      UNREACHABLE();
    }
  }
}
References AddNodeAtBlockEnd(), v8::internal::maglev::MergePointInterpreterFrameState::backedge_deopt_frame(), v8::internal::maglev::Graph::begin(), v8::internal::maglev::Graph::broker(), v8::internal::maglev::NodeBase::Cast(), CHECK, CHECK_EQ, v8::internal::maglev::BasicBlock::control_node(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::maglev::Graph::GetFloat64Constant(), v8::internal::maglev::Graph::GetInt32Constant(), v8::internal::maglev::anonymous_namespace{maglev-phi-representation-selector.cc}::GetOpcodeForConversion(), v8::internal::maglev::ValueNode::GetStaticType(), graph_, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::Phi::is_backedge_offset(), v8::internal::maglev::OpProperties::is_conversion(), v8::internal::maglev::Phi::is_loop_phi(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop_with_peeled_iteration(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, kLoopEntry, kLoopEntryUnchecked, kNone, v8::internal::maglev::kOnlyNumber, kPrologue, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::Phi::merge_state(), v8::internal::maglev::Input::node(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::Phi::predecessor_at(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_at(), v8::internal::maglev::NodeBase::properties(), TRACE_INPUT_LABEL, TRACE_UNTAGGING, v8::internal::maglev::NodeBase::TryCast(), v8::internal::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::maglev::Phi::uses_require_31_bit_value(), v8::internal::maglev::SmiConstant::value(), v8::internal::Tagged< Smi >::value(), v8::internal::maglev::ValueNode::value_representation(), and zone().
Referenced by ProcessPhi().
EnsurePhiInputsTagged()
void v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiInputsTagged (Phi * phi) [private]
Definition at line 335 of file maglev-phi-representation-selector.cc.
                                                                    {
  // Since we are untagging some Phis, it's possible that one of the inputs of
  // {phi} is an untagged Phi. However, if this function is called, then we've
  // decided that {phi} is going to stay tagged, and thus, all of its inputs
  // should be tagged. We'll thus insert tagging operation on the untagged phi
  // inputs of {phi}.
  const int skip_backedge = phi->is_loop_phi() ? 1 : 0;
  for (int i = 0; i < phi->input_count() - skip_backedge; i++) {
    ValueNode* input = phi->input(i).node();
    if (Phi* phi_input = input->TryCast<Phi>()) {
      phi->change_input(
          i, EnsurePhiTagged(phi_input, phi->predecessor_at(i),
                             NewNodePosition::kEndOfBlock, nullptr, i));
    } else {
      // Inputs of Phis that aren't Phi should always be tagged (except for the
      // phis untagged by this class, but {phi} isn't one of them).
      DCHECK(input->is_tagged());
    }
  }
}
References v8::internal::DCHECK(), EnsurePhiTagged(), v8::internal::maglev::Phi::is_loop_phi(), v8::internal::maglev::ValueNode::is_tagged(), kEndOfBlock, v8::internal::maglev::Phi::predecessor_at(), and v8::internal::maglev::NodeBase::TryCast().
Referenced by ProcessPhi().
EnsurePhiTagged()
ValueNode * v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiTagged (Phi * phi, BasicBlock * block, NewNodePosition pos, const ProcessingState * state, std::optional< int > predecessor_index = std::nullopt) [private]
Definition at line 987 of file maglev-phi-representation-selector.cc.
                                                                      {
  DCHECK_IMPLIES(state == nullptr, pos == NewNodePosition::kEndOfBlock);
  if (phi->value_representation() == ValueRepresentation::kTagged) {
    return phi;
  }
  // Try to find an existing Tagged conversion for {phi} in {phi_taggings_}.
  if (phi->has_key()) {
    if (predecessor_index.has_value()) {
      if (ValueNode* tagging = phi_taggings_.GetPredecessorValue(
              phi->key(), predecessor_index.value())) {
        return tagging;
      }
    } else {
      if (ValueNode* tagging = phi_taggings_.Get(phi->key())) {
        return tagging;
      }
    }
  }
  // We didn't already Tag {phi} on the current path; creating this tagging now.
  ValueNode* tagged = nullptr;
  switch (phi->value_representation()) {
    case ValueRepresentation::kFloat64:
      // It's important to use kCanonicalizeSmi for Float64ToTagged, as
      // otherwise, we could end up storing HeapNumbers in Smi fields.
      tagged = AddNode(
          NodeBase::New<Float64ToTagged>(
              zone(), {phi}, Float64ToTagged::ConversionMode::kCanonicalizeSmi),
          block, pos, state);
      break;
    case ValueRepresentation::kHoleyFloat64:
      // It's important to use kCanonicalizeSmi for HoleyFloat64ToTagged, as
      // otherwise, we could end up storing HeapNumbers in Smi fields.
      tagged =
          AddNode(NodeBase::New<HoleyFloat64ToTagged>(
                      zone(), {phi},
                      HoleyFloat64ToTagged::ConversionMode::kCanonicalizeSmi),
                  block, pos, state);
      break;
    case ValueRepresentation::kInt32:
      tagged = AddNode(NodeBase::New<Int32ToNumber>(zone(), {phi}), block, pos,
                       state);
      break;
    case ValueRepresentation::kUint32:
      tagged = AddNode(NodeBase::New<Uint32ToNumber>(zone(), {phi}), block, pos,
                       state);
      break;
    case ValueRepresentation::kTagged:
      // Already handled at the begining of this function.
    case ValueRepresentation::kIntPtr:
      UNREACHABLE();
  }
  if (predecessor_index.has_value()) {
    // We inserted the new tagging node in a predecessor of the current block,
    // so we shouldn't update the snapshot table for the current block (and we
    // can't update it for the predecessor either since its snapshot is sealed).
    DCHECK_IMPLIES(block == current_block_,
                   block->is_loop() && block->successors().size() == 1 &&
                       block->successors().at(0) == block);
    return tagged;
  }
  if (phi->has_key()) {
    // The Key already existed, but wasn't set on the current path.
    phi_taggings_.Set(phi->key(), tagged);
  } else {
    // The Key didn't already exist, so we create it now.
    auto key = phi_taggings_.NewKey();
    phi->set_key(key);
    phi_taggings_.Set(key, tagged);
  }
  return tagged;
}
References AddNode(), current_block_, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::GetPredecessorValue(), v8::internal::maglev::Phi::has_key(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::Float64ToTagged::kCanonicalizeSmi, v8::internal::maglev::HoleyFloat64ToTagged::kCanonicalizeSmi, kEndOfBlock, v8::internal::key, v8::internal::maglev::Phi::key(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewKey(), phi_taggings_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set(), v8::internal::maglev::Phi::set_key(), v8::internal::maglev::BasicBlock::successors(), v8::internal::UNREACHABLE(), and zone().
Referenced by EnsurePhiInputsTagged(), FixLoopPhisBackedge(), and UpdateNodePhiInput().
FixLoopPhisBackedge()
void v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge (BasicBlock * block) [private]
Definition at line 1066 of file maglev-phi-representation-selector.cc.
                                                                           {
  // TODO(dmercadier): it would be interesting to compute a fix point for loop
  // phis, or at least to go over the loop header twice.
  if (!block->has_phi()) return;
  for (Phi* phi : *block->phis()) {
    int last_input_idx = phi->input_count() - 1;
    ValueNode* backedge = phi->input(last_input_idx).node();
    if (phi->value_representation() == ValueRepresentation::kTagged) {
      // If the backedge is a Phi that was untagged, but {phi} is tagged, then
      // we need to retag the backedge.
      // Identity nodes are used to replace outdated untagging nodes after a phi
      // has been untagged. Here, since the backedge was initially tagged, it
      // couldn't have been such an untagging node, so it shouldn't be an
      // Identity node now.
      DCHECK(!backedge->Is<Identity>());
      if (backedge->value_representation() != ValueRepresentation::kTagged) {
        // Since all Phi inputs are initially tagged, the fact that the backedge
        // is not tagged means that it's a Phi that we recently untagged.
        DCHECK(backedge->Is<Phi>());
        phi->change_input(
            last_input_idx,
            EnsurePhiTagged(backedge->Cast<Phi>(), current_block_,
                            NewNodePosition::kEndOfBlock, /*state*/ nullptr));
      }
    } else {
      // If {phi} was untagged and its backedge became Identity, then we need to
      // unwrap it.
      DCHECK_NE(phi->value_representation(), ValueRepresentation::kTagged);
      if (backedge->Is<Identity>()) {
        // {backedge} should have the same representation as {phi}, although if
        // {phi} has HoleyFloat64 representation, the backedge is allowed to
        // have Float64 representation rather than HoleyFloat64.
        DCHECK((backedge->input(0).node()->value_representation() ==
                phi->value_representation()) ||
               (backedge->input(0).node()->value_representation() ==
                    ValueRepresentation::kFloat64 &&
                phi->value_representation() ==
                    ValueRepresentation::kHoleyFloat64));
        phi->change_input(last_input_idx, backedge->input(0).node());
      }
    }
  }
}
References v8::internal::maglev::NodeBase::Cast(), current_block_, v8::internal::DCHECK(), DCHECK_NE, EnsurePhiTagged(), v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::Is(), kEndOfBlock, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kTagged, v8::internal::maglev::Input::node(), v8::internal::maglev::BasicBlock::phis(), and v8::internal::maglev::ValueNode::value_representation().
Referenced by Process().
GetReplacementForPhiInputConversion()
template<class NodeT >
ValueNode * v8::internal::maglev::MaglevPhiRepresentationSelector::GetReplacementForPhiInputConversion (ValueNode * conversion_node, Phi * phi, uint32_t input_index) [private]
Definition at line 703 of file maglev-phi-representation-selector.cc.
                                                      {
  TRACE_UNTAGGING(TRACE_INPUT_LABEL
                  << ": Replacing old conversion with a "
                  << OpcodeToString(NodeBase::opcode_of<NodeT>));
  ValueNode* new_node = NodeBase::New<NodeT>(zone(), {input->input(0).node()});
  return AddNodeAtBlockEnd(new_node, phi->predecessor_at(input_index));
}
References AddNodeAtBlockEnd(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::OpcodeToString(), v8::internal::maglev::Phi::predecessor_at(), TRACE_INPUT_LABEL, TRACE_UNTAGGING, and zone().
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::MaglevPhiRepresentationSelector::graph_labeller () const [inline], [private]
Definition at line 203 of file maglev-phi-representation-selector.h.
                                              {
    return graph_->graph_labeller();
  }
References graph_, and v8::internal::maglev::Graph::graph_labeller().
Referenced by ProcessPhi().
IsUntagging()
bool v8::internal::maglev::MaglevPhiRepresentationSelector::IsUntagging (Opcode op) [private]
Definition at line 712 of file maglev-phi-representation-selector.cc.
                                                           {
  switch (op) {
    case Opcode::kCheckedSmiUntag:
    case Opcode::kUnsafeSmiUntag:
    case Opcode::kCheckedNumberToInt32:
    case Opcode::kCheckedObjectToIndex:
    case Opcode::kCheckedTruncateNumberOrOddballToInt32:
    case Opcode::kTruncateNumberOrOddballToInt32:
    case Opcode::kCheckedNumberOrOddballToFloat64:
    case Opcode::kUncheckedNumberOrOddballToFloat64:
    case Opcode::kCheckedNumberOrOddballToHoleyFloat64:
      return true;
    default:
      return false;
  }
}
Referenced by UpdateNodeInputs(), UpdateNodePhiInput(), and UpdateNonUntaggingNodeInputs().
PostPhiProcessing()
void v8::internal::maglev::MaglevPhiRepresentationSelector::PostPhiProcessing () [inline]
Definition at line 49 of file maglev-phi-representation-selector.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessBasicBlock (BasicBlock * block)
Definition at line 858 of file maglev-phi-representation-selector.cc.
                                                                             {
  size_t diff = new_nodes_at_start_.size();
  if (diff == 0) return;
  size_t old_size = block->nodes().size();
  block->nodes().resize(old_size + new_nodes_at_start_.size());
  auto begin = block->nodes().begin();
  std::copy_backward(begin, begin + old_size, block->nodes().end());
  std::copy(new_nodes_at_start_.begin(), new_nodes_at_start_.end(), begin);
  new_nodes_at_start_.resize(0);
}
References v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::begin(), v8::internal::ZoneVector< T >::end(), new_nodes_at_start_, v8::internal::maglev::BasicBlock::nodes(), v8::internal::ZoneVector< T >::resize(), and v8::internal::ZoneVector< T >::size().
PostProcessGraph()
void v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessGraph (Graph * graph) [inline]
Definition at line 42 of file maglev-phi-representation-selector.h.
                                      {
    if (v8_flags.trace_maglev_phi_untagging) {
      StdoutStream{} << "\n";
    }
  }
References v8::internal::v8_flags.
PreparePhiTaggings()
void v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings (BasicBlock * old_block, const BasicBlock * new_block) [private]
Definition at line 1150 of file maglev-phi-representation-selector.cc.
                                                        {
  // Sealing and saving current snapshot
  if (phi_taggings_.IsSealed()) {
    phi_taggings_.StartNewSnapshot();
    return;
  }
  snapshots_.emplace(old_block->id(), phi_taggings_.Seal());
  // Setting up new snapshot
  predecessors_.clear();
  if (!new_block->is_merge_block()) {
    BasicBlock* pred = new_block->predecessor();
    predecessors_.push_back(snapshots_.at(pred->id()));
  } else {
    int skip_backedge = new_block->is_loop();
    for (int i = 0; i < new_block->predecessor_count() - skip_backedge; i++) {
      BasicBlock* pred = new_block->predecessor_at(i);
      predecessors_.push_back(snapshots_.at(pred->id()));
    }
  }
  auto merge_taggings =
      [&](Key key, base::Vector<ValueNode* const> predecessors) -> ValueNode* {
    for (ValueNode* node : predecessors) {
      if (node == nullptr) {
        // There is a predecessor that doesn't have this Tagging, so we'll
        // return nullptr, and if we need it in the future, we'll have to
        // recreate it. An alternative would be to eagerly insert this Tagging
        // in all of the other predecesors, but it's possible that it's not used
        // anymore or not on all future path, so this could also introduce
        // unnecessary tagging.
        return static_cast<Phi*>(nullptr);
      }
    }
    // Only merge blocks should require Phis.
    DCHECK(new_block->is_merge_block());
    // We create a Phi to merge all of the existing taggings.
    int predecessor_count = new_block->predecessor_count();
    Phi* phi = Node::New<Phi>(zone(), predecessor_count, new_block->state(),
                              interpreter::Register());
    for (int i = 0; static_cast<size_t>(i) < predecessors.size(); i++) {
      phi->set_input(i, predecessors[i]);
    }
    if (predecessors.size() != static_cast<size_t>(predecessor_count)) {
      // The backedge is omitted from {predecessors}. With set the Phi as its
      // own backedge.
      DCHECK(new_block->is_loop());
      phi->set_input(predecessor_count - 1, phi);
    }
    RegisterNewNode(phi);
    new_block->AddPhi(phi);
    return phi;
  };
  phi_taggings_.StartNewSnapshot(base::VectorOf(predecessors_), merge_taggings);
}
References v8::internal::maglev::BasicBlock::AddPhi(), v8::internal::ZoneVector< T >::clear(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::BasicBlock::id(), v8::internal::maglev::BasicBlock::is_loop(), v8::internal::maglev::BasicBlock::is_merge_block(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::key, phi_taggings_, v8::internal::maglev::BasicBlock::predecessor(), v8::internal::maglev::BasicBlock::predecessor_at(), v8::internal::maglev::BasicBlock::predecessor_count(), predecessors_, v8::internal::ZoneVector< T >::push_back(), RegisterNewNode(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), snapshots_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), v8::internal::maglev::BasicBlock::state(), v8::base::VectorOf(), and zone().
Referenced by PreProcessBasicBlock().
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::PreProcessBasicBlock (BasicBlock * block)
Definition at line 30 of file maglev-phi-representation-selector.cc.
                       {
  PreparePhiTaggings(current_block_, block);
  current_block_ = block;
  if (block->has_phi()) {
    auto& phis = *block->phis();
    auto first_retry = phis.begin();
    auto end_retry = first_retry;
    bool any_change = false;
    for (auto it = phis.begin(); it != phis.end(); ++it) {
      Phi* phi = *it;
      switch (ProcessPhi(phi)) {
        case ProcessPhiResult::kNone:
          break;
        case ProcessPhiResult::kChanged:
          any_change = true;
          break;
        case ProcessPhiResult::kRetryOnChange:
          if (end_retry == first_retry) {
            first_retry = it;
          }
          end_retry = it;
          ++end_retry;
          break;
      }
    }
    // Give it one more shot in case an earlier phi has a later one as input.
    if (any_change) {
      for (auto it = first_retry; it != end_retry; ++it) {
        ProcessPhi(*it);
      }
    }
  }
  return BlockProcessResult::kContinue;
}
References v8::base::ThreadedListBase< T, BaseClass, TLTraits, kSupportsUnsafeInsertion >::begin(), current_block_, v8::internal::maglev::BasicBlock::has_phi(), v8::internal::maglev::kContinue, v8::internal::maglev::BasicBlock::phis(), PreparePhiTaggings(), and ProcessPhi().
PreProcessGraph()
void v8::internal::maglev::MaglevPhiRepresentationSelector::PreProcessGraph (Graph * graph) [inline]
Definition at line 36 of file maglev-phi-representation-selector.h.
                                     {
    if (v8_flags.trace_maglev_phi_untagging) {
      StdoutStream{} << "\nMaglevPhiRepresentationSelector\n";
    }
    graph_ = graph;
  }
References graph(), graph_, and v8::internal::v8_flags.
Process() [1/4]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::Process (Dead * node, const ProcessingState &) [inline]
Definition at line 65 of file maglev-phi-representation-selector.h.
                                                            {
    return ProcessResult::kRemove;
  }
References v8::internal::maglev::kRemove.
Process() [2/4]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::Process (JumpLoop * node, const ProcessingState &) [inline]
Definition at line 60 of file maglev-phi-representation-selector.h.
                                                                {
    FixLoopPhisBackedge(node->target());
    return ProcessResult::kContinue;
  }
References FixLoopPhisBackedge(), and v8::internal::maglev::kContinue.
Process() [3/4]
template<class NodeT >
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 70 of file maglev-phi-representation-selector.h.
                                                                   {
    return UpdateNodeInputs(node, &state);
  }
References UpdateNodeInputs().
Process() [4/4]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::Process (Phi * node, const ProcessingState &) [inline]
Definition at line 56 of file maglev-phi-representation-selector.h.
                                                           {
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::kContinue.
ProcessPhi()
MaglevPhiRepresentationSelector::ProcessPhiResult v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi (Phi * node)
Definition at line 79 of file maglev-phi-representation-selector.cc.
                                                     {
  if (node->value_representation() != ValueRepresentation::kTagged) {
    return ProcessPhiResult::kNone;
  }
  if (node->is_exception_phi()) {
    // Exception phis have no inputs (or, at least, none accessible through
    // `node->input(...)`), so we don't know if the inputs could be untagged or
    // not, so we just keep those Phis tagged.
    return ProcessPhiResult::kNone;
  }
  TRACE_UNTAGGING(
      "Considering for untagging: " << PrintNodeLabel(graph_labeller(), node));
  // {input_mask} represents the ValueRepresentation that {node} could have,
  // based on the ValueRepresentation of its inputs.
  ValueRepresentationSet input_reprs;
  HoistTypeList hoist_untagging;
  hoist_untagging.resize(node->input_count(), HoistType::kNone);
  bool has_tagged_phi_input = false;
  for (int i = 0; i < node->input_count(); i++) {
    ValueNode* input = node->input(i).node();
    if (input->Is<SmiConstant>()) {
      // Could be any representation. We treat such inputs as Int32, since we
      // later allow ourselves to promote Int32 to Float64 if needed (but we
      // never downgrade Float64 to Int32, as it could cause deopt loops).
      input_reprs.Add(ValueRepresentation::kInt32);
    } else if (Constant* constant = input->TryCast<Constant>()) {
      if (constant->object().IsHeapNumber()) {
        input_reprs.Add(ValueRepresentation::kFloat64);
      } else {
        // Not a Constant that we can untag.
        // TODO(leszeks): Consider treating 'undefined' as a potential
        // HoleyFloat64.
        input_reprs.RemoveAll();
        break;
      }
    } else if (input->properties().is_conversion()) {
      DCHECK_EQ(input->input_count(), 1);
      // The graph builder tags all Phi inputs, so this conversion should
      // produce a tagged value.
      DCHECK_EQ(input->value_representation(), ValueRepresentation::kTagged);
      // If we want to untag {node}, then we'll drop the conversion and use its
      // input instead.
      input_reprs.Add(
          input->input(0).node()->properties().value_representation());
    } else if (Phi* input_phi = input->TryCast<Phi>()) {
      if (input_phi->value_representation() != ValueRepresentation::kTagged) {
        input_reprs.Add(input_phi->value_representation());
      } else {
        // An untagged phi is an input of the current phi.
        if (node->is_backedge_offset(i) &&
            node->merge_state()->is_loop_with_peeled_iteration()) {
          // This is the backedge of a loop that has a peeled iteration. We
          // ignore it and speculatively assume that it will be the same as the
          // 1st input.
          DCHECK_EQ(node->input_count(), 2);
          DCHECK_EQ(i, 1);
          break;
        }
        has_tagged_phi_input = true;
        input_reprs.RemoveAll();
        break;
      }
    } else {
      // This is the case where we don't have an existing conversion to attach
      // the untagging to. In the general case we give up, however in the
      // special case of the value originating from the loop entry branch, we
      // can try to hoist untagging out of the loop.
      if (graph_->is_osr() && v8_flags.maglev_hoist_osr_value_phi_untagging &&
          input->Is<InitialValue>() && CanHoistUntaggingTo(*graph_->begin())) {
        hoist_untagging[i] = HoistType::kPrologue;
        continue;
      }
      if (node->is_loop_phi() && !node->is_backedge_offset(i)) {
        BasicBlock* pred = node->merge_state()->predecessor_at(i);
        if (CanHoistUntaggingTo(pred)) {
          auto static_type = input->GetStaticType(graph_->broker());
          if (NodeTypeIs(static_type, NodeType::kSmi)) {
            input_reprs.Add(ValueRepresentation::kInt32);
            hoist_untagging[i] = HoistType::kLoopEntryUnchecked;
            continue;
          }
          if (NodeTypeIs(static_type, NodeType::kNumber)) {
            input_reprs.Add(ValueRepresentation::kFloat64);
            hoist_untagging[i] = HoistType::kLoopEntryUnchecked;
            continue;
          }
          // TODO(olivf): Unless we untag OSR values, speculatively untagging
          // could end us in deopt loops. To enable this by default we need to
          // add some feedback to be able to back off. Or, ideally find the
          // respective checked conversion from within the loop to wire up the
          // feedback collection.
          if (v8_flags.maglev_speculative_hoist_phi_untagging) {
            // TODO(olivf): Currently there is no hard guarantee that the phi
            // merge state has a checkpointed jump.
            if (pred->control_node()->Is<CheckpointedJump>()) {
              DCHECK(!node->merge_state()->is_resumable_loop());
              hoist_untagging[i] = HoistType::kLoopEntry;
              continue;
            }
          }
        }
      }
      // This input is tagged, didn't require a tagging operation to be
      // tagged and we decided not to hosit; we won't untag {node}.
      // TODO(dmercadier): this is a bit suboptimal, because some nodes start
      // tagged, and later become untagged (parameters for instance). Such nodes
      // will have their untagged alternative passed to {node} without any
      // explicit conversion, and we thus won't untag {node} even though we
      // could have.
      input_reprs.RemoveAll();
      break;
    }
  }
  ProcessPhiResult default_result = has_tagged_phi_input
                                        ? ProcessPhiResult::kRetryOnChange
                                        : ProcessPhiResult::kNone;
  UseRepresentationSet use_reprs;
  if (node->is_loop_phi() && !node->get_same_loop_uses_repr_hints().empty()) {
    // {node} is a loop phi that has uses inside the loop; we will tag/untag
    // based on those uses, ignoring uses after the loop.
    use_reprs = node->get_same_loop_uses_repr_hints();
    TRACE_UNTAGGING(" + use_reprs : " << use_reprs << " (same loop only)");
  } else {
    use_reprs = node->get_uses_repr_hints();
    TRACE_UNTAGGING(" + use_reprs : " << use_reprs << " (all uses)");
  }
  TRACE_UNTAGGING(" + input_reprs: " << input_reprs);
  if (use_reprs.contains(UseRepresentation::kTagged) ||
      use_reprs.contains(UseRepresentation::kUint32) || use_reprs.empty()) {
    // We don't untag phis that are used as tagged (because we'd have to retag
    // them later). We also ignore phis that are used as Uint32, because this is
    // a fairly rare case and supporting it doesn't improve performance all that
    // much but will increase code complexity.
    // TODO(dmercadier): consider taking into account where those Tagged uses
    // are: Tagged uses outside of a loop or for a Return could probably be
    // ignored.
    TRACE_UNTAGGING(" => Leaving tagged [incompatible uses]");
    EnsurePhiInputsTagged(node);
    return default_result;
  }
  if (input_reprs.contains(ValueRepresentation::kTagged) ||
      input_reprs.contains(ValueRepresentation::kIntPtr) ||
      input_reprs.empty()) {
    TRACE_UNTAGGING(" => Leaving tagged [tagged or intptr inputs]");
    EnsurePhiInputsTagged(node);
    return default_result;
  }
  // Only allowed to have Uint32, Int32, Float64 and HoleyFloat64 inputs from
  // here.
  DCHECK_EQ(input_reprs -
                ValueRepresentationSet({ValueRepresentation::kInt32,
                                        ValueRepresentation::kUint32,
                                        ValueRepresentation::kFloat64,
                                        ValueRepresentation::kHoleyFloat64}),
            ValueRepresentationSet());
  DCHECK_EQ(
      use_reprs - UseRepresentationSet({UseRepresentation::kInt32,
                                        UseRepresentation::kTruncatedInt32,
                                        UseRepresentation::kFloat64,
                                        UseRepresentation::kHoleyFloat64}),
      UseRepresentationSet());
  // The rules for untagging are that we can only widen input representations,
  // i.e. promote Int32 -> Float64 -> HoleyFloat64. We cannot convert from Int32
  // to Uint32 and vise versa, but both can be converted to Float64.
  //
  // Inputs can always be used as more generic uses, and tighter uses always
  // block more generic inputs. So, we can find the minimum generic use and
  // maximum generic input, extend inputs upwards, uses downwards, and convert
  // to the least generic use in the intersection.
  //
  // Of interest is the fact that we don't want to insert conversions which
  // reduce genericity, e.g. Float64->Int32 conversions, since they could deopt
  // and lead to deopt loops. The above logic ensures that if a Phi has Float64
  // inputs and Int32 uses, we simply don't untag it.
  //
  // TODO(leszeks): The above logic could be implemented with bit magic if the
  // representations were contiguous.
  ValueRepresentationSet possible_inputs;
  if (input_reprs.contains(ValueRepresentation::kHoleyFloat64)) {
    possible_inputs = {ValueRepresentation::kHoleyFloat64};
  } else if (input_reprs.contains(ValueRepresentation::kFloat64) ||
             input_reprs.contains(ValueRepresentation::kUint32)) {
    possible_inputs = {ValueRepresentation::kFloat64,
                       ValueRepresentation::kHoleyFloat64};
  } else {
    DCHECK(input_reprs.contains_only(ValueRepresentation::kInt32));
    possible_inputs = {ValueRepresentation::kInt32,
                       ValueRepresentation::kFloat64,
                       ValueRepresentation::kHoleyFloat64};
  }
  ValueRepresentationSet allowed_inputs_for_uses;
  if (use_reprs.contains(UseRepresentation::kInt32)) {
    allowed_inputs_for_uses = {ValueRepresentation::kInt32};
  } else if (use_reprs.contains(UseRepresentation::kFloat64)) {
    allowed_inputs_for_uses = {ValueRepresentation::kInt32,
                               ValueRepresentation::kFloat64};
  } else {
    DCHECK(!use_reprs.empty() &&
           use_reprs.is_subset_of({UseRepresentation::kHoleyFloat64,
                                   UseRepresentation::kTruncatedInt32}));
    allowed_inputs_for_uses = {ValueRepresentation::kInt32,
                               ValueRepresentation::kFloat64,
                               ValueRepresentation::kHoleyFloat64};
  }
  // When hoisting we must ensure that we don't turn a tagged flowing into
  // CheckedSmiUntag into a float64. This would cause us to loose the smi check
  // which in turn can invalidate assumptions on aliasing values.
  if (hoist_untagging.size() && node->uses_require_31_bit_value()) {
    TRACE_UNTAGGING(" => Leaving tagged [depends on smi check]");
    EnsurePhiInputsTagged(node);
    return default_result;
  }
  auto intersection = possible_inputs & allowed_inputs_for_uses;
  TRACE_UNTAGGING(" + intersection reprs: " << intersection);
  if (intersection.contains(ValueRepresentation::kInt32) &&
      use_reprs.contains_any(UseRepresentationSet{
          UseRepresentation::kInt32, UseRepresentation::kTruncatedInt32})) {
    TRACE_UNTAGGING(" => Untagging to Int32");
    ConvertTaggedPhiTo(node, ValueRepresentation::kInt32, hoist_untagging);
    return ProcessPhiResult::kChanged;
  } else if (intersection.contains(ValueRepresentation::kFloat64)) {
    TRACE_UNTAGGING(" => Untagging to kFloat64");
    ConvertTaggedPhiTo(node, ValueRepresentation::kFloat64, hoist_untagging);
    return ProcessPhiResult::kChanged;
  } else if (intersection.contains(ValueRepresentation::kHoleyFloat64)) {
    TRACE_UNTAGGING(" => Untagging to HoleyFloat64");
    ConvertTaggedPhiTo(node, ValueRepresentation::kHoleyFloat64,
                       hoist_untagging);
    return ProcessPhiResult::kChanged;
  }
  DCHECK(intersection.empty());
  // We don't untag the Phi.
  TRACE_UNTAGGING(" => Leaving tagged [incompatible inputs/uses]");
  EnsurePhiInputsTagged(node);
  return default_result;
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::maglev::Graph::begin(), v8::internal::maglev::Graph::broker(), CanHoistUntaggingTo(), v8::base::EnumSet< E, T >::contains(), v8::base::EnumSet< E, T >::contains_any(), v8::base::EnumSet< E, T >::contains_only(), v8::internal::maglev::BasicBlock::control_node(), ConvertTaggedPhiTo(), v8::internal::DCHECK(), DCHECK_EQ, v8::base::EnumSet< E, T >::empty(), EnsurePhiInputsTagged(), v8::internal::maglev::Phi::get_same_loop_uses_repr_hints(), v8::internal::maglev::Phi::get_uses_repr_hints(), v8::internal::maglev::ValueNode::GetStaticType(), graph_, graph_labeller(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::Phi::is_backedge_offset(), v8::internal::maglev::OpProperties::is_conversion(), v8::internal::maglev::Phi::is_exception_phi(), v8::internal::maglev::Phi::is_loop_phi(), v8::internal::maglev::MergePointInterpreterFrameState::is_loop_with_peeled_iteration(), v8::internal::maglev::Graph::is_osr(), v8::internal::maglev::MergePointInterpreterFrameState::is_resumable_loop(), v8::base::EnumSet< E, T >::is_subset_of(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, kLoopEntry, kLoopEntryUnchecked, kNone, kPrologue, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::maglev::kTruncatedInt32, v8::internal::maglev::kUint32, v8::internal::maglev::Phi::merge_state(), v8::internal::maglev::Input::node(), v8::internal::maglev::NodeTypeIs(), v8::internal::maglev::MergePointInterpreterFrameState::predecessor_at(), v8::internal::maglev::NodeBase::properties(), v8::base::EnumSet< E, T >::RemoveAll(), v8::base::SmallVector< T, kSize, Allocator >::resize(), v8::base::SmallVector< T, kSize, Allocator >::size(), TRACE_UNTAGGING, v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::Phi::uses_require_31_bit_value(), v8::internal::v8_flags, v8::internal::maglev::OpProperties::value_representation(), and v8::internal::maglev::ValueNode::value_representation().
Referenced by PreProcessBasicBlock().
RegisterNewNode()
void v8::internal::maglev::MaglevPhiRepresentationSelector::RegisterNewNode (ValueNode * node) [private]
Definition at line 1141 of file maglev-phi-representation-selector.cc.
                                                                     {
  if (graph_->has_graph_labeller()) {
    graph_->graph_labeller()->RegisterNode(node);
  }
#ifdef DEBUG
  new_nodes_.insert(node);
#endif
}
References graph_, v8::internal::maglev::Graph::graph_labeller(), v8::internal::maglev::Graph::has_graph_labeller(), and v8::internal::maglev::MaglevGraphLabeller::RegisterNode().
Referenced by AddNode(), and PreparePhiTaggings().
UpdateNodeInputs()
template<class NodeT >
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs (NodeT * n, const ProcessingState * state) [inline], [private]
Definition at line 98 of file maglev-phi-representation-selector.h.
                                                                         {
    NodeBase* node = static_cast<NodeBase*>(n);
    ProcessResult result = ProcessResult::kContinue;
    if (IsUntagging(n->opcode())) {
      if (node->input(0).node()->Is<Phi>() &&
          node->input(0).node()->value_representation() !=
              ValueRepresentation::kTagged) {
        DCHECK_EQ(node->input_count(), 1);
        // This untagging conversion is outdated, since its input has been
        // untagged. Depending on the conversion, it might need to be replaced
        // by another untagged->untagged conversion, or it might need to be
        // removed alltogether (or rather, replaced by an identity node).
        UpdateUntaggingOfPhi(node->input(0).node()->Cast<Phi>(),
                             n->template Cast<ValueNode>());
      }
    } else {
      result = UpdateNonUntaggingNodeInputs(n, state);
    }
    return result;
  }
References v8::internal::maglev::NodeBase::Cast(), DCHECK_EQ, v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::NodeBase::Is(), IsUntagging(), v8::internal::maglev::kContinue, v8::internal::maglev::kTagged, v8::internal::maglev::Input::node(), v8::internal::maglev::NodeTMixin< Base, Derived >::opcode(), v8::base::internal::result, UpdateNonUntaggingNodeInputs(), UpdateUntaggingOfPhi(), and v8::internal::maglev::ValueNode::value_representation().
Referenced by Process().
UpdateNodePhiInput() [1/6]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput (BranchIfToBooleanTrue * node, Phi * phi, int input_index, const ProcessingState * state) [private]
Definition at line 939 of file maglev-phi-representation-selector.cc.
                                  {
  DCHECK_EQ(input_index, 0);
  switch (phi->value_representation()) {
    case ValueRepresentation::kInt32:
      node->OverwriteWith<BranchIfInt32ToBooleanTrue>();
      return ProcessResult::kContinue;
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      node->OverwriteWith<BranchIfFloat64ToBooleanTrue>();
      return ProcessResult::kContinue;
    case ValueRepresentation::kTagged:
      return ProcessResult::kContinue;
    case ValueRepresentation::kUint32:
    case ValueRepresentation::kIntPtr:
      UNREACHABLE();
  }
}
References DCHECK_EQ, v8::internal::maglev::kContinue, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, and v8::internal::UNREACHABLE().
UpdateNodePhiInput() [2/6]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput (CheckNumber * node, Phi * phi, int input_index, const ProcessingState * state) [private]
Definition at line 836 of file maglev-phi-representation-selector.cc.
                                  {
  switch (phi->value_representation()) {
    case ValueRepresentation::kInt32:
    case ValueRepresentation::kFloat64:
      // The phi was untagged to a Int32 or Float64, so we know that it's a
      // number. We thus remove this CheckNumber from the graph.
      return ProcessResult::kRemove;
    case ValueRepresentation::kHoleyFloat64:
      // We need to check that the phi is not the hole nan.
      node->OverwriteWith<CheckHoleyFloat64NotHole>();
      return ProcessResult::kContinue;
    case ValueRepresentation::kTagged:
      // {phi} wasn't untagged, so we don't need to do anything.
      return ProcessResult::kContinue;
    case ValueRepresentation::kUint32:
    case ValueRepresentation::kIntPtr:
      UNREACHABLE();
  }
}
References v8::internal::maglev::kContinue, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kRemove, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, and v8::internal::UNREACHABLE().
UpdateNodePhiInput() [3/6]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput (CheckSmi * node, Phi * phi, int input_index, const ProcessingState * state) [private]
Definition at line 809 of file maglev-phi-representation-selector.cc.
                                                                             {
  DCHECK_EQ(input_index, 0);
  switch (phi->value_representation()) {
    case ValueRepresentation::kTagged:
      return ProcessResult::kContinue;
    case ValueRepresentation::kInt32:
      if (!SmiValuesAre32Bits()) {
        node->OverwriteWith<CheckInt32IsSmi>();
        return ProcessResult::kContinue;
      } else {
        return ProcessResult::kRemove;
      }
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kHoleyFloat64:
      node->OverwriteWith<CheckHoleyFloat64IsSmi>();
      return ProcessResult::kContinue;
    case ValueRepresentation::kUint32:
    case ValueRepresentation::kIntPtr:
      UNREACHABLE();
  }
}
References DCHECK_EQ, v8::internal::maglev::kContinue, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::maglev::kRemove, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::SmiValuesAre32Bits(), and v8::internal::UNREACHABLE().
Referenced by UpdateNodePhiInput(), and UpdateNonUntaggingNodeInputs().
UpdateNodePhiInput() [4/6]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput (NodeBase * node, Phi * phi, int input_index, const ProcessingState * state) [private]
Definition at line 966 of file maglev-phi-representation-selector.cc.
                                                                             {
  if (node->properties().is_conversion()) {
    // {node} can't be an Untagging if we reached this point (because
    // UpdateNodePhiInput is not called on untagging nodes).
    DCHECK(!IsUntagging(node->opcode()));
    // So, {node} has to be a conversion that takes an input an untagged node,
    // and this input happens to be {phi}, which means that {node} is aware that
    // {phi} isn't tagged. This means that {node} was inserted during the
    // current phase. In this case, we don't do anything.
    DCHECK_NE(phi->value_representation(), ValueRepresentation::kTagged);
    DCHECK_NE(new_nodes_.find(node), new_nodes_.end());
  } else {
    node->change_input(
        input_index,
        EnsurePhiTagged(phi, current_block_,
                        NewNodePosition::kBeginingOfCurrentBlock, state));
  }
  return ProcessResult::kContinue;
}
References v8::internal::maglev::NodeBase::change_input(), current_block_, v8::internal::DCHECK(), DCHECK_NE, EnsurePhiTagged(), v8::internal::maglev::OpProperties::is_conversion(), IsUntagging(), kBeginingOfCurrentBlock, v8::internal::maglev::kContinue, v8::internal::maglev::kTagged, v8::internal::maglev::NodeBase::opcode(), and v8::internal::maglev::NodeBase::properties().
UpdateNodePhiInput() [5/6]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput (StoreFixedArrayElementNoWriteBarrier * node, Phi * phi, int input_index, const ProcessingState * state) [private]
Definition at line 907 of file maglev-phi-representation-selector.cc.
                                  {
  if (input_index != StoreFixedArrayElementNoWriteBarrier::kValueIndex) {
    return UpdateNodePhiInput(static_cast<NodeBase*>(node), phi, input_index,
                              state);
  }
  if (phi->value_representation() != ValueRepresentation::kTagged) {
    // We need to tag {phi}. However, this could turn it into a HeapObject
    // rather than a Smi (either because {phi} is a Float64 phi, or because it's
    // an Int32/Uint32 phi that doesn't fit on 31 bits), so we need the write
    // barrier.
    node->change_input(
        input_index,
        EnsurePhiTagged(phi, current_block_,
                        NewNodePosition::kBeginingOfCurrentBlock, state));
    static_assert(StoreFixedArrayElementNoWriteBarrier::kElementsIndex ==
                  StoreFixedArrayElementWithWriteBarrier::kElementsIndex);
    static_assert(StoreFixedArrayElementNoWriteBarrier::kIndexIndex ==
                  StoreFixedArrayElementWithWriteBarrier::kIndexIndex);
    static_assert(StoreFixedArrayElementNoWriteBarrier::kValueIndex ==
                  StoreFixedArrayElementWithWriteBarrier::kValueIndex);
    node->OverwriteWith<StoreFixedArrayElementWithWriteBarrier>();
  }
  return ProcessResult::kContinue;
}
References current_block_, EnsurePhiTagged(), kBeginingOfCurrentBlock, v8::internal::maglev::kContinue, v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kElementsIndex, v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kElementsIndex, v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kIndexIndex, v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kIndexIndex, v8::internal::maglev::kTagged, v8::internal::maglev::StoreFixedArrayElementWithWriteBarrier::kValueIndex, v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kValueIndex, and UpdateNodePhiInput().
UpdateNodePhiInput() [6/6]
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput (StoreTaggedFieldNoWriteBarrier * node, Phi * phi, int input_index, const ProcessingState * state) [private]
Definition at line 872 of file maglev-phi-representation-selector.cc.
                                  {
  if (input_index == StoreTaggedFieldNoWriteBarrier::kObjectIndex) {
    // The 1st input of a Store should usually not be untagged. However, it is
    // possible to write `let x = a ? 4 : 2; x.c = 10`, which will produce a
    // store whose receiver could be an untagged Phi. So, for such cases, we use
    // the generic UpdateNodePhiInput method to tag `phi` if needed.
    return UpdateNodePhiInput(static_cast<NodeBase*>(node), phi, input_index,
                              state);
  }
  DCHECK_EQ(input_index, StoreTaggedFieldNoWriteBarrier::kValueIndex);
  if (phi->value_representation() != ValueRepresentation::kTagged) {
    // We need to tag {phi}. However, this could turn it into a HeapObject
    // rather than a Smi (either because {phi} is a Float64 phi, or because it's
    // an Int32/Uint32 phi that doesn't fit on 31 bits), so we need the write
    // barrier.
    node->change_input(
        input_index,
        EnsurePhiTagged(phi, current_block_,
                        NewNodePosition::kBeginingOfCurrentBlock, state));
    static_assert(StoreTaggedFieldNoWriteBarrier::kObjectIndex ==
                  StoreTaggedFieldWithWriteBarrier::kObjectIndex);
    static_assert(StoreTaggedFieldNoWriteBarrier::kValueIndex ==
                  StoreTaggedFieldWithWriteBarrier::kValueIndex);
    node->OverwriteWith<StoreTaggedFieldWithWriteBarrier>();
  }
  return ProcessResult::kContinue;
}
References current_block_, DCHECK_EQ, EnsurePhiTagged(), kBeginingOfCurrentBlock, v8::internal::maglev::kContinue, v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::kObjectIndex, v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::kObjectIndex, v8::internal::maglev::kTagged, v8::internal::maglev::StoreTaggedFieldNoWriteBarrier::kValueIndex, v8::internal::maglev::StoreTaggedFieldWithWriteBarrier::kValueIndex, and UpdateNodePhiInput().
UpdateNonUntaggingNodeInputs()
template<class NodeT >
ProcessResult v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs (NodeT * n, const ProcessingState * state) [inline], [private]
Definition at line 122 of file maglev-phi-representation-selector.h.
                                                                           {
    NodeBase* node = static_cast<NodeBase*>(n);
    // It would be bad to re-tag the input of an untagging node, so this
    // function should never be called on untagging nodes.
    DCHECK(!IsUntagging(n->opcode()));
    for (int i = 0; i < n->input_count(); i++) {
      ValueNode* input = node->input(i).node();
      if (input->Is<Identity>()) {
        // Bypassing the identity
        node->change_input(i, input->input(0).node());
      } else if (Phi* phi = input->TryCast<Phi>()) {
        // If the input is a Phi and it was used without any untagging, then
        // we need to retag it (with some additional checks/changes for some
        // nodes, cf the overload of UpdateNodePhiInput).
        ProcessResult result = UpdateNodePhiInput(n, phi, i, state);
        if (V8_UNLIKELY(result == ProcessResult::kRemove)) {
          return ProcessResult::kRemove;
        }
      }
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::NodeBase::change_input(), v8::internal::DCHECK(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::Is(), IsUntagging(), v8::internal::maglev::kContinue, v8::internal::maglev::kRemove, v8::internal::maglev::Input::node(), v8::internal::maglev::NodeTMixin< Base, Derived >::opcode(), v8::base::internal::result, v8::internal::maglev::NodeBase::TryCast(), UpdateNodePhiInput(), and V8_UNLIKELY.
Referenced by UpdateNodeInputs().
UpdateUntaggingOfPhi()
void v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi (Phi * phi, ValueNode * old_untagging) [private]
Definition at line 729 of file maglev-phi-representation-selector.cc.
                                        {
  DCHECK_EQ(old_untagging->input_count(), 1);
  DCHECK(old_untagging->input(0).node()->Is<Phi>());
  ValueRepresentation from_repr =
      old_untagging->input(0).node()->value_representation();
  ValueRepresentation to_repr = old_untagging->value_representation();
  // Since initially Phis are tagged, it would make not sense for
  // {old_conversion} to convert a Phi to a Tagged value.
  DCHECK_NE(to_repr, ValueRepresentation::kTagged);
  // The graph builder never inserts Tagged->Uint32 conversions (and thus, we
  // don't handle them in GetOpcodeForCheckedConversion).
  DCHECK_NE(to_repr, ValueRepresentation::kUint32);
  if (from_repr == ValueRepresentation::kTagged) {
    // The Phi hasn't been untagged, so we leave the conversion as it is.
    return;
  }
  if (from_repr == to_repr) {
    if (from_repr == ValueRepresentation::kInt32) {
      if (phi->uses_require_31_bit_value() &&
          old_untagging->Is<CheckedSmiUntag>()) {
        old_untagging->OverwriteWith<CheckedSmiSizedInt32>();
        return;
      }
    }
    old_untagging->OverwriteWith<Identity>();
    return;
  }
  if (old_untagging->Is<UnsafeSmiUntag>()) {
    // UnsafeSmiTag are only inserted when the node is a known Smi. If the
    // current phi has a Float64/Uint32 representation, then we can safely
    // truncate it to Int32, because we know that the Float64/Uint32 fits in a
    // Smi, and therefore in an Int32.
    if (from_repr == ValueRepresentation::kFloat64 ||
        from_repr == ValueRepresentation::kHoleyFloat64) {
      old_untagging->OverwriteWith<UnsafeTruncateFloat64ToInt32>();
    } else if (from_repr == ValueRepresentation::kUint32) {
      old_untagging->OverwriteWith<UnsafeTruncateUint32ToInt32>();
    } else {
      DCHECK_EQ(from_repr, ValueRepresentation::kInt32);
      old_untagging->OverwriteWith<Identity>();
    }
    return;
  }
  // The graph builder inserts 3 kind of Tagged->Int32 conversions that can have
  // heap number as input: CheckedTruncateNumberToInt32, which truncates its
  // input (and deopts if it's not a HeapNumber), TruncateNumberToInt32, which
  // truncates its input (assuming that it's indeed a HeapNumber) and
  // CheckedSmiTag, which deopts on non-smi inputs. The first 2 cannot deopt if
  // we have Float64 phi and will happily truncate it, but the 3rd one should
  // deopt if it cannot be converted without loss of precision.
  bool conversion_is_truncating_float64 =
      old_untagging->Is<CheckedTruncateNumberOrOddballToInt32>() ||
      old_untagging->Is<TruncateNumberOrOddballToInt32>();
  Opcode needed_conversion = GetOpcodeForConversion(
      from_repr, to_repr, conversion_is_truncating_float64);
  if (CheckedNumberOrOddballToFloat64* number_untagging =
          old_untagging->TryCast<CheckedNumberOrOddballToFloat64>()) {
    if (from_repr == ValueRepresentation::kHoleyFloat64 &&
        number_untagging->conversion_type() !=
            TaggedToFloat64ConversionType::kNumberOrOddball) {
      // {phi} is a HoleyFloat64 (and thus, it could be a hole), but the
      // original untagging did not allow holes.
      needed_conversion = Opcode::kCheckedHoleyFloat64ToFloat64;
    }
  }
  if (needed_conversion != old_untagging->opcode()) {
    old_untagging->OverwriteWith(needed_conversion);
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::maglev::anonymous_namespace{maglev-phi-representation-selector.cc}::GetOpcodeForConversion(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::input_count(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kNumberOrOddball, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::maglev::Input::node(), v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::NodeBase::OverwriteWith(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::Phi::uses_require_31_bit_value(), and v8::internal::maglev::ValueNode::value_representation().
Referenced by UpdateNodeInputs().
zone()
Zone* v8::internal::maglev::MaglevPhiRepresentationSelector::zone () const [inline], [private]
Definition at line 209 of file maglev-phi-representation-selector.h.
{ return graph_->zone(); }
References graph_, and v8::internal::maglev::Graph::zone().
Referenced by AddNode(), ConvertTaggedPhiTo(), EnsurePhiTagged(), GetReplacementForPhiInputConversion(), and PreparePhiTaggings().
Member Data Documentation
current_block_
BasicBlock* v8::internal::maglev::MaglevPhiRepresentationSelector::current_block_ = nullptr [private]
Definition at line 212 of file maglev-phi-representation-selector.h.
Referenced by AddNode(), EnsurePhiTagged(), FixLoopPhisBackedge(), PreProcessBasicBlock(), and UpdateNodePhiInput().
graph_
Graph* v8::internal::maglev::MaglevPhiRepresentationSelector::graph_ [private]
Definition at line 211 of file maglev-phi-representation-selector.h.
Referenced by ConvertTaggedPhiTo(), graph_labeller(), PreProcessGraph(), ProcessPhi(), RegisterNewNode(), and zone().
new_nodes_at_start_
ZoneVector<Node*> v8::internal::maglev::MaglevPhiRepresentationSelector::new_nodes_at_start_ [private]
Definition at line 221 of file maglev-phi-representation-selector.h.
Referenced by AddNode(), and PostProcessBasicBlock().
phi_taggings_
SnapshotTable<ValueNode*> v8::internal::maglev::MaglevPhiRepresentationSelector::phi_taggings_ [private]
Definition at line 216 of file maglev-phi-representation-selector.h.
Referenced by EnsurePhiTagged(), and PreparePhiTaggings().
predecessors_
ZoneVector<Snapshot> v8::internal::maglev::MaglevPhiRepresentationSelector::predecessors_ [private]
Definition at line 219 of file maglev-phi-representation-selector.h.
Referenced by PreparePhiTaggings().
snapshots_
absl::flat_hash_map<BasicBlock::Id, Snapshot> v8::internal::maglev::MaglevPhiRepresentationSelector::snapshots_ [private]
Definition at line 223 of file maglev-phi-representation-selector.h.
Referenced by PreparePhiTaggings().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-phi-representation-selector.h
/mnt/V8SourceCode/src/maglev/maglev-phi-representation-selector.cc