v8::internal::interpreter::BytecodeGenerator Class Reference
#include <bytecode-generator.h>
Classes
class AccumulatorPreservingScope
class AssignmentLhsData
class ContextScope
class ControlScope
class ControlScopeForBreakable
class ControlScopeForDerivedConstructor
class ControlScopeForIteration
class ControlScopeForTopLevel
class ControlScopeForTryCatch
class ControlScopeForTryFinally
class CurrentScope
class DisposablesStackScope
class EffectResultScope
class ExpressionResultScope
class FeedbackSlotCache
class ForInScope
class HoleCheckElisionMergeScope
class HoleCheckElisionScope
class IteratorRecord
class LoopScope
class MultipleEntryBlockContextScope
class NaryCodeCoverageSlots
class OptionalChainNullLabelScope
class RegisterAllocationScope
class TestResultScope
class TopLevelDeclarationsBuilder
class ValueResultScope
Public Types
enum TypeHint : uint8_t {
kBoolean = 1 << 0
, kInternalizedString = 1 << 1
, kString = kInternalizedString | (1 << 2)
, kAny = kBoolean | kString
,
kUnknown = 0xFFu
 }
Public Member Functions
BytecodeGenerator (LocalIsolate *local_isolate, Zone *zone, UnoptimizedCompilationInfo *info, const AstStringConstants *ast_string_constants, std::vector< FunctionLiteral * > *eager_inner_literals, Handle< Script > script)
void GenerateBytecode (uintptr_t stack_limit)
template<typename IsolateT >
Handle< BytecodeArray > FinalizeBytecode (IsolateT *isolate, Handle< Script > script)
template<typename IsolateT >
DirectHandle< TrustedByteArray > FinalizeSourcePositionTable (IsolateT *isolate)
void VisitModuleDeclarations (Declaration::List *declarations)
void VisitGlobalDeclarations (Declaration::List *declarations)
void VisitDeclarations (Declaration::List *declarations)
void VisitStatements (const ZonePtrList< Statement > *statments, int start=0)
Static Public Member Functions
static bool IsSameOrSubTypeHint (TypeHint hint1, TypeHint hint2)
static bool IsStringTypeHint (TypeHint hint)
Private Types
enum class TestFallthrough { kThen
, kElse
, kNone
 }
enum class AccumulatorPreservingMode { kNone
, kPreserve
 }
using ToBooleanMode = BytecodeArrayBuilder::ToBooleanMode
Private Member Functions
void GenerateBytecodeBody ()
void GenerateBaseConstructorBody ()
void GenerateDerivedConstructorBody ()
void GenerateAsyncFunctionBody ()
void GenerateAsyncGeneratorFunctionBody ()
void GenerateBodyPrologue ()
void GenerateBodyStatements (int start=0)
void GenerateBodyStatementsWithoutImplicitFinalReturn (int start=0)
template<typename IsolateT >
void AllocateDeferredConstants (IsolateT *isolate, Handle< Script > script)
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS ()
void VisitArithmeticExpression (BinaryOperation *binop)
void VisitCommaExpression (BinaryOperation *binop)
void VisitLogicalOrExpression (BinaryOperation *binop)
void VisitLogicalAndExpression (BinaryOperation *binop)
void VisitNullishExpression (BinaryOperation *binop)
void VisitNaryArithmeticExpression (NaryOperation *expr)
void VisitNaryCommaExpression (NaryOperation *expr)
void VisitNaryLogicalOrExpression (NaryOperation *expr)
void VisitNaryLogicalAndExpression (NaryOperation *expr)
void VisitNaryNullishExpression (NaryOperation *expr)
void VisitVoid (UnaryOperation *expr)
void VisitTypeOf (UnaryOperation *expr)
void VisitNot (UnaryOperation *expr)
void VisitDelete (UnaryOperation *expr)
void VisitForTypeOfValue (Expression *expr)
void VisitCondition (Expression *expr)
void VisitArguments (const ZonePtrList< Expression > *args, RegisterList *arg_regs)
void VisitKeyedSuperPropertyLoad (Property *property, Register opt_receiver_out)
void VisitNamedSuperPropertyLoad (Property *property, Register opt_receiver_out)
void VisitPropertyLoad (Register obj, Property *expr)
void VisitPropertyLoadForRegister (Register obj, Property *expr, Register destination)
bool BuildInitializationBlockForParametersIfExist ()
AssignmentLhsData PrepareAssignmentLhs (Expression *lhs, AccumulatorPreservingMode accumulator_preserving_mode=AccumulatorPreservingMode::kNone)
void BuildAssignment (const AssignmentLhsData &data, Token::Value op, LookupHoistingMode lookup_hoisting_mode)
void BuildThisVariableLoad ()
void BuildDeclareCall (Runtime::FunctionId id)
Expression * GetDestructuringDefaultValue (Expression **target)
void BuildDestructuringArrayAssignment (ArrayLiteral *pattern, Token::Value op, LookupHoistingMode lookup_hoisting_mode)
void BuildDestructuringObjectAssignment (ObjectLiteral *pattern, Token::Value op, LookupHoistingMode lookup_hoisting_mode)
void BuildLoadNamedProperty (const Expression *object_expr, Register object, const AstRawString *name)
void BuildSetNamedProperty (const Expression *object_expr, Register object, const AstRawString *name)
void BuildStoreGlobal (Variable *variable)
void BuildLoadKeyedProperty (Register object, FeedbackSlot slot)
bool IsVariableInRegister (Variable *var, Register reg)
void SetVariableInRegister (Variable *var, Register reg)
Variable * GetPotentialVariableInAccumulator ()
void AddDisposableValue (VariableMode mode)
void BuildVariableLoad (Variable *variable, HoleCheckMode hole_check_mode, TypeofMode typeof_mode=TypeofMode::kNotInside)
void BuildVariableLoadForAccumulatorValue (Variable *variable, HoleCheckMode hole_check_mode, TypeofMode typeof_mode=TypeofMode::kNotInside)
void BuildVariableAssignment (Variable *variable, Token::Value op, HoleCheckMode hole_check_mode, LookupHoistingMode lookup_hoisting_mode=LookupHoistingMode::kNormal)
void BuildLiteralCompareNil (Token::Value compare_op, BytecodeArrayBuilder::NilValue nil)
void BuildLiteralStrictCompareBoolean (Literal *literal)
void BuildReturn (int source_position)
void BuildAsyncReturn (int source_position)
void BuildAsyncGeneratorReturn ()
void BuildReThrow ()
void RememberHoleCheckInCurrentBlock (Variable *variable)
bool VariableNeedsHoleCheckInCurrentBlock (Variable *variable, HoleCheckMode hole_check_mode)
bool VariableNeedsHoleCheckInCurrentBlockForAssignment (Variable *variable, Token::Value op, HoleCheckMode hole_check_mode)
void BuildHoleCheckForVariableAssignment (Variable *variable, Token::Value op)
void BuildThrowIfHole (Variable *variable)
void BuildNewLocalActivationContext ()
void BuildLocalActivationContextInitialization ()
void BuildNewLocalBlockContext (Scope *scope)
void BuildNewLocalCatchContext (Scope *scope)
void BuildNewLocalWithContext (Scope *scope)
void BuildGeneratorPrologue ()
void BuildSuspendPoint (int position)
void BuildAwait (int position=kNoSourcePosition)
void BuildAwait (Expression *await_expr)
void BuildFinalizeIteration (IteratorRecord iterator, Register done, Register iteration_continuation_token)
void BuildGetIterator (IteratorType hint)
IteratorRecord BuildGetIteratorRecord (Register iterator_next, Register iterator_object, IteratorType hint)
IteratorRecord BuildGetIteratorRecord (IteratorType hint)
void BuildIteratorNext (const IteratorRecord &iterator, Register next_result)
void BuildIteratorClose (const IteratorRecord &iterator, Expression *expr=nullptr)
void BuildCallIteratorMethod (Register iterator, const AstRawString *method, RegisterList receiver_and_args, BytecodeLabel *if_called, BytecodeLabels *if_notcalled)
void BuildFillArrayWithIterator (IteratorRecord iterator, Register array, Register index, Register value, FeedbackSlot next_value_slot, FeedbackSlot next_done_slot, FeedbackSlot index_slot, FeedbackSlot element_slot)
void BuildCreateArrayLiteral (const ZonePtrList< Expression > *elements, ArrayLiteral *expr)
void BuildCreateObjectLiteral (Register literal, uint8_t flags, size_t entry)
void AllocateTopLevelRegisters ()
void VisitArgumentsObject (Variable *variable)
void VisitRestArgumentsArray (Variable *rest)
void VisitCallSuper (Call *call)
void BuildInstanceInitializationAfterSuperCall (Register this_function, Register instance)
void BuildInvalidPropertyAccess (MessageTemplate tmpl, Property *property)
void BuildPrivateBrandCheck (Property *property, Register object)
void BuildPrivateMethodIn (Variable *private_name, Expression *object_expression)
void BuildPrivateGetterAccess (Register obj, Register access_pair)
void BuildPrivateSetterAccess (Register obj, Register access_pair, Register value)
void BuildPrivateDebugDynamicGet (Property *property, Register obj)
void BuildPrivateDebugDynamicSet (Property *property, Register obj, Register value)
void BuildPrivateMethods (ClassLiteral *expr, bool is_static, Register home_object)
void BuildClassProperty (ClassLiteral::Property *property)
void BuildClassLiteral (ClassLiteral *expr, Register name)
void VisitClassLiteral (ClassLiteral *expr, Register name)
void VisitNewTargetVariable (Variable *variable)
void VisitThisFunctionVariable (Variable *variable)
void BuildPrivateBrandInitialization (Register receiver, Variable *brand)
void BuildInstanceMemberInitialization (Register constructor, Register instance)
void BuildGeneratorObjectVariableInitialization ()
void VisitBlockDeclarationsAndStatements (Block *stmt)
void VisitBlockMaybeDispose (Block *stmt)
void VisitLiteralAccessor (LiteralProperty *property, Register value_out)
void VisitForInAssignment (Expression *expr)
void VisitModuleNamespaceImports ()
void VisitLogicalTest (Token::Value token, Expression *left, Expression *right, int right_coverage_slot)
void VisitNaryLogicalTest (Token::Value token, NaryOperation *expr, const NaryCodeCoverageSlots *coverage_slots)
void VisitLogicalTestSubExpression (Token::Value token, Expression *expr, BytecodeLabels *then_labels, BytecodeLabels *else_labels, int coverage_slot)
bool VisitLogicalOrSubExpression (Expression *expr, BytecodeLabels *end_labels, int coverage_slot)
bool VisitLogicalAndSubExpression (Expression *expr, BytecodeLabels *end_labels, int coverage_slot)
bool VisitNullishSubExpression (Expression *expr, BytecodeLabels *end_labels, int coverage_slot)
void VisitIterationBody (IterationStatement *stmt, LoopBuilder *loop_builder)
void VisitInScope (Statement *stmt, Scope *scope)
void BuildPushUndefinedIntoRegisterList (RegisterList *reg_list)
void BuildLoadPropertyKey (LiteralProperty *property, Register out_reg)
int AllocateBlockCoverageSlotIfEnabled (AstNode *node, SourceRangeKind kind)
int AllocateNaryBlockCoverageSlotIfEnabled (NaryOperation *node, size_t index)
int AllocateConditionalChainBlockCoverageSlotIfEnabled (ConditionalChain *node, SourceRangeKind kind, size_t index)
void BuildIncrementBlockCoverageCounterIfEnabled (AstNode *node, SourceRangeKind kind)
void BuildIncrementBlockCoverageCounterIfEnabled (int coverage_array_slot)
void BuildTest (ToBooleanMode mode, BytecodeLabels *then_labels, BytecodeLabels *else_labels, TestFallthrough fallthrough)
template<typename TryBodyFunc , typename CatchBodyFunc >
void BuildTryCatch (TryBodyFunc try_body_func, CatchBodyFunc catch_body_func, HandlerTable::CatchPrediction catch_prediction, TryCatchStatement *stmt_for_coverage=nullptr)
template<typename TryBodyFunc , typename FinallyBodyFunc >
void BuildTryFinally (TryBodyFunc try_body_func, FinallyBodyFunc finally_body_func, HandlerTable::CatchPrediction catch_prediction, TryFinallyStatement *stmt_for_coverage=nullptr)
template<typename WrappedFunc >
void BuildDisposeScope (WrappedFunc wrapped_func, bool has_await_using)
template<typename ExpressionFunc >
void BuildOptionalChain (ExpressionFunc expression_func)
void BuildGetAndCheckSuperConstructor (Register this_function, Register new_target, Register constructor, BytecodeLabel *super_ctor_call_done)
void BuildSuperCallOptimization (Register this_function, Register new_target, Register constructor_then_instance, BytecodeLabel *super_ctor_call_done)
TypeHint VisitForAccumulatorValue (Expression *expr)
TypeHint VisitForAccumulatorValueAsPropertyKey (Expression *expr)
TypeHint VisitForAccumulatorValueImpl (Expression *expr, ValueResultScope *accumulator_scope)
void VisitForAccumulatorValueOrTheHole (Expression *expr)
V8_WARN_UNUSED_RESULT Register VisitForRegisterValue (Expression *expr)
void VisitForRegisterValue (Expression *expr, Register destination)
void VisitAndPushIntoRegisterList (Expression *expr, RegisterList *reg_list)
void VisitForEffect (Expression *expr)
void VisitForTest (Expression *expr, BytecodeLabels *then_labels, BytecodeLabels *else_labels, TestFallthrough fallthrough)
void VisitForNullishTest (Expression *expr, BytecodeLabels *then_labels, BytecodeLabels *test_next_labels, BytecodeLabels *else_labels)
template<typename T >
void VisitInHoleCheckElisionScope (T *node)
void VisitIterationBodyInHoleCheckElisionScope (IterationStatement *stmt, LoopBuilder *loop_builder)
TypeHint VisitInHoleCheckElisionScopeForAccumulatorValue (Expression *expr)
void VisitInSameTestExecutionScope (Expression *expr)
Register GetRegisterForLocalVariable (Variable *variable)
bool IsLocalVariableWithInternalizedStringHint (Expression *expr)
TypeHint GetTypeHintForLocalVariable (Variable *variable)
Runtime::FunctionId StoreToSuperRuntimeId ()
Runtime::FunctionId StoreKeyedToSuperRuntimeId ()
FeedbackSlot GetCachedLoadGlobalICSlot (TypeofMode typeof_mode, Variable *variable)
FeedbackSlot GetCachedStoreGlobalICSlot (LanguageMode language_mode, Variable *variable)
FeedbackSlot GetCachedLoadICSlot (const Expression *expr, const AstRawString *name)
FeedbackSlot GetCachedLoadSuperICSlot (const AstRawString *name)
FeedbackSlot GetCachedStoreICSlot (const Expression *expr, const AstRawString *name)
FeedbackSlot GetDummyCompareICSlot ()
int GetCachedCreateClosureSlot (FunctionLiteral *literal)
void AddToEagerLiteralsIfEager (FunctionLiteral *literal)
Register incoming_new_target () const
Register generator_object () const
BytecodeArrayBuilder * builder ()
Zone * zone () const
DeclarationScope * closure_scope () const
UnoptimizedCompilationInfo * info () const
const AstStringConstants * ast_string_constants () const
Scope * current_scope () const
void set_current_scope (Scope *scope)
ControlScope * execution_control () const
void set_execution_control (ControlScope *scope)
ContextScope * execution_context () const
void set_execution_context (ContextScope *context)
void set_execution_result (ExpressionResultScope *execution_result)
ExpressionResultScope * execution_result () const
BytecodeRegisterAllocator * register_allocator ()
TopLevelDeclarationsBuilder * top_level_builder ()
LanguageMode language_mode () const
FunctionKind function_kind () const
FeedbackVectorSpec * feedback_spec ()
int feedback_index (FeedbackSlot slot) const
FeedbackSlotCache * feedback_slot_cache ()
HandlerTable::CatchPrediction catch_prediction () const
void set_catch_prediction (HandlerTable::CatchPrediction value)
LoopScope * current_loop_scope () const
void set_current_loop_scope (LoopScope *loop_scope)
ForInScope * current_for_in_scope () const
void set_current_for_in_scope (ForInScope *for_in_scope)
Register current_disposables_stack () const
void set_current_disposables_stack (Register disposables_stack)
Static Private Member Functions
static constexpr ToBooleanMode ToBooleanModeFromTypeHint (TypeHint type_hint)
Private Attributes
LocalIsolate * local_isolate_
Zone * zone_
BytecodeArrayBuilder builder_
UnoptimizedCompilationInfo * info_
const AstStringConstants * ast_string_constants_
DeclarationScope * closure_scope_
Scope * current_scope_
std::vector< FunctionLiteral * > * eager_inner_literals_
Handle< Script > script_
FeedbackSlotCache * feedback_slot_cache_
TopLevelDeclarationsBuilder * top_level_builder_
BlockCoverageBuilder * block_coverage_builder_
ZoneVector< std::pair< FunctionLiteral *, size_t > > function_literals_
ZoneVector< std::pair< NativeFunctionLiteral *, size_t > > native_function_literals_
ZoneVector< std::pair< ObjectLiteralBoilerplateBuilder *, size_t > > object_literals_
ZoneVector< std::pair< ArrayLiteralBoilerplateBuilder *, size_t > > array_literals_
ZoneVector< std::pair< ClassLiteral *, size_t > > class_literals_
ZoneVector< std::pair< GetTemplateObject *, size_t > > template_objects_
ZoneVector< Variable * > vars_in_hole_check_bitmap_
ZoneVector< std::pair< Call *, Scope * > > eval_calls_
ControlScope * execution_control_
ContextScope * execution_context_
ExpressionResultScope * execution_result_
Register incoming_new_target_or_generator_
Register current_disposables_stack_
BytecodeLabels * optional_chaining_null_labels_
SharedFeedbackSlot dummy_feedback_slot_
BytecodeJumpTable * generator_jump_table_
int suspend_count_
int loop_depth_
Variable::HoleCheckBitmap hole_check_bitmap_
LoopScope * current_loop_scope_
ForInScope * current_for_in_scope_
HandlerTable::CatchPrediction catch_prediction_
Additional Inherited Members
Detailed Description
Definition at line 32 of file bytecode-generator.h.
Member Typedef Documentation
ToBooleanMode
using v8::internal::interpreter::BytecodeGenerator::ToBooleanMode = BytecodeArrayBuilder::ToBooleanMode [private]
Definition at line 106 of file bytecode-generator.h.
Member Enumeration Documentation
AccumulatorPreservingMode
enum v8::internal::interpreter::BytecodeGenerator::AccumulatorPreservingMode [strong], [private]
Enumerator
kNone
kPreserve
Definition at line 109 of file bytecode-generator.h.
{ kNone, kPreserve };
TestFallthrough
enum v8::internal::interpreter::BytecodeGenerator::TestFallthrough [strong], [private]
Enumerator
kThen
kElse
kNone
Definition at line 108 of file bytecode-generator.h.
{ kThen, kElse, kNone };
TypeHint
enum v8::internal::interpreter::BytecodeGenerator::TypeHint : uint8_t
Enumerator
kBoolean
kInternalizedString
kString
kAny
kUnknown
Definition at line 34 of file bytecode-generator.h.
                : uint8_t {
    kBoolean = 1 << 0,
    kInternalizedString = 1 << 1,
    kString = kInternalizedString | (1 << 2),
    kAny = kBoolean | kString,
    kUnknown = 0xFFu
  };
Constructor & Destructor Documentation
BytecodeGenerator()
v8::internal::interpreter::BytecodeGenerator::BytecodeGenerator (LocalIsolate * local_isolate, Zone * zone, UnoptimizedCompilationInfo * info, const AstStringConstants * ast_string_constants, std::vector< FunctionLiteral * > * eager_inner_literals, Handle< Script > script) [explicit]
Definition at line 1406 of file bytecode-generator.cc.
    : local_isolate_(local_isolate),
      zone_(compile_zone),
      builder_(zone(), info->num_parameters_including_this(),
               info->scope()->num_stack_slots(), info->feedback_vector_spec(),
               info->SourcePositionRecordingMode()),
      info_(info),
      ast_string_constants_(ast_string_constants),
      closure_scope_(info->scope()),
      current_scope_(info->scope()),
      eager_inner_literals_(eager_inner_literals),
      script_(script),
      feedback_slot_cache_(zone()->New<FeedbackSlotCache>(zone())),
      top_level_builder_(zone()->New<TopLevelDeclarationsBuilder>()),
      block_coverage_builder_(nullptr),
      function_literals_(0, zone()),
      native_function_literals_(0, zone()),
      object_literals_(0, zone()),
      array_literals_(0, zone()),
      class_literals_(0, zone()),
      template_objects_(0, zone()),
      vars_in_hole_check_bitmap_(0, zone()),
      eval_calls_(0, zone()),
      execution_control_(nullptr),
      execution_context_(nullptr),
      execution_result_(nullptr),
      incoming_new_target_or_generator_(),
      current_disposables_stack_(),
      optional_chaining_null_labels_(nullptr),
      dummy_feedback_slot_(feedback_spec(), FeedbackSlotKind::kCompareOp),
      generator_jump_table_(nullptr),
      suspend_count_(0),
      loop_depth_(0),
      hole_check_bitmap_(0),
      current_loop_scope_(nullptr),
      current_for_in_scope_(nullptr),
      catch_prediction_(HandlerTable::UNCAUGHT) {
  DCHECK_EQ(closure_scope(), closure_scope()->GetClosureScope());
  if (info->has_source_range_map()) {
    block_coverage_builder_ = zone()->New<BlockCoverageBuilder>(
        zone(), builder(), info->source_range_map());
  }
}
References block_coverage_builder_, builder(), closure_scope(), DCHECK_EQ, v8::internal::UnoptimizedCompilationInfo::has_source_range_map(), info(), v8::internal::kCompareOp, v8::internal::Zone::New(), v8::internal::UnoptimizedCompilationInfo::source_range_map(), and zone().
Member Function Documentation
AddDisposableValue()
void v8::internal::interpreter::BytecodeGenerator::AddDisposableValue (VariableMode mode) [private]
Definition at line 4729 of file bytecode-generator.cc.
                                                            {
  if (mode == VariableMode::kUsing) {
    RegisterList args = register_allocator()->NewRegisterList(2);
    builder()
        ->MoveRegister(current_disposables_stack(), args[0])
        .StoreAccumulatorInRegister(args[1])
        .CallRuntime(Runtime::kAddDisposableValue, args);
  } else if (mode == VariableMode::kAwaitUsing) {
    RegisterList args = register_allocator()->NewRegisterList(2);
    builder()
        ->MoveRegister(current_disposables_stack(), args[0])
        .StoreAccumulatorInRegister(args[1])
        .CallRuntime(Runtime::kAddAsyncDisposableValue, args);
  }
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), current_disposables_stack(), v8::internal::kAwaitUsing, v8::internal::kUsing, mode(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildVariableAssignment().
AddToEagerLiteralsIfEager()
void v8::internal::interpreter::BytecodeGenerator::AddToEagerLiteralsIfEager (FunctionLiteral * literal) [private]
Definition at line 3282 of file bytecode-generator.cc.
                                                                          {
  // Only parallel compile when there's a script (not the case for source
  // position collection).
  if (!script_.is_null() && literal->should_parallel_compile()) {
    // If we should normally be eagerly compiling this function, we must be here
    // because of post_parallel_compile_tasks_for_eager_toplevel.
    DCHECK_IMPLIES(
        literal->ShouldEagerCompile(),
        info()->flags().post_parallel_compile_tasks_for_eager_toplevel());
    // There exists a lazy compile dispatcher.
    DCHECK(info()->dispatcher());
    // There exists a cloneable character stream.
    DCHECK(info()->character_stream()->can_be_cloned_for_parallel_access());
    UnparkedScopeIfOnBackground scope(local_isolate_);
    // If there doesn't already exist a SharedFunctionInfo for this function,
    // then create one and enqueue it. Otherwise, we're reparsing (e.g. for the
    // debugger, source position collection, call printing, recompile after
    // flushing, etc.) and don't want to over-compile.
    DirectHandle<SharedFunctionInfo> shared_info =
        Compiler::GetSharedFunctionInfo(literal, script_, local_isolate_);
    if (!shared_info->is_compiled()) {
      info()->dispatcher()->Enqueue(
          local_isolate_, indirect_handle(shared_info, local_isolate_),
          info()->character_stream()->Clone());
    }
  } else if (eager_inner_literals_ && literal->ShouldEagerCompile()) {
    DCHECK(!IsInEagerLiterals(literal, *eager_inner_literals_));
    DCHECK(!literal->should_parallel_compile());
    eager_inner_literals_->push_back(literal);
  }
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::UnoptimizedCompilationInfo::dispatcher(), eager_inner_literals_, v8::internal::LazyCompileDispatcher::Enqueue(), v8::internal::flags, v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::indirect_handle(), info(), local_isolate_, script_, v8::internal::FunctionLiteral::should_parallel_compile(), and v8::internal::FunctionLiteral::ShouldEagerCompile().
Referenced by VisitGlobalDeclarations(), and VisitModuleDeclarations().
AllocateBlockCoverageSlotIfEnabled()
int v8::internal::interpreter::BytecodeGenerator::AllocateBlockCoverageSlotIfEnabled (AstNode * node, SourceRangeKind kind) [private]
Definition at line 8435 of file bytecode-generator.cc.
                                         {
  return (block_coverage_builder_ == nullptr)
             ? BlockCoverageBuilder::kNoCoverageArraySlot
             : block_coverage_builder_->AllocateBlockCoverageSlot(node, kind);
}
References v8::internal::interpreter::BlockCoverageBuilder::AllocateBlockCoverageSlot(), block_coverage_builder_, and v8::internal::interpreter::BlockCoverageBuilder::kNoCoverageArraySlot.
Referenced by VisitDelete(), VisitLogicalAndExpression(), VisitLogicalOrExpression(), VisitNullishExpression(), and VisitPropertyLoad().
AllocateConditionalChainBlockCoverageSlotIfEnabled()
int v8::internal::interpreter::BytecodeGenerator::AllocateConditionalChainBlockCoverageSlotIfEnabled (ConditionalChain * node, SourceRangeKind kind, size_t index) [private]
Definition at line 8450 of file bytecode-generator.cc.
                                                                {
  return (block_coverage_builder_ == nullptr)
             ? BlockCoverageBuilder::kNoCoverageArraySlot
             : block_coverage_builder_
                   ->AllocateConditionalChainBlockCoverageSlot(node, kind,
                                                               index);
}
References v8::internal::interpreter::BlockCoverageBuilder::AllocateConditionalChainBlockCoverageSlot(), block_coverage_builder_, v8::internal::index, and v8::internal::interpreter::BlockCoverageBuilder::kNoCoverageArraySlot.
AllocateDeferredConstants()
template<typename IsolateT >
template void v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants (IsolateT * isolate, Handle< Script > script) [private]
Definition at line 1549 of file bytecode-generator.cc.
                                                                         {
  if (top_level_builder()->has_top_level_declaration()) {
    // Build global declaration pair array.
    Handle<FixedArray> declarations = top_level_builder()->AllocateDeclarations(
        info(), this, script, isolate);
    if (declarations.is_null()) return SetStackOverflow();
    builder()->SetDeferredConstantPoolEntry(
        top_level_builder()->constant_pool_entry(), declarations);
  }
  // Find or build shared function infos.
  for (std::pair<FunctionLiteral*, size_t> literal : function_literals_) {
    FunctionLiteral* expr = literal.first;
    DirectHandle<SharedFunctionInfo> shared_info =
        Compiler::GetSharedFunctionInfo(expr, script, isolate);
    if (shared_info.is_null()) return SetStackOverflow();
    builder()->SetDeferredConstantPoolEntry(
        literal.second, indirect_handle(shared_info, isolate));
  }
  // Find or build shared function infos for the native function templates.
  for (std::pair<NativeFunctionLiteral*, size_t> literal :
       native_function_literals_) {
    // This should only happen for main-thread compilations.
    DCHECK((std::is_same_v<Isolate, v8::internal::Isolate>));
    NativeFunctionLiteral* expr = literal.first;
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
    // Compute the function template for the native function.
    v8::Local<v8::FunctionTemplate> info =
        expr->extension()->GetNativeFunctionTemplate(
            v8_isolate, Utils::ToLocal(expr->name()));
    DCHECK(!info.IsEmpty());
    Handle<SharedFunctionInfo> shared_info =
        FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(
            isolate, Utils::OpenDirectHandle(*info), expr->name());
    DCHECK(!shared_info.is_null());
    builder()->SetDeferredConstantPoolEntry(literal.second, shared_info);
  }
  for (std::pair<Call*, Scope*> call : eval_calls_) {
    Tagged<ScopeInfo> current;
    int index = call.first->eval_scope_info_index();
    if (script->infos()->get(index).GetHeapObjectIfWeak(&current) &&
        v8_flags.reuse_scope_infos) {
      CHECK_EQ(current, *call.second->scope_info());
    } else {
      script->infos()->set(call.first->eval_scope_info_index(),
                           MakeWeak(*call.second->scope_info()));
    }
  }
  // Build object literal constant properties
  for (std::pair<ObjectLiteralBoilerplateBuilder*, size_t> literal :
       object_literals_) {
    ObjectLiteralBoilerplateBuilder* object_literal_builder = literal.first;
    if (object_literal_builder->properties_count() > 0) {
      // If constant properties is an empty fixed array, we've already added it
      // to the constant pool when visiting the object literal.
      Handle<ObjectBoilerplateDescription> constant_properties =
          object_literal_builder->GetOrBuildBoilerplateDescription(isolate);
      builder()->SetDeferredConstantPoolEntry(literal.second,
                                              constant_properties);
    }
  }
  // Build array literal constant elements
  for (std::pair<ArrayLiteralBoilerplateBuilder*, size_t> literal :
       array_literals_) {
    ArrayLiteralBoilerplateBuilder* array_literal_builder = literal.first;
    Handle<ArrayBoilerplateDescription> constant_elements =
        array_literal_builder->GetOrBuildBoilerplateDescription(isolate);
    builder()->SetDeferredConstantPoolEntry(literal.second, constant_elements);
  }
  // Build class literal boilerplates.
  for (std::pair<ClassLiteral*, size_t> literal : class_literals_) {
    ClassLiteral* class_literal = literal.first;
    Handle<ClassBoilerplate> class_boilerplate =
        ClassBoilerplate::New(isolate, class_literal, AllocationType::kOld);
    builder()->SetDeferredConstantPoolEntry(literal.second, class_boilerplate);
  }
  // Build template literals.
  for (std::pair<GetTemplateObject*, size_t> literal : template_objects_) {
    GetTemplateObject* get_template_object = literal.first;
    Handle<TemplateObjectDescription> description =
        get_template_object->GetOrBuildDescription(isolate);
    builder()->SetDeferredConstantPoolEntry(literal.second, description);
  }
}
References v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), array_literals_, builder(), CHECK_EQ, class_literals_, v8::internal::DCHECK(), eval_calls_, v8::internal::NativeFunctionLiteral::extension(), function_literals_, v8::Extension::GetNativeFunctionTemplate(), v8::internal::ObjectLiteralBoilerplateBuilder::GetOrBuildBoilerplateDescription(), v8::internal::ArrayLiteralBoilerplateBuilder::GetOrBuildBoilerplateDescription(), v8::internal::GetTemplateObject::GetOrBuildDescription(), v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(), v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::index, v8::internal::indirect_handle(), info(), v8::internal::HandleBase::is_null(), v8::internal::DirectHandle< T >::is_null(), v8::internal::kOld, v8::internal::MakeWeak(), v8::internal::NativeFunctionLiteral::name(), native_function_literals_, v8::internal::ClassBoilerplate::New(), object_literals_, v8::Utils::OpenDirectHandle(), v8::internal::ObjectLiteralBoilerplateBuilder::properties_count(), v8::internal::script, v8::internal::interpreter::BytecodeArrayBuilder::SetDeferredConstantPoolEntry(), template_objects_, top_level_builder(), and v8::internal::v8_flags.
Referenced by FinalizeBytecode().
AllocateNaryBlockCoverageSlotIfEnabled()
int v8::internal::interpreter::BytecodeGenerator::AllocateNaryBlockCoverageSlotIfEnabled (NaryOperation * node, size_t index) [private]
Definition at line 8442 of file bytecode-generator.cc.
                                       {
  return (block_coverage_builder_ == nullptr)
             ? BlockCoverageBuilder::kNoCoverageArraySlot
             : block_coverage_builder_->AllocateNaryBlockCoverageSlot(node,
                                                                      index);
}
References v8::internal::interpreter::BlockCoverageBuilder::AllocateNaryBlockCoverageSlot(), block_coverage_builder_, v8::internal::index, and v8::internal::interpreter::BlockCoverageBuilder::kNoCoverageArraySlot.
Referenced by v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::NaryCodeCoverageSlots().
AllocateTopLevelRegisters()
void v8::internal::interpreter::BytecodeGenerator::AllocateTopLevelRegisters () [private]
Definition at line 2008 of file bytecode-generator.cc.
                                                  {
  if (IsResumableFunction(info()->literal()->kind())) {
    // Either directly use generator_object_var or allocate a new register for
    // the incoming generator object.
    Variable* generator_object_var = closure_scope()->generator_object_var();
    if (generator_object_var->location() == VariableLocation::LOCAL) {
      incoming_new_target_or_generator_ =
          GetRegisterForLocalVariable(generator_object_var);
    } else {
      incoming_new_target_or_generator_ = register_allocator()->NewRegister();
    }
  } else if (closure_scope()->new_target_var()) {
    // Either directly use new_target_var or allocate a new register for
    // the incoming new target object.
    Variable* new_target_var = closure_scope()->new_target_var();
    if (new_target_var->location() == VariableLocation::LOCAL) {
      incoming_new_target_or_generator_ =
          GetRegisterForLocalVariable(new_target_var);
    } else {
      incoming_new_target_or_generator_ = register_allocator()->NewRegister();
    }
  }
}
References closure_scope(), v8::internal::DeclarationScope::generator_object_var(), GetRegisterForLocalVariable(), incoming_new_target_or_generator_, info(), v8::internal::IsResumableFunction(), v8::internal::LOCAL, v8::internal::DeclarationScope::new_target_var(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), and register_allocator().
Referenced by GenerateBytecode().
ast_string_constants()
const AstStringConstants* v8::internal::interpreter::BytecodeGenerator::ast_string_constants () const [inline], [private]
Definition at line 540 of file bytecode-generator.h.
                                                                {
    return ast_string_constants_;
  }
References ast_string_constants_.
Referenced by BuildClassLiteral(), BuildCreateArrayLiteral(), BuildDestructuringArrayAssignment(), BuildFillArrayWithIterator(), BuildFinalizeIteration(), BuildGetIteratorRecord(), BuildIteratorClose(), and BuildVariableLoad().
BuildAssignment()
void v8::internal::interpreter::BytecodeGenerator::BuildAssignment (const AssignmentLhsData & data, Token::Value op, LookupHoistingMode lookup_hoisting_mode) [private]
Definition at line 5552 of file bytecode-generator.cc.
                                             {
  // Assign the value to the LHS.
  switch (lhs_data.assign_type()) {
    case NON_PROPERTY: {
      if (ObjectLiteral* pattern_as_object =
              lhs_data.expr()->AsObjectLiteral()) {
        // Split object literals into destructuring.
        BuildDestructuringObjectAssignment(pattern_as_object, op,
                                           lookup_hoisting_mode);
      } else if (ArrayLiteral* pattern_as_array =
                     lhs_data.expr()->AsArrayLiteral()) {
        // Split object literals into destructuring.
        BuildDestructuringArrayAssignment(pattern_as_array, op,
                                          lookup_hoisting_mode);
      } else {
        DCHECK(lhs_data.expr()->IsVariableProxy());
        VariableProxy* proxy = lhs_data.expr()->AsVariableProxy();
        BuildVariableAssignment(proxy->var(), op, proxy->hole_check_mode(),
                                lookup_hoisting_mode);
      }
      break;
    }
    case NAMED_PROPERTY: {
      BuildSetNamedProperty(lhs_data.object_expr(), lhs_data.object(),
                            lhs_data.name());
      break;
    }
    case KEYED_PROPERTY: {
      FeedbackSlot slot = feedback_spec()->AddKeyedStoreICSlot(language_mode());
      Register value;
      if (!execution_result()->IsEffect()) {
        value = register_allocator()->NewRegister();
        builder()->StoreAccumulatorInRegister(value);
      }
      builder()->SetKeyedProperty(lhs_data.object(), lhs_data.key(),
                                  feedback_index(slot), language_mode());
      if (!execution_result()->IsEffect()) {
        builder()->LoadAccumulatorWithRegister(value);
      }
      break;
    }
    case NAMED_SUPER_PROPERTY: {
      builder()
          ->StoreAccumulatorInRegister(lhs_data.super_property_args()[3])
          .CallRuntime(Runtime::kStoreToSuper, lhs_data.super_property_args());
      break;
    }
    case KEYED_SUPER_PROPERTY: {
      builder()
          ->StoreAccumulatorInRegister(lhs_data.super_property_args()[3])
          .CallRuntime(Runtime::kStoreKeyedToSuper,
                       lhs_data.super_property_args());
      break;
    }
    case PRIVATE_METHOD: {
      Property* property = lhs_data.expr()->AsProperty();
      BuildPrivateBrandCheck(property, lhs_data.object());
      BuildInvalidPropertyAccess(MessageTemplate::kInvalidPrivateMethodWrite,
                                 lhs_data.expr()->AsProperty());
      break;
    }
    case PRIVATE_GETTER_ONLY: {
      Property* property = lhs_data.expr()->AsProperty();
      BuildPrivateBrandCheck(property, lhs_data.object());
      BuildInvalidPropertyAccess(MessageTemplate::kInvalidPrivateSetterAccess,
                                 lhs_data.expr()->AsProperty());
      break;
    }
    case PRIVATE_SETTER_ONLY:
    case PRIVATE_GETTER_AND_SETTER: {
      Register value = register_allocator()->NewRegister();
      builder()->StoreAccumulatorInRegister(value);
      Property* property = lhs_data.expr()->AsProperty();
      BuildPrivateBrandCheck(property, lhs_data.object());
      BuildPrivateSetterAccess(lhs_data.object(), lhs_data.key(), value);
      if (!execution_result()->IsEffect()) {
        builder()->LoadAccumulatorWithRegister(value);
      }
      break;
    }
    case PRIVATE_DEBUG_DYNAMIC: {
      Register value = register_allocator()->NewRegister();
      builder()->StoreAccumulatorInRegister(value);
      Property* property = lhs_data.expr()->AsProperty();
      BuildPrivateDebugDynamicSet(property, lhs_data.object(), value);
      if (!execution_result()->IsEffect()) {
        builder()->LoadAccumulatorWithRegister(value);
      }
      break;
    }
  }
}
References v8::internal::FeedbackVectorSpec::AddKeyedStoreICSlot(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::assign_type(), BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), builder(), BuildInvalidPropertyAccess(), BuildPrivateBrandCheck(), BuildPrivateDebugDynamicSet(), BuildPrivateSetterAccess(), BuildSetNamedProperty(), BuildVariableAssignment(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::DCHECK(), execution_result(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::expr(), feedback_index(), feedback_spec(), v8::internal::VariableProxy::hole_check_mode(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::key(), v8::internal::KEYED_PROPERTY, v8::internal::KEYED_SUPER_PROPERTY, language_mode(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::name(), v8::internal::NAMED_PROPERTY, v8::internal::NAMED_SUPER_PROPERTY, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::NON_PROPERTY, v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::object(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::object_expr(), v8::internal::PRIVATE_DEBUG_DYNAMIC, v8::internal::PRIVATE_GETTER_AND_SETTER, v8::internal::PRIVATE_GETTER_ONLY, v8::internal::PRIVATE_METHOD, v8::internal::PRIVATE_SETTER_ONLY, register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetKeyedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::super_property_args(), v8::internal::value, and v8::internal::VariableProxy::var().
Referenced by BuildDestructuringArrayAssignment(), and BuildDestructuringObjectAssignment().
BuildAsyncGeneratorReturn()
void v8::internal::interpreter::BytecodeGenerator::BuildAsyncGeneratorReturn () [private]
BuildAsyncReturn()
void v8::internal::interpreter::BytecodeGenerator::BuildAsyncReturn (int source_position) [private]
Definition at line 4634 of file bytecode-generator.cc.
                                                            {
  RegisterAllocationScope register_scope(this);
  if (IsAsyncGeneratorFunction(info()->literal()->kind())) {
    RegisterList args = register_allocator()->NewRegisterList(3);
    builder()
        ->MoveRegister(generator_object(), args[0]) // generator
        .StoreAccumulatorInRegister(args[1]) // value
        .LoadTrue()
        .StoreAccumulatorInRegister(args[2]) // done
        .CallRuntime(Runtime::kInlineAsyncGeneratorResolve, args);
  } else {
    DCHECK(IsAsyncFunction(info()->literal()->kind()) ||
           IsModuleWithTopLevelAwait(info()->literal()->kind()));
    RegisterList args = register_allocator()->NewRegisterList(2);
    builder()
        ->MoveRegister(generator_object(), args[0]) // generator
        .StoreAccumulatorInRegister(args[1]) // value
        .CallRuntime(Runtime::kInlineAsyncFunctionResolve, args);
  }
  BuildReturn(source_position);
}
References v8::base::args, builder(), BuildReturn(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::DCHECK(), generator_object(), info(), v8::internal::IsAsyncFunction(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::IsModuleWithTopLevelAwait(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTrue(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel::Execute().
BuildAwait() [1/2]
void v8::internal::interpreter::BytecodeGenerator::BuildAwait (Expression * await_expr) [private]
BuildAwait() [2/2]
void v8::internal::interpreter::BytecodeGenerator::BuildAwait (int position = kNoSourcePosition) [private]
Definition at line 6116 of file bytecode-generator.cc.
                                               {
  // Rather than HandlerTable::UNCAUGHT, async functions use
  // HandlerTable::ASYNC_AWAIT to communicate that top-level exceptions are
  // transformed into promise rejections. This is necessary to prevent emitting
  // multiple debug events for the same uncaught exception. There is no point
  // in the body of an async function where catch prediction is
  // HandlerTable::UNCAUGHT.
  DCHECK(catch_prediction() != HandlerTable::UNCAUGHT ||
         info()->scope()->is_repl_mode_scope());
  {
    // Await(operand) and suspend.
    RegisterAllocationScope register_scope(this);
    Runtime::FunctionId await_intrinsic_id;
    if (IsAsyncGeneratorFunction(function_kind())) {
      await_intrinsic_id = Runtime::kInlineAsyncGeneratorAwait;
    } else {
      await_intrinsic_id = Runtime::kInlineAsyncFunctionAwait;
    }
    RegisterList args = register_allocator()->NewRegisterList(2);
    builder()
        ->MoveRegister(generator_object(), args[0])
        .StoreAccumulatorInRegister(args[1])
        .CallRuntime(await_intrinsic_id, args);
  }
  BuildSuspendPoint(position);
  Register input = register_allocator()->NewRegister();
  Register resume_mode = register_allocator()->NewRegister();
  // Now dispatch on resume mode.
  BytecodeLabel resume_next;
  builder()
      ->StoreAccumulatorInRegister(input)
      .CallRuntime(Runtime::kInlineGeneratorGetResumeMode, generator_object())
      .StoreAccumulatorInRegister(resume_mode)
      .LoadLiteral(Smi::FromInt(JSGeneratorObject::kNext))
      .CompareReference(resume_mode)
      .JumpIfTrue(ToBooleanMode::kAlreadyBoolean, &resume_next);
  // Resume with "throw" completion (rethrow the received value).
  // TODO(leszeks): Add a debug-only check that the accumulator is
  // JSGeneratorObject::kThrow.
  builder()->LoadAccumulatorWithRegister(input).ReThrow();
  // Resume with next.
  builder()->Bind(&resume_next);
  builder()->LoadAccumulatorWithRegister(input);
}
References v8::base::args, v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), BuildSuspendPoint(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), catch_prediction(), v8::internal::interpreter::BytecodeArrayBuilder::CompareReference(), v8::internal::DCHECK(), v8::internal::Smi::FromInt(), function_kind(), generator_object(), info(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, v8::internal::JSGeneratorObject::kNext, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::ReThrow(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::HandlerTable::UNCAUGHT.
Referenced by BuildDisposeScope(), BuildFinalizeIteration(), BuildIteratorClose(), and BuildIteratorNext().
BuildCallIteratorMethod()
void v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod (Register iterator, const AstRawString * method, RegisterList receiver_and_args, BytecodeLabel * if_called, BytecodeLabels * if_notcalled) [private]
Definition at line 7791 of file bytecode-generator.cc.
                                                                              {
  RegisterAllocationScope register_scope(this);
  Register method = register_allocator()->NewRegister();
  FeedbackSlot slot = feedback_spec()->AddLoadICSlot();
  builder()
      ->LoadNamedProperty(iterator, method_name, feedback_index(slot))
      .JumpIfUndefinedOrNull(if_notcalled->New())
      .StoreAccumulatorInRegister(method)
      .CallProperty(method, receiver_and_args,
                    feedback_index(feedback_spec()->AddCallICSlot()))
      .Jump(if_called);
}
References v8::internal::FeedbackVectorSpec::AddLoadICSlot(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildIteratorClose().
BuildClassLiteral()
void v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral (ClassLiteral * expr, Register name) [private]
Definition at line 3315 of file bytecode-generator.cc.
                                                                           {
  size_t class_boilerplate_entry =
      builder()->AllocateDeferredConstantPoolEntry();
  class_literals_.push_back(std::make_pair(expr, class_boilerplate_entry));
  VisitDeclarations(expr->scope()->declarations());
  Register class_constructor = register_allocator()->NewRegister();
  // Create the class brand symbol and store it on the context during class
  // evaluation. This will be stored in the instance later in the constructor.
  // We do this early so that invalid access to private methods or accessors
  // in computed property keys throw.
  if (expr->scope()->brand() != nullptr) {
    Register brand = register_allocator()->NewRegister();
    const AstRawString* class_name =
        expr->scope()->class_variable() != nullptr
            ? expr->scope()->class_variable()->raw_name()
            : ast_string_constants()->anonymous_string();
    builder()
        ->LoadLiteral(class_name)
        .StoreAccumulatorInRegister(brand)
        .CallRuntime(Runtime::kCreatePrivateBrandSymbol, brand);
    register_allocator()->ReleaseRegister(brand);
    BuildVariableAssignment(expr->scope()->brand(), Token::kInit,
                            HoleCheckMode::kElided);
  }
  AccessorTable<ClassLiteral::Property> private_accessors(zone());
  for (int i = 0; i < expr->private_members()->length(); i++) {
    ClassLiteral::Property* property = expr->private_members()->at(i);
    DCHECK(property->is_private());
    switch (property->kind()) {
      case ClassLiteral::Property::FIELD: {
        // Initialize the private field variables early.
        // Create the private name symbols for fields during class
        // evaluation and store them on the context. These will be
        // used as keys later during instance or static initialization.
        RegisterAllocationScope private_name_register_scope(this);
        Register private_name = register_allocator()->NewRegister();
        VisitForRegisterValue(property->key(), private_name);
        builder()
            ->LoadLiteral(property->key()->AsLiteral()->AsRawPropertyName())
            .StoreAccumulatorInRegister(private_name)
            .CallRuntime(Runtime::kCreatePrivateNameSymbol, private_name);
        DCHECK_NOT_NULL(property->private_name_var());
        BuildVariableAssignment(property->private_name_var(), Token::kInit,
                                HoleCheckMode::kElided);
        break;
      }
      case ClassLiteral::Property::METHOD: {
        RegisterAllocationScope register_scope(this);
        VisitForAccumulatorValue(property->value());
        BuildVariableAssignment(property->private_name_var(), Token::kInit,
                                HoleCheckMode::kElided);
        break;
      }
      // Collect private accessors into a table to merge the creation of
      // those closures later.
      case ClassLiteral::Property::GETTER: {
        Literal* key = property->key()->AsLiteral();
        DCHECK_NULL(private_accessors.LookupOrInsert(key)->getter);
        private_accessors.LookupOrInsert(key)->getter = property;
        break;
      }
      case ClassLiteral::Property::SETTER: {
        Literal* key = property->key()->AsLiteral();
        DCHECK_NULL(private_accessors.LookupOrInsert(key)->setter);
        private_accessors.LookupOrInsert(key)->setter = property;
        break;
      }
      case ClassLiteral::Property::AUTO_ACCESSOR: {
        Literal* key = property->key()->AsLiteral();
        RegisterAllocationScope private_name_register_scope(this);
        Register accessor_storage_private_name =
            register_allocator()->NewRegister();
        Variable* accessor_storage_private_name_var =
            property->auto_accessor_info()
                ->accessor_storage_name_proxy()
                ->var();
        // We reuse the already internalized
        // ".accessor-storage-<accessor_number>" strings that were defined in
        // the parser instead of the "<name>accessor storage" string from the
        // spec. The downsides are that is that these are the property names
        // that will show up in devtools and in error messages.
        // Additionally, a property can share a name with the corresponding
        // property of their parent class, i.e. for classes defined as
        // "class C {accessor x}" and "class D extends C {accessor y}",
        // if "d = new D()", then d.x and d.y will share the name
        // ".accessor-storage-0", (but a different private symbol).
        // TODO(42202709): Get to a resolution on how to handle this naming
        // issue before shipping the feature.
        builder()
            ->LoadLiteral(accessor_storage_private_name_var->raw_name())
            .StoreAccumulatorInRegister(accessor_storage_private_name)
            .CallRuntime(Runtime::kCreatePrivateNameSymbol,
                         accessor_storage_private_name);
        BuildVariableAssignment(accessor_storage_private_name_var, Token::kInit,
                                HoleCheckMode::kElided);
        auto* accessor_pair = private_accessors.LookupOrInsert(key);
        DCHECK_NULL(accessor_pair->getter);
        accessor_pair->getter = property;
        DCHECK_NULL(accessor_pair->setter);
        accessor_pair->setter = property;
        break;
      }
      default:
        UNREACHABLE();
    }
  }
  {
    RegisterAllocationScope register_scope(this);
    RegisterList args = register_allocator()->NewGrowableRegisterList();
    Register class_boilerplate = register_allocator()->GrowRegisterList(&args);
    Register class_constructor_in_args =
        register_allocator()->GrowRegisterList(&args);
    Register super_class = register_allocator()->GrowRegisterList(&args);
    DCHECK_EQ(ClassBoilerplate::kFirstDynamicArgumentIndex,
              args.register_count());
    VisitForAccumulatorValueOrTheHole(expr->extends());
    builder()->StoreAccumulatorInRegister(super_class);
    VisitFunctionLiteral(expr->constructor());
    builder()
        ->StoreAccumulatorInRegister(class_constructor)
        .MoveRegister(class_constructor, class_constructor_in_args)
        .LoadConstantPoolEntry(class_boilerplate_entry)
        .StoreAccumulatorInRegister(class_boilerplate);
    // Create computed names and method values nodes to store into the literal.
    for (int i = 0; i < expr->public_members()->length(); i++) {
      ClassLiteral::Property* property = expr->public_members()->at(i);
      if (property->is_computed_name()) {
        Register key = register_allocator()->GrowRegisterList(&args);
        builder()->SetExpressionAsStatementPosition(property->key());
        BuildLoadPropertyKey(property, key);
        if (property->is_static()) {
          // The static prototype property is read only. We handle the non
          // computed property name case in the parser. Since this is the only
          // case where we need to check for an own read only property we
          // special case this so we do not need to do this for every property.
          FeedbackSlot slot = GetDummyCompareICSlot();
          BytecodeLabel done;
          builder()
              ->LoadLiteral(ast_string_constants()->prototype_string())
              .CompareOperation(Token::kEqStrict, key, feedback_index(slot))
              .JumpIfFalse(ToBooleanMode::kAlreadyBoolean, &done)
              .CallRuntime(Runtime::kThrowStaticPrototypeError)
              .Bind(&done);
        }
        if (property->kind() == ClassLiteral::Property::FIELD) {
          DCHECK(!property->is_private());
          // Initialize field's name variable with the computed name.
          DCHECK_NOT_NULL(property->computed_name_var());
          builder()->LoadAccumulatorWithRegister(key);
          BuildVariableAssignment(property->computed_name_var(), Token::kInit,
                                  HoleCheckMode::kElided);
        }
      }
      DCHECK(!property->is_private());
      if (property->kind() == ClassLiteral::Property::FIELD) {
        // We don't compute field's value here, but instead do it in the
        // initializer function.
        continue;
      }
      if (property->kind() == ClassLiteral::Property::AUTO_ACCESSOR) {
        {
          RegisterAllocationScope private_name_register_scope(this);
          Register name_register = register_allocator()->NewRegister();
          Variable* accessor_storage_private_name_var =
              property->auto_accessor_info()
                  ->accessor_storage_name_proxy()
                  ->var();
          builder()
              ->LoadLiteral(accessor_storage_private_name_var->raw_name())
              .StoreAccumulatorInRegister(name_register)
              .CallRuntime(Runtime::kCreatePrivateNameSymbol, name_register);
          BuildVariableAssignment(accessor_storage_private_name_var,
                                  Token::kInit, HoleCheckMode::kElided);
        }
        Register getter = register_allocator()->GrowRegisterList(&args);
        Register setter = register_allocator()->GrowRegisterList(&args);
        AutoAccessorInfo* auto_accessor_info = property->auto_accessor_info();
        VisitForRegisterValue(auto_accessor_info->generated_getter(), getter);
        VisitForRegisterValue(auto_accessor_info->generated_setter(), setter);
        continue;
      }
      Register value = register_allocator()->GrowRegisterList(&args);
      VisitForRegisterValue(property->value(), value);
    }
    builder()->CallRuntime(Runtime::kDefineClass, args);
  }
  // Assign to the home object variable. Accumulator already contains the
  // prototype.
  Variable* home_object_variable = expr->home_object();
  if (home_object_variable != nullptr) {
    DCHECK(home_object_variable->is_used());
    DCHECK(home_object_variable->IsContextSlot());
    BuildVariableAssignment(home_object_variable, Token::kInit,
                            HoleCheckMode::kElided);
  }
  Variable* static_home_object_variable = expr->static_home_object();
  if (static_home_object_variable != nullptr) {
    DCHECK(static_home_object_variable->is_used());
    DCHECK(static_home_object_variable->IsContextSlot());
    builder()->LoadAccumulatorWithRegister(class_constructor);
    BuildVariableAssignment(static_home_object_variable, Token::kInit,
                            HoleCheckMode::kElided);
  }
  // Assign to class variable.
  Variable* class_variable = expr->scope()->class_variable();
  if (class_variable != nullptr && class_variable->is_used()) {
    DCHECK(class_variable->IsStackLocal() || class_variable->IsContextSlot());
    builder()->LoadAccumulatorWithRegister(class_constructor);
    BuildVariableAssignment(class_variable, Token::kInit,
                            HoleCheckMode::kElided);
  }
  // Define private accessors, using only a single call to the runtime for
  // each pair of corresponding getters and setters, in the order the first
  // component is declared.
  for (auto accessors : private_accessors.ordered_accessors()) {
    RegisterAllocationScope inner_register_scope(this);
    RegisterList accessors_reg = register_allocator()->NewRegisterList(2);
    ClassLiteral::Property* getter = accessors.second->getter;
    ClassLiteral::Property* setter = accessors.second->setter;
    Variable* accessor_pair_var;
    if (getter && getter->kind() == ClassLiteral::Property::AUTO_ACCESSOR) {
      DCHECK_EQ(setter, getter);
      AutoAccessorInfo* auto_accessor_info = getter->auto_accessor_info();
      VisitForRegisterValue(auto_accessor_info->generated_getter(),
                            accessors_reg[0]);
      VisitForRegisterValue(auto_accessor_info->generated_setter(),
                            accessors_reg[1]);
      accessor_pair_var =
          auto_accessor_info->property_private_name_proxy()->var();
    } else {
      VisitLiteralAccessor(getter, accessors_reg[0]);
      VisitLiteralAccessor(setter, accessors_reg[1]);
      accessor_pair_var = getter != nullptr ? getter->private_name_var()
                                            : setter->private_name_var();
    }
    builder()->CallRuntime(Runtime::kCreatePrivateAccessors, accessors_reg);
    DCHECK_NOT_NULL(accessor_pair_var);
    BuildVariableAssignment(accessor_pair_var, Token::kInit,
                            HoleCheckMode::kElided);
  }
  if (expr->instance_members_initializer_function() != nullptr) {
    VisitForAccumulatorValue(expr->instance_members_initializer_function());
    FeedbackSlot slot = feedback_spec()->AddStoreICSlot(language_mode());
    builder()
        ->StoreClassFieldsInitializer(class_constructor, feedback_index(slot))
        .LoadAccumulatorWithRegister(class_constructor);
  }
  if (expr->static_initializer() != nullptr) {
    // TODO(gsathya): This can be optimized away to be a part of the
    // class boilerplate in the future. The name argument can be
    // passed to the DefineClass runtime function and have it set
    // there.
    // TODO(v8:13451): Alternatively, port SetFunctionName to an ic so that we
    // can replace the runtime call to a dedicate bytecode here.
    if (name.is_valid()) {
      RegisterAllocationScope inner_register_scope(this);
      RegisterList args = register_allocator()->NewRegisterList(2);
      builder()
          ->MoveRegister(class_constructor, args[0])
          .MoveRegister(name, args[1])
          .CallRuntime(Runtime::kSetFunctionName, args);
    }
    RegisterAllocationScope inner_register_scope(this);
    RegisterList args = register_allocator()->NewRegisterList(1);
    Register initializer = VisitForRegisterValue(expr->static_initializer());
    builder()
        ->MoveRegister(class_constructor, args[0])
        .CallProperty(initializer, args,
                      feedback_index(feedback_spec()->AddCallICSlot()));
  }
  builder()->LoadAccumulatorWithRegister(class_constructor);
}
References v8::internal::AutoAccessorInfo::accessor_storage_name_proxy(), v8::internal::FeedbackVectorSpec::AddStoreICSlot(), v8::internal::interpreter::BytecodeArrayBuilder::AllocateDeferredConstantPoolEntry(), v8::base::args, ast_string_constants(), v8::internal::ClassLiteralProperty::AUTO_ACCESSOR, v8::internal::ClassLiteralProperty::auto_accessor_info(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::ClassScope::brand(), builder(), BuildLoadPropertyKey(), BuildVariableAssignment(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), class_literals_, v8::internal::ClassScope::class_variable(), v8::internal::interpreter::BytecodeArrayBuilder::CompareOperation(), v8::internal::ClassLiteralProperty::computed_name_var(), v8::internal::ClassLiteral::constructor(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::Scope::declarations(), v8::internal::ClassLiteral::extends(), feedback_index(), feedback_spec(), v8::internal::ClassLiteralProperty::FIELD, v8::internal::AutoAccessorInfo::generated_getter(), v8::internal::AutoAccessorInfo::generated_setter(), GetDummyCompareICSlot(), v8::internal::ClassLiteralProperty::GETTER, v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList(), v8::internal::ClassLiteral::home_object(), v8::internal::ClassLiteral::instance_members_initializer_function(), v8::internal::LiteralProperty::is_computed_name(), v8::internal::ClassLiteralProperty::is_private(), v8::internal::ClassLiteralProperty::is_static(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse(), v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, v8::internal::kElided, v8::internal::LiteralProperty::key(), v8::internal::key, v8::internal::ClassBoilerplate::kFirstDynamicArgumentIndex, v8::internal::ClassLiteralProperty::kind(), language_mode(), v8::internal::length, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadConstantPoolEntry(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::ClassLiteralProperty::METHOD, v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::name, v8::internal::interpreter::BytecodeRegisterAllocator::NewGrowableRegisterList(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::ClassLiteral::private_members(), v8::internal::ClassLiteralProperty::private_name_var(), v8::internal::AutoAccessorInfo::property_private_name_proxy(), v8::internal::ClassLiteral::public_members(), v8::internal::Variable::raw_name(), register_allocator(), v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister(), v8::internal::ClassLiteral::scope(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionAsStatementPosition(), v8::internal::ClassLiteralProperty::SETTER, v8::internal::setter, v8::internal::ClassLiteral::static_home_object(), v8::internal::ClassLiteral::static_initializer(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::StoreClassFieldsInitializer(), v8::internal::UNREACHABLE(), v8::internal::LiteralProperty::value(), v8::internal::value, v8::internal::VariableProxy::var(), VisitDeclarations(), VisitForAccumulatorValue(), VisitForAccumulatorValueOrTheHole(), VisitForRegisterValue(), VisitLiteralAccessor(), and zone().
BuildClassProperty()
void v8::internal::interpreter::BytecodeGenerator::BuildClassProperty (ClassLiteral::Property * property) [private]
Definition at line 3644 of file bytecode-generator.cc.
                                                                         {
  RegisterAllocationScope register_scope(this);
  Register key;
  // Private methods are not initialized in BuildClassProperty.
  DCHECK_IMPLIES(property->is_private(),
                 property->kind() == ClassLiteral::Property::FIELD ||
                     property->is_auto_accessor());
  builder()->SetExpressionPosition(property->key());
  bool is_literal_store =
      property->key()->IsPropertyName() && !property->is_computed_name() &&
      !property->is_private() && !property->is_auto_accessor();
  if (!is_literal_store) {
    key = register_allocator()->NewRegister();
    if (property->is_auto_accessor()) {
      Variable* var =
          property->auto_accessor_info()->accessor_storage_name_proxy()->var();
      DCHECK_NOT_NULL(var);
      BuildVariableLoad(var, HoleCheckMode::kElided);
      builder()->StoreAccumulatorInRegister(key);
    } else if (property->is_computed_name()) {
      DCHECK_EQ(property->kind(), ClassLiteral::Property::FIELD);
      DCHECK(!property->is_private());
      Variable* var = property->computed_name_var();
      DCHECK_NOT_NULL(var);
      // The computed name is already evaluated and stored in a variable at
      // class definition time.
      BuildVariableLoad(var, HoleCheckMode::kElided);
      builder()->StoreAccumulatorInRegister(key);
    } else if (property->is_private()) {
      Variable* private_name_var = property->private_name_var();
      DCHECK_NOT_NULL(private_name_var);
      BuildVariableLoad(private_name_var, HoleCheckMode::kElided);
      builder()->StoreAccumulatorInRegister(key);
    } else {
      VisitForRegisterValue(property->key(), key);
    }
  }
  builder()->SetExpressionAsStatementPosition(property->value());
  if (is_literal_store) {
    VisitForAccumulatorValue(property->value());
    FeedbackSlot slot = feedback_spec()->AddDefineNamedOwnICSlot();
    builder()->DefineNamedOwnProperty(
        builder()->Receiver(),
        property->key()->AsLiteral()->AsRawPropertyName(),
        feedback_index(slot));
  } else {
    DefineKeyedOwnPropertyFlags flags = DefineKeyedOwnPropertyFlag::kNoFlags;
    if (property->NeedsSetFunctionName()) {
      // Static class fields require the name property to be set on
      // the class, meaning we can't wait until the
      // DefineKeyedOwnProperty call later to set the name.
      if (property->value()->IsClassLiteral() &&
          property->value()->AsClassLiteral()->static_initializer() !=
              nullptr) {
        VisitClassLiteral(property->value()->AsClassLiteral(), key);
      } else {
        VisitForAccumulatorValue(property->value());
        flags |= DefineKeyedOwnPropertyFlag::kSetFunctionName;
      }
    } else {
      VisitForAccumulatorValue(property->value());
    }
    FeedbackSlot slot = feedback_spec()->AddDefineKeyedOwnICSlot();
    builder()->DefineKeyedOwnProperty(builder()->Receiver(), key, flags,
                                      feedback_index(slot));
  }
}
References v8::internal::AutoAccessorInfo::accessor_storage_name_proxy(), v8::internal::FeedbackVectorSpec::AddDefineKeyedOwnICSlot(), v8::internal::FeedbackVectorSpec::AddDefineNamedOwnICSlot(), v8::internal::ClassLiteralProperty::auto_accessor_info(), builder(), BuildVariableLoad(), v8::internal::ClassLiteralProperty::computed_name_var(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::interpreter::BytecodeArrayBuilder::DefineKeyedOwnProperty(), v8::internal::interpreter::BytecodeArrayBuilder::DefineNamedOwnProperty(), feedback_index(), feedback_spec(), v8::internal::ClassLiteralProperty::FIELD, v8::internal::flags, v8::internal::ClassLiteralProperty::is_auto_accessor(), v8::internal::LiteralProperty::is_computed_name(), v8::internal::ClassLiteralProperty::is_private(), v8::internal::Expression::IsPropertyName(), v8::internal::kElided, v8::internal::LiteralProperty::key(), v8::internal::key, v8::internal::ClassLiteralProperty::kind(), v8::internal::kNoFlags, v8::internal::kSetFunctionName, v8::internal::LiteralProperty::NeedsSetFunctionName(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::ClassLiteralProperty::private_name_var(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionAsStatementPosition(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::LiteralProperty::value(), v8::internal::VariableProxy::var(), VisitClassLiteral(), VisitForAccumulatorValue(), and VisitForRegisterValue().
BuildCreateArrayLiteral()
void v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral (const ZonePtrList< Expression > * elements, ArrayLiteral * expr) [private]
Definition at line 4290 of file bytecode-generator.cc.
                                                                 {
  RegisterAllocationScope register_scope(this);
  // Make this the first register allocated so that it has a chance of aliasing
  // the next register allocated after returning from this function.
  Register array = register_allocator()->NewRegister();
  Register index = register_allocator()->NewRegister();
  SharedFeedbackSlot element_slot(feedback_spec(),
                                  FeedbackSlotKind::kStoreInArrayLiteral);
  ZonePtrList<Expression>::const_iterator current = elements->begin();
  ZonePtrList<Expression>::const_iterator end = elements->end();
  bool is_empty = elements->is_empty();
  if (!is_empty && (*current)->IsSpread()) {
    // If we have a leading spread, use CreateArrayFromIterable to create
    // an array from it and then add the remaining components to that array.
    VisitForAccumulatorValue(*current);
    builder()->SetExpressionPosition((*current)->AsSpread()->expression());
    builder()->CreateArrayFromIterable().StoreAccumulatorInRegister(array);
    if (++current != end) {
      // If there are remaining elements, prepare the index register that is
      // used for adding those elements. The next index is the length of the
      // newly created array.
      auto length = ast_string_constants()->length_string();
      int length_load_slot = feedback_index(feedback_spec()->AddLoadICSlot());
      builder()
          ->LoadNamedProperty(array, length, length_load_slot)
          .StoreAccumulatorInRegister(index);
    }
  } else {
    // There are some elements before the first (if any) spread, and we can
    // use a boilerplate when creating the initial array from those elements.
    // First, allocate a constant pool entry for the boilerplate that will
    // be created during finalization, and will contain all the constant
    // elements before the first spread. This also handle the empty array case
    // and one-shot optimization.
    ArrayLiteralBoilerplateBuilder* array_literal_builder = nullptr;
    if (expr != nullptr) {
      array_literal_builder = expr->builder();
    } else {
      DCHECK(!elements->is_empty());
      // get first_spread_index
      int first_spread_index = -1;
      for (auto iter = elements->begin(); iter != elements->end(); iter++) {
        if ((*iter)->IsSpread()) {
          first_spread_index = static_cast<int>(iter - elements->begin());
          break;
        }
      }
      array_literal_builder = zone()->New<ArrayLiteralBoilerplateBuilder>(
          elements, first_spread_index);
      array_literal_builder->InitDepthAndFlags();
    }
    DCHECK(array_literal_builder != nullptr);
    uint8_t flags = CreateArrayLiteralFlags::Encode(
        array_literal_builder->IsFastCloningSupported(),
        array_literal_builder->ComputeFlags());
    if (is_empty) {
      // Empty array literal fast-path.
      int literal_index = feedback_index(feedback_spec()->AddLiteralSlot());
      DCHECK(array_literal_builder->IsFastCloningSupported());
      builder()->CreateEmptyArrayLiteral(literal_index);
    } else {
      // Create array literal from boilerplate.
      size_t entry = builder()->AllocateDeferredConstantPoolEntry();
      array_literals_.push_back(std::make_pair(array_literal_builder, entry));
      int literal_index = feedback_index(feedback_spec()->AddLiteralSlot());
      builder()->CreateArrayLiteral(entry, literal_index, flags);
    }
    builder()->StoreAccumulatorInRegister(array);
    ZonePtrList<Expression>::const_iterator first_spread_or_end =
        array_literal_builder->first_spread_index() >= 0
            ? current + array_literal_builder->first_spread_index()
            : end;
    // Insert the missing non-constant elements, up until the first spread
    // index, into the initial array (the remaining elements will be inserted
    // below).
    DCHECK_EQ(current, elements->begin());
    int array_index = 0;
    for (; current != first_spread_or_end; ++current, array_index++) {
      Expression* subexpr = *current;
      DCHECK(!subexpr->IsSpread());
      // Skip the constants.
      if (subexpr->IsCompileTimeValue()) continue;
      builder()
          ->LoadLiteral(Smi::FromInt(array_index))
          .StoreAccumulatorInRegister(index);
      VisitForAccumulatorValue(subexpr);
      builder()->StoreInArrayLiteral(array, index,
                                     feedback_index(element_slot.Get()));
    }
    if (current != end) {
      // If there are remaining elements, prepare the index register
      // to store the next element, which comes from the first spread.
      builder()
          ->LoadLiteral(Smi::FromInt(array_index))
          .StoreAccumulatorInRegister(index);
    }
  }
  // Now build insertions for the remaining elements from current to end.
  SharedFeedbackSlot index_slot(feedback_spec(), FeedbackSlotKind::kBinaryOp);
  SharedFeedbackSlot length_slot(
      feedback_spec(), feedback_spec()->GetStoreICSlot(LanguageMode::kStrict));
  for (; current != end; ++current) {
    Expression* subexpr = *current;
    if (subexpr->IsSpread()) {
      RegisterAllocationScope scope(this);
      builder()->SetExpressionPosition(subexpr->AsSpread()->expression());
      VisitForAccumulatorValue(subexpr->AsSpread()->expression());
      builder()->SetExpressionPosition(subexpr->AsSpread()->expression());
      IteratorRecord iterator = BuildGetIteratorRecord(IteratorType::kNormal);
      Register value = register_allocator()->NewRegister();
      FeedbackSlot next_value_load_slot = feedback_spec()->AddLoadICSlot();
      FeedbackSlot next_done_load_slot = feedback_spec()->AddLoadICSlot();
      FeedbackSlot real_index_slot = index_slot.Get();
      FeedbackSlot real_element_slot = element_slot.Get();
      BuildFillArrayWithIterator(iterator, array, index, value,
                                 next_value_load_slot, next_done_load_slot,
                                 real_index_slot, real_element_slot);
    } else if (!subexpr->IsTheHoleLiteral()) {
      // literal[index++] = subexpr
      VisitForAccumulatorValue(subexpr);
      builder()
          ->StoreInArrayLiteral(array, index,
                                feedback_index(element_slot.Get()))
          .LoadAccumulatorWithRegister(index);
      // Only increase the index if we are not the last element.
      if (current + 1 != end) {
        builder()
            ->UnaryOperation(Token::kInc, feedback_index(index_slot.Get()))
            .StoreAccumulatorInRegister(index);
      }
    } else {
      // literal.length = ++index
      // length_slot is only used when there are holes.
      auto length = ast_string_constants()->length_string();
      builder()
          ->LoadAccumulatorWithRegister(index)
          .UnaryOperation(Token::kInc, feedback_index(index_slot.Get()))
          .StoreAccumulatorInRegister(index)
          .SetNamedProperty(array, length, feedback_index(length_slot.Get()),
                            LanguageMode::kStrict);
    }
  }
  builder()->LoadAccumulatorWithRegister(array);
}
References v8::internal::FeedbackVectorSpec::AddLoadICSlot(), v8::internal::interpreter::BytecodeArrayBuilder::AllocateDeferredConstantPoolEntry(), array_literals_, ast_string_constants(), v8::internal::ZoneList< T >::begin(), builder(), v8::internal::ArrayLiteral::builder(), BuildFillArrayWithIterator(), BuildGetIteratorRecord(), v8::internal::ArrayLiteralBoilerplateBuilder::ComputeFlags(), v8::internal::interpreter::BytecodeArrayBuilder::CreateArrayFromIterable(), v8::internal::interpreter::BytecodeArrayBuilder::CreateArrayLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::CreateEmptyArrayLiteral(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::CreateArrayLiteralFlags::Encode(), v8::internal::ZoneList< T >::end(), v8::internal::compiler::end(), feedback_index(), feedback_spec(), v8::internal::ArrayLiteralBoilerplateBuilder::first_spread_index(), v8::internal::flags, v8::internal::Smi::FromInt(), v8::internal::SharedFeedbackSlot::Get(), v8::internal::index, v8::internal::ArrayLiteralBoilerplateBuilder::InitDepthAndFlags(), v8::internal::ZoneList< T >::is_empty(), v8::internal::compiler::turboshaft::is_empty(), v8::internal::Expression::IsCompileTimeValue(), v8::internal::ArrayLiteralBoilerplateBuilder::IsFastCloningSupported(), v8::internal::Expression::IsTheHoleLiteral(), v8::internal::kBinaryOp, v8::internal::kNormal, v8::internal::kStoreInArrayLiteral, v8::internal::kStrict, v8::internal::length, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), v8::internal::Zone::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeArrayBuilder::SetNamedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::StoreInArrayLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::UnaryOperation(), v8::internal::value, VisitForAccumulatorValue(), and zone().
Referenced by VisitCallSuper().
BuildCreateObjectLiteral()
void v8::internal::interpreter::BytecodeGenerator::BuildCreateObjectLiteral (Register literal, uint8_t flags, size_t entry) [private]
Definition at line 3961 of file bytecode-generator.cc.
                                                                              {
  // TODO(cbruni): Directly generate runtime call for literals we cannot
  // optimize once the CreateShallowObjectLiteral stub is in sync with the TF
  // optimizations.
  int literal_index = feedback_index(feedback_spec()->AddLiteralSlot());
  builder()
      ->CreateObjectLiteral(entry, literal_index, flags)
      .StoreAccumulatorInRegister(literal);
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::CreateObjectLiteral(), feedback_index(), feedback_spec(), v8::internal::flags, and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
BuildDeclareCall()
void v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall (Runtime::FunctionId id) [private]
Definition at line 2197 of file bytecode-generator.cc.
                                                             {
  if (!top_level_builder()->has_top_level_declaration()) return;
  DCHECK(!top_level_builder()->processed());
  top_level_builder()->set_constant_pool_entry(
      builder()->AllocateDeferredConstantPoolEntry());
  // Emit code to declare globals.
  RegisterList args = register_allocator()->NewRegisterList(2);
  builder()
      ->LoadConstantPoolEntry(top_level_builder()->constant_pool_entry())
      .StoreAccumulatorInRegister(args[0])
      .MoveRegister(Register::function_closure(), args[1])
      .CallRuntime(id, args);
  top_level_builder()->mark_processed();
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::DCHECK(), v8::internal::interpreter::Register::function_closure(), v8::internal::interpreter::BytecodeArrayBuilder::LoadConstantPoolEntry(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::mark_processed(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::set_constant_pool_entry(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and top_level_builder().
Referenced by VisitGlobalDeclarations(), and VisitModuleDeclarations().
BuildDestructuringArrayAssignment()
void v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment (ArrayLiteral * pattern, Token::Value op, LookupHoistingMode lookup_hoisting_mode) [private]
Definition at line 5243 of file bytecode-generator.cc.
                                             {
  RegisterAllocationScope scope(this);
  Register value = register_allocator()->NewRegister();
  builder()->StoreAccumulatorInRegister(value);
  // Store the iterator in a dedicated register so that it can be closed on
  // exit, and the 'done' value in a dedicated register so that it can be
  // changed and accessed independently of the iteration result.
  IteratorRecord iterator = BuildGetIteratorRecord(IteratorType::kNormal);
  Register done = register_allocator()->NewRegister();
  builder()->LoadFalse();
  builder()->StoreAccumulatorInRegister(done);
  BuildTryFinally(
      // Try block.
      [&]() {
        Register next_result = register_allocator()->NewRegister();
        FeedbackSlot next_value_load_slot = feedback_spec()->AddLoadICSlot();
        FeedbackSlot next_done_load_slot = feedback_spec()->AddLoadICSlot();
        Spread* spread = nullptr;
        for (Expression* target : *pattern->values()) {
          if (target->IsSpread()) {
            spread = target->AsSpread();
            break;
          }
          Expression* default_value = GetDestructuringDefaultValue(&target);
          builder()->SetExpressionPosition(target);
          AssignmentLhsData lhs_data = PrepareAssignmentLhs(target);
          // if (!done) {
          // // Make sure we are considered done if .next(), .done or .value
          // // fail.
          // done = true
          // var next_result = iterator.next()
          // var tmp_done = next_result.done
          // if (!tmp_done) {
          // value = next_result.value
          // done = false
          // }
          // }
          // if (done)
          // value = undefined
          BytecodeLabels is_done(zone());
          builder()->LoadAccumulatorWithRegister(done);
          builder()->JumpIfTrue(ToBooleanMode::kConvertToBoolean,
                                is_done.New());
          builder()->LoadTrue().StoreAccumulatorInRegister(done);
          BuildIteratorNext(iterator, next_result);
          builder()
              ->LoadNamedProperty(next_result,
                                  ast_string_constants()->done_string(),
                                  feedback_index(next_done_load_slot))
              .JumpIfTrue(ToBooleanMode::kConvertToBoolean, is_done.New());
          // Only do the assignment if this is not a hole (i.e. 'elided').
          if (!target->IsTheHoleLiteral()) {
            builder()
                ->LoadNamedProperty(next_result,
                                    ast_string_constants()->value_string(),
                                    feedback_index(next_value_load_slot))
                .StoreAccumulatorInRegister(next_result)
                .LoadFalse()
                .StoreAccumulatorInRegister(done)
                .LoadAccumulatorWithRegister(next_result);
            // [<pattern> = <init>] = <value>
            // becomes (roughly)
            // temp = <value>.next();
            // <pattern> = temp === undefined ? <init> : temp;
            BytecodeLabel do_assignment;
            if (default_value) {
              builder()->JumpIfNotUndefined(&do_assignment);
              // Since done == true => temp == undefined, jump directly to using
              // the default value for that case.
              is_done.Bind(builder());
              VisitInHoleCheckElisionScopeForAccumulatorValue(default_value);
            } else {
              builder()->Jump(&do_assignment);
              is_done.Bind(builder());
              builder()->LoadUndefined();
            }
            builder()->Bind(&do_assignment);
            BuildAssignment(lhs_data, op, lookup_hoisting_mode);
          } else {
            builder()->LoadFalse().StoreAccumulatorInRegister(done);
            DCHECK_EQ(lhs_data.assign_type(), NON_PROPERTY);
            is_done.Bind(builder());
          }
        }
        if (spread) {
          RegisterAllocationScope scope(this);
          BytecodeLabel is_done;
          // A spread is turned into a loop over the remainer of the iterator.
          Expression* target = spread->expression();
          builder()->SetExpressionPosition(spread);
          AssignmentLhsData lhs_data = PrepareAssignmentLhs(target);
          // var array = [];
          Register array = register_allocator()->NewRegister();
          builder()->CreateEmptyArrayLiteral(
              feedback_index(feedback_spec()->AddLiteralSlot()));
          builder()->StoreAccumulatorInRegister(array);
          // If done, jump to assigning empty array
          builder()->LoadAccumulatorWithRegister(done);
          builder()->JumpIfTrue(ToBooleanMode::kConvertToBoolean, &is_done);
          // var index = 0;
          Register index = register_allocator()->NewRegister();
          builder()->LoadLiteral(Smi::zero());
          builder()->StoreAccumulatorInRegister(index);
          // Set done to true, since it's guaranteed to be true by the time the
          // array fill completes.
          builder()->LoadTrue().StoreAccumulatorInRegister(done);
          // Fill the array with the iterator.
          FeedbackSlot element_slot =
              feedback_spec()->AddStoreInArrayLiteralICSlot();
          FeedbackSlot index_slot = feedback_spec()->AddBinaryOpICSlot();
          BuildFillArrayWithIterator(iterator, array, index, next_result,
                                     next_value_load_slot, next_done_load_slot,
                                     index_slot, element_slot);
          builder()->Bind(&is_done);
          // Assign the array to the LHS.
          builder()->LoadAccumulatorWithRegister(array);
          BuildAssignment(lhs_data, op, lookup_hoisting_mode);
        }
      },
      // Finally block.
      [&](Register iteration_continuation_token,
          Register iteration_continuation_result, Register message) {
        // Finish the iteration in the finally block.
        BuildFinalizeIteration(iterator, done, iteration_continuation_token);
      },
      HandlerTable::UNCAUGHT);
  if (!execution_result()->IsEffect()) {
    builder()->LoadAccumulatorWithRegister(value);
  }
}
References v8::internal::FeedbackVectorSpec::AddBinaryOpICSlot(), v8::internal::FeedbackVectorSpec::AddLoadICSlot(), v8::internal::FeedbackVectorSpec::AddStoreInArrayLiteralICSlot(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::assign_type(), ast_string_constants(), v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildAssignment(), builder(), BuildFillArrayWithIterator(), BuildFinalizeIteration(), BuildGetIteratorRecord(), BuildIteratorNext(), BuildTryFinally(), v8::internal::interpreter::BytecodeArrayBuilder::CreateEmptyArrayLiteral(), DCHECK_EQ, execution_result(), v8::internal::Spread::expression(), feedback_index(), feedback_spec(), GetDestructuringDefaultValue(), v8::internal::index, v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::IsEffect(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotUndefined(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeArrayBuilder::kConvertToBoolean, v8::internal::kNormal, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadFalse(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTrue(), v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::NON_PROPERTY, PrepareAssignmentLhs(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::HandlerTable::UNCAUGHT, v8::internal::value, v8::internal::ArrayLiteral::values(), VisitInHoleCheckElisionScopeForAccumulatorValue(), v8::internal::Smi::zero(), and zone().
Referenced by BuildAssignment().
BuildDestructuringObjectAssignment()
void v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment (ObjectLiteral * pattern, Token::Value op, LookupHoistingMode lookup_hoisting_mode) [private]
Definition at line 5417 of file bytecode-generator.cc.
                                             {
  RegisterAllocationScope register_scope(this);
  // Store the assignment value in a register.
  Register value;
  RegisterList rest_runtime_callargs;
  if (pattern->builder()->has_rest_property()) {
    rest_runtime_callargs =
        register_allocator()->NewRegisterList(pattern->properties()->length());
    value = rest_runtime_callargs[0];
  } else {
    value = register_allocator()->NewRegister();
  }
  builder()->StoreAccumulatorInRegister(value);
  // if (value === null || value === undefined)
  // throw new TypeError(kNonCoercible);
  //
  // Since the first property access on null/undefined will also trigger a
  // TypeError, we can elide this check. The exception is when there are no
  // properties and no rest property (this is an empty literal), or when the
  // first property is a computed name and accessing it can have side effects.
  //
  // TODO(leszeks): Also eliminate this check if the value is known to be
  // non-null (e.g. an object literal).
  if (pattern->properties()->is_empty() ||
      (pattern->properties()->at(0)->is_computed_name() &&
       pattern->properties()->at(0)->kind() != ObjectLiteralProperty::SPREAD)) {
    BytecodeLabel is_null_or_undefined, not_null_or_undefined;
    builder()
        ->JumpIfUndefinedOrNull(&is_null_or_undefined)
        .Jump(&not_null_or_undefined);
    {
      builder()->Bind(&is_null_or_undefined);
      builder()->SetExpressionPosition(pattern);
      builder()->CallRuntime(Runtime::kThrowPatternAssignmentNonCoercible,
                             value);
    }
    builder()->Bind(&not_null_or_undefined);
  }
  int i = 0;
  for (ObjectLiteralProperty* pattern_property : *pattern->properties()) {
    RegisterAllocationScope inner_register_scope(this);
    // The key of the pattern becomes the key into the RHS value, and the value
    // of the pattern becomes the target of the assignment.
    //
    // e.g. { a: b } = o becomes b = o.a
    Expression* pattern_key = pattern_property->key();
    Expression* target = pattern_property->value();
    Expression* default_value = GetDestructuringDefaultValue(&target);
    builder()->SetExpressionPosition(target);
    // Calculate this property's key into the assignment RHS value, additionally
    // storing the key for rest_runtime_callargs if needed.
    //
    // The RHS is accessed using the key either by LoadNamedProperty (if
    // value_name is valid) or by LoadKeyedProperty (otherwise).
    const AstRawString* value_name = nullptr;
    Register value_key;
    if (pattern_property->kind() != ObjectLiteralProperty::Kind::SPREAD) {
      if (pattern_key->IsPropertyName()) {
        value_name = pattern_key->AsLiteral()->AsRawPropertyName();
      }
      if (pattern->builder()->has_rest_property() || !value_name) {
        if (pattern->builder()->has_rest_property()) {
          value_key = rest_runtime_callargs[i + 1];
        } else {
          value_key = register_allocator()->NewRegister();
        }
        if (pattern_property->is_computed_name()) {
          // { [a()]: b().x } = c
          // becomes
          // var tmp = a()
          // b().x = c[tmp]
          DCHECK(!pattern_key->IsPropertyName() ||
                 !pattern_key->IsNumberLiteral());
          VisitForAccumulatorValue(pattern_key);
          builder()->ToName().StoreAccumulatorInRegister(value_key);
        } else {
          // We only need the key for non-computed properties when it is numeric
          // or is being saved for the rest_runtime_callargs.
          DCHECK(pattern_key->IsNumberLiteral() ||
                 (pattern->builder()->has_rest_property() &&
                  pattern_key->IsPropertyName()));
          VisitForRegisterValue(pattern_key, value_key);
        }
      }
    }
    AssignmentLhsData lhs_data = PrepareAssignmentLhs(target);
    // Get the value from the RHS.
    if (pattern_property->kind() == ObjectLiteralProperty::Kind::SPREAD) {
      DCHECK_EQ(i, pattern->properties()->length() - 1);
      DCHECK(!value_key.is_valid());
      DCHECK_NULL(value_name);
      builder()->CallRuntime(
          Runtime::kInlineCopyDataPropertiesWithExcludedPropertiesOnStack,
          rest_runtime_callargs);
    } else if (value_name) {
      builder()->LoadNamedProperty(
          value, value_name, feedback_index(feedback_spec()->AddLoadICSlot()));
    } else {
      DCHECK(value_key.is_valid());
      builder()->LoadAccumulatorWithRegister(value_key).LoadKeyedProperty(
          value, feedback_index(feedback_spec()->AddKeyedLoadICSlot()));
    }
    // {<pattern> = <init>} = <value>
    // becomes
    // temp = <value>;
    // <pattern> = temp === undefined ? <init> : temp;
    if (default_value) {
      BytecodeLabel value_not_undefined;
      builder()->JumpIfNotUndefined(&value_not_undefined);
      VisitInHoleCheckElisionScopeForAccumulatorValue(default_value);
      builder()->Bind(&value_not_undefined);
    }
    BuildAssignment(lhs_data, op, lookup_hoisting_mode);
    i++;
  }
  if (!execution_result()->IsEffect()) {
    builder()->LoadAccumulatorWithRegister(value);
  }
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildAssignment(), builder(), v8::internal::ObjectLiteral::builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, execution_result(), feedback_index(), feedback_spec(), GetDestructuringDefaultValue(), v8::internal::ObjectLiteralBoilerplateBuilder::has_rest_property(), v8::internal::interpreter::Register::is_valid(), v8::internal::Expression::IsNumberLiteral(), v8::internal::Expression::IsPropertyName(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotUndefined(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadKeyedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), PrepareAssignmentLhs(), v8::internal::ObjectLiteral::properties(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::ObjectLiteralProperty::SPREAD, v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::ToName(), v8::internal::value, VisitForAccumulatorValue(), VisitForRegisterValue(), and VisitInHoleCheckElisionScopeForAccumulatorValue().
Referenced by BuildAssignment().
BuildDisposeScope()
template<typename WrappedFunc >
void v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope (WrappedFunc wrapped_func, bool has_await_using) [private]
Definition at line 2852 of file bytecode-generator.cc.
                                                                {
  RegisterAllocationScope allocation_scope(this);
  DisposablesStackScope disposables_stack_scope(this);
  if (has_await_using) {
    set_catch_prediction(info()->scope()->is_repl_mode_scope()
                             ? HandlerTable::UNCAUGHT_ASYNC_AWAIT
                             : HandlerTable::ASYNC_AWAIT);
  }
  BuildTryFinally(
      // Try block
      [&]() { wrapped_func(); },
      // Finally block
      [&](Register body_continuation_token, Register body_continuation_result,
          Register message) {
        if (has_await_using) {
          Register result_register = register_allocator()->NewRegister();
          Register disposable_stack_register =
              register_allocator()->NewRegister();
          builder()->MoveRegister(current_disposables_stack(),
                                  disposable_stack_register);
          LoopBuilder loop_builder(builder(), nullptr, nullptr,
                                   feedback_spec());
          LoopScope loop_scope(this, &loop_builder);
          {
            RegisterAllocationScope allocation_scope(this);
            RegisterList args = register_allocator()->NewRegisterList(5);
            builder()
                ->MoveRegister(disposable_stack_register, args[0])
                .MoveRegister(body_continuation_token, args[1])
                .MoveRegister(body_continuation_result, args[2])
                .MoveRegister(message, args[3])
                .LoadLiteral(Smi::FromEnum(
                    DisposableStackResourcesType::kAtLeastOneAsync))
                .StoreAccumulatorInRegister(args[4]);
            builder()->CallRuntime(Runtime::kDisposeDisposableStack, args);
          }
          builder()
              ->StoreAccumulatorInRegister(result_register)
              .LoadTrue()
              .CompareReference(result_register);
          loop_builder.BreakIfTrue(ToBooleanMode::kConvertToBoolean);
          builder()->LoadAccumulatorWithRegister(result_register);
          BuildTryCatch(
              [&]() { BuildAwait(); },
              [&](Register context) {
                RegisterList args = register_allocator()->NewRegisterList(3);
                builder()
                    ->MoveRegister(current_disposables_stack(), args[0])
                    .StoreAccumulatorInRegister(args[1]) // exception
                    .LoadTheHole()
                    .SetPendingMessage()
                    .StoreAccumulatorInRegister(args[2])
                    .CallRuntime(
                        Runtime::kHandleExceptionsInDisposeDisposableStack,
                        args);
                builder()->StoreAccumulatorInRegister(
                    disposable_stack_register);
              },
              catch_prediction());
          loop_builder.BindContinueTarget();
        } else {
          RegisterList args = register_allocator()->NewRegisterList(5);
          builder()
              ->MoveRegister(current_disposables_stack(), args[0])
              .MoveRegister(body_continuation_token, args[1])
              .MoveRegister(body_continuation_result, args[2])
              .MoveRegister(message, args[3])
              .LoadLiteral(
                  Smi::FromEnum(DisposableStackResourcesType::kAllSync))
              .StoreAccumulatorInRegister(args[4]);
          builder()->CallRuntime(Runtime::kDisposeDisposableStack, args);
        }
      },
      catch_prediction());
}
References v8::base::args, v8::internal::HandlerTable::ASYNC_AWAIT, v8::internal::interpreter::LoopBuilder::BindContinueTarget(), v8::internal::interpreter::BreakableControlFlowBuilder::BreakIfTrue(), BuildAwait(), builder(), BuildTryCatch(), BuildTryFinally(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), catch_prediction(), v8::internal::interpreter::BytecodeArrayBuilder::CompareReference(), current_disposables_stack(), feedback_spec(), v8::internal::Smi::FromEnum(), info(), v8::internal::kAllSync, v8::internal::kAtLeastOneAsync, v8::internal::interpreter::BytecodeArrayBuilder::kConvertToBoolean, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTheHole(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTrue(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), set_catch_prediction(), v8::internal::interpreter::BytecodeArrayBuilder::SetPendingMessage(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::HandlerTable::UNCAUGHT_ASYNC_AWAIT.
Referenced by GenerateBodyStatementsWithoutImplicitFinalReturn(), and VisitBlockMaybeDispose().
builder()
BytecodeArrayBuilder* v8::internal::interpreter::BytecodeGenerator::builder () [inline], [private]
Definition at line 536 of file bytecode-generator.h.
{ return &builder_; }
References builder_.
Referenced by AddDisposableValue(), AllocateDeferredConstants(), BuildAssignment(), BuildAsyncReturn(), BuildAwait(), BuildCallIteratorMethod(), BuildClassLiteral(), BuildClassProperty(), BuildCreateArrayLiteral(), BuildCreateObjectLiteral(), BuildDeclareCall(), BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), BuildDisposeScope(), BuildFillArrayWithIterator(), BuildFinalizeIteration(), BuildGeneratorObjectVariableInitialization(), BuildGeneratorPrologue(), BuildGetAndCheckSuperConstructor(), BuildGetIterator(), BuildGetIteratorRecord(), BuildHoleCheckForVariableAssignment(), BuildInstanceInitializationAfterSuperCall(), BuildInstanceMemberInitialization(), BuildInvalidPropertyAccess(), BuildIteratorClose(), BuildIteratorNext(), BuildLiteralCompareNil(), BuildLiteralStrictCompareBoolean(), BuildLoadKeyedProperty(), BuildLoadNamedProperty(), BuildLoadPropertyKey(), BuildLocalActivationContextInitialization(), BuildNewLocalActivationContext(), BuildNewLocalBlockContext(), BuildNewLocalCatchContext(), BuildNewLocalWithContext(), BuildOptionalChain(), BuildPrivateBrandCheck(), BuildPrivateBrandInitialization(), BuildPrivateDebugDynamicGet(), BuildPrivateDebugDynamicSet(), BuildPrivateGetterAccess(), BuildPrivateMethodIn(), BuildPrivateSetterAccess(), BuildPushUndefinedIntoRegisterList(), BuildReThrow(), BuildReturn(), BuildSetNamedProperty(), BuildStoreGlobal(), BuildSuperCallOptimization(), BuildSuspendPoint(), BuildTest(), BuildThrowIfHole(), BuildTryCatch(), BuildTryFinally(), BuildVariableAssignment(), BuildVariableLoad(), BytecodeGenerator(), v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::DisposablesStackScope(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute(), FinalizeBytecode(), FinalizeSourcePositionTable(), GenerateAsyncFunctionBody(), GenerateAsyncGeneratorFunctionBody(), GenerateBaseConstructorBody(), GenerateBodyPrologue(), GenerateBodyStatements(), GenerateBytecode(), GenerateDerivedConstructorBody(), GetPotentialVariableInAccumulator(), GetRegisterForLocalVariable(), GetTypeHintForLocalVariable(), IsVariableInRegister(), v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope(), PrepareAssignmentLhs(), register_allocator(), SetVariableInRegister(), VisitAndPushIntoRegisterList(), VisitArguments(), VisitArgumentsObject(), VisitArithmeticExpression(), VisitBlockDeclarationsAndStatements(), VisitCallSuper(), VisitCommaExpression(), VisitDelete(), VisitForAccumulatorValueImpl(), VisitForAccumulatorValueOrTheHole(), VisitForNullishTest(), VisitForRegisterValue(), VisitKeyedSuperPropertyLoad(), VisitLiteralAccessor(), VisitLogicalAndExpression(), VisitLogicalAndSubExpression(), VisitLogicalOrExpression(), VisitLogicalOrSubExpression(), VisitLogicalTestSubExpression(), VisitModuleNamespaceImports(), VisitNamedSuperPropertyLoad(), VisitNaryArithmeticExpression(), VisitNaryCommaExpression(), VisitNaryLogicalAndExpression(), VisitNaryLogicalOrExpression(), VisitNaryNullishExpression(), VisitNewTargetVariable(), VisitNot(), VisitNullishExpression(), VisitNullishSubExpression(), VisitPropertyLoad(), VisitPropertyLoadForRegister(), VisitRestArgumentsArray(), VisitStatements(), VisitThisFunctionVariable(), VisitTypeOf(), and VisitVoid().
BuildFillArrayWithIterator()
void v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator (IteratorRecord iterator, Register array, Register index, Register value, FeedbackSlot next_value_slot, FeedbackSlot next_done_slot, FeedbackSlot index_slot, FeedbackSlot element_slot) [private]
Definition at line 4256 of file bytecode-generator.cc.
                                                        {
  DCHECK(array.is_valid());
  DCHECK(index.is_valid());
  DCHECK(value.is_valid());
  LoopBuilder loop_builder(builder(), nullptr, nullptr, feedback_spec());
  LoopScope loop_scope(this, &loop_builder);
  // Call the iterator's .next() method. Break from the loop if the `done`
  // property is truthy, otherwise load the value from the iterator result and
  // append the argument.
  BuildIteratorNext(iterator, value);
  builder()->LoadNamedProperty(
      value, ast_string_constants()->done_string(),
      feedback_index(feedback_spec()->AddLoadICSlot()));
  loop_builder.BreakIfTrue(ToBooleanMode::kConvertToBoolean);
  loop_builder.LoopBody();
  builder()
      // value = value.value
      ->LoadNamedProperty(value, ast_string_constants()->value_string(),
                          feedback_index(next_value_slot))
      // array[index] = value
      .StoreInArrayLiteral(array, index, feedback_index(element_slot))
      // index++
      .LoadAccumulatorWithRegister(index)
      .UnaryOperation(Token::kInc, feedback_index(index_slot))
      .StoreAccumulatorInRegister(index);
  loop_builder.BindContinueTarget();
}
References ast_string_constants(), v8::internal::interpreter::LoopBuilder::BindContinueTarget(), v8::internal::interpreter::BreakableControlFlowBuilder::BreakIfTrue(), builder(), BuildIteratorNext(), v8::internal::DCHECK(), feedback_index(), feedback_spec(), v8::internal::index, v8::internal::interpreter::Register::is_valid(), v8::internal::interpreter::BytecodeArrayBuilder::kConvertToBoolean, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), v8::internal::interpreter::LoopBuilder::LoopBody(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::StoreInArrayLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::UnaryOperation(), and v8::internal::value.
Referenced by BuildCreateArrayLiteral(), and BuildDestructuringArrayAssignment().
BuildFinalizeIteration()
void v8::internal::interpreter::BytecodeGenerator::BuildFinalizeIteration (IteratorRecord iterator, Register done, Register iteration_continuation_token) [private]
Definition at line 5110 of file bytecode-generator.cc.
                                           {
  RegisterAllocationScope register_scope(this);
  BytecodeLabels iterator_is_done(zone());
  // if (!done) {
  builder()->LoadAccumulatorWithRegister(done).JumpIfTrue(
      ToBooleanMode::kConvertToBoolean, iterator_is_done.New());
  {
    RegisterAllocationScope inner_register_scope(this);
    BuildTryCatch(
        // try {
        // let method = iterator.return
        // if (method !== null && method !== undefined) {
        // let return_val = method.call(iterator)
        // if (!%IsObject(return_val)) throw TypeError
        // }
        // }
        [&]() {
          Register method = register_allocator()->NewRegister();
          builder()
              ->LoadNamedProperty(
                  iterator.object(), ast_string_constants()->return_string(),
                  feedback_index(feedback_spec()->AddLoadICSlot()))
              .JumpIfUndefinedOrNull(iterator_is_done.New())
              .StoreAccumulatorInRegister(method);
          RegisterList args(iterator.object());
          builder()->CallProperty(
              method, args, feedback_index(feedback_spec()->AddCallICSlot()));
          if (iterator.type() == IteratorType::kAsync) {
            BuildAwait();
          }
          builder()->JumpIfJSReceiver(iterator_is_done.New());
          {
            // Throw this exception inside the try block so that it is
            // suppressed by the iteration continuation if necessary.
            RegisterAllocationScope register_scope(this);
            Register return_result = register_allocator()->NewRegister();
            builder()
                ->StoreAccumulatorInRegister(return_result)
                .CallRuntime(Runtime::kThrowIteratorResultNotAnObject,
                             return_result);
          }
        },
        // catch (e) {
        // if (iteration_continuation != RETHROW)
        // rethrow e
        // }
        [&](Register context) {
          // Reuse context register to store the exception.
          Register close_exception = context;
          builder()->StoreAccumulatorInRegister(close_exception);
          BytecodeLabel suppress_close_exception;
          builder()
              ->LoadLiteral(Smi::FromInt(
                  static_cast<int>(TryFinallyContinuationToken::kRethrowToken)))
              .CompareReference(iteration_continuation_token)
              .JumpIfTrue(ToBooleanMode::kAlreadyBoolean,
                          &suppress_close_exception)
              .LoadAccumulatorWithRegister(close_exception)
              .ReThrow()
              .Bind(&suppress_close_exception);
        },
        catch_prediction());
  }
  iterator_is_done.Bind(builder());
}
References v8::base::args, ast_string_constants(), v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildAwait(), builder(), BuildTryCatch(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), catch_prediction(), v8::internal::interpreter::BytecodeArrayBuilder::CompareReference(), feedback_index(), feedback_spec(), v8::internal::Smi::FromInt(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, v8::internal::kAsync, v8::internal::interpreter::BytecodeArrayBuilder::kConvertToBoolean, v8::internal::interpreter::kRethrowToken, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeGenerator::IteratorRecord::object(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::ReThrow(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeGenerator::IteratorRecord::type(), and zone().
Referenced by BuildDestructuringArrayAssignment().
BuildGeneratorObjectVariableInitialization()
void v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization () [private]
Definition at line 8388 of file bytecode-generator.cc.
                                                                   {
  DCHECK(IsResumableFunction(info()->literal()->kind()));
  Variable* generator_object_var = closure_scope()->generator_object_var();
  RegisterAllocationScope register_scope(this);
  RegisterList args = register_allocator()->NewRegisterList(2);
  Runtime::FunctionId function_id =
      ((IsAsyncFunction(info()->literal()->kind()) &&
        !IsAsyncGeneratorFunction(info()->literal()->kind())) ||
       IsModuleWithTopLevelAwait(info()->literal()->kind()))
          ? Runtime::kInlineAsyncFunctionEnter
          : Runtime::kInlineCreateJSGeneratorObject;
  builder()
      ->MoveRegister(Register::function_closure(), args[0])
      .MoveRegister(builder()->Receiver(), args[1])
      .CallRuntime(function_id, args)
      .StoreAccumulatorInRegister(generator_object());
  if (generator_object_var->location() == VariableLocation::LOCAL) {
    // The generator object register is already set to the variable's local
    // register.
    DCHECK_EQ(generator_object().index(),
              GetRegisterForLocalVariable(generator_object_var).index());
  } else {
    BuildVariableAssignment(generator_object_var, Token::kInit,
                            HoleCheckMode::kElided);
  }
}
References v8::base::args, builder(), BuildVariableAssignment(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), closure_scope(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Register::function_closure(), generator_object(), v8::internal::DeclarationScope::generator_object_var(), GetRegisterForLocalVariable(), v8::internal::index, info(), v8::internal::IsAsyncFunction(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::IsModuleWithTopLevelAwait(), v8::internal::IsResumableFunction(), v8::internal::kElided, v8::internal::FunctionLiteral::kind(), v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::LOCAL, v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by GenerateAsyncFunctionBody(), GenerateAsyncGeneratorFunctionBody(), and GenerateBytecodeBody().
BuildGeneratorPrologue()
void v8::internal::interpreter::BytecodeGenerator::BuildGeneratorPrologue () [private]
Definition at line 2032 of file bytecode-generator.cc.
                                               {
  DCHECK_GT(info()->literal()->suspend_count(), 0);
  generator_jump_table_ =
      builder()->AllocateJumpTable(info()->literal()->suspend_count(), 0);
  // If the generator is not undefined, this is a resume, so perform state
  // dispatch.
  builder()->SwitchOnGeneratorState(generator_object(), generator_jump_table_);
  // Otherwise, fall-through to the ordinary function prologue, after which we
  // will run into the generator object creation and other extra code inserted
  // by the parser.
}
References v8::internal::interpreter::BytecodeArrayBuilder::AllocateJumpTable(), builder(), DCHECK_GT, generator_jump_table_, generator_object(), info(), and v8::internal::interpreter::BytecodeArrayBuilder::SwitchOnGeneratorState().
Referenced by GenerateBytecode().
BuildGetAndCheckSuperConstructor()
void v8::internal::interpreter::BytecodeGenerator::BuildGetAndCheckSuperConstructor (Register this_function, Register new_target, Register constructor, BytecodeLabel * super_ctor_call_done) [private]
Definition at line 6887 of file bytecode-generator.cc.
                                         {
  bool omit_super_ctor = v8_flags.omit_default_ctors &&
                         IsDerivedConstructor(info()->literal()->kind());
  if (omit_super_ctor) {
    BuildSuperCallOptimization(this_function, new_target, constructor,
                               super_ctor_call_done);
  } else {
    builder()
        ->LoadAccumulatorWithRegister(this_function)
        .GetSuperConstructor(constructor);
  }
  // Check if the constructor is in fact a constructor.
  builder()->ThrowIfNotSuperConstructor(constructor);
}
References builder(), BuildSuperCallOptimization(), v8::internal::interpreter::BytecodeArrayBuilder::GetSuperConstructor(), info(), v8::internal::IsDerivedConstructor(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::ThrowIfNotSuperConstructor(), and v8::internal::v8_flags.
Referenced by VisitCallSuper().
BuildGetIterator()
void v8::internal::interpreter::BytecodeGenerator::BuildGetIterator (IteratorType hint) [private]
Definition at line 7690 of file bytecode-generator.cc.
                                                          {
  if (hint == IteratorType::kAsync) {
    RegisterAllocationScope scope(this);
    Register obj = register_allocator()->NewRegister();
    Register method = register_allocator()->NewRegister();
    // Set method to GetMethod(obj, @@asyncIterator)
    builder()->StoreAccumulatorInRegister(obj).LoadAsyncIteratorProperty(
        obj, feedback_index(feedback_spec()->AddLoadICSlot()));
    BytecodeLabel async_iterator_undefined, done;
    builder()->JumpIfUndefinedOrNull(&async_iterator_undefined);
    // Let iterator be Call(method, obj)
    builder()->StoreAccumulatorInRegister(method).CallProperty(
        method, RegisterList(obj),
        feedback_index(feedback_spec()->AddCallICSlot()));
    // If Type(iterator) is not Object, throw a TypeError exception.
    builder()->JumpIfJSReceiver(&done);
    builder()->CallRuntime(Runtime::kThrowSymbolAsyncIteratorInvalid);
    builder()->Bind(&async_iterator_undefined);
    // If method is undefined,
    // Let syncMethod be GetMethod(obj, @@iterator)
    builder()
        ->LoadIteratorProperty(obj,
                               feedback_index(feedback_spec()->AddLoadICSlot()))
        .StoreAccumulatorInRegister(method);
    // Let syncIterator be Call(syncMethod, obj)
    builder()->CallProperty(method, RegisterList(obj),
                            feedback_index(feedback_spec()->AddCallICSlot()));
    // Return CreateAsyncFromSyncIterator(syncIterator)
    // alias `method` register as it's no longer used
    Register sync_iter = method;
    builder()->StoreAccumulatorInRegister(sync_iter).CallRuntime(
        Runtime::kInlineCreateAsyncFromSyncIterator, sync_iter);
    builder()->Bind(&done);
  } else {
    {
      RegisterAllocationScope scope(this);
      Register obj = register_allocator()->NewRegister();
      int load_feedback_index =
          feedback_index(feedback_spec()->AddLoadICSlot());
      int call_feedback_index =
          feedback_index(feedback_spec()->AddCallICSlot());
      // Let method be GetMethod(obj, @@iterator) and
      // iterator be Call(method, obj). If iterator is
      // not JSReceiver, then throw TypeError.
      builder()->StoreAccumulatorInRegister(obj).GetIterator(
          obj, load_feedback_index, call_feedback_index);
    }
  }
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeArrayBuilder::GetIterator(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::kAsync, v8::internal::interpreter::BytecodeArrayBuilder::LoadAsyncIteratorProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadIteratorProperty(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildGetIteratorRecord().
BuildGetIteratorRecord() [1/2]
BytecodeGenerator::IteratorRecord v8::internal::interpreter::BytecodeGenerator::BuildGetIteratorRecord (IteratorType hint) [private]
Definition at line 7766 of file bytecode-generator.cc.
                       {
  Register next = register_allocator()->NewRegister();
  Register object = register_allocator()->NewRegister();
  return BuildGetIteratorRecord(next, object, hint);
}
References BuildGetIteratorRecord(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), and register_allocator().
BuildGetIteratorRecord() [2/2]
BytecodeGenerator::IteratorRecord v8::internal::interpreter::BytecodeGenerator::BuildGetIteratorRecord (Register iterator_next, Register iterator_object, IteratorType hint) [private]
Definition at line 7753 of file bytecode-generator.cc.
                                                       {
  DCHECK(next.is_valid() && object.is_valid());
  BuildGetIterator(hint);
  builder()
      ->StoreAccumulatorInRegister(object)
      .LoadNamedProperty(object, ast_string_constants()->next_string(),
                         feedback_index(feedback_spec()->AddLoadICSlot()))
      .StoreAccumulatorInRegister(next);
  return IteratorRecord(object, next, hint);
}
References ast_string_constants(), builder(), BuildGetIterator(), v8::internal::DCHECK(), feedback_index(), feedback_spec(), v8::internal::interpreter::Register::is_valid(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildCreateArrayLiteral(), BuildDestructuringArrayAssignment(), and BuildGetIteratorRecord().
BuildHoleCheckForVariableAssignment()
void v8::internal::interpreter::BytecodeGenerator::BuildHoleCheckForVariableAssignment (Variable * variable, Token::Value op) [private]
Definition at line 4707 of file bytecode-generator.cc.
                                                                           {
  DCHECK(!IsPrivateMethodOrAccessorVariableMode(variable->mode()));
  DCHECK(VariableNeedsHoleCheckInCurrentBlockForAssignment(
      variable, op, HoleCheckMode::kRequired));
  if (variable->is_this()) {
    DCHECK(variable->mode() == VariableMode::kConst && op == Token::kInit);
    // Perform an initialization check for 'this'. 'this' variable is the
    // only variable able to trigger bind operations outside the TDZ
    // via 'super' calls.
    //
    // Do not remember the hole check because this bytecode throws if 'this' is
    // *not* the hole, i.e. the opposite of the TDZ hole check.
    builder()->ThrowSuperAlreadyCalledIfNotHole();
  } else {
    // Perform an initialization check for let/const declared variables.
    // E.g. let x = (x = 20); is not allowed.
    DCHECK(IsLexicalVariableMode(variable->mode()));
    BuildThrowIfHole(variable);
  }
}
References builder(), BuildThrowIfHole(), v8::internal::DCHECK(), v8::internal::IsLexicalVariableMode(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::kConst, v8::internal::kRequired, v8::internal::interpreter::BytecodeArrayBuilder::ThrowSuperAlreadyCalledIfNotHole(), and VariableNeedsHoleCheckInCurrentBlockForAssignment().
Referenced by BuildVariableAssignment().
BuildIncrementBlockCoverageCounterIfEnabled() [1/2]
void v8::internal::interpreter::BytecodeGenerator::BuildIncrementBlockCoverageCounterIfEnabled (AstNode * node, SourceRangeKind kind) [private]
Definition at line 8459 of file bytecode-generator.cc.
                                         {
  if (block_coverage_builder_ == nullptr) return;
  block_coverage_builder_->IncrementBlockCounter(node, kind);
}
References block_coverage_builder_, and v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter().
Referenced by GenerateBodyPrologue(), VisitDelete(), VisitLogicalAndExpression(), VisitLogicalAndSubExpression(), VisitLogicalOrExpression(), VisitLogicalOrSubExpression(), VisitLogicalTestSubExpression(), VisitNullishExpression(), VisitNullishSubExpression(), and VisitPropertyLoad().
BuildIncrementBlockCoverageCounterIfEnabled() [2/2]
void v8::internal::interpreter::BytecodeGenerator::BuildIncrementBlockCoverageCounterIfEnabled (int coverage_array_slot) [private]
Definition at line 8465 of file bytecode-generator.cc.
                             {
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(coverage_array_slot);
  }
}
References block_coverage_builder_, and v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter().
BuildInitializationBlockForParametersIfExist()
bool v8::internal::interpreter::BytecodeGenerator::BuildInitializationBlockForParametersIfExist () [private]
Definition at line 1899 of file bytecode-generator.cc.
                                                                     {
  ZonePtrList<Statement>* body = info()->literal()->body();
  if (body->length() > 0 && body->at(0)->IsBlock()) {
    Block* block = body->at(0)->AsBlock();
    if (block->is_initialization_block_for_parameters()) {
      RegisterAllocationScope allocation_scope(this);
      VisitBlockDeclarationsAndStatements(block);
      return true;
    }
  }
  return false;
}
References v8::internal::ZoneList< T >::at(), v8::internal::FunctionLiteral::body(), info(), v8::internal::ZoneList< T >::length(), v8::internal::UnoptimizedCompilationInfo::literal(), and VisitBlockDeclarationsAndStatements().
Referenced by GenerateAsyncGeneratorFunctionBody(), and GenerateBytecodeBody().
BuildInstanceInitializationAfterSuperCall()
void v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall (Register this_function, Register instance) [private]
Definition at line 6837 of file bytecode-generator.cc.
                                               {
  // Explicit calls to the super constructor using super() perform an
  // implicit binding assignment to the 'this' variable.
  //
  // Default constructors don't need have to do the assignment because
  // 'this' isn't accessed in default constructors.
  if (!IsDefaultConstructor(info()->literal()->kind())) {
    Variable* var = closure_scope()->GetReceiverScope()->receiver();
    builder()->LoadAccumulatorWithRegister(instance);
    BuildVariableAssignment(var, Token::kInit, HoleCheckMode::kRequired);
  }
  // The constructor scope always needs ScopeInfo, so we are certain that
  // the first constructor scope found in the outer scope chain is the
  // scope that we are looking for for this super() call.
  // Note that this doesn't necessarily mean that the constructor needs
  // a context, if it doesn't this would get handled specially in
  // BuildPrivateBrandInitialization().
  DeclarationScope* constructor_scope = info()->scope()->GetConstructorScope();
  // We can rely on the class_scope_has_private_brand bit to tell if the
  // constructor needs private brand initialization, and if that's
  // the case we are certain that its outer class scope requires a context to
  // keep the brand variable, so we can just get the brand variable
  // from the outer scope.
  if (constructor_scope->class_scope_has_private_brand()) {
    DCHECK(constructor_scope->outer_scope()->is_class_scope());
    ClassScope* class_scope = constructor_scope->outer_scope()->AsClassScope();
    DCHECK_NOT_NULL(class_scope->brand());
    Variable* brand = class_scope->brand();
    BuildPrivateBrandInitialization(instance, brand);
  }
  // The derived constructor has the correct bit set always, so we
  // don't emit code to load and call the initializer if not
  // required.
  //
  // For the arrow function or eval case, we always emit code to load
  // and call the initializer.
  //
  // TODO(gsathya): In the future, we could tag nested arrow functions
  // or eval with the correct bit so that we do the load conditionally
  // if required.
  if (info()->literal()->requires_instance_members_initializer() ||
      !IsDerivedConstructor(info()->literal()->kind())) {
    BuildInstanceMemberInitialization(this_function, instance);
  }
}
References v8::internal::Scope::AsClassScope(), v8::internal::ClassScope::brand(), builder(), BuildInstanceMemberInitialization(), BuildPrivateBrandInitialization(), BuildVariableAssignment(), v8::internal::DeclarationScope::class_scope_has_private_brand(), closure_scope(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Scope::GetConstructorScope(), v8::internal::Scope::GetReceiverScope(), info(), v8::internal::Scope::is_class_scope(), v8::internal::IsDefaultConstructor(), v8::internal::IsDerivedConstructor(), v8::internal::kRequired, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::Scope::outer_scope(), v8::internal::DeclarationScope::receiver(), v8::internal::requires_instance_members_initializer, and v8::internal::UnoptimizedCompilationInfo::scope().
Referenced by VisitCallSuper().
BuildInstanceMemberInitialization()
void v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization (Register constructor, Register instance) [private]
Definition at line 3807 of file bytecode-generator.cc.
                                                                             {
  RegisterList args = register_allocator()->NewRegisterList(1);
  Register initializer = register_allocator()->NewRegister();
  FeedbackSlot slot = feedback_spec()->AddLoadICSlot();
  BytecodeLabel done;
  builder()
      ->LoadClassFieldsInitializer(constructor, feedback_index(slot))
      // TODO(gsathya): This jump can be elided for the base
      // constructor and derived constructor. This is only required
      // when called from an arrow function.
      .JumpIfUndefined(&done)
      .StoreAccumulatorInRegister(initializer)
      .MoveRegister(instance, args[0])
      .CallProperty(initializer, args,
                    feedback_index(feedback_spec()->AddCallICSlot()))
      .Bind(&done);
}
References v8::internal::FeedbackVectorSpec::AddLoadICSlot(), v8::base::args, v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefined(), v8::internal::interpreter::BytecodeArrayBuilder::LoadClassFieldsInitializer(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildInstanceInitializationAfterSuperCall(), and GenerateBaseConstructorBody().
BuildInvalidPropertyAccess()
void v8::internal::interpreter::BytecodeGenerator::BuildInvalidPropertyAccess (MessageTemplate tmpl, Property * property) [private]
Definition at line 3762 of file bytecode-generator.cc.
                                                                       {
  RegisterAllocationScope register_scope(this);
  const AstRawString* name = property->key()->AsVariableProxy()->raw_name();
  RegisterList args = register_allocator()->NewRegisterList(2);
  builder()
      ->LoadLiteral(Smi::FromEnum(tmpl))
      .StoreAccumulatorInRegister(args[0])
      .LoadLiteral(name)
      .StoreAccumulatorInRegister(args[1])
      .CallRuntime(Runtime::kNewTypeError, args)
      .Throw();
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::Smi::FromEnum(), v8::internal::Property::key(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::name, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::interpreter::BytecodeArrayBuilder::Throw().
Referenced by BuildAssignment(), and VisitPropertyLoad().
BuildIteratorClose()
void v8::internal::interpreter::BytecodeGenerator::BuildIteratorClose (const IteratorRecord & iterator, Expression * expr = nullptr) [private]
Definition at line 7809 of file bytecode-generator.cc.
                                                             {
  RegisterAllocationScope register_scope(this);
  BytecodeLabels done(zone());
  BytecodeLabel if_called;
  RegisterList args = RegisterList(iterator.object());
  BuildCallIteratorMethod(iterator.object(),
                          ast_string_constants()->return_string(), args,
                          &if_called, &done);
  builder()->Bind(&if_called);
  if (iterator.type() == IteratorType::kAsync) {
    DCHECK_NOT_NULL(expr);
    BuildAwait(expr->position());
  }
  builder()->JumpIfJSReceiver(done.New());
  {
    RegisterAllocationScope inner_register_scope(this);
    Register return_result = register_allocator()->NewRegister();
    builder()
        ->StoreAccumulatorInRegister(return_result)
        .CallRuntime(Runtime::kThrowIteratorResultNotAnObject, return_result);
  }
  done.Bind(builder());
}
References v8::base::args, ast_string_constants(), v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildAwait(), BuildCallIteratorMethod(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), DCHECK_NOT_NULL, v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver(), v8::internal::kAsync, v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeGenerator::IteratorRecord::object(), v8::internal::AstNode::position(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeGenerator::IteratorRecord::type(), and zone().
BuildIteratorNext()
void v8::internal::interpreter::BytecodeGenerator::BuildIteratorNext (const IteratorRecord & iterator, Register next_result) [private]
Definition at line 7773 of file bytecode-generator.cc.
                                                                {
  DCHECK(next_result.is_valid());
  builder()->CallProperty(iterator.next(), RegisterList(iterator.object()),
                          feedback_index(feedback_spec()->AddCallICSlot()));
  if (iterator.type() == IteratorType::kAsync) {
    BuildAwait();
  }
  BytecodeLabel is_object;
  builder()
      ->StoreAccumulatorInRegister(next_result)
      .JumpIfJSReceiver(&is_object)
      .CallRuntime(Runtime::kThrowIteratorResultNotAnObject, next_result)
      .Bind(&is_object);
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildAwait(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::DCHECK(), feedback_index(), feedback_spec(), v8::internal::interpreter::Register::is_valid(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver(), v8::internal::kAsync, v8::internal::interpreter::BytecodeGenerator::IteratorRecord::next(), v8::internal::interpreter::BytecodeGenerator::IteratorRecord::object(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::interpreter::BytecodeGenerator::IteratorRecord::type().
Referenced by BuildDestructuringArrayAssignment(), and BuildFillArrayWithIterator().
BuildLiteralCompareNil()
void v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil (Token::Value compare_op, BytecodeArrayBuilder::NilValue nil) [private]
Definition at line 7405 of file bytecode-generator.cc.
                                                     {
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    switch (test_result->fallthrough()) {
      case TestFallthrough::kThen:
        builder()->JumpIfNotNil(test_result->NewElseLabel(), op, nil);
        break;
      case TestFallthrough::kElse:
        builder()->JumpIfNil(test_result->NewThenLabel(), op, nil);
        break;
      case TestFallthrough::kNone:
        builder()
            ->JumpIfNil(test_result->NewThenLabel(), op, nil)
            .Jump(test_result->NewElseLabel());
    }
    test_result->SetResultConsumedByTest();
  } else {
    builder()->CompareNil(op, nil);
  }
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CompareNil(), execution_result(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNil(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfNotNil(), kElse, kNone, kThen, v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewElseLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel(), and v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest().
BuildLiteralStrictCompareBoolean()
void v8::internal::interpreter::BytecodeGenerator::BuildLiteralStrictCompareBoolean (Literal * literal) [private]
Definition at line 7427 of file bytecode-generator.cc.
                                                                         {
  DCHECK(literal->IsBooleanLiteral());
  Register result = register_allocator()->NewRegister();
  builder()->StoreAccumulatorInRegister(result);
  builder()->LoadBoolean(literal->AsBooleanLiteral());
  builder()->CompareReference(result);
}
References v8::internal::Literal::AsBooleanLiteral(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::CompareReference(), v8::internal::DCHECK(), v8::internal::Expression::IsBooleanLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadBoolean(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::base::internal::result, and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
BuildLoadKeyedProperty()
void v8::internal::interpreter::BytecodeGenerator::BuildLoadKeyedProperty (Register object, FeedbackSlot slot) [private]
Definition at line 4946 of file bytecode-generator.cc.
                                                                  {
  if (v8_flags.enable_enumerated_keyed_access_bytecode &&
      current_for_in_scope() != nullptr) {
    Variable* key = GetPotentialVariableInAccumulator();
    if (key != nullptr) {
      ForInScope* scope = current_for_in_scope()->GetForInScope(key);
      if (scope != nullptr) {
        Register enum_index = scope->enum_index();
        Register cache_type = scope->cache_type();
        builder()->LoadEnumeratedKeyedProperty(object, enum_index, cache_type,
                                               feedback_index(slot));
        return;
      }
    }
  }
  builder()->LoadKeyedProperty(object, feedback_index(slot));
}
References builder(), v8::internal::interpreter::BytecodeGenerator::ForInScope::cache_type(), current_for_in_scope(), v8::internal::interpreter::BytecodeGenerator::ForInScope::enum_index(), feedback_index(), v8::internal::interpreter::BytecodeGenerator::ForInScope::GetForInScope(), GetPotentialVariableInAccumulator(), v8::internal::key, v8::internal::interpreter::BytecodeArrayBuilder::LoadEnumeratedKeyedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadKeyedProperty(), and v8::internal::v8_flags.
Referenced by VisitPropertyLoad().
BuildLoadNamedProperty()
void v8::internal::interpreter::BytecodeGenerator::BuildLoadNamedProperty (const Expression * object_expr, Register object, const AstRawString * name) [private]
Definition at line 4906 of file bytecode-generator.cc.
                                                                         {
  FeedbackSlot slot = GetCachedLoadICSlot(object_expr, name);
  builder()->LoadNamedProperty(object, name, feedback_index(slot));
}
References builder(), feedback_index(), GetCachedLoadICSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedProperty(), and v8::internal::name.
Referenced by VisitPropertyLoad().
BuildLoadPropertyKey()
void v8::internal::interpreter::BytecodeGenerator::BuildLoadPropertyKey (LiteralProperty * property, Register out_reg) [private]
Definition at line 8423 of file bytecode-generator.cc.
                                                               {
  if (property->key()->IsStringLiteral()) {
    builder()
        ->LoadLiteral(property->key()->AsLiteral()->AsRawString())
        .StoreAccumulatorInRegister(out_reg);
  } else {
    VisitForAccumulatorValue(property->key());
    builder()->ToName().StoreAccumulatorInRegister(out_reg);
  }
}
References builder(), v8::internal::Expression::IsStringLiteral(), v8::internal::LiteralProperty::key(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::ToName(), and VisitForAccumulatorValue().
Referenced by BuildClassLiteral().
BuildLocalActivationContextInitialization()
void v8::internal::interpreter::BytecodeGenerator::BuildLocalActivationContextInitialization () [private]
Definition at line 8273 of file bytecode-generator.cc.
                                                                  {
  DeclarationScope* scope = closure_scope();
  if (scope->has_this_declaration() && scope->receiver()->IsContextSlot()) {
    Variable* variable = scope->receiver();
    Register receiver(builder()->Receiver());
    // Context variable (at bottom of the context chain).
    DCHECK_EQ(0, scope->ContextChainLength(variable->scope()));
    builder()->LoadAccumulatorWithRegister(receiver).StoreContextSlot(
        execution_context()->reg(), variable, 0);
  }
  // Copy parameters into context if necessary.
  int num_parameters = scope->num_parameters();
  for (int i = 0; i < num_parameters; i++) {
    Variable* variable = scope->parameter(i);
    if (!variable->IsContextSlot()) continue;
    Register parameter(builder()->Parameter(i));
    // Context variable (at bottom of the context chain).
    DCHECK_EQ(0, scope->ContextChainLength(variable->scope()));
    builder()->LoadAccumulatorWithRegister(parameter).StoreContextSlot(
        execution_context()->reg(), variable, 0);
  }
}
References builder(), closure_scope(), v8::internal::Scope::ContextChainLength(), DCHECK_EQ, execution_context(), v8::internal::DeclarationScope::has_this_declaration(), v8::internal::Variable::IsContextSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::DeclarationScope::num_parameters(), v8::internal::DeclarationScope::parameter(), v8::internal::DeclarationScope::receiver(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreContextSlot().
Referenced by GenerateBytecode().
BuildNewLocalActivationContext()
void v8::internal::interpreter::BytecodeGenerator::BuildNewLocalActivationContext () [private]
Definition at line 8246 of file bytecode-generator.cc.
                                                       {
  ValueResultScope value_execution_result(this);
  Scope* scope = closure_scope();
  DCHECK_EQ(current_scope(), closure_scope());
  // Create the appropriate context.
  DCHECK(scope->is_function_scope() || scope->is_eval_scope());
  int slot_count = scope->num_heap_slots() - Context::MIN_CONTEXT_SLOTS;
  if (slot_count <= ConstructorBuiltins::MaximumFunctionContextSlots()) {
    switch (scope->scope_type()) {
      case EVAL_SCOPE:
        builder()->CreateEvalContext(scope, slot_count);
        break;
      case FUNCTION_SCOPE:
        builder()->CreateFunctionContext(scope, slot_count);
        break;
      default:
        UNREACHABLE();
    }
  } else {
    Register arg = register_allocator()->NewRegister();
    builder()->LoadLiteral(scope).StoreAccumulatorInRegister(arg).CallRuntime(
        Runtime::kNewFunctionContext, arg);
    register_allocator()->ReleaseRegister(arg);
  }
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), closure_scope(), v8::internal::interpreter::BytecodeArrayBuilder::CreateEvalContext(), v8::internal::interpreter::BytecodeArrayBuilder::CreateFunctionContext(), current_scope(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, v8::internal::Scope::is_eval_scope(), v8::internal::Scope::is_function_scope(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::ConstructorBuiltins::MaximumFunctionContextSlots(), v8::internal::Context::MIN_CONTEXT_SLOTS, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::Scope::num_heap_slots(), register_allocator(), v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister(), v8::internal::Scope::scope_type(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::UNREACHABLE().
Referenced by GenerateBytecode().
BuildNewLocalBlockContext()
void v8::internal::interpreter::BytecodeGenerator::BuildNewLocalBlockContext (Scope * scope) [private]
Definition at line 8299 of file bytecode-generator.cc.
                                                              {
  ValueResultScope value_execution_result(this);
  DCHECK(scope->is_block_scope());
  builder()->CreateBlockContext(scope);
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::CreateBlockContext(), v8::internal::DCHECK(), and v8::internal::Scope::is_block_scope().
Referenced by v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope().
BuildNewLocalCatchContext()
void v8::internal::interpreter::BytecodeGenerator::BuildNewLocalCatchContext (Scope * scope) [private]
Definition at line 8317 of file bytecode-generator.cc.
                                                              {
  ValueResultScope value_execution_result(this);
  DCHECK(scope->catch_variable()->IsContextSlot());
  Register exception = register_allocator()->NewRegister();
  builder()->StoreAccumulatorInRegister(exception);
  builder()->CreateCatchContext(exception, scope);
  register_allocator()->ReleaseRegister(exception);
}
References builder(), v8::internal::Scope::catch_variable(), v8::internal::interpreter::BytecodeArrayBuilder::CreateCatchContext(), v8::internal::DCHECK(), v8::internal::Variable::IsContextSlot(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
BuildNewLocalWithContext()
void v8::internal::interpreter::BytecodeGenerator::BuildNewLocalWithContext (Scope * scope) [private]
Definition at line 8306 of file bytecode-generator.cc.
                                                             {
  ValueResultScope value_execution_result(this);
  Register extension_object = register_allocator()->NewRegister();
  builder()->ToObject(extension_object);
  builder()->CreateWithContext(extension_object, scope);
  register_allocator()->ReleaseRegister(extension_object);
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::CreateWithContext(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::internal::interpreter::BytecodeRegisterAllocator::ReleaseRegister(), and v8::internal::interpreter::BytecodeArrayBuilder::ToObject().
BuildOptionalChain()
template<typename ExpressionFunc >
void v8::internal::interpreter::BytecodeGenerator::BuildOptionalChain (ExpressionFunc expression_func) [private]
Definition at line 6483 of file bytecode-generator.cc.
                                                                         {
  BytecodeLabel done;
  OptionalChainNullLabelScope label_scope(this);
  // Use the same scope for the entire optional chain, as links earlier in the
  // chain dominate later links, linearly.
  HoleCheckElisionScope elider(this);
  expression_func();
  builder()->Jump(&done);
  label_scope.labels()->Bind(builder());
  builder()->LoadUndefined();
  builder()->Bind(&done);
}
References v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeGenerator::OptionalChainNullLabelScope::labels(), and v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined().
BuildPrivateBrandCheck()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandCheck (Property * property, Register object) [private]
Definition at line 6361 of file bytecode-generator.cc.
                                                                {
  Variable* private_name = property->key()->AsVariableProxy()->var();
  DCHECK(IsPrivateMethodOrAccessorVariableMode(private_name->mode()));
  ClassScope* scope = private_name->scope()->AsClassScope();
  builder()->SetExpressionPosition(property);
  if (private_name->is_static()) {
    // For static private methods, the only valid receiver is the class.
    // Load the class constructor.
    if (scope->class_variable() == nullptr) {
      // If the static private method has not been used used in source
      // code (either explicitly or through the presence of eval), but is
      // accessed by the debugger at runtime, reference to the class variable
      // is not available since it was not be context-allocated. Therefore we
      // can't build a branch check, and throw an ReferenceError as if the
      // method was optimized away.
      // TODO(joyee): get a reference to the class constructor through
      // something other than scope->class_variable() in this scenario.
      RegisterAllocationScope register_scope(this);
      RegisterList args = register_allocator()->NewRegisterList(2);
      builder()
          ->LoadLiteral(Smi::FromEnum(
              MessageTemplate::
                  kInvalidUnusedPrivateStaticMethodAccessedByDebugger))
          .StoreAccumulatorInRegister(args[0])
          .LoadLiteral(private_name->raw_name())
          .StoreAccumulatorInRegister(args[1])
          .CallRuntime(Runtime::kNewError, args)
          .Throw();
    } else {
      BuildVariableLoadForAccumulatorValue(scope->class_variable(),
                                           HoleCheckMode::kElided);
      BytecodeLabel return_check;
      builder()->CompareReference(object).JumpIfTrue(
          ToBooleanMode::kAlreadyBoolean, &return_check);
      const AstRawString* name = scope->class_variable()->raw_name();
      RegisterAllocationScope register_scope(this);
      RegisterList args = register_allocator()->NewRegisterList(2);
      builder()
          ->LoadLiteral(
              Smi::FromEnum(MessageTemplate::kInvalidPrivateBrandStatic))
          .StoreAccumulatorInRegister(args[0])
          .LoadLiteral(name)
          .StoreAccumulatorInRegister(args[1])
          .CallRuntime(Runtime::kNewTypeError, args)
          .Throw();
      builder()->Bind(&return_check);
    }
  } else {
    BuildVariableLoadForAccumulatorValue(scope->brand(),
                                         HoleCheckMode::kElided);
    builder()->LoadKeyedProperty(
        object, feedback_index(feedback_spec()->AddKeyedLoadICSlot()));
  }
}
References v8::base::args, v8::internal::Scope::AsClassScope(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::ClassScope::brand(), builder(), BuildVariableLoadForAccumulatorValue(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::ClassScope::class_variable(), v8::internal::interpreter::BytecodeArrayBuilder::CompareReference(), v8::internal::DCHECK(), feedback_index(), feedback_spec(), v8::internal::Smi::FromEnum(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, v8::internal::kElided, v8::internal::Property::key(), v8::internal::interpreter::BytecodeArrayBuilder::LoadKeyedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::name, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::Variable::raw_name(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::interpreter::BytecodeArrayBuilder::Throw().
Referenced by BuildAssignment(), and VisitPropertyLoad().
BuildPrivateBrandInitialization()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization (Register receiver, Variable * brand) [private]
Definition at line 3776 of file bytecode-generator.cc.
                                                                         {
  BuildVariableLoad(brand, HoleCheckMode::kElided);
  int depth = execution_context()->ContextChainDepth(brand->scope());
  ContextScope* class_context = execution_context()->Previous(depth);
  if (class_context) {
    Register brand_reg = register_allocator()->NewRegister();
    FeedbackSlot slot = feedback_spec()->AddDefineKeyedOwnICSlot();
    builder()
        ->StoreAccumulatorInRegister(brand_reg)
        .LoadAccumulatorWithRegister(class_context->reg())
        .DefineKeyedOwnProperty(receiver, brand_reg,
                                DefineKeyedOwnPropertyFlag::kNoFlags,
                                feedback_index(slot));
  } else {
    // We are in the slow case where super() is called from a nested
    // arrow function or an eval(), so the class scope context isn't
    // tracked in a context register in the stack, and we have to
    // walk the context chain from the runtime to find it.
    DCHECK_NE(info()->literal()->scope()->outer_scope(), brand->scope());
    RegisterList brand_args = register_allocator()->NewRegisterList(4);
    builder()
        ->StoreAccumulatorInRegister(brand_args[1])
        .MoveRegister(receiver, brand_args[0])
        .MoveRegister(execution_context()->reg(), brand_args[2])
        .LoadLiteral(Smi::FromInt(depth))
        .StoreAccumulatorInRegister(brand_args[3])
        .CallRuntime(Runtime::kAddPrivateBrand, brand_args);
  }
}
References v8::internal::FeedbackVectorSpec::AddDefineKeyedOwnICSlot(), builder(), BuildVariableLoad(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextChainDepth(), DCHECK_NE, v8::internal::interpreter::BytecodeArrayBuilder::DefineKeyedOwnProperty(), execution_context(), feedback_index(), feedback_spec(), v8::internal::Smi::FromInt(), info(), v8::internal::kElided, v8::internal::kNoFlags, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::interpreter::BytecodeGenerator::ContextScope::Previous(), v8::internal::interpreter::BytecodeGenerator::ContextScope::reg(), register_allocator(), v8::internal::UnoptimizedCompilationInfo::scope(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildInstanceInitializationAfterSuperCall(), and GenerateBaseConstructorBody().
BuildPrivateDebugDynamicGet()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicGet (Property * property, Register obj) [private]
Definition at line 6244 of file bytecode-generator.cc.
                                                                  {
  RegisterAllocationScope scope(this);
  RegisterList args = register_allocator()->NewRegisterList(2);
  Variable* private_name = property->key()->AsVariableProxy()->var();
  builder()
      ->MoveRegister(obj, args[0])
      .LoadLiteral(private_name->raw_name())
      .StoreAccumulatorInRegister(args[1])
      .CallRuntime(Runtime::kGetPrivateMember, args);
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::Property::key(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by VisitPropertyLoad().
BuildPrivateDebugDynamicSet()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateDebugDynamicSet (Property * property, Register obj, Register value) [private]
Definition at line 6257 of file bytecode-generator.cc.
                                                                    {
  RegisterAllocationScope scope(this);
  RegisterList args = register_allocator()->NewRegisterList(3);
  Variable* private_name = property->key()->AsVariableProxy()->var();
  builder()
      ->MoveRegister(obj, args[0])
      .LoadLiteral(private_name->raw_name())
      .StoreAccumulatorInRegister(args[1])
      .MoveRegister(value, args[2])
      .CallRuntime(Runtime::kSetPrivateMember, args);
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::Property::key(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::value.
Referenced by BuildAssignment().
BuildPrivateGetterAccess()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateGetterAccess (Register obj, Register access_pair) [private]
Definition at line 6272 of file bytecode-generator.cc.
                                                                         {
  RegisterAllocationScope scope(this);
  Register accessor = register_allocator()->NewRegister();
  RegisterList args = register_allocator()->NewRegisterList(1);
  builder()
      ->CallRuntime(Runtime::kLoadPrivateGetter, accessor_pair)
      .StoreAccumulatorInRegister(accessor)
      .MoveRegister(object, args[0])
      .CallProperty(accessor, args,
                    feedback_index(feedback_spec()->AddCallICSlot()));
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by VisitPropertyLoad().
BuildPrivateMethodIn()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn (Variable * private_name, Expression * object_expression) [private]
Definition at line 6302 of file bytecode-generator.cc.
                                                                            {
  DCHECK(IsPrivateMethodOrAccessorVariableMode(private_name->mode()));
  ClassScope* scope = private_name->scope()->AsClassScope();
  if (private_name->is_static()) {
    // For static private methods, "#privatemethod in ..." only returns true for
    // the class constructor.
    if (scope->class_variable() == nullptr) {
      // Can only happen via the debugger. See comment in
      // BuildPrivateBrandCheck.
      RegisterAllocationScope register_scope(this);
      RegisterList args = register_allocator()->NewRegisterList(2);
      builder()
          ->LoadLiteral(Smi::FromEnum(
              MessageTemplate::
                  kInvalidUnusedPrivateStaticMethodAccessedByDebugger))
          .StoreAccumulatorInRegister(args[0])
          .LoadLiteral(private_name->raw_name())
          .StoreAccumulatorInRegister(args[1])
          .CallRuntime(Runtime::kNewError, args)
          .Throw();
    } else {
      VisitForAccumulatorValue(object_expression);
      Register object = register_allocator()->NewRegister();
      builder()->StoreAccumulatorInRegister(object);
      BytecodeLabel is_object;
      builder()->JumpIfJSReceiver(&is_object);
      RegisterList args = register_allocator()->NewRegisterList(3);
      builder()
          ->StoreAccumulatorInRegister(args[2])
          .LoadLiteral(Smi::FromEnum(MessageTemplate::kInvalidInOperatorUse))
          .StoreAccumulatorInRegister(args[0])
          .LoadLiteral(private_name->raw_name())
          .StoreAccumulatorInRegister(args[1])
          .CallRuntime(Runtime::kNewTypeError, args)
          .Throw();
      builder()->Bind(&is_object);
      BuildVariableLoadForAccumulatorValue(scope->class_variable(),
                                           HoleCheckMode::kElided);
      builder()->CompareReference(object);
    }
  } else {
    BuildVariableLoadForAccumulatorValue(scope->brand(),
                                         HoleCheckMode::kElided);
    Register brand = register_allocator()->NewRegister();
    builder()->StoreAccumulatorInRegister(brand);
    VisitForAccumulatorValue(object_expression);
    builder()->SetExpressionPosition(object_expression);
    FeedbackSlot slot = feedback_spec()->AddKeyedHasICSlot();
    builder()->CompareOperation(Token::kIn, brand, feedback_index(slot));
    execution_result()->SetResultIsBoolean();
  }
}
References v8::internal::FeedbackVectorSpec::AddKeyedHasICSlot(), v8::base::args, v8::internal::Scope::AsClassScope(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::ClassScope::brand(), builder(), BuildVariableLoadForAccumulatorValue(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::ClassScope::class_variable(), v8::internal::interpreter::BytecodeArrayBuilder::CompareOperation(), v8::internal::interpreter::BytecodeArrayBuilder::CompareReference(), v8::internal::DCHECK(), execution_result(), feedback_index(), feedback_spec(), v8::internal::Smi::FromEnum(), v8::internal::IsPrivateMethodOrAccessorVariableMode(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfJSReceiver(), v8::internal::kElided, v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsBoolean(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::Throw(), and VisitForAccumulatorValue().
BuildPrivateMethods()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethods (ClassLiteral * expr, bool is_static, Register home_object) [private]
BuildPrivateSetterAccess()
void v8::internal::interpreter::BytecodeGenerator::BuildPrivateSetterAccess (Register obj, Register access_pair, Register value) [private]
Definition at line 6286 of file bytecode-generator.cc.
                                                                 {
  RegisterAllocationScope scope(this);
  Register accessor = register_allocator()->NewRegister();
  RegisterList args = register_allocator()->NewRegisterList(2);
  builder()
      ->CallRuntime(Runtime::kLoadPrivateSetter, accessor_pair)
      .StoreAccumulatorInRegister(accessor)
      .MoveRegister(object, args[0])
      .MoveRegister(value, args[1])
      .CallProperty(accessor, args,
                    feedback_index(feedback_spec()->AddCallICSlot()));
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::value.
Referenced by BuildAssignment().
BuildPushUndefinedIntoRegisterList()
void v8::internal::interpreter::BytecodeGenerator::BuildPushUndefinedIntoRegisterList (RegisterList * reg_list) [private]
Definition at line 8417 of file bytecode-generator.cc.
                            {
  Register reg = register_allocator()->GrowRegisterList(reg_list);
  builder()->LoadUndefined().StoreAccumulatorInRegister(reg);
}
References builder(), v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList(), v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
BuildReThrow()
void v8::internal::interpreter::BytecodeGenerator::BuildReThrow () [private]
Definition at line 4658 of file bytecode-generator.cc.
{ builder()->ReThrow(); }
References builder(), and v8::internal::interpreter::BytecodeArrayBuilder::ReThrow().
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel::Execute(), and v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryCatch::Execute().
BuildReturn()
void v8::internal::interpreter::BytecodeGenerator::BuildReturn (int source_position) [private]
Definition at line 4622 of file bytecode-generator.cc.
                                                       {
  if (v8_flags.trace) {
    RegisterAllocationScope register_scope(this);
    Register result = register_allocator()->NewRegister();
    // Runtime returns {result} value, preserving accumulator.
    builder()->StoreAccumulatorInRegister(result).CallRuntime(
        Runtime::kTraceExit, result);
  }
  builder()->SetStatementPosition(source_position);
  builder()->Return();
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::base::internal::result, v8::internal::interpreter::BytecodeArrayBuilder::Return(), v8::internal::interpreter::BytecodeArrayBuilder::SetStatementPosition(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::v8_flags.
Referenced by BuildAsyncReturn(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel::Execute(), GenerateAsyncFunctionBody(), and GenerateDerivedConstructorBody().
BuildSetNamedProperty()
void v8::internal::interpreter::BytecodeGenerator::BuildSetNamedProperty (const Expression * object_expr, Register object, const AstRawString * name) [private]
Definition at line 4913 of file bytecode-generator.cc.
                                                                        {
  Register value;
  if (!execution_result()->IsEffect()) {
    value = register_allocator()->NewRegister();
    builder()->StoreAccumulatorInRegister(value);
  }
  FeedbackSlot slot = GetCachedStoreICSlot(object_expr, name);
  builder()->SetNamedProperty(object, name, feedback_index(slot),
                              language_mode());
  if (!execution_result()->IsEffect()) {
    builder()->LoadAccumulatorWithRegister(value);
  }
}
References builder(), execution_result(), feedback_index(), GetCachedStoreICSlot(), language_mode(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::name, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetNamedProperty(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::value.
Referenced by BuildAssignment().
BuildStoreGlobal()
void v8::internal::interpreter::BytecodeGenerator::BuildStoreGlobal (Variable * variable) [private]
Definition at line 4931 of file bytecode-generator.cc.
                                                           {
  Register value;
  if (!execution_result()->IsEffect()) {
    value = register_allocator()->NewRegister();
    builder()->StoreAccumulatorInRegister(value);
  }
  FeedbackSlot slot = GetCachedStoreGlobalICSlot(language_mode(), variable);
  builder()->StoreGlobal(variable->raw_name(), feedback_index(slot));
  if (!execution_result()->IsEffect()) {
    builder()->LoadAccumulatorWithRegister(value);
  }
}
References builder(), execution_result(), feedback_index(), GetCachedStoreGlobalICSlot(), language_mode(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::StoreGlobal(), and v8::internal::value.
Referenced by BuildVariableAssignment().
BuildSuperCallOptimization()
void v8::internal::interpreter::BytecodeGenerator::BuildSuperCallOptimization (Register this_function, Register new_target, Register constructor_then_instance, BytecodeLabel * super_ctor_call_done) [private]
Definition at line 6906 of file bytecode-generator.cc.
                                                                             {
  DCHECK(v8_flags.omit_default_ctors);
  RegisterList output = register_allocator()->NewRegisterList(2);
  builder()->FindNonDefaultConstructorOrConstruct(this_function, new_target,
                                                  output);
  builder()->MoveRegister(output[1], constructor_then_instance);
  builder()->LoadAccumulatorWithRegister(output[0]).JumpIfTrue(
      ToBooleanMode::kAlreadyBoolean, super_ctor_call_done);
}
References builder(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayBuilder::FindNonDefaultConstructorOrConstruct(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), and v8::internal::v8_flags.
Referenced by BuildGetAndCheckSuperConstructor().
BuildSuspendPoint()
void v8::internal::interpreter::BytecodeGenerator::BuildSuspendPoint (int position) [private]
Definition at line 5756 of file bytecode-generator.cc.
                                                      {
  // Because we eliminate jump targets in dead code, we also eliminate resumes
  // when the suspend is not emitted because otherwise the below call to Bind
  // would start a new basic block and the code would be considered alive.
  if (builder()->RemainderOfBlockIsDead()) {
    return;
  }
  const int suspend_id = suspend_count_++;
  RegisterList registers = register_allocator()->AllLiveRegisters();
  // Save context, registers, and state. This bytecode then returns the value
  // in the accumulator.
  builder()->SetExpressionPosition(position);
  builder()->SuspendGenerator(generator_object(), registers, suspend_id);
  // Upon resume, we continue here.
  builder()->Bind(generator_jump_table_, suspend_id);
  // Clobbers all registers and sets the accumulator to the
  // [[input_or_debug_pos]] slot of the generator object.
  builder()->ResumeGenerator(generator_object(), registers);
}
References v8::internal::interpreter::BytecodeRegisterAllocator::AllLiveRegisters(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), generator_jump_table_, generator_object(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::ResumeGenerator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), suspend_count_, and v8::internal::interpreter::BytecodeArrayBuilder::SuspendGenerator().
Referenced by BuildAwait().
BuildTest()
void v8::internal::interpreter::BytecodeGenerator::BuildTest (ToBooleanMode mode, BytecodeLabels * then_labels, BytecodeLabels * else_labels, TestFallthrough fallthrough) [private]
Definition at line 8546 of file bytecode-generator.cc.
                                                               {
  switch (fallthrough) {
    case TestFallthrough::kThen:
      builder()->JumpIfFalse(mode, else_labels->New());
      break;
    case TestFallthrough::kElse:
      builder()->JumpIfTrue(mode, then_labels->New());
      break;
    case TestFallthrough::kNone:
      builder()->JumpIfTrue(mode, then_labels->New());
      builder()->Jump(else_labels->New());
      break;
  }
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), kElse, kNone, kThen, mode(), and v8::internal::interpreter::BytecodeLabels::New().
Referenced by VisitForNullishTest(), VisitForTest(), and VisitInSameTestExecutionScope().
BuildThisVariableLoad()
void v8::internal::interpreter::BytecodeGenerator::BuildThisVariableLoad () [private]
Definition at line 7893 of file bytecode-generator.cc.
                                              {
  DeclarationScope* receiver_scope = closure_scope()->GetReceiverScope();
  Variable* var = receiver_scope->receiver();
  // TODO(littledan): implement 'this' hole check elimination.
  HoleCheckMode hole_check_mode =
      IsDerivedConstructor(receiver_scope->function_kind())
          ? HoleCheckMode::kRequired
          : HoleCheckMode::kElided;
  BuildVariableLoad(var, hole_check_mode);
}
References BuildVariableLoad(), closure_scope(), v8::internal::DeclarationScope::function_kind(), v8::internal::Scope::GetReceiverScope(), v8::internal::IsDerivedConstructor(), v8::internal::kElided, v8::internal::kRequired, and v8::internal::DeclarationScope::receiver().
Referenced by GenerateDerivedConstructorBody(), PrepareAssignmentLhs(), VisitKeyedSuperPropertyLoad(), and VisitNamedSuperPropertyLoad().
BuildThrowIfHole()
void v8::internal::interpreter::BytecodeGenerator::BuildThrowIfHole (Variable * variable) [private]
Definition at line 4684 of file bytecode-generator.cc.
                                                           {
  if (variable->is_this()) {
    DCHECK(variable->mode() == VariableMode::kConst);
    builder()->ThrowSuperNotCalledIfHole();
  } else {
    builder()->ThrowReferenceErrorIfHole(variable->raw_name());
  }
  RememberHoleCheckInCurrentBlock(variable);
}
References builder(), v8::internal::DCHECK(), v8::internal::kConst, RememberHoleCheckInCurrentBlock(), v8::internal::interpreter::BytecodeArrayBuilder::ThrowReferenceErrorIfHole(), and v8::internal::interpreter::BytecodeArrayBuilder::ThrowSuperNotCalledIfHole().
Referenced by BuildHoleCheckForVariableAssignment(), and BuildVariableLoad().
BuildTryCatch()
template<typename TryBodyFunc , typename CatchBodyFunc >
void v8::internal::interpreter::BytecodeGenerator::BuildTryCatch (TryBodyFunc try_body_func, CatchBodyFunc catch_body_func, HandlerTable::CatchPrediction catch_prediction, TryCatchStatement * stmt_for_coverage = nullptr) [private]
Definition at line 2727 of file bytecode-generator.cc.
                                          {
  if (builder()->RemainderOfBlockIsDead()) return;
  TryCatchBuilder try_control_builder(
      builder(),
      stmt_for_coverage == nullptr ? nullptr : block_coverage_builder_,
      stmt_for_coverage, catch_prediction);
  // Preserve the context in a dedicated register, so that it can be restored
  // when the handler is entered by the stack-unwinding machinery.
  // TODO(ignition): Be smarter about register allocation.
  Register context = register_allocator()->NewRegister();
  builder()->MoveRegister(Register::current_context(), context);
  // Evaluate the try-block inside a control scope. This simulates a handler
  // that is intercepting 'throw' control commands.
  try_control_builder.BeginTry(context);
  HoleCheckElisionMergeScope merge_elider(this);
  {
    ControlScopeForTryCatch scope(this, &try_control_builder);
    // The try-block itself, even though unconditionally executed, can throw
    // basically at any point, and so must be treated as conditional from the
    // perspective of the hole check elision analysis.
    //
    // try { x } catch (e) { }
    // use(x); <-- Still requires a TDZ check
    //
    // However, if both the try-block and the catch-block emit a hole check,
    // subsequent TDZ checks can be elided.
    //
    // try { x; } catch (e) { x; }
    // use(x); <-- TDZ check can be elided
    HoleCheckElisionMergeScope::Branch branch_elider(merge_elider);
    try_body_func();
  }
  try_control_builder.EndTry();
  {
    HoleCheckElisionMergeScope::Branch branch_elider(merge_elider);
    catch_body_func(context);
  }
  merge_elider.Merge();
  try_control_builder.EndCatch();
}
References v8::internal::interpreter::TryCatchBuilder::BeginTry(), block_coverage_builder_, builder(), catch_prediction(), v8::internal::interpreter::Register::current_context(), v8::internal::interpreter::TryCatchBuilder::EndCatch(), v8::internal::interpreter::TryCatchBuilder::EndTry(), v8::internal::interpreter::BytecodeGenerator::HoleCheckElisionMergeScope::Merge(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), and register_allocator().
Referenced by BuildDisposeScope(), BuildFinalizeIteration(), GenerateAsyncFunctionBody(), and GenerateAsyncGeneratorFunctionBody().
BuildTryFinally()
template<typename TryBodyFunc , typename FinallyBodyFunc >
void v8::internal::interpreter::BytecodeGenerator::BuildTryFinally (TryBodyFunc try_body_func, FinallyBodyFunc finally_body_func, HandlerTable::CatchPrediction catch_prediction, TryFinallyStatement * stmt_for_coverage = nullptr) [private]
Definition at line 2780 of file bytecode-generator.cc.
                                            {
  if (builder()->RemainderOfBlockIsDead()) return;
  // We can't know whether the finally block will override ("catch") an
  // exception thrown in the try block, so we just adopt the outer prediction.
  TryFinallyBuilder try_control_builder(
      builder(),
      stmt_for_coverage == nullptr ? nullptr : block_coverage_builder_,
      stmt_for_coverage, catch_prediction);
  // We keep a record of all paths that enter the finally-block to be able to
  // dispatch to the correct continuation point after the statements in the
  // finally-block have been evaluated.
  //
  // The try-finally construct can enter the finally-block in three ways:
  // 1. By exiting the try-block normally, falling through at the end.
  // 2. By exiting the try-block with a function-local control flow transfer
  // (i.e. through break/continue/return statements).
  // 3. By exiting the try-block with a thrown exception.
  //
  // The result register semantics depend on how the block was entered:
  // - ReturnStatement: It represents the return value being returned.
  // - ThrowStatement: It represents the exception being thrown.
  // - BreakStatement/ContinueStatement: Undefined and not used.
  // - Falling through into finally-block: Undefined and not used.
  Register token = register_allocator()->NewRegister();
  Register result = register_allocator()->NewRegister();
  Register message = register_allocator()->NewRegister();
  builder()->LoadTheHole().StoreAccumulatorInRegister(message);
  ControlScope::DeferredCommands commands(this, token, result, message);
  // Preserve the context in a dedicated register, so that it can be restored
  // when the handler is entered by the stack-unwinding machinery.
  // TODO(ignition): Be smarter about register allocation.
  Register context = register_allocator()->NewRegister();
  builder()->MoveRegister(Register::current_context(), context);
  // Evaluate the try-block inside a control scope. This simulates a handler
  // that is intercepting all control commands.
  try_control_builder.BeginTry(context);
  {
    ControlScopeForTryFinally scope(this, &try_control_builder, &commands);
    // The try-block itself, even though unconditionally executed, can throw
    // basically at any point, and so must be treated as conditional from the
    // perspective of the hole check elision analysis.
    HoleCheckElisionScope elider(this);
    try_body_func();
  }
  try_control_builder.EndTry();
  // Record fall-through and exception cases.
  if (!builder()->RemainderOfBlockIsDead()) {
    commands.RecordFallThroughPath();
  }
  try_control_builder.LeaveTry();
  try_control_builder.BeginHandler();
  commands.RecordHandlerReThrowPath();
  try_control_builder.BeginFinally();
  // Evaluate the finally-block.
  finally_body_func(token, result, message);
  try_control_builder.EndFinally();
  // Dynamic dispatch after the finally-block.
  commands.ApplyDeferredCommands();
}
References v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::ApplyDeferredCommands(), v8::internal::interpreter::TryFinallyBuilder::BeginFinally(), v8::internal::interpreter::TryFinallyBuilder::BeginHandler(), v8::internal::interpreter::TryFinallyBuilder::BeginTry(), block_coverage_builder_, builder(), catch_prediction(), v8::internal::interpreter::Register::current_context(), v8::internal::interpreter::TryFinallyBuilder::EndFinally(), v8::internal::interpreter::TryFinallyBuilder::EndTry(), v8::internal::interpreter::TryFinallyBuilder::LeaveTry(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTheHole(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordFallThroughPath(), v8::internal::interpreter::BytecodeGenerator::ControlScope::DeferredCommands::RecordHandlerReThrowPath(), register_allocator(), v8::base::internal::result, and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by BuildDestructuringArrayAssignment(), BuildDisposeScope(), and GenerateAsyncGeneratorFunctionBody().
BuildVariableAssignment()
void v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment (Variable * variable, Token::Value op, HoleCheckMode hole_check_mode, LookupHoistingMode lookup_hoisting_mode = LookupHoistingMode::kNormal) [private]
Definition at line 4745 of file bytecode-generator.cc.
                                             {
  VariableMode mode = variable->mode();
  RegisterAllocationScope assignment_register_scope(this);
  switch (variable->location()) {
    case VariableLocation::PARAMETER:
    case VariableLocation::LOCAL: {
      Register destination;
      if (VariableLocation::PARAMETER == variable->location()) {
        if (variable->IsReceiver()) {
          destination = builder()->Receiver();
        } else {
          destination = builder()->Parameter(variable->index());
        }
      } else {
        destination = builder()->Local(variable->index());
      }
      if (VariableNeedsHoleCheckInCurrentBlockForAssignment(variable, op,
                                                            hole_check_mode)) {
        // Load destination to check for hole.
        Register value_temp = register_allocator()->NewRegister();
        builder()
            ->StoreAccumulatorInRegister(value_temp)
            .LoadAccumulatorWithRegister(destination);
        BuildHoleCheckForVariableAssignment(variable, op);
        builder()->LoadAccumulatorWithRegister(value_temp);
      }
      if ((mode != VariableMode::kConst && mode != VariableMode::kUsing &&
           mode != VariableMode::kAwaitUsing) ||
          op == Token::kInit) {
        if (op == Token::kInit) {
          if (variable->HasHoleCheckUseInSameClosureScope()) {
            // After initializing a variable it won't be the hole anymore, so
            // elide subsequent checks.
            RememberHoleCheckInCurrentBlock(variable);
          }
          AddDisposableValue(mode);
        }
        builder()->StoreAccumulatorInRegister(destination);
      } else if (variable->throw_on_const_assignment(language_mode()) &&
                 mode == VariableMode::kConst) {
        builder()->CallRuntime(Runtime::kThrowConstAssignError);
      } else if (variable->throw_on_const_assignment(language_mode()) &&
                 mode == VariableMode::kUsing) {
        builder()->CallRuntime(Runtime::kThrowUsingAssignError);
      }
      break;
    }
    case VariableLocation::UNALLOCATED: {
      BuildStoreGlobal(variable);
      break;
    }
    case VariableLocation::CONTEXT: {
      int depth = execution_context()->ContextChainDepth(variable->scope());
      ContextScope* context = execution_context()->Previous(depth);
      Register context_reg;
      if (context) {
        context_reg = context->reg();
        depth = 0;
      } else {
        context_reg = execution_context()->reg();
      }
      if (VariableNeedsHoleCheckInCurrentBlockForAssignment(variable, op,
                                                            hole_check_mode)) {
        // Load destination to check for hole.
        Register value_temp = register_allocator()->NewRegister();
        builder()
            ->StoreAccumulatorInRegister(value_temp)
            .LoadContextSlot(context_reg, variable, depth,
                             BytecodeArrayBuilder::kMutableSlot);
        BuildHoleCheckForVariableAssignment(variable, op);
        builder()->LoadAccumulatorWithRegister(value_temp);
      }
      if ((mode != VariableMode::kConst && mode != VariableMode::kUsing &&
           mode != VariableMode::kAwaitUsing) ||
          op == Token::kInit) {
        if (op == Token::kInit) {
          if (variable->HasHoleCheckUseInSameClosureScope()) {
            // After initializing a variable it won't be the hole anymore, so
            // elide subsequent checks.
            RememberHoleCheckInCurrentBlock(variable);
          }
          AddDisposableValue(mode);
        }
        builder()->StoreContextSlot(context_reg, variable, depth);
      } else if (variable->throw_on_const_assignment(language_mode())) {
        builder()->CallRuntime(Runtime::kThrowConstAssignError);
      }
      break;
    }
    case VariableLocation::LOOKUP: {
      builder()->StoreLookupSlot(variable->raw_name(), language_mode(),
                                 lookup_hoisting_mode);
      break;
    }
    case VariableLocation::MODULE: {
      DCHECK(IsDeclaredVariableMode(mode));
      if (mode == VariableMode::kConst && op != Token::kInit) {
        builder()->CallRuntime(Runtime::kThrowConstAssignError);
        break;
      }
      // If we don't throw above, we know that we're dealing with an
      // export because imports are const and we do not generate initializing
      // assignments for them.
      DCHECK(variable->IsExport());
      int depth = execution_context()->ContextChainDepth(variable->scope());
      if (VariableNeedsHoleCheckInCurrentBlockForAssignment(variable, op,
                                                            hole_check_mode)) {
        Register value_temp = register_allocator()->NewRegister();
        builder()
            ->StoreAccumulatorInRegister(value_temp)
            .LoadModuleVariable(variable->index(), depth);
        BuildHoleCheckForVariableAssignment(variable, op);
        builder()->LoadAccumulatorWithRegister(value_temp);
      }
      builder()->StoreModuleVariable(variable->index(), depth);
      break;
    }
    case VariableLocation::REPL_GLOBAL: {
      // A let or const declaration like 'let x = 7' is effectively translated
      // to:
      // <top of the script>:
      // ScriptContext.x = TheHole;
      // ...
      // <where the actual 'let' is>:
      // ScriptContextTable.x = 7; // no hole check
      //
      // The ScriptContext slot for 'x' that we store to here is not
      // necessarily the ScriptContext of this script, but rather the
      // first ScriptContext that has a slot for name 'x'.
      DCHECK(variable->IsReplGlobal());
      if (op == Token::kInit) {
        RegisterList store_args = register_allocator()->NewRegisterList(2);
        builder()
            ->StoreAccumulatorInRegister(store_args[1])
            .LoadLiteral(variable->raw_name())
            .StoreAccumulatorInRegister(store_args[0]);
        builder()->CallRuntime(
            Runtime::kStoreGlobalNoHoleCheckForReplLetOrConst, store_args);
      } else {
        if (mode == VariableMode::kConst) {
          builder()->CallRuntime(Runtime::kThrowConstAssignError);
        } else {
          BuildStoreGlobal(variable);
        }
      }
      break;
    }
  }
}
References AddDisposableValue(), builder(), BuildHoleCheckForVariableAssignment(), BuildStoreGlobal(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::CONTEXT, v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextChainDepth(), v8::internal::DCHECK(), execution_context(), v8::internal::IsDeclaredVariableMode(), v8::internal::kAwaitUsing, v8::internal::kConst, v8::internal::interpreter::BytecodeArrayBuilder::kMutableSlot, v8::internal::kUsing, language_mode(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadContextSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadModuleVariable(), v8::internal::LOCAL, v8::internal::interpreter::BytecodeArrayBuilder::Local(), v8::internal::LOOKUP, mode(), v8::internal::MODULE, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::PARAMETER, v8::internal::interpreter::BytecodeArrayBuilder::Parameter(), v8::internal::interpreter::BytecodeGenerator::ContextScope::Previous(), v8::internal::interpreter::BytecodeArrayBuilder::Receiver(), v8::internal::interpreter::BytecodeGenerator::ContextScope::reg(), register_allocator(), RememberHoleCheckInCurrentBlock(), v8::internal::REPL_GLOBAL, v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::interpreter::BytecodeArrayBuilder::StoreContextSlot(), v8::internal::interpreter::BytecodeArrayBuilder::StoreLookupSlot(), v8::internal::interpreter::BytecodeArrayBuilder::StoreModuleVariable(), v8::internal::UNALLOCATED, and VariableNeedsHoleCheckInCurrentBlockForAssignment().
Referenced by BuildAssignment(), BuildClassLiteral(), BuildGeneratorObjectVariableInitialization(), BuildInstanceInitializationAfterSuperCall(), VisitArgumentsObject(), VisitModuleNamespaceImports(), VisitNewTargetVariable(), VisitRestArgumentsArray(), and VisitThisFunctionVariable().
BuildVariableLoad()
void v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad (Variable * variable, HoleCheckMode hole_check_mode, TypeofMode typeof_mode = TypeofMode::kNotInside) [private]
Definition at line 4483 of file bytecode-generator.cc.
                                                                  {
  switch (variable->location()) {
    case VariableLocation::LOCAL: {
      Register source(builder()->Local(variable->index()));
      // We need to load the variable into the accumulator, even when in a
      // VisitForRegisterScope, in order to avoid register aliasing if
      // subsequent expressions assign to the same variable.
      builder()->LoadAccumulatorWithRegister(source);
      if (VariableNeedsHoleCheckInCurrentBlock(variable, hole_check_mode)) {
        BuildThrowIfHole(variable);
      }
      break;
    }
    case VariableLocation::PARAMETER: {
      Register source;
      if (variable->IsReceiver()) {
        source = builder()->Receiver();
      } else {
        source = builder()->Parameter(variable->index());
      }
      // We need to load the variable into the accumulator, even when in a
      // VisitForRegisterScope, in order to avoid register aliasing if
      // subsequent expressions assign to the same variable.
      builder()->LoadAccumulatorWithRegister(source);
      if (VariableNeedsHoleCheckInCurrentBlock(variable, hole_check_mode)) {
        BuildThrowIfHole(variable);
      }
      break;
    }
    case VariableLocation::UNALLOCATED: {
      // The global identifier "undefined" is immutable. Everything
      // else could be reassigned. For performance, we do a pointer comparison
      // rather than checking if the raw_name is really "undefined".
      if (variable->raw_name() == ast_string_constants()->undefined_string()) {
        builder()->LoadUndefined();
      } else {
        FeedbackSlot slot = GetCachedLoadGlobalICSlot(typeof_mode, variable);
        builder()->LoadGlobal(variable->raw_name(), feedback_index(slot),
                              typeof_mode);
      }
      break;
    }
    case VariableLocation::CONTEXT: {
      int depth = execution_context()->ContextChainDepth(variable->scope());
      ContextScope* context = execution_context()->Previous(depth);
      Register context_reg;
      if (context) {
        context_reg = context->reg();
        depth = 0;
      } else {
        context_reg = execution_context()->reg();
      }
      BytecodeArrayBuilder::ContextSlotMutability immutable =
          (variable->maybe_assigned() == kNotAssigned)
              ? BytecodeArrayBuilder::kImmutableSlot
              : BytecodeArrayBuilder::kMutableSlot;
      Register acc = Register::virtual_accumulator();
      if (immutable == BytecodeArrayBuilder::kImmutableSlot &&
          IsVariableInRegister(variable, acc)) {
        return;
      }
      builder()->LoadContextSlot(context_reg, variable, depth, immutable);
      if (VariableNeedsHoleCheckInCurrentBlock(variable, hole_check_mode)) {
        BuildThrowIfHole(variable);
      }
      if (immutable == BytecodeArrayBuilder::kImmutableSlot) {
        SetVariableInRegister(variable, acc);
      }
      break;
    }
    case VariableLocation::LOOKUP: {
      switch (variable->mode()) {
        case VariableMode::kDynamicLocal: {
          Variable* local_variable = variable->local_if_not_shadowed();
          int depth =
              execution_context()->ContextChainDepth(local_variable->scope());
          ContextMode context_mode =
              (local_variable->scope()->has_context_cells()
                   ? ContextMode::kHasContextCells
                   : ContextMode::kNoContextCells);
          builder()->LoadLookupContextSlot(variable->raw_name(), typeof_mode,
                                           context_mode,
                                           local_variable->index(), depth);
          if (VariableNeedsHoleCheckInCurrentBlock(local_variable,
                                                   hole_check_mode)) {
            BuildThrowIfHole(local_variable);
          }
          break;
        }
        case VariableMode::kDynamicGlobal: {
          int depth =
              current_scope()->ContextChainLengthUntilOutermostSloppyEval();
          // TODO(1008414): Add back caching here when bug is fixed properly.
          FeedbackSlot slot = feedback_spec()->AddLoadGlobalICSlot(typeof_mode);
          builder()->LoadLookupGlobalSlot(variable->raw_name(), typeof_mode,
                                          feedback_index(slot), depth);
          break;
        }
        default: {
          // Normally, private names should not be looked up dynamically,
          // but we make an exception in debug-evaluate, in that case the
          // lookup will be done in %SetPrivateMember() and %GetPrivateMember()
          // calls, not here.
          DCHECK(!variable->raw_name()->IsPrivateName());
          builder()->LoadLookupSlot(variable->raw_name(), typeof_mode);
          break;
        }
      }
      break;
    }
    case VariableLocation::MODULE: {
      int depth = execution_context()->ContextChainDepth(variable->scope());
      builder()->LoadModuleVariable(variable->index(), depth);
      if (VariableNeedsHoleCheckInCurrentBlock(variable, hole_check_mode)) {
        BuildThrowIfHole(variable);
      }
      break;
    }
    case VariableLocation::REPL_GLOBAL: {
      DCHECK(variable->IsReplGlobal());
      FeedbackSlot slot = GetCachedLoadGlobalICSlot(typeof_mode, variable);
      builder()->LoadGlobal(variable->raw_name(), feedback_index(slot),
                            typeof_mode);
      break;
    }
  }
}
References v8::internal::FeedbackVectorSpec::AddLoadGlobalICSlot(), ast_string_constants(), builder(), BuildThrowIfHole(), v8::internal::CONTEXT, v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextChainDepth(), v8::internal::Scope::ContextChainLengthUntilOutermostSloppyEval(), current_scope(), v8::internal::DCHECK(), execution_context(), feedback_index(), feedback_spec(), GetCachedLoadGlobalICSlot(), IsVariableInRegister(), v8::internal::kDynamicGlobal, v8::internal::kDynamicLocal, v8::internal::kHasContextCells, v8::internal::interpreter::BytecodeArrayBuilder::kImmutableSlot, v8::internal::interpreter::BytecodeArrayBuilder::kMutableSlot, v8::internal::kNoContextCells, v8::internal::kNotAssigned, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeArrayBuilder::LoadContextSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadGlobal(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLookupContextSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLookupGlobalSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLookupSlot(), v8::internal::interpreter::BytecodeArrayBuilder::LoadModuleVariable(), v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined(), v8::internal::LOCAL, v8::internal::LOOKUP, v8::internal::MODULE, v8::internal::PARAMETER, v8::internal::interpreter::BytecodeArrayBuilder::Parameter(), v8::internal::interpreter::BytecodeGenerator::ContextScope::Previous(), v8::internal::interpreter::BytecodeArrayBuilder::Receiver(), v8::internal::interpreter::BytecodeGenerator::ContextScope::reg(), v8::internal::REPL_GLOBAL, SetVariableInRegister(), v8::internal::UNALLOCATED, VariableNeedsHoleCheckInCurrentBlock(), and v8::internal::interpreter::Register::virtual_accumulator().
Referenced by BuildClassProperty(), BuildPrivateBrandInitialization(), BuildThisVariableLoad(), BuildVariableLoadForAccumulatorValue(), PrepareAssignmentLhs(), VisitKeyedSuperPropertyLoad(), and VisitNamedSuperPropertyLoad().
BuildVariableLoadForAccumulatorValue()
void v8::internal::interpreter::BytecodeGenerator::BuildVariableLoadForAccumulatorValue (Variable * variable, HoleCheckMode hole_check_mode, TypeofMode typeof_mode = TypeofMode::kNotInside) [private]
Definition at line 4616 of file bytecode-generator.cc.
                                                                               {
  ValueResultScope accumulator_result(this);
  BuildVariableLoad(variable, hole_check_mode, typeof_mode);
}
References BuildVariableLoad().
Referenced by BuildPrivateBrandCheck(), BuildPrivateMethodIn(), and VisitForTypeOfValue().
catch_prediction()
HandlerTable::CatchPrediction v8::internal::interpreter::BytecodeGenerator::catch_prediction () const [inline], [private]
Definition at line 576 of file bytecode-generator.h.
                                                              {
    return catch_prediction_;
  }
References catch_prediction_.
Referenced by BuildAwait(), BuildDisposeScope(), BuildFinalizeIteration(), BuildTryCatch(), BuildTryFinally(), GenerateAsyncFunctionBody(), and GenerateAsyncGeneratorFunctionBody().
closure_scope()
DeclarationScope* v8::internal::interpreter::BytecodeGenerator::closure_scope () const [inline], [private]
Definition at line 538 of file bytecode-generator.h.
{ return closure_scope_; }
References closure_scope_.
Referenced by AllocateTopLevelRegisters(), BuildGeneratorObjectVariableInitialization(), BuildInstanceInitializationAfterSuperCall(), BuildLocalActivationContextInitialization(), BuildNewLocalActivationContext(), BuildThisVariableLoad(), BytecodeGenerator(), GenerateBodyPrologue(), GenerateBodyStatementsWithoutImplicitFinalReturn(), GenerateBytecode(), VisitArgumentsObject(), and VisitModuleNamespaceImports().
current_disposables_stack()
Register v8::internal::interpreter::BytecodeGenerator::current_disposables_stack () const [inline], [private]
Definition at line 595 of file bytecode-generator.h.
                                             {
    SBXCHECK(current_disposables_stack_.is_valid());
    return current_disposables_stack_;
  }
References current_disposables_stack_, v8::internal::interpreter::Register::is_valid(), and SBXCHECK.
Referenced by AddDisposableValue(), and BuildDisposeScope().
current_for_in_scope()
ForInScope* v8::internal::interpreter::BytecodeGenerator::current_for_in_scope () const [inline], [private]
Definition at line 588 of file bytecode-generator.h.
                                                  {
    return current_for_in_scope_;
  }
References current_for_in_scope_.
Referenced by BuildLoadKeyedProperty().
current_loop_scope()
LoopScope* v8::internal::interpreter::BytecodeGenerator::current_loop_scope () const [inline], [private]
Definition at line 583 of file bytecode-generator.h.
{ return current_loop_scope_; }
References current_loop_scope_.
current_scope()
Scope* v8::internal::interpreter::BytecodeGenerator::current_scope () const [inline], [private]
Definition at line 544 of file bytecode-generator.h.
{ return current_scope_; }
References current_scope_.
Referenced by BuildNewLocalActivationContext(), BuildVariableLoad(), language_mode(), and VisitInScope().
DEFINE_AST_VISITOR_SUBCLASS_MEMBERS()
v8::internal::interpreter::BytecodeGenerator::DEFINE_AST_VISITOR_SUBCLASS_MEMBERS () [private]
execution_context()
ContextScope* v8::internal::interpreter::BytecodeGenerator::execution_context () const [inline], [private]
Definition at line 551 of file bytecode-generator.h.
{ return execution_context_; }
References execution_context_.
Referenced by BuildLocalActivationContextInitialization(), BuildPrivateBrandInitialization(), BuildVariableAssignment(), BuildVariableLoad(), and v8::internal::interpreter::BytecodeGenerator::ControlScope::PopContextToExpectedDepth().
execution_control()
ControlScope* v8::internal::interpreter::BytecodeGenerator::execution_control () const [inline], [private]
Definition at line 547 of file bytecode-generator.h.
{ return execution_control_; }
References execution_control_.
Referenced by GenerateAsyncGeneratorFunctionBody(), GenerateBodyStatements(), VisitBlockDeclarationsAndStatements(), and VisitIterationBody().
execution_result()
ExpressionResultScope* v8::internal::interpreter::BytecodeGenerator::execution_result () const [inline], [private]
Definition at line 558 of file bytecode-generator.h.
{ return execution_result_; }
References execution_result_.
Referenced by BuildAssignment(), BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), BuildLiteralCompareNil(), BuildPrivateMethodIn(), BuildSetNamedProperty(), BuildStoreGlobal(), set_execution_result(), VisitArithmeticExpression(), VisitInSameTestExecutionScope(), VisitLogicalAndExpression(), VisitLogicalOrExpression(), VisitLogicalTest(), VisitNaryArithmeticExpression(), VisitNaryLogicalAndExpression(), VisitNaryLogicalOrExpression(), VisitNaryLogicalTest(), VisitNaryNullishExpression(), VisitNot(), VisitNullishExpression(), and VisitTypeOf().
feedback_index()
int v8::internal::interpreter::BytecodeGenerator::feedback_index (FeedbackSlot slot) const [inline], [private]
Definition at line 8685 of file bytecode-generator.cc.
                                                             {
  DCHECK(!slot.IsInvalid());
  return FeedbackVector::GetIndex(slot);
}
References v8::internal::DCHECK(), v8::internal::FeedbackVector::GetIndex(), and v8::internal::FeedbackSlot::IsInvalid().
Referenced by BuildAssignment(), BuildCallIteratorMethod(), BuildClassLiteral(), BuildClassProperty(), BuildCreateArrayLiteral(), BuildCreateObjectLiteral(), BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), BuildFillArrayWithIterator(), BuildFinalizeIteration(), BuildGetIterator(), BuildGetIteratorRecord(), BuildInstanceMemberInitialization(), BuildIteratorNext(), BuildLoadKeyedProperty(), BuildLoadNamedProperty(), BuildPrivateBrandCheck(), BuildPrivateBrandInitialization(), BuildPrivateGetterAccess(), BuildPrivateMethodIn(), BuildPrivateSetterAccess(), BuildSetNamedProperty(), BuildStoreGlobal(), BuildVariableLoad(), GetCachedLoadGlobalICSlot(), GetCachedLoadICSlot(), GetCachedLoadSuperICSlot(), GetCachedStoreGlobalICSlot(), GetCachedStoreICSlot(), VisitArithmeticExpression(), VisitCallSuper(), VisitNamedSuperPropertyLoad(), VisitNaryArithmeticExpression(), and VisitTypeOf().
feedback_slot_cache()
FeedbackSlotCache* v8::internal::interpreter::BytecodeGenerator::feedback_slot_cache () [inline], [private]
Definition at line 572 of file bytecode-generator.h.
                                                  {
    return feedback_slot_cache_;
  }
References feedback_slot_cache_.
Referenced by GetCachedCreateClosureSlot(), GetCachedLoadGlobalICSlot(), GetCachedLoadICSlot(), GetCachedLoadSuperICSlot(), GetCachedStoreGlobalICSlot(), and GetCachedStoreICSlot().
feedback_spec()
FeedbackVectorSpec * v8::internal::interpreter::BytecodeGenerator::feedback_spec () [inline], [private]
Definition at line 8681 of file bytecode-generator.cc.
                                                     {
  return info()->feedback_vector_spec();
}
References v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec(), and info().
Referenced by BuildAssignment(), BuildCallIteratorMethod(), BuildClassLiteral(), BuildClassProperty(), BuildCreateArrayLiteral(), BuildCreateObjectLiteral(), BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), BuildDisposeScope(), BuildFillArrayWithIterator(), BuildFinalizeIteration(), BuildGetIterator(), BuildGetIteratorRecord(), BuildInstanceMemberInitialization(), BuildIteratorNext(), BuildPrivateBrandCheck(), BuildPrivateBrandInitialization(), BuildPrivateGetterAccess(), BuildPrivateMethodIn(), BuildPrivateSetterAccess(), BuildVariableLoad(), GetCachedCreateClosureSlot(), GetCachedLoadGlobalICSlot(), GetCachedLoadICSlot(), GetCachedLoadSuperICSlot(), GetCachedStoreGlobalICSlot(), GetCachedStoreICSlot(), VisitArithmeticExpression(), VisitCallSuper(), VisitNaryArithmeticExpression(), VisitPropertyLoad(), and VisitTypeOf().
FinalizeBytecode()
template<typename IsolateT >
template Handle< BytecodeArray > v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode (IsolateT * isolate, Handle< Script > script)
Definition at line 1479 of file bytecode-generator.cc.
                                              {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
#ifdef DEBUG
  // Unoptimized compilation should be context-independent. Verify that we don't
  // access the native context by nulling it out during finalization.
  NullContextScopeFor<IsolateT> null_context_scope(isolate);
#endif
  AllocateDeferredConstants(isolate, script);
  if (block_coverage_builder_) {
    Handle<CoverageInfo> coverage_info =
        isolate->factory()->NewCoverageInfo(block_coverage_builder_->slots());
    info()->set_coverage_info(coverage_info);
    if (v8_flags.trace_block_coverage) {
      StdoutStream os;
      coverage_info->CoverageInfoPrint(os, info()->literal()->GetDebugName());
    }
  }
  if (HasStackOverflow()) return Handle<BytecodeArray>();
  Handle<BytecodeArray> bytecode_array = builder()->ToBytecodeArray(isolate);
  if (incoming_new_target_or_generator_.is_valid()) {
    bytecode_array->set_incoming_new_target_or_generator_register(
        incoming_new_target_or_generator_);
  }
  return bytecode_array;
}
References AllocateDeferredConstants(), block_coverage_builder_, builder(), v8::internal::ThreadId::Current(), DCHECK_EQ, v8::internal::compiler::GetDebugName(), incoming_new_target_or_generator_, info(), v8::internal::interpreter::Register::is_valid(), v8::internal::script, v8::internal::UnoptimizedCompilationInfo::set_coverage_info(), v8::internal::interpreter::BlockCoverageBuilder::slots(), v8::internal::interpreter::BytecodeArrayBuilder::ToBytecodeArray(), and v8::internal::v8_flags.
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl().
FinalizeSourcePositionTable()
template<typename IsolateT >
template DirectHandle< TrustedByteArray > v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable (IsolateT * isolate)
Definition at line 1517 of file bytecode-generator.cc.
                       {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
#ifdef DEBUG
  // Unoptimized compilation should be context-independent. Verify that we don't
  // access the native context by nulling it out during finalization.
  NullContextScopeFor<IsolateT> null_context_scope(isolate);
#endif
  DirectHandle<TrustedByteArray> source_position_table =
      builder()->ToSourcePositionTable(isolate);
  LOG_CODE_EVENT(isolate,
                 CodeLinePosInfoRecordEvent(
                     info_->bytecode_array()->GetFirstBytecodeAddress(),
                     *source_position_table, JitCodeEvent::BYTE_CODE));
  return source_position_table;
}
References builder(), v8::JitCodeEvent::BYTE_CODE, v8::internal::UnoptimizedCompilationInfo::bytecode_array(), v8::internal::ThreadId::Current(), DCHECK_EQ, info_, LOG_CODE_EVENT, and v8::internal::interpreter::BytecodeArrayBuilder::ToSourcePositionTable().
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl().
function_kind()
FunctionKind v8::internal::interpreter::BytecodeGenerator::function_kind () const [inline], [private]
Definition at line 8661 of file bytecode-generator.cc.
                                                    {
  return info()->literal()->kind();
}
References info(), v8::internal::FunctionLiteral::kind(), and v8::internal::UnoptimizedCompilationInfo::literal().
Referenced by BuildAwait(), GenerateAsyncFunctionBody(), GenerateAsyncGeneratorFunctionBody(), GenerateBaseConstructorBody(), GenerateBodyStatements(), GenerateBytecodeBody(), and GenerateDerivedConstructorBody().
GenerateAsyncFunctionBody()
void v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody () [private]
Definition at line 1853 of file bytecode-generator.cc.
                                                  {
  DCHECK((IsAsyncFunction(function_kind()) &&
          !IsAsyncGeneratorFunction(function_kind())) ||
         IsModuleWithTopLevelAwait(function_kind()));
  // Async functions always return promises. Return values fulfill that promise,
  // while synchronously thrown exceptions reject that promise. This is handled
  // by surrounding the body statements in a try-catch block as follows:
  //
  // try {
  // <inner_block>
  // } catch (.catch) {
  // return %_AsyncFunctionReject(.generator_object, .catch);
  // }
  FunctionLiteral* literal = info()->literal();
  BuildGeneratorObjectVariableInitialization();
  HandlerTable::CatchPrediction outer_catch_prediction = catch_prediction();
  // When compiling a REPL script, use UNCAUGHT_ASYNC_AWAIT to preserve the
  // pending message so DevTools can inspect it.
  set_catch_prediction(literal->scope()->is_repl_mode_scope()
                           ? HandlerTable::UNCAUGHT_ASYNC_AWAIT
                           : HandlerTable::ASYNC_AWAIT);
  BuildTryCatch(
      [&]() {
        GenerateBodyStatements();
        set_catch_prediction(outer_catch_prediction);
      },
      [&](Register context) {
        RegisterList args = register_allocator()->NewRegisterList(2);
        builder()
            ->MoveRegister(generator_object(), args[0])
            .StoreAccumulatorInRegister(args[1]); // exception
        if (!literal->scope()->is_repl_mode_scope()) {
          builder()->LoadTheHole().SetPendingMessage();
        }
        builder()->CallRuntime(Runtime::kInlineAsyncFunctionReject, args);
        // TODO(358404372): Should this return have a statement position?
        // Without one it is not possible to apply a debugger breakpoint.
        BuildReturn(kNoSourcePosition);
      },
      catch_prediction());
}
References v8::base::args, v8::internal::HandlerTable::ASYNC_AWAIT, builder(), BuildGeneratorObjectVariableInitialization(), BuildReturn(), BuildTryCatch(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), catch_prediction(), v8::internal::DCHECK(), function_kind(), GenerateBodyStatements(), generator_object(), info(), v8::internal::Scope::is_repl_mode_scope(), v8::internal::IsAsyncFunction(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::IsModuleWithTopLevelAwait(), v8::internal::kNoSourcePosition, v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTheHole(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::FunctionLiteral::scope(), set_catch_prediction(), v8::internal::interpreter::BytecodeArrayBuilder::SetPendingMessage(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::HandlerTable::UNCAUGHT_ASYNC_AWAIT.
Referenced by GenerateBytecodeBody().
GenerateAsyncGeneratorFunctionBody()
void v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody () [private]
Definition at line 1912 of file bytecode-generator.cc.
                                                           {
  DCHECK(IsAsyncGeneratorFunction(function_kind()));
  set_catch_prediction(HandlerTable::ASYNC_AWAIT);
  // For ES2017 Async Generators, we produce:
  //
  // try {
  // InitialYield;
  // ...body...;
  // } catch (.catch) {
  // %AsyncGeneratorReject(generator, .catch);
  // } finally {
  // %_GeneratorClose(generator);
  // }
  //
  // - InitialYield yields the actual generator object.
  // - Any return statement inside the body will have its argument wrapped
  // in an iterator result object with a "done" property set to `true`.
  // - If the generator terminates for whatever reason, we must close it.
  // Hence the finally clause.
  // - BytecodeGenerator performs special handling for ReturnStatements in
  // async generator functions, resolving the appropriate Promise with an
  // "done" iterator result object containing a Promise-unwrapped value.
  // In async generator functions, when parameters are not simple,
  // a parameter initialization block will be added as the first block to the
  // AST. Since this block can throw synchronously, it should not be wrapped
  // in the following try-finally. We visit this block outside the try-finally
  // and remove it from the AST.
  int start = 0;
  if (BuildInitializationBlockForParametersIfExist()) {
    start = 1;
  }
  BuildGeneratorObjectVariableInitialization();
  BuildTryFinally(
      [&]() {
        BuildTryCatch(
            [&]() { GenerateBodyStatements(start); },
            [&](Register context) {
              RegisterAllocationScope register_scope(this);
              RegisterList args = register_allocator()->NewRegisterList(2);
              builder()
                  ->MoveRegister(generator_object(), args[0])
                  .StoreAccumulatorInRegister(args[1]) // exception
                  .LoadTheHole()
                  .SetPendingMessage()
                  .CallRuntime(Runtime::kInlineAsyncGeneratorReject, args);
              execution_control()->ReturnAccumulator(kNoSourcePosition);
            },
            catch_prediction());
      },
      [&](Register body_continuation_token, Register body_continuation_result,
          Register message) {
        RegisterAllocationScope register_scope(this);
        Register arg = register_allocator()->NewRegister();
        builder()
            ->MoveRegister(generator_object(), arg)
            .CallRuntime(Runtime::kInlineGeneratorClose, arg);
      },
      catch_prediction());
}
References v8::base::args, v8::internal::HandlerTable::ASYNC_AWAIT, builder(), BuildGeneratorObjectVariableInitialization(), BuildInitializationBlockForParametersIfExist(), BuildTryCatch(), BuildTryFinally(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), catch_prediction(), v8::internal::DCHECK(), execution_control(), function_kind(), GenerateBodyStatements(), generator_object(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::kNoSourcePosition, v8::internal::interpreter::BytecodeArrayBuilder::LoadTheHole(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeGenerator::ControlScope::ReturnAccumulator(), set_catch_prediction(), v8::internal::interpreter::BytecodeArrayBuilder::SetPendingMessage(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by GenerateBytecodeBody().
GenerateBaseConstructorBody()
void v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody () [private]
Definition at line 1769 of file bytecode-generator.cc.
                                                    {
  DCHECK(IsBaseConstructor(function_kind()));
  FunctionLiteral* literal = info()->literal();
  // The derived constructor case is handled in VisitCallSuper.
  if (literal->class_scope_has_private_brand()) {
    ClassScope* scope = info()->scope()->outer_scope()->AsClassScope();
    DCHECK_NOT_NULL(scope->brand());
    BuildPrivateBrandInitialization(builder()->Receiver(), scope->brand());
  }
  if (literal->requires_instance_members_initializer()) {
    BuildInstanceMemberInitialization(Register::function_closure(),
                                      builder()->Receiver());
  }
  GenerateBodyStatements();
}
References v8::internal::Scope::AsClassScope(), v8::internal::ClassScope::brand(), builder(), BuildInstanceMemberInitialization(), BuildPrivateBrandInitialization(), v8::internal::FunctionLiteral::class_scope_has_private_brand(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::interpreter::Register::function_closure(), function_kind(), GenerateBodyStatements(), info(), v8::internal::IsBaseConstructor(), v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::Scope::outer_scope(), v8::internal::FunctionLiteral::requires_instance_members_initializer(), and v8::internal::UnoptimizedCompilationInfo::scope().
Referenced by GenerateBytecodeBody().
GenerateBodyPrologue()
void v8::internal::interpreter::BytecodeGenerator::GenerateBodyPrologue () [private]
Definition at line 1733 of file bytecode-generator.cc.
                                             {
  // Build the arguments object if it is used.
  VisitArgumentsObject(closure_scope()->arguments());
  // Build rest arguments array if it is used.
  Variable* rest_parameter = closure_scope()->rest_parameter();
  VisitRestArgumentsArray(rest_parameter);
  // Build assignment to the function name or {.this_function}
  // variables if used.
  VisitThisFunctionVariable(closure_scope()->function_var());
  VisitThisFunctionVariable(closure_scope()->this_function_var());
  // Build assignment to {new.target} variable if it is used.
  VisitNewTargetVariable(closure_scope()->new_target_var());
  FunctionLiteral* literal = info()->literal();
  // Emit tracing call if requested to do so.
  if (v8_flags.trace) builder()->CallRuntime(Runtime::kTraceEnter);
  // Increment the function-scope block coverage counter.
  BuildIncrementBlockCoverageCounterIfEnabled(literal, SourceRangeKind::kBody);
  // Visit declarations within the function scope.
  if (closure_scope()->is_script_scope()) {
    VisitGlobalDeclarations(closure_scope()->declarations());
  } else if (closure_scope()->is_module_scope()) {
    VisitModuleDeclarations(closure_scope()->declarations());
  } else {
    VisitDeclarations(closure_scope()->declarations());
  }
  // Emit initializing assignments for module namespace imports (if any).
  VisitModuleNamespaceImports();
}
References builder(), BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), closure_scope(), info(), v8::internal::kBody, v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::DeclarationScope::rest_parameter(), v8::internal::v8_flags, VisitArgumentsObject(), VisitDeclarations(), VisitGlobalDeclarations(), VisitModuleDeclarations(), VisitModuleNamespaceImports(), VisitNewTargetVariable(), VisitRestArgumentsArray(), and VisitThisFunctionVariable().
Referenced by GenerateBytecodeBody().
GenerateBodyStatements()
void v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatements (int start = 0) [private]
Definition at line 1975 of file bytecode-generator.cc.
                                                        {
  GenerateBodyStatementsWithoutImplicitFinalReturn(start);
  // Emit an implicit return instruction in case control flow can fall off the
  // end of the function without an explicit return being present on all paths.
  //
  // ControlScope is used instead of building the Return bytecode directly, as
  // the entire body is wrapped in a try-finally block for async generators.
  if (!builder()->RemainderOfBlockIsDead()) {
    builder()->LoadUndefined();
    const int pos = info()->literal()->return_position();
    if (IsAsyncFunction(function_kind()) ||
        IsModuleWithTopLevelAwait(function_kind())) {
      execution_control()->AsyncReturnAccumulator(pos);
    } else {
      execution_control()->ReturnAccumulator(pos);
    }
  }
}
References v8::internal::interpreter::BytecodeGenerator::ControlScope::AsyncReturnAccumulator(), builder(), execution_control(), function_kind(), GenerateBodyStatementsWithoutImplicitFinalReturn(), info(), v8::internal::IsAsyncFunction(), v8::internal::IsModuleWithTopLevelAwait(), v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined(), v8::internal::FunctionLiteral::return_position(), and v8::internal::interpreter::BytecodeGenerator::ControlScope::ReturnAccumulator().
Referenced by GenerateAsyncFunctionBody(), GenerateAsyncGeneratorFunctionBody(), GenerateBaseConstructorBody(), and GenerateBytecodeBody().
GenerateBodyStatementsWithoutImplicitFinalReturn()
void v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatementsWithoutImplicitFinalReturn (int start = 0) [private]
Definition at line 1995 of file bytecode-generator.cc.
               {
  ZonePtrList<Statement>* body = info()->literal()->body();
  if (v8_flags.js_explicit_resource_management && closure_scope() != nullptr &&
      (closure_scope()->has_using_declaration() ||
       closure_scope()->has_await_using_declaration())) {
    BuildDisposeScope([&]() { VisitStatements(body, start); },
                      closure_scope()->has_await_using_declaration());
  } else {
    VisitStatements(body, start);
  }
}
References v8::internal::FunctionLiteral::body(), BuildDisposeScope(), closure_scope(), v8::internal::Scope::has_await_using_declaration(), info(), v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::v8_flags, and VisitStatements().
Referenced by GenerateBodyStatements(), and GenerateDerivedConstructorBody().
GenerateBytecode()
void v8::internal::interpreter::BytecodeGenerator::GenerateBytecode (uintptr_t stack_limit)
Definition at line 1657 of file bytecode-generator.cc.
                                                              {
  InitializeAstVisitor(stack_limit);
  if (v8_flags.stress_lazy_compilation && local_isolate_->is_main_thread() &&
      !local_isolate_->AsIsolate()->bootstrapper()->IsActive()) {
    // Trigger stack overflow with 1/stress_lazy_compilation probability.
    // Do this only for the main thread compilations because querying random
    // numbers from background threads will make the random values dependent
    // on the thread scheduling and thus non-deterministic.
    stack_overflow_ = local_isolate_->fuzzer_rng()->NextInt(
                          v8_flags.stress_lazy_compilation) == 0;
  }
  // Initialize the incoming context.
  ContextScope incoming_context(this, closure_scope());
  // Initialize control scope.
  ControlScopeForTopLevel control(this);
  RegisterAllocationScope register_scope(this);
  AllocateTopLevelRegisters();
  builder()->EmitFunctionStartSourcePosition(
      info()->literal()->start_position());
  if (info()->literal()->CanSuspend()) {
    BuildGeneratorPrologue();
  }
  if (NeedsContextInitialization(closure_scope())) {
    // Push a new inner context scope for the function.
    BuildNewLocalActivationContext();
    ContextScope local_function_context(this, closure_scope());
    BuildLocalActivationContextInitialization();
    GenerateBytecodeBody();
  } else {
    GenerateBytecodeBody();
  }
  // Reset variables with hole check bitmap indices for subsequent compilations
  // in the same parsing zone.
  for (Variable* var : vars_in_hole_check_bitmap_) {
    var->ResetHoleCheckBitmapIndex();
  }
  // Check that we are not falling off the end.
  DCHECK(builder()->RemainderOfBlockIsDead());
}
References AllocateTopLevelRegisters(), v8::internal::LocalIsolate::AsIsolate(), v8::internal::Isolate::bootstrapper(), builder(), BuildGeneratorPrologue(), BuildLocalActivationContextInitialization(), BuildNewLocalActivationContext(), closure_scope(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayBuilder::EmitFunctionStartSourcePosition(), v8::internal::LocalIsolate::fuzzer_rng(), GenerateBytecodeBody(), info(), v8::internal::LocalIsolate::is_main_thread(), v8::internal::Bootstrapper::IsActive(), local_isolate_, v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::NeedsContextInitialization(), v8::base::RandomNumberGenerator::NextInt(), v8::internal::v8_flags, and vars_in_hole_check_bitmap_.
Referenced by v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl().
GenerateBytecodeBody()
void v8::internal::interpreter::BytecodeGenerator::GenerateBytecodeBody () [private]
Definition at line 1706 of file bytecode-generator.cc.
                                             {
  GenerateBodyPrologue();
  if (IsBaseConstructor(function_kind())) {
    GenerateBaseConstructorBody();
  } else if (function_kind() == FunctionKind::kDerivedConstructor) {
    GenerateDerivedConstructorBody();
  } else if (IsAsyncFunction(function_kind()) ||
             IsModuleWithTopLevelAwait(function_kind())) {
    if (IsAsyncGeneratorFunction(function_kind())) {
      GenerateAsyncGeneratorFunctionBody();
    } else {
      GenerateAsyncFunctionBody();
    }
  } else {
    int start = 0;
    if (BuildInitializationBlockForParametersIfExist()) {
      start = 1;
    }
    if (IsResumableFunction(info()->literal()->kind())) {
      BuildGeneratorObjectVariableInitialization();
    }
    GenerateBodyStatements(start);
  }
}
References BuildGeneratorObjectVariableInitialization(), BuildInitializationBlockForParametersIfExist(), function_kind(), GenerateAsyncFunctionBody(), GenerateAsyncGeneratorFunctionBody(), GenerateBaseConstructorBody(), GenerateBodyPrologue(), GenerateBodyStatements(), GenerateDerivedConstructorBody(), info(), v8::internal::IsAsyncFunction(), v8::internal::IsAsyncGeneratorFunction(), v8::internal::IsBaseConstructor(), v8::internal::IsModuleWithTopLevelAwait(), v8::internal::IsResumableFunction(), and v8::internal::kDerivedConstructor.
Referenced by GenerateBytecode().
GenerateDerivedConstructorBody()
void v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody () [private]
Definition at line 1789 of file bytecode-generator.cc.
                                                       {
  DCHECK_EQ(FunctionKind::kDerivedConstructor, function_kind());
  FunctionLiteral* literal = info()->literal();
  // Per spec, derived constructors can only return undefined or an object;
  // other primitives trigger an exception in ConstructStub.
  //
  // Since the receiver is popped by the callee, derived constructors return
  // <this> if the original return value was undefined.
  //
  // Also per spec, this return value check is done after all user code (e.g.,
  // finally blocks) are executed. For example, the following code does not
  // throw.
  //
  // class C extends class {} {
  // constructor() {
  // try { throw 42; }
  // catch(e) { return; }
  // finally { super(); }
  // }
  // }
  // new C();
  //
  // This check is implemented by jumping to the check instead of emitting a
  // return bytecode in-place inside derived constructors.
  //
  // Note that default derived constructors do not need this check as they
  // just forward a super call.
  BytecodeLabels check_return_value(zone());
  Register result = register_allocator()->NewRegister();
  ControlScopeForDerivedConstructor control(this, result, &check_return_value);
  {
    HoleCheckElisionScope elider(this);
    GenerateBodyStatementsWithoutImplicitFinalReturn();
  }
  if (check_return_value.empty()) {
    if (!builder()->RemainderOfBlockIsDead()) {
      BuildThisVariableLoad();
      BuildReturn(literal->return_position());
    }
  } else {
    BytecodeLabels return_this(zone());
    if (!builder()->RemainderOfBlockIsDead()) {
      builder()->Jump(return_this.New());
    }
    check_return_value.Bind(builder());
    builder()->LoadAccumulatorWithRegister(result);
    builder()->JumpIfUndefined(return_this.New());
    BuildReturn(literal->return_position());
    {
      return_this.Bind(builder());
      BuildThisVariableLoad();
      BuildReturn(literal->return_position());
    }
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildReturn(), BuildThisVariableLoad(), DCHECK_EQ, v8::internal::interpreter::BytecodeLabels::empty(), function_kind(), GenerateBodyStatementsWithoutImplicitFinalReturn(), info(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefined(), v8::internal::kDerivedConstructor, v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::base::internal::result, v8::internal::FunctionLiteral::return_position(), and zone().
Referenced by GenerateBytecodeBody().
generator_object()
Register v8::internal::interpreter::BytecodeGenerator::generator_object () const [inline], [private]
Definition at line 8675 of file bytecode-generator.cc.
                                                   {
  DCHECK(IsResumableFunction(info()->literal()->kind()));
  SBXCHECK(incoming_new_target_or_generator_.is_valid());
  return incoming_new_target_or_generator_;
}
References v8::internal::DCHECK(), incoming_new_target_or_generator_, info(), v8::internal::interpreter::Register::is_valid(), v8::internal::IsResumableFunction(), and SBXCHECK.
Referenced by BuildAsyncReturn(), BuildAwait(), BuildGeneratorObjectVariableInitialization(), BuildGeneratorPrologue(), BuildSuspendPoint(), GenerateAsyncFunctionBody(), and GenerateAsyncGeneratorFunctionBody().
GetCachedCreateClosureSlot()
int v8::internal::interpreter::BytecodeGenerator::GetCachedCreateClosureSlot (FunctionLiteral * literal) [private]
Definition at line 8783 of file bytecode-generator.cc.
                                                                          {
  FeedbackSlotCache::SlotKind slot_kind =
      FeedbackSlotCache::SlotKind::kClosureFeedbackCell;
  int index = feedback_slot_cache()->Get(slot_kind, literal);
  if (index != -1) {
    return index;
  }
  index = feedback_spec()->AddCreateClosureParameterCount(
      JSParameterCount(literal->parameter_count()));
  feedback_slot_cache()->Put(slot_kind, literal, index);
  return index;
}
References v8::internal::FeedbackVectorSpec::AddCreateClosureParameterCount(), feedback_slot_cache(), feedback_spec(), v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Get(), v8::internal::index, v8::internal::JSParameterCount(), v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kClosureFeedbackCell, v8::internal::FunctionLiteral::parameter_count(), and v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put().
Referenced by v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations().
GetCachedLoadGlobalICSlot()
FeedbackSlot v8::internal::interpreter::BytecodeGenerator::GetCachedLoadGlobalICSlot (TypeofMode typeof_mode, Variable * variable) [private]
Definition at line 8690 of file bytecode-generator.cc.
                                                {
  FeedbackSlotCache::SlotKind slot_kind =
      typeof_mode == TypeofMode::kInside
          ? FeedbackSlotCache::SlotKind::kLoadGlobalInsideTypeof
          : FeedbackSlotCache::SlotKind::kLoadGlobalNotInsideTypeof;
  FeedbackSlot slot(feedback_slot_cache()->Get(slot_kind, variable));
  if (!slot.IsInvalid()) {
    return slot;
  }
  slot = feedback_spec()->AddLoadGlobalICSlot(typeof_mode);
  feedback_slot_cache()->Put(slot_kind, variable, feedback_index(slot));
  return slot;
}
References v8::internal::FeedbackVectorSpec::AddLoadGlobalICSlot(), feedback_index(), feedback_slot_cache(), feedback_spec(), v8::internal::compiler::turboshaft::Get(), v8::internal::FeedbackSlot::IsInvalid(), v8::internal::kInside, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kLoadGlobalInsideTypeof, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kLoadGlobalNotInsideTypeof, and v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put().
Referenced by BuildVariableLoad().
GetCachedLoadICSlot()
FeedbackSlot v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot (const Expression * expr, const AstRawString * name) [private]
Definition at line 8720 of file bytecode-generator.cc.
                                                                              {
  DCHECK(!expr->IsSuperPropertyReference());
  if (!v8_flags.ignition_share_named_property_feedback) {
    return feedback_spec()->AddLoadICSlot();
  }
  FeedbackSlotCache::SlotKind slot_kind =
      FeedbackSlotCache::SlotKind::kLoadProperty;
  if (!expr->IsVariableProxy()) {
    return feedback_spec()->AddLoadICSlot();
  }
  const VariableProxy* proxy = expr->AsVariableProxy();
  FeedbackSlot slot(
      feedback_slot_cache()->Get(slot_kind, proxy->var()->index(), name));
  if (!slot.IsInvalid()) {
    return slot;
  }
  slot = feedback_spec()->AddLoadICSlot();
  feedback_slot_cache()->Put(slot_kind, proxy->var()->index(), name,
                             feedback_index(slot));
  return slot;
}
References v8::internal::FeedbackVectorSpec::AddLoadICSlot(), v8::internal::DCHECK(), feedback_index(), feedback_slot_cache(), feedback_spec(), v8::internal::compiler::turboshaft::Get(), v8::internal::Variable::index(), v8::internal::FeedbackSlot::IsInvalid(), v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kLoadProperty, v8::internal::name, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put(), v8::internal::v8_flags, and v8::internal::VariableProxy::var().
Referenced by BuildLoadNamedProperty().
GetCachedLoadSuperICSlot()
FeedbackSlot v8::internal::interpreter::BytecodeGenerator::GetCachedLoadSuperICSlot (const AstRawString * name) [private]
Definition at line 8743 of file bytecode-generator.cc.
                              {
  if (!v8_flags.ignition_share_named_property_feedback) {
    return feedback_spec()->AddLoadICSlot();
  }
  FeedbackSlotCache::SlotKind slot_kind =
      FeedbackSlotCache::SlotKind::kLoadSuperProperty;
  FeedbackSlot slot(feedback_slot_cache()->Get(slot_kind, name));
  if (!slot.IsInvalid()) {
    return slot;
  }
  slot = feedback_spec()->AddLoadICSlot();
  feedback_slot_cache()->Put(slot_kind, name, feedback_index(slot));
  return slot;
}
References v8::internal::FeedbackVectorSpec::AddLoadICSlot(), feedback_index(), feedback_slot_cache(), feedback_spec(), v8::internal::compiler::turboshaft::Get(), v8::internal::FeedbackSlot::IsInvalid(), v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kLoadSuperProperty, v8::internal::name, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put(), and v8::internal::v8_flags.
Referenced by VisitNamedSuperPropertyLoad().
GetCachedStoreGlobalICSlot()
FeedbackSlot v8::internal::interpreter::BytecodeGenerator::GetCachedStoreGlobalICSlot (LanguageMode language_mode, Variable * variable) [private]
Definition at line 8705 of file bytecode-generator.cc.
                                                    {
  FeedbackSlotCache::SlotKind slot_kind =
      is_strict(language_mode)
          ? FeedbackSlotCache::SlotKind::kStoreGlobalStrict
          : FeedbackSlotCache::SlotKind::kStoreGlobalSloppy;
  FeedbackSlot slot(feedback_slot_cache()->Get(slot_kind, variable));
  if (!slot.IsInvalid()) {
    return slot;
  }
  slot = feedback_spec()->AddStoreGlobalICSlot(language_mode);
  feedback_slot_cache()->Put(slot_kind, variable, feedback_index(slot));
  return slot;
}
References v8::internal::FeedbackVectorSpec::AddStoreGlobalICSlot(), feedback_index(), feedback_slot_cache(), feedback_spec(), v8::internal::compiler::turboshaft::Get(), v8::internal::is_strict(), v8::internal::FeedbackSlot::IsInvalid(), v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kStoreGlobalSloppy, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kStoreGlobalStrict, language_mode(), and v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put().
Referenced by BuildStoreGlobal().
GetCachedStoreICSlot()
FeedbackSlot v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot (const Expression * expr, const AstRawString * name) [private]
Definition at line 8760 of file bytecode-generator.cc.
                                                                               {
  if (!v8_flags.ignition_share_named_property_feedback) {
    return feedback_spec()->AddStoreICSlot(language_mode());
  }
  FeedbackSlotCache::SlotKind slot_kind =
      is_strict(language_mode()) ? FeedbackSlotCache::SlotKind::kSetNamedStrict
                                 : FeedbackSlotCache::SlotKind::kSetNamedSloppy;
  if (!expr->IsVariableProxy()) {
    return feedback_spec()->AddStoreICSlot(language_mode());
  }
  const VariableProxy* proxy = expr->AsVariableProxy();
  FeedbackSlot slot(
      feedback_slot_cache()->Get(slot_kind, proxy->var()->index(), name));
  if (!slot.IsInvalid()) {
    return slot;
  }
  slot = feedback_spec()->AddStoreICSlot(language_mode());
  feedback_slot_cache()->Put(slot_kind, proxy->var()->index(), name,
                             feedback_index(slot));
  return slot;
}
References v8::internal::FeedbackVectorSpec::AddStoreICSlot(), feedback_index(), feedback_slot_cache(), feedback_spec(), v8::internal::compiler::turboshaft::Get(), v8::internal::Variable::index(), v8::internal::is_strict(), v8::internal::FeedbackSlot::IsInvalid(), v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kSetNamedSloppy, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::kSetNamedStrict, language_mode(), v8::internal::name, v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put(), v8::internal::v8_flags, and v8::internal::VariableProxy::var().
Referenced by BuildSetNamedProperty().
GetDestructuringDefaultValue()
Expression * v8::internal::interpreter::BytecodeGenerator::GetDestructuringDefaultValue (Expression ** target) [private]
Definition at line 5192 of file bytecode-generator.cc.
                         {
  Expression* default_value = nullptr;
  if ((*target)->IsAssignment()) {
    Assignment* default_init = (*target)->AsAssignment();
    DCHECK_EQ(default_init->op(), Token::kAssign);
    default_value = default_init->value();
    *target = default_init->target();
    DCHECK((*target)->IsValidReferenceExpression() || (*target)->IsPattern());
  }
  return default_value;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Assignment::op(), v8::internal::Assignment::target(), and v8::internal::Assignment::value().
Referenced by BuildDestructuringArrayAssignment(), and BuildDestructuringObjectAssignment().
GetDummyCompareICSlot()
FeedbackSlot v8::internal::interpreter::BytecodeGenerator::GetDummyCompareICSlot () [private]
Definition at line 8796 of file bytecode-generator.cc.
                                                      {
  return dummy_feedback_slot_.Get();
}
References dummy_feedback_slot_, and v8::internal::SharedFeedbackSlot::Get().
Referenced by BuildClassLiteral().
GetPotentialVariableInAccumulator()
Variable * v8::internal::interpreter::BytecodeGenerator::GetPotentialVariableInAccumulator () [private]
Definition at line 4475 of file bytecode-generator.cc.
                                                               {
  BytecodeRegisterOptimizer* optimizer = builder()->GetRegisterOptimizer();
  if (optimizer) {
    return optimizer->GetPotentialVariableInAccumulator();
  }
  return nullptr;
}
References builder(), v8::internal::interpreter::BytecodeRegisterOptimizer::GetPotentialVariableInAccumulator(), and v8::internal::interpreter::BytecodeArrayBuilder::GetRegisterOptimizer().
Referenced by BuildLoadKeyedProperty().
GetRegisterForLocalVariable()
Register v8::internal::interpreter::BytecodeGenerator::GetRegisterForLocalVariable (Variable * variable) [private]
Definition at line 8646 of file bytecode-generator.cc.
                                                                          {
  DCHECK_EQ(VariableLocation::LOCAL, variable->location());
  return builder()->Local(variable->index());
}
References builder(), DCHECK_EQ, v8::internal::LOCAL, and v8::internal::interpreter::BytecodeArrayBuilder::Local().
Referenced by AllocateTopLevelRegisters(), BuildGeneratorObjectVariableInitialization(), GetTypeHintForLocalVariable(), and VisitNewTargetVariable().
GetTypeHintForLocalVariable()
BytecodeGenerator::TypeHint v8::internal::interpreter::BytecodeGenerator::GetTypeHintForLocalVariable (Variable * variable) [private]
Definition at line 8651 of file bytecode-generator.cc.
                        {
  BytecodeRegisterOptimizer* optimizer = builder()->GetRegisterOptimizer();
  if (optimizer) {
    Register reg = GetRegisterForLocalVariable(variable);
    return optimizer->GetTypeHint(reg);
  }
  return TypeHint::kAny;
}
References builder(), GetRegisterForLocalVariable(), v8::internal::interpreter::BytecodeArrayBuilder::GetRegisterOptimizer(), and v8::internal::interpreter::BytecodeRegisterOptimizer::GetTypeHint().
Referenced by IsLocalVariableWithInternalizedStringHint().
incoming_new_target()
Register v8::internal::interpreter::BytecodeGenerator::incoming_new_target () const [inline], [private]
Definition at line 8669 of file bytecode-generator.cc.
                                                      {
  DCHECK(!IsResumableFunction(info()->literal()->kind()));
  SBXCHECK(incoming_new_target_or_generator_.is_valid());
  return incoming_new_target_or_generator_;
}
References v8::internal::DCHECK(), incoming_new_target_or_generator_, info(), v8::internal::interpreter::Register::is_valid(), v8::internal::IsResumableFunction(), and SBXCHECK.
Referenced by VisitNewTargetVariable().
info()
UnoptimizedCompilationInfo* v8::internal::interpreter::BytecodeGenerator::info () const [inline], [private]
Definition at line 539 of file bytecode-generator.h.
{ return info_; }
References info_.
Referenced by AddToEagerLiteralsIfEager(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), AllocateDeferredConstants(), AllocateTopLevelRegisters(), BuildAsyncReturn(), BuildAwait(), BuildDisposeScope(), BuildGeneratorObjectVariableInitialization(), BuildGeneratorPrologue(), BuildGetAndCheckSuperConstructor(), BuildInitializationBlockForParametersIfExist(), BuildInstanceInitializationAfterSuperCall(), BuildPrivateBrandInitialization(), BytecodeGenerator(), feedback_spec(), FinalizeBytecode(), function_kind(), GenerateAsyncFunctionBody(), GenerateBaseConstructorBody(), GenerateBodyPrologue(), GenerateBodyStatements(), GenerateBodyStatementsWithoutImplicitFinalReturn(), GenerateBytecode(), GenerateBytecodeBody(), GenerateDerivedConstructorBody(), generator_object(), incoming_new_target(), and VisitNewTargetVariable().
IsLocalVariableWithInternalizedStringHint()
bool v8::internal::interpreter::BytecodeGenerator::IsLocalVariableWithInternalizedStringHint (Expression * expr) [private]
Definition at line 7435 of file bytecode-generator.cc.
                      {
  VariableProxy* proxy = expr->AsVariableProxy();
  return proxy != nullptr && proxy->is_resolved() &&
         proxy->var()->IsStackLocal() &&
         GetTypeHintForLocalVariable(proxy->var()) ==
             TypeHint::kInternalizedString;
}
References GetTypeHintForLocalVariable(), v8::internal::VariableProxy::is_resolved(), v8::internal::Variable::IsStackLocal(), and v8::internal::VariableProxy::var().
IsSameOrSubTypeHint()
static bool v8::internal::interpreter::BytecodeGenerator::IsSameOrSubTypeHint (TypeHint hint1, TypeHint hint2) [inline], [static]
Definition at line 56 of file bytecode-generator.h.
                                                                  {
    return hint1 == (hint1 | hint2);
  }
Referenced by IsStringTypeHint(), and v8::internal::interpreter::BytecodeRegisterOptimizer::SetTypeHintForAccumulator().
IsStringTypeHint()
static bool v8::internal::interpreter::BytecodeGenerator::IsStringTypeHint (TypeHint hint) [inline], [static]
Definition at line 60 of file bytecode-generator.h.
                                              {
    return IsSameOrSubTypeHint(TypeHint::kString, hint);
  }
References IsSameOrSubTypeHint().
Referenced by VisitArithmeticExpression(), and VisitNaryArithmeticExpression().
IsVariableInRegister()
bool v8::internal::interpreter::BytecodeGenerator::IsVariableInRegister (Variable * var, Register reg) [private]
Definition at line 4460 of file bytecode-generator.cc.
                                                                        {
  BytecodeRegisterOptimizer* optimizer = builder()->GetRegisterOptimizer();
  if (optimizer) {
    return optimizer->IsVariableInRegister(var, reg);
  }
  return false;
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::GetRegisterOptimizer(), and v8::internal::interpreter::BytecodeRegisterOptimizer::IsVariableInRegister().
Referenced by BuildVariableLoad().
language_mode()
LanguageMode v8::internal::interpreter::BytecodeGenerator::language_mode () const [inline], [private]
Definition at line 8665 of file bytecode-generator.cc.
                                                    {
  return current_scope()->language_mode();
}
References current_scope(), and v8::internal::Scope::language_mode().
Referenced by BuildAssignment(), BuildClassLiteral(), BuildSetNamedProperty(), BuildStoreGlobal(), BuildVariableAssignment(), GetCachedStoreGlobalICSlot(), GetCachedStoreICSlot(), and VisitDelete().
PrepareAssignmentLhs()
BytecodeGenerator::AssignmentLhsData v8::internal::interpreter::BytecodeGenerator::PrepareAssignmentLhs (Expression * lhs, AccumulatorPreservingMode accumulator_preserving_mode = AccumulatorPreservingMode::kNone) [private]
Definition at line 5016 of file bytecode-generator.cc.
                                                                            {
  // Left-hand side can only be a property, a global or a variable slot.
  Property* property = lhs->AsProperty();
  AssignType assign_type = Property::GetAssignType(property);
  // Evaluate LHS expression.
  switch (assign_type) {
    case NON_PROPERTY:
      return AssignmentLhsData::NonProperty(lhs);
    case NAMED_PROPERTY: {
      AccumulatorPreservingScope scope(this, accumulator_preserving_mode);
      Register object = VisitForRegisterValue(property->obj());
      const AstRawString* name =
          property->key()->AsLiteral()->AsRawPropertyName();
      return AssignmentLhsData::NamedProperty(property->obj(), object, name);
    }
    case KEYED_PROPERTY: {
      AccumulatorPreservingScope scope(this, accumulator_preserving_mode);
      Register object = VisitForRegisterValue(property->obj());
      Register key = VisitForRegisterValue(property->key());
      return AssignmentLhsData::KeyedProperty(object, key);
    }
    case PRIVATE_METHOD:
    case PRIVATE_GETTER_ONLY:
    case PRIVATE_SETTER_ONLY:
    case PRIVATE_GETTER_AND_SETTER: {
      DCHECK(!property->IsSuperAccess());
      AccumulatorPreservingScope scope(this, accumulator_preserving_mode);
      Register object = VisitForRegisterValue(property->obj());
      Register key = VisitForRegisterValue(property->key());
      return AssignmentLhsData::PrivateMethodOrAccessor(assign_type, property,
                                                        object, key);
    }
    case PRIVATE_DEBUG_DYNAMIC: {
      AccumulatorPreservingScope scope(this, accumulator_preserving_mode);
      Register object = VisitForRegisterValue(property->obj());
      // Do not visit the key here, instead we will look them up at run time.
      return AssignmentLhsData::PrivateDebugEvaluate(assign_type, property,
                                                     object);
    }
    case NAMED_SUPER_PROPERTY: {
      AccumulatorPreservingScope scope(this, accumulator_preserving_mode);
      RegisterList super_property_args =
          register_allocator()->NewRegisterList(4);
      BuildThisVariableLoad();
      builder()->StoreAccumulatorInRegister(super_property_args[0]);
      BuildVariableLoad(
          property->obj()->AsSuperPropertyReference()->home_object()->var(),
          HoleCheckMode::kElided);
      builder()->StoreAccumulatorInRegister(super_property_args[1]);
      builder()
          ->LoadLiteral(property->key()->AsLiteral()->AsRawPropertyName())
          .StoreAccumulatorInRegister(super_property_args[2]);
      return AssignmentLhsData::NamedSuperProperty(super_property_args);
    }
    case KEYED_SUPER_PROPERTY: {
      AccumulatorPreservingScope scope(this, accumulator_preserving_mode);
      RegisterList super_property_args =
          register_allocator()->NewRegisterList(4);
      BuildThisVariableLoad();
      builder()->StoreAccumulatorInRegister(super_property_args[0]);
      BuildVariableLoad(
          property->obj()->AsSuperPropertyReference()->home_object()->var(),
          HoleCheckMode::kElided);
      builder()->StoreAccumulatorInRegister(super_property_args[1]);
      VisitForRegisterValue(property->key(), super_property_args[2]);
      return AssignmentLhsData::KeyedSuperProperty(super_property_args);
    }
  }
  UNREACHABLE();
}
References builder(), BuildThisVariableLoad(), BuildVariableLoad(), v8::internal::DCHECK(), v8::internal::Property::GetAssignType(), v8::internal::Property::IsSuperAccess(), v8::internal::kElided, v8::internal::Property::key(), v8::internal::key, v8::internal::KEYED_PROPERTY, v8::internal::KEYED_SUPER_PROPERTY, v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::KeyedProperty(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::KeyedSuperProperty(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::name, v8::internal::NAMED_PROPERTY, v8::internal::NAMED_SUPER_PROPERTY, v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NamedProperty(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NamedSuperProperty(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::NON_PROPERTY, v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::NonProperty(), v8::internal::Property::obj(), v8::internal::PRIVATE_DEBUG_DYNAMIC, v8::internal::PRIVATE_GETTER_AND_SETTER, v8::internal::PRIVATE_GETTER_ONLY, v8::internal::PRIVATE_METHOD, v8::internal::PRIVATE_SETTER_ONLY, v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::PrivateDebugEvaluate(), v8::internal::interpreter::BytecodeGenerator::AssignmentLhsData::PrivateMethodOrAccessor(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::UNREACHABLE(), and VisitForRegisterValue().
Referenced by BuildDestructuringArrayAssignment(), and BuildDestructuringObjectAssignment().
register_allocator()
BytecodeRegisterAllocator* v8::internal::interpreter::BytecodeGenerator::register_allocator () [inline], [private]
Definition at line 559 of file bytecode-generator.h.
                                                  {
    return builder()->register_allocator();
  }
References builder(), and v8::internal::interpreter::BytecodeArrayBuilder::register_allocator().
Referenced by AddDisposableValue(), AllocateTopLevelRegisters(), BuildAssignment(), BuildAsyncReturn(), BuildAwait(), BuildCallIteratorMethod(), BuildClassLiteral(), BuildClassProperty(), BuildCreateArrayLiteral(), BuildDeclareCall(), BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), BuildDisposeScope(), BuildFinalizeIteration(), BuildGeneratorObjectVariableInitialization(), BuildGetIterator(), BuildGetIteratorRecord(), BuildInstanceMemberInitialization(), BuildInvalidPropertyAccess(), BuildIteratorClose(), BuildLiteralStrictCompareBoolean(), BuildNewLocalActivationContext(), BuildNewLocalCatchContext(), BuildNewLocalWithContext(), BuildPrivateBrandCheck(), BuildPrivateBrandInitialization(), BuildPrivateDebugDynamicGet(), BuildPrivateDebugDynamicSet(), BuildPrivateGetterAccess(), BuildPrivateMethodIn(), BuildPrivateSetterAccess(), BuildPushUndefinedIntoRegisterList(), BuildReturn(), BuildSetNamedProperty(), BuildStoreGlobal(), BuildSuperCallOptimization(), BuildSuspendPoint(), BuildTryCatch(), BuildTryFinally(), BuildVariableAssignment(), v8::internal::interpreter::BytecodeGenerator::DisposablesStackScope::DisposablesStackScope(), GenerateAsyncFunctionBody(), GenerateAsyncGeneratorFunctionBody(), GenerateDerivedConstructorBody(), v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope(), PrepareAssignmentLhs(), VisitAndPushIntoRegisterList(), VisitArithmeticExpression(), VisitCallSuper(), VisitDelete(), VisitForRegisterValue(), VisitKeyedSuperPropertyLoad(), VisitModuleNamespaceImports(), VisitNamedSuperPropertyLoad(), and VisitNaryArithmeticExpression().
RememberHoleCheckInCurrentBlock()
void v8::internal::interpreter::BytecodeGenerator::RememberHoleCheckInCurrentBlock (Variable * variable) [private]
Definition at line 4660 of file bytecode-generator.cc.
                                                                          {
  if (!v8_flags.ignition_elide_redundant_tdz_checks) return;
  // The first N-1 variables that need hole checks may be cached in a bitmap to
  // elide subsequent hole checks in the same basic block, where N is
  // Variable::kHoleCheckBitmapBits.
  //
  // This numbering is done during bytecode generation instead of scope analysis
  // for 2 reasons:
  //
  // 1. There may be multiple eagerly compiled inner functions during a single
  // run of scope analysis, so a global numbering will result in fewer variables
  // with cacheable hole checks.
  //
  // 2. Compiler::CollectSourcePositions reparses functions and checks that the
  // recompiled bytecode is identical. Therefore the numbering must be kept
  // identical regardless of whether a function is eagerly compiled as part of
  // an outer compilation or recompiled during source position collection. The
  // simplest way to guarantee identical numbering is to scope it to the
  // compilation instead of scope analysis.
  variable->RememberHoleCheckInBitmap(hole_check_bitmap_,
                                      vars_in_hole_check_bitmap_);
}
References hole_check_bitmap_, v8::internal::v8_flags, and vars_in_hole_check_bitmap_.
Referenced by BuildThrowIfHole(), and BuildVariableAssignment().
set_catch_prediction()
void v8::internal::interpreter::BytecodeGenerator::set_catch_prediction (HandlerTable::CatchPrediction value) [inline], [private]
Definition at line 579 of file bytecode-generator.h.
                                                                      {
    catch_prediction_ = value;
  }
References catch_prediction_, and v8::internal::value.
Referenced by BuildDisposeScope(), GenerateAsyncFunctionBody(), and GenerateAsyncGeneratorFunctionBody().
set_current_disposables_stack()
void v8::internal::interpreter::BytecodeGenerator::set_current_disposables_stack (Register disposables_stack) [inline], [private]
Definition at line 599 of file bytecode-generator.h.
                                                                 {
    current_disposables_stack_ = disposables_stack;
  }
References current_disposables_stack_.
set_current_for_in_scope()
void v8::internal::interpreter::BytecodeGenerator::set_current_for_in_scope (ForInScope * for_in_scope) [inline], [private]
Definition at line 591 of file bytecode-generator.h.
                                                                 {
    current_for_in_scope_ = for_in_scope;
  }
References current_for_in_scope_.
set_current_loop_scope()
void v8::internal::interpreter::BytecodeGenerator::set_current_loop_scope (LoopScope * loop_scope) [inline], [private]
Definition at line 584 of file bytecode-generator.h.
                                                     {
    current_loop_scope_ = loop_scope;
  }
References current_loop_scope_.
set_current_scope()
void v8::internal::interpreter::BytecodeGenerator::set_current_scope (Scope * scope) [inline], [private]
Definition at line 545 of file bytecode-generator.h.
{ current_scope_ = scope; }
References current_scope_.
set_execution_context()
void v8::internal::interpreter::BytecodeGenerator::set_execution_context (ContextScope * context) [inline], [private]
Definition at line 552 of file bytecode-generator.h.
                                                           {
    execution_context_ = context;
  }
References execution_context_.
set_execution_control()
void v8::internal::interpreter::BytecodeGenerator::set_execution_control (ControlScope * scope) [inline], [private]
Definition at line 548 of file bytecode-generator.h.
                                                         {
    execution_control_ = scope;
  }
References execution_control_.
set_execution_result()
void v8::internal::interpreter::BytecodeGenerator::set_execution_result (ExpressionResultScope * execution_result) [inline], [private]
Definition at line 555 of file bytecode-generator.h.
                                                                            {
    execution_result_ = execution_result;
  }
References execution_result(), and execution_result_.
Referenced by v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::ExpressionResultScope().
SetVariableInRegister()
void v8::internal::interpreter::BytecodeGenerator::SetVariableInRegister (Variable * var, Register reg) [private]
Definition at line 4468 of file bytecode-generator.cc.
                                                                         {
  BytecodeRegisterOptimizer* optimizer = builder()->GetRegisterOptimizer();
  if (optimizer) {
    optimizer->SetVariableInRegister(var, reg);
  }
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::GetRegisterOptimizer(), and v8::internal::interpreter::BytecodeRegisterOptimizer::SetVariableInRegister().
Referenced by BuildVariableLoad().
StoreKeyedToSuperRuntimeId()
Runtime::FunctionId v8::internal::interpreter::BytecodeGenerator::StoreKeyedToSuperRuntimeId () [inline], [private]
StoreToSuperRuntimeId()
Runtime::FunctionId v8::internal::interpreter::BytecodeGenerator::StoreToSuperRuntimeId () [inline], [private]
ToBooleanModeFromTypeHint()
static constexpr ToBooleanMode v8::internal::interpreter::BytecodeGenerator::ToBooleanModeFromTypeHint (TypeHint type_hint) [inline], [static], [constexpr], [private]
Definition at line 528 of file bytecode-generator.h.
                                                                               {
    return type_hint == TypeHint::kBoolean ? ToBooleanMode::kAlreadyBoolean
                                           : ToBooleanMode::kConvertToBoolean;
  }
References v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, and v8::internal::interpreter::BytecodeArrayBuilder::kConvertToBoolean.
Referenced by VisitForNullishTest(), VisitForTest(), VisitInSameTestExecutionScope(), VisitLogicalAndSubExpression(), VisitLogicalOrSubExpression(), and VisitNot().
top_level_builder()
TopLevelDeclarationsBuilder* v8::internal::interpreter::BytecodeGenerator::top_level_builder () [inline], [private]
Definition at line 563 of file bytecode-generator.h.
                                                   {
    DCHECK_NOT_NULL(top_level_builder_);
    return top_level_builder_;
  }
References DCHECK_NOT_NULL, and top_level_builder_.
Referenced by AllocateDeferredConstants(), BuildDeclareCall(), VisitGlobalDeclarations(), and VisitModuleDeclarations().
VariableNeedsHoleCheckInCurrentBlock()
bool v8::internal::interpreter::BytecodeGenerator::VariableNeedsHoleCheckInCurrentBlock (Variable * variable, HoleCheckMode hole_check_mode) [private]
Definition at line 4694 of file bytecode-generator.cc.
                                                       {
  return hole_check_mode == HoleCheckMode::kRequired &&
         !variable->HasRememberedHoleCheck(hole_check_bitmap_);
}
References hole_check_bitmap_, and v8::internal::kRequired.
Referenced by BuildVariableLoad(), and VariableNeedsHoleCheckInCurrentBlockForAssignment().
VariableNeedsHoleCheckInCurrentBlockForAssignment()
bool v8::internal::interpreter::BytecodeGenerator::VariableNeedsHoleCheckInCurrentBlockForAssignment (Variable * variable, Token::Value op, HoleCheckMode hole_check_mode) [private]
Definition at line 4700 of file bytecode-generator.cc.
                                                                      {
  return VariableNeedsHoleCheckInCurrentBlock(variable, hole_check_mode) ||
         (variable->is_this() && variable->mode() == VariableMode::kConst &&
          op == Token::kInit);
}
References v8::internal::kConst, and VariableNeedsHoleCheckInCurrentBlock().
Referenced by BuildHoleCheckForVariableAssignment(), and BuildVariableAssignment().
VisitAndPushIntoRegisterList()
void v8::internal::interpreter::BytecodeGenerator::VisitAndPushIntoRegisterList (Expression * expr, RegisterList * reg_list) [private]
Definition at line 8532 of file bytecode-generator.cc.
                                                                             {
  {
    ValueResultScope register_scope(this);
    Visit(expr);
  }
  // Grow the register list after visiting the expression to avoid reserving
  // the register across the expression evaluation, which could cause memory
  // leaks for deep expressions due to dead objects being kept alive by pointers
  // in registers.
  Register destination = register_allocator()->GrowRegisterList(reg_list);
  builder()->StoreAccumulatorInRegister(destination);
}
References builder(), v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by VisitArguments().
VisitArguments()
void v8::internal::interpreter::BytecodeGenerator::VisitArguments (const ZonePtrList< Expression > * args, RegisterList * arg_regs) [private]
Definition at line 6511 of file bytecode-generator.cc.
                                                               {
  // Visit arguments.
  builder()->UpdateMaxArguments(static_cast<uint16_t>(args->length()));
  for (int i = 0; i < static_cast<int>(args->length()); i++) {
    VisitAndPushIntoRegisterList(args->at(i), arg_regs);
  }
}
References v8::base::args, builder(), v8::internal::interpreter::BytecodeArrayBuilder::UpdateMaxArguments(), and VisitAndPushIntoRegisterList().
Referenced by VisitCallSuper().
VisitArgumentsObject()
void v8::internal::interpreter::BytecodeGenerator::VisitArgumentsObject (Variable * variable) [private]
Definition at line 8336 of file bytecode-generator.cc.
                                                               {
  if (variable == nullptr) return;
  DCHECK(variable->IsContextSlot() || variable->IsStackAllocated());
  // Allocate and initialize a new arguments object and assign to the
  // {arguments} variable.
  builder()->CreateArguments(closure_scope()->GetArgumentsType());
  BuildVariableAssignment(variable, Token::kAssign, HoleCheckMode::kElided);
}
References builder(), BuildVariableAssignment(), closure_scope(), v8::internal::interpreter::BytecodeArrayBuilder::CreateArguments(), v8::internal::DCHECK(), and v8::internal::kElided.
Referenced by GenerateBodyPrologue().
VisitArithmeticExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression (BinaryOperation * binop) [private]
Definition at line 7558 of file bytecode-generator.cc.
                                                                       {
  FeedbackSlot slot;
  // We special-case string concatenation when the result is used as a property
  // key. In this case, we know it will eventually be internalized and it's
  // better to do so early.
  //
  // For now, we handle only the specialized situation in which one side is a
  // string constant.
  // TODO(jgruber): Generalize. ConsString literals, property-key but no
  // string-literal, string-literal but no property-key.
  const bool maybe_emit_specialized_string_add =
      expr->op() == Token::kAdd && execution_result()->IsValueAsPropertyKey() &&
      v8_flags.cache_property_key_string_adds;
  bool emit_add_string_constant_internalize = false;
  using ASVariant = AddStringConstantAndInternalizeVariant;
  auto as_variant = ASVariant::kLhsIsStringConstant;
  if (maybe_emit_specialized_string_add) {
    // Is lhs a string constant?
    emit_add_string_constant_internalize =
        expr->left()->IsLiteral() && expr->left()->AsLiteral()->IsRawString();
    if (!emit_add_string_constant_internalize) {
      // Is rhs a string constant?
      emit_add_string_constant_internalize =
          expr->right()->IsLiteral() &&
          expr->right()->AsLiteral()->IsRawString();
      if (emit_add_string_constant_internalize) {
        as_variant = ASVariant::kRhsIsStringConstant;
      }
    }
  }
  if (emit_add_string_constant_internalize) {
    slot = feedback_spec()->AddStringAddAndInternalizeICSlot();
  } else {
    slot = feedback_spec()->AddBinaryOpICSlot();
  }
  Expression* subexpr;
  Tagged<Smi> literal;
  if (expr->IsSmiLiteralOperation(&subexpr, &literal)) {
    TypeHint type_hint = VisitForAccumulatorValue(subexpr);
    builder()->SetExpressionPosition(expr);
    builder()->BinaryOperationSmiLiteral(expr->op(), literal,
                                         feedback_index(slot));
    if (expr->op() == Token::kAdd && IsStringTypeHint(type_hint)) {
      execution_result()->SetResultIsString();
    }
  } else {
    TypeHint lhs_type = VisitForAccumulatorValue(expr->left());
    Register lhs = register_allocator()->NewRegister();
    builder()->StoreAccumulatorInRegister(lhs);
    TypeHint rhs_type = VisitForAccumulatorValue(expr->right());
    if (expr->op() == Token::kAdd &&
        (IsStringTypeHint(lhs_type) || IsStringTypeHint(rhs_type))) {
      execution_result()->SetResultIsString();
    }
    if (emit_add_string_constant_internalize) {
      // Subtle: Stack overflows can cause the AST to be visited only
      // partially. Visitation is eventually aborted and the resulting
      // bytecode discarded.
      DCHECK_IMPLIES(
          !HasStackOverflow(),
          IsStringTypeHint(as_variant == ASVariant::kLhsIsStringConstant
                               ? lhs_type
                               : rhs_type));
      builder()->SetExpressionPosition(expr);
      builder()->Add_StringConstant_Internalize(
          expr->op(), lhs, feedback_index(slot), as_variant);
    } else {
      builder()->SetExpressionPosition(expr);
      builder()->BinaryOperation(expr->op(), lhs, feedback_index(slot));
    }
  }
}
References v8::internal::interpreter::BytecodeArrayBuilder::Add_StringConstant_Internalize(), v8::internal::FeedbackVectorSpec::AddBinaryOpICSlot(), v8::internal::FeedbackVectorSpec::AddStringAddAndInternalizeICSlot(), v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperation(), v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperationSmiLiteral(), builder(), DCHECK_IMPLIES, execution_result(), feedback_index(), feedback_spec(), v8::internal::BinaryOperation::IsSmiLiteralOperation(), IsStringTypeHint(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::IsValueAsPropertyKey(), v8::internal::BinaryOperation::left(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::BinaryOperation::op(), register_allocator(), v8::internal::BinaryOperation::right(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsString(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::v8_flags, and VisitForAccumulatorValue().
VisitBlockDeclarationsAndStatements()
void v8::internal::interpreter::BytecodeGenerator::VisitBlockDeclarationsAndStatements (Block * stmt) [private]
Definition at line 2069 of file bytecode-generator.cc.
                                                                       {
  BlockBuilder block_builder(builder(), block_coverage_builder_, stmt);
  ControlScopeForBreakable execution_control(this, stmt, &block_builder);
  if (stmt->scope() != nullptr) {
    VisitDeclarations(stmt->scope()->declarations());
  }
  if (V8_UNLIKELY(stmt->is_breakable())) {
    // Loathsome labeled blocks can be the target of break statements, which
    // causes unconditional blocks to act conditionally, and therefore to
    // require their own elision scope.
    //
    // lbl: {
    // if (cond) break lbl;
    // x;
    // }
    // x; <-- Cannot elide TDZ check
    HoleCheckElisionScope elider(this);
    VisitStatements(stmt->statements());
  } else {
    VisitStatements(stmt->statements());
  }
}
References block_coverage_builder_, builder(), execution_control(), V8_UNLIKELY, VisitDeclarations(), and VisitStatements().
Referenced by BuildInitializationBlockForParametersIfExist(), and VisitBlockMaybeDispose().
VisitBlockMaybeDispose()
void v8::internal::interpreter::BytecodeGenerator::VisitBlockMaybeDispose (Block * stmt) [private]
Definition at line 2058 of file bytecode-generator.cc.
                                                          {
  if (v8_flags.js_explicit_resource_management && stmt->scope() != nullptr &&
      (stmt->scope()->has_using_declaration() ||
       stmt->scope()->has_await_using_declaration())) {
    BuildDisposeScope([&]() { VisitBlockDeclarationsAndStatements(stmt); },
                      stmt->scope()->has_await_using_declaration());
  } else {
    VisitBlockDeclarationsAndStatements(stmt);
  }
}
References BuildDisposeScope(), v8::internal::v8_flags, and VisitBlockDeclarationsAndStatements().
VisitCallSuper()
void v8::internal::interpreter::BytecodeGenerator::VisitCallSuper (Call * call) [private]
Definition at line 6743 of file bytecode-generator.cc.
                                                 {
  RegisterAllocationScope register_scope(this);
  SuperCallReference* super = expr->expression()->AsSuperCallReference();
  const ZonePtrList<Expression>* args = expr->arguments();
  // We compile the super call differently depending on the presence of spreads
  // and their positions.
  //
  // If there is only one spread and it is the final argument, there is a
  // special ConstructWithSpread bytecode.
  //
  // It there is a non-final spread, we rewrite something like
  // super(1, ...x, 2)
  // to
  // %reflect_construct(constructor, [1, ...x, 2], new_target)
  //
  // That is, we implement (non-last-arg) spreads in super calls via our
  // mechanism for spreads in array literals.
  const Call::SpreadPosition spread_position = expr->spread_position();
  // Prepare the constructor to the super call.
  Register this_function = VisitForRegisterValue(super->this_function_var());
  // This register will initially hold the constructor, then afterward it will
  // hold the instance -- the lifetimes of the two don't need to overlap, and
  // this way FindNonDefaultConstructorOrConstruct can choose to write either
  // the instance or the constructor into the same register.
  Register constructor_then_instance = register_allocator()->NewRegister();
  BytecodeLabel super_ctor_call_done;
  if (spread_position == Call::kHasNonFinalSpread) {
    RegisterAllocationScope inner_register_scope(this);
    RegisterList construct_args(constructor_then_instance);
    const Register& constructor = constructor_then_instance;
    // Generate the array containing all arguments.
    BuildCreateArrayLiteral(args, nullptr);
    Register args_array =
        register_allocator()->GrowRegisterList(&construct_args);
    builder()->StoreAccumulatorInRegister(args_array);
    Register new_target =
        register_allocator()->GrowRegisterList(&construct_args);
    VisitForRegisterValue(super->new_target_var(), new_target);
    BuildGetAndCheckSuperConstructor(this_function, new_target, constructor,
                                     &super_ctor_call_done);
    // Now pass that array to %reflect_construct.
    builder()->CallJSRuntime(Context::REFLECT_CONSTRUCT_INDEX, construct_args);
  } else {
    RegisterAllocationScope inner_register_scope(this);
    RegisterList args_regs = register_allocator()->NewGrowableRegisterList();
    VisitArguments(args, &args_regs);
    // The new target is loaded into the new_target register from the
    // {new.target} variable.
    Register new_target = register_allocator()->NewRegister();
    VisitForRegisterValue(super->new_target_var(), new_target);
    const Register& constructor = constructor_then_instance;
    BuildGetAndCheckSuperConstructor(this_function, new_target, constructor,
                                     &super_ctor_call_done);
    builder()->LoadAccumulatorWithRegister(new_target);
    builder()->SetExpressionPosition(expr);
    int feedback_slot_index = feedback_index(feedback_spec()->AddCallICSlot());
    if (spread_position == Call::kHasFinalSpread) {
      builder()->ConstructWithSpread(constructor, args_regs,
                                     feedback_slot_index);
    } else {
      DCHECK_EQ(spread_position, Call::kNoSpread);
      // Call construct.
      // TODO(turbofan): For now we do gather feedback on super constructor
      // calls, utilizing the existing machinery to inline the actual call
      // target and the JSCreate for the implicit receiver allocation. This
      // is not an ideal solution for super constructor calls, but it gets
      // the job done for now. In the long run we might want to revisit this
      // and come up with a better way.
      builder()->Construct(constructor, args_regs, feedback_slot_index);
    }
  }
  // From here onwards, constructor_then_instance will hold the instance.
  const Register& instance = constructor_then_instance;
  builder()->StoreAccumulatorInRegister(instance);
  builder()->Bind(&super_ctor_call_done);
  BuildInstanceInitializationAfterSuperCall(this_function, instance);
  builder()->LoadAccumulatorWithRegister(instance);
}
References v8::base::args, v8::internal::CallBase::arguments(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), BuildCreateArrayLiteral(), builder(), BuildGetAndCheckSuperConstructor(), BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeArrayBuilder::CallJSRuntime(), v8::internal::interpreter::BytecodeArrayBuilder::Construct(), v8::internal::interpreter::BytecodeArrayBuilder::ConstructWithSpread(), DCHECK_EQ, v8::internal::CallBase::expression(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeRegisterAllocator::GrowRegisterList(), v8::internal::CallBase::kHasFinalSpread, v8::internal::CallBase::kHasNonFinalSpread, v8::internal::CallBase::kNoSpread, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::SuperCallReference::new_target_var(), v8::internal::interpreter::BytecodeRegisterAllocator::NewGrowableRegisterList(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::CallBase::spread_position(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::SuperCallReference::this_function_var(), VisitArguments(), and VisitForRegisterValue().
VisitClassLiteral()
void v8::internal::interpreter::BytecodeGenerator::VisitClassLiteral (ClassLiteral * expr, Register name) [private]
Definition at line 3614 of file bytecode-generator.cc.
                                                            {
  VisitClassLiteral(expr, Register::invalid_value());
}
References v8::internal::interpreter::Register::invalid_value().
Referenced by BuildClassProperty().
VisitCommaExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitCommaExpression (BinaryOperation * binop) [private]
Definition at line 7920 of file bytecode-generator.cc.
                                                                   {
  VisitForEffect(binop->left());
  builder()->SetExpressionAsStatementPosition(binop->right());
  Visit(binop->right());
}
References builder(), v8::internal::BinaryOperation::left(), v8::internal::BinaryOperation::right(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionAsStatementPosition(), v8::internal::AstVisitor< BytecodeGenerator >::Visit(), and VisitForEffect().
VisitCondition()
void v8::internal::interpreter::BytecodeGenerator::VisitCondition (Expression * expr) [private]
VisitDeclarations()
void v8::internal::interpreter::BytecodeGenerator::VisitDeclarations (Declaration::List * declarations)
Definition at line 2262 of file bytecode-generator.cc.
                                                                       {
  for (Declaration* decl : *declarations) {
    RegisterAllocationScope register_scope(this);
    Visit(decl);
  }
}
References v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by BuildClassLiteral(), GenerateBodyPrologue(), and VisitBlockDeclarationsAndStatements().
VisitDelete()
void v8::internal::interpreter::BytecodeGenerator::VisitDelete (UnaryOperation * expr) [private]
Definition at line 7083 of file bytecode-generator.cc.
                                                         {
  Expression* expr = unary->expression();
  if (expr->IsProperty()) {
    // Delete of an object property is allowed both in sloppy
    // and strict modes.
    Property* property = expr->AsProperty();
    DCHECK(!property->IsPrivateReference());
    if (property->IsSuperAccess()) {
      // Delete of super access is not allowed.
      VisitForEffect(property->key());
      builder()->CallRuntime(Runtime::kThrowUnsupportedSuperError);
    } else {
      Register object = VisitForRegisterValue(property->obj());
      VisitForAccumulatorValue(property->key());
      builder()->Delete(object, language_mode());
    }
  } else if (expr->IsOptionalChain()) {
    Expression* expr_inner = expr->AsOptionalChain()->expression();
    if (expr_inner->IsProperty()) {
      Property* property = expr_inner->AsProperty();
      DCHECK(!property->IsPrivateReference());
      BytecodeLabel done;
      OptionalChainNullLabelScope label_scope(this);
      VisitForAccumulatorValue(property->obj());
      if (property->is_optional_chain_link()) {
        int right_range = AllocateBlockCoverageSlotIfEnabled(
            property, SourceRangeKind::kRight);
        builder()->JumpIfUndefinedOrNull(label_scope.labels()->New());
        BuildIncrementBlockCoverageCounterIfEnabled(right_range);
      }
      Register object = register_allocator()->NewRegister();
      builder()->StoreAccumulatorInRegister(object);
      if (property->is_optional_chain_link()) {
        VisitInHoleCheckElisionScopeForAccumulatorValue(property->key());
      } else {
        VisitForAccumulatorValue(property->key());
      }
      builder()->Delete(object, language_mode());
      builder()->Jump(&done);
      label_scope.labels()->Bind(builder());
      builder()->LoadTrue();
      builder()->Bind(&done);
    } else {
      VisitForEffect(expr);
      builder()->LoadTrue();
    }
  } else if (expr->IsVariableProxy() &&
             !expr->AsVariableProxy()->is_new_target()) {
    // Delete of an unqualified identifier is allowed in sloppy mode but is
    // not allowed in strict mode.
    DCHECK(is_sloppy(language_mode()));
    Variable* variable = expr->AsVariableProxy()->var();
    switch (variable->location()) {
      case VariableLocation::PARAMETER:
      case VariableLocation::LOCAL:
      case VariableLocation::CONTEXT:
      case VariableLocation::REPL_GLOBAL: {
        // Deleting local var/let/const, context variables, and arguments
        // does not have any effect.
        builder()->LoadFalse();
        break;
      }
      case VariableLocation::UNALLOCATED:
      // TODO(adamk): Falling through to the runtime results in correct
      // behavior, but does unnecessary context-walking (since scope
      // analysis has already proven that the variable doesn't exist in
      // any non-global scope). Consider adding a DeleteGlobal bytecode
      // that knows how to deal with ScriptContexts as well as global
      // object properties.
      case VariableLocation::LOOKUP: {
        Register name_reg = register_allocator()->NewRegister();
        builder()
            ->LoadLiteral(variable->raw_name())
            .StoreAccumulatorInRegister(name_reg)
            .CallRuntime(Runtime::kDeleteLookupSlot, name_reg);
        break;
      }
      case VariableLocation::MODULE:
        // Modules are always in strict mode and unqualified identifiers are not
        // allowed in strict mode.
        UNREACHABLE();
    }
  } else {
    // Delete of an unresolvable reference, new.target, and this returns true.
    VisitForEffect(expr);
    builder()->LoadTrue();
  }
}
References AllocateBlockCoverageSlotIfEnabled(), v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::CONTEXT, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayBuilder::Delete(), v8::internal::UnaryOperation::expression(), v8::internal::Property::is_optional_chain_link(), v8::internal::is_sloppy(), v8::internal::Property::IsPrivateReference(), v8::internal::Property::IsSuperAccess(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::Property::key(), v8::internal::kRight, v8::internal::interpreter::BytecodeGenerator::OptionalChainNullLabelScope::labels(), language_mode(), v8::internal::interpreter::BytecodeArrayBuilder::LoadFalse(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTrue(), v8::internal::LOCAL, v8::internal::LOOKUP, v8::internal::MODULE, v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::Property::obj(), v8::internal::PARAMETER, register_allocator(), v8::internal::REPL_GLOBAL, v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::UNALLOCATED, v8::internal::UNREACHABLE(), VisitForAccumulatorValue(), VisitForEffect(), VisitForRegisterValue(), and VisitInHoleCheckElisionScopeForAccumulatorValue().
VisitForAccumulatorValue()
BytecodeGenerator::TypeHint v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValue (Expression * expr) [private]
Definition at line 8473 of file bytecode-generator.cc.
                      {
  ValueResultScope accumulator_scope(this);
  return VisitForAccumulatorValueImpl(expr, &accumulator_scope);
}
References VisitForAccumulatorValueImpl().
Referenced by BuildClassLiteral(), BuildClassProperty(), BuildCreateArrayLiteral(), BuildDestructuringObjectAssignment(), BuildLoadPropertyKey(), BuildPrivateMethodIn(), VisitArithmeticExpression(), VisitDelete(), VisitForAccumulatorValueOrTheHole(), VisitForNullishTest(), VisitForRegisterValue(), VisitForTypeOfValue(), VisitInHoleCheckElisionScopeForAccumulatorValue(), VisitLogicalAndSubExpression(), VisitLogicalOrSubExpression(), VisitNaryArithmeticExpression(), VisitNaryLogicalAndExpression(), VisitNaryLogicalOrExpression(), VisitNaryNullishExpression(), VisitNot(), VisitNullishSubExpression(), and VisitPropertyLoad().
VisitForAccumulatorValueAsPropertyKey()
BytecodeGenerator::TypeHint v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueAsPropertyKey (Expression * expr) [private]
Definition at line 8480 of file bytecode-generator.cc.
                                                                         {
  ValueResultScope accumulator_scope(this,
                                     ValueResultScope::kValueAsPropertyKey);
  return VisitForAccumulatorValueImpl(expr, &accumulator_scope);
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::kValueAsPropertyKey, and VisitForAccumulatorValueImpl().
Referenced by VisitPropertyLoad().
VisitForAccumulatorValueImpl()
BytecodeGenerator::TypeHint v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueImpl (Expression * expr, ValueResultScope * accumulator_scope) [private]
Definition at line 8486 of file bytecode-generator.cc.
                                                           {
  Visit(expr);
  // Record the type hint for the result of current expression in accumulator.
  const TypeHint type_hint = accumulator_scope->type_hint();
  BytecodeRegisterOptimizer* optimizer = builder()->GetRegisterOptimizer();
  if (optimizer && type_hint != TypeHint::kUnknown) {
    optimizer->SetTypeHintForAccumulator(type_hint);
  }
  return type_hint;
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::GetRegisterOptimizer(), v8::internal::interpreter::BytecodeRegisterOptimizer::SetTypeHintForAccumulator(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::type_hint(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by VisitForAccumulatorValue(), and VisitForAccumulatorValueAsPropertyKey().
VisitForAccumulatorValueOrTheHole()
void v8::internal::interpreter::BytecodeGenerator::VisitForAccumulatorValueOrTheHole (Expression * expr) [private]
Definition at line 8498 of file bytecode-generator.cc.
                                                                          {
  if (expr == nullptr) {
    builder()->LoadTheHole();
  } else {
    VisitForAccumulatorValue(expr);
  }
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::LoadTheHole(), and VisitForAccumulatorValue().
Referenced by BuildClassLiteral().
VisitForEffect()
void v8::internal::interpreter::BytecodeGenerator::VisitForEffect (Expression * expr) [private]
Definition at line 8507 of file bytecode-generator.cc.
                                                       {
  EffectResultScope effect_scope(this);
  Visit(expr);
}
References v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by VisitCommaExpression(), VisitDelete(), VisitNaryCommaExpression(), VisitNot(), and VisitVoid().
VisitForInAssignment()
void v8::internal::interpreter::BytecodeGenerator::VisitForInAssignment (Expression * expr) [private]
VisitForNullishTest()
void v8::internal::interpreter::BytecodeGenerator::VisitForNullishTest (Expression * expr, BytecodeLabels * then_labels, BytecodeLabels * test_next_labels, BytecodeLabels * else_labels) [private]
Definition at line 8594 of file bytecode-generator.cc.
                                                                         {
  // Nullish short circuits on undefined or null, otherwise we fall back to
  // BuildTest with no fallthrough.
  // TODO(joshualitt): We should do this in a TestResultScope.
  TypeHint type_hint = VisitForAccumulatorValue(expr);
  ToBooleanMode mode = ToBooleanModeFromTypeHint(type_hint);
  // Skip the nullish shortcircuit if we already have a boolean.
  if (mode != ToBooleanMode::kAlreadyBoolean) {
    builder()->JumpIfUndefinedOrNull(test_next_labels->New());
  }
  BuildTest(mode, then_labels, else_labels, TestFallthrough::kNone);
}
References builder(), BuildTest(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::interpreter::BytecodeArrayBuilder::kAlreadyBoolean, kNone, mode(), v8::internal::interpreter::BytecodeLabels::New(), ToBooleanModeFromTypeHint(), and VisitForAccumulatorValue().
Referenced by VisitLogicalTestSubExpression().
VisitForRegisterValue() [1/2]
Register v8::internal::interpreter::BytecodeGenerator::VisitForRegisterValue (Expression * expr) [private]
Definition at line 8514 of file bytecode-generator.cc.
                                                                  {
  VisitForAccumulatorValue(expr);
  Register result = register_allocator()->NewRegister();
  builder()->StoreAccumulatorInRegister(result);
  return result;
}
References builder(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), v8::base::internal::result, v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and VisitForAccumulatorValue().
Referenced by BuildClassLiteral(), BuildClassProperty(), BuildDestructuringObjectAssignment(), PrepareAssignmentLhs(), VisitCallSuper(), VisitDelete(), VisitKeyedSuperPropertyLoad(), VisitLiteralAccessor(), and VisitPropertyLoad().
VisitForRegisterValue() [2/2]
void v8::internal::interpreter::BytecodeGenerator::VisitForRegisterValue (Expression * expr, Register destination) [inline], [private]
Definition at line 8523 of file bytecode-generator.cc.
                                                                    {
  ValueResultScope register_scope(this);
  Visit(expr);
  builder()->StoreAccumulatorInRegister(destination);
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
VisitForTest()
void v8::internal::interpreter::BytecodeGenerator::VisitForTest (Expression * expr, BytecodeLabels * then_labels, BytecodeLabels * else_labels, TestFallthrough fallthrough) [private]
Definition at line 8566 of file bytecode-generator.cc.
                                                                  {
  bool result_consumed;
  TypeHint type_hint;
  {
    // To make sure that all temporary registers are returned before generating
    // jumps below, we ensure that the result scope is deleted before doing so.
    // Dead registers might be materialized otherwise.
    TestResultScope test_result(this, then_labels, else_labels, fallthrough);
    Visit(expr);
    result_consumed = test_result.result_consumed_by_test();
    type_hint = test_result.type_hint();
    // Labels and fallthrough might have been mutated, so update based on
    // TestResultScope.
    then_labels = test_result.then_labels();
    else_labels = test_result.else_labels();
    fallthrough = test_result.fallthrough();
  }
  if (!result_consumed) {
    BuildTest(ToBooleanModeFromTypeHint(type_hint), then_labels, else_labels,
              fallthrough);
  }
}
References BuildTest(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::else_labels(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::result_consumed_by_test(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::then_labels(), ToBooleanModeFromTypeHint(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::type_hint(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by VisitLogicalTest(), VisitLogicalTestSubExpression(), and VisitNaryLogicalTest().
VisitForTypeOfValue()
void v8::internal::interpreter::BytecodeGenerator::VisitForTypeOfValue (Expression * expr) [private]
Definition at line 7012 of file bytecode-generator.cc.
                                                            {
  if (expr->IsVariableProxy()) {
    // Typeof does not throw a reference error on global variables, hence we
    // perform a non-contextual load in case the operand is a variable proxy.
    VariableProxy* proxy = expr->AsVariableProxy();
    BuildVariableLoadForAccumulatorValue(proxy->var(), proxy->hole_check_mode(),
                                         TypeofMode::kInside);
  } else {
    VisitForAccumulatorValue(expr);
  }
}
References BuildVariableLoadForAccumulatorValue(), v8::internal::VariableProxy::hole_check_mode(), v8::internal::kInside, v8::internal::VariableProxy::var(), and VisitForAccumulatorValue().
Referenced by VisitTypeOf().
VisitGlobalDeclarations()
void v8::internal::interpreter::BytecodeGenerator::VisitGlobalDeclarations (Declaration::List * declarations)
Definition at line 2238 of file bytecode-generator.cc.
                                                                      {
  RegisterAllocationScope register_scope(this);
  for (Declaration* decl : *decls) {
    Variable* var = decl->var();
    DCHECK(var->is_used());
    if (var->location() == VariableLocation::UNALLOCATED) {
      // var or function.
      if (decl->IsFunctionDeclaration()) {
        top_level_builder()->record_global_function_declaration();
        FunctionDeclaration* f = static_cast<FunctionDeclaration*>(decl);
        AddToEagerLiteralsIfEager(f->fun());
      } else {
        top_level_builder()->record_global_variable_declaration();
      }
    } else {
      // let or const. Handled in NewScriptContext.
      DCHECK(decl->IsVariableDeclaration());
      DCHECK(IsLexicalVariableMode(var->mode()));
    }
  }
  BuildDeclareCall(Runtime::kDeclareGlobals);
}
References AddToEagerLiteralsIfEager(), BuildDeclareCall(), v8::internal::DCHECK(), v8::internal::FunctionDeclaration::fun(), v8::internal::IsLexicalVariableMode(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_global_function_declaration(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_global_variable_declaration(), top_level_builder(), and v8::internal::UNALLOCATED.
Referenced by GenerateBodyPrologue().
VisitInHoleCheckElisionScope()
template<typename T >
void v8::internal::interpreter::BytecodeGenerator::VisitInHoleCheckElisionScope (T * node) [private]
Definition at line 8634 of file bytecode-generator.cc.
                                                            {
  HoleCheckElisionScope elider(this);
  Visit(node);
}
References v8::internal::AstVisitor< BytecodeGenerator >::Visit().
VisitInHoleCheckElisionScopeForAccumulatorValue()
BytecodeGenerator::TypeHint v8::internal::interpreter::BytecodeGenerator::VisitInHoleCheckElisionScopeForAccumulatorValue (Expression * expr) [private]
Definition at line 8640 of file bytecode-generator.cc.
                      {
  HoleCheckElisionScope elider(this);
  return VisitForAccumulatorValue(expr);
}
References VisitForAccumulatorValue().
Referenced by BuildDestructuringArrayAssignment(), BuildDestructuringObjectAssignment(), VisitDelete(), VisitLogicalAndExpression(), VisitLogicalOrExpression(), and VisitNullishExpression().
VisitInSameTestExecutionScope()
void v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope (Expression * expr) [private]
Definition at line 8611 of file bytecode-generator.cc.
                                                                      {
  DCHECK(execution_result()->IsTest());
  {
    RegisterAllocationScope reg_scope(this);
    Visit(expr);
  }
  if (!execution_result()->AsTest()->result_consumed_by_test()) {
    TestResultScope* result_scope = execution_result()->AsTest();
    BuildTest(ToBooleanModeFromTypeHint(result_scope->type_hint()),
              result_scope->then_labels(), result_scope->else_labels(),
              result_scope->fallthrough());
    result_scope->SetResultConsumedByTest();
  }
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), BuildTest(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::else_labels(), execution_result(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::then_labels(), ToBooleanModeFromTypeHint(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::type_hint(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by VisitNot().
VisitInScope()
void v8::internal::interpreter::BytecodeGenerator::VisitInScope (Statement * stmt, Scope * scope) [private]
Definition at line 8626 of file bytecode-generator.cc.
                                                                  {
  DCHECK(scope->declarations()->is_empty());
  CurrentScope current_scope(this, scope);
  ContextScope context_scope(this, scope);
  Visit(stmt);
}
References current_scope(), v8::internal::DCHECK(), v8::internal::Scope::declarations(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
VisitIterationBody()
void v8::internal::interpreter::BytecodeGenerator::VisitIterationBody (IterationStatement * stmt, LoopBuilder * loop_builder) [private]
Definition at line 2936 of file bytecode-generator.cc.
                                                                      {
  loop_builder->LoopBody();
  ControlScopeForIteration execution_control(this, stmt, loop_builder);
  Visit(stmt->body());
  loop_builder->BindContinueTarget();
}
References v8::internal::interpreter::LoopBuilder::BindContinueTarget(), v8::internal::IterationStatement::body(), execution_control(), v8::internal::interpreter::LoopBuilder::LoopBody(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by VisitIterationBodyInHoleCheckElisionScope().
VisitIterationBodyInHoleCheckElisionScope()
void v8::internal::interpreter::BytecodeGenerator::VisitIterationBodyInHoleCheckElisionScope (IterationStatement * stmt, LoopBuilder * loop_builder) [private]
Definition at line 2944 of file bytecode-generator.cc.
                                                         {
  HoleCheckElisionScope elider(this);
  VisitIterationBody(stmt, loop_builder);
}
References VisitIterationBody().
VisitKeyedSuperPropertyLoad()
void v8::internal::interpreter::BytecodeGenerator::VisitKeyedSuperPropertyLoad (Property * property, Register opt_receiver_out) [private]
Definition at line 6462 of file bytecode-generator.cc.
                                                                               {
  RegisterAllocationScope register_scope(this);
  RegisterList args = register_allocator()->NewRegisterList(3);
  BuildThisVariableLoad();
  builder()->StoreAccumulatorInRegister(args[0]);
  BuildVariableLoad(
      property->obj()->AsSuperPropertyReference()->home_object()->var(),
      HoleCheckMode::kElided);
  builder()->StoreAccumulatorInRegister(args[1]);
  VisitForRegisterValue(property->key(), args[2]);
  builder()->SetExpressionPosition(property);
  builder()->CallRuntime(Runtime::kLoadKeyedFromSuper, args);
  if (opt_receiver_out.is_valid()) {
    builder()->MoveRegister(args[0], opt_receiver_out);
  }
}
References v8::base::args, builder(), BuildThisVariableLoad(), BuildVariableLoad(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::interpreter::Register::is_valid(), v8::internal::kElided, v8::internal::Property::key(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::Property::obj(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and VisitForRegisterValue().
Referenced by VisitPropertyLoad().
VisitLiteralAccessor()
void v8::internal::interpreter::BytecodeGenerator::VisitLiteralAccessor (LiteralProperty * property, Register value_out) [private]
Definition at line 8327 of file bytecode-generator.cc.
                                                                 {
  if (property == nullptr) {
    builder()->LoadNull().StoreAccumulatorInRegister(value_out);
  } else {
    VisitForRegisterValue(property->value(), value_out);
  }
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNull(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::LiteralProperty::value(), and VisitForRegisterValue().
Referenced by BuildClassLiteral().
VisitLogicalAndExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression (BinaryOperation * binop) [private]
Definition at line 8121 of file bytecode-generator.cc.
                                                                        {
  Expression* left = binop->left();
  Expression* right = binop->right();
  int right_coverage_slot =
      AllocateBlockCoverageSlotIfEnabled(binop, SourceRangeKind::kRight);
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    if (left->ToBooleanIsFalse()) {
      builder()->Jump(test_result->NewElseLabel());
    } else if (left->ToBooleanIsTrue() && right->ToBooleanIsTrue()) {
      BuildIncrementBlockCoverageCounterIfEnabled(right_coverage_slot);
      builder()->Jump(test_result->NewThenLabel());
    } else {
      VisitLogicalTest(Token::kAnd, left, right, right_coverage_slot);
    }
    test_result->SetResultConsumedByTest();
  } else {
    BytecodeLabels end_labels(zone());
    if (VisitLogicalAndSubExpression(left, &end_labels, right_coverage_slot)) {
      return;
    }
    VisitInHoleCheckElisionScopeForAccumulatorValue(right);
    end_labels.Bind(builder());
  }
}
References AllocateBlockCoverageSlotIfEnabled(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), execution_result(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::kRight, v8::internal::BinaryOperation::left(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewElseLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel(), v8::internal::BinaryOperation::right(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::Expression::ToBooleanIsFalse(), v8::internal::Expression::ToBooleanIsTrue(), VisitInHoleCheckElisionScopeForAccumulatorValue(), VisitLogicalAndSubExpression(), VisitLogicalTest(), and zone().
VisitLogicalAndSubExpression()
bool v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndSubExpression (Expression * expr, BytecodeLabels * end_labels, int coverage_slot) [private]
Definition at line 8019 of file bytecode-generator.cc.
                                                                        {
  if (expr->ToBooleanIsFalse()) {
    VisitForAccumulatorValue(expr);
    end_labels->Bind(builder());
    return true;
  } else if (!expr->ToBooleanIsTrue()) {
    TypeHint type_hint = VisitForAccumulatorValue(expr);
    builder()->JumpIfFalse(ToBooleanModeFromTypeHint(type_hint),
                           end_labels->New());
  }
  BuildIncrementBlockCoverageCounterIfEnabled(coverage_slot);
  return false;
}
References v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfFalse(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::Expression::ToBooleanIsFalse(), v8::internal::Expression::ToBooleanIsTrue(), ToBooleanModeFromTypeHint(), and VisitForAccumulatorValue().
Referenced by VisitLogicalAndExpression(), and VisitNaryLogicalAndExpression().
VisitLogicalOrExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression (BinaryOperation * binop) [private]
Definition at line 8058 of file bytecode-generator.cc.
                                                                       {
  Expression* left = binop->left();
  Expression* right = binop->right();
  int right_coverage_slot =
      AllocateBlockCoverageSlotIfEnabled(binop, SourceRangeKind::kRight);
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    if (left->ToBooleanIsTrue()) {
      builder()->Jump(test_result->NewThenLabel());
    } else if (left->ToBooleanIsFalse() && right->ToBooleanIsFalse()) {
      BuildIncrementBlockCoverageCounterIfEnabled(right_coverage_slot);
      builder()->Jump(test_result->NewElseLabel());
    } else {
      VisitLogicalTest(Token::kOr, left, right, right_coverage_slot);
    }
    test_result->SetResultConsumedByTest();
  } else {
    BytecodeLabels end_labels(zone());
    if (VisitLogicalOrSubExpression(left, &end_labels, right_coverage_slot)) {
      return;
    }
    VisitInHoleCheckElisionScopeForAccumulatorValue(right);
    end_labels.Bind(builder());
  }
}
References AllocateBlockCoverageSlotIfEnabled(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), execution_result(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::kRight, v8::internal::BinaryOperation::left(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewElseLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel(), v8::internal::BinaryOperation::right(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::Expression::ToBooleanIsFalse(), v8::internal::Expression::ToBooleanIsTrue(), VisitInHoleCheckElisionScopeForAccumulatorValue(), VisitLogicalOrSubExpression(), VisitLogicalTest(), and zone().
VisitLogicalOrSubExpression()
bool v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrSubExpression (Expression * expr, BytecodeLabels * end_labels, int coverage_slot) [private]
Definition at line 8001 of file bytecode-generator.cc.
                                                                       {
  if (expr->ToBooleanIsTrue()) {
    VisitForAccumulatorValue(expr);
    end_labels->Bind(builder());
    return true;
  } else if (!expr->ToBooleanIsFalse()) {
    TypeHint type_hint = VisitForAccumulatorValue(expr);
    builder()->JumpIfTrue(ToBooleanModeFromTypeHint(type_hint),
                          end_labels->New());
  }
  BuildIncrementBlockCoverageCounterIfEnabled(coverage_slot);
  return false;
}
References v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfTrue(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::Expression::ToBooleanIsFalse(), v8::internal::Expression::ToBooleanIsTrue(), ToBooleanModeFromTypeHint(), and VisitForAccumulatorValue().
Referenced by VisitLogicalOrExpression(), and VisitNaryLogicalOrExpression().
VisitLogicalTest()
void v8::internal::interpreter::BytecodeGenerator::VisitLogicalTest (Token::Value token, Expression * left, Expression * right, int right_coverage_slot) [private]
Definition at line 7959 of file bytecode-generator.cc.
                                                                  {
  DCHECK(token == Token::kOr || token == Token::kAnd ||
         token == Token::kNullish);
  TestResultScope* test_result = execution_result()->AsTest();
  BytecodeLabels* then_labels = test_result->then_labels();
  BytecodeLabels* else_labels = test_result->else_labels();
  TestFallthrough fallthrough = test_result->fallthrough();
  VisitLogicalTestSubExpression(token, left, then_labels, else_labels,
                                right_coverage_slot);
  // The last test has the same then, else and fallthrough as the parent test.
  HoleCheckElisionScope elider(this);
  VisitForTest(right, then_labels, else_labels, fallthrough);
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::DCHECK(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::else_labels(), execution_result(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::then_labels(), VisitForTest(), and VisitLogicalTestSubExpression().
Referenced by VisitLogicalAndExpression(), VisitLogicalOrExpression(), and VisitNullishExpression().
VisitLogicalTestSubExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitLogicalTestSubExpression (Token::Value token, Expression * expr, BytecodeLabels * then_labels, BytecodeLabels * else_labels, int coverage_slot) [private]
Definition at line 7939 of file bytecode-generator.cc.
                                                    {
  DCHECK(token == Token::kOr || token == Token::kAnd ||
         token == Token::kNullish);
  BytecodeLabels test_next(zone());
  if (token == Token::kOr) {
    VisitForTest(expr, then_labels, &test_next, TestFallthrough::kElse);
  } else if (token == Token::kAnd) {
    VisitForTest(expr, &test_next, else_labels, TestFallthrough::kThen);
  } else {
    DCHECK_EQ(Token::kNullish, token);
    VisitForNullishTest(expr, then_labels, &test_next, else_labels);
  }
  test_next.Bind(builder());
  BuildIncrementBlockCoverageCounterIfEnabled(coverage_slot);
}
References v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::DCHECK(), DCHECK_EQ, kElse, kThen, VisitForNullishTest(), VisitForTest(), and zone().
Referenced by VisitLogicalTest(), and VisitNaryLogicalTest().
VisitModuleDeclarations()
void v8::internal::interpreter::BytecodeGenerator::VisitModuleDeclarations (Declaration::List * declarations)
Definition at line 2215 of file bytecode-generator.cc.
                                                                      {
  RegisterAllocationScope register_scope(this);
  for (Declaration* decl : *decls) {
    Variable* var = decl->var();
    if (!var->is_used()) continue;
    if (var->location() == VariableLocation::MODULE) {
      if (decl->IsFunctionDeclaration()) {
        DCHECK(var->IsExport());
        FunctionDeclaration* f = static_cast<FunctionDeclaration*>(decl);
        AddToEagerLiteralsIfEager(f->fun());
        top_level_builder()->record_module_function_declaration();
      } else if (var->IsExport() && var->binding_needs_init()) {
        DCHECK(decl->IsVariableDeclaration());
        top_level_builder()->record_module_variable_declaration();
      }
    } else {
      RegisterAllocationScope inner_register_scope(this);
      Visit(decl);
    }
  }
  BuildDeclareCall(Runtime::kDeclareModuleExports);
}
References AddToEagerLiteralsIfEager(), BuildDeclareCall(), v8::internal::DCHECK(), v8::internal::FunctionDeclaration::fun(), v8::internal::MODULE, v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_module_function_declaration(), v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_module_variable_declaration(), top_level_builder(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by GenerateBodyPrologue().
VisitModuleNamespaceImports()
void v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports () [private]
Definition at line 2179 of file bytecode-generator.cc.
                                                    {
  if (!closure_scope()->is_module_scope()) return;
  RegisterAllocationScope register_scope(this);
  Register module_request = register_allocator()->NewRegister();
  SourceTextModuleDescriptor* descriptor =
      closure_scope()->AsModuleScope()->module();
  for (auto entry : descriptor->namespace_imports()) {
    builder()
        ->LoadLiteral(Smi::FromInt(entry->module_request))
        .StoreAccumulatorInRegister(module_request)
        .CallRuntime(Runtime::kGetModuleNamespace, module_request);
    Variable* var = closure_scope()->LookupInModule(entry->local_name);
    BuildVariableAssignment(var, Token::kInit, HoleCheckMode::kElided);
  }
}
References v8::internal::Scope::AsModuleScope(), builder(), BuildVariableAssignment(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), closure_scope(), v8::internal::Smi::FromInt(), v8::internal::kElided, v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::DeclarationScope::LookupInModule(), v8::internal::ModuleScope::module(), v8::internal::SourceTextModuleDescriptor::namespace_imports(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Referenced by GenerateBodyPrologue().
VisitNamedSuperPropertyLoad()
void v8::internal::interpreter::BytecodeGenerator::VisitNamedSuperPropertyLoad (Property * property, Register opt_receiver_out) [private]
Definition at line 6425 of file bytecode-generator.cc.
                                                                               {
  RegisterAllocationScope register_scope(this);
  if (v8_flags.super_ic) {
    Register receiver = register_allocator()->NewRegister();
    BuildThisVariableLoad();
    builder()->StoreAccumulatorInRegister(receiver);
    BuildVariableLoad(
        property->obj()->AsSuperPropertyReference()->home_object()->var(),
        HoleCheckMode::kElided);
    builder()->SetExpressionPosition(property);
    auto name = property->key()->AsLiteral()->AsRawPropertyName();
    FeedbackSlot slot = GetCachedLoadSuperICSlot(name);
    builder()->LoadNamedPropertyFromSuper(receiver, name, feedback_index(slot));
    if (opt_receiver_out.is_valid()) {
      builder()->MoveRegister(receiver, opt_receiver_out);
    }
  } else {
    RegisterList args = register_allocator()->NewRegisterList(3);
    BuildThisVariableLoad();
    builder()->StoreAccumulatorInRegister(args[0]);
    BuildVariableLoad(
        property->obj()->AsSuperPropertyReference()->home_object()->var(),
        HoleCheckMode::kElided);
    builder()->StoreAccumulatorInRegister(args[1]);
    builder()->SetExpressionPosition(property);
    builder()
        ->LoadLiteral(property->key()->AsLiteral()->AsRawPropertyName())
        .StoreAccumulatorInRegister(args[2])
        .CallRuntime(Runtime::kLoadFromSuper, args);
    if (opt_receiver_out.is_valid()) {
      builder()->MoveRegister(args[0], opt_receiver_out);
    }
  }
}
References v8::base::args, builder(), BuildThisVariableLoad(), BuildVariableLoad(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), feedback_index(), GetCachedLoadSuperICSlot(), v8::internal::interpreter::Register::is_valid(), v8::internal::kElided, v8::internal::Property::key(), v8::internal::interpreter::BytecodeArrayBuilder::LoadLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::LoadNamedPropertyFromSuper(), v8::internal::interpreter::BytecodeArrayBuilder::MoveRegister(), v8::internal::name, v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegisterList(), v8::internal::Property::obj(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and v8::internal::v8_flags.
Referenced by VisitPropertyLoad().
VisitNaryArithmeticExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression (NaryOperation * expr) [private]
Definition at line 7635 of file bytecode-generator.cc.
                                                                         {
  // TODO(leszeks): Add support for lhs smi in commutative ops.
  TypeHint type_hint = VisitForAccumulatorValue(expr->first());
  for (size_t i = 0; i < expr->subsequent_length(); ++i) {
    RegisterAllocationScope register_scope(this);
    if (expr->subsequent(i)->IsSmiLiteral()) {
      builder()->SetExpressionPosition(expr->subsequent_op_position(i));
      builder()->BinaryOperationSmiLiteral(
          expr->op(), expr->subsequent(i)->AsLiteral()->AsSmiLiteral(),
          feedback_index(feedback_spec()->AddBinaryOpICSlot()));
    } else {
      Register lhs = register_allocator()->NewRegister();
      builder()->StoreAccumulatorInRegister(lhs);
      TypeHint rhs_hint = VisitForAccumulatorValue(expr->subsequent(i));
      if (IsStringTypeHint(rhs_hint)) type_hint = TypeHint::kString;
      builder()->SetExpressionPosition(expr->subsequent_op_position(i));
      builder()->BinaryOperation(
          expr->op(), lhs,
          feedback_index(feedback_spec()->AddBinaryOpICSlot()));
    }
  }
  if (IsStringTypeHint(type_hint) && expr->op() == Token::kAdd) {
    // If any operand of an ADD is a String, a String is produced.
    execution_result()->SetResultIsString();
  }
}
References v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperation(), v8::internal::interpreter::BytecodeArrayBuilder::BinaryOperationSmiLiteral(), builder(), execution_result(), feedback_index(), feedback_spec(), v8::internal::NaryOperation::first(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Expression::IsSmiLiteral(), IsStringTypeHint(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::NaryOperation::op(), register_allocator(), v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsString(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::NaryOperation::subsequent_op_position(), and VisitForAccumulatorValue().
VisitNaryCommaExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitNaryCommaExpression (NaryOperation * expr) [private]
Definition at line 7926 of file bytecode-generator.cc.
                                                                    {
  DCHECK_GT(expr->subsequent_length(), 0);
  VisitForEffect(expr->first());
  for (size_t i = 0; i < expr->subsequent_length() - 1; ++i) {
    builder()->SetExpressionAsStatementPosition(expr->subsequent(i));
    VisitForEffect(expr->subsequent(i));
  }
  builder()->SetExpressionAsStatementPosition(
      expr->subsequent(expr->subsequent_length() - 1));
  Visit(expr->subsequent(expr->subsequent_length() - 1));
}
References builder(), DCHECK_GT, v8::internal::NaryOperation::first(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionAsStatementPosition(), v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::AstVisitor< BytecodeGenerator >::Visit(), and VisitForEffect().
VisitNaryLogicalAndExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression (NaryOperation * expr) [private]
Definition at line 8149 of file bytecode-generator.cc.
                                                                         {
  Expression* first = expr->first();
  DCHECK_GT(expr->subsequent_length(), 0);
  NaryCodeCoverageSlots coverage_slots(this, expr);
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    if (first->ToBooleanIsFalse()) {
      builder()->Jump(test_result->NewElseLabel());
    } else {
      VisitNaryLogicalTest(Token::kAnd, expr, &coverage_slots);
    }
    test_result->SetResultConsumedByTest();
  } else {
    BytecodeLabels end_labels(zone());
    if (VisitLogicalAndSubExpression(first, &end_labels,
                                     coverage_slots.GetSlotFor(0))) {
      return;
    }
    HoleCheckElisionScope elider(this);
    for (size_t i = 0; i < expr->subsequent_length() - 1; ++i) {
      if (VisitLogicalAndSubExpression(expr->subsequent(i), &end_labels,
                                       coverage_slots.GetSlotFor(i + 1))) {
        return;
      }
    }
    // We have to visit the last value even if it's false, because we need its
    // actual value.
    VisitForAccumulatorValue(expr->subsequent(expr->subsequent_length() - 1));
    end_labels.Bind(builder());
  }
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::interpreter::BytecodeLabels::Bind(), builder(), DCHECK_GT, execution_result(), v8::internal::NaryOperation::first(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewElseLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::Expression::ToBooleanIsFalse(), VisitForAccumulatorValue(), VisitLogicalAndSubExpression(), VisitNaryLogicalTest(), and zone().
VisitNaryLogicalOrExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression (NaryOperation * expr) [private]
Definition at line 8086 of file bytecode-generator.cc.
                                                                        {
  Expression* first = expr->first();
  DCHECK_GT(expr->subsequent_length(), 0);
  NaryCodeCoverageSlots coverage_slots(this, expr);
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    if (first->ToBooleanIsTrue()) {
      builder()->Jump(test_result->NewThenLabel());
    } else {
      VisitNaryLogicalTest(Token::kOr, expr, &coverage_slots);
    }
    test_result->SetResultConsumedByTest();
  } else {
    BytecodeLabels end_labels(zone());
    if (VisitLogicalOrSubExpression(first, &end_labels,
                                    coverage_slots.GetSlotFor(0))) {
      return;
    }
    HoleCheckElisionScope elider(this);
    for (size_t i = 0; i < expr->subsequent_length() - 1; ++i) {
      if (VisitLogicalOrSubExpression(expr->subsequent(i), &end_labels,
                                      coverage_slots.GetSlotFor(i + 1))) {
        return;
      }
    }
    // We have to visit the last value even if it's true, because we need its
    // actual value.
    VisitForAccumulatorValue(expr->subsequent(expr->subsequent_length() - 1));
    end_labels.Bind(builder());
  }
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::interpreter::BytecodeLabels::Bind(), builder(), DCHECK_GT, execution_result(), v8::internal::NaryOperation::first(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::Expression::ToBooleanIsTrue(), VisitForAccumulatorValue(), VisitLogicalOrSubExpression(), VisitNaryLogicalTest(), and zone().
VisitNaryLogicalTest()
void v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest (Token::Value token, NaryOperation * expr, const NaryCodeCoverageSlots * coverage_slots) [private]
Definition at line 7976 of file bytecode-generator.cc.
                                                 {
  DCHECK(token == Token::kOr || token == Token::kAnd ||
         token == Token::kNullish);
  DCHECK_GT(expr->subsequent_length(), 0);
  TestResultScope* test_result = execution_result()->AsTest();
  BytecodeLabels* then_labels = test_result->then_labels();
  BytecodeLabels* else_labels = test_result->else_labels();
  TestFallthrough fallthrough = test_result->fallthrough();
  VisitLogicalTestSubExpression(token, expr->first(), then_labels, else_labels,
                                coverage_slots->GetSlotFor(0));
  HoleCheckElisionScope elider(this);
  for (size_t i = 0; i < expr->subsequent_length() - 1; ++i) {
    VisitLogicalTestSubExpression(token, expr->subsequent(i), then_labels,
                                  else_labels,
                                  coverage_slots->GetSlotFor(i + 1));
  }
  // The last test has the same then, else and fallthrough as the parent test.
  VisitForTest(expr->subsequent(expr->subsequent_length() - 1), then_labels,
               else_labels, fallthrough);
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::interpreter::BytecodeGenerator::TestResultScope::else_labels(), execution_result(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough(), v8::internal::NaryOperation::first(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::then_labels(), VisitForTest(), and VisitLogicalTestSubExpression().
Referenced by VisitNaryLogicalAndExpression(), VisitNaryLogicalOrExpression(), and VisitNaryNullishExpression().
VisitNaryNullishExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression (NaryOperation * expr) [private]
Definition at line 8212 of file bytecode-generator.cc.
                                                                      {
  Expression* first = expr->first();
  DCHECK_GT(expr->subsequent_length(), 0);
  NaryCodeCoverageSlots coverage_slots(this, expr);
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    if (first->IsLiteralButNotNullOrUndefined() && first->ToBooleanIsTrue()) {
      builder()->Jump(test_result->NewThenLabel());
    } else {
      VisitNaryLogicalTest(Token::kNullish, expr, &coverage_slots);
    }
    test_result->SetResultConsumedByTest();
  } else {
    BytecodeLabels end_labels(zone());
    if (VisitNullishSubExpression(first, &end_labels,
                                  coverage_slots.GetSlotFor(0))) {
      return;
    }
    HoleCheckElisionScope elider(this);
    for (size_t i = 0; i < expr->subsequent_length() - 1; ++i) {
      if (VisitNullishSubExpression(expr->subsequent(i), &end_labels,
                                    coverage_slots.GetSlotFor(i + 1))) {
        return;
      }
    }
    // We have to visit the last value even if it's nullish, because we need its
    // actual value.
    VisitForAccumulatorValue(expr->subsequent(expr->subsequent_length() - 1));
    end_labels.Bind(builder());
  }
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::interpreter::BytecodeLabels::Bind(), builder(), DCHECK_GT, execution_result(), v8::internal::NaryOperation::first(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Expression::IsLiteralButNotNullOrUndefined(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::NaryOperation::subsequent(), v8::internal::NaryOperation::subsequent_length(), v8::internal::Expression::ToBooleanIsTrue(), VisitForAccumulatorValue(), VisitNaryLogicalTest(), VisitNullishSubExpression(), and zone().
VisitNewTargetVariable()
void v8::internal::interpreter::BytecodeGenerator::VisitNewTargetVariable (Variable * variable) [private]
Definition at line 8365 of file bytecode-generator.cc.
                                                                 {
  if (variable == nullptr) return;
  // The generator resume trampoline abuses the new.target register
  // to pass in the generator object. In ordinary calls, new.target is always
  // undefined because generator functions are non-constructible, so don't
  // assign anything to the new.target variable.
  if (IsResumableFunction(info()->literal()->kind())) return;
  if (variable->location() == VariableLocation::LOCAL) {
    // The new.target register was already assigned by entry trampoline.
    DCHECK_EQ(incoming_new_target().index(),
              GetRegisterForLocalVariable(variable).index());
    return;
  }
  // Store the new target we were called with in the given variable.
  builder()->LoadAccumulatorWithRegister(incoming_new_target());
  BuildVariableAssignment(variable, Token::kInit, HoleCheckMode::kElided);
}
References builder(), BuildVariableAssignment(), DCHECK_EQ, GetRegisterForLocalVariable(), incoming_new_target(), v8::internal::index, info(), v8::internal::IsResumableFunction(), v8::internal::kElided, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), and v8::internal::LOCAL.
Referenced by GenerateBodyPrologue().
VisitNot()
void v8::internal::interpreter::BytecodeGenerator::VisitNot (UnaryOperation * expr) [private]
Definition at line 7030 of file bytecode-generator.cc.
                                                     {
  if (execution_result()->IsEffect()) {
    VisitForEffect(expr->expression());
  } else if (execution_result()->IsTest()) {
    // No actual logical negation happening, we just swap the control flow, by
    // swapping the target labels and the fallthrough branch, and visit in the
    // same test result context.
    TestResultScope* test_result = execution_result()->AsTest();
    test_result->InvertControlFlow();
    VisitInSameTestExecutionScope(expr->expression());
  } else {
    UnaryOperation* unary_op = expr->expression()->AsUnaryOperation();
    if (unary_op && unary_op->op() == Token::kNot) {
      // Shortcut repeated nots, to capture the `!!foo` pattern for converting
      // expressions to booleans.
      TypeHint type_hint = VisitForAccumulatorValue(unary_op->expression());
      builder()->ToBoolean(ToBooleanModeFromTypeHint(type_hint));
    } else {
      TypeHint type_hint = VisitForAccumulatorValue(expr->expression());
      builder()->LogicalNot(ToBooleanModeFromTypeHint(type_hint));
    }
    // Always returns a boolean value.
    execution_result()->SetResultIsBoolean();
  }
}
References v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), builder(), execution_result(), v8::internal::UnaryOperation::expression(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::InvertControlFlow(), v8::internal::interpreter::BytecodeArrayBuilder::LogicalNot(), v8::internal::UnaryOperation::op(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsBoolean(), v8::internal::interpreter::BytecodeArrayBuilder::ToBoolean(), ToBooleanModeFromTypeHint(), VisitForAccumulatorValue(), VisitForEffect(), and VisitInSameTestExecutionScope().
VisitNullishExpression()
void v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression (BinaryOperation * binop) [private]
Definition at line 8183 of file bytecode-generator.cc.
                                                                     {
  Expression* left = binop->left();
  Expression* right = binop->right();
  int right_coverage_slot =
      AllocateBlockCoverageSlotIfEnabled(binop, SourceRangeKind::kRight);
  if (execution_result()->IsTest()) {
    TestResultScope* test_result = execution_result()->AsTest();
    if (left->IsLiteralButNotNullOrUndefined() && left->ToBooleanIsTrue()) {
      builder()->Jump(test_result->NewThenLabel());
    } else if (left->IsNullOrUndefinedLiteral() &&
               right->IsNullOrUndefinedLiteral()) {
      BuildIncrementBlockCoverageCounterIfEnabled(right_coverage_slot);
      builder()->Jump(test_result->NewElseLabel());
    } else {
      VisitLogicalTest(Token::kNullish, left, right, right_coverage_slot);
    }
    test_result->SetResultConsumedByTest();
  } else {
    BytecodeLabels end_labels(zone());
    if (VisitNullishSubExpression(left, &end_labels, right_coverage_slot)) {
      return;
    }
    VisitInHoleCheckElisionScopeForAccumulatorValue(right);
    end_labels.Bind(builder());
  }
}
References AllocateBlockCoverageSlotIfEnabled(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::AsTest(), v8::internal::interpreter::BytecodeLabels::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), execution_result(), v8::internal::Expression::IsLiteralButNotNullOrUndefined(), v8::internal::Expression::IsNullOrUndefinedLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::kRight, v8::internal::BinaryOperation::left(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewElseLabel(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel(), v8::internal::BinaryOperation::right(), v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest(), v8::internal::Expression::ToBooleanIsTrue(), VisitInHoleCheckElisionScopeForAccumulatorValue(), VisitLogicalTest(), VisitNullishSubExpression(), and zone().
VisitNullishSubExpression()
bool v8::internal::interpreter::BytecodeGenerator::VisitNullishSubExpression (Expression * expr, BytecodeLabels * end_labels, int coverage_slot) [private]
Definition at line 8037 of file bytecode-generator.cc.
                                                                     {
  if (expr->IsLiteralButNotNullOrUndefined()) {
    VisitForAccumulatorValue(expr);
    end_labels->Bind(builder());
    return true;
  } else if (!expr->IsNullOrUndefinedLiteral()) {
    VisitForAccumulatorValue(expr);
    BytecodeLabel is_null_or_undefined;
    builder()
        ->JumpIfUndefinedOrNull(&is_null_or_undefined)
        .Jump(end_labels->New());
    builder()->Bind(&is_null_or_undefined);
  }
  BuildIncrementBlockCoverageCounterIfEnabled(coverage_slot);
  return false;
}
References v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::BytecodeArrayBuilder::Bind(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), v8::internal::Expression::IsLiteralButNotNullOrUndefined(), v8::internal::Expression::IsNullOrUndefinedLiteral(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::interpreter::BytecodeLabels::New(), and VisitForAccumulatorValue().
Referenced by VisitNaryNullishExpression(), and VisitNullishExpression().
VisitPropertyLoad()
void v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoad (Register obj, Property * expr) [private]
Definition at line 6183 of file bytecode-generator.cc.
                                                                          {
  if (property->is_optional_chain_link()) {
    DCHECK_NOT_NULL(optional_chaining_null_labels_);
    int right_range =
        AllocateBlockCoverageSlotIfEnabled(property, SourceRangeKind::kRight);
    builder()->LoadAccumulatorWithRegister(obj).JumpIfUndefinedOrNull(
        optional_chaining_null_labels_->New());
    BuildIncrementBlockCoverageCounterIfEnabled(right_range);
  }
  AssignType property_kind = Property::GetAssignType(property);
  switch (property_kind) {
    case NON_PROPERTY:
      UNREACHABLE();
    case NAMED_PROPERTY: {
      builder()->SetExpressionPosition(property);
      const AstRawString* name =
          property->key()->AsLiteral()->AsRawPropertyName();
      BuildLoadNamedProperty(property->obj(), obj, name);
      break;
    }
    case KEYED_PROPERTY: {
      VisitForAccumulatorValueAsPropertyKey(property->key());
      builder()->SetExpressionPosition(property);
      BuildLoadKeyedProperty(obj, feedback_spec()->AddKeyedLoadICSlot());
      break;
    }
    case NAMED_SUPER_PROPERTY:
      VisitNamedSuperPropertyLoad(property, Register::invalid_value());
      break;
    case KEYED_SUPER_PROPERTY:
      VisitKeyedSuperPropertyLoad(property, Register::invalid_value());
      break;
    case PRIVATE_SETTER_ONLY: {
      BuildPrivateBrandCheck(property, obj);
      BuildInvalidPropertyAccess(MessageTemplate::kInvalidPrivateGetterAccess,
                                 property);
      break;
    }
    case PRIVATE_GETTER_ONLY:
    case PRIVATE_GETTER_AND_SETTER: {
      Register key = VisitForRegisterValue(property->key());
      BuildPrivateBrandCheck(property, obj);
      BuildPrivateGetterAccess(obj, key);
      break;
    }
    case PRIVATE_METHOD: {
      BuildPrivateBrandCheck(property, obj);
      // In the case of private methods, property->key() is the function to be
      // loaded (stored in a context slot), so load this directly.
      VisitForAccumulatorValue(property->key());
      break;
    }
    case PRIVATE_DEBUG_DYNAMIC: {
      BuildPrivateDebugDynamicGet(property, obj);
      break;
    }
  }
}
References AllocateBlockCoverageSlotIfEnabled(), builder(), BuildIncrementBlockCoverageCounterIfEnabled(), BuildInvalidPropertyAccess(), BuildLoadKeyedProperty(), BuildLoadNamedProperty(), BuildPrivateBrandCheck(), BuildPrivateDebugDynamicGet(), BuildPrivateGetterAccess(), DCHECK_NOT_NULL, feedback_spec(), v8::internal::Property::GetAssignType(), v8::internal::interpreter::Register::invalid_value(), v8::internal::Property::is_optional_chain_link(), v8::internal::interpreter::BytecodeArrayBuilder::JumpIfUndefinedOrNull(), v8::internal::Property::key(), v8::internal::key, v8::internal::KEYED_PROPERTY, v8::internal::KEYED_SUPER_PROPERTY, v8::internal::kRight, v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(), v8::internal::name, v8::internal::NAMED_PROPERTY, v8::internal::NAMED_SUPER_PROPERTY, v8::internal::interpreter::BytecodeLabels::New(), v8::internal::NON_PROPERTY, v8::internal::Property::obj(), optional_chaining_null_labels_, v8::internal::PRIVATE_DEBUG_DYNAMIC, v8::internal::PRIVATE_GETTER_AND_SETTER, v8::internal::PRIVATE_GETTER_ONLY, v8::internal::PRIVATE_METHOD, v8::internal::PRIVATE_SETTER_ONLY, v8::internal::interpreter::BytecodeArrayBuilder::SetExpressionPosition(), v8::internal::UNREACHABLE(), VisitForAccumulatorValue(), VisitForAccumulatorValueAsPropertyKey(), VisitForRegisterValue(), VisitKeyedSuperPropertyLoad(), and VisitNamedSuperPropertyLoad().
Referenced by VisitPropertyLoadForRegister().
VisitPropertyLoadForRegister()
void v8::internal::interpreter::BytecodeGenerator::VisitPropertyLoadForRegister (Register obj, Property * expr, Register destination) [private]
Definition at line 6417 of file bytecode-generator.cc.
                                                                           {
  ValueResultScope result_scope(this);
  VisitPropertyLoad(obj, expr);
  builder()->StoreAccumulatorInRegister(destination);
}
References builder(), v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(), and VisitPropertyLoad().
VisitRestArgumentsArray()
void v8::internal::interpreter::BytecodeGenerator::VisitRestArgumentsArray (Variable * rest) [private]
Definition at line 8347 of file bytecode-generator.cc.
                                                              {
  if (rest == nullptr) return;
  // Allocate and initialize a new rest parameter and assign to the {rest}
  // variable.
  builder()->CreateArguments(CreateArgumentsType::kRestParameter);
  DCHECK(rest->IsContextSlot() || rest->IsStackAllocated());
  BuildVariableAssignment(rest, Token::kAssign, HoleCheckMode::kElided);
}
References builder(), BuildVariableAssignment(), v8::internal::interpreter::BytecodeArrayBuilder::CreateArguments(), v8::internal::DCHECK(), v8::internal::kElided, and v8::internal::kRestParameter.
Referenced by GenerateBodyPrologue().
VisitStatements()
void v8::internal::interpreter::BytecodeGenerator::VisitStatements (const ZonePtrList< Statement > * statments, int start = 0)
Definition at line 2269 of file bytecode-generator.cc.
                                                         {
  for (int i = start; i < statements->length(); i++) {
    // Allocate an outer register allocations scope for the statement.
    RegisterAllocationScope allocation_scope(this);
    Statement* stmt = statements->at(i);
    Visit(stmt);
    if (builder()->RemainderOfBlockIsDead()) break;
  }
}
References v8::internal::ZoneList< T >::at(), builder(), v8::internal::ZoneList< T >::length(), and v8::internal::AstVisitor< BytecodeGenerator >::Visit().
Referenced by GenerateBodyStatementsWithoutImplicitFinalReturn(), and VisitBlockDeclarationsAndStatements().
VisitThisFunctionVariable()
void v8::internal::interpreter::BytecodeGenerator::VisitThisFunctionVariable (Variable * variable) [private]
Definition at line 8357 of file bytecode-generator.cc.
                                                                    {
  if (variable == nullptr) return;
  // Store the closure we were called with in the given variable.
  builder()->LoadAccumulatorWithRegister(Register::function_closure());
  BuildVariableAssignment(variable, Token::kInit, HoleCheckMode::kElided);
}
References builder(), BuildVariableAssignment(), v8::internal::interpreter::Register::function_closure(), v8::internal::kElided, and v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister().
Referenced by GenerateBodyPrologue().
VisitTypeOf()
void v8::internal::interpreter::BytecodeGenerator::VisitTypeOf (UnaryOperation * expr) [private]
Definition at line 7024 of file bytecode-generator.cc.
                                                        {
  VisitForTypeOfValue(expr->expression());
  builder()->TypeOf(feedback_index(feedback_spec()->AddTypeOfSlot()));
  execution_result()->SetResultIsInternalizedString();
}
References builder(), execution_result(), v8::internal::UnaryOperation::expression(), feedback_index(), feedback_spec(), v8::internal::interpreter::BytecodeGenerator::ExpressionResultScope::SetResultIsInternalizedString(), v8::internal::interpreter::BytecodeArrayBuilder::TypeOf(), and VisitForTypeOfValue().
VisitVoid()
void v8::internal::interpreter::BytecodeGenerator::VisitVoid (UnaryOperation * expr) [private]
Definition at line 7007 of file bytecode-generator.cc.
                                                      {
  VisitForEffect(expr->expression());
  builder()->LoadUndefined();
}
References builder(), v8::internal::UnaryOperation::expression(), v8::internal::interpreter::BytecodeArrayBuilder::LoadUndefined(), and VisitForEffect().
zone()
Zone* v8::internal::interpreter::BytecodeGenerator::zone () const [inline], [private]
Definition at line 537 of file bytecode-generator.h.
{ return zone_; }
References zone_.
Referenced by BuildClassLiteral(), BuildCreateArrayLiteral(), BuildDestructuringArrayAssignment(), BuildFinalizeIteration(), BuildIteratorClose(), BytecodeGenerator(), GenerateDerivedConstructorBody(), VisitLogicalAndExpression(), VisitLogicalOrExpression(), VisitLogicalTestSubExpression(), VisitNaryLogicalAndExpression(), VisitNaryLogicalOrExpression(), VisitNaryNullishExpression(), and VisitNullishExpression().
Member Data Documentation
array_literals_
ZoneVector<std::pair<ArrayLiteralBoilerplateBuilder*, size_t> > v8::internal::interpreter::BytecodeGenerator::array_literals_ [private]
Definition at line 625 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants(), and BuildCreateArrayLiteral().
ast_string_constants_
const AstStringConstants* v8::internal::interpreter::BytecodeGenerator::ast_string_constants_ [private]
Definition at line 607 of file bytecode-generator.h.
Referenced by ast_string_constants().
block_coverage_builder_
BlockCoverageBuilder* v8::internal::interpreter::BytecodeGenerator::block_coverage_builder_ [private]
Definition at line 618 of file bytecode-generator.h.
Referenced by AllocateBlockCoverageSlotIfEnabled(), AllocateConditionalChainBlockCoverageSlotIfEnabled(), AllocateNaryBlockCoverageSlotIfEnabled(), BuildIncrementBlockCoverageCounterIfEnabled(), BuildTryCatch(), BuildTryFinally(), BytecodeGenerator(), FinalizeBytecode(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::GetSlotFor(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::NaryCodeCoverageSlots(), and VisitBlockDeclarationsAndStatements().
builder_
BytecodeArrayBuilder v8::internal::interpreter::BytecodeGenerator::builder_ [private]
Definition at line 605 of file bytecode-generator.h.
Referenced by builder().
catch_prediction_
HandlerTable::CatchPrediction v8::internal::interpreter::BytecodeGenerator::catch_prediction_ [private]
Definition at line 656 of file bytecode-generator.h.
Referenced by catch_prediction(), and set_catch_prediction().
class_literals_
ZoneVector<std::pair<ClassLiteral*, size_t> > v8::internal::interpreter::BytecodeGenerator::class_literals_ [private]
Definition at line 626 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants(), and BuildClassLiteral().
closure_scope_
DeclarationScope* v8::internal::interpreter::BytecodeGenerator::closure_scope_ [private]
Definition at line 608 of file bytecode-generator.h.
Referenced by closure_scope().
current_disposables_stack_
Register v8::internal::interpreter::BytecodeGenerator::current_disposables_stack_ [private]
Definition at line 636 of file bytecode-generator.h.
Referenced by current_disposables_stack(), and set_current_disposables_stack().
current_for_in_scope_
ForInScope* v8::internal::interpreter::BytecodeGenerator::current_for_in_scope_ [private]
Definition at line 654 of file bytecode-generator.h.
Referenced by current_for_in_scope(), and set_current_for_in_scope().
current_loop_scope_
LoopScope* v8::internal::interpreter::BytecodeGenerator::current_loop_scope_ [private]
Definition at line 653 of file bytecode-generator.h.
Referenced by current_loop_scope(), and set_current_loop_scope().
current_scope_
Scope* v8::internal::interpreter::BytecodeGenerator::current_scope_ [private]
Definition at line 609 of file bytecode-generator.h.
Referenced by current_scope(), v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::EnterScope(), v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::ExitScope(), and set_current_scope().
dummy_feedback_slot_
SharedFeedbackSlot v8::internal::interpreter::BytecodeGenerator::dummy_feedback_slot_ [private]
Definition at line 642 of file bytecode-generator.h.
Referenced by GetDummyCompareICSlot().
eager_inner_literals_
std::vector<FunctionLiteral*>* v8::internal::interpreter::BytecodeGenerator::eager_inner_literals_ [private]
Definition at line 612 of file bytecode-generator.h.
Referenced by AddToEagerLiteralsIfEager().
eval_calls_
ZoneVector<std::pair<Call*, Scope*> > v8::internal::interpreter::BytecodeGenerator::eval_calls_ [private]
Definition at line 629 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants().
execution_context_
ContextScope* v8::internal::interpreter::BytecodeGenerator::execution_context_ [private]
Definition at line 632 of file bytecode-generator.h.
Referenced by execution_context(), and set_execution_context().
execution_control_
ControlScope* v8::internal::interpreter::BytecodeGenerator::execution_control_ [private]
Definition at line 631 of file bytecode-generator.h.
Referenced by execution_control(), and set_execution_control().
execution_result_
ExpressionResultScope* v8::internal::interpreter::BytecodeGenerator::execution_result_ [private]
Definition at line 633 of file bytecode-generator.h.
Referenced by execution_result(), and set_execution_result().
feedback_slot_cache_
FeedbackSlotCache* v8::internal::interpreter::BytecodeGenerator::feedback_slot_cache_ [private]
Definition at line 615 of file bytecode-generator.h.
Referenced by feedback_slot_cache().
function_literals_
ZoneVector<std::pair<FunctionLiteral*, size_t> > v8::internal::interpreter::BytecodeGenerator::function_literals_ [private]
Definition at line 619 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants().
generator_jump_table_
BytecodeJumpTable* v8::internal::interpreter::BytecodeGenerator::generator_jump_table_ [private]
Definition at line 644 of file bytecode-generator.h.
Referenced by BuildGeneratorPrologue(), and BuildSuspendPoint().
hole_check_bitmap_
Variable::HoleCheckBitmap v8::internal::interpreter::BytecodeGenerator::hole_check_bitmap_ [private]
Definition at line 651 of file bytecode-generator.h.
Referenced by RememberHoleCheckInCurrentBlock(), and VariableNeedsHoleCheckInCurrentBlock().
incoming_new_target_or_generator_
Register v8::internal::interpreter::BytecodeGenerator::incoming_new_target_or_generator_ [private]
Definition at line 635 of file bytecode-generator.h.
Referenced by AllocateTopLevelRegisters(), FinalizeBytecode(), generator_object(), and incoming_new_target().
info_
UnoptimizedCompilationInfo* v8::internal::interpreter::BytecodeGenerator::info_ [private]
Definition at line 606 of file bytecode-generator.h.
Referenced by FinalizeSourcePositionTable(), and info().
local_isolate_
LocalIsolate* v8::internal::interpreter::BytecodeGenerator::local_isolate_ [private]
Definition at line 603 of file bytecode-generator.h.
Referenced by AddToEagerLiteralsIfEager(), and GenerateBytecode().
loop_depth_
int v8::internal::interpreter::BytecodeGenerator::loop_depth_ [private]
Definition at line 647 of file bytecode-generator.h.
native_function_literals_
ZoneVector<std::pair<NativeFunctionLiteral*, size_t> > v8::internal::interpreter::BytecodeGenerator::native_function_literals_ [private]
Definition at line 621 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants().
object_literals_
ZoneVector<std::pair<ObjectLiteralBoilerplateBuilder*, size_t> > v8::internal::interpreter::BytecodeGenerator::object_literals_ [private]
Definition at line 623 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants().
optional_chaining_null_labels_
BytecodeLabels* v8::internal::interpreter::BytecodeGenerator::optional_chaining_null_labels_ [private]
Definition at line 638 of file bytecode-generator.h.
Referenced by VisitPropertyLoad().
script_
Handle<Script> v8::internal::interpreter::BytecodeGenerator::script_ [private]
Definition at line 613 of file bytecode-generator.h.
Referenced by AddToEagerLiteralsIfEager().
suspend_count_
int v8::internal::interpreter::BytecodeGenerator::suspend_count_ [private]
Definition at line 645 of file bytecode-generator.h.
Referenced by BuildSuspendPoint().
template_objects_
ZoneVector<std::pair<GetTemplateObject*, size_t> > v8::internal::interpreter::BytecodeGenerator::template_objects_ [private]
Definition at line 627 of file bytecode-generator.h.
Referenced by AllocateDeferredConstants().
top_level_builder_
TopLevelDeclarationsBuilder* v8::internal::interpreter::BytecodeGenerator::top_level_builder_ [private]
Definition at line 617 of file bytecode-generator.h.
Referenced by top_level_builder().
vars_in_hole_check_bitmap_
ZoneVector<Variable*> v8::internal::interpreter::BytecodeGenerator::vars_in_hole_check_bitmap_ [private]
Definition at line 628 of file bytecode-generator.h.
Referenced by GenerateBytecode(), and RememberHoleCheckInCurrentBlock().
zone_
Zone* v8::internal::interpreter::BytecodeGenerator::zone_ [private]
Definition at line 604 of file bytecode-generator.h.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::AccessorTable< PropertyT >::LookupOrInsert(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.h
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc