v8_inspector::RemoteObjectId Class Reference
#include <remote-object-id.h>
Public Member Functions
~RemoteObjectId ()=default
int id () const
Static Public Member Functions
static Response parse (const String16 &, std::unique_ptr< RemoteObjectId > *)
static String16 serialize (uint64_t isolateId, int injectedScriptId, int id)
Additional Inherited Members
Detailed Description
Definition at line 32 of file remote-object-id.h.
Constructor & Destructor Documentation
 RemoteObjectId()
v8_inspector::RemoteObjectId::~RemoteObjectId () [default]
Member Function Documentation
id()
int v8_inspector::RemoteObjectId::id () const [inline]
Definition at line 36 of file remote-object-id.h.
{ return m_id; }
References v8_inspector::RemoteObjectIdBase::m_id.
Referenced by v8_inspector::InjectedScript::findObject(), and v8_inspector::InjectedScript::objectGroupName().
parse()
Response v8_inspector::RemoteObjectId::parse (const String16 & objectId, std::unique_ptr< RemoteObjectId > * result) [static]
Definition at line 49 of file remote-object-id.cc.
                                                                      {
  std::unique_ptr<RemoteObjectId> remoteObjectId(new RemoteObjectId());
  if (!remoteObjectId->parseId(objectId))
    return Response::ServerError("Invalid remote object id");
  *result = std::move(remoteObjectId);
  return Response::Success();
}
References v8::base::internal::result.
Referenced by v8_inspector::InjectedScript::ObjectScope::findInjectedScript(), v8_inspector::InjectedScript::releaseObject(), v8_inspector::InjectedScript::resolveCallArgument(), and v8_inspector::V8InspectorSessionImpl::unwrapObject().
serialize()
String16 v8_inspector::RemoteObjectId::serialize (uint64_t isolateId, int injectedScriptId, int id) [static]
Definition at line 58 of file remote-object-id.cc.
                                           {
  return serializeId(isolateId, injectedScriptId, id);
}
References v8_inspector::RemoteObjectIdBase::isolateId(), and v8_inspector::anonymous_namespace{remote-object-id.cc}::serializeId().
Referenced by v8_inspector::InjectedScript::bindObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/remote-object-id.h
/mnt/V8SourceCode/src/inspector/remote-object-id.cc