v8::internal::torque::Declarations Class Reference
#include <declarations.h>
Static Public Member Functions
static std::vector< Declarable * > TryLookup (const QualifiedName &name)
static std::vector< Declarable * > TryLookupShallow (const QualifiedName &name)
template<class T >
static std::vector< T * > TryLookup (const QualifiedName &name)
static std::vector< Declarable * > Lookup (const QualifiedName &name)
static std::vector< Declarable * > LookupGlobalScope (const QualifiedName &name)
static const TypeAlias * LookupTypeAlias (const QualifiedName &name)
static const Type * LookupType (const QualifiedName &name)
static const Type * LookupType (const Identifier *identifier)
static std::optional< const Type * > TryLookupType (const QualifiedName &name)
static const Type * LookupGlobalType (const QualifiedName &name)
static Builtin * FindSomeInternalBuiltinWithType (const BuiltinPointerType *type)
static Value * LookupValue (const QualifiedName &name)
static Macro * TryLookupMacro (const std::string &name, const TypeVector &types)
static std::optional< Builtin * > TryLookupBuiltin (const QualifiedName &name)
static std::vector< GenericCallable * > LookupGeneric (const std::string &name)
static GenericCallable * LookupUniqueGeneric (const QualifiedName &name)
static GenericType * LookupUniqueGenericType (const QualifiedName &name)
static GenericType * LookupGlobalUniqueGenericType (const std::string &name)
static std::optional< GenericType * > TryLookupGenericType (const QualifiedName &name)
static Namespace * DeclareNamespace (const std::string &name)
static TypeAlias * DeclareType (const Identifier *name, const Type *type)
static TypeAlias * PredeclareTypeAlias (const Identifier *name, TypeDeclaration *type, bool redeclaration)
static TorqueMacro * CreateTorqueMacro (std::string external_name, std::string readable_name, bool exported_to_csa, Signature signature, std::optional< Statement * > body, bool is_user_defined)
static ExternMacro * CreateExternMacro (std::string name, std::string external_assembler_name, Signature signature)
static Macro * DeclareMacro (const std::string &name, bool accessible_from_csa, std::optional< std::string > external_assembler_name, const Signature &signature, std::optional< Statement * > body, std::optional< std::string > op={}, bool is_user_defined=true)
static Method * CreateMethod (AggregateType *class_type, const std::string &name, Signature signature, Statement *body)
static Intrinsic * CreateIntrinsic (const std::string &name, const Signature &signature)
static Intrinsic * DeclareIntrinsic (const std::string &name, const Signature &signature)
static Builtin * CreateBuiltin (std::string external_name, std::string readable_name, Builtin::Kind kind, Builtin::Flags flags, Signature signature, std::optional< std::string > use_counter_name, std::optional< Statement * > body)
static RuntimeFunction * DeclareRuntimeFunction (const std::string &name, const Signature &signature)
static ExternConstant * DeclareExternConstant (Identifier *name, const Type *type, std::string value)
static NamespaceConstant * DeclareNamespaceConstant (Identifier *name, const Type *type, Expression *body)
static GenericCallable * DeclareGenericCallable (const std::string &name, GenericCallableDeclaration *ast_node)
static GenericType * DeclareGenericType (const std::string &name, GenericTypeDeclaration *ast_node)
template<class T >
static T * Declare (const std::string &name, T *d)
template<class T >
static T * Declare (const std::string &name, std::unique_ptr< T > d)
static Macro * DeclareOperator (const std::string &name, Macro *m)
static std::string GetGeneratedCallableName (const std::string &name, const TypeVector &specialized_types)
Detailed Description
Definition at line 44 of file declarations.h.
Member Function Documentation
CreateBuiltin()
Builtin * v8::internal::torque::Declarations::CreateBuiltin (std::string external_name, std::string readable_name, Builtin::Kind kind, Builtin::Flags flags, Signature signature, std::optional< std::string > use_counter_name, std::optional< Statement * > body) [static]
Definition at line 255 of file declarations.cc.
                                  {
  return RegisterDeclarable(std::unique_ptr<Builtin>(new Builtin(
      std::move(external_name), std::move(readable_name), kind, flags,
      std::move(signature), std::move(use_counter_name), body)));
}
References v8::internal::flags, and v8::internal::torque::RegisterDeclarable().
Referenced by v8::internal::torque::DeclarationVisitor::CreateBuiltin().
CreateExternMacro()
ExternMacro * v8::internal::torque::Declarations::CreateExternMacro (std::string name, std::string external_assembler_name, Signature signature) [static]
Definition at line 190 of file declarations.cc.
                         {
  return RegisterDeclarable(std::unique_ptr<ExternMacro>(
      new ExternMacro(std::move(name), std::move(external_assembler_name),
                      std::move(signature))));
}
References v8::internal::name, and v8::internal::torque::RegisterDeclarable().
Referenced by DeclareMacro().
CreateIntrinsic()
Intrinsic * v8::internal::torque::Declarations::CreateIntrinsic (const std::string & name, const Signature & signature) [static]
Definition at line 241 of file declarations.cc.
                                                                     {
  Intrinsic* result = RegisterDeclarable(std::unique_ptr<Intrinsic>(
      new Intrinsic(std::move(name), std::move(signature))));
  return result;
}
References v8::internal::name, v8::internal::torque::RegisterDeclarable(), and v8::base::internal::result.
Referenced by DeclareIntrinsic(), and v8::internal::torque::DeclarationVisitor::Specialize().
CreateMethod()
Method * v8::internal::torque::Declarations::CreateMethod (AggregateType * class_type, const std::string & name, Signature signature, Statement * body) [static]
Definition at line 230 of file declarations.cc.
                                                    {
  std::string generated_name = GlobalContext::MakeUniqueName(
      "Method_" + container_type->SimpleName() + "_" + name);
  Method* result = RegisterDeclarable(std::unique_ptr<Method>(new Method(
      container_type, generated_name, name, std::move(signature), body)));
  container_type->RegisterMethod(result);
  return result;
}
References v8::internal::torque::GlobalContext::MakeUniqueName(), v8::internal::name, v8::internal::torque::RegisterDeclarable(), v8::internal::torque::AggregateType::RegisterMethod(), v8::base::internal::result, v8::internal::torque::Type::SimpleName(), and v8::internal::string.
Referenced by v8::internal::torque::DeclareMethods().
CreateTorqueMacro()
TorqueMacro * v8::internal::torque::Declarations::CreateTorqueMacro (std::string external_name, std::string readable_name, bool exported_to_csa, Signature signature, std::optional< Statement * > body, bool is_user_defined) [static]
Definition at line 181 of file declarations.cc.
                                                                             {
  external_name = GlobalContext::MakeUniqueName(external_name);
  return RegisterDeclarable(std::unique_ptr<TorqueMacro>(new TorqueMacro(
      std::move(external_name), std::move(readable_name), std::move(signature),
      body, is_user_defined, exported_to_csa)));
}
References v8::internal::torque::GlobalContext::MakeUniqueName(), and v8::internal::torque::RegisterDeclarable().
Referenced by DeclareMacro(), and v8::internal::torque::DeclarationVisitor::Specialize().
Declare() [1/2]
template<class T >
static T* v8::internal::torque::Declarations::Declare (const std::string & name, std::unique_ptr< T > d) [inline], [static]
Definition at line 151 of file declarations.h.
                                                               {
    return CurrentScope::Get()->AddDeclarable(name,
                                              RegisterDeclarable(std::move(d)));
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::name, and v8::internal::torque::RegisterDeclarable().
Declare() [2/2]
template<class T >
static T* v8::internal::torque::Declarations::Declare (const std::string & name, T * d) [inline], [static]
Definition at line 146 of file declarations.h.
                                                 {
    CurrentScope::Get()->AddDeclarable(name, d);
    return d;
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::name.
Referenced by DeclareExternConstant(), DeclareGenericCallable(), DeclareGenericType(), DeclareIntrinsic(), DeclareMacro(), DeclareNamespace(), DeclareNamespaceConstant(), DeclareRuntimeFunction(), DeclareType(), PredeclareTypeAlias(), and v8::internal::torque::DeclarationVisitor::Visit().
DeclareExternConstant()
ExternConstant * v8::internal::torque::Declarations::DeclareExternConstant (Identifier * name, const Type * type, std::string value) [static]
Definition at line 272 of file declarations.cc.
                                                                     {
  CheckAlreadyDeclared<Value>(name->value, "constant");
  return Declare(name->value, std::unique_ptr<ExternConstant>(
                                  new ExternConstant(name, type, value)));
}
References Declare(), v8::internal::name, v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::torque::DeclarationVisitor::Visit().
DeclareGenericCallable()
GenericCallable * v8::internal::torque::Declarations::DeclareGenericCallable (const std::string & name, GenericCallableDeclaration * ast_node) [static]
Definition at line 292 of file declarations.cc.
                                                                 {
  return Declare(name, std::unique_ptr<GenericCallable>(
                           new GenericCallable(name, ast_node)));
}
References Declare(), and v8::internal::name.
Referenced by v8::internal::torque::PredeclarationVisitor::Predeclare().
DeclareGenericType()
GenericType * v8::internal::torque::Declarations::DeclareGenericType (const std::string & name, GenericTypeDeclaration * ast_node) [static]
Definition at line 298 of file declarations.cc.
                                                             {
  return Declare(name,
                 std::unique_ptr<GenericType>(new GenericType(name, ast_node)));
}
References Declare(), and v8::internal::name.
Referenced by v8::internal::torque::PredeclarationVisitor::Predeclare().
DeclareIntrinsic()
Intrinsic * v8::internal::torque::Declarations::DeclareIntrinsic (const std::string & name, const Signature & signature) [static]
Definition at line 248 of file declarations.cc.
                                                                      {
  Intrinsic* result = CreateIntrinsic(std::move(name), std::move(signature));
  Declare(name, result);
  return result;
}
References CreateIntrinsic(), Declare(), v8::internal::name, and v8::base::internal::result.
Referenced by v8::internal::torque::DeclarationVisitor::Visit().
DeclareMacro()
Macro * v8::internal::torque::Declarations::DeclareMacro (const std::string & name, bool accessible_from_csa, std::optional< std::string > external_assembler_name, const Signature & signature, std::optional< Statement * > body, std::optional< std::string > op = {}, bool is_user_defined = true) [static]
Definition at line 198 of file declarations.cc.
                                                     {
  if (Macro* existing_macro =
          TryLookupMacro(name, signature.GetExplicitTypes())) {
    if (existing_macro->ParentScope() == CurrentScope::Get()) {
      ReportError("cannot redeclare macro ", name,
                  " with identical explicit parameters");
    }
  }
  Macro* macro;
  if (external_assembler_name) {
    macro =
        CreateExternMacro(name, std::move(*external_assembler_name), signature);
  } else {
    macro = CreateTorqueMacro(name, name, accessible_from_csa, signature, body,
                              is_user_defined);
  }
  Declare(name, macro);
  if (op) {
    if (TryLookupMacro(*op, signature.GetExplicitTypes())) {
      ReportError("cannot redeclare operator ", name,
                  " with identical explicit parameters");
    }
    DeclareOperator(*op, macro);
  }
  return macro;
}
References CreateExternMacro(), CreateTorqueMacro(), Declare(), DeclareOperator(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Signature::GetExplicitTypes(), v8::internal::name, v8::internal::torque::ReportError(), and TryLookupMacro().
Referenced by v8::internal::torque::ClassType::GenerateAccessors(), v8::internal::torque::ClassType::GenerateSliceAccessor(), and v8::internal::torque::DeclarationVisitor::Visit().
DeclareNamespace()
Namespace * v8::internal::torque::Declarations::DeclareNamespace (const std::string & name) [static]
Definition at line 162 of file declarations.cc.
                                                               {
  return Declare(name, std::make_unique<Namespace>(name));
}
References Declare(), and v8::internal::name.
Referenced by v8::internal::torque::GetOrCreateNamespace().
DeclareNamespaceConstant()
NamespaceConstant * v8::internal::torque::Declarations::DeclareNamespaceConstant (Identifier * name, const Type * type, Expression * body) [static]
Definition at line 280 of file declarations.cc.
                                                                            {
  CheckAlreadyDeclared<Value>(name->value, "constant");
  std::string external_name = GlobalContext::MakeUniqueName(name->value);
  std::unique_ptr<NamespaceConstant> namespaceConstant(
      new NamespaceConstant(name, std::move(external_name), type, body));
  NamespaceConstant* result = namespaceConstant.get();
  Declare(name->value, std::move(namespaceConstant));
  return result;
}
References Declare(), v8::internal::torque::GlobalContext::MakeUniqueName(), v8::internal::name, v8::base::internal::result, v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::DeclarationVisitor::Visit().
DeclareOperator()
Macro * v8::internal::torque::Declarations::DeclareOperator (const std::string & name, Macro * m) [static]
Definition at line 313 of file declarations.cc.
                                                                    {
  GlobalContext::GetDefaultNamespace()->AddDeclarable(name, m);
  return m;
}
References v8::internal::torque::Scope::AddDeclarable(), v8::internal::torque::GlobalContext::GetDefaultNamespace(), and v8::internal::name.
Referenced by DeclareMacro().
DeclareRuntimeFunction()
RuntimeFunction * v8::internal::torque::Declarations::DeclareRuntimeFunction (const std::string & name, const Signature & signature) [static]
Definition at line 265 of file declarations.cc.
                                                       {
  CheckAlreadyDeclared<RuntimeFunction>(name, "runtime function");
  return Declare(name, RegisterDeclarable(std::unique_ptr<RuntimeFunction>(
                           new RuntimeFunction(name, signature))));
}
References Declare(), v8::internal::name, and v8::internal::torque::RegisterDeclarable().
Referenced by v8::internal::torque::DeclarationVisitor::Visit().
DeclareType()
TypeAlias * v8::internal::torque::Declarations::DeclareType (const Identifier * name, const Type * type) [static]
Definition at line 166 of file declarations.cc.
                                                                             {
  CheckAlreadyDeclared<TypeAlias>(name->value, "type");
  return Declare(name->value, std::unique_ptr<TypeAlias>(
                                  new TypeAlias(type, true, name->pos)));
}
References Declare(), v8::internal::name, and v8::internal::tracing::type.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::DeclarationVisitor::DeclareSpecializedTypes().
FindSomeInternalBuiltinWithType()
Builtin * v8::internal::torque::Declarations::FindSomeInternalBuiltinWithType (const BuiltinPointerType * type) [static]
Definition at line 93 of file declarations.cc.
                                    {
  for (auto& declarable : GlobalContext::AllDeclarables()) {
    if (Builtin* builtin = Builtin::DynamicCast(declarable.get())) {
      if (!builtin->IsExternal() && builtin->kind() == Builtin::kStub &&
          builtin->signature().return_type == type->return_type() &&
          builtin->signature().parameter_types.types ==
              type->parameter_types()) {
        return builtin;
      }
    }
  }
  return nullptr;
}
References v8::internal::torque::GlobalContext::AllDeclarables(), v8::internal::torque::Builtin::kStub, and v8::internal::tracing::type.
GetGeneratedCallableName()
std::string v8::internal::torque::Declarations::GetGeneratedCallableName (const std::string & name, const TypeVector & specialized_types) [static]
Definition at line 304 of file declarations.cc.
                                                                {
  std::string result = name;
  for (auto type : specialized_types) {
    result += "_" + type->SimpleName();
  }
  return result;
}
References v8::internal::name, v8::base::internal::result, v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::DeclarationVisitor::Specialize().
Lookup()
static std::vector<Declarable*> v8::internal::torque::Declarations::Lookup (const QualifiedName & name) [inline], [static]
Definition at line 59 of file declarations.h.
                                                                  {
    std::vector<Declarable*> d = TryLookup(name);
    if (d.empty()) {
      ReportError("cannot find \"", name, "\"");
    }
    return d;
  }
References v8::internal::name, v8::internal::torque::ReportError(), and TryLookup().
Referenced by LookupGeneric(), LookupTypeAlias(), LookupUniqueGeneric(), LookupUniqueGenericType(), and LookupValue().
LookupGeneric()
std::vector< GenericCallable * > v8::internal::torque::Declarations::LookupGeneric (const std::string & name) [static]
Definition at line 131 of file declarations.cc.
                           {
  return EnsureNonempty(
      FilterDeclarables<GenericCallable>(Lookup(QualifiedName(name))), name,
      "generic callable");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureNonempty(), Lookup(), and v8::internal::name.
Referenced by v8::internal::torque::TypeOracle::ImplicitlyConvertableFrom(), and v8::internal::torque::DeclarationVisitor::Visit().
LookupGlobalScope()
std::vector< Declarable * > v8::internal::torque::Declarations::LookupGlobalScope (const QualifiedName & name) [static]
Definition at line 49 of file declarations.cc.
                               {
  std::vector<Declarable*> d =
      GlobalContext::GetDefaultNamespace()->Lookup(name);
  if (d.empty()) {
    std::stringstream s;
    s << "cannot find \"" << name << "\" in global scope";
    ReportError(s.str());
  }
  return d;
}
References v8::internal::torque::GlobalContext::GetDefaultNamespace(), v8::internal::torque::Scope::Lookup(), v8::internal::name, and v8::internal::torque::ReportError().
Referenced by LookupGlobalType(), and LookupGlobalUniqueGenericType().
LookupGlobalType()
const Type * v8::internal::torque::Declarations::LookupGlobalType (const QualifiedName & name) [static]
Definition at line 87 of file declarations.cc.
                                                                    {
  TypeAlias* declaration = EnsureUnique(
      FilterDeclarables<TypeAlias>(LookupGlobalScope(name)), name, "type");
  return declaration->type();
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), LookupGlobalScope(), v8::internal::name, and v8::internal::torque::TypeAlias::type().
Referenced by v8::internal::torque::TypeOracle::GetBuiltinType().
LookupGlobalUniqueGenericType()
GenericType * v8::internal::torque::Declarations::LookupGlobalUniqueGenericType (const std::string & name) [static]
Definition at line 148 of file declarations.cc.
                           {
  return EnsureUnique(
      FilterDeclarables<GenericType>(LookupGlobalScope(QualifiedName(name))),
      name, "generic type");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), LookupGlobalScope(), and v8::internal::name.
Referenced by v8::internal::torque::TypeOracle::GetLazyGeneric(), v8::internal::torque::TypeOracle::GetSmiTaggedGeneric(), and v8::internal::torque::TypeOracle::GetWeakGeneric().
LookupType() [1/2]
const Type * v8::internal::torque::Declarations::LookupType (const Identifier * identifier) [static]
Definition at line 71 of file declarations.cc.
                                                           {
  const TypeAlias* alias = LookupTypeAlias(QualifiedName(name->value));
  if (GlobalContext::collect_language_server_data()) {
    LanguageServerData::AddDefinition(name->pos,
                                      alias->GetDeclarationPosition());
  }
  return alias->type();
}
References v8::internal::torque::LanguageServerData::AddDefinition(), v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::TypeAlias::GetDeclarationPosition(), LookupTypeAlias(), v8::internal::name, and v8::internal::torque::TypeAlias::type().
LookupType() [2/2]
const Type * v8::internal::torque::Declarations::LookupType (const QualifiedName & name) [static]
Definition at line 67 of file declarations.cc.
                                                              {
  return LookupTypeAlias(name)->type();
}
References LookupTypeAlias(), v8::internal::name, and v8::internal::torque::TypeAlias::type().
Referenced by v8::internal::torque::DeclarationVisitor::Visit().
LookupTypeAlias()
const TypeAlias * v8::internal::torque::Declarations::LookupTypeAlias (const QualifiedName & name) [static]
Definition at line 61 of file declarations.cc.
                                                                        {
  TypeAlias* declaration =
      EnsureUnique(FilterDeclarables<TypeAlias>(Lookup(name)), name, "type");
  return declaration;
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), Lookup(), and v8::internal::name.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and LookupType().
LookupUniqueGeneric()
GenericCallable * v8::internal::torque::Declarations::LookupUniqueGeneric (const QualifiedName & name) [static]
Definition at line 138 of file declarations.cc.
                                                                            {
  return EnsureUnique(FilterDeclarables<GenericCallable>(Lookup(name)), name,
                      "generic callable");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), Lookup(), and v8::internal::name.
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference().
LookupUniqueGenericType()
GenericType * v8::internal::torque::Declarations::LookupUniqueGenericType (const QualifiedName & name) [static]
Definition at line 143 of file declarations.cc.
                                                                            {
  return EnsureUnique(FilterDeclarables<GenericType>(Lookup(name)), name,
                      "generic type");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), Lookup(), and v8::internal::name.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::TypeOracle::GetConstSliceGeneric(), v8::internal::torque::TypeOracle::GetMutableSliceGeneric(), v8::internal::torque::TypeOracle::GetReferenceGeneric(), and v8::internal::torque::TypeArgumentInference::MatchGeneric().
LookupValue()
Value * v8::internal::torque::Declarations::LookupValue (const QualifiedName & name) [static]
Definition at line 108 of file declarations.cc.
                                                          {
  return EnsureUnique(FilterDeclarables<Value>(Lookup(name)), name, "value");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), Lookup(), and v8::internal::name.
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference().
PredeclareTypeAlias()
TypeAlias * v8::internal::torque::Declarations::PredeclareTypeAlias (const Identifier * name, TypeDeclaration * type, bool redeclaration) [static]
Definition at line 172 of file declarations.cc.
                                                                 {
  CheckAlreadyDeclared<TypeAlias>(name->value, "type");
  std::unique_ptr<TypeAlias> alias_ptr(
      new TypeAlias(type, redeclaration, name->pos));
  return Declare(name->value, std::move(alias_ptr));
}
References Declare(), v8::internal::name, and v8::internal::tracing::type.
Referenced by v8::internal::torque::PredeclarationVisitor::Predeclare().
TryLookup() [1/2]
static std::vector<Declarable*> v8::internal::torque::Declarations::TryLookup (const QualifiedName & name) [inline], [static]
Definition at line 46 of file declarations.h.
                                                                     {
    return CurrentScope::Get()->Lookup(name);
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::name.
Referenced by Lookup(), v8::internal::torque::ImplementationVisitor::TestLookupCallable(), TryLookup(), and TryLookupType().
TryLookup() [2/2]
template<class T >
static std::vector<T*> v8::internal::torque::Declarations::TryLookup (const QualifiedName & name) [inline], [static]
Definition at line 55 of file declarations.h.
                                                            {
    return FilterDeclarables<T>(TryLookup(name));
  }
References v8::internal::name, and TryLookup().
TryLookupBuiltin()
std::optional< Builtin * > v8::internal::torque::Declarations::TryLookupBuiltin (const QualifiedName & name) [static]
Definition at line 124 of file declarations.cc.
                               {
  std::vector<Builtin*> builtins = TryLookup<Builtin>(name);
  if (builtins.empty()) return std::nullopt;
  return EnsureUnique(builtins, name.name, "builtin");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), and v8::internal::name.
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference().
TryLookupGenericType()
std::optional< GenericType * > v8::internal::torque::Declarations::TryLookupGenericType (const QualifiedName & name) [static]
Definition at line 155 of file declarations.cc.
                               {
  std::vector<GenericType*> results = TryLookup<GenericType>(name);
  if (results.empty()) return std::nullopt;
  return EnsureUnique(results, name.name, "generic type");
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), and v8::internal::name.
Referenced by v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression().
TryLookupMacro()
Macro * v8::internal::torque::Declarations::TryLookupMacro (const std::string & name, const TypeVector & types) [static]
Definition at line 112 of file declarations.cc.
                                                             {
  std::vector<Macro*> macros = TryLookup<Macro>(QualifiedName(name));
  for (auto& m : macros) {
    auto signature_types = m->signature().GetExplicitTypes();
    if (signature_types == types && !m->signature().parameter_types.var_args) {
      return m;
    }
  }
  return nullptr;
}
References v8::internal::name.
Referenced by DeclareMacro().
TryLookupShallow()
static std::vector<Declarable*> v8::internal::torque::Declarations::TryLookupShallow (const QualifiedName & name) [inline], [static]
Definition at line 50 of file declarations.h.
                                                                            {
    return CurrentScope::Get()->LookupShallow(name);
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::name.
Referenced by v8::internal::torque::anonymous_namespace{declarations.cc}::CheckAlreadyDeclared(), and v8::internal::torque::GetOrCreateNamespace().
TryLookupType()
std::optional< const Type * > v8::internal::torque::Declarations::TryLookupType (const QualifiedName & name) [static]
Definition at line 80 of file declarations.cc.
                               {
  auto decls = FilterDeclarables<TypeAlias>(TryLookup(name));
  if (decls.empty()) return std::nullopt;
  return EnsureUnique(std::move(decls), name, "type")->type();
}
References v8::internal::torque::anonymous_namespace{declarations.cc}::EnsureUnique(), v8::internal::name, and TryLookup().
Referenced by v8::internal::torque::TypeVisitor::ComputeType().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declarations.h
/mnt/V8SourceCode/src/torque/declarations.cc