v8::Counter Class Reference
#include <d8.h>
Public Member Functions
void Bind (const char *name, bool histogram)
int * ptr ()
int count () const
int sample_total () const
bool is_histogram () const
void AddSample (int32_t sample)
Static Public Attributes
static const int kMaxNameSize = 64
Private Attributes
std::atomic< int > count_
std::atomic< int > sample_total_
bool is_histogram_
char name_ [kMaxNameSize]
Detailed Description
Definition at line 46 of file d8.h.
Member Function Documentation
AddSample()
void v8::Counter::AddSample (int32_t sample)
Definition at line 3792 of file d8.cc.
                                  {
  count_.fetch_add(1, std::memory_order_relaxed);
  sample_total_.fetch_add(sample, std::memory_order_relaxed);
}
Referenced by v8::Shell::AddHistogramSample().
Bind()
void v8::Counter::Bind (const char * name, bool histogram)
Definition at line 3785 of file d8.cc.
                                                      {
  base::OS::StrNCpy(name_, kMaxNameSize, name, kMaxNameSize);
  // Explicitly null-terminate, in case {name} is longer than {kMaxNameSize}.
  name_[kMaxNameSize - 1] = '\0';
  is_histogram_ = is_histogram;
}
References name, and v8::base::OS::StrNCpy().
Referenced by v8::Shell::GetCounter().
count()
int v8::Counter::count () const [inline]
Definition at line 55 of file d8.h.
{ return count_.load(std::memory_order_relaxed); }
References count_.
Referenced by v8::Shell::DumpCounters().
is_histogram()
bool v8::Counter::is_histogram () const [inline]
Definition at line 59 of file d8.h.
{ return is_histogram_; }
References is_histogram_.
Referenced by v8::Shell::DumpCounters(), and v8::Shell::GetCounter().
ptr()
int* v8::Counter::ptr () [inline]
Definition at line 51 of file d8.h.
             {
    static_assert(sizeof(int) == sizeof(count_));
    return reinterpret_cast<int*>(&count_);
  }
References count_.
Referenced by v8::Shell::LookupCounter().
sample_total()
int v8::Counter::sample_total () const [inline]
Definition at line 56 of file d8.h.
                           {
    return sample_total_.load(std::memory_order_relaxed);
  }
References sample_total_.
Referenced by v8::Shell::DumpCounters().
Member Data Documentation
count_
std::atomic<int> v8::Counter::count_ [private]
Definition at line 63 of file d8.h.
Referenced by count(), and ptr().
is_histogram_
bool v8::Counter::is_histogram_ [private]
Definition at line 65 of file d8.h.
Referenced by is_histogram().
kMaxNameSize
const int v8::Counter::kMaxNameSize = 64 [static]
Definition at line 48 of file d8.h.
Referenced by v8::CounterCollection::CounterCollection().
name_
char v8::Counter::name_[kMaxNameSize] [private]
Definition at line 66 of file d8.h.
sample_total_
std::atomic<int> v8::Counter::sample_total_ [private]
Definition at line 64 of file d8.h.
Referenced by sample_total().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc