v8_inspector::V8DebuggerId Class Reference
#include <v8-inspector.h>
Public Member Functions
V8DebuggerId ()=default
V8DebuggerId (const V8DebuggerId &)=default
V8DebuggerId & operator= (const V8DebuggerId &)=default
std::unique_ptr< StringBuffer > toString () const
bool isValid () const
std::pair< int64_t, int64_t > pair () const
Private Member Functions
V8DebuggerId (std::pair< int64_t, int64_t >)
Private Attributes
int64_t m_first = 0
int64_t m_second = 0
Friends
class internal::V8DebuggerId
Detailed Description
Definition at line 119 of file v8-inspector.h.
Constructor & Destructor Documentation
V8DebuggerId() [1/3]
v8_inspector::V8DebuggerId::V8DebuggerId () [default]
V8DebuggerId() [2/3]
v8_inspector::V8DebuggerId::V8DebuggerId (const V8DebuggerId &) [default]
V8DebuggerId() [3/3]
v8_inspector::V8DebuggerId::V8DebuggerId (std::pair< int64_t, int64_t > pair) [explicit], [private]
Definition at line 13 of file v8-debugger-id.cc.
    : m_first(pair.first), m_second(pair.second) {}
Member Function Documentation
isValid()
bool v8_inspector::V8DebuggerId::isValid () const
Definition at line 21 of file v8-debugger-id.cc.
{ return m_first || m_second; }
References m_first, and m_second.
Referenced by v8_inspector::internal::V8DebuggerId::isValid().
operator=()
V8DebuggerId& v8_inspector::V8DebuggerId::operator= (const V8DebuggerId &) [default]
pair()
std::pair< int64_t, int64_t > v8_inspector::V8DebuggerId::pair () const
Definition at line 23 of file v8-debugger-id.cc.
                                                   {
  return std::make_pair(m_first, m_second);
}
References m_first, and m_second.
Referenced by v8_inspector::internal::V8DebuggerId::pair().
toString()
std::unique_ptr< StringBuffer > v8_inspector::V8DebuggerId::toString () const
Definition at line 16 of file v8-debugger-id.cc.
                                                         {
  return StringBufferFrom(String16::fromInteger64(m_first) + "." +
                          String16::fromInteger64(m_second));
}
References v8_inspector::String16::fromInteger64(), m_first, m_second, and v8_inspector::StringBufferFrom().
Referenced by v8_inspector::internal::V8DebuggerId::toString().
Friends And Related Function Documentation
internal::V8DebuggerId
friend class internal::V8DebuggerId [friend]
Definition at line 130 of file v8-inspector.h.
Member Data Documentation
m_first
int64_t v8_inspector::V8DebuggerId::m_first = 0 [private]
Definition at line 133 of file v8-inspector.h.
Referenced by isValid(), pair(), and toString().
m_second
int64_t v8_inspector::V8DebuggerId::m_second = 0 [private]
Definition at line 134 of file v8-inspector.h.
Referenced by isValid(), pair(), and toString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-inspector.h
/mnt/V8SourceCode/src/inspector/v8-debugger-id.cc