v8::internal::StringForwardingTable Class Reference
#include <string-forwarding-table.h>
Classes
class Block
class BlockVector
class Record
Public Member Functions
StringForwardingTable (Isolate *isolate)
~StringForwardingTable ()
int size () const
bool empty () const
int AddForwardString (Tagged< String > string, Tagged< String > forward_to)
template<typename T >
int AddExternalResourceAndHash (Tagged< String > string, T *resource, uint32_t raw_hash)
void UpdateForwardString (int index, Tagged< String > forward_to)
template<typename T >
bool TryUpdateExternalResource (int index, T *resource)
Tagged< String > GetForwardString (PtrComprCageBase cage_base, int index) const
V8_EXPORT_PRIVATE uint32_t GetRawHash (PtrComprCageBase cage_base, int index) const
v8::String::ExternalStringResourceBase * GetExternalResource (int index, bool *is_one_byte) const
template<typename Func >
void IterateElements (Func &&callback)
void TearDown ()
void Reset ()
void UpdateAfterYoungEvacuation ()
void UpdateAfterFullEvacuation ()
Static Public Member Functions
static constexpr Tagged< Smi > unused_element ()
static constexpr Tagged< Smi > deleted_element ()
static Address GetForwardStringAddress (Isolate *isolate, int index)
static uint32_t GetRawHashStatic (Isolate *isolate, int index)
Static Public Attributes
static constexpr int kInitialBlockSize = 16
static constexpr int kInitialBlockSizeHighestBit
static constexpr int kInitialBlockVectorCapacity = 4
Private Member Functions
void InitializeBlockVector ()
BlockVector * EnsureCapacity (uint32_t block)
Static Private Member Functions
static uint32_t BlockForIndex (int index, uint32_t *index_in_block_out)
static uint32_t IndexInBlock (int index, uint32_t block)
static uint32_t CapacityForBlock (uint32_t block)
Private Attributes
Isolate * isolate_
std::atomic< BlockVector * > blocks_
std::vector< std::unique_ptr< BlockVector > > block_vector_storage_
std::atomic< int > next_free_index_
base::Mutex grow_mutex_
Detailed Description
Definition at line 26 of file string-forwarding-table.h.
Constructor & Destructor Documentation
StringForwardingTable()
v8::internal::StringForwardingTable::StringForwardingTable (Isolate * isolate) [explicit]
Definition at line 160 of file string-forwarding-table.cc.
    : isolate_(isolate), next_free_index_(0) {
  InitializeBlockVector();
}
References InitializeBlockVector().
 StringForwardingTable()
v8::internal::StringForwardingTable::~StringForwardingTable ()
Definition at line 165 of file string-forwarding-table.cc.
                                              {
  BlockVector* blocks = blocks_.load(std::memory_order_relaxed);
  for (uint32_t block_index = 0; block_index < blocks->size(); block_index++) {
    delete blocks->LoadBlock(block_index);
  }
}
References blocks_, v8::internal::StringForwardingTable::BlockVector::LoadBlock(), and v8::internal::StringForwardingTable::BlockVector::size().
Member Function Documentation
AddExternalResourceAndHash()
template<typename T >
int v8::internal::StringForwardingTable::AddExternalResourceAndHash (Tagged< String > string, T * resource, uint32_t raw_hash)
Definition at line 234 of file string-forwarding-table.cc.
                                                                         {
  constexpr bool is_one_byte =
      std::is_base_of_v<v8::String::ExternalOneByteStringResource, T>;
  DCHECK_IMPLIES(!v8_flags.always_use_string_forwarding_table,
                 HeapLayout::InAnySharedSpace(string));
  int index = next_free_index_++;
  uint32_t index_in_block;
  const uint32_t block_index = BlockForIndex(index, &index_in_block);
  BlockVector* blocks = EnsureCapacity(block_index);
  Block* block = blocks->LoadBlock(block_index, kAcquireLoad);
  block->record(index_in_block)
      ->SetExternal(string, resource, is_one_byte, raw_hash);
  return index;
}
References BlockForIndex(), DCHECK_IMPLIES, EnsureCapacity(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::index, v8::kAcquireLoad, v8::internal::StringForwardingTable::BlockVector::LoadBlock(), next_free_index_, v8::internal::StringForwardingTable::Block::record(), v8::internal::StringForwardingTable::Record::SetExternal(), and v8::internal::v8_flags.
AddForwardString()
int v8::internal::StringForwardingTable::AddForwardString (Tagged< String > string, Tagged< String > forward_to)
Definition at line 207 of file string-forwarding-table.cc.
                                                                       {
  DCHECK_IMPLIES(!v8_flags.always_use_string_forwarding_table,
                 HeapLayout::InAnySharedSpace(string));
  DCHECK_IMPLIES(!v8_flags.always_use_string_forwarding_table,
                 HeapLayout::InAnySharedSpace(forward_to));
  int index = next_free_index_++;
  uint32_t index_in_block;
  const uint32_t block_index = BlockForIndex(index, &index_in_block);
  BlockVector* blocks = EnsureCapacity(block_index);
  Block* block = blocks->LoadBlock(block_index, kAcquireLoad);
  block->record(index_in_block)->SetInternalized(string, forward_to);
  return index;
}
References BlockForIndex(), DCHECK_IMPLIES, EnsureCapacity(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::index, v8::kAcquireLoad, v8::internal::StringForwardingTable::BlockVector::LoadBlock(), next_free_index_, v8::internal::StringForwardingTable::Block::record(), v8::internal::StringForwardingTable::Record::SetInternalized(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference().
BlockForIndex()
uint32_t v8::internal::StringForwardingTable::BlockForIndex (int index, uint32_t * index_in_block_out) [inline], [static], [private]
Definition at line 303 of file string-forwarding-table-inl.h.
                                                                        {
  DCHECK_GE(index, 0);
  DCHECK_NOT_NULL(index_in_block);
  // The block is the leftmost set bit of the index, corrected by the size
  // of the first block.
  const uint32_t block_index =
      kBitsPerInt -
      base::bits::CountLeadingZeros(
          static_cast<uint32_t>(index + kInitialBlockSize)) -
      kInitialBlockSizeHighestBit - 1;
  *index_in_block = IndexInBlock(index, block_index);
  return block_index;
}
References v8::base::bits::CountLeadingZeros(), DCHECK_GE, DCHECK_NOT_NULL, v8::internal::index, IndexInBlock(), v8::internal::kBitsPerInt, kInitialBlockSize, and kInitialBlockSizeHighestBit.
Referenced by AddExternalResourceAndHash(), AddForwardString(), GetExternalResource(), GetRawHash(), and UpdateForwardString().
CapacityForBlock()
uint32_t v8::internal::StringForwardingTable::CapacityForBlock (uint32_t block) [inline], [static], [private]
Definition at line 328 of file string-forwarding-table-inl.h.
                                                                     {
  return 1u << (block_index + kInitialBlockSizeHighestBit);
}
References kInitialBlockSizeHighestBit.
Referenced by EnsureCapacity().
deleted_element()
static constexpr Tagged<Smi> v8::internal::StringForwardingTable::deleted_element () [inline], [static], [constexpr]
Definition at line 36 of file string-forwarding-table.h.
{ return Smi::FromInt(1); }
References v8::internal::Smi::FromInt().
Referenced by v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ClearNonLiveYoungObjects(), TearDown(), and v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation().
empty()
bool v8::internal::StringForwardingTable::empty () const [inline]
Definition at line 300 of file string-forwarding-table-inl.h.
{ return size() == 0; }
References size().
Referenced by IterateElements(), UpdateAfterFullEvacuation(), and UpdateAfterYoungEvacuation().
EnsureCapacity()
StringForwardingTable::BlockVector * v8::internal::StringForwardingTable::EnsureCapacity (uint32_t block) [private]
Definition at line 181 of file string-forwarding-table.cc.
                          {
  BlockVector* blocks = blocks_.load(std::memory_order_acquire);
  if (V8_UNLIKELY(block_index >= blocks->size())) {
    base::MutexGuard table_grow_guard(&grow_mutex_);
    // Reload the vector, as another thread could have grown it.
    blocks = blocks_.load(std::memory_order_relaxed);
    // Check again if we need to grow under lock.
    if (block_index >= blocks->size()) {
      // Grow the vector if the block to insert is greater than the vectors
      // capacity.
      if (block_index >= blocks->capacity()) {
        std::unique_ptr<BlockVector> new_blocks =
            BlockVector::Grow(blocks, blocks->capacity() * 2, grow_mutex_);
        block_vector_storage_.push_back(std::move(new_blocks));
        blocks = block_vector_storage_.back().get();
        blocks_.store(blocks, std::memory_order_release);
      }
      const uint32_t capacity = CapacityForBlock(block_index);
      std::unique_ptr<Block> new_block = Block::New(capacity);
      blocks->AddBlock(std::move(new_block));
    }
  }
  return blocks;
}
References v8::internal::StringForwardingTable::BlockVector::AddBlock(), block_vector_storage_, blocks_, v8::internal::StringForwardingTable::BlockVector::capacity(), CapacityForBlock(), v8::internal::StringForwardingTable::BlockVector::Grow(), grow_mutex_, v8::internal::StringForwardingTable::Block::New(), v8::internal::StringForwardingTable::BlockVector::size(), and V8_UNLIKELY.
Referenced by AddExternalResourceAndHash(), and AddForwardString().
GetExternalResource()
v8::String::ExternalStringResourceBase * v8::internal::StringForwardingTable::GetExternalResource (int index, bool * is_one_byte) const
Definition at line 317 of file string-forwarding-table.cc.
                                                                             {
  CHECK_LT(index, size());
  uint32_t index_in_block;
  const uint32_t block_index = BlockForIndex(index, &index_in_block);
  Block* block = blocks_.load(std::memory_order_acquire)
                     ->LoadBlock(block_index, kAcquireLoad);
  return block->record(index_in_block)->external_resource(is_one_byte);
}
References BlockForIndex(), blocks_, CHECK_LT, v8::internal::StringForwardingTable::Record::external_resource(), v8::internal::index, v8::kAcquireLoad, v8::internal::StringForwardingTable::Block::record(), and size().
GetForwardString()
Tagged<String> v8::internal::StringForwardingTable::GetForwardString (PtrComprCageBase cage_base, int index) const
Referenced by GetForwardStringAddress(), v8::internal::StringTable::LookupString(), and v8::internal::StringTable::Data::TryStringToIndexOrLookupExisting().
GetForwardStringAddress()
Address v8::internal::StringForwardingTable::GetForwardStringAddress (Isolate * isolate, int index) [static]
Definition at line 294 of file string-forwarding-table.cc.
                                                                  {
  return isolate->string_forwarding_table()
      ->GetForwardString(isolate, index)
      .ptr();
}
References GetForwardString(), v8::internal::index, and v8::internal::Isolate::string_forwarding_table().
GetRawHash()
uint32_t v8::internal::StringForwardingTable::GetRawHash (PtrComprCageBase cage_base, int index) const
Definition at line 301 of file string-forwarding-table.cc.
                                                            {
  CHECK_LT(index, size());
  uint32_t index_in_block;
  const uint32_t block_index = BlockForIndex(index, &index_in_block);
  Block* block = blocks_.load(std::memory_order_acquire)
                     ->LoadBlock(block_index, kAcquireLoad);
  return block->record(index_in_block)->raw_hash(cage_base);
}
References BlockForIndex(), blocks_, CHECK_LT, v8::internal::index, v8::kAcquireLoad, v8::internal::StringForwardingTable::Record::raw_hash(), v8::internal::StringForwardingTable::Block::record(), and size().
Referenced by v8::internal::Name::GetRawHashFromForwardingTable(), and GetRawHashStatic().
GetRawHashStatic()
uint32_t v8::internal::StringForwardingTable::GetRawHashStatic (Isolate * isolate, int index) [static]
Definition at line 312 of file string-forwarding-table.cc.
                                                                            {
  return isolate->string_forwarding_table()->GetRawHash(isolate, index);
}
References GetRawHash(), v8::internal::index, and v8::internal::Isolate::string_forwarding_table().
IndexInBlock()
uint32_t v8::internal::StringForwardingTable::IndexInBlock (int index, uint32_t block) [inline], [static], [private]
Definition at line 319 of file string-forwarding-table-inl.h.
                                                                            {
  DCHECK_GE(index, 0);
  // Clear out the leftmost set bit (the block index) to get the index within
  // the block.
  return static_cast<uint32_t>(index + kInitialBlockSize) &
         ~(1u << (block_index + kInitialBlockSizeHighestBit));
}
References DCHECK_GE, v8::internal::index, kInitialBlockSize, and kInitialBlockSizeHighestBit.
Referenced by BlockForIndex(), IterateElements(), UpdateAfterFullEvacuation(), and UpdateAfterYoungEvacuation().
InitializeBlockVector()
void v8::internal::StringForwardingTable::InitializeBlockVector () [private]
Definition at line 172 of file string-forwarding-table.cc.
                                                  {
  BlockVector* blocks = block_vector_storage_
                            .emplace_back(std::make_unique<BlockVector>(
                                kInitialBlockVectorCapacity))
                            .get();
  blocks->AddBlock(Block::New(kInitialBlockSize));
  blocks_.store(blocks, std::memory_order_relaxed);
}
References v8::internal::StringForwardingTable::BlockVector::AddBlock(), block_vector_storage_, blocks_, kInitialBlockSize, kInitialBlockVectorCapacity, and v8::internal::StringForwardingTable::Block::New().
Referenced by Reset(), and StringForwardingTable().
IterateElements()
template<typename Func >
void v8::internal::StringForwardingTable::IterateElements (Func && callback) [inline]
Definition at line 333 of file string-forwarding-table-inl.h.
                                                           {
  if (empty()) return;
  BlockVector* blocks = blocks_.load(std::memory_order_relaxed);
  const uint32_t last_block_index = static_cast<uint32_t>(blocks->size() - 1);
  for (uint32_t block_index = 0; block_index < last_block_index;
       ++block_index) {
    Block* block = blocks->LoadBlock(block_index);
    for (int index = 0; index < block->capacity(); ++index) {
      Record* rec = block->record(index);
      callback(rec);
    }
  }
  // Handle last block separately, as it is not filled to capacity.
  const uint32_t max_index = IndexInBlock(size() - 1, last_block_index) + 1;
  Block* block = blocks->LoadBlock(last_block_index);
  for (uint32_t index = 0; index < max_index; ++index) {
    Record* rec = block->record(index);
    callback(rec);
  }
}
References blocks_, v8::internal::StringForwardingTable::Block::capacity(), empty(), v8::internal::index, IndexInBlock(), v8::internal::StringForwardingTable::BlockVector::LoadBlock(), v8::internal::StringForwardingTable::Block::record(), v8::internal::StringForwardingTable::BlockVector::size(), and size().
Referenced by v8::internal::FullStringForwardingTableCleaner::ProcessFullWithStack(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ProcessYoungObjects(), TearDown(), and v8::internal::FullStringForwardingTableCleaner::TransitionStrings().
Reset()
void v8::internal::StringForwardingTable::Reset ()
Definition at line 340 of file string-forwarding-table.cc.
                                  {
  isolate_->heap()->safepoint()->AssertActive();
  DCHECK_NE(isolate_->heap()->gc_state(), Heap::NOT_IN_GC);
  BlockVector* blocks = blocks_.load(std::memory_order_relaxed);
  for (uint32_t block_index = 0; block_index < blocks->size(); ++block_index) {
    delete blocks->LoadBlock(block_index);
  }
  block_vector_storage_.clear();
  InitializeBlockVector();
  next_free_index_ = 0;
}
References v8::internal::IsolateSafepoint::AssertActive(), block_vector_storage_, blocks_, DCHECK_NE, v8::internal::Heap::gc_state(), v8::internal::Isolate::heap(), InitializeBlockVector(), isolate_, v8::internal::StringForwardingTable::BlockVector::LoadBlock(), next_free_index_, v8::internal::Heap::NOT_IN_GC, v8::internal::Heap::safepoint(), and v8::internal::StringForwardingTable::BlockVector::size().
Referenced by TearDown(), and v8::internal::FullStringForwardingTableCleaner::TransitionStrings().
size()
int v8::internal::StringForwardingTable::size () const [inline]
Definition at line 299 of file string-forwarding-table-inl.h.
{ return next_free_index_; }
References next_free_index_.
Referenced by v8::internal::StringForwardingTable::BlockVector::AddBlock(), empty(), GetExternalResource(), GetRawHash(), IterateElements(), v8::internal::StringForwardingTable::BlockVector::LoadBlock(), v8::internal::StringForwardingTable::Block::operator new(), UpdateAfterFullEvacuation(), UpdateAfterYoungEvacuation(), and UpdateForwardString().
TearDown()
void v8::internal::StringForwardingTable::TearDown ()
Definition at line 326 of file string-forwarding-table.cc.
                                     {
  std::unordered_set<Address> disposed_resources;
  IterateElements([this, &disposed_resources](Record* record) {
    if (record->OriginalStringObject(isolate_) != deleted_element()) {
      Address resource = record->ExternalResourceAddress();
      if (resource != kNullAddress && disposed_resources.count(resource) == 0) {
        record->DisposeExternalResource();
        disposed_resources.insert(resource);
      }
    }
  });
  Reset();
}
References deleted_element(), v8::internal::StringForwardingTable::Record::ExternalResourceAddress(), isolate_, IterateElements(), v8::internal::kNullAddress, v8::internal::StringForwardingTable::Record::OriginalStringObject(), and Reset().
Referenced by v8::internal::Isolate::Deinit().
TryUpdateExternalResource()
template<typename T >
bool v8::internal::StringForwardingTable::TryUpdateExternalResource (int index, T * resource)
Referenced by v8::internal::StringForwardingTable::Record::TryUpdateExternalResource().
unused_element()
static constexpr Tagged<Smi> v8::internal::StringForwardingTable::unused_element () [inline], [static], [constexpr]
Definition at line 35 of file string-forwarding-table.h.
{ return Smi::FromInt(0); }
References v8::internal::Smi::FromInt().
Referenced by v8::internal::StringForwardingTable::Block::Block(), and v8::internal::StringForwardingTable::Record::set_raw_hash_if_empty().
UpdateAfterFullEvacuation()
void v8::internal::StringForwardingTable::UpdateAfterFullEvacuation ()
Definition at line 375 of file string-forwarding-table.cc.
                                                      {
  if (empty()) return;
  BlockVector* blocks = blocks_.load(std::memory_order_relaxed);
  const unsigned int last_block_index =
      static_cast<unsigned int>(blocks->size() - 1);
  for (unsigned int block_index = 0; block_index < last_block_index;
       ++block_index) {
    Block* block = blocks->LoadBlock(block_index, kAcquireLoad);
    block->UpdateAfterFullEvacuation(isolate_);
  }
  // Handle last block separately, as it is not filled to capacity.
  const int max_index = IndexInBlock(size() - 1, last_block_index) + 1;
  blocks->LoadBlock(last_block_index, kAcquireLoad)
      ->UpdateAfterFullEvacuation(isolate_, max_index);
}
References blocks_, empty(), IndexInBlock(), isolate_, v8::kAcquireLoad, v8::internal::StringForwardingTable::BlockVector::LoadBlock(), v8::internal::StringForwardingTable::BlockVector::size(), size(), and v8::internal::StringForwardingTable::Block::UpdateAfterFullEvacuation().
Referenced by v8::internal::StringForwardingTable::Block::UpdateAfterFullEvacuation().
UpdateAfterYoungEvacuation()
void v8::internal::StringForwardingTable::UpdateAfterYoungEvacuation ()
Definition at line 354 of file string-forwarding-table.cc.
                                                       {
  // This is only used for the Scavenger.
  DCHECK(!v8_flags.minor_ms);
  DCHECK(v8_flags.always_use_string_forwarding_table);
  if (empty()) return;
  BlockVector* blocks = blocks_.load(std::memory_order_relaxed);
  const unsigned int last_block_index =
      static_cast<unsigned int>(blocks->size() - 1);
  for (unsigned int block_index = 0; block_index < last_block_index;
       ++block_index) {
    Block* block = blocks->LoadBlock(block_index, kAcquireLoad);
    block->UpdateAfterYoungEvacuation(isolate_);
  }
  // Handle last block separately, as it is not filled to capacity.
  const int max_index = IndexInBlock(size() - 1, last_block_index) + 1;
  blocks->LoadBlock(last_block_index, kAcquireLoad)
      ->UpdateAfterYoungEvacuation(isolate_, max_index);
}
References blocks_, v8::internal::DCHECK(), empty(), IndexInBlock(), isolate_, v8::kAcquireLoad, v8::internal::StringForwardingTable::BlockVector::LoadBlock(), v8::internal::StringForwardingTable::BlockVector::size(), size(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), and v8::internal::v8_flags.
Referenced by v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation().
UpdateForwardString()
void v8::internal::StringForwardingTable::UpdateForwardString (int index, Tagged< String > forward_to)
Definition at line 223 of file string-forwarding-table.cc.
                                                                           {
  CHECK_LT(index, size());
  uint32_t index_in_block;
  const uint32_t block_index = BlockForIndex(index, &index_in_block);
  Block* block = blocks_.load(std::memory_order_acquire)
                     ->LoadBlock(block_index, kAcquireLoad);
  block->record(index_in_block)->set_forward_string(forward_to);
}
References BlockForIndex(), blocks_, CHECK_LT, v8::internal::index, v8::kAcquireLoad, v8::internal::StringForwardingTable::Block::record(), v8::internal::StringForwardingTable::Record::set_forward_string(), and size().
Referenced by v8::internal::anonymous_namespace{string-table.cc}::SetInternalizedReference().
Member Data Documentation
block_vector_storage_
std::vector<std::unique_ptr<BlockVector> > v8::internal::StringForwardingTable::block_vector_storage_ [private]
Definition at line 98 of file string-forwarding-table.h.
Referenced by EnsureCapacity(), InitializeBlockVector(), and Reset().
blocks_
std::atomic<BlockVector*> v8::internal::StringForwardingTable::blocks_ [private]
Definition at line 92 of file string-forwarding-table.h.
Referenced by EnsureCapacity(), GetExternalResource(), GetRawHash(), InitializeBlockVector(), IterateElements(), Reset(), UpdateAfterFullEvacuation(), UpdateAfterYoungEvacuation(), UpdateForwardString(), and ~StringForwardingTable().
grow_mutex_
base::Mutex v8::internal::StringForwardingTable::grow_mutex_ [private]
Definition at line 100 of file string-forwarding-table.h.
Referenced by EnsureCapacity().
isolate_
Isolate* v8::internal::StringForwardingTable::isolate_ [private]
Definition at line 91 of file string-forwarding-table.h.
Referenced by Reset(), TearDown(), UpdateAfterFullEvacuation(), and UpdateAfterYoungEvacuation().
kInitialBlockSize
constexpr int v8::internal::StringForwardingTable::kInitialBlockSize = 16 [static], [constexpr]
Definition at line 29 of file string-forwarding-table.h.
Referenced by BlockForIndex(), IndexInBlock(), and InitializeBlockVector().
kInitialBlockSizeHighestBit
constexpr int v8::internal::StringForwardingTable::kInitialBlockSizeHighestBit [static], [constexpr]
Initial value:
=
      kBitsPerInt - base::bits::CountLeadingZeros32(kInitialBlockSize) - 1
Definition at line 31 of file string-forwarding-table.h.
Referenced by BlockForIndex(), CapacityForBlock(), and IndexInBlock().
kInitialBlockVectorCapacity
constexpr int v8::internal::StringForwardingTable::kInitialBlockVectorCapacity = 4 [static], [constexpr]
Definition at line 34 of file string-forwarding-table.h.
Referenced by InitializeBlockVector().
next_free_index_
std::atomic<int> v8::internal::StringForwardingTable::next_free_index_ [private]
Definition at line 99 of file string-forwarding-table.h.
Referenced by AddExternalResourceAndHash(), AddForwardString(), Reset(), and size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-forwarding-table.h
/mnt/V8SourceCode/src/objects/string-forwarding-table-inl.h
/mnt/V8SourceCode/src/objects/string-forwarding-table.cc