v8::internal::maglev::ArgumentsElements Class Reference
#include <maglev-ir.h>
Public Member Functions
ArgumentsElements (uint64_t bitfield, CreateArgumentsType type, int formal_parameter_count)
Input & arguments_count_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
CreateArgumentsType type () const
int formal_parameter_count () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, ArgumentsElements >
Private Attributes
CreateArgumentsType type_
int formal_parameter_count_
Additional Inherited Members
Detailed Description
Definition at line 6524 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ArgumentsElements::Base = FixedInputValueNodeT<1, ArgumentsElements> [private]
Definition at line 6525 of file maglev-ir.h.
Constructor & Destructor Documentation
ArgumentsElements()
v8::internal::maglev::ArgumentsElements::ArgumentsElements (uint64_t bitfield, CreateArgumentsType type, int formal_parameter_count) [inline], [explicit]
Definition at line 6528 of file maglev-ir.h.
      : Base(bitfield),
        type_(type),
        formal_parameter_count_(formal_parameter_count) {}
Member Function Documentation
arguments_count_input()
Input& v8::internal::maglev::ArgumentsElements::arguments_count_input () [inline]
Definition at line 6541 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
formal_parameter_count()
int v8::internal::maglev::ArgumentsElements::formal_parameter_count () const [inline]
Definition at line 6549 of file maglev-ir.h.
{ return formal_parameter_count_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::ArgumentsElements::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ArgumentsElements::MaxCallStackArgs () const [inline]
Definition at line 6543 of file maglev-ir.h.
{ return 0; }
PrintParams()
void v8::internal::maglev::ArgumentsElements::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 6546 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::ArgumentsElements::SetValueLocationConstraints ()
type()
CreateArgumentsType v8::internal::maglev::ArgumentsElements::type () const [inline]
Definition at line 6548 of file maglev-ir.h.
{ return type_; }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildNestedValue(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject().
Member Data Documentation
formal_parameter_count_
int v8::internal::maglev::ArgumentsElements::formal_parameter_count_ [private]
Definition at line 6553 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ArgumentsElements::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 6539 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ArgumentsElements::kProperties [static], [constexpr]
Initial value:
= OpProperties::Call() |
                                              OpProperties::CanAllocate() |
                                              OpProperties::NotIdempotent()
Definition at line 6534 of file maglev-ir.h.
type_
CreateArgumentsType v8::internal::maglev::ArgumentsElements::type_ [private]
Definition at line 6552 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h