v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next > Class Template Reference
#include <wasm-in-js-inlining-reducer-inl.h>
Public Member Functions
V< Any > REDUCE() Call (V< CallTarget > callee, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects)
Private Member Functions
V< Any > TryInlineWasmCall (const wasm::WasmModule *module, wasm::NativeModule *native_module, uint32_t func_idx, base::Vector< const OpIndex > arguments)
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >
Definition at line 37 of file wasm-in-js-inlining-reducer-inl.h.
Member Function Documentation
Call()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call (V< CallTarget > callee, OptionalV< turboshaft::FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects) [inline]
Definition at line 41 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    if (!descriptor->js_wasm_call_parameters) {
      // Regular call, nothing to do with Wasm or inlining. Proceed untouched...
      return Next::ReduceCall(callee, frame_state, arguments, descriptor,
                              effects);
    }
    // We shouldn't have attached `JSWasmCallParameters` at this call, unless
    // we have TS Wasm-in-JS inlining enabled.
    CHECK(v8_flags.turboshaft_wasm_in_js_inlining);
    const wasm::WasmModule* module =
        descriptor->js_wasm_call_parameters->module();
    wasm::NativeModule* native_module =
        descriptor->js_wasm_call_parameters->native_module();
    uint32_t func_idx = descriptor->js_wasm_call_parameters->function_index();
    V<Any> result =
        TryInlineWasmCall(module, native_module, func_idx, arguments);
    if (result.valid()) {
      return result;
    } else {
      // The JS-to-Wasm wrapper was already inlined by the earlier TurboFan
      // phase, specifically `JSInliner::ReduceJSWasmCall`. However, it did
      // not toggle the thread-in-Wasm flag, since we don't want to set it
      // in the inline case above.
      // For the non-inline case, we need to toggle the flag now.
      // TODO(dlehmann,353475584): Reuse the code from
      // `WasmGraphBuilderBase::BuildModifyThreadInWasmFlag`, but that
      // requires a different assembler stack...
      OpIndex isolate_root = __ LoadRootRegister();
      V<WordPtr> thread_in_wasm_flag_address =
          __ Load(isolate_root, LoadOp::Kind::RawAligned().Immutable(),
                  MemoryRepresentation::UintPtr(),
                  Isolate::thread_in_wasm_flag_address_offset());
      __ Store(thread_in_wasm_flag_address, __ Word32Constant(1),
               LoadOp::Kind::RawAligned(), MemoryRepresentation::Int32(),
               compiler::kNoWriteBarrier);
      result =
          Next::ReduceCall(callee, frame_state, arguments, descriptor, effects);
      __ Store(thread_in_wasm_flag_address, __ Word32Constant(0),
               LoadOp::Kind::RawAligned(), MemoryRepresentation::Int32(),
               compiler::kNoWriteBarrier);
      return result;
    }
  }
References __, CHECK, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::kNoWriteBarrier, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::base::internal::result, v8::internal::wasm::liftoff::Store(), v8::internal::Isolate::thread_in_wasm_flag_address_offset(), v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::internal::v8_flags.
TryInlineWasmCall()
template<class Next >
V< Any > v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::TryInlineWasmCall (const wasm::WasmModule * module, wasm::NativeModule * native_module, uint32_t func_idx, base::Vector< const OpIndex > arguments) [private]
Definition at line 1258 of file wasm-in-js-inlining-reducer-inl.h.
                                                            {
  const wasm::WasmFunction& func = module->functions[func_idx];
  TRACE("Considering wasm function ["
        << func_idx << "] "
        << JSInliner::WasmFunctionNameForTrace(native_module, func_idx)
        << " of module " << module << " for inlining");
  if (wasm::is_asmjs_module(module)) {
    TRACE("- not inlining: asm.js-in-JS inlining is not supported");
    return OpIndex::Invalid();
  }
  if (func_idx < module->num_imported_functions) {
    TRACE("- not inlining: call to an imported function");
    return OpIndex::Invalid();
  }
  DCHECK_LT(func_idx - module->num_imported_functions,
            module->num_declared_functions);
  // TODO(42204563): Support shared-everything proposal (at some point, or
  // possibly never).
  bool is_shared = module->type(func.sig_index).is_shared;
  if (is_shared) {
    TRACE("- not inlining: shared everything is not supported");
    return OpIndex::Invalid();
  }
  base::Vector<const uint8_t> module_bytes = native_module->wire_bytes();
  const uint8_t* start = module_bytes.begin() + func.code.offset();
  const uint8_t* end = module_bytes.begin() + func.code.end_offset();
  wasm::FunctionBody func_body{func.sig, func.code.offset(), start, end,
                               is_shared};
  auto env = wasm::CompilationEnv::ForModule(native_module);
  wasm::WasmDetectedFeatures detected{};
  // JS-to-Wasm wrapper inlining doesn't support multi-value at the moment,
  // so we should never reach here with more than 1 return value.
  DCHECK_LE(func.sig->return_count(), 1);
  base::Vector<const OpIndex> arguments_without_instance =
      arguments.SubVectorFrom(1);
  V<WasmTrustedInstanceData> trusted_instance_data =
      arguments[wasm::kWasmInstanceDataParameterIndex];
  Block* inlinee_body_and_rest = __ NewBlock();
  __ Goto(inlinee_body_and_rest);
  // First pass: Decode Wasm body to see if we could inline or would bail out.
  // Emit into an unreachable block. We are not interested in the operations at
  // this point, only in the decoder status afterwards.
  Block* unreachable = __ NewBlock();
  __ Bind(unreachable);
  using Interface = WasmInJsInliningInterface<Assembler<ReducerList>>;
  using Decoder =
      wasm::WasmFullDecoder<typename Interface::ValidationTag, Interface>;
  Decoder can_inline_decoder(Asm().phase_zone(), env.module,
                             env.enabled_features, &detected, func_body, Asm(),
                             arguments_without_instance, trusted_instance_data);
  DCHECK(env.module->function_was_validated(func_idx));
  can_inline_decoder.Decode();
  // The function was already validated, so decoding can only fail if we bailed
  // out due to an unsupported instruction.
  if (!can_inline_decoder.ok()) {
    TRACE("- not inlining: " << can_inline_decoder.error().message());
    __ Bind(inlinee_body_and_rest);
    return OpIndex::Invalid();
  }
  // Second pass: Actually emit the inlinee instructions now.
  __ Bind(inlinee_body_and_rest);
  Decoder emitting_decoder(Asm().phase_zone(), env.module, env.enabled_features,
                           &detected, func_body, Asm(),
                           arguments_without_instance, trusted_instance_data);
  emitting_decoder.Decode();
  DCHECK(emitting_decoder.ok());
  DCHECK(emitting_decoder.interface().Result().valid());
  TRACE("- inlining");
  return emitting_decoder.interface().Result();
}
References __, v8::base::Vector< T >::begin(), v8::internal::wasm::WasmFunction::code, v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, v8::internal::Decoder< V >::Decode(), v8::internal::compiler::end(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::CompilationEnv::ForModule(), v8::internal::wasm::WasmModule::functions, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::wasm::is_asmjs_module(), v8::internal::is_shared, v8::internal::wasm::TypeDefinition::is_shared, v8::internal::wasm::kWasmInstanceDataParameterIndex, v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::WasmModule::num_imported_functions, v8::internal::wasm::WireBytesRef::offset(), v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, v8::base::Vector< T >::SubVectorFrom(), v8::internal::TRACE(), v8::internal::wasm::WasmModule::type(), v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::wasm::NativeModule::wire_bytes().
Referenced by v8::internal::compiler::turboshaft::WasmInJSInliningReducer< Next >::Call().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-in-js-inlining-reducer-inl.h