v8::internal::WasmDebugBreakFrameConstants Class Reference
#include <frame-constants-arm.h>
Static Public Member Functions
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
static int GetPushedGpRegisterOffset (int reg_code)
static int GetPushedFpRegisterOffset (int reg_code)
Static Public Attributes
static constexpr RegList kPushedGpRegs
static constexpr DoubleRegList kPushedFpRegs
static constexpr int kNumPushedGpRegisters = kPushedGpRegs.Count()
static constexpr int kNumPushedFpRegisters = kPushedFpRegs.Count()
static constexpr int kLastPushedGpRegisterOffset
static constexpr int kLastPushedFpRegisterOffset
static constexpr Simd128RegList kPushedSimd128Regs
Detailed Description
Definition at line 109 of file frame-constants-arm.h.
Member Function Documentation
GetPushedFpRegisterOffset() [1/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 137 of file frame-constants-arm.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kDoubleSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, v8::internal::kDoubleSize, kLastPushedFpRegisterOffset, and kPushedFpRegs.
Referenced by v8::internal::wasm::DebugInfoImpl::GetValue().
GetPushedFpRegisterOffset() [2/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 153 of file frame-constants-arm64.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSimd128Size;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedFpRegisterOffset, kPushedFpRegs, and v8::internal::kSimd128Size.
GetPushedFpRegisterOffset() [3/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 99 of file frame-constants-ia32.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSimd128Size;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedFpRegisterOffset, kPushedFpRegs, and v8::internal::kSimd128Size.
GetPushedFpRegisterOffset() [4/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 93 of file frame-constants-loong64.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kDoubleSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, v8::internal::kDoubleSize, kLastPushedFpRegisterOffset, and kPushedFpRegs.
GetPushedFpRegisterOffset() [5/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 91 of file frame-constants-mips64.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kDoubleSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, v8::internal::kDoubleSize, kLastPushedFpRegisterOffset, and kPushedFpRegs.
GetPushedFpRegisterOffset() [6/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 91 of file frame-constants-ppc.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSimd128Size;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedFpRegisterOffset, kPushedFpRegs, and v8::internal::kSimd128Size.
GetPushedFpRegisterOffset() [7/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 86 of file frame-constants-riscv.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kDoubleSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, v8::internal::kDoubleSize, kLastPushedFpRegisterOffset, and kPushedFpRegs.
GetPushedFpRegisterOffset() [8/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 84 of file frame-constants-s390.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSimd128Size;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedFpRegisterOffset, kPushedFpRegs, and v8::internal::kSimd128Size.
GetPushedFpRegisterOffset() [9/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedFpRegisterOffset (int reg_code) [inline], [static]
Definition at line 140 of file frame-constants-x64.h.
                                                     {
    DCHECK_NE(0, kPushedFpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedFpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedFpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSimd128Size;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedFpRegisterOffset, kPushedFpRegs, and v8::internal::kSimd128Size.
GetPushedGpRegisterOffset() [1/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 129 of file frame-constants-arm.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::wasm::DebugInfoImpl::GetValue().
GetPushedGpRegisterOffset() [2/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 145 of file frame-constants-arm64.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [3/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 91 of file frame-constants-ia32.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [4/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 85 of file frame-constants-loong64.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [5/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 83 of file frame-constants-mips64.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [6/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 83 of file frame-constants-ppc.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [7/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 78 of file frame-constants-riscv.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [8/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 76 of file frame-constants-s390.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
GetPushedGpRegisterOffset() [9/9]
static int v8::internal::WasmDebugBreakFrameConstants::GetPushedGpRegisterOffset (int reg_code) [inline], [static]
Definition at line 132 of file frame-constants-x64.h.
                                                     {
    DCHECK_NE(0, kPushedGpRegs.bits() & (1 << reg_code));
    uint32_t lower_regs =
        kPushedGpRegs.bits() & ((uint32_t{1} << reg_code) - 1);
    return kLastPushedGpRegisterOffset +
           base::bits::CountPopulation(lower_regs) * kSystemPointerSize;
  }
References v8::internal::RegListBase< RegisterT >::bits(), v8::base::bits::CountPopulation(), DCHECK_NE, kLastPushedGpRegisterOffset, kPushedGpRegs, and v8::internal::kSystemPointerSize.
Member Data Documentation
kLastPushedFpRegisterOffset
static constexpr int v8::internal::WasmDebugBreakFrameConstants::kLastPushedFpRegisterOffset [static], [constexpr]
Initial value:
=
      kLastPushedGpRegisterOffset - kDoubleSize * kNumPushedFpRegisters
Definition at line 125 of file frame-constants-arm.h.
Referenced by GetPushedFpRegisterOffset().
kLastPushedGpRegisterOffset
static constexpr int v8::internal::WasmDebugBreakFrameConstants::kLastPushedGpRegisterOffset [static], [constexpr]
Initial value:
=
      -TypedFrameConstants::kFixedFrameSizeFromFp -
      kSystemPointerSize * kNumPushedGpRegisters
Definition at line 122 of file frame-constants-arm.h.
Referenced by GetPushedGpRegisterOffset().
kNumPushedFpRegisters
static constexpr int v8::internal::WasmDebugBreakFrameConstants::kNumPushedFpRegisters = kPushedFpRegs.Count() [static], [constexpr]
Definition at line 120 of file frame-constants-arm.h.
kNumPushedGpRegisters
static constexpr int v8::internal::WasmDebugBreakFrameConstants::kNumPushedGpRegisters = kPushedGpRegs.Count() [static], [constexpr]
Definition at line 119 of file frame-constants-arm.h.
kPushedFpRegs
static constexpr DoubleRegList v8::internal::WasmDebugBreakFrameConstants::kPushedFpRegs [static], [constexpr]
Initial value:
= {d0, d1, d2, d3, d4, d5, d6,
                                                  d7, d8, d9, d10, d11, d12}
Definition at line 116 of file frame-constants-arm.h.
Referenced by GetPushedFpRegisterOffset().
kPushedGpRegs
static constexpr RegList v8::internal::WasmDebugBreakFrameConstants::kPushedGpRegs [static], [constexpr]
Initial value:
= {r0, r1, r2, r3, r4,
                                            r5, r6, r7, r8, r9}
Definition at line 112 of file frame-constants-arm.h.
Referenced by GetPushedGpRegisterOffset().
kPushedSimd128Regs
constexpr Simd128RegList v8::internal::WasmDebugBreakFrameConstants::kPushedSimd128Regs [static], [constexpr]
Initial value:
= {
      v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12}
Definition at line 70 of file frame-constants-ppc.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/arm/frame-constants-arm.h
/mnt/V8SourceCode/src/execution/arm64/frame-constants-arm64.h
/mnt/V8SourceCode/src/execution/ia32/frame-constants-ia32.h
/mnt/V8SourceCode/src/execution/loong64/frame-constants-loong64.h
/mnt/V8SourceCode/src/execution/mips64/frame-constants-mips64.h
/mnt/V8SourceCode/src/execution/ppc/frame-constants-ppc.h
/mnt/V8SourceCode/src/execution/riscv/frame-constants-riscv.h
/mnt/V8SourceCode/src/execution/s390/frame-constants-s390.h
/mnt/V8SourceCode/src/execution/x64/frame-constants-x64.h