v8::Proxy Class Reference
An instance of the built-in Proxy constructor (ECMA-262, 6th Edition, 26.2.1).
#include <v8-proxy.h>
Public Member Functions
Local< Value > GetTarget ()
Local< Value > GetHandler ()
bool IsRevoked () const
void Revoke ()
Static Public Member Functions
static MaybeLocal< Proxy > New (Local< Context > context, Local< Object > local_target, Local< Object > local_handler)
Creates a new Proxy for the target object.
static Proxy * Cast (Value *value)
Private Member Functions
Proxy ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in Proxy constructor (ECMA-262, 6th Edition, 26.2.1).
Definition at line 21 of file v8-proxy.h.
Constructor & Destructor Documentation
Proxy()
v8::Proxy::Proxy () [private]
Member Function Documentation
Cast()
static Proxy* v8::Proxy::Cast (Value * value) [inline], [static]
Definition at line 35 of file v8-proxy.h.
                                             {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Proxy*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::Proxy::CheckCast (Value * obj) [static], [private]
Definition at line 3987 of file api.cc.
                                   {
  Utils::ApiCheck(that->IsProxy(), "v8::Proxy::Cast", "Value is not a Proxy");
}
References v8::Utils::ApiCheck(), and v8::Value::IsProxy().
GetHandler()
Local< Value > v8::Proxy::GetHandler ()
Definition at line 8746 of file api.cc.
                               {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return Utils::ToLocal(i::direct_handle(self->handler(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
GetTarget()
Local< Value > v8::Proxy::GetTarget ()
Definition at line 8740 of file api.cc.
                              {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return Utils::ToLocal(i::direct_handle(self->target(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
IsRevoked()
bool v8::Proxy::IsRevoked () const
Definition at line 8752 of file api.cc.
                            {
  return Utils::OpenDirectHandle(this)->IsRevoked();
}
References v8::Utils::OpenDirectHandle().
New()
MaybeLocal< Proxy > v8::Proxy::New (Local< Context > context, Local< Object > local_target, Local< Object > local_handler) [static]
Creates a new Proxy for the target object.
Definition at line 8761 of file api.cc.
                                                          {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Proxy_New};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto target = Utils::OpenDirectHandle(*local_target);
  auto handler = Utils::OpenDirectHandle(*local_handler);
  // The API doesn't distinguish revocable proxies, so we must assume that all
  // objects created through it are revocable.
  bool api_proxies_assumed_revocable = true;
  return api_scope.EscapeMaybe(i::JSProxy::New(i_isolate, target, handler,
                                               api_proxies_assumed_revocable));
}
References v8::internal::JSProxy::New(), and v8::Utils::OpenDirectHandle().
Revoke()
void v8::Proxy::Revoke ()
Definition at line 8756 of file api.cc.
                   {
  auto self = Utils::OpenDirectHandle(this);
  i::JSProxy::Revoke(self);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::JSProxy::Revoke().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-proxy.h
/mnt/V8SourceCode/src/api/api.cc