v8::internal::compiler::JSLoadNamedNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSLoadNamedNode (Node *node)
const NamedAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1563 of file js-operator.h.
Constructor & Destructor Documentation
JSLoadNamedNode()
constexpr v8::internal::compiler::JSLoadNamedNode::JSLoadNamedNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1565 of file js-operator.h.
                                                 : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSLoadNamed, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const NamedAccess& v8::internal::compiler::JSLoadNamedNode::Parameters () const [inline]
Definition at line 1569 of file js-operator.h.
{ return NamedAccessOf(node()->op()); }
References v8::internal::compiler::NamedAccessOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadNamed().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h