v8::internal::CodeTracer::Scope Class Reference
#include <code-tracer.h>
Public Member Functions
Scope (CodeTracer *tracer)
~Scope ()
FILE * file () const
Private Attributes
CodeTracer * tracer_
Detailed Description
Definition at line 43 of file code-tracer.h.
Constructor & Destructor Documentation
Scope()
v8::internal::CodeTracer::Scope::Scope (CodeTracer * tracer) [inline], [explicit]
Definition at line 45 of file code-tracer.h.
: tracer_(tracer) { tracer->OpenFile(); }
References v8::internal::CodeTracer::OpenFile().
 Scope()
v8::internal::CodeTracer::Scope::~Scope () [inline]
Definition at line 46 of file code-tracer.h.
{ tracer_->CloseFile(); }
Member Function Documentation
file()
FILE* v8::internal::CodeTracer::Scope::file () const [inline]
Definition at line 48 of file code-tracer.h.
{ return tracer_->file(); }
Referenced by v8::internal::baseline::BaselineBatchCompilerJob::BaselineBatchCompilerJob(), v8::internal::RegExpImpl::Compile(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev(), v8::internal::SharedFunctionInfo::DisableOptimization(), v8::internal::SharedFunctionInfo::DiscardCompiledMetadata(), v8::internal::Deoptimizer::DoComputeInlinedExtraArguments(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::baseline::BaselineCompilerTask::Install(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::Builtins::PrintBuiltinCode(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTracePrefix(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTraceSuffix(), v8::internal::Deoptimizer::ProcessDeoptReason(), v8::internal::RUNTIME_FUNCTION(), v8::internal::baseline::BaselineBatchCompiler::ShouldCompileBatch(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedJob(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedMaglevCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceCompletedJob(), v8::internal::Deoptimizer::TraceDeoptAll(), v8::internal::Deoptimizer::TraceDeoptBegin(), v8::internal::Deoptimizer::TraceEvictFromOptimizedCodeCache(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishBaselineCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishMaglevCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishTurbofanCompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceMarkForAlwaysOpt(), v8::internal::Deoptimizer::TraceMarkForDeoptimization(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizedCodeCacheHit(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeForAlwaysOpt(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRAvailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRFinished(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRStarted(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRUnavailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TracePrepareJob(), v8::internal::anonymous_namespace{tiering-manager.cc}::TraceRecompile(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceStartMaglevCompile(), and v8::internal::anonymous_namespace{tiering-manager.cc}::TrySetOsrUrgency().
Member Data Documentation
tracer_
CodeTracer* v8::internal::CodeTracer::Scope::tracer_ [private]
Definition at line 51 of file code-tracer.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/diagnostics/code-tracer.h