v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits > Class Template Reference
Static Public Member Functions
static Handle< Object > GetImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode)
static void CopyElementsImpl (Isolate *isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size)
static Maybe< bool > CollectValuesOrEntriesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int *nof_items, PropertyFilter filter)
static Maybe< int64_t > IndexOfValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > search_value, size_t start_from, size_t length)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >
Definition at line 3198 of file elements.cc.
Member Function Documentation
CollectValuesOrEntriesImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CollectValuesOrEntriesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int * nof_items, PropertyFilter filter) [inline], [static]
Definition at line 3280 of file elements.cc.
                                             {
    DirectHandle<FixedDoubleArray> elements(
        Cast<FixedDoubleArray>(object->elements()), isolate);
    int count = 0;
    uint32_t length = elements->length();
    for (uint32_t index = 0; index < length; ++index) {
      InternalIndex entry(index);
      if (!Subclass::HasEntryImpl(isolate, *elements, entry)) continue;
      DirectHandle<Object> value = Subclass::GetImpl(isolate, *elements, entry);
      if (get_entries) {
        value = MakeEntryPair(isolate, index, value);
      }
      values_or_entries->set(count++, *value);
    }
    *nof_items = count;
    return Just(true);
  }
References v8::internal::index, v8::Just(), v8::internal::length, v8::internal::MakeEntryPair(), and v8::internal::value.
CopyElementsImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::CopyElementsImpl (Isolate * isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size) [inline], [static]
Definition at line 3232 of file elements.cc.
                                                               {
    DisallowGarbageCollection no_gc;
    switch (from_kind) {
      case PACKED_SMI_ELEMENTS:
        CopyPackedSmiToDoubleElements(from, from_start, to, to_start,
                                      packed_size, copy_size);
        break;
      case HOLEY_SMI_ELEMENTS:
        CopySmiToDoubleElements(from, from_start, to, to_start, copy_size);
        break;
      case PACKED_DOUBLE_ELEMENTS:
      case HOLEY_DOUBLE_ELEMENTS:
        CopyDoubleToDoubleElements(from, from_start, to, to_start, copy_size);
        break;
      case PACKED_ELEMENTS:
      case PACKED_FROZEN_ELEMENTS:
      case PACKED_SEALED_ELEMENTS:
      case PACKED_NONEXTENSIBLE_ELEMENTS:
      case HOLEY_ELEMENTS:
      case HOLEY_FROZEN_ELEMENTS:
      case HOLEY_SEALED_ELEMENTS:
      case HOLEY_NONEXTENSIBLE_ELEMENTS:
      case SHARED_ARRAY_ELEMENTS:
        CopyObjectToDoubleElements(from, from_start, to, to_start, copy_size);
        break;
      case DICTIONARY_ELEMENTS:
        CopyDictionaryToDoubleElements(isolate, from, from_start, to, to_start,
                                       copy_size);
        break;
      case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
      case SLOW_SLOPPY_ARGUMENTS_ELEMENTS:
      case FAST_STRING_WRAPPER_ELEMENTS:
      case SLOW_STRING_WRAPPER_ELEMENTS:
      case WASM_ARRAY_ELEMENTS:
      case NO_ELEMENTS:
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
        TYPED_ARRAYS(TYPED_ARRAY_CASE)
        RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
        // This function is currently only used for JSArrays with non-zero
        // length.
        UNREACHABLE();
    }
  }
References v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToDoubleElements(), v8::internal::anonymous_namespace{elements.cc}::CopyDoubleToDoubleElements(), v8::internal::anonymous_namespace{elements.cc}::CopyObjectToDoubleElements(), v8::internal::anonymous_namespace{elements.cc}::CopyPackedSmiToDoubleElements(), v8::internal::anonymous_namespace{elements.cc}::CopySmiToDoubleElements(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::NO_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNREACHABLE(), and v8::internal::WASM_ARRAY_ELEMENTS.
GetImpl()
template<typename Subclass , typename KindTraits >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::GetImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 3201 of file elements.cc.
                                                     {
    return FixedDoubleArray::get(Cast<FixedDoubleArray>(backing_store),
                                 entry.as_int(), isolate);
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::FixedDoubleArray::get().
IndexOfValueImpl()
template<typename Subclass , typename KindTraits >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::IndexOfValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > search_value, size_t start_from, size_t length) [inline], [static]
Definition at line 3301 of file elements.cc.
                                                                           {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *receiver));
    DisallowGarbageCollection no_gc;
    Tagged<FixedArrayBase> elements_base = receiver->elements();
    Tagged<Object> value = *search_value;
    length = std::min(static_cast<size_t>(elements_base->length()), length);
    if (start_from >= length) return Just<int64_t>(-1);
    if (!IsNumber(value)) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      if (IsUndefined(value)) {
        Tagged<FixedDoubleArray> elements =
            Cast<FixedDoubleArray>(receiver->elements());
        static_assert(FixedDoubleArray::kMaxLength <=
                      std::numeric_limits<int>::max());
        for (size_t k = start_from; k < length; ++k) {
          int k_int = static_cast<int>(k);
          if (elements->is_undefined(k_int)) {
            return Just<int64_t>(k);
          }
        }
      }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      return Just<int64_t>(-1);
    }
    if (IsNaN(value)) {
      return Just<int64_t>(-1);
    }
    double numeric_search_value = Object::NumberValue(value);
    Tagged<FixedDoubleArray> elements =
        Cast<FixedDoubleArray>(receiver->elements());
    static_assert(FixedDoubleArray::kMaxLength <=
                  std::numeric_limits<int>::max());
    for (size_t k = start_from; k < length; ++k) {
      int k_int = static_cast<int>(k);
      if (elements->is_the_hole(k_int)) {
        continue;
      }
      if (elements->get_scalar(k_int) == numeric_search_value) {
        return Just<int64_t>(k);
      }
    }
    return Just<int64_t>(-1);
  }
References v8::internal::DCHECK(), v8::internal::IsNaN(), v8::internal::IsNumber(), v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), v8::internal::JSObject::PrototypeHasNoElements(), and v8::internal::value.
SetImpl() [1/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 3208 of file elements.cc.
                                                   {
    SetImpl(holder->elements(), entry, value);
  }
References v8::internal::value.
SetImpl() [2/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 3213 of file elements.cc.
                                                                        {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    if (IsUndefined(value)) {
      Cast<FixedDoubleArray>(backing_store)->set_undefined(entry.as_int());
      return;
    }
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    Cast<FixedDoubleArray>(backing_store)
        ->set(entry.as_int(), Object::NumberValue(value));
  }
References v8::internal::InternalIndex::as_int(), v8::internal::Object::NumberValue(), and v8::internal::value.
SetImpl() [3/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode) [inline], [static]
Definition at line 3225 of file elements.cc.
                                                    {
    Cast<FixedDoubleArray>(backing_store)
        ->set(entry.as_int(), Object::NumberValue(value));
  }
References v8::internal::InternalIndex::as_int(), v8::internal::Object::NumberValue(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc