v8_inspector::String16 Class Reference
#include <string-16.h>
Public Member Functions
String16 ()=default
String16 (const String16 &) V8_NOEXCEPT=default
String16 (String16 &&) V8_NOEXCEPT=default
String16 (const UChar *characters, size_t size)
String16 (const uint16_t *characters, size_t size)
String16 (const UChar *characters)
String16 (const char *characters)
String16 (const char *characters, size_t size)
String16 (std::string_view string)
String16 (const std::basic_string< UChar > &impl)
String16 (std::basic_string< UChar > &&impl)
String16 & operator= (const String16 &) V8_NOEXCEPT=default
String16 & operator= (String16 &&) V8_NOEXCEPT=default
int64_t toInteger64 (bool *ok=nullptr) const
uint64_t toUInt64 (bool *ok=nullptr) const
int toInteger (bool *ok=nullptr) const
std::pair< size_t, size_t > getTrimmedOffsetAndLength () const
String16 stripWhiteSpace () const
const uint16_t * characters16 () const
size_t length () const
bool isEmpty () const
UChar operator[] (size_t index) const
String16 substring (size_t pos, size_t len=UINT_MAX) const
size_t find (const String16 &str, size_t start=0) const
size_t reverseFind (const String16 &str, size_t start=UINT_MAX) const
size_t find (UChar c, size_t start=0) const
size_t reverseFind (UChar c, size_t start=UINT_MAX) const
void swap (String16 &other)
std::string utf8 () const
std::size_t hash () const
bool operator== (const String16 &other) const
bool operator< (const String16 &other) const
bool operator!= (const String16 &other) const
String16 operator+ (const String16 &other) const
String16 & operator+= (const String16 &other)
Static Public Member Functions
static String16 fromInteger (int)
static String16 fromInteger (size_t)
static String16 fromInteger64 (int64_t)
static String16 fromUInt64 (uint64_t)
static String16 fromDouble (double)
static String16 fromDouble (double, int precision)
static String16 fromUTF8 (const char *stringStart, size_t length)
static String16 fromUTF16LE (const UChar *stringStart, size_t length)
static String16 fromUTF16LE (const uint16_t *stringStart, size_t length)
template<typename... T>
static String16 concat (T... args)
Static Public Attributes
static const size_t kNotFound = static_cast<size_t>(-1)
Private Attributes
std::basic_string< UChar > m_impl
std::size_t hash_code = 0
Detailed Description
Definition at line 24 of file string-16.h.
Constructor & Destructor Documentation
String16() [1/11]
v8_inspector::String16::String16 () [default]
Referenced by fromDouble(), fromInteger(), fromInteger64(), fromUTF16LE(), fromUTF8(), operator+(), stripWhiteSpace(), and substring().
String16() [2/11]
v8_inspector::String16::String16 (const String16 &) [default]
String16() [3/11]
v8_inspector::String16::String16 (String16 &&) [default]
String16() [4/11]
v8_inspector::String16::String16 (const UChar * characters, size_t size)
Definition at line 51 of file string-16.cc.
    : m_impl(characters, size) {}
String16() [5/11]
v8_inspector::String16::String16 (const uint16_t * characters, size_t size)
Definition at line 53 of file string-16.cc.
    : m_impl(reinterpret_cast<const UChar*>(characters), size) {}
String16() [6/11]
v8_inspector::String16::String16 (const UChar * characters)
Definition at line 56 of file string-16.cc.
: m_impl(characters) {}
String16() [7/11]
v8_inspector::String16::String16 (const char * characters)
Definition at line 58 of file string-16.cc.
    : String16(characters, std::strlen(characters)) {}
String16() [8/11]
v8_inspector::String16::String16 (const char * characters, size_t size)
Definition at line 61 of file string-16.cc.
    : m_impl(characters, characters + size) {}
String16() [9/11]
v8_inspector::String16::String16 (std::string_view string)
Definition at line 63 of file string-16.cc.
    : String16(string.data(), string.length()) {}
String16() [10/11]
v8_inspector::String16::String16 (const std::basic_string< UChar > & impl) [explicit]
Definition at line 66 of file string-16.cc.
: m_impl(impl) {}
String16() [11/11]
v8_inspector::String16::String16 (std::basic_string< UChar > && impl) [explicit]
Definition at line 68 of file string-16.cc.
: m_impl(impl) {}
Member Function Documentation
characters16()
const uint16_t* v8_inspector::String16::characters16 () const [inline]
Definition at line 55 of file string-16.h.
                                       {
    return reinterpret_cast<const uint16_t*>(m_impl.c_str());
  }
References m_impl.
Referenced by v8_inspector::String16Builder::append(), v8_inspector::protocol::StringUtil::CharactersUTF16(), v8_inspector::computeCrc32(), v8_inspector::V8Console::createTask(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), getTrimmedOffsetAndLength(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), and toInteger64().
concat()
template<typename... T>
String16 v8_inspector::String16::concat (T... args) [static]
Definition at line 158 of file string-16.h.
                                   {
  String16Builder builder;
  builder.appendAll(args...);
  return builder.toString();
}
References v8_inspector::String16Builder::appendAll(), v8::base::args, and v8_inspector::String16Builder::toString().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForEntry(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethodList(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForProxy(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScopeList(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForSymbol(), and v8_inspector::anonymous_namespace{remote-object-id.cc}::serializeId().
find() [1/2]
size_t v8_inspector::String16::find (const String16 & str, size_t start = 0) const [inline]
Definition at line 64 of file string-16.h.
                                                           {
    return m_impl.find(str.m_impl, start);
  }
References m_impl.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment(), v8_inspector::anonymous_namespace{search-util.cc}::lineEndings(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), v8_inspector::RemoteObjectIdBase::parseId(), and v8_inspector::internal::V8DebuggerId::V8DebuggerId().
find() [2/2]
size_t v8_inspector::String16::find (UChar c, size_t start = 0) const [inline]
Definition at line 70 of file string-16.h.
{ return m_impl.find(c, start); }
References m_impl.
fromDouble() [1/2]
String16 v8_inspector::String16::fromDouble (double number) [static]
Definition at line 98 of file string-16.cc.
                                           {
  char arr[50];
  v8::base::Vector<char> buffer = v8::base::ArrayVector(arr);
  std::string_view str = v8::internal::DoubleToStringView(number, buffer);
  return String16(str);
}
References v8::base::ArrayVector(), v8::internal::DoubleToStringView(), and String16().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForNumber(), v8_inspector::V8Console::TimeEnd(), and v8_inspector::V8Console::TimeLog().
fromDouble() [2/2]
String16 v8_inspector::String16::fromDouble (double number, int precision) [static]
Definition at line 106 of file string-16.cc.
                                                          {
  char arr[v8::internal::kDoubleToPrecisionMaxChars];
  v8::base::Vector<char> buffer = v8::base::ArrayVector(arr);
  std::string_view str =
      v8::internal::DoubleToPrecisionStringView(number, precision, buffer);
  return String16(str);
}
References v8::base::ArrayVector(), v8::internal::DoubleToPrecisionStringView(), v8::internal::kDoubleToPrecisionMaxChars, and String16().
fromInteger() [1/2]
String16 v8_inspector::String16::fromInteger (int number) [static]
Definition at line 71 of file string-16.cc.
                                         {
  char arr[50];
  v8::base::Vector<char> buffer = v8::base::ArrayVector(arr);
  std::string_view str = v8::internal::IntToStringView(number, buffer);
  return String16(str);
}
References v8::base::ArrayVector(), v8::internal::IntToStringView(), and String16().
Referenced by v8_inspector::StackFrame::buildInspectorObject(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::buildInspectorObjectFor(), v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::buildRemoteObject(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::buildSampingHeapProfileNode(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::buildScopes(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::anonymous_namespace{v8-console.cc}::consoleContextToString(), v8_inspector::V8Console::Count(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::coverageToProtocol(), v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::currentDebugLocation(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForCollection(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethodList(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScopeList(), v8_inspector::V8DebuggerAgentImpl::disassembleWasmModule(), v8_inspector::V8HeapProfilerAgentImpl::getHeapObjectId(), v8_inspector::V8Debugger::IsFunctionBlackboxed(), v8_inspector::V8ProfilerAgentImpl::nextProfileId(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::anonymous_namespace{remote-object-id.cc}::serializeId(), v8_inspector::V8Debugger::ShouldBeSkipped(), and v8_inspector::V8StackTraceImpl::toString().
fromInteger() [2/2]
String16 v8_inspector::String16::fromInteger (size_t number) [static]
Definition at line 79 of file string-16.cc.
                                            {
  const size_t kBufferSize = 50;
  char buffer[kBufferSize];
#if defined(V8_OS_WIN)
  v8::base::OS::SNPrintF(buffer, kBufferSize, "%Iu", number);
#else
  v8::base::OS::SNPrintF(buffer, kBufferSize, "%zu", number);
#endif
  return String16(buffer);
}
References v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, v8::base::SNPrintF(), and String16().
fromInteger64()
String16 v8_inspector::String16::fromInteger64 (int64_t number) [static]
Definition at line 91 of file string-16.cc.
                                               {
  char buffer[50];
  v8::base::OS::SNPrintF(buffer, arraysize(buffer), "%" PRId64 "", number);
  return String16(buffer);
}
References arraysize, v8::base::SNPrintF(), and String16().
Referenced by v8_inspector::anonymous_namespace{remote-object-id.cc}::serializeId(), v8_inspector::V8StackTraceId::ToString(), and v8_inspector::V8DebuggerId::toString().
fromUInt64()
static String16 v8_inspector::String16::fromUInt64 (uint64_t) [static]
fromUTF16LE() [1/2]
String16 v8_inspector::String16::fromUTF16LE (const UChar * stringStart, size_t length) [static]
Definition at line 233 of file string-16.cc.
                                                                      {
#ifdef V8_TARGET_BIG_ENDIAN
  // Need to flip the byte order on big endian machines.
  String16Builder builder;
  builder.reserveCapacity(length);
  for (size_t i = 0; i < length; i++) {
    const UChar utf16be_char =
        stringStart[i] << 8 | (stringStart[i] >> 8 & 0x00FF);
    builder.append(utf16be_char);
  }
  return builder.toString();
#else
  // No need to do anything on little endian machines.
  return String16(stringStart, length);
#endif // V8_TARGET_BIG_ENDIAN
}
References v8_inspector::String16Builder::append(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, length(), v8_inspector::String16Builder::reserveCapacity(), String16(), and v8_inspector::String16Builder::toString().
Referenced by v8_inspector::protocol::StringUtil::fromUTF16LE(), and fromUTF16LE().
fromUTF16LE() [2/2]
String16 v8_inspector::String16::fromUTF16LE (const uint16_t * stringStart, size_t length) [static]
Definition at line 250 of file string-16.cc.
                                                                         {
  return fromUTF16LE(reinterpret_cast<const UChar*>(stringStart), length);
}
References fromUTF16LE(), and length().
fromUTF8()
String16 v8_inspector::String16::fromUTF8 (const char * stringStart, size_t length) [static]
Definition at line 229 of file string-16.cc.
                                                                  {
  return String16(UTF8ToUTF16(stringStart, length));
}
References length(), String16(), and v8_inspector::UTF8ToUTF16().
Referenced by v8_inspector::protocol::StringUtil::fromUTF8(), and v8_inspector::V8InspectorSessionImpl::unwrapObject().
getTrimmedOffsetAndLength()
std::pair< size_t, size_t > v8_inspector::String16::getTrimmedOffsetAndLength () const
Definition at line 127 of file string-16.cc.
                                                                  {
  if (!length()) return std::make_pair(0, 0);
  size_t start = 0;
  size_t end = length() - 1;
  // skip white space from start
  while (start <= end && isSpaceOrNewLine(characters16()[start])) ++start;
  // only white space
  if (start > end) return std::make_pair(0, 0);
  // skip white space from end
  while (end && isSpaceOrNewLine(characters16()[end])) --end;
  return std::make_pair(start, end + 1 - start);
}
References characters16(), v8::internal::compiler::end(), v8_inspector::anonymous_namespace{string-16.cc}::isSpaceOrNewLine(), and length().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint(), and stripWhiteSpace().
hash()
std::size_t v8_inspector::String16::hash () const [inline]
Definition at line 90 of file string-16.h.
                         {
    if (!hash_code) {
      for (char c : m_impl) hash_code = 31 * hash_code + c;
      // Map hash code 0 to 1. This double the number of hash collisions for 1,
      // but avoids recomputing the hash code.
      if (!hash_code) ++hash_code;
    }
    return hash_code;
  }
References hash_code, and m_impl.
isEmpty()
bool v8_inspector::String16::isEmpty () const [inline]
Definition at line 59 of file string-16.h.
{ return !m_impl.length(); }
References m_impl.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBindings(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::InjectedScript::bindObject(), v8_inspector::V8DebuggerScript::buildId(), v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), v8_inspector::AsyncStackTrace::capture(), v8_inspector::V8ProfilerAgentImpl::consoleProfileEnd(), v8_inspector::V8ConsoleMessage::contextDestroyed(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), v8_inspector::protocol::Binary::fromBase64(), v8_inspector::V8DebuggerScript::hash(), v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::InjectedScript::releaseObjectGroup(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines(), v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded(), and v8_inspector::StringBufferFrom().
length()
size_t v8_inspector::String16::length () const [inline]
Definition at line 58 of file string-16.h.
{ return m_impl.length(); }
References m_impl.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::String16Builder::append(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint(), v8_inspector::StackFrame::buildInspectorObject(), v8_inspector::protocol::StringUtil::CharacterCount(), v8_inspector::computeCrc32(), v8_inspector::anonymous_namespace{search-util.cc}::createSearchRegexSource(), v8_inspector::V8Console::createTask(), v8_inspector::V8DebuggerAgentImpl::didParseSource(), v8_inspector::V8ConsoleMessage::estimatedSize(), v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment(), v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL(), v8_inspector::protocol::Binary::fromBase64(), fromUTF16LE(), fromUTF8(), v8_inspector::V8Debugger::getTargetScopes(), getTrimmedOffsetAndLength(), v8_inspector::anonymous_namespace{search-util.cc}::lineEndings(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines(), v8_inspector::V8DebuggerScript::setSourceURL(), v8_inspector::V8DebuggerAgentImpl::CachedScript::size(), stripWhiteSpace(), toInteger64(), and v8_inspector::V8StackTraceImpl::toString().
operator!=()
bool v8_inspector::String16::operator!= (const String16 & other) const [inline]
Definition at line 106 of file string-16.h.
                                                      {
    return m_impl != other.m_impl;
  }
References m_impl.
operator+()
String16 v8_inspector::String16::operator+ (const String16 & other) const [inline]
Definition at line 109 of file string-16.h.
                                                         {
    return String16(m_impl + other.m_impl);
  }
References m_impl, and String16().
operator+=()
String16& v8_inspector::String16::operator+= (const String16 & other) [inline]
Definition at line 112 of file string-16.h.
                                                     {
    m_impl += other.m_impl;
    return *this;
  }
References m_impl.
operator<()
bool v8_inspector::String16::operator< (const String16 & other) const [inline]
Definition at line 103 of file string-16.h.
                                                     {
    return m_impl < other.m_impl;
  }
References m_impl.
operator=() [1/2]
String16& v8_inspector::String16::operator= (const String16 &) [default]
operator=() [2/2]
String16& v8_inspector::String16::operator= (String16 &&) [default]
operator==()
bool v8_inspector::String16::operator== (const String16 & other) const [inline]
Definition at line 100 of file string-16.h.
                                                      {
    return m_impl == other.m_impl;
  }
References m_impl.
operator[]()
UChar v8_inspector::String16::operator[] (size_t index) const [inline]
Definition at line 60 of file string-16.h.
{ return m_impl[index]; }
References v8::internal::index, and m_impl.
reverseFind() [1/2]
size_t v8_inspector::String16::reverseFind (const String16 & str, size_t start = UINT_MAX) const [inline]
Definition at line 67 of file string-16.h.
                                                                         {
    return m_impl.rfind(str.m_impl, start);
  }
References m_impl.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), and v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment().
reverseFind() [2/2]
size_t v8_inspector::String16::reverseFind (UChar c, size_t start = UINT_MAX) const [inline]
Definition at line 71 of file string-16.h.
                                                             {
    return m_impl.rfind(c, start);
  }
References m_impl.
stripWhiteSpace()
String16 v8_inspector::String16::stripWhiteSpace () const
Definition at line 145 of file string-16.cc.
                                         {
  std::pair<size_t, size_t> offsetAndLength = getTrimmedOffsetAndLength();
  if (offsetAndLength.second == 0) return String16();
  if (offsetAndLength.first == 0 && offsetAndLength.second == length() - 1) {
    return *this;
  }
  return substring(offsetAndLength.first, offsetAndLength.second);
}
References getTrimmedOffsetAndLength(), length(), String16(), and substring().
Referenced by v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment().
substring()
String16 v8_inspector::String16::substring (size_t pos, size_t len = UINT_MAX) const [inline]
Definition at line 61 of file string-16.h.
                                                              {
    return String16(m_impl.substr(pos, len));
  }
References m_impl, and String16().
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::breakpointHint(), v8_inspector::StackFrame::buildInspectorObject(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), v8_inspector::RemoteObjectIdBase::parseId(), v8_inspector::anonymous_namespace{search-util.cc}::scriptRegexpMatchesByLines(), v8_inspector::V8ConsoleMessage::setLocation(), stripWhiteSpace(), and v8_inspector::internal::V8DebuggerId::V8DebuggerId().
swap()
void v8_inspector::String16::swap (String16 & other) [inline]
Definition at line 74 of file string-16.h.
                             {
    m_impl.swap(other.m_impl);
    std::swap(hash_code, other.hash_code);
  }
References hash_code, and m_impl.
toInteger()
int v8_inspector::String16::toInteger (bool * ok = nullptr) const
Definition at line 118 of file string-16.cc.
                                      {
  int64_t result = toInteger64(ok);
  if (ok && *ok) {
    *ok = result <= std::numeric_limits<int>::max() &&
          result >= std::numeric_limits<int>::min();
  }
  return static_cast<int>(result);
}
References v8::base::internal::result, and toInteger64().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject(), v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), and v8_inspector::RemoteObjectIdBase::parseId().
toInteger64()
int64_t v8_inspector::String16::toInteger64 (bool * ok = nullptr) const
Definition at line 114 of file string-16.cc.
                                            {
  return charactersToInteger(characters16(), length(), ok);
}
References characters16(), v8_inspector::anonymous_namespace{string-16.cc}::charactersToInteger(), and length().
Referenced by v8_inspector::RemoteObjectIdBase::parseId(), toInteger(), v8_inspector::internal::V8DebuggerId::V8DebuggerId(), and v8_inspector::V8StackTraceId::V8StackTraceId().
toUInt64()
uint64_t v8_inspector::String16::toUInt64 (bool * ok = nullptr) const
utf8()
std::string v8_inspector::String16::utf8 () const
Definition at line 254 of file string-16.cc.
                               {
  return UTF16ToUTF8(m_impl.data(), m_impl.size());
}
References m_impl, and v8_inspector::UTF16ToUTF8().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue(), v8_inspector::V8Console::Count(), v8_inspector::V8Console::CountReset(), v8_inspector::V8DebuggerAgentImpl::disassembleWasmModule(), v8_inspector::V8DebuggerAgentImpl::getScriptSource(), v8_inspector::V8DebuggerAgentImpl::getWasmBytecode(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::getWrapOptions(), v8_inspector::V8DebuggerAgentImpl::nextWasmDisassemblyChunk(), v8_inspector::V8Console::Profile(), v8_inspector::V8Console::ProfileEnd(), v8_inspector::V8DebuggerAgentImpl::searchInContent(), and v8_inspector::V8DebuggerAgentImpl::setPauseOnExceptions().
Member Data Documentation
hash_code
std::size_t v8_inspector::String16::hash_code = 0 [mutable], [private]
Definition at line 123 of file string-16.h.
Referenced by hash(), and swap().
kNotFound
const size_t v8_inspector::String16::kNotFound = static_cast<size_t>(-1) [static]
Definition at line 26 of file string-16.h.
Referenced by v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::adjustBreakpointLocation(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{search-util.cc}::findMagicComment(), v8_inspector::anonymous_namespace{search-util.cc}::lineEndings(), v8_inspector::anonymous_namespace{v8-debugger-agent-impl.cc}::parseBreakpointId(), v8_inspector::RemoteObjectIdBase::parseId(), and v8_inspector::internal::V8DebuggerId::V8DebuggerId().
m_impl
std::basic_string<UChar> v8_inspector::String16::m_impl [private]
Definition at line 122 of file string-16.h.
Referenced by characters16(), find(), hash(), isEmpty(), length(), operator!=(), operator+(), operator+=(), operator<(), operator==(), operator[](), reverseFind(), substring(), swap(), and utf8().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/string-16.h
/mnt/V8SourceCode/src/inspector/string-16.cc