v8::internal::compiler::PairLoadStoreReducer Class Reference
#include <pair-load-store-reducer.h>
Public Member Functions
PairLoadStoreReducer (Editor *editor, MachineGraph *mcgraph, Isolate *isolate_)
const char * reducer_name () const override
Reduction Reduce (Node *node) override
Private Attributes
MachineGraph * mcgraph_
Isolate * isolate_
Detailed Description
Definition at line 27 of file pair-load-store-reducer.h.
Constructor & Destructor Documentation
PairLoadStoreReducer()
v8::internal::compiler::PairLoadStoreReducer::PairLoadStoreReducer (Editor * editor, MachineGraph * mcgraph, Isolate * isolate_)
Definition at line 58 of file pair-load-store-reducer.cc.
    : AdvancedReducer(editor), mcgraph_(mcgraph), isolate_(isolate) {}
Member Function Documentation
Reduce()
Reduction v8::internal::compiler::PairLoadStoreReducer::Reduce (Node * node) [override]
Definition at line 63 of file pair-load-store-reducer.cc.
                                                {
  if (cur->opcode() != IrOpcode::kStore) {
    return Reduction();
  }
  Node* prev = NodeProperties::GetEffectInput(cur);
  if (prev->opcode() != IrOpcode::kStore) {
    return Reduction();
  }
  if (!prev->OwnedBy(cur)) {
    return Reduction();
  }
  auto pairing = CanBePaired(prev, cur, mcgraph_->machine(), isolate_);
  if (!pairing) return Reduction();
  if (std::get<int>(*pairing) > 0) {
    prev->InsertInput(mcgraph_->zone(), 3, cur->InputAt(2));
  } else {
    NodeProperties::ReplaceValueInput(prev, cur->InputAt(1), 1);
    prev->InsertInput(mcgraph_->zone(), 2, cur->InputAt(2));
  }
  NodeProperties::ChangeOp(prev, std::get<const Operator*>(*pairing));
  Replace(cur, prev);
  cur->Kill();
  return Reduction(prev);
}
References v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc}::CanBePaired(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InsertInput(), isolate_, v8::internal::compiler::Node::Kill(), v8::internal::compiler::MachineGraph::machine(), mcgraph_, v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::OwnedBy(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), and v8::internal::compiler::MachineGraph::zone().
reducer_name()
const char* v8::internal::compiler::PairLoadStoreReducer::reducer_name () const [inline], [override]
Definition at line 33 of file pair-load-store-reducer.h.
{ return "PairLoadStoreReducer"; }
Member Data Documentation
isolate_
Isolate* v8::internal::compiler::PairLoadStoreReducer::isolate_ [private]
Definition at line 39 of file pair-load-store-reducer.h.
Referenced by Reduce().
mcgraph_
MachineGraph* v8::internal::compiler::PairLoadStoreReducer::mcgraph_ [private]
Definition at line 38 of file pair-load-store-reducer.h.
Referenced by Reduce().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/pair-load-store-reducer.h
/mnt/V8SourceCode/src/compiler/pair-load-store-reducer.cc