v8::internal::interpreter::BytecodeGenerator::ControlScope Class Reference
Classes
class DeferredCommands
Public Member Functions
ControlScope (BytecodeGenerator *generator)
~ControlScope ()
ControlScope (const ControlScope &)=delete
ControlScope & operator= (const ControlScope &)=delete
void Break (Statement *stmt)
void Continue (Statement *stmt)
void ReturnAccumulator (int source_position)
void AsyncReturnAccumulator (int source_position)
Protected Types
enum Command {
CMD_BREAK
, CMD_CONTINUE
, CMD_RETURN
, CMD_ASYNC_RETURN
,
CMD_RETHROW
 }
Protected Member Functions
void PerformCommand (Command command, Statement *statement, int source_position)
virtual bool Execute (Command command, Statement *statement, int source_position)=0
void PopContextToExpectedDepth ()
BytecodeGenerator * generator () const
ControlScope * outer () const
ContextScope * context () const
Static Protected Member Functions
static constexpr bool CommandUsesAccumulator (Command command)
Private Attributes
BytecodeGenerator * generator_
ControlScope * outer_
ContextScope * context_
Detailed Description
Definition at line 120 of file bytecode-generator.cc.
Member Enumeration Documentation
Command
enum v8::internal::interpreter::BytecodeGenerator::ControlScope::Command [protected]
Enumerator
CMD_BREAK
CMD_CONTINUE
CMD_RETURN
CMD_ASYNC_RETURN
CMD_RETHROW
Definition at line 148 of file bytecode-generator.cc.
               {
    CMD_BREAK,
    CMD_CONTINUE,
    CMD_RETURN,
    CMD_ASYNC_RETURN,
    CMD_RETHROW
  };
Constructor & Destructor Documentation
ControlScope() [1/2]
v8::internal::interpreter::BytecodeGenerator::ControlScope::ControlScope (BytecodeGenerator * generator) [inline], [explicit]
Definition at line 122 of file bytecode-generator.cc.
      : generator_(generator),
        outer_(generator->execution_control()),
        context_(generator->execution_context()) {
    generator_->set_execution_control(this);
  }
 ControlScope()
v8::internal::interpreter::BytecodeGenerator::ControlScope::~ControlScope () [inline]
Definition at line 128 of file bytecode-generator.cc.
{ generator_->set_execution_control(outer()); }
ControlScope() [2/2]
v8::internal::interpreter::BytecodeGenerator::ControlScope::ControlScope (const ControlScope &) [delete]
Member Function Documentation
AsyncReturnAccumulator()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::AsyncReturnAccumulator (int source_position) [inline]
Definition at line 141 of file bytecode-generator.cc.
                                                   {
    PerformCommand(CMD_ASYNC_RETURN, nullptr, source_position);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatements().
Break()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::Break (Statement * stmt) [inline]
Definition at line 132 of file bytecode-generator.cc.
                              {
    PerformCommand(CMD_BREAK, stmt, kNoSourcePosition);
  }
References v8::internal::kNoSourcePosition.
CommandUsesAccumulator()
static constexpr bool v8::internal::interpreter::BytecodeGenerator::ControlScope::CommandUsesAccumulator (Command command) [inline], [static], [constexpr], [protected]
Definition at line 155 of file bytecode-generator.cc.
                                                                {
    return command != CMD_BREAK && command != CMD_CONTINUE;
  }
context()
ContextScope* v8::internal::interpreter::BytecodeGenerator::ControlScope::context () const [inline], [protected]
Definition at line 171 of file bytecode-generator.cc.
{ return context_; }
Continue()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::Continue (Statement * stmt) [inline]
Definition at line 135 of file bytecode-generator.cc.
                                 {
    PerformCommand(CMD_CONTINUE, stmt, kNoSourcePosition);
  }
References v8::internal::kNoSourcePosition.
Execute()
virtual bool v8::internal::interpreter::BytecodeGenerator::ControlScope::Execute (Command command, Statement * statement, int source_position) [protected], [pure virtual]
Implemented in v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor, v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally, v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryCatch, v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration, v8::internal::interpreter::BytecodeGenerator::ControlScopeForBreakable, and v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel.
Referenced by PerformCommand().
generator()
BytecodeGenerator* v8::internal::interpreter::BytecodeGenerator::ControlScope::generator () const [inline], [protected]
Definition at line 169 of file bytecode-generator.cc.
{ return generator_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForTopLevel::Execute(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryCatch::Execute(), and v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute().
operator=()
ControlScope& v8::internal::interpreter::BytecodeGenerator::ControlScope::operator= (const ControlScope &) [delete]
outer()
ControlScope* v8::internal::interpreter::BytecodeGenerator::ControlScope::outer () const [inline], [protected]
Definition at line 170 of file bytecode-generator.cc.
{ return outer_; }
Referenced by PerformCommand().
PerformCommand()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::PerformCommand (Command command, Statement * statement, int source_position) [protected]
Definition at line 631 of file bytecode-generator.cc.
                                                                          {
  ControlScope* current = this;
  do {
    if (current->Execute(command, statement, source_position)) {
      return;
    }
    current = current->outer();
  } while (current != nullptr);
  UNREACHABLE();
}
References Execute(), outer(), and v8::internal::UNREACHABLE().
PopContextToExpectedDepth()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::PopContextToExpectedDepth () [protected]
Definition at line 644 of file bytecode-generator.cc.
                                                              {
  // Pop context to the expected depth. Note that this can in fact pop multiple
  // contexts at once because the {PopContext} bytecode takes a saved register.
  if (generator()->execution_context() != context()) {
    generator()->builder()->PopContext(context()->reg());
  }
}
References v8::internal::interpreter::BytecodeGenerator::execution_context().
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForBreakable::Execute(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::Execute(), v8::internal::interpreter::BytecodeGenerator::ControlScopeForTryFinally::Execute(), and v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute().
ReturnAccumulator()
void v8::internal::interpreter::BytecodeGenerator::ControlScope::ReturnAccumulator (int source_position) [inline]
Definition at line 138 of file bytecode-generator.cc.
                                              {
    PerformCommand(CMD_RETURN, nullptr, source_position);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateAsyncGeneratorFunctionBody(), and v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatements().
Member Data Documentation
context_
ContextScope* v8::internal::interpreter::BytecodeGenerator::ControlScope::context_ [private]
Definition at line 176 of file bytecode-generator.cc.
generator_
BytecodeGenerator* v8::internal::interpreter::BytecodeGenerator::ControlScope::generator_ [private]
Definition at line 174 of file bytecode-generator.cc.
outer_
ControlScope* v8::internal::interpreter::BytecodeGenerator::ControlScope::outer_ [private]
Definition at line 175 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc