v8::internal::compiler::SparseInputMask::InputIterator Class Reference
#include <common-operator.h>
Public Member Functions
InputIterator ()=default
InputIterator (BitMaskType bit_mask, Node *parent)
Node * parent () const
int real_index () const
void Advance ()
Node * GetReal () const
size_t AdvanceToNextRealOrEnd ()
Node * Get (Node *empty_value) const
bool IsReal () const
bool IsEmpty () const
bool IsEnd () const
Private Attributes
BitMaskType bit_mask_
Node * parent_
int real_index_
Detailed Description
Definition at line 293 of file common-operator.h.
Constructor & Destructor Documentation
InputIterator() [1/2]
v8::internal::compiler::SparseInputMask::InputIterator::InputIterator () [default]
InputIterator() [2/2]
v8::internal::compiler::SparseInputMask::InputIterator::InputIterator (SparseInputMask::BitMaskType bit_mask, Node * parent)
Definition at line 270 of file common-operator.cc.
    : bit_mask_(bit_mask), parent_(parent), real_index_(0) {
#if DEBUG
  if (bit_mask_ != SparseInputMask::kDenseBitMask) {
    DCHECK_EQ(base::bits::CountPopulation(bit_mask_) -
                  base::bits::CountPopulation(kEndMarker),
              parent->InputCount());
  }
#endif
}
References bit_mask_, v8::base::bits::CountPopulation(), DCHECK_EQ, v8::internal::compiler::Node::InputCount(), v8::internal::compiler::SparseInputMask::kDenseBitMask, v8::internal::compiler::SparseInputMask::kEndMarker, and parent().
Member Function Documentation
Advance()
void v8::internal::compiler::SparseInputMask::InputIterator::Advance ()
Definition at line 282 of file common-operator.cc.
                                           {
  DCHECK(!IsEnd());
  if (IsReal()) {
    ++real_index_;
  }
  bit_mask_ >>= 1;
}
References v8::internal::compiler::SparseInputMask::bit_mask_, and v8::internal::DCHECK().
AdvanceToNextRealOrEnd()
size_t v8::internal::compiler::SparseInputMask::InputIterator::AdvanceToNextRealOrEnd ()
Definition at line 291 of file common-operator.cc.
                                                            {
  DCHECK_NE(bit_mask_, SparseInputMask::kDenseBitMask);
  size_t count = base::bits::CountTrailingZeros(bit_mask_);
  bit_mask_ >>= count;
  DCHECK(IsReal() || IsEnd());
  return count;
}
References v8::internal::compiler::SparseInputMask::bit_mask_, v8::base::bits::CountTrailingZeros(), v8::internal::DCHECK(), DCHECK_NE, and v8::internal::compiler::SparseInputMask::kDenseBitMask.
Get()
Node* v8::internal::compiler::SparseInputMask::InputIterator::Get (Node * empty_value) const [inline]
Definition at line 317 of file common-operator.h.
                                       {
      return IsReal() ? GetReal() : empty_value;
    }
References GetReal(), and IsReal().
GetReal()
Node * v8::internal::compiler::SparseInputMask::InputIterator::GetReal () const
Definition at line 300 of file common-operator.cc.
                                                  {
  DCHECK(IsReal());
  return parent_->InputAt(real_index_);
}
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::StateValuesAccess::iterator::EnsureValid(), and Get().
IsEmpty()
bool v8::internal::compiler::SparseInputMask::InputIterator::IsEmpty () const [inline]
Definition at line 325 of file common-operator.h.
{ return !IsReal(); }
References IsReal().
Referenced by v8::internal::compiler::StateValuesAccess::iterator::EnsureValid().
IsEnd()
bool v8::internal::compiler::SparseInputMask::InputIterator::IsEnd () const
Definition at line 310 of file common-operator.cc.
                                               {
  return (bit_mask_ == kEndMarker) ||
         (bit_mask_ == SparseInputMask::kDenseBitMask &&
          real_index_ >= parent_->InputCount());
}
References v8::internal::compiler::SparseInputMask::bit_mask_, v8::internal::compiler::SparseInputMask::kDenseBitMask, and v8::internal::compiler::SparseInputMask::kEndMarker.
Referenced by v8::internal::compiler::StateValuesAccess::iterator::EnsureValid().
IsReal()
bool v8::internal::compiler::SparseInputMask::InputIterator::IsReal () const
Definition at line 305 of file common-operator.cc.
                                                {
  return bit_mask_ == SparseInputMask::kDenseBitMask ||
         (bit_mask_ & kEntryMask);
}
References v8::internal::compiler::SparseInputMask::bit_mask_, v8::internal::compiler::SparseInputMask::kDenseBitMask, and v8::internal::compiler::SparseInputMask::kEntryMask.
Referenced by Get(), and IsEmpty().
parent()
Node* v8::internal::compiler::SparseInputMask::InputIterator::parent () const [inline]
Definition at line 298 of file common-operator.h.
{ return parent_; }
References parent_.
Referenced by InputIterator().
real_index()
int v8::internal::compiler::SparseInputMask::InputIterator::real_index () const [inline]
Definition at line 299 of file common-operator.h.
{ return real_index_; }
References real_index_.
Member Data Documentation
bit_mask_
BitMaskType v8::internal::compiler::SparseInputMask::InputIterator::bit_mask_ [private]
Definition at line 331 of file common-operator.h.
Referenced by InputIterator().
parent_
Node* v8::internal::compiler::SparseInputMask::InputIterator::parent_ [private]
Definition at line 332 of file common-operator.h.
Referenced by parent().
real_index_
int v8::internal::compiler::SparseInputMask::InputIterator::real_index_ [private]
Definition at line 333 of file common-operator.h.
Referenced by real_index().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/common-operator.h
/mnt/V8SourceCode/src/compiler/common-operator.cc