v8::internal::torque::GenericCallable Class Reference
#include <declarable.h>
Public Member Functions
std::optional< Statement * > CallableBody ()
TypeArgumentInference InferSpecializationTypes (const TypeVector &explicit_specialization_types, const std::vector< std::optional< const Type * >> &arguments)
Private Member Functions
GenericCallable (const std::string &name, GenericCallableDeclaration *generic_declaration)
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 637 of file declarable.h.
Constructor & Destructor Documentation
GenericCallable()
v8::internal::torque::GenericCallable::GenericCallable (const std::string & name, GenericCallableDeclaration * generic_declaration) [inline], [private]
Definition at line 650 of file declarable.h.
      : GenericDeclarable<Callable*, GenericCallableDeclaration*>(
            Declarable::kGenericCallable, name, generic_declaration) {}
Member Function Documentation
CallableBody()
std::optional< Statement * > v8::internal::torque::GenericCallable::CallableBody ()
Definition at line 163 of file declarable.cc.
                                                      {
  if (auto* macro_decl = TorqueMacroDeclaration::DynamicCast(declaration())) {
    return macro_decl->body;
  } else if (auto* builtin_decl =
                 TorqueBuiltinDeclaration::DynamicCast(declaration())) {
    return builtin_decl->body;
  } else {
    return std::nullopt;
  }
}
References v8::internal::torque::GenericDeclarable< Callable *, GenericCallableDeclaration * >::declaration().
InferSpecializationTypes()
TypeArgumentInference v8::internal::torque::GenericCallable::InferSpecializationTypes (const TypeVector & explicit_specialization_types, const std::vector< std::optional< const Type * >> & arguments)
Definition at line 145 of file declarable.cc.
                                                          {
  const std::vector<TypeExpression*>& parameters =
      declaration()->parameters.types;
  CurrentScope::Scope generic_scope(ParentScope());
  TypeArgumentInference inference(generic_parameters(),
                                  explicit_specialization_types, parameters,
                                  arguments);
  if (!inference.HasFailed()) {
    if (auto violation =
            FindConstraintViolation(inference.GetResult(), Constraints())) {
      inference.Fail(*violation);
    }
  }
  return inference;
}
References v8::internal::torque::GenericDeclarable< Callable *, GenericCallableDeclaration * >::Constraints(), v8::internal::torque::GenericDeclarable< Callable *, GenericCallableDeclaration * >::declaration(), v8::internal::torque::TypeArgumentInference::Fail(), v8::internal::torque::FindConstraintViolation(), v8::internal::torque::GenericDeclarable< Callable *, GenericCallableDeclaration * >::generic_parameters(), v8::internal::torque::TypeArgumentInference::GetResult(), v8::internal::torque::TypeArgumentInference::HasFailed(), and v8::internal::torque::Declarable::ParentScope().
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 649 of file declarable.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/declarable.h
/mnt/V8SourceCode/src/torque/declarable.cc