v8::internal::Comparator::Input Class Reference
#include <liveedit-diff.h>
Public Member Functions
virtual int GetLength1 ()=0
virtual int GetLength2 ()=0
virtual bool Equals (int index1, int index2)=0
Protected Member Functions
virtual ~Input ()=default
Detailed Description
Definition at line 16 of file liveedit-diff.h.
Constructor & Destructor Documentation
 Input()
virtual v8::internal::Comparator::Input::~Input () [protected], [virtual], [default]
Member Function Documentation
Equals()
virtual bool v8::internal::Comparator::Input::Equals (int index1, int index2) [pure virtual]
Implemented in v8::internal::anonymous_namespace{liveedit.cc}::LineArrayCompareInput, and v8::internal::anonymous_namespace{liveedit.cc}::TokensCompareInput.
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::NarrowDownInput(), v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::ShortestEditReverse(), and v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::WalkDiagonal().
GetLength1()
virtual int v8::internal::Comparator::Input::GetLength1 () [pure virtual]
Implemented in v8::internal::anonymous_namespace{liveedit.cc}::LineArrayCompareInput, and v8::internal::anonymous_namespace{liveedit.cc}::TokensCompareInput.
Referenced by v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::FindEditPath(), and v8::internal::anonymous_namespace{liveedit.cc}::NarrowDownInput().
GetLength2()
virtual int v8::internal::Comparator::Input::GetLength2 () [pure virtual]
Implemented in v8::internal::anonymous_namespace{liveedit.cc}::LineArrayCompareInput, and v8::internal::anonymous_namespace{liveedit.cc}::TokensCompareInput.
Referenced by v8::internal::anonymous_namespace{liveedit-diff.cc}::MyersDiffer::FindEditPath(), and v8::internal::anonymous_namespace{liveedit.cc}::NarrowDownInput().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/liveedit-diff.h