v8::bigint::ShiftedDigits Class Reference
#include <div-helpers.h>
Public Member Functions
ShiftedDigits (Digits &original, int shift=-1, bool allow_inplace=false)
~ShiftedDigits ()=default
void Reset ()
int shift ()
Private Attributes
int shift_
bool inplace_
std::unique_ptr< digit_t[]> storage_
Additional Inherited Members
Detailed Description
Definition at line 36 of file div-helpers.h.
Constructor & Destructor Documentation
ShiftedDigits()
v8::bigint::ShiftedDigits::ShiftedDigits (Digits & original, int shift = -1, bool allow_inplace = false) [inline], [explicit]
Definition at line 38 of file div-helpers.h.
      : Digits(original.digits_, original.len_) {
    int leading_zeros = CountLeadingZeros(original.msd());
    if (shift < 0) {
      shift = leading_zeros;
    } else if (shift > leading_zeros) {
      allow_inplace = false;
      len_++;
    }
    shift_ = shift;
    if (shift == 0) {
      inplace_ = true;
      return;
    }
    inplace_ = allow_inplace;
    if (!inplace_) {
      digit_t* digits = new digit_t[len_];
      storage_.reset(digits);
      digits_ = digits;
    }
    RWDigits rw_view(digits_, len_);
    LeftShift(rw_view, original, shift_);
  }
References v8::bigint::CountLeadingZeros(), v8::bigint::Digits::digits(), v8::bigint::Digits::digits_, inplace_, v8::base::leading_zeros, v8::bigint::LeftShift(), v8::bigint::Digits::len_, v8::bigint::Digits::msd(), shift(), shift_, and storage_.
 ShiftedDigits()
v8::bigint::ShiftedDigits::~ShiftedDigits () [default]
Member Function Documentation
Reset()
void v8::bigint::ShiftedDigits::Reset () [inline]
Definition at line 64 of file div-helpers.h.
               {
    if (inplace_) {
      RWDigits rw_view(digits_, len_);
      RightShift(rw_view, rw_view, shift_);
    }
  }
References v8::bigint::Digits::digits_, inplace_, v8::bigint::Digits::len_, v8::bigint::RightShift(), and shift_.
shift()
int v8::bigint::ShiftedDigits::shift () [inline]
Definition at line 71 of file div-helpers.h.
{ return shift_; }
References shift_.
Referenced by v8::bigint::ProcessorImpl::DivideSchoolbook(), and ShiftedDigits().
Member Data Documentation
inplace_
bool v8::bigint::ShiftedDigits::inplace_ [private]
Definition at line 75 of file div-helpers.h.
Referenced by Reset(), and ShiftedDigits().
shift_
int v8::bigint::ShiftedDigits::shift_ [private]
Definition at line 74 of file div-helpers.h.
Referenced by Reset(), shift(), and ShiftedDigits().
storage_
std::unique_ptr<digit_t[]> v8::bigint::ShiftedDigits::storage_ [private]
Definition at line 76 of file div-helpers.h.
Referenced by ShiftedDigits().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/bigint/div-helpers.h