v8::internal::compiler::turboshaft::V< T > Class Template Reference
#include <index.h>
Public Types
using type = T
Public Member Functions
constexpr V ()
template<typename U >
requires implicitly_constructible_from< U > V (V< U > index)
template<typename U >
requires (std::is_same_v< U, OpIndex >) V(U index)
Static Public Member Functions
static V Invalid ()
template<typename U >
static V< T > Cast (V< U > index)
static V< T > Cast (OpIndex index)
static constexpr bool allows_representation (RegisterRepresentation maybe_allowed_rep)
Static Public Attributes
static constexpr auto rep = v_traits<type>::rep
Static Private Attributes
template<typename U >
constexpr static bool implicitly_constructible_from
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::compiler::turboshaft::V< T >
Definition at line 613 of file index.h.
Member Typedef Documentation
type
template<typename T >
using v8::internal::compiler::turboshaft::V< T >::type = T
Definition at line 623 of file index.h.
Constructor & Destructor Documentation
V() [1/2]
template<typename T >
constexpr v8::internal::compiler::turboshaft::V< T >::V () [inline], [constexpr]
Definition at line 625 of file index.h.
: OpIndex() {}
V() [2/2]
template<typename T >
template<typename U >
requires implicitly_constructible_from<U> v8::internal::compiler::turboshaft::V< T >::V (V< U > index) [inline]
Definition at line 633 of file index.h.
: OpIndex(index) {} // NOLINT(runtime/explicit)
Member Function Documentation
allows_representation()
template<typename T >
static constexpr bool v8::internal::compiler::turboshaft::V< T >::allows_representation (RegisterRepresentation maybe_allowed_rep) [inline], [static], [constexpr]
Definition at line 643 of file index.h.
                                                {
    return v_traits<T>::allows_representation(maybe_allowed_rep);
  }
Cast() [1/2]
template<typename T >
static V<T> v8::internal::compiler::turboshaft::V< T >::Cast (OpIndex index) [inline], [static]
Definition at line 641 of file index.h.
{ return V<T>(index); }
References v8::internal::index.
Cast() [2/2]
template<typename T >
template<typename U >
static V<T> v8::internal::compiler::turboshaft::V< T >::Cast (V< U > index) [inline], [static]
Definition at line 638 of file index.h.
                               {
    return V<T>(OpIndex{index});
  }
References v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::AdaptFastCallArgument(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArraySet(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::AtIndex(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::BigIntBinop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckArrayWithLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckMem(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildChangeInt32ToSmi(), v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildFunctionReferenceTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildFunctionTargetAndImplicitArg(), v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildLoadCallTargetFromExportedFunctionData(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeArrayTaggedPointer(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Change(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat16RawBitsToFloat64(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToAdditiveSafeIntegerOrDeopt(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToInt32OrDeopt(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToInt64OrDeopt(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeFloat64ToUint32OrDeopt(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeInt32ToIntPtr(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeIntPtrToInt64(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ChangeOrDeopt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ChangeUint31ToSmi(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeUint32ToUintPtr(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ChangeUintPtrToUint64(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CheckedSmiUntag(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertFloat64ToNumber(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertNumberToString(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertStringToNumber(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ConvertToBoolean(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitive(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertUntaggedToJSPrimitiveOrDeopt(), v8::internal::detail::BuiltinArgumentsTS< Assembler >::Iterator::Dereference(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ExternRefToString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::FloatUnary(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetContext(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::IsRootConstant(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVector(), v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorSlot(), v8::internal::wasm::TurboshaftGraphBuildingInterface::LoadTable(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Map(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Map(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::MapToNewGraph(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemOrTableAddressToUintPtrOrOOBTrap(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NewDoubleArray(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::NoContextConstant(), v8::internal::wasm::TurboshaftGraphBuildingInterface::NullCheck(), v8::internal::compiler::turboshaft::ShadowyOpIndex::operator V<T >(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::PendingLoopPhi(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Projection(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Shift(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128ExtractLane(), v8::internal::wasm::TurboshaftGraphBuildingInterface::SimdLaneOp(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::SmiConstant(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringAsIter(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringAsWtf8(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCompare(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringConcat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEncodeWtf16(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEncodeWtf16Array(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEncodeWtf8(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringHash(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringIsUSVSequence(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf16Array(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewIterAdvance(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewIterNext(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewIterRewind(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewIterSlice(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf16Encode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf16Slice(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf8Advance(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf8Encode(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf8Slice(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGrow(), v8::internal::BuiltinsReducer< Next >::TaggedToWord32OrBigIntImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Throw(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ThrowDataViewTypeError(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateFloat64ToFloat16RawBits(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateNumberToInt32(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::TruncateWordPtrToWord32(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Tuple(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnpackWasmException(), v8::internal::FeedbackCollectorReducer< Next >::UpdateFeedback(), v8::internal::compiler::turboshaft::OptionalV< T >::value(), v8::internal::compiler::turboshaft::OptionalV< T >::value_or_invalid(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::WordBinopDeoptOnOverflow(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::WordPtrConstant(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
Invalid()
template<typename T >
static V v8::internal::compiler::turboshaft::V< T >::Invalid () [inline], [static]
Definition at line 635 of file index.h.
{ return V<T>(OpIndex::Invalid()); }
References v8::internal::compiler::turboshaft::OpIndex::Invalid().
Referenced by v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateBigInt(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::AssembleOutputGraphCheckException(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::DuplicationOptimizationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::Branch(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::turboshaft::BranchEliminationReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::DeoptimizeIf(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::expected_high(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::expected_low(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::index(), v8::internal::compiler::turboshaft::StackCheckLoweringReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::LoopPeelingReducer< Next >::JSStackCheck(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessBasicBlock(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::RuntimeAbort(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::StaticAssert(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MemoryOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StoreMessage(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringConcat(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsKind(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionElementsKindOrCheckMap(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::TrapIf(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_high(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::value_low(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
requires()
template<typename T >
template<typename U >
v8::internal::compiler::turboshaft::V< T >::requires (std::is_same_v< U, OpIndex >) [inline]
Definition at line 654 of file index.h.
             : OpIndex(index) {} // NOLINT(runtime/explicit)
Member Data Documentation
implicitly_constructible_from
template<typename T >
template<typename U >
constexpr static bool v8::internal::compiler::turboshaft::V< T >::implicitly_constructible_from [static], [constexpr], [private]
Initial value:
=
      v_traits<T>::template implicitly_constructible_from<U>::value
Definition at line 619 of file index.h.
rep
template<typename T >
constexpr auto v8::internal::compiler::turboshaft::V< T >::rep = v_traits<type>::rep [static], [constexpr]
Definition at line 624 of file index.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/index.h