v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer Class Reference
#include <pretenuring-propagation-reducer.h>
Public Member Functions
PretenuringPropagationAnalyzer (Zone *phase_zone, Graph &mutable_input_graph)
void Run ()
Private Member Functions
void ProcessStore (const StoreOp &store)
void ProcessPhi (const PhiOp &phi)
void ProcessAllocate (const AllocateOp &allocate)
bool PushContainedValues (OpIndex base)
void OldifySubgraph (OpIndex old_alloc)
void BuildStoreInputGraph ()
void PropagateAllocationTypes ()
ZoneVector< OpIndex > * FindOrCreate (OpIndex idx)
ZoneVector< OpIndex > * Create (OpIndex idx)
ZoneVector< OpIndex > * TryFind (OpIndex idx)
Private Attributes
Zone * zone_
Graph & input_graph_
ZoneVector< OpIndex > old_allocs_
ZoneAbslFlatHashMap< OpIndex, ZoneVector< OpIndex > * > store_graph_
ZoneAbslFlatHashSet< OpIndex > old_phis_
ZoneVector< OpIndex > queue_
Detailed Description
Definition at line 151 of file pretenuring-propagation-reducer.h.
Constructor & Destructor Documentation
PretenuringPropagationAnalyzer()
v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::PretenuringPropagationAnalyzer (Zone * phase_zone, Graph & mutable_input_graph) [inline]
Definition at line 153 of file pretenuring-propagation-reducer.h.
      : zone_(phase_zone),
        input_graph_(mutable_input_graph),
        old_allocs_(phase_zone),
        store_graph_(phase_zone),
        old_phis_(phase_zone),
        queue_(phase_zone) {}
Member Function Documentation
BuildStoreInputGraph()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::BuildStoreInputGraph () [private]
Definition at line 123 of file pretenuring-propagation-reducer.cc.
                                                          {
  for (auto& op : input_graph_.AllOperations()) {
    if (ShouldSkipOperation(op)) {
      continue;
    }
    switch (op.opcode) {
      case Opcode::kStore:
        ProcessStore(op.Cast<StoreOp>());
        break;
      case Opcode::kAllocate:
        ProcessAllocate(op.Cast<AllocateOp>());
        break;
      case Opcode::kPhi:
        ProcessPhi(op.Cast<PhiOp>());
        break;
      default:
        break;
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::AllOperations(), input_graph_, ProcessAllocate(), ProcessPhi(), ProcessStore(), and v8::internal::compiler::turboshaft::ShouldSkipOperation().
Referenced by Run().
Create()
ZoneVector<OpIndex>* v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::Create (OpIndex idx) [inline], [private]
Definition at line 180 of file pretenuring-propagation-reducer.h.
                                           {
    DCHECK_EQ(store_graph_.count(idx), 0);
    ZoneVector<OpIndex>* stored_items = zone_->New<ZoneVector<OpIndex>>(zone_);
    store_graph_.insert({idx, stored_items});
    return stored_items;
  }
References DCHECK_EQ, v8::internal::Zone::New(), store_graph_, and zone_.
Referenced by FindOrCreate(), and ProcessPhi().
FindOrCreate()
ZoneVector<OpIndex>* v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::FindOrCreate (OpIndex idx) [inline], [private]
Definition at line 174 of file pretenuring-propagation-reducer.h.
                                                 {
    auto it = store_graph_.find(idx);
    if (it != store_graph_.end()) return it->second;
    return Create(idx);
  }
References Create(), and store_graph_.
Referenced by ProcessStore().
OldifySubgraph()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::OldifySubgraph (OpIndex old_alloc) [private]
Definition at line 96 of file pretenuring-propagation-reducer.cc.
                                                                     {
  queue_.clear();
  if (!PushContainedValues(old_alloc)) return;
  while (!queue_.empty()) {
    OpIndex idx = queue_.back();
    queue_.pop_back();
    Operation& op = input_graph_.Get(idx);
    if (AllocateOp* alloc = op.TryCast<AllocateOp>()) {
      if (alloc->type == AllocationType::kOld) continue;
      alloc->type = AllocationType::kOld;
      PushContainedValues(idx);
    } else {
      DCHECK(op.Is<PhiOp>());
      if (old_phis_.find(idx) != old_phis_.end()) continue;
      old_phis_.insert(idx);
      PushContainedValues(idx);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), input_graph_, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::kOld, old_phis_, PushContainedValues(), queue_, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by PropagateAllocationTypes().
ProcessAllocate()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessAllocate (const AllocateOp & allocate) [private]
Definition at line 72 of file pretenuring-propagation-reducer.cc.
                                {
  if (allocate.type == AllocationType::kOld) {
    // We could be a bit more lazy in storing old AllocateOp into {old_allocs_}
    // (by waiting for a Store or a Phi to use the AllocateOp), but there is
    // usually very few old allocation, so it makes sense to do it eagerly.
    old_allocs_.push_back(input_graph_.Index(allocate));
  }
}
References v8::internal::compiler::turboshaft::Graph::Index(), input_graph_, v8::internal::kOld, old_allocs_, and v8::internal::compiler::turboshaft::AllocateOp::type.
Referenced by BuildStoreInputGraph().
ProcessPhi()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi (const PhiOp & phi) [private]
Definition at line 44 of file pretenuring-propagation-reducer.cc.
                                                                {
  // Phis act as storing all of their inputs. It's not how they work in
  // practice, but if a Phi has a Young input, and is stored in an Old object,
  // it makes sense to Oldify the phi input.
  // For better performance, we only record inputs that could be an allocation:
  // Phis with an entry in {store_graph_} or AllocateOp.
  // Note that this is slightly imprecise for loop Phis (since if the backedge
  // is a Phi itself, it won't have an entry in {store_graph_} yet), but it
  // should still be good enough for most cases.
  base::SmallVector<OpIndex, 16> interesting_inputs;
  for (OpIndex input : phi.inputs()) {
    const Operation& op = input_graph_.Get(input);
    if (op.Is<AllocateOp>()) {
      interesting_inputs.push_back(input);
    } else if (op.Is<PhiOp>() && TryFind(input) != nullptr) {
      interesting_inputs.push_back(input);
    }
  }
  if (interesting_inputs.empty()) return;
  ZoneVector<OpIndex>* stored_in_phi = Create(input_graph_.Index(phi));
  for (OpIndex input : interesting_inputs) {
    stored_in_phi->push_back(input);
  }
}
References Create(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::Graph::Index(), input_graph_, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::ZoneVector< T >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), and TryFind().
Referenced by BuildStoreInputGraph().
ProcessStore()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessStore (const StoreOp & store) [private]
Definition at line 17 of file pretenuring-propagation-reducer.cc.
                                                                      {
  OpIndex base_idx = store.base();
  OpIndex value_idx = store.value();
  const Operation& base = input_graph_.Get(base_idx);
  const Operation& value = input_graph_.Get(value_idx);
  if (!CouldBeAllocate(base) || !CouldBeAllocate(value)) {
    return;
  }
  if (value.Is<AllocateOp>() &&
      value.Cast<AllocateOp>().type == AllocationType::kOld) {
    // {value} is already Old, and we don't care about new-to-old and old-to-old
    // stores.
    return;
  }
  if (value.Is<PhiOp>() && TryFind(value_idx) == nullptr) {
    // {value} is not worth being recorded, as it's not an Allocation (or a Phi
    // of Allocations) that could be promoted to Old.
    return;
  }
  ZoneVector<OpIndex>* stored_in_base = FindOrCreate(base_idx);
  stored_in_base->push_back(value_idx);
}
References v8::internal::compiler::turboshaft::anonymous_namespace{pretenuring-propagation-reducer.cc}::CouldBeAllocate(), FindOrCreate(), v8::internal::compiler::turboshaft::Graph::Get(), input_graph_, v8::internal::kOld, v8::internal::ZoneVector< T >::push_back(), store(), TryFind(), v8::internal::compiler::turboshaft::AllocateOp::type, and v8::internal::value.
Referenced by BuildStoreInputGraph().
PropagateAllocationTypes()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::PropagateAllocationTypes () [private]
Definition at line 117 of file pretenuring-propagation-reducer.cc.
                                                              {
  for (OpIndex old_alloc : old_allocs_) {
    OldifySubgraph(old_alloc);
  }
}
References old_allocs_, and OldifySubgraph().
Referenced by Run().
PushContainedValues()
bool v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::PushContainedValues (OpIndex base) [private]
Definition at line 82 of file pretenuring-propagation-reducer.cc.
                                                                     {
  // Push into {queue_} all of the values that are "contained" into {base}:
  // values that are stored to {base} if {base} is an AllocateOp, or Phi inputs
  // if {base} is a Phi.
  ZoneVector<OpIndex>* contained = TryFind(base);
  if (contained == nullptr) return false;
  for (OpIndex index : *contained) {
    queue_.push_back(index);
  }
  return true;
}
References v8::internal::index, queue_, and TryFind().
Referenced by OldifySubgraph().
Run()
void v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::Run ()
Definition at line 144 of file pretenuring-propagation-reducer.cc.
                                         {
  BuildStoreInputGraph();
  PropagateAllocationTypes();
}
References BuildStoreInputGraph(), and PropagateAllocationTypes().
Referenced by v8::internal::compiler::turboshaft::PretenuringPropagationReducer< Next >::Analyze().
TryFind()
ZoneVector<OpIndex>* v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::TryFind (OpIndex idx) [inline], [private]
Definition at line 187 of file pretenuring-propagation-reducer.h.
                                            {
    auto it = store_graph_.find(idx);
    if (it != store_graph_.end()) return it->second;
    return nullptr;
  }
References store_graph_.
Referenced by ProcessPhi(), ProcessStore(), and PushContainedValues().
Member Data Documentation
input_graph_
Graph& v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::input_graph_ [private]
Definition at line 194 of file pretenuring-propagation-reducer.h.
Referenced by BuildStoreInputGraph(), OldifySubgraph(), ProcessAllocate(), ProcessPhi(), and ProcessStore().
old_allocs_
ZoneVector<OpIndex> v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::old_allocs_ [private]
Definition at line 195 of file pretenuring-propagation-reducer.h.
Referenced by ProcessAllocate(), and PropagateAllocationTypes().
old_phis_
ZoneAbslFlatHashSet<OpIndex> v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::old_phis_ [private]
Definition at line 208 of file pretenuring-propagation-reducer.h.
Referenced by OldifySubgraph().
queue_
ZoneVector<OpIndex> v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::queue_ [private]
Definition at line 213 of file pretenuring-propagation-reducer.h.
Referenced by OldifySubgraph(), and PushContainedValues().
store_graph_
ZoneAbslFlatHashMap<OpIndex, ZoneVector<OpIndex>*> v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::store_graph_ [private]
Definition at line 202 of file pretenuring-propagation-reducer.h.
Referenced by Create(), FindOrCreate(), and TryFind().
zone_
Zone* v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::zone_ [private]
Definition at line 193 of file pretenuring-propagation-reducer.h.
Referenced by Create().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/pretenuring-propagation-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/pretenuring-propagation-reducer.cc