v8::internal::ExternalReferenceEncoder Class Reference
#include <external-reference-encoder.h>
Classes
class Value
Public Member Functions
ExternalReferenceEncoder (Isolate *isolate)
ExternalReferenceEncoder (const ExternalReferenceEncoder &)=delete
ExternalReferenceEncoder & operator= (const ExternalReferenceEncoder &)=delete
Value Encode (Address key) const
Maybe< Value > TryEncode (Address key) const
const char * NameOfAddress (Isolate *isolate, Address address) const
Private Attributes
AddressToIndexHashMap * map_
Detailed Description
Definition at line 19 of file external-reference-encoder.h.
Constructor & Destructor Documentation
ExternalReferenceEncoder() [1/2]
v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder (Isolate * isolate) [explicit]
Definition at line 13 of file external-reference-encoder.cc.
                                                                   {
#ifdef DEBUG
  api_references_ = isolate->api_external_references();
  if (api_references_ != nullptr) {
    for (uint32_t i = 0; api_references_[i] != 0; ++i) count_.push_back(0);
  }
#endif // DEBUG
  map_ = isolate->external_reference_map();
  if (map_ != nullptr) return;
  map_ = new AddressToIndexHashMap();
  isolate->set_external_reference_map(map_);
  // Add V8's external references.
  ExternalReferenceTable* table = isolate->external_reference_table();
  for (uint32_t i = 0; i < ExternalReferenceTable::kSize; ++i) {
    Address addr = table->address(i);
    // Ignore duplicate references.
    // This can happen due to ICF. See http://crbug.com/726896.
    if (map_->Get(addr).IsNothing()) map_->Set(addr, Value::Encode(i, false));
    DCHECK(map_->Get(addr).IsJust());
  }
  // Add external references provided by the embedder.
  const intptr_t* api_references = isolate->api_external_references();
  if (api_references == nullptr) return;
  for (uint32_t i = 0; api_references[i] != 0; ++i) {
    Address addr = static_cast<Address>(api_references[i]);
    // Ignore duplicate references.
    // This can happen due to ICF. See http://crbug.com/726896.
    if (map_->Get(addr).IsNothing()) map_->Set(addr, Value::Encode(i, true));
    DCHECK(map_->Get(addr).IsJust());
  }
}
References v8::internal::ExternalReferenceTable::address(), v8::internal::DCHECK(), v8::internal::ExternalReferenceEncoder::Value::Encode(), v8::internal::Isolate::external_reference_table(), v8::internal::PointerToIndexHashMap< Type >::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ExternalReferenceTable::kSize, map_, and v8::internal::PointerToIndexHashMap< Type >::Set().
ExternalReferenceEncoder() [2/2]
v8::internal::ExternalReferenceEncoder::ExternalReferenceEncoder (const ExternalReferenceEncoder &) [delete]
Member Function Documentation
Encode()
ExternalReferenceEncoder::Value v8::internal::ExternalReferenceEncoder::Encode (Address key) const
Definition at line 70 of file external-reference-encoder.cc.
                           {
  Maybe<uint32_t> maybe_index = map_->Get(address);
  if (maybe_index.IsNothing()) {
    void* addr = reinterpret_cast<void*>(address);
    v8::base::OS::PrintError("Unknown external reference %p.\n", addr);
    v8::base::OS::PrintError("%s\n",
                             ExternalReferenceTable::ResolveSymbol(addr));
    v8::base::OS::Abort();
  }
  Value result(maybe_index.FromJust());
#ifdef DEBUG
  if (result.is_from_api()) count_[result.index()]++;
#endif // DEBUG
  return result;
}
References v8::base::OS::Abort(), v8::Maybe< T >::FromJust(), v8::internal::PointerToIndexHashMap< Type >::Get(), v8::Maybe< T >::IsNothing(), map_, v8::internal::ExternalReferenceTable::ResolveSymbol(), and v8::base::internal::result.
Referenced by v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReferenceTableEntry().
NameOfAddress()
const char * v8::internal::ExternalReferenceEncoder::NameOfAddress (Isolate * isolate, Address address) const
Definition at line 87 of file external-reference-encoder.cc.
                                                                           {
  Maybe<uint32_t> maybe_index = map_->Get(address);
  if (maybe_index.IsNothing()) return "<unknown>";
  Value value(maybe_index.FromJust());
  if (value.is_from_api()) return "<from api>";
  return isolate->external_reference_table()->name(value.index());
}
References v8::internal::Isolate::external_reference_table(), v8::Maybe< T >::FromJust(), v8::internal::PointerToIndexHashMap< Type >::Get(), v8::Maybe< T >::IsNothing(), map_, v8::internal::ExternalReferenceTable::name(), and v8::internal::value.
operator=()
ExternalReferenceEncoder& v8::internal::ExternalReferenceEncoder::operator= (const ExternalReferenceEncoder &) [delete]
TryEncode()
Maybe< ExternalReferenceEncoder::Value > v8::internal::ExternalReferenceEncoder::TryEncode (Address key) const
Definition at line 59 of file external-reference-encoder.cc.
                           {
  Maybe<uint32_t> maybe_index = map_->Get(address);
  if (maybe_index.IsNothing()) return Nothing<Value>();
  Value result(maybe_index.FromJust());
#ifdef DEBUG
  if (result.is_from_api()) count_[result.index()]++;
#endif // DEBUG
  return Just<Value>(result);
}
References v8::Maybe< T >::FromJust(), v8::internal::PointerToIndexHashMap< Type >::Get(), v8::Maybe< T >::IsNothing(), map_, and v8::base::internal::result.
Referenced by v8::internal::Serializer::EncodeExternalReference(), and v8::internal::Serializer::TryEncodeExternalReference().
Member Data Documentation
map_
AddressToIndexHashMap* v8::internal::ExternalReferenceEncoder::map_ [private]
Definition at line 51 of file external-reference-encoder.h.
Referenced by Encode(), ExternalReferenceEncoder(), NameOfAddress(), and TryEncode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/external-reference-encoder.h
/mnt/V8SourceCode/src/codegen/external-reference-encoder.cc