v8::Shell Class Reference
#include <d8.h>
Public Types
enum PrintResult : bool { kPrintResult = true
, kNoPrintResult = false
 }
enum ReportExceptions : bool { kReportExceptions = true
, kNoReportExceptions = false
 }
enum ProcessMessageQueue : bool { kProcessMessageQueue = true
, kNoProcessMessageQueue = false
 }
enum class CodeType {
kFileName
, kString
, kFunction
, kInvalid
,
kNone
 }
Static Public Member Functions
static bool ExecuteString (Isolate *isolate, Local< String > source, Local< String > name, ReportExceptions report_exceptions, Global< Value > *out_result=nullptr)
static bool ExecuteModule (Isolate *isolate, const char *file_name)
static bool LoadJSON (Isolate *isolate, const char *file_name)
static void ReportException (Isolate *isolate, Local< Message > message, Local< Value > exception)
static void ReportException (Isolate *isolate, const TryCatch &try_catch)
static MaybeLocal< String > ReadFile (Isolate *isolate, const char *name, bool should_throw=true)
static std::unique_ptr< base::OS::MemoryMappedFile > ReadFileData (Isolate *isolate, const char *name, bool should_throw=true)
static Local< String > WasmLoadSourceMapCallback (Isolate *isolate, const char *name)
static MaybeLocal< Context > CreateEvaluationContext (Isolate *isolate)
static int RunMain (Isolate *isolate, bool last_run)
static int Main (int argc, char *argv[])
static void Exit (int exit_code)
static void OnExit (Isolate *isolate, bool dispose)
static void DumpCounters ()
static void CollectGarbage (Isolate *isolate)
static bool EmptyMessageQueues (Isolate *isolate)
static bool CompleteMessageLoop (Isolate *isolate)
static bool FinishExecuting (Isolate *isolate, const Global< Context > &context)
static bool HandleUnhandledPromiseRejections (Isolate *isolate)
static std::unique_ptr< SerializationData > SerializeValue (Isolate *isolate, Local< Value > value, Local< Value > transfer)
static MaybeLocal< Value > DeserializeValue (Isolate *isolate, std::unique_ptr< SerializationData > data)
static int * LookupCounter (const char *name)
static void * CreateHistogram (const char *name, int min, int max, size_t buckets)
static void AddHistogramSample (void *histogram, int sample)
static void MapCounters (v8::Isolate *isolate, const char *name)
static double GetTimestamp ()
static uint64_t GetTracingTimestampFromPerformanceTimestamp (double performance_timestamp)
static void PerformanceNow (const v8::FunctionCallbackInfo< v8::Value > &info)
static void PerformanceMark (const v8::FunctionCallbackInfo< v8::Value > &info)
static void PerformanceMeasure (const v8::FunctionCallbackInfo< v8::Value > &info)
static void PerformanceMeasureMemory (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmCurrent (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmOwner (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmGlobal (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmCreate (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmNavigate (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmCreateAllowCrossRealmAccess (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmDetachGlobal (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmDispose (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmSwitch (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmEval (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RealmSharedGet (Local< Name > property, const PropertyCallbackInfo< Value > &info)
static void RealmSharedSet (Local< Name > property, Local< Value > value, const PropertyCallbackInfo< void > &info)
static void LogGetAndStop (const v8::FunctionCallbackInfo< v8::Value > &info)
static void TestVerifySourcePositions (const v8::FunctionCallbackInfo< v8::Value > &info)
static void InstallConditionalFeatures (const v8::FunctionCallbackInfo< v8::Value > &info)
static void EnableJSPI (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SetFlushDenormals (const v8::FunctionCallbackInfo< v8::Value > &info)
static void AsyncHooksCreateHook (const v8::FunctionCallbackInfo< v8::Value > &info)
static void AsyncHooksExecutionAsyncId (const v8::FunctionCallbackInfo< v8::Value > &info)
static void AsyncHooksTriggerAsyncId (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SetPromiseHooks (const v8::FunctionCallbackInfo< v8::Value > &info)
static void EnableDebugger (const v8::FunctionCallbackInfo< v8::Value > &info)
static void DisableDebugger (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SerializerSerialize (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SerializerDeserialize (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ProfilerSetOnProfileEndListener (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ProfilerTriggerSample (const v8::FunctionCallbackInfo< v8::Value > &info)
static bool HasOnProfileEndListener (Isolate *isolate)
static void TriggerOnProfileEndListener (Isolate *isolate, std::string profile)
static void ResetOnProfileEndListener (Isolate *isolate)
static void Print (const v8::FunctionCallbackInfo< v8::Value > &info)
static void PrintErr (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WriteStdout (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WaitUntilDone (const v8::FunctionCallbackInfo< v8::Value > &info)
static void NotifyDone (const v8::FunctionCallbackInfo< v8::Value > &info)
static void QuitOnce (v8::FunctionCallbackInfo< v8::Value > *info)
static void Quit (const v8::FunctionCallbackInfo< v8::Value > &info)
static void TerminateNow (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ScheduleTermination (const v8::FunctionCallbackInfo< v8::Value > &info)
static void Version (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WriteFile (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ReadFile (const v8::FunctionCallbackInfo< v8::Value > &info)
static void CreateWasmMemoryMapDescriptor (const v8::FunctionCallbackInfo< v8::Value > &info)
static char * ReadChars (const char *name, int *size_out)
static MaybeLocal< PrimitiveArray > ReadLines (Isolate *isolate, const char *name)
static void ReadBuffer (const v8::FunctionCallbackInfo< v8::Value > &info)
static Local< String > ReadFromStdin (Isolate *isolate)
static void ReadLine (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WriteChars (const char *name, uint8_t *buffer, size_t buffer_size)
static void ExecuteFile (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SetTimeout (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ReadCodeTypeAndArguments (const v8::FunctionCallbackInfo< v8::Value > &info, int index, CodeType *code_type, Local< Value > *arguments=nullptr)
static bool FunctionAndArgumentsToString (Local< Function > function, Local< Value > arguments, Local< String > *source, Isolate *isolate)
static MaybeLocal< String > ReadSource (const v8::FunctionCallbackInfo< v8::Value > &info, int index, CodeType default_type)
static void WorkerNew (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WorkerPostMessage (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WorkerGetMessage (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WorkerOnMessageGetter (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WorkerOnMessageSetter (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WorkerTerminate (const v8::FunctionCallbackInfo< v8::Value > &info)
static void WorkerTerminateAndWait (const v8::FunctionCallbackInfo< v8::Value > &info)
static void System (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ChangeDirectory (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SetEnvironment (const v8::FunctionCallbackInfo< v8::Value > &info)
static void UnsetEnvironment (const v8::FunctionCallbackInfo< v8::Value > &info)
static void SetUMask (const v8::FunctionCallbackInfo< v8::Value > &info)
static void MakeDirectory (const v8::FunctionCallbackInfo< v8::Value > &info)
static void RemoveDirectory (const v8::FunctionCallbackInfo< v8::Value > &info)
static void GetExtrasBindingObject (const v8::FunctionCallbackInfo< v8::Value > &info)
static MaybeLocal< Promise > HostImportModuleDynamically (Local< Context > context, Local< Data > host_defined_options, Local< Value > resource_name, Local< String > specifier, Local< FixedArray > import_attributes)
static MaybeLocal< Promise > HostImportModuleWithPhaseDynamically (Local< Context > context, Local< Data > host_defined_options, Local< Value > resource_name, Local< String > specifier, ModuleImportPhase phase, Local< FixedArray > import_attributes)
static void ModuleResolutionSuccessCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
static void ModuleResolutionFailureCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
static void HostInitializeImportMetaObject (Local< Context > context, Local< Module > module, Local< Object > meta)
static MaybeLocal< Context > HostCreateShadowRealmContext (Local< Context > initiator_context)
static void DoHostImportModuleDynamically (void *data)
static void AddOSMethods (v8::Isolate *isolate, Local< ObjectTemplate > os_template)
static void SetWaitUntilDone (Isolate *isolate, bool value)
static char * ReadCharsFromTcpPort (const char *name, int *size_out)
static void set_script_executed ()
static bool use_interactive_shell ()
static void update_script_size (int size)
static bool is_valid_fuzz_script ()
static void WaitForRunningWorkers (const i::ParkedScope &parked)
static void AddRunningWorker (std::shared_ptr< Worker > worker)
static void RemoveRunningWorker (const std::shared_ptr< Worker > &worker)
static void Initialize (Isolate *isolate, D8Console *console, bool isOnMainThread=true)
static void PromiseRejectCallback (v8::PromiseRejectMessage reject_message)
Static Public Attributes
static const char * kPrompt
static ShellOptions options
static ArrayBuffer::Allocator * array_buffer_allocator
Static Private Member Functions
static int DeserializationRunCount ()
static void WriteIgnitionDispatchCountersFile (v8::Isolate *isolate)
static void WriteLcovData (v8::Isolate *isolate, const char *file)
static Counter * GetCounter (const char *name, bool is_histogram)
static Local< String > Stringify (Isolate *isolate, Local< Value > value)
static void RunShell (Isolate *isolate)
static bool RunMainIsolate (Isolate *isolate, bool keep_context_alive)
static bool SetOptions (int argc, char *argv[])
static void NodeTypeCallback (const v8::FunctionCallbackInfo< v8::Value > &info)
static Local< FunctionTemplate > CreateEventTargetTemplate (Isolate *isolate)
static Local< FunctionTemplate > CreateNodeTemplates (Isolate *isolate, Local< FunctionTemplate > event_target)
static Local< ObjectTemplate > CreateGlobalTemplate (Isolate *isolate)
static Local< ObjectTemplate > CreateOSTemplate (Isolate *isolate)
static Local< FunctionTemplate > CreateWorkerTemplate (Isolate *isolate)
static Local< ObjectTemplate > CreateAsyncHookTemplate (Isolate *isolate)
static Local< ObjectTemplate > CreatePerformanceTemplate (Isolate *isolate)
static Local< ObjectTemplate > CreateRealmTemplate (Isolate *isolate)
static Local< ObjectTemplate > CreateD8Template (Isolate *isolate)
static Local< FunctionTemplate > CreateTestFastCApiTemplate (Isolate *isolate)
static Local< FunctionTemplate > CreateLeafInterfaceTypeTemplate (Isolate *isolate)
static MaybeLocal< Context > CreateRealm (const v8::FunctionCallbackInfo< v8::Value > &info, int index, v8::MaybeLocal< Value > global_object)
static void DisposeRealm (const v8::FunctionCallbackInfo< v8::Value > &info, int index)
static MaybeLocal< Object > FetchModuleSource (v8::Local< v8::Module > origin_module, v8::Local< v8::Context > context, const std::string &file_name, ModuleType module_type)
static MaybeLocal< Module > FetchModuleTree (v8::Local< v8::Module > origin_module, v8::Local< v8::Context > context, const std::string &file_name, ModuleType module_type)
static MaybeLocal< Value > JSONModuleEvaluationSteps (Local< Context > context, Local< Module > module)
template<class T >
static MaybeLocal< T > CompileString (Isolate *isolate, Local< Context > context, Local< String > source, const ScriptOrigin &origin)
static ScriptCompiler::CachedData * LookupCodeCache (Isolate *isolate, Local< Value > name)
static void StoreInCodeCache (Isolate *isolate, Local< Value > name, const ScriptCompiler::CachedData *data)
Static Private Attributes
static Global< Context > evaluation_context_
static base::OnceType quit_once_ = V8_ONCE_INIT
static Global< Function > stringify_function_
static base::Mutex profiler_end_callback_lock_
static std::map< Isolate *, std::pair< Global< Function >, Global< Context > > > profiler_end_callback_
static const char * stringify_source_
static CounterMap * counter_map_
static base::Mutex counter_mutex_
static CounterCollection local_counters_
static CounterCollection * counters_ = &local_counters_
static base::OS::MemoryMappedFile * counters_file_ = nullptr
static base::LazyMutex context_mutex_
static const base::TimeTicks kInitialTicks = base::TimeTicks::Now()
static base::LazyMutex workers_mutex_
static bool allow_new_workers_ = true
static std::unordered_set< std::shared_ptr< Worker > > running_workers_
static std::atomic< bool > script_executed_ {false}
static std::atomic< bool > valid_fuzz_script_ {false}
static base::LazyMutex isolate_status_lock_
static std::map< Isolate *, bool > isolate_status_
static std::map< Isolate *, int > isolate_running_streaming_tasks_
static base::LazyMutex cached_code_mutex_
static std::map< std::string, std::unique_ptr< ScriptCompiler::CachedData > > cached_code_map_
static std::atomic< int > unhandled_promise_rejections_ {0}
Detailed Description
Definition at line 521 of file d8.h.
Member Enumeration Documentation
CodeType
enum v8::Shell::CodeType [strong]
Enumerator
kFileName
kString
kFunction
kInvalid
kNone
Definition at line 532 of file d8.h.
{ kFileName, kString, kFunction, kInvalid, kNone };
PrintResult
enum v8::Shell::PrintResult : bool
Enumerator
kPrintResult
kNoPrintResult
Definition at line 523 of file d8.h.
: bool { kPrintResult = true, kNoPrintResult = false };
ProcessMessageQueue
enum v8::Shell::ProcessMessageQueue : bool
Enumerator
kProcessMessageQueue
kNoProcessMessageQueue
Definition at line 528 of file d8.h.
                           : bool {
    kProcessMessageQueue = true,
    kNoProcessMessageQueue = false
  };
ReportExceptions
enum v8::Shell::ReportExceptions : bool
Enumerator
kReportExceptions
kNoReportExceptions
Definition at line 524 of file d8.h.
                        : bool {
    kReportExceptions = true,
    kNoReportExceptions = false
  };
Member Function Documentation
AddHistogramSample()
void v8::Shell::AddHistogramSample (void * histogram, int sample) [static]
Definition at line 3864 of file d8.cc.
                                                          {
  Counter* counter = reinterpret_cast<Counter*>(histogram);
  counter->AddSample(sample);
}
References v8::Counter::AddSample().
AddOSMethods()
void v8::Shell::AddOSMethods (v8::Isolate * isolate, Local< ObjectTemplate > os_template) [static]
Definition at line 747 of file d8-posix.cc.
                                                                         {
  if (options.enable_os_system) {
    os_templ->Set(isolate, "system", FunctionTemplate::New(isolate, System));
  }
  os_templ->Set(isolate, "chdir",
                FunctionTemplate::New(isolate, ChangeDirectory));
  os_templ->Set(isolate, "setenv",
                FunctionTemplate::New(isolate, SetEnvironment));
  os_templ->Set(isolate, "unsetenv",
                FunctionTemplate::New(isolate, UnsetEnvironment));
  os_templ->Set(isolate, "umask", FunctionTemplate::New(isolate, SetUMask));
  os_templ->Set(isolate, "mkdirp",
                FunctionTemplate::New(isolate, MakeDirectory));
  os_templ->Set(isolate, "rmdir",
                FunctionTemplate::New(isolate, RemoveDirectory));
}
References ChangeDirectory(), v8::ShellOptions::enable_os_system, MakeDirectory(), v8::FunctionTemplate::New(), options, RemoveDirectory(), SetEnvironment(), SetUMask(), System(), and UnsetEnvironment().
AddRunningWorker()
void v8::Shell::AddRunningWorker (std::shared_ptr< Worker > worker) [static]
Definition at line 6610 of file d8.cc.
                                                         {
  workers_mutex_.Pointer()->AssertHeld(); // caller should hold the mutex.
  running_workers_.insert(worker);
}
Referenced by v8::Worker::StartWorkerThread().
AsyncHooksCreateHook()
void v8::Shell::AsyncHooksCreateHook (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2760 of file d8.cc.
                                                 {
  Local<Object> wrap =
      PerIsolateData::Get(info.GetIsolate())->GetAsyncHooks()->CreateHook(info);
  info.GetReturnValue().Set(wrap);
}
References v8::AsyncHooks::CreateHook(), v8::PerIsolateData::Get(), v8::PerIsolateData::GetAsyncHooks(), v8::FunctionCallbackInfo< T >::GetIsolate(), and v8::FunctionCallbackInfo< T >::GetReturnValue().
AsyncHooksExecutionAsyncId()
void v8::Shell::AsyncHooksExecutionAsyncId (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2769 of file d8.cc.
                                                 {
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  info.GetReturnValue().Set(v8::Number::New(
      isolate,
      PerIsolateData::Get(isolate)->GetAsyncHooks()->GetExecutionAsyncId()));
}
References v8::PerIsolateData::Get(), v8::PerIsolateData::GetAsyncHooks(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::Number::New().
AsyncHooksTriggerAsyncId()
void v8::Shell::AsyncHooksTriggerAsyncId (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2778 of file d8.cc.
                                                 {
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  info.GetReturnValue().Set(v8::Number::New(
      isolate,
      PerIsolateData::Get(isolate)->GetAsyncHooks()->GetTriggerAsyncId()));
}
References v8::PerIsolateData::Get(), v8::PerIsolateData::GetAsyncHooks(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::Number::New().
ChangeDirectory()
void v8::Shell::ChangeDirectory (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 493 of file d8-posix.cc.
                                                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  if (info.Length() != 1) {
    info.GetIsolate()->ThrowError("chdir() takes one argument");
    return;
  }
  String::Utf8Value directory(info.GetIsolate(), info[0]);
  if (*directory == nullptr) {
    info.GetIsolate()->ThrowError(
        "os.chdir(): String conversion of argument failed.");
    return;
  }
  if (chdir(*directory) != 0) {
    info.GetIsolate()->ThrowError(v8_strerror(info.GetIsolate(), errno));
    return;
  }
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::ThrowError(), v8::anonymous_namespace{d8-posix.cc}::v8_strerror(), and v8::internal::ValidateCallbackInfo().
Referenced by AddOSMethods().
CollectGarbage()
void v8::Shell::CollectGarbage (Isolate * isolate) [static]
Definition at line 6219 of file d8.cc.
                                           {
  if (options.send_idle_notification) {
    isolate->ContextDisposedNotification(
        v8::ContextDependants::kSomeDependants);
  }
  if (options.invoke_weak_callbacks) {
    // By sending a low memory notifications, we will try hard to collect all
    // garbage and will therefore also invoke all weak callbacks of actually
    // unreachable persistent handles.
    isolate->LowMemoryNotification();
  }
}
References v8::Isolate::ContextDisposedNotification(), v8::kSomeDependants, and v8::Isolate::LowMemoryNotification().
Referenced by v8::SourceGroup::ExecuteInThread(), and v8::Worker::ExecuteInThread().
CompileString()
template<class T >
MaybeLocal< T > v8::Shell::CompileString (Isolate * isolate, Local< Context > context, Local< String > source, const ScriptOrigin & origin) [static], [private]
Definition at line 688 of file d8.cc.
                                                               {
  if (options.streaming_compile) {
    v8::ScriptCompiler::StreamedSource streamed_source(
        std::make_unique<DummySourceStream>(isolate, source),
        v8::ScriptCompiler::StreamedSource::TWO_BYTE);
    std::unique_ptr<v8::ScriptCompiler::ScriptStreamingTask> streaming_task(
        v8::ScriptCompiler::StartStreaming(isolate, &streamed_source,
                                           std::is_same_v<T, Module>
                                               ? v8::ScriptType::kModule
                                               : v8::ScriptType::kClassic));
    StreamerThread::StartThreadForTaskAndJoin(streaming_task.get());
    return CompileStreamed<T>(context, &streamed_source, source, origin);
  }
  ScriptCompiler::CachedData* cached_code = nullptr;
  if (options.compile_options & ScriptCompiler::kConsumeCodeCache) {
    cached_code = LookupCodeCache(isolate, source);
  }
  ScriptCompiler::Source script_source(source, origin, cached_code);
  MaybeLocal<T> result =
      Compile<T>(context, &script_source,
                 cached_code ? ScriptCompiler::kConsumeCodeCache
                             : ScriptCompiler::kNoCompileOptions);
  if (cached_code) CHECK(!cached_code->rejected);
  return result;
}
References CHECK, v8::ShellOptions::compile_options, v8::kClassic, v8::ScriptCompiler::kConsumeCodeCache, v8::kModule, v8::ScriptCompiler::kNoCompileOptions, LookupCodeCache(), options, v8::ScriptCompiler::CachedData::rejected, v8::base::internal::result, v8::ScriptCompiler::StartStreaming(), v8::StreamerThread::StartThreadForTaskAndJoin(), v8::ShellOptions::streaming_compile, and v8::ScriptCompiler::StreamedSource::TWO_BYTE.
CompleteMessageLoop()
bool v8::Shell::CompleteMessageLoop (Isolate * isolate) [static]
Definition at line 6281 of file d8.cc.
                                                {
  auto get_waiting_behaviour = [isolate]() {
    if (options.wait_for_background_tasks &&
        isolate->HasPendingBackgroundTasks()) {
      return platform::MessageLoopBehavior::kWaitForWork;
    }
    if (PerIsolateData::Get(isolate)->HasRunningSubscribedWorkers()) {
      return platform::MessageLoopBehavior::kWaitForWork;
    }
    return platform::MessageLoopBehavior::kDoNotWait;
  };
  if (i::v8_flags.verify_predictable) {
    bool ran_tasks = ProcessMessages(
        isolate, [] { return platform::MessageLoopBehavior::kDoNotWait; });
    if (get_waiting_behaviour() ==
        platform::MessageLoopBehavior::kWaitForWork) {
      FATAL(
          "There is outstanding work after executing all tasks in predictable "
          "mode -- this would deadlock.");
    }
    return ran_tasks;
  }
  return ProcessMessages(isolate, get_waiting_behaviour);
}
References FATAL, v8::PerIsolateData::Get(), v8::Isolate::HasPendingBackgroundTasks(), v8::PerIsolateData::HasRunningSubscribedWorkers(), v8::platform::kDoNotWait, v8::platform::kWaitForWork, v8::Worker::ProcessMessages(), and v8::internal::v8_flags.
Referenced by ExecuteModule().
CreateAsyncHookTemplate()
Local< ObjectTemplate > v8::Shell::CreateAsyncHookTemplate (Isolate * isolate) [static], [private]
Definition at line 4056 of file d8.cc.
                                                                     {
  Local<ObjectTemplate> async_hooks_templ = ObjectTemplate::New(isolate);
  async_hooks_templ->Set(isolate, "createHook",
                         FunctionTemplate::New(isolate, AsyncHooksCreateHook));
  async_hooks_templ->Set(
      isolate, "executionAsyncId",
      FunctionTemplate::New(isolate, AsyncHooksExecutionAsyncId));
  async_hooks_templ->Set(
      isolate, "triggerAsyncId",
      FunctionTemplate::New(isolate, AsyncHooksTriggerAsyncId));
  return async_hooks_templ;
}
References v8::FunctionTemplate::New(), and v8::ObjectTemplate::New().
Referenced by CreateGlobalTemplate().
CreateD8Template()
Local< ObjectTemplate > v8::Shell::CreateD8Template (Isolate * isolate) [static], [private]
Definition at line 4112 of file d8.cc.
                                                              {
  Local<ObjectTemplate> d8_template = ObjectTemplate::New(isolate);
  {
    Local<ObjectTemplate> file_template = ObjectTemplate::New(isolate);
    file_template->Set(isolate, "read",
                       FunctionTemplate::New(isolate, Shell::ReadFile));
    file_template->Set(isolate, "execute",
                       FunctionTemplate::New(isolate, Shell::ExecuteFile));
#if V8_TARGET_OS_LINUX && V8_ENABLE_WEBASSEMBLY
    if (i::v8_flags.experimental_wasm_memory_control) {
      file_template->Set(
          isolate, "create_wasm_memory_map_descriptor",
          FunctionTemplate::New(isolate, Shell::CreateWasmMemoryMapDescriptor));
    }
#endif
    d8_template->Set(isolate, "file", file_template);
  }
  {
    Local<ObjectTemplate> log_template = ObjectTemplate::New(isolate);
    log_template->Set(isolate, "getAndStop",
                      FunctionTemplate::New(isolate, LogGetAndStop));
    d8_template->Set(isolate, "log", log_template);
  }
  {
    Local<ObjectTemplate> dom_template = ObjectTemplate::New(isolate);
    Local<FunctionTemplate> event_target =
        Shell::CreateEventTargetTemplate(isolate);
    dom_template->Set(isolate, "EventTarget", event_target);
    dom_template->Set(isolate, "Div",
                      Shell::CreateNodeTemplates(isolate, event_target));
    d8_template->Set(isolate, "dom", dom_template);
  }
  {
    Local<ObjectTemplate> test_template = ObjectTemplate::New(isolate);
    // For different runs of correctness fuzzing the bytecode of a function
    // might get flushed, resulting in spurious errors.
    if (!i::v8_flags.correctness_fuzzer_suppressions) {
      test_template->Set(
          isolate, "verifySourcePositions",
          FunctionTemplate::New(isolate, TestVerifySourcePositions));
    }
    // Correctness fuzzing will attempt to compare results of tests with and
    // without turbo_fast_api_calls, so we don't expose the fast_c_api
    // constructor when --correctness_fuzzer_suppressions is on.
    if (options.expose_fast_api && i::v8_flags.turbo_fast_api_calls &&
        !i::v8_flags.correctness_fuzzer_suppressions) {
      test_template->Set(isolate, "FastCAPI",
                         Shell::CreateTestFastCApiTemplate(isolate));
      test_template->Set(isolate, "LeafInterfaceType",
                         Shell::CreateLeafInterfaceTypeTemplate(isolate));
    }
    // Allows testing code paths that are triggered when Origin Trials are
    // added in the browser.
    test_template->Set(
        isolate, "installConditionalFeatures",
        FunctionTemplate::New(isolate, Shell::InstallConditionalFeatures));
    // Enable JavaScript Promise Integration at runtime, to simulate
    // Origin Trial behavior.
    test_template->Set(isolate, "enableJSPI",
                       FunctionTemplate::New(isolate, Shell::EnableJSPI));
    test_template->Set(
        isolate, "setFlushDenormals",
        FunctionTemplate::New(isolate, Shell::SetFlushDenormals));
    d8_template->Set(isolate, "test", test_template);
  }
  {
    Local<ObjectTemplate> promise_template = ObjectTemplate::New(isolate);
    promise_template->Set(
        isolate, "setHooks",
        FunctionTemplate::New(isolate, SetPromiseHooks, Local<Value>(),
                              Local<Signature>(), 4));
    d8_template->Set(isolate, "promise", promise_template);
  }
  {
    Local<ObjectTemplate> debugger_template = ObjectTemplate::New(isolate);
    debugger_template->Set(
        isolate, "enable",
        FunctionTemplate::New(isolate, EnableDebugger, Local<Value>(),
                              Local<Signature>(), 0));
    debugger_template->Set(
        isolate, "disable",
        FunctionTemplate::New(isolate, DisableDebugger, Local<Value>(),
                              Local<Signature>(), 0));
    d8_template->Set(isolate, "debugger", debugger_template);
  }
  {
    Local<ObjectTemplate> serializer_template = ObjectTemplate::New(isolate);
    serializer_template->Set(
        isolate, "serialize",
        FunctionTemplate::New(isolate, SerializerSerialize));
    serializer_template->Set(
        isolate, "deserialize",
        FunctionTemplate::New(isolate, SerializerDeserialize, Local<Value>(),
                              Local<Signature>(), 1));
    d8_template->Set(isolate, "serializer", serializer_template);
  }
  {
    Local<ObjectTemplate> profiler_template = ObjectTemplate::New(isolate);
    profiler_template->Set(
        isolate, "setOnProfileEndListener",
        FunctionTemplate::New(isolate, ProfilerSetOnProfileEndListener));
    profiler_template->Set(
        isolate, "triggerSample",
        FunctionTemplate::New(isolate, ProfilerTriggerSample));
    d8_template->Set(isolate, "profiler", profiler_template);
  }
  {
    Local<ObjectTemplate> constants_template = ObjectTemplate::New(isolate);
    if (!i::v8_flags.correctness_fuzzer_suppressions) {
      // Don't expose these constants in differential-fuzzing builds as they
      // differ with lower-limits mode.
      constants_template->Set(
          String::NewFromUtf8Literal(isolate, "maxFixedArrayCapacity",
                                     NewStringType::kInternalized),
          Number::New(isolate, i::kMaxFixedArrayCapacity));
      constants_template->Set(
          String::NewFromUtf8Literal(isolate, "maxFastArrayLength",
                                     NewStringType::kInternalized),
          Number::New(isolate, i::JSArray::kMaxFastArrayLength));
    }
    d8_template->Set(isolate, "constants", constants_template);
  }
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  d8_template->Set(
      isolate, "getContinuationPreservedEmbedderDataViaAPIForTesting",
      FunctionTemplate::New(isolate, GetContinuationPreservedEmbedderData));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  d8_template->Set(isolate, "terminateNow",
                   FunctionTemplate::New(isolate, TerminateNow));
  d8_template->Set(isolate, "terminate",
                   FunctionTemplate::New(isolate, ScheduleTermination));
  d8_template->Set(isolate, "getExtrasBindingObject",
                   FunctionTemplate::New(isolate, GetExtrasBindingObject));
  if (!options.omit_quit) {
    d8_template->Set(isolate, "quit", FunctionTemplate::New(isolate, Quit));
  }
  return d8_template;
}
References CreateEventTargetTemplate(), CreateLeafInterfaceTypeTemplate(), CreateNodeTemplates(), CreateTestFastCApiTemplate(), CreateWasmMemoryMapDescriptor(), EnableJSPI(), ExecuteFile(), InstallConditionalFeatures(), v8::kInternalized, v8::internal::JSArray::kMaxFastArrayLength, v8::internal::kMaxFixedArrayCapacity, v8::Number::New(), v8::FunctionTemplate::New(), v8::ObjectTemplate::New(), v8::String::NewFromUtf8Literal(), ReadFile(), SetFlushDenormals(), and v8::internal::v8_flags.
Referenced by CreateGlobalTemplate().
CreateEvaluationContext()
MaybeLocal< Context > v8::Shell::CreateEvaluationContext (Isolate * isolate) [static]
Definition at line 4362 of file d8.cc.
                                                                   {
  // This needs to be a critical section since this is not thread-safe
  i::ParkedMutexGuard lock_guard(
      reinterpret_cast<i::Isolate*>(isolate)->main_thread_local_isolate(),
      context_mutex_.Pointer());
  // Initialize the global objects
  Local<ObjectTemplate> global_template = CreateGlobalTemplate(isolate);
  EscapableHandleScope handle_scope(isolate);
  Local<Context> context = Context::New(isolate, nullptr, global_template);
  if (context.IsEmpty()) {
    DCHECK(isolate->IsExecutionTerminating());
    return {};
  }
  if (i::v8_flags.perf_prof_annotate_wasm ||
      i::v8_flags.vtune_prof_annotate_wasm) {
    isolate->SetWasmLoadSourceMapCallback(Shell::WasmLoadSourceMapCallback);
  }
  InitializeModuleEmbedderData(context);
  Context::Scope scope(context);
  if (options.include_arguments) {
    const std::vector<const char*>& args = options.arguments;
    int size = static_cast<int>(args.size());
    Local<Array> array = Array::New(isolate, size);
    for (int i = 0; i < size; i++) {
      Local<String> arg =
          v8::String::NewFromUtf8(isolate, args[i]).ToLocalChecked();
      Local<Number> index = v8::Number::New(isolate, i);
      array->Set(context, index, arg).FromJust();
    }
    Local<String> name = String::NewFromUtf8Literal(
        isolate, "arguments", NewStringType::kInternalized);
    context->Global()->Set(context, name, array).FromJust();
  }
  {
    // setup console global.
    Local<String> name = String::NewFromUtf8Literal(
        isolate, "console", NewStringType::kInternalized);
    Local<Value> console =
        context->GetExtrasBindingObject()->Get(context, name).ToLocalChecked();
    context->Global()->Set(context, name, console).FromJust();
  }
  return handle_scope.Escape(context);
}
References v8::base::args, DCHECK, v8::EscapableHandleScope::Escape(), v8::Object::Get(), v8::Context::GetExtrasBindingObject(), v8::Context::Global(), v8::internal::index, v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Isolate::IsExecutionTerminating(), v8::kInternalized, name, v8::Number::New(), v8::Context::New(), v8::Array::New(), v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), v8::Object::Set(), v8::Isolate::SetWasmLoadSourceMapCallback(), size(), v8::MaybeLocal< T >::ToLocalChecked(), v8::internal::v8_flags, and WasmLoadSourceMapCallback().
Referenced by v8::SourceGroup::ExecuteInThread(), and v8::Worker::ExecuteInThread().
CreateEventTargetTemplate()
Local< FunctionTemplate > v8::Shell::CreateEventTargetTemplate (Isolate * isolate) [static], [private]
Definition at line 3915 of file d8.cc.
                                                                         {
  Local<FunctionTemplate> event_target =
      NewDOMFunctionTemplate(isolate, JSApiInstanceType::kEventTarget);
  return event_target;
}
References v8::kEventTarget, and v8::NewDOMFunctionTemplate().
Referenced by CreateD8Template().
CreateGlobalTemplate()
Local< ObjectTemplate > v8::Shell::CreateGlobalTemplate (Isolate * isolate) [static], [private]
Definition at line 3957 of file d8.cc.
                                                                  {
  Local<ObjectTemplate> global_template = ObjectTemplate::New(isolate);
  global_template->Set(Symbol::GetToStringTag(isolate),
                       String::NewFromUtf8Literal(isolate, "global"));
  global_template->Set(isolate, "version",
                       FunctionTemplate::New(isolate, Version));
  global_template->Set(isolate, "print", FunctionTemplate::New(isolate, Print));
  global_template->Set(isolate, "printErr",
                       FunctionTemplate::New(isolate, PrintErr));
  global_template->Set(isolate, "write",
                       FunctionTemplate::New(isolate, WriteStdout));
  if (!i::v8_flags.fuzzing) {
    global_template->Set(isolate, "writeFile",
                         FunctionTemplate::New(isolate, WriteFile));
  }
  global_template->Set(isolate, "read",
                       FunctionTemplate::New(isolate, ReadFile));
  global_template->Set(isolate, "readbuffer",
                       FunctionTemplate::New(isolate, ReadBuffer));
  global_template->Set(isolate, "readline",
                       FunctionTemplate::New(isolate, ReadLine));
  global_template->Set(isolate, "load",
                       FunctionTemplate::New(isolate, ExecuteFile));
  global_template->Set(isolate, "setTimeout",
                       FunctionTemplate::New(isolate, SetTimeout));
  // Some Emscripten-generated code tries to call 'quit', which in turn would
  // call C's exit(). This would lead to memory leaks, because there is no way
  // we can terminate cleanly then, so we need a way to hide 'quit'.
  if (!options.omit_quit) {
    global_template->Set(isolate, "quit", FunctionTemplate::New(isolate, Quit));
  }
  global_template->Set(isolate, "Realm", Shell::CreateRealmTemplate(isolate));
  global_template->Set(isolate, "performance",
                       Shell::CreatePerformanceTemplate(isolate));
  global_template->Set(isolate, "Worker", Shell::CreateWorkerTemplate(isolate));
  // Prevent fuzzers from creating side effects.
  if (!i::v8_flags.fuzzing) {
    global_template->Set(isolate, "os", Shell::CreateOSTemplate(isolate));
  }
  global_template->Set(isolate, "d8", Shell::CreateD8Template(isolate));
  if (i::v8_flags.expose_async_hooks) {
    global_template->Set(isolate, "async_hooks",
                         Shell::CreateAsyncHookTemplate(isolate));
  }
  return global_template;
}
References CreateAsyncHookTemplate(), CreateD8Template(), CreateOSTemplate(), CreatePerformanceTemplate(), CreateRealmTemplate(), CreateWorkerTemplate(), v8::Symbol::GetToStringTag(), v8::FunctionTemplate::New(), v8::ObjectTemplate::New(), v8::String::NewFromUtf8Literal(), v8::internal::Print(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadFile(), v8::internal::ReadLine(), and v8::internal::v8_flags.
CreateHistogram()
void * v8::Shell::CreateHistogram (const char * name, int min, int max, size_t buckets) [static]
Definition at line 3859 of file d8.cc.
                                             {
  return GetCounter(name, true);
}
References name.
CreateLeafInterfaceTypeTemplate()
Local< FunctionTemplate > v8::Shell::CreateLeafInterfaceTypeTemplate (Isolate * isolate) [static], [private]
Definition at line 2008 of file d8-test.cc.
                      {
  Local<FunctionTemplate> leaf_object_ctor =
      FunctionTemplate::New(isolate, CreateLeafInterfaceObject);
  leaf_object_ctor->SetClassName(
      String::NewFromUtf8Literal(isolate, "LeafInterfaceType"));
  return leaf_object_ctor;
}
References v8::CreateLeafInterfaceObject(), v8::FunctionTemplate::New(), and v8::String::NewFromUtf8Literal().
Referenced by CreateD8Template().
CreateNodeTemplates()
Local< FunctionTemplate > v8::Shell::CreateNodeTemplates (Isolate * isolate, Local< FunctionTemplate > event_target) [static], [private]
Definition at line 3921 of file d8.cc.
                                                            {
  Local<FunctionTemplate> node =
      NewDOMFunctionTemplate(isolate, JSApiInstanceType::kNode);
  node->Inherit(event_target);
  PerIsolateData* data = PerIsolateData::Get(isolate);
  data->SetDomNodeCtor(node);
  Local<ObjectTemplate> proto_template = node->PrototypeTemplate();
  Local<Signature> signature = v8::Signature::New(isolate, node);
  Local<FunctionTemplate> nodeType = FunctionTemplate::New(
      isolate, NodeTypeCallback, Local<Value>(), signature, 0,
      ConstructorBehavior::kThrow, SideEffectType::kHasSideEffect, nullptr,
      static_cast<uint16_t>(JSApiInstanceType::kGenericApiObject),
      static_cast<uint16_t>(JSApiInstanceType::kElement),
      static_cast<uint16_t>(JSApiInstanceType::kHTMLDivElement));
  nodeType->SetAcceptAnyReceiver(false);
  proto_template->SetAccessorProperty(
      String::NewFromUtf8Literal(isolate, "nodeType"), nodeType);
  Local<FunctionTemplate> element =
      NewDOMFunctionTemplate(isolate, JSApiInstanceType::kElement);
  element->Inherit(node);
  Local<FunctionTemplate> html_element =
      NewDOMFunctionTemplate(isolate, JSApiInstanceType::kHTMLElement);
  html_element->Inherit(element);
  Local<FunctionTemplate> div_element =
      NewDOMFunctionTemplate(isolate, JSApiInstanceType::kHTMLDivElement);
  div_element->Inherit(html_element);
  return div_element;
}
References v8::PerIsolateData::Get(), v8::kElement, v8::kGenericApiObject, v8::kHasSideEffect, v8::kHTMLDivElement, v8::kHTMLElement, v8::kNode, v8::kThrow, v8::FunctionTemplate::New(), v8::Signature::New(), v8::NewDOMFunctionTemplate(), v8::String::NewFromUtf8Literal(), and v8::PerIsolateData::SetDomNodeCtor().
Referenced by CreateD8Template().
CreateOSTemplate()
Local< ObjectTemplate > v8::Shell::CreateOSTemplate (Isolate * isolate) [static], [private]
Definition at line 4008 of file d8.cc.
                                                              {
  Local<ObjectTemplate> os_template = ObjectTemplate::New(isolate);
  AddOSMethods(isolate, os_template);
  os_template->Set(isolate, "name",
                   v8::String::NewFromUtf8Literal(isolate, V8_TARGET_OS_STRING),
                   PropertyAttribute::ReadOnly);
  os_template->Set(
      isolate, "d8Path",
      v8::String::NewFromUtf8(isolate, options.d8_path).ToLocalChecked(),
      PropertyAttribute::ReadOnly);
  return os_template;
}
References v8::ObjectTemplate::New(), v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), v8::ReadOnly, and V8_TARGET_OS_STRING.
Referenced by CreateGlobalTemplate().
CreatePerformanceTemplate()
Local< ObjectTemplate > v8::Shell::CreatePerformanceTemplate (Isolate * isolate) [static], [private]
Definition at line 4069 of file d8.cc.
                                                                       {
  Local<ObjectTemplate> performance_template = ObjectTemplate::New(isolate);
  performance_template->Set(isolate, "now",
                            FunctionTemplate::New(isolate, PerformanceNow));
  performance_template->Set(isolate, "mark",
                            FunctionTemplate::New(isolate, PerformanceMark));
  performance_template->Set(isolate, "measure",
                            FunctionTemplate::New(isolate, PerformanceMeasure));
  performance_template->Set(
      isolate, "measureMemory",
      FunctionTemplate::New(isolate, PerformanceMeasureMemory));
  return performance_template;
}
References v8::FunctionTemplate::New(), and v8::ObjectTemplate::New().
Referenced by CreateGlobalTemplate().
CreateRealm()
MaybeLocal< Context > v8::Shell::CreateRealm (const v8::FunctionCallbackInfo< v8::Value > & info, int index, v8::MaybeLocal< Value > global_object) [static], [private]
Definition at line 2391 of file d8.cc.
                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  const char* kGlobalHandleLabel = "d8::realm";
  Isolate* isolate = info.GetIsolate();
  if (isolate->IsExecutionTerminating()) return MaybeLocal<Context>();
  TryCatch try_catch(isolate);
  PerIsolateData* data = PerIsolateData::Get(isolate);
  if (index < 0) {
    Global<Context>* old_realms = data->realms_;
    index = data->realm_count_;
    data->realms_ = new Global<Context>[++data->realm_count_];
    for (int i = 0; i < index; ++i) {
      Global<Context>& realm = data->realms_[i];
      realm.Reset(isolate, old_realms[i]);
      if (!realm.IsEmpty()) {
        realm.AnnotateStrongRetainer(kGlobalHandleLabel);
      }
      old_realms[i].Reset();
    }
    delete[] old_realms;
  }
  Local<ObjectTemplate> global_template = CreateGlobalTemplate(isolate);
  Local<Context> context =
      Context::New(isolate, nullptr, global_template, global_object);
  if (context.IsEmpty()) return MaybeLocal<Context>();
  DCHECK(!try_catch.HasCaught());
  InitializeModuleEmbedderData(context);
  data->realms_[index].Reset(isolate, context);
  data->realms_[index].AnnotateStrongRetainer(kGlobalHandleLabel);
  info.GetReturnValue().Set(index);
  return context;
}
References v8::PersistentBase< T >::AnnotateStrongRetainer(), DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::TryCatch::HasCaught(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Isolate::IsExecutionTerminating(), v8_inspector::anonymous_namespace{injected-script.cc}::kGlobalHandleLabel, v8::Context::New(), v8::PerIsolateData::realm_count_, v8::PerIsolateData::realms_, v8::PersistentBase< T >::Reset(), and v8::internal::ValidateCallbackInfo().
CreateRealmTemplate()
Local< ObjectTemplate > v8::Shell::CreateRealmTemplate (Isolate * isolate) [static], [private]
Definition at line 4083 of file d8.cc.
                                                                 {
  Local<ObjectTemplate> realm_template = ObjectTemplate::New(isolate);
  realm_template->Set(isolate, "current",
                      FunctionTemplate::New(isolate, RealmCurrent));
  realm_template->Set(isolate, "owner",
                      FunctionTemplate::New(isolate, RealmOwner));
  realm_template->Set(isolate, "global",
                      FunctionTemplate::New(isolate, RealmGlobal));
  realm_template->Set(isolate, "create",
                      FunctionTemplate::New(isolate, RealmCreate));
  realm_template->Set(
      isolate, "createAllowCrossRealmAccess",
      FunctionTemplate::New(isolate, RealmCreateAllowCrossRealmAccess));
  realm_template->Set(isolate, "navigate",
                      FunctionTemplate::New(isolate, RealmNavigate));
  realm_template->Set(isolate, "detachGlobal",
                      FunctionTemplate::New(isolate, RealmDetachGlobal));
  realm_template->Set(isolate, "dispose",
                      FunctionTemplate::New(isolate, RealmDispose));
  realm_template->Set(isolate, "switch",
                      FunctionTemplate::New(isolate, RealmSwitch));
  realm_template->Set(isolate, "eval",
                      FunctionTemplate::New(isolate, RealmEval));
  realm_template->SetNativeDataProperty(
      String::NewFromUtf8Literal(isolate, "shared"), RealmSharedGet,
      RealmSharedSet);
  return realm_template;
}
References v8::FunctionTemplate::New(), v8::ObjectTemplate::New(), and v8::String::NewFromUtf8Literal().
Referenced by CreateGlobalTemplate().
CreateTestFastCApiTemplate()
Local< FunctionTemplate > v8::Shell::CreateTestFastCApiTemplate (Isolate * isolate) [static], [private]
Definition at line 1511 of file d8-test.cc.
                                                                          {
  Local<FunctionTemplate> api_obj_ctor =
      FunctionTemplate::New(isolate, CreateFastCAPIObject);
  PerIsolateData::Get(isolate)->SetTestApiObjectCtor(api_obj_ctor);
  Local<Signature> signature = Signature::New(isolate, api_obj_ctor);
  {
    CFunction throw_no_fallback_func = CFunction::Make(
        FastCApiObject::ThrowNoFallbackFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::ThrowNoFallbackFastCallbackPatch));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "throw_no_fallback",
        FunctionTemplate::New(
            isolate, FastCApiObject::ThrowFallbackSlowCallback, Local<Value>(),
            Local<Signature>(), 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &throw_no_fallback_func));
    CFunction copy_str_func = CFunction::Make(
        FastCApiObject::CopyStringFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::CopyStringFastCallbackPatch));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "copy_string",
        FunctionTemplate::New(isolate, FastCApiObject::CopyStringSlowCallback,
                              Local<Value>(), signature, 1,
                              ConstructorBehavior::kThrow,
                              SideEffectType::kHasSideEffect, &copy_str_func));
    CFunction add_all_c_func =
        CFunction::Make(FastCApiObject::AddAllFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAllFastCallbackPatch));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all",
        FunctionTemplate::New(isolate, FastCApiObject::AddAllSlowCallback,
                              Local<Value>(), signature, 1,
                              ConstructorBehavior::kThrow,
                              SideEffectType::kHasSideEffect, &add_all_c_func));
    CFunction fast_setter = CFunction::Make(
        FastCApiObject::AttributeSetterFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::AttributeSetterFastCallback));
    CFunction fast_getter = CFunction::Make(
        FastCApiObject::AttributeGetterFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::AttributeGetterFastCallback));
    api_obj_ctor->PrototypeTemplate()->SetAccessorProperty(
        String::NewFromUtf8(isolate, "fast_attribute").ToLocalChecked(),
        FunctionTemplate::New(
            isolate, FastCApiObject::AttributeGetterSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &fast_getter),
        FunctionTemplate::New(
            isolate, FastCApiObject::AttributeSetterSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &fast_setter),
        v8::PropertyAttribute::None);
    CFunction add_all_seq_c_func = CFunction::Make(
        FastCApiObject::AddAllSequenceFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAllSequenceFastCallbackPatch));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_sequence",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllSequenceSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_seq_c_func));
    CFunction add_all_uint8_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<uint8_t>
            V8_IF_USE_SIMULATOR(
                FastCApiObject::AddAllTypedArrayFastCallbackPatch<uint8_t>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_uint8_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_uint8_typed_array_c_func));
    CFunction add_all_int32_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<int32_t>
            V8_IF_USE_SIMULATOR(
                FastCApiObject::AddAllTypedArrayFastCallbackPatch<int32_t>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_int32_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_int32_typed_array_c_func));
    CFunction add_all_int64_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<int64_t>
            V8_IF_USE_SIMULATOR(
                FastCApiObject::AddAllTypedArrayFastCallbackPatch<int64_t>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_int64_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_int64_typed_array_c_func));
    CFunction add_all_uint64_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<uint64_t>
            V8_IF_USE_SIMULATOR(
                FastCApiObject::AddAllTypedArrayFastCallbackPatch<uint64_t>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_uint64_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect,
            &add_all_uint64_typed_array_c_func));
    CFunction add_all_uint32_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<uint32_t>
            V8_IF_USE_SIMULATOR(
                FastCApiObject::AddAllTypedArrayFastCallbackPatch<uint32_t>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_uint32_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect,
            &add_all_uint32_typed_array_c_func));
    CFunction add_all_float32_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<float> V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAllTypedArrayFastCallbackPatch<float>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_float32_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect,
            &add_all_float32_typed_array_c_func));
    CFunction add_all_no_options_c_func = CFunction::Make(
        FastCApiObject::AddAllFastCallbackNoOptions V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAllFastCallbackNoOptionsPatch),
        CFunctionInfo::Int64Representation::kBigInt);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_no_options",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllSlowCallback, Local<Value>(),
            Local<Signature>(), 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_no_options_c_func));
    CFunction add_all_float64_typed_array_c_func = CFunction::Make(
        FastCApiObject::AddAllTypedArrayFastCallback<double>
            V8_IF_USE_SIMULATOR(
                FastCApiObject::AddAllTypedArrayFastCallbackPatch<double>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_float64_typed_array",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllTypedArraySlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect,
            &add_all_float64_typed_array_c_func));
    const CFunction add_all_overloads[] = {
        add_all_seq_c_func,
        add_all_no_options_c_func,
    };
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_overload",
        FunctionTemplate::NewWithCFunctionOverloads(
            isolate, FastCApiObject::AddAllSequenceSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, {add_all_overloads, 2}));
    CFunction add_all_32bit_int_8args_c_func = CFunction::Make(
        FastCApiObject::AddAll32BitIntFastCallback_8Args V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAll32BitIntFastCallback_8ArgsPatch));
    CFunction add_all_32bit_int_6args_c_func = CFunction::Make(
        FastCApiObject::AddAll32BitIntFastCallback_6Args V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAll32BitIntFastCallback_6ArgsPatch));
    CFunction add_all_32bit_int_5args_c_func = CFunction::Make(
        FastCApiObject::AddAll32BitIntFastCallback_5Args V8_IF_USE_SIMULATOR(
            FastCApiObject::AddAll32BitIntFastCallback_5ArgsPatch));
    const CFunction c_function_overloads[] = {add_all_32bit_int_6args_c_func,
                                              add_all_32bit_int_5args_c_func};
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "overloaded_add_all_32bit_int",
        FunctionTemplate::NewWithCFunctionOverloads(
            isolate, FastCApiObject::AddAll32BitIntSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, {c_function_overloads, 2}));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "overloaded_add_all_8args",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAll32BitIntSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_32bit_int_8args_c_func));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "overloaded_add_all_32bit_int_no_sig",
        FunctionTemplate::NewWithCFunctionOverloads(
            isolate, FastCApiObject::AddAll32BitIntSlowCallback, Local<Value>(),
            Local<Signature>(), 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, {c_function_overloads, 2}));
    CFunction add_32bit_int_c_func = CFunction::Make(
        FastCApiObject::Add32BitIntFastCallback V8_IF_USE_SIMULATOR(
            FastCApiObject::Add32BitIntFastCallbackPatch));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_32bit_int",
        FunctionTemplate::New(
            isolate, FastCApiObject::Add32BitIntSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_32bit_int_c_func));
    CFunction add_all_annotate_c_func = CFunction::Make(
        FastCApiObject::AddAllAnnotateFastCallback<
            v8::CTypeInfo::Flags::kEnforceRangeBit>
            V8_IF_USE_SIMULATOR(FastCApiObject::AddAllAnnotateFastCallbackPatch<
                                v8::CTypeInfo::Flags::kEnforceRangeBit>));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_annotate_enforce_range",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAllAnnotateSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &add_all_annotate_c_func));
    // Testing enforce range annotation.
    CFunction enforce_range_compare_i32_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::EnforceRangeCompare<int32_t>)
            .Arg<2, v8::CTypeInfo::Flags::kEnforceRangeBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::EnforceRangeCompareI32Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "enforce_range_compare_i32",
        FunctionTemplate::New(
            isolate, FastCApiObject::EnforceRangeCompareSlowCallback<int32_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &enforce_range_compare_i32_c_func));
    CFunction enforce_range_compare_u32_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::EnforceRangeCompare<uint32_t>)
            .Arg<2, v8::CTypeInfo::Flags::kEnforceRangeBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::EnforceRangeCompareU32Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "enforce_range_compare_u32",
        FunctionTemplate::New(
            isolate, FastCApiObject::EnforceRangeCompareSlowCallback<uint32_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &enforce_range_compare_u32_c_func));
    CFunction enforce_range_compare_i64_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::EnforceRangeCompare<int64_t>)
            .Arg<2, v8::CTypeInfo::Flags::kEnforceRangeBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::EnforceRangeCompareI64Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "enforce_range_compare_i64",
        FunctionTemplate::New(
            isolate, FastCApiObject::EnforceRangeCompareSlowCallback<int64_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &enforce_range_compare_i64_c_func));
    CFunction enforce_range_compare_u64_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::EnforceRangeCompare<uint64_t>)
            .Arg<2, v8::CTypeInfo::Flags::kEnforceRangeBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::EnforceRangeCompareU64Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "enforce_range_compare_u64",
        FunctionTemplate::New(
            isolate, FastCApiObject::EnforceRangeCompareSlowCallback<uint64_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &enforce_range_compare_u64_c_func));
    // Testing clamp annotation.
    CFunction clamp_compare_i32_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::ClampCompare<int32_t>)
            .Arg<3, v8::CTypeInfo::Flags::kClampBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::ClampCompareI32Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "clamp_compare_i32",
        FunctionTemplate::New(
            isolate, FastCApiObject::ClampCompareSlowCallback<int32_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &clamp_compare_i32_c_func));
    CFunction clamp_compare_u32_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::ClampCompare<uint32_t>)
            .Arg<3, v8::CTypeInfo::Flags::kClampBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::ClampCompareU32Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "clamp_compare_u32",
        FunctionTemplate::New(
            isolate, FastCApiObject::ClampCompareSlowCallback<uint32_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &clamp_compare_u32_c_func));
    CFunction clamp_compare_i64_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::ClampCompare<int64_t>)
            .Arg<3, v8::CTypeInfo::Flags::kClampBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::ClampCompareI64Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "clamp_compare_i64",
        FunctionTemplate::New(
            isolate, FastCApiObject::ClampCompareSlowCallback<int64_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &clamp_compare_i64_c_func));
    CFunction clamp_compare_u64_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::ClampCompare<uint64_t>)
            .Arg<3, v8::CTypeInfo::Flags::kClampBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::ClampCompareU64Patch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "clamp_compare_u64",
        FunctionTemplate::New(
            isolate, FastCApiObject::ClampCompareSlowCallback<uint64_t>,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &clamp_compare_u64_c_func));
    CFunction is_valid_api_object_c_func =
        CFunction::Make(FastCApiObject::IsFastCApiObjectFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "is_fast_c_api_object",
        FunctionTemplate::New(
            isolate, FastCApiObject::IsFastCApiObjectSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &is_valid_api_object_c_func));
    CFunction call_to_number_c_func =
        CFunction::Make(FastCApiObject::CallToNumberFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "call_to_number",
        FunctionTemplate::New(
            isolate, FastCApiObject::CallToNumberSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &call_to_number_c_func));
    CFunction test_wasm_memory_c_func =
        CFunction::Make(FastCApiObject::TestWasmMemoryFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "test_wasm_memory",
        FunctionTemplate::New(
            isolate, FastCApiObject::TestWasmMemorySlowCallback, Local<Value>(),
            Local<Signature>(), 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &test_wasm_memory_c_func));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "assert_is_external",
        FunctionTemplate::New(isolate, FastCApiObject::AssertIsExternal,
                              Local<Value>(), signature, 1,
                              ConstructorBehavior::kThrow,
                              SideEffectType::kHasSideEffect, nullptr));
    CFunction get_pointer_c_func =
        CFunction::Make(FastCApiObject::GetPointerFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "get_pointer",
        FunctionTemplate::New(
            isolate, FastCApiObject::GetPointerSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &get_pointer_c_func));
    CFunction get_null_pointer_c_func =
        CFunction::Make(FastCApiObject::GetNullPointerFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "get_null_pointer",
        FunctionTemplate::New(
            isolate, FastCApiObject::GetNullPointerSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &get_null_pointer_c_func));
    CFunction pass_pointer_c_func =
        CFunction::Make(FastCApiObject::PassPointerFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "pass_pointer",
        FunctionTemplate::New(
            isolate, FastCApiObject::PassPointerSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &pass_pointer_c_func));
    CFunction compare_pointers_c_func =
        CFunction::Make(FastCApiObject::ComparePointersFastCallback);
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "compare_pointers",
        FunctionTemplate::New(
            isolate, FastCApiObject::ComparePointersSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &compare_pointers_c_func));
    CFunction sum_int64_as_number_c_func =
        CFunctionBuilder().Fn(FastCApiObject::sumInt64FastCallback).Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "sum_int64_as_number",
        FunctionTemplate::New(
            isolate, FastCApiObject::sumInt64AsNumberSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &sum_int64_as_number_c_func));
    CFunction sum_int64_as_bigint_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::sumInt64FastCallback)
            .Build<CFunctionInfo::Int64Representation::kBigInt>();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "sum_int64_as_bigint",
        FunctionTemplate::New(
            isolate, FastCApiObject::sumInt64AsBigIntSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &sum_int64_as_bigint_c_func));
    CFunction sum_uint64_as_number_c_func =
        CFunctionBuilder().Fn(FastCApiObject::sumUint64FastCallback).Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "sum_uint64_as_number",
        FunctionTemplate::New(
            isolate, FastCApiObject::sumUint64AsNumberSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &sum_uint64_as_number_c_func));
    CFunction sum_uint64_as_bigint_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::sumUint64FastCallback)
            .Build<CFunctionInfo::Int64Representation::kBigInt>();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "sum_uint64_as_bigint",
        FunctionTemplate::New(
            isolate, FastCApiObject::sumUint64AsBigIntSlowCallback,
            Local<Value>(), signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasSideEffect, &sum_uint64_as_bigint_c_func));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "fast_call_count",
        FunctionTemplate::New(
            isolate, FastCApiObject::FastCallCount, Local<Value>(), signature,
            1, ConstructorBehavior::kThrow, SideEffectType::kHasNoSideEffect));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "slow_call_count",
        FunctionTemplate::New(
            isolate, FastCApiObject::SlowCallCount, Local<Value>(), signature,
            1, ConstructorBehavior::kThrow, SideEffectType::kHasNoSideEffect));
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "reset_counts",
        FunctionTemplate::New(isolate, FastCApiObject::ResetCounts,
                              Local<Value>(), signature, 1,
                              ConstructorBehavior::kThrow));
    CFunction add_all_32bit_int_5args_enforce_range_c_func =
        CFunctionBuilder()
            .Fn(FastCApiObject::AddAll32BitIntFastCallback_5Args)
            .Arg<3, v8::CTypeInfo::Flags::kEnforceRangeBit>()
            .Arg<5, v8::CTypeInfo::Flags::kEnforceRangeBit>()
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Patch(FastCApiObject::AddAll32BitIntFastCallback_5ArgsPatch)
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
            .Build();
    api_obj_ctor->PrototypeTemplate()->Set(
        isolate, "add_all_5args_enforce_range",
        FunctionTemplate::New(
            isolate, FastCApiObject::AddAll32BitIntSlowCallback, Local<Value>(),
            signature, 1, ConstructorBehavior::kThrow,
            SideEffectType::kHasNoSideEffect,
            &add_all_32bit_int_5args_enforce_range_c_func));
  }
  api_obj_ctor->InstanceTemplate()->SetInternalFieldCount(
      FastCApiObject::kV8WrapperObjectIndex + 1);
  return api_obj_ctor;
}
References v8::CreateFastCAPIObject(), v8::internal::CFunctionBuilder::Fn(), v8::PerIsolateData::Get(), v8::CFunctionInfo::kBigInt, v8::CTypeInfo::kClampBit, v8::CTypeInfo::kEnforceRangeBit, v8::kHasNoSideEffect, v8::kHasSideEffect, v8::kThrow, v8::CFunction::Make(), v8::FunctionTemplate::New(), v8::Signature::New(), v8::String::NewFromUtf8(), v8::FunctionTemplate::NewWithCFunctionOverloads(), v8::None, v8::PerIsolateData::SetTestApiObjectCtor(), and V8_IF_USE_SIMULATOR.
Referenced by CreateD8Template().
CreateWasmMemoryMapDescriptor()
static void v8::Shell::CreateWasmMemoryMapDescriptor (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Referenced by CreateD8Template().
CreateWorkerTemplate()
Local< FunctionTemplate > v8::Shell::CreateWorkerTemplate (Isolate * isolate) [static], [private]
Definition at line 4021 of file d8.cc.
                                                                    {
  Local<FunctionTemplate> worker_fun_template =
      FunctionTemplate::New(isolate, WorkerNew);
  Local<Signature> worker_signature =
      Signature::New(isolate, worker_fun_template);
  worker_fun_template->SetClassName(
      String::NewFromUtf8Literal(isolate, "Worker"));
  worker_fun_template->ReadOnlyPrototype();
  worker_fun_template->PrototypeTemplate()->Set(
      isolate, "terminate",
      FunctionTemplate::New(isolate, WorkerTerminate, Local<Value>(),
                            worker_signature));
  worker_fun_template->PrototypeTemplate()->Set(
      isolate, "terminateAndWait",
      FunctionTemplate::New(isolate, WorkerTerminateAndWait, Local<Value>(),
                            worker_signature));
  worker_fun_template->PrototypeTemplate()->Set(
      isolate, "postMessage",
      FunctionTemplate::New(isolate, WorkerPostMessage, Local<Value>(),
                            worker_signature));
  worker_fun_template->PrototypeTemplate()->Set(
      isolate, "getMessage",
      FunctionTemplate::New(isolate, WorkerGetMessage, Local<Value>(),
                            worker_signature));
  worker_fun_template->PrototypeTemplate()->SetAccessorProperty(
      String::NewFromUtf8(isolate, "onmessage", NewStringType::kInternalized)
          .ToLocalChecked(),
      FunctionTemplate::New(isolate, WorkerOnMessageGetter, Local<Value>(),
                            worker_signature),
      FunctionTemplate::New(isolate, WorkerOnMessageSetter, Local<Value>(),
                            worker_signature));
  worker_fun_template->InstanceTemplate()->SetInternalFieldCount(1);
  return worker_fun_template;
}
References v8::kInternalized, v8::FunctionTemplate::New(), v8::Signature::New(), v8::String::NewFromUtf8(), and v8::String::NewFromUtf8Literal().
Referenced by CreateGlobalTemplate().
DeserializationRunCount()
static int v8::Shell::DeserializationRunCount () [inline], [static], [private]
Definition at line 788 of file d8.h.
                                              {
    return options.stress_deserialize ? 1000 : 1;
  }
References options, and v8::ShellOptions::stress_deserialize.
Referenced by LoadJSON().
DeserializeValue()
MaybeLocal< Value > v8::Shell::DeserializeValue (Isolate * isolate, std::unique_ptr< SerializationData > data) [static]
Definition at line 6603 of file d8.cc.
                                                             {
  Local<Context> context = isolate->GetCurrentContext();
  Deserializer deserializer(isolate, std::move(data));
  return deserializer.ReadValue(context);
}
References v8::Isolate::GetCurrentContext(), and v8::Deserializer::ReadValue().
Referenced by v8::Worker::ProcessMessage(), v8::OnMessageFromWorkerTask::Run(), and WorkerGetMessage().
DisableDebugger()
void v8::Shell::DisableDebugger (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2793 of file d8.cc.
                                                                       {
  v8::debug::SetDebugDelegate(info.GetIsolate(), nullptr);
}
References v8::FunctionCallbackInfo< T >::GetIsolate(), and v8::debug::SetDebugDelegate().
DisposeRealm()
void v8::Shell::DisposeRealm (const v8::FunctionCallbackInfo< v8::Value > & info, int index) [static], [private]
Definition at line 2427 of file d8.cc.
                                    {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  Local<Context> context = data->realms_[index].Get(isolate);
  data->realms_[index].Reset();
  // ContextDisposedNotification expects the disposed context to be entered.
  v8::Context::Scope scope(context);
  isolate->ContextDisposedNotification(v8::ContextDependants::kSomeDependants);
}
References v8::Isolate::ContextDisposedNotification(), DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::kSomeDependants, v8::PerIsolateData::realms_, and v8::internal::ValidateCallbackInfo().
DoHostImportModuleDynamically()
void v8::Shell::DoHostImportModuleDynamically (void * data) [static]
Definition at line 1653 of file d8.cc.
                                                           {
  DynamicImportData* import_data_ =
      static_cast<DynamicImportData*>(import_data);
  Isolate* isolate(import_data_->isolate);
  Global<Context> global_realm;
  Global<Promise::Resolver> global_resolver;
  Global<Promise> global_result_promise;
  Global<Value> global_namespace_or_source;
  TryCatch try_catch(isolate);
  try_catch.SetVerbose(true);
  {
    HandleScope handle_scope(isolate);
    Local<Context> realm = import_data_->context.Get(isolate);
    Local<Value> referrer = import_data_->referrer.Get(isolate);
    Local<String> v8_specifier = import_data_->specifier.Get(isolate);
    ModuleImportPhase phase = import_data_->phase;
    Local<FixedArray> import_attributes =
        import_data_->import_attributes.Get(isolate);
    Local<Promise::Resolver> resolver = import_data_->resolver.Get(isolate);
    global_realm.Reset(isolate, realm);
    global_resolver.Reset(isolate, resolver);
    PerIsolateData* data = PerIsolateData::Get(isolate);
    data->DeleteDynamicImportData(import_data_);
    Context::Scope context_scope(realm);
    std::string specifier = ToSTLString(isolate, v8_specifier);
    ModuleType module_type =
        ModuleEmbedderData::ModuleTypeFromImportSpecifierAndAttributes(
            realm, specifier, import_attributes, false);
    if (module_type == ModuleType::kInvalid) {
      ThrowError(isolate, "Invalid module type was asserted");
      RejectPromiseIfExecutionIsNotTerminating(isolate, realm, resolver,
                                               try_catch);
      return;
    }
    std::shared_ptr<ModuleEmbedderData> module_data =
        GetModuleDataFromContext(realm);
    std::string source_url = referrer->IsNull()
                                 ? module_data->origin
                                 : ToSTLString(isolate, referrer.As<String>());
    std::string dir_name =
        DirName(NormalizePath(source_url, GetWorkingDirectory()));
    std::string absolute_path = NormalizeModuleSpecifier(specifier, dir_name);
    switch (phase) {
      case ModuleImportPhase::kSource: {
        Local<Object> module_source;
        auto module_it = module_data->module_source_map.find(
            std::make_pair(absolute_path, module_type));
        if (module_it != module_data->module_source_map.end()) {
          module_source = module_it->second.Get(isolate);
        } else if (!FetchModuleSource(Local<Module>(), realm, absolute_path,
                                      module_type)
                        .ToLocal(&module_source)) {
          break;
        }
        Local<Promise::Resolver> module_resolver =
            Promise::Resolver::New(realm).ToLocalChecked();
        module_resolver->Resolve(realm, module_source).ToChecked();
        global_namespace_or_source.Reset(isolate, module_source);
        global_result_promise.Reset(isolate, module_resolver->GetPromise());
        break;
      }
      case v8::ModuleImportPhase::kEvaluation: {
        Local<Module> root_module;
        auto module_it = module_data->module_map.find(
            std::make_pair(absolute_path, module_type));
        if (module_it != module_data->module_map.end()) {
          root_module = module_it->second.Get(isolate);
        } else if (!FetchModuleTree(Local<Module>(), realm, absolute_path,
                                    module_type)
                        .ToLocal(&root_module)) {
          break;
        }
        if (root_module
                ->InstantiateModule(realm, ResolveModuleCallback,
                                    ResolveModuleSourceCallback)
                .FromMaybe(false)) {
          MaybeLocal<Value> maybe_result = root_module->Evaluate(realm);
          if (maybe_result.IsEmpty()) break;
          global_result_promise.Reset(
              isolate, maybe_result.ToLocalChecked().As<Promise>());
          global_namespace_or_source.Reset(isolate,
                                           root_module->GetModuleNamespace());
        }
        break;
      }
      default: {
        UNREACHABLE();
      }
    }
  }
  if (global_result_promise.IsEmpty()) {
    HandleScope handle_scope(isolate);
    Local<Context> realm = global_realm.Get(isolate);
    Local<Promise::Resolver> resolver = global_resolver.Get(isolate);
    RejectPromiseIfExecutionIsNotTerminating(isolate, realm, resolver,
                                             try_catch);
    return;
  }
  {
    // This method is invoked from a microtask, where in general we may have
    // an non-trivial stack. Emptying the message queue below may trigger the
    // execution of a stackless GC. We need to override the embedder stack
    // state, to force scanning the stack, if this happens.
    i::Heap* heap = reinterpret_cast<i::Isolate*>(isolate)->heap();
    i::EmbedderStackStateScope scope(
        heap, i::EmbedderStackStateOrigin::kExplicitInvocation,
        StackState::kMayContainHeapPointers);
    EmptyMessageQueues(isolate);
  }
  // Setup callbacks, and then chain them to the result promise.
  HandleScope handle_scope(isolate);
  Local<Context> realm = global_realm.Get(isolate);
  Local<Promise::Resolver> resolver = global_resolver.Get(isolate);
  Local<Promise> result_promise = global_result_promise.Get(isolate);
  Local<Value> namespace_or_source = global_namespace_or_source.Get(isolate);
  Context::Scope context_scope(realm);
  // Chaining the promise generally does not throw, but execution may be
  // terminating (e.g. when within a worker being terminated). Check the return
  // value to display a helpful message.
  if (ChainDynamicImportPromise(isolate, realm, resolver, result_promise,
                                namespace_or_source)
          .IsNothing()) {
    RejectPromiseIfExecutionIsNotTerminating(isolate, realm, resolver,
                                             try_catch);
  }
}
References v8::Local< T >::As(), v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise(), v8::DynamicImportData::context, v8::PerIsolateData::DeleteDynamicImportData(), v8::anonymous_namespace{d8.cc}::DirName(), EmptyMessageQueues(), FetchModuleSource(), FetchModuleTree(), v8::PerIsolateData::Get(), v8::PersistentBase< T >::Get(), v8::Object::Get(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::anonymous_namespace{d8.cc}::GetWorkingDirectory(), heap(), v8::DynamicImportData::import_attributes, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::MaybeLocal< T >::IsEmpty(), v8::DynamicImportData::isolate, v8::kEvaluation, v8::kInvalid, v8::kSource, v8::Promise::Resolver::New(), v8::anonymous_namespace{d8.cc}::NormalizeModuleSpecifier(), v8::anonymous_namespace{d8.cc}::NormalizePath(), v8::DynamicImportData::phase, v8::DynamicImportData::referrer, v8::anonymous_namespace{d8.cc}::RejectPromiseIfExecutionIsNotTerminating(), v8::PersistentBase< T >::Reset(), v8::anonymous_namespace{d8.cc}::ResolveModuleCallback(), v8::anonymous_namespace{d8.cc}::ResolveModuleSourceCallback(), v8::DynamicImportData::resolver, v8::TryCatch::SetVerbose(), v8::DynamicImportData::specifier, v8::internal::string, v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocalChecked(), v8::anonymous_namespace{d8.cc}::ToSTLString(), and UNREACHABLE.
Referenced by HostImportModuleWithPhaseDynamically().
DumpCounters()
void v8::Shell::DumpCounters () [static]
Definition at line 4691 of file d8.cc.
                         {
  base::MutexGuard mutex_guard(&counter_mutex_);
  std::vector<std::pair<std::string, Counter*>> counters(counter_map_->begin(),
                                                         counter_map_->end());
  std::sort(counters.begin(), counters.end());
  if (options.dump_counters_nvp) {
    // Dump counters as name-value pairs.
    for (const auto& pair : counters) {
      std::string key = pair.first;
      Counter* counter = pair.second;
      if (counter->is_histogram()) {
        std::cout << "\"c:" << key << "\"=" << counter->count() << "\n";
        std::cout << "\"t:" << key << "\"=" << counter->sample_total() << "\n";
      } else {
        std::cout << "\"" << key << "\"=" << counter->count() << "\n";
      }
    }
    return;
  }
  // Dump counters in formatted boxes.
  constexpr int kNameBoxSize = 64;
  constexpr int kValueBoxSize = 13;
  std::cout << std::string(kNameBoxSize, '-') << "+"
            << std::string(kValueBoxSize - 1, '-') << "\n";
  std::cout << "Name" << std::string(kNameBoxSize - 4, ' ') << "| Value"
            << std::string(kValueBoxSize - 7, ' ') << "\n";
  std::cout << std::string(kNameBoxSize, '-') << "+"
            << std::string(kValueBoxSize - 1, '-') << "\n";
  for (const auto& pair : counters) {
    std::string key = pair.first;
    Counter* counter = pair.second;
    if (counter->is_histogram()) {
      std::cout << "c:" << std::setw(kNameBoxSize - 2) << std::left << key
                << std::setw(kValueBoxSize) << std::right << counter->count()
                << "\n";
      std::cout << "t:" << std::setw(kNameBoxSize - 2) << std::left << key
                << std::setw(kValueBoxSize) << std::right
                << counter->sample_total() << "\n";
    } else {
      std::cout << std::setw(kNameBoxSize) << std::left << key
                << std::setw(kValueBoxSize) << std::right << counter->count()
                << "\n";
    }
  }
}
References v8::Counter::count(), anonymous_namespace{mksnapshot.cc}::counter_map_, v8::Counter::is_histogram(), v8::internal::key, v8::Counter::sample_total(), v8::base::sort(), and v8::internal::string.
EmptyMessageQueues()
bool v8::Shell::EmptyMessageQueues (Isolate * isolate) [static]
Definition at line 6318 of file d8.cc.
                                               {
  return ProcessMessages(
      isolate, []() { return platform::MessageLoopBehavior::kDoNotWait; });
}
References v8::platform::kDoNotWait, and v8::Worker::ProcessMessages().
Referenced by DoHostImportModuleDynamically(), and ExecuteModule().
EnableDebugger()
void v8::Shell::EnableDebugger (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2789 of file d8.cc.
                                                                      {
  v8::debug::SetDebugDelegate(info.GetIsolate(), &dummy_delegate);
}
References v8::dummy_delegate, v8::FunctionCallbackInfo< T >::GetIsolate(), and v8::debug::SetDebugDelegate().
EnableJSPI()
void v8::Shell::EnableJSPI (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2731 of file d8.cc.
                                                                  {
  Isolate* isolate = info.GetIsolate();
  isolate->SetWasmJSPIEnabledCallback([](auto) { return true; });
  isolate->InstallConditionalFeatures(isolate->GetCurrentContext());
}
References v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Isolate::InstallConditionalFeatures(), and v8::Isolate::SetWasmJSPIEnabledCallback().
Referenced by CreateD8Template().
ExecuteFile()
void v8::Shell::ExecuteFile (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3119 of file d8.cc.
                                                                   {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  for (int i = 0; i < info.Length(); i++) {
    HandleScope handle_scope(isolate);
    String::Utf8Value file_name(isolate, info[i]);
    if (*file_name == nullptr) {
      std::ostringstream oss;
      oss << "Cannot convert file[" << i << "] name to string.";
      ThrowError(
          isolate,
          String::NewFromUtf8(isolate, oss.str().c_str()).ToLocalChecked());
      return;
    }
    Local<String> source;
    if (!ReadFile(isolate, *file_name).ToLocal(&source)) return;
    if (!ExecuteString(
            info.GetIsolate(), source,
            String::NewFromUtf8(isolate, *file_name).ToLocalChecked(),
            options.quiet_load ? kNoReportExceptions : kReportExceptions)) {
      std::ostringstream oss;
      oss << "Error executing file: \"" << *file_name << '"';
      ThrowError(
          isolate,
          String::NewFromUtf8(isolate, oss.str().c_str()).ToLocalChecked());
      return;
    }
  }
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::String::NewFromUtf8(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadFile(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by CreateD8Template(), and v8::Worker::ImportScripts().
ExecuteModule()
bool v8::Shell::ExecuteModule (Isolate * isolate, const char * file_name) [static]
Definition at line 1797 of file d8.cc.
                                                                 {
  HandleScope handle_scope(isolate);
  Global<Module> global_root_module;
  Global<Promise> global_result_promise;
  // Use a non-verbose TryCatch and report exceptions manually using
  // Shell::ReportException, because some errors (such as file errors) are
  // thrown without entering JS and thus do not trigger
  // isolate->ReportPendingMessages().
  TryCatch try_catch(isolate);
  {
    PerIsolateData* data = PerIsolateData::Get(isolate);
    Local<Context> realm = data->realms_[data->realm_current_].Get(isolate);
    Context::Scope context_scope(realm);
    std::string absolute_path =
        NormalizeModuleSpecifier(file_name, GetWorkingDirectory());
    std::shared_ptr<ModuleEmbedderData> module_data =
        GetModuleDataFromContext(realm);
    Local<Module> root_module;
    auto module_it = module_data->module_map.find(
        std::make_pair(absolute_path, ModuleType::kJavaScript));
    if (module_it != module_data->module_map.end()) {
      root_module = module_it->second.Get(isolate);
    } else if (!FetchModuleTree(Local<Module>(), realm, absolute_path,
                                ModuleType::kJavaScript)
                    .ToLocal(&root_module)) {
      CHECK(try_catch.HasCaught());
      ReportException(isolate, try_catch);
      return false;
    }
    global_root_module.Reset(isolate, root_module);
    module_data->origin = absolute_path;
    MaybeLocal<Value> maybe_result;
    if (root_module
            ->InstantiateModule(realm, ResolveModuleCallback,
                                ResolveModuleSourceCallback)
            .FromMaybe(false)) {
      maybe_result = root_module->Evaluate(realm);
      CHECK(!maybe_result.IsEmpty());
      global_result_promise.Reset(isolate,
                                  maybe_result.ToLocalChecked().As<Promise>());
    }
  }
  if (!global_result_promise.IsEmpty()) {
    EmptyMessageQueues(isolate);
  } else {
    DCHECK(try_catch.HasCaught());
    ReportException(isolate, try_catch);
    return false;
  }
  // Loop until module execution finishes
  while (isolate->HasPendingBackgroundTasks() ||
         (i::ValueHelper::HandleAsValue(global_result_promise)->State() ==
              Promise::kPending &&
          reinterpret_cast<i::Isolate*>(isolate)
                  ->default_microtask_queue()
                  ->size() > 0)) {
    Shell::CompleteMessageLoop(isolate);
  }
  {
    Local<Promise> result_promise = global_result_promise.Get(isolate);
    Local<Module> root_module = global_root_module.Get(isolate);
    if (result_promise->State() == Promise::kRejected) {
      // If the exception has been caught by the promise pipeline, we rethrow
      // here in order to ReportException.
      // TODO(cbruni): Clean this up after we create a new API for the case
      // where TLA is enabled.
      if (!try_catch.HasCaught()) {
        isolate->ThrowException(result_promise->Result());
      } else {
        DCHECK_EQ(try_catch.Exception(), result_promise->Result());
      }
      ReportException(isolate, try_catch);
      return false;
    }
    auto [stalled_modules, stalled_messages] =
        root_module->GetStalledTopLevelAwaitMessages(isolate);
    DCHECK_EQ(stalled_modules.size(), stalled_messages.size());
    if (stalled_messages.size() > 0) {
      Local<Message> message = stalled_messages[0];
      ReportException(isolate, message, v8::Exception::Error(message->Get()));
      return false;
    }
  }
  DCHECK(!try_catch.HasCaught());
  return true;
}
References CHECK, CompleteMessageLoop(), DCHECK, DCHECK_EQ, EmptyMessageQueues(), v8::Exception::Error(), v8::TryCatch::Exception(), FetchModuleTree(), v8::PerIsolateData::Get(), v8::PersistentBase< T >::Get(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::anonymous_namespace{d8.cc}::GetWorkingDirectory(), v8::internal::ValueHelper::HandleAsValue(), v8::TryCatch::HasCaught(), v8::Isolate::HasPendingBackgroundTasks(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::MaybeLocal< T >::IsEmpty(), v8::kJavaScript, v8::Promise::kPending, v8::Promise::kRejected, v8::anonymous_namespace{d8.cc}::NormalizeModuleSpecifier(), v8::PerIsolateData::realm_current_, v8::PerIsolateData::realms_, ReportException(), v8::PersistentBase< T >::Reset(), v8::anonymous_namespace{d8.cc}::ResolveModuleCallback(), v8::anonymous_namespace{d8.cc}::ResolveModuleSourceCallback(), v8::internal::string, v8::Isolate::ThrowException(), and v8::MaybeLocal< T >::ToLocalChecked().
Referenced by v8::SourceGroup::Execute().
ExecuteString()
bool v8::Shell::ExecuteString (Isolate * isolate, Local< String > source, Local< String > name, ReportExceptions report_exceptions, Global< Value > * out_result = nullptr) [static]
Definition at line 936 of file d8.cc.
                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  if (i_isolate->is_execution_terminating()) return true;
  if (i::v8_flags.parse_only) {
    i::VMState<PARSER> state(i_isolate);
    i::DirectHandle<i::String> str = Utils::OpenDirectHandle(*(source));
    // Set up ParseInfo.
    i::UnoptimizedCompileState compile_state;
    i::ReusableUnoptimizedCompileState reusable_state(i_isolate);
    i::UnoptimizedCompileFlags flags =
        i::UnoptimizedCompileFlags::ForToplevelCompile(
            i_isolate, true, i::construct_language_mode(i::v8_flags.use_strict),
            i::REPLMode::kNo, ScriptType::kClassic, i::v8_flags.lazy);
    if (options.compile_options & v8::ScriptCompiler::kEagerCompile) {
      flags.set_is_eager(true);
    }
    i::ParseInfo parse_info(i_isolate, flags, &compile_state, &reusable_state);
    i::Handle<i::Script> script = parse_info.CreateScript(
        i_isolate, str, i::kNullMaybeHandle, ScriptOriginOptions());
    if (!i::parsing::ParseProgram(&parse_info, script, i_isolate,
                                  i::parsing::ReportStatisticsMode::kYes)) {
      parse_info.pending_error_handler()->PrepareErrors(
          i_isolate, parse_info.ast_value_factory());
      parse_info.pending_error_handler()->ReportErrors(i_isolate, script);
      fprintf(stderr, "Failed parsing\n");
      return false;
    }
    return true;
  }
  HandleScope handle_scope(isolate);
  TryCatch try_catch(isolate);
  try_catch.SetVerbose(report_exceptions == kReportExceptions);
  // Explicitly check for stack overflows. This method can be called
  // recursively, and since we consume quite some stack space for the C++
  // frames, the stack check in the called frame might be too late.
  if (i::StackLimitCheck{i_isolate}.HasOverflowed()) {
    i_isolate->StackOverflow();
    return false;
  }
  PerIsolateData* data = PerIsolateData::Get(isolate);
  Local<Context> realm =
      Local<Context>::New(isolate, data->realms_[data->realm_current_]);
  Context::Scope context_scope(realm);
  Local<Context> context(isolate->GetCurrentContext());
  ScriptOrigin origin = CreateScriptOrigin(isolate, name, ScriptType::kClassic);
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(realm);
  module_data->origin = ToSTLString(isolate, name);
  for (int i = 1; i < options.repeat_compile; ++i) {
    HandleScope handle_scope_for_compiling(isolate);
    if (CompileString<Script>(isolate, context, source, origin).IsEmpty()) {
      return false;
    }
  }
  Local<Script> script;
  if (!CompileString<Script>(isolate, context, source, origin)
           .ToLocal(&script)) {
    return false;
  }
  if (options.code_cache_options ==
      ShellOptions::CodeCacheOptions::kProduceCache) {
    // Serialize and store it in memory for the next execution.
    ScriptCompiler::CachedData* cached_data =
        ScriptCompiler::CreateCodeCache(script->GetUnboundScript());
    StoreInCodeCache(isolate, source, cached_data);
    delete cached_data;
  }
  if (options.compile_only) return true;
  if (options.compile_options & ScriptCompiler::kConsumeCodeCache) {
    i::DirectHandle<i::Script> i_script(
        i::Cast<i::Script>(
            Utils::OpenDirectHandle(*script)->shared()->script()),
        i_isolate);
    // TODO(cbruni, chromium:1244145): remove once context-allocated.
    i_script->set_host_defined_options(i::Cast<i::FixedArray>(
        *Utils::OpenDirectHandle(*(origin.GetHostDefinedOptions()))));
  }
  MaybeLocal<Value> maybe_result = script->Run(realm);
  if (options.code_cache_options ==
          ShellOptions::CodeCacheOptions::kProduceCacheAfterExecute &&
      !isolate->IsExecutionTerminating()) {
    // Serialize and store it in memory for the next execution.
    ScriptCompiler::CachedData* cached_data =
        ScriptCompiler::CreateCodeCache(script->GetUnboundScript());
    StoreInCodeCache(isolate, source, cached_data);
    delete cached_data;
  }
  data->realm_current_ = data->realm_switch_;
  Local<Value> result;
  if (!maybe_result.ToLocal(&result)) {
    if (try_catch.HasTerminated()) {
      // Re-request terminate execution as it's been cleared, so
      // Shell::FinishExecution doesn't waste time draining all enqueued tasks
      // and microtasks.
      isolate->TerminateExecution();
      return true;
    }
    DCHECK(try_catch.HasCaught());
    return false;
  } else if (out_result != nullptr) {
    out_result->Reset(isolate, result);
  }
  // It's possible that a FinalizationRegistry cleanup task threw an error.
  return !try_catch.HasCaught();
}
References v8::internal::ParseInfo::ast_value_factory(), v8::ShellOptions::code_cache_options, v8::ShellOptions::compile_only, v8::ShellOptions::compile_options, v8::internal::construct_language_mode(), v8::ScriptCompiler::CreateCodeCache(), v8::internal::ParseInfo::CreateScript(), v8::anonymous_namespace{d8.cc}::CreateScriptOrigin(), DCHECK, flags(), v8::internal::UnoptimizedCompileFlags::ForToplevelCompile(), v8::PerIsolateData::Get(), v8::Isolate::GetCurrentContext(), v8::ScriptOrigin::GetHostDefinedOptions(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::TryCatch::HasCaught(), v8::TryCatch::HasTerminated(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Isolate::is_execution_terminating(), v8::Isolate::IsExecutionTerminating(), v8::kClassic, v8::ScriptCompiler::kConsumeCodeCache, v8::ScriptCompiler::kEagerCompile, v8::internal::kNo, v8::internal::kNullMaybeHandle, kReportExceptions, name, v8::Local< T >::New(), v8::Utils::OpenDirectHandle(), options, v8::internal::parsing::ParseProgram(), v8::internal::ParseInfo::pending_error_handler(), v8::internal::PendingCompilationErrorHandler::PrepareErrors(), v8::PerIsolateData::realm_current_, v8::PerIsolateData::realm_switch_, v8::PerIsolateData::realms_, v8::ShellOptions::repeat_compile, v8::internal::PendingCompilationErrorHandler::ReportErrors(), v8::PersistentBase< T >::Reset(), v8::base::internal::result, v8::internal::script, v8::TryCatch::SetVerbose(), v8::internal::Isolate::StackOverflow(), StoreInCodeCache(), v8::Isolate::TerminateExecution(), v8::MaybeLocal< T >::ToLocal(), v8::anonymous_namespace{d8.cc}::ToSTLString(), and v8::internal::v8_flags.
Referenced by v8::SourceGroup::Execute(), and v8::Worker::ExecuteInThread().
Exit()
static void v8::Shell::Exit (int exit_code) [static]
FetchModuleSource()
MaybeLocal< Object > v8::Shell::FetchModuleSource (v8::Local< v8::Module > origin_module, v8::Local< v8::Context > context, const std::string & file_name, ModuleType module_type) [static], [private]
Definition at line 1217 of file d8.cc.
                                                                    {
  Isolate* isolate = Isolate::GetCurrent();
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(context);
  // Loading modules is only allowed for local absolute paths.
  if (!IsAbsolutePath(module_specifier)) {
    std::string msg =
        "d8: Reading module from " + module_specifier + " is not supported.";
    if (!referrer.IsEmpty()) {
      std::string referrer_specifier =
          module_data->GetModuleSpecifier(referrer);
      msg += "\n imported by " + referrer_specifier;
    }
    ThrowError(isolate,
               v8::String::NewFromUtf8(isolate, msg.c_str()).ToLocalChecked());
    return MaybeLocal<Object>();
  }
  auto file = ReadFileData(isolate, module_specifier.c_str());
  if (!file) {
    std::string msg = "d8: Error reading module from " + module_specifier;
    if (!referrer.IsEmpty()) {
      std::string referrer_specifier =
          module_data->GetModuleSpecifier(referrer);
      msg += "\n imported by " + referrer_specifier;
    }
    ThrowError(isolate,
               v8::String::NewFromUtf8(isolate, msg.c_str()).ToLocalChecked());
    return MaybeLocal<Object>();
  }
  Local<Object> module_source;
  switch (module_type) {
    case ModuleType::kWebAssembly: {
      if (!v8::WasmModuleObject::Compile(
               isolate,
               MemorySpan<const uint8_t>(static_cast<uint8_t*>(file->memory()),
                                         file->size()))
               .ToLocal(&module_source)) {
        return MaybeLocal<Object>();
      }
      break;
    }
    default:
      // https://tc39.es/proposal-source-phase-imports/#table-abstract-methods-of-module-records
      // For Module Records that do not have a source representation,
      // GetModuleSource() must always return a throw completion whose [[Value]]
      // is a ReferenceError.
      ThrowException(
          isolate, v8::Exception::SyntaxError(String::NewFromUtf8Literal(
                       isolate, "Module source can not be imported for type")));
      return MaybeLocal<Object>();
  }
  CHECK(
      module_data->module_source_map
          .insert(std::make_pair(std::make_pair(module_specifier, module_type),
                                 Global<Object>(isolate, module_source)))
          .second);
  return module_source;
}
References CHECK, v8::WasmModuleObject::Compile(), file(), v8::Isolate::GetCurrent(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::anonymous_namespace{d8.cc}::IsAbsolutePath(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::kWebAssembly, v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), ReadFileData(), v8::internal::string, v8::Exception::SyntaxError(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::anonymous_namespace{d8.cc}::ThrowException().
Referenced by DoHostImportModuleDynamically(), and FetchModuleTree().
FetchModuleTree()
MaybeLocal< Module > v8::Shell::FetchModuleTree (v8::Local< v8::Module > origin_module, v8::Local< v8::Context > context, const std::string & file_name, ModuleType module_type) [static], [private]
Definition at line 1284 of file d8.cc.
                                                                  {
  Isolate* isolate = Isolate::GetCurrent();
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(context);
  MaybeLocal<String> source_text;
  if (module_specifier.starts_with(kDataURLPrefix)) {
    source_text = String::NewFromUtf8(
        isolate, module_specifier.c_str() + strlen(kDataURLPrefix));
  } else if (IsAbsolutePath(module_specifier)) {
    source_text = ReadFile(isolate, module_specifier.c_str(), false);
    if (source_text.IsEmpty() && options.fuzzy_module_file_extensions) {
      std::string fallback_file_name = module_specifier + ".js";
      source_text = ReadFile(isolate, fallback_file_name.c_str(), false);
      if (source_text.IsEmpty()) {
        fallback_file_name = module_specifier + ".mjs";
        source_text = ReadFile(isolate, fallback_file_name.c_str());
      }
    }
  } else {
    // Loading modules is only allowed for local absolute paths.
    std::string msg =
        "d8: Reading module from " + module_specifier + " is not supported.";
    if (!referrer.IsEmpty()) {
      std::string referrer_specifier =
          module_data->GetModuleSpecifier(referrer);
      msg += "\n imported by " + referrer_specifier;
    }
    ThrowError(isolate,
               v8::String::NewFromUtf8(isolate, msg.c_str()).ToLocalChecked());
    return MaybeLocal<Module>();
  }
  if (source_text.IsEmpty()) {
    std::string msg = "d8: Error reading module from " + module_specifier;
    if (!referrer.IsEmpty()) {
      std::string referrer_specifier =
          module_data->GetModuleSpecifier(referrer);
      msg += "\n imported by " + referrer_specifier;
    }
    ThrowError(isolate,
               v8::String::NewFromUtf8(isolate, msg.c_str()).ToLocalChecked());
    return MaybeLocal<Module>();
  }
  Local<String> resource_name =
      String::NewFromUtf8(isolate, module_specifier.c_str()).ToLocalChecked();
  ScriptOrigin origin =
      CreateScriptOrigin(isolate, resource_name, ScriptType::kModule);
  Local<Module> module;
  if (module_type == ModuleType::kJavaScript) {
    ScriptCompiler::Source source(source_text.ToLocalChecked(), origin);
    if (!CompileString<Module>(isolate, context, source_text.ToLocalChecked(),
                               origin)
             .ToLocal(&module)) {
      return MaybeLocal<Module>();
    }
  } else if (module_type == ModuleType::kJSON) {
    Local<Value> parsed_json;
    if (!v8::JSON::Parse(context, source_text.ToLocalChecked())
             .ToLocal(&parsed_json)) {
      return MaybeLocal<Module>();
    }
    auto export_names = v8::to_array<Local<String>>(
        {String::NewFromUtf8(isolate, "default").ToLocalChecked()});
    module = v8::Module::CreateSyntheticModule(
        isolate,
        String::NewFromUtf8(isolate, module_specifier.c_str()).ToLocalChecked(),
        export_names, Shell::JSONModuleEvaluationSteps);
    CHECK(module_data->json_module_to_parsed_json_map
              .insert(std::make_pair(Global<Module>(isolate, module),
                                     Global<Value>(isolate, parsed_json)))
              .second);
  } else {
    UNREACHABLE();
  }
  CHECK(
      module_data->module_map
          .insert(std::make_pair(std::make_pair(module_specifier, module_type),
                                 Global<Module>(isolate, module)))
          .second);
  CHECK(module_data->module_to_specifier_map
            .insert(std::make_pair(Global<Module>(isolate, module),
                                   module_specifier))
            .second);
  std::string dir_name = DirName(module_specifier);
  Local<FixedArray> module_requests = module->GetModuleRequests();
  for (int i = 0, length = module_requests->Length(); i < length; ++i) {
    Local<ModuleRequest> module_request =
        module_requests->Get(context, i).As<ModuleRequest>();
    std::string specifier =
        ToSTLString(isolate, module_request->GetSpecifier());
    std::string normalized_specifier =
        NormalizeModuleSpecifier(specifier, dir_name);
    Local<FixedArray> import_attributes = module_request->GetImportAttributes();
    ModuleType request_module_type =
        ModuleEmbedderData::ModuleTypeFromImportSpecifierAndAttributes(
            context, normalized_specifier, import_attributes, true);
    if (request_module_type == ModuleType::kInvalid) {
      ThrowError(isolate, "Invalid module type was asserted");
      return MaybeLocal<Module>();
    }
    if (module_request->GetPhase() == ModuleImportPhase::kSource) {
      if (module_data->module_source_map.count(
              std::make_pair(normalized_specifier, request_module_type))) {
        continue;
      }
      if (FetchModuleSource(module, context, normalized_specifier,
                            request_module_type)
              .IsEmpty()) {
        return MaybeLocal<Module>();
      }
    } else {
      if (module_data->module_map.count(
              std::make_pair(normalized_specifier, request_module_type))) {
        continue;
      }
      if (FetchModuleTree(module, context, normalized_specifier,
                          request_module_type)
              .IsEmpty()) {
        return MaybeLocal<Module>();
      }
    }
  }
  return module;
}
References CHECK, v8::anonymous_namespace{d8.cc}::CreateScriptOrigin(), v8::Module::CreateSyntheticModule(), v8::anonymous_namespace{d8.cc}::DirName(), FetchModuleSource(), v8::ShellOptions::fuzzy_module_file_extensions, v8::Isolate::GetCurrent(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::anonymous_namespace{d8.cc}::IsAbsolutePath(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::MaybeLocal< T >::IsEmpty(), JSONModuleEvaluationSteps(), v8::anonymous_namespace{d8.cc}::kDataURLPrefix, v8::kInvalid, v8::kJavaScript, v8::kJSON, v8::kModule, v8::kSource, v8::internal::length, v8::String::NewFromUtf8(), v8::anonymous_namespace{d8.cc}::NormalizeModuleSpecifier(), options, v8::JSON::Parse(), ReadFile(), v8::internal::string, v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocal(), v8::MaybeLocal< T >::ToLocalChecked(), v8::anonymous_namespace{d8.cc}::ToSTLString(), and UNREACHABLE.
Referenced by DoHostImportModuleDynamically(), and ExecuteModule().
FinishExecuting()
bool v8::Shell::FinishExecuting (Isolate * isolate, const Global< Context > & context) [static]
Definition at line 6306 of file d8.cc.
                                                                            {
  if (!CompleteMessageLoop(isolate)) return false;
  HandleScope scope(isolate);
  // We cannot use a Context::Scope here, as it keeps a local handle to the
  // context and HandleUnhandledPromiseRejections may execute a non-nestable
  // task, e.g. a stackless GC.
  context.Get(isolate)->Enter();
  bool result = HandleUnhandledPromiseRejections(isolate);
  context.Get(isolate)->Exit();
  return result;
}
References v8::PersistentBase< T >::Get(), and v8::base::internal::result.
Referenced by v8::SourceGroup::ExecuteInThread(), and v8::Worker::ExecuteInThread().
FunctionAndArgumentsToString()
bool v8::Shell::FunctionAndArgumentsToString (Local< Function > function, Local< Value > arguments, Local< String > * source, Isolate * isolate) [static]
Definition at line 3242 of file d8.cc.
                                                           {
  Local<Context> context = isolate->GetCurrentContext();
  MaybeLocal<String> maybe_function_string =
      function->FunctionProtoToString(context);
  Local<String> function_string;
  if (!maybe_function_string.ToLocal(&function_string)) {
    ThrowError(isolate, "Failed to convert function to string");
    return false;
  }
  *source = String::NewFromUtf8Literal(isolate, "(");
  *source = String::Concat(isolate, *source, function_string);
  Local<String> middle = String::NewFromUtf8Literal(isolate, ")(");
  *source = String::Concat(isolate, *source, middle);
  if (!arguments.IsEmpty() && !arguments->IsUndefined()) {
    if (!arguments->IsArray()) {
      ThrowError(isolate, "'arguments' must be an array");
      return false;
    }
    Local<String> comma = String::NewFromUtf8Literal(isolate, ",");
    Local<Array> array = arguments.As<Array>();
    for (uint32_t i = 0; i < array->Length(); ++i) {
      if (i > 0) {
        *source = String::Concat(isolate, *source, comma);
      }
      MaybeLocal<Value> maybe_argument = array->Get(context, i);
      Local<Value> argument;
      if (!maybe_argument.ToLocal(&argument)) {
        ThrowError(isolate, "Failed to get argument");
        return false;
      }
      Local<String> argument_string;
      if (!JSON::Stringify(context, argument).ToLocal(&argument_string)) {
        ThrowError(isolate, "Failed to convert argument to string");
        return false;
      }
      *source = String::Concat(isolate, *source, argument_string);
    }
  }
  Local<String> suffix = String::NewFromUtf8Literal(isolate, ")");
  *source = String::Concat(isolate, *source, suffix);
  return true;
}
References v8::Local< T >::As(), v8::String::Concat(), v8::Isolate::GetCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::String::NewFromUtf8Literal(), v8::JSON::Stringify(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::MaybeLocal< T >::ToLocal().
GetCounter()
Counter * v8::Shell::GetCounter (const char * name, bool is_histogram) [static], [private]
Definition at line 3824 of file d8.cc.
                                                              {
  Counter* counter = nullptr;
  {
    base::MutexGuard mutex_guard(&counter_mutex_);
    auto map_entry = counter_map_->find(name);
    if (map_entry != counter_map_->end()) {
      counter = map_entry->second;
    }
  }
  if (counter == nullptr) {
    base::MutexGuard mutex_guard(&counter_mutex_);
    counter = (*counter_map_)[name];
    if (counter == nullptr) {
      counter = counters_->GetNextCounter();
      if (counter == nullptr) {
        // Too many counters.
        return nullptr;
      }
      (*counter_map_)[name] = counter;
      counter->Bind(name, is_histogram);
    }
  }
  DCHECK_EQ(is_histogram, counter->is_histogram());
  return counter;
}
References v8::Counter::Bind(), anonymous_namespace{mksnapshot.cc}::counter_map_, DCHECK_EQ, v8::Counter::is_histogram(), and name.
GetExtrasBindingObject()
void v8::Shell::GetExtrasBindingObject (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3198 of file d8.cc.
                                                 {
  Local<Context> context = info.GetIsolate()->GetCurrentContext();
  info.GetReturnValue().Set(context->GetExtrasBindingObject());
}
References v8::Isolate::GetCurrentContext(), v8::Context::GetExtrasBindingObject(), v8::FunctionCallbackInfo< T >::GetIsolate(), and v8::FunctionCallbackInfo< T >::GetReturnValue().
GetTimestamp()
double v8::Shell::GetTimestamp () [static]
Definition at line 2123 of file d8.cc.
                           {
  if (i::v8_flags.verify_predictable) {
    return g_platform->MonotonicallyIncreasingTime();
  } else {
    base::TimeDelta delta = base::TimeTicks::Now() - kInitialTicks;
    return delta.InMillisecondsF();
  }
}
References v8::anonymous_namespace{d8.cc}::g_platform, v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeTicks::Now(), and v8::internal::v8_flags.
GetTracingTimestampFromPerformanceTimestamp()
uint64_t v8::Shell::GetTracingTimestampFromPerformanceTimestamp (double performance_timestamp) [static]
Definition at line 2131 of file d8.cc.
                                  {
  // Don't use this in --verify-predictable mode, predictable timestamps don't
  // work well with tracing.
  DCHECK(!i::v8_flags.verify_predictable);
  base::TimeDelta delta =
      base::TimeDelta::FromMillisecondsD(performance_timestamp);
  // See TracingController::CurrentTimestampMicroseconds().
  int64_t internal_value = (delta + kInitialTicks).ToInternalValue();
  DCHECK_GE(internal_value, 0);
  return internal_value;
}
References DCHECK, DCHECK_GE, v8::base::TimeDelta::FromMillisecondsD(), and v8::internal::v8_flags.
HandleUnhandledPromiseRejections()
bool v8::Shell::HandleUnhandledPromiseRejections (Isolate * isolate) [static]
Definition at line 6323 of file d8.cc.
                                                             {
  if (options.ignore_unhandled_promises) return true;
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int count = data->HandleUnhandledPromiseRejections();
  Shell::unhandled_promise_rejections_.store(
      Shell::unhandled_promise_rejections_.load() + count);
  return count == 0;
}
References v8::PerIsolateData::Get(), v8::PerIsolateData::HandleUnhandledPromiseRejections(), and unhandled_promise_rejections_.
HasOnProfileEndListener()
bool v8::Shell::HasOnProfileEndListener (Isolate * isolate) [static]
Definition at line 2889 of file d8.cc.
                                                    {
  base::MutexGuard lock_guard(&profiler_end_callback_lock_);
  return profiler_end_callback_.find(isolate) != profiler_end_callback_.end();
}
Referenced by v8::D8Console::ProfileEnd().
HostCreateShadowRealmContext()
MaybeLocal< Context > v8::Shell::HostCreateShadowRealmContext (Local< Context > initiator_context) [static]
Definition at line 1583 of file d8.cc.
                                      {
  Local<Context> context = v8::Context::New(Isolate::GetCurrent());
  std::shared_ptr<ModuleEmbedderData> shadow_realm_data =
      InitializeModuleEmbedderData(context);
  std::shared_ptr<ModuleEmbedderData> initiator_data =
      GetModuleDataFromContext(initiator_context);
  // ShadowRealms are synchronously accessible and are always in the same origin
  // as the initiator context.
  context->SetSecurityToken(initiator_context->GetSecurityToken());
  shadow_realm_data->origin = initiator_data->origin;
  return context;
}
References v8::Isolate::GetCurrent(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::Context::GetSecurityToken(), v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData(), v8::Context::New(), and v8::Context::SetSecurityToken().
Referenced by Initialize().
HostImportModuleDynamically()
MaybeLocal< Promise > v8::Shell::HostImportModuleDynamically (Local< Context > context, Local< Data > host_defined_options, Local< Value > resource_name, Local< String > specifier, Local< FixedArray > import_attributes) [static]
Definition at line 1529 of file d8.cc.
                                         {
  return HostImportModuleWithPhaseDynamically(
      context, host_defined_options, resource_name, specifier,
      ModuleImportPhase::kEvaluation, import_attributes);
}
References HostImportModuleWithPhaseDynamically(), and v8::kEvaluation.
Referenced by Initialize().
HostImportModuleWithPhaseDynamically()
MaybeLocal< Promise > v8::Shell::HostImportModuleWithPhaseDynamically (Local< Context > context, Local< Data > host_defined_options, Local< Value > resource_name, Local< String > specifier, ModuleImportPhase phase, Local< FixedArray > import_attributes) [static]
Definition at line 1538 of file d8.cc.
                                                                  {
  Isolate* isolate = Isolate::GetCurrent();
  MaybeLocal<Promise::Resolver> maybe_resolver =
      Promise::Resolver::New(context);
  Local<Promise::Resolver> resolver;
  if (!maybe_resolver.ToLocal(&resolver)) return MaybeLocal<Promise>();
  if (!resource_name->IsNull() &&
      !IsValidHostDefinedOptions(context, host_defined_options,
                                 resource_name)) {
    resolver
        ->Reject(context, v8::Exception::TypeError(String::NewFromUtf8Literal(
                              isolate, "Invalid host defined options")))
        .ToChecked();
  } else {
    DynamicImportData* data =
        new DynamicImportData(isolate, context, resource_name, specifier, phase,
                              import_attributes, resolver);
    PerIsolateData::Get(isolate)->AddDynamicImportData(data);
    isolate->EnqueueMicrotask(Shell::DoHostImportModuleDynamically, data);
  }
  return resolver->GetPromise();
}
References v8::PerIsolateData::AddDynamicImportData(), DoHostImportModuleDynamically(), v8::Isolate::EnqueueMicrotask(), v8::PerIsolateData::Get(), v8::Isolate::GetCurrent(), v8::anonymous_namespace{d8.cc}::IsValidHostDefinedOptions(), v8::Promise::Resolver::New(), v8::String::NewFromUtf8Literal(), v8::MaybeLocal< T >::ToLocal(), and v8::Exception::TypeError().
Referenced by HostImportModuleDynamically(), and Initialize().
HostInitializeImportMetaObject()
void v8::Shell::HostInitializeImportMetaObject (Local< Context > context, Local< Module > module, Local< Object > meta) [static]
Definition at line 1566 of file d8.cc.
                                                               {
  Isolate* isolate = Isolate::GetCurrent();
  HandleScope handle_scope(isolate);
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(context);
  std::string specifier = module_data->GetModuleSpecifier(module);
  Local<String> url_key =
      String::NewFromUtf8Literal(isolate, "url", NewStringType::kInternalized);
  Local<String> url =
      String::NewFromUtf8(isolate, specifier.c_str()).ToLocalChecked();
  meta->CreateDataProperty(context, url_key, url).ToChecked();
}
References v8::Object::CreateDataProperty(), v8::Isolate::GetCurrent(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::kInternalized, v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), and v8::internal::string.
Referenced by Initialize().
Initialize()
void v8::Shell::Initialize (Isolate * isolate, D8Console * console, bool isOnMainThread = true) [static]
Definition at line 4327 of file d8.cc.
                                            {
  isolate->SetPromiseRejectCallback(PromiseRejectCallback);
  isolate->SetWasmAsyncResolvePromiseCallback(
      D8WasmAsyncResolvePromiseCallback);
  if (isOnMainThread) {
    // Set up counters
    if (i::v8_flags.map_counters[0] != '\0') {
      MapCounters(isolate, i::v8_flags.map_counters);
    }
    // Disable default message reporting.
    isolate->AddMessageListenerWithErrorLevel(
        PrintMessageCallback,
        v8::Isolate::kMessageError | v8::Isolate::kMessageWarning |
            v8::Isolate::kMessageInfo | v8::Isolate::kMessageDebug |
            v8::Isolate::kMessageLog);
  }
  isolate->SetHostImportModuleDynamicallyCallback(
      Shell::HostImportModuleDynamically);
  isolate->SetHostImportModuleWithPhaseDynamicallyCallback(
      Shell::HostImportModuleWithPhaseDynamically);
  isolate->SetHostInitializeImportMetaObjectCallback(
      Shell::HostInitializeImportMetaObject);
  isolate->SetHostCreateShadowRealmContextCallback(
      Shell::HostCreateShadowRealmContext);
  debug::SetConsoleDelegate(isolate, console);
}
References v8::Isolate::AddMessageListenerWithErrorLevel(), v8::anonymous_namespace{d8.cc}::D8WasmAsyncResolvePromiseCallback(), HostCreateShadowRealmContext(), HostImportModuleDynamically(), HostImportModuleWithPhaseDynamically(), HostInitializeImportMetaObject(), v8::Isolate::kMessageDebug, v8::Isolate::kMessageError, v8::Isolate::kMessageInfo, v8::Isolate::kMessageLog, v8::Isolate::kMessageWarning, v8::PrintMessageCallback(), v8::debug::SetConsoleDelegate(), v8::Isolate::SetHostCreateShadowRealmContextCallback(), v8::Isolate::SetHostImportModuleDynamicallyCallback(), v8::Isolate::SetHostImportModuleWithPhaseDynamicallyCallback(), v8::Isolate::SetHostInitializeImportMetaObjectCallback(), v8::Isolate::SetPromiseRejectCallback(), v8::Isolate::SetWasmAsyncResolvePromiseCallback(), and v8::internal::v8_flags.
Referenced by v8::SourceGroup::ExecuteInThread(), and v8::Worker::ExecuteInThread().
InstallConditionalFeatures()
void v8::Shell::InstallConditionalFeatures (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2725 of file d8.cc.
                                                 {
  Isolate* isolate = info.GetIsolate();
  isolate->InstallConditionalFeatures(isolate->GetCurrentContext());
}
References v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), and v8::Isolate::InstallConditionalFeatures().
Referenced by CreateD8Template().
is_valid_fuzz_script()
static bool v8::Shell::is_valid_fuzz_script () [inline], [static]
Definition at line 776 of file d8.h.
{ return valid_fuzz_script_.load(); }
References valid_fuzz_script_.
JSONModuleEvaluationSteps()
MaybeLocal< Value > v8::Shell::JSONModuleEvaluationSteps (Local< Context > context, Local< Module > module) [static], [private]
Definition at line 1425 of file d8.cc.
                                                                         {
  Isolate* isolate = Isolate::GetCurrent();
  std::shared_ptr<ModuleEmbedderData> module_data =
      GetModuleDataFromContext(context);
  Local<Value> json_value = module_data->GetJsonModuleValue(module);
  TryCatch try_catch(isolate);
  Maybe<bool> result = module->SetSyntheticModuleExport(
      isolate,
      String::NewFromUtf8Literal(isolate, "default",
                                 NewStringType::kInternalized),
      json_value);
  // Setting the default export should never fail.
  CHECK(!try_catch.HasCaught());
  CHECK(!result.IsNothing() && result.FromJust());
  Local<Promise::Resolver> resolver =
      Promise::Resolver::New(context).ToLocalChecked();
  resolver->Resolve(context, Undefined(isolate)).ToChecked();
  return resolver->GetPromise();
}
References CHECK, v8::Isolate::GetCurrent(), v8::anonymous_namespace{d8.cc}::GetModuleDataFromContext(), v8::TryCatch::HasCaught(), v8::kInternalized, v8::Promise::Resolver::New(), v8::String::NewFromUtf8Literal(), v8::base::internal::result, and v8::Undefined().
Referenced by FetchModuleTree().
LoadJSON()
bool v8::Shell::LoadJSON (Isolate * isolate, const char * file_name) [static]
Definition at line 1897 of file d8.cc.
                                                            {
  HandleScope handle_scope(isolate);
  PerIsolateData* isolate_data = PerIsolateData::Get(isolate);
  Local<Context> realm =
      isolate_data->realms_[isolate_data->realm_current_].Get(isolate);
  Context::Scope context_scope(realm);
  TryCatch try_catch(isolate);
  std::string absolute_path = NormalizePath(file_name, GetWorkingDirectory());
  int length = 0;
  std::unique_ptr<char[]> data(ReadChars(absolute_path.c_str(), &length));
  if (length == 0) {
    printf("Error reading '%s'\n", file_name);
    base::OS::ExitProcess(1);
  }
  std::stringstream stream(data.get());
  std::string line;
  while (std::getline(stream, line, '\n')) {
    for (int r = 0; r < DeserializationRunCount(); ++r) {
      Local<String> source =
          String::NewFromUtf8(isolate, line.c_str()).ToLocalChecked();
      MaybeLocal<Value> maybe_value = JSON::Parse(realm, source);
      Local<Value> value;
      if (!maybe_value.ToLocal(&value)) {
        DCHECK(try_catch.HasCaught());
        ReportException(isolate, try_catch);
        return false;
      }
    }
  }
  return true;
}
References DCHECK, DeserializationRunCount(), v8::base::OS::ExitProcess(), v8::PerIsolateData::Get(), v8::anonymous_namespace{d8.cc}::GetWorkingDirectory(), v8::TryCatch::HasCaught(), v8::internal::length, v8::String::NewFromUtf8(), v8::anonymous_namespace{d8.cc}::NormalizePath(), v8::JSON::Parse(), ReadChars(), v8::PerIsolateData::realm_current_, v8::PerIsolateData::realms_, ReportException(), v8::internal::string, v8::MaybeLocal< T >::ToLocal(), and v8::internal::value.
Referenced by v8::SourceGroup::Execute().
LogGetAndStop()
void v8::Shell::LogGetAndStop (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2590 of file d8.cc.
                                                                     {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  HandleScope handle_scope(isolate);
  std::string file_name = i_isolate->v8_file_logger()->file_name();
  if (!i::LogFile::IsLoggingToTemporaryFile(file_name)) {
    ThrowError(isolate, "Only capturing from temporary files is supported.");
    return;
  }
  if (!i_isolate->v8_file_logger()->is_logging()) {
    ThrowError(isolate, "Logging not enabled.");
    return;
  }
  std::string raw_log;
  FILE* log_file = i_isolate->v8_file_logger()->TearDownAndGetLogFile();
  if (!log_file) {
    ThrowError(isolate, "Log file does not exist.");
    return;
  }
  bool exists = false;
  raw_log = i::ReadFile(log_file, &exists, true);
  base::Fclose(log_file);
  if (!exists) {
    ThrowError(isolate, "Unable to read log file.");
    return;
  }
  Local<String> result =
      String::NewFromUtf8(isolate, raw_log.c_str(), NewStringType::kNormal,
                          static_cast<int>(raw_log.size()))
          .ToLocalChecked();
  info.GetReturnValue().Set(result);
}
References DCHECK, v8::base::Fclose(), v8::internal::V8FileLogger::file_name(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::V8FileLogger::is_logging(), v8::internal::LogFile::IsLoggingToTemporaryFile(), v8::kNormal, v8::String::NewFromUtf8(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadFile(), v8::base::internal::result, v8::internal::string, v8::internal::V8FileLogger::TearDownAndGetLogFile(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::internal::Isolate::v8_file_logger(), and v8::internal::ValidateCallbackInfo().
LookupCodeCache()
ScriptCompiler::CachedData * v8::Shell::LookupCodeCache (Isolate * isolate, Local< Value > name) [static], [private]
Definition at line 561 of file d8.cc.
                                                                        {
  i::ParkedMutexGuard lock_guard(
      reinterpret_cast<i::Isolate*>(isolate)->main_thread_local_isolate(),
      cached_code_mutex_.Pointer());
  CHECK(source->IsString());
  v8::String::Utf8Value key(isolate, source);
  DCHECK(*key);
  auto entry = cached_code_map_.find(*key);
  if (entry != cached_code_map_.end() && entry->second) {
    int length = entry->second->length;
    uint8_t* cache = new uint8_t[length];
    memcpy(cache, entry->second->data, length);
    ScriptCompiler::CachedData* cached_data = new ScriptCompiler::CachedData(
        cache, length, ScriptCompiler::CachedData::BufferOwned);
    return cached_data;
  }
  return nullptr;
}
References v8::ScriptCompiler::CachedData::BufferOwned, cached_code_map_, cached_code_mutex_, CHECK, DCHECK, v8::internal::key, v8::internal::length, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by CompileString().
LookupCounter()
int * v8::Shell::LookupCounter (const char * name) [static]
Definition at line 3854 of file d8.cc.
                                          {
  Counter* counter = GetCounter(name, false);
  return counter ? counter->ptr() : nullptr;
}
References name, and v8::Counter::ptr().
Main()
int v8::Shell::Main (int argc, char * argv[]) [static]
Definition at line 6671 of file d8.cc.
                                      {
#if defined(V8_ENABLE_PARTITION_ALLOC)
#if PA_BUILDFLAG(USE_PARTITION_ALLOC_AS_MALLOC)
  allocator_shim::ConfigurePartitionsForTesting();
  allocator_shim::internal::PartitionAllocMalloc::Allocator()
      ->EnableThreadCacheIfSupported();
#endif // PA_BUILDFLAG(USE_PARTITION_ALLOC_AS_MALLOC)
#endif
  v8::base::EnsureConsoleOutput();
  if (!SetOptions(argc, argv)) return 1;
  if (!i::v8_flags.fuzzing) d8_install_sigterm_handler();
  v8::base::FlushDenormalsScope denormals_scope(options.flush_denormals);
  v8::V8::InitializeICUDefaultLocation(argv[0], options.icu_data_file);
#ifdef V8_OS_DARWIN
  if (options.apply_priority) {
    struct task_category_policy category = {.role =
                                                TASK_FOREGROUND_APPLICATION};
    task_policy_set(mach_task_self(), TASK_CATEGORY_POLICY,
                    (task_policy_t)&category, TASK_CATEGORY_POLICY_COUNT);
    pthread_set_qos_class_self_np(QOS_CLASS_USER_INTERACTIVE, 0);
  }
#endif
#ifdef V8_INTL_SUPPORT
  if (options.icu_locale != nullptr) {
    icu::Locale locale(options.icu_locale);
    UErrorCode error_code = U_ZERO_ERROR;
    icu::Locale::setDefault(locale, error_code);
  }
#endif // V8_INTL_SUPPORT
  v8::platform::InProcessStackDumping in_process_stack_dumping =
      options.disable_in_process_stack_traces
          ? v8::platform::InProcessStackDumping::kDisabled
          : v8::platform::InProcessStackDumping::kEnabled;
  std::ofstream trace_file;
  std::unique_ptr<platform::tracing::TracingController> tracing;
  if (options.trace_enabled && !i::v8_flags.verify_predictable) {
    tracing = std::make_unique<platform::tracing::TracingController>();
    if (!options.enable_etw_stack_walking) {
      const char* trace_path =
          options.trace_path ? options.trace_path : "v8_trace.json";
      trace_file.open(trace_path);
      if (!trace_file.good()) {
        printf("Cannot open trace file '%s' for writing: %s.\n", trace_path,
               strerror(errno));
        return 1;
      }
    }
#ifdef V8_USE_PERFETTO
    // Set up the in-process backend that the tracing controller will connect
    // to.
    perfetto::TracingInitArgs init_args;
    init_args.backends = perfetto::BackendType::kInProcessBackend;
    perfetto::Tracing::Initialize(init_args);
    tracing->InitializeForPerfetto(&trace_file);
#else
    platform::tracing::TraceBuffer* trace_buffer = nullptr;
#if defined(V8_ENABLE_SYSTEM_INSTRUMENTATION)
    if (options.enable_system_instrumentation) {
      trace_buffer =
          platform::tracing::TraceBuffer::CreateTraceBufferRingBuffer(
              platform::tracing::TraceBuffer::kRingBufferChunks,
              platform::tracing::TraceWriter::
                  CreateSystemInstrumentationTraceWriter());
    }
#endif // V8_ENABLE_SYSTEM_INSTRUMENTATION
    if (!trace_buffer) {
      trace_buffer =
          platform::tracing::TraceBuffer::CreateTraceBufferRingBuffer(
              platform::tracing::TraceBuffer::kRingBufferChunks,
              platform::tracing::TraceWriter::CreateJSONTraceWriter(
                  trace_file));
    }
    tracing->Initialize(trace_buffer);
#endif // V8_USE_PERFETTO
  }
  v8::SandboxHardwareSupport::InitializeBeforeThreadCreation();
  platform::tracing::TracingController* tracing_controller = tracing.get();
  if (i::v8_flags.single_threaded) {
    g_platform = v8::platform::NewSingleThreadedDefaultPlatform(
        v8::platform::IdleTaskSupport::kEnabled, in_process_stack_dumping,
        std::move(tracing));
  } else {
    g_platform = v8::platform::NewDefaultPlatform(
        options.thread_pool_size, v8::platform::IdleTaskSupport::kEnabled,
        in_process_stack_dumping, std::move(tracing),
        options.apply_priority ? v8::platform::PriorityMode::kApply
                               : v8::platform::PriorityMode::kDontApply);
  }
  g_default_platform = g_platform.get();
  if (i::v8_flags.predictable) {
    g_platform = MakePredictablePlatform(std::move(g_platform));
  }
  if (options.stress_delay_tasks) {
    int64_t random_seed = i::v8_flags.fuzzer_random_seed;
    if (!random_seed) random_seed = i::v8_flags.random_seed;
    // If random_seed is still 0 here, the {DelayedTasksPlatform} will choose a
    // random seed.
    g_platform = MakeDelayedTasksPlatform(std::move(g_platform), random_seed);
  }
  if (i::v8_flags.trace_turbo_cfg_file == nullptr) {
    V8::SetFlagsFromString("--trace-turbo-cfg-file=turbo.cfg");
  }
  if (i::v8_flags.redirect_code_traces_to == nullptr) {
    V8::SetFlagsFromString("--redirect-code-traces-to=code.asm");
  }
  v8::V8::InitializePlatform(g_platform.get());
  // Disable flag freezing if we are producing a code cache, because for that we
  // modify v8_flags.hash_seed (below).
  if (options.code_cache_options != ShellOptions::kNoProduceCache) {
    i::v8_flags.freeze_flags_after_init = false;
  }
  v8::V8::Initialize();
  if (options.snapshot_blob) {
    v8::V8::InitializeExternalStartupDataFromFile(options.snapshot_blob);
  } else {
    v8::V8::InitializeExternalStartupData(argv[0]);
  }
  int result = 0;
  Isolate::CreateParams create_params;
  ShellArrayBufferAllocator shell_array_buffer_allocator;
  MockArrayBufferAllocator mock_arraybuffer_allocator;
  const size_t memory_limit =
      options.mock_arraybuffer_allocator_limit * options.num_isolates;
  MockArrayBufferAllocatiorWithLimit mock_arraybuffer_allocator_with_limit(
      memory_limit >= options.mock_arraybuffer_allocator_limit
          ? memory_limit
          : std::numeric_limits<size_t>::max());
#ifdef V8_OS_LINUX
  MultiMappedAllocator multi_mapped_mock_allocator;
#endif // V8_OS_LINUX
  if (options.mock_arraybuffer_allocator) {
    if (memory_limit) {
      Shell::array_buffer_allocator = &mock_arraybuffer_allocator_with_limit;
    } else {
      Shell::array_buffer_allocator = &mock_arraybuffer_allocator;
    }
#ifdef V8_OS_LINUX
  } else if (options.multi_mapped_mock_allocator) {
    Shell::array_buffer_allocator = &multi_mapped_mock_allocator;
#endif // V8_OS_LINUX
  } else {
    Shell::array_buffer_allocator = &shell_array_buffer_allocator;
  }
  create_params.array_buffer_allocator = Shell::array_buffer_allocator;
#ifdef ENABLE_VTUNE_JIT_INTERFACE
  if (i::v8_flags.enable_vtunejit) {
    create_params.code_event_handler = vTune::GetVtuneCodeEventHandler();
  }
#endif // ENABLE_VTUNE_JIT_INTERFACE
  create_params.constraints.ConfigureDefaults(
      base::SysInfo::AmountOfPhysicalMemory(),
      base::SysInfo::AmountOfVirtualMemory());
  Shell::counter_map_ = new CounterMap();
  if (options.dump_counters || options.dump_counters_nvp ||
      i::v8_flags.trace_number_string_cache ||
      i::TracingFlags::is_gc_stats_enabled()) {
    create_params.counter_lookup_callback = LookupCounter;
    create_params.create_histogram_callback = CreateHistogram;
    create_params.add_histogram_sample_callback = AddHistogramSample;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (V8_TRAP_HANDLER_SUPPORTED && options.wasm_trap_handler) {
    constexpr bool kUseDefaultTrapHandler = true;
    if (!v8::V8::EnableWebAssemblyTrapHandler(kUseDefaultTrapHandler)) {
      FATAL("Could not register trap handler");
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (i::v8_flags.experimental) {
    // This message is printed to stderr so that it is also visible in
    // Clusterfuzz reports.
    fprintf(stderr,
            "V8 is running with experimental features enabled. Stability and "
            "security will suffer.\n");
  }
  Isolate* isolate = Isolate::New(create_params);
#ifdef V8_FUZZILLI
  // Let the parent process (Fuzzilli) know we are ready.
  if (options.fuzzilli_enable_builtins_coverage) {
    cov_init_builtins_edges(static_cast<uint32_t>(
        i::BasicBlockProfiler::Get()
            ->GetCoverageBitmap(reinterpret_cast<i::Isolate*>(isolate))
            .size()));
  }
  char helo[] = "HELO";
  if (write(REPRL_CWFD, helo, 4) != 4 || read(REPRL_CRFD, helo, 4) != 4) {
    fuzzilli_reprl = false;
  }
  if (memcmp(helo, "HELO", 4) != 0) {
    FATAL("REPRL: Invalid response from parent");
  }
#endif // V8_FUZZILLI
  {
    Isolate::Scope scope(isolate);
    D8Console console(isolate);
    Initialize(isolate, &console);
    PerIsolateData data(isolate);
    // Fuzzilli REPRL = read-eval-print-loop
    do {
#ifdef V8_FUZZILLI
      if (fuzzilli_reprl) {
        unsigned action = 0;
        ssize_t nread = read(REPRL_CRFD, &action, 4);
        if (nread != 4 || action != 'cexe') {
          FATAL("REPRL: Unknown action: %u", action);
        }
      }
#endif // V8_FUZZILLI
      result = 0;
      if (options.trace_enabled) {
        platform::tracing::TraceConfig* trace_config;
        if (options.trace_config) {
          int size = 0;
          char* trace_config_json_str = ReadChars(options.trace_config, &size);
          trace_config = tracing::CreateTraceConfigFromJSON(
              isolate, trace_config_json_str);
          delete[] trace_config_json_str;
        } else {
          trace_config =
              platform::tracing::TraceConfig::CreateDefaultTraceConfig();
          if (options.enable_system_instrumentation) {
            trace_config->AddIncludedCategory("disabled-by-default-v8.compile");
          }
        }
        tracing_controller->StartTracing(trace_config);
      }
      CpuProfiler* cpu_profiler;
      if (options.cpu_profiler) {
        cpu_profiler = CpuProfiler::New(isolate);
        cpu_profiler->StartProfiling(String::Empty(isolate),
                                     CpuProfilingOptions{});
      }
      if (i::v8_flags.stress_runs > 0) {
        options.stress_runs = i::v8_flags.stress_runs;
        for (int i = 0; i < options.stress_runs && result == 0; i++) {
          printf("============ Run %d/%d ============\n", i + 1,
                 options.stress_runs.get());
          bool last_run = i == options.stress_runs - 1;
          result = RunMain(isolate, last_run);
        }
      } else if (options.code_cache_options != ShellOptions::kNoProduceCache) {
        // Park the main thread here in case the new isolate wants to perform
        // a shared GC to prevent a deadlock.
        reinterpret_cast<i::Isolate*>(isolate)
            ->main_thread_local_isolate()
            ->ExecuteMainThreadWhileParked([&result]() {
              printf("============ Run: Produce code cache ============\n");
              // First run to produce the cache
              Isolate::CreateParams create_params2;
              create_params2.array_buffer_allocator =
                  Shell::array_buffer_allocator;
              // Use a different hash seed.
              i::v8_flags.hash_seed = i::v8_flags.hash_seed ^ 1337;
              Isolate* isolate2 = Isolate::New(create_params2);
              // Restore old hash seed.
              i::v8_flags.hash_seed = i::v8_flags.hash_seed ^ 1337;
              {
                Isolate::Scope isolate_scope(isolate2);
                D8Console console2(isolate2);
                Initialize(isolate2, &console2);
                PerIsolateData data2(isolate2);
                result = RunMain(isolate2, false);
                ResetOnProfileEndListener(isolate2);
              }
              // D8WasmAsyncResolvePromiseTask may be still in the runner at
              // this point. We need to terminate the task runners before the
              // Isolate to avoid retaining stray tasks with v8::Global pointing
              // into a reclaimed Isolate.
              platform::NotifyIsolateShutdown(g_default_platform, isolate2);
              isolate2->Dispose();
            });
        // Change the options to consume cache
        DCHECK(options.compile_options == v8::ScriptCompiler::kEagerCompile ||
               options.compile_options ==
                   v8::ScriptCompiler::kNoCompileOptions);
        options.compile_options.Overwrite(
            v8::ScriptCompiler::kConsumeCodeCache);
        options.code_cache_options.Overwrite(ShellOptions::kNoProduceCache);
        printf("============ Run: Consume code cache ============\n");
        // Second run to consume the cache in current isolate
        result = RunMain(isolate, true);
        options.compile_options.Overwrite(
            v8::ScriptCompiler::kNoCompileOptions);
      } else {
        bool last_run = true;
        result = RunMain(isolate, last_run);
      }
      // Run interactive shell if explicitly requested or if no script has been
      // executed, but never on --test
      if (use_interactive_shell()) {
        RunShell(isolate);
      }
      if (i::v8_flags.trace_ignition_dispatches_output_file != nullptr) {
        WriteIgnitionDispatchCountersFile(isolate);
      }
      if (options.cpu_profiler) {
        CpuProfile* profile =
            cpu_profiler->StopProfiling(String::Empty(isolate));
        if (options.cpu_profiler_print) {
          const internal::ProfileNode* root =
              reinterpret_cast<const internal::ProfileNode*>(
                  profile->GetTopDownRoot());
          root->Print(0);
        }
        profile->Delete();
        cpu_profiler->Dispose();
      }
#ifdef V8_FUZZILLI
      // Send result to parent (fuzzilli) and reset edge guards.
      if (fuzzilli_reprl) {
        int status = result << 8;
        std::vector<bool> bitmap;
        if (options.fuzzilli_enable_builtins_coverage) {
          bitmap = i::BasicBlockProfiler::Get()->GetCoverageBitmap(
              reinterpret_cast<i::Isolate*>(isolate));
          cov_update_builtins_basic_block_coverage(bitmap);
        }
        if (options.fuzzilli_coverage_statistics) {
          int tot = 0;
          for (bool b : bitmap) {
            if (b) tot++;
          }
          static int iteration_counter = 0;
          std::ofstream covlog("covlog.txt", std::ios::app);
          covlog << iteration_counter << "\t" << tot << "\t"
                 << sanitizer_cov_count_discovered_edges() << "\t"
                 << bitmap.size() << std::endl;
          iteration_counter++;
        }
        // In REPRL mode, stdout and stderr can be regular files, so they need
        // to be flushed after every execution
        fflush(stdout);
        fflush(stderr);
        CHECK_EQ(write(REPRL_CWFD, &status, 4), 4);
        sanitizer_cov_reset_edgeguards();
        if (options.fuzzilli_enable_builtins_coverage) {
          i::BasicBlockProfiler::Get()->ResetCounts(
              reinterpret_cast<i::Isolate*>(isolate));
        }
      }
#endif // V8_FUZZILLI
    } while (fuzzilli_reprl);
    // Shut down contexts and collect garbage.
    cached_code_map_.clear();
    evaluation_context_.Reset();
    stringify_function_.Reset();
    ResetOnProfileEndListener(isolate);
    CollectGarbage(isolate);
  }
  OnExit(isolate, true);
  // Delete the platform explicitly here to write the tracing output to the
  // tracing file.
  if (options.trace_enabled) {
    tracing_controller->StopTracing();
  }
  g_platform.reset();
#ifdef V8_TARGET_OS_WIN
  // We need to free the allocated utf8 filenames in
  // PreProcessUnicodeFilenameArg.
  for (char* utf8_str : utf8_filenames) {
    delete[] utf8_str;
  }
  utf8_filenames.clear();
#endif
  return result;
}
References v8::Isolate::CreateParams::add_histogram_sample_callback, v8::platform::tracing::TraceConfig::AddIncludedCategory(), v8::base::SysInfo::AmountOfPhysicalMemory(), v8::base::SysInfo::AmountOfVirtualMemory(), v8::Isolate::CreateParams::array_buffer_allocator, array_buffer_allocator, CHECK_EQ, v8::Isolate::CreateParams::code_event_handler, v8::ResourceConstraints::ConfigureDefaults(), v8::Isolate::CreateParams::constraints, v8::Isolate::CreateParams::counter_lookup_callback, counter_map_, cov_init_builtins_edges(), cov_update_builtins_basic_block_coverage(), v8::Isolate::CreateParams::create_histogram_callback, v8::platform::tracing::TraceConfig::CreateDefaultTraceConfig(), v8::platform::tracing::TraceWriter::CreateJSONTraceWriter(), v8::platform::tracing::TraceBuffer::CreateTraceBufferRingBuffer(), v8::tracing::CreateTraceConfigFromJSON(), v8::anonymous_namespace{d8.cc}::d8_install_sigterm_handler(), DCHECK, v8::CpuProfile::Delete(), v8::Isolate::Dispose(), v8::CpuProfiler::Dispose(), v8::String::Empty(), v8::V8::EnableWebAssemblyTrapHandler(), v8::base::EnsureConsoleOutput(), FATAL, v8::anonymous_namespace{d8.cc}::fuzzilli_reprl, v8::anonymous_namespace{d8.cc}::g_default_platform, v8::anonymous_namespace{d8.cc}::g_platform, v8::internal::BasicBlockProfiler::Get(), v8::internal::BasicBlockProfiler::GetCoverageBitmap(), v8::CpuProfile::GetTopDownRoot(), v8::V8::Initialize(), v8::SandboxHardwareSupport::InitializeBeforeThreadCreation(), v8::V8::InitializeExternalStartupData(), v8::V8::InitializeExternalStartupDataFromFile(), v8::V8::InitializeICUDefaultLocation(), v8::V8::InitializePlatform(), v8::internal::TracingFlags::is_gc_stats_enabled(), v8::platform::kApply, v8::ScriptCompiler::kConsumeCodeCache, v8::platform::kDisabled, v8::platform::kDontApply, v8::ScriptCompiler::kEagerCompile, v8::platform::kEnabled, v8::ScriptCompiler::kNoCompileOptions, v8::ShellOptions::kNoProduceCache, v8::platform::tracing::TraceBuffer::kRingBufferChunks, v8::MakeDelayedTasksPlatform(), v8::MakePredictablePlatform(), v8::Isolate::New(), v8::CpuProfiler::New(), v8::platform::NewDefaultPlatform(), v8::platform::NewSingleThreadedDefaultPlatform(), v8::platform::NotifyIsolateShutdown(), v8::internal::ProfileNode::Print(), REPRL_CRFD, REPRL_CWFD, v8::internal::BasicBlockProfiler::ResetCounts(), v8::base::internal::result, sanitizer_cov_count_discovered_edges(), sanitizer_cov_reset_edgeguards(), v8::V8::SetFlagsFromString(), size(), v8::CpuProfiler::StartProfiling(), v8::platform::tracing::TracingController::StartTracing(), v8::internal::status, v8::CpuProfiler::StopProfiling(), v8::platform::tracing::TracingController::StopTracing(), v8::internal::v8_flags, and V8_TRAP_HANDLER_SUPPORTED.
Referenced by main().
MakeDirectory()
void v8::Shell::MakeDirectory (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 569 of file d8-posix.cc.
                                                                     {
  DCHECK(i::ValidateCallbackInfo(info));
  mode_t mask = 0777;
  if (info.Length() == 2) {
    if (info[1]->IsNumber()) {
      mask = info[1]
                 ->Int32Value(info.GetIsolate()->GetCurrentContext())
                 .FromJust();
    } else {
      info.GetIsolate()->ThrowError("mkdirp() second argument must be numeric");
      return;
    }
  } else if (info.Length() != 1) {
    info.GetIsolate()->ThrowError("mkdirp() takes one or two arguments");
    return;
  }
  String::Utf8Value directory(info.GetIsolate(), info[0]);
  if (*directory == nullptr) {
    info.GetIsolate()->ThrowError(
        "os.mkdirp(): String conversion of argument failed.");
    return;
  }
  mkdirp(info.GetIsolate(), *directory, mask);
}
References DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::IsNumber(), v8::FunctionCallbackInfo< T >::Length(), v8::mkdirp(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by AddOSMethods().
MapCounters()
void v8::Shell::MapCounters (v8::Isolate * isolate, const char * name) [static]
Definition at line 3809 of file d8.cc.
                                                            {
  counters_file_ = base::OS::MemoryMappedFile::create(
      name, sizeof(CounterCollection), &local_counters_);
  void* memory =
      (counters_file_ == nullptr) ? nullptr : counters_file_->memory();
  if (memory == nullptr) {
    printf("Could not map counters file %s\n", name);
    base::OS::ExitProcess(1);
  }
  counters_ = static_cast<CounterCollection*>(memory);
  isolate->SetCounterFunction(LookupCounter);
  isolate->SetCreateHistogramFunction(CreateHistogram);
  isolate->SetAddHistogramSampleFunction(AddHistogramSample);
}
References v8::base::OS::MemoryMappedFile::create(), v8::base::OS::ExitProcess(), name, v8::Isolate::SetAddHistogramSampleFunction(), v8::Isolate::SetCounterFunction(), and v8::Isolate::SetCreateHistogramFunction().
ModuleResolutionFailureCallback()
void v8::Shell::ModuleResolutionFailureCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 1508 of file d8.cc.
                                             {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate(info.GetIsolate());
  HandleScope handle_scope(isolate);
  Local<Array> module_resolution_data(info.Data().As<Array>());
  Local<Context> context(isolate->GetCurrentContext());
  Local<Promise::Resolver> resolver(
      module_resolution_data->Get(context, ModuleResolutionDataIndex::kResolver)
          .ToLocalChecked()
          .As<Promise::Resolver>());
  PerIsolateData* data = PerIsolateData::Get(isolate);
  Local<Context> realm = data->realms_[data->realm_current_].Get(isolate);
  Context::Scope context_scope(realm);
  DCHECK_EQ(info.Length(), 1);
  resolver->Reject(realm, info[0]).ToChecked();
}
References v8::FunctionCallbackInfo< T >::Data(), DCHECK, DCHECK_EQ, v8::PerIsolateData::Get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::kResolver, v8::FunctionCallbackInfo< T >::Length(), v8::PerIsolateData::realm_current_, v8::PerIsolateData::realms_, and v8::internal::ValidateCallbackInfo().
Referenced by v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise().
ModuleResolutionSuccessCallback()
void v8::Shell::ModuleResolutionSuccessCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 1484 of file d8.cc.
                                             {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate(info.GetIsolate());
  HandleScope handle_scope(isolate);
  Local<Array> module_resolution_data(info.Data().As<Array>());
  Local<Context> context(isolate->GetCurrentContext());
  Local<Promise::Resolver> resolver(
      module_resolution_data->Get(context, ModuleResolutionDataIndex::kResolver)
          .ToLocalChecked()
          .As<Promise::Resolver>());
  Local<Value> namespace_or_source(
      module_resolution_data
          ->Get(context, ModuleResolutionDataIndex::kNamespaceOrSource)
          .ToLocalChecked());
  PerIsolateData* data = PerIsolateData::Get(isolate);
  Local<Context> realm = data->realms_[data->realm_current_].Get(isolate);
  Context::Scope context_scope(realm);
  resolver->Resolve(realm, namespace_or_source).ToChecked();
}
References v8::FunctionCallbackInfo< T >::Data(), DCHECK, v8::internal::compiler::turboshaft::Get(), v8::PerIsolateData::Get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::kNamespaceOrSource, v8::anonymous_namespace{d8.cc}::kResolver, v8::PerIsolateData::realm_current_, v8::PerIsolateData::realms_, and v8::internal::ValidateCallbackInfo().
Referenced by v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise().
NodeTypeCallback()
void v8::Shell::NodeTypeCallback (const v8::FunctionCallbackInfo< v8::Value > & info) [static], [private]
Definition at line 3891 of file d8.cc.
                                                                        {
  DCHECK(i::ValidateCallbackInfo(info));
  v8::Isolate* isolate = info.GetIsolate();
  info.GetReturnValue().Set(v8::Number::New(isolate, 1));
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Number::New(), and v8::internal::ValidateCallbackInfo().
NotifyDone()
static void v8::Shell::NotifyDone (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
OnExit()
void v8::Shell::OnExit (v8::Isolate * isolate, bool dispose) [static]
Definition at line 4638 of file d8.cc.
                                                   {
  platform::NotifyIsolateShutdown(g_default_platform, isolate);
  if (Worker* worker = Worker::GetCurrentWorker()) {
    // When invoking `quit` on a worker isolate, the worker needs to reach
    // State::kTerminated before invoking Isolate::Dispose. This is because the
    // main thread tries to terminate all workers at the end, which can happen
    // concurrently to Isolate::Dispose.
    worker->EnterTerminatedState();
  }
  if (dispose) {
    isolate->Dispose();
  } else {
    // Normally, Dispose() prints counters. Benchmarks expect counters to be
    // printed on process exit, so do so manually if not disposing.
    isolate->DumpAndResetStats();
  }
  // Simulate errors before disposing V8, as that resets flags (via
  // FlagList::ResetAllFlags()), but error simulation reads the random seed.
  if (options.simulate_errors && is_valid_fuzz_script()) {
    // Simulate several errors detectable by fuzzers behind a flag if the
    // minimum file size for fuzzing was executed.
    FuzzerMonitor::SimulateErrors();
  }
  if (dispose) {
    V8::Dispose();
    V8::DisposePlatform();
  }
  if (options.dump_counters || options.dump_counters_nvp) {
    DumpCounters();
  }
  if (options.dump_system_memory_stats) {
    int peak_memory_usage = base::OS::GetPeakMemoryUsageKb();
    std::cout << "System peak memory usage (kb): " << peak_memory_usage
              << std::endl;
    // TODO(jdapena): call rusage platform independent call, and extract peak
    // memory usage to print it
  }
  // Only delete the counters if we are done executing; after calling `quit`,
  // other isolates might still be running and accessing that memory. This is a
  // memory leak, which is OK in this case.
  if (dispose) {
    delete counters_file_;
    delete counter_map_;
  }
}
References anonymous_namespace{mksnapshot.cc}::counter_map_, v8::V8::Dispose(), v8::Isolate::Dispose(), v8::V8::DisposePlatform(), v8::Isolate::DumpAndResetStats(), v8::anonymous_namespace{d8.cc}::g_default_platform, v8::Worker::GetCurrentWorker(), v8::base::OS::GetPeakMemoryUsageKb(), v8::platform::NotifyIsolateShutdown(), and v8::FuzzerMonitor::SimulateErrors().
PerformanceMark()
void v8::Shell::PerformanceMark (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2173 of file d8.cc.
                                                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  if (info.Length() < 1 || !info[0]->IsString()) {
    ThrowError(info.GetIsolate(), "Invalid 'name' argument");
    return;
  }
  Local<String> name = info[0].As<String>();
  double timestamp = GetTimestamp();
  Local<Object> performance_entry = Object::New(isolate);
  performance_entry
      ->DefineOwnProperty(context,
                          String::NewFromUtf8Literal(isolate, "entryType"),
                          String::NewFromUtf8Literal(isolate, "mark"), ReadOnly)
      .Check();
  performance_entry
      ->DefineOwnProperty(context, String::NewFromUtf8Literal(isolate, "name"),
                          name, ReadOnly)
      .Check();
  performance_entry
      ->DefineOwnProperty(context,
                          String::NewFromUtf8Literal(isolate, "startTime"),
                          Number::New(isolate, timestamp), ReadOnly)
      .Check();
  performance_entry
      ->DefineOwnProperty(context,
                          String::NewFromUtf8Literal(isolate, "duration"),
                          Integer::New(isolate, 0), ReadOnly)
      .Check();
  info.GetReturnValue().Set(performance_entry);
#ifdef V8_OS_LINUX
  if (options.scope_linux_perf_to_mark_measure) {
    SendPerfControlCommand("enable");
  }
#endif
}
References DCHECK, v8::Object::DefineOwnProperty(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), name, v8::Object::New(), v8::Number::New(), v8::Integer::New(), v8::String::NewFromUtf8Literal(), v8::ReadOnly, v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
PerformanceMeasure()
void v8::Shell::PerformanceMeasure (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2218 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  if (info.Length() < 1 || !info[0]->IsString()) {
    ThrowError(info.GetIsolate(), "Invalid 'name' argument");
    return;
  }
  v8::Local<String> name = info[0].As<String>();
  double start_timestamp = 0;
  if (info.Length() >= 2) {
#ifdef V8_OS_LINUX
    if (options.scope_linux_perf_to_mark_measure) {
      SendPerfControlCommand("disable");
    }
#endif
    Local<Value> start_mark = info[1].As<Value>();
    if (!start_mark->IsObject()) {
      ThrowError(info.GetIsolate(),
                 "Invalid 'startMark' argument: Not an Object");
      return;
    }
    Local<Value> start_time_field;
    if (!start_mark.As<Object>()
             ->Get(context, String::NewFromUtf8Literal(isolate, "startTime"))
             .ToLocal(&start_time_field)) {
      return;
    }
    if (!start_time_field->IsNumber()) {
      ThrowError(info.GetIsolate(),
                 "Invalid 'startMark' argument: No numeric 'startTime' field");
      return;
    }
    start_timestamp = start_time_field.As<Number>()->Value();
  }
  if (info.Length() > 2) {
    ThrowError(info.GetIsolate(), "Too many arguments");
    return;
  }
  double end_timestamp = GetTimestamp();
  if (options.trace_enabled) {
    size_t hash = base::hash_combine(name->GetIdentityHash(), start_timestamp,
                                     end_timestamp);
    String::Utf8Value utf8(isolate, name);
    TRACE_EVENT_COPY_NESTABLE_ASYNC_BEGIN_WITH_TIMESTAMP1(
        "v8", *utf8, static_cast<uint64_t>(hash),
        GetTracingTimestampFromPerformanceTimestamp(start_timestamp),
        "startTime", start_timestamp);
    TRACE_EVENT_COPY_NESTABLE_ASYNC_END_WITH_TIMESTAMP0(
        "v8", *utf8, static_cast<uint64_t>(hash),
        GetTracingTimestampFromPerformanceTimestamp(end_timestamp));
  }
  Local<Object> performance_entry = Object::New(isolate);
  performance_entry
      ->DefineOwnProperty(
          context, String::NewFromUtf8Literal(isolate, "entryType"),
          String::NewFromUtf8Literal(isolate, "measure"), ReadOnly)
      .Check();
  performance_entry
      ->DefineOwnProperty(context, String::NewFromUtf8Literal(isolate, "name"),
                          name, ReadOnly)
      .Check();
  performance_entry
      ->DefineOwnProperty(context,
                          String::NewFromUtf8Literal(isolate, "startTime"),
                          Number::New(isolate, start_timestamp), ReadOnly)
      .Check();
  performance_entry
      ->DefineOwnProperty(
          context, String::NewFromUtf8Literal(isolate, "duration"),
          Number::New(isolate, end_timestamp - start_timestamp), ReadOnly)
      .Check();
  info.GetReturnValue().Set(performance_entry);
}
References v8::Local< T >::As(), DCHECK, v8::Object::DefineOwnProperty(), v8::Object::Get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::base::hash_combine(), v8::FunctionCallbackInfo< T >::Length(), name, v8::Object::New(), v8::Number::New(), v8::String::NewFromUtf8Literal(), v8::ReadOnly, v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocal(), TRACE_EVENT_COPY_NESTABLE_ASYNC_BEGIN_WITH_TIMESTAMP1, TRACE_EVENT_COPY_NESTABLE_ASYNC_END_WITH_TIMESTAMP0, and v8::internal::ValidateCallbackInfo().
PerformanceMeasureMemory()
void v8::Shell::PerformanceMeasureMemory (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2304 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  v8::MeasureMemoryMode mode = v8::MeasureMemoryMode::kSummary;
  v8::Isolate* isolate = info.GetIsolate();
  Local<Context> context = isolate->GetCurrentContext();
  if (info.Length() >= 1 && info[0]->IsObject()) {
    Local<Object> object = info[0].As<Object>();
    Local<Value> value = TryGetValue(isolate, context, object, "detailed")
                             .FromMaybe(Local<Value>());
    if (value.IsEmpty()) {
      // Exception was thrown and scheduled, so return from the callback.
      return;
    }
    if (value->IsBoolean() && value->BooleanValue(isolate)) {
      mode = v8::MeasureMemoryMode::kDetailed;
    }
  }
  Local<v8::Promise::Resolver> promise_resolver =
      v8::Promise::Resolver::New(context).ToLocalChecked();
  info.GetIsolate()->MeasureMemory(
      v8::MeasureMemoryDelegate::Default(isolate, context, promise_resolver,
                                         mode),
      v8::MeasureMemoryExecution::kEager);
  info.GetReturnValue().Set(promise_resolver->GetPromise());
}
References DCHECK, v8::MeasureMemoryDelegate::Default(), v8::MaybeLocal< T >::FromMaybe(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::kDetailed, v8::kEager, v8::kSummary, v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::MeasureMemory(), mode(), v8::Promise::Resolver::New(), v8::anonymous_namespace{d8.cc}::TryGetValue(), v8::internal::ValidateCallbackInfo(), and v8::internal::value.
PerformanceNow()
void v8::Shell::PerformanceNow (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2166 of file d8.cc.
                                                                      {
  DCHECK(i::ValidateCallbackInfo(info));
  info.GetReturnValue().Set(GetTimestamp());
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::internal::ValidateCallbackInfo().
Print()
void v8::Shell::Print (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2978 of file d8.cc.
                                                             {
  WriteAndFlush(stdout, info);
}
References v8::WriteAndFlush().
PrintErr()
void v8::Shell::PrintErr (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2982 of file d8.cc.
                                                                {
  WriteAndFlush(stderr, info);
}
References v8::WriteAndFlush().
ProfilerSetOnProfileEndListener()
void v8::Shell::ProfilerSetOnProfileEndListener (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2874 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  if (!info[0]->IsFunction()) {
    ThrowError(isolate, "The OnProfileEnd listener has to be a function");
    return;
  }
  base::MutexGuard lock_guard(&profiler_end_callback_lock_);
  profiler_end_callback_[isolate] =
      std::make_pair(Global<Function>(isolate, info[0].As<Function>()),
                     Global<Context>(isolate, isolate->GetCurrentContext()));
}
References DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
ProfilerTriggerSample()
void v8::Shell::ProfilerTriggerSample (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2911 of file d8.cc.
                                                 {
  Isolate* isolate = info.GetIsolate();
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  D8Console* console =
      reinterpret_cast<D8Console*>(i_isolate->console_delegate());
  if (console && console->profiler()) {
    console->profiler()->CollectSample(isolate);
  }
}
References v8::CpuProfiler::CollectSample(), v8::internal::Isolate::console_delegate(), v8::FunctionCallbackInfo< T >::GetIsolate(), and v8::D8Console::profiler().
PromiseRejectCallback()
void v8::Shell::PromiseRejectCallback (v8::PromiseRejectMessage reject_message) [static]
Definition at line 4289 of file d8.cc.
                                                             {
  if (options.ignore_unhandled_promises) return;
  if (data.GetEvent() == v8::kPromiseRejectAfterResolved ||
      data.GetEvent() == v8::kPromiseResolveAfterResolved) {
    // Ignore reject/resolve after resolved.
    return;
  }
  v8::Local<v8::Promise> promise = data.GetPromise();
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  PerIsolateData* isolate_data = PerIsolateData::Get(isolate);
  if (data.GetEvent() == v8::kPromiseHandlerAddedAfterReject) {
    isolate_data->RemoveUnhandledPromise(promise);
    return;
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  bool capture_exceptions =
      i_isolate->get_capture_stack_trace_for_uncaught_exceptions();
  isolate->SetCaptureStackTraceForUncaughtExceptions(true);
  v8::Local<Value> exception = data.GetValue();
  v8::Local<Message> message;
  // Assume that all objects are stack-traces.
  if (exception->IsObject()) {
    message = v8::Exception::CreateMessage(isolate, exception);
  }
  if (!exception->IsNativeError() &&
      (message.IsEmpty() || message->GetStackTrace().IsEmpty())) {
    // If there is no real Error object, manually create a stack trace.
    exception = v8::Exception::Error(
        v8::String::NewFromUtf8Literal(isolate, "Unhandled Promise."));
    message = Exception::CreateMessage(isolate, exception);
  }
  isolate->SetCaptureStackTraceForUncaughtExceptions(capture_exceptions);
  isolate_data->AddUnhandledPromise(promise, message, exception);
}
References v8::PerIsolateData::AddUnhandledPromise(), v8::Exception::CreateMessage(), v8::Exception::Error(), v8::PerIsolateData::Get(), v8::internal::Isolate::get_capture_stack_trace_for_uncaught_exceptions(), v8::Isolate::GetCurrent(), v8::PromiseRejectMessage::GetEvent(), v8::PromiseRejectMessage::GetPromise(), v8::PromiseRejectMessage::GetValue(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::kPromiseHandlerAddedAfterReject, v8::kPromiseRejectAfterResolved, v8::kPromiseResolveAfterResolved, v8::String::NewFromUtf8Literal(), v8::PerIsolateData::RemoveUnhandledPromise(), and v8::Isolate::SetCaptureStackTraceForUncaughtExceptions().
Quit()
void v8::Shell::Quit (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3701 of file d8.cc.
                                                            {
  DCHECK(i::ValidateCallbackInfo(info));
  base::CallOnce(&quit_once_, &QuitOnce,
                 const_cast<v8::FunctionCallbackInfo<v8::Value>*>(&info));
}
References v8::base::CallOnce(), DCHECK, and v8::internal::ValidateCallbackInfo().
QuitOnce()
void v8::Shell::QuitOnce (v8::FunctionCallbackInfo< v8::Value > * info) [static]
Definition at line 3635 of file d8.cc.
                                                          {
  int exit_code = (*info)[0]
                      ->Int32Value(info->GetIsolate()->GetCurrentContext())
                      .FromMaybe(0);
  Isolate* isolate = info->GetIsolate();
  ResetOnProfileEndListener(isolate);
  // As we exit the process anyway, we do not dispose the platform and other
  // global data and manually unlock to quell DCHECKs. Other isolates might
  // still be running, so disposing here can cause them to crash.
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  if (i_isolate->thread_manager()->IsLockedByCurrentThread()) {
    i_isolate->thread_manager()->Unlock();
  }
  // When disposing the shared space isolate, the workers (client isolates) need
  // to be terminated first.
  if (i_isolate->is_shared_space_isolate()) {
    i_isolate->main_thread_local_isolate()->ExecuteMainThreadWhileParked(
        [](const i::ParkedScope& parked) { WaitForRunningWorkers(parked); });
  }
  // Reset thread-locals here only after stopping workers. They are still used
  // e.g. during heap verification in shared GCs.
  isolate->Exit();
  OnExit(isolate, false);
  base::OS::ExitProcess(exit_code);
}
References v8::internal::LocalIsolate::ExecuteMainThreadWhileParked(), v8::Isolate::Exit(), v8::base::OS::ExitProcess(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::ThreadManager::IsLockedByCurrentThread(), v8::internal::Isolate::main_thread_local_isolate(), v8::internal::Isolate::thread_manager(), and v8::internal::ThreadManager::Unlock().
ReadBuffer()
void v8::Shell::ReadBuffer (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 4870 of file d8.cc.
                                                                  {
  DCHECK(i::ValidateCallbackInfo(info));
  static_assert(sizeof(char) == sizeof(uint8_t),
                "char and uint8_t should both have 1 byte");
  Isolate* isolate = info.GetIsolate();
  String::Utf8Value filename(isolate, info[0]);
  int length;
  if (*filename == nullptr) {
    ThrowError(isolate, "Error loading file");
    return;
  }
  uint8_t* data = reinterpret_cast<uint8_t*>(ReadChars(*filename, &length));
  if (data == nullptr) {
    ThrowError(isolate, "Error reading file");
    return;
  }
  Local<v8::ArrayBuffer> buffer = ArrayBuffer::New(isolate, length);
  memcpy(buffer->GetBackingStore()->Data(), data, length);
  delete[] data;
  info.GetReturnValue().Set(buffer);
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::length, v8::ArrayBuffer::New(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
ReadChars()
char * v8::Shell::ReadChars (const char * name, int * size_out) [static]
Definition at line 4813 of file d8.cc.
                                                      {
  if (options.read_from_tcp_port >= 0) {
    return ReadCharsFromTcpPort(name, size_out);
  }
  FILE* file = base::OS::FOpen(name, "rb");
  if (file == nullptr) return nullptr;
  fseek(file, 0, SEEK_END);
  size_t size = ftell(file);
  rewind(file);
  char* chars = new char[size + 1];
  chars[size] = '\0';
  for (size_t i = 0; i < size;) {
    i += fread(&chars[i], 1, size - i, file);
    if (ferror(file)) {
      base::Fclose(file);
      delete[] chars;
      return nullptr;
    }
  }
  base::Fclose(file);
  *size_out = static_cast<int>(size);
  return chars;
}
References v8::base::Fclose(), file(), v8::base::OS::FOpen(), name, and size().
Referenced by LoadJSON().
ReadCharsFromTcpPort()
char * v8::Shell::ReadCharsFromTcpPort (const char * name, int * size_out) [static]
Definition at line 645 of file d8-posix.cc.
                                                                 {
  DCHECK_GE(Shell::options.read_from_tcp_port, 0);
  int sockfd = socket(PF_INET, SOCK_STREAM, 0);
  if (sockfd < 0) {
    fprintf(stderr, "Failed to create IPv4 socket\n");
    return nullptr;
  }
  // Create an address for localhost:PORT where PORT is specified by the shell
  // option --read-from-tcp-port.
  sockaddr_in serv_addr;
  memset(&serv_addr, 0, sizeof(sockaddr_in));
  serv_addr.sin_family = AF_INET;
  serv_addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
  serv_addr.sin_port = htons(Shell::options.read_from_tcp_port);
  if (connect(sockfd, reinterpret_cast<sockaddr*>(&serv_addr),
              sizeof(serv_addr)) < 0) {
    fprintf(stderr, "Failed to connect to localhost:%d\n",
            Shell::options.read_from_tcp_port.get());
    close(sockfd);
    return nullptr;
  }
  // The file server follows the simple protocol for requesting and receiving
  // a file with a given filename:
  //
  // REQUEST client -> server: {filename}"\0"
  // RESPONSE server -> client: {4-byte file-length}{file contents}
  //
  // i.e. the request sends the filename with a null terminator, and response
  // sends the file contents by sending the length (as a 4-byte big-endian
  // value) and the contents.
  // If the file length is <0, there was an error sending the file, and the
  // rest of the response is undefined (and may, in the future, contain an error
  // message). The socket should be closed to avoid trying to interpret the
  // undefined data.
  // REQUEST
  // Send the filename.
  size_t sent_len = 0;
  size_t name_len = strlen(name) + 1; // Includes the null terminator
  while (sent_len < name_len) {
    ssize_t sent_now = send(sockfd, name + sent_len, name_len - sent_len, 0);
    if (sent_now < 0) {
      fprintf(stderr, "Failed to send %s to localhost:%d\n", name,
              Shell::options.read_from_tcp_port.get());
      close(sockfd);
      return nullptr;
    }
    sent_len += sent_now;
  }
  // RESPONSE
  // Receive the file.
  ssize_t received = 0;
  // First, read the (zero-terminated) file length.
  uint32_t big_endian_file_length;
  received = recv(sockfd, &big_endian_file_length, 4, 0);
  // We need those 4 bytes to read off the file length.
  if (received < 4) {
    fprintf(stderr, "Failed to receive %s's length from localhost:%d\n", name,
            Shell::options.read_from_tcp_port.get());
    close(sockfd);
    return nullptr;
  }
  // Reinterpretet the received file length as a signed big-endian integer.
  int32_t file_length = base::bit_cast<int32_t>(htonl(big_endian_file_length));
  if (file_length < 0) {
    fprintf(stderr, "Received length %d for %s from localhost:%d\n",
            file_length, name, Shell::options.read_from_tcp_port.get());
    close(sockfd);
    return nullptr;
  }
  // Allocate the output array.
  char* chars = new char[file_length];
  // Now keep receiving and copying until the whole file is received.
  ssize_t total_received = 0;
  while (total_received < file_length) {
    received =
        recv(sockfd, chars + total_received, file_length - total_received, 0);
    if (received < 0) {
      fprintf(stderr, "Failed to receive %s from localhost:%d\n", name,
              Shell::options.read_from_tcp_port.get());
      close(sockfd);
      delete[] chars;
      return nullptr;
    }
    total_received += received;
  }
  close(sockfd);
  *size_out = file_length;
  return chars;
}
References DCHECK_GE, name, and options.
ReadCodeTypeAndArguments()
void v8::Shell::ReadCodeTypeAndArguments (const v8::FunctionCallbackInfo< v8::Value > & info, int index, CodeType * code_type, Local< Value > * arguments = nullptr) [static]
Definition at line 3204 of file d8.cc.
                                                  {
  Isolate* isolate = info.GetIsolate();
  if (info.Length() > index && info[index]->IsObject()) {
    Local<Object> object = info[index].As<Object>();
    Local<Context> context = isolate->GetCurrentContext();
    Local<Value> value;
    if (!TryGetValue(isolate, context, object, "type").ToLocal(&value)) {
      *code_type = CodeType::kNone;
      return;
    }
    if (!value->IsString()) {
      *code_type = CodeType::kInvalid;
      return;
    }
    Local<String> worker_type_string =
        value->ToString(context).ToLocalChecked();
    String::Utf8Value str(isolate, worker_type_string);
    if (strcmp("classic", *str) == 0) {
      *code_type = CodeType::kFileName;
    } else if (strcmp("string", *str) == 0) {
      *code_type = CodeType::kString;
    } else if (strcmp("function", *str) == 0) {
      *code_type = CodeType::kFunction;
    } else {
      *code_type = CodeType::kInvalid;
    }
    if (arguments != nullptr) {
      bool got_arguments =
          TryGetValue(isolate, context, object, "arguments").ToLocal(arguments);
      USE(got_arguments);
    }
  } else {
    *code_type = CodeType::kNone;
  }
}
References v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::internal::torque::ls::kFunction, v8::internal::anonymous_namespace{isolate.cc}::kInvalid, v8::FunctionCallbackInfo< T >::Length(), v8::MaybeLocal< T >::ToLocal(), v8::anonymous_namespace{d8.cc}::TryGetValue(), USE, and v8::internal::value.
ReadFile() [1/2]
void v8::Shell::ReadFile (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3040 of file d8.cc.
                                                                {
  DCHECK(i::ValidateCallbackInfo(info));
  String::Utf8Value file_name(info.GetIsolate(), info[0]);
  if (*file_name == nullptr) {
    ThrowError(info.GetIsolate(), "Error converting filename to string");
    return;
  }
  if (info.Length() == 2) {
    String::Utf8Value format(info.GetIsolate(), info[1]);
    if (*format && std::strcmp(*format, "binary") == 0) {
      ReadBuffer(info);
      return;
    }
  }
  Local<String> source;
  if (!ReadFile(info.GetIsolate(), *file_name).ToLocal(&source)) return;
  info.GetReturnValue().Set(source);
}
References DCHECK, v8::base::format, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadFile(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
ReadFile() [2/2]
MaybeLocal< String > v8::Shell::ReadFile (Isolate * isolate, const char * name, bool should_throw = true) [static]
Definition at line 4920 of file d8.cc.
                                                      {
  auto file = ReadFileData(isolate, name, should_throw);
  if (!file) {
    return MaybeLocal<String>();
  }
  int size = static_cast<int>(file->size());
  char* chars = static_cast<char*>(file->memory());
  if (i::v8_flags.use_external_strings && i::String::IsAscii(chars, size)) {
    String::ExternalOneByteStringResource* resource =
        new ExternalOwningOneByteStringResource(std::move(file));
    return String::NewExternalOneByte(isolate, resource);
  }
  return String::NewFromUtf8(isolate, chars, NewStringType::kNormal, size);
}
References file(), v8::internal::String::IsAscii(), v8::kNormal, name, v8::String::NewExternalOneByte(), v8::String::NewFromUtf8(), size(), and v8::internal::v8_flags.
Referenced by CreateD8Template(), v8::SourceGroup::Execute(), FetchModuleTree(), ReadSource(), and WasmLoadSourceMapCallback().
ReadFileData()
std::unique_ptr< base::OS::MemoryMappedFile > v8::Shell::ReadFileData (Isolate * isolate, const char * name, bool should_throw = true) [static]
Definition at line 4900 of file d8.cc.
                                                           {
  std::unique_ptr<base::OS::MemoryMappedFile> file(
      base::OS::MemoryMappedFile::open(
          name, base::OS::MemoryMappedFile::FileMode::kReadOnly));
  if (!file) {
    if (should_throw) {
      std::ostringstream oss;
      oss << "Error loading file: " << name;
      ThrowError(isolate,
                 v8::String::NewFromUtf8(
                     isolate, oss.str().substr(0, String::kMaxLength).c_str())
                     .ToLocalChecked());
    }
    return nullptr;
  }
  return file;
}
References file(), v8::String::kMaxLength, v8::base::OS::MemoryMappedFile::kReadOnly, name, v8::String::NewFromUtf8(), v8::base::OS::MemoryMappedFile::open(), and v8::anonymous_namespace{d8.cc}::ThrowError().
Referenced by FetchModuleSource().
ReadFromStdin()
Local< String > v8::Shell::ReadFromStdin (Isolate * isolate) [static]
Definition at line 3079 of file d8.cc.
                                                   {
  static const int kBufferSize = 256;
  char buffer[kBufferSize];
  Local<String> accumulator = String::NewFromUtf8Literal(isolate, "");
  int length;
  // Flush stdout before reading stdin, as stdout isn't guaranteed to be flushed
  // automatically.
  fflush(stdout);
  while (true) {
    // Continue reading if the line ends with an escape '\\' or the line has
    // not been fully read into the buffer yet (does not end with '\n').
    // If fgets gets an error, just give up.
    char* input = nullptr;
    input = fgets(buffer, kBufferSize, stdin);
    if (input == nullptr) return Local<String>();
    length = static_cast<int>(strlen(buffer));
    if (length == 0) {
      return accumulator;
    } else if (buffer[length - 1] != '\n') {
      accumulator = String::Concat(
          isolate, accumulator,
          String::NewFromUtf8(isolate, buffer, NewStringType::kNormal, length)
              .ToLocalChecked());
    } else if (length > 1 && buffer[length - 2] == '\\') {
      buffer[length - 2] = '\n';
      accumulator =
          String::Concat(isolate, accumulator,
                         String::NewFromUtf8(isolate, buffer,
                                             NewStringType::kNormal, length - 1)
                             .ToLocalChecked());
    } else {
      return String::Concat(
          isolate, accumulator,
          String::NewFromUtf8(isolate, buffer, NewStringType::kNormal,
                              length - 1)
              .ToLocalChecked());
    }
  }
}
References v8::String::Concat(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, v8::kNormal, v8::internal::length, v8::String::NewFromUtf8(), and v8::String::NewFromUtf8Literal().
Referenced by RunShell().
ReadLine()
void v8::Shell::ReadLine (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 4894 of file d8.cc.
                                                                {
  DCHECK(i::ValidateCallbackInfo(info));
  info.GetReturnValue().Set(ReadFromStdin(info.GetIsolate()));
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::internal::ValidateCallbackInfo().
ReadLines()
MaybeLocal< PrimitiveArray > v8::Shell::ReadLines (Isolate * isolate, const char * name) [static]
Definition at line 4840 of file d8.cc.
                                                              {
  int length;
  std::unique_ptr<char[]> data(ReadChars(name, &length));
  if (data.get() == nullptr) {
    return MaybeLocal<PrimitiveArray>();
  }
  std::stringstream stream(data.get());
  std::string line;
  std::vector<std::string> lines;
  while (std::getline(stream, line, '\n')) {
    lines.emplace_back(line);
  }
  // Create a Local<PrimitiveArray> off the read lines.
  int size = static_cast<int>(lines.size());
  Local<PrimitiveArray> exports = PrimitiveArray::New(isolate, size);
  for (int i = 0; i < size; ++i) {
    MaybeLocal<String> maybe_str = v8::String::NewFromUtf8(
        isolate, lines[i].c_str(), NewStringType::kNormal,
        static_cast<int>(lines[i].length()));
    Local<String> str;
    if (!maybe_str.ToLocal(&str)) {
      return MaybeLocal<PrimitiveArray>();
    }
    exports->Set(isolate, i, str);
  }
  return exports;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::kNormal, v8::internal::length, name, v8::PrimitiveArray::New(), v8::String::NewFromUtf8(), size(), v8::internal::string, and v8::MaybeLocal< T >::ToLocal().
ReadSource()
MaybeLocal< String > v8::Shell::ReadSource (const v8::FunctionCallbackInfo< v8::Value > & info, int index, CodeType default_type) [static]
Definition at line 3291 of file d8.cc.
                           {
  CodeType code_type;
  Local<Value> arguments;
  ReadCodeTypeAndArguments(info, index + 1, &code_type, &arguments);
  Isolate* isolate = info.GetIsolate();
  Local<String> source;
  if (code_type == CodeType::kNone) {
    code_type = default_type;
  }
  switch (code_type) {
    case CodeType::kFunction:
      if (!info[index]->IsFunction()) {
        return MaybeLocal<String>();
      }
      // Source: (function_to_string)(params)
      if (!FunctionAndArgumentsToString(info[index].As<Function>(), arguments,
                                        &source, isolate)) {
        return MaybeLocal<String>();
      }
      break;
    case CodeType::kFileName: {
      if (!info[index]->IsString()) {
        return MaybeLocal<String>();
      }
      String::Utf8Value filename(isolate, info[index]);
      if (!Shell::ReadFile(isolate, *filename).ToLocal(&source)) {
        return MaybeLocal<String>();
      }
      break;
    }
    case CodeType::kString:
      if (!info[index]->IsString()) {
        return MaybeLocal<String>();
      }
      source = info[index].As<String>();
      break;
    case CodeType::kNone:
    case CodeType::kInvalid:
      return MaybeLocal<String>();
  }
  return source;
}
References v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::internal::torque::ls::kFunction, v8::internal::anonymous_namespace{isolate.cc}::kInvalid, and ReadFile().
RealmCreate()
void v8::Shell::RealmCreate (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2441 of file d8.cc.
                                                                   {
  DCHECK(i::ValidateCallbackInfo(info));
  CreateRealm(info, -1, v8::MaybeLocal<Value>());
}
References DCHECK, and v8::internal::ValidateCallbackInfo().
RealmCreateAllowCrossRealmAccess()
void v8::Shell::RealmCreateAllowCrossRealmAccess (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2448 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Local<Context> context;
  if (CreateRealm(info, -1, v8::MaybeLocal<Value>()).ToLocal(&context)) {
    context->SetSecurityToken(
        info.GetIsolate()->GetEnteredOrMicrotaskContext()->GetSecurityToken());
  }
}
References DCHECK, v8::Isolate::GetEnteredOrMicrotaskContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Context::GetSecurityToken(), v8::Context::SetSecurityToken(), and v8::internal::ValidateCallbackInfo().
RealmCurrent()
void v8::Shell::RealmCurrent (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2332 of file d8.cc.
                                                                    {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int index = data->RealmFind(isolate->GetEnteredOrMicrotaskContext());
  if (index == -1) return;
  info.GetReturnValue().Set(index);
}
References DCHECK, v8::PerIsolateData::Get(), v8::Isolate::GetEnteredOrMicrotaskContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::PerIsolateData::RealmFind(), and v8::internal::ValidateCallbackInfo().
RealmDetachGlobal()
void v8::Shell::RealmDetachGlobal (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2490 of file d8.cc.
                                                                         {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int index = data->RealmIndexOrThrow(info, 0);
  if (index == -1) return;
  if (index == 0 || index == data->realm_current_ ||
      index == data->realm_switch_) {
    ThrowError(info.GetIsolate(), "Invalid realm index");
    return;
  }
  HandleScope scope(isolate);
  Local<Context> realm = Local<Context>::New(isolate, data->realms_[index]);
  realm->DetachGlobal();
}
References DCHECK, v8::Context::DetachGlobal(), v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::Local< T >::New(), v8::PerIsolateData::realm_current_, v8::PerIsolateData::realm_switch_, v8::PerIsolateData::RealmIndexOrThrow(), v8::PerIsolateData::realms_, v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
RealmDispose()
void v8::Shell::RealmDispose (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2508 of file d8.cc.
                                                                    {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int index = data->RealmIndexOrThrow(info, 0);
  if (index == -1) return;
  if (index == 0 || index == data->realm_current_ ||
      index == data->realm_switch_) {
    ThrowError(info.GetIsolate(), "Invalid realm index");
    return;
  }
  DisposeRealm(info, index);
}
References DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::PerIsolateData::realm_current_, v8::PerIsolateData::realm_switch_, v8::PerIsolateData::RealmIndexOrThrow(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
RealmEval()
void v8::Shell::RealmEval (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2533 of file d8.cc.
                                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int index = data->RealmIndexOrThrow(info, 0);
  if (index == -1) return;
  if (info.Length() < 2) {
    ThrowError(isolate, "Invalid argument");
    return;
  }
  Local<String> source;
  if (!ReadSource(info, 1, CodeType::kString).ToLocal(&source)) {
    ThrowError(isolate, "Invalid argument");
    return;
  }
  ScriptOrigin origin =
      CreateScriptOrigin(isolate, String::NewFromUtf8Literal(isolate, "(d8)"),
                         ScriptType::kClassic);
  if (isolate->IsExecutionTerminating()) return;
  ScriptCompiler::Source script_source(source, origin);
  Local<UnboundScript> script;
  if (!ScriptCompiler::CompileUnboundScript(isolate, &script_source)
           .ToLocal(&script)) {
    return;
  }
  Local<Value> result;
  {
    PerIsolateData::ExplicitRealmScope realm_scope(data, index);
    if (!script->BindToCurrentContext()
             ->Run(realm_scope.context())
             .ToLocal(&result)) {
      return;
    }
  }
  info.GetReturnValue().Set(result);
}
References v8::ScriptCompiler::CompileUnboundScript(), v8::PerIsolateData::ExplicitRealmScope::context(), v8::anonymous_namespace{d8.cc}::CreateScriptOrigin(), DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::Isolate::IsExecutionTerminating(), v8::kClassic, v8::FunctionCallbackInfo< T >::Length(), v8::String::NewFromUtf8Literal(), v8::PerIsolateData::RealmIndexOrThrow(), v8::base::internal::result, v8::internal::script, v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
RealmGlobal()
void v8::Shell::RealmGlobal (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2369 of file d8.cc.
                                                                   {
  DCHECK(i::ValidateCallbackInfo(info));
  PerIsolateData* data = PerIsolateData::Get(info.GetIsolate());
  int index = data->RealmIndexOrThrow(info, 0);
  if (index == -1) return;
  // TODO(chromium:324812): Ideally Context::Global should never return raw
  // global objects but return a global proxy. Currently it returns global
  // object when the global proxy is detached from the global object. The
  // following is a workaround till we fix Context::Global so we don't leak
  // global objects.
  Local<Object> global =
      Local<Context>::New(info.GetIsolate(), data->realms_[index])->Global();
  i::DirectHandle<i::Object> i_global = Utils::OpenDirectHandle(*global);
  if (IsJSGlobalObject(*i_global)) {
    i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(info.GetIsolate());
    i::DirectHandle<i::JSObject> i_global_proxy(
        i::Cast<i::JSGlobalObject>(i_global)->global_proxy(), i_isolate);
    global = Utils::ToLocal(i_global_proxy);
  }
  info.GetReturnValue().Set(global);
}
References DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::Local< T >::New(), v8::Utils::OpenDirectHandle(), v8::PerIsolateData::RealmIndexOrThrow(), v8::PerIsolateData::realms_, and v8::internal::ValidateCallbackInfo().
RealmNavigate()
void v8::Shell::RealmNavigate (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2460 of file d8.cc.
                                                                     {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int index = data->RealmIndexOrThrow(info, 0);
  if (index == -1) return;
  if (index == 0 || index == data->realm_current_ ||
      index == data->realm_switch_) {
    ThrowError(info.GetIsolate(), "Invalid realm index");
    return;
  }
  Local<Context> context = Local<Context>::New(isolate, data->realms_[index]);
  v8::MaybeLocal<Value> global_object = context->Global();
  // Context::Global doesn't return JSGlobalProxy if DetachGlobal is called in
  // advance.
  if (!global_object.IsEmpty()) {
    HandleScope scope(isolate);
    if (!IsJSGlobalProxy(
            *Utils::OpenDirectHandle(*global_object.ToLocalChecked()))) {
      global_object = v8::MaybeLocal<Value>();
    }
  }
  DisposeRealm(info, index);
  CreateRealm(info, index, global_object);
}
References DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::Context::Global(), v8::internal::index, v8::MaybeLocal< T >::IsEmpty(), v8::Local< T >::New(), v8::Utils::OpenDirectHandle(), v8::PerIsolateData::realm_current_, v8::PerIsolateData::realm_switch_, v8::PerIsolateData::RealmIndexOrThrow(), v8::PerIsolateData::realms_, v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocalChecked(), and v8::internal::ValidateCallbackInfo().
RealmOwner()
void v8::Shell::RealmOwner (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2342 of file d8.cc.
                                                                  {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  if (info.Length() < 1 || !info[0]->IsObject()) {
    ThrowError(info.GetIsolate(), "Invalid argument");
    return;
  }
  Local<Object> object =
      info[0]->ToObject(isolate->GetCurrentContext()).ToLocalChecked();
  i::DirectHandle<i::JSReceiver> i_object = Utils::OpenDirectHandle(*object);
  if (IsJSGlobalProxy(*i_object) &&
      i::Cast<i::JSGlobalProxy>(i_object)->IsDetached()) {
    return;
  }
  Local<Context> creation_context;
  if (!object->GetCreationContext(isolate).ToLocal(&creation_context)) {
    ThrowError(info.GetIsolate(), "object doesn't have creation context");
    return;
  }
  int index = data->RealmFind(creation_context);
  if (index == -1) return;
  info.GetReturnValue().Set(index);
}
References DCHECK, v8::PerIsolateData::Get(), v8::Object::GetCreationContext(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::index, v8::FunctionCallbackInfo< T >::Length(), v8::Utils::OpenDirectHandle(), v8::PerIsolateData::RealmFind(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocal(), and v8::internal::ValidateCallbackInfo().
RealmSharedGet()
void v8::Shell::RealmSharedGet (Local< Name > property, const PropertyCallbackInfo< Value > & info) [static]
Definition at line 2573 of file d8.cc.
                                                                    {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  if (data->realm_shared_.IsEmpty()) return;
  info.GetReturnValue().Set(data->realm_shared_);
}
References DCHECK, v8::PerIsolateData::Get(), v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PropertyCallbackInfo< T >::GetReturnValue(), v8::PerIsolateData::realm_shared_, and v8::internal::ValidateCallbackInfo().
RealmSharedSet()
void v8::Shell::RealmSharedSet (Local< Name > property, Local< Value > value, const PropertyCallbackInfo< void > & info) [static]
Definition at line 2582 of file d8.cc.
                                                                   {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  data->realm_shared_.Reset(isolate, value);
}
References DCHECK, v8::PerIsolateData::Get(), v8::PropertyCallbackInfo< T >::GetIsolate(), v8::PerIsolateData::realm_shared_, v8::internal::ValidateCallbackInfo(), and v8::internal::value.
RealmSwitch()
void v8::Shell::RealmSwitch (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2523 of file d8.cc.
                                                                   {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  PerIsolateData* data = PerIsolateData::Get(isolate);
  int index = data->RealmIndexOrThrow(info, 0);
  if (index == -1) return;
  data->realm_switch_ = index;
}
References DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::index, v8::PerIsolateData::realm_switch_, v8::PerIsolateData::RealmIndexOrThrow(), and v8::internal::ValidateCallbackInfo().
RemoveDirectory()
void v8::Shell::RemoveDirectory (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 594 of file d8-posix.cc.
                                                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  if (info.Length() != 1) {
    info.GetIsolate()->ThrowError("rmdir() takes one arguments");
    return;
  }
  String::Utf8Value directory(info.GetIsolate(), info[0]);
  if (*directory == nullptr) {
    info.GetIsolate()->ThrowError(
        "os.rmdir(): String conversion of argument failed.");
    return;
  }
  rmdir(*directory);
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by AddOSMethods().
RemoveRunningWorker()
void v8::Shell::RemoveRunningWorker (const std::shared_ptr< Worker > & worker) [static]
Definition at line 6615 of file d8.cc.
                                                                   {
  base::MutexGuard lock_guard(workers_mutex_.Pointer());
  auto it = running_workers_.find(worker);
  if (it != running_workers_.end()) running_workers_.erase(it);
}
Referenced by v8::Worker::WorkerThread::Run().
ReportException() [1/2]
void v8::Shell::ReportException (v8::Isolate * isolate, const TryCatch & try_catch) [static]
Definition at line 3776 of file d8.cc.
                                                         {
  if (isolate->IsExecutionTerminating()) {
    printf("Got Execution Termination Exception\n");
  } else {
    ReportException(isolate, try_catch.Message(), try_catch.Exception());
  }
}
References v8::TryCatch::Exception(), v8::Isolate::IsExecutionTerminating(), and v8::TryCatch::Message().
ReportException() [2/2]
void v8::Shell::ReportException (Isolate * isolate, Local< Message > message, Local< Value > exception) [static]
Definition at line 3714 of file d8.cc.
                                                          {
  HandleScope handle_scope(isolate);
  Local<Context> context = isolate->GetCurrentContext();
  bool enter_context = context.IsEmpty();
  if (enter_context) {
    context = Local<Context>::New(isolate, evaluation_context_);
    context->Enter();
  }
  // Converts a V8 value to a C string.
  auto ToCString = [](const v8::String::Utf8Value& value) {
    return *value ? *value : "<string conversion failed>";
  };
  v8::String::Utf8Value exception(isolate, exception_obj);
  const char* exception_string = ToCString(exception);
  if (message.IsEmpty()) {
    // V8 didn't provide any extra information about this error; just
    // print the exception.
    printf("%s\n", exception_string);
  } else if (message->GetScriptOrigin().Options().IsWasm()) {
    // Print wasm-function[(function index)]:(offset): (message).
    int function_index = message->GetWasmFunctionIndex();
    int offset = message->GetStartColumn(context).FromJust();
    printf("wasm-function[%d]:0x%x: %s\n", function_index, offset,
           exception_string);
  } else {
    // Print (filename):(line number): (message).
    v8::String::Utf8Value filename(isolate,
                                   message->GetScriptOrigin().ResourceName());
    const char* filename_string = ToCString(filename);
    int linenum = message->GetLineNumber(context).FromMaybe(-1);
    printf("%s:%i: %s\n", filename_string, linenum, exception_string);
    Local<String> sourceline;
    if (message->GetSourceLine(context).ToLocal(&sourceline)) {
      // Print line of source code.
      v8::String::Utf8Value sourcelinevalue(isolate, sourceline);
      const char* sourceline_string = ToCString(sourcelinevalue);
      printf("%s\n", sourceline_string);
      // Print wavy underline (GetUnderline is deprecated).
      int start = message->GetStartColumn(context).FromJust();
      for (int i = 0; i < start; i++) {
        printf(" ");
      }
      int end = message->GetEndColumn(context).FromJust();
      for (int i = start; i < end; i++) {
        printf("^");
      }
      printf("\n");
    }
  }
  Local<Value> stack_trace_string;
  if (v8::TryCatch::StackTrace(context, exception_obj)
          .ToLocal(&stack_trace_string) &&
      stack_trace_string->IsString()) {
    v8::String::Utf8Value stack_trace(isolate, stack_trace_string.As<String>());
    printf("%s\n", ToCString(stack_trace));
  }
  printf("\n");
  if (enter_context) context->Exit();
}
References v8::Local< T >::As(), v8::internal::compiler::end(), v8::Context::Enter(), v8::Context::Exit(), v8::Isolate::GetCurrentContext(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Local< T >::New(), v8::TryCatch::StackTrace(), and v8::internal::value.
Referenced by ExecuteModule(), v8::PerIsolateData::HandleUnhandledPromiseRejections(), LoadJSON(), v8::PrintMessageCallback(), v8::anonymous_namespace{d8.cc}::RejectPromiseIfExecutionIsNotTerminating(), and v8::AsyncHooks::ShellPromiseHook().
ResetOnProfileEndListener()
void v8::Shell::ResetOnProfileEndListener (Isolate * isolate) [static]
Definition at line 2894 of file d8.cc.
                                                      {
  // If the inspector is enabled, then the installed console is not the
  // D8Console.
  if (options.enable_inspector) return;
  {
    base::MutexGuard lock_guard(&profiler_end_callback_lock_);
    profiler_end_callback_.erase(isolate);
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  D8Console* console =
      reinterpret_cast<D8Console*>(i_isolate->console_delegate());
  if (console) {
    console->DisposeProfiler();
  }
}
References v8::internal::Isolate::console_delegate(), and v8::D8Console::DisposeProfiler().
Referenced by v8::SourceGroup::ExecuteInThread(), and v8::Worker::ExecuteInThread().
RunMain()
int v8::Shell::RunMain (v8::Isolate * isolate, bool last_run) [static]
Definition at line 6108 of file d8.cc.
                                                    {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  for (int i = 1; i < options.num_isolates; ++i) {
    options.isolate_sources[i].StartExecuteInThread();
  }
  // The Context object, created inside RunMainIsolate, is used after the method
  // returns in some situations:
  const bool keep_context_alive =
      last_run && (use_interactive_shell() || i::v8_flags.stress_snapshot);
  bool success = RunMainIsolate(isolate, keep_context_alive);
  CollectGarbage(isolate);
  // Park the main thread here to prevent deadlocks in shared GCs when
  // waiting in JoinThread.
  i_isolate->main_thread_local_heap()->ExecuteMainThreadWhileParked(
      [last_run](const i::ParkedScope& parked) {
        for (int i = 1; i < options.num_isolates; ++i) {
          if (last_run) {
            options.isolate_sources[i].JoinThread(parked);
          } else {
            options.isolate_sources[i].WaitForThread(parked);
          }
        }
        WaitForRunningWorkers(parked);
      });
  // Other threads have terminated, we can now run the artificial
  // serialize-deserialize pass (which destructively mutates heap state).
  if (success && last_run && i::v8_flags.stress_snapshot) {
    HandleScope handle_scope(isolate);
    static constexpr bool kClearRecompilableData = true;
    auto context = v8::Local<v8::Context>::New(isolate, evaluation_context_);
    i::DirectHandle<i::Context> i_context = Utils::OpenDirectHandle(*context);
    // Stop concurrent compiles before mutating the heap.
    if (i_isolate->concurrent_recompilation_enabled()) {
      i_isolate->optimizing_compile_dispatcher()->StartTearDown();
      i_isolate->optimizing_compile_dispatcher()->FinishTearDown();
    }
#if V8_ENABLE_MAGLEV
    if (i_isolate->maglev_concurrent_dispatcher()->is_enabled()) {
      i_isolate->maglev_concurrent_dispatcher()->AwaitCompileJobs();
    }
#endif // V8_ENABLE_MAGLEV
    // TODO(jgruber,v8:10500): Don't deoptimize once we support serialization
    // of optimized code.
    i::Deoptimizer::DeoptimizeAll(i_isolate);
    // Trigger GC to better align with production code. Also needed by
    // ClearReconstructableDataForSerialization to not look into dead objects.
    i_isolate->heap()->CollectAllAvailableGarbage(
        i::GarbageCollectionReason::kSnapshotCreator);
    i::Snapshot::ClearReconstructableDataForSerialization(
        i_isolate, kClearRecompilableData);
    i::Snapshot::SerializeDeserializeAndVerifyForTesting(i_isolate, i_context);
  }
  if (Shell::unhandled_promise_rejections_.load() > 0) {
    printf("%i pending unhandled Promise rejection(s) detected.\n",
           Shell::unhandled_promise_rejections_.load());
    success = false;
    // RunMain may be executed multiple times, e.g. in REPRL mode, so we have to
    // reset this counter.
    Shell::unhandled_promise_rejections_.store(0);
  }
  // In order to finish successfully, success must be != expected_to_throw.
  if (Shell::options.no_fail) return 0;
  // Fuzzers aren't expected to use --throws, but may pick it up from testcases.
  // In that case, just ignore the flag.
  if (i::v8_flags.fuzzing && Shell::options.expected_to_throw) return 0;
  return (success == Shell::options.expected_to_throw ? 1 : 0);
}
References v8::internal::Snapshot::ClearReconstructableDataForSerialization(), v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::Isolate::concurrent_recompilation_enabled(), v8::internal::Deoptimizer::DeoptimizeAll(), v8::internal::LocalHeap::ExecuteMainThreadWhileParked(), v8::internal::OptimizingCompileDispatcher::FinishTearDown(), v8::internal::Isolate::heap(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Isolate::main_thread_local_heap(), v8::Local< T >::New(), v8::Utils::OpenDirectHandle(), v8::internal::Isolate::optimizing_compile_dispatcher(), options, v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), v8::internal::OptimizingCompileDispatcher::StartTearDown(), unhandled_promise_rejections_, and v8::internal::v8_flags.
RunMainIsolate()
bool v8::Shell::RunMainIsolate (v8::Isolate * isolate, bool keep_context_alive) [static], [private]
Definition at line 6181 of file d8.cc.
                                                                      {
  if (options.lcov_file) {
    debug::Coverage::SelectMode(isolate, debug::CoverageMode::kBlockCount);
  }
  HandleScope scope(isolate);
  Global<Context> global_context;
  {
    Local<Context> context;
    if (!CreateEvaluationContext(isolate).ToLocal(&context)) {
      DCHECK(isolate->IsExecutionTerminating());
      // We must not exit early here in REPRL mode as that would cause the next
      // testcase sent by Fuzzilli to be skipped, which will desynchronize the
      // communication between d8 and Fuzzilli, leading to a crash.
      DCHECK(!fuzzilli_reprl);
      return true;
    }
    global_context.Reset(isolate, context);
    if (keep_context_alive) {
      evaluation_context_.Reset(isolate, context);
    }
  }
  PerIsolateData::RealmScope realm_scope(isolate, global_context);
  InspectorClient inspector_client(isolate, global_context,
                                   options.enable_inspector);
  bool success = true;
  {
    // We cannot use a Context::Scope here, as it keeps a local handle to the
    // context and SourceGroup::Execute may execute a non-nestable task, e.g. a
    // stackless GC.
    global_context.Get(isolate)->Enter();
    if (!options.isolate_sources[0].Execute(isolate)) success = false;
    global_context.Get(isolate)->Exit();
  }
  if (!FinishExecuting(isolate, global_context)) success = false;
  WriteLcovData(isolate, options.lcov_file);
  return success;
}
References DCHECK, v8::anonymous_namespace{d8.cc}::fuzzilli_reprl, v8::PersistentBase< T >::Get(), v8::Isolate::IsExecutionTerminating(), v8::debug::kBlockCount, v8::PersistentBase< T >::Reset(), and v8::debug::Coverage::SelectMode().
RunShell()
void v8::Shell::RunShell (Isolate * isolate) [static], [private]
Definition at line 4943 of file d8.cc.
                                     {
  Global<Context> context;
  {
    HandleScope scope(isolate);
    context.Reset(isolate, Local<Context>::New(isolate, evaluation_context_));
  }
  PerIsolateData::RealmScope realm_scope(isolate, context);
  printf("V8 version %s\n", V8::GetVersion());
  while (true) {
    Global<Value> global_result;
    bool success;
    {
      HandleScope scope(isolate);
      Context::Scope context_scope(context.Get(isolate));
      printf("d8> ");
      Local<String> input = Shell::ReadFromStdin(isolate);
      if (input.IsEmpty()) break;
      Local<String> name = String::NewFromUtf8Literal(isolate, "(d8)");
      success = ExecuteString(isolate, input, name, kReportExceptions,
                              &global_result);
      CHECK_EQ(success, !global_result.IsEmpty());
    }
    if (!FinishExecuting(isolate, context)) success = false;
    if (success) {
      HandleScope scope(isolate);
      Context::Scope context_scope(context.Get(isolate));
      Local<Value> result = global_result.Get(isolate);
      if (options.test_shell) {
        if (!result->IsUndefined()) {
          // If all went well and the result wasn't undefined then print
          // the returned value.
          v8::String::Utf8Value str(isolate, result);
          fwrite(*str, sizeof(**str), str.length(), stdout);
          printf("\n");
        }
      } else {
        v8::String::Utf8Value str(isolate, Stringify(isolate, result));
        fwrite(*str, sizeof(**str), str.length(), stdout);
        printf("\n");
      }
    }
  }
  printf("\n");
}
References CHECK_EQ, v8::PersistentBase< T >::Get(), v8::V8::GetVersion(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::String::Utf8Value::length(), name, v8::String::NewFromUtf8Literal(), ReadFromStdin(), v8::PersistentBase< T >::Reset(), and v8::base::internal::result.
ScheduleTermination()
void v8::Shell::ScheduleTermination (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3692 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  if (SkipTerminationForFuzzing()) return;
  auto v8_isolate = info.GetIsolate();
  // Schedule a termination request, handled by an interrupt later.
  if (!v8_isolate->IsExecutionTerminating()) v8_isolate->TerminateExecution();
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::SkipTerminationForFuzzing(), v8::Isolate::TerminateExecution(), and v8::internal::ValidateCallbackInfo().
SerializerDeserialize()
void v8::Shell::SerializerDeserialize (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2851 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  Local<Context> context = isolate->GetCurrentContext();
  if (!info[0]->IsArrayBuffer()) {
    ThrowError(isolate, "Can only deserialize from an ArrayBuffer");
    return;
  }
  std::shared_ptr<BackingStore> backing_store =
      info[0].As<ArrayBuffer>()->GetBackingStore();
  ValueDeserializer deserializer(
      isolate, static_cast<const uint8_t*>(backing_store->Data()),
      backing_store->ByteLength());
  bool ok;
  if (!deserializer.ReadHeader(context).To(&ok)) return;
  Local<Value> result;
  if (!deserializer.ReadValue(context).ToLocal(&result)) return;
  info.GetReturnValue().Set(result);
}
References DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::ReadValue(), v8::base::internal::result, v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocal(), and v8::internal::ValidateCallbackInfo().
SerializerSerialize()
void v8::Shell::SerializerSerialize (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2828 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  Local<Context> context = isolate->GetCurrentContext();
  ValueSerializer serializer(isolate);
  serializer.WriteHeader();
  for (int i = 0; i < info.Length(); i++) {
    bool ok;
    if (!serializer.WriteValue(context, info[i]).To(&ok)) return;
  }
  Local<v8::ArrayBuffer> buffer;
  {
    std::pair<uint8_t*, size_t> pair = serializer.Release();
    buffer = ArrayBuffer::New(isolate, pair.second);
    memcpy(buffer->GetBackingStore()->Data(), pair.first, pair.second);
    free(pair.first);
  }
  info.GetReturnValue().Set(buffer);
}
References DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::ArrayBuffer::New(), v8::ValueSerializer::Release(), v8::internal::ValidateCallbackInfo(), v8::ValueSerializer::WriteHeader(), and v8::ValueSerializer::WriteValue().
SerializeValue()
std::unique_ptr< SerializationData > v8::Shell::SerializeValue (Isolate * isolate, Local< Value > value, Local< Value > transfer) [static]
Definition at line 6591 of file d8.cc.
                                                                 {
  bool ok;
  Local<Context> context = isolate->GetCurrentContext();
  Serializer serializer(isolate);
  std::unique_ptr<SerializationData> data;
  if (serializer.WriteValue(context, value, transfer).To(&ok)) {
    data = serializer.Release();
  }
  return data;
}
References v8::Isolate::GetCurrentContext(), v8::Serializer::Release(), v8::internal::value, and v8::Serializer::WriteValue().
Referenced by v8::Worker::PostMessageOut(), and WorkerPostMessage().
set_script_executed()
static void v8::Shell::set_script_executed () [inline], [static]
Definition at line 767 of file d8.h.
{ script_executed_.store(true); }
References script_executed_.
Referenced by v8::SourceGroup::Execute().
SetEnvironment()
void v8::Shell::SetEnvironment (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 609 of file d8-posix.cc.
                                                                      {
  DCHECK(i::ValidateCallbackInfo(info));
  if (info.Length() != 2) {
    info.GetIsolate()->ThrowError("setenv() takes two arguments");
    return;
  }
  String::Utf8Value var(info.GetIsolate(), info[0]);
  String::Utf8Value value(info.GetIsolate(), info[1]);
  if (*var == nullptr) {
    info.GetIsolate()->ThrowError(
        "os.setenv(): String conversion of variable name failed.");
    return;
  }
  if (*value == nullptr) {
    info.GetIsolate()->ThrowError(
        "os.setenv(): String conversion of variable contents failed.");
    return;
  }
  setenv(*var, *value, 1);
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::ThrowError(), v8::internal::ValidateCallbackInfo(), and v8::internal::value.
Referenced by AddOSMethods().
SetFlushDenormals()
void v8::Shell::SetFlushDenormals (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2737 of file d8.cc.
                                                                         {
  Isolate* isolate = info.GetIsolate();
  if (i::v8_flags.correctness_fuzzer_suppressions || i::v8_flags.fuzzing) {
    // Setting denormals flushing in the middle of code is almost certain to
    // cause correctness issues or crashes, in a way that isn't interesting to
    // us. Make this a no-op instead.
    return;
  }
  // Check if the argument is a valid function.
  if (info.Length() != 1) {
    ThrowError(isolate, "Expected single boolean argument.");
    return;
  }
  Local<Value> arg = info[0];
  if (!arg->IsBoolean()) {
    ThrowError(isolate, "Expected single boolean argument.");
    return;
  }
  base::FPU::SetFlushDenormals(arg.As<Boolean>()->BooleanValue(isolate));
}
References v8::Local< T >::As(), v8::Value::BooleanValue(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::base::FPU::SetFlushDenormals(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::v8_flags.
Referenced by CreateD8Template().
SetOptions()
bool v8::Shell::SetOptions (int argc, char * argv[]) [static], [private]
Definition at line 5836 of file d8.cc.
                                             {
  bool logfile_per_isolate = false;
  options.d8_path = argv[0];
  for (int i = 0; i < argc; i++) {
    char* flag_value = nullptr;
    if (FlagMatches("--", &argv[i])) {
      i++;
      for (; i < argc; i++) {
        options.arguments.push_back(argv[i]);
        argv[i] = nullptr;
      }
      break;
    } else if (FlagMatches("--no-arguments", &argv[i])) {
      options.include_arguments = false;
    } else if (FlagMatches("--simulate-errors", &argv[i])) {
      options.simulate_errors = true;
    } else if (FlagMatches("--fuzzing", &argv[i], /*keep_flag=*/true) ||
               FlagMatches("--no-abort-on-contradictory-flags", &argv[i],
                           /*keep_flag=*/true) ||
               FlagMatches("--noabort-on-contradictory-flags", &argv[i],
                           /*keep_flag=*/true)) {
      check_d8_flag_contradictions = false;
    } else if (FlagMatches("--abort-on-contradictory-flags", &argv[i],
                           /*keep_flag=*/true)) {
      check_d8_flag_contradictions = true;
    } else if (FlagMatches("--logfile-per-isolate", &argv[i])) {
      logfile_per_isolate = true;
    } else if (FlagMatches("--shell", &argv[i])) {
      options.interactive_shell = true;
    } else if (FlagMatches("--test", &argv[i])) {
      options.test_shell = true;
    } else if (FlagMatches("--notest", &argv[i]) ||
               FlagMatches("--no-test", &argv[i])) {
      options.test_shell = false;
    } else if (FlagMatches("--send-idle-notification", &argv[i])) {
      options.send_idle_notification = true;
    } else if (FlagMatches("--invoke-weak-callbacks", &argv[i])) {
      options.invoke_weak_callbacks = true;
      // TODO(v8:3351): Invoking weak callbacks does not always collect all
      // available garbage.
      options.send_idle_notification = true;
    } else if (FlagMatches("--omit-quit", &argv[i])) {
      options.omit_quit = true;
    } else if (FlagMatches("--no-wait-for-background-tasks", &argv[i])) {
      // TODO(herhut) Remove this flag once wasm compilation is fully
      // isolate-independent.
      options.wait_for_background_tasks = false;
    } else if (FlagMatches("-f", &argv[i], /*keep_flag=*/true)) {
      // Ignore any -f flags for compatibility with other stand-alone
      // JavaScript engines.
      continue;
    } else if (FlagMatches("--ignore-unhandled-promises", &argv[i])) {
      options.ignore_unhandled_promises = true;
    } else if (FlagMatches("--isolate", &argv[i], /*keep_flag=*/true)) {
      options.num_isolates++;
    } else if (FlagMatches("--throws", &argv[i])) {
      options.expected_to_throw = true;
    } else if (FlagMatches("--no-fail", &argv[i])) {
      options.no_fail = true;
    } else if (FlagMatches("--dump-counters", &argv[i])) {
      options.dump_counters = true;
    } else if (FlagMatches("--dump-counters-nvp", &argv[i])) {
      options.dump_counters_nvp = true;
    } else if (FlagMatches("--dump-system-memory-stats", &argv[i])) {
      options.dump_system_memory_stats = true;
    } else if (FlagWithArgMatches("--icu-data-file", &flag_value, argc, argv,
                                  &i)) {
      options.icu_data_file = flag_value;
    } else if (FlagWithArgMatches("--icu-locale", &flag_value, argc, argv,
                                  &i)) {
      options.icu_locale = flag_value;
#ifdef V8_USE_EXTERNAL_STARTUP_DATA
    } else if (FlagWithArgMatches("--snapshot_blob", &flag_value, argc, argv,
                                  &i)) {
      options.snapshot_blob = flag_value;
#endif // V8_USE_EXTERNAL_STARTUP_DATA
    } else if (FlagMatches("--cache", &argv[i]) ||
               FlagWithArgMatches("--cache", &flag_value, argc, argv, &i)) {
      if (!flag_value || strcmp(flag_value, "code") == 0) {
        options.compile_options = v8::ScriptCompiler::kNoCompileOptions;
        options.code_cache_options =
            ShellOptions::CodeCacheOptions::kProduceCache;
      } else if (strcmp(flag_value, "none") == 0) {
        options.compile_options = v8::ScriptCompiler::kNoCompileOptions;
        options.code_cache_options = ShellOptions::kNoProduceCache;
      } else if (strcmp(flag_value, "after-execute") == 0) {
        options.compile_options = v8::ScriptCompiler::kNoCompileOptions;
        options.code_cache_options =
            ShellOptions::CodeCacheOptions::kProduceCacheAfterExecute;
      } else if (strcmp(flag_value, "full-code-cache") == 0) {
        options.compile_options = v8::ScriptCompiler::kEagerCompile;
        options.code_cache_options =
            ShellOptions::CodeCacheOptions::kProduceCache;
      } else {
        fprintf(stderr, "Unknown option to --cache.\n");
        return false;
      }
    } else if (FlagMatches("--streaming-compile", &argv[i])) {
      options.streaming_compile = true;
    } else if ((FlagMatches("--no-streaming-compile", &argv[i])) ||
               (FlagMatches("--nostreaming-compile", &argv[i]))) {
      options.streaming_compile = false;
    } else if (FlagMatches("--enable-tracing", &argv[i])) {
      options.trace_enabled = true;
    } else if (FlagWithArgMatches("--trace-path", &flag_value, argc, argv,
                                  &i)) {
      options.trace_path = flag_value;
    } else if (FlagWithArgMatches("--trace-config", &flag_value, argc, argv,
                                  &i)) {
      options.trace_config = flag_value;
    } else if (FlagMatches("--enable-inspector", &argv[i])) {
      options.enable_inspector = true;
    } else if (FlagWithArgMatches("--lcov", &flag_value, argc, argv, &i)) {
      options.lcov_file = flag_value;
#ifdef V8_OS_LINUX
    } else if (FlagMatches("--scope-linux-perf-to-mark-measure", &argv[i])) {
      options.scope_linux_perf_to_mark_measure = true;
    } else if (FlagWithArgMatches("--perf-ctl-fd", &flag_value, argc, argv,
                                  &i)) {
      options.perf_ctl_fd = atoi(flag_value);
    } else if (FlagWithArgMatches("--perf-ack-fd", &flag_value, argc, argv,
                                  &i)) {
      options.perf_ack_fd = atoi(flag_value);
#endif
    } else if (FlagMatches("--disable-in-process-stack-traces", &argv[i])) {
      options.disable_in_process_stack_traces = true;
#ifdef V8_OS_POSIX
    } else if (FlagWithArgMatches("--read-from-tcp-port", &flag_value, argc,
                                  argv, &i)) {
      options.read_from_tcp_port = atoi(flag_value);
#endif // V8_OS_POSIX
    } else if (FlagMatches("--enable-os-system", &argv[i])) {
      options.enable_os_system = true;
    } else if (FlagMatches("--no-apply-priority", &argv[i])) {
      options.apply_priority = false;
    } else if (FlagMatches("--quiet-load", &argv[i])) {
      options.quiet_load = true;
    } else if (FlagWithArgMatches("--thread-pool-size", &flag_value, argc, argv,
                                  &i)) {
      options.thread_pool_size = atoi(flag_value);
    } else if (FlagMatches("--stress-delay-tasks", &argv[i])) {
      // Delay execution of tasks by 0-100ms randomly (based on --random-seed).
      options.stress_delay_tasks = true;
    } else if (FlagMatches("--cpu-profiler", &argv[i])) {
      options.cpu_profiler = true;
    } else if (FlagMatches("--cpu-profiler-print", &argv[i])) {
      options.cpu_profiler = true;
      options.cpu_profiler_print = true;
    } else if (FlagMatches("--stress-deserialize", &argv[i])) {
      options.stress_deserialize = true;
    } else if (FlagMatches("--compile-only", &argv[i])) {
      options.compile_only = true;
    } else if (FlagWithArgMatches("--repeat-compile", &flag_value, argc, argv,
                                  &i)) {
      options.repeat_compile = atoi(flag_value);
    } else if (FlagWithArgMatches("--max-serializer-memory", &flag_value, argc,
                                  argv, &i)) {
      // Value is expressed in MB.
      options.max_serializer_memory = atoi(flag_value) * i::MB;
#ifdef V8_FUZZILLI
    } else if (FlagMatches("--fuzzilli-enable-builtins-coverage", &argv[i])) {
      options.fuzzilli_enable_builtins_coverage = true;
    } else if (FlagMatches("--fuzzilli-coverage-statistics", &argv[i])) {
      options.fuzzilli_coverage_statistics = true;
#endif
    } else if (FlagMatches("--no-fuzzy-module-file-extensions", &argv[i])) {
      DCHECK(options.fuzzy_module_file_extensions);
      options.fuzzy_module_file_extensions = false;
#if defined(V8_ENABLE_ETW_STACK_WALKING)
    } else if (FlagMatches("--enable-etw-stack-walking", &argv[i])) {
      options.enable_etw_stack_walking = true;
      // This needs to be manually triggered for JIT ETW events to work.
      i::v8_flags.enable_etw_stack_walking = true;
#if defined(V8_ENABLE_SYSTEM_INSTRUMENTATION)
    } else if (FlagMatches("--enable-system-instrumentation", &argv[i])) {
      options.enable_system_instrumentation = true;
      options.trace_enabled = true;
#endif
#if defined(V8_OS_WIN)
      // Guard this bc the flag has a lot of overhead and is not currently used
      // by macos
      i::v8_flags.interpreted_frames_native_stack = true;
#endif
#endif
#if V8_ENABLE_WEBASSEMBLY
    } else if (FlagMatches("--wasm-trap-handler", &argv[i])) {
      options.wasm_trap_handler = true;
    } else if (FlagMatches("--no-wasm-trap-handler", &argv[i])) {
      options.wasm_trap_handler = false;
#endif // V8_ENABLE_WEBASSEMBLY
    } else if (FlagMatches("--expose-fast-api", &argv[i])) {
      options.expose_fast_api = true;
    } else if (FlagMatches("--flush-denormals", &argv[i])) {
      options.flush_denormals = true;
    } else {
#ifdef V8_TARGET_OS_WIN
      PreProcessUnicodeFilenameArg(argv, i);
#endif
    }
  }
#ifdef V8_OS_LINUX
  if (options.scope_linux_perf_to_mark_measure) {
    if (options.perf_ctl_fd == -1 || options.perf_ack_fd == -1) {
      fprintf(stderr,
              "Flag --scope-linux-perf-to-mark-measure requires both "
              "--perf-ctl-fd and --perf-ack-fd\n");
      return false;
    }
    SendPerfControlCommand("disable");
  }
#endif
  const char* usage =
      "Synopsis:\n"
      " shell [options] [--shell] [<file>...]\n"
      " d8 [options] [-e <string>] [--shell] [--module|]"
      " <file>...]\n\n"
      " -e execute a string in V8\n"
      " --shell run an interactive JavaScript shell\n"
      " --module execute a file as a JavaScript module\n";
  using HelpOptions = i::FlagList::HelpOptions;
  i::v8_flags.abort_on_contradictory_flags = true;
  i::FlagList::SetFlagsFromCommandLine(&argc, argv, true,
                                       HelpOptions(HelpOptions::kExit, usage));
  i::FlagList::ResolveContradictionsWhenFuzzing();
  options.mock_arraybuffer_allocator = i::v8_flags.mock_arraybuffer_allocator;
  options.mock_arraybuffer_allocator_limit =
      i::v8_flags.mock_arraybuffer_allocator_limit;
#ifdef V8_OS_LINUX
  options.multi_mapped_mock_allocator = i::v8_flags.multi_mapped_mock_allocator;
#endif // V8_OS_LINUX
  if (i::v8_flags.stress_snapshot && options.expose_fast_api &&
      check_d8_flag_contradictions) {
    FATAL("Flag --expose-fast-api is incompatible with --stress-snapshot.");
  }
  // Set up isolated source groups.
  options.isolate_sources = new SourceGroup[options.num_isolates];
  internal::g_num_isolates_for_testing = options.num_isolates;
  SourceGroup* current = options.isolate_sources;
  current->Begin(argv, 1);
  for (int i = 1; i < argc; i++) {
    const char* str = argv[i];
    if (strcmp(str, "--isolate") == 0) {
      current->End(i);
      current++;
      current->Begin(argv, i + 1);
    } else if (strcmp(str, "--module") == 0 || strcmp(str, "--json") == 0) {
      // Pass on to SourceGroup, which understands these options.
    } else if (strncmp(str, "--", 2) == 0) {
      if (!i::v8_flags.correctness_fuzzer_suppressions) {
        printf("Warning: unknown flag %s.\nTry --help for options\n", str);
      }
    } else if (strcmp(str, "-e") == 0 && i + 1 < argc) {
      set_script_executed();
    } else if (strncmp(str, "-", 1) != 0) {
      // Not a flag, so it must be a script to execute.
      set_script_executed();
    }
  }
  current->End(argc);
  if (!logfile_per_isolate && options.num_isolates) {
    V8::SetFlagsFromString("--no-logfile-per-isolate");
  }
  return true;
}
References v8::SourceGroup::Begin(), v8::check_d8_flag_contradictions, DCHECK, v8::SourceGroup::End(), FATAL, v8::anonymous_namespace{d8.cc}::FlagMatches(), v8::anonymous_namespace{d8.cc}::FlagWithArgMatches(), v8::internal::g_num_isolates_for_testing, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::ScriptCompiler::kEagerCompile, v8::ScriptCompiler::kNoCompileOptions, v8::ShellOptions::kNoProduceCache, MB, v8::internal::FlagList::ResolveContradictionsWhenFuzzing(), v8::internal::FlagList::SetFlagsFromCommandLine(), v8::V8::SetFlagsFromString(), and v8::internal::v8_flags.
SetPromiseHooks()
void v8::Shell::SetPromiseHooks (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2797 of file d8.cc.
                                                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  if (i::v8_flags.correctness_fuzzer_suppressions) {
    // Setting promise hooks dynamically has unexpected timing side-effects
    // with certain promise optimizations. We might not get all callbacks for
    // previously scheduled Promises or optimized code-paths that skip Promise
    // creation.
    ThrowError(isolate,
               "d8.promise.setHooks is disabled with "
               "--correctness-fuzzer-suppressions");
    return;
  }
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  Local<Context> context = isolate->GetCurrentContext();
  HandleScope handle_scope(isolate);
  context->SetPromiseHooks(
      info[0]->IsFunction() ? info[0].As<Function>() : Local<Function>(),
      info[1]->IsFunction() ? info[1].As<Function>() : Local<Function>(),
      info[2]->IsFunction() ? info[2].As<Function>() : Local<Function>(),
      info[3]->IsFunction() ? info[3].As<Function>() : Local<Function>());
  info.GetReturnValue().Set(v8::Undefined(isolate));
#else // V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  ThrowError(isolate,
             "d8.promise.setHooks is disabled due to missing build flag "
             "v8_enabale_javascript_in_promise_hooks");
#endif // V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
}
References DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Context::SetPromiseHooks(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::Undefined(), v8::internal::v8_flags, and v8::internal::ValidateCallbackInfo().
SetTimeout()
void v8::Shell::SetTimeout (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3173 of file d8.cc.
                                                                  {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  info.GetReturnValue().Set(v8::Number::New(isolate, 0));
  if (info.Length() == 0 || !info[0]->IsFunction()) return;
  Local<Function> callback = info[0].As<Function>();
  Local<Context> context = isolate->GetCurrentContext();
  g_platform->GetForegroundTaskRunner(isolate)->PostTask(
      std::make_unique<SetTimeoutTask>(isolate, context, callback));
}
References DCHECK, v8::anonymous_namespace{d8.cc}::g_platform, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), and v8::internal::ValidateCallbackInfo().
SetUMask()
void v8::Shell::SetUMask (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 511 of file d8-posix.cc.
                                                                {
  DCHECK(i::ValidateCallbackInfo(info));
  if (info.Length() != 1) {
    info.GetIsolate()->ThrowError("umask() takes one argument");
    return;
  }
  if (info[0]->IsNumber()) {
    int previous = umask(
        info[0]->Int32Value(info.GetIsolate()->GetCurrentContext()).FromJust());
    info.GetReturnValue().Set(previous);
    return;
  } else {
    info.GetIsolate()->ThrowError("umask() argument must be numeric");
    return;
  }
}
References DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::IsNumber(), v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by AddOSMethods().
SetWaitUntilDone()
static void v8::Shell::SetWaitUntilDone (Isolate * isolate, bool value) [static]
StoreInCodeCache()
void v8::Shell::StoreInCodeCache (Isolate * isolate, Local< Value > name, const ScriptCompiler::CachedData * data) [static], [private]
Definition at line 581 of file d8.cc.
                                                                         {
  i::ParkedMutexGuard lock_guard(
      reinterpret_cast<i::Isolate*>(isolate)->main_thread_local_isolate(),
      cached_code_mutex_.Pointer());
  CHECK(source->IsString());
  if (cache_data == nullptr) return;
  v8::String::Utf8Value key(isolate, source);
  DCHECK(*key);
  int length = cache_data->length;
  uint8_t* cache = new uint8_t[length];
  memcpy(cache, cache_data->data, length);
  cached_code_map_[*key] = std::unique_ptr<ScriptCompiler::CachedData>(
      new ScriptCompiler::CachedData(cache, length,
                                     ScriptCompiler::CachedData::BufferOwned));
}
References v8::ScriptCompiler::CachedData::BufferOwned, cached_code_map_, cached_code_mutex_, CHECK, v8::ScriptCompiler::CachedData::data, DCHECK, v8::internal::key, v8::ScriptCompiler::CachedData::length, v8::internal::length, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by ExecuteString().
Stringify()
Local< String > v8::Shell::Stringify (Isolate * isolate, Local< Value > value) [static], [private]
Definition at line 3870 of file d8.cc.
                                                                   {
  v8::Local<v8::Context> context =
      v8::Local<v8::Context>::New(isolate, evaluation_context_);
  if (stringify_function_.IsEmpty()) {
    Local<String> source =
        String::NewFromUtf8(isolate, stringify_source_).ToLocalChecked();
    Local<String> name = String::NewFromUtf8Literal(isolate, "d8-stringify");
    ScriptOrigin origin(name);
    Local<Script> script =
        Script::Compile(context, source, &origin).ToLocalChecked();
    stringify_function_.Reset(
        isolate, script->Run(context).ToLocalChecked().As<Function>());
  }
  Local<Function> fun = Local<Function>::New(isolate, stringify_function_);
  Local<Value> argv[1] = {value};
  v8::TryCatch try_catch(isolate);
  MaybeLocal<Value> result = fun->Call(context, Undefined(isolate), 1, argv);
  if (result.IsEmpty()) return String::Empty(isolate);
  return result.ToLocalChecked().As<String>();
}
References v8::Script::Compile(), v8::String::Empty(), name, v8::Local< T >::New(), v8::String::NewFromUtf8(), v8::String::NewFromUtf8Literal(), v8::base::internal::result, v8::internal::script, v8::Undefined(), and v8::internal::value.
System()
void v8::Shell::System (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 417 of file d8-posix.cc.
                                                              {
  DCHECK(i::ValidateCallbackInfo(info));
  HandleScope scope(info.GetIsolate());
  int read_timeout = -1;
  int total_timeout = -1;
  if (!GetTimeouts(info, &read_timeout, &total_timeout)) return;
  Local<Array> command_args;
  if (info.Length() > 1) {
    if (!info[1]->IsArray()) {
      info.GetIsolate()->ThrowError("system: Argument 2 must be an array");
      return;
    }
    command_args = info[1].As<Array>();
  } else {
    command_args = Array::New(info.GetIsolate(), 0);
  }
  if (command_args->Length() > ExecArgs::kMaxArgs) {
    info.GetIsolate()->ThrowError("Too many arguments to system()");
    return;
  }
  if (info.Length() < 1) {
    info.GetIsolate()->ThrowError("Too few arguments to system()");
    return;
  }
  struct timeval start_time;
  gettimeofday(&start_time, nullptr);
  ExecArgs exec_args;
  if (!exec_args.Init(info.GetIsolate(), info[0], command_args)) {
    return;
  }
  int exec_error_fds[2];
  int stdout_fds[2];
  if (pipe(exec_error_fds) != 0) {
    info.GetIsolate()->ThrowError("pipe syscall failed.");
    return;
  }
  if (pipe(stdout_fds) != 0) {
    info.GetIsolate()->ThrowError("pipe syscall failed.");
    return;
  }
  pid_t pid = fork();
  if (pid == 0) { // Child process.
    ExecSubprocess(exec_error_fds, stdout_fds, exec_args);
    exit(1);
  }
  // Parent process. Ensure that we clean up if we exit this function early.
  ZombieProtector child_waiter(pid);
  close(exec_error_fds[kWriteFD]);
  close(stdout_fds[kWriteFD]);
  OpenFDCloser error_read_closer(exec_error_fds[kReadFD]);
  OpenFDCloser stdout_read_closer(stdout_fds[kReadFD]);
  Isolate* isolate = info.GetIsolate();
  if (!ChildLaunchedOK(isolate, exec_error_fds)) return;
  Local<Value> accumulator = GetStdout(isolate, stdout_fds[kReadFD], start_time,
                                       read_timeout, total_timeout);
  if (accumulator->IsUndefined()) {
    kill(pid, SIGINT); // On timeout, kill the subprocess.
    info.GetReturnValue().Set(accumulator);
    return;
  }
  if (!WaitForChild(isolate, pid, child_waiter, start_time, read_timeout,
                    total_timeout)) {
    return;
  }
  info.GetReturnValue().Set(accumulator);
}
References v8::ChildLaunchedOK(), DCHECK, v8::ExecSubprocess(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::GetStdout(), v8::GetTimeouts(), v8::ExecArgs::Init(), v8::ExecArgs::kMaxArgs, v8::kReadFD, v8::kWriteFD, v8::FunctionCallbackInfo< T >::Length(), v8::Array::New(), v8::Isolate::ThrowError(), v8::internal::ValidateCallbackInfo(), and v8::WaitForChild().
Referenced by AddOSMethods().
TerminateNow()
void v8::Shell::TerminateNow (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3681 of file d8.cc.
                                                                    {
  DCHECK(i::ValidateCallbackInfo(info));
  if (SkipTerminationForFuzzing()) return;
  auto v8_isolate = info.GetIsolate();
  if (!v8_isolate->IsExecutionTerminating()) {
    // Force a termination exception for immediate termination.
    i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(info.GetIsolate());
    i_isolate->TerminateExecution();
  }
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::SkipTerminationForFuzzing(), v8::internal::Isolate::TerminateExecution(), and v8::internal::ValidateCallbackInfo().
TestVerifySourcePositions()
void v8::Shell::TestVerifySourcePositions (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2629 of file d8.cc.
                                                 {
  Isolate* isolate = info.GetIsolate();
  // Check if the argument is a valid function.
  if (info.Length() != 1) {
    ThrowError(isolate, "Expected function as single argument.");
    return;
  }
  auto arg_handle = Utils::OpenHandle(*info[0]);
  if (!IsHeapObject(*arg_handle) ||
      !IsJSFunctionOrBoundFunctionOrWrappedFunction(
          *i::Cast<i::HeapObject>(arg_handle))) {
    ThrowError(isolate, "Expected function as single argument.");
    return;
  }
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  HandleScope handle_scope(isolate);
  auto callable =
      i::Cast<i::JSFunctionOrBoundFunctionOrWrappedFunction>(arg_handle);
  while (IsJSBoundFunction(*callable)) {
    internal::DisallowGarbageCollection no_gc;
    auto bound_function = i::Cast<i::JSBoundFunction>(callable);
    auto bound_target = bound_function->bound_target_function();
    if (!IsJSFunctionOrBoundFunctionOrWrappedFunction(bound_target)) {
      internal::AllowGarbageCollection allow_gc;
      ThrowError(isolate, "Expected function as bound target.");
      return;
    }
    callable = handle(
        i::Cast<i::JSFunctionOrBoundFunctionOrWrappedFunction>(bound_target),
        i_isolate);
  }
  i::DirectHandle<i::JSFunction> function = i::Cast<i::JSFunction>(callable);
  if (!function->shared()->HasBytecodeArray()) {
    ThrowError(isolate, "Function has no BytecodeArray attached.");
    return;
  }
  i::Handle<i::BytecodeArray> bytecodes =
      handle(function->shared()->GetBytecodeArray(i_isolate), i_isolate);
  i::interpreter::BytecodeArrayIterator bytecode_iterator(bytecodes);
  bool has_baseline = function->shared()->HasBaselineCode();
  i::Handle<i::TrustedByteArray> bytecode_offsets;
  std::unique_ptr<i::baseline::BytecodeOffsetIterator> offset_iterator;
  if (has_baseline) {
    bytecode_offsets = handle(
        i::Cast<i::TrustedByteArray>(
            function->shared()->GetCode(i_isolate)->bytecode_offset_table()),
        i_isolate);
    offset_iterator = std::make_unique<i::baseline::BytecodeOffsetIterator>(
        bytecode_offsets, bytecodes);
    // A freshly initiated BytecodeOffsetIterator points to the prologue.
    DCHECK_EQ(offset_iterator->current_pc_start_offset(), 0);
    DCHECK_EQ(offset_iterator->current_bytecode_offset(),
              i::kFunctionEntryBytecodeOffset);
    offset_iterator->Advance();
  }
  while (!bytecode_iterator.done()) {
    if (has_baseline) {
      if (offset_iterator->current_bytecode_offset() !=
          bytecode_iterator.current_offset()) {
        ThrowError(isolate, "Baseline bytecode offset mismatch.");
        return;
      }
      // Check that we map every address to this bytecode correctly.
      // The start address is exclusive and the end address inclusive.
      for (i::Address pc = offset_iterator->current_pc_start_offset() + 1;
           pc <= offset_iterator->current_pc_end_offset(); ++pc) {
        i::baseline::BytecodeOffsetIterator pc_lookup(bytecode_offsets,
                                                      bytecodes);
        pc_lookup.AdvanceToPCOffset(pc);
        if (pc_lookup.current_bytecode_offset() !=
            bytecode_iterator.current_offset()) {
          ThrowError(isolate,
                     "Baseline bytecode offset mismatch for PC lookup.");
          return;
        }
      }
    }
    bytecode_iterator.Advance();
    if (has_baseline && !bytecode_iterator.done()) {
      if (offset_iterator->done()) {
        ThrowError(isolate, "Missing bytecode(s) in baseline offset mapping.");
        return;
      }
      offset_iterator->Advance();
    }
  }
  if (has_baseline && !offset_iterator->done()) {
    ThrowError(isolate, "Excess offsets in baseline offset mapping.");
    return;
  }
}
References DCHECK_EQ, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::internal::handle(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::kFunctionEntryBytecodeOffset, v8::FunctionCallbackInfo< T >::Length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenHandle(), and v8::anonymous_namespace{d8.cc}::ThrowError().
TriggerOnProfileEndListener()
void v8::Shell::TriggerOnProfileEndListener (Isolate * isolate, std::string profile) [static]
Definition at line 2922 of file d8.cc.
                                                                           {
  CHECK(HasOnProfileEndListener(isolate));
  Local<Function> callback;
  Local<Context> context;
  Local<Value> argv[1] = {
      String::NewFromUtf8(isolate, profile.c_str()).ToLocalChecked()};
  {
    base::MutexGuard lock_guard(&profiler_end_callback_lock_);
    auto& callback_pair = profiler_end_callback_[isolate];
    callback = callback_pair.first.Get(isolate);
    context = callback_pair.second.Get(isolate);
  }
  TryCatch try_catch(isolate);
  try_catch.SetVerbose(true);
  USE(callback->Call(context, Undefined(isolate), 1, argv));
}
References CHECK, v8::String::NewFromUtf8(), v8::TryCatch::SetVerbose(), v8::Undefined(), and USE.
Referenced by v8::D8Console::ProfileEnd().
UnsetEnvironment()
void v8::Shell::UnsetEnvironment (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 630 of file d8-posix.cc.
                                                                        {
  DCHECK(i::ValidateCallbackInfo(info));
  if (info.Length() != 1) {
    info.GetIsolate()->ThrowError("unsetenv() takes one argument");
    return;
  }
  String::Utf8Value var(info.GetIsolate(), info[0]);
  if (*var == nullptr) {
    info.GetIsolate()->ThrowError(
        "os.setenv(): String conversion of variable name failed.");
    return;
  }
  unsetenv(*var);
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Referenced by AddOSMethods().
update_script_size()
static void v8::Shell::update_script_size (int size) [inline], [static]
Definition at line 773 of file d8.h.
                                           {
    if (size > 0) valid_fuzz_script_.store(true);
  }
References size(), and valid_fuzz_script_.
Referenced by v8::SourceGroup::Execute().
use_interactive_shell()
static bool v8::Shell::use_interactive_shell () [inline], [static]
Definition at line 768 of file d8.h.
                                      {
    return (options.interactive_shell || !script_executed_.load()) &&
           !options.test_shell;
  }
References v8::ShellOptions::interactive_shell, options, script_executed_, and v8::ShellOptions::test_shell.
Version()
void v8::Shell::Version (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3707 of file d8.cc.
                                                               {
  DCHECK(i::ValidateCallbackInfo(info));
  info.GetReturnValue().Set(
      String::NewFromUtf8(info.GetIsolate(), V8::GetVersion())
          .ToLocalChecked());
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::V8::GetVersion(), v8::String::NewFromUtf8(), and v8::internal::ValidateCallbackInfo().
WaitForRunningWorkers()
void v8::Shell::WaitForRunningWorkers (const i::ParkedScope & parked) [static]
Definition at line 6621 of file d8.cc.
                                                            {
  // Make a copy of running_workers_, because we don't want to call
  // Worker::Terminate while holding the workers_mutex_ lock. Otherwise, if a
  // worker is about to create a new Worker, it would deadlock.
  std::unordered_set<std::shared_ptr<Worker>> workers_copy;
  {
    base::MutexGuard lock_guard(workers_mutex_.Pointer());
    allow_new_workers_ = false;
    workers_copy.swap(running_workers_);
  }
  for (auto& worker : workers_copy) {
    worker->TerminateAndWaitForThread(parked);
  }
  // Now that all workers are terminated, we can re-enable Worker creation.
  base::MutexGuard lock_guard(workers_mutex_.Pointer());
  DCHECK(running_workers_.empty());
  allow_new_workers_ = true;
}
References DCHECK.
WaitUntilDone()
static void v8::Shell::WaitUntilDone (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
WasmLoadSourceMapCallback()
Local< String > v8::Shell::WasmLoadSourceMapCallback (Isolate * isolate, const char * name) [static]
Definition at line 4357 of file d8.cc.
                                                                 {
  return Shell::ReadFile(isolate, path, false).ToLocalChecked();
}
References ReadFile().
Referenced by CreateEvaluationContext().
WorkerGetMessage()
void v8::Shell::WorkerGetMessage (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3436 of file d8.cc.
                                                                        {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  std::shared_ptr<Worker> worker =
      GetWorkerFromInternalField(isolate, info.This());
  if (!worker.get()) {
    return;
  }
  std::unique_ptr<SerializationData> data = worker->GetMessage(isolate);
  if (data) {
    Local<Value> value;
    if (Shell::DeserializeValue(isolate, std::move(data)).ToLocal(&value)) {
      info.GetReturnValue().Set(value);
    }
  }
}
References DCHECK, DeserializeValue(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::FunctionCallbackInfo< T >::This(), v8::internal::ValidateCallbackInfo(), and v8::internal::value.
WorkerNew()
void v8::Shell::WorkerNew (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3337 of file d8.cc.
                                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  if (info.Length() < 1 || (!info[0]->IsString() && !info[0]->IsFunction())) {
    ThrowError(isolate, "1st argument must be a string or a function");
    return;
  }
  Local<String> source;
  if (!ReadSource(info, 0, CodeType::kFileName).ToLocal(&source)) {
    ThrowError(isolate, "Invalid argument");
    return;
  }
  if (!info.IsConstructCall()) {
    ThrowError(isolate, "Worker must be constructed with new");
    return;
  }
  // Initialize the embedder field to 0; if we return early without
  // creating a new Worker (because the main thread is terminating) we can
  // early-out from the instance calls.
  info.This()->SetInternalField(0, v8::Integer::New(isolate, 0));
  // By default, propagate flush denormals state.
  bool flush_denormals = base::FPU::GetFlushDenormals();
  if (info.Length() > 1 && info[1]->IsObject()) {
    Local<Value> value;
    if (!TryGetValue(isolate, isolate->GetCurrentContext(),
                     info[1].As<Object>(), "flushDenormals")
             .ToLocal(&value)) {
      return;
    }
    if (!value->IsUndefined()) {
      flush_denormals = value->BooleanValue(isolate);
    }
  }
  {
    // Don't allow workers to create more workers if the main thread
    // is waiting for existing running workers to terminate.
    i::ParkedMutexGuard lock_guard(
        reinterpret_cast<i::Isolate*>(isolate)->main_thread_local_isolate(),
        workers_mutex_.Pointer());
    if (!allow_new_workers_) return;
    String::Utf8Value script(isolate, source);
    if (!*script) {
      ThrowError(isolate, "Can't get worker script");
      return;
    }
    // The C++ worker object's lifetime is shared between the Managed<Worker>
    // object on the heap, which the JavaScript object points to, and an
    // internal std::shared_ptr in the worker thread itself.
    auto worker = std::make_shared<Worker>(isolate, *script, flush_denormals);
    i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
    const size_t kWorkerSizeEstimate = 4 * 1024 * 1024; // stack + heap.
    i::DirectHandle<i::Object> managed =
        i::Managed<Worker>::From(i_isolate, kWorkerSizeEstimate, worker);
    info.This()->SetInternalField(0, Utils::ToLocal(managed));
    base::Thread::Priority priority =
        options.apply_priority ? base::Thread::Priority::kUserBlocking
                               : base::Thread::Priority::kDefault;
    if (!Worker::StartWorkerThread(isolate, worker, priority)) {
      ThrowError(isolate, "Can't start thread");
      return;
    }
    PerIsolateData::Get(isolate)->RegisterWorker(worker);
  }
}
References DCHECK, v8::internal::Managed< CppType >::From(), v8::PerIsolateData::Get(), v8::Isolate::GetCurrentContext(), v8::base::FPU::GetFlushDenormals(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::IsConstructCall(), v8::base::Thread::kDefault, v8::base::Thread::kUserBlocking, v8::FunctionCallbackInfo< T >::Length(), v8::Integer::New(), v8::PerIsolateData::RegisterWorker(), v8::internal::script, v8::Object::SetInternalField(), v8::Worker::StartWorkerThread(), v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::MaybeLocal< T >::ToLocal(), v8::anonymous_namespace{d8.cc}::TryGetValue(), v8::internal::ValidateCallbackInfo(), and v8::internal::value.
WorkerOnMessageGetter()
void v8::Shell::WorkerOnMessageGetter (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3564 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  std::shared_ptr<Worker> worker =
      GetWorkerFromInternalField(isolate, info.This());
  if (!worker.get()) {
    return;
  }
  Local<Function> callback =
      PerIsolateData::Get(isolate)->GetWorkerOnMessage(worker).second;
  if (!callback.IsEmpty()) {
    info.GetReturnValue().Set(callback);
  }
}
References DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::PerIsolateData::GetWorkerOnMessage(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
WorkerOnMessageSetter()
void v8::Shell::WorkerOnMessageSetter (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3583 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  if (info.Length() < 1) {
    ThrowError(isolate, "Invalid argument");
    return;
  }
  std::shared_ptr<Worker> worker =
      GetWorkerFromInternalField(isolate, info.This());
  if (!worker.get()) {
    return;
  }
  Local<Value> callback = info[0];
  if (!callback->IsFunction()) return;
  PerIsolateData::Get(isolate)->SubscribeWorkerOnMessage(
      worker, isolate->GetCurrentContext(), Local<Function>::Cast(callback));
}
References DCHECK, v8::PerIsolateData::Get(), v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::FunctionCallbackInfo< T >::Length(), v8::PerIsolateData::SubscribeWorkerOnMessage(), v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{d8.cc}::ThrowError(), and v8::internal::ValidateCallbackInfo().
WorkerPostMessage()
void v8::Shell::WorkerPostMessage (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3410 of file d8.cc.
                                                                         {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  if (info.Length() < 1) {
    ThrowError(isolate, "Invalid argument");
    return;
  }
  std::shared_ptr<Worker> worker =
      GetWorkerFromInternalField(isolate, info.This());
  if (!worker.get()) {
    return;
  }
  Local<Value> message = info[0];
  Local<Value> transfer =
      info.Length() >= 2 ? info[1] : Undefined(isolate).As<Value>();
  std::unique_ptr<SerializationData> data =
      Shell::SerializeValue(isolate, message, transfer);
  if (data) {
    worker->PostMessage(std::move(data));
  }
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::FunctionCallbackInfo< T >::Length(), SerializeValue(), v8::FunctionCallbackInfo< T >::This(), v8::anonymous_namespace{d8.cc}::ThrowError(), v8::Undefined(), and v8::internal::ValidateCallbackInfo().
WorkerTerminate()
void v8::Shell::WorkerTerminate (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3607 of file d8.cc.
                                                                       {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  std::shared_ptr<Worker> worker =
      GetWorkerFromInternalField(isolate, info.This());
  if (!worker.get()) return;
  worker->Terminate();
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
WorkerTerminateAndWait()
void v8::Shell::WorkerTerminateAndWait (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 3617 of file d8.cc.
                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  Isolate* isolate = info.GetIsolate();
  HandleScope handle_scope(isolate);
  std::shared_ptr<Worker> worker =
      GetWorkerFromInternalField(isolate, info.This());
  if (!worker.get()) {
    return;
  }
  reinterpret_cast<i::Isolate*>(isolate)
      ->main_thread_local_isolate()
      ->ExecuteMainThreadWhileParked([worker](const i::ParkedScope& parked) {
        worker->TerminateAndWaitForThread(parked);
      });
}
References DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
WriteChars()
void v8::Shell::WriteChars (const char * name, uint8_t * buffer, size_t buffer_size) [static]
Definition at line 4936 of file d8.cc.
                                                                            {
  FILE* file = base::Fopen(name, "w");
  if (file == nullptr) return;
  fwrite(buffer, 1, buffer_size, file);
  base::Fclose(file);
}
References v8::base::Fclose(), file(), v8::base::Fopen(), and name.
WriteFile()
void v8::Shell::WriteFile (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2999 of file d8.cc.
                                                                 {
  DCHECK(i::ValidateCallbackInfo(info));
  String::Utf8Value file_name(info.GetIsolate(), info[0]);
  if (*file_name == nullptr) {
    ThrowError(info.GetIsolate(), "Error converting filename to string");
    return;
  }
  FILE* file;
  if (info.Length() == 2 &&
      (info[1]->IsArrayBuffer() || info[1]->IsArrayBufferView())) {
    file = base::Fopen(*file_name, "wb");
    if (file == nullptr) {
      ThrowError(info.GetIsolate(), "Error opening file");
      return;
    }
    void* data;
    size_t length;
    if (info[1]->IsArrayBuffer()) {
      Local<v8::ArrayBuffer> buffer = Local<v8::ArrayBuffer>::Cast(info[1]);
      length = buffer->ByteLength();
      data = buffer->Data();
    } else {
      Local<v8::ArrayBufferView> buffer_view =
          Local<v8::ArrayBufferView>::Cast(info[1]);
      length = buffer_view->ByteLength();
      data = static_cast<uint8_t*>(buffer_view->Buffer()->Data()) +
             buffer_view->ByteOffset();
    }
    fwrite(data, 1, length, file);
  } else {
    file = base::Fopen(*file_name, "w");
    if (file == nullptr) {
      ThrowError(info.GetIsolate(), "Error opening file");
      return;
    }
    WriteToFile(file, info, 1);
  }
  base::Fclose(file);
}
References v8::Local< T >::Cast(), DCHECK, v8::base::Fclose(), file(), v8::base::Fopen(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::internal::length, v8::anonymous_namespace{d8.cc}::ThrowError(), v8::internal::ValidateCallbackInfo(), and v8::WriteToFile().
WriteIgnitionDispatchCountersFile()
void v8::Shell::WriteIgnitionDispatchCountersFile (v8::Isolate * isolate) [static], [private]
Definition at line 4407 of file d8.cc.
                                                                {
  HandleScope handle_scope(isolate);
  Local<Context> context = Context::New(isolate);
  Context::Scope context_scope(context);
  i::DirectHandle<i::JSObject> dispatch_counters =
      reinterpret_cast<i::Isolate*>(isolate)
          ->interpreter()
          ->GetDispatchCountersObject();
  std::ofstream dispatch_counters_stream(
      i::v8_flags.trace_ignition_dispatches_output_file);
  dispatch_counters_stream << *String::Utf8Value(
      isolate, JSON::Stringify(context, Utils::ToLocal(dispatch_counters))
                   .ToLocalChecked());
}
References v8::Context::New(), v8::JSON::Stringify(), and v8::internal::v8_flags.
WriteLcovData()
void v8::Shell::WriteLcovData (v8::Isolate * isolate, const char * file) [static], [private]
Definition at line 4570 of file d8.cc.
                                                              {
  if (!file) return;
#if V8_ENABLE_WEBASSEMBLY
  if (i::v8_flags.wasm_code_coverage) {
    WriteWasmLcovData(isolate, file);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  HandleScope handle_scope(isolate);
  debug::Coverage coverage = debug::Coverage::CollectPrecise(isolate);
  std::ofstream sink(file, std::ofstream::app);
  for (size_t i = 0; i < coverage.ScriptCount(); i++) {
    debug::Coverage::ScriptData script_data = coverage.GetScriptData(i);
    Local<debug::Script> script = script_data.GetScript();
    // Skip unnamed scripts.
    Local<String> name;
    if (!script->Name().ToLocal(&name)) continue;
    std::string file_name = ToSTLString(isolate, name);
    // Skip scripts not backed by a file.
    if (!std::ifstream(file_name).good()) continue;
    sink << "SF:";
    sink << NormalizePath(file_name, GetWorkingDirectory()) << std::endl;
    std::vector<uint32_t> lines;
    for (size_t j = 0; j < script_data.FunctionCount(); j++) {
      debug::Coverage::FunctionData function_data =
          script_data.GetFunctionData(j);
      // Write function stats.
      {
        debug::Location start =
            script->GetSourceLocation(function_data.StartOffset());
        debug::Location end =
            script->GetSourceLocation(function_data.EndOffset());
        int start_line = start.GetLineNumber();
        int end_line = end.GetLineNumber();
        uint32_t count = function_data.Count();
        Local<String> function_name;
        std::stringstream name_stream;
        if (function_data.Name().ToLocal(&function_name)) {
          name_stream << ToSTLString(isolate, function_name);
        } else {
          name_stream << "<" << start_line + 1 << "-";
          name_stream << start.GetColumnNumber() << ">";
        }
        WriteLcovDataForNamedRange(sink, &lines, name_stream.str(), start_line,
                                   end_line, count);
      }
      // Process inner blocks.
      for (size_t k = 0; k < function_data.BlockCount(); k++) {
        debug::Coverage::BlockData block_data = function_data.GetBlockData(k);
        int start_line = LineFromOffset(script, block_data.StartOffset());
        int end_line = LineFromOffset(script, block_data.EndOffset() - 1);
        uint32_t count = block_data.Count();
        WriteLcovDataForRange(&lines, start_line, end_line, count);
      }
    }
    // Write per-line coverage. LCOV uses 1-based line numbers.
    for (size_t j = 0; j < lines.size(); j++) {
      sink << "DA:" << (j + 1) << "," << lines[j] << std::endl;
    }
    sink << "end_of_record" << std::endl;
  }
}
References v8::debug::Coverage::FunctionData::BlockCount(), v8::debug::Coverage::CollectPrecise(), v8::debug::Coverage::BlockData::Count(), v8::debug::Coverage::FunctionData::Count(), v8::internal::compiler::end(), v8::debug::Coverage::BlockData::EndOffset(), v8::debug::Coverage::FunctionData::EndOffset(), file(), v8::debug::Coverage::ScriptData::FunctionCount(), v8::debug::Coverage::FunctionData::GetBlockData(), v8::debug::Location::GetColumnNumber(), v8::debug::Coverage::ScriptData::GetFunctionData(), v8::debug::Location::GetLineNumber(), v8::debug::Coverage::ScriptData::GetScript(), v8::debug::Coverage::GetScriptData(), v8::anonymous_namespace{d8.cc}::GetWorkingDirectory(), v8::anonymous_namespace{d8.cc}::LineFromOffset(), v8::debug::Coverage::FunctionData::Name(), name, v8::anonymous_namespace{d8.cc}::NormalizePath(), v8::internal::script, v8::debug::Coverage::ScriptCount(), v8::debug::Coverage::BlockData::StartOffset(), v8::debug::Coverage::FunctionData::StartOffset(), v8::internal::string, v8::anonymous_namespace{d8.cc}::ToSTLString(), v8::internal::v8_flags, v8::anonymous_namespace{d8.cc}::WriteLcovDataForNamedRange(), and v8::anonymous_namespace{d8.cc}::WriteLcovDataForRange().
WriteStdout()
void v8::Shell::WriteStdout (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 2986 of file d8.cc.
                                                                   {
  WriteToFile(stdout, info);
}
References v8::WriteToFile().
Member Data Documentation
allow_new_workers_
bool v8::Shell::allow_new_workers_ = true [static], [private]
Definition at line 812 of file d8.h.
array_buffer_allocator
ArrayBuffer::Allocator * v8::Shell::array_buffer_allocator [static]
Definition at line 761 of file d8.h.
Referenced by v8::SourceGroup::ExecuteInThread(), v8::Worker::ExecuteInThread(), and Main().
cached_code_map_
std::map< std::string, std::unique_ptr< ScriptCompiler::CachedData > > v8::Shell::cached_code_map_ [static], [private]
Definition at line 878 of file d8.h.
Referenced by LookupCodeCache(), and StoreInCodeCache().
cached_code_mutex_
base::LazyMutex v8::Shell::cached_code_mutex_ [static], [private]
Definition at line 876 of file d8.h.
Referenced by LookupCodeCache(), and StoreInCodeCache().
context_mutex_
base::LazyMutex v8::Shell::context_mutex_ [static], [private]
Definition at line 808 of file d8.h.
counter_map_
CounterMap * v8::Shell::counter_map_ [static], [private]
Definition at line 801 of file d8.h.
Referenced by Main().
counter_mutex_
base::Mutex v8::Shell::counter_mutex_ [static], [private]
Definition at line 802 of file d8.h.
counters_
CounterCollection * v8::Shell::counters_ = &local_counters_ [static], [private]
Definition at line 806 of file d8.h.
counters_file_
base::OS::MemoryMappedFile * v8::Shell::counters_file_ = nullptr [static], [private]
Definition at line 807 of file d8.h.
evaluation_context_
Global< Context > v8::Shell::evaluation_context_ [static], [private]
Definition at line 792 of file d8.h.
isolate_running_streaming_tasks_
std::map<Isolate*, int> v8::Shell::isolate_running_streaming_tasks_ [static], [private]
Definition at line 874 of file d8.h.
isolate_status_
std::map<Isolate*, bool> v8::Shell::isolate_status_ [static], [private]
Definition at line 873 of file d8.h.
isolate_status_lock_
base::LazyMutex v8::Shell::isolate_status_lock_ [static], [private]
Definition at line 872 of file d8.h.
kInitialTicks
const base::TimeTicks v8::Shell::kInitialTicks = base::TimeTicks::Now() [static], [private]
Definition at line 809 of file d8.h.
kPrompt
const char* v8::Shell::kPrompt [static]
Definition at line 759 of file d8.h.
local_counters_
CounterCollection v8::Shell::local_counters_ [static], [private]
Definition at line 805 of file d8.h.
options
ShellOptions v8::Shell::options [static]
Definition at line 760 of file d8.h.
Referenced by AddOSMethods(), CompileString(), DeserializationRunCount(), v8::SourceGroup::ExecuteInThread(), ExecuteString(), FetchModuleTree(), ReadCharsFromTcpPort(), v8::Serializer::ReallocateBufferMemory(), RunMain(), and use_interactive_shell().
profiler_end_callback_
std::map< Isolate *, std::pair< Global< Function >, Global< Context > > > v8::Shell::profiler_end_callback_ [static], [private]
Definition at line 798 of file d8.h.
profiler_end_callback_lock_
base::Mutex v8::Shell::profiler_end_callback_lock_ [static], [private]
Definition at line 796 of file d8.h.
quit_once_
base::OnceType v8::Shell::quit_once_ = V8_ONCE_INIT [static], [private]
Definition at line 793 of file d8.h.
running_workers_
std::unordered_set< std::shared_ptr< Worker > > v8::Shell::running_workers_ [static], [private]
Definition at line 813 of file d8.h.
script_executed_
std::atomic< bool > v8::Shell::script_executed_ {false} [static], [private]
Definition at line 816 of file d8.h.
Referenced by set_script_executed(), and use_interactive_shell().
stringify_function_
Global< Function > v8::Shell::stringify_function_ [static], [private]
Definition at line 794 of file d8.h.
stringify_source_
const char * v8::Shell::stringify_source_ [static], [private]
Definition at line 800 of file d8.h.
unhandled_promise_rejections_
std::atomic< int > v8::Shell::unhandled_promise_rejections_ {0} [static], [private]
Definition at line 879 of file d8.h.
Referenced by HandleUnhandledPromiseRejections(), and RunMain().
valid_fuzz_script_
std::atomic< bool > v8::Shell::valid_fuzz_script_ {false} [static], [private]
Definition at line 817 of file d8.h.
Referenced by is_valid_fuzz_script(), and update_script_size().
workers_mutex_
base::LazyMutex v8::Shell::workers_mutex_ [static], [private]
Definition at line 811 of file d8.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8-js.cc
/mnt/V8SourceCode/src/d8/d8-posix.cc
/mnt/V8SourceCode/src/d8/d8-test.cc
/mnt/V8SourceCode/src/d8/d8-windows.cc
/mnt/V8SourceCode/src/d8/d8.cc