v8::internal::compiler::FixedArrayBaseRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< FixedArrayBase > object () const
uint32_t length () const
Detailed Description
Definition at line 1010 of file heap-refs.h.
Member Function Documentation
length()
uint32_t v8::internal::compiler::FixedArrayBaseRef::length () const
Definition at line 2300 of file heap-refs.cc.
                                         {
  IF_ACCESS_FROM_HEAP_C(length);
  return data()->AsFixedArrayBase()->length();
}
References IF_ACCESS_FROM_HEAP_C.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedDoubleArrayElement(), v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements(), v8::internal::compiler::FixedArrayRef::TryGet(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
object()
IndirectHandle<FixedArrayBase> v8::internal::compiler::FixedArrayBaseRef::object () const
Referenced by v8::internal::compiler::JSArrayRef::GetOwnCowElement().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc