v8::internal::UnifiedHeapMarkingVisitorBase Class Reference
#include <unified-heap-marking-visitor.h>
Public Member Functions
UnifiedHeapMarkingVisitorBase (HeapBase &, cppgc::internal::BasicMarkingState &, UnifiedHeapMarkingState &)
~UnifiedHeapMarkingVisitorBase () override=default
Protected Member Functions
void Visit (const void *, TraceDescriptor) final
void VisitMultipleUncompressedMember (const void *, size_t, TraceDescriptorCallback) final
void VisitWeak (const void *, TraceDescriptor, WeakCallback, const void *) final
void VisitEphemeron (const void *, const void *, TraceDescriptor) final
void VisitWeakContainer (const void *self, TraceDescriptor strong_desc, TraceDescriptor weak_desc, WeakCallback callback, const void *data) final
void RegisterWeakCallback (WeakCallback, const void *) final
void HandleMovableReference (const void **) final
void Visit (const TracedReferenceBase &ref) override
Protected Attributes
cppgc::internal::BasicMarkingState & marking_state_
UnifiedHeapMarkingState & unified_heap_marking_state_
Friends
class UnifiedHeapMarker
Detailed Description
Definition at line 37 of file unified-heap-marking-visitor.h.
Constructor & Destructor Documentation
UnifiedHeapMarkingVisitorBase()
v8::internal::UnifiedHeapMarkingVisitorBase::UnifiedHeapMarkingVisitorBase (HeapBase & heap, cppgc::internal::BasicMarkingState & marking_state, UnifiedHeapMarkingState & unified_heap_marking_state)
Definition at line 29 of file unified-heap-marking-visitor.cc.
    : JSVisitor(cppgc::internal::VisitorFactory::CreateKey()),
      marking_state_(marking_state),
      unified_heap_marking_state_(unified_heap_marking_state) {}
 UnifiedHeapMarkingVisitorBase()
v8::internal::UnifiedHeapMarkingVisitorBase::~UnifiedHeapMarkingVisitorBase () [override], [default]
Member Function Documentation
HandleMovableReference()
void v8::internal::UnifiedHeapMarkingVisitorBase::HandleMovableReference (const void ** slot) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 100 of file unified-heap-marking-visitor.cc.
                                                                            {
  marking_state_.RegisterMovableReference(slot);
}
References marking_state_, and cppgc::internal::BasicMarkingState::RegisterMovableReference().
RegisterWeakCallback()
void v8::internal::UnifiedHeapMarkingVisitorBase::RegisterWeakCallback (WeakCallback callback, const void * object) [final], [protected]
Definition at line 95 of file unified-heap-marking-visitor.cc.
                                                                             {
  marking_state_.RegisterWeakCustomCallback(callback, object);
}
References marking_state_, and cppgc::internal::BasicMarkingState::RegisterWeakCustomCallback().
Visit() [1/2]
void v8::internal::UnifiedHeapMarkingVisitorBase::Visit (const TracedReferenceBase & ref) [override], [protected], [virtual]
Reimplemented from v8::JSVisitor.
Definition at line 104 of file unified-heap-marking-visitor.cc.
                                                                        {
  unified_heap_marking_state_.MarkAndPush(ref);
}
References v8::internal::UnifiedHeapMarkingState::MarkAndPush(), and unified_heap_marking_state_.
Visit() [2/2]
void v8::internal::UnifiedHeapMarkingVisitorBase::Visit (const void * object, TraceDescriptor desc) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 36 of file unified-heap-marking-visitor.cc.
                                                                {
  marking_state_.MarkAndPush(object, desc);
}
References cppgc::internal::MarkingStateBase::MarkAndPush(), and marking_state_.
VisitEphemeron()
void v8::internal::UnifiedHeapMarkingVisitorBase::VisitEphemeron (const void * key, const void * value, TraceDescriptor value_desc) [final], [protected], [virtual]
Reimplemented from cppgc::Visitor.
Definition at line 83 of file unified-heap-marking-visitor.cc.
                                                                               {
  marking_state_.ProcessEphemeron(key, value, value_desc, *this);
}
References v8::internal::key, marking_state_, cppgc::internal::BasicMarkingState::ProcessEphemeron(), and v8::internal::value.
VisitMultipleUncompressedMember()
void v8::internal::UnifiedHeapMarkingVisitorBase::VisitMultipleUncompressedMember (const void * start, size_t len, TraceDescriptorCallback get_trace_descriptor) [final], [protected]
Definition at line 41 of file unified-heap-marking-visitor.cc.
                                                  {
  const char* it = static_cast<const char*>(start);
  const char* end = it + len * cppgc::internal::kSizeOfUncompressedMember;
  for (; it < end; it += cppgc::internal::kSizeOfUncompressedMember) {
    const auto* current =
        reinterpret_cast<const cppgc::internal::RawPointer*>(it);
    const void* object = current->LoadAtomic();
    if (!object) continue;
    marking_state_.MarkAndPush(object, get_trace_descriptor(object));
  }
}
References v8::internal::compiler::end(), cppgc::internal::kSizeOfUncompressedMember, cppgc::internal::RawPointer::LoadAtomic(), cppgc::internal::MarkingStateBase::MarkAndPush(), and marking_state_.
VisitWeak()
void v8::internal::UnifiedHeapMarkingVisitorBase::VisitWeak (const void * object, TraceDescriptor desc, WeakCallback weak_callback, const void * weak_member) [final], [protected]
Definition at line 75 of file unified-heap-marking-visitor.cc.
                                                                       {
  marking_state_.RegisterWeakReferenceIfNeeded(object, desc, weak_callback,
                                               weak_member);
}
References marking_state_, and cppgc::internal::BasicMarkingState::RegisterWeakReferenceIfNeeded().
VisitWeakContainer()
void v8::internal::UnifiedHeapMarkingVisitorBase::VisitWeakContainer (const void * self, TraceDescriptor strong_desc, TraceDescriptor weak_desc, WeakCallback callback, const void * data) [final], [protected]
Definition at line 89 of file unified-heap-marking-visitor.cc.
                                             {
  marking_state_.ProcessWeakContainer(self, weak_desc, callback, data);
}
References marking_state_, and cppgc::internal::BasicMarkingState::ProcessWeakContainer().
Friends And Related Function Documentation
UnifiedHeapMarker
friend class UnifiedHeapMarker [friend]
Definition at line 66 of file unified-heap-marking-visitor.h.
Member Data Documentation
marking_state_
cppgc::internal::BasicMarkingState& v8::internal::UnifiedHeapMarkingVisitorBase::marking_state_ [protected]
Definition at line 63 of file unified-heap-marking-visitor.h.
Referenced by v8::internal::ConcurrentUnifiedHeapMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent(), v8::internal::UnifiedHeapMarker::GetMutatorMarkingState(), HandleMovableReference(), RegisterWeakCallback(), Visit(), VisitEphemeron(), VisitMultipleUncompressedMember(), VisitWeak(), and VisitWeakContainer().
unified_heap_marking_state_
UnifiedHeapMarkingState& v8::internal::UnifiedHeapMarkingVisitorBase::unified_heap_marking_state_ [protected]
Definition at line 64 of file unified-heap-marking-visitor.h.
Referenced by Visit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-visitor.h
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-visitor.cc