v8::internal::Factory Class Reference
#include <factory.h>
Classes
class CodeBuilder
class JSFunctionBuilder
Public Member Functions
ReadOnlyRoots read_only_roots () const
DirectHandle< Hole > NewHole ()
DirectHandle< PropertyArray > NewPropertyArray (int length, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeHandle< FixedArray > TryNewFixedArray (int length, AllocationType allocation=AllocationType::kYoung)
Handle< FeedbackVector > NewFeedbackVector (DirectHandle< SharedFunctionInfo > shared, DirectHandle< ClosureFeedbackCellArray > closure_feedback_cell_array, DirectHandle< FeedbackCell > parent_feedback_cell)
DirectHandle< EmbedderDataArray > NewEmbedderDataArray (int length)
DirectHandle< FixedArrayBase > NewFixedDoubleArrayWithHoles (int size)
DirectHandle< NameDictionary > NewNameDictionary (int at_least_space_for)
Handle< OrderedHashSet > NewOrderedHashSet ()
Handle< OrderedHashMap > NewOrderedHashMap ()
Handle< SmallOrderedHashSet > NewSmallOrderedHashSet (int capacity=kSmallOrderedHashSetMinCapacity, AllocationType allocation=AllocationType::kYoung)
Handle< SmallOrderedHashMap > NewSmallOrderedHashMap (int capacity=kSmallOrderedHashMapMinCapacity, AllocationType allocation=AllocationType::kYoung)
Handle< SmallOrderedNameDictionary > NewSmallOrderedNameDictionary (int capacity=kSmallOrderedHashMapMinCapacity, AllocationType allocation=AllocationType::kYoung)
DirectHandle< SwissNameDictionary > CreateCanonicalEmptySwissNameDictionary ()
DirectHandle< PrototypeInfo > NewPrototypeInfo ()
DirectHandle< EnumCache > NewEnumCache (DirectHandle< FixedArray > keys, DirectHandle< FixedArray > indices, AllocationType allocation=AllocationType::kOld)
DirectHandle< Tuple2 > NewTuple2Uninitialized (AllocationType allocation)
DirectHandle< Tuple2 > NewTuple2 (DirectHandle< Object > value1, DirectHandle< Object > value2, AllocationType allocation)
DirectHandle< PropertyDescriptorObject > NewPropertyDescriptorObject ()
Handle< String > InternalizeUtf8String (base::Vector< const char > str)
Handle< String > InternalizeUtf8String (const char *str)
Handle< String > InternalizeString (base::Vector< const char > str, bool convert_encoding=false)
Handle< String > InternalizeString (const char *str, bool convert_encoding=false)
template<typename SeqString , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< SeqString >, DirectHandle< SeqString >>) Handle< String > InternalizeSubString(HandleType< SeqString >
template<typename T >
requires (std::is_convertible_v< Handle< T >, Handle< String >>) inline Handle< String > InternalizeString(Handle< T > string)
template<typename T >
requires (std::is_convertible_v< Handle< T >, Handle< Name >>) inline Handle< Name > InternalizeName(Handle< T > name)
template<typename T >
requires (std::is_convertible_v< DirectHandle< T >, DirectHandle< String >>) inline DirectHandle< String > InternalizeString(DirectHandle< T > string)
template<typename T >
requires (std::is_convertible_v< DirectHandle< T >, DirectHandle< Name >>) inline DirectHandle< Name > InternalizeName(DirectHandle< T > name)
template<size_t N>
Handle< String > NewStringFromStaticChars (const char(&str)[N], AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeHandle< String > NewStringFromUtf8 (base::Vector< const char > str, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeHandle< String > NewStringFromUtf8 (base::Vector< const uint8_t > str, unibrow::Utf8Variant utf8_variant, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeHandle< String > NewStringFromUtf8SubString (Handle< SeqOneByteString > str, int begin, int end, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeHandle< String > NewStringFromTwoByte (base::Vector< const base::uc16 > str, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > NewStringFromTwoByte (const ZoneVector< base::uc16 > *str, AllocationType allocation=AllocationType::kYoung)
DirectHandle< JSStringIterator > NewJSStringIterator (Handle< String > string)
DirectHandle< String > NewInternalizedStringImpl (DirectHandle< String > string, int len, uint32_t hash_field)
V8_WARN_UNUSED_RESULT StringTransitionStrategy ComputeInternalizationStrategyForString (DirectHandle< String > string, MaybeDirectHandle< Map > *internalized_map)
template<class StringClass >
DirectHandle< StringClass > InternalizeExternalString (DirectHandle< String > string)
V8_WARN_UNUSED_RESULT StringTransitionStrategy ComputeSharingStrategyForString (DirectHandle< String > string, MaybeDirectHandle< Map > *shared_map)
DirectHandle< String > NewSurrogatePairString (uint16_t lead, uint16_t trail)
Handle< String > NewProperSubString (DirectHandle< String > str, uint32_t begin, uint32_t end)
Handle< String > NewCopiedSubstring (DirectHandle< String > str, uint32_t begin, uint32_t length)
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, HandleType< String >>) inline HandleType< String > NewSubString(HandleType< T > str
V8_WARN_UNUSED_RESULT MaybeHandle< String > NewExternalStringFromOneByte (const v8::String::ExternalOneByteStringResource *resource)
V8_WARN_UNUSED_RESULT MaybeHandle< String > NewExternalStringFromTwoByte (const v8::String::ExternalStringResource *resource)
Handle< Symbol > NewSymbol (AllocationType allocation=AllocationType::kOld)
Handle< Symbol > NewPrivateSymbol (AllocationType allocation=AllocationType::kOld)
DirectHandle< Symbol > NewPrivateNameSymbol (DirectHandle< String > name)
Handle< NativeContext > NewNativeContext ()
DirectHandle< Context > NewScriptContext (DirectHandle< NativeContext > outer, DirectHandle< ScopeInfo > scope_info)
Handle< ScriptContextTable > NewScriptContextTable ()
DirectHandle< Context > NewModuleContext (DirectHandle< SourceTextModule > module, DirectHandle< NativeContext > outer, DirectHandle< ScopeInfo > scope_info)
DirectHandle< Context > NewFunctionContext (DirectHandle< Context > outer, DirectHandle< ScopeInfo > scope_info)
DirectHandle< Context > NewCatchContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info, DirectHandle< Object > thrown_object)
Handle< Context > NewWithContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info, DirectHandle< JSReceiver > extension)
Handle< Context > NewDebugEvaluateContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info, DirectHandle< JSReceiver > extension, DirectHandle< Context > wrapped)
DirectHandle< Context > NewBlockContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info)
DirectHandle< ContextCell > NewContextCell (DirectHandle< JSAny > value, AllocationType allocation_type=AllocationType::kYoung)
DirectHandle< Context > NewBuiltinContext (DirectHandle< NativeContext > native_context, int length)
DirectHandle< AliasedArgumentsEntry > NewAliasedArgumentsEntry (int aliased_context_slot)
DirectHandle< AccessorInfo > NewAccessorInfo ()
DirectHandle< InterceptorInfo > NewInterceptorInfo (AllocationType allocation=AllocationType::kOld)
DirectHandle< ErrorStackData > NewErrorStackData (DirectHandle< UnionOf< JSAny, FixedArray >> call_site_infos_or_formatted_stack, DirectHandle< StackTraceInfo > stack_trace)
Handle< Script > CloneScript (DirectHandle< Script > script, DirectHandle< String > source)
DirectHandle< BreakPointInfo > NewBreakPointInfo (int source_position)
Handle< BreakPoint > NewBreakPoint (int id, DirectHandle< String > condition)
Handle< CallSiteInfo > NewCallSiteInfo (DirectHandle< JSAny > receiver_or_instance, DirectHandle< UnionOf< Smi, JSFunction >> function, DirectHandle< HeapObject > code_object, int code_offset_or_source_position, int flags, DirectHandle< FixedArray > parameters)
DirectHandle< StackFrameInfo > NewStackFrameInfo (DirectHandle< UnionOf< SharedFunctionInfo, Script >> shared_or_script, int bytecode_offset_or_source_position, DirectHandle< String > function_name, bool is_constructor)
Handle< StackTraceInfo > NewStackTraceInfo (DirectHandle< FixedArray > frames)
DirectHandle< CallableTask > NewCallableTask (DirectHandle< JSReceiver > callable, DirectHandle< Context > context)
DirectHandle< CallbackTask > NewCallbackTask (DirectHandle< Foreign > callback, DirectHandle< Foreign > data)
DirectHandle< PromiseResolveThenableJobTask > NewPromiseResolveThenableJobTask (DirectHandle< JSPromise > promise_to_resolve, DirectHandle< JSReceiver > thenable, DirectHandle< JSReceiver > then, DirectHandle< Context > context)
template<ExternalPointerTag tag>
Handle< Foreign > NewForeign (Address addr, AllocationType allocation_type=AllocationType::kYoung)
Handle< TrustedForeign > NewTrustedForeign (Address addr, bool shared)
Handle< Cell > NewCell (Tagged< Smi > value)
Handle< Cell > NewCell ()
Handle< PropertyCell > NewPropertyCell (DirectHandle< Name > name, PropertyDetails details, DirectHandle< Object > value, AllocationType allocation=AllocationType::kOld)
DirectHandle< PropertyCell > NewProtector ()
DirectHandle< FeedbackCell > NewNoClosuresCell ()
DirectHandle< FeedbackCell > NewOneClosureCell (DirectHandle< ClosureFeedbackCellArray > value)
DirectHandle< FeedbackCell > NewManyClosuresCell (AllocationType allocation=AllocationType::kOld)
DirectHandle< TransitionArray > NewTransitionArray (int number_of_transitions, int slack=0)
Handle< AllocationSite > NewAllocationSite (bool with_weak_next)
Handle< Map > NewMap (DirectHandle< HeapObject > meta_map_holder, InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
DirectHandle< Map > NewMapWithMetaMap (DirectHandle< Map > meta_map, InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
DirectHandle< Map > NewContextfulMap (DirectHandle< JSReceiver > creation_context_holder, InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
DirectHandle< Map > NewContextfulMap (DirectHandle< NativeContext > native_context, InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
Handle< Map > NewContextfulMapForCurrentContext (InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
Handle< Map > NewContextlessMap (InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
Tagged< Map > InitializeMap (Tagged< Map > map, InstanceType type, int instance_size, ElementsKind elements_kind, int inobject_properties, ReadOnlyRoots roots)
DirectHandle< HeapObject > NewFillerObject (int size, AllocationAlignment alignment, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime)
DirectHandle< JSObject > NewFunctionPrototype (DirectHandle< JSFunction > function)
Handle< JSObject > CopyJSObject (DirectHandle< JSObject > object)
Handle< JSObject > CopyJSObjectWithAllocationSite (DirectHandle< JSObject > object, DirectHandle< AllocationSite > site)
Handle< FixedArray > CopyFixedArrayWithMap (DirectHandle< FixedArray > array, DirectHandle< Map > map, AllocationType allocation=AllocationType::kYoung)
Handle< FixedArray > CopyFixedArrayAndGrow (DirectHandle< FixedArray > array, int grow_by, AllocationType allocation=AllocationType::kYoung)
DirectHandle< WeakArrayList > NewWeakArrayList (int capacity, AllocationType allocation=AllocationType::kYoung)
DirectHandle< WeakFixedArray > CopyWeakFixedArray (DirectHandle< WeakFixedArray > array)
DirectHandle< WeakFixedArray > CopyWeakFixedArrayAndGrow (DirectHandle< WeakFixedArray > array, int grow_by)
Handle< WeakArrayList > CopyWeakArrayListAndGrow (DirectHandle< WeakArrayList > array, int grow_by, AllocationType allocation=AllocationType::kYoung)
DirectHandle< WeakArrayList > CompactWeakArrayList (DirectHandle< WeakArrayList > array, int new_capacity, AllocationType allocation=AllocationType::kYoung)
DirectHandle< PropertyArray > CopyPropertyArrayAndGrow (DirectHandle< PropertyArray > array, int grow_by)
Handle< FixedArray > CopyFixedArrayUpTo (DirectHandle< FixedArray > array, int new_len, AllocationType allocation=AllocationType::kYoung)
Handle< FixedArray > CopyFixedArray (Handle< FixedArray > array)
Handle< FixedDoubleArray > CopyFixedDoubleArray (Handle< FixedDoubleArray > array)
Handle< HeapNumber > NewHeapNumberForCodeAssembler (double value)
Handle< JSObject > NewArgumentsObject (DirectHandle< JSFunction > callee, int length)
Handle< JSObject > NewJSObject (DirectHandle< JSFunction > constructor, AllocationType allocation=AllocationType::kYoung, NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
Handle< JSObject > NewJSObjectWithNullProto ()
Handle< JSObject > NewSlowJSObjectWithNullProto ()
Handle< JSGlobalObject > NewJSGlobalObject (DirectHandle< JSFunction > constructor)
Handle< JSObject > NewJSObjectFromMap (DirectHandle< Map > map, AllocationType allocation=AllocationType::kYoung, DirectHandle< AllocationSite > allocation_site=DirectHandle< AllocationSite >::null(), NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
Handle< JSObject > NewSlowJSObjectFromMap (DirectHandle< Map > map, int number_of_slow_properties, AllocationType allocation=AllocationType::kYoung, DirectHandle< AllocationSite > allocation_site=DirectHandle< AllocationSite >::null(), NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
Handle< JSObject > NewSlowJSObjectFromMap (DirectHandle< Map > map)
Handle< JSObject > NewFastOrSlowJSObjectFromMap (DirectHandle< Map > map, int number_of_slow_properties, AllocationType allocation=AllocationType::kYoung, DirectHandle< AllocationSite > allocation_site=DirectHandle< AllocationSite >::null(), NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
Handle< JSObject > NewFastOrSlowJSObjectFromMap (DirectHandle< Map > map)
DirectHandle< JSObject > NewSlowJSObjectWithPropertiesAndElements (DirectHandle< JSPrototype > prototype, DirectHandle< HeapObject > properties, DirectHandle< FixedArrayBase > elements)
Handle< JSArray > NewJSArray (ElementsKind elements_kind, int length, int capacity, ArrayStorageAllocationMode mode=ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS, AllocationType allocation=AllocationType::kYoung)
Handle< JSArray > NewJSArray (int capacity, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, AllocationType allocation=AllocationType::kYoung)
Handle< JSArray > NewJSArrayWithElements (DirectHandle< FixedArrayBase > elements, ElementsKind elements_kind, int length, AllocationType allocation=AllocationType::kYoung)
Handle< JSArray > NewJSArrayWithElements (DirectHandle< FixedArrayBase > elements, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, AllocationType allocation=AllocationType::kYoung)
DirectHandle< JSArray > NewJSArrayForTemplateLiteralArray (DirectHandle< FixedArray > cooked_strings, DirectHandle< FixedArray > raw_strings, int function_literal_id, int slot_id)
void NewJSArrayStorage (DirectHandle< JSArray > array, int length, int capacity, ArrayStorageAllocationMode mode=ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS)
Handle< JSWeakMap > NewJSWeakMap ()
DirectHandle< JSGeneratorObject > NewJSGeneratorObject (DirectHandle< JSFunction > function)
DirectHandle< JSModuleNamespace > NewJSModuleNamespace ()
DirectHandle< JSWrappedFunction > NewJSWrappedFunction (DirectHandle< NativeContext > creation_context, DirectHandle< Object > target)
DirectHandle< JSDisposableStackBase > NewJSDisposableStackBase ()
DirectHandle< JSSyncDisposableStack > NewJSSyncDisposableStack (DirectHandle< Map > map)
DirectHandle< JSAsyncDisposableStack > NewJSAsyncDisposableStack (DirectHandle< Map > map)
DirectHandle< SourceTextModule > NewSourceTextModule (DirectHandle< SharedFunctionInfo > code)
Handle< SyntheticModule > NewSyntheticModule (DirectHandle< String > module_name, DirectHandle< FixedArray > export_names, v8::Module::SyntheticModuleEvaluationSteps evaluation_steps)
Handle< JSArrayBuffer > NewJSArrayBuffer (std::shared_ptr< BackingStore > backing_store, AllocationType allocation=AllocationType::kYoung)
MaybeHandle< JSArrayBuffer > NewJSArrayBufferAndBackingStore (size_t byte_length, InitializedFlag initialized, AllocationType allocation=AllocationType::kYoung)
MaybeHandle< JSArrayBuffer > NewJSArrayBufferAndBackingStore (size_t byte_length, size_t max_byte_length, InitializedFlag initialized, ResizableFlag resizable=ResizableFlag::kNotResizable, AllocationType allocation=AllocationType::kYoung)
Handle< JSArrayBuffer > NewJSSharedArrayBuffer (std::shared_ptr< BackingStore > backing_store)
Handle< JSTypedArray > NewJSTypedArray (ExternalArrayType type, DirectHandle< JSArrayBuffer > buffer, size_t byte_offset, size_t length, bool is_length_tracking=false)
Handle< JSDataViewOrRabGsabDataView > NewJSDataViewOrRabGsabDataView (DirectHandle< JSArrayBuffer > buffer, size_t byte_offset, size_t byte_length, bool is_length_tracking=false)
DirectHandle< JSUint8ArraySetFromResult > NewJSUint8ArraySetFromResult (DirectHandle< Number > read, DirectHandle< Number > written)
DirectHandle< JSIteratorResult > NewJSIteratorResult (DirectHandle< Object > value, bool done)
DirectHandle< JSAsyncFromSyncIterator > NewJSAsyncFromSyncIterator (DirectHandle< JSReceiver > sync_iterator, DirectHandle< Object > next)
DirectHandle< JSMap > NewJSMap ()
DirectHandle< JSSet > NewJSSet ()
MaybeDirectHandle< JSBoundFunction > NewJSBoundFunction (DirectHandle< JSReceiver > target_function, DirectHandle< JSAny > bound_this, base::Vector< DirectHandle< Object >> bound_args, DirectHandle< JSPrototype > prototype)
Handle< JSProxy > NewJSProxy (DirectHandle< JSReceiver > target, DirectHandle< JSReceiver > handler, bool revocable)
void ReinitializeJSGlobalProxy (DirectHandle< JSGlobalProxy > global, DirectHandle< JSFunction > constructor)
Handle< JSGlobalProxy > NewUninitializedJSGlobalProxy (int size)
Handle< JSFunction > NewFunctionForTesting (DirectHandle< String > name)
Handle< JSObject > NewExternal (void *value, AllocationType allocation=AllocationType::kYoung)
Handle< CppHeapExternalObject > NewCppHeapExternal (AllocationType allocation=AllocationType::kYoung)
DirectHandle< Code > NewCodeObjectForEmbeddedBuiltin (DirectHandle< Code > code, Address off_heap_entry)
DirectHandle< BytecodeArray > CopyBytecodeArray (DirectHandle< BytecodeArray >)
Handle< JSObject > NewError (DirectHandle< JSFunction > constructor, DirectHandle< String > message, DirectHandle< Object > options={})
DirectHandle< Object > NewInvalidStringLengthError ()
DirectHandle< Object > NewURIError ()
Handle< JSObject > NewError (DirectHandle< JSFunction > constructor, MessageTemplate template_index, base::Vector< const DirectHandle< Object >> args)
DirectHandle< JSObject > NewSuppressedErrorAtDisposal (Isolate *isolate, DirectHandle< Object > error, DirectHandle< Object > suppressed_error)
template<typename... Args>
DirectHandle< JSObject > NewError (DirectHandle< JSFunction > constructor, MessageTemplate template_index, Args... args) requires(std
DirectHandle< JSObject > ShadowRealmNewTypeErrorCopy (DirectHandle< Object > original, MessageTemplate template_index, base::Vector< const DirectHandle< Object >> args)
template<typename... Args>
DirectHandle< JSObject > ShadowRealmNewTypeErrorCopy (DirectHandle< Object > original, MessageTemplate template_index, Args... args) requires(std
Handle< String > SizeToString (size_t value, bool check_cache=true)
DirectHandle< String > Uint32ToString (uint32_t value, bool check_cache=true)
Handle< SharedFunctionInfo > NewSharedFunctionInfoForApiFunction (MaybeDirectHandle< String > maybe_name, DirectHandle< FunctionTemplateInfo > function_template_info, FunctionKind kind)
Handle< SharedFunctionInfo > NewSharedFunctionInfoForBuiltin (MaybeDirectHandle< String > name, Builtin builtin, int len, AdaptArguments adapt, FunctionKind kind=FunctionKind::kNormalFunction)
DirectHandle< InterpreterData > NewInterpreterData (DirectHandle< BytecodeArray > bytecode_array, DirectHandle< Code > code)
DirectHandle< Map > CreateSloppyFunctionMap (FunctionMode function_mode, MaybeDirectHandle< JSFunction > maybe_empty_function)
DirectHandle< Map > CreateStrictFunctionMap (FunctionMode function_mode, DirectHandle< JSFunction > empty_function)
DirectHandle< Map > CreateClassFunctionMap (DirectHandle< JSFunction > empty_function)
Handle< JSMessageObject > NewJSMessageObject (MessageTemplate message, DirectHandle< Object > argument, int start_position, int end_position, DirectHandle< SharedFunctionInfo > shared_info, int bytecode_offset, DirectHandle< Script > script, DirectHandle< StackTraceInfo > stack_trace=DirectHandle< StackTraceInfo >::null())
Handle< DebugInfo > NewDebugInfo (DirectHandle< SharedFunctionInfo > shared)
Handle< Map > ObjectLiteralMapFromCache (DirectHandle< NativeContext > native_context, int number_of_properties)
Handle< LoadHandler > NewLoadHandler (int data_count, AllocationType allocation=AllocationType::kOld)
Handle< StoreHandler > NewStoreHandler (int data_count)
DirectHandle< MegaDomHandler > NewMegaDomHandler (MaybeObjectDirectHandle accessor, MaybeObjectDirectHandle context)
void SetRegExpAtomData (DirectHandle< JSRegExp > regexp, DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< String > match_pattern)
void SetRegExpIrregexpData (DirectHandle< JSRegExp > regexp, DirectHandle< String > source, JSRegExp::Flags flags, int capture_count, uint32_t backtrack_limit)
void SetRegExpExperimentalData (DirectHandle< JSRegExp > regexp, DirectHandle< String > source, JSRegExp::Flags flags, int capture_count)
DirectHandle< RegExpData > NewAtomRegExpData (DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< String > pattern)
DirectHandle< RegExpData > NewIrRegExpData (DirectHandle< String > source, JSRegExp::Flags flags, int capture_count, uint32_t backtrack_limit)
DirectHandle< RegExpData > NewExperimentalRegExpData (DirectHandle< String > source, JSRegExp::Flags flags, int capture_count)
DirectHandle< Object > GlobalConstantFor (DirectHandle< Name > name)
DirectHandle< String > ToPrimitiveHintString (ToPrimitiveHint hint)
Handle< JSPromise > NewJSPromiseWithoutHook ()
Handle< JSPromise > NewJSPromise ()
Tagged< HeapObject > NewForTest (DirectHandle< Map > map, AllocationType allocation)
DirectHandle< JSSharedStruct > NewJSSharedStruct (DirectHandle< JSFunction > constructor, MaybeDirectHandle< NumberDictionary > maybe_elements_template)
DirectHandle< JSSharedArray > NewJSSharedArray (DirectHandle< JSFunction > constructor, int length)
Handle< JSAtomicsMutex > NewJSAtomicsMutex ()
Handle< JSAtomicsCondition > NewJSAtomicsCondition ()
DirectHandle< FunctionTemplateInfo > NewFunctionTemplateInfo (int length, bool do_not_cache)
DirectHandle< ObjectTemplateInfo > NewObjectTemplateInfo (DirectHandle< FunctionTemplateInfo > constructor, bool do_not_cache)
DirectHandle< DictionaryTemplateInfo > NewDictionaryTemplateInfo (DirectHandle< FixedArray > property_names)
Handle< String > InternalizeString (base::Vector< const uint8_t > string, bool convert_encoding=false)
Handle< String > InternalizeString (base::Vector< const uint16_t > string, bool convert_encoding=false)
Static Public Member Functions
static void TypeAndSizeForElementsKind (ElementsKind kind, ExternalArrayType *array_type, size_t *element_size)
static bool IsFunctionModeWithPrototype (FunctionMode function_mode)
static bool IsFunctionModeWithWritablePrototype (FunctionMode function_mode)
static bool IsFunctionModeWithName (FunctionMode function_mode)
Public Attributes
uint32_t from
uint32_t uint32_t length
uint32_t uint32_t bool convert_encoding = false)
uint32_t begin
uint32_t uint32_t end
Private Member Functions
Tagged< HeapObject > AllocateRaw (int size, AllocationType allocation, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
Isolate * isolate () const
HeapAllocator * allocator () const
bool CanAllocateInReadOnlySpace ()
bool EmptyStringRootIsInitialized ()
AllocationType AllocationTypeForInPlaceInternalizableString ()
void ProcessNewScript (DirectHandle< Script > shared, ScriptEventType script_event_type)
template<typename MetaMapProviderFunc >
Handle< Map > NewMapImpl (MetaMapProviderFunc &&meta_map_provider, InstanceType type, int instance_size, ElementsKind elements_kind=TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties=0, AllocationType allocation_type=AllocationType::kMap)
Tagged< HeapObject > AllocateRawWithAllocationSite (DirectHandle< Map > map, AllocationType allocation, DirectHandle< AllocationSite > allocation_site)
Handle< JSArrayBufferView > NewJSArrayBufferView (DirectHandle< Map > map, DirectHandle< FixedArrayBase > elements, DirectHandle< JSArrayBuffer > buffer, size_t byte_offset, size_t byte_length)
Tagged< Symbol > NewSymbolInternal (AllocationType allocation=AllocationType::kOld)
Tagged< Context > NewContextInternal (DirectHandle< Map > map, int size, int variadic_part_length, AllocationType allocation)
template<typename T >
Handle< T > AllocateSmallOrderedHashTable (DirectHandle< Map > map, int capacity, AllocationType allocation)
Tagged< HeapObject > New (DirectHandle< Map > map, AllocationType allocation)
template<typename T >
Handle< T > CopyArrayWithMap (DirectHandle< T > src, DirectHandle< Map > map, AllocationType allocation=AllocationType::kYoung)
template<typename T >
Handle< T > CopyArrayAndGrow (DirectHandle< T > src, int grow_by, AllocationType allocation)
MaybeHandle< String > NewStringFromTwoByte (const base::uc16 *string, int length, AllocationType allocation)
Handle< JSArray > NewJSArrayWithUnverifiedElements (DirectHandle< FixedArrayBase > elements, ElementsKind elements_kind, int length, AllocationType allocation=AllocationType::kYoung)
Handle< JSArray > NewJSArrayWithUnverifiedElements (DirectHandle< Map > map, DirectHandle< FixedArrayBase > elements, int length, AllocationType allocation=AllocationType::kYoung)
DirectHandle< FixedArrayBase > NewJSArrayStorage (ElementsKind elements_kind, int capacity, ArrayStorageAllocationMode mode=ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS)
void InitializeAllocationMemento (Tagged< AllocationMemento > memento, Tagged< AllocationSite > allocation_site)
void InitializeJSObjectFromMap (Tagged< JSObject > obj, Tagged< Object > properties, Tagged< Map > map, NewJSObjectType=NewJSObjectType::kNoAPIWrapper)
void InitializeJSObjectBody (Tagged< JSObject > obj, Tagged< Map > map, int start_offset)
Handle< WeakArrayList > NewUninitializedWeakArrayList (int capacity, AllocationType allocation=AllocationType::kYoung)
Friends
class FactoryBase< Factory >
Additional Inherited Members
Detailed Description
Definition at line 141 of file factory.h.
Member Function Documentation
AllocateRaw()
Tagged< HeapObject > v8::internal::Factory::AllocateRaw (int size, AllocationType allocation, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [private]
Definition at line 294 of file factory.cc.
                                                             {
  return allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
      size, allocation, AllocationOrigin::kRuntime, alignment, hint);
}
References v8::internal::HeapAllocator::AllocateRawWith(), allocator(), v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kRuntime, and size().
AllocateRawWithAllocationSite()
Tagged< HeapObject > v8::internal::Factory::AllocateRawWithAllocationSite (DirectHandle< Map > map, AllocationType allocation, DirectHandle< AllocationSite > allocation_site) [private]
Definition at line 301 of file factory.cc.
                                                  {
  DCHECK_NE(map->instance_type(), MAP_TYPE);
  const auto [write_barrier_mode, should_allocate_memento] =
      allocation == AllocationType::kYoung
          ? std::pair{SKIP_WRITE_BARRIER, !allocation_site.is_null()}
          : std::pair{UPDATE_WRITE_BARRIER, false};
  DCHECK_IMPLIES(should_allocate_memento, V8_ALLOCATION_SITE_TRACKING_BOOL);
  const int instance_size = map->instance_size();
  const int allocation_size =
      should_allocate_memento
          ? instance_size +
                ALIGN_TO_ALLOCATION_ALIGNMENT(sizeof(AllocationMemento))
          : instance_size;
  Tagged<HeapObject> result =
      allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(allocation_size,
                                                                allocation);
  result->set_map_after_allocation(isolate(), *map, write_barrier_mode);
  if (should_allocate_memento) {
    const int aligned_size = ALIGN_TO_ALLOCATION_ALIGNMENT(instance_size);
    Tagged<AllocationMemento> alloc_memento = UncheckedCast<AllocationMemento>(
        Tagged<Object>(result.ptr() + aligned_size));
    InitializeAllocationMemento(alloc_memento, *allocation_site);
  }
  return result;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::HeapAllocator::AllocateRawWith(), allocator(), DCHECK_IMPLIES, DCHECK_NE, InitializeAllocationMemento(), v8::internal::DirectHandle< T >::is_null(), isolate(), v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kYoung, v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and V8_ALLOCATION_SITE_TRACKING_BOOL.
Referenced by NewCppHeapExternal(), and NewJSObjectFromMap().
AllocateSmallOrderedHashTable()
template<typename T >
Handle< T > v8::internal::Factory::AllocateSmallOrderedHashTable (DirectHandle< Map > map, int capacity, AllocationType allocation) [private]
Definition at line 517 of file factory.cc.
                                                                            {
  // Capacity must be a power of two, since we depend on being able
  // to divide and multiple by 2 (kLoadFactor) to derive capacity
  // from number of buckets. If we decide to change kLoadFactor
  // to something other than 2, capacity should be stored as another
  // field of this object.
  DCHECK_EQ(T::kLoadFactor, 2);
  capacity =
      base::bits::RoundUpToPowerOfTwo32(std::max({T::kMinCapacity, capacity}));
  capacity = std::min({capacity, T::kMaxCapacity});
  DCHECK_LT(0, capacity);
  DCHECK_EQ(0, capacity % T::kLoadFactor);
  int size = T::SizeFor(capacity);
  Tagged<HeapObject> result =
      AllocateRawWithImmortalMap(size, allocation, *map);
  Handle<T> table(Cast<T>(result), isolate());
  table->Initialize(isolate(), capacity);
  return table;
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), DCHECK_EQ, DCHECK_LT, isolate(), v8::base::internal::result, and size().
AllocationTypeForInPlaceInternalizableString()
AllocationType v8::internal::Factory::AllocationTypeForInPlaceInternalizableString () [private]
Definition at line 4577 of file factory.cc.
                                                                     {
  return isolate()
      ->heap()
      ->allocation_type_for_in_place_internalizable_strings();
}
References v8::internal::Heap::allocation_type_for_in_place_internalizable_strings(), v8::internal::Isolate::heap(), and isolate().
allocator()
HeapAllocator * v8::internal::Factory::allocator () const [inline], [private]
Definition at line 140 of file factory-inl.h.
                                        {
  return isolate()->heap()->allocator();
}
References v8::internal::Heap::allocator(), v8::internal::Isolate::heap(), and isolate().
Referenced by AllocateRaw(), AllocateRawWithAllocationSite(), CanAllocateInReadOnlySpace(), CopyJSObjectWithAllocationSite(), New(), NewContextInternal(), NewFillerObject(), and NewMapImpl().
CanAllocateInReadOnlySpace()
bool v8::internal::Factory::CanAllocateInReadOnlySpace () [private]
Definition at line 4569 of file factory.cc.
                                         {
  return allocator()->CanAllocateInReadOnlySpace();
}
References allocator(), and v8::internal::HeapAllocator::CanAllocateInReadOnlySpace().
Referenced by NewHeapNumberForCodeAssembler().
CloneScript()
Handle< Script > v8::internal::Factory::CloneScript (DirectHandle< Script > script, DirectHandle< String > source)
Definition at line 1590 of file factory.cc.
                                                                 {
  int script_id = isolate()->GetNextScriptId();
#ifdef V8_SCRIPTORMODULE_LEGACY_LIFETIME
  DirectHandle<ArrayList> list = ArrayList::New(isolate(), 0);
#endif
  Handle<Script> new_script_handle =
      Cast<Script>(NewStruct(SCRIPT_TYPE, AllocationType::kOld));
  {
    DisallowGarbageCollection no_gc;
    Tagged<Script> new_script = *new_script_handle;
    const Tagged<Script> old_script = *script;
    new_script->set_source(*source);
    new_script->set_name(old_script->name());
    new_script->set_id(script_id);
    new_script->set_line_offset(old_script->line_offset());
    new_script->set_column_offset(old_script->column_offset());
    new_script->set_context_data(old_script->context_data());
    new_script->set_type(old_script->type());
    new_script->set_line_ends(Smi::zero());
    new_script->set_eval_from_shared_or_wrapped_arguments(
        script->eval_from_shared_or_wrapped_arguments());
    new_script->set_infos(*empty_weak_fixed_array(), SKIP_WRITE_BARRIER);
    new_script->set_eval_from_position(old_script->eval_from_position());
    new_script->set_flags(old_script->flags());
    new_script->set_host_defined_options(old_script->host_defined_options());
    new_script->set_source_hash(*undefined_value(), SKIP_WRITE_BARRIER);
    new_script->set_compiled_lazy_function_positions(*undefined_value(),
                                                     SKIP_WRITE_BARRIER);
#ifdef V8_SCRIPTORMODULE_LEGACY_LIFETIME
    new_script->set_script_or_modules(*list);
#endif
  }
  ProcessNewScript(new_script_handle, ScriptEventType::kCreate);
  return new_script_handle;
}
References v8::internal::Isolate::GetNextScriptId(), isolate(), v8::internal::kCreate, v8::internal::kOld, v8::internal::ArrayList::New(), v8::internal::FactoryBase< Factory >::NewStruct(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ProcessNewScript(), v8::internal::script, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Smi::zero().
Referenced by v8::internal::LiveEdit::PatchScript().
CompactWeakArrayList()
DirectHandle< WeakArrayList > v8::internal::Factory::CompactWeakArrayList (DirectHandle< WeakArrayList > array, int new_capacity, AllocationType allocation = AllocationType::kYoung)
Definition at line 2732 of file factory.cc.
                               {
  DirectHandle<WeakArrayList> result =
      NewUninitializedWeakArrayList(new_capacity, allocation);
  // Copy the content.
  DisallowGarbageCollection no_gc;
  Tagged<WeakArrayList> raw_src = *src;
  Tagged<WeakArrayList> raw_result = *result;
  WriteBarrierMode mode = raw_result->GetWriteBarrierMode(no_gc);
  int copy_to = 0, length = raw_src->length();
  for (int i = 0; i < length; i++) {
    Tagged<MaybeObject> element = raw_src->Get(i);
    if (element.IsCleared()) continue;
    raw_result->Set(copy_to++, element, mode);
  }
  raw_result->set_length(copy_to);
  MemsetTagged(ObjectSlot(raw_result->data_start() + copy_to),
               read_only_roots().undefined_value(), new_capacity - copy_to);
  return result;
}
References v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), length, v8::internal::MemsetTagged(), mode(), NewUninitializedWeakArrayList(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), and v8::base::internal::result.
Referenced by v8::internal::WeakArrayList::Append().
ComputeInternalizationStrategyForString()
StringTransitionStrategy v8::internal::Factory::ComputeInternalizationStrategyForString (DirectHandle< String > string, MaybeDirectHandle< Map > * internalized_map)
Definition at line 955 of file factory.cc.
                                                                           {
  // The serializer requires internalized strings to be in ReadOnlySpace s.t.
  // other objects referencing the string can be allocated in RO space
  // themselves.
  if (isolate()->enable_ro_allocation_for_snapshot() &&
      isolate()->serializer_enabled()) {
    return StringTransitionStrategy::kCopy;
  }
  // Do not internalize young strings in-place: This allows us to ignore both
  // string table and stub cache on scavenges.
  if (HeapLayout::InYoungGeneration(*string)) {
    return StringTransitionStrategy::kCopy;
  }
  // If the string table is shared, we need to copy if the string is not already
  // in the shared heap.
  if (v8_flags.shared_string_table && !HeapLayout::InAnySharedSpace(*string)) {
    return StringTransitionStrategy::kCopy;
  }
  DCHECK_NOT_NULL(internalized_map);
  DisallowGarbageCollection no_gc;
  // This method may be called concurrently, so snapshot the map from the input
  // string instead of the calling IsType methods on HeapObject, which would
  // reload the map each time.
  Tagged<Map> map = string->map();
  *internalized_map = GetInPlaceInternalizedStringMap(map);
  if (!internalized_map->is_null()) {
    return StringTransitionStrategy::kInPlace;
  }
  if (InstanceTypeChecker::IsInternalizedString(map)) {
    return StringTransitionStrategy::kAlreadyTransitioned;
  }
  return StringTransitionStrategy::kCopy;
}
References DCHECK_NOT_NULL, v8::internal::FactoryBase< Factory >::GetInPlaceInternalizedStringMap(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::InstanceTypeChecker::IsInternalizedString(), isolate(), v8::internal::kAlreadyTransitioned, v8::internal::kCopy, v8::internal::kInPlace, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::v8_flags.
Referenced by v8::internal::InternalizedStringKey::PrepareForInsertion().
ComputeSharingStrategyForString()
StringTransitionStrategy v8::internal::Factory::ComputeSharingStrategyForString (DirectHandle< String > string, MaybeDirectHandle< Map > * shared_map)
Definition at line 1012 of file factory.cc.
                                                                     {
  DCHECK(v8_flags.shared_string_table);
  // TODO(pthier): Avoid copying LO-space strings. Update page flags instead.
  if (!HeapLayout::InAnySharedSpace(*string)) {
    return StringTransitionStrategy::kCopy;
  }
  DCHECK_NOT_NULL(shared_map);
  DisallowGarbageCollection no_gc;
  InstanceType instance_type = string->map()->instance_type();
  if (InstanceTypeChecker::IsSharedString(instance_type)) {
    return StringTransitionStrategy::kAlreadyTransitioned;
  }
  switch (instance_type) {
    case SEQ_TWO_BYTE_STRING_TYPE:
      *shared_map = shared_seq_two_byte_string_map();
      return StringTransitionStrategy::kInPlace;
    case SEQ_ONE_BYTE_STRING_TYPE:
      *shared_map = shared_seq_one_byte_string_map();
      return StringTransitionStrategy::kInPlace;
    case EXTERNAL_TWO_BYTE_STRING_TYPE:
      *shared_map = shared_external_two_byte_string_map();
      return StringTransitionStrategy::kInPlace;
    case EXTERNAL_ONE_BYTE_STRING_TYPE:
      *shared_map = shared_external_one_byte_string_map();
      return StringTransitionStrategy::kInPlace;
    case UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE:
      *shared_map = shared_uncached_external_two_byte_string_map();
      return StringTransitionStrategy::kInPlace;
    case UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE:
      *shared_map = shared_uncached_external_one_byte_string_map();
      return StringTransitionStrategy::kInPlace;
    default:
      return StringTransitionStrategy::kCopy;
  }
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::InstanceTypeChecker::IsSharedString(), v8::internal::kAlreadyTransitioned, v8::internal::kCopy, v8::internal::kInPlace, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SEQ_TWO_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE, and v8::internal::v8_flags.
CopyArrayAndGrow()
template<typename T >
Handle< T > v8::internal::Factory::CopyArrayAndGrow (DirectHandle< T > src, int grow_by, AllocationType allocation) [private]
Definition at line 2642 of file factory.cc.
                                                               {
  DCHECK_LT(0, grow_by);
  DCHECK_LE(grow_by, kMaxInt - src->length());
  int old_len = src->length();
  int new_len = old_len + grow_by;
  // TODO(jgruber,v8:14345): Use T::Allocate instead.
  Tagged<HeapObject> new_object = AllocateRawFixedArray(new_len, allocation);
  DisallowGarbageCollection no_gc;
  new_object->set_map_after_allocation(isolate(), src->map(),
                                       SKIP_WRITE_BARRIER);
  Tagged<T> result = Cast<T>(new_object);
  initialize_length(result, new_len);
  // Copy the content.
  WriteBarrierMode mode = result->GetWriteBarrierMode(no_gc);
  T::CopyElements(isolate(), result, 0, *src, 0, old_len, mode);
  // TODO(jgruber,v8:14345): Enable the static assert once all T's support it:
  // static_assert(T::kElementSize == kTaggedSize);
  MemsetTagged(ObjectSlot(result->RawFieldOfElementAt(old_len)),
               read_only_roots().undefined_value(), grow_by);
  return handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawFixedArray(), DCHECK_LE, DCHECK_LT, v8::internal::handle(), v8::internal::anonymous_namespace{factory.cc}::initialize_length(), isolate(), v8::internal::kMaxInt, v8::internal::MemsetTagged(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by CopyFixedArrayAndGrow(), CopyPropertyArrayAndGrow(), and CopyWeakFixedArrayAndGrow().
CopyArrayWithMap()
template<typename T >
Handle< T > v8::internal::Factory::CopyArrayWithMap (DirectHandle< T > src, DirectHandle< Map > map, AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 2627 of file factory.cc.
                                                               {
  int len = src->length();
  Tagged<HeapObject> new_object = AllocateRawFixedArray(len, allocation);
  DisallowGarbageCollection no_gc;
  new_object->set_map_after_allocation(isolate(), *map, SKIP_WRITE_BARRIER);
  Tagged<T> result = Cast<T>(new_object);
  initialize_length(result, len);
  // Copy the content.
  WriteBarrierMode mode = result->GetWriteBarrierMode(no_gc);
  T::CopyElements(isolate(), result, 0, *src, 0, len, mode);
  return handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawFixedArray(), v8::internal::handle(), v8::internal::anonymous_namespace{factory.cc}::initialize_length(), isolate(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by CopyFixedArray(), CopyFixedArrayWithMap(), CopyJSObjectWithAllocationSite(), and CopyWeakFixedArray().
CopyBytecodeArray()
DirectHandle< BytecodeArray > v8::internal::Factory::CopyBytecodeArray (DirectHandle< BytecodeArray > source)
Definition at line 2989 of file factory.cc.
                                        {
  DirectHandle<BytecodeWrapper> wrapper = NewBytecodeWrapper();
  int size = BytecodeArray::SizeFor(source->length());
  Tagged<BytecodeArray> copy = Cast<BytecodeArray>(AllocateRawWithImmortalMap(
      size, AllocationType::kTrusted, *bytecode_array_map()));
  DisallowGarbageCollection no_gc;
  Tagged<BytecodeArray> raw_source = *source;
  copy->init_self_indirect_pointer(isolate());
  copy->set_length(raw_source->length());
  copy->set_frame_size(raw_source->frame_size());
  copy->set_parameter_count(raw_source->parameter_count());
  copy->set_max_arguments(raw_source->max_arguments());
  copy->set_incoming_new_target_or_generator_register(
      raw_source->incoming_new_target_or_generator_register());
  copy->set_constant_pool(raw_source->constant_pool());
  copy->set_handler_table(raw_source->handler_table());
  copy->set_wrapper(*wrapper);
  if (raw_source->has_source_position_table(kAcquireLoad)) {
    copy->set_source_position_table(
        raw_source->source_position_table(kAcquireLoad), kReleaseStore);
  } else {
    copy->clear_source_position_table(kReleaseStore);
  }
  raw_source->CopyBytecodesTo(copy);
  wrapper->set_bytecode(copy);
  return direct_handle(copy, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), isolate(), v8::kAcquireLoad, v8::kReleaseStore, v8::internal::kTrusted, v8::internal::FactoryBase< Factory >::NewBytecodeWrapper(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::BytecodeArray::SizeFor().
Referenced by v8::internal::SharedFunctionInfo::InstallDebugBytecode().
CopyFixedArray()
Handle< FixedArray > v8::internal::Factory::CopyFixedArray (Handle< FixedArray > array)
Definition at line 2779 of file factory.cc.
                                                                   {
  if (array->length() == 0) return array;
  return CopyArrayWithMap(DirectHandle<FixedArray>(array),
                          direct_handle(array->map(), isolate()));
}
References CopyArrayWithMap(), v8::internal::direct_handle(), and isolate().
Referenced by CopyJSObjectWithAllocationSite(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateArrayLiteral(), v8::internal::Runtime::GetInternalProperties(), v8::internal::FastKeyAccumulator::GetOwnKeysWithUninitializedEnumLength(), and v8::internal::Genesis::TransferIndexedProperties().
CopyFixedArrayAndGrow()
Handle< FixedArray > v8::internal::Factory::CopyFixedArrayAndGrow (DirectHandle< FixedArray > array, int grow_by, AllocationType allocation = AllocationType::kYoung)
Definition at line 2696 of file factory.cc.
                                                                            {
  return CopyArrayAndGrow(array, grow_by, allocation);
}
References CopyArrayAndGrow().
Referenced by v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace(), and v8::internal::WasmTableObject::Grow().
CopyFixedArrayUpTo()
Handle< FixedArray > v8::internal::Factory::CopyFixedArrayUpTo (DirectHandle< FixedArray > array, int new_len, AllocationType allocation = AllocationType::kYoung)
Definition at line 2761 of file factory.cc.
                                                                          {
  DCHECK_LE(0, new_len);
  DCHECK_LE(new_len, array->length());
  if (new_len == 0) return empty_fixed_array();
  Tagged<HeapObject> heap_object = AllocateRawFixedArray(new_len, allocation);
  DisallowGarbageCollection no_gc;
  heap_object->set_map_after_allocation(isolate(), *fixed_array_map(),
                                        SKIP_WRITE_BARRIER);
  Tagged<FixedArray> result = Cast<FixedArray>(heap_object);
  result->set_length(new_len);
  // Copy the content.
  WriteBarrierMode mode = result->GetWriteBarrierMode(no_gc);
  result->CopyElements(isolate(), 0, *array, 0, new_len, mode);
  return handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawFixedArray(), DCHECK_LE, v8::internal::handle(), isolate(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache(), and v8::internal::anonymous_namespace{keys.cc}::ReduceFixedArrayTo().
CopyFixedArrayWithMap()
Handle< FixedArray > v8::internal::Factory::CopyFixedArrayWithMap (DirectHandle< FixedArray > array, DirectHandle< Map > map, AllocationType allocation = AllocationType::kYoung)
Definition at line 2665 of file factory.cc.
                               {
  return CopyArrayWithMap(array, map, allocation);
}
References CopyArrayWithMap().
Referenced by v8::internal::JSObject::MakeElementsWritable(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
CopyFixedDoubleArray()
Handle< FixedDoubleArray > v8::internal::Factory::CopyFixedDoubleArray (Handle< FixedDoubleArray > array)
Definition at line 2785 of file factory.cc.
                                    {
  int len = array->length();
  if (len == 0) return array;
  Handle<FixedDoubleArray> result =
      Cast<FixedDoubleArray>(NewFixedDoubleArray(len));
  Heap::CopyBlock(
      result->address() + offsetof(FixedDoubleArray, length_),
      array->address() + offsetof(FixedDoubleArray, length_),
      FixedDoubleArray::SizeFor(len) - offsetof(FixedDoubleArray, length_));
  return result;
}
References v8::internal::HandleBase::address(), v8::internal::Heap::CopyBlock(), v8::internal::FactoryBase< Factory >::NewFixedDoubleArray(), v8::base::internal::result, and v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::SizeFor().
Referenced by CopyJSObjectWithAllocationSite(), and v8::internal::anonymous_namespace{runtime-literals.cc}::CreateArrayLiteral().
CopyJSObject()
Handle< JSObject > v8::internal::Factory::CopyJSObject (DirectHandle< JSObject > object)
Definition at line 2507 of file factory.cc.
                                                                    {
  return CopyJSObjectWithAllocationSite(source, DirectHandle<AllocationSite>());
}
References CopyJSObjectWithAllocationSite().
Referenced by v8::Object::Clone(), and v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject().
CopyJSObjectWithAllocationSite()
Handle< JSObject > v8::internal::Factory::CopyJSObjectWithAllocationSite (DirectHandle< JSObject > object, DirectHandle< AllocationSite > site)
Definition at line 2511 of file factory.cc.
                                                                      {
  DirectHandle<Map> map(source->map(), isolate());
  // We can only clone regexps, normal objects, api objects, errors or arrays.
  // Copying anything else will break invariants.
  InstanceType instance_type = map->instance_type();
  bool is_clonable_js_type =
      instance_type == JS_REG_EXP_TYPE || instance_type == JS_OBJECT_TYPE ||
      instance_type == JS_ERROR_TYPE || instance_type == JS_ARRAY_TYPE ||
      instance_type == JS_SPECIAL_API_OBJECT_TYPE ||
      InstanceTypeChecker::IsJSApiObject(instance_type);
  bool is_clonable_wasm_type = false;
#if V8_ENABLE_WEBASSEMBLY
  is_clonable_wasm_type = instance_type == WASM_GLOBAL_OBJECT_TYPE ||
                          instance_type == WASM_INSTANCE_OBJECT_TYPE ||
                          instance_type == WASM_MEMORY_OBJECT_TYPE ||
                          instance_type == WASM_MODULE_OBJECT_TYPE ||
                          instance_type == WASM_TABLE_OBJECT_TYPE;
#endif // V8_ENABLE_WEBASSEMBLY
  CHECK(is_clonable_js_type || is_clonable_wasm_type);
  DCHECK(site.is_null() || AllocationSite::CanTrack(instance_type));
  int object_size = map->instance_size();
  int aligned_object_size = ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  int adjusted_object_size = aligned_object_size;
  if (!site.is_null()) {
    DCHECK(V8_ALLOCATION_SITE_TRACKING_BOOL);
    adjusted_object_size +=
        ALIGN_TO_ALLOCATION_ALIGNMENT(sizeof(AllocationMemento));
  }
  Tagged<HeapObject> raw_clone =
      allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
          adjusted_object_size, AllocationType::kYoung);
  DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG(isolate(), raw_clone);
  Heap::CopyBlock(raw_clone.address(), source->address(), object_size);
  Handle<JSObject> clone(Cast<JSObject>(raw_clone), isolate());
  if (v8_flags.enable_unconditional_write_barriers) {
    // By default, we shouldn't need to update the write barrier here, as the
    // clone will be allocated in new space.
    const ObjectSlot start(raw_clone.address());
    const ObjectSlot end(raw_clone.address() + object_size);
    WriteBarrier::ForRange(isolate()->heap(), raw_clone, start, end);
  }
  if (!site.is_null()) {
    Tagged<AllocationMemento> alloc_memento = UncheckedCast<AllocationMemento>(
        Tagged<Object>(raw_clone.ptr() + aligned_object_size));
    InitializeAllocationMemento(alloc_memento, *site);
  }
  SLOW_DCHECK(clone->GetElementsKind() == source->GetElementsKind());
  Tagged<FixedArrayBase> elements = source->elements();
  // Update elements if necessary.
  if (elements->length() > 0) {
    Tagged<FixedArrayBase> elem;
    if (elements->map() == *fixed_cow_array_map()) {
      elem = elements;
    } else if (source->HasDoubleElements()) {
      elem = *CopyFixedDoubleArray(
          handle(Cast<FixedDoubleArray>(elements), isolate()));
    } else {
      elem = *CopyFixedArray(handle(Cast<FixedArray>(elements), isolate()));
    }
    clone->set_elements(elem);
  }
  // Update properties if necessary.
  if (source->HasFastProperties()) {
    Tagged<PropertyArray> properties = source->property_array();
    if (properties->length() > 0) {
      // TODO(gsathya): Do not copy hash code.
      DirectHandle<PropertyArray> prop =
          CopyArrayWithMap(direct_handle(properties, isolate()),
                           direct_handle(properties->map(), isolate()));
      clone->set_raw_properties_or_hash(*prop, kRelaxedStore);
    }
  } else {
    DirectHandle<Object> copied_properties;
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      copied_properties = SwissNameDictionary::ShallowCopy(
          isolate(),
          direct_handle(source->property_dictionary_swiss(), isolate()));
    } else {
      copied_properties =
          CopyFixedArray(handle(source->property_dictionary(), isolate()));
    }
    clone->set_raw_properties_or_hash(*copied_properties, kRelaxedStore);
  }
  return clone;
}
References v8::internal::DirectHandle< T >::address(), v8::internal::Tagged< HeapObject >::address(), ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::HeapAllocator::AllocateRawWith(), allocator(), v8::internal::AllocationSite::CanTrack(), CHECK, CopyArrayWithMap(), v8::internal::Heap::CopyBlock(), CopyFixedArray(), CopyFixedDoubleArray(), v8::internal::DCHECK(), DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG, v8::internal::direct_handle(), end, v8::internal::WriteBarrier::ForRange(), v8::internal::handle(), heap(), InitializeAllocationMemento(), v8::internal::DirectHandle< T >::is_null(), isolate(), v8::kRelaxedStore, v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kYoung, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::SwissNameDictionary::ShallowCopy(), SLOW_DCHECK, V8_ALLOCATION_SITE_TRACKING_BOOL, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and v8::internal::v8_flags.
Referenced by CopyJSObject(), and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
CopyPropertyArrayAndGrow()
DirectHandle< PropertyArray > v8::internal::Factory::CopyPropertyArrayAndGrow (DirectHandle< PropertyArray > array, int grow_by)
Definition at line 2756 of file factory.cc.
                                                    {
  return CopyArrayAndGrow(array, grow_by, AllocationType::kYoung);
}
References CopyArrayAndGrow(), and v8::internal::kYoung.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast().
CopyWeakArrayListAndGrow()
Handle< WeakArrayList > v8::internal::Factory::CopyWeakArrayListAndGrow (DirectHandle< WeakArrayList > array, int grow_by, AllocationType allocation = AllocationType::kYoung)
Definition at line 2713 of file factory.cc.
                                                                             {
  int old_capacity = src->capacity();
  int new_capacity = old_capacity + grow_by;
  DCHECK_GE(new_capacity, old_capacity);
  Handle<WeakArrayList> result =
      NewUninitializedWeakArrayList(new_capacity, allocation);
  DisallowGarbageCollection no_gc;
  Tagged<WeakArrayList> raw = *result;
  int old_len = src->length();
  raw->set_length(old_len);
  // Copy the content.
  WriteBarrierMode mode = raw->GetWriteBarrierMode(no_gc);
  raw->CopyElements(isolate(), 0, *src, 0, old_len, mode);
  MemsetTagged(ObjectSlot(raw->data_start() + old_len),
               read_only_roots().undefined_value(), new_capacity - old_len);
  return result;
}
References DCHECK_GE, isolate(), v8::internal::MemsetTagged(), mode(), NewUninitializedWeakArrayList(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), and v8::base::internal::result.
Referenced by v8::internal::WeakArrayList::EnsureSpace().
CopyWeakFixedArray()
DirectHandle< WeakFixedArray > v8::internal::Factory::CopyWeakFixedArray (DirectHandle< WeakFixedArray > array)
Definition at line 2701 of file factory.cc.
                                      {
  DCHECK(!IsTransitionArray(*src)); // Compacted by GC, this code doesn't work
  return CopyArrayWithMap(src, weak_fixed_array_map(), AllocationType::kOld);
}
References CopyArrayWithMap(), v8::internal::DCHECK(), and v8::internal::kOld.
CopyWeakFixedArrayAndGrow()
DirectHandle< WeakFixedArray > v8::internal::Factory::CopyWeakFixedArrayAndGrow (DirectHandle< WeakFixedArray > array, int grow_by)
Definition at line 2707 of file factory.cc.
                                                   {
  DCHECK(!IsTransitionArray(*src)); // Compacted by GC, this code doesn't work
  return CopyArrayAndGrow(src, grow_by, AllocationType::kOld);
}
References CopyArrayAndGrow(), v8::internal::DCHECK(), and v8::internal::kOld.
Referenced by v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap(), v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity(), and v8::internal::TransitionArray::GrowPrototypeTransitionArray().
CreateCanonicalEmptySwissNameDictionary()
DirectHandle< SwissNameDictionary > v8::internal::Factory::CreateCanonicalEmptySwissNameDictionary ()
Definition at line 592 of file factory.cc.
                                                 {
  // This function is only supposed to be used to create the canonical empty
  // version and should not be used afterwards.
  DCHECK(!ReadOnlyRoots(isolate()).is_initialized(
      RootIndex::kEmptySwissPropertyDictionary));
  ReadOnlyRoots roots(isolate());
  DirectHandle<ByteArray> empty_meta_table =
      NewByteArray(SwissNameDictionary::kMetaTableEnumerationDataStartIndex,
                   AllocationType::kReadOnly);
  Tagged<Map> map = roots.swiss_name_dictionary_map();
  int size = SwissNameDictionary::SizeFor(0);
  Tagged<HeapObject> obj =
      AllocateRawWithImmortalMap(size, AllocationType::kReadOnly, map);
  Tagged<SwissNameDictionary> result = Cast<SwissNameDictionary>(obj);
  result->Initialize(isolate(), *empty_meta_table, 0);
  return direct_handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::DCHECK(), v8::internal::direct_handle(), isolate(), v8::internal::SwissNameDictionary::kMetaTableEnumerationDataStartIndex, v8::internal::kReadOnly, v8::internal::FactoryBase< Factory >::NewByteArray(), v8::base::internal::result, size(), and v8::internal::SwissNameDictionary::SizeFor().
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
CreateClassFunctionMap()
DirectHandle< Map > v8::internal::Factory::CreateClassFunctionMap (DirectHandle< JSFunction > empty_function)
Definition at line 4506 of file factory.cc.
                                             {
  DirectHandle<Map> map = NewContextfulMapForCurrentContext(
      JS_CLASS_CONSTRUCTOR_TYPE, JSFunction::kSizeWithPrototype);
  {
    DisallowGarbageCollection no_gc;
    Tagged<Map> raw_map = *map;
    raw_map->set_has_prototype_slot(true);
    raw_map->set_is_constructor(true);
    raw_map->set_is_prototype_map(true);
    raw_map->set_is_callable(true);
    // Temporarily set constructor to empty function to calm down map verifier.
    raw_map->SetConstructor(*empty_function);
  }
  Map::SetPrototype(isolate(), map, empty_function);
  //
  // Setup descriptors array.
  //
  Map::EnsureDescriptorSlack(isolate(), map, 2);
  PropertyAttributes ro_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
  PropertyAttributes roc_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
  static_assert(JSFunction::kLengthDescriptorIndex == 0);
  { // Add length accessor.
    Descriptor d = Descriptor::AccessorConstant(
        length_string(), function_length_accessor(), roc_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  {
    // Add prototype accessor.
    Descriptor d = Descriptor::AccessorConstant(
        prototype_string(), function_prototype_accessor(), ro_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  LOG(isolate(), MapDetails(*map));
  return map;
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Map::EnsureDescriptorSlack(), isolate(), v8::internal::JSFunction::kSizeWithPrototype, LOG, NewContextfulMapForCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::READ_ONLY, and v8::internal::Map::SetPrototype().
Referenced by v8::internal::Genesis::CreateStrictModeFunctionMaps().
CreateSloppyFunctionMap()
DirectHandle< Map > v8::internal::Factory::CreateSloppyFunctionMap (FunctionMode function_mode, MaybeDirectHandle< JSFunction > maybe_empty_function)
Definition at line 4325 of file factory.cc.
                                                        {
  // TODO(syg): Does sloppy/strict function map distinction need to exist
  // anymore after V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS is removed?
  bool has_prototype = IsFunctionModeWithPrototype(function_mode);
  int header_size = has_prototype ? JSFunction::kSizeWithPrototype
                                  : JSFunction::kSizeWithoutPrototype;
  int descriptors_count = has_prototype ? 3 : 2;
#ifdef V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
  descriptors_count += 2;
#endif
  int inobject_properties_count = 0;
  if (IsFunctionModeWithName(function_mode)) ++inobject_properties_count;
  DirectHandle<Map> map = NewContextfulMapForCurrentContext(
      JS_FUNCTION_TYPE, header_size + inobject_properties_count * kTaggedSize,
      TERMINAL_FAST_ELEMENTS_KIND, inobject_properties_count);
  {
    DisallowGarbageCollection no_gc;
    Tagged<Map> raw_map = *map;
    raw_map->set_has_prototype_slot(has_prototype);
    raw_map->set_is_constructor(has_prototype);
    raw_map->set_is_callable(true);
  }
  DirectHandle<JSFunction> empty_function;
  if (maybe_empty_function.ToHandle(&empty_function)) {
    // Temporarily set constructor to empty function to calm down map verifier.
    map->SetConstructor(*empty_function);
    Map::SetPrototype(isolate(), map, empty_function);
  } else {
    // |maybe_empty_function| is allowed to be empty only during empty function
    // creation.
    DCHECK(IsUndefined(isolate()->raw_native_context()->GetNoCell(
        Context::EMPTY_FUNCTION_INDEX)));
  }
  //
  // Setup descriptors array.
  //
  Map::EnsureDescriptorSlack(isolate(), map, descriptors_count);
  PropertyAttributes ro_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
  PropertyAttributes rw_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE);
  PropertyAttributes roc_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
  int field_index = 0;
  static_assert(
      JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex == 0);
  { // Add length accessor.
    Descriptor d = Descriptor::AccessorConstant(
        length_string(), function_length_accessor(), roc_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  static_assert(
      JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex == 1);
  if (IsFunctionModeWithName(function_mode)) {
    // Add name field.
    DirectHandle<Name> name = isolate()->factory()->name_string();
    Descriptor d = Descriptor::DataField(isolate(), name, field_index++,
                                         roc_attribs, Representation::Tagged());
    map->AppendDescriptor(isolate(), &d);
  } else {
    // Add name accessor.
    Descriptor d = Descriptor::AccessorConstant(
        name_string(), function_name_accessor(), roc_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
#ifdef V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
  { // Add arguments accessor.
    Descriptor d = Descriptor::AccessorConstant(
        arguments_string(), function_arguments_accessor(), ro_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  { // Add caller accessor.
    Descriptor d = Descriptor::AccessorConstant(
        caller_string(), function_caller_accessor(), ro_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
#endif // V8_FUNCTION_ARGUMENTS_CALLER_ARE_OWN_PROPS
  if (IsFunctionModeWithPrototype(function_mode)) {
    // Add prototype accessor.
    PropertyAttributes attribs =
        IsFunctionModeWithWritablePrototype(function_mode) ? rw_attribs
                                                           : ro_attribs;
    Descriptor d = Descriptor::AccessorConstant(
        prototype_string(), function_prototype_accessor(), attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  DCHECK_EQ(inobject_properties_count, field_index);
  DCHECK_EQ(
      0, map->instance_descriptors(isolate())->number_of_slack_descriptors());
  LOG(isolate(), MapDetails(*map));
  return map;
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::Descriptor::DataField(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Map::EnsureDescriptorSlack(), v8::internal::Isolate::factory(), IsFunctionModeWithName(), IsFunctionModeWithPrototype(), IsFunctionModeWithWritablePrototype(), isolate(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kLengthDescriptorIndex, v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::kNameDescriptorIndex, v8::internal::JSFunction::kSizeWithoutPrototype, v8::internal::JSFunction::kSizeWithPrototype, v8::internal::kTaggedSize, LOG, v8::internal::name, NewContextfulMapForCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::READ_ONLY, v8::internal::Map::SetPrototype(), v8::internal::Representation::Tagged(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, and v8::internal::MaybeDirectHandle< T >::ToHandle().
Referenced by v8::internal::Genesis::CreateEmptyFunction(), and v8::internal::Genesis::CreateSloppyModeFunctionMaps().
CreateStrictFunctionMap()
DirectHandle< Map > v8::internal::Factory::CreateStrictFunctionMap (FunctionMode function_mode, DirectHandle< JSFunction > empty_function)
Definition at line 4426 of file factory.cc.
                                                                         {
  bool has_prototype = IsFunctionModeWithPrototype(function_mode);
  int header_size = has_prototype ? JSFunction::kSizeWithPrototype
                                  : JSFunction::kSizeWithoutPrototype;
  int inobject_properties_count = 0;
  // length and prototype accessors or just length accessor.
  int descriptors_count = IsFunctionModeWithPrototype(function_mode) ? 2 : 1;
  if (IsFunctionModeWithName(function_mode)) {
    ++inobject_properties_count; // name property.
  } else {
    ++descriptors_count; // name accessor.
  }
  descriptors_count += inobject_properties_count;
  DirectHandle<Map> map = NewContextfulMapForCurrentContext(
      JS_FUNCTION_TYPE, header_size + inobject_properties_count * kTaggedSize,
      TERMINAL_FAST_ELEMENTS_KIND, inobject_properties_count);
  {
    DisallowGarbageCollection no_gc;
    Tagged<Map> raw_map = *map;
    raw_map->set_has_prototype_slot(has_prototype);
    raw_map->set_is_constructor(has_prototype);
    raw_map->set_is_callable(true);
    // Temporarily set constructor to empty function to calm down map verifier.
    raw_map->SetConstructor(*empty_function);
  }
  Map::SetPrototype(isolate(), map, empty_function);
  //
  // Setup descriptors array.
  //
  Map::EnsureDescriptorSlack(isolate(), map, descriptors_count);
  PropertyAttributes rw_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE);
  PropertyAttributes ro_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
  PropertyAttributes roc_attribs =
      static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
  int field_index = 0;
  static_assert(JSFunction::kLengthDescriptorIndex == 0);
  { // Add length accessor.
    Descriptor d = Descriptor::AccessorConstant(
        length_string(), function_length_accessor(), roc_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  static_assert(JSFunction::kNameDescriptorIndex == 1);
  if (IsFunctionModeWithName(function_mode)) {
    // Add name field.
    DirectHandle<Name> name = isolate()->factory()->name_string();
    Descriptor d = Descriptor::DataField(isolate(), name, field_index++,
                                         roc_attribs, Representation::Tagged());
    map->AppendDescriptor(isolate(), &d);
  } else {
    // Add name accessor.
    Descriptor d = Descriptor::AccessorConstant(
        name_string(), function_name_accessor(), roc_attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  if (IsFunctionModeWithPrototype(function_mode)) {
    // Add prototype accessor.
    PropertyAttributes attribs =
        IsFunctionModeWithWritablePrototype(function_mode) ? rw_attribs
                                                           : ro_attribs;
    Descriptor d = Descriptor::AccessorConstant(
        prototype_string(), function_prototype_accessor(), attribs);
    map->AppendDescriptor(isolate(), &d);
  }
  DCHECK_EQ(inobject_properties_count, field_index);
  DCHECK_EQ(
      0, map->instance_descriptors(isolate())->number_of_slack_descriptors());
  LOG(isolate(), MapDetails(*map));
  return map;
}
References v8::internal::Descriptor::AccessorConstant(), v8::internal::Descriptor::DataField(), DCHECK_EQ, v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::Map::EnsureDescriptorSlack(), v8::internal::Isolate::factory(), IsFunctionModeWithName(), IsFunctionModeWithPrototype(), IsFunctionModeWithWritablePrototype(), isolate(), v8::internal::JSFunction::kSizeWithoutPrototype, v8::internal::JSFunction::kSizeWithPrototype, v8::internal::kTaggedSize, LOG, v8::internal::name, NewContextfulMapForCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::READ_ONLY, v8::internal::Map::SetPrototype(), v8::internal::Representation::Tagged(), and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by v8::internal::Genesis::CreateStrictModeFunctionMaps().
EmptyStringRootIsInitialized()
bool v8::internal::Factory::EmptyStringRootIsInitialized () [private]
Definition at line 4573 of file factory.cc.
                                           {
  return isolate()->roots_table()[RootIndex::kempty_string] != kNullAddress;
}
References isolate(), v8::internal::kNullAddress, and v8::internal::Isolate::roots_table().
GlobalConstantFor()
DirectHandle< Object > v8::internal::Factory::GlobalConstantFor (DirectHandle< Name > name)
Definition at line 4304 of file factory.cc.
                                                                       {
  if (Name::Equals(isolate(), name, undefined_string())) {
    return undefined_value();
  }
  if (Name::Equals(isolate(), name, NaN_string())) return nan_value();
  if (Name::Equals(isolate(), name, Infinity_string())) return infinity_value();
  return Handle<Object>::null();
}
References v8::internal::Name::Equals(), isolate(), v8::internal::name, and v8::internal::Handle< T >::null().
InitializeAllocationMemento()
void v8::internal::Factory::InitializeAllocationMemento (Tagged< AllocationMemento > memento, Tagged< AllocationSite > allocation_site) [private]
Definition at line 329 of file factory.cc.
                                                                               {
  DCHECK(V8_ALLOCATION_SITE_TRACKING_BOOL);
  memento->set_map_after_allocation(isolate(), *allocation_memento_map(),
                                    SKIP_WRITE_BARRIER);
  memento->set_allocation_site(allocation_site, SKIP_WRITE_BARRIER);
  if (v8_flags.allocation_site_pretenuring) {
    allocation_site->IncrementMementoCreateCount();
  }
}
References v8::internal::DCHECK(), isolate(), v8::internal::SKIP_WRITE_BARRIER, V8_ALLOCATION_SITE_TRACKING_BOOL, and v8::internal::v8_flags.
Referenced by AllocateRawWithAllocationSite(), and CopyJSObjectWithAllocationSite().
InitializeJSObjectBody()
void v8::internal::Factory::InitializeJSObjectBody (Tagged< JSObject > obj, Tagged< Map > map, int start_offset) [private]
Definition at line 3135 of file factory.cc.
                                                       {
  DisallowGarbageCollection no_gc;
  if (start_offset == map->instance_size()) return;
  DCHECK_LT(start_offset, map->instance_size());
  // We cannot always fill with one_pointer_filler_map because objects
  // created from API functions expect their embedder fields to be initialized
  // with undefined_value.
  // Pre-allocated fields need to be initialized with undefined_value as well
  // so that object accesses before the constructor completes (e.g. in the
  // debugger) will not cause a crash.
  // In case of Array subclassing the |map| could already be transitioned
  // to different elements kind from the initial map on which we track slack.
  bool in_progress = map->IsInobjectSlackTrackingInProgress();
  obj->InitializeBody(map, start_offset, in_progress,
                      ReadOnlyRoots(isolate()).one_pointer_filler_map_word(),
                      *undefined_value());
  if (in_progress) {
    map->FindRootMap(isolate())->InobjectSlackTrackingStep(isolate());
  }
}
References DCHECK_LT, isolate(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Factory::JSFunctionBuilder::BuildRaw(), and InitializeJSObjectFromMap().
InitializeJSObjectFromMap()
void v8::internal::Factory::InitializeJSObjectFromMap (Tagged< JSObject > obj, Tagged< Object > properties, Tagged< Map > map, NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper) [private]
Definition at line 3110 of file factory.cc.
                                                                            {
  DisallowGarbageCollection no_gc;
  obj->set_raw_properties_or_hash(properties, kRelaxedStore);
  obj->initialize_elements();
  // TODO(1240798): Initialize the object's body using valid initial values
  // according to the object's initial map. For example, if the map's
  // instance type is JS_ARRAY_TYPE, the length field should be initialized
  // to a number (e.g. Smi::zero()) and the elements initialized to a
  // fixed array (e.g. Heap::empty_fixed_array()). Currently, the object
  // verification code has to cope with (temporarily) invalid objects. See
  // for example, JSArray::JSArrayVerify).
  DCHECK_EQ(IsJSApiWrapperObjectMap(map),
            new_js_object_type == NewJSObjectType::kAPIWrapper);
  InitializeJSObjectBody(obj, map,
                         new_js_object_type == NewJSObjectType::kNoAPIWrapper
                             ? JSObject::kHeaderSize
                             : JSAPIObjectWithEmbedderSlots::kHeaderSize);
  if (new_js_object_type == NewJSObjectType::kAPIWrapper) {
    CppHeapObjectWrapper(obj).InitializeCppHeapWrapper();
  }
}
References DCHECK_EQ, v8::internal::CppHeapObjectWrapper::InitializeCppHeapWrapper(), InitializeJSObjectBody(), v8::internal::kAPIWrapper, v8::internal::kNoAPIWrapper, v8::kRelaxedStore, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by NewJSGlobalObject(), NewJSObjectFromMap(), and ReinitializeJSGlobalProxy().
InitializeMap()
Tagged< Map > v8::internal::Factory::InitializeMap (Tagged< Map > map, InstanceType type, int instance_size, ElementsKind elements_kind, int inobject_properties, ReadOnlyRoots roots)
Definition at line 2349 of file factory.cc.
                                                        {
  DisallowGarbageCollection no_gc;
  map->set_bit_field(0);
  map->set_bit_field2(Map::Bits2::NewTargetIsBaseBit::encode(true));
  int bit_field3 =
      Map::Bits3::EnumLengthBits::encode(kInvalidEnumCacheSentinel) |
      Map::Bits3::OwnsDescriptorsBit::encode(true) |
      Map::Bits3::ConstructionCounterBits::encode(Map::kNoSlackTracking) |
      Map::Bits3::IsExtensibleBit::encode(true);
  map->set_bit_field3(bit_field3);
  map->set_instance_type(type);
  map->init_prototype_and_constructor_or_back_pointer(roots);
  map->set_instance_size(instance_size);
  if (InstanceTypeChecker::IsJSObject(type)) {
    // JSObjects that may be allocated in RO space must have RO maps.
    DCHECK_IMPLIES(InstanceTypeChecker::IsMaybeReadOnlyJSObject(type),
                   ReadOnlyHeap::Contains(map));
    // Shared space JS objects have fixed layout and can have RO maps. No other
    // JS objects have RO maps.
    DCHECK_IMPLIES(!IsMaybeReadOnlyJSObjectMap(*map) &&
                       !IsAlwaysSharedSpaceJSObjectMap(*map),
                   !ReadOnlyHeap::Contains(map));
    map->SetInObjectPropertiesStartInWords(instance_size / kTaggedSize -
                                           inobject_properties);
    DCHECK_EQ(map->GetInObjectProperties(), inobject_properties);
    map->set_prototype_validity_cell(roots.invalid_prototype_validity_cell(),
                                     kRelaxedStore);
  } else {
    DCHECK_EQ(inobject_properties, 0);
    map->set_inobject_properties_start_or_constructor_function_index(0);
    map->set_prototype_validity_cell(Map::kPrototypeChainValidSmi,
                                     kRelaxedStore, SKIP_WRITE_BARRIER);
  }
  map->set_dependent_code(DependentCode::empty_dependent_code(roots),
                          SKIP_WRITE_BARRIER);
  map->set_raw_transitions(Smi::zero(), SKIP_WRITE_BARRIER);
  map->SetInObjectUnusedPropertyFields(inobject_properties);
  map->SetInstanceDescriptors(isolate(), roots.empty_descriptor_array(), 0,
                              SKIP_WRITE_BARRIER);
  // Must be called only after |instance_type| and |instance_size| are set.
  map->set_visitor_id(Map::GetVisitorId(map));
  DCHECK(!map->is_in_retained_map_list());
  map->clear_padding();
  map->set_elements_kind(elements_kind);
  if (V8_UNLIKELY(v8_flags.log_maps)) {
    LOG(isolate(), MapCreate(map));
  }
  return map;
}
References v8::internal::bit_field3, v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::DependentCode::empty_dependent_code(), v8::internal::Map::GetVisitorId(), v8::internal::InstanceTypeChecker::IsMaybeReadOnlyJSObject(), isolate(), v8::internal::kInvalidEnumCacheSentinel, v8::internal::Map::kNoSlackTracking, v8::internal::Map::kPrototypeChainValidSmi, v8::kRelaxedStore, v8::internal::kTaggedSize, LOG, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::tracing::type, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::AllocateMap(), and NewMapImpl().
InternalizeExternalString()
template<class StringClass >
template DirectHandle< ExternalTwoByteString > v8::internal::Factory::InternalizeExternalString< ExternalTwoByteString > (DirectHandle< String > string)
Definition at line 991 of file factory.cc.
                                 {
  DirectHandle<Map> map =
      GetInPlaceInternalizedStringMap(string->map()).ToHandleChecked();
  Tagged<StringClass> external_string =
      Cast<StringClass>(New(map, AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  external_string->InitExternalPointerFields(isolate());
  Tagged<StringClass> cast_string = Cast<StringClass>(*string);
  external_string->set_length(cast_string->length());
  external_string->set_raw_hash_field(cast_string->raw_hash_field());
  external_string->SetResource(isolate(), nullptr);
  isolate()->heap()->RegisterExternalString(external_string);
  return direct_handle(external_string, isolate());
}
References v8::internal::direct_handle(), v8::internal::FactoryBase< Factory >::GetInPlaceInternalizedStringMap(), v8::internal::Isolate::heap(), isolate(), v8::internal::kOld, New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::RegisterExternalString(), and v8::internal::string.
Referenced by v8::internal::InternalizedStringKey::PrepareForInsertion().
InternalizeString() [1/4]
Handle<String> v8::internal::Factory::InternalizeString (base::Vector< const char > str, bool convert_encoding = false) [inline]
Definition at line 217 of file factory.h.
                                                                  {
    return InternalizeString(base::Vector<const uint8_t>::cast(str),
                             convert_encoding);
  }
Referenced by v8::internal::DictionaryTemplateInfo::Create(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::Genesis::CreateEmptyFunction(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::Heap::CreateReadOnlyObjects(), v8::Module::CreateSyntheticModule(), v8::internal::RegExpResultsCache::Enter(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::MessageFormatter::Format(), v8::internal::JsonStringifier::InitializeReplacer(), v8::anonymous_namespace{api.cc}::MakeAccessorInfo(), v8::internal::WasmValueObject::New(), v8::anonymous_namespace{api.cc}::NewString(), v8::internal::CodeStubAssembler::PrintToStream(), v8::internal::PropertyKey::PropertyKey(), v8::internal::ValueDeserializer::ReadJSObjectProperties(), v8::internal::SharedStructTypeRegistry::RegisterNoThrow(), v8::internal::ScopeIterator::SetVariableValue(), v8::internal::anonymous_namespace{asm-js.cc}::StdlibMathMember(), v8::internal::compiler::CodeAssembler::StringConstant(), v8::internal::Isolate::SymbolFor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ToInternalString(), and v8::internal::anonymous_namespace{ic.cc}::TryConvertKey().
InternalizeString() [2/4]
Handle< String > v8::internal::FactoryBase< Impl >::InternalizeString
Definition at line 299 of file factory-base.cc.
                                                              {
  SequentialStringKey<uint16_t> key(string, HashSeed(read_only_roots()),
                                    convert_encoding);
  return InternalizeStringWithKey(&key);
}
InternalizeString() [3/4]
Handle<String> v8::internal::FactoryBase< Impl >::InternalizeString
Referenced by InternalizeUtf8String().
InternalizeString() [4/4]
Handle<String> v8::internal::Factory::InternalizeString (const char * str, bool convert_encoding = false) [inline]
Definition at line 223 of file factory.h.
                                                                  {
    return InternalizeString(base::OneByteVector(str), convert_encoding);
  }
References v8::base::OneByteVector().
InternalizeUtf8String() [1/2]
Handle< String > v8::internal::Factory::InternalizeUtf8String (base::Vector< const char > str)
Definition at line 614 of file factory.cc.
                                                                           {
  base::Vector<const uint8_t> utf8_data =
      base::Vector<const uint8_t>::cast(string);
  Utf8Decoder decoder(utf8_data);
  if (decoder.is_ascii()) return InternalizeString(utf8_data);
  if (decoder.is_one_byte()) {
    std::unique_ptr<uint8_t[]> buffer(new uint8_t[decoder.utf16_length()]);
    decoder.Decode(buffer.get(), utf8_data);
    return InternalizeString(
        base::Vector<const uint8_t>(buffer.get(), decoder.utf16_length()));
  }
  std::unique_ptr<uint16_t[]> buffer(new uint16_t[decoder.utf16_length()]);
  decoder.Decode(buffer.get(), utf8_data);
  return InternalizeString(
      base::Vector<const base::uc16>(buffer.get(), decoder.utf16_length()));
}
References v8::internal::Utf8DecoderBase< Decoder >::Decode(), InternalizeString(), v8::internal::Utf8DecoderBase< Decoder >::is_ascii(), v8::internal::Utf8DecoderBase< Decoder >::is_one_byte(), and v8::internal::Utf8DecoderBase< Decoder >::utf16_length().
Referenced by v8::internal::JSObject::AddProperty(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::BUILTIN(), v8::internal::ErrorUtils::Construct(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), v8::internal::wasm::CreateFunctionForCompileTimeImport(), v8::internal::JSReceiver::DefineProperties(), v8::internal::JSReceiver::DefineProperty(), v8::internal::WasmModuleObject::ExtractUtf8StringFromModuleBytes(), v8::internal::wasm::GetExports(), v8::CpuProfileNode::GetFunctionName(), v8::internal::wasm::GetImports(), v8::HeapGraphEdge::GetName(), v8::HeapGraphNode::GetName(), v8::internal::JSReceiver::GetProperty(), v8::CpuProfileNode::GetScriptResourceName(), v8::CpuProfile::GetTitle(), v8::internal::wasm::GetTypeForFunction(), v8::internal::wasm::GetTypeForGlobal(), v8::internal::wasm::GetTypeForMemory(), v8::internal::wasm::GetTypeForTable(), v8::internal::Oddball::Initialize(), v8::internal::Genesis::InitializeGlobal(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallConstant(), v8::internal::anonymous_namespace{builtins-console.cc}::InstallContextFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionAtSymbol(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunctionWithBuiltinId(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallToStringTag(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallTrueValuedProperty(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject(), v8::anonymous_namespace{api.cc}::NewString(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::anonymous_namespace{asm-js.cc}::Report(), v8::internal::SimpleInstallFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleInstallGetterSetter(), v8::internal::wasm::anonymous_namespace{wasm-module.cc}::ToValueTypeString(), and v8::internal::SamplingHeapProfiler::TranslateAllocationNode().
InternalizeUtf8String() [2/2]
Handle<String> v8::internal::Factory::InternalizeUtf8String (const char * str) [inline]
Definition at line 210 of file factory.h.
                                                        {
    return InternalizeUtf8String(base::CStrVector(str));
  }
References v8::base::CStrVector().
IsFunctionModeWithName()
static bool v8::internal::Factory::IsFunctionModeWithName (FunctionMode function_mode) [inline], [static]
Definition at line 1020 of file factory.h.
                                                                 {
    return (function_mode & kWithNameBit) != 0;
  }
References v8::internal::kWithNameBit.
Referenced by CreateSloppyFunctionMap(), and CreateStrictFunctionMap().
IsFunctionModeWithPrototype()
static bool v8::internal::Factory::IsFunctionModeWithPrototype (FunctionMode function_mode) [inline], [static]
Definition at line 1012 of file factory.h.
                                                                      {
    return (function_mode & kWithPrototypeBits) != 0;
  }
References v8::internal::kWithPrototypeBits.
Referenced by CreateSloppyFunctionMap(), and CreateStrictFunctionMap().
IsFunctionModeWithWritablePrototype()
static bool v8::internal::Factory::IsFunctionModeWithWritablePrototype (FunctionMode function_mode) [inline], [static]
Definition at line 1016 of file factory.h.
                                                                              {
    return (function_mode & kWithWritablePrototypeBit) != 0;
  }
References v8::internal::kWithWritablePrototypeBit.
Referenced by CreateSloppyFunctionMap(), and CreateStrictFunctionMap().
isolate()
Isolate* v8::internal::Factory::isolate () const [inline], [private]
Definition at line 1293 of file factory.h.
                           {
    // Downcast to the privately inherited sub-class using c-style casts to
    // avoid undefined behavior (as static_cast cannot cast across private
    // bases).
    // NOLINTNEXTLINE (google-readability-casting)
    return (Isolate*)this; // NOLINT(readability/casting)
  }
Referenced by v8::internal::Isolate::Allocate(), AllocateRawWithAllocationSite(), AllocateSmallOrderedHashTable(), AllocationTypeForInPlaceInternalizableString(), allocator(), v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Check(), v8::internal::Heap::ExternalStringTable::CleanUpAll(), v8::internal::MarkCompactCollector::ClearFullMapTransitions(), v8::internal::MarkCompactCollector::ClearJSWeakRefs(), v8::internal::MarkCompactCollector::ClearNonLiveReferences(), CloneScript(), ComputeInternalizationStrategyForString(), CopyArrayAndGrow(), CopyArrayWithMap(), CopyBytecodeArray(), CopyFixedArray(), CopyFixedArrayUpTo(), CopyJSObjectWithAllocationSite(), CopyWeakArrayListAndGrow(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy::Create(), CreateCanonicalEmptySwissNameDictionary(), CreateClassFunctionMap(), CreateSloppyFunctionMap(), CreateStrictFunctionMap(), v8::internal::Isolate::Current(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Dcheck(), v8::internal::Isolate::Deinitialize(), v8::internal::Isolate::Delete(), v8::internal::TracingAccountingAllocator::Dump(), EmptyStringRootIsInitialized(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FailAssert(), v8::internal::Isolate::FireCallCompletedCallbackInternal(), v8::internal::Isolate::Free(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetObject(), v8::internal::anonymous_namespace{isolate.cc}::GetPromiseMethod(), v8::internal::Isolate::GetStackTraceLimit(), v8::internal::Isolate::GetTurboCfgFileName(), GlobalConstantFor(), InitializeAllocationMemento(), InitializeJSObjectBody(), InitializeMap(), InternalizeExternalString(), v8::internal::wasm::DebugInfoImpl::IsFrameBlackboxed(), v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::isolate(), v8::internal::compiler::InstructionSelector::isolate(), v8::internal::compiler::EscapeAnalysisReducer::isolate(), v8::internal::compiler::EscapeAnalysis::isolate(), v8::internal::compiler::PipelineImpl::isolate(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::isolate(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::isolate(), v8::internal::RegExpMacroAssemblerARM::isolate(), v8::internal::RegExpMacroAssemblerARM64::isolate(), v8::internal::RegExpMacroAssemblerIA32::isolate(), v8::internal::RegExpMacroAssemblerLOONG64::isolate(), v8::internal::RegExpMacroAssemblerMIPS::isolate(), v8::internal::RegExpMacroAssemblerPPC::isolate(), v8::internal::RegExpMacroAssemblerRISCV::isolate(), v8::internal::RegExpMacroAssemblerS390::isolate(), v8::internal::RegExpMacroAssemblerX64::isolate(), v8::internal::wasm::DebugInfoImpl::IsStepping(), v8::internal::Isolate::IterateRegistersAndStackOfSimulator(), New(), NewAccessorInfo(), NewAliasedArgumentsEntry(), NewAllocationSite(), NewArgumentsObject(), NewAtomRegExpData(), NewBlockContext(), NewBreakPoint(), NewBreakPointInfo(), NewBuiltinContext(), NewCallableTask(), NewCallbackTask(), NewCallSiteInfo(), NewCatchContext(), NewCell(), NewCodeObjectForEmbeddedBuiltin(), NewContextCell(), NewContextfulMapForCurrentContext(), NewContextInternal(), NewContextlessMap(), NewCppHeapExternal(), NewDebugEvaluateContext(), NewDebugInfo(), NewDictionaryTemplateInfo(), NewEmbedderDataArray(), NewEnumCache(), NewError(), NewErrorStackData(), NewExperimentalRegExpData(), NewExternal(), NewExternalStringFromOneByte(), NewExternalStringFromTwoByte(), NewFeedbackVector(), NewFillerObject(), NewForeign(), NewFunctionContext(), NewFunctionForTesting(), NewFunctionPrototype(), NewFunctionTemplateInfo(), NewHeapNumberForCodeAssembler(), NewHole(), NewInterceptorInfo(), NewInterpreterData(), NewInvalidStringLengthError(), NewIrRegExpData(), NewJSArray(), NewJSArrayBuffer(), NewJSArrayBufferAndBackingStore(), NewJSArrayForTemplateLiteralArray(), NewJSArrayStorage(), NewJSArrayWithElements(), NewJSArrayWithUnverifiedElements(), NewJSAsyncFromSyncIterator(), NewJSBoundFunction(), NewJSDataViewOrRabGsabDataView(), NewJSDisposableStackBase(), NewJSGeneratorObject(), NewJSGlobalObject(), NewJSIteratorResult(), NewJSMap(), NewJSMessageObject(), NewJSModuleNamespace(), NewJSObject(), NewJSObjectFromMap(), NewJSObjectWithNullProto(), NewJSPromise(), NewJSPromiseWithoutHook(), NewJSProxy(), NewJSSet(), NewJSSharedArrayBuffer(), NewJSSharedStruct(), NewJSStringIterator(), NewJSTypedArray(), NewJSUint8ArraySetFromResult(), NewJSWeakMap(), NewJSWrappedFunction(), NewLoadHandler(), NewManyClosuresCell(), NewMapImpl(), NewMegaDomHandler(), NewModuleContext(), NewNameDictionary(), NewNativeContext(), NewNoClosuresCell(), NewObjectTemplateInfo(), NewOneClosureCell(), NewOrderedHashMap(), NewOrderedHashSet(), NewPrivateNameSymbol(), NewPrivateSymbol(), NewPromiseResolveThenableJobTask(), NewProperSubString(), NewPropertyArray(), NewPropertyCell(), NewPropertyDescriptorObject(), NewProtector(), NewPrototypeInfo(), NewScriptContext(), NewScriptContextTable(), NewSlowJSObjectFromMap(), NewSlowJSObjectWithNullProto(), NewSlowJSObjectWithPropertiesAndElements(), NewSourceTextModule(), NewStackFrameInfo(), NewStackTraceInfo(), NewStoreHandler(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes(), NewStringFromTwoByte(), NewStringFromUtf8(), NewStringFromUtf8SubString(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromUtf8Variant(), NewSuppressedErrorAtDisposal(), NewSurrogatePairString(), NewSymbol(), NewSymbolInternal(), NewSyntheticModule(), NewTransitionArray(), NewTrustedForeign(), NewTuple2(), NewTuple2Uninitialized(), NewUninitializedJSGlobalProxy(), NewUninitializedWeakArrayList(), NewURIError(), NewWithContext(), ObjectLiteralMapFromCache(), v8::internal::MarkCompactCollector::PinPreciseRootsIfNeeded(), v8::internal::anonymous_namespace{isolate.cc}::PredictException(), v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionFromGenerator(), v8::internal::MarkCompactCollector::ProcessMarkingWorklist(), ProcessNewScript(), v8::internal::MarkCompactCollector::ProcessOldBytecodeSFI(), read_only_roots(), v8::internal::anonymous_namespace{isolate.cc}::ReceiverIsForwardingHandler(), ReinitializeJSGlobalProxy(), v8::internal::Isolate::RemoveContextIdCallback(), v8::internal::Isolate::RequestInvalidateNoProfilingProtector(), v8::internal::requires(), v8::internal::SharedHeapSerializer::SerializeStringTable(), v8::internal::Isolate::SetIsolateThreadLocals(), ShadowRealmNewTypeErrorCopy(), v8::internal::anonymous_namespace{factory.cc}::ThrowInvalidEncodedStringBytes(), TryNewFixedArray(), v8::internal::OptimizingCompileTaskExecutor::TryQueueForOptimization(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeaps(), v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::VisitRootPointers(), and v8::internal::anonymous_namespace{isolate.cc}::WalkPromiseTreeInternal().
New()
Tagged< HeapObject > v8::internal::Factory::New (DirectHandle< Map > map, AllocationType allocation) [private]
Definition at line 340 of file factory.cc.
                                                           {
  DCHECK(map->instance_type() != MAP_TYPE);
  int size = map->instance_size();
  Tagged<HeapObject> result =
      allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(size,
                                                                allocation);
  // New space objects are allocated white.
  WriteBarrierMode write_barrier_mode = allocation == AllocationType::kYoung
                                            ? SKIP_WRITE_BARRIER
                                            : UPDATE_WRITE_BARRIER;
  result->set_map_after_allocation(isolate(), *map, write_barrier_mode);
  return result;
}
References v8::internal::HeapAllocator::AllocateRawWith(), allocator(), v8::internal::DCHECK(), isolate(), v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kYoung, v8::base::internal::result, size(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by v8::internal::Factory::JSFunctionBuilder::BuildRaw(), InternalizeExternalString(), NewAccessorInfo(), NewAllocationSite(), NewContextCell(), NewExternalStringFromOneByte(), NewExternalStringFromTwoByte(), NewHole(), NewInterceptorInfo(), NewJSGlobalObject(), NewJSMessageObject(), NewJSProxy(), NewLoadHandler(), NewMegaDomHandler(), NewProperSubString(), NewSourceTextModule(), NewStoreHandler(), and NewSyntheticModule().
NewAccessorInfo()
DirectHandle< AccessorInfo > v8::internal::Factory::NewAccessorInfo ()
Definition at line 1525 of file factory.cc.
                                                    {
  Tagged<AccessorInfo> info =
      Cast<AccessorInfo>(New(accessor_info_map(), AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  info->set_name(*empty_string(), SKIP_WRITE_BARRIER);
  info->set_data(*undefined_value(), SKIP_WRITE_BARRIER);
  info->set_flags(0); // Must clear the flags, it was initialized as undefined.
  info->set_is_sloppy(true);
  info->set_initial_property_attributes(NONE);
  info->init_getter(isolate(), kNullAddress);
  info->init_setter(isolate(), kNullAddress);
  info->clear_padding();
  return direct_handle(info, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::kNullAddress, v8::internal::kOld, New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NONE, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Accessors::MakeAccessor(), and v8::anonymous_namespace{api.cc}::MakeAccessorInfo().
NewAliasedArgumentsEntry()
DirectHandle< AliasedArgumentsEntry > v8::internal::Factory::NewAliasedArgumentsEntry (int aliased_context_slot)
Definition at line 1517 of file factory.cc.
                              {
  auto entry = NewStructInternal<AliasedArgumentsEntry>(
      ALIASED_ARGUMENTS_ENTRY_TYPE, AllocationType::kYoung);
  entry->set_aliased_context_slot(aliased_context_slot);
  return direct_handle(entry, isolate());
}
References v8::internal::direct_handle(), isolate(), and v8::internal::kYoung.
Referenced by v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl().
NewAllocationSite()
Handle< AllocationSite > v8::internal::Factory::NewAllocationSite (bool with_weak_next)
Definition at line 2297 of file factory.cc.
                                                                     {
  DirectHandle<Map> map = with_weak_next
                              ? allocation_site_map()
                              : allocation_site_without_weaknext_map();
  Handle<AllocationSite> site(
      Cast<AllocationSite>(New(map, AllocationType::kOld)), isolate());
  site->Initialize();
  if (with_weak_next) {
    // Link the site
    Cast<AllocationSiteWithWeakNext>(site)->set_weak_next(
        Cast<UnionOf<Undefined, AllocationSiteWithWeakNext>>(
            isolate()->heap()->allocation_sites_list()));
    isolate()->heap()->set_allocation_sites_list(
        *Cast<AllocationSiteWithWeakNext>(site));
  }
  return site;
}
References v8::internal::Cast(), v8::internal::Isolate::heap(), heap(), isolate(), v8::internal::kOld, New(), and v8::internal::Heap::set_allocation_sites_list().
NewArgumentsObject()
Handle< JSObject > v8::internal::Factory::NewArgumentsObject (DirectHandle< JSFunction > callee, int length)
Definition at line 4087 of file factory.cc.
                                                         {
  bool strict_mode_callee = is_strict(callee->shared()->language_mode()) ||
                            !callee->shared()->has_simple_parameters();
  DirectHandle<Map> map = strict_mode_callee
                              ? isolate()->strict_arguments_map()
                              : isolate()->sloppy_arguments_map();
  AllocationSiteUsageContext context(isolate(), Handle<AllocationSite>(),
                                     false);
  DCHECK(!isolate()->has_exception());
  Handle<JSObject> result = NewJSObjectFromMap(map);
  DirectHandle<Smi> value(Smi::FromInt(length), isolate());
  Object::SetProperty(isolate(), result, length_string(), value,
                      StoreOrigin::kMaybeKeyed,
                      Just(ShouldThrow::kThrowOnError))
      .Assert();
  if (!strict_mode_callee) {
    Object::SetProperty(isolate(), result, callee_string(), callee,
                        StoreOrigin::kMaybeKeyed,
                        Just(ShouldThrow::kThrowOnError))
        .Assert();
  }
  return result;
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), v8::internal::is_strict(), isolate(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, length, NewJSObjectFromMap(), v8::base::internal::result, v8::internal::Object::SetProperty(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), and v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments().
NewAtomRegExpData()
DirectHandle< RegExpData > v8::internal::Factory::NewAtomRegExpData (DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< String > pattern)
Definition at line 4218 of file factory.cc.
                                  {
  DirectHandle<RegExpDataWrapper> wrapper = NewRegExpDataWrapper();
  int size = AtomRegExpData::kSize;
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(
      size, AllocationType::kTrusted, read_only_roots().atom_regexp_data_map());
  DisallowGarbageCollection no_gc;
  Tagged<AtomRegExpData> instance = Cast<AtomRegExpData>(result);
  instance->init_self_indirect_pointer(isolate());
  instance->set_type_tag(RegExpData::Type::ATOM);
  instance->set_source(*source);
  instance->set_flags(flags);
  instance->set_pattern(*pattern);
  Tagged<RegExpDataWrapper> raw_wrapper = *wrapper;
  instance->set_wrapper(raw_wrapper);
  raw_wrapper->set_data(instance);
  return direct_handle(instance, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::RegExpData::ATOM, v8::internal::direct_handle(), v8::internal::flags, isolate(), v8::internal::kTrusted, v8::internal::FactoryBase< Factory >::NewRegExpDataWrapper(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), v8::base::internal::result, and size().
Referenced by SetRegExpAtomData().
NewBlockContext()
DirectHandle< Context > v8::internal::Factory::NewBlockContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info)
Definition at line 1473 of file factory.cc.
                                                                        {
  DCHECK_IMPLIES(scope_info->scope_type() != BLOCK_SCOPE,
                 scope_info->scope_type() == CLASS_SCOPE);
  int variadic_part_length = scope_info->ContextLength();
  Tagged<Context> context = NewContextInternal(
      isolate()->block_context_map(), Context::SizeFor(variadic_part_length),
      variadic_part_length, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG(isolate(), context);
  context->set_scope_info(*scope_info, SKIP_WRITE_BARRIER);
  context->set_previous(*previous, SKIP_WRITE_BARRIER);
  return direct_handle(context, isolate());
}
References v8::internal::BLOCK_SCOPE, v8::internal::CLASS_SCOPE, DCHECK_IMPLIES, DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG, v8::internal::direct_handle(), isolate(), v8::internal::kYoung, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::SizeFor(), and v8::internal::SKIP_WRITE_BARRIER.
NewBreakPoint()
Handle< BreakPoint > v8::internal::Factory::NewBreakPoint (int id, DirectHandle< String > condition)
Definition at line 4033 of file factory.cc.
                                                                          {
  auto new_break_point =
      NewStructInternal<BreakPoint>(BREAK_POINT_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  new_break_point->set_id(id);
  new_break_point->set_condition(*condition);
  return handle(new_break_point, isolate());
}
References v8::internal::handle(), isolate(), v8::internal::kOld, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Debug::RemoveBreakpoint(), v8::internal::Debug::SetBreakpointForFunction(), and v8::internal::Debug::SetBreakPointForScript().
NewBreakPointInfo()
DirectHandle< BreakPointInfo > v8::internal::Factory::NewBreakPointInfo (int source_position)
Definition at line 4023 of file factory.cc.
                                                                           {
  auto new_break_point_info = NewStructInternal<BreakPointInfo>(
      BREAK_POINT_INFO_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  new_break_point_info->set_source_position(source_position);
  new_break_point_info->set_break_points(*undefined_value(),
                                         SKIP_WRITE_BARRIER);
  return direct_handle(new_break_point_info, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::WasmScript::AddBreakpointToInfo(), and v8::internal::DebugInfo::SetBreakPoint().
NewBuiltinContext()
DirectHandle< Context > v8::internal::Factory::NewBuiltinContext (DirectHandle< NativeContext > native_context, int length)
Definition at line 1488 of file factory.cc.
                                                                          {
  DCHECK_LE(Context::MIN_CONTEXT_SLOTS, variadic_part_length);
  Tagged<Context> context = NewContextInternal(
      isolate()->function_context_map(), Context::SizeFor(variadic_part_length),
      variadic_part_length, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG(isolate(), context);
  context->set_scope_info(read_only_roots().empty_scope_info(),
                          SKIP_WRITE_BARRIER);
  context->set_previous(*native_context, SKIP_WRITE_BARRIER);
  return direct_handle(context, isolate());
}
References DCHECK_LE, DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG, v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::Context::MIN_CONTEXT_SLOTS, v8::internal::native_context, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), v8::internal::Context::SizeFor(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::BUILTIN(), v8::internal::JSDisposableStackBase::CheckValueAndGetDisposeMethod(), v8::internal::anonymous_namespace{builtins-intl.cc}::CreateBoundFunction(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::SetAsyncUnlockHandlers(), and v8::internal::JSAtomicsCondition::WaitAsync().
NewCallableTask()
DirectHandle< CallableTask > v8::internal::Factory::NewCallableTask (DirectHandle< JSReceiver > callable, DirectHandle< Context > context)
Definition at line 1627 of file factory.cc.
                                                                      {
  DCHECK(IsCallable(*callable));
  auto microtask = NewStructInternal<CallableTask>(CALLABLE_TASK_TYPE,
                                                   AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  microtask->set_callable(*callable, SKIP_WRITE_BARRIER);
  microtask->set_context(*context, SKIP_WRITE_BARRIER);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  microtask->set_continuation_preserved_embedder_data(
      isolate()->isolate_data()->continuation_preserved_embedder_data(),
      SKIP_WRITE_BARRIER);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return direct_handle(microtask, isolate());
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::MicrotaskQueue::EnqueueMicrotask().
NewCallbackTask()
DirectHandle< CallbackTask > v8::internal::Factory::NewCallbackTask (DirectHandle< Foreign > callback, DirectHandle< Foreign > data)
Definition at line 1643 of file factory.cc.
                                                                {
  auto microtask = NewStructInternal<CallbackTask>(CALLBACK_TASK_TYPE,
                                                   AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  microtask->set_callback(*callback, SKIP_WRITE_BARRIER);
  microtask->set_data(*data, SKIP_WRITE_BARRIER);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  microtask->set_continuation_preserved_embedder_data(
      isolate()->isolate_data()->continuation_preserved_embedder_data(),
      SKIP_WRITE_BARRIER);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return direct_handle(microtask, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::MicrotaskQueue::EnqueueMicrotask().
NewCallSiteInfo()
Handle< CallSiteInfo > v8::internal::Factory::NewCallSiteInfo (DirectHandle< JSAny > receiver_or_instance, DirectHandle< UnionOf< Smi, JSFunction >> function, DirectHandle< HeapObject > code_object, int code_offset_or_source_position, int flags, DirectHandle< FixedArray > parameters)
Definition at line 4043 of file factory.cc.
                                                    {
  auto info = NewStructInternal<CallSiteInfo>(CALL_SITE_INFO_TYPE,
                                              AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  info->set_receiver_or_instance(*receiver_or_instance, SKIP_WRITE_BARRIER);
  info->set_function(*function, SKIP_WRITE_BARRIER);
  info->set_code_object(*code_object, SKIP_WRITE_BARRIER);
  info->set_code_offset_or_source_position(code_offset_or_source_position);
  info->set_flags(flags);
  info->set_parameters(*parameters, SKIP_WRITE_BARRIER);
  return handle(info, isolate());
}
References v8::internal::flags, v8::internal::handle(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
NewCatchContext()
DirectHandle< Context > v8::internal::Factory::NewCatchContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info, DirectHandle< Object > thrown_object)
Definition at line 1412 of file factory.cc.
                                        {
  DCHECK_EQ(scope_info->scope_type(), CATCH_SCOPE);
  static_assert(Context::MIN_CONTEXT_SLOTS == Context::THROWN_OBJECT_INDEX);
  // TODO(ishell): Take the details from CatchContext class.
  int variadic_part_length = Context::MIN_CONTEXT_SLOTS + 1;
  Tagged<Context> context = NewContextInternal(
      isolate()->catch_context_map(), Context::SizeFor(variadic_part_length),
      variadic_part_length, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG(isolate(), context);
  context->set_scope_info(*scope_info, SKIP_WRITE_BARRIER);
  context->set_previous(*previous, SKIP_WRITE_BARRIER);
  context->SetNoCell(Context::THROWN_OBJECT_INDEX, *thrown_object,
                     SKIP_WRITE_BARRIER);
  return direct_handle(context, isolate());
}
References v8::internal::CATCH_SCOPE, DCHECK_EQ, DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG, v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::Context::MIN_CONTEXT_SLOTS, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::SizeFor(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Context::THROWN_OBJECT_INDEX.
NewCell() [1/2]
Handle< Cell > v8::internal::Factory::NewCell ()
Definition at line 2198 of file factory.cc.
                              {
  static_assert(Cell::kSize <= kMaxRegularHeapObjectSize);
  Tagged<Cell> result = Cast<Cell>(AllocateRawWithImmortalMap(
      Cell::kSize, AllocationType::kOld, *cell_map()));
  result->set_value(read_only_roots().undefined_value(),
                    WriteBarrierMode::SKIP_WRITE_BARRIER);
  return handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::handle(), isolate(), v8::internal::kMaxRegularHeapObjectSize, v8::internal::kOld, read_only_roots(), v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
NewCell() [2/2]
Handle< Cell > v8::internal::Factory::NewCell (Tagged< Smi > value)
Definition at line 2189 of file factory.cc.
                                               {
  static_assert(Cell::kSize <= kMaxRegularHeapObjectSize);
  Tagged<Cell> result = Cast<Cell>(AllocateRawWithImmortalMap(
      Cell::kSize, AllocationType::kOld, *cell_map()));
  DisallowGarbageCollection no_gc;
  result->set_value(value, WriteBarrierMode::SKIP_WRITE_BARRIER);
  return handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::handle(), isolate(), v8::internal::kMaxRegularHeapObjectSize, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::SourceTextModule::CreateExport(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::SyntheticModule::PrepareInstantiate(), and v8::internal::SourceTextModule::ResolveImport().
NewCodeObjectForEmbeddedBuiltin()
DirectHandle< Code > v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin (DirectHandle< Code > code, Address off_heap_entry)
Definition at line 2937 of file factory.cc.
                                                     {
  CHECK_NOT_NULL(isolate()->embedded_blob_code());
  CHECK_NE(0, isolate()->embedded_blob_code_size());
  CHECK(Builtins::IsIsolateIndependentBuiltin(*code));
  DCHECK(code->has_instruction_stream()); // Just generated as on-heap code.
  DCHECK(Builtins::IsBuiltinId(code->builtin_id()));
  DCHECK_EQ(code->inlined_bytecode_size(), 0);
  DCHECK_EQ(code->osr_offset(), BytecodeOffset::None());
  DCHECK_EQ(code->raw_deoptimization_data_or_interpreter_data(), Smi::zero());
  // .. because we don't explicitly initialize these flags:
  DCHECK(!code->marked_for_deoptimization());
  DCHECK(!code->can_have_weak_objects());
  DCHECK(!code->embedded_objects_cleared());
  // This check would fail. We explicitly clear any existing position tables
  // below. Note this isn't strictly necessary - we could keep the position
  // tables if we'd properly allocate them into RO space when needed.
  // DCHECK_EQ(code->raw_position_table(), *empty_byte_array());
  NewCodeOptions new_code_options = {
      code->kind(),
      code->builtin_id(),
      code->is_context_specialized(),
      code->is_turbofanned(),
      code->parameter_count(),
      code->instruction_size(),
      code->metadata_size(),
      code->inlined_bytecode_size(),
      code->osr_offset(),
      code->handler_table_offset(),
      code->constant_pool_offset(),
      code->code_comments_offset(),
      code->jump_table_info_offset(),
      code->unwinding_info_offset(),
      MaybeHandle<TrustedObject>{},
      MaybeHandle<DeoptimizationData>{},
      /*bytecode_offset_table=*/MaybeHandle<TrustedByteArray>{},
      /*source_position_table=*/MaybeHandle<TrustedByteArray>{},
      MaybeHandle<InstructionStream>{},
      off_heap_entry,
  };
  Handle<Code> new_code = NewCode(new_code_options);
#if V8_ENABLE_GEARBOX
  if (Builtins::IsGearboxPlaceholder(new_code->builtin_id())) {
    new_code->set_is_gearbox_placeholder_builtin(true);
  }
#endif // V8_ENABLE_GEARBOX
  return new_code;
}
References CHECK, CHECK_NE, CHECK_NOT_NULL, code, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Builtins::IsBuiltinId(), v8::internal::Builtins::IsIsolateIndependentBuiltin(), isolate(), v8::internal::FactoryBase< Factory >::NewCode(), v8::internal::BytecodeOffset::None(), and v8::internal::Smi::zero().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects().
NewContextCell()
DirectHandle< ContextCell > v8::internal::Factory::NewContextCell (DirectHandle< JSAny > value, AllocationType allocation_type = AllocationType::kYoung)
Definition at line 1502 of file factory.cc.
                                                               {
  Tagged<ContextCell> cell =
      Cast<ContextCell>(New(context_cell_map(), allocation_type));
  DisallowGarbageCollection no_gc;
  cell->set_tagged_value(*value, SKIP_WRITE_BARRIER);
  cell->set_dependent_code(
      DependentCode::empty_dependent_code(ReadOnlyRoots(isolate())),
      SKIP_WRITE_BARRIER);
  cell->set_float64_value(0);
  cell->set_state(ContextCell::kConst);
  cell->clear_padding();
  return direct_handle(cell, isolate());
}
References v8::internal::direct_handle(), v8::internal::DependentCode::empty_dependent_code(), isolate(), v8::internal::ContextCell::kConst, New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::Heap::CreateReadOnlyObjects(), and v8::internal::Context::Set().
NewContextfulMap() [1/2]
DirectHandle< Map > v8::internal::Factory::NewContextfulMap (DirectHandle< JSReceiver > creation_context_holder, InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap)
Definition at line 2436 of file factory.cc.
                                    {
  // TODO(ishell): There should probably be a DCHECK(IsNCSpecific(type)) here.
  auto meta_map_provider = [creation_context_holder] {
    // Tie new map to the creation context of given |creation_context_holder|
    // object.
    Tagged<Map> meta_map = creation_context_holder->map()->map();
    DCHECK(IsMapMap(meta_map));
    return meta_map;
  };
  DirectHandle<Map> map =
      NewMapImpl(meta_map_provider, type, instance_size, elements_kind,
                 inobject_properties, allocation_type);
  return map;
}
References v8::internal::DCHECK(), NewMapImpl(), and v8::internal::tracing::type.
Referenced by v8::internal::ApiNatives::CreateApiFunction(), v8::internal::CreateStructMap(), v8::internal::JSFunction::EnsureHasInitialMap(), and v8::internal::anonymous_namespace{wasm-js.cc}::SetupConstructor().
NewContextfulMap() [2/2]
DirectHandle< Map > v8::internal::Factory::NewContextfulMap (DirectHandle< NativeContext > native_context, InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap)
Definition at line 2454 of file factory.cc.
                                    {
  DCHECK(InstanceTypeChecker::IsNativeContextSpecific(type) ||
#if V8_ENABLE_WEBASSEMBLY
         InstanceTypeChecker::IsWasmStruct(type) ||
#endif // V8_ENABLE_WEBASSEMBLY
         InstanceTypeChecker::IsMap(type));
  auto meta_map_provider = [native_context] {
    // Tie new map to given native context.
    return native_context->meta_map();
  };
  DirectHandle<Map> map =
      NewMapImpl(meta_map_provider, type, instance_size, elements_kind,
                 inobject_properties, allocation_type);
  return map;
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsNativeContextSpecific(), v8::internal::native_context, NewMapImpl(), and v8::internal::tracing::type.
NewContextfulMapForCurrentContext()
Handle< Map > v8::internal::Factory::NewContextfulMapForCurrentContext (InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap)
Definition at line 2473 of file factory.cc.
                                                             {
  DCHECK(InstanceTypeChecker::IsNativeContextSpecific(type) ||
         InstanceTypeChecker::IsMap(type));
  auto meta_map_provider = [this] {
    // Tie new map to current native context.
    return isolate()->raw_native_context()->meta_map();
  };
  Handle<Map> map =
      NewMapImpl(meta_map_provider, type, instance_size, elements_kind,
                 inobject_properties, allocation_type);
  return map;
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsNativeContextSpecific(), isolate(), NewMapImpl(), v8::internal::Isolate::raw_native_context(), and v8::internal::tracing::type.
Referenced by v8::internal::Genesis::CreateAsyncIteratorMaps(), CreateClassFunctionMap(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), v8::internal::Genesis::CreateInitialMapForArraySubclass(), v8::internal::Genesis::CreateJSProxyMaps(), CreateSloppyFunctionMap(), CreateStrictFunctionMap(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::Genesis::InstallTypedArray(), and v8::internal::WasmValueObject::New().
NewContextInternal()
Tagged< Context > v8::internal::Factory::NewContextInternal (DirectHandle< Map > map, int size, int variadic_part_length, AllocationType allocation) [private]
Definition at line 1260 of file factory.cc.
                                                                       {
  DCHECK_LE(Context::kTodoHeaderSize, size);
  DCHECK(IsAligned(size, kTaggedSize));
  DCHECK_LE(Context::MIN_CONTEXT_SLOTS, variadic_part_length);
  DCHECK_LE(Context::SizeFor(variadic_part_length), size);
  Tagged<HeapObject> result =
      allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(size,
                                                                allocation);
  result->set_map_after_allocation(isolate(), *map);
  DisallowGarbageCollection no_gc;
  Tagged<Context> context = Cast<Context>(result);
  context->set_length(variadic_part_length);
  DCHECK_EQ(context->SizeFromMap(*map), size);
  if (size > Context::kTodoHeaderSize) {
    ObjectSlot start = context->RawField(Context::kTodoHeaderSize);
    ObjectSlot end = context->RawField(size);
    size_t slot_count = end - start;
    MemsetTagged(start, *undefined_value(), slot_count);
  }
  return context;
}
References v8::internal::HeapAllocator::AllocateRawWith(), allocator(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, end, IsAligned(), isolate(), v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kTaggedSize, v8::internal::Context::kTodoHeaderSize, v8::internal::MemsetTagged(), v8::internal::Context::MIN_CONTEXT_SLOTS, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, size(), and v8::internal::Context::SizeFor().
Referenced by NewBlockContext(), NewBuiltinContext(), NewCatchContext(), NewDebugEvaluateContext(), NewFunctionContext(), NewModuleContext(), NewNativeContext(), NewScriptContext(), and NewWithContext().
NewContextlessMap()
Handle< Map > v8::internal::Factory::NewContextlessMap (InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap)
Definition at line 2488 of file factory.cc.
                                                                       {
  DCHECK(!InstanceTypeChecker::IsNativeContextSpecific(type) ||
         type == NATIVE_CONTEXT_TYPE || // just during NativeContext creation.
         type == JS_GLOBAL_PROXY_TYPE || // might be a placeholder object.
         type == JS_SPECIAL_API_OBJECT_TYPE || // might be a remote Api object.
         InstanceTypeChecker::IsMap(type));
  auto meta_map_provider = [this] {
    // The new map is not tied to any context.
    return ReadOnlyRoots(isolate()).meta_map();
  };
  Handle<Map> map =
      NewMapImpl(meta_map_provider, type, instance_size, elements_kind,
                 inobject_properties, allocation_type);
  return map;
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsNativeContextSpecific(), isolate(), NewMapImpl(), and v8::internal::tracing::type.
Referenced by v8::internal::CreateArrayMap(), v8::internal::CreateFuncRefMap(), v8::internal::CreateStructMap(), v8::internal::Genesis::Genesis(), v8::internal::ApiNatives::InstantiateRemoteObject(), NewNativeContext(), and NewUninitializedJSGlobalProxy().
NewCopiedSubstring()
Handle< String > v8::internal::Factory::NewCopiedSubstring (DirectHandle< String > str, uint32_t begin, uint32_t length)
Definition at line 1065 of file factory.cc.
                                                                            {
  DCHECK(str->IsFlat()); // Callers must flatten.
  DCHECK_GT(length, 0); // Callers must handle empty string.
  bool one_byte;
  {
    DisallowGarbageCollection no_gc;
    String::FlatContent flat = str->GetFlatContent(no_gc);
    if (flat.IsOneByte()) {
      one_byte = true;
    } else {
      one_byte = String::IsOneByte(flat.ToUC16Vector().data() + begin, length);
    }
  }
  if (one_byte) {
    Handle<SeqOneByteString> result =
        NewRawOneByteString(length).ToHandleChecked();
    DisallowGarbageCollection no_gc;
    uint8_t* dest = result->GetChars(no_gc);
    String::WriteToFlat(*str, dest, begin, length);
    return result;
  } else {
    Handle<SeqTwoByteString> result =
        NewRawTwoByteString(length).ToHandleChecked();
    DisallowGarbageCollection no_gc;
    base::uc16* dest = result->GetChars(no_gc);
    String::WriteToFlat(*str, dest, begin, length);
    return result;
  }
}
References begin, v8::base::Vector< T >::data(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::IsOneByte(), length, v8::internal::FactoryBase< Factory >::NewRawOneByteString(), v8::internal::FactoryBase< Factory >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::String::FlatContent::ToUC16Vector(), and v8::internal::String::WriteToFlat().
Referenced by NewProperSubString(), and v8::internal::RUNTIME_FUNCTION().
NewCppHeapExternal()
Handle< CppHeapExternalObject > v8::internal::Factory::NewCppHeapExternal (AllocationType allocation = AllocationType::kYoung)
Definition at line 2928 of file factory.cc.
                                    {
  Tagged<CppHeapExternalObject> external = Cast<CppHeapExternalObject>(
      AllocateRawWithAllocationSite(cpp_heap_external_map(), allocation_type,
                                    DirectHandle<AllocationSite>::null()));
  CppHeapObjectWrapper(external).InitializeCppHeapWrapper();
  return handle(external, isolate());
}
References AllocateRawWithAllocationSite(), v8::internal::handle(), v8::internal::CppHeapObjectWrapper::InitializeCppHeapWrapper(), and isolate().
Referenced by v8::CppHeapExternal::NewImpl().
NewDebugEvaluateContext()
Handle< Context > v8::internal::Factory::NewDebugEvaluateContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info, DirectHandle< JSReceiver > extension, DirectHandle< Context > wrapped)
Definition at line 1431 of file factory.cc.
                                                                       {
  DCHECK(scope_info->IsDebugEvaluateScope());
  DirectHandle<HeapObject> ext = extension.is_null()
                                     ? Cast<HeapObject>(undefined_value())
                                     : Cast<HeapObject>(extension);
  // TODO(ishell): Take the details from DebugEvaluateContextContext class.
  int variadic_part_length = Context::MIN_CONTEXT_EXTENDED_SLOTS + 1;
  Tagged<Context> context =
      NewContextInternal(isolate()->debug_evaluate_context_map(),
                         Context::SizeFor(variadic_part_length),
                         variadic_part_length, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG(isolate(), context);
  context->set_scope_info(*scope_info, SKIP_WRITE_BARRIER);
  context->set_previous(*previous, SKIP_WRITE_BARRIER);
  context->set_extension(*ext, SKIP_WRITE_BARRIER);
  if (!wrapped.is_null()) {
    context->SetNoCell(Context::WRAPPED_CONTEXT_INDEX, *wrapped,
                       SKIP_WRITE_BARRIER);
  }
  return handle(context, isolate());
}
References v8::internal::DCHECK(), DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG, v8::internal::handle(), v8::internal::DirectHandle< T >::is_null(), isolate(), v8::internal::kYoung, v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::SizeFor(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Context::WRAPPED_CONTEXT_INDEX.
Referenced by v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder(), and v8::internal::DebugEvaluate::WithTopmostArguments().
NewDebugInfo()
Handle< DebugInfo > v8::internal::Factory::NewDebugInfo (DirectHandle< SharedFunctionInfo > shared)
Definition at line 4004 of file factory.cc.
                                             {
  DCHECK(!shared->HasDebugInfo(isolate()));
  auto debug_info =
      NewStructInternal<DebugInfo>(DEBUG_INFO_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  Tagged<SharedFunctionInfo> raw_shared = *shared;
  debug_info->set_flags(DebugInfo::kNone, kRelaxedStore);
  debug_info->set_shared(raw_shared);
  debug_info->set_debugger_hints(0);
  DCHECK_EQ(DebugInfo::kNoDebuggingId, debug_info->debugging_id());
  debug_info->set_break_points(*empty_fixed_array(), SKIP_WRITE_BARRIER);
  debug_info->clear_original_bytecode_array();
  debug_info->clear_debug_bytecode_array();
  return handle(debug_info, isolate());
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::handle(), isolate(), v8::internal::DebugInfo::kNoDebuggingId, v8::internal::kOld, v8::kRelaxedStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Debug::GetOrCreateDebugInfo().
NewDictionaryTemplateInfo()
DirectHandle< DictionaryTemplateInfo > v8::internal::Factory::NewDictionaryTemplateInfo (DirectHandle< FixedArray > property_names)
Definition at line 4740 of file factory.cc.
                                             {
  const int size = DictionaryTemplateInfo::SizeFor();
  DirectHandle<Map> map = dictionary_template_info_map();
  Tagged<DictionaryTemplateInfo> obj = Cast<DictionaryTemplateInfo>(
      AllocateRawWithImmortalMap(size, AllocationType::kOld, *map));
  InitializeTemplate(obj, true);
  obj->set_property_names(*property_names);
  return direct_handle(obj, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), v8::internal::anonymous_namespace{factory.cc}::InitializeTemplate(), isolate(), v8::internal::kOld, and size().
Referenced by v8::internal::DictionaryTemplateInfo::Create().
NewEmbedderDataArray()
DirectHandle< EmbedderDataArray > v8::internal::Factory::NewEmbedderDataArray (int length)
Definition at line 489 of file factory.cc.
                                                                        {
  DCHECK_LE(0, length);
  int size = EmbedderDataArray::SizeFor(length);
  Tagged<EmbedderDataArray> array =
      Cast<EmbedderDataArray>(AllocateRawWithImmortalMap(
          size, AllocationType::kYoung, *embedder_data_array_map()));
  DisallowGarbageCollection no_gc;
  array->set_length(length);
  if (length > 0) {
    for (int i = 0; i < length; i++) {
      // TODO(v8): consider initializing embedded data array with Smi::zero().
      EmbedderDataSlot(array, i).Initialize(*undefined_value());
    }
  }
  return direct_handle(array, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), DCHECK_LE, v8::internal::direct_handle(), v8::internal::EmbedderDataSlot::Initialize(), isolate(), v8::internal::kYoung, length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::EmbedderDataArray::SizeFor().
Referenced by v8::internal::EmbedderDataArray::EnsureCapacity(), and v8::internal::Genesis::InitializeGlobal().
NewEnumCache()
DirectHandle< EnumCache > v8::internal::Factory::NewEnumCache (DirectHandle< FixedArray > keys, DirectHandle< FixedArray > indices, AllocationType allocation = AllocationType::kOld)
Definition at line 381 of file factory.cc.
                                                                         {
  DCHECK(allocation == AllocationType::kOld ||
         allocation == AllocationType::kSharedOld);
  DCHECK_EQ(allocation == AllocationType::kSharedOld,
            HeapLayout::InAnySharedSpace(*keys) &&
                HeapLayout::InAnySharedSpace(*indices));
  auto result = NewStructInternal<EnumCache>(ENUM_CACHE_TYPE, allocation);
  DisallowGarbageCollection no_gc;
  result->set_keys(*keys);
  result->set_indices(*indices);
  return direct_handle(result, isolate());
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::HeapLayout::InAnySharedSpace(), isolate(), v8::internal::kOld, v8::internal::kSharedOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::DescriptorArray::InitializeOrChangeEnumCache().
NewError() [1/3]
Handle< JSObject > v8::internal::Factory::NewError (DirectHandle< JSFunction > constructor, DirectHandle< String > message, DirectHandle< Object > options = {})
Definition at line 2817 of file factory.cc.
                                                                 {
  // Construct a new error object. If an exception is thrown, use the exception
  // as the result.
  DirectHandle<Object> no_caller;
  if (options.is_null()) options = undefined_value();
  return ErrorUtils::Construct(isolate(), constructor, constructor, message,
                               options, SKIP_NONE, no_caller,
                               ErrorUtils::StackTraceCollection::kEnabled)
      .ToHandleChecked();
}
References v8::internal::ErrorUtils::Construct(), v8::internal::DirectHandle< T >::is_null(), isolate(), v8::internal::ErrorUtils::kEnabled, and v8::internal::SKIP_NONE.
Referenced by v8::ValueSerializer::Delegate::AdoptSharedValueConveyor(), v8::internal::BUILTIN(), wasm::anonymous_namespace{c-api.cc}::GetProperException(), v8::ValueDeserializer::Delegate::GetSharedArrayBufferFromId(), v8::ValueSerializer::Delegate::GetSharedArrayBufferId(), v8::ValueDeserializer::Delegate::GetSharedValueConveyor(), v8::ValueDeserializer::Delegate::GetWasmModuleFromId(), v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), NewURIError(), v8::internal::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::ReadHeader(), v8::ValueDeserializer::Delegate::ReadHostObject(), v8::internal::ValueDeserializer::ReadObject(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadObjectWrapper(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::Isolate::RunHostCreateShadowRealmContextCallback(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ValueSerializer::ThrowDataCloneError(), v8::internal::anonymous_namespace{value-serializer.cc}::ThrowDeserializationExceptionIfNonePending(), and v8::internal::ValueSerializer::WriteHostObject().
NewError() [2/3]
template<typename... Args>
DirectHandle<JSObject> v8::internal::Factory::NewError (DirectHandle< JSFunction > constructor, MessageTemplate template_index, Args... args) [inline]
Definition at line 939 of file factory.h.
  {
    return NewError(constructor, template_index,
                    base::VectorOf<DirectHandle<Object>>({args...}));
  }
References v8::base::args, v8::internal::anonymous_namespace{runtime-internal.cc}::NewError(), and v8::base::VectorOf().
NewError() [3/3]
Handle< JSObject > v8::internal::Factory::NewError (DirectHandle< JSFunction > constructor, MessageTemplate template_index, base::Vector< const DirectHandle< Object >> args)
Definition at line 2808 of file factory.cc.
                                                 {
  HandleScope scope(isolate());
  return scope.CloseAndEscape(ErrorUtils::MakeGenericError(
      isolate(), constructor, template_index, args, SKIP_NONE));
}
References v8::base::args, isolate(), v8::internal::ErrorUtils::MakeGenericError(), and v8::internal::SKIP_NONE.
NewErrorStackData()
DirectHandle< ErrorStackData > v8::internal::Factory::NewErrorStackData (DirectHandle< UnionOf< JSAny, FixedArray >> call_site_infos_or_formatted_stack, DirectHandle< StackTraceInfo > stack_trace)
Definition at line 1562 of file factory.cc.
                                              {
  Tagged<ErrorStackData> error_stack_data = NewStructInternal<ErrorStackData>(
      ERROR_STACK_DATA_TYPE, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  error_stack_data->set_call_site_infos_or_formatted_stack(
      *call_site_infos_or_formatted_stack, SKIP_WRITE_BARRIER);
  error_stack_data->set_stack_trace(*stack_trace, SKIP_WRITE_BARRIER);
  return direct_handle(error_stack_data, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Isolate::CaptureAndSetErrorStack().
NewExperimentalRegExpData()
DirectHandle< RegExpData > v8::internal::Factory::NewExperimentalRegExpData (DirectHandle< String > source, JSRegExp::Flags flags, int capture_count)
Definition at line 4270 of file factory.cc.
                                                                         {
  DirectHandle<RegExpDataWrapper> wrapper = NewRegExpDataWrapper();
  int size = IrRegExpData::kSize;
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(
      size, AllocationType::kTrusted, read_only_roots().ir_regexp_data_map());
  DisallowGarbageCollection no_gc;
  Tagged<IrRegExpData> instance = Cast<IrRegExpData>(result);
  // TODO(mbid,v8:10765): At the moment the ExperimentalRegExpData is just an
  // alias of IrRegExpData, with most fields set to some default/uninitialized
  // value. This is because EXPERIMENTAL and IRREGEXP regexps take the same code
  // path in `RegExpExecInternal`, which reads off various fields from this
  // struct. `RegExpExecInternal` should probably distinguish between
  // EXPERIMENTAL and IRREGEXP, and then we can get rid of all the IRREGEXP only
  // fields.
  instance->init_self_indirect_pointer(isolate());
  instance->set_type_tag(RegExpData::Type::EXPERIMENTAL);
  instance->set_source(*source);
  instance->set_flags(flags);
  instance->clear_latin1_code();
  instance->clear_uc16_code();
  instance->clear_latin1_bytecode();
  instance->clear_uc16_bytecode();
  instance->set_capture_name_map(Smi::FromInt(JSRegExp::kUninitializedValue));
  instance->set_max_register_count(JSRegExp::kUninitializedValue);
  instance->set_capture_count(capture_count);
  instance->set_ticks_until_tier_up(JSRegExp::kUninitializedValue);
  instance->set_backtrack_limit(JSRegExp::kUninitializedValue);
  Tagged<RegExpDataWrapper> raw_wrapper = *wrapper;
  instance->set_wrapper(raw_wrapper);
  raw_wrapper->set_data(instance);
  return direct_handle(instance, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), v8::internal::RegExpData::EXPERIMENTAL, v8::internal::flags, v8::internal::Smi::FromInt(), isolate(), v8::internal::kTrusted, v8::internal::JSRegExp::kUninitializedValue, v8::internal::FactoryBase< Factory >::NewRegExpDataWrapper(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), v8::base::internal::result, and size().
Referenced by SetRegExpExperimentalData().
NewExternal()
Handle< JSObject > v8::internal::Factory::NewExternal (void * value, AllocationType allocation = AllocationType::kYoung)
Definition at line 2920 of file factory.cc.
                                                                      {
  auto external = Cast<JSExternalObject>(
      NewJSObjectFromMap(external_map(), allocation_type));
  external->init_value(isolate(), value);
  return external;
}
References isolate(), NewJSObjectFromMap(), and v8::internal::value.
Referenced by v8::External::New().
NewExternalStringFromOneByte()
MaybeHandle< String > v8::internal::Factory::NewExternalStringFromOneByte (const v8::String::ExternalOneByteStringResource * resource)
Definition at line 1151 of file factory.cc.
                                                   {
  size_t length = resource->length();
  if (length > static_cast<size_t>(String::kMaxLength)) {
    THROW_NEW_ERROR(isolate(), NewInvalidStringLengthError());
  }
  if (length == 0) return empty_string();
  DirectHandle<Map> map = resource->IsCacheable()
                              ? external_one_byte_string_map()
                              : uncached_external_one_byte_string_map();
  Tagged<ExternalOneByteString> external_string =
      Cast<ExternalOneByteString>(New(map, AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  external_string->InitExternalPointerFields(isolate());
  external_string->set_length(static_cast<int>(length));
  external_string->set_raw_hash_field(String::kEmptyHashField);
  external_string->SetResource(isolate(), resource);
  isolate()->heap()->RegisterExternalString(external_string);
  return Handle<String>(external_string, isolate());
}
References v8::internal::Isolate::heap(), v8::String::ExternalStringResourceBase::IsCacheable(), isolate(), v8::internal::Name::kEmptyHashField, v8::internal::String::kMaxLength, v8::internal::kOld, v8::String::ExternalOneByteStringResource::length(), length, New(), NewInvalidStringLengthError(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::RegisterExternalString(), and THROW_NEW_ERROR.
Referenced by v8::internal::Genesis::CompileExtension(), and v8::String::NewExternalOneByte().
NewExternalStringFromTwoByte()
MaybeHandle< String > v8::internal::Factory::NewExternalStringFromTwoByte (const v8::String::ExternalStringResource * resource)
Definition at line 1175 of file factory.cc.
                                                   {
  size_t length = resource->length();
  if (length > static_cast<size_t>(String::kMaxLength)) {
    THROW_NEW_ERROR(isolate(), NewInvalidStringLengthError());
  }
  if (length == 0) return empty_string();
  DirectHandle<Map> map = resource->IsCacheable()
                              ? external_two_byte_string_map()
                              : uncached_external_two_byte_string_map();
  Tagged<ExternalTwoByteString> string =
      Cast<ExternalTwoByteString>(New(map, AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  string->InitExternalPointerFields(isolate());
  string->set_length(static_cast<int>(length));
  string->set_raw_hash_field(String::kEmptyHashField);
  string->SetResource(isolate(), resource);
  isolate()->heap()->RegisterExternalString(string);
  return Handle<ExternalTwoByteString>(string, isolate());
}
References v8::internal::Isolate::heap(), v8::String::ExternalStringResourceBase::IsCacheable(), isolate(), v8::internal::Name::kEmptyHashField, v8::internal::String::kMaxLength, v8::internal::kOld, v8::String::ExternalStringResource::length(), length, New(), NewInvalidStringLengthError(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Heap::RegisterExternalString(), and THROW_NEW_ERROR.
Referenced by v8::String::NewExternalTwoByte().
NewFastOrSlowJSObjectFromMap() [1/2]
Handle< JSObject > v8::internal::Factory::NewFastOrSlowJSObjectFromMap (DirectHandle< Map > map) [inline]
Definition at line 113 of file factory-inl.h.
                                                                            {
  return NewFastOrSlowJSObjectFromMap(map,
                                      PropertyDictionary::kInitialCapacity);
}
References v8::internal::NameDictionary::kInitialCapacity, and NewFastOrSlowJSObjectFromMap().
NewFastOrSlowJSObjectFromMap() [2/2]
Handle< JSObject > v8::internal::Factory::NewFastOrSlowJSObjectFromMap (DirectHandle< Map > map, int number_of_slow_properties, AllocationType allocation = AllocationType::kYoung, DirectHandle< AllocationSite > allocation_site = DirectHandle<AllocationSite>::null(), NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper) [inline]
Definition at line 100 of file factory-inl.h.
                                        {
  auto js_object =
      map->is_dictionary_map()
          ? NewSlowJSObjectFromMap(map, number_of_slow_properties, allocation,
                                   allocation_site, new_js_object_type)
          : NewJSObjectFromMap(map, allocation, allocation_site,
                               new_js_object_type);
  return js_object;
}
References NewJSObjectFromMap(), and NewSlowJSObjectFromMap().
Referenced by v8::internal::CloneObjectSlowPath(), v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::Create(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::JSObject::New(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSDurationFormat::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), v8::internal::JSLocale::New(), NewFastOrSlowJSObjectFromMap(), v8::internal::JSObject::NewWithMap(), and v8::internal::JSObject::ObjectCreate().
NewFeedbackVector()
Handle< FeedbackVector > v8::internal::Factory::NewFeedbackVector (DirectHandle< SharedFunctionInfo > shared, DirectHandle< ClosureFeedbackCellArray > closure_feedback_cell_array, DirectHandle< FeedbackCell > parent_feedback_cell)
Definition at line 459 of file factory.cc.
                                                     {
  int length = shared->feedback_metadata()->slot_count();
  DCHECK_LE(0, length);
  int size = FeedbackVector::SizeFor(length);
  Tagged<FeedbackVector> vector =
      Cast<FeedbackVector>(AllocateRawWithImmortalMap(
          size, AllocationType::kOld, *feedback_vector_map()));
  DisallowGarbageCollection no_gc;
  vector->set_shared_function_info(*shared);
  vector->set_length(length);
  vector->set_invocation_count(0);
  vector->set_invocation_count_before_stable(0);
  vector->reset_osr_state();
  vector->reset_flags();
#ifndef V8_ENABLE_LEAPTIERING
  vector->set_maybe_optimized_code(ClearedValue(isolate()));
  vector->set_log_next_execution(v8_flags.log_function_events);
#endif // !V8_ENABLE_LEAPTIERING
  vector->set_closure_feedback_cell_array(*closure_feedback_cell_array);
  vector->set_parent_feedback_cell(*parent_feedback_cell);
  // TODO(leszeks): Initialize based on the feedback metadata.
  MemsetTagged(ObjectSlot(vector->slots_start()), *undefined_value(), length);
  return handle(vector, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::ClearedValue(), DCHECK_LE, v8::internal::handle(), isolate(), v8::internal::kOld, length, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::v8_flags.
Referenced by v8::internal::FeedbackVector::New().
NewFillerObject()
DirectHandle< HeapObject > v8::internal::Factory::NewFillerObject (int size, AllocationAlignment alignment, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime)
Definition at line 355 of file factory.cc.
                                                                           {
  Heap* heap = isolate()->heap();
  Tagged<HeapObject> result =
      allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
          size, allocation, origin, alignment);
  heap->CreateFillerObjectAt(result.address(), size);
  return DirectHandle<HeapObject>(result, isolate());
}
References v8::internal::HeapAllocator::AllocateRawWith(), allocator(), v8::internal::Isolate::heap(), isolate(), v8::internal::HeapAllocator::kRetryOrFail, v8::base::internal::result, and size().
Referenced by v8::internal::RUNTIME_FUNCTION().
NewFixedDoubleArrayWithHoles()
DirectHandle< FixedArrayBase > v8::internal::Factory::NewFixedDoubleArrayWithHoles (int size)
Definition at line 507 of file factory.cc.
                                                                             {
  DCHECK_LE(0, length);
  DirectHandle<FixedArrayBase> array = NewFixedDoubleArray(length);
  if (length > 0) {
    Cast<FixedDoubleArray>(array)->FillWithHoles(0, length);
  }
  return array;
}
References DCHECK_LE, length, and v8::internal::FactoryBase< Factory >::NewFixedDoubleArray().
Referenced by NewJSArrayStorage().
NewForeign()
template<ExternalPointerTag tag>
Handle< Foreign > v8::internal::Factory::NewForeign (Address addr, AllocationType allocation_type = AllocationType::kYoung)
Definition at line 119 of file factory-inl.h.
                                                                    {
  // Statically ensure that it is safe to allocate foreigns in paged spaces.
  static_assert(Foreign::kSize <= kMaxRegularHeapObjectSize);
  Tagged<Map> map = *foreign_map();
  Tagged<Foreign> foreign = Cast<Foreign>(
      AllocateRawWithImmortalMap(map->instance_size(), allocation_type, map));
  DisallowGarbageCollection no_gc;
  foreign->init_foreign_address<tag>(isolate(), addr);
  return handle(foreign, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::handle(), isolate(), v8::internal::kMaxRegularHeapObjectSize, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::internal::Managed< CppType >::From(), v8::FromCData(), and v8::internal::JSAtomicsMutex::LockOrEnqueuePromise().
NewForTest()
Tagged<HeapObject> v8::internal::Factory::NewForTest (DirectHandle< Map > map, AllocationType allocation) [inline]
Definition at line 1095 of file factory.h.
                                                           {
    return New(map, allocation);
  }
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
NewFunctionContext()
DirectHandle< Context > v8::internal::Factory::NewFunctionContext (DirectHandle< Context > outer, DirectHandle< ScopeInfo > scope_info)
Definition at line 1378 of file factory.cc.
                                                                     {
  DirectHandle<Map> map;
  switch (scope_info->scope_type()) {
    case EVAL_SCOPE:
      map = isolate()->eval_context_map();
      break;
    case FUNCTION_SCOPE:
      map = isolate()->function_context_map();
      break;
    default:
      UNREACHABLE();
  }
  int variadic_part_length = scope_info->ContextLength();
  Tagged<Context> context =
      NewContextInternal(map, Context::SizeFor(variadic_part_length),
                         variadic_part_length, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  context->set_scope_info(*scope_info);
  context->set_previous(*outer);
  return direct_handle(context, isolate());
}
References v8::internal::direct_handle(), v8::internal::EVAL_SCOPE, v8::internal::FUNCTION_SCOPE, isolate(), v8::internal::kYoung, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::SizeFor(), and v8::internal::UNREACHABLE().
NewFunctionForTesting()
Handle< JSFunction > v8::internal::Factory::NewFunctionForTesting (DirectHandle< String > name)
Definition at line 4583 of file factory.cc.
                                                                           {
  DirectHandle<SharedFunctionInfo> info =
      NewSharedFunctionInfoForBuiltin(name, Builtin::kIllegal, 0, kDontAdapt);
  info->set_language_mode(LanguageMode::kSloppy);
  return JSFunctionBuilder{isolate(), info, isolate()->native_context()}
      .Build();
}
References isolate(), v8::internal::kDontAdapt, v8::internal::kSloppy, v8::internal::name, v8::internal::Isolate::native_context(), and NewSharedFunctionInfoForBuiltin().
NewFunctionPrototype()
DirectHandle< JSObject > v8::internal::Factory::NewFunctionPrototype (DirectHandle< JSFunction > function)
Definition at line 2885 of file factory.cc.
                                       {
  // Make sure to use globals from the function's context, since the function
  // can be from a different context.
  DirectHandle<NativeContext> native_context(function->native_context(),
                                             isolate());
  DirectHandle<Map> new_map;
  if (V8_UNLIKELY(IsAsyncGeneratorFunction(function->shared()->kind()))) {
    new_map = direct_handle(
        native_context->async_generator_object_prototype_map(), isolate());
  } else if (IsResumableFunction(function->shared()->kind())) {
    // Generator and async function prototypes can share maps since they
    // don't have "constructor" properties.
    new_map = direct_handle(native_context->generator_object_prototype_map(),
                            isolate());
  } else {
    // Each function prototype gets a fresh map to avoid unwanted sharing of
    // maps between prototypes of different constructors.
    DirectHandle<JSFunction> object_function(native_context->object_function(),
                                             isolate());
    DCHECK(object_function->has_initial_map());
    new_map = direct_handle(object_function->initial_map(), isolate());
  }
  DCHECK(!new_map->is_prototype_map());
  DirectHandle<JSObject> prototype = NewJSObjectFromMap(new_map);
  if (!IsResumableFunction(function->shared()->kind())) {
    JSObject::AddProperty(isolate(), prototype, constructor_string(), function,
                          DONT_ENUM);
  }
  return prototype;
}
References v8::internal::JSObject::AddProperty(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::DONT_ENUM, v8::internal::IsAsyncGeneratorFunction(), isolate(), v8::internal::IsResumableFunction(), v8::internal::native_context, NewJSObjectFromMap(), v8::internal::prototype, and V8_UNLIKELY.
Referenced by v8::internal::ApiNatives::CreateApiFunction(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunctionForBuiltinWithPrototype(), v8::internal::Genesis::CreateNewGlobals(), v8::internal::Genesis::CreateObjectFunction(), v8::internal::JSFunction::EnsureHasInitialMap(), and v8::internal::GetFunctionPrototype().
NewFunctionTemplateInfo()
DirectHandle< FunctionTemplateInfo > v8::internal::Factory::NewFunctionTemplateInfo (int length, bool do_not_cache)
Definition at line 4681 of file factory.cc.
                                   {
  const int size = FunctionTemplateInfo::SizeFor();
  Tagged<FunctionTemplateInfo> obj =
      Cast<FunctionTemplateInfo>(AllocateRawWithImmortalMap(
          size, AllocationType::kOld,
          read_only_roots().function_template_info_map()));
  {
    // Disallow GC until all fields of obj have acceptable types.
    DisallowGarbageCollection no_gc;
    Tagged<FunctionTemplateInfo> raw = *obj;
    ReadOnlyRoots roots(isolate());
    InitializeTemplateWithProperties(raw, roots, !do_not_cache);
    raw->set_class_name(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_interface_name(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_signature(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_rare_data(roots.undefined_value(), kReleaseStore,
                       SKIP_WRITE_BARRIER);
    raw->set_shared_function_info(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_cached_property_name(roots.the_hole_value(), SKIP_WRITE_BARRIER);
    raw->set_flag(0, kRelaxedStore);
    raw->set_undetectable(false);
    raw->set_needs_access_check(false);
    raw->set_accept_any_receiver(true);
    raw->set_exception_context(
        static_cast<uint32_t>(ExceptionContext::kUnknown));
    raw->set_length(length);
    raw->SetInstanceType(0);
    raw->init_callback(isolate(), kNullAddress);
    raw->set_callback_data(roots.the_hole_value(), kReleaseStore,
                           SKIP_WRITE_BARRIER);
  }
  return direct_handle(obj, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), v8::internal::anonymous_namespace{factory.cc}::InitializeTemplateWithProperties(), isolate(), v8::internal::kNullAddress, v8::internal::kOld, v8::kRelaxedStore, v8::kReleaseStore, v8::kUnknown, length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), size(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::ObjectTemplate::SetCallAsFunctionHandler().
NewHeapNumberForCodeAssembler()
Handle< HeapNumber > v8::internal::Factory::NewHeapNumberForCodeAssembler (double value)
Definition at line 2798 of file factory.cc.
                                                                      {
  ReadOnlyRoots roots(isolate());
  auto num = isolate()->roots_table().FindHeapNumber(value);
  if (!num.is_null()) return num;
  // Add known HeapNumber constants to the read only roots. This ensures
  // r/o snapshots to be deterministic.
  DCHECK(!CanAllocateInReadOnlySpace());
  return NewHeapNumber<AllocationType::kOld>(value);
}
References CanAllocateInReadOnlySpace(), v8::internal::DCHECK(), v8::internal::RootsTable::FindHeapNumber(), isolate(), v8::internal::Isolate::roots_table(), and v8::internal::value.
NewHole()
DirectHandle< Hole > v8::internal::Factory::NewHole ()
Definition at line 412 of file factory.cc.
                                    {
  DirectHandle<Hole> hole(
      Cast<Hole>(New(hole_map(), AllocationType::kReadOnly)), isolate());
  Hole::Initialize(isolate(), hole, hole_nan_value());
  return hole;
}
References v8::internal::Hole::Initialize(), isolate(), v8::internal::kReadOnly, and New().
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
NewInterceptorInfo()
DirectHandle< InterceptorInfo > v8::internal::Factory::NewInterceptorInfo (AllocationType allocation = AllocationType::kOld)
Definition at line 1543 of file factory.cc.
                               {
  Tagged<InterceptorInfo> info =
      Cast<InterceptorInfo>(New(interceptor_info_map(), allocation));
  DisallowGarbageCollection no_gc;
  info->set_data(*undefined_value());
  info->set_flags(0);
  info->clear_padding();
  // Initialization of these lazy-initialized callback fields is the same
  // for named and indexed versions.
#define INIT_CALLBACK_FIELD(Name, name) info->init_named_##name();
  INTERCEPTOR_INFO_CALLBACK_LIST(INIT_CALLBACK_FIELD)
#undef INIT_CALLBACK_FIELD
  return direct_handle(info, isolate());
}
References v8::internal::direct_handle(), INIT_CALLBACK_FIELD, INTERCEPTOR_INFO_CALLBACK_LIST, isolate(), New(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::anonymous_namespace{api.cc}::CreateInterceptorInfo(), and v8::internal::Heap::CreateReadOnlyApiObjects().
NewInternalizedStringImpl()
DirectHandle< String > v8::internal::Factory::NewInternalizedStringImpl (DirectHandle< String > string, int len, uint32_t hash_field)
Definition at line 938 of file factory.cc.
                                                               {
  if (string->IsOneByteRepresentation()) {
    DirectHandle<SeqOneByteString> result =
        AllocateRawOneByteInternalizedString(len, hash_field);
    DisallowGarbageCollection no_gc;
    String::WriteToFlat(*string, result->GetChars(no_gc), 0, len);
    return result;
  }
  DirectHandle<SeqTwoByteString> result =
      AllocateRawTwoByteInternalizedString(len, hash_field);
  DisallowGarbageCollection no_gc;
  String::WriteToFlat(*string, result->GetChars(no_gc), 0, len);
  return result;
}
References v8::internal::FactoryBase< Factory >::AllocateRawOneByteInternalizedString(), v8::internal::FactoryBase< Factory >::AllocateRawTwoByteInternalizedString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::string, and v8::internal::String::WriteToFlat().
Referenced by v8::internal::InternalizedStringKey::PrepareForInsertion().
NewInterpreterData()
DirectHandle< InterpreterData > v8::internal::Factory::NewInterpreterData (DirectHandle< BytecodeArray > bytecode_array, DirectHandle< Code > code)
Definition at line 3950 of file factory.cc.
                                                                         {
  Tagged<Map> map = *interpreter_data_map();
  Tagged<InterpreterData> interpreter_data = Cast<InterpreterData>(
      AllocateRawWithImmortalMap(map->instance_size(), AllocationType::kTrusted,
                                 *interpreter_data_map()));
  DisallowGarbageCollection no_gc;
  interpreter_data->init_self_indirect_pointer(isolate());
  interpreter_data->set_bytecode_array(*bytecode_array);
  interpreter_data->set_interpreter_trampoline(*code);
  return direct_handle(interpreter_data, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), code, v8::internal::direct_handle(), isolate(), v8::internal::kTrusted, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), and v8::internal::Compiler::InstallInterpreterTrampolineCopy().
NewInvalidStringLengthError()
DirectHandle< Object > v8::internal::Factory::NewInvalidStringLengthError ()
Definition at line 2838 of file factory.cc.
                                                          {
  if (v8_flags.correctness_fuzzer_suppressions) {
    FATAL("Aborting on invalid string length");
  }
  // Invalidate the "string length" protector.
  if (Protectors::IsStringLengthOverflowLookupChainIntact(isolate())) {
    Protectors::InvalidateStringLengthOverflowLookupChain(isolate());
  }
  return NewRangeError(MessageTemplate::kInvalidStringLength);
}
References FATAL, isolate(), and v8::internal::v8_flags.
Referenced by NewExternalStringFromOneByte(), NewExternalStringFromTwoByte(), NewStringFromUtf8(), v8::internal::JsonStringifier::SerializeArrayLikeSlow(), and v8::internal::JsonStringifier::SerializeJSProxy().
NewIrRegExpData()
DirectHandle< RegExpData > v8::internal::Factory::NewIrRegExpData (DirectHandle< String > source, JSRegExp::Flags flags, int capture_count, uint32_t backtrack_limit)
Definition at line 4238 of file factory.cc.
                                                                            {
  DirectHandle<RegExpDataWrapper> wrapper = NewRegExpDataWrapper();
  int size = IrRegExpData::kSize;
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(
      size, AllocationType::kTrusted, read_only_roots().ir_regexp_data_map());
  DisallowGarbageCollection no_gc;
  Tagged<IrRegExpData> instance = Cast<IrRegExpData>(result);
  instance->init_self_indirect_pointer(isolate());
  instance->set_type_tag(RegExpData::Type::IRREGEXP);
  instance->set_source(*source);
  instance->set_flags(flags);
  instance->clear_latin1_code();
  instance->clear_uc16_code();
  instance->clear_latin1_bytecode();
  instance->clear_uc16_bytecode();
  instance->set_capture_name_map(Smi::FromInt(JSRegExp::kUninitializedValue));
  instance->set_max_register_count(JSRegExp::kUninitializedValue);
  instance->set_capture_count(capture_count);
  int ticks_until_tier_up = v8_flags.regexp_tier_up
                                ? v8_flags.regexp_tier_up_ticks
                                : JSRegExp::kUninitializedValue;
  instance->set_ticks_until_tier_up(ticks_until_tier_up);
  instance->set_backtrack_limit(backtrack_limit);
  Tagged<RegExpDataWrapper> raw_wrapper = *wrapper;
  instance->set_wrapper(raw_wrapper);
  raw_wrapper->set_data(instance);
  return direct_handle(instance, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), v8::internal::flags, v8::internal::Smi::FromInt(), v8::internal::RegExpData::IRREGEXP, isolate(), v8::internal::kTrusted, v8::internal::JSRegExp::kUninitializedValue, v8::internal::FactoryBase< Factory >::NewRegExpDataWrapper(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), v8::base::internal::result, size(), and v8::internal::v8_flags.
Referenced by SetRegExpIrregexpData().
NewJSArray() [1/2]
Handle< JSArray > v8::internal::Factory::NewJSArray (ElementsKind elements_kind, int length, int capacity, ArrayStorageAllocationMode mode = ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS, AllocationType allocation = AllocationType::kYoung)
Definition at line 3235 of file factory.cc.
                                                               {
  DCHECK(capacity >= length);
  if (capacity == 0) {
    return NewJSArrayWithElements(empty_fixed_array(), elements_kind, length,
                                  allocation);
  }
  HandleScope inner_scope(isolate());
  DirectHandle<FixedArrayBase> elms =
      NewJSArrayStorage(elements_kind, capacity, mode);
  return inner_scope.CloseAndEscape(NewJSArrayWithUnverifiedElements(
      elms, elements_kind, length, allocation));
}
References v8::internal::DCHECK(), isolate(), length, mode(), NewJSArrayStorage(), NewJSArrayWithElements(), and NewJSArrayWithUnverifiedElements().
Referenced by v8::internal::ElementsAccessor::Concat(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FieldPositionIteratorToArray(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormattedDateIntervalToJSArray(), v8::internal::anonymous_namespace{js-list-format.cc}::FormattedListToJSArray(), v8::internal::FormattedListToJSArray(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToJSArray(), v8::internal::anonymous_namespace{js-number-format.cc}::FormatToJSArray(), v8::internal::wasm::GetCustomSections(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::Genesis::InitializeGlobal(), v8::anonymous_namespace{api.cc}::MapAsArray(), v8::Array::New(), v8::internal::ValueDeserializer::ReadDenseJSArray(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::ValueDeserializer::ReadSparseJSArray(), v8::internal::RUNTIME_FUNCTION(), and v8::anonymous_namespace{api.cc}::SetAsArray().
NewJSArray() [2/2]
Handle<JSArray> v8::internal::Factory::NewJSArray (int capacity, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 692 of file factory.h.
                                                        {
    if (capacity != 0) {
      elements_kind = GetHoleyElementsKind(elements_kind);
    }
    return NewJSArray(
        elements_kind, 0, capacity,
        ArrayStorageAllocationMode::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE,
        allocation);
  }
References v8::internal::GetHoleyElementsKind().
NewJSArrayBuffer()
Handle< JSArrayBuffer > v8::internal::Factory::NewJSArrayBuffer (std::shared_ptr< BackingStore > backing_store, AllocationType allocation = AllocationType::kYoung)
Definition at line 3515 of file factory.cc.
                                                                          {
  DirectHandle<Map> map(
      isolate()->native_context()->array_buffer_fun()->initial_map(),
      isolate());
  ResizableFlag resizable_by_js = ResizableFlag::kNotResizable;
  if (backing_store->is_resizable_by_js()) {
    resizable_by_js = ResizableFlag::kResizable;
  }
  auto result = Cast<JSArrayBuffer>(
      NewJSObjectFromMap(map, allocation, DirectHandle<AllocationSite>::null(),
                         NewJSObjectType::kAPIWrapper));
  result->Setup(SharedFlag::kNotShared, resizable_by_js,
                std::move(backing_store), isolate());
  return result;
}
References v8::internal::compiler::initial_map, isolate(), v8::internal::kAPIWrapper, v8::internal::kNotResizable, v8::internal::kNotShared, v8::internal::kResizable, v8::internal::native_context, NewJSObjectFromMap(), and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::WasmMemoryObject::New(), v8::ArrayBuffer::New(), and v8::internal::WasmMemoryObject::RefreshBuffer().
NewJSArrayBufferAndBackingStore() [1/2]
MaybeHandle< JSArrayBuffer > v8::internal::Factory::NewJSArrayBufferAndBackingStore (size_t byte_length, InitializedFlag initialized, AllocationType allocation = AllocationType::kYoung)
Definition at line 3532 of file factory.cc.
                               {
  return NewJSArrayBufferAndBackingStore(byte_length, byte_length, initialized,
                                         ResizableFlag::kNotResizable,
                                         allocation);
}
References v8::internal::kNotResizable.
Referenced by v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::GetCustomSections(), v8::ArrayBuffer::MaybeNew(), v8::internal::WasmGlobalObject::New(), v8::ArrayBuffer::New(), and v8::internal::ValueDeserializer::ReadJSArrayBuffer().
NewJSArrayBufferAndBackingStore() [2/2]
MaybeHandle< JSArrayBuffer > v8::internal::Factory::NewJSArrayBufferAndBackingStore (size_t byte_length, size_t max_byte_length, InitializedFlag initialized, ResizableFlag resizable = ResizableFlag::kNotResizable, AllocationType allocation = AllocationType::kYoung)
Definition at line 3540 of file factory.cc.
                                                        {
  DCHECK_LE(byte_length, max_byte_length);
  std::unique_ptr<BackingStore> backing_store = nullptr;
  if (resizable == ResizableFlag::kResizable) {
    size_t page_size, initial_pages, max_pages;
    if (JSArrayBuffer::GetResizableBackingStorePageConfiguration(
            isolate(), byte_length, max_byte_length, kDontThrow, &page_size,
            &initial_pages, &max_pages)
            .IsNothing()) {
      return MaybeHandle<JSArrayBuffer>();
    }
    backing_store = BackingStore::TryAllocateAndPartiallyCommitMemory(
        isolate(), byte_length, max_byte_length, page_size, initial_pages,
        max_pages, WasmMemoryFlag::kNotWasm, SharedFlag::kNotShared);
    if (!backing_store) return MaybeHandle<JSArrayBuffer>();
  } else {
    if (byte_length > 0) {
      backing_store = BackingStore::Allocate(
          isolate(), byte_length, SharedFlag::kNotShared, initialized);
      if (!backing_store) return MaybeHandle<JSArrayBuffer>();
    }
  }
  DirectHandle<Map> map(
      isolate()->native_context()->array_buffer_fun()->initial_map(),
      isolate());
  auto array_buffer = Cast<JSArrayBuffer>(
      NewJSObjectFromMap(map, allocation, DirectHandle<AllocationSite>::null(),
                         NewJSObjectType::kAPIWrapper));
  array_buffer->Setup(SharedFlag::kNotShared, resizable,
                      std::move(backing_store), isolate());
  return array_buffer;
}
References v8::internal::BackingStore::Allocate(), DCHECK_LE, v8::internal::JSArrayBuffer::GetResizableBackingStorePageConfiguration(), v8::internal::compiler::initial_map, isolate(), v8::internal::kAPIWrapper, v8::internal::kDontThrow, v8::internal::kNotShared, v8::internal::kNotWasm, v8::internal::kResizable, v8::internal::native_context, NewJSObjectFromMap(), and v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory().
NewJSArrayBufferView()
Handle< JSArrayBufferView > v8::internal::Factory::NewJSArrayBufferView (DirectHandle< Map > map, DirectHandle< FixedArrayBase > elements, DirectHandle< JSArrayBuffer > buffer, size_t byte_offset, size_t byte_length) [private]
Definition at line 3652 of file factory.cc.
                        {
  if (!IsRabGsabTypedArrayElementsKind(map->elements_kind())) {
    CHECK_LE(byte_length, buffer->GetByteLength());
    CHECK_LE(byte_offset, buffer->GetByteLength());
    CHECK_LE(byte_offset + byte_length, buffer->GetByteLength());
  }
  Handle<JSArrayBufferView> array_buffer_view =
      Cast<JSArrayBufferView>(NewJSObjectFromMap(
          map, AllocationType::kYoung, DirectHandle<AllocationSite>::null(),
          NewJSObjectType::kAPIWrapper));
  DisallowGarbageCollection no_gc;
  Tagged<JSArrayBufferView> raw = *array_buffer_view;
  raw->set_elements(*elements, SKIP_WRITE_BARRIER);
  raw->set_buffer(*buffer, SKIP_WRITE_BARRIER);
  raw->set_byte_offset(byte_offset);
  raw->set_byte_length(byte_length);
  raw->set_bit_field(0);
  // TODO(v8) remove once embedder data slots are always zero-initialized.
  InitEmbedderFields(raw, Smi::zero());
  DCHECK_EQ(raw->GetEmbedderFieldCount(),
            v8::ArrayBufferView::kEmbedderFieldCount);
  return array_buffer_view;
}
References CHECK_LE, DCHECK_EQ, v8::internal::anonymous_namespace{factory.cc}::InitEmbedderFields(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::internal::kAPIWrapper, v8::ArrayBufferView::kEmbedderFieldCount, v8::internal::kYoung, NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Smi::zero().
Referenced by NewJSDataViewOrRabGsabDataView(), and NewJSTypedArray().
NewJSArrayForTemplateLiteralArray()
DirectHandle< JSArray > v8::internal::Factory::NewJSArrayForTemplateLiteralArray (DirectHandle< FixedArray > cooked_strings, DirectHandle< FixedArray > raw_strings, int function_literal_id, int slot_id)
Definition at line 3288 of file factory.cc.
                 {
  DirectHandle<JSArray> raw_object =
      NewJSArrayWithElements(raw_strings, PACKED_ELEMENTS,
                             raw_strings->length(), AllocationType::kOld);
  JSObject::SetIntegrityLevel(isolate(), raw_object, FROZEN, kThrowOnError)
      .ToChecked();
  DirectHandle<NativeContext> native_context = isolate()->native_context();
  auto template_object =
      Cast<TemplateLiteralObject>(NewJSArrayWithUnverifiedElements(
          direct_handle(native_context->js_array_template_literal_object_map(),
                        isolate()),
          cooked_strings, cooked_strings->length(), AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  Tagged<TemplateLiteralObject> raw_template_object = *template_object;
  DCHECK_EQ(raw_template_object->map(),
            native_context->js_array_template_literal_object_map());
  raw_template_object->set_raw(*raw_object);
  raw_template_object->set_function_literal_id(function_literal_id);
  raw_template_object->set_slot_id(slot_id);
  return template_object;
}
References DCHECK_EQ, v8::internal::direct_handle(), v8::internal::FROZEN, v8::internal::function_literal_id, isolate(), v8::internal::kOld, v8::internal::kThrowOnError, v8::internal::Isolate::native_context(), v8::internal::native_context, NewJSArrayWithElements(), NewJSArrayWithUnverifiedElements(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::PACKED_ELEMENTS.
Referenced by v8::internal::TemplateObjectDescription::GetTemplateObject().
NewJSArrayStorage() [1/2]
void v8::internal::Factory::NewJSArrayStorage (DirectHandle< JSArray > array, int length, int capacity, ArrayStorageAllocationMode mode = ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS)
Definition at line 3314 of file factory.cc.
                                                                               {
  DCHECK(capacity >= length);
  if (capacity == 0) {
    Tagged<JSArray> raw = *array;
    DisallowGarbageCollection no_gc;
    raw->set_length(Smi::zero());
    raw->set_elements(*empty_fixed_array());
    return;
  }
  HandleScope inner_scope(isolate());
  DirectHandle<FixedArrayBase> elms =
      NewJSArrayStorage(array->GetElementsKind(), capacity, mode);
  DisallowGarbageCollection no_gc;
  Tagged<JSArray> raw = *array;
  raw->set_elements(*elms);
  raw->set_length(Smi::FromInt(length));
}
References v8::internal::DCHECK(), v8::internal::Smi::FromInt(), isolate(), length, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::zero().
Referenced by v8::internal::JSArray::Initialize(), NewJSArray(), and v8::internal::RUNTIME_FUNCTION().
NewJSArrayStorage() [2/2]
DirectHandle< FixedArrayBase > v8::internal::Factory::NewJSArrayStorage (ElementsKind elements_kind, int capacity, ArrayStorageAllocationMode mode = ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS) [private]
Definition at line 3335 of file factory.cc.
                                                                               {
  DCHECK_GT(capacity, 0);
  DirectHandle<FixedArrayBase> elms;
  if (IsDoubleElementsKind(elements_kind)) {
    if (mode == ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS) {
      elms = NewFixedDoubleArray(capacity);
    } else {
      DCHECK_EQ(
          mode,
          ArrayStorageAllocationMode::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE);
      elms = NewFixedDoubleArrayWithHoles(capacity);
    }
  } else {
    DCHECK(IsSmiOrObjectElementsKind(elements_kind));
    if (mode == ArrayStorageAllocationMode::DONT_INITIALIZE_ARRAY_ELEMENTS) {
      elms = NewFixedArray(capacity);
    } else {
      DCHECK_EQ(
          mode,
          ArrayStorageAllocationMode::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE);
      elms = NewFixedArrayWithHoles(capacity);
    }
  }
  return elms;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::DONT_INITIALIZE_ARRAY_ELEMENTS, v8::internal::INITIALIZE_ARRAY_ELEMENTS_WITH_HOLE, v8::internal::IsDoubleElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), mode(), v8::internal::FactoryBase< Factory >::NewFixedArray(), v8::internal::FactoryBase< Factory >::NewFixedArrayWithHoles(), v8::internal::FactoryBase< Factory >::NewFixedDoubleArray(), and NewFixedDoubleArrayWithHoles().
NewJSArrayWithElements() [1/2]
Handle< JSArray > v8::internal::Factory::NewJSArrayWithElements (DirectHandle< FixedArrayBase > elements, ElementsKind elements_kind, int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 3252 of file factory.cc.
                                           {
  Handle<JSArray> array = NewJSArrayWithUnverifiedElements(
      elements, elements_kind, length, allocation);
#ifdef ENABLE_SLOW_DCHECKS
  JSObject::ValidateElements(isolate(), *array);
#endif
  return array;
}
References isolate(), length, NewJSArrayWithUnverifiedElements(), and v8::internal::JSObject::ValidateElements().
Referenced by v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateArrayLiteral(), v8::internal::JSWeakCollection::GetEntries(), v8::internal::JSLocale::GetHourCycles(), v8::internal::Runtime::GetInternalProperties(), v8::internal::GetKeywordValuesFromLocale(), v8::internal::JSLocale::GetNumberingSystems(), v8::internal::anonymous_namespace{builtins-object.cc}::GetOwnPropertyKeys(), v8::internal::GetOwnValuesOrEntries(), v8::Object::GetPropertyNames(), v8::internal::anonymous_namespace{messages.cc}::GetStackFrames(), v8::internal::wasm::GetTypeForFunction(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::MakeEntryPair(), v8::anonymous_namespace{api.cc}::MapAsArray(), v8::internal::ScopeIterator::MaterializeScopeDetails(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::NamedEnumerator(), v8::Array::New(), NewJSArray(), NewJSArrayForTemplateLiteralArray(), NewJSArrayWithElements(), v8::internal::anonymous_namespace{runtime-regexp.cc}::NewJSArrayWithElements(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::anonymous_namespace{api.cc}::SetAsArray(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), and v8::internal::anonymous_namespace{intl-objects.cc}::VectorToJSArray().
NewJSArrayWithElements() [2/2]
Handle< JSArray > v8::internal::Factory::NewJSArrayWithElements (DirectHandle< FixedArrayBase > elements, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 93 of file factory-inl.h.
                               {
  return NewJSArrayWithElements(elements, elements_kind, elements->length(),
                                allocation);
}
References NewJSArrayWithElements().
NewJSArrayWithUnverifiedElements() [1/2]
Handle< JSArray > v8::internal::Factory::NewJSArrayWithUnverifiedElements (DirectHandle< FixedArrayBase > elements, ElementsKind elements_kind, int length, AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 3263 of file factory.cc.
                                           {
  DCHECK(length <= elements->length());
  Tagged<NativeContext> native_context = isolate()->raw_native_context();
  Tagged<Map> map = native_context->GetInitialJSArrayMap(elements_kind);
  if (map.is_null()) {
    Tagged<JSFunction> array_function = native_context->array_function();
    map = array_function->initial_map();
  }
  return NewJSArrayWithUnverifiedElements(direct_handle(map, isolate()),
                                          elements, length, allocation);
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::Tagged< HeapObject >::is_null(), isolate(), length, v8::internal::native_context, and v8::internal::Isolate::raw_native_context().
Referenced by NewJSArray(), NewJSArrayForTemplateLiteralArray(), and NewJSArrayWithElements().
NewJSArrayWithUnverifiedElements() [2/2]
Handle< JSArray > v8::internal::Factory::NewJSArrayWithUnverifiedElements (DirectHandle< Map > map, DirectHandle< FixedArrayBase > elements, int length, AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 3277 of file factory.cc.
                               {
  auto array = Cast<JSArray>(NewJSObjectFromMap(map, allocation));
  DisallowGarbageCollection no_gc;
  Tagged<JSArray> raw = *array;
  raw->set_elements(*elements);
  raw->set_length(Smi::FromInt(length));
  return array;
}
References v8::internal::Smi::FromInt(), length, NewJSObjectFromMap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
NewJSAsyncDisposableStack()
DirectHandle< JSAsyncDisposableStack > v8::internal::Factory::NewJSAsyncDisposableStack (DirectHandle< Map > map)
Definition at line 3439 of file factory.cc.
                           {
  DirectHandle<JSAsyncDisposableStack> disposable_stack(
      Cast<JSAsyncDisposableStack>(NewJSObjectFromMap(map)));
  disposable_stack->set_status(0);
  return disposable_stack;
}
References NewJSObjectFromMap().
NewJSAsyncFromSyncIterator()
DirectHandle< JSAsyncFromSyncIterator > v8::internal::Factory::NewJSAsyncFromSyncIterator (DirectHandle< JSReceiver > sync_iterator, DirectHandle< Object > next)
Definition at line 3606 of file factory.cc.
                                                                       {
  DirectHandle<Map> map(
      isolate()->native_context()->async_from_sync_iterator_map(), isolate());
  DirectHandle<JSAsyncFromSyncIterator> iterator =
      Cast<JSAsyncFromSyncIterator>(
          NewJSObjectFromMap(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  Tagged<JSAsyncFromSyncIterator> raw = *iterator;
  raw->set_sync_iterator(*sync_iterator, SKIP_WRITE_BARRIER);
  raw->set_next(*next, SKIP_WRITE_BARRIER);
  return iterator;
}
References isolate(), v8::internal::kYoung, v8::internal::native_context, NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::RUNTIME_FUNCTION().
NewJSAtomicsCondition()
Handle< JSAtomicsCondition > v8::internal::Factory::NewJSAtomicsCondition ()
Definition at line 4652 of file factory.cc.
                                                          {
  SharedObjectSafePublishGuard publish_guard;
  DirectHandle<Map> map = js_atomics_condition_map();
  Handle<JSAtomicsCondition> cond = Cast<JSAtomicsCondition>(
      NewJSObjectFromMap(map, AllocationType::kSharedOld));
  cond->set_state(JSAtomicsCondition::kEmptyState);
  cond->SetNullWaiterQueueHead();
  return cond;
}
References v8::internal::kSharedOld, and NewJSObjectFromMap().
NewJSAtomicsMutex()
Handle< JSAtomicsMutex > v8::internal::Factory::NewJSAtomicsMutex ()
Definition at line 4641 of file factory.cc.
                                                  {
  SharedObjectSafePublishGuard publish_guard;
  DirectHandle<Map> map = js_atomics_mutex_map();
  auto mutex =
      Cast<JSAtomicsMutex>(NewJSObjectFromMap(map, AllocationType::kSharedOld));
  mutex->set_state(JSAtomicsMutex::kUnlockedUncontended);
  mutex->set_owner_thread_id(ThreadId::Invalid().ToInteger());
  mutex->SetNullWaiterQueueHead();
  return mutex;
}
References v8::internal::ThreadId::Invalid(), v8::internal::kSharedOld, v8::internal::JSAtomicsMutex::kUnlockedUncontended, and NewJSObjectFromMap().
NewJSBoundFunction()
MaybeDirectHandle< JSBoundFunction > v8::internal::Factory::NewJSBoundFunction (DirectHandle< JSReceiver > target_function, DirectHandle< JSAny > bound_this, base::Vector< DirectHandle< Object >> bound_args, DirectHandle< JSPrototype > prototype)
Definition at line 3764 of file factory.cc.
                                         {
  DCHECK(IsCallable(*target_function));
  static_assert(Code::kMaxArguments <= FixedArray::kMaxLength);
  if (bound_args.length() >= Code::kMaxArguments) {
    THROW_NEW_ERROR(isolate(),
                    NewRangeError(MessageTemplate::kTooManyArguments));
  }
  SaveAndSwitchContext save(isolate(),
                            target_function->GetCreationContext().value());
  // Create the [[BoundArguments]] for the result.
  DirectHandle<FixedArray> bound_arguments;
  if (bound_args.empty()) {
    bound_arguments = empty_fixed_array();
  } else {
    bound_arguments = NewFixedArray(bound_args.length());
    for (int i = 0; i < bound_args.length(); ++i) {
      bound_arguments->set(i, *bound_args[i]);
    }
  }
  // Setup the map for the JSBoundFunction instance.
  DirectHandle<Map> map =
      IsConstructor(*target_function)
          ? isolate()->bound_function_with_constructor_map()
          : isolate()->bound_function_without_constructor_map();
  if (map->prototype() != *prototype) {
    map = Map::TransitionRootMapToPrototypeForNewObject(isolate(), map,
                                                        prototype);
  }
  DCHECK_EQ(IsConstructor(*target_function), map->is_constructor());
  // Setup the JSBoundFunction instance.
  DirectHandle<JSBoundFunction> result =
      Cast<JSBoundFunction>(NewJSObjectFromMap(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  Tagged<JSBoundFunction> raw = *result;
  raw->set_bound_target_function(Cast<JSCallable>(*target_function),
                                 SKIP_WRITE_BARRIER);
  raw->set_bound_this(*bound_this, SKIP_WRITE_BARRIER);
  raw->set_bound_arguments(*bound_arguments, SKIP_WRITE_BARRIER);
  return result;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), v8::internal::Code::kMaxArguments, v8::internal::FixedArray::kMaxLength, v8::internal::kYoung, v8::internal::FactoryBase< Factory >::NewFixedArray(), NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::prototype, v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, THROW_NEW_ERROR, and v8::internal::Map::TransitionRootMapToPrototypeForNewObject().
Referenced by v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind().
NewJSDataViewOrRabGsabDataView()
Handle< JSDataViewOrRabGsabDataView > v8::internal::Factory::NewJSDataViewOrRabGsabDataView (DirectHandle< JSArrayBuffer > buffer, size_t byte_offset, size_t byte_length, bool is_length_tracking = false)
Definition at line 3723 of file factory.cc.
                             {
  if (is_length_tracking) {
    // Security: enforce the invariant that length-tracking DataViews have their
    // byte_length set to 0.
    byte_length = 0;
  }
  bool is_backed_by_rab = !buffer->is_shared() && buffer->is_resizable_by_js();
  DirectHandle<Map> map;
  if (is_backed_by_rab || is_length_tracking) {
    map = direct_handle(
        isolate()->native_context()->js_rab_gsab_data_view_map(), isolate());
  } else {
    map = direct_handle(
        isolate()->native_context()->data_view_fun()->initial_map(), isolate());
  }
  Handle<JSDataViewOrRabGsabDataView> obj =
      Cast<JSDataViewOrRabGsabDataView>(NewJSArrayBufferView(
          map, empty_fixed_array(), buffer, byte_offset, byte_length));
  obj->set_data_pointer(
      isolate(), static_cast<uint8_t*>(buffer->backing_store()) + byte_offset);
  obj->set_is_length_tracking(is_length_tracking);
  obj->set_is_backed_by_rab(is_backed_by_rab);
  return obj;
}
References v8::internal::direct_handle(), v8::internal::compiler::initial_map, v8::internal::is_backed_by_rab, isolate(), v8::internal::native_context, and NewJSArrayBufferView().
Referenced by v8::DataView::New(), and v8::internal::ValueDeserializer::ReadJSArrayBufferView().
NewJSDisposableStackBase()
DirectHandle< JSDisposableStackBase > v8::internal::Factory::NewJSDisposableStackBase ()
Definition at line 3422 of file factory.cc.
                                                                      {
  DirectHandle<NativeContext> native_context = isolate()->native_context();
  DirectHandle<Map> map(native_context->js_disposable_stack_map(), isolate());
  DirectHandle<JSDisposableStackBase> disposable_stack(
      Cast<JSDisposableStackBase>(NewJSObjectFromMap(map)));
  disposable_stack->set_status(0);
  return disposable_stack;
}
References isolate(), v8::internal::Isolate::native_context(), v8::internal::native_context, and NewJSObjectFromMap().
NewJSGeneratorObject()
DirectHandle< JSGeneratorObject > v8::internal::Factory::NewJSGeneratorObject (DirectHandle< JSFunction > function)
Definition at line 3410 of file factory.cc.
                                       {
  DCHECK(IsResumableFunction(function->shared()->kind()));
  JSFunction::EnsureHasInitialMap(isolate(), function);
  DirectHandle<Map> map(function->initial_map(), isolate());
  DCHECK(map->instance_type() == JS_GENERATOR_OBJECT_TYPE ||
         map->instance_type() == JS_ASYNC_GENERATOR_OBJECT_TYPE);
  return Cast<JSGeneratorObject>(NewJSObjectFromMap(map));
}
References v8::internal::DCHECK(), v8::internal::JSFunction::EnsureHasInitialMap(), isolate(), v8::internal::IsResumableFunction(), and NewJSObjectFromMap().
NewJSGlobalObject()
Handle< JSGlobalObject > v8::internal::Factory::NewJSGlobalObject (DirectHandle< JSFunction > constructor)
Definition at line 3045 of file factory.cc.
                                          {
  DCHECK(constructor->has_initial_map());
  DirectHandle<Map> map(constructor->initial_map(), isolate());
  DCHECK(map->is_dictionary_map());
  // Make sure no field properties are described in the initial map.
  // This guarantees us that normalizing the properties does not
  // require us to change property values to PropertyCells.
  DCHECK_EQ(map->NextFreePropertyIndex(), 0);
  // Make sure we don't have a ton of pre-allocated slots in the
  // global objects. They will be unused once we normalize the object.
  DCHECK_EQ(map->UnusedPropertyFields(), 0);
  DCHECK_EQ(map->GetInObjectProperties(), 0);
  // Initial size of the backing store to avoid resize of the storage during
  // bootstrapping. The size differs between the JS global object ad the
  // builtins object.
  int initial_size = 64;
  // Allocate a dictionary object for backing storage.
  int at_least_space_for = map->NumberOfOwnDescriptors() * 2 + initial_size;
  Handle<GlobalDictionary> dictionary =
      GlobalDictionary::New(isolate(), at_least_space_for);
  // The global object might be created from an object template with accessors.
  // Fill these accessors into the dictionary.
  DirectHandle<DescriptorArray> descs(map->instance_descriptors(isolate()),
                                      isolate());
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    PropertyDetails details = descs->GetDetails(i);
    // Only accessors are expected.
    DCHECK_EQ(PropertyKind::kAccessor, details.kind());
    PropertyDetails d(PropertyKind::kAccessor, details.attributes(),
                      PropertyCellType::kMutable);
    DirectHandle<Name> name(descs->GetKey(i), isolate());
    DirectHandle<Object> value(descs->GetStrongValue(i), isolate());
    DirectHandle<PropertyCell> cell = NewPropertyCell(name, d, value);
    // |dictionary| already contains enough space for all properties.
    USE(GlobalDictionary::Add(isolate(), dictionary, name, cell, d));
  }
  // Allocate the global object and initialize it with the backing store.
  Handle<JSGlobalObject> global(
      Cast<JSGlobalObject>(New(map, AllocationType::kOld)), isolate());
  InitializeJSObjectFromMap(*global, *dictionary, *map,
                            NewJSObjectType::kAPIWrapper);
  // Create a new map for the global object.
  DirectHandle<Map> new_map = Map::CopyDropDescriptors(isolate(), map);
  Tagged<Map> raw_map = *new_map;
  raw_map->set_may_have_interesting_properties(true);
  raw_map->set_is_dictionary_map(true);
  LOG(isolate(), MapDetails(raw_map));
  // Set up the global object as a normalized object.
  global->set_global_dictionary(*dictionary, kReleaseStore);
  global->set_map(isolate(), raw_map, kReleaseStore);
  // Make sure result is a global object with properties in dictionary.
  DCHECK(IsJSGlobalObject(*global) && !global->HasFastProperties());
  return global;
}
References v8::bigint::Add(), v8::internal::PropertyDetails::attributes(), v8::internal::Map::CopyDropDescriptors(), v8::internal::DCHECK(), DCHECK_EQ, InitializeJSObjectFromMap(), isolate(), v8::internal::kAccessor, v8::internal::kAPIWrapper, v8::internal::PropertyDetails::kind(), v8::internal::kMutable, v8::internal::kOld, v8::kReleaseStore, LOG, v8::internal::name, New(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), NewPropertyCell(), USE, and v8::internal::value.
Referenced by v8::internal::Genesis::CreateNewGlobals().
NewJSIteratorResult()
DirectHandle< JSIteratorResult > v8::internal::Factory::NewJSIteratorResult (DirectHandle< Object > value, bool done)
Definition at line 3593 of file factory.cc.
                                           {
  DirectHandle<Map> map(isolate()->native_context()->iterator_result_map(),
                        isolate());
  DirectHandle<JSIteratorResult> js_iter_result =
      Cast<JSIteratorResult>(NewJSObjectFromMap(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  Tagged<JSIteratorResult> raw = *js_iter_result;
  raw->set_value(*value, SKIP_WRITE_BARRIER);
  raw->set_done(*ToBoolean(done), SKIP_WRITE_BARRIER);
  return js_iter_result;
}
References isolate(), v8::internal::kYoung, v8::internal::native_context, NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::FactoryBase< Factory >::ToBoolean(), and v8::internal::value.
Referenced by v8::internal::JSSegmentIterator::Next().
NewJSMap()
DirectHandle< JSMap > v8::internal::Factory::NewJSMap ()
Definition at line 3620 of file factory.cc.
                                      {
  DirectHandle<Map> map(isolate()->native_context()->js_map_map(), isolate());
  DirectHandle<JSMap> js_map = Cast<JSMap>(NewJSObjectFromMap(map));
  JSMap::Initialize(js_map, isolate());
  return js_map;
}
References v8::internal::JSMap::Initialize(), isolate(), v8::internal::native_context, and NewJSObjectFromMap().
Referenced by v8::Map::New(), and v8::internal::ValueDeserializer::ReadJSMap().
NewJSMessageObject()
Handle< JSMessageObject > v8::internal::Factory::NewJSMessageObject (MessageTemplate message, DirectHandle< Object > argument, int start_position, int end_position, DirectHandle< SharedFunctionInfo > shared_info, int bytecode_offset, DirectHandle< Script > script, DirectHandle< StackTraceInfo > stack_trace = DirectHandle<StackTraceInfo>::null())
Definition at line 3890 of file factory.cc.
                                              {
  DirectHandle<Map> map = message_object_map();
  Tagged<JSMessageObject> message_obj =
      Cast<JSMessageObject>(New(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  message_obj->set_raw_properties_or_hash(*empty_fixed_array(),
                                          SKIP_WRITE_BARRIER);
  message_obj->initialize_elements();
  message_obj->set_elements(*empty_fixed_array(), SKIP_WRITE_BARRIER);
  message_obj->set_type(message);
  message_obj->set_argument(*argument, SKIP_WRITE_BARRIER);
  message_obj->set_start_position(start_position);
  message_obj->set_end_position(end_position);
  message_obj->set_script(*script, SKIP_WRITE_BARRIER);
  if (start_position >= 0) {
    // If there's a start_position, then there's no need to store the
    // SharedFunctionInfo as it will never be necessary to regenerate the
    // position.
    message_obj->set_shared_info(Smi::FromInt(-1));
    message_obj->set_bytecode_offset(Smi::FromInt(0));
  } else {
    message_obj->set_bytecode_offset(Smi::FromInt(bytecode_offset));
    if (shared_info.is_null()) {
      message_obj->set_shared_info(Smi::FromInt(-1));
      DCHECK_EQ(bytecode_offset, -1);
    } else {
      message_obj->set_shared_info(*shared_info, SKIP_WRITE_BARRIER);
      DCHECK_GE(bytecode_offset, kFunctionEntryBytecodeOffset);
    }
  }
  if (stack_trace.is_null()) {
    message_obj->set_stack_trace(*the_hole_value(), SKIP_WRITE_BARRIER);
  } else {
    message_obj->set_stack_trace(*stack_trace, SKIP_WRITE_BARRIER);
  }
  message_obj->set_error_level(v8::Isolate::kMessageError);
  return handle(message_obj, isolate());
}
References DCHECK_EQ, DCHECK_GE, v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::DirectHandle< T >::is_null(), isolate(), v8::internal::kFunctionEntryBytecodeOffset, v8::Isolate::kMessageError, v8::internal::kYoung, New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::script, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::MessageHandler::MakeMessageObject().
NewJSModuleNamespace()
DirectHandle< JSModuleNamespace > v8::internal::Factory::NewJSModuleNamespace ()
Definition at line 3376 of file factory.cc.
                                                              {
  DirectHandle<Map> map = isolate()->js_module_namespace_map();
  DirectHandle<JSModuleNamespace> module_namespace(
      Cast<JSModuleNamespace>(NewJSObjectFromMap(
          map, AllocationType::kYoung, DirectHandle<AllocationSite>::null(),
          NewJSObjectType::kAPIWrapper)));
  FieldIndex index = FieldIndex::ForDescriptor(
      *map, InternalIndex(JSModuleNamespace::kToStringTagFieldIndex));
  module_namespace->FastPropertyAtPut(index, read_only_roots().Module_string(),
                                      SKIP_WRITE_BARRIER);
  return module_namespace;
}
References v8::internal::FieldIndex::ForDescriptor(), v8::internal::index, isolate(), v8::internal::kAPIWrapper, v8::internal::JSModuleNamespace::kToStringTagFieldIndex, v8::internal::kYoung, NewJSObjectFromMap(), read_only_roots(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Module::GetModuleNamespace().
NewJSObject()
Handle< JSObject > v8::internal::Factory::NewJSObject (DirectHandle< JSFunction > constructor, AllocationType allocation = AllocationType::kYoung, NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper)
Definition at line 3018 of file factory.cc.
                                                                          {
  JSFunction::EnsureHasInitialMap(isolate(), constructor);
  DirectHandle<Map> map(constructor->initial_map(), isolate());
  // NewJSObjectFromMap does not support creating dictionary mode objects. Need
  // to use NewSlowJSObjectFromMap instead.
  DCHECK(!map->is_dictionary_map());
  return NewJSObjectFromMap(map, allocation,
                            DirectHandle<AllocationSite>::null(),
                            new_js_object_type);
}
References v8::internal::DCHECK(), v8::internal::JSFunction::EnsureHasInitialMap(), isolate(), and NewJSObjectFromMap().
Referenced by v8::internal::BUILTIN(), v8::internal::CloneObjectSlowPath(), v8::internal::Genesis::CreateArrayBuffer(), v8::internal::Genesis::CreateAsyncFunctionMaps(), v8::internal::Genesis::CreateAsyncIteratorMaps(), v8::internal::Genesis::CreateIteratorMaps(), v8::internal::JSAtomicsMutex::CreateResultObject(), v8::internal::JsonStringifier::CurrentHolder(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareEvalHelper(), v8::internal::wasm::GetExports(), v8::internal::wasm::GetImports(), v8::internal::anonymous_namespace{runtime-debug.cc}::GetJSPositionInfo(), v8::internal::JSLocale::GetTextInfo(), v8::internal::wasm::GetTypeForFunction(), v8::internal::wasm::GetTypeForGlobal(), v8::internal::wasm::GetTypeForMemory(), v8::internal::wasm::GetTypeForTable(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::Genesis::InitializeConsole(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InitializeIteratorFunctions(), v8::internal::anonymous_namespace{intl-objects.cc}::InnerAddElement(), v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), v8::internal::JsonParseInternalizer::Internalize(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::WasmTrustedInstanceData::New(), v8::Object::New(), v8::internal::WasmTagObject::New(), v8::internal::WasmMemoryObject::New(), v8::internal::WasmSuspendingObject::New(), v8::internal::WasmDescriptorOptions::New(), v8::internal::JSRegExp::New(), v8::internal::WasmExceptionPackage::New(), v8::internal::WasmGlobalObject::New(), v8::internal::WasmTableObject::New(), v8::internal::WasmModuleObject::New(), v8::internal::WasmMemoryMapDescriptor::NewFromFileDescriptor(), NewJSPromiseWithoutHook(), NewJSSharedArray(), NewJSSharedStruct(), v8::internal::WasmJs::PrepareForSnapshot(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::ValueDeserializer::ReadJSObject(), v8::internal::ValueDeserializer::ReadJSPrimitiveWrapper(), v8::internal::ValueDeserializer::ReadObjectUsingEntireBufferForLegacyFormat(), v8::internal::JSCollator::ResolvedOptions(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::JSDurationFormat::ResolvedOptions(), v8::internal::JSListFormat::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::JSPluralRules::ResolvedOptions(), v8::internal::JSRelativeTimeFormat::ResolvedOptions(), v8::internal::JSSegmenter::ResolvedOptions(), v8::internal::JSV8BreakIterator::ResolvedOptions(), v8::internal::PropertyDescriptor::ToObject(), v8::internal::Object::ToObjectImpl(), and v8::internal::FutexEmulation::WaitAsync().
NewJSObjectFromMap()
Handle< JSObject > v8::internal::Factory::NewJSObjectFromMap (DirectHandle< Map > map, AllocationType allocation = AllocationType::kYoung, DirectHandle< AllocationSite > allocation_site = DirectHandle<AllocationSite>::null(), NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper)
Definition at line 3159 of file factory.cc.
                                        {
  // JSFunctions should be allocated using AllocateFunction to be
  // properly initialized.
  DCHECK(!InstanceTypeChecker::IsJSFunction(*map));
  // Both types of global objects should be allocated using
  // AllocateGlobalObject to be properly initialized.
  DCHECK_NE(map->instance_type(), JS_GLOBAL_OBJECT_TYPE);
  Tagged<JSObject> js_obj = Cast<JSObject>(
      AllocateRawWithAllocationSite(map, allocation, allocation_site));
  InitializeJSObjectFromMap(js_obj, *empty_fixed_array(), *map,
                            new_js_object_type);
  DCHECK(js_obj->HasFastElements() ||
         (isolate()->bootstrapper()->IsActive() ||
          *map == isolate()
                      ->raw_native_context()
                      ->js_array_template_literal_object_map()) ||
         js_obj->HasTypedArrayOrRabGsabTypedArrayElements() ||
         js_obj->HasFastStringWrapperElements() ||
         js_obj->HasFastArgumentsElements() ||
         js_obj->HasDictionaryElements() || js_obj->HasSharedArrayElements());
  return handle(js_obj, isolate());
}
References AllocateRawWithAllocationSite(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::handle(), InitializeJSObjectFromMap(), and isolate().
Referenced by v8::internal::WasmStruct::AllocatePrototype(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::Create(), v8::internal::JSSegments::Create(), v8::internal::JSSegmentIterator::Create(), v8::internal::JSRawJson::Create(), v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::anonymous_namespace{runtime-classes.cc}::CreateClassPrototype(), v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::ApiNatives::InstantiateRemoteObject(), v8::internal::WasmValueObject::New(), NewArgumentsObject(), NewExternal(), NewFastOrSlowJSObjectFromMap(), NewFunctionPrototype(), v8::internal::DictionaryTemplateInfo::NewInstance(), NewJSArrayBuffer(), NewJSArrayBufferAndBackingStore(), NewJSArrayBufferView(), NewJSArrayWithUnverifiedElements(), NewJSAsyncDisposableStack(), NewJSAsyncFromSyncIterator(), NewJSAtomicsCondition(), NewJSAtomicsMutex(), NewJSBoundFunction(), NewJSDisposableStackBase(), NewJSGeneratorObject(), NewJSIteratorResult(), NewJSMap(), NewJSModuleNamespace(), NewJSObject(), NewJSObjectWithNullProto(), NewJSSet(), NewJSSharedArrayBuffer(), NewJSStringIterator(), NewJSSyncDisposableStack(), NewJSUint8ArraySetFromResult(), NewJSWeakMap(), NewJSWrappedFunction(), NewSlowJSObjectFromMap(), NewSlowJSObjectWithPropertiesAndElements(), NewUninitializedJSGlobalProxy(), v8::internal::JSSegmentIterator::Next(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::PropertyDescriptor::ToObject().
NewJSObjectWithNullProto()
Handle< JSObject > v8::internal::Factory::NewJSObjectWithNullProto ()
Definition at line 3037 of file factory.cc.
                                                   {
  DirectHandle<Map> map(isolate()->object_function()->initial_map(), isolate());
  DirectHandle<Map> map_with_null_proto =
      Map::TransitionRootMapToPrototypeForNewObject(isolate(), map,
                                                    null_value());
  return NewJSObjectFromMap(map_with_null_proto);
}
References v8::internal::compiler::initial_map, isolate(), NewJSObjectFromMap(), and v8::internal::Map::TransitionRootMapToPrototypeForNewObject().
Referenced by v8::internal::CloneObjectSlowPath(), v8::internal::CoerceOptionsToObject(), v8::internal::anonymous_namespace{runtime-regexp.cc}::ConstructNamedCaptureGroupsObject(), v8::internal::CreateDummyWasmLookAlikeForFuzzing(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), v8::internal::GetOptionsObject(), v8::internal::Genesis::InitializeGlobal(), v8::internal::Genesis::InstallExtrasBindings(), v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSTemporalInstant::Round(), and v8::internal::Isolate::RunHostInitializeImportMetaObjectCallback().
NewJSPromise()
Handle< JSPromise > v8::internal::Factory::NewJSPromise ()
Definition at line 4562 of file factory.cc.
                                        {
  Handle<JSPromise> promise = NewJSPromiseWithoutHook();
  isolate()->RunAllPromiseHooks(PromiseHookType::kInit, promise,
                                undefined_value());
  return promise;
}
References isolate(), v8::kInit, NewJSPromiseWithoutHook(), and v8::internal::Isolate::RunAllPromiseHooks().
Referenced by v8::internal::SyntheticModule::Evaluate(), v8::internal::Module::Evaluate(), v8::internal::SourceTextModule::Evaluate(), v8::internal::SourceTextModule::ExecuteAsyncModule(), v8::internal::JSAtomicsMutex::LockAsyncWrapperForWait(), v8::internal::JSAtomicsMutex::LockOrEnqueuePromise(), v8::Promise::Resolver::New(), v8::internal::FutexEmulation::WaitAsync(), and v8::internal::JSAtomicsCondition::WaitAsync().
NewJSPromiseWithoutHook()
Handle< JSPromise > v8::internal::Factory::NewJSPromiseWithoutHook ()
Definition at line 4549 of file factory.cc.
                                                   {
  Handle<JSPromise> promise =
      Cast<JSPromise>(NewJSObject(isolate()->promise_function()));
  DisallowGarbageCollection no_gc;
  Tagged<JSPromise> raw = *promise;
  raw->set_reactions_or_result(Smi::zero(), SKIP_WRITE_BARRIER);
  raw->set_flags(0);
  // TODO(v8) remove once embedder data slots are always zero-initialized.
  InitEmbedderFields(*promise, Smi::zero());
  DCHECK_EQ(raw->GetEmbedderFieldCount(), v8::Promise::kEmbedderFieldCount);
  return promise;
}
References DCHECK_EQ, v8::internal::anonymous_namespace{factory.cc}::InitEmbedderFields(), isolate(), v8::Promise::kEmbedderFieldCount, NewJSObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Smi::zero().
Referenced by NewJSPromise().
NewJSProxy()
Handle< JSProxy > v8::internal::Factory::NewJSProxy (DirectHandle< JSReceiver > target, DirectHandle< JSReceiver > handler, bool revocable)
Definition at line 3813 of file factory.cc.
                                                    {
  // Allocate the proxy object.
  DirectHandle<Map> map = IsCallable(*target)
                              ? IsConstructor(*target)
                                    ? isolate()->proxy_constructor_map()
                                    : isolate()->proxy_callable_map()
                              : isolate()->proxy_map();
  DCHECK(IsNull(map->prototype(), isolate()));
  Tagged<JSProxy> result = Cast<JSProxy>(New(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  result->initialize_properties(isolate());
  result->set_target(*target, SKIP_WRITE_BARRIER);
  result->set_handler(*handler, SKIP_WRITE_BARRIER);
  result->set_flags(JSProxy::IsRevocableBit::encode(revocable));
  return handle(result, isolate());
}
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::handle(), v8::internal::IsNull(), isolate(), v8::internal::kYoung, New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::JSProxy::New().
NewJSSet()
DirectHandle< JSSet > v8::internal::Factory::NewJSSet ()
Definition at line 3627 of file factory.cc.
                                      {
  DirectHandle<Map> map(isolate()->native_context()->js_set_map(), isolate());
  DirectHandle<JSSet> js_set = Cast<JSSet>(NewJSObjectFromMap(map));
  JSSet::Initialize(js_set, isolate());
  return js_set;
}
References v8::internal::JSSet::Initialize(), isolate(), v8::internal::native_context, and NewJSObjectFromMap().
Referenced by v8::Set::New(), and v8::internal::ValueDeserializer::ReadJSSet().
NewJSSharedArray()
DirectHandle< JSSharedArray > v8::internal::Factory::NewJSSharedArray (DirectHandle< JSFunction > constructor, int length)
Definition at line 4626 of file factory.cc.
                                                      {
  SharedObjectSafePublishGuard publish_guard;
  DirectHandle<FixedArrayBase> storage =
      NewFixedArray(length, AllocationType::kSharedOld);
  auto instance =
      Cast<JSSharedArray>(NewJSObject(constructor, AllocationType::kSharedOld));
  instance->set_elements(*storage);
  FieldIndex index = FieldIndex::ForDescriptor(
      constructor->initial_map(),
      InternalIndex(JSSharedArray::kLengthFieldIndex));
  instance->FastPropertyAtPut(index, Smi::FromInt(length), SKIP_WRITE_BARRIER);
  return instance;
}
References v8::internal::FieldIndex::ForDescriptor(), v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::JSSharedArray::kLengthFieldIndex, v8::internal::kSharedOld, length, v8::internal::FactoryBase< Factory >::NewFixedArray(), NewJSObject(), and v8::internal::SKIP_WRITE_BARRIER.
NewJSSharedArrayBuffer()
Handle< JSArrayBuffer > v8::internal::Factory::NewJSSharedArrayBuffer (std::shared_ptr< BackingStore > backing_store)
Definition at line 3577 of file factory.cc.
                                               {
  DirectHandle<Map> map(
      isolate()->native_context()->shared_array_buffer_fun()->initial_map(),
      isolate());
  auto result = Cast<JSArrayBuffer>(NewJSObjectFromMap(
      map, AllocationType::kYoung, DirectHandle<AllocationSite>::null(),
      NewJSObjectType::kAPIWrapper));
  ResizableFlag resizable = backing_store->is_resizable_by_js()
                                ? ResizableFlag::kResizable
                                : ResizableFlag::kNotResizable;
  result->Setup(SharedFlag::kShared, resizable, std::move(backing_store),
                isolate());
  return result;
}
References v8::internal::compiler::initial_map, isolate(), v8::internal::kAPIWrapper, v8::internal::kNotResizable, v8::internal::kResizable, v8::internal::kShared, v8::internal::kYoung, v8::internal::native_context, NewJSObjectFromMap(), and v8::base::internal::result.
Referenced by v8::SharedArrayBuffer::MaybeNew(), v8::internal::WasmMemoryObject::New(), v8::SharedArrayBuffer::New(), and v8::internal::WasmMemoryObject::RefreshSharedBuffer().
NewJSSharedStruct()
DirectHandle< JSSharedStruct > v8::internal::Factory::NewJSSharedStruct (DirectHandle< JSFunction > constructor, MaybeDirectHandle< NumberDictionary > maybe_elements_template)
Definition at line 4591 of file factory.cc.
                                                                 {
  SharedObjectSafePublishGuard publish_guard;
  DirectHandle<Map> instance_map(constructor->initial_map(), isolate());
  DirectHandle<PropertyArray> property_array;
  const int num_oob_fields =
      instance_map->NumberOfFields(ConcurrencyMode::kSynchronous) -
      instance_map->GetInObjectProperties();
  if (num_oob_fields > 0) {
    property_array =
        NewPropertyArray(num_oob_fields, AllocationType::kSharedOld);
  }
  DirectHandle<NumberDictionary> elements_dictionary;
  bool has_elements_dictionary;
  if ((has_elements_dictionary =
           maybe_elements_template.ToHandle(&elements_dictionary))) {
    elements_dictionary = NumberDictionary::ShallowCopy(
        isolate(), elements_dictionary, AllocationType::kSharedOld);
  }
  DirectHandle<JSSharedStruct> instance = Cast<JSSharedStruct>(
      NewJSObject(constructor, AllocationType::kSharedOld));
  // The struct object has not been fully initialized yet. Disallow allocation
  // from this point on.
  DisallowGarbageCollection no_gc;
  if (!property_array.is_null()) instance->SetProperties(*property_array);
  if (has_elements_dictionary) instance->set_elements(*elements_dictionary);
  return instance;
}
References v8::internal::DirectHandle< T >::is_null(), isolate(), v8::internal::kSharedOld, v8::internal::kSynchronous, NewJSObject(), NewPropertyArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::MaybeDirectHandle< T >::ToHandle().
NewJSStringIterator()
DirectHandle< JSStringIterator > v8::internal::Factory::NewJSStringIterator (Handle< String > string)
Definition at line 1199 of file factory.cc.
                           {
  DirectHandle<Map> map(
      isolate()->native_context()->initial_string_iterator_map(), isolate());
  DirectHandle<String> flat_string = String::Flatten(isolate(), string);
  DirectHandle<JSStringIterator> iterator =
      Cast<JSStringIterator>(NewJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  Tagged<JSStringIterator> raw = *iterator;
  raw->set_string(*flat_string);
  raw->set_index(0);
  return iterator;
}
References isolate(), v8::internal::native_context, NewJSObjectFromMap(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
NewJSSyncDisposableStack()
DirectHandle< JSSyncDisposableStack > v8::internal::Factory::NewJSSyncDisposableStack (DirectHandle< Map > map)
Definition at line 3431 of file factory.cc.
                           {
  DirectHandle<JSSyncDisposableStack> disposable_stack(
      Cast<JSSyncDisposableStack>(NewJSObjectFromMap(map)));
  disposable_stack->set_status(0);
  return disposable_stack;
}
References NewJSObjectFromMap().
NewJSTypedArray()
Handle< JSTypedArray > v8::internal::Factory::NewJSTypedArray (ExternalArrayType type, DirectHandle< JSArrayBuffer > buffer, size_t byte_offset, size_t length, bool is_length_tracking = false)
Definition at line 3680 of file factory.cc.
                                                                {
  size_t element_size;
  ElementsKind elements_kind;
  JSTypedArray::ForFixedTypedArray(type, &element_size, &elements_kind);
  const bool is_backed_by_rab =
      buffer->is_resizable_by_js() && !buffer->is_shared();
  DirectHandle<Map> map;
  if (is_backed_by_rab || is_length_tracking) {
    map = direct_handle(
        isolate()->raw_native_context()->TypedArrayElementsKindToRabGsabCtorMap(
            elements_kind),
        isolate());
  } else {
    map = direct_handle(
        isolate()->raw_native_context()->TypedArrayElementsKindToCtorMap(
            elements_kind),
        isolate());
  }
  if (is_length_tracking) {
    // Security: enforce the invariant that length-tracking TypedArrays have
    // their length and byte_length set to 0.
    length = 0;
  }
  CHECK_LE(length, JSTypedArray::kMaxByteLength / element_size);
  CHECK_EQ(0, byte_offset % element_size);
  size_t byte_length = length * element_size;
  Handle<JSTypedArray> typed_array = Cast<JSTypedArray>(NewJSArrayBufferView(
      map, empty_byte_array(), buffer, byte_offset, byte_length));
  Tagged<JSTypedArray> raw = *typed_array;
  DisallowGarbageCollection no_gc;
  raw->SetOffHeapDataPtr(isolate(), buffer->backing_store(), byte_offset);
  raw->set_is_length_tracking(is_length_tracking);
  raw->set_is_backed_by_rab(is_backed_by_rab);
  return typed_array;
}
References CHECK_EQ, CHECK_LE, v8::internal::direct_handle(), v8::internal::JSTypedArray::ForFixedTypedArray(), v8::internal::is_backed_by_rab, isolate(), v8::internal::JSTypedArray::kMaxByteLength, length, NewJSArrayBufferView(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::tracing::type.
Referenced by v8::internal::Runtime::GetInternalProperties(), v8::Float16Array::New(), and v8::internal::ValueDeserializer::ReadJSArrayBufferView().
NewJSUint8ArraySetFromResult()
DirectHandle< JSUint8ArraySetFromResult > v8::internal::Factory::NewJSUint8ArraySetFromResult (DirectHandle< Number > read, DirectHandle< Number > written)
Definition at line 3750 of file factory.cc.
                                                             {
  DirectHandle<Map> map(
      isolate()->native_context()->set_unit8_array_result_map(), isolate());
  DirectHandle<JSUint8ArraySetFromResult> js_uint8_array_set_from_result =
      Cast<JSUint8ArraySetFromResult>(
          NewJSObjectFromMap(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  Tagged<JSUint8ArraySetFromResult> raw = *js_uint8_array_set_from_result;
  raw->set_read(*read, SKIP_WRITE_BARRIER);
  raw->set_written(*written, SKIP_WRITE_BARRIER);
  return js_uint8_array_set_from_result;
}
References isolate(), v8::internal::kYoung, v8::internal::native_context, NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
NewJSWeakMap()
Handle< JSWeakMap > v8::internal::Factory::NewJSWeakMap ()
Definition at line 3362 of file factory.cc.
                                        {
  Tagged<NativeContext> native_context = isolate()->raw_native_context();
  DirectHandle<Map> map(native_context->js_weak_map_fun()->initial_map(),
                        isolate());
  Handle<JSWeakMap> weakmap(Cast<JSWeakMap>(*NewJSObjectFromMap(map)),
                            isolate());
  {
    // Do not leak handles for the hash table, it would make entries strong.
    HandleScope scope(isolate());
    JSWeakCollection::Initialize(weakmap, isolate());
  }
  return weakmap;
}
References v8::internal::JSWeakCollection::Initialize(), isolate(), v8::internal::native_context, NewJSObjectFromMap(), and v8::internal::Isolate::raw_native_context().
NewJSWrappedFunction()
DirectHandle< JSWrappedFunction > v8::internal::Factory::NewJSWrappedFunction (DirectHandle< NativeContext > creation_context, DirectHandle< Object > target)
Definition at line 3389 of file factory.cc.
                                                                               {
  DCHECK(IsCallable(*target));
  DirectHandle<Map> map(Cast<Map>(creation_context->GetNoCell(
                            Context::WRAPPED_FUNCTION_MAP_INDEX)),
                        isolate());
  // 2. Let wrapped be ! MakeBasicObject(internalSlotsList).
  // 3. Set wrapped.[[Prototype]] to
  // callerRealm.[[Intrinsics]].[[%Function->prototype%]].
  // 4. Set wrapped.[[Call]] as described in 2.1.
  DirectHandle<JSWrappedFunction> wrapped =
      Cast<JSWrappedFunction>(isolate()->factory()->NewJSObjectFromMap(map));
  // 5. Set wrapped.[[WrappedTargetFunction]] to Target.
  wrapped->set_wrapped_target_function(Cast<JSCallable>(*target));
  // 6. Set wrapped.[[Realm]] to callerRealm.
  wrapped->set_context(*creation_context);
  // TODO(v8:11989): https://github.com/tc39/proposal-shadowrealm/pull/348
  return wrapped;
}
References v8::internal::DCHECK(), isolate(), and NewJSObjectFromMap().
Referenced by v8::internal::JSWrappedFunction::Create().
NewLoadHandler()
Handle< LoadHandler > v8::internal::Factory::NewLoadHandler (int data_count, AllocationType allocation = AllocationType::kOld)
Definition at line 4151 of file factory.cc.
                                                                       {
  DirectHandle<Map> map;
  switch (data_count) {
    case 1:
      map = load_handler1_map();
      break;
    case 2:
      map = load_handler2_map();
      break;
    case 3:
      map = load_handler3_map();
      break;
    default:
      UNREACHABLE();
  }
  return handle(Cast<LoadHandler>(New(map, allocation)), isolate());
}
References v8::internal::handle(), isolate(), New(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::LoadHandler::LoadFromPrototype(), v8::internal::LoadHandler::LoadFullChain(), and v8::internal::LoadHandler::LoadNonExistent().
NewManyClosuresCell()
DirectHandle< FeedbackCell > v8::internal::Factory::NewManyClosuresCell (AllocationType allocation = AllocationType::kOld)
Definition at line 2236 of file factory.cc.
                               {
  Tagged<FeedbackCell> result = Cast<FeedbackCell>(AllocateRawWithImmortalMap(
      FeedbackCell::kAlignedSize, allocation, *many_closures_cell_map()));
  DisallowGarbageCollection no_gc;
  result->set_value(read_only_roots().undefined_value());
  result->clear_interrupt_budget();
  result->clear_dispatch_handle();
  result->clear_padding();
  return direct_handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), isolate(), v8::internal::FeedbackCell::kAlignedSize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), and v8::base::internal::result.
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
NewMap()
Handle< Map > v8::internal::Factory::NewMap (DirectHandle< HeapObject > meta_map_holder, InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap)
Definition at line 2403 of file factory.cc.
                                                            {
  auto meta_map_provider = [meta_map_holder] {
    // Tie new map to the same native context as given |meta_map_holder| object.
    Tagged<Map> meta_map = meta_map_holder->map();
    DCHECK(IsMapMap(meta_map));
    return meta_map;
  };
  Handle<Map> map =
      NewMapImpl(meta_map_provider, type, instance_size, elements_kind,
                 inobject_properties, allocation_type);
  return map;
}
References v8::internal::DCHECK(), NewMapImpl(), and v8::internal::tracing::type.
Referenced by v8::internal::Map::RawCopy().
NewMapImpl()
template<typename MetaMapProviderFunc >
Handle< Map > v8::internal::Factory::NewMapImpl (MetaMapProviderFunc && meta_map_provider, InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap) [inline], [private]
Definition at line 2317 of file factory.cc.
                                                                {
  static_assert(LAST_JS_OBJECT_TYPE == LAST_TYPE);
  DCHECK(!InstanceTypeChecker::MayHaveMapCheckFastCase(type));
  DCHECK_IMPLIES(InstanceTypeChecker::IsJSObject(type) &&
                     !Map::CanHaveFastTransitionableElementsKind(type),
                 IsDictionaryElementsKind(elements_kind) ||
                     IsTerminalElementsKind(elements_kind) ||
                     IsSharedArrayElementsKind(elements_kind));
  DCHECK(allocation_type == AllocationType::kMap ||
         allocation_type == AllocationType::kSharedMap);
  Tagged<HeapObject> result =
      allocator()->AllocateRawWith<HeapAllocator::kRetryOrFail>(
          Map::kSize, allocation_type);
  DisallowGarbageCollection no_gc;
  ReadOnlyRoots roots(isolate());
  result->set_map_after_allocation(isolate(), meta_map_provider());
#if V8_STATIC_ROOTS_BOOL
  CHECK_IMPLIES(InstanceTypeChecker::IsJSReceiver(type),
                V8HeapCompressionScheme::CompressObject(result.ptr()) >
                    InstanceTypeChecker::kNonJsReceiverMapLimit);
#endif
  isolate()->counters()->maps_created()->Increment();
  return handle(InitializeMap(Cast<Map>(result), type, instance_size,
                              elements_kind, inobject_properties, roots),
                isolate());
}
References v8::internal::HeapAllocator::AllocateRawWith(), allocator(), v8::internal::Map::CanHaveFastTransitionableElementsKind(), CHECK_IMPLIES, v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::handle(), InitializeMap(), v8::internal::IsDictionaryElementsKind(), isolate(), v8::internal::IsSharedArrayElementsKind(), v8::internal::IsTerminalElementsKind(), v8::internal::kMap, v8::internal::InstanceTypeChecker::kNonJsReceiverMapLimit, v8::internal::HeapAllocator::kRetryOrFail, v8::internal::kSharedMap, v8::internal::LAST_TYPE, v8::internal::InstanceTypeChecker::MayHaveMapCheckFastCase(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by NewContextfulMap(), NewContextfulMapForCurrentContext(), NewContextlessMap(), NewMap(), and NewMapWithMetaMap().
NewMapWithMetaMap()
DirectHandle< Map > v8::internal::Factory::NewMapWithMetaMap (DirectHandle< Map > meta_map, InstanceType type, int instance_size, ElementsKind elements_kind = TERMINAL_FAST_ELEMENTS_KIND, int inobject_properties = 0, AllocationType allocation_type = AllocationType::kMap)
Definition at line 2419 of file factory.cc.
                                                                             {
  DCHECK_EQ(*meta_map, meta_map->map());
  auto meta_map_provider = [meta_map] {
    // Use given meta map.
    return *meta_map;
  };
  DirectHandle<Map> map =
      NewMapImpl(meta_map_provider, type, instance_size, elements_kind,
                 inobject_properties, allocation_type);
  return map;
}
References DCHECK_EQ, NewMapImpl(), and v8::internal::tracing::type.
Referenced by v8::internal::CreateArrayMap(), v8::internal::CreateStructMap(), v8::internal::Genesis::InitializeGlobal(), and NewNativeContext().
NewMegaDomHandler()
DirectHandle< MegaDomHandler > v8::internal::Factory::NewMegaDomHandler (MaybeObjectDirectHandle accessor, MaybeObjectDirectHandle context)
Definition at line 4140 of file factory.cc.
                                                                       {
  DirectHandle<Map> map = mega_dom_handler_map();
  Tagged<MegaDomHandler> handler =
      Cast<MegaDomHandler>(New(map, AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  handler->set_accessor(*accessor, kReleaseStore);
  handler->set_context(*context);
  return direct_handle(handler, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::kOld, v8::kReleaseStore, New(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::IC::UpdateMegaDOMIC().
NewModuleContext()
DirectHandle< Context > v8::internal::Factory::NewModuleContext (DirectHandle< SourceTextModule > module, DirectHandle< NativeContext > outer, DirectHandle< ScopeInfo > scope_info)
Definition at line 1361 of file factory.cc.
                                        {
  // TODO(v8:13567): Const tracking let in module contexts.
  DCHECK_EQ(scope_info->scope_type(), MODULE_SCOPE);
  int variadic_part_length = scope_info->ContextLength();
  Tagged<Context> context = NewContextInternal(
      isolate()->module_context_map(), Context::SizeFor(variadic_part_length),
      variadic_part_length, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  context->set_scope_info(*scope_info);
  context->set_previous(*outer);
  context->set_extension(*module);
  DCHECK(context->IsModuleContext());
  return direct_handle(context, isolate());
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), isolate(), v8::internal::kOld, v8::internal::MODULE_SCOPE, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Context::SizeFor().
Referenced by v8::internal::SourceTextModule::RunInitializationCode().
NewNameDictionary()
DirectHandle< NameDictionary > v8::internal::Factory::NewNameDictionary (int at_least_space_for)
Definition at line 574 of file factory.cc.
                            {
  return NameDictionary::New(isolate(), at_least_space_for);
}
References isolate(), and v8::internal::NameDictionary::New().
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), and v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow().
NewNativeContext()
Handle< NativeContext > v8::internal::Factory::NewNativeContext ()
Definition at line 1301 of file factory.cc.
                                                {
  // All maps that belong to this new native context will have this meta map.
  // The native context does not exist yet, so create the map as contextless
  // for now.
  DirectHandle<Map> contextful_meta_map =
      NewContextlessMap(MAP_TYPE, Map::kSize);
  contextful_meta_map->set_map(isolate(), *contextful_meta_map);
  DirectHandle<Map> context_map = NewMapWithMetaMap(
      contextful_meta_map, NATIVE_CONTEXT_TYPE, kVariableSizeSentinel);
  if (v8_flags.log_maps) {
    LOG(isolate(),
        MapEvent("NewNativeContext", isolate()->factory()->meta_map(),
                 contextful_meta_map, "contextful meta map"));
    LOG(isolate(),
        MapEvent("NewNativeContext", isolate()->factory()->meta_map(),
                 context_map, "native context map"));
  }
  Tagged<NativeContext> context = Cast<NativeContext>(NewContextInternal(
      context_map, NativeContext::kSize, NativeContext::NATIVE_CONTEXT_SLOTS,
      AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  contextful_meta_map->set_native_context(context);
  context_map->set_native_context(context);
  context->set_meta_map(*contextful_meta_map);
  context->set_scope_info(*native_scope_info());
  context->set_previous(Context());
  context->set_extension(*undefined_value());
  context->set_errors_thrown(Smi::zero());
  context->set_is_wasm_js_installed(Smi::zero());
  context->set_is_wasm_jspi_installed(Smi::zero());
  context->set_math_random_index(Smi::zero());
  context->set_serialized_objects(*empty_fixed_array());
  context->init_microtask_queue(isolate(), nullptr);
  context->set_retained_maps(*empty_weak_array_list());
  return handle(context, isolate());
}
References v8::internal::handle(), isolate(), v8::internal::kOld, v8::internal::kVariableSizeSentinel, LOG, v8::internal::Context::NATIVE_CONTEXT_SLOTS, NewContextInternal(), NewContextlessMap(), NewMapWithMetaMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by v8::internal::Genesis::CreateRoots().
NewNoClosuresCell()
DirectHandle< FeedbackCell > v8::internal::Factory::NewNoClosuresCell ()
Definition at line 2207 of file factory.cc.
                                                      {
  Tagged<FeedbackCell> result = Cast<FeedbackCell>(AllocateRawWithImmortalMap(
      FeedbackCell::kAlignedSize, AllocationType::kOld,
      *no_closures_cell_map()));
  DisallowGarbageCollection no_gc;
  result->set_value(read_only_roots().undefined_value());
  result->clear_interrupt_budget();
#ifdef V8_ENABLE_LEAPTIERING
  result->clear_dispatch_handle();
#endif // V8_ENABLE_LEAPTIERING
  result->clear_padding();
  return direct_handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), isolate(), v8::internal::FeedbackCell::kAlignedSize, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), and v8::base::internal::result.
Referenced by v8::internal::ClosureFeedbackCellArray::New(), and v8::internal::FeedbackVector::NewForTesting().
NewObjectTemplateInfo()
DirectHandle< ObjectTemplateInfo > v8::internal::Factory::NewObjectTemplateInfo (DirectHandle< FunctionTemplateInfo > constructor, bool do_not_cache)
Definition at line 4718 of file factory.cc.
                                                                       {
  const int size = ObjectTemplateInfo::SizeFor();
  Tagged<ObjectTemplateInfo> obj = Cast<ObjectTemplateInfo>(
      AllocateRawWithImmortalMap(size, AllocationType::kOld,
                                 read_only_roots().object_template_info_map()));
  {
    // Disallow GC until all fields of obj have acceptable types.
    DisallowGarbageCollection no_gc;
    Tagged<ObjectTemplateInfo> raw = *obj;
    ReadOnlyRoots roots(isolate());
    InitializeTemplateWithProperties(raw, roots, !do_not_cache);
    if (constructor.is_null()) {
      raw->set_constructor(roots.undefined_value(), SKIP_WRITE_BARRIER);
    } else {
      raw->set_constructor(*constructor);
    }
    raw->set_data(0);
  }
  return direct_handle(obj, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), v8::internal::anonymous_namespace{factory.cc}::InitializeTemplateWithProperties(), v8::internal::DirectHandle< T >::is_null(), isolate(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), size(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::FunctionTemplate::InstanceTemplate(), v8::ObjectTemplate::New(), and v8::FunctionTemplate::PrototypeTemplate().
NewOneClosureCell()
DirectHandle< FeedbackCell > v8::internal::Factory::NewOneClosureCell (DirectHandle< ClosureFeedbackCellArray > value)
Definition at line 2221 of file factory.cc.
                                                  {
  Tagged<FeedbackCell> result = Cast<FeedbackCell>(AllocateRawWithImmortalMap(
      FeedbackCell::kAlignedSize, AllocationType::kOld,
      *one_closure_cell_map()));
  DisallowGarbageCollection no_gc;
  result->set_value(*value);
  result->clear_interrupt_budget();
#ifdef V8_ENABLE_LEAPTIERING
  result->clear_dispatch_handle();
#endif // V8_ENABLE_LEAPTIERING
  result->clear_padding();
  return direct_handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::direct_handle(), isolate(), v8::internal::FeedbackCell::kAlignedSize, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::JSFunction::EnsureClosureFeedbackCellArray().
NewOrderedHashMap()
Handle< OrderedHashMap > v8::internal::Factory::NewOrderedHashMap ()
Definition at line 568 of file factory.cc.
                                                  {
  return OrderedHashMap::Allocate(isolate(), OrderedHashMap::kInitialCapacity,
                                  AllocationType::kYoung)
      .ToHandleChecked();
}
References v8::internal::OrderedHashMap::Allocate(), isolate(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::kInitialCapacity, and v8::internal::kYoung.
Referenced by v8::internal::JSMap::Initialize().
NewOrderedHashSet()
Handle< OrderedHashSet > v8::internal::Factory::NewOrderedHashSet ()
Definition at line 562 of file factory.cc.
                                                  {
  return OrderedHashSet::Allocate(isolate(), OrderedHashSet::kInitialCapacity,
                                  AllocationType::kYoung)
      .ToHandleChecked();
}
References v8::internal::OrderedHashSet::Allocate(), isolate(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::kInitialCapacity, and v8::internal::kYoung.
Referenced by v8::internal::JSSet::Initialize(), v8::internal::JsonStringifier::InitializeReplacer(), and v8::internal::Heap::KeepDuringJob().
NewPrivateNameSymbol()
DirectHandle< Symbol > v8::internal::Factory::NewPrivateNameSymbol (DirectHandle< String > name)
Definition at line 1252 of file factory.cc.
                                                                            {
  Tagged<Symbol> symbol = NewSymbolInternal();
  DisallowGarbageCollection no_gc;
  symbol->set_is_private_name();
  symbol->set_description(*name);
  return direct_handle(symbol, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::name, NewSymbolInternal(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
NewPrivateSymbol()
Handle< Symbol > v8::internal::Factory::NewPrivateSymbol (AllocationType allocation = AllocationType::kOld)
Definition at line 1244 of file factory.cc.
                                                                  {
  DCHECK(allocation != AllocationType::kYoung);
  Tagged<Symbol> symbol = NewSymbolInternal(allocation);
  DisallowGarbageCollection no_gc;
  symbol->set_is_private(true);
  return handle(symbol, isolate());
}
References v8::internal::DCHECK(), v8::internal::handle(), isolate(), v8::internal::kYoung, NewSymbolInternal(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::Private::New(), and v8::internal::Isolate::SymbolFor().
NewPromiseResolveThenableJobTask()
DirectHandle< PromiseResolveThenableJobTask > v8::internal::Factory::NewPromiseResolveThenableJobTask (DirectHandle< JSPromise > promise_to_resolve, DirectHandle< JSReceiver > thenable, DirectHandle< JSReceiver > then, DirectHandle< Context > context)
Definition at line 1659 of file factory.cc.
                                   {
  DCHECK(IsCallable(*then));
  auto microtask = NewStructInternal<PromiseResolveThenableJobTask>(
      PROMISE_RESOLVE_THENABLE_JOB_TASK_TYPE, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  microtask->set_promise_to_resolve(*promise_to_resolve, SKIP_WRITE_BARRIER);
  microtask->set_thenable(*thenable, SKIP_WRITE_BARRIER);
  microtask->set_then(*then, SKIP_WRITE_BARRIER);
  microtask->set_context(*context, SKIP_WRITE_BARRIER);
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  microtask->set_continuation_preserved_embedder_data(
      isolate()->isolate_data()->continuation_preserved_embedder_data(),
      SKIP_WRITE_BARRIER);
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
  return direct_handle(microtask, isolate());
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::JSPromise::Resolve().
NewProperSubString()
Handle< String > v8::internal::Factory::NewProperSubString (DirectHandle< String > str, uint32_t begin, uint32_t end)
Definition at line 1096 of file factory.cc.
                                                                         {
#if VERIFY_HEAP
  if (v8_flags.verify_heap) str->StringVerify(isolate());
#endif
  DCHECK_LE(begin, str->length());
  DCHECK_LE(end, str->length());
  str = String::Flatten(isolate(), str);
  if (begin >= end) return empty_string();
  uint32_t length = end - begin;
  if (length == 1) {
    return LookupSingleCharacterStringFromCode(str->Get(begin));
  }
  if (length == 2) {
    // Optimization for 2-byte strings often used as keys in a decompression
    // dictionary. Check whether we already have the string in the string
    // table to prevent creation of many unnecessary strings.
    uint16_t c1 = str->Get(begin);
    uint16_t c2 = str->Get(begin + 1);
    return MakeOrFindTwoCharacterString(c1, c2);
  }
  if (!v8_flags.string_slices || length < SlicedString::kMinLength) {
    return NewCopiedSubstring(str, begin, length);
  }
  int offset = begin;
  if (IsSlicedString(*str)) {
    auto slice = Cast<SlicedString>(str);
    str = direct_handle(slice->parent(), isolate());
    offset += slice->offset();
  }
  if (IsThinString(*str)) {
    auto thin = Cast<ThinString>(str);
    str = direct_handle(thin->actual(), isolate());
  }
  DCHECK(IsSeqString(*str) || IsExternalString(*str));
  DirectHandle<Map> map = str->IsOneByteRepresentation()
                              ? sliced_one_byte_string_map()
                              : sliced_two_byte_string_map();
  Tagged<SlicedString> slice =
      Cast<SlicedString>(New(map, AllocationType::kYoung));
  DisallowGarbageCollection no_gc;
  slice->set_raw_hash_field(String::kEmptyHashField);
  slice->set_length(length);
  slice->set_parent(*str);
  slice->set_offset(offset);
  return handle(slice, isolate());
}
References begin, v8::internal::DCHECK(), DCHECK_LE, v8::internal::direct_handle(), end, v8::internal::handle(), v8::internal::InstanceTypeChecker::IsExternalString(), isolate(), v8::internal::InstanceTypeChecker::IsSeqString(), v8::internal::InstanceTypeChecker::IsSlicedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::Name::kEmptyHashField, v8::internal::SlicedString::kMinLength, v8::internal::kYoung, length, v8::internal::FactoryBase< Factory >::LookupSingleCharacterStringFromCode(), v8::internal::FactoryBase< Factory >::MakeOrFindTwoCharacterString(), New(), NewCopiedSubstring(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::requires(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), and v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow().
NewPropertyArray()
DirectHandle< PropertyArray > v8::internal::Factory::NewPropertyArray (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 419 of file factory.cc.
                                           {
  DCHECK_LE(0, length);
  if (length == 0) return empty_property_array();
  Tagged<HeapObject> result = AllocateRawFixedArray(length, allocation);
  DisallowGarbageCollection no_gc;
  result->set_map_after_allocation(isolate(), *property_array_map(),
                                   SKIP_WRITE_BARRIER);
  Tagged<PropertyArray> array = Cast<PropertyArray>(result);
  array->initialize_length(length);
  MemsetTagged(array->data_start(), read_only_roots().undefined_value(),
               length);
  return direct_handle(array, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawFixedArray(), DCHECK_LE, v8::internal::direct_handle(), isolate(), length, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate(), v8::internal::JSObject::AllocateStorageForMap(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::JSObject::MigrateSlowToFast(), and NewJSSharedStruct().
NewPropertyCell()
Handle< PropertyCell > v8::internal::Factory::NewPropertyCell (DirectHandle< Name > name, PropertyDetails details, DirectHandle< Object > value, AllocationType allocation = AllocationType::kOld)
Definition at line 2248 of file factory.cc.
                                                                         {
  DCHECK(IsUniqueName(*name));
  static_assert(PropertyCell::kSize <= kMaxRegularHeapObjectSize);
  Tagged<PropertyCell> cell = Cast<PropertyCell>(AllocateRawWithImmortalMap(
      PropertyCell::kSize, allocation, *global_property_cell_map()));
  DisallowGarbageCollection no_gc;
  cell->set_dependent_code(
      DependentCode::empty_dependent_code(ReadOnlyRoots(isolate())),
      SKIP_WRITE_BARRIER);
  WriteBarrierMode mode = allocation == AllocationType::kYoung
                              ? SKIP_WRITE_BARRIER
                              : UPDATE_WRITE_BARRIER;
  cell->set_name(*name, mode);
  cell->set_value(*value, mode);
  cell->set_property_details_raw(details.AsSmi(), SKIP_WRITE_BARRIER);
  return handle(cell, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::PropertyDetails::AsSmi(), v8::internal::DCHECK(), v8::internal::DependentCode::empty_dependent_code(), v8::internal::handle(), isolate(), v8::internal::IsUniqueName(), v8::internal::kMaxRegularHeapObjectSize, v8::internal::kYoung, mode(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::PropertyCell::InvalidateAndReplaceEntry(), NewJSGlobalObject(), NewProtector(), v8::internal::LookupIterator::PrepareTransitionToDataProperty(), and v8::internal::JSObject::SetNormalizedProperty().
NewPropertyDescriptorObject()
DirectHandle< PropertyDescriptorObject > v8::internal::Factory::NewPropertyDescriptorObject ()
Definition at line 579 of file factory.cc.
                                                                            {
  auto object = NewStructInternal<PropertyDescriptorObject>(
      PROPERTY_DESCRIPTOR_OBJECT_TYPE, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  object->set_flags(0);
  Tagged<Hole> the_hole = read_only_roots().the_hole_value();
  object->set_value(the_hole, SKIP_WRITE_BARRIER);
  object->set_get(the_hole, SKIP_WRITE_BARRIER);
  object->set_set(the_hole, SKIP_WRITE_BARRIER);
  return direct_handle(object, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::PropertyDescriptor::ToPropertyDescriptorObject().
NewProtector()
DirectHandle< PropertyCell > v8::internal::Factory::NewProtector ()
Definition at line 2269 of file factory.cc.
                                                 {
  return NewPropertyCell(
      empty_string(), PropertyDetails::Empty(PropertyCellType::kConstantType),
      direct_handle(Smi::FromInt(Protectors::kProtectorValid), isolate()));
}
References v8::internal::direct_handle(), v8::internal::PropertyDetails::Empty(), v8::internal::Smi::FromInt(), isolate(), v8::internal::kConstantType, v8::internal::Protectors::kProtectorValid, and NewPropertyCell().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
NewPrototypeInfo()
DirectHandle< PrototypeInfo > v8::internal::Factory::NewPrototypeInfo ()
Definition at line 367 of file factory.cc.
                                                      {
  auto result = NewStructInternal<PrototypeInfo>(PROTOTYPE_INFO_TYPE,
                                                 AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  result->set_prototype_users(Smi::zero());
  result->set_registry_slot(PrototypeInfo::UNREGISTERED);
  result->set_bit_field(0);
  result->set_module_namespace(*undefined_value(), SKIP_WRITE_BARRIER);
  for (int i = 0; i < PrototypeInfo::kCachedHandlerCount; i++) {
    result->set_cached_handler(i, Smi::zero(), SKIP_WRITE_BARRIER);
  }
  return direct_handle(result, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::PrototypeInfo::kCachedHandlerCount, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::SKIP_WRITE_BARRIER, v8::internal::PrototypeInfo::UNREGISTERED, and v8::internal::Smi::zero().
Referenced by v8::internal::Map::GetOrCreatePrototypeInfo().
NewScriptContext()
DirectHandle< Context > v8::internal::Factory::NewScriptContext (DirectHandle< NativeContext > outer, DirectHandle< ScopeInfo > scope_info)
Definition at line 1341 of file factory.cc.
                                                                           {
  DCHECK(scope_info->is_script_scope());
  int variadic_part_length = scope_info->ContextLength();
  Tagged<Context> context =
      NewContextInternal(direct_handle(outer->script_context_map(), isolate()),
                         Context::SizeFor(variadic_part_length),
                         variadic_part_length, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  context->set_scope_info(*scope_info);
  context->set_previous(*outer);
  DCHECK(context->IsScriptContext());
  return direct_handle(context, isolate());
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), isolate(), v8::internal::kOld, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Context::SizeFor().
Referenced by v8::internal::Genesis::InstallGlobalThisBinding(), and v8::internal::anonymous_namespace{execution.cc}::NewScriptContext().
NewScriptContextTable()
Handle< ScriptContextTable > v8::internal::Factory::NewScriptContextTable ()
Definition at line 1356 of file factory.cc.
                                                          {
  static constexpr int kInitialCapacity = 0;
  return ScriptContextTable::New(isolate(), kInitialCapacity);
}
References isolate(), and v8::internal::ScriptContextTable::New().
Referenced by v8::internal::Genesis::InitializeGlobal().
NewSharedFunctionInfoForApiFunction()
Handle< SharedFunctionInfo > v8::internal::Factory::NewSharedFunctionInfoForApiFunction (MaybeDirectHandle< String > maybe_name, DirectHandle< FunctionTemplateInfo > function_template_info, FunctionKind kind)
Definition at line 3934 of file factory.cc.
                       {
  return NewSharedFunctionInfo(
      maybe_name, function_template_info, Builtin::kNoBuiltinId,
      function_template_info->length(), kDontAdapt, kind);
}
References v8::internal::kDontAdapt, v8::internal::kNoBuiltinId, and v8::internal::FactoryBase< Factory >::NewSharedFunctionInfo().
Referenced by v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo().
NewSharedFunctionInfoForBuiltin()
Handle< SharedFunctionInfo > v8::internal::Factory::NewSharedFunctionInfoForBuiltin (MaybeDirectHandle< String > name, Builtin builtin, int len, AdaptArguments adapt, FunctionKind kind = FunctionKind::kNormalFunction)
Definition at line 3943 of file factory.cc.
                                             {
  return NewSharedFunctionInfo(maybe_name, MaybeDirectHandle<HeapObject>(),
                               builtin, len, adapt, kind);
}
References v8::internal::FactoryBase< Factory >::NewSharedFunctionInfo().
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-intl.cc}::CreateBoundFunction(), v8::internal::wasm::CreateFunctionForCompileTimeImport(), v8::internal::anonymous_namespace{setup-heap-internal.cc}::CreateSharedFunctionInfo(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedFunctionInfoForBuiltin(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateSharedObjectConstructor(), v8::debug::GetBuiltin(), v8::internal::Genesis::InitializeConsole(), v8::internal::anonymous_namespace{builtins-console.cc}::InstallContextFunction(), v8::internal::wasm::JSPrototypesSetup::MakeConstructor(), v8::internal::FeedbackVector::NewForTesting(), NewFunctionForTesting(), and v8::internal::WasmJs::PrepareForSnapshot().
NewSlowJSObjectFromMap() [1/2]
Handle< JSObject > v8::internal::Factory::NewSlowJSObjectFromMap (DirectHandle< Map > map)
Definition at line 3206 of file factory.cc.
                                                                      {
  return NewSlowJSObjectFromMap(map, PropertyDictionary::kInitialCapacity);
}
References v8::internal::NameDictionary::kInitialCapacity, and NewSlowJSObjectFromMap().
NewSlowJSObjectFromMap() [2/2]
Handle< JSObject > v8::internal::Factory::NewSlowJSObjectFromMap (DirectHandle< Map > map, int number_of_slow_properties, AllocationType allocation = AllocationType::kYoung, DirectHandle< AllocationSite > allocation_site = DirectHandle<AllocationSite>::null(), NewJSObjectType new_js_object_type = NewJSObjectType::kNoAPIWrapper)
Definition at line 3189 of file factory.cc.
                                        {
  DCHECK(map->is_dictionary_map());
  DirectHandle<HeapObject> object_properties;
  if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
    object_properties = NewSwissNameDictionary(capacity, allocation);
  } else {
    object_properties = NameDictionary::New(isolate(), capacity);
  }
  Handle<JSObject> js_object =
      NewJSObjectFromMap(map, allocation, allocation_site, new_js_object_type);
  js_object->set_raw_properties_or_hash(*object_properties, kRelaxedStore);
  return js_object;
}
References v8::internal::DCHECK(), isolate(), v8::kRelaxedStore, v8::internal::NameDictionary::New(), NewJSObjectFromMap(), v8::internal::FactoryBase< Factory >::NewSwissNameDictionary(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject(), v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties(), NewFastOrSlowJSObjectFromMap(), NewSlowJSObjectFromMap(), and NewSlowJSObjectWithNullProto().
NewSlowJSObjectWithNullProto()
Handle< JSObject > v8::internal::Factory::NewSlowJSObjectWithNullProto ()
Definition at line 3031 of file factory.cc.
                                                       {
  Handle<JSObject> result =
      NewSlowJSObjectFromMap(isolate()->slow_object_with_null_prototype_map());
  return result;
}
References isolate(), NewSlowJSObjectFromMap(), and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::DebugWasmScopeIterator::GetObject(), v8::internal::ScopeIterator::ScopeObject(), v8::internal::ScopeIterator::WithContextExtension(), and v8::internal::DebugEvaluate::WithTopmostArguments().
NewSlowJSObjectWithPropertiesAndElements()
DirectHandle< JSObject > v8::internal::Factory::NewSlowJSObjectWithPropertiesAndElements (DirectHandle< JSPrototype > prototype, DirectHandle< HeapObject > properties, DirectHandle< FixedArrayBase > elements)
Definition at line 3210 of file factory.cc.
                                           {
  DCHECK(IsPropertyDictionary(*properties));
  DirectHandle<Map> object_map =
      isolate()->slow_object_with_object_prototype_map();
  if (object_map->prototype() != *prototype) {
    object_map = Map::TransitionRootMapToPrototypeForNewObject(
        isolate(), object_map, prototype);
  }
  DCHECK(object_map->is_dictionary_map());
  DirectHandle<JSObject> object =
      NewJSObjectFromMap(object_map, AllocationType::kYoung);
  object->set_raw_properties_or_hash(*properties);
  if (*elements != read_only_roots().empty_fixed_array()) {
    DCHECK(IsNumberDictionary(*elements));
    object_map = JSObject::GetElementsTransitionMap(isolate(), object,
                                                    DICTIONARY_ELEMENTS);
    JSObject::MigrateToMap(isolate(), object, object_map);
    object->set_elements(*elements);
  }
  return object;
}
References v8::internal::DCHECK(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::JSObject::GetElementsTransitionMap(), isolate(), v8::internal::InstanceTypeChecker::IsPropertyDictionary(), v8::internal::kYoung, v8::internal::JSObject::MigrateToMap(), NewJSObjectFromMap(), v8::internal::prototype, read_only_roots(), and v8::internal::Map::TransitionRootMapToPrototypeForNewObject().
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), and v8::Object::New().
NewSmallOrderedHashMap()
Handle< SmallOrderedHashMap > v8::internal::Factory::NewSmallOrderedHashMap (int capacity = kSmallOrderedHashMapMinCapacity, AllocationType allocation = AllocationType::kYoung)
Definition at line 547 of file factory.cc.
                                             {
  return AllocateSmallOrderedHashTable<SmallOrderedHashMap>(
      small_ordered_hash_map_map(), capacity, allocation);
}
Referenced by v8::internal::SmallOrderedHashTable< Derived >::Allocate().
NewSmallOrderedHashSet()
Handle< SmallOrderedHashSet > v8::internal::Factory::NewSmallOrderedHashSet (int capacity = kSmallOrderedHashSetMinCapacity, AllocationType allocation = AllocationType::kYoung)
Definition at line 541 of file factory.cc.
                                             {
  return AllocateSmallOrderedHashTable<SmallOrderedHashSet>(
      small_ordered_hash_set_map(), capacity, allocation);
}
Referenced by v8::internal::SmallOrderedHashTable< Derived >::Allocate().
NewSmallOrderedNameDictionary()
Handle< SmallOrderedNameDictionary > v8::internal::Factory::NewSmallOrderedNameDictionary (int capacity = kSmallOrderedHashMapMinCapacity, AllocationType allocation = AllocationType::kYoung)
Definition at line 553 of file factory.cc.
                                             {
  Handle<SmallOrderedNameDictionary> dict =
      AllocateSmallOrderedHashTable<SmallOrderedNameDictionary>(
          small_ordered_name_dictionary_map(), capacity, allocation);
  dict->SetHash(PropertyArray::kNoHashSentinel);
  return dict;
}
References v8::internal::PropertyArray::kNoHashSentinel.
Referenced by v8::internal::SmallOrderedHashTable< Derived >::Allocate().
NewSourceTextModule()
DirectHandle< SourceTextModule > v8::internal::Factory::NewSourceTextModule (DirectHandle< SharedFunctionInfo > code)
Definition at line 3447 of file factory.cc.
                                          {
  DirectHandle<SourceTextModuleInfo> module_info(
      sfi->scope_info()->ModuleDescriptorInfo(), isolate());
  DirectHandle<ObjectHashTable> exports =
      ObjectHashTable::New(isolate(), module_info->RegularExportCount());
  DirectHandle<FixedArray> regular_exports =
      NewFixedArray(module_info->RegularExportCount());
  DirectHandle<FixedArray> regular_imports =
      NewFixedArray(module_info->regular_imports()->length());
  int requested_modules_length = module_info->module_requests()->length();
  DirectHandle<FixedArray> requested_modules =
      requested_modules_length > 0 ? NewFixedArray(requested_modules_length)
                                   : empty_fixed_array();
  ReadOnlyRoots roots(isolate());
  Tagged<SourceTextModule> module = Cast<SourceTextModule>(
      New(source_text_module_map(), AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  module->set_code(*sfi);
  module->set_exports(*exports);
  module->set_regular_exports(*regular_exports);
  module->set_regular_imports(*regular_imports);
  module->set_hash(isolate()->GenerateIdentityHash(Smi::kMaxValue));
  module->set_module_namespace(roots.undefined_value(), SKIP_WRITE_BARRIER);
  module->set_requested_modules(*requested_modules);
  module->set_status(Module::kUnlinked);
  module->set_exception(roots.the_hole_value(), SKIP_WRITE_BARRIER);
  module->set_top_level_capability(roots.undefined_value(), SKIP_WRITE_BARRIER);
  module->set_import_meta(roots.the_hole_value(), kReleaseStore,
                          SKIP_WRITE_BARRIER);
  module->set_dfs_index(-1);
  module->set_dfs_ancestor_index(-1);
  module->set_flags(0);
  module->set_has_toplevel_await(IsModuleWithTopLevelAwait(sfi->kind()));
  module->set_async_evaluation_ordinal(SourceTextModule::kNotAsyncEvaluated);
  module->set_cycle_root(roots.the_hole_value(), SKIP_WRITE_BARRIER);
  module->set_async_parent_modules(roots.empty_array_list());
  module->set_pending_async_dependencies(0);
  return direct_handle(module, isolate());
}
References v8::internal::direct_handle(), v8::internal::IsModuleWithTopLevelAwait(), isolate(), v8::internal::Smi::kMaxValue, v8::internal::SourceTextModule::kNotAsyncEvaluated, v8::internal::kOld, v8::kReleaseStore, v8::internal::Module::kUnlinked, New(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::FactoryBase< Factory >::NewFixedArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::ScriptCompiler::CompileModule().
NewStackFrameInfo()
DirectHandle< StackFrameInfo > v8::internal::Factory::NewStackFrameInfo (DirectHandle< UnionOf< SharedFunctionInfo, Script >> shared_or_script, int bytecode_offset_or_source_position, DirectHandle< String > function_name, bool is_constructor)
Definition at line 4060 of file factory.cc.
                         {
  DCHECK_GE(bytecode_offset_or_source_position, 0);
  Tagged<StackFrameInfo> info = NewStructInternal<StackFrameInfo>(
      STACK_FRAME_INFO_TYPE, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  info->set_flags(0);
  info->set_shared_or_script(*shared_or_script, SKIP_WRITE_BARRIER);
  info->set_bytecode_offset_or_source_position(
      bytecode_offset_or_source_position);
  info->set_function_name(*function_name, SKIP_WRITE_BARRIER);
  info->set_is_constructor(is_constructor);
  return direct_handle(info, isolate());
}
References DCHECK_GE, v8::internal::direct_handle(), v8::internal::is_constructor, isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos().
NewStackTraceInfo()
Handle< StackTraceInfo > v8::internal::Factory::NewStackTraceInfo (DirectHandle< FixedArray > frames)
Definition at line 4077 of file factory.cc.
                                     {
  Tagged<StackTraceInfo> info = NewStructInternal<StackTraceInfo>(
      STACK_TRACE_INFO_TYPE, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  info->set_id(isolate()->heap()->NextStackTraceId());
  info->set_frames(*frames, SKIP_WRITE_BARRIER);
  return handle(info, isolate());
}
References v8::internal::handle(), heap(), isolate(), v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Isolate::CaptureDetailedStackTrace(), and v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos().
NewStoreHandler()
Handle< StoreHandler > v8::internal::Factory::NewStoreHandler (int data_count)
Definition at line 4170 of file factory.cc.
                                                            {
  DirectHandle<Map> map;
  switch (data_count) {
    case 0:
      map = store_handler0_map();
      break;
    case 1:
      map = store_handler1_map();
      break;
    case 2:
      map = store_handler2_map();
      break;
    case 3:
      map = store_handler3_map();
      break;
    default:
      UNREACHABLE();
  }
  return handle(Cast<StoreHandler>(New(map, AllocationType::kOld)), isolate());
}
References v8::internal::handle(), isolate(), v8::internal::kOld, New(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::StoreHandler::StoreElementTransition(), v8::internal::StoreHandler::StoreThroughPrototype(), and v8::internal::StoreHandler::StoreTransition().
NewStringFromStaticChars()
template<size_t N>
Handle< String > v8::internal::Factory::NewStringFromStaticChars (const char(&) str[N], AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 78 of file factory-inl.h.
                                                                            {
  DCHECK_EQ(N, strlen(str) + 1);
  return NewStringFromOneByte(base::StaticOneByteVector(str), allocation)
      .ToHandleChecked();
}
References DCHECK_EQ, v8::internal::N, v8::internal::FactoryBase< Factory >::NewStringFromOneByte(), and v8::base::StaticOneByteVector().
Referenced by v8::internal::AddWasmModuleObjectInternalProperties(), v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::Context::ErrorMessageForCodeGenerationFromStrings(), v8::internal::Context::ErrorMessageForWasmCodeGeneration(), v8::internal::Runtime::GetInternalProperties(), v8::internal::JSNumberFormat::New(), v8::internal::Intl::Normalize(), v8::internal::BigInt::NoSideEffectsToString(), v8::internal::NumberFormatRange(), v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern(), v8::internal::Intl::SupportedValuesOf(), and v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue().
NewStringFromTwoByte() [1/3]
MaybeHandle< String > v8::internal::Factory::NewStringFromTwoByte (base::Vector< const base::uc16 > str, AllocationType allocation = AllocationType::kYoung)
Definition at line 912 of file factory.cc.
                                                                  {
  return NewStringFromTwoByte(string.begin(), string.length(), allocation);
}
References begin, and length.
Referenced by v8::internal::RegExp::Compile(), v8::anonymous_namespace{api.cc}::NewString(), NewStringFromTwoByte(), v8::internal::JsonStringifier::Stringify(), and v8::internal::Intl::ToString().
NewStringFromTwoByte() [2/3]
MaybeHandle< String > v8::internal::Factory::NewStringFromTwoByte (const base::uc16 * string, int length, AllocationType allocation) [private]
Definition at line 889 of file factory.cc.
                                                                             {
  DCHECK_NE(allocation, AllocationType::kReadOnly);
  if (length == 0) return empty_string();
  if (String::IsOneByte(string, length)) {
    if (length == 1) return LookupSingleCharacterStringFromCode(string[0]);
    Handle<SeqOneByteString> result;
    ASSIGN_RETURN_ON_EXCEPTION(isolate(), result,
                               NewRawOneByteString(length, allocation));
    DisallowGarbageCollection no_gc;
    CopyChars(result->GetChars(no_gc), string, length);
    return result;
  } else {
    Handle<SeqTwoByteString> result;
    ASSIGN_RETURN_ON_EXCEPTION(isolate(), result,
                               NewRawTwoByteString(length, allocation));
    DisallowGarbageCollection no_gc;
    CopyChars(result->GetChars(no_gc), string, length);
    return result;
  }
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::CopyChars(), DCHECK_NE, isolate(), v8::internal::String::IsOneByte(), v8::internal::kReadOnly, length, v8::internal::FactoryBase< Factory >::LookupSingleCharacterStringFromCode(), v8::internal::FactoryBase< Factory >::NewRawOneByteString(), v8::internal::FactoryBase< Factory >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
NewStringFromTwoByte() [3/3]
MaybeDirectHandle< String > v8::internal::Factory::NewStringFromTwoByte (const ZoneVector< base::uc16 > * str, AllocationType allocation = AllocationType::kYoung)
Definition at line 917 of file factory.cc.
                                                                   {
  return NewStringFromTwoByte(string->data(), static_cast<int>(string->size()),
                              allocation);
}
References NewStringFromTwoByte(), and v8::internal::string.
NewStringFromUtf8() [1/2]
MaybeHandle< String > v8::internal::Factory::NewStringFromUtf8 (base::Vector< const char > str, AllocationType allocation = AllocationType::kYoung)
Definition at line 759 of file factory.cc.
                                                                          {
  return NewStringFromUtf8(base::Vector<const uint8_t>::cast(string),
                           unibrow::Utf8Variant::kLossyUtf8, allocation);
}
References unibrow::kLossyUtf8.
Referenced by v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString(), v8::internal::Genesis::CompileExtension(), v8::internal::anonymous_namespace{intl-objects.cc}::CreateArrayFromList(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::SharedFunctionInfo::DebugName(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::debug::GetDateDescription(), v8::anonymous_namespace{api.cc}::NewString(), v8::internal::ValueDeserializer::ReadUtf8String(), v8::internal::wasm::ErrorThrower::Reify(), v8::internal::RUNTIME_FUNCTION(), v8::Date::ToISOString(), v8::internal::StringStream::ToString(), v8::Date::ToUTCString(), and wasm::VecToString().
NewStringFromUtf8() [2/2]
MaybeHandle< String > v8::internal::Factory::NewStringFromUtf8 (base::Vector< const uint8_t > str, unibrow::Utf8Variant utf8_variant, AllocationType allocation = AllocationType::kYoung)
Definition at line 746 of file factory.cc.
                               {
  if (string.size() > kMaxInt) {
    // The Utf8Decode can't handle longer inputs, and we couldn't create
    // strings from them anyway.
    THROW_NEW_ERROR(isolate(), NewInvalidStringLengthError());
  }
  auto peek_bytes = [&]() -> base::Vector<const uint8_t> { return string; };
  return NewStringFromUtf8Variant(isolate(), peek_bytes, utf8_variant,
                                  allocation);
}
References isolate(), v8::internal::kMaxInt, NewInvalidStringLengthError(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromUtf8Variant(), size(), v8::internal::string, and THROW_NEW_ERROR.
NewStringFromUtf8SubString()
MaybeHandle< String > v8::internal::Factory::NewStringFromUtf8SubString (Handle< SeqOneByteString > str, int begin, int end, AllocationType allocation = AllocationType::kYoung)
Definition at line 834 of file factory.cc.
                               {
  base::Vector<const uint8_t> utf8_data;
  {
    DisallowGarbageCollection no_gc;
    utf8_data =
        base::Vector<const uint8_t>(str->GetChars(no_gc) + begin, length);
  }
  Utf8Decoder decoder(utf8_data);
  if (length == 1) {
    uint16_t t;
    // Decode even in the case of length 1 since it can be a bad character.
    decoder.Decode(&t, utf8_data);
    return LookupSingleCharacterStringFromCode(t);
  }
  if (decoder.is_ascii()) {
    // If the string is ASCII, we can just make a substring.
    // TODO(v8): the allocation flag is ignored in this case.
    return NewSubString(str, begin, begin + length);
  }
  DCHECK_GT(decoder.utf16_length(), 0);
  if (decoder.is_one_byte()) {
    // Allocate string.
    Handle<SeqOneByteString> result;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate(), result,
        NewRawOneByteString(decoder.utf16_length(), allocation));
    DisallowGarbageCollection no_gc;
    // Update pointer references, since the original string may have moved after
    // allocation.
    utf8_data =
        base::Vector<const uint8_t>(str->GetChars(no_gc) + begin, length);
    decoder.Decode(result->GetChars(no_gc), utf8_data);
    return result;
  }
  // Allocate string.
  Handle<SeqTwoByteString> result;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate(), result,
      NewRawTwoByteString(decoder.utf16_length(), allocation));
  DisallowGarbageCollection no_gc;
  // Update pointer references, since the original string may have moved after
  // allocation.
  utf8_data = base::Vector<const uint8_t>(str->GetChars(no_gc) + begin, length);
  decoder.Decode(result->GetChars(no_gc), utf8_data);
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, begin, DCHECK_GT, v8::internal::Utf8DecoderBase< Decoder >::Decode(), v8::internal::Utf8DecoderBase< Decoder >::is_ascii(), v8::internal::Utf8DecoderBase< Decoder >::is_one_byte(), isolate(), length, v8::internal::FactoryBase< Factory >::LookupSingleCharacterStringFromCode(), v8::internal::FactoryBase< Factory >::NewRawOneByteString(), v8::internal::FactoryBase< Factory >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::Utf8DecoderBase< Decoder >::utf16_length().
NewSuppressedErrorAtDisposal()
DirectHandle< JSObject > v8::internal::Factory::NewSuppressedErrorAtDisposal (Isolate * isolate, DirectHandle< Object > error, DirectHandle< Object > suppressed_error)
Definition at line 2849 of file factory.cc.
                                           {
  DirectHandle<JSObject> err =
      NewSuppressedError(MessageTemplate::kSuppressedErrorDuringDisposal);
  JSObject::SetOwnPropertyIgnoreAttributes(
      err, isolate->factory()->error_string(), error, DONT_ENUM)
      .Assert();
  JSObject::SetOwnPropertyIgnoreAttributes(
      err, isolate->factory()->suppressed_string(), suppressed_error, DONT_ENUM)
      .Assert();
  return err;
}
References v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), isolate(), and v8::internal::JSObject::SetOwnPropertyIgnoreAttributes().
Referenced by v8::internal::JSDisposableStackBase::HandleErrorInDisposal().
NewSurrogatePairString()
DirectHandle< String > v8::internal::Factory::NewSurrogatePairString (uint16_t lead, uint16_t trail)
Definition at line 1049 of file factory.cc.
                                                                     {
  DCHECK_GE(lead, 0xD800);
  DCHECK_LE(lead, 0xDBFF);
  DCHECK_GE(trail, 0xDC00);
  DCHECK_LE(trail, 0xDFFF);
  DirectHandle<SeqTwoByteString> str =
      isolate()->factory()->NewRawTwoByteString(2).ToHandleChecked();
  DisallowGarbageCollection no_gc;
  base::uc16* dest = str->GetChars(no_gc);
  dest[0] = lead;
  dest[1] = trail;
  return str;
}
References DCHECK_GE, DCHECK_LE, v8::internal::Isolate::factory(), isolate(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
NewSymbol()
Handle< Symbol > v8::internal::Factory::NewSymbol (AllocationType allocation = AllocationType::kOld)
Definition at line 1240 of file factory.cc.
                                                           {
  return handle(NewSymbolInternal(allocation), isolate());
}
References v8::internal::handle(), isolate(), and NewSymbolInternal().
Referenced by v8::Symbol::New(), and v8::internal::Isolate::SymbolFor().
NewSymbolInternal()
Tagged< Symbol > v8::internal::Factory::NewSymbolInternal (AllocationType allocation = AllocationType::kOld) [private]
Definition at line 1214 of file factory.cc.
                                                                   {
  DCHECK(allocation != AllocationType::kYoung);
  // Statically ensure that it is safe to allocate symbols in paged spaces.
  static_assert(sizeof(Symbol) <= kMaxRegularHeapObjectSize);
  Tagged<Symbol> symbol = Cast<Symbol>(AllocateRawWithImmortalMap(
      sizeof(Symbol), allocation, read_only_roots().symbol_map()));
  DisallowGarbageCollection no_gc;
  // Generate a random hash value.
  int hash = isolate()->GenerateIdentityHash(Name::HashBits::kMax);
  symbol->set_raw_hash_field(
      Name::CreateHashFieldValue(hash, Name::HashFieldType::kHash));
  if (isolate()->read_only_heap()->roots_init_complete()) {
    symbol->set_description(read_only_roots().undefined_value(),
                            SKIP_WRITE_BARRIER);
  } else {
    // Can't use setter during bootstrapping as its typecheck tries to access
    // the roots table before it is initialized.
    symbol->description_.store(&*symbol, read_only_roots().undefined_value(),
                               SKIP_WRITE_BARRIER);
  }
  symbol->set_flags(0);
  DCHECK(!symbol->is_private());
  return symbol;
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::Name::CreateHashFieldValue(), v8::internal::DCHECK(), v8::internal::Isolate::GenerateIdentityHash(), isolate(), v8::internal::Name::kHash, v8::base::BitField< T, shift, size, U >::kMax, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kYoung, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, read_only_roots(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by NewPrivateNameSymbol(), NewPrivateSymbol(), and NewSymbol().
NewSyntheticModule()
Handle< SyntheticModule > v8::internal::Factory::NewSyntheticModule (DirectHandle< String > module_name, DirectHandle< FixedArray > export_names, v8::Module::SyntheticModuleEvaluationSteps evaluation_steps)
Definition at line 3489 of file factory.cc.
                                                             {
  ReadOnlyRoots roots(isolate());
  DirectHandle<ObjectHashTable> exports =
      ObjectHashTable::New(isolate(), static_cast<int>(export_names->length()));
  DirectHandle<Foreign> evaluation_steps_foreign =
      NewForeign<kSyntheticModuleTag>(
          reinterpret_cast<Address>(evaluation_steps));
  Tagged<SyntheticModule> module =
      Cast<SyntheticModule>(New(synthetic_module_map(), AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  module->set_hash(isolate()->GenerateIdentityHash(Smi::kMaxValue));
  module->set_module_namespace(roots.undefined_value(), SKIP_WRITE_BARRIER);
  module->set_status(Module::kUnlinked);
  module->set_exception(roots.the_hole_value(), SKIP_WRITE_BARRIER);
  module->set_top_level_capability(roots.undefined_value(), SKIP_WRITE_BARRIER);
  module->set_name(*module_name);
  module->set_export_names(*export_names);
  module->set_exports(*exports);
  module->set_evaluation_steps(*evaluation_steps_foreign);
  return handle(module, isolate());
}
References v8::internal::handle(), isolate(), v8::internal::Smi::kMaxValue, v8::internal::kOld, v8::internal::Module::kUnlinked, New(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::Module::CreateSyntheticModule().
NewTransitionArray()
DirectHandle< TransitionArray > v8::internal::Factory::NewTransitionArray (int number_of_transitions, int slack = 0)
Definition at line 2275 of file factory.cc.
                                          {
  int capacity = TransitionArray::LengthFor(number_of_transitions + slack);
  DirectHandle<TransitionArray> array = Cast<TransitionArray>(
      NewWeakFixedArrayWithMap(read_only_roots().transition_array_map(),
                               capacity, AllocationType::kOld));
  // Transition arrays are AllocationType::kOld. When black allocation is on we
  // have to add the transition array to the list of
  // encountered_transition_arrays.
  Heap* heap = isolate()->heap();
  if (heap->incremental_marking()->black_allocation()) {
    heap->mark_compact_collector()->AddTransitionArray(*array);
  }
  array->WeakFixedArray::set(TransitionArray::kPrototypeTransitionsIndex,
                             Smi::zero());
  array->WeakFixedArray::set(TransitionArray::kSideStepTransitionsIndex,
                             Smi::zero());
  array->WeakFixedArray::set(TransitionArray::kTransitionLengthIndex,
                             Smi::FromInt(number_of_transitions));
  return array;
}
References v8::internal::Smi::FromInt(), v8::internal::Isolate::heap(), isolate(), v8::internal::kOld, v8::internal::TransitionArray::kPrototypeTransitionsIndex, v8::internal::TransitionArray::kSideStepTransitionsIndex, v8::internal::TransitionArray::kTransitionLengthIndex, v8::internal::TransitionArray::LengthFor(), v8::internal::FactoryBase< Factory >::NewWeakFixedArrayWithMap(), read_only_roots(), and v8::internal::Smi::zero().
Referenced by v8::internal::TransitionsAccessor::EnsureHasFullTransitionArray(), and v8::internal::TransitionsAccessor::InsertHelper().
NewTrustedForeign()
Handle< TrustedForeign > v8::internal::Factory::NewTrustedForeign (Address addr, bool shared)
Definition at line 4751 of file factory.cc.
                                                                           {
  // Statically ensure that it is safe to allocate foreigns in paged spaces.
  static_assert(TrustedForeign::kSize <= kMaxRegularHeapObjectSize);
  Tagged<Map> map = *trusted_foreign_map();
  Tagged<TrustedForeign> foreign =
      Cast<TrustedForeign>(AllocateRawWithImmortalMap(
          map->instance_size(),
          shared ? AllocationType::kSharedTrusted : AllocationType::kTrusted,
          map));
  DisallowGarbageCollection no_gc;
  foreign->set_foreign_address(addr);
  return handle(foreign, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWithImmortalMap(), v8::internal::handle(), isolate(), v8::internal::kMaxRegularHeapObjectSize, v8::internal::kSharedTrusted, v8::internal::kTrusted, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::TrustedManaged< CppType >::From().
NewTuple2()
DirectHandle< Tuple2 > v8::internal::Factory::NewTuple2 (DirectHandle< Object > value1, DirectHandle< Object > value2, AllocationType allocation)
Definition at line 402 of file factory.cc.
                                                                   {
  auto result = NewStructInternal<Tuple2>(TUPLE2_TYPE, allocation);
  DisallowGarbageCollection no_gc;
  result->set_value1(*value1);
  result->set_value2(*value2);
  return direct_handle(result, isolate());
}
References v8::internal::direct_handle(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by v8::internal::Isolate::LocalsBlockListCacheSet(), v8::internal::WasmInterpreterObject::New(), v8::internal::WasmTableObject::SetFunctionTablePlaceholder(), and v8::internal::JSFunction::SetPrototype().
NewTuple2Uninitialized()
DirectHandle< Tuple2 > v8::internal::Factory::NewTuple2Uninitialized (AllocationType allocation)
Definition at line 396 of file factory.cc.
                               {
  auto result = NewStructInternal<Tuple2>(TUPLE2_TYPE, allocation);
  return direct_handle(result, isolate());
}
References v8::internal::direct_handle(), isolate(), and v8::base::internal::result.
NewUninitializedJSGlobalProxy()
Handle< JSGlobalProxy > v8::internal::Factory::NewUninitializedJSGlobalProxy (int size)
Definition at line 3832 of file factory.cc.
                                                                     {
  // Create an empty shell of a JSGlobalProxy that needs to be reinitialized
  // via ReinitializeJSGlobalProxy later.
  DirectHandle<Map> map = NewContextlessMap(JS_GLOBAL_PROXY_TYPE, size);
  // Maintain invariant expected from any JSGlobalProxy.
  {
    DisallowGarbageCollection no_gc;
    Tagged<Map> raw = *map;
    raw->set_is_access_check_needed(true);
    raw->set_may_have_interesting_properties(true);
    LOG(isolate(), MapDetails(raw));
  }
  Handle<JSGlobalProxy> proxy = Cast<JSGlobalProxy>(NewJSObjectFromMap(
      map, AllocationType::kOld, DirectHandle<AllocationSite>::null(),
      NewJSObjectType::kAPIWrapper));
  // Create identity hash early in case there is any JS collection containing
  // a global proxy key and needs to be rehashed after deserialization.
  proxy->GetOrCreateIdentityHash(isolate());
  return proxy;
}
References isolate(), v8::internal::kAPIWrapper, v8::internal::kOld, LOG, NewContextlessMap(), NewJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
Referenced by v8::internal::Genesis::Genesis().
NewUninitializedWeakArrayList()
Handle< WeakArrayList > v8::internal::Factory::NewUninitializedWeakArrayList (int capacity, AllocationType allocation = AllocationType::kYoung) [private]
Definition at line 2671 of file factory.cc.
                                             {
  DCHECK_LE(0, capacity);
  if (capacity == 0) return empty_weak_array_list();
  Tagged<HeapObject> heap_object =
      AllocateRawWeakArrayList(capacity, allocation);
  DisallowGarbageCollection no_gc;
  heap_object->set_map_after_allocation(isolate(), *weak_array_list_map(),
                                        SKIP_WRITE_BARRIER);
  Tagged<WeakArrayList> result = Cast<WeakArrayList>(heap_object);
  result->set_length(0);
  result->set_capacity(capacity);
  return handle(result, isolate());
}
References v8::internal::FactoryBase< Factory >::AllocateRawWeakArrayList(), DCHECK_LE, v8::internal::handle(), isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by CompactWeakArrayList(), CopyWeakArrayListAndGrow(), and NewWeakArrayList().
NewURIError()
DirectHandle< Object > v8::internal::Factory::NewURIError () [inline]
Definition at line 131 of file factory-inl.h.
                                          {
  return NewError(isolate()->uri_error_function(),
                  MessageTemplate::kURIMalformed);
}
References isolate(), and NewError().
NewWeakArrayList()
DirectHandle< WeakArrayList > v8::internal::Factory::NewWeakArrayList (int capacity, AllocationType allocation = AllocationType::kYoung)
Definition at line 2687 of file factory.cc.
                                             {
  DirectHandle<WeakArrayList> result =
      NewUninitializedWeakArrayList(capacity, allocation);
  MemsetTagged(ObjectSlot(result->data_start()),
               read_only_roots().undefined_value(), capacity);
  return result;
}
References v8::internal::MemsetTagged(), NewUninitializedWeakArrayList(), read_only_roots(), and v8::base::internal::result.
Referenced by v8::internal::PrototypeInfo::AddDerivedMap(), and v8::internal::PrototypeInfo::SetObjectCreateMap().
NewWithContext()
Handle< Context > v8::internal::Factory::NewWithContext (DirectHandle< Context > previous, DirectHandle< ScopeInfo > scope_info, DirectHandle< JSReceiver > extension)
Definition at line 1456 of file factory.cc.
                                                                            {
  DCHECK_EQ(scope_info->scope_type(), WITH_SCOPE);
  // TODO(ishell): Take the details from WithContext class.
  int variadic_part_length = Context::MIN_CONTEXT_EXTENDED_SLOTS;
  Tagged<Context> context = NewContextInternal(
      isolate()->with_context_map(), Context::SizeFor(variadic_part_length),
      variadic_part_length, AllocationType::kYoung);
  DisallowGarbageCollection no_gc;
  DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG(isolate(), context);
  context->set_scope_info(*scope_info, SKIP_WRITE_BARRIER);
  context->set_previous(*previous, SKIP_WRITE_BARRIER);
  context->set_extension(*extension, SKIP_WRITE_BARRIER);
  return handle(context, isolate());
}
References DCHECK_EQ, DCHECK_NEWLY_ALLOCATED_OBJECT_IS_YOUNG, v8::internal::handle(), isolate(), v8::internal::kYoung, v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, NewContextInternal(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Context::SizeFor(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::WITH_SCOPE.
Referenced by v8::ScriptCompiler::CompileFunction(), and v8::internal::DebugEvaluate::Local().
ObjectLiteralMapFromCache()
Handle< Map > v8::internal::Factory::ObjectLiteralMapFromCache (DirectHandle< NativeContext > native_context, int number_of_properties)
Definition at line 4112 of file factory.cc.
                                                                   {
  // Use initial slow object proto map for too many properties.
  if (number_of_properties >= JSObject::kMapCacheSize) {
    return handle(context->slow_object_with_object_prototype_map(), isolate());
  }
  // TODO(chromium:1503456): remove once fixed.
  CHECK_LE(0, number_of_properties);
  DirectHandle<WeakFixedArray> cache(Cast<WeakFixedArray>(context->map_cache()),
                                     isolate());
  // Check to see whether there is a matching element in the cache.
  Tagged<MaybeObject> result = cache->get(number_of_properties);
  Tagged<HeapObject> heap_object;
  if (result.GetHeapObjectIfWeak(&heap_object)) {
    Tagged<Map> map = Cast<Map>(heap_object);
    DCHECK(!map->is_dictionary_map());
    return handle(map, isolate());
  }
  // Create a new map and add it to the cache.
  Handle<Map> map = Map::Create(isolate(), number_of_properties);
  DCHECK(!map->is_dictionary_map());
  cache->set(number_of_properties, MakeWeak(*map));
  return map;
}
References CHECK_LE, v8::internal::Map::Create(), v8::internal::DCHECK(), v8::internal::handle(), isolate(), v8::internal::JSObject::kMapCacheSize, v8::internal::MakeWeak(), and v8::base::internal::result.
Referenced by v8::internal::CloneObjectSlowPath(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateLiteralObjectMapFromCache(), v8::internal::anonymous_namespace{runtime-literals.cc}::CreateObjectLiteral(), v8::internal::JSDataObjectBuilder::InitializeMapFromZero(), and v8::internal::DictionaryTemplateInfo::NewInstance().
ProcessNewScript()
void v8::internal::Factory::ProcessNewScript (DirectHandle< Script > shared, ScriptEventType script_event_type) [private]
Definition at line 1574 of file factory.cc.
                                                                  {
  int script_id = script->id();
  if (script_id != Script::kTemporaryScriptId) {
    DirectHandle<WeakArrayList> scripts = script_list();
    scripts = WeakArrayList::Append(isolate(), scripts,
                                    MaybeObjectDirectHandle::Weak(script),
                                    AllocationType::kOld);
    isolate()->heap()->set_script_list(*scripts);
  }
  if (IsString(script->source()) && isolate()->NeedsSourcePositions()) {
    Script::InitLineEnds(isolate(), script);
  }
  LOG(isolate(), ScriptEvent(script_event_type, script_id));
}
References v8::internal::WeakArrayList::Append(), v8::internal::Isolate::heap(), v8::internal::Script::InitLineEnds(), isolate(), v8::internal::kOld, v8::internal::Script::kTemporaryScriptId, LOG, v8::internal::script, and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by CloneScript().
read_only_roots()
ReadOnlyRoots v8::internal::Factory::read_only_roots () const [inline]
Definition at line 136 of file factory-inl.h.
                                             {
  return ReadOnlyRoots(isolate());
}
References isolate().
Referenced by CompactWeakArrayList(), CopyArrayAndGrow(), CopyWeakArrayListAndGrow(), v8::internal::Heap::CreateReadOnlyObjects(), NewAtomRegExpData(), NewBuiltinContext(), NewCell(), NewExperimentalRegExpData(), NewFunctionTemplateInfo(), NewIrRegExpData(), NewJSModuleNamespace(), NewManyClosuresCell(), NewNoClosuresCell(), NewObjectTemplateInfo(), NewPropertyArray(), NewPropertyDescriptorObject(), NewSlowJSObjectWithPropertiesAndElements(), NewSymbolInternal(), NewTransitionArray(), and NewWeakArrayList().
ReinitializeJSGlobalProxy()
void v8::internal::Factory::ReinitializeJSGlobalProxy (DirectHandle< JSGlobalProxy > global, DirectHandle< JSFunction > constructor)
Definition at line 3853 of file factory.cc.
                                                                              {
  DCHECK(constructor->has_initial_map());
  DirectHandle<Map> map(constructor->initial_map(), isolate());
  DirectHandle<Map> old_map(object->map(), isolate());
  // The proxy's hash should be retained across reinitialization.
  DirectHandle<Object> raw_properties_or_hash(object->raw_properties_or_hash(),
                                              isolate());
  if (old_map->is_prototype_map()) {
    map = Map::Copy(isolate(), map, "CopyAsPrototypeForJSGlobalProxy");
    map->set_is_prototype_map(true);
  }
  JSObject::NotifyMapChange(old_map, map, isolate());
  old_map->NotifyLeafMapLayoutChange(isolate());
  // Check that the already allocated object has the same size and type as
  // objects allocated using the constructor.
  DCHECK(map->instance_size() == old_map->instance_size());
  DCHECK(map->instance_type() == old_map->instance_type());
  // In order to keep heap in consistent state there must be no allocations
  // before object re-initialization is finished.
  DisallowGarbageCollection no_gc;
  // Reset the map for the object.
  Tagged<JSGlobalProxy> raw = *object;
  raw->set_map(isolate(), *map, kReleaseStore);
  // Reinitialize the object from the constructor map.
  InitializeJSObjectFromMap(raw, *raw_properties_or_hash, *map,
                            NewJSObjectType::kAPIWrapper);
  // Ensure that the object and constructor belongs to the same native context.
  DCHECK_EQ(object->map()->map(), constructor->map()->map());
}
References v8::internal::Map::Copy(), v8::internal::DCHECK(), DCHECK_EQ, InitializeJSObjectFromMap(), isolate(), v8::internal::kAPIWrapper, v8::kReleaseStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JSObject::NotifyMapChange(), and v8::internal::raw_properties_or_hash.
Referenced by v8::internal::Genesis::CreateNewGlobals(), and v8::internal::Genesis::HookUpGlobalProxy().
requires() [1/6]
template<typename T >
v8::internal::Factory::requires (std::is_convertible_v< DirectHandle< T >, DirectHandle< Name >>)
requires() [2/6]
template<typename T >
v8::internal::Factory::requires (std::is_convertible_v< DirectHandle< T >, DirectHandle< String >>)
requires() [3/6]
template<typename T >
v8::internal::Factory::requires (std::is_convertible_v< Handle< T >, Handle< Name >>)
requires() [4/6]
template<typename T >
v8::internal::Factory::requires (std::is_convertible_v< Handle< T >, Handle< String >>)
requires() [5/6]
template<typename SeqString , template< typename > typename HandleType>
v8::internal::Factory::requires (std::is_convertible_v< HandleType< SeqString >, DirectHandle< SeqString >>)
requires() [6/6]
template<typename T , template< typename > typename HandleType>
v8::internal::Factory::requires (std::is_convertible_v< HandleType< T >, HandleType< String >>)
SetRegExpAtomData()
void v8::internal::Factory::SetRegExpAtomData (DirectHandle< JSRegExp > regexp, DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< String > match_pattern)
Definition at line 4191 of file factory.cc.
                                                              {
  DirectHandle<RegExpData> regexp_data =
      NewAtomRegExpData(source, flags, pattern);
  regexp->set_data(*regexp_data);
}
References v8::internal::flags, and NewAtomRegExpData().
Referenced by v8::internal::RegExpImpl::AtomCompile().
SetRegExpExperimentalData()
void v8::internal::Factory::SetRegExpExperimentalData (DirectHandle< JSRegExp > regexp, DirectHandle< String > source, JSRegExp::Flags flags, int capture_count)
Definition at line 4209 of file factory.cc.
                                                           {
  DirectHandle<RegExpData> regexp_data =
      NewExperimentalRegExpData(source, flags, capture_count);
  regexp->set_data(*regexp_data);
}
References v8::internal::flags, and NewExperimentalRegExpData().
Referenced by v8::internal::ExperimentalRegExp::Initialize().
SetRegExpIrregexpData()
void v8::internal::Factory::SetRegExpIrregexpData (DirectHandle< JSRegExp > regexp, DirectHandle< String > source, JSRegExp::Flags flags, int capture_count, uint32_t backtrack_limit)
Definition at line 4200 of file factory.cc.
                                                              {
  DirectHandle<RegExpData> regexp_data =
      NewIrRegExpData(source, flags, capture_count, backtrack_limit);
  regexp->set_data(*regexp_data);
}
References v8::internal::flags, and NewIrRegExpData().
Referenced by v8::internal::RegExpImpl::IrregexpInitialize().
ShadowRealmNewTypeErrorCopy() [1/2]
template<typename... Args>
DirectHandle<JSObject> v8::internal::Factory::ShadowRealmNewTypeErrorCopy (DirectHandle< Object > original, MessageTemplate template_index, Args... args) [inline]
Definition at line 954 of file factory.h.
  {
    return ShadowRealmNewTypeErrorCopy(
        original, template_index,
        base::VectorOf<DirectHandle<Object>>({args...}));
  }
References v8::base::args, and v8::base::VectorOf().
ShadowRealmNewTypeErrorCopy() [2/2]
DirectHandle< JSObject > v8::internal::Factory::ShadowRealmNewTypeErrorCopy (DirectHandle< Object > original, MessageTemplate template_index, base::Vector< const DirectHandle< Object >> args)
Definition at line 2831 of file factory.cc.
                                                 {
  return ErrorUtils::ShadowRealmConstructTypeErrorCopy(isolate(), original,
                                                       template_index, args);
}
References v8::base::args, isolate(), and v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy().
SizeToString()
Handle< String > v8::internal::Factory::SizeToString (size_t value, bool check_cache = true)
Definition at line 3963 of file factory.cc.
                                                                   {
  Handle<String> result;
  NumberCacheMode cache_mode =
      check_cache ? NumberCacheMode::kBoth : NumberCacheMode::kIgnore;
  if (value <= Smi::kMaxValue) {
    int32_t int32v = static_cast<int32_t>(static_cast<uint32_t>(value));
    // SmiToString sets the hash when needed, we can return immediately.
    return SmiToString(Smi::FromInt(int32v), cache_mode);
  } else if (value <= kMaxSafeInteger) {
    double double_value = static_cast<double>(value);
    // The value is already out of Smi range, so canonicalization can't
    // succeed. Skip it.
    result = DoubleToString(double_value, false, cache_mode);
  } else {
    char arr[kNumberToStringBufferSize];
    base::Vector<char> buffer(arr, arraysize(arr));
    // Build the string backwards from the least significant digit.
    int i = buffer.length();
    size_t value_copy = value;
    buffer[--i] = '\0';
    do {
      buffer[--i] = '0' + (value_copy % 10);
      value_copy /= 10;
    } while (value_copy > 0);
    char* string = buffer.begin() + i;
    // No way to cache this; we'd need an {Object} to use as key.
    result = NewStringFromAsciiChecked(string);
  }
  {
    DisallowGarbageCollection no_gc;
    Tagged<String> raw = *result;
    if (value <= JSArray::kMaxArrayIndex &&
        raw->raw_hash_field() == String::kEmptyHashField) {
      uint32_t raw_hash_field = StringHasher::MakeArrayIndexHash(
          static_cast<uint32_t>(value), raw->length());
      raw->set_raw_hash_field(raw_hash_field);
    }
  }
  return result;
}
References arraysize, v8::base::Vector< T >::begin(), v8::internal::FactoryBase< Factory >::DoubleToString(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kBoth, v8::internal::Name::kEmptyHashField, v8::internal::kIgnore, v8::internal::JSArray::kMaxArrayIndex, v8::internal::kMaxSafeInteger, v8::internal::Smi::kMaxValue, v8::internal::FactoryBase< Factory >::kNumberToStringBufferSize, v8::base::Vector< T >::length(), v8::internal::StringHasher::MakeArrayIndexHash(), v8::internal::FactoryBase< Factory >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::FactoryBase< Factory >::SmiToString(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DirectCollectElementIndicesImpl(), v8::internal::LookupIterator::GetName(), v8::internal::PropertyKey::GetName(), v8::internal::LookupIterator::LookupIterator(), v8::internal::MakeEntryPair(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), and v8::internal::DebugPropertyIterator::raw_name().
ToPrimitiveHintString()
DirectHandle< String > v8::internal::Factory::ToPrimitiveHintString (ToPrimitiveHint hint)
Definition at line 4313 of file factory.cc.
                                                                        {
  switch (hint) {
    case ToPrimitiveHint::kDefault:
      return default_string();
    case ToPrimitiveHint::kNumber:
      return number_string();
    case ToPrimitiveHint::kString:
      return string_string();
  }
  UNREACHABLE();
}
References v8::internal::kDefault, v8::internal::kNumber, v8::internal::kString, and v8::internal::UNREACHABLE().
TryNewFixedArray()
MaybeHandle< FixedArray > v8::internal::Factory::TryNewFixedArray (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 434 of file factory.cc.
                                                {
  DCHECK_LE(0, length);
  if (length == 0) return empty_fixed_array();
  int size = FixedArray::SizeFor(length);
  Heap* heap = isolate()->heap();
  AllocationResult allocation = heap->AllocateRaw(size, allocation_type);
  Tagged<HeapObject> result;
  if (!allocation.To(&result)) return MaybeHandle<FixedArray>();
  if ((size > heap->MaxRegularHeapObjectSize(allocation_type)) &&
      v8_flags.use_marking_progress_bar) {
    LargePageMetadata::FromHeapObject(result)
        ->marking_progress_tracker()
        .Enable(size);
  }
  DisallowGarbageCollection no_gc;
  result->set_map_after_allocation(isolate(), *fixed_array_map(),
                                   SKIP_WRITE_BARRIER);
  Tagged<FixedArray> array = Cast<FixedArray>(result);
  array->set_length(length);
  MemsetTagged(array->RawFieldOfFirstElement(), *undefined_value(), length);
  return handle(array, isolate());
}
References DCHECK_LE, v8::internal::MarkingProgressTracker::Enable(), v8::internal::LargePageMetadata::FromHeapObject(), v8::internal::handle(), v8::internal::Isolate::heap(), isolate(), length, v8::internal::MutablePageMetadata::marking_progress_tracker(), v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, size(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::AllocationResult::To(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl().
TypeAndSizeForElementsKind()
void v8::internal::Factory::TypeAndSizeForElementsKind (ElementsKind kind, ExternalArrayType * array_type, size_t * element_size) [static]
Definition at line 3634 of file factory.cc.
                                                               {
  switch (kind) {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: \
    *array_type = kExternal##Type##Array; \
    *element_size = sizeof(ctype); \
    break;
    TYPED_ARRAYS(TYPED_ARRAY_CASE)
    RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
    default:
      UNREACHABLE();
  }
}
References RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE, TYPED_ARRAY_CASE, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::RUNTIME_FUNCTION().
Uint32ToString()
DirectHandle<String> v8::internal::Factory::Uint32ToString (uint32_t value, bool check_cache = true) [inline]
Definition at line 990 of file factory.h.
                                                                      {
    return SizeToString(value, check_cache);
  }
References v8::internal::value.
Referenced by v8::internal::OrderedHashSet::ConvertToKeysArray(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DirectCollectElementIndicesImpl(), and v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl().
Friends And Related Function Documentation
FactoryBase< Factory >
friend class FactoryBase< Factory > [friend]
Definition at line 1117 of file factory.h.
Member Data Documentation
begin
uint32_t v8::internal::Factory::begin
Definition at line 384 of file factory.h.
Referenced by v8::internal::Isolate::AddCodeRange(), NewCopiedSubstring(), NewProperSubString(), NewStringFromTwoByte(), and NewStringFromUtf8SubString().
convert_encoding
uint32_t uint32_t bool v8::internal::Factory::convert_encoding = false)
Definition at line 233 of file factory.h.
Referenced by v8::internal::requires().
end
uint32_t uint32_t v8::internal::Factory::end
Definition at line 385 of file factory.h.
Referenced by CopyJSObjectWithAllocationSite(), NewContextInternal(), and NewProperSubString().
from
uint32_t v8::internal::Factory::from
Definition at line 231 of file factory.h.
Referenced by v8::internal::requires(), and v8::internal::Isolate::RestoreThread().
length
uint32_t uint32_t v8::internal::Factory::length
Definition at line 232 of file factory.h.
Referenced by v8::internal::Isolate::CaptureAndSetErrorStack(), v8::internal::Isolate::CheckDetachedContextsAfterGC(), CompactWeakArrayList(), v8::internal::anonymous_namespace{factory.cc}::initialize_length(), v8::internal::anonymous_namespace{factory.cc}::initialize_length< PropertyArray >(), NewArgumentsObject(), NewCopiedSubstring(), NewEmbedderDataArray(), NewExternalStringFromOneByte(), NewExternalStringFromTwoByte(), NewFeedbackVector(), NewFixedDoubleArrayWithHoles(), NewFunctionTemplateInfo(), NewJSArray(), NewJSArrayStorage(), NewJSArrayWithElements(), NewJSArrayWithUnverifiedElements(), NewJSSharedArray(), NewJSTypedArray(), NewProperSubString(), NewPropertyArray(), NewStringFromTwoByte(), NewStringFromUtf8SubString(), v8::internal::Factory::CodeBuilder::NewTrustedByteArray(), v8::internal::requires(), and TryNewFixedArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/factory.h
/mnt/V8SourceCode/src/heap/factory-inl.h
/mnt/V8SourceCode/src/heap/factory.cc