v8::internal::SamplingEventsProcessor Class Reference
#include <cpu-profiler.h>
Public Member Functions
SamplingEventsProcessor (Isolate *isolate, Symbolizer *symbolizer, ProfilerCodeObserver *code_observer, CpuProfilesCollection *profiles, base::TimeDelta period, bool use_precise_sampling)
~SamplingEventsProcessor () override
void * operator new (size_t size)
void operator delete (void *ptr)
void Run () override
void SetSamplingInterval (base::TimeDelta period) override
TickSample * StartTickSample ()
void FinishTickSample ()
sampler::Sampler * sampler ()
base::TimeDelta period () const
Private Member Functions
SampleProcessingResult ProcessOneSample () override
void SymbolizeAndAddToProfiles (const TickSampleEventRecord *record)
Private Attributes
SamplingCircularQueue< TickSampleEventRecord, kTickSampleQueueLength > ticks_buffer_
std::unique_ptr< sampler::Sampler > sampler_
base::TimeDelta period_
const bool use_precise_sampling_
Static Private Attributes
static const size_t kTickSampleBufferSize = 512 * KB
static const size_t kTickSampleQueueLength
Additional Inherited Members
Detailed Description
Definition at line 219 of file cpu-profiler.h.
Constructor & Destructor Documentation
SamplingEventsProcessor()
v8::internal::SamplingEventsProcessor::SamplingEventsProcessor (Isolate * isolate, Symbolizer * symbolizer, ProfilerCodeObserver * code_observer, CpuProfilesCollection * profiles, base::TimeDelta period, bool use_precise_sampling)
Definition at line 122 of file cpu-profiler.cc.
    : ProfilerEventsProcessor(isolate, symbolizer, code_observer, profiles),
      sampler_(new CpuSampler(isolate, this)),
      period_(period),
      use_precise_sampling_(use_precise_sampling) {
#if V8_OS_WIN
  precise_sleep_timer_.TryInit();
#endif // V8_OS_WIN
  sampler_->Start();
}
References sampler_.
 SamplingEventsProcessor()
v8::internal::SamplingEventsProcessor::~SamplingEventsProcessor () [override]
Definition at line 137 of file cpu-profiler.cc.
{ sampler_->Stop(); }
References sampler_.
Member Function Documentation
FinishTickSample()
void v8::internal::SamplingEventsProcessor::FinishTickSample () [inline]
Definition at line 87 of file cpu-profiler-inl.h.
                                               {
  ticks_buffer_.FinishEnqueue();
}
References ticks_buffer_.
Referenced by v8::internal::CpuSampler::SampleStack().
operator delete()
void v8::internal::SamplingEventsProcessor::operator delete (void * ptr)
Definition at line 354 of file cpu-profiler.cc.
{ AlignedFree(ptr); }
References v8::internal::AlignedFree().
operator new()
void * v8::internal::SamplingEventsProcessor::operator new (size_t size)
Definition at line 350 of file cpu-profiler.cc.
                                                       {
  return AlignedAllocWithRetry(size, alignof(SamplingEventsProcessor));
}
References v8::internal::AlignedAllocWithRetry(), and size().
period()
base::TimeDelta v8::internal::SamplingEventsProcessor::period () const [inline]
Definition at line 247 of file cpu-profiler.h.
{ return period_; }
Referenced by v8::internal::CpuSampler::SampleStack(), and SetSamplingInterval().
ProcessOneSample()
ProfilerEventsProcessor::SampleProcessingResult v8::internal::SamplingEventsProcessor::ProcessOneSample () [override], [private], [virtual]
Implements v8::internal::ProfilerEventsProcessor.
Definition at line 252 of file cpu-profiler.cc.
                                          {
  TickSampleEventRecord record1;
  if (ticks_from_vm_buffer_.Peek(&record1) &&
      (record1.order == last_processed_code_event_id_)) {
    TickSampleEventRecord record;
    ticks_from_vm_buffer_.Dequeue(&record);
    SymbolizeAndAddToProfiles(&record);
    return OneSampleProcessed;
  }
  const TickSampleEventRecord* record = ticks_buffer_.Peek();
  if (record == nullptr) {
    if (ticks_from_vm_buffer_.IsEmpty()) return NoSamplesInQueue;
    return FoundSampleForNextCodeEvent;
  }
  if (record->order != last_processed_code_event_id_) {
    return FoundSampleForNextCodeEvent;
  }
  SymbolizeAndAddToProfiles(record);
  ticks_buffer_.Remove();
  return OneSampleProcessed;
}
References v8::internal::ProfilerEventsProcessor::FoundSampleForNextCodeEvent, v8::internal::ProfilerEventsProcessor::last_processed_code_event_id_, v8::internal::ProfilerEventsProcessor::NoSamplesInQueue, v8::internal::ProfilerEventsProcessor::OneSampleProcessed, v8::internal::TickSampleEventRecord::order, SymbolizeAndAddToProfiles(), ticks_buffer_, and v8::internal::ProfilerEventsProcessor::ticks_from_vm_buffer_.
Referenced by Run().
Run()
void v8::internal::SamplingEventsProcessor::Run () [override], [virtual]
Implements v8::internal::ProfilerEventsProcessor.
Definition at line 275 of file cpu-profiler.cc.
                                  {
  // Set the current isolate such that trusted pointer tables etc are available.
  SetCurrentIsolateScope isolate_scope(isolate_);
  base::MutexGuard guard(&running_mutex_);
  while (running_.load(std::memory_order_relaxed)) {
    base::TimeTicks nextSampleTime = base::TimeTicks::Now() + period_;
    base::TimeTicks now;
    SampleProcessingResult result;
    // Keep processing existing events until we need to do next sample
    // or the ticks buffer is empty.
    do {
      result = ProcessOneSample();
      if (result == FoundSampleForNextCodeEvent) {
        // All ticks of the current last_processed_code_event_id_ are
        // processed, proceed to the next code event.
        ProcessCodeEvent();
      }
      now = base::TimeTicks::Now();
    } while (result != NoSamplesInQueue && now < nextSampleTime);
    if (nextSampleTime > now) {
#if V8_OS_WIN
      if (use_precise_sampling_ &&
          nextSampleTime - now < base::TimeDelta::FromMilliseconds(100)) {
        if (precise_sleep_timer_.IsInitialized()) {
          precise_sleep_timer_.Sleep(nextSampleTime - now);
        } else {
          // Do not use Sleep on Windows as it is very imprecise, with up to
          // 16ms jitter, which is unacceptable for short profile intervals.
          while (base::TimeTicks::Now() < nextSampleTime) {
          }
        }
      } else // NOLINT
#else
      USE(use_precise_sampling_);
#endif // V8_OS_WIN
      {
        // Allow another thread to interrupt the delay between samples in the
        // event of profiler shutdown.
        while (now < nextSampleTime &&
               running_cond_.WaitFor(&running_mutex_, nextSampleTime - now)) {
          // If true was returned, we got interrupted before the timeout
          // elapsed. If this was not due to a change in running state, a
          // spurious wakeup occurred (thus we should continue to wait).
          if (!running_.load(std::memory_order_relaxed)) {
            break;
          }
          now = base::TimeTicks::Now();
        }
      }
    }
    // Schedule next sample.
    sampler_->DoSample();
  }
  // Process remaining tick events.
  do {
    SampleProcessingResult result;
    do {
      result = ProcessOneSample();
    } while (result == OneSampleProcessed);
  } while (ProcessCodeEvent());
}
References v8::internal::ProfilerEventsProcessor::FoundSampleForNextCodeEvent, v8::base::TimeDelta::FromMilliseconds(), v8::internal::ProfilerEventsProcessor::isolate_, v8::internal::ProfilerEventsProcessor::NoSamplesInQueue, v8::base::TimeTicks::Now(), v8::internal::ProfilerEventsProcessor::OneSampleProcessed, period_, v8::internal::ProfilerEventsProcessor::ProcessCodeEvent(), ProcessOneSample(), v8::base::internal::result, v8::internal::ProfilerEventsProcessor::running_, v8::internal::ProfilerEventsProcessor::running_cond_, v8::internal::ProfilerEventsProcessor::running_mutex_, sampler_, USE, use_precise_sampling_, and v8::base::ConditionVariable::WaitFor().
sampler()
sampler::Sampler* v8::internal::SamplingEventsProcessor::sampler () [inline]
Definition at line 246 of file cpu-profiler.h.
{ return sampler_.get(); }
SetSamplingInterval()
void v8::internal::SamplingEventsProcessor::SetSamplingInterval (base::TimeDelta period) [override], [virtual]
Reimplemented from v8::internal::ProfilerEventsProcessor.
Definition at line 340 of file cpu-profiler.cc.
                                                                      {
  if (period_ == period) return;
  StopSynchronously();
  period_ = period;
  running_.store(true, std::memory_order_relaxed);
  CHECK(StartSynchronously());
}
References CHECK, period(), period_, v8::internal::ProfilerEventsProcessor::running_, v8::base::Thread::StartSynchronously(), and v8::internal::ProfilerEventsProcessor::StopSynchronously().
StartTickSample()
TickSample * v8::internal::SamplingEventsProcessor::StartTickSample () [inline]
Definition at line 73 of file cpu-profiler-inl.h.
                                                     {
  void* address = ticks_buffer_.StartEnqueue();
  if (address == nullptr) return nullptr;
  TickSampleEventRecord* evt =
      new (address) TickSampleEventRecord(last_code_event_id_);
  return &evt->sample;
}
References v8::internal::ProfilerEventsProcessor::last_code_event_id_, v8::internal::TickSampleEventRecord::sample, and ticks_buffer_.
Referenced by v8::internal::CpuSampler::SampleStack().
SymbolizeAndAddToProfiles()
void v8::internal::SamplingEventsProcessor::SymbolizeAndAddToProfiles (const TickSampleEventRecord * record) [private]
Definition at line 237 of file cpu-profiler.cc.
                                         {
  const TickSample& tick_sample = record->sample;
  Symbolizer::SymbolizedSample symbolized =
      symbolizer_->SymbolizeTickSample(tick_sample);
  profiles_->AddPathToCurrentProfiles(
      tick_sample.timestamp, symbolized.stack_trace, symbolized.src_pos,
      tick_sample.update_stats_, tick_sample.sampling_interval_,
      tick_sample.state, tick_sample.embedder_state,
      reinterpret_cast<Address>(tick_sample.context),
      reinterpret_cast<Address>(tick_sample.embedder_context),
      tick_sample.trace_id_);
}
References v8::internal::CpuProfilesCollection::AddPathToCurrentProfiles(), v8::internal::TickSample::context, v8::internal::TickSample::embedder_context, v8::internal::TickSample::embedder_state, v8::internal::ProfilerEventsProcessor::profiles_, v8::internal::TickSampleEventRecord::sample, v8::internal::TickSample::sampling_interval_, v8::internal::Symbolizer::SymbolizedSample::src_pos, v8::internal::Symbolizer::SymbolizedSample::stack_trace, v8::internal::TickSample::state, v8::internal::ProfilerEventsProcessor::symbolizer_, v8::internal::Symbolizer::SymbolizeTickSample(), v8::internal::TickSample::timestamp, v8::internal::TickSample::trace_id_, and v8::internal::TickSample::update_stats_.
Referenced by ProcessOneSample().
Member Data Documentation
kTickSampleBufferSize
const size_t v8::internal::SamplingEventsProcessor::kTickSampleBufferSize = 512 * KB [static], [private]
Definition at line 253 of file cpu-profiler.h.
kTickSampleQueueLength
const size_t v8::internal::SamplingEventsProcessor::kTickSampleQueueLength [static], [private]
Initial value:
=
      kTickSampleBufferSize / sizeof(TickSampleEventRecord)
Definition at line 254 of file cpu-profiler.h.
period_
base::TimeDelta v8::internal::SamplingEventsProcessor::period_ [private]
Definition at line 259 of file cpu-profiler.h.
Referenced by Run(), and SetSamplingInterval().
sampler_
std::unique_ptr<sampler::Sampler> v8::internal::SamplingEventsProcessor::sampler_ [private]
Definition at line 258 of file cpu-profiler.h.
Referenced by Run(), SamplingEventsProcessor(), and ~SamplingEventsProcessor().
ticks_buffer_
SamplingCircularQueue<TickSampleEventRecord, kTickSampleQueueLength> v8::internal::SamplingEventsProcessor::ticks_buffer_ [private]
Definition at line 257 of file cpu-profiler.h.
Referenced by FinishTickSample(), ProcessOneSample(), and StartTickSample().
use_precise_sampling_
const bool v8::internal::SamplingEventsProcessor::use_precise_sampling_ [private]
Definition at line 260 of file cpu-profiler.h.
Referenced by Run().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/cpu-profiler.h
/mnt/V8SourceCode/src/profiler/cpu-profiler-inl.h
/mnt/V8SourceCode/src/profiler/cpu-profiler.cc