v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor Class Reference
Public Member Functions
CustomRootBodyMarkingVisitor (MarkCompactCollector *collector)
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
Private Member Functions
void MarkObject (Tagged< HeapObject > host, Tagged< Object > object)
Private Attributes
MarkCompactCollector *const collector_
Detailed Description
Definition at line 955 of file mark-compact.cc.
Constructor & Destructor Documentation
CustomRootBodyMarkingVisitor()
v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::CustomRootBodyMarkingVisitor (MarkCompactCollector * collector) [inline], [explicit]
Definition at line 958 of file mark-compact.cc.
      : ObjectVisitorWithCageBases(collector->heap_->isolate()),
        collector_(collector) {}
Member Function Documentation
MarkObject()
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::MarkObject (Tagged< HeapObject > host, Tagged< Object > object) [inline], [private]
Definition at line 1004 of file mark-compact.cc.
                                                                            {
    if (!IsHeapObject(object)) return;
    Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
    const auto target_worklist =
        MarkingHelper::ShouldMarkObject(collector_->heap(), heap_object);
    if (!target_worklist) {
      return;
    }
    collector_->MarkObject(host, heap_object, target_worklist.value());
  }
References collector_, v8::internal::MarkCompactCollector::heap(), v8::internal::IsHeapObject(), v8::internal::MarkCompactCollector::MarkObject(), and v8::internal::MarkingHelper::ShouldMarkObject().
Referenced by VisitCodeTarget(), VisitEmbeddedPointer(), VisitInstructionStreamPointer(), VisitMapPointer(), VisitPointer(), and VisitPointers().
VisitCodeTarget()
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 991 of file mark-compact.cc.
                                                  {
    Tagged<InstructionStream> target =
        InstructionStream::FromTargetAddress(rinfo->target_address());
    MarkObject(host, target);
  }
References v8::internal::InstructionStream::FromTargetAddress(), MarkObject(), and v8::internal::RelocInfo::target_address().
VisitEmbeddedPointer()
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 998 of file mark-compact.cc.
                                                       {
    MarkObject(host, rinfo->target_object(cage_base()));
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), MarkObject(), and v8::internal::RelocInfo::target_object().
VisitInstructionStreamPointer()
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 980 of file mark-compact.cc.
                                                                          {
    MarkObject(host, slot.load(code_cage_base()));
  }
References v8::internal::ObjectVisitorWithCageBases::code_cage_base(), v8::internal::FullObjectSlot::load(), and MarkObject().
VisitMapPointer()
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 966 of file mark-compact.cc.
                                                      {
    MarkObject(host, host->map(cage_base()));
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and MarkObject().
VisitPointer()
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 962 of file mark-compact.cc.
                                                                 {
    MarkObject(host, p.load(cage_base()));
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and MarkObject().
VisitPointers() [1/2]
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 985 of file mark-compact.cc.
                                                {
    // At the moment, custom roots cannot contain weak pointers.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitPointers() [2/2]
void v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 970 of file mark-compact.cc.
                                           {
    for (ObjectSlot p = start; p < end; ++p) {
      // The map slot should be handled in VisitMapPointer.
      DCHECK_NE(host->map_slot(), p);
      DCHECK(!HasWeakHeapObjectTag(p.load(cage_base())));
      MarkObject(host, p.load(cage_base()));
    }
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::end(), v8::internal::HasWeakHeapObjectTag(), and MarkObject().
Member Data Documentation
collector_
MarkCompactCollector* const v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::collector_ [private]
Definition at line 1015 of file mark-compact.cc.
Referenced by MarkObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc