v8::internal::compiler::ControlPathState< NodeState, node_uniqueness > Class Template Reference
#include <control-path-state.h>
Public Member Functions
ControlPathState (Zone *zone)
NodeState LookupState (Node *node) const
void AddState (Zone *zone, Node *node, NodeState state, ControlPathState hint)
void AddStateInNewBlock (Zone *zone, Node *node, NodeState state)
void ResetToCommonAncestor (ControlPathState other)
bool IsEmpty ()
bool operator== (const ControlPathState &other) const
bool operator!= (const ControlPathState &other) const
Private Types
using NodeWithPathDepth = std::pair< Node *, size_t >
Private Member Functions
size_t depth (size_t depth_if_multiple_instances)
Private Attributes
FunctionalList< FunctionalList< NodeState > > blocks_
PersistentMap< NodeWithPathDepth, NodeState > states_
Detailed Description
template<typename NodeState, NodeUniqueness node_uniqueness>
class v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >
Definition at line 31 of file control-path-state.h.
Member Typedef Documentation
NodeWithPathDepth
template<typename NodeState , NodeUniqueness node_uniqueness>
using v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::NodeWithPathDepth = std::pair<Node*, size_t> [private]
Definition at line 66 of file control-path-state.h.
Constructor & Destructor Documentation
ControlPathState()
template<typename NodeState , NodeUniqueness node_uniqueness>
v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::ControlPathState (Zone * zone) [inline], [explicit]
Definition at line 39 of file control-path-state.h.
: states_(zone) {}
Member Function Documentation
AddState()
template<typename NodeState , NodeUniqueness node_uniqueness>
void v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddState (Zone * zone, Node * node, NodeState state, ControlPathState< NodeState, node_uniqueness > hint)
Definition at line 135 of file control-path-state.h.
                                                       {
  NodeState previous_state = LookupState(node);
  if (node_uniqueness == kUniqueInstance ? previous_state.IsSet()
                                         : previous_state == state) {
    return;
  }
  FunctionalList<NodeState> prev_front = blocks_.Front();
  if (hint.blocks_.Size() > 0) {
    prev_front.PushFront(state, zone, hint.blocks_.Front());
  } else {
    prev_front.PushFront(state, zone);
  }
  blocks_.DropFront();
  blocks_.PushFront(prev_front, zone);
  states_.Set({node, depth(blocks_.Size())}, state);
  SLOW_DCHECK(BlocksAndStatesInvariant());
}
References v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::blocks_, v8::internal::compiler::FunctionalList< A >::Front(), v8::internal::compiler::kUniqueInstance, v8::internal::compiler::FunctionalList< A >::PushFront(), and SLOW_DCHECK.
Referenced by v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::UpdateStates().
AddStateInNewBlock()
template<typename NodeState , NodeUniqueness node_uniqueness>
void v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddStateInNewBlock (Zone * zone, Node * node, NodeState state)
Definition at line 157 of file control-path-state.h.
                                             {
  FunctionalList<NodeState> new_block;
  NodeState previous_state = LookupState(node);
  if (node_uniqueness == kUniqueInstance ? !previous_state.IsSet()
                                         : previous_state != state) {
    new_block.PushFront(state, zone);
    states_.Set({node, depth(blocks_.Size() + 1)}, state);
  }
  blocks_.PushFront(new_block, zone);
  SLOW_DCHECK(BlocksAndStatesInvariant());
}
References v8::internal::compiler::kUniqueInstance, v8::internal::compiler::FunctionalList< A >::PushFront(), and SLOW_DCHECK.
Referenced by v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::UpdateStates().
depth()
template<typename NodeState , NodeUniqueness node_uniqueness>
size_t v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::depth (size_t depth_if_multiple_instances) [inline], [private]
Definition at line 68 of file control-path-state.h.
                                                   {
    return node_uniqueness == kMultipleInstances ? depth_if_multiple_instances
                                                 : 0;
  }
References v8::internal::compiler::kMultipleInstances.
IsEmpty()
template<typename NodeState , NodeUniqueness node_uniqueness>
bool v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::IsEmpty () [inline]
Definition at line 56 of file control-path-state.h.
{ return blocks_.Size() == 0; }
References v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::blocks_.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::UpdateNodeAndAliasesTypes(), and v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::UpdateStates().
LookupState()
template<typename NodeState , NodeUniqueness node_uniqueness>
NodeState v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::LookupState (Node * node) const
Definition at line 124 of file control-path-state.h.
                      {
  if (node_uniqueness == kUniqueInstance) return states_.Get({node, 0});
  for (size_t depth = blocks_.Size(); depth > 0; depth--) {
    NodeState state = states_.Get({node, depth});
    if (state.IsSet()) return state;
  }
  return {};
}
References v8::internal::compiler::kUniqueInstance.
Referenced by v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), and v8::internal::compiler::WasmGCOperatorReducer::UpdateNodeAndAliasesTypes().
operator!=()
template<typename NodeState , NodeUniqueness node_uniqueness>
bool v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::operator!= (const ControlPathState< NodeState, node_uniqueness > & other) const [inline]
Definition at line 61 of file control-path-state.h.
                                                       {
    return blocks_ != other.blocks_;
  }
References v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::blocks_.
operator==()
template<typename NodeState , NodeUniqueness node_uniqueness>
bool v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::operator== (const ControlPathState< NodeState, node_uniqueness > & other) const [inline]
Definition at line 58 of file control-path-state.h.
                                                       {
    return blocks_ == other.blocks_;
  }
References v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::blocks_.
ResetToCommonAncestor()
template<typename NodeState , NodeUniqueness node_uniqueness>
void v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::ResetToCommonAncestor (ControlPathState< NodeState, node_uniqueness > other)
Definition at line 171 of file control-path-state.h.
                                                        {
  while (other.blocks_.Size() > blocks_.Size()) other.blocks_.DropFront();
  while (blocks_.Size() > other.blocks_.Size()) {
    for (NodeState state : blocks_.Front()) {
      states_.Set({state.node, depth(blocks_.Size())}, {});
    }
    blocks_.DropFront();
  }
  while (blocks_ != other.blocks_) {
    for (NodeState state : blocks_.Front()) {
      states_.Set({state.node, depth(blocks_.Size())}, {});
    }
    blocks_.DropFront();
    other.blocks_.DropFront();
  }
  SLOW_DCHECK(BlocksAndStatesInvariant());
}
References v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::blocks_, and SLOW_DCHECK.
Referenced by v8::internal::compiler::BranchElimination::ReduceMerge(), and v8::internal::compiler::WasmGCOperatorReducer::ReduceMerge().
Member Data Documentation
blocks_
template<typename NodeState , NodeUniqueness node_uniqueness>
FunctionalList<FunctionalList<NodeState> > v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::blocks_ [private]
Definition at line 77 of file control-path-state.h.
Referenced by v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::AddState(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::IsEmpty(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::operator!=(), v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::operator==(), and v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::ResetToCommonAncestor().
states_
template<typename NodeState , NodeUniqueness node_uniqueness>
PersistentMap<NodeWithPathDepth, NodeState> v8::internal::compiler::ControlPathState< NodeState, node_uniqueness >::states_ [private]
Definition at line 82 of file control-path-state.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/control-path-state.h