v8::internal::ScavengerCollector::QuarantinedPageSweeper Class Reference
Classes
class JobTask
Public Member Functions
QuarantinedPageSweeper (Heap *heap)
~QuarantinedPageSweeper ()
void StartSweeping (const PinnedObjects &&pinned_objects)
void FinishSweeping ()
bool IsSweeping () const
Private Attributes
Heap *const heap_
std::unique_ptr< JobHandle > job_handle_
Detailed Description
Definition at line 291 of file scavenger.h.
Constructor & Destructor Documentation
QuarantinedPageSweeper()
v8::internal::ScavengerCollector::QuarantinedPageSweeper::QuarantinedPageSweeper (Heap * heap) [inline], [explicit]
Definition at line 293 of file scavenger.h.
: heap_(heap) {}
 QuarantinedPageSweeper()
v8::internal::ScavengerCollector::QuarantinedPageSweeper::~QuarantinedPageSweeper () [inline]
Definition at line 294 of file scavenger.h.
                              {
      if (IsSweeping()) {
        FinishSweeping();
      }
    }
References FinishSweeping(), and IsSweeping().
Member Function Documentation
FinishSweeping()
void v8::internal::ScavengerCollector::QuarantinedPageSweeper::FinishSweeping ()
Definition at line 807 of file scavenger.cc.
                                                              {
  job_handle_->Join();
  job_handle_.reset();
}
References job_handle_.
Referenced by v8::internal::ScavengerCollector::CompleteSweepingQuarantinedPagesIfNeeded(), and ~QuarantinedPageSweeper().
IsSweeping()
bool v8::internal::ScavengerCollector::QuarantinedPageSweeper::IsSweeping () const [inline]
Definition at line 302 of file scavenger.h.
                            {
      DCHECK_IMPLIES(job_handle_, job_handle_->IsValid());
      return job_handle_.get();
    }
References DCHECK_IMPLIES, and job_handle_.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::ScavengerCollector::CompleteSweepingQuarantinedPagesIfNeeded(), and ~QuarantinedPageSweeper().
StartSweeping()
void v8::internal::ScavengerCollector::QuarantinedPageSweeper::StartSweeping (const PinnedObjects && pinned_objects)
Definition at line 796 of file scavenger.cc.
                                                            {
  DCHECK_NULL(job_handle_);
  DCHECK(!pinned_objects.empty());
  auto job = std::make_unique<JobTask>(heap_, std::move(pinned_objects));
  TRACE_GC_NOTE_WITH_FLOW("Quarantined page sweeper started", job->trace_id(),
                          TRACE_EVENT_FLAG_FLOW_OUT);
  job_handle_ = V8::GetCurrentPlatform()->PostJob(
      v8::TaskPriority::kUserVisible, std::move(job));
}
References v8::internal::DCHECK(), DCHECK_NULL, v8::internal::V8::GetCurrentPlatform(), heap_, job_handle_, v8::kUserVisible, v8::Platform::PostJob(), TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_GC_NOTE_WITH_FLOW.
Member Data Documentation
heap_
Heap* const v8::internal::ScavengerCollector::QuarantinedPageSweeper::heap_ [private]
Definition at line 352 of file scavenger.h.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), StartSweeping(), and v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::SweepPage().
job_handle_
std::unique_ptr<JobHandle> v8::internal::ScavengerCollector::QuarantinedPageSweeper::job_handle_ [private]
Definition at line 353 of file scavenger.h.
Referenced by FinishSweeping(), IsSweeping(), and StartSweeping().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger.h
/mnt/V8SourceCode/src/heap/scavenger.cc