v8::internal::MinorGCJob Class Reference
#include <minor-gc-job.h>
Classes
class Task
Public Member Functions
MinorGCJob (Heap *heap) V8_NOEXCEPT
void TryScheduleTask ()
void CancelTaskIfScheduled ()
Private Member Functions
bool IsScheduled () const
Private Attributes
Heap *const heap_
CancelableTaskManager::Id current_task_id_
std::unique_ptr< AllocationObserver > minor_gc_task_observer_
Detailed Description
Definition at line 24 of file minor-gc-job.h.
Constructor & Destructor Documentation
MinorGCJob()
v8::internal::MinorGCJob::MinorGCJob (Heap * heap) [explicit]
Definition at line 133 of file minor-gc-job.cc.
    : heap_(heap),
      minor_gc_task_observer_(new ScheduleMinorGCTaskObserver(this, heap)) {}
Member Function Documentation
CancelTaskIfScheduled()
void v8::internal::MinorGCJob::CancelTaskIfScheduled ()
Definition at line 153 of file minor-gc-job.cc.
                                       {
  if (!IsScheduled()) {
    return;
  }
  // The task may have ran and bailed out already if major incremental marking
  // was running, in which `TryAbort` will return `kTaskRemoved`.
  heap_->isolate()->cancelable_task_manager()->TryAbort(current_task_id_);
  current_task_id_ = CancelableTaskManager::kInvalidTaskId;
}
References v8::internal::Isolate::cancelable_task_manager(), current_task_id_, heap_, v8::internal::Heap::isolate(), IsScheduled(), v8::internal::CancelableTaskManager::kInvalidTaskId, and v8::internal::CancelableTaskManager::TryAbort().
Referenced by v8::internal::Heap::GarbageCollectionPrologue().
IsScheduled()
bool v8::internal::MinorGCJob::IsScheduled () const [inline], [private]
Definition at line 37 of file minor-gc-job.h.
                           {
    return current_task_id_ != CancelableTaskManager::kInvalidTaskId;
  }
References current_task_id_, and v8::internal::CancelableTaskManager::kInvalidTaskId.
Referenced by CancelTaskIfScheduled(), and TryScheduleTask().
TryScheduleTask()
void v8::internal::MinorGCJob::TryScheduleTask ()
Definition at line 137 of file minor-gc-job.cc.
                                 {
  if (!v8_flags.minor_gc_task || IsScheduled() || heap_->IsTearingDown()) {
    return;
  }
  const auto priority = v8_flags.minor_gc_task_with_lower_priority
                            ? TaskPriority::kUserVisible
                            : TaskPriority::kUserBlocking;
  std::shared_ptr<v8::TaskRunner> taskrunner =
      heap_->GetForegroundTaskRunner(priority);
  if (taskrunner->NonNestableTasksEnabled()) {
    std::unique_ptr<Task> task = std::make_unique<Task>(heap_->isolate(), this);
    current_task_id_ = task->id();
    taskrunner->PostNonNestableTask(std::move(task));
  }
}
References current_task_id_, v8::internal::Heap::GetForegroundTaskRunner(), heap_, v8::internal::Heap::isolate(), IsScheduled(), v8::internal::Heap::IsTearingDown(), v8::kUserBlocking, v8::kUserVisible, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded(), and v8::internal::ScheduleMinorGCTaskObserver::Step().
Member Data Documentation
current_task_id_
CancelableTaskManager::Id v8::internal::MinorGCJob::current_task_id_ [private]
Initial value:
=
      CancelableTaskManager::kInvalidTaskId
Definition at line 42 of file minor-gc-job.h.
Referenced by CancelTaskIfScheduled(), IsScheduled(), v8::internal::MinorGCJob::Task::RunInternal(), and TryScheduleTask().
heap_
Heap* const v8::internal::MinorGCJob::heap_ [private]
Definition at line 41 of file minor-gc-job.h.
Referenced by CancelTaskIfScheduled(), and TryScheduleTask().
minor_gc_task_observer_
std::unique_ptr<AllocationObserver> v8::internal::MinorGCJob::minor_gc_task_observer_ [private]
Definition at line 44 of file minor-gc-job.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/minor-gc-job.h
/mnt/V8SourceCode/src/heap/minor-gc-job.cc