v8::internal::PretenuringHandler Class Reference
#include <pretenuring-handler.h>
Public Types
enum FindMementoMode { kForRuntime
, kForGC
 }
using PretenuringFeedbackMap = std::unordered_map< Tagged< AllocationSite >, size_t, Object::Hasher >
Public Member Functions
PretenuringHandler (Heap *heap)
~PretenuringHandler ()
void reset ()
void MergeAllocationSitePretenuringFeedback (const PretenuringFeedbackMap &local_pretenuring_feedback)
V8_EXPORT_PRIVATE void PretenureAllocationSiteOnNextCollection (Tagged< AllocationSite > site)
void ProcessPretenuringFeedback (size_t new_space_capacity_before_gc)
void RemoveAllocationSitePretenuringFeedback (Tagged< AllocationSite > site)
bool HasPretenuringFeedback () const
Static Public Member Functions
template<FindMementoMode mode>
static Tagged< AllocationMemento > FindAllocationMemento (Heap *heap, Tagged< Map > map, Tagged< HeapObject > object)
template<FindMementoMode mode>
static Tagged< AllocationMemento > FindAllocationMemento (Heap *heap, Tagged< Map > map, Tagged< HeapObject > object, int object_size)
static void UpdateAllocationSite (Heap *heap, Tagged< Map > map, Tagged< HeapObject > object, int object_size, PretenuringFeedbackMap *pretenuring_feedback)
static V8_EXPORT_PRIVATE int GetMinMementoCountForTesting ()
Static Public Attributes
static constexpr int kInitialFeedbackCapacity = 256
Private Attributes
Heap *const heap_
PretenuringFeedbackMap global_pretenuring_feedback_
std::unique_ptr< GlobalHandleVector< AllocationSite > > allocation_sites_to_pretenure_
Detailed Description
Definition at line 21 of file pretenuring-handler.h.
Member Typedef Documentation
PretenuringFeedbackMap
using v8::internal::PretenuringHandler::PretenuringFeedbackMap = std::unordered_map<Tagged<AllocationSite>, size_t, Object::Hasher>
Definition at line 25 of file pretenuring-handler.h.
Member Enumeration Documentation
FindMementoMode
enum v8::internal::PretenuringHandler::FindMementoMode
Enumerator
kForRuntime
kForGC
Definition at line 27 of file pretenuring-handler.h.
{ kForRuntime, kForGC };
Constructor & Destructor Documentation
PretenuringHandler()
v8::internal::PretenuringHandler::PretenuringHandler (Heap * heap) [explicit]
Definition at line 19 of file pretenuring-handler.cc.
    : heap_(heap), global_pretenuring_feedback_(kInitialFeedbackCapacity) {}
 PretenuringHandler()
v8::internal::PretenuringHandler::~PretenuringHandler () [default]
Member Function Documentation
FindAllocationMemento() [1/2]
template<PretenuringHandler::FindMementoMode mode>
Tagged< AllocationMemento > v8::internal::PretenuringHandler::FindAllocationMemento (Heap * heap, Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 55 of file pretenuring-handler-inl.h.
                                                            {
  return FindAllocationMemento<mode>(heap, map, object,
                                     object->SizeFromMap(map));
}
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::JSObject::UpdateAllocationSite().
FindAllocationMemento() [2/2]
template<PretenuringHandler::FindMementoMode mode>
Tagged< AllocationMemento > v8::internal::PretenuringHandler::FindAllocationMemento (Heap * heap, Tagged< Map > map, Tagged< HeapObject > object, int object_size) [inline], [static]
Definition at line 63 of file pretenuring-handler-inl.h.
                                                                             {
  // For uses from within the GC, the size here may actually change when e.g.
  // updating mementos during marking in the young generation collector. This is
  // not an issue with Scavenger that stops the mutator.
  DCHECK_IMPLIES(mode != FindMementoMode::kForGC || !v8_flags.minor_ms,
                 object_size == object->SizeFromMap(map));
  // For configurations where object size changes, we can check that it only
  // shinks in case the sizes are not matching.
  DCHECK_IMPLIES(mode == FindMementoMode::kForGC && v8_flags.minor_ms,
                 object_size >= object->SizeFromMap(map));
  Address object_address = object.address();
  Address memento_address =
      object_address + ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  Address last_memento_word_address = memento_address + kTaggedSize;
  // If the memento would be on another page, bail out immediately.
  if (!PageMetadata::OnSamePage(object_address, last_memento_word_address)) {
    return {};
  }
  // If the page is being swept, treat it as if the memento was already swept
  // and bail out.
  if constexpr (mode != FindMementoMode::kForGC) {
    MemoryChunk* object_chunk = MemoryChunk::FromAddress(object_address);
    PageMetadata* object_page = PageMetadata::cast(object_chunk->Metadata());
    if (!object_page->SweepingDone()) {
      return {};
    }
  }
  Tagged<HeapObject> candidate = HeapObject::FromAddress(memento_address);
  ObjectSlot candidate_map_slot = candidate->map_slot();
  // This fast check may peek at an uninitialized word. However, the slow check
  // below (memento_address == top) ensures that this is safe. Mark the word as
  // initialized to silence MemorySanitizer warnings.
  MSAN_MEMORY_IS_INITIALIZED(candidate_map_slot.address(), kTaggedSize);
  if (!candidate_map_slot.Relaxed_ContainsMapValue(
          ReadOnlyRoots(heap).allocation_memento_map().ptr())) {
    return {};
  }
  // Bailout if memento is below the age mark. This is only possible for pinned
  // pages in the scavenger. Full GC has page promotion but clears the
  // NEW_SPACE_BELOW_AGE_MARK page flags before checking mementos.
  if (!v8_flags.minor_ms &&
      heap->semi_space_new_space()->IsAddressBelowAgeMark(object_address)) {
    return {};
  }
  Tagged<AllocationMemento> memento_candidate =
      Cast<AllocationMemento>(candidate);
  // Depending on what the memento is used for, we might need to perform
  // additional checks.
  Address top;
  switch (mode) {
    case kForGC:
      return memento_candidate;
    case kForRuntime:
      if (memento_candidate.is_null()) return {};
      // Either the object is the last object in the new space, or there is
      // another object of at least word size (the header map word) following
      // it, so suffices to compare ptr and top here.
      top = heap->NewSpaceTop();
      DCHECK(memento_address >= heap->NewSpaceLimit() ||
             memento_address +
                     ALIGN_TO_ALLOCATION_ALIGNMENT(sizeof(AllocationMemento)) <=
                 top);
      if ((memento_address != top) && memento_candidate->IsValid()) {
        return memento_candidate;
      }
      return {};
    default:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::PageMetadata::cast(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::MemoryChunk::FromAddress(), v8::internal::HeapObject::FromAddress(), v8::internal::Tagged< HeapObject >::is_null(), kForGC, kForRuntime, v8::internal::kTaggedSize, v8::internal::MemoryChunk::Metadata(), mode(), MSAN_MEMORY_IS_INITIALIZED, v8::internal::PageMetadata::OnSamePage(), v8::internal::FullObjectSlot::Relaxed_ContainsMapValue(), v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
GetMinMementoCountForTesting()
int v8::internal::PretenuringHandler::GetMinMementoCountForTesting () [static]
Definition at line 136 of file pretenuring-handler.cc.
                                                     {
  return kMinMementoCount;
}
References v8::internal::anonymous_namespace{pretenuring-handler.cc}::kMinMementoCount.
HasPretenuringFeedback()
bool v8::internal::PretenuringHandler::HasPretenuringFeedback () const [inline]
Definition at line 77 of file pretenuring-handler.h.
                                      {
    return !global_pretenuring_feedback_.empty();
  }
References global_pretenuring_feedback_.
MergeAllocationSitePretenuringFeedback()
void v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback (const PretenuringFeedbackMap & local_pretenuring_feedback)
Definition at line 140 of file pretenuring-handler.cc.
                                                              {
  PtrComprCageBase cage_base(heap_->isolate());
  Tagged<AllocationSite> site;
  for (auto& site_and_count : local_pretenuring_feedback) {
    site = site_and_count.first;
    MapWord map_word = site->map_word(kRelaxedLoad);
    if (map_word.IsForwardingAddress()) {
      DCHECK(!HeapLayout::IsSelfForwarded(site, map_word));
      site = Cast<AllocationSite>(map_word.ToForwardingAddress(site));
    }
    // We have not validated the allocation site yet, since we have not
    // dereferenced the site during collecting information.
    // This is an inlined check of AllocationMemento::IsValid.
    if (!IsAllocationSite(site) || site->IsZombie()) continue;
    const int value = static_cast<int>(site_and_count.second);
    DCHECK_LT(0, value);
    if (site->IncrementMementoFoundCount(value) >= kMinMementoCount) {
      // For sites in the global map the count is accessed through the site.
      global_pretenuring_feedback_.insert(std::make_pair(site, 0));
    }
  }
}
References v8::internal::DCHECK(), DCHECK_LT, global_pretenuring_feedback_, heap_, v8::internal::MapWord::IsForwardingAddress(), v8::internal::Heap::isolate(), v8::internal::HeapLayout::IsSelfForwarded(), v8::internal::anonymous_namespace{pretenuring-handler.cc}::kMinMementoCount, v8::kRelaxedLoad, v8::internal::MapWord::ToForwardingAddress(), and v8::internal::value.
Referenced by v8::internal::ConcurrentMarking::FlushPretenuringFeedback(), and v8::internal::MinorMarkSweepCollector::MarkLiveObjects().
PretenureAllocationSiteOnNextCollection()
void v8::internal::PretenuringHandler::PretenureAllocationSiteOnNextCollection (Tagged< AllocationSite > site)
Definition at line 286 of file pretenuring-handler.cc.
                                 {
  if (!allocation_sites_to_pretenure_) {
    allocation_sites_to_pretenure_.reset(
        new GlobalHandleVector<AllocationSite>(heap_));
  }
  allocation_sites_to_pretenure_->Push(site);
}
References allocation_sites_to_pretenure_, and heap_.
Referenced by v8::internal::RUNTIME_FUNCTION().
ProcessPretenuringFeedback()
void v8::internal::PretenuringHandler::ProcessPretenuringFeedback (size_t new_space_capacity_before_gc)
Definition at line 171 of file pretenuring-handler.cc.
                                               {
  // The minimum new space capacity from which allocation sites can be
  // pretenured. A too small capacity means frequent GCs. Objects thus don't get
  // a chance to die before being promoted, which may lead to wrong pretenuring
  // decisions.
  static constexpr size_t kDefaultMinNewSpaceCapacityForPretenuring =
      8192 * KB * Heap::kPointerMultiplier;
  DCHECK(heap_->tracer()->IsInAtomicPause());
  if (!v8_flags.allocation_site_pretenuring) return;
  // TODO(333906585): Adjust capacity for sticky bits.
  const size_t max_capacity = v8_flags.sticky_mark_bits
                                  ? heap_->sticky_space()->Capacity()
                                  : heap_->new_space()->MaximumCapacity();
  const size_t min_new_space_capacity_for_pretenuring =
      std::min(max_capacity, kDefaultMinNewSpaceCapacityForPretenuring);
  bool trigger_deoptimization = false;
  int tenure_decisions = 0;
  int dont_tenure_decisions = 0;
  int allocation_mementos_found = 0;
  int allocation_sites = 0;
  int active_allocation_sites = 0;
  Tagged<AllocationSite> site;
  // Step 1: Digest feedback for recorded allocation sites.
  // This is the pretenuring trigger for allocation sites that are in maybe
  // tenure state. When we switched to a large enough new space size we
  // deoptimize the code that belongs to the allocation site and derive the
  // lifetime of the allocation site.
  const bool new_space_was_above_pretenuring_threshold =
      new_space_capacity_target_capacity >=
      min_new_space_capacity_for_pretenuring;
  for (auto& site_and_count : global_pretenuring_feedback_) {
    allocation_sites++;
    site = site_and_count.first;
    // Count is always access through the site.
    DCHECK_EQ(0, site_and_count.second);
    int found_count = site->memento_found_count();
    // An entry in the storage does not imply that the count is > 0 because
    // allocation sites might have been reset due to too many objects dying
    // in old space.
    if (found_count > 0) {
      DCHECK(IsAllocationSite(site));
      active_allocation_sites++;
      allocation_mementos_found += found_count;
      if (DigestPretenuringFeedback(heap_->isolate(), site,
                                    new_space_was_above_pretenuring_threshold,
                                    new_space_capacity_target_capacity)) {
        trigger_deoptimization = true;
      }
      if (site->GetAllocationType() == AllocationType::kOld) {
        tenure_decisions++;
      } else {
        dont_tenure_decisions++;
      }
    }
  }
  // Step 2: Pretenure allocation sites for manual requests.
  if (allocation_sites_to_pretenure_) {
    while (!allocation_sites_to_pretenure_->empty()) {
      auto pretenure_site = allocation_sites_to_pretenure_->Pop();
      if (PretenureAllocationSiteManually(heap_->isolate(), pretenure_site)) {
        trigger_deoptimization = true;
      }
    }
    allocation_sites_to_pretenure_.reset();
  }
  // Step 3: Deopt maybe tenured allocation sites if necessary.
  // New space capacity was too low for pretenuring but is now above the
  // threshold. Maybe tenured allocation sites may be pretenured on the next GC.
  bool deopt_maybe_tenured = (heap_->NewSpaceTargetCapacity() >=
                              min_new_space_capacity_for_pretenuring) &&
                             !new_space_was_above_pretenuring_threshold;
  if (deopt_maybe_tenured) {
    heap_->ForeachAllocationSite(heap_->allocation_sites_list(),
                                 [&allocation_sites, &trigger_deoptimization](
                                     Tagged<AllocationSite> site) {
                                   DCHECK(IsAllocationSite(site));
                                   allocation_sites++;
                                   if (site->IsMaybeTenure()) {
                                     site->set_deopt_dependent_code(true);
                                     trigger_deoptimization = true;
                                   }
                                 });
  }
  if (trigger_deoptimization) {
    heap_->isolate()->stack_guard()->RequestDeoptMarkedAllocationSites();
  }
  if (V8_UNLIKELY(v8_flags.trace_pretenuring_statistics) &&
      (allocation_mementos_found > 0 || tenure_decisions > 0 ||
       dont_tenure_decisions > 0)) {
    PrintIsolate(
        heap_->isolate(),
        "pretenuring: threshold=%.2f deopt_maybe_tenured=%d visited_sites=%d "
        "active_sites=%d "
        "mementos=%d tenured=%d not_tenured=%d\n",
        GetPretenuringRatioThreshold(new_space_capacity_target_capacity),
        deopt_maybe_tenured ? 1 : 0, allocation_sites, active_allocation_sites,
        allocation_mementos_found, tenure_decisions, dont_tenure_decisions);
  }
  global_pretenuring_feedback_.clear();
  global_pretenuring_feedback_.reserve(kInitialFeedbackCapacity);
}
References v8::internal::Heap::allocation_sites_list(), allocation_sites_to_pretenure_, v8::internal::PagedSpaceBase::Capacity(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{pretenuring-handler.cc}::DigestPretenuringFeedback(), v8::internal::Heap::ForeachAllocationSite(), v8::internal::anonymous_namespace{pretenuring-handler.cc}::GetPretenuringRatioThreshold(), global_pretenuring_feedback_, heap_, v8::internal::Heap::isolate(), v8::internal::KB, kInitialFeedbackCapacity, v8::internal::kOld, v8::internal::Heap::kPointerMultiplier, v8::internal::NewSpace::MaximumCapacity(), v8::internal::Heap::new_space(), v8::internal::Heap::NewSpaceTargetCapacity(), v8::internal::anonymous_namespace{pretenuring-handler.cc}::PretenureAllocationSiteManually(), v8::internal::PrintIsolate(), v8::internal::Isolate::stack_guard(), v8::internal::Heap::sticky_space(), v8::internal::Heap::tracer(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Heap::PerformGarbageCollection().
RemoveAllocationSitePretenuringFeedback()
void v8::internal::PretenuringHandler::RemoveAllocationSitePretenuringFeedback (Tagged< AllocationSite > site)
Definition at line 166 of file pretenuring-handler.cc.
                                 {
  global_pretenuring_feedback_.erase(site);
}
References global_pretenuring_feedback_.
reset()
void v8::internal::PretenuringHandler::reset ()
Definition at line 295 of file pretenuring-handler.cc.
{ allocation_sites_to_pretenure_.reset(); }
References allocation_sites_to_pretenure_.
Referenced by v8::internal::Heap::TearDown().
UpdateAllocationSite()
void v8::internal::PretenuringHandler::UpdateAllocationSite (Heap * heap, Tagged< Map > map, Tagged< HeapObject > object, int object_size, PretenuringFeedbackMap * pretenuring_feedback) [inline], [static]
Definition at line 22 of file pretenuring-handler-inl.h.
                                                  {
  DCHECK_NE(pretenuring_feedback,
            &heap->pretenuring_handler()->global_pretenuring_feedback_);
#ifdef DEBUG
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  // MemoryChunk::IsToPage() is not available with sticky mark-bits.
  DCHECK_IMPLIES(v8_flags.sticky_mark_bits || chunk->IsToPage(),
                 v8_flags.minor_ms);
  DCHECK_IMPLIES(!v8_flags.minor_ms && !HeapLayout::InYoungGeneration(object),
                 chunk->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION));
#endif
  if (V8_UNLIKELY(!v8_flags.allocation_site_pretenuring) ||
      !AllocationSite::CanTrack(map->instance_type())) {
    return;
  }
  Tagged<AllocationMemento> memento_candidate =
      FindAllocationMemento<kForGC>(heap, map, object, object_size);
  if (memento_candidate.is_null()) {
    return;
  }
  DCHECK(IsJSObjectMap(map));
  // Entering cached feedback is used in the parallel case. We are not allowed
  // to dereference the allocation site and rather have to postpone all checks
  // till actually merging the data.
  Address key = memento_candidate->GetAllocationSiteUnchecked();
  (*pretenuring_feedback)[UncheckedCast<AllocationSite>(Tagged<Object>(key))]++;
}
References v8::internal::AllocationSite::CanTrack(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsToPage(), v8::internal::key, v8::internal::MemoryChunk::PAGE_NEW_OLD_PROMOTION, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Scavenger::MigrateObject(), v8::internal::EvacuateNewSpaceVisitor::Visit(), v8::internal::EvacuateNewToOldSpacePageVisitor::Visit(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitJSObjectSubclass().
Member Data Documentation
allocation_sites_to_pretenure_
std::unique_ptr<GlobalHandleVector<AllocationSite> > v8::internal::PretenuringHandler::allocation_sites_to_pretenure_ [private]
Definition at line 94 of file pretenuring-handler.h.
Referenced by PretenureAllocationSiteOnNextCollection(), ProcessPretenuringFeedback(), and reset().
global_pretenuring_feedback_
PretenuringFeedbackMap v8::internal::PretenuringHandler::global_pretenuring_feedback_ [private]
Definition at line 91 of file pretenuring-handler.h.
Referenced by HasPretenuringFeedback(), MergeAllocationSitePretenuringFeedback(), ProcessPretenuringFeedback(), and RemoveAllocationSitePretenuringFeedback().
heap_
Heap* const v8::internal::PretenuringHandler::heap_ [private]
Definition at line 84 of file pretenuring-handler.h.
Referenced by MergeAllocationSitePretenuringFeedback(), PretenureAllocationSiteOnNextCollection(), and ProcessPretenuringFeedback().
kInitialFeedbackCapacity
constexpr int v8::internal::PretenuringHandler::kInitialFeedbackCapacity = 256 [static], [constexpr]
Definition at line 23 of file pretenuring-handler.h.
Referenced by ProcessPretenuringFeedback(), and v8::internal::MinorMarkSweepCollector::StartMarking().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/pretenuring-handler.h
/mnt/V8SourceCode/src/heap/pretenuring-handler-inl.h
/mnt/V8SourceCode/src/heap/pretenuring-handler.cc