v8::internal::SourceTextModuleInfo Class Reference
#include <source-text-module.h>
Public Member Functions
Tagged< FixedArray > module_requests () const
Tagged< FixedArray > special_exports () const
Tagged< FixedArray > regular_exports () const
Tagged< FixedArray > regular_imports () const
Tagged< FixedArray > namespace_imports () const
int RegularExportCount () const
Tagged< String > RegularExportLocalName (int i) const
int RegularExportCellIndex (int i) const
Tagged< FixedArray > RegularExportExportNames (int i) const
bool Equals (Tagged< SourceTextModuleInfo > other) const
Static Public Member Functions
template<typename IsolateT >
static DirectHandle< SourceTextModuleInfo > New (IsolateT *isolate, Zone *zone, SourceTextModuleDescriptor *descr)
Private Types
enum {
kModuleRequestsIndex
, kSpecialExportsIndex
, kRegularExportsIndex
, kNamespaceImportsIndex
,
kRegularImportsIndex
, kLength
 }
enum { kRegularExportLocalNameOffset
, kRegularExportCellIndexOffset
, kRegularExportExportNamesOffset
, kRegularExportLength
 }
Friends
template<typename Impl >
class FactoryBase
class SourceTextModuleDescriptor
Additional Inherited Members
Detailed Description
Definition at line 238 of file source-text-module.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
kModuleRequestsIndex
kSpecialExportsIndex
kRegularExportsIndex
kNamespaceImportsIndex
kRegularImportsIndex
kLength
Definition at line 262 of file source-text-module.h.
       {
    kModuleRequestsIndex,
    kSpecialExportsIndex,
    kRegularExportsIndex,
    kNamespaceImportsIndex,
    kRegularImportsIndex,
    kLength
  };
anonymous enum
anonymous enum [private]
Enumerator
kRegularExportLocalNameOffset
kRegularExportCellIndexOffset
kRegularExportExportNamesOffset
kRegularExportLength
Definition at line 270 of file source-text-module.h.
       {
    kRegularExportLocalNameOffset,
    kRegularExportCellIndexOffset,
    kRegularExportExportNamesOffset,
    kRegularExportLength
  };
Member Function Documentation
Equals()
bool v8::internal::SourceTextModuleInfo::Equals (Tagged< SourceTextModuleInfo > other) const [inline]
Definition at line 80 of file module-inl.h.
                                                                          {
  return regular_exports() == other->regular_exports() &&
         regular_imports() == other->regular_imports() &&
         special_exports() == other->special_exports() &&
         namespace_imports() == other->namespace_imports() &&
         module_requests() == other->module_requests();
}
References module_requests(), namespace_imports(), regular_exports(), regular_imports(), and special_exports().
module_requests()
Tagged< FixedArray > v8::internal::SourceTextModuleInfo::module_requests () const [inline]
Definition at line 59 of file module-inl.h.
                                                               {
  return Cast<FixedArray>(get(kModuleRequestsIndex));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and kModuleRequestsIndex.
Referenced by Equals(), and New().
namespace_imports()
Tagged< FixedArray > v8::internal::SourceTextModuleInfo::namespace_imports () const [inline]
Definition at line 75 of file module-inl.h.
                                                                 {
  return Cast<FixedArray>(get(kNamespaceImportsIndex));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and kNamespaceImportsIndex.
Referenced by Equals(), and New().
New()
template<typename IsolateT >
template DirectHandle< SourceTextModuleInfo > v8::internal::SourceTextModuleInfo::New (IsolateT * isolate, Zone * zone, SourceTextModuleDescriptor * descr) [static]
Definition at line 1252 of file scope-info.cc.
                                                                      {
  // Serialize module requests.
  int size = static_cast<int>(descr->module_requests().size());
  DirectHandle<FixedArray> module_requests =
      isolate->factory()->NewFixedArray(size, AllocationType::kOld);
  for (const auto& elem : descr->module_requests()) {
    DirectHandle<ModuleRequest> serialized_module_request =
        elem->Serialize(isolate);
    module_requests->set(elem->index(), *serialized_module_request);
  }
  // Serialize special exports.
  DirectHandle<FixedArray> special_exports = isolate->factory()->NewFixedArray(
      static_cast<int>(descr->special_exports().size()), AllocationType::kOld);
  {
    int i = 0;
    for (auto entry : descr->special_exports()) {
      DirectHandle<SourceTextModuleInfoEntry> serialized_entry =
          entry->Serialize(isolate);
      special_exports->set(i++, *serialized_entry);
    }
  }
  // Serialize namespace imports.
  DirectHandle<FixedArray> namespace_imports =
      isolate->factory()->NewFixedArray(
          static_cast<int>(descr->namespace_imports().size()),
          AllocationType::kOld);
  {
    int i = 0;
    for (auto entry : descr->namespace_imports()) {
      DirectHandle<SourceTextModuleInfoEntry> serialized_entry =
          entry->Serialize(isolate);
      namespace_imports->set(i++, *serialized_entry);
    }
  }
  // Serialize regular exports.
  DirectHandle<FixedArray> regular_exports =
      descr->SerializeRegularExports(isolate, zone);
  // Serialize regular imports.
  DirectHandle<FixedArray> regular_imports = isolate->factory()->NewFixedArray(
      static_cast<int>(descr->regular_imports().size()), AllocationType::kOld);
  {
    int i = 0;
    for (const auto& elem : descr->regular_imports()) {
      DirectHandle<SourceTextModuleInfoEntry> serialized_entry =
          elem.second->Serialize(isolate);
      regular_imports->set(i++, *serialized_entry);
    }
  }
  DirectHandle<SourceTextModuleInfo> result =
      isolate->factory()->NewSourceTextModuleInfo();
  result->set(kModuleRequestsIndex, *module_requests);
  result->set(kSpecialExportsIndex, *special_exports);
  result->set(kRegularExportsIndex, *regular_exports);
  result->set(kNamespaceImportsIndex, *namespace_imports);
  result->set(kRegularImportsIndex, *regular_imports);
  return result;
}
References kModuleRequestsIndex, kNamespaceImportsIndex, v8::internal::kOld, kRegularExportsIndex, kRegularImportsIndex, kSpecialExportsIndex, v8::internal::SourceTextModuleDescriptor::module_requests(), module_requests(), v8::internal::SourceTextModuleDescriptor::namespace_imports(), namespace_imports(), regular_exports(), v8::internal::SourceTextModuleDescriptor::regular_imports(), regular_imports(), v8::base::internal::result, v8::internal::SourceTextModuleDescriptor::SerializeRegularExports(), size(), v8::internal::SourceTextModuleDescriptor::special_exports(), and special_exports().
Referenced by v8::internal::ScopeInfo::Create().
regular_exports()
Tagged< FixedArray > v8::internal::SourceTextModuleInfo::regular_exports () const [inline]
Definition at line 67 of file module-inl.h.
                                                               {
  return Cast<FixedArray>(get(kRegularExportsIndex));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and kRegularExportsIndex.
Referenced by Equals(), New(), RegularExportCellIndex(), RegularExportCount(), RegularExportExportNames(), and RegularExportLocalName().
regular_imports()
Tagged< FixedArray > v8::internal::SourceTextModuleInfo::regular_imports () const [inline]
Definition at line 71 of file module-inl.h.
                                                               {
  return Cast<FixedArray>(get(kRegularImportsIndex));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and kRegularImportsIndex.
Referenced by Equals(), and New().
RegularExportCellIndex()
int v8::internal::SourceTextModuleInfo::RegularExportCellIndex (int i) const
Definition at line 1331 of file scope-info.cc.
                                                            {
  return Smi::ToInt(regular_exports()->get(i * kRegularExportLength +
                                           kRegularExportCellIndexOffset));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kRegularExportCellIndexOffset, kRegularExportLength, regular_exports(), and v8::internal::Smi::ToInt().
RegularExportCount()
int v8::internal::SourceTextModuleInfo::RegularExportCount () const
Definition at line 1321 of file scope-info.cc.
                                                   {
  DCHECK_EQ(regular_exports()->length() % kRegularExportLength, 0);
  return regular_exports()->length() / kRegularExportLength;
}
References DCHECK_EQ, kRegularExportLength, v8::internal::length, and regular_exports().
RegularExportExportNames()
Tagged< FixedArray > v8::internal::SourceTextModuleInfo::RegularExportExportNames (int i) const
Definition at line 1336 of file scope-info.cc.
                                                                             {
  return Cast<FixedArray>(regular_exports()->get(
      i * kRegularExportLength + kRegularExportExportNamesOffset));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kRegularExportExportNamesOffset, kRegularExportLength, and regular_exports().
RegularExportLocalName()
Tagged< String > v8::internal::SourceTextModuleInfo::RegularExportLocalName (int i) const
Definition at line 1326 of file scope-info.cc.
                                                                       {
  return Cast<String>(regular_exports()->get(i * kRegularExportLength +
                                             kRegularExportLocalNameOffset));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), kRegularExportLength, kRegularExportLocalNameOffset, and regular_exports().
special_exports()
Tagged< FixedArray > v8::internal::SourceTextModuleInfo::special_exports () const [inline]
Definition at line 63 of file module-inl.h.
                                                               {
  return Cast<FixedArray>(get(kSpecialExportsIndex));
}
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and kSpecialExportsIndex.
Referenced by Equals(), and New().
Friends And Related Function Documentation
FactoryBase
template<typename Impl >
friend class FactoryBase [friend]
Definition at line 260 of file source-text-module.h.
SourceTextModuleDescriptor
friend class SourceTextModuleDescriptor [friend]
Definition at line 261 of file source-text-module.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/source-text-module.h
/mnt/V8SourceCode/src/objects/module-inl.h
/mnt/V8SourceCode/src/objects/scope-info.cc