v8::internal::StringToIntHelper Class Reference
Public Member Functions
StringToIntHelper (DirectHandle< String > subject, int radix)
StringToIntHelper (const uint8_t *subject, int radix, size_t length)
StringToIntHelper (const base::uc16 *subject, int radix, size_t length)
StringToIntHelper (DirectHandle< String > subject)
StringToIntHelper (const uint8_t *subject, size_t length)
virtual ~StringToIntHelper ()=default
Protected Member Functions
virtual void ParseOneByte (const uint8_t *start)=0
virtual void ParseTwoByte (const base::uc16 *start)=0
void ParseInt ()
void set_allow_binary_and_octal_prefixes ()
void set_disallow_trailing_junk ()
bool allow_trailing_junk ()
bool IsOneByte () const
base::Vector< const uint8_t > GetOneByteVector (const DisallowGarbageCollection &no_gc)
base::Vector< const base::uc16 > GetTwoByteVector (const DisallowGarbageCollection &no_gc)
int radix ()
size_t cursor ()
size_t length ()
bool negative ()
Sign sign ()
State state ()
void set_state (State state)
Private Member Functions
template<class Char >
void DetectRadixInternal (const Char *current, size_t length)
Private Attributes
DirectHandle< String > subject_
const uint8_t * raw_one_byte_subject_ = nullptr
const base::uc16 * raw_two_byte_subject_ = nullptr
int radix_ = 0
size_t cursor_ = 0
size_t length_ = 0
Sign sign_ = Sign::kNone
bool leading_zero_ = false
bool allow_binary_and_octal_prefixes_ = false
bool allow_trailing_junk_ = true
State state_ = State::kRunning
Detailed Description
Definition at line 489 of file conversions.cc.
Constructor & Destructor Documentation
StringToIntHelper() [1/5]
v8::internal::StringToIntHelper::StringToIntHelper (DirectHandle< String > subject, int radix) [inline]
Definition at line 491 of file conversions.cc.
      : subject_(subject), radix_(radix) {
    DCHECK(subject->IsFlat());
  }
References v8::internal::DCHECK().
StringToIntHelper() [2/5]
v8::internal::StringToIntHelper::StringToIntHelper (const uint8_t * subject, int radix, size_t length) [inline]
Definition at line 497 of file conversions.cc.
      : raw_one_byte_subject_(subject), radix_(radix), length_(length) {}
StringToIntHelper() [3/5]
v8::internal::StringToIntHelper::StringToIntHelper (const base::uc16 * subject, int radix, size_t length) [inline]
Definition at line 500 of file conversions.cc.
      : raw_two_byte_subject_(subject), radix_(radix), length_(length) {}
StringToIntHelper() [4/5]
v8::internal::StringToIntHelper::StringToIntHelper (DirectHandle< String > subject) [inline], [explicit]
Definition at line 504 of file conversions.cc.
                                                           : subject_(subject) {
    DCHECK(subject->IsFlat());
  }
References v8::internal::DCHECK().
StringToIntHelper() [5/5]
v8::internal::StringToIntHelper::StringToIntHelper (const uint8_t * subject, size_t length) [inline]
Definition at line 510 of file conversions.cc.
      : raw_one_byte_subject_(subject), length_(length) {}
 StringToIntHelper()
virtual v8::internal::StringToIntHelper::~StringToIntHelper () [virtual], [default]
Member Function Documentation
allow_trailing_junk()
bool v8::internal::StringToIntHelper::allow_trailing_junk () [inline], [protected]
Definition at line 528 of file conversions.cc.
{ return allow_trailing_junk_; }
References allow_trailing_junk_.
Referenced by v8::internal::NumberParseIntHelper::HandleGenericCase(), v8::internal::NumberParseIntHelper::HandlePowerOfTwoCase(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
cursor()
size_t v8::internal::StringToIntHelper::cursor () [inline], [protected]
Definition at line 553 of file conversions.cc.
{ return cursor_; }
References cursor_.
Referenced by v8::internal::NumberParseIntHelper::ParseInternal(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
DetectRadixInternal()
template<class Char >
void v8::internal::StringToIntHelper::DetectRadixInternal (const Char * current, size_t length) [private]
Definition at line 593 of file conversions.cc.
                                                           {
  const Char* start = current;
  length_ = length;
  const Char* end = start + length;
  if (!AdvanceToNonspace(&current, end)) {
    return set_state(State::kEmpty);
  }
  if (*current == '+') {
    // Ignore leading sign; skip following spaces.
    ++current;
    if (current == end) {
      return set_state(State::kJunk);
    }
    sign_ = Sign::kPositive;
  } else if (*current == '-') {
    ++current;
    if (current == end) {
      return set_state(State::kJunk);
    }
    sign_ = Sign::kNegative;
  }
  if (radix_ == 0) {
    // Radix detection.
    radix_ = 10;
    if (*current == '0') {
      ++current;
      if (current == end) return set_state(State::kZero);
      if (*current == 'x' || *current == 'X') {
        radix_ = 16;
        ++current;
        if (current == end) return set_state(State::kJunk);
      } else if (allow_binary_and_octal_prefixes_ &&
                 (*current == 'o' || *current == 'O')) {
        radix_ = 8;
        ++current;
        if (current == end) return set_state(State::kJunk);
      } else if (allow_binary_and_octal_prefixes_ &&
                 (*current == 'b' || *current == 'B')) {
        radix_ = 2;
        ++current;
        if (current == end) return set_state(State::kJunk);
      } else {
        leading_zero_ = true;
      }
    }
  } else if (radix_ == 16) {
    if (*current == '0') {
      // Allow "0x" prefix.
      ++current;
      if (current == end) return set_state(State::kZero);
      if (*current == 'x' || *current == 'X') {
        ++current;
        if (current == end) return set_state(State::kJunk);
      } else {
        leading_zero_ = true;
      }
    }
  }
  // Skip leading zeros.
  while (*current == '0') {
    leading_zero_ = true;
    ++current;
    if (current == end) return set_state(State::kZero);
  }
  // Detect leading zeros with junk after them, if allowed.
  if (leading_zero_ && allow_trailing_junk_ && !isDigit(*current, radix_)) {
    return set_state(State::kZero);
  }
  if (!leading_zero_ && !isDigit(*current, radix_)) {
    return set_state(State::kJunk);
  }
  DCHECK(radix_ >= 2 && radix_ <= 36);
  cursor_ = current - start;
}
References v8::internal::AdvanceToNonspace(), allow_binary_and_octal_prefixes_, allow_trailing_junk_, cursor_, v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::isDigit(), v8::internal::swiss_table::kEmpty, v8::internal::compiler::kNegative, v8::internal::kZero, leading_zero_, length(), length_, radix_, set_state(), and sign_.
Referenced by ParseInt().
GetOneByteVector()
base::Vector<const uint8_t> v8::internal::StringToIntHelper::GetOneByteVector (const DisallowGarbageCollection & no_gc) [inline], [protected]
Definition at line 536 of file conversions.cc.
                                              {
    if (raw_one_byte_subject_ != nullptr) {
      return base::Vector<const uint8_t>(raw_one_byte_subject_, length_);
    }
    return subject_->GetFlatContent(no_gc).ToOneByteVector();
  }
References length_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, raw_one_byte_subject_, and subject_.
Referenced by ParseInt().
GetTwoByteVector()
base::Vector<const base::uc16> v8::internal::StringToIntHelper::GetTwoByteVector (const DisallowGarbageCollection & no_gc) [inline], [protected]
Definition at line 544 of file conversions.cc.
                                              {
    if (raw_two_byte_subject_ != nullptr) {
      return base::Vector<const base::uc16>(raw_two_byte_subject_, length_);
    }
    return subject_->GetFlatContent(no_gc).ToUC16Vector();
  }
References length_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, raw_two_byte_subject_, and subject_.
Referenced by ParseInt().
IsOneByte()
bool v8::internal::StringToIntHelper::IsOneByte () const [inline], [protected]
Definition at line 530 of file conversions.cc.
                         {
    if (raw_two_byte_subject_ != nullptr) return false;
    return raw_one_byte_subject_ != nullptr ||
           String::IsOneByteRepresentationUnderneath(*subject_);
  }
References v8::internal::String::IsOneByteRepresentationUnderneath(), raw_one_byte_subject_, raw_two_byte_subject_, and subject_.
Referenced by ParseInt().
length()
size_t v8::internal::StringToIntHelper::length () [inline], [protected]
Definition at line 554 of file conversions.cc.
{ return length_; }
References length_.
Referenced by DetectRadixInternal(), v8::internal::NumberParseIntHelper::ParseInternal(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
negative()
bool v8::internal::StringToIntHelper::negative () [inline], [protected]
Definition at line 555 of file conversions.cc.
{ return sign_ == Sign::kNegative; }
References v8::internal::compiler::kNegative, and sign_.
Referenced by v8::internal::NumberParseIntHelper::GetResult(), v8::internal::StringToBigIntHelper< IsolateT >::GetResult(), and v8::internal::NumberParseIntHelper::HandlePowerOfTwoCase().
ParseInt()
void v8::internal::StringToIntHelper::ParseInt () [protected]
Definition at line 577 of file conversions.cc.
                                 {
  DisallowGarbageCollection no_gc;
  if (IsOneByte()) {
    base::Vector<const uint8_t> vector = GetOneByteVector(no_gc);
    DetectRadixInternal(vector.begin(), vector.size());
    if (state_ != State::kRunning) return;
    ParseOneByte(vector.begin());
  } else {
    base::Vector<const base::uc16> vector = GetTwoByteVector(no_gc);
    DetectRadixInternal(vector.begin(), vector.size());
    if (state_ != State::kRunning) return;
    ParseTwoByte(vector.begin());
  }
}
References v8::base::Vector< T >::begin(), DetectRadixInternal(), GetOneByteVector(), GetTwoByteVector(), IsOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ParseOneByte(), ParseTwoByte(), v8::base::Vector< T >::size(), and state_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), v8::internal::NumberParseIntHelper::GetResult(), and v8::internal::StringToBigIntHelper< IsolateT >::GetResult().
ParseOneByte()
virtual void v8::internal::StringToIntHelper::ParseOneByte (const uint8_t * start) [protected], [pure virtual]
Implemented in v8::internal::StringToBigIntHelper< IsolateT >, and v8::internal::NumberParseIntHelper.
Referenced by ParseInt().
ParseTwoByte()
virtual void v8::internal::StringToIntHelper::ParseTwoByte (const base::uc16 * start) [protected], [pure virtual]
Implemented in v8::internal::StringToBigIntHelper< IsolateT >, and v8::internal::NumberParseIntHelper.
Referenced by ParseInt().
radix()
int v8::internal::StringToIntHelper::radix () [inline], [protected]
Definition at line 552 of file conversions.cc.
{ return radix_; }
References radix_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::GetResult(), v8::internal::NumberParseIntHelper::HandleGenericCase(), v8::internal::NumberParseIntHelper::HandlePowerOfTwoCase(), v8::internal::NumberParseIntHelper::ParseInternal(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
set_allow_binary_and_octal_prefixes()
void v8::internal::StringToIntHelper::set_allow_binary_and_octal_prefixes () [inline], [protected]
Definition at line 524 of file conversions.cc.
                                             {
    allow_binary_and_octal_prefixes_ = true;
  }
References allow_binary_and_octal_prefixes_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::StringToBigIntHelper().
set_disallow_trailing_junk()
void v8::internal::StringToIntHelper::set_disallow_trailing_junk () [inline], [protected]
Definition at line 527 of file conversions.cc.
{ allow_trailing_junk_ = false; }
References allow_trailing_junk_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::StringToBigIntHelper().
set_state()
void v8::internal::StringToIntHelper::set_state (State state) [inline], [protected]
Definition at line 558 of file conversions.cc.
{ state_ = state; }
References state(), and state_.
Referenced by DetectRadixInternal(), v8::internal::StringToBigIntHelper< IsolateT >::GetResult(), v8::internal::NumberParseIntHelper::HandleBaseTenCase(), v8::internal::NumberParseIntHelper::HandleGenericCase(), v8::internal::NumberParseIntHelper::ParseInternal(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
sign()
Sign v8::internal::StringToIntHelper::sign () [inline], [protected]
Definition at line 556 of file conversions.cc.
{ return sign_; }
References sign_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::GetResult().
state()
State v8::internal::StringToIntHelper::state () [inline], [protected]
Definition at line 557 of file conversions.cc.
{ return state_; }
References state_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), v8::internal::NumberParseIntHelper::GetResult(), v8::internal::StringToBigIntHelper< IsolateT >::GetResult(), and set_state().
Member Data Documentation
allow_binary_and_octal_prefixes_
bool v8::internal::StringToIntHelper::allow_binary_and_octal_prefixes_ = false [private]
Definition at line 572 of file conversions.cc.
Referenced by DetectRadixInternal(), and set_allow_binary_and_octal_prefixes().
allow_trailing_junk_
bool v8::internal::StringToIntHelper::allow_trailing_junk_ = true [private]
Definition at line 573 of file conversions.cc.
Referenced by allow_trailing_junk(), DetectRadixInternal(), and set_disallow_trailing_junk().
cursor_
size_t v8::internal::StringToIntHelper::cursor_ = 0 [private]
Definition at line 568 of file conversions.cc.
Referenced by cursor(), and DetectRadixInternal().
leading_zero_
bool v8::internal::StringToIntHelper::leading_zero_ = false [private]
Definition at line 571 of file conversions.cc.
Referenced by DetectRadixInternal().
length_
size_t v8::internal::StringToIntHelper::length_ = 0 [private]
Definition at line 569 of file conversions.cc.
Referenced by DetectRadixInternal(), GetOneByteVector(), GetTwoByteVector(), and length().
radix_
int v8::internal::StringToIntHelper::radix_ = 0 [private]
Definition at line 567 of file conversions.cc.
Referenced by DetectRadixInternal(), and radix().
raw_one_byte_subject_
const uint8_t* v8::internal::StringToIntHelper::raw_one_byte_subject_ = nullptr [private]
Definition at line 565 of file conversions.cc.
Referenced by GetOneByteVector(), and IsOneByte().
raw_two_byte_subject_
const base::uc16* v8::internal::StringToIntHelper::raw_two_byte_subject_ = nullptr [private]
Definition at line 566 of file conversions.cc.
Referenced by GetTwoByteVector(), and IsOneByte().
sign_
Sign v8::internal::StringToIntHelper::sign_ = Sign::kNone [private]
Definition at line 570 of file conversions.cc.
Referenced by DetectRadixInternal(), negative(), and sign().
state_
State v8::internal::StringToIntHelper::state_ = State::kRunning [private]
Definition at line 574 of file conversions.cc.
Referenced by ParseInt(), set_state(), and state().
subject_
DirectHandle<String> v8::internal::StringToIntHelper::subject_ [private]
Definition at line 564 of file conversions.cc.
Referenced by GetOneByteVector(), GetTwoByteVector(), and IsOneByte().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/numbers/conversions.cc