v8::internal::compiler::RiscvOperandGenerator Class Reference
#include <instruction-selector-riscv.h>
Public Member Functions
RiscvOperandGenerator (InstructionSelector *selector)
InstructionOperand UseOperand (OpIndex node, InstructionCode opcode)
InstructionOperand UseRegisterOrImmediateZero (OpIndex node)
bool IsIntegerConstant (OpIndex node)
bool IsIntegerConstant (OptionalOpIndex node)
std::optional< int64_t > GetOptionalIntegerConstant (OpIndex operation)
bool CanBeZero (OpIndex node)
bool CanBeImmediate (OpIndex node, InstructionCode mode)
bool CanBeImmediate (int64_t value, InstructionCode opcode)
Private Member Functions
bool ImmediateFitsAddrMode1Instruction (int32_t imm) const
Additional Inherited Members
Detailed Description
Definition at line 34 of file instruction-selector-riscv.h.
Constructor & Destructor Documentation
RiscvOperandGenerator()
v8::internal::compiler::RiscvOperandGenerator::RiscvOperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 36 of file instruction-selector-riscv.h.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeImmediate() [1/2]
bool v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate (int64_t value, InstructionCode opcode)
Definition at line 21 of file instruction-selector-riscv32.cc.
                                                                   {
  switch (ArchOpcodeField::decode(opcode)) {
    case kRiscvShl32:
    case kRiscvSar32:
    case kRiscvShr32:
      return is_uint5(value);
    case kRiscvAdd32:
    case kRiscvAnd32:
    case kRiscvAnd:
    case kRiscvOr32:
    case kRiscvOr:
    case kRiscvTst32:
    case kRiscvXor:
      return is_int12(value);
    case kRiscvLb:
    case kRiscvLbu:
    case kRiscvSb:
    case kRiscvLh:
    case kRiscvLhu:
    case kRiscvSh:
    case kRiscvLw:
    case kRiscvSw:
    case kRiscvLoadFloat:
    case kRiscvStoreFloat:
    case kRiscvLoadDouble:
    case kRiscvStoreDouble:
      return is_int32(value);
    default:
      return is_int12(value);
  }
}
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::value.
CanBeImmediate() [2/2]
bool v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate (OpIndex node, InstructionCode mode) [inline]
Definition at line 79 of file instruction-selector-riscv.h.
                                                          {
    const ConstantOp* constant = selector()->Get(node).TryCast<ConstantOp>();
    if (!constant) return false;
    if (constant->kind == ConstantOp::Kind::kCompressedHeapObject) {
      if (!COMPRESS_POINTERS_BOOL) return false;
      // For builtin code we need static roots
      if (selector()->isolate()->bootstrapper() && !V8_STATIC_ROOTS_BOOL) {
        return false;
      }
      const RootsTable& roots_table = selector()->isolate()->roots_table();
      RootIndex root_index;
      Handle<HeapObject> value = constant->handle();
      if (roots_table.IsRootHandle(value, &root_index)) {
        if (!RootsTable::IsReadOnly(root_index)) return false;
        return CanBeImmediate(MacroAssemblerBase::ReadOnlyRootPtr(
                                  root_index, selector()->isolate()),
                              mode);
      }
      return false;
    }
    int64_t value;
    return selector()->MatchSignedIntegralConstant(node, &value) &&
           CanBeImmediate(value, mode);
  }
References v8::internal::compiler::CanBeImmediate(), COMPRESS_POINTERS_BOOL, v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::RootsTable::IsReadOnly(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, mode(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::compiler::turboshaft::Operation::TryCast(), V8_STATIC_ROOTS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::EmitS128Load(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), and v8::internal::compiler::VisitWordCompare().
CanBeZero()
bool v8::internal::compiler::RiscvOperandGenerator::CanBeZero (OpIndex node) [inline]
Definition at line 77 of file instruction-selector-riscv.h.
{ return MatchZero(node); }
Referenced by v8::internal::compiler::VisitWordCompare().
GetOptionalIntegerConstant()
std::optional<int64_t> v8::internal::compiler::RiscvOperandGenerator::GetOptionalIntegerConstant (OpIndex operation) [inline]
Definition at line 70 of file instruction-selector-riscv.h.
                                                                     {
    if (int64_t constant; MatchSignedIntegralConstant(operation, &constant)) {
      return constant;
    }
    return std::nullopt;
  }
ImmediateFitsAddrMode1Instruction()
bool v8::internal::compiler::RiscvOperandGenerator::ImmediateFitsAddrMode1Instruction (int32_t imm) const [inline], [private]
Definition at line 108 of file instruction-selector-riscv.h.
                                                            {
    TRACE("UNIMPLEMENTED instr_sel: %s at line %d\n", __FUNCTION__, __LINE__);
    return false;
  }
References v8::internal::TRACE().
IsIntegerConstant() [1/2]
bool v8::internal::compiler::RiscvOperandGenerator::IsIntegerConstant (OpIndex node) [inline]
Definition at line 61 of file instruction-selector-riscv.h.
                                       {
    int64_t unused;
    return selector()->MatchSignedIntegralConstant(node, &unused);
  }
IsIntegerConstant() [2/2]
bool v8::internal::compiler::RiscvOperandGenerator::IsIntegerConstant (OptionalOpIndex node) [inline]
Definition at line 66 of file instruction-selector-riscv.h.
                                               {
    return node.has_value() && IsIntegerConstant(node.value());
  }
References v8::internal::compiler::turboshaft::OptionalOpIndex::has_value(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
UseOperand()
InstructionOperand v8::internal::compiler::RiscvOperandGenerator::UseOperand (OpIndex node, InstructionCode opcode) [inline]
Definition at line 39 of file instruction-selector-riscv.h.
                                                                      {
    if (CanBeImmediate(node, opcode)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::CanBeImmediate(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::VisitBinop(), and v8::internal::compiler::VisitRRO().
UseRegisterOrImmediateZero()
InstructionOperand v8::internal::compiler::RiscvOperandGenerator::UseRegisterOrImmediateZero (OpIndex node) [inline]
Definition at line 48 of file instruction-selector-riscv.h.
                                                              {
    if (const ConstantOp* constant =
            selector()->Get(node).TryCast<ConstantOp>()) {
      if ((constant->IsIntegral() && constant->integral() == 0) ||
          (constant->kind == ConstantOp::Kind::kFloat32 &&
           constant->float32().get_bits() == 0) ||
          (constant->kind == ConstantOp::Kind::kFloat64 &&
           constant->float64().get_bits() == 0))
        return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::VisitBinop(), and v8::internal::compiler::VisitWordCompare().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv.h
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv32.cc
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv64.cc