v8::internal::ValueHelper Class Reference
#include <v8-internal.h>
Public Types
using InternalRepresentationType = internal::Address *
Static Public Member Functions
template<typename T >
static bool IsEmpty (T *value)
template<template< typename T, typename... Ms > typename H, typename T , typename... Ms>
static T * HandleAsValue (const H< T, Ms... > &handle)
template<typename T >
static Address ValueAsAddress (const T *value)
template<typename T , bool check_null = true, typename S >
static T * SlotAsValue (S *slot)
template<typename T >
static InternalRepresentationType ValueAsRepr (const T *value)
template<typename T >
static T * ReprAsValue (InternalRepresentationType repr)
Static Public Attributes
static constexpr InternalRepresentationType kEmpty = nullptr
Detailed Description
Definition at line 1662 of file v8-internal.h.
Member Typedef Documentation
InternalRepresentationType
using v8::internal::ValueHelper::InternalRepresentationType = internal::Address*
Definition at line 1676 of file v8-internal.h.
Member Function Documentation
HandleAsValue()
template<template< typename T, typename... Ms > typename H, typename T , typename... Ms>
static T* v8::internal::ValueHelper::HandleAsValue (const H< T, Ms... > & handle) [inline], [static]
Definition at line 1690 of file v8-internal.h.
                                                               {
    return handle.template value<T>();
  }
References v8::internal::handle().
Referenced by v8::Shell::ExecuteModule().
IsEmpty()
template<typename T >
static bool v8::internal::ValueHelper::IsEmpty (T * value) [inline], [static]
Definition at line 1681 of file v8-internal.h.
                                          {
    return ValueAsRepr(value) == kEmpty;
  }
References kEmpty, v8::internal::value, and ValueAsRepr().
Referenced by v8::LocalBase< T >::New(), and v8::PersistentBase< T >::New().
ReprAsValue()
template<typename T >
static T* v8::internal::ValueHelper::ReprAsValue (InternalRepresentationType repr) [inline], [static]
Definition at line 1738 of file v8-internal.h.
                                                                   {
    return reinterpret_cast<T*>(repr);
  }
SlotAsValue()
template<typename T , bool check_null = true, typename S >
static T* v8::internal::ValueHelper::SlotAsValue (S * slot) [inline], [static]
Definition at line 1727 of file v8-internal.h.
                                           {
    return reinterpret_cast<T*>(slot);
  }
ValueAsAddress()
template<typename T >
static Address v8::internal::ValueHelper::ValueAsAddress (const T * value) [inline], [static]
Definition at line 1722 of file v8-internal.h.
                                                          {
    return *reinterpret_cast<const Address*>(value);
  }
References v8::internal::value.
Referenced by v8::SnapshotCreator::AddData(), v8::Context::GetAlignedPointerFromEmbedderData(), v8::Object::GetAlignedPointerFromInternalField(), v8::Context::GetEmbedderData(), v8::String::GetExternalStringResource(), v8::String::GetExternalStringResourceBase(), v8::Object::GetInternalField(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsValidApiObject(), v8::TypecheckWitness::Matches(), v8::LocalBase< T >::New(), v8::PersistentBase< T >::New(), v8::BasicTracedReference< T >::NewFromNonEmptyValue(), v8::Value::QuickIsNull(), v8::Value::QuickIsNullOrUndefined(), v8::Value::QuickIsString(), v8::Value::QuickIsUndefined(), v8::Object::Unwrap(), and v8::Object::Wrap().
ValueAsRepr()
template<typename T >
static InternalRepresentationType v8::internal::ValueHelper::ValueAsRepr (const T * value) [inline], [static]
Definition at line 1732 of file v8-internal.h.
                                                                          {
    return const_cast<InternalRepresentationType>(
        reinterpret_cast<const Address*>(value));
  }
References v8::internal::value.
Referenced by IsEmpty().
Member Data Documentation
kEmpty
constexpr InternalRepresentationType v8::internal::ValueHelper::kEmpty = nullptr [static], [constexpr]
Definition at line 1677 of file v8-internal.h.
Referenced by v8::Context::GetDataFromSnapshotOnce(), v8::Isolate::GetDataFromSnapshotOnce(), v8::anonymous_namespace{api.cc}::GetSerializedDataFromFixedArray(), and IsEmpty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-internal.h