v8::internal::Deserializer< IsolateT > Class Template Reference
#include <deserializer.h>
Classes
class DisableGCStats
class HotObjectsList
struct ReferenceDescriptor
struct UnresolvedForwardRef
Public Member Functions
~Deserializer () override
Deserializer (const Deserializer &)=delete
Deserializer & operator= (const Deserializer &)=delete
template<typename SlotAccessor >
int ReadRepeatedRoot (SlotAccessor slot_accessor, int repeat_count)
Protected Member Functions
Deserializer (IsolateT *isolate, base::Vector< const uint8_t > payload, uint32_t magic_number, bool deserializing_user_code, bool can_rehash)
void DeserializeDeferredObjects ()
void LogNewObjectEvents ()
void LogScriptEvents (Tagged< Script > script)
void LogNewMapEvents ()
void WeakenDescriptorArrays ()
Handle< HeapObject > GetBackReferencedObject ()
Handle< HeapObject > GetBackReferencedObject (uint32_t index)
void AddAttachedObject (DirectHandle< HeapObject > attached_object)
IsolateT * isolate () const
Isolate * main_thread_isolate () const
SnapshotByteSource * source ()
base::Vector< const DirectHandle< AllocationSite > > new_allocation_sites () const
base::Vector< const DirectHandle< InstructionStream > > new_code_objects () const
base::Vector< const DirectHandle< Map > > new_maps () const
base::Vector< const DirectHandle< AccessorInfo > > accessor_infos () const
base::Vector< const DirectHandle< FunctionTemplateInfo > > function_template_infos () const
base::Vector< const DirectHandle< Script > > new_scripts () const
std::shared_ptr< BackingStore > backing_store (size_t i)
bool deserializing_user_code () const
bool should_rehash () const
void PushObjectToRehash (DirectHandle< HeapObject > object)
void Rehash ()
DirectHandle< HeapObject > ReadObject ()
Private Member Functions
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void Synchronize (VisitorSynchronization::SyncTag tag) override
template<typename SlotAccessor >
int WriteHeapPointer (SlotAccessor slot_accessor, Tagged< HeapObject > heap_object, ReferenceDescriptor descr, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
template<typename SlotAccessor >
int WriteHeapPointer (SlotAccessor slot_accessor, DirectHandle< HeapObject > heap_object, ReferenceDescriptor descr, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
int WriteExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot dest, Address value, ExternalPointerTag tag)
int WriteIndirectPointer (IndirectPointerSlot dest, Tagged< HeapObject > value)
void ReadData (Handle< HeapObject > object, int start_slot_index, int end_slot_index)
void ReadData (FullMaybeObjectSlot start, FullMaybeObjectSlot end)
template<typename SlotAccessor >
int ReadSingleBytecodeData (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadNewObject (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadBackref (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadReadOnlyHeapRef (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadRootArray (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadStartupObjectCache (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadSharedHeapObjectCache (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadNewMetaMap (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadExternalReference (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadRawExternalReference (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadAttachedReference (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadRegisterPendingForwardRef (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadResolvePendingForwardRef (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadVariableRawData (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadVariableRepeatRoot (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadOffHeapBackingStore (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadApiReference (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadClearedWeakReference (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadWeakPrefix (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadIndirectPointerPrefix (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadInitializeSelfIndirectPointer (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadAllocateJSDispatchEntry (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadJSDispatchEntry (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadProtectedPointerPrefix (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadRootArrayConstants (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadHotObject (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadFixedRawData (uint8_t data, SlotAccessor slot_accessor)
template<typename SlotAccessor >
int ReadFixedRepeatRoot (uint8_t data, SlotAccessor slot_accessor)
Address ReadExternalReferenceCase ()
ExternalPointerTag ReadExternalPointerTag ()
Handle< HeapObject > ReadObject (SnapshotSpace space)
Handle< HeapObject > ReadMetaMap (SnapshotSpace space)
ReferenceDescriptor GetAndResetNextReferenceDescriptor ()
template<typename SlotGetter >
int ReadRepeatedRoot (SlotGetter slot_getter, int repeat_count)
void PostProcessNewObject (DirectHandle< Map > map, Handle< HeapObject > obj, SnapshotSpace space)
void PostProcessNewJSReceiver (Tagged< Map > map, DirectHandle< JSReceiver > obj, InstanceType instance_type, SnapshotSpace space)
Tagged< HeapObject > Allocate (AllocationType allocation, int size, AllocationAlignment alignment)
void PostProcessNewJSReceiver (Tagged< Map > map, DirectHandle< JSReceiver > obj, InstanceType instance_type, SnapshotSpace space)
void PostProcessNewJSReceiver (Tagged< Map > map, DirectHandle< JSReceiver > obj, InstanceType instance_type, SnapshotSpace space)
Private Attributes
IsolateT * isolate_
DirectHandleVector< HeapObject > attached_objects_
SnapshotByteSource source_
uint32_t magic_number_
HotObjectsList hot_objects_
DirectHandleVector< Map > new_maps_
DirectHandleVector< AllocationSite > new_allocation_sites_
DirectHandleVector< InstructionStream > new_code_objects_
DirectHandleVector< AccessorInfo > accessor_infos_
DirectHandleVector< FunctionTemplateInfo > function_template_infos_
DirectHandleVector< Script > new_scripts_
std::vector< std::shared_ptr< BackingStore > > backing_stores_
GlobalHandleVector< DescriptorArray > new_descriptor_arrays_
std::vector< IndirectHandle< HeapObject > > back_refs_
std::vector< JSDispatchHandle > js_dispatch_entries_
std::vector< UnresolvedForwardRef > unresolved_forward_refs_
int num_unresolved_forward_refs_ = 0
const bool deserializing_user_code_
bool next_reference_is_weak_ = false
bool next_reference_is_indirect_pointer_ = false
bool next_reference_is_protected_pointer = false
const bool should_rehash_
DirectHandleVector< HeapObject > to_rehash_
DisableGCStats no_gc_stats_
int depth_ = 0
Additional Inherited Members
Detailed Description
template<typename IsolateT>
class v8::internal::Deserializer< IsolateT >
Definition at line 44 of file deserializer.h.
Constructor & Destructor Documentation
 Deserializer()
template<typename IsolateT >
v8::internal::Deserializer< IsolateT >::~Deserializer [override]
Definition at line 365 of file deserializer.cc.
                                      {
#ifdef DEBUG
  // Do not perform checks if we aborted deserialization.
  if (source_.position() == 0) return;
  // Check that we only have padding bytes remaining.
  while (source_.HasMore()) DCHECK_EQ(kNop, source_.Get());
  // Check that there are no remaining forward refs.
  DCHECK_EQ(num_unresolved_forward_refs_, 0);
  DCHECK(unresolved_forward_refs_.empty());
#endif // DEBUG
  isolate_->RegisterDeserializerFinished();
}
References v8::internal::DCHECK(), and DCHECK_EQ.
Deserializer() [1/2]
template<typename IsolateT >
v8::internal::Deserializer< IsolateT >::Deserializer (const Deserializer< IsolateT > &) [delete]
Deserializer() [2/2]
template<typename IsolateT >
v8::internal::Deserializer< IsolateT >::Deserializer (IsolateT * isolate, base::Vector< const uint8_t > payload, uint32_t magic_number, bool deserializing_user_code, bool can_rehash) [protected]
Definition at line 318 of file deserializer.cc.
    : isolate_(isolate),
      attached_objects_(isolate),
      source_(payload),
      magic_number_(magic_number),
      new_maps_(isolate),
      new_allocation_sites_(isolate),
      new_code_objects_(isolate),
      accessor_infos_(isolate),
      function_template_infos_(isolate),
      new_scripts_(isolate),
      new_descriptor_arrays_(isolate->heap()),
      deserializing_user_code_(deserializing_user_code),
      should_rehash_((v8_flags.rehash_snapshot && can_rehash) ||
                     deserializing_user_code),
      to_rehash_(isolate) {
  DCHECK_NOT_NULL(isolate);
  isolate->RegisterDeserializerStarted();
  // We start the indices here at 1, so that we can distinguish between an
  // actual index and an empty backing store (serialized as
  // kEmptyBackingStoreRefSentinel) in a deserialized object requiring fix-up.
  static_assert(kEmptyBackingStoreRefSentinel == 0);
  backing_stores_.push_back({});
  back_refs_.reserve(2048);
  js_dispatch_entries_.reserve(512);
#ifdef DEBUG
  num_api_references_ = GetNumApiReferences(isolate);
#endif // DEBUG
  CHECK_EQ(magic_number_, SerializedData::kMagicNumber);
}
References v8::internal::Deserializer< IsolateT >::back_refs_, v8::internal::Deserializer< IsolateT >::backing_stores_, CHECK_EQ, DCHECK_NOT_NULL, v8::internal::Deserializer< IsolateT >::isolate(), v8::internal::Deserializer< IsolateT >::js_dispatch_entries_, v8::internal::SerializerDeserializer::kEmptyBackingStoreRefSentinel, v8::internal::SerializedData::kMagicNumber, and v8::internal::Deserializer< IsolateT >::magic_number_.
Member Function Documentation
accessor_infos()
template<typename IsolateT >
base::Vector<const DirectHandle<AccessorInfo> > v8::internal::Deserializer< IsolateT >::accessor_infos () const [inline], [protected]
Definition at line 95 of file deserializer.h.
                                                                      {
    return {accessor_infos_.data(), accessor_infos_.size()};
  }
References v8::internal::Deserializer< IsolateT >::accessor_infos_.
AddAttachedObject()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::AddAttachedObject (DirectHandle< HeapObject > attached_object) [inline], [protected]
Definition at line 75 of file deserializer.h.
                                                                   {
    attached_objects_.push_back(attached_object);
  }
References v8::internal::Deserializer< IsolateT >::attached_objects_.
Referenced by v8::internal::ObjectDeserializer::DeserializeSharedFunctionInfo(), and v8::internal::OffThreadObjectDeserializer::DeserializeSharedFunctionInfo().
Allocate()
template<typename IsolateT >
Tagged< HeapObject > v8::internal::Deserializer< IsolateT >::Allocate (AllocationType allocation, int size, AllocationAlignment alignment) [private]
Definition at line 1663 of file deserializer.cc.
                                                                        {
#ifdef DEBUG
  if (!previous_allocation_obj_.is_null()) {
    // Make sure that the previous object is initialized sufficiently to
    // be iterated over by the GC.
    int object_size = previous_allocation_obj_->Size(isolate_);
    DCHECK_LE(object_size, previous_allocation_size_);
  }
#endif
  Tagged<HeapObject> obj =
      HeapObject::FromAddress(isolate()->heap()->AllocateRawOrFail(
          size, allocation, AllocationOrigin::kRuntime, alignment));
#ifdef DEBUG
  previous_allocation_obj_ = direct_handle(obj, isolate());
  previous_allocation_size_ = size;
#endif
  return obj;
}
References DCHECK_LE, v8::internal::direct_handle(), heap(), and size().
backing_store()
template<typename IsolateT >
std::shared_ptr<BackingStore> v8::internal::Deserializer< IsolateT >::backing_store (size_t i) [inline], [protected]
Definition at line 106 of file deserializer.h.
                                                      {
    DCHECK_LT(i, backing_stores_.size());
    return backing_stores_[i];
  }
References v8::internal::Deserializer< IsolateT >::backing_stores_, DCHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
DeserializeDeferredObjects()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::DeserializeDeferredObjects [protected]
Definition at line 410 of file deserializer.cc.
                                                        {
  if (v8_flags.trace_deserialization) {
    PrintF("-- Deferred objects\n");
  }
  for (int code = source_.Get(); code != kSynchronize; code = source_.Get()) {
    SnapshotSpace space = NewObject::Decode(code);
    ReadObject(space);
  }
}
References code, v8::internal::PrintF(), space, and v8::internal::v8_flags.
deserializing_user_code()
template<typename IsolateT >
bool v8::internal::Deserializer< IsolateT >::deserializing_user_code () const [inline], [protected]
Definition at line 111 of file deserializer.h.
{ return deserializing_user_code_; }
References v8::internal::Deserializer< IsolateT >::deserializing_user_code_.
function_template_infos()
template<typename IsolateT >
base::Vector<const DirectHandle<FunctionTemplateInfo> > v8::internal::Deserializer< IsolateT >::function_template_infos () const [inline], [protected]
Definition at line 99 of file deserializer.h.
                                  {
    return {function_template_infos_.data(), function_template_infos_.size()};
  }
References v8::internal::Deserializer< IsolateT >::function_template_infos_.
GetAndResetNextReferenceDescriptor()
template<typename IsolateT >
Deserializer< IsolateT >::ReferenceDescriptor v8::internal::Deserializer< IsolateT >::GetAndResetNextReferenceDescriptor [private]
Definition at line 702 of file deserializer.cc.
                                                           {
  DCHECK(!(next_reference_is_weak_ && next_reference_is_indirect_pointer_));
  ReferenceDescriptor desc;
  desc.type = next_reference_is_weak_ ? HeapObjectReferenceType::WEAK
                                      : HeapObjectReferenceType::STRONG;
  next_reference_is_weak_ = false;
  desc.is_indirect_pointer = next_reference_is_indirect_pointer_;
  next_reference_is_indirect_pointer_ = false;
  desc.is_protected_pointer = next_reference_is_protected_pointer;
  next_reference_is_protected_pointer = false;
  return desc;
}
References DCHECK, v8::internal::Deserializer< IsolateT >::ReferenceDescriptor::is_indirect_pointer, v8::internal::Deserializer< IsolateT >::ReferenceDescriptor::is_protected_pointer, STRONG, v8::internal::Deserializer< IsolateT >::ReferenceDescriptor::type, and WEAK.
GetBackReferencedObject() [1/2]
template<typename IsolateT >
Handle< HeapObject > v8::internal::Deserializer< IsolateT >::GetBackReferencedObject [protected]
Definition at line 716 of file deserializer.cc.
                                                                   {
  return GetBackReferencedObject(source_.GetUint30());
}
GetBackReferencedObject() [2/2]
template<typename IsolateT >
Handle< HeapObject > v8::internal::Deserializer< IsolateT >::GetBackReferencedObject (uint32_t index) [protected]
Definition at line 721 of file deserializer.cc.
                    {
  Handle<HeapObject> obj = back_refs_[index];
  // We don't allow ThinStrings in backreferences -- if internalization produces
  // a thin string, then it should also update the backref handle.
  DCHECK(!IsThinString(*obj, isolate()));
  hot_objects_.Add(obj);
  DCHECK(!HasWeakHeapObjectTag(*obj));
  return obj;
}
References DCHECK, v8::internal::HasWeakHeapObjectTag(), v8::internal::index, and v8::internal::InstanceTypeChecker::IsThinString().
isolate()
template<typename IsolateT >
IsolateT* v8::internal::Deserializer< IsolateT >::isolate () const [inline], [protected]
Definition at line 79 of file deserializer.h.
{ return isolate_; }
References v8::internal::Deserializer< IsolateT >::isolate_.
Referenced by v8::internal::Deserializer< IsolateT >::Deserializer().
LogNewMapEvents()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::LogNewMapEvents [protected]
Definition at line 421 of file deserializer.cc.
                                             {
  if (V8_LIKELY(!v8_flags.log_maps)) return;
  DisallowGarbageCollection no_gc;
  for (DirectHandle<Map> map : new_maps_) {
    DCHECK(v8_flags.log_maps);
    LOG(isolate(), MapCreate(*map));
    LOG(isolate(), MapDetails(*map));
  }
}
References v8::internal::DCHECK(), LOG, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::v8_flags, and V8_LIKELY.
LogNewObjectEvents()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::LogNewObjectEvents () [protected]
LogScriptEvents()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::LogScriptEvents (Tagged< Script > script) [protected]
Definition at line 437 of file deserializer.cc.
                                                                  {
  DisallowGarbageCollection no_gc;
  LOG(isolate(), ScriptEvent(ScriptEventType::kDeserialize, script->id()));
  LOG(isolate(), ScriptDetails(script));
}
References v8::internal::kDeserialize, LOG, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::script.
main_thread_isolate()
template<typename IsolateT >
Isolate* v8::internal::Deserializer< IsolateT >::main_thread_isolate () const [inline], [protected]
Definition at line 81 of file deserializer.h.
{ return isolate_->AsIsolate(); }
References v8::internal::Deserializer< IsolateT >::isolate_.
new_allocation_sites()
template<typename IsolateT >
base::Vector<const DirectHandle<AllocationSite> > v8::internal::Deserializer< IsolateT >::new_allocation_sites () const [inline], [protected]
Definition at line 85 of file deserializer.h.
            {
    return {new_allocation_sites_.data(), new_allocation_sites_.size()};
  }
References v8::internal::Deserializer< IsolateT >::new_allocation_sites_.
new_code_objects()
template<typename IsolateT >
base::Vector<const DirectHandle<InstructionStream> > v8::internal::Deserializer< IsolateT >::new_code_objects () const [inline], [protected]
Definition at line 89 of file deserializer.h.
                                                                             {
    return {new_code_objects_.data(), new_code_objects_.size()};
  }
References v8::internal::Deserializer< IsolateT >::new_code_objects_.
new_maps()
template<typename IsolateT >
base::Vector<const DirectHandle<Map> > v8::internal::Deserializer< IsolateT >::new_maps () const [inline], [protected]
Definition at line 92 of file deserializer.h.
                                                       {
    return {new_maps_.data(), new_maps_.size()};
  }
References v8::internal::Deserializer< IsolateT >::new_maps_.
new_scripts()
template<typename IsolateT >
base::Vector<const DirectHandle<Script> > v8::internal::Deserializer< IsolateT >::new_scripts () const [inline], [protected]
Definition at line 102 of file deserializer.h.
                                                             {
    return {new_scripts_.data(), new_scripts_.size()};
  }
References v8::internal::Deserializer< IsolateT >::new_scripts_.
operator=()
template<typename IsolateT >
Deserializer& v8::internal::Deserializer< IsolateT >::operator= (const Deserializer< IsolateT > &) [delete]
PostProcessNewJSReceiver() [1/3]
void v8::internal::Deserializer< Isolate >::PostProcessNewJSReceiver (Tagged< Map > map, DirectHandle< JSReceiver > obj, InstanceType instance_type, SnapshotSpace space) [private]
Definition at line 512 of file deserializer.cc.
                         {
  DCHECK_EQ(map->instance_type(), instance_type);
  if (InstanceTypeChecker::IsJSDataView(instance_type) ||
      InstanceTypeChecker::IsJSRabGsabDataView(instance_type)) {
    auto data_view = Cast<JSDataViewOrRabGsabDataView>(*obj);
    auto buffer = Cast<JSArrayBuffer>(data_view->buffer());
    if (buffer->was_detached()) {
      // Directly set the data pointer to point to the EmptyBackingStoreBuffer.
      // Otherwise, we might end up setting it to EmptyBackingStoreBuffer() +
      // byte_offset() which would result in an invalid pointer.
      data_view->set_data_pointer(main_thread_isolate(),
                                  EmptyBackingStoreBuffer());
    } else {
      void* backing_store = buffer->backing_store();
      data_view->set_data_pointer(
          main_thread_isolate(),
          reinterpret_cast<uint8_t*>(backing_store) + data_view->byte_offset());
    }
  } else if (InstanceTypeChecker::IsJSTypedArray(instance_type)) {
    auto typed_array = Cast<JSTypedArray>(*obj);
    // Note: ByteArray objects must not be deferred s.t. they are
    // available here for is_on_heap(). See also: CanBeDeferred.
    // Fixup typed array pointers.
    if (typed_array->is_on_heap()) {
      typed_array->AddExternalPointerCompensationForDeserialization(
          main_thread_isolate());
    } else {
      // Serializer writes backing store ref as a DataPtr() value.
      uint32_t store_index =
          typed_array->GetExternalBackingStoreRefForDeserialization();
      auto backing_store = backing_stores_[store_index];
      void* start = backing_store ? backing_store->buffer_start() : nullptr;
      if (!start) start = EmptyBackingStoreBuffer();
      typed_array->SetOffHeapDataPtr(main_thread_isolate(), start,
                                     typed_array->byte_offset());
    }
  } else if (InstanceTypeChecker::IsJSArrayBuffer(instance_type)) {
    auto buffer = Cast<JSArrayBuffer>(*obj);
    uint32_t store_index = buffer->GetBackingStoreRefForDeserialization();
    buffer->init_extension();
    if (store_index == kEmptyBackingStoreRefSentinel) {
      buffer->set_backing_store(main_thread_isolate(),
                                EmptyBackingStoreBuffer());
    } else {
      auto bs = backing_store(store_index);
      SharedFlag shared =
          bs && bs->is_shared() ? SharedFlag::kShared : SharedFlag::kNotShared;
      DCHECK_IMPLIES(bs,
                     buffer->is_resizable_by_js() == bs->is_resizable_by_js());
      ResizableFlag resizable = bs && bs->is_resizable_by_js()
                                    ? ResizableFlag::kResizable
                                    : ResizableFlag::kNotResizable;
      buffer->Setup(shared, resizable, bs, main_thread_isolate());
    }
  } else if (InstanceTypeChecker::IsJSDate(instance_type)) {
    Cast<JSDate>(*obj)->UpdateFieldsAfterDeserialization(main_thread_isolate());
  }
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::EmptyBackingStoreBuffer(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, and v8::internal::anonymous_namespace{elements.cc}::kShared.
PostProcessNewJSReceiver() [2/3]
void v8::internal::Deserializer< LocalIsolate >::PostProcessNewJSReceiver (Tagged< Map > map, DirectHandle< JSReceiver > obj, InstanceType instance_type, SnapshotSpace space) [private]
Definition at line 575 of file deserializer.cc.
                         {
  UNREACHABLE();
}
References UNREACHABLE.
PostProcessNewJSReceiver() [3/3]
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::PostProcessNewJSReceiver (Tagged< Map > map, DirectHandle< JSReceiver > obj, InstanceType instance_type, SnapshotSpace space) [private]
PostProcessNewObject()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::PostProcessNewObject (DirectHandle< Map > map, Handle< HeapObject > obj, SnapshotSpace space) [private]
Definition at line 582 of file deserializer.cc.
                                                                       {
  DisallowGarbageCollection no_gc;
  Tagged<Map> raw_map = *map;
  DCHECK_EQ(raw_map, obj->map(isolate_));
  InstanceType instance_type = raw_map->instance_type();
  Tagged<HeapObject> raw_obj = *obj;
  DCHECK_IMPLIES(deserializing_user_code(), should_rehash());
  if (should_rehash()) {
    if (InstanceTypeChecker::IsString(instance_type)) {
      // Uninitialize hash field as we need to recompute the hash.
      Tagged<String> string = Cast<String>(raw_obj);
      string->set_raw_hash_field(String::kEmptyHashField);
      // Rehash strings before read-only space is sealed. Strings outside
      // read-only space are rehashed lazily. (e.g. when rehashing dictionaries)
      if (space == SnapshotSpace::kReadOnlyHeap) {
        PushObjectToRehash(obj);
      }
    } else if (raw_obj->NeedsRehashing(instance_type)) {
      PushObjectToRehash(obj);
    }
    if (deserializing_user_code()) {
      if (InstanceTypeChecker::IsInternalizedString(instance_type)) {
        // Canonicalize the internalized string. If it already exists in the
        // string table, set the string to point to the existing one and patch
        // the deserialized string handle to point to the existing one.
        // TODO(leszeks): This handle patching is ugly, consider adding an
        // explicit internalized string bytecode. Also, the new thin string
        // should be dead, try immediately freeing it.
        DirectHandle<String> string = Cast<String>(obj);
        StringTableInsertionKey key(
            isolate(), string,
            DeserializingUserCodeOption::kIsDeserializingUserCode);
        Tagged<String> result =
            *isolate()->string_table()->LookupKey(isolate(), &key);
        if (result != raw_obj) {
          Cast<String>(raw_obj)->MakeThin(isolate(), result);
          // Mutate the given object handle so that the backreference entry is
          // also updated.
          obj.PatchValue(result);
        }
        return;
      } else if (InstanceTypeChecker::IsScript(instance_type)) {
        new_scripts_.push_back(Cast<Script>(obj));
      } else if (InstanceTypeChecker::IsAllocationSite(instance_type)) {
        // We should link new allocation sites, but we can't do this immediately
        // because |AllocationSite::HasWeakNext()| internally accesses
        // |Heap::roots_| that may not have been initialized yet. So defer this
        // to |ObjectDeserializer::CommitPostProcessedObjects()|.
        new_allocation_sites_.push_back(Cast<AllocationSite>(obj));
      } else {
        // We dont defer ByteArray because JSTypedArray needs the base_pointer
        // ByteArray immediately if it's on heap.
        DCHECK(CanBeDeferred(*obj, SlotType::kAnySlot) ||
               InstanceTypeChecker::IsByteArray(instance_type));
      }
    }
  }
  if (InstanceTypeChecker::IsInstructionStream(instance_type)) {
    // We flush all code pages after deserializing the startup snapshot.
    // Hence we only remember each individual code object when deserializing
    // user code.
    if (deserializing_user_code()) {
      new_code_objects_.push_back(Cast<InstructionStream>(obj));
    }
  } else if (InstanceTypeChecker::IsCode(instance_type)) {
    Tagged<Code> code = Cast<Code>(raw_obj);
    if (!code->has_instruction_stream()) {
      code->SetInstructionStartForOffHeapBuiltin(
          main_thread_isolate(), EmbeddedData::FromBlob(main_thread_isolate())
                                     .InstructionStartOf(code->builtin_id()));
    } else {
      code->UpdateInstructionStart(main_thread_isolate(),
                                   code->instruction_stream());
    }
  } else if (InstanceTypeChecker::IsSharedFunctionInfo(instance_type)) {
    Tagged<SharedFunctionInfo> sfi = Cast<SharedFunctionInfo>(raw_obj);
    // Reset the id to avoid collisions - it must be unique in this isolate.
    sfi->set_unique_id(isolate()->GetAndIncNextUniqueSfiId());
  } else if (InstanceTypeChecker::IsMap(instance_type)) {
    if (v8_flags.log_maps) {
      // Keep track of all seen Maps to log them later since they might be only
      // partially initialized at this point.
      new_maps_.push_back(Cast<Map>(obj));
    }
  } else if (InstanceTypeChecker::IsAccessorInfo(instance_type)) {
#ifdef USE_SIMULATOR
    accessor_infos_.push_back(Cast<AccessorInfo>(obj));
#endif
  } else if (InstanceTypeChecker::IsFunctionTemplateInfo(instance_type)) {
#ifdef USE_SIMULATOR
    function_template_infos_.push_back(Cast<FunctionTemplateInfo>(obj));
#endif
  } else if (InstanceTypeChecker::IsExternalString(instance_type)) {
    PostProcessExternalString(Cast<ExternalString>(raw_obj),
                              main_thread_isolate());
  } else if (InstanceTypeChecker::IsJSReceiver(instance_type)) {
    // PostProcessNewJSReceiver may trigger GC.
    no_gc.Release();
    return PostProcessNewJSReceiver(raw_map, Cast<JSReceiver>(obj),
                                    instance_type, space);
  } else if (InstanceTypeChecker::IsDescriptorArray(instance_type)) {
    DCHECK(InstanceTypeChecker::IsStrongDescriptorArray(instance_type));
    auto descriptors = Cast<DescriptorArray>(obj);
    new_descriptor_arrays_.Push(*descriptors);
  } else if (InstanceTypeChecker::IsNativeContext(instance_type)) {
    Cast<NativeContext>(raw_obj)->init_microtask_queue(main_thread_isolate(),
                                                       nullptr);
  } else if (InstanceTypeChecker::IsScript(instance_type)) {
    LogScriptEvents(Cast<Script>(*obj));
  }
}
References code, DCHECK, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Handle< T >::PatchValue(), v8::internal::anonymous_namespace{deserializer.cc}::PostProcessExternalString(), v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::Release(), v8::base::internal::result, space, and v8::internal::v8_flags.
PushObjectToRehash()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::PushObjectToRehash (DirectHandle< HeapObject > object) [inline], [protected]
Definition at line 114 of file deserializer.h.
                                                           {
    to_rehash_.push_back(object);
  }
References v8::internal::Deserializer< IsolateT >::to_rehash_.
ReadAllocateJSDispatchEntry()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadAllocateJSDispatchEntry (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1491 of file deserializer.cc.
                                              {
#ifdef V8_ENABLE_LEAPTIERING
  DCHECK_NE(slot_accessor.object()->address(), kNullAddress);
  DirectHandle<HeapObject> host = slot_accessor.object();
  uint32_t parameter_count = source_.GetUint30();
  DCHECK_LE(parameter_count, kMaxUInt16);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sAllocateJSDispatchEntry [%u]\n", depth_, "", parameter_count);
  }
  DirectHandle<Code> code = Cast<Code>(ReadObject());
  JSDispatchTable::Space* space =
      isolate()->GetJSDispatchTableSpaceFor(host->address());
  JSDispatchHandle handle =
      isolate()->factory()->NewJSDispatchHandle(parameter_count, code, space);
  js_dispatch_entries_.push_back(handle);
  host->Relaxed_WriteField<JSDispatchHandle::underlying_type>(
      slot_accessor.offset(), handle.value());
  JS_DISPATCH_HANDLE_WRITE_BARRIER(*host, handle);
  return 1;
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::DirectHandle< T >::address(), code, DCHECK_LE, DCHECK_NE, v8::internal::handle(), JS_DISPATCH_HANDLE_WRITE_BARRIER, v8::internal::kMaxUInt16, v8::base::kNullAddress, v8::internal::PrintF(), space, UNREACHABLE, and v8::internal::v8_flags.
ReadApiReference()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadApiReference (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1404 of file deserializer.cc.
                                                                         {
  DCHECK_IMPLIES(data == kSandboxedApiReference, V8_ENABLE_SANDBOX_BOOL);
  uint32_t reference_id = static_cast<uint32_t>(source_.GetUint30());
  Address address;
  if (main_thread_isolate()->api_external_references()) {
    DCHECK_WITH_MSG(reference_id < num_api_references_,
                    "too few external references provided through the API");
    address = static_cast<Address>(
        main_thread_isolate()->api_external_references()[reference_id]);
  } else {
    address = reinterpret_cast<Address>(NoExternalReferencesCallback);
  }
  ExternalPointerTag tag = kExternalPointerNullTag;
  if (data == kSandboxedApiReference) {
    tag = ReadExternalPointerTag();
  }
  if (v8_flags.trace_deserialization) {
    PrintF("%*sApiReference [%" PRIxPTR ", %i]\n", depth_, "", address, tag);
  }
  return WriteExternalPointer(*slot_accessor.object(),
                              slot_accessor.external_pointer_slot(tag), address,
                              tag);
}
References DCHECK_IMPLIES, DCHECK_WITH_MSG, v8::internal::kExternalPointerNullTag, v8::internal::anonymous_namespace{deserializer.cc}::NoExternalReferencesCallback(), v8::internal::PrintF(), V8_ENABLE_SANDBOX_BOOL, and v8::internal::v8_flags.
ReadAttachedReference()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadAttachedReference (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1279 of file deserializer.cc.
                                                                              {
  int index = source_.GetUint30();
  DirectHandle<HeapObject> heap_object = attached_objects_[index];
  if (v8_flags.trace_deserialization) {
    PrintF("%*sAttachedReference [%u] : ", depth_, "", index);
    ShortPrint(*heap_object);
    PrintF("\n");
  }
  return WriteHeapPointer(slot_accessor, heap_object,
                          GetAndResetNextReferenceDescriptor());
}
References v8::internal::index, v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
ReadBackref()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadBackref (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1119 of file deserializer.cc.
                                                                    {
  uint32_t index = source_.GetUint30();
  DirectHandle<HeapObject> heap_object = GetBackReferencedObject(index);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sBackref [%u]\n", depth_, "", index);
    // Don't print the backref object, since it might still be being
    // initialized.
    // TODO(leszeks): Have some sort of initialization marker on backrefs to
    // allow them to be printed when valid.
  }
  return WriteHeapPointer(slot_accessor, heap_object,
                          GetAndResetNextReferenceDescriptor());
}
References v8::internal::index, v8::internal::PrintF(), and v8::internal::v8_flags.
ReadClearedWeakReference()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadClearedWeakReference (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1431 of file deserializer.cc.
                                              {
  if (v8_flags.trace_deserialization) {
    PrintF("%*sClearedWeakReference\n", depth_, "");
  }
  return slot_accessor.Write(ClearedValue(isolate()), 0, SKIP_WRITE_BARRIER);
}
References v8::internal::ClearedValue(), v8::internal::PrintF(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::v8_flags.
ReadData() [1/2]
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::ReadData (FullMaybeObjectSlot start, FullMaybeObjectSlot end) [private]
Definition at line 980 of file deserializer.cc.
                                                               {
  FullMaybeObjectSlot current = start;
  while (current < end) {
    uint8_t data = source_.Get();
    current += ReadSingleBytecodeData(data, SlotAccessorForRootSlots(current));
  }
  CHECK_EQ(current, end);
}
References CHECK_EQ, and v8::internal::compiler::end().
ReadData() [2/2]
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::ReadData (Handle< HeapObject > object, int start_slot_index, int end_slot_index) [private]
Definition at line 967 of file deserializer.cc.
                                                          {
  int current = start_slot_index;
  while (current < end_slot_index) {
    uint8_t data = source_.Get();
    current += ReadSingleBytecodeData(
        data, SlotAccessorForHeapObject::ForSlotIndex(object, current));
  }
  CHECK_EQ(current, end_slot_index);
}
References CHECK_EQ.
ReadExternalPointerTag()
template<typename IsolateT >
ExternalPointerTag v8::internal::Deserializer< IsolateT >::ReadExternalPointerTag [private]
Definition at line 1658 of file deserializer.cc.
                                                                  {
  return static_cast<ExternalPointerTag>(source_.GetUint30());
}
ReadExternalReference()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadExternalReference (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1238 of file deserializer.cc.
                                                                              {
  DCHECK_IMPLIES(data == kSandboxedExternalReference, V8_ENABLE_SANDBOX_BOOL);
  Address address = ReadExternalReferenceCase();
  ExternalPointerTag tag = kExternalPointerNullTag;
  if (data == kSandboxedExternalReference) {
    tag = ReadExternalPointerTag();
  }
  if (v8_flags.trace_deserialization) {
    PrintF("%*sExternalReference [%" PRIxPTR ", %i]\n", depth_, "", address,
           tag);
  }
  return WriteExternalPointer(*slot_accessor.object(),
                              slot_accessor.external_pointer_slot(tag), address,
                              tag);
}
References DCHECK_IMPLIES, v8::internal::kExternalPointerNullTag, v8::internal::PrintF(), V8_ENABLE_SANDBOX_BOOL, and v8::internal::v8_flags.
ReadExternalReferenceCase()
template<typename IsolateT >
Address v8::internal::Deserializer< IsolateT >::ReadExternalReferenceCase [inline], [private]
Definition at line 1651 of file deserializer.cc.
                                                          {
  uint32_t reference_id = static_cast<uint32_t>(source_.GetUint30());
  return main_thread_isolate()->external_reference_table()->address(
      reference_id);
}
ReadFixedRawData()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadFixedRawData (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1598 of file deserializer.cc.
                                                                         {
  using TSlot = decltype(slot_accessor.slot());
  // Deserialize raw data of fixed length from 1 to 32 times kTaggedSize.
  int size_in_tagged = FixedRawDataWithSize::Decode(data);
  static_assert(TSlot::kSlotDataSize == kTaggedSize ||
                TSlot::kSlotDataSize == 2 * kTaggedSize);
  int size_in_slots = size_in_tagged / (TSlot::kSlotDataSize / kTaggedSize);
  // kFixedRawData can have kTaggedSize != TSlot::kSlotDataSize when
  // serializing Smi roots in pointer-compressed builds. In this case, the
  // size in bytes is unconditionally the (full) slot size.
  DCHECK_IMPLIES(kTaggedSize != TSlot::kSlotDataSize, size_in_slots == 1);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sFixedRawData [%u] :", depth_, "", size_in_tagged);
    for (int i = 0; i < size_in_tagged; ++i) {
      PrintF(" %0*" PRIxTAGGED, kTaggedSize / 2,
             reinterpret_cast<const Tagged_t*>(source_.data())[i]);
    }
    PrintF("\n");
  }
  // TODO(leszeks): Only copy slots when there are Smis in the serialized
  // data.
  source_.CopySlots(slot_accessor.slot().location(), size_in_slots);
  return size_in_slots;
}
References DCHECK_IMPLIES, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kTaggedSize, v8::internal::PrintF(), PRIxTAGGED, and v8::internal::v8_flags.
ReadFixedRepeatRoot()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadFixedRepeatRoot (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1627 of file deserializer.cc.
                                                                            {
  int repeats = FixedRepeatRootWithCount::Decode(data);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sFixedRepeat [%u] : ", depth_, "", repeats);
  }
  int ret = ReadRepeatedRoot(slot_accessor, repeats);
  if (v8_flags.trace_deserialization) {
    PrintF("\n");
  }
  return ret;
}
References v8::internal::PrintF(), and v8::internal::v8_flags.
ReadHotObject()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadHotObject (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1583 of file deserializer.cc.
                                                                      {
  int index = HotObject::Decode(data);
  DirectHandle<HeapObject> hot_object = hot_objects_.Get(index);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sHotObject [%u] : ", depth_, "", index);
    ShortPrint(*hot_object);
    PrintF("\n");
  }
  return WriteHeapPointer(slot_accessor, hot_object,
                          GetAndResetNextReferenceDescriptor());
}
References v8::internal::index, v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
ReadIndirectPointerPrefix()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadIndirectPointerPrefix (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1456 of file deserializer.cc.
                                              {
  if (v8_flags.trace_deserialization) {
    PrintF("%*sIndirectPointerPrefix\n", depth_, "");
  }
  // We shouldn't have two indirect pointer prefixes in a row.
  DCHECK(!next_reference_is_indirect_pointer_);
  // We shouldn't have a indirect pointer prefix without a current object.
  DCHECK_NE(slot_accessor.object()->address(), kNullAddress);
  next_reference_is_indirect_pointer_ = true;
  return 0;
}
References DCHECK, DCHECK_NE, v8::base::kNullAddress, v8::internal::PrintF(), and v8::internal::v8_flags.
ReadInitializeSelfIndirectPointer()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadInitializeSelfIndirectPointer (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1471 of file deserializer.cc.
                                              {
#ifdef V8_ENABLE_SANDBOX
  DCHECK_NE(slot_accessor.object()->address(), kNullAddress);
  DCHECK(IsExposedTrustedObject(*slot_accessor.object()));
  DCHECK_EQ(slot_accessor.offset(),
            ExposedTrustedObject::kSelfIndirectPointerOffset);
  Tagged<ExposedTrustedObject> host =
      Cast<ExposedTrustedObject>(*slot_accessor.object());
  host->init_self_indirect_pointer(isolate());
  return 1;
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References DCHECK, DCHECK_EQ, DCHECK_NE, v8::base::kNullAddress, and UNREACHABLE.
ReadJSDispatchEntry()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadJSDispatchEntry (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1523 of file deserializer.cc.
                                                                            {
#ifdef V8_ENABLE_LEAPTIERING
  DCHECK_NE(slot_accessor.object()->address(), kNullAddress);
  DirectHandle<HeapObject> host = slot_accessor.object();
  uint32_t entry_id = source_.GetUint30();
  DCHECK_LT(entry_id, js_dispatch_entries_.size());
  if (v8_flags.trace_deserialization) {
    PrintF("%*sJSDispatchEntry [%u]\n", depth_, "", entry_id);
  }
  JSDispatchHandle handle = js_dispatch_entries_[entry_id];
  DCHECK_NE(handle, kNullJSDispatchHandle);
  host->Relaxed_WriteField<JSDispatchHandle::underlying_type>(
      slot_accessor.offset(), handle.value());
  JS_DISPATCH_HANDLE_WRITE_BARRIER(*host, handle);
  return 1;
#else
  UNREACHABLE();
#endif // V8_ENABLE_SANDBOX
}
References DCHECK_LT, DCHECK_NE, v8::internal::handle(), JS_DISPATCH_HANDLE_WRITE_BARRIER, v8::base::kNullAddress, v8::internal::kNullJSDispatchHandle(), v8::internal::PrintF(), UNREACHABLE, and v8::internal::v8_flags.
ReadMetaMap()
template<typename IsolateT >
Handle< HeapObject > v8::internal::Deserializer< IsolateT >::ReadMetaMap (SnapshotSpace space) [private]
Definition at line 882 of file deserializer.cc.
                                                                          {
  const int size_in_bytes = Map::kSize;
  const int size_in_tagged = size_in_bytes / kTaggedSize;
  Tagged<HeapObject> raw_obj =
      Allocate(SpaceToAllocation(space), size_in_bytes, kTaggedAligned);
  raw_obj->set_map_after_allocation(isolate_, UncheckedCast<Map>(raw_obj));
  MemsetTagged(raw_obj->RawField(kTaggedSize),
               Smi::uninitialized_deserialization_value(), size_in_tagged - 1);
  DCHECK(raw_obj->CheckRequiredAlignment(isolate()));
  Handle<HeapObject> obj = handle(raw_obj, isolate());
  back_refs_.push_back(obj);
  if (v8_flags.trace_deserialization) {
    PrintF(" %*s(set obj backref %u)\n", depth_, "",
           static_cast<int>(back_refs_.size() - 1));
  }
  // Set the instance-type manually, to allow backrefs to read it.
  UncheckedCast<Map>(*obj)->set_instance_type(MAP_TYPE);
  ReadData(obj, 1, size_in_tagged);
  PostProcessNewObject(Cast<Map>(obj), obj, space);
  return obj;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), DCHECK, v8::internal::handle(), v8::internal::kTaggedAligned, v8::internal::kTaggedSize, v8::internal::MemsetTagged(), v8::internal::PrintF(), space, v8::internal::anonymous_namespace{deserializer.cc}::SpaceToAllocation(), and v8::internal::v8_flags.
ReadNewMetaMap()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadNewMetaMap (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1221 of file deserializer.cc.
                                                                       {
  SnapshotSpace space = data == kNewContextlessMetaMap
                            ? SnapshotSpace::kReadOnlyHeap
                            : SnapshotSpace::kOld;
  DirectHandle<HeapObject> heap_object = ReadMetaMap(space);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sNewMetaMap [%s]\n", depth_, "", SnapshotSpaceName(space));
  }
  return slot_accessor.Write(heap_object, HeapObjectReferenceType::STRONG, 0,
                             UPDATE_WRITE_BARRIER);
}
References v8::internal::PrintF(), v8::internal::anonymous_namespace{deserializer.cc}::SnapshotSpaceName(), space, STRONG, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::v8_flags.
ReadNewObject()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadNewObject (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1098 of file deserializer.cc.
                                                                      {
  SnapshotSpace space = NewObject::Decode(data);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sNewObject [%s]\n", depth_, "", SnapshotSpaceName(space));
    ++depth_;
  }
  DCHECK_IMPLIES(V8_STATIC_ROOTS_BOOL, space != SnapshotSpace::kReadOnlyHeap);
  // Save the descriptor before recursing down into reading the object.
  ReferenceDescriptor descr = GetAndResetNextReferenceDescriptor();
  DirectHandle<HeapObject> heap_object = ReadObject(space);
  if (v8_flags.trace_deserialization) {
    --depth_;
  }
  return WriteHeapPointer(slot_accessor, heap_object, descr);
}
References DCHECK_IMPLIES, v8::internal::PrintF(), v8::internal::anonymous_namespace{deserializer.cc}::SnapshotSpaceName(), space, v8::internal::v8_flags, and V8_STATIC_ROOTS_BOOL.
ReadObject() [1/2]
template<typename IsolateT >
DirectHandle< HeapObject > v8::internal::Deserializer< IsolateT >::ReadObject [protected]
Definition at line 735 of file deserializer.cc.
                                                            {
  DirectHandle<HeapObject> ret;
  CHECK_EQ(ReadSingleBytecodeData(
               source_.Get(), SlotAccessorForHandle<IsolateT>(&ret, isolate())),
           1);
  return ret;
}
References CHECK_EQ.
ReadObject() [2/2]
template<typename IsolateT >
Handle< HeapObject > v8::internal::Deserializer< IsolateT >::ReadObject (SnapshotSpace space) [private]
Definition at line 759 of file deserializer.cc.
                                                                         {
  const int size_in_tagged = source_.GetUint30();
  const int size_in_bytes = size_in_tagged * kTaggedSize;
  // The map can't be a forward ref. If you want the map to be a forward ref,
  // then you're probably serializing the meta-map, in which case you want to
  // use the kNewContextlessMetaMap/kNewContextfulMetaMap bytecode.
  DCHECK_NE(source()->Peek(), kRegisterPendingForwardRef);
  DirectHandle<Map> map = Cast<Map>(ReadObject());
  AllocationType allocation = SpaceToAllocation(space);
  // When sharing a string table, all in-place internalizable and internalized
  // strings internalized strings are allocated in the shared heap.
  //
  // TODO(12007): When shipping, add a new SharedOld SnapshotSpace.
  if (v8_flags.shared_string_table) {
    InstanceType instance_type = map->instance_type();
    if (InstanceTypeChecker::IsInternalizedString(instance_type) ||
        String::IsInPlaceInternalizable(instance_type)) {
      allocation = isolate()
                       ->factory()
                       ->RefineAllocationTypeForInPlaceInternalizableString(
                           allocation, *map);
    }
  }
  // Filling an object's fields can cause GCs and heap walks, so this object has
  // to be in a 'sufficiently initialised' state by the time the next allocation
  // can happen. For this to be the case, the object is carefully deserialized
  // as follows:
  // * The space for the object is allocated.
  // * The map is set on the object so that the GC knows what type the object
  // has.
  // * The rest of the object is filled with a fixed Smi value
  // - This is a Smi so that tagged fields become initialized to a valid
  // tagged value.
  // - It's a fixed value, "Smi::uninitialized_deserialization_value()", so
  // that we can DCHECK for it when reading objects that are assumed to be
  // partially initialized objects.
  // * The fields of the object are deserialized in order, under the
  // assumption that objects are laid out in such a way that any fields
  // required for object iteration (e.g. length fields) are deserialized
  // before fields with objects.
  // - We ensure this is the case by DCHECKing on object allocation that the
  // previously allocated object has a valid size (see `Allocate`).
  const InSharedSpace in_shared_space =
      IsSharedAllocationType(allocation) ? kInSharedSpace : kNotInSharedSpace;
  Tagged<HeapObject> raw_obj =
      Allocate(allocation, size_in_bytes,
               HeapObject::RequiredAlignment(in_shared_space, *map));
  raw_obj->set_map_after_allocation(isolate_, *map);
  MemsetTagged(raw_obj->RawField(kTaggedSize),
               Smi::uninitialized_deserialization_value(), size_in_tagged - 1);
  DCHECK(raw_obj->CheckRequiredAlignment(isolate()));
  // Make sure BytecodeArrays have a valid age, so that the marker doesn't
  // break when making them older.
  if (IsSharedFunctionInfo(raw_obj, isolate())) {
    Cast<SharedFunctionInfo>(raw_obj)->set_age(0);
  } else if (IsEphemeronHashTable(raw_obj)) {
    // Make sure EphemeronHashTables have valid HeapObject keys, so that the
    // marker does not break when marking EphemeronHashTable, see
    // MarkingVisitorBase::VisitEphemeronHashTable.
    Tagged<EphemeronHashTable> table = Cast<EphemeronHashTable>(raw_obj);
    MemsetTagged(Cast<HeapObject>(table)->RawField(table->kElementsStartOffset),
                 ReadOnlyRoots(isolate()).undefined_value(),
                 (size_in_bytes - table->kElementsStartOffset) / kTaggedSize);
  }
#ifdef DEBUG
  PtrComprCageBase cage_base(isolate());
  // We want to make sure that all embedder pointers are initialized to null.
  if (IsJSObject(raw_obj, cage_base) &&
      Cast<JSObject>(raw_obj)->MayHaveEmbedderFields()) {
    Tagged<JSObject> js_obj = Cast<JSObject>(raw_obj);
    for (int i = 0; i < js_obj->GetEmbedderFieldCount(); ++i) {
      void* pointer;
      CHECK(EmbedderDataSlot(js_obj, i).ToAlignedPointer(main_thread_isolate(),
                                                         &pointer));
      CHECK_NULL(pointer);
    }
  } else if (IsEmbedderDataArray(raw_obj, cage_base)) {
    Tagged<EmbedderDataArray> array = Cast<EmbedderDataArray>(raw_obj);
    EmbedderDataSlot start(array, 0);
    EmbedderDataSlot end(array, array->length());
    for (EmbedderDataSlot slot = start; slot < end; ++slot) {
      void* pointer;
      CHECK(slot.ToAlignedPointer(main_thread_isolate(), &pointer));
      CHECK_NULL(pointer);
    }
  }
#endif
  Handle<HeapObject> obj = handle(raw_obj, isolate());
  back_refs_.push_back(obj);
  if (v8_flags.trace_deserialization) {
    PrintF(" %*s(set obj backref %u)\n", depth_, "",
           static_cast<int>(back_refs_.size() - 1));
  }
  ReadData(obj, 1, size_in_tagged);
  PostProcessNewObject(map, obj, space);
#ifdef DEBUG
  if (IsInstructionStream(*obj, cage_base)) {
    DCHECK(space == SnapshotSpace::kCode ||
           space == SnapshotSpace::kReadOnlyHeap);
  } else {
    DCHECK_NE(space, SnapshotSpace::kCode);
  }
  if (IsTrustedObject(*obj)) {
    DCHECK_EQ(space, SnapshotSpace::kTrusted);
  } else {
    DCHECK_NE(space, SnapshotSpace::kTrusted);
  }
#endif // DEBUG
  return obj;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), CHECK, CHECK_NULL, DCHECK, DCHECK_EQ, DCHECK_NE, v8::internal::compiler::end(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::IsSharedAllocationType(), v8::internal::kInSharedSpace, v8::internal::kNotInSharedSpace, v8::internal::kTaggedSize, v8::internal::MemsetTagged(), v8::internal::PrintF(), space, v8::internal::anonymous_namespace{deserializer.cc}::SpaceToAllocation(), and v8::internal::v8_flags.
ReadOffHeapBackingStore()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadOffHeapBackingStore (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1370 of file deserializer.cc.
                                              {
  int byte_length = source_.GetUint32();
  if (v8_flags.trace_deserialization) {
    PrintF("%*sOffHeapBackingStore [%d]\n", depth_, "", byte_length);
  }
  std::unique_ptr<BackingStore> backing_store;
  if (data == kOffHeapBackingStore) {
    backing_store = BackingStore::Allocate(main_thread_isolate(), byte_length,
                                           SharedFlag::kNotShared,
                                           InitializedFlag::kUninitialized);
  } else {
    int max_byte_length = source_.GetUint32();
    size_t page_size, initial_pages, max_pages;
    Maybe<bool> result =
        JSArrayBuffer::GetResizableBackingStorePageConfiguration(
            nullptr, byte_length, max_byte_length, kDontThrow, &page_size,
            &initial_pages, &max_pages);
    DCHECK(result.FromJust());
    USE(result);
    backing_store = BackingStore::TryAllocateAndPartiallyCommitMemory(
        main_thread_isolate(), byte_length, max_byte_length, page_size,
        initial_pages, max_pages, WasmMemoryFlag::kNotWasm,
        SharedFlag::kNotShared);
  }
  CHECK_NOT_NULL(backing_store);
  source_.CopyRaw(backing_store->buffer_start(), byte_length);
  backing_stores_.push_back(std::move(backing_store));
  return 0;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), CHECK_NOT_NULL, DCHECK, v8::internal::kDontThrow, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, v8::internal::PrintF(), v8::base::internal::result, USE, and v8::internal::v8_flags.
ReadProtectedPointerPrefix()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadProtectedPointerPrefix (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1550 of file deserializer.cc.
                                              {
  // We shouldn't have two protected pointer prefixes in a row.
  DCHECK(!next_reference_is_protected_pointer);
  // We shouldn't have a protected pointer prefix without a current object.
  DCHECK_NE(slot_accessor.object()->address(), kNullAddress);
  next_reference_is_protected_pointer = true;
  return 0;
}
References DCHECK, DCHECK_NE, and v8::base::kNullAddress.
ReadRawExternalReference()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadRawExternalReference (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1257 of file deserializer.cc.
                                              {
  DCHECK_IMPLIES(data == kSandboxedExternalReference, V8_ENABLE_SANDBOX_BOOL);
  Address address;
  source_.CopyRaw(&address, kSystemPointerSize);
  ExternalPointerTag tag = kExternalPointerNullTag;
  if (data == kSandboxedRawExternalReference) {
    tag = ReadExternalPointerTag();
  }
  if (v8_flags.trace_deserialization) {
    PrintF("%*sRawExternalReference [%" PRIxPTR ", %i]\n", depth_, "", address,
           tag);
  }
  return WriteExternalPointer(*slot_accessor.object(),
                              slot_accessor.external_pointer_slot(tag), address,
                              tag);
}
References DCHECK_IMPLIES, v8::internal::kExternalPointerNullTag, v8::internal::kSystemPointerSize, v8::internal::PrintF(), V8_ENABLE_SANDBOX_BOOL, and v8::internal::v8_flags.
ReadReadOnlyHeapRef()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadReadOnlyHeapRef (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1137 of file deserializer.cc.
                                                                            {
  uint32_t chunk_index = source_.GetUint30();
  uint32_t chunk_offset = source_.GetUint30();
  ReadOnlySpace* read_only_space = isolate()->heap()->read_only_space();
  ReadOnlyPageMetadata* page = read_only_space->pages()[chunk_index];
  Address address = page->OffsetToAddress(chunk_offset);
  Tagged<HeapObject> heap_object = HeapObject::FromAddress(address);
  if (v8_flags.trace_deserialization) {
    PrintF("%*sReadOnlyHeapRef [%u, %u] : ", depth_, "", chunk_index,
           chunk_offset);
    ShortPrint(heap_object);
    PrintF("\n");
  }
  return WriteHeapPointer(slot_accessor, heap_object,
                          GetAndResetNextReferenceDescriptor(),
                          SKIP_WRITE_BARRIER);
}
References v8::internal::BaseSpace::heap(), v8::internal::ReadOnlyPageMetadata::OffsetToAddress(), v8::internal::ReadOnlySpace::pages(), v8::internal::PrintF(), v8::internal::Heap::read_only_space(), v8::internal::ShortPrint(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::v8_flags.
ReadRegisterPendingForwardRef()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadRegisterPendingForwardRef (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1294 of file deserializer.cc.
                                              {
  ReferenceDescriptor descr = GetAndResetNextReferenceDescriptor();
  unresolved_forward_refs_.emplace_back(slot_accessor.object(),
                                        slot_accessor.offset(), descr);
  num_unresolved_forward_refs_++;
  return 1;
}
ReadRepeatedRoot() [1/2]
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadRepeatedRoot (SlotAccessor slot_accessor, int repeat_count)
Definition at line 911 of file deserializer.cc.
                                                               {
  CHECK_LE(2, repeat_count);
  uint8_t id = source_.Get();
  RootIndex root_index = static_cast<RootIndex>(id);
  if (v8_flags.trace_deserialization) {
    PrintF("%s", RootsTable::name(root_index));
  }
  DCHECK(RootsTable::IsReadOnly(root_index));
  Tagged<HeapObject> heap_object =
      Cast<HeapObject>(isolate()->root(root_index));
  for (int i = 0; i < repeat_count; i++) {
    slot_accessor.Write(heap_object, HeapObjectReferenceType::STRONG, i,
                        SKIP_WRITE_BARRIER);
  }
  return repeat_count;
}
References CHECK_LE, DCHECK, name, v8::internal::PrintF(), v8::internal::SKIP_WRITE_BARRIER, STRONG, and v8::internal::v8_flags.
ReadRepeatedRoot() [2/2]
template<typename IsolateT >
template<typename SlotGetter >
int v8::internal::Deserializer< IsolateT >::ReadRepeatedRoot (SlotGetter slot_getter, int repeat_count) [private]
ReadResolvePendingForwardRef()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadResolvePendingForwardRef (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1305 of file deserializer.cc.
                                              {
  // Pending forward refs can only be resolved after the heap object's map
  // field is deserialized; currently they only appear immediately after
  // the map field or after the 'self' indirect pointer for trusted objects.
  DCHECK(slot_accessor.offset() == HeapObject::kHeaderSize ||
         slot_accessor.offset() == ExposedTrustedObject::kHeaderSize);
  DirectHandle<HeapObject> obj = slot_accessor.object();
  int index = source_.GetUint30();
  auto& forward_ref = unresolved_forward_refs_[index];
  auto slot = SlotAccessorForHeapObject::ForSlotOffset(forward_ref.object,
                                                       forward_ref.offset);
  WriteHeapPointer(slot, obj, forward_ref.descr);
  num_unresolved_forward_refs_--;
  if (num_unresolved_forward_refs_ == 0) {
    // If there's no more pending fields, clear the entire pending field
    // vector.
    unresolved_forward_refs_.clear();
  } else {
    // Otherwise, at least clear the pending field.
    forward_ref.object = Handle<HeapObject>();
  }
  return 0;
}
References DCHECK, and v8::internal::index.
ReadRootArray()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadRootArray (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1163 of file deserializer.cc.
                                                                      {
  int id = source_.GetUint30();
  RootIndex root_index = static_cast<RootIndex>(id);
  DirectHandle<HeapObject> heap_object =
      Cast<HeapObject>(isolate()->root_handle(root_index));
  if (v8_flags.trace_deserialization) {
    PrintF("%*sRootArray [%u] : %s\n", depth_, "", id,
           RootsTable::name(root_index));
  }
  hot_objects_.Add(heap_object);
  return WriteHeapPointer(
      slot_accessor, heap_object, GetAndResetNextReferenceDescriptor(),
      RootsTable::IsReadOnly(root_index) ? SKIP_WRITE_BARRIER
                                         : UPDATE_WRITE_BARRIER);
}
References name, v8::internal::PrintF(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::v8_flags.
ReadRootArrayConstants()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadRootArrayConstants (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1562 of file deserializer.cc.
                                                                               {
  // First kRootArrayConstantsCount roots are guaranteed to be in
  // the old space.
  static_assert(static_cast<int>(RootIndex::kFirstImmortalImmovableRoot) == 0);
  static_assert(kRootArrayConstantsCount <=
                static_cast<int>(RootIndex::kLastImmortalImmovableRoot));
  RootIndex root_index = RootArrayConstant::Decode(data);
  DirectHandle<HeapObject> heap_object =
      Cast<HeapObject>(isolate()->root_handle(root_index));
  if (v8_flags.trace_deserialization) {
    PrintF("%*sRootArrayConstants [%u] : %s\n", depth_, "",
           static_cast<int>(root_index), RootsTable::name(root_index));
  }
  return slot_accessor.Write(heap_object, HeapObjectReferenceType::STRONG, 0,
                             SKIP_WRITE_BARRIER);
}
References name, v8::internal::PrintF(), v8::internal::SKIP_WRITE_BARRIER, STRONG, and v8::internal::v8_flags.
ReadSharedHeapObjectCache()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadSharedHeapObjectCache (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1205 of file deserializer.cc.
                                              {
  int cache_index = source_.GetUint30();
  // TODO(leszeks): Could we use the address of the
  // shared_heap_object_cache entry as a Handle backing?
  Tagged<HeapObject> heap_object = Cast<HeapObject>(
      main_thread_isolate()->shared_heap_object_cache()->at(cache_index));
  DCHECK(SharedHeapSerializer::ShouldBeInSharedHeapObjectCache(heap_object));
  return WriteHeapPointer(slot_accessor, heap_object,
                          GetAndResetNextReferenceDescriptor());
}
References DCHECK.
ReadSingleBytecodeData()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadSingleBytecodeData (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 992 of file deserializer.cc.
                                                                               {
  if (v8_flags.trace_deserialization) {
    PrintF("%02x ", data);
  }
  switch (data) {
    case CASE_RANGE_ALL_SPACES(kNewObject):
      return ReadNewObject(data, slot_accessor);
    case kBackref:
      return ReadBackref(data, slot_accessor);
    case kReadOnlyHeapRef:
      return ReadReadOnlyHeapRef(data, slot_accessor);
    case kRootArray:
      return ReadRootArray(data, slot_accessor);
    case kStartupObjectCache:
      return ReadStartupObjectCache(data, slot_accessor);
    case kSharedHeapObjectCache:
      return ReadSharedHeapObjectCache(data, slot_accessor);
    case kNewContextlessMetaMap:
    case kNewContextfulMetaMap:
      return ReadNewMetaMap(data, slot_accessor);
    case kSandboxedExternalReference:
    case kExternalReference:
      return ReadExternalReference(data, slot_accessor);
    case kSandboxedRawExternalReference:
      return ReadRawExternalReference(data, slot_accessor);
    case kAttachedReference:
      return ReadAttachedReference(data, slot_accessor);
    case kNop:
      return 0;
    case kRegisterPendingForwardRef:
      return ReadRegisterPendingForwardRef(data, slot_accessor);
    case kResolvePendingForwardRef:
      return ReadResolvePendingForwardRef(data, slot_accessor);
    case kSynchronize:
      // If we get here then that indicates that you have a mismatch between
      // the number of GC roots when serializing and deserializing.
      UNREACHABLE();
    case kVariableRawData:
      return ReadVariableRawData(data, slot_accessor);
    case kVariableRepeatRoot:
      return ReadVariableRepeatRoot(data, slot_accessor);
    case kOffHeapBackingStore:
    case kOffHeapResizableBackingStore:
      return ReadOffHeapBackingStore(data, slot_accessor);
    case kSandboxedApiReference:
    case kApiReference:
      return ReadApiReference(data, slot_accessor);
    case kClearedWeakReference:
      return ReadClearedWeakReference(data, slot_accessor);
    case kWeakPrefix:
      return ReadWeakPrefix(data, slot_accessor);
    case kIndirectPointerPrefix:
      return ReadIndirectPointerPrefix(data, slot_accessor);
    case kInitializeSelfIndirectPointer:
      return ReadInitializeSelfIndirectPointer(data, slot_accessor);
    case kAllocateJSDispatchEntry:
      return ReadAllocateJSDispatchEntry(data, slot_accessor);
    case kJSDispatchEntry:
      return ReadJSDispatchEntry(data, slot_accessor);
    case kProtectedPointerPrefix:
      return ReadProtectedPointerPrefix(data, slot_accessor);
    case CASE_RANGE(kRootArrayConstants, 32):
      return ReadRootArrayConstants(data, slot_accessor);
    case CASE_RANGE(kHotObject, 8):
      return ReadHotObject(data, slot_accessor);
    case CASE_RANGE(kFixedRawData, 32):
      return ReadFixedRawData(data, slot_accessor);
    case CASE_RANGE(kFixedRepeatRoot, 16):
      return ReadFixedRepeatRoot(data, slot_accessor);
#ifdef DEBUG
#define UNUSED_CASE(byte_code) \
  case byte_code: \
    UNREACHABLE();
      UNUSED_SERIALIZER_BYTE_CODES(UNUSED_CASE)
#endif
#undef UNUSED_CASE
  }
  // The above switch, including UNUSED_SERIALIZER_BYTE_CODES, covers all
  // possible bytecodes; but, clang doesn't realize this, so we have an explicit
  // UNREACHABLE here too.
  UNREACHABLE();
}
References CASE_RANGE, CASE_RANGE_ALL_SPACES, v8::internal::PrintF(), UNREACHABLE, UNUSED_SERIALIZER_BYTE_CODES, and v8::internal::v8_flags.
ReadStartupObjectCache()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadStartupObjectCache (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1185 of file deserializer.cc.
                                                                               {
  int cache_index = source_.GetUint30();
  // TODO(leszeks): Could we use the address of the startup_object_cache
  // entry as a Handle backing?
  Tagged<HeapObject> heap_object = Cast<HeapObject>(
      main_thread_isolate()->startup_object_cache()->at(cache_index));
  if (v8_flags.trace_deserialization) {
    PrintF("%*sStartupObjectCache [%u] : ", depth_, "", cache_index);
    ShortPrint(*heap_object);
    PrintF("\n");
  }
  return WriteHeapPointer(slot_accessor, heap_object,
                          GetAndResetNextReferenceDescriptor());
}
References v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
ReadVariableRawData()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadVariableRawData (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1333 of file deserializer.cc.
                                                                            {
  // This operation is only supported for tagged-size slots, else we might
  // become misaligned.
  DCHECK_EQ(decltype(slot_accessor.slot())::kSlotDataSize, kTaggedSize);
  int size_in_tagged = source_.GetUint30();
  if (v8_flags.trace_deserialization) {
    PrintF("%*sVariableRawData [%u] :", depth_, "", size_in_tagged);
    for (int i = 0; i < size_in_tagged; ++i) {
      PrintF(" %0*" PRIxTAGGED, kTaggedSize / 2,
             reinterpret_cast<const Tagged_t*>(source_.data())[i]);
    }
    PrintF("\n");
  }
  // TODO(leszeks): Only copy slots when there are Smis in the serialized
  // data.
  source_.CopySlots(slot_accessor.slot().location(), size_in_tagged);
  return size_in_tagged;
}
References DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kTaggedSize, v8::internal::PrintF(), PRIxTAGGED, and v8::internal::v8_flags.
ReadVariableRepeatRoot()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadVariableRepeatRoot (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1355 of file deserializer.cc.
                                                                               {
  int repeats = VariableRepeatRootCount::Decode(source_.GetUint30());
  if (v8_flags.trace_deserialization) {
    PrintF("%*sVariableRepeat [%u] : ", depth_, "", repeats);
  }
  int ret = ReadRepeatedRoot(slot_accessor, repeats);
  if (v8_flags.trace_deserialization) {
    PrintF("\n");
  }
  return ret;
}
References v8::internal::PrintF(), and v8::internal::v8_flags.
ReadWeakPrefix()
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::ReadWeakPrefix (uint8_t data, SlotAccessor slot_accessor) [private]
Definition at line 1441 of file deserializer.cc.
                                                                       {
  if (v8_flags.trace_deserialization) {
    PrintF("%*sWeakPrefix\n", depth_, "");
  }
  // We shouldn't have two weak prefixes in a row.
  DCHECK(!next_reference_is_weak_);
  // We shouldn't have weak refs without a current object.
  DCHECK_NE(slot_accessor.object()->address(), kNullAddress);
  next_reference_is_weak_ = true;
  return 0;
}
References DCHECK, DCHECK_NE, v8::base::kNullAddress, v8::internal::PrintF(), and v8::internal::v8_flags.
Rehash()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::Rehash [protected]
Definition at line 357 of file deserializer.cc.
                                    {
  DCHECK(should_rehash());
  for (DirectHandle<HeapObject> item : to_rehash_) {
    item->RehashBasedOnMap(isolate());
  }
}
References v8::internal::DCHECK().
should_rehash()
template<typename IsolateT >
bool v8::internal::Deserializer< IsolateT >::should_rehash () const [inline], [protected]
Definition at line 112 of file deserializer.h.
{ return should_rehash_; }
References v8::internal::Deserializer< IsolateT >::should_rehash_.
source()
template<typename IsolateT >
SnapshotByteSource* v8::internal::Deserializer< IsolateT >::source () [inline], [protected]
Definition at line 83 of file deserializer.h.
{ return &source_; }
References v8::internal::Deserializer< IsolateT >::source_.
Synchronize()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::Synchronize (VisitorSynchronization::SyncTag tag) [override], [private], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 389 of file deserializer.cc.
                                                                          {
  static const uint8_t expected = kSynchronize;
  CHECK_EQ(expected, source_.Get());
  if (v8_flags.trace_deserialization) {
    const char* name;
    switch (tag) {
#define CASE(ID, NAME) \
  case VisitorSynchronization::ID: \
    name = NAME; \
    break;
      ROOT_ID_LIST(CASE)
#undef CASE
      default:
        name = "(!unknown!)";
        break;
    }
    PrintF("Synchronize %d %s\n", tag, name);
  }
}
References CASE, CHECK_EQ, v8::internal::name, v8::internal::PrintF(), ROOT_ID_LIST, and v8::internal::v8_flags.
VisitRootPointers()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [override], [private], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 381 of file deserializer.cc.
                                                                   {
  ReadData(FullMaybeObjectSlot(start), FullMaybeObjectSlot(end));
}
References v8::internal::compiler::end().
WeakenDescriptorArrays()
template<typename IsolateT >
void v8::internal::Deserializer< IsolateT >::WeakenDescriptorArrays [protected]
Definition at line 432 of file deserializer.cc.
                                                    {
  isolate()->heap()->WeakenDescriptorArrays(std::move(new_descriptor_arrays_));
}
WriteExternalPointer()
template<typename IsolateT >
int v8::internal::Deserializer< IsolateT >::WriteExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot dest, Address value, ExternalPointerTag tag) [inline], [private]
Definition at line 248 of file deserializer.cc.
                                                                         {
  DCHECK(!next_reference_is_weak_ && !next_reference_is_indirect_pointer_ &&
         !next_reference_is_protected_pointer);
  #ifdef V8_ENABLE_SANDBOX
  ExternalPointerTable::ManagedResource* managed_resource = nullptr;
  ExternalPointerTable* owning_table = nullptr;
  ExternalPointerHandle original_handle = kNullExternalPointerHandle;
  if (IsManagedExternalPointerType(tag)) {
    // This can currently only happen during snapshot stress mode as we cannot
    // normally serialized managed resources. In snapshot stress mode, the new
    // isolate will be destroyed and the old isolate (really, the old isolate's
    // external pointer table) therefore effectively retains ownership of the
    // resource. As such, we need to save and restore the relevant fields of
    // the external resource. Once the external pointer table itself destroys
    // the managed resource when freeing the corresponding table entry, this
    // workaround can be removed again.
    DCHECK(v8_flags.stress_snapshot);
    managed_resource =
        reinterpret_cast<ExternalPointerTable::ManagedResource*>(value);
    owning_table = managed_resource->owning_table_;
    original_handle = managed_resource->ept_entry_;
    managed_resource->owning_table_ = nullptr;
    managed_resource->ept_entry_ = kNullExternalPointerHandle;
  }
#endif // V8_ENABLE_SANDBOX
  if (tag == kExternalPointerNullTag && value == kNullAddress) {
    dest.init_lazily_initialized();
  } else {
    dest.init(main_thread_isolate(), host, value, tag);
  }
#ifdef V8_ENABLE_SANDBOX
  if (managed_resource) {
    managed_resource->owning_table_ = owning_table;
    managed_resource->ept_entry_ = original_handle;
  }
#endif // V8_ENABLE_SANDBOX
  // ExternalPointers can only be written into HeapObject fields, therefore they
  // cover (kExternalPointerSlotSize / kTaggedSize) slots.
  return (kExternalPointerSlotSize / kTaggedSize);
}
WriteHeapPointer() [1/2]
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::WriteHeapPointer (SlotAccessor slot_accessor, DirectHandle< HeapObject > heap_object, ReferenceDescriptor descr, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [private]
Definition at line 233 of file deserializer.cc.
                                                      {
  if (descr.is_indirect_pointer) {
    return slot_accessor.WriteIndirectPointerTo(*heap_object, mode);
  } else if (descr.is_protected_pointer) {
    DCHECK(IsTrustedObject(*heap_object));
    return slot_accessor.WriteProtectedPointerTo(
        Cast<TrustedObject>(*heap_object), mode);
  } else {
    return slot_accessor.Write(heap_object, descr.type, 0, mode);
  }
}
WriteHeapPointer() [2/2]
template<typename IsolateT >
template<typename SlotAccessor >
int v8::internal::Deserializer< IsolateT >::WriteHeapPointer (SlotAccessor slot_accessor, Tagged< HeapObject > heap_object, ReferenceDescriptor descr, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [private]
Definition at line 220 of file deserializer.cc.
                                                                    {
  if (descr.is_indirect_pointer) {
    return slot_accessor.WriteIndirectPointerTo(heap_object, mode);
  } else {
    return slot_accessor.Write(heap_object, descr.type, 0, mode);
  }
}
WriteIndirectPointer()
template<typename IsolateT >
int v8::internal::Deserializer< IsolateT >::WriteIndirectPointer (IndirectPointerSlot dest, Tagged< HeapObject > value) [inline], [private]
Member Data Documentation
accessor_infos_
template<typename IsolateT >
DirectHandleVector<AccessorInfo> v8::internal::Deserializer< IsolateT >::accessor_infos_ [private]
Definition at line 287 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::accessor_infos().
attached_objects_
template<typename IsolateT >
DirectHandleVector<HeapObject> v8::internal::Deserializer< IsolateT >::attached_objects_ [private]
Definition at line 278 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::AddAttachedObject().
back_refs_
template<typename IsolateT >
std::vector<IndirectHandle<HeapObject> > v8::internal::Deserializer< IsolateT >::back_refs_ [private]
Definition at line 297 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::Deserializer().
backing_stores_
template<typename IsolateT >
std::vector<std::shared_ptr<BackingStore> > v8::internal::Deserializer< IsolateT >::backing_stores_ [private]
Definition at line 290 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::backing_store(), and v8::internal::Deserializer< IsolateT >::Deserializer().
depth_
template<typename IsolateT >
int v8::internal::Deserializer< IsolateT >::depth_ = 0 [private]
Definition at line 345 of file deserializer.h.
deserializing_user_code_
template<typename IsolateT >
const bool v8::internal::Deserializer< IsolateT >::deserializing_user_code_ [private]
Definition at line 320 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::deserializing_user_code().
function_template_infos_
template<typename IsolateT >
DirectHandleVector<FunctionTemplateInfo> v8::internal::Deserializer< IsolateT >::function_template_infos_ [private]
Definition at line 288 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::function_template_infos().
hot_objects_
template<typename IsolateT >
HotObjectsList v8::internal::Deserializer< IsolateT >::hot_objects_ [private]
Definition at line 283 of file deserializer.h.
isolate_
template<typename IsolateT >
IsolateT* v8::internal::Deserializer< IsolateT >::isolate_ [private]
Definition at line 275 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::isolate(), and v8::internal::Deserializer< IsolateT >::main_thread_isolate().
js_dispatch_entries_
template<typename IsolateT >
std::vector<JSDispatchHandle> v8::internal::Deserializer< IsolateT >::js_dispatch_entries_ [private]
Definition at line 300 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::Deserializer().
magic_number_
template<typename IsolateT >
uint32_t v8::internal::Deserializer< IsolateT >::magic_number_ [private]
Definition at line 281 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::Deserializer().
new_allocation_sites_
template<typename IsolateT >
DirectHandleVector<AllocationSite> v8::internal::Deserializer< IsolateT >::new_allocation_sites_ [private]
Definition at line 285 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::new_allocation_sites().
new_code_objects_
template<typename IsolateT >
DirectHandleVector<InstructionStream> v8::internal::Deserializer< IsolateT >::new_code_objects_ [private]
Definition at line 286 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::new_code_objects().
new_descriptor_arrays_
template<typename IsolateT >
GlobalHandleVector<DescriptorArray> v8::internal::Deserializer< IsolateT >::new_descriptor_arrays_ [private]
Definition at line 294 of file deserializer.h.
new_maps_
template<typename IsolateT >
DirectHandleVector<Map> v8::internal::Deserializer< IsolateT >::new_maps_ [private]
Definition at line 284 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::new_maps().
new_scripts_
template<typename IsolateT >
DirectHandleVector<Script> v8::internal::Deserializer< IsolateT >::new_scripts_ [private]
Definition at line 289 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::new_scripts().
next_reference_is_indirect_pointer_
template<typename IsolateT >
bool v8::internal::Deserializer< IsolateT >::next_reference_is_indirect_pointer_ = false [private]
Definition at line 323 of file deserializer.h.
next_reference_is_protected_pointer
template<typename IsolateT >
bool v8::internal::Deserializer< IsolateT >::next_reference_is_protected_pointer = false [private]
Definition at line 324 of file deserializer.h.
next_reference_is_weak_
template<typename IsolateT >
bool v8::internal::Deserializer< IsolateT >::next_reference_is_weak_ = false [private]
Definition at line 322 of file deserializer.h.
no_gc_stats_
template<typename IsolateT >
DisableGCStats v8::internal::Deserializer< IsolateT >::no_gc_stats_ [private]
Definition at line 343 of file deserializer.h.
num_unresolved_forward_refs_
template<typename IsolateT >
int v8::internal::Deserializer< IsolateT >::num_unresolved_forward_refs_ = 0 [private]
Definition at line 318 of file deserializer.h.
should_rehash_
template<typename IsolateT >
const bool v8::internal::Deserializer< IsolateT >::should_rehash_ [private]
Definition at line 327 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::should_rehash().
source_
template<typename IsolateT >
SnapshotByteSource v8::internal::Deserializer< IsolateT >::source_ [private]
Definition at line 280 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::source().
to_rehash_
template<typename IsolateT >
DirectHandleVector<HeapObject> v8::internal::Deserializer< IsolateT >::to_rehash_ [private]
Definition at line 328 of file deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::PushObjectToRehash().
unresolved_forward_refs_
template<typename IsolateT >
std::vector<UnresolvedForwardRef> v8::internal::Deserializer< IsolateT >::unresolved_forward_refs_ [private]
Definition at line 317 of file deserializer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/deserializer.h
/mnt/V8SourceCode/src/snapshot/deserializer.cc