cppgc::internal::ExplicitManagementImpl Class Reference
#include <explicit-management.h>
Static Private Member Functions
static void FreeUnreferencedObject (HeapHandle &, void *)
static bool Resize (void *, size_t)
Friends
template<typename T >
void subtle::FreeUnreferencedObject (HeapHandle &, T &)
template<typename T >
bool subtle::Resize (T &, AdditionalBytes)
Detailed Description
Definition at line 29 of file explicit-management.h.
Member Function Documentation
FreeUnreferencedObject()
void cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject (HeapHandle & heap_handle, void * object) [static], [private]
Definition at line 31 of file explicit-management.cc.
                                                                  {
  if (InGC(heap_handle)) {
    return;
  }
  auto& header = HeapObjectHeader::FromObject(object);
  header.Finalize();
  // `object` is guaranteed to be of type GarbageCollected, so getting the
  // BasePage is okay for regular and large objects.
  BasePage* base_page = BasePage::FromPayload(object);
#if defined(CPPGC_YOUNG_GENERATION)
  const size_t object_size = ObjectView<>(header).Size();
  if (auto& heap_base = HeapBase::From(heap_handle);
      heap_base.generational_gc_supported()) {
    heap_base.remembered_set().InvalidateRememberedSlotsInRange(
        object, reinterpret_cast<uint8_t*>(object) + object_size);
    // If this object was registered as remembered, remove it. Do that before
    // the page gets destroyed.
    heap_base.remembered_set().InvalidateRememberedSourceObject(header);
    if (header.IsMarked()) {
      base_page->DecrementMarkedBytes(
          header.IsLargeObject<AccessMode::kNonAtomic>()
              ? reinterpret_cast<const LargePage*>(
                    BasePage::FromPayload(&header))
                    ->PayloadSize()
              : header.AllocatedSize<AccessMode::kNonAtomic>());
    }
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  if (base_page->is_large()) { // Large object.
    base_page->space().RemovePage(base_page);
    base_page->heap().stats_collector()->NotifyExplicitFree(
        LargePage::From(base_page)->PayloadSize());
    LargePage::Destroy(LargePage::From(base_page));
  } else { // Regular object.
    const size_t header_size = header.AllocatedSize();
    auto* normal_page = NormalPage::From(base_page);
    auto& normal_space = *static_cast<NormalPageSpace*>(&base_page->space());
    auto& lab = normal_space.linear_allocation_buffer();
    ConstAddress payload_end = header.ObjectEnd();
    SetMemoryInaccessible(&header, header_size);
    if (payload_end == lab.start()) { // Returning to LAB.
      lab.Set(reinterpret_cast<Address>(&header), lab.size() + header_size);
      normal_page->object_start_bitmap().ClearBit(lab.start());
    } else { // Returning to free list.
      base_page->heap().stats_collector()->NotifyExplicitFree(header_size);
      normal_space.free_list().Add({&header, header_size});
      // No need to update the bitmap as the same bit is reused for the free
      // list entry.
    }
  }
}
References cppgc::internal::BasePage::DecrementMarkedBytes(), cppgc::internal::LargePage::Destroy(), cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::HeapBase::From(), cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapBase::generational_gc_supported(), cppgc::internal::BasePage::heap(), cppgc::internal::anonymous_namespace{explicit-management.cc}::InGC(), cppgc::internal::BasePage::is_large(), cppgc::internal::kNonAtomic, cppgc::internal::NormalPageSpace::linear_allocation_buffer(), cppgc::internal::StatsCollector::NotifyExplicitFree(), cppgc::internal::LargePage::PayloadSize(), cppgc::internal::BaseSpace::RemovePage(), cppgc::internal::SetMemoryInaccessible(), cppgc::internal::ObjectView< AccessMode >::Size(), cppgc::internal::BasePage::space(), and cppgc::internal::HeapBase::stats_collector().
Referenced by cppgc::subtle::FreeUnreferencedObject().
Resize()
bool cppgc::internal::ExplicitManagementImpl::Resize (void * object, size_t new_object_size) [static], [private]
Definition at line 162 of file explicit-management.cc.
                                                                        {
  // `object` is guaranteed to be of type GarbageCollected, so getting the
  // BasePage is okay for regular and large objects.
  BasePage* base_page = BasePage::FromPayload(object);
  if (InGC(base_page->heap())) {
    return false;
  }
  // TODO(chromium:1056170): Consider supporting large objects within certain
  // restrictions.
  if (base_page->is_large()) {
    return false;
  }
  const size_t new_size = RoundUp<kAllocationGranularity>(
      sizeof(HeapObjectHeader) + new_object_size);
  auto& header = HeapObjectHeader::FromObject(object);
  const size_t old_size = header.AllocatedSize();
  if (new_size > old_size) {
    return Grow(header, *base_page, new_size, new_size - old_size);
  } else if (old_size > new_size) {
    return Shrink(header, *base_page, new_size, old_size - new_size);
  }
  // Same size considering internal restrictions, e.g. alignment.
  return true;
}
References cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::internal::BasePage::heap(), cppgc::internal::anonymous_namespace{explicit-management.cc}::InGC(), cppgc::internal::BasePage::is_large(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
Referenced by cppgc::subtle::Resize().
Friends And Related Function Documentation
subtle::FreeUnreferencedObject
template<typename T >
void subtle::FreeUnreferencedObject (HeapHandle & , T &) [friend]
subtle::Resize
template<typename T >
bool subtle::Resize (T & , AdditionalBytes) [friend]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/explicit-management.h
/mnt/V8SourceCode/src/heap/cppgc/explicit-management.cc