v8::internal::Interval Class Reference
#include <regexp-ast.h>
Public Member Functions
Interval ()
Interval (int from, int to)
Interval Union (Interval that)
bool Contains (int value) const
bool is_empty () const
int from () const
int to () const
int size () const
Static Public Member Functions
static Interval Empty ()
Static Public Attributes
static constexpr int kNone = -1
Private Attributes
int from_
int to_
Detailed Description
Definition at line 56 of file regexp-ast.h.
Constructor & Destructor Documentation
Interval() [1/2]
v8::internal::Interval::Interval () [inline]
Definition at line 58 of file regexp-ast.h.
: from_(kNone), to_(kNone - 1) {} // '- 1' for branchless size().
Referenced by Empty(), and Union().
Interval() [2/2]
v8::internal::Interval::Interval (int from, int to) [inline]
Definition at line 59 of file regexp-ast.h.
: from_(from), to_(to) {}
Member Function Documentation
Contains()
bool v8::internal::Interval::Contains (int value) const [inline]
Definition at line 68 of file regexp-ast.h.
{ return (from_ <= value) && (value <= to_); }
References from_, to_, and v8::internal::value.
Empty()
static Interval v8::internal::Interval::Empty () [inline], [static]
Definition at line 66 of file regexp-ast.h.
{ return Interval(); }
References Interval().
Referenced by v8::internal::RegExpTree::CaptureRegisters(), and v8::internal::anonymous_namespace{regexp-ast.cc}::ListCaptureRegisters().
from()
int v8::internal::Interval::from () const [inline]
Definition at line 70 of file regexp-ast.h.
{ return from_; }
References from_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), v8::internal::ActionNode::ClearCaptures(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::ClearRegisters(), v8::internal::BoyerMoorePositionInfo::SetInterval(), and v8::internal::BoyerMooreLookahead::SetInterval().
is_empty()
bool v8::internal::Interval::is_empty () const [inline]
Definition at line 69 of file regexp-ast.h.
{ return from_ == kNone; }
References from_, and kNone.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::ClearRegisters(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitLookaround(), v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::VisitQuantifier(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier().
size()
int v8::internal::Interval::size () const [inline]
Definition at line 72 of file regexp-ast.h.
{ return to_ - from_ + 1; }
References from_, and to_.
Referenced by v8::internal::BoyerMoorePositionInfo::SetInterval().
to()
int v8::internal::Interval::to () const [inline]
Definition at line 71 of file regexp-ast.h.
{ return to_; }
References to_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::AddRange(), v8::internal::ActionNode::ClearCaptures(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::ClearRegisters(), v8::internal::BoyerMoorePositionInfo::SetInterval(), and v8::internal::BoyerMooreLookahead::SetInterval().
Union()
Interval v8::internal::Interval::Union (Interval that) [inline]
Definition at line 60 of file regexp-ast.h.
                                {
    if (that.from_ == kNone) return *this;
    if (from_ == kNone) return that;
    return Interval(std::min(from_, that.from_), std::max(to_, that.to_));
  }
References from_, Interval(), kNone, and to_.
Referenced by v8::internal::RegExpCapture::CaptureRegisters().
Member Data Documentation
from_
int v8::internal::Interval::from_ [private]
Definition at line 77 of file regexp-ast.h.
Referenced by Contains(), from(), is_empty(), size(), and Union().
kNone
constexpr int v8::internal::Interval::kNone = -1 [static], [constexpr]
Definition at line 74 of file regexp-ast.h.
Referenced by is_empty(), and Union().
to_
int v8::internal::Interval::to_ [private]
Definition at line 78 of file regexp-ast.h.
Referenced by Contains(), size(), to(), and Union().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-ast.h