v8::internal::SwitchStatement Class Reference
#include <ast.h>
Public Member Functions
Expression * tag () const
void set_tag (Expression *t)
ZonePtrList< CaseClause > * cases ()
Private Member Functions
SwitchStatement (Zone *zone, Expression *tag, int pos)
Private Attributes
friend Zone
Expression * tag_
ZonePtrList< CaseClause > cases_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 721 of file ast.h.
Constructor & Destructor Documentation
SwitchStatement()
v8::internal::SwitchStatement::SwitchStatement (Zone * zone, Expression * tag, int pos) [inline], [private]
Definition at line 732 of file ast.h.
      : BreakableStatement(pos, kSwitchStatement), tag_(tag), cases_(4, zone) {}
Member Function Documentation
cases()
ZonePtrList<CaseClause>* v8::internal::SwitchStatement::cases () [inline]
Definition at line 726 of file ast.h.
{ return &cases_; }
References cases_.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable(), and v8::internal::SourceRangeAstVisitor::VisitSwitchStatement().
set_tag()
void v8::internal::SwitchStatement::set_tag (Expression * t) [inline]
Definition at line 724 of file ast.h.
{ tag_ = t; }
References tag_.
Referenced by v8::internal::Parser::RewriteSwitchStatement().
tag()
Expression* v8::internal::SwitchStatement::tag () const [inline]
Definition at line 723 of file ast.h.
{ return tag_; }
References tag_.
Referenced by v8::internal::Parser::RewriteSwitchStatement().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 729 of file ast.h.
Member Data Documentation
cases_
ZonePtrList<CaseClause> v8::internal::SwitchStatement::cases_ [private]
Definition at line 736 of file ast.h.
Referenced by cases().
tag_
Expression* v8::internal::SwitchStatement::tag_ [private]
Definition at line 735 of file ast.h.
Referenced by set_tag(), and tag().
Zone
friend v8::internal::SwitchStatement::Zone [private]
Definition at line 730 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h