v8::internal::compiler::NodeHashCache::Constructor Class Reference
#include <escape-analysis-reducer.h>
Public Member Functions
Constructor (NodeHashCache *cache, Node *from)
Constructor (NodeHashCache *cache, const Operator *op, int input_count, Node **inputs, Type type)
void ReplaceValueInput (Node *input, int i)
void ReplaceInput (Node *input, int i)
Node * Get ()
Private Member Functions
Node * MutableNode ()
Private Attributes
NodeHashCache * node_cache_
Node * from_
Node * tmp_
Detailed Description
Definition at line 29 of file escape-analysis-reducer.h.
Constructor & Destructor Documentation
Constructor() [1/2]
v8::internal::compiler::NodeHashCache::Constructor::Constructor (NodeHashCache * cache, Node * from) [inline]
Definition at line 32 of file escape-analysis-reducer.h.
        : node_cache_(cache), from_(from), tmp_(nullptr) {}
Constructor() [2/2]
v8::internal::compiler::NodeHashCache::Constructor::Constructor (NodeHashCache * cache, const Operator * op, int input_count, Node ** inputs, Type type)
Definition at line 365 of file escape-analysis-reducer.cc.
    : node_cache_(cache), from_(nullptr) {
  if (!node_cache_->temp_nodes_.empty()) {
    tmp_ = node_cache_->temp_nodes_.back();
    node_cache_->temp_nodes_.pop_back();
    int tmp_input_count = tmp_->InputCount();
    if (input_count <= tmp_input_count) {
      tmp_->TrimInputCount(input_count);
    }
    for (int i = 0; i < input_count; ++i) {
      if (i < tmp_input_count) {
        tmp_->ReplaceInput(i, inputs[i]);
      } else {
        tmp_->AppendInput(node_cache_->graph_->zone(), inputs[i]);
      }
    }
    NodeProperties::ChangeOp(tmp_, op);
  } else {
    tmp_ = node_cache_->graph_->NewNode(op, input_count, inputs);
  }
  NodeProperties::SetType(tmp_, type);
}
References v8::internal::compiler::Node::AppendInput(), v8::internal::ZoneVector< T >::back(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::NodeHashCache::graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::TFGraph::NewNode(), node_cache_, v8::internal::ZoneVector< T >::pop_back(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::compiler::NodeHashCache::temp_nodes_, tmp_, v8::internal::compiler::Node::TrimInputCount(), v8::internal::tracing::type, and v8::internal::compiler::TFGraph::zone().
Member Function Documentation
Get()
Node * v8::internal::compiler::NodeHashCache::Constructor::Get ()
Definition at line 390 of file escape-analysis-reducer.cc.
                                    {
  DCHECK(tmp_ || from_);
  Node* node;
  if (!tmp_) {
    node = node_cache_->Query(from_);
    if (!node) node = from_;
  } else {
    node = node_cache_->Query(tmp_);
    if (node) {
      node_cache_->temp_nodes_.push_back(tmp_);
    } else {
      node = tmp_;
      node_cache_->Insert(node);
    }
  }
  tmp_ = from_ = nullptr;
  return node;
}
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState().
MutableNode()
Node * v8::internal::compiler::NodeHashCache::Constructor::MutableNode () [private]
Definition at line 409 of file escape-analysis-reducer.cc.
                                            {
  DCHECK(tmp_ || from_);
  if (!tmp_) {
    if (node_cache_->temp_nodes_.empty()) {
      tmp_ = node_cache_->graph_->CloneNode(from_);
    } else {
      tmp_ = node_cache_->temp_nodes_.back();
      node_cache_->temp_nodes_.pop_back();
      int from_input_count = from_->InputCount();
      int tmp_input_count = tmp_->InputCount();
      if (from_input_count <= tmp_input_count) {
        tmp_->TrimInputCount(from_input_count);
      }
      for (int i = 0; i < from_input_count; ++i) {
        if (i < tmp_input_count) {
          tmp_->ReplaceInput(i, from_->InputAt(i));
        } else {
          tmp_->AppendInput(node_cache_->graph_->zone(), from_->InputAt(i));
        }
      }
      NodeProperties::SetType(tmp_, NodeProperties::GetType(from_));
      NodeProperties::ChangeOp(tmp_, from_->op());
    }
  }
  return tmp_;
}
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::compiler::NodeProperties::SetType().
Referenced by ReplaceInput(), and ReplaceValueInput().
ReplaceInput()
void v8::internal::compiler::NodeHashCache::Constructor::ReplaceInput (Node * input, int i) [inline]
Definition at line 44 of file escape-analysis-reducer.h.
                                          {
      if (!tmp_ && input == from_->InputAt(i)) return;
      Node* node = MutableNode();
      node->ReplaceInput(i, input);
    }
References from_, v8::internal::compiler::Node::InputAt(), MutableNode(), v8::internal::compiler::Node::ReplaceInput(), and tmp_.
Referenced by v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState().
ReplaceValueInput()
void v8::internal::compiler::NodeHashCache::Constructor::ReplaceValueInput (Node * input, int i) [inline]
Definition at line 39 of file escape-analysis-reducer.h.
                                               {
      if (!tmp_ && input == NodeProperties::GetValueInput(from_, i)) return;
      Node* node = MutableNode();
      NodeProperties::ReplaceValueInput(node, input, i);
    }
References from_, v8::internal::compiler::NodeProperties::GetValueInput(), MutableNode(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), and tmp_.
Referenced by v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState().
Member Data Documentation
from_
Node* v8::internal::compiler::NodeHashCache::Constructor::from_ [private]
Definition at line 58 of file escape-analysis-reducer.h.
Referenced by ReplaceInput(), and ReplaceValueInput().
node_cache_
NodeHashCache* v8::internal::compiler::NodeHashCache::Constructor::node_cache_ [private]
Definition at line 56 of file escape-analysis-reducer.h.
Referenced by Constructor().
tmp_
Node* v8::internal::compiler::NodeHashCache::Constructor::tmp_ [private]
Definition at line 60 of file escape-analysis-reducer.h.
Referenced by Constructor(), ReplaceInput(), and ReplaceValueInput().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/escape-analysis-reducer.h
/mnt/V8SourceCode/src/compiler/escape-analysis-reducer.cc