v8::internal::compiler::KeyedAccessMode Class Reference
#include <processed-feedback.h>
Public Member Functions
AccessMode access_mode () const
bool IsLoad () const
bool IsStore () const
KeyedAccessLoadMode load_mode () const
KeyedAccessStoreMode store_mode () const
bool string_keys () const
Static Public Member Functions
static KeyedAccessMode FromNexus (FeedbackNexus const &nexus)
Private Member Functions
KeyedAccessMode (AccessMode access_mode, KeyedAccessLoadMode load_mode, bool string_keys)
KeyedAccessMode (AccessMode access_mode, KeyedAccessStoreMode store_mode, bool string_keys)
Private Attributes
AccessMode const access_mode_
xx xx xx xx xx xx xx xx xx
union {
 KeyedAccessLoadMode load_mode_
 KeyedAccessStoreMode store_mode_
};
bool string_keys_
Detailed Description
Definition at line 102 of file processed-feedback.h.
Constructor & Destructor Documentation
KeyedAccessMode() [1/2]
v8::internal::compiler::KeyedAccessMode::KeyedAccessMode (AccessMode access_mode, KeyedAccessLoadMode load_mode, bool string_keys) [private]
Definition at line 368 of file js-heap-broker.cc.
    : access_mode_(access_mode),
      load_mode_(load_mode),
      string_keys_(string_keys) {
  CHECK(!IsStore());
  CHECK(IsLoad());
}
References CHECK, IsLoad(), and IsStore().
Referenced by FromNexus().
KeyedAccessMode() [2/2]
v8::internal::compiler::KeyedAccessMode::KeyedAccessMode (AccessMode access_mode, KeyedAccessStoreMode store_mode, bool string_keys) [private]
Definition at line 377 of file js-heap-broker.cc.
    : access_mode_(access_mode),
      store_mode_(store_mode),
      string_keys_(string_keys) {
  CHECK(!IsLoad());
  CHECK(IsStore());
}
References CHECK, IsLoad(), and IsStore().
Member Function Documentation
access_mode()
AccessMode v8::internal::compiler::KeyedAccessMode::access_mode () const
Definition at line 347 of file js-heap-broker.cc.
{ return access_mode_; }
References access_mode_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfos(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), and v8::internal::compiler::JSNativeContextSpecialization::TryRefineElementAccessFeedback().
FromNexus()
KeyedAccessMode v8::internal::compiler::KeyedAccessMode::FromNexus (FeedbackNexus const & nexus) [static]
Definition at line 317 of file js-heap-broker.cc.
                                                                     {
  FeedbackSlotKind kind = nexus.kind();
  constexpr bool kStringKeysUnsupported = false;
  if (IsKeyedLoadICKind(kind)) {
    bool string_keys = nexus.GetKeyType() == IcCheckType::kProperty;
    return KeyedAccessMode(AccessMode::kLoad, nexus.GetKeyedAccessLoadMode(),
                           string_keys);
  }
  if (IsKeyedHasICKind(kind)) {
    return KeyedAccessMode(AccessMode::kHas, nexus.GetKeyedAccessLoadMode(),
                           kStringKeysUnsupported);
  }
  if (IsDefineKeyedOwnICKind(kind)) {
    return KeyedAccessMode(AccessMode::kDefine, nexus.GetKeyedAccessStoreMode(),
                           kStringKeysUnsupported);
  }
  if (IsKeyedStoreICKind(kind)) {
    bool string_keys = nexus.GetKeyType() == IcCheckType::kProperty;
    return KeyedAccessMode(AccessMode::kStore, nexus.GetKeyedAccessStoreMode(),
                           string_keys);
  }
  if (IsStoreInArrayLiteralICKind(kind) ||
      IsDefineKeyedOwnPropertyInLiteralKind(kind)) {
    return KeyedAccessMode(AccessMode::kStoreInLiteral,
                           nexus.GetKeyedAccessStoreMode(),
                           kStringKeysUnsupported);
  }
  UNREACHABLE();
}
References v8::internal::FeedbackNexus::GetKeyedAccessLoadMode(), v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), v8::internal::FeedbackNexus::GetKeyType(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsStoreInArrayLiteralICKind(), v8::internal::compiler::kDefine, KeyedAccessMode(), v8::internal::compiler::kHas, v8::internal::FeedbackNexus::kind(), v8::internal::compiler::kLoad, v8::internal::kProperty, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, string_keys(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess().
IsLoad()
bool v8::internal::compiler::KeyedAccessMode::IsLoad () const
Definition at line 349 of file js-heap-broker.cc.
                                   {
  return access_mode_ == AccessMode::kLoad || access_mode_ == AccessMode::kHas;
}
References access_mode_, v8::internal::compiler::kHas, and v8::internal::compiler::kLoad.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), KeyedAccessMode(), and load_mode().
IsStore()
bool v8::internal::compiler::KeyedAccessMode::IsStore () const
Definition at line 352 of file js-heap-broker.cc.
                                    {
  return access_mode_ == AccessMode::kStore ||
         access_mode_ == AccessMode::kDefine ||
         access_mode_ == AccessMode::kStoreInLiteral;
}
References access_mode_, v8::internal::compiler::kDefine, v8::internal::compiler::kStore, and v8::internal::compiler::kStoreInLiteral.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), KeyedAccessMode(), and store_mode().
load_mode()
KeyedAccessLoadMode v8::internal::compiler::KeyedAccessMode::load_mode () const
Definition at line 358 of file js-heap-broker.cc.
                                                     {
  CHECK(IsLoad());
  return load_mode_;
}
References CHECK, IsLoad(), and load_mode_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnJSArrayOrJSObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess().
store_mode()
KeyedAccessStoreMode v8::internal::compiler::KeyedAccessMode::store_mode () const
Definition at line 363 of file js-heap-broker.cc.
                                                       {
  CHECK(IsStore());
  return store_mode_;
}
References CHECK, IsStore(), and store_mode_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnTypedArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementStoreOnJSArrayOrJSObject().
string_keys()
bool v8::internal::compiler::KeyedAccessMode::string_keys () const [inline]
Definition at line 114 of file processed-feedback.h.
{ return string_keys_; }
References string_keys_.
Referenced by FromNexus(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), and v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForKeyedPropertyAccess().
Member Data Documentation
union { ... } [private]
access_mode_
AccessMode const v8::internal::compiler::KeyedAccessMode::access_mode_ [private]
Definition at line 117 of file processed-feedback.h.
Referenced by access_mode(), IsLoad(), and IsStore().
load_mode_
KeyedAccessLoadMode v8::internal::compiler::KeyedAccessMode::load_mode_
Definition at line 119 of file processed-feedback.h.
Referenced by load_mode().
store_mode_
KeyedAccessStoreMode v8::internal::compiler::KeyedAccessMode::store_mode_
Definition at line 120 of file processed-feedback.h.
Referenced by store_mode().
string_keys_
bool v8::internal::compiler::KeyedAccessMode::string_keys_ [private]
Definition at line 122 of file processed-feedback.h.
Referenced by string_keys().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/processed-feedback.h
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc