v8::internal::FlagList::HelpOptions Class Reference
#include <flags.h>
Public Types
enum ExitBehavior : bool { kExit = true
, kDontExit = false
 }
Public Member Functions
HelpOptions (ExitBehavior exit_behavior=kExit, const char *usage=nullptr)
bool ShouldExit ()
bool HasUsage ()
const char * usage ()
Private Attributes
ExitBehavior exit_behavior_
const char * usage_
Detailed Description
Definition at line 79 of file flags.h.
Member Enumeration Documentation
ExitBehavior
enum v8::internal::FlagList::HelpOptions::ExitBehavior : bool
Enumerator
kExit
kDontExit
Definition at line 81 of file flags.h.
: bool { kExit = true, kDontExit = false };
Constructor & Destructor Documentation
HelpOptions()
v8::internal::FlagList::HelpOptions::HelpOptions (ExitBehavior exit_behavior = kExit, const char * usage = nullptr) [inline], [explicit]
Definition at line 83 of file flags.h.
        : exit_behavior_(exit_behavior), usage_(usage) {}
Member Function Documentation
HasUsage()
bool v8::internal::FlagList::HelpOptions::HasUsage () [inline]
Definition at line 88 of file flags.h.
{ return usage_ != nullptr; }
Referenced by v8::internal::FlagList::SetFlagsFromCommandLine().
ShouldExit()
bool v8::internal::FlagList::HelpOptions::ShouldExit () [inline]
Definition at line 87 of file flags.h.
{ return exit_behavior_ == kExit; }
Referenced by v8::internal::FlagList::SetFlagsFromCommandLine().
usage()
const char* v8::internal::FlagList::HelpOptions::usage () [inline]
Definition at line 89 of file flags.h.
{ return usage_; }
Referenced by v8::internal::FlagList::SetFlagsFromCommandLine().
Member Data Documentation
exit_behavior_
ExitBehavior v8::internal::FlagList::HelpOptions::exit_behavior_ [private]
Definition at line 92 of file flags.h.
usage_
const char* v8::internal::FlagList::HelpOptions::usage_ [private]
Definition at line 93 of file flags.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/flags/flags.h