v8::internal::compiler::LoadElimination::AbstractMaps Class Reference
Public Member Functions
AbstractMaps (Zone *zone)
AbstractMaps (Node *object, ZoneRefSet< Map > maps, Zone *zone)
AbstractMaps const * Extend (Node *object, ZoneRefSet< Map > maps, Zone *zone) const
bool Lookup (Node *object, ZoneRefSet< Map > *object_maps) const
AbstractMaps const * Kill (const AliasStateInfo &alias_info, Zone *zone) const
bool Equals (AbstractMaps const *that) const
AbstractMaps const * Merge (AbstractMaps const *that, Zone *zone) const
void Print () const
Private Attributes
ZoneMap< Node *, ZoneRefSet< Map > > info_for_node_
Detailed Description
Definition at line 196 of file load-elimination.h.
Constructor & Destructor Documentation
AbstractMaps() [1/2]
v8::internal::compiler::LoadElimination::AbstractMaps::AbstractMaps (Zone * zone) [explicit]
Definition at line 341 of file load-elimination.cc.
    : info_for_node_(zone) {}
AbstractMaps() [2/2]
v8::internal::compiler::LoadElimination::AbstractMaps::AbstractMaps (Node * object, ZoneRefSet< Map > maps, Zone * zone)
Definition at line 344 of file load-elimination.cc.
    : info_for_node_(zone) {
  object = ResolveRenames(object);
  info_for_node_.insert(std::make_pair(object, maps));
}
References info_for_node_, and v8::internal::compiler::anonymous_namespace{load-elimination.cc}::ResolveRenames().
Member Function Documentation
Equals()
bool v8::internal::compiler::LoadElimination::AbstractMaps::Equals (AbstractMaps const * that) const [inline]
Definition at line 206 of file load-elimination.h.
                                                {
      return this == that || this->info_for_node_ == that->info_for_node_;
    }
References info_for_node_.
Referenced by v8::internal::compiler::LoadElimination::AbstractState::Equals().
Extend()
LoadElimination::AbstractMaps const * v8::internal::compiler::LoadElimination::AbstractMaps::Extend (Node * object, ZoneRefSet< Map > maps, Zone * zone) const
Definition at line 389 of file load-elimination.cc.
                                                          {
  AbstractMaps* that = zone->New<AbstractMaps>(*this);
  if (that->info_for_node_.size() >= kMaxTrackedObjects) {
    // We are tracking too many objects, which leads to bad performance.
    // Delete one to avoid the map from becoming bigger.
    that->info_for_node_.erase(that->info_for_node_.begin());
    if (V8_UNLIKELY(v8_flags.trace_turbo_bailouts)) {
      std::cout
          << "Bailing out in Load Elimination because of kMaxTrackedObjects\n";
    }
  }
  object = ResolveRenames(object);
  that->info_for_node_[object] = maps;
  return that;
}
References info_for_node_, v8::internal::compiler::LoadElimination::kMaxTrackedObjects, v8::internal::Zone::New(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::ResolveRenames(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::SetMaps().
Kill()
LoadElimination::AbstractMaps const * v8::internal::compiler::LoadElimination::AbstractMaps::Kill (const AliasStateInfo & alias_info, Zone * zone) const
Definition at line 359 of file load-elimination.cc.
                                                        {
  for (auto info1 : this->info_for_node_) {
    if (alias_info.MayAlias(info1.first)) {
      AbstractMaps* that = zone->New<AbstractMaps>(zone);
      for (auto info2 : this->info_for_node_) {
        if (!alias_info.MayAlias(info2.first))
          that->info_for_node_.insert(info2);
      }
      return that;
    }
  }
  return this;
}
References info_for_node_, v8::internal::compiler::LoadElimination::AliasStateInfo::MayAlias(), v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::KillMaps().
Lookup()
bool v8::internal::compiler::LoadElimination::AbstractMaps::Lookup (Node * object, ZoneRefSet< Map > * object_maps) const
Definition at line 351 of file load-elimination.cc.
                                                                               {
  auto it = info_for_node_.find(ResolveRenames(object));
  if (it == info_for_node_.end()) return false;
  *object_maps = it->second;
  return true;
}
References v8::internal::compiler::anonymous_namespace{load-elimination.cc}::ResolveRenames().
Merge()
LoadElimination::AbstractMaps const * v8::internal::compiler::LoadElimination::AbstractMaps::Merge (AbstractMaps const * that, Zone * zone) const
Definition at line 374 of file load-elimination.cc.
                                                {
  if (this->Equals(that)) return this;
  AbstractMaps* copy = zone->New<AbstractMaps>(zone);
  for (auto this_it : this->info_for_node_) {
    Node* this_object = this_it.first;
    ZoneRefSet<Map> this_maps = this_it.second;
    auto that_it = that->info_for_node_.find(this_object);
    if (that_it != that->info_for_node_.end() && that_it->second == this_maps) {
      copy->info_for_node_.insert(this_it);
    }
  }
  return copy;
}
References v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Equals(), info_for_node_, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::AbstractState::Merge().
Print()
void v8::internal::compiler::LoadElimination::AbstractMaps::Print () const
Definition at line 406 of file load-elimination.cc.
                                              {
  AllowHandleDereference allow_handle_dereference;
  StdoutStream os;
  for (auto pair : info_for_node_) {
    os << " #" << pair.first->id() << ":" << pair.first->op()->mnemonic()
       << std::endl;
    ZoneRefSet<Map> const& maps = pair.second;
    for (size_t i = 0; i < maps.size(); ++i) {
      os << " - " << Brief(*maps[i].object()) << std::endl;
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::ZoneCompactSet< T >::size().
Member Data Documentation
info_for_node_
ZoneMap<Node*, ZoneRefSet<Map> > v8::internal::compiler::LoadElimination::AbstractMaps::info_for_node_ [private]
Definition at line 214 of file load-elimination.h.
Referenced by AbstractMaps(), Equals(), Extend(), Kill(), and Merge().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/load-elimination.h
/mnt/V8SourceCode/src/compiler/load-elimination.cc