v8_inspector::protocol::Binary Class Reference
#include <string-util.h>
Public Member Functions
Binary ()
const uint8_t * data () const
size_t size () const
String toBase64 () const
Static Public Member Functions
static Binary fromBase64 (const String &base64, bool *success)
static Binary fromSpan (v8_crdtp::span< uint8_t > span)
static Binary fromSpan (v8::MemorySpan< const uint8_t > span)
Private Member Functions
Binary (std::shared_ptr< std::vector< uint8_t >> bytes)
Private Attributes
std::shared_ptr< std::vector< uint8_t > > bytes_
Detailed Description
Definition at line 47 of file string-util.h.
Constructor & Destructor Documentation
Binary() [1/2]
v8_inspector::protocol::Binary::Binary () [inline]
Definition at line 49 of file string-util.h.
: bytes_(std::make_shared<std::vector<uint8_t>>()) {}
Referenced by fromBase64().
Binary() [2/2]
v8_inspector::protocol::Binary::Binary (std::shared_ptr< std::vector< uint8_t >> bytes) [inline], [explicit], [private]
Definition at line 66 of file string-util.h.
      : bytes_(bytes) {}
Member Function Documentation
data()
const uint8_t* v8_inspector::protocol::Binary::data () const [inline]
Definition at line 51 of file string-util.h.
{ return bytes_->data(); }
fromBase64()
Binary v8_inspector::protocol::Binary::fromBase64 (const String & base64, bool * success) [static]
Definition at line 59 of file string-util.cc.
                                                             {
  if (base64.isEmpty()) {
    *success = true;
    return {};
  }
  *success = false;
  // Fail if the length is invalid or decoding would overflow.
  if (base64.length() % 4 != 0 || base64.length() + 4 < base64.length()) {
    return {};
  }
  std::vector<uint8_t> result;
  result.reserve(3 * base64.length() / 4);
  char pad = '=';
  // Iterate groups of four
  for (size_t i = 0; i < base64.length(); i += 4) {
    uint8_t a = 0, b = 0, c = 0, d = 0;
    if (!DecodeByte(base64[i + 0]).To(&a)) return {};
    if (!DecodeByte(base64[i + 1]).To(&b)) return {};
    if (!DecodeByte(base64[i + 2]).To(&c)) {
      // Padding is allowed only in the group on the last two positions
      if (i + 4 < base64.length() || base64[i + 2] != pad ||
          base64[i + 3] != pad) {
        return {};
      }
    }
    if (!DecodeByte(base64[i + 3]).To(&d)) {
      // Padding is allowed only in the group on the last two positions
      if (i + 4 < base64.length() || base64[i + 3] != pad) {
        return {};
      }
    }
    result.push_back((a << 2) | (b >> 4));
    if (base64[i + 2] != '=') result.push_back((0xFF & (b << 4)) | (c >> 2));
    if (base64[i + 3] != '=') result.push_back((0xFF & (c << 6)) | d);
  }
  *success = true;
  return Binary(std::make_shared<std::vector<uint8_t>>(std::move(result)));
}
References Binary(), v8_inspector::protocol::anonymous_namespace{string-util.cc}::DecodeByte(), v8_inspector::String16::isEmpty(), v8_inspector::String16::length(), and v8::base::internal::result.
fromSpan() [1/2]
static Binary v8_inspector::protocol::Binary::fromSpan (v8::MemorySpan< const uint8_t > span) [inline], [static]
Definition at line 58 of file string-util.h.
                                                           {
    return Binary(
        std::make_shared<std::vector<uint8_t>>(span.begin(), span.end()));
  }
References v8::MemorySpan< T >::begin(), and v8::MemorySpan< T >::end().
fromSpan() [2/2]
static Binary v8_inspector::protocol::Binary::fromSpan (v8_crdtp::span< uint8_t > span) [inline], [static]
Definition at line 55 of file string-util.h.
                                                     {
    return fromSpan(v8::MemorySpan<const uint8_t>(span.begin(), span.size()));
  }
Referenced by v8_inspector::V8DebuggerAgentImpl::getScriptSource(), and v8_inspector::V8DebuggerAgentImpl::getWasmBytecode().
size()
size_t v8_inspector::protocol::Binary::size () const [inline]
Definition at line 52 of file string-util.h.
{ return bytes_->size(); }
Referenced by toBase64().
toBase64()
String v8_inspector::protocol::Binary::toBase64 () const
Definition at line 34 of file string-util.cc.
                              {
  const char* table =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  if (size() == 0) return {};
  std::basic_string<UChar> result;
  result.reserve(4 * ((size() + 2) / 3));
  uint8_t last = 0;
  for (size_t n = 0; n < size();) {
    auto split = SplitByte((*bytes_)[n], 2 + 2 * (n % 3));
    result.push_back(table[split.first | last]);
    ++n;
    if (n < size() && n % 3 == 0) {
      result.push_back(table[split.second]);
      last = 0;
    } else {
      last = split.second;
    }
  }
  result.push_back(table[last]);
  while (result.size() % 4 > 0) result.push_back('=');
  return String16(std::move(result));
}
References bytes_, v8::base::internal::result, size(), v8::internal::libvtune::split(), and v8_inspector::protocol::anonymous_namespace{string-util.cc}::SplitByte().
Member Data Documentation
bytes_
std::shared_ptr<std::vector<uint8_t> > v8_inspector::protocol::Binary::bytes_ [private]
Definition at line 64 of file string-util.h.
Referenced by toBase64().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/string-util.h
/mnt/V8SourceCode/src/inspector/string-util.cc