v8::internal::ZoneAllocationPolicy Class Reference
#include <zone.h>
Public Member Functions
ZoneAllocationPolicy ()
ZoneAllocationPolicy (Zone *zone)
template<typename T , typename TypeTag = T[]>
T * AllocateArray (size_t length)
template<typename T , typename TypeTag = T[]>
void DeleteArray (T *p, size_t length)
Zone * zone () const
Private Attributes
Zone * zone_
Detailed Description
Definition at line 349 of file zone.h.
Constructor & Destructor Documentation
ZoneAllocationPolicy() [1/2]
v8::internal::ZoneAllocationPolicy::ZoneAllocationPolicy () [inline]
Definition at line 352 of file zone.h.
: zone_(nullptr) {}
ZoneAllocationPolicy() [2/2]
v8::internal::ZoneAllocationPolicy::ZoneAllocationPolicy (Zone * zone) [inline], [explicit]
Definition at line 353 of file zone.h.
: zone_(zone) {}
Member Function Documentation
AllocateArray()
template<typename T , typename TypeTag = T[]>
T* v8::internal::ZoneAllocationPolicy::AllocateArray (size_t length) [inline]
Definition at line 356 of file zone.h.
                                            {
    return zone()->AllocateArray<T, TypeTag>(length);
  }
References v8::internal::Zone::AllocateArray(), v8::internal::length, T, and zone().
DeleteArray()
template<typename T , typename TypeTag = T[]>
void v8::internal::ZoneAllocationPolicy::DeleteArray (T * p, size_t length) [inline]
Definition at line 360 of file zone.h.
                                                  {
    zone()->DeleteArray<T, TypeTag>(p, length);
  }
References v8::internal::Zone::DeleteArray(), v8::internal::length, T, and zone().
zone()
Zone* v8::internal::ZoneAllocationPolicy::zone () const [inline]
Definition at line 364 of file zone.h.
{ return zone_; }
References zone_.
Referenced by AllocateArray(), and DeleteArray().
Member Data Documentation
zone_
Zone* v8::internal::ZoneAllocationPolicy::zone_ [private]
Definition at line 367 of file zone.h.
Referenced by zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/zone/zone.h