v8::ScriptOrModule Class Reference
A container type that holds relevant metadata for module loading.
#include <v8-script.h>
Public Member Functions
Local< Value > GetResourceName ()
The name that was passed by the embedder as ResourceName to the ScriptOrigin.
Local< Data > HostDefinedOptions ()
The options that were passed by the embedder as HostDefinedOptions to the ScriptOrigin.
Detailed Description
A container type that holds relevant metadata for module loading.
This is passed back to the embedder as part of HostImportModuleDynamicallyCallback for module loading.
Definition at line 42 of file v8-script.h.
Member Function Documentation
GetResourceName()
Local< Value > v8::ScriptOrModule::GetResourceName ()
The name that was passed by the embedder as ResourceName to the ScriptOrigin.
This can be either a v8::String or v8::Undefined.
Definition at line 1968 of file api.cc.
                                             {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return ToApiHandle<Value>(i::direct_handle(obj->resource_name(), i_isolate));
}
References v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), and v8::Utils::OpenDirectHandle().
HostDefinedOptions()
Local< Data > v8::ScriptOrModule::HostDefinedOptions ()
The options that were passed by the embedder as HostDefinedOptions to the ScriptOrigin.
Definition at line 1975 of file api.cc.
                                               {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return ToApiHandle<Data>(
      i::direct_handle(obj->host_defined_options(), i_isolate));
}
References v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc