v8::internal::wasm::NativeModuleSerializer Class Reference
Public Member Functions
NativeModuleSerializer (const NativeModule *, base::Vector< WasmCode *const >, base::Vector< WellKnownImport const >)
NativeModuleSerializer (const NativeModuleSerializer &)=delete
NativeModuleSerializer & operator= (const NativeModuleSerializer &)=delete
size_t Measure () const
bool Write (Writer *writer)
Private Member Functions
size_t MeasureCode (const WasmCode *) const
void WriteHeader (Writer *, size_t total_code_size)
void WriteCode (const WasmCode *, Writer *, const NativeModule::CallIndirectTargetMap &)
void WriteTieringBudget (Writer *writer)
uint32_t CanonicalSigIdToModuleLocalTypeId (uint32_t canonical_sig_id)
Private Attributes
const NativeModule *const native_module_
const base::Vector< WasmCode *const > code_table_
const base::Vector< WellKnownImport const > import_statuses_
std::unordered_map< uint32_t, uint32_t > canonical_sig_ids_to_module_local_ids_
bool write_called_ = false
size_t total_written_code_ = 0
int num_turbofan_functions_ = 0
Detailed Description
Definition at line 306 of file wasm-serialization.cc.
Constructor & Destructor Documentation
NativeModuleSerializer() [1/2]
v8::internal::wasm::NativeModuleSerializer::NativeModuleSerializer (const NativeModule * module, base::Vector< WasmCode *const > code_table, base::Vector< WellKnownImport const > import_statuses)
Definition at line 335 of file wasm-serialization.cc.
    : native_module_(module),
      code_table_(code_table),
      import_statuses_(import_statuses) {
  DCHECK_NOT_NULL(native_module_);
  // TODO(mtrofin): persist the export wrappers. Ideally, we'd only persist
  // the unique ones, i.e. the cache.
}
References DCHECK_NOT_NULL, and native_module_.
NativeModuleSerializer() [2/2]
v8::internal::wasm::NativeModuleSerializer::NativeModuleSerializer (const NativeModuleSerializer &) [delete]
Member Function Documentation
CanonicalSigIdToModuleLocalTypeId()
uint32_t v8::internal::wasm::NativeModuleSerializer::CanonicalSigIdToModuleLocalTypeId (uint32_t canonical_sig_id) [private]
Definition at line 573 of file wasm-serialization.cc.
                               {
  if (canonical_sig_ids_to_module_local_ids_.empty()) {
    const WasmModule* module = native_module_->module();
    DCHECK_GE(kMaxUInt32, module->isorecursive_canonical_type_ids.size());
    size_t num_types = module->types.size();
    DCHECK_EQ(num_types, module->isorecursive_canonical_type_ids.size());
    for (uint32_t local_id = 0; local_id < num_types; ++local_id) {
      // Only add function signatures.
      if (!module->has_signature(ModuleTypeIndex{local_id})) continue;
      CanonicalTypeIndex canonical_id =
          module->canonical_sig_id(ModuleTypeIndex{local_id});
      // Try to emplace, skip if an entry exists already. It does not matter
      // which local type ID we use if multiple types got canonicalized to the
      // same ID.
      canonical_sig_ids_to_module_local_ids_.emplace(
          std::make_pair(canonical_id.index, local_id));
    }
  }
  auto it = canonical_sig_ids_to_module_local_ids_.find(canonical_sig_id);
  DCHECK_NE(canonical_sig_ids_to_module_local_ids_.end(), it);
  return it->second;
}
References v8::internal::wasm::WasmModule::canonical_sig_id(), canonical_sig_ids_to_module_local_ids_, DCHECK_EQ, DCHECK_GE, DCHECK_NE, v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::TypeIndex::index, v8::internal::wasm::WasmModule::isorecursive_canonical_type_ids, v8::internal::kMaxUInt32, v8::internal::wasm::NativeModule::module(), native_module_, and v8::internal::wasm::WasmModule::types.
Referenced by WriteCode().
Measure()
size_t v8::internal::wasm::NativeModuleSerializer::Measure () const
Definition at line 358 of file wasm-serialization.cc.
                                             {
  // From {WriteHeader}:
  size_t size = sizeof(WasmDetectedFeatures::StorageType) +
                sizeof(size_t) + // total code size
                sizeof(bool) + // all functions validated
                sizeof(typename CompileTimeImportFlags::StorageType) +
                sizeof(uint32_t) + // length of constants_module.
                native_module_->compile_imports().constants_module().size() +
                import_statuses_.size() * sizeof(WellKnownImport);
  // From {WriteCode}, called repeatedly.
  for (WasmCode* code : code_table_) {
    size += MeasureCode(code);
  }
  // Tiering budget, wrote in {Write} directly.
  size += native_module_->module()->num_declared_functions * sizeof(uint32_t);
  return size;
}
References v8::internal::bool, code, code_table_, v8::internal::wasm::NativeModule::compile_imports(), v8::internal::wasm::CompileTimeImports::constants_module(), import_statuses_, MeasureCode(), v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::wasm::WasmModule::num_declared_functions, and size().
Referenced by v8::internal::wasm::WasmSerializer::GetSerializedNativeModuleSize(), and v8::internal::wasm::WasmSerializer::SerializeNativeModule().
MeasureCode()
size_t v8::internal::wasm::NativeModuleSerializer::MeasureCode (const WasmCode * code) const [private]
Definition at line 346 of file wasm-serialization.cc.
                                                                     {
  if (code == nullptr) return sizeof(uint8_t);
  DCHECK_EQ(WasmCode::kWasmFunction, code->kind());
  if (code->tier() != ExecutionTier::kTurbofan) {
    return sizeof(uint8_t);
  }
  return kCodeHeaderSize + code->instructions().size() +
         code->reloc_info().size() + code->source_positions().size() +
         code->inlining_positions().size() +
         code->protected_instructions_data().size() + code->deopt_data().size();
}
References code, DCHECK_EQ, v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kCodeHeaderSize, v8::internal::wasm::kTurbofan, and v8::internal::wasm::WasmCode::kWasmFunction.
Referenced by Measure().
operator=()
NativeModuleSerializer& v8::internal::wasm::NativeModuleSerializer::operator= (const NativeModuleSerializer &) [delete]
Write()
bool v8::internal::wasm::NativeModuleSerializer::Write (Writer * writer)
Definition at line 597 of file wasm-serialization.cc.
                                                 {
  DCHECK(!write_called_);
  write_called_ = true;
  size_t total_code_size = 0;
  for (WasmCode* code : code_table_) {
    if (code && code->tier() == ExecutionTier::kTurbofan) {
      DCHECK(IsAligned(code->instructions().size(), kCodeAlignment));
      total_code_size += code->instructions().size();
    }
  }
  WriteHeader(writer, total_code_size);
  NativeModule::CallIndirectTargetMap function_index_map =
      native_module_->CreateIndirectCallTargetToFunctionIndexMap();
  for (WasmCode* code : code_table_) {
    WriteCode(code, writer, function_index_map);
  }
  // No TurboFan-compiled functions in jitless mode.
  if (!v8_flags.wasm_jitless) {
    // If not a single function was written, serialization was not successful.
    if (num_turbofan_functions_ == 0) return false;
  }
  // Make sure that the serialized total code size was correct.
  CHECK_EQ(total_written_code_, total_code_size);
  WriteTieringBudget(writer);
  return true;
}
References CHECK_EQ, code, code_table_, v8::internal::wasm::NativeModule::CreateIndirectCallTargetToFunctionIndexMap(), v8::internal::DCHECK(), IsAligned(), v8::internal::kCodeAlignment, v8::internal::wasm::kTurbofan, native_module_, num_turbofan_functions_, total_written_code_, v8::internal::v8_flags, write_called_, WriteCode(), WriteHeader(), and WriteTieringBudget().
Referenced by v8::internal::wasm::WasmSerializer::SerializeNativeModule().
WriteCode()
void v8::internal::wasm::NativeModuleSerializer::WriteCode (const WasmCode * code, Writer * writer, const NativeModule::CallIndirectTargetMap & function_index_map) [private]
Definition at line 417 of file wasm-serialization.cc.
                                                                 {
  if (code == nullptr) {
    writer->Write(kLazyFunction);
    return;
  }
  DCHECK_EQ(WasmCode::kWasmFunction, code->kind());
  // Only serialize TurboFan code, as Liftoff code can contain breakpoints or
  // non-relocatable constants.
  if (code->tier() != ExecutionTier::kTurbofan) {
    // We check if the function has been executed already. If so, we serialize
    // it as {kEagerFunction} so that upon deserialization the function will
    // get eagerly compiled with Liftoff (if enabled). If the function has not
    // been executed yet, we serialize it as {kLazyFunction}, and the function
    // will not get compiled upon deserialization.
    NativeModule* native_module = code->native_module();
    uint32_t budget = native_module
                          ->tiering_budget_array()[declared_function_index(
                              native_module->module(), code->index())]
                          .load(std::memory_order_relaxed);
    writer->Write(budget == static_cast<uint32_t>(v8_flags.wasm_tiering_budget)
                      ? kLazyFunction
                      : kEagerFunction);
    return;
  }
  ++num_turbofan_functions_;
  writer->Write(kTurboFanFunction);
  // Write the size of the entire code section, followed by the code header.
  writer->Write(code->constant_pool_offset());
  writer->Write(code->safepoint_table_offset());
  writer->Write(code->handler_table_offset());
  writer->Write(code->code_comments_offset());
  writer->Write(code->jump_table_info_offset());
  writer->Write(code->unpadded_binary_size());
  writer->Write(code->stack_slots());
  writer->Write(code->ool_spills());
  writer->Write(code->raw_tagged_parameter_slots_for_serialization());
  writer->Write(code->instructions().length());
  writer->Write(code->reloc_info().length());
  writer->Write(code->source_positions().length());
  writer->Write(code->inlining_positions().length());
  writer->Write(code->deopt_data().length());
  writer->Write(code->protected_instructions_data().length());
  writer->Write(code->kind());
  writer->Write(code->tier());
  // Get a pointer to the destination buffer, to hold relocated code.
  uint8_t* serialized_code_start = writer->current_buffer().begin();
  uint8_t* code_start = serialized_code_start;
  size_t code_size = code->instructions().size();
  writer->Skip(code_size);
  // Write the reloc info, source positions, inlining positions and protected
  // code.
  writer->WriteVector(code->reloc_info());
  writer->WriteVector(code->source_positions());
  writer->WriteVector(code->inlining_positions());
  writer->WriteVector(code->deopt_data());
  writer->WriteVector(code->protected_instructions_data());
#if V8_TARGET_ARCH_MIPS64 || V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_PPC64 || \
    V8_TARGET_ARCH_S390X || V8_TARGET_ARCH_RISCV32 || V8_TARGET_ARCH_RISCV64
  // On platforms that don't support misaligned word stores, copy to an aligned
  // buffer if necessary so we can relocate the serialized code.
  std::unique_ptr<uint8_t[]> aligned_buffer;
  if (!IsAligned(reinterpret_cast<Address>(serialized_code_start),
                 kSystemPointerSize)) {
    // 'uint8_t' does not guarantee an alignment but seems to work well enough
    // in practice.
    aligned_buffer.reset(new uint8_t[code_size]);
    code_start = aligned_buffer.get();
  }
#endif
  memcpy(code_start, code->instructions().begin(), code_size);
  // Relocate the code.
  constexpr int kMask =
      RelocInfo::ModeMask(RelocInfo::WASM_CALL) |
      RelocInfo::ModeMask(RelocInfo::WASM_STUB_CALL) |
      RelocInfo::ModeMask(RelocInfo::WASM_CANONICAL_SIG_ID) |
      RelocInfo::ModeMask(RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY) |
      RelocInfo::ModeMask(RelocInfo::EXTERNAL_REFERENCE) |
      RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE) |
      RelocInfo::ModeMask(RelocInfo::INTERNAL_REFERENCE_ENCODED);
  RelocIterator orig_iter(code->instructions(), code->reloc_info(),
                          code->constant_pool(), kMask);
  WritableJitAllocation jit_allocation =
      WritableJitAllocation::ForNonExecutableMemory(
          reinterpret_cast<Address>(code_start), code->instructions().size(),
          ThreadIsolation::JitAllocationType::kWasmCode);
  for (WritableRelocIterator iter(
           jit_allocation, {code_start, code->instructions().size()},
           code->reloc_info(),
           reinterpret_cast<Address>(code_start) + code->constant_pool_offset(),
           kMask);
       !iter.done(); iter.next(), orig_iter.next()) {
    RelocInfo::Mode mode = orig_iter.rinfo()->rmode();
    switch (mode) {
      case RelocInfo::WASM_CALL: {
        Address orig_target = orig_iter.rinfo()->wasm_call_address();
        uint32_t tag =
            native_module_->GetFunctionIndexFromJumpTableSlot(orig_target);
        SetWasmCalleeTag(iter.rinfo(), tag);
      } break;
      case RelocInfo::WASM_STUB_CALL: {
        Address target = orig_iter.rinfo()->wasm_stub_call_address();
        uint32_t tag = static_cast<uint32_t>(
            native_module_->GetBuiltinInJumptableSlot(target));
        SetWasmCalleeTag(iter.rinfo(), tag);
      } break;
      case RelocInfo::WASM_CANONICAL_SIG_ID: {
        uint32_t canonical_sig_id = orig_iter.rinfo()->wasm_canonical_sig_id();
        uint32_t module_local_sig_id =
            CanonicalSigIdToModuleLocalTypeId(canonical_sig_id);
        iter.rinfo()->set_wasm_canonical_sig_id(module_local_sig_id);
      } break;
      case RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY: {
        WasmCodePointer target =
            orig_iter.rinfo()->wasm_code_pointer_table_entry();
        uint32_t function_index = function_index_map.at(target);
        iter.rinfo()->set_wasm_code_pointer_table_entry(
            WasmCodePointer{function_index}, SKIP_ICACHE_FLUSH);
      } break;
      case RelocInfo::EXTERNAL_REFERENCE: {
        Address orig_target = orig_iter.rinfo()->target_external_reference();
        uint32_t ext_ref_tag =
            ExternalReferenceList::Get().tag_from_address(orig_target);
        SetWasmCalleeTag(iter.rinfo(), ext_ref_tag);
      } break;
      case RelocInfo::INTERNAL_REFERENCE:
      case RelocInfo::INTERNAL_REFERENCE_ENCODED: {
        Address orig_target = orig_iter.rinfo()->target_internal_reference();
        Address offset = orig_target - code->instruction_start();
        Assembler::deserialization_set_target_internal_reference_at(
            iter.rinfo()->pc(), offset, jit_allocation, mode);
      } break;
      default:
        UNREACHABLE();
    }
  }
  // If we copied to an aligned buffer, copy code into serialized buffer.
  if (code_start != serialized_code_start) {
    memcpy(serialized_code_start, code_start, code_size);
  }
  total_written_code_ += code_size;
}
References CanonicalSigIdToModuleLocalTypeId(), code, DCHECK_EQ, v8::internal::wasm::declared_function_index(), v8::internal::Assembler::deserialization_set_target_internal_reference_at(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, v8::internal::WritableJitAllocation::ForNonExecutableMemory(), v8::internal::compiler::turboshaft::Get(), v8::internal::wasm::NativeModule::GetBuiltinInJumptableSlot(), v8::internal::wasm::NativeModule::GetFunctionIndexFromJumpTableSlot(), v8::internal::RelocInfo::INTERNAL_REFERENCE, v8::internal::RelocInfo::INTERNAL_REFERENCE_ENCODED, IsAligned(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kEagerFunction, v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kLazyFunction, v8::internal::kSystemPointerSize, v8::internal::wasm::kTurbofan, v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::kTurboFanFunction, v8::internal::ThreadIsolation::kWasmCode, v8::internal::wasm::WasmCode::kWasmFunction, mode(), v8::internal::RelocInfo::ModeMask(), v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::RelocIteratorBase< RelocInfoT >::next(), num_turbofan_functions_, v8::internal::RelocIteratorBase< RelocInfoT >::rinfo(), v8::internal::RelocInfo::rmode(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), size(), v8::internal::SKIP_ICACHE_FLUSH, v8::internal::RelocInfo::target_external_reference(), v8::internal::RelocInfo::target_internal_reference(), v8::internal::wasm::NativeModule::tiering_budget_array(), total_written_code_, v8::internal::UNREACHABLE(), v8::internal::v8_flags, v8::internal::RelocInfo::WASM_CALL, v8::internal::RelocInfo::wasm_call_address(), v8::internal::RelocInfo::WASM_CANONICAL_SIG_ID, v8::internal::RelocInfo::wasm_canonical_sig_id(), v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY, v8::internal::RelocInfo::wasm_code_pointer_table_entry(), v8::internal::RelocInfo::WASM_STUB_CALL, and v8::internal::RelocInfo::wasm_stub_call_address().
Referenced by Write().
WriteHeader()
void v8::internal::wasm::NativeModuleSerializer::WriteHeader (Writer * writer, size_t total_code_size) [private]
Definition at line 379 of file wasm-serialization.cc.
                                                                 {
  // TODO(eholk): We need to properly preserve the flag whether the trap
  // handler was used or not when serializing.
  // Serialize the set of detected features; this contains
  // - all features detected during module decoding,
  // - all features detected during function body decoding (if lazy validation
  // is disabled), and
  // - some features detected during compilation; some might still be missing
  // because installing code and publishing detected features is not atomic.
  writer->Write(
      native_module_->compilation_state()->detected_features().ToIntegral());
  writer->Write(total_code_size);
  // We do not ship lazy validation, so in most cases all functions will be
  // validated. Thus only write out a single bit instead of serializing the
  // information per function.
  const bool fully_validated = !v8_flags.wasm_lazy_validation;
  writer->Write(fully_validated);
#ifdef DEBUG
  if (fully_validated) {
    const WasmModule* module = native_module_->module();
    for (auto& function : module->declared_functions()) {
      DCHECK(module->function_was_validated(function.func_index));
    }
  }
#endif
  const CompileTimeImports& compile_imports = native_module_->compile_imports();
  const std::string& constants_module = compile_imports.constants_module();
  writer->Write(compile_imports.flags().ToIntegral());
  writer->Write(static_cast<uint32_t>(constants_module.size()));
  writer->WriteVector(base::VectorOf(constants_module));
  writer->WriteVector(base::VectorOf(import_statuses_));
}
References v8::internal::wasm::NativeModule::compilation_state(), v8::internal::wasm::NativeModule::compile_imports(), v8::internal::wasm::CompileTimeImports::constants_module(), v8::internal::DCHECK(), v8::internal::wasm::WasmModule::declared_functions(), v8::internal::wasm::CompilationState::detected_features(), v8::internal::wasm::CompileTimeImports::flags(), v8::internal::wasm::WasmModule::function_was_validated(), import_statuses_, v8::internal::wasm::NativeModule::module(), native_module_, v8::internal::string, v8::base::EnumSet< E, T >::ToIntegral(), v8::internal::v8_flags, and v8::base::VectorOf().
Referenced by Write().
WriteTieringBudget()
void v8::internal::wasm::NativeModuleSerializer::WriteTieringBudget (Writer * writer) [private]
Definition at line 565 of file wasm-serialization.cc.
                                                              {
  for (size_t i = 0; i < native_module_->module()->num_declared_functions;
       ++i) {
    writer->Write(native_module_->tiering_budget_array()[i].load(
        std::memory_order_relaxed));
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::NativeModule::module(), native_module_, and v8::internal::wasm::NativeModule::tiering_budget_array().
Referenced by Write().
Member Data Documentation
canonical_sig_ids_to_module_local_ids_
std::unordered_map<uint32_t, uint32_t> v8::internal::wasm::NativeModuleSerializer::canonical_sig_ids_to_module_local_ids_ [private]
Definition at line 329 of file wasm-serialization.cc.
Referenced by CanonicalSigIdToModuleLocalTypeId().
code_table_
const base::Vector<WasmCode* const> v8::internal::wasm::NativeModuleSerializer::code_table_ [private]
Definition at line 326 of file wasm-serialization.cc.
Referenced by Measure(), and Write().
import_statuses_
const base::Vector<WellKnownImport const> v8::internal::wasm::NativeModuleSerializer::import_statuses_ [private]
Definition at line 327 of file wasm-serialization.cc.
Referenced by Measure(), and WriteHeader().
native_module_
const NativeModule* const v8::internal::wasm::NativeModuleSerializer::native_module_ [private]
Definition at line 325 of file wasm-serialization.cc.
Referenced by CanonicalSigIdToModuleLocalTypeId(), Measure(), NativeModuleSerializer(), Write(), WriteCode(), WriteHeader(), and WriteTieringBudget().
num_turbofan_functions_
int v8::internal::wasm::NativeModuleSerializer::num_turbofan_functions_ = 0 [private]
Definition at line 332 of file wasm-serialization.cc.
Referenced by Write(), and WriteCode().
total_written_code_
size_t v8::internal::wasm::NativeModuleSerializer::total_written_code_ = 0 [private]
Definition at line 331 of file wasm-serialization.cc.
Referenced by Write(), and WriteCode().
write_called_
bool v8::internal::wasm::NativeModuleSerializer::write_called_ = false [private]
Definition at line 330 of file wasm-serialization.cc.
Referenced by Write().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc