v8::internal::Coverage Class Reference
#include <debug-coverage.h>
Static Public Member Functions
static std::unique_ptr< Coverage > CollectPrecise (Isolate *isolate)
static std::unique_ptr< Coverage > CollectBestEffort (Isolate *isolate)
static V8_EXPORT_PRIVATE void SelectMode (Isolate *isolate, debug::CoverageMode mode)
Private Member Functions
Coverage ()=default
Static Private Member Functions
static std::unique_ptr< Coverage > Collect (Isolate *isolate, v8::debug::CoverageMode collectionMode)
Detailed Description
Definition at line 53 of file debug-coverage.h.
Constructor & Destructor Documentation
Coverage()
v8::internal::Coverage::Coverage () [private], [default]
Referenced by Collect().
Member Function Documentation
Collect()
std::unique_ptr< Coverage > v8::internal::Coverage::Collect (Isolate * isolate, v8::debug::CoverageMode collectionMode) [static], [private]
Definition at line 703 of file debug-coverage.cc.
                                                           {
  // Unsupported if jitless mode is enabled at build-time since related
  // optimizations deactivate invocation count updates.
  CHECK(!V8_JITLESS_BOOL);
  // Collect call counts for all functions.
  SharedToCounterMap counter_map;
  CollectAndMaybeResetCounts(isolate, &counter_map, collection_mode);
  // Iterate shared function infos of every script and build a mapping
  // between source ranges and invocation counts.
  std::unique_ptr<Coverage> result(new Coverage());
  std::vector<Handle<Script>> scripts;
  Script::Iterator script_it(isolate);
  for (Tagged<Script> script = script_it.Next(); !script.is_null();
       script = script_it.Next()) {
    if (script->IsUserJavaScript()) scripts.push_back(handle(script, isolate));
  }
  for (Handle<Script> script : scripts) {
    // Create and add new script data.
    result->emplace_back(script);
    std::vector<CoverageFunction>* functions = &result->back().functions;
    std::vector<SharedFunctionInfoAndCount> sorted;
    {
      // Sort functions by start position, from outer to inner functions.
      SharedFunctionInfo::ScriptIterator infos(isolate, *script);
      for (Tagged<SharedFunctionInfo> info = infos.Next(); !info.is_null();
           info = infos.Next()) {
        sorted.emplace_back(handle(info, isolate), counter_map.Get(info));
      }
      std::sort(sorted.begin(), sorted.end());
    }
    // Stack to track nested functions, referring function by index.
    std::vector<size_t> nesting;
    // Use sorted list to reconstruct function nesting.
    for (const SharedFunctionInfoAndCount& v : sorted) {
      DirectHandle<SharedFunctionInfo> info = v.info;
      int start = v.start;
      int end = v.end;
      uint32_t count = v.count;
      // Find the correct outer function based on start position.
      //
      // This is, in general, not robust when considering two functions with
      // identical source ranges; then the notion of inner and outer is unclear.
      // Identical source ranges arise when the source range of top-most entity
      // (e.g. function) in the script is identical to the whole script, e.g.
      // <script>function foo() {}<script>. The script has its own shared
      // function info, which has the same source range as the SFI for `foo`.
      // Node.js creates an additional wrapper for scripts (again with identical
      // source range) and those wrappers will have a call count of zero even if
      // the wrapped script was executed (see v8:9212). We mitigate this issue
      // by sorting top-level SFIs first among SFIs with the same source range:
      // This ensures top-level SFIs are processed first. If a top-level SFI has
      // a non-zero call count, it gets recorded due to `function_is_relevant`
      // below (e.g. script wrappers), while top-level SFIs with zero call count
      // do not get reported (this ensures node's extra wrappers do not get
      // reported). If two SFIs with identical source ranges get reported, we
      // report them in decreasing order of call count, as in all known cases
      // this corresponds to the nesting order. In the case of the script tag
      // example above, we report the zero call count of `foo` last. As it turns
      // out, embedders started to rely on functions being reported in nesting
      // order.
      // TODO(jgruber): Investigate whether it is possible to remove node's
      // extra top-level wrapper script, or change its source range, or ensure
      // that it follows the invariant that nesting order is descending count
      // order for SFIs with identical source ranges.
      while (!nesting.empty() && functions->at(nesting.back()).end <= start) {
        nesting.pop_back();
      }
      if (count != 0) {
        switch (collection_mode) {
          case v8::debug::CoverageMode::kBlockCount:
          case v8::debug::CoverageMode::kPreciseCount:
            break;
          case v8::debug::CoverageMode::kBlockBinary:
          case v8::debug::CoverageMode::kPreciseBinary:
            count = info->has_reported_binary_coverage() ? 0 : 1;
            info->set_has_reported_binary_coverage(true);
            break;
          case v8::debug::CoverageMode::kBestEffort:
            count = 1;
            break;
        }
      }
      Handle<String> name = SharedFunctionInfo::DebugName(isolate, info);
      CoverageFunction function(start, end, count, name);
      if (IsBlockMode(collection_mode) && info->HasCoverageInfo(isolate)) {
        CollectBlockCoverage(isolate, &function, *info, collection_mode);
      }
      // Only include a function range if itself or its parent function is
      // covered, or if it contains non-trivial block coverage.
      bool is_covered = (count != 0);
      bool parent_is_covered =
          (!nesting.empty() && functions->at(nesting.back()).count != 0);
      bool has_block_coverage = !function.blocks.empty();
      bool function_is_relevant =
          (is_covered || parent_is_covered || has_block_coverage);
      // It must also have a non-empty source range (otherwise it is not
      // interesting to report).
      bool has_nonempty_source_range = function.HasNonEmptySourceRange();
      if (has_nonempty_source_range && function_is_relevant) {
        nesting.push_back(functions->size());
        functions->emplace_back(function);
      }
      if (v8_flags.trace_block_coverage) {
        PrintBlockCoverage(&function, *info, has_nonempty_source_range,
                           function_is_relevant);
      }
    }
    // Remove entries for scripts that have no coverage.
    if (functions->empty()) result->pop_back();
  }
  return result;
}
References CHECK, v8::internal::anonymous_namespace{debug-coverage.cc}::CollectAndMaybeResetCounts(), v8::internal::anonymous_namespace{debug-coverage.cc}::CollectBlockCoverage(), Coverage(), v8::internal::SharedFunctionInfo::DebugName(), v8::internal::compiler::end(), v8::internal::SharedToCounterMap::Get(), v8::internal::handle(), v8::internal::anonymous_namespace{debug-coverage.cc}::IsBlockMode(), v8::debug::kBestEffort, v8::debug::kBlockBinary, v8::debug::kBlockCount, v8::debug::kPreciseBinary, v8::debug::kPreciseCount, v8::internal::name, v8::internal::Script::Iterator::Next(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::anonymous_namespace{debug-coverage.cc}::PrintBlockCoverage(), v8::base::internal::result, v8::internal::script, v8::base::sort(), v8::internal::v8_flags, and V8_JITLESS_BOOL.
Referenced by CollectBestEffort(), and CollectPrecise().
CollectBestEffort()
std::unique_ptr< Coverage > v8::internal::Coverage::CollectBestEffort (Isolate * isolate) [static]
Definition at line 621 of file debug-coverage.cc.
                                                                    {
  return Collect(isolate, v8::debug::CoverageMode::kBestEffort);
}
References Collect(), and v8::debug::kBestEffort.
Referenced by v8::debug::Coverage::CollectBestEffort(), and v8::internal::RUNTIME_FUNCTION().
CollectPrecise()
std::unique_ptr< Coverage > v8::internal::Coverage::CollectPrecise (Isolate * isolate) [static]
Definition at line 607 of file debug-coverage.cc.
                                                                 {
  DCHECK(!isolate->is_best_effort_code_coverage());
  std::unique_ptr<Coverage> result =
      Collect(isolate, isolate->code_coverage_mode());
  if (isolate->is_precise_binary_code_coverage() ||
      isolate->is_block_binary_code_coverage()) {
    // We do not have to hold onto feedback vectors for invocations we already
    // reported. So we can reset the list.
    isolate->SetFeedbackVectorsForProfilingTools(
        ReadOnlyRoots(isolate).empty_array_list());
  }
  return result;
}
References v8::internal::Isolate::code_coverage_mode(), Collect(), v8::internal::DCHECK(), v8::internal::Isolate::is_best_effort_code_coverage(), v8::internal::Isolate::is_block_binary_code_coverage(), v8::internal::Isolate::is_precise_binary_code_coverage(), v8::base::internal::result, and v8::internal::Isolate::SetFeedbackVectorsForProfilingTools().
Referenced by v8::debug::Coverage::CollectPrecise(), and v8::internal::RUNTIME_FUNCTION().
SelectMode()
void v8::internal::Coverage::SelectMode (Isolate * isolate, debug::CoverageMode mode) [static]
Definition at line 834 of file debug-coverage.cc.
                                                                  {
  if (mode != isolate->code_coverage_mode()) {
    // Changing the coverage mode can change the bytecode that would be
    // generated for a function, which can interfere with lazy source positions,
    // so just force source position collection whenever there's such a change.
    isolate->CollectSourcePositionsForAllBytecodeArrays();
    // Changing the coverage mode changes the generated bytecode and hence it is
    // not safe to flush bytecode. Set a flag here, so we can disable bytecode
    // flushing.
    isolate->set_disable_bytecode_flushing(true);
  }
  switch (mode) {
    case debug::CoverageMode::kBestEffort:
      // Note that DevTools switches back to best-effort coverage once the
      // recording is stopped. Since we delete coverage infos at that point, any
      // following coverage recording (without reloads) will be at function
      // granularity.
      isolate->debug()->RemoveAllCoverageInfos();
      isolate->SetFeedbackVectorsForProfilingTools(
          ReadOnlyRoots(isolate).undefined_value());
      break;
    case debug::CoverageMode::kBlockBinary:
    case debug::CoverageMode::kBlockCount:
    case debug::CoverageMode::kPreciseBinary:
    case debug::CoverageMode::kPreciseCount: {
      HandleScope scope(isolate);
      // Remove all optimized function. Optimized and inlined functions do not
      // increment invocation count.
      Deoptimizer::DeoptimizeAll(isolate);
      std::vector<Handle<JSFunction>> funcs_needing_feedback_vector;
      {
        HeapObjectIterator heap_iterator(isolate->heap());
        for (Tagged<HeapObject> o = heap_iterator.Next(); !o.is_null();
             o = heap_iterator.Next()) {
          if (IsJSFunction(o)) {
            Tagged<JSFunction> func = Cast<JSFunction>(o);
            if (func->has_closure_feedback_cell_array()) {
              funcs_needing_feedback_vector.push_back(
                  Handle<JSFunction>(func, isolate));
            }
          } else if (IsBinaryMode(mode) && IsSharedFunctionInfo(o)) {
            // If collecting binary coverage, reset
            // SFI::has_reported_binary_coverage to avoid optimizing / inlining
            // functions before they have reported coverage.
            Tagged<SharedFunctionInfo> shared = Cast<SharedFunctionInfo>(o);
            shared->set_has_reported_binary_coverage(false);
          } else if (IsFeedbackVector(o)) {
            // In any case, clear any collected invocation counts.
            Cast<FeedbackVector>(o)->clear_invocation_count(kRelaxedStore);
          }
        }
      }
      for (DirectHandle<JSFunction> func : funcs_needing_feedback_vector) {
        IsCompiledScope is_compiled_scope(
            func->shared()->is_compiled_scope(isolate));
        CHECK(is_compiled_scope.is_compiled());
        JSFunction::EnsureFeedbackVector(isolate, func, &is_compiled_scope);
      }
      // Root all feedback vectors to avoid early collection.
      isolate->MaybeInitializeVectorListFromHeap();
      break;
    }
  }
  isolate->set_code_coverage_mode(mode);
}
References CHECK, v8::internal::Isolate::code_coverage_mode(), v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::Isolate::debug(), v8::internal::Deoptimizer::DeoptimizeAll(), v8::internal::JSFunction::EnsureFeedbackVector(), v8::internal::Isolate::heap(), v8::internal::IsCompiledScope::is_compiled(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::anonymous_namespace{debug-coverage.cc}::IsBinaryMode(), v8::debug::kBestEffort, v8::debug::kBlockBinary, v8::debug::kBlockCount, v8::debug::kPreciseBinary, v8::debug::kPreciseCount, v8::kRelaxedStore, v8::internal::Isolate::MaybeInitializeVectorListFromHeap(), mode(), v8::internal::HeapObjectIterator::Next(), v8::internal::Debug::RemoveAllCoverageInfos(), v8::internal::Isolate::set_code_coverage_mode(), and v8::internal::Isolate::SetFeedbackVectorsForProfilingTools().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::debug::Coverage::SelectMode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-coverage.h
/mnt/V8SourceCode/src/debug/debug-coverage.cc