v8::internal::StringToBigIntHelper< IsolateT > Class Template Reference
Public Types
enum class Behavior { kStringToBigInt
, kLiteral
 }
Public Member Functions
StringToBigIntHelper (IsolateT *isolate, DirectHandle< String > string)
StringToBigIntHelper (IsolateT *isolate, const uint8_t *string, size_t length)
void ParseOneByte (const uint8_t *start) final
void ParseTwoByte (const base::uc16 *start) final
MaybeHandle< BigInt > GetResult ()
std::unique_ptr< char[]> DecimalString (bigint::Processor *processor)
IsolateT * isolate ()
Private Member Functions
template<class Char >
void ParseInternal (const Char *start)
AllocationType allocation_type ()
Private Attributes
IsolateT * isolate_
bigint::FromStringAccumulator accumulator_ {BigInt::kMaxLength}
Behavior behavior_
Additional Inherited Members
Detailed Description
template<typename IsolateT>
class v8::internal::StringToBigIntHelper< IsolateT >
Definition at line 997 of file conversions.cc.
Member Enumeration Documentation
Behavior
template<typename IsolateT >
enum v8::internal::StringToBigIntHelper::Behavior [strong]
Enumerator
kStringToBigInt
kLiteral
Definition at line 999 of file conversions.cc.
{ kStringToBigInt, kLiteral };
Constructor & Destructor Documentation
StringToBigIntHelper() [1/2]
template<typename IsolateT >
v8::internal::StringToBigIntHelper< IsolateT >::StringToBigIntHelper (IsolateT * isolate, DirectHandle< String > string) [inline]
Definition at line 1002 of file conversions.cc.
      : StringToIntHelper(string),
        isolate_(isolate),
        behavior_(Behavior::kStringToBigInt) {
    set_allow_binary_and_octal_prefixes();
    set_disallow_trailing_junk();
  }
References v8::internal::StringToIntHelper::set_allow_binary_and_octal_prefixes(), and v8::internal::StringToIntHelper::set_disallow_trailing_junk().
StringToBigIntHelper() [2/2]
template<typename IsolateT >
v8::internal::StringToBigIntHelper< IsolateT >::StringToBigIntHelper (IsolateT * isolate, const uint8_t * string, size_t length) [inline]
Definition at line 1012 of file conversions.cc.
      : StringToIntHelper(string, length),
        isolate_(isolate),
        behavior_(Behavior::kLiteral) {
    set_allow_binary_and_octal_prefixes();
  }
References v8::internal::kLiteral, and v8::internal::StringToIntHelper::set_allow_binary_and_octal_prefixes().
Member Function Documentation
allocation_type()
template<typename IsolateT >
AllocationType v8::internal::StringToBigIntHelper< IsolateT >::allocation_type () [inline], [private]
Definition at line 1093 of file conversions.cc.
                                   {
    // For literals, we pretenure the allocated BigInt, since it's about
    // to be stored in the interpreter's constants array.
    return behavior_ == Behavior::kLiteral ? AllocationType::kOld
                                           : AllocationType::kYoung;
  }
References v8::internal::StringToBigIntHelper< IsolateT >::behavior_, v8::internal::StringToBigIntHelper< IsolateT >::kLiteral, v8::internal::kOld, and v8::internal::kYoung.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::GetResult().
DecimalString()
template<typename IsolateT >
std::unique_ptr<char[]> v8::internal::StringToBigIntHelper< IsolateT >::DecimalString (bigint::Processor * processor) [inline]
Definition at line 1055 of file conversions.cc.
                                                                  {
    DCHECK_EQ(behavior_, Behavior::kLiteral);
    ParseInt();
    if (state() == State::kZero) {
      // Input may have been "0x0" or similar.
      return std::unique_ptr<char[]>(new char[2]{'0', '\0'});
    }
    DCHECK_EQ(state(), State::kDone);
    int num_digits = accumulator_.ResultLength();
    base::SmallVector<bigint::digit_t, 8> digit_storage(num_digits);
    bigint::RWDigits digits(digit_storage.data(), num_digits);
    processor->FromString(digits, &accumulator_);
    uint32_t num_chars = bigint::ToStringResultLength(digits, 10, false);
    std::unique_ptr<char[]> out(new char[num_chars + 1]);
    processor->ToString(out.get(), &num_chars, digits, 10, false);
    out[num_chars] = '\0';
    return out;
  }
References v8::internal::StringToBigIntHelper< IsolateT >::accumulator_, v8::internal::StringToBigIntHelper< IsolateT >::behavior_, v8::base::SmallVector< T, kSize, Allocator >::data(), DCHECK_EQ, v8::bigint::Processor::FromString(), v8::internal::StringToBigIntHelper< IsolateT >::kLiteral, v8::internal::kZero, v8::internal::StringToIntHelper::ParseInt(), v8::bigint::FromStringAccumulator::ResultLength(), v8::internal::StringToIntHelper::state(), v8::bigint::Processor::ToString(), and v8::bigint::ToStringResultLength().
Referenced by v8::internal::BigIntLiteralToDecimal().
GetResult()
template<typename IsolateT >
MaybeHandle<BigInt> v8::internal::StringToBigIntHelper< IsolateT >::GetResult () [inline]
Definition at line 1024 of file conversions.cc.
                                  {
    ParseInt();
    if (behavior_ == Behavior::kStringToBigInt && sign() != Sign::kNone &&
        radix() != 10) {
      return MaybeHandle<BigInt>();
    }
    if (state() == State::kEmpty) {
      if (behavior_ == Behavior::kStringToBigInt) {
        set_state(State::kZero);
      } else {
        UNREACHABLE();
      }
    }
    switch (this->state()) {
      case State::kJunk:
      case State::kError:
        return MaybeHandle<BigInt>();
      case State::kZero:
        return BigInt::Zero(isolate(), allocation_type());
      case State::kDone:
        return BigInt::Allocate(isolate(), &accumulator_, negative(),
                                allocation_type());
      case State::kEmpty:
      case State::kRunning:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::StringToBigIntHelper< IsolateT >::accumulator_, v8::internal::BigInt::Allocate(), v8::internal::StringToBigIntHelper< IsolateT >::allocation_type(), v8::internal::StringToBigIntHelper< IsolateT >::behavior_, v8::internal::StringToBigIntHelper< IsolateT >::isolate(), v8::internal::swiss_table::kEmpty, v8::internal::StringToBigIntHelper< IsolateT >::kStringToBigInt, v8::internal::kZero, v8::internal::StringToIntHelper::negative(), v8::internal::StringToIntHelper::ParseInt(), v8::internal::StringToIntHelper::radix(), v8::internal::StringToIntHelper::set_state(), v8::internal::StringToIntHelper::sign(), v8::internal::StringToIntHelper::state(), v8::internal::UNREACHABLE(), and v8::internal::BigInt::Zero().
Referenced by v8::internal::BigIntLiteral(), and v8::internal::StringToBigInt().
isolate()
template<typename IsolateT >
IsolateT* v8::internal::StringToBigIntHelper< IsolateT >::isolate () [inline]
Definition at line 1073 of file conversions.cc.
{ return isolate_; }
References v8::internal::StringToBigIntHelper< IsolateT >::isolate_.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::GetResult().
ParseInternal()
template<typename IsolateT >
template<class Char >
void v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal (const Char * start) [inline], [private]
Definition at line 1077 of file conversions.cc.
                                        {
    using Result = bigint::FromStringAccumulator::Result;
    const Char* current = start + cursor();
    const Char* end = start + length();
    current = accumulator_.Parse(current, end, radix());
    Result result = accumulator_.result();
    if (result == Result::kMaxSizeExceeded) {
      return set_state(State::kError);
    }
    if (!allow_trailing_junk() && AdvanceToNonspace(&current, end)) {
      return set_state(State::kJunk);
    }
    return set_state(State::kDone);
  }
References v8::internal::StringToBigIntHelper< IsolateT >::accumulator_, v8::internal::AdvanceToNonspace(), v8::internal::StringToIntHelper::allow_trailing_junk(), v8::internal::StringToIntHelper::cursor(), v8::internal::compiler::end(), v8::internal::StringToIntHelper::length(), v8::bigint::FromStringAccumulator::Parse(), v8::internal::StringToIntHelper::radix(), v8::base::internal::result, v8::bigint::FromStringAccumulator::result(), and v8::internal::StringToIntHelper::set_state().
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::ParseOneByte(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseTwoByte().
ParseOneByte()
template<typename IsolateT >
void v8::internal::StringToBigIntHelper< IsolateT >::ParseOneByte (const uint8_t * start) [inline], [final], [virtual]
Implements v8::internal::StringToIntHelper.
Definition at line 1019 of file conversions.cc.
{ return ParseInternal(start); }
References v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
ParseTwoByte()
template<typename IsolateT >
void v8::internal::StringToBigIntHelper< IsolateT >::ParseTwoByte (const base::uc16 * start) [inline], [final], [virtual]
Implements v8::internal::StringToIntHelper.
Definition at line 1020 of file conversions.cc.
                                                 {
    return ParseInternal(start);
  }
References v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
Member Data Documentation
accumulator_
template<typename IsolateT >
bigint::FromStringAccumulator v8::internal::StringToBigIntHelper< IsolateT >::accumulator_ {BigInt::kMaxLength} [private]
Definition at line 1101 of file conversions.cc.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), v8::internal::StringToBigIntHelper< IsolateT >::GetResult(), and v8::internal::StringToBigIntHelper< IsolateT >::ParseInternal().
behavior_
template<typename IsolateT >
Behavior v8::internal::StringToBigIntHelper< IsolateT >::behavior_ [private]
Definition at line 1102 of file conversions.cc.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::allocation_type(), v8::internal::StringToBigIntHelper< IsolateT >::DecimalString(), and v8::internal::StringToBigIntHelper< IsolateT >::GetResult().
isolate_
template<typename IsolateT >
IsolateT* v8::internal::StringToBigIntHelper< IsolateT >::isolate_ [private]
Definition at line 1100 of file conversions.cc.
Referenced by v8::internal::StringToBigIntHelper< IsolateT >::isolate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/numbers/conversions.cc