v8_inspector::V8DebuggerScript Class Reference
#include <v8-debugger-script.h>
Public Types
enum class Language { JavaScript
, WebAssembly
 }
Public Member Functions
V8DebuggerScript (v8::Isolate *isolate, v8::Local< v8::debug::Script > script, bool isLiveEdit, V8DebuggerAgentImpl *agent, V8InspectorClient *client)
~V8DebuggerScript ()=default
V8DebuggerScript (const V8DebuggerScript &)=delete
V8DebuggerScript & operator= (const V8DebuggerScript &)=delete
v8::Local< v8::debug::ScriptSource > scriptSource ()
const String16 & scriptId () const
bool hasSourceURLComment () const
const String16 & sourceURL () const
const String16 & embedderName () const
const String16 & sourceMappingURL () const
String16 source (size_t pos, size_t len=UINT_MAX) const
Language getLanguage () const
const String16 & hash () const
String16 buildId () const
int startLine () const
int startColumn () const
int endLine () const
int endColumn () const
int codeOffset () const
int executionContextId () const
bool isLiveEdit () const
bool isModule () const
int length () const
void setSourceURL (const String16 &)
void setSourceMappingURL (const String16 &)
void setBuildId (const String16 &)
void setSource (const String16 &source, bool preview, bool allowTopFrameLiveEditing, v8::debug::LiveEditResult *result)
bool getPossibleBreakpoints (const v8::debug::Location &start, const v8::debug::Location &end, bool ignoreNestedFunctions, std::vector< v8::debug::BreakLocation > *locations)
void resetBlackboxedStateCache ()
v8::Maybe< int > offset (int lineNumber, int columnNumber) const
v8::debug::Location location (int offset) const
bool setBreakpoint (const String16 &condition, v8::debug::Location *location, int *id) const
void MakeWeak ()
void WeakCallback ()
bool setInstrumentationBreakpoint (int *id) const
Private Member Functions
v8::Local< v8::debug::Script > script () const
void Initialize (v8::Local< v8::debug::Script > script)
Static Private Member Functions
static String16 GetScriptURL (v8::Isolate *isolate, v8::Local< v8::debug::Script > script, V8InspectorClient *client)
static String16 GetScriptName (v8::Isolate *isolate, v8::Local< v8::debug::Script > script, V8InspectorClient *client)
Private Attributes
String16 m_id
String16 m_url
bool m_hasSourceURLComment = false
int m_executionContextId = 0
v8::Isolate * m_isolate
String16 m_embedderName
V8DebuggerAgentImpl * m_agent
String16 m_sourceMappingURL
String16 m_buildId
Language m_language
bool m_isLiveEdit = false
bool m_isModule = false
String16 m_hash
int m_startLine = 0
int m_startColumn = 0
int m_endLine = 0
int m_endColumn = 0
v8::Global< v8::debug::Script > m_script
v8::Global< v8::debug::ScriptSource > m_scriptSource
Detailed Description
Definition at line 51 of file v8-debugger-script.h.
Member Enumeration Documentation
Language
enum v8_inspector::V8DebuggerScript::Language [strong]
Enumerator
JavaScript
WebAssembly
Definition at line 53 of file v8-debugger-script.h.
{ JavaScript, WebAssembly };
Constructor & Destructor Documentation
V8DebuggerScript() [1/2]
v8_inspector::V8DebuggerScript::V8DebuggerScript (v8::Isolate * isolate, v8::Local< v8::debug::Script > script, bool isLiveEdit, V8DebuggerAgentImpl * agent, V8InspectorClient * client)
Definition at line 43 of file v8-debugger-script.cc.
    : m_id(String16::fromInteger(script->Id())),
      m_url(GetScriptURL(isolate, script, client)),
      m_isolate(isolate),
      m_embedderName(GetScriptName(isolate, script, client)),
      m_agent(agent),
      m_isLiveEdit(isLiveEdit) {
  Initialize(script);
}
References Initialize(), and script().
 V8DebuggerScript()
v8_inspector::V8DebuggerScript::~V8DebuggerScript () [default]
V8DebuggerScript() [2/2]
v8_inspector::V8DebuggerScript::V8DebuggerScript (const V8DebuggerScript &) [delete]
Member Function Documentation
buildId()
String16 v8_inspector::V8DebuggerScript::buildId () const
Definition at line 214 of file v8-debugger-script.cc.
                                         {
  if (!m_buildId.isEmpty()) return m_buildId;
  v8::Local<v8::debug::Script> script = this->script();
#if V8_ENABLE_WEBASSEMBLY
    if (m_language == Language::WebAssembly) {
      auto maybe_build_id =
          v8::debug::WasmScript::Cast(*script)->GetModuleBuildId();
      if (maybe_build_id.IsJust()) {
        v8::MemorySpan<const uint8_t> buildId = maybe_build_id.FromJust();
        String16Builder buildIdFormatter;
        for (size_t i = 0; i < buildId.size(); i++) {
          buildIdFormatter.appendUnsignedAsHex(
              static_cast<uint8_t>(buildId[i]));
        }
        m_buildId = buildIdFormatter.toString();
      }
    }
#endif // V8_ENABLE_WEBASSEMBLY
    if (m_language == Language::JavaScript) {
      v8::Local<v8::String> debugId;
      if (script->DebugId().ToLocal(&debugId)) {
        m_buildId = toProtocolString(m_isolate, debugId);
      }
    }
    return m_buildId;
}
References v8_inspector::String16Builder::appendUnsignedAsHex(), v8::internal::Cast(), v8::debug::Script::DebugId(), v8_inspector::String16::isEmpty(), JavaScript, m_buildId, m_isolate, m_language, script(), v8_inspector::toProtocolString(), v8_inspector::String16Builder::toString(), and WebAssembly.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), and setBuildId().
codeOffset()
int v8_inspector::V8DebuggerScript::codeOffset () const
Definition at line 102 of file v8-debugger-script.cc.
                                       {
#if V8_ENABLE_WEBASSEMBLY
    if (script()->IsWasm()) {
      return v8::debug::WasmScript::Cast(*script())->CodeOffset();
    }
#endif // V8_ENABLE_WEBASSEMBLY
    return 0;
}
References v8::internal::Cast(), and script().
embedderName()
const String16& v8_inspector::V8DebuggerScript::embedderName () const [inline]
Definition at line 66 of file v8-debugger-script.h.
{ return m_embedderName; }
References m_embedderName.
endColumn()
int v8_inspector::V8DebuggerScript::endColumn () const [inline]
Definition at line 76 of file v8-debugger-script.h.
{ return m_endColumn; }
References m_endColumn.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), and v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded().
endLine()
int v8_inspector::V8DebuggerScript::endLine () const [inline]
Definition at line 75 of file v8-debugger-script.h.
{ return m_endLine; }
References m_endLine.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), and v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded().
executionContextId()
int v8_inspector::V8DebuggerScript::executionContextId () const [inline]
Definition at line 78 of file v8-debugger-script.h.
{ return m_executionContextId; }
References m_executionContextId.
getLanguage()
Language v8_inspector::V8DebuggerScript::getLanguage () const [inline]
Definition at line 70 of file v8-debugger-script.h.
{ return m_language; }
References m_language.
getPossibleBreakpoints()
bool v8_inspector::V8DebuggerScript::getPossibleBreakpoints (const v8::debug::Location & start, const v8::debug::Location & end, bool ignoreNestedFunctions, std::vector< v8::debug::BreakLocation > * locations)
Definition at line 135 of file v8-debugger-script.cc.
                                                                         {
  v8::HandleScope scope(m_isolate);
  v8::Local<v8::debug::Script> script = m_script.Get(m_isolate);
  std::vector<v8::debug::BreakLocation> allLocations;
  if (!script->GetPossibleBreakpoints(start, end, restrictToFunction,
                                      &allLocations)) {
    return false;
  }
  if (allLocations.empty()) return true;
  v8::debug::BreakLocation current = allLocations[0];
  for (size_t i = 1; i < allLocations.size(); ++i) {
    if (allLocations[i].GetLineNumber() == current.GetLineNumber() &&
        allLocations[i].GetColumnNumber() == current.GetColumnNumber()) {
      if (allLocations[i].type() != v8::debug::kCommonBreakLocation) {
        DCHECK(allLocations[i].type() == v8::debug::kCallBreakLocation ||
               allLocations[i].type() == v8::debug::kReturnBreakLocation);
        // debugger can returns more then one break location at the same
        // source location, e.g. foo() - in this case there are two break
        // locations before foo: for statement and for function call, we can
        // merge them for inspector and report only one with call type.
        current = allLocations[i];
      }
    } else {
      // we assume that returned break locations are sorted.
      DCHECK(allLocations[i].GetLineNumber() > current.GetLineNumber() ||
             (allLocations[i].GetColumnNumber() >= current.GetColumnNumber() &&
              allLocations[i].GetLineNumber() == current.GetLineNumber()));
      locations->push_back(current);
      current = allLocations[i];
    }
  }
  locations->push_back(current);
  return true;
}
References DCHECK, v8::internal::compiler::end(), v8::PersistentBase< T >::Get(), v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::debug::Script::GetPossibleBreakpoints(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::debug::kCallBreakLocation, v8::debug::kCommonBreakLocation, v8::debug::kReturnBreakLocation, m_isolate, m_script, script(), and v8::internal::tracing::type.
GetScriptName()
String16 v8_inspector::V8DebuggerScript::GetScriptName (v8::Isolate * isolate, v8::Local< v8::debug::Script > script, V8InspectorClient * client) [static], [private]
Definition at line 256 of file v8-debugger-script.cc.
                                                                    {
  v8::Local<v8::String> v8Name;
  if (script->Name().ToLocal(&v8Name) && v8Name->Length() > 0) {
    String16 name = toProtocolString(isolate, v8Name);
    std::unique_ptr<StringBuffer> url =
        client->resourceNameToUrl(toStringView(name));
    return url ? toString16(url->string()) : name;
  }
  return String16();
}
References v8::String::Length(), v8::debug::Script::Name(), name, v8_inspector::V8InspectorClient::resourceNameToUrl(), script(), v8_inspector::toProtocolString(), v8_inspector::toString16(), and v8_inspector::toStringView().
Referenced by GetScriptURL().
GetScriptURL()
String16 v8_inspector::V8DebuggerScript::GetScriptURL (v8::Isolate * isolate, v8::Local< v8::debug::Script > script, V8InspectorClient * client) [static], [private]
Definition at line 246 of file v8-debugger-script.cc.
                                                                   {
  v8::Local<v8::String> sourceURL;
  if (script->SourceURL().ToLocal(&sourceURL) && sourceURL->Length() > 0)
    return toProtocolString(isolate, sourceURL);
  return GetScriptName(isolate, script, client);
}
References GetScriptName(), script(), v8::debug::Script::SourceURL(), sourceURL(), and v8_inspector::toProtocolString().
hash()
const String16 & v8_inspector::V8DebuggerScript::hash () const
Definition at line 202 of file v8-debugger-script.cc.
                                             {
  if (!m_hash.isEmpty()) return m_hash;
  v8::HandleScope scope(m_isolate);
  v8::Local<v8::String> v8Source;
  if (!m_scriptSource.Get(m_isolate)->JavaScriptCode().ToLocal(&v8Source)) {
    v8Source = v8::String::Empty(m_isolate);
  }
  m_hash = calculateHash(m_isolate, v8Source);
  DCHECK(!m_hash.isEmpty());
  return m_hash;
}
References v8_inspector::anonymous_namespace{v8-debugger-script.cc}::calculateHash(), DCHECK, v8::String::Empty(), v8::PersistentBase< T >::Get(), v8_inspector::String16::isEmpty(), m_hash, m_isolate, and m_scriptSource.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
hasSourceURLComment()
bool v8_inspector::V8DebuggerScript::hasSourceURLComment () const [inline]
Definition at line 64 of file v8-debugger-script.h.
{ return m_hasSourceURLComment; }
References m_hasSourceURLComment.
Initialize()
void v8_inspector::V8DebuggerScript::Initialize (v8::Local< v8::debug::Script > script) [private]
Definition at line 273 of file v8-debugger-script.cc.
                                                               {
  v8::Local<v8::String> tmp;
  m_hasSourceURLComment =
      script->SourceURL().ToLocal(&tmp) && tmp->Length() > 0;
  if (script->SourceMappingURL().ToLocal(&tmp))
    m_sourceMappingURL = toProtocolString(m_isolate, tmp);
  m_startLine = script->StartLine();
  m_startColumn = script->StartColumn();
  m_endLine = script->EndLine();
  m_endColumn = script->EndColumn();
  USE(script->ContextId().To(&m_executionContextId));
  m_language = V8DebuggerScript::Language::JavaScript;
#if V8_ENABLE_WEBASSEMBLY
    if (script->IsWasm()) {
      m_language = V8DebuggerScript::Language::WebAssembly;
    }
#endif // V8_ENABLE_WEBASSEMBLY
    m_isModule = script->IsModule();
    bool hasHash = script->GetSha256Hash().ToLocal(&tmp) && tmp->Length() > 0;
    if (hasHash) {
      m_hash = toProtocolString(m_isolate, tmp);
    }
    m_script.Reset(m_isolate, script);
    m_script.AnnotateStrongRetainer(kGlobalDebuggerScriptHandleLabel);
    m_scriptSource.Reset(m_isolate, script->Source());
    m_scriptSource.AnnotateStrongRetainer(kGlobalDebuggerScriptHandleLabel);
}
References v8::PersistentBase< T >::AnnotateStrongRetainer(), v8::debug::Script::ContextId(), v8::debug::Script::EndColumn(), v8::debug::Script::EndLine(), v8::debug::Script::GetSha256Hash(), v8::debug::Script::IsModule(), JavaScript, v8_inspector::anonymous_namespace{v8-debugger-script.cc}::kGlobalDebuggerScriptHandleLabel, v8::String::Length(), m_endColumn, m_endLine, m_executionContextId, m_hash, m_hasSourceURLComment, m_isModule, m_isolate, m_language, m_script, m_scriptSource, m_sourceMappingURL, m_startColumn, m_startLine, v8::PersistentBase< T >::Reset(), script(), v8::debug::Script::Source(), v8::debug::Script::SourceMappingURL(), v8::debug::Script::SourceURL(), v8::debug::Script::StartColumn(), v8::debug::Script::StartLine(), v8_inspector::toProtocolString(), USE, and WebAssembly.
Referenced by setSource(), and V8DebuggerScript().
isLiveEdit()
bool v8_inspector::V8DebuggerScript::isLiveEdit () const [inline]
Definition at line 79 of file v8-debugger-script.h.
{ return m_isLiveEdit; }
References m_isLiveEdit.
isModule()
bool v8_inspector::V8DebuggerScript::isModule () const [inline]
Definition at line 80 of file v8-debugger-script.h.
{ return m_isModule; }
References m_isModule.
length()
int v8_inspector::V8DebuggerScript::length () const
Definition at line 110 of file v8-debugger-script.cc.
                                   {
  return static_cast<int>(m_scriptSource.Get(m_isolate)->Length());
}
References v8::PersistentBase< T >::Get(), m_isolate, and m_scriptSource.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
location()
v8::debug::Location v8_inspector::V8DebuggerScript::location (int offset) const
Definition at line 184 of file v8-debugger-script.cc.
                                                           {
  v8::HandleScope scope(m_isolate);
  return m_script.Get(m_isolate)->GetSourceLocation(offset);
}
References v8::PersistentBase< T >::Get(), m_isolate, m_script, and offset().
Referenced by setBreakpoint().
MakeWeak()
void v8_inspector::V8DebuggerScript::MakeWeak ()
Definition at line 305 of file v8-debugger-script.cc.
                                {
  m_script.SetWeak(
      this,
      [](const v8::WeakCallbackInfo<V8DebuggerScript>& data) {
        data.GetParameter()->WeakCallback();
      },
      v8::WeakCallbackType::kParameter);
}
References v8::WeakCallbackInfo< T >::GetParameter(), v8::kParameter, m_script, v8::PersistentBase< T >::SetWeak(), and WeakCallback().
offset()
v8::Maybe< int > v8_inspector::V8DebuggerScript::offset (int lineNumber, int columnNumber) const
Definition at line 177 of file v8-debugger-script.cc.
                                                                {
  v8::HandleScope scope(m_isolate);
  return m_script.Get(m_isolate)->GetSourceOffset(
      v8::debug::Location(lineNumber, columnNumber));
}
References v8::PersistentBase< T >::Get(), m_isolate, and m_script.
Referenced by location().
operator=()
V8DebuggerScript& v8_inspector::V8DebuggerScript::operator= (const V8DebuggerScript &) [delete]
resetBlackboxedStateCache()
void v8_inspector::V8DebuggerScript::resetBlackboxedStateCache ()
Definition at line 172 of file v8-debugger-script.cc.
                                                 {
  v8::HandleScope scope(m_isolate);
  v8::debug::ResetBlackboxedStateCache(m_isolate, m_script.Get(m_isolate));
}
References v8::PersistentBase< T >::Get(), m_isolate, m_script, and v8::debug::ResetBlackboxedStateCache().
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
script()
v8::Local< v8::debug::Script > v8_inspector::V8DebuggerScript::script () const [private]
Definition at line 269 of file v8-debugger-script.cc.
                                                      {
  return m_script.Get(m_isolate);
}
References v8::PersistentBase< T >::Get(), m_isolate, and m_script.
Referenced by buildId(), codeOffset(), getPossibleBreakpoints(), GetScriptName(), GetScriptURL(), Initialize(), setBreakpoint(), setInstrumentationBreakpoint(), and V8DebuggerScript().
scriptId()
const String16& v8_inspector::V8DebuggerScript::scriptId () const [inline]
Definition at line 63 of file v8-debugger-script.h.
{ return m_id; }
References m_id.
Referenced by v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded().
scriptSource()
v8::Local<v8::debug::ScriptSource> v8_inspector::V8DebuggerScript::scriptSource ()
setBreakpoint()
bool v8_inspector::V8DebuggerScript::setBreakpoint (const String16 & condition, v8::debug::Location * location, int * id) const
Definition at line 189 of file v8-debugger-script.cc.
                                                    {
  v8::HandleScope scope(m_isolate);
  return script()->SetBreakpoint(toV8String(m_isolate, condition), location,
                                 id);
}
References location(), m_isolate, script(), v8::debug::Script::SetBreakpoint(), and v8_inspector::toV8String().
setBuildId()
void v8_inspector::V8DebuggerScript::setBuildId (const String16 & buildId)
Definition at line 241 of file v8-debugger-script.cc.
                                                         {
  m_buildId = buildId;
}
References buildId(), and m_buildId.
setInstrumentationBreakpoint()
bool v8_inspector::V8DebuggerScript::setInstrumentationBreakpoint (int * id) const
Definition at line 197 of file v8-debugger-script.cc.
                                                                 {
  v8::HandleScope scope(m_isolate);
  return script()->SetInstrumentationBreakpoint(id);
}
References m_isolate, script(), and v8::debug::Script::SetInstrumentationBreakpoint().
Referenced by v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded().
setSource()
void v8_inspector::V8DebuggerScript::setSource (const String16 & source, bool preview, bool allowTopFrameLiveEditing, v8::debug::LiveEditResult * result)
Definition at line 118 of file v8-debugger-script.cc.
                                                                {
  v8::EscapableHandleScope scope(m_isolate);
  v8::Local<v8::String> v8Source = toV8String(m_isolate, newSource);
  if (!m_script.Get(m_isolate)->SetScriptSource(
          v8Source, preview, allowTopFrameLiveEditing, result)) {
    result->message = scope.Escape(result->message);
    return;
  }
  // NOP if preview or unchanged source (diffs.empty() in PatchScript)
  if (preview || result->script.IsEmpty()) return;
  m_hash = String16();
  Initialize(scope.Escape(result->script));
}
References v8::EscapableHandleScope::Escape(), v8::PersistentBase< T >::Get(), Initialize(), m_hash, m_isolate, m_script, v8::base::internal::result, and v8_inspector::toV8String().
setSourceMappingURL()
void v8_inspector::V8DebuggerScript::setSourceMappingURL (const String16 & sourceMappingURL)
Definition at line 114 of file v8-debugger-script.cc.
                                                                           {
  m_sourceMappingURL = sourceMappingURL;
}
References m_sourceMappingURL, and sourceMappingURL().
setSourceURL()
void v8_inspector::V8DebuggerScript::setSourceURL (const String16 & sourceURL)
Definition at line 319 of file v8-debugger-script.cc.
                                                             {
  if (sourceURL.length() > 0) {
    m_hasSourceURLComment = true;
    m_url = sourceURL;
  }
}
References v8_inspector::String16::length(), m_hasSourceURLComment, m_url, and sourceURL().
source()
String16 v8_inspector::V8DebuggerScript::source (size_t pos, size_t len = UINT_MAX) const
Definition at line 56 of file v8-debugger-script.cc.
                                                              {
  v8::HandleScope scope(m_isolate);
  v8::Local<v8::String> v8Source;
  if (!m_scriptSource.Get(m_isolate)->JavaScriptCode().ToLocal(&v8Source)) {
    return String16();
  }
  if (pos >= static_cast<size_t>(v8Source->Length())) return String16();
  size_t substringLength =
      std::min(len, static_cast<size_t>(v8Source->Length()) - pos);
  std::unique_ptr<UChar[]> buffer(new UChar[substringLength]);
  v8Source->WriteV2(m_isolate, static_cast<uint32_t>(pos),
                    static_cast<uint32_t>(substringLength),
                    reinterpret_cast<uint16_t*>(buffer.get()));
  return String16(buffer.get(), substringLength);
}
References v8::PersistentBase< T >::Get(), v8::String::Length(), m_isolate, m_scriptSource, and v8::String::WriteV2().
sourceMappingURL()
const String16& v8_inspector::V8DebuggerScript::sourceMappingURL () const [inline]
Definition at line 68 of file v8-debugger-script.h.
{ return m_sourceMappingURL; }
References m_sourceMappingURL.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource(), v8_inspector::V8DebuggerAgentImpl::setScriptInstrumentationBreakpointIfNeeded(), and setSourceMappingURL().
sourceURL()
const String16& v8_inspector::V8DebuggerScript::sourceURL () const [inline]
Definition at line 65 of file v8-debugger-script.h.
{ return m_url; }
References m_url.
Referenced by GetScriptURL(), and setSourceURL().
startColumn()
int v8_inspector::V8DebuggerScript::startColumn () const [inline]
Definition at line 74 of file v8-debugger-script.h.
{ return m_startColumn; }
References m_startColumn.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
startLine()
int v8_inspector::V8DebuggerScript::startLine () const [inline]
Definition at line 73 of file v8-debugger-script.h.
{ return m_startLine; }
References m_startLine.
Referenced by v8_inspector::V8DebuggerAgentImpl::didParseSource().
WeakCallback()
void v8_inspector::V8DebuggerScript::WeakCallback ()
Definition at line 314 of file v8-debugger-script.cc.
                                    {
  m_script.Reset();
  m_agent->ScriptCollected(this);
}
References m_agent, m_script, v8::PersistentBase< T >::Reset(), and v8_inspector::V8DebuggerAgentImpl::ScriptCollected().
Referenced by MakeWeak().
Member Data Documentation
m_agent
V8DebuggerAgentImpl* v8_inspector::V8DebuggerScript::m_agent [private]
Definition at line 131 of file v8-debugger-script.h.
Referenced by WeakCallback().
m_buildId
String16 v8_inspector::V8DebuggerScript::m_buildId [mutable], [private]
Definition at line 133 of file v8-debugger-script.h.
Referenced by buildId(), and setBuildId().
m_embedderName
String16 v8_inspector::V8DebuggerScript::m_embedderName [private]
Definition at line 130 of file v8-debugger-script.h.
Referenced by embedderName().
m_endColumn
int v8_inspector::V8DebuggerScript::m_endColumn = 0 [private]
Definition at line 141 of file v8-debugger-script.h.
Referenced by endColumn(), and Initialize().
m_endLine
int v8_inspector::V8DebuggerScript::m_endLine = 0 [private]
Definition at line 140 of file v8-debugger-script.h.
Referenced by endLine(), and Initialize().
m_executionContextId
int v8_inspector::V8DebuggerScript::m_executionContextId = 0 [private]
Definition at line 127 of file v8-debugger-script.h.
Referenced by executionContextId(), and Initialize().
m_hash
String16 v8_inspector::V8DebuggerScript::m_hash [mutable], [private]
Definition at line 137 of file v8-debugger-script.h.
Referenced by hash(), Initialize(), and setSource().
m_hasSourceURLComment
bool v8_inspector::V8DebuggerScript::m_hasSourceURLComment = false [private]
Definition at line 126 of file v8-debugger-script.h.
Referenced by hasSourceURLComment(), Initialize(), and setSourceURL().
m_id
String16 v8_inspector::V8DebuggerScript::m_id [private]
Definition at line 124 of file v8-debugger-script.h.
Referenced by scriptId().
m_isLiveEdit
bool v8_inspector::V8DebuggerScript::m_isLiveEdit = false [private]
Definition at line 135 of file v8-debugger-script.h.
Referenced by isLiveEdit().
m_isModule
bool v8_inspector::V8DebuggerScript::m_isModule = false [private]
Definition at line 136 of file v8-debugger-script.h.
Referenced by Initialize(), and isModule().
m_isolate
v8::Isolate* v8_inspector::V8DebuggerScript::m_isolate [private]
Definition at line 129 of file v8-debugger-script.h.
Referenced by buildId(), getPossibleBreakpoints(), hash(), Initialize(), length(), location(), offset(), resetBlackboxedStateCache(), script(), setBreakpoint(), setInstrumentationBreakpoint(), setSource(), and source().
m_language
Language v8_inspector::V8DebuggerScript::m_language [private]
Definition at line 134 of file v8-debugger-script.h.
Referenced by buildId(), getLanguage(), and Initialize().
m_script
v8::Global<v8::debug::Script> v8_inspector::V8DebuggerScript::m_script [private]
Definition at line 142 of file v8-debugger-script.h.
Referenced by getPossibleBreakpoints(), Initialize(), location(), MakeWeak(), offset(), resetBlackboxedStateCache(), script(), setSource(), and WeakCallback().
m_scriptSource
v8::Global<v8::debug::ScriptSource> v8_inspector::V8DebuggerScript::m_scriptSource [private]
Definition at line 143 of file v8-debugger-script.h.
Referenced by hash(), Initialize(), length(), and source().
m_sourceMappingURL
String16 v8_inspector::V8DebuggerScript::m_sourceMappingURL [private]
Definition at line 132 of file v8-debugger-script.h.
Referenced by Initialize(), setSourceMappingURL(), and sourceMappingURL().
m_startColumn
int v8_inspector::V8DebuggerScript::m_startColumn = 0 [private]
Definition at line 139 of file v8-debugger-script.h.
Referenced by Initialize(), and startColumn().
m_startLine
int v8_inspector::V8DebuggerScript::m_startLine = 0 [private]
Definition at line 138 of file v8-debugger-script.h.
Referenced by Initialize(), and startLine().
m_url
String16 v8_inspector::V8DebuggerScript::m_url [private]
Definition at line 125 of file v8-debugger-script.h.
Referenced by setSourceURL(), and sourceURL().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-debugger-script.h
/mnt/V8SourceCode/src/inspector/v8-debugger-script.cc