v8::internal::compiler::SelectLowering Class Reference
#include <select-lowering.h>
Public Member Functions
SelectLowering (JSGraphAssembler *graph_assembler, TFGraph *graph)
~SelectLowering () override
const char * reducer_name () const override
Reduction Reduce (Node *node) override
Private Member Functions
Reduction LowerSelect (Node *node)
JSGraphAssembler * gasm () const
Node * start () const
Private Attributes
JSGraphAssembler * graph_assembler_
Node * start_
Additional Inherited Members
Detailed Description
Definition at line 18 of file select-lowering.h.
Constructor & Destructor Documentation
SelectLowering()
v8::internal::compiler::SelectLowering::SelectLowering (JSGraphAssembler * graph_assembler, TFGraph * graph)
Definition at line 16 of file select-lowering.cc.
    : graph_assembler_(graph_assembler), start_(graph->start()) {}
 SelectLowering()
v8::internal::compiler::SelectLowering::~SelectLowering () [override], [default]
Member Function Documentation
gasm()
JSGraphAssembler* v8::internal::compiler::SelectLowering::gasm () const [inline], [private]
Definition at line 30 of file select-lowering.h.
{ return graph_assembler_; }
References graph_assembler_.
Referenced by LowerSelect().
LowerSelect()
Reduction v8::internal::compiler::SelectLowering::LowerSelect (Node * node) [private]
Definition at line 29 of file select-lowering.cc.
                                                {
  SelectParameters const p = SelectParametersOf(node->op());
  Node* condition = node->InputAt(0);
  Node* vtrue = node->InputAt(1);
  Node* vfalse = node->InputAt(2);
  bool reset_gasm = false;
  if (gasm()->control() == nullptr) {
    gasm()->InitializeEffectControl(start(), start());
    reset_gasm = true;
  }
  auto done = __ MakeLabel(p.representation());
  __ GotoIf(condition, &done, vtrue);
  __ Goto(&done, vfalse);
  __ Bind(&done);
  if (reset_gasm) {
    gasm()->Reset();
  }
  return Changed(done.PhiAt(0));
}
References __, v8::internal::compiler::Reducer::Changed(), gasm(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::op(), v8::internal::compiler::SelectParameters::representation(), v8::internal::compiler::GraphAssembler::Reset(), v8::internal::compiler::SelectParametersOf(), and start().
Referenced by Reduce().
Reduce()
Reduction v8::internal::compiler::SelectLowering::Reduce (Node * node) [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 22 of file select-lowering.cc.
                                           {
  if (node->opcode() != IrOpcode::kSelect) return NoChange();
  return LowerSelect(node);
}
References LowerSelect(), v8::internal::compiler::Reducer::NoChange(), and v8::internal::compiler::Node::opcode().
reducer_name()
const char* v8::internal::compiler::SelectLowering::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 23 of file select-lowering.h.
{ return "SelectLowering"; }
start()
Node* v8::internal::compiler::SelectLowering::start () const [inline], [private]
Definition at line 31 of file select-lowering.h.
{ return start_; }
References start_.
Referenced by LowerSelect().
Member Data Documentation
graph_assembler_
JSGraphAssembler* v8::internal::compiler::SelectLowering::graph_assembler_ [private]
Definition at line 33 of file select-lowering.h.
Referenced by gasm().
start_
Node* v8::internal::compiler::SelectLowering::start_ [private]
Definition at line 34 of file select-lowering.h.
Referenced by start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/select-lowering.h
/mnt/V8SourceCode/src/compiler/select-lowering.cc