v8::internal::torque::ResidueClass Class Reference
#include <utils.h>
Public Member Functions
ResidueClass (size_t value, size_t modulus_log_2=kMaxModulusLog2)
std::optional< size_t > SingleValue () const
ResidueClass & operator+= (const ResidueClass &other)
ResidueClass & operator*= (const ResidueClass &other)
size_t AlignmentLog2 () const
size_t Alignment () const
Static Public Member Functions
static ResidueClass Unknown ()
Private Attributes
size_t value_
size_t modulus_log_2_
Static Private Attributes
static const size_t kMaxModulusLog2 = 8 * sizeof(size_t)
Friends
ResidueClass operator+ (const ResidueClass &a, const ResidueClass &b)
ResidueClass operator* (const ResidueClass &a, const ResidueClass &b)
std::ostream & operator<< (std::ostream &os, const ResidueClass &a)
Detailed Description
Definition at line 424 of file utils.h.
Constructor & Destructor Documentation
ResidueClass()
v8::internal::torque::ResidueClass::ResidueClass (size_t value, size_t modulus_log_2 = kMaxModulusLog2) [inline]
Definition at line 426 of file utils.h.
      : value_(value),
        modulus_log_2_(std::min(modulus_log_2, kMaxModulusLog2)) {
    if (modulus_log_2_ < kMaxModulusLog2) {
      value_ %= size_t{1} << modulus_log_2_;
    }
  }
References kMaxModulusLog2, modulus_log_2_, and value_.
Member Function Documentation
Alignment()
size_t v8::internal::torque::ResidueClass::Alignment () const [inline]
Definition at line 478 of file utils.h.
                           {
    DCHECK_LT(AlignmentLog2(), kMaxModulusLog2);
    return size_t{1} << AlignmentLog2();
  }
References AlignmentLog2(), DCHECK_LT, and kMaxModulusLog2.
AlignmentLog2()
size_t v8::internal::torque::ResidueClass::AlignmentLog2 () const
Definition at line 383 of file utils.cc.
                                         {
  if (value_ == 0) return modulus_log_2_;
  return base::bits::CountTrailingZeros(value_);
}
References v8::base::bits::CountTrailingZeros(), modulus_log_2_, and value_.
Referenced by Alignment(), and v8::internal::torque::Field::ValidateAlignment().
operator*=()
ResidueClass& v8::internal::torque::ResidueClass::operator*= (const ResidueClass & other) [inline]
Definition at line 470 of file utils.h.
                                                      {
    *this = *this * other;
    return *this;
  }
operator+=()
ResidueClass& v8::internal::torque::ResidueClass::operator+= (const ResidueClass & other) [inline]
Definition at line 465 of file utils.h.
                                                      {
    *this = *this + other;
    return *this;
  }
SingleValue()
std::optional<size_t> v8::internal::torque::ResidueClass::SingleValue () const [inline]
Definition at line 440 of file utils.h.
                                          {
    if (modulus_log_2_ == kMaxModulusLog2) return value_;
    return std::nullopt;
  }
References kMaxModulusLog2, modulus_log_2_, and value_.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), v8::internal::torque::ClassType::HasStaticSize(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
Unknown()
static ResidueClass v8::internal::torque::ResidueClass::Unknown () [inline], [static]
Definition at line 436 of file utils.h.
{ return ResidueClass{0, 0}; }
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
Friends And Related Function Documentation
operator*
ResidueClass operator* (const ResidueClass & a, const ResidueClass & b) [friend]
Definition at line 457 of file utils.h.
                                                                              {
    return ResidueClass{a.value_ * b.value_,
                        std::min(a.modulus_log_2_ + b.AlignmentLog2(),
                                 b.modulus_log_2_ + a.AlignmentLog2())};
  }
operator+
ResidueClass operator+ (const ResidueClass & a, const ResidueClass & b) [friend]
Definition at line 445 of file utils.h.
                                                                              {
    return ResidueClass{a.value_ + b.value_,
                        std::min(a.modulus_log_2_, b.modulus_log_2_)};
  }
operator<<
std::ostream& operator<< (std::ostream & os, const ResidueClass & a) [friend]
Definition at line 390 of file utils.cc.
                                                              {
  if (a.SingleValue().has_value()) return os << *a.SingleValue();
  return os << "[" << a.value_ << " mod 2^" << a.modulus_log_2_ << "]";
}
Member Data Documentation
kMaxModulusLog2
const size_t v8::internal::torque::ResidueClass::kMaxModulusLog2 = 8 * sizeof(size_t) [static], [private]
Definition at line 492 of file utils.h.
Referenced by Alignment(), ResidueClass(), and SingleValue().
modulus_log_2_
size_t v8::internal::torque::ResidueClass::modulus_log_2_ [private]
Definition at line 488 of file utils.h.
Referenced by AlignmentLog2(), ResidueClass(), and SingleValue().
value_
size_t v8::internal::torque::ResidueClass::value_ [private]
Definition at line 486 of file utils.h.
Referenced by AlignmentLog2(), ResidueClass(), and SingleValue().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/utils.h
/mnt/V8SourceCode/src/torque/utils.cc