v8::internal::TrustedWeakFixedArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Static Public Member Functions
template<class IsolateT >
static Handle< TrustedWeakFixedArray > New (IsolateT *isolate, int capacity)
Private Types
using Super = TaggedArrayBase< TrustedWeakFixedArray, TrustedWeakFixedArrayShape >
Additional Inherited Members
Detailed Description
Definition at line 533 of file fixed-array.h.
Member Typedef Documentation
Super
using v8::internal::TrustedWeakFixedArray::Super = TaggedArrayBase<TrustedWeakFixedArray, TrustedWeakFixedArrayShape> [private]
Definition at line 536 of file fixed-array.h.
Member Function Documentation
New()
template<class IsolateT >
Handle< TrustedWeakFixedArray > v8::internal::TrustedWeakFixedArray::New (IsolateT * isolate, int capacity) [inline], [static]
Definition at line 645 of file fixed-array-inl.h.
                                                                       {
  if (V8_UNLIKELY(static_cast<unsigned>(capacity) >
                  TrustedFixedArray::kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d (see crbug.com/1201626)",
          capacity);
  }
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<TrustedWeakFixedArray> result = Cast<TrustedWeakFixedArray>(
      Allocate(isolate, capacity, &no_gc, AllocationType::kTrusted));
  MemsetTagged((*result)->RawFieldOfFirstElement(), Smi::zero(), capacity);
  return result;
}
References v8::internal::TaggedArrayBase< TrustedWeakFixedArray, TrustedWeakFixedArrayShape, TrustedObjectLayout >::Allocate(), FATAL, v8::internal::TrustedFixedArray::kMaxLength, v8::internal::kTrusted, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h