v8::internal::compiler::InstructionOperandConverter Class Reference
#include <code-generator-impl.h>
Public Member Functions
InstructionOperandConverter (CodeGenerator *gen, Instruction *instr)
Register InputRegister (size_t index) const
FloatRegister InputFloatRegister (size_t index)
DoubleRegister InputDoubleRegister (size_t index)
Simd128Register InputSimd128Register (size_t index)
double InputDouble (size_t index)
float InputFloat32 (size_t index)
int32_t InputInt32 (size_t index)
uint32_t InputUint32 (size_t index)
int64_t InputInt64 (size_t index)
int8_t InputInt8 (size_t index)
uint8_t InputUint8 (size_t index)
int16_t InputInt16 (size_t index)
uint8_t InputInt3 (size_t index)
uint8_t InputInt4 (size_t index)
uint8_t InputInt5 (size_t index)
uint8_t InputInt6 (size_t index)
CodeEntrypointTag InputCodeEntrypointTag (size_t index)
ExternalReference InputExternalReference (size_t index)
Handle< Code > InputCode (size_t index)
Label * InputLabel (size_t index)
RpoNumber InputRpo (size_t index)
Register OutputRegister (size_t index=0) const
Register TempRegister (size_t index)
FloatRegister OutputFloatRegister (size_t index=0)
DoubleRegister OutputDoubleRegister (size_t index=0)
DoubleRegister TempDoubleRegister (size_t index)
Simd128Register OutputSimd128Register ()
Simd128Register TempSimd128Register (size_t index)
Label * ToLabel (InstructionOperand *op)
RpoNumber ToRpoNumber (InstructionOperand *op)
Register ToRegister (InstructionOperand *op) const
FloatRegister ToFloatRegister (InstructionOperand *op)
DoubleRegister ToDoubleRegister (InstructionOperand *op)
Simd128Register ToSimd128Register (InstructionOperand *op)
Constant ToConstant (InstructionOperand *op) const
double ToDouble (InstructionOperand *op)
float ToFloat32 (InstructionOperand *op)
ExternalReference ToExternalReference (InstructionOperand *op)
Handle< Code > ToCode (InstructionOperand *op)
const Frame * frame () const
FrameAccessState * frame_access_state () const
Isolate * isolate () const
Linkage * linkage () const
Protected Attributes
CodeGenerator * gen_
Instruction * instr_
Detailed Description
Definition at line 22 of file code-generator-impl.h.
Constructor & Destructor Documentation
InstructionOperandConverter()
v8::internal::compiler::InstructionOperandConverter::InstructionOperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 24 of file code-generator-impl.h.
      : gen_(gen), instr_(instr) {}
Member Function Documentation
frame()
const Frame* v8::internal::compiler::InstructionOperandConverter::frame () const [inline]
Definition at line 212 of file code-generator-impl.h.
{ return gen_->frame(); }
References v8::internal::compiler::CodeGenerator::frame(), and gen_.
Referenced by v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand().
frame_access_state()
FrameAccessState* v8::internal::compiler::InstructionOperandConverter::frame_access_state () const [inline]
Definition at line 213 of file code-generator-impl.h.
                                               {
    return gen_->frame_access_state();
  }
References v8::internal::compiler::CodeGenerator::frame_access_state(), and gen_.
Referenced by v8::internal::compiler::ArmOperandConverter::SlotToMemOperand(), v8::internal::compiler::Loong64OperandConverter::SlotToMemOperand(), v8::internal::compiler::MipsOperandConverter::SlotToMemOperand(), v8::internal::compiler::PPCOperandConverter::SlotToMemOperand(), v8::internal::compiler::RiscvOperandConverter::SlotToMemOperand(), v8::internal::compiler::S390OperandConverter::SlotToMemOperand(), v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand(), v8::internal::compiler::IA32OperandConverter::SlotToOperand(), and v8::internal::compiler::X64OperandConverter::SlotToOperand().
InputCode()
Handle<Code> v8::internal::compiler::InstructionOperandConverter::InputCode (size_t index) [inline]
Definition at line 100 of file code-generator-impl.h.
                                       {
    return ToCode(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToCode().
InputCodeEntrypointTag()
CodeEntrypointTag v8::internal::compiler::InstructionOperandConverter::InputCodeEntrypointTag (size_t index) [inline]
Definition at line 89 of file code-generator-impl.h.
                                                         {
    // Tags are stored shifted to the right so they fit into 32-bits.
    uint64_t shifted_tag = InputUint32(index);
    return static_cast<CodeEntrypointTag>(shifted_tag
                                          << kCodeEntrypointTagShift);
  }
References v8::internal::index, InputUint32(), and v8::internal::kCodeEntrypointTagShift.
InputDouble()
double v8::internal::compiler::InstructionOperandConverter::InputDouble (size_t index) [inline]
Definition at line 45 of file code-generator-impl.h.
{ return ToDouble(instr_->InputAt(index)); }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToDouble().
Referenced by v8::internal::compiler::Arm64OperandConverter::InputFloat64OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrZeroRegister(), and v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister().
InputDoubleRegister()
DoubleRegister v8::internal::compiler::InstructionOperandConverter::InputDoubleRegister (size_t index) [inline]
Definition at line 37 of file code-generator-impl.h.
                                                   {
    return ToDoubleRegister(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToDoubleRegister().
Referenced by v8::internal::compiler::Arm64OperandConverter::InputFloat32OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat32Register(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64Register(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroDoubleRegister(), and v8::internal::compiler::Arm64OperandConverter::InputSimd128Register().
InputExternalReference()
ExternalReference v8::internal::compiler::InstructionOperandConverter::InputExternalReference (size_t index) [inline]
Definition at line 96 of file code-generator-impl.h.
                                                         {
    return ToExternalReference(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToExternalReference().
InputFloat32()
float v8::internal::compiler::InstructionOperandConverter::InputFloat32 (size_t index) [inline]
Definition at line 47 of file code-generator-impl.h.
{ return ToFloat32(instr_->InputAt(index)); }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToFloat32().
Referenced by v8::internal::compiler::Arm64OperandConverter::InputFloat32OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrZeroRegister(), and v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister().
InputFloatRegister()
FloatRegister v8::internal::compiler::InstructionOperandConverter::InputFloatRegister (size_t index) [inline]
Definition at line 33 of file code-generator-impl.h.
                                                 {
    return ToFloatRegister(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToFloatRegister().
InputInt16()
int16_t v8::internal::compiler::InstructionOperandConverter::InputInt16 (size_t index) [inline]
Definition at line 69 of file code-generator-impl.h.
                                   {
    return static_cast<int16_t>(InputInt32(index));
  }
References v8::internal::index, InputInt32(), and v8::internal::compiler::int16_t.
InputInt3()
uint8_t v8::internal::compiler::InstructionOperandConverter::InputInt3 (size_t index) [inline]
Definition at line 73 of file code-generator-impl.h.
                                  {
    return static_cast<uint8_t>(InputInt32(index) & 0x7);
  }
References v8::internal::index, and InputInt32().
InputInt32()
int32_t v8::internal::compiler::InstructionOperandConverter::InputInt32 (size_t index) [inline]
Definition at line 49 of file code-generator-impl.h.
                                   {
    return ToConstant(instr_->InputAt(index)).ToInt32();
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, ToConstant(), and v8::internal::compiler::Constant::ToInt32().
Referenced by v8::internal::compiler::CodeGenerator::GetSlotAboveSPBeforeTailCall(), InputInt16(), InputInt3(), InputInt4(), InputInt5(), InputInt6(), InputInt8(), v8::internal::compiler::ArmOperandConverter::InputOffset(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister32(), InputUint32(), v8::internal::compiler::S390OperandConverter::MemoryOperand(), v8::internal::compiler::Loong64OperandConverter::MemoryOperand(), v8::internal::compiler::MipsOperandConverter::MemoryOperand(), v8::internal::compiler::RiscvOperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::X64OperandConverter::MemoryOperand(), and v8::internal::compiler::Arm64OperandConverter::MemoryOperand().
InputInt4()
uint8_t v8::internal::compiler::InstructionOperandConverter::InputInt4 (size_t index) [inline]
Definition at line 77 of file code-generator-impl.h.
                                  {
    return static_cast<uint8_t>(InputInt32(index) & 0xF);
  }
References v8::internal::index, and InputInt32().
InputInt5()
uint8_t v8::internal::compiler::InstructionOperandConverter::InputInt5 (size_t index) [inline]
Definition at line 81 of file code-generator-impl.h.
                                  {
    return static_cast<uint8_t>(InputInt32(index) & 0x1F);
  }
References v8::internal::index, and InputInt32().
Referenced by v8::internal::compiler::ArmOperandConverter::InputOperand2(), and v8::internal::compiler::Arm64OperandConverter::InputOperand2_32().
InputInt6()
uint8_t v8::internal::compiler::InstructionOperandConverter::InputInt6 (size_t index) [inline]
Definition at line 85 of file code-generator-impl.h.
                                  {
    return static_cast<uint8_t>(InputInt32(index) & 0x3F);
  }
References v8::internal::index, and InputInt32().
Referenced by v8::internal::compiler::Arm64OperandConverter::InputOperand2_64().
InputInt64()
int64_t v8::internal::compiler::InstructionOperandConverter::InputInt64 (size_t index) [inline]
Definition at line 57 of file code-generator-impl.h.
                                   {
    return ToConstant(instr_->InputAt(index)).ToInt64();
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, ToConstant(), and v8::internal::compiler::Constant::ToInt64().
Referenced by v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister64(), v8::internal::compiler::PPCOperandConverter::MemoryOperand(), and v8::internal::compiler::Arm64OperandConverter::MemoryOperand().
InputInt8()
int8_t v8::internal::compiler::InstructionOperandConverter::InputInt8 (size_t index) [inline]
Definition at line 61 of file code-generator-impl.h.
                                 {
    return static_cast<int8_t>(InputInt32(index));
  }
References v8::internal::index, and InputInt32().
Referenced by InputUint8().
InputLabel()
Label* v8::internal::compiler::InstructionOperandConverter::InputLabel (size_t index) [inline]
Definition at line 104 of file code-generator-impl.h.
{ return ToLabel(instr_->InputAt(index)); }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToLabel().
InputRegister()
Register v8::internal::compiler::InstructionOperandConverter::InputRegister (size_t index) const [inline]
Definition at line 29 of file code-generator-impl.h.
                                             {
    return ToRegister(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToRegister().
Referenced by v8::internal::compiler::ArmOperandConverter::InputOffset(), v8::internal::compiler::ArmOperandConverter::InputOperand2(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputRegister64(), v8::internal::compiler::PPCOperandConverter::MemoryOperand(), v8::internal::compiler::S390OperandConverter::MemoryOperand(), v8::internal::compiler::Loong64OperandConverter::MemoryOperand(), v8::internal::compiler::MipsOperandConverter::MemoryOperand(), v8::internal::compiler::RiscvOperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::X64OperandConverter::MemoryOperand(), v8::internal::compiler::Arm64OperandConverter::MemoryOperand(), v8::internal::compiler::ArmOperandConverter::NeonInputOperand(), and v8::internal::compiler::IA32OperandConverter::NextMemoryOperand().
InputRpo()
RpoNumber v8::internal::compiler::InstructionOperandConverter::InputRpo (size_t index) [inline]
Definition at line 106 of file code-generator-impl.h.
                                   {
    return ToRpoNumber(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToRpoNumber().
InputSimd128Register()
Simd128Register v8::internal::compiler::InstructionOperandConverter::InputSimd128Register (size_t index) [inline]
Definition at line 41 of file code-generator-impl.h.
                                                     {
    return ToSimd128Register(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), instr_, and ToSimd128Register().
InputUint32()
uint32_t v8::internal::compiler::InstructionOperandConverter::InputUint32 (size_t index) [inline]
Definition at line 53 of file code-generator-impl.h.
                                     {
    return base::bit_cast<uint32_t>(InputInt32(index));
  }
References v8::internal::index, and InputInt32().
Referenced by InputCodeEntrypointTag().
InputUint8()
uint8_t v8::internal::compiler::InstructionOperandConverter::InputUint8 (size_t index) [inline]
Definition at line 65 of file code-generator-impl.h.
                                   {
    return base::bit_cast<uint8_t>(InputInt8(index));
  }
References v8::internal::index, and InputInt8().
isolate()
Isolate* v8::internal::compiler::InstructionOperandConverter::isolate () const [inline]
Definition at line 216 of file code-generator-impl.h.
{ return gen_->isolate(); }
References gen_, and v8::internal::compiler::CodeGenerator::isolate().
linkage()
Linkage* v8::internal::compiler::InstructionOperandConverter::linkage () const [inline]
Definition at line 217 of file code-generator-impl.h.
{ return gen_->linkage(); }
References gen_, and v8::internal::compiler::CodeGenerator::linkage().
OutputDoubleRegister()
DoubleRegister v8::internal::compiler::InstructionOperandConverter::OutputDoubleRegister (size_t index = 0) [inline]
Definition at line 122 of file code-generator-impl.h.
                                                        {
    return ToDoubleRegister(instr_->OutputAt(index));
  }
References v8::internal::index, instr_, v8::internal::compiler::Instruction::OutputAt(), and ToDoubleRegister().
Referenced by v8::internal::compiler::Arm64OperandConverter::OutputFloat32Register(), v8::internal::compiler::Arm64OperandConverter::OutputFloat64Register(), and v8::internal::compiler::Arm64OperandConverter::OutputSimd128Register().
OutputFloatRegister()
FloatRegister v8::internal::compiler::InstructionOperandConverter::OutputFloatRegister (size_t index = 0) [inline]
Definition at line 118 of file code-generator-impl.h.
                                                      {
    return ToFloatRegister(instr_->OutputAt(index));
  }
References v8::internal::index, instr_, v8::internal::compiler::Instruction::OutputAt(), and ToFloatRegister().
OutputRegister()
Register v8::internal::compiler::InstructionOperandConverter::OutputRegister (size_t index = 0) const [inline]
Definition at line 110 of file code-generator-impl.h.
                                                  {
    return ToRegister(instr_->OutputAt(index));
  }
References v8::internal::index, instr_, v8::internal::compiler::Instruction::OutputAt(), and ToRegister().
Referenced by v8::internal::compiler::Arm64OperandConverter::OutputRegister32(), and v8::internal::compiler::Arm64OperandConverter::OutputRegister64().
OutputSimd128Register()
Simd128Register v8::internal::compiler::InstructionOperandConverter::OutputSimd128Register () [inline]
Definition at line 130 of file code-generator-impl.h.
                                          {
    return ToSimd128Register(instr_->Output());
  }
References instr_, v8::internal::compiler::Instruction::Output(), and ToSimd128Register().
TempDoubleRegister()
DoubleRegister v8::internal::compiler::InstructionOperandConverter::TempDoubleRegister (size_t index) [inline]
Definition at line 126 of file code-generator-impl.h.
                                                  {
    return ToDoubleRegister(instr_->TempAt(index));
  }
References v8::internal::index, instr_, v8::internal::compiler::Instruction::TempAt(), and ToDoubleRegister().
TempRegister()
Register v8::internal::compiler::InstructionOperandConverter::TempRegister (size_t index) [inline]
Definition at line 114 of file code-generator-impl.h.
                                      {
    return ToRegister(instr_->TempAt(index));
  }
References v8::internal::index, instr_, v8::internal::compiler::Instruction::TempAt(), and ToRegister().
TempSimd128Register()
Simd128Register v8::internal::compiler::InstructionOperandConverter::TempSimd128Register (size_t index) [inline]
Definition at line 134 of file code-generator-impl.h.
                                                    {
    return ToSimd128Register(instr_->TempAt(index));
  }
References v8::internal::index, instr_, v8::internal::compiler::Instruction::TempAt(), and ToSimd128Register().
ToCode()
Handle<Code> v8::internal::compiler::InstructionOperandConverter::ToCode (InstructionOperand * op) [inline]
Definition at line 208 of file code-generator-impl.h.
                                              {
    return ToConstant(op).ToCode();
  }
References v8::internal::compiler::Constant::ToCode(), and ToConstant().
Referenced by InputCode().
ToConstant()
Constant v8::internal::compiler::InstructionOperandConverter::ToConstant (InstructionOperand * op) const [inline]
Definition at line 190 of file code-generator-impl.h.
                                                    {
    if (op->IsImmediate()) {
      return gen_->instructions()->GetImmediate(ImmediateOperand::cast(op));
    }
    return gen_->instructions()->GetConstant(
        ConstantOperand::cast(op)->virtual_register());
  }
References gen_, v8::internal::compiler::InstructionSequence::GetConstant(), v8::internal::compiler::InstructionSequence::GetImmediate(), and v8::internal::compiler::CodeGenerator::instructions().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), InputInt32(), InputInt64(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), ToCode(), ToDouble(), ToExternalReference(), ToFloat32(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), v8::internal::compiler::ArmOperandConverter::ToImmediate(), and ToRpoNumber().
ToDouble()
double v8::internal::compiler::InstructionOperandConverter::ToDouble (InstructionOperand * op) [inline]
Definition at line 198 of file code-generator-impl.h.
                                          {
    return ToConstant(op).ToFloat64().value();
  }
References ToConstant(), v8::internal::compiler::Constant::ToFloat64(), and v8::base::Double::value().
Referenced by InputDouble().
ToDoubleRegister()
DoubleRegister v8::internal::compiler::InstructionOperandConverter::ToDoubleRegister (InstructionOperand * op) [inline]
Definition at line 170 of file code-generator-impl.h.
                                                          {
    return LocationOperand::cast(op)->GetDoubleRegister();
  }
References v8::internal::compiler::LocationOperand::cast(), and v8::internal::compiler::LocationOperand::GetDoubleRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), InputDoubleRegister(), OutputDoubleRegister(), TempDoubleRegister(), v8::internal::compiler::IA32OperandConverter::ToOperand(), v8::internal::compiler::Loong64OperandConverter::ToSingleRegister(), v8::internal::compiler::MipsOperandConverter::ToSingleRegister(), and v8::internal::compiler::RiscvOperandConverter::ToSingleRegister().
ToExternalReference()
ExternalReference v8::internal::compiler::InstructionOperandConverter::ToExternalReference (InstructionOperand * op) [inline]
Definition at line 204 of file code-generator-impl.h.
                                                                {
    return ToConstant(op).ToExternalReference();
  }
References ToConstant(), and v8::internal::compiler::Constant::ToExternalReference().
Referenced by InputExternalReference().
ToFloat32()
float v8::internal::compiler::InstructionOperandConverter::ToFloat32 (InstructionOperand * op) [inline]
Definition at line 202 of file code-generator-impl.h.
{ return ToConstant(op).ToFloat32(); }
References ToConstant(), and v8::internal::compiler::Constant::ToFloat32().
Referenced by InputFloat32().
ToFloatRegister()
FloatRegister v8::internal::compiler::InstructionOperandConverter::ToFloatRegister (InstructionOperand * op) [inline]
Definition at line 166 of file code-generator-impl.h.
                                                        {
    return LocationOperand::cast(op)->GetFloatRegister();
  }
References v8::internal::compiler::LocationOperand::cast(), and v8::internal::compiler::LocationOperand::GetFloatRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleMove(), InputFloatRegister(), v8::internal::compiler::CodeGenerator::MoveTempLocationTo(), v8::internal::compiler::CodeGenerator::MoveToTempLocation(), and OutputFloatRegister().
ToLabel()
Label* v8::internal::compiler::InstructionOperandConverter::ToLabel (InstructionOperand * op) [inline]
Definition at line 154 of file code-generator-impl.h.
                                         {
    return gen_->GetLabel(ToRpoNumber(op));
  }
References gen_, v8::internal::compiler::CodeGenerator::GetLabel(), and ToRpoNumber().
Referenced by InputLabel(), and v8::internal::compiler::IA32OperandConverter::ToImmediate().
ToRegister()
Register v8::internal::compiler::InstructionOperandConverter::ToRegister (InstructionOperand * op) const [inline]
Definition at line 162 of file code-generator-impl.h.
                                                    {
    return LocationOperand::cast(op)->GetRegister();
  }
References v8::internal::compiler::LocationOperand::cast(), and v8::internal::compiler::LocationOperand::GetRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::compiler::Loong64OperandConverter::InputOperand(), v8::internal::compiler::MipsOperandConverter::InputOperand(), v8::internal::compiler::RiscvOperandConverter::InputOperand(), InputRegister(), v8::internal::compiler::Arm64OperandConverter::InputRegister32(), v8::internal::compiler::IA32OperandConverter::MoveInstructionOperandToRegister(), v8::internal::compiler::CodeGenerator::MoveTempLocationTo(), v8::internal::compiler::CodeGenerator::MoveToTempLocation(), OutputRegister(), v8::internal::compiler::CodeGenerator::Pop(), v8::internal::compiler::CodeGenerator::Push(), TempRegister(), v8::internal::compiler::Arm64OperandConverter::TempRegister32(), v8::internal::compiler::Arm64OperandConverter::ToOperand(), v8::internal::compiler::IA32OperandConverter::ToOperand(), and v8::internal::compiler::Arm64OperandConverter::ToOperand32().
ToRpoNumber()
RpoNumber v8::internal::compiler::InstructionOperandConverter::ToRpoNumber (InstructionOperand * op) [inline]
Definition at line 158 of file code-generator-impl.h.
                                                {
    return ToConstant(op).ToRpoNumber();
  }
References ToConstant(), and v8::internal::compiler::Constant::ToRpoNumber().
Referenced by InputRpo(), and ToLabel().
ToSimd128Register()
Simd128Register v8::internal::compiler::InstructionOperandConverter::ToSimd128Register (InstructionOperand * op) [inline]
Definition at line 174 of file code-generator-impl.h.
                                                            {
    LocationOperand* loc_op = LocationOperand::cast(op);
#ifdef V8_TARGET_ARCH_X64
    if (loc_op->IsSimd256Register()) {
      return loc_op->GetSimd256RegisterAsSimd128();
    }
#endif
    return loc_op->GetSimd128Register();
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::compiler::LocationOperand::GetSimd128Register(), and v8::internal::compiler::InstructionOperand::IsSimd256Register().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), InputSimd128Register(), OutputSimd128Register(), and TempSimd128Register().
Member Data Documentation
gen_
CodeGenerator* v8::internal::compiler::InstructionOperandConverter::gen_ [protected]
Definition at line 220 of file code-generator-impl.h.
Referenced by frame(), frame_access_state(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), isolate(), linkage(), v8::internal::compiler::IA32OperandConverter::MoveInstructionOperandToRegister(), ToConstant(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), and ToLabel().
instr_
Instruction* v8::internal::compiler::InstructionOperandConverter::instr_ [protected]
Definition at line 221 of file code-generator-impl.h.
Referenced by v8::internal::compiler::PPCOperandConverter::CompareLogical(), v8::internal::compiler::S390OperandConverter::CompareLogical(), InputCode(), InputDouble(), InputDoubleRegister(), InputExternalReference(), InputFloat32(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat32OrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrFPZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputFloat64OrZeroRegister(), InputFloatRegister(), v8::internal::compiler::IA32OperandConverter::InputImmediate(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::X64OperandConverter::InputImmediate(), v8::internal::compiler::ArmOperandConverter::InputImmediate(), InputInt32(), InputInt64(), InputLabel(), v8::internal::compiler::ArmOperandConverter::InputOffset(), v8::internal::compiler::Arm64OperandConverter::InputOperand(), v8::internal::compiler::Loong64OperandConverter::InputOperand(), v8::internal::compiler::MipsOperandConverter::InputOperand(), v8::internal::compiler::RiscvOperandConverter::InputOperand(), v8::internal::compiler::IA32OperandConverter::InputOperand(), v8::internal::compiler::X64OperandConverter::InputOperand(), v8::internal::compiler::ArmOperandConverter::InputOperand2(), v8::internal::compiler::Arm64OperandConverter::InputOperand2_32(), v8::internal::compiler::Arm64OperandConverter::InputOperand2_64(), v8::internal::compiler::Arm64OperandConverter::InputOperand32(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroDoubleRegister(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister32(), v8::internal::compiler::Arm64OperandConverter::InputOrZeroRegister64(), v8::internal::compiler::Loong64OperandConverter::InputOrZeroSingleRegister(), v8::internal::compiler::MipsOperandConverter::InputOrZeroSingleRegister(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroSingleRegister(), InputRegister(), v8::internal::compiler::Arm64OperandConverter::InputRegister32(), InputRpo(), InputSimd128Register(), v8::internal::compiler::Loong64OperandConverter::InputSingleRegister(), v8::internal::compiler::MipsOperandConverter::InputSingleRegister(), v8::internal::compiler::RiscvOperandConverter::InputSingleRegister(), v8::internal::compiler::S390OperandConverter::InputStackSlot(), v8::internal::compiler::S390OperandConverter::Is32BitOperand(), v8::internal::compiler::S390OperandConverter::Is64BitOperand(), v8::internal::compiler::PPCOperandConverter::MemoryOperand(), v8::internal::compiler::S390OperandConverter::MemoryOperand(), v8::internal::compiler::Loong64OperandConverter::MemoryOperand(), v8::internal::compiler::MipsOperandConverter::MemoryOperand(), v8::internal::compiler::RiscvOperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::X64OperandConverter::MemoryOperand(), v8::internal::compiler::Arm64OperandConverter::MemoryOperand(), v8::internal::compiler::ArmOperandConverter::NeonInputOperand(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::compiler::Arm64OperandConverter::OutputCount(), v8::internal::compiler::PPCOperandConverter::OutputCount(), v8::internal::compiler::S390OperandConverter::OutputCount(), OutputDoubleRegister(), OutputFloatRegister(), v8::internal::compiler::IA32OperandConverter::OutputOperand(), v8::internal::compiler::X64OperandConverter::OutputOperand(), v8::internal::compiler::PPCOperandConverter::OutputRCBit(), OutputRegister(), v8::internal::compiler::ArmOperandConverter::OutputSBit(), OutputSimd128Register(), v8::internal::compiler::Loong64OperandConverter::OutputSingleRegister(), v8::internal::compiler::MipsOperandConverter::OutputSingleRegister(), v8::internal::compiler::RiscvOperandConverter::OutputSingleRegister(), TempDoubleRegister(), TempRegister(), v8::internal::compiler::Arm64OperandConverter::TempRegister32(), and TempSimd128Register().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/code-generator-impl.h