v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration Class Reference
Public Member Functions
ControlScopeForIteration (BytecodeGenerator *generator, IterationStatement *statement, LoopBuilder *loop_builder)
Protected Member Functions
bool Execute (Command command, Statement *statement, int source_position) override
Private Attributes
Statement * statement_
LoopBuilder * loop_builder_
Additional Inherited Members
Detailed Description
Definition at line 472 of file bytecode-generator.cc.
Constructor & Destructor Documentation
ControlScopeForIteration()
v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::ControlScopeForIteration (BytecodeGenerator * generator, IterationStatement * statement, LoopBuilder * loop_builder) [inline]
Definition at line 475 of file bytecode-generator.cc.
      : ControlScope(generator),
        statement_(statement),
        loop_builder_(loop_builder) {}
Member Function Documentation
Execute()
bool v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::Execute (Command command, Statement * statement, int source_position) [inline], [override], [protected], [virtual]
Implements v8::internal::interpreter::BytecodeGenerator::ControlScope.
Definition at line 483 of file bytecode-generator.cc.
                                             {
    if (statement != statement_) return false;
    switch (command) {
      case CMD_BREAK:
        PopContextToExpectedDepth();
        loop_builder_->Break();
        return true;
      case CMD_CONTINUE:
        PopContextToExpectedDepth();
        loop_builder_->Continue();
        return true;
      case CMD_RETURN:
      case CMD_ASYNC_RETURN:
      case CMD_RETHROW:
        break;
    }
    return false;
  }
References v8::internal::interpreter::BreakableControlFlowBuilder::Break(), v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_ASYNC_RETURN, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_BREAK, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_CONTINUE, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETHROW, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETURN, v8::internal::interpreter::LoopBuilder::Continue(), loop_builder_, v8::internal::interpreter::BytecodeGenerator::ControlScope::PopContextToExpectedDepth(), and statement_.
Member Data Documentation
loop_builder_
LoopBuilder* v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::loop_builder_ [private]
Definition at line 505 of file bytecode-generator.cc.
Referenced by Execute().
statement_
Statement* v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::statement_ [private]
Definition at line 504 of file bytecode-generator.cc.
Referenced by Execute().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc