v8::internal::compiler::AccessInfoFactory Class Reference
#include <access-info.h>
Public Member Functions
AccessInfoFactory (JSHeapBroker *broker, Zone *zone)
std::optional< ElementAccessInfo > ComputeElementAccessInfo (MapRef map, AccessMode access_mode) const
bool ComputeElementAccessInfos (ElementAccessFeedback const &feedback, ZoneVector< ElementAccessInfo > *access_infos) const
PropertyAccessInfo ComputePropertyAccessInfo (MapRef map, NameRef name, AccessMode access_mode) const
PropertyAccessInfo ComputeDictionaryProtoAccessInfo (MapRef receiver_map, NameRef name, JSObjectRef holder, InternalIndex dict_index, AccessMode access_mode, PropertyDetails details) const
bool FinalizePropertyAccessInfos (ZoneVector< PropertyAccessInfo > infos, AccessMode access_mode, ZoneVector< PropertyAccessInfo > *result) const
PropertyAccessInfo FinalizePropertyAccessInfosAsOne (ZoneVector< PropertyAccessInfo > infos, AccessMode access_mode) const
Private Member Functions
std::optional< ElementAccessInfo > ConsolidateElementLoad (ElementAccessFeedback const &feedback) const
PropertyAccessInfo LookupSpecialFieldAccessor (MapRef map, NameRef name) const
PropertyAccessInfo LookupSpecialFieldAccessorInHolder (MapRef receiver_map, NameRef name, JSObjectRef holder, PropertyDetails details, InternalIndex index) const
PropertyAccessInfo LookupTransition (MapRef map, NameRef name, OptionalJSObjectRef holder, PropertyAttributes attrs) const
PropertyAccessInfo ComputeDataFieldAccessInfo (MapRef receiver_map, MapRef map, NameRef name, OptionalJSObjectRef holder, InternalIndex descriptor, AccessMode access_mode) const
PropertyAccessInfo ComputeAccessorDescriptorAccessInfo (MapRef receiver_map, NameRef name, MapRef map, OptionalJSObjectRef holder, InternalIndex descriptor, AccessMode access_mode) const
PropertyAccessInfo Invalid () const
void MergePropertyAccessInfos (ZoneVector< PropertyAccessInfo > infos, AccessMode access_mode, ZoneVector< PropertyAccessInfo > *result) const
bool TryLoadPropertyDetails (MapRef map, OptionalJSObjectRef maybe_holder, NameRef name, InternalIndex *index_out, PropertyDetails *details_out) const
bool ObjectMayHaveElements (JSObjectRef obj, MapRef map) const
bool ObjectMayHaveOwnProperties (JSObjectRef obj, MapRef map) const
CompilationDependencies * dependencies () const
JSHeapBroker * broker () const
Isolate * isolate () const
Zone * zone () const
AccessInfoFactory (const AccessInfoFactory &)=delete
AccessInfoFactory & operator= (const AccessInfoFactory &)=delete
Private Attributes
JSHeapBroker *const broker_
TypeCache const *const type_cache_
Zone *const zone_
Detailed Description
Definition at line 256 of file access-info.h.
Constructor & Destructor Documentation
AccessInfoFactory() [1/2]
v8::internal::compiler::AccessInfoFactory::AccessInfoFactory (JSHeapBroker * broker, Zone * zone)
Definition at line 405 of file access-info.cc.
    : broker_(broker), type_cache_(TypeCache::Get()), zone_(zone) {}
AccessInfoFactory() [2/2]
v8::internal::compiler::AccessInfoFactory::AccessInfoFactory (const AccessInfoFactory &) [private], [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::AccessInfoFactory::broker () const [inline], [private]
Definition at line 323 of file access-info.h.
{ return broker_; }
References broker_.
Referenced by ComputeAccessorDescriptorAccessInfo(), ComputeDataFieldAccessInfo(), ComputeDictionaryProtoAccessInfo(), ComputeElementAccessInfo(), ComputePropertyAccessInfo(), dependencies(), isolate(), LookupSpecialFieldAccessor(), LookupTransition(), ObjectMayHaveElements(), and TryLoadPropertyDetails().
ComputeAccessorDescriptorAccessInfo()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::ComputeAccessorDescriptorAccessInfo (MapRef receiver_map, NameRef name, MapRef map, OptionalJSObjectRef holder, InternalIndex descriptor, AccessMode access_mode) const [private]
Definition at line 811 of file access-info.cc.
                                  {
  DCHECK(descriptor.is_found());
  Handle<DescriptorArray> descriptors = broker()->CanonicalPersistentHandle(
      holder_map.object()->instance_descriptors(kRelaxedLoad));
  SLOW_DCHECK(descriptor ==
              descriptors->Search(*name.object(), *holder_map.object(), true));
  auto get_accessors = [&]() {
    return broker()->CanonicalPersistentHandle(
        descriptors->GetStrongValue(descriptor));
  };
  return AccessorAccessInfoHelper(isolate(), zone(), broker(), this,
                                  receiver_map, name, holder_map, holder,
                                  access_mode, get_accessors);
}
References v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), broker(), v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle(), v8::internal::DCHECK(), v8::internal::InternalIndex::is_found(), isolate(), v8::kRelaxedLoad, v8::internal::name, v8::internal::compiler::MapRef::object(), SLOW_DCHECK, and zone().
Referenced by ComputePropertyAccessInfo().
ComputeDataFieldAccessInfo()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo (MapRef receiver_map, MapRef map, NameRef name, OptionalJSObjectRef holder, InternalIndex descriptor, AccessMode access_mode) const [private]
Definition at line 585 of file access-info.cc.
                                                            {
  DCHECK(descriptor.is_found());
  // TODO(jgruber,v8:7790): Use DescriptorArrayRef instead.
  DirectHandle<DescriptorArray> descriptors =
      map.instance_descriptors(broker()).object();
  PropertyDetails const details = descriptors->GetDetails(descriptor);
  int index = descriptors->GetFieldIndex(descriptor);
  Representation details_representation = details.representation();
  if (details_representation.IsNone()) {
    // The ICs collect feedback in PREMONOMORPHIC state already,
    // but at this point the {receiver_map} might still contain
    // fields for which the representation has not yet been
    // determined by the runtime. So we need to catch this case
    // here and fall back to use the regular IC logic instead.
    return Invalid();
  }
  FieldIndex field_index = FieldIndex::ForPropertyIndex(*map.object(), index,
                                                        details_representation);
  // Private brands are used when loading private methods, which are stored in a
  // BlockContext, an internal object.
  Type field_type = name.object()->IsPrivateBrand() ? Type::OtherInternal()
                                                    : Type::NonInternal();
  OptionalMapRef field_map;
  ZoneVector<CompilationDependency const*> unrecorded_dependencies(zone());
  Handle<FieldType> descriptors_field_type =
      broker()->CanonicalPersistentHandle(
          descriptors->GetFieldType(descriptor));
  OptionalObjectRef descriptors_field_type_ref =
      TryMakeRef<Object>(broker(), descriptors_field_type);
  if (!descriptors_field_type_ref.has_value()) return Invalid();
  // Note: FindFieldOwner may be called multiple times throughout one
  // compilation. This is safe since its result is fixed for a given map and
  // descriptor.
  MapRef field_owner_map = map.FindFieldOwner(broker(), descriptor);
  if (details_representation.IsSmi()) {
    field_type = Type::SignedSmall();
    unrecorded_dependencies.push_back(
        dependencies()->FieldRepresentationDependencyOffTheRecord(
            map, field_owner_map, descriptor, details_representation));
  } else if (details_representation.IsDouble()) {
    field_type = type_cache_->kFloat64;
    unrecorded_dependencies.push_back(
        dependencies()->FieldRepresentationDependencyOffTheRecord(
            map, field_owner_map, descriptor, details_representation));
  } else if (details_representation.IsHeapObject()) {
    if (IsNone(*descriptors_field_type)) {
      // Cleared field-types are pre-monomorphic states. The field type was
      // garbge collected and we need to record an updated type.
      static_assert(FieldType::kFieldTypesCanBeClearedOnGC);
      switch (access_mode) {
        case AccessMode::kStore:
        case AccessMode::kStoreInLiteral:
        case AccessMode::kDefine:
          return Invalid();
        case AccessMode::kLoad:
        case AccessMode::kHas:
          break;
      }
    }
    unrecorded_dependencies.push_back(
        dependencies()->FieldRepresentationDependencyOffTheRecord(
            map, field_owner_map, descriptor, details_representation));
    if (IsClass(*descriptors_field_type)) {
      // Remember the field map, and try to infer a useful type.
      OptionalMapRef maybe_field_map =
          TryMakeRef(broker(), FieldType::AsClass(*descriptors_field_type));
      if (!maybe_field_map.has_value()) return Invalid();
      field_map = maybe_field_map;
      // field_type can only be inferred from field_map if it is stable and we
      // add a stability dependency. This happens on use in the access builder.
    }
  } else {
    CHECK(details_representation.IsTagged());
  }
  // TODO(turbofan): We may want to do this only depending on the use
  // of the access info.
  unrecorded_dependencies.push_back(
      dependencies()->FieldTypeDependencyOffTheRecord(
          map, field_owner_map, descriptor,
          descriptors_field_type_ref.value()));
  PropertyConstness constness =
      map.GetPropertyDetails(broker_, descriptor).constness();
  switch (constness) {
    case PropertyConstness::kMutable:
      return PropertyAccessInfo::DataField(
          broker(), zone(), receiver_map, std::move(unrecorded_dependencies),
          field_index, details_representation, field_type, field_owner_map,
          field_map, holder, {});
    case PropertyConstness::kConst:
      auto constness_dep = dependencies()->FieldConstnessDependencyOffTheRecord(
          map, field_owner_map, descriptor);
      unrecorded_dependencies.push_back(constness_dep);
      return PropertyAccessInfo::FastDataConstant(
          zone(), receiver_map, std::move(unrecorded_dependencies), field_index,
          details_representation, field_type, field_owner_map, field_map,
          holder, {});
  }
  UNREACHABLE();
}
References v8::internal::FieldType::AsClass(), broker(), broker_, v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle(), CHECK, v8::internal::PropertyDetails::constness(), v8::internal::compiler::PropertyAccessInfo::DataField(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::PropertyAccessInfo::FastDataConstant(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::MapRef::FindFieldOwner(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::index, v8::internal::compiler::MapRef::instance_descriptors(), Invalid(), v8::internal::InternalIndex::is_found(), v8::internal::IsClass(), v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), v8::internal::Representation::IsNone(), v8::internal::IsNone(), v8::internal::Representation::IsSmi(), v8::internal::Representation::IsTagged(), v8::internal::kConst, v8::internal::compiler::kDefine, v8::internal::FieldType::kFieldTypesCanBeClearedOnGC, v8::internal::compiler::TypeCache::kFloat64, v8::internal::compiler::kHas, v8::internal::compiler::kLoad, v8::internal::kMutable, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::name, v8::internal::compiler::DescriptorArrayRef::object(), v8::internal::compiler::MapRef::object(), v8::internal::ZoneVector< T >::push_back(), v8::internal::PropertyDetails::representation(), v8::internal::compiler::Type::SignedSmall(), v8::internal::compiler::TryMakeRef(), type_cache_, v8::internal::UNREACHABLE(), and zone().
Referenced by ComputePropertyAccessInfo().
ComputeDictionaryProtoAccessInfo()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo (MapRef receiver_map, NameRef name, JSObjectRef holder, InternalIndex dict_index, AccessMode access_mode, PropertyDetails details) const
Definition at line 830 of file access-info.cc.
                                   {
  CHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
  DCHECK(holder.map(broker()).object()->is_prototype_map());
  DCHECK_EQ(access_mode, AccessMode::kLoad);
  // We can only inline accesses to constant properties.
  if (details.constness() != PropertyConstness::kConst) {
    return Invalid();
  }
  if (details.kind() == PropertyKind::kData) {
    return PropertyAccessInfo::DictionaryProtoDataConstant(
        zone(), receiver_map, holder, dictionary_index, name);
  }
  auto get_accessors = [&]() {
    return JSObject::DictionaryPropertyAt(isolate(), holder.object(),
                                          dictionary_index);
  };
  return AccessorAccessInfoHelper(isolate(), zone(), broker(), this,
                                  receiver_map, name, holder.map(broker()),
                                  holder, access_mode, get_accessors);
}
References v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), broker(), CHECK, v8::internal::PropertyDetails::constness(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSObject::DictionaryPropertyAt(), v8::internal::compiler::PropertyAccessInfo::DictionaryProtoDataConstant(), Invalid(), v8::internal::is_prototype_map, isolate(), v8::internal::kConst, v8::internal::kData, v8::internal::PropertyDetails::kind(), v8::internal::compiler::kLoad, v8::internal::compiler::HeapObjectRef::map(), v8::internal::name, v8::internal::compiler::JSObjectRef::object(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, and zone().
Referenced by ComputePropertyAccessInfo().
ComputeElementAccessInfo()
std::optional< ElementAccessInfo > v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo (MapRef map, AccessMode access_mode) const
Definition at line 444 of file access-info.cc.
                                              {
  if (map.CanInlineElementAccess()) {
    return ElementAccessInfo({{map}, zone()}, map.elements_kind(), zone());
  }
#if V8_ENABLE_WEBASSEMBLY
  if (map.IsWasmObjectMap() &&
      (access_mode == AccessMode::kLoad || access_mode == AccessMode::kStore)) {
    // See if there is a Proxy on the prototype chain that will handle
    // element accesses.
    HeapObjectRef prototype = map.prototype(broker());
    bool prototypes_may_have_properties = false;
    while (true) {
      if (prototype.IsNull()) return {};
      MapRef proto_map = prototype.map(broker());
      if (proto_map.is_access_check_needed()) return {};
      if (proto_map.IsJSObjectMap()) {
        // Any regular prototypes on the chain must be guaranteed not to have
        // or later acquire any elements. We need to require this for both
        // indexed and named mode.
        if (ObjectMayHaveElements(prototype.AsJSObject(), proto_map)) return {};
        // If the Proxy trap we'll find later (see reads of
        // {prototypes_may_have_properties}) supports named properties, we'll
        // need to know whether prototypes contained any named properties.
        prototypes_may_have_properties =
            prototypes_may_have_properties ||
            ObjectMayHaveOwnProperties(prototype.AsJSObject(), proto_map);
        // This prototype is okay. Continue walking the chain.
        prototype = proto_map.prototype(broker());
        continue;
      }
      if (proto_map.IsJSProxyMap()) {
        JSProxyRef proxy = prototype.AsJSProxy();
        if (proxy.is_revocable()) return {};
        // Check the "handler". We do this first because the specific trap
        // function we find determines what to require from the "target".
        OptionalObjectRef maybe_handler = proxy.GetHandler(broker());
        if (!maybe_handler.has_value()) return {};
        if (!maybe_handler->IsJSObject()) return {};
        JSObjectRef handler = maybe_handler.value().AsJSObject();
        MapRef handler_map = handler.map(broker());
        // We could implement support for dictionary-mode handlers, but it's
        // probably not worth it.
        if (handler_map.is_dictionary_map()) return {};
        NameRef trap_name = access_mode == AccessMode::kLoad
                                ? broker()->get_string()
                                : broker()->set_string();
        PropertyAccessInfo trap_info = broker()->GetPropertyAccessInfo(
            handler_map, trap_name, AccessMode::kLoad);
        if (!trap_info.IsFastDataConstant()) return {};
        Representation repr = trap_info.field_representation();
        if (!repr.IsHeapObject() && !repr.IsTagged()) return {};
        OptionalObjectRef trap = handler.GetOwnFastConstantDataProperty(
            broker(), repr, trap_info.field_index(), dependencies());
        if (!trap.has_value()) return {};
        ObjectRef trap_value = trap.value();
        // Check that the trap is a Wasm function. We require that for spec
        // compliance reasons: the JS-to-Wasm value conversion of parameters
        // hides the fact that we're not emitting toString conversion operations
        // for the property keys, which is in particular helpful when the
        // Wasm function wants integer indices anyway.
        if (!trap_value.IsHeapObject()) return {};
        // Support for other callables is not implemented.
        if (!trap_value.AsHeapObject().IsJSFunction()) return {};
        SharedFunctionInfoRef sfi = trap_value.AsJSFunction().shared(broker());
        Tagged<Object> trusted_data =
            sfi.object()->GetTrustedData(broker()->local_isolate_or_isolate());
        if (!IsWasmExportedFunctionData(trusted_data)) return {};
        Tagged<WasmExportedFunctionData> wasm_data =
            Cast<WasmExportedFunctionData>(trusted_data);
        // Supporting receiver-is-first-param mode would require passing
        // the Proxy's handler to the eventual building of the Call node.
        if (wasm_data->receiver_is_first_param()) return {};
        const wasm::CanonicalSig* wasm_signature = wasm_data->sig();
        if (wasm_signature->parameter_count() < 2) return {};
        wasm::CanonicalValueType key_type = wasm_signature->GetParam(1);
        // Check the "target".
        OptionalObjectRef maybe_target = proxy.GetTarget(broker());
        if (!maybe_target.has_value()) return {};
        if (!maybe_target->IsJSObject()) return {};
        JSObjectRef target = maybe_target.value().AsJSObject();
        MapRef target_map = target.map(broker());
        if (ObjectMayHaveElements(target, target_map)) return {};
        if (key_type == wasm::kWasmExternRef) {
          if (prototypes_may_have_properties) return {};
          if (ObjectMayHaveOwnProperties(target, target_map)) return {};
        } else if (key_type != wasm::kWasmI32) {
          return {};
        }
        if (!target_map.prototype(broker()).IsNull()) return {};
        // Finally: all good!
        bool string_keys = key_type == wasm::kWasmExternRef;
        return ElementAccessInfo(map, trap_value, target, string_keys, zone());
      }
      // Nothing else can occur on prototype chains.
      UNREACHABLE();
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return {};
}
References broker(), v8::internal::compiler::MapRef::CanInlineElementAccess(), dependencies(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::compiler::PropertyAccessInfo::field_index(), v8::internal::compiler::PropertyAccessInfo::field_representation(), v8::internal::compiler::JSProxyRef::GetHandler(), v8::internal::compiler::JSObjectRef::GetOwnFastConstantDataProperty(), v8::internal::Signature< T >::GetParam(), v8::internal::compiler::JSHeapBroker::GetPropertyAccessInfo(), v8::internal::compiler::JSProxyRef::GetTarget(), v8::internal::compiler::MapRef::is_access_check_needed(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::compiler::JSProxyRef::is_revocable(), v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant(), v8::internal::Representation::IsHeapObject(), v8::internal::IsNull(), v8::internal::Representation::IsTagged(), v8::internal::compiler::kLoad, v8::internal::compiler::kStore, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmI32, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::SharedFunctionInfoRef::object(), ObjectMayHaveElements(), ObjectMayHaveOwnProperties(), v8::internal::Signature< T >::parameter_count(), v8::internal::compiler::MapRef::prototype(), v8::internal::prototype, v8::internal::UNREACHABLE(), and zone().
Referenced by ComputeElementAccessInfos().
ComputeElementAccessInfos()
bool v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfos (ElementAccessFeedback const & feedback, ZoneVector< ElementAccessInfo > * access_infos) const
Definition at line 551 of file access-info.cc.
                                                       {
  AccessMode access_mode = feedback.keyed_mode().access_mode();
  if (access_mode == AccessMode::kLoad || access_mode == AccessMode::kHas) {
    // For polymorphic loads of similar elements kinds (i.e. all tagged or all
    // double), always use the "worst case" code without a transition. This is
    // much faster than transitioning the elements to the worst case, trading a
    // TransitionElementsKind for a CheckMaps, avoiding mutation of the array.
    std::optional<ElementAccessInfo> access_info =
        ConsolidateElementLoad(feedback);
    if (access_info.has_value()) {
      access_infos->push_back(*access_info);
      return true;
    }
  }
  for (auto const& group : feedback.transition_groups()) {
    DCHECK(!group.empty());
    OptionalMapRef target = group.front();
    std::optional<ElementAccessInfo> access_info =
        ComputeElementAccessInfo(target.value(), access_mode);
    if (!access_info.has_value()) return false;
    for (size_t i = 1; i < group.size(); ++i) {
      OptionalMapRef map_ref = group[i];
      if (!map_ref.has_value()) continue;
      access_info->AddTransitionSource(map_ref.value());
    }
    access_infos->push_back(*access_info);
  }
  return true;
}
References v8::internal::compiler::KeyedAccessMode::access_mode(), ComputeElementAccessInfo(), ConsolidateElementLoad(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::ElementAccessFeedback::keyed_mode(), v8::internal::compiler::kHas, v8::internal::compiler::kLoad, v8::internal::ZoneVector< T >::push_back(), and v8::internal::compiler::ElementAccessFeedback::transition_groups().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess().
ComputePropertyAccessInfo()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo (MapRef map, NameRef name, AccessMode access_mode) const
Definition at line 906 of file access-info.cc.
                                                            {
  CHECK(name.IsUniqueName());
  // Dictionary property const tracking is unsupported with concurrent inlining.
  CHECK(!V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
  JSHeapBroker::MapUpdaterGuardIfNeeded mumd_scope(broker());
  if (access_mode == AccessMode::kHas && !IsJSReceiverMap(*map.object())) {
    return Invalid();
  }
  // Check if it is safe to inline property access for the {map}.
  if (!CanInlinePropertyAccess(map, access_mode)) {
    return Invalid();
  }
  // We support fast inline cases for certain JSObject getters.
  if (access_mode == AccessMode::kLoad || access_mode == AccessMode::kHas) {
    PropertyAccessInfo access_info = LookupSpecialFieldAccessor(map, name);
    if (!access_info.IsInvalid()) return access_info;
  }
  // Only relevant if V8_DICT_PROPERTY_CONST_TRACKING enabled.
  bool dictionary_prototype_on_chain = false;
  bool fast_mode_prototype_on_chain = false;
  // Remember the receiver map. We use {map} as loop variable.
  MapRef receiver_map = map;
  OptionalJSObjectRef holder;
  // Perform the implicit ToObject for primitives here.
  // Implemented according to ES6 section 7.3.2 GetV (V, P).
  // Note: Keep sync'd with
  // CompilationDependencies::DependOnStablePrototypeChains.
  if (receiver_map.IsPrimitiveMap()) {
    OptionalJSFunctionRef constructor =
        broker()->target_native_context().GetConstructorFunction(broker(),
                                                                 receiver_map);
    if (!constructor.has_value()) return Invalid();
    map = constructor->initial_map(broker());
    DCHECK(!map.IsPrimitiveMap());
  }
  while (true) {
    PropertyDetails details = PropertyDetails::Empty();
    InternalIndex index = InternalIndex::NotFound();
    if (!TryLoadPropertyDetails(map, holder, name, &index, &details)) {
      return Invalid();
    }
    if (index.is_found()) {
      if (IsAnyStore(access_mode)) {
        DCHECK(!map.is_dictionary_map());
        // Don't bother optimizing stores to read-only properties.
        if (details.IsReadOnly()) return Invalid();
        if (details.kind() == PropertyKind::kData && holder.has_value()) {
          // This is a store to a property not found on the receiver but on a
          // prototype. According to ES6 section 9.1.9 [[Set]], we need to
          // create a new data property on the receiver. We can still optimize
          // if such a transition already exists.
          return LookupTransition(receiver_map, name, holder, NONE);
        }
      }
      if (IsDefiningStore(access_mode)) {
        if (details.attributes() != PropertyAttributes::NONE ||
            details.kind() != PropertyKind::kData) {
          // We should store the property with WEC attributes, but that's not
          // the attributes of the property that we found. We just bail out and
          // let the runtime figure out what to do (which probably requires
          // changing the object's map).
          // Same for accessor case - we must reconfigure property to a data
          // property.
          return Invalid();
        }
      }
      if (map.is_dictionary_map()) {
        DCHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
        if (fast_mode_prototype_on_chain) {
          // TODO(v8:11248) While the work on dictionary mode prototypes is in
          // progress, we may still see fast mode objects on the chain prior to
          // reaching a dictionary mode prototype holding the property . Due to
          // this only being an intermediate state, we don't stupport these kind
          // of heterogenous prototype chains.
          return Invalid();
        }
        // TryLoadPropertyDetails only succeeds if we know the holder.
        return ComputeDictionaryProtoAccessInfo(
            receiver_map, name, holder.value(), index, access_mode, details);
      }
      if (dictionary_prototype_on_chain) {
        // If V8_DICT_PROPERTY_CONST_TRACKING_BOOL was disabled, then a
        // dictionary prototype would have caused a bailout earlier.
        DCHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
        // TODO(v8:11248) We have a fast mode holder, but there was a dictionary
        // mode prototype earlier on the chain. Note that seeing a fast mode
        // prototype even though V8_DICT_PROPERTY_CONST_TRACKING is enabled
        // should only be possible while the implementation of dictionary mode
        // prototypes is work in progress. Eventually, enabling
        // V8_DICT_PROPERTY_CONST_TRACKING will guarantee that all prototypes
        // are always in dictionary mode, making this case unreachable. However,
        // due to the complications of checking dictionary mode prototypes for
        // modification, we don't attempt to support dictionary mode prototypes
        // occuring before a fast mode holder on the chain.
        return Invalid();
      }
      if (access_mode == AccessMode::kLoad && holder.has_value()) {
        PropertyAccessInfo access_info = LookupSpecialFieldAccessorInHolder(
            receiver_map, name, *holder, details, index);
        if (!access_info.IsInvalid()) return access_info;
      }
      if (details.location() == PropertyLocation::kField) {
        if (details.kind() == PropertyKind::kData) {
          return ComputeDataFieldAccessInfo(receiver_map, map, name, holder,
                                            index, access_mode);
        } else {
          DCHECK_EQ(PropertyKind::kAccessor, details.kind());
          // TODO(turbofan): Add support for general accessors?
          return Invalid();
        }
      } else {
        DCHECK_EQ(PropertyLocation::kDescriptor, details.location());
        DCHECK_EQ(PropertyKind::kAccessor, details.kind());
        return ComputeAccessorDescriptorAccessInfo(receiver_map, name, map,
                                                   holder, index, access_mode);
      }
      UNREACHABLE();
    }
    // The property wasn't found on {map}. Look on the prototype if appropriate.
    DCHECK(!index.is_found());
    // Don't search on the prototype chain for special indices in case of
    // integer indexed exotic objects (see ES6 section 9.4.5).
    if (IsJSTypedArrayMap(*map.object()) && name.IsString()) {
      StringRef name_str = name.AsString();
      SharedStringAccessGuardIfNeeded access_guard(
          *name_str.object(), broker()->local_isolate_or_isolate());
      if (IsSpecialIndex(*name_str.object(), access_guard)) return Invalid();
    }
    // Don't search on the prototype when storing in literals, or performing a
    // Define operation
    if (access_mode == AccessMode::kStoreInLiteral ||
        access_mode == AccessMode::kDefine) {
      PropertyAttributes attrs = NONE;
      if (name.object()->IsPrivate()) {
        // When PrivateNames are added to an object, they are by definition
        // non-enumerable.
        attrs = DONT_ENUM;
      }
      return LookupTransition(receiver_map, name, holder, attrs);
    }
    // Don't lookup private symbols on the prototype chain.
    if (name.object()->IsPrivate()) {
      return Invalid();
    }
    if (V8_DICT_PROPERTY_CONST_TRACKING_BOOL && holder.has_value()) {
      // At this point, we are past the first loop iteration.
      DCHECK(holder->object()->map()->is_prototype_map());
      DCHECK(!holder->map(broker()).equals(receiver_map));
      fast_mode_prototype_on_chain =
          fast_mode_prototype_on_chain || !map.is_dictionary_map();
      dictionary_prototype_on_chain =
          dictionary_prototype_on_chain || map.is_dictionary_map();
    }
    // Walk up the prototype chain.
    // Load the map's prototype's map to guarantee that every time we use it,
    // we use the same Map.
    HeapObjectRef prototype = map.prototype(broker());
    MapRef map_prototype_map = prototype.map(broker());
    if (!IsJSObjectMap(*map_prototype_map.object())) {
      // Don't allow proxies on the prototype chain.
      if (!prototype.IsNull()) {
        DCHECK(IsJSProxy(*prototype.object()) ||
               IsWasmObject(*prototype.object()));
        return Invalid();
      }
      DCHECK(prototype.IsNull());
      if (dictionary_prototype_on_chain) {
        // TODO(v8:11248) See earlier comment about
        // dictionary_prototype_on_chain. We don't support absent properties
        // with dictionary mode prototypes on the chain, either. This is again
        // just due to how we currently deal with dependencies for dictionary
        // properties during finalization.
        return Invalid();
      }
      // Store to property not found on the receiver or any prototype, we need
      // to transition to a new data property.
      // Implemented according to ES6 section 9.1.9 [[Set]] (P, V, Receiver)
      if (access_mode == AccessMode::kStore) {
        return LookupTransition(receiver_map, name, holder, NONE);
      }
      // The property was not found (access returns undefined or throws
      // depending on the language mode of the load operation.
      // Implemented according to ES6 section 9.1.8 [[Get]] (P, Receiver)
      return PropertyAccessInfo::NotFound(zone(), receiver_map, holder);
    }
    CHECK(prototype.IsJSObject());
    holder = prototype.AsJSObject();
    map = map_prototype_map;
    if (!CanInlinePropertyAccess(map, access_mode)) {
      return Invalid();
    }
    // Successful lookup on prototype chain needs to guarantee that all the
    // prototypes up to the holder have stable maps, except for dictionary-mode
    // prototypes. We currently do this by taking a
    // DependOnStablePrototypeChains dependency in the caller.
    //
    // TODO(jgruber): This is brittle and easy to miss. Consider a refactor
    // that moves the responsibility of taking the dependency into
    // AccessInfoFactory.
  }
  UNREACHABLE();
}
References v8::internal::PropertyDetails::attributes(), broker(), v8::internal::compiler::anonymous_namespace{access-info.cc}::CanInlinePropertyAccess(), CHECK, ComputeAccessorDescriptorAccessInfo(), ComputeDataFieldAccessInfo(), ComputeDictionaryProtoAccessInfo(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::DONT_ENUM, v8::internal::PropertyDetails::Empty(), v8::internal::compiler::NativeContextRef::GetConstructorFunction(), v8::internal::index, Invalid(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::compiler::IsAnyStore(), v8::internal::compiler::IsDefiningStore(), v8::internal::compiler::PropertyAccessInfo::IsInvalid(), v8::internal::compiler::MapRef::IsPrimitiveMap(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::IsSpecialIndex(), v8::internal::IsWasmObject(), v8::internal::kAccessor, v8::internal::kData, v8::internal::compiler::kDefine, v8::internal::kDescriptor, v8::internal::kField, v8::internal::compiler::kHas, v8::internal::PropertyDetails::kind(), v8::internal::compiler::kLoad, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, v8::internal::PropertyDetails::location(), LookupSpecialFieldAccessor(), LookupSpecialFieldAccessorInHolder(), LookupTransition(), v8::internal::name, v8::internal::NONE, v8::internal::InternalIndex::NotFound(), v8::internal::compiler::PropertyAccessInfo::NotFound(), v8::internal::compiler::MapRef::object(), v8::internal::compiler::StringRef::object(), v8::internal::compiler::MapRef::prototype(), v8::internal::prototype, v8::internal::compiler::JSHeapBroker::target_native_context(), TryLoadPropertyDetails(), v8::internal::UNREACHABLE(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, and zone().
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), and v8::internal::compiler::JSHeapBroker::GetPropertyAccessInfo().
ConsolidateElementLoad()
std::optional< ElementAccessInfo > v8::internal::compiler::AccessInfoFactory::ConsolidateElementLoad (ElementAccessFeedback const & feedback) const [private]
Definition at line 1227 of file access-info.cc.
                                                 {
  if (feedback.transition_groups().empty()) return {};
  DCHECK(!feedback.transition_groups().front().empty());
  MapRef first_map = feedback.transition_groups().front().front();
  InstanceType instance_type = first_map.instance_type();
  ElementsKind elements_kind = first_map.elements_kind();
  ZoneVector<MapRef> maps(zone());
  for (auto const& group : feedback.transition_groups()) {
    for (MapRef map : group) {
      if (map.instance_type() != instance_type ||
          !map.CanInlineElementAccess()) {
        return {};
      }
      if (!GeneralizeElementsKind(elements_kind, map.elements_kind())
               .To(&elements_kind)) {
        return {};
      }
      maps.push_back(map);
    }
  }
  return ElementAccessInfo(std::move(maps), elements_kind, zone());
}
References v8::internal::DCHECK(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::compiler::anonymous_namespace{access-info.cc}::GeneralizeElementsKind(), v8::internal::compiler::MapRef::instance_type(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::ElementAccessFeedback::transition_groups(), and zone().
Referenced by ComputeElementAccessInfos().
dependencies()
CompilationDependencies * v8::internal::compiler::AccessInfoFactory::dependencies () const [private]
Definition at line 1199 of file access-info.cc.
                                                               {
  return broker()->dependencies();
}
References broker(), and v8::internal::compiler::JSHeapBroker::dependencies().
Referenced by ComputeDataFieldAccessInfo(), ComputeElementAccessInfo(), FinalizePropertyAccessInfos(), FinalizePropertyAccessInfosAsOne(), LookupSpecialFieldAccessorInHolder(), and LookupTransition().
FinalizePropertyAccessInfos()
bool v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfos (ZoneVector< PropertyAccessInfo > infos, AccessMode access_mode, ZoneVector< PropertyAccessInfo > * result) const
Definition at line 1168 of file access-info.cc.
                                                  {
  if (access_infos.empty()) return false;
  MergePropertyAccessInfos(access_infos, access_mode, result);
  for (PropertyAccessInfo const& info : *result) {
    if (info.IsInvalid()) return false;
  }
  for (PropertyAccessInfo& info : *result) {
    info.RecordDependencies(dependencies());
  }
  return true;
}
References dependencies(), v8::internal::ZoneVector< T >::empty(), MergePropertyAccessInfos(), and v8::base::internal::result.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess().
FinalizePropertyAccessInfosAsOne()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfosAsOne (ZoneVector< PropertyAccessInfo > infos, AccessMode access_mode) const
Definition at line 1146 of file access-info.cc.
                                                                               {
  ZoneVector<PropertyAccessInfo> merged_access_infos(zone());
  MergePropertyAccessInfos(access_infos, access_mode, &merged_access_infos);
  if (merged_access_infos.size() == 1) {
    PropertyAccessInfo& result = merged_access_infos.front();
    if (!result.IsInvalid()) {
      result.RecordDependencies(dependencies());
      return result;
    }
  }
  return Invalid();
}
References dependencies(), v8::internal::ZoneVector< T >::front(), Invalid(), MergePropertyAccessInfos(), v8::base::internal::result, v8::internal::ZoneVector< T >::size(), and zone().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), and v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest().
Invalid()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::Invalid () const [inline], [private]
Definition at line 307 of file access-info.h.
                                     {
    return PropertyAccessInfo::Invalid(zone());
  }
References v8::internal::compiler::PropertyAccessInfo::Invalid(), and zone().
Referenced by ComputeDataFieldAccessInfo(), ComputeDictionaryProtoAccessInfo(), ComputePropertyAccessInfo(), FinalizePropertyAccessInfosAsOne(), LookupSpecialFieldAccessor(), LookupSpecialFieldAccessorInHolder(), and LookupTransition().
isolate()
Isolate * v8::internal::compiler::AccessInfoFactory::isolate () const [private]
Definition at line 1202 of file access-info.cc.
{ return broker()->isolate(); }
References broker(), and v8::internal::compiler::JSHeapBroker::isolate().
Referenced by ComputeAccessorDescriptorAccessInfo(), ComputeDictionaryProtoAccessInfo(), LookupSpecialFieldAccessor(), LookupSpecialFieldAccessorInHolder(), LookupTransition(), and TryLoadPropertyDetails().
LookupSpecialFieldAccessor()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor (MapRef map, NameRef name) const [private]
Definition at line 1254 of file access-info.cc.
                                    {
  // Check for String::length field accessor.
  if (IsStringMap(*map.object())) {
    if (Name::Equals(isolate(), name.object(),
                     isolate()->factory()->length_string())) {
      return PropertyAccessInfo::StringLength(zone(), map);
    }
    return Invalid();
  }
  if (IsJSPrimitiveWrapperMap(*map.object()) &&
      (map.elements_kind() == FAST_STRING_WRAPPER_ELEMENTS ||
       map.elements_kind() == SLOW_STRING_WRAPPER_ELEMENTS)) {
    if (Name::Equals(isolate(), name.object(),
                     isolate()->factory()->length_string())) {
      return PropertyAccessInfo::StringWrapperLength(zone(), map);
    }
  }
  // Check for special JSObject field accessors.
  FieldIndex field_index;
  if (Accessors::IsJSObjectFieldAccessor(isolate(), map.object(), name.object(),
                                         &field_index)) {
    Type field_type = Type::NonInternal();
    Representation field_representation = Representation::Tagged();
    if (IsJSArrayMap(*map.object())) {
      DCHECK(Name::Equals(isolate(), isolate()->factory()->length_string(),
                          name.object()));
      // The JSArray::length property is a smi in the range
      // [0, FixedDoubleArray::kMaxLength] in case of fast double
      // elements, a smi in the range [0, FixedArray::kMaxLength]
      // in case of other fast elements, and [0, kMaxUInt32] in
      // case of other arrays.
      if (IsDoubleElementsKind(map.elements_kind())) {
        field_type = type_cache_->kFixedDoubleArrayLengthType;
        field_representation = Representation::Smi();
      } else if (IsFastElementsKind(map.elements_kind())) {
        field_type = type_cache_->kFixedArrayLengthType;
        field_representation = Representation::Smi();
      } else {
        field_type = type_cache_->kJSArrayLengthType;
      }
    }
    // Special fields are always mutable.
    return PropertyAccessInfo::DataField(broker(), zone(), map, {{}, zone()},
                                         field_index, field_representation,
                                         field_type, map, {}, {}, {});
  }
  return Invalid();
}
References broker(), v8::internal::compiler::PropertyAccessInfo::DataField(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::Name::Equals(), v8::internal::FAST_STRING_WRAPPER_ELEMENTS, Invalid(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::Accessors::IsJSObjectFieldAccessor(), isolate(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::TypeCache::kFixedDoubleArrayLengthType, v8::internal::compiler::TypeCache::kJSArrayLengthType, v8::internal::name, v8::internal::compiler::MapRef::object(), v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::Representation::Smi(), v8::internal::compiler::PropertyAccessInfo::StringLength(), v8::internal::compiler::PropertyAccessInfo::StringWrapperLength(), v8::internal::Representation::Tagged(), type_cache_, and zone().
Referenced by ComputePropertyAccessInfo().
LookupSpecialFieldAccessorInHolder()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder (MapRef receiver_map, NameRef name, JSObjectRef holder, PropertyDetails details, InternalIndex index) const [private]
Definition at line 1304 of file access-info.cc.
                                                        {
  // Check whether we're accessing the `length` property in a TypedArray
  // prototype.
  if (v8_flags.typed_array_length_loading &&
      IsJSTypedArrayMap(*receiver_map.object()) &&
      !IsRabGsabTypedArrayElementsKind(receiver_map.elements_kind()) &&
      Name::Equals(isolate(), name.object(),
                   isolate()->factory()->length_string()) &&
      details.location() == PropertyLocation::kDescriptor) {
    Tagged<DescriptorArray> descriptors =
        holder.map(broker_).object()->instance_descriptors(kRelaxedLoad);
    SLOW_DCHECK(index == descriptors->Search(*name.object(),
                                             *holder.map(broker_).object(),
                                             true));
    Tagged<Object> maybe_accessors = descriptors->GetStrongValue(index);
    if (IsAccessorPair(maybe_accessors)) {
      Tagged<AccessorPair> accessors = Cast<AccessorPair>(maybe_accessors);
      Tagged<Object> maybe_getter = accessors->getter(kAcquireLoad);
      if (Tagged<JSFunction> getter;
          TryCast<JSFunction>(maybe_getter, &getter)) {
        if (getter->shared()->HasBuiltinId() &&
            getter->shared()->builtin_id() ==
                Builtin::kTypedArrayPrototypeLength &&
            broker_->dependencies()->DependOnArrayBufferDetachingProtector()) {
          dependencies()->DependOnStablePrototypeChain(
              receiver_map, kStartAtPrototype, holder);
          // TODO(388844115): If we cannot depend on the detaching protector,
          // add a different kind of TypedArrayLength operator which checks for
          // detached before reading the byte_length.
          return PropertyAccessInfo::TypedArrayLength(zone(), receiver_map);
        }
      }
    }
  }
  return Invalid();
}
References broker_, dependencies(), v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnArrayBufferDetachingProtector(), v8::internal::compiler::CompilationDependencies::DependOnStablePrototypeChain(), v8::internal::compiler::MapRef::elements_kind(), v8::internal::Name::Equals(), v8::internal::index, Invalid(), isolate(), v8::internal::IsRabGsabTypedArrayElementsKind(), v8::kAcquireLoad, v8::internal::kDescriptor, v8::kRelaxedLoad, v8::internal::kStartAtPrototype, v8::internal::PropertyDetails::location(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::name, v8::internal::compiler::MapRef::object(), SLOW_DCHECK, v8::internal::compiler::PropertyAccessInfo::TypedArrayLength(), v8::internal::v8_flags, and zone().
Referenced by ComputePropertyAccessInfo().
LookupTransition()
PropertyAccessInfo v8::internal::compiler::AccessInfoFactory::LookupTransition (MapRef map, NameRef name, OptionalJSObjectRef holder, PropertyAttributes attrs) const [private]
Definition at line 1344 of file access-info.cc.
                                    {
  // Check if the {map} has a data transition with the given {name}.
  Tagged<Map> transition =
      TransitionsAccessor(isolate(), *map.object(), true)
          .SearchTransition(*name.object(), PropertyKind::kData, attrs);
  if (transition.is_null()) return Invalid();
  OptionalMapRef maybe_transition_map = TryMakeRef(broker(), transition);
  if (!maybe_transition_map.has_value()) return Invalid();
  MapRef transition_map = maybe_transition_map.value();
  InternalIndex const number = transition_map.object()->LastAdded();
  DirectHandle<DescriptorArray> descriptors =
      transition_map.instance_descriptors(broker()).object();
  PropertyDetails const details = descriptors->GetDetails(number);
  // Don't bother optimizing stores to read-only properties.
  if (details.IsReadOnly()) return Invalid();
  // TODO(bmeurer): Handle transition to data constant?
  if (details.location() != PropertyLocation::kField) return Invalid();
  int const index = details.field_index();
  Representation details_representation = details.representation();
  if (details_representation.IsNone()) return Invalid();
  FieldIndex field_index = FieldIndex::ForPropertyIndex(
      *transition_map.object(), index, details_representation);
  Type field_type = Type::NonInternal();
  OptionalMapRef field_map;
  DCHECK_EQ(transition_map, transition_map.FindFieldOwner(broker(), number));
  ZoneVector<CompilationDependency const*> unrecorded_dependencies(zone());
  if (details_representation.IsSmi()) {
    field_type = Type::SignedSmall();
    unrecorded_dependencies.push_back(
        dependencies()->FieldRepresentationDependencyOffTheRecord(
            transition_map, transition_map, number, details_representation));
  } else if (details_representation.IsDouble()) {
    field_type = type_cache_->kFloat64;
    unrecorded_dependencies.push_back(
        dependencies()->FieldRepresentationDependencyOffTheRecord(
            transition_map, transition_map, number, details_representation));
  } else if (details_representation.IsHeapObject()) {
    // Extract the field type from the property details (make sure its
    // representation is TaggedPointer to reflect the heap object case).
    // TODO(jgruber,v8:7790): Use DescriptorArrayRef instead.
    Handle<FieldType> descriptors_field_type =
        broker()->CanonicalPersistentHandle(descriptors->GetFieldType(number));
    OptionalObjectRef descriptors_field_type_ref =
        TryMakeRef<Object>(broker(), descriptors_field_type);
    if (!descriptors_field_type_ref.has_value()) return Invalid();
    if (IsNone(*descriptors_field_type)) {
      // Cleared field-types are pre-monomorphic states. The field type was
      // garbge collected and we need to record an updated type.
      static_assert(FieldType::kFieldTypesCanBeClearedOnGC);
      return Invalid();
    }
    unrecorded_dependencies.push_back(
        dependencies()->FieldRepresentationDependencyOffTheRecord(
            transition_map, transition_map, number, details_representation));
    if (IsClass(*descriptors_field_type)) {
      unrecorded_dependencies.push_back(
          dependencies()->FieldTypeDependencyOffTheRecord(
              transition_map, transition_map, number,
              *descriptors_field_type_ref));
      // Remember the field map, and try to infer a useful type.
      OptionalMapRef maybe_field_map =
          TryMakeRef(broker(), FieldType::AsClass(*descriptors_field_type));
      if (!maybe_field_map.has_value()) return Invalid();
      field_map = maybe_field_map;
      // field_type can only be inferred from field_map if it is stable and we
      // add a stability dependency. This happens on use in the access builder.
    }
  }
  unrecorded_dependencies.push_back(
      dependencies()->TransitionDependencyOffTheRecord(transition_map));
  // Transitioning stores *may* store to const fields. The resulting
  // DataConstant access infos can be distinguished from later, i.e. redundant,
  // stores to the same constant field by the presence of a transition map.
  PropertyConstness constness =
      transition_map.GetPropertyDetails(broker_, number).constness();
  switch (constness) {
    case PropertyConstness::kMutable:
      return PropertyAccessInfo::DataField(
          broker(), zone(), map, std::move(unrecorded_dependencies),
          field_index, details_representation, field_type, transition_map,
          field_map, holder, transition_map);
    case PropertyConstness::kConst:
      auto constness_dep = dependencies()->FieldConstnessDependencyOffTheRecord(
          transition_map, transition_map, number);
      unrecorded_dependencies.push_back(constness_dep);
      return PropertyAccessInfo::FastDataConstant(
          zone(), map, std::move(unrecorded_dependencies), field_index,
          details_representation, field_type, transition_map, field_map, holder,
          transition_map);
  }
  UNREACHABLE();
}
References v8::internal::FieldType::AsClass(), broker(), broker_, v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle(), v8::internal::PropertyDetails::constness(), v8::internal::compiler::PropertyAccessInfo::DataField(), DCHECK_EQ, dependencies(), v8::internal::compiler::PropertyAccessInfo::FastDataConstant(), v8::internal::PropertyDetails::field_index(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::MapRef::FindFieldOwner(), v8::internal::FieldIndex::ForPropertyIndex(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::index, v8::internal::compiler::MapRef::instance_descriptors(), Invalid(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsClass(), v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), v8::internal::Representation::IsNone(), v8::internal::IsNone(), isolate(), v8::internal::PropertyDetails::IsReadOnly(), v8::internal::Representation::IsSmi(), v8::internal::kConst, v8::internal::kData, v8::internal::kField, v8::internal::FieldType::kFieldTypesCanBeClearedOnGC, v8::internal::compiler::TypeCache::kFloat64, v8::internal::kMutable, v8::internal::PropertyDetails::location(), v8::internal::name, v8::internal::compiler::DescriptorArrayRef::object(), v8::internal::compiler::MapRef::object(), v8::internal::ZoneVector< T >::push_back(), v8::internal::PropertyDetails::representation(), v8::internal::TransitionsAccessor::SearchTransition(), v8::internal::compiler::Type::SignedSmall(), v8::internal::compiler::TryMakeRef(), type_cache_, v8::internal::UNREACHABLE(), and zone().
Referenced by ComputePropertyAccessInfo().
MergePropertyAccessInfos()
void v8::internal::compiler::AccessInfoFactory::MergePropertyAccessInfos (ZoneVector< PropertyAccessInfo > infos, AccessMode access_mode, ZoneVector< PropertyAccessInfo > * result) const [private]
Definition at line 1182 of file access-info.cc.
                                                  {
  DCHECK(result->empty());
  for (auto it = infos.begin(), end = infos.end(); it != end; ++it) {
    bool merged = false;
    for (auto ot = it + 1; ot != end; ++ot) {
      if (ot->Merge(&(*it), access_mode, zone())) {
        merged = true;
        break;
      }
    }
    if (!merged) result->push_back(*it);
  }
  CHECK(!result->empty());
}
References v8::internal::ZoneVector< T >::begin(), CHECK, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::end(), v8::base::internal::result, and zone().
Referenced by FinalizePropertyAccessInfos(), and FinalizePropertyAccessInfosAsOne().
ObjectMayHaveElements()
bool v8::internal::compiler::AccessInfoFactory::ObjectMayHaveElements (JSObjectRef obj, MapRef map) const [private]
Definition at line 408 of file access-info.cc.
                                                                {
  if (IsCustomElementsReceiverInstanceType(map.instance_type())) return true;
  // Ruled out by non-"custom elements" receiver type:
  DCHECK(!map.has_indexed_interceptor());
  if (map.is_extensible()) return true;
  // When the map is not extensible (as we just checked), an empty elements
  // array will always remain empty.
  OptionalFixedArrayBaseRef elements = obj.elements(broker(), kRelaxedLoad);
  if (!elements.has_value()) return true;
  return (elements.value() != broker()->empty_fixed_array() &&
          elements.value() != broker()->empty_slow_element_dictionary());
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::JSObjectRef::elements(), v8::internal::compiler::MapRef::has_indexed_interceptor(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_extensible(), v8::internal::IsCustomElementsReceiverInstanceType(), and v8::kRelaxedLoad.
Referenced by ComputeElementAccessInfo().
ObjectMayHaveOwnProperties()
bool v8::internal::compiler::AccessInfoFactory::ObjectMayHaveOwnProperties (JSObjectRef obj, MapRef map) const [private]
Definition at line 422 of file access-info.cc.
                                                                     {
  if (IsSpecialReceiverInstanceType(map.instance_type())) return true;
  // Ruled out by non-"special" receiver type:
  DCHECK(!map.has_named_interceptor());
  if (map.is_extensible()) return true;
  // When the map is not extensible (as we just checked), an empty property
  // backing store will always remain empty.
  if (map.is_dictionary_map()) {
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      Tagged<SwissNameDictionary> dict =
          obj.object()->property_dictionary_swiss();
      return dict->NumberOfElements() > 0;
    } else {
      Tagged<NameDictionary> dict = obj.object()->property_dictionary();
      return dict->NumberOfElements() > 0;
    }
  } else {
    return map.NumberOfOwnDescriptors() > 0;
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::MapRef::has_named_interceptor(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::compiler::MapRef::is_extensible(), v8::internal::IsSpecialReceiverInstanceType(), v8::internal::compiler::MapRef::NumberOfOwnDescriptors(), v8::internal::compiler::JSObjectRef::object(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by ComputeElementAccessInfo().
operator=()
AccessInfoFactory& v8::internal::compiler::AccessInfoFactory::operator= (const AccessInfoFactory &) [private], [delete]
TryLoadPropertyDetails()
bool v8::internal::compiler::AccessInfoFactory::TryLoadPropertyDetails (MapRef map, OptionalJSObjectRef maybe_holder, NameRef name, InternalIndex * index_out, PropertyDetails * details_out) const [private]
Definition at line 857 of file access-info.cc.
                                                                  {
  if (map.is_dictionary_map()) {
    DCHECK(V8_DICT_PROPERTY_CONST_TRACKING_BOOL);
    DCHECK(map.object()->is_prototype_map());
    DisallowGarbageCollection no_gc;
    if (!maybe_holder.has_value()) {
      // TODO(v8:11457) In this situation, we have a dictionary mode prototype
      // as a receiver. Consider other means of obtaining the holder in this
      // situation.
      // Without the holder, we can't get the property details.
      return false;
    }
    DirectHandle<JSObject> holder = maybe_holder->object();
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      Tagged<SwissNameDictionary> dict = holder->property_dictionary_swiss();
      *index_out = dict->FindEntry(isolate(), name.object());
      if (index_out->is_found()) {
        *details_out = dict->DetailsAt(*index_out);
      }
    } else {
      Tagged<NameDictionary> dict = holder->property_dictionary();
      *index_out = dict->FindEntry(isolate(), name.object());
      if (index_out->is_found()) {
        *details_out = dict->DetailsAt(*index_out);
      }
    }
#if V8_ENABLE_WEBASSEMBLY
  } else if (InstanceTypeChecker::IsWasmObject(map.instance_type())) {
    DCHECK(index_out->is_not_found());
    return true; // Skip to prototypes.
#endif // V8_ENABLE_WEBASSEMBLY
  } else {
    Tagged<DescriptorArray> descriptors =
        *map.instance_descriptors(broker()).object();
    *index_out = descriptors->Search(*name.object(), *map.object(), true);
    if (index_out->is_found()) {
      *details_out = descriptors->GetDetails(*index_out);
    }
  }
  return true;
}
References broker(), v8::internal::DCHECK(), v8::internal::compiler::MapRef::instance_descriptors(), v8::internal::compiler::MapRef::instance_type(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::InternalIndex::is_found(), v8::internal::InternalIndex::is_not_found(), isolate(), v8::internal::IsWasmObject(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::compiler::DescriptorArrayRef::object(), v8::internal::compiler::MapRef::object(), V8_DICT_PROPERTY_CONST_TRACKING_BOOL, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by ComputePropertyAccessInfo().
zone()
Zone* v8::internal::compiler::AccessInfoFactory::zone () const [inline], [private]
Definition at line 325 of file access-info.h.
{ return zone_; }
References zone_.
Referenced by ComputeAccessorDescriptorAccessInfo(), ComputeDataFieldAccessInfo(), ComputeDictionaryProtoAccessInfo(), ComputeElementAccessInfo(), ComputePropertyAccessInfo(), ConsolidateElementLoad(), FinalizePropertyAccessInfosAsOne(), Invalid(), LookupSpecialFieldAccessor(), LookupSpecialFieldAccessorInHolder(), LookupTransition(), and MergePropertyAccessInfos().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::AccessInfoFactory::broker_ [private]
Definition at line 327 of file access-info.h.
Referenced by broker(), ComputeDataFieldAccessInfo(), LookupSpecialFieldAccessorInHolder(), and LookupTransition().
type_cache_
TypeCache const* const v8::internal::compiler::AccessInfoFactory::type_cache_ [private]
Definition at line 328 of file access-info.h.
Referenced by ComputeDataFieldAccessInfo(), LookupSpecialFieldAccessor(), and LookupTransition().
zone_
Zone* const v8::internal::compiler::AccessInfoFactory::zone_ [private]
Definition at line 329 of file access-info.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/access-info.h
/mnt/V8SourceCode/src/compiler/access-info.cc