v8::internal::compiler::Linkage Class Reference
#include <linkage.h>
Public Member Functions
Linkage (CallDescriptor *incoming)
Linkage (const Linkage &)=delete
Linkage & operator= (const Linkage &)=delete
CallDescriptor * GetIncomingDescriptor () const
LinkageLocation GetParameterLocation (int index) const
MachineType GetParameterType (int index) const
LinkageLocation GetReturnLocation (size_t index=0) const
MachineType GetReturnType (size_t index=0) const
bool ParameterHasSecondaryLocation (int index) const
LinkageLocation GetParameterSecondaryLocation (int index) const
LinkageLocation GetOsrValueLocation (int index) const
Static Public Member Functions
static CallDescriptor * ComputeIncoming (Zone *zone, OptimizedCompilationInfo *info)
static CallDescriptor * GetJSCallDescriptor (Zone *zone, bool is_osr, int parameter_count, CallDescriptor::Flags flags, Operator::Properties properties=Operator::kNoProperties)
static CallDescriptor * GetRuntimeCallDescriptor (Zone *zone, Runtime::FunctionId function, int js_parameter_count, Operator::Properties properties, CallDescriptor::Flags flags, LazyDeoptOnThrow lazy_deopt_on_throw=LazyDeoptOnThrow::kNo)
static CallDescriptor * GetCEntryStubCallDescriptor (Zone *zone, int return_count, int js_parameter_count, const char *debug_name, Operator::Properties properties, CallDescriptor::Flags flags, StackArgumentOrder stack_order=StackArgumentOrder::kDefault)
static CallDescriptor * GetStubCallDescriptor (Zone *zone, const CallInterfaceDescriptor &descriptor, int stack_parameter_count, CallDescriptor::Flags flags, Operator::Properties properties=Operator::kNoProperties, StubCallMode stub_mode=StubCallMode::kCallCodeObject)
static CallDescriptor * GetBytecodeDispatchCallDescriptor (Zone *zone, const CallInterfaceDescriptor &descriptor, int stack_parameter_count)
static CallDescriptor * GetSimplifiedCDescriptor (Zone *zone, const MachineSignature *sig, CallDescriptor::Flags flags=CallDescriptor::kNoFlags, Operator::Properties properties=Operator::kNoThrow)
static bool NeedsFrameStateInput (Runtime::FunctionId function)
static int GetStubCallContextParamIndex (int parameter_count)
static constexpr int GetJSCallNewTargetParamIndex (int parameter_count)
static constexpr int GetJSCallArgCountParamIndex (int parameter_count)
static constexpr int GetJSCallContextParamIndex (int parameter_count)
Static Public Attributes
static constexpr int kJSCallClosureParamIndex = kJSCallClosureParameterIndex
static const int kOsrContextSpillSlotIndex = -1
static const int kOsrAccumulatorRegisterIndex = -1
Private Attributes
CallDescriptor *const incoming_
Detailed Description
Definition at line 402 of file linkage.h.
Constructor & Destructor Documentation
Linkage() [1/2]
v8::internal::compiler::Linkage::Linkage (CallDescriptor * incoming) [inline], [explicit]
Definition at line 404 of file linkage.h.
: incoming_(incoming) {}
Linkage() [2/2]
v8::internal::compiler::Linkage::Linkage (const Linkage &) [delete]
Member Function Documentation
ComputeIncoming()
CallDescriptor * v8::internal::compiler::Linkage::ComputeIncoming (Zone * zone, OptimizedCompilationInfo * info) [static]
Definition at line 361 of file linkage.cc.
                                                                         {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(info->IsOptimizing() || info->IsWasm());
#else
  DCHECK(info->IsOptimizing());
#endif // V8_ENABLE_WEBASSEMBLY
  if (!info->closure().is_null()) {
    // If we are compiling a JS function, use a JS call descriptor,
    // plus the receiver.
    DCHECK(info->has_bytecode_array());
    DCHECK_EQ(info->closure()
                  ->shared()
                  ->internal_formal_parameter_count_with_receiver(),
              info->bytecode_array()->parameter_count());
    return GetJSCallDescriptor(zone, info->is_osr(),
                               info->bytecode_array()->parameter_count(),
                               CallDescriptor::kCanUseRoots);
  }
  return nullptr; // TODO(titzer): ?
}
References v8::internal::OptimizedCompilationInfo::bytecode_array(), v8::internal::OptimizedCompilationInfo::closure(), v8::internal::DCHECK(), DCHECK_EQ, GetJSCallDescriptor(), v8::internal::OptimizedCompilationInfo::has_bytecode_array(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::OptimizedCompilationInfo::IsOptimizing(), and v8::internal::compiler::CallDescriptor::kCanUseRoots.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl().
GetBytecodeDispatchCallDescriptor()
CallDescriptor * v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor (Zone * zone, const CallInterfaceDescriptor & descriptor, int stack_parameter_count) [static]
Definition at line 688 of file linkage.cc.
                               {
  const int register_parameter_count = descriptor.GetRegisterParameterCount();
  const int parameter_count = register_parameter_count + stack_parameter_count;
  DCHECK_EQ(descriptor.GetReturnCount(), 1);
  LocationSignature::Builder locations(zone, 1, parameter_count);
  locations.AddReturn(regloc(kReturnRegister0, descriptor.GetReturnType(0)));
  // Add parameters in registers and on the stack.
  for (int i = 0; i < parameter_count; i++) {
    if (i < register_parameter_count) {
      // The first parameters go in registers.
      Register reg = descriptor.GetRegisterParameter(i);
      MachineType type = descriptor.GetParameterType(i);
      locations.AddParam(regloc(reg, type));
    } else {
      // The rest of the parameters go on the stack.
      int stack_slot = i - register_parameter_count - stack_parameter_count;
      locations.AddParam(LinkageLocation::ForCallerFrameSlot(
          stack_slot, MachineType::AnyTagged()));
    }
  }
  // The target for interpreter dispatches is a code entry address.
  MachineType target_type = MachineType::Pointer();
  LinkageLocation target_loc = LinkageLocation::ForAnyRegister(target_type);
  const CallDescriptor::Flags kFlags =
      CallDescriptor::kCanUseRoots | CallDescriptor::kFixedTargetRegister;
  return zone->New<CallDescriptor>(// --
      CallDescriptor::kCallAddress, // kind
      kBytecodeHandlerEntrypointTag, // tag
      target_type, // target MachineType
      target_loc, // target location
      locations.Get(), // location_sig
      stack_parameter_count, // stack_parameter_count
      Operator::kNoProperties, // properties
      kNoCalleeSaved, // callee-saved registers
      kNoCalleeSavedFp, // callee-saved fp
      kFlags, // flags
      descriptor.DebugName());
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::MachineType::AnyTagged(), DCHECK_EQ, v8::internal::CallInterfaceDescriptor::DebugName(), v8::internal::LinkageLocation::ForAnyRegister(), v8::internal::LinkageLocation::ForCallerFrameSlot(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::CallInterfaceDescriptor::GetParameterType(), v8::internal::CallInterfaceDescriptor::GetRegisterParameter(), v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetReturnCount(), v8::internal::CallInterfaceDescriptor::GetReturnType(), v8::internal::kBytecodeHandlerEntrypointTag, v8::internal::compiler::CallDescriptor::kCallAddress, v8::internal::compiler::CallDescriptor::kCanUseRoots, v8::internal::compiler::CallDescriptor::kFixedTargetRegister, v8::internal::compiler::kNoCalleeSaved, v8::internal::compiler::kNoCalleeSavedFp, v8::internal::compiler::Operator::kNoProperties, v8::internal::kReturnRegister0, v8::internal::Zone::New(), v8::internal::MachineType::Pointer(), v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch(), and v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch().
GetCEntryStubCallDescriptor()
CallDescriptor * v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor (Zone * zone, int return_count, int js_parameter_count, const char * debug_name, Operator::Properties properties, CallDescriptor::Flags flags, StackArgumentOrder stack_order = StackArgumentOrder::kDefault) [static]
Definition at line 449 of file linkage.cc.
                                                               {
  const size_t function_count = 1;
  const size_t num_args_count = 1;
  const size_t context_count = 1;
  const size_t parameter_count = function_count +
                                 static_cast<size_t>(js_parameter_count) +
                                 num_args_count + context_count;
  LocationSignature::Builder locations(zone, static_cast<size_t>(return_count),
                                       static_cast<size_t>(parameter_count));
  // Add returns.
  if (locations.return_count_ > 0) {
    locations.AddReturn(regloc(kReturnRegister0, MachineType::AnyTagged()));
  }
  if (locations.return_count_ > 1) {
    locations.AddReturn(regloc(kReturnRegister1, MachineType::AnyTagged()));
  }
  if (locations.return_count_ > 2) {
    locations.AddReturn(regloc(kReturnRegister2, MachineType::AnyTagged()));
  }
  // All parameters to the runtime call go on the stack.
  for (int i = 0; i < js_parameter_count; i++) {
    locations.AddParam(LinkageLocation::ForCallerFrameSlot(
        i - js_parameter_count, MachineType::AnyTagged()));
  }
  // Add runtime function itself.
  locations.AddParam(
      regloc(kRuntimeCallFunctionRegister, MachineType::Pointer()));
  // Add runtime call argument count.
  locations.AddParam(
      regloc(kRuntimeCallArgCountRegister, MachineType::Int32()));
  // Add context.
  locations.AddParam(regloc(kContextRegister, MachineType::AnyTagged()));
  // The target for runtime calls is a code object.
  MachineType target_type = MachineType::AnyTagged();
  LinkageLocation target_loc =
      LinkageLocation::ForAnyRegister(MachineType::AnyTagged());
  return zone->New<CallDescriptor>(// --
      CallDescriptor::kCallCodeObject, // kind
      kDefaultCodeEntrypointTag, // tag
      target_type, // target MachineType
      target_loc, // target location
      locations.Get(), // location_sig
      js_parameter_count, // stack_parameter_count
      properties, // properties
      kNoCalleeSaved, // callee-saved
      kNoCalleeSavedFp, // callee-saved fp
      flags, // flags
      debug_name, // debug name
      stack_order); // stack order
}
References v8::internal::MachineType::AnyTagged(), v8::internal::flags, v8::internal::LinkageLocation::ForAnyRegister(), v8::internal::LinkageLocation::ForCallerFrameSlot(), v8::internal::MachineType::Int32(), v8::internal::compiler::CallDescriptor::kCallCodeObject, v8::internal::kContextRegister, v8::internal::kDefaultCodeEntrypointTag, v8::internal::compiler::kNoCalleeSaved, v8::internal::compiler::kNoCalleeSavedFp, v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, v8::internal::kReturnRegister2, v8::internal::kRuntimeCallArgCountRegister, v8::internal::kRuntimeCallFunctionRegister, v8::internal::Zone::New(), v8::internal::MachineType::Pointer(), and v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc().
Referenced by GetRuntimeCallDescriptor(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
GetIncomingDescriptor()
CallDescriptor* v8::internal::compiler::Linkage::GetIncomingDescriptor () const [inline]
Definition at line 413 of file linkage.h.
{ return incoming_; }
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::compiler::InstructionSelector::CanUseRootsRegister(), v8::internal::compiler::CodeGenerator::FinishFrame(), v8::internal::compiler::turboshaft::Pipeline::GenerateCode(), v8::internal::compiler::CodeGenerator::GetStackCheckOffset(), v8::internal::compiler::CodeGenerator::IsMaterializableFromRoot(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::turboshaft::Pipeline::SelectInstructions(), v8::internal::compiler::InstructionSelector::VisitReturn(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
GetJSCallArgCountParamIndex()
static constexpr int v8::internal::compiler::Linkage::GetJSCallArgCountParamIndex (int parameter_count) [inline], [static], [constexpr]
Definition at line 490 of file linkage.h.
                                                                        {
    return GetJSCallNewTargetParamIndex(parameter_count) + 1;
  }
Referenced by v8::internal::compiler::StartNode::ArgCountOutputIndex(), v8::internal::compiler::StartNode::ArgCountParameterIndex(), and v8::internal::compiler::StartNode::OutputArityForFormalParameterCount().
GetJSCallContextParamIndex()
static constexpr int v8::internal::compiler::Linkage::GetJSCallContextParamIndex (int parameter_count) [inline], [static], [constexpr]
Definition at line 503 of file linkage.h.
                                                                       {
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
    return GetJSCallDispatchHandleParamIndex(parameter_count) + 1;
#else
    return GetJSCallArgCountParamIndex(parameter_count) + 1;
#endif
  }
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::StartNode::ContextOutputIndex(), v8::internal::compiler::StartNode::ContextParameterIndex(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::compiler::CodeAssembler::GetJSContextParameter(), GetOsrValueLocation(), v8::internal::BuiltinsReducer< Next >::JSContextParameter(), v8::internal::compiler::StartNode::OutputArityForFormalParameterCount(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GetJSCallDescriptor()
CallDescriptor * v8::internal::compiler::Linkage::GetJSCallDescriptor (Zone * zone, bool is_osr, int parameter_count, CallDescriptor::Flags flags, Operator::Properties properties = Operator::kNoProperties) [static]
Definition at line 509 of file linkage.cc.
                                                                            {
  const size_t return_count = 1;
  const size_t context_count = 1;
  const size_t new_target_count = 1;
  const size_t num_args_count = 1;
  const size_t dispatch_handle_count =
      V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 1 : 0;
  const size_t parameter_count = js_parameter_count + new_target_count +
                                 num_args_count + dispatch_handle_count +
                                 context_count;
  // The JSCallDescriptor must be compatible both with the interface descriptor
  // of JS builtins and with the general JS calling convention (as defined by
  // the JSTrampolineDescriptor). The JS builtin descriptors are already
  // statically asserted to be compatible with the JS calling convention, so
  // here we just ensure compatibility with the JS builtin descriptors.
  DCHECK_EQ(parameter_count, kJSBuiltinBaseParameterCount + js_parameter_count);
  LocationSignature::Builder locations(zone, return_count, parameter_count);
  // All JS calls have exactly one return value.
  locations.AddReturn(regloc(kReturnRegister0, MachineType::AnyTagged()));
  // All parameters to JS calls go on the stack.
  for (int i = 0; i < js_parameter_count; i++) {
    int spill_slot_index = -i - 1;
    locations.AddParam(LinkageLocation::ForCallerFrameSlot(
        spill_slot_index, MachineType::AnyTagged()));
  }
  // Add JavaScript call new target value.
  locations.AddParam(
      regloc(kJavaScriptCallNewTargetRegister, MachineType::AnyTagged()));
  // Add JavaScript call argument count.
  locations.AddParam(
      regloc(kJavaScriptCallArgCountRegister, MachineType::Int32()));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
  // Add dispatch handle.
  locations.AddParam(
      regloc(kJavaScriptCallDispatchHandleRegister, MachineType::Int32()));
#endif
  // Add context.
  locations.AddParam(regloc(kContextRegister, MachineType::AnyTagged()));
  // The target for JS function calls is the JSFunction object.
  MachineType target_type = MachineType::AnyTagged();
  // When entering into an OSR function from unoptimized code the JSFunction
  // is not in a register, but it is on the stack in the marker spill slot.
  // For kind == JSDescKind::kBuiltin, we should still use the regular
  // kJSFunctionRegister, so that frame attribution for stack traces works.
  LinkageLocation target_loc = is_osr
                                   ? LinkageLocation::ForSavedCallerFunction()
                                   : regloc(kJSFunctionRegister, target_type);
  CallDescriptor::Kind descriptor_kind = CallDescriptor::kCallJSFunction;
  return zone->New<CallDescriptor>(// --
      descriptor_kind, // kind
      kJSEntrypointTag, // tag
      target_type, // target MachineType
      target_loc, // target location
      locations.Get(), // location_sig
      js_parameter_count, // stack_parameter_count
      properties, // properties
      kNoCalleeSaved, // callee-saved
      kNoCalleeSavedFp, // callee-saved fp
      flags, // flags
      "js-call"); // debug name
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::MachineType::AnyTagged(), DCHECK_EQ, v8::internal::flags, v8::internal::LinkageLocation::ForCallerFrameSlot(), v8::internal::LinkageLocation::ForSavedCallerFunction(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::CallDescriptor::kCallJSFunction, v8::internal::kContextRegister, v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJavaScriptCallDispatchHandleRegister, v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::kJSBuiltinBaseParameterCount, v8::internal::kJSEntrypointTag, v8::internal::kJSFunctionRegister, v8::internal::compiler::kNoCalleeSaved, v8::internal::compiler::kNoCalleeSavedFp, v8::internal::kReturnRegister0, v8::internal::Zone::New(), v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc(), and V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerJS(), ComputeIncoming(), v8::internal::compiler::Pipeline::NewJSLinkageCodeStubBuiltinCompilationJob(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::compiler::JSTypedLowering::ReduceJSCall().
GetJSCallNewTargetParamIndex()
static constexpr int v8::internal::compiler::Linkage::GetJSCallNewTargetParamIndex (int parameter_count) [inline], [static], [constexpr]
Definition at line 485 of file linkage.h.
                                                                         {
    return parameter_count + 0;
  }
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::compiler::StartNode::NewTargetOutputIndex(), v8::internal::compiler::StartNode::NewTargetParameterIndex(), v8::internal::compiler::StartNode::OutputArityForFormalParameterCount(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph().
GetOsrValueLocation()
LinkageLocation v8::internal::compiler::Linkage::GetOsrValueLocation (int index) const
Definition at line 733 of file linkage.cc.
                                                            {
  CHECK(incoming_->IsJSFunctionCall());
  int parameter_count_with_receiver =
      static_cast<int>(incoming_->JSParameterCount());
  int first_stack_slot =
      OsrHelper::FirstStackSlotIndex(parameter_count_with_receiver - 1);
  if (index == kOsrContextSpillSlotIndex) {
    int context_index =
        Linkage::GetJSCallContextParamIndex(parameter_count_with_receiver);
    return GetParameterLocation(context_index);
  } else if (index >= first_stack_slot) {
    // Local variable stored in this (callee) stack.
    int spill_index =
        index - first_stack_slot + StandardFrameConstants::kFixedSlotCount;
    return LinkageLocation::ForCalleeFrameSlot(spill_index,
                                               MachineType::AnyTagged());
  } else {
    // Parameter. Use the assigned location from the incoming call descriptor.
    return GetParameterLocation(index);
  }
}
References v8::internal::MachineType::AnyTagged(), CHECK, v8::internal::compiler::OsrHelper::FirstStackSlotIndex(), v8::internal::LinkageLocation::ForCalleeFrameSlot(), GetJSCallContextParamIndex(), GetParameterLocation(), incoming_, v8::internal::index, v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), v8::internal::compiler::CallDescriptor::JSParameterCount(), v8::internal::StandardFrameConstants::kFixedSlotCount, and kOsrContextSpillSlotIndex.
GetParameterLocation()
LinkageLocation v8::internal::compiler::Linkage::GetParameterLocation (int index) const [inline]
Definition at line 452 of file linkage.h.
                                                        {
    return incoming_->GetInputLocation(index + 1); // + 1 to skip target.
  }
References v8::internal::index.
Referenced by GetOsrValueLocation(), GetParameterSecondaryLocation(), and ParameterHasSecondaryLocation().
GetParameterSecondaryLocation()
LinkageLocation v8::internal::compiler::Linkage::GetParameterSecondaryLocation (int index) const
Definition at line 780 of file linkage.cc.
                                                                      {
  // TODO(titzer): these constants are necessary due to offset/slot# mismatch
  static const int kJSContextSlot = 2 + StandardFrameConstants::kCPSlotCount;
  static const int kJSFunctionSlot = 3 + StandardFrameConstants::kCPSlotCount;
  DCHECK(ParameterHasSecondaryLocation(index));
  LinkageLocation loc = GetParameterLocation(index);
  // TODO(titzer): this should be configurable, not call-type specific.
  if (incoming_->IsJSFunctionCall()) {
    if (IsTaggedReg(loc, kJSFunctionRegister)) {
      return LinkageLocation::ForCalleeFrameSlot(kJSFunctionSlot,
                                                 MachineType::AnyTagged());
    } else {
      DCHECK(IsTaggedReg(loc, kContextRegister));
      return LinkageLocation::ForCalleeFrameSlot(kJSContextSlot,
                                                 MachineType::AnyTagged());
    }
  }
#if V8_ENABLE_WEBASSEMBLY
  static const int kWasmInstanceDataSlot =
      3 + StandardFrameConstants::kCPSlotCount;
  if (incoming_->IsAnyWasmFunctionCall()) {
    DCHECK(IsTaggedReg(loc, kWasmImplicitArgRegister));
    return LinkageLocation::ForCalleeFrameSlot(kWasmInstanceDataSlot,
                                               MachineType::AnyTagged());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  UNREACHABLE();
}
References v8::internal::MachineType::AnyTagged(), v8::internal::DCHECK(), v8::internal::LinkageLocation::ForCalleeFrameSlot(), GetParameterLocation(), incoming_, v8::internal::index, v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), v8::internal::compiler::anonymous_namespace{linkage.cc}::IsTaggedReg(), v8::internal::kContextRegister, v8::internal::CommonFrameConstants::kCPSlotCount, v8::internal::kJSFunctionRegister, v8::internal::kWasmImplicitArgRegister, v8::internal::loc, ParameterHasSecondaryLocation(), and v8::internal::UNREACHABLE().
GetParameterType()
MachineType v8::internal::compiler::Linkage::GetParameterType (int index) const [inline]
Definition at line 457 of file linkage.h.
                                                {
    return incoming_->GetInputType(index + 1); // + 1 to skip target.
  }
References v8::internal::index.
Referenced by v8::internal::compiler::InstructionSelector::VisitNode().
GetReturnLocation()
LinkageLocation v8::internal::compiler::Linkage::GetReturnLocation (size_t index = 0) const [inline]
Definition at line 462 of file linkage.h.
                                                            {
    return incoming_->GetReturnLocation(index);
  }
References v8::internal::index.
Referenced by v8::internal::compiler::InstructionSelector::VisitReturn().
GetReturnType()
MachineType v8::internal::compiler::Linkage::GetReturnType (size_t index = 0) const [inline]
Definition at line 467 of file linkage.h.
                                                    {
    return incoming_->GetReturnType(index);
  }
References v8::internal::index.
GetRuntimeCallDescriptor()
CallDescriptor * v8::internal::compiler::Linkage::GetRuntimeCallDescriptor (Zone * zone, Runtime::FunctionId function, int js_parameter_count, Operator::Properties properties, CallDescriptor::Flags flags, LazyDeoptOnThrow lazy_deopt_on_throw = LazyDeoptOnThrow::kNo) [static]
Definition at line 426 of file linkage.cc.
                                          {
  const Runtime::Function* function = Runtime::FunctionForId(function_id);
  const int return_count = function->result_size;
  const char* debug_name = function->name;
  if (lazy_deopt_on_throw == LazyDeoptOnThrow::kNo &&
      !Linkage::NeedsFrameStateInput(function_id)) {
    flags = static_cast<CallDescriptor::Flags>(
        flags & ~CallDescriptor::kNeedsFrameState);
  }
  DCHECK_IMPLIES(lazy_deopt_on_throw == LazyDeoptOnThrow::kYes,
                 flags & CallDescriptor::kNeedsFrameState);
  CallDescriptor* descriptor = GetCEntryStubCallDescriptor(
      zone, return_count, js_parameter_count, debug_name, properties, flags);
  descriptor->runtime_function_id_ = function_id;
  return descriptor;
}
References DCHECK_IMPLIES, v8::internal::flags, v8::internal::Runtime::FunctionForId(), GetCEntryStubCallDescriptor(), v8::internal::compiler::CallDescriptor::kNeedsFrameState, v8::internal::compiler::kNo, v8::internal::compiler::kYes, NeedsFrameStateInput(), and v8::internal::compiler::CallDescriptor::runtime_function_id_.
Referenced by v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), v8::internal::compiler::turboshaft::RuntimeCallDescriptor::Descriptor< Derived >::Create(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException(), and v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl().
GetSimplifiedCDescriptor()
CallDescriptor * v8::internal::compiler::Linkage::GetSimplifiedCDescriptor (Zone * zone, const MachineSignature * sig, CallDescriptor::Flags flags = CallDescriptor::kNoFlags, Operator::Properties properties = Operator::kNoThrow) [static]
Definition at line 261 of file c-linkage.cc.
                                   {
#ifdef UNSUPPORTED_C_LINKAGE
  // This method should not be called on unknown architectures.
  FATAL("requested C call descriptor on unsupported architecture");
  return nullptr;
#endif
  DCHECK(properties == Operator::kNoThrow || properties == Operator::kPure);
  DCHECK_LE(msig->parameter_count(), static_cast<size_t>(kMaxCParameters));
  LocationSignature::Builder locations(zone, msig->return_count(),
                                       msig->parameter_count());
#ifndef V8_ENABLE_FP_PARAMS_IN_C_LINKAGE
  // Check the types of the signature.
  for (size_t i = 0; i < msig->parameter_count(); i++) {
    MachineType type = msig->GetParam(i);
    CHECK(!IsFloatingPoint(type.representation()));
  }
  // Check the return types.
  for (size_t i = 0; i < locations.return_count_; i++) {
    MachineType type = msig->GetReturn(i);
    CHECK(!IsFloatingPoint(type.representation()));
  }
#endif
  CHECK_GE(2, locations.return_count_);
  if (locations.return_count_ > 0) {
#ifdef FP_RETURN_REGISTER
    const v8::internal::DoubleRegister kFPReturnRegister = FP_RETURN_REGISTER;
    auto reg = IsFloatingPoint(msig->GetReturn(0).representation())
                   ? kFPReturnRegister.code()
                   : kReturnRegister0.code();
#else
    auto reg = kReturnRegister0.code();
#endif
    // TODO(chromium:1052746): Use the correctly sized register here (e.g. "al"
    // if the return type is kBit), so we don't have to use a hacky bitwise AND
    // elsewhere.
    locations.AddReturn(LinkageLocation::ForRegister(reg, msig->GetReturn(0)));
  }
  if (locations.return_count_ > 1) {
    DCHECK(!IsFloatingPoint(msig->GetReturn(0).representation()));
    locations.AddReturn(LinkageLocation::ForRegister(kReturnRegister1.code(),
                                                     msig->GetReturn(1)));
  }
#ifdef PARAM_REGISTERS
  const v8::internal::Register kParamRegisters[] = {PARAM_REGISTERS};
  const int kParamRegisterCount = static_cast<int>(arraysize(kParamRegisters));
#else
  const v8::internal::Register* kParamRegisters = nullptr;
  const int kParamRegisterCount = 0;
#endif
#ifdef FP_PARAM_REGISTERS
  const DoubleRegister kFPParamRegisters[] = {FP_PARAM_REGISTERS};
  const size_t kFPParamRegisterCount = arraysize(kFPParamRegisters);
#else
  const DoubleRegister* kFPParamRegisters = nullptr;
  const size_t kFPParamRegisterCount = 0;
#endif
  // Add register and/or stack parameter(s).
  BuildParameterLocations(msig, kFPParamRegisterCount, kParamRegisterCount,
                          kFPParamRegisters, kParamRegisters, &locations);
  const RegList kCalleeSaveRegisters = {CALLEE_SAVE_REGISTERS};
  const DoubleRegList kCalleeSaveFPRegisters = {CALLEE_SAVE_FP_REGISTERS};
  // The target for C calls is always an address (i.e. machine pointer).
  MachineType target_type = MachineType::Pointer();
  LinkageLocation target_loc = LinkageLocation::ForAnyRegister(target_type);
  flags |= CallDescriptor::kNoAllocate;
  // TODO(saelo): here we probably want to use a c-call specific tag.
  return zone->New<CallDescriptor>(// --
      CallDescriptor::kCallAddress, // kind
      kDefaultCodeEntrypointTag, // tag
      target_type, // target MachineType
      target_loc, // target location
      locations.Get(), // location_sig
      0, // stack_parameter_count
      properties, // properties
      kCalleeSaveRegisters, // callee-saved registers
      kCalleeSaveFPRegisters, // callee-saved fp regs
      flags, "c-call");
}
References v8::internal::SignatureBuilder< SigT, T >::AddReturn(), arraysize, v8::internal::compiler::BuildParameterLocations(), CHECK, CHECK_GE, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), DCHECK_LE, FATAL, v8::internal::flags, v8::internal::LinkageLocation::ForAnyRegister(), v8::internal::LinkageLocation::ForRegister(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::internal::IsFloatingPoint(), v8::internal::compiler::CallDescriptor::kCallAddress, v8::internal::kDefaultCodeEntrypointTag, v8::internal::kMaxCParameters, v8::internal::compiler::CallDescriptor::kNoAllocate, v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Operator::kPure, v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, v8::internal::Zone::New(), v8::internal::Signature< T >::parameter_count(), v8::internal::MachineType::Pointer(), v8::internal::Signature< T >::return_count(), v8::internal::SignatureBuilder< SigT, T >::return_count_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildCCall(), v8::internal::wasm::WasmGraphBuilderBase::CallC(), v8::internal::compiler::anonymous_namespace{raw-machine-assembler.cc}::CallCFunctionImpl(), v8::internal::compiler::CodeAssembler::CallCFunctionN(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::ConvertJSPrimitiveToUntaggedOrDeopt(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::compiler::RepresentationChanger::Ieee754Fp16RawBitsToFp32RawBitsOperator(), v8::internal::compiler::RepresentationChanger::Ieee754Fp64ToFp16RawBitsOperator(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
GetStubCallContextParamIndex()
static int v8::internal::compiler::Linkage::GetStubCallContextParamIndex (int parameter_count) [inline], [static]
Definition at line 480 of file linkage.h.
                                                               {
    return parameter_count + 0;
  }
GetStubCallDescriptor()
CallDescriptor * v8::internal::compiler::Linkage::GetStubCallDescriptor (Zone * zone, const CallInterfaceDescriptor & descriptor, int stack_parameter_count, CallDescriptor::Flags flags, Operator::Properties properties = Operator::kNoProperties, StubCallMode stub_mode = StubCallMode::kCallCodeObject) [static]
Definition at line 589 of file linkage.cc.
                                                           {
  const int register_parameter_count = descriptor.GetRegisterParameterCount();
  const int js_parameter_count =
      register_parameter_count + stack_parameter_count;
  const int context_count = descriptor.HasContextParameter() ? 1 : 0;
  const size_t parameter_count =
      static_cast<size_t>(js_parameter_count + context_count);
  DCHECK_GE(stack_parameter_count, descriptor.GetStackParameterCount());
  int return_count = descriptor.GetReturnCount();
  LocationSignature::Builder locations(zone, return_count, parameter_count);
  // Add returns.
  for (int i = 0; i < return_count; i++) {
    MachineType type = descriptor.GetReturnType(static_cast<int>(i));
    if (IsFloatingPoint(type.representation())) {
      DoubleRegister reg = descriptor.GetDoubleRegisterReturn(i);
      locations.AddReturn(regloc(reg, type));
    } else {
      Register reg = descriptor.GetRegisterReturn(i);
      locations.AddReturn(regloc(reg, type));
    }
  }
  // Add parameters in registers and on the stack.
  for (int i = 0; i < js_parameter_count; i++) {
    if (i < register_parameter_count) {
      // The first parameters go in registers.
      MachineType type = descriptor.GetParameterType(i);
      if (IsFloatingPoint(type.representation())) {
        DoubleRegister reg = descriptor.GetDoubleRegisterParameter(i);
        locations.AddParam(regloc(reg, type));
      } else {
        Register reg = descriptor.GetRegisterParameter(i);
        locations.AddParam(regloc(reg, type));
      }
    } else {
      // The rest of the parameters go on the stack.
      int stack_slot = i - register_parameter_count - stack_parameter_count;
      locations.AddParam(LinkageLocation::ForCallerFrameSlot(
          stack_slot, i < descriptor.GetParameterCount()
                          ? descriptor.GetParameterType(i)
                          : MachineType::AnyTagged()));
    }
  }
  // Add context.
  if (context_count) {
    locations.AddParam(regloc(kContextRegister, MachineType::AnyTagged()));
  }
  // The target for stub calls depends on the requested mode.
  CallDescriptor::Kind kind;
  MachineType target_type;
  switch (stub_mode) {
    case StubCallMode::kCallCodeObject:
      kind = CallDescriptor::kCallCodeObject;
      target_type = MachineType::AnyTagged();
      break;
#if V8_ENABLE_WEBASSEMBLY
    case StubCallMode::kCallWasmRuntimeStub:
      kind = CallDescriptor::kCallWasmFunction;
      target_type = MachineType::Pointer();
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    case StubCallMode::kCallBuiltinPointer:
      kind = CallDescriptor::kCallBuiltinPointer;
      target_type = MachineType::AnyTagged();
      break;
  }
  RegList allocatable_registers = descriptor.allocatable_registers();
  RegList callee_saved_registers = kNoCalleeSaved;
  if (descriptor.CalleeSaveRegisters()) {
    callee_saved_registers = allocatable_registers;
    DCHECK(!callee_saved_registers.is_empty());
  }
  LinkageLocation target_loc = LinkageLocation::ForAnyRegister(target_type);
  return zone->New<CallDescriptor>(// --
      kind, // kind
      descriptor.tag(), // tag
      target_type, // target MachineType
      target_loc, // target location
      locations.Get(), // location_sig
      stack_parameter_count, // stack_parameter_count
      properties, // properties
      callee_saved_registers, // callee-saved registers
      kNoCalleeSavedFp, // callee-saved fp
      CallDescriptor::kCanUseRoots | flags, // flags
      descriptor.DebugName(), // debug name
      descriptor.GetStackArgumentOrder(), // stack order
      allocatable_registers);
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::CallInterfaceDescriptor::allocatable_registers(), v8::internal::MachineType::AnyTagged(), v8::internal::CallInterfaceDescriptor::CalleeSaveRegisters(), v8::internal::DCHECK(), DCHECK_GE, v8::internal::CallInterfaceDescriptor::DebugName(), v8::internal::flags, v8::internal::LinkageLocation::ForAnyRegister(), v8::internal::LinkageLocation::ForCallerFrameSlot(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::CallInterfaceDescriptor::GetDoubleRegisterParameter(), v8::internal::CallInterfaceDescriptor::GetDoubleRegisterReturn(), v8::internal::CallInterfaceDescriptor::GetParameterCount(), v8::internal::CallInterfaceDescriptor::GetParameterType(), v8::internal::CallInterfaceDescriptor::GetRegisterParameter(), v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::CallInterfaceDescriptor::GetRegisterReturn(), v8::internal::CallInterfaceDescriptor::GetReturnCount(), v8::internal::CallInterfaceDescriptor::GetReturnType(), v8::internal::CallInterfaceDescriptor::GetStackArgumentOrder(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::CallInterfaceDescriptor::HasContextParameter(), v8::internal::RegListBase< RegisterT >::is_empty(), v8::internal::IsFloatingPoint(), v8::internal::kCallBuiltinPointer, v8::internal::compiler::CallDescriptor::kCallBuiltinPointer, v8::internal::kCallCodeObject, v8::internal::compiler::CallDescriptor::kCallCodeObject, v8::internal::compiler::CallDescriptor::kCanUseRoots, v8::internal::kContextRegister, v8::internal::compiler::kNoCalleeSaved, v8::internal::compiler::kNoCalleeSavedFp, v8::internal::Zone::New(), v8::internal::MachineType::Pointer(), v8::internal::compiler::anonymous_namespace{linkage.cc}::regloc(), v8::internal::CallInterfaceDescriptor::tag(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerCS(), v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallBuiltin(), v8::internal::wasm::WasmWrapperTSGraphBuilder::CallBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::CodeAssembler::CallStubN(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived >::Create(), v8::internal::compiler::turboshaft::CreateAllocateBuiltinDescriptor(), v8::internal::compiler::MemoryLowering::EnsureAllocateOperator(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor(), v8::internal::compiler::GetBuiltinCallDescriptor(), v8::internal::compiler::Pipeline::NewBytecodeHandlerCompilationJob(), v8::internal::compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::CodeAssembler::TailCallJSCode(), v8::internal::compiler::CodeAssembler::TailCallStubImpl(), v8::internal::compiler::CodeAssembler::TailCallStubThenBytecodeDispatchImpl(), v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntOperator(), v8::internal::compiler::SimplifiedLowering::ToNumberOperator(), v8::internal::compiler::SimplifiedLowering::ToNumericOperator(), and v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::WasmStackCheck().
NeedsFrameStateInput()
bool v8::internal::compiler::Linkage::NeedsFrameStateInput (Runtime::FunctionId function) [static]
Definition at line 385 of file linkage.cc.
                                                             {
  switch (function) {
    // Most runtime functions need a FrameState. A few chosen ones that we know
    // not to call into arbitrary JavaScript, not to throw, and not to lazily
    // deoptimize are allowlisted here and can be called without a FrameState.
    case Runtime::kAbort:
    case Runtime::kAllocateInOldGeneration:
    case Runtime::kCreateIterResultObject:
    case Runtime::kGrowableSharedArrayBufferByteLength:
    case Runtime::kIncBlockCounter:
    case Runtime::kNewClosure:
    case Runtime::kNewClosure_Tenured:
    case Runtime::kNewFunctionContext:
    case Runtime::kPushBlockContext:
    case Runtime::kPushCatchContext:
    case Runtime::kStringEqual:
    case Runtime::kStringLessThan:
    case Runtime::kStringLessThanOrEqual:
    case Runtime::kStringGreaterThan:
    case Runtime::kStringGreaterThanOrEqual:
    case Runtime::kToFastProperties: // TODO(conradw): Is it safe?
    case Runtime::kTraceEnter:
    case Runtime::kTraceExit:
      return false;
    // Some inline intrinsics are also safe to call without a FrameState.
    case Runtime::kInlineCreateIterResultObject:
    case Runtime::kInlineIncBlockCounter:
    case Runtime::kInlineGeneratorClose:
    case Runtime::kInlineGeneratorGetResumeMode:
    case Runtime::kInlineCreateJSGeneratorObject:
      return false;
    default:
      break;
  }
  // For safety, default to needing a FrameState unless allowlisted.
  return true;
}
Referenced by GetRuntimeCallDescriptor(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), and v8::internal::compiler::JSIntrinsicLowering::ReduceIncBlockCounter().
operator=()
Linkage& v8::internal::compiler::Linkage::operator= (const Linkage &) [delete]
ParameterHasSecondaryLocation()
bool v8::internal::compiler::Linkage::ParameterHasSecondaryLocation (int index) const
Definition at line 764 of file linkage.cc.
                                                           {
  // TODO(titzer): this should be configurable, not call-type specific.
  if (incoming_->IsJSFunctionCall()) {
    LinkageLocation loc = GetParameterLocation(index);
    return IsTaggedReg(loc, kJSFunctionRegister) ||
           IsTaggedReg(loc, kContextRegister);
  }
#if V8_ENABLE_WEBASSEMBLY
  if (incoming_->IsAnyWasmFunctionCall()) {
    LinkageLocation loc = GetParameterLocation(index);
    return IsTaggedReg(loc, kWasmImplicitArgRegister);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return false;
}
References GetParameterLocation(), incoming_, v8::internal::index, v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), v8::internal::compiler::anonymous_namespace{linkage.cc}::IsTaggedReg(), v8::internal::kContextRegister, v8::internal::kJSFunctionRegister, v8::internal::kWasmImplicitArgRegister, and v8::internal::loc.
Referenced by GetParameterSecondaryLocation(), and v8::internal::compiler::InstructionSelector::VisitParameter().
Member Data Documentation
incoming_
CallDescriptor* const v8::internal::compiler::Linkage::incoming_ [private]
Definition at line 522 of file linkage.h.
Referenced by GetOsrValueLocation(), GetParameterSecondaryLocation(), and ParameterHasSecondaryLocation().
kJSCallClosureParamIndex
constexpr int v8::internal::compiler::Linkage::kJSCallClosureParamIndex = kJSCallClosureParameterIndex [static], [constexpr]
Definition at line 512 of file linkage.h.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildJSToWasmWrapper(), v8::internal::compiler::BytecodeGraphBuilder::GetFunctionClosure(), v8::internal::compiler::StartNode::OutputArityForFormalParameterCount(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::RawMachineAssembler::RawMachineAssembler(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), and v8::internal::compiler::WasmGraphBuilder::Start().
kOsrAccumulatorRegisterIndex
const int v8::internal::compiler::Linkage::kOsrAccumulatorRegisterIndex = -1 [static]
Definition at line 519 of file linkage.h.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
kOsrContextSpillSlotIndex
const int v8::internal::compiler::Linkage::kOsrContextSpillSlotIndex = -1 [static]
Definition at line 516 of file linkage.h.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::Environment::FillWithOsrValues(), GetOsrValueLocation(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/linkage.h
/mnt/V8SourceCode/src/compiler/c-linkage.cc
/mnt/V8SourceCode/src/compiler/linkage.cc