v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT > Class Template Reference
Public Member Functions
void RecordFirstOccurrence (Tagged< String > s, const SinkCharT *position)
bool TryApply (Tagged< String > s, SinkCharT **current_position)
bool enabled () const
Private Attributes
bool enabled_ = false
std::unordered_map< Address, const SinkCharT * > first_occurrence_
Detailed Description
template<typename SinkCharT>
class v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >
Definition at line 958 of file string.cc.
Member Function Documentation
enabled()
template<typename SinkCharT >
bool v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::enabled () const [inline]
Definition at line 987 of file string.cc.
{ return enabled_; }
Referenced by v8::internal::anonymous_namespace{string.cc}::WriteToFlat2Impl().
RecordFirstOccurrence()
template<typename SinkCharT >
void v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::RecordFirstOccurrence (Tagged< String > s, const SinkCharT * position) [inline]
Definition at line 960 of file string.cc.
                                                                  {
    enabled_ = true;
    auto it = first_occurrence_.find(s.ptr());
    if (it == first_occurrence_.end()) {
      first_occurrence_.insert({s.ptr(), position});
    }
  }
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::anonymous_namespace{string.cc}::WriteToFlat2Impl().
TryApply()
template<typename SinkCharT >
bool v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::TryApply (Tagged< String > s, SinkCharT ** current_position) [inline]
Definition at line 969 of file string.cc.
                                                                          {
    if (V8_UNLIKELY(enabled_)) {
      auto it = first_occurrence_.find(s.ptr());
      if (it != first_occurrence_.end()) {
        const SinkCharT* previous_position = it->second;
        if (*current_position != previous_position) {
          uint32_t length = s->length();
          DCHECK_LE(*current_position, previous_position - length);
          previous_position -= length;
          (*current_position) -= length;
          CopyChars(*current_position, previous_position, length);
          return true;
        }
      }
    }
    return false;
  }
References v8::internal::CopyChars(), DCHECK_LE, v8::internal::length, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{string.cc}::WriteToFlat2Impl().
Member Data Documentation
enabled_
template<typename SinkCharT >
bool v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::enabled_ = false [private]
Definition at line 991 of file string.cc.
first_occurrence_
template<typename SinkCharT >
std::unordered_map<Address, const SinkCharT*> v8::internal::anonymous_namespace{string.cc}::WriteToFlat_RepeatOptimizer< SinkCharT >::first_occurrence_ [private]
Definition at line 993 of file string.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string.cc