v8::internal::CodeEventLogger Class Reference
#include <log.h>
Classes
class NameBuffer
Public Member Functions
CodeEventLogger (Isolate *isolate)
~CodeEventLogger () override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char *name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) override
void RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) override
void CallbackEvent (DirectHandle< Name > name, Address entry_point) override
void GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SharedFunctionInfoMoveEvent (Address from, Address to) override
void NativeContextMoveEvent (Address from, Address to) override
void CodeMovingGCEvent () override
void CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) override
void CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char *reason) override
void WeakCodeClearEvent () override
bool is_listening_to_code_events () override
Protected Attributes
Isolate * isolate_
Private Member Functions
virtual void LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > maybe_shared, const char *name, size_t length)=0
Private Attributes
std::unique_ptr< NameBuffer > name_buffer_
Additional Inherited Members
Detailed Description
Definition at line 427 of file log.h.
Constructor & Destructor Documentation
CodeEventLogger()
v8::internal::CodeEventLogger::CodeEventLogger (Isolate * isolate) [explicit]
Definition at line 245 of file log.cc.
    : isolate_(isolate), name_buffer_(std::make_unique<NameBuffer>()) {}
 CodeEventLogger()
v8::internal::CodeEventLogger::~CodeEventLogger () [override], [default]
Member Function Documentation
CallbackEvent()
void v8::internal::CodeEventLogger::CallbackEvent (DirectHandle< Name > name, Address entry_point) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 452 of file log.h.
{}
CodeCreateEvent() [1/4]
void v8::internal::CodeEventLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char * name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 250 of file log.cc.
                                                           {
  DCHECK(is_listening_to_code_events());
  name_buffer_->Init(tag);
  name_buffer_->AppendBytes(comment);
  DisallowGarbageCollection no_gc;
  LogRecordedBuffer(*code, MaybeDirectHandle<SharedFunctionInfo>(),
                    name_buffer_->get(), name_buffer_->size());
}
References code, v8::internal::DCHECK(), is_listening_to_code_events(), LogRecordedBuffer(), name_buffer_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CodeCreateEvent() [2/4]
void v8::internal::CodeEventLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 261 of file log.cc.
                                                               {
  DCHECK(is_listening_to_code_events());
  name_buffer_->Init(tag);
  name_buffer_->AppendName(*name);
  DisallowGarbageCollection no_gc;
  LogRecordedBuffer(*code, MaybeDirectHandle<SharedFunctionInfo>(),
                    name_buffer_->get(), name_buffer_->size());
}
References code, v8::internal::DCHECK(), is_listening_to_code_events(), LogRecordedBuffer(), v8::internal::name, name_buffer_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CodeCreateEvent() [3/4]
void v8::internal::CodeEventLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 272 of file log.cc.
                                                                      {
  DCHECK(is_listening_to_code_events());
  name_buffer_->Init(tag);
  name_buffer_->AppendBytes(ComputeMarker(*shared, *code));
  name_buffer_->AppendByte(' ');
  name_buffer_->AppendName(*script_name);
  DisallowGarbageCollection no_gc;
  LogRecordedBuffer(*code, shared, name_buffer_->get(), name_buffer_->size());
}
References code, v8::internal::anonymous_namespace{log.cc}::ComputeMarker(), v8::internal::DCHECK(), is_listening_to_code_events(), LogRecordedBuffer(), name_buffer_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CodeCreateEvent() [4/4]
void v8::internal::CodeEventLogger::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 285 of file log.cc.
                                                  {
  DCHECK(is_listening_to_code_events());
  name_buffer_->Init(tag);
  name_buffer_->AppendBytes(ComputeMarker(*shared, *code));
  name_buffer_->AppendBytes(shared->DebugNameCStr().get());
  name_buffer_->AppendByte(' ');
  if (IsString(*script_name)) {
    name_buffer_->AppendString(Cast<String>(*script_name));
  } else {
    name_buffer_->AppendBytes("symbol(hash ");
    name_buffer_->AppendHex(Cast<Name>(*script_name)->hash());
    name_buffer_->AppendByte(')');
  }
  name_buffer_->AppendByte(':');
  name_buffer_->AppendInt(line);
  name_buffer_->AppendByte(':');
  name_buffer_->AppendInt(column);
  DisallowGarbageCollection no_gc;
  LogRecordedBuffer(*code, shared, name_buffer_->get(), name_buffer_->size());
}
References code, v8::internal::anonymous_namespace{log.cc}::ComputeMarker(), v8::internal::DCHECK(), is_listening_to_code_events(), LogRecordedBuffer(), name_buffer_, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
CodeDeoptEvent()
void v8::internal::CodeEventLogger::CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 460 of file log.h.
                                                   {}
CodeDependencyChangeEvent()
void v8::internal::CodeEventLogger::CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char * reason) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 462 of file log.h.
                                                              {}
CodeMovingGCEvent()
void v8::internal::CodeEventLogger::CodeMovingGCEvent () [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 459 of file log.h.
{}
GetterCallbackEvent()
void v8::internal::CodeEventLogger::GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 453 of file log.h.
                                                         {}
is_listening_to_code_events()
bool v8::internal::CodeEventLogger::is_listening_to_code_events () [inline], [override], [virtual]
Reimplemented from v8::internal::LogEventListener.
Definition at line 467 of file log.h.
{ return true; }
Referenced by CodeCreateEvent(), and RegExpCodeCreateEvent().
LogRecordedBuffer()
virtual void v8::internal::CodeEventLogger::LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > maybe_shared, const char * name, size_t length) [private], [pure virtual]
Implemented in v8::internal::CodeAddressMap, v8::internal::JitLogger, and v8::internal::LowLevelLogger.
Referenced by CodeCreateEvent(), and RegExpCodeCreateEvent().
NativeContextMoveEvent()
void v8::internal::CodeEventLogger::NativeContextMoveEvent (Address from, Address to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 458 of file log.h.
{}
RegExpCodeCreateEvent()
void v8::internal::CodeEventLogger::RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 332 of file log.cc.
                                                               {
  DCHECK(is_listening_to_code_events());
  // Note we don't call Init due to the required pprof demangling hack for
  // regexp patterns.
  name_buffer_->Reset();
  // https://github.com/google/pprof/blob/4cf4322d492d108a9d6526d10844e04792982cbb/internal/symbolizer/symbolizer.go#L312.
  name_buffer_->AppendBytes("RegExp.>");
  name_buffer_->AppendBytes(" src: '");
  name_buffer_->AppendString(*source);
  name_buffer_->AppendBytes("' flags: '");
  DirectHandle<String> flags_str =
      JSRegExp::StringFromFlags(isolate_, JSRegExp::AsJSRegExpFlags(flags));
  name_buffer_->AppendString(*flags_str);
  name_buffer_->AppendBytes("'");
  DisallowGarbageCollection no_gc;
  LogRecordedBuffer(*code, MaybeDirectHandle<SharedFunctionInfo>(),
                    name_buffer_->get(), name_buffer_->size());
}
References v8::internal::JSRegExp::AsJSRegExpFlags(), code, v8::internal::DCHECK(), v8::internal::flags, is_listening_to_code_events(), isolate_, LogRecordedBuffer(), name_buffer_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::JSRegExp::StringFromFlags().
SetterCallbackEvent()
void v8::internal::CodeEventLogger::SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 455 of file log.h.
                                                         {}
SharedFunctionInfoMoveEvent()
void v8::internal::CodeEventLogger::SharedFunctionInfoMoveEvent (Address from, Address to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 457 of file log.h.
{}
WeakCodeClearEvent()
void v8::internal::CodeEventLogger::WeakCodeClearEvent () [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 465 of file log.h.
{}
Member Data Documentation
isolate_
Isolate* v8::internal::CodeEventLogger::isolate_ [protected]
Definition at line 470 of file log.h.
Referenced by v8::internal::JitLogger::AddCodeLinePosInfoEvent(), v8::internal::JitLogger::BytecodeMoveEvent(), v8::internal::JitLogger::CodeMoveEvent(), v8::internal::JitLogger::EndCodePosInfoEvent(), v8::internal::LowLevelLogger::LogRecordedBuffer(), v8::internal::JitLogger::LogRecordedBuffer(), RegExpCodeCreateEvent(), v8::internal::JitLogger::StartCodePosInfoEvent(), and v8::internal::CodeAddressMap::~CodeAddressMap().
name_buffer_
std::unique_ptr<NameBuffer> v8::internal::CodeEventLogger::name_buffer_ [private]
Definition at line 484 of file log.h.
Referenced by CodeCreateEvent(), and RegExpCodeCreateEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log.h
/mnt/V8SourceCode/src/logging/log.cc