v8::internal::TickCounter Class Reference
#include <tick-counter.h>
Public Member Functions
void TickAndMaybeEnterSafepoint ()
void AttachLocalHeap (LocalHeap *local_heap)
void DetachLocalHeap ()
size_t CurrentTicks () const
Private Attributes
size_t ticks_ = 0
LocalHeap * local_heap_ = nullptr
Detailed Description
Definition at line 23 of file tick-counter.h.
Member Function Documentation
AttachLocalHeap()
void v8::internal::TickCounter::AttachLocalHeap (LocalHeap * local_heap)
Definition at line 14 of file tick-counter.cc.
                                                       {
  DCHECK_NULL(local_heap_);
  local_heap_ = local_heap;
  DCHECK_NOT_NULL(local_heap_);
}
References DCHECK_NOT_NULL, DCHECK_NULL, and local_heap_.
CurrentTicks()
size_t v8::internal::TickCounter::CurrentTicks () const [inline]
Definition at line 37 of file tick-counter.h.
{ return ticks_; }
References ticks_.
DetachLocalHeap()
void v8::internal::TickCounter::DetachLocalHeap ()
Definition at line 20 of file tick-counter.cc.
{ local_heap_ = nullptr; }
References local_heap_.
TickAndMaybeEnterSafepoint()
void v8::internal::TickCounter::TickAndMaybeEnterSafepoint () [inline]
Definition at line 25 of file tick-counter.h.
                                    {
    ++ticks_;
    // Magical number to detect performance bugs or compiler divergence.
    // Selected as being roughly 10x of what's needed frequently.
    constexpr size_t kMaxTicks = 100000000;
    USE(kMaxTicks);
    DCHECK_LT(ticks_, kMaxTicks);
    if (local_heap_) local_heap_->Safepoint();
  }
References DCHECK_LT, local_heap_, v8::internal::LocalHeap::Safepoint(), ticks_, and USE.
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::OperandAssigner::CommitAssignment(), v8::internal::compiler::OperandAssigner::DecideSpillingMode(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraints(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::LoopFinderImpl::PropagateForward(), v8::internal::compiler::GraphReducer::Reduce(), v8::internal::compiler::EffectGraphReducer::ReduceFrom(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::ScheduleEarlyNodeVisitor::Run(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitBlock(), v8::internal::compiler::MemoryOptimizer::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::InstructionSelector::VisitNode().
Member Data Documentation
local_heap_
LocalHeap* v8::internal::TickCounter::local_heap_ = nullptr [private]
Definition at line 41 of file tick-counter.h.
Referenced by AttachLocalHeap(), DetachLocalHeap(), and TickAndMaybeEnterSafepoint().
ticks_
size_t v8::internal::TickCounter::ticks_ = 0 [private]
Definition at line 40 of file tick-counter.h.
Referenced by CurrentTicks(), and TickAndMaybeEnterSafepoint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/tick-counter.h
/mnt/V8SourceCode/src/codegen/tick-counter.cc