v8::internal::ThreadId Class Reference
#include <thread-id.h>
Public Member Functions
constexpr ThreadId () noexcept
bool operator== (const ThreadId &other) const
bool operator!= (const ThreadId &other) const
bool IsValid () const
constexpr int ToInteger () const
Static Public Member Functions
static ThreadId TryGetCurrent ()
static ThreadId Current ()
static constexpr ThreadId Invalid ()
static constexpr ThreadId FromInteger (int id)
Private Member Functions
constexpr ThreadId (int id) noexcept
Static Private Member Functions
static V8_EXPORT_PRIVATE int GetCurrentThreadId ()
Private Attributes
int id_
Static Private Attributes
static constexpr int kInvalidId = -1
Detailed Description
Definition at line 14 of file thread-id.h.
Constructor & Destructor Documentation
ThreadId() [1/2]
constexpr v8::internal::ThreadId::ThreadId () [inline], [constexpr], [noexcept]
Definition at line 17 of file thread-id.h.
: ThreadId(kInvalidId) {}
Referenced by Current(), FromInteger(), Invalid(), and TryGetCurrent().
ThreadId() [2/2]
constexpr v8::internal::ThreadId::ThreadId (int id) [inline], [explicit], [constexpr], [private], [noexcept]
Definition at line 44 of file thread-id.h.
: id_(id) {}
Member Function Documentation
Current()
static ThreadId v8::internal::ThreadId::Current () [inline], [static]
Definition at line 32 of file thread-id.h.
{ return ThreadId(GetCurrentThreadId()); }
References GetCurrentThreadId(), and ThreadId().
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::internal::ThreadManager::ArchiveThread(), v8::internal::LocalIsolate::AsIsolate(), v8::internal::AstStringConstants::AstStringConstants(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Check(), v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::Compile(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode(), v8::internal::anonymous_namespace{compiler.cc}::CompileToplevel(), v8::internal::ThreadManager::CurrentId(), v8::internal::Isolate::CurrentLocalHeap(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Dcheck(), v8::internal::Isolate::Deinitialize(), v8::internal::Parser::DeserializeScopeChain(), v8::internal::JSObject::DictionaryPropertyAt(), v8::internal::Isolate::Enter(), v8::internal::IsolateSafepoint::EnterLocalSafepointScope(), v8::internal::LocalHeap::ExecuteBackgroundThreadWhileParked(), v8::internal::LocalHeap::ExecuteWithStackMarker(), v8::internal::Isolate::Exit(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FailAssert(), v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode(), v8::internal::UnoptimizedCompilationJob::FinalizeJob(), v8::internal::OptimizedCompilationJob::FinalizeJob(), v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable(), v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread(), v8::internal::Isolate::FindPerThreadDataForThisThread(), v8::internal::FlatStringReader::FlatStringReader(), v8::internal::ExternalOneByteString::GetChars(), v8::internal::ExternalTwoByteString::GetChars(), v8::internal::wasm::WasmInterpreterThreadMap::GetCurrentInterpreterThread(), v8::internal::OptimizingCompileDispatcher::HasJobs(), v8::internal::ThreadLocalTop::Initialize(), v8::internal::LocalHeap::is_in_trampoline(), v8::internal::JSAtomicsMutex::IsCurrentThreadOwner(), v8::internal::ThreadManager::IsLockedByCurrentThread(), v8::internal::Heap::IsMainThread(), v8::internal::ThreadManager::Lock(), v8::Isolate::MemoryPressureNotification(), v8::internal::MutexGuardIfOffThread< Isolate >::MutexGuardIfOffThread(), v8::internal::OptimizedCompilationJob::PrepareJob(), v8::internal::OptimizingCompileInputQueue::Prioritize(), v8::internal::TransitionsAccessor::PutPrototypeTransition(), v8::internal::CpuProfilesCollection::RemoveProfile(), v8::internal::ThreadManager::RestoreThread(), v8::internal::BackgroundCompileTask::Run(), v8::internal::JSAtomicsMutex::SetCurrentThreadAsOwner(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), v8::internal::compiler::JSHeapBroker::StackHasOverflowed(), and v8::internal::VMStateIfMainThread< tag >::VMStateIfMainThread().
FromInteger()
static constexpr ThreadId v8::internal::ThreadId::FromInteger (int id) [inline], [static], [constexpr]
Definition at line 39 of file thread-id.h.
{ return ThreadId(id); }
References ThreadId().
GetCurrentThreadId()
int v8::internal::ThreadId::GetCurrentThreadId () [static], [private]
Definition at line 26 of file thread-id.cc.
                                 {
  if (thread_id == 0) {
    thread_id = next_thread_id.fetch_add(1);
    CHECK_LE(1, thread_id);
  }
  return thread_id;
}
References CHECK_LE, v8::internal::anonymous_namespace{thread-id.cc}::next_thread_id, and v8::internal::anonymous_namespace{thread-id.cc}::thread_id.
Referenced by Current().
Invalid()
static constexpr ThreadId v8::internal::ThreadId::Invalid () [inline], [static], [constexpr]
Definition at line 35 of file thread-id.h.
{ return ThreadId(kInvalidId); }
References kInvalidId, and ThreadId().
Referenced by v8::internal::ThreadManager::ArchiveThread(), v8::internal::JSAtomicsMutex::ClearOwnerThread(), v8::internal::ThreadManager::EagerlyArchiveThread(), v8::internal::Isolate::Exit(), v8::internal::Factory::NewJSAtomicsMutex(), v8::internal::ThreadManager::RestoreThread(), TryGetCurrent(), v8::internal::ThreadManager::Unlock(), and v8::internal::JSAtomicsMutex::UnlockSlowPath().
IsValid()
bool v8::internal::ThreadId::IsValid () const [inline]
Definition at line 23 of file thread-id.h.
{ return id_ != kInvalidId; }
References id_, and kInvalidId.
Referenced by v8::internal::Isolate::DiscardPerThreadDataForThisThread(), and v8::internal::ThreadManager::RestoreThread().
operator!=()
bool v8::internal::ThreadId::operator!= (const ThreadId & other) const [inline]
Definition at line 20 of file thread-id.h.
{ return id_ != other.id_; }
References id_.
operator==()
bool v8::internal::ThreadId::operator== (const ThreadId & other) const [inline]
Definition at line 19 of file thread-id.h.
{ return id_ == other.id_; }
References id_.
ToInteger()
constexpr int v8::internal::ThreadId::ToInteger () const [inline], [constexpr]
Definition at line 26 of file thread-id.h.
{ return id_; }
References id_.
Referenced by v8::internal::wasm::WasmInterpreterThreadMap::GetCurrentInterpreterThread(), v8::internal::JSAtomicsMutex::IsCurrentThreadOwner(), and v8::internal::Isolate::ThreadDataTable::Hasher::operator()().
TryGetCurrent()
ThreadId v8::internal::ThreadId::TryGetCurrent () [static]
Definition at line 21 of file thread-id.cc.
                                 {
  return thread_id == 0 ? Invalid() : ThreadId(thread_id);
}
References Invalid(), v8::internal::anonymous_namespace{thread-id.cc}::thread_id, and ThreadId().
Referenced by v8::internal::Isolate::DiscardPerThreadDataForThisThread().
Member Data Documentation
id_
int v8::internal::ThreadId::id_ [private]
Definition at line 48 of file thread-id.h.
Referenced by IsValid(), operator!=(), operator==(), and ToInteger().
kInvalidId
constexpr int v8::internal::ThreadId::kInvalidId = -1 [static], [constexpr], [private]
Definition at line 42 of file thread-id.h.
Referenced by Invalid(), and IsValid().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/thread-id.h
/mnt/V8SourceCode/src/execution/thread-id.cc