v8::internal::torque::Binding< T > Class Template Reference
#include <implementation-visitor.h>
Public Member Functions
template<class... Args>
Binding (BindingsManager< T > *manager, const std::string &name, Args &&... args)
template<class... Args>
Binding (BindingsManager< T > *manager, const Identifier *name, Args &&... args)
~Binding ()
Binding (const Binding &)=delete
Binding & operator= (const Binding &)=delete
std::string BindingTypeString () const
bool CheckWritten () const
const std::string & name () const
SourcePosition declaration_position () const
bool Used () const
void SetUsed ()
bool Written () const
void SetWritten ()
uint64_t unique_index () const
std::string BindingTypeString () const
bool CheckWritten () const
std::string BindingTypeString () const
bool CheckWritten () const
Private Member Functions
bool SkipLintCheck () const
Private Attributes
BindingsManager< T > * manager_
const std::string name_
std::optional< Binding * > previous_binding_
SourcePosition declaration_position_ = CurrentSourcePosition::Get()
bool used_
bool written_
uint64_t unique_index_
Detailed Description
template<class T>
class v8::internal::torque::Binding< T >
Definition at line 265 of file implementation-visitor.h.
Constructor & Destructor Documentation
Binding() [1/3]
template<class T >
template<class... Args>
v8::internal::torque::Binding< T >::Binding (BindingsManager< T > * manager, const std::string & name, Args &&... args) [inline]
Definition at line 268 of file implementation-visitor.h.
      : T(std::forward<Args>(args)...),
        manager_(manager),
        name_(name),
        previous_binding_(this),
        used_(false),
        written_(false),
        unique_index_(next_unique_binding_index++) {
    std::swap(previous_binding_, manager_->current_bindings_[name]);
  }
References v8::internal::torque::Binding< T >::manager_, v8::internal::torque::Binding< T >::name(), and v8::internal::torque::Binding< T >::previous_binding_.
Binding() [2/3]
template<class T >
template<class... Args>
v8::internal::torque::Binding< T >::Binding (BindingsManager< T > * manager, const Identifier * name, Args &&... args) [inline]
Definition at line 279 of file implementation-visitor.h.
      : Binding(manager, name->value, std::forward<Args>(args)...) {
    declaration_position_ = name->pos;
  }
References v8::internal::torque::Binding< T >::declaration_position_, and v8::internal::torque::Binding< T >::name().
 Binding()
template<class T >
v8::internal::torque::Binding< T >::~Binding () [inline]
Definition at line 283 of file implementation-visitor.h.
             {
    if (!used_ && !SkipLintCheck()) {
      Lint(BindingTypeString(), "'", name_,
           "' is never used. Prefix with '_' if this is intentional.")
          .Position(declaration_position_);
    }
    if (CheckWritten() && !written_ && !SkipLintCheck()) {
      Lint(BindingTypeString(), "'", name_,
           "' is never assigned to. Use 'const' instead of 'let'.")
          .Position(declaration_position_);
    }
    manager_->current_bindings_[name_] = previous_binding_;
  }
References v8::internal::torque::Binding< T >::BindingTypeString(), v8::internal::torque::Binding< T >::CheckWritten(), v8::internal::torque::Binding< T >::declaration_position_, v8::internal::torque::Lint(), v8::internal::torque::Binding< T >::manager_, v8::internal::torque::Binding< T >::name_, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::Binding< T >::previous_binding_, v8::internal::torque::Binding< T >::SkipLintCheck(), v8::internal::torque::Binding< T >::used_, and v8::internal::torque::Binding< T >::written_.
Binding() [3/3]
template<class T >
v8::internal::torque::Binding< T >::Binding (const Binding< T > &) [delete]
Member Function Documentation
BindingTypeString() [1/3]
template<class T >
std::string v8::internal::torque::Binding< T >::BindingTypeString () const
Referenced by v8::internal::torque::Binding< T >::~Binding().
BindingTypeString() [2/3]
std::string v8::internal::torque::Binding< LocalValue >::BindingTypeString () const [inline]
Definition at line 419 of file implementation-visitor.h.
                                                              {
  return "Variable ";
}
BindingTypeString() [3/3]
std::string v8::internal::torque::Binding< LocalLabel >::BindingTypeString () const [inline]
Definition at line 432 of file implementation-visitor.h.
                                                              {
  return "Label ";
}
CheckWritten() [1/3]
template<class T >
bool v8::internal::torque::Binding< T >::CheckWritten () const
Referenced by v8::internal::torque::Binding< T >::~Binding().
CheckWritten() [2/3]
bool v8::internal::torque::Binding< LocalValue >::CheckWritten () const [inline]
Definition at line 423 of file implementation-visitor.h.
                                                    {
  // Do the check only for non-const variables and non struct types.
  auto binding = *manager_->current_bindings_[name_];
  if (!binding->IsAccessibleNonLazy()) return false;
  const LocationReference& ref = binding->GetLocationReference(binding);
  if (!ref.IsVariableAccess()) return false;
  return !ref.GetVisitResult().type()->StructSupertype();
}
References v8::internal::torque::LocationReference::GetVisitResult(), v8::internal::torque::LocationReference::IsVariableAccess(), v8::internal::torque::Type::StructSupertype(), and v8::internal::torque::VisitResult::type().
CheckWritten() [3/3]
bool v8::internal::torque::Binding< LocalLabel >::CheckWritten () const [inline]
Definition at line 436 of file implementation-visitor.h.
                                                    {
  return false;
}
declaration_position()
template<class T >
SourcePosition v8::internal::torque::Binding< T >::declaration_position () const [inline]
Definition at line 305 of file implementation-visitor.h.
{ return declaration_position_; }
References v8::internal::torque::Binding< T >::declaration_position_.
Referenced by v8::internal::torque::KytheData::AddBindingDefinition(), v8::internal::torque::ImplementationVisitor::LabelsFromIdentifiers(), and v8::internal::torque::ImplementationVisitor::Visit().
name()
template<class T >
const std::string& v8::internal::torque::Binding< T >::name () const [inline]
Definition at line 304 of file implementation-visitor.h.
{ return name_; }
References v8::internal::torque::Binding< T >::name_.
Referenced by v8::internal::torque::KytheData::AddBindingDefinition(), v8::internal::torque::Binding< T >::Binding(), v8::internal::torque::ImplementationVisitor::GenerateCall(), and v8::internal::torque::LocalValue::GetLocationReference().
operator=()
template<class T >
Binding& v8::internal::torque::Binding< T >::operator= (const Binding< T > &) [delete]
SetUsed()
template<class T >
void v8::internal::torque::Binding< T >::SetUsed () [inline]
Definition at line 308 of file implementation-visitor.h.
{ used_ = true; }
References v8::internal::torque::Binding< T >::used_.
SetWritten()
template<class T >
void v8::internal::torque::Binding< T >::SetWritten () [inline]
Definition at line 311 of file implementation-visitor.h.
{ written_ = true; }
References v8::internal::torque::Binding< T >::written_.
SkipLintCheck()
template<class T >
bool v8::internal::torque::Binding< T >::SkipLintCheck () const [inline], [private]
Definition at line 316 of file implementation-visitor.h.
{ return name_.length() > 0 && name_[0] == '_'; }
References v8::internal::torque::Binding< T >::name_.
Referenced by v8::internal::torque::Binding< T >::~Binding().
unique_index()
template<class T >
uint64_t v8::internal::torque::Binding< T >::unique_index () const [inline]
Definition at line 313 of file implementation-visitor.h.
{ return unique_index_; }
References v8::internal::torque::Binding< T >::unique_index_.
Referenced by v8::internal::torque::KytheData::AddBindingDefinition().
Used()
template<class T >
bool v8::internal::torque::Binding< T >::Used () const [inline]
Definition at line 307 of file implementation-visitor.h.
{ return used_; }
References v8::internal::torque::Binding< T >::used_.
Written()
template<class T >
bool v8::internal::torque::Binding< T >::Written () const [inline]
Definition at line 310 of file implementation-visitor.h.
{ return written_; }
References v8::internal::torque::Binding< T >::written_.
Member Data Documentation
declaration_position_
template<class T >
SourcePosition v8::internal::torque::Binding< T >::declaration_position_ = CurrentSourcePosition::Get() [private]
Definition at line 321 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::Binding(), v8::internal::torque::Binding< T >::declaration_position(), and v8::internal::torque::Binding< T >::~Binding().
manager_
template<class T >
BindingsManager<T>* v8::internal::torque::Binding< T >::manager_ [private]
Definition at line 318 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::Binding(), and v8::internal::torque::Binding< T >::~Binding().
name_
template<class T >
const std::string v8::internal::torque::Binding< T >::name_ [private]
Definition at line 319 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::name(), v8::internal::torque::Binding< T >::SkipLintCheck(), and v8::internal::torque::Binding< T >::~Binding().
previous_binding_
template<class T >
std::optional<Binding*> v8::internal::torque::Binding< T >::previous_binding_ [private]
Definition at line 320 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::Binding(), and v8::internal::torque::Binding< T >::~Binding().
unique_index_
template<class T >
uint64_t v8::internal::torque::Binding< T >::unique_index_ [private]
Definition at line 324 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::unique_index().
used_
template<class T >
bool v8::internal::torque::Binding< T >::used_ [private]
Definition at line 322 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::SetUsed(), v8::internal::torque::Binding< T >::Used(), and v8::internal::torque::Binding< T >::~Binding().
written_
template<class T >
bool v8::internal::torque::Binding< T >::written_ [private]
Definition at line 323 of file implementation-visitor.h.
Referenced by v8::internal::torque::Binding< T >::SetWritten(), v8::internal::torque::Binding< T >::Written(), and v8::internal::torque::Binding< T >::~Binding().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.h