v8::internal::Assembler::VectorUnit Class Reference
#include <assembler-riscv.h>
Public Member Functions
int32_t sew () const
int32_t vlmax () const
VectorUnit (Assembler *assm)
void set (Register rd, VSew sew, Vlmul lmul)
void set (Register rd, int8_t sew, int8_t lmul)
void set (FPURoundingMode mode)
void set (Register rd, Register rs1, VSew sew, Vlmul lmul)
void set (VSew sew, Vlmul lmul)
void clear ()
Private Attributes
VSew sew_ = kVsInvalid
Vlmul lmul_ = kVlInvalid
int32_t vl = 0
Assembler * assm_
FPURoundingMode mode_ = RNE
Detailed Description
Definition at line 628 of file assembler-riscv.h.
Constructor & Destructor Documentation
VectorUnit()
v8::internal::Assembler::VectorUnit::VectorUnit (Assembler * assm) [inline], [explicit]
Definition at line 640 of file assembler-riscv.h.
: assm_(assm) {}
Member Function Documentation
clear()
void v8::internal::Assembler::VectorUnit::clear () [inline]
Definition at line 683 of file assembler-riscv.h.
                 {
      sew_ = kVsInvalid;
      lmul_ = kVlInvalid;
    }
References v8::internal::kVlInvalid, and v8::internal::kVsInvalid.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::Assembler::branch_long_offset(), v8::internal::Assembler::branch_offset_helper(), and v8::internal::Assembler::ClearVectorunit().
set() [1/5]
void v8::internal::Assembler::VectorUnit::set (FPURoundingMode mode) [inline]
Definition at line 659 of file assembler-riscv.h.
                                   {
      if (mode_ != mode) {
        assm_->addi(kScratchReg, zero_reg, mode << kFcsrFrmShift);
        assm_->fscsr(kScratchReg);
        mode_ = mode;
      }
    }
References v8::internal::kFcsrFrmShift, v8::internal::kScratchReg, and mode().
set() [2/5]
void v8::internal::Assembler::VectorUnit::set (Register rd, int8_t sew, int8_t lmul) [inline]
Definition at line 651 of file assembler-riscv.h.
                                                   {
      DCHECK_GE(sew, E8);
      DCHECK_LE(sew, E64);
      DCHECK_GE(lmul, m1);
      DCHECK_LE(lmul, mf2);
      set(rd, VSew(sew), Vlmul(lmul));
    }
References DCHECK_GE, and DCHECK_LE.
set() [3/5]
void v8::internal::Assembler::VectorUnit::set (Register rd, Register rs1, VSew sew, Vlmul lmul) [inline]
Definition at line 666 of file assembler-riscv.h.
                                                              {
      if (sew != sew_ || lmul != lmul_) {
        sew_ = sew;
        lmul_ = lmul;
        vl = 0;
        assm_->vsetvli(rd, rs1, sew_, lmul_);
      }
    }
set() [4/5]
void v8::internal::Assembler::VectorUnit::set (Register rd, VSew sew, Vlmul lmul) [inline]
Definition at line 642 of file assembler-riscv.h.
                                                {
      if (sew != sew_ || lmul != lmul_ || vl != vlmax()) {
        sew_ = sew;
        lmul_ = lmul;
        vl = vlmax();
        assm_->vsetvlmax(rd, sew_, lmul_);
      }
    }
Referenced by v8::internal::MacroAssembler::LoadLane(), v8::internal::MacroAssembler::RoundHelper(), v8::internal::MacroAssembler::StoreLane(), v8::internal::MacroAssembler::WasmRvvEq(), v8::internal::MacroAssembler::WasmRvvGeS(), v8::internal::MacroAssembler::WasmRvvGeU(), v8::internal::MacroAssembler::WasmRvvGtS(), v8::internal::MacroAssembler::WasmRvvGtU(), and v8::internal::MacroAssembler::WasmRvvNe().
set() [5/5]
void v8::internal::Assembler::VectorUnit::set (VSew sew, Vlmul lmul) [inline]
Definition at line 675 of file assembler-riscv.h.
                                   {
      if (sew != sew_ || lmul != lmul_) {
        sew_ = sew;
        lmul_ = lmul;
        assm_->vsetvl(sew_, lmul_);
      }
    }
sew()
int32_t v8::internal::Assembler::VectorUnit::sew () const [inline]
Definition at line 630 of file assembler-riscv.h.
{ return 2 ^ (sew_ + 3); }
vlmax()
int32_t v8::internal::Assembler::VectorUnit::vlmax () const [inline]
Definition at line 632 of file assembler-riscv.h.
                                 {
      if ((lmul_ & 0b100) != 0) {
        return (kRvvVLEN / sew()) >> (lmul_ & 0b11);
      } else {
        return ((kRvvVLEN << lmul_) / sew());
      }
    }
References v8::internal::kRvvVLEN.
Member Data Documentation
assm_
Assembler* v8::internal::Assembler::VectorUnit::assm_ [private]
Definition at line 692 of file assembler-riscv.h.
lmul_
Vlmul v8::internal::Assembler::VectorUnit::lmul_ = kVlInvalid [private]
Definition at line 690 of file assembler-riscv.h.
mode_
FPURoundingMode v8::internal::Assembler::VectorUnit::mode_ = RNE [private]
Definition at line 693 of file assembler-riscv.h.
sew_
VSew v8::internal::Assembler::VectorUnit::sew_ = kVsInvalid [private]
Definition at line 689 of file assembler-riscv.h.
vl
int32_t v8::internal::Assembler::VectorUnit::vl = 0 [private]
Definition at line 691 of file assembler-riscv.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.h