v8::internal::ApiNatives Class Reference
#include <api-natives.h>
Static Public Member Functions
static DirectHandle< FunctionTemplateInfo > CreateAccessorFunctionTemplateInfo (Isolate *isolate, FunctionCallback callback, int length, v8::SideEffectType side_effect_type)
static V8_WARN_UNUSED_RESULT MaybeHandle< JSFunction > InstantiateFunction (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name={})
static V8_WARN_UNUSED_RESULT MaybeHandle< JSFunction > InstantiateFunction (Isolate *isolate, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name={})
static V8_WARN_UNUSED_RESULT MaybeHandle< JSObject > InstantiateObject (Isolate *isolate, DirectHandle< ObjectTemplateInfo > data, DirectHandle< JSReceiver > new_target={})
static V8_WARN_UNUSED_RESULT MaybeHandle< JSObject > InstantiateRemoteObject (DirectHandle< ObjectTemplateInfo > data)
static Handle< JSFunction > CreateApiFunction (Isolate *isolate, DirectHandle< NativeContext > native_context, DirectHandle< FunctionTemplateInfo > obj, DirectHandle< Object > prototype, InstanceType type, MaybeDirectHandle< Name > name={})
static void AddDataProperty (Isolate *isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes)
static void AddDataProperty (Isolate *isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< Name > name, v8::Intrinsic intrinsic, PropertyAttributes attributes)
static void AddAccessorProperty (Isolate *isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< Name > name, DirectHandle< FunctionTemplateInfo > getter, DirectHandle< FunctionTemplateInfo > setter, PropertyAttributes attributes)
static void AddNativeDataProperty (Isolate *isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< AccessorInfo > property)
Static Public Attributes
static const int kInitialFunctionCacheSize = 256
Detailed Description
Definition at line 22 of file api-natives.h.
Member Function Documentation
AddAccessorProperty()
void v8::internal::ApiNatives::AddAccessorProperty (Isolate * isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< Name > name, DirectHandle< FunctionTemplateInfo > getter, DirectHandle< FunctionTemplateInfo > setter, PropertyAttributes attributes) [static]
Definition at line 568 of file api-natives.cc.
                                                                              {
  if (!getter.is_null()) getter->set_published(true);
  if (!setter.is_null()) setter->set_published(true);
  PropertyDetails details(PropertyKind::kAccessor, attributes,
                          PropertyConstness::kMutable);
  DirectHandle<Object> data[] = {name, direct_handle(details.AsSmi(), isolate),
                                 getter, setter};
  AddPropertyToPropertyList(isolate, info, base::VectorOf(data));
}
References v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList(), v8::internal::PropertyDetails::AsSmi(), v8::internal::direct_handle(), v8::internal::DirectHandle< T >::is_null(), v8::internal::kAccessor, v8::internal::kMutable, v8::internal::name, v8::internal::setter, and v8::base::VectorOf().
Referenced by v8::Template::SetAccessorProperty().
AddDataProperty() [1/2]
void v8::internal::ApiNatives::AddDataProperty (Isolate * isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< Name > name, DirectHandle< Object > value, PropertyAttributes attributes) [static]
Definition at line 542 of file api-natives.cc.
                                                                {
  PropertyDetails details(PropertyKind::kData, attributes,
                          PropertyConstness::kMutable);
  DirectHandle<Object> data[] = {name, direct_handle(details.AsSmi(), isolate),
                                 value};
  AddPropertyToPropertyList(isolate, info, base::VectorOf(data));
}
References v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList(), v8::internal::PropertyDetails::AsSmi(), v8::internal::direct_handle(), v8::internal::kData, v8::internal::kMutable, v8::internal::name, v8::internal::value, and v8::base::VectorOf().
Referenced by v8::Template::Set(), and v8::Template::SetIntrinsicDataProperty().
AddDataProperty() [2/2]
void v8::internal::ApiNatives::AddDataProperty (Isolate * isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< Name > name, v8::Intrinsic intrinsic, PropertyAttributes attributes) [static]
Definition at line 554 of file api-natives.cc.
                                                                {
  auto value = direct_handle(Smi::FromInt(intrinsic), isolate);
  auto intrinsic_marker = isolate->factory()->true_value();
  PropertyDetails details(PropertyKind::kData, attributes,
                          PropertyConstness::kMutable);
  DirectHandle<Object> data[] = {
      name, intrinsic_marker, direct_handle(details.AsSmi(), isolate), value};
  AddPropertyToPropertyList(isolate, info, base::VectorOf(data));
}
References v8::internal::anonymous_namespace{api-natives.cc}::AddPropertyToPropertyList(), v8::internal::PropertyDetails::AsSmi(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::kData, v8::internal::kMutable, v8::internal::name, v8::internal::value, and v8::base::VectorOf().
AddNativeDataProperty()
void v8::internal::ApiNatives::AddNativeDataProperty (Isolate * isolate, DirectHandle< TemplateInfoWithProperties > info, DirectHandle< AccessorInfo > property) [static]
Definition at line 581 of file api-natives.cc.
                                         {
  Tagged<Object> maybe_list = info->property_accessors();
  DirectHandle<ArrayList> list;
  if (IsUndefined(maybe_list, isolate)) {
    list = ArrayList::New(isolate, 1, AllocationType::kOld);
  } else {
    list = direct_handle(Cast<ArrayList>(maybe_list), isolate);
  }
  list = ArrayList::Add(isolate, list, property);
  info->set_property_accessors(*list);
}
References v8::internal::ArrayList::Add(), v8::internal::direct_handle(), v8::internal::kOld, and v8::internal::ArrayList::New().
Referenced by v8::anonymous_namespace{api.cc}::TemplateSetAccessor().
CreateAccessorFunctionTemplateInfo()
DirectHandle< FunctionTemplateInfo > v8::internal::ApiNatives::CreateAccessorFunctionTemplateInfo (Isolate * isolate, FunctionCallback callback, int length, v8::SideEffectType side_effect_type) [static]
Definition at line 484 of file api-natives.cc.
                                     {
  // TODO(v8:5962): move FunctionTemplateNew() from api.cc here.
  auto isolate = reinterpret_cast<v8::Isolate*>(i_isolate);
  Local<FunctionTemplate> func_template = FunctionTemplate::New(
      isolate, callback, v8::Local<Value>{}, v8::Local<v8::Signature>{}, length,
      v8::ConstructorBehavior::kThrow, side_effect_type);
  return Utils::OpenDirectHandle(*func_template);
}
References v8::kThrow, v8::internal::length, v8::FunctionTemplate::New(), and v8::Utils::OpenDirectHandle().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
CreateApiFunction()
Handle< JSFunction > v8::internal::ApiNatives::CreateApiFunction (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< FunctionTemplateInfo > obj, DirectHandle< Object > prototype, InstanceType type, MaybeDirectHandle< Name > name = {}) [static]
Definition at line 595 of file api-natives.cc.
                                                           {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCreateApiFunction);
  DirectHandle<SharedFunctionInfo> shared =
      FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(isolate, obj,
                                                          maybe_name);
  // To simplify things, API functions always have shared name.
  DCHECK(shared->HasSharedName());
  Handle<JSFunction> result =
      Factory::JSFunctionBuilder{isolate, shared, native_context}.Build();
  if (obj->remove_prototype()) {
    DCHECK(prototype.is_null());
    DCHECK(result->shared()->IsApiFunction());
    DCHECK(!IsConstructor(*result));
    DCHECK(!result->has_prototype_slot());
    return result;
  }
  // Down from here is only valid for API functions that can be used as a
  // constructor (don't set the "remove prototype" flag).
  DCHECK(result->has_prototype_slot());
  if (obj->read_only_prototype()) {
    result->set_map(isolate,
                    *isolate->sloppy_function_with_readonly_prototype_map());
  }
  if (IsTheHole(*prototype, isolate)) {
    prototype = isolate->factory()->NewFunctionPrototype(result);
  } else if (IsUndefined(obj->GetPrototypeProviderTemplate(), isolate)) {
    JSObject::AddProperty(isolate, Cast<JSObject>(prototype),
                          isolate->factory()->constructor_string(), result,
                          DONT_ENUM);
  }
  int embedder_field_count = 0;
  bool immutable_proto = false;
  if (!IsUndefined(obj->GetInstanceTemplate(), isolate)) {
    DirectHandle<ObjectTemplateInfo> GetInstanceTemplate(
        Cast<ObjectTemplateInfo>(obj->GetInstanceTemplate()), isolate);
    embedder_field_count = GetInstanceTemplate->embedder_field_count();
    immutable_proto = GetInstanceTemplate->immutable_proto();
  }
  // JSFunction requires information about the prototype slot.
  DCHECK(!InstanceTypeChecker::IsJSFunction(type));
  int instance_size = JSObject::GetHeaderSize(type) +
                      kEmbedderDataSlotSize * embedder_field_count;
  DirectHandle<Map> map = isolate->factory()->NewContextfulMap(
      native_context, type, instance_size, TERMINAL_FAST_ELEMENTS_KIND);
  // Mark as undetectable if needed.
  if (obj->undetectable()) {
    // We only allow callable undetectable receivers here, since this whole
    // undetectable business is only to support document.all, which is both
    // undetectable and callable. If we ever see the need to have an object
    // that is undetectable but not callable, we need to update the types.h
    // to allow encoding this.
    CHECK(!IsUndefined(obj->GetInstanceCallHandler(), isolate));
    if (Protectors::IsNoUndetectableObjectsIntact(isolate)) {
      Protectors::InvalidateNoUndetectableObjects(isolate);
    }
    map->set_is_undetectable(true);
  }
  // Mark as needs_access_check if needed.
  if (obj->needs_access_check()) {
    map->set_is_access_check_needed(true);
    map->set_may_have_interesting_properties(true);
  }
  // Set interceptor information in the map.
  if (!IsUndefined(obj->GetNamedPropertyHandler(), isolate)) {
    map->set_has_named_interceptor(true);
    map->set_may_have_interesting_properties(true);
  }
  if (!IsUndefined(obj->GetIndexedPropertyHandler(), isolate)) {
    map->set_has_indexed_interceptor(true);
  }
  // Mark instance as callable in the map.
  if (!IsUndefined(obj->GetInstanceCallHandler(), isolate)) {
    map->set_is_callable(true);
    map->set_is_constructor(!obj->undetectable());
  }
  if (immutable_proto) map->set_is_immutable_proto(true);
  JSFunction::SetInitialMap(isolate, result, map, Cast<JSObject>(prototype));
  return result;
}
References v8::internal::JSObject::AddProperty(), CHECK, v8::internal::DCHECK(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::internal::JSObject::GetHeaderSize(), v8::internal::FunctionTemplateInfo::GetOrCreateSharedFunctionInfo(), v8::internal::kEmbedderDataSlotSize, v8::internal::native_context, v8::internal::Factory::NewContextfulMap(), v8::internal::Factory::NewFunctionPrototype(), v8::internal::prototype, RCS_SCOPE, v8::base::internal::result, v8::internal::JSFunction::SetInitialMap(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, and v8::internal::tracing::type.
Referenced by v8::internal::Genesis::CreateNewGlobals(), and v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction().
InstantiateFunction() [1/2]
MaybeHandle< JSFunction > v8::internal::ApiNatives::InstantiateFunction (Isolate * isolate, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name = {}) [static]
Definition at line 503 of file api-natives.cc.
                                        {
  InvokeScope invoke_scope(isolate);
  return ::i::InstantiateFunction(isolate, data, maybe_name);
}
References v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction().
InstantiateFunction() [2/2]
MaybeHandle< JSFunction > v8::internal::ApiNatives::InstantiateFunction (Isolate * isolate, DirectHandle< NativeContext > native_context, DirectHandle< FunctionTemplateInfo > data, MaybeDirectHandle< Name > maybe_name = {}) [static]
Definition at line 495 of file api-natives.cc.
                                        {
  InvokeScope invoke_scope(isolate);
  return ::i::InstantiateFunction(isolate, native_context, data, maybe_name);
}
References v8::internal::anonymous_namespace{api-natives.cc}::InstantiateFunction(), and v8::internal::native_context.
Referenced by v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::AccessorPair::GetComponent(), v8::internal::ApiCallbackExitFrame::GetFunction(), v8::FunctionTemplate::GetFunction(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap().
InstantiateObject()
MaybeHandle< JSObject > v8::internal::ApiNatives::InstantiateObject (Isolate * isolate, DirectHandle< ObjectTemplateInfo > data, DirectHandle< JSReceiver > new_target = {}) [static]
Definition at line 510 of file api-natives.cc.
                                         {
  InvokeScope invoke_scope(isolate);
  return ::i::InstantiateObject(isolate, data, new_target, false);
}
References v8::internal::anonymous_namespace{api-natives.cc}::InstantiateObject().
Referenced by v8::internal::Genesis::ConfigureApiObject(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), and v8::ObjectTemplate::NewInstance().
InstantiateRemoteObject()
MaybeHandle< JSObject > v8::internal::ApiNatives::InstantiateRemoteObject (DirectHandle< ObjectTemplateInfo > data) [static]
Definition at line 517 of file api-natives.cc.
                                           {
  Isolate* isolate = Isolate::Current();
  InvokeScope invoke_scope(isolate);
  DirectHandle<FunctionTemplateInfo> constructor(
      Cast<FunctionTemplateInfo>(data->constructor()), isolate);
  DirectHandle<Map> object_map = isolate->factory()->NewContextlessMap(
      JS_SPECIAL_API_OBJECT_TYPE,
      JSSpecialObject::kHeaderSize +
          data->embedder_field_count() * kEmbedderDataSlotSize,
      TERMINAL_FAST_ELEMENTS_KIND);
  object_map->SetConstructor(*constructor);
  object_map->set_is_access_check_needed(true);
  object_map->set_may_have_interesting_properties(true);
  Handle<JSObject> object = isolate->factory()->NewJSObjectFromMap(
      object_map, AllocationType::kYoung, DirectHandle<AllocationSite>::null(),
      NewJSObjectType::kAPIWrapper);
  JSObject::ForceSetPrototype(isolate, object,
                              isolate->factory()->null_value());
  return object;
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::JSObject::ForceSetPrototype(), v8::internal::kAPIWrapper, v8::internal::kEmbedderDataSlotSize, v8::internal::kYoung, v8::internal::Factory::NewContextlessMap(), v8::internal::Factory::NewJSObjectFromMap(), and v8::internal::TERMINAL_FAST_ELEMENTS_KIND.
Referenced by v8::internal::Genesis::Genesis(), and v8::FunctionTemplate::NewRemoteInstance().
Member Data Documentation
kInitialFunctionCacheSize
const int v8::internal::ApiNatives::kInitialFunctionCacheSize = 256 [static]
Definition at line 24 of file api-natives.h.
Referenced by v8::internal::Genesis::InstallABunchOfRandomThings().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api-natives.h
/mnt/V8SourceCode/src/api/api-natives.cc