v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem Class Reference
Public Member Functions
RememberedSetUpdatingItem (Heap *heap, MutablePageMetadata *chunk)
~RememberedSetUpdatingItem () override=default
void Process () override
Private Member Functions
template<typename TSlot >
void CheckSlotForOldToSharedUntyped (PtrComprCageBase cage_base, MutablePageMetadata *page, TSlot slot)
void CheckSlotForOldToSharedTyped (MutablePageMetadata *page, SlotType slot_type, Address addr, WritableJitAllocation &jit_allocation)
template<typename TSlot >
void CheckAndUpdateOldToNewSlot (TSlot slot, const PtrComprCageBase cage_base)
void UpdateUntypedPointers ()
template<RememberedSetType old_to_new_type>
void UpdateUntypedOldToNewPointers ()
void UpdateUntypedOldToOldPointers ()
void UpdateUntypedTrustedToCodePointers ()
void UpdateUntypedTrustedToTrustedPointers ()
void UpdateTypedPointers ()
void UpdateTypedOldToNewPointers (WritableJitPage &jit_page)
void UpdateTypedOldToOldPointers (WritableJitPage &jit_page)
Private Attributes
Heap * heap_
NonAtomicMarkingState * marking_state_
MutablePageMetadata * chunk_
const bool record_old_to_shared_slots_
Detailed Description
Definition at line 5214 of file mark-compact.cc.
Constructor & Destructor Documentation
RememberedSetUpdatingItem()
v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::RememberedSetUpdatingItem (Heap * heap, MutablePageMetadata * chunk) [inline], [explicit]
Definition at line 5216 of file mark-compact.cc.
      : heap_(heap),
        marking_state_(heap_->non_atomic_marking_state()),
        chunk_(chunk),
        record_old_to_shared_slots_(heap->isolate()->has_shared_space() &&
                                    !chunk->Chunk()->InWritableSharedSpace()) {}
 RememberedSetUpdatingItem()
v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::~RememberedSetUpdatingItem () [override], [default]
Member Function Documentation
CheckAndUpdateOldToNewSlot()
template<typename TSlot >
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckAndUpdateOldToNewSlot (TSlot slot, const PtrComprCageBase cage_base) [inline], [private]
Definition at line 5272 of file mark-compact.cc.
                                                                           {
    static_assert(
        std::is_same_v<TSlot, FullMaybeObjectSlot> ||
            std::is_same_v<TSlot, MaybeObjectSlot>,
        "Only FullMaybeObjectSlot and MaybeObjectSlot are expected here");
    Tagged<HeapObject> heap_object;
    if (!(*slot).GetHeapObject(&heap_object)) return;
    if (!HeapLayout::InYoungGeneration(heap_object)) return;
    if (!v8_flags.sticky_mark_bits) {
      DCHECK_IMPLIES(v8_flags.minor_ms && !Heap::IsLargeObject(heap_object),
                     Heap::InToPage(heap_object));
      DCHECK_IMPLIES(!v8_flags.minor_ms || Heap::IsLargeObject(heap_object),
                     Heap::InFromPage(heap_object));
    }
    // OLD_TO_NEW slots are recorded in dead memory, so they might point to
    // dead objects.
    DCHECK_IMPLIES(!heap_object->map_word(kRelaxedLoad).IsForwardingAddress(),
                   !marking_state_->IsMarked(heap_object));
    UpdateSlot(cage_base, slot);
  }
References DCHECK_IMPLIES, v8::kRelaxedLoad, v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot(), and v8::internal::v8_flags.
CheckSlotForOldToSharedTyped()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckSlotForOldToSharedTyped (MutablePageMetadata * page, SlotType slot_type, Address addr, WritableJitAllocation & jit_allocation) [inline], [private]
Definition at line 5248 of file mark-compact.cc.
                                             {
    Tagged<HeapObject> heap_object =
        UpdateTypedSlotHelper::GetTargetObject(page->heap(), slot_type, addr);
#if DEBUG
    UpdateTypedSlotHelper::UpdateTypedSlot(
        jit_allocation, page->heap(), slot_type, addr,
        [heap_object](FullMaybeObjectSlot slot) {
          DCHECK_EQ((*slot).GetHeapObjectAssumeStrong(), heap_object);
          return KEEP_SLOT;
        });
#endif // DEBUG
    if (HeapLayout::InWritableSharedSpace(heap_object)) {
      const uintptr_t offset = page->Offset(addr);
      DCHECK_LT(offset, static_cast<uintptr_t>(TypedSlotSet::kMaxOffset));
      RememberedSet<OLD_TO_SHARED>::InsertTyped(page, slot_type,
                                                static_cast<uint32_t>(offset));
    }
  }
References DCHECK_LT, v8::internal::MemoryChunkMetadata::heap(), and v8::internal::MemoryChunkMetadata::Offset().
CheckSlotForOldToSharedUntyped()
template<typename TSlot >
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckSlotForOldToSharedUntyped (PtrComprCageBase cage_base, MutablePageMetadata * page, TSlot slot) [inline], [private]
Definition at line 5233 of file mark-compact.cc.
                                                         {
    Tagged<HeapObject> heap_object;
    if (!slot.load(cage_base).GetHeapObject(&heap_object)) {
      return;
    }
    if (HeapLayout::InWritableSharedSpace(heap_object)) {
      RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::NON_ATOMIC>(
          page, page->Offset(slot.address()));
    }
  }
References v8::internal::MemoryChunkMetadata::Offset().
Process()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::Process () [inline], [override], [virtual]
Implements v8::internal::UpdatingItem.
Definition at line 5224 of file mark-compact.cc.
                          {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                 "RememberedSetUpdatingItem::Process");
    UpdateUntypedPointers();
    UpdateTypedPointers();
  }
References TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
UpdateTypedOldToNewPointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateTypedOldToNewPointers (WritableJitPage & jit_page) [inline], [private]
Definition at line 5481 of file mark-compact.cc.
                                                              {
    if (chunk_->typed_slot_set<OLD_TO_NEW, AccessMode::NON_ATOMIC>() == nullptr)
      return;
    const PtrComprCageBase cage_base = heap_->isolate();
    const auto check_and_update_old_to_new_slot_fn =
        [this, cage_base](FullMaybeObjectSlot slot) {
          CheckAndUpdateOldToNewSlot(slot, cage_base);
          return KEEP_SLOT;
        };
    RememberedSet<OLD_TO_NEW>::IterateTyped(
        chunk_, [this, &check_and_update_old_to_new_slot_fn, &jit_page](
                    SlotType slot_type, Address slot) {
          WritableJitAllocation jit_allocation =
              jit_page.LookupAllocationContaining(slot);
          UpdateTypedSlotHelper::UpdateTypedSlot(
              jit_allocation, heap_, slot_type, slot,
              check_and_update_old_to_new_slot_fn);
          // A new space string might have been promoted into the shared heap
          // during GC.
          if (record_old_to_shared_slots_) {
            CheckSlotForOldToSharedTyped(chunk_, slot_type, slot,
                                         jit_allocation);
          }
          // Always keep slot since all slots are dropped at once after
          // iteration.
          return KEEP_SLOT;
        });
    // Full GCs will empty new space, so OLD_TO_NEW is empty.
    chunk_->ReleaseTypedSlotSet(OLD_TO_NEW);
    // OLD_TO_NEW_BACKGROUND typed slots set should always be empty.
    DCHECK_NULL(chunk_->typed_slot_set<OLD_TO_NEW_BACKGROUND>());
  }
References DCHECK_NULL, heap::base::KEEP_SLOT, v8::internal::WritableJitPage::LookupAllocationContaining(), v8::internal::OLD_TO_NEW, and v8::internal::OLD_TO_NEW_BACKGROUND.
UpdateTypedOldToOldPointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateTypedOldToOldPointers (WritableJitPage & jit_page) [inline], [private]
Definition at line 5515 of file mark-compact.cc.
                                                              {
    if (chunk_->typed_slot_set<OLD_TO_OLD, AccessMode::NON_ATOMIC>() == nullptr)
      return;
    PtrComprCageBase cage_base = heap_->isolate();
    RememberedSet<OLD_TO_OLD>::IterateTyped(
        chunk_, [this, cage_base, &jit_page](SlotType slot_type, Address slot) {
          // Using UpdateStrongSlot is OK here, because there are no weak
          // typed slots.
          WritableJitAllocation jit_allocation =
              jit_page.LookupAllocationContaining(slot);
          SlotCallbackResult result = UpdateTypedSlotHelper::UpdateTypedSlot(
              jit_allocation, heap_, slot_type, slot,
              [cage_base](FullMaybeObjectSlot slot) {
                UpdateStrongSlot(cage_base, slot);
                // Always keep slot since all slots are dropped at once after
                // iteration.
                return KEEP_SLOT;
              });
          // A string might have been promoted into the shared heap during GC.
          if (record_old_to_shared_slots_) {
            CheckSlotForOldToSharedTyped(chunk_, slot_type, slot,
                                         jit_allocation);
          }
          return result;
        });
    chunk_->ReleaseTypedSlotSet(OLD_TO_OLD);
  }
References heap::base::KEEP_SLOT, v8::internal::WritableJitPage::LookupAllocationContaining(), v8::internal::OLD_TO_OLD, v8::base::internal::result, and v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot().
UpdateTypedPointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateTypedPointers () [inline], [private]
Definition at line 5468 of file mark-compact.cc.
                             {
    if (!chunk_->Chunk()->executable()) {
      DCHECK_NULL((chunk_->typed_slot_set<OLD_TO_NEW>()));
      DCHECK_NULL((chunk_->typed_slot_set<OLD_TO_OLD>()));
      return;
    }
    WritableJitPage jit_page = ThreadIsolation::LookupWritableJitPage(
        chunk_->area_start(), chunk_->area_size());
    UpdateTypedOldToNewPointers(jit_page);
    UpdateTypedOldToOldPointers(jit_page);
  }
References DCHECK_NULL, v8::internal::OLD_TO_NEW, and v8::internal::OLD_TO_OLD.
UpdateUntypedOldToNewPointers()
template<RememberedSetType old_to_new_type>
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedOldToNewPointers () [inline], [private]
Definition at line 5305 of file mark-compact.cc.
                                       {
    if (!chunk_->slot_set<old_to_new_type, AccessMode::NON_ATOMIC>()) {
      return;
    }
    const PtrComprCageBase cage_base = heap_->isolate();
    // Marking bits are cleared already when the page is already swept. This
    // is fine since in that case the sweeper has already removed dead invalid
    // objects as well.
    RememberedSet<old_to_new_type>::Iterate(
        chunk_,
        [this, cage_base](MaybeObjectSlot slot) {
          CheckAndUpdateOldToNewSlot(slot, cage_base);
          // A new space string might have been promoted into the shared heap
          // during GC.
          if (record_old_to_shared_slots_) {
            CheckSlotForOldToSharedUntyped(cage_base, chunk_, slot);
          }
          // Always keep slot since all slots are dropped at once after
          // iteration.
          return KEEP_SLOT;
        },
        SlotSet::KEEP_EMPTY_BUCKETS);
    // Full GCs will empty new space, so [old_to_new_type] is empty.
    chunk_->ReleaseSlotSet(old_to_new_type);
  }
References heap::base::KEEP_SLOT.
UpdateUntypedOldToOldPointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedOldToOldPointers () [inline], [private]
Definition at line 5333 of file mark-compact.cc.
                                       {
    if (!chunk_->slot_set<OLD_TO_OLD, AccessMode::NON_ATOMIC>()) {
      return;
    }
    const PtrComprCageBase cage_base = heap_->isolate();
    if (chunk_->Chunk()->executable()) {
      // When updating pointer in an InstructionStream (in particular, the
      // pointer to relocation info), we need to use WriteProtectedSlots that
      // ensure that the code page is unlocked.
      WritableJitPage jit_page(chunk_->area_start(), chunk_->area_size());
      RememberedSet<OLD_TO_OLD>::Iterate(
          chunk_,
          [&](MaybeObjectSlot slot) {
            WritableJitAllocation jit_allocation =
                jit_page.LookupAllocationContaining(slot.address());
            UpdateSlot(cage_base, WriteProtectedSlot<ObjectSlot>(
                                      jit_allocation, slot.address()));
            // Always keep slot since all slots are dropped at once after
            // iteration.
            return KEEP_SLOT;
          },
          SlotSet::KEEP_EMPTY_BUCKETS);
    } else {
      RememberedSet<OLD_TO_OLD>::Iterate(
          chunk_,
          [&](MaybeObjectSlot slot) {
            UpdateSlot(cage_base, slot);
            // A string might have been promoted into the shared heap during
            // GC.
            if (record_old_to_shared_slots_) {
              CheckSlotForOldToSharedUntyped(cage_base, chunk_, slot);
            }
            // Always keep slot since all slots are dropped at once after
            // iteration.
            return KEEP_SLOT;
          },
          SlotSet::KEEP_EMPTY_BUCKETS);
    }
    chunk_->ReleaseSlotSet(OLD_TO_OLD);
  }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), heap::base::KEEP_SLOT, v8::internal::WritableJitPage::LookupAllocationContaining(), v8::internal::OLD_TO_OLD, and v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot().
UpdateUntypedPointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedPointers () [inline], [private]
Definition at line 5296 of file mark-compact.cc.
                               {
    UpdateUntypedOldToNewPointers<OLD_TO_NEW>();
    UpdateUntypedOldToNewPointers<OLD_TO_NEW_BACKGROUND>();
    UpdateUntypedOldToOldPointers();
    UpdateUntypedTrustedToCodePointers();
    UpdateUntypedTrustedToTrustedPointers();
  }
UpdateUntypedTrustedToCodePointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToCodePointers () [inline], [private]
Definition at line 5376 of file mark-compact.cc.
                                            {
    if (!chunk_->slot_set<TRUSTED_TO_CODE, AccessMode::NON_ATOMIC>()) {
      return;
    }
#ifdef V8_ENABLE_SANDBOX
    // When the sandbox is enabled, we must not process the TRUSTED_TO_CODE
    // remembered set on any chunk that is located inside the sandbox (in which
    // case the set should be unused). This is because an attacker could either
    // directly modify the TRUSTED_TO_CODE set on such a chunk, or trick the GC
    // into populating it with invalid pointers, both of which may lead to
    // memory corruption inside the (trusted) code space here.
    SBXCHECK(!InsideSandbox(chunk_->ChunkAddress()));
#endif
    const PtrComprCageBase cage_base = heap_->isolate();
#ifdef V8_EXTERNAL_CODE_SPACE
    const PtrComprCageBase code_cage_base(heap_->isolate()->code_cage_base());
#else
    const PtrComprCageBase code_cage_base = cage_base;
#endif
    RememberedSet<TRUSTED_TO_CODE>::Iterate(
        chunk_,
        [cage_base, code_cage_base,
         isolate = IsolateForSandbox{heap_->isolate()}](MaybeObjectSlot slot) {
          DCHECK(IsCode(HeapObject::FromAddress(slot.address() -
                                                Code::kInstructionStreamOffset),
                        cage_base));
          UpdateStrongCodeSlot(isolate, cage_base, code_cage_base,
                               InstructionStreamSlot(slot.address()));
          // Always keep slot since all slots are dropped at once after
          // iteration.
          return KEEP_SLOT;
        },
        SlotSet::FREE_EMPTY_BUCKETS);
    chunk_->ReleaseSlotSet(TRUSTED_TO_CODE);
  }
References DCHECK, v8::internal::InsideSandbox(), heap::base::KEEP_SLOT, SBXCHECK, v8::internal::TRUSTED_TO_CODE, and v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot().
UpdateUntypedTrustedToTrustedPointers()
void v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::UpdateUntypedTrustedToTrustedPointers () [inline], [private]
Definition at line 5415 of file mark-compact.cc.
                                               {
    if (!chunk_->slot_set<TRUSTED_TO_TRUSTED, AccessMode::NON_ATOMIC>()) {
      return;
    }
#ifdef V8_ENABLE_SANDBOX
    // When the sandbox is enabled, we must not process the TRUSTED_TO_TRUSTED
    // remembered set on any chunk that is located inside the sandbox (in which
    // case the set should be unused). This is because an attacker could either
    // directly modify the TRUSTED_TO_TRUSTED set on such a chunk, or trick the
    // GC into populating it with invalid pointers, both of which may lead to
    // memory corruption inside the trusted space here.
    SBXCHECK(!InsideSandbox(chunk_->ChunkAddress()));
#endif
    // TODO(saelo) we can probably drop all the cage_bases here once we no
    // longer need to pass them into our slot implementations.
    const PtrComprCageBase unused_cage_base(kNullAddress);
    if (chunk_->Chunk()->executable()) {
      // When updating the InstructionStream -> Code pointer, we need to use
      // WriteProtectedSlots that ensure that the code page is unlocked.
      WritableJitPage jit_page(chunk_->area_start(), chunk_->area_size());
      RememberedSet<TRUSTED_TO_TRUSTED>::Iterate(
          chunk_,
          [&](MaybeObjectSlot slot) {
            WritableJitAllocation jit_allocation =
                jit_page.LookupAllocationContaining(slot.address());
            UpdateStrongSlot(unused_cage_base,
                             WriteProtectedSlot<ProtectedPointerSlot>(
                                 jit_allocation, slot.address()));
            // Always keep slot since all slots are dropped at once after
            // iteration.
            return KEEP_SLOT;
          },
          SlotSet::FREE_EMPTY_BUCKETS);
    } else {
      RememberedSet<TRUSTED_TO_TRUSTED>::Iterate(
          chunk_,
          [&](MaybeObjectSlot slot) {
            UpdateSlot(unused_cage_base,
                       ProtectedMaybeObjectSlot(slot.address()));
            // Always keep slot since all slots are dropped at once after
            // iteration.
            return KEEP_SLOT;
          },
          SlotSet::FREE_EMPTY_BUCKETS);
    }
    chunk_->ReleaseSlotSet(TRUSTED_TO_TRUSTED);
  }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::InsideSandbox(), heap::base::KEEP_SLOT, v8::base::kNullAddress, v8::internal::WritableJitPage::LookupAllocationContaining(), SBXCHECK, v8::internal::TRUSTED_TO_TRUSTED, v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot(), and v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot().
Member Data Documentation
chunk_
MutablePageMetadata* v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::chunk_ [private]
Definition at line 5545 of file mark-compact.cc.
heap_
Heap* v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::heap_ [private]
Definition at line 5543 of file mark-compact.cc.
marking_state_
NonAtomicMarkingState* v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::marking_state_ [private]
Definition at line 5544 of file mark-compact.cc.
record_old_to_shared_slots_
const bool v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::record_old_to_shared_slots_ [private]
Definition at line 5546 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc