v8::internal::compiler::LiveRangeBundle Class Reference
#include <register-allocator.h>
Public Member Functions
LiveRangeBundle (Zone *zone, int id)
int id () const
int reg () const
void set_reg (int reg)
void MergeSpillRangesAndClear ()
bool TryAddRange (TopLevelLiveRange *range)
Static Public Member Functions
static LiveRangeBundle * TryMerge (LiveRangeBundle *lhs, LiveRangeBundle *rhs)
Private Member Functions
void AddRange (TopLevelLiveRange *range)
Private Attributes
ZoneVector< TopLevelLiveRange * > ranges_
ZoneVector< UseInterval > intervals_
int id_
int reg_ = kUnassignedRegister
Detailed Description
Definition at line 981 of file register-allocator.h.
Constructor & Destructor Documentation
LiveRangeBundle()
v8::internal::compiler::LiveRangeBundle::LiveRangeBundle (Zone * zone, int id) [inline], [explicit]
Definition at line 983 of file register-allocator.h.
      : ranges_(zone), intervals_(zone), id_(id) {}
Member Function Documentation
AddRange()
void v8::internal::compiler::LiveRangeBundle::AddRange (TopLevelLiveRange * range) [private]
Definition at line 2646 of file register-allocator.cc.
                                                       {
  TopLevelLiveRange** range_insert_it = std::lower_bound(
      ranges_.begin(), ranges_.end(), range, LiveRangeOrdering());
  DCHECK_IMPLIES(range_insert_it != ranges_.end(), *range_insert_it != range);
  // TODO(dlehmann): We might save some memory by using
  // `DoubleEndedSplitVector::insert<kFront>()` here: Since we add ranges
  // mostly backwards, ranges with an earlier `Start()` are inserted mostly
  // at the front.
  ranges_.insert(range_insert_it, 1, range);
  range->set_bundle(this);
  // We also tried `std::merge`ing the sorted vectors of `intervals_` directly,
  // but it turns out the (always happening) copies are more expensive
  // than the (apparently seldom) copies due to insertion in the middle.
  for (UseInterval interval : range->intervals()) {
    UseInterval* interval_insert_it =
        std::lower_bound(intervals_.begin(), intervals_.end(), interval);
    DCHECK_IMPLIES(interval_insert_it != intervals_.end(),
                   *interval_insert_it != interval);
    intervals_.insert(interval_insert_it, 1, interval);
  }
}
References DCHECK_IMPLIES, v8::internal::compiler::LiveRange::intervals(), intervals_, ranges_, and v8::internal::compiler::TopLevelLiveRange::set_bundle().
Referenced by TryAddRange(), and TryMerge().
id()
int v8::internal::compiler::LiveRangeBundle::id () const [inline]
Definition at line 986 of file register-allocator.h.
{ return id_; }
References id_.
Referenced by v8::internal::compiler::BundleBuilder::BuildBundles(), and v8::internal::compiler::GraphC1Visualizer::PrintLiveRange().
MergeSpillRangesAndClear()
void v8::internal::compiler::LiveRangeBundle::MergeSpillRangesAndClear ()
Definition at line 2697 of file register-allocator.cc.
                                               {
  DCHECK_IMPLIES(ranges_.empty(), intervals_.empty());
  SpillRange* target = nullptr;
  for (auto range : ranges_) {
    if (range->TopLevel()->HasSpillRange()) {
      SpillRange* current = range->TopLevel()->GetSpillRange();
      if (target == nullptr) {
        target = current;
      } else if (target != current) {
        target->TryMerge(current);
      }
    }
  }
  // Clear the fields so that we don't try to merge the spill ranges again when
  // we hit the same bundle from a different LiveRange in AssignSpillSlots.
  // LiveRangeBundles are not used after this.
  ranges_.clear();
  intervals_.clear();
}
References DCHECK_IMPLIES, intervals_, ranges_, and v8::internal::compiler::SpillRange::TryMerge().
reg()
int v8::internal::compiler::LiveRangeBundle::reg () const [inline]
Definition at line 988 of file register-allocator.h.
{ return reg_; }
References reg_.
Referenced by v8::internal::compiler::LiveRange::RegisterFromBundle(), set_reg(), and v8::internal::compiler::LiveRange::UpdateBundleRegister().
set_reg()
void v8::internal::compiler::LiveRangeBundle::set_reg (int reg) [inline]
Definition at line 989 of file register-allocator.h.
                        {
    DCHECK_EQ(reg_, kUnassignedRegister);
    reg_ = reg;
  }
References DCHECK_EQ, v8::internal::compiler::kUnassignedRegister, reg(), and reg_.
Referenced by v8::internal::compiler::LiveRange::UpdateBundleRegister().
TryAddRange()
bool v8::internal::compiler::LiveRangeBundle::TryAddRange (TopLevelLiveRange * range)
Definition at line 2636 of file register-allocator.cc.
                                                          {
  DCHECK_NULL(range->get_bundle());
  // We may only add a new live range if its use intervals do not
  // overlap with existing intervals in the bundle.
  if (AreUseIntervalsIntersecting(this->intervals_, range->intervals()))
    return false;
  AddRange(range);
  return true;
}
References AddRange(), v8::internal::compiler::AreUseIntervalsIntersecting(), DCHECK_NULL, v8::internal::compiler::TopLevelLiveRange::get_bundle(), v8::internal::compiler::LiveRange::intervals(), and intervals_.
Referenced by v8::internal::compiler::BundleBuilder::BuildBundles().
TryMerge()
LiveRangeBundle * v8::internal::compiler::LiveRangeBundle::TryMerge (LiveRangeBundle * lhs, LiveRangeBundle * rhs) [static]
Definition at line 2669 of file register-allocator.cc.
                                                                 {
  if (rhs == lhs) return lhs;
  if (auto found =
          AreUseIntervalsIntersecting(lhs->intervals_, rhs->intervals_)) {
    auto [interval1, interval2] = *found;
    TRACE("No merge %d:%d %d:%d\n", interval1.start().value(),
          interval1.end().value(), interval2.start().value(),
          interval2.end().value());
    return nullptr;
  }
  // Uses are disjoint, merging is possible.
  // Merge the smaller bundle into the bigger.
  if (lhs->intervals_.size() < rhs->intervals_.size()) {
    std::swap(lhs, rhs);
  }
  for (TopLevelLiveRange* range : rhs->ranges_) {
    lhs->AddRange(range);
  }
  rhs->ranges_.clear();
  rhs->intervals_.clear();
  return lhs;
}
References AddRange(), v8::internal::compiler::AreUseIntervalsIntersecting(), intervals_, ranges_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::BundleBuilder::BuildBundles().
Member Data Documentation
id_
int v8::internal::compiler::LiveRangeBundle::id_ [private]
Definition at line 1008 of file register-allocator.h.
Referenced by id().
intervals_
ZoneVector<UseInterval> v8::internal::compiler::LiveRangeBundle::intervals_ [private]
Definition at line 1006 of file register-allocator.h.
Referenced by AddRange(), MergeSpillRangesAndClear(), TryAddRange(), and TryMerge().
ranges_
ZoneVector<TopLevelLiveRange*> v8::internal::compiler::LiveRangeBundle::ranges_ [private]
Definition at line 1004 of file register-allocator.h.
Referenced by AddRange(), MergeSpillRangesAndClear(), and TryMerge().
reg_
int v8::internal::compiler::LiveRangeBundle::reg_ = kUnassignedRegister [private]
Definition at line 1009 of file register-allocator.h.
Referenced by reg(), and set_reg().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc