v8::internal::PagedSpaceIterator Class Reference
#include <heap.h>
Public Member Functions
PagedSpaceIterator (const Heap *heap)
PagedSpace * Next ()
Private Attributes
const Heap *const heap_
int counter_
Detailed Description
Definition at line 2663 of file heap.h.
Constructor & Destructor Documentation
PagedSpaceIterator()
v8::internal::PagedSpaceIterator::PagedSpaceIterator (const Heap * heap) [inline], [explicit]
Definition at line 2665 of file heap.h.
      : heap_(heap), counter_(FIRST_GROWABLE_PAGED_SPACE) {}
Member Function Documentation
Next()
PagedSpace * v8::internal::PagedSpaceIterator::Next ()
Definition at line 6676 of file heap.cc.
                                     {
  DCHECK_GE(counter_, FIRST_GROWABLE_PAGED_SPACE);
  while (counter_ <= LAST_GROWABLE_PAGED_SPACE) {
    PagedSpace* space = heap_->paged_space(counter_++);
    if (space) return space;
  }
  return nullptr;
}
References counter_, DCHECK_GE, v8::internal::FIRST_GROWABLE_PAGED_SPACE, heap_, v8::internal::LAST_GROWABLE_PAGED_SPACE, v8::internal::Heap::paged_space(), and space.
Referenced by v8::internal::Heap::CollectAllAvailableGarbage(), v8::internal::Heap::CommittedOldGenerationMemory(), v8::internal::CountTotalHolesSize(), v8::internal::Heap::NotifyDeserializationComplete(), v8::internal::Heap::OldGenerationCapacity(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), and v8::internal::Heap::OldGenerationWastedBytes().
Member Data Documentation
counter_
int v8::internal::PagedSpaceIterator::counter_ [private]
Definition at line 2671 of file heap.h.
Referenced by Next().
heap_
const Heap* const v8::internal::PagedSpaceIterator::heap_ [private]
Definition at line 2670 of file heap.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap.cc