v8::internal::WritableRelocInfo Class Reference
#include <reloc-info.h>
Public Member Functions
WritableRelocInfo (WritableJitAllocation &jit_allocation, Address pc, Mode rmode)
WritableRelocInfo (WritableJitAllocation &jit_allocation, Address pc, Mode rmode, intptr_t data, Address constant_pool)
void apply (intptr_t delta)
void set_wasm_call_address (Address)
void set_wasm_stub_call_address (Address)
void set_wasm_canonical_sig_id (uint32_t)
void set_wasm_code_pointer_table_entry (WasmCodePointer, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
void set_target_address (Tagged< InstructionStream > host, Address target, WriteBarrierMode write_barrier_mode=UPDATE_WRITE_BARRIER, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
void set_target_address (Address target, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
void set_target_object (Tagged< InstructionStream > host, Tagged< HeapObject > target, WriteBarrierMode write_barrier_mode=UPDATE_WRITE_BARRIER, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
void set_target_object (Tagged< HeapObject > target, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
void set_target_external_reference (Address, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
void set_js_dispatch_handle (Tagged< InstructionStream > host, JSDispatchHandle handle, WriteBarrierMode write_barrier_mode=UPDATE_WRITE_BARRIER, ICacheFlushMode icache_flush_mode=FLUSH_ICACHE_IF_NEEDED)
WritableJitAllocation & jit_allocation ()
Private Attributes
WritableJitAllocation & jit_allocation_
Additional Inherited Members
Detailed Description
Definition at line 412 of file reloc-info.h.
Constructor & Destructor Documentation
WritableRelocInfo() [1/2]
v8::internal::WritableRelocInfo::WritableRelocInfo (WritableJitAllocation & jit_allocation, Address pc, Mode rmode) [inline]
Definition at line 414 of file reloc-info.h.
      : RelocInfo(pc, rmode), jit_allocation_(jit_allocation) {}
WritableRelocInfo() [2/2]
v8::internal::WritableRelocInfo::WritableRelocInfo (WritableJitAllocation & jit_allocation, Address pc, Mode rmode, intptr_t data, Address constant_pool) [inline]
Definition at line 417 of file reloc-info.h.
      : RelocInfo(pc, rmode, data, constant_pool),
        jit_allocation_(jit_allocation) {}
Member Function Documentation
apply()
void v8::internal::WritableRelocInfo::apply (intptr_t delta) [inline]
Definition at line 58 of file assembler-arm-inl.h.
                                            {
  if (RelocInfo::IsInternalReference(rmode_)) {
    // absolute code pointer inside code object moves with the code object.
    int32_t* p = reinterpret_cast<int32_t*>(pc_);
    jit_allocation_.WriteValue(pc_, *p + delta); // relocate entry
  } else if (RelocInfo::IsRelativeCodeTarget(rmode_)) {
    Instruction* branch = Instruction::At(pc_);
    int32_t branch_offset = branch->GetBranchOffset() - delta;
    branch->SetBranchOffset(branch_offset, &jit_allocation_);
  }
}
References v8::internal::Instruction::At(), v8::internal::Instruction::GetBranchOffset(), v8::internal::RelocInfo::IsInternalReference(), v8::internal::RelocInfo::IsRelativeCodeTarget(), jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, v8::internal::Instruction::SetBranchOffset(), and v8::internal::WritableJitAllocation::WriteValue().
jit_allocation()
WritableJitAllocation& v8::internal::WritableRelocInfo::jit_allocation () [inline]
Definition at line 460 of file reloc-info.h.
{ return jit_allocation_; }
References jit_allocation_.
set_js_dispatch_handle()
void v8::internal::WritableRelocInfo::set_js_dispatch_handle (Tagged< InstructionStream > host, JSDispatchHandle handle, WriteBarrierMode write_barrier_mode = UPDATE_WRITE_BARRIER, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED)
Definition at line 306 of file reloc-info.cc.
                                                                            {
  DCHECK(IsJSDispatchHandle(rmode_));
  Assembler::set_uint32_constant_at(pc_, constant_pool_, *handle,
                                    &jit_allocation_, icache_flush_mode);
  if (!v8_flags.disable_write_barriers && handle != kNullJSDispatchHandle) {
    WriteBarrier::ForJSDispatchHandle(host, handle, write_barrier_mode);
  }
}
References v8::internal::RelocInfo::constant_pool_, v8::internal::DCHECK(), v8::internal::WriteBarrier::ForJSDispatchHandle(), v8::internal::handle(), v8::internal::RelocInfo::IsJSDispatchHandle(), jit_allocation_, v8::internal::kNullJSDispatchHandle(), v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, v8::internal::Assembler::set_uint32_constant_at(), and v8::internal::v8_flags.
set_target_address() [1/2]
void v8::internal::WritableRelocInfo::set_target_address (Address target, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED)
Definition at line 286 of file reloc-info.cc.
                                                                              {
  DCHECK(IsCodeTargetMode(rmode_) || IsNearBuiltinEntry(rmode_) ||
         IsWasmCall(rmode_));
  Assembler::set_target_address_at(pc_, constant_pool_, target,
                                   &jit_allocation_, icache_flush_mode);
}
References v8::internal::RelocInfo::constant_pool_, v8::internal::DCHECK(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::RelocInfo::IsNearBuiltinEntry(), v8::internal::RelocInfo::IsWasmCall(), jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, and v8::internal::Assembler::set_target_address_at().
set_target_address() [2/2]
void v8::internal::WritableRelocInfo::set_target_address (Tagged< InstructionStream > host, Address target, WriteBarrierMode write_barrier_mode = UPDATE_WRITE_BARRIER, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED)
Definition at line 294 of file reloc-info.cc.
                                                                              {
  set_target_address(target, icache_flush_mode);
  if (IsCodeTargetMode(rmode_) && !v8_flags.disable_write_barriers) {
    Tagged<InstructionStream> target_code =
        InstructionStream::FromTargetAddress(target);
    WriteBarrier::ForRelocInfo(host, this, target_code, write_barrier_mode);
  }
}
References v8::internal::WriteBarrier::ForRelocInfo(), v8::internal::InstructionStream::FromTargetAddress(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::RelocInfo::rmode_, and v8::internal::v8_flags.
Referenced by v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag(), and v8::internal::UpdateTypedSlotHelper::UpdateCodeTarget().
set_target_external_reference()
void v8::internal::WritableRelocInfo::set_target_external_reference (Address target, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED) [inline]
Definition at line 123 of file assembler-arm-inl.h.
                                                       {
  DCHECK(rmode_ == RelocInfo::EXTERNAL_REFERENCE);
  Assembler::set_target_address_at(pc_, constant_pool_, target,
                                   &jit_allocation_, icache_flush_mode);
}
References v8::internal::RelocInfo::constant_pool_, v8::internal::DCHECK(), v8::internal::RelocInfo::EXTERNAL_REFERENCE, jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, and v8::internal::Assembler::set_target_address_at().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
set_target_object() [1/2]
void v8::internal::WritableRelocInfo::set_target_object (Tagged< HeapObject > target, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED) [inline]
Definition at line 111 of file assembler-arm-inl.h.
                                                                             {
  DCHECK(IsCodeTarget(rmode_) || IsFullEmbeddedObject(rmode_));
  Assembler::set_target_address_at(pc_, constant_pool_, target.ptr(),
                                   &jit_allocation_, icache_flush_mode);
}
References v8::internal::RelocInfo::constant_pool_, v8::internal::DCHECK(), v8::internal::RelocInfo::IsCodeTarget(), v8::internal::RelocInfo::IsFullEmbeddedObject(), jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::RelocInfo::rmode_, and v8::internal::Assembler::set_target_address_at().
set_target_object() [2/2]
void v8::internal::WritableRelocInfo::set_target_object (Tagged< InstructionStream > host, Tagged< HeapObject > target, WriteBarrierMode write_barrier_mode = UPDATE_WRITE_BARRIER, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED) [inline]
Definition at line 42 of file reloc-info-inl.h.
                                                                             {
  set_target_object(target, icache_flush_mode);
  if (!v8_flags.disable_write_barriers) {
    WriteBarrier::ForRelocInfo(host, this, target, write_barrier_mode);
  }
}
References v8::internal::WriteBarrier::ForRelocInfo(), and v8::internal::v8_flags.
Referenced by v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), and v8::internal::UpdateTypedSlotHelper::UpdateEmbeddedPointer().
set_wasm_call_address()
void v8::internal::WritableRelocInfo::set_wasm_call_address (Address address)
Definition at line 258 of file reloc-info.cc.
                                                             {
  DCHECK_EQ(rmode_, WASM_CALL);
  Assembler::set_target_address_at(pc_, constant_pool_, address,
                                   &jit_allocation_, SKIP_ICACHE_FLUSH);
}
References v8::internal::RelocInfo::constant_pool_, DCHECK_EQ, jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, v8::internal::Assembler::set_target_address_at(), v8::internal::SKIP_ICACHE_FLUSH, and v8::internal::RelocInfo::WASM_CALL.
set_wasm_canonical_sig_id()
void v8::internal::WritableRelocInfo::set_wasm_canonical_sig_id (uint32_t canonical_sig_id)
Definition at line 280 of file reloc-info.cc.
                                                                           {
  DCHECK_EQ(rmode_, WASM_CANONICAL_SIG_ID);
  Assembler::set_uint32_constant_at(pc_, constant_pool_, canonical_sig_id,
                                    &jit_allocation_, SKIP_ICACHE_FLUSH);
}
References v8::internal::RelocInfo::constant_pool_, DCHECK_EQ, jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, v8::internal::Assembler::set_uint32_constant_at(), v8::internal::SKIP_ICACHE_FLUSH, and v8::internal::RelocInfo::WASM_CANONICAL_SIG_ID.
set_wasm_code_pointer_table_entry()
void v8::internal::WritableRelocInfo::set_wasm_code_pointer_table_entry (WasmCodePointer target, ICacheFlushMode icache_flush_mode = FLUSH_ICACHE_IF_NEEDED) [inline]
Definition at line 135 of file assembler-arm-inl.h.
                                                               {
  DCHECK(rmode_ == RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY);
  Assembler::set_uint32_constant_at(pc_, constant_pool_, target.value(),
                                    &jit_allocation_, icache_flush_mode);
}
References v8::internal::RelocInfo::constant_pool_, v8::internal::DCHECK(), jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, v8::internal::Assembler::set_uint32_constant_at(), v8::internal::WasmCodePointer::value(), and v8::internal::RelocInfo::WASM_CODE_POINTER_TABLE_ENTRY.
set_wasm_stub_call_address()
void v8::internal::WritableRelocInfo::set_wasm_stub_call_address (Address address)
Definition at line 269 of file reloc-info.cc.
                                                                  {
  DCHECK_EQ(rmode_, WASM_STUB_CALL);
  Assembler::set_target_address_at(pc_, constant_pool_, address,
                                   &jit_allocation_, SKIP_ICACHE_FLUSH);
}
References v8::internal::RelocInfo::constant_pool_, DCHECK_EQ, jit_allocation_, v8::internal::RelocInfo::pc_, v8::internal::RelocInfo::rmode_, v8::internal::Assembler::set_target_address_at(), v8::internal::SKIP_ICACHE_FLUSH, and v8::internal::RelocInfo::WASM_STUB_CALL.
Referenced by v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::SetWasmCalleeTag().
Member Data Documentation
jit_allocation_
WritableJitAllocation& v8::internal::WritableRelocInfo::jit_allocation_ [private]
Definition at line 463 of file reloc-info.h.
Referenced by apply(), jit_allocation(), set_js_dispatch_handle(), set_target_address(), set_target_external_reference(), set_target_object(), set_wasm_call_address(), set_wasm_canonical_sig_id(), set_wasm_code_pointer_table_entry(), and set_wasm_stub_call_address().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/reloc-info.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32-inl.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64-inl.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64-inl.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc-inl.h
/mnt/V8SourceCode/src/codegen/reloc-info-inl.h
/mnt/V8SourceCode/src/codegen/reloc-info.cc
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv-inl.h
/mnt/V8SourceCode/src/codegen/s390/assembler-s390-inl.h
/mnt/V8SourceCode/src/codegen/x64/assembler-x64-inl.h