v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope Class Reference
Public Member Functions
SanitizeIsolateScope (Isolate *isolate, bool allow_active_isolate_for_testing, const DisallowGarbageCollection &no_gc)
~SanitizeIsolateScope ()
Private Attributes
Isolate * isolate_
const Tagged< Object > feedback_vectors_for_profiling_tools_
const Tagged< WeakArrayList > detached_contexts_
Detailed Description
Definition at line 24 of file startup-serializer.cc.
Constructor & Destructor Documentation
SanitizeIsolateScope()
v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::SanitizeIsolateScope (Isolate * isolate, bool allow_active_isolate_for_testing, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 26 of file startup-serializer.cc.
      : isolate_(isolate),
        feedback_vectors_for_profiling_tools_(
            isolate->heap()->feedback_vectors_for_profiling_tools()),
        detached_contexts_(isolate->heap()->detached_contexts()) {
#ifdef DEBUG
    if (!allow_active_isolate_for_testing) {
      // These should already be empty when creating a real snapshot.
      DCHECK_EQ(feedback_vectors_for_profiling_tools_,
                ReadOnlyRoots(isolate).undefined_value());
      DCHECK_EQ(detached_contexts_,
                ReadOnlyRoots(isolate).empty_weak_array_list());
    }
#endif
    isolate->SetFeedbackVectorsForProfilingTools(
        ReadOnlyRoots(isolate).undefined_value());
    isolate->heap()->SetDetachedContexts(
        ReadOnlyRoots(isolate).empty_weak_array_list());
  }
References DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::Heap::SetDetachedContexts(), and v8::internal::Isolate::SetFeedbackVectorsForProfilingTools().
 SanitizeIsolateScope()
v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::~SanitizeIsolateScope () [inline]
Definition at line 48 of file startup-serializer.cc.
                          {
    // Restore saved fields.
    isolate_->SetFeedbackVectorsForProfilingTools(
        feedback_vectors_for_profiling_tools_);
    isolate_->heap()->SetDetachedContexts(detached_contexts_);
  }
Member Data Documentation
detached_contexts_
const Tagged<WeakArrayList> v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::detached_contexts_ [private]
Definition at line 58 of file startup-serializer.cc.
feedback_vectors_for_profiling_tools_
const Tagged<Object> v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::feedback_vectors_for_profiling_tools_ [private]
Definition at line 57 of file startup-serializer.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{startup-serializer.cc}::SanitizeIsolateScope::isolate_ [private]
Definition at line 56 of file startup-serializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/startup-serializer.cc