v8::internal::PlatformEmbeddedFileWriterZOS Class Reference
#include <platform-embedded-file-writer-zos.h>
Public Member Functions
PlatformEmbeddedFileWriterZOS (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os)
void SectionText () override
void SectionRoData () override
void AlignToCodeAlignment () override
void AlignToDataAlignment () override
void DeclareUint32 (const char *name, uint32_t value) override
void DeclareLabel (const char *name) override
void DeclareLabelProlog (const char *name) override
void DeclareLabelEpilogue () override
void SourceInfo (int fileid, const char *filename, int line) override
void DeclareFunctionBegin (const char *name, uint32_t size) override
void DeclareFunctionEnd (const char *name) override
int HexLiteral (uint64_t value) override
void Comment (const char *string) override
void FilePrologue () override
void DeclareExternalFilename (int fileid, const char *filename) override
void FileEpilogue () override
int IndentedDataDirective (DataDirective directive) override
DataDirective ByteChunkDataDirective () const override
int WriteByteChunk (const uint8_t *data) override
Private Member Functions
void DeclareSymbolGlobal (const char *name) override
Private Attributes
const EmbeddedTargetArch target_arch_
const EmbeddedTargetOs target_os_
Additional Inherited Members
Detailed Description
Definition at line 14 of file platform-embedded-file-writer-zos.h.
Constructor & Destructor Documentation
PlatformEmbeddedFileWriterZOS()
v8::internal::PlatformEmbeddedFileWriterZOS::PlatformEmbeddedFileWriterZOS (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os) [inline]
Definition at line 16 of file platform-embedded-file-writer-zos.h.
      : target_arch_(target_arch), target_os_(target_os) {
    USE(target_arch_);
    USE(target_os_);
    DCHECK_EQ(target_os_, EmbeddedTargetOs::kZOS);
  }
References DCHECK_EQ, v8::internal::kZOS, target_arch_, target_os_, and USE.
Member Function Documentation
AlignToCodeAlignment()
void v8::internal::PlatformEmbeddedFileWriterZOS::AlignToCodeAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 91 of file platform-embedded-file-writer-zos.cc.
                                                         {
  // No code alignment required.
}
AlignToDataAlignment()
void v8::internal::PlatformEmbeddedFileWriterZOS::AlignToDataAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 95 of file platform-embedded-file-writer-zos.cc.
                                                         {
  // No data alignment required.
}
ByteChunkDataDirective()
DataDirective v8::internal::PlatformEmbeddedFileWriterZOS::ByteChunkDataDirective () const [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 155 of file platform-embedded-file-writer-zos.cc.
                                                                          {
  return kQuad;
}
References v8::internal::kQuad.
Referenced by WriteByteChunk().
Comment()
void v8::internal::PlatformEmbeddedFileWriterZOS::Comment (const char * string) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 99 of file platform-embedded-file-writer-zos.cc.
                                                              {
  hlasmPrintLine(fp_, "* %s\n", string);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc}::hlasmPrintLine().
DeclareExternalFilename()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareExternalFilename (int fileid, const char * filename) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 142 of file platform-embedded-file-writer-zos.cc.
                                      {
  // Not used.
}
DeclareFunctionBegin()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareFunctionBegin (const char * name, uint32_t size) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 115 of file platform-embedded-file-writer-zos.cc.
                                                                        {
  hlasmPrintLine(fp_, "*--------------------------------------------\n");
  hlasmPrintLine(fp_, "* Builtin %s\n", name);
  hlasmPrintLine(fp_, "*--------------------------------------------\n");
  hlasmPrintLine(fp_, "%s DS 0H\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc}::hlasmPrintLine(), and v8::internal::name.
DeclareFunctionEnd()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareFunctionEnd (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 123 of file platform-embedded-file-writer-zos.cc.
                                                                       {
  // Not used.
}
DeclareLabel()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabel (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 103 of file platform-embedded-file-writer-zos.cc.
                                                                 {
  hlasmPrintLine(fp_, "*--------------------------------------------\n");
  hlasmPrintLine(fp_, "* Label %s\n", name);
  hlasmPrintLine(fp_, "*--------------------------------------------\n");
  hlasmPrintLine(fp_, "%s DS 0H\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc}::hlasmPrintLine(), and v8::internal::name.
DeclareLabelEpilogue()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabelEpilogue () [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 66 of file platform-embedded-file-writer-zos.cc.
                                                         {
  fprintf(fp_,
          "C_WSA64 CATTR PART(PART1)\n"
          "LBL&suffix DC AD(AL&suffix)\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
DeclareLabelProlog()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareLabelProlog (const char * name) [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 56 of file platform-embedded-file-writer-zos.cc.
                                                                       {
  fprintf(fp_,
          "&suffix SETA &suffix+1\n"
          "CEECWSA LOCTR\n"
          "AL&suffix ALIAS C'%s'\n"
          "C_WSA64 CATTR DEFLOAD,RMODE(64),PART(AL&suffix)\n"
          "AL&suffix XATTR REF(DATA),LINKAGE(XPLINK),SCOPE(EXPORT)\n",
          name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::name.
DeclareSymbolGlobal()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareSymbolGlobal (const char * name) [override], [private], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 87 of file platform-embedded-file-writer-zos.cc.
                                                                        {
  hlasmPrintLine(fp_, "* Global Symbol %s\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc}::hlasmPrintLine(), and v8::internal::name.
Referenced by DeclareUint32().
DeclareUint32()
void v8::internal::PlatformEmbeddedFileWriterZOS::DeclareUint32 (const char * name, uint32_t value) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 72 of file platform-embedded-file-writer-zos.cc.
                                                                  {
  DeclareSymbolGlobal(name);
  fprintf(fp_,
          "&suffix SETA &suffix+1\n"
          "CEECWSA LOCTR\n"
          "AL&suffix ALIAS C'%s'\n"
          "C_WSA64 CATTR DEFLOAD,RMODE(64),PART(AL&suffix)\n"
          "AL&suffix XATTR REF(DATA),LINKAGE(XPLINK),SCOPE(EXPORT)\n"
          " DC F'%d'\n"
          "C_WSA64 CATTR PART(PART1)\n"
          "LBL&suffix DC AD(AL&suffix)\n",
          name, value);
}
References DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::name, and v8::internal::value.
FileEpilogue()
void v8::internal::PlatformEmbeddedFileWriterZOS::FileEpilogue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 147 of file platform-embedded-file-writer-zos.cc.
{ fprintf(fp_, " end\n"); }
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
FilePrologue()
void v8::internal::PlatformEmbeddedFileWriterZOS::FilePrologue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 133 of file platform-embedded-file-writer-zos.cc.
                                                 {
  fprintf(fp_,
          "&C SETC 'embed'\n"
          " SYSSTATE AMODE64=YES\n"
          "&C csect\n"
          "&C amode 64\n"
          "&C rmode 64\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
HexLiteral()
int v8::internal::PlatformEmbeddedFileWriterZOS::HexLiteral (uint64_t value) [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 127 of file platform-embedded-file-writer-zos.cc.
                                                            {
  // The cast is because some platforms define uint64_t as unsigned long long,
  // while others (e.g. z/OS) define it as unsigned long.
  return fprintf(fp_, "%.16lx", static_cast<unsigned long>(value));
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::value.
Referenced by WriteByteChunk().
IndentedDataDirective()
int v8::internal::PlatformEmbeddedFileWriterZOS::IndentedDataDirective (DataDirective directive) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 149 of file platform-embedded-file-writer-zos.cc.
                             {
  // Not used.
  return 0;
}
SectionRoData()
void v8::internal::PlatformEmbeddedFileWriterZOS::SectionRoData () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 169 of file platform-embedded-file-writer-zos.cc.
                                                  {
  // Not used.
}
SectionText()
void v8::internal::PlatformEmbeddedFileWriterZOS::SectionText () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 165 of file platform-embedded-file-writer-zos.cc.
                                                {
  // Not used.
}
SourceInfo()
void v8::internal::PlatformEmbeddedFileWriterZOS::SourceInfo (int fileid, const char * filename, int line) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 110 of file platform-embedded-file-writer-zos.cc.
                                                         {
  hlasmPrintLine(fp_, "* line %d \"%s\"\n", line, filename);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::anonymous_namespace{platform-embedded-file-writer-zos.cc}::hlasmPrintLine().
WriteByteChunk()
int v8::internal::PlatformEmbeddedFileWriterZOS::WriteByteChunk (const uint8_t * data) [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 159 of file platform-embedded-file-writer-zos.cc.
                                                                     {
  DCHECK_EQ(ByteChunkDataDirective(), kQuad);
  const uint64_t* quad_ptr = reinterpret_cast<const uint64_t*>(data);
  return HexLiteral(*quad_ptr);
}
References ByteChunkDataDirective(), DCHECK_EQ, HexLiteral(), and v8::internal::kQuad.
Member Data Documentation
target_arch_
const EmbeddedTargetArch v8::internal::PlatformEmbeddedFileWriterZOS::target_arch_ [private]
Definition at line 55 of file platform-embedded-file-writer-zos.h.
Referenced by PlatformEmbeddedFileWriterZOS().
target_os_
const EmbeddedTargetOs v8::internal::PlatformEmbeddedFileWriterZOS::target_os_ [private]
Definition at line 56 of file platform-embedded-file-writer-zos.h.
Referenced by PlatformEmbeddedFileWriterZOS().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-zos.h
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-zos.cc