v8::internal::TracedNodeBlock Class Reference
#include <traced-handles.h>
Classes
struct BaseListTraits
struct ListNode
class NodeIteratorImpl
struct OverallListTraits
struct UsableListTraits
struct YoungListTraits
Public Types
using OverallList = v8::base::DoublyThreadedList< TracedNodeBlock *, OverallListTraits >
using UsableList = v8::base::DoublyThreadedList< TracedNodeBlock *, UsableListTraits >
using YoungList = v8::base::DoublyThreadedList< TracedNodeBlock *, YoungListTraits >
using Iterator = NodeIteratorImpl
Public Member Functions
TracedNode * AllocateNode ()
void FreeNode (TracedNode *node, Address zap_value)
TracedNode * at (TracedNode::IndexType index)
const TracedNode * at (TracedNode::IndexType index) const
const void * nodes_begin_address () const
const void * nodes_end_address () const
TracedHandles & traced_handles () const
Iterator begin ()
Iterator end ()
bool IsFull () const
bool IsEmpty () const
size_t used () const
size_t size_bytes () const
bool InYoungList () const
bool InUsableList () const
bool NeedsReprocessing () const
void SetReprocessing (bool value)
void SetLocallyFreed (TracedNode::IndexType count)
TracedNode::IndexType ConsumeLocallyFreed ()
Static Public Member Functions
static TracedNodeBlock * Create (TracedHandles &)
static void Delete (TracedNodeBlock *)
static TracedNodeBlock & From (TracedNode &node)
static const TracedNodeBlock & From (const TracedNode &node)
Static Public Attributes
static constexpr size_t kMinCapacity = 128
static constexpr size_t kMaxCapacity
static constexpr TracedNode::IndexType kInvalidFreeListNodeIndex = -1
Private Member Functions
TracedNodeBlock (TracedHandles &, TracedNode::IndexType)
Private Attributes
ListNode overall_list_node_
ListNode usable_list_node_
ListNode young_list_node_
TracedHandles & traced_handles_
TracedNode::IndexType used_ = 0
const TracedNode::IndexType capacity_ = 0
TracedNode::IndexType first_free_node_ = 0
TracedNode::IndexType locally_freed_ = 0
bool reprocess_ = false
Detailed Description
Definition at line 113 of file traced-handles.h.
Member Typedef Documentation
Iterator
using v8::internal::TracedNodeBlock::Iterator = NodeIteratorImpl
Definition at line 191 of file traced-handles.h.
OverallList
using v8::internal::TracedNodeBlock::OverallList = v8::base::DoublyThreadedList<TracedNodeBlock*, OverallListTraits>
Definition at line 185 of file traced-handles.h.
UsableList
using v8::internal::TracedNodeBlock::UsableList = v8::base::DoublyThreadedList<TracedNodeBlock*, UsableListTraits>
Definition at line 187 of file traced-handles.h.
YoungList
using v8::internal::TracedNodeBlock::YoungList = v8::base::DoublyThreadedList<TracedNodeBlock*, YoungListTraits>
Definition at line 189 of file traced-handles.h.
Constructor & Destructor Documentation
TracedNodeBlock()
v8::internal::TracedNodeBlock::TracedNodeBlock (TracedHandles & traced_handles, TracedNode::IndexType capacity) [private]
Definition at line 70 of file traced-handles.cc.
    : traced_handles_(traced_handles), capacity_(capacity) {
  for (TracedNode::IndexType i = 0; i < (capacity_ - 1); i++) {
    new (at(i)) TracedNode(i, i + 1);
  }
  new (at(capacity_ - 1)) TracedNode(capacity_ - 1, kInvalidFreeListNodeIndex);
}
References at(), capacity_, and kInvalidFreeListNodeIndex.
Referenced by Create().
Member Function Documentation
AllocateNode()
TracedNode * v8::internal::TracedNodeBlock::AllocateNode () [inline]
Definition at line 17 of file traced-handles-inl.h.
                                          {
  DCHECK_NE(used_, capacity_);
  DCHECK_NE(first_free_node_, kInvalidFreeListNodeIndex);
  auto* node = at(first_free_node_);
  first_free_node_ = node->next_free();
  used_++;
  DCHECK(!node->is_in_use());
  return node;
}
References at(), capacity_, v8::internal::DCHECK(), DCHECK_NE, first_free_node_, kInvalidFreeListNodeIndex, and used_.
Referenced by v8::internal::TracedHandles::AllocateNode().
at() [1/2]
TracedNode* v8::internal::TracedNodeBlock::at (TracedNode::IndexType index) [inline]
Definition at line 220 of file traced-handles.h.
                                            {
    return &(reinterpret_cast<TracedNode*>(this + 1)[index]);
  }
References v8::internal::index.
Referenced by AllocateNode(), at(), nodes_begin_address(), nodes_end_address(), v8::internal::TracedNodeBlock::NodeIteratorImpl::operator*(), and TracedNodeBlock().
at() [2/2]
const TracedNode* v8::internal::TracedNodeBlock::at (TracedNode::IndexType index) const [inline]
Definition at line 223 of file traced-handles.h.
                                                        {
    return const_cast<TracedNodeBlock*>(this)->at(index);
  }
References at(), and v8::internal::index.
begin()
Iterator v8::internal::TracedNodeBlock::begin () [inline]
Definition at line 232 of file traced-handles.h.
{ return Iterator(this); }
ConsumeLocallyFreed()
TracedNode::IndexType v8::internal::TracedNodeBlock::ConsumeLocallyFreed () [inline]
Definition at line 253 of file traced-handles.h.
                                            {
    const auto locally_freed = locally_freed_;
    locally_freed_ = 0;
    return locally_freed;
  }
References locally_freed_.
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects().
Create()
TracedNodeBlock * v8::internal::TracedNodeBlock::Create (TracedHandles & traced_handles) [static]
Definition at line 50 of file traced-handles.cc.
                                                                      {
  static_assert(alignof(TracedNodeBlock) >= alignof(TracedNode));
  static_assert(sizeof(TracedNodeBlock) % alignof(TracedNode) == 0,
                "TracedNodeBlock size is used to auto-align node FAM storage.");
  const size_t min_wanted_size =
      sizeof(TracedNodeBlock) +
      sizeof(TracedNode) * TracedNodeBlock::kMinCapacity;
  const auto raw_result = v8::base::AllocateAtLeast<char>(min_wanted_size);
  const size_t capacity = std::min(
      (raw_result.count - sizeof(TracedNodeBlock)) / sizeof(TracedNode),
      kMaxCapacity);
  CHECK_LT(capacity, std::numeric_limits<TracedNode::IndexType>::max());
  const auto result = std::make_pair(raw_result.ptr, capacity);
  return new (result.first) TracedNodeBlock(
      traced_handles, static_cast<TracedNode::IndexType>(result.second));
}
References CHECK_LT, kMaxCapacity, kMinCapacity, v8::base::internal::result, traced_handles(), and TracedNodeBlock().
Referenced by v8::internal::TracedHandles::RefillUsableNodeBlocks().
Delete()
void v8::internal::TracedNodeBlock::Delete (TracedNodeBlock * block) [static]
Definition at line 68 of file traced-handles.cc.
{ free(block); }
Referenced by v8::internal::TracedHandles::DeleteEmptyBlocks(), and v8::internal::TracedHandles::~TracedHandles().
end()
Iterator v8::internal::TracedNodeBlock::end () [inline]
Definition at line 233 of file traced-handles.h.
{ return Iterator(this, capacity_); }
References capacity_.
FreeNode()
void v8::internal::TracedNodeBlock::FreeNode (TracedNode * node, Address zap_value)
Definition at line 91 of file traced-handles.cc.
                                                                  {
  DCHECK(node->is_in_use());
  node->Release(zap_value);
  DCHECK(!node->is_in_use());
  node->set_next_free(first_free_node_);
  first_free_node_ = node->index();
  used_--;
}
References v8::internal::DCHECK(), first_free_node_, v8::internal::TracedNode::index(), v8::internal::TracedNode::is_in_use(), v8::internal::TracedNode::Release(), v8::internal::TracedNode::set_next_free(), and used_.
From() [1/2]
const TracedNodeBlock & v8::internal::TracedNodeBlock::From (const TracedNode & node) [static]
Definition at line 87 of file traced-handles.cc.
                                                                   {
  return From(const_cast<TracedNode&>(node));
}
References From().
From() [2/2]
TracedNodeBlock & v8::internal::TracedNodeBlock::From (TracedNode & node) [static]
Definition at line 80 of file traced-handles.cc.
                                                       {
  TracedNode* first_node = &node - node.index();
  return *reinterpret_cast<TracedNodeBlock*>(
      reinterpret_cast<uintptr_t>(first_node) - sizeof(TracedNodeBlock));
}
References v8::internal::TracedNode::index().
Referenced by v8::internal::TracedHandles::Copy(), v8::internal::TracedHandles::Destroy(), v8::internal::TracedHandles::FreeNode(), From(), and v8::internal::TracedHandles::Move().
InUsableList()
bool v8::internal::TracedNodeBlock::InUsableList () const [inline]
Definition at line 244 of file traced-handles.h.
{ return UsableListTraits::in_use(this); }
References v8::internal::TracedNodeBlock::BaseListTraits< UsableListTraits >::in_use().
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects().
InYoungList()
bool v8::internal::TracedNodeBlock::InYoungList () const [inline]
Definition at line 243 of file traced-handles.h.
{ return YoungListTraits::in_use(this); }
References v8::internal::TracedNodeBlock::BaseListTraits< YoungListTraits >::in_use().
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects(), v8::internal::TracedHandles::RefillUsableNodeBlocks(), v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::RunImpl(), and v8::internal::TracedHandles::UpdateListOfYoungNodes().
IsEmpty()
bool v8::internal::TracedNodeBlock::IsEmpty () const [inline]
Definition at line 236 of file traced-handles.h.
{ return used_ == 0; }
References used_.
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects(), and v8::internal::TracedHandles::RefillUsableNodeBlocks().
IsFull()
bool v8::internal::TracedNodeBlock::IsFull () const [inline]
Definition at line 235 of file traced-handles.h.
{ return used_ == capacity_; }
References capacity_, and used_.
Referenced by v8::internal::TracedHandles::AllocateNode(), and v8::internal::TracedHandles::ProcessWeakYoungObjects().
NeedsReprocessing()
bool v8::internal::TracedNodeBlock::NeedsReprocessing () const [inline]
Definition at line 246 of file traced-handles.h.
{ return reprocess_; }
References reprocess_.
Referenced by v8::internal::TracedHandles::ProcessWeakYoungObjects().
nodes_begin_address()
const void* v8::internal::TracedNodeBlock::nodes_begin_address () const [inline]
Definition at line 227 of file traced-handles.h.
{ return at(0); }
References at().
nodes_end_address()
const void* v8::internal::TracedNodeBlock::nodes_end_address () const [inline]
Definition at line 228 of file traced-handles.h.
{ return at(capacity_); }
References at(), and capacity_.
SetLocallyFreed()
void v8::internal::TracedNodeBlock::SetLocallyFreed (TracedNode::IndexType count) [inline]
Definition at line 249 of file traced-handles.h.
                                                  {
    DCHECK_EQ(locally_freed_, 0);
    locally_freed_ = count;
  }
References DCHECK_EQ, and locally_freed_.
Referenced by v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ProcessBlock().
SetReprocessing()
void v8::internal::TracedNodeBlock::SetReprocessing (bool value) [inline]
Definition at line 247 of file traced-handles.h.
{ reprocess_ = value; }
References reprocess_, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ProcessBlock(), and v8::internal::TracedHandles::ProcessWeakYoungObjects().
size_bytes()
size_t v8::internal::TracedNodeBlock::size_bytes () const [inline]
Definition at line 239 of file traced-handles.h.
                            {
    return sizeof(*this) + capacity_ * sizeof(TracedNode);
  }
References capacity_.
Referenced by v8::internal::TracedHandles::RefillUsableNodeBlocks().
traced_handles()
TracedHandles& v8::internal::TracedNodeBlock::traced_handles () const [inline]
Definition at line 230 of file traced-handles.h.
{ return traced_handles_; }
References traced_handles_.
Referenced by Create().
used()
size_t v8::internal::TracedNodeBlock::used () const [inline]
Definition at line 237 of file traced-handles.h.
{ return used_; }
References used_.
Referenced by v8::internal::anonymous_namespace{traced-handles.cc}::ClearWeaknessProcessor::ProcessBlock().
Member Data Documentation
capacity_
const TracedNode::IndexType v8::internal::TracedNodeBlock::capacity_ = 0 [private]
Definition at line 267 of file traced-handles.h.
Referenced by AllocateNode(), end(), IsFull(), nodes_end_address(), size_bytes(), and TracedNodeBlock().
first_free_node_
TracedNode::IndexType v8::internal::TracedNodeBlock::first_free_node_ = 0 [private]
Definition at line 268 of file traced-handles.h.
Referenced by AllocateNode(), and FreeNode().
kInvalidFreeListNodeIndex
constexpr TracedNode::IndexType v8::internal::TracedNodeBlock::kInvalidFreeListNodeIndex = -1 [static], [constexpr]
Definition at line 206 of file traced-handles.h.
Referenced by AllocateNode(), and TracedNodeBlock().
kMaxCapacity
constexpr size_t v8::internal::TracedNodeBlock::kMaxCapacity [static], [constexpr]
Initial value:
=
      std::numeric_limits<TracedNode::IndexType>::max() - 1
Definition at line 202 of file traced-handles.h.
Referenced by Create().
kMinCapacity
constexpr size_t v8::internal::TracedNodeBlock::kMinCapacity = 128 [static], [constexpr]
Definition at line 200 of file traced-handles.h.
Referenced by Create().
locally_freed_
TracedNode::IndexType v8::internal::TracedNodeBlock::locally_freed_ = 0 [private]
Definition at line 269 of file traced-handles.h.
Referenced by ConsumeLocallyFreed(), and SetLocallyFreed().
overall_list_node_
ListNode v8::internal::TracedNodeBlock::overall_list_node_ [private]
Definition at line 262 of file traced-handles.h.
Referenced by v8::internal::TracedNodeBlock::OverallListTraits::GetListNode().
reprocess_
bool v8::internal::TracedNodeBlock::reprocess_ = false [private]
Definition at line 270 of file traced-handles.h.
Referenced by NeedsReprocessing(), and SetReprocessing().
traced_handles_
TracedHandles& v8::internal::TracedNodeBlock::traced_handles_ [private]
Definition at line 265 of file traced-handles.h.
Referenced by traced_handles().
usable_list_node_
ListNode v8::internal::TracedNodeBlock::usable_list_node_ [private]
Definition at line 263 of file traced-handles.h.
Referenced by v8::internal::TracedNodeBlock::UsableListTraits::GetListNode().
used_
TracedNode::IndexType v8::internal::TracedNodeBlock::used_ = 0 [private]
Definition at line 266 of file traced-handles.h.
Referenced by AllocateNode(), FreeNode(), IsEmpty(), IsFull(), and used().
young_list_node_
ListNode v8::internal::TracedNodeBlock::young_list_node_ [private]
Definition at line 264 of file traced-handles.h.
Referenced by v8::internal::TracedNodeBlock::YoungListTraits::GetListNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/traced-handles.h
/mnt/V8SourceCode/src/handles/traced-handles-inl.h
/mnt/V8SourceCode/src/handles/traced-handles.cc