heap::base::IncrementalMarkingSchedule Class Reference
#include <incremental-marking-schedule.h>
Classes
struct StepInfo
Public Member Functions
IncrementalMarkingSchedule (const IncrementalMarkingSchedule &)=delete
IncrementalMarkingSchedule & operator= (const IncrementalMarkingSchedule &)=delete
void NotifyIncrementalMarkingStart ()
void NotifyConcurrentMarkingStart ()
void AddMutatorThreadMarkedBytes (size_t)
void AddConcurrentlyMarkedBytes (size_t)
size_t GetNextIncrementalStepDuration (size_t estimated_live_bytes)
StepInfo GetCurrentStepInfo () const
bool ShouldFlushEphemeronPairs ()
v8::base::TimeDelta GetTimeSinceLastConcurrentMarkingUpdate ()
size_t min_marked_bytes_per_step () const
void SetElapsedTimeForTesting (v8::base::TimeDelta)
Static Public Member Functions
static std::unique_ptr< IncrementalMarkingSchedule > Create (bool predictable_schedule=false)
static std::unique_ptr< IncrementalMarkingSchedule > CreateWithMarkedBytesPerStepForTesting (size_t min_marked_bytes_per_step, bool predictable_schedule=false)
Static Public Attributes
static constexpr v8::base::TimeDelta kEstimatedMarkingTime
static constexpr size_t kStepSizeWhenNotMakingProgress = 64 * 1024
Private Member Functions
IncrementalMarkingSchedule (size_t min_marked_bytes_per_step, bool predictable_schedule)
v8::base::TimeDelta GetElapsedTimeSinceMarkingStart ()
size_t GetOverallMarkedBytes () const
size_t GetConcurrentlyMarkedBytes () const
Private Attributes
v8::base::TimeTicks incremental_marking_start_time_
size_t mutator_thread_marked_bytes_ = 0
std::atomic_size_t concurrently_marked_bytes_ {0}
size_t last_estimated_live_bytes_ = 0
double ephemeron_pairs_flushing_ratio_target_ = 0.25
StepInfo current_step_
const size_t min_marked_bytes_per_step_
const bool predictable_schedule_ = false
std::optional< v8::base::TimeDelta > elapsed_time_override_
size_t last_concurrently_marked_bytes_ = 0
v8::base::TimeTicks last_concurrently_marked_bytes_update_
Static Private Attributes
static constexpr double kEphemeronPairsFlushingRatioIncrements = 0.25
Detailed Description
Definition at line 25 of file incremental-marking-schedule.h.
Constructor & Destructor Documentation
IncrementalMarkingSchedule() [1/2]
heap::base::IncrementalMarkingSchedule::IncrementalMarkingSchedule (const IncrementalMarkingSchedule &) [delete]
Referenced by Create(), and CreateWithMarkedBytesPerStepForTesting().
IncrementalMarkingSchedule() [2/2]
heap::base::IncrementalMarkingSchedule::IncrementalMarkingSchedule (size_t min_marked_bytes_per_step, bool predictable_schedule) [private]
Definition at line 39 of file incremental-marking-schedule.cc.
    : min_marked_bytes_per_step_(min_marked_bytes_per_step),
      predictable_schedule_(predictable_schedule) {
  if (predictable_schedule_) {
    elapsed_time_override_.emplace(kTimeDeltaForPredictableSchedule);
  }
}
References elapsed_time_override_, heap::base::anonymous_namespace{incremental-marking-schedule.cc}::kTimeDeltaForPredictableSchedule, and predictable_schedule_.
Member Function Documentation
AddConcurrentlyMarkedBytes()
void heap::base::IncrementalMarkingSchedule::AddConcurrentlyMarkedBytes (size_t marked_bytes)
Definition at line 67 of file incremental-marking-schedule.cc.
                         {
  concurrently_marked_bytes_.fetch_add(marked_bytes, std::memory_order_relaxed);
}
References concurrently_marked_bytes_.
Referenced by cppgc::internal::ConcurrentMarkerBase::AddConcurrentlyMarkedBytes().
AddMutatorThreadMarkedBytes()
void heap::base::IncrementalMarkingSchedule::AddMutatorThreadMarkedBytes (size_t marked_bytes)
Definition at line 62 of file incremental-marking-schedule.cc.
                         {
  mutator_thread_marked_bytes_ += marked_bytes;
}
References mutator_thread_marked_bytes_.
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimits().
Create()
std::unique_ptr< IncrementalMarkingSchedule > heap::base::IncrementalMarkingSchedule::Create (bool predictable_schedule = false) [static]
Definition at line 24 of file incremental-marking-schedule.cc.
                               {
  return std::unique_ptr<IncrementalMarkingSchedule>(
      new IncrementalMarkingSchedule(0, predictable_schedule));
}
References IncrementalMarkingSchedule().
Referenced by v8::internal::CppHeap::InitializeMarking(), and v8::internal::IncrementalMarking::StartMarkingMajor().
CreateWithMarkedBytesPerStepForTesting()
std::unique_ptr< IncrementalMarkingSchedule > heap::base::IncrementalMarkingSchedule::CreateWithMarkedBytesPerStepForTesting (size_t min_marked_bytes_per_step, bool predictable_schedule = false) [static]
Definition at line 32 of file incremental-marking-schedule.cc.
                                                                 {
  return std::unique_ptr<IncrementalMarkingSchedule>(
      new IncrementalMarkingSchedule(min_marked_bytes_per_step,
                                     predictable_schedule));
}
References IncrementalMarkingSchedule(), and min_marked_bytes_per_step().
GetConcurrentlyMarkedBytes()
size_t heap::base::IncrementalMarkingSchedule::GetConcurrentlyMarkedBytes () const [private]
Definition at line 76 of file incremental-marking-schedule.cc.
                                                                    {
  return concurrently_marked_bytes_.load(std::memory_order_relaxed);
}
References concurrently_marked_bytes_.
Referenced by GetNextIncrementalStepDuration(), GetOverallMarkedBytes(), and GetTimeSinceLastConcurrentMarkingUpdate().
GetCurrentStepInfo()
IncrementalMarkingSchedule::StepInfo heap::base::IncrementalMarkingSchedule::GetCurrentStepInfo () const
Definition at line 95 of file incremental-marking-schedule.cc.
                                                     {
  return current_step_;
}
References current_step_.
GetElapsedTimeSinceMarkingStart()
v8::base::TimeDelta heap::base::IncrementalMarkingSchedule::GetElapsedTimeSinceMarkingStart () [private]
Definition at line 81 of file incremental-marking-schedule.cc.
                                                            {
  if (elapsed_time_override_.has_value()) {
    const v8::base::TimeDelta elapsed_time = *elapsed_time_override_;
    if (predictable_schedule_) {
      elapsed_time_override_ = kTimeDeltaForPredictableSchedule;
    } else {
      elapsed_time_override_.reset();
    }
    return elapsed_time;
  }
  return v8::base::TimeTicks::Now() - incremental_marking_start_time_;
}
References elapsed_time_override_, incremental_marking_start_time_, heap::base::anonymous_namespace{incremental-marking-schedule.cc}::kTimeDeltaForPredictableSchedule, v8::base::TimeTicks::Now(), and predictable_schedule_.
Referenced by GetNextIncrementalStepDuration().
GetNextIncrementalStepDuration()
size_t heap::base::IncrementalMarkingSchedule::GetNextIncrementalStepDuration (size_t estimated_live_bytes)
Definition at line 99 of file incremental-marking-schedule.cc.
                                 {
  last_estimated_live_bytes_ = estimated_live_bytes;
  DCHECK(!incremental_marking_start_time_.IsNull());
  const auto elapsed_time = GetElapsedTimeSinceMarkingStart();
  const size_t last_marked_bytes = current_step_.marked_bytes();
  const size_t actual_marked_bytes = GetOverallMarkedBytes();
  const size_t expected_marked_bytes =
      std::ceil(estimated_live_bytes * elapsed_time.InMillisecondsF() /
                kEstimatedMarkingTime.InMillisecondsF());
  // Stash away the current data for others to access.
  current_step_ = {mutator_thread_marked_bytes_, GetConcurrentlyMarkedBytes(),
                   estimated_live_bytes, expected_marked_bytes, elapsed_time};
  if ((actual_marked_bytes >= last_marked_bytes) &&
      (actual_marked_bytes - last_marked_bytes) <
          kStepSizeWhenNotMakingProgress) {
    return std::max(kStepSizeWhenNotMakingProgress, min_marked_bytes_per_step_);
  }
  if (expected_marked_bytes < actual_marked_bytes) {
    // Marking is ahead of schedule, incremental marking should do the minimum.
    return min_marked_bytes_per_step_;
  }
  // Assuming marking will take |kEstimatedMarkingTime|, overall there will
  // be |estimated_live_bytes| live bytes to mark, and that marking speed is
  // constant, after |elapsed_time| the number of marked_bytes should be
  // |estimated_live_bytes| * (|elapsed_time| / |kEstimatedMarkingTime|),
  // denoted as |expected_marked_bytes|. If |actual_marked_bytes| is less,
  // i.e. marking is behind schedule, incremental marking should help "catch
  // up" by marking (|expected_marked_bytes| - |actual_marked_bytes|).
  return std::max(min_marked_bytes_per_step_,
                  expected_marked_bytes - actual_marked_bytes);
}
References current_step_, DCHECK, GetConcurrentlyMarkedBytes(), GetElapsedTimeSinceMarkingStart(), GetOverallMarkedBytes(), incremental_marking_start_time_, v8::base::TimeDelta::InMillisecondsF(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), kEstimatedMarkingTime, kStepSizeWhenNotMakingProgress, last_estimated_live_bytes_, heap::base::IncrementalMarkingSchedule::StepInfo::marked_bytes(), min_marked_bytes_per_step_, and mutator_thread_marked_bytes_.
Referenced by cppgc::internal::anonymous_namespace{marker.cc}::GetNextIncrementalStepDuration().
GetOverallMarkedBytes()
size_t heap::base::IncrementalMarkingSchedule::GetOverallMarkedBytes () const [private]
Definition at line 72 of file incremental-marking-schedule.cc.
                                                               {
  return mutator_thread_marked_bytes_ + GetConcurrentlyMarkedBytes();
}
References GetConcurrentlyMarkedBytes(), and mutator_thread_marked_bytes_.
Referenced by GetNextIncrementalStepDuration(), and ShouldFlushEphemeronPairs().
GetTimeSinceLastConcurrentMarkingUpdate()
v8::base::TimeDelta heap::base::IncrementalMarkingSchedule::GetTimeSinceLastConcurrentMarkingUpdate ()
Definition at line 144 of file incremental-marking-schedule.cc.
                                                                    {
  const size_t current_concurrently_marked_bytes = GetConcurrentlyMarkedBytes();
  if (current_concurrently_marked_bytes > last_concurrently_marked_bytes_) {
    last_concurrently_marked_bytes_ = current_concurrently_marked_bytes;
    last_concurrently_marked_bytes_update_ = v8::base::TimeTicks::Now();
    return {};
  }
  // In case `NotifyConcurrentMarkingStart()` was not called we just return an
  // empty time delta, providing the same signal as making progress.
  if (last_concurrently_marked_bytes_update_.IsNull()) {
    return {};
  }
  return v8::base::TimeTicks::Now() - last_concurrently_marked_bytes_update_;
}
References GetConcurrentlyMarkedBytes(), v8::base::time_internal::TimeBase< TimeClass >::IsNull(), last_concurrently_marked_bytes_, last_concurrently_marked_bytes_update_, and v8::base::TimeTicks::Now().
Referenced by cppgc::internal::ConcurrentMarkerBase::IncreaseMarkingPriorityIfNeeded().
min_marked_bytes_per_step()
size_t heap::base::IncrementalMarkingSchedule::min_marked_bytes_per_step () const [inline]
Definition at line 108 of file incremental-marking-schedule.h.
                                           {
    return min_marked_bytes_per_step_;
  }
Referenced by CreateWithMarkedBytesPerStepForTesting().
NotifyConcurrentMarkingStart()
void heap::base::IncrementalMarkingSchedule::NotifyConcurrentMarkingStart ()
Definition at line 55 of file incremental-marking-schedule.cc.
                                                              {
  if (!last_concurrently_marked_bytes_update_.IsNull()) {
    return;
  }
  last_concurrently_marked_bytes_update_ = v8::base::TimeTicks::Now();
}
References v8::base::time_internal::TimeBase< TimeClass >::IsNull(), last_concurrently_marked_bytes_update_, and v8::base::TimeTicks::Now().
Referenced by cppgc::internal::ConcurrentMarkerBase::Start().
NotifyIncrementalMarkingStart()
void heap::base::IncrementalMarkingSchedule::NotifyIncrementalMarkingStart ()
Definition at line 48 of file incremental-marking-schedule.cc.
                                                               {
  if (!incremental_marking_start_time_.IsNull()) {
    return;
  }
  incremental_marking_start_time_ = v8::base::TimeTicks::Now();
}
References incremental_marking_start_time_, v8::base::time_internal::TimeBase< TimeClass >::IsNull(), and v8::base::TimeTicks::Now().
Referenced by cppgc::internal::MarkerBase::StartMarking().
operator=()
IncrementalMarkingSchedule& heap::base::IncrementalMarkingSchedule::operator= (const IncrementalMarkingSchedule &) [delete]
SetElapsedTimeForTesting()
void heap::base::IncrementalMarkingSchedule::SetElapsedTimeForTesting (v8::base::TimeDelta elapsed_time)
Definition at line 159 of file incremental-marking-schedule.cc.
                                  {
  elapsed_time_override_.emplace(elapsed_time);
}
References elapsed_time_override_.
ShouldFlushEphemeronPairs()
bool heap::base::IncrementalMarkingSchedule::ShouldFlushEphemeronPairs ()
Definition at line 134 of file incremental-marking-schedule.cc.
                                                           {
  if (GetOverallMarkedBytes() <
      (ephemeron_pairs_flushing_ratio_target_ * last_estimated_live_bytes_))
    return false;
  ephemeron_pairs_flushing_ratio_target_ +=
      kEphemeronPairsFlushingRatioIncrements;
  return true;
}
References ephemeron_pairs_flushing_ratio_target_, GetOverallMarkedBytes(), kEphemeronPairsFlushingRatioIncrements, and last_estimated_live_bytes_.
Member Data Documentation
concurrently_marked_bytes_
std::atomic_size_t heap::base::IncrementalMarkingSchedule::concurrently_marked_bytes_ {0} [private]
Definition at line 134 of file incremental-marking-schedule.h.
Referenced by AddConcurrentlyMarkedBytes(), and GetConcurrentlyMarkedBytes().
current_step_
StepInfo heap::base::IncrementalMarkingSchedule::current_step_ [private]
Definition at line 137 of file incremental-marking-schedule.h.
Referenced by GetCurrentStepInfo(), and GetNextIncrementalStepDuration().
elapsed_time_override_
std::optional<v8::base::TimeDelta> heap::base::IncrementalMarkingSchedule::elapsed_time_override_ [private]
Definition at line 140 of file incremental-marking-schedule.h.
Referenced by GetElapsedTimeSinceMarkingStart(), IncrementalMarkingSchedule(), and SetElapsedTimeForTesting().
ephemeron_pairs_flushing_ratio_target_
double heap::base::IncrementalMarkingSchedule::ephemeron_pairs_flushing_ratio_target_ = 0.25 [private]
Definition at line 136 of file incremental-marking-schedule.h.
Referenced by ShouldFlushEphemeronPairs().
incremental_marking_start_time_
v8::base::TimeTicks heap::base::IncrementalMarkingSchedule::incremental_marking_start_time_ [private]
Definition at line 132 of file incremental-marking-schedule.h.
Referenced by GetElapsedTimeSinceMarkingStart(), GetNextIncrementalStepDuration(), and NotifyIncrementalMarkingStart().
kEphemeronPairsFlushingRatioIncrements
constexpr double heap::base::IncrementalMarkingSchedule::kEphemeronPairsFlushingRatioIncrements = 0.25 [static], [constexpr], [private]
Definition at line 117 of file incremental-marking-schedule.h.
Referenced by ShouldFlushEphemeronPairs().
kEstimatedMarkingTime
constexpr v8::base::TimeDelta heap::base::IncrementalMarkingSchedule::kEstimatedMarkingTime [static], [constexpr]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(500)
Definition at line 51 of file incremental-marking-schedule.h.
Referenced by cppgc::internal::HeapGrowing::HeapGrowingImpl::ConfigureLimit(), GetNextIncrementalStepDuration(), and cppgc::internal::ConcurrentMarkerBase::IncreaseMarkingPriorityIfNeeded().
kStepSizeWhenNotMakingProgress
constexpr size_t heap::base::IncrementalMarkingSchedule::kStepSizeWhenNotMakingProgress = 64 * 1024 [static], [constexpr]
Definition at line 56 of file incremental-marking-schedule.h.
Referenced by GetNextIncrementalStepDuration().
last_concurrently_marked_bytes_
size_t heap::base::IncrementalMarkingSchedule::last_concurrently_marked_bytes_ = 0 [private]
Definition at line 141 of file incremental-marking-schedule.h.
Referenced by GetTimeSinceLastConcurrentMarkingUpdate().
last_concurrently_marked_bytes_update_
v8::base::TimeTicks heap::base::IncrementalMarkingSchedule::last_concurrently_marked_bytes_update_ [private]
Definition at line 142 of file incremental-marking-schedule.h.
Referenced by GetTimeSinceLastConcurrentMarkingUpdate(), and NotifyConcurrentMarkingStart().
last_estimated_live_bytes_
size_t heap::base::IncrementalMarkingSchedule::last_estimated_live_bytes_ = 0 [private]
Definition at line 135 of file incremental-marking-schedule.h.
Referenced by GetNextIncrementalStepDuration(), and ShouldFlushEphemeronPairs().
min_marked_bytes_per_step_
const size_t heap::base::IncrementalMarkingSchedule::min_marked_bytes_per_step_ [private]
Definition at line 138 of file incremental-marking-schedule.h.
Referenced by GetNextIncrementalStepDuration().
mutator_thread_marked_bytes_
size_t heap::base::IncrementalMarkingSchedule::mutator_thread_marked_bytes_ = 0 [private]
Definition at line 133 of file incremental-marking-schedule.h.
Referenced by AddMutatorThreadMarkedBytes(), GetNextIncrementalStepDuration(), and GetOverallMarkedBytes().
predictable_schedule_
const bool heap::base::IncrementalMarkingSchedule::predictable_schedule_ = false [private]
Definition at line 139 of file incremental-marking-schedule.h.
Referenced by GetElapsedTimeSinceMarkingStart(), and IncrementalMarkingSchedule().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/base/incremental-marking-schedule.h
/mnt/V8SourceCode/src/heap/base/incremental-marking-schedule.cc