v8::internal::interpreter::StoreLookupSlotFlags Class Reference
#include <bytecode-flags-and-tokens.h>
Public Types
using LanguageModeBit = base::BitField8< LanguageMode, 0, 1 >
using LookupHoistingModeBit = LanguageModeBit::Next< bool, 1 >
Static Public Member Functions
static uint8_t Encode (LanguageMode language_mode, LookupHoistingMode lookup_hoisting_mode)
static LanguageMode GetLanguageMode (uint8_t flags)
static bool IsLookupHoistingMode (uint8_t flags)
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (StoreLookupSlotFlags)
Detailed Description
Definition at line 84 of file bytecode-flags-and-tokens.h.
Member Typedef Documentation
LanguageModeBit
using v8::internal::interpreter::StoreLookupSlotFlags::LanguageModeBit = base::BitField8<LanguageMode, 0, 1>
Definition at line 86 of file bytecode-flags-and-tokens.h.
LookupHoistingModeBit
using v8::internal::interpreter::StoreLookupSlotFlags::LookupHoistingModeBit = LanguageModeBit::Next<bool, 1>
Definition at line 87 of file bytecode-flags-and-tokens.h.
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::interpreter::StoreLookupSlotFlags::DISALLOW_IMPLICIT_CONSTRUCTORS (StoreLookupSlotFlags) [private]
Encode()
uint8_t v8::internal::interpreter::StoreLookupSlotFlags::Encode (LanguageMode language_mode, LookupHoistingMode lookup_hoisting_mode) [static]
Definition at line 91 of file bytecode-flags-and-tokens.cc.
                                                                              {
  DCHECK_IMPLIES(lookup_hoisting_mode == LookupHoistingMode::kLegacySloppy,
                 language_mode == LanguageMode::kSloppy);
  return LanguageModeBit::encode(language_mode) |
         LookupHoistingModeBit::encode(static_cast<bool>(lookup_hoisting_mode));
}
References DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::kLegacySloppy, and v8::internal::kSloppy.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::StoreLookupSlot().
GetLanguageMode()
LanguageMode v8::internal::interpreter::StoreLookupSlotFlags::GetLanguageMode (uint8_t flags) [static]
Definition at line 100 of file bytecode-flags-and-tokens.cc.
                                                                {
  return LanguageModeBit::decode(flags);
}
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::flags.
IsLookupHoistingMode()
bool v8::internal::interpreter::StoreLookupSlotFlags::IsLookupHoistingMode (uint8_t flags) [static]
Definition at line 105 of file bytecode-flags-and-tokens.cc.
                                                             {
  return LookupHoistingModeBit::decode(flags);
}
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-flags-and-tokens.h
/mnt/V8SourceCode/src/interpreter/bytecode-flags-and-tokens.cc