v8::internal::JSGlobalObject Class Reference
#include <js-objects.h>
Public Member Functions
bool IsDetached (Isolate *isolate)
Tagged< NativeContext > native_context ()
Static Public Member Functions
static void InvalidatePropertyCell (DirectHandle< JSGlobalObject > object, DirectHandle< Name > name)
Detailed Description
Definition at line 1203 of file js-objects.h.
Member Function Documentation
InvalidatePropertyCell()
void v8::internal::JSGlobalObject::InvalidatePropertyCell (DirectHandle< JSGlobalObject > object, DirectHandle< Name > name) [static]
Definition at line 5685 of file js-objects.cc.
                                                                     {
  Isolate* isolate = Isolate::Current();
  // Regardless of whether the property is there or not invalidate
  // Load/StoreGlobalICs that load/store through global object's prototype.
  JSObject::InvalidatePrototypeValidityCell(*global);
  DCHECK(!global->HasFastProperties());
  auto dictionary =
      direct_handle(global->global_dictionary(kAcquireLoad), isolate);
  InternalIndex entry = dictionary->FindEntry(isolate, name);
  if (entry.is_not_found()) return;
  DirectHandle<PropertyCell> cell(dictionary->CellAt(entry), isolate);
  DirectHandle<Object> value(cell->value(), isolate);
  PropertyDetails details = cell->property_details();
  details = details.set_cell_type(PropertyCellType::kMutable);
  PropertyCell::InvalidateAndReplaceEntry(isolate, dictionary, entry, details,
                                          value);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::PropertyCell::InvalidateAndReplaceEntry(), v8::internal::JSObject::InvalidatePrototypeValidityCell(), v8::internal::InternalIndex::is_not_found(), v8::kAcquireLoad, v8::internal::kMutable, v8::internal::name, v8::internal::PropertyDetails::set_cell_type(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{execution.cc}::NewScriptContext().
IsDetached()
bool v8::internal::JSGlobalObject::IsDetached (Isolate * isolate) [inline]
Definition at line 1013 of file js-objects-inl.h.
                                                {
  return global_proxy()->IsDetachedFrom(isolate, *this);
}
native_context()
Tagged< NativeContext > v8::internal::JSGlobalObject::native_context () [inline]
Definition at line 1009 of file js-objects-inl.h.
                                                     {
  return *GetCreationContext();
}
References v8::debug::GetCreationContext().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-objects.h
/mnt/V8SourceCode/src/objects/js-objects-inl.h
/mnt/V8SourceCode/src/objects/js-objects.cc