v8::internal::ProxiesCodeStubAssembler Class Reference
#include <builtins-proxy-gen.h>
Public Types
enum ProxyRevokeFunctionContextSlot { kProxySlot = Context::MIN_CONTEXT_SLOTS
, kProxyContextLength
 }
Public Member Functions
ProxiesCodeStubAssembler (compiler::CodeAssemblerState *state)
TNode< JSProxy > AllocateProxy (TNode< Context > context, TNode< JSReceiver > target, TNode< JSReceiver > handler, TNode< Int32T > flags)
TNode< JSFunction > AllocateProxyRevokeFunction (TNode< Context > context, TNode< JSProxy > proxy)
void CheckGetSetTrapResult (TNode< Context > context, TNode< JSReceiver > target, TNode< JSProxy > proxy, TNode< Name > name, TNode< Object > trap_result, JSProxy::AccessKind access_kind)
void CheckHasTrapResult (TNode< Context > context, TNode< JSReceiver > target, TNode< JSProxy > proxy, TNode< Name > name)
void CheckDeleteTrapResult (TNode< Context > context, TNode< JSReceiver > target, TNode< JSProxy > proxy, TNode< Name > name)
Private Member Functions
TNode< Context > CreateProxyRevokeFunctionContext (TNode< JSProxy > proxy, TNode< NativeContext > native_context)
Additional Inherited Members
Detailed Description
Definition at line 14 of file builtins-proxy-gen.h.
Member Enumeration Documentation
ProxyRevokeFunctionContextSlot
enum v8::internal::ProxiesCodeStubAssembler::ProxyRevokeFunctionContextSlot
Enumerator
kProxySlot
kProxyContextLength
Definition at line 35 of file builtins-proxy-gen.h.
                                      {
    kProxySlot = Context::MIN_CONTEXT_SLOTS,
    kProxyContextLength,
  };
Constructor & Destructor Documentation
ProxiesCodeStubAssembler()
v8::internal::ProxiesCodeStubAssembler::ProxiesCodeStubAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 16 of file builtins-proxy-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
AllocateProxy()
TNode< JSProxy > v8::internal::ProxiesCodeStubAssembler::AllocateProxy (TNode< Context > context, TNode< JSReceiver > target, TNode< JSReceiver > handler, TNode< Int32T > flags)
Definition at line 22 of file builtins-proxy-gen.cc.
                         {
  TVARIABLE(Map, map);
  Label callable_target(this), constructor_target(this), none_target(this),
      create_proxy(this);
  TNode<NativeContext> nativeContext = LoadNativeContext(context);
  Branch(IsCallable(target), &callable_target, &none_target);
  BIND(&callable_target);
  {
    // Every object that is a constructor is implicitly callable
    // so it's okay to nest this check here
    GotoIf(IsConstructor(target), &constructor_target);
    map = CAST(LoadContextElementNoCell(nativeContext,
                                        Context::PROXY_CALLABLE_MAP_INDEX));
    Goto(&create_proxy);
  }
  BIND(&constructor_target);
  {
    map = CAST(LoadContextElementNoCell(nativeContext,
                                        Context::PROXY_CONSTRUCTOR_MAP_INDEX));
    Goto(&create_proxy);
  }
  BIND(&none_target);
  {
    map =
        CAST(LoadContextElementNoCell(nativeContext, Context::PROXY_MAP_INDEX));
    Goto(&create_proxy);
  }
  BIND(&create_proxy);
  TNode<HeapObject> proxy = Allocate(JSProxy::kSize);
  StoreMapNoWriteBarrier(proxy, map.value());
  RootIndex empty_dict = V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL
                             ? RootIndex::kEmptySwissPropertyDictionary
                             : RootIndex::kEmptyPropertyDictionary;
  StoreObjectFieldRoot(proxy, JSProxy::kPropertiesOrHashOffset, empty_dict);
  StoreObjectFieldNoWriteBarrier(proxy, JSProxy::kTargetOffset, target);
  StoreObjectFieldNoWriteBarrier(proxy, JSProxy::kHandlerOffset, handler);
  StoreObjectFieldNoWriteBarrier(proxy, JSProxy::kFlagsOffset, flags);
  return CAST(proxy);
}
References v8::internal::CodeStubAssembler::Allocate(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsCallable(), v8::internal::CodeStubAssembler::IsConstructor(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldRoot(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
AllocateProxyRevokeFunction()
TNode< JSFunction > v8::internal::ProxiesCodeStubAssembler::AllocateProxyRevokeFunction (TNode< Context > context, TNode< JSProxy > proxy)
Definition at line 79 of file builtins-proxy-gen.cc.
                                                  {
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<Context> proxy_context =
      CreateProxyRevokeFunctionContext(proxy, native_context);
  return AllocateRootFunctionWithContext(RootIndex::kProxyRevokeSharedFun,
                                         proxy_context, native_context);
}
References v8::internal::CodeStubAssembler::AllocateRootFunctionWithContext(), CreateProxyRevokeFunctionContext(), v8::internal::CodeStubAssembler::LoadNativeContext(), and v8::internal::native_context.
CheckDeleteTrapResult()
void v8::internal::ProxiesCodeStubAssembler::CheckDeleteTrapResult (TNode< Context > context, TNode< JSReceiver > target, TNode< JSProxy > proxy, TNode< Name > name)
Definition at line 371 of file builtins-proxy-gen.cc.
                                                                       {
  TNode<Map> target_map = LoadMap(target);
  TVARIABLE(Object, var_value);
  TVARIABLE(Uint32T, var_details);
  TVARIABLE(Object, var_raw_value);
  Label if_found_value(this, Label::kDeferred),
      throw_non_configurable(this, Label::kDeferred),
      throw_non_extensible(this, Label::kDeferred), check_passed(this),
      check_in_runtime(this, Label::kDeferred);
  // 10. Let targetDesc be ? target.[[GetOwnProperty]](P).
  GotoIfNot(IsUniqueNameNoIndex(name), &check_in_runtime);
  TNode<Uint16T> instance_type = LoadInstanceType(target);
  TryGetOwnProperty(context, target, target, target_map, instance_type, name,
                    &if_found_value, &var_value, &var_details, &var_raw_value,
                    &check_passed, &check_in_runtime, kReturnAccessorPair);
  // 11. If targetDesc is undefined, return true.
  BIND(&if_found_value);
  {
    // 12. If targetDesc.[[Configurable]] is false, throw a TypeError exception.
    TNode<BoolT> non_configurable = IsSetWord32(
        var_details.value(), PropertyDetails::kAttributesDontDeleteMask);
    GotoIf(non_configurable, &throw_non_configurable);
    // 13. Let extensibleTarget be ? IsExtensible(target).
    TNode<BoolT> target_extensible = IsExtensibleMap(target_map);
    // 14. If extensibleTarget is false, throw a TypeError exception.
    GotoIfNot(target_extensible, &throw_non_extensible);
    Goto(&check_passed);
  }
  BIND(&throw_non_configurable);
  {
    ThrowTypeError(context,
                   MessageTemplate::kProxyDeletePropertyNonConfigurable, name);
  }
  BIND(&throw_non_extensible);
  {
    ThrowTypeError(context, MessageTemplate::kProxyDeletePropertyNonExtensible,
                   name);
  }
  BIND(&check_in_runtime);
  {
    CallRuntime(Runtime::kCheckProxyDeleteTrapResult, context, name, target);
    Goto(&check_passed);
  }
  BIND(&check_passed);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsExtensibleMap(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::CodeStubAssembler::IsUniqueNameNoIndex(), v8::internal::PropertyDetails::kAttributesDontDeleteMask, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::kReturnAccessorPair, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::name, v8::internal::CodeStubAssembler::ThrowTypeError(), and v8::internal::CodeStubAssembler::TryGetOwnProperty().
CheckGetSetTrapResult()
void v8::internal::ProxiesCodeStubAssembler::CheckGetSetTrapResult (TNode< Context > context, TNode< JSReceiver > target, TNode< JSProxy > proxy, TNode< Name > name, TNode< Object > trap_result, JSProxy::AccessKind access_kind)
Definition at line 211 of file builtins-proxy-gen.cc.
                                   {
  // TODO(mslekova): Think of a better name for the trap_result param.
  TNode<Map> map = LoadMap(target);
  TVARIABLE(Object, var_value);
  TVARIABLE(Uint32T, var_details);
  TVARIABLE(Object, var_raw_value);
  Label if_found_value(this), check_in_runtime(this, Label::kDeferred),
      check_passed(this);
  GotoIfNot(IsUniqueNameNoIndex(name), &check_in_runtime);
  TNode<Uint16T> instance_type = LoadInstanceType(target);
  TryGetOwnProperty(context, target, target, map, instance_type, name,
                    &if_found_value, &var_value, &var_details, &var_raw_value,
                    &check_passed, &check_in_runtime, kReturnAccessorPair);
  BIND(&if_found_value);
  {
    Label throw_non_configurable_data(this, Label::kDeferred),
        throw_non_configurable_accessor(this, Label::kDeferred),
        check_accessor(this), check_data(this);
    // If targetDesc is not undefined and targetDesc.[[Configurable]] is
    // false, then:
    GotoIfNot(IsSetWord32(var_details.value(),
                          PropertyDetails::kAttributesDontDeleteMask),
              &check_passed);
    // If IsDataDescriptor(targetDesc) is true and
    // targetDesc.[[Writable]] is false, then:
    BranchIfAccessorPair(var_raw_value.value(), &check_accessor, &check_data);
    BIND(&check_data);
    {
      TNode<BoolT> read_only = IsSetWord32(
          var_details.value(), PropertyDetails::kAttributesReadOnlyMask);
      GotoIfNot(read_only, &check_passed);
      // If SameValue(trapResult, targetDesc.[[Value]]) is false,
      // throw a TypeError exception.
      BranchIfSameValue(trap_result, var_value.value(), &check_passed,
                        &throw_non_configurable_data);
    }
    BIND(&check_accessor);
    {
      TNode<HeapObject> accessor_pair = CAST(var_raw_value.value());
      if (access_kind == JSProxy::kGet) {
        Label continue_check(this, Label::kDeferred);
        // 10.b. If IsAccessorDescriptor(targetDesc) is true and
        // targetDesc.[[Get]] is undefined, then:
        TNode<Object> getter = LoadAccessorPairGetter(CAST(accessor_pair));
        // Here we check for null as well because if the getter was never
        // defined it's set as null.
        GotoIf(IsUndefined(getter), &continue_check);
        GotoIf(IsNull(getter), &continue_check);
        Goto(&check_passed);
        // 10.b.i. If trapResult is not undefined, throw a TypeError exception.
        BIND(&continue_check);
        GotoIfNot(IsUndefined(trap_result), &throw_non_configurable_accessor);
      } else {
        // 11.b.i. If targetDesc.[[Set]] is undefined, throw a TypeError
        // exception.
        TNode<Object> setter = LoadAccessorPairSetter(CAST(accessor_pair));
        GotoIf(IsUndefined(setter), &throw_non_configurable_accessor);
        GotoIf(IsNull(setter), &throw_non_configurable_accessor);
      }
      Goto(&check_passed);
    }
    BIND(&throw_non_configurable_data);
    {
      if (access_kind == JSProxy::kGet) {
        ThrowTypeError(context, MessageTemplate::kProxyGetNonConfigurableData,
                       name, var_value.value(), trap_result);
      } else {
        ThrowTypeError(context, MessageTemplate::kProxySetFrozenData, name);
      }
    }
    BIND(&throw_non_configurable_accessor);
    {
      if (access_kind == JSProxy::kGet) {
        ThrowTypeError(context,
                       MessageTemplate::kProxyGetNonConfigurableAccessor, name,
                       trap_result);
      } else {
        ThrowTypeError(context, MessageTemplate::kProxySetFrozenAccessor, name);
      }
    }
    BIND(&check_in_runtime);
    {
      CallRuntime(Runtime::kCheckProxyGetSetTrapResult, context, name, target,
                  trap_result, SmiConstant(access_kind));
      Goto(&check_passed);
    }
    BIND(&check_passed);
  }
}
References v8::internal::CodeStubAssembler::BranchIfAccessorPair(), v8::internal::CodeStubAssembler::BranchIfSameValue(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::IsNull(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::CodeStubAssembler::IsUniqueNameNoIndex(), v8::internal::PropertyDetails::kAttributesDontDeleteMask, v8::internal::PropertyDetails::kAttributesReadOnlyMask, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::JSProxy::kGet, v8::internal::CodeStubAssembler::kReturnAccessorPair, v8::internal::CodeStubAssembler::LoadAccessorPairGetter(), v8::internal::CodeStubAssembler::LoadAccessorPairSetter(), v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::name, v8::internal::setter, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::ThrowTypeError(), and v8::internal::CodeStubAssembler::TryGetOwnProperty().
CheckHasTrapResult()
void v8::internal::ProxiesCodeStubAssembler::CheckHasTrapResult (TNode< Context > context, TNode< JSReceiver > target, TNode< JSProxy > proxy, TNode< Name > name)
Definition at line 318 of file builtins-proxy-gen.cc.
                                                                    {
  TNode<Map> target_map = LoadMap(target);
  TVARIABLE(Object, var_value);
  TVARIABLE(Uint32T, var_details);
  TVARIABLE(Object, var_raw_value);
  Label if_found_value(this, Label::kDeferred),
      throw_non_configurable(this, Label::kDeferred),
      throw_non_extensible(this, Label::kDeferred), check_passed(this),
      check_in_runtime(this, Label::kDeferred);
  // 9.a. Let targetDesc be ? target.[[GetOwnProperty]](P).
  GotoIfNot(IsUniqueNameNoIndex(name), &check_in_runtime);
  TNode<Uint16T> instance_type = LoadInstanceType(target);
  TryGetOwnProperty(context, target, target, target_map, instance_type, name,
                    &if_found_value, &var_value, &var_details, &var_raw_value,
                    &check_passed, &check_in_runtime, kReturnAccessorPair);
  // 9.b. If targetDesc is not undefined, then (see 9.b.i. below).
  BIND(&if_found_value);
  {
    // 9.b.i. If targetDesc.[[Configurable]] is false, throw a TypeError
    // exception.
    TNode<BoolT> non_configurable = IsSetWord32(
        var_details.value(), PropertyDetails::kAttributesDontDeleteMask);
    GotoIf(non_configurable, &throw_non_configurable);
    // 9.b.ii. Let extensibleTarget be ? IsExtensible(target).
    TNode<BoolT> target_extensible = IsExtensibleMap(target_map);
    // 9.b.iii. If extensibleTarget is false, throw a TypeError exception.
    GotoIfNot(target_extensible, &throw_non_extensible);
    Goto(&check_passed);
  }
  BIND(&throw_non_configurable);
  { ThrowTypeError(context, MessageTemplate::kProxyHasNonConfigurable, name); }
  BIND(&throw_non_extensible);
  { ThrowTypeError(context, MessageTemplate::kProxyHasNonExtensible, name); }
  BIND(&check_in_runtime);
  {
    CallRuntime(Runtime::kCheckProxyHasTrapResult, context, name, target);
    Goto(&check_passed);
  }
  BIND(&check_passed);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsExtensibleMap(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::CodeStubAssembler::IsUniqueNameNoIndex(), v8::internal::PropertyDetails::kAttributesDontDeleteMask, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::kReturnAccessorPair, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::name, v8::internal::CodeStubAssembler::ThrowTypeError(), and v8::internal::CodeStubAssembler::TryGetOwnProperty().
CreateProxyRevokeFunctionContext()
TNode< Context > v8::internal::ProxiesCodeStubAssembler::CreateProxyRevokeFunctionContext (TNode< JSProxy > proxy, TNode< NativeContext > native_context) [private]
Definition at line 70 of file builtins-proxy-gen.cc.
                                                               {
  const TNode<Context> context = AllocateSyntheticFunctionContext(
      native_context, ProxyRevokeFunctionContextSlot::kProxyContextLength);
  StoreContextElementNoWriteBarrier(
      context, ProxyRevokeFunctionContextSlot::kProxySlot, proxy);
  return context;
}
References v8::internal::native_context, and v8::internal::CodeStubAssembler::StoreContextElementNoWriteBarrier().
Referenced by AllocateProxyRevokeFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-proxy-gen.h
/mnt/V8SourceCode/src/builtins/builtins-proxy-gen.cc