v8::internal::wasm::TryTableIterator< ValidationTag > Class Template Reference
#include <function-body-decoder-impl.h>
Public Member Functions
uint32_t cur_index () const
bool has_next () const
CatchCase next ()
uint32_t length () const
const uint8_t * pc () const
TryTableIterator (Decoder *decoder, const TryTableImmediate &imm)
Private Attributes
Decoder *const decoder_
const uint8_t *const start_
const uint8_t * pc_
uint32_t index_ = 0
const uint32_t table_count_
Detailed Description
template<typename ValidationTag>
class v8::internal::wasm::TryTableIterator< ValidationTag >
Definition at line 955 of file function-body-decoder-impl.h.
Constructor & Destructor Documentation
TryTableIterator()
template<typename ValidationTag >
v8::internal::wasm::TryTableIterator< ValidationTag >::TryTableIterator (Decoder * decoder, const TryTableImmediate & imm) [inline]
Definition at line 985 of file function-body-decoder-impl.h.
      : decoder_(decoder),
        start_(imm.start),
        pc_(imm.table),
        table_count_(imm.table_count) {}
Member Function Documentation
cur_index()
template<typename ValidationTag >
uint32_t v8::internal::wasm::TryTableIterator< ValidationTag >::cur_index () const [inline]
Definition at line 957 of file function-body-decoder-impl.h.
{ return index_; }
References v8::internal::wasm::TryTableIterator< ValidationTag >::index_.
has_next()
template<typename ValidationTag >
bool v8::internal::wasm::TryTableIterator< ValidationTag >::has_next () const [inline]
Definition at line 958 of file function-body-decoder-impl.h.
                        {
    return VALIDATE(decoder_->ok()) && index_ < table_count_;
  }
References v8::internal::wasm::TryTableIterator< ValidationTag >::decoder_, v8::internal::wasm::TryTableIterator< ValidationTag >::index_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::TryTableIterator< ValidationTag >::table_count_, and VALIDATE.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::TryTableIterator< ValidationTag >::length(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
length()
template<typename ValidationTag >
uint32_t v8::internal::wasm::TryTableIterator< ValidationTag >::length () const [inline]
Definition at line 979 of file function-body-decoder-impl.h.
                          {
    DCHECK(!has_next());
    return static_cast<uint32_t>(pc_ - start_);
  }
References v8::internal::DCHECK(), v8::internal::wasm::TryTableIterator< ValidationTag >::has_next(), v8::internal::wasm::TryTableIterator< ValidationTag >::pc_, and v8::internal::wasm::TryTableIterator< ValidationTag >::start_.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
next()
template<typename ValidationTag >
CatchCase v8::internal::wasm::TryTableIterator< ValidationTag >::next () [inline]
Definition at line 962 of file function-body-decoder-impl.h.
                   {
    uint8_t kind =
        static_cast<CatchKind>(decoder_->read_u8<ValidationTag>(pc_));
    pc_ += 1;
    CatchCase::MaybeTagIndex maybe_tag{0};
    if (kind == kCatch || kind == kCatchRef) {
      maybe_tag.tag_imm = TagIndexImmediate(decoder_, pc_, ValidationTag{});
      pc_ += maybe_tag.tag_imm.length;
    }
    BranchDepthImmediate br_imm(decoder_, pc_, ValidationTag{});
    pc_ += br_imm.length;
    index_++;
    return CatchCase{static_cast<CatchKind>(kind), maybe_tag, br_imm};
  }
References v8::internal::wasm::TryTableIterator< ValidationTag >::decoder_, v8::internal::wasm::TryTableIterator< ValidationTag >::index_, v8::internal::wasm::kCatch, v8::internal::wasm::kCatchRef, v8::internal::wasm::TryTableIterator< ValidationTag >::pc_, v8::internal::wasm::Decoder::read_u8(), and v8::internal::wasm::CatchCase::MaybeTagIndex::tag_imm.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength().
pc()
template<typename ValidationTag >
const uint8_t* v8::internal::wasm::TryTableIterator< ValidationTag >::pc () const [inline]
Definition at line 983 of file function-body-decoder-impl.h.
{ return pc_; }
References v8::internal::wasm::TryTableIterator< ValidationTag >::pc_.
Member Data Documentation
decoder_
template<typename ValidationTag >
Decoder* const v8::internal::wasm::TryTableIterator< ValidationTag >::decoder_ [private]
Definition at line 992 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TryTableIterator< ValidationTag >::has_next(), and v8::internal::wasm::TryTableIterator< ValidationTag >::next().
index_
template<typename ValidationTag >
uint32_t v8::internal::wasm::TryTableIterator< ValidationTag >::index_ = 0 [private]
Definition at line 995 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TryTableIterator< ValidationTag >::cur_index(), v8::internal::wasm::TryTableIterator< ValidationTag >::has_next(), and v8::internal::wasm::TryTableIterator< ValidationTag >::next().
pc_
template<typename ValidationTag >
const uint8_t* v8::internal::wasm::TryTableIterator< ValidationTag >::pc_ [private]
Definition at line 994 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TryTableIterator< ValidationTag >::length(), v8::internal::wasm::TryTableIterator< ValidationTag >::next(), and v8::internal::wasm::TryTableIterator< ValidationTag >::pc().
start_
template<typename ValidationTag >
const uint8_t* const v8::internal::wasm::TryTableIterator< ValidationTag >::start_ [private]
Definition at line 993 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TryTableIterator< ValidationTag >::length().
table_count_
template<typename ValidationTag >
const uint32_t v8::internal::wasm::TryTableIterator< ValidationTag >::table_count_ [private]
Definition at line 996 of file function-body-decoder-impl.h.
Referenced by v8::internal::wasm::TryTableIterator< ValidationTag >::has_next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/function-body-decoder-impl.h