v8::internal::compiler::PropertyAccessInfo Class Reference
#include <access-info.h>
Public Types
enum Kind {
kInvalid
, kNotFound
, kDataField
, kFastDataConstant
,
kDictionaryProtoDataConstant
, kFastAccessorConstant
, kDictionaryProtoAccessorConstant
, kModuleExport
,
kStringLength
, kStringWrapperLength
, kTypedArrayLength
 }
Public Member Functions
bool Merge (PropertyAccessInfo const *that, AccessMode access_mode, Zone *zone) V8_WARN_UNUSED_RESULT
void RecordDependencies (CompilationDependencies *dependencies)
bool IsInvalid () const
bool IsNotFound () const
bool IsDataField () const
bool IsFastDataConstant () const
bool IsFastAccessorConstant () const
bool IsModuleExport () const
bool IsStringLength () const
bool IsStringWrapperLength () const
bool IsTypedArrayLength () const
bool IsDictionaryProtoDataConstant () const
bool IsDictionaryProtoAccessorConstant () const
bool HasTransitionMap () const
bool HasDictionaryHolder () const
ConstFieldInfo GetConstFieldInfo () const
Kind kind () const
OptionalJSObjectRef holder () const
OptionalMapRef transition_map () const
OptionalObjectRef constant () const
FieldIndex field_index () const
Type field_type () const
Representation field_representation () const
OptionalMapRef field_map () const
ZoneVector< MapRef > const & lookup_start_object_maps () const
InternalIndex dictionary_index () const
NameRef name () const
void set_elements_kind (ElementsKind elements_kind)
ElementsKind elements_kind () const
Static Public Member Functions
static PropertyAccessInfo NotFound (Zone *zone, MapRef receiver_map, OptionalJSObjectRef holder)
static PropertyAccessInfo DataField (JSHeapBroker *broker, Zone *zone, MapRef receiver_map, ZoneVector< CompilationDependency const * > &&unrecorded_dependencies, FieldIndex field_index, Representation field_representation, Type field_type, MapRef field_owner_map, OptionalMapRef field_map, OptionalJSObjectRef holder, OptionalMapRef transition_map)
static PropertyAccessInfo FastDataConstant (Zone *zone, MapRef receiver_map, ZoneVector< CompilationDependency const * > &&unrecorded_dependencies, FieldIndex field_index, Representation field_representation, Type field_type, MapRef field_owner_map, OptionalMapRef field_map, OptionalJSObjectRef holder, OptionalMapRef transition_map)
static PropertyAccessInfo FastAccessorConstant (Zone *zone, MapRef receiver_map, OptionalJSObjectRef holder, OptionalObjectRef constant, OptionalJSObjectRef api_holder)
static PropertyAccessInfo ModuleExport (Zone *zone, MapRef receiver_map, CellRef cell)
static PropertyAccessInfo StringLength (Zone *zone, MapRef receiver_map)
static PropertyAccessInfo StringWrapperLength (Zone *zone, MapRef receiver_map)
static PropertyAccessInfo TypedArrayLength (Zone *zone, MapRef receiver_map)
static PropertyAccessInfo Invalid (Zone *zone)
static PropertyAccessInfo DictionaryProtoDataConstant (Zone *zone, MapRef receiver_map, JSObjectRef holder, InternalIndex dict_index, NameRef name)
static PropertyAccessInfo DictionaryProtoAccessorConstant (Zone *zone, MapRef receiver_map, OptionalJSObjectRef holder, ObjectRef constant, OptionalJSObjectRef api_holder, NameRef name)
Private Member Functions
PropertyAccessInfo (Zone *zone)
PropertyAccessInfo (Zone *zone, Kind kind, OptionalJSObjectRef holder, ZoneVector< MapRef > &&lookup_start_object_maps)
PropertyAccessInfo (Zone *zone, Kind kind, OptionalJSObjectRef holder, OptionalObjectRef constant, OptionalJSObjectRef api_holder, OptionalNameRef name, ZoneVector< MapRef > &&lookup_start_object_maps)
PropertyAccessInfo (Kind kind, OptionalJSObjectRef holder, OptionalMapRef transition_map, FieldIndex field_index, Representation field_representation, Type field_type, MapRef field_owner_map, OptionalMapRef field_map, ZoneVector< MapRef > &&lookup_start_object_maps, ZoneVector< CompilationDependency const * > &&dependencies)
PropertyAccessInfo (Zone *zone, Kind kind, OptionalJSObjectRef holder, ZoneVector< MapRef > &&lookup_start_object_maps, InternalIndex dictionary_index, NameRef name)
Private Attributes
Kind kind_
ZoneVector< MapRef > lookup_start_object_maps_
OptionalObjectRef constant_
OptionalJSObjectRef holder_
OptionalJSObjectRef api_holder_
ZoneVector< CompilationDependency const * > unrecorded_dependencies_
OptionalMapRef transition_map_
FieldIndex field_index_
Representation field_representation_
Type field_type_
OptionalMapRef field_owner_map_
OptionalMapRef field_map_
InternalIndex dictionary_index_
OptionalNameRef name_
ElementsKind elements_kind_
Detailed Description
Definition at line 81 of file access-info.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::PropertyAccessInfo::Kind
Enumerator
kInvalid
kNotFound
kDataField
kFastDataConstant
kDictionaryProtoDataConstant
kFastAccessorConstant
kDictionaryProtoAccessorConstant
kModuleExport
kStringLength
kStringWrapperLength
kTypedArrayLength
Definition at line 83 of file access-info.h.
            {
    kInvalid,
    kNotFound,
    kDataField,
    kFastDataConstant,
    kDictionaryProtoDataConstant,
    kFastAccessorConstant,
    kDictionaryProtoAccessorConstant,
    kModuleExport,
    kStringLength,
    kStringWrapperLength,
    kTypedArrayLength
  };
Constructor & Destructor Documentation
PropertyAccessInfo() [1/5]
v8::internal::compiler::PropertyAccessInfo::PropertyAccessInfo (Zone * zone) [explicit], [private]
Definition at line 221 of file access-info.cc.
    : kind_(kInvalid),
      lookup_start_object_maps_(zone),
      unrecorded_dependencies_(zone),
      field_representation_(Representation::None()),
      field_type_(Type::None()),
      dictionary_index_(InternalIndex::NotFound()) {}
Referenced by DataField(), DictionaryProtoAccessorConstant(), DictionaryProtoDataConstant(), FastAccessorConstant(), FastDataConstant(), Invalid(), ModuleExport(), NotFound(), StringLength(), and StringWrapperLength().
PropertyAccessInfo() [2/5]
v8::internal::compiler::PropertyAccessInfo::PropertyAccessInfo (Zone * zone, Kind kind, OptionalJSObjectRef holder, ZoneVector< MapRef > && lookup_start_object_maps) [private]
Definition at line 229 of file access-info.cc.
    : kind_(kind),
      lookup_start_object_maps_(lookup_start_object_maps),
      holder_(holder),
      unrecorded_dependencies_(zone),
      field_representation_(Representation::None()),
      field_type_(Type::None()),
      dictionary_index_(InternalIndex::NotFound()) {}
PropertyAccessInfo() [3/5]
v8::internal::compiler::PropertyAccessInfo::PropertyAccessInfo (Zone * zone, Kind kind, OptionalJSObjectRef holder, OptionalObjectRef constant, OptionalJSObjectRef api_holder, OptionalNameRef name, ZoneVector< MapRef > && lookup_start_object_maps) [private]
Definition at line 240 of file access-info.cc.
    : kind_(kind),
      lookup_start_object_maps_(lookup_start_object_maps),
      constant_(constant),
      holder_(holder),
      api_holder_(api_holder),
      unrecorded_dependencies_(zone),
      field_representation_(Representation::None()),
      field_type_(Type::Any()),
      dictionary_index_(InternalIndex::NotFound()),
      name_(name) {
  DCHECK_IMPLIES(kind == kDictionaryProtoAccessorConstant, name.has_value());
}
References DCHECK_IMPLIES, kDictionaryProtoAccessorConstant, kind(), and name().
PropertyAccessInfo() [4/5]
v8::internal::compiler::PropertyAccessInfo::PropertyAccessInfo (Kind kind, OptionalJSObjectRef holder, OptionalMapRef transition_map, FieldIndex field_index, Representation field_representation, Type field_type, MapRef field_owner_map, OptionalMapRef field_map, ZoneVector< MapRef > && lookup_start_object_maps, ZoneVector< CompilationDependency const * > && dependencies) [private]
Definition at line 257 of file access-info.cc.
    : kind_(kind),
      lookup_start_object_maps_(lookup_start_object_maps),
      holder_(holder),
      unrecorded_dependencies_(std::move(unrecorded_dependencies)),
      transition_map_(transition_map),
      field_index_(field_index),
      field_representation_(field_representation),
      field_type_(field_type),
      field_owner_map_(field_owner_map),
      field_map_(field_map),
      dictionary_index_(InternalIndex::NotFound()) {
  DCHECK_IMPLIES(transition_map.has_value(),
                 field_owner_map.equals(transition_map.value()));
}
References DCHECK_IMPLIES, and transition_map().
PropertyAccessInfo() [5/5]
v8::internal::compiler::PropertyAccessInfo::PropertyAccessInfo (Zone * zone, Kind kind, OptionalJSObjectRef holder, ZoneVector< MapRef > && lookup_start_object_maps, InternalIndex dictionary_index, NameRef name) [private]
Definition at line 278 of file access-info.cc.
    : kind_(kind),
      lookup_start_object_maps_(lookup_start_object_maps),
      holder_(holder),
      unrecorded_dependencies_(zone),
      field_representation_(Representation::None()),
      field_type_(Type::Any()),
      dictionary_index_(dictionary_index),
      name_{name} {}
Member Function Documentation
constant()
OptionalObjectRef v8::internal::compiler::PropertyAccessInfo::constant () const [inline]
Definition at line 171 of file access-info.h.
                                     {
    DCHECK_IMPLIES(constant_.has_value(),
                   IsModuleExport() || IsFastAccessorConstant() ||
                       IsDictionaryProtoAccessorConstant());
    return constant_;
  }
References constant_, DCHECK_IMPLIES, IsDictionaryProtoAccessorConstant(), IsFastAccessorConstant(), and IsModuleExport().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), DictionaryProtoAccessorConstant(), FastAccessorConstant(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertySetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertySetterCall().
DataField()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::DataField (JSHeapBroker * broker, Zone * zone, MapRef receiver_map, ZoneVector< CompilationDependency const * > && unrecorded_dependencies, FieldIndex field_index, Representation field_representation, Type field_type, MapRef field_owner_map, OptionalMapRef field_map, OptionalJSObjectRef holder, OptionalMapRef transition_map) [static]
Definition at line 132 of file access-info.cc.
                                                               {
  DCHECK(!field_representation.IsNone());
  DCHECK_IMPLIES(
      field_representation.IsDouble(),
      HasFieldRepresentationDependenciesOnMap(
          dependencies, transition_map.has_value() ? transition_map->object()
                        : holder.has_value() ? holder->map(broker).object()
                                             : receiver_map.object()));
  return PropertyAccessInfo(kDataField, holder, transition_map, field_index,
                            field_representation, field_type, field_owner_map,
                            field_map, {{receiver_map}, zone},
                            std::move(dependencies));
}
References broker(), v8::internal::DCHECK(), DCHECK_IMPLIES, field_index(), field_map(), field_representation(), field_type(), holder(), v8::internal::Representation::IsDouble(), v8::internal::Representation::IsNone(), kDataField, v8::internal::compiler::MapRef::object(), PropertyAccessInfo(), and transition_map().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor(), and v8::internal::compiler::AccessInfoFactory::LookupTransition().
dictionary_index()
InternalIndex v8::internal::compiler::PropertyAccessInfo::dictionary_index () const [inline]
Definition at line 198 of file access-info.h.
                                         {
    DCHECK(HasDictionaryHolder());
    return dictionary_index_;
  }
References v8::internal::DCHECK(), dictionary_index_, and HasDictionaryHolder().
Referenced by DictionaryProtoDataConstant(), v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant().
DictionaryProtoAccessorConstant()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::DictionaryProtoAccessorConstant (Zone * zone, MapRef receiver_map, OptionalJSObjectRef holder, ObjectRef constant, OptionalJSObjectRef api_holder, NameRef name) [static]
Definition at line 213 of file access-info.cc.
                                                                               {
  return PropertyAccessInfo(zone, kDictionaryProtoAccessorConstant, holder,
                            constant, api_holder, property_name,
                            {{receiver_map}, zone});
}
References constant(), holder(), kDictionaryProtoAccessorConstant, and PropertyAccessInfo().
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper().
DictionaryProtoDataConstant()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::DictionaryProtoDataConstant (Zone * zone, MapRef receiver_map, JSObjectRef holder, InternalIndex dict_index, NameRef name) [static]
Definition at line 205 of file access-info.cc.
                                                  {
  return PropertyAccessInfo(zone, kDictionaryProtoDataConstant, holder,
                            {{receiver_map}, zone}, dictionary_index, name);
}
References dictionary_index(), holder(), kDictionaryProtoDataConstant, name(), and PropertyAccessInfo().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDictionaryProtoAccessInfo().
elements_kind()
ElementsKind v8::internal::compiler::PropertyAccessInfo::elements_kind () const [inline]
Definition at line 211 of file access-info.h.
{ return elements_kind_; }
References elements_kind_.
Referenced by set_elements_kind(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad().
FastAccessorConstant()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::FastAccessorConstant (Zone * zone, MapRef receiver_map, OptionalJSObjectRef holder, OptionalObjectRef constant, OptionalJSObjectRef api_holder) [static]
Definition at line 166 of file access-info.cc.
                                                                {
  return PropertyAccessInfo(zone, kFastAccessorConstant, holder, constant,
                            api_holder, {} /* name */, {{receiver_map}, zone});
}
References constant(), holder(), kFastAccessorConstant, and PropertyAccessInfo().
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper().
FastDataConstant()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::FastDataConstant (Zone * zone, MapRef receiver_map, ZoneVector< CompilationDependency const * > && unrecorded_dependencies, FieldIndex field_index, Representation field_representation, Type field_type, MapRef field_owner_map, OptionalMapRef field_map, OptionalJSObjectRef holder, OptionalMapRef transition_map) [static]
Definition at line 152 of file access-info.cc.
                                                               {
  DCHECK(!field_representation.IsNone());
  return PropertyAccessInfo(kFastDataConstant, holder, transition_map,
                            field_index, field_representation, field_type,
                            field_owner_map, field_map, {{receiver_map}, zone},
                            std::move(dependencies));
}
References v8::internal::DCHECK(), field_index(), field_map(), field_representation(), field_type(), holder(), v8::internal::Representation::IsNone(), kFastDataConstant, PropertyAccessInfo(), and transition_map().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), and v8::internal::compiler::AccessInfoFactory::LookupTransition().
field_index()
FieldIndex v8::internal::compiler::PropertyAccessInfo::field_index () const [inline]
Definition at line 177 of file access-info.h.
                                 {
    DCHECK(!HasDictionaryHolder());
    return field_index_;
  }
References v8::internal::DCHECK(), field_index_, and HasDictionaryHolder().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), DataField(), FastDataConstant(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDoubleField().
field_map()
OptionalMapRef v8::internal::compiler::PropertyAccessInfo::field_map () const [inline]
Definition at line 190 of file access-info.h.
                                   {
    DCHECK(!HasDictionaryHolder());
    return field_map_;
  }
References v8::internal::DCHECK(), field_map_, and HasDictionaryHolder().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), DataField(), FastDataConstant(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField().
field_representation()
Representation v8::internal::compiler::PropertyAccessInfo::field_representation () const [inline]
Definition at line 186 of file access-info.h.
                                              {
    DCHECK(!HasDictionaryHolder());
    return field_representation_;
  }
References v8::internal::DCHECK(), field_representation_, and HasDictionaryHolder().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), DataField(), FastDataConstant(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadConstantDoubleField().
field_type()
Type v8::internal::compiler::PropertyAccessInfo::field_type () const [inline]
Definition at line 182 of file access-info.h.
                          {
    DCHECK(!HasDictionaryHolder());
    return field_type_;
  }
References v8::internal::DCHECK(), field_type_, and HasDictionaryHolder().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), DataField(), and FastDataConstant().
GetConstFieldInfo()
ConstFieldInfo v8::internal::compiler::PropertyAccessInfo::GetConstFieldInfo () const
Definition at line 400 of file access-info.cc.
                                                           {
  return IsFastDataConstant() ? ConstFieldInfo(*field_owner_map_)
                              : ConstFieldInfo::None();
}
References field_owner_map_, IsFastDataConstant(), and v8::internal::compiler::ConstFieldInfo::None().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), and v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore().
HasDictionaryHolder()
bool v8::internal::compiler::PropertyAccessInfo::HasDictionaryHolder () const [inline]
Definition at line 152 of file access-info.h.
                                   {
    return kind_ == kDictionaryProtoDataConstant ||
           kind_ == kDictionaryProtoAccessorConstant;
  }
References kDictionaryProtoAccessorConstant, kDictionaryProtoDataConstant, and kind_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyTest(), dictionary_index(), field_index(), field_map(), field_representation(), field_type(), name(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), transition_map(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad().
HasTransitionMap()
bool v8::internal::compiler::PropertyAccessInfo::HasTransitionMap () const [inline]
Definition at line 151 of file access-info.h.
{ return transition_map().has_value(); }
References transition_map().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField().
holder()
OptionalJSObjectRef v8::internal::compiler::PropertyAccessInfo::holder () const [inline]
Definition at line 161 of file access-info.h.
                                     {
    // TODO(neis): There was a CHECK here that tries to protect against
    // using the access info without recording its dependencies first.
    // Find a more suitable place for it.
    return holder_;
  }
References holder_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyTest(), DataField(), DictionaryProtoAccessorConstant(), DictionaryProtoDataConstant(), FastAccessorConstant(), FastDataConstant(), v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), NotFound(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::PropertyAccessBuilder::ResolveHolder(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant(), and v8::internal::maglev::MaglevGraphBuilder::TryGetConstantDataFieldHolder().
Invalid()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::Invalid (Zone * zone) [static]
Definition at line 121 of file access-info.cc.
                                                         {
  return PropertyAccessInfo(zone);
}
References PropertyAccessInfo().
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), and v8::internal::compiler::AccessInfoFactory::Invalid().
IsDataField()
bool v8::internal::compiler::PropertyAccessInfo::IsDataField () const [inline]
Definition at line 135 of file access-info.h.
{ return kind() == kDataField; }
References kDataField, and kind().
Referenced by v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), and v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore().
IsDictionaryProtoAccessorConstant()
bool v8::internal::compiler::PropertyAccessInfo::IsDictionaryProtoAccessorConstant () const [inline]
Definition at line 147 of file access-info.h.
                                                 {
    return kind() == kDictionaryProtoAccessorConstant;
  }
References kDictionaryProtoAccessorConstant, and kind().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), constant(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall().
IsDictionaryProtoDataConstant()
bool v8::internal::compiler::PropertyAccessInfo::IsDictionaryProtoDataConstant () const [inline]
Definition at line 144 of file access-info.h.
                                             {
    return kind() == kDictionaryProtoDataConstant;
  }
References kDictionaryProtoDataConstant, and kind().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant().
IsFastAccessorConstant()
bool v8::internal::compiler::PropertyAccessInfo::IsFastAccessorConstant () const [inline]
Definition at line 137 of file access-info.h.
                                      {
    return kind() == kFastAccessorConstant;
  }
References kFastAccessorConstant, and kind().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), and constant().
IsFastDataConstant()
bool v8::internal::compiler::PropertyAccessInfo::IsFastDataConstant () const [inline]
Definition at line 136 of file access-info.h.
{ return kind() == kFastDataConstant; }
References kFastDataConstant, and kind().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AccessInfoGuaranteedConst(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), GetConstFieldInfo(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), and v8::internal::maglev::MaglevGraphBuilder::TryGetConstantDataFieldHolder().
IsInvalid()
bool v8::internal::compiler::PropertyAccessInfo::IsInvalid () const [inline]
Definition at line 133 of file access-info.h.
{ return kind() == kInvalid; }
References kind(), and kInvalid.
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper(), v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess().
IsModuleExport()
bool v8::internal::compiler::PropertyAccessInfo::IsModuleExport () const [inline]
Definition at line 140 of file access-info.h.
{ return kind() == kModuleExport; }
References kind(), and kModuleExport.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), and constant().
IsNotFound()
bool v8::internal::compiler::PropertyAccessInfo::IsNotFound () const [inline]
Definition at line 134 of file access-info.h.
{ return kind() == kNotFound; }
References kind(), and kNotFound.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyTest(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf().
IsStringLength()
bool v8::internal::compiler::PropertyAccessInfo::IsStringLength () const [inline]
Definition at line 141 of file access-info.h.
{ return kind() == kStringLength; }
References kind(), and kStringLength.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AccessInfoGuaranteedConst(), and v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad().
IsStringWrapperLength()
bool v8::internal::compiler::PropertyAccessInfo::IsStringWrapperLength () const [inline]
Definition at line 142 of file access-info.h.
{ return kind() == kStringWrapperLength; }
References kind(), and kStringWrapperLength.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad().
IsTypedArrayLength()
bool v8::internal::compiler::PropertyAccessInfo::IsTypedArrayLength () const [inline]
Definition at line 143 of file access-info.h.
{ return kind() == kTypedArrayLength; }
References kind(), and kTypedArrayLength.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad().
kind()
Kind v8::internal::compiler::PropertyAccessInfo::kind () const [inline]
Definition at line 158 of file access-info.h.
{ return kind_; }
References kind_.
Referenced by IsDataField(), IsDictionaryProtoAccessorConstant(), IsDictionaryProtoDataConstant(), IsFastAccessorConstant(), IsFastDataConstant(), IsInvalid(), IsModuleExport(), IsNotFound(), IsStringLength(), IsStringWrapperLength(), IsTypedArrayLength(), PropertyAccessInfo(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore().
lookup_start_object_maps()
ZoneVector<MapRef> const& v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps () const [inline]
Definition at line 194 of file access-info.h.
                                                             {
    return lookup_start_object_maps_;
  }
References lookup_start_object_maps_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::AccessInfoGuaranteedConst(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyTest(), v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyStore(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant().
Merge()
bool v8::internal::compiler::PropertyAccessInfo::Merge (PropertyAccessInfo const * that, AccessMode access_mode, Zone * zone)
Definition at line 307 of file access-info.cc.
                                                                   {
  if (kind_ != that->kind_) return false;
  if (!OptionalRefEquals(holder_, that->holder_)) return false;
  switch (kind_) {
    case kInvalid:
      DCHECK_EQ(that->kind_, kInvalid);
      return true;
    case kDataField:
    case kFastDataConstant: {
      // Check if we actually access the same field (we use the
      // GetFieldAccessStubKey method here just like the ICs do
      // since that way we only compare the relevant bits of the
      // field indices).
      if (field_index_.GetFieldAccessStubKey() !=
          that->field_index_.GetFieldAccessStubKey()) {
        return false;
      }
      switch (access_mode) {
        case AccessMode::kHas:
        case AccessMode::kLoad: {
          if (!field_representation_.Equals(that->field_representation_)) {
            if (field_representation_.IsDouble() ||
                that->field_representation_.IsDouble()) {
              return false;
            }
            field_representation_ = Representation::Tagged();
          }
          if (!OptionalRefEquals(field_map_, that->field_map_)) {
            field_map_ = {};
          }
          break;
        }
        case AccessMode::kStore:
        case AccessMode::kStoreInLiteral:
        case AccessMode::kDefine: {
          // For stores, the field map and field representation information
          // must match exactly, otherwise we cannot merge the stores. We
          // also need to make sure that in case of transitioning stores,
          // the transition targets match.
          if (!OptionalRefEquals(field_map_, that->field_map_) ||
              !field_representation_.Equals(that->field_representation_) ||
              !OptionalRefEquals(transition_map_, that->transition_map_)) {
            return false;
          }
          break;
        }
      }
      field_type_ = Type::Union(field_type_, that->field_type_, zone);
      AppendVector(&lookup_start_object_maps_, that->lookup_start_object_maps_);
      AppendVector(&unrecorded_dependencies_, that->unrecorded_dependencies_);
      return true;
    }
    case kDictionaryProtoAccessorConstant:
    case kFastAccessorConstant: {
      // Check if we actually access the same constant.
      if (!OptionalRefEquals(constant_, that->constant_)) return false;
      DCHECK(unrecorded_dependencies_.empty());
      DCHECK(that->unrecorded_dependencies_.empty());
      AppendVector(&lookup_start_object_maps_, that->lookup_start_object_maps_);
      return true;
    }
    case kDictionaryProtoDataConstant: {
      DCHECK_EQ(AccessMode::kLoad, access_mode);
      if (dictionary_index_ != that->dictionary_index_) return false;
      AppendVector(&lookup_start_object_maps_, that->lookup_start_object_maps_);
      return true;
    }
    case kNotFound:
    case kStringLength:
    case kStringWrapperLength: {
      DCHECK(unrecorded_dependencies_.empty());
      DCHECK(that->unrecorded_dependencies_.empty());
      AppendVector(&lookup_start_object_maps_, that->lookup_start_object_maps_);
      return true;
    }
    case kTypedArrayLength:
      DCHECK_EQ(lookup_start_object_maps_.size(), 1);
      DCHECK_EQ(that->lookup_start_object_maps_.size(), 1);
      return lookup_start_object_maps_[0] == that->lookup_start_object_maps_[0];
    case kModuleExport:
      return false;
  }
}
References v8::internal::compiler::anonymous_namespace{access-info.cc}::AppendVector(), constant_, v8::internal::DCHECK(), DCHECK_EQ, dictionary_index_, v8::internal::Representation::Equals(), field_index_, field_map_, field_representation_, field_type_, v8::internal::FieldIndex::GetFieldAccessStubKey(), holder_, v8::internal::Representation::IsDouble(), kDataField, v8::internal::compiler::kDefine, kDictionaryProtoAccessorConstant, kDictionaryProtoDataConstant, kFastAccessorConstant, kFastDataConstant, v8::internal::compiler::kHas, kind_, kInvalid, v8::internal::compiler::kLoad, kModuleExport, kNotFound, v8::internal::compiler::kStore, v8::internal::compiler::kStoreInLiteral, kStringLength, kStringWrapperLength, kTypedArrayLength, lookup_start_object_maps_, v8::internal::compiler::anonymous_namespace{access-info.cc}::OptionalRefEquals(), v8::internal::Representation::Tagged(), transition_map_, v8::internal::compiler::Type::Union(), and unrecorded_dependencies_.
ModuleExport()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::ModuleExport (Zone * zone, MapRef receiver_map, CellRef cell) [static]
Definition at line 174 of file access-info.cc.
                                                                  {
  return PropertyAccessInfo(zone, kModuleExport, {} /* holder */,
                            cell /* constant */, {} /* api_holder */,
                            {} /* name */, {{receiver_map}, zone});
}
References kModuleExport, and PropertyAccessInfo().
Referenced by v8::internal::compiler::anonymous_namespace{access-info.cc}::AccessorAccessInfoHelper().
name()
NameRef v8::internal::compiler::PropertyAccessInfo::name () const [inline]
Definition at line 203 of file access-info.h.
                       {
    DCHECK(HasDictionaryHolder());
    return name_.value();
  }
References v8::internal::DCHECK(), HasDictionaryHolder(), and name_.
Referenced by DictionaryProtoDataConstant(), v8::internal::compiler::PropertyAccessBuilder::FoldLoadDictPrototypeConstant(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), PropertyAccessInfo(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyGetterCall(), and v8::internal::maglev::MaglevGraphBuilder::TryFoldLoadDictPrototypeConstant().
NotFound()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::NotFound (Zone * zone, MapRef receiver_map, OptionalJSObjectRef holder) [static]
Definition at line 126 of file access-info.cc.
                                                                            {
  return PropertyAccessInfo(zone, kNotFound, holder, {{receiver_map}, zone});
}
References holder(), kNotFound, and PropertyAccessInfo().
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo().
RecordDependencies()
void v8::internal::compiler::PropertyAccessInfo::RecordDependencies (CompilationDependencies * dependencies)
Definition at line 1160 of file access-info.cc.
                                           {
  for (CompilationDependency const* d : unrecorded_dependencies_) {
    dependencies->RecordDependency(d);
  }
  unrecorded_dependencies_.clear();
}
References v8::internal::compiler::CompilationDependencies::RecordDependency(), and unrecorded_dependencies_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf().
set_elements_kind()
void v8::internal::compiler::PropertyAccessInfo::set_elements_kind (ElementsKind elements_kind) [inline]
Definition at line 208 of file access-info.h.
                                                     {
    elements_kind_ = elements_kind;
  }
References elements_kind(), and elements_kind_.
StringLength()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::StringLength (Zone * zone, MapRef receiver_map) [static]
Definition at line 183 of file access-info.cc.
                                                                         {
  return PropertyAccessInfo(zone, kStringLength, {}, {{receiver_map}, zone});
}
References kStringLength, and PropertyAccessInfo().
Referenced by v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor().
StringWrapperLength()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::StringWrapperLength (Zone * zone, MapRef receiver_map) [static]
Definition at line 189 of file access-info.cc.
                                     {
  return PropertyAccessInfo(zone, kStringWrapperLength, {},
                            {{receiver_map}, zone});
}
References kStringWrapperLength, and PropertyAccessInfo().
Referenced by v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessor().
transition_map()
OptionalMapRef v8::internal::compiler::PropertyAccessInfo::transition_map () const [inline]
Definition at line 167 of file access-info.h.
                                        {
    DCHECK(!HasDictionaryHolder());
    return transition_map_;
  }
References v8::internal::DCHECK(), HasDictionaryHolder(), and transition_map_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyStore(), DataField(), FastDataConstant(), HasTransitionMap(), PropertyAccessInfo(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildStoreField().
TypedArrayLength()
PropertyAccessInfo v8::internal::compiler::PropertyAccessInfo::TypedArrayLength (Zone * zone, MapRef receiver_map) [static]
Definition at line 196 of file access-info.cc.
                                                                             {
  PropertyAccessInfo result(zone, kTypedArrayLength, {},
                            {{receiver_map}, zone});
  result.set_elements_kind(receiver_map.elements_kind());
  return result;
}
References v8::internal::compiler::MapRef::elements_kind(), kTypedArrayLength, and v8::base::internal::result.
Referenced by v8::internal::compiler::AccessInfoFactory::LookupSpecialFieldAccessorInHolder().
Member Data Documentation
api_holder_
OptionalJSObjectRef v8::internal::compiler::PropertyAccessInfo::api_holder_ [private]
Definition at line 236 of file access-info.h.
constant_
OptionalObjectRef v8::internal::compiler::PropertyAccessInfo::constant_ [private]
Definition at line 234 of file access-info.h.
Referenced by constant(), and Merge().
dictionary_index_
InternalIndex v8::internal::compiler::PropertyAccessInfo::dictionary_index_ [private]
Definition at line 248 of file access-info.h.
Referenced by dictionary_index(), and Merge().
elements_kind_
ElementsKind v8::internal::compiler::PropertyAccessInfo::elements_kind_ [private]
Definition at line 252 of file access-info.h.
Referenced by elements_kind(), and set_elements_kind().
field_index_
FieldIndex v8::internal::compiler::PropertyAccessInfo::field_index_ [private]
Definition at line 241 of file access-info.h.
Referenced by field_index(), and Merge().
field_map_
OptionalMapRef v8::internal::compiler::PropertyAccessInfo::field_map_ [private]
Definition at line 245 of file access-info.h.
Referenced by field_map(), and Merge().
field_owner_map_
OptionalMapRef v8::internal::compiler::PropertyAccessInfo::field_owner_map_ [private]
Definition at line 244 of file access-info.h.
Referenced by GetConstFieldInfo().
field_representation_
Representation v8::internal::compiler::PropertyAccessInfo::field_representation_ [private]
Definition at line 242 of file access-info.h.
Referenced by field_representation(), and Merge().
field_type_
Type v8::internal::compiler::PropertyAccessInfo::field_type_ [private]
Definition at line 243 of file access-info.h.
Referenced by field_type(), and Merge().
holder_
OptionalJSObjectRef v8::internal::compiler::PropertyAccessInfo::holder_ [private]
Definition at line 235 of file access-info.h.
Referenced by holder(), and Merge().
kind_
Kind v8::internal::compiler::PropertyAccessInfo::kind_ [private]
Definition at line 232 of file access-info.h.
Referenced by HasDictionaryHolder(), kind(), and Merge().
lookup_start_object_maps_
ZoneVector<MapRef> v8::internal::compiler::PropertyAccessInfo::lookup_start_object_maps_ [private]
Definition at line 233 of file access-info.h.
Referenced by lookup_start_object_maps(), and Merge().
name_
OptionalNameRef v8::internal::compiler::PropertyAccessInfo::name_ [private]
Definition at line 249 of file access-info.h.
Referenced by name().
transition_map_
OptionalMapRef v8::internal::compiler::PropertyAccessInfo::transition_map_ [private]
Definition at line 240 of file access-info.h.
Referenced by Merge(), and transition_map().
unrecorded_dependencies_
ZoneVector<CompilationDependency const*> v8::internal::compiler::PropertyAccessInfo::unrecorded_dependencies_ [private]
Definition at line 239 of file access-info.h.
Referenced by Merge(), and RecordDependencies().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/access-info.h
/mnt/V8SourceCode/src/compiler/access-info.cc