v8::internal::compiler::PropertyAccess Class Reference
#include <js-operator.h>
Public Member Functions
PropertyAccess (LanguageMode language_mode, FeedbackSource const &feedback)
LanguageMode language_mode () const
FeedbackSource const & feedback () const
Private Attributes
FeedbackSource const feedback_
LanguageMode const language_mode_
Detailed Description
Definition at line 535 of file js-operator.h.
Constructor & Destructor Documentation
PropertyAccess()
v8::internal::compiler::PropertyAccess::PropertyAccess (LanguageMode language_mode, FeedbackSource const & feedback) [inline]
Definition at line 537 of file js-operator.h.
      : feedback_(feedback), language_mode_(language_mode) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::PropertyAccess::feedback () const [inline]
Definition at line 541 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadProperty(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetKeyedProperty().
language_mode()
LanguageMode v8::internal::compiler::PropertyAccess::language_mode () const [inline]
Definition at line 540 of file js-operator.h.
{ return language_mode_; }
References language_mode_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess().
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::PropertyAccess::feedback_ [private]
Definition at line 544 of file js-operator.h.
Referenced by feedback().
language_mode_
LanguageMode const v8::internal::compiler::PropertyAccess::language_mode_ [private]
Definition at line 545 of file js-operator.h.
Referenced by language_mode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h