v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData > Class Template Reference
#include <snapshot-table.h>
Public Types
using Super = SnapshotTable< Value, KeyData >
using Key = SnapshotTableKey< Value, KeyData >
Public Member Functions
void StartNewSnapshot (base::Vector< const Snapshot > predecessors)
void StartNewSnapshot (std::initializer_list< Snapshot > predecessors={})
void StartNewSnapshot (Snapshot parent)
template<class MergeFun >
void StartNewSnapshot (base::Vector< const Snapshot > predecessors, const MergeFun &merge_fun) requires(std
template<class MergeFun >
void StartNewSnapshot (std::initializer_list< Snapshot > predecessors, const MergeFun &merge_fun) requires(std
void Set (Key key, Value new_value)
void SetNoNotify (Key key, Value new_value)
Key NewKey (KeyData data, Value initial_value=Value{})
Key NewKey (Value initial_value=Value{})
Detailed Description
template<class Derived, class Value, class KeyData = NoKeyData>
class v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >
Definition at line 519 of file snapshot-table.h.
Member Typedef Documentation
Key
template<class Derived , class Value , class KeyData = NoKeyData>
using v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Key = SnapshotTableKey<Value, KeyData>
Definition at line 99 of file snapshot-table.h.
Super
template<class Derived , class Value , class KeyData = NoKeyData>
using v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::Super = SnapshotTable<Value, KeyData>
Definition at line 521 of file snapshot-table.h.
Member Function Documentation
NewKey() [1/2]
template<class Derived , class Value , class KeyData = NoKeyData>
Key v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::NewKey (KeyData data, Value initial_value = Value{}) [inline]
Definition at line 568 of file snapshot-table.h.
                                                      {}) {
    Key key = Super::NewKey(std::move(data), std::move(initial_value));
    static_cast<Derived*>(this)->OnNewKey(key, Super::Get(key));
    return key;
  }
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewLoopInvariantVariable(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::NewVariable().
NewKey() [2/2]
template<class Derived , class Value , class KeyData = NoKeyData>
Key v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::NewKey (Value initial_value = Value{}) [inline]
Definition at line 573 of file snapshot-table.h.
                                        {}) {
    return NewKey(KeyData{}, initial_value);
  }
Set()
template<class Derived , class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::Set (Key key, Value new_value) [inline]
Definition at line 556 of file snapshot-table.h.
                                     {
    Value old_value = Super::Get(key);
    if (Super::Set(key, std::move(new_value))) {
      static_cast<Derived*>(this)->OnValueChange(key, old_value,
                                                 Super::Get(key));
    }
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set().
Referenced by v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Set(), and v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::SetVariable().
SetNoNotify()
template<class Derived , class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::SetNoNotify (Key key, Value new_value) [inline]
Definition at line 564 of file snapshot-table.h.
                                             {
    Super::Set(key, std::move(new_value));
  }
References v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set().
StartNewSnapshot() [1/5]
template<class Derived , class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot (base::Vector< const Snapshot > predecessors) [inline]
Definition at line 526 of file snapshot-table.h.
                                                                 {
    Super::StartNewSnapshot(
        predecessors,
        [this](Key key, const Value& old_value, const Value& new_value) {
          static_cast<Derived*>(this)->OnValueChange(key, old_value, new_value);
        });
  }
References v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::RestoreTemporaryVariableSnapshotAfter(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor(), and v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor().
StartNewSnapshot() [2/5]
template<class Derived , class Value , class KeyData = NoKeyData>
template<class MergeFun >
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot (base::Vector< const Snapshot > predecessors, const MergeFun & merge_fun) [inline]
Definition at line 538 of file snapshot-table.h.
  {
    Super::StartNewSnapshot(
        predecessors, merge_fun,
        [this](Key key, const Value& old_value, const Value& new_value) {
          static_cast<Derived*>(this)->OnValueChange(key, old_value, new_value);
        });
  }
References v8::internal::key, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot().
StartNewSnapshot() [3/5]
template<class Derived , class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot (Snapshot parent) [inline]
Definition at line 536 of file snapshot-table.h.
{ StartNewSnapshot({parent}); }
References v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot().
Referenced by v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot().
StartNewSnapshot() [4/5]
template<class Derived , class Value , class KeyData = NoKeyData>
template<class MergeFun >
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot (std::initializer_list< Snapshot > predecessors, const MergeFun & merge_fun) [inline]
Definition at line 549 of file snapshot-table.h.
  {
    StartNewSnapshot(base::VectorOf(predecessors), merge_fun);
  }
References v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), and v8::base::VectorOf().
StartNewSnapshot() [5/5]
template<class Derived , class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot (std::initializer_list< Snapshot > predecessors = {}) [inline]
Definition at line 533 of file snapshot-table.h.
                                                                     {}) {
    StartNewSnapshot(base::VectorOf(predecessors));
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/snapshot-table.h