v8::D8Console Class Reference
#include <d8-console.h>
Public Member Functions
D8Console (Isolate *isolate)
~D8Console () override
CpuProfiler * profiler () const
void DisposeProfiler ()
Private Member Functions
void Assert (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Log (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Error (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Warn (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Info (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Debug (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Profile (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &context) override
void ProfileEnd (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &context) override
void Time (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void TimeLog (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void TimeEnd (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void TimeStamp (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
void Trace (const debug::ConsoleCallArguments &args, const v8::debug::ConsoleContext &) override
Private Attributes
Isolate * isolate_
std::map< std::string, base::TimeTicks > timers_
base::TimeTicks origin_
CpuProfiler * profiler_ {nullptr}
bool profiler_active_ {false}
Detailed Description
Definition at line 17 of file d8-console.h.
Constructor & Destructor Documentation
D8Console()
v8::D8Console::D8Console (Isolate * isolate) [explicit]
Definition at line 59 of file d8-console.cc.
    : isolate_(isolate), origin_(base::TimeTicks::Now()) {}
 D8Console()
v8::D8Console::~D8Console () [override]
Definition at line 62 of file d8-console.cc.
{ DCHECK_NULL(profiler_); }
References DCHECK_NULL, and profiler_.
Member Function Documentation
Assert()
void v8::D8Console::Assert (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 75 of file d8-console.cc.
                                                     {
  // If no arguments given, the "first" argument is undefined which is
  // false-ish.
  if (args.Length() > 0 && args[0]->BooleanValue(isolate_)) return;
  WriteToFile("console.assert", stdout, isolate_, args);
  isolate_->ThrowError("console.assert failed");
}
References v8::base::args, isolate_, v8::Isolate::ThrowError(), and v8::WriteToFile().
Debug()
void v8::D8Console::Debug (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 104 of file d8-console.cc.
                                                    {
  WriteToFile("console.debug", stdout, isolate_, args);
}
References v8::base::args, isolate_, and v8::WriteToFile().
DisposeProfiler()
void v8::D8Console::DisposeProfiler ()
Definition at line 64 of file d8-console.cc.
                                {
  if (profiler_) {
    if (profiler_active_) {
      profiler_->StopProfiling(String::Empty(isolate_));
      profiler_active_ = false;
    }
    profiler_->Dispose();
    profiler_ = nullptr;
  }
}
References v8::CpuProfiler::Dispose(), v8::String::Empty(), isolate_, profiler_, profiler_active_, and v8::CpuProfiler::StopProfiling().
Referenced by v8::Shell::ResetOnProfileEndListener().
Error()
void v8::D8Console::Error (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 89 of file d8-console.cc.
                                                    {
  WriteToFile("console.error", stderr, isolate_, args);
}
References v8::base::args, isolate_, and v8::WriteToFile().
Info()
void v8::D8Console::Info (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 99 of file d8-console.cc.
                                                   {
  WriteToFile("console.info", stdout, isolate_, args);
}
References v8::base::args, isolate_, and v8::WriteToFile().
Log()
void v8::D8Console::Log (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 84 of file d8-console.cc.
                                                  {
  WriteToFile(nullptr, stdout, isolate_, args);
}
References v8::base::args, isolate_, and v8::WriteToFile().
Profile()
void v8::D8Console::Profile (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext & context) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 109 of file d8-console.cc.
                                                      {
  if (!profiler_) {
    profiler_ = CpuProfiler::New(isolate_);
  }
  profiler_active_ = true;
  profiler_->StartProfiling(String::Empty(isolate_), CpuProfilingOptions{});
}
References v8::String::Empty(), isolate_, v8::CpuProfiler::New(), profiler_, profiler_active_, and v8::CpuProfiler::StartProfiling().
ProfileEnd()
void v8::D8Console::ProfileEnd (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext & context) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 118 of file d8-console.cc.
                                                         {
  if (!profiler_) return;
  CpuProfile* profile = profiler_->StopProfiling(String::Empty(isolate_));
  profiler_active_ = false;
  if (!profile) return;
  if (Shell::HasOnProfileEndListener(isolate_)) {
    i::StringOutputStream out;
    profile->Serialize(&out);
    Shell::TriggerOnProfileEndListener(isolate_, out.str());
  } else {
    i::FileOutputStream out(kCpuProfileOutputFilename);
    profile->Serialize(&out);
  }
  profile->Delete();
}
References v8::CpuProfile::Delete(), v8::String::Empty(), v8::Shell::HasOnProfileEndListener(), isolate_, v8::anonymous_namespace{d8-console.cc}::kCpuProfileOutputFilename, profiler_, profiler_active_, v8::CpuProfile::Serialize(), v8::CpuProfiler::StopProfiling(), v8::internal::StringOutputStream::str(), and v8::Shell::TriggerOnProfileEndListener().
profiler()
CpuProfiler* v8::D8Console::profiler () const [inline]
Definition at line 22 of file d8-console.h.
{ return profiler_; }
References profiler_.
Referenced by v8::Shell::ProfilerTriggerSample().
Time()
void v8::D8Console::Time (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 135 of file d8-console.cc.
                                                   {
  if (i::v8_flags.correctness_fuzzer_suppressions) return;
  std::optional label = GetTimerLabel(args);
  if (!label.has_value()) return;
  if (!timers_.try_emplace(label.value(), base::TimeTicks::Now()).second) {
    printf("console.time: Timer '%s' already exists\n", label.value().c_str());
  }
}
References v8::base::args, v8::anonymous_namespace{d8-console.cc}::GetTimerLabel(), v8::base::TimeTicks::Now(), timers_, and v8::internal::v8_flags.
TimeEnd()
void v8::D8Console::TimeEnd (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 161 of file d8-console.cc.
                                                      {
  if (i::v8_flags.correctness_fuzzer_suppressions) return;
  std::optional label = GetTimerLabel(args);
  if (!label.has_value()) return;
  auto it = timers_.find(label.value());
  if (it == timers_.end()) {
    printf("console.timeEnd: Timer '%s' does not exist\n",
           label.value().c_str());
    return;
  }
  base::TimeDelta delta = base::TimeTicks::Now() - it->second;
  printf("console.timeEnd: %s, %f\n", label.value().c_str(),
         delta.InMillisecondsF());
  timers_.erase(it);
}
References v8::base::args, v8::anonymous_namespace{d8-console.cc}::GetTimerLabel(), v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeTicks::Now(), timers_, and v8::internal::v8_flags.
TimeLog()
void v8::D8Console::TimeLog (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 145 of file d8-console.cc.
                                                      {
  if (i::v8_flags.correctness_fuzzer_suppressions) return;
  std::optional label = GetTimerLabel(args);
  if (!label.has_value()) return;
  auto it = timers_.find(label.value());
  if (it == timers_.end()) {
    printf("console.timeLog: Timer '%s' does not exist\n",
           label.value().c_str());
    return;
  }
  base::TimeDelta delta = base::TimeTicks::Now() - it->second;
  printf("console.timeLog: %s, %f\n", label.value().c_str(),
         delta.InMillisecondsF());
}
References v8::base::args, v8::anonymous_namespace{d8-console.cc}::GetTimerLabel(), v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeTicks::Now(), timers_, and v8::internal::v8_flags.
TimeStamp()
void v8::D8Console::TimeStamp (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 178 of file d8-console.cc.
                                                        {
  if (i::v8_flags.correctness_fuzzer_suppressions) return;
  std::optional label = GetTimerLabel(args);
  if (!label.has_value()) return;
  base::TimeDelta delta = base::TimeTicks::Now() - origin_;
  printf("console.timeStamp: %s, %f\n", label.value().c_str(),
         delta.InMillisecondsF());
}
References v8::base::args, v8::anonymous_namespace{d8-console.cc}::GetTimerLabel(), v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeTicks::Now(), origin_, and v8::internal::v8_flags.
Trace()
void v8::D8Console::Trace (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 188 of file d8-console.cc.
                                                    {
  if (i::v8_flags.correctness_fuzzer_suppressions) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate_);
  i_isolate->PrintStack(stderr, i::Isolate::kPrintStackConcise);
}
References isolate_, v8::internal::Isolate::kPrintStackConcise, v8::internal::Isolate::PrintStack(), and v8::internal::v8_flags.
Warn()
void v8::D8Console::Warn (const debug::ConsoleCallArguments & args, const v8::debug::ConsoleContext &) [override], [private], [virtual]
Reimplemented from v8::debug::ConsoleDelegate.
Definition at line 94 of file d8-console.cc.
                                                   {
  WriteToFile("console.warn", stdout, isolate_, args);
}
References v8::base::args, isolate_, and v8::WriteToFile().
Member Data Documentation
isolate_
Isolate* v8::D8Console::isolate_ [private]
Definition at line 54 of file d8-console.h.
Referenced by Assert(), Debug(), DisposeProfiler(), Error(), Info(), Log(), Profile(), ProfileEnd(), Trace(), and Warn().
origin_
base::TimeTicks v8::D8Console::origin_ [private]
Definition at line 61 of file d8-console.h.
Referenced by TimeStamp().
profiler_
CpuProfiler* v8::D8Console::profiler_ {nullptr} [private]
Definition at line 62 of file d8-console.h.
Referenced by DisposeProfiler(), Profile(), ProfileEnd(), profiler(), and ~D8Console().
profiler_active_
bool v8::D8Console::profiler_active_ {false} [private]
Definition at line 63 of file d8-console.h.
Referenced by DisposeProfiler(), Profile(), and ProfileEnd().
timers_
std::map<std::string, base::TimeTicks> v8::D8Console::timers_ [private]
Definition at line 59 of file d8-console.h.
Referenced by Time(), TimeEnd(), and TimeLog().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8-console.h
/mnt/V8SourceCode/src/d8/d8-console.cc