v8::internal::compiler::Node Class Reference
#include <node.h>
Classes
class InputEdges
struct OutOfLineInputs
struct Use
class UseEdges
class Uses
Public Types
using value_type = Node *
Public Member Functions
bool IsDead () const
void Kill ()
const Operator * op () const
constexpr IrOpcode::Value opcode () const
NodeId id () const
int InputCount () const
void Verify ()
Node * InputAt (int index) const
void ReplaceInput (int index, Node *new_to)
void AppendInput (Zone *zone, Node *new_to)
void InsertInput (Zone *zone, int index, Node *new_to)
void InsertInputs (Zone *zone, int index, int count)
Node * RemoveInput (int index)
void NullAllInputs ()
void TrimInputCount (int new_input_count)
void EnsureInputCount (Zone *zone, int new_input_count)
int UseCount () const
int BranchUseCount () const
void ReplaceUses (Node *replace_to)
InputEdges input_edges ()
Inputs inputs () const
base::Vector< Node * > inputs_vector () const
UseEdges use_edges ()
Uses uses ()
bool OwnedBy (Node const *owner) const
bool OwnedBy (Node const *owner1, Node const *owner2) const
void Print () const
void Print (int depth) const
void Print (std::ostream &, int depth=1) const
const_iterator begin () const
const_iterator end () const
bool empty () const
int count () const
value_type operator[] (int index) const
Inputs (ZoneNodePtr const *input_root, int count)
Static Public Member Functions
static Node * New (Zone *zone, NodeId id, const Operator *op, int input_count, Node *const *inputs, bool has_extensible_inputs)
static Node * Clone (Zone *zone, NodeId id, const Node *node)
Private Types
using ZoneUsePtr = GraphZoneTraits::Ptr< Use >
using ZoneOutOfLineInputsPtr = GraphZoneTraits::Ptr< OutOfLineInputs >
using IdField = base::BitField< NodeId, 0, 24 >
using InlineCountField = base::BitField< unsigned, 24, 4 >
using InlineCapacityField = base::BitField< unsigned, 28, 4 >
Private Member Functions
Node (NodeId id, const Operator *op, int inline_count, int inline_capacity)
Node (const Node &)=delete
Node & operator= (const Node &)=delete
Address inputs_location () const
ZoneNodePtr * inline_inputs () const
OutOfLineInputs * outline_inputs () const
void set_outline_inputs (OutOfLineInputs *outline)
ZoneNodePtr const * GetInputPtrConst (int input_index) const
ZoneNodePtr * GetInputPtr (int input_index)
Use * GetUsePtr (int input_index)
void AppendUse (Use *use)
void RemoveUse (Use *use)
void * operator new (size_t, void *location)
void set_op (const Operator *op)
Type type () const
void set_type (Type type)
Mark mark () const
void set_mark (Mark mark)
bool has_inline_inputs () const
void ClearInputs (int start, int count)
Static Private Member Functions
template<typename NodePtrT >
static Node * NewImpl (Zone *zone, NodeId id, const Operator *op, int input_count, NodePtrT const *inputs, bool has_extensible_inputs)
Private Attributes
const Operator * op_
Type type_
Mark mark_
uint32_t bit_field_
ZoneUsePtr first_use_
ZoneNodePtr const * input_root_
int count_
Static Private Attributes
static const int kOutlineMarker = InlineCountField::kMax
static const int kMaxInlineCapacity = InlineCapacityField::kMax - 1
Friends
class Edge
class NodeMarkerBase
class NodeProperties
Detailed Description
Definition at line 41 of file node.h.
Member Typedef Documentation
IdField
using v8::internal::compiler::Node::IdField = base::BitField<NodeId, 0, 24> [private]
Definition at line 291 of file node.h.
InlineCapacityField
using v8::internal::compiler::Node::InlineCapacityField = base::BitField<unsigned, 28, 4> [private]
Definition at line 293 of file node.h.
InlineCountField
using v8::internal::compiler::Node::InlineCountField = base::BitField<unsigned, 24, 4> [private]
Definition at line 292 of file node.h.
value_type
using v8::internal::compiler::Node::value_type = Node*
Definition at line 401 of file node.h.
ZoneOutOfLineInputsPtr
using v8::internal::compiler::Node::ZoneOutOfLineInputsPtr = GraphZoneTraits::Ptr<OutOfLineInputs> [private]
Definition at line 178 of file node.h.
ZoneUsePtr
using v8::internal::compiler::Node::ZoneUsePtr = GraphZoneTraits::Ptr<Use> [private]
Definition at line 163 of file node.h.
Constructor & Destructor Documentation
Node() [1/2]
v8::internal::compiler::Node::Node (NodeId id, const Operator * op, int inline_count, int inline_capacity) [private]
Definition at line 392 of file node.cc.
    : op_(op),
      mark_(0),
      bit_field_(IdField::encode(id) | InlineCountField::encode(inline_count) |
                 InlineCapacityField::encode(inline_capacity)),
      first_use_(nullptr) {
  // Check that the id didn't overflow.
  static_assert(IdField::kMax < std::numeric_limits<NodeId>::max());
  CHECK(IdField::is_valid(id));
  // Inputs must either be out of line or within the inline capacity.
  DCHECK(inline_count == kOutlineMarker || inline_count <= inline_capacity);
  DCHECK_LE(inline_capacity, kMaxInlineCapacity);
}
References CHECK, v8::internal::DCHECK(), DCHECK_LE, v8::base::BitField< T, shift, size, U >::is_valid(), v8::base::BitField< T, shift, size, U >::kMax, kMaxInlineCapacity, and kOutlineMarker.
Referenced by NewImpl().
Node() [2/2]
v8::internal::compiler::Node::Node (const Node &) [private], [delete]
Member Function Documentation
AppendInput()
void v8::internal::compiler::Node::AppendInput (Zone * zone, Node * new_to)
Definition at line 152 of file node.cc.
                                               {
  DCHECK_NOT_NULL(zone);
  DCHECK_NOT_NULL(new_to);
  int const inline_count = InlineCountField::decode(bit_field_);
  int const inline_capacity = InlineCapacityField::decode(bit_field_);
  if (inline_count < inline_capacity) {
    // Append inline input.
    bit_field_ = InlineCountField::update(bit_field_, inline_count + 1);
    *GetInputPtr(inline_count) = new_to;
    Use* use = GetUsePtr(inline_count);
    static_assert(InlineCapacityField::kMax <= Use::InputIndexField::kMax);
    use->bit_field_ = Use::InputIndexField::encode(inline_count) |
                      Use::InlineField::encode(true);
    new_to->AppendUse(use);
  } else {
    // Append out-of-line input.
    int const input_count = InputCount();
    OutOfLineInputs* outline = nullptr;
    if (inline_count != kOutlineMarker) {
      // switch to out of line inputs.
      outline = OutOfLineInputs::New(zone, input_count * 2 + 3);
      outline->node_ = this;
      outline->ExtractFrom(GetUsePtr(0), GetInputPtr(0), input_count);
      bit_field_ = InlineCountField::update(bit_field_, kOutlineMarker);
      set_outline_inputs(outline);
    } else {
      // use current out of line inputs.
      outline = outline_inputs();
      if (input_count >= outline->capacity_) {
        // out of space in out-of-line inputs.
        outline = OutOfLineInputs::New(zone, input_count * 2 + 3);
        outline->node_ = this;
        outline->ExtractFrom(GetUsePtr(0), GetInputPtr(0), input_count);
        set_outline_inputs(outline);
      }
    }
    outline->count_++;
    *GetInputPtr(input_count) = new_to;
    Use* use = GetUsePtr(input_count);
    CHECK(Use::InputIndexField::is_valid(input_count));
    use->bit_field_ = Use::InputIndexField::encode(input_count) |
                      Use::InlineField::encode(false);
    new_to->AppendUse(use);
  }
  Verify();
}
References AppendUse(), bit_field_, v8::internal::compiler::Node::OutOfLineInputs::capacity_, CHECK, v8::internal::compiler::Node::OutOfLineInputs::count_, DCHECK_NOT_NULL, v8::base::BitField< T, shift, size, U >::decode(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), GetInputPtr(), GetUsePtr(), v8::internal::compiler::turboshaft::detail::input_count(), InputCount(), v8::base::BitField< T, shift, size, U >::is_valid(), v8::base::BitField< T, shift, size, U >::kMax, kOutlineMarker, v8::internal::compiler::Node::OutOfLineInputs::New(), v8::internal::compiler::Node::OutOfLineInputs::node_, outline_inputs(), set_outline_inputs(), v8::base::BitField< T, shift, size, U >::update(), use(), and Verify().
Referenced by v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::SimplifiedLowering::DoIntegerToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit(), v8::internal::compiler::SimplifiedLowering::DoMax(), v8::internal::compiler::SimplifiedLowering::DoNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoOrderedNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoSigned32ToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoUnsigned32ToUint8Clamped(), EnsureInputCount(), InsertInput(), InsertInputs(), v8::internal::compiler::BytecodeGraphBuilder::MergeControl(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), and v8::internal::compiler::RepresentationSelector::VisitNode().
AppendUse()
void v8::internal::compiler::Node::AppendUse (Use * use) [private]
Definition at line 407 of file node.cc.
                             {
  DCHECK(first_use_ == nullptr || first_use_->prev == nullptr);
  DCHECK_EQ(this, *use->input_ptr());
  use->next = first_use_;
  use->prev = nullptr;
  if (first_use_) first_use_->prev = use;
  first_use_ = use;
}
References v8::internal::DCHECK(), DCHECK_EQ, first_use_, and use().
Referenced by AppendInput(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), NewImpl(), ReplaceInput(), and v8::internal::compiler::Edge::UpdateTo().
begin()
const_iterator v8::internal::compiler::Node::begin () const [inline]
Referenced by v8::internal::compiler::LoopTree::HeaderNode().
BranchUseCount()
int v8::internal::compiler::Node::BranchUseCount () const
Definition at line 294 of file node.cc.
                               {
  int use_count = 0;
  for (Use* use = first_use_; use; use = use->next) {
    if (use->from()->opcode() == IrOpcode::kBranch) {
      ++use_count;
    }
  }
  return use_count;
}
References first_use_, v8::internal::compiler::turboshaft::kBranch, and use().
ClearInputs()
void v8::internal::compiler::Node::ClearInputs (int start, int count) [private]
Definition at line 242 of file node.cc.
                                           {
  ZoneNodePtr* input_ptr = GetInputPtr(start);
  Use* use_ptr = GetUsePtr(start);
  while (count-- > 0) {
    DCHECK_EQ(input_ptr, use_ptr->input_ptr());
    Node* input = *input_ptr;
    *input_ptr = nullptr;
    if (input) input->RemoveUse(use_ptr);
    input_ptr++;
    use_ptr--;
  }
  Verify();
}
References DCHECK_EQ, GetInputPtr(), GetUsePtr(), v8::internal::compiler::Node::Use::input_ptr(), RemoveUse(), and Verify().
Referenced by NullAllInputs(), and TrimInputCount().
Clone()
Node * v8::internal::compiler::Node::Clone (Zone * zone, NodeId id, const Node * node) [static]
Definition at line 134 of file node.cc.
                                                         {
  int const input_count = node->InputCount();
  ZoneNodePtr const* const inputs = node->has_inline_inputs()
                                        ? node->inline_inputs()
                                        : node->outline_inputs()->inputs();
  Node* const clone = NewImpl(zone, id, node->op(), input_count, inputs, false);
  clone->set_type(node->type());
  return clone;
}
References has_inline_inputs(), inline_inputs(), v8::internal::compiler::turboshaft::detail::input_count(), InputCount(), v8::internal::compiler::Node::OutOfLineInputs::inputs(), inputs(), NewImpl(), op(), outline_inputs(), set_type(), and type().
Referenced by v8::internal::compiler::TFGraph::CloneNode().
count()
int v8::internal::compiler::Node::count () const [inline]
Definition at line 408 of file node.h.
{ return count_; }
References count_.
Referenced by v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), and InsertInputs().
empty()
bool v8::internal::compiler::Node::empty () const [inline]
Definition at line 407 of file node.h.
{ return count_ == 0; }
References count_.
Referenced by Kill().
end()
const_iterator v8::internal::compiler::Node::end () const [inline]
EnsureInputCount()
void v8::internal::compiler::Node::EnsureInputCount (Zone * zone, int new_input_count)
Definition at line 272 of file node.cc.
                                                           {
  int current_count = InputCount();
  DCHECK_NE(current_count, 0);
  if (current_count > new_input_count) {
    TrimInputCount(new_input_count);
  } else if (current_count < new_input_count) {
    Node* dummy = InputAt(current_count - 1);
    do {
      AppendInput(zone, dummy);
      current_count++;
    } while (current_count < new_input_count);
  }
}
References AppendInput(), DCHECK_NE, InputAt(), InputCount(), and TrimInputCount().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf().
GetInputPtr()
ZoneNodePtr* v8::internal::compiler::Node::GetInputPtr (int input_index) [inline], [private]
Definition at line 259 of file node.h.
                                            {
    return has_inline_inputs() ? &(inline_inputs()[input_index])
                               : &(outline_inputs()->inputs()[input_index]);
  }
Referenced by AppendInput(), and ClearInputs().
GetInputPtrConst()
ZoneNodePtr const* v8::internal::compiler::Node::GetInputPtrConst (int input_index) const [inline], [private]
Definition at line 255 of file node.h.
                                                             {
    return has_inline_inputs() ? &(inline_inputs()[input_index])
                               : &(outline_inputs()->inputs()[input_index]);
  }
GetUsePtr()
Use* v8::internal::compiler::Node::GetUsePtr (int input_index) [inline], [private]
Definition at line 263 of file node.h.
                                  {
    Use* ptr = has_inline_inputs() ? reinterpret_cast<Use*>(this)
                                   : reinterpret_cast<Use*>(outline_inputs());
    return &ptr[-1 - input_index];
  }
Referenced by AppendInput(), and ClearInputs().
has_inline_inputs()
bool v8::internal::compiler::Node::has_inline_inputs () const [inline], [private]
Definition at line 285 of file node.h.
                                        {
    return InlineCountField::decode(bit_field_) != kOutlineMarker;
  }
Referenced by Clone(), and TrimInputCount().
id()
NodeId v8::internal::compiler::Node::id () const [inline]
Definition at line 57 of file node.h.
{ return IdField::decode(bit_field_); }
Referenced by v8::internal::compiler::MemoryLowering::AllocationGroup::Add(), v8::internal::compiler::WasmAddressReassociation::AddCandidate(), v8::internal::compiler::InductionVariable::AddLowerBound(), v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::InductionVariable::AddUpperBound(), v8::internal::compiler::ControlEquivalence::AllocateData(), v8::internal::compiler::MemoryLowering::AllocationGroup::AllocationGroup(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllSameAddress(), v8::internal::compiler::Schedule::block(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckCallInputs(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::Verifier::Visitor::CheckNotTyped(), v8::internal::compiler::Verifier::Visitor::CheckOutput(), v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::compiler::SimplifiedLoweringVerifier::CheckType(), v8::internal::compiler::Verifier::Visitor::CheckTypeIs(), v8::internal::compiler::Verifier::Visitor::CheckTypeMaybe(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForFloat32Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForFloat64Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForInt32Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForInt64Op(), v8::internal::compiler::Verifier::Visitor::CheckValueInputIs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsCompressedOrTagged(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsCompressedOrTaggedOrInt32(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTagged(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTaggedOrPointer(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputRepresentationIs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueIsTaggedOrInt32(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::LoopTree::ContainingLoop(), v8::internal::compiler::MemoryLowering::AllocationGroup::Contains(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::Scheduler::DecrementUnscheduledUseCount(), v8::internal::compiler::RepresentationSelector::DeferReplacement(), v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::compiler::RepresentationSelector::EnqueueInput(), v8::internal::compiler::MemoryOptimizer::EnqueueMerge(), v8::internal::compiler::LoopVariableOptimizer::FindInductionVariable(), v8::internal::compiler::SparseSidetable< T >::Get(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get(), v8::internal::compiler::NodeAuxData< T, def >::Get(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Get(), v8::internal::compiler::ControlEquivalence::GetData(), v8::internal::compiler::Scheduler::GetData(), v8::internal::compiler::RepresentationSelector::GetInfo(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::GetRepresentation(), v8::internal::compiler::StringBuilderOptimizer::GetStatus(), v8::internal::compiler::SimplifiedLoweringVerifier::GetType(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), v8::internal::compiler::LoopFinder::HasMarkedExits(), v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount(), v8::internal::compiler::LoopFinderImpl::info(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::SimplifiedLoweringVerifier::InputTruncation(), v8::internal::compiler::LoopFinderImpl::IsInLoop(), v8::internal::compiler::AllNodes::IsReachable(), v8::internal::compiler::Schedule::IsScheduled(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::compiler::LoopFinderImpl::LoopNum(), v8::internal::compiler::RepresentationSelector::MarkAsPossibleRevisit(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::Schedule::MovePhis(), v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::compiler::ObserveNodeManager::OnNodeChanged(), v8::internal::compiler::JSInliningHeuristic::CandidateCompare::operator()(), v8::internal::compiler::operator<<(), v8::internal::compiler::Sidetable< T >::operator[](), v8::internal::compiler::Schedule::PlanNode(), v8::internal::compiler::PackNode::Print(), v8::internal::compiler::CsaLoadElimination::HalfState::Print(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::PrintDebugHelp(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledNode(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::LoopFinderImpl::PropagateBackwardMarks(), v8::internal::compiler::LoopFinderImpl::PropagateForwardMarks(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::RepresentationSelector::PropagateTruncation(), v8::internal::compiler::RepresentationSelector::PushNodeToRevisitIfVisited(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::EscapeAnalysis::Reduce(), v8::internal::compiler::GraphReducer::Replace(), v8::internal::compiler::SimplifiedLoweringVerifier::ReportInvalidTypeCombination(), v8::internal::compiler::SimplifiedLoweringVerifier::ResizeDataIfNecessary(), v8::internal::compiler::RepresentationSelector::RetypeNode(), v8::internal::compiler::EffectGraphReducer::Revisit(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::compiler::SafeId(), v8::internal::compiler::NodeOriginTable::Scope::Scope(), v8::internal::compiler::SparseSidetable< T >::Set(), v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Set(), v8::internal::compiler::RedundancyElimination::PathChecksForEffectNodes::Set(), v8::internal::compiler::NodeAuxData< T, def >::Set(), v8::internal::compiler::LoopFinderImpl::SetBackwardMark(), v8::internal::compiler::Schedule::SetBlockForNode(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetEscaped(), v8::internal::compiler::LoopFinderImpl::SetForwardMark(), v8::internal::compiler::LoopFinderImpl::SetLoopMark(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetReplacement(), v8::internal::compiler::StringBuilderOptimizer::SetStatus(), v8::internal::compiler::SimplifiedLoweringVerifier::SetTruncation(), v8::internal::compiler::SimplifiedLoweringVerifier::SetType(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::ObserveNodeManager::StartObserving(), v8::internal::compiler::anonymous_namespace{state-values-utils.cc}::StateValuesHashKey(), v8::internal::compiler::CFGBuilder::TraceConnect(), v8::internal::compiler::RepresentationChanger::TypeError(), v8::internal::compiler::Revectorizer::UpdateSources(), v8::internal::compiler::StringBuilderOptimizer::UpdateStatus(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement(), v8::internal::compiler::ControlEquivalence::VisitBackedge(), v8::internal::compiler::PrepareUsesVisitor::Visited(), v8::internal::compiler::PrepareUsesVisitor::VisitInputs(), v8::internal::compiler::ControlEquivalence::VisitMid(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::ControlEquivalence::VisitPost(), v8::internal::compiler::ControlEquivalence::VisitPre(), v8::internal::compiler::RepresentationSelector::VisitUnused(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::WriteBarrierAssertFailed().
inline_inputs()
ZoneNodePtr* v8::internal::compiler::Node::inline_inputs () const [inline], [private]
Definition at line 245 of file node.h.
                                     {
    return reinterpret_cast<ZoneNodePtr*>(inputs_location());
  }
Referenced by Clone(), input_edges(), inputs(), inputs_vector(), and NewImpl().
input_edges()
Node::InputEdges v8::internal::compiler::Node::input_edges () [inline]
Definition at line 466 of file node.h.
                                 {
  int inline_count = InlineCountField::decode(bit_field_);
  if (inline_count != kOutlineMarker) {
    return InputEdges(inline_inputs(), reinterpret_cast<Use*>(this) - 1,
                      inline_count);
  } else {
    return InputEdges(outline_inputs()->inputs(),
                      reinterpret_cast<Use*>(outline_inputs()) - 1,
                      outline_inputs()->count_);
  }
}
References bit_field_, count_, v8::base::BitField< T, shift, size, U >::decode(), inline_inputs(), inputs(), kOutlineMarker, and outline_inputs().
Referenced by v8::internal::compiler::ControlEquivalence::DFSPush(), v8::internal::compiler::LateEscapeAnalysis::Reduce(), v8::internal::compiler::ControlEquivalence::RunUndirectedDFS(), v8::internal::compiler::Scheduler::UpdatePlacement(), and v8::internal::compiler::PrepareUsesVisitor::VisitInputs().
InputAt()
Node* v8::internal::compiler::Node::InputAt (int index) const [inline]
Definition at line 70 of file node.h.
                                 {
    DCHECK_LE(0, index);
    DCHECK_LT(index, InputCount());
    return *GetInputPtrConst(index);
  }
References DCHECK_LE, DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::LoopVariableOptimizer::AddCmpToLimits(), v8::internal::compiler::MemoryOptimizer::AllocationTypeNeedsUpdateToOld(), v8::internal::compiler::RepresentationSelector::BothInputsAre(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc}::CanBePaired(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanLoopAllocate(), v8::internal::compiler::RepresentationSelector::CanSpeculateAdditiveSafeInteger(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckCallInputs(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForFloat32Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForFloat64Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForInt32Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForInt64Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsCompressedOrTagged(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsCompressedOrTaggedOrInt32(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTagged(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTaggedOrPointer(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputRepresentationIs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueIsTaggedOrInt32(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectStateValuesOwnedUses(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::FrameState::context(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), v8::internal::compiler::ControlEquivalence::DetermineParticipation(), v8::internal::compiler::DiamondMatcher::DiamondMatcher(), v8::internal::compiler::SimplifiedLowering::DoIntegerToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::SimplifiedLowering::DoMax(), v8::internal::compiler::SimplifiedLowering::DoMin(), v8::internal::compiler::SimplifiedLowering::DoNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoNumberToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoOrderedNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoSigned32ToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoUnsigned32ToUint8Clamped(), v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::EffectInputOf(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::RepresentationSelector::EnqueueInput(), v8::internal::compiler::MemoryOptimizer::EnqueueMerge(), EnsureInputCount(), v8::internal::compiler::DiamondMatcher::FalseInputOf(), v8::internal::compiler::SimplifiedLowering::Float64Round(), v8::internal::compiler::SimplifiedLowering::Float64Sign(), v8::internal::compiler::FrameState::function(), v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetMemoryOffsetValue(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetNodeAddress(), v8::internal::compiler::NodeProperties::GetProjectionType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::LoopFinder::HasMarkedExits(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::NodeMatcher::InputAt(), v8::internal::compiler::RepresentationSelector::InputCannotBe(), v8::internal::compiler::RepresentationSelector::InputIs(), v8::internal::compiler::SimplifiedLoweringVerifier::InputTruncation(), v8::internal::compiler::SimplifiedLoweringVerifier::InputType(), InsertInput(), InsertInputs(), v8::internal::compiler::SimplifiedLowering::Int32Abs(), v8::internal::compiler::SimplifiedLowering::Int32Sign(), v8::internal::compiler::CFGBuilder::IsFinalMerge(), v8::internal::compiler::StateValuesCache::IsKeysEqualToNode(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::compiler::JSBinopReduction::left_type(), v8::internal::compiler::FrameState::locals(), v8::internal::compiler::SelectLowering::LowerSelect(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias(), v8::internal::compiler::RepresentationSelector::OneInputCannotBe(), v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::compiler::operator<<(), v8::internal::compiler::FrameState::outer_frame_state(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::OwnedByAddressingOperand(), v8::internal::compiler::FrameState::parameters(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::PhiInputsAreConcatsOrPhi(), v8::internal::compiler::JSONGraphWriter::PrintEdges(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSIntrinsicLowering::ReduceCheckTurboshaftTypeOf(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertHighWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertLowWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64RoundDown(), v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs(), v8::internal::compiler::EffectGraphReducer::ReduceFrom(), v8::internal::compiler::BranchElimination::ReduceIf(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigInt(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSTypedLowering::ReduceJSToString(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::WasmGCLowering::ReduceRttCanon(), v8::internal::compiler::CommonOperatorReducer::ReduceSelect(), v8::internal::compiler::CommonOperatorReducer::ReduceStaticAssert(), v8::internal::compiler::MachineOperatorReducer::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::TypedOptimization::ReduceStringLength(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceTrapConditional(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::TypedOptimization::ReduceTypeOf(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), RemoveInput(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), v8::internal::compiler::NodeHashCache::Constructor::ReplaceInput(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::ResolveRenames(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::ResolveSameValueRenames(), v8::internal::compiler::JSBinopReduction::right_type(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::RepresentationSelector::RunVerifyPhase(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::Revectorizer::SetEffectInput(), v8::internal::compiler::Revectorizer::SetMemoryOpInputs(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::FrameState::stack(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), v8::internal::compiler::JSCallAccessor::target(), v8::internal::compiler::DiamondMatcher::TrueInputOf(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareForTestBit(), v8::internal::compiler::CodeAssembler::TryToIntPtrConstant(), v8::internal::compiler::CodeAssembler::TryToSmiConstant(), v8::internal::compiler::RepresentationSelector::TypePhi(), v8::internal::compiler::RepresentationSelector::TypeSelect(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::LoadElimination::UpdateStateForPhi(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw(), v8::internal::compiler::RepresentationSelector::VisitCheck(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::LoopVariableOptimizer::VisitIf(), v8::internal::compiler::LoopVariableOptimizer::VisitMerge(), v8::internal::compiler::BitcastElider::VisitNode(), v8::internal::compiler::StringBuilderOptimizer::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNoop(), v8::internal::compiler::RepresentationSelector::VisitObjectIs(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), v8::internal::compiler::RepresentationSelector::VisitSelect(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
InputCount()
int v8::internal::compiler::Node::InputCount () const [inline]
Definition at line 59 of file node.h.
                         {
    return has_inline_inputs() ? InlineCountField::decode(bit_field_)
                               : outline_inputs()->count_;
  }
Referenced by AppendInput(), v8::internal::compiler::RawMachineAssembler::AppendPhiInput(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanLoopAllocate(), v8::internal::compiler::SimplifiedOperatorReducer::Change(), v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses(), Clone(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectStateValuesOwnedUses(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::DiamondMatcher::DiamondMatcher(), v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename(), v8::internal::compiler::MemoryOptimizer::EnqueueMerge(), EnsureInputCount(), v8::internal::compiler::NodeProperties::Equals(), v8::internal::compiler::DiamondMatcher::FalseInputOf(), v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::NodeProperties::HashCode(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::SparseInputMask::InputIterator::InputIterator(), InsertInput(), InsertInputs(), v8::internal::compiler::StateValuesCache::IsKeysEqualToNode(), v8::internal::compiler::SparseInputMask::IterateOverInputs(), NullAllInputs(), v8::internal::compiler::operator<<(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::PhiInputsAreConcatsOrPhi(), v8::internal::compiler::JSONGraphWriter::PrintEdges(), v8::internal::compiler::RepresentationSelector::ProcessRemainingInputs(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::CommonOperatorReducer::ReduceEffectPhi(), v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), RemoveInput(), v8::internal::compiler::WasmAddressReassociation::ReplaceInputs(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::ScaleMatcher(), v8::internal::compiler::LoopFinderImpl::SetLoopMarkForLoopHeader(), TrimInputCount(), v8::internal::compiler::DiamondMatcher::TrueInputOf(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::LoadElimination::UpdateStateForPhi(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::RepresentationSelector::VisitBinop(), v8::internal::compiler::RepresentationSelector::VisitInputs(), v8::internal::compiler::RepresentationSelector::VisitLeaf(), v8::internal::compiler::LoopVariableOptimizer::VisitMerge(), v8::internal::compiler::BitcastElider::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), v8::internal::compiler::RepresentationSelector::VisitPhi(), v8::internal::compiler::RepresentationSelector::VisitReturn(), and v8::internal::compiler::RepresentationSelector::VisitStateValues().
inputs()
Node::Inputs v8::internal::compiler::Node::inputs () const [inline]
Definition at line 478 of file node.h.
                              {
  int inline_count = InlineCountField::decode(bit_field_);
  if (inline_count != kOutlineMarker) {
    return Inputs(inline_inputs(), inline_count);
  } else {
    return Inputs(outline_inputs()->inputs(), outline_inputs()->count_);
  }
}
References bit_field_, count_, v8::base::BitField< T, shift, size, U >::decode(), inline_inputs(), Inputs(), kOutlineMarker, and outline_inputs().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), Clone(), v8::internal::compiler::CFGBuilder::ConnectMerge(), v8::internal::compiler::NodeProperties::Equals(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::FindDeadInput(), v8::internal::compiler::NodeProperties::HashCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), input_edges(), inputs_vector(), IsDead(), v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstant(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsPhiContainingGivenInputs(), New(), NewImpl(), v8::internal::compiler::operator<<(), v8::internal::compiler::GraphC1Visualizer::PrintInputs(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledNode(), v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), v8::internal::compiler::CommonOperatorReducer::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::BranchElimination::ReduceMerge(), v8::internal::compiler::WasmGCOperatorReducer::ReduceMerge(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::GraphReducer::ReduceTop(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::GraphTrimmer::TrimGraph(), and v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition().
Inputs()
v8::internal::compiler::Node::Inputs (ZoneNodePtr const * input_root, int count) [inline], [explicit]
Definition at line 412 of file node.h.
      : input_root_(input_root), count_(count) {}
Referenced by v8::internal::compiler::NodeProperties::Equals(), inputs(), IsDead(), v8::internal::compiler::CommonOperatorReducer::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::BranchElimination::ReduceMerge(), v8::internal::compiler::WasmGCOperatorReducer::ReduceMerge(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::GraphReducer::ReduceTop(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::BytecodeGraphBuilder::Environment::StateValuesRequireUpdate(), and v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition().
inputs_location()
Address v8::internal::compiler::Node::inputs_location () const [inline], [private]
Definition at line 308 of file node.h.
                                    {
  return reinterpret_cast<Address>(this) + sizeof(Node);
}
inputs_vector()
base::Vector< Node * > v8::internal::compiler::Node::inputs_vector () const [inline]
Definition at line 487 of file node.h.
                                            {
  int inline_count = InlineCountField::decode(bit_field_);
  if (inline_count != kOutlineMarker) {
    return base::VectorOf<Node*>(inline_inputs(), inline_count);
  } else {
    return base::VectorOf<Node*>(outline_inputs()->inputs(),
                                 outline_inputs()->count_);
  }
}
References bit_field_, count_, v8::base::BitField< T, shift, size, U >::decode(), inline_inputs(), inputs(), kOutlineMarker, and outline_inputs().
InsertInput()
void v8::internal::compiler::Node::InsertInput (Zone * zone, int index, Node * new_to)
Definition at line 201 of file node.cc.
                                                          {
  DCHECK_NOT_NULL(zone);
  DCHECK_LE(0, index);
  DCHECK_LT(index, InputCount());
  AppendInput(zone, InputAt(InputCount() - 1));
  for (int i = InputCount() - 1; i > index; --i) {
    ReplaceInput(i, InputAt(i - 1));
  }
  ReplaceInput(index, new_to);
  Verify();
}
References AppendInput(), DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, InputAt(), InputCount(), ReplaceInput(), and Verify().
Referenced by v8::internal::compiler::RawMachineAssembler::AppendPhiInput(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::SimplifiedLowering::DoMin(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSIntrinsicLowering::ReduceCall(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), and v8::internal::compiler::MemoryLowering::ReduceStoreField().
InsertInputs()
void v8::internal::compiler::Node::InsertInputs (Zone * zone, int index, int count)
Definition at line 213 of file node.cc.
                                                        {
  DCHECK_NOT_NULL(zone);
  DCHECK_LE(0, index);
  DCHECK_LT(0, count);
  DCHECK_LT(index, InputCount());
  for (int i = 0; i < count; i++) {
    AppendInput(zone, InputAt(std::max(InputCount() - count, 0)));
  }
  for (int i = InputCount() - count - 1; i >= std::max(index, count); --i) {
    ReplaceInput(i, InputAt(i - count));
  }
  for (int i = 0; i < count; i++) {
    ReplaceInput(index + i, nullptr);
  }
  Verify();
}
References AppendInput(), count(), DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, InputAt(), InputCount(), ReplaceInput(), and Verify().
IsDead()
bool v8::internal::compiler::Node::IsDead () const [inline]
Definition at line 461 of file node.h.
                        {
  Node::Inputs inputs = this->inputs();
  return inputs.count() > 0 && inputs[0] == nullptr;
}
References inputs(), and Inputs().
Referenced by v8::internal::compiler::JSInliningHeuristic::Finalize(), v8::internal::compiler::LateEscapeAnalysis::Finalize(), v8::internal::compiler::ValueNumberingReducer::Grow(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsRename(), v8::internal::compiler::GraphTrimmer::MarkAsLive(), v8::internal::compiler::LoadElimination::AbstractField::Merge(), v8::internal::compiler::ValueNumberingReducer::Reduce(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::GraphReducer::ReduceTop(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::ResolveSameValueRenames(), v8::internal::compiler::GraphTrimmer::TrimGraph(), and v8::internal::compiler::MemoryOptimizer::VisitNode().
Kill()
void v8::internal::compiler::Node::Kill ()
Definition at line 145 of file node.cc.
                {
  DCHECK_NOT_NULL(op());
  NullAllInputs();
  DCHECK(uses().empty());
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, empty(), NullAllInputs(), op(), and uses().
Referenced by v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceTrapConditional(), v8::internal::compiler::WasmGCLowering::ReduceTypeGuard(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::GraphReducer::Replace(), v8::internal::compiler::MemoryOptimizer::ReplaceUsesAndKillNode(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), and v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch().
mark()
Mark v8::internal::compiler::Node::mark () const [inline], [private]
Definition at line 282 of file node.h.
{ return mark_; }
Referenced by v8::internal::compiler::NodeMarkerBase::Get(), and v8::internal::compiler::NodeMarkerBase::Set().
New()
Node * v8::internal::compiler::Node::New (Zone * zone, NodeId id, const Operator * op, int input_count, Node *const * inputs, bool has_extensible_inputs) [static]
Definition at line 129 of file node.cc.
                                                                 {
  return NewImpl(zone, id, op, input_count, inputs, has_extensible_inputs);
}
References v8::internal::compiler::turboshaft::detail::input_count(), inputs(), NewImpl(), and op().
Referenced by v8::internal::compiler::TFGraph::NewNodeUnchecked().
NewImpl()
template<typename NodePtrT >
Node * v8::internal::compiler::Node::NewImpl (Zone * zone, NodeId id, const Operator * op, int input_count, NodePtrT const * inputs, bool has_extensible_inputs) [inline], [static], [private]
Definition at line 58 of file node.cc.
                                                                        {
  DCHECK_GE(input_count, 0);
  ZoneNodePtr* input_ptr;
  Use* use_ptr;
  Node* node;
  bool is_inline;
  // Verify that none of the inputs are {nullptr}.
  for (int i = 0; i < input_count; i++) {
    if (inputs[i] == nullptr) {
      FATAL("Node::New() Error: #%d:%s[%d] is nullptr", static_cast<int>(id),
            op->mnemonic(), i);
    }
  }
  if (input_count > kMaxInlineCapacity) {
    // Allocate out-of-line inputs.
    int capacity =
        has_extensible_inputs ? input_count + kMaxInlineCapacity : input_count;
    OutOfLineInputs* outline = OutOfLineInputs::New(zone, capacity);
    // Allocate node, with space for OutOfLineInputs pointer.
    void* node_buffer = zone->Allocate<NodeWithOutOfLineInputs>(
        sizeof(Node) + sizeof(ZoneOutOfLineInputsPtr));
    node = new (node_buffer) Node(id, op, kOutlineMarker, 0);
    node->set_outline_inputs(outline);
    outline->node_ = node;
    outline->count_ = input_count;
    input_ptr = outline->inputs();
    use_ptr = reinterpret_cast<Use*>(outline);
    is_inline = false;
  } else {
    // Allocate node with inline inputs. Capacity must be at least 1 so that
    // an OutOfLineInputs pointer can be stored when inputs are added later.
    int capacity = std::max(1, input_count);
    if (has_extensible_inputs) {
      const int max = kMaxInlineCapacity;
      capacity = std::min(input_count + 3, max);
    }
    size_t size = sizeof(Node) + capacity * (sizeof(ZoneNodePtr) + sizeof(Use));
    intptr_t raw_buffer =
        reinterpret_cast<intptr_t>(zone->Allocate<NodeWithInLineInputs>(size));
    void* node_buffer =
        reinterpret_cast<void*>(raw_buffer + capacity * sizeof(Use));
    node = new (node_buffer) Node(id, op, input_count, capacity);
    input_ptr = node->inline_inputs();
    use_ptr = reinterpret_cast<Use*>(node);
    is_inline = true;
  }
  // Initialize the input pointers and the uses.
  CHECK_IMPLIES(input_count > 0,
                Use::InputIndexField::is_valid(input_count - 1));
  for (int current = 0; current < input_count; ++current) {
    Node* to = *inputs++;
    input_ptr[current] = to;
    Use* use = use_ptr - 1 - current;
    use->bit_field_ = Use::InputIndexField::encode(current) |
                      Use::InlineField::encode(is_inline);
    to->AppendUse(use);
  }
  node->Verify();
  return node;
}
References v8::internal::Zone::Allocate(), AppendUse(), CHECK_IMPLIES, v8::internal::compiler::Node::OutOfLineInputs::count_, DCHECK_GE, v8::base::BitField< T, shift, size, U >::encode(), FATAL, inline_inputs(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::OutOfLineInputs::inputs(), inputs(), v8::base::BitField< T, shift, size, U >::is_valid(), kMaxInlineCapacity, kOutlineMarker, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::OutOfLineInputs::New(), Node(), v8::internal::compiler::Node::OutOfLineInputs::node_, op(), size(), use(), and Verify().
Referenced by Clone(), and New().
NullAllInputs()
void v8::internal::compiler::Node::NullAllInputs ()
Definition at line 257 of file node.cc.
{ ClearInputs(0, InputCount()); }
References ClearInputs(), and InputCount().
Referenced by v8::internal::compiler::RepresentationSelector::DeferReplacement(), Kill(), and v8::internal::compiler::RepresentationSelector::VisitUnused().
op()
const Operator* v8::internal::compiler::Node::op () const [inline]
Definition at line 50 of file node.h.
{ return op_; }
Referenced by v8::internal::compiler::GraphAssembler::AddClonedNode(), v8::internal::compiler::AddMatcher< BinopMatcher, AddOpcode, SubOpcode, kMulOpcode, kShiftOpcode >::AddMatcher(), v8::internal::compiler::Schedule::AddNode(), v8::internal::compiler::anonymous_namespace{wasm-typer.cc}::AllInputsTyped(), v8::internal::compiler::MemoryOptimizer::AllocationTypeNeedsUpdateToOld(), v8::internal::compiler::NodeProperties::AllValueInputsAreTyped(), v8::internal::compiler::RawMachineAssembler::AppendPhiInput(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::BaseWithIndexAndDisplacementMatcher(), v8::internal::compiler::BytecodeGraphBuilder::Environment::BindRegistersToProjections(), v8::internal::compiler::RepresentationSelector::BothInputsAre(), v8::internal::compiler::CommonOperatorReducer::BranchSemanticsOf(), v8::internal::compiler::CFGBuilder::BuildBlockForNode(), v8::internal::compiler::CFGBuilder::BuildBlocksForSuccessors(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate(), v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc}::CanBePaired(), v8::internal::compiler::RepresentationSelector::CanSpeculateAdditiveSafeInteger(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckCallInputs(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::Verifier::Visitor::CheckNotTyped(), v8::internal::compiler::Verifier::Visitor::CheckOutput(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::compiler::SimplifiedLoweringVerifier::CheckType(), v8::internal::compiler::Verifier::Visitor::CheckTypeIs(), v8::internal::compiler::Verifier::Visitor::CheckTypeMaybe(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForFloat32Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForFloat64Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForInt32Op(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputForInt64Op(), v8::internal::compiler::Verifier::Visitor::CheckValueInputIs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsCompressedOrTagged(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsCompressedOrTaggedOrInt32(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTagged(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTaggedOrPointer(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputRepresentationIs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueIsTaggedOrInt32(), Clone(), v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::JSInliningHeuristic::CollectFunctions(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::CFGBuilder::ConnectBranch(), v8::internal::compiler::CFGBuilder::ConnectSwitch(), v8::internal::compiler::StartNode::ContextParameterIndex_MaybeNonStandardLayout(), v8::internal::compiler::Control::Control(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::DeadCodeElimination::DeadValue(), v8::internal::compiler::Typer::Decorator::Decorate(), v8::internal::compiler::Scheduler::DecrementUnscheduledUseCount(), v8::internal::compiler::RepresentationSelector::DeferReplacement(), v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::Effect::Effect(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::compiler::NodeProperties::Equals(), v8::internal::compiler::FastApiCallNode::FastCallArgumentCount(), v8::internal::compiler::NodeProperties::FindFrameStateBefore(), v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection(), v8::internal::compiler::StartNode::FormalParameterCount(), v8::internal::compiler::StartNode::FormalParameterCountWithoutReceiver(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::FrameStateFlagForCall(), v8::internal::compiler::JSBinopReduction::GetBinaryOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareBigIntOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareNumberOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareOperationHint(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetConstantValue(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::GetFunctionInfo(), v8::internal::compiler::GetModuleContext(), v8::internal::compiler::StringBuilderOptimizer::GetPhiPredecessorsCommonId(), v8::internal::compiler::NodeProperties::GetProjectionType(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::CodeAssembler::HandleException(), v8::internal::compiler::NodeProperties::HashCode(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::LoopFinder::HasMarkedExits(), v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::RepresentationSelector::InputCannotBe(), v8::internal::compiler::RepresentationSelector::InputIs(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::NodeProperties::IsContextEdge(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::IsContextParameter(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::compiler::NodeProperties::IsFrameStateEdge(), v8::internal::compiler::JSBinopReduction::IsInternalizedStringCompareOperation(), v8::internal::compiler::StateValuesCache::IsKeysEqualToNode(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLoadFloat16ArrayElement(), v8::internal::compiler::JSBinopReduction::IsReceiverCompareOperation(), v8::internal::compiler::JSBinopReduction::IsReceiverOrNullOrUndefinedCompareOperation(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::compiler::JSBinopReduction::IsStringCompareOperation(), v8::internal::compiler::JSBinopReduction::IsStringOrOddballCompareOperation(), v8::internal::compiler::JSBinopReduction::IsSymbolCompareOperation(), v8::internal::compiler::NodeProperties::IsValueEdge(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper(), v8::internal::compiler::StateValuesAccess::iterator::iterator(), Kill(), v8::internal::compiler::SelectLowering::LowerSelect(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RepresentationSelector::MarkAsPossibleRevisit(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::BytecodeGraphBuilder::MergeControl(), v8::internal::compiler::BytecodeGraphBuilder::MergeEffect(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::BytecodeGraphBuilder::MergeValue(), New(), NewImpl(), v8::internal::compiler::NodeProperties::NoObservableSideEffectBetween(), v8::internal::compiler::RepresentationSelector::OneInputCannotBe(), v8::internal::compiler::NodeMatcher::op(), v8::internal::compiler::operator<<(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::NodeProperties::PastContextIndex(), v8::internal::compiler::NodeProperties::PastControlIndex(), v8::internal::compiler::NodeProperties::PastEffectIndex(), v8::internal::compiler::NodeProperties::PastFrameStateIndex(), v8::internal::compiler::NodeProperties::PastValueIndex(), v8::internal::compiler::Schedule::PlanNode(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameState(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForFunctionEntryStackCheck(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck(), v8::internal::compiler::PackNode::Print(), v8::internal::compiler::CsaLoadElimination::HalfState::Print(), v8::internal::compiler::GraphC1Visualizer::PrintInputs(), v8::internal::compiler::GraphC1Visualizer::PrintNode(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledNode(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput(), v8::internal::compiler::RepresentationSelector::ProcessInput(), v8::internal::compiler::DeadCodeElimination::PropagateDeadControl(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::RepresentationSelector::PropagateTruncation(), v8::internal::compiler::StateValuesAccess::iterator::Push(), v8::internal::compiler::RepresentationSelector::PushNodeToRevisitIfVisited(), v8::internal::compiler::BranchElimination::Reduce(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSIntrinsicLowering::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::EscapeAnalysisReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::Typer::Visitor::Reduce(), v8::internal::compiler::ValueNumberingReducer::Reduce(), v8::internal::compiler::EscapeAnalysis::Reduce(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSIntrinsicLowering::ReduceCall(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::WasmGCLowering::ReduceIsNotNull(), v8::internal::compiler::WasmGCLowering::ReduceIsNull(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), v8::internal::compiler::WasmGCLowering::ReduceNull(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::BranchElimination::ReduceOtherControl(), v8::internal::compiler::CsaLoadElimination::ReduceOtherNode(), v8::internal::compiler::LoadElimination::ReduceOtherNode(), v8::internal::compiler::RedundancyElimination::ReduceOtherNode(), v8::internal::compiler::WasmLoadElimination::ReduceOtherNode(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::DeadCodeElimination::ReducePureNode(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::WasmGCLowering::ReduceRttCanon(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::MachineOperatorReducer::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::LoadElimination::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWordEqualForConstantRhs(), v8::internal::compiler::NodeProperties::RemoveNonValueInputs(), v8::internal::compiler::NodeProperties::RemoveValueInputs(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::ReplaceFrameStateInput(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::SimplifiedLoweringVerifier::ReportInvalidTypeCombination(), v8::internal::compiler::RepresentationSelector::RetypeNode(), v8::internal::compiler::EffectGraphReducer::Revisit(), v8::internal::compiler::LoopVariableOptimizer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::compiler::SafeMnemonic(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::VariableTracker::Scope::Scope(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::SearchAllocatingNode(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetEscaped(), v8::internal::compiler::EscapeAnalysisTracker::Scope::SetReplacement(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::JSTypeHintLowering::LoweringResult::SideEffectFree(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell(), v8::internal::compiler::StateValuesAccess::size(), v8::internal::compiler::FastApiCallNode::SlowCallArgumentCount(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), v8::internal::compiler::MachineOperatorReducer::SwapBranches(), v8::internal::compiler::RedundancyElimination::TakeChecksFromFirstEffect(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), v8::internal::compiler::CFGBuilder::TraceConnect(), v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareForTestBit(), v8::internal::compiler::StateValuesAccess::iterator::type(), v8::internal::compiler::RepresentationChanger::TypeError(), v8::internal::compiler::RepresentationSelector::TypePhi(), v8::internal::compiler::GraphAssembler::UpdateEffectControlWith(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::Revectorizer::UpdateSources(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueMatcher(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement(), v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw(), v8::internal::compiler::LoopVariableOptimizer::VisitBackedge(), v8::internal::compiler::ControlEquivalence::VisitBackedge(), v8::internal::compiler::RepresentationSelector::VisitBinop(), v8::internal::compiler::MemoryOptimizer::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitFastApiCall(), v8::internal::compiler::PrepareUsesVisitor::VisitInputs(), v8::internal::compiler::ControlEquivalence::VisitMid(), v8::internal::compiler::MemoryOptimizer::VisitNode(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode(), v8::internal::compiler::StringBuilderOptimizer::VisitNode(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), v8::internal::compiler::LoopVariableOptimizer::VisitOtherControl(), v8::internal::compiler::RepresentationSelector::VisitPhi(), v8::internal::compiler::ControlEquivalence::VisitPost(), v8::internal::compiler::ControlEquivalence::VisitPre(), v8::internal::compiler::RepresentationSelector::VisitSelect(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeInt32Binop(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), v8::internal::compiler::RepresentationSelector::VisitStateValues(), v8::internal::compiler::RepresentationSelector::VisitUnop(), v8::internal::compiler::RepresentationSelector::VisitUnused(), and v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::WriteBarrierAssertFailed().
opcode()
constexpr IrOpcode::Value v8::internal::compiler::Node::opcode () const [inline], [constexpr]
Definition at line 52 of file node.h.
                                         {
    DCHECK_GE(IrOpcode::kLast, op_->opcode());
    return static_cast<IrOpcode::Value>(op_->opcode());
  }
References DCHECK_GE, and v8::internal::compiler::IrOpcode::kLast.
Referenced by v8::internal::compiler::Schedule::AddBranch(), v8::internal::compiler::Schedule::AddCall(), v8::internal::compiler::WasmAddressReassociation::CandidateMemOps::AddCandidate(), v8::internal::compiler::RepresentationSelector::AdditiveSafeIntegerOverflowOp(), v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::Schedule::AddSwitch(), v8::internal::compiler::MemoryOptimizer::AllocationTypeNeedsUpdateToOld(), v8::internal::compiler::JSCallAccessor::argument_count(), v8::internal::compiler::RepresentationSelector::BigIntOp(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BlockKind(), v8::internal::compiler::BranchMatcher::BranchMatcher(), v8::internal::compiler::CFGBuilder::BuildBlocks(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::WasmGraphAssembler::CallBuiltinWithFrameState(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanAllocate(), v8::internal::compiler::NodeProperties::CanBeNullOrUndefined(), v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc}::CanBePaired(), v8::internal::compiler::NodeProperties::CanBePrimitive(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::Verifier::Visitor::CheckValueInputIs(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::CheckValueInputIsTaggedOrPointer(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectStateValuesOwnedUses(), v8::internal::compiler::LinearScheduler::ComputeControlLevel(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::CFGBuilder::ConnectBlocks(), v8::internal::compiler::MemoryLowering::AllocationGroup::Contains(), v8::internal::compiler::Control::Control(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::LoopFinderImpl::CreateLoopInfo(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::compiler::DeadCodeElimination::DeadValue(), v8::internal::compiler::CommonOperatorReducer::DecideCondition(), v8::internal::compiler::Revectorizer::DecideVectorize(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::Detect(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::JSInliner::DetermineCallTarget(), v8::internal::compiler::DiamondMatcher::DiamondMatcher(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::MemoryOptimizer::EnqueueMerge(), v8::internal::compiler::MemoryOptimizer::EnqueueUse(), v8::internal::compiler::StateValuesAccess::iterator::EnsureValid(), v8::internal::compiler::DiamondMatcher::FalseInputOf(), v8::internal::compiler::FastApiCallNode::FastApiCallNode(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCallReducerAssembler(), v8::internal::compiler::JSInliningHeuristic::Finalize(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::NodeProperties::FindFrameStateBefore(), v8::internal::compiler::RepresentationSelector::Float64Op(), v8::internal::compiler::FrameState::FrameState(), v8::internal::compiler::EscapeAnalysisTracker::Scope::FrameStateMightLazyDeopt(), v8::internal::compiler::JSCallAccessor::frequency(), v8::internal::compiler::VariableTracker::Scope::Get(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::GetAlias(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetConstantValue(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::GetFunctionInfo(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetMemoryOffsetValue(), v8::internal::compiler::GetModuleContext(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetNodeAddress(), v8::internal::compiler::StateValuesCache::GetNodeForValues(), v8::internal::compiler::NodeProperties::GetOuterContext(), v8::internal::compiler::StringBuilderOptimizer::GetPhiPredecessorsCommonId(), v8::internal::compiler::NodeProperties::GetProjectionType(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::SimplifiedLoweringVerifier::GetType(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::HashGraphForPGO(), v8::internal::compiler::LoopFinder::HasMarkedExits(), v8::internal::compiler::LoopTree::HeaderNode(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::InDeadBranch(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::NodeProperties::InferMapsUnsafe(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::Scheduler::InitializePlacement(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::RepresentationSelector::Int32Op(), v8::internal::compiler::RepresentationSelector::Int32OverflowOp(), v8::internal::compiler::RepresentationSelector::Int64Op(), v8::internal::compiler::RepresentationSelector::Int64OverflowOp(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::IsBitcast(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallOrConstructWithSpread(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsCallWithArrayLikeOrSpread(), v8::internal::compiler::NodeProperties::IsCommon(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat(), v8::internal::compiler::NodeProperties::IsConstant(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::IsConstant(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::IsContextParameter(), v8::internal::compiler::NodeProperties::IsControl(), v8::internal::compiler::LateEscapeAnalysis::IsEscaping(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsEscapingAllocationWitness(), v8::internal::compiler::CFGBuilder::IsFinalMerge(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::IsFresh(), v8::internal::compiler::StateValuesCache::IsKeysEqualToNode(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), v8::internal::compiler::LoopFinderImpl::IsLoopExitNode(), v8::internal::compiler::LoopFinderImpl::IsLoopHeaderNode(), v8::internal::compiler::StringBuilderOptimizer::IsLoopPhi(), v8::internal::compiler::RawMachineAssembler::IsMapOffsetConstant(), v8::internal::compiler::NodeProperties::IsPhi(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsPhiContainingGivenInputs(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::IsRename(), v8::internal::compiler::NodeProperties::IsSame(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsStore(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSupportedLoad(), v8::internal::compiler::JSCallOrConstructNode::IsValidNode(), v8::internal::compiler::NodeProperties::IsValueIdentity(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::IsZero(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IteratingArrayBuiltinHelper::IteratingArrayBuiltinHelper(), v8::internal::compiler::JSBinaryOpNode::JSBinaryOpNode(), v8::internal::compiler::JSCallAccessor::JSCallAccessor(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::JSCallNodeBase(), v8::internal::compiler::JSCloneObjectNode::JSCloneObjectNode(), v8::internal::compiler::JSConstructNodeBase< kOpcode >::JSConstructNodeBase(), v8::internal::compiler::JSCreateClosureNode::JSCreateClosureNode(), v8::internal::compiler::JSCreateEmptyLiteralArrayNode::JSCreateEmptyLiteralArrayNode(), v8::internal::compiler::JSCreateLiteralOpNode::JSCreateLiteralOpNode(), v8::internal::compiler::JSDefineKeyedOwnPropertyInLiteralNode::JSDefineKeyedOwnPropertyInLiteralNode(), v8::internal::compiler::JSDefineKeyedOwnPropertyNode::JSDefineKeyedOwnPropertyNode(), v8::internal::compiler::JSDefineNamedOwnPropertyNode::JSDefineNamedOwnPropertyNode(), v8::internal::compiler::JSFindNonDefaultConstructorOrConstructNode::JSFindNonDefaultConstructorOrConstructNode(), v8::internal::compiler::JSForInNextNode::JSForInNextNode(), v8::internal::compiler::JSForInPrepareNode::JSForInPrepareNode(), v8::internal::compiler::JSGetIteratorNode::JSGetIteratorNode(), v8::internal::compiler::JSGetTemplateObjectNode::JSGetTemplateObjectNode(), v8::internal::compiler::JSHasPropertyNode::JSHasPropertyNode(), v8::internal::compiler::JSLoadGlobalNode::JSLoadGlobalNode(), v8::internal::compiler::JSLoadNamedFromSuperNode::JSLoadNamedFromSuperNode(), v8::internal::compiler::JSLoadNamedNode::JSLoadNamedNode(), v8::internal::compiler::JSLoadPropertyNode::JSLoadPropertyNode(), v8::internal::compiler::JSSetKeyedPropertyNode::JSSetKeyedPropertyNode(), v8::internal::compiler::JSSetNamedPropertyNode::JSSetNamedPropertyNode(), v8::internal::compiler::JSStoreGlobalNode::JSStoreGlobalNode(), v8::internal::compiler::JSStoreInArrayLiteralNode::JSStoreInArrayLiteralNode(), v8::internal::compiler::JSUnaryOpNode::JSUnaryOpNode(), v8::internal::compiler::FrameState::locals(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias(), v8::internal::compiler::BytecodeGraphBuilder::MergeControl(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::Schedule::MovePhis(), v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::NoReturn(), v8::internal::compiler::JSBinopReduction::NumberOp(), v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext(), v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::compiler::NodeMatcher::opcode(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::OwnedByAddressingOperand(), v8::internal::compiler::FrameState::parameters(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::PhiInputsAreConcatsOrPhi(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::BytecodeGraphBuilder::Environment::PrepareForLoopExit(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForFunctionEntryStackCheck(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput(), v8::internal::compiler::PromiseBuiltinReducerAssembler::PromiseBuiltinReducerAssembler(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::DeadCodeElimination::PropagateDeadControl(), v8::internal::compiler::LateEscapeAnalysis::RecordEscapingAllocation(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordHint(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordMachineUsesOfConstant(), v8::internal::compiler::BranchElimination::Reduce(), v8::internal::compiler::CheckpointElimination::Reduce(), v8::internal::compiler::CommonOperatorReducer::Reduce(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::DeadCodeElimination::Reduce(), v8::internal::compiler::JSCallReducer::Reduce(), v8::internal::compiler::JSContextSpecialization::Reduce(), v8::internal::compiler::JSCreateLowering::Reduce(), v8::internal::compiler::JSGenericLowering::Reduce(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSIntrinsicLowering::Reduce(), v8::internal::compiler::JSNativeContextSpecialization::Reduce(), v8::internal::compiler::JSTypedLowering::Reduce(), v8::internal::compiler::LateEscapeAnalysis::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::RedundancyElimination::Reduce(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::TypedOptimization::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::Reduce(), v8::internal::compiler::WasmGCLowering::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::Reduce(), v8::internal::compiler::WasmLoadElimination::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::EscapeAnalysisReducer::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::MemoryLowering::Reduce(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::SelectLowering::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::WasmLoadElimination::ReduceAnyConvertExtern(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::CheckpointElimination::ReduceCheckpoint(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::MachineOperatorReducer::ReduceConditional(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::CommonOperatorReducer::ReduceEffectPhi(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertHighWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64InsertLowWord32(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64RoundDown(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::WasmGCLowering::ReduceIsNotNull(), v8::internal::compiler::WasmGCLowering::ReduceIsNull(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSComparison(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::compiler::JSTypedLowering::ReduceJSToString(), v8::internal::compiler::JSTypedLowering::ReduceJSToStringInput(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::DeadCodeElimination::ReduceLoopExit(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::DeadCodeElimination::ReduceNode(), v8::internal::compiler::WasmGCLowering::ReduceNull(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::WasmLoadElimination::ReduceOtherNode(), v8::internal::compiler::JSContextSpecialization::ReduceParameter(), v8::internal::compiler::CommonOperatorReducer::ReducePhi(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::MachineOperatorReducer::ReduceProjection(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::compiler::DeadCodeElimination::ReducePureNode(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::WasmGCLowering::ReduceRttCanon(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::CommonOperatorReducer::ReduceSelect(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeToNumber(), v8::internal::compiler::CommonOperatorReducer::ReduceStaticAssert(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmLoadElimination::ReduceStringAsWtf16(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::TypedOptimization::ReduceStringLength(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceTrapConditional(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceTypeGuard(), v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard(), v8::internal::compiler::DeadCodeElimination::ReduceUnreachableOrIfException(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32And(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Or(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shifts(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Xor(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64And(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Or(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shr(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Xor(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation(), v8::internal::compiler::DeadCodeElimination::RemoveLoopExit(), v8::internal::compiler::LateEscapeAnalysis::RemoveWitness(), v8::internal::compiler::JSGenericLowering::ReplaceBinaryOpWithBuiltinCall(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::ResolveSameValueRenames(), v8::internal::compiler::LoopVariableOptimizer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run(), v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationChecker::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::ScaleMatcher< BinopMatcher, kMulOpcode, kShiftOpcode >::ScaleMatcher(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::VariableTracker::Scope::Scope(), v8::internal::compiler::LoopFinderImpl::SetLoopMarkForLoopHeader(), v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::StartNode::StartNode(), v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), v8::internal::compiler::JSNativeContextSpecialization::StringCanSafelyBeRead(), v8::internal::compiler::MachineOperatorReducer::SwapBranches(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), v8::internal::compiler::DiamondMatcher::TrueInputOf(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::PropertyAccessBuilder::TryFoldLoadConstantDataField(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TryGetInvertedCondition(), v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange(), v8::internal::compiler::BytecodeGraphBuilder::TryGetScopeInfo(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::TryGetStoredValue(), v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCodeToConstant(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::TrySimplifyCompareForTestBit(), v8::internal::compiler::CodeAssembler::TryToIntPtrConstant(), v8::internal::compiler::CodeAssembler::TryToSmiConstant(), v8::internal::compiler::StateValuesAccess::iterator::type(), v8::internal::compiler::Typer::Visitor::TypeNode(), v8::internal::compiler::RepresentationSelector::Uint32Op(), v8::internal::compiler::RepresentationSelector::Uint32OverflowOp(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::Scheduler::UpdatePlacement(), v8::internal::compiler::Typer::Visitor::UpdateType(), v8::internal::compiler::ValueMatcher< T, kOpcode >::ValueMatcher(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::EscapeAnalysisReducer::VerifyReplacement(), v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw(), v8::internal::compiler::MemoryOptimizer::VisitCall(), v8::internal::compiler::RepresentationSelector::VisitForCheckedInt32Mul(), v8::internal::compiler::LoopVariableOptimizer::VisitIf(), v8::internal::compiler::MemoryOptimizer::VisitLoadElement(), v8::internal::compiler::MemoryOptimizer::VisitLoadField(), v8::internal::compiler::MemoryOptimizer::VisitLoadFromObject(), v8::internal::compiler::MemoryOptimizer::VisitNode(), v8::internal::compiler::BitcastElider::VisitNode(), v8::internal::compiler::LoopVariableOptimizer::VisitNode(), v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode(), v8::internal::compiler::StringBuilderOptimizer::VisitNode(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::MemoryOptimizer::VisitProtectedLoad(), v8::internal::compiler::MemoryOptimizer::VisitProtectedStore(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), v8::internal::compiler::MemoryOptimizer::VisitStore(), v8::internal::compiler::MemoryOptimizer::VisitStoreElement(), v8::internal::compiler::MemoryOptimizer::VisitStoreField(), v8::internal::compiler::MemoryOptimizer::VisitStoreToObject(), and v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::WriteBarrierAssertFailed().
operator new()
void* v8::internal::compiler::Node::operator new (size_t , void * location) [inline], [private]
Definition at line 272 of file node.h.
{ return location; }
operator=()
Node& v8::internal::compiler::Node::operator= (const Node &) [private], [delete]
operator[]()
value_type v8::internal::compiler::Node::operator[] (int index) const [inline]
outline_inputs()
OutOfLineInputs* v8::internal::compiler::Node::outline_inputs () const [inline], [private]
Definition at line 248 of file node.h.
                                          {
    return *reinterpret_cast<ZoneOutOfLineInputsPtr*>(inputs_location());
  }
Referenced by AppendInput(), Clone(), input_edges(), inputs(), inputs_vector(), and TrimInputCount().
OwnedBy() [1/2]
bool v8::internal::compiler::Node::OwnedBy (Node const * owner) const
Definition at line 323 of file node.cc.
                                          {
  for (Use* use = first_use_; use; use = use->next) {
    if (use->from() != owner) {
      return false;
    }
  }
  return first_use_ != nullptr;
}
References first_use_, and use().
Referenced by v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::Initialize(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), and v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition().
OwnedBy() [2/2]
bool v8::internal::compiler::Node::OwnedBy (Node const * owner1, Node const * owner2) const
Definition at line 332 of file node.cc.
                                                               {
  unsigned mask = 0;
  for (Use* use = first_use_; use; use = use->next) {
    Node* from = use->from();
    if (from == owner1) {
      mask |= 1;
    } else if (from == owner2) {
      mask |= 2;
    } else {
      return false;
    }
  }
  return mask == 3;
}
References first_use_, and use().
Print() [1/3]
void v8::internal::compiler::Node::Print () const [inline]
Definition at line 152 of file node.h.
{ Print(1); }
References Print().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BlockKind(), Print(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::SimplifiedLoweringVerifier::ReportInvalidTypeCombination(), and v8::internal::compiler::Typer::Visitor::UpdateType().
Print() [2/3]
void v8::internal::compiler::Node::Print (int depth) const
Definition at line 347 of file node.cc.
                                {
  StdoutStream os;
  Print(os, depth);
}
References Print().
Print() [3/3]
void v8::internal::compiler::Node::Print (std::ostream & os, int depth = 1) const
Definition at line 371 of file node.cc.
                                                {
  PrintNode(this, os, depth);
}
References v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode().
RemoveInput()
Node * v8::internal::compiler::Node::RemoveInput (int index)
Definition at line 230 of file node.cc.
                                 {
  DCHECK_LE(0, index);
  DCHECK_LT(index, InputCount());
  Node* result = InputAt(index);
  for (; index < InputCount() - 1; ++index) {
    ReplaceInput(index, InputAt(index + 1));
  }
  TrimInputCount(InputCount() - 1);
  Verify();
  return result;
}
References DCHECK_LE, DCHECK_LT, v8::internal::index, InputAt(), InputCount(), ReplaceInput(), v8::base::internal::result, TrimInputCount(), and Verify().
Referenced by v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::NodeProperties::RemoveValueInputs(), v8::internal::compiler::JSGenericLowering::ReplaceBinaryOpWithBuiltinCall(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), and v8::internal::compiler::RepresentationSelector::VisitNode().
RemoveUse()
void v8::internal::compiler::Node::RemoveUse (Use * use) [private]
Definition at line 417 of file node.cc.
                             {
  DCHECK(first_use_ == nullptr || first_use_->prev == nullptr);
  if (use->prev) {
    DCHECK_NE(first_use_, use);
    use->prev->next = use->next;
  } else {
    DCHECK_EQ(first_use_, use);
    first_use_ = use->next;
  }
  if (use->next) {
    use->next->prev = use->prev;
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, first_use_, and use().
Referenced by ClearInputs(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), ReplaceInput(), and v8::internal::compiler::Edge::UpdateTo().
ReplaceInput()
void v8::internal::compiler::Node::ReplaceInput (int index, Node * new_to) [inline]
Definition at line 76 of file node.h.
                                             {
    DCHECK_LE(0, index);
    DCHECK_LT(index, InputCount());
    ZoneNodePtr* input_ptr = GetInputPtr(index);
    Node* old_to = *input_ptr;
    if (old_to != new_to) {
      Use* use = GetUsePtr(index);
      if (old_to) old_to->RemoveUse(use);
      *input_ptr = new_to;
      if (new_to) new_to->AppendUse(use);
    }
  }
References AppendUse(), DCHECK_LE, DCHECK_LT, v8::internal::index, RemoveUse(), and use().
Referenced by v8::internal::compiler::WasmGraphBuilder::Assert(), v8::internal::compiler::JSTypeHintLowering::BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::Diamond::Chain(), v8::internal::compiler::SimplifiedOperatorReducer::Change(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::CommonOperatorReducer::Change(), v8::internal::compiler::RepresentationSelector::ChangeToDeadValue(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSBinopReduction::CheckInputsToInternalizedString(), v8::internal::compiler::JSBinopReduction::CheckInputsToReceiver(), v8::internal::compiler::JSBinopReduction::CheckInputsToReceiverOrNullOrUndefined(), v8::internal::compiler::JSBinopReduction::CheckInputsToString(), v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrOddball(), v8::internal::compiler::JSBinopReduction::CheckInputsToStringOrStringWrapper(), v8::internal::compiler::JSBinopReduction::CheckInputsToSymbol(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiver(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToReceiverOrNullOrUndefined(), v8::internal::compiler::JSBinopReduction::CheckLeftInputToSymbol(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::RepresentationSelector::ConvertInput(), v8::internal::compiler::JSBinopReduction::ConvertInputsToNumber(), v8::internal::compiler::JSBinopReduction::ConvertInputsToUI32(), v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::SimplifiedLowering::DoIntegerToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit(), v8::internal::compiler::SimplifiedLowering::DoMax(), v8::internal::compiler::SimplifiedLowering::DoNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoNumberToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoOrderedNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoSigned32ToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoUnsigned32ToUint8Clamped(), v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename(), v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), InsertInput(), InsertInputs(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::RepresentationSelector::MaskShiftOperand(), v8::internal::compiler::Diamond::Nest(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare(), v8::internal::compiler::EscapeAnalysisReducer::ReduceFrameStateInputs(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::MachineOperatorReducer::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32And(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shifts(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNOr(), RemoveInput(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), v8::internal::compiler::NodeProperties::ReplaceEffectInput(), v8::internal::compiler::NodeProperties::ReplaceFrameStateInput(), v8::internal::compiler::NodeHashCache::Constructor::ReplaceInput(), v8::internal::compiler::WasmAddressReassociation::ReplaceInputs(), v8::internal::compiler::NodeProperties::ReplaceValueInput(), v8::internal::compiler::NodeProperties::ReplaceValueInputs(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::JSBinopReduction::SwapInputs(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::SwapInputs(), v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), and v8::internal::compiler::RepresentationSelector::VisitNode().
ReplaceUses()
void v8::internal::compiler::Node::ReplaceUses (Node * replace_to)
Definition at line 304 of file node.cc.
                                 {
  DCHECK(this->first_use_ == nullptr || this->first_use_->prev == nullptr);
  DCHECK(that->first_use_ == nullptr || that->first_use_->prev == nullptr);
  // Update the pointers to {this} to point to {that}.
  Use* last_use = nullptr;
  for (Use* use = this->first_use_; use; use = use->next) {
    *use->input_ptr() = that;
    last_use = use;
  }
  if (last_use) {
    // Concat the use list of {this} and {that}.
    last_use->next = that->first_use_;
    if (that->first_use_) that->first_use_->prev = last_use;
    that->first_use_ = this->first_use_;
  }
  first_use_ = nullptr;
}
References v8::internal::DCHECK(), first_use_, v8::internal::compiler::Node::Use::next, and use().
Referenced by v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::Schedule::EliminateRedundantPhiNodes(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), and v8::internal::compiler::RepresentationSelector::RunVerifyPhase().
set_mark()
void v8::internal::compiler::Node::set_mark (Mark mark) [inline], [private]
Definition at line 283 of file node.h.
{ mark_ = mark; }
Referenced by v8::internal::compiler::NodeMarkerBase::Set().
set_op()
void v8::internal::compiler::Node::set_op (const Operator * op) [inline], [private]
Definition at line 275 of file node.h.
{ op_ = op; }
Referenced by v8::internal::compiler::NodeProperties::ChangeOp(), and v8::internal::compiler::NodeProperties::ChangeOpUnchecked().
set_outline_inputs()
void v8::internal::compiler::Node::set_outline_inputs (OutOfLineInputs * outline) [inline], [private]
Definition at line 251 of file node.h.
                                                    {
    *reinterpret_cast<ZoneOutOfLineInputsPtr*>(inputs_location()) = outline;
  }
Referenced by AppendInput().
set_type()
void v8::internal::compiler::Node::set_type (Type type) [inline], [private]
Definition at line 279 of file node.h.
{ type_ = type; }
References v8::internal::tracing::type.
Referenced by Clone(), v8::internal::compiler::NodeProperties::RemoveType(), and v8::internal::compiler::NodeProperties::SetType().
TrimInputCount()
void v8::internal::compiler::Node::TrimInputCount (int new_input_count)
Definition at line 260 of file node.cc.
                                             {
  int current_count = InputCount();
  DCHECK_LE(new_input_count, current_count);
  if (new_input_count == current_count) return; // Nothing to do.
  ClearInputs(new_input_count, current_count - new_input_count);
  if (has_inline_inputs()) {
    bit_field_ = InlineCountField::update(bit_field_, new_input_count);
  } else {
    outline_inputs()->count_ = new_input_count;
  }
}
References bit_field_, ClearInputs(), v8::internal::compiler::Node::OutOfLineInputs::count_, DCHECK_LE, has_inline_inputs(), InputCount(), outline_inputs(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::CommonOperatorReducer::Change(), v8::internal::compiler::RepresentationSelector::ChangeToDeadValue(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), EnsureInputCount(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal(), RemoveInput(), v8::internal::compiler::NodeProperties::RemoveNonValueInputs(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi(), and v8::internal::compiler::RepresentationSelector::VisitNode().
type()
Type v8::internal::compiler::Node::type () const [inline], [private]
Definition at line 278 of file node.h.
{ return type_; }
Referenced by Clone(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetArgumentsFrameState(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetTypeOrAny(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), and v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet().
use_edges()
UseEdges v8::internal::compiler::Node::use_edges () [inline]
Definition at line 126 of file node.h.
{ return UseEdges(this); }
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::NodeProperties::CollectValueProjections(), v8::internal::compiler::LinearScheduler::ComputeControlLevel(), v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables(), v8::internal::compiler::ControlEquivalence::DFSPush(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), v8::internal::compiler::MemoryOptimizer::EnqueueUses(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection(), v8::internal::compiler::ScheduleLateNodeVisitor::GetCommonDominatorOfUses(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::NodeProperties::IsExceptionalCall(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsSafeArgumentsElements(), v8::internal::compiler::BaseWithIndexAndDisplacementMatcher< AddMatcher >::OwnedByAddressingOperand(), v8::internal::compiler::LoopFinderImpl::PropagateForward(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::EffectGraphReducer::ReduceFrom(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::GraphReducer::Replace(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), v8::internal::compiler::NodeProperties::ReplaceUses(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::LoopVariableOptimizer::Run(), v8::internal::compiler::ControlEquivalence::RunUndirectedDFS(), v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), and v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw().
UseCount()
int v8::internal::compiler::Node::UseCount () const
Definition at line 286 of file node.cc.
                         {
  int use_count = 0;
  for (const Use* use = first_use_; use; use = use->next) {
    ++use_count;
  }
  return use_count;
}
References first_use_, and use().
Referenced by v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses(), v8::internal::compiler::NodeProperties::CollectControlProjections(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectStateValuesOwnedUses(), v8::internal::compiler::JSInliningHeuristic::DuplicateStateValuesAndRename(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::MachineOperatorReducer::ReduceWordEqualForConstantRhs(), v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded(), and v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition().
uses()
Uses v8::internal::compiler::Node::uses () [inline]
Definition at line 144 of file node.h.
{ return Uses(this); }
Referenced by v8::internal::compiler::begin(), v8::internal::compiler::BranchMatcher::BranchMatcher(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses(), v8::internal::compiler::Verifier::Visitor::CheckSwitch(), v8::internal::compiler::Revectorizer::DecideVectorize(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::EffectPhiForPhi(), v8::internal::compiler::end(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::NodeProperties::FindProjection(), v8::internal::compiler::EscapeAnalysisTracker::Scope::FrameStateMightLazyDeopt(), v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::HasConcatOrPhiUse(), v8::internal::compiler::LoopFinder::HasMarkedExits(), Kill(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::OwnedByWord32Op(), v8::internal::compiler::BinopMatcher< Left, Right, rep >::OwnsInput(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::GraphReducer::ReduceTop(), v8::internal::compiler::DeadCodeElimination::RemoveLoopExit(), v8::internal::compiler::GraphReducer::Replace(), v8::internal::compiler::Verifier::Run(), v8::internal::compiler::RepresentationSelector::RunRetypePhase(), v8::internal::compiler::LoopFinderImpl::SetLoopMarkForLoopHeader(), v8::internal::compiler::MachineOperatorReducer::SwapBranches(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Scheduler::UpdatePlacement(), v8::internal::compiler::ScheduleEarlyNodeVisitor::VisitNode(), v8::internal::compiler::StringBuilderOptimizer::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Verify()
void v8::internal::compiler::Node::Verify () [inline]
Definition at line 67 of file node.h.
{}
Referenced by AppendInput(), ClearInputs(), InsertInput(), InsertInputs(), NewImpl(), and RemoveInput().
Friends And Related Function Documentation
Edge
friend class Edge [friend]
Definition at line 303 of file node.h.
Referenced by v8::internal::compiler::Node::InputEdges::iterator::operator*(), v8::internal::compiler::Node::UseEdges::iterator::operator*(), and v8::internal::compiler::Node::InputEdges::operator[]().
NodeMarkerBase
friend class NodeMarkerBase [friend]
Definition at line 304 of file node.h.
NodeProperties
friend class NodeProperties [friend]
Definition at line 305 of file node.h.
Member Data Documentation
bit_field_
uint32_t v8::internal::compiler::Node::bit_field_ [private]
Definition at line 300 of file node.h.
Referenced by AppendInput(), input_edges(), inputs(), inputs_vector(), and TrimInputCount().
count_
int v8::internal::compiler::Node::count_ [private]
Definition at line 417 of file node.h.
Referenced by v8::internal::compiler::Node::InputEdges::count(), count(), v8::internal::compiler::Node::InputEdges::empty(), empty(), v8::internal::compiler::Node::InputEdges::end(), v8::internal::compiler::Node::OutOfLineInputs::ExtractFrom(), input_edges(), inputs(), and inputs_vector().
first_use_
ZoneUsePtr v8::internal::compiler::Node::first_use_ [private]
Definition at line 301 of file node.h.
Referenced by AppendUse(), BranchUseCount(), OwnedBy(), RemoveUse(), ReplaceUses(), and UseCount().
input_root_
ZoneNodePtr const* v8::internal::compiler::Node::input_root_ [private]
Definition at line 416 of file node.h.
Referenced by v8::internal::compiler::Node::InputEdges::begin(), v8::internal::compiler::Node::InputEdges::end(), and v8::internal::compiler::Node::InputEdges::operator[]().
kMaxInlineCapacity
const int v8::internal::compiler::Node::kMaxInlineCapacity = InlineCapacityField::kMax - 1 [static], [private]
Definition at line 295 of file node.h.
Referenced by NewImpl(), and Node().
kOutlineMarker
const int v8::internal::compiler::Node::kOutlineMarker = InlineCountField::kMax [static], [private]
Definition at line 294 of file node.h.
Referenced by AppendInput(), input_edges(), inputs(), inputs_vector(), NewImpl(), and Node().
mark_
Mark v8::internal::compiler::Node::mark_ [private]
Definition at line 299 of file node.h.
op_
const Operator* v8::internal::compiler::Node::op_ [private]
Definition at line 297 of file node.h.
type_
Type v8::internal::compiler::Node::type_ [private]
Definition at line 298 of file node.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node.h
/mnt/V8SourceCode/src/compiler/node.cc