v8::internal::CodeLargeObjectSpace Class Reference
#include <large-spaces.h>
Public Member Functions
CodeLargeObjectSpace (Heap *heap)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (LocalHeap *local_heap, int object_size, AllocationHint hint)
Protected Member Functions
void AddPage (LargePageMetadata *page, size_t object_size) override
void RemovePage (LargePageMetadata *page) override
Additional Inherited Members
Detailed Description
Definition at line 199 of file large-spaces.h.
Constructor & Destructor Documentation
CodeLargeObjectSpace()
v8::internal::CodeLargeObjectSpace::CodeLargeObjectSpace (Heap * heap) [explicit]
Definition at line 468 of file large-spaces.cc.
    : OldLargeObjectSpace(heap, CODE_LO_SPACE) {}
Member Function Documentation
AddPage()
void v8::internal::CodeLargeObjectSpace::AddPage (LargePageMetadata * page, size_t object_size) [override], [protected], [virtual]
Reimplemented from v8::internal::LargeObjectSpace.
Definition at line 478 of file large-spaces.cc.
                                                       {
  OldLargeObjectSpace::AddPage(page, object_size);
}
References v8::internal::LargeObjectSpace::AddPage().
AllocateRaw()
AllocationResult v8::internal::CodeLargeObjectSpace::AllocateRaw (LocalHeap * local_heap, int object_size, AllocationHint hint)
Definition at line 471 of file large-spaces.cc.
                                                                        {
  return OldLargeObjectSpace::AllocateRaw(local_heap, object_size, EXECUTABLE,
                                          hint);
}
References v8::internal::OldLargeObjectSpace::AllocateRaw(), and v8::internal::EXECUTABLE.
Referenced by v8::internal::HeapAllocator::AllocateRawLargeInternal().
RemovePage()
void v8::internal::CodeLargeObjectSpace::RemovePage (LargePageMetadata * page) [override], [protected], [virtual]
Reimplemented from v8::internal::LargeObjectSpace.
Definition at line 483 of file large-spaces.cc.
                                                             {
  heap()->isolate()->RemoveCodeMemoryChunk(page);
  OldLargeObjectSpace::RemovePage(page);
}
References v8::internal::BaseSpace::heap(), v8::internal::Heap::isolate(), v8::internal::Isolate::RemoveCodeMemoryChunk(), and v8::internal::LargeObjectSpace::RemovePage().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/large-spaces.h
/mnt/V8SourceCode/src/heap/large-spaces.cc