v8_inspector::StringView Class Reference
#include <v8-inspector.h>
Public Member Functions
StringView ()
StringView (const uint8_t *characters, size_t length)
StringView (const uint16_t *characters, size_t length)
bool is8Bit () const
size_t length () const
const uint8_t * characters8 () const
const uint16_t * characters16 () const
Private Attributes
bool m_is8Bit
size_t m_length
xx xx xx xx xx xx xx xx xx
union {
 const uint8_t * m_characters8
 const uint16_t * m_characters16
};
Detailed Description
Definition at line 50 of file v8-inspector.h.
Constructor & Destructor Documentation
StringView() [1/3]
v8_inspector::StringView::StringView () [inline]
Definition at line 52 of file v8-inspector.h.
: m_is8Bit(true), m_length(0), m_characters8(nullptr) {}
StringView() [2/3]
v8_inspector::StringView::StringView (const uint8_t * characters, size_t length) [inline]
Definition at line 54 of file v8-inspector.h.
      : m_is8Bit(true), m_length(length), m_characters8(characters) {}
StringView() [3/3]
v8_inspector::StringView::StringView (const uint16_t * characters, size_t length) [inline]
Definition at line 57 of file v8-inspector.h.
      : m_is8Bit(false), m_length(length), m_characters16(characters) {}
Member Function Documentation
characters16()
const uint16_t* v8_inspector::StringView::characters16 () const [inline]
Definition at line 66 of file v8-inspector.h.
{ return m_characters16; }
Referenced by v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), and v8_inspector::V8StackTraceId::V8StackTraceId().
characters8()
const uint8_t* v8_inspector::StringView::characters8 () const [inline]
Definition at line 65 of file v8-inspector.h.
{ return m_characters8; }
Referenced by v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::IsCBORMessage(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ParseState(), and v8_inspector::V8StackTraceId::V8StackTraceId().
is8Bit()
bool v8_inspector::StringView::is8Bit () const [inline]
Definition at line 60 of file v8-inspector.h.
{ return m_is8Bit; }
Referenced by v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::IsCBORMessage(), and v8_inspector::V8StackTraceId::V8StackTraceId().
length()
size_t v8_inspector::StringView::length () const [inline]
Definition at line 61 of file v8-inspector.h.
{ return m_length; }
Referenced by v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::IsCBORMessage(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ParseState(), v8_inspector::V8InspectorSessionImpl::V8InspectorSessionImpl(), and v8_inspector::V8StackTraceId::V8StackTraceId().
Member Data Documentation
union { ... } [private]
m_characters16
const uint16_t* v8_inspector::StringView::m_characters16
Definition at line 73 of file v8-inspector.h.
m_characters8
const uint8_t* v8_inspector::StringView::m_characters8
Definition at line 72 of file v8-inspector.h.
m_is8Bit
bool v8_inspector::StringView::m_is8Bit [private]
Definition at line 69 of file v8-inspector.h.
m_length
size_t v8_inspector::StringView::m_length [private]
Definition at line 70 of file v8-inspector.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-inspector.h