v8::debug::GeneratorObject Class Reference
Native wrapper around v8::internal::JSGeneratorObject object.
#include <debug-interface.h>
Public Member Functions
v8::MaybeLocal< debug::Script > Script ()
v8::Local< v8::Function > Function ()
debug::Location SuspendedLocation ()
bool IsSuspended ()
Static Public Member Functions
static v8::Local< debug::GeneratorObject > Cast (v8::Local< v8::Value > value)
Detailed Description
Native wrapper around v8::internal::JSGeneratorObject object.
Definition at line 380 of file debug-interface.h.
Member Function Documentation
Cast()
v8::Local< GeneratorObject > v8::debug::GeneratorObject::Cast (v8::Local< v8::Value > value) [static]
Definition at line 1224 of file debug-interface.cc.
                                                                     {
  CHECK(value->IsGeneratorObject());
  return ToApiHandle<GeneratorObject>(Utils::OpenDirectHandle(*value));
}
References CHECK, v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::LocationMirror::createForGenerator(), and v8_inspector::V8Debugger::getTargetScopes().
Function()
Local< Function > v8::debug::GeneratorObject::Function ()
Definition at line 1201 of file debug-interface.cc.
                                          {
  auto obj = Utils::OpenDirectHandle(this);
  return Utils::ToLocal(direct_handle(obj->function(), i::Isolate::Current()));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
IsSuspended()
bool v8::debug::GeneratorObject::IsSuspended ()
Definition at line 1220 of file debug-interface.cc.
                                  {
  return Utils::OpenDirectHandle(this)->is_suspended();
}
References v8::Utils::OpenDirectHandle().
Script()
MaybeLocal< Script > v8::debug::GeneratorObject::Script ()
Definition at line 1192 of file debug-interface.cc.
                                           {
  auto obj = Utils::OpenDirectHandle(this);
  i::Tagged<i::Object> maybe_script = obj->function()->shared()->script();
  if (!IsScript(maybe_script)) return {};
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Script> script(i::Cast<i::Script>(maybe_script), isolate);
  return ToApiHandle<v8::debug::Script>(script);
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
SuspendedLocation()
Location v8::debug::GeneratorObject::SuspendedLocation ()
Definition at line 1206 of file debug-interface.cc.
                                            {
  auto obj = Utils::OpenDirectHandle(this);
  CHECK(obj->is_suspended());
  i::Tagged<i::Object> maybe_script = obj->function()->shared()->script();
  if (!IsScript(maybe_script)) return Location();
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Script> script(i::Cast<i::Script>(maybe_script), isolate);
  i::Script::PositionInfo info;
  i::SharedFunctionInfo::EnsureSourcePositionsAvailable(
      isolate, i::direct_handle(obj->function()->shared(), isolate));
  i::Script::GetPositionInfo(script, obj->source_position(), &info);
  return Location(info.line, info.column);
}
References CHECK, v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::Script::GetPositionInfo(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc