v8::internal::MarkCompactWeakObjectRetainer Class Reference
Public Member Functions
MarkCompactWeakObjectRetainer (Heap *heap, MarkingState *marking_state)
Tagged< Object > RetainAs (Tagged< Object > object) override
Private Attributes
Heap *const heap_
MarkingState *const marking_state_
Detailed Description
Definition at line 1205 of file mark-compact.cc.
Constructor & Destructor Documentation
MarkCompactWeakObjectRetainer()
v8::internal::MarkCompactWeakObjectRetainer::MarkCompactWeakObjectRetainer (Heap * heap, MarkingState * marking_state) [inline]
Definition at line 1207 of file mark-compact.cc.
      : heap_(heap), marking_state_(marking_state) {}
Member Function Documentation
RetainAs()
Tagged<Object> v8::internal::MarkCompactWeakObjectRetainer::RetainAs (Tagged< Object > object) [inline], [override], [virtual]
Implements v8::internal::WeakObjectRetainer.
Definition at line 1210 of file mark-compact.cc.
                                                          {
    Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_,
                                            heap_object)) {
      return object;
    } else if (IsAllocationSite(heap_object) &&
               !Cast<AllocationSite>(object)->IsZombie()) {
      // "dead" AllocationSites need to live long enough for a traversal of new
      // space. These sites get a one-time reprieve.
      Tagged<Object> nested = object;
      while (IsAllocationSite(nested)) {
        Tagged<AllocationSite> current_site = Cast<AllocationSite>(nested);
        // MarkZombie will override the nested_site, read it first before
        // marking
        nested = current_site->nested_site();
        current_site->MarkZombie();
        marking_state_->TryMarkAndAccountLiveBytes(current_site);
      }
      return object;
    } else {
      return Smi::zero();
    }
  }
References heap_, v8::internal::MarkingHelper::IsMarkedOrAlwaysLive(), marking_state_, v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMarkAndAccountLiveBytes(), and v8::internal::Smi::zero().
Member Data Documentation
heap_
Heap* const v8::internal::MarkCompactWeakObjectRetainer::heap_ [private]
Definition at line 1237 of file mark-compact.cc.
Referenced by RetainAs().
marking_state_
MarkingState* const v8::internal::MarkCompactWeakObjectRetainer::marking_state_ [private]
Definition at line 1238 of file mark-compact.cc.
Referenced by RetainAs().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc