v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator Class Reference
Public Member Functions
void * Allocate (size_t length) override
Allocate |length| bytes.
void * AllocateUninitialized (size_t length) override
Allocate |length| bytes.
void Free (void *data, size_t length) override
Free the memory block of size |length|, pointed to by |data|.
Private Member Functions
void * AllocateVM (size_t length)
void FreeVM (void *data, size_t length)
Static Private Attributes
static constexpr size_t kVMThreshold = 65536
Additional Inherited Members
Detailed Description
Definition at line 170 of file d8.cc.
Member Function Documentation
Allocate()
void* v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::Allocate (size_t length) [inline], [override], [virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory should be initialized to zeroes.
Reimplemented from v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
Definition at line 172 of file d8.cc.
                                         {
    if (length >= kVMThreshold) return AllocateVM(length);
    return ArrayBufferAllocatorBase::Allocate(length);
  }
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), and v8::internal::length.
AllocateUninitialized()
void* v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::AllocateUninitialized (size_t length) [inline], [override], [virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory does not have to be initialized.
Reimplemented from v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
Definition at line 177 of file d8.cc.
                                                      {
    if (length >= kVMThreshold) return AllocateVM(length);
    return ArrayBufferAllocatorBase::AllocateUninitialized(length);
  }
References v8::internal::length.
AllocateVM()
void* v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::AllocateVM (size_t length) [inline], [private]
Definition at line 193 of file d8.cc.
                                  {
    DCHECK_LE(kVMThreshold, length);
    v8::PageAllocator* page_allocator = GetPageAllocator();
    size_t page_size = page_allocator->AllocatePageSize();
    size_t allocated = RoundUp(length, page_size);
    return i::AllocatePages(page_allocator, allocated, page_size,
                            PageAllocator::kReadWrite);
  }
References v8::internal::AllocatePages(), v8::PageAllocator::AllocatePageSize(), DCHECK_LE, v8::PageAllocator::kReadWrite, v8::internal::length, and RoundUp().
Free()
void v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::Free (void * data, size_t length) [inline], [override], [virtual]
Free the memory block of size |length|, pointed to by |data|.
That memory is guaranteed to be previously allocated by |Allocate|.
Reimplemented from v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
Definition at line 182 of file d8.cc.
                                                {
    if (length >= kVMThreshold) {
      FreeVM(data, length);
    } else {
      ArrayBufferAllocatorBase::Free(data, length);
    }
  }
References v8::base::Free(), and v8::internal::length.
FreeVM()
void v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::FreeVM (void * data, size_t length) [inline], [private]
Definition at line 202 of file d8.cc.
                                         {
    v8::PageAllocator* page_allocator = GetPageAllocator();
    size_t page_size = page_allocator->AllocatePageSize();
    size_t allocated = RoundUp(length, page_size);
    i::FreePages(page_allocator, data, allocated);
  }
References v8::PageAllocator::AllocatePageSize(), v8::internal::FreePages(), v8::internal::length, and RoundUp().
Member Data Documentation
kVMThreshold
constexpr size_t v8::anonymous_namespace{d8.cc}::ShellArrayBufferAllocator::kVMThreshold = 65536 [static], [constexpr], [private]
Definition at line 191 of file d8.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc