v8::internal::compiler::Node::UseEdges Class Reference
#include <node.h>
Classes
class iterator
Public Types
using value_type = Edge
Public Member Functions
iterator begin () const
iterator end () const
bool empty () const
UseEdges (Node *node)
Private Attributes
Node * node_
Detailed Description
Definition at line 110 of file node.h.
Member Typedef Documentation
value_type
using v8::internal::compiler::Node::UseEdges::value_type = Edge
Definition at line 112 of file node.h.
Constructor & Destructor Documentation
UseEdges()
v8::internal::compiler::Node::UseEdges::UseEdges (Node * node) [inline], [explicit]
Definition at line 120 of file node.h.
: node_(node) {}
Member Function Documentation
begin()
Node::UseEdges::iterator v8::internal::compiler::Node::UseEdges::begin () const [inline]
Definition at line 642 of file node.h.
                                               {
  return Node::UseEdges::iterator(this->node_);
}
Referenced by v8::internal::compiler::ControlEquivalence::DFSPush().
empty()
bool v8::internal::compiler::Node::UseEdges::empty () const
Definition at line 490 of file node.cc.
{ return begin() == end(); }
References v8::internal::compiler::Node::InputEdges::begin(), and v8::internal::compiler::Node::InputEdges::end().
end()
Node::UseEdges::iterator v8::internal::compiler::Node::UseEdges::end () const [inline]
Definition at line 647 of file node.h.
                                             {
  return Node::UseEdges::iterator();
}
Referenced by v8::internal::compiler::ControlEquivalence::RunUndirectedDFS().
Member Data Documentation
node_
Node* v8::internal::compiler::Node::UseEdges::node_ [private]
Definition at line 123 of file node.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node.h
/mnt/V8SourceCode/src/compiler/node.cc