v8::internal::compiler::FastApiCallParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
FastApiCallParameters (FastApiCallFunction c_function, FeedbackSource const &feedback, CallDescriptor *descriptor)
FastApiCallFunction c_function () const
FeedbackSource const & feedback () const
CallDescriptor * descriptor () const
const CFunctionInfo * signature () const
unsigned int argument_count () const
Private Attributes
FastApiCallFunction c_function_
const FeedbackSource feedback_
CallDescriptor * descriptor_
Detailed Description
Definition at line 750 of file simplified-operator.h.
Constructor & Destructor Documentation
FastApiCallParameters()
v8::internal::compiler::FastApiCallParameters::FastApiCallParameters (FastApiCallFunction c_function, FeedbackSource const & feedback, CallDescriptor * descriptor) [inline], [explicit]
Definition at line 752 of file simplified-operator.h.
      : c_function_(c_function), feedback_(feedback), descriptor_(descriptor) {}
Member Function Documentation
argument_count()
unsigned int v8::internal::compiler::FastApiCallParameters::argument_count () const [inline]
Definition at line 761 of file simplified-operator.h.
                                      {
    const unsigned int count = signature()->ArgumentCount();
    return count;
  }
c_function()
FastApiCallFunction v8::internal::compiler::FastApiCallParameters::c_function () const [inline]
Definition at line 757 of file simplified-operator.h.
{ return c_function_; }
Referenced by v8::internal::compiler::FastApiCallNode::FastCallArgumentCount(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
descriptor()
CallDescriptor* v8::internal::compiler::FastApiCallParameters::descriptor () const [inline]
Definition at line 759 of file simplified-operator.h.
{ return descriptor_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::FastApiCallNode::SlowCallArgumentCount(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
feedback()
FeedbackSource const& v8::internal::compiler::FastApiCallParameters::feedback () const [inline]
Definition at line 758 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::RepresentationSelector::VisitFastApiCall().
signature()
const CFunctionInfo* v8::internal::compiler::FastApiCallParameters::signature () const [inline]
Definition at line 760 of file simplified-operator.h.
{ return c_function_.signature; }
Member Data Documentation
c_function_
FastApiCallFunction v8::internal::compiler::FastApiCallParameters::c_function_ [private]
Definition at line 767 of file simplified-operator.h.
descriptor_
CallDescriptor* v8::internal::compiler::FastApiCallParameters::descriptor_ [private]
Definition at line 770 of file simplified-operator.h.
feedback_
const FeedbackSource v8::internal::compiler::FastApiCallParameters::feedback_ [private]
Definition at line 769 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h