v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler > Class Template Reference
#include <wasm-in-js-inlining-reducer-inl.h>
Classes
struct Value
Public Types
using ValidationTag = wasm::Decoder::NoValidationTag
using FullDecoder = wasm::WasmFullDecoder< ValidationTag, WasmInJsInliningInterface >
using Control = wasm::ControlBase< Value, ValidationTag >
Public Member Functions
WasmInJsInliningInterface (Assembler &assembler, base::Vector< const OpIndex > arguments, V< WasmTrustedInstanceData > trusted_instance_data)
V< Any > Result ()
void OnFirstError (FullDecoder *)
void Bailout (FullDecoder *decoder)
void StartFunction (FullDecoder *decoder)
void StartFunctionBody (FullDecoder *decoder, Control *block)
void FinishFunction (FullDecoder *decoder)
void NextInstruction (FullDecoder *decoder, WasmOpcode)
void NopForTestingUnsupportedInLiftoff (FullDecoder *decoder)
void TraceInstruction (FullDecoder *decoder, uint32_t markid)
void UnOp (FullDecoder *decoder, WasmOpcode opcode, const Value &value, Value *result)
void BinOp (FullDecoder *decoder, WasmOpcode opcode, const Value &lhs, const Value &rhs, Value *result)
OpIndex UnOpImpl (FullDecoder *decoder, WasmOpcode opcode, OpIndex arg, ValueType input_type)
OpIndex BinOpImpl (FullDecoder *decoder, WasmOpcode opcode, OpIndex lhs, OpIndex rhs)
void I32Const (FullDecoder *decoder, Value *result, int32_t value)
void I64Const (FullDecoder *decoder, Value *result, int64_t value)
void F32Const (FullDecoder *decoder, Value *result, float value)
void F64Const (FullDecoder *decoder, Value *result, double value)
void S128Const (FullDecoder *decoder, const Simd128Immediate &imm, Value *result)
void RefNull (FullDecoder *decoder, ValueType type, Value *result)
void RefFunc (FullDecoder *decoder, uint32_t function_index, Value *result)
void RefAsNonNull (FullDecoder *decoder, const Value &arg, Value *result)
void Drop (FullDecoder *decoder)
void LocalGet (FullDecoder *decoder, Value *result, const IndexImmediate &imm)
void LocalSet (FullDecoder *decoder, const Value &value, const IndexImmediate &imm)
void LocalTee (FullDecoder *decoder, const Value &value, Value *result, const IndexImmediate &imm)
void GlobalGet (FullDecoder *decoder, Value *result, const GlobalIndexImmediate &imm)
void GlobalSet (FullDecoder *decoder, const Value &value, const GlobalIndexImmediate &imm)
void Block (FullDecoder *decoder, Control *block)
void Loop (FullDecoder *decoder, Control *block)
void If (FullDecoder *decoder, const Value &cond, Control *if_block)
void Else (FullDecoder *decoder, Control *if_block)
void BrOrRet (FullDecoder *decoder, uint32_t depth, uint32_t drop_values=0)
void BrIf (FullDecoder *decoder, const Value &cond, uint32_t depth)
void BrTable (FullDecoder *decoder, const BranchTableImmediate &imm, const Value &key)
void FallThruTo (FullDecoder *decoder, Control *block)
void PopControl (FullDecoder *decoder, Control *block)
void DoReturn (FullDecoder *decoder, uint32_t drop_values)
void Select (FullDecoder *decoder, const Value &cond, const Value &fval, const Value &tval, Value *result)
void Try (FullDecoder *decoder, Control *block)
void Throw (FullDecoder *decoder, const TagIndexImmediate &imm, const Value arg_values[])
void Rethrow (FullDecoder *decoder, Control *block)
void CatchException (FullDecoder *decoder, const TagIndexImmediate &imm, Control *block, base::Vector< Value > values)
void Delegate (FullDecoder *decoder, uint32_t depth, Control *block)
void CatchAll (FullDecoder *decoder, Control *block)
void TryTable (FullDecoder *decoder, Control *block)
void CatchCase (FullDecoder *decoder, Control *block, const wasm::CatchCase &catch_case, base::Vector< Value > values)
void ThrowRef (FullDecoder *decoder, Value *value)
void ContNew (FullDecoder *decoder, const wasm::ContIndexImmediate &imm, const Value &func_ref, Value *result)
void ContBind (FullDecoder *decoder, const wasm::ContIndexImmediate &orig_imm, Value input_cont, const Value args[], const wasm::ContIndexImmediate &new_imm, Value *result)
void Resume (FullDecoder *decoder, const wasm::ContIndexImmediate &imm, base::Vector< wasm::HandlerCase > handlers, const Value args[], const Value returns[])
void ResumeThrow (FullDecoder *decoder, const wasm::ContIndexImmediate &cont_imm, const TagIndexImmediate &exc_imm, base::Vector< wasm::HandlerCase > handlers, const Value args[], const Value returns[])
void Switch (FullDecoder *decoder, const TagIndexImmediate &tag_imm, const wasm::ContIndexImmediate &con_imm, const Value &cont_ref, const Value args[], Value returns[])
void Suspend (FullDecoder *decoder, const TagIndexImmediate &imm, const Value args[], const Value returns[])
void EffectHandlerTable (FullDecoder *decoder, Control *block)
void Trap (FullDecoder *decoder, wasm::TrapReason reason)
void AssertNullTypecheck (FullDecoder *decoder, const Value &obj, Value *result)
void AssertNotNullTypecheck (FullDecoder *decoder, const Value &obj, Value *result)
void AtomicNotify (FullDecoder *decoder, const MemoryAccessImmediate &imm, OpIndex index, OpIndex num_waiters_to_wake, Value *result)
void AtomicWait (FullDecoder *decoder, WasmOpcode opcode, const MemoryAccessImmediate &imm, OpIndex index, OpIndex expected, V< Word64 > timeout, Value *result)
void AtomicOp (FullDecoder *decoder, WasmOpcode opcode, const Value args[], const size_t argc, const MemoryAccessImmediate &imm, Value *result)
void AtomicFence (FullDecoder *decoder)
void StructAtomicRMW (FullDecoder *decoder, WasmOpcode opcode, const Value &struct_object, const FieldImmediate &field, const Value &field_value, AtomicMemoryOrder order, Value *result)
void StructAtomicCompareExchange (FullDecoder *decoder, WasmOpcode opcode, const Value &struct_object, const FieldImmediate &field, const Value &expected_value, const Value &new_value, AtomicMemoryOrder order, Value *result)
void ArrayAtomicRMW (FullDecoder *decoder, WasmOpcode opcode, const Value &array_obj, const ArrayIndexImmediate &imm, const Value &index, const Value &value, AtomicMemoryOrder order, Value *result)
void ArrayAtomicCompareExchange (FullDecoder *decoder, WasmOpcode opcode, const Value &array_obj, const ArrayIndexImmediate &imm, const Value &index, const Value &expected_value, const Value &new_value, AtomicMemoryOrder order, Value *result)
void MemoryInit (FullDecoder *decoder, const MemoryInitImmediate &imm, const Value &dst, const Value &src, const Value &size)
void MemoryCopy (FullDecoder *decoder, const MemoryCopyImmediate &imm, const Value &dst, const Value &src, const Value &size)
void MemoryFill (FullDecoder *decoder, const MemoryIndexImmediate &imm, const Value &dst, const Value &value, const Value &size)
void DataDrop (FullDecoder *decoder, const IndexImmediate &imm)
void TableGet (FullDecoder *decoder, const Value &index, Value *result, const TableIndexImmediate &imm)
void TableSet (FullDecoder *decoder, const Value &index, const Value &value, const TableIndexImmediate &imm)
void TableInit (FullDecoder *decoder, const TableInitImmediate &imm, const Value &dst_val, const Value &src_val, const Value &size_val)
void TableCopy (FullDecoder *decoder, const TableCopyImmediate &imm, const Value &dst_val, const Value &src_val, const Value &size_val)
void TableGrow (FullDecoder *decoder, const TableIndexImmediate &imm, const Value &value, const Value &delta, Value *result)
void TableFill (FullDecoder *decoder, const TableIndexImmediate &imm, const Value &start, const Value &value, const Value &count)
void TableSize (FullDecoder *decoder, const TableIndexImmediate &imm, Value *result)
void ElemDrop (FullDecoder *decoder, const IndexImmediate &imm)
void StructNew (FullDecoder *decoder, const StructIndexImmediate &imm, const Value &descriptor, const Value args[], Value *result)
void StructNewDefault (FullDecoder *decoder, const StructIndexImmediate &imm, const Value &descriptor, Value *result)
void StructGet (FullDecoder *decoder, const Value &struct_object, const FieldImmediate &field, bool is_signed, Value *result)
void StructSet (FullDecoder *decoder, const Value &struct_object, const FieldImmediate &field, const Value &field_value)
void StructAtomicGet (FullDecoder *decoder, const Value &struct_obj, const FieldImmediate &field, bool is_signed, AtomicMemoryOrder memory_order, Value *result)
void StructAtomicSet (FullDecoder *decoder, const Value &struct_object, const FieldImmediate &field, const Value &field_value, AtomicMemoryOrder memory_order)
void ArrayNew (FullDecoder *decoder, const ArrayIndexImmediate &imm, const Value &length, const Value &initial_value, Value *result)
void ArrayNewDefault (FullDecoder *decoder, const ArrayIndexImmediate &imm, const Value &length, Value *result)
void ArrayGet (FullDecoder *decoder, const Value &array_obj, const ArrayIndexImmediate &imm, const Value &index, bool is_signed, Value *result)
void ArrayAtomicGet (FullDecoder *decoder, const Value &array_obj, const ArrayIndexImmediate &imm, const Value &index, bool is_signed, AtomicMemoryOrder memory_order, Value *result)
void ArraySet (FullDecoder *decoder, const Value &array_obj, const ArrayIndexImmediate &imm, const Value &index, const Value &value)
void ArrayAtomicSet (FullDecoder *decoder, const Value &array_obj, const ArrayIndexImmediate &imm, const Value &index_val, const Value &value_val, AtomicMemoryOrder order)
void ArrayLen (FullDecoder *decoder, const Value &array_obj, Value *result)
void ArrayCopy (FullDecoder *decoder, const Value &dst, const Value &dst_index, const Value &src, const Value &src_index, const ArrayIndexImmediate &src_imm, const Value &length)
void ArrayFill (FullDecoder *decoder, ArrayIndexImmediate &imm, const Value &array, const Value &index, const Value &value, const Value &length)
void ArrayNewFixed (FullDecoder *decoder, const ArrayIndexImmediate &array_imm, const IndexImmediate &length_imm, const Value elements[], Value *result)
void ArrayNewSegment (FullDecoder *decoder, const ArrayIndexImmediate &array_imm, const IndexImmediate &segment_imm, const Value &offset, const Value &length, Value *result)
void ArrayInitSegment (FullDecoder *decoder, const ArrayIndexImmediate &array_imm, const IndexImmediate &segment_imm, const Value &array, const Value &array_index, const Value &segment_offset, const Value &length)
void RefI31 (FullDecoder *decoder, const Value &input, Value *result)
void I31GetS (FullDecoder *decoder, const Value &input, Value *result)
void I31GetU (FullDecoder *decoder, const Value &input, Value *result)
void RefGetDesc (FullDecoder *decoder, const Value &ref, Value *desc)
void RefTest (FullDecoder *decoder, wasm::HeapType target_type, const Value &object, Value *result, bool null_succeeds)
void RefTestAbstract (FullDecoder *decoder, const Value &object, wasm::HeapType type, Value *result, bool null_succeeds)
void RefCast (FullDecoder *decoder, const Value &object, Value *result)
void RefCastDesc (FullDecoder *decoder, const Value &object, const Value &descriptor, Value *result)
void RefCastAbstract (FullDecoder *decoder, const Value &object, wasm::HeapType type, Value *result, bool null_succeeds)
void LoadMem (FullDecoder *decoder, wasm::LoadType type, const MemoryAccessImmediate &imm, const Value &index, Value *result)
void LoadTransform (FullDecoder *decoder, wasm::LoadType type, wasm::LoadTransformationKind transform, const MemoryAccessImmediate &imm, const Value &index, Value *result)
void LoadLane (FullDecoder *decoder, wasm::LoadType type, const Value &value, const Value &index, const MemoryAccessImmediate &imm, const uint8_t laneidx, Value *result)
void StoreMem (FullDecoder *decoder, wasm::StoreType type, const MemoryAccessImmediate &imm, const Value &index, const Value &value)
void StoreLane (FullDecoder *decoder, wasm::StoreType type, const MemoryAccessImmediate &imm, const Value &index, const Value &value, const uint8_t laneidx)
void CurrentMemoryPages (FullDecoder *decoder, const MemoryIndexImmediate &imm, Value *result)
void MemoryGrow (FullDecoder *decoder, const MemoryIndexImmediate &imm, const Value &value, Value *result)
void CallDirect (FullDecoder *decoder, const CallFunctionImmediate &imm, const Value args[], Value returns[])
void ReturnCall (FullDecoder *decoder, const CallFunctionImmediate &imm, const Value args[])
void CallIndirect (FullDecoder *decoder, const Value &index, const CallIndirectImmediate &imm, const Value args[], Value returns[])
void ReturnCallIndirect (FullDecoder *decoder, const Value &index, const CallIndirectImmediate &imm, const Value args[])
void CallRef (FullDecoder *decoder, const Value &func_ref, const wasm::FunctionSig *sig, const Value args[], Value returns[])
void ReturnCallRef (FullDecoder *decoder, const Value &func_ref, const wasm::FunctionSig *sig, const Value args[])
void BrOnNull (FullDecoder *decoder, const Value &ref_object, uint32_t depth, bool pass_null_along_branch, Value *result_on_fallthrough)
void BrOnNonNull (FullDecoder *decoder, const Value &ref_object, Value *result, uint32_t depth, bool)
void BrOnCast (FullDecoder *decoder, wasm::HeapType target_type, const Value &object, Value *value_on_branch, uint32_t br_depth, bool null_succeeds)
void BrOnCastDesc (FullDecoder *decoder, wasm::HeapType target_type, const Value &object, const Value &descriptor, Value *value_on_branch, uint32_t br_depth, bool null_succeeds)
void BrOnCastAbstract (FullDecoder *decoder, const Value &object, wasm::HeapType type, Value *value_on_branch, uint32_t br_depth, bool null_succeeds)
void BrOnCastFail (FullDecoder *decoder, wasm::HeapType target_type, const Value &object, Value *value_on_fallthrough, uint32_t br_depth, bool null_succeeds)
void BrOnCastDescFail (FullDecoder *decoder, wasm::HeapType target_type, const Value &object, const Value &descriptor, Value *value_on_fallthrough, uint32_t br_depth, bool null_succeeds)
void BrOnCastFailAbstract (FullDecoder *decoder, const Value &object, wasm::HeapType type, Value *value_on_fallthrough, uint32_t br_depth, bool null_succeeds)
void SimdOp (FullDecoder *decoder, WasmOpcode opcode, const Value *args, Value *result)
void SimdLaneOp (FullDecoder *decoder, WasmOpcode opcode, const SimdLaneImmediate &imm, base::Vector< const Value > inputs, Value *result)
void Simd8x16ShuffleOp (FullDecoder *decoder, const Simd128Immediate &imm, const Value &input0, const Value &input1, Value *result)
void StringNewWtf8 (FullDecoder *decoder, const MemoryIndexImmediate &imm, const unibrow::Utf8Variant variant, const Value &offset, const Value &size, Value *result)
void StringNewWtf8Array (FullDecoder *decoder, const unibrow::Utf8Variant variant, const Value &array, const Value &start, const Value &end, Value *result)
void StringNewWtf16 (FullDecoder *decoder, const MemoryIndexImmediate &imm, const Value &offset, const Value &size, Value *result)
void StringNewWtf16Array (FullDecoder *decoder, const Value &array, const Value &start, const Value &end, Value *result)
void StringConst (FullDecoder *decoder, const StringConstImmediate &imm, Value *result)
void StringMeasureWtf8 (FullDecoder *decoder, const unibrow::Utf8Variant variant, const Value &str, Value *result)
void StringMeasureWtf16 (FullDecoder *decoder, const Value &str, Value *result)
void StringEncodeWtf8 (FullDecoder *decoder, const MemoryIndexImmediate &memory, const unibrow::Utf8Variant variant, const Value &str, const Value &offset, Value *result)
void StringEncodeWtf8Array (FullDecoder *decoder, const unibrow::Utf8Variant variant, const Value &str, const Value &array, const Value &start, Value *result)
void StringEncodeWtf16 (FullDecoder *decoder, const MemoryIndexImmediate &imm, const Value &str, const Value &offset, Value *result)
void StringEncodeWtf16Array (FullDecoder *decoder, const Value &str, const Value &array, const Value &start, Value *result)
void StringConcat (FullDecoder *decoder, const Value &head, const Value &tail, Value *result)
void StringEq (FullDecoder *decoder, const Value &a, const Value &b, Value *result)
void StringIsUSVSequence (FullDecoder *decoder, const Value &str, Value *result)
void StringAsWtf8 (FullDecoder *decoder, const Value &str, Value *result)
void StringViewWtf8Advance (FullDecoder *decoder, const Value &view, const Value &pos, const Value &bytes, Value *result)
void StringViewWtf8Encode (FullDecoder *decoder, const MemoryIndexImmediate &memory, const unibrow::Utf8Variant variant, const Value &view, const Value &addr, const Value &pos, const Value &bytes, Value *next_pos, Value *bytes_written)
void StringViewWtf8Slice (FullDecoder *decoder, const Value &view, const Value &start, const Value &end, Value *result)
void StringAsWtf16 (FullDecoder *decoder, const Value &str, Value *result)
void StringViewWtf16GetCodeUnit (FullDecoder *decoder, const Value &view, const Value &pos, Value *result)
void StringViewWtf16Encode (FullDecoder *decoder, const MemoryIndexImmediate &imm, const Value &view, const Value &offset, const Value &pos, const Value &codeunits, Value *result)
void StringViewWtf16Slice (FullDecoder *decoder, const Value &view, const Value &start, const Value &end, Value *result)
void StringAsIter (FullDecoder *decoder, const Value &str, Value *result)
void StringViewIterNext (FullDecoder *decoder, const Value &view, Value *result)
void StringViewIterAdvance (FullDecoder *decoder, const Value &view, const Value &codepoints, Value *result)
void StringViewIterRewind (FullDecoder *decoder, const Value &view, const Value &codepoints, Value *result)
void StringViewIterSlice (FullDecoder *decoder, const Value &view, const Value &codepoints, Value *result)
void StringCompare (FullDecoder *decoder, const Value &lhs, const Value &rhs, Value *result)
void StringFromCodePoint (FullDecoder *decoder, const Value &code_point, Value *result)
void StringHash (FullDecoder *decoder, const Value &string, Value *result)
void Forward (FullDecoder *decoder, const Value &from, Value *to)
Static Public Attributes
static constexpr bool kUsesPoppedArgs = false
Private Member Functions
V< Any > DefaultValue (ValueType type)
Assembler & Asm ()
Private Attributes
Assembler & asm_
ZoneVector< OpIndex > locals_
base::Vector< const OpIndex > arguments_
V< WasmTrustedInstanceData > trusted_instance_data_
V< Any > result_
Detailed Description
template<class Assembler>
class v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >
Definition at line 123 of file wasm-in-js-inlining-reducer-inl.h.
Member Typedef Documentation
Control
template<class Assembler >
using v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Control = wasm::ControlBase<Value, ValidationTag>
Definition at line 136 of file wasm-in-js-inlining-reducer-inl.h.
FullDecoder
template<class Assembler >
using v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::FullDecoder = wasm::WasmFullDecoder<ValidationTag, WasmInJsInliningInterface>
Definition at line 126 of file wasm-in-js-inlining-reducer-inl.h.
ValidationTag
template<class Assembler >
using v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ValidationTag = wasm::Decoder::NoValidationTag
Definition at line 125 of file wasm-in-js-inlining-reducer-inl.h.
Constructor & Destructor Documentation
WasmInJsInliningInterface()
template<class Assembler >
v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::WasmInJsInliningInterface (Assembler & assembler, base::Vector< const OpIndex > arguments, V< WasmTrustedInstanceData > trusted_instance_data) [inline]
Definition at line 139 of file wasm-in-js-inlining-reducer-inl.h.
      : asm_(assembler),
        locals_(assembler.phase_zone()),
        arguments_(arguments),
        trusted_instance_data_(trusted_instance_data) {}
Member Function Documentation
ArrayAtomicCompareExchange()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicCompareExchange (FullDecoder * decoder, WasmOpcode opcode, const Value & array_obj, const ArrayIndexImmediate & imm, const Value & index, const Value & expected_value, const Value & new_value, AtomicMemoryOrder order, Value * result) [inline]
Definition at line 750 of file wasm-in-js-inlining-reducer-inl.h.
                                                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayAtomicGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicGet (FullDecoder * decoder, const Value & array_obj, const ArrayIndexImmediate & imm, const Value & index, bool is_signed, AtomicMemoryOrder memory_order, Value * result) [inline]
Definition at line 855 of file wasm-in-js-inlining-reducer-inl.h.
                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayAtomicRMW()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicRMW (FullDecoder * decoder, WasmOpcode opcode, const Value & array_obj, const ArrayIndexImmediate & imm, const Value & index, const Value & value, AtomicMemoryOrder order, Value * result) [inline]
Definition at line 743 of file wasm-in-js-inlining-reducer-inl.h.
                                                              {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayAtomicSet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicSet (FullDecoder * decoder, const Value & array_obj, const ArrayIndexImmediate & imm, const Value & index_val, const Value & value_val, AtomicMemoryOrder order) [inline]
Definition at line 866 of file wasm-in-js-inlining-reducer-inl.h.
                                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayCopy()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayCopy (FullDecoder * decoder, const Value & dst, const Value & dst_index, const Value & src, const Value & src_index, const ArrayIndexImmediate & src_imm, const Value & length) [inline]
Definition at line 874 of file wasm-in-js-inlining-reducer-inl.h.
                                                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayFill()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayFill (FullDecoder * decoder, ArrayIndexImmediate & imm, const Value & array, const Value & index, const Value & value, const Value & length) [inline]
Definition at line 879 of file wasm-in-js-inlining-reducer-inl.h.
                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayGet (FullDecoder * decoder, const Value & array_obj, const ArrayIndexImmediate & imm, const Value & index, bool is_signed, Value * result) [inline]
Definition at line 850 of file wasm-in-js-inlining-reducer-inl.h.
                                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayInitSegment()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayInitSegment (FullDecoder * decoder, const ArrayIndexImmediate & array_imm, const IndexImmediate & segment_imm, const Value & array, const Value & array_index, const Value & segment_offset, const Value & length) [inline]
Definition at line 895 of file wasm-in-js-inlining-reducer-inl.h.
                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayLen()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayLen (FullDecoder * decoder, const Value & array_obj, Value * result) [inline]
Definition at line 871 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayNew()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNew (FullDecoder * decoder, const ArrayIndexImmediate & imm, const Value & length, const Value & initial_value, Value * result) [inline]
Definition at line 837 of file wasm-in-js-inlining-reducer-inl.h.
                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayNewDefault()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNewDefault (FullDecoder * decoder, const ArrayIndexImmediate & imm, const Value & length, Value * result) [inline]
Definition at line 842 of file wasm-in-js-inlining-reducer-inl.h.
                                                           {
    // TODO(dlehmann): This will pull in/cause a lot of code duplication wrt.
    // the Wasm pipeline / `TurboshaftGraphBuildingInterface`.
    // How to reduce duplication best? Common superclass? But both will have
    // different Assemblers (reducer stacks), so I will have to templatize that.
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayNewFixed()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNewFixed (FullDecoder * decoder, const ArrayIndexImmediate & array_imm, const IndexImmediate & length_imm, const Value elements[], Value * result) [inline]
Definition at line 884 of file wasm-in-js-inlining-reducer-inl.h.
                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArrayNewSegment()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNewSegment (FullDecoder * decoder, const ArrayIndexImmediate & array_imm, const IndexImmediate & segment_imm, const Value & offset, const Value & length, Value * result) [inline]
Definition at line 889 of file wasm-in-js-inlining-reducer-inl.h.
                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ArraySet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArraySet (FullDecoder * decoder, const Value & array_obj, const ArrayIndexImmediate & imm, const Value & index, const Value & value) [inline]
Definition at line 861 of file wasm-in-js-inlining-reducer-inl.h.
                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Asm()
template<class Assembler >
Assembler& v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Asm () [inline], [private]
Definition at line 1240 of file wasm-in-js-inlining-reducer-inl.h.
{ return asm_; }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::asm_.
AssertNotNullTypecheck()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AssertNotNullTypecheck (FullDecoder * decoder, const Value & obj, Value * result) [inline]
Definition at line 707 of file wasm-in-js-inlining-reducer-inl.h.
                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
AssertNullTypecheck()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AssertNullTypecheck (FullDecoder * decoder, const Value & obj, Value * result) [inline]
Definition at line 702 of file wasm-in-js-inlining-reducer-inl.h.
                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
AtomicFence()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicFence (FullDecoder * decoder) [inline]
Definition at line 725 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
AtomicNotify()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicNotify (FullDecoder * decoder, const MemoryAccessImmediate & imm, OpIndex index, OpIndex num_waiters_to_wake, Value * result) [inline]
Definition at line 711 of file wasm-in-js-inlining-reducer-inl.h.
                                                                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
AtomicOp()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicOp (FullDecoder * decoder, WasmOpcode opcode, const Value args[], const size_t argc, const MemoryAccessImmediate & imm, Value * result) [inline]
Definition at line 720 of file wasm-in-js-inlining-reducer-inl.h.
                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
AtomicWait()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicWait (FullDecoder * decoder, WasmOpcode opcode, const MemoryAccessImmediate & imm, OpIndex index, OpIndex expected, V< Word64 > timeout, Value * result) [inline]
Definition at line 715 of file wasm-in-js-inlining-reducer-inl.h.
                                                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Bailout()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout (FullDecoder * decoder) [inline]
Definition at line 151 of file wasm-in-js-inlining-reducer-inl.h.
                                     {
    decoder->errorf("unsupported operation: %s",
                    decoder->SafeOpcodeNameAt(decoder->pc()));
  }
References v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::pc(), and v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::SafeOpcodeNameAt().
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicCompareExchange(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicRMW(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayAtomicSet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayCopy(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayFill(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayInitSegment(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayLen(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNew(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNewDefault(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNewFixed(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArrayNewSegment(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ArraySet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AssertNotNullTypecheck(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AssertNullTypecheck(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicFence(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicNotify(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicOp(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::AtomicWait(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOpImpl(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Block(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrIf(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCast(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastAbstract(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastDesc(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastDescFail(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastFail(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastFailAbstract(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnNonNull(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnNull(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOrRet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrTable(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CallDirect(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CallIndirect(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CallRef(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CatchAll(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CatchCase(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CatchException(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ContBind(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ContNew(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CurrentMemoryPages(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DataDrop(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Delegate(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::EffectHandlerTable(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ElemDrop(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Else(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::FallThruTo(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Forward(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalSet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I31GetS(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I31GetU(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I64Const(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::If(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LoadLane(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LoadMem(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LoadTransform(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Loop(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryCopy(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryFill(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryGrow(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryInit(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::PopControl(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefAsNonNull(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefCast(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefCastAbstract(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefCastDesc(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefFunc(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefGetDesc(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefI31(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefNull(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefTest(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefTestAbstract(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Resume(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ResumeThrow(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Rethrow(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ReturnCall(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ReturnCallIndirect(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ReturnCallRef(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::S128Const(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Select(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Simd8x16ShuffleOp(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::SimdLaneOp(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::SimdOp(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StoreLane(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StoreMem(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringAsIter(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringAsWtf16(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringAsWtf8(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringCompare(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringConcat(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringConst(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf16(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf16Array(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf8(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf8Array(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEq(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringFromCodePoint(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringHash(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringIsUSVSequence(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringMeasureWtf16(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringMeasureWtf8(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf16(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf16Array(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf8(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf8Array(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterAdvance(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterNext(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterRewind(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterSlice(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf16Encode(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf16GetCodeUnit(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf16Slice(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf8Advance(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf8Encode(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf8Slice(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicCompareExchange(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicRMW(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicSet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructNew(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructNewDefault(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructSet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Suspend(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Switch(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableCopy(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableFill(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableGrow(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableInit(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableSet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableSize(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Throw(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ThrowRef(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TraceInstruction(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Trap(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Try(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TryTable(), and v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOpImpl().
BinOp()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOp (FullDecoder * decoder, WasmOpcode opcode, const Value & lhs, const Value & rhs, Value * result) [inline]
Definition at line 203 of file wasm-in-js-inlining-reducer-inl.h.
                                              {
    result->op = BinOpImpl(decoder, opcode, lhs.op, rhs.op);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOpImpl(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Value::op, and v8::base::internal::result.
BinOpImpl()
template<class Assembler >
OpIndex v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOpImpl (FullDecoder * decoder, WasmOpcode opcode, OpIndex lhs, OpIndex rhs) [inline]
Definition at line 343 of file wasm-in-js-inlining-reducer-inl.h.
                                 {
    switch (opcode) {
      case wasm::kExprI32Add:
        return __ Word32Add(lhs, rhs);
      case wasm::kExprI32Sub:
        return __ Word32Sub(lhs, rhs);
      case wasm::kExprI32Mul:
        return __ Word32Mul(lhs, rhs);
      case wasm::kExprI32And:
        return __ Word32BitwiseAnd(lhs, rhs);
      case wasm::kExprI32Ior:
        return __ Word32BitwiseOr(lhs, rhs);
      case wasm::kExprI32Xor:
        return __ Word32BitwiseXor(lhs, rhs);
      case wasm::kExprI32Shl:
        // If possible, the bitwise-and gets optimized away later.
        return __ Word32ShiftLeft(lhs, __ Word32BitwiseAnd(rhs, 0x1f));
      case wasm::kExprI32ShrS:
        return __ Word32ShiftRightArithmetic(lhs,
                                             __ Word32BitwiseAnd(rhs, 0x1f));
      case wasm::kExprI32ShrU:
        return __ Word32ShiftRightLogical(lhs, __ Word32BitwiseAnd(rhs, 0x1f));
      case wasm::kExprI32Ror:
        return __ Word32RotateRight(lhs, __ Word32BitwiseAnd(rhs, 0x1f));
      case wasm::kExprI32Rol:
        if (SupportedOperations::word32_rol()) {
          return __ Word32RotateLeft(lhs, __ Word32BitwiseAnd(rhs, 0x1f));
        } else {
          return __ Word32RotateRight(
              lhs, __ Word32Sub(32, __ Word32BitwiseAnd(rhs, 0x1f)));
        }
      case wasm::kExprI32Eq:
        return __ Word32Equal(lhs, rhs);
      case wasm::kExprI32Ne:
        return __ Word32Equal(__ Word32Equal(lhs, rhs), 0);
      case wasm::kExprI32LtS:
        return __ Int32LessThan(lhs, rhs);
      case wasm::kExprI32LeS:
        return __ Int32LessThanOrEqual(lhs, rhs);
      case wasm::kExprI32LtU:
        return __ Uint32LessThan(lhs, rhs);
      case wasm::kExprI32LeU:
        return __ Uint32LessThanOrEqual(lhs, rhs);
      case wasm::kExprI32GtS:
        return __ Int32LessThan(rhs, lhs);
      case wasm::kExprI32GeS:
        return __ Int32LessThanOrEqual(rhs, lhs);
      case wasm::kExprI32GtU:
        return __ Uint32LessThan(rhs, lhs);
      case wasm::kExprI32GeU:
        return __ Uint32LessThanOrEqual(rhs, lhs);
      case wasm::kExprF32CopySign: {
        V<Word32> lhs_without_sign =
            __ Word32BitwiseAnd(__ BitcastFloat32ToWord32(lhs), 0x7fffffff);
        V<Word32> rhs_sign =
            __ Word32BitwiseAnd(__ BitcastFloat32ToWord32(rhs), 0x80000000);
        return __ BitcastWord32ToFloat32(
            __ Word32BitwiseOr(lhs_without_sign, rhs_sign));
      }
      case wasm::kExprF32Add:
        return __ Float32Add(lhs, rhs);
      case wasm::kExprF32Sub:
        return __ Float32Sub(lhs, rhs);
      case wasm::kExprF32Mul:
        return __ Float32Mul(lhs, rhs);
      case wasm::kExprF32Div:
        return __ Float32Div(lhs, rhs);
      case wasm::kExprF32Eq:
        return __ Float32Equal(lhs, rhs);
      case wasm::kExprF32Ne:
        return __ Word32Equal(__ Float32Equal(lhs, rhs), 0);
      case wasm::kExprF32Lt:
        return __ Float32LessThan(lhs, rhs);
      case wasm::kExprF32Le:
        return __ Float32LessThanOrEqual(lhs, rhs);
      case wasm::kExprF32Gt:
        return __ Float32LessThan(rhs, lhs);
      case wasm::kExprF32Ge:
        return __ Float32LessThanOrEqual(rhs, lhs);
      case wasm::kExprF32Min:
        return __ Float32Min(rhs, lhs);
      case wasm::kExprF32Max:
        return __ Float32Max(rhs, lhs);
      case wasm::kExprF64Add:
        return __ Float64Add(lhs, rhs);
      case wasm::kExprF64Sub:
        return __ Float64Sub(lhs, rhs);
      case wasm::kExprF64Mul:
        return __ Float64Mul(lhs, rhs);
      case wasm::kExprF64Div:
        return __ Float64Div(lhs, rhs);
      case wasm::kExprF64Eq:
        return __ Float64Equal(lhs, rhs);
      case wasm::kExprF64Ne:
        return __ Word32Equal(__ Float64Equal(lhs, rhs), 0);
      case wasm::kExprF64Lt:
        return __ Float64LessThan(lhs, rhs);
      case wasm::kExprF64Le:
        return __ Float64LessThanOrEqual(lhs, rhs);
      case wasm::kExprF64Gt:
        return __ Float64LessThan(rhs, lhs);
      case wasm::kExprF64Ge:
        return __ Float64LessThanOrEqual(rhs, lhs);
      case wasm::kExprF64Min:
        return __ Float64Min(lhs, rhs);
      case wasm::kExprF64Max:
        return __ Float64Max(lhs, rhs);
      case wasm::kExprRefEq:
        return __ TaggedEqual(lhs, rhs);
      // We currently don't support operations that:
      // - could trap,
      // - call a builtin,
      // - need the instance,
      // - require later Int64Lowering (which is currently only compatible with
      // the Wasm pipeline),
      // - are actually asm.js opcodes and not spec'ed in Wasm.
      case wasm::kExprI64Add:
      case wasm::kExprI64Sub:
      case wasm::kExprI64Mul:
      case wasm::kExprI64And:
      case wasm::kExprI64Ior:
      case wasm::kExprI64Xor:
      case wasm::kExprI64Shl:
      case wasm::kExprI64ShrS:
      case wasm::kExprI64ShrU:
      case wasm::kExprI64Ror:
      case wasm::kExprI64Rol:
      case wasm::kExprI64Eq:
      case wasm::kExprI64Ne:
      case wasm::kExprI64LtS:
      case wasm::kExprI64LeS:
      case wasm::kExprI64LtU:
      case wasm::kExprI64LeU:
      case wasm::kExprI64GtS:
      case wasm::kExprI64GeS:
      case wasm::kExprI64GtU:
      case wasm::kExprI64GeU:
      case wasm::kExprF64CopySign:
      case wasm::kExprI32DivS:
      case wasm::kExprI32DivU:
      case wasm::kExprI32RemS:
      case wasm::kExprI32RemU:
      case wasm::kExprI64DivS:
      case wasm::kExprI64DivU:
      case wasm::kExprI64RemS:
      case wasm::kExprI64RemU:
      // asm.js:
      case wasm::kExprF64Atan2:
      case wasm::kExprF64Pow:
      case wasm::kExprF64Mod:
      case wasm::kExprI32AsmjsDivS:
      case wasm::kExprI32AsmjsDivU:
      case wasm::kExprI32AsmjsRemS:
      case wasm::kExprI32AsmjsRemU:
      case wasm::kExprI32AsmjsStoreMem8:
      case wasm::kExprI32AsmjsStoreMem16:
      case wasm::kExprI32AsmjsStoreMem:
      case wasm::kExprF32AsmjsStoreMem:
      case wasm::kExprF64AsmjsStoreMem:
        // Not supported, but we are aware of it. Bailout below.
        break;
      default:
        // Fuzzers should alert us when we forget ops, but it's not security
        // critical, so we just bailout below as well.
        DCHECK_WITH_MSG(false, "unhandled binary op");
    }
    Bailout(decoder);
    return OpIndex::Invalid();
  }
References __, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout(), DCHECK_WITH_MSG, v8::internal::compiler::Float64Add(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BinOp().
Block()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Block (FullDecoder * decoder, Control * block) [inline]
Definition at line 592 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrIf()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrIf (FullDecoder * decoder, const Value & cond, uint32_t depth) [inline]
Definition at line 601 of file wasm-in-js-inlining-reducer-inl.h.
                                                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnCast()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCast (FullDecoder * decoder, wasm::HeapType target_type, const Value & object, Value * value_on_branch, uint32_t br_depth, bool null_succeeds) [inline]
Definition at line 1018 of file wasm-in-js-inlining-reducer-inl.h.
                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnCastAbstract()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastAbstract (FullDecoder * decoder, const Value & object, wasm::HeapType type, Value * value_on_branch, uint32_t br_depth, bool null_succeeds) [inline]
Definition at line 1029 of file wasm-in-js-inlining-reducer-inl.h.
                                                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnCastDesc()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastDesc (FullDecoder * decoder, wasm::HeapType target_type, const Value & object, const Value & descriptor, Value * value_on_branch, uint32_t br_depth, bool null_succeeds) [inline]
Definition at line 1023 of file wasm-in-js-inlining-reducer-inl.h.
                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnCastDescFail()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastDescFail (FullDecoder * decoder, wasm::HeapType target_type, const Value & object, const Value & descriptor, Value * value_on_fallthrough, uint32_t br_depth, bool null_succeeds) [inline]
Definition at line 1039 of file wasm-in-js-inlining-reducer-inl.h.
                                            {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnCastFail()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastFail (FullDecoder * decoder, wasm::HeapType target_type, const Value & object, Value * value_on_fallthrough, uint32_t br_depth, bool null_succeeds) [inline]
Definition at line 1034 of file wasm-in-js-inlining-reducer-inl.h.
                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnCastFailAbstract()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnCastFailAbstract (FullDecoder * decoder, const Value & object, wasm::HeapType type, Value * value_on_fallthrough, uint32_t br_depth, bool null_succeeds) [inline]
Definition at line 1045 of file wasm-in-js-inlining-reducer-inl.h.
                                                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnNonNull()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnNonNull (FullDecoder * decoder, const Value & ref_object, Value * result, uint32_t depth, bool) [inline]
Definition at line 1013 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOnNull()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOnNull (FullDecoder * decoder, const Value & ref_object, uint32_t depth, bool pass_null_along_branch, Value * result_on_fallthrough) [inline]
Definition at line 1008 of file wasm-in-js-inlining-reducer-inl.h.
                                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrOrRet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrOrRet (FullDecoder * decoder, uint32_t depth, uint32_t drop_values = 0) [inline]
Definition at line 598 of file wasm-in-js-inlining-reducer-inl.h.
                                                                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
BrTable()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::BrTable (FullDecoder * decoder, const BranchTableImmediate & imm, const Value & key) [inline]
Definition at line 604 of file wasm-in-js-inlining-reducer-inl.h.
                                 {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CallDirect()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CallDirect (FullDecoder * decoder, const CallFunctionImmediate & imm, const Value args[], Value returns[]) [inline]
Definition at line 979 of file wasm-in-js-inlining-reducer-inl.h.
                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CallIndirect()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CallIndirect (FullDecoder * decoder, const Value & index, const CallIndirectImmediate & imm, const Value args[], Value returns[]) [inline]
Definition at line 987 of file wasm-in-js-inlining-reducer-inl.h.
                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CallRef()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CallRef (FullDecoder * decoder, const Value & func_ref, const wasm::FunctionSig * sig, const Value args[], Value returns[]) [inline]
Definition at line 997 of file wasm-in-js-inlining-reducer-inl.h.
                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CatchAll()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CatchAll (FullDecoder * decoder, Control * block) [inline]
Definition at line 650 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CatchCase()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CatchCase (FullDecoder * decoder, Control * block, const wasm::CatchCase & catch_case, base::Vector< Value > values) [inline]
Definition at line 652 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CatchException()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CatchException (FullDecoder * decoder, const TagIndexImmediate & imm, Control * block, base::Vector< Value > values) [inline]
Definition at line 642 of file wasm-in-js-inlining-reducer-inl.h.
                                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ContBind()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ContBind (FullDecoder * decoder, const wasm::ContIndexImmediate & orig_imm, Value input_cont, const Value args[], const wasm::ContIndexImmediate & new_imm, Value * result) [inline]
Definition at line 664 of file wasm-in-js-inlining-reducer-inl.h.
                                                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ContNew()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ContNew (FullDecoder * decoder, const wasm::ContIndexImmediate & imm, const Value & func_ref, Value * result) [inline]
Definition at line 659 of file wasm-in-js-inlining-reducer-inl.h.
                                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
CurrentMemoryPages()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::CurrentMemoryPages (FullDecoder * decoder, const MemoryIndexImmediate & imm, Value * result) [inline]
Definition at line 966 of file wasm-in-js-inlining-reducer-inl.h.
                                         {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
DataDrop()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DataDrop (FullDecoder * decoder, const IndexImmediate & imm) [inline]
Definition at line 772 of file wasm-in-js-inlining-reducer-inl.h.
                                                                 {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
DefaultValue()
template<class Assembler >
V<Any> v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DefaultValue (ValueType type) [inline], [private]
Definition at line 1213 of file wasm-in-js-inlining-reducer-inl.h.
                                      {
    switch (type.kind()) {
      case wasm::kI8:
      case wasm::kI16:
      case wasm::kI32:
        return __ Word32Constant(int32_t{0});
      case wasm::kI64:
        return __ Word64Constant(int64_t{0});
      case wasm::kF16:
      case wasm::kF32:
        return __ Float32Constant(0.0f);
      case wasm::kF64:
        return __ Float64Constant(0.0);
      case wasm::kRefNull:
        return __ Null(type);
      case wasm::kS128: {
        uint8_t value[kSimd128Size] = {};
        return __ Simd128Constant(value);
      }
      case wasm::kVoid:
      case wasm::kRef:
      case wasm::kBottom:
      case wasm::kTop:
        UNREACHABLE();
    }
  }
References __, v8::internal::kSimd128Size, v8::internal::compiler::Null, v8::internal::tracing::type, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction().
Delegate()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Delegate (FullDecoder * decoder, uint32_t depth, Control * block) [inline]
Definition at line 646 of file wasm-in-js-inlining-reducer-inl.h.
                                                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
DoReturn()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DoReturn (FullDecoder * decoder, uint32_t drop_values) [inline]
Definition at line 611 of file wasm-in-js-inlining-reducer-inl.h.
                                                            {
    size_t return_count = decoder->sig_->return_count();
    if (return_count == 1) {
      result_ =
          decoder
              ->stack_value(static_cast<uint32_t>(return_count + drop_values))
              ->op;
    } else if (return_count == 0) {
      Isolate* isolate = __ data() -> isolate();
      DCHECK_NOT_NULL(isolate);
      result_ = __ HeapConstant(isolate->factory()->undefined_value());
    } else {
      // We currently don't support wrapper inlining with multi-value returns,
      // so this should never be hit.
      UNREACHABLE();
    }
  }
References __, DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Value::op, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::result_, v8::internal::Signature< T >::return_count(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::sig_, v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::stack_value(), and v8::internal::UNREACHABLE().
Drop()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Drop (FullDecoder * decoder) [inline]
Definition at line 555 of file wasm-in-js-inlining-reducer-inl.h.
{}
EffectHandlerTable()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::EffectHandlerTable (FullDecoder * decoder, Control * block) [inline]
Definition at line 695 of file wasm-in-js-inlining-reducer-inl.h.
                                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ElemDrop()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ElemDrop (FullDecoder * decoder, const IndexImmediate & imm) [inline]
Definition at line 807 of file wasm-in-js-inlining-reducer-inl.h.
                                                                 {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Else()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Else (FullDecoder * decoder, Control * if_block) [inline]
Definition at line 597 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
F32Const()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::F32Const (FullDecoder * decoder, Value * result, float value) [inline]
Definition at line 530 of file wasm-in-js-inlining-reducer-inl.h.
                                                                  {
    result->op = __ Float32Constant(value);
  }
References __, v8::base::internal::result, and v8::internal::value.
F64Const()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::F64Const (FullDecoder * decoder, Value * result, double value) [inline]
Definition at line 534 of file wasm-in-js-inlining-reducer-inl.h.
                                                                   {
    result->op = __ Float64Constant(value);
  }
References __, v8::base::internal::result, and v8::internal::value.
FallThruTo()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::FallThruTo (FullDecoder * decoder, Control * block) [inline]
Definition at line 609 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
FinishFunction()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::FinishFunction (FullDecoder * decoder) [inline]
Definition at line 182 of file wasm-in-js-inlining-reducer-inl.h.
{}
Forward()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Forward (FullDecoder * decoder, const Value & from, Value * to) [inline]
Definition at line 1207 of file wasm-in-js-inlining-reducer-inl.h.
                                                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
GlobalGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalGet (FullDecoder * decoder, Value * result, const GlobalIndexImmediate & imm) [inline]
Definition at line 572 of file wasm-in-js-inlining-reducer-inl.h.
                                                  {
    bool shared = decoder->module_->globals[imm.index].shared;
    if (shared) {
      return Bailout(decoder);
    }
    result->op = __ GlobalGet(trusted_instance_data_, imm.global);
  }
References __, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout(), v8::internal::wasm::GlobalIndexImmediate::global, v8::internal::wasm::WasmModule::globals, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::base::internal::result, and v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::trusted_instance_data_.
GlobalSet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalSet (FullDecoder * decoder, const Value & value, const GlobalIndexImmediate & imm) [inline]
Definition at line 581 of file wasm-in-js-inlining-reducer-inl.h.
                                                  {
    bool shared = decoder->module_->globals[imm.index].shared;
    if (shared) {
      return Bailout(decoder);
    }
    __ GlobalSet(trusted_instance_data_, value.op, imm.global);
  }
References __, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout(), v8::internal::wasm::GlobalIndexImmediate::global, v8::internal::wasm::WasmModule::globals, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::trusted_instance_data_, and v8::internal::value.
I31GetS()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I31GetS (FullDecoder * decoder, const Value & input, Value * result) [inline]
Definition at line 906 of file wasm-in-js-inlining-reducer-inl.h.
                                                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
I31GetU()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I31GetU (FullDecoder * decoder, const Value & input, Value * result) [inline]
Definition at line 910 of file wasm-in-js-inlining-reducer-inl.h.
                                                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
I32Const()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I32Const (FullDecoder * decoder, Value * result, int32_t value) [inline]
Definition at line 521 of file wasm-in-js-inlining-reducer-inl.h.
                                                                    {
    result->op = __ Word32Constant(value);
  }
References __, v8::base::internal::result, and v8::internal::value.
I64Const()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::I64Const (FullDecoder * decoder, Value * result, int64_t value) [inline]
Definition at line 525 of file wasm-in-js-inlining-reducer-inl.h.
                                                                    {
    // TODO(dlehmann,353475584): Support i64 ops.
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
If()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::If (FullDecoder * decoder, const Value & cond, Control * if_block) [inline]
Definition at line 594 of file wasm-in-js-inlining-reducer-inl.h.
                                                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
LoadLane()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LoadLane (FullDecoder * decoder, wasm::LoadType type, const Value & value, const Value & index, const MemoryAccessImmediate & imm, const uint8_t laneidx, Value * result) [inline]
Definition at line 948 of file wasm-in-js-inlining-reducer-inl.h.
                                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
LoadMem()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LoadMem (FullDecoder * decoder, wasm::LoadType type, const MemoryAccessImmediate & imm, const Value & index, Value * result) [inline]
Definition at line 937 of file wasm-in-js-inlining-reducer-inl.h.
                              {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
LoadTransform()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LoadTransform (FullDecoder * decoder, wasm::LoadType type, wasm::LoadTransformationKind transform, const MemoryAccessImmediate & imm, const Value & index, Value * result) [inline]
Definition at line 942 of file wasm-in-js-inlining-reducer-inl.h.
                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
LocalGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LocalGet (FullDecoder * decoder, Value * result, const IndexImmediate & imm) [inline]
Definition at line 557 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    result->op = locals_[imm.index];
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::locals_, and v8::base::internal::result.
LocalSet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LocalSet (FullDecoder * decoder, const Value & value, const IndexImmediate & imm) [inline]
Definition at line 562 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    locals_[imm.index] = value.op;
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::locals_, and v8::internal::value.
LocalTee()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LocalTee (FullDecoder * decoder, const Value & value, Value * result, const IndexImmediate & imm) [inline]
Definition at line 567 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    locals_[imm.index] = result->op = value.op;
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::locals_, v8::base::internal::result, and v8::internal::value.
Loop()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Loop (FullDecoder * decoder, Control * block) [inline]
Definition at line 593 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
MemoryCopy()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryCopy (FullDecoder * decoder, const MemoryCopyImmediate & imm, const Value & dst, const Value & src, const Value & size) [inline]
Definition at line 764 of file wasm-in-js-inlining-reducer-inl.h.
                                                                         {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
MemoryFill()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryFill (FullDecoder * decoder, const MemoryIndexImmediate & imm, const Value & dst, const Value & value, const Value & size) [inline]
Definition at line 768 of file wasm-in-js-inlining-reducer-inl.h.
                                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
MemoryGrow()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryGrow (FullDecoder * decoder, const MemoryIndexImmediate & imm, const Value & value, Value * result) [inline]
Definition at line 971 of file wasm-in-js-inlining-reducer-inl.h.
                                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
MemoryInit()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::MemoryInit (FullDecoder * decoder, const MemoryInitImmediate & imm, const Value & dst, const Value & src, const Value & size) [inline]
Definition at line 760 of file wasm-in-js-inlining-reducer-inl.h.
                                                                         {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
NextInstruction()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::NextInstruction (FullDecoder * decoder, WasmOpcode) [inline]
Definition at line 184 of file wasm-in-js-inlining-reducer-inl.h.
                                                         {
    // TODO(dlehmann,353475584): Copied from Turboshaft graph builder, still
    // need to understand what the inlining ID is / where to get it.
    // __ SetCurrentOrigin(
    // WasmPositionToOpIndex(decoder->position(), inlining_id_));
  }
NopForTestingUnsupportedInLiftoff()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::NopForTestingUnsupportedInLiftoff (FullDecoder * decoder) [inline]
Definition at line 191 of file wasm-in-js-inlining-reducer-inl.h.
                                                               {
    // This is just for testing bailouts in Liftoff, here it's just a nop.
  }
OnFirstError()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::OnFirstError (FullDecoder *) [inline]
Definition at line 149 of file wasm-in-js-inlining-reducer-inl.h.
{}
PopControl()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::PopControl (FullDecoder * decoder, Control * block) [inline]
Definition at line 610 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefAsNonNull()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefAsNonNull (FullDecoder * decoder, const Value & arg, Value * result) [inline]
Definition at line 551 of file wasm-in-js-inlining-reducer-inl.h.
                                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefCast()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefCast (FullDecoder * decoder, const Value & object, Value * result) [inline]
Definition at line 926 of file wasm-in-js-inlining-reducer-inl.h.
                                                                         {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefCastAbstract()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefCastAbstract (FullDecoder * decoder, const Value & object, wasm::HeapType type, Value * result, bool null_succeeds) [inline]
Definition at line 933 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefCastDesc()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefCastDesc (FullDecoder * decoder, const Value & object, const Value & descriptor, Value * result) [inline]
Definition at line 929 of file wasm-in-js-inlining-reducer-inl.h.
                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefFunc()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefFunc (FullDecoder * decoder, uint32_t function_index, Value * result) [inline]
Definition at line 547 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefGetDesc()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefGetDesc (FullDecoder * decoder, const Value & ref, Value * desc) [inline]
Definition at line 914 of file wasm-in-js-inlining-reducer-inl.h.
                                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefI31()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefI31 (FullDecoder * decoder, const Value & input, Value * result) [inline]
Definition at line 903 of file wasm-in-js-inlining-reducer-inl.h.
                                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefNull()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefNull (FullDecoder * decoder, ValueType type, Value * result) [inline]
Definition at line 543 of file wasm-in-js-inlining-reducer-inl.h.
                                                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefTest()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefTest (FullDecoder * decoder, wasm::HeapType target_type, const Value & object, Value * result, bool null_succeeds) [inline]
Definition at line 918 of file wasm-in-js-inlining-reducer-inl.h.
                                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
RefTestAbstract()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::RefTestAbstract (FullDecoder * decoder, const Value & object, wasm::HeapType type, Value * result, bool null_succeeds) [inline]
Definition at line 922 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Result()
template<class Assembler >
V<Any> v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Result () [inline]
Definition at line 147 of file wasm-in-js-inlining-reducer-inl.h.
{ return result_; }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::result_.
Resume()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Resume (FullDecoder * decoder, const wasm::ContIndexImmediate & imm, base::Vector< wasm::HandlerCase > handlers, const Value args[], const Value returns[]) [inline]
Definition at line 670 of file wasm-in-js-inlining-reducer-inl.h.
                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ResumeThrow()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ResumeThrow (FullDecoder * decoder, const wasm::ContIndexImmediate & cont_imm, const TagIndexImmediate & exc_imm, base::Vector< wasm::HandlerCase > handlers, const Value args[], const Value returns[]) [inline]
Definition at line 676 of file wasm-in-js-inlining-reducer-inl.h.
                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Rethrow()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Rethrow (FullDecoder * decoder, Control * block) [inline]
Definition at line 641 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ReturnCall()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ReturnCall (FullDecoder * decoder, const CallFunctionImmediate & imm, const Value args[]) [inline]
Definition at line 983 of file wasm-in-js-inlining-reducer-inl.h.
                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ReturnCallIndirect()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ReturnCallIndirect (FullDecoder * decoder, const Value & index, const CallIndirectImmediate & imm, const Value args[]) [inline]
Definition at line 992 of file wasm-in-js-inlining-reducer-inl.h.
                                              {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ReturnCallRef()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ReturnCallRef (FullDecoder * decoder, const Value & func_ref, const wasm::FunctionSig * sig, const Value args[]) [inline]
Definition at line 1003 of file wasm-in-js-inlining-reducer-inl.h.
                                                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
S128Const()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::S128Const (FullDecoder * decoder, const Simd128Immediate & imm, Value * result) [inline]
Definition at line 538 of file wasm-in-js-inlining-reducer-inl.h.
                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Select()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Select (FullDecoder * decoder, const Value & cond, const Value & fval, const Value & tval, Value * result) [inline]
Definition at line 629 of file wasm-in-js-inlining-reducer-inl.h.
                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Simd8x16ShuffleOp()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Simd8x16ShuffleOp (FullDecoder * decoder, const Simd128Immediate & imm, const Value & input0, const Value & input1, Value * result) [inline]
Definition at line 1062 of file wasm-in-js-inlining-reducer-inl.h.
                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
SimdLaneOp()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::SimdLaneOp (FullDecoder * decoder, WasmOpcode opcode, const SimdLaneImmediate & imm, base::Vector< const Value > inputs, Value * result) [inline]
Definition at line 1057 of file wasm-in-js-inlining-reducer-inl.h.
                                                                 {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
SimdOp()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::SimdOp (FullDecoder * decoder, WasmOpcode opcode, const Value * args, Value * result) [inline]
Definition at line 1053 of file wasm-in-js-inlining-reducer-inl.h.
                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StartFunction()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction (FullDecoder * decoder) [inline]
Definition at line 156 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    locals_.resize(decoder->num_locals());
    // Initialize the function parameters, which are part of the local space.
    CHECK_LE(arguments_.size(), locals_.size());
    std::copy(arguments_.begin(), arguments_.end(), locals_.begin());
    // Initialize the non-parameter locals.
    uint32_t index = static_cast<uint32_t>(decoder->sig_->parameter_count());
    CHECK_EQ(index, arguments_.size());
    while (index < decoder->num_locals()) {
      ValueType type = decoder->local_type(index);
      OpIndex op;
      if (!type.is_defaultable()) {
        DCHECK(type.is_reference());
        op = __ RootConstant(RootIndex::kOptimizedOut);
      } else {
        op = DefaultValue(type);
      }
      while (index < decoder->num_locals() &&
             decoder->local_type(index) == type) {
        locals_[index++] = op;
      }
    }
  }
References __, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::arguments_, CHECK_EQ, CHECK_LE, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DefaultValue(), v8::internal::index, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::local_type(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::locals_, v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::num_locals(), v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::sig_, and v8::internal::tracing::type.
StartFunctionBody()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunctionBody (FullDecoder * decoder, Control * block) [inline]
Definition at line 181 of file wasm-in-js-inlining-reducer-inl.h.
{}
StoreLane()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StoreLane (FullDecoder * decoder, wasm::StoreType type, const MemoryAccessImmediate & imm, const Value & index, const Value & value, const uint8_t laneidx) [inline]
Definition at line 960 of file wasm-in-js-inlining-reducer-inl.h.
                                                            {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StoreMem()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StoreMem (FullDecoder * decoder, wasm::StoreType type, const MemoryAccessImmediate & imm, const Value & index, const Value & value) [inline]
Definition at line 954 of file wasm-in-js-inlining-reducer-inl.h.
                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringAsIter()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringAsIter (FullDecoder * decoder, const Value & str, Value * result) [inline]
Definition at line 1175 of file wasm-in-js-inlining-reducer-inl.h.
                                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringAsWtf16()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringAsWtf16 (FullDecoder * decoder, const Value & str, Value * result) [inline]
Definition at line 1157 of file wasm-in-js-inlining-reducer-inl.h.
                                                                            {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringAsWtf8()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringAsWtf8 (FullDecoder * decoder, const Value & str, Value * result) [inline]
Definition at line 1136 of file wasm-in-js-inlining-reducer-inl.h.
                                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringCompare()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringCompare (FullDecoder * decoder, const Value & lhs, const Value & rhs, Value * result) [inline]
Definition at line 1195 of file wasm-in-js-inlining-reducer-inl.h.
                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringConcat()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringConcat (FullDecoder * decoder, const Value & head, const Value & tail, Value * result) [inline]
Definition at line 1124 of file wasm-in-js-inlining-reducer-inl.h.
                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringConst()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringConst (FullDecoder * decoder, const StringConstImmediate & imm, Value * result) [inline]
Definition at line 1090 of file wasm-in-js-inlining-reducer-inl.h.
                                  {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringEncodeWtf16()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf16 (FullDecoder * decoder, const MemoryIndexImmediate & imm, const Value & str, const Value & offset, Value * result) [inline]
Definition at line 1115 of file wasm-in-js-inlining-reducer-inl.h.
                                                                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringEncodeWtf16Array()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf16Array (FullDecoder * decoder, const Value & str, const Value & array, const Value & start, Value * result) [inline]
Definition at line 1119 of file wasm-in-js-inlining-reducer-inl.h.
                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringEncodeWtf8()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf8 (FullDecoder * decoder, const MemoryIndexImmediate & memory, const unibrow::Utf8Variant variant, const Value & str, const Value & offset, Value * result) [inline]
Definition at line 1103 of file wasm-in-js-inlining-reducer-inl.h.
                                                            {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringEncodeWtf8Array()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEncodeWtf8Array (FullDecoder * decoder, const unibrow::Utf8Variant variant, const Value & str, const Value & array, const Value & start, Value * result) [inline]
Definition at line 1109 of file wasm-in-js-inlining-reducer-inl.h.
                                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringEq()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringEq (FullDecoder * decoder, const Value & a, const Value & b, Value * result) [inline]
Definition at line 1128 of file wasm-in-js-inlining-reducer-inl.h.
                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringFromCodePoint()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringFromCodePoint (FullDecoder * decoder, const Value & code_point, Value * result) [inline]
Definition at line 1199 of file wasm-in-js-inlining-reducer-inl.h.
                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringHash()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringHash (FullDecoder * decoder, const Value & string, Value * result) [inline]
Definition at line 1203 of file wasm-in-js-inlining-reducer-inl.h.
                                                                            {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringIsUSVSequence()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringIsUSVSequence (FullDecoder * decoder, const Value & str, Value * result) [inline]
Definition at line 1132 of file wasm-in-js-inlining-reducer-inl.h.
                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringMeasureWtf16()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringMeasureWtf16 (FullDecoder * decoder, const Value & str, Value * result) [inline]
Definition at line 1099 of file wasm-in-js-inlining-reducer-inl.h.
                                         {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringMeasureWtf8()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringMeasureWtf8 (FullDecoder * decoder, const unibrow::Utf8Variant variant, const Value & str, Value * result) [inline]
Definition at line 1094 of file wasm-in-js-inlining-reducer-inl.h.
                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringNewWtf16()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf16 (FullDecoder * decoder, const MemoryIndexImmediate & imm, const Value & offset, const Value & size, Value * result) [inline]
Definition at line 1081 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringNewWtf16Array()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf16Array (FullDecoder * decoder, const Value & array, const Value & start, const Value & end, Value * result) [inline]
Definition at line 1085 of file wasm-in-js-inlining-reducer-inl.h.
                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringNewWtf8()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf8 (FullDecoder * decoder, const MemoryIndexImmediate & imm, const unibrow::Utf8Variant variant, const Value & offset, const Value & size, Value * result) [inline]
Definition at line 1070 of file wasm-in-js-inlining-reducer-inl.h.
                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringNewWtf8Array()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringNewWtf8Array (FullDecoder * decoder, const unibrow::Utf8Variant variant, const Value & array, const Value & start, const Value & end, Value * result) [inline]
Definition at line 1075 of file wasm-in-js-inlining-reducer-inl.h.
                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewIterAdvance()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterAdvance (FullDecoder * decoder, const Value & view, const Value & codepoints, Value * result) [inline]
Definition at line 1183 of file wasm-in-js-inlining-reducer-inl.h.
                                                                     {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewIterNext()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterNext (FullDecoder * decoder, const Value & view, Value * result) [inline]
Definition at line 1179 of file wasm-in-js-inlining-reducer-inl.h.
                                         {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewIterRewind()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterRewind (FullDecoder * decoder, const Value & view, const Value & codepoints, Value * result) [inline]
Definition at line 1187 of file wasm-in-js-inlining-reducer-inl.h.
                                                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewIterSlice()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewIterSlice (FullDecoder * decoder, const Value & view, const Value & codepoints, Value * result) [inline]
Definition at line 1191 of file wasm-in-js-inlining-reducer-inl.h.
                                                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewWtf16Encode()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf16Encode (FullDecoder * decoder, const MemoryIndexImmediate & imm, const Value & view, const Value & offset, const Value & pos, const Value & codeunits, Value * result) [inline]
Definition at line 1164 of file wasm-in-js-inlining-reducer-inl.h.
                                                                    {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewWtf16GetCodeUnit()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf16GetCodeUnit (FullDecoder * decoder, const Value & view, const Value & pos, Value * result) [inline]
Definition at line 1160 of file wasm-in-js-inlining-reducer-inl.h.
                                                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewWtf16Slice()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf16Slice (FullDecoder * decoder, const Value & view, const Value & start, const Value & end, Value * result) [inline]
Definition at line 1170 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewWtf8Advance()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf8Advance (FullDecoder * decoder, const Value & view, const Value & pos, const Value & bytes, Value * result) [inline]
Definition at line 1139 of file wasm-in-js-inlining-reducer-inl.h.
                                            {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewWtf8Encode()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf8Encode (FullDecoder * decoder, const MemoryIndexImmediate & memory, const unibrow::Utf8Variant variant, const Value & view, const Value & addr, const Value & pos, const Value & bytes, Value * next_pos, Value * bytes_written) [inline]
Definition at line 1144 of file wasm-in-js-inlining-reducer-inl.h.
                                                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StringViewWtf8Slice()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StringViewWtf8Slice (FullDecoder * decoder, const Value & view, const Value & start, const Value & end, Value * result) [inline]
Definition at line 1152 of file wasm-in-js-inlining-reducer-inl.h.
                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructAtomicCompareExchange()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicCompareExchange (FullDecoder * decoder, WasmOpcode opcode, const Value & struct_object, const FieldImmediate & field, const Value & expected_value, const Value & new_value, AtomicMemoryOrder order, Value * result) [inline]
Definition at line 734 of file wasm-in-js-inlining-reducer-inl.h.
                                                                           {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructAtomicGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicGet (FullDecoder * decoder, const Value & struct_obj, const FieldImmediate & field, bool is_signed, AtomicMemoryOrder memory_order, Value * result) [inline]
Definition at line 827 of file wasm-in-js-inlining-reducer-inl.h.
                                                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructAtomicRMW()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicRMW (FullDecoder * decoder, WasmOpcode opcode, const Value & struct_object, const FieldImmediate & field, const Value & field_value, AtomicMemoryOrder order, Value * result) [inline]
Definition at line 727 of file wasm-in-js-inlining-reducer-inl.h.
                                      {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructAtomicSet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructAtomicSet (FullDecoder * decoder, const Value & struct_object, const FieldImmediate & field, const Value & field_value, AtomicMemoryOrder memory_order) [inline]
Definition at line 832 of file wasm-in-js-inlining-reducer-inl.h.
                                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructGet (FullDecoder * decoder, const Value & struct_object, const FieldImmediate & field, bool is_signed, Value * result) [inline]
Definition at line 819 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructNew()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructNew (FullDecoder * decoder, const StructIndexImmediate & imm, const Value & descriptor, const Value args[], Value * result) [inline]
Definition at line 811 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructNewDefault()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructNewDefault (FullDecoder * decoder, const StructIndexImmediate & imm, const Value & descriptor, Value * result) [inline]
Definition at line 815 of file wasm-in-js-inlining-reducer-inl.h.
                                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
StructSet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StructSet (FullDecoder * decoder, const Value & struct_object, const FieldImmediate & field, const Value & field_value) [inline]
Definition at line 823 of file wasm-in-js-inlining-reducer-inl.h.
                                                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Suspend()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Suspend (FullDecoder * decoder, const TagIndexImmediate & imm, const Value args[], const Value returns[]) [inline]
Definition at line 690 of file wasm-in-js-inlining-reducer-inl.h.
                                                          {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Switch()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Switch (FullDecoder * decoder, const TagIndexImmediate & tag_imm, const wasm::ContIndexImmediate & con_imm, const Value & cont_ref, const Value args[], Value returns[]) [inline]
Definition at line 684 of file wasm-in-js-inlining-reducer-inl.h.
                                                   {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableCopy()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableCopy (FullDecoder * decoder, const TableCopyImmediate & imm, const Value & dst_val, const Value & src_val, const Value & size_val) [inline]
Definition at line 789 of file wasm-in-js-inlining-reducer-inl.h.
                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableFill()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableFill (FullDecoder * decoder, const TableIndexImmediate & imm, const Value & start, const Value & value, const Value & count) [inline]
Definition at line 798 of file wasm-in-js-inlining-reducer-inl.h.
                                                                             {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableGet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableGet (FullDecoder * decoder, const Value & index, Value * result, const TableIndexImmediate & imm) [inline]
Definition at line 776 of file wasm-in-js-inlining-reducer-inl.h.
                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableGrow()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableGrow (FullDecoder * decoder, const TableIndexImmediate & imm, const Value & value, const Value & delta, Value * result) [inline]
Definition at line 794 of file wasm-in-js-inlining-reducer-inl.h.
                                                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableInit()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableInit (FullDecoder * decoder, const TableInitImmediate & imm, const Value & dst_val, const Value & src_val, const Value & size_val) [inline]
Definition at line 784 of file wasm-in-js-inlining-reducer-inl.h.
                                        {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableSet()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableSet (FullDecoder * decoder, const Value & index, const Value & value, const TableIndexImmediate & imm) [inline]
Definition at line 780 of file wasm-in-js-inlining-reducer-inl.h.
                                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TableSize()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TableSize (FullDecoder * decoder, const TableIndexImmediate & imm, Value * result) [inline]
Definition at line 802 of file wasm-in-js-inlining-reducer-inl.h.
                                {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Throw()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Throw (FullDecoder * decoder, const TagIndexImmediate & imm, const Value arg_values[]) [inline]
Definition at line 637 of file wasm-in-js-inlining-reducer-inl.h.
                                       {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
ThrowRef()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::ThrowRef (FullDecoder * decoder, Value * value) [inline]
Definition at line 657 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TraceInstruction()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TraceInstruction (FullDecoder * decoder, uint32_t markid) [inline]
Definition at line 195 of file wasm-in-js-inlining-reducer-inl.h.
                                                               {
    Bailout(decoder);
  }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Trap()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Trap (FullDecoder * decoder, wasm::TrapReason reason) [inline]
Definition at line 701 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
Try()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Try (FullDecoder * decoder, Control * block) [inline]
Definition at line 636 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
TryTable()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::TryTable (FullDecoder * decoder, Control * block) [inline]
Definition at line 651 of file wasm-in-js-inlining-reducer-inl.h.
{ Bailout(decoder); }
References v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout().
UnOp()
template<class Assembler >
void v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOp (FullDecoder * decoder, WasmOpcode opcode, const Value & value, Value * result) [inline]
Definition at line 199 of file wasm-in-js-inlining-reducer-inl.h.
                           {
    result->op = UnOpImpl(decoder, opcode, value.op, value.type);
  }
References v8::base::internal::result, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOpImpl(), and v8::internal::value.
UnOpImpl()
template<class Assembler >
OpIndex v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOpImpl (FullDecoder * decoder, WasmOpcode opcode, OpIndex arg, ValueType input_type) [inline]
Definition at line 208 of file wasm-in-js-inlining-reducer-inl.h.
                                           {
    switch (opcode) {
      case wasm::kExprI32Eqz:
        return __ Word32Equal(arg, 0);
      case wasm::kExprF32Abs:
        return __ Float32Abs(arg);
      case wasm::kExprF32Neg:
        return __ Float32Negate(arg);
      case wasm::kExprF32Sqrt:
        return __ Float32Sqrt(arg);
      case wasm::kExprF64Abs:
        return __ Float64Abs(arg);
      case wasm::kExprF64Neg:
        return __ Float64Negate(arg);
      case wasm::kExprF64Sqrt:
        return __ Float64Sqrt(arg);
      case wasm::kExprF64SConvertI32:
        return __ ChangeInt32ToFloat64(arg);
      case wasm::kExprF64UConvertI32:
        return __ ChangeUint32ToFloat64(arg);
      case wasm::kExprF32SConvertI32:
        return __ ChangeInt32ToFloat32(arg);
      case wasm::kExprF32UConvertI32:
        return __ ChangeUint32ToFloat32(arg);
      case wasm::kExprF32ConvertF64:
        return __ TruncateFloat64ToFloat32(arg);
      case wasm::kExprF64ConvertF32:
        return __ ChangeFloat32ToFloat64(arg);
      case wasm::kExprF32ReinterpretI32:
        return __ BitcastWord32ToFloat32(arg);
      case wasm::kExprI32ReinterpretF32:
        return __ BitcastFloat32ToWord32(arg);
      case wasm::kExprI32Clz:
        return __ Word32CountLeadingZeros(arg);
      case wasm::kExprI32SExtendI8:
        return __ Word32SignExtend8(arg);
      case wasm::kExprI32SExtendI16:
        return __ Word32SignExtend16(arg);
      case wasm::kExprRefIsNull:
        return __ IsNull(arg, input_type);
      case wasm::kExprRefAsNonNull:
        // We abuse ref.as_non_null opcode (which is ordinarily a binary op and
        // not otherwise used in this switch) as a sentinel for the negation of
        // ref.is_null. See `function-body-decoder-impl.h`
        return __ Word32Equal(__ IsNull(arg, input_type), 0);
      // We currently don't support operations that:
      // - could trap,
      // - call a builtin,
      // - need the instance,
      // - require later Int64Lowering (which is currently only compatible with
      // the Wasm pipeline),
      // - are actually asm.js opcodes and not spec'ed in Wasm.
      case wasm::kExprI32ConvertI64:
      case wasm::kExprI64SConvertI32:
      case wasm::kExprI64UConvertI32:
      case wasm::kExprF64ReinterpretI64:
      case wasm::kExprI64ReinterpretF64:
      case wasm::kExprI64Clz:
      case wasm::kExprI64Eqz:
      case wasm::kExprI64SExtendI8:
      case wasm::kExprI64SExtendI16:
      case wasm::kExprI64SExtendI32:
      case wasm::kExprI32SConvertF32:
      case wasm::kExprI32UConvertF32:
      case wasm::kExprI32SConvertF64:
      case wasm::kExprI32UConvertF64:
      case wasm::kExprI64SConvertF32:
      case wasm::kExprI64UConvertF32:
      case wasm::kExprI64SConvertF64:
      case wasm::kExprI64UConvertF64:
      case wasm::kExprI32SConvertSatF32:
      case wasm::kExprI32UConvertSatF32:
      case wasm::kExprI32SConvertSatF64:
      case wasm::kExprI32UConvertSatF64:
      case wasm::kExprI64SConvertSatF32:
      case wasm::kExprI64UConvertSatF32:
      case wasm::kExprI64SConvertSatF64:
      case wasm::kExprI64UConvertSatF64:
      case wasm::kExprI32Ctz:
      case wasm::kExprI32Popcnt:
      case wasm::kExprF32Floor:
      case wasm::kExprF32Ceil:
      case wasm::kExprF32Trunc:
      case wasm::kExprF32NearestInt:
      case wasm::kExprF64Floor:
      case wasm::kExprF64Ceil:
      case wasm::kExprF64Trunc:
      case wasm::kExprF64NearestInt:
      case wasm::kExprI64Ctz:
      case wasm::kExprI64Popcnt:
      case wasm::kExprF32SConvertI64:
      case wasm::kExprF32UConvertI64:
      case wasm::kExprF64SConvertI64:
      case wasm::kExprF64UConvertI64:
      // TODO(dlehmann): Fix arm64 no-ptr-compression builds, see relevant
      // earlier CL https://crrev.com/c/4311941/1..4.
      case wasm::kExprAnyConvertExtern:
      case wasm::kExprExternConvertAny:
      // asm.js:
      case wasm::kExprF64Acos:
      case wasm::kExprF64Asin:
      case wasm::kExprF64Atan:
      case wasm::kExprF64Cos:
      case wasm::kExprF64Sin:
      case wasm::kExprF64Tan:
      case wasm::kExprF64Exp:
      case wasm::kExprF64Log:
      case wasm::kExprI32AsmjsLoadMem8S:
      case wasm::kExprI32AsmjsLoadMem8U:
      case wasm::kExprI32AsmjsLoadMem16S:
      case wasm::kExprI32AsmjsLoadMem16U:
      case wasm::kExprI32AsmjsLoadMem:
      case wasm::kExprF32AsmjsLoadMem:
      case wasm::kExprF64AsmjsLoadMem:
      case wasm::kExprI32AsmjsSConvertF32:
      case wasm::kExprI32AsmjsUConvertF32:
      case wasm::kExprI32AsmjsSConvertF64:
      case wasm::kExprI32AsmjsUConvertF64:
        // Not supported, but we are aware of it. Bailout below.
        break;
      default:
        // Fuzzers should alert us when we forget ops, but it's not security
        // critical, so we just bailout below as well.
        DCHECK_WITH_MSG(false, "unhandled unary op");
    }
    Bailout(decoder);
    return OpIndex::Invalid();
  }
References __, v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Bailout(), DCHECK_WITH_MSG, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::IsNull(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::UnOp().
Member Data Documentation
arguments_
template<class Assembler >
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::arguments_ [private]
Definition at line 1250 of file wasm-in-js-inlining-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction().
asm_
template<class Assembler >
Assembler& v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::asm_ [private]
Definition at line 1241 of file wasm-in-js-inlining-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Asm().
kUsesPoppedArgs
template<class Assembler >
constexpr bool v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::kUsesPoppedArgs = false [static], [constexpr]
Definition at line 137 of file wasm-in-js-inlining-reducer-inl.h.
locals_
template<class Assembler >
ZoneVector<OpIndex> v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::locals_ [private]
Definition at line 1246 of file wasm-in-js-inlining-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LocalGet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LocalSet(), v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::LocalTee(), and v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::StartFunction().
result_
template<class Assembler >
V<Any> v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::result_ [private]
Definition at line 1254 of file wasm-in-js-inlining-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::DoReturn(), and v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::Result().
trusted_instance_data_
template<class Assembler >
V<WasmTrustedInstanceData> v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::trusted_instance_data_ [private]
Definition at line 1251 of file wasm-in-js-inlining-reducer-inl.h.
Referenced by v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalGet(), and v8::internal::compiler::turboshaft::WasmInJsInliningInterface< Assembler >::GlobalSet().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-in-js-inlining-reducer-inl.h