v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor Class Reference
Public Member Functions
bool EnforceImplications ()
Private Member Functions
template<class T >
bool TriggerImplication (bool premise, const char *premise_name, FlagValue< T > *conclusion_value, const char *conclusion_name, T value, bool weak_implication)
template<class T >
bool TriggerImplication (bool premise, const char *premise_name, const FlagValue< T > *conclusion_value, const char *conclusion_name, T value, bool weak_implication)
void CheckForCycle ()
Private Attributes
size_t num_iterations_ = 0
uint32_t cycle_start_hash_
std::ostringstream cycle_
Static Private Attributes
static constexpr size_t kMaxNumIterations = kNumFlags
Detailed Description
Definition at line 989 of file flags.cc.
Member Function Documentation
CheckForCycle()
void v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::CheckForCycle () [inline], [private]
Definition at line 1052 of file flags.cc.
                       {
    // Make sure flag implications reach a fixed point within
    // {kMaxNumIterations} iterations.
    if (++num_iterations_ < kMaxNumIterations) return;
    if (num_iterations_ == kMaxNumIterations) {
      // Start cycle detection.
      DCHECK(cycle_.str().empty());
      cycle_start_hash_ = ComputeFlagListHash();
      return;
    }
    DCHECK_NE(0, cycle_start_hash_);
    // We accept spurious but highly unlikely hash collisions here. This is
    // only a debug output anyway.
    if (ComputeFlagListHash() == cycle_start_hash_) {
      DCHECK(!cycle_.str().empty());
      // {cycle_} starts with a newline.
      FATAL("Cycle in flag implications:%s", cycle_.str().c_str());
    }
    // We must have found a cycle within another {kMaxNumIterations}.
    DCHECK_GE(2 * kMaxNumIterations, num_iterations_);
  }
References v8::internal::ComputeFlagListHash(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_NE, and FATAL.
EnforceImplications()
bool v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::EnforceImplications () [inline]
Definition at line 992 of file flags.cc.
                             {
    bool changed = false;
#define FLAG_MODE_DEFINE_IMPLICATIONS
#include "src/flags/flag-definitions.h" // NOLINT(build/include)
#undef FLAG_MODE_DEFINE_IMPLICATIONS
    CheckForCycle();
    return changed;
  }
TriggerImplication() [1/2]
template<class T >
bool v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::TriggerImplication (bool premise, const char * premise_name, const FlagValue< T > * conclusion_value, const char * conclusion_name, T value, bool weak_implication) [inline], [private]
Definition at line 1032 of file flags.cc.
                                                 {
    if (!premise) return false;
    Flag* conclusion_flag = FindImplicationFlagByName(conclusion_name);
    // Because this is the `const FlagValue*` overload:
    DCHECK(conclusion_flag->IsReadOnly());
    if (!conclusion_flag->CheckFlagChange(
            weak_implication ? Flag::SetBy::kWeakImplication
                             : Flag::SetBy::kImplication,
            conclusion_value->value() != value, premise_name)) {
      return false;
    }
    // Must equal the default value, otherwise CheckFlagChange should've
    // returned false.
    DCHECK_EQ(value, conclusion_flag->GetDefaultValue<T>());
    return true;
  }
References v8::internal::Flag::CheckFlagChange(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FindImplicationFlagByName(), v8::internal::Flag::GetDefaultValue(), v8::internal::Flag::IsReadOnly(), v8::internal::Flag::kImplication, v8::internal::Flag::kWeakImplication, v8::internal::FlagValue< T >::value(), and v8::internal::value.
TriggerImplication() [2/2]
template<class T >
bool v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::TriggerImplication (bool premise, const char * premise_name, FlagValue< T > * conclusion_value, const char * conclusion_name, T value, bool weak_implication) [inline], [private]
Definition at line 1004 of file flags.cc.
                                                 {
    if (!premise) return false;
    Flag* conclusion_flag = FindImplicationFlagByName(conclusion_name);
    if (!conclusion_flag->CheckFlagChange(
            weak_implication ? Flag::SetBy::kWeakImplication
                             : Flag::SetBy::kImplication,
            conclusion_value->value() != value, premise_name)) {
      return false;
    }
    if (V8_UNLIKELY(num_iterations_ >= kMaxNumIterations)) {
      cycle_ << "\n" << FlagName{premise_name} << " -> ";
      if constexpr (std::is_same_v<T, bool>) {
        cycle_ << FlagName{conclusion_flag->name(), !value};
      } else {
        cycle_ << FlagName{conclusion_flag->name()} << " = " << value;
      }
    }
    *conclusion_value = value;
    return true;
  }
References v8::internal::Flag::CheckFlagChange(), v8::internal::FindImplicationFlagByName(), v8::internal::Flag::kImplication, v8::internal::Flag::kWeakImplication, v8::internal::Flag::name(), V8_UNLIKELY, v8::internal::FlagValue< T >::value(), and v8::internal::value.
Member Data Documentation
cycle_
std::ostringstream v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::cycle_ [private]
Definition at line 1081 of file flags.cc.
cycle_start_hash_
uint32_t v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::cycle_start_hash_ [private]
Definition at line 1080 of file flags.cc.
kMaxNumIterations
constexpr size_t v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::kMaxNumIterations = kNumFlags [static], [constexpr], [private]
Definition at line 1076 of file flags.cc.
num_iterations_
size_t v8::internal::anonymous_namespace{flags.cc}::ImplicationProcessor::num_iterations_ = 0 [private]
Definition at line 1077 of file flags.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/flags/flags.cc