v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror Class Reference
Public Member Functions
ObjectMirror (v8::Local< v8::Object > value, const String16 &description)
ObjectMirror (v8::Local< v8::Object > value, const String16 &subtype, const String16 &description)
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
void buildObjectPreview (v8::Local< v8::Context > context, bool generatePreviewForTable, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *result) const override
void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *result) const override
void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< PropertyPreview > *result) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Private Member Functions
void buildObjectPreviewInternal (v8::Local< v8::Context > context, bool forEntry, bool generatePreviewForTable, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *result) const
Private Attributes
String16 m_description
bool m_hasSubtype
String16 m_subtype
Additional Inherited Members
Detailed Description
Definition at line 1174 of file value-mirror.cc.
Constructor & Destructor Documentation
ObjectMirror() [1/2]
v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::ObjectMirror (v8::Local< v8::Object > value, const String16 & description) [inline]
Definition at line 1176 of file value-mirror.cc.
      : ValueMirrorBase(v8::Isolate::GetCurrent(), value),
        m_description(description),
        m_hasSubtype(false) {}
ObjectMirror() [2/2]
v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::ObjectMirror (v8::Local< v8::Object > value, const String16 & subtype, const String16 & description) [inline]
Definition at line 1180 of file value-mirror.cc.
      : ValueMirrorBase(v8::Isolate::GetCurrent(), value),
        m_description(description),
        m_hasSubtype(true),
        m_subtype(subtype) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 1251 of file value-mirror.cc.
                                                                     {
    v8::Local<v8::Object> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::Object>();
    maxDepth = std::min(kMaxProtocolDepth, maxDepth);
    bool isKnown;
    *result = duplicateTracker.LinkExistingOrCreate(value, &isKnown);
    if (isKnown) {
      return Response::Success();
    }
    // Check if embedder implemented custom serialization.
    std::unique_ptr<v8_inspector::DeepSerializationResult>
        embedderDeepSerializedResult = clientFor(context)->deepSerialize(
            value, maxDepth, additionalParameters);
    if (embedderDeepSerializedResult) {
      // Embedder-implemented serialization.
      if (!embedderDeepSerializedResult->isSuccess)
        return Response::ServerError(
            toString16(embedderDeepSerializedResult->errorMessage->string())
                .utf8());
      (*result)->setString(
          "type",
          toString16(
              embedderDeepSerializedResult->serializedValue->type->string()));
      v8::Local<v8::Value> v8Value;
      if (embedderDeepSerializedResult->serializedValue->value.ToLocal(
              &v8Value)) {
        // Embedder-implemented serialization has value.
        std::unique_ptr<protocol::Value> protocolValue;
        Response response = toProtocolValue(context, v8Value, &protocolValue);
        if (!response.IsSuccess()) return response;
        (*result)->setValue("value", std::move(protocolValue));
      }
      return Response::Success();
    }
    // No embedder-implemented serialization. Serialize as V8 Object.
    return V8DeepSerializer::serializeV8Value(value, context, maxDepth,
                                              additionalParameters,
                                              duplicateTracker, *(*result));
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::clientFor(), v8_inspector::V8InspectorClient::deepSerialize(), v8::Isolate::GetCurrent(), v8_inspector::kMaxProtocolDepth, v8_inspector::V8SerializationDuplicateTracker::LinkExistingOrCreate(), v8::base::internal::result, v8_inspector::V8DeepSerializer::serializeV8Value(), v8_inspector::toProtocolValue(), v8_inspector::toString16(), v8_inspector::String16::utf8(), and v8::internal::value.
buildEntryPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * result) const [inline], [override]
Definition at line 1229 of file value-mirror.cc.
                                                           {
    buildObjectPreviewInternal(context, true /* forEntry */,
                               false /* generatePreviewForTable */, nameLimit,
                               indexLimit, result);
  }
References v8::base::internal::result.
buildObjectPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreview (v8::Local< v8::Context > context, bool generatePreviewForTable, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * result) const [inline], [override]
Definition at line 1220 of file value-mirror.cc.
                                                           {
    buildObjectPreviewInternal(context, false /* forEntry */,
                               generatePreviewForTable, nameLimit, indexLimit,
                               result);
  }
References v8::base::internal::result.
buildObjectPreviewInternal()
void v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildObjectPreviewInternal (v8::Local< v8::Context > context, bool forEntry, bool generatePreviewForTable, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * result) const [inline], [private]
Definition at line 1300 of file value-mirror.cc.
                                                  {
    auto properties = std::make_unique<protocol::Array<PropertyPreview>>();
    std::unique_ptr<protocol::Array<EntryPreview>> entriesPreview;
    bool overflow = false;
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    while (value->IsProxy()) value = value.As<v8::Proxy>()->GetTarget();
    if (value->IsObject() && !value->IsProxy()) {
      v8::Local<v8::Object> objectForPreview = value.As<v8::Object>();
      std::vector<InternalPropertyMirror> internalProperties;
      getInternalPropertiesForPreview(context, objectForPreview, nameLimit,
                                      &overflow, &internalProperties);
      for (size_t i = 0; i < internalProperties.size(); ++i) {
        std::unique_ptr<PropertyPreview> propertyPreview;
        internalProperties[i].value->buildPropertyPreview(
            context, internalProperties[i].name, &propertyPreview);
        if (propertyPreview) {
          properties->emplace_back(std::move(propertyPreview));
        }
      }
      getPrivatePropertiesForPreview(context, objectForPreview, nameLimit,
                                     &overflow, properties.get());
      std::vector<PropertyMirror> mirrors;
      if (getPropertiesForPreview(context, objectForPreview, nameLimit,
                                  indexLimit, &overflow, &mirrors)) {
        for (size_t i = 0; i < mirrors.size(); ++i) {
          std::unique_ptr<PropertyPreview> preview;
          std::unique_ptr<ObjectPreview> valuePreview;
          if (mirrors[i].value) {
            mirrors[i].value->buildPropertyPreview(context, mirrors[i].name,
                                                   &preview);
            if (generatePreviewForTable) {
              int tableLimit = 1000;
              mirrors[i].value->buildObjectPreview(context, false, &tableLimit,
                                                   &tableLimit, &valuePreview);
            }
          } else {
            preview = PropertyPreview::create()
                          .setName(mirrors[i].name)
                          .setType(PropertyPreview::TypeEnum::Accessor)
                          .build();
          }
          if (valuePreview) {
            preview->setValuePreview(std::move(valuePreview));
          }
          properties->emplace_back(std::move(preview));
        }
      }
      std::vector<EntryMirror> entries;
      if (EntryMirror::getEntries(context, objectForPreview, 5, &overflow,
                                  &entries)) {
        if (forEntry) {
          overflow = true;
        } else {
          entriesPreview = std::make_unique<protocol::Array<EntryPreview>>();
          for (const auto& entry : entries) {
            std::unique_ptr<ObjectPreview> valuePreview;
            entry.value->buildEntryPreview(context, nameLimit, indexLimit,
                                           &valuePreview);
            if (!valuePreview) continue;
            std::unique_ptr<ObjectPreview> keyPreview;
            if (entry.key) {
              entry.key->buildEntryPreview(context, nameLimit, indexLimit,
                                           &keyPreview);
              if (!keyPreview) continue;
            }
            std::unique_ptr<EntryPreview> entryPreview =
                EntryPreview::create()
                    .setValue(std::move(valuePreview))
                    .build();
            if (keyPreview) entryPreview->setKey(std::move(keyPreview));
            entriesPreview->emplace_back(std::move(entryPreview));
          }
        }
      }
    }
    *result = ObjectPreview::create()
                  .setType(RemoteObject::TypeEnum::Object)
                  .setDescription(m_description)
                  .setOverflow(overflow)
                  .setProperties(std::move(properties))
                  .build();
    if (m_hasSubtype) (*result)->setSubtype(m_subtype);
    if (entriesPreview) (*result)->setEntries(std::move(entriesPreview));
  }
References v8::Isolate::GetCurrent(), v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::getPrivatePropertiesForPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, name, v8::internal::compiler::Object, v8::internal::overflow, v8::base::internal::result, and v8::internal::value.
buildPropertyPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< PropertyPreview > * result) const [inline], [override]
Definition at line 1237 of file value-mirror.cc.
                                                             {
    *result = PropertyPreview::create()
                  .setName(name)
                  .setType(RemoteObject::TypeEnum::Object)
                  .setValue(abbreviateString(
                      m_description,
                      m_subtype == RemoteObject::SubtypeEnum::Regexp ? kMiddle
                                                                     : kEnd))
                  .build();
    if (m_hasSubtype) (*result)->setSubtype(m_subtype);
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8_inspector::anonymous_namespace{value-mirror.cc}::kMiddle, name, v8::internal::compiler::Object, and v8::base::internal::result.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 1187 of file value-mirror.cc.
                                                          {
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::Local<v8::Object> value = v8Value(isolate).As<v8::Object>();
    if (wrapOptions.mode == WrapMode::kJson) {
      std::unique_ptr<protocol::Value> protocolValue;
      Response response = toProtocolValue(context, value, &protocolValue);
      if (!response.IsSuccess()) return response;
      *result = RemoteObject::create()
                    .setType(RemoteObject::TypeEnum::Object)
                    .setValue(std::move(protocolValue))
                    .build();
    } else {
      *result = RemoteObject::create()
                    .setType(RemoteObject::TypeEnum::Object)
                    .setClassName(
                        toProtocolString(isolate, value->GetConstructorName()))
                    .setDescription(m_description)
                    .build();
      if (m_hasSubtype) (*result)->setSubtype(m_subtype);
      if (wrapOptions.mode == WrapMode::kPreview) {
        std::unique_ptr<ObjectPreview> previewValue;
        int nameLimit = 5;
        int indexLimit = 100;
        buildObjectPreview(context, false, &nameLimit, &indexLimit,
                           &previewValue);
        (*result)->setPreview(std::move(previewValue));
      }
    }
    return Response::Success();
  }
References v8::Isolate::GetCurrent(), v8_inspector::kJson, v8_inspector::kPreview, v8_inspector::WrapOptions::mode, v8::internal::compiler::Object, v8::base::internal::result, v8_inspector::toProtocolString(), v8_inspector::toProtocolValue(), and v8::internal::value.
Member Data Documentation
m_description
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::m_description [private]
Definition at line 1393 of file value-mirror.cc.
m_hasSubtype
bool v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::m_hasSubtype [private]
Definition at line 1394 of file value-mirror.cc.
m_subtype
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::m_subtype [private]
Definition at line 1395 of file value-mirror.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc