v8::internal::MemoryChunkLayout Class Reference
#include <memory-chunk-layout.h>
Static Public Member Functions
static constexpr intptr_t ObjectStartOffsetInCodePage ()
static constexpr size_t AllocatableMemoryInCodePage ()
static constexpr size_t ObjectStartOffsetInDataPage ()
static constexpr size_t AllocatableMemoryInDataPage ()
static constexpr size_t ObjectStartOffsetInMemoryChunk (AllocationSpace space)
static constexpr size_t AllocatableMemoryInMemoryChunk (AllocationSpace space)
static constexpr int MaxRegularCodeObjectSize ()
Detailed Description
Definition at line 14 of file memory-chunk-layout.h.
Member Function Documentation
AllocatableMemoryInCodePage()
static constexpr size_t v8::internal::MemoryChunkLayout::AllocatableMemoryInCodePage () [inline], [static], [constexpr]
Definition at line 26 of file memory-chunk-layout.h.
                                                        {
    return kRegularPageSize - ObjectStartOffsetInCodePage();
  }
References kRegularPageSize.
AllocatableMemoryInDataPage()
static constexpr size_t v8::internal::MemoryChunkLayout::AllocatableMemoryInDataPage () [inline], [static], [constexpr]
Definition at line 35 of file memory-chunk-layout.h.
                                                        {
    constexpr size_t kAllocatableMemoryInDataPage =
        kRegularPageSize - ObjectStartOffsetInDataPage();
    static_assert(kMaxRegularHeapObjectSize <= kAllocatableMemoryInDataPage);
    return kAllocatableMemoryInDataPage;
  }
References v8::internal::kMaxRegularHeapObjectSize, and kRegularPageSize.
Referenced by v8::internal::SemiSpaceNewSpace::Capacity(), v8::internal::SemiSpaceNewSpace::CurrentCapacitySafe(), v8::internal::Scavenger::EvacuateObjectDefault(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::NewSpacePageEvacuationThreshold(), and v8::internal::SemiSpaceNewSpace::Size().
AllocatableMemoryInMemoryChunk()
static constexpr size_t v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk (AllocationSpace space) [inline], [static], [constexpr]
Definition at line 51 of file memory-chunk-layout.h.
                             {
    DCHECK_NE(space, CODE_LO_SPACE);
    if (space == CODE_SPACE) {
      return AllocatableMemoryInCodePage();
    }
    // Read-only pages use the same layout as regular pages.
    return AllocatableMemoryInDataPage();
  }
References v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, DCHECK_NE, and space.
Referenced by v8::internal::MemoryAllocator::AllocatePage(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::PagedSpaceBase::PagedSpaceBase(), v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlyAreaSize(), v8::internal::OldSpace::RelinkQuarantinedPageFreeList(), and v8::internal::PagedSpaceBase::TryExpand().
MaxRegularCodeObjectSize()
static constexpr int v8::internal::MemoryChunkLayout::MaxRegularCodeObjectSize () [inline], [static], [constexpr]
Definition at line 61 of file memory-chunk-layout.h.
                                                  {
    constexpr int kMaxRegularCodeObjectSize = static_cast<int>(
        RoundDown(AllocatableMemoryInCodePage() / 2, kTaggedSize));
    static_assert(kMaxRegularCodeObjectSize <= kMaxRegularHeapObjectSize);
    return kMaxRegularCodeObjectSize;
  }
References v8::internal::kMaxRegularHeapObjectSize, v8::internal::kTaggedSize, and RoundDown().
Referenced by v8::internal::Heap::Heap(), and v8::internal::Heap::MaxRegularHeapObjectSize().
ObjectStartOffsetInCodePage()
static constexpr intptr_t v8::internal::MemoryChunkLayout::ObjectStartOffsetInCodePage () [inline], [static], [constexpr]
Definition at line 18 of file memory-chunk-layout.h.
                                                          {
    // The instruction stream data (so after the header) should be aligned to
    // kCodeAlignment.
    return RoundUp(sizeof(MemoryChunk) + InstructionStream::kHeaderSize,
                   kCodeAlignment) -
           InstructionStream::kHeaderSize;
  }
References v8::internal::kCodeAlignment, v8::internal::TrustedObject::kHeaderSize, and RoundUp().
ObjectStartOffsetInDataPage()
static constexpr size_t v8::internal::MemoryChunkLayout::ObjectStartOffsetInDataPage () [inline], [static], [constexpr]
Definition at line 30 of file memory-chunk-layout.h.
                                                        {
    return RoundUp(sizeof(MemoryChunk),
                   ALIGN_TO_ALLOCATION_ALIGNMENT(kDoubleSize));
  }
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::kDoubleSize, and RoundUp().
Referenced by v8::internal::Scavenger::HandleLargeObject(), and v8::internal::StressConcurrentAllocationTask::RunInternal().
ObjectStartOffsetInMemoryChunk()
static constexpr size_t v8::internal::MemoryChunkLayout::ObjectStartOffsetInMemoryChunk (AllocationSpace space) [inline], [static], [constexpr]
Definition at line 42 of file memory-chunk-layout.h.
                             {
    if (IsAnyCodeSpace(space)) {
      return ObjectStartOffsetInCodePage();
    }
    // Read-only pages use the same layout as regular pages.
    return ObjectStartOffsetInDataPage();
  }
References v8::internal::IsAnyCodeSpace(), and space.
Referenced by v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::MemoryAllocator::ComputeChunkSize(), v8::internal::ReadOnlyPageMetadata::GetAreaStart(), and v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/memory-chunk-layout.h