v8::internal::ProducedPreparseData Class Reference
#include <preparse-data.h>
Public Member Functions
virtual Handle< PreparseData > Serialize (Isolate *isolate)=0
virtual Handle< PreparseData > Serialize (LocalIsolate *isolate)=0
virtual ZonePreparseData * Serialize (Zone *zone)=0
Static Public Member Functions
static ProducedPreparseData * For (PreparseDataBuilder *builder, Zone *zone)
static ProducedPreparseData * For (Handle< PreparseData > data, Zone *zone)
static ProducedPreparseData * For (ZonePreparseData *data, Zone *zone)
Detailed Description
Definition at line 248 of file preparse-data.h.
Member Function Documentation
For() [1/3]
ProducedPreparseData * v8::internal::ProducedPreparseData::For (Handle< PreparseData > data, Zone * zone) [static]
Definition at line 574 of file preparse-data.cc.
                                                            {
  return zone->New<OnHeapProducedPreparseData>(data);
}
References v8::internal::Zone::New().
For() [2/3]
ProducedPreparseData * v8::internal::ProducedPreparseData::For (PreparseDataBuilder * builder, Zone * zone) [static]
Definition at line 569 of file preparse-data.cc.
                                                            {
  return zone->New<BuilderProducedPreparseData>(builder);
}
References v8::internal::Zone::New().
Referenced by v8::internal::OnHeapConsumedPreparseData::GetChildData(), v8::internal::ZoneConsumedPreparseData::GetChildData(), and v8::internal::PreParser::PreParseFunction().
For() [3/3]
ProducedPreparseData * v8::internal::ProducedPreparseData::For (ZonePreparseData * data, Zone * zone) [static]
Definition at line 579 of file preparse-data.cc.
                                                            {
  return zone->New<ZoneProducedPreparseData>(data);
}
References v8::internal::Zone::New().
Serialize() [1/3]
virtual Handle<PreparseData> v8::internal::ProducedPreparseData::Serialize (Isolate * isolate) [pure virtual]
Implemented in v8::internal::ZoneProducedPreparseData, v8::internal::OnHeapProducedPreparseData, and v8::internal::BuilderProducedPreparseData.
Referenced by v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData(), and v8::internal::Compiler::GetSharedFunctionInfo().
Serialize() [2/3]
virtual Handle<PreparseData> v8::internal::ProducedPreparseData::Serialize (LocalIsolate * isolate) [pure virtual]
Implemented in v8::internal::ZoneProducedPreparseData, v8::internal::OnHeapProducedPreparseData, and v8::internal::BuilderProducedPreparseData.
Serialize() [3/3]
virtual ZonePreparseData* v8::internal::ProducedPreparseData::Serialize (Zone * zone) [pure virtual]
Implemented in v8::internal::ZoneProducedPreparseData, v8::internal::OnHeapProducedPreparseData, and v8::internal::BuilderProducedPreparseData.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc