v8::internal::JSTypedArray Class Reference
#include <js-array-buffer.h>
Classes
class BodyDescriptor
Public Member Functions
ExternalArrayType type ()
V8_EXPORT_PRIVATE size_t element_size () const
V8_EXPORT_PRIVATE Handle< JSArrayBuffer > GetBuffer (Isolate *isolate)
void * DataPtr ()
void SetOffHeapDataPtr (Isolate *isolate, void *base, Address offset)
bool is_on_heap () const
bool is_on_heap (AcquireLoadTag tag) const
size_t GetVariableByteLengthOrOutOfBounds (bool &out_of_bounds) const
size_t GetVariableLengthOrOutOfBounds (bool &out_of_bounds) const
size_t GetLengthOrOutOfBounds (bool &out_of_bounds) const
size_t GetLength () const
size_t GetByteLength () const
bool IsOutOfBounds () const
uint32_t GetExternalBackingStoreRefForDeserialization () const
void SetExternalBackingStoreRefForSerialization (uint32_t ref)
void RemoveExternalPointerCompensationForSerialization (Isolate *isolate)
void AddExternalPointerCompensationForDeserialization (Isolate *isolate)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Isolate *isolate, DirectHandle< JSTypedArray > o, DirectHandle< Object > key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static void ForFixedTypedArray (ExternalArrayType array_type, size_t *element_size, ElementsKind *element_kind)
static size_t LengthTrackingGsabBackedTypedArrayLength (Isolate *isolate, Address raw_array)
static Address ExternalPointerCompensationForOnHeapArray (PtrComprCageBase cage_base)
static MaybeDirectHandle< JSTypedArray > Validate (Isolate *isolate, DirectHandle< Object > receiver, const char *method_name)
Static Public Attributes
static constexpr size_t kMaxByteLength = JSArrayBuffer::kMaxByteLength
static constexpr bool kOffHeapDataPtrEqualsExternalPointer = true
static constexpr int kSizeWithEmbedderFields
static constexpr bool kContainsEmbedderFields
static constexpr size_t kMaxSizeInHeap = 64
Private Member Functions
void set_external_pointer (Isolate *isolate, Address value)
Friends
template<typename IsolateT >
class Deserializer
class Factory
Detailed Description
Definition at line 329 of file js-array-buffer.h.
Member Function Documentation
AddExternalPointerCompensationForDeserialization()
void v8::internal::JSTypedArray::AddExternalPointerCompensationForDeserialization (Isolate * isolate) [inline]
Definition at line 329 of file js-array-buffer-inl.h.
                      {
  DCHECK(is_on_heap());
  Address pointer = ReadField<Address>(kExternalPointerOffset) +
                    ExternalPointerCompensationForOnHeapArray(isolate);
  set_external_pointer(isolate, pointer);
}
References v8::internal::DCHECK(), ExternalPointerCompensationForOnHeapArray(), is_on_heap(), and set_external_pointer().
DataPtr()
void * v8::internal::JSTypedArray::DataPtr () [inline]
Definition at line 337 of file js-array-buffer-inl.h.
                            {
  // Zero-extend Tagged_t to Address according to current compression scheme
  // so that the addition with |external_pointer| (which already contains
  // compensated offset value) will decompress the tagged value.
  // See JSTypedArray::ExternalPointerCompensationForOnHeapArray() for details.
  static_assert(kOffHeapDataPtrEqualsExternalPointer);
  return reinterpret_cast<void*>(external_pointer() +
                                 static_cast<Tagged_t>(base_pointer().ptr()));
}
References kOffHeapDataPtrEqualsExternalPointer.
Referenced by SetOffHeapDataPtr().
DefineOwnProperty()
Maybe< bool > v8::internal::JSTypedArray::DefineOwnProperty (Isolate * isolate, DirectHandle< JSTypedArray > o, DirectHandle< Object > key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 340 of file js-array-buffer.cc.
                                                                             {
  DCHECK(IsName(*key) || IsNumber(*key));
  // 1. If Type(P) is String, then
  PropertyKey lookup_key(isolate, key);
  if (lookup_key.is_element() || IsSmi(*key) || IsString(*key)) {
    // 1a. Let numericIndex be ! CanonicalNumericIndexString(P)
    // 1b. If numericIndex is not undefined, then
    bool is_minus_zero = false;
    if (IsSmi(*key) || // Smi keys are definitely canonical
        CanonicalNumericIndexString(isolate, lookup_key, &is_minus_zero)) {
      // 1b i. If IsValidIntegerIndex(O, numericIndex) is false, return false.
      // IsValidIntegerIndex:
      size_t index = lookup_key.index();
      bool out_of_bounds = false;
      size_t length = o->GetLengthOrOutOfBounds(out_of_bounds);
      if (o->WasDetached() || out_of_bounds || index >= length) {
        RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                       NewTypeError(MessageTemplate::kInvalidTypedArrayIndex));
      }
      if (!lookup_key.is_element() || is_minus_zero) {
        RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                       NewTypeError(MessageTemplate::kInvalidTypedArrayIndex));
      }
      // 1b ii. If Desc has a [[Configurable]] field and if
      // Desc.[[Configurable]] is false, return false.
      // 1b iii. If Desc has an [[Enumerable]] field and if Desc.[[Enumerable]]
      // is false, return false.
      // 1b iv. If IsAccessorDescriptor(Desc) is true, return false.
      // 1b v. If Desc has a [[Writable]] field and if Desc.[[Writable]] is
      // false, return false.
      if (PropertyDescriptor::IsAccessorDescriptor(desc)) {
        RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                       NewTypeError(MessageTemplate::kRedefineDisallowed, key));
      }
      if ((desc->has_configurable() && !desc->configurable()) ||
          (desc->has_enumerable() && !desc->enumerable()) ||
          (desc->has_writable() && !desc->writable())) {
        RETURN_FAILURE(isolate, GetShouldThrow(isolate, should_throw),
                       NewTypeError(MessageTemplate::kRedefineDisallowed, key));
      }
      // 1b vi. If Desc has a [[Value]] field, perform
      // ? IntegerIndexedElementSet(O, numericIndex, Desc.[[Value]]).
      if (desc->has_value()) {
        if (!desc->has_configurable()) desc->set_configurable(true);
        if (!desc->has_enumerable()) desc->set_enumerable(true);
        if (!desc->has_writable()) desc->set_writable(true);
        DirectHandle<Object> value = desc->value();
        LookupIterator it(isolate, o, index, LookupIterator::OWN);
        RETURN_ON_EXCEPTION_VALUE(
            isolate,
            DefineOwnPropertyIgnoreAttributes(&it, value, desc->ToAttributes()),
            Nothing<bool>());
      }
      // 1b vii. Return true.
      return Just(true);
    }
  }
  // 4. Return ! OrdinaryDefineOwnProperty(O, P, Desc).
  return OrdinaryDefineOwnProperty(isolate, o, lookup_key, desc, should_throw);
}
References v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString(), v8::internal::PropertyDescriptor::configurable(), v8::internal::DCHECK(), v8::internal::PropertyDescriptor::enumerable(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_configurable(), v8::internal::PropertyDescriptor::has_enumerable(), v8::internal::PropertyDescriptor::has_value(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::PropertyKey::index, v8::internal::index, v8::internal::PropertyKey::is_element(), v8::internal::compiler::turboshaft::detail::is_minus_zero(), v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::Just(), v8::internal::key, v8::internal::length, v8::internal::LookupIterator::OWN, RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::PropertyDescriptor::ToAttributes(), v8::internal::value, v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by v8::internal::JSReceiver::DefineOwnProperty().
element_size()
size_t v8::internal::JSTypedArray::element_size () const
Definition at line 425 of file js-array-buffer.cc.
                                        {
  switch (map()->elements_kind()) {
#define ELEMENTS_KIND_TO_ELEMENT_SIZE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: \
    return sizeof(ctype);
    TYPED_ARRAYS(ELEMENTS_KIND_TO_ELEMENT_SIZE)
    RAB_GSAB_TYPED_ARRAYS(ELEMENTS_KIND_TO_ELEMENT_SIZE)
#undef ELEMENTS_KIND_TO_ELEMENT_SIZE
    default:
      UNREACHABLE();
  }
}
References ELEMENTS_KIND_TO_ELEMENT_SIZE, RAB_GSAB_TYPED_ARRAYS, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
Referenced by GetLengthOrOutOfBounds(), GetVariableByteLengthOrOutOfBounds(), and GetVariableLengthOrOutOfBounds().
ExternalPointerCompensationForOnHeapArray()
Address v8::internal::JSTypedArray::ExternalPointerCompensationForOnHeapArray (PtrComprCageBase cage_base) [inline], [static]
Definition at line 302 of file js-array-buffer-inl.h.
                                {
#ifdef V8_COMPRESS_POINTERS
  return cage_base.address();
#else
  return 0;
#endif
}
Referenced by AddExternalPointerCompensationForDeserialization(), RemoveExternalPointerCompensationForSerialization(), and v8::internal::TypedArrayBuiltinsAssembler::SetJSTypedArrayOnHeapDataPtr().
ForFixedTypedArray()
void v8::internal::JSTypedArray::ForFixedTypedArray (ExternalArrayType array_type, size_t * element_size, ElementsKind * element_kind) [inline], [static]
Definition at line 278 of file js-array-buffer-inl.h.
                                                                         {
  switch (array_type) {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case kExternal##Type##Array: \
    *element_size = sizeof(ctype); \
    *element_kind = TYPE##_ELEMENTS; \
    return;
    TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
  }
  UNREACHABLE();
}
References TYPED_ARRAY_CASE, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Factory::NewJSTypedArray().
GetBuffer()
Handle< JSArrayBuffer > v8::internal::JSTypedArray::GetBuffer (Isolate * isolate)
Definition at line 297 of file js-array-buffer.cc.
                                                              {
  DirectHandle<JSTypedArray> self(*this, isolate);
  DCHECK(IsTypedArrayOrRabGsabTypedArrayElementsKind(self->GetElementsKind()));
  Handle<JSArrayBuffer> array_buffer(Cast<JSArrayBuffer>(self->buffer()),
                                     isolate);
  if (!is_on_heap()) {
    // Already is off heap, so return the existing buffer.
    return array_buffer;
  }
  DCHECK(!array_buffer->is_resizable_by_js());
  // The existing array buffer should be empty.
  DCHECK(array_buffer->IsEmpty());
  // Allocate a new backing store and attach it to the existing array buffer.
  size_t byte_length = self->byte_length();
  auto backing_store =
      BackingStore::Allocate(isolate, byte_length, SharedFlag::kNotShared,
                             InitializedFlag::kUninitialized);
  if (!backing_store) {
    isolate->heap()->FatalProcessOutOfMemory("JSTypedArray::GetBuffer");
  }
  // Copy the elements into the backing store of the array buffer.
  if (byte_length > 0) {
    memcpy(backing_store->buffer_start(), self->DataPtr(), byte_length);
  }
  // Attach the backing store to the array buffer.
  array_buffer->Setup(SharedFlag::kNotShared, ResizableFlag::kNotResizable,
                      std::move(backing_store), isolate);
  // Clear the elements of the typed array.
  self->set_elements(ReadOnlyRoots(isolate).empty_byte_array());
  self->SetOffHeapDataPtr(isolate, array_buffer->backing_store(), 0);
  DCHECK(!self->is_on_heap());
  return array_buffer;
}
References v8::internal::BackingStore::Allocate(), v8::internal::DCHECK(), v8::internal::Heap::FatalProcessOutOfMemory(), v8::internal::Isolate::heap(), is_on_heap(), v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), v8::internal::kNotResizable, v8::internal::kNotShared, and v8::internal::kUninitialized.
GetByteLength()
size_t v8::internal::JSTypedArray::GetByteLength () const [inline]
Definition at line 262 of file js-array-buffer-inl.h.
                                         {
  if (WasDetached()) return 0;
  if (IsVariableLength()) {
    bool out_of_bounds = false;
    return GetVariableByteLengthOrOutOfBounds(out_of_bounds);
  }
  return byte_length();
}
References GetVariableByteLengthOrOutOfBounds().
GetExternalBackingStoreRefForDeserialization()
uint32_t v8::internal::JSTypedArray::GetExternalBackingStoreRefForDeserialization () const [inline]
Definition at line 311 of file js-array-buffer-inl.h.
                                                                          {
  DCHECK(!is_on_heap());
  return static_cast<uint32_t>(ReadField<Address>(kExternalPointerOffset));
}
References v8::internal::DCHECK(), and is_on_heap().
GetLength()
size_t v8::internal::JSTypedArray::GetLength () const [inline]
Definition at line 257 of file js-array-buffer-inl.h.
                                     {
  bool out_of_bounds = false;
  return GetLengthOrOutOfBounds(out_of_bounds);
}
References GetLengthOrOutOfBounds().
GetLengthOrOutOfBounds()
size_t v8::internal::JSTypedArray::GetLengthOrOutOfBounds (bool & out_of_bounds) const [inline]
Definition at line 248 of file js-array-buffer-inl.h.
                                                                     {
  DCHECK(!out_of_bounds);
  if (WasDetached()) return 0;
  if (IsVariableLength()) {
    return GetVariableLengthOrOutOfBounds(out_of_bounds);
  }
  return byte_length() / element_size();
}
References v8::internal::DCHECK(), element_size(), and GetVariableLengthOrOutOfBounds().
Referenced by GetLength(), and IsOutOfBounds().
GetVariableByteLengthOrOutOfBounds()
size_t v8::internal::JSTypedArray::GetVariableByteLengthOrOutOfBounds (bool & out_of_bounds) const
Definition at line 458 of file js-array-buffer.cc.
                               {
  DCHECK(!WasDetached());
  size_t own_byte_offset = byte_offset();
  if (is_length_tracking()) {
    size_t own_element_size = element_size();
    if (is_backed_by_rab()) {
      size_t buffer_byte_length = buffer()->byte_length();
      if (own_byte_offset > buffer_byte_length) {
        out_of_bounds = true;
        return 0;
      }
      // Round down to the nearest multiple of element size.
      return RoundDown(buffer_byte_length - own_byte_offset, own_element_size);
    }
    // GSAB-backed TypedArrays can't be out of bounds.
    size_t buffer_byte_length =
        buffer()->GetBackingStore()->byte_length(std::memory_order_seq_cst);
    SBXCHECK(own_byte_offset <= buffer_byte_length);
    // Round down to the nearest multiple of element size.
    return RoundDown(buffer_byte_length - own_byte_offset, own_element_size);
  }
  DCHECK(is_backed_by_rab());
  size_t own_byte_length = byte_length();
  size_t buffer_byte_length = buffer()->byte_length();
  if (own_byte_length > buffer_byte_length ||
      own_byte_offset > buffer_byte_length - own_byte_length) {
    out_of_bounds = true;
    return 0;
  }
  return own_byte_length;
}
References v8::internal::DCHECK(), element_size(), v8::internal::is_backed_by_rab, RoundDown(), and SBXCHECK.
Referenced by GetByteLength(), and GetVariableLengthOrOutOfBounds().
GetVariableLengthOrOutOfBounds()
size_t v8::internal::JSTypedArray::GetVariableLengthOrOutOfBounds (bool & out_of_bounds) const
Definition at line 491 of file js-array-buffer.cc.
                                                                             {
  return GetVariableByteLengthOrOutOfBounds(out_of_bounds) / element_size();
}
References element_size(), and GetVariableByteLengthOrOutOfBounds().
Referenced by GetLengthOrOutOfBounds().
is_on_heap() [1/2]
bool v8::internal::JSTypedArray::is_on_heap () const [inline]
Definition at line 361 of file js-array-buffer-inl.h.
                                    {
  // Keep synced with `is_on_heap(AcquireLoadTag)`.
  DisallowGarbageCollection no_gc;
  return base_pointer() != Smi::zero();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::zero().
Referenced by AddExternalPointerCompensationForDeserialization(), GetBuffer(), GetExternalBackingStoreRefForDeserialization(), RemoveExternalPointerCompensationForSerialization(), and SetExternalBackingStoreRefForSerialization().
is_on_heap() [2/2]
bool v8::internal::JSTypedArray::is_on_heap (AcquireLoadTag tag) const [inline]
Definition at line 367 of file js-array-buffer-inl.h.
                                                      {
  // Keep synced with `is_on_heap()`.
  // Note: For Turbofan concurrency requirements, it's important that this
  // function reads only `base_pointer`.
  DisallowGarbageCollection no_gc;
  return base_pointer(tag) != Smi::zero();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::zero().
IsOutOfBounds()
bool v8::internal::JSTypedArray::IsOutOfBounds () const [inline]
Definition at line 271 of file js-array-buffer-inl.h.
                                       {
  bool out_of_bounds = false;
  GetLengthOrOutOfBounds(out_of_bounds);
  return out_of_bounds;
}
References GetLengthOrOutOfBounds().
LengthTrackingGsabBackedTypedArrayLength()
size_t v8::internal::JSTypedArray::LengthTrackingGsabBackedTypedArrayLength (Isolate * isolate, Address raw_array) [static]
Definition at line 440 of file js-array-buffer.cc.
                                         {
  // TODO(v8:11111): Cache the last seen length in JSArrayBuffer and use it
  // in bounds checks to minimize the need for calling this function.
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate);
  Tagged<JSTypedArray> array = Cast<JSTypedArray>(Tagged<Object>(raw_array));
  CHECK(array->is_length_tracking());
  Tagged<JSArrayBuffer> buffer = array->buffer();
  CHECK(buffer->is_resizable_by_js());
  CHECK(buffer->is_shared());
  size_t backing_byte_length =
      buffer->GetBackingStore()->byte_length(std::memory_order_seq_cst);
  CHECK_GE(backing_byte_length, array->byte_offset());
  auto element_byte_size = ElementsKindToByteSize(array->GetElementsKind());
  return (backing_byte_length - array->byte_offset()) / element_byte_size;
}
References CHECK, CHECK_GE, v8::internal::ElementsKindToByteSize(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
RemoveExternalPointerCompensationForSerialization()
void v8::internal::JSTypedArray::RemoveExternalPointerCompensationForSerialization (Isolate * isolate) [inline]
Definition at line 321 of file js-array-buffer-inl.h.
                      {
  DCHECK(is_on_heap());
  Address offset =
      external_pointer() - ExternalPointerCompensationForOnHeapArray(isolate);
  WriteField<Address>(kExternalPointerOffset, offset);
}
References v8::internal::DCHECK(), ExternalPointerCompensationForOnHeapArray(), and is_on_heap().
set_external_pointer()
void v8::internal::JSTypedArray::set_external_pointer (Isolate * isolate, Address value) [inline], [private]
Definition at line 298 of file js-array-buffer-inl.h.
                                                                       {
  WriteSandboxedPointerField(kExternalPointerOffset, isolate, value);
}
References v8::internal::value, and v8::internal::WriteSandboxedPointerField().
Referenced by AddExternalPointerCompensationForDeserialization(), and SetOffHeapDataPtr().
SetExternalBackingStoreRefForSerialization()
void v8::internal::JSTypedArray::SetExternalBackingStoreRefForSerialization (uint32_t ref) [inline]
Definition at line 316 of file js-array-buffer-inl.h.
                                                                          {
  DCHECK(!is_on_heap());
  WriteField<Address>(kExternalPointerOffset, static_cast<Address>(ref));
}
References v8::internal::DCHECK(), and is_on_heap().
SetOffHeapDataPtr()
void v8::internal::JSTypedArray::SetOffHeapDataPtr (Isolate * isolate, void * base, Address offset) [inline]
Definition at line 347 of file js-array-buffer-inl.h.
                                                     {
  Address address = reinterpret_cast<Address>(base) + offset;
  set_external_pointer(isolate, address);
  // This is the only spot in which the `base_pointer` field can be mutated
  // after object initialization. Note this can happen at most once, when
  // `JSTypedArray::GetBuffer` transitions from an on- to off-heap
  // representation.
  // To play well with Turbofan concurrency requirements, `base_pointer` is set
  // with a release store, after external_pointer has been set.
  set_base_pointer(Smi::zero(), kReleaseStore, SKIP_WRITE_BARRIER);
  DCHECK_EQ(address, reinterpret_cast<Address>(DataPtr()));
}
References DataPtr(), DCHECK_EQ, v8::kReleaseStore, set_external_pointer(), v8::internal::SKIP_WRITE_BARRIER, and v8::internal::Smi::zero().
type()
ExternalArrayType v8::internal::JSTypedArray::type ()
Definition at line 410 of file js-array-buffer.cc.
                                     {
  switch (map()->elements_kind()) {
#define ELEMENTS_KIND_TO_ARRAY_TYPE(Type, type, TYPE, ctype) \
  case TYPE##_ELEMENTS: \
    return kExternal##Type##Array;
    TYPED_ARRAYS(ELEMENTS_KIND_TO_ARRAY_TYPE)
    RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE(ELEMENTS_KIND_TO_ARRAY_TYPE)
#undef ELEMENTS_KIND_TO_ARRAY_TYPE
    default:
      UNREACHABLE();
  }
}
References ELEMENTS_KIND_TO_ARRAY_TYPE, RAB_GSAB_TYPED_ARRAYS_WITH_TYPED_ARRAY_TYPE, TYPED_ARRAYS, and v8::internal::UNREACHABLE().
Validate()
MaybeDirectHandle< JSTypedArray > v8::internal::JSTypedArray::Validate (Isolate * isolate, DirectHandle< Object > receiver, const char * method_name) [inline], [static]
Definition at line 376 of file js-array-buffer-inl.h.
                                                                              {
  if (V8_UNLIKELY(!IsJSTypedArray(*receiver))) {
    const MessageTemplate message = MessageTemplate::kNotTypedArray;
    THROW_NEW_ERROR(isolate, NewTypeError(message));
  }
  DirectHandle<JSTypedArray> array = Cast<JSTypedArray>(receiver);
  if (V8_UNLIKELY(array->WasDetached())) {
    const MessageTemplate message = MessageTemplate::kDetachedOperation;
    DirectHandle<String> operation =
        isolate->factory()->NewStringFromAsciiChecked(method_name);
    THROW_NEW_ERROR(isolate, NewTypeError(message, operation));
  }
  if (V8_UNLIKELY(array->IsVariableLength() && array->IsOutOfBounds())) {
    const MessageTemplate message = MessageTemplate::kDetachedOperation;
    DirectHandle<String> operation =
        isolate->factory()->NewStringFromAsciiChecked(method_name);
    THROW_NEW_ERROR(isolate, NewTypeError(message, operation));
  }
  // spec describes to return `buffer`, but it may disrupt current
  // implementations, and it's much useful to return array for now.
  return array;
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), THROW_NEW_ERROR, and V8_UNLIKELY.
Referenced by v8::internal::BUILTIN().
Friends And Related Function Documentation
Deserializer
template<typename IsolateT >
friend class Deserializer [friend]
Definition at line 435 of file js-array-buffer.h.
Factory
friend class Factory [friend]
Definition at line 436 of file js-array-buffer.h.
Member Data Documentation
kContainsEmbedderFields
constexpr bool v8::internal::JSTypedArray::kContainsEmbedderFields [static], [constexpr]
Initial value:
=
      v8::ArrayBufferView::kEmbedderFieldCount > 0
Definition at line 422 of file js-array-buffer.h.
Referenced by v8::internal::JSTypedArray::BodyDescriptor::IterateBody().
kMaxByteLength
constexpr size_t v8::internal::JSTypedArray::kMaxByteLength = JSArrayBuffer::kMaxByteLength [static], [constexpr]
Definition at line 332 of file js-array-buffer.h.
Referenced by v8::internal::Runtime::GetInternalProperties(), v8::internal::Factory::NewJSTypedArray(), and v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::TryAllocateBackingStore().
kMaxSizeInHeap
constexpr size_t v8::internal::JSTypedArray::kMaxSizeInHeap = 64 [static], [constexpr]
Definition at line 430 of file js-array-buffer.h.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccessForTypedArrayOrRabGsabTypedArray(), and v8::internal::maglev::MaglevAssembler::BuildTypedArrayDataPointer().
kOffHeapDataPtrEqualsExternalPointer
constexpr bool v8::internal::JSTypedArray::kOffHeapDataPtrEqualsExternalPointer = true [static], [constexpr]
Definition at line 350 of file js-array-buffer.h.
Referenced by v8::internal::compiler::JSTypedArrayRef::data_ptr(), and DataPtr().
kSizeWithEmbedderFields
constexpr int v8::internal::JSTypedArray::kSizeWithEmbedderFields [static], [constexpr]
Initial value:
=
      kHeaderSize +
      v8::ArrayBufferView::kEmbedderFieldCount * kEmbedderDataSlotSize
Definition at line 419 of file js-array-buffer.h.
Referenced by v8::internal::Genesis::InstallTypedArray(), and v8::internal::TypedArrayBuiltinsAssembler::SetupTypedArrayEmbedderFields().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-array-buffer.h
/mnt/V8SourceCode/src/objects/js-array-buffer-inl.h
/mnt/V8SourceCode/src/objects/js-array-buffer.cc