v8::internal::compiler::turboshaft::DemandedElementAnalysis Class Reference
#include <wasm-shuffle-reducer.h>
Public Types
using LaneBitSet = std::bitset< 16 >
using DemandedElementMap = ZoneVector< std::pair< const Operation *, LaneBitSet > >
Public Member Functions
DemandedElementAnalysis (Zone *phase_zone, const Graph &input_graph)
void AddUnaryOp (const Simd128UnaryOp &unop, LaneBitSet lanes)
void AddBinaryOp (const Simd128BinopOp &binop, LaneBitSet lanes)
void RecordOp (const Operation *op, LaneBitSet lanes)
const DemandedElementMap & demanded_elements () const
const Graph & input_graph () const
bool Visited (const Operation *op) const
Static Public Attributes
static constexpr uint16_t k8x16 = 0xFFFF
static constexpr uint16_t k8x8Low = 0xFF
static constexpr uint16_t k8x4Low = 0xF
static constexpr uint16_t k8x2Low = 0x3
Private Attributes
Zone * phase_zone_
const Graph & input_graph_
DemandedElementMap demanded_elements_ {phase_zone_}
ZoneUnorderedSet< const Operation * > visited_ {phase_zone_}
Detailed Description
Definition at line 43 of file wasm-shuffle-reducer.h.
Member Typedef Documentation
DemandedElementMap
using v8::internal::compiler::turboshaft::DemandedElementAnalysis::DemandedElementMap = ZoneVector<std::pair<const Operation*, LaneBitSet> >
Definition at line 51 of file wasm-shuffle-reducer.h.
LaneBitSet
using v8::internal::compiler::turboshaft::DemandedElementAnalysis::LaneBitSet = std::bitset<16>
Definition at line 50 of file wasm-shuffle-reducer.h.
Constructor & Destructor Documentation
DemandedElementAnalysis()
v8::internal::compiler::turboshaft::DemandedElementAnalysis::DemandedElementAnalysis (Zone * phase_zone, const Graph & input_graph) [inline]
Definition at line 54 of file wasm-shuffle-reducer.h.
      : phase_zone_(phase_zone), input_graph_(input_graph) {}
Member Function Documentation
AddBinaryOp()
void v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddBinaryOp (const Simd128BinopOp & binop, LaneBitSet lanes)
Definition at line 42 of file wasm-shuffle-reducer.cc.
                                                            {
  if (Visited(&binop)) return;
  visited_.insert(&binop);
  static constexpr std::array low_half_ops = {
      Simd128BinopOp::Kind::kI16x8ExtMulLowI8x16S,
      Simd128BinopOp::Kind::kI16x8ExtMulLowI8x16U,
      Simd128BinopOp::Kind::kI32x4ExtMulLowI16x8S,
      Simd128BinopOp::Kind::kI32x4ExtMulLowI16x8U,
      Simd128BinopOp::Kind::kI64x2ExtMulLowI32x4S,
      Simd128BinopOp::Kind::kI64x2ExtMulLowI32x4U,
  };
  const Operation& left = input_graph().Get(binop.left());
  const Operation& right = input_graph().Get(binop.right());
  for (auto const& kind : low_half_ops) {
    if (kind == binop.kind) {
      DCHECK(lanes == k8x16 || lanes == k8x8Low);
      lanes >>= lanes.count() / 2;
      if (left.saturated_use_count.IsOne()) {
        RecordOp(&left, lanes);
      }
      if (right.saturated_use_count.IsOne()) {
        RecordOp(&right, lanes);
      }
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), input_graph(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), k8x16, k8x8Low, RecordOp(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, Visited(), and visited_.
Referenced by v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessBinary(), and RecordOp().
AddUnaryOp()
void v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddUnaryOp (const Simd128UnaryOp & unop, LaneBitSet lanes)
Definition at line 11 of file wasm-shuffle-reducer.cc.
                                                           {
  if (Visited(&unop)) return;
  visited_.insert(&unop);
  const Operation& input = input_graph().Get(unop.input());
  if (!input.saturated_use_count.IsOne()) {
    return;
  }
  // TODO(sparker): Add floating-point conversions:
  // - PromoteLow
  // - ConvertLow
  static constexpr std::array low_half_ops = {
      Simd128UnaryOp::Kind::kI16x8SConvertI8x16Low,
      Simd128UnaryOp::Kind::kI16x8UConvertI8x16Low,
      Simd128UnaryOp::Kind::kI32x4SConvertI16x8Low,
      Simd128UnaryOp::Kind::kI32x4UConvertI16x8Low,
      Simd128UnaryOp::Kind::kI64x2SConvertI32x4Low,
      Simd128UnaryOp::Kind::kI64x2UConvertI32x4Low,
  };
  for (auto const kind : low_half_ops) {
    if (kind == unop.kind) {
      DCHECK(lanes == k8x16 || lanes == k8x8Low || lanes == k8x4Low);
      lanes >>= lanes.count() / 2;
      RecordOp(&input, lanes);
      return;
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), input_graph(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), k8x16, k8x4Low, k8x8Low, RecordOp(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, Visited(), and visited_.
Referenced by v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessUnary(), and RecordOp().
demanded_elements()
const DemandedElementMap& v8::internal::compiler::turboshaft::DemandedElementAnalysis::demanded_elements () const [inline]
Definition at line 61 of file wasm-shuffle-reducer.h.
                                                      {
    return demanded_elements_;
  }
References demanded_elements_.
Referenced by v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ops_to_reduce(), and v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ShouldReduce().
input_graph()
const Graph& v8::internal::compiler::turboshaft::DemandedElementAnalysis::input_graph () const [inline]
Definition at line 65 of file wasm-shuffle-reducer.h.
{ return input_graph_; }
References input_graph_.
Referenced by AddBinaryOp(), and AddUnaryOp().
RecordOp()
void v8::internal::compiler::turboshaft::DemandedElementAnalysis::RecordOp (const Operation * op, LaneBitSet lanes)
Definition at line 71 of file wasm-shuffle-reducer.cc.
                                                                            {
  if (auto* unop = op->TryCast<Simd128UnaryOp>()) {
    AddUnaryOp(*unop, lanes);
  } else if (auto* binop = op->TryCast<Simd128BinopOp>()) {
    AddBinaryOp(*binop, lanes);
  } else if (auto* shuffle = op->TryCast<Simd128ShuffleOp>()) {
    demanded_elements_.emplace_back(shuffle, lanes);
  }
}
References AddBinaryOp(), AddUnaryOp(), demanded_elements_, v8::internal::ZoneVector< T >::emplace_back(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by AddBinaryOp(), AddUnaryOp(), and v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffleOfShuffle().
Visited()
bool v8::internal::compiler::turboshaft::DemandedElementAnalysis::Visited (const Operation * op) const [inline]
Definition at line 67 of file wasm-shuffle-reducer.h.
{ return visited_.count(op); }
References visited_.
Referenced by AddBinaryOp(), and AddUnaryOp().
Member Data Documentation
demanded_elements_
DemandedElementMap v8::internal::compiler::turboshaft::DemandedElementAnalysis::demanded_elements_ {phase_zone_} [private]
Definition at line 72 of file wasm-shuffle-reducer.h.
Referenced by demanded_elements(), and RecordOp().
input_graph_
const Graph& v8::internal::compiler::turboshaft::DemandedElementAnalysis::input_graph_ [private]
Definition at line 71 of file wasm-shuffle-reducer.h.
Referenced by input_graph().
k8x16
constexpr uint16_t v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x16 = 0xFFFF [static], [constexpr]
Definition at line 45 of file wasm-shuffle-reducer.h.
Referenced by AddBinaryOp(), AddUnaryOp(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessBinary(), and v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessUnary().
k8x2Low
constexpr uint16_t v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x2Low = 0x3 [static], [constexpr]
Definition at line 48 of file wasm-shuffle-reducer.h.
Referenced by v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle().
k8x4Low
constexpr uint16_t v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x4Low = 0xF [static], [constexpr]
Definition at line 47 of file wasm-shuffle-reducer.h.
Referenced by AddUnaryOp(), and v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle().
k8x8Low
constexpr uint16_t v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x8Low = 0xFF [static], [constexpr]
Definition at line 46 of file wasm-shuffle-reducer.h.
Referenced by AddBinaryOp(), AddUnaryOp(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffleOfShuffle(), and v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle().
phase_zone_
Zone* v8::internal::compiler::turboshaft::DemandedElementAnalysis::phase_zone_ [private]
Definition at line 70 of file wasm-shuffle-reducer.h.
visited_
ZoneUnorderedSet<const Operation*> v8::internal::compiler::turboshaft::DemandedElementAnalysis::visited_ {phase_zone_} [private]
Definition at line 73 of file wasm-shuffle-reducer.h.
Referenced by AddBinaryOp(), AddUnaryOp(), and Visited().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-shuffle-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-shuffle-reducer.cc