v8::internal::TypedFrame Class Reference
#include <frames.h>
Public Member Functions
Tagged< HeapObject > unchecked_code () const override
void Iterate (RootVisitor *v) const override
void IterateParamsOfGenericWasmToJSWrapper (RootVisitor *v) const
Protected Member Functions
TypedFrame (StackFrameIteratorBase *iterator)
Additional Inherited Members
Detailed Description
Definition at line 702 of file frames.h.
Constructor & Destructor Documentation
TypedFrame()
v8::internal::TypedFrame::TypedFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 116 of file frames-inl.h.
    : CommonFrame(iterator) {}
Member Function Documentation
Iterate()
void v8::internal::TypedFrame::Iterate (RootVisitor * v) const [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::IrregexpFrame, v8::internal::ConstructFrame, v8::internal::InternalFrame, v8::internal::ExitFrame, v8::internal::EntryFrame, and v8::internal::NativeFrame.
Definition at line 1971 of file frames.cc.
                                             {
  DCHECK(!iterator_->IsStackFrameIteratorForProfiler());
  // === TypedFrame ===
  // +-----------------+-----------------------------------------
  // | out_param n | <-- parameters_base / sp
  // | ... |
  // | out_param 0 |
  // +-----------------+-----------------------------------------
  // | spill_slot n | <-- parameters_limit ^
  // | ... | spill_slot_count
  // | spill_slot 0 | v
  // +-----------------+-----------------------------------------
  // | Type Marker | <-- frame_header_base ^
  // |- - - - - - - - -| |
  // | [Constant Pool] | |
  // |- - - - - - - - -| kFixedSlotCount
  // | saved frame ptr | <-- fp |
  // |- - - - - - - - -| |
  // | return addr | v
  // +-----------------+-----------------------------------------
  // Find the code and compute the safepoint information.
  Address inner_pointer = pc();
  InnerPointerToCodeCache::InnerPointerToCodeCacheEntry* entry =
      isolate()->inner_pointer_to_code_cache()->GetCacheEntry(inner_pointer);
  CHECK(entry->code.has_value());
  Tagged<GcSafeCode> code = entry->code.value();
#if V8_ENABLE_WEBASSEMBLY
  bool is_generic_wasm_to_js =
      code->is_builtin() && code->builtin_id() == Builtin::kWasmToJsWrapperCSA;
  // Optimized wasm-to-js frames map to the WasmFrame type.
  DCHECK_NE(this->type(), WASM_TO_JS);
  if (is_generic_wasm_to_js) {
    IterateParamsOfGenericWasmToJSWrapper(v);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DCHECK(code->is_turbofanned());
  SafepointEntry safepoint_entry =
      GetSafepointEntryFromCodeCache(isolate(), inner_pointer, entry);
#ifdef DEBUG
  intptr_t marker =
      Memory<intptr_t>(fp() + CommonFrameConstants::kContextOrFrameTypeOffset);
  DCHECK(StackFrame::IsTypeMarker(marker));
#endif // DEBUG
  // Determine the fixed header and spill slot area size.
  int frame_header_size = TypedFrameConstants::kFixedFrameSizeFromFp;
  int spill_slots_size =
      code->stack_slots() * kSystemPointerSize -
      (frame_header_size + StandardFrameConstants::kFixedFrameSizeAboveFp);
  // Fixed frame slots.
  FullObjectSlot frame_header_base(&Memory<Address>(fp() - frame_header_size));
  FullObjectSlot frame_header_limit(
      &Memory<Address>(fp() - StandardFrameConstants::kCPSlotSize));
  // Parameters passed to the callee.
#if V8_ENABLE_WEBASSEMBLY
  // Frame layout without stack switching (stack grows upwards):
  //
  // | callee |
  // | frame |
  // |-------------| <- sp()
  // | out params |
  // |-------------| <- frame_header_base - spill_slot_space
  // | spill slots |
  // |-------------| <- frame_header_base
  // | frame header|
  // |-------------| <- fp()
  //
  // With stack-switching:
  //
  // Secondary stack: Central stack:
  //
  // | callee |
  // | frame |
  // |------------| <- sp()
  // | out params |
  // |-------------| |------------| <- maybe_stack_switch.target_sp
  // | spill slots |
  // |-------------| <- frame_header_base
  // | frame header|
  // |-------------| <- fp()
  //
  // The base (lowest address) of the outgoing stack parameters area is always
  // sp(), and the limit (highest address) is either {frame_header_base -
  // spill_slot_size} or {maybe_stack_switch.target_sp} depending on
  // stack-switching.
  wasm::StackMemory::StackSwitchInfo maybe_stack_switch;
  if (iterator_->wasm_stack() != nullptr) {
    maybe_stack_switch = iterator_->wasm_stack()->stack_switch_info();
  }
  FullObjectSlot parameters_limit(
      maybe_stack_switch.has_value() && maybe_stack_switch.source_fp == fp()
          ? maybe_stack_switch.target_sp
          : frame_header_base.address() - spill_slots_size);
#else
  FullObjectSlot parameters_limit(frame_header_base.address() -
                                  spill_slots_size);
#endif
  FullObjectSlot parameters_base(&Memory<Address>(sp()));
  FullObjectSlot spill_slots_end(frame_header_base.address() -
                                 spill_slots_size);
  // Visit the rest of the parameters.
  if (HasTaggedOutgoingParams(code)) {
    v->VisitRootPointers(Root::kStackRoots, nullptr, parameters_base,
                         parameters_limit);
  }
  // Visit pointer spill slots and locals.
  DCHECK_GE((code->stack_slots() + kBitsPerByte) / kBitsPerByte,
            safepoint_entry.tagged_slots().size());
  VisitSpillSlots(isolate(), v, spill_slots_end,
                  safepoint_entry.tagged_slots());
  // Visit fixed header region.
  v->VisitRootPointers(Root::kStackRoots, nullptr, frame_header_base,
                       frame_header_limit);
  // Visit the return address in the callee and incoming arguments.
  IteratePc(v, constant_pool_address(), code);
}
References CHECK, v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCacheEntry::code, code, v8::internal::StackFrame::constant_pool_address(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_NE, v8::internal::StackFrame::fp(), v8::internal::InnerPointerToCodeCache::GetCacheEntry(), v8::internal::anonymous_namespace{frames.cc}::GetSafepointEntryFromCodeCache(), v8::internal::wasm::StackMemory::StackSwitchInfo::has_value(), v8::internal::CommonFrame::HasTaggedOutgoingParams(), v8::internal::Isolate::inner_pointer_to_code_cache(), v8::internal::StackFrame::isolate(), v8::internal::StackFrame::IsTypeMarker(), IterateParamsOfGenericWasmToJSWrapper(), v8::internal::StackFrame::IteratePc(), v8::internal::StackFrame::iterator_, v8::internal::kBitsPerByte, v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::CommonFrameConstants::kCPSlotSize, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::TypedFrameConstants::kFixedFrameSizeFromFp, v8::internal::kSystemPointerSize, v8::internal::StackFrame::pc(), v8::base::Vector< T >::size(), v8::internal::wasm::StackMemory::StackSwitchInfo::source_fp, v8::internal::StackFrame::sp(), v8::internal::SafepointEntry::tagged_slots(), v8::internal::wasm::StackMemory::StackSwitchInfo::target_sp, v8::internal::StackFrame::type(), v8::internal::RootVisitor::VisitRootPointers(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlots().
IterateParamsOfGenericWasmToJSWrapper()
void v8::internal::TypedFrame::IterateParamsOfGenericWasmToJSWrapper (RootVisitor * v) const
Referenced by Iterate().
unchecked_code()
Tagged<HeapObject> v8::internal::TypedFrame::unchecked_code () const [inline], [override], [virtual]
Implements v8::internal::StackFrame.
Reimplemented in v8::internal::StubFrame, v8::internal::ConstructEntryFrame, and v8::internal::EntryFrame.
Definition at line 704 of file frames.h.
{ return {}; }
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc