v8::internal::wasm::DeserializeCodeTask Class Reference
Public Member Functions
DeserializeCodeTask (NativeModuleDeserializer *deserializer, DeserializationQueue *reloc_queue)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Member Functions
bool TryPublishing (JobDelegate *delegate)
Private Attributes
NativeModuleDeserializer *const deserializer_
DeserializationQueue *const reloc_queue_
DeserializationQueue publish_queue_
std::atomic< bool > publishing_ {false}
Detailed Description
Definition at line 738 of file wasm-serialization.cc.
Constructor & Destructor Documentation
DeserializeCodeTask()
v8::internal::wasm::DeserializeCodeTask::DeserializeCodeTask (NativeModuleDeserializer * deserializer, DeserializationQueue * reloc_queue) [inline]
Definition at line 740 of file wasm-serialization.cc.
      : deserializer_(deserializer), reloc_queue_(reloc_queue) {}
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::wasm::DeserializeCodeTask::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 760 of file wasm-serialization.cc.
                                                    {
    // Number of copy&reloc batches, plus 1 if there is also something to
    // publish.
    bool publish = publishing_.load(std::memory_order_relaxed) == false &&
                   publish_queue_.NumBatches() > 0;
    return reloc_queue_->NumBatches() + (publish ? 1 : 0);
  }
References v8::internal::wasm::DeserializationQueue::NumBatches(), publish_queue_, publishing_, and reloc_queue_.
Run()
void v8::internal::wasm::DeserializeCodeTask::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 744 of file wasm-serialization.cc.
                                           {
    bool finished = false;
    while (!finished) {
      // Repeatedly publish everything that was copied already.
      finished = TryPublishing(delegate);
      auto batch = reloc_queue_->Pop();
      if (batch.empty()) break;
      for (const auto& unit : batch) {
        deserializer_->CopyAndRelocate(unit);
      }
      publish_queue_.Add(std::move(batch));
      delegate->NotifyConcurrencyIncrease();
    }
  }
References v8::internal::wasm::DeserializationQueue::Add(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), deserializer_, v8::JobDelegate::NotifyConcurrencyIncrease(), v8::internal::wasm::DeserializationQueue::Pop(), publish_queue_, reloc_queue_, and TryPublishing().
TryPublishing()
bool v8::internal::wasm::DeserializeCodeTask::TryPublishing (JobDelegate * delegate) [inline], [private]
Definition at line 769 of file wasm-serialization.cc.
                                            {
    // Publishing is sequential, so only start publishing if no one else is.
    if (publishing_.exchange(true, std::memory_order_relaxed)) return false;
    WasmCodeRefScope code_scope;
    while (true) {
      bool yield = false;
      while (!yield) {
        auto to_publish = publish_queue_.PopAll();
        if (to_publish.empty()) break;
        deserializer_->Publish(std::move(to_publish));
        yield = delegate->ShouldYield();
      }
      publishing_.store(false, std::memory_order_relaxed);
      if (yield) return true;
      // After finishing publishing, check again if new work arrived in the mean
      // time. If so, continue publishing.
      if (publish_queue_.NumBatches() == 0) break;
      if (publishing_.exchange(true, std::memory_order_relaxed)) break;
      // We successfully reset {publishing_} from {false} to {true}.
    }
    return false;
  }
References deserializer_, v8::internal::wasm::DeserializationQueue::NumBatches(), v8::internal::wasm::DeserializationQueue::PopAll(), v8::internal::wasm::NativeModuleDeserializer::Publish(), publish_queue_, publishing_, and v8::JobDelegate::ShouldYield().
Referenced by Run().
Member Data Documentation
deserializer_
NativeModuleDeserializer* const v8::internal::wasm::DeserializeCodeTask::deserializer_ [private]
Definition at line 793 of file wasm-serialization.cc.
Referenced by Run(), and TryPublishing().
publish_queue_
DeserializationQueue v8::internal::wasm::DeserializeCodeTask::publish_queue_ [private]
Definition at line 795 of file wasm-serialization.cc.
Referenced by GetMaxConcurrency(), Run(), and TryPublishing().
publishing_
std::atomic<bool> v8::internal::wasm::DeserializeCodeTask::publishing_ {false} [private]
Definition at line 796 of file wasm-serialization.cc.
Referenced by GetMaxConcurrency(), and TryPublishing().
reloc_queue_
DeserializationQueue* const v8::internal::wasm::DeserializeCodeTask::reloc_queue_ [private]
Definition at line 794 of file wasm-serialization.cc.
Referenced by GetMaxConcurrency(), and Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc