v8::internal::AllocationCounter Class Reference
#include <allocation-observer.h>
Classes
struct AllocationObserverCounter
Public Member Functions
AllocationCounter ()=default
V8_EXPORT_PRIVATE void AddAllocationObserver (AllocationObserver *observer)
V8_EXPORT_PRIVATE void RemoveAllocationObserver (AllocationObserver *observer)
V8_EXPORT_PRIVATE void AdvanceAllocationObservers (size_t allocated)
V8_EXPORT_PRIVATE void InvokeAllocationObservers (Address soon_object, size_t object_size, size_t aligned_object_size)
bool IsStepInProgress () const
size_t NextBytes () const
Private Attributes
std::vector< AllocationObserverCounter > observers_
std::vector< AllocationObserverCounter > pending_added_
std::unordered_set< AllocationObserver * > pending_removed_
size_t current_counter_ = 0
size_t next_counter_ = 0
bool step_in_progress_ = false
Detailed Description
Definition at line 54 of file allocation-observer.h.
Constructor & Destructor Documentation
AllocationCounter()
v8::internal::AllocationCounter::AllocationCounter () [default]
Member Function Documentation
AddAllocationObserver()
void v8::internal::AllocationCounter::AddAllocationObserver (AllocationObserver * observer)
Definition at line 15 of file allocation-observer.cc.
                                                                          {
#if DEBUG
  auto it = std::find_if(observers_.begin(), observers_.end(),
                         [observer](const AllocationObserverCounter& aoc) {
                           return aoc.observer_ == observer;
                         });
  DCHECK_EQ(observers_.end(), it);
#endif
  if (step_in_progress_) {
    pending_added_.push_back(AllocationObserverCounter(observer, 0, 0));
    return;
  }
  intptr_t step_size = observer->GetNextStepSize();
  size_t observer_next_counter = current_counter_ + step_size;
  observers_.push_back(AllocationObserverCounter(observer, current_counter_,
                                                 observer_next_counter));
  if (observers_.size() == 1) {
    DCHECK_EQ(current_counter_, next_counter_);
    next_counter_ = observer_next_counter;
  } else {
    size_t missing_bytes = next_counter_ - current_counter_;
    next_counter_ = current_counter_ +
                    std::min(static_cast<intptr_t>(missing_bytes), step_size);
  }
}
References current_counter_, DCHECK_EQ, v8::internal::AllocationObserver::GetNextStepSize(), next_counter_, observers_, pending_added_, and step_in_progress_.
Referenced by v8::internal::LargeObjectSpace::AddAllocationObserver(), and v8::internal::MainAllocator::AddAllocationObserver().
AdvanceAllocationObservers()
void v8::internal::AllocationCounter::AdvanceAllocationObservers (size_t allocated)
Definition at line 75 of file allocation-observer.cc.
                                                                   {
  if (observers_.empty()) return;
  DCHECK(!step_in_progress_);
  DCHECK_LT(allocated, next_counter_ - current_counter_);
  current_counter_ += allocated;
}
References current_counter_, v8::internal::DCHECK(), DCHECK_LT, next_counter_, observers_, and step_in_progress_.
Referenced by v8::internal::MainAllocator::AdvanceAllocationObservers(), and v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers().
InvokeAllocationObservers()
void v8::internal::AllocationCounter::InvokeAllocationObservers (Address soon_object, size_t object_size, size_t aligned_object_size)
Definition at line 82 of file allocation-observer.cc.
                                                                              {
  if (observers_.empty()) return;
  DCHECK(!step_in_progress_);
  DCHECK_GE(aligned_object_size, next_counter_ - current_counter_);
  DCHECK(soon_object);
  bool step_run = false;
  step_in_progress_ = true;
  size_t step_size = 0;
  DCHECK(pending_added_.empty());
  DCHECK(pending_removed_.empty());
  for (AllocationObserverCounter& aoc : observers_) {
    if (aoc.next_counter_ - current_counter_ <= aligned_object_size) {
      {
        DisallowGarbageCollection no_gc;
        aoc.observer_->Step(
            static_cast<int>(current_counter_ - aoc.prev_counter_), soon_object,
            object_size);
      }
      size_t observer_step_size = aoc.observer_->GetNextStepSize();
      aoc.prev_counter_ = current_counter_;
      aoc.next_counter_ =
          current_counter_ + aligned_object_size + observer_step_size;
      step_run = true;
    }
    size_t left_in_step = aoc.next_counter_ - current_counter_;
    step_size = step_size ? std::min(step_size, left_in_step) : left_in_step;
  }
  CHECK(step_run);
  // Now process newly added allocation observers.
  for (AllocationObserverCounter& aoc : pending_added_) {
    DCHECK_EQ(0, aoc.next_counter_);
    size_t observer_step_size = aoc.observer_->GetNextStepSize();
    aoc.prev_counter_ = current_counter_;
    aoc.next_counter_ =
        current_counter_ + aligned_object_size + observer_step_size;
    DCHECK_NE(step_size, 0);
    step_size = std::min(step_size, aligned_object_size + observer_step_size);
    observers_.push_back(aoc);
  }
  pending_added_.clear();
  if (!pending_removed_.empty()) {
    observers_.erase(
        std::remove_if(observers_.begin(), observers_.end(),
                       [this](const AllocationObserverCounter& aoc) {
                         return pending_removed_.count(aoc.observer_) != 0;
                       }),
        observers_.end());
    pending_removed_.clear();
    // Some observers were removed, recalculate step size.
    step_size = 0;
    for (AllocationObserverCounter& aoc : observers_) {
      size_t left_in_step = aoc.next_counter_ - current_counter_;
      step_size = step_size ? std::min(step_size, left_in_step) : left_in_step;
    }
    if (observers_.empty()) {
      next_counter_ = current_counter_ = 0;
      step_in_progress_ = false;
      return;
    }
  }
  next_counter_ = current_counter_ + step_size;
  step_in_progress_ = false;
}
References CHECK, current_counter_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_NE, v8::internal::AllocationCounter::AllocationObserverCounter::next_counter_, next_counter_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, observers_, pending_added_, pending_removed_, and step_in_progress_.
Referenced by v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), and v8::internal::MainAllocator::InvokeAllocationObservers().
IsStepInProgress()
bool v8::internal::AllocationCounter::IsStepInProgress () const [inline]
Definition at line 73 of file allocation-observer.h.
{ return step_in_progress_; }
References step_in_progress_.
NextBytes()
size_t v8::internal::AllocationCounter::NextBytes () const [inline]
Definition at line 75 of file allocation-observer.h.
                           {
    if (observers_.empty()) return SIZE_MAX;
    return next_counter_ - current_counter_;
  }
References current_counter_, next_counter_, and observers_.
Referenced by v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers(), and v8::internal::MainAllocator::ComputeLimit().
RemoveAllocationObserver()
void v8::internal::AllocationCounter::RemoveAllocationObserver (AllocationObserver * observer)
Definition at line 45 of file allocation-observer.cc.
                                                                             {
  auto it = std::find_if(observers_.begin(), observers_.end(),
                         [observer](const AllocationObserverCounter& aoc) {
                           return aoc.observer_ == observer;
                         });
  DCHECK_NE(observers_.end(), it);
  if (step_in_progress_) {
    DCHECK_EQ(pending_removed_.count(observer), 0);
    pending_removed_.insert(observer);
    return;
  }
  observers_.erase(it);
  if (observers_.empty()) {
    current_counter_ = next_counter_ = 0;
  } else {
    size_t step_size = 0;
    for (AllocationObserverCounter& observer_counter : observers_) {
      size_t left_in_step = observer_counter.next_counter_ - current_counter_;
      DCHECK_GT(left_in_step, 0);
      step_size = step_size ? std::min(step_size, left_in_step) : left_in_step;
    }
    next_counter_ = current_counter_ + step_size;
  }
}
References current_counter_, DCHECK_EQ, DCHECK_GT, DCHECK_NE, next_counter_, observers_, pending_removed_, and step_in_progress_.
Referenced by v8::internal::LargeObjectSpace::RemoveAllocationObserver(), and v8::internal::MainAllocator::RemoveAllocationObserver().
Member Data Documentation
current_counter_
size_t v8::internal::AllocationCounter::current_counter_ = 0 [private]
Definition at line 104 of file allocation-observer.h.
Referenced by AddAllocationObserver(), AdvanceAllocationObservers(), InvokeAllocationObservers(), NextBytes(), and RemoveAllocationObserver().
next_counter_
size_t v8::internal::AllocationCounter::next_counter_ = 0 [private]
Definition at line 105 of file allocation-observer.h.
Referenced by AddAllocationObserver(), AdvanceAllocationObservers(), InvokeAllocationObservers(), NextBytes(), and RemoveAllocationObserver().
observers_
std::vector<AllocationObserverCounter> v8::internal::AllocationCounter::observers_ [private]
Definition at line 100 of file allocation-observer.h.
Referenced by AddAllocationObserver(), AdvanceAllocationObservers(), InvokeAllocationObservers(), NextBytes(), and RemoveAllocationObserver().
pending_added_
std::vector<AllocationObserverCounter> v8::internal::AllocationCounter::pending_added_ [private]
Definition at line 101 of file allocation-observer.h.
Referenced by AddAllocationObserver(), and InvokeAllocationObservers().
pending_removed_
std::unordered_set<AllocationObserver*> v8::internal::AllocationCounter::pending_removed_ [private]
Definition at line 102 of file allocation-observer.h.
Referenced by InvokeAllocationObservers(), and RemoveAllocationObserver().
step_in_progress_
bool v8::internal::AllocationCounter::step_in_progress_ = false [private]
Definition at line 106 of file allocation-observer.h.
Referenced by AddAllocationObserver(), AdvanceAllocationObservers(), InvokeAllocationObservers(), IsStepInProgress(), and RemoveAllocationObserver().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/allocation-observer.h
/mnt/V8SourceCode/src/heap/allocation-observer.cc