v8::internal::UnoptimizedJSFrame Class Reference
#include <frames.h>
Public Member Functions
int position () const override
int LookupExceptionHandlerInTable (int *data, HandlerTable::CatchPrediction *prediction) override
virtual int GetBytecodeOffset () const =0
Tagged< BytecodeArray > GetBytecodeArray () const
Tagged< Object > ReadInterpreterRegister (int register_index) const
void SetFeedbackVector (Tagged< FeedbackVector > feedback_vector)
FrameSummaries Summarize () const override
Static Public Member Functions
static UnoptimizedJSFrame * cast (StackFrame *frame)
Protected Member Functions
UnoptimizedJSFrame (StackFrameIteratorBase *iterator)
Address GetExpressionAddress (int n) const override
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1096 of file frames.h.
Constructor & Destructor Documentation
UnoptimizedJSFrame()
v8::internal::UnoptimizedJSFrame::UnoptimizedJSFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 306 of file frames-inl.h.
    : JavaScriptFrame(iterator) {}
Member Function Documentation
cast()
static UnoptimizedJSFrame* v8::internal::UnoptimizedJSFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1119 of file frames.h.
                                                     {
    DCHECK(frame->is_unoptimized_js());
    return static_cast<UnoptimizedJSFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_unoptimized_js().
Referenced by v8::internal::BreakLocation::GetGeneratorObjectForSuspendedFrame(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
GetBytecodeArray()
Tagged< BytecodeArray > v8::internal::UnoptimizedJSFrame::GetBytecodeArray () const
Definition at line 3296 of file frames.cc.
                                                                 {
  const int index = UnoptimizedFrameConstants::kBytecodeArrayExpressionIndex;
  DCHECK_EQ(UnoptimizedFrameConstants::kBytecodeArrayFromFp,
            UnoptimizedFrameConstants::kExpressionsOffset -
                index * kSystemPointerSize);
  return Cast<BytecodeArray>(GetExpression(index));
}
References DCHECK_EQ, v8::internal::index, v8::internal::UnoptimizedFrameConstants::kBytecodeArrayExpressionIndex, v8::internal::UnoptimizedFrameConstants::kBytecodeArrayFromFp, v8::internal::UnoptimizedFrameConstants::kExpressionsOffset, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::Isolate::GetAbstractPC(), v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::JavaScriptFrame::Print(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread().
GetBytecodeOffset()
virtual int v8::internal::UnoptimizedJSFrame::GetBytecodeOffset () const [pure virtual]
Implemented in v8::internal::BaselineFrame, and v8::internal::InterpretedFrame.
Referenced by v8::internal::Isolate::GetAbstractPC(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), and v8::internal::RUNTIME_FUNCTION().
GetExpressionAddress()
Address v8::internal::UnoptimizedJSFrame::GetExpressionAddress (int n) const [override], [protected], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1476 of file frames.cc.
                                                            {
  const int offset = UnoptimizedFrameConstants::kExpressionsOffset;
  return fp() + offset - n * kSystemPointerSize;
}
References v8::internal::StackFrame::fp(), v8::internal::UnoptimizedFrameConstants::kExpressionsOffset, and v8::internal::kSystemPointerSize.
LookupExceptionHandlerInTable()
int v8::internal::UnoptimizedJSFrame::LookupExceptionHandlerInTable (int * data, HandlerTable::CatchPrediction * prediction) [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 3283 of file frames.cc.
                                                                    {
  HandlerTable table(GetBytecodeArray());
  int handler_index = table.LookupHandlerIndexForRange(GetBytecodeOffset());
  if (handler_index != HandlerTable::kNoHandlerFound) {
    if (context_register) *context_register = table.GetRangeData(handler_index);
    if (prediction) *prediction = table.GetRangePrediction(handler_index);
    table.MarkHandlerUsed(handler_index);
    return table.GetRangeHandler(handler_index);
  }
  return handler_index;
}
References v8::internal::HandlerTable::GetRangeData(), v8::internal::HandlerTable::GetRangeHandler(), v8::internal::HandlerTable::GetRangePrediction(), v8::internal::HandlerTable::kNoHandlerFound, v8::internal::HandlerTable::LookupHandlerIndexForRange(), and v8::internal::HandlerTable::MarkHandlerUsed().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
position()
int v8::internal::UnoptimizedJSFrame::position () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 3277 of file frames.cc.
                                       {
  Tagged<BytecodeArray> code = GetBytecodeArray();
  int code_offset = GetBytecodeOffset();
  return code->SourcePosition(code_offset);
}
References code, and v8::internal::FrameSummary::code_offset().
ReadInterpreterRegister()
Tagged< Object > v8::internal::UnoptimizedJSFrame::ReadInterpreterRegister (int register_index) const
Definition at line 3304 of file frames.cc.
                              {
  const int index = UnoptimizedFrameConstants::kRegisterFileExpressionIndex;
  DCHECK_EQ(UnoptimizedFrameConstants::kRegisterFileFromFp,
            UnoptimizedFrameConstants::kExpressionsOffset -
                index * kSystemPointerSize);
  return GetExpression(index + register_index);
}
References DCHECK_EQ, v8::internal::index, v8::internal::UnoptimizedFrameConstants::kExpressionsOffset, v8::internal::UnoptimizedFrameConstants::kRegisterFileExpressionIndex, v8::internal::UnoptimizedFrameConstants::kRegisterFileFromFp, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::BreakLocation::GetGeneratorObjectForSuspendedFrame(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), and v8::internal::Isolate::UnwindAndFindHandler().
SetFeedbackVector()
void v8::internal::UnoptimizedJSFrame::SetFeedbackVector (Tagged< FeedbackVector > feedback_vector) [inline]
Definition at line 285 of file frames-inl.h.
                                            {
  const int offset = InterpreterFrameConstants::kFeedbackVectorFromFp;
  base::Memory<Address>(fp() + offset) = feedback_vector.ptr();
}
References v8::internal::StackFrame::fp(), v8::internal::UnoptimizedFrameConstants::kFeedbackVectorFromFp, and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Summarize()
FrameSummaries v8::internal::UnoptimizedJSFrame::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 3313 of file frames.cc.
                                                   {
  DirectHandle<AbstractCode> abstract_code(
      Cast<AbstractCode>(GetBytecodeArray()), isolate());
  DirectHandle<FixedArray> params = GetParameters();
  FrameSummary::JavaScriptFrameSummary summary(
      isolate(), receiver(), function(), *abstract_code, GetBytecodeOffset(),
      IsConstructor(), *params);
  return FrameSummaries(summary);
}
References v8::bigint::anonymous_namespace{mul-fft.cc}::GetParameters(), and v8::internal::FrameSummary::receiver().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1130 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc