v8::internal::EhFrameWriter Class Reference
#include <eh-frame.h>
Public Member Functions
EhFrameWriter (Zone *zone)
EhFrameWriter (const EhFrameWriter &)=delete
EhFrameWriter & operator= (const EhFrameWriter &)=delete
void Initialize ()
void AdvanceLocation (int pc_offset)
void SetBaseAddressRegister (Register base_register)
void SetBaseAddressOffset (int base_offset)
void IncreaseBaseAddressOffset (int base_delta)
void SetBaseAddressRegisterAndOffset (Register base_register, int base_offset)
void RecordRegisterSavedToStack (Register name, int offset)
void RecordRegisterSavedToStack (int dwarf_register_code, int offset)
void RecordRegisterNotModified (Register name)
void RecordRegisterNotModified (int dwarf_register_code)
void RecordRegisterFollowsInitialRule (Register name)
void RecordRegisterFollowsInitialRule (int dwarf_register_code)
void Finish (int code_size)
void GetEhFrame (CodeDesc *desc)
int last_pc_offset () const
Register base_register () const
int base_offset () const
Static Public Member Functions
static void WriteEmptyEhFrame (std::ostream &stream)
Private Types
enum class InternalState { kUndefined
, kInitialized
, kFinalized
 }
Private Member Functions
void WriteSLeb128 (int32_t value)
void WriteULeb128 (uint32_t value)
void WriteByte (uint8_t value)
void WriteOpcode (EhFrameConstants::DwarfOpcodes opcode)
void WriteBytes (const uint8_t *start, int size)
void WriteInt16 (uint16_t value)
void WriteInt32 (uint32_t value)
void PatchInt32 (int base_offset, uint32_t value)
void WriteCie ()
void WriteFdeHeader ()
void WriteEhFrameHdr (int code_size)
void WritePaddingToAlignedSize (int unpadded_size)
int GetProcedureAddressOffset () const
int GetProcedureSizeOffset () const
int eh_frame_offset () const
int fde_offset () const
void WriteInitialStateInCie ()
void WriteReturnAddressRegisterCode ()
Static Private Member Functions
static int RegisterToDwarfCode (Register name)
Private Attributes
int cie_size_
int last_pc_offset_
InternalState writer_state_
Register base_register_
int base_offset_
ZoneVector< uint8_t > eh_frame_buffer_
Static Private Attributes
static const uint32_t kInt32Placeholder = 0xdeadc0de
Detailed Description
Definition at line 72 of file eh-frame.h.
Member Enumeration Documentation
InternalState
enum v8::internal::EhFrameWriter::InternalState [strong], [private]
Enumerator
kUndefined
kInitialized
kFinalized
Definition at line 134 of file eh-frame.h.
{ kUndefined, kInitialized, kFinalized };
Constructor & Destructor Documentation
EhFrameWriter() [1/2]
v8::internal::EhFrameWriter::EhFrameWriter (Zone * zone) [explicit]
Definition at line 73 of file eh-frame.cc.
    : cie_size_(0),
      last_pc_offset_(0),
      writer_state_(InternalState::kUndefined),
      base_register_(no_reg),
      base_offset_(0),
      eh_frame_buffer_(zone) {}
EhFrameWriter() [2/2]
v8::internal::EhFrameWriter::EhFrameWriter (const EhFrameWriter &) [delete]
Member Function Documentation
AdvanceLocation()
void v8::internal::EhFrameWriter::AdvanceLocation (int pc_offset)
Definition at line 251 of file eh-frame.cc.
                                                 {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  DCHECK_GE(pc_offset, last_pc_offset_);
  uint32_t delta = pc_offset - last_pc_offset_;
  DCHECK_EQ(delta % EhFrameConstants::kCodeAlignmentFactor, 0u);
  uint32_t factored_delta = delta / EhFrameConstants::kCodeAlignmentFactor;
  if (factored_delta <= EhFrameConstants::kLocationMask) {
    WriteByte((EhFrameConstants::kLocationTag
               << EhFrameConstants::kLocationMaskSize) |
              (factored_delta & EhFrameConstants::kLocationMask));
  } else if (factored_delta <= kMaxUInt8) {
    WriteOpcode(EhFrameConstants::DwarfOpcodes::kAdvanceLoc1);
    WriteByte(factored_delta);
  } else if (factored_delta <= kMaxUInt16) {
    WriteOpcode(EhFrameConstants::DwarfOpcodes::kAdvanceLoc2);
    WriteInt16(factored_delta);
  } else {
    WriteOpcode(EhFrameConstants::DwarfOpcodes::kAdvanceLoc4);
    WriteInt32(factored_delta);
  }
  last_pc_offset_ = pc_offset;
}
References DCHECK_EQ, DCHECK_GE, v8::internal::EhFrameConstants::kAdvanceLoc1, v8::internal::EhFrameConstants::kAdvanceLoc2, v8::internal::EhFrameConstants::kAdvanceLoc4, v8::internal::EhFrameConstants::kCodeAlignmentFactor, kInitialized, v8::internal::EhFrameConstants::kLocationMask, v8::internal::EhFrameConstants::kLocationMaskSize, v8::internal::EhFrameConstants::kLocationTag, v8::internal::kMaxUInt16, v8::internal::kMaxUInt8, last_pc_offset_, WriteByte(), WriteInt16(), WriteInt32(), WriteOpcode(), and writer_state_.
Referenced by v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock(), v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed(), v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed(), v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack(), v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack(), and v8::internal::compiler::UnwindingInfoWriter::MaybeIncreaseBaseOffsetAt().
base_offset()
int v8::internal::EhFrameWriter::base_offset () const [inline]
Definition at line 131 of file eh-frame.h.
{ return base_offset_; }
Referenced by SetBaseAddressOffset(), and SetBaseAddressRegisterAndOffset().
base_register()
Register v8::internal::EhFrameWriter::base_register () const [inline]
Definition at line 130 of file eh-frame.h.
{ return base_register_; }
Referenced by SetBaseAddressRegister(), and SetBaseAddressRegisterAndOffset().
eh_frame_offset()
int v8::internal::EhFrameWriter::eh_frame_offset () const [inline], [private]
Definition at line 189 of file eh-frame.h.
                              {
    return static_cast<int>(eh_frame_buffer_.size());
  }
Referenced by Finish(), WriteCie(), WriteEhFrameHdr(), and WriteFdeHeader().
fde_offset()
int v8::internal::EhFrameWriter::fde_offset () const [inline], [private]
Definition at line 193 of file eh-frame.h.
{ return cie_size_; }
Referenced by Finish(), and WriteFdeHeader().
Finish()
void v8::internal::EhFrameWriter::Finish (int code_size)
Definition at line 349 of file eh-frame.cc.
                                        {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  DCHECK_GE(eh_frame_offset(), cie_size_);
  DCHECK_GE(eh_frame_offset(), fde_offset() + kInt32Size);
  WritePaddingToAlignedSize(eh_frame_offset() - fde_offset() - kInt32Size);
  // Write the size of the FDE now that we know it.
  // The encoded size does not include the size field itself.
  int encoded_fde_size = eh_frame_offset() - fde_offset() - kInt32Size;
  PatchInt32(fde_offset(), encoded_fde_size);
  // Write size and offset to procedure.
  PatchInt32(GetProcedureAddressOffset(),
             -(RoundUp(code_size, 8) + GetProcedureAddressOffset()));
  PatchInt32(GetProcedureSizeOffset(), code_size);
  // Terminate the .eh_frame.
  static const uint8_t kTerminator[EhFrameConstants::kEhFrameTerminatorSize] = {
      0};
  WriteBytes(&kTerminator[0], EhFrameConstants::kEhFrameTerminatorSize);
  WriteEhFrameHdr(code_size);
  writer_state_ = InternalState::kFinalized;
}
References cie_size_, DCHECK_EQ, DCHECK_GE, eh_frame_offset(), fde_offset(), GetProcedureAddressOffset(), GetProcedureSizeOffset(), v8::internal::EhFrameConstants::kEhFrameTerminatorSize, kFinalized, kInitialized, v8::internal::kInt32Size, PatchInt32(), RoundUp(), WriteBytes(), WriteEhFrameHdr(), WritePaddingToAlignedSize(), and writer_state_.
Referenced by v8::internal::compiler::UnwindingInfoWriter::Finish().
GetEhFrame()
void v8::internal::EhFrameWriter::GetEhFrame (CodeDesc * desc)
Definition at line 376 of file eh-frame.cc.
                                             {
  DCHECK_EQ(writer_state_, InternalState::kFinalized);
  desc->unwinding_info_size = static_cast<int>(eh_frame_buffer_.size());
  desc->unwinding_info = eh_frame_buffer_.data();
}
References v8::internal::ZoneVector< T >::data(), DCHECK_EQ, eh_frame_buffer_, kFinalized, v8::internal::ZoneVector< T >::size(), v8::internal::CodeDesc::unwinding_info, v8::internal::CodeDesc::unwinding_info_size, and writer_state_.
Referenced by v8::internal::compiler::CodeGenerator::FinalizeCode().
GetProcedureAddressOffset()
int v8::internal::EhFrameWriter::GetProcedureAddressOffset () const [inline], [private]
Definition at line 181 of file eh-frame.h.
                                        {
    return fde_offset() + EhFrameConstants::kProcedureAddressOffsetInFde;
  }
References v8::internal::EhFrameConstants::kProcedureAddressOffsetInFde.
Referenced by Finish(), and WriteFdeHeader().
GetProcedureSizeOffset()
int v8::internal::EhFrameWriter::GetProcedureSizeOffset () const [inline], [private]
Definition at line 185 of file eh-frame.h.
                                     {
    return fde_offset() + EhFrameConstants::kProcedureSizeOffsetInFde;
  }
References v8::internal::EhFrameConstants::kProcedureSizeOffsetInFde.
Referenced by Finish(), and WriteFdeHeader().
IncreaseBaseAddressOffset()
void v8::internal::EhFrameWriter::IncreaseBaseAddressOffset (int base_delta) [inline]
Definition at line 97 of file eh-frame.h.
                                                 {
    SetBaseAddressOffset(base_offset_ + base_delta);
  }
Referenced by v8::internal::compiler::UnwindingInfoWriter::MaybeIncreaseBaseOffsetAt().
Initialize()
void v8::internal::EhFrameWriter::Initialize ()
Definition at line 81 of file eh-frame.cc.
                               {
  DCHECK_EQ(writer_state_, InternalState::kUndefined);
  eh_frame_buffer_.reserve(128);
  writer_state_ = InternalState::kInitialized;
  WriteCie();
  WriteFdeHeader();
}
References DCHECK_EQ, eh_frame_buffer_, kInitialized, kUndefined, v8::internal::ZoneVector< T >::reserve(), WriteCie(), WriteFdeHeader(), and writer_state_.
Referenced by v8::internal::compiler::UnwindingInfoWriter::UnwindingInfoWriter().
last_pc_offset()
int v8::internal::EhFrameWriter::last_pc_offset () const [inline]
Definition at line 129 of file eh-frame.h.
{ return last_pc_offset_; }
operator=()
EhFrameWriter& v8::internal::EhFrameWriter::operator= (const EhFrameWriter &) [delete]
PatchInt32()
void v8::internal::EhFrameWriter::PatchInt32 (int base_offset, uint32_t value) [inline], [private]
Definition at line 154 of file eh-frame.h.
                                                   {
    DCHECK_EQ(
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(eh_frame_buffer_.data()) + base_offset),
        kInt32Placeholder);
    DCHECK_LT(base_offset + kInt32Size, eh_frame_offset());
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(eh_frame_buffer_.data()) + base_offset,
        value);
  }
References DCHECK_EQ, DCHECK_LT, v8::internal::kInt32Size, and v8::internal::value.
Referenced by Finish(), and WriteCie().
RecordRegisterFollowsInitialRule() [1/2]
void v8::internal::EhFrameWriter::RecordRegisterFollowsInitialRule (int dwarf_register_code)
Definition at line 337 of file eh-frame.cc.
                                                                            {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  if (dwarf_register_code <= EhFrameConstants::kFollowInitialRuleMask) {
    WriteByte((EhFrameConstants::kFollowInitialRuleTag
               << EhFrameConstants::kFollowInitialRuleMaskSize) |
              (dwarf_register_code & EhFrameConstants::kFollowInitialRuleMask));
  } else {
    WriteOpcode(EhFrameConstants::DwarfOpcodes::kRestoreExtended);
    WriteULeb128(dwarf_register_code);
  }
}
References DCHECK_EQ, v8::internal::EhFrameConstants::kFollowInitialRuleMask, v8::internal::EhFrameConstants::kFollowInitialRuleMaskSize, v8::internal::EhFrameConstants::kFollowInitialRuleTag, kInitialized, v8::internal::EhFrameConstants::kRestoreExtended, WriteByte(), WriteOpcode(), writer_state_, and WriteULeb128().
RecordRegisterFollowsInitialRule() [2/2]
void v8::internal::EhFrameWriter::RecordRegisterFollowsInitialRule (Register name)
Definition at line 333 of file eh-frame.cc.
                                                                  {
  RecordRegisterFollowsInitialRule(RegisterToDwarfCode(name));
}
References v8::internal::name, and RegisterToDwarfCode().
Referenced by v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock(), v8::internal::compiler::UnwindingInfoWriter::MarkFrameDeconstructed(), and v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack().
RecordRegisterNotModified() [1/2]
void v8::internal::EhFrameWriter::RecordRegisterNotModified (int dwarf_register_code)
Definition at line 327 of file eh-frame.cc.
                                                                     {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  WriteOpcode(EhFrameConstants::DwarfOpcodes::kSameValue);
  WriteULeb128(dwarf_register_code);
}
References DCHECK_EQ, kInitialized, v8::internal::EhFrameConstants::kSameValue, WriteOpcode(), writer_state_, and WriteULeb128().
RecordRegisterNotModified() [2/2]
void v8::internal::EhFrameWriter::RecordRegisterNotModified (Register name)
Definition at line 323 of file eh-frame.cc.
                                                           {
  RecordRegisterNotModified(RegisterToDwarfCode(name));
}
References v8::internal::name, and RegisterToDwarfCode().
Referenced by WriteInitialStateInCie().
RecordRegisterSavedToStack() [1/2]
void v8::internal::EhFrameWriter::RecordRegisterSavedToStack (int dwarf_register_code, int offset)
Definition at line 305 of file eh-frame.cc.
                                                           {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  DCHECK_EQ(offset % EhFrameConstants::kDataAlignmentFactor, 0);
  int factored_offset = offset / EhFrameConstants::kDataAlignmentFactor;
  if (factored_offset >= 0) {
    DCHECK_LE(dwarf_register_code, EhFrameConstants::kSavedRegisterMask);
    WriteByte((EhFrameConstants::kSavedRegisterTag
               << EhFrameConstants::kSavedRegisterMaskSize) |
              (dwarf_register_code & EhFrameConstants::kSavedRegisterMask));
    WriteULeb128(factored_offset);
  } else {
    WriteOpcode(EhFrameConstants::DwarfOpcodes::kOffsetExtendedSf);
    WriteULeb128(dwarf_register_code);
    WriteSLeb128(factored_offset);
  }
}
References DCHECK_EQ, DCHECK_LE, v8::internal::EhFrameConstants::kDataAlignmentFactor, kInitialized, v8::internal::EhFrameConstants::kOffsetExtendedSf, v8::internal::EhFrameConstants::kSavedRegisterMask, v8::internal::EhFrameConstants::kSavedRegisterMaskSize, v8::internal::EhFrameConstants::kSavedRegisterTag, WriteByte(), WriteOpcode(), writer_state_, WriteSLeb128(), and WriteULeb128().
RecordRegisterSavedToStack() [2/2]
void v8::internal::EhFrameWriter::RecordRegisterSavedToStack (Register name, int offset) [inline]
Definition at line 104 of file eh-frame.h.
                                                             {
    RecordRegisterSavedToStack(RegisterToDwarfCode(name), offset);
  }
References v8::internal::name.
Referenced by v8::internal::compiler::UnwindingInfoWriter::BeginInstructionBlock(), v8::internal::compiler::UnwindingInfoWriter::MarkFrameConstructed(), and v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack().
RegisterToDwarfCode()
int v8::internal::EhFrameWriter::RegisterToDwarfCode (Register name) [static], [private]
Definition at line 28 of file eh-frame-arm.cc.
                                                    {
  switch (name.code()) {
    case kRegCode_fp:
      return kFpDwarfCode;
    case kRegCode_sp:
      return kSpDwarfCode;
    case kRegCode_lr:
      return kLrDwarfCode;
    case kRegCode_r0:
      return kR0DwarfCode;
    default:
      UNIMPLEMENTED();
  }
}
References v8::internal::kFpDwarfCode, v8::internal::kLrDwarfCode, v8::internal::kR0DwarfCode, v8::internal::kSpDwarfCode, v8::internal::name, and v8::internal::UNIMPLEMENTED().
Referenced by RecordRegisterFollowsInitialRule(), RecordRegisterNotModified(), SetBaseAddressRegister(), and SetBaseAddressRegisterAndOffset().
SetBaseAddressOffset()
void v8::internal::EhFrameWriter::SetBaseAddressOffset (int base_offset)
Definition at line 277 of file eh-frame.cc.
                                                        {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  DCHECK_GE(base_offset, 0);
  WriteOpcode(EhFrameConstants::DwarfOpcodes::kDefCfaOffset);
  WriteULeb128(base_offset);
  base_offset_ = base_offset;
}
References base_offset(), base_offset_, DCHECK_EQ, DCHECK_GE, v8::internal::EhFrameConstants::kDefCfaOffset, kInitialized, WriteOpcode(), writer_state_, and WriteULeb128().
SetBaseAddressRegister()
void v8::internal::EhFrameWriter::SetBaseAddressRegister (Register base_register)
Definition at line 285 of file eh-frame.cc.
                                                                 {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  int code = RegisterToDwarfCode(base_register);
  WriteOpcode(EhFrameConstants::DwarfOpcodes::kDefCfaRegister);
  WriteULeb128(code);
  base_register_ = base_register;
}
References base_register(), base_register_, code, DCHECK_EQ, v8::internal::EhFrameConstants::kDefCfaRegister, kInitialized, RegisterToDwarfCode(), WriteOpcode(), writer_state_, and WriteULeb128().
SetBaseAddressRegisterAndOffset()
void v8::internal::EhFrameWriter::SetBaseAddressRegisterAndOffset (Register base_register, int base_offset)
Definition at line 293 of file eh-frame.cc.
                                                                     {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  DCHECK_GE(base_offset, 0);
  int code = RegisterToDwarfCode(base_register);
  WriteOpcode(EhFrameConstants::DwarfOpcodes::kDefCfa);
  WriteULeb128(code);
  WriteULeb128(base_offset);
  base_offset_ = base_offset;
  base_register_ = base_register;
}
References base_offset(), base_offset_, base_register(), base_register_, code, DCHECK_EQ, DCHECK_GE, v8::internal::EhFrameConstants::kDefCfa, kInitialized, RegisterToDwarfCode(), WriteOpcode(), writer_state_, and WriteULeb128().
Referenced by v8::internal::compiler::UnwindingInfoWriter::MarkLinkRegisterOnTopOfStack(), v8::internal::compiler::UnwindingInfoWriter::MarkPopLinkRegisterFromTopOfStack(), and WriteInitialStateInCie().
WriteByte()
void v8::internal::EhFrameWriter::WriteByte (uint8_t value) [inline], [private]
Definition at line 141 of file eh-frame.h.
{ eh_frame_buffer_.push_back(value); }
References v8::internal::value.
Referenced by AdvanceLocation(), RecordRegisterFollowsInitialRule(), RecordRegisterSavedToStack(), WriteCie(), WriteEhFrameHdr(), WriteFdeHeader(), WriteSLeb128(), and WriteULeb128().
WriteBytes()
void v8::internal::EhFrameWriter::WriteBytes (const uint8_t * start, int size) [inline], [private]
Definition at line 145 of file eh-frame.h.
                                                  {
    eh_frame_buffer_.insert(eh_frame_buffer_.end(), start, start + size);
  }
References size().
Referenced by Finish(), WriteCie(), and WritePaddingToAlignedSize().
WriteCie()
void v8::internal::EhFrameWriter::WriteCie () [private]
Definition at line 89 of file eh-frame.cc.
                             {
  static const int kCIEIdentifier = 0;
  static const int kCIEVersion = 3;
  static const int kAugmentationDataSize = 2;
  static const uint8_t kAugmentationString[] = {'z', 'L', 'R', 0};
  // Placeholder for the size of the CIE.
  int size_offset = eh_frame_offset();
  WriteInt32(kInt32Placeholder);
  // CIE identifier and version.
  int record_start_offset = eh_frame_offset();
  WriteInt32(kCIEIdentifier);
  WriteByte(kCIEVersion);
  // Augmentation data contents descriptor: LSDA and FDE encoding.
  WriteBytes(&kAugmentationString[0], sizeof(kAugmentationString));
  // Alignment factors.
  WriteSLeb128(EhFrameConstants::kCodeAlignmentFactor);
  WriteSLeb128(EhFrameConstants::kDataAlignmentFactor);
  WriteReturnAddressRegisterCode();
  // Augmentation data.
  WriteULeb128(kAugmentationDataSize);
  // No language-specific data area (LSDA).
  WriteByte(EhFrameConstants::kOmit);
  // FDE pointers encoding.
  WriteByte(EhFrameConstants::kSData4 | EhFrameConstants::kPcRel);
  // Write directives to build the initial state of the unwinding table.
  DCHECK_EQ(eh_frame_offset() - size_offset,
            EhFrameConstants::kInitialStateOffsetInCie);
  WriteInitialStateInCie();
  WritePaddingToAlignedSize(eh_frame_offset() - record_start_offset);
  int record_end_offset = eh_frame_offset();
  int encoded_cie_size = record_end_offset - record_start_offset;
  cie_size_ = record_end_offset - size_offset;
  // Patch the size of the CIE now that we know it.
  PatchInt32(size_offset, encoded_cie_size);
}
References cie_size_, DCHECK_EQ, eh_frame_offset(), v8::internal::EhFrameConstants::kCodeAlignmentFactor, v8::internal::EhFrameConstants::kDataAlignmentFactor, v8::internal::EhFrameConstants::kInitialStateOffsetInCie, kInt32Placeholder, v8::internal::EhFrameConstants::kOmit, v8::internal::EhFrameConstants::kPcRel, v8::internal::EhFrameConstants::kSData4, PatchInt32(), WriteByte(), WriteBytes(), WriteInitialStateInCie(), WriteInt32(), WritePaddingToAlignedSize(), WriteReturnAddressRegisterCode(), WriteSLeb128(), and WriteULeb128().
Referenced by Initialize().
WriteEhFrameHdr()
void v8::internal::EhFrameWriter::WriteEhFrameHdr (int code_size) [private]
Definition at line 157 of file eh-frame.cc.
                                                 {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  //
  // In order to calculate offsets in the .eh_frame_hdr, we must know the layout
  // of the DSO generated by perf inject, which is assumed to be the following:
  //
  // | ... | |
  // +---------------+ <-- (F) --- | Larger offsets in file
  // | | ^ |
  // | Instructions | | .text v
  // | | v
  // +---------------+ <-- (E) ---
  // |///////////////|
  // |////Padding////|
  // |///////////////|
  // +---------------+ <-- (D) ---
  // | | ^
  // | CIE | |
  // | | |
  // +---------------+ <-- (C) |
  // | | | .eh_frame
  // | FDE | |
  // | | |
  // +---------------+ |
  // | terminator | v
  // +---------------+ <-- (B) ---
  // | version | ^
  // +---------------+ |
  // | encoding | |
  // | specifiers | |
  // +---------------+ <---(A) | .eh_frame_hdr
  // | offset to | |
  // | .eh_frame | |
  // +---------------+ |
  // | ... | ...
  //
  // (F) is aligned to a 16-byte boundary.
  // (D) is aligned to a 8-byte boundary.
  // (B) is aligned to a 4-byte boundary.
  // (C), (E) and (A) have no alignment requirements.
  //
  // The distance between (A) and (B) is 4 bytes.
  //
  // The size of the FDE is required to be a multiple of the pointer size, which
  // means that (B) will be naturally aligned to a 4-byte boundary on all the
  // architectures we support.
  //
  // Because (E) has no alignment requirements, there is padding between (E) and
  // (D). (F) is aligned at a 16-byte boundary, thus to a 8-byte one as well.
  //
  int eh_frame_size = eh_frame_offset();
  WriteByte(EhFrameConstants::kEhFrameHdrVersion);
  // .eh_frame pointer encoding specifier.
  WriteByte(EhFrameConstants::kSData4 | EhFrameConstants::kPcRel);
  // Lookup table size encoding specifier.
  WriteByte(EhFrameConstants::kUData4);
  // Lookup table entries encoding specifier.
  WriteByte(EhFrameConstants::kSData4 | EhFrameConstants::kDataRel);
  // Pointer to .eh_frame, relative to this offset (A -> D in the diagram).
  WriteInt32(-(eh_frame_size + EhFrameConstants::kFdeVersionSize +
               EhFrameConstants::kFdeEncodingSpecifiersSize));
  // Number of entries in the LUT, one for the only routine.
  WriteInt32(1);
  // Pointer to the start of the routine, relative to the beginning of the
  // .eh_frame_hdr (B -> F in the diagram).
  WriteInt32(-(RoundUp(code_size, 8) + eh_frame_size));
  // Pointer to the start of the associated FDE, relative to the start of the
  // .eh_frame_hdr (B -> C in the diagram).
  WriteInt32(-(eh_frame_size - cie_size_));
  DCHECK_EQ(eh_frame_offset() - eh_frame_size,
            EhFrameConstants::kEhFrameHdrSize);
}
References cie_size_, DCHECK_EQ, eh_frame_offset(), v8::internal::EhFrameConstants::kDataRel, v8::internal::EhFrameConstants::kEhFrameHdrSize, v8::internal::EhFrameConstants::kEhFrameHdrVersion, v8::internal::EhFrameConstants::kFdeEncodingSpecifiersSize, v8::internal::EhFrameConstants::kFdeVersionSize, kInitialized, v8::internal::EhFrameConstants::kPcRel, v8::internal::EhFrameConstants::kSData4, v8::internal::EhFrameConstants::kUData4, RoundUp(), WriteByte(), WriteInt32(), and writer_state_.
Referenced by Finish().
WriteEmptyEhFrame()
void v8::internal::EhFrameWriter::WriteEmptyEhFrame (std::ostream & stream) [static]
Definition at line 56 of file eh-frame.cc.
                                                        {
  stream.put(EhFrameConstants::kEhFrameHdrVersion);
  // .eh_frame pointer encoding specifier.
  stream.put(EhFrameConstants::kSData4 | EhFrameConstants::kPcRel);
  // Lookup table size encoding.
  stream.put(EhFrameConstants::kUData4);
  // Lookup table entries encoding.
  stream.put(EhFrameConstants::kSData4 | EhFrameConstants::kDataRel);
  // Dummy pointers and 0 entries in the lookup table.
  char dummy_data[EhFrameConstants::kEhFrameHdrSize - 4] = {0};
  stream.write(&dummy_data[0], sizeof(dummy_data));
}
References v8::internal::EhFrameConstants::kDataRel, v8::internal::EhFrameConstants::kEhFrameHdrSize, v8::internal::EhFrameConstants::kEhFrameHdrVersion, v8::internal::EhFrameConstants::kPcRel, v8::internal::EhFrameConstants::kSData4, and v8::internal::EhFrameConstants::kUData4.
WriteFdeHeader()
void v8::internal::EhFrameWriter::WriteFdeHeader () [private]
Definition at line 135 of file eh-frame.cc.
                                   {
  DCHECK_NE(cie_size_, 0);
  // Placeholder for size of the FDE. Will be filled in Finish().
  DCHECK_EQ(eh_frame_offset(), fde_offset());
  WriteInt32(kInt32Placeholder);
  // Backwards offset to the CIE.
  WriteInt32(cie_size_ + kInt32Size);
  // Placeholder for pointer to procedure. Will be filled in Finish().
  DCHECK_EQ(eh_frame_offset(), GetProcedureAddressOffset());
  WriteInt32(kInt32Placeholder);
  // Placeholder for size of the procedure. Will be filled in Finish().
  DCHECK_EQ(eh_frame_offset(), GetProcedureSizeOffset());
  WriteInt32(kInt32Placeholder);
  // No augmentation data.
  WriteByte(0);
}
References cie_size_, DCHECK_EQ, DCHECK_NE, eh_frame_offset(), fde_offset(), GetProcedureAddressOffset(), GetProcedureSizeOffset(), kInt32Placeholder, v8::internal::kInt32Size, WriteByte(), and WriteInt32().
Referenced by Initialize().
WriteInitialStateInCie()
void v8::internal::EhFrameWriter::WriteInitialStateInCie () [private]
Definition at line 22 of file eh-frame-arm.cc.
                                           {
  SetBaseAddressRegisterAndOffset(fp, 0);
  RecordRegisterNotModified(lr);
}
References RecordRegisterNotModified(), and SetBaseAddressRegisterAndOffset().
Referenced by WriteCie().
WriteInt16()
void v8::internal::EhFrameWriter::WriteInt16 (uint16_t value) [inline], [private]
Definition at line 148 of file eh-frame.h.
                                  {
    WriteBytes(reinterpret_cast<const uint8_t*>(&value), sizeof(value));
  }
References v8::internal::value, and v8::internal::WriteBytes().
Referenced by AdvanceLocation().
WriteInt32()
void v8::internal::EhFrameWriter::WriteInt32 (uint32_t value) [inline], [private]
Definition at line 151 of file eh-frame.h.
                                  {
    WriteBytes(reinterpret_cast<const uint8_t*>(&value), sizeof(value));
  }
References v8::internal::value, and v8::internal::WriteBytes().
Referenced by AdvanceLocation(), WriteCie(), WriteEhFrameHdr(), and WriteFdeHeader().
WriteOpcode()
void v8::internal::EhFrameWriter::WriteOpcode (EhFrameConstants::DwarfOpcodes opcode) [inline], [private]
Definition at line 142 of file eh-frame.h.
                                                        {
    WriteByte(static_cast<uint8_t>(opcode));
  }
Referenced by AdvanceLocation(), RecordRegisterFollowsInitialRule(), RecordRegisterNotModified(), RecordRegisterSavedToStack(), SetBaseAddressOffset(), SetBaseAddressRegister(), and SetBaseAddressRegisterAndOffset().
WritePaddingToAlignedSize()
void v8::internal::EhFrameWriter::WritePaddingToAlignedSize (int unpadded_size) [private]
Definition at line 239 of file eh-frame.cc.
                                                               {
  DCHECK_EQ(writer_state_, InternalState::kInitialized);
  DCHECK_GE(unpadded_size, 0);
  int padding_size = RoundUp(unpadded_size, kSystemPointerSize) - unpadded_size;
  uint8_t nop = static_cast<uint8_t>(EhFrameConstants::DwarfOpcodes::kNop);
  static const uint8_t kPadding[] = {nop, nop, nop, nop, nop, nop, nop, nop};
  DCHECK_LE(padding_size, static_cast<int>(sizeof(kPadding)));
  WriteBytes(&kPadding[0], padding_size);
}
References DCHECK_EQ, DCHECK_GE, DCHECK_LE, kInitialized, v8::internal::EhFrameConstants::kNop, v8::internal::kPadding, v8::internal::kSystemPointerSize, RoundUp(), WriteBytes(), and writer_state_.
Referenced by Finish(), and WriteCie().
WriteReturnAddressRegisterCode()
void v8::internal::EhFrameWriter::WriteReturnAddressRegisterCode () [private]
Definition at line 18 of file eh-frame-arm.cc.
                                                   {
  WriteULeb128(kLrDwarfCode);
}
References v8::internal::kLrDwarfCode, and WriteULeb128().
Referenced by WriteCie().
WriteSLeb128()
void v8::internal::EhFrameWriter::WriteSLeb128 (int32_t value) [private]
Definition at line 391 of file eh-frame.cc.
                                              {
  static const int kSignBitMask = 0x40;
  bool done;
  do {
    uint8_t chunk = value & 0x7F;
    value >>= 7;
    done = ((value == 0) && ((chunk & kSignBitMask) == 0)) ||
           ((value == -1) && ((chunk & kSignBitMask) != 0));
    if (!done) chunk |= 0x80;
    WriteByte(chunk);
  } while (!done);
}
References v8::internal::value, and WriteByte().
Referenced by RecordRegisterSavedToStack(), and WriteCie().
WriteULeb128()
void v8::internal::EhFrameWriter::WriteULeb128 (uint32_t value) [private]
Definition at line 382 of file eh-frame.cc.
                                               {
  do {
    uint8_t chunk = value & 0x7F;
    value >>= 7;
    if (value != 0) chunk |= 0x80;
    WriteByte(chunk);
  } while (value != 0);
}
References v8::internal::value, and WriteByte().
Referenced by RecordRegisterFollowsInitialRule(), RecordRegisterNotModified(), RecordRegisterSavedToStack(), SetBaseAddressOffset(), SetBaseAddressRegister(), SetBaseAddressRegisterAndOffset(), WriteCie(), and WriteReturnAddressRegisterCode().
Member Data Documentation
base_offset_
int v8::internal::EhFrameWriter::base_offset_ [private]
Definition at line 209 of file eh-frame.h.
Referenced by SetBaseAddressOffset(), and SetBaseAddressRegisterAndOffset().
base_register_
Register v8::internal::EhFrameWriter::base_register_ [private]
Definition at line 208 of file eh-frame.h.
Referenced by SetBaseAddressRegister(), and SetBaseAddressRegisterAndOffset().
cie_size_
int v8::internal::EhFrameWriter::cie_size_ [private]
Definition at line 205 of file eh-frame.h.
Referenced by Finish(), WriteCie(), WriteEhFrameHdr(), and WriteFdeHeader().
eh_frame_buffer_
ZoneVector<uint8_t> v8::internal::EhFrameWriter::eh_frame_buffer_ [private]
Definition at line 210 of file eh-frame.h.
Referenced by GetEhFrame(), and Initialize().
kInt32Placeholder
STATIC_CONST_MEMBER_DEFINITION const uint32_t v8::internal::EhFrameWriter::kInt32Placeholder = 0xdeadc0de [static], [private]
Definition at line 136 of file eh-frame.h.
Referenced by WriteCie(), and WriteFdeHeader().
last_pc_offset_
int v8::internal::EhFrameWriter::last_pc_offset_ [private]
Definition at line 206 of file eh-frame.h.
Referenced by AdvanceLocation().
writer_state_
InternalState v8::internal::EhFrameWriter::writer_state_ [private]
Definition at line 207 of file eh-frame.h.
Referenced by AdvanceLocation(), Finish(), GetEhFrame(), Initialize(), RecordRegisterFollowsInitialRule(), RecordRegisterNotModified(), RecordRegisterSavedToStack(), SetBaseAddressOffset(), SetBaseAddressRegister(), SetBaseAddressRegisterAndOffset(), WriteEhFrameHdr(), and WritePaddingToAlignedSize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/eh-frame.h
/mnt/V8SourceCode/src/diagnostics/arm/eh-frame-arm.cc
/mnt/V8SourceCode/src/diagnostics/arm64/eh-frame-arm64.cc
/mnt/V8SourceCode/src/diagnostics/eh-frame.cc
/mnt/V8SourceCode/src/diagnostics/ppc/eh-frame-ppc.cc
/mnt/V8SourceCode/src/diagnostics/s390/eh-frame-s390.cc
/mnt/V8SourceCode/src/diagnostics/x64/eh-frame-x64.cc