v8::internal::wasm::ModuleDecoder Class Reference
#include <module-decoder.h>
Public Member Functions
ModuleDecoder (WasmEnabledFeatures enabled_features, WasmDetectedFeatures *detected_features)
~ModuleDecoder ()
void DecodeModuleHeader (base::Vector< const uint8_t > bytes)
void DecodeSection (SectionCode section_code, base::Vector< const uint8_t > bytes, uint32_t offset)
void StartCodeSection (WireBytesRef section_bytes)
bool CheckFunctionsCount (uint32_t functions_count, uint32_t error_offset)
void DecodeFunctionBody (uint32_t index, uint32_t size, uint32_t offset)
ModuleResult FinishDecoding ()
const std::shared_ptr< WasmModule > & shared_module () const
WasmModule * module () const
bool ok () const
Static Public Member Functions
static size_t IdentifyUnknownSection (ModuleDecoder *decoder, base::Vector< const uint8_t > bytes, uint32_t offset, SectionCode *result)
Private Attributes
std::unique_ptr< ModuleDecoderImpl > impl_
Detailed Description
Definition at line 167 of file module-decoder.h.
Constructor & Destructor Documentation
ModuleDecoder()
v8::internal::wasm::ModuleDecoder::ModuleDecoder (WasmEnabledFeatures enabled_features, WasmDetectedFeatures * detected_features) [explicit]
Definition at line 142 of file module-decoder.cc.
    : impl_(std::make_unique<ModuleDecoderImpl>(
          enabled_features, base::Vector<const uint8_t>{}, kWasmOrigin,
          detected_features)) {}
 ModuleDecoder()
v8::internal::wasm::ModuleDecoder::~ModuleDecoder () [default]
Member Function Documentation
CheckFunctionsCount()
bool v8::internal::wasm::ModuleDecoder::CheckFunctionsCount (uint32_t functions_count, uint32_t error_offset)
Definition at line 173 of file module-decoder.cc.
                                                               {
  return impl_->CheckFunctionsCount(functions_count, error_offset);
}
References impl_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
DecodeFunctionBody()
void v8::internal::wasm::ModuleDecoder::DecodeFunctionBody (uint32_t index, uint32_t size, uint32_t offset)
Definition at line 164 of file module-decoder.cc.
                                                        {
  impl_->DecodeFunctionBody(index, length, offset);
}
References impl_, v8::internal::index, and v8::internal::length.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody().
DecodeModuleHeader()
void v8::internal::wasm::ModuleDecoder::DecodeModuleHeader (base::Vector< const uint8_t > bytes)
Definition at line 154 of file module-decoder.cc.
                                                                      {
  impl_->DecodeModuleHeader(bytes);
}
References impl_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessModuleHeader().
DecodeSection()
void v8::internal::wasm::ModuleDecoder::DecodeSection (SectionCode section_code, base::Vector< const uint8_t > bytes, uint32_t offset)
Definition at line 158 of file module-decoder.cc.
                                                   {
  impl_->DecodeSection(section_code, bytes, offset);
}
References impl_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessSection().
FinishDecoding()
ModuleResult v8::internal::wasm::ModuleDecoder::FinishDecoding ()
Definition at line 178 of file module-decoder.cc.
{ return impl_->FinishDecoding(); }
References impl_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream().
IdentifyUnknownSection()
size_t v8::internal::wasm::ModuleDecoder::IdentifyUnknownSection (ModuleDecoder * decoder, base::Vector< const uint8_t > bytes, uint32_t offset, SectionCode * result) [static]
Definition at line 180 of file module-decoder.cc.
                                                                  {
  if (!decoder->ok()) return 0;
  decoder->impl_->Reset(bytes, offset);
  *result =
      IdentifyUnknownSectionInternal(decoder->impl_.get(), ITracer::NoTrace);
  return decoder->impl_->pc() - bytes.begin();
}
References v8::base::Vector< T >::begin(), v8::internal::wasm::IdentifyUnknownSectionInternal(), impl_, v8::internal::wasm::ITracer::NoTrace, ok(), and v8::base::internal::result.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessSection().
module()
WasmModule* v8::internal::wasm::ModuleDecoder::module () const [inline]
Definition at line 188 of file module-decoder.h.
{ return shared_module().get(); }
References shared_module().
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessFunctionBody().
ok()
bool v8::internal::wasm::ModuleDecoder::ok () const
Definition at line 191 of file module-decoder.cc.
{ return impl_->ok(); }
References impl_.
Referenced by IdentifyUnknownSection(), v8::internal::wasm::AsyncStreamingProcessor::ProcessModuleHeader(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessSection().
shared_module()
const std::shared_ptr< WasmModule > & v8::internal::wasm::ModuleDecoder::shared_module () const
Definition at line 150 of file module-decoder.cc.
                                                                    {
  return impl_->shared_module();
}
References impl_.
Referenced by module(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
StartCodeSection()
void v8::internal::wasm::ModuleDecoder::StartCodeSection (WireBytesRef section_bytes)
Definition at line 169 of file module-decoder.cc.
                                                               {
  impl_->StartCodeSection(section_bytes);
}
References impl_.
Referenced by v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
Member Data Documentation
impl_
std::unique_ptr<ModuleDecoderImpl> v8::internal::wasm::ModuleDecoder::impl_ [private]
Definition at line 202 of file module-decoder.h.
Referenced by CheckFunctionsCount(), DecodeFunctionBody(), DecodeModuleHeader(), DecodeSection(), FinishDecoding(), IdentifyUnknownSection(), ok(), shared_module(), and StartCodeSection().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/module-decoder.h
/mnt/V8SourceCode/src/wasm/module-decoder.cc