v8::internal::Profiler Class Reference
Public Member Functions
Profiler (Isolate *isolate)
void Engage ()
void Disengage ()
void Insert (TickSample *sample)
void Run () override
Private Member Functions
bool Remove (TickSample *sample)
int Succ (int index)
Private Attributes
Isolate * isolate_
TickSample buffer_ [kBufferSize]
int head_
base::Atomic32 tail_
base::Atomic32 overflow_
base::Semaphore buffer_semaphore_
base::Atomic32 running_
Static Private Attributes
static const int kBufferSize = 128
Additional Inherited Members
Detailed Description
Definition at line 1063 of file log.cc.
Constructor & Destructor Documentation
Profiler()
v8::internal::Profiler::Profiler (Isolate * isolate) [explicit]
Definition at line 1163 of file log.cc.
    : base::Thread(Options("v8:Profiler")),
      isolate_(isolate),
      head_(0),
      buffer_semaphore_(0) {
  base::Relaxed_Store(&tail_, 0);
  base::Relaxed_Store(&overflow_, false);
  base::Relaxed_Store(&running_, 0);
}
References overflow_, v8::base::Relaxed_Store(), running_, and tail_.
Member Function Documentation
Disengage()
void v8::internal::Profiler::Disengage ()
Definition at line 1193 of file log.cc.
                         {
  // Stop receiving ticks.
  isolate_->v8_file_logger()->ticker_->ClearProfiler();
  // Terminate the worker thread by setting running_ to false,
  // inserting a fake element in the queue and then wait for
  // the thread to terminate.
  base::Relaxed_Store(&running_, 0);
  TickSample sample;
  Insert(&sample);
  Join();
  LOG(isolate_, UncheckedStringEvent("profiler", "end"));
}
References Insert(), isolate_, v8::base::Thread::Join(), LOG, v8::base::Relaxed_Store(), running_, v8::internal::V8FileLogger::ticker_, and v8::internal::Isolate::v8_file_logger().
Engage()
void v8::internal::Profiler::Engage ()
Definition at line 1173 of file log.cc.
                      {
  std::vector<base::OS::SharedLibraryAddress> addresses =
      base::OS::GetSharedLibraryAddresses();
  for (const auto& address : addresses) {
    LOG(isolate_, SharedLibraryEvent(address.library_path, address.start,
                                     address.end, address.aslr_slide));
  }
  LOG(isolate_, SharedLibraryEnd());
  // Start thread processing the profiler buffer.
  base::Relaxed_Store(&running_, 1);
  CHECK(Start());
  // Register to get ticks.
  V8FileLogger* logger = isolate_->v8_file_logger();
  logger->ticker_->SetProfiler(this);
  LOG(isolate_, ProfilerBeginEvent());
}
References CHECK, v8::base::OS::GetSharedLibraryAddresses(), isolate_, LOG, v8::base::Relaxed_Store(), running_, v8::base::Thread::Start(), v8::internal::V8FileLogger::ticker_, and v8::internal::Isolate::v8_file_logger().
Insert()
void v8::internal::Profiler::Insert (TickSample * sample) [inline]
Definition at line 1070 of file log.cc.
                                  {
    if (Succ(head_) == static_cast<int>(base::Acquire_Load(&tail_))) {
      base::Relaxed_Store(&overflow_, true);
    } else {
      buffer_[head_] = *sample;
      head_ = Succ(head_);
      buffer_semaphore_.Signal(); // Tell we have an element.
    }
  }
References v8::base::Acquire_Load(), buffer_, buffer_semaphore_, head_, overflow_, v8::base::Relaxed_Store(), v8::base::Semaphore::Signal(), Succ(), and tail_.
Referenced by Disengage(), and v8::internal::Ticker::SampleStack().
Remove()
bool v8::internal::Profiler::Remove (TickSample * sample) [inline], [private]
Definition at line 1084 of file log.cc.
                                  {
    buffer_semaphore_.Wait(); // Wait for an element.
    *sample = buffer_[base::Relaxed_Load(&tail_)];
    bool result = base::Relaxed_Load(&overflow_);
    base::Release_Store(
        &tail_, static_cast<base::Atomic32>(Succ(base::Relaxed_Load(&tail_))));
    base::Relaxed_Store(&overflow_, false);
    return result;
  }
References buffer_, buffer_semaphore_, overflow_, v8::base::Relaxed_Load(), v8::base::Relaxed_Store(), v8::base::Release_Store(), v8::base::internal::result, Succ(), tail_, and v8::base::Semaphore::Wait().
Referenced by Run().
Run()
void v8::internal::Profiler::Run () [override], [virtual]
Implements v8::base::Thread.
Definition at line 1208 of file log.cc.
                   {
  TickSample sample;
  bool overflow = Remove(&sample);
  while (base::Relaxed_Load(&running_)) {
    LOG(isolate_, TickEvent(&sample, overflow));
    overflow = Remove(&sample);
  }
}
References isolate_, LOG, v8::internal::overflow, v8::base::Relaxed_Load(), Remove(), and running_.
Succ()
int v8::internal::Profiler::Succ (int index) [inline], [private]
Definition at line 1095 of file log.cc.
{ return (index + 1) % kBufferSize; }
References v8::internal::index, and kBufferSize.
Referenced by Insert(), and Remove().
Member Data Documentation
buffer_
TickSample v8::internal::Profiler::buffer_[kBufferSize] [private]
Definition at line 1101 of file log.cc.
Referenced by Insert(), and Remove().
buffer_semaphore_
base::Semaphore v8::internal::Profiler::buffer_semaphore_ [private]
Definition at line 1106 of file log.cc.
Referenced by Insert(), and Remove().
head_
int v8::internal::Profiler::head_ [private]
Definition at line 1102 of file log.cc.
Referenced by Insert().
isolate_
Isolate* v8::internal::Profiler::isolate_ [private]
Definition at line 1097 of file log.cc.
Referenced by Disengage(), Engage(), and Run().
kBufferSize
const int v8::internal::Profiler::kBufferSize = 128 [static], [private]
Definition at line 1100 of file log.cc.
Referenced by Succ().
overflow_
base::Atomic32 v8::internal::Profiler::overflow_ [private]
Definition at line 1104 of file log.cc.
Referenced by Insert(), Profiler(), and Remove().
running_
base::Atomic32 v8::internal::Profiler::running_ [private]
Definition at line 1109 of file log.cc.
Referenced by Disengage(), Engage(), Profiler(), and Run().
tail_
base::Atomic32 v8::internal::Profiler::tail_ [private]
Definition at line 1103 of file log.cc.
Referenced by Insert(), Profiler(), and Remove().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/log.cc