v8::internal::ICUTimezoneCache Class Reference
Public Member Functions
ICUTimezoneCache ()
~ICUTimezoneCache () override
const char * LocalTimezone (double time_ms) override
double DaylightSavingsOffset (double time_ms) override
double LocalTimeOffset (double time_ms, bool is_utc) override
void Clear (TimeZoneDetection time_zone_detection) override
Private Member Functions
icu::TimeZone * GetTimeZone ()
bool GetOffsets (double time_ms, bool is_utc, int32_t *raw_offset, int32_t *dst_offset)
Private Attributes
icu::TimeZone * timezone_
std::string timezone_name_
std::string dst_timezone_name_
Additional Inherited Members
Detailed Description
Definition at line 2683 of file intl-objects.cc.
Constructor & Destructor Documentation
ICUTimezoneCache()
v8::internal::ICUTimezoneCache::ICUTimezoneCache () [inline]
Definition at line 2685 of file intl-objects.cc.
: timezone_(nullptr) { Clear(TimeZoneDetection::kSkip); }
References Clear(), and v8::base::TimezoneCache::kSkip.
 ICUTimezoneCache()
v8::internal::ICUTimezoneCache::~ICUTimezoneCache () [inline], [override]
Definition at line 2687 of file intl-objects.cc.
{ Clear(TimeZoneDetection::kSkip); }
References Clear(), and v8::base::TimezoneCache::kSkip.
Member Function Documentation
Clear()
void v8::internal::ICUTimezoneCache::Clear (TimeZoneDetection time_zone_detection) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 2760 of file intl-objects.cc.
                                                                  {
  delete timezone_;
  timezone_ = nullptr;
  timezone_name_.clear();
  dst_timezone_name_.clear();
  if (time_zone_detection == TimeZoneDetection::kRedetect) {
    icu::TimeZone::adoptDefault(icu::TimeZone::detectHostTimeZone());
  }
}
References dst_timezone_name_, v8::base::TimezoneCache::kRedetect, timezone_, and timezone_name_.
Referenced by ICUTimezoneCache(), and ~ICUTimezoneCache().
DaylightSavingsOffset()
double v8::internal::ICUTimezoneCache::DaylightSavingsOffset (double time_ms) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 2748 of file intl-objects.cc.
                                                             {
  int32_t raw_offset, dst_offset;
  if (!GetOffsets(time_ms, true, &raw_offset, &dst_offset)) return 0;
  return dst_offset;
}
References GetOffsets().
Referenced by LocalTimezone().
GetOffsets()
bool v8::internal::ICUTimezoneCache::GetOffsets (double time_ms, bool is_utc, int32_t * raw_offset, int32_t * dst_offset) [private]
Definition at line 2731 of file intl-objects.cc.
                                                                            {
  UErrorCode status = U_ZERO_ERROR;
  if (is_utc) {
    GetTimeZone()->getOffset(time_ms, false, *raw_offset, *dst_offset, status);
  } else {
    // Note that casting TimeZone to BasicTimeZone is safe because we know that
    // icu::TimeZone used here is a BasicTimeZone.
    static_cast<const icu::BasicTimeZone*>(GetTimeZone())
        ->getOffsetFromLocal(time_ms, UCAL_TZ_LOCAL_FORMER,
                             UCAL_TZ_LOCAL_FORMER, *raw_offset, *dst_offset,
                             status);
  }
  return U_SUCCESS(status);
}
References GetTimeZone(), and v8::internal::status.
Referenced by DaylightSavingsOffset(), and LocalTimeOffset().
GetTimeZone()
icu::TimeZone * v8::internal::ICUTimezoneCache::GetTimeZone () [private]
Definition at line 2724 of file intl-objects.cc.
                                           {
  if (timezone_ == nullptr) {
    timezone_ = icu::TimeZone::createDefault();
  }
  return timezone_;
}
References timezone_.
Referenced by GetOffsets(), and LocalTimezone().
LocalTimeOffset()
double v8::internal::ICUTimezoneCache::LocalTimeOffset (double time_ms, bool is_utc) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 2754 of file intl-objects.cc.
                                                                    {
  int32_t raw_offset, dst_offset;
  if (!GetOffsets(time_ms, is_utc, &raw_offset, &dst_offset)) return 0;
  return raw_offset + dst_offset;
}
References GetOffsets().
LocalTimezone()
const char * v8::internal::ICUTimezoneCache::LocalTimezone (double time_ms) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 2709 of file intl-objects.cc.
                                                          {
  bool is_dst = DaylightSavingsOffset(time_ms) != 0;
  std::string* name = is_dst ? &dst_timezone_name_ : &timezone_name_;
  if (name->empty()) {
    icu::UnicodeString result;
    GetTimeZone()->getDisplayName(is_dst, icu::TimeZone::LONG, result);
    result += '\0';
    icu::StringByteSink<std::string> byte_sink(name);
    result.toUTF8(byte_sink);
  }
  DCHECK(!name->empty());
  return name->c_str();
}
References DaylightSavingsOffset(), v8::internal::DCHECK(), dst_timezone_name_, GetTimeZone(), v8::internal::name, v8::base::internal::result, v8::internal::string, and timezone_name_.
Member Data Documentation
dst_timezone_name_
std::string v8::internal::ICUTimezoneCache::dst_timezone_name_ [private]
Definition at line 2706 of file intl-objects.cc.
Referenced by Clear(), and LocalTimezone().
timezone_
icu::TimeZone* v8::internal::ICUTimezoneCache::timezone_ [private]
Definition at line 2703 of file intl-objects.cc.
Referenced by Clear(), and GetTimeZone().
timezone_name_
std::string v8::internal::ICUTimezoneCache::timezone_name_ [private]
Definition at line 2705 of file intl-objects.cc.
Referenced by Clear(), and LocalTimezone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/intl-objects.cc