v8::internal::TracedHandles Class Reference
#include <traced-handles.h>
Public Types
enum class MarkMode : uint8_t { kOnlyYoung
, kAll
 }
using NodeBounds = std::vector< std::pair< const void *, const void * > >
Public Member Functions
TracedHandles (Isolate *)
~TracedHandles ()
TracedHandles (const TracedHandles &)=delete
TracedHandles & operator= (const TracedHandles &)=delete
FullObjectSlot Create (Address value, Address *slot, TracedReferenceStoreMode store_mode, TracedReferenceHandling reference_handling)
const NodeBounds GetNodeBounds () const
void SetIsMarking (bool)
void SetIsSweepingOnMutatorThread (bool)
void UpdateListOfYoungNodes ()
void DeleteEmptyBlocks ()
void ResetDeadNodes (WeakSlotCallbackWithHeap should_reset_handle)
void ResetYoungDeadNodes (WeakSlotCallbackWithHeap should_reset_handle)
void ComputeWeaknessForYoungObjects ()
void ProcessWeakYoungObjects (RootVisitor *v, WeakSlotCallbackWithHeap should_reset_handle)
void Iterate (RootVisitor *)
void IterateYoung (RootVisitor *)
void IterateYoungRoots (RootVisitor *)
void IterateAndMarkYoungRootsWithOldHosts (RootVisitor *)
void IterateYoungRootsWithOldHostsForTesting (RootVisitor *)
size_t used_node_count () const
size_t total_size_bytes () const
size_t used_size_bytes () const
bool HasYoung () const
Static Public Member Functions
static void Destroy (Address *location)
static void Copy (const Address *const *from, Address **to)
static void Move (Address **from, Address **to)
static Tagged< Object > Mark (Address *location, MarkMode mark_mode)
static Tagged< Object > MarkConservatively (Address *inner_location, Address *traced_node_block_base, MarkMode mark_mode)
static bool IsValidInUseNode (const Address *location)
Private Member Functions
std::pair< TracedNodeBlock *, TracedNode * > AllocateNode ()
V8_NOINLINE V8_PRESERVE_MOST void RefillUsableNodeBlocks ()
void FreeNode (TracedNode *node, Address zap_value)
bool NeedsToBeRemembered (Tagged< Object > value, TracedNode *node, Address *slot, TracedReferenceStoreMode store_mode) const
bool NeedsTrackingInYoungNodes (Tagged< Object > object, TracedNode *node) const
CppHeap * GetCppHeapIfUnifiedYoungGC (Isolate *isolate) const
bool IsCppGCHostOld (CppHeap &cpp_heap, Address host) const
void Destroy (TracedNodeBlock &node_block, TracedNode &node)
void Copy (const TracedNode &from_node, Address **to)
void Move (TracedNode &from_node, Address **from, Address **to)
bool SupportsClearingWeakNonLiveWrappers ()
Private Attributes
TracedNodeBlock::OverallList blocks_
size_t num_blocks_ = 0
TracedNodeBlock::UsableList usable_blocks_
TracedNodeBlock::YoungList young_blocks_
size_t num_young_blocks_ {0}
std::vector< TracedNodeBlock * > empty_blocks_
Isolate * isolate_
bool is_marking_ = false
bool is_sweeping_on_mutator_thread_ = false
size_t used_nodes_ = 0
size_t block_size_bytes_ = 0
bool disable_block_handling_on_free_ = false
Detailed Description
Definition at line 275 of file traced-handles.h.
Member Typedef Documentation
NodeBounds
using v8::internal::TracedHandles::NodeBounds = std::vector<std::pair<const void*, const void*> >
Definition at line 300 of file traced-handles.h.
Member Enumeration Documentation
MarkMode
enum v8::internal::TracedHandles::MarkMode : uint8_t [strong]
Enumerator
kOnlyYoung
kAll
Definition at line 277 of file traced-handles.h.
: uint8_t { kOnlyYoung, kAll };
Constructor & Destructor Documentation
TracedHandles() [1/2]
v8::internal::TracedHandles::TracedHandles (Isolate * isolate) [explicit]
Definition at line 149 of file traced-handles.cc.
: isolate_(isolate) {}
 TracedHandles()
v8::internal::TracedHandles::~TracedHandles ()
Definition at line 151 of file traced-handles.cc.
                              {
  size_t block_size_bytes = 0;
  while (!blocks_.empty()) {
    auto* block = blocks_.Front();
    blocks_.PopFront();
    block_size_bytes += block->size_bytes();
    TracedNodeBlock::Delete(block);
  }
  for (auto* block : empty_blocks_) {
    block_size_bytes += block->size_bytes();
    TracedNodeBlock::Delete(block);
  }
  USE(block_size_bytes);
  DCHECK_EQ(block_size_bytes, block_size_bytes_);
}
References block_size_bytes_, blocks_, DCHECK_EQ, v8::internal::TracedNodeBlock::Delete(), v8::base::DoublyThreadedList< T, DTLTraits >::empty(), empty_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::Front(), v8::base::DoublyThreadedList< T, DTLTraits >::PopFront(), and USE.
TracedHandles() [2/2]
v8::internal::TracedHandles::TracedHandles (const TracedHandles &) [delete]
Member Function Documentation
AllocateNode()
std::pair< TracedNodeBlock *, TracedNode * > v8::internal::TracedHandles::AllocateNode () [inline], [private]
Definition at line 27 of file traced-handles-inl.h.
                                                                   {
  if (V8_UNLIKELY(usable_blocks_.empty())) {
    RefillUsableNodeBlocks();
  }
  TracedNodeBlock* block = usable_blocks_.Front();
  auto* node = block->AllocateNode();
  DCHECK(node->IsMetadataCleared());
  if (V8_UNLIKELY(block->IsFull())) {
    usable_blocks_.Remove(block);
  }
  used_nodes_++;
  return std::make_pair(block, node);
}
References v8::internal::TracedNodeBlock::AllocateNode(), v8::internal::DCHECK(), v8::base::DoublyThreadedList< T, DTLTraits >::empty(), v8::base::DoublyThreadedList< T, DTLTraits >::Front(), v8::internal::TracedNodeBlock::IsFull(), RefillUsableNodeBlocks(), v8::base::DoublyThreadedList< T, DTLTraits >::Remove(), usable_blocks_, used_nodes_, and V8_UNLIKELY.
Referenced by Create().
ComputeWeaknessForYoungObjects()
void v8::internal::TracedHandles::ComputeWeaknessForYoungObjects ()
Definition at line 514 of file traced-handles.cc.
                                                   {
  if (!SupportsClearingWeakNonLiveWrappers()) {
    return;
  }
  ComputeWeaknessProcessor job(isolate_->heap(), young_blocks_,
                               num_young_blocks_);
  job.Run();
}
References v8::internal::Isolate::heap(), isolate_, num_young_blocks_, SupportsClearingWeakNonLiveWrappers(), and young_blocks_.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), and v8::internal::MinorMarkSweepCollector::MarkRoots().
Copy() [1/2]
void v8::internal::TracedHandles::Copy (const Address *const * from, Address ** to) [static]
Definition at line 767 of file traced-handles.cc.
                                                                 {
  DCHECK_NOT_NULL(*from);
  DCHECK_NULL(*to);
  const TracedNode* from_node = TracedNode::FromLocation(*from);
  const auto& node_block = TracedNodeBlock::From(*from_node);
  auto& traced_handles = node_block.traced_handles();
  traced_handles.Copy(*from_node, to);
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::TracedNodeBlock::From(), and v8::internal::TracedNode::FromLocation().
Referenced by v8::internal::CopyTracedReference().
Copy() [2/2]
void v8::internal::TracedHandles::Copy (const TracedNode & from_node, Address ** to) [private]
Definition at line 198 of file traced-handles.cc.
                                                                  {
  DCHECK_NE(kGlobalHandleZapValue, from_node.raw_object());
  FullObjectSlot o =
      Create(from_node.raw_object(), reinterpret_cast<Address*>(to),
             TracedReferenceStoreMode::kAssigningStore,
             TracedReferenceHandling::kDefault);
  SetSlotThreadSafe(to, o.location());
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    Object::ObjectVerify(Tagged<Object>(**to), isolate_);
  }
#endif // VERIFY_HEAP
}
References Create(), DCHECK_NE, isolate_, v8::internal::kAssigningStore, v8::internal::kDefault, v8::internal::kGlobalHandleZapValue, v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::location(), v8::internal::TracedNode::raw_object(), v8::internal::SetSlotThreadSafe(), and v8::internal::v8_flags.
Create()
FullObjectSlot v8::internal::TracedHandles::Create (Address value, Address * slot, TracedReferenceStoreMode store_mode, TracedReferenceHandling reference_handling) [inline]
Definition at line 106 of file traced-handles-inl.h.
                                                {
  DCHECK_NOT_NULL(slot);
  Tagged<Object> object(value);
  auto [block, node] = AllocateNode();
  const bool needs_young_bit_update = NeedsTrackingInYoungNodes(object, node);
  const bool has_old_host = NeedsToBeRemembered(object, node, slot, store_mode);
  const bool needs_black_allocation =
      is_marking_ && store_mode != TracedReferenceStoreMode::kInitializingStore;
  const bool is_droppable =
      reference_handling == TracedReferenceHandling::kDroppable;
  auto result_slot =
      node->Publish(object, needs_young_bit_update, needs_black_allocation,
                    has_old_host, is_droppable);
  // Write barrier and young node tracking may be reordered, so move them below
  // `Publish()`.
  if (needs_young_bit_update && !block->InYoungList()) {
    young_blocks_.PushFront(block);
    DCHECK(block->InYoungList());
    num_young_blocks_++;
  }
  if (needs_black_allocation) {
    WriteBarrier::MarkingFromTracedHandle(object);
  }
#ifdef VERIFY_HEAP
  if (i::v8_flags.verify_heap) {
    Object::ObjectVerify(*result_slot, isolate_);
  }
#endif // VERIFY_HEAP
  return result_slot;
}
References AllocateNode(), v8::internal::DCHECK(), DCHECK_NOT_NULL, is_marking_, isolate_, v8::internal::kDroppable, v8::internal::kInitializingStore, v8::internal::WriteBarrier::MarkingFromTracedHandle(), NeedsToBeRemembered(), NeedsTrackingInYoungNodes(), num_young_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), v8::internal::v8_flags, v8::internal::value, and young_blocks_.
Referenced by Copy(), and v8::internal::GlobalizeTracedReference().
DeleteEmptyBlocks()
void v8::internal::TracedHandles::DeleteEmptyBlocks ()
Definition at line 305 of file traced-handles.cc.
                                      {
  // Keep one node block around for fast allocation/deallocation patterns.
  if (empty_blocks_.size() <= 1) return;
  for (size_t i = 1; i < empty_blocks_.size(); i++) {
    auto* block = empty_blocks_[i];
    DCHECK(block->IsEmpty());
    DCHECK_GE(block_size_bytes_, block->size_bytes());
    block_size_bytes_ -= block->size_bytes();
    TracedNodeBlock::Delete(block);
  }
  empty_blocks_.resize(1);
  empty_blocks_.shrink_to_fit();
}
References block_size_bytes_, v8::internal::DCHECK(), DCHECK_GE, v8::internal::TracedNodeBlock::Delete(), empty_blocks_, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::CppHeap::FinishSweepingIfRunning().
Destroy() [1/2]
void v8::internal::TracedHandles::Destroy (Address * location) [static]
Definition at line 757 of file traced-handles.cc.
                                             {
  if (!location) return;
  auto* node = TracedNode::FromLocation(location);
  auto& node_block = TracedNodeBlock::From(*node);
  auto& traced_handles = node_block.traced_handles();
  traced_handles.Destroy(node_block, *node);
}
References v8::internal::TracedNodeBlock::From(), and v8::internal::TracedNode::FromLocation().
Referenced by v8::internal::DisposeTracedReference(), and Move().
Destroy() [2/2]
void v8::internal::TracedHandles::Destroy (TracedNodeBlock & node_block, TracedNode & node) [private]
Definition at line 167 of file traced-handles.cc.
                                                                         {
  DCHECK_IMPLIES(is_marking_, !is_sweeping_on_mutator_thread_);
  DCHECK_IMPLIES(is_sweeping_on_mutator_thread_, !is_marking_);
  // If sweeping on the mutator thread is running then the handle destruction
  // may be a result of a Reset() call from a destructor. The node will be
  // reclaimed on the next cycle.
  //
  // This allows v8::TracedReference::Reset() calls from destructors on
  // objects that may be used from stack and heap.
  if (is_sweeping_on_mutator_thread_) {
    return;
  }
  if (is_marking_) {
    // Incremental/concurrent marking is running.
    //
    // On-heap traced nodes are released in the atomic pause in
    // `ResetDeadNodes()` when they are discovered as not marked. Eagerly clear
    // out the object here to avoid needlessly marking it from this point on.
    // The node will be reclaimed on the next cycle.
    node.set_raw_object<AccessMode::ATOMIC>(kNullAddress);
    return;
  }
  // In case marking and sweeping are off, the handle may be freed immediately.
  // Note that this includes also the case when invoking the first pass
  // callbacks during the atomic pause which requires releasing a node fully.
  FreeNode(&node, kTracedHandleEagerResetZapValue);
}
References v8::internal::ATOMIC, DCHECK_IMPLIES, FreeNode(), is_marking_, is_sweeping_on_mutator_thread_, v8::internal::kNullAddress, v8::internal::kTracedHandleEagerResetZapValue, and v8::internal::TracedNode::set_raw_object().
FreeNode()
void v8::internal::TracedHandles::FreeNode (TracedNode * node, Address zap_value) [private]
Definition at line 123 of file traced-handles.cc.
                                                                {
  auto& block = TracedNodeBlock::From(*node);
  if (disable_block_handling_on_free_) {
    // The list of blocks and used nodes will be updated separately.
    block.FreeNode(node, zap_value);
    return;
  }
  if (V8_UNLIKELY(block.IsFull())) {
    DCHECK(!usable_blocks_.ContainsSlow(&block));
    usable_blocks_.PushFront(&block);
  }
  block.FreeNode(node, zap_value);
  if (block.IsEmpty()) {
    usable_blocks_.Remove(&block);
    blocks_.Remove(&block);
    if (block.InYoungList()) {
      young_blocks_.Remove(&block);
      DCHECK(!block.InYoungList());
      num_young_blocks_--;
    }
    num_blocks_--;
    empty_blocks_.push_back(&block);
  }
  used_nodes_--;
}
References blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::ContainsSlow(), v8::internal::DCHECK(), disable_block_handling_on_free_, empty_blocks_, v8::internal::TracedNodeBlock::From(), num_blocks_, num_young_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), v8::base::DoublyThreadedList< T, DTLTraits >::Remove(), usable_blocks_, used_nodes_, V8_UNLIKELY, and young_blocks_.
Referenced by Destroy(), ResetDeadNodes(), and ResetYoungDeadNodes().
GetCppHeapIfUnifiedYoungGC()
CppHeap * v8::internal::TracedHandles::GetCppHeapIfUnifiedYoungGC (Isolate * isolate) const [inline], [private]
Definition at line 47 of file traced-handles-inl.h.
                                                                         {
  // TODO(v8:13475) Consider removing this check when unified-young-gen becomes
  // default.
  if (!v8_flags.cppgc_young_generation) return nullptr;
  auto* cpp_heap = CppHeap::From(isolate->heap()->cpp_heap());
  if (cpp_heap && cpp_heap->generational_gc_supported()) return cpp_heap;
  return nullptr;
}
References v8::internal::Heap::cpp_heap(), v8::internal::CppHeap::From(), v8::internal::Isolate::heap(), and v8::internal::v8_flags.
Referenced by Move(), NeedsToBeRemembered(), and UpdateListOfYoungNodes().
GetNodeBounds()
const TracedHandles::NodeBounds v8::internal::TracedHandles::GetNodeBounds () const
Definition at line 259 of file traced-handles.cc.
                                                                 {
  TracedHandles::NodeBounds block_bounds;
  block_bounds.reserve(num_blocks_);
  for (const auto* block : blocks_) {
    block_bounds.push_back(
        {block->nodes_begin_address(), block->nodes_end_address()});
  }
  std::sort(block_bounds.begin(), block_bounds.end(),
            [](const auto& pair1, const auto& pair2) {
              return pair1.first < pair2.first;
            });
  return block_bounds;
}
References blocks_, num_blocks_, and v8::base::sort().
HasYoung()
bool v8::internal::TracedHandles::HasYoung () const
Definition at line 844 of file traced-handles.cc.
{ return !young_blocks_.empty(); }
References v8::base::DoublyThreadedList< T, DTLTraits >::empty(), and young_blocks_.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
IsCppGCHostOld()
bool v8::internal::TracedHandles::IsCppGCHostOld (CppHeap & cpp_heap, Address host) const [inline], [private]
Definition at line 56 of file traced-handles-inl.h.
                                                                        {
  DCHECK(host);
  DCHECK(cpp_heap.generational_gc_supported());
  auto* host_ptr = reinterpret_cast<void*>(host);
  auto* page = cppgc::internal::BasePage::FromInnerAddress(&cpp_heap, host_ptr);
  // TracedReference may be created on stack, in which case assume it's young
  // and doesn't need to be remembered, since it'll anyway be scanned.
  if (!page) return false;
  return !page->ObjectHeaderFromInnerAddress(host_ptr).IsYoung();
}
References v8::internal::DCHECK(), cppgc::internal::BasePage::FromInnerAddress(), and cppgc::internal::HeapBase::generational_gc_supported().
Referenced by Move(), and NeedsToBeRemembered().
IsValidInUseNode()
bool v8::internal::TracedHandles::IsValidInUseNode (const Address * location) [static]
Definition at line 834 of file traced-handles.cc.
                                                            {
  const TracedNode* node = TracedNode::FromLocation(location);
  // This method is called after mark bits have been cleared.
  DCHECK(!node->markbit());
  CHECK_IMPLIES(node->is_in_use(), node->raw_object() != kGlobalHandleZapValue);
  CHECK_IMPLIES(!node->is_in_use(),
                node->raw_object() == kGlobalHandleZapValue);
  return node->is_in_use();
}
References CHECK_IMPLIES, v8::internal::DCHECK(), v8::internal::TracedNode::FromLocation(), v8::internal::TracedNode::is_in_use(), v8::internal::kGlobalHandleZapValue, v8::internal::TracedNode::markbit(), and v8::internal::TracedNode::raw_object().
Referenced by v8::internal::UnifiedHeapVerificationState::VerifyMarkedTracedReference().
Iterate()
void v8::internal::TracedHandles::Iterate (RootVisitor * visitor)
Definition at line 682 of file traced-handles.cc.
                                                {
  for (auto* block : blocks_) {
    for (auto* node : *block) {
      if (!node->is_in_use()) continue;
      visitor->VisitRootPointer(Root::kTracedHandles, nullptr,
                                node->location());
    }
  }
}
References blocks_, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), v8::internal::V8HeapExplorer::CollectTemporaryGlobalObjectsTags(), v8::internal::Heap::IterateRoots(), and v8::internal::Heap::IterateWeakGlobalHandles().
IterateAndMarkYoungRootsWithOldHosts()
void v8::internal::TracedHandles::IterateAndMarkYoungRootsWithOldHosts (RootVisitor * visitor)
Definition at line 721 of file traced-handles.cc.
                                                                             {
  DCHECK(!is_marking_);
  for (auto* block : young_blocks_) {
    for (auto* node : *block) {
      if (!node->is_in_young_list()) continue;
      DCHECK(node->is_in_use());
      if (!node->has_old_host()) continue;
      if (node->is_weak()) continue;
      node->set_markbit();
      CHECK(HeapLayout::InYoungGeneration(node->object()));
      visitor->VisitRootPointer(Root::kTracedHandles, nullptr,
                                node->location());
    }
  }
}
References CHECK, v8::internal::DCHECK(), v8::internal::HeapLayout::InYoungGeneration(), is_marking_, v8::internal::RootVisitor::VisitRootPointer(), and young_blocks_.
Referenced by v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles().
IterateYoung()
void v8::internal::TracedHandles::IterateYoung (RootVisitor * visitor)
Definition at line 693 of file traced-handles.cc.
                                                     {
  for (auto* block : young_blocks_) {
    for (auto* node : *block) {
      if (!node->is_in_young_list()) continue;
      DCHECK(node->is_in_use());
      visitor->VisitRootPointer(Root::kTracedHandles, nullptr,
                                node->location());
    }
  }
}
References v8::internal::DCHECK(), v8::internal::RootVisitor::VisitRootPointer(), and young_blocks_.
IterateYoungRoots()
void v8::internal::TracedHandles::IterateYoungRoots (RootVisitor * visitor)
Definition at line 704 of file traced-handles.cc.
                                                          {
  DCHECK(!is_marking_);
  for (auto* block : young_blocks_) {
    DCHECK(block->InYoungList());
    for (auto* node : *block) {
      if (!node->is_in_young_list()) continue;
      DCHECK(node->is_in_use());
      if (node->is_weak()) continue;
      visitor->VisitRootPointer(Root::kTracedHandles, nullptr,
                                node->location());
    }
  }
}
References v8::internal::DCHECK(), is_marking_, v8::internal::RootVisitor::VisitRootPointer(), and young_blocks_.
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), and v8::internal::MinorMarkSweepCollector::MarkRootsFromTracedHandles().
IterateYoungRootsWithOldHostsForTesting()
void v8::internal::TracedHandles::IterateYoungRootsWithOldHostsForTesting (RootVisitor * visitor)
Definition at line 739 of file traced-handles.cc.
                          {
  DCHECK(!is_marking_);
  for (auto* block : young_blocks_) {
    for (auto* node : *block) {
      if (!node->is_in_young_list()) continue;
      DCHECK(node->is_in_use());
      if (!node->has_old_host()) continue;
      if (node->is_weak()) continue;
      visitor->VisitRootPointer(Root::kTracedHandles, nullptr,
                                node->location());
    }
  }
}
References v8::internal::DCHECK(), is_marking_, v8::internal::RootVisitor::VisitRootPointer(), and young_blocks_.
Mark()
Tagged< Object > v8::internal::TracedHandles::Mark (Address * location, MarkMode mark_mode) [static]
Definition at line 809 of file traced-handles.cc.
                                                                        {
  // The load synchronizes internal bitfields that are also read atomically
  // from the concurrent marker. The counterpart is `TracedNode::Publish()`.
  Tagged<Object> object =
      Tagged<Object>(reinterpret_cast<std::atomic<Address>*>(location)->load(
          std::memory_order_acquire));
  auto* node = TracedNode::FromLocation(location);
  DCHECK(node->is_in_use());
  return MarkObject(object, *node, mark_mode);
}
References v8::internal::DCHECK(), v8::internal::TracedNode::FromLocation(), v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), and v8::internal::Tagged< Object >.
Referenced by v8::internal::UnifiedHeapMarkingState::MarkAndPush().
MarkConservatively()
Tagged< Object > v8::internal::TracedHandles::MarkConservatively (Address * inner_location, Address * traced_node_block_base, MarkMode mark_mode) [static]
Definition at line 821 of file traced-handles.cc.
                        {
  // Compute the `TracedNode` address based on its inner pointer.
  const ptrdiff_t delta = reinterpret_cast<uintptr_t>(inner_location) -
                          reinterpret_cast<uintptr_t>(traced_node_block_base);
  const auto index = delta / sizeof(TracedNode);
  TracedNode& node =
      reinterpret_cast<TracedNode*>(traced_node_block_base)[index];
  if (!node.is_in_use()) return Smi::zero();
  return MarkObject(node.object(), node, mark_mode);
}
References v8::internal::index, v8::internal::TracedNode::is_in_use(), v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), v8::internal::TracedNode::object(), and v8::internal::Smi::zero().
Referenced by v8::internal::ConservativeTracedHandlesMarkingVisitor::VisitPointer().
Move() [1/2]
void v8::internal::TracedHandles::Move (Address ** from, Address ** to) [static]
Definition at line 778 of file traced-handles.cc.
                                                     {
  // Fast path for moving from an empty reference.
  if (!*from) {
    Destroy(*to);
    SetSlotThreadSafe(to, nullptr);
    return;
  }
  TracedNode* from_node = TracedNode::FromLocation(*from);
  auto& node_block = TracedNodeBlock::From(*from_node);
  auto& traced_handles = node_block.traced_handles();
  traced_handles.Move(*from_node, from, to);
}
References Destroy(), v8::internal::TracedNodeBlock::From(), v8::internal::TracedNode::FromLocation(), and v8::internal::SetSlotThreadSafe().
Referenced by v8::internal::MoveTracedReference().
Move() [2/2]
void v8::internal::TracedHandles::Move (TracedNode & from_node, Address ** from, Address ** to) [private]
Definition at line 212 of file traced-handles.cc.
                                                                            {
  DCHECK(from_node.is_in_use());
  // Deal with old "to".
  auto* to_node = TracedNode::FromLocation(*to);
  DCHECK_IMPLIES(*to, to_node->is_in_use());
  DCHECK_IMPLIES(*to, kGlobalHandleZapValue != to_node->raw_object());
  DCHECK_NE(kGlobalHandleZapValue, from_node.raw_object());
  if (*to) {
    auto& to_node_block = TracedNodeBlock::From(*to_node);
    Destroy(to_node_block, *to_node);
  }
  // Set "to" to "from".
  SetSlotThreadSafe(to, *from);
  to_node = &from_node;
  // Deal with new "to"
  DCHECK_NOT_NULL(*to);
  DCHECK_EQ(*from, *to);
  if (is_marking_) {
    // Write barrier needs to cover node as well as object.
    to_node->set_markbit();
    WriteBarrier::MarkingFromTracedHandle(to_node->object());
  } else if (auto* cpp_heap = GetCppHeapIfUnifiedYoungGC(isolate_)) {
    const bool object_is_young_and_not_yet_recorded =
        !from_node.has_old_host() &&
        HeapLayout::InYoungGeneration(from_node.object());
    if (object_is_young_and_not_yet_recorded &&
        IsCppGCHostOld(*cpp_heap, reinterpret_cast<Address>(to))) {
      DCHECK(from_node.is_in_young_list());
      from_node.set_has_old_host(true);
    }
  }
  SetSlotThreadSafe(from, nullptr);
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, DCHECK_NOT_NULL, Destroy(), v8::internal::TracedNodeBlock::From(), v8::internal::TracedNode::FromLocation(), GetCppHeapIfUnifiedYoungGC(), v8::internal::TracedNode::has_old_host(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::TracedNode::is_in_use(), v8::internal::TracedNode::is_in_young_list(), is_marking_, IsCppGCHostOld(), isolate_, v8::internal::kGlobalHandleZapValue, v8::internal::WriteBarrier::MarkingFromTracedHandle(), v8::internal::TracedNode::object(), v8::internal::TracedNode::raw_object(), v8::internal::TracedNode::set_has_old_host(), and v8::internal::SetSlotThreadSafe().
NeedsToBeRemembered()
bool v8::internal::TracedHandles::NeedsToBeRemembered (Tagged< Object > value, TracedNode * node, Address * slot, TracedReferenceStoreMode store_mode) const [inline], [private]
Definition at line 67 of file traced-handles-inl.h.
                                               {
  DCHECK(!node->has_old_host());
  auto* cpp_heap = GetCppHeapIfUnifiedYoungGC(isolate_);
  if (!cpp_heap) {
    return false;
  }
  if (store_mode == TracedReferenceStoreMode::kInitializingStore) {
    // Don't record initializing stores.
    return false;
  }
  if (is_marking_) {
    // If marking is in progress, the marking barrier will be issued later.
    return false;
  }
  if (!HeapLayout::InYoungGeneration(object)) {
    return false;
  }
  return IsCppGCHostOld(*cpp_heap, reinterpret_cast<Address>(slot));
}
References v8::internal::DCHECK(), GetCppHeapIfUnifiedYoungGC(), v8::internal::TracedNode::has_old_host(), v8::internal::HeapLayout::InYoungGeneration(), is_marking_, IsCppGCHostOld(), isolate_, and v8::internal::kInitializingStore.
Referenced by Create().
NeedsTrackingInYoungNodes()
bool v8::internal::TracedHandles::NeedsTrackingInYoungNodes (Tagged< Object > object, TracedNode * node) const [inline], [private]
Definition at line 41 of file traced-handles-inl.h.
                                                                      {
  DCHECK(!node->is_in_young_list());
  return HeapLayout::InYoungGeneration(object);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InYoungGeneration(), and v8::internal::TracedNode::is_in_young_list().
Referenced by Create().
operator=()
TracedHandles& v8::internal::TracedHandles::operator= (const TracedHandles &) [delete]
ProcessWeakYoungObjects()
void v8::internal::TracedHandles::ProcessWeakYoungObjects (RootVisitor * v, WeakSlotCallbackWithHeap should_reset_handle)
Definition at line 592 of file traced-handles.cc.
                                                                        {
  if (!SupportsClearingWeakNonLiveWrappers()) {
    return;
  }
  auto* heap = isolate_->heap();
  // ResetRoot() below should not trigger allocations in CppGC.
  if (auto* cpp_heap = CppHeap::From(heap->cpp_heap())) {
    cpp_heap->EnterDisallowGCScope();
    cpp_heap->EnterNoGCScope();
  }
#ifdef DEBUG
  size_t num_young_blocks = 0;
  for (auto it = young_blocks_.begin(); it != young_blocks_.end(); it++) {
    TracedNodeBlock* block = *it;
    DCHECK(block->InYoungList());
    DCHECK(!block->NeedsReprocessing());
    num_young_blocks++;
  }
  DCHECK_EQ(num_young_blocks_, num_young_blocks);
#endif
  disable_block_handling_on_free_ = true;
  ClearWeaknessProcessor job(young_blocks_, num_young_blocks_, heap, visitor,
                             should_reset_handle);
  job.Run();
  disable_block_handling_on_free_ = false;
  // Post processing on block level.
  for (auto it = young_blocks_.begin(); it != young_blocks_.end();) {
    TracedNodeBlock* block = *it;
    // Avoid iterator invalidation by incrementing iterator here before a block
    // is possible removed below.
    it++;
    DCHECK(block->InYoungList());
    // Freeing a node will not make the block fuller, so IsFull() should mean
    // that the block was already not usable before freeing.
    CHECK_IMPLIES(block->IsFull(), !usable_blocks_.Contains(block));
    if (!block->IsFull() && !block->IsEmpty()) {
      // A block is usable but may have been full before. Check if we need to
      // add it to the usable blocks.
      if (!usable_blocks_.Contains(block)) {
        DCHECK(!block->InUsableList());
        usable_blocks_.PushFront(block);
        DCHECK(block->InUsableList());
      }
    } else if (block->IsEmpty()) {
      // A non-empty block got empty during freeing. The block must not require
      // reprocessing which would mean that at least one node was not yet freed.
      DCHECK(!block->NeedsReprocessing());
      if (usable_blocks_.Contains(block)) {
        DCHECK(block->InUsableList());
        usable_blocks_.Remove(block);
        DCHECK(!block->InUsableList());
      }
      blocks_.Remove(block);
      DCHECK(block->InYoungList());
      young_blocks_.Remove(block);
      DCHECK(!block->InYoungList());
      num_young_blocks_--;
      empty_blocks_.push_back(block);
      num_blocks_--;
    }
    used_nodes_ -= block->ConsumeLocallyFreed();
    // Handle reprocessing of blocks because `TryReset()` was not able to reset
    // a node concurrently.
    if (!block->NeedsReprocessing()) {
      continue;
    }
    block->SetReprocessing(false);
    job.template ProcessBlock</*IsMainThread=*/true>(block);
    DCHECK(!block->NeedsReprocessing());
    // The nodes are fully freed and accounted but still reported as locally
    // freed as we reuse the processor.
    const auto locally_freed = block->ConsumeLocallyFreed();
    (void)locally_freed;
    DCHECK_GT(locally_freed, 0);
  }
  if (auto* cpp_heap = CppHeap::From(isolate_->heap()->cpp_heap())) {
    cpp_heap->LeaveNoGCScope();
    cpp_heap->LeaveDisallowGCScope();
  }
}
References v8::base::DoublyThreadedList< T, DTLTraits >::begin(), blocks_, CHECK_IMPLIES, v8::internal::TracedNodeBlock::ConsumeLocallyFreed(), v8::base::DoublyThreadedList< T, DTLTraits >::Contains(), v8::internal::Heap::cpp_heap(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, disable_block_handling_on_free_, empty_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::end(), v8::internal::CppHeap::From(), v8::internal::Isolate::heap(), v8::internal::TracedNodeBlock::InUsableList(), v8::internal::TracedNodeBlock::InYoungList(), v8::internal::TracedNodeBlock::IsEmpty(), v8::internal::TracedNodeBlock::IsFull(), isolate_, v8::internal::TracedNodeBlock::NeedsReprocessing(), num_blocks_, num_young_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), v8::base::DoublyThreadedList< T, DTLTraits >::Remove(), v8::internal::TracedNodeBlock::SetReprocessing(), SupportsClearingWeakNonLiveWrappers(), usable_blocks_, used_nodes_, v8::internal::wasm::void(), and young_blocks_.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
RefillUsableNodeBlocks()
void v8::internal::TracedHandles::RefillUsableNodeBlocks () [private]
Definition at line 105 of file traced-handles.cc.
                                           {
  TracedNodeBlock* block;
  if (empty_blocks_.empty()) {
    block = TracedNodeBlock::Create(*this);
    block_size_bytes_ += block->size_bytes();
  } else {
    block = empty_blocks_.back();
    empty_blocks_.pop_back();
  }
  usable_blocks_.PushFront(block);
  blocks_.PushFront(block);
  num_blocks_++;
  DCHECK(!block->InYoungList());
  DCHECK(block->IsEmpty());
  DCHECK_EQ(usable_blocks_.Front(), block);
  DCHECK(!usable_blocks_.empty());
}
References block_size_bytes_, blocks_, v8::internal::TracedNodeBlock::Create(), v8::internal::DCHECK(), DCHECK_EQ, v8::base::DoublyThreadedList< T, DTLTraits >::empty(), empty_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::Front(), v8::internal::TracedNodeBlock::InYoungList(), v8::internal::TracedNodeBlock::IsEmpty(), num_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::PushFront(), v8::internal::TracedNodeBlock::size_bytes(), and usable_blocks_.
Referenced by AllocateNode().
ResetDeadNodes()
void v8::internal::TracedHandles::ResetDeadNodes (WeakSlotCallbackWithHeap should_reset_handle)
Definition at line 320 of file traced-handles.cc.
                                                  {
  // Manual iteration as the block may be deleted in `FreeNode()`.
  for (auto it = blocks_.begin(); it != blocks_.end();) {
    auto* block = *(it++);
    for (auto* node : *block) {
      if (!node->is_in_use()) continue;
      // Detect unreachable nodes first.
      if (!node->markbit()) {
        FreeNode(node, kTracedHandleFullGCResetZapValue);
        continue;
      }
      // Node was reachable. Clear the markbit for the next GC.
      node->clear_markbit();
      // TODO(v8:13141): Turn into a DCHECK after some time.
      CHECK(!should_reset_handle(isolate_->heap(), node->location()));
    }
    if (block->InYoungList()) {
      young_blocks_.Remove(block);
      DCHECK(!block->InYoungList());
      num_young_blocks_--;
    }
  }
  CHECK(young_blocks_.empty());
}
References v8::base::DoublyThreadedList< T, DTLTraits >::begin(), blocks_, CHECK, v8::internal::DCHECK(), v8::base::DoublyThreadedList< T, DTLTraits >::empty(), v8::base::DoublyThreadedList< T, DTLTraits >::end(), FreeNode(), v8::internal::Isolate::heap(), isolate_, v8::internal::kTracedHandleFullGCResetZapValue, num_young_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::Remove(), and young_blocks_.
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences().
ResetYoungDeadNodes()
void v8::internal::TracedHandles::ResetYoungDeadNodes (WeakSlotCallbackWithHeap should_reset_handle)
Definition at line 350 of file traced-handles.cc.
                                                  {
  for (auto* block : young_blocks_) {
    for (auto* node : *block) {
      if (!node->is_in_young_list()) continue;
      DCHECK(node->is_in_use());
      DCHECK_IMPLIES(node->has_old_host(), node->markbit());
      if (!node->markbit()) {
        FreeNode(node, kTracedHandleMinorGCResetZapValue);
        continue;
      }
      // Node was reachable. Clear the markbit for the next GC.
      node->clear_markbit();
      // TODO(v8:13141): Turn into a DCHECK after some time.
      CHECK(!should_reset_handle(isolate_->heap(), node->location()));
    }
  }
}
References CHECK, v8::internal::DCHECK(), DCHECK_IMPLIES, FreeNode(), v8::internal::Isolate::heap(), isolate_, v8::internal::kTracedHandleMinorGCResetZapValue, and young_blocks_.
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences().
SetIsMarking()
void v8::internal::TracedHandles::SetIsMarking (bool value)
Definition at line 249 of file traced-handles.cc.
                                           {
  DCHECK_EQ(is_marking_, !value);
  is_marking_ = value;
}
References DCHECK_EQ, is_marking_, and v8::internal::value.
Referenced by v8::internal::IncrementalMarking::StartMarkingMajor().
SetIsSweepingOnMutatorThread()
void v8::internal::TracedHandles::SetIsSweepingOnMutatorThread (bool value)
Definition at line 254 of file traced-handles.cc.
                                                           {
  DCHECK_EQ(is_sweeping_on_mutator_thread_, !value);
  is_sweeping_on_mutator_thread_ = value;
}
References DCHECK_EQ, is_sweeping_on_mutator_thread_, and v8::internal::value.
SupportsClearingWeakNonLiveWrappers()
bool v8::internal::TracedHandles::SupportsClearingWeakNonLiveWrappers () [private]
Definition at line 371 of file traced-handles.cc.
                                                        {
  DCHECK(!is_marking_);
  if (!v8_flags.reclaim_unmodified_wrappers) {
    return false;
  }
  if (!isolate_->heap()->GetEmbedderRootsHandler()) {
    return false;
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::Heap::GetEmbedderRootsHandler(), v8::internal::Isolate::heap(), is_marking_, isolate_, and v8::internal::v8_flags.
Referenced by ComputeWeaknessForYoungObjects(), and ProcessWeakYoungObjects().
total_size_bytes()
size_t v8::internal::TracedHandles::total_size_bytes () const [inline]
Definition at line 333 of file traced-handles.h.
{ return block_size_bytes_; }
Referenced by v8::internal::Heap::TotalGlobalHandlesSize().
UpdateListOfYoungNodes()
void v8::internal::TracedHandles::UpdateListOfYoungNodes ()
Definition at line 273 of file traced-handles.cc.
                                           {
  const bool needs_to_mark_as_old =
      static_cast<bool>(GetCppHeapIfUnifiedYoungGC(isolate_));
  for (auto it = young_blocks_.begin(); it != young_blocks_.end();) {
    bool contains_young_node = false;
    TracedNodeBlock* const block = *it;
    DCHECK(block->InYoungList());
    for (auto* node : *block) {
      if (!node->is_in_young_list()) continue;
      DCHECK(node->is_in_use());
      if (HeapLayout::InYoungGeneration(node->object())) {
        contains_young_node = true;
        // The node was discovered through a cppgc object, which will be
        // immediately promoted. Remember the object.
        if (needs_to_mark_as_old) node->set_has_old_host(true);
      } else {
        node->set_is_in_young_list(false);
        node->set_has_old_host(false);
      }
    }
    if (contains_young_node) {
      ++it;
    } else {
      it = young_blocks_.RemoveAt(it);
      DCHECK(!block->InYoungList());
      num_young_blocks_--;
    }
  }
}
References v8::base::DoublyThreadedList< T, DTLTraits >::begin(), v8::internal::DCHECK(), v8::base::DoublyThreadedList< T, DTLTraits >::end(), GetCppHeapIfUnifiedYoungGC(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::TracedNodeBlock::InYoungList(), isolate_, num_young_blocks_, v8::base::DoublyThreadedList< T, DTLTraits >::RemoveAt(), and young_blocks_.
used_node_count()
size_t v8::internal::TracedHandles::used_node_count () const [inline]
Definition at line 332 of file traced-handles.h.
{ return used_nodes_; }
used_size_bytes()
size_t v8::internal::TracedHandles::used_size_bytes () const [inline]
Definition at line 334 of file traced-handles.h.
{ return sizeof(TracedNode) * used_nodes_; }
Referenced by v8::internal::Heap::UsedGlobalHandlesSize().
Member Data Documentation
block_size_bytes_
size_t v8::internal::TracedHandles::block_size_bytes_ = 0 [private]
Definition at line 369 of file traced-handles.h.
Referenced by DeleteEmptyBlocks(), RefillUsableNodeBlocks(), and ~TracedHandles().
blocks_
TracedNodeBlock::OverallList v8::internal::TracedHandles::blocks_ [private]
Definition at line 357 of file traced-handles.h.
Referenced by FreeNode(), GetNodeBounds(), Iterate(), ProcessWeakYoungObjects(), RefillUsableNodeBlocks(), ResetDeadNodes(), and ~TracedHandles().
disable_block_handling_on_free_
bool v8::internal::TracedHandles::disable_block_handling_on_free_ = false [private]
Definition at line 370 of file traced-handles.h.
Referenced by FreeNode(), and ProcessWeakYoungObjects().
empty_blocks_
std::vector<TracedNodeBlock*> v8::internal::TracedHandles::empty_blocks_ [private]
Definition at line 364 of file traced-handles.h.
Referenced by DeleteEmptyBlocks(), FreeNode(), ProcessWeakYoungObjects(), RefillUsableNodeBlocks(), and ~TracedHandles().
is_marking_
bool v8::internal::TracedHandles::is_marking_ = false [private]
Definition at line 366 of file traced-handles.h.
Referenced by Create(), Destroy(), IterateAndMarkYoungRootsWithOldHosts(), IterateYoungRoots(), IterateYoungRootsWithOldHostsForTesting(), Move(), NeedsToBeRemembered(), SetIsMarking(), and SupportsClearingWeakNonLiveWrappers().
is_sweeping_on_mutator_thread_
bool v8::internal::TracedHandles::is_sweeping_on_mutator_thread_ = false [private]
Definition at line 367 of file traced-handles.h.
Referenced by Destroy(), and SetIsSweepingOnMutatorThread().
isolate_
Isolate* v8::internal::TracedHandles::isolate_ [private]
Definition at line 365 of file traced-handles.h.
Referenced by ComputeWeaknessForYoungObjects(), Copy(), Create(), Move(), NeedsToBeRemembered(), ProcessWeakYoungObjects(), ResetDeadNodes(), ResetYoungDeadNodes(), SupportsClearingWeakNonLiveWrappers(), and UpdateListOfYoungNodes().
num_blocks_
size_t v8::internal::TracedHandles::num_blocks_ = 0 [private]
Definition at line 358 of file traced-handles.h.
Referenced by FreeNode(), GetNodeBounds(), ProcessWeakYoungObjects(), and RefillUsableNodeBlocks().
num_young_blocks_
size_t v8::internal::TracedHandles::num_young_blocks_ {0} [private]
Definition at line 361 of file traced-handles.h.
Referenced by ComputeWeaknessForYoungObjects(), Create(), FreeNode(), ProcessWeakYoungObjects(), ResetDeadNodes(), and UpdateListOfYoungNodes().
usable_blocks_
TracedNodeBlock::UsableList v8::internal::TracedHandles::usable_blocks_ [private]
Definition at line 359 of file traced-handles.h.
Referenced by AllocateNode(), FreeNode(), ProcessWeakYoungObjects(), and RefillUsableNodeBlocks().
used_nodes_
size_t v8::internal::TracedHandles::used_nodes_ = 0 [private]
Definition at line 368 of file traced-handles.h.
Referenced by AllocateNode(), FreeNode(), and ProcessWeakYoungObjects().
young_blocks_
TracedNodeBlock::YoungList v8::internal::TracedHandles::young_blocks_ [private]
Definition at line 360 of file traced-handles.h.
Referenced by ComputeWeaknessForYoungObjects(), Create(), FreeNode(), HasYoung(), IterateAndMarkYoungRootsWithOldHosts(), IterateYoung(), IterateYoungRoots(), IterateYoungRootsWithOldHostsForTesting(), ProcessWeakYoungObjects(), ResetDeadNodes(), ResetYoungDeadNodes(), and UpdateListOfYoungNodes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/traced-handles.h
/mnt/V8SourceCode/src/handles/traced-handles-inl.h
/mnt/V8SourceCode/src/handles/traced-handles.cc