v8::internal::StackFrameIterator Class Reference
#include <frames.h>
Public Member Functions
V8_EXPORT_PRIVATE StackFrameIterator (Isolate *isolate)
V8_EXPORT_PRIVATE StackFrameIterator (Isolate *isolate, ThreadLocalTop *t)
StackFrameIterator (const StackFrameIterator &)=delete
StackFrameIterator & operator= (const StackFrameIterator &)=delete
StackFrame * frame () const
V8_EXPORT_PRIVATE void Advance ()
StackFrame * Reframe ()
StackFrame::Type ComputeStackFrameType (StackFrame::State *state) const override
Private Member Functions
void Reset (ThreadLocalTop *top)
Additional Inherited Members
Detailed Description
Definition at line 1687 of file frames.h.
Constructor & Destructor Documentation
StackFrameIterator() [1/3]
v8::internal::StackFrameIterator::StackFrameIterator (Isolate * isolate) [explicit]
Definition at line 152 of file frames.cc.
    : StackFrameIterator(isolate, isolate->thread_local_top()) {}
StackFrameIterator() [2/3]
v8::internal::StackFrameIterator::StackFrameIterator (Isolate * isolate, ThreadLocalTop * t)
Definition at line 155 of file frames.cc.
    : StackFrameIteratorBase(isolate) {
  Reset(t);
}
References Reset().
StackFrameIterator() [3/3]
v8::internal::StackFrameIterator::StackFrameIterator (const StackFrameIterator &) [delete]
Member Function Documentation
Advance()
void v8::internal::StackFrameIterator::Advance ()
Definition at line 176 of file frames.cc.
                                 {
  DCHECK(!done());
  // Compute the state of the calling frame before restoring
  // callee-saved registers and unwinding handlers. This allows the
  // frame code that computes the caller state to access the top
  // handler and the value of any callee-saved register if needed.
  StackFrame::State state;
  StackFrame::Type type;
#if V8_ENABLE_WEBASSEMBLY
  if (frame_->type() == StackFrame::STACK_SWITCH &&
      Memory<Address>(frame_->fp() +
                      StackSwitchFrameConstants::kCallerFPOffset) ==
          kNullAddress &&
      !first_stack_only_) {
    // Handle stack switches here.
    // Note: both the "callee" frame (outermost frame of the child stack) and
    // the "caller" frame (top frame of the parent stack) have frame type
    // STACK_SWITCH. We use the caller FP to distinguish them: the callee frame
    // does not have a caller fp.
    wasm_stack_ = wasm_stack()->jmpbuf()->parent;
    CHECK_NOT_NULL(wasm_stack_);
    CHECK_EQ(wasm_stack_->jmpbuf()->state, wasm::JumpBuffer::Inactive);
    StackSwitchFrame::GetStateForJumpBuffer(wasm_stack_->jmpbuf(), &state);
    SetNewFrame(StackFrame::STACK_SWITCH, &state);
    return;
  }
#endif
  type = frame_->GetCallerState(&state);
  // {StackHandlerIterator} assumes that frame pointers strictly go from lower
  // to higher addresses as we iterate the stack. This breaks with
  // stack-switching, so only unwind the stack handlers for frames that are
  // known to use them.
  if (frame_->type() == StackFrame::ENTRY ||
      frame_->type() == StackFrame::CONSTRUCT_ENTRY
#if V8_ENABLE_WEBASSEMBLY
      || frame_->type() == StackFrame::C_WASM_ENTRY
#endif
  ) {
    StackHandlerIterator it(frame_, handler_);
    while (!it.done()) it.Advance();
    handler_ = it.handler();
  }
  // Advance to the calling frame.
  SetNewFrame(type, &state);
  // When we're done iterating over the stack frames, the handler
  // chain must have been completely unwound. Except if we are only iterating
  // the first stack of the chain for wasm stack-switching.
#if V8_ENABLE_WEBASSEMBLY
  DCHECK_IMPLIES(done() && !first_stack_only_, handler_ == nullptr);
#else
  DCHECK_IMPLIES(done(), handler_ == nullptr);
#endif
}
References v8::internal::StackHandlerIterator::Advance(), CHECK_EQ, CHECK_NOT_NULL, CONSTRUCT_ENTRY, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::StackHandlerIterator::done(), v8::internal::StackFrameIteratorBase::done(), ENTRY, v8::internal::StackFrame::fp(), v8::internal::StackFrameIteratorBase::frame_, v8::internal::StackFrame::GetCallerState(), v8::internal::StackHandlerIterator::handler(), v8::internal::StackFrameIteratorBase::handler_, v8::internal::wasm::JumpBuffer::Inactive, v8::internal::kNullAddress, v8::internal::StackFrameIteratorBase::SetNewFrame(), v8::internal::StackFrame::type(), and v8::internal::tracing::type.
Referenced by v8::internal::JavaScriptStackFrameIterator::Advance(), v8::internal::DebuggableStackFrameIterator::Advance(), v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack(), v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), v8::internal::Debug::OnException(), v8::internal::PrintFrames(), v8::internal::StackTraceFailureMessage::StackTraceFailureMessage(), and v8::internal::Isolate::UnwindAndFindHandler().
ComputeStackFrameType()
StackFrame::Type v8::internal::StackFrameIterator::ComputeStackFrameType (StackFrame::State * state) const [override], [virtual]
Implements v8::internal::StackFrameIteratorBase.
Definition at line 915 of file frames.cc.
                                  {
#if V8_ENABLE_WEBASSEMBLY
  if (state->fp == kNullAddress && first_stack_only_) {
    DCHECK(!isolate_->wasm_stacks().empty()); // I.e., JSPI active
    return StackFrame::NO_FRAME_TYPE;
  }
#endif
  const Address pc = StackFrame::ReadPC(state->pc_address);
#if V8_ENABLE_WEBASSEMBLY
  // If the {pc} does not point into WebAssembly code we can rely on the
  // returned {wasm_code} to be null and fall back to {GetContainingCode}.
  if (wasm::WasmCode* wasm_code =
          wasm::GetWasmCodeManager()->LookupCode(isolate(), pc)) {
    switch (wasm_code->kind()) {
      case wasm::WasmCode::kWasmFunction:
        return StackFrame::WASM;
      case wasm::WasmCode::kWasmToCapiWrapper:
        return StackFrame::WASM_EXIT;
      case wasm::WasmCode::kWasmToJsWrapper:
        return StackFrame::WASM_TO_JS;
#if V8_ENABLE_DRUMBRAKE
      case wasm::WasmCode::kInterpreterEntry:
        return StackFrame::WASM_INTERPRETER_ENTRY;
#endif // V8_ENABLE_DRUMBRAKE
      default:
        UNREACHABLE();
    }
  }
#endif // V8_ENABLE_WEBASSEMBLY
  // Look up the code object to figure out the type of the stack frame.
  std::optional<Tagged<GcSafeCode>> lookup_result =
      GetContainingCode(isolate(), pc);
  if (!lookup_result.has_value()) return StackFrame::NATIVE;
  MSAN_MEMORY_IS_INITIALIZED(
      state->fp + CommonFrameConstants::kContextOrFrameTypeOffset,
      kSystemPointerSize);
  const intptr_t marker = Memory<intptr_t>(
      state->fp + CommonFrameConstants::kContextOrFrameTypeOffset);
  switch (lookup_result.value()->kind()) {
    case CodeKind::BUILTIN:
    case CodeKind::FOR_TESTING: {
      if (StackFrame::IsTypeMarker(marker)) break;
      return ComputeBuiltinFrameType(lookup_result.value());
    }
    case CodeKind::BASELINE:
      // Baseline code can be deoptimized by DiscardBaselineCodeVisitor.
      if (lookup_result.value()->marked_for_deoptimization())
        return StackFrame::INTERPRETED;
      return StackFrame::BASELINE;
    case CodeKind::MAGLEV:
      if (StackFrame::IsTypeMarker(marker)) {
        // An INTERNAL frame can be set up with an associated Maglev code
        // object when calling into runtime to handle tiering. In this case,
        // all stack slots are tagged pointers and should be visited through
        // the usual logic.
        DCHECK_EQ(StackFrame::MarkerToType(marker), StackFrame::INTERNAL);
        return StackFrame::INTERNAL;
      }
      return StackFrame::MAGLEV;
    case CodeKind::TURBOFAN_JS:
      return StackFrame::TURBOFAN_JS;
#if V8_ENABLE_WEBASSEMBLY
    case CodeKind::JS_TO_WASM_FUNCTION:
      if (lookup_result.value()->builtin_id() == Builtin::kJSToWasmWrapperAsm) {
        return StackFrame::JS_TO_WASM;
      }
#if V8_ENABLE_DRUMBRAKE
      if (lookup_result.value()->builtin_id() ==
          Builtin::kGenericJSToWasmInterpreterWrapper) {
        return StackFrame::JS_TO_WASM;
      }
#endif // V8_ENABLE_DRUMBRAKE
      return StackFrame::TURBOFAN_STUB_WITH_CONTEXT;
    case CodeKind::C_WASM_ENTRY:
      return StackFrame::C_WASM_ENTRY;
    case CodeKind::WASM_TO_JS_FUNCTION:
      // Should have been found by the WasmCode lookup above.
      UNREACHABLE();
    case CodeKind::WASM_FUNCTION:
    case CodeKind::WASM_TO_CAPI_FUNCTION:
      // These never appear as on-heap Code objects.
      UNREACHABLE();
#else
    case CodeKind::C_WASM_ENTRY:
    case CodeKind::JS_TO_WASM_FUNCTION:
    case CodeKind::WASM_FUNCTION:
    case CodeKind::WASM_TO_CAPI_FUNCTION:
    case CodeKind::WASM_TO_JS_FUNCTION:
      UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
    case CodeKind::BYTECODE_HANDLER:
    case CodeKind::REGEXP:
    case CodeKind::INTERPRETED_FUNCTION:
      // Fall back to the marker.
      break;
  }
  return SafeStackFrameType(StackFrame::MarkerToType(marker));
}
References BUILTIN, v8::internal::anonymous_namespace{frames.cc}::ComputeBuiltinFrameType(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::StackFrame::State::fp, v8::internal::anonymous_namespace{frames.cc}::GetContainingCode(), v8::internal::wasm::GetWasmCodeManager(), v8::internal::StackFrameIteratorBase::isolate(), v8::internal::StackFrameIteratorBase::isolate_, v8::internal::StackFrame::IsTypeMarker(), v8::internal::CommonFrameConstants::kContextOrFrameTypeOffset, v8::internal::kNullAddress, v8::internal::kSystemPointerSize, v8::internal::wasm::WasmCode::kWasmFunction, v8::internal::wasm::WasmCode::kWasmToCapiWrapper, v8::internal::wasm::WasmCode::kWasmToJsWrapper, v8::internal::StackFrame::MarkerToType(), MSAN_MEMORY_IS_INITIALIZED, v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::StackFrame::State::pc_address, v8::internal::StackFrame::ReadPC(), v8::internal::anonymous_namespace{frames.cc}::SafeStackFrameType(), and v8::internal::UNREACHABLE().
Referenced by Reframe().
frame()
StackFrame* v8::internal::StackFrameIterator::frame () const [inline]
Definition at line 1711 of file frames.h.
                            {
    DCHECK(!done());
    return frame_;
  }
References v8::internal::DCHECK(), v8::internal::StackFrameIteratorBase::done(), and v8::internal::StackFrameIteratorBase::frame_.
Referenced by v8::internal::ProfilerEventsProcessor::AddCurrentStack(), v8::internal::JavaScriptStackFrameIterator::Advance(), v8::internal::DebuggableStackFrameIterator::Advance(), v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack(), v8::internal::DebuggableStackFrameIterator::DebuggableStackFrameIterator(), v8::internal::anonymous_namespace{wasm-interpreter-runtime.cc}::FindInterpreterEntryFramePointer(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::DebuggableStackFrameIterator::FrameFunctionCount(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), v8::internal::Debug::OnException(), v8::internal::PrintFrames(), Reframe(), v8::internal::StackTraceFailureMessage::StackTraceFailureMessage(), and v8::internal::Isolate::UnwindAndFindHandler().
operator=()
StackFrameIterator& v8::internal::StackFrameIterator::operator= (const StackFrameIterator &) [delete]
Reframe()
StackFrame * v8::internal::StackFrameIterator::Reframe ()
Definition at line 232 of file frames.cc.
                                        {
  StackFrame::State state = frame_->state_;
  StackFrame::Type type = ComputeStackFrameType(&state);
  SetNewFrame(type, &state);
  return frame();
}
References ComputeStackFrameType(), frame(), v8::internal::StackFrameIteratorBase::frame_, v8::internal::StackFrameIteratorBase::SetNewFrame(), v8::internal::StackFrame::state_, and v8::internal::tracing::type.
Referenced by v8::internal::JavaScriptStackFrameIterator::Reframe(), and v8::internal::DebuggableStackFrameIterator::Reframe().
Reset()
void v8::internal::StackFrameIterator::Reset (ThreadLocalTop * top) [private]
Definition at line 270 of file frames.cc.
                                                  {
  StackFrame::State state;
  StackFrame::Type type;
  const Address fast_c_call_caller_fp =
      isolate_->isolate_data()->fast_c_call_caller_fp();
  if (fast_c_call_caller_fp != kNullAddress) {
    const Address caller_pc = isolate_->isolate_data()->fast_c_call_caller_pc();
    const Address caller_pc_address =
        isolate_->isolate_data()->fast_c_call_caller_pc_address();
    type = GetStateForFastCCallCallerFP(isolate_, fast_c_call_caller_fp,
                                        caller_pc, caller_pc_address, &state);
  } else {
    type = ExitFrame::GetStateForFramePointer(Isolate::c_entry_fp(top), &state);
  }
#if V8_ENABLE_WEBASSEMBLY
  wasm_stack_ = isolate_->isolate_data()->active_stack();
#endif
  handler_ = StackHandler::FromAddress(Isolate::handler(top));
  SetNewFrame(type, &state);
}
References v8::internal::IsolateData::active_stack(), v8::internal::Isolate::c_entry_fp(), v8::internal::IsolateData::fast_c_call_caller_fp(), v8::internal::IsolateData::fast_c_call_caller_pc(), v8::internal::StackHandler::FromAddress(), v8::internal::anonymous_namespace{frames.cc}::GetStateForFastCCallCallerFP(), v8::internal::ExitFrame::GetStateForFramePointer(), v8::internal::Isolate::handler(), v8::internal::StackFrameIteratorBase::handler_, v8::internal::StackFrameIteratorBase::isolate_, v8::internal::Isolate::isolate_data(), v8::internal::kNullAddress, v8::internal::StackFrameIteratorBase::SetNewFrame(), and v8::internal::tracing::type.
Referenced by StackFrameIterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc