v8::base::LsanPageAllocator Class Reference
#include <lsan-page-allocator.h>
Public Member Functions
LsanPageAllocator (v8::PageAllocator *page_allocator)
~LsanPageAllocator () override=default
size_t AllocatePageSize () override
Gets the page granularity for AllocatePages and FreePages.
size_t CommitPageSize () override
Gets the page granularity for SetPermissions and ReleasePages.
void SetRandomMmapSeed (int64_t seed) override
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
void * GetRandomMmapAddr () override
Returns a randomized address, suitable for memory allocation under ASLR.
void * AllocatePages (void *address, size_t size, size_t alignment, PageAllocator::Permission access) override
Allocates memory in range with the given alignment and permission.
std::unique_ptr< SharedMemory > AllocateSharedPages (size_t size, const void *original_address) override
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
bool CanAllocateSharedPages () override
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
bool FreePages (void *address, size_t size) override
Frees memory in a range that was allocated by a call to AllocatePages.
bool ReleasePages (void *address, size_t size, size_t new_size) override
Releases memory in a range that was allocated by a call to AllocatePages.
bool SetPermissions (void *address, size_t size, PageAllocator::Permission access) override
Sets permissions on pages in an allocated range.
bool RecommitPages (void *address, size_t size, PageAllocator::Permission access) override
Recommits discarded pages in the given range with given permissions.
bool DiscardSystemPages (void *address, size_t size) override
Frees memory in the given [address, address + size) range.
bool DecommitPages (void *address, size_t size) override
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
Private Attributes
v8::PageAllocator *const page_allocator_
const size_t allocate_page_size_
const size_t commit_page_size_
Additional Inherited Members
Detailed Description
Definition at line 23 of file lsan-page-allocator.h.
Constructor & Destructor Documentation
LsanPageAllocator()
v8::base::LsanPageAllocator::LsanPageAllocator (v8::PageAllocator * page_allocator) [explicit]
Definition at line 17 of file lsan-page-allocator.cc.
    : page_allocator_(page_allocator),
      allocate_page_size_(page_allocator_->AllocatePageSize()),
      commit_page_size_(page_allocator_->CommitPageSize()) {
  DCHECK_NOT_NULL(page_allocator);
}
References DCHECK_NOT_NULL.
 LsanPageAllocator()
v8::base::LsanPageAllocator::~LsanPageAllocator () [override], [default]
Member Function Documentation
AllocatePages()
void * v8::base::LsanPageAllocator::AllocatePages (void * address, size_t length, size_t alignment, PageAllocator::Permission permissions) [override], [virtual]
Allocates memory in range with the given alignment and permission.
Implements v8::PageAllocator.
Definition at line 24 of file lsan-page-allocator.cc.
                                                                       {
  void* result = page_allocator_->AllocatePages(hint, size, alignment, access);
#if defined(LEAK_SANITIZER)
  if (result != nullptr) {
    if (access != PageAllocator::Permission::kNoAccessWillJitLater) {
      __lsan_register_root_region(result, size);
    } else {
      // We allocate the JIT cage as RWX from the beginning und use Discard to
      // mark the memory as unused. This makes tests with LSAN enabled 2-3x
      // slower since it will always try to scan the area for pointers. So skip
      // registering the JIT regions with LSAN.
      base::MutexGuard lock(&not_registered_regions_mutex_);
      DCHECK_EQ(0, not_registered_regions_.count(result));
      not_registered_regions_.insert(result);
    }
  }
#endif
  return result;
}
References v8::PageAllocator::AllocatePages(), DCHECK_EQ, page_allocator_, v8::base::internal::result, and size().
AllocatePageSize()
size_t v8::base::LsanPageAllocator::AllocatePageSize () [inline], [override], [virtual]
Gets the page granularity for AllocatePages and FreePages.
Addresses and lengths for those calls should be multiples of AllocatePageSize().
Implements v8::PageAllocator.
Definition at line 28 of file lsan-page-allocator.h.
{ return allocate_page_size_; }
AllocateSharedPages()
std::unique_ptr< v8::PageAllocator::SharedMemory > v8::base::LsanPageAllocator::AllocateSharedPages (size_t length, const void * original_address) [override], [virtual]
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
Allocates shared memory pages. Not all PageAllocators need support this and so this method need not be overridden. Allocates a new read-only shared memory region of size |length| and copies the memory at |original_address| into it.
Reimplemented from v8::PageAllocator.
Definition at line 47 of file lsan-page-allocator.cc.
                                                                     {
  auto result = page_allocator_->AllocateSharedPages(size, original_address);
#if defined(LEAK_SANITIZER)
  if (result != nullptr) {
    __lsan_register_root_region(result->GetMemory(), size);
  }
#endif
  return result;
}
References v8::PageAllocator::AllocateSharedPages(), page_allocator_, v8::base::internal::result, and size().
CanAllocateSharedPages()
bool v8::base::LsanPageAllocator::CanAllocateSharedPages () [override], [virtual]
INTERNAL ONLY: This interface has not been stabilised and may change without notice from one release to another without being deprecated first.
If not overridden and changed to return true, V8 will not attempt to call AllocateSharedPages or RemapSharedPages. If overridden, AllocateSharedPages and RemapSharedPages must also be overridden.
Reimplemented from v8::PageAllocator.
Definition at line 58 of file lsan-page-allocator.cc.
                                               {
  return page_allocator_->CanAllocateSharedPages();
}
References v8::PageAllocator::CanAllocateSharedPages(), and page_allocator_.
CommitPageSize()
size_t v8::base::LsanPageAllocator::CommitPageSize () [inline], [override], [virtual]
Gets the page granularity for SetPermissions and ReleasePages.
Addresses and lengths for those calls should be multiples of CommitPageSize().
Implements v8::PageAllocator.
Definition at line 30 of file lsan-page-allocator.h.
{ return commit_page_size_; }
DecommitPages()
bool v8::base::LsanPageAllocator::DecommitPages (void * address, size_t size) [inline], [override], [virtual]
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
The address range stays reserved and can be accessed again later by changing its permissions. However, in that case the memory content is guaranteed to be zero-initialized again. The memory must have been previously allocated by a call to AllocatePages. Returns true on success, false otherwise.
Implements v8::PageAllocator.
Definition at line 66 of file lsan-page-allocator.h.
                                                          {
    return page_allocator_->DecommitPages(address, size);
  }
References size().
DiscardSystemPages()
bool v8::base::LsanPageAllocator::DiscardSystemPages (void * address, size_t size) [inline], [override], [virtual]
Frees memory in the given [address, address + size) range.
address and size should be operating system page-aligned. The next write to this memory area brings the memory transparently back. This should be treated as a hint to the OS that the pages are no longer needed. It does not guarantee that the pages will be discarded immediately or at all.
Reimplemented from v8::PageAllocator.
Definition at line 62 of file lsan-page-allocator.h.
                                                               {
    return page_allocator_->DiscardSystemPages(address, size);
  }
References size().
FreePages()
bool v8::base::LsanPageAllocator::FreePages (void * address, size_t length) [override], [virtual]
Frees memory in a range that was allocated by a call to AllocatePages.
Implements v8::PageAllocator.
Definition at line 62 of file lsan-page-allocator.cc.
                                                            {
#if defined(LEAK_SANITIZER)
  base::MutexGuard lock(&not_registered_regions_mutex_);
  if (not_registered_regions_.count(address) == 0) {
    __lsan_unregister_root_region(address, size);
  } else {
    not_registered_regions_.erase(address);
  }
#endif
  CHECK(page_allocator_->FreePages(address, size));
  return true;
}
References CHECK, v8::PageAllocator::FreePages(), page_allocator_, and size().
GetRandomMmapAddr()
void* v8::base::LsanPageAllocator::GetRandomMmapAddr () [inline], [override], [virtual]
Returns a randomized address, suitable for memory allocation under ASLR.
The address will be aligned to AllocatePageSize.
Implements v8::PageAllocator.
Definition at line 36 of file lsan-page-allocator.h.
                                     {
    return page_allocator_->GetRandomMmapAddr();
  }
RecommitPages()
bool v8::base::LsanPageAllocator::RecommitPages (void * address, size_t length, PageAllocator::Permission permissions) [inline], [override], [virtual]
Recommits discarded pages in the given range with given permissions.
Discarded pages must be recommitted with their original permissions before they are used again.
Reimplemented from v8::PageAllocator.
Definition at line 57 of file lsan-page-allocator.h.
                                                              {
    return page_allocator_->RecommitPages(address, size, access);
  }
References size().
ReleasePages()
bool v8::base::LsanPageAllocator::ReleasePages (void * address, size_t length, size_t new_length) [override], [virtual]
Releases memory in a range that was allocated by a call to AllocatePages.
Implements v8::PageAllocator.
Definition at line 75 of file lsan-page-allocator.cc.
                                                      {
#if defined(LEAK_SANITIZER)
  base::MutexGuard lock(&not_registered_regions_mutex_);
  if (not_registered_regions_.count(address) == 0) {
    __lsan_unregister_root_region(address, size);
    __lsan_register_root_region(address, new_size);
  }
#endif
  CHECK(page_allocator_->ReleasePages(address, size, new_size));
  return true;
}
References CHECK, page_allocator_, v8::PageAllocator::ReleasePages(), and size().
SetPermissions()
bool v8::base::LsanPageAllocator::SetPermissions (void * address, size_t length, PageAllocator::Permission permissions) [inline], [override], [virtual]
Sets permissions on pages in an allocated range.
Implements v8::PageAllocator.
Definition at line 52 of file lsan-page-allocator.h.
                                                               {
    return page_allocator_->SetPermissions(address, size, access);
  }
References size().
SetRandomMmapSeed()
void v8::base::LsanPageAllocator::SetRandomMmapSeed (int64_t seed) [inline], [override], [virtual]
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
Implements v8::PageAllocator.
Definition at line 32 of file lsan-page-allocator.h.
                                                {
    return page_allocator_->SetRandomMmapSeed(seed);
  }
Member Data Documentation
allocate_page_size_
const size_t v8::base::LsanPageAllocator::allocate_page_size_ [private]
Definition at line 72 of file lsan-page-allocator.h.
commit_page_size_
const size_t v8::base::LsanPageAllocator::commit_page_size_ [private]
Definition at line 73 of file lsan-page-allocator.h.
page_allocator_
v8::PageAllocator* const v8::base::LsanPageAllocator::page_allocator_ [private]
Definition at line 71 of file lsan-page-allocator.h.
Referenced by AllocatePages(), AllocateSharedPages(), CanAllocateSharedPages(), FreePages(), and ReleasePages().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/sanitizer/lsan-page-allocator.h
/mnt/V8SourceCode/src/base/sanitizer/lsan-page-allocator.cc