v8::internal::StressConcurrentAllocationTask Class Reference
Public Member Functions
StressConcurrentAllocationTask (Isolate *isolate)
void RunInternal () override
Static Public Member Functions
static void Schedule (Isolate *isolate)
Private Attributes
Isolate * isolate_
Additional Inherited Members
Detailed Description
Definition at line 5870 of file heap.cc.
Constructor & Destructor Documentation
StressConcurrentAllocationTask()
v8::internal::StressConcurrentAllocationTask::StressConcurrentAllocationTask (Isolate * isolate) [inline], [explicit]
Definition at line 5872 of file heap.cc.
      : CancelableTask(isolate), isolate_(isolate) {}
Member Function Documentation
RunInternal()
void v8::internal::StressConcurrentAllocationTask::RunInternal () [inline], [override], [virtual]
Implements v8::internal::CancelableTask.
Definition at line 5875 of file heap.cc.
                              {
    Heap* heap = isolate_->heap();
    LocalHeap local_heap(heap, ThreadKind::kBackground);
    UnparkedScope unparked_scope(&local_heap);
    const int kNumIterations = 2000;
    const int kSmallObjectSize = 10 * kTaggedSize;
    const int kMediumObjectSize = 8 * KB;
    const int kLargeObjectSize =
        static_cast<int>(MutablePageMetadata::kPageSize -
                         MemoryChunkLayout::ObjectStartOffsetInDataPage());
    for (int i = 0; i < kNumIterations; i++) {
      // Isolate tear down started, stop allocation...
      if (heap->gc_state() == Heap::TEAR_DOWN) return;
      AllocationResult result = local_heap.AllocateRaw(
          kSmallObjectSize, AllocationType::kOld, AllocationOrigin::kRuntime,
          AllocationAlignment::kTaggedAligned);
      if (!result.IsFailure()) {
        heap->CreateFillerObjectAtBackground(
            WritableFreeSpace::ForNonExecutableMemory(result.ToAddress(),
                                                      kSmallObjectSize));
      } else {
        heap->CollectGarbageFromAnyThread(&local_heap);
      }
      result = local_heap.AllocateRaw(kMediumObjectSize, AllocationType::kOld,
                                      AllocationOrigin::kRuntime,
                                      AllocationAlignment::kTaggedAligned);
      if (!result.IsFailure()) {
        heap->CreateFillerObjectAtBackground(
            WritableFreeSpace::ForNonExecutableMemory(result.ToAddress(),
                                                      kMediumObjectSize));
      } else {
        heap->CollectGarbageFromAnyThread(&local_heap);
      }
      result = local_heap.AllocateRaw(kLargeObjectSize, AllocationType::kOld,
                                      AllocationOrigin::kRuntime,
                                      AllocationAlignment::kTaggedAligned);
      if (!result.IsFailure()) {
        heap->CreateFillerObjectAtBackground(
            WritableFreeSpace::ForNonExecutableMemory(result.ToAddress(),
                                                      kLargeObjectSize));
      } else {
        heap->CollectGarbageFromAnyThread(&local_heap);
      }
      local_heap.Safepoint();
    }
    Schedule(isolate_);
  }
References v8::internal::LocalHeap::AllocateRaw(), v8::internal::WritableFreeSpace::ForNonExecutableMemory(), v8::internal::Isolate::heap(), isolate_, v8::internal::KB, v8::internal::kBackground, v8::internal::kOld, v8::internal::MutablePageMetadata::kPageSize, v8::internal::kRuntime, v8::internal::kTaggedAligned, v8::internal::kTaggedSize, v8::internal::MemoryChunkLayout::ObjectStartOffsetInDataPage(), v8::base::internal::result, v8::internal::LocalHeap::Safepoint(), Schedule(), and v8::internal::Heap::TEAR_DOWN.
Schedule()
static void v8::internal::StressConcurrentAllocationTask::Schedule (Isolate * isolate) [inline], [static]
Definition at line 5930 of file heap.cc.
                                         {
    auto task = std::make_unique<StressConcurrentAllocationTask>(isolate);
    const double kDelayInSeconds = 0.1;
    V8::GetCurrentPlatform()->PostDelayedTaskOnWorkerThread(
        TaskPriority::kUserVisible, std::move(task), kDelayInSeconds);
  }
References v8::internal::V8::GetCurrentPlatform(), v8::kUserVisible, and v8::Platform::PostDelayedTaskOnWorkerThread().
Referenced by RunInternal(), and v8::internal::StressConcurrentAllocationObserver::Step().
Member Data Documentation
isolate_
Isolate* v8::internal::StressConcurrentAllocationTask::isolate_ [private]
Definition at line 5938 of file heap.cc.
Referenced by RunInternal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.cc