cppgc::internal::BasePage Class Reference
#include <heap-page.h>
Classes
struct SlotSetDeleter
Public Member Functions
BasePage (const BasePage &)=delete
BasePage & operator= (const BasePage &)=delete
HeapBase & heap () const
BaseSpace & space () const
bool is_large () const
Address PayloadStart ()
ConstAddress PayloadStart () const
Address PayloadEnd ()
ConstAddress PayloadEnd () const
size_t AllocatedSize () const
size_t AllocatedBytesAtLastGC () const
template<AccessMode = AccessMode::kNonAtomic>
HeapObjectHeader & ObjectHeaderFromInnerAddress (void *address) const
template<AccessMode = AccessMode::kNonAtomic>
const HeapObjectHeader & ObjectHeaderFromInnerAddress (const void *address) const
HeapObjectHeader * TryObjectHeaderFromInnerAddress (void *address) const
const HeapObjectHeader * TryObjectHeaderFromInnerAddress (const void *address) const
void SynchronizedLoad () const
void SynchronizedStore ()
void IncrementDiscardedMemory (size_t value)
void ResetDiscardedMemory ()
size_t discarded_memory () const
void IncrementMarkedBytes (size_t value)
void DecrementMarkedBytes (size_t value)
void ResetMarkedBytes (size_t new_value=0)
size_t marked_bytes () const
bool contains_young_objects () const
void set_as_containing_young_objects (bool value)
void ChangeOwner (BaseSpace &)
Static Public Member Functions
static BasePage * FromPayload (void *)
static const BasePage * FromPayload (const void *)
static BasePage * FromInnerAddress (const HeapBase *, void *)
static const BasePage * FromInnerAddress (const HeapBase *, const void *)
static void Destroy (BasePage *)
Protected Types
enum class PageType : uint8_t { kNormal
, kLarge
 }
Protected Member Functions
BasePage (HeapBase &, BaseSpace &, PageType)
Private Member Functions
void AllocateSlotSet ()
Private Attributes
BaseSpace * space_
PageType type_
bool contains_young_objects_ = false
size_t discarded_memory_ = 0
std::atomic< size_t > marked_bytes_ {0}
Additional Inherited Members
Detailed Description
Definition at line 30 of file heap-page.h.
Member Enumeration Documentation
PageType
enum cppgc::internal::BasePage::PageType : uint8_t [strong], [protected]
Enumerator
kNormal
kLarge
Definition at line 132 of file heap-page.h.
: uint8_t { kNormal, kLarge };
Constructor & Destructor Documentation
BasePage() [1/2]
cppgc::internal::BasePage::BasePage (const BasePage &) [delete]
BasePage() [2/2]
cppgc::internal::BasePage::BasePage (HeapBase & heap, BaseSpace & space, PageType type) [protected]
Definition at line 145 of file heap-page.cc.
    : BasePageHandle(heap),
      space_(&space),
      type_(type)
#if defined(CPPGC_YOUNG_GENERATION)
      ,
      slot_set_(nullptr, SlotSetDeleter{})
#endif // defined(CPPGC_YOUNG_GENERATION)
{
  DCHECK_EQ(0u, reinterpret_cast<uintptr_t>(this) & kPageOffsetMask);
  DCHECK_EQ(&heap.raw_heap(), space_->raw_heap());
}
References DCHECK_EQ, cppgc::internal::kPageOffsetMask, cppgc::internal::BaseSpace::raw_heap(), and space_.
Member Function Documentation
AllocatedBytesAtLastGC()
size_t cppgc::internal::BasePage::AllocatedBytesAtLastGC () const
Definition at line 93 of file heap-page.cc.
                                              {
  return is_large() ? LargePage::From(this)->AllocatedBytesAtLastGC()
                    : NormalPage::From(this)->AllocatedBytesAtLastGC();
}
References cppgc::internal::NormalPage::AllocatedBytesAtLastGC(), cppgc::internal::LargePage::AllocatedBytesAtLastGC(), cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), and is_large().
AllocatedSize()
size_t cppgc::internal::BasePage::AllocatedSize () const
Definition at line 86 of file heap-page.cc.
                                     {
  return is_large() ? LargePage::PageHeaderSize() +
                          LargePage::From(this)->PayloadSize()
                    : NormalPage::From(this)->PayloadSize() +
                          RoundUp(sizeof(NormalPage), kAllocationGranularity);
}
References cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), is_large(), cppgc::internal::kAllocationGranularity, cppgc::internal::LargePage::PageHeaderSize(), cppgc::internal::NormalPage::PayloadSize(), cppgc::internal::LargePage::PayloadSize(), and RoundUp().
AllocateSlotSet()
void cppgc::internal::BasePage::AllocateSlotSet () [private]
ChangeOwner()
void cppgc::internal::BasePage::ChangeOwner (BaseSpace & space)
Definition at line 158 of file heap-page.cc.
                                           {
  DCHECK_EQ(space_->raw_heap(), space.raw_heap());
  space_ = &space;
}
References DCHECK_EQ, cppgc::internal::BaseSpace::raw_heap(), space(), and space_.
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
contains_young_objects()
bool cppgc::internal::BasePage::contains_young_objects () const [inline]
Definition at line 118 of file heap-page.h.
{ return contains_young_objects_; }
DecrementMarkedBytes()
void cppgc::internal::BasePage::DecrementMarkedBytes (size_t value) [inline]
Definition at line 105 of file heap-page.h.
                                          {
    const size_t old_marked_bytes =
        marked_bytes_.fetch_sub(value, std::memory_order_relaxed);
    USE(old_marked_bytes);
    DCHECK_LE(old_marked_bytes - value, old_marked_bytes);
  }
References DCHECK_LE, USE, and v8::internal::value.
Referenced by cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
Destroy()
void cppgc::internal::BasePage::Destroy (BasePage * page) [static]
Definition at line 53 of file heap-page.cc.
                                     {
  if (page->discarded_memory()) {
    page->space()
        .raw_heap()
        ->heap()
        ->stats_collector()
        ->DecrementDiscardedMemory(page->discarded_memory());
  }
  if (page->is_large()) {
    LargePage::Destroy(LargePage::From(page));
  } else {
    NormalPage::Destroy(NormalPage::From(page));
  }
}
References cppgc::internal::StatsCollector::DecrementDiscardedMemory(), cppgc::internal::LargePage::Destroy(), cppgc::internal::NormalPage::Destroy(), discarded_memory(), cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::RawHeap::heap(), is_large(), cppgc::internal::BaseSpace::raw_heap(), space(), and cppgc::internal::HeapBase::stats_collector().
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage().
discarded_memory()
size_t cppgc::internal::BasePage::discarded_memory () const [inline]
Definition at line 97 of file heap-page.h.
{ return discarded_memory_; }
Referenced by Destroy(), and cppgc::internal::HeapStatisticsCollector::VisitNormalPage().
FromInnerAddress() [1/2]
const BasePage * cppgc::internal::BasePage::FromInnerAddress (const HeapBase * heap, const void * address) [static]
Definition at line 46 of file heap-page.cc.
                                                                {
  return reinterpret_cast<const BasePage*>(
      heap->page_backend()->Lookup(static_cast<ConstAddress>(address)));
}
FromInnerAddress() [2/2]
BasePage * cppgc::internal::BasePage::FromInnerAddress (const HeapBase * heap, void * address) [static]
Definition at line 40 of file heap-page.cc.
                                                                        {
  return const_cast<BasePage*>(
      FromInnerAddress(heap, const_cast<const void*>(address)));
}
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter(), cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), v8::internal::TracedHandles::IsCppGCHostOld(), and v8::internal::CrossHeapRememberedSet::RememberReferenceIfNeeded().
FromPayload() [1/2]
const BasePage * cppgc::internal::BasePage::FromPayload (const void * payload) [inline], [static]
Definition at line 319 of file heap-page.h.
                                                         {
  return static_cast<const BasePage*>(BasePageHandle::FromPayload(payload));
}
References cppgc::internal::BasePageHandle::FromPayload().
FromPayload() [2/2]
BasePage * cppgc::internal::BasePage::FromPayload (void * payload) [inline], [static]
Definition at line 314 of file heap-page.h.
                                             {
  return static_cast<BasePage*>(BasePageHandle::FromPayload(payload));
}
References cppgc::internal::BasePageHandle::FromPayload().
Referenced by cppgc::internal::BasicMarkingState::AccountMarkedBytes(), cppgc::internal::anonymous_namespace{object-allocator.cc}::AddToFreeList(), cppgc::internal::ObjectAllocator::AllocateObjectOnSpace(), cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), v8::internal::ConcurrentUnifiedHeapMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent(), cppgc::internal::ConcurrentMarkingVisitor::DeferTraceToMutatorThreadIfConcurrent(), cppgc::internal::WriteBarrier::DijkstraMarkingBarrierSlow(), cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::HeapObjectHeader::GetName(), cppgc::internal::BaseObjectSizeTrait::GetObjectSizeForGarbageCollectedMixin(), cppgc::internal::StrongPersistentPolicy::GetPersistentRegion(), cppgc::internal::WeakPersistentPolicy::GetPersistentRegion(), cppgc::internal::StrongCrossThreadPersistentPolicy::GetPersistentRegion(), cppgc::internal::WeakCrossThreadPersistentPolicy::GetPersistentRegion(), cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor(), cppgc::internal::MarkingStateBase::MarkNoPush(), cppgc::internal::PrefinalizerRegistration::PrefinalizerRegistration(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), cppgc::internal::ExplicitManagementImpl::Resize(), cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlow(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList(), and cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader().
heap()
HeapBase & cppgc::internal::BasePage::heap () const
Definition at line 35 of file heap-page.cc.
                               {
  return static_cast<HeapBase&>(heap_handle_);
}
References cppgc::internal::BasePageHandle::heap_handle_.
Referenced by cppgc::internal::LargePage::Destroy(), cppgc::internal::NormalPage::Destroy(), cppgc::internal::WriteBarrier::DijkstraMarkingBarrierSlow(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::StrongPersistentPolicy::GetPersistentRegion(), cppgc::internal::WeakPersistentPolicy::GetPersistentRegion(), cppgc::internal::StrongCrossThreadPersistentPolicy::GetPersistentRegion(), cppgc::internal::WeakCrossThreadPersistentPolicy::GetPersistentRegion(), cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung(), cppgc::internal::ExplicitManagementImpl::Resize(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlow(), cppgc::internal::LargePage::TryCreate(), and cppgc::internal::ConservativeTracingVisitor::TryTracePointerConservatively().
IncrementDiscardedMemory()
void cppgc::internal::BasePage::IncrementDiscardedMemory (size_t value) [inline]
Definition at line 92 of file heap-page.h.
                                              {
    DCHECK_GE(discarded_memory_ + value, discarded_memory_);
    discarded_memory_ += value;
  }
References DCHECK_GE, and v8::internal::value.
IncrementMarkedBytes()
void cppgc::internal::BasePage::IncrementMarkedBytes (size_t value) [inline]
Definition at line 99 of file heap-page.h.
                                          {
    const size_t old_marked_bytes =
        marked_bytes_.fetch_add(value, std::memory_order_relaxed);
    USE(old_marked_bytes);
    DCHECK_GE(old_marked_bytes + value, old_marked_bytes);
  }
References DCHECK_GE, USE, and v8::internal::value.
Referenced by cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow().
is_large()
bool cppgc::internal::BasePage::is_large () const [inline]
Definition at line 47 of file heap-page.h.
{ return type_ == PageType::kLarge; }
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter(), AllocatedBytesAtLastGC(), AllocatedSize(), Destroy(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), PayloadEnd(), PayloadStart(), cppgc::internal::ExplicitManagementImpl::Resize(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::HeapVisitor< Derived >::Traverse(), and TryObjectHeaderFromInnerAddress().
marked_bytes()
size_t cppgc::internal::BasePage::marked_bytes () const [inline]
Definition at line 114 of file heap-page.h.
                              {
    return marked_bytes_.load(std::memory_order_relaxed);
  }
Referenced by cppgc::internal::MarkingVerifierBase::ReportLargePage(), cppgc::internal::MarkingVerifierBase::ReportNormalPage(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), cppgc::internal::MarkingVerifierBase::VisitLargePage(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitLargePage(), cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitLargePage(), and cppgc::internal::MarkingVerifierBase::VisitNormalPage().
ObjectHeaderFromInnerAddress() [1/2]
template<AccessMode mode>
const HeapObjectHeader & cppgc::internal::BasePage::ObjectHeaderFromInnerAddress (const void * address) const
Definition at line 345 of file heap-page.h.
                               {
  // This method might be called for |address| found via a Trace method of
  // another object. If |address| is on a newly allocated page , there will
  // be no sync between the page allocation and a concurrent marking thread,
  // resulting in a race with page initialization (specifically with writing
  // the page |type_| field). This can occur when tracing a Member holding a
  // reference to a mixin type
  SynchronizedLoad();
  const HeapObjectHeader* header =
      ObjectHeaderFromInnerAddressImpl<mode>(this, address);
  DCHECK_NE(kFreeListGCInfoIndex, header->GetGCInfoIndex<mode>());
  return *header;
}
References DCHECK_NE, cppgc::internal::HeapObjectHeader::GetGCInfoIndex(), cppgc::internal::kFreeListGCInfoIndex, mode(), and SynchronizedLoad().
ObjectHeaderFromInnerAddress() [2/2]
template<AccessMode mode>
HeapObjectHeader & cppgc::internal::BasePage::ObjectHeaderFromInnerAddress (void * address) const
Definition at line 339 of file heap-page.h.
                                                                            {
  return const_cast<HeapObjectHeader&>(
      ObjectHeaderFromInnerAddress<mode>(const_cast<const void*>(address)));
}
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter(), cppgc::internal::WriteBarrier::DijkstraMarkingBarrierSlow(), cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress(), cppgc::internal::BaseObjectSizeTrait::GetObjectSizeForGarbageCollectedMixin(), cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor(), and cppgc::internal::WriteBarrier::SteeleMarkingBarrierSlow().
operator=()
BasePage& cppgc::internal::BasePage::operator= (const BasePage &) [delete]
PayloadEnd() [1/2]
Address cppgc::internal::BasePage::PayloadEnd ()
Definition at line 77 of file heap-page.cc.
                             {
  return is_large() ? LargePage::From(this)->PayloadEnd()
                    : NormalPage::From(this)->PayloadEnd();
}
References cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), is_large(), cppgc::internal::NormalPage::PayloadEnd(), and cppgc::internal::LargePage::PayloadEnd().
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung(), and PayloadEnd().
PayloadEnd() [2/2]
ConstAddress cppgc::internal::BasePage::PayloadEnd () const
Definition at line 82 of file heap-page.cc.
                                        {
  return const_cast<BasePage*>(this)->PayloadEnd();
}
References PayloadEnd().
PayloadStart() [1/2]
Address cppgc::internal::BasePage::PayloadStart ()
Definition at line 68 of file heap-page.cc.
                               {
  return is_large() ? LargePage::From(this)->PayloadStart()
                    : NormalPage::From(this)->PayloadStart();
}
References cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), is_large(), cppgc::internal::NormalPage::PayloadStart(), and cppgc::internal::LargePage::PayloadStart().
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung(), and PayloadStart().
PayloadStart() [2/2]
ConstAddress cppgc::internal::BasePage::PayloadStart () const
Definition at line 73 of file heap-page.cc.
                                          {
  return const_cast<BasePage*>(this)->PayloadStart();
}
References PayloadStart().
ResetDiscardedMemory()
void cppgc::internal::BasePage::ResetDiscardedMemory () [inline]
Definition at line 96 of file heap-page.h.
{ discarded_memory_ = 0; }
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::ConcurrentSweepTask::VisitNormalPage().
ResetMarkedBytes()
void cppgc::internal::BasePage::ResetMarkedBytes (size_t new_value = 0) [inline]
Definition at line 111 of file heap-page.h.
                                              {
    marked_bytes_.store(new_value, std::memory_order_relaxed);
  }
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepNormalPage(), cppgc::internal::SequentialUnmarker::VisitLargePage(), and cppgc::internal::SequentialUnmarker::VisitNormalPage().
set_as_containing_young_objects()
void cppgc::internal::BasePage::set_as_containing_young_objects (bool value) [inline]
Definition at line 119 of file heap-page.h.
                                                   {
    contains_young_objects_ = value;
  }
References v8::internal::value.
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung().
space()
BaseSpace& cppgc::internal::BasePage::space () const [inline]
Definition at line 45 of file heap-page.h.
{ return *space_; }
Referenced by cppgc::internal::anonymous_namespace{compactor.cc}::MovableReferences::AddOrFilter(), cppgc::internal::anonymous_namespace{compactor.cc}::CompactionState::AddPage(), cppgc::internal::NormalPage::begin(), ChangeOwner(), Destroy(), cppgc::internal::LargePage::Destroy(), cppgc::internal::NormalPage::Destroy(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::internal::MarkingVerifierBase::ReportLargePage(), cppgc::internal::MarkingVerifierBase::ReportNormalPage(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::SweepLiveLargePage(), cppgc::internal::LargePage::TryCreate(), cppgc::internal::NormalPage::TryCreate(), TryObjectHeaderFromInnerAddress(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
SynchronizedLoad()
void cppgc::internal::BasePage::SynchronizedLoad () const [inline]
Definition at line 80 of file heap-page.h.
                                {
#if defined(THREAD_SANITIZER)
    v8::base::AsAtomicPtr(&type_)->load(std::memory_order_acquire);
#endif
  }
References v8::base::AsAtomicPtr().
Referenced by cppgc::internal::TraceTraitFromInnerAddressImpl::GetTraceDescriptor(), ObjectHeaderFromInnerAddress(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists().
SynchronizedStore()
void cppgc::internal::BasePage::SynchronizedStore () [inline]
Definition at line 85 of file heap-page.h.
                           {
    std::atomic_thread_fence(std::memory_order_seq_cst);
#if defined(THREAD_SANITIZER)
    v8::base::AsAtomicPtr(&type_)->store(type_, std::memory_order_release);
#endif
  }
References v8::base::AsAtomicPtr().
Referenced by cppgc::internal::LargePage::TryCreate().
TryObjectHeaderFromInnerAddress() [1/2]
const HeapObjectHeader * cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress (const void * address) const
Definition at line 104 of file heap-page.cc.
                               {
  if (is_large()) {
    if (!LargePage::From(this)->PayloadContains(
            static_cast<ConstAddress>(address)))
      return nullptr;
  } else {
    const NormalPage* normal_page = NormalPage::From(this);
    if (!normal_page->PayloadContains(static_cast<ConstAddress>(address)))
      return nullptr;
    // Check that the space has no linear allocation buffer.
    DCHECK(!NormalPageSpace::From(normal_page->space())
                .linear_allocation_buffer()
                .size());
  }
  // |address| is on the heap, so we FromInnerAddress can get the header.
  const HeapObjectHeader* header =
      ObjectHeaderFromInnerAddressImpl(this, address);
  if (header->IsFree()) return nullptr;
  DCHECK_NE(kFreeListGCInfoIndex, header->GetGCInfoIndex());
  return header;
}
References DCHECK, DCHECK_NE, cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::NormalPageSpace::From(), cppgc::internal::HeapObjectHeader::GetGCInfoIndex(), is_large(), cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::kFreeListGCInfoIndex, cppgc::internal::NormalPageSpace::linear_allocation_buffer(), cppgc::internal::ObjectHeaderFromInnerAddressImpl(), cppgc::internal::NormalPage::PayloadContains(), cppgc::internal::NormalPageSpace::LinearAllocationBuffer::size(), and space().
TryObjectHeaderFromInnerAddress() [2/2]
HeapObjectHeader * cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress (void * address) const
Definition at line 98 of file heap-page.cc.
                         {
  return const_cast<HeapObjectHeader*>(
      TryObjectHeaderFromInnerAddress(const_cast<const void*>(address)));
}
Referenced by cppgc::internal::ConservativeTracingVisitor::TryTracePointerConservatively().
Member Data Documentation
contains_young_objects_
bool cppgc::internal::BasePage::contains_young_objects_ = false [private]
Definition at line 144 of file heap-page.h.
discarded_memory_
size_t cppgc::internal::BasePage::discarded_memory_ = 0 [private]
Definition at line 148 of file heap-page.h.
marked_bytes_
std::atomic<size_t> cppgc::internal::BasePage::marked_bytes_ {0} [private]
Definition at line 149 of file heap-page.h.
space_
BaseSpace* cppgc::internal::BasePage::space_ [private]
Definition at line 142 of file heap-page.h.
Referenced by BasePage(), and ChangeOwner().
type_
PageType cppgc::internal::BasePage::type_ [private]
Definition at line 143 of file heap-page.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-page.h
/mnt/V8SourceCode/src/heap/cppgc/heap-page.cc