v8::internal::compiler::JSGetTemplateObjectNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSGetTemplateObjectNode (Node *node)
const GetTemplateObjectParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1237 of file js-operator.h.
Constructor & Destructor Documentation
JSGetTemplateObjectNode()
constexpr v8::internal::compiler::JSGetTemplateObjectNode::JSGetTemplateObjectNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1239 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSGetTemplateObject, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const GetTemplateObjectParameters& v8::internal::compiler::JSGetTemplateObjectNode::Parameters () const [inline]
Definition at line 1244 of file js-operator.h.
                                                        {
    return GetTemplateObjectParametersOf(node()->op());
  }
References v8::internal::compiler::GetTemplateObjectParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h