v8::internal::SaveContext Class Reference
#include <isolate.h>
Public Member Functions
SaveContext (Isolate *isolate)
~SaveContext ()
Private Attributes
Isolate *const isolate_
Handle< Context > context_
Handle< Context > topmost_script_having_context_
Detailed Description
Definition at line 3004 of file isolate.h.
Constructor & Destructor Documentation
SaveContext()
v8::internal::SaveContext::SaveContext (Isolate * isolate) [explicit]
Definition at line 7450 of file isolate.cc.
                                         : isolate_(isolate) {
  if (!isolate->context().is_null()) {
    context_ = Handle<Context>(isolate->context(), isolate);
  }
  if (!isolate->topmost_script_having_context().is_null()) {
    topmost_script_having_context_ =
        Handle<Context>(isolate->topmost_script_having_context(), isolate);
  }
}
References v8::internal::Isolate::context(), context_, v8::internal::Isolate::topmost_script_having_context(), and topmost_script_having_context_.
 SaveContext()
v8::internal::SaveContext::~SaveContext ()
Definition at line 7460 of file isolate.cc.
                          {
  isolate_->set_context(context_.is_null() ? Tagged<Context>() : *context_);
  isolate_->set_topmost_script_having_context(
      topmost_script_having_context_.is_null()
          ? Tagged<Context>()
          : *topmost_script_having_context_);
}
References context_, isolate_, v8::internal::Isolate::set_context(), v8::internal::Isolate::set_topmost_script_having_context(), and topmost_script_having_context_.
Member Data Documentation
context_
Handle<Context> v8::internal::SaveContext::context_ [private]
Definition at line 3012 of file isolate.h.
Referenced by SaveContext(), and ~SaveContext().
isolate_
Isolate* const v8::internal::SaveContext::isolate_ [private]
Definition at line 3011 of file isolate.h.
Referenced by ~SaveContext().
topmost_script_having_context_
Handle<Context> v8::internal::SaveContext::topmost_script_having_context_ [private]
Definition at line 3013 of file isolate.h.
Referenced by SaveContext(), and ~SaveContext().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/isolate.h
/mnt/V8SourceCode/src/execution/isolate.cc