v8::internal::compiler::Node::InputEdges Class Reference
#include <node.h>
Classes
class iterator
Public Types
using value_type = Edge
Public Member Functions
iterator begin () const
iterator end () const
bool empty () const
int count () const
value_type operator[] (int index) const
InputEdges (ZoneNodePtr *input_root, Use *use_root, int count)
Private Attributes
ZoneNodePtr * input_root_
Use * use_root_
int count_
Detailed Description
Definition at line 377 of file node.h.
Member Typedef Documentation
value_type
using v8::internal::compiler::Node::InputEdges::value_type = Edge
Definition at line 379 of file node.h.
Constructor & Destructor Documentation
InputEdges()
v8::internal::compiler::Node::InputEdges::InputEdges (ZoneNodePtr * input_root, Use * use_root, int count) [inline]
Definition at line 390 of file node.h.
      : input_root_(input_root), use_root_(use_root), count_(count) {}
Member Function Documentation
begin()
Node::InputEdges::iterator v8::internal::compiler::Node::InputEdges::begin () const [inline]
Definition at line 543 of file node.h.
                                                   {
  return Node::InputEdges::iterator(use_root_, input_root_);
}
References v8::internal::compiler::Node::input_root_.
Referenced by v8::internal::compiler::ControlEquivalence::DFSPush(), v8::internal::compiler::Node::UseEdges::empty(), and v8::internal::compiler::Node::Uses::empty().
count()
int v8::internal::compiler::Node::InputEdges::count () const [inline]
Definition at line 386 of file node.h.
{ return count_; }
References v8::internal::compiler::Node::count_.
empty()
bool v8::internal::compiler::Node::InputEdges::empty () const [inline]
Definition at line 385 of file node.h.
{ return count_ == 0; }
References v8::internal::compiler::Node::count_.
end()
Node::InputEdges::iterator v8::internal::compiler::Node::InputEdges::end () const [inline]
Definition at line 548 of file node.h.
                                                 {
  return Node::InputEdges::iterator(use_root_ - count_, input_root_ + count_);
}
References v8::internal::compiler::Node::count_, and v8::internal::compiler::Node::input_root_.
Referenced by v8::internal::compiler::Node::UseEdges::empty(), v8::internal::compiler::Node::Uses::empty(), and v8::internal::compiler::ControlEquivalence::RunUndirectedDFS().
operator[]()
Edge v8::internal::compiler::Node::InputEdges::operator[] (int index) const [inline]
Definition at line 552 of file node.h.
                                               {
  return Edge(use_root_ + index, input_root_ + index);
}
References v8::internal::compiler::Node::Edge, v8::internal::index, and v8::internal::compiler::Node::input_root_.
Member Data Documentation
count_
int v8::internal::compiler::Node::InputEdges::count_ [private]
Definition at line 396 of file node.h.
input_root_
ZoneNodePtr* v8::internal::compiler::Node::InputEdges::input_root_ [private]
Definition at line 394 of file node.h.
use_root_
Use* v8::internal::compiler::Node::InputEdges::use_root_ [private]
Definition at line 395 of file node.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node.h