v8::internal::JSDisposableStackBase Class Reference
#include <js-disposable-stack.h>
Public Types
enum class AsyncDisposableStackContextSlots { kStack = Context::MIN_CONTEXT_SLOTS
, kOuterPromise
, kLength
 }
enum class AsyncDisposeFromSyncDisposeContextSlots { kMethod = Context::MIN_CONTEXT_SLOTS
, kLength
 }
Public Member Functions
DisposableStackState state () const
void set_state (DisposableStackState value)
Static Public Member Functions
static void InitializeJSDisposableStackBase (Isolate *isolate, DirectHandle< JSDisposableStackBase > stack)
static void Add (Isolate *isolate, DirectHandle< JSDisposableStackBase > disposable_stack, DirectHandle< Object > value, DirectHandle< Object > method, DisposeMethodCallType type, DisposeMethodHint hint)
static MaybeDirectHandle< Object > CheckValueAndGetDisposeMethod (Isolate *isolate, DirectHandle< JSAny > value, DisposeMethodHint hint)
static MaybeDirectHandle< Object > DisposeResources (Isolate *isolate, DirectHandle< JSDisposableStackBase > disposable_stack, DisposableStackResourcesType resources_type)
static MaybeDirectHandle< JSReceiver > ResolveAPromiseWithValueAndReturnIt (Isolate *isolate, DirectHandle< Object > value)
static void HandleErrorInDisposal (Isolate *isolate, DirectHandle< JSDisposableStackBase > disposable_stack, DirectHandle< Object > current_error, DirectHandle< Object > current_error_message)
Detailed Description
Definition at line 46 of file js-disposable-stack.h.
Member Enumeration Documentation
AsyncDisposableStackContextSlots
enum v8::internal::JSDisposableStackBase::AsyncDisposableStackContextSlots [strong]
Enumerator
kStack
kOuterPromise
kLength
Definition at line 61 of file js-disposable-stack.h.
                                              {
    kStack = Context::MIN_CONTEXT_SLOTS,
    kOuterPromise,
    kLength,
  };
AsyncDisposeFromSyncDisposeContextSlots
enum v8::internal::JSDisposableStackBase::AsyncDisposeFromSyncDisposeContextSlots [strong]
Enumerator
kMethod
kLength
Definition at line 67 of file js-disposable-stack.h.
                                                     {
    kMethod = Context::MIN_CONTEXT_SLOTS,
    kLength,
  };
Member Function Documentation
Add()
static void v8::internal::JSDisposableStackBase::Add (Isolate * isolate, DirectHandle< JSDisposableStackBase > disposable_stack, DirectHandle< Object > value, DirectHandle< Object > method, DisposeMethodCallType type, DisposeMethodHint hint) [static]
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::AddToDisposableStack(), and v8::internal::BUILTIN().
CheckValueAndGetDisposeMethod()
MaybeDirectHandle< Object > v8::internal::JSDisposableStackBase::CheckValueAndGetDisposeMethod (Isolate * isolate, DirectHandle< JSAny > value, DisposeMethodHint hint) [inline], [static]
Definition at line 65 of file js-disposable-stack-inl.h.
                                                                             {
  DirectHandle<Object> method;
  if (hint == DisposeMethodHint::kSyncDispose) {
    // 1. If method is not present, then
    // a. If V is either null or undefined, then
    // i. Set V to undefined.
    // ii. Set method to undefined.
    // We has already returned from the caller if V is null or undefined, when
    // hint is `kSyncDispose`.
    DCHECK(!IsNullOrUndefined(*value));
    // b. Else,
    // i. If V is not an Object, throw a TypeError exception.
    if (!IsJSReceiver(*value)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kExpectAnObjectWithUsing));
    }
    // ii. Set method to ? GetDisposeMethod(V, hint).
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, method,
        Object::GetProperty(isolate, value,
                            isolate->factory()->dispose_symbol()));
    // (GetMethod)3. If IsCallable(func) is false, throw a TypeError
    // exception.
    if (!IsJSFunction(*method)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kNotCallable,
                                   isolate->factory()->dispose_symbol()));
    }
    // iii. If method is undefined, throw a TypeError exception.
    // It is already checked in step ii.
  } else if (hint == DisposeMethodHint::kAsyncDispose) {
    // 1. If method is not present, then
    // a. If V is either null or undefined, then
    // i. Set V to undefined.
    // ii. Set method to undefined.
    if (IsNullOrUndefined(*value)) {
      return isolate->factory()->undefined_value();
    }
    // b. Else,
    // i. If V is not an Object, throw a TypeError exception.
    if (!IsJSReceiver(*value)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kExpectAnObjectWithUsing));
    }
    // https://tc39.es/proposal-explicit-resource-management/#sec-getdisposemethod
    // 1. If hint is async-dispose, then
    // a. Let method be ? GetMethod(V, @@asyncDispose).
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, method,
        Object::GetProperty(isolate, value,
                            isolate->factory()->async_dispose_symbol()));
    // b. If method is undefined, then
    if (IsNullOrUndefined(*method)) {
      // i. Set method to ? GetMethod(V, @@dispose).
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate, method,
          Object::GetProperty(isolate, value,
                              isolate->factory()->dispose_symbol()));
      // (GetMethod)3. If IsCallable(func) is false, throw a TypeError
      // exception.
      if (!IsJSFunction(*method)) {
        THROW_NEW_ERROR(isolate,
                        NewTypeError(MessageTemplate::kNotCallable,
                                     isolate->factory()->dispose_symbol()));
      }
      // ii. If method is not undefined, then
      if (!IsUndefined(*method)) {
        // 1. Let closure be a new Abstract Closure with no parameters that
        // captures method and performs the following steps when called:
        // a. Let O be the this value.
        // b. Let promiseCapability be ! NewPromiseCapability(%Promise%).
        // c. Let result be Completion(Call(method, O)).
        // d. IfAbruptRejectPromise(result, promiseCapability).
        // e. Perform ? Call(promiseCapability.[[Resolve]], undefined, «
        // undefined »).
        // f. Return promiseCapability.[[Promise]].
        // 2. NOTE: This function is not observable to user code. It is
        // used to ensure that a Promise returned from a synchronous
        // @@dispose method will not be awaited and that any exception
        // thrown will not be thrown synchronously.
        // 3. Return CreateBuiltinFunction(closure, 0, "", « »).
        // (TODO:rezvan): Add `kAsyncFromSyncDispose` to the `DisposeMethodHint`
        // enum and remove the following allocation of adapter closure.
        DirectHandle<Context> async_dispose_from_sync_dispose_context =
            isolate->factory()->NewBuiltinContext(
                isolate->native_context(),
                static_cast<int>(
                    AsyncDisposeFromSyncDisposeContextSlots::kLength));
        async_dispose_from_sync_dispose_context->SetNoCell(
            static_cast<int>(AsyncDisposeFromSyncDisposeContextSlots::kMethod),
            *method);
        method =
            Factory::JSFunctionBuilder{
                isolate,
                isolate->factory()
                    ->async_dispose_from_sync_dispose_shared_fun(),
                async_dispose_from_sync_dispose_context}
                .Build();
      }
    }
    // (GetMethod)3. If IsCallable(func) is false, throw a TypeError
    // exception.
    if (!IsJSFunction(*method)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kNotCallable,
                                   isolate->factory()->async_dispose_symbol()));
    }
  }
  return method;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), v8::internal::IsNullOrUndefined(), v8::internal::kAsyncDispose, kLength, kMethod, v8::internal::kSyncDispose, v8::internal::Isolate::native_context(), v8::internal::Factory::NewBuiltinContext(), THROW_NEW_ERROR, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::AddToDisposableStack(), and v8::internal::BUILTIN().
DisposeResources()
MaybeDirectHandle< Object > v8::internal::JSDisposableStackBase::DisposeResources (Isolate * isolate, DirectHandle< JSDisposableStackBase > disposable_stack, DisposableStackResourcesType resources_type) [static]
Definition at line 47 of file js-disposable-stack.cc.
                                                 {
  DCHECK(!IsUndefined(disposable_stack->stack()));
  DCHECK_EQ(disposable_stack->state(), DisposableStackState::kDisposed);
  DirectHandle<FixedArray> stack(disposable_stack->stack(), isolate);
  // 1. Let needsAwait be false.
  // 2. Let hasAwaited be false.
  // `false` is assigned to both in the initialization of the DisposableStack.
  int length = disposable_stack->length();
  MaybeDirectHandle<Object> result;
  // 3. For each element resource of
  // disposeCapability.[[DisposableResourceStack]], in reverse list order, do
  while (length > 0) {
    // a. Let value be resource.[[ResourceValue]].
    // b. Let hint be resource.[[Hint]].
    // c. Let method be resource.[[DisposeMethod]].
    Tagged<Object> stack_type = stack->get(--length);
    Tagged<Object> tagged_method = stack->get(--length);
    DirectHandle<Object> method(tagged_method, isolate);
    Tagged<Object> tagged_value = stack->get(--length);
    DirectHandle<Object> value(tagged_value, isolate);
    DirectHandle<Object> args[] = {value};
    auto stack_type_case = static_cast<int>(Cast<Smi>(stack_type).value());
    DisposeMethodCallType call_type =
        DisposeCallTypeBit::decode(stack_type_case);
    DisposeMethodHint hint = DisposeHintBit::decode(stack_type_case);
    // d. If hint is sync-dispose and needsAwait is true and hasAwaited is
    // false, then
    // i. Perform ! Await(undefined).
    // ii. Set needsAwait to false.
    if (hint == DisposeMethodHint::kSyncDispose &&
        disposable_stack->needs_await() == true &&
        disposable_stack->has_awaited() == false) {
      // i. Perform ! Await(undefined).
      // ii. Set needsAwait to false.
      disposable_stack->set_needs_await(false);
      return ResolveAPromiseWithValueAndReturnIt(
          isolate, isolate->factory()->undefined_value());
    }
    // e. If method is not undefined, then
    if (!IsUndefined(*method)) {
      // i. Let result be Completion(Call(method, value)).
      if (call_type == DisposeMethodCallType::kValueIsReceiver) {
        result = Execution::Call(isolate, method, value, {});
      } else if (call_type == DisposeMethodCallType::kValueIsArgument) {
        result = Execution::Call(isolate, method,
                                 isolate->factory()->undefined_value(),
                                 base::VectorOf(args));
      }
      DirectHandle<Object> result_handle;
      // ii. If result is a normal completion and hint is async-dispose, then
      // 1. Set result to Completion(Await(result.[[Value]])).
      // 2. Set hasAwaited to true.
      if (result.ToHandle(&result_handle)) {
        if (hint == DisposeMethodHint::kAsyncDispose) {
          DCHECK_NE(resources_type, DisposableStackResourcesType::kAllSync);
          disposable_stack->set_length(length);
          disposable_stack->set_has_awaited(true);
          MaybeDirectHandle<JSReceiver> resolved_promise =
              ResolveAPromiseWithValueAndReturnIt(isolate, result_handle);
          if (resolved_promise.is_null()) {
            // iii. If result is a throw completion, then
            // 1. If completion is a throw completion, then
            // a. Set result to result.[[Value]].
            // b. Let suppressed be completion.[[Value]].
            // c. Let error be a newly created SuppressedError object.
            // d. Perform CreateNonEnumerableDataPropertyOrThrow(error,
            // "error", result).
            // e. Perform CreateNonEnumerableDataPropertyOrThrow(error,
            // "suppressed", suppressed).
            // f. Set completion to ThrowCompletion(error).
            // 2. Else,
            // a. Set completion to result.
            CHECK_EXCEPTION_ON_DISPOSAL(isolate, disposable_stack, {});
          } else {
            return resolved_promise;
          }
        }
      } else {
        CHECK_EXCEPTION_ON_DISPOSAL(isolate, disposable_stack, {});
      }
    } else {
      // Else,
      // i. Assert: hint is async-dispose.
      DCHECK_EQ(hint, DisposeMethodHint::kAsyncDispose);
      // ii. Set needsAwait to true.
      // iii. NOTE: This can only indicate a case where either null or
      // undefined was the initialized value of an await using declaration.
      disposable_stack->set_length(length);
      disposable_stack->set_needs_await(true);
    }
  }
  // 4. If needsAwait is true and hasAwaited is false, then
  // a. Perform ! Await(undefined).
  if (disposable_stack->needs_await() == true &&
      disposable_stack->has_awaited() == false) {
    disposable_stack->set_length(length);
    disposable_stack->set_has_awaited(true);
    return ResolveAPromiseWithValueAndReturnIt(
        isolate, isolate->factory()->undefined_value());
  }
  // 5. NOTE: After disposeCapability has been disposed, it will never be used
  // again. The contents of disposeCapability.[[DisposableResourceStack]] can be
  // discarded in implementations, such as by garbage collection, at this point.
  // 6. Set disposeCapability.[[DisposableResourceStack]] to a new empty List.
  disposable_stack->set_stack(ReadOnlyRoots(isolate).empty_fixed_array());
  disposable_stack->set_length(0);
  Handle<Object> existing_error_handle(disposable_stack->error(), isolate);
  DirectHandle<Object> existing_error_message_handle(
      disposable_stack->error_message(), isolate);
  disposable_stack->set_error(*(isolate->factory()->uninitialized_value()));
  disposable_stack->set_error_message(
      *(isolate->factory()->uninitialized_value()));
  // 7. Return ? completion.
  if (!IsUninitialized(*existing_error_handle)) {
    if (disposable_stack->suppressed_error_created() == true) {
      // Created SuppressedError is intentionally suppressed here for debug.
      SuppressDebug while_processing(isolate->debug());
      isolate->Throw(*existing_error_handle);
    } else {
      isolate->ReThrow(*existing_error_handle, *existing_error_message_handle);
    }
    return MaybeDirectHandle<Object>();
  }
  return isolate->factory()->true_value();
}
References v8::base::args, v8::internal::Execution::Call(), CHECK_EXCEPTION_ON_DISPOSAL, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::debug(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::Isolate::factory(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::kAllSync, v8::internal::kAsyncDispose, v8::internal::kDisposed, v8::internal::kSyncDispose, v8::internal::kValueIsArgument, v8::internal::kValueIsReceiver, v8::internal::length, ResolveAPromiseWithValueAndReturnIt(), v8::base::internal::result, v8::internal::Isolate::ReThrow(), v8::internal::stack, v8::internal::Isolate::Throw(), v8::internal::value, and v8::base::VectorOf().
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
HandleErrorInDisposal()
void v8::internal::JSDisposableStackBase::HandleErrorInDisposal (Isolate * isolate, DirectHandle< JSDisposableStackBase > disposable_stack, DirectHandle< Object > current_error, DirectHandle< Object > current_error_message) [inline], [static]
Definition at line 185 of file js-disposable-stack-inl.h.
                                                {
  DCHECK(isolate->is_catchable_by_javascript(*current_error));
  DirectHandle<Object> maybe_error(disposable_stack->error(), isolate);
  // i. If completion is a throw completion, then
  if (!IsUninitialized(*maybe_error)) {
    // 1. Set result to result.[[Value]].
    // 2. Let suppressed be completion.[[Value]].
    // 3. Let error be a newly created SuppressedError object.
    // 4. Perform CreateNonEnumerableDataPropertyOrThrow(error, "error",
    // result).
    // 5. Perform CreateNonEnumerableDataPropertyOrThrow(error,
    // "suppressed", suppressed).
    // 6. Set completion to ThrowCompletion(error).
    maybe_error = isolate->factory()->NewSuppressedErrorAtDisposal(
        isolate, current_error, maybe_error);
    disposable_stack->set_suppressed_error_created(true);
  } else {
    // ii. Else,
    // 1. Set completion to result.
    maybe_error = current_error;
  }
  disposable_stack->set_error(*maybe_error);
  disposable_stack->set_error_message(*current_error_message);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::Isolate::is_catchable_by_javascript(), and v8::internal::Factory::NewSuppressedErrorAtDisposal().
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
InitializeJSDisposableStackBase()
void v8::internal::JSDisposableStackBase::InitializeJSDisposableStackBase (Isolate * isolate, DirectHandle< JSDisposableStackBase > stack) [static]
Definition at line 6420 of file objects.cc.
                                                                            {
  DirectHandle<FixedArray> array = isolate->factory()->NewFixedArray(0);
  disposable_stack->set_stack(*array);
  disposable_stack->set_needs_await(false);
  disposable_stack->set_has_awaited(false);
  disposable_stack->set_suppressed_error_created(false);
  disposable_stack->set_length(0);
  disposable_stack->set_state(DisposableStackState::kPending);
  disposable_stack->set_error(*(isolate->factory()->uninitialized_value()));
  disposable_stack->set_error_message(
      *(isolate->factory()->uninitialized_value()));
}
References v8::internal::Isolate::factory(), v8::internal::kPending, and v8::internal::FactoryBase< Impl >::NewFixedArray().
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
ResolveAPromiseWithValueAndReturnIt()
MaybeDirectHandle< JSReceiver > v8::internal::JSDisposableStackBase::ResolveAPromiseWithValueAndReturnIt (Isolate * isolate, DirectHandle< Object > value) [static]
Definition at line 199 of file js-disposable-stack.cc.
                                                  {
  DirectHandle<JSFunction> promise_function = isolate->promise_function();
  DirectHandle<Object> args[] = {value};
  DirectHandle<Object> result;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, result,
      Execution::CallBuiltin(isolate, isolate->promise_resolve(),
                             promise_function, base::VectorOf(args)),
      MaybeDirectHandle<JSReceiver>());
  return Cast<JSReceiver>(result);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Execution::CallBuiltin(), v8::base::internal::result, v8::internal::value, and v8::base::VectorOf().
Referenced by DisposeResources().
set_state()
void v8::internal::JSDisposableStackBase::set_state (DisposableStackState value) [inline]
state()
DisposableStackState v8::internal::JSDisposableStackBase::state () const [inline]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-disposable-stack.h
/mnt/V8SourceCode/src/objects/js-disposable-stack-inl.h
/mnt/V8SourceCode/src/objects/js-disposable-stack.cc
/mnt/V8SourceCode/src/objects/objects.cc