v8::base::OS Class Reference
#include <platform.h>
Classes
class MemoryMappedFile
struct MemoryRange
struct SharedLibraryAddress
struct StackFrame
Public Types
enum class MemoryPermission {
kNoAccess
, kRead
, kReadWrite
, kReadWriteExecute
,
kReadExecute
, kNoAccessWillJitLater
 }
using Address = uintptr_t
Static Public Member Functions
static void Initialize (AbortMode abort_mode, const char *const gc_fake_mmap)
static bool IsHardwareEnforcedShadowStacksEnabled ()
static void EnsureAlternativeSignalStackIsAvailableForCurrentThread ()
static int GetUserTime (uint32_t *secs, uint32_t *usecs)
static int GetPeakMemoryUsageKb ()
static double TimeCurrentMillis ()
static TimezoneCache * CreateTimezoneCache ()
static int GetLastError ()
static FILE * FOpen (const char *path, const char *mode)
static bool Remove (const char *path)
static char DirectorySeparator ()
static bool isDirectorySeparator (const char ch)
static FILE * OpenTemporaryFile ()
static PRINTF_FORMAT (1, 2) void Print(const char *format
static static PRINTF_FORMAT (1, 0) void VPrint(const char *format
static PRINTF_FORMAT (2, 3) void FPrint(FILE *out
static const char static PRINTF_FORMAT (2, 0) void VFPrint(FILE *out
static PRINTF_FORMAT (1, 2) void PrintError(const char *format
static static PRINTF_FORMAT (1, 0) void VPrintError(const char *format
static PlatformSharedMemoryHandle CreateSharedMemoryHandleForTesting (size_t size)
static void DestroySharedMemoryHandle (PlatformSharedMemoryHandle handle)
static bool HasLazyCommits ()
static void Sleep (TimeDelta interval)
static void Abort ()
static void DebugBreak ()
static PRINTF_FORMAT (3, 4) int SNPrintF(char *str
static int const char static PRINTF_FORMAT (3, 0) int VSNPrintF(char *str
static void StrNCpy (char *dest, int length, const char *src, size_t n)
static std::vector< SharedLibraryAddress > GetSharedLibraryAddresses ()
static void SignalCodeMovingGC ()
static bool ArmUsingHardFloat ()
static int ActivationFrameAlignment ()
static int GetCurrentProcessId ()
static int GetCurrentThreadId ()
static void AdjustSchedulingParams ()
static std::optional< MemoryRange > GetFirstFreeMemoryRangeWithin (Address boundary_start, Address boundary_end, size_t minimum_size, size_t alignment)
static void ExitProcess (int exit_code)
static constexpr V8_WARN_UNUSED_RESULT bool IsRemapPageSupported ()
static V8_WARN_UNUSED_RESULT bool RemapPages (const void *address, size_t size, void *new_address, MemoryPermission access)
static void SetDataReadOnly (void *address, size_t size)
Public Attributes
static static va_list args
static const char * format
static const char static const char * format
static const char static const char va_list args
static int length
static int const char * format
static int const char static int length
static int const char static int const char * format
static int const char static int const char va_list args
Static Public Attributes
static const char *const LogFileOpenMode = `w+`
static const int kStackWalkError = -1
static const int kStackWalkMaxNameLen = 256
static const int kStackWalkMaxTextLen = 256
Private Member Functions
FRIEND_TEST (OS, RemapPages)
DISALLOW_IMPLICIT_CONSTRUCTORS (OS)
Static Private Member Functions
static int GetCurrentThreadIdInternal ()
static size_t AllocatePageSize ()
static size_t CommitPageSize ()
static void SetRandomMmapSeed (int64_t seed)
static void * GetRandomMmapAddr ()
static V8_WARN_UNUSED_RESULT void * Allocate (void *address, size_t size, size_t alignment, MemoryPermission access)
static V8_WARN_UNUSED_RESULT void * AllocateShared (size_t size, MemoryPermission access)
static V8_WARN_UNUSED_RESULT void * RemapShared (void *old_address, void *new_address, size_t size)
static void Free (void *address, size_t size)
static V8_WARN_UNUSED_RESULT void * AllocateShared (void *address, size_t size, OS::MemoryPermission access, PlatformSharedMemoryHandle handle, uint64_t offset)
static void FreeShared (void *address, size_t size)
static void Release (void *address, size_t size)
static V8_WARN_UNUSED_RESULT bool SetPermissions (void *address, size_t size, MemoryPermission access)
static V8_WARN_UNUSED_RESULT bool RecommitPages (void *address, size_t size, MemoryPermission access)
static V8_WARN_UNUSED_RESULT bool DiscardSystemPages (void *address, size_t size)
static V8_WARN_UNUSED_RESULT bool DecommitPages (void *address, size_t size)
static V8_WARN_UNUSED_RESULT bool SealPages (void *address, size_t size)
static V8_WARN_UNUSED_RESULT bool CanReserveAddressSpace ()
static V8_WARN_UNUSED_RESULT std::optional< AddressSpaceReservation > CreateAddressSpaceReservation (void *hint, size_t size, size_t alignment, MemoryPermission max_permission)
static void FreeAddressSpaceReservation (AddressSpaceReservation reservation)
Static Private Attributes
static const int msPerSecond = 1000
Friends
class AddressSpaceReservation
class MemoryMappedFile
class PosixMemoryMappedFile
class v8::base::PageAllocator
class v8::base::VirtualAddressSpace
class v8::base::VirtualAddressSubspace
Detailed Description
Definition at line 145 of file platform.h.
Member Typedef Documentation
Address
using v8::base::OS::Address = uintptr_t
Definition at line 320 of file platform.h.
Member Enumeration Documentation
MemoryPermission
enum v8::base::OS::MemoryPermission [strong]
Enumerator
kNoAccess
kRead
kReadWrite
kReadWriteExecute
kReadExecute
kNoAccessWillJitLater
Definition at line 220 of file platform.h.
                              {
    kNoAccess,
    kRead,
    kReadWrite,
    kReadWriteExecute,
    kReadExecute,
    // TODO(jkummerow): Remove this when Wasm has a platform-independent
    // w^x implementation.
    kNoAccessWillJitLater
  };
Member Function Documentation
Abort()
void v8::base::OS::Abort () [static]
Definition at line 759 of file platform-posix.cc.
               {
  switch (g_abort_mode) {
    case AbortMode::kExitWithSuccessAndIgnoreDcheckFailures:
      _exit(0);
    case AbortMode::kExitWithFailureAndIgnoreDcheckFailures:
      _exit(-1);
    case AbortMode::kImmediateCrash:
      IMMEDIATE_CRASH();
    case AbortMode::kDefault:
      break;
  }
  // Redirect to std abort to signal abnormal program termination.
  abort();
}
References v8::base::g_abort_mode, IMMEDIATE_CRASH, v8::base::kDefault, v8::base::kExitWithFailureAndIgnoreDcheckFailures, v8::base::kExitWithSuccessAndIgnoreDcheckFailures, and v8::base::kImmediateCrash.
Referenced by v8::internal::abort_with_reason(), v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::Isolate::CreateMessageOrAbort(), v8::internal::ExternalReferenceEncoder::Encode(), v8::internal::Serializer::EncodeExternalReference(), v8::base::FatalOOM(), v8::TryCatch::operator delete(), v8::HandleScope::operator delete(), v8::TryCatch::operator delete[](), v8::HandleScope::operator delete[](), v8::TryCatch::operator new(), v8::HandleScope::operator new(), v8::TryCatch::operator new[](), v8::HandleScope::operator new[](), v8::internal::Isolate::PushParamsAndDie(), v8::internal::Isolate::PushStackTraceAndDie(), v8::internal::torque::ls::ReadMessage(), v8::Utils::ReportApiFailure(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Isolate::StackTraceString(), V8_Fatal(), and v8::internal::torque::WrappedMain().
ActivationFrameAlignment()
int v8::base::OS::ActivationFrameAlignment () [static]
Definition at line 312 of file platform-posix.cc.
                                 {
#if V8_TARGET_ARCH_ARM
  // On EABI ARM targets this is required for fp correctness in the
  // runtime system.
  return 8;
#elif V8_TARGET_ARCH_S390X
  return 8;
#else
  // Otherwise we just assume 16 byte alignment, i.e.:
  // - With gcc 4.4 the tree vectorization optimizer can generate code
  // that requires 16 byte alignment such as movdqa on x86.
  // - Mac OS X, PPC and Solaris (64-bit) activation frames must
  // be 16 byte-aligned; see "Mac OS X ABI Function Call Guide"
  return 16;
#endif
}
Referenced by v8::internal::MacroAssembler::ActivationFrameAlignment(), v8::internal::MacroAssembler::CallCFunctionHelper(), v8::internal::compiler::CallCFunctionHelperLatency(), and v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState().
AdjustSchedulingParams()
void v8::base::OS::AdjustSchedulingParams () [static]
Definition at line 130 of file platform-aix.cc.
{}
Referenced by v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread().
Allocate()
void * v8::base::OS::Allocate (void * address, size_t size, size_t alignment, MemoryPermission access) [static], [private]
Definition at line 99 of file platform-cygwin.cc.
                                            {
  size_t page_size = AllocatePageSize();
  DCHECK_EQ(0, size % page_size);
  DCHECK_EQ(0, alignment % page_size);
  DCHECK_LE(page_size, alignment);
  hint = AlignedAddress(hint, alignment);
  DWORD flags = (access == OS::MemoryPermission::kNoAccess)
                    ? MEM_RESERVE
                    : MEM_RESERVE | MEM_COMMIT;
  DWORD protect = GetProtectionFromMemoryPermission(access);
  // First, try an exact size aligned allocation.
  uint8_t* base = RandomizedVirtualAlloc(size, flags, protect, hint);
  if (base == nullptr) return nullptr; // Can't allocate, we're OOM.
  // If address is suitably aligned, we're done.
  uint8_t* aligned_base = RoundUp(base, alignment);
  if (base == aligned_base) return reinterpret_cast<void*>(base);
  // Otherwise, free it and try a larger allocation.
  Free(base, size);
  // Clear the hint. It's unlikely we can allocate at this address.
  hint = nullptr;
  // Add the maximum misalignment so we are guaranteed an aligned base address
  // in the allocated region.
  size_t padded_size = size + (alignment - page_size);
  const int kMaxAttempts = 3;
  aligned_base = nullptr;
  for (int i = 0; i < kMaxAttempts; ++i) {
    base = RandomizedVirtualAlloc(padded_size, flags, protect, hint);
    if (base == nullptr) return nullptr; // Can't allocate, we're OOM.
    // Try to trim the allocation by freeing the padded allocation and then
    // calling VirtualAlloc at the aligned base.
    Free(base, padded_size);
    aligned_base = RoundUp(base, alignment);
    base = reinterpret_cast<uint8_t*>(
        VirtualAlloc(aligned_base, size, flags, protect));
    // We might not get the reduced allocation due to a race. In that case,
    // base will be nullptr.
    if (base != nullptr) break;
  }
  DCHECK_IMPLIES(base, base == aligned_base);
  return reinterpret_cast<void*>(base);
}
References AlignedAddress(), AllocatePageSize(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LE, flags(), Free(), v8::base::GetProtectionFromMemoryPermission(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kNoAccess, v8::base::anonymous_namespace{platform-cygwin.cc}::RandomizedVirtualAlloc(), RoundUp(), and size().
Referenced by v8::base::VirtualAddressSpace::AllocateGuardRegion(), v8::base::VirtualAddressSpace::AllocatePages(), v8::base::PageAllocator::AllocatePages(), and EnsureAlternativeSignalStackIsAvailableForCurrentThread().
AllocatePageSize()
size_t v8::base::OS::AllocatePageSize () [static], [private]
Definition at line 330 of file platform-posix.cc.
                            {
#if defined(V8_TARGET_OS_MACOS) && V8_HOST_ARCH_ARM64
  return kAppleArmPageSize;
#else
  static size_t page_size = static_cast<size_t>(sysconf(_SC_PAGESIZE));
  return page_size;
#endif
}
Referenced by v8::base::AddressSpaceReservation::Allocate(), Allocate(), AllocateShared(), CommitPageSize(), CreateAddressSpaceReservation(), v8::base::AddressSpaceReservation::CreateSubReservation(), EnsureAlternativeSignalStackIsAvailableForCurrentThread(), Free(), v8::base::AddressSpaceReservation::Free(), FreeShared(), v8::base::AddressSpaceReservation::FreeShared(), GetRandomMmapAddr(), RemapPages(), and v8::base::PosixMemoryMappedFile::~PosixMemoryMappedFile().
AllocateShared() [1/2]
void * v8::base::OS::AllocateShared (size_t size, MemoryPermission access) [static], [private]
Definition at line 491 of file platform-posix.cc.
                                                             {
  DCHECK_EQ(0, size % AllocatePageSize());
  return base::Allocate(nullptr, size, access, PageType::kShared);
}
References v8::base::Allocate(), AllocatePageSize(), DCHECK_EQ, v8::internal::anonymous_namespace{elements.cc}::kShared, and size().
Referenced by v8::base::VirtualAddressSpace::AllocateSharedPages(), and v8::base::PageAllocator::AllocateSharedPages().
AllocateShared() [2/2]
void * v8::base::OS::AllocateShared (void * address, size_t size, OS::MemoryPermission access, PlatformSharedMemoryHandle handle, uint64_t offset) [static], [private]
Definition at line 163 of file platform-darwin.cc.
                                                                             {
  DCHECK_EQ(0, size % AllocatePageSize());
  mach_vm_address_t addr = reinterpret_cast<mach_vm_address_t>(hint);
  vm_prot_t prot = GetVMProtFromMemoryPermission(access);
  mach_port_t shared_mem_port = MachMemoryEntryFromSharedMemoryHandle(handle);
  kern_return_t kr = mach_vm_map_wrapper(&addr, size, VM_FLAGS_FIXED,
                                         shared_mem_port, offset, prot);
  if (kr != KERN_SUCCESS) {
    // Retry without hint.
    kr = mach_vm_map_wrapper(&addr, size, VM_FLAGS_ANYWHERE, shared_mem_port,
                             offset, prot);
  }
  if (kr != KERN_SUCCESS) return nullptr;
  return reinterpret_cast<void*>(addr);
}
References AllocatePageSize(), DCHECK_EQ, v8::base::anonymous_namespace{platform-darwin.cc}::GetVMProtFromMemoryPermission(), v8::internal::handle(), v8::base::anonymous_namespace{platform-darwin.cc}::mach_vm_map_wrapper(), and size().
ArmUsingHardFloat()
static bool v8::base::OS::ArmUsingHardFloat () [static]
Referenced by v8::internal::MacroAssembler::use_eabi_hardfloat().
CanReserveAddressSpace()
bool v8::base::OS::CanReserveAddressSpace () [static], [private]
Definition at line 336 of file platform-fuchsia.cc.
{ return true; }
Referenced by v8::base::VirtualAddressSpace::CanAllocateSubspaces().
CommitPageSize()
size_t v8::base::OS::CommitPageSize () [static], [private]
Definition at line 340 of file platform-posix.cc.
                          {
  // Commit and allocate page size are the same on posix.
  return OS::AllocatePageSize();
}
References AllocatePageSize().
Referenced by DecommitPages(), v8::base::AddressSpaceReservation::DiscardSystemPages(), Release(), SetPermissions(), and v8::base::AddressSpaceReservation::SetPermissions().
CreateAddressSpaceReservation()
std::optional< AddressSpaceReservation > v8::base::OS::CreateAddressSpaceReservation (void * hint, size_t size, size_t alignment, MemoryPermission max_permission) [static], [private]
Definition at line 339 of file platform-fuchsia.cc.
                                     {
  DCHECK_EQ(0, reinterpret_cast<Address>(hint) % alignment);
  zx::vmar child;
  zx_vaddr_t child_addr;
  PlacementMode placement =
      hint != nullptr ? PlacementMode::kUseHint : PlacementMode::kAnywhere;
  zx_status_t status = CreateAddressSpaceReservationInternal(
      *zx::vmar::root_self(), g_root_vmar_base, AllocatePageSize(), hint,
      placement, size, alignment, max_permission, &child, &child_addr);
  if (status != ZX_OK) return {};
  return AddressSpaceReservation(reinterpret_cast<void*>(child_addr), size,
                                 child.release());
}
References AddressSpaceReservation, AllocatePageSize(), v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAddressSpaceReservationInternal(), DCHECK_EQ, v8::base::anonymous_namespace{platform-fuchsia.cc}::g_root_vmar_base, size(), and v8::internal::status.
Referenced by v8::base::VirtualAddressSpace::AllocateSubspace().
CreateSharedMemoryHandleForTesting()
PlatformSharedMemoryHandle v8::base::OS::CreateSharedMemoryHandleForTesting (size_t size) [static]
Definition at line 144 of file platform-darwin.cc.
                                                                             {
  mach_vm_size_t vm_size = size;
  mach_port_t port;
  kern_return_t kr = mach_make_memory_entry_64(
      mach_task_self(), &vm_size, 0,
      MAP_MEM_NAMED_CREATE | VM_PROT_READ | VM_PROT_WRITE, &port,
      MACH_PORT_NULL);
  if (kr != KERN_SUCCESS) return kInvalidSharedMemoryHandle;
  return SharedMemoryHandleFromMachMemoryEntry(port);
}
References v8::kInvalidSharedMemoryHandle, and size().
CreateTimezoneCache()
TimezoneCache * v8::base::OS::CreateTimezoneCache () [static]
Definition at line 82 of file platform-aix.cc.
{ return new AIXTimezoneCache(); }
Referenced by v8::internal::Intl::CreateTimeZoneCache().
DebugBreak()
void v8::base::OS::DebugBreak () [static]
Definition at line 775 of file platform-posix.cc.
                    {
#if V8_HOST_ARCH_ARM
  asm("bkpt 0");
#elif V8_HOST_ARCH_ARM64
  asm("brk 0");
#elif V8_HOST_ARCH_MIPS
  asm("break");
#elif V8_HOST_ARCH_MIPS64
  asm("break");
#elif V8_HOST_ARCH_LOONG64
  asm("break 0");
#elif V8_HOST_ARCH_PPC64
  asm("twge 2,2");
#elif V8_HOST_ARCH_IA32
  asm("int $3");
#elif V8_HOST_ARCH_X64
  asm("int $3");
#elif V8_OS_ZOS
  asm(" dc x'0001'");
#elif V8_HOST_ARCH_S390X
  // Software breakpoint instruction is 0x0001
  asm volatile(".word 0x0001");
#elif V8_HOST_ARCH_RISCV64
  asm("ebreak");
#elif V8_HOST_ARCH_RISCV32
  asm("ebreak");
#else
#error Unsupported host architecture.
#endif
}
Referenced by v8::internal::Assembler::breakpoint(), v8::internal::compiler::BreakOnNodeDecorator::Decorate(), and v8::internal::RUNTIME_FUNCTION().
DecommitPages()
bool v8::base::OS::DecommitPages (void * address, size_t size) [static], [private]
Definition at line 168 of file platform-aix.cc.
                                                 {
  // The difference between this implementation and the alternative under
  // platform-posix.cc is that on AIX, calling mmap on a pre-designated address
  // with MAP_FIXED will fail and return -1 unless the application has requested
  // SPEC1170 compliant behaviour:
  // https://www.ibm.com/docs/en/aix/7.3?topic=m-mmap-mmap64-subroutine
  // Therefore in case if failure we need to unmap the address before trying to
  // map it again. The downside is another thread could place another mapping at
  // the same address after the munmap but before the mmap, therefore a CHECK is
  // also added to assure the address is mapped successfully. Refer to the
  // comments under https://crrev.com/c/3010195 for more details.
#define MMAP() \
  mmap(address, size, PROT_NONE, MAP_FIXED | MAP_ANONYMOUS | MAP_PRIVATE, -1, 0)
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % CommitPageSize());
  DCHECK_EQ(0, size % CommitPageSize());
  void* ptr;
  // Try without mapping first.
  ptr = MMAP();
  if (ptr != address) {
    DCHECK_EQ(ptr, MAP_FAILED);
    // Returns 0 when successful.
    if (munmap(address, size)) {
      return false;
    }
    // Try again after unmap.
    ptr = MMAP();
    // If this check fails it's most likely due to a racing condition where
    // another thread has mapped the same address right before we do.
    // Since this could cause hard-to-debug issues, potentially with security
    // impact, and we can't recover from this, the best we can do is abort the
    // process.
    CHECK_EQ(ptr, address);
  }
#undef MMAP
  return true;
}
References CHECK_EQ, CommitPageSize(), DCHECK_EQ, MMAP, and size().
Referenced by v8::base::VirtualAddressSpace::DecommitPages(), and v8::base::PageAllocator::DecommitPages().
DestroySharedMemoryHandle()
void v8::base::OS::DestroySharedMemoryHandle (PlatformSharedMemoryHandle handle) [static]
Definition at line 156 of file platform-darwin.cc.
                                                                    {
  DCHECK_NE(kInvalidSharedMemoryHandle, handle);
  mach_port_t port = MachMemoryEntryFromSharedMemoryHandle(handle);
  CHECK_EQ(KERN_SUCCESS, mach_port_deallocate(mach_task_self(), port));
}
References CHECK_EQ, DCHECK_NE, v8::internal::handle(), and v8::kInvalidSharedMemoryHandle.
DirectorySeparator()
char v8::base::OS::DirectorySeparator () [static]
Definition at line 989 of file platform-posix.cc.
{ return '/'; }
Referenced by v8::internal::wasm::DumpModule(), v8::internal::compiler::GetVisualizerLogFileName(), and isDirectorySeparator().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::base::OS::DISALLOW_IMPLICIT_CONSTRUCTORS (OS) [private]
DiscardSystemPages()
bool v8::base::OS::DiscardSystemPages (void * address, size_t size) [static], [private]
Definition at line 181 of file platform-cygwin.cc.
                                                      {
  // On Windows, discarded pages are not returned to the system immediately and
  // not guaranteed to be zeroed when returned to the application.
  using DiscardVirtualMemoryFunction =
      DWORD(WINAPI*)(PVOID virtualAddress, SIZE_T size);
  static std::atomic<DiscardVirtualMemoryFunction> discard_virtual_memory(
      reinterpret_cast<DiscardVirtualMemoryFunction>(-1));
  if (discard_virtual_memory ==
      reinterpret_cast<DiscardVirtualMemoryFunction>(-1))
    discard_virtual_memory =
        reinterpret_cast<DiscardVirtualMemoryFunction>(GetProcAddress(
            GetModuleHandle(L"Kernel32.dll"), "DiscardVirtualMemory"));
  // Use DiscardVirtualMemory when available because it releases faster than
  // MEM_RESET.
  DiscardVirtualMemoryFunction discard_function = discard_virtual_memory.load();
  if (discard_function) {
    DWORD ret = discard_function(address, size);
    if (!ret) return true;
  }
  // DiscardVirtualMemory is buggy in Win10 SP0, so fall back to MEM_RESET on
  // failure.
  void* ptr = VirtualAlloc(address, size, MEM_RESET, PAGE_READWRITE);
  CHECK(ptr);
  return ptr;
}
References CHECK, v8::internal::L, size(), and WINAPI.
Referenced by v8::base::VirtualAddressSpace::DiscardSystemPages(), and v8::base::PageAllocator::DiscardSystemPages().
EnsureAlternativeSignalStackIsAvailableForCurrentThread()
void v8::base::OS::EnsureAlternativeSignalStackIsAvailableForCurrentThread () [static]
Definition at line 277 of file platform-posix.cc.
                                                                 {
  stack_t ss, old_ss;
  memset(&ss, 0, sizeof(stack_t));
  memset(&old_ss, 0, sizeof(stack_t));
  if (sigaltstack(nullptr, &old_ss) == -1) {
    FATAL("sigaltstack failed with error %d: %s", errno, strerror(errno));
  }
  // If an alternative stack is already registered, there's nothing left to do.
  if (!(old_ss.ss_flags & SS_DISABLE)) return;
  // The default alternative stack size of SIGSTKSZ can be too small (e.g.
  // 8192). For example the profiler signal handler requires a larger stack.
  const size_t kStackSize = 1024 * 1024;
  CHECK_GE(kStackSize, SIGSTKSZ);
  // Allocate the alternative stack with guard regions on both sides to
  // ensure that we catch stack overflows (and similar issues) on that stack.
  const size_t kPageSize = AllocatePageSize();
  const size_t kAllocationSize = kStackSize + 2 * kPageSize;
  void* ptr = Allocate(nullptr, kAllocationSize, kPageSize,
                       MemoryPermission::kNoAccess);
  CHECK_NE(ptr, nullptr);
  void* stack_ptr = reinterpret_cast<char*>(ptr) + kPageSize;
  CHECK(SetPermissions(stack_ptr, kStackSize, MemoryPermission::kReadWrite));
  ss.ss_sp = stack_ptr;
  ss.ss_size = kStackSize;
  ss.ss_flags = 0;
  if (sigaltstack(&ss, nullptr) == -1) {
    FATAL("sigaltstack failed with error %d: %s", errno, strerror(errno));
  }
}
References Allocate(), AllocatePageSize(), CHECK, CHECK_GE, CHECK_NE, FATAL, kNoAccess, cppgc::internal::kPageSize, kReadWrite, v8::base::anonymous_namespace{platform-starboard.cc}::kStackSize, and SetPermissions().
ExitProcess()
void v8::base::OS::ExitProcess (int exit_code) [static]
Definition at line 902 of file platform-posix.cc.
                                  {
  // Use _exit instead of exit to avoid races between isolate
  // threads and static destructors.
  fflush(stdout);
  fflush(stderr);
  _exit(exit_code);
}
Referenced by v8::internal::Flag::CheckFlagChange(), v8::SourceGroup::Execute(), v8::Shell::LoadJSON(), v8::Shell::MapCounters(), v8::Shell::QuitOnce(), v8::anonymous_namespace{d8-console.cc}::WriteToFile(), and v8::WriteToFile().
FOpen()
FILE * v8::base::OS::FOpen (const char * path, const char * mode) [static]
Definition at line 970 of file platform-posix.cc.
                                                  {
  FILE* file = fopen(path, mode);
  if (file == nullptr) return nullptr;
  struct stat file_stat;
  if (fstat(fileno(file), &file_stat) != 0) {
    fclose(file);
    return nullptr;
  }
  bool is_regular_file = ((file_stat.st_mode & S_IFREG) != 0);
  if (is_regular_file) return file;
  fclose(file);
  return nullptr;
}
References file(), and mode().
Referenced by v8::internal::LogFile::CreateOutputHandle(), v8::internal::wasm::DumpModule(), v8::internal::wasm::DumpProfileToFile(), anonymous_namespace{mksnapshot.cc}::GetExtraCode(), v8::internal::EmbeddedFileWriter::GetFileDescriptorOrDie(), anonymous_namespace{mksnapshot.cc}::SnapshotFileWriter::GetFileDescriptorOrDie(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::LowLevelLogger::LowLevelLogger(), v8::internal::CodeTracer::OpenFile(), v8::Shell::ReadChars(), v8::internal::anonymous_namespace{utils.cc}::ReadCharsFromFile(), and v8::internal::WriteChars().
Free()
void v8::base::OS::Free (void * address, size_t size) [static], [private]
Definition at line 150 of file platform-cygwin.cc.
                                              {
  DCHECK_EQ(0, static_cast<uintptr_t>(address) % AllocatePageSize());
  DCHECK_EQ(0, size % AllocatePageSize());
  USE(size);
  CHECK_NE(0, VirtualFree(address, 0, MEM_RELEASE));
}
References AllocatePageSize(), CHECK_NE, DCHECK_EQ, size(), and USE.
Referenced by Allocate(), v8::base::VirtualAddressSpace::AllocateGuardRegion(), v8::base::VirtualAddressSpace::FreeGuardRegion(), v8::base::VirtualAddressSpace::FreePages(), v8::base::PageAllocator::FreePages(), and v8::base::PosixMemoryMappedFile::~PosixMemoryMappedFile().
FreeAddressSpaceReservation()
void v8::base::OS::FreeAddressSpaceReservation (AddressSpaceReservation reservation) [static], [private]
Definition at line 356 of file platform-fuchsia.cc.
                                                                        {
  // Destroy the vmar and release the handle.
  zx::vmar vmar(reservation.vmar_);
  CHECK_EQ(ZX_OK, vmar.destroy());
}
References CHECK_EQ.
Referenced by v8::base::AddressSpaceReservation::FreeSubReservation(), and v8::base::VirtualAddressSpace::FreeSubspace().
FreeShared()
void v8::base::OS::FreeShared (void * address, size_t size) [static], [private]
Definition at line 295 of file platform-fuchsia.cc.
                                              {
  CHECK(UnmapVmo(*zx::vmar::root_self(), AllocatePageSize(), address, size));
}
References AllocatePageSize(), CHECK, size(), and v8::base::anonymous_namespace{platform-fuchsia.cc}::UnmapVmo().
Referenced by v8::base::VirtualAddressSpace::FreeSharedPages().
FRIEND_TEST()
v8::base::OS::FRIEND_TEST (OS , RemapPages) [private]
GetCurrentProcessId()
int v8::base::OS::GetCurrentProcessId () [static]
Definition at line 878 of file platform-posix.cc.
                            {
  return static_cast<int>(getpid());
}
Referenced by v8::internal::AddIsolateIdIfNeeded(), v8::internal::CodeTracer::CodeTracer(), v8::internal::Isolate::GetTurboCfgFileName(), v8::platform::tracing::TraceObject::Initialize(), v8::internal::CodeDataSourceIncrementalState::InternIsolate(), v8::base::LoadSymbols(), v8::internal::PrepareLogFileName(), v8::internal::GCTracer::Print(), v8::internal::PrintIsolate(), and v8::internal::PrintPID().
GetCurrentThreadId()
int v8::base::OS::GetCurrentThreadId () [static]
Definition at line 29 of file platform.cc.
                           {
  static thread_local int id = GetCurrentThreadIdInternal();
  return id;
}
References GetCurrentThreadIdInternal().
Referenced by cppgc::internal::HeapBase::CurrentThreadIsHeapThread(), v8::platform::tracing::TraceObject::Initialize(), v8::base::RecursiveMutex::Lock(), v8::internal::anonymous_namespace{perfetto-logger.cc}::NewTracePacket(), v8::internal::CppHeap::StartDetachingIsolate(), v8::base::RecursiveMutex::TryLock(), and v8::base::RecursiveMutex::Unlock().
GetCurrentThreadIdInternal()
int v8::base::OS::GetCurrentThreadIdInternal () [static], [private]
Definition at line 882 of file platform-posix.cc.
                                   {
#if V8_OS_DARWIN || (V8_OS_ANDROID && defined(__APPLE__))
  return static_cast<int>(pthread_mach_thread_np(pthread_self()));
#elif V8_OS_LINUX
  return static_cast<int>(syscall(__NR_gettid));
#elif V8_OS_ANDROID
  return static_cast<int>(gettid());
#elif V8_OS_AIX
  return static_cast<int>(thread_self());
#elif V8_OS_FUCHSIA
  return static_cast<int>(zx_thread_self());
#elif V8_OS_SOLARIS
  return static_cast<int>(pthread_self());
#elif V8_OS_ZOS
  return gettid();
#else
  return static_cast<int>(reinterpret_cast<intptr_t>(pthread_self()));
#endif
}
Referenced by GetCurrentThreadId().
GetFirstFreeMemoryRangeWithin()
std::optional< OS::MemoryRange > v8::base::OS::GetFirstFreeMemoryRangeWithin (OS::Address boundary_start, OS::Address boundary_end, size_t minimum_size, size_t alignment) [static]
Definition at line 132 of file platform-aix.cc.
                      {
  return std::nullopt;
}
GetLastError()
int v8::base::OS::GetLastError () [static]
Definition at line 961 of file platform-posix.cc.
                     {
  return errno;
}
Referenced by v8::base::LoadSymbols(), and v8::internal::Heap::RecordStats().
GetPeakMemoryUsageKb()
int v8::base::OS::GetPeakMemoryUsageKb () [static]
Definition at line 925 of file platform-posix.cc.
                             {
#if defined(V8_OS_FUCHSIA)
  // Fuchsia does not implement getrusage()
  return -1;
#elif defined(V8_OS_ZOS)
  // TODO(v8:342445981): zos - rusage struct doesn't yet include ru_maxrss
  return -1;
#else
  struct rusage usage;
  if (getrusage(RUSAGE_SELF, &usage) < 0) return -1;
#if defined(V8_OS_MACOS) || defined(V8_OS_IOS)
  constexpr int KB = 1024;
  // MacOS and iOS ru_maxrss count bytes
  return static_cast<int>(usage.ru_maxrss / KB);
#else
  // Most other cases (at least Linux, IOS, return kilobytes)
  return static_cast<int>(usage.ru_maxrss);
#endif // defined(V8_OS_MACOS) || defined(V8_OS_IOS)
#endif // defined(V8_OS_FUCHSIA)
}
References KB.
Referenced by v8::Shell::OnExit().
GetRandomMmapAddr()
void * v8::base::OS::GetRandomMmapAddr () [static], [private]
Definition at line 354 of file platform-posix.cc.
                            {
  uintptr_t raw_addr;
  {
    MutexGuard guard(rng_mutex.Pointer());
    GetPlatformRandomNumberGenerator()->NextBytes(&raw_addr, sizeof(raw_addr));
  }
#if V8_HOST_ARCH_ARM64
#if defined(V8_TARGET_OS_MACOS)
  DCHECK_EQ(1 << 14, AllocatePageSize());
#endif
  // Keep the address page-aligned, AArch64 supports 4K, 16K and 64K
  // configurations.
  raw_addr = RoundDown(raw_addr, AllocatePageSize());
#endif
#if defined(V8_USE_ADDRESS_SANITIZER) || defined(MEMORY_SANITIZER) || \
    defined(THREAD_SANITIZER) || defined(LEAK_SANITIZER)
  // If random hint addresses interfere with address ranges hard coded in
  // sanitizers, bad things happen. This address range is copied from TSAN
  // source but works with all tools.
  // See crbug.com/539863.
  raw_addr &= 0x007fffff0000ULL;
  raw_addr += 0x7e8000000000ULL;
#else
#if V8_TARGET_ARCH_X64
  // Currently available CPUs have 48 bits of virtual addressing. Truncate
  // the hint address to 46 bits to give the kernel a fighting chance of
  // fulfilling our placement request.
  raw_addr &= uint64_t{0x3FFFFFFFF000};
#elif V8_TARGET_ARCH_ARM64
#if defined(V8_TARGET_OS_LINUX) || defined(V8_TARGET_OS_ANDROID)
  // On Linux, the default virtual address space is limited to 39 bits when
  // using 4KB pages, see arch/arm64/Kconfig. We truncate to 38 bits.
  raw_addr &= uint64_t{0x3FFFFFF000};
#else
  // On macOS and elsewhere, we use 46 bits, same as on x64.
  raw_addr &= uint64_t{0x3FFFFFFFF000};
#endif
#elif V8_TARGET_ARCH_PPC64
#if V8_OS_AIX
  // AIX: 64 bits of virtual addressing, but we limit address range to minimize
  // Segment Lookaside Buffer (SLB) misses.
  raw_addr &= uint64_t{0x3FFFF000};
  // Use extra address space to isolate the mmap regions.
  raw_addr += uint64_t{0x400000000000};
#else
  // Little-endian Linux: 46 bits of virtual addressing.
  raw_addr &= uint64_t{0x3FFFFFFF0000};
#endif
#elif V8_TARGET_ARCH_S390X
  // Linux on Z uses bits 22-32 for Region Indexing, which translates to 42 bits
  // of virtual addressing. Truncate to 40 bits to allow kernel chance to
  // fulfill request.
  raw_addr &= uint64_t{0xFFFFFFF000};
#elif V8_TARGET_ARCH_MIPS64
  // 42 bits of virtual addressing. Truncate to 40 bits to allow kernel chance
  // to fulfill request.
  raw_addr &= uint64_t{0xFFFFFF0000};
#elif V8_TARGET_ARCH_RISCV64
  // TODO(RISCV): We need more information from the kernel to correctly mask
  // this address for RISC-V. https://github.com/v8-riscv/v8/issues/375
  raw_addr &= uint64_t{0xFFFFFF0000};
#elif V8_TARGET_ARCH_RISCV32
  // TODO(RISCV): We need more information from the kernel to correctly mask
  // this address for RISC-V. https://github.com/v8-riscv/v8/issues/375
  raw_addr &= 0x3FFFF000;
#elif V8_TARGET_ARCH_LOONG64
  // 40 or 47 bits of virtual addressing. Truncate to 38 bits to allow kernel
  // chance to fulfill request.
  raw_addr &= uint64_t{0x3FFFFF0000};
#else
  raw_addr &= 0x3FFFF000;
#ifdef __sun
  // For our Solaris/illumos mmap hint, we pick a random address in the bottom
  // half of the top half of the address space (that is, the third quarter).
  // Because we do not MAP_FIXED, this will be treated only as a hint -- the
  // system will not fail to mmap() because something else happens to already
  // be mapped at our random address. We deliberately set the hint high enough
  // to get well above the system's break (that is, the heap); Solaris and
  // illumos will try the hint and if that fails allocate as if there were
  // no hint at all. The high hint prevents the break from getting hemmed in
  // at low values, ceding half of the address space to the system heap.
  raw_addr += 0x80000000;
#elif V8_OS_AIX
  // The range 0x30000000 - 0xD0000000 is available on AIX;
  // choose the upper range.
  raw_addr += 0x90000000;
#else
  // The range 0x20000000 - 0x60000000 is relatively unpopulated across a
  // variety of ASLR modes (PAE kernel, NX compat mode, etc) and on macos
  // 10.6 and 10.7.
  raw_addr += 0x20000000;
#endif
#endif
#endif
  return reinterpret_cast<void*>(raw_addr);
}
References AllocatePageSize(), DCHECK_EQ, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), v8::base::anonymous_namespace{platform-starboard.cc}::rng_mutex, and RoundDown().
Referenced by v8::base::OS::MemoryMappedFile::create(), v8::base::PageAllocator::GetRandomMmapAddr(), v8::base::OS::MemoryMappedFile::open(), and v8::base::VirtualAddressSpace::RandomPageAddress().
GetSharedLibraryAddresses()
std::vector< OS::SharedLibraryAddress > v8::base::OS::GetSharedLibraryAddresses () [static]
Definition at line 88 of file platform-aix.cc.
                                                                {
  std::vector<SharedLibraryAddress> result;
  static const int MAP_LENGTH = 1024;
  int fd = open("/proc/self/maps", O_RDONLY);
  if (fd < 0) return result;
  while (true) {
    char addr_buffer[11];
    addr_buffer[0] = '0';
    addr_buffer[1] = 'x';
    addr_buffer[10] = 0;
    ssize_t rc = read(fd, addr_buffer + 2, 8);
    if (rc < 8) break;
    unsigned start = StringToLong(addr_buffer);
    rc = read(fd, addr_buffer + 2, 1);
    if (rc < 1) break;
    if (addr_buffer[2] != '-') break;
    rc = read(fd, addr_buffer + 2, 8);
    if (rc < 8) break;
    unsigned end = StringToLong(addr_buffer);
    char buffer[MAP_LENGTH];
    int bytes_read = -1;
    do {
      bytes_read++;
      if (bytes_read >= MAP_LENGTH - 1) break;
      rc = read(fd, buffer + bytes_read, 1);
      if (rc < 1) break;
    } while (buffer[bytes_read] != '\n');
    buffer[bytes_read] = 0;
    // Ignore mappings that are not executable.
    if (buffer[3] != 'x') continue;
    char* start_of_path = index(buffer, '/');
    // There may be no filename in this line. Skip to next.
    if (start_of_path == nullptr) continue;
    buffer[bytes_read] = 0;
    result.push_back(SharedLibraryAddress(start_of_path, start, end));
  }
  close(fd);
  return result;
}
References v8::internal::compiler::end(), v8::internal::index, v8::base::internal::result, and v8::base::StringToLong().
Referenced by v8::internal::Profiler::Engage().
GetUserTime()
int v8::base::OS::GetUserTime (uint32_t * secs, uint32_t * usecs) [static]
Definition at line 389 of file platform-fuchsia.cc.
                                                   {
  const auto kNanosPerMicrosecond = 1000ULL;
  const auto kMicrosPerSecond = 1000000ULL;
  zx_info_thread_stats_t info = {};
  if (zx::thread::self()->get_info(ZX_INFO_THREAD_STATS, &info, sizeof(info),
                                   nullptr, nullptr) != ZX_OK) {
    return -1;
  }
  // First convert to microseconds, rounding up.
  const uint64_t micros_since_thread_started =
      (info.total_runtime + kNanosPerMicrosecond - 1ULL) / kNanosPerMicrosecond;
  *secs = static_cast<uint32_t>(micros_since_thread_started / kMicrosPerSecond);
  *usecs =
      static_cast<uint32_t>(micros_since_thread_started % kMicrosPerSecond);
  return 0;
}
HasLazyCommits()
bool v8::base::OS::HasLazyCommits () [static]
Definition at line 211 of file platform-cygwin.cc.
                        {
  // TODO(alph): implement for the platform.
  return false;
}
Referenced by v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::SemiSpace::CommittedPhysicalMemory(), v8::internal::SemiSpaceNewSpace::CommittedPhysicalMemory(), v8::internal::PagedSpaceBase::CommittedPhysicalMemory(), v8::internal::ReadOnlySpace::CommittedPhysicalMemory(), v8::internal::SemiSpace::DecrementCommittedPhysicalMemory(), v8::internal::PagedSpaceBase::DecrementCommittedPhysicalMemory(), v8::internal::SemiSpace::IncrementCommittedPhysicalMemory(), and v8::internal::PagedSpaceBase::IncrementCommittedPhysicalMemory().
Initialize()
void v8::base::OS::Initialize (AbortMode abort_mode, const char *const gc_fake_mmap) [static]
Definition at line 254 of file platform-fuchsia.cc.
                                                                        {
  PosixInitializeCommon(abort_mode, gc_fake_mmap);
  // Determine base address of root VMAR.
  zx_info_vmar_t info;
  zx_status_t status = zx::vmar::root_self()->get_info(
      ZX_INFO_VMAR, &info, sizeof(info), nullptr, nullptr);
  CHECK_EQ(ZX_OK, status);
  g_root_vmar_base = reinterpret_cast<void*>(info.base);
  SetVmexResource();
}
References CHECK_EQ, v8::base::anonymous_namespace{platform-fuchsia.cc}::g_root_vmar_base, v8::base::PosixInitializeCommon(), v8::base::anonymous_namespace{platform-fuchsia.cc}::SetVmexResource(), and v8::internal::status.
Referenced by v8::internal::V8::Initialize().
isDirectorySeparator()
bool v8::base::OS::isDirectorySeparator (const char ch) [static]
Definition at line 991 of file platform-posix.cc.
                                           {
  return ch == DirectorySeparator();
}
References DirectorySeparator().
Referenced by v8::internal::wasm::DumpModule(), v8::internal::PrepareLogFileName(), and v8::base::RelativePath().
IsHardwareEnforcedShadowStacksEnabled()
bool v8::base::OS::IsHardwareEnforcedShadowStacksEnabled () [static]
Definition at line 275 of file platform-posix.cc.
{ return false; }
IsRemapPageSupported()
static constexpr V8_WARN_UNUSED_RESULT bool v8::base::OS::IsRemapPageSupported () [inline], [static], [constexpr]
Definition at line 338 of file platform.h.
                                                                     {
#if (defined(V8_OS_MACOS) || defined(V8_OS_LINUX)) && \
    !(defined(V8_TARGET_ARCH_PPC64) || defined(V8_TARGET_ARCH_S390X))
    return true;
#else
    return false;
#endif
  }
Referenced by v8::internal::CodeRange::RemapEmbeddedBuiltins().
OpenTemporaryFile()
FILE * v8::base::OS::OpenTemporaryFile () [static]
Definition at line 996 of file platform-posix.cc.
                            {
  return tmpfile();
}
Referenced by v8::internal::LogFile::CreateOutputHandle().
PRINTF_FORMAT() [1/8]
static static v8::base::OS::PRINTF_FORMAT (1 , 0) const [static]
PRINTF_FORMAT() [2/8]
static static v8::base::OS::PRINTF_FORMAT (1 , 0) const [static]
PRINTF_FORMAT() [3/8]
static v8::base::OS::PRINTF_FORMAT (1 , 2) const [static]
PRINTF_FORMAT() [4/8]
static v8::base::OS::PRINTF_FORMAT (1 , 2) const [static]
PRINTF_FORMAT() [5/8]
static const char static v8::base::OS::PRINTF_FORMAT (2 , 0) [static]
PRINTF_FORMAT() [6/8]
static v8::base::OS::PRINTF_FORMAT (2 , 3) [static]
PRINTF_FORMAT() [7/8]
static int const char static v8::base::OS::PRINTF_FORMAT (3 , 0) [static]
PRINTF_FORMAT() [8/8]
static v8::base::OS::PRINTF_FORMAT (3 , 4) [static]
RecommitPages()
bool v8::base::OS::RecommitPages (void * address, size_t size, MemoryPermission access) [static], [private]
Definition at line 176 of file platform-cygwin.cc.
                                                                          {
  return SetPermissions(address, size, access);
}
References SetPermissions(), and size().
Referenced by v8::base::VirtualAddressSpace::RecommitPages(), and v8::base::PageAllocator::RecommitPages().
Release()
void v8::base::OS::Release (void * address, size_t size) [static], [private]
Definition at line 158 of file platform-cygwin.cc.
                                           {
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % CommitPageSize());
  DCHECK_EQ(0, size % CommitPageSize());
  CHECK_NE(0, VirtualFree(address, size, MEM_DECOMMIT));
}
References CHECK_NE, CommitPageSize(), DCHECK_EQ, and size().
Referenced by v8::base::PageAllocator::ReleasePages().
RemapPages()
bool v8::base::OS::RemapPages (const void * address, size_t size, void * new_address, MemoryPermission access) [static]
Definition at line 184 of file platform-darwin.cc.
                                             {
  DCHECK(IsAligned(reinterpret_cast<uintptr_t>(address), AllocatePageSize()));
  DCHECK(
      IsAligned(reinterpret_cast<uintptr_t>(new_address), AllocatePageSize()));
  DCHECK(IsAligned(size, AllocatePageSize()));
  vm_prot_t cur_protection = GetVMProtFromMemoryPermission(access);
  vm_prot_t max_protection;
  // Asks the kernel to remap *on top* of an existing mapping, rather than
  // copying the data.
  int flags = VM_FLAGS_FIXED | VM_FLAGS_OVERWRITE;
  mach_vm_address_t target = reinterpret_cast<mach_vm_address_t>(new_address);
  kern_return_t ret =
      mach_vm_remap(mach_task_self(), &target, size, 0, flags, mach_task_self(),
                    reinterpret_cast<mach_vm_address_t>(address), FALSE,
                    &cur_protection, &max_protection, VM_INHERIT_NONE);
  if (ret != KERN_SUCCESS) return false;
  // Did we get the address we wanted?
  CHECK_EQ(new_address, reinterpret_cast<void*>(target));
  return true;
}
References AllocatePageSize(), CHECK_EQ, DCHECK, flags(), v8::base::anonymous_namespace{platform-darwin.cc}::GetVMProtFromMemoryPermission(), IsAligned(), mach_vm_remap(), and size().
Referenced by v8::internal::CodeRange::RemapEmbeddedBuiltins().
RemapShared()
void * v8::base::OS::RemapShared (void * old_address, void * new_address, size_t size) [static], [private]
Definition at line 79 of file platform-linux.cc.
                                                                       {
  void* result =
      mremap(old_address, 0, size, MREMAP_FIXED | MREMAP_MAYMOVE, new_address);
  if (result == MAP_FAILED) {
    return nullptr;
  }
  DCHECK(result == new_address);
  return result;
}
References DCHECK, v8::base::internal::result, and size().
Referenced by v8::base::PageAllocator::RemapShared().
Remove()
bool v8::base::OS::Remove (const char * path) [static]
Definition at line 985 of file platform-posix.cc.
                                {
  return (remove(path) == 0);
}
SealPages()
bool v8::base::OS::SealPages (void * address, size_t size) [static], [private]
Definition at line 208 of file platform-cygwin.cc.
{ return false; }
Referenced by v8::base::PageAllocator::SealPages().
SetDataReadOnly()
void v8::base::OS::SetDataReadOnly (void * address, size_t size) [static]
Definition at line 308 of file platform-fuchsia.cc.
                                                   {
  CHECK(OS::SetPermissions(address, size, MemoryPermission::kRead));
}
References CHECK, kRead, SetPermissions(), and size().
Referenced by v8::internal::FlagList::FreezeFlags().
SetPermissions()
bool v8::base::OS::SetPermissions (void * address, size_t size, MemoryPermission access) [static], [private]
Definition at line 165 of file platform-cygwin.cc.
                                                                           {
  DCHECK_EQ(0, reinterpret_cast<uintptr_t>(address) % CommitPageSize());
  DCHECK_EQ(0, size % CommitPageSize());
  if (access == MemoryPermission::kNoAccess) {
    return VirtualFree(address, size, MEM_DECOMMIT) != 0;
  }
  DWORD protect = GetProtectionFromMemoryPermission(access);
  return VirtualAlloc(address, size, MEM_COMMIT, protect) != nullptr;
}
References CommitPageSize(), DCHECK_EQ, v8::base::GetProtectionFromMemoryPermission(), kNoAccess, and size().
Referenced by v8::base::PageAllocator::AllocateSharedPages(), EnsureAlternativeSignalStackIsAvailableForCurrentThread(), RecommitPages(), SetDataReadOnly(), v8::base::VirtualAddressSpace::SetPagePermissions(), and v8::base::PageAllocator::SetPermissions().
SetRandomMmapSeed()
void v8::base::OS::SetRandomMmapSeed (int64_t seed) [static], [private]
Definition at line 346 of file platform-posix.cc.
                                       {
  if (seed) {
    MutexGuard guard(rng_mutex.Pointer());
    GetPlatformRandomNumberGenerator()->SetSeed(seed);
  }
}
References v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), and v8::base::anonymous_namespace{platform-starboard.cc}::rng_mutex.
Referenced by v8::base::PageAllocator::SetRandomMmapSeed(), and v8::base::VirtualAddressSpace::SetRandomSeed().
SignalCodeMovingGC()
void v8::base::OS::SignalCodeMovingGC () [static]
Definition at line 128 of file platform-aix.cc.
{}
Referenced by v8::internal::V8FileLogger::CodeMovingGCEvent().
Sleep()
void v8::base::OS::Sleep (TimeDelta interval) [static]
Definition at line 754 of file platform-posix.cc.
                                 {
  usleep(static_cast<useconds_t>(interval.InMicroseconds()));
}
References v8::base::TimeDelta::InMicroseconds().
Referenced by v8::platform::TaskQueue::BlockUntilQueueEmptyForTesting(), v8::DelayedTasksPlatform::DelayedTask::Run(), v8::internal::SamplingThread::Run(), v8::DelayedTasksPlatform::DelayedIdleTask::Run(), v8::DelayedTasksPlatform::DelayedJob::Run(), and v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob().
StrNCpy()
void v8::base::OS::StrNCpy (char * dest, int length, const char * src, size_t n) [static]
Definition at line 1085 of file platform-posix.cc.
                                                                  {
  strncpy(dest, src, n);
}
Referenced by v8::Counter::Bind(), and v8::base::StrNCpy().
TimeCurrentMillis()
double v8::base::OS::TimeCurrentMillis () [static]
Definition at line 947 of file platform-posix.cc.
                             {
  return Time::Now().ToJsTime();
}
References v8::base::Time::Now(), and v8::base::Time::ToJsTime().
Referenced by v8::platform::DefaultPlatform::CurrentClockTimeMillis(), v8::base::WindowsTimezoneCache::LocalTimeOffset(), and v8::Platform::SystemClockTimeMillis().
Friends And Related Function Documentation
AddressSpaceReservation
friend class AddressSpaceReservation [friend]
Definition at line 369 of file platform.h.
Referenced by CreateAddressSpaceReservation().
MemoryMappedFile
friend class MemoryMappedFile [friend]
Definition at line 370 of file platform.h.
PosixMemoryMappedFile
friend class PosixMemoryMappedFile [friend]
Definition at line 371 of file platform.h.
Referenced by v8::base::OS::MemoryMappedFile::create(), and v8::base::OS::MemoryMappedFile::open().
v8::base::PageAllocator
friend class v8::base::PageAllocator [friend]
Definition at line 372 of file platform.h.
v8::base::VirtualAddressSpace
friend class v8::base::VirtualAddressSpace [friend]
Definition at line 373 of file platform.h.
v8::base::VirtualAddressSubspace
friend class v8::base::VirtualAddressSubspace [friend]
Definition at line 374 of file platform.h.
Member Data Documentation
args [1/3]
static static va_list v8::base::OS::args
Definition at line 205 of file platform.h.
args [2/3]
const char static const char va_list v8::base::OS::args
Definition at line 210 of file platform.h.
args [3/3]
int const char static int const char va_list v8::base::OS::args
Definition at line 275 of file platform.h.
format [1/4]
const char* v8::base::OS::format
Definition at line 208 of file platform.h.
format [2/4]
const char static const char* v8::base::OS::format
Definition at line 209 of file platform.h.
format [3/4]
int const char* v8::base::OS::format
Definition at line 273 of file platform.h.
format [4/4]
int const char static int const char* v8::base::OS::format
Definition at line 275 of file platform.h.
kStackWalkError
const int v8::base::OS::kStackWalkError = -1 [static]
Definition at line 248 of file platform.h.
kStackWalkMaxNameLen
const int v8::base::OS::kStackWalkMaxNameLen = 256 [static]
Definition at line 249 of file platform.h.
Referenced by v8::base::LoadSymbols().
kStackWalkMaxTextLen
const int v8::base::OS::kStackWalkMaxTextLen = 256 [static]
Definition at line 250 of file platform.h.
length [1/2]
int v8::base::OS::length
Definition at line 272 of file platform.h.
length [2/2]
int const char static int v8::base::OS::length
Definition at line 274 of file platform.h.
LogFileOpenMode
const char *const v8::base::OS::LogFileOpenMode = `w+` [static]
Definition at line 199 of file platform.h.
Referenced by v8::internal::LogFile::CreateOutputHandle(), and v8::internal::LowLevelLogger::LowLevelLogger().
msPerSecond
const int v8::base::OS::msPerSecond = 1000 [static], [private]
Definition at line 427 of file platform.h.
Referenced by v8::base::PosixTimezoneCache::DaylightSavingsOffset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform.h
/mnt/V8SourceCode/src/base/platform/platform-aix.cc
/mnt/V8SourceCode/src/base/platform/platform-cygwin.cc
/mnt/V8SourceCode/src/base/platform/platform-darwin.cc
/mnt/V8SourceCode/src/base/platform/platform-freebsd.cc
/mnt/V8SourceCode/src/base/platform/platform-fuchsia.cc
/mnt/V8SourceCode/src/base/platform/platform-linux.cc
/mnt/V8SourceCode/src/base/platform/platform-openbsd.cc
/mnt/V8SourceCode/src/base/platform/platform-posix.cc
/mnt/V8SourceCode/src/base/platform/platform-qnx.cc
/mnt/V8SourceCode/src/base/platform/platform-solaris.cc
/mnt/V8SourceCode/src/base/platform/platform-starboard.cc
/mnt/V8SourceCode/src/base/platform/platform-win32.cc
/mnt/V8SourceCode/src/base/platform/platform-zos.cc
/mnt/V8SourceCode/src/base/platform/platform.cc