v8::internal::torque::GlobalContext Class Reference
#include <global-context.h>
Classes
struct PerFileStreams
Public Member Functions
GlobalContext (GlobalContext &&) V8_NOEXCEPT=default
GlobalContext & operator= (GlobalContext &&) V8_NOEXCEPT=default
GlobalContext (Ast ast)
template<class T >
T * RegisterDeclarable (std::unique_ptr< T > d)
Static Public Member Functions
static Namespace * GetDefaultNamespace ()
static const std::vector< std::unique_ptr< Declarable > > & AllDeclarables ()
static void AddCppInclude (std::string include_path)
static const std::set< std::string > & CppIncludes ()
static void SetCollectLanguageServerData ()
static bool collect_language_server_data ()
static void SetCollectKytheData ()
static bool collect_kythe_data ()
static void SetForceAssertStatements ()
static bool force_assert_statements ()
static void SetAnnotateIR ()
static bool annotate_ir ()
static Ast * ast ()
static std::string MakeUniqueName (const std::string &base)
static PerFileStreams & GeneratedPerFile (SourceId file)
static void SetInstanceTypesInitialized ()
static bool IsInstanceTypesInitialized ()
static void EnsureInCCOutputList (TorqueMacro *macro, SourceId source)
static const std::vector< std::pair< TorqueMacro *, SourceId > > & AllMacrosForCCOutput ()
static void EnsureInCCDebugOutputList (TorqueMacro *macro, SourceId source)
static const std::vector< std::pair< TorqueMacro *, SourceId > > & AllMacrosForCCDebugOutput ()
Private Attributes
bool collect_language_server_data_
bool collect_kythe_data_
bool force_assert_statements_
bool annotate_ir_
Namespace * default_namespace_
Ast ast_
std::vector< std::unique_ptr< Declarable > > declarables_
std::set< std::string > cpp_includes_
std::map< SourceId, PerFileStreams > generated_per_file_
std::map< std::string, size_t > fresh_ids_
std::vector< std::pair< TorqueMacro *, SourceId > > macros_for_cc_output_
std::set< std::pair< TorqueMacro *, SourceId > > macros_for_cc_output_set_
std::vector< std::pair< TorqueMacro *, SourceId > > macros_for_cc_debug_output_
std::set< std::pair< TorqueMacro *, SourceId > > macros_for_cc_debug_output_set_
bool instance_types_initialized_ = false
Friends
class LanguageServerData
Additional Inherited Members
Detailed Description
Definition at line 21 of file global-context.h.
Constructor & Destructor Documentation
GlobalContext() [1/2]
v8::internal::torque::GlobalContext::GlobalContext (GlobalContext &&) [default]
GlobalContext() [2/2]
v8::internal::torque::GlobalContext::GlobalContext (Ast ast) [explicit]
Definition at line 11 of file global-context.cc.
    : collect_language_server_data_(false),
      collect_kythe_data_(false),
      force_assert_statements_(false),
      annotate_ir_(false),
      ast_(std::move(ast)) {
  CurrentScope::Scope current_scope(nullptr);
  CurrentSourcePosition::Scope current_source_position(
      SourcePosition{CurrentSourceFile::Get(), LineAndColumn::Invalid(),
                     LineAndColumn::Invalid()});
  default_namespace_ =
      RegisterDeclarable(std::make_unique<Namespace>(kBaseNamespaceName));
}
References default_namespace_, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::LineAndColumn::Invalid(), v8::internal::torque::kBaseNamespaceName, and RegisterDeclarable().
Member Function Documentation
AddCppInclude()
static void v8::internal::torque::GlobalContext::AddCppInclude (std::string include_path) [inline], [static]
Definition at line 39 of file global-context.h.
                                                    {
    Get().cpp_includes_.insert(std::move(include_path));
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::DeclarationVisitor::Visit().
AllDeclarables()
static const std::vector<std::unique_ptr<Declarable> >& v8::internal::torque::GlobalContext::AllDeclarables () [inline], [static]
Definition at line 35 of file global-context.h.
                                                                      {
    return Get().declarables_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::BuildInstanceTypeTree(), v8::internal::torque::Declarations::FindSomeInternalBuiltinWithType(), and v8::internal::torque::PredeclarationVisitor::ResolvePredeclarations().
AllMacrosForCCDebugOutput()
static const std::vector<std::pair<TorqueMacro*, SourceId> >& v8::internal::torque::GlobalContext::AllMacrosForCCDebugOutput () [inline], [static]
Definition at line 129 of file global-context.h.
                              {
    return Get().macros_for_cc_debug_output_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
AllMacrosForCCOutput()
static const std::vector<std::pair<TorqueMacro*, SourceId> >& v8::internal::torque::GlobalContext::AllMacrosForCCOutput () [inline], [static]
Definition at line 118 of file global-context.h.
                         {
    return Get().macros_for_cc_output_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
annotate_ir()
static bool v8::internal::torque::GlobalContext::annotate_ir () [inline], [static]
Definition at line 61 of file global-context.h.
{ return Get().annotate_ir_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
ast()
static Ast* v8::internal::torque::GlobalContext::ast () [inline], [static]
Definition at line 62 of file global-context.h.
{ return &Get().ast_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
collect_kythe_data()
static bool v8::internal::torque::GlobalContext::collect_kythe_data () [inline], [static]
Definition at line 53 of file global-context.h.
{ return Get().collect_kythe_data_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::PredeclarationVisitor::Predeclare(), v8::internal::torque::DeclarationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::Visit().
collect_language_server_data()
static bool v8::internal::torque::GlobalContext::collect_language_server_data () [inline], [static]
Definition at line 49 of file global-context.h.
                                             {
    return Get().collect_language_server_data_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::Declarations::LookupType(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::DeclarationVisitor::Visit().
CppIncludes()
static const std::set<std::string>& v8::internal::torque::GlobalContext::CppIncludes () [inline], [static]
Definition at line 42 of file global-context.h.
                                                {
    return Get().cpp_includes_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), and v8::internal::torque::ImplementationVisitor::GenerateClassDebugReaders().
EnsureInCCDebugOutputList()
static void v8::internal::torque::GlobalContext::EnsureInCCDebugOutputList (TorqueMacro * macro, SourceId source) [inline], [static]
Definition at line 121 of file global-context.h.
                                                                             {
    GlobalContext& c = Get();
    auto item = std::make_pair(macro, source);
    if (c.macros_for_cc_debug_output_set_.insert(item).second) {
      c.macros_for_cc_debug_output_.push_back(item);
    }
  }
References v8::base::ContextualVariable< Derived, VarType >::Get(), macros_for_cc_debug_output_, and macros_for_cc_debug_output_set_.
Referenced by EnsureInCCOutputList(), and v8::internal::torque::ClassType::GenerateSliceAccessor().
EnsureInCCOutputList()
static void v8::internal::torque::GlobalContext::EnsureInCCOutputList (TorqueMacro * macro, SourceId source) [inline], [static]
Definition at line 109 of file global-context.h.
                                                                        {
    GlobalContext& c = Get();
    auto item = std::make_pair(macro, source);
    if (c.macros_for_cc_output_set_.insert(item).second) {
      c.macros_for_cc_output_.push_back(item);
    }
    EnsureInCCDebugOutputList(macro, source);
  }
References EnsureInCCDebugOutputList(), v8::base::ContextualVariable< Derived, VarType >::Get(), macros_for_cc_output_, and macros_for_cc_output_set_.
Referenced by v8::internal::torque::ClassType::GenerateSliceAccessor().
force_assert_statements()
static bool v8::internal::torque::GlobalContext::force_assert_statements () [inline], [static]
Definition at line 57 of file global-context.h.
                                        {
    return Get().force_assert_statements_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
GeneratedPerFile()
static PerFileStreams& v8::internal::torque::GlobalContext::GeneratedPerFile (SourceId file) [inline], [static]
Definition at line 96 of file global-context.h.
                                                         {
    PerFileStreams& result = Get().generated_per_file_[file];
    result.file = file;
    return result;
  }
References file(), v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::torque::ImplementationVisitor::EndGeneratedFiles(), and v8::internal::torque::ImplementationVisitor::GenerateImplementation().
GetDefaultNamespace()
static Namespace* v8::internal::torque::GlobalContext::GetDefaultNamespace () [inline], [static]
Definition at line 27 of file global-context.h.
{ return Get().default_namespace_; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst(), v8::internal::torque::Declarations::DeclareOperator(), v8::internal::torque::Namespace::IsDefaultNamespace(), v8::internal::torque::Scope::Lookup(), v8::internal::torque::Declarations::LookupGlobalScope(), v8::internal::torque::PredeclarationVisitor::Predeclare(), and v8::internal::torque::DeclarationVisitor::Visit().
IsInstanceTypesInitialized()
static bool v8::internal::torque::GlobalContext::IsInstanceTypesInitialized () [inline], [static]
Definition at line 106 of file global-context.h.
                                           {
    return Get().instance_types_initialized_;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::ClassType::InstanceTypeRange(), and v8::internal::torque::ClassType::OwnInstanceType().
MakeUniqueName()
static std::string v8::internal::torque::GlobalContext::MakeUniqueName (const std::string & base) [inline], [static]
Definition at line 63 of file global-context.h.
                                                         {
    return base + "_" + std::to_string(Get().fresh_ids_[base]++);
  }
References fresh_ids_, and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::Declarations::CreateMethod(), v8::internal::torque::Declarations::CreateTorqueMacro(), v8::internal::torque::Declarations::DeclareNamespaceConstant(), v8::internal::torque::DeclarationVisitor::Specialize(), and v8::internal::torque::StructType::StructType().
operator=()
GlobalContext& v8::internal::torque::GlobalContext::operator= (GlobalContext &&) [default]
RegisterDeclarable()
template<class T >
T* v8::internal::torque::GlobalContext::RegisterDeclarable (std::unique_ptr< T > d) [inline]
Definition at line 29 of file global-context.h.
                                            {
    T* ptr = d.get();
    declarables_.push_back(std::move(d));
    return ptr;
  }
References declarables_.
Referenced by GlobalContext().
SetAnnotateIR()
static void v8::internal::torque::GlobalContext::SetAnnotateIR () [inline], [static]
Definition at line 60 of file global-context.h.
{ Get().annotate_ir_ = true; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SetCollectKytheData()
static void v8::internal::torque::GlobalContext::SetCollectKytheData () [inline], [static]
Definition at line 52 of file global-context.h.
{ Get().collect_kythe_data_ = true; }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SetCollectLanguageServerData()
static void v8::internal::torque::GlobalContext::SetCollectLanguageServerData () [inline], [static]
Definition at line 46 of file global-context.h.
                                             {
    Get().collect_language_server_data_ = true;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SetForceAssertStatements()
static void v8::internal::torque::GlobalContext::SetForceAssertStatements () [inline], [static]
Definition at line 54 of file global-context.h.
                                         {
    Get().force_assert_statements_ = true;
  }
References v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SetInstanceTypesInitialized()
static void v8::internal::torque::GlobalContext::SetInstanceTypesInitialized () [inline], [static]
Definition at line 102 of file global-context.h.
                                            {
    DCHECK(!Get().instance_types_initialized_);
    Get().instance_types_initialized_ = true;
  }
References v8::internal::DCHECK(), v8::base::ContextualVariable< Derived, VarType >::Get(), and instance_types_initialized_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes().
Friends And Related Function Documentation
LanguageServerData
friend class LanguageServerData [friend]
Definition at line 150 of file global-context.h.
Member Data Documentation
annotate_ir_
bool v8::internal::torque::GlobalContext::annotate_ir_ [private]
Definition at line 137 of file global-context.h.
ast_
Ast v8::internal::torque::GlobalContext::ast_ [private]
Definition at line 139 of file global-context.h.
collect_kythe_data_
bool v8::internal::torque::GlobalContext::collect_kythe_data_ [private]
Definition at line 135 of file global-context.h.
collect_language_server_data_
bool v8::internal::torque::GlobalContext::collect_language_server_data_ [private]
Definition at line 134 of file global-context.h.
cpp_includes_
std::set<std::string> v8::internal::torque::GlobalContext::cpp_includes_ [private]
Definition at line 141 of file global-context.h.
declarables_
std::vector<std::unique_ptr<Declarable> > v8::internal::torque::GlobalContext::declarables_ [private]
Definition at line 140 of file global-context.h.
Referenced by RegisterDeclarable().
default_namespace_
Namespace* v8::internal::torque::GlobalContext::default_namespace_ [private]
Definition at line 138 of file global-context.h.
Referenced by GlobalContext().
force_assert_statements_
bool v8::internal::torque::GlobalContext::force_assert_statements_ [private]
Definition at line 136 of file global-context.h.
fresh_ids_
std::map<std::string, size_t> v8::internal::torque::GlobalContext::fresh_ids_ [private]
Definition at line 143 of file global-context.h.
Referenced by MakeUniqueName().
generated_per_file_
std::map<SourceId, PerFileStreams> v8::internal::torque::GlobalContext::generated_per_file_ [private]
Definition at line 142 of file global-context.h.
instance_types_initialized_
bool v8::internal::torque::GlobalContext::instance_types_initialized_ = false [private]
Definition at line 148 of file global-context.h.
Referenced by SetInstanceTypesInitialized().
macros_for_cc_debug_output_
std::vector<std::pair<TorqueMacro*, SourceId> > v8::internal::torque::GlobalContext::macros_for_cc_debug_output_ [private]
Definition at line 146 of file global-context.h.
Referenced by EnsureInCCDebugOutputList().
macros_for_cc_debug_output_set_
std::set<std::pair<TorqueMacro*, SourceId> > v8::internal::torque::GlobalContext::macros_for_cc_debug_output_set_ [private]
Definition at line 147 of file global-context.h.
Referenced by EnsureInCCDebugOutputList().
macros_for_cc_output_
std::vector<std::pair<TorqueMacro*, SourceId> > v8::internal::torque::GlobalContext::macros_for_cc_output_ [private]
Definition at line 144 of file global-context.h.
Referenced by EnsureInCCOutputList().
macros_for_cc_output_set_
std::set<std::pair<TorqueMacro*, SourceId> > v8::internal::torque::GlobalContext::macros_for_cc_output_set_ [private]
Definition at line 145 of file global-context.h.
Referenced by EnsureInCCOutputList().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/global-context.h
/mnt/V8SourceCode/src/torque/global-context.cc