v8::InspectorFrontend Class Reference
Public Member Functions
InspectorFrontend (Local< Context > context)
~InspectorFrontend () override=default
Private Member Functions
void sendResponse (int callId, std::unique_ptr< v8_inspector::StringBuffer > message) override
void sendNotification (std::unique_ptr< v8_inspector::StringBuffer > message) override
void flushProtocolNotifications () override
void Send (const v8_inspector::StringView &string)
Private Attributes
Isolate * isolate_
Global< Context > context_
Detailed Description
Definition at line 4988 of file d8.cc.
Constructor & Destructor Documentation
InspectorFrontend()
v8::InspectorFrontend::InspectorFrontend (Local< Context > context) [inline], [explicit]
Definition at line 4990 of file d8.cc.
                                                     {
    isolate_ = Isolate::GetCurrent();
    context_.Reset(isolate_, context);
  }
References v8::Isolate::GetCurrent(), and v8::PerIsolateData::isolate_.
 InspectorFrontend()
v8::InspectorFrontend::~InspectorFrontend () [override], [default]
Member Function Documentation
flushProtocolNotifications()
void v8::InspectorFrontend::flushProtocolNotifications () [inline], [override], [private], [virtual]
Implements v8_inspector::V8Inspector::Channel.
Definition at line 5006 of file d8.cc.
{}
Send()
void v8::InspectorFrontend::Send (const v8_inspector::StringView & string) [inline], [private]
Definition at line 5008 of file d8.cc.
                                                  {
    v8::Isolate::AllowJavascriptExecutionScope allow_script(isolate_);
    v8::HandleScope handle_scope(isolate_);
    int length = static_cast<int>(string.length());
    DCHECK_LT(length, v8::String::kMaxLength);
    Local<String> message =
        (string.is8Bit()
             ? v8::String::NewFromOneByte(
                   isolate_,
                   reinterpret_cast<const uint8_t*>(string.characters8()),
                   v8::NewStringType::kNormal, length)
             : v8::String::NewFromTwoByte(
                   isolate_,
                   reinterpret_cast<const uint16_t*>(string.characters16()),
                   v8::NewStringType::kNormal, length))
            .ToLocalChecked();
    Local<String> callback_name = v8::String::NewFromUtf8Literal(
        isolate_, "receive", NewStringType::kInternalized);
    Local<Context> context = context_.Get(isolate_);
    Local<Value> callback =
        context->Global()->Get(context, callback_name).ToLocalChecked();
    if (callback->IsFunction()) {
      v8::TryCatch try_catch(isolate_);
      Local<Value> args[] = {message};
      USE(callback.As<Function>()->Call(context, Undefined(isolate_), 1, args));
#ifdef DEBUG
      if (try_catch.HasCaught()) {
        Local<Object> exception = try_catch.Exception().As<Object>();
        Local<String> key = v8::String::NewFromUtf8Literal(
            isolate_, "message", NewStringType::kInternalized);
        Local<String> expected = v8::String::NewFromUtf8Literal(
            isolate_, "Maximum call stack size exceeded");
        Local<Value> value = exception->Get(context, key).ToLocalChecked();
        DCHECK(value->StrictEquals(expected));
      }
#endif
    }
  }
References v8::base::args, v8::Local< T >::As(), v8::Function::Call(), DCHECK, DCHECK_LT, v8::TryCatch::Exception(), v8::Object::Get(), v8::Context::Global(), v8::TryCatch::HasCaught(), v8::PerIsolateData::isolate_, v8::internal::key, v8::kInternalized, v8::String::kMaxLength, v8::kNormal, v8::internal::length, v8::String::NewFromOneByte(), v8::String::NewFromTwoByte(), v8::String::NewFromUtf8Literal(), v8::MaybeLocal< T >::ToLocalChecked(), v8::Undefined(), USE, and v8::internal::value.
sendNotification()
void v8::InspectorFrontend::sendNotification (std::unique_ptr< v8_inspector::StringBuffer > message) [inline], [override], [private], [virtual]
Implements v8_inspector::V8Inspector::Channel.
Definition at line 5002 of file d8.cc.
                                                                {
    Send(message->string());
  }
sendResponse()
void v8::InspectorFrontend::sendResponse (int callId, std::unique_ptr< v8_inspector::StringBuffer > message) [inline], [override], [private], [virtual]
Implements v8_inspector::V8Inspector::Channel.
Definition at line 4997 of file d8.cc.
                                                                {
    Send(message->string());
  }
Member Data Documentation
context_
Global<Context> v8::InspectorFrontend::context_ [private]
Definition at line 5048 of file d8.cc.
isolate_
Isolate* v8::InspectorFrontend::isolate_ [private]
Definition at line 5047 of file d8.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc