v8::internal::PromiseBuiltinsAssembler Class Reference
#include <builtins-promise-gen.h>
Public Member Functions
PromiseBuiltinsAssembler (compiler::CodeAssemblerState *state)
void ZeroOutEmbedderOffsets (TNode< JSPromise > promise)
TNode< HeapObject > AllocateJSPromise (TNode< Context > context)
Additional Inherited Members
Detailed Description
Definition at line 16 of file builtins-promise-gen.h.
Constructor & Destructor Documentation
PromiseBuiltinsAssembler()
v8::internal::PromiseBuiltinsAssembler::PromiseBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 18 of file builtins-promise-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
AllocateJSPromise()
TNode< HeapObject > v8::internal::PromiseBuiltinsAssembler::AllocateJSPromise (TNode< Context > context)
Definition at line 30 of file builtins-promise-gen.cc.
                            {
  return Allocate(JSPromise::kSizeWithEmbedderFields);
}
References v8::internal::CodeStubAssembler::Allocate(), and v8::internal::JSPromise::kSizeWithEmbedderFields.
ZeroOutEmbedderOffsets()
void v8::internal::PromiseBuiltinsAssembler::ZeroOutEmbedderOffsets (TNode< JSPromise > promise)
Definition at line 22 of file builtins-promise-gen.cc.
                              {
  for (int offset = JSPromise::kHeaderSize;
       offset < JSPromise::kSizeWithEmbedderFields; offset += kTaggedSize) {
    StoreObjectFieldNoWriteBarrier(promise, offset, SmiConstant(Smi::zero()));
  }
}
References v8::internal::JSPromise::kSizeWithEmbedderFields, v8::internal::kTaggedSize, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), and v8::internal::Smi::zero().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-promise-gen.h
/mnt/V8SourceCode/src/builtins/builtins-promise-gen.cc