v8::internal::ConditionalSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
ConditionalSourceRanges (const SourceRange &then_range, const SourceRange &else_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
Private Attributes
SourceRange then_range_
SourceRange else_range_
Detailed Description
Definition at line 179 of file ast-source-ranges.h.
Constructor & Destructor Documentation
ConditionalSourceRanges()
v8::internal::ConditionalSourceRanges::ConditionalSourceRanges (const SourceRange & then_range, const SourceRange & else_range) [inline], [explicit]
Definition at line 181 of file ast-source-ranges.h.
      : then_range_(then_range), else_range_(else_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::ConditionalSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 185 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    switch (kind) {
      case SourceRangeKind::kThen:
        return then_range_;
      case SourceRangeKind::kElse:
        return else_range_;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::DCHECK(), else_range_, HasRange(), v8::internal::kElse, v8::internal::kThen, then_range_, and v8::internal::UNREACHABLE().
HasRange()
bool v8::internal::ConditionalSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 197 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kThen || kind == SourceRangeKind::kElse;
  }
References v8::internal::kElse, and v8::internal::kThen.
Referenced by GetRange().
Member Data Documentation
else_range_
SourceRange v8::internal::ConditionalSourceRanges::else_range_ [private]
Definition at line 203 of file ast-source-ranges.h.
Referenced by GetRange().
then_range_
SourceRange v8::internal::ConditionalSourceRanges::then_range_ [private]
Definition at line 202 of file ast-source-ranges.h.
Referenced by GetRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h