v8::internal::wasm::LocalDeclEncoder Class Reference
#include <local-decl-encoder.h>
Public Member Functions
LocalDeclEncoder (Zone *zone, const FunctionSig *s=nullptr)
void Prepend (Zone *zone, const uint8_t **start, const uint8_t **end) const
size_t Emit (uint8_t *buffer) const
uint32_t AddLocals (uint32_t count, ValueType type)
size_t Size () const
bool has_sig () const
const FunctionSig * get_sig () const
void set_sig (const FunctionSig *s)
Private Attributes
const FunctionSig * sig
ZoneVector< std::pair< uint32_t, ValueType > > local_decls
size_t total
Detailed Description
Definition at line 22 of file local-decl-encoder.h.
Constructor & Destructor Documentation
LocalDeclEncoder()
v8::internal::wasm::LocalDeclEncoder::LocalDeclEncoder (Zone * zone, const FunctionSig * s = nullptr) [inline], [explicit]
Definition at line 24 of file local-decl-encoder.h.
      : sig(s), local_decls(zone), total(0) {}
Member Function Documentation
AddLocals()
uint32_t v8::internal::wasm::LocalDeclEncoder::AddLocals (uint32_t count, ValueType type)
Definition at line 56 of file local-decl-encoder.cc.
                                                                   {
  uint32_t result =
      static_cast<uint32_t>(total + (sig ? sig->parameter_count() : 0));
  total += count;
  if (!local_decls.empty() && local_decls.back().second == type) {
    count += local_decls.back().first;
    local_decls.pop_back();
  }
  local_decls.push_back(std::pair<uint32_t, ValueType>(count, type));
  return result;
}
References local_decls, v8::internal::Signature< T >::parameter_count(), v8::base::internal::result, sig, total, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::WasmFunctionBuilder::AddLocal().
Emit()
size_t v8::internal::wasm::LocalDeclEncoder::Emit (uint8_t * buffer) const
Definition at line 31 of file local-decl-encoder.cc.
                                                   {
  uint8_t* pos = buffer;
  LEBHelper::write_u32v(&pos, static_cast<uint32_t>(local_decls.size()));
  for (auto& local_decl : local_decls) {
    uint32_t locals_count = local_decl.first;
    ValueType locals_type = local_decl.second;
    LEBHelper::write_u32v(&pos, locals_count);
    *pos = locals_type.value_type_code();
    ++pos;
    if (locals_type.encoding_needs_shared()) {
      *pos = kSharedFlagCode;
      ++pos;
    }
    if (locals_type.encoding_needs_heap_type()) {
      if (locals_type.encoding_needs_exact()) {
        *pos = kExactCode;
        ++pos;
      }
      LEBHelper::write_i32v(&pos, locals_type.heap_type().code());
    }
  }
  DCHECK_EQ(Size(), pos - buffer);
  return static_cast<size_t>(pos - buffer);
}
References v8::internal::wasm::HeapType::code(), DCHECK_EQ, v8::internal::wasm::ValueTypeBase::encoding_needs_exact(), v8::internal::wasm::ValueTypeBase::encoding_needs_heap_type(), v8::internal::wasm::ValueTypeBase::encoding_needs_shared(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::kExactCode, v8::internal::wasm::kSharedFlagCode, local_decls, Size(), v8::internal::wasm::ValueTypeBase::value_type_code(), v8::internal::wasm::LEBHelper::write_i32v(), and v8::internal::wasm::LEBHelper::write_u32v().
Referenced by Prepend(), and v8::internal::wasm::WasmFunctionBuilder::WriteBody().
get_sig()
const FunctionSig* v8::internal::wasm::LocalDeclEncoder::get_sig () const [inline]
Definition at line 40 of file local-decl-encoder.h.
{ return sig; }
References v8::internal::sig.
has_sig()
bool v8::internal::wasm::LocalDeclEncoder::has_sig () const [inline]
Definition at line 39 of file local-decl-encoder.h.
{ return sig != nullptr; }
References v8::internal::sig.
Referenced by v8::internal::wasm::WasmFunctionBuilder::AddLocal(), and v8::internal::wasm::WasmFunctionBuilder::SetSignature().
Prepend()
void v8::internal::wasm::LocalDeclEncoder::Prepend (Zone * zone, const uint8_t ** start, const uint8_t ** end) const
Definition at line 17 of file local-decl-encoder.cc.
                                                          {
  size_t size = (*end - *start);
  uint8_t* buffer =
      zone->AllocateArray<uint8_t, LocalDeclEncoderBuffer>(Size() + size);
  size_t pos = Emit(buffer);
  if (size > 0) {
    memcpy(buffer + pos, *start, size);
  }
  pos += size;
  *start = buffer;
  *end = buffer + pos;
}
References v8::internal::Zone::AllocateArray(), Emit(), v8::internal::compiler::end(), Size(), and size().
set_sig()
void v8::internal::wasm::LocalDeclEncoder::set_sig (const FunctionSig * s) [inline]
Definition at line 41 of file local-decl-encoder.h.
{ sig = s; }
References v8::internal::sig.
Referenced by v8::internal::wasm::WasmFunctionBuilder::SetSignature().
Size()
size_t v8::internal::wasm::LocalDeclEncoder::Size () const
Definition at line 70 of file local-decl-encoder.cc.
                                    {
  size_t size = LEBHelper::sizeof_u32v(local_decls.size());
  for (auto p : local_decls) {
    size += LEBHelper::sizeof_u32v(p.first) + // number of locals
            1 + // Opcode
            (p.second.encoding_needs_shared() ? 1 : 0) +
            (p.second.encoding_needs_exact() ? 1 : 0) +
            (p.second.encoding_needs_heap_type()
                 ? LEBHelper::sizeof_i32v(p.second.heap_type().code())
                 : 0);
  }
  return size;
}
References local_decls, size(), v8::internal::wasm::LEBHelper::sizeof_i32v(), and v8::internal::wasm::LEBHelper::sizeof_u32v().
Referenced by Emit(), Prepend(), v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable(), and v8::internal::wasm::WasmFunctionBuilder::WriteBody().
Member Data Documentation
local_decls
ZoneVector<std::pair<uint32_t, ValueType> > v8::internal::wasm::LocalDeclEncoder::local_decls [private]
Definition at line 45 of file local-decl-encoder.h.
Referenced by AddLocals(), Emit(), and Size().
sig
const FunctionSig* v8::internal::wasm::LocalDeclEncoder::sig [private]
Definition at line 44 of file local-decl-encoder.h.
Referenced by AddLocals().
total
size_t v8::internal::wasm::LocalDeclEncoder::total [private]
Definition at line 46 of file local-decl-encoder.h.
Referenced by AddLocals().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/local-decl-encoder.h
/mnt/V8SourceCode/src/wasm/local-decl-encoder.cc