v8::Local< T > Class Template Reference
An object reference managed by the v8 garbage collector.
#include <v8-local-handle.h>
Public Member Functions
Local ()=default
Default constructor: Returns an empty handle.
template<class S >
requires std::is_base_of_v< T, S > Local (Local< S > that)
Constructor for handling automatic up casting.
T * operator-> () const
T * operator* () const
template<class S >
bool operator== (const Local< S > &that) const
Checks whether two handles are equal or different.
template<class S >
bool operator== (const PersistentBase< S > &that) const
template<class S >
bool operator!= (const Local< S > &that) const
template<class S >
bool operator!= (const Persistent< S > &that) const
template<class S >
Local< S > As () const
Calling this is equivalent to Local<S>::Cast().
Static Public Member Functions
template<class S >
static Local< T > Cast (Local< S > that)
Cast a handle to a subclass, e.g.
static Local< T > New (Isolate *isolate, Local< T > that)
Create a local handle for the content of another handle.
static Local< T > New (Isolate *isolate, const PersistentBase< T > &that)
static Local< T > New (Isolate *isolate, const BasicTracedReference< T > &that)
Private Member Functions
Local (no_checking_tag do_not_check)
Local (const Local< T > &other, no_checking_tag do_not_check)
Local (const LocalBase< T > &other)
template<class S >
Local< S > UnsafeAs () const
Static Private Member Functions
static Local< T > FromRepr (internal::ValueHelper::InternalRepresentationType repr)
static Local< T > FromSlot (internal::Address *slot)
static Local< T > New (Isolate *isolate, internal::Address value)
static Local< T > New (Isolate *isolate, T *that)
Friends
class TracedReferenceBase
class Utils
template<class F >
class Eternal
template<class F >
class Global
template<class F >
class Local
template<class F >
class MaybeLocal
template<class F , class M >
class Persistent
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
template<class F >
class FunctionCallbackInfo
template<class F >
class PropertyCallbackInfo
class String
class Object
class Context
class Isolate
class Private
template<class F >
class internal::CustomArguments
class HandleScope
class EscapableHandleScope
class InternalEscapableScope
template<class F1 , class F2 , class F3 >
class PersistentValueMapBase
template<class F >
class ReturnValue
template<class F >
class Traced
class internal::SamplingHeapProfiler
class internal::HandleHelper
class debug::ConsoleCallArguments
class internal::LocalUnchecked< T >
Local< Primitive > Undefined (Isolate *isolate)
Local< Primitive > Null (Isolate *isolate)
Local< Boolean > True (Isolate *isolate)
Local< Boolean > False (Isolate *isolate)
Additional Inherited Members
Detailed Description
template<class T>
class v8::Local< T >
An object reference managed by the v8 garbage collector.
All objects returned from v8 have to be tracked by the garbage collector so that it knows that the objects are still alive. Also, because the garbage collector may move objects, it is unsafe to point directly to an object. Instead, all objects are stored in handles which are known by the garbage collector and updated whenever an object moves. Handles should always be passed by value (except in cases like out-parameters) and they should never be allocated on the heap.
There are two types of handles: local and persistent handles.
Local handles are light-weight and transient and typically used in local operations. They are managed by HandleScopes. That means that a HandleScope must exist on the stack when they are created and that they are only valid inside of the HandleScope active during their creation. For passing a local handle to an outer HandleScope, an EscapableHandleScope and its Escape() method must be used.
Persistent handles can be used when storing objects across several independent operations and have to be explicitly deallocated when they're no longer used.
It is safe to extract the object stored in the handle by dereferencing the handle (for instance, to extract the Object* from a Local<Object>); the value will still be governed by a handle behind the scenes and the same rules apply to these values as to their handles.
Definition at line 291 of file v8-local-handle.h.
Constructor & Destructor Documentation
Local() [1/5]
template<class T >
v8::Local< T >::Local () [inline], [default]
Default constructor: Returns an empty handle.
Local() [2/5]
template<class T >
template<class S >
requires std::is_base_of_v<T, S> v8::Local< T >::Local (Local< S > that) [inline]
Constructor for handling automatic up casting.
Ex. Local<Object> can be passed when Local<Value> is expected but not the other way round.
Definition at line 311 of file v8-local-handle.h.
: LocalBase<T>(that) {}
Local() [3/5]
template<class T >
v8::Local< T >::Local (no_checking_tag do_not_check) [inline], [explicit], [private]
Definition at line 435 of file v8-local-handle.h.
      : LocalBase<T>(), StackAllocated(do_not_check) {}
Local() [4/5]
template<class T >
v8::Local< T >::Local (const Local< T > & other, no_checking_tag do_not_check) [inline], [explicit], [private]
Definition at line 437 of file v8-local-handle.h.
      : LocalBase<T>(other), StackAllocated(do_not_check) {}
Local() [5/5]
template<class T >
v8::Local< T >::Local (const LocalBase< T > & other) [inline], [explicit], [private]
Definition at line 440 of file v8-local-handle.h.
: LocalBase<T>(other) {}
Member Function Documentation
As()
template<class T >
template<class S >
Local<S> v8::Local< T >::As () const [inline]
Calling this is equivalent to Local<S>::Cast().
In particular, this is only valid if the handle actually refers to a value of the target type or if the handle is empty.
Definition at line 370 of file v8-local-handle.h.
                                {
    return Local<S>::Cast(*this);
  }
References v8::Local< T >::Cast().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArrayFastCallback(), v8::internal::CppGraphBuilderImpl::AddEdge(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::clientMirror(), v8_inspector::V8Debugger::collectionsEntries(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringFastCallback(), v8_inspector::ValueMirror::create(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForProxy(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::Shell::DoHostImportModuleDynamically(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::internal::ExtractEmbedderDataBackref(), v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig(), v8_inspector::V8SerializationDuplicateTracker::FindKnownSerializedValue(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgAsFunction(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToString(), v8::Shell::FunctionAndArgumentsToString(), v8_inspector::generateCustomPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::InspectedContext::getInternalType(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::ValueMirror::getProperties(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectFastCallback(), v8::anonymous_namespace{d8.cc}::IsValidHostDefinedOptions(), v8_inspector::V8Regex::match(), v8::Shell::PerformanceMeasure(), v8::Serializer::PrepareTransfer(), v8_inspector::V8Debugger::privateMethods(), v8::Worker::ProcessMessage(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::V8Console::queryObjectsCallback(), v8::internal::anonymous_namespace{gc-extension.cc}::ReadProperty(), v8::Shell::ReportException(), v8::OnMessageFromWorkerTask::Run(), v8::InspectorClient::runMessageLoopOnPause(), v8_inspector::V8Console::runTask(), v8::InspectorFrontend::Send(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8::Shell::SetFlushDenormals(), v8::AsyncHooks::ShellPromiseHook(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8::EmbedderGraph::V8Node(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), v8_inspector::V8ConsoleMessage::wrapArguments(), v8_inspector::InjectedScript::wrapTable(), and v8::WriteToFile().
Cast()
template<class T >
template<class S >
static Local<T> v8::Local< T >::Cast (Local< S > that) [inline], [static]
Cast a handle to a subclass, e.g.
Local<Value> to Local<Object>. This is only valid if the handle actually refers to a value of the target type or if the handle is empty.
Definition at line 354 of file v8-local-handle.h.
                                                {
#ifdef V8_ENABLE_CHECKS
    // If we're going to perform the type check then we have to check
    // that the handle isn't empty before doing the checked cast.
    if (that.IsEmpty()) return Local<T>();
    T::Cast(that.template value<S>());
#endif
    return Local<T>(LocalBase<T>(that));
  }
References v8::internal::Cast(), and v8::api_internal::IndirectHandleBase::IsEmpty().
Referenced by v8::Local< T >::As(), v8::MaybeLocal< T >::Cast(), v8::anonymous_namespace{wasm-js.cc}::GetFirstArgumentAsBytes(), v8::Promise::Resolver::GetPromise(), v8::Message::GetWasmFunctionIndex(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ImportsAsMaybeReceiver(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::IsWasmInstantiateAllowed(), v8::Signature::New(), v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall(), v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), v8::Shell::WriteFile(), and v8::anonymous_namespace{d8-console.cc}::WriteToFile().
FromRepr()
template<class T >
static Local<T> v8::Local< T >::FromRepr (internal::ValueHelper::InternalRepresentationType repr) [inline], [static], [private]
Definition at line 442 of file v8-local-handle.h.
                                                          {
    return Local<T>(LocalBase<T>::FromRepr(repr));
  }
Referenced by v8::Context::GetDataFromSnapshotOnce(), and v8::Isolate::GetDataFromSnapshotOnce().
FromSlot()
template<class T >
static Local<T> v8::Local< T >::FromSlot (internal::Address * slot) [inline], [static], [private]
Definition at line 447 of file v8-local-handle.h.
                                                            {
    return Local<T>(LocalBase<T>::FromSlot(slot));
  }
Referenced by v8::Utils::Convert(), v8::FunctionCallbackInfo< T >::Data(), v8::PropertyCallbackInfo< T >::Data(), v8::String::Empty(), v8::EscapableHandleScope::Escape(), v8::InternalEscapableScope::Escape(), v8::Eternal< T >::Get(), v8::PropertyCallbackInfo< T >::HolderV2(), v8::FunctionCallbackInfo< T >::NewTarget(), v8::FunctionCallbackInfo< T >::operator[](), v8::debug::ConsoleCallArguments::operator[](), v8::internal::SamplingHeapProfiler::SampleObject(), v8::FunctionCallbackInfo< T >::This(), and v8::PropertyCallbackInfo< T >::This().
New() [1/5]
template<class T >
static Local<T> v8::Local< T >::New (Isolate * isolate, const BasicTracedReference< T > & that) [inline], [static]
Definition at line 388 of file v8-local-handle.h.
                                                                     {
    return New(isolate, that.template value<T, true>());
  }
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
New() [2/5]
template<class T >
static Local<T> v8::Local< T >::New (Isolate * isolate, const PersistentBase< T > & that) [inline], [static]
Definition at line 383 of file v8-local-handle.h.
                                                               {
    return New(isolate, that.template value<T, true>());
  }
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
New() [3/5]
template<class T >
static Local<T> v8::Local< T >::New (Isolate * isolate, internal::Address value) [inline], [static], [private]
Definition at line 459 of file v8-local-handle.h.
                                                                         {
    return Local<T>(LocalBase<T>::New(isolate, value));
  }
References v8::internal::value.
New() [4/5]
template<class T >
static Local<T> v8::Local< T >::New (Isolate * isolate, Local< T > that) [inline], [static]
Create a local handle for the content of another handle.
The referee is kept alive by the local handle even when the original handle is destroyed/disposed.
Definition at line 379 of file v8-local-handle.h.
                                                                 {
    return New(isolate, that.template value<T, true>());
  }
References v8::internal::anonymous_namespace{intl-objects.cc}::New().
Referenced by v8::Shell::ExecuteString(), v8::PerIsolateData::ExplicitRealmScope::ExplicitRealmScope(), v8::Serializer::FinalizeTransfer(), v8::ReturnValue< T >::Get(), v8::PersistentValueMapBase< K, V, Traits >::Get(), v8::PersistentBase< T >::Get(), v8::TracedReferenceBase::Get(), v8::BasicTracedReference< T >::Get(), v8::Context::GetEmbedderData(), v8::Object::GetInternalField(), v8::PersistentValueMapBase< K, V, Traits >::PersistentValueReference::NewLocal(), v8::Shell::RealmDetachGlobal(), v8::Shell::RealmGlobal(), v8::Shell::RealmNavigate(), v8::Shell::ReportException(), v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::RunInternal(), v8::Shell::RunMain(), v8::PersistentValueMap< K, V, Traits >::SetUnique(), v8::GlobalValueMap< K, V, Traits >::SetUnique(), and v8::Shell::Stringify().
New() [5/5]
template<class T >
static Local<T> v8::Local< T >::New (Isolate * isolate, T * that) [inline], [static], [private]
Definition at line 463 of file v8-local-handle.h.
                                                           {
    return Local<T>(LocalBase<T>::New(isolate, that));
  }
operator!=() [1/2]
template<class T >
template<class S >
bool v8::Local< T >::operator!= (const Local< S > & that) const [inline]
Definition at line 339 of file v8-local-handle.h.
                                                        {
    return !operator==(that);
  }
References v8::operator==().
operator!=() [2/2]
template<class T >
template<class S >
bool v8::Local< T >::operator!= (const Persistent< S > & that) const [inline]
Definition at line 344 of file v8-local-handle.h.
                                                             {
    return !operator==(that);
  }
References v8::operator==().
operator*()
template<class T >
T* v8::Local< T >::operator* () const [inline]
Definition at line 315 of file v8-local-handle.h.
{ return this->operator->(); }
operator->()
template<class T >
T* v8::Local< T >::operator-> () const [inline]
Definition at line 313 of file v8-local-handle.h.
{ return this->template value<T>(); }
operator==() [1/2]
template<class T >
template<class S >
bool v8::Local< T >::operator== (const Local< S > & that) const [inline]
Checks whether two handles are equal or different.
They are equal iff they are both empty or they are both non-empty and the objects to which they refer are physically equal.
If both handles refer to JS objects, this is the same as strict non-equality. For primitives, such as numbers or strings, a true return value does not indicate that the values aren't equal in the JavaScript sense. Use Value::StrictEquals() to check primitives for equality.
Definition at line 329 of file v8-local-handle.h.
                                                        {
    return internal::HandleHelper::EqualHandles(*this, that);
  }
References v8::internal::HandleHelper::EqualHandles().
operator==() [2/2]
template<class T >
template<class S >
bool v8::Local< T >::operator== (const PersistentBase< S > & that) const [inline]
Definition at line 334 of file v8-local-handle.h.
                                                                 {
    return internal::HandleHelper::EqualHandles(*this, that);
  }
References v8::internal::HandleHelper::EqualHandles().
UnsafeAs()
template<class T >
template<class S >
Local<S> v8::Local< T >::UnsafeAs () const [inline], [private]
Definition at line 469 of file v8-local-handle.h.
                                      {
    return Local<S>(LocalBase<S>(*this));
  }
Friends And Related Function Documentation
Context
template<class T >
friend class Context [friend]
Definition at line 412 of file v8-local-handle.h.
debug::ConsoleCallArguments
template<class T >
friend class debug::ConsoleCallArguments [friend]
Definition at line 432 of file v8-local-handle.h.
EscapableHandleScope
template<class T >
friend class EscapableHandleScope [friend]
Definition at line 422 of file v8-local-handle.h.
Eternal
template<class T >
template<class F >
friend class Eternal [friend]
Definition at line 397 of file v8-local-handle.h.
False
template<class T >
Local<Boolean> False (Isolate * isolate) [friend]
Definition at line 1079 of file v8-primitive.h.
                                                 {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kFalseValueRootIndex);
  return Local<Boolean>::FromSlot(slot);
}
FunctionCallbackInfo
template<class T >
template<class F >
friend class FunctionCallbackInfo [friend]
Definition at line 407 of file v8-local-handle.h.
Global
template<class T >
template<class F >
friend class Global [friend]
Definition at line 399 of file v8-local-handle.h.
HandleScope
template<class T >
friend class HandleScope [friend]
Definition at line 421 of file v8-local-handle.h.
internal::CustomArguments
template<class T >
template<class F >
friend class internal::CustomArguments [friend]
Definition at line 416 of file v8-local-handle.h.
internal::HandleHelper
template<class T >
friend class internal::HandleHelper [friend]
Definition at line 431 of file v8-local-handle.h.
internal::LocalUnchecked< T >
template<class T >
friend class internal::LocalUnchecked< T > [friend]
Definition at line 432 of file v8-local-handle.h.
internal::SamplingHeapProfiler
template<class T >
friend class internal::SamplingHeapProfiler [friend]
Definition at line 430 of file v8-local-handle.h.
InternalEscapableScope
template<class T >
friend class InternalEscapableScope [friend]
Definition at line 423 of file v8-local-handle.h.
Isolate
template<class T >
friend class Isolate [friend]
Definition at line 413 of file v8-local-handle.h.
Local
template<class T >
template<class F >
friend class Local [friend]
Definition at line 401 of file v8-local-handle.h.
MaybeLocal
template<class T >
template<class F >
friend class MaybeLocal [friend]
Definition at line 403 of file v8-local-handle.h.
Null
template<class T >
Local<Primitive> Null (Isolate * isolate) [friend]
Definition at line 1063 of file v8-primitive.h.
                                                  {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kNullValueRootIndex);
  return Local<Primitive>::FromSlot(slot);
}
Object
template<class T >
friend class Object [friend]
Definition at line 411 of file v8-local-handle.h.
Persistent
template<class T >
template<class F , class M >
friend class Persistent [friend]
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
As long as the Persistent handle is alive the GC will keep the object pointed to alive. The Persistent handle is always a GC root from the point of view of the GC. Persistent must be constructed and destructed in the same thread.
Definition at line 405 of file v8-local-handle.h.
PersistentValueMapBase
template<class T >
template<class F1 , class F2 , class F3 >
friend class PersistentValueMapBase [friend]
Definition at line 425 of file v8-local-handle.h.
Private
template<class T >
friend class Private [friend]
Definition at line 414 of file v8-local-handle.h.
PropertyCallbackInfo
template<class T >
template<class F >
friend class PropertyCallbackInfo [friend]
Definition at line 409 of file v8-local-handle.h.
ReturnValue
template<class T >
template<class F >
friend class ReturnValue [friend]
Definition at line 427 of file v8-local-handle.h.
String
template<class T >
friend class String [friend]
Definition at line 410 of file v8-local-handle.h.
Traced
template<class T >
template<class F >
friend class Traced [friend]
Definition at line 429 of file v8-local-handle.h.
TracedReferenceBase
template<class T >
friend class TracedReferenceBase [friend]
Definition at line 394 of file v8-local-handle.h.
True
template<class T >
Local<Boolean> True (Isolate * isolate) [friend]
Definition at line 1071 of file v8-primitive.h.
                                                {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kTrueValueRootIndex);
  return Local<Boolean>::FromSlot(slot);
}
Undefined
template<class T >
Local<Primitive> Undefined (Isolate * isolate) [friend]
Definition at line 1055 of file v8-primitive.h.
                                                       {
  using S = internal::Address;
  using I = internal::Internals;
  I::CheckInitialized(isolate);
  S* slot = I::GetRootSlot(isolate, I::kUndefinedValueRootIndex);
  return Local<Primitive>::FromSlot(slot);
}
Utils
template<class T >
friend class Utils [friend]
Definition at line 395 of file v8-local-handle.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-local-handle.h