v8::internal::SlotSet Class Reference
#include <slot-set.h>
Public Member Functions
template<v8::internal::AccessMode access_mode = v8::internal::AccessMode::ATOMIC, typename Callback >
size_t Iterate (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, EmptyBucketMode mode)
template<typename Callback >
size_t IterateAndTrackEmptyBuckets (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, PossiblyEmptyBuckets *possibly_empty_buckets)
bool CheckPossiblyEmptyBuckets (size_t buckets, PossiblyEmptyBuckets *possibly_empty_buckets)
void Merge (SlotSet *other, size_t buckets)
Static Public Member Functions
static SlotSet * Allocate (size_t buckets)
template<v8::internal::AccessMode access_mode>
static constexpr BasicSlotSet::AccessMode ConvertAccessMode ()
Static Public Attributes
static const int kBucketsRegularPage
Private Types
using BasicSlotSet = ::heap::base::BasicSlotSet< kTaggedSize >
Additional Inherited Members
Detailed Description
Definition at line 126 of file slot-set.h.
Member Typedef Documentation
BasicSlotSet
using v8::internal::SlotSet::BasicSlotSet = ::heap::base::BasicSlotSet<kTaggedSize> [private]
Definition at line 127 of file slot-set.h.
Member Function Documentation
Allocate()
static SlotSet* v8::internal::SlotSet::Allocate (size_t buckets) [inline], [static]
Definition at line 133 of file slot-set.h.
                                           {
    return static_cast<SlotSet*>(BasicSlotSet::Allocate(buckets));
  }
References heap::base::BasicSlotSet< kTaggedSize >::Allocate(), and heap::base::BasicSlotSet< kTaggedSize >::buckets().
Referenced by v8::internal::MutablePageMetadata::AllocateSlotSet().
CheckPossiblyEmptyBuckets()
bool v8::internal::SlotSet::CheckPossiblyEmptyBuckets (size_t buckets, PossiblyEmptyBuckets * possibly_empty_buckets) [inline]
Definition at line 182 of file slot-set.h.
                                                                               {
    bool empty = true;
    for (size_t bucket_index = 0; bucket_index < buckets; bucket_index++) {
      Bucket* bucket = LoadBucket<AccessMode::NON_ATOMIC>(bucket_index);
      if (bucket) {
        if (possibly_empty_buckets->Contains(bucket_index)) {
          if (bucket->IsEmpty()) {
            ReleaseBucket<AccessMode::NON_ATOMIC>(bucket_index);
          } else {
            empty = false;
          }
        } else {
          empty = false;
        }
      } else {
        // Unfortunately we cannot DCHECK here that the corresponding bit in
        // possibly_empty_buckets is not set. After scavenge, the
        // MergeOldToNewRememberedSets operation might remove a recorded bucket.
      }
    }
    possibly_empty_buckets->Release();
    return empty;
  }
References heap::base::BasicSlotSet< kTaggedSize >::bucket(), heap::base::BasicSlotSet< kTaggedSize >::buckets(), v8::internal::PossiblyEmptyBuckets::Contains(), and v8::internal::PossiblyEmptyBuckets::Release().
Referenced by v8::internal::RememberedSet< type >::CheckPossiblyEmptyBuckets().
ConvertAccessMode()
template<v8::internal::AccessMode access_mode>
static constexpr BasicSlotSet::AccessMode v8::internal::SlotSet::ConvertAccessMode () [inline], [static], [constexpr]
Definition at line 138 of file slot-set.h.
                                                              {
    switch (access_mode) {
      case v8::internal::AccessMode::ATOMIC:
        return BasicSlotSet::AccessMode::ATOMIC;
      case v8::internal::AccessMode::NON_ATOMIC:
        return BasicSlotSet::AccessMode::NON_ATOMIC;
    }
  }
References v8::internal::ATOMIC, and v8::internal::NON_ATOMIC.
Iterate()
template<v8::internal::AccessMode access_mode = v8::internal::AccessMode::ATOMIC, typename Callback >
size_t v8::internal::SlotSet::Iterate (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, EmptyBucketMode mode) [inline]
Definition at line 152 of file slot-set.h.
                                                          {
    return BasicSlotSet::Iterate<ConvertAccessMode<access_mode>()>(
        chunk_start, start_bucket, end_bucket,
        [&callback](Address slot) { return callback(MaybeObjectSlot(slot)); },
        [this, mode](size_t bucket_index) {
          if (mode == EmptyBucketMode::FREE_EMPTY_BUCKETS) {
            ReleaseBucket(bucket_index);
          }
        });
  }
References mode(), and heap::base::BasicSlotSet< kTaggedSize >::ReleaseBucket().
Referenced by v8::internal::RememberedSetOperations::CheckNoneInRange(), and v8::internal::RememberedSetOperations::Iterate().
IterateAndTrackEmptyBuckets()
template<typename Callback >
size_t v8::internal::SlotSet::IterateAndTrackEmptyBuckets (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, PossiblyEmptyBuckets * possibly_empty_buckets) [inline]
Definition at line 169 of file slot-set.h.
                                                                       {
    return BasicSlotSet::Iterate(
        chunk_start, start_bucket, end_bucket,
        [&callback](Address slot) { return callback(MaybeObjectSlot(slot)); },
        [possibly_empty_buckets, end_bucket](size_t bucket_index) {
          possibly_empty_buckets->Insert(bucket_index, end_bucket);
        });
  }
References v8::internal::PossiblyEmptyBuckets::Insert(), and heap::base::BasicSlotSet< kTaggedSize >::Iterate().
Referenced by v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets().
Merge()
void v8::internal::SlotSet::Merge (SlotSet * other, size_t buckets) [inline]
Definition at line 209 of file slot-set.h.
                                             {
    for (size_t bucket_index = 0; bucket_index < buckets; bucket_index++) {
      Bucket* other_bucket =
          other->LoadBucket<AccessMode::NON_ATOMIC>(bucket_index);
      if (!other_bucket) continue;
      Bucket* bucket = LoadBucket<AccessMode::NON_ATOMIC>(bucket_index);
      if (bucket == nullptr) {
        other->StoreBucket<AccessMode::NON_ATOMIC>(bucket_index, nullptr);
        StoreBucket<AccessMode::NON_ATOMIC>(bucket_index, other_bucket);
      } else {
        for (int cell_index = 0; cell_index < kCellsPerBucket; cell_index++) {
          bucket->SetCellBits<AccessMode::NON_ATOMIC>(
              cell_index,
              other_bucket->LoadCell<AccessMode::NON_ATOMIC>(cell_index));
        }
      }
    }
  }
References heap::base::BasicSlotSet< kTaggedSize >::bucket(), heap::base::BasicSlotSet< kTaggedSize >::buckets(), heap::base::BasicSlotSet< kTaggedSize >::kCellsPerBucket, heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), v8::internal::NON_ATOMIC, and heap::base::BasicSlotSet< SlotGranularity >::StoreBucket().
Referenced by v8::internal::RememberedSet< type >::MergeAndDelete().
Member Data Documentation
kBucketsRegularPage
const int v8::internal::SlotSet::kBucketsRegularPage [static]
Initial value:
=
      (1 << kPageSizeBits) / kTaggedSize / kCellsPerBucket / kBitsPerCell
Definition at line 130 of file slot-set.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/slot-set.h