v8::internal::Immediate Class Reference
#include <assembler-arm64.h>
Classes
union Value
Public Member Functions
template<typename T >
Immediate (Handle< T > handle, RelocInfo::Mode mode=RelocInfo::FULL_EMBEDDED_OBJECT)
template<typename T >
Immediate (T value)
template<typename T >
Immediate (T value, RelocInfo::Mode rmode)
int64_t value () const
RelocInfo::Mode rmode () const
Immediate (int x, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Immediate (const ExternalReference &ext)
Immediate (Handle< HeapObject > handle)
Immediate (Tagged< Smi > value)
bool is_heap_number_request () const
HeapNumberRequest heap_number_request () const
int immediate () const
bool is_embedded_object () const
Handle< HeapObject > embedded_object () const
bool is_external_reference () const
ExternalReference external_reference () const
bool is_zero () const
bool is_int8 () const
bool is_uint8 () const
bool is_int16 () const
bool is_uint16 () const
RelocInfo::Mode rmode () const
constexpr Immediate (int32_t value)
constexpr Immediate (int32_t value, RelocInfo::Mode rmode)
Immediate (Tagged< Smi > value)
int32_t value () const
RelocInfo::Mode rmode () const
Static Public Member Functions
static Immediate EmbeddedNumber (double number)
static Immediate CodeRelativeOffset (Label *label)
Private Member Functions
Immediate (Label *value)
Private Attributes
int64_t value_
RelocInfo::Mode rmode_
union v8::internal::Immediate::Value value_
bool is_heap_number_request_ = false
const int32_t value_
const RelocInfo::Mode rmode_ = RelocInfo::NO_INFO
Friends
class Operand
class Assembler
class MacroAssembler
Detailed Description
Definition at line 41 of file assembler-arm64.h.
Constructor & Destructor Documentation
Immediate() [1/11]
template<typename T >
v8::internal::Immediate::Immediate (Handle< T > handle, RelocInfo::Mode mode = RelocInfo::FULL_EMBEDDED_OBJECT) [inline], [explicit]
Definition at line 230 of file assembler-arm64-inl.h.
    : value_(static_cast<intptr_t>(handle.address())), rmode_(mode) {
  DCHECK(RelocInfo::IsEmbeddedObjectMode(mode));
}
References v8::internal::DCHECK(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), and mode().
Referenced by CodeRelativeOffset().
Immediate() [2/11]
template<typename T >
v8::internal::Immediate::Immediate (T value) [inline]
Definition at line 236 of file assembler-arm64-inl.h.
    : value_(ImmediateInitializer<T>::immediate_for(t)),
      rmode_(ImmediateInitializer<T>::rmode_for(t)) {}
Immediate() [3/11]
template<typename T >
v8::internal::Immediate::Immediate (T value, RelocInfo::Mode rmode) [inline]
Definition at line 241 of file assembler-arm64-inl.h.
    : value_(ImmediateInitializer<T>::immediate_for(t)), rmode_(rmode) {
  static_assert(std::is_integral_v<T>);
}
Immediate() [4/11]
v8::internal::Immediate::Immediate (int x, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 119 of file assembler-ia32.h.
                                                                           {
    value_.immediate = x;
    rmode_ = rmode;
  }
References rmode(), rmode_, and value_.
Immediate() [5/11]
v8::internal::Immediate::Immediate (const ExternalReference & ext) [inline], [explicit]
Definition at line 123 of file assembler-ia32.h.
      : Immediate(ext.raw(), RelocInfo::EXTERNAL_REFERENCE) {}
Immediate() [6/11]
v8::internal::Immediate::Immediate (Handle< HeapObject > handle) [inline], [explicit]
Definition at line 125 of file assembler-ia32.h.
      : Immediate(handle.address(), RelocInfo::FULL_EMBEDDED_OBJECT) {}
Immediate() [7/11]
v8::internal::Immediate::Immediate (Tagged< Smi > value) [inline], [explicit]
Definition at line 127 of file assembler-ia32.h.
      : Immediate(static_cast<intptr_t>(value.ptr())) {}
Immediate() [8/11]
v8::internal::Immediate::Immediate (Label * value) [inline], [explicit], [private]
Definition at line 189 of file assembler-ia32.h.
                                          {
    value_.immediate = reinterpret_cast<int32_t>(value);
    rmode_ = RelocInfo::INTERNAL_REFERENCE;
  }
References v8::internal::RelocInfo::INTERNAL_REFERENCE, rmode_, value(), and value_.
Immediate() [9/11]
constexpr v8::internal::Immediate::Immediate (int32_t value) [inline], [explicit], [constexpr]
Definition at line 128 of file assembler-x64.h.
: value_(value) {}
Immediate() [10/11]
constexpr v8::internal::Immediate::Immediate (int32_t value, RelocInfo::Mode rmode) [inline], [explicit], [constexpr]
Definition at line 129 of file assembler-x64.h.
      : value_(value), rmode_(rmode) {}
Immediate() [11/11]
v8::internal::Immediate::Immediate (Tagged< Smi > value) [inline], [explicit]
Definition at line 131 of file assembler-x64.h.
      : value_(static_cast<int32_t>(static_cast<intptr_t>(value.ptr()))) {
    DCHECK(SmiValuesAre31Bits()); // Only available for 31-bit SMI.
  }
References v8::internal::DCHECK(), and v8::internal::SmiValuesAre31Bits().
Member Function Documentation
CodeRelativeOffset()
static Immediate v8::internal::Immediate::CodeRelativeOffset (Label * label) [inline], [static]
Definition at line 132 of file assembler-ia32.h.
{ return Immediate(label); }
References Immediate().
Referenced by v8::internal::compiler::IA32OperandConverter::ToImmediate().
embedded_object()
Handle<HeapObject> v8::internal::Immediate::embedded_object () const [inline]
Definition at line 156 of file assembler-ia32.h.
                                             {
    return Handle<HeapObject>(reinterpret_cast<Address*>(immediate()));
  }
References immediate().
EmbeddedNumber()
static Immediate v8::internal::Immediate::EmbeddedNumber (double number) [static]
Referenced by v8::internal::compiler::IA32OperandConverter::ToImmediate().
external_reference()
ExternalReference v8::internal::Immediate::external_reference () const [inline]
Definition at line 164 of file assembler-ia32.h.
                                               {
    DCHECK(is_external_reference());
    return base::bit_cast<ExternalReference>(immediate());
  }
References v8::internal::DCHECK(), immediate(), and is_external_reference().
heap_number_request()
HeapNumberRequest v8::internal::Immediate::heap_number_request () const [inline]
Definition at line 141 of file assembler-ia32.h.
                                                {
    DCHECK(is_heap_number_request());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK(), is_heap_number_request(), and value_.
Referenced by v8::internal::Assembler::emit().
immediate()
int v8::internal::Immediate::immediate () const [inline]
Definition at line 146 of file assembler-ia32.h.
                        {
    DCHECK(!is_heap_number_request());
    return value_.immediate;
  }
References v8::internal::DCHECK(), is_heap_number_request(), and value_.
Referenced by embedded_object(), v8::internal::Assembler::emit(), v8::internal::Assembler::emit_b(), v8::internal::Assembler::emit_w(), external_reference(), is_int16(), is_int8(), is_uint16(), is_uint8(), and is_zero().
is_embedded_object()
bool v8::internal::Immediate::is_embedded_object () const [inline]
Definition at line 151 of file assembler-ia32.h.
                                  {
    return !is_heap_number_request() &&
           rmode() == RelocInfo::FULL_EMBEDDED_OBJECT;
  }
References v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, is_heap_number_request(), and rmode().
is_external_reference()
bool v8::internal::Immediate::is_external_reference () const [inline]
Definition at line 160 of file assembler-ia32.h.
                                     {
    return rmode() == RelocInfo::EXTERNAL_REFERENCE;
  }
References v8::internal::RelocInfo::EXTERNAL_REFERENCE, and rmode().
Referenced by external_reference().
is_heap_number_request()
bool v8::internal::Immediate::is_heap_number_request () const [inline]
Definition at line 134 of file assembler-ia32.h.
                                      {
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, is_heap_number_request_, and rmode_.
Referenced by v8::internal::Assembler::emit(), heap_number_request(), immediate(), and is_embedded_object().
is_int16()
bool v8::internal::Immediate::is_int16 () const [inline]
Definition at line 178 of file assembler-ia32.h.
                        {
    return RelocInfo::IsNoInfo(rmode_) && i::is_int16(immediate());
  }
References immediate(), v8::internal::RelocInfo::IsNoInfo(), and rmode_.
is_int8()
bool v8::internal::Immediate::is_int8 () const [inline]
Definition at line 172 of file assembler-ia32.h.
                       {
    return RelocInfo::IsNoInfo(rmode_) && i::is_int8(immediate());
  }
References immediate(), v8::internal::RelocInfo::IsNoInfo(), and rmode_.
Referenced by v8::internal::Assembler::emit_b().
is_uint16()
bool v8::internal::Immediate::is_uint16 () const [inline]
Definition at line 182 of file assembler-ia32.h.
                         {
    return RelocInfo::IsNoInfo(rmode_) && i::is_uint16(immediate());
  }
References immediate(), v8::internal::RelocInfo::IsNoInfo(), and rmode_.
is_uint8()
bool v8::internal::Immediate::is_uint8 () const [inline]
Definition at line 175 of file assembler-ia32.h.
                        {
    return RelocInfo::IsNoInfo(rmode_) && i::is_uint8(immediate());
  }
References immediate(), v8::internal::RelocInfo::IsNoInfo(), and rmode_.
Referenced by v8::internal::Assembler::emit_b().
is_zero()
bool v8::internal::Immediate::is_zero () const [inline]
Definition at line 169 of file assembler-ia32.h.
                       {
    return RelocInfo::IsNoInfo(rmode_) && immediate() == 0;
  }
References immediate(), v8::internal::RelocInfo::IsNoInfo(), and rmode_.
rmode() [1/3]
RelocInfo::Mode v8::internal::Immediate::rmode () const [inline]
Definition at line 56 of file assembler-arm64.h.
{ return rmode_; }
References rmode_.
Referenced by Immediate(), v8::internal::Operand::immediate_for_heap_number_request(), v8::internal::Operand::ImmediateRMode(), is_embedded_object(), and is_external_reference().
rmode() [2/3]
RelocInfo::Mode v8::internal::Immediate::rmode () const [inline]
Definition at line 186 of file assembler-ia32.h.
{ return rmode_; }
References rmode_.
rmode() [3/3]
RelocInfo::Mode v8::internal::Immediate::rmode () const [inline]
Definition at line 137 of file assembler-x64.h.
{ return rmode_; }
References rmode_.
value() [1/2]
int64_t v8::internal::Immediate::value () const [inline]
Definition at line 55 of file assembler-arm64.h.
{ return value_; }
References value_.
Referenced by v8::internal::SharedMacroAssemblerBase::And(), Immediate(), and v8::internal::Operand::ImmediateValue().
value() [2/2]
int32_t v8::internal::Immediate::value () const [inline]
Definition at line 136 of file assembler-x64.h.
{ return value_; }
References value_.
Friends And Related Function Documentation
Assembler
Assembler [friend]
Definition at line 203 of file assembler-ia32.h.
MacroAssembler
friend class MacroAssembler [friend]
Definition at line 204 of file assembler-ia32.h.
Operand
friend class Operand [friend]
Definition at line 202 of file assembler-ia32.h.
Member Data Documentation
is_heap_number_request_
bool v8::internal::Immediate::is_heap_number_request_ = false [private]
Definition at line 199 of file assembler-ia32.h.
Referenced by is_heap_number_request().
rmode_ [1/2]
RelocInfo::Mode v8::internal::Immediate::rmode_ [private]
Definition at line 60 of file assembler-arm64.h.
Referenced by v8::internal::Assembler::emit(), v8::internal::Assembler::emit_w(), Immediate(), is_heap_number_request(), is_int16(), is_int8(), is_uint16(), is_uint8(), is_zero(), and rmode().
rmode_ [2/2]
const RelocInfo::Mode v8::internal::Immediate::rmode_ = RelocInfo::NO_INFO [private]
Definition at line 141 of file assembler-x64.h.
value_ [1/3]
int64_t v8::internal::Immediate::value_ [private]
Definition at line 59 of file assembler-arm64.h.
Referenced by heap_number_request(), immediate(), Immediate(), and value().
value_ [2/3]
union v8::internal::Immediate::Value v8::internal::Immediate::value_ [private]
value_ [3/3]
const int32_t v8::internal::Immediate::value_ [private]
Definition at line 140 of file assembler-x64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64.h
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32.h
/mnt/V8SourceCode/src/codegen/x64/assembler-x64.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h