v8::internal::MemoryChunkIterator Class Reference
#include <spaces.h>
Public Member Functions
MemoryChunkIterator (Heap *heap)
bool HasNext ()
MutablePageMetadata * Next ()
Private Attributes
SpaceIterator space_iterator_
MutablePageMetadata * current_chunk_ = nullptr
Detailed Description
Definition at line 242 of file spaces.h.
Constructor & Destructor Documentation
MemoryChunkIterator()
v8::internal::MemoryChunkIterator::MemoryChunkIterator (Heap * heap) [inline], [explicit]
Definition at line 244 of file spaces.h.
: space_iterator_(heap) {}
Member Function Documentation
HasNext()
bool v8::internal::MemoryChunkIterator::HasNext () [inline]
Definition at line 116 of file spaces-inl.h.
                                  {
  if (current_chunk_) return true;
  while (space_iterator_.HasNext()) {
    Space* space = space_iterator_.Next();
    current_chunk_ = space->first_page();
    if (current_chunk_) return true;
  }
  return false;
}
References current_chunk_, v8::internal::SpaceIterator::HasNext(), v8::internal::SpaceIterator::Next(), space, and space_iterator_.
Referenced by v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
Next()
MutablePageMetadata * v8::internal::MemoryChunkIterator::Next () [inline]
Definition at line 128 of file spaces-inl.h.
                                               {
  MutablePageMetadata* chunk = current_chunk_;
  current_chunk_ = chunk->list_node().next();
  return chunk;
}
References current_chunk_, and v8::internal::MutablePageMetadata::list_node().
Referenced by v8::internal::MarkCompactCollector::UpdatePointersInClientHeap().
Member Data Documentation
current_chunk_
MutablePageMetadata* v8::internal::MemoryChunkIterator::current_chunk_ = nullptr [private]
Definition at line 251 of file spaces.h.
Referenced by HasNext(), and Next().
space_iterator_
SpaceIterator v8::internal::MemoryChunkIterator::space_iterator_ [private]
Definition at line 250 of file spaces.h.
Referenced by HasNext().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/spaces.h
/mnt/V8SourceCode/src/heap/spaces-inl.h