v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits > Class Template Reference
Public Types
using BackingStore = typename KindTraits::BackingStore
Static Public Member Functions
static Tagged< Object > RemoveElement (Isolate *isolate, DirectHandle< JSArray > receiver, Where remove_position)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry)
static void DeleteAtEnd (Isolate *isolate, DirectHandle< JSObject > obj, DirectHandle< BackingStore > backing_store, uint32_t entry)
static void DeleteCommon (Isolate *isolate, DirectHandle< JSObject > obj, uint32_t entry, DirectHandle< FixedArrayBase > store)
static Tagged< Object > PopImpl (Isolate *isolate, DirectHandle< JSArray > receiver)
static Maybe< uint32_t > PushImpl (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t push_size)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static Maybe< bool > SetLengthImpl (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >
Definition at line 2961 of file elements.cc.
Member Typedef Documentation
BackingStore
template<typename Subclass , typename KindTraits >
using v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::BackingStore = typename KindTraits::BackingStore
Definition at line 2964 of file elements.cc.
Member Function Documentation
AddImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 2999 of file elements.cc.
                                                    {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteAtEnd()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::DeleteAtEnd (Isolate * isolate, DirectHandle< JSObject > obj, DirectHandle< BackingStore > backing_store, uint32_t entry) [inline], [static]
Definition at line 2977 of file elements.cc.
                                          {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteCommon()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::DeleteCommon (Isolate * isolate, DirectHandle< JSObject > obj, uint32_t entry, DirectHandle< FixedArrayBase > store) [inline], [static]
Definition at line 2983 of file elements.cc.
                                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [static]
Definition at line 2972 of file elements.cc.
                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
PopImpl()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::PopImpl (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [static]
Definition at line 2988 of file elements.cc.
                                                                {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
PushImpl()
template<typename Subclass , typename KindTraits >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::PushImpl (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t push_size) [inline], [static]
Definition at line 2993 of file elements.cc.
                                                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
RemoveElement()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::RemoveElement (Isolate * isolate, DirectHandle< JSArray > receiver, Where remove_position) [inline], [static]
Definition at line 2966 of file elements.cc.
                                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SetLengthImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastSealedObjectElementsAccessor< Subclass, KindTraits >::SetLengthImpl (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store) [inline], [static]
Definition at line 3009 of file elements.cc.
                                                                               {
    uint32_t old_length = 0;
    CHECK(Object::ToArrayIndex(array->length(), &old_length));
    if (length == old_length) {
      // Do nothing.
      return Just(true);
    }
    // Transition to DICTIONARY_ELEMENTS.
    // Convert to dictionary mode
    DirectHandle<NumberDictionary> new_element_dictionary =
        old_length == 0
            ? isolate->factory()->empty_slow_element_dictionary()
            : array->GetElementsAccessor()->Normalize(isolate, array);
    // Migrate map.
    DirectHandle<Map> new_map =
        Map::Copy(isolate, direct_handle(array->map(), isolate),
                  "SlowCopyForSetLengthImpl");
    new_map->set_is_extensible(false);
    new_map->set_elements_kind(DICTIONARY_ELEMENTS);
    JSObject::MigrateToMap(isolate, array, new_map);
    if (!new_element_dictionary.is_null()) {
      array->set_elements(*new_element_dictionary);
    }
    if (array->elements() !=
        ReadOnlyRoots(isolate).empty_slow_element_dictionary()) {
      DirectHandle<NumberDictionary> dictionary(array->element_dictionary(),
                                                isolate);
      // Make sure we never go back to the fast case
      array->RequireSlowElements(*dictionary);
      JSObject::ApplyAttributesToDictionary(isolate, ReadOnlyRoots(isolate),
                                            dictionary,
                                            PropertyAttributes::SEALED);
    }
    // Set length
    DirectHandle<FixedArrayBase> new_backing_store(array->elements(), isolate);
    return DictionaryElementsAccessor::SetLengthImpl(isolate, array, length,
                                                     new_backing_store);
  }
References v8::internal::JSObject::ApplyAttributesToDictionary(), CHECK, v8::internal::Map::Copy(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::DirectHandle< T >::is_null(), v8::Just(), v8::internal::length, v8::internal::JSObject::MigrateToMap(), v8::internal::SEALED, and v8::internal::Object::ToArrayIndex().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc