v8::internal::compiler::FrameStateDescriptor Class Reference
#include <instruction.h>
Public Member Functions
FrameStateDescriptor (Zone *zone, FrameStateType type, BytecodeOffset bailout_id, OutputFrameStateCombine state_combine, uint16_t parameters_count, uint16_t max_arguments, size_t locals_count, size_t stack_count, MaybeIndirectHandle< SharedFunctionInfo > shared_info, MaybeIndirectHandle< BytecodeArray > bytecode_array, FrameStateDescriptor *outer_state=nullptr, uint32_t wasm_liftoff_frame_size=std::numeric_limits< uint32_t >::max(), uint32_t wasm_function_index=std::numeric_limits< uint32_t >::max())
FrameStateType type () const
BytecodeOffset bailout_id () const
OutputFrameStateCombine state_combine () const
uint16_t parameters_count () const
uint16_t max_arguments () const
size_t locals_count () const
size_t stack_count () const
MaybeIndirectHandle< SharedFunctionInfo > shared_info () const
MaybeIndirectHandle< BytecodeArray > bytecode_array () const
FrameStateDescriptor * outer_state () const
bool HasClosure () const
bool HasContext () const
size_t GetHeight () const
size_t total_conservative_frame_size_in_bytes () const
size_t GetSize () const
size_t GetTotalSize () const
size_t GetFrameCount () const
size_t GetJSFrameCount () const
uint32_t GetWasmFunctionIndex () const
StateValueList * GetStateValueDescriptors ()
Static Public Attributes
static const int kImpossibleValue = 0xdead
Private Attributes
FrameStateType type_
BytecodeOffset bailout_id_
OutputFrameStateCombine frame_state_combine_
const uint16_t parameters_count_
const uint16_t max_arguments_
const size_t locals_count_
const size_t stack_count_
const size_t total_conservative_frame_size_in_bytes_
StateValueList values_
MaybeIndirectHandle< SharedFunctionInfo > const shared_info_
MaybeIndirectHandle< BytecodeArray > const bytecode_array_
FrameStateDescriptor *const outer_state_
uint32_t wasm_function_index_
Detailed Description
Definition at line 1533 of file instruction.h.
Constructor & Destructor Documentation
FrameStateDescriptor()
v8::internal::compiler::FrameStateDescriptor::FrameStateDescriptor (Zone * zone, FrameStateType type, BytecodeOffset bailout_id, OutputFrameStateCombine state_combine, uint16_t parameters_count, uint16_t max_arguments, size_t locals_count, size_t stack_count, MaybeIndirectHandle< SharedFunctionInfo > shared_info, MaybeIndirectHandle< BytecodeArray > bytecode_array, FrameStateDescriptor * outer_state = nullptr, uint32_t wasm_liftoff_frame_size = std::numeric_limits<uint32_t>::max(), uint32_t wasm_function_index = std::numeric_limits<uint32_t>::max())
Definition at line 1218 of file instruction.cc.
    : type_(type),
      bailout_id_(bailout_id),
      frame_state_combine_(state_combine),
      parameters_count_(parameters_count),
      max_arguments_(max_arguments),
      locals_count_(locals_count),
      stack_count_(stack_count),
      total_conservative_frame_size_in_bytes_(
          GetTotalConservativeFrameSizeInBytes(
              type, parameters_count, locals_count, bailout_id,
              wasm_liftoff_frame_size, outer_state)),
      values_(zone),
      shared_info_(shared_info),
      bytecode_array_(bytecode_array),
      outer_state_(outer_state),
      wasm_function_index_(wasm_function_index) {}
Member Function Documentation
bailout_id()
BytecodeOffset v8::internal::compiler::FrameStateDescriptor::bailout_id () const [inline]
Definition at line 1546 of file instruction.h.
{ return bailout_id_; }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation(), and v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
bytecode_array()
MaybeIndirectHandle<BytecodeArray> v8::internal::compiler::FrameStateDescriptor::bytecode_array () const [inline]
Definition at line 1555 of file instruction.h.
                                                            {
    return bytecode_array_;
  }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
GetFrameCount()
size_t v8::internal::compiler::FrameStateDescriptor::GetFrameCount () const
Definition at line 1288 of file instruction.cc.
                                                 {
  size_t count = 0;
  for (const FrameStateDescriptor* iter = this; iter != nullptr;
       iter = iter->outer_state_) {
    ++count;
  }
  return count;
}
References outer_state_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
GetHeight()
size_t v8::internal::compiler::FrameStateDescriptor::GetHeight () const
Definition at line 1243 of file instruction.cc.
                                             {
  switch (type()) {
    case FrameStateType::kUnoptimizedFunction:
      return locals_count(); // The accumulator is *not* included.
    case FrameStateType::kBuiltinContinuation:
#if V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kJSToWasmBuiltinContinuation:
    case FrameStateType::kWasmInlinedIntoJS:
#endif
      // Custom, non-JS calling convention (that does not have a notion of
      // a receiver or context).
      return parameters_count();
    case FrameStateType::kInlinedExtraArguments:
    case FrameStateType::kConstructCreateStub:
    case FrameStateType::kConstructInvokeStub:
    case FrameStateType::kJavaScriptBuiltinContinuation:
    case FrameStateType::kJavaScriptBuiltinContinuationWithCatch:
      // JS linkage. The parameters count
      // - includes the receiver (input 1 in CreateArtificialFrameState, and
      // passed as part of stack parameters to
      // CreateJavaScriptBuiltinContinuationFrameState), and
      // - does *not* include the context.
      return parameters_count();
#if V8_ENABLE_WEBASSEMBLY
    case FrameStateType::kLiftoffFunction:
      return locals_count() + parameters_count();
#endif
  }
  UNREACHABLE();
}
References v8::internal::compiler::kBuiltinContinuation, v8::internal::compiler::kConstructCreateStub, v8::internal::compiler::kConstructInvokeStub, v8::internal::compiler::kInlinedExtraArguments, v8::internal::compiler::kJavaScriptBuiltinContinuation, v8::internal::compiler::kJavaScriptBuiltinContinuationWithCatch, v8::internal::compiler::kUnoptimizedFunction, locals_count(), parameters_count(), type(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
GetJSFrameCount()
size_t v8::internal::compiler::FrameStateDescriptor::GetJSFrameCount () const
Definition at line 1297 of file instruction.cc.
                                                   {
  size_t count = 0;
  for (const FrameStateDescriptor* iter = this; iter != nullptr;
       iter = iter->outer_state_) {
    if (FrameStateFunctionInfo::IsJSFunctionType(iter->type_)) {
      ++count;
    }
  }
  return count;
}
References v8::internal::compiler::FrameStateFunctionInfo::IsJSFunctionType(), and outer_state_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
GetSize()
size_t v8::internal::compiler::FrameStateDescriptor::GetSize () const
Definition at line 1274 of file instruction.cc.
                                           {
  return (HasClosure() ? 1 : 0) + parameters_count() + locals_count() +
         stack_count() + (HasContext() ? 1 : 0);
}
References HasClosure(), HasContext(), locals_count(), parameters_count(), and stack_count().
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and v8::internal::compiler::CodeGenerator::TranslateFrameStateDescriptorOperands().
GetStateValueDescriptors()
StateValueList* v8::internal::compiler::FrameStateDescriptor::GetStateValueDescriptors () [inline]
Definition at line 1603 of file instruction.h.
{ return &values_; }
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and v8::internal::compiler::CodeGenerator::TranslateFrameStateDescriptorOperands().
GetTotalSize()
size_t v8::internal::compiler::FrameStateDescriptor::GetTotalSize () const
Definition at line 1279 of file instruction.cc.
                                                {
  size_t total_size = 0;
  for (const FrameStateDescriptor* iter = this; iter != nullptr;
       iter = iter->outer_state_) {
    total_size += iter->GetSize();
  }
  return total_size;
}
References outer_state_.
Referenced by v8::internal::compiler::CallBuffer::frame_state_value_count().
GetWasmFunctionIndex()
uint32_t v8::internal::compiler::FrameStateDescriptor::GetWasmFunctionIndex () const [inline]
Definition at line 1598 of file instruction.h.
                                        {
    DCHECK(wasm_function_index_ != std::numeric_limits<uint32_t>::max());
    return wasm_function_index_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
HasClosure()
bool v8::internal::compiler::FrameStateDescriptor::HasClosure () const [inline]
Definition at line 1559 of file instruction.h.
                          {
    return
#if V8_ENABLE_WEBASSEMBLY
        type_ != FrameStateType::kLiftoffFunction &&
#endif
        type_ != FrameStateType::kConstructInvokeStub;
  }
References v8::internal::compiler::kConstructInvokeStub.
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and GetSize().
HasContext()
bool v8::internal::compiler::FrameStateDescriptor::HasContext () const [inline]
Definition at line 1566 of file instruction.h.
                          {
    return FrameStateFunctionInfo::IsJSFunctionType(type_) ||
           type_ == FrameStateType::kBuiltinContinuation ||
#if V8_ENABLE_WEBASSEMBLY
           type_ == FrameStateType::kJSToWasmBuiltinContinuation ||
           // TODO(mliedtke): Should we skip the context for the FrameState of
           // inlined wasm functions?
           type_ == FrameStateType::kWasmInlinedIntoJS ||
#endif // V8_ENABLE_WEBASSEMBLY
           type_ == FrameStateType::kConstructCreateStub ||
           type_ == FrameStateType::kConstructInvokeStub;
  }
References v8::internal::compiler::FrameStateFunctionInfo::IsJSFunctionType(), v8::internal::compiler::kBuiltinContinuation, v8::internal::compiler::kConstructCreateStub, and v8::internal::compiler::kConstructInvokeStub.
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and GetSize().
locals_count()
size_t v8::internal::compiler::FrameStateDescriptor::locals_count () const [inline]
Definition at line 1550 of file instruction.h.
{ return locals_count_; }
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), GetHeight(), and GetSize().
max_arguments()
uint16_t v8::internal::compiler::FrameStateDescriptor::max_arguments () const [inline]
Definition at line 1549 of file instruction.h.
{ return max_arguments_; }
outer_state()
FrameStateDescriptor* v8::internal::compiler::FrameStateDescriptor::outer_state () const [inline]
Definition at line 1558 of file instruction.h.
{ return outer_state_; }
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
parameters_count()
uint16_t v8::internal::compiler::FrameStateDescriptor::parameters_count () const [inline]
Definition at line 1548 of file instruction.h.
{ return parameters_count_; }
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), GetHeight(), and GetSize().
shared_info()
MaybeIndirectHandle<SharedFunctionInfo> v8::internal::compiler::FrameStateDescriptor::shared_info () const [inline]
Definition at line 1552 of file instruction.h.
                                                              {
    return shared_info_;
  }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
stack_count()
size_t v8::internal::compiler::FrameStateDescriptor::stack_count () const [inline]
Definition at line 1551 of file instruction.h.
{ return stack_count_; }
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and GetSize().
state_combine()
OutputFrameStateCombine v8::internal::compiler::FrameStateDescriptor::state_combine () const [inline]
Definition at line 1547 of file instruction.h.
{ return frame_state_combine_; }
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), and v8::internal::compiler::CodeGenerator::RecordDeoptInfo().
total_conservative_frame_size_in_bytes()
size_t v8::internal::compiler::FrameStateDescriptor::total_conservative_frame_size_in_bytes () const [inline]
Definition at line 1589 of file instruction.h.
                                                        {
    return total_conservative_frame_size_in_bytes_;
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction.cc}::GetTotalConservativeFrameSizeInBytes().
type()
FrameStateType v8::internal::compiler::FrameStateDescriptor::type () const [inline]
Definition at line 1545 of file instruction.h.
{ return type_; }
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), GetHeight(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
Member Data Documentation
bailout_id_
BytecodeOffset v8::internal::compiler::FrameStateDescriptor::bailout_id_ [private]
Definition at line 1609 of file instruction.h.
bytecode_array_
MaybeIndirectHandle<BytecodeArray> const v8::internal::compiler::FrameStateDescriptor::bytecode_array_ [private]
Definition at line 1618 of file instruction.h.
frame_state_combine_
OutputFrameStateCombine v8::internal::compiler::FrameStateDescriptor::frame_state_combine_ [private]
Definition at line 1610 of file instruction.h.
kImpossibleValue
const int v8::internal::compiler::FrameStateDescriptor::kImpossibleValue = 0xdead [static]
Definition at line 1605 of file instruction.h.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), and v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt().
locals_count_
const size_t v8::internal::compiler::FrameStateDescriptor::locals_count_ [private]
Definition at line 1613 of file instruction.h.
max_arguments_
const uint16_t v8::internal::compiler::FrameStateDescriptor::max_arguments_ [private]
Definition at line 1612 of file instruction.h.
outer_state_
FrameStateDescriptor* const v8::internal::compiler::FrameStateDescriptor::outer_state_ [private]
Definition at line 1619 of file instruction.h.
Referenced by GetFrameCount(), GetJSFrameCount(), and GetTotalSize().
parameters_count_
const uint16_t v8::internal::compiler::FrameStateDescriptor::parameters_count_ [private]
Definition at line 1611 of file instruction.h.
shared_info_
MaybeIndirectHandle<SharedFunctionInfo> const v8::internal::compiler::FrameStateDescriptor::shared_info_ [private]
Definition at line 1617 of file instruction.h.
stack_count_
const size_t v8::internal::compiler::FrameStateDescriptor::stack_count_ [private]
Definition at line 1614 of file instruction.h.
total_conservative_frame_size_in_bytes_
const size_t v8::internal::compiler::FrameStateDescriptor::total_conservative_frame_size_in_bytes_ [private]
Definition at line 1615 of file instruction.h.
type_
FrameStateType v8::internal::compiler::FrameStateDescriptor::type_ [private]
Definition at line 1608 of file instruction.h.
values_
StateValueList v8::internal::compiler::FrameStateDescriptor::values_ [private]
Definition at line 1616 of file instruction.h.
wasm_function_index_
uint32_t v8::internal::compiler::FrameStateDescriptor::wasm_function_index_ [private]
Definition at line 1620 of file instruction.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc