v8_inspector::V8InspectorSessionImpl Class Reference
#include <v8-inspector-session-impl.h>
Classes
class KeepSessionAliveScope
Public Member Functions
~V8InspectorSessionImpl () override
V8InspectorSessionImpl (const V8InspectorSessionImpl &)=delete
V8InspectorSessionImpl & operator= (const V8InspectorSessionImpl &)=delete
V8InspectorImpl * inspector () const
V8ConsoleAgentImpl * consoleAgent ()
V8DebuggerAgentImpl * debuggerAgent ()
V8SchemaAgentImpl * schemaAgent ()
V8ProfilerAgentImpl * profilerAgent ()
V8RuntimeAgentImpl * runtimeAgent ()
V8HeapProfilerAgentImpl * heapProfilerAgent ()
int contextGroupId () const
int sessionId () const
Response findInjectedScript (int contextId, InjectedScript *&)
Response findInjectedScript (RemoteObjectIdBase *, InjectedScript *&)
void reset ()
void discardInjectedScripts ()
void reportAllContexts (V8RuntimeAgentImpl *)
void setCustomObjectFormatterEnabled (bool)
std::unique_ptr< protocol::Runtime::RemoteObject > wrapObject (v8::Local< v8::Context >, v8::Local< v8::Value >, const String16 &groupName, bool generatePreview)
std::unique_ptr< protocol::Runtime::RemoteObject > wrapTable (v8::Local< v8::Context >, v8::Local< v8::Object > table, v8::MaybeLocal< v8::Array > columns)
std::vector< std::unique_ptr< protocol::Schema::Domain > > supportedDomainsImpl ()
Response unwrapObject (const String16 &objectId, v8::Local< v8::Value > *, v8::Local< v8::Context > *, String16 *objectGroup)
void releaseObjectGroup (const String16 &objectGroup)
void dispatchProtocolMessage (StringView message) override
std::vector< uint8_t > state () override
std::vector< std::unique_ptr< protocol::Schema::API::Domain > > supportedDomains () override
void addInspectedObject (std::unique_ptr< V8InspectorSession::Inspectable >) override
void schedulePauseOnNextStatement (StringView breakReason, StringView breakDetails) override
void cancelPauseOnNextStatement () override
void breakProgram (StringView breakReason, StringView breakDetails) override
void setSkipAllPauses (bool) override
void resume (bool terminateOnResume=false) override
void stepOver () override
std::vector< std::unique_ptr< protocol::Debugger::API::SearchMatch > > searchInTextByLines (StringView text, StringView query, bool caseSensitive, bool isRegex) override
void releaseObjectGroup (StringView objectGroup) override
bool unwrapObject (std::unique_ptr< StringBuffer > *, StringView objectId, v8::Local< v8::Value > *, v8::Local< v8::Context > *, std::unique_ptr< StringBuffer > *objectGroup) override
std::unique_ptr< protocol::Runtime::API::RemoteObject > wrapObject (v8::Local< v8::Context >, v8::Local< v8::Value >, StringView groupName, bool generatePreview) override
V8InspectorSession::Inspectable * inspectedObject (unsigned num)
void triggerPreciseCoverageDeltaUpdate (StringView occasion) override
EvaluateResult evaluate (v8::Local< v8::Context > context, StringView expression, bool includeCommandLineAPI=false) override
void stop () override
V8Inspector::ClientTrustLevel clientTrustLevel ()
void setWeakThis (std::weak_ptr< V8InspectorSessionImpl > weakThis)
Static Public Member Functions
static V8InspectorSessionImpl * create (V8InspectorImpl *, int contextGroupId, int sessionId, V8Inspector::Channel *, StringView state, v8_inspector::V8Inspector::ClientTrustLevel, std::shared_ptr< V8DebuggerBarrier >)
Static Public Attributes
static const unsigned kInspectedObjectBufferSize = 5
Private Member Functions
V8InspectorSessionImpl (V8InspectorImpl *, int contextGroupId, int sessionId, V8Inspector::Channel *, StringView state, V8Inspector::ClientTrustLevel, std::shared_ptr< V8DebuggerBarrier >)
protocol::DictionaryValue * agentState (const String16 &name)
void SendProtocolResponse (int callId, std::unique_ptr< protocol::Serializable > message) override
void SendProtocolNotification (std::unique_ptr< protocol::Serializable > message) override
void FallThrough (int callId, v8_crdtp::span< uint8_t > method, v8_crdtp::span< uint8_t > message) override
void FlushProtocolNotifications () override
std::unique_ptr< StringBuffer > serializeForFrontend (std::unique_ptr< protocol::Serializable > message)
Private Attributes
int m_contextGroupId
int m_sessionId
V8InspectorImpl * m_inspector
V8Inspector::Channel * m_channel
bool m_customObjectFormatterEnabled
protocol::UberDispatcher m_dispatcher
std::unique_ptr< protocol::DictionaryValue > m_state
std::unique_ptr< V8RuntimeAgentImpl > m_runtimeAgent
std::unique_ptr< V8DebuggerAgentImpl > m_debuggerAgent
std::unique_ptr< V8HeapProfilerAgentImpl > m_heapProfilerAgent
std::unique_ptr< V8ProfilerAgentImpl > m_profilerAgent
std::unique_ptr< V8ConsoleAgentImpl > m_consoleAgent
std::unique_ptr< V8SchemaAgentImpl > m_schemaAgent
std::vector< std::unique_ptr< V8InspectorSession::Inspectable > > m_inspectedObjects
bool use_binary_protocol_ = false
V8Inspector::ClientTrustLevel m_clientTrustLevel = V8Inspector::kUntrusted
std::weak_ptr< V8InspectorSessionImpl > m_weakThis
Detailed Description
Definition at line 33 of file v8-inspector-session-impl.h.
Constructor & Destructor Documentation
 V8InspectorSessionImpl()
v8_inspector::V8InspectorSessionImpl::~V8InspectorSessionImpl () [override]
Definition at line 160 of file v8-inspector-session-impl.cc.
                                                {
  v8::Isolate::Scope scope(m_inspector->isolate());
  discardInjectedScripts();
  m_consoleAgent->disable();
  m_profilerAgent->disable();
  if (m_heapProfilerAgent) m_heapProfilerAgent->disable();
  m_debuggerAgent->disable();
  m_runtimeAgent->disable();
  m_inspector->disconnect(this);
}
References discardInjectedScripts(), v8_inspector::V8InspectorImpl::disconnect(), v8_inspector::V8InspectorImpl::isolate(), m_consoleAgent, m_debuggerAgent, m_heapProfilerAgent, m_inspector, m_profilerAgent, and m_runtimeAgent.
V8InspectorSessionImpl() [1/2]
v8_inspector::V8InspectorSessionImpl::V8InspectorSessionImpl (const V8InspectorSessionImpl &) [delete]
Referenced by create().
V8InspectorSessionImpl() [2/2]
v8_inspector::V8InspectorSessionImpl::V8InspectorSessionImpl (V8InspectorImpl * inspector, int contextGroupId, int sessionId, V8Inspector::Channel * channel, StringView state, V8Inspector::ClientTrustLevel clientTrustLevel, std::shared_ptr< V8DebuggerBarrier > debuggerBarrier) [private]
Definition at line 103 of file v8-inspector-session-impl.cc.
    : m_contextGroupId(contextGroupId),
      m_sessionId(sessionId),
      m_inspector(inspector),
      m_channel(channel),
      m_customObjectFormatterEnabled(false),
      m_dispatcher(this),
      m_state(ParseState(savedState)),
      m_runtimeAgent(nullptr),
      m_debuggerAgent(nullptr),
      m_heapProfilerAgent(nullptr),
      m_profilerAgent(nullptr),
      m_consoleAgent(nullptr),
      m_schemaAgent(nullptr),
      m_clientTrustLevel(clientTrustLevel) {
  m_state->getBoolean("use_binary_protocol", &use_binary_protocol_);
  m_runtimeAgent.reset(new V8RuntimeAgentImpl(
      this, this, agentState(protocol::Runtime::Metainfo::domainName),
      std::move(debuggerBarrier)));
  protocol::Runtime::Dispatcher::wire(&m_dispatcher, m_runtimeAgent.get());
  m_debuggerAgent.reset(new V8DebuggerAgentImpl(
      this, this, agentState(protocol::Debugger::Metainfo::domainName)));
  protocol::Debugger::Dispatcher::wire(&m_dispatcher, m_debuggerAgent.get());
  m_consoleAgent.reset(new V8ConsoleAgentImpl(
      this, this, agentState(protocol::Console::Metainfo::domainName)));
  protocol::Console::Dispatcher::wire(&m_dispatcher, m_consoleAgent.get());
  m_profilerAgent.reset(new V8ProfilerAgentImpl(
      this, this, agentState(protocol::Profiler::Metainfo::domainName)));
  protocol::Profiler::Dispatcher::wire(&m_dispatcher, m_profilerAgent.get());
  if (m_clientTrustLevel == V8Inspector::kFullyTrusted) {
    m_heapProfilerAgent.reset(new V8HeapProfilerAgentImpl(
        this, this, agentState(protocol::HeapProfiler::Metainfo::domainName)));
    protocol::HeapProfiler::Dispatcher::wire(&m_dispatcher,
                                             m_heapProfilerAgent.get());
    m_schemaAgent.reset(new V8SchemaAgentImpl(
        this, this, agentState(protocol::Schema::Metainfo::domainName)));
    protocol::Schema::Dispatcher::wire(&m_dispatcher, m_schemaAgent.get());
  }
  if (savedState.length()) {
    m_runtimeAgent->restore();
    m_debuggerAgent->restore();
    if (m_heapProfilerAgent) m_heapProfilerAgent->restore();
    m_profilerAgent->restore();
    m_consoleAgent->restore();
  }
}
References agentState(), v8_inspector::V8Inspector::kFullyTrusted, v8_inspector::StringView::length(), m_clientTrustLevel, m_consoleAgent, m_debuggerAgent, m_dispatcher, m_heapProfilerAgent, m_profilerAgent, m_runtimeAgent, m_schemaAgent, m_state, and use_binary_protocol_.
Member Function Documentation
addInspectedObject()
void v8_inspector::V8InspectorSessionImpl::addInspectedObject (std::unique_ptr< V8InspectorSession::Inspectable > inspectable) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 440 of file v8-inspector-session-impl.cc.
                                                              {
  m_inspectedObjects.insert(m_inspectedObjects.begin(), std::move(inspectable));
  if (m_inspectedObjects.size() > kInspectedObjectBufferSize)
    m_inspectedObjects.resize(kInspectedObjectBufferSize);
}
References kInspectedObjectBufferSize, and m_inspectedObjects.
Referenced by v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject().
agentState()
protocol::DictionaryValue * v8_inspector::V8InspectorSessionImpl::agentState (const String16 & name) [private]
Definition at line 171 of file v8-inspector-session-impl.cc.
                          {
  protocol::DictionaryValue* state = m_state->getObject(name);
  if (!state) {
    std::unique_ptr<protocol::DictionaryValue> newState =
        protocol::DictionaryValue::create();
    state = newState.get();
    m_state->setObject(name, std::move(newState));
  }
  return state;
}
References m_state, name, and state().
Referenced by V8InspectorSessionImpl().
breakProgram()
void v8_inspector::V8InspectorSessionImpl::breakProgram (StringView breakReason, StringView breakDetails) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 467 of file v8-inspector-session-impl.cc.
                                                                   {
  std::vector<uint8_t> cbor;
  ConvertToCBOR(breakDetails, &cbor);
  m_debuggerAgent->breakProgram(
      toString16(breakReason),
      protocol::DictionaryValue::cast(
          protocol::Value::parseBinary(cbor.data(), cbor.size())));
}
References v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), m_debuggerAgent, and v8_inspector::toString16().
cancelPauseOnNextStatement()
void v8_inspector::V8InspectorSessionImpl::cancelPauseOnNextStatement () [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 463 of file v8-inspector-session-impl.cc.
                                                        {
  m_debuggerAgent->cancelPauseOnNextStatement();
}
References m_debuggerAgent.
clientTrustLevel()
V8Inspector::ClientTrustLevel v8_inspector::V8InspectorSessionImpl::clientTrustLevel () [inline]
Definition at line 107 of file v8-inspector-session-impl.h.
                                                 {
    return m_clientTrustLevel;
  }
References m_clientTrustLevel.
Referenced by create(), and v8_inspector::InjectedScript::Scope::installCommandLineAPI().
consoleAgent()
V8ConsoleAgentImpl* v8_inspector::V8InspectorSessionImpl::consoleAgent () [inline]
Definition at line 46 of file v8-inspector-session-impl.h.
{ return m_consoleAgent.get(); }
References m_consoleAgent.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage().
contextGroupId()
int v8_inspector::V8InspectorSessionImpl::contextGroupId () const [inline]
Definition at line 54 of file v8-inspector-session-impl.h.
{ return m_contextGroupId; }
References m_contextGroupId.
Referenced by v8_inspector::V8RuntimeAgentImpl::addBinding(), v8_inspector::V8DebuggerAgentImpl::breakProgram(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::V8DebuggerAgentImpl::cancelPauseOnNextStatement(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8DebuggerAgentImpl::continueToLocation(), create(), v8_inspector::V8RuntimeAgentImpl::disable(), v8_inspector::V8RuntimeAgentImpl::discardConsoleEntries(), v8_inspector::V8InspectorImpl::disconnect(), v8_inspector::V8RuntimeAgentImpl::enable(), v8_inspector::V8DebuggerAgentImpl::enable(), v8_inspector::V8DebuggerAgentImpl::enableImpl(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::getStackTrace(), v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames(), v8_inspector::V8DebuggerAgentImpl::isPaused(), v8_inspector::V8DebuggerAgentImpl::pause(), v8_inspector::V8ConsoleAgentImpl::reportAllMessages(), v8_inspector::V8ConsoleAgentImpl::reportMessage(), v8_inspector::V8RuntimeAgentImpl::reportMessage(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::V8RuntimeAgentImpl::reset(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), v8_inspector::V8DebuggerAgentImpl::restore(), v8_inspector::V8RuntimeAgentImpl::restore(), v8_inspector::V8DebuggerAgentImpl::resume(), v8_inspector::V8RuntimeAgentImpl::runIfWaitingForDebugger(), v8_inspector::V8RuntimeAgentImpl::runScript(), v8_inspector::V8DebuggerAgentImpl::schedulePauseOnNextStatement(), v8_inspector::V8DebuggerAgentImpl::setBreakpointsActive(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), v8_inspector::V8DebuggerAgentImpl::stepInto(), v8_inspector::V8DebuggerAgentImpl::stepOut(), v8_inspector::V8DebuggerAgentImpl::stepOver(), v8_inspector::V8RuntimeAgentImpl::terminateExecution(), v8_inspector::V8ConsoleMessage::wrapArguments(), and v8_inspector::V8ConsoleMessage::wrapException().
create()
V8InspectorSessionImpl * v8_inspector::V8InspectorSessionImpl::create (V8InspectorImpl * inspector, int contextGroupId, int sessionId, V8Inspector::Channel * channel, StringView state, v8_inspector::V8Inspector::ClientTrustLevel clientTrustLevel, std::shared_ptr< V8DebuggerBarrier > debuggerBarrier) [static]
Definition at line 93 of file v8-inspector-session-impl.cc.
                                                      {
  return new V8InspectorSessionImpl(inspector, contextGroupId, sessionId,
                                    channel, state, clientTrustLevel,
                                    std::move(debuggerBarrier));
}
References clientTrustLevel(), contextGroupId(), inspector(), sessionId(), state(), and V8InspectorSessionImpl().
Referenced by v8_inspector::V8InspectorImpl::connectImpl().
debuggerAgent()
V8DebuggerAgentImpl* v8_inspector::V8InspectorSessionImpl::debuggerAgent () [inline]
Definition at line 47 of file v8-inspector-session-impl.h.
{ return m_debuggerAgent.get(); }
References m_debuggerAgent.
Referenced by v8_inspector::V8Debugger::BreakOnInstrumentation(), v8_inspector::V8Debugger::disable(), v8_inspector::V8RuntimeAgentImpl::disable(), v8_inspector::V8Debugger::handleProgramBreak(), v8_inspector::V8Debugger::quitMessageLoopIfAgentsFinishedInstrumentation(), and v8_inspector::setFunctionBreakpoint().
discardInjectedScripts()
void v8_inspector::V8InspectorSessionImpl::discardInjectedScripts ()
Definition at line 229 of file v8-inspector-session-impl.cc.
                                                    {
  m_inspectedObjects.clear();
  int sessionId = m_sessionId;
  m_inspector->forEachContext(m_contextGroupId,
                              [&sessionId](InspectedContext* context) {
                                context->discardInjectedScript(sessionId);
                              });
}
References v8_inspector::InspectedContext::discardInjectedScript(), v8_inspector::V8InspectorImpl::forEachContext(), m_contextGroupId, m_inspectedObjects, m_inspector, m_sessionId, and sessionId().
Referenced by reset(), and ~V8InspectorSessionImpl().
dispatchProtocolMessage()
void v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage (StringView message) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 361 of file v8-inspector-session-impl.cc.
                                                                       {
  KeepSessionAliveScope keepAlive(*this);
  using v8_crdtp::span;
  using v8_crdtp::SpanFrom;
  span<uint8_t> cbor;
  std::vector<uint8_t> converted_cbor;
  if (IsCBORMessage(message)) {
    use_binary_protocol_ = true;
    m_state->setBoolean("use_binary_protocol", true);
    cbor = span<uint8_t>(message.characters8(), message.length());
  } else {
    // We're ignoring the return value of the conversion function
    // intentionally. It means the |parsed_message| below will be nullptr.
    auto status = ConvertToCBOR(message, &converted_cbor);
    if (!status.ok()) {
      m_channel->sendNotification(
          serializeForFrontend(v8_crdtp::CreateErrorNotification(
              v8_crdtp::DispatchResponse::ParseError(status.ToASCIIString()))));
      return;
    }
    cbor = SpanFrom(converted_cbor);
  }
  v8_crdtp::Dispatchable dispatchable(cbor);
  if (!dispatchable.ok()) {
    if (!dispatchable.HasCallId()) {
      m_channel->sendNotification(serializeForFrontend(
          v8_crdtp::CreateErrorNotification(dispatchable.DispatchError())));
    } else {
      m_channel->sendResponse(
          dispatchable.CallId(),
          serializeForFrontend(v8_crdtp::CreateErrorResponse(
              dispatchable.CallId(), dispatchable.DispatchError())));
    }
    return;
  }
  m_dispatcher.Dispatch(dispatchable).Run();
}
References v8_inspector::StringView::characters8(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::IsCBORMessage(), v8_inspector::StringView::length(), m_channel, m_dispatcher, m_state, v8_inspector::V8Inspector::Channel::sendNotification(), v8_inspector::V8Inspector::Channel::sendResponse(), serializeForFrontend(), v8::internal::status, and use_binary_protocol_.
evaluate()
V8InspectorSession::EvaluateResult v8_inspector::V8InspectorSessionImpl::evaluate (v8::Local< v8::Context > context, StringView expression, bool includeCommandLineAPI = false) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 505 of file v8-inspector-session-impl.cc.
                                {
  v8::EscapableHandleScope handleScope(m_inspector->isolate());
  InjectedScript::ContextScope scope(this,
                                     InspectedContext::contextId(context));
  if (!scope.initialize().IsSuccess()) {
    return {EvaluateResult::ResultType::kNotRun, v8::Local<v8::Value>()};
  }
  // Temporarily allow eval.
  scope.allowCodeGenerationFromStrings();
  scope.setTryCatchVerbose();
  if (includeCommandLineAPI) {
    scope.installCommandLineAPI();
  }
  v8::MaybeLocal<v8::Value> maybeResultValue;
  {
    v8::MicrotasksScope microtasksScope(scope.context(),
                                        v8::MicrotasksScope::kRunMicrotasks);
    const v8::Local<v8::String> source =
        toV8String(m_inspector->isolate(), expression);
    maybeResultValue = v8::debug::EvaluateGlobal(
        m_inspector->isolate(), source, v8::debug::EvaluateGlobalMode::kDefault,
        /*repl_mode=*/false);
  }
  if (scope.tryCatch().HasCaught()) {
    return {EvaluateResult::ResultType::kException,
            handleScope.Escape(scope.tryCatch().Exception())};
  }
  v8::Local<v8::Value> result;
  CHECK(maybeResultValue.ToLocal(&result));
  return {EvaluateResult::ResultType::kSuccess, handleScope.Escape(result)};
}
References v8_inspector::InjectedScript::Scope::allowCodeGenerationFromStrings(), CHECK, v8_inspector::InjectedScript::Scope::context(), v8_inspector::InspectedContext::contextId(), v8::EscapableHandleScope::Escape(), v8::debug::EvaluateGlobal(), v8::TryCatch::Exception(), v8::TryCatch::HasCaught(), v8_inspector::InjectedScript::Scope::initialize(), v8_inspector::InjectedScript::Scope::installCommandLineAPI(), v8_inspector::V8InspectorImpl::isolate(), v8::debug::kDefault, v8::debug::kException, v8::MicrotasksScope::kRunMicrotasks, v8::internal::detail::kSuccess, m_inspector, v8::base::internal::result, v8_inspector::InjectedScript::Scope::setTryCatchVerbose(), v8::MaybeLocal< T >::ToLocal(), v8_inspector::toV8String(), and v8_inspector::InjectedScript::Scope::tryCatch().
FallThrough()
void v8_inspector::V8InspectorSessionImpl::FallThrough (int callId, v8_crdtp::span< uint8_t > method, v8_crdtp::span< uint8_t > message) [override], [private]
Definition at line 212 of file v8-inspector-session-impl.cc.
                                                                        {
  // There's no other layer to handle the command.
  UNREACHABLE();
}
References UNREACHABLE.
findInjectedScript() [1/2]
Response v8_inspector::V8InspectorSessionImpl::findInjectedScript (int contextId, InjectedScript *& injectedScript)
Definition at line 238 of file v8-inspector-session-impl.cc.
                                                    {
  injectedScript = nullptr;
  InspectedContext* context =
      m_inspector->getContext(m_contextGroupId, contextId);
  if (!context)
    return Response::ServerError("Cannot find context with specified id");
  injectedScript = context->getInjectedScript(m_sessionId);
  if (!injectedScript) {
    injectedScript = context->createInjectedScript(m_sessionId);
    if (m_customObjectFormatterEnabled)
      injectedScript->setCustomObjectFormatterEnabled(true);
  }
  return Response::Success();
}
References v8_inspector::InspectedContext::createInjectedScript(), v8_inspector::V8InspectorImpl::getContext(), v8_inspector::InspectedContext::getInjectedScript(), m_contextGroupId, m_customObjectFormatterEnabled, m_inspector, m_sessionId, and v8_inspector::InjectedScript::setCustomObjectFormatterEnabled().
Referenced by v8_inspector::V8DebuggerAgentImpl::currentCallFrames(), v8_inspector::V8DebuggerAgentImpl::didPause(), findInjectedScript(), v8_inspector::InjectedScript::ContextScope::findInjectedScript(), v8_inspector::InjectedScript::ObjectScope::findInjectedScript(), v8_inspector::InjectedScript::CallFrameScope::findInjectedScript(), unwrapObject(), wrapObject(), and wrapTable().
findInjectedScript() [2/2]
Response v8_inspector::V8InspectorSessionImpl::findInjectedScript (RemoteObjectIdBase * objectId, InjectedScript *& injectedScript)
Definition at line 254 of file v8-inspector-session-impl.cc.
                                                                   {
  if (objectId->isolateId() != m_inspector->isolateId())
    return Response::ServerError("Cannot find context with specified id");
  return findInjectedScript(objectId->contextId(), injectedScript);
}
References v8_inspector::RemoteObjectIdBase::contextId(), findInjectedScript(), v8_inspector::RemoteObjectIdBase::isolateId(), v8_inspector::V8InspectorImpl::isolateId(), and m_inspector.
FlushProtocolNotifications()
void v8_inspector::V8InspectorSessionImpl::FlushProtocolNotifications () [override], [private]
Definition at line 219 of file v8-inspector-session-impl.cc.
                                                        {
  m_channel->flushProtocolNotifications();
}
References v8_inspector::V8Inspector::Channel::flushProtocolNotifications(), and m_channel.
heapProfilerAgent()
V8HeapProfilerAgentImpl* v8_inspector::V8InspectorSessionImpl::heapProfilerAgent () [inline]
Definition at line 51 of file v8-inspector-session-impl.h.
                                               {
    return m_heapProfilerAgent.get();
  }
References m_heapProfilerAgent.
Referenced by v8_inspector::V8Debugger::handleProgramBreak().
inspectedObject()
V8InspectorSession::Inspectable * v8_inspector::V8InspectorSessionImpl::inspectedObject (unsigned num)
Definition at line 447 of file v8-inspector-session-impl.cc.
                  {
  if (num >= m_inspectedObjects.size()) return nullptr;
  return m_inspectedObjects[num].get();
}
References m_inspectedObjects.
inspector()
V8InspectorImpl* v8_inspector::V8InspectorSessionImpl::inspector () const [inline]
Definition at line 45 of file v8-inspector-session-impl.h.
{ return m_inspector; }
References m_inspector.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8ProfilerAgentImpl::consoleProfile(), v8_inspector::V8ProfilerAgentImpl::consoleProfileEnd(), create(), v8_inspector::V8ProfilerAgentImpl::getBestEffortCoverage(), v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), v8_inspector::V8ConsoleAgentImpl::reportAllMessages(), v8_inspector::V8ConsoleAgentImpl::reportMessage(), v8_inspector::V8ConsoleMessage::reportToFrontend(), v8_inspector::V8HeapProfilerAgentImpl::requestHeapStatsUpdate(), v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal(), v8_inspector::V8ProfilerAgentImpl::stopProfiling(), v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjectsInternal(), v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshot(), v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage(), v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate(), v8_inspector::V8ConsoleMessage::wrapArguments(), and v8_inspector::V8ConsoleMessage::wrapException().
operator=()
V8InspectorSessionImpl& v8_inspector::V8InspectorSessionImpl::operator= (const V8InspectorSessionImpl &) [delete]
profilerAgent()
V8ProfilerAgentImpl* v8_inspector::V8InspectorSessionImpl::profilerAgent () [inline]
Definition at line 49 of file v8-inspector-session-impl.h.
{ return m_profilerAgent.get(); }
References m_profilerAgent.
Referenced by v8_inspector::V8Console::Profile(), and v8_inspector::V8Console::ProfileEnd().
releaseObjectGroup() [1/2]
void v8_inspector::V8InspectorSessionImpl::releaseObjectGroup (const String16 & objectGroup)
Definition at line 265 of file v8-inspector-session-impl.cc.
                                                                           {
  int sessionId = m_sessionId;
  m_inspector->forEachContext(
      m_contextGroupId, [&objectGroup, &sessionId](InspectedContext* context) {
        InjectedScript* injectedScript = context->getInjectedScript(sessionId);
        if (injectedScript) injectedScript->releaseObjectGroup(objectGroup);
      });
}
References v8_inspector::V8InspectorImpl::forEachContext(), v8_inspector::InspectedContext::getInjectedScript(), m_contextGroupId, m_inspector, m_sessionId, v8_inspector::InjectedScript::releaseObjectGroup(), and sessionId().
Referenced by v8_inspector::V8ConsoleMessageStorage::clear(), v8_inspector::V8RuntimeAgentImpl::releaseObjectGroup(), releaseObjectGroup(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), v8_inspector::V8DebuggerAgentImpl::resume(), v8_inspector::V8DebuggerAgentImpl::setScriptSource(), v8_inspector::V8DebuggerAgentImpl::stepInto(), v8_inspector::V8DebuggerAgentImpl::stepOut(), and v8_inspector::V8DebuggerAgentImpl::stepOver().
releaseObjectGroup() [2/2]
void v8_inspector::V8InspectorSessionImpl::releaseObjectGroup (StringView objectGroup) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 261 of file v8-inspector-session-impl.cc.
                                                                      {
  releaseObjectGroup(toString16(objectGroup));
}
References releaseObjectGroup(), and v8_inspector::toString16().
reportAllContexts()
void v8_inspector::V8InspectorSessionImpl::reportAllContexts (V8RuntimeAgentImpl * agent)
Definition at line 354 of file v8-inspector-session-impl.cc.
                                                                        {
  m_inspector->forEachContext(m_contextGroupId,
                              [&agent](InspectedContext* context) {
                                agent->reportExecutionContextCreated(context);
                              });
}
References v8_inspector::V8InspectorImpl::forEachContext(), m_contextGroupId, m_inspector, and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated().
Referenced by v8_inspector::V8RuntimeAgentImpl::enable().
reset()
void v8_inspector::V8InspectorSessionImpl::reset ()
Definition at line 223 of file v8-inspector-session-impl.cc.
                                   {
  m_debuggerAgent->reset();
  m_runtimeAgent->reset();
  discardInjectedScripts();
}
References discardInjectedScripts(), m_debuggerAgent, and m_runtimeAgent.
Referenced by v8_inspector::InjectedScript::Scope::installCommandLineAPI(), and v8_inspector::V8InspectorImpl::resetContextGroup().
resume()
void v8_inspector::V8InspectorSessionImpl::resume (bool terminateOnResume = false) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 481 of file v8-inspector-session-impl.cc.
                                                          {
  m_debuggerAgent->resume(terminateOnResume);
}
References m_debuggerAgent.
runtimeAgent()
V8RuntimeAgentImpl* v8_inspector::V8InspectorSessionImpl::runtimeAgent () [inline]
Definition at line 50 of file v8-inspector-session-impl.h.
{ return m_runtimeAgent.get(); }
References m_runtimeAgent.
Referenced by v8_inspector::V8ConsoleMessageStorage::addMessage(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::V8Debugger::captureStackTrace(), v8_inspector::V8InspectorImpl::contextCollected(), and v8_inspector::V8DebuggerAgentImpl::setAsyncCallStackDepth().
schedulePauseOnNextStatement()
void v8_inspector::V8InspectorSessionImpl::schedulePauseOnNextStatement (StringView breakReason, StringView breakDetails) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 453 of file v8-inspector-session-impl.cc.
                                                     {
  std::vector<uint8_t> cbor;
  ConvertToCBOR(breakDetails, &cbor);
  m_debuggerAgent->schedulePauseOnNextStatement(
      toString16(breakReason),
      protocol::DictionaryValue::cast(
          protocol::Value::parseBinary(cbor.data(), cbor.size())));
}
References v8_inspector::anonymous_namespace{v8-inspector-session-impl.cc}::ConvertToCBOR(), m_debuggerAgent, and v8_inspector::toString16().
schemaAgent()
V8SchemaAgentImpl* v8_inspector::V8InspectorSessionImpl::schemaAgent () [inline]
Definition at line 48 of file v8-inspector-session-impl.h.
{ return m_schemaAgent.get(); }
References m_schemaAgent.
searchInTextByLines()
std::vector< std::unique_ptr< protocol::Debugger::API::SearchMatch > > v8_inspector::V8InspectorSessionImpl::searchInTextByLines (StringView text, StringView query, bool caseSensitive, bool isRegex) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 488 of file v8-inspector-session-impl.cc.
                                                                              {
  // TODO(dgozman): search may operate on StringView and avoid copying |text|.
  std::vector<std::unique_ptr<protocol::Debugger::SearchMatch>> matches =
      searchInTextByLinesImpl(this, toString16(text), toString16(query),
                              caseSensitive, isRegex);
  std::vector<std::unique_ptr<protocol::Debugger::API::SearchMatch>> result;
  for (size_t i = 0; i < matches.size(); ++i)
    result.push_back(std::move(matches[i]));
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::internal::result, v8_inspector::searchInTextByLinesImpl(), and v8_inspector::toString16().
SendProtocolNotification()
void v8_inspector::V8InspectorSessionImpl::SendProtocolNotification (std::unique_ptr< protocol::Serializable > message) [override], [private]
Definition at line 207 of file v8-inspector-session-impl.cc.
                                                 {
  m_channel->sendNotification(serializeForFrontend(std::move(message)));
}
References m_channel, v8_inspector::V8Inspector::Channel::sendNotification(), and serializeForFrontend().
SendProtocolResponse()
void v8_inspector::V8InspectorSessionImpl::SendProtocolResponse (int callId, std::unique_ptr< protocol::Serializable > message) [override], [private]
Definition at line 202 of file v8-inspector-session-impl.cc.
                                                             {
  m_channel->sendResponse(callId, serializeForFrontend(std::move(message)));
}
References m_channel, v8_inspector::V8Inspector::Channel::sendResponse(), and serializeForFrontend().
serializeForFrontend()
std::unique_ptr< StringBuffer > v8_inspector::V8InspectorSessionImpl::serializeForFrontend (std::unique_ptr< protocol::Serializable > message) [private]
Definition at line 183 of file v8-inspector-session-impl.cc.
                                                 {
  std::vector<uint8_t> cbor = message->Serialize();
  DCHECK(CheckCBORMessage(SpanFrom(cbor)).ok());
  if (use_binary_protocol_) return StringBufferFrom(std::move(cbor));
  std::vector<uint8_t> json;
  Status status = ConvertCBORToJSON(SpanFrom(cbor), &json);
  DCHECK(status.ok());
  USE(status);
  // TODO(johannes): It should be OK to make a StringBuffer from |json|
  // directly, since it's 7 Bit US-ASCII with anything else escaped.
  // However it appears that the Node.js tests (or perhaps even production)
  // assume that the StringBuffer is 16 Bit. It probably accesses
  // characters16() somehwere without checking is8Bit. Until it's fixed
  // we take a detour via String16 which makes the StringBuffer 16 bit.
  String16 string16(reinterpret_cast<const char*>(json.data()), json.size());
  return StringBufferFrom(std::move(string16));
}
References DCHECK, v8::internal::status, v8_inspector::StringBufferFrom(), USE, and use_binary_protocol_.
Referenced by dispatchProtocolMessage(), SendProtocolNotification(), and SendProtocolResponse().
sessionId()
int v8_inspector::V8InspectorSessionImpl::sessionId () const [inline]
Definition at line 55 of file v8-inspector-session-impl.h.
{ return m_sessionId; }
References m_sessionId.
Referenced by v8_inspector::V8DebuggerAgentImpl::breakProgram(), create(), discardInjectedScripts(), v8_inspector::V8InspectorImpl::disconnect(), releaseObjectGroup(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed(), v8_inspector::V8RuntimeAgentImpl::reset(), and setCustomObjectFormatterEnabled().
setCustomObjectFormatterEnabled()
void v8_inspector::V8InspectorSessionImpl::setCustomObjectFormatterEnabled (bool enabled)
Definition at line 343 of file v8-inspector-session-impl.cc.
                                                                         {
  m_customObjectFormatterEnabled = enabled;
  int sessionId = m_sessionId;
  m_inspector->forEachContext(
      m_contextGroupId, [&enabled, &sessionId](InspectedContext* context) {
        InjectedScript* injectedScript = context->getInjectedScript(sessionId);
        if (injectedScript)
          injectedScript->setCustomObjectFormatterEnabled(enabled);
      });
}
References v8_inspector::V8InspectorImpl::forEachContext(), v8_inspector::InspectedContext::getInjectedScript(), m_contextGroupId, m_customObjectFormatterEnabled, m_inspector, m_sessionId, sessionId(), and v8_inspector::InjectedScript::setCustomObjectFormatterEnabled().
Referenced by v8_inspector::V8RuntimeAgentImpl::disable(), v8_inspector::V8RuntimeAgentImpl::restore(), and v8_inspector::V8RuntimeAgentImpl::setCustomObjectFormatterEnabled().
setSkipAllPauses()
void v8_inspector::V8InspectorSessionImpl::setSkipAllPauses (bool skip) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 477 of file v8-inspector-session-impl.cc.
                                                       {
  m_debuggerAgent->setSkipAllPauses(skip);
}
References m_debuggerAgent.
setWeakThis()
void v8_inspector::V8InspectorSessionImpl::setWeakThis (std::weak_ptr< V8InspectorSessionImpl > weakThis) [inline]
Definition at line 111 of file v8-inspector-session-impl.h.
                                                                 {
    m_weakThis = std::move(weakThis);
  }
References m_weakThis.
state()
std::vector< uint8_t > v8_inspector::V8InspectorSessionImpl::state () [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 400 of file v8-inspector-session-impl.cc.
                                                 {
  return m_state->Serialize();
}
References m_state.
Referenced by agentState(), and create().
stepOver()
void v8_inspector::V8InspectorSessionImpl::stepOver () [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 485 of file v8-inspector-session-impl.cc.
{ m_debuggerAgent->stepOver({}); }
References m_debuggerAgent.
stop()
void v8_inspector::V8InspectorSessionImpl::stop () [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 541 of file v8-inspector-session-impl.cc.
{ m_debuggerAgent->stop(); }
References m_debuggerAgent.
supportedDomains()
std::vector< std::unique_ptr< protocol::Schema::API::Domain > > v8_inspector::V8InspectorSessionImpl::supportedDomains () [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 405 of file v8-inspector-session-impl.cc.
                                         {
  std::vector<std::unique_ptr<protocol::Schema::Domain>> domains =
      supportedDomainsImpl();
  std::vector<std::unique_ptr<protocol::Schema::API::Domain>> result;
  for (size_t i = 0; i < domains.size(); ++i)
    result.push_back(std::move(domains[i]));
  return result;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::internal::result, and supportedDomainsImpl().
supportedDomainsImpl()
std::vector< std::unique_ptr< protocol::Schema::Domain > > v8_inspector::V8InspectorSessionImpl::supportedDomainsImpl ()
Definition at line 415 of file v8-inspector-session-impl.cc.
                                             {
  std::vector<std::unique_ptr<protocol::Schema::Domain>> result;
  result.push_back(protocol::Schema::Domain::create()
                       .setName(protocol::Runtime::Metainfo::domainName)
                       .setVersion(protocol::Runtime::Metainfo::version)
                       .build());
  result.push_back(protocol::Schema::Domain::create()
                       .setName(protocol::Debugger::Metainfo::domainName)
                       .setVersion(protocol::Debugger::Metainfo::version)
                       .build());
  result.push_back(protocol::Schema::Domain::create()
                       .setName(protocol::Profiler::Metainfo::domainName)
                       .setVersion(protocol::Profiler::Metainfo::version)
                       .build());
  result.push_back(protocol::Schema::Domain::create()
                       .setName(protocol::HeapProfiler::Metainfo::domainName)
                       .setVersion(protocol::HeapProfiler::Metainfo::version)
                       .build());
  result.push_back(protocol::Schema::Domain::create()
                       .setName(protocol::Schema::Metainfo::domainName)
                       .setVersion(protocol::Schema::Metainfo::version)
                       .build());
  return result;
}
References v8::base::internal::result.
Referenced by v8_inspector::V8SchemaAgentImpl::getDomains(), and supportedDomains().
triggerPreciseCoverageDeltaUpdate()
void v8_inspector::V8InspectorSessionImpl::triggerPreciseCoverageDeltaUpdate (StringView occasion) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 500 of file v8-inspector-session-impl.cc.
                         {
  m_profilerAgent->triggerPreciseCoverageDeltaUpdate(toString16(occasion));
}
References m_profilerAgent, and v8_inspector::toString16().
unwrapObject() [1/2]
Response v8_inspector::V8InspectorSessionImpl::unwrapObject (const String16 & objectId, v8::Local< v8::Value > * object, v8::Local< v8::Context > * context, String16 * objectGroup)
Definition at line 293 of file v8-inspector-session-impl.cc.
                                                                     {
  std::unique_ptr<RemoteObjectId> remoteId;
  Response response = RemoteObjectId::parse(objectId, &remoteId);
  if (!response.IsSuccess()) return response;
  InjectedScript* injectedScript = nullptr;
  response = findInjectedScript(remoteId.get(), injectedScript);
  if (!response.IsSuccess()) return response;
  response = injectedScript->findObject(*remoteId, object);
  if (!response.IsSuccess()) return response;
  *context = injectedScript->context()->context();
  if (objectGroup) *objectGroup = injectedScript->objectGroupName(*remoteId);
  return Response::Success();
}
References v8_inspector::InjectedScript::context(), v8_inspector::InspectedContext::context(), findInjectedScript(), v8_inspector::InjectedScript::findObject(), v8_inspector::InjectedScript::objectGroupName(), and v8_inspector::RemoteObjectId::parse().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::getHeapObjectId(), and unwrapObject().
unwrapObject() [2/2]
bool v8_inspector::V8InspectorSessionImpl::unwrapObject (std::unique_ptr< StringBuffer > * error, StringView objectId, v8::Local< v8::Value > * object, v8::Local< v8::Context > * context, std::unique_ptr< StringBuffer > * objectGroup) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 274 of file v8-inspector-session-impl.cc.
                                              {
  String16 objectGroupString;
  Response response = unwrapObject(toString16(objectId), object, context,
                                   objectGroup ? &objectGroupString : nullptr);
  if (response.IsError()) {
    if (error) {
      const std::string& msg = response.Message();
      *error = StringBufferFrom(String16::fromUTF8(msg.data(), msg.size()));
    }
    return false;
  }
  if (objectGroup)
    *objectGroup = StringBufferFrom(std::move(objectGroupString));
  return true;
}
References v8_inspector::String16::fromUTF8(), v8::internal::string, v8_inspector::StringBufferFrom(), v8_inspector::toString16(), and unwrapObject().
wrapObject() [1/2]
std::unique_ptr< protocol::Runtime::RemoteObject > v8_inspector::V8InspectorSessionImpl::wrapObject (v8::Local< v8::Context > context, v8::Local< v8::Value > value, const String16 & groupName, bool generatePreview)
Definition at line 318 of file v8-inspector-session-impl.cc.
                                                         {
  InjectedScript* injectedScript = nullptr;
  findInjectedScript(InspectedContext::contextId(context), injectedScript);
  if (!injectedScript) return nullptr;
  std::unique_ptr<protocol::Runtime::RemoteObject> result;
  injectedScript->wrapObject(value, groupName,
                             generatePreview ? WrapOptions({WrapMode::kPreview})
                                             : WrapOptions({WrapMode::kIdOnly}),
                             &result);
  return result;
}
References v8_inspector::InspectedContext::contextId(), findInjectedScript(), v8_inspector::kIdOnly, v8_inspector::kPreview, v8::base::internal::result, v8::internal::value, and v8_inspector::InjectedScript::wrapObject().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), v8_inspector::V8ConsoleMessage::wrapArguments(), v8_inspector::V8ConsoleMessage::wrapException(), and wrapObject().
wrapObject() [2/2]
std::unique_ptr< protocol::Runtime::API::RemoteObject > v8_inspector::V8InspectorSessionImpl::wrapObject (v8::Local< v8::Context > context, v8::Local< v8::Value > value, StringView groupName, bool generatePreview) [override], [virtual]
Implements v8_inspector::V8InspectorSession.
Definition at line 311 of file v8-inspector-session-impl.cc.
                                                                               {
  return wrapObject(context, value, toString16(groupName), generatePreview);
}
References v8_inspector::toString16(), v8::internal::value, and wrapObject().
wrapTable()
std::unique_ptr< protocol::Runtime::RemoteObject > v8_inspector::V8InspectorSessionImpl::wrapTable (v8::Local< v8::Context > context, v8::Local< v8::Object > table, v8::MaybeLocal< v8::Array > columns)
Definition at line 334 of file v8-inspector-session-impl.cc.
                                                                 {
  InjectedScript* injectedScript = nullptr;
  findInjectedScript(InspectedContext::contextId(context), injectedScript);
  if (!injectedScript) return nullptr;
  return injectedScript->wrapTable(table, columns);
}
References v8_inspector::InspectedContext::contextId(), findInjectedScript(), and v8_inspector::InjectedScript::wrapTable().
Referenced by v8_inspector::V8ConsoleMessage::wrapArguments().
Member Data Documentation
kInspectedObjectBufferSize
const unsigned v8_inspector::V8InspectorSessionImpl::kInspectedObjectBufferSize = 5 [static]
Definition at line 100 of file v8-inspector-session-impl.h.
Referenced by addInspectedObject(), and v8_inspector::V8Console::inspectedObject().
m_channel
V8Inspector::Channel* v8_inspector::V8InspectorSessionImpl::m_channel [private]
Definition at line 136 of file v8-inspector-session-impl.h.
Referenced by dispatchProtocolMessage(), FlushProtocolNotifications(), SendProtocolNotification(), and SendProtocolResponse().
m_clientTrustLevel
V8Inspector::ClientTrustLevel v8_inspector::V8InspectorSessionImpl::m_clientTrustLevel = V8Inspector::kUntrusted [private]
Definition at line 151 of file v8-inspector-session-impl.h.
Referenced by clientTrustLevel(), and V8InspectorSessionImpl().
m_consoleAgent
std::unique_ptr<V8ConsoleAgentImpl> v8_inspector::V8InspectorSessionImpl::m_consoleAgent [private]
Definition at line 146 of file v8-inspector-session-impl.h.
Referenced by consoleAgent(), V8InspectorSessionImpl(), and ~V8InspectorSessionImpl().
m_contextGroupId
int v8_inspector::V8InspectorSessionImpl::m_contextGroupId [private]
Definition at line 133 of file v8-inspector-session-impl.h.
Referenced by contextGroupId(), discardInjectedScripts(), findInjectedScript(), releaseObjectGroup(), reportAllContexts(), and setCustomObjectFormatterEnabled().
m_customObjectFormatterEnabled
bool v8_inspector::V8InspectorSessionImpl::m_customObjectFormatterEnabled [private]
Definition at line 137 of file v8-inspector-session-impl.h.
Referenced by findInjectedScript(), and setCustomObjectFormatterEnabled().
m_debuggerAgent
std::unique_ptr<V8DebuggerAgentImpl> v8_inspector::V8InspectorSessionImpl::m_debuggerAgent [private]
Definition at line 143 of file v8-inspector-session-impl.h.
Referenced by breakProgram(), cancelPauseOnNextStatement(), debuggerAgent(), reset(), resume(), schedulePauseOnNextStatement(), setSkipAllPauses(), stepOver(), stop(), V8InspectorSessionImpl(), and ~V8InspectorSessionImpl().
m_dispatcher
protocol::UberDispatcher v8_inspector::V8InspectorSessionImpl::m_dispatcher [private]
Definition at line 139 of file v8-inspector-session-impl.h.
Referenced by dispatchProtocolMessage(), and V8InspectorSessionImpl().
m_heapProfilerAgent
std::unique_ptr<V8HeapProfilerAgentImpl> v8_inspector::V8InspectorSessionImpl::m_heapProfilerAgent [private]
Definition at line 144 of file v8-inspector-session-impl.h.
Referenced by heapProfilerAgent(), V8InspectorSessionImpl(), and ~V8InspectorSessionImpl().
m_inspectedObjects
std::vector<std::unique_ptr<V8InspectorSession::Inspectable> > v8_inspector::V8InspectorSessionImpl::m_inspectedObjects [private]
Definition at line 149 of file v8-inspector-session-impl.h.
Referenced by addInspectedObject(), discardInjectedScripts(), and inspectedObject().
m_inspector
V8InspectorImpl* v8_inspector::V8InspectorSessionImpl::m_inspector [private]
Definition at line 135 of file v8-inspector-session-impl.h.
Referenced by discardInjectedScripts(), evaluate(), findInjectedScript(), inspector(), releaseObjectGroup(), reportAllContexts(), setCustomObjectFormatterEnabled(), and ~V8InspectorSessionImpl().
m_profilerAgent
std::unique_ptr<V8ProfilerAgentImpl> v8_inspector::V8InspectorSessionImpl::m_profilerAgent [private]
Definition at line 145 of file v8-inspector-session-impl.h.
Referenced by profilerAgent(), triggerPreciseCoverageDeltaUpdate(), V8InspectorSessionImpl(), and ~V8InspectorSessionImpl().
m_runtimeAgent
std::unique_ptr<V8RuntimeAgentImpl> v8_inspector::V8InspectorSessionImpl::m_runtimeAgent [private]
Definition at line 142 of file v8-inspector-session-impl.h.
Referenced by reset(), runtimeAgent(), V8InspectorSessionImpl(), and ~V8InspectorSessionImpl().
m_schemaAgent
std::unique_ptr<V8SchemaAgentImpl> v8_inspector::V8InspectorSessionImpl::m_schemaAgent [private]
Definition at line 147 of file v8-inspector-session-impl.h.
Referenced by schemaAgent(), and V8InspectorSessionImpl().
m_sessionId
int v8_inspector::V8InspectorSessionImpl::m_sessionId [private]
Definition at line 134 of file v8-inspector-session-impl.h.
Referenced by discardInjectedScripts(), findInjectedScript(), releaseObjectGroup(), sessionId(), and setCustomObjectFormatterEnabled().
m_state
std::unique_ptr<protocol::DictionaryValue> v8_inspector::V8InspectorSessionImpl::m_state [private]
Definition at line 140 of file v8-inspector-session-impl.h.
Referenced by agentState(), dispatchProtocolMessage(), state(), and V8InspectorSessionImpl().
m_weakThis
std::weak_ptr<V8InspectorSessionImpl> v8_inspector::V8InspectorSessionImpl::m_weakThis [private]
Definition at line 165 of file v8-inspector-session-impl.h.
Referenced by setWeakThis().
use_binary_protocol_
bool v8_inspector::V8InspectorSessionImpl::use_binary_protocol_ = false [private]
Definition at line 150 of file v8-inspector-session-impl.h.
Referenced by dispatchProtocolMessage(), serializeForFrontend(), and V8InspectorSessionImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-inspector-session-impl.h
/mnt/V8SourceCode/src/inspector/v8-inspector-session-impl.cc