v8::internal::ReadOnlySerializer Class Reference
#include <read-only-serializer.h>
Public Member Functions
ReadOnlySerializer (Isolate *isolate, Snapshot::SerializerFlags flags)
~ReadOnlySerializer () override
void Serialize ()
Private Member Functions
void SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) override
ReadOnlySerializer (const ReadOnlySerializer &)=delete
ReadOnlySerializer & operator= (const ReadOnlySerializer &)=delete
Additional Inherited Members
Detailed Description
Definition at line 18 of file read-only-serializer.h.
Constructor & Destructor Documentation
ReadOnlySerializer() [1/2]
v8::internal::ReadOnlySerializer::ReadOnlySerializer (Isolate * isolate, Snapshot::SerializerFlags flags)
Definition at line 474 of file read-only-serializer.cc.
    : RootsSerializer(isolate, flags, RootIndex::kFirstReadOnlyRoot) {}
References v8::internal::kFirstReadOnlyRoot.
 ReadOnlySerializer()
v8::internal::ReadOnlySerializer::~ReadOnlySerializer () [override]
Definition at line 478 of file read-only-serializer.cc.
                                        {
  OutputStatistics("ReadOnlySerializer");
}
References v8::internal::Serializer::OutputStatistics().
ReadOnlySerializer() [2/2]
v8::internal::ReadOnlySerializer::ReadOnlySerializer (const ReadOnlySerializer &) [private], [delete]
Member Function Documentation
operator=()
ReadOnlySerializer& v8::internal::ReadOnlySerializer::operator= (const ReadOnlySerializer &) [private], [delete]
Serialize()
void v8::internal::ReadOnlySerializer::Serialize ()
Definition at line 482 of file read-only-serializer.cc.
                                   {
  DisallowGarbageCollection no_gc;
  ReadOnlyHeapImageSerializer::Serialize(isolate(), &sink_,
                                         GetUnmappedRegions(isolate()));
  ReadOnlyHeapObjectIterator it(isolate()->read_only_heap());
  for (Tagged<HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
    CheckRehashability(o);
    if (v8_flags.serialization_statistics) {
      CountAllocation(o->map(), o->Size(), SnapshotSpace::kReadOnlyHeap);
    }
  }
}
References v8::internal::RootsSerializer::CheckRehashability(), v8::internal::Serializer::CountAllocation(), v8::internal::anonymous_namespace{read-only-serializer.cc}::GetUnmappedRegions(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Serializer::isolate(), v8::internal::kReadOnlyHeap, v8::internal::ReadOnlyHeapObjectIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::sink_, and v8::internal::v8_flags.
Referenced by v8::internal::Snapshot::Create().
SerializeObjectImpl()
void v8::internal::ReadOnlySerializer::SerializeObjectImpl (Handle< HeapObject > o, SlotType slot_type) [inline], [override], [private], [virtual]
Implements v8::internal::Serializer.
Definition at line 27 of file read-only-serializer.h.
                                                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/read-only-serializer.h
/mnt/V8SourceCode/src/snapshot/read-only-serializer.cc