v8::internal::CompareOperation Class Reference
#include <ast.h>
Public Member Functions
Token::Value op () const
Expression * left () const
Expression * right () const
bool IsLiteralStrictCompareBoolean (Expression **expr, Literal **literal)
bool IsLiteralCompareUndefined (Expression **expr)
bool IsLiteralCompareNull (Expression **expr)
bool IsLiteralCompareEqualVariable (Expression **expr, Literal **literal)
Private Types
using OperatorField = Expression::NextBitField< Token::Value, 7 >
Private Member Functions
CompareOperation (Token::Value op, Expression *left, Expression *right, int pos)
Private Attributes
friend Zone
Expression * left_
Expression * right_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2024 of file ast.h.
Member Typedef Documentation
OperatorField
using v8::internal::CompareOperation::OperatorField = Expression::NextBitField<Token::Value, 7> [private]
Definition at line 2050 of file ast.h.
Constructor & Destructor Documentation
CompareOperation()
v8::internal::CompareOperation::CompareOperation (Token::Value op, Expression * left, Expression * right, int pos) [inline], [private]
Definition at line 2040 of file ast.h.
      : Expression(pos, kCompareOperation), left_(left), right_(right) {
    bit_field_ |= OperatorField::encode(op);
    DCHECK(Token::IsCompareOp(op));
  }
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Token::IsCompareOp(), and op().
Member Function Documentation
IsLiteralCompareEqualVariable()
bool v8::internal::CompareOperation::IsLiteralCompareEqualVariable (Expression ** expr, Literal ** literal)
Definition at line 955 of file ast.cc.
                                                                        {
  return (
      MatchLiteralCompareEqualVariable(left_, op(), right_, expr, literal) ||
      MatchLiteralCompareEqualVariable(right_, op(), left_, expr, literal));
}
References left_, v8::internal::MatchLiteralCompareEqualVariable(), op(), and right_.
IsLiteralCompareNull()
bool v8::internal::CompareOperation::IsLiteralCompareNull (Expression ** expr)
Definition at line 937 of file ast.cc.
                                                             {
  return MatchLiteralCompareNull(left_, op(), right_, expr) ||
         MatchLiteralCompareNull(right_, op(), left_, expr);
}
References left_, v8::internal::MatchLiteralCompareNull(), op(), and right_.
IsLiteralCompareUndefined()
bool v8::internal::CompareOperation::IsLiteralCompareUndefined (Expression ** expr)
Definition at line 922 of file ast.cc.
                                                                  {
  return MatchLiteralCompareUndefined(left_, op(), right_, expr) ||
         MatchLiteralCompareUndefined(right_, op(), left_, expr);
}
References left_, v8::internal::MatchLiteralCompareUndefined(), op(), and right_.
IsLiteralStrictCompareBoolean()
bool v8::internal::CompareOperation::IsLiteralStrictCompareBoolean (Expression ** expr, Literal ** literal)
Definition at line 901 of file ast.cc.
                                                                        {
  return MatchLiteralStrictCompareBoolean(left_, op(), right_, expr, literal) ||
         MatchLiteralStrictCompareBoolean(right_, op(), left_, expr, literal);
}
References left_, v8::internal::MatchLiteralStrictCompareBoolean(), op(), and right_.
left()
Expression* v8::internal::CompareOperation::left () const [inline]
Definition at line 2027 of file ast.h.
{ return left_; }
References left_.
Referenced by v8::internal::interpreter::IsLiteralCompareTypeof().
op()
Token::Value v8::internal::CompareOperation::op () const [inline]
Definition at line 2026 of file ast.h.
{ return OperatorField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by CompareOperation(), IsLiteralCompareEqualVariable(), IsLiteralCompareNull(), v8::internal::interpreter::IsLiteralCompareTypeof(), IsLiteralCompareUndefined(), and IsLiteralStrictCompareBoolean().
right()
Expression* v8::internal::CompareOperation::right () const [inline]
Definition at line 2028 of file ast.h.
{ return right_; }
References right_.
Referenced by v8::internal::interpreter::IsLiteralCompareTypeof().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2037 of file ast.h.
Member Data Documentation
left_
Expression* v8::internal::CompareOperation::left_ [private]
Definition at line 2047 of file ast.h.
Referenced by IsLiteralCompareEqualVariable(), IsLiteralCompareNull(), IsLiteralCompareUndefined(), IsLiteralStrictCompareBoolean(), and left().
right_
Expression* v8::internal::CompareOperation::right_ [private]
Definition at line 2048 of file ast.h.
Referenced by IsLiteralCompareEqualVariable(), IsLiteralCompareNull(), IsLiteralCompareUndefined(), IsLiteralStrictCompareBoolean(), and right().
Zone
friend v8::internal::CompareOperation::Zone [private]
Definition at line 2038 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc