v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand Class Reference
Public Member Functions
SignedOperand (int32_t value)
SignedOperand (uint32_t value)=delete
void WriteVLQ (ZoneVector< uint8_t > *buffer)
bool IsSigned () const
Detailed Description
Definition at line 54 of file frame-translation-builder.cc.
Constructor & Destructor Documentation
SignedOperand() [1/2]
v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::SignedOperand (int32_t value) [inline], [explicit]
Definition at line 56 of file frame-translation-builder.cc.
: OperandBase(value) {}
SignedOperand() [2/2]
v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::SignedOperand (uint32_t value) [explicit], [delete]
Member Function Documentation
IsSigned()
bool v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::IsSigned () const [inline]
Definition at line 67 of file frame-translation-builder.cc.
{ return true; }
WriteVLQ()
void v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::WriteVLQ (ZoneVector< uint8_t > * buffer) [inline]
Definition at line 59 of file frame-translation-builder.cc.
                                             {
    base::VLQEncode(
        [buffer](uint8_t value) {
          buffer->push_back(value);
          return &buffer->back();
        },
        value());
  }
References v8::internal::ZoneVector< T >::back(), v8::internal::ZoneVector< T >::push_back(), v8::internal::value, and v8::base::VLQEncode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/deoptimizer/frame-translation-builder.cc