v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger Class Reference
Public Member Functions
KnownMapsMerger (compiler::JSHeapBroker *broker, Zone *zone, base::Vector< const compiler::MapRef > requested_maps)
void IntersectWithKnownNodeAspects (ValueNode *object, const KnownNodeAspects &known_node_aspects)
void UpdateKnownNodeAspects (ValueNode *object, KnownNodeAspects &known_node_aspects)
bool known_maps_are_subset_of_requested_maps () const
bool emit_check_with_migration () const
const compiler::ZoneRefSet< Map > & intersect_set () const
NodeType node_type () const
Private Member Functions
Zone * zone () const
void InsertMap (compiler::MapRef map)
Private Attributes
compiler::JSHeapBroker * broker_
Zone * zone_
base::Vector< const compiler::MapRef > requested_maps_
compiler::ZoneRefSet< Map > intersect_set_
bool known_maps_are_subset_of_requested_maps_ = true
bool existing_known_maps_found_ = true
bool emit_check_with_migration_ = false
bool any_map_is_unstable_ = false
NodeType node_type_ = EmptyNodeType()
Detailed Description
Definition at line 4734 of file maglev-graph-builder.cc.
Constructor & Destructor Documentation
KnownMapsMerger()
v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::KnownMapsMerger (compiler::JSHeapBroker * broker, Zone * zone, base::Vector< const compiler::MapRef > requested_maps) [inline], [explicit]
Definition at line 4736 of file maglev-graph-builder.cc.
      : broker_(broker), zone_(zone), requested_maps_(requested_maps) {}
Member Function Documentation
emit_check_with_migration()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::emit_check_with_migration () const [inline]
Definition at line 4819 of file maglev-graph-builder.cc.
{ return emit_check_with_migration_; }
InsertMap()
void v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::InsertMap (compiler::MapRef map) [inline], [private]
Definition at line 4840 of file maglev-graph-builder.cc.
                                     {
    if (map.is_migration_target()) {
      emit_check_with_migration_ = true;
    }
    NodeType new_type = StaticTypeForMap(map, broker_);
    if (new_type == NodeType::kHeapNumber) {
      new_type = UnionType(new_type, NodeType::kSmi);
    }
    node_type_ = UnionType(node_type_, new_type);
    if (!map.is_stable()) {
      any_map_is_unstable_ = true;
    }
    intersect_set_.insert(map, zone());
  }
References v8::internal::ZoneCompactSet< T >::insert(), v8::internal::compiler::MapRef::is_migration_target(), v8::internal::compiler::MapRef::is_stable(), v8::internal::compiler::kSmi, v8::internal::maglev::StaticTypeForMap(), and v8::internal::maglev::UnionType().
intersect_set()
const compiler::ZoneRefSet<Map>& v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::intersect_set () const [inline]
Definition at line 4821 of file maglev-graph-builder.cc.
                                                       {
    return intersect_set_;
  }
IntersectWithKnownNodeAspects()
void v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::IntersectWithKnownNodeAspects (ValueNode * object, const KnownNodeAspects & known_node_aspects) [inline]
Definition at line 4740 of file maglev-graph-builder.cc.
                                                                     {
    auto node_info_it = known_node_aspects.FindInfo(object);
    bool has_node_info = known_node_aspects.IsValid(node_info_it);
    NodeType type =
        has_node_info ? node_info_it->second.type() : NodeType::kUnknown;
    if (has_node_info && node_info_it->second.possible_maps_are_known()) {
      // TODO(v8:7700): Make intersection non-quadratic.
      for (compiler::MapRef possible_map :
           node_info_it->second.possible_maps()) {
        if (std::find(requested_maps_.begin(), requested_maps_.end(),
                      possible_map) != requested_maps_.end()) {
          // No need to add dependencies, we already have them for all known
          // possible maps.
          // Filter maps which are impossible given this objects type. Since we
          // want to prove that an object with map `map` is not an instance of
          // `type`, we cannot use `StaticTypeForMap`, as it only provides an
          // approximation. This filtering is done to avoid creating
          // non-sensical types later (e.g. if we think only a non-string map
          // is possible, after a string check).
          if (IsInstanceOfNodeType(possible_map, type, broker_)) {
            InsertMap(possible_map);
          }
        } else {
          known_maps_are_subset_of_requested_maps_ = false;
        }
      }
      if (intersect_set_.is_empty()) {
        node_type_ = EmptyNodeType();
      }
    } else {
      // A missing entry here means the universal set, i.e., we don't know
      // anything about the possible maps of the object. Intersect with the
      // universal set, which means just insert all requested maps.
      known_maps_are_subset_of_requested_maps_ = false;
      existing_known_maps_found_ = false;
      for (compiler::MapRef map : requested_maps_) {
        InsertMap(map);
      }
    }
  }
References v8::internal::maglev::EmptyNodeType(), v8::internal::maglev::KnownNodeAspects::FindInfo(), v8::internal::maglev::IsInstanceOfNodeType(), v8::internal::maglev::KnownNodeAspects::IsValid(), and v8::internal::tracing::type.
known_maps_are_subset_of_requested_maps()
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::known_maps_are_subset_of_requested_maps () const [inline]
Definition at line 4816 of file maglev-graph-builder.cc.
                                                       {
    return known_maps_are_subset_of_requested_maps_;
  }
node_type()
NodeType v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::node_type () const [inline]
Definition at line 4825 of file maglev-graph-builder.cc.
{ return node_type_; }
UpdateKnownNodeAspects()
void v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::UpdateKnownNodeAspects (ValueNode * object, KnownNodeAspects & known_node_aspects) [inline]
Definition at line 4782 of file maglev-graph-builder.cc.
                                                                    {
    // Update known maps.
    auto node_info = known_node_aspects.GetOrCreateInfoFor(broker_, object);
    node_info->SetPossibleMaps(intersect_set_, any_map_is_unstable_, node_type_,
                               broker_);
    // Make sure known_node_aspects.any_map_for_any_node_is_unstable is updated
    // in case any_map_is_unstable changed to true for this object -- this can
    // happen if this was an intersection with the universal set which added new
    // possible unstable maps.
    if (any_map_is_unstable_) {
      known_node_aspects.any_map_for_any_node_is_unstable = true;
    }
    // At this point, known_node_aspects.any_map_for_any_node_is_unstable may be
    // true despite there no longer being any unstable maps for any nodes (if
    // this was the only node with unstable maps and this intersection removed
    // those). This is ok, because that's at worst just an overestimate -- we
    // could track whether this node's any_map_is_unstable flipped from true to
    // false, but this is likely overkill.
    // Insert stable map dependencies which weren't inserted yet. This is only
    // needed if our set of known maps was empty and we created it anew based on
    // maps we checked.
    if (!existing_known_maps_found_) {
      for (compiler::MapRef map : intersect_set_) {
        if (map.is_stable()) {
          broker_->dependencies()->DependOnStableMap(map);
        }
      }
    } else {
      // TODO(victorgomes): Add a DCHECK_SLOW that checks if the maps already
      // exist in the CompilationDependencySet.
    }
  }
References v8::internal::maglev::KnownNodeAspects::any_map_for_any_node_is_unstable, v8::internal::maglev::KnownNodeAspects::GetOrCreateInfoFor(), and v8::internal::maglev::NodeInfo::SetPossibleMaps().
zone()
Zone* v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::zone () const [inline], [private]
Definition at line 4838 of file maglev-graph-builder.cc.
{ return zone_; }
Member Data Documentation
any_map_is_unstable_
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::any_map_is_unstable_ = false [private]
Definition at line 4835 of file maglev-graph-builder.cc.
broker_
compiler::JSHeapBroker* v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::broker_ [private]
Definition at line 4828 of file maglev-graph-builder.cc.
emit_check_with_migration_
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::emit_check_with_migration_ = false [private]
Definition at line 4834 of file maglev-graph-builder.cc.
existing_known_maps_found_
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::existing_known_maps_found_ = true [private]
Definition at line 4833 of file maglev-graph-builder.cc.
intersect_set_
compiler::ZoneRefSet<Map> v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::intersect_set_ [private]
Definition at line 4831 of file maglev-graph-builder.cc.
known_maps_are_subset_of_requested_maps_
bool v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::known_maps_are_subset_of_requested_maps_ = true [private]
Definition at line 4832 of file maglev-graph-builder.cc.
node_type_
NodeType v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::node_type_ = EmptyNodeType() [private]
Definition at line 4836 of file maglev-graph-builder.cc.
requested_maps_
base::Vector<const compiler::MapRef> v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::requested_maps_ [private]
Definition at line 4830 of file maglev-graph-builder.cc.
zone_
Zone* v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::KnownMapsMerger::zone_ [private]
Definition at line 4829 of file maglev-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc