v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey Class Reference
#include <maglev-interpreter-frame-state.h>
Public Types
enum Type { kName = 0
, kElements
, kTypedArrayLength
, kStringLength
 }
Public Member Functions
LoadedPropertyMapKey (compiler::NameRef ref)
bool operator== (const LoadedPropertyMapKey &other) const
bool operator< (const LoadedPropertyMapKey &other) const
compiler::NameRef name ()
Type type ()
Static Public Member Functions
static LoadedPropertyMapKey Elements ()
static LoadedPropertyMapKey TypedArrayLength ()
static LoadedPropertyMapKey StringLength ()
Static Public Attributes
static constexpr int kTypeMask = 0x3
Private Member Functions
LoadedPropertyMapKey (Type type)
Private Attributes
Address data_
Detailed Description
Definition at line 468 of file maglev-interpreter-frame-state.h.
Member Enumeration Documentation
Type
enum v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::Type
Enumerator
kName
kElements
kTypedArrayLength
kStringLength
Definition at line 470 of file maglev-interpreter-frame-state.h.
              {
      // kName must be zero so that pointers are unaffected.
      kName = 0,
      kElements,
      kTypedArrayLength,
      // TODO(leszeks): We could probably share kStringLength with
      // kTypedArrayLength if needed.
      kStringLength
    };
Constructor & Destructor Documentation
LoadedPropertyMapKey() [1/2]
v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::LoadedPropertyMapKey (compiler::NameRef ref) [inline]
Definition at line 500 of file maglev-interpreter-frame-state.h.
        : data_(reinterpret_cast<Address>(ref.data())) {
      DCHECK_EQ(data_ & kTypeMask, kName);
    }
References data_, DCHECK_EQ, kName, and kTypeMask.
Referenced by Elements(), StringLength(), and TypedArrayLength().
LoadedPropertyMapKey() [2/2]
v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::LoadedPropertyMapKey (Type type) [inline], [explicit], [private]
Definition at line 521 of file maglev-interpreter-frame-state.h.
                                             : data_(type) {
      DCHECK_NE(type, kName);
    }
References DCHECK_NE, kName, and type().
Member Function Documentation
Elements()
static LoadedPropertyMapKey v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::Elements () [inline], [static]
Definition at line 485 of file maglev-interpreter-frame-state.h.
                                           {
      return LoadedPropertyMapKey(kElements);
    }
References kElements, and LoadedPropertyMapKey().
Referenced by v8::internal::maglev::NodeBase::ClearElementsProperties().
name()
compiler::NameRef v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::name () [inline]
Definition at line 512 of file maglev-interpreter-frame-state.h.
                           {
      DCHECK_EQ(type(), kName);
      return compiler::NameRef(reinterpret_cast<compiler::ObjectData*>(data_),
                               false);
    }
References data_, DCHECK_EQ, kName, and type().
operator<()
bool v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::operator< (const LoadedPropertyMapKey & other) const [inline]
Definition at line 508 of file maglev-interpreter-frame-state.h.
                                                            {
      return data_ < other.data_;
    }
References data_.
operator==()
bool v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::operator== (const LoadedPropertyMapKey & other) const [inline]
Definition at line 505 of file maglev-interpreter-frame-state.h.
                                                             {
      return data_ == other.data_;
    }
References data_.
StringLength()
static LoadedPropertyMapKey v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::StringLength () [inline], [static]
Definition at line 493 of file maglev-interpreter-frame-state.h.
                                               {
      return LoadedPropertyMapKey(kStringLength);
    }
References kStringLength, and LoadedPropertyMapKey().
Referenced by v8::internal::maglev::LoopOptimizationProcessor::Process().
type()
Type v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::type () [inline]
Definition at line 518 of file maglev-interpreter-frame-state.h.
{ return static_cast<Type>(data_ & kTypeMask); }
References data_, and kTypeMask.
Referenced by LoadedPropertyMapKey(), and name().
TypedArrayLength()
static LoadedPropertyMapKey v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::TypedArrayLength () [inline], [static]
Definition at line 489 of file maglev-interpreter-frame-state.h.
                                                   {
      return LoadedPropertyMapKey(kTypedArrayLength);
    }
References kTypedArrayLength, and LoadedPropertyMapKey().
Referenced by v8::internal::maglev::LoopOptimizationProcessor::Process().
Member Data Documentation
data_
Address v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::data_ [private]
Definition at line 525 of file maglev-interpreter-frame-state.h.
Referenced by LoadedPropertyMapKey(), name(), operator<(), operator==(), and type().
kTypeMask
constexpr int v8::internal::maglev::KnownNodeAspects::LoadedPropertyMapKey::kTypeMask = 0x3 [static], [constexpr]
Definition at line 479 of file maglev-interpreter-frame-state.h.
Referenced by LoadedPropertyMapKey(), and type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h