v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency Class Reference
Public Member Functions
OwnConstantDoublePropertyDependency (JSHeapBroker *broker, JSObjectRef holder, MapRef map, FieldIndex index, Float64 value)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
JSHeapBroker *const broker_
JSObjectRef const holder_
MapRef const map_
FieldIndex const index_
Float64 const value_
Additional Inherited Members
Detailed Description
Definition at line 507 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
OwnConstantDoublePropertyDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::OwnConstantDoublePropertyDependency (JSHeapBroker * broker, JSObjectRef holder, MapRef map, FieldIndex index, Float64 value) [inline]
Definition at line 509 of file compilation-dependencies.cc.
      : CompilationDependency(kOwnConstantDoubleProperty),
        broker_(broker),
        holder_(holder),
        map_(map),
        index_(index),
        value_(value) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 552 of file compilation-dependencies.cc.
                                                                {
    const OwnConstantDoublePropertyDependency* const zat =
        that->AsOwnConstantDoubleProperty();
    return holder_.equals(zat->holder_) && map_.equals(zat->map_) &&
           index_ == zat->index_ && value_.get_bits() == zat->value_.get_bits();
  }
References holder_, index_, map_, and value_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 546 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(holder_), h(map_), index_.bit_field(),
                              value_.get_bits());
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 542 of file compilation-dependencies.cc.
                                                                               {
  }
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 519 of file compilation-dependencies.cc.
                                                    {
    if (holder_.object()->map() != *map_.object()) {
      TRACE_BROKER_MISSING(broker_,
                           "Map change detected in " << holder_.object());
      return false;
    }
    DisallowGarbageCollection no_heap_allocation;
    Tagged<Object> current_value = holder_.object()->RawFastPropertyAt(index_);
    Float64 used_value = value_;
    // Compare doubles by bit pattern.
    if (!IsHeapNumber(current_value) ||
        Cast<HeapNumber>(current_value)->value_as_bits() !=
            used_value.get_bits()) {
      TRACE_BROKER_MISSING(broker_, "Constant Double property value changed in "
                                        << holder_.object() << " at FieldIndex "
                                        << index_.property_index());
      return false;
    }
    return true;
  }
References v8::internal::compiler::CompilationDependencies::broker_, and TRACE_BROKER_MISSING.
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::broker_ [private]
Definition at line 559 of file compilation-dependencies.cc.
holder_
JSObjectRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::holder_ [private]
Definition at line 560 of file compilation-dependencies.cc.
Referenced by Equals().
index_
FieldIndex const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::index_ [private]
Definition at line 562 of file compilation-dependencies.cc.
Referenced by Equals().
map_
MapRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::map_ [private]
Definition at line 561 of file compilation-dependencies.cc.
Referenced by Equals().
value_
Float64 const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDoublePropertyDependency::value_ [private]
Definition at line 563 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc