v8::internal::compiler::OperandAssigner Class Reference
#include <register-allocator.h>
Public Member Functions
OperandAssigner (RegisterAllocationData *data)
OperandAssigner (const OperandAssigner &)=delete
OperandAssigner & operator= (const OperandAssigner &)=delete
void DecideSpillingMode ()
void AssignSpillSlots ()
void CommitAssignment ()
Private Member Functions
RegisterAllocationData * data () const
Private Attributes
RegisterAllocationData *const data_
Detailed Description
Definition at line 1696 of file register-allocator.h.
Constructor & Destructor Documentation
OperandAssigner() [1/2]
v8::internal::compiler::OperandAssigner::OperandAssigner (RegisterAllocationData * data) [explicit]
Definition at line 4606 of file register-allocator.cc.
: data_(data) {}
OperandAssigner() [2/2]
v8::internal::compiler::OperandAssigner::OperandAssigner (const OperandAssigner &) [delete]
Member Function Documentation
AssignSpillSlots()
void v8::internal::compiler::OperandAssigner::AssignSpillSlots ()
Definition at line 4633 of file register-allocator.cc.
                                       {
  ZoneVector<SpillRange*> spill_ranges(data()->allocation_zone());
  for (const TopLevelLiveRange* range : data()->live_ranges()) {
    DCHECK_NOT_NULL(range);
    if (range->HasSpillRange()) {
      DCHECK_NOT_NULL(range->GetSpillRange());
      spill_ranges.push_back(range->GetSpillRange());
    }
  }
  // At this point, the `SpillRange`s for all `TopLevelLiveRange`s should be
  // unique, since none have been merged yet.
  DCHECK_EQ(spill_ranges.size(),
            std::set(spill_ranges.begin(), spill_ranges.end()).size());
  // Merge all `SpillRange`s that belong to the same `LiveRangeBundle`.
  for (const TopLevelLiveRange* range : data()->live_ranges()) {
    data()->tick_counter()->TickAndMaybeEnterSafepoint();
    DCHECK_NOT_NULL(range);
    if (range->get_bundle() != nullptr) {
      range->get_bundle()->MergeSpillRangesAndClear();
    }
  }
  // Now merge *all* disjoint, non-empty `SpillRange`s.
  // Formerly, this merging was O(n^2) in the number of `SpillRange`s, which
  // then dominated compile time (>40%) for some pathological cases,
  // e.g., https://crbug.com/v8/14133.
  // Now, we allow only `kMaxRetries` unsuccessful merges with directly
  // following `SpillRange`s. After each `kMaxRetries`, we exponentially
  // increase the stride, which limits the inner loop to O(log n) and thus
  // the overall merging to O(n * log n).
  // The merging above may have left some `SpillRange`s empty, remove them.
  SpillRange** end_nonempty =
      std::remove_if(spill_ranges.begin(), spill_ranges.end(),
                     [](const SpillRange* range) { return range->IsEmpty(); });
  for (SpillRange** range_it = spill_ranges.begin(); range_it < end_nonempty;
       ++range_it) {
    data()->tick_counter()->TickAndMaybeEnterSafepoint();
    SpillRange* range = *range_it;
    DCHECK(!range->IsEmpty());
    constexpr size_t kMaxRetries = 1000;
    size_t retries = kMaxRetries;
    size_t stride = 1;
    for (SpillRange** other_it = range_it + 1; other_it < end_nonempty;
         other_it += stride) {
      SpillRange* other = *other_it;
      DCHECK(!other->IsEmpty());
      if (range->TryMerge(other)) {
        DCHECK(other->IsEmpty());
        std::iter_swap(other_it, --end_nonempty);
      } else if (--retries == 0) {
        retries = kMaxRetries;
        stride *= 2;
      }
    }
  }
  spill_ranges.erase(end_nonempty, spill_ranges.end());
  // Allocate slots for the merged spill ranges.
  for (SpillRange* range : spill_ranges) {
    data()->tick_counter()->TickAndMaybeEnterSafepoint();
    DCHECK(!range->IsEmpty());
    if (!range->HasSlot()) {
      // Allocate a new operand referring to the spill slot, aligned to the
      // operand size.
      int width = range->byte_width();
      int index = data()->frame()->AllocateSpillSlot(width, width);
      range->set_assigned_slot(index);
    }
  }
}
References v8::internal::compiler::Frame::AllocateSpillSlot(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::SpillRange::byte_width(), data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::erase(), v8::internal::compiler::RegisterAllocationData::frame(), v8::internal::compiler::SpillRange::HasSlot(), v8::internal::index, v8::internal::compiler::SpillRange::IsEmpty(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::SpillRange::set_assigned_slot(), v8::internal::ZoneVector< T >::size(), v8::internal::anonymous_namespace{json-stringifier.cc}::stride, v8::internal::compiler::RegisterAllocationData::tick_counter(), v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), and v8::internal::compiler::SpillRange::TryMerge().
Referenced by v8::internal::compiler::turboshaft::AssignSpillSlotsPhase::Run().
CommitAssignment()
void v8::internal::compiler::OperandAssigner::CommitAssignment ()
Definition at line 4706 of file register-allocator.cc.
                                       {
  const size_t live_ranges_size = data()->live_ranges().size();
  for (TopLevelLiveRange* top_range : data()->live_ranges()) {
    data()->tick_counter()->TickAndMaybeEnterSafepoint();
    CHECK_EQ(live_ranges_size,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    DCHECK_NOT_NULL(top_range);
    if (top_range->IsEmpty()) continue;
    InstructionOperand spill_operand;
    if (top_range->HasSpillOperand()) {
      auto it = data()->slot_for_const_range().find(top_range);
      if (it != data()->slot_for_const_range().end()) {
        spill_operand = *it->second;
      } else {
        spill_operand = *top_range->GetSpillOperand();
      }
    } else if (top_range->HasSpillRange()) {
      spill_operand = top_range->GetSpillRangeOperand();
    }
    if (top_range->is_phi()) {
      data()->GetPhiMapValueFor(top_range)->CommitAssignment(
          top_range->GetAssignedOperand());
    }
    for (LiveRange* range = top_range; range != nullptr;
         range = range->next()) {
      InstructionOperand assigned = range->GetAssignedOperand();
      DCHECK(!assigned.IsUnallocated());
      range->ConvertUsesToOperand(assigned, spill_operand);
    }
    if (!spill_operand.IsInvalid()) {
      // If this top level range has a child spilled in a deferred block, we use
      // the range and control flow connection mechanism instead of spilling at
      // definition. Refer to the ConnectLiveRanges and ResolveControlFlow
      // phases. Normally, when we spill at definition, we do not insert a
      // connecting move when a successor child range is spilled - because the
      // spilled range picks up its value from the slot which was assigned at
      // definition. For ranges that are determined to spill only in deferred
      // blocks, we let ConnectLiveRanges and ResolveControlFlow find the blocks
      // where a spill operand is expected, and then finalize by inserting the
      // spills in the deferred blocks dominators.
      if (!top_range->IsSpilledOnlyInDeferredBlocks(data()) &&
          !top_range->HasGeneralSpillRange()) {
        // Spill at definition if the range isn't spilled in a way that will be
        // handled later.
        top_range->FilterSpillMoves(data(), spill_operand);
        top_range->CommitSpillMoves(data(), spill_operand);
      }
    }
  }
}
References CHECK_EQ, v8::internal::compiler::RegisterAllocationData::PhiMapValue::CommitAssignment(), data(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::compiler::end(), v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::LiveRange::next(), size(), v8::internal::compiler::RegisterAllocationData::slot_for_const_range(), v8::internal::compiler::RegisterAllocationData::tick_counter(), and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
Referenced by v8::internal::compiler::turboshaft::CommitAssignmentPhase::Run().
data()
RegisterAllocationData* v8::internal::compiler::OperandAssigner::data () const [inline], [private]
Definition at line 1712 of file register-allocator.h.
{ return data_; }
References data_.
Referenced by AssignSpillSlots(), CommitAssignment(), and DecideSpillingMode().
DecideSpillingMode()
void v8::internal::compiler::OperandAssigner::DecideSpillingMode ()
Definition at line 4608 of file register-allocator.cc.
                                         {
  for (auto range : data()->live_ranges()) {
    data()->tick_counter()->TickAndMaybeEnterSafepoint();
    DCHECK_NOT_NULL(range);
    if (range->IsSpilledOnlyInDeferredBlocks(data())) {
      // If the range is spilled only in deferred blocks and starts in
      // a non-deferred block, we transition its representation here so
      // that the LiveRangeConnector processes them correctly. If,
      // however, they start in a deferred block, we uograde them to
      // spill at definition, as that definition is in a deferred block
      // anyway. While this is an optimization, the code in LiveRangeConnector
      // relies on it!
      if (GetInstructionBlock(data()->code(), range->Start())->IsDeferred()) {
        TRACE("Live range %d is spilled and alive in deferred code only\n",
              range->vreg());
        range->TransitionRangeToSpillAtDefinition();
      } else {
        TRACE("Live range %d is spilled deferred code only but alive outside\n",
              range->vreg());
        range->TransitionRangeToDeferredSpill(data()->allocation_zone());
      }
    }
  }
}
References code, data(), DCHECK_NOT_NULL, v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::RegisterAllocationData::tick_counter(), v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), and v8::internal::TRACE().
Referenced by v8::internal::compiler::turboshaft::DecideSpillingModePhase::Run().
operator=()
OperandAssigner& v8::internal::compiler::OperandAssigner::operator= (const OperandAssigner &) [delete]
Member Data Documentation
data_
RegisterAllocationData* const v8::internal::compiler::OperandAssigner::data_ [private]
Definition at line 1714 of file register-allocator.h.
Referenced by data().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc