v8::internal::AssemblerRISCVC Class Reference
#include <extension-riscv-c.h>
Public Member Functions
void c_nop ()
void c_addi (Register rd, int8_t imm6)
void c_addi16sp (int16_t imm10)
void c_addi4spn (Register rd, int16_t uimm10)
void c_li (Register rd, int8_t imm6)
void c_lui (Register rd, int8_t imm6)
void c_slli (Register rd, uint8_t shamt6)
void c_lwsp (Register rd, uint16_t uimm8)
void c_jr (Register rs1)
void c_mv (Register rd, Register rs2)
void c_ebreak ()
void c_jalr (Register rs1)
void c_j (int16_t imm12)
void c_add (Register rd, Register rs2)
void c_sub (Register rd, Register rs2)
void c_and (Register rd, Register rs2)
void c_xor (Register rd, Register rs2)
void c_or (Register rd, Register rs2)
void c_swsp (Register rs2, uint16_t uimm8)
void c_lw (Register rd, Register rs1, uint16_t uimm7)
void c_sw (Register rs2, Register rs1, uint16_t uimm7)
void c_bnez (Register rs1, int16_t imm9)
void c_beqz (Register rs1, int16_t imm9)
void c_srli (Register rs1, int8_t shamt6)
void c_srai (Register rs1, int8_t shamt6)
void c_andi (Register rs1, int8_t imm6)
void c_fld (FPURegister rd, Register rs1, uint16_t uimm8)
void c_fsd (FPURegister rs2, Register rs1, uint16_t uimm8)
void c_fldsp (FPURegister rd, uint16_t uimm9)
void c_fsdsp (FPURegister rs2, uint16_t uimm9)
int CJumpOffset (Instr instr)
int16_t cjump_offset (Label *L)
int32_t cbranch_offset (Label *L)
void c_j (Label *L)
void c_bnez (Register rs1, Label *L)
void c_beqz (Register rs1, Label *L)
Static Public Member Functions
static bool IsCBranch (Instr instr)
static bool IsCJal (Instr instr)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-c.h.
Member Function Documentation
c_add()
void v8::internal::AssemblerRISCVC::c_add (Register rd, Register rs2)
Definition at line 92 of file extension-riscv-c.cc.
                                                     {
  DCHECK(rd != zero_reg && rs2 != zero_reg);
  GenInstrCR(0b1001, C2, rd, rs2);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCR().
c_addi()
void v8::internal::AssemblerRISCVC::c_addi (Register rd, int8_t imm6)
Definition at line 11 of file extension-riscv-c.cc.
                                                     {
  DCHECK(rd != zero_reg && imm6 != 0);
  GenInstrCI(0b000, C1, rd, imm6);
}
References v8::internal::C1, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCI().
c_addi16sp()
void v8::internal::AssemblerRISCVC::c_addi16sp (int16_t imm10)
Definition at line 23 of file extension-riscv-c.cc.
                                              {
  DCHECK(is_int10(imm10) && (imm10 & 0xf) == 0);
  uint8_t uimm6 = ((imm10 & 0x200) >> 4) | (imm10 & 0x10) |
                  ((imm10 & 0x40) >> 3) | ((imm10 & 0x180) >> 6) |
                  ((imm10 & 0x20) >> 5);
  GenInstrCIU(0b011, C1, sp, uimm6);
}
References v8::internal::C1, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCIU().
c_addi4spn()
void v8::internal::AssemblerRISCVC::c_addi4spn (Register rd, int16_t uimm10)
Definition at line 31 of file extension-riscv-c.cc.
                                                            {
  DCHECK(is_uint10(uimm10) && (uimm10 != 0));
  uint8_t uimm8 = ((uimm10 & 0x4) >> 1) | ((uimm10 & 0x8) >> 3) |
                  ((uimm10 & 0x30) << 2) | ((uimm10 & 0x3c0) >> 4);
  GenInstrCIW(0b000, C0, rd, uimm8);
}
References v8::internal::C0, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCIW().
c_and()
void v8::internal::AssemblerRISCVC::c_and (Register rd, Register rs2)
Definition at line 116 of file extension-riscv-c.cc.
                                                     {
  DCHECK(((rd.code() & 0b11000) == 0b01000) &&
         ((rs2.code() & 0b11000) == 0b01000));
  GenInstrCA(0b100011, C1, rd, 0b11, rs2);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCA().
Referenced by v8::internal::MacroAssembler::And().
c_andi()
void v8::internal::AssemblerRISCVC::c_andi (Register rs1, int8_t imm6)
Definition at line 252 of file extension-riscv-c.cc.
                                                      {
  DCHECK(((rs1.code() & 0b11000) == 0b01000) && is_int6(imm6));
  GenInstrCBA(0b100, 0b10, C1, rs1, imm6);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCBA().
Referenced by v8::internal::MacroAssembler::And().
c_beqz() [1/2]
void v8::internal::AssemblerRISCVC::c_beqz (Register rs1, int16_t imm9)
Definition at line 235 of file extension-riscv-c.cc.
                                                       {
  DCHECK(((rs1.code() & 0b11000) == 0b01000) && is_int9(imm9));
  uint8_t uimm8 = ((imm9 & 0x20) >> 5) | ((imm9 & 0x6)) | ((imm9 & 0xc0) >> 3) |
                  ((imm9 & 0x18) << 2) | ((imm9 & 0x100) >> 1);
  GenInstrCB(0b110, C1, rs1, uimm8);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCB().
c_beqz() [2/2]
void v8::internal::AssemblerRISCVC::c_beqz (Register rs1, Label * L) [inline]
Definition at line 74 of file extension-riscv-c.h.
{ c_beqz(rs1, cbranch_offset(L)); }
References c_beqz(), cbranch_offset(), and v8::internal::L.
Referenced by c_beqz().
c_bnez() [1/2]
void v8::internal::AssemblerRISCVC::c_bnez (Register rs1, int16_t imm9)
Definition at line 228 of file extension-riscv-c.cc.
                                                       {
  DCHECK(((rs1.code() & 0b11000) == 0b01000) && is_int9(imm9));
  uint8_t uimm8 = ((imm9 & 0x20) >> 5) | ((imm9 & 0x6)) | ((imm9 & 0xc0) >> 3) |
                  ((imm9 & 0x18) << 2) | ((imm9 & 0x100) >> 1);
  GenInstrCB(0b111, C1, rs1, uimm8);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCB().
c_bnez() [2/2]
void v8::internal::AssemblerRISCVC::c_bnez (Register rs1, Label * L) [inline]
Definition at line 73 of file extension-riscv-c.h.
{ c_bnez(rs1, cbranch_offset(L)); }
References c_bnez(), cbranch_offset(), and v8::internal::L.
Referenced by c_bnez().
c_ebreak()
void v8::internal::AssemblerRISCVC::c_ebreak ()
Definition at line 84 of file extension-riscv-c.cc.
{ GenInstrCR(0b1001, C2, zero_reg, zero_reg); }
References v8::internal::C2, and v8::internal::AssemblerRiscvBase::GenInstrCR().
Referenced by v8::internal::Assembler::EBREAK().
c_fld()
void v8::internal::AssemblerRISCVC::c_fld (FPURegister rd, Register rs1, uint16_t uimm8)
Definition at line 177 of file extension-riscv-c.cc.
                                                                        {
  DCHECK(((rd.code() & 0b11000) == 0b01000) &&
         ((rs1.code() & 0b11000) == 0b01000) && is_uint8(uimm8) &&
         ((uimm8 & 0x7) == 0));
  uint8_t uimm5 = ((uimm8 & 0x38) >> 1) | ((uimm8 & 0xc0) >> 6);
  GenInstrCL(0b001, C0, rd, rs1, uimm5);
}
References v8::internal::C0, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCL().
Referenced by v8::internal::MacroAssembler::LoadDouble().
c_fldsp()
void v8::internal::AssemblerRISCVC::c_fldsp (FPURegister rd, uint16_t uimm9)
Definition at line 53 of file extension-riscv-c.cc.
                                                            {
  DCHECK(is_uint9(uimm9) && (uimm9 & 0x7) == 0);
  uint8_t uimm6 = (uimm9 & 0x38) | ((uimm9 & 0x1c0) >> 6);
  GenInstrCIU(0b001, C2, rd, uimm6);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCIU().
Referenced by v8::internal::MacroAssembler::LoadDouble().
c_fsd()
void v8::internal::AssemblerRISCVC::c_fsd (FPURegister rs2, Register rs1, uint16_t uimm8)
Definition at line 206 of file extension-riscv-c.cc.
                                                                         {
  DCHECK(((rs2.code() & 0b11000) == 0b01000) &&
         ((rs1.code() & 0b11000) == 0b01000) && is_uint8(uimm8) &&
         ((uimm8 & 0x7) == 0));
  uint8_t uimm5 = ((uimm8 & 0x38) >> 1) | ((uimm8 & 0xc0) >> 6);
  GenInstrCS(0b101, C0, rs2, rs1, uimm5);
}
References v8::internal::C0, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCS().
Referenced by v8::internal::MacroAssembler::StoreDouble().
c_fsdsp()
void v8::internal::AssemblerRISCVC::c_fsdsp (FPURegister rs2, uint16_t uimm9)
Definition at line 150 of file extension-riscv-c.cc.
                                                             {
  DCHECK(is_uint9(uimm9) && (uimm9 & 0x7) == 0);
  uint8_t uimm6 = (uimm9 & 0x38) | ((uimm9 & 0x1c0) >> 6);
  GenInstrCSS(0b101, C2, rs2, uimm6);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCSS().
Referenced by v8::internal::MacroAssembler::StoreDouble().
c_j() [1/2]
void v8::internal::AssemblerRISCVC::c_j (int16_t imm12)
Definition at line 216 of file extension-riscv-c.cc.
                                       {
  DCHECK(is_int12(imm12));
  int16_t uimm11 = ((imm12 & 0x800) >> 1) | ((imm12 & 0x400) >> 4) |
                   ((imm12 & 0x300) >> 1) | ((imm12 & 0x80) >> 3) |
                   ((imm12 & 0x40) >> 1) | ((imm12 & 0x20) >> 5) |
                   ((imm12 & 0x10) << 5) | (imm12 & 0xe);
  GenInstrCJ(0b101, C1, uimm11);
  BlockTrampolinePoolFor(1);
}
References v8::internal::AssemblerRiscvBase::BlockTrampolinePoolFor(), v8::internal::C1, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCJ().
c_j() [2/2]
void v8::internal::AssemblerRISCVC::c_j (Label * L) [inline]
Definition at line 72 of file extension-riscv-c.h.
{ c_j(cjump_offset(L)); }
References c_j(), cjump_offset(), and v8::internal::L.
Referenced by c_j().
c_jalr()
void v8::internal::AssemblerRISCVC::c_jalr (Register rs1)
Definition at line 86 of file extension-riscv-c.cc.
                                         {
  DCHECK(rs1 != zero_reg);
  GenInstrCR(0b1001, C2, rs1, zero_reg);
  BlockTrampolinePoolFor(1);
}
References v8::internal::AssemblerRiscvBase::BlockTrampolinePoolFor(), v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCR().
c_jr()
void v8::internal::AssemblerRISCVC::c_jr (Register rs1)
Definition at line 73 of file extension-riscv-c.cc.
                                       {
  DCHECK(rs1 != zero_reg);
  GenInstrCR(0b1000, C2, rs1, zero_reg);
  BlockTrampolinePoolFor(1);
}
References v8::internal::AssemblerRiscvBase::BlockTrampolinePoolFor(), v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCR().
c_li()
void v8::internal::AssemblerRISCVC::c_li (Register rd, int8_t imm6)
Definition at line 38 of file extension-riscv-c.cc.
                                                   {
  DCHECK(rd != zero_reg);
  GenInstrCI(0b010, C1, rd, imm6);
}
References v8::internal::C1, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCI().
c_lui()
void v8::internal::AssemblerRISCVC::c_lui (Register rd, int8_t imm6)
Definition at line 43 of file extension-riscv-c.cc.
                                                    {
  DCHECK(rd != zero_reg && rd != sp && imm6 != 0);
  GenInstrCI(0b011, C1, rd, imm6);
}
References v8::internal::C1, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCI().
c_lw()
void v8::internal::AssemblerRISCVC::c_lw (Register rd, Register rs1, uint16_t uimm7)
Definition at line 158 of file extension-riscv-c.cc.
                                                                    {
  DCHECK(((rd.code() & 0b11000) == 0b01000) &&
         ((rs1.code() & 0b11000) == 0b01000) && is_uint7(uimm7) &&
         ((uimm7 & 0x3) == 0));
  uint8_t uimm5 =
      ((uimm7 & 0x4) >> 1) | ((uimm7 & 0x40) >> 6) | ((uimm7 & 0x38) >> 1);
  GenInstrCL(0b010, C0, rd, rs1, uimm5);
}
References v8::internal::C0, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCL().
Referenced by v8::internal::MacroAssembler::Lw().
c_lwsp()
void v8::internal::AssemblerRISCVC::c_lwsp (Register rd, uint16_t uimm8)
Definition at line 67 of file extension-riscv-c.cc.
                                                        {
  DCHECK(rd != zero_reg && is_uint8(uimm8) && (uimm8 & 0x3) == 0);
  uint8_t uimm6 = (uimm8 & 0x3c) | ((uimm8 & 0xc0) >> 6);
  GenInstrCIU(0b010, C2, rd, uimm6);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCIU().
Referenced by v8::internal::MacroAssembler::Lw().
c_mv()
void v8::internal::AssemblerRISCVC::c_mv (Register rd, Register rs2)
Definition at line 79 of file extension-riscv-c.cc.
                                                    {
  DCHECK(rd != zero_reg && rs2 != zero_reg);
  GenInstrCR(0b1000, C2, rd, rs2);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCR().
c_nop()
void v8::internal::AssemblerRISCVC::c_nop ()
Definition at line 9 of file extension-riscv-c.cc.
{ GenInstrCI(0b000, C1, zero_reg, 0); }
References v8::internal::C1, and v8::internal::AssemblerRiscvBase::GenInstrCI().
Referenced by v8::internal::Assembler::NOP().
c_or()
void v8::internal::AssemblerRISCVC::c_or (Register rd, Register rs2)
Definition at line 110 of file extension-riscv-c.cc.
                                                    {
  DCHECK(((rd.code() & 0b11000) == 0b01000) &&
         ((rs2.code() & 0b11000) == 0b01000));
  GenInstrCA(0b100011, C1, rd, 0b10, rs2);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCA().
Referenced by v8::internal::MacroAssembler::Or().
c_slli()
void v8::internal::AssemblerRISCVC::c_slli (Register rd, uint8_t shamt6)
Definition at line 48 of file extension-riscv-c.cc.
                                                        {
  DCHECK(rd != zero_reg && shamt6 != 0);
  GenInstrCIU(0b000, C2, rd, shamt6);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCIU().
c_srai()
void v8::internal::AssemblerRISCVC::c_srai (Register rs1, int8_t shamt6)
Definition at line 247 of file extension-riscv-c.cc.
                                                        {
  DCHECK(((rs1.code() & 0b11000) == 0b01000) && is_int6(shamt6));
  GenInstrCBA(0b100, 0b01, C1, rs1, shamt6);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCBA().
c_srli()
void v8::internal::AssemblerRISCVC::c_srli (Register rs1, int8_t shamt6)
Definition at line 242 of file extension-riscv-c.cc.
                                                        {
  DCHECK(((rs1.code() & 0b11000) == 0b01000) && is_int6(shamt6));
  GenInstrCBA(0b100, 0b00, C1, rs1, shamt6);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCBA().
c_sub()
void v8::internal::AssemblerRISCVC::c_sub (Register rd, Register rs2)
Definition at line 98 of file extension-riscv-c.cc.
                                                     {
  DCHECK(((rd.code() & 0b11000) == 0b01000) &&
         ((rs2.code() & 0b11000) == 0b01000));
  GenInstrCA(0b100011, C1, rd, 0b00, rs2);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCA().
c_sw()
void v8::internal::AssemblerRISCVC::c_sw (Register rs2, Register rs1, uint16_t uimm7)
Definition at line 187 of file extension-riscv-c.cc.
                                                                     {
  DCHECK(((rs2.code() & 0b11000) == 0b01000) &&
         ((rs1.code() & 0b11000) == 0b01000) && is_uint7(uimm7) &&
         ((uimm7 & 0x3) == 0));
  uint8_t uimm5 =
      ((uimm7 & 0x4) >> 1) | ((uimm7 & 0x40) >> 6) | ((uimm7 & 0x38) >> 1);
  GenInstrCS(0b110, C0, rs2, rs1, uimm5);
}
References v8::internal::C0, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCS().
Referenced by v8::internal::MacroAssembler::Sw().
c_swsp()
void v8::internal::AssemblerRISCVC::c_swsp (Register rs2, uint16_t uimm8)
Definition at line 136 of file extension-riscv-c.cc.
                                                         {
  DCHECK(is_uint8(uimm8) && (uimm8 & 0x3) == 0);
  uint8_t uimm6 = (uimm8 & 0x3c) | ((uimm8 & 0xc0) >> 6);
  GenInstrCSS(0b110, C2, rs2, uimm6);
}
References v8::internal::C2, v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCSS().
Referenced by v8::internal::MacroAssembler::Sw().
c_xor()
void v8::internal::AssemblerRISCVC::c_xor (Register rd, Register rs2)
Definition at line 104 of file extension-riscv-c.cc.
                                                     {
  DCHECK(((rd.code() & 0b11000) == 0b01000) &&
         ((rs2.code() & 0b11000) == 0b01000));
  GenInstrCA(0b100011, C1, rd, 0b01, rs2);
}
References v8::internal::C1, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), and v8::internal::AssemblerRiscvBase::GenInstrCA().
Referenced by v8::internal::MacroAssembler::Xor().
cbranch_offset()
int32_t v8::internal::AssemblerRISCVC::cbranch_offset (Label * L) [inline]
Definition at line 68 of file extension-riscv-c.h.
                                          {
    return branch_offset_helper(L, OffsetSize::kOffset9);
  }
References v8::internal::AssemblerRiscvBase::branch_offset_helper(), and v8::internal::L.
Referenced by c_beqz(), and c_bnez().
cjump_offset()
int16_t v8::internal::AssemblerRISCVC::cjump_offset (Label * L) [inline]
Definition at line 65 of file extension-riscv-c.h.
                                        {
    return (int16_t)branch_offset_helper(L, OffsetSize::kOffset11);
  }
References v8::internal::AssemblerRiscvBase::branch_offset_helper(), and v8::internal::L.
Referenced by c_j().
CJumpOffset()
int v8::internal::AssemblerRISCVC::CJumpOffset (Instr instr)
Definition at line 266 of file extension-riscv-c.cc.
                                            {
  int32_t imm12 = ((instr & 0x4) << 3) | ((instr & 0x38) >> 2) |
                  ((instr & 0x40) << 1) | ((instr & 0x80) >> 1) |
                  ((instr & 0x100) << 2) | ((instr & 0x600) >> 1) |
                  ((instr & 0x800) >> 7) | ((instr & 0x1000) >> 1);
  imm12 = imm12 << 20 >> 20;
  return imm12;
}
IsCBranch()
bool v8::internal::AssemblerRISCVC::IsCBranch (Instr instr) [static]
Definition at line 261 of file extension-riscv-c.cc.
                                           {
  int Op = instr & kRvcOpcodeMask;
  return Op == RO_C_BNEZ || Op == RO_C_BEQZ;
}
References v8::internal::kRvcOpcodeMask, v8::internal::RO_C_BEQZ, and v8::internal::RO_C_BNEZ.
Referenced by v8::internal::SetCBranchOffset().
IsCJal()
bool v8::internal::AssemblerRISCVC::IsCJal (Instr instr) [static]
Definition at line 257 of file extension-riscv-c.cc.
                                        {
  return (instr & kRvcOpcodeMask) == RO_C_J;
}
References v8::internal::kRvcOpcodeMask, and v8::internal::RO_C_J.
Referenced by v8::internal::SetCJalOffset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-c.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-c.cc