v8::internal::FrequencyCollator Class Reference
#include <regexp-compiler.h>
Classes
class CharacterFrequency
Public Member Functions
FrequencyCollator ()
void CountCharacter (int character)
int Frequency (int in_character)
Private Attributes
CharacterFrequency frequencies_ [RegExpMacroAssembler::kTableSize]
int total_samples_
Detailed Description
Definition at line 418 of file regexp-compiler.h.
Constructor & Destructor Documentation
FrequencyCollator()
v8::internal::FrequencyCollator::FrequencyCollator () [inline]
Definition at line 420 of file regexp-compiler.h.
                      : total_samples_(0) {
    for (int i = 0; i < RegExpMacroAssembler::kTableSize; i++) {
      frequencies_[i] = CharacterFrequency(i);
    }
  }
References frequencies_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::RegExpMacroAssembler::kTableSize.
Member Function Documentation
CountCharacter()
void v8::internal::FrequencyCollator::CountCharacter (int character) [inline]
Definition at line 426 of file regexp-compiler.h.
                                     {
    int index = (character & RegExpMacroAssembler::kTableMask);
    frequencies_[index].Increment();
    total_samples_++;
  }
References v8::internal::character, frequencies_, v8::internal::FrequencyCollator::CharacterFrequency::Increment(), v8::internal::index, v8::internal::RegExpMacroAssembler::kTableMask, and total_samples_.
Referenced by v8::internal::RegExpImpl::Compile().
Frequency()
int v8::internal::FrequencyCollator::Frequency (int in_character) [inline]
Definition at line 434 of file regexp-compiler.h.
                                  {
    DCHECK((in_character & RegExpMacroAssembler::kTableMask) == in_character);
    if (total_samples_ < 1) return 1; // Division by zero.
    int freq_in_per128 =
        (frequencies_[in_character].counter() * 128) / total_samples_;
    return freq_in_per128;
  }
References v8::internal::FrequencyCollator::CharacterFrequency::counter(), v8::internal::DCHECK(), frequencies_, v8::internal::RegExpMacroAssembler::kTableMask, and total_samples_.
Referenced by v8::internal::BoyerMooreLookahead::FindBestInterval().
Member Data Documentation
frequencies_
CharacterFrequency v8::internal::FrequencyCollator::frequencies_[RegExpMacroAssembler::kTableSize] [private]
Definition at line 459 of file regexp-compiler.h.
Referenced by CountCharacter(), Frequency(), and FrequencyCollator().
total_samples_
int v8::internal::FrequencyCollator::total_samples_ [private]
Definition at line 460 of file regexp-compiler.h.
Referenced by CountCharacter(), and Frequency().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h