v8::internal::compiler::Deduplicator Class Reference
Public Member Functions
Deduplicator (Zone *zone)
bool SeenBefore (const VirtualObject *vobject)
Private Attributes
Zone * zone_
BitVector is_duplicate_
Detailed Description
Definition at line 117 of file escape-analysis-reducer.cc.
Constructor & Destructor Documentation
Deduplicator()
v8::internal::compiler::Deduplicator::Deduplicator (Zone * zone) [inline], [explicit]
Definition at line 119 of file escape-analysis-reducer.cc.
: zone_(zone) {}
Member Function Documentation
SeenBefore()
bool v8::internal::compiler::Deduplicator::SeenBefore (const VirtualObject * vobject) [inline]
Definition at line 120 of file escape-analysis-reducer.cc.
                                                {
    DCHECK_LE(vobject->id(), std::numeric_limits<int>::max());
    int id = static_cast<int>(vobject->id());
    if (id >= is_duplicate_.length()) {
      is_duplicate_.Resize(id + 1, zone_);
    }
    bool is_duplicate = is_duplicate_.Contains(id);
    is_duplicate_.Add(id);
    return is_duplicate;
  }
References v8::internal::BitVector::Add(), v8::internal::BitVector::Contains(), DCHECK_LE, v8::internal::compiler::VirtualObject::id(), is_duplicate_, v8::internal::BitVector::length(), v8::internal::BitVector::Resize(), and zone_.
Referenced by v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState().
Member Data Documentation
is_duplicate_
BitVector v8::internal::compiler::Deduplicator::is_duplicate_ [private]
Definition at line 133 of file escape-analysis-reducer.cc.
Referenced by SeenBefore().
zone_
Zone* v8::internal::compiler::Deduplicator::zone_ [private]
Definition at line 132 of file escape-analysis-reducer.cc.
Referenced by SeenBefore().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis-reducer.cc