v8::internal::ObjectDeserializer Class Reference
#include <object-deserializer.h>
Static Public Member Functions
static MaybeDirectHandle< SharedFunctionInfo > DeserializeSharedFunctionInfo (Isolate *isolate, const SerializedCodeData *data, DirectHandle< String > source)
Private Member Functions
ObjectDeserializer (Isolate *isolate, const SerializedCodeData *data)
MaybeDirectHandle< HeapObject > Deserialize ()
void LinkAllocationSites ()
void CommitPostProcessedObjects ()
Additional Inherited Members
Detailed Description
Definition at line 17 of file object-deserializer.h.
Constructor & Destructor Documentation
ObjectDeserializer()
v8::internal::ObjectDeserializer::ObjectDeserializer (Isolate * isolate, const SerializedCodeData * data) [explicit], [private]
Definition at line 18 of file object-deserializer.cc.
    : Deserializer(isolate, data->Payload(), data->GetMagicNumber(), true,
                   false) {}
Member Function Documentation
CommitPostProcessedObjects()
void v8::internal::ObjectDeserializer::CommitPostProcessedObjects () [private]
Definition at line 55 of file object-deserializer.cc.
                                                    {
  for (DirectHandle<Script> script : new_scripts()) {
    // Assign a new script id to avoid collision.
    script->set_id(isolate()->GetNextScriptId());
    LogScriptEvents(*script);
    // Add script to list.
    Handle<WeakArrayList> list = isolate()->factory()->script_list();
    list = WeakArrayList::AddToEnd(isolate(), list,
                                   MaybeObjectDirectHandle::Weak(script));
    isolate()->heap()->SetRootScriptList(*list);
  }
}
References v8::internal::WeakArrayList::AddToEnd(), v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::Deserializer< Isolate >::LogScriptEvents(), v8::internal::Deserializer< Isolate >::new_scripts(), v8::internal::script, v8::internal::Heap::SetRootScriptList(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by Deserialize().
Deserialize()
MaybeDirectHandle< HeapObject > v8::internal::ObjectDeserializer::Deserialize () [private]
Definition at line 37 of file object-deserializer.cc.
                                                              {
  DCHECK(deserializing_user_code());
  HandleScope scope(isolate());
  DirectHandle<HeapObject> result;
  {
    result = ReadObject();
    DeserializeDeferredObjects();
    CHECK(new_code_objects().empty());
    LinkAllocationSites();
    CHECK(new_maps().empty());
    WeakenDescriptorArrays();
  }
  Rehash();
  CommitPostProcessedObjects();
  return scope.CloseAndEscape(result);
}
References CHECK, CommitPostProcessedObjects(), v8::internal::DCHECK(), v8::internal::Deserializer< Isolate >::DeserializeDeferredObjects(), v8::internal::Deserializer< Isolate >::deserializing_user_code(), v8::internal::Deserializer< Isolate >::isolate(), LinkAllocationSites(), v8::internal::Deserializer< Isolate >::new_code_objects(), v8::internal::Deserializer< Isolate >::new_maps(), v8::internal::Deserializer< Isolate >::ReadObject(), v8::internal::Deserializer< Isolate >::Rehash(), v8::base::internal::result, and v8::internal::Deserializer< Isolate >::WeakenDescriptorArrays().
Referenced by DeserializeSharedFunctionInfo().
DeserializeSharedFunctionInfo()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::ObjectDeserializer::DeserializeSharedFunctionInfo (Isolate * isolate, const SerializedCodeData * data, DirectHandle< String > source) [static]
Definition at line 24 of file object-deserializer.cc.
                                 {
  ObjectDeserializer d(isolate, data);
  d.AddAttachedObject(source);
  DirectHandle<HeapObject> result;
  return d.Deserialize().ToHandle(&result)
             ? Cast<SharedFunctionInfo>(result)
             : MaybeDirectHandle<SharedFunctionInfo>();
}
References v8::internal::Deserializer< IsolateT >::AddAttachedObject(), Deserialize(), v8::internal::Deserializer< Isolate >::isolate(), v8::base::internal::result, and v8::internal::Deserializer< Isolate >::source().
Referenced by v8::internal::CodeSerializer::Deserialize().
LinkAllocationSites()
void v8::internal::ObjectDeserializer::LinkAllocationSites () [private]
Definition at line 68 of file object-deserializer.cc.
                                             {
  DisallowGarbageCollection no_gc;
  Heap* heap = isolate()->heap();
  // Allocation sites are present in the snapshot, and must be linked into
  // a list at deserialization time.
  for (DirectHandle<AllocationSite> site : new_allocation_sites()) {
    if (!site->HasWeakNext()) continue;
    DirectHandle<AllocationSiteWithWeakNext> site_with_next =
        Cast<AllocationSiteWithWeakNext>(site);
    // TODO(mvstanton): consider treating the heap()->allocation_sites_list()
    // as a (weak) root. If this root is relocated correctly, this becomes
    // unnecessary.
    if (heap->allocation_sites_list() == Smi::zero()) {
      site_with_next->set_weak_next(ReadOnlyRoots(heap).undefined_value());
    } else {
      site_with_next->set_weak_next(
          Cast<UnionOf<Undefined, AllocationSiteWithWeakNext>>(
              heap->allocation_sites_list()));
    }
    heap->set_allocation_sites_list(*site_with_next);
  }
}
References v8::internal::Cast(), v8::internal::Isolate::heap(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::Deserializer< Isolate >::new_allocation_sites(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Smi::zero().
Referenced by Deserialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/object-deserializer.h
/mnt/V8SourceCode/src/snapshot/object-deserializer.cc