v8::internal::ZoneVector< T > Class Template Reference
#include <zone-containers.h>
Inherited by v8::internal::wasm::AsmJsParser::CachedVector< T >.
Public Types
using iterator = T *
using const_iterator = const T *
using reverse_iterator = std::reverse_iterator< T * >
using const_reverse_iterator = std::reverse_iterator< const T * >
using value_type = T
using reference = T &
using const_reference = const T &
using size_type = size_t
Public Member Functions
ZoneVector (Zone *zone)
ZoneVector (size_t size, Zone *zone)
ZoneVector (size_t size, T def, Zone *zone)
ZoneVector (std::initializer_list< T > list, Zone *zone)
template<class It , typename = typename std::iterator_traits<It>::iterator_category>
ZoneVector (It first, It last, Zone *zone)
ZoneVector (const ZoneVector &other) V8_NOEXCEPT
ZoneVector (ZoneVector &&other) V8_NOEXCEPT
~ZoneVector ()
ZoneVector & operator= (const ZoneVector &other) V8_NOEXCEPT
ZoneVector & operator= (ZoneVector &&other) V8_NOEXCEPT
ZoneVector & operator= (std::initializer_list< T > ilist)
void swap (ZoneVector< T > &other) noexcept
void resize (size_t new_size)
void resize (size_t new_size, const T &value)
void assign (size_t new_size, const T &value)
void clear ()
size_t size () const
bool empty () const
size_t capacity () const
void reserve (size_t new_cap)
T * data ()
const T * data () const
Zone * zone () const
T & at (size_t pos)
const T & at (size_t pos) const
T & operator[] (size_t pos)
const T & operator[] (size_t pos) const
T & front ()
const T & front () const
T & back ()
const T & back () const
T * begin () V8_NOEXCEPT
const T * begin () const V8_NOEXCEPT
const T * cbegin () const V8_NOEXCEPT
T * end () V8_NOEXCEPT
const T * end () const V8_NOEXCEPT
const T * cend () const V8_NOEXCEPT
reverse_iterator rbegin () V8_NOEXCEPT
const_reverse_iterator rbegin () const V8_NOEXCEPT
const_reverse_iterator crbegin () const V8_NOEXCEPT
reverse_iterator rend () V8_NOEXCEPT
const_reverse_iterator rend () const V8_NOEXCEPT
const_reverse_iterator crend () const V8_NOEXCEPT
void push_back (const T &value)
void push_back (T &&value)
void pop_back ()
template<typename... Args>
T & emplace_back (Args &&... args)
template<class It , typename = typename std::iterator_traits<It>::iterator_category>
T * insert (const T *pos, It first, It last)
T * insert (const T *pos, size_t count, const T &value)
T * erase (const T *pos)
T * erase (const T *first, const T *last)
Private Member Functions
size_t NewCapacity (size_t minimum)
void EnsureOneMoreCapacity ()
void EnsureCapacity (size_t minimum)
void CopyToNewStorage (T *dst, const T *src)
void MoveToNewStorage (T *dst, T *src)
void CopyingOverwrite (T *dst, const T *src)
void MovingOverwrite (T *dst, T *src)
void CopyToNewStorage (T *dst, const T *src, const T *src_end)
void MoveToNewStorage (T *dst, T *src, const T *src_end)
void CopyingOverwrite (T *dst, const T *src, const T *src_end)
void MovingOverwrite (T *dst, T *src, const T *src_end)
V8_NOINLINE V8_PRESERVE_MOST void Grow (size_t minimum)
T * PrepareForInsertion (const T *pos, size_t count, size_t *assignable)
T * erase (const T *first, size_t count)
template<typename... Args>
void emplace (T *target, Args &&... args)
Private Attributes
Zone * zone_ {nullptr}
T * data_ {nullptr}
T * end_ {nullptr}
T * capacity_ {nullptr}
Static Private Attributes
static constexpr size_t kMinCapacity = 2
Detailed Description
template<typename T>
class v8::internal::ZoneVector< T >
Definition at line 53 of file zone-containers.h.
Member Typedef Documentation
const_iterator
template<typename T >
using v8::internal::ZoneVector< T >::const_iterator = const T*
Definition at line 56 of file zone-containers.h.
const_reference
template<typename T >
using v8::internal::ZoneVector< T >::const_reference = const T&
Definition at line 61 of file zone-containers.h.
const_reverse_iterator
template<typename T >
using v8::internal::ZoneVector< T >::const_reverse_iterator = std::reverse_iterator<const T*>
Definition at line 58 of file zone-containers.h.
iterator
template<typename T >
using v8::internal::ZoneVector< T >::iterator = T*
Definition at line 55 of file zone-containers.h.
reference
template<typename T >
using v8::internal::ZoneVector< T >::reference = T&
Definition at line 60 of file zone-containers.h.
reverse_iterator
template<typename T >
using v8::internal::ZoneVector< T >::reverse_iterator = std::reverse_iterator<T*>
Definition at line 57 of file zone-containers.h.
size_type
template<typename T >
using v8::internal::ZoneVector< T >::size_type = size_t
Definition at line 62 of file zone-containers.h.
value_type
template<typename T >
using v8::internal::ZoneVector< T >::value_type = T
Definition at line 59 of file zone-containers.h.
Constructor & Destructor Documentation
ZoneVector() [1/7]
template<typename T >
v8::internal::ZoneVector< T >::ZoneVector (Zone * zone) [inline], [explicit]
Definition at line 65 of file zone-containers.h.
: zone_(zone) {}
ZoneVector() [2/7]
template<typename T >
v8::internal::ZoneVector< T >::ZoneVector (size_t size, Zone * zone) [inline]
Definition at line 69 of file zone-containers.h.
                                      : zone_(zone) {
    data_ = size > 0 ? zone->AllocateArray<T>(size) : nullptr;
    end_ = capacity_ = data_ + size;
    for (T* p = data_; p < end_; p++) emplace(p);
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::size(), and v8::internal::ZoneVector< T >::zone().
ZoneVector() [3/7]
template<typename T >
v8::internal::ZoneVector< T >::ZoneVector (size_t size, T def, Zone * zone) [inline]
Definition at line 77 of file zone-containers.h.
                                             : zone_(zone) {
    data_ = size > 0 ? zone->AllocateArray<T>(size) : nullptr;
    end_ = capacity_ = data_ + size;
    for (T* p = data_; p < end_; p++) emplace(p, def);
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::size(), and v8::internal::ZoneVector< T >::zone().
ZoneVector() [4/7]
template<typename T >
v8::internal::ZoneVector< T >::ZoneVector (std::initializer_list< T > list, Zone * zone) [inline]
Definition at line 85 of file zone-containers.h.
                                                      : zone_(zone) {
    size_t size = list.size();
    if (size > 0) {
      data_ = zone->AllocateArray<T>(size);
      CopyToNewStorage(data_, list.begin(), list.end());
    } else {
      data_ = nullptr;
    }
    end_ = capacity_ = data_ + size;
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::CopyToNewStorage(), v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::size(), and v8::internal::ZoneVector< T >::zone().
ZoneVector() [5/7]
template<typename T >
template<class It , typename = typename std::iterator_traits<It>::iterator_category>
v8::internal::ZoneVector< T >::ZoneVector (It first, It last, Zone * zone) [inline]
Definition at line 100 of file zone-containers.h.
                                            : zone_(zone) {
    if constexpr (std::is_base_of_v<
                      std::random_access_iterator_tag,
                      typename std::iterator_traits<It>::iterator_category>) {
      size_t size = last - first;
      data_ = size > 0 ? zone->AllocateArray<T>(size) : nullptr;
      end_ = capacity_ = data_ + size;
      for (T* p = data_; p < end_; p++) emplace(p, *first++);
    } else {
      while (first != last) push_back(*first++);
    }
    DCHECK_EQ(first, last);
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, DCHECK_EQ, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), and v8::internal::ZoneVector< T >::zone().
ZoneVector() [6/7]
template<typename T >
v8::internal::ZoneVector< T >::ZoneVector (const ZoneVector< T > & other) [inline]
Definition at line 114 of file zone-containers.h.
                                                  : zone_(other.zone_) {
    *this = other;
  }
ZoneVector() [7/7]
template<typename T >
v8::internal::ZoneVector< T >::ZoneVector (ZoneVector< T > && other) [inline]
Definition at line 118 of file zone-containers.h.
{ *this = std::move(other); }
 ZoneVector()
template<typename T >
v8::internal::ZoneVector< T >::~ZoneVector () [inline]
Definition at line 120 of file zone-containers.h.
                {
    for (T* p = data_; p < end_; p++) p->~T();
    if (data_) zone_->DeleteArray(data_, capacity());
  }
References v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::data_, v8::internal::Zone::DeleteArray(), v8::internal::ZoneVector< T >::end_, and v8::internal::ZoneVector< T >::zone_.
Member Function Documentation
assign()
template<typename T >
void v8::internal::ZoneVector< T >::assign (size_t new_size, const T & value) [inline]
Definition at line 216 of file zone-containers.h.
                                               {
    if (capacity() >= new_size) {
      T* new_end = data_ + new_size;
      T* assignable = data_ + std::min(size(), new_size);
      for (T* p = data_; p < assignable; p++) CopyingOverwrite(p, &value);
      for (T* p = assignable; p < new_end; p++) CopyToNewStorage(p, &value);
      for (T* p = new_end; p < end_; p++) p->~T();
      end_ = new_end;
    } else {
      clear();
      EnsureCapacity(new_size);
      T* new_end = data_ + new_size;
      for (T* p = data_; p < new_end; p++) emplace(p, value);
      end_ = new_end;
    }
  }
References v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::clear(), v8::internal::ZoneVector< T >::CopyingOverwrite(), v8::internal::ZoneVector< T >::CopyToNewStorage(), v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::EnsureCapacity(), v8::internal::ZoneVector< T >::size(), and v8::internal::value.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), and v8::internal::compiler::InstructionSelector::InstructionSelector().
at() [1/2]
template<typename T >
T& v8::internal::ZoneVector< T >::at (size_t pos) [inline]
Definition at line 246 of file zone-containers.h.
                    {
    DCHECK_LT(pos, size());
    return data_[pos];
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_LT, and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::ZoneVectorWrapper::Inner::get(), v8::internal::ZoneVector< T >::operator[](), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand(), v8::internal::compiler::ScheduleVerifier::Run(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
at() [2/2]
template<typename T >
const T& v8::internal::ZoneVector< T >::at (size_t pos) const [inline]
Definition at line 250 of file zone-containers.h.
                                {
    DCHECK_LT(pos, size());
    return data_[pos];
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_LT, and v8::internal::ZoneVector< T >::size().
back() [1/2]
template<typename T >
T& v8::internal::ZoneVector< T >::back () [inline]
Definition at line 267 of file zone-containers.h.
            {
    DCHECK_GT(end_, data_);
    return *(end_ - 1);
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_GT, and v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::RegExpCompiler::Assemble(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::Module::IsGraphAsync(), v8::internal::maglev::Graph::last_block(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude(), v8::internal::compiler::BasicBlock::set_control_input(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder(), v8::internal::compiler::InstructionSelector::VisitBlock(), v8::internal::compiler::StringBuilderOptimizer::VisitGraph(), and v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::WriteVLQ().
back() [2/2]
template<typename T >
const T& v8::internal::ZoneVector< T >::back () const [inline]
Definition at line 271 of file zone-containers.h.
                        {
    DCHECK_GT(end_, data_);
    return *(end_ - 1);
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_GT, and v8::internal::ZoneVector< T >::end_.
begin() [1/2]
template<typename T >
const T* v8::internal::ZoneVector< T >::begin () const [inline]
Definition at line 277 of file zone-containers.h.
{ return data_; }
References v8::internal::ZoneVector< T >::data_.
begin() [2/2]
template<typename T >
T* v8::internal::ZoneVector< T >::begin () [inline]
Definition at line 276 of file zone-containers.h.
{ return data_; }
References v8::internal::ZoneVector< T >::data_.
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::compiler::anonymous_namespace{access-info.cc}::AppendVector(), v8::internal::maglev::StraightForwardRegisterAllocator::ApplyPatches(), v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::maglev::Graph::begin(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::CodeStubAssembler::BuildFastLoop(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::Revectorizer::CollectSeeds(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CopyOptimizedBytecode(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CopyRangeToOutput(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::compiler::InstructionSelector::CachedStateValues::Emit(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitArgument(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitValue(), v8::internal::compiler::Schedule::EnsureSplitEdgeForm(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::maglev::MaglevGraphBuilder::FlushNodesToBlock(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), v8::internal::Module::GetModuleNamespace(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::NodeCopier::Insert(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::maglev::Graph::IterateGraphAndSweepDeadBlocks(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::AccessInfoFactory::MergePropertyAccessInfos(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::MergeSLPTree(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::operator<(), v8::internal::operator==(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessBasicBlock(), v8::internal::compiler::InstructionBlock::PredecessorIndexOf(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::Revectorizer::ReduceStoreChains(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::compiler::JSNativeContextSpecialization::RemoveImpossibleMaps(), v8::internal::compiler::BasicBlock::RemovePredecessor(), v8::internal::ZoneVector< T >::rend(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::EarlyGraphTrimmingPhase::Run(), v8::internal::compiler::LoopPeelingPhase::Run(), v8::internal::compiler::MemoryOptimizationPhase::Run(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::SetRange(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), v8::internal::maglev::MaglevInliner::TruncateGraphAt(), v8::internal::compiler::SLPTree::TryReduceLoadChain(), v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges(), and v8::internal::compiler::InstructionSelector::VisitBlock().
capacity()
template<typename T >
size_t v8::internal::ZoneVector< T >::capacity () const [inline]
Definition at line 240 of file zone-containers.h.
{ return capacity_ - data_; }
References v8::internal::ZoneVector< T >::capacity_, and v8::internal::ZoneVector< T >::data_.
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::EnsureCapacity(), v8::internal::ZoneVector< T >::EnsureOneMoreCapacity(), v8::internal::ZoneVector< T >::NewCapacity(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::PrepareForInsertion(), and v8::internal::ZoneVector< T >::~ZoneVector().
cbegin()
template<typename T >
const T* v8::internal::ZoneVector< T >::cbegin () const [inline]
Definition at line 278 of file zone-containers.h.
{ return data_; }
References v8::internal::ZoneVector< T >::data_.
Referenced by v8::internal::ZoneVector< T >::crend(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), and v8::internal::compiler::RepresentationSelector::RunRetypePhase().
cend()
template<typename T >
const T* v8::internal::ZoneVector< T >::cend () const [inline]
Definition at line 282 of file zone-containers.h.
{ return end_; }
References v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::ZoneVector< T >::crbegin(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), and v8::internal::compiler::RepresentationSelector::RunRetypePhase().
clear()
template<typename T >
void v8::internal::ZoneVector< T >::clear () [inline]
Definition at line 233 of file zone-containers.h.
               {
    for (T* p = data_; p < end_; p++) p->~T();
    end_ = data_;
  }
References v8::internal::ZoneVector< T >::data_, and v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::MoveOptimizer::CompressMoves(), v8::internal::wasm::AsmJsParser::CachedVectors< T >::fill(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::FlushPendingPushRegisters(), v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::FlushPendingPushRegisters(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::FlushPendingPushRegisters(), v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::compiler::anonymous_namespace{move-optimizer.cc}::OperandSet::OperandSet(), v8::internal::ZoneVector< T >::operator=(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::CFGBuilder::ResetDataStructures(), and v8::internal::compiler::Dependable::RevisitDependants().
CopyingOverwrite() [1/2]
template<typename T >
void v8::internal::ZoneVector< T >::CopyingOverwrite (T * dst, const T * src) [inline], [private]
Definition at line 413 of file zone-containers.h.
                                                        {
    if constexpr (std::is_copy_assignable_v<T>) {
      *dst = *src;
    } else {
      dst->~T();
      CopyToNewStorage(dst, src);
    }
  }
References v8::internal::ZoneVector< T >::CopyToNewStorage().
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::CopyingOverwrite(), v8::internal::ZoneVector< T >::insert(), and v8::internal::ZoneVector< T >::MovingOverwrite().
CopyingOverwrite() [2/2]
template<typename T >
void v8::internal::ZoneVector< T >::CopyingOverwrite (T * dst, const T * src, const T * src_end) [inline], [private]
Definition at line 455 of file zone-containers.h.
                                                                          {
    EMIT_TRIVIAL_CASE(memmove)
    for (; src < src_end; dst++, src++) {
      CopyingOverwrite(dst, src);
    }
  }
References v8::internal::ZoneVector< T >::CopyingOverwrite(), and EMIT_TRIVIAL_CASE.
CopyToNewStorage() [1/2]
template<typename T >
void v8::internal::ZoneVector< T >::CopyToNewStorage (T * dst, const T * src) [inline], [private]
Definition at line 403 of file zone-containers.h.
{ emplace(dst, *src); }
References v8::internal::ZoneVector< T >::emplace().
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::CopyingOverwrite(), v8::internal::ZoneVector< T >::CopyToNewStorage(), v8::internal::ZoneVector< T >::insert(), v8::internal::ZoneVector< T >::MoveToNewStorage(), v8::internal::ZoneVector< T >::operator=(), and v8::internal::ZoneVector< T >::ZoneVector().
CopyToNewStorage() [2/2]
template<typename T >
void v8::internal::ZoneVector< T >::CopyToNewStorage (T * dst, const T * src, const T * src_end) [inline], [private]
Definition at line 440 of file zone-containers.h.
                                                                          {
    EMIT_TRIVIAL_CASE(memcpy)
    for (; src < src_end; dst++, src++) {
      CopyToNewStorage(dst, src);
    }
  }
References v8::internal::ZoneVector< T >::CopyToNewStorage(), and EMIT_TRIVIAL_CASE.
crbegin()
template<typename T >
const_reverse_iterator v8::internal::ZoneVector< T >::crbegin () const [inline]
Definition at line 290 of file zone-containers.h.
                                                     {
    return std::make_reverse_iterator(cend());
  }
References v8::internal::ZoneVector< T >::cend().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude(), and v8::internal::compiler::RepresentationSelector::RunPropagatePhase().
crend()
template<typename T >
const_reverse_iterator v8::internal::ZoneVector< T >::crend () const [inline]
Definition at line 299 of file zone-containers.h.
                                                   {
    return std::make_reverse_iterator(cbegin());
  }
References v8::internal::ZoneVector< T >::cbegin().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude(), and v8::internal::compiler::RepresentationSelector::RunPropagatePhase().
data() [1/2]
template<typename T >
T* v8::internal::ZoneVector< T >::data () [inline]
Definition at line 242 of file zone-containers.h.
{ return data_; }
References v8::internal::ZoneVector< T >::data_.
Referenced by v8::internal::RegExpBytecodeGenerator::Bind(), v8::internal::RegExpBytecodeGenerator::Copy(), v8::internal::RegExpBytecodeGenerator::Emit16(), v8::internal::RegExpBytecodeGenerator::Emit32(), v8::internal::RegExpBytecodeGenerator::Emit8(), v8::internal::RegExpBytecodeGenerator::GetCode(), v8::internal::EhFrameWriter::GetEhFrame(), v8::internal::FrameTranslationBuilder::ToFrameTranslation(), v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
data() [2/2]
template<typename T >
const T* v8::internal::ZoneVector< T >::data () const [inline]
Definition at line 243 of file zone-containers.h.
{ return data_; }
References v8::internal::ZoneVector< T >::data_.
emplace()
template<typename T >
template<typename... Args>
void v8::internal::ZoneVector< T >::emplace (T * target, Args &&... args) [inline], [private]
Definition at line 571 of file zone-containers.h.
                                          {
    new (target) T(std::forward<Args>(args)...);
  }
References v8::base::args, and T.
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::CopyToNewStorage(), v8::internal::ZoneVector< T >::insert(), v8::internal::ZoneVector< T >::MoveToNewStorage(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::resize(), and v8::internal::ZoneVector< T >::ZoneVector().
emplace_back()
template<typename T >
template<typename... Args>
T& v8::internal::ZoneVector< T >::emplace_back (Args &&... args) [inline]
Definition at line 315 of file zone-containers.h.
                                  {
    EnsureOneMoreCapacity();
    T* ptr = end_++;
    new (ptr) T(std::forward<Args>(args)...);
    return *ptr;
  }
References v8::base::args, v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::EnsureOneMoreCapacity(), and T.
Referenced by v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO(), v8::internal::ParserBase< Impl >::ParseConditionalChainExpression(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::DemandedElementAnalysis::RecordOp(), and v8::internal::compiler::turboshaft::UseMap::UseMap().
empty()
template<typename T >
bool v8::internal::ZoneVector< T >::empty () const [inline]
Definition at line 239 of file zone-containers.h.
{ return end_ == data_; }
References v8::internal::ZoneVector< T >::data_, and v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::RegExpCompiler::Assemble(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::compiler::MoveOptimizer::CompressMoves(), v8::internal::maglev::BasicBlock::ComputeRealJumpTarget(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::compiler::RawMachineAssembler::ExportForOptimization(), v8::internal::compiler::RawMachineAssembler::ExportForTest(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfos(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::Module::IsGraphAsync(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude(), v8::internal::compiler::FrameElider::PropagateIntoBlock(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::compiler::CFGBuilder::ResetDataStructures(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run(), v8::internal::compiler::BasicBlock::set_control_input(), v8::internal::maglev::BasicBlock::set_edge_split_block(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ShouldReduce(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_get(), v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder(), v8::internal::compiler::StringBuilderOptimizer::VisitGraph(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
end() [1/2]
template<typename T >
const T* v8::internal::ZoneVector< T >::end () const [inline]
Definition at line 281 of file zone-containers.h.
{ return end_; }
References v8::internal::ZoneVector< T >::end_.
end() [2/2]
template<typename T >
T* v8::internal::ZoneVector< T >::end () [inline]
Definition at line 280 of file zone-containers.h.
{ return end_; }
References v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::anonymous_namespace{access-info.cc}::AppendVector(), v8::internal::maglev::StraightForwardRegisterAllocator::ApplyPatches(), v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::CodeStubAssembler::BuildFastLoop(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::Revectorizer::CollectSeeds(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CopyRangeToOutput(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::compiler::InstructionSelector::CachedStateValues::Emit(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitValue(), v8::internal::maglev::Graph::end(), v8::internal::compiler::Schedule::EnsureSplitEdgeForm(), v8::internal::ZoneVector< T >::erase(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::LinearScanAllocator::ForwardStateTo(), v8::internal::Module::GetModuleNamespace(), v8::internal::ZoneVector< T >::insert(), v8::internal::compiler::NodeCopier::Insert(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::maglev::Graph::IterateGraphAndSweepDeadBlocks(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::AccessInfoFactory::MergePropertyAccessInfos(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::MergeSLPTree(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::operator<(), v8::internal::operator==(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessBasicBlock(), v8::internal::compiler::InstructionBlock::PredecessorIndexOf(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::compiler::Scheduler::PropagateImmediateDominators(), v8::internal::ZoneVector< T >::rbegin(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::Revectorizer::ReduceStoreChains(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::compiler::JSNativeContextSpecialization::RemoveImpossibleMaps(), v8::internal::compiler::CFGBuilder::Run(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::EarlyGraphTrimmingPhase::Run(), v8::internal::compiler::LoopPeelingPhase::Run(), v8::internal::compiler::MemoryOptimizationPhase::Run(), v8::internal::compiler::RepresentationSelector::RunLowerPhase(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::SetRange(), v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting(), v8::internal::maglev::MaglevInliner::TruncateGraphAt(), v8::internal::compiler::SLPTree::TryReduceLoadChain(), v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges(), and v8::internal::compiler::InstructionSelector::VisitBlock().
EnsureCapacity()
template<typename T >
void v8::internal::ZoneVector< T >::EnsureCapacity (size_t minimum) [inline], [private]
Definition at line 398 of file zone-containers.h.
                                                {
    if (V8_LIKELY(minimum <= capacity())) return;
    Grow(minimum);
  }
References v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::Grow(), and V8_LIKELY.
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::reserve(), and v8::internal::ZoneVector< T >::resize().
EnsureOneMoreCapacity()
template<typename T >
void v8::internal::ZoneVector< T >::EnsureOneMoreCapacity () [inline], [private]
Definition at line 393 of file zone-containers.h.
                                         {
    if (V8_LIKELY(end_ < capacity_)) return;
    Grow(capacity() + 1);
  }
References v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::Grow(), and V8_LIKELY.
Referenced by v8::internal::ZoneVector< T >::emplace_back(), v8::internal::ZoneVector< T >::insert(), and v8::internal::ZoneVector< T >::push_back().
erase() [1/3]
template<typename T >
T* v8::internal::ZoneVector< T >::erase (const T * first, const T * last) [inline]
Definition at line 375 of file zone-containers.h.
                                          {
    DCHECK(data_ <= first && first <= last && last <= end());
    if (first == last) return const_cast<T*>(first);
    return erase(first, last - first);
  }
References v8::internal::ZoneVector< T >::data_, v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), and v8::internal::ZoneVector< T >::erase().
erase() [2/3]
template<typename T >
T* v8::internal::ZoneVector< T >::erase (const T * first, size_t count) [inline], [private]
Definition at line 559 of file zone-containers.h.
                                         {
    DCHECK(data_ <= first && first <= end());
    DCHECK_LE(count, end() - first);
    T* position = const_cast<T*>(first);
    MovingOverwrite(position, position + count, end());
    T* old_end = end();
    end_ -= count;
    for (T* p = end_; p < old_end; p++) p->~T();
    return position;
  }
References v8::internal::ZoneVector< T >::data_, v8::internal::DCHECK(), DCHECK_LE, v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::end_, and v8::internal::ZoneVector< T >::MovingOverwrite().
erase() [3/3]
template<typename T >
T* v8::internal::ZoneVector< T >::erase (const T * pos) [inline]
Definition at line 370 of file zone-containers.h.
                         {
    DCHECK(data_ <= pos && pos <= end());
    if (pos == end()) return const_cast<T*>(pos);
    return erase(pos, 1);
  }
References v8::internal::ZoneVector< T >::data_, v8::internal::DCHECK(), and v8::internal::ZoneVector< T >::end().
Referenced by v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::ZoneVector< T >::erase(), v8::internal::compiler::LinearScanAllocator::InactiveToHandled(), v8::internal::compiler::JSNativeContextSpecialization::RemoveImpossibleMaps(), v8::internal::compiler::BasicBlock::RemovePredecessor(), v8::internal::compiler::BasicBlock::TrimNodes(), and v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges().
front() [1/2]
template<typename T >
T& v8::internal::ZoneVector< T >::front () [inline]
Definition at line 258 of file zone-containers.h.
             {
    DCHECK_GT(end_, data_);
    return *data_;
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_GT, and v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::BytecodeGraphBuilder::CreateGraph(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfosAsOne(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::MemoryOptimizer::MergeStates(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::maglev::Graph::RemoveUnreachableBlocks(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared(), v8::internal::compiler::InstructionSelector::VisitCall(), and v8::internal::compiler::InstructionSelector::VisitTailCall().
front() [2/2]
template<typename T >
const T& v8::internal::ZoneVector< T >::front () const [inline]
Definition at line 262 of file zone-containers.h.
                         {
    DCHECK_GT(end_, data_);
    return *data_;
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_GT, and v8::internal::ZoneVector< T >::end_.
Grow()
template<typename T >
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::ZoneVector< T >::Grow (size_t minimum) [inline], [private]
Definition at line 471 of file zone-containers.h.
                                                         {
    T* old_data = data_;
    T* old_end = end_;
    size_t old_size = size();
    size_t new_capacity = NewCapacity(minimum);
    data_ = zone_->AllocateArray<T>(new_capacity);
    end_ = data_ + old_size;
    if (old_data) {
      MoveToNewStorage(data_, old_data, old_end);
      zone_->DeleteArray(old_data, capacity_ - old_data);
    }
    capacity_ = data_ + new_capacity;
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, v8::internal::Zone::DeleteArray(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::MoveToNewStorage(), v8::internal::ZoneVector< T >::NewCapacity(), v8::internal::ZoneVector< T >::size(), and v8::internal::ZoneVector< T >::zone_.
Referenced by v8::internal::ZoneVector< T >::EnsureCapacity(), and v8::internal::ZoneVector< T >::EnsureOneMoreCapacity().
insert() [1/2]
template<typename T >
template<class It , typename = typename std::iterator_traits<It>::iterator_category>
T* v8::internal::ZoneVector< T >::insert (const T * pos, It first, It last) [inline]
Definition at line 324 of file zone-containers.h.
                                             {
    T* position;
    if constexpr (std::is_base_of_v<
                      std::random_access_iterator_tag,
                      typename std::iterator_traits<It>::iterator_category>) {
      DCHECK_LE(0, last - first);
      size_t count = last - first;
      size_t assignable;
      position = PrepareForInsertion(pos, count, &assignable);
      if constexpr (std::is_trivially_copyable_v<T>) {
        if (count > 0) memcpy(position, first, count * sizeof(T));
      } else {
        CopyingOverwrite(position, first, first + assignable);
        CopyToNewStorage(position + assignable, first + assignable, last);
      }
    } else if (pos == end()) {
      position = end_;
      while (first != last) {
        EnsureOneMoreCapacity();
        emplace(end_++, *first++);
      }
    } else {
      UNIMPLEMENTED();
      // We currently have no users of this case.
      // It could be implemented inefficiently as a combination of the two
      // cases above: while (first != last) { PrepareForInsertion(_, 1, _); }.
      // A more efficient approach would be to accumulate the input iterator's
      // results into a temporary vector first, then grow {this} only once
      // (by calling PrepareForInsertion(_, count, _)), then copy over the
      // accumulated elements.
    }
    return position;
  }
References v8::internal::ZoneVector< T >::CopyingOverwrite(), v8::internal::ZoneVector< T >::CopyToNewStorage(), DCHECK_LE, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::EnsureOneMoreCapacity(), v8::internal::ZoneVector< T >::PrepareForInsertion(), and v8::internal::UNIMPLEMENTED().
Referenced by v8::internal::compiler::LinearScanAllocator::ActiveToInactive(), v8::internal::compiler::LinearScanAllocator::AddToInactive(), v8::internal::compiler::anonymous_namespace{access-info.cc}::AppendVector(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::CopyRangeToOutput(), v8::internal::compiler::InstructionSelector::CachedStateValues::Emit(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::EmitValue(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::MergeSLPTree(), v8::internal::compiler::Scheduler::MovePlannedNodes(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run(), and v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::SetRange().
insert() [2/2]
template<typename T >
T* v8::internal::ZoneVector< T >::insert (const T * pos, size_t count, const T & value) [inline]
Definition at line 357 of file zone-containers.h.
                                                        {
    size_t assignable;
    T* position = PrepareForInsertion(pos, count, &assignable);
    T* dst = position;
    T* stop = dst + assignable;
    while (dst < stop) {
      CopyingOverwrite(dst++, &value);
    }
    stop = position + count;
    while (dst < stop) emplace(dst++, value);
    return position;
  }
References v8::internal::ZoneVector< T >::CopyingOverwrite(), v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::PrepareForInsertion(), and v8::internal::value.
MoveToNewStorage() [1/2]
template<typename T >
void v8::internal::ZoneVector< T >::MoveToNewStorage (T * dst, T * src) [inline], [private]
Definition at line 405 of file zone-containers.h.
                                                  {
    if constexpr (std::is_move_constructible_v<T>) {
      emplace(dst, std::move(*src));
    } else {
      CopyToNewStorage(dst, src);
    }
  }
References v8::internal::ZoneVector< T >::CopyToNewStorage(), and v8::internal::ZoneVector< T >::emplace().
Referenced by v8::internal::ZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::MoveToNewStorage(), and v8::internal::ZoneVector< T >::PrepareForInsertion().
MoveToNewStorage() [2/2]
template<typename T >
void v8::internal::ZoneVector< T >::MoveToNewStorage (T * dst, T * src, const T * src_end) [inline], [private]
Definition at line 447 of file zone-containers.h.
                                                                    {
    EMIT_TRIVIAL_CASE(memcpy)
    for (; src < src_end; dst++, src++) {
      MoveToNewStorage(dst, src);
      src->~T();
    }
  }
References EMIT_TRIVIAL_CASE, and v8::internal::ZoneVector< T >::MoveToNewStorage().
MovingOverwrite() [1/2]
template<typename T >
void v8::internal::ZoneVector< T >::MovingOverwrite (T * dst, T * src) [inline], [private]
Definition at line 422 of file zone-containers.h.
                                                 {
    if constexpr (std::is_move_assignable_v<T>) {
      *dst = std::move(*src);
    } else {
      CopyingOverwrite(dst, src);
    }
  }
References v8::internal::ZoneVector< T >::CopyingOverwrite().
Referenced by v8::internal::ZoneVector< T >::erase(), v8::internal::ZoneVector< T >::MovingOverwrite(), and v8::internal::ZoneVector< T >::PrepareForInsertion().
MovingOverwrite() [2/2]
template<typename T >
void v8::internal::ZoneVector< T >::MovingOverwrite (T * dst, T * src, const T * src_end) [inline], [private]
Definition at line 462 of file zone-containers.h.
                                                                   {
    EMIT_TRIVIAL_CASE(memmove)
    for (; src < src_end; dst++, src++) {
      MovingOverwrite(dst, src);
    }
  }
References EMIT_TRIVIAL_CASE, and v8::internal::ZoneVector< T >::MovingOverwrite().
NewCapacity()
template<typename T >
size_t v8::internal::ZoneVector< T >::NewCapacity (size_t minimum) [inline], [private]
Definition at line 383 of file zone-containers.h.
                                     {
    // We can ignore possible overflow here: on 32-bit platforms, if the
    // multiplication overflows, there's no better way to handle it than
    // relying on the "new_capacity < minimum" check; in particular, a
    // saturating multiplication would make no sense. On 64-bit platforms,
    // overflow is effectively impossible anyway.
    size_t new_capacity = data_ == capacity_ ? kMinCapacity : capacity() * 2;
    return new_capacity < minimum ? minimum : new_capacity;
  }
References v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, and v8::internal::ZoneVector< T >::kMinCapacity.
Referenced by v8::internal::ZoneVector< T >::Grow(), and v8::internal::ZoneVector< T >::PrepareForInsertion().
operator=() [1/3]
template<typename T >
ZoneVector& v8::internal::ZoneVector< T >::operator= (const ZoneVector< T > & other) [inline]
Definition at line 126 of file zone-containers.h.
                                                             {
    // Self-assignment would cause undefined behavior in the !copy_assignable
    // branch, but likely indicates a bug in calling code anyway.
    DCHECK_NE(this, &other);
    T* src = other.data_;
    if (capacity() >= other.size() && zone_ == other.zone_) {
      T* dst = data_;
      if constexpr (std::is_trivially_copyable_v<T>) {
        size_t size = other.size();
        if (size) memcpy(dst, src, size * sizeof(T));
        end_ = dst + size;
      } else if constexpr (std::is_copy_assignable_v<T>) {
        while (dst < end_ && src < other.end_) *dst++ = *src++;
        while (src < other.end_) emplace(dst++, *src++);
        T* old_end = end_;
        end_ = dst;
        for (T* p = end_; p < old_end; p++) p->~T();
      } else {
        for (T* p = data_; p < end_; p++) p->~T();
        while (src < other.end_) emplace(dst++, *src++);
        end_ = dst;
      }
    } else {
      for (T* p = data_; p < end_; p++) p->~T();
      if (data_) zone_->DeleteArray(data_, capacity());
      size_t new_cap = other.capacity();
      if (new_cap > 0) {
        data_ = zone_->AllocateArray<T>(new_cap);
        CopyToNewStorage(data_, other.data_, other.end_);
      } else {
        data_ = nullptr;
      }
      capacity_ = data_ + new_cap;
      end_ = data_ + other.size();
    }
    return *this;
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::CopyToNewStorage(), v8::internal::ZoneVector< T >::data_, DCHECK_NE, v8::internal::Zone::DeleteArray(), v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::size(), and v8::internal::ZoneVector< T >::zone_.
operator=() [2/3]
template<typename T >
ZoneVector& v8::internal::ZoneVector< T >::operator= (std::initializer_list< T > ilist) [inline]
Definition at line 185 of file zone-containers.h.
                                                      {
    clear();
    EnsureCapacity(ilist.size());
    CopyToNewStorage(data_, ilist.begin(), ilist.end());
    end_ = data_ + ilist.size();
    return *this;
  }
References v8::internal::ZoneVector< T >::clear(), v8::internal::ZoneVector< T >::CopyToNewStorage(), v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::end_, and v8::internal::ZoneVector< T >::EnsureCapacity().
operator=() [3/3]
template<typename T >
ZoneVector& v8::internal::ZoneVector< T >::operator= (ZoneVector< T > && other) [inline]
Definition at line 164 of file zone-containers.h.
                                                        {
    // Self-assignment would cause undefined behavior, and is probably a bug.
    DCHECK_NE(this, &other);
    // Move-assigning vectors from different zones would have surprising
    // lifetime semantics regardless of how we choose to implement it (keep
    // the old zone? Take the new zone?).
    if (zone_ == nullptr) {
      zone_ = other.zone_;
    } else {
      DCHECK_EQ(zone_, other.zone_);
    }
    for (T* p = data_; p < end_; p++) p->~T();
    if (data_) zone_->DeleteArray(data_, capacity());
    data_ = other.data_;
    end_ = other.end_;
    capacity_ = other.capacity_;
    // {other.zone_} may stay.
    other.data_ = other.end_ = other.capacity_ = nullptr;
    return *this;
  }
References v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, DCHECK_EQ, DCHECK_NE, v8::internal::Zone::DeleteArray(), v8::internal::ZoneVector< T >::end_, and v8::internal::ZoneVector< T >::zone_.
operator[]() [1/2]
template<typename T >
T& v8::internal::ZoneVector< T >::operator[] (size_t pos) [inline]
Definition at line 255 of file zone-containers.h.
{ return at(pos); }
References v8::internal::ZoneVector< T >::at().
operator[]() [2/2]
template<typename T >
const T& v8::internal::ZoneVector< T >::operator[] (size_t pos) const [inline]
Definition at line 256 of file zone-containers.h.
{ return at(pos); }
References v8::internal::ZoneVector< T >::at().
pop_back()
template<typename T >
void v8::internal::ZoneVector< T >::pop_back () [inline]
Definition at line 309 of file zone-containers.h.
                  {
    DCHECK_GT(end_, data_);
    (--end_)->~T();
  }
References v8::internal::ZoneVector< T >::data_, DCHECK_GT, v8::internal::ZoneVector< T >::end_, and T.
Referenced by v8::internal::RegExpCompiler::Assemble(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::compiler::LinearScanAllocator::InactiveToActive(), v8::internal::Module::IsGraphAsync(), v8::internal::compiler::BasicBlock::set_control_input(), and v8::internal::compiler::StringBuilderOptimizer::VisitGraph().
PrepareForInsertion()
template<typename T >
T* v8::internal::ZoneVector< T >::PrepareForInsertion (const T * pos, size_t count, size_t * assignable) [inline], [private]
Definition at line 485 of file zone-containers.h.
                                                                         {
    DCHECK(data_ <= pos && pos <= end_);
    CHECK(std::numeric_limits<size_t>::max() - size() >= count);
    size_t index = pos - data_;
    size_t to_shift = end() - pos;
    DCHECK_EQ(index + to_shift, size());
    if (capacity() < size() + count) {
      *assignable = 0; // Fresh memory is not assignable (must be constructed).
      T* old_data = data_;
      T* old_end = end_;
      size_t old_size = size();
      size_t new_capacity = NewCapacity(old_size + count);
      data_ = zone_->AllocateArray<T>(new_capacity);
      end_ = data_ + old_size + count;
      if (old_data) {
        MoveToNewStorage(data_, old_data, pos);
        MoveToNewStorage(data_ + index + count, const_cast<T*>(pos), old_end);
        zone_->DeleteArray(old_data, capacity_ - old_data);
      }
      capacity_ = data_ + new_capacity;
    } else {
      // There are two interesting cases: we're inserting more elements
      // than we're shifting (top), or the other way round (bottom).
      //
      // Old: [ABCDEFGHIJ___________]
      // <--used--><--empty-->
      //
      // Case 1: index=7, count=8, to_shift=3
      // New: [ABCDEFGaaacccccHIJ___]
      // <-><------>
      // to be in-place constructed
      //
      // assignable_slots
      //
      // Case 2: index=3, count=3, to_shift=7
      // New: [ABCaaaDEFGHIJ________]
      // <-----><->
      // to be in-place constructed
      //
      // This range can be assigned. We report the first 3
      // as {assignable_slots} to the caller, and use the other 4
      // in the loop below.
      // Observe that the number of old elements that are moved to the
      // new end by in-place construction always equals {assignable_slots}.
      size_t assignable_slots = std::min(to_shift, count);
      *assignable = assignable_slots;
      if constexpr (std::is_trivially_copyable_v<T>) {
        if (to_shift > 0) {
          // Add V8_ASSUME to silence gcc null check warning.
          V8_ASSUME(pos != nullptr);
          memmove(const_cast<T*>(pos + count), pos, to_shift * sizeof(T));
        }
        end_ += count;
        return data_ + index;
      }
      // Construct elements in previously-unused area ("HIJ" in the example
      // above). This frees up assignable slots.
      T* dst = end_ + count;
      T* src = end_;
      for (T* stop = dst - assignable_slots; dst > stop;) {
        MoveToNewStorage(--dst, --src);
      }
      // Move (by assignment) elements into previously used area. This is
      // "DEFG" in "case 2" in the example above.
      DCHECK_EQ(src > pos, to_shift > count);
      DCHECK_IMPLIES(src > pos, dst == end_);
      while (src > pos) MovingOverwrite(--dst, --src);
      // Not destructing {src} here because that'll happen either in a
      // future iteration (when that spot becomes {dst}) or in {insert()}.
      end_ += count;
    }
    return data_ + index;
  }
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::capacity_, CHECK, v8::internal::ZoneVector< T >::data_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Zone::DeleteArray(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::end_, v8::internal::index, v8::internal::ZoneVector< T >::MoveToNewStorage(), v8::internal::ZoneVector< T >::MovingOverwrite(), v8::internal::ZoneVector< T >::NewCapacity(), v8::internal::ZoneVector< T >::size(), V8_ASSUME, and v8::internal::ZoneVector< T >::zone_.
Referenced by v8::internal::ZoneVector< T >::insert().
push_back() [1/2]
template<typename T >
void v8::internal::ZoneVector< T >::push_back (const T & value) [inline]
Definition at line 303 of file zone-containers.h.
                                 {
    EnsureOneMoreCapacity();
    emplace(end_++, value);
  }
References v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::EnsureOneMoreCapacity(), and v8::internal::value.
Referenced by v8::internal::maglev::Graph::Add(), v8::internal::wasm::WasmModuleBuilder::AddDataSegment(), v8::internal::compiler::InstructionSequence::AddDeoptimizationEntry(), v8::internal::compiler::Dependable::AddDependency(), v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph(), v8::internal::compiler::InstructionSequence::AddInstruction(), v8::internal::maglev::StraightForwardRegisterAllocator::AddMoveBeforeCurrentNode(), v8::internal::compiler::BasicBlock::AddNode(), v8::internal::maglev::MaglevPhiRepresentationSelector::AddNode(), v8::internal::maglev::MaglevInliner::AddNodeAtBlockEnd(), v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::SpecialRPONumberer::LoopInfo::AddOutgoing(), v8::internal::wasm::WasmModuleBuilder::AddPassiveDataSegment(), v8::internal::compiler::BasicBlock::AddPredecessor(), v8::internal::FrameTranslationBuilder::AddRawToContents(), v8::internal::FrameTranslationBuilder::AddRawToContentsForCompression(), v8::internal::compiler::BasicBlock::AddSuccessor(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::Variable::AssignHoleCheckBitmapIndex(), v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock(), v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Bind(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::CodeStubAssembler::BuildFastLoop(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfos(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::AccessInfoFactory::ConsolidateElementLoad(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::RepresentationSelector::DeferReplacement(), v8::internal::compiler::InstructionSelector::Emit(), v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::anonymous_namespace{source-position-table.cc}::EncodeUInt(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::compiler::EXPORT_TEMPLATE_DECLARE(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::FrameTranslationBuilder::FinishPendingInstructionIfNeeded(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromHoleyFloat64ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromIntPtrToTagged(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromUint32ToTagged(), v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::wasm::AsmJsParser::GatherCases(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::compiler::RepresentationSelector::GenerateTraversal(), v8::internal::compiler::turboshaft::LoopFinder::GetLoopBody(), v8::internal::Module::GetModuleNamespace(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::GetNamedCaptures(), v8::internal::wasm::LiftoffAssembler::CacheState::GetTaggedSlotsForOOLCode(), v8::internal::compiler::JSNativeContextSpecialization::InferHasInPrototypeChain(), v8::internal::maglev::MaglevGraphBuilder::InferHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::InferMaps(), v8::internal::interpreter::BytecodeArrayRandomIterator::Initialize(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertyGetterCall(), v8::internal::compiler::JSNativeContextSpecialization::InlinePropertySetterCall(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::InstanceSizeWithMinSlack(), v8::internal::compiler::InstructionBlockFor(), v8::internal::Module::IsGraphAsync(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::compiler::AllNodes::Mark(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeFrameState(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::CodeStubAssembler::NameDictionaryLookup(), v8::internal::compiler::Schedule::NewBasicBlock(), v8::internal::compiler::SLPTree::NewPackNodeAndRecurs(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::compiler::ParallelMove::PrepareInsertAfter(), v8::internal::maglev::MaglevPhiRepresentationSelector::PreparePhiTaggings(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::maglev::GraphProcessor< NodeProcessor, visit_identity_nodes >::ProcessGraph(), v8::internal::compiler::BytecodeGraphBuilder::OsrIteratorState::ProcessOsrPrelude(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessStore(), v8::internal::compiler::MapRef::PrototypesElementsDoNotHaveAccessorsOrThrow(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::push_code_unit(), v8::internal::compiler::CFGBuilder::Queue(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordHint(), v8::internal::compiler::ReferenceMap::RecordReference(), v8::internal::compiler::TFGraph::RecordSimdStore(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeAt(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier(), v8::internal::compiler::TyperPhase::Run(), v8::internal::compiler::LoopFinderImpl::SerializeLoop(), v8::internal::compiler::SpecialRPONumberer::SerializeRPOIntoSchedule(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_get(), v8::internal::CodeStubAssembler::TaggedToWord32OrBigIntImpl(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateFunctionParams(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::StringBuilderOptimizer::VisitGraph(), v8::internal::compiler::InstructionSelector::VisitTailCall(), v8::internal::anonymous_namespace{frame-translation-builder.cc}::SmallUnsignedOperand::WriteVLQ(), v8::internal::anonymous_namespace{frame-translation-builder.cc}::UnsignedOperand::WriteVLQ(), v8::internal::anonymous_namespace{frame-translation-builder.cc}::SignedOperand::WriteVLQ(), and v8::internal::ZoneVector< T >::ZoneVector().
push_back() [2/2]
template<typename T >
void v8::internal::ZoneVector< T >::push_back (T && value) [inline]
Definition at line 307 of file zone-containers.h.
{ emplace_back(std::move(value)); }
References v8::internal::ZoneVector< T >::emplace_back(), and v8::internal::value.
rbegin() [1/2]
template<typename T >
const_reverse_iterator v8::internal::ZoneVector< T >::rbegin () const [inline]
Definition at line 287 of file zone-containers.h.
                                                    {
    return std::make_reverse_iterator(end());
  }
References v8::internal::ZoneVector< T >::end().
rbegin() [2/2]
template<typename T >
reverse_iterator v8::internal::ZoneVector< T >::rbegin () [inline]
Definition at line 284 of file zone-containers.h.
                                        {
    return std::make_reverse_iterator(end());
  }
References v8::internal::ZoneVector< T >::end().
Referenced by v8::internal::maglev::Graph::rbegin(), and v8::internal::compiler::InstructionSelector::SelectInstructions().
rend() [1/2]
template<typename T >
const_reverse_iterator v8::internal::ZoneVector< T >::rend () const [inline]
Definition at line 296 of file zone-containers.h.
                                                  {
    return std::make_reverse_iterator(begin());
  }
References v8::internal::ZoneVector< T >::begin().
rend() [2/2]
template<typename T >
reverse_iterator v8::internal::ZoneVector< T >::rend () [inline]
Definition at line 293 of file zone-containers.h.
                                      {
    return std::make_reverse_iterator(begin());
  }
References v8::internal::ZoneVector< T >::begin().
Referenced by v8::internal::maglev::Graph::rend(), and v8::internal::compiler::InstructionSelector::SelectInstructions().
reserve()
template<typename T >
void v8::internal::ZoneVector< T >::reserve (size_t new_cap) [inline]
Definition at line 241 of file zone-containers.h.
{ EnsureCapacity(new_cap); }
References v8::internal::ZoneVector< T >::EnsureCapacity().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::interpreter::BytecodeArrayRandomIterator::BytecodeArrayRandomIterator(), v8::internal::interpreter::BytecodeArrayWriter::BytecodeArrayWriter(), v8::internal::compiler::CallBuffer::CallBuffer(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::turboshaft::anonymous_namespace{decompression-optimization.cc}::DecompressionAnalyzer::DecompressionAnalyzer(), v8::internal::compiler::LoopFinderImpl::FinishLoopTree(), v8::internal::compiler::LoopFinderImpl::FinishSingleLoop(), v8::internal::Module::GetModuleNamespace(), v8::internal::maglev::Graph::Graph(), v8::internal::compiler::GraphTrimmer::GraphTrimmer(), v8::internal::EhFrameWriter::Initialize(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::InstructionSelector::InstructionSelector(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::RegExpBytecodePeephole(), v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier(), v8::internal::compiler::Schedule::Schedule(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
resize() [1/2]
template<typename T >
void v8::internal::ZoneVector< T >::resize (size_t new_size) [inline]
Definition at line 200 of file zone-containers.h.
                               {
    EnsureCapacity(new_size);
    T* new_end = data_ + new_size;
    for (T* p = end_; p < new_end; p++) emplace(p);
    for (T* p = new_end; p < end_; p++) p->~T();
    end_ = new_end;
  }
References v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, and v8::internal::ZoneVector< T >::EnsureCapacity().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::ApplyPatches(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::RegExpBytecodeGenerator::ExpandBuffer(), v8::internal::maglev::MaglevGraphBuilder::FlushNodesToBlock(), v8::internal::compiler::BytecodeGraphBuilder::GetParameter(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::StateValuesCache::GetWorkingSpace(), v8::internal::compiler::turboshaft::InitVectorOf(), v8::internal::compiler::turboshaft::PhiOp::inputs_rep(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::inputs_rep(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), v8::internal::maglev::Graph::IterateGraphAndSweepDeadBlocks(), v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::interpreter::BytecodeArrayWriter::MaybeElideLastBytecode(), v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode(), v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessBasicBlock(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessGraph(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::SourceTextModuleDescriptor::SerializeRegularExports(), v8::internal::compiler::Schedule::SetBlockForNode(), v8::internal::compiler::InstructionSelector::SetRename(), v8::internal::maglev::BasicBlock::Split(), and v8::internal::maglev::MaglevInliner::TruncateGraphAt().
resize() [2/2]
template<typename T >
void v8::internal::ZoneVector< T >::resize (size_t new_size, const T & value) [inline]
Definition at line 208 of file zone-containers.h.
                                               {
    EnsureCapacity(new_size);
    T* new_end = data_ + new_size;
    for (T* p = end_; p < new_end; p++) emplace(p, value);
    for (T* p = new_end; p < end_; p++) p->~T();
    end_ = new_end;
  }
References v8::internal::ZoneVector< T >::data_, v8::internal::ZoneVector< T >::emplace(), v8::internal::ZoneVector< T >::end_, v8::internal::ZoneVector< T >::EnsureCapacity(), and v8::internal::value.
size()
template<typename T >
size_t v8::internal::ZoneVector< T >::size () const [inline]
Definition at line 238 of file zone-containers.h.
{ return end_ - data_; }
References v8::internal::ZoneVector< T >::data_, and v8::internal::ZoneVector< T >::end_.
Referenced by v8::internal::compiler::InstructionSequence::AddDeoptimizationEntry(), v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::InstructionSequence::AddInstruction(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllPackableOperator(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllSameAddress(), v8::internal::compiler::JumpThreading::ApplyForwarding(), v8::internal::maglev::StraightForwardRegisterAllocator::ApplyPatches(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::compiler::CodeGenerator::AssembleTailCallBeforeGap(), v8::internal::ZoneVector< T >::assign(), v8::internal::Variable::AssignHoleCheckBitmapIndex(), v8::internal::compiler::OperandAssigner::AssignSpillSlots(), v8::internal::ZoneVector< T >::at(), v8::internal::interpreter::BytecodeArrayWriter::BindHandlerTarget(), v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry(), v8::internal::interpreter::BytecodeArrayWriter::BindLabel(), v8::internal::interpreter::BytecodeArrayWriter::BindLoopHeader(), v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionEnd(), v8::internal::interpreter::BytecodeArrayWriter::BindTryRegionStart(), v8::internal::compiler::Schedule::block(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildPropertyLoad(), v8::internal::compiler::BytecodeGraphBuilder::BuildSwitchOnGeneratorState(), v8::internal::compiler::SLPTree::BuildTreeRec(), v8::internal::compiler::SLPTree::CanBePacked(), v8::internal::compiler::Schedule::ClearBlockById(), v8::internal::compiler::SpecialRPONumberer::ComputeAndInsertSpecialRPO(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::LoopTree::ContainingLoop(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::compiler::NodeCopier::CopyNodes(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::compiler::BytecodeGraphBuilder::CreateGraph(), v8::internal::ZoneVectorWrapper::Inner::data_length(), v8::internal::compiler::Revectorizer::DecideVectorize(), v8::internal::compiler::InstructionSelector::CachedStateValues::Emit(), v8::internal::RegExpBytecodeGenerator::Emit16(), v8::internal::RegExpBytecodeGenerator::Emit32(), v8::internal::RegExpBytecodeGenerator::Emit8(), v8::internal::interpreter::BytecodeArrayWriter::EmitJump(), v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), v8::internal::compiler::InstructionSelector::EmitPrepareArguments(), v8::internal::interpreter::BytecodeArrayWriter::EmitSwitch(), v8::internal::compiler::InstructionSelector::EmitWithContinuation(), v8::internal::compiler::InstructionSequence::EndBlock(), v8::internal::compiler::BytecodeGraphBuilder::Environment::Environment(), v8::internal::RegExpBytecodeGenerator::ExpandBuffer(), v8::internal::compiler::AccessInfoFactory::FinalizePropertyAccessInfosAsOne(), v8::internal::maglev::MaglevGraphBuilder::FinishInlinedBlockForCaller(), v8::internal::maglev::MaglevGraphBuilder::FlushNodesToBlock(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::FlushPendingPushRegisters(), v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::FlushPendingPushRegisters(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::FlushPendingPushRegisters(), v8::internal::compiler::Schedule::GetBlockById(), v8::internal::compiler::InstructionSelector::GetEffectLevel(), v8::internal::EhFrameWriter::GetEhFrame(), v8::internal::compiler::fast_api_call::GetFastApiCallTarget(), v8::internal::Module::GetModuleNamespace(), v8::internal::compiler::SpillPlacer::GetOrCreateIndexForLatestVreg(), v8::internal::compiler::BytecodeGraphBuilder::GetParameter(), v8::internal::compiler::CodeGenerator::GetPushCompatibleMoves(), v8::internal::compiler::InstructionSelector::GetRename(), v8::internal::compiler::InstructionSequence::GetRepresentation(), v8::internal::compiler::InstructionSelector::GetVirtualRegister(), v8::internal::compiler::InstructionSelector::GetVirtualRegistersForTesting(), v8::internal::compiler::StateValuesCache::GetWorkingSpace(), v8::internal::ZoneVector< T >::Grow(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::NodeCopier::Insert(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::RegisterAllocationData::IsBlockBoundary(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsContinuousAccess(), v8::internal::compiler::Schedule::IsScheduled(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::interpreter::BytecodeArrayRandomIterator::IsValid(), v8::internal::maglev::Graph::IterateGraphAndSweepDeadBlocks(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::AllNodes::Mark(), v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::interpreter::BytecodeArrayWriter::MaybeElideLastBytecode(), v8::internal::compiler::MemoryOptimizer::MergeStates(), v8::internal::compiler::Schedule::NewBasicBlock(), v8::internal::FactoryBase< Impl >::NewCoverageInfo(), v8::internal::compiler::SLPTree::NewPackNodeAndRecurs(), v8::internal::maglev::Graph::num_blocks(), v8::internal::compiler::LoopFinderImpl::num_nodes(), v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode(), v8::internal::compiler::operator<<(), v8::internal::ZoneVector< T >::operator=(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::RegExpBytecodePeephole::pc(), v8::internal::compiler::RegisterAllocationData::PhiMapValue::PhiMapValue(), v8::internal::compiler::SLPTree::PopStack(), v8::internal::maglev::MaglevPhiRepresentationSelector::PostProcessBasicBlock(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::PreProcessGraph(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledGraph(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForKeyedPropertyAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::ElementAccessFeedback::Refine(), v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier(), v8::internal::Variable::RememberHoleCheckInBitmap(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::ZonePreparseData::Serialize(), v8::internal::compiler::LoopFinderImpl::SerializeLoop(), v8::internal::SourceTextModuleDescriptor::SerializeRegularExports(), v8::internal::compiler::Schedule::SetBlockForNode(), v8::internal::compiler::Revectorizer::SetEffectInput(), v8::internal::compiler::InstructionSelector::SetEffectLevel(), v8::internal::compiler::InstructionSelector::SetRename(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::ShiftBySameScalar(), v8::internal::FrameTranslationBuilder::Size(), v8::internal::maglev::BasicBlock::Split(), v8::internal::compiler::SLPTree::StackTopIsPhi(), v8::internal::compiler::InstructionSequence::StartBlock(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::compiler::SwitchInfo::SwitchInfo(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_copy(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::table_get(), v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray(), v8::internal::FrameTranslationBuilder::ToFrameTranslation(), v8::internal::SourcePositionTableBuilder::ToSourcePositionTable(), v8::internal::compiler::GraphTrimmer::TrimGraph(), v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildNamedAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicElementAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPolymorphicPropertyAccess(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainShared(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), v8::internal::compiler::Revectorizer::TryRevectorize(), v8::internal::compiler::CommonOperatorBuilder::TypedObjectState(), v8::internal::compiler::CommonOperatorBuilder::TypedStateValues(), v8::internal::interpreter::BytecodeArrayWriter::UpdateSourcePositionTable(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFunction(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateFunctionParams(), v8::internal::compiler::Revectorizer::VectorizeTree(), v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves(), v8::internal::compiler::InstructionSelector::VisitBlock(), v8::internal::compiler::InstructionSelector::VisitCall(), v8::internal::compiler::InstructionSelector::VisitControl(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::InstructionSelector::VisitTailCall(), v8::internal::wasm::WasmModuleBuilder::WriteTo(), and v8::internal::ZoneVector< T >::ZoneVector().
swap()
template<typename T >
void v8::internal::ZoneVector< T >::swap (ZoneVector< T > & other) [inline], [noexcept]
Definition at line 193 of file zone-containers.h.
                                           {
    DCHECK_EQ(zone_, other.zone_);
    std::swap(data_, other.data_);
    std::swap(end_, other.end_);
    std::swap(capacity_, other.capacity_);
  }
References v8::internal::ZoneVector< T >::capacity_, v8::internal::ZoneVector< T >::data_, DCHECK_EQ, v8::internal::ZoneVector< T >::end_, and v8::internal::ZoneVector< T >::zone_.
zone()
template<typename T >
Zone* v8::internal::ZoneVector< T >::zone () const [inline]
Definition at line 244 of file zone-containers.h.
{ return zone_; }
References v8::internal::ZoneVector< T >::zone_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::zone(), and v8::internal::ZoneVector< T >::ZoneVector().
Member Data Documentation
capacity_
template<typename T >
T* v8::internal::ZoneVector< T >::capacity_ {nullptr} [private]
Definition at line 578 of file zone-containers.h.
Referenced by v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::EnsureOneMoreCapacity(), v8::internal::ZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::NewCapacity(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::ZoneVector< T >::swap(), and v8::internal::ZoneVector< T >::ZoneVector().
data_
template<typename T >
T* v8::internal::ZoneVector< T >::data_ {nullptr} [private]
Definition at line 576 of file zone-containers.h.
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::at(), v8::internal::ZoneVector< T >::back(), v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::capacity(), v8::internal::ZoneVector< T >::cbegin(), v8::internal::ZoneVector< T >::clear(), v8::internal::ZoneVector< T >::data(), v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::erase(), v8::internal::ZoneVector< T >::front(), v8::internal::ZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::NewCapacity(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::pop_back(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), v8::internal::ZoneVector< T >::swap(), v8::internal::ZoneVector< T >::ZoneVector(), and v8::internal::ZoneVector< T >::~ZoneVector().
end_
template<typename T >
T* v8::internal::ZoneVector< T >::end_ {nullptr} [private]
Definition at line 577 of file zone-containers.h.
Referenced by v8::internal::ZoneVector< T >::assign(), v8::internal::ZoneVector< T >::back(), v8::internal::ZoneVector< T >::cend(), v8::internal::ZoneVector< T >::clear(), v8::internal::ZoneVector< T >::emplace_back(), v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::EnsureOneMoreCapacity(), v8::internal::ZoneVector< T >::erase(), v8::internal::ZoneVector< T >::front(), v8::internal::ZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::insert(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::pop_back(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), v8::internal::ZoneVector< T >::swap(), v8::internal::ZoneVector< T >::ZoneVector(), and v8::internal::ZoneVector< T >::~ZoneVector().
kMinCapacity
template<typename T >
constexpr size_t v8::internal::ZoneVector< T >::kMinCapacity = 2 [static], [constexpr], [private]
Definition at line 382 of file zone-containers.h.
Referenced by v8::internal::ZoneVector< T >::NewCapacity().
zone_
template<typename T >
Zone* v8::internal::ZoneVector< T >::zone_ {nullptr} [private]
Definition at line 575 of file zone-containers.h.
Referenced by v8::internal::ZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::ZoneVector< T >::swap(), v8::internal::ZoneVector< T >::zone(), and v8::internal::ZoneVector< T >::~ZoneVector().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-cache.h
/mnt/V8SourceCode/src/zone/zone-containers.h