v8::CppHeap Class Reference
A heap for allocating managed C++ objects.
#include <v8-cppgc.h>
Public Member Functions
virtual ~CppHeap ()=default
cppgc::AllocationHandle & GetAllocationHandle ()
cppgc::HeapHandle & GetHeapHandle ()
void Terminate ()
Terminate clears all roots and performs multiple garbage collections to reclaim potentially newly created objects in destructors.
cppgc::HeapStatistics CollectStatistics (cppgc::HeapStatistics::DetailLevel detail_level)
void CollectCustomSpaceStatisticsAtLastGC (std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver)
Collects statistics for the given spaces and reports them to the receiver.
void EnableDetachedGarbageCollectionsForTesting ()
Enables a detached mode that allows testing garbage collection using cppgc::testing APIs.
void CollectGarbageForTesting (cppgc::EmbedderStackState stack_state)
Performs a stop-the-world garbage collection for testing purposes.
void CollectGarbageInYoungGenerationForTesting (cppgc::EmbedderStackState stack_state)
Performs a stop-the-world minor garbage collection for testing purposes.
Static Public Member Functions
static std::unique_ptr< CppHeap > Create (v8::Platform *platform, const CppHeapCreateParams &params)
Private Member Functions
CppHeap ()=default
Friends
class internal::CppHeap
Detailed Description
A heap for allocating managed C++ objects.
Similar to v8::Isolate, the heap may only be accessed from one thread at a time. The heap may be used from different threads using the v8::Locker/v8::Unlocker APIs which is different from generic Oilpan.
Definition at line 65 of file v8-cppgc.h.
Constructor & Destructor Documentation
 CppHeap()
virtual v8::CppHeap::~CppHeap () [virtual], [default]
Reimplemented in v8::internal::CppHeap.
CppHeap()
v8::CppHeap::CppHeap () [private], [default]
Member Function Documentation
CollectCustomSpaceStatisticsAtLastGC()
void v8::CppHeap::CollectCustomSpaceStatisticsAtLastGC (std::vector< cppgc::CustomSpaceIndex > custom_spaces, std::unique_ptr< CustomSpaceStatisticsReceiver > receiver)
Collects statistics for the given spaces and reports them to the receiver.
Parameters
custom_spaces a collection of custom space indices.
receiver an object that gets the results.
Definition at line 126 of file cpp-heap.cc.
                                                           {
  return internal::CppHeap::From(this)->CollectCustomSpaceStatisticsAtLastGC(
      std::move(custom_spaces), std::move(receiver));
}
References v8::internal::CppHeap::CollectCustomSpaceStatisticsAtLastGC(), and v8::internal::CppHeap::From().
CollectGarbageForTesting()
void v8::CppHeap::CollectGarbageForTesting (cppgc::EmbedderStackState stack_state)
Performs a stop-the-world garbage collection for testing purposes.
Parameters
stack_state The stack state to assume for the garbage collection.
Definition at line 138 of file cpp-heap.cc.
                                                                          {
  return internal::CppHeap::From(this)->CollectGarbageForTesting(
      internal::CppHeap::CollectionType::kMajor, stack_state);
}
References v8::internal::CppHeap::CollectGarbageForTesting(), v8::internal::CppHeap::From(), and cppgc::internal::kMajor.
CollectGarbageInYoungGenerationForTesting()
void v8::CppHeap::CollectGarbageInYoungGenerationForTesting (cppgc::EmbedderStackState stack_state)
Performs a stop-the-world minor garbage collection for testing purposes.
Parameters
stack_state The stack state to assume for the garbage collection.
Definition at line 143 of file cpp-heap.cc.
                                         {
  return internal::CppHeap::From(this)->CollectGarbageForTesting(
      internal::CppHeap::CollectionType::kMinor, stack_state);
}
References v8::internal::CppHeap::CollectGarbageForTesting(), v8::internal::CppHeap::From(), and cppgc::internal::kMinor.
CollectStatistics()
cppgc::HeapStatistics v8::CppHeap::CollectStatistics (cppgc::HeapStatistics::DetailLevel detail_level)
Parameters
detail_level specifies whether should return detailed statistics or only brief summary statistics.
Returns
current CppHeap statistics regarding memory consumption and utilization.
Definition at line 120 of file cpp-heap.cc.
                                                 {
  return internal::CppHeap::From(this)->AsBase().CollectStatistics(
      detail_level);
}
References v8::internal::CppHeap::AsBase(), cppgc::internal::HeapBase::CollectStatistics(), and v8::internal::CppHeap::From().
Create()
std::unique_ptr< CppHeap > v8::CppHeap::Create (v8::Platform * platform, const CppHeapCreateParams & params) [static]
Definition at line 103 of file cpp-heap.cc.
                                                                            {
  return std::make_unique<internal::CppHeap>(platform, params.custom_spaces,
                                             params.marking_support,
                                             params.sweeping_support);
}
References v8::CppHeapCreateParams::custom_spaces, v8::CppHeapCreateParams::marking_support, and v8::CppHeapCreateParams::sweeping_support.
Referenced by v8::Isolate::Initialize().
EnableDetachedGarbageCollectionsForTesting()
void v8::CppHeap::EnableDetachedGarbageCollectionsForTesting ()
Enables a detached mode that allows testing garbage collection using cppgc::testing APIs.
Once used, the heap cannot be attached to an Isolate anymore.
Definition at line 133 of file cpp-heap.cc.
                                                         {
  return internal::CppHeap::From(this)
      ->EnableDetachedGarbageCollectionsForTesting();
}
References v8::internal::CppHeap::EnableDetachedGarbageCollectionsForTesting(), and v8::internal::CppHeap::From().
GetAllocationHandle()
cppgc::AllocationHandle & v8::CppHeap::GetAllocationHandle ()
Returns
the opaque handle for allocating objects using MakeGarbageCollected().
Definition at line 110 of file cpp-heap.cc.
                                                    {
  return internal::CppHeap::From(this)->object_allocator();
}
References v8::internal::CppHeap::From(), and cppgc::internal::HeapBase::object_allocator().
GetHeapHandle()
cppgc::HeapHandle & v8::CppHeap::GetHeapHandle ()
Returns
the opaque heap handle which may be used to refer to this heap in other APIs. Valid as long as the underlying CppHeap is alive.
Definition at line 114 of file cpp-heap.cc.
                                        {
  return *internal::CppHeap::From(this);
}
References v8::internal::CppHeap::From().
Terminate()
void v8::CppHeap::Terminate ()
Terminate clears all roots and performs multiple garbage collections to reclaim potentially newly created objects in destructors.
After this call, object allocation is prohibited.
Definition at line 118 of file cpp-heap.cc.
{ internal::CppHeap::From(this)->Terminate(); }
References v8::internal::CppHeap::From(), and v8::internal::CppHeap::Terminate().
Friends And Related Function Documentation
internal::CppHeap
friend class internal::CppHeap [friend]
Definition at line 137 of file v8-cppgc.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-cppgc.h
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.cc