v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator Class Reference
Public Member Functions
EffectChainIterator (Node *node)
Node * Advance ()
Node * Prev ()
Node * Next ()
void Set (Node *node)
Node * operator* ()
Private Member Functions
Node * EffectInputOf (Node *node)
Private Attributes
Node * node_
Node * prev_
Detailed Description
Definition at line 342 of file revectorizer.cc.
Constructor & Destructor Documentation
EffectChainIterator()
v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::EffectChainIterator (Node * node) [inline], [explicit]
Definition at line 344 of file revectorizer.cc.
: node_(node), prev_(nullptr) {}
Member Function Documentation
Advance()
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::Advance () [inline]
Definition at line 346 of file revectorizer.cc.
                  {
    prev_ = node_;
    node_ = EffectInputOf(node_);
    return node_;
  }
EffectInputOf()
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::EffectInputOf (Node * node) [inline], [private]
Definition at line 367 of file revectorizer.cc.
                                  {
    DCHECK(IsSupportedLoad(node));
    return node->InputAt(2);
  }
References v8::internal::DCHECK(), v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::anonymous_namespace{revectorizer.cc}::IsSupportedLoad().
Next()
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::Next () [inline]
Definition at line 357 of file revectorizer.cc.
{ return EffectInputOf(node_); }
Referenced by v8::internal::compiler::anonymous_namespace{revectorizer.cc}::InsertAfter().
operator*()
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::operator* () [inline]
Definition at line 364 of file revectorizer.cc.
{ return node_; }
Prev()
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::Prev () [inline]
Definition at line 352 of file revectorizer.cc.
               {
    DCHECK_NE(prev_, nullptr);
    return prev_;
  }
References DCHECK_NE.
Referenced by v8::internal::compiler::anonymous_namespace{revectorizer.cc}::InsertAfter().
Set()
void v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::Set (Node * node) [inline]
Definition at line 359 of file revectorizer.cc.
                       {
    node_ = node;
    prev_ = nullptr;
  }
Member Data Documentation
node_
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::node_ [private]
Definition at line 372 of file revectorizer.cc.
prev_
Node* v8::internal::compiler::anonymous_namespace{revectorizer.cc}::EffectChainIterator::prev_ [private]
Definition at line 373 of file revectorizer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/revectorizer.cc