v8::External Class Reference
A JavaScript value that wraps a C++ void*.
#include <v8-external.h>
Public Member Functions
void * Value () const
Static Public Member Functions
static Local< External > New (Isolate *isolate, void *value)
static External * Cast (Value *value)
Static Private Member Functions
static void CheckCast (v8::Value *obj)
Detailed Description
A JavaScript value that wraps a C++ void*.
This type of value is mainly used to associate C++ data structures with JavaScript objects.
Definition at line 19 of file v8-external.h.
Member Function Documentation
Cast()
static External* v8::External::Cast (Value * value) [inline], [static]
Definition at line 22 of file v8-external.h.
                                                {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<External*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::External::CheckCast (v8::Value * obj) [static], [private]
Definition at line 3858 of file api.cc.
                                      {
  Utils::ApiCheck(that->IsExternal(), "v8::External::Cast",
                  "Value is not an External");
}
References v8::Utils::ApiCheck(), and v8::Value::IsExternal().
New()
Local< External > v8::External::New (Isolate * isolate, void * value) [static]
Definition at line 7434 of file api.cc.
                                                                {
  static_assert(sizeof(value) == sizeof(i::Address));
  // Nullptr is not allowed here because serialization/deserialization of
  // nullptr external api references is not possible as nullptr is used as an
  // external_references table terminator, see v8::SnapshotCreator()
  // constructors.
  DCHECK_NOT_NULL(value);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_External_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::JSObject> external =
      i_isolate->factory()->NewExternal(value);
  return Utils::ExternalToLocal(external);
}
References DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::Factory::NewExternal(), and v8::internal::value.
Referenced by v8::Worker::ExecuteInThread(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerSlowCallback(), v8_inspector::V8Console::installAsyncStackTaggingAPI(), v8_inspector::V8Console::installMemoryGetter(), v8_inspector::V8SerializationDuplicateTracker::SetKnownSerializedValue(), v8_inspector::TaskInfo::TaskInfo(), and v8_inspector::V8Console::taskTemplate().
Value()
void * v8::External::Value () const
Definition at line 7449 of file api.cc.
                            {
  i::IsolateForSandbox isolate = i::GetCurrentIsolateForSandbox();
  return i::Cast<i::JSExternalObject>(*Utils::OpenDirectHandle(this))
      ->value(isolate);
}
References v8::internal::GetCurrentIsolateForSandbox(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-external.h
/mnt/V8SourceCode/src/api/api.cc