v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor > Class Template Reference
Public Member Functions
ObjectPinningVisitorBase (const Heap *heap, Scavenger &scavenger, ScavengerCollector::PinnedObjects &pinned_objects)
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
Protected Member Functions
void HandleHeapObject (Tagged< HeapObject > object)
Private Attributes
const Heap *const heap_
Scavenger & scavenger_
ScavengerCollector::PinnedObjects & pinned_objects_
Additional Inherited Members
Detailed Description
template<typename ConcreteVisitor>
class v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >
Definition at line 461 of file scavenger.cc.
Constructor & Destructor Documentation
ObjectPinningVisitorBase()
template<typename ConcreteVisitor >
v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::ObjectPinningVisitorBase (const Heap * heap, Scavenger & scavenger, ScavengerCollector::PinnedObjects & pinned_objects) [inline]
Definition at line 463 of file scavenger.cc.
      : RootVisitor(),
        heap_(heap),
        scavenger_(scavenger),
        pinned_objects_(pinned_objects) {}
Member Function Documentation
HandleHeapObject()
template<typename ConcreteVisitor >
void v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject (Tagged< HeapObject > object) [inline], [protected]
Definition at line 485 of file scavenger.cc.
                                                   {
    DCHECK(!HasWeakHeapObjectTag(object));
    DCHECK(!MapWord::IsPacked(object.ptr()));
    DCHECK(!HeapLayout::IsSelfForwarded(object));
    if (IsAllocationMemento(object)) {
      // Don't pin allocation mementos since they should not survive a GC.
      return;
    }
    if (scavenger_.PromoteIfLargeObject(object)) {
      // Large objects are not moved and thus don't require pinning. Instead,
      // we scavenge large pages eagerly to keep them from being reclaimed (if
      // the page is only reachable from stack).
      return;
    }
    DCHECK(!MemoryChunk::FromHeapObject(object)->IsLargePage());
    DCHECK(HeapLayout::InYoungGeneration(object));
    DCHECK(Heap::InFromPage(object));
    Address object_address = object.address();
    MapWord map_word = object->map_word(kRelaxedLoad);
    DCHECK(!map_word.IsForwardingAddress());
    DCHECK(std::all_of(
        pinned_objects_.begin(), pinned_objects_.end(),
        [object_address](ScavengerCollector::PinnedObjectEntry& entry) {
          return entry.address != object_address;
        }));
    int object_size = object->SizeFromMap(map_word.ToMap());
    DCHECK_LT(0, object_size);
    pinned_objects_.push_back(
        {object_address, map_word, static_cast<size_t>(object_size)});
    MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
    if (!chunk->IsQuarantined()) {
      chunk->SetFlagNonExecutable(MemoryChunk::IS_QUARANTINED);
      if (v8_flags.scavenger_promote_quarantined_pages &&
          heap_->semi_space_new_space()->ShouldPageBePromoted(chunk)) {
        chunk->SetFlagNonExecutable(MemoryChunk::WILL_BE_PROMOTED);
      }
    }
    scavenger_.PinAndPushObject(chunk, object, map_word);
  }
References v8::base::all_of(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HasWeakHeapObjectTag(), v8::internal::Heap::InFromPage(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::IS_QUARANTINED, v8::internal::MapWord::IsForwardingAddress(), v8::internal::MapWord::IsPacked(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::HeapLayout::IsSelfForwarded(), v8::kRelaxedLoad, v8::internal::MemoryChunk::SetFlagNonExecutable(), v8::internal::MapWord::ToMap(), v8::internal::v8_flags, and v8::internal::MemoryChunk::WILL_BE_PROMOTED.
VisitRootPointer()
template<typename ConcreteVisitor >
void v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 470 of file scavenger.cc.
                                                {
    DCHECK(root == Root::kStackRoots || root == Root::kHandleScope);
    static_cast<ConcreteVisitor*>(this)->HandlePointer(p);
  }
References v8::internal::DCHECK().
VisitRootPointers()
template<typename ConcreteVisitor >
void v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 476 of file scavenger.cc.
                                                                         {
    DCHECK(root == Root::kStackRoots || root == Root::kHandleScope);
    for (FullObjectSlot p = start; p < end; ++p) {
      static_cast<ConcreteVisitor*>(this)->HandlePointer(p);
    }
  }
References v8::internal::DCHECK(), and v8::internal::compiler::end().
Member Data Documentation
heap_
template<typename ConcreteVisitor >
const Heap* const v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::heap_ [private]
Definition at line 526 of file scavenger.cc.
pinned_objects_
template<typename ConcreteVisitor >
ScavengerCollector::PinnedObjects& v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::pinned_objects_ [private]
Definition at line 528 of file scavenger.cc.
scavenger_
template<typename ConcreteVisitor >
Scavenger& v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::scavenger_ [private]
Definition at line 527 of file scavenger.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/scavenger.cc