v8::internal::compiler::JSSetKeyedPropertyNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSSetKeyedPropertyNode (Node *node)
const PropertyAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1311 of file js-operator.h.
Constructor & Destructor Documentation
JSSetKeyedPropertyNode()
constexpr v8::internal::compiler::JSSetKeyedPropertyNode::JSSetKeyedPropertyNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1313 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSSetKeyedProperty, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const PropertyAccess& v8::internal::compiler::JSSetKeyedPropertyNode::Parameters () const [inline]
Definition at line 1318 of file js-operator.h.
                                           {
    return PropertyAccessOf(node()->op());
  }
References v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::PropertyAccessOf().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSSetKeyedProperty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h