v8::internal::ArrayBufferSweeper Class Reference
#include <array-buffer-sweeper.h>
Classes
class SweepingState
Public Types
enum class SweepingType { kYoung
, kFull
 }
enum class TreatAllYoungAsPromoted { kNo
, kYes
 }
Public Member Functions
ArrayBufferSweeper (Heap *heap)
~ArrayBufferSweeper ()
void RequestSweep (SweepingType sweeping_type, TreatAllYoungAsPromoted treat_all_young_as_promoted)
void EnsureFinished ()
void Append (ArrayBufferExtension *extension)
void Resize (ArrayBufferExtension *extension, int64_t delta)
void Detach (ArrayBufferExtension *extension)
const ArrayBufferList & young () const
const ArrayBufferList & old () const
size_t YoungBytes () const
size_t OldBytes () const
bool sweeping_in_progress () const
uint64_t GetTraceIdForFlowEvent (GCTracer::Scope::ScopeId scope_id) const
Private Member Functions
void FinishIfDone ()
void Finish ()
void UpdateApproximateBytes (int64_t delta, ArrayBufferExtension::Age age)
void IncrementExternalMemoryCounters (size_t bytes)
void DecrementExternalMemoryCounters (size_t bytes)
void Prepare (SweepingType type, TreatAllYoungAsPromoted treat_all_young_as_promoted, uint64_t trace_id)
void Finalize ()
void ReleaseAll (ArrayBufferList *extension)
Static Private Member Functions
static void FinalizeAndDelete (ArrayBufferExtension *extension)
Private Attributes
Heap *const heap_
std::unique_ptr< SweepingState > state_
ArrayBufferList young_ {ArrayBufferList::Age::kYoung}
ArrayBufferList old_ {ArrayBufferList::Age::kOld}
int64_t young_bytes_adjustment_while_sweeping_ {0}
int64_t old_bytes_adjustment_while_sweeping_ {0}
V8_NO_UNIQUE_ADDRESS ExternalMemoryAccounter external_memory_accounter_
Detailed Description
Definition at line 54 of file array-buffer-sweeper.h.
Member Enumeration Documentation
SweepingType
enum v8::internal::ArrayBufferSweeper::SweepingType [strong]
Enumerator
kYoung
kFull
Definition at line 56 of file array-buffer-sweeper.h.
{ kYoung, kFull };
TreatAllYoungAsPromoted
enum v8::internal::ArrayBufferSweeper::TreatAllYoungAsPromoted [strong]
Enumerator
kNo
kYes
Definition at line 57 of file array-buffer-sweeper.h.
{ kNo, kYes };
Constructor & Destructor Documentation
ArrayBufferSweeper()
v8::internal::ArrayBufferSweeper::ArrayBufferSweeper (Heap * heap) [explicit]
Definition at line 251 of file array-buffer-sweeper.cc.
: heap_(heap) {}
 ArrayBufferSweeper()
v8::internal::ArrayBufferSweeper::~ArrayBufferSweeper ()
Definition at line 253 of file array-buffer-sweeper.cc.
                                        {
  EnsureFinished();
  ReleaseAll(&old_);
  ReleaseAll(&young_);
}
References EnsureFinished(), old_, ReleaseAll(), and young_.
Member Function Documentation
Append()
void v8::internal::ArrayBufferSweeper::Append (ArrayBufferExtension * extension)
Definition at line 354 of file array-buffer-sweeper.cc.
                                                               {
  size_t bytes = extension->accounting_length();
  FinishIfDone();
  switch (extension->age()) {
    case ArrayBufferExtension::Age::kYoung:
      young_.Append(extension);
      break;
    case v8::internal::ArrayBufferExtension::Age::kOld:
      old_.Append(extension);
      break;
  }
  IncrementExternalMemoryCounters(bytes);
}
References v8::internal::ArrayBufferExtension::accounting_length(), v8::internal::ArrayBufferExtension::age(), v8::internal::ArrayBufferList::Append(), FinishIfDone(), IncrementExternalMemoryCounters(), v8::internal::ArrayBufferExtension::kOld, v8::internal::ArrayBufferExtension::kYoung, old_, and young_.
DecrementExternalMemoryCounters()
void v8::internal::ArrayBufferSweeper::DecrementExternalMemoryCounters (size_t bytes) [private]
Definition at line 430 of file array-buffer-sweeper.cc.
                                                                     {
  if (bytes == 0) return;
  heap_->DecrementExternalBackingStoreBytes(
      ExternalBackingStoreType::kArrayBuffer, bytes);
  external_memory_accounter_.Decrease(
      reinterpret_cast<v8::Isolate*>(heap_->isolate()), bytes);
}
References v8::ExternalMemoryAccounter::Decrease(), v8::internal::Heap::DecrementExternalBackingStoreBytes(), external_memory_accounter_, heap_, v8::internal::Heap::isolate(), and v8::internal::kArrayBuffer.
Referenced by Detach(), v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), ReleaseAll(), and Resize().
Detach()
void v8::internal::ArrayBufferSweeper::Detach (ArrayBufferExtension * extension)
Definition at line 385 of file array-buffer-sweeper.cc.
                                                               {
  // Finish sweeping here first such that the code below is guaranteed to
  // observe the same sweeping state.
  FinishIfDone();
  ArrayBufferExtension::AccountingState previous_value =
      extension->ClearAccountingLength();
  // We cannot free the extension eagerly here, since extensions are tracked in
  // a singly linked list. The next GC will remove it automatically.
  UpdateApproximateBytes(-previous_value.accounting_length(),
                         previous_value.age());
  DecrementExternalMemoryCounters(previous_value.accounting_length());
}
References v8::internal::ArrayBufferExtension::AccountingState::accounting_length(), v8::internal::ArrayBufferExtension::AccountingState::age(), v8::internal::ArrayBufferExtension::ClearAccountingLength(), DecrementExternalMemoryCounters(), FinishIfDone(), and UpdateApproximateBytes().
EnsureFinished()
void v8::internal::ArrayBufferSweeper::EnsureFinished ()
Definition at line 259 of file array-buffer-sweeper.cc.
                                        {
  if (!sweeping_in_progress()) return;
  Finish();
}
References Finish(), and sweeping_in_progress().
Referenced by v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), and ~ArrayBufferSweeper().
Finalize()
void v8::internal::ArrayBufferSweeper::Finalize () [private]
Definition at line 334 of file array-buffer-sweeper.cc.
                                  {
  DCHECK(sweeping_in_progress());
  CHECK(state_->IsDone());
  state_->MergeTo(this);
  state_.reset();
  DCHECK(!sweeping_in_progress());
}
References CHECK, v8::internal::DCHECK(), state_, and sweeping_in_progress().
Referenced by Finish().
FinalizeAndDelete()
void v8::internal::ArrayBufferSweeper::FinalizeAndDelete (ArrayBufferExtension * extension) [static], [private]
Definition at line 438 of file array-buffer-sweeper.cc.
                                                                          {
#ifdef V8_COMPRESS_POINTERS
  extension->ZapExternalPointerTableEntry();
#endif // V8_COMPRESS_POINTERS
  delete extension;
}
Referenced by ReleaseAll(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
Finish()
void v8::internal::ArrayBufferSweeper::Finish () [private]
Definition at line 265 of file array-buffer-sweeper.cc.
                                {
  state_->FinishSweeping();
  Finalize();
  DCHECK_LE(heap_->backing_store_bytes(), SIZE_MAX);
  DCHECK(!sweeping_in_progress());
}
References v8::internal::Heap::backing_store_bytes(), v8::internal::DCHECK(), DCHECK_LE, Finalize(), heap_, state_, and sweeping_in_progress().
Referenced by EnsureFinished(), FinishIfDone(), and RequestSweep().
FinishIfDone()
void v8::internal::ArrayBufferSweeper::FinishIfDone () [private]
Definition at line 273 of file array-buffer-sweeper.cc.
                                      {
  if (sweeping_in_progress()) {
    DCHECK(state_);
    if (state_->IsDone()) {
      Finish();
    }
  }
}
References v8::internal::DCHECK(), Finish(), state_, and sweeping_in_progress().
Referenced by Append(), Detach(), and Resize().
GetTraceIdForFlowEvent()
uint64_t v8::internal::ArrayBufferSweeper::GetTraceIdForFlowEvent (GCTracer::Scope::ScopeId scope_id) const
Definition at line 565 of file array-buffer-sweeper.cc.
                                         {
  return reinterpret_cast<uint64_t>(this) ^
         heap_->tracer()->CurrentEpoch(scope_id);
}
References v8::internal::GCTracer::CurrentEpoch(), heap_, and v8::internal::Heap::tracer().
Referenced by v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), and RequestSweep().
IncrementExternalMemoryCounters()
void v8::internal::ArrayBufferSweeper::IncrementExternalMemoryCounters (size_t bytes) [private]
Definition at line 422 of file array-buffer-sweeper.cc.
                                                                     {
  if (bytes == 0) return;
  heap_->IncrementExternalBackingStoreBytes(
      ExternalBackingStoreType::kArrayBuffer, bytes);
  external_memory_accounter_.Increase(
      reinterpret_cast<v8::Isolate*>(heap_->isolate()), bytes);
}
References external_memory_accounter_, heap_, v8::ExternalMemoryAccounter::Increase(), v8::internal::Heap::IncrementExternalBackingStoreBytes(), v8::internal::Heap::isolate(), and v8::internal::kArrayBuffer.
Referenced by Append(), and Resize().
old()
const ArrayBufferList& v8::internal::ArrayBufferSweeper::old () const [inline]
Definition at line 75 of file array-buffer-sweeper.h.
{ return old_; }
References old_.
Referenced by OldBytes().
OldBytes()
size_t v8::internal::ArrayBufferSweeper::OldBytes () const [inline]
Definition at line 80 of file array-buffer-sweeper.h.
{ return old().ApproximateBytes(); }
References v8::internal::ArrayBufferList::ApproximateBytes(), and old().
Referenced by v8::internal::Heap::OldArrayBufferBytes().
Prepare()
void v8::internal::ArrayBufferSweeper::Prepare (SweepingType type, TreatAllYoungAsPromoted treat_all_young_as_promoted, uint64_t trace_id) [private]
Definition at line 310 of file array-buffer-sweeper.cc.
                       {
  DCHECK(!sweeping_in_progress());
  DCHECK_IMPLIES(type == SweepingType::kFull,
                 treat_all_young_as_promoted == TreatAllYoungAsPromoted::kYes);
  switch (type) {
    case SweepingType::kYoung: {
      state_ = std::make_unique<SweepingState>(
          heap_, std::move(young_), ArrayBufferList(ArrayBufferList::Age::kOld),
          type, treat_all_young_as_promoted, trace_id);
      young_ = ArrayBufferList(ArrayBufferList::Age::kYoung);
    } break;
    case SweepingType::kFull: {
      state_ = std::make_unique<SweepingState>(
          heap_, std::move(young_), std::move(old_), type,
          treat_all_young_as_promoted, trace_id);
      young_ = ArrayBufferList(ArrayBufferList::Age::kYoung);
      old_ = ArrayBufferList(ArrayBufferList::Age::kOld);
    } break;
  }
  DCHECK(sweeping_in_progress());
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, heap_, kFull, v8::internal::ArrayBufferExtension::kOld, kYes, kYoung, v8::internal::ArrayBufferExtension::kYoung, old_, state_, sweeping_in_progress(), v8::internal::tracing::type, and young_.
Referenced by RequestSweep().
ReleaseAll()
void v8::internal::ArrayBufferSweeper::ReleaseAll (ArrayBufferList * extension) [private]
Definition at line 342 of file array-buffer-sweeper.cc.
                                                         {
  ArrayBufferExtension* current = list->head_;
  while (current) {
    ArrayBufferExtension* next = current->next();
    const size_t bytes = current->ClearAccountingLength().accounting_length();
    DecrementExternalMemoryCounters(bytes);
    FinalizeAndDelete(current);
    current = next;
  }
  *list = ArrayBufferList(list->age_);
}
References v8::internal::ArrayBufferExtension::AccountingState::accounting_length(), v8::internal::ArrayBufferList::age_, v8::internal::ArrayBufferExtension::ClearAccountingLength(), DecrementExternalMemoryCounters(), FinalizeAndDelete(), v8::internal::ArrayBufferList::head_, and v8::internal::ArrayBufferExtension::next().
Referenced by ~ArrayBufferSweeper().
RequestSweep()
void v8::internal::ArrayBufferSweeper::RequestSweep (SweepingType sweeping_type, TreatAllYoungAsPromoted treat_all_young_as_promoted)
Definition at line 282 of file array-buffer-sweeper.cc.
                                                                            {
  DCHECK(!sweeping_in_progress());
  if (young_.IsEmpty() && (old_.IsEmpty() || type == SweepingType::kYoung))
    return;
  GCTracer::Scope::ScopeId scope_id =
      type == SweepingType::kYoung
          ? v8_flags.minor_ms
                ? GCTracer::Scope::MINOR_MS_FINISH_SWEEP_ARRAY_BUFFERS
                : GCTracer::Scope::SCAVENGER_SWEEP_ARRAY_BUFFERS
          : GCTracer::Scope::MC_FINISH_SWEEP_ARRAY_BUFFERS;
  auto trace_id = GetTraceIdForFlowEvent(scope_id);
  TRACE_GC_WITH_FLOW(heap_->tracer(), scope_id, trace_id,
                     TRACE_EVENT_FLAG_FLOW_OUT);
  Prepare(type, treat_all_young_as_promoted, trace_id);
  DCHECK_IMPLIES(v8_flags.minor_ms && type == SweepingType::kYoung,
                 !heap_->ShouldReduceMemory());
  if (!heap_->IsTearingDown() && !heap_->ShouldReduceMemory() &&
      v8_flags.concurrent_array_buffer_sweeping &&
      heap_->ShouldUseBackgroundThreads()) {
    state_->StartBackgroundSweeping();
  } else {
    Finish();
  }
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, Finish(), GetTraceIdForFlowEvent(), heap_, v8::internal::ArrayBufferList::IsEmpty(), v8::internal::Heap::IsTearingDown(), kYoung, old_, Prepare(), v8::internal::Heap::ShouldReduceMemory(), v8::internal::Heap::ShouldUseBackgroundThreads(), state_, sweeping_in_progress(), TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_WITH_FLOW, v8::internal::Heap::tracer(), v8::internal::tracing::type, v8::internal::v8_flags, and young_.
Referenced by v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::MarkCompactCollector::SweepArrayBufferExtensions(), and v8::internal::ScavengerCollector::SweepArrayBufferExtensions().
Resize()
void v8::internal::ArrayBufferSweeper::Resize (ArrayBufferExtension * extension, int64_t delta)
Definition at line 371 of file array-buffer-sweeper.cc.
                                               {
  FinishIfDone();
  const ArrayBufferExtension::AccountingState previous_value =
      extension->UpdateAccountingLength(delta);
  UpdateApproximateBytes(delta, previous_value.age());
  if (delta > 0) {
    IncrementExternalMemoryCounters(delta);
  } else {
    DecrementExternalMemoryCounters(-delta);
  }
}
References v8::internal::ArrayBufferExtension::AccountingState::age(), DecrementExternalMemoryCounters(), FinishIfDone(), IncrementExternalMemoryCounters(), v8::internal::ArrayBufferExtension::UpdateAccountingLength(), and UpdateApproximateBytes().
sweeping_in_progress()
bool v8::internal::ArrayBufferSweeper::sweeping_in_progress () const [inline]
Definition at line 82 of file array-buffer-sweeper.h.
{ return state_.get(); }
References state_.
Referenced by v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::anonymous_namespace{heap.cc}::CompleteArrayBufferSweeping(), EnsureFinished(), Finalize(), Finish(), FinishIfDone(), Prepare(), RequestSweep(), and UpdateApproximateBytes().
UpdateApproximateBytes()
void v8::internal::ArrayBufferSweeper::UpdateApproximateBytes (int64_t delta, ArrayBufferExtension::Age age) [private]
Definition at line 401 of file array-buffer-sweeper.cc.
                                                                             {
  switch (age) {
    case ArrayBufferExtension::Age::kYoung:
      if (!sweeping_in_progress()) {
        DCHECK_GE(young_.bytes_, -delta);
        young_.bytes_ += delta;
      } else {
        young_bytes_adjustment_while_sweeping_ += delta;
      }
      break;
    case ArrayBufferExtension::Age::kOld:
      if (!sweeping_in_progress()) {
        DCHECK_GE(old_.bytes_, -delta);
        old_.bytes_ += delta;
      } else {
        old_bytes_adjustment_while_sweeping_ += delta;
      }
  }
}
References v8::internal::ArrayBufferList::bytes_, DCHECK_GE, v8::internal::ArrayBufferExtension::kOld, v8::internal::ArrayBufferExtension::kYoung, old_, old_bytes_adjustment_while_sweeping_, sweeping_in_progress(), young_, and young_bytes_adjustment_while_sweeping_.
Referenced by Detach(), and Resize().
young()
const ArrayBufferList& v8::internal::ArrayBufferSweeper::young () const [inline]
Definition at line 74 of file array-buffer-sweeper.h.
{ return young_; }
References young_.
Referenced by YoungBytes().
YoungBytes()
size_t v8::internal::ArrayBufferSweeper::YoungBytes () const [inline]
Definition at line 78 of file array-buffer-sweeper.h.
{ return young().ApproximateBytes(); }
References v8::internal::ArrayBufferList::ApproximateBytes(), and young().
Referenced by v8::internal::Heap::YoungArrayBufferBytes().
Member Data Documentation
external_memory_accounter_
V8_NO_UNIQUE_ADDRESS ExternalMemoryAccounter v8::internal::ArrayBufferSweeper::external_memory_accounter_ [private]
Definition at line 118 of file array-buffer-sweeper.h.
Referenced by DecrementExternalMemoryCounters(), and IncrementExternalMemoryCounters().
heap_
Heap* const v8::internal::ArrayBufferSweeper::heap_ [private]
Definition at line 109 of file array-buffer-sweeper.h.
Referenced by DecrementExternalMemoryCounters(), Finish(), GetTraceIdForFlowEvent(), IncrementExternalMemoryCounters(), Prepare(), and RequestSweep().
old_
ArrayBufferList v8::internal::ArrayBufferSweeper::old_ {ArrayBufferList::Age::kOld} [private]
Definition at line 112 of file array-buffer-sweeper.h.
Referenced by Append(), v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), old(), Prepare(), RequestSweep(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepFull(), UpdateApproximateBytes(), and ~ArrayBufferSweeper().
old_bytes_adjustment_while_sweeping_
int64_t v8::internal::ArrayBufferSweeper::old_bytes_adjustment_while_sweeping_ {0} [private]
Definition at line 117 of file array-buffer-sweeper.h.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), and UpdateApproximateBytes().
state_
std::unique_ptr<SweepingState> v8::internal::ArrayBufferSweeper::state_ [private]
Definition at line 110 of file array-buffer-sweeper.h.
Referenced by Finalize(), Finish(), FinishIfDone(), Prepare(), RequestSweep(), sweeping_in_progress(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
young_
ArrayBufferList v8::internal::ArrayBufferSweeper::young_ {ArrayBufferList::Age::kYoung} [private]
Definition at line 111 of file array-buffer-sweeper.h.
Referenced by Append(), v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), Prepare(), RequestSweep(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepFull(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung(), UpdateApproximateBytes(), young(), and ~ArrayBufferSweeper().
young_bytes_adjustment_while_sweeping_
int64_t v8::internal::ArrayBufferSweeper::young_bytes_adjustment_while_sweeping_ {0} [private]
Definition at line 116 of file array-buffer-sweeper.h.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::MergeTo(), and UpdateApproximateBytes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/array-buffer-sweeper.h
/mnt/V8SourceCode/src/heap/array-buffer-sweeper.cc