v8::internal::compiler::BytecodeArrayRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< BytecodeArray > object () const
int length () const
int register_count () const
uint16_t parameter_count () const
uint16_t parameter_count_without_receiver () const
uint16_t max_arguments () const
interpreter::Register incoming_new_target_or_generator_register () const
IndirectHandle< TrustedByteArray > SourcePositionTable (JSHeapBroker *broker) const
Address handler_table_address () const
int handler_table_size () const
Detailed Description
Definition at line 1048 of file heap-refs.h.
Member Function Documentation
handler_table_address()
Address v8::internal::compiler::BytecodeArrayRef::handler_table_address () const
Definition at line 1516 of file heap-refs.cc.
                                                      {
  return reinterpret_cast<Address>(object()->handler_table()->begin());
}
References object().
handler_table_size()
int v8::internal::compiler::BytecodeArrayRef::handler_table_size () const
Definition at line 1520 of file heap-refs.cc.
                                               {
  return object()->handler_table()->length();
}
References object().
incoming_new_target_or_generator_register()
interpreter::Register v8::internal::compiler::BytecodeArrayRef::incoming_new_target_or_generator_register () const
Definition at line 1595 of file heap-refs.cc.
                                                                  {
  return object()->incoming_new_target_or_generator_register();
}
References object().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
length()
int v8::internal::compiler::BytecodeArrayRef::length () const
Definition at line 1581 of file heap-refs.cc.
{ return object()->length(); }
References object().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::maglev::MaglevGraphBuilder::ShouldEagerInlineCall(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildInlineCall().
max_arguments()
uint16_t v8::internal::compiler::BytecodeArrayRef::max_arguments () const
Definition at line 1591 of file heap-refs.cc.
                                               {
  return object()->max_arguments();
}
References object().
object()
IndirectHandle<BytecodeArray> v8::internal::compiler::BytecodeArrayRef::object () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), handler_table_address(), handler_table_size(), incoming_new_target_or_generator_register(), length(), max_arguments(), parameter_count(), parameter_count_without_receiver(), v8::internal::compiler::JSInliner::ReduceJSCall(), and register_count().
parameter_count()
uint16_t v8::internal::compiler::BytecodeArrayRef::parameter_count () const
Definition at line 1585 of file heap-refs.cc.
                                                 {
  return object()->parameter_count();
}
References object().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject().
parameter_count_without_receiver()
uint16_t v8::internal::compiler::BytecodeArrayRef::parameter_count_without_receiver () const
Definition at line 1588 of file heap-refs.cc.
                                                                  {
  return object()->parameter_count_without_receiver();
}
References object().
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
register_count()
int v8::internal::compiler::BytecodeArrayRef::register_count () const
Definition at line 1582 of file heap-refs.cc.
                                           {
  return object()->register_count();
}
References object().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject().
SourcePositionTable()
IndirectHandle< TrustedByteArray > v8::internal::compiler::BytecodeArrayRef::SourcePositionTable (JSHeapBroker * broker) const
Definition at line 1511 of file heap-refs.cc.
                                {
  return broker->CanonicalPersistentHandle(object()->SourcePositionTable());
}
References broker().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc