v8::internal::wasm::ITracer Class Reference
#include <decoder.h>
Public Member Functions
virtual void TypeOffset (uint32_t offset)=0
virtual void ImportOffset (uint32_t offset)=0
virtual void ImportsDone (const WasmModule *module)=0
virtual void TableOffset (uint32_t offset)=0
virtual void MemoryOffset (uint32_t offset)=0
virtual void TagOffset (uint32_t offset)=0
virtual void GlobalOffset (uint32_t offset)=0
virtual void StartOffset (uint32_t offset)=0
virtual void ElementOffset (uint32_t offset)=0
virtual void DataOffset (uint32_t offset)=0
virtual void StringOffset (uint32_t offset)=0
virtual void RecGroupOffset (uint32_t offset, uint32_t group_size)=0
virtual void Bytes (const uint8_t *start, uint32_t count)=0
virtual void Description (const char *desc)=0
virtual void Description (const char *desc, size_t length)=0
virtual void Description (uint32_t number)=0
virtual void Description (uint64_t number)=0
virtual void Description (ValueType type)=0
virtual void Description (HeapType type)=0
virtual void Description (const FunctionSig *sig)=0
virtual void NextLine ()=0
virtual void NextLineIfFull ()=0
virtual void NextLineIfNonEmpty ()=0
virtual void InitializerExpression (const uint8_t *start, const uint8_t *end, ValueType expected_type)=0
virtual void FunctionBody (const WasmFunction *func, const uint8_t *start)=0
virtual void FunctionName (uint32_t func_index)=0
virtual void NameSection (const uint8_t *start, const uint8_t *end, uint32_t offset)=0
virtual ~ITracer ()=default
Static Public Attributes
static constexpr ITracer * NoTrace = nullptr
Detailed Description
Definition at line 43 of file decoder.h.
Constructor & Destructor Documentation
 ITracer()
virtual v8::internal::wasm::ITracer::~ITracer () [virtual], [default]
Member Function Documentation
Bytes()
virtual void v8::internal::wasm::ITracer::Bytes (const uint8_t * start, uint32_t count) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_exception_attribute(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_heap_type(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_mutability(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::consume_string(), v8::internal::wasm::Decoder::consume_u32(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u64v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), and v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection().
DataOffset()
virtual void v8::internal::wasm::ITracer::DataOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection().
Description() [1/7]
virtual void v8::internal::wasm::ITracer::Description (const char * desc) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::Decoder::consume_bytes(), v8::internal::wasm::ModuleDecoderImpl::consume_count(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_global_flags(), v8::internal::wasm::ModuleDecoderImpl::consume_heap_type(), v8::internal::wasm::ModuleDecoderImpl::consume_index(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_mutability(), v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::Decoder::consume_u32(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u64v(), v8::internal::wasm::Decoder::consume_u8(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), and v8::internal::wasm::WasmSectionIterator::next().
Description() [2/7]
virtual void v8::internal::wasm::ITracer::Description (const char * desc, size_t length) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Description() [3/7]
virtual void v8::internal::wasm::ITracer::Description (const FunctionSig * sig) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Description() [4/7]
virtual void v8::internal::wasm::ITracer::Description (HeapType type) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Description() [5/7]
virtual void v8::internal::wasm::ITracer::Description (uint32_t number) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Description() [6/7]
virtual void v8::internal::wasm::ITracer::Description (uint64_t number) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Description() [7/7]
virtual void v8::internal::wasm::ITracer::Description (ValueType type) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
ElementOffset()
virtual void v8::internal::wasm::ITracer::ElementOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection().
FunctionBody()
virtual void v8::internal::wasm::ITracer::FunctionBody (const WasmFunction * func, const uint8_t * start) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionBody().
FunctionName()
virtual void v8::internal::wasm::ITracer::FunctionName (uint32_t func_index) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeFunctionSection().
GlobalOffset()
virtual void v8::internal::wasm::ITracer::GlobalOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeGlobalSection().
ImportOffset()
virtual void v8::internal::wasm::ITracer::ImportOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection().
ImportsDone()
virtual void v8::internal::wasm::ITracer::ImportsDone (const WasmModule * module) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection().
InitializerExpression()
virtual void v8::internal::wasm::ITracer::InitializerExpression (const uint8_t * start, const uint8_t * end, ValueType expected_type) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr().
MemoryOffset()
virtual void v8::internal::wasm::ITracer::MemoryOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeMemorySection().
NameSection()
virtual void v8::internal::wasm::ITracer::NameSection (const uint8_t * start, const uint8_t * end, uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection().
NextLine()
virtual void v8::internal::wasm::ITracer::NextLine () [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_array(), v8::internal::wasm::ModuleDecoderImpl::consume_base_type_definition(), v8::internal::wasm::ModuleDecoderImpl::consume_count(), v8::internal::wasm::ModuleDecoderImpl::consume_data_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_described_type(), v8::internal::wasm::ModuleDecoderImpl::consume_describing_type(), v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::ModuleDecoderImpl::consume_limits_byte(), v8::internal::wasm::ModuleDecoderImpl::consume_resizable_limits(), v8::internal::wasm::ModuleDecoderImpl::consume_sig(), v8::internal::wasm::ModuleDecoderImpl::consume_sig_index(), v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::consume_struct(), v8::internal::wasm::ModuleDecoderImpl::consume_subtype_definition(), v8::internal::wasm::ModuleDecoderImpl::DecodeCodeSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeExportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeImportSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeModuleHeader(), v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection(), v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection(), and v8::internal::wasm::WasmSectionIterator::next().
NextLineIfFull()
virtual void v8::internal::wasm::ITracer::NextLineIfFull () [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_sig().
NextLineIfNonEmpty()
virtual void v8::internal::wasm::ITracer::NextLineIfNonEmpty () [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::ModuleDecoderImpl::consume_sig(), v8::internal::wasm::ModuleDecoderImpl::DecodeDataCountSection(), and v8::internal::wasm::ModuleDecoderImpl::DecodeElementSection().
RecGroupOffset()
virtual void v8::internal::wasm::ITracer::RecGroupOffset (uint32_t offset, uint32_t group_size) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection().
StartOffset()
virtual void v8::internal::wasm::ITracer::StartOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeStartSection().
StringOffset()
virtual void v8::internal::wasm::ITracer::StringOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeStringRefSection().
TableOffset()
virtual void v8::internal::wasm::ITracer::TableOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection().
TagOffset()
virtual void v8::internal::wasm::ITracer::TagOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeTagSection().
TypeOffset()
virtual void v8::internal::wasm::ITracer::TypeOffset (uint32_t offset) [pure virtual]
Implemented in v8::internal::wasm::OffsetsProvider.
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeTypeSection().
Member Data Documentation
NoTrace
constexpr ITracer* v8::internal::wasm::ITracer::NoTrace = nullptr [static], [constexpr]
Definition at line 45 of file decoder.h.
Referenced by v8::internal::wasm::consume_string(), v8::internal::wasm::ModuleDecoderImpl::DecodeNameSection(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::FindNameSection(), and v8::internal::wasm::ModuleDecoder::IdentifyUnknownSection().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/decoder.h