v8_inspector::V8DeepSerializer Class Reference
#include <v8-deep-serializer.h>
Public Member Functions
V8DeepSerializer (v8::Isolate *isolate)
Static Public Member Functions
static protocol::Response serializeV8Value (v8::Local< v8::Object > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, protocol::DictionaryValue &result)
Detailed Description
Definition at line 13 of file v8-deep-serializer.h.
Constructor & Destructor Documentation
V8DeepSerializer()
v8_inspector::V8DeepSerializer::V8DeepSerializer (v8::Isolate * isolate) [explicit]
Member Function Documentation
serializeV8Value()
Response v8_inspector::V8DeepSerializer::serializeV8Value (v8::Local< v8::Object > value, v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, protocol::DictionaryValue & result) [static]
Definition at line 294 of file v8-deep-serializer.cc.
                                     {
  if (value->IsArray()) {
    return SerializeArray(value.As<v8::Array>(), context, maxDepth,
                          additionalParameters, duplicateTracker, result);
  }
  if (value->IsRegExp()) {
    return SerializeRegexp(value.As<v8::RegExp>(), context, duplicateTracker,
                           result);
  }
  if (value->IsDate()) {
    return SerializeDate(value.As<v8::Date>(), context, duplicateTracker,
                         result);
  }
  if (value->IsMap()) {
    return SerializeMap(value.As<v8::Map>(), context, maxDepth,
                        additionalParameters, duplicateTracker, result);
  }
  if (value->IsSet()) {
    return SerializeSet(value.As<v8::Set>(), context, maxDepth,
                        additionalParameters, duplicateTracker, result);
  }
  if (value->IsWeakMap()) {
    result.setString("type",
                     protocol::Runtime::DeepSerializedValue::TypeEnum::Weakmap);
    return Response::Success();
  }
  if (value->IsWeakSet()) {
    result.setString("type",
                     protocol::Runtime::DeepSerializedValue::TypeEnum::Weakset);
    return Response::Success();
  }
  if (value->IsNativeError()) {
    result.setString("type",
                     protocol::Runtime::DeepSerializedValue::TypeEnum::Error);
    return Response::Success();
  }
  if (value->IsProxy()) {
    result.setString("type",
                     protocol::Runtime::DeepSerializedValue::TypeEnum::Proxy);
    return Response::Success();
  }
  if (value->IsPromise()) {
    result.setString("type",
                     protocol::Runtime::DeepSerializedValue::TypeEnum::Promise);
    return Response::Success();
  }
  if (value->IsTypedArray()) {
    result.setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Typedarray);
    return Response::Success();
  }
  if (value->IsArrayBuffer()) {
    result.setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Arraybuffer);
    return Response::Success();
  }
  if (value->IsFunction()) {
    result.setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Function);
    return Response::Success();
  }
  if (value->IsGeneratorObject()) {
    result.setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Generator);
    return Response::Success();
  }
  // Serialize as an Object.
  return SerializeObject(value.As<v8::Object>(), context, maxDepth,
                         additionalParameters, duplicateTracker, result);
}
References v8::internal::torque::Error(), v8::base::internal::result, v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeArray(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeDate(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObject(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeRegexp(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeSet(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-deep-serializer.h
/mnt/V8SourceCode/src/inspector/v8-deep-serializer.cc