v8::TracedReference< T > Class Template Reference
A traced handle without destructor that clears the handle.
#include <v8-traced-handle.h>
Classes
struct IsDroppable
Public Member Functions
TracedReference ()=default
An empty TracedReference without storage cell.
template<class S >
TracedReference (Isolate *isolate, Local< S > that)
Construct a TracedReference from a Local.
template<class S >
TracedReference (Isolate *isolate, Local< S > that, IsDroppable)
Construct a droppable TracedReference from a Local.
TracedReference (TracedReference &&other) noexcept
Move constructor initializing TracedReference from an existing one.
template<typename S >
TracedReference (TracedReference< S > &&other) noexcept
Move constructor initializing TracedReference from an existing one.
TracedReference (const TracedReference &other)
Copy constructor initializing TracedReference from an existing one.
template<typename S >
TracedReference (const TracedReference< S > &other)
Copy constructor initializing TracedReference from an existing one.
TracedReference & operator= (TracedReference &&rhs) noexcept
Move assignment operator initializing TracedReference from an existing one.
template<class S >
TracedReference & operator= (TracedReference< S > &&rhs) noexcept
Move assignment operator initializing TracedReference from an existing one.
TracedReference & operator= (const TracedReference &rhs)
Copy assignment operator initializing TracedReference from an existing one.
template<class S >
TracedReference & operator= (const TracedReference< S > &rhs)
Copy assignment operator initializing TracedReference from an existing one.
template<class S >
void Reset (Isolate *isolate, const Local< S > &other)
Always resets the reference.
template<class S >
void Reset (Isolate *isolate, const Local< S > &other, IsDroppable)
Always resets the reference.
template<class S >
TracedReference< S > & As () const
template<class S >
TracedReference< T > & operator= (TracedReference< S > &&rhs) noexcept
template<class S >
TracedReference< T > & operator= (const TracedReference< S > &rhs)
Additional Inherited Members
Detailed Description
template<typename T>
class v8::TracedReference< T >
A traced handle without destructor that clears the handle.
The embedder needs to ensure that the handle is not accessed once the V8 object has been reclaimed. For more details see BasicTracedReference.
Definition at line 165 of file v8-traced-handle.h.
Constructor & Destructor Documentation
TracedReference() [1/7]
template<typename T >
v8::TracedReference< T >::TracedReference () [inline], [default]
An empty TracedReference without storage cell.
TracedReference() [2/7]
template<typename T >
template<class S >
v8::TracedReference< T >::TracedReference (Isolate * isolate, Local< S > that) [inline]
Construct a TracedReference from a Local.
When the Local is non-empty, a new storage cell is created pointing to the same object.
Definition at line 183 of file v8-traced-handle.h.
                                                   : BasicTracedReference<T>() {
    static_assert(std::is_base_of_v<T, S>, "type check");
    if (V8_UNLIKELY(that.IsEmpty())) {
      return;
    }
    this->slot() = this->NewFromNonEmptyValue(
        isolate, *that, &this->slot(),
        internal::TracedReferenceStoreMode::kInitializingStore,
        internal::TracedReferenceHandling::kDefault);
  }
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kDefault, v8::internal::kInitializingStore, v8::BasicTracedReference< T >::NewFromNonEmptyValue(), v8::api_internal::IndirectHandleBase::slot(), and V8_UNLIKELY.
TracedReference() [3/7]
template<typename T >
template<class S >
v8::TracedReference< T >::TracedReference (Isolate * isolate, Local< S > that, IsDroppable) [inline]
Construct a droppable TracedReference from a Local.
Droppable means that V8 is free to reclaim the pointee if it is unmodified and otherwise unreachable
When the Local is non-empty, a new storage cell is created pointing to the same object.
Definition at line 203 of file v8-traced-handle.h.
      : BasicTracedReference<T>() {
    static_assert(std::is_base_of_v<T, S>, "type check");
    if (V8_UNLIKELY(that.IsEmpty())) {
      return;
    }
    this->slot() = this->NewFromNonEmptyValue(
        isolate, *that, &this->slot(),
        internal::TracedReferenceStoreMode::kInitializingStore,
        internal::TracedReferenceHandling::kDroppable);
  }
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kDroppable, v8::internal::kInitializingStore, v8::BasicTracedReference< T >::NewFromNonEmptyValue(), v8::api_internal::IndirectHandleBase::slot(), and V8_UNLIKELY.
TracedReference() [4/7]
template<typename T >
v8::TracedReference< T >::TracedReference (TracedReference< T > && other) [inline], [noexcept]
Move constructor initializing TracedReference from an existing one.
Definition at line 219 of file v8-traced-handle.h.
                                                              {
    // Forward to operator=.
    *this = std::move(other);
  }
TracedReference() [5/7]
template<typename T >
template<typename S >
v8::TracedReference< T >::TracedReference (TracedReference< S > && other) [inline], [noexcept]
Move constructor initializing TracedReference from an existing one.
Definition at line 229 of file v8-traced-handle.h.
                                                                 {
    // Forward to operator=.
    *this = std::move(other);
  }
TracedReference() [6/7]
template<typename T >
v8::TracedReference< T >::TracedReference (const TracedReference< T > & other) [inline]
Copy constructor initializing TracedReference from an existing one.
Definition at line 238 of file v8-traced-handle.h.
                                                          {
    // Forward to operator=;
    *this = other;
  }
TracedReference() [7/7]
template<typename T >
template<typename S >
v8::TracedReference< T >::TracedReference (const TracedReference< S > & other) [inline]
Copy constructor initializing TracedReference from an existing one.
Definition at line 248 of file v8-traced-handle.h.
                                                             {
    // Forward to operator=;
    *this = other;
  }
Member Function Documentation
As()
template<typename T >
template<class S >
TracedReference<S>& v8::TracedReference< T >::As () const [inline]
Definition at line 290 of file v8-traced-handle.h.
                                           {
    return reinterpret_cast<TracedReference<S>&>(
        const_cast<TracedReference<T>&>(*this));
  }
operator=() [1/6]
template<class T >
TracedReference< T > & v8::TracedReference< T >::operator= (const TracedReference< T > & rhs) [inline]
Copy assignment operator initializing TracedReference from an existing one.
Definition at line 408 of file v8-traced-handle.h.
                                                                            {
  if (this != &rhs) {
    this->Reset();
    if (!rhs.IsEmpty()) {
      internal::CopyTracedReference(&rhs.slot(), &this->slot());
    }
  }
  return *this;
}
References v8::internal::CopyTracedReference(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::api_internal::IndirectHandleBase::slot(), and v8::internal::this.
operator=() [2/6]
template<typename T >
template<class S >
TracedReference& v8::TracedReference< T >::operator= (const TracedReference< S > & rhs) [inline]
Copy assignment operator initializing TracedReference from an existing one.
operator=() [3/6]
template<typename T >
template<class S >
TracedReference<T>& v8::TracedReference< T >::operator= (const TracedReference< S > & rhs)
Definition at line 391 of file v8-traced-handle.h.
                                   {
  static_assert(std::is_base_of_v<T, S>, "type check");
  *this = rhs.template As<T>();
  return *this;
}
operator=() [4/6]
template<class T >
TracedReference< T > & v8::TracedReference< T >::operator= (TracedReference< T > && rhs) [inline], [noexcept]
Move assignment operator initializing TracedReference from an existing one.
Definition at line 399 of file v8-traced-handle.h.
                                    {
  if (this != &rhs) {
    internal::MoveTracedReference(&rhs.slot(), &this->slot());
  }
  return *this;
}
References v8::internal::MoveTracedReference(), and v8::internal::this.
operator=() [5/6]
template<typename T >
template<class S >
TracedReference& v8::TracedReference< T >::operator= (TracedReference< S > && rhs) [inline], [noexcept]
Move assignment operator initializing TracedReference from an existing one.
operator=() [6/6]
template<typename T >
template<class S >
TracedReference<T>& v8::TracedReference< T >::operator= (TracedReference< S > && rhs) [noexcept]
Definition at line 382 of file v8-traced-handle.h.
                                       {
  static_assert(std::is_base_of_v<T, S>, "type check");
  *this = std::move(rhs.template As<T>());
  return *this;
}
Reset() [1/2]
template<class T >
template<class S >
void v8::TracedReference< T >::Reset (Isolate * isolate, const Local< S > & other) [inline]
Always resets the reference.
Creates a new reference from other if it is non-empty.
Definition at line 353 of file v8-traced-handle.h.
                                                                      {
  static_assert(std::is_base_of_v<T, S>, "type check");
  this->Reset();
  if (V8_UNLIKELY(other.IsEmpty())) {
    return;
  }
  this->SetSlotThreadSafe(this->NewFromNonEmptyValue(
      isolate, *other, &this->slot(),
      internal::TracedReferenceStoreMode::kAssigningStore,
      internal::TracedReferenceHandling::kDefault));
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kAssigningStore, v8::internal::kDefault, v8::internal::SetSlotThreadSafe(), and V8_UNLIKELY.
Reset() [2/2]
template<class T >
template<class S >
void v8::TracedReference< T >::Reset (Isolate * isolate, const Local< S > & other, IsDroppable) [inline]
Always resets the reference.
Creates a new reference from other if it is non-empty. The new reference is droppable, see constructor.
Definition at line 367 of file v8-traced-handle.h.
                                            {
  static_assert(std::is_base_of_v<T, S>, "type check");
  this->Reset();
  if (V8_UNLIKELY(other.IsEmpty())) {
    return;
  }
  this->SetSlotThreadSafe(this->NewFromNonEmptyValue(
      isolate, *other, &this->slot(),
      internal::TracedReferenceStoreMode::kAssigningStore,
      internal::TracedReferenceHandling::kDroppable));
}
References v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kAssigningStore, v8::internal::kDroppable, v8::internal::SetSlotThreadSafe(), and V8_UNLIKELY.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-local-handle.h
/mnt/V8SourceCode/include/v8-traced-handle.h