v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache Class Reference
Public Types
enum class SlotKind {
kStoreGlobalSloppy
, kStoreGlobalStrict
, kSetNamedStrict
, kSetNamedSloppy
,
kLoadProperty
, kLoadSuperProperty
, kLoadGlobalNotInsideTypeof
, kLoadGlobalInsideTypeof
,
kClosureFeedbackCell
 }
Public Member Functions
FeedbackSlotCache (Zone *zone)
void Put (SlotKind slot_kind, Variable *variable, int slot_index)
void Put (SlotKind slot_kind, AstNode *node, int slot_index)
void Put (SlotKind slot_kind, int variable_index, const AstRawString *name, int slot_index)
void Put (SlotKind slot_kind, const AstRawString *name, int slot_index)
int Get (SlotKind slot_kind, Variable *variable) const
int Get (SlotKind slot_kind, AstNode *node) const
int Get (SlotKind slot_kind, int variable_index, const AstRawString *name) const
int Get (SlotKind slot_kind, const AstRawString *name) const
Private Types
using Key = std::tuple< SlotKind, int, const void * >
Private Member Functions
void PutImpl (SlotKind slot_kind, int index, const void *node, int slot_index)
int GetImpl (SlotKind slot_kind, int index, const void *node) const
Private Attributes
ZoneMap< Key, int > map_
Detailed Description
Definition at line 1040 of file bytecode-generator.cc.
Member Typedef Documentation
Key
using v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Key = std::tuple<SlotKind, int, const void*> [private]
Definition at line 1085 of file bytecode-generator.cc.
Member Enumeration Documentation
SlotKind
enum v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::SlotKind [strong]
Enumerator
kStoreGlobalSloppy
kStoreGlobalStrict
kSetNamedStrict
kSetNamedSloppy
kLoadProperty
kLoadSuperProperty
kLoadGlobalNotInsideTypeof
kLoadGlobalInsideTypeof
kClosureFeedbackCell
Definition at line 1042 of file bytecode-generator.cc.
                      {
    kStoreGlobalSloppy,
    kStoreGlobalStrict,
    kSetNamedStrict,
    kSetNamedSloppy,
    kLoadProperty,
    kLoadSuperProperty,
    kLoadGlobalNotInsideTypeof,
    kLoadGlobalInsideTypeof,
    kClosureFeedbackCell
  };
Constructor & Destructor Documentation
FeedbackSlotCache()
v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::FeedbackSlotCache (Zone * zone) [inline], [explicit]
Definition at line 1054 of file bytecode-generator.cc.
: map_(zone) {}
Member Function Documentation
Get() [1/4]
int v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Get (SlotKind slot_kind, AstNode * node) const [inline]
Definition at line 1073 of file bytecode-generator.cc.
                                                   {
    return GetImpl(slot_kind, 0, node);
  }
Get() [2/4]
int v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Get (SlotKind slot_kind, const AstRawString * name) const [inline]
Definition at line 1080 of file bytecode-generator.cc.
                                                              {
    return GetImpl(slot_kind, 0, name);
  }
References v8::internal::name.
Get() [3/4]
int v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Get (SlotKind slot_kind, int variable_index, const AstRawString * name) const [inline]
Definition at line 1076 of file bytecode-generator.cc.
                                          {
    return GetImpl(slot_kind, variable_index, name);
  }
References v8::internal::name.
Get() [4/4]
int v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Get (SlotKind slot_kind, Variable * variable) const [inline]
Definition at line 1070 of file bytecode-generator.cc.
                                                        {
    return GetImpl(slot_kind, 0, variable);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GetCachedCreateClosureSlot().
GetImpl()
int v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::GetImpl (SlotKind slot_kind, int index, const void * node) const [inline], [private]
Definition at line 1094 of file bytecode-generator.cc.
                                                                     {
    Key key = std::make_tuple(slot_kind, index, node);
    auto iter = map_.find(key);
    if (iter != map_.end()) {
      return iter->second;
    }
    return -1;
  }
References v8::internal::index, and v8::internal::key.
Put() [1/4]
void v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put (SlotKind slot_kind, AstNode * node, int slot_index) [inline]
Definition at line 1059 of file bytecode-generator.cc.
                                                              {
    PutImpl(slot_kind, 0, node, slot_index);
  }
Put() [2/4]
void v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put (SlotKind slot_kind, const AstRawString * name, int slot_index) [inline]
Definition at line 1066 of file bytecode-generator.cc.
                                                                         {
    PutImpl(slot_kind, 0, name, slot_index);
  }
References v8::internal::name.
Put() [3/4]
void v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put (SlotKind slot_kind, int variable_index, const AstRawString * name, int slot_index) [inline]
Definition at line 1062 of file bytecode-generator.cc.
                           {
    PutImpl(slot_kind, variable_index, name, slot_index);
  }
References v8::internal::name.
Put() [4/4]
void v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::Put (SlotKind slot_kind, Variable * variable, int slot_index) [inline]
Definition at line 1056 of file bytecode-generator.cc.
                                                                   {
    PutImpl(slot_kind, 0, variable, slot_index);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GetCachedCreateClosureSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadGlobalICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadSuperICSlot(), v8::internal::interpreter::BytecodeGenerator::GetCachedStoreGlobalICSlot(), and v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot().
PutImpl()
void v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::PutImpl (SlotKind slot_kind, int index, const void * node, int slot_index) [inline], [private]
Definition at line 1087 of file bytecode-generator.cc.
                               {
    Key key = std::make_tuple(slot_kind, index, node);
    auto entry = std::make_pair(key, slot_index);
    map_.insert(entry);
  }
References v8::internal::index, and v8::internal::key.
Member Data Documentation
map_
ZoneMap<Key, int> v8::internal::interpreter::BytecodeGenerator::FeedbackSlotCache::map_ [private]
Definition at line 1103 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc