v8::internal::JSPluralRules Class Reference
#include <js-plural-rules.h>
Public Types
enum class Type { CARDINAL
, ORDINAL
 }
Public Member Functions
void set_type (Type type)
Type type () const
Handle< String > TypeAsString (Isolate *isolate) const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSPluralRules > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options)
static DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSPluralRules > plural_rules)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ResolvePlural (Isolate *isolate, DirectHandle< JSPluralRules > plural_rules, double number)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > ResolvePluralRange (Isolate *isolate, DirectHandle< JSPluralRules > plural_rules, double x, double y)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
Detailed Description
Definition at line 38 of file js-plural-rules.h.
Member Enumeration Documentation
Type
enum v8::internal::JSPluralRules::Type [strong]
Enumerator
CARDINAL
ORDINAL
Definition at line 60 of file js-plural-rules.h.
{ CARDINAL, ORDINAL };
Member Function Documentation
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSPluralRules::GetAvailableLocales () [static]
Definition at line 382 of file js-plural-rules.cc.
                                                            {
  static base::LazyInstance<PluralRulesAvailableLocales>::type
      available_locales = LAZY_INSTANCE_INITIALIZER;
  return available_locales.Pointer()->Get();
}
References LAZY_INSTANCE_INITIALIZER.
Referenced by v8::internal::BUILTIN(), and New().
New()
MaybeDirectHandle< JSPluralRules > v8::internal::JSPluralRules::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 69 of file js-plural-rules.cc.
                                      {
  // 1. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, DirectHandle<JSPluralRules>());
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  // 2. Set options to ? CoerceOptionsToObject(options).
  DirectHandle<JSReceiver> options;
  const char* service = "Intl.PluralRules";
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, CoerceOptionsToObject(isolate, options_obj, service));
  // 5. Let matcher be ? GetOption(options, "localeMatcher", "string",
  // « "lookup", "best fit" », "best fit").
  // 6. Set opt.[[localeMatcher]] to matcher.
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, MaybeDirectHandle<JSPluralRules>());
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  // 7. Let t be ? GetOption(options, "type", "string", « "cardinal",
  // "ordinal" », "cardinal").
  Maybe<Type> maybe_type = GetStringOption<Type>(
      isolate, options, "type", service,
      std::to_array<const std::string_view>({"cardinal", "ordinal"}),
      std::array{Type::CARDINAL, Type::ORDINAL}, Type::CARDINAL);
  MAYBE_RETURN(maybe_type, MaybeDirectHandle<JSPluralRules>());
  Type type = maybe_type.FromJust();
  // Note: The spec says we should do ResolveLocale after performing
  // SetNumberFormatDigitOptions but we need the locale to create all
  // the ICU data structures.
  //
  // This isn't observable so we aren't violating the spec.
  // 11. Let r be ResolveLocale(%PluralRules%.[[AvailableLocales]],
  // requestedLocales, opt, %PluralRules%.[[RelevantExtensionKeys]],
  // localeData).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSPluralRules::GetAvailableLocales(),
                           requested_locales, matcher, {})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  DirectHandle<String> locale_str =
      isolate->factory()->NewStringFromAsciiChecked(r.locale.c_str());
  icu::Locale icu_locale = r.icu_locale;
  icu::number::UnlocalizedNumberFormatter settings =
      icu::number::UnlocalizedNumberFormatter().roundingMode(UNUM_ROUND_HALFUP);
  std::unique_ptr<icu::PluralRules> icu_plural_rules;
  bool success =
      CreateICUPluralRules(isolate, r.icu_locale, type, &icu_plural_rules);
  if (!success || icu_plural_rules == nullptr) {
    // Remove extensions and try again.
    icu::Locale no_extension_locale(icu_locale.getBaseName());
    success = CreateICUPluralRules(isolate, no_extension_locale, type,
                                   &icu_plural_rules);
    icu_locale = no_extension_locale;
    if (!success || icu_plural_rules == nullptr) {
      THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
    }
  }
  // 9. Perform ? SetNumberFormatDigitOptions(pluralRules, options, 0, 3).
  Maybe<Intl::NumberFormatDigitOptions> maybe_digit_options =
      Intl::SetNumberFormatDigitOptions(isolate, options, 0, 3, false, service);
  MAYBE_RETURN(maybe_digit_options, MaybeDirectHandle<JSPluralRules>());
  Intl::NumberFormatDigitOptions digit_options = maybe_digit_options.FromJust();
  settings =
      JSNumberFormat::SetDigitOptionsToFormatter(settings, digit_options);
  icu::number::LocalizedNumberFormatter icu_number_formatter =
      settings.locale(icu_locale);
  DirectHandle<Managed<icu::PluralRules>> managed_plural_rules =
      Managed<icu::PluralRules>::From(isolate, 0, std::move(icu_plural_rules));
  DirectHandle<Managed<icu::number::LocalizedNumberFormatter>>
      managed_number_formatter =
          Managed<icu::number::LocalizedNumberFormatter>::From(
              isolate, 0,
              std::make_shared<icu::number::LocalizedNumberFormatter>(
                  icu_number_formatter));
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSPluralRules> plural_rules = Cast<JSPluralRules>(
      isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  plural_rules->set_flags(0);
  // 8. Set pluralRules.[[Type]] to t.
  plural_rules->set_type(type);
  // 12. Set pluralRules.[[Locale]] to the value of r.[[locale]].
  plural_rules->set_locale(*locale_str);
  plural_rules->set_icu_plural_rules(*managed_plural_rules);
  plural_rules->set_icu_number_formatter(*managed_number_formatter);
  // 13. Return pluralRules.
  return plural_rules;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Intl::CanonicalizeLocaleList(), CARDINAL, v8::internal::CoerceOptionsToObject(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateICUPluralRules(), v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::Intl::ResolvedLocale::icu_locale, v8::internal::icu_number_formatter, v8::internal::Intl::ResolvedLocale::locale, MAYBE_RETURN, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ORDINAL, v8::internal::Intl::ResolveLocale(), v8::internal::JSNumberFormat::SetDigitOptionsToFormatter(), v8::internal::Intl::SetNumberFormatDigitOptions(), THROW_NEW_ERROR, and type().
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSPluralRules::ResolvedOptions (Isolate * isolate, DirectHandle< JSPluralRules > plural_rules) [static]
Definition at line 251 of file js-plural-rules.cc.
                                                                {
  DirectHandle<JSObject> options =
      isolate->factory()->NewJSObject(isolate->object_function());
  DirectHandle<String> locale_value(plural_rules->locale(), isolate);
  CreateDataPropertyForOptions(isolate, options, locale_value, "locale");
  CreateDataPropertyForOptions(isolate, options,
                               plural_rules->TypeAsString(isolate), "type");
  UErrorCode status = U_ZERO_ERROR;
  icu::number::LocalizedNumberFormatter* icu_number_formatter =
      plural_rules->icu_number_formatter()->raw();
  icu::UnicodeString skeleton = icu_number_formatter->toSkeleton(status);
  DCHECK(U_SUCCESS(status));
  CreateDataPropertyForOptions(
      isolate, options,
      JSNumberFormat::MinimumIntegerDigitsFromSkeleton(skeleton),
      "minimumIntegerDigits");
  int32_t min = 0, max = 0;
  if (JSNumberFormat::SignificantDigitsFromSkeleton(skeleton, &min, &max)) {
    CreateDataPropertyForOptions(isolate, options, min,
                                 "minimumSignificantDigits");
    CreateDataPropertyForOptions(isolate, options, max,
                                 "maximumSignificantDigits");
  } else {
    JSNumberFormat::FractionDigitsFromSkeleton(skeleton, &min, &max);
    CreateDataPropertyForOptions(isolate, options, min,
                                 "minimumFractionDigits");
    CreateDataPropertyForOptions(isolate, options, max,
                                 "maximumFractionDigits");
  }
  // 6. Let pluralCategories be a List of Strings containing all possible
  // results of PluralRuleSelect for the selected locale pr.[[Locale]], sorted
  // according to the following order: "zero", "one", "two", "few", "many",
  // "other".
  icu::PluralRules* icu_plural_rules = plural_rules->icu_plural_rules()->raw();
  DCHECK_NOT_NULL(icu_plural_rules);
  std::unique_ptr<icu::StringEnumeration> categories(
      icu_plural_rules->getKeywords(status));
  DCHECK(U_SUCCESS(status));
  int32_t count = categories->count(status);
  DCHECK(U_SUCCESS(status));
  Factory* factory = isolate->factory();
  DirectHandle<FixedArray> plural_categories = factory->NewFixedArray(count);
  const std::vector<const char*> kCategories = {"zero", "one", "two",
                                                "few", "many", "other"};
  int32_t index = 0;
  std::for_each(kCategories.cbegin(), kCategories.cend(), [&](const char* val) {
    categories->reset(status);
    DCHECK(U_SUCCESS(status));
    for (int32_t i = 0; i < count; i++) {
      int32_t len;
      const char* cat = categories->next(&len, status);
      DCHECK(U_SUCCESS(status));
      if (cat == nullptr) break;
      if (std::strcmp(val, cat) == 0) {
        DirectHandle<String> value_string =
            factory->NewStringFromAsciiChecked(val);
        plural_categories->set(index++, *value_string);
        break;
      }
    }
  });
  DCHECK(count == index);
  // 7. Perform ! CreateDataProperty(options, "pluralCategories",
  // CreateArrayFromList(pluralCategories)).
  DirectHandle<JSArray> plural_categories_value =
      factory->NewJSArrayWithElements(plural_categories);
  CreateDataPropertyForOptions(isolate, options, plural_categories_value,
                               "pluralCategories");
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->roundingIncrement_string(),
            JSNumberFormat::RoundingIncrement(isolate, skeleton),
            Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->roundingMode_string(),
            JSNumberFormat::RoundingModeString(isolate, skeleton),
            Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->roundingPriority_string(),
            JSNumberFormat::RoundingPriorityString(isolate, skeleton),
            Just(kDontThrow))
            .FromJust());
  CHECK(JSReceiver::CreateDataProperty(
            isolate, options, factory->trailingZeroDisplay_string(),
            JSNumberFormat::TrailingZeroDisplayString(isolate, skeleton),
            Just(kDontThrow))
            .FromJust());
  return options;
}
References v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::JSNumberFormat::FractionDigitsFromSkeleton(), v8::internal::icu_number_formatter, v8::internal::index, v8::internal::JSNumberFormat::MinimumIntegerDigitsFromSkeleton(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSObject(), v8::internal::JSNumberFormat::SignificantDigitsFromSkeleton(), and v8::internal::status.
Referenced by v8::internal::BUILTIN().
ResolvePlural()
MaybeDirectHandle< String > v8::internal::JSPluralRules::ResolvePlural (Isolate * isolate, DirectHandle< JSPluralRules > plural_rules, double number) [static]
Definition at line 179 of file js-plural-rules.cc.
                                                                               {
  icu::PluralRules* icu_plural_rules = plural_rules->icu_plural_rules()->raw();
  DCHECK_NOT_NULL(icu_plural_rules);
  icu::number::LocalizedNumberFormatter* fmt =
      plural_rules->icu_number_formatter()->raw();
  DCHECK_NOT_NULL(fmt);
  UErrorCode status = U_ZERO_ERROR;
  icu::number::FormattedNumber formatted_number =
      fmt->formatDouble(number, status);
  DCHECK(U_SUCCESS(status));
  icu::UnicodeString result =
      icu_plural_rules->select(formatted_number, status);
  DCHECK(U_SUCCESS(status));
  return Intl::ToString(isolate, result);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::base::internal::result, v8::internal::status, and v8::internal::Intl::ToString().
Referenced by v8::internal::BUILTIN().
ResolvePluralRange()
MaybeDirectHandle< String > v8::internal::JSPluralRules::ResolvePluralRange (Isolate * isolate, DirectHandle< JSPluralRules > plural_rules, double x, double y) [static]
Definition at line 200 of file js-plural-rules.cc.
              {
  icu::PluralRules* icu_plural_rules = plural_rules->icu_plural_rules()->raw();
  DCHECK_NOT_NULL(icu_plural_rules);
  Maybe<icu::number::LocalizedNumberRangeFormatter> maybe_range_formatter =
      JSNumberFormat::GetRangeFormatter(
          isolate, plural_rules->locale(),
          *plural_rules->icu_number_formatter()->raw());
  MAYBE_RETURN(maybe_range_formatter, MaybeDirectHandle<String>());
  icu::number::LocalizedNumberRangeFormatter nrfmt =
      maybe_range_formatter.FromJust();
  UErrorCode status = U_ZERO_ERROR;
  icu::number::FormattedNumberRange formatted = nrfmt.formatFormattableRange(
      icu::Formattable(x), icu::Formattable(y), status);
  DCHECK(U_SUCCESS(status));
  icu::UnicodeString result = icu_plural_rules->select(formatted, status);
  DCHECK(U_SUCCESS(status));
  return Intl::ToString(isolate, result);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::Maybe< T >::FromJust(), v8::internal::JSNumberFormat::GetRangeFormatter(), MAYBE_RETURN, v8::base::internal::result, v8::internal::status, v8::internal::Intl::ToString(), and v8::internal::y.
Referenced by v8::internal::BUILTIN().
set_type()
kIcuNumberFormatterOffset void v8::internal::JSPluralRules::set_type (Type type) [inline]
Definition at line 34 of file js-plural-rules-inl.h.
                                             {
  DCHECK(TypeBit::is_valid(type));
  int hints = flags();
  hints = TypeBit::update(hints, type);
  set_flags(hints);
}
References v8::internal::DCHECK(), v8::internal::flags, and v8::internal::tracing::type.
type()
JSPluralRules::Type v8::internal::JSPluralRules::type () const [inline]
Definition at line 41 of file js-plural-rules-inl.h.
                                                   {
  return TypeBit::decode(flags());
}
References v8::internal::flags.
Referenced by New(), and TypeAsString().
TypeAsString()
Handle< String > v8::internal::JSPluralRules::TypeAsString (Isolate * isolate) const
Definition at line 58 of file js-plural-rules.cc.
                                                                 {
  switch (type()) {
    case Type::CARDINAL:
      return isolate->factory()->cardinal_string();
    case Type::ORDINAL:
      return isolate->factory()->ordinal_string();
  }
  UNREACHABLE();
}
References CARDINAL, v8::internal::Isolate::factory(), ORDINAL, type(), and v8::internal::UNREACHABLE().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-plural-rules.h
/mnt/V8SourceCode/src/objects/js-plural-rules-inl.h
/mnt/V8SourceCode/src/objects/js-plural-rules.cc