v8::internal::compiler::turboshaft::SLPTree Class Reference
#include <wasm-revec-reducer.h>
Classes
struct ExtendIntToF32x4Info
struct LaneExtendInfo
Public Member Functions
SLPTree (Graph &graph, WasmRevecAnalyzer *analyzer, Zone *zone)
PackNode * BuildTree (const NodeGroup &roots)
void DeleteTree ()
PackNode * GetPackNode (OpIndex node)
ZoneVector< PackNode * > * GetIntersectPackNodes (OpIndex node)
ZoneUnorderedMap< OpIndex, PackNode * > & GetNodeMapping ()
ZoneUnorderedMap< OpIndex, ZoneVector< PackNode * > > & GetIntersectNodeMapping ()
void Print (const char *info)
Private Member Functions
PackNode * BuildTreeRec (const NodeGroup &node_group, unsigned depth)
PackNode * NewPackNode (const NodeGroup &node_group)
PackNode * NewIntersectPackNode (const NodeGroup &node_group)
PackNode * NewForcePackNode (const NodeGroup &node_group, ForcePackNode::ForcePackType type, const Graph &graph)
BundlePackNode * NewBundlePackNode (const NodeGroup &node_group, OpIndex base, int8_t offset, uint8_t lane_size, bool is_sign_extract, bool is_sign_convert)
PackNode * NewPackNodeAndRecurs (const NodeGroup &node_group, int start_index, int count, unsigned depth)
PackNode * NewCommutativePackNodeAndRecurs (const NodeGroup &node_group, unsigned depth)
ShufflePackNode * NewShufflePackNode (const NodeGroup &node_group, ShufflePackNode::SpecificInfo::Kind kind)
ShufflePackNode * Try256ShuffleMatchLoad8x8U (const NodeGroup &node_group, const uint8_t *shuffle0, const uint8_t *shuffle1)
bool TryMatchExtendIntToF32x4 (const NodeGroup &node_group, ExtendIntToF32x4Info *info)
std::optional< ExtendIntToF32x4Info > TryGetExtendIntToF32x4Info (OpIndex index)
bool IsSideEffectFree (OpIndex first, OpIndex second)
bool CanBePacked (const NodeGroup &node_group)
bool IsEqual (const OpIndex node0, const OpIndex node1)
bool HasInputDependencies (const NodeGroup &node_group)
Graph & graph () const
Zone * zone () const
Private Attributes
Graph & graph_
WasmRevecAnalyzer * analyzer_
Zone * phase_zone_
PackNode * root_
ZoneUnorderedMap< OpIndex, PackNode * > node_to_packnode_
ZoneUnorderedMap< OpIndex, ZoneVector< PackNode * > > node_to_intersect_packnodes_
Static Private Attributes
static constexpr size_t RecursionMaxDepth = 1000
Detailed Description
Definition at line 461 of file wasm-revec-reducer.h.
Constructor & Destructor Documentation
SLPTree()
v8::internal::compiler::turboshaft::SLPTree::SLPTree (Graph & graph, WasmRevecAnalyzer * analyzer, Zone * zone) [inline], [explicit]
Definition at line 463 of file wasm-revec-reducer.h.
      : graph_(graph),
        analyzer_(analyzer),
        phase_zone_(zone),
        root_(nullptr),
        node_to_packnode_(zone),
        node_to_intersect_packnodes_(zone) {}
Member Function Documentation
BuildTree()
PackNode * v8::internal::compiler::turboshaft::SLPTree::BuildTree (const NodeGroup & roots)
Definition at line 892 of file wasm-revec-reducer.cc.
                                                   {
  root_ = BuildTreeRec(roots, 0);
  return root_;
}
References BuildTreeRec(), and root_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run().
BuildTreeRec()
PackNode * v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec (const NodeGroup & node_group, unsigned depth) [private]
Definition at line 923 of file wasm-revec-reducer.cc.
                                                          {
  DCHECK_EQ(node_group.size(), 2);
  OpIndex node0 = node_group[0];
  OpIndex node1 = node_group[1];
  Operation& op0 = graph_.Get(node0);
  Operation& op1 = graph_.Get(node1);
  if (recursion_depth == RecursionMaxDepth) {
    TRACE("Failed due to max recursion depth!\n");
    return nullptr;
  }
  if (!CanBePacked(node_group)) {
    return nullptr;
  }
  // Check if this is a duplicate of another entry.
  bool is_intersected = false;
  // For revisited node_group, we only need to match from node0.
  if (PackNode* pnode = GetPackNode(node0)) {
    const Operation& op = graph_.Get(node0);
    if (pnode->IsSame(node_group)) {
      TRACE("Perfect diamond merge at #%d,%s\n", node0.id(),
            GetSimdOpcodeName(op).c_str());
      return pnode;
    }
    // TODO(yolanda): Support other intersect PackNode e.g. overlapped loads.
    if (!pnode->IsForcePackNode() || recursion_depth < 1) {
      TRACE("Unsupported partial overlap at #%d,%s!\n", node0.id(),
            GetSimdOpcodeName(op).c_str());
      return nullptr;
    }
    // Match intersect packnodes from current tree.
    if (auto intersect_packnodes = GetIntersectPackNodes(node0)) {
      for (auto intersect_pnode : *intersect_packnodes) {
        if (intersect_pnode->IsSame(node_group)) {
          TRACE("Perfect diamond merge at intersect pack node #%d,%s, #%d\n",
                node0.id(), GetSimdOpcodeName(op).c_str(), node1.id());
          return intersect_pnode;
        }
      }
    }
    // Match intersect packnodes from analyzer
    if (auto intersect_packnodes = analyzer_->GetIntersectPackNodes(node0)) {
      for (auto intersect_pnode : *intersect_packnodes) {
        if (intersect_pnode->IsSame(node_group)) {
          TRACE("Perfect diamond merge at intersect pack node #%d,%s, #%d\n",
                node0.id(), GetSimdOpcodeName(op).c_str(), node1.id());
          return intersect_pnode;
        }
      }
    }
    is_intersected = true;
    TRACE("Partial overlap at #%d,%s!\n", node0.id(),
          GetSimdOpcodeName(op).c_str());
  }
  // Catch overlapped PackNode on the other nodes.
  if (!is_intersected) {
    for (int i = 1; i < static_cast<int>(node_group.size()); i++) {
      const OpIndex op_idx = node_group[i];
      const Operation& op = graph_.Get(op_idx);
      if (auto pnode = GetPackNode(op_idx)) {
        if (!pnode->IsForcePackNode()) {
          TRACE("Unsupported partial overlap at #%d,%s!\n", op_idx.id(),
                GetSimdOpcodeName(op).c_str());
          return nullptr;
        }
      } else if (!GetIntersectPackNodes(op_idx) &&
                 !analyzer_->GetIntersectPackNodes(op_idx)) {
        continue;
      }
      is_intersected = true;
      TRACE("Partial overlap at #%d,%s!\n", op_idx.id(),
            GetSimdOpcodeName(op).c_str());
      break;
    }
  }
  if (is_intersected) {
    TRACE("Create IntersectPackNode due to partial overlap!\n");
    PackNode* pnode = NewIntersectPackNode(node_group);
    return pnode;
  }
  int value_in_count = op0.input_count;
  switch (op0.opcode) {
    case Opcode::kSimd128Constant: {
      PackNode* p = NewPackNode(node_group);
      return p;
    }
    case Opcode::kSimd128LoadTransform: {
      const Simd128LoadTransformOp& transform_op0 =
          op0.Cast<Simd128LoadTransformOp>();
      const Simd128LoadTransformOp& transform_op1 =
          op1.Cast<Simd128LoadTransformOp>();
      StoreLoadInfo<Simd128LoadTransformOp> info0(&graph_, &transform_op0);
      StoreLoadInfo<Simd128LoadTransformOp> info1(&graph_, &transform_op1);
      if (!info0.IsValid() || !info1.IsValid()) {
        return NewForcePackNode(node_group, ForcePackNode::kGeneral, graph_);
      }
      auto stride = info1 - info0;
      if (IsLoadSplat(transform_op0)) {
        TRACE("Simd128LoadTransform: LoadSplat\n");
        if (IsSplat(node_group) ||
            (stride.has_value() && stride.value() == 0)) {
          return NewPackNode(node_group);
        }
        return NewForcePackNode(node_group, ForcePackNode::kGeneral, graph_);
      } else if (IsLoadExtend(transform_op0)) {
        TRACE("Simd128LoadTransform: LoadExtend\n");
        if (stride.has_value()) {
          const OffsetDiff value = stride.value();
          if (value == kSimd128Size / 2) {
            return NewPackNode(node_group);
          } else if (value == 0) {
            return NewForcePackNode(node_group, ForcePackNode::kSplat, graph_);
          }
        }
        return NewForcePackNode(node_group, ForcePackNode::kGeneral, graph_);
      } else {
        TRACE("Load Transfrom k64Zero/k32Zero!\n");
        DCHECK(transform_op0.transform_kind ==
                   Simd128LoadTransformOp::TransformKind::k32Zero ||
               transform_op0.transform_kind ==
                   Simd128LoadTransformOp::TransformKind::k64Zero);
        if (stride.has_value() && stride.value() == 0) {
          return NewForcePackNode(node_group, ForcePackNode::kSplat, graph_);
        }
        return NewForcePackNode(node_group, ForcePackNode::kGeneral, graph_);
      }
    }
    case Opcode::kLoad: {
      TRACE("Load leaf node\n");
      const LoadOp& load0 = op0.Cast<LoadOp>();
      const LoadOp& load1 = op1.Cast<LoadOp>();
      if (load0.loaded_rep != MemoryRepresentation::Simd128() ||
          load1.loaded_rep != MemoryRepresentation::Simd128()) {
        TRACE("Failed due to non-simd load representation!\n");
        return nullptr;
      }
      StoreLoadInfo<LoadOp> info0(&graph_, &load0);
      StoreLoadInfo<LoadOp> info1(&graph_, &load1);
      if (info0.IsValid() && info1.IsValid()) {
        auto stride = info1 - info0;
        if (stride.has_value()) {
          if (const OffsetDiff value = stride.value(); value == kSimd128Size) {
            // TODO(jiepan) Sort load
            return NewPackNode(node_group);
          } else if (value == 0) {
            return NewForcePackNode(node_group, ForcePackNode::kSplat, graph_);
          }
        }
      }
      return NewForcePackNode(node_group, ForcePackNode::kGeneral, graph_);
    }
    case Opcode::kStore: {
      TRACE("Added a vector of stores.\n");
      // input: base, value, [index]
      PackNode* pnode = NewPackNodeAndRecurs(node_group, 1, 1, recursion_depth);
      return pnode;
    }
    case Opcode::kPhi: {
      TRACE("Added a vector of phi nodes.\n");
      const PhiOp& phi = graph().Get(node0).Cast<PhiOp>();
      if (phi.rep != RegisterRepresentation::Simd128() ||
          op0.input_count != op1.input_count) {
        TRACE("Failed due to invalid phi\n");
        return nullptr;
      }
      PackNode* pnode =
          NewPackNodeAndRecurs(node_group, 0, value_in_count, recursion_depth);
      return pnode;
    }
    case Opcode::kSimd128Unary: {
#define UNARY_CASE(op_128, not_used) case Simd128UnaryOp::Kind::k##op_128:
#define UNARY_SIGN_EXTENSION_CASE(op_low, not_used1, op_high) \
  case Simd128UnaryOp::Kind::k##op_low: { \
    if (const Simd128UnaryOp* unop1 = \
            op1.TryCast<Opmask::kSimd128##op_high>(); \
        unop1 && op0.Cast<Simd128UnaryOp>().input() == unop1->input()) { \
      return NewPackNode(node_group); \
    } \
    [[fallthrough]]; \
  } \
  case Simd128UnaryOp::Kind::k##op_high: { \
    if (op1.Cast<Simd128UnaryOp>().kind == op0.Cast<Simd128UnaryOp>().kind) { \
      auto force_pack_type = \
          node0 == node1 ? ForcePackNode::kSplat : ForcePackNode::kGeneral; \
      return NewForcePackNode(node_group, force_pack_type, graph_); \
    } else { \
      return nullptr; \
    } \
  }
      switch (op0.Cast<Simd128UnaryOp>().kind) {
        SIMD256_UNARY_SIGN_EXTENSION_OP(UNARY_SIGN_EXTENSION_CASE)
        SIMD256_UNARY_SIMPLE_OP(UNARY_CASE) {
          TRACE("Added a vector of Unary\n");
          PackNode* pnode = NewPackNodeAndRecurs(node_group, 0, value_in_count,
                                                 recursion_depth);
          return pnode;
        }
        default: {
          TRACE("Unsupported Simd128Unary: %s\n",
                GetSimdOpcodeName(op0).c_str());
          return nullptr;
        }
      }
#undef UNARY_CASE
#undef UNARY_SIGN_EXTENSION_CASE
    }
    case Opcode::kSimd128Binop: {
#define BINOP_CASE(op_128, not_used) case Simd128BinopOp::Kind::k##op_128:
#define BINOP_SIGN_EXTENSION_CASE(op_low, not_used1, op_high) \
  case Simd128BinopOp::Kind::k##op_low: { \
    if (const Simd128BinopOp* binop1 = \
            op1.TryCast<Opmask::kSimd128##op_high>(); \
        binop1 && op0.Cast<Simd128BinopOp>().left() == binop1->left() && \
        op0.Cast<Simd128BinopOp>().right() == binop1->right()) { \
      return NewPackNode(node_group); \
    } \
    [[fallthrough]]; \
  } \
  case Simd128BinopOp::Kind::k##op_high: { \
    if (op1.Cast<Simd128BinopOp>().kind == op0.Cast<Simd128BinopOp>().kind) { \
      auto force_pack_type = \
          node0 == node1 ? ForcePackNode::kSplat : ForcePackNode::kGeneral; \
      return NewForcePackNode(node_group, force_pack_type, graph_); \
    } else { \
      return nullptr; \
    } \
  }
      switch (op0.Cast<Simd128BinopOp>().kind) {
        SIMD256_BINOP_SIGN_EXTENSION_OP(BINOP_SIGN_EXTENSION_CASE)
        SIMD256_BINOP_SIMPLE_OP(BINOP_CASE) {
          TRACE("Added a vector of Binop\n");
          PackNode* pnode =
              NewCommutativePackNodeAndRecurs(node_group, recursion_depth);
          return pnode;
        }
        default: {
          TRACE("Unsupported Simd128Binop: %s\n",
                GetSimdOpcodeName(op0).c_str());
          return nullptr;
        }
      }
#undef BINOP_CASE
#undef BINOP_SIGN_EXTENSION_CASE
    }
    case Opcode::kSimd128Shift: {
      Simd128ShiftOp& shift_op0 = op0.Cast<Simd128ShiftOp>();
      Simd128ShiftOp& shift_op1 = op1.Cast<Simd128ShiftOp>();
      if (IsEqual(shift_op0.shift(), shift_op1.shift())) {
        switch (op0.Cast<Simd128ShiftOp>().kind) {
#define SHIFT_CASE(op_128, not_used) case Simd128ShiftOp::Kind::k##op_128:
          SIMD256_SHIFT_OP(SHIFT_CASE) {
            TRACE("Added a vector of Shift op.\n");
            // We've already checked that the "shift by" input of both shifts is
            // the same, and we'll only pack the 1st input of the shifts
            // together anyways (since on both Simd128 and Simd256, the "shift
            // by" input of shifts is a Word32). Thus we only need to check the
            // 1st input of the shift when recursing.
            constexpr int kShiftValueInCount = 1;
            PackNode* pnode = NewPackNodeAndRecurs(
                node_group, 0, kShiftValueInCount, recursion_depth);
            return pnode;
          }
#undef SHIFT_CASE
          default: {
            TRACE("Unsupported Simd128ShiftOp: %s\n",
                  GetSimdOpcodeName(op0).c_str());
            return nullptr;
          }
        }
      }
      TRACE("Failed due to SimdShiftOp kind or shift scalar is different!\n");
      return nullptr;
    }
    case Opcode::kSimd128Ternary: {
#define TERNARY_CASE(op_128, not_used) case Simd128TernaryOp::Kind::k##op_128:
      switch (op0.Cast<Simd128TernaryOp>().kind) {
        SIMD256_TERNARY_OP(TERNARY_CASE) {
          TRACE("Added a vector of Ternary\n");
          PackNode* pnode = NewPackNodeAndRecurs(node_group, 0, value_in_count,
                                                 recursion_depth);
          return pnode;
        }
#undef TERNARY_CASE
        default: {
          TRACE("Unsupported Simd128Ternary: %s\n",
                GetSimdOpcodeName(op0).c_str());
          return nullptr;
        }
      }
    }
    case Opcode::kSimd128Splat: {
      if (!IsEqual(op0.input(0), op1.input(0))) {
        TRACE("Failed due to different splat input!\n");
        return nullptr;
      }
      PackNode* pnode = NewPackNode(node_group);
      return pnode;
    }
    case Opcode::kSimd128Shuffle: {
      const auto& shuffle_op0 = op0.Cast<Simd128ShuffleOp>();
      const auto& shuffle_op1 = op1.Cast<Simd128ShuffleOp>();
      if (shuffle_op0.kind != Simd128ShuffleOp::Kind::kI8x16 ||
          shuffle_op1.kind != Simd128ShuffleOp::Kind::kI8x16) {
        return nullptr;
      }
      // We pack shuffles only if it can match specific patterns. We should
      // avoid packing general shuffles because it will cause regression.
      const auto& shuffle0 = shuffle_op0.shuffle;
      const auto& shuffle1 = shuffle_op1.shuffle;
      if (CompareCharsEqual(shuffle0, shuffle1, kSimd128Size)) {
        if (IsSplat(node_group)) {
          // Check if the shuffle can be replaced by a loadsplat.
          // Take load32splat as an example:
          // 1. Param0 # be used as load base
          // 2. Param1 # be used as load index
          // 3. Param2 # be used as store base
          // 4. Param3 # be used as store index
          // 5. Load128(base, index, offset=0)
          // 6. AnyOp
          // 7. Shuffle32x4 (1,2, [2,2,2,2])
          // 8. Store128(3,4,7, offset=0)
          // 9. Store128(3,4,7, offset=16)
          //
          // We can replace the load128 and shuffle with a loadsplat32:
          // 1. Param0 # be used as load base
          // 2. Param1 # be used as load index
          // 3. Param2 # be used as store base
          // 4. Param3 # be used as store index
          // 5. Load32Splat256(base, index, offset=4)
          // 6. Store256(3,4,7,offset=0)
          int index;
          if (wasm::SimdShuffle::TryMatchSplat<4>(shuffle0, &index) &&
              graph_.Get(op0.input(index >> 2)).opcode == Opcode::kLoad) {
            ShufflePackNode* pnode = NewShufflePackNode(
                node_group,
                ShufflePackNode::SpecificInfo::Kind::kS256Load32Transform);
            pnode->info().set_splat_index(index);
            return pnode;
          } else if (wasm::SimdShuffle::TryMatchSplat<2>(shuffle0, &index) &&
                     graph_.Get(op0.input(index >> 1)).opcode ==
                         Opcode::kLoad) {
            ShufflePackNode* pnode = NewShufflePackNode(
                node_group,
                ShufflePackNode::SpecificInfo::Kind::kS256Load64Transform);
            pnode->info().set_splat_index(index);
            return pnode;
          }
        }
#ifdef V8_TARGET_ARCH_X64
        if (ShufflePackNode* pnode =
                X64TryMatch256Shuffle(node_group, shuffle0, shuffle1)) {
          // Manually invoke recur build tree for shuffle node
          for (int i = 0; i < value_in_count; ++i) {
            NodeGroup operands(graph_.Get(node_group[0]).input(i),
                               graph_.Get(node_group[1]).input(i));
            PackNode* child = BuildTreeRec(operands, recursion_depth + 1);
            if (child) {
              pnode->SetOperand(i, child);
            } else {
              return nullptr;
            }
          }
          return pnode;
        }
#endif // V8_TARGET_ARCH_X64
        TRACE("Unsupported Simd128Shuffle\n");
        return nullptr;
      } else {
        return Try256ShuffleMatchLoad8x8U(node_group, shuffle0, shuffle1);
      }
    }
    case Opcode::kSimd128ReplaceLane: {
      ExtendIntToF32x4Info info;
      if (TryMatchExtendIntToF32x4(node_group, &info)) {
        TRACE("Match extend i8x4/i16x4 to f32x4\n");
        PackNode* p = NewBundlePackNode(
            node_group, info.extend_from, info.start_lane, info.lane_size,
            info.is_sign_extract, info.is_sign_convert);
        return p;
      }
      if (recursion_depth < 1) {
        TRACE("Do not force pack at root #%d:%s\n", node0.id(),
              GetSimdOpcodeName(op0).c_str());
        return nullptr;
      }
      return NewForcePackNode(
          node_group,
          node0 == node1 ? ForcePackNode::kSplat : ForcePackNode::kGeneral,
          graph_);
    }
    default:
      TRACE("Default branch #%d:%s\n", node0.id(),
            GetSimdOpcodeName(op0).c_str());
      break;
  }
  return nullptr;
}
References analyzer_, BINOP_CASE, BINOP_SIGN_EXTENSION_CASE, CanBePacked(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::CompareCharsEqual(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::extend_from, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetIntersectPackNodes(), GetIntersectPackNodes(), GetPackNode(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::index, v8::internal::compiler::turboshaft::ShufflePackNode::info(), v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::is_sign_convert, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::is_sign_extract, IsEqual(), v8::internal::compiler::turboshaft::IsLoadExtend(), v8::internal::compiler::turboshaft::IsLoadSplat(), v8::internal::compiler::turboshaft::IsSplat(), v8::internal::compiler::turboshaft::StoreLoadInfo< Op, typename >::IsValid(), v8::internal::compiler::turboshaft::ForcePackNode::kGeneral, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kS256Load32Transform, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kS256Load64Transform, v8::internal::kSimd128Size, v8::internal::compiler::turboshaft::ForcePackNode::kSplat, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::lane_size, v8::internal::compiler::turboshaft::LoadOp::loaded_rep, NewBundlePackNode(), NewCommutativePackNodeAndRecurs(), NewForcePackNode(), NewIntersectPackNode(), NewPackNode(), NewPackNodeAndRecurs(), NewShufflePackNode(), v8::internal::compiler::turboshaft::Operation::opcode, RecursionMaxDepth, v8::internal::compiler::turboshaft::PhiOp::rep, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::set_splat_index(), SHIFT_CASE, v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::MemoryRepresentation::Simd128(), SIMD256_BINOP_SIGN_EXTENSION_OP, SIMD256_BINOP_SIMPLE_OP, SIMD256_SHIFT_OP, SIMD256_TERNARY_OP, SIMD256_UNARY_SIGN_EXTENSION_OP, SIMD256_UNARY_SIMPLE_OP, v8::internal::compiler::turboshaft::NodeGroup::size(), v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::start_lane, v8::internal::anonymous_namespace{json-stringifier.cc}::stride, TERNARY_CASE, v8::internal::TRACE(), Try256ShuffleMatchLoad8x8U(), TryMatchExtendIntToF32x4(), UNARY_CASE, UNARY_SIGN_EXTENSION_CASE, and v8::internal::value.
Referenced by BuildTree(), NewCommutativePackNodeAndRecurs(), and NewPackNodeAndRecurs().
CanBePacked()
bool v8::internal::compiler::turboshaft::SLPTree::CanBePacked (const NodeGroup & node_group) [private]
Definition at line 850 of file wasm-revec-reducer.cc.
                                                     {
  OpIndex node0 = node_group[0];
  OpIndex node1 = node_group[1];
  Operation& op0 = graph_.Get(node0);
  Operation& op1 = graph_.Get(node1);
  if (op0.opcode != op1.opcode) {
    TRACE("Different opcode\n");
    return false;
  }
  if (graph().BlockIndexOf(node0) != graph().BlockIndexOf(node1)) {
    TRACE("Can't pack operations of different basic block\n");
    return false;
  }
  auto is_sign_ext = IsSignExtensionOp(op0) && IsSignExtensionOp(op1);
  if (!is_sign_ext && !IsSameOpAndKind(op0, op1)) {
    TRACE("(%s, %s) have different op\n", GetSimdOpcodeName(op0).c_str(),
          GetSimdOpcodeName(op1).c_str());
    return false;
  }
  if (node0.offset() <= node1.offset() ? !IsSideEffectFree(node0, node1)
                                       : !IsSideEffectFree(node1, node0)) {
    TRACE("Break side effect\n");
    return false;
  }
  return true;
}
References v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph(), graph_, v8::internal::compiler::turboshaft::IsSameOpAndKind(), IsSideEffectFree(), v8::internal::compiler::turboshaft::IsSignExtensionOp(), v8::internal::compiler::turboshaft::OpIndex::offset(), v8::internal::compiler::turboshaft::Operation::opcode, and v8::internal::TRACE().
Referenced by BuildTreeRec().
DeleteTree()
void v8::internal::compiler::turboshaft::SLPTree::DeleteTree ()
GetIntersectNodeMapping()
ZoneUnorderedMap<OpIndex, ZoneVector<PackNode*> >& v8::internal::compiler::turboshaft::SLPTree::GetIntersectNodeMapping () [inline]
Definition at line 497 of file wasm-revec-reducer.h.
                                                                              {
    return node_to_intersect_packnodes_;
  }
References node_to_intersect_packnodes_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::MergeSLPTree().
GetIntersectPackNodes()
ZoneVector< PackNode * > * v8::internal::compiler::turboshaft::SLPTree::GetIntersectPackNodes (OpIndex node)
Definition at line 242 of file wasm-revec-reducer.cc.
                                                                  {
  auto I = node_to_intersect_packnodes_.find(node);
  if (I != node_to_intersect_packnodes_.end()) {
    return &(I->second);
  }
  return nullptr;
}
References v8::internal::I, and node_to_intersect_packnodes_.
Referenced by BuildTreeRec().
GetNodeMapping()
ZoneUnorderedMap<OpIndex, PackNode*>& v8::internal::compiler::turboshaft::SLPTree::GetNodeMapping () [inline]
Definition at line 494 of file wasm-revec-reducer.h.
                                                         {
    return node_to_packnode_;
  }
References node_to_packnode_.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::MergeSLPTree().
GetPackNode()
PackNode * v8::internal::compiler::turboshaft::SLPTree::GetPackNode (OpIndex node)
Definition at line 234 of file wasm-revec-reducer.cc.
                                           {
  auto itr = node_to_packnode_.find(node);
  if (itr != node_to_packnode_.end()) {
    return itr->second;
  }
  return analyzer_->GetPackNode(node);
}
References analyzer_, v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetPackNode(), and node_to_packnode_.
Referenced by BuildTreeRec().
graph()
Graph& v8::internal::compiler::turboshaft::SLPTree::graph () const [inline], [private]
Definition at line 572 of file wasm-revec-reducer.h.
{ return graph_; }
References graph_.
Referenced by BuildTreeRec(), CanBePacked(), and IsSideEffectFree().
HasInputDependencies()
bool v8::internal::compiler::turboshaft::SLPTree::HasInputDependencies (const NodeGroup & node_group) [private]
Definition at line 294 of file wasm-revec-reducer.cc.
                                                              {
  DCHECK_EQ(node_group.size(), 2);
  if (node_group[0] == node_group[1]) return false;
  OpIndex start, end;
  if (node_group[0] < node_group[1]) {
    start = node_group[0];
    end = node_group[1];
  } else {
    start = node_group[1];
    end = node_group[0];
  }
  // Do BFS from the end node and see if there is a path to the start node.
  ZoneQueue<OpIndex> to_visit(phase_zone_);
  to_visit.push(end);
  while (!to_visit.empty()) {
    OpIndex to_visit_node = to_visit.front();
    Operation& op = graph_.Get(to_visit_node);
    to_visit.pop();
    for (OpIndex input : op.inputs()) {
      if (input == start) {
        return true;
      } else if (input > start) {
        // We should ensure that there is no back edge.
        DCHECK_LT(input, to_visit_node);
        to_visit.push(input);
      }
    }
  }
  return false;
}
References DCHECK_EQ, DCHECK_LT, v8::internal::compiler::end(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Operation::inputs(), phase_zone_, and v8::internal::compiler::turboshaft::NodeGroup::size().
Referenced by NewForcePackNode(), and NewIntersectPackNode().
IsEqual()
bool v8::internal::compiler::turboshaft::SLPTree::IsEqual (const OpIndex node0, const OpIndex node1) [private]
Definition at line 882 of file wasm-revec-reducer.cc.
                                                              {
  if (node0 == node1) return true;
  if (const ConstantOp* const0 = graph_.Get(node0).TryCast<ConstantOp>()) {
    if (const ConstantOp* const1 = graph_.Get(node1).TryCast<ConstantOp>()) {
      return *const0 == *const1;
    }
  }
  return false;
}
References v8::internal::compiler::turboshaft::Graph::Get(), graph_, and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by BuildTreeRec().
IsSideEffectFree()
bool v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree (OpIndex first, OpIndex second) [private]
Definition at line 820 of file wasm-revec-reducer.cc.
                                                            {
  DCHECK_LE(first.offset(), second.offset());
  if (first == second) return true;
  OpEffects effects = graph().Get(second).Effects();
  OpIndex prev_node = graph().PreviousIndex(second);
  while (prev_node != first) {
    OpEffects prev_effects = graph().Get(prev_node).Effects();
    if ((graph().Get(second).IsProtectedLoad() &&
         graph().Get(prev_node).IsProtectedLoad())
            ? CannotSwapProtectedLoads(prev_effects, effects)
            : CannotSwapOperations(prev_effects, effects)) {
      TRACE("break side effect %d, %d\n", prev_node.id(), second.id());
      return false;
    }
    prev_node = graph().PreviousIndex(prev_node);
  }
  return true;
}
References v8::internal::compiler::turboshaft::CannotSwapOperations(), v8::internal::compiler::turboshaft::CannotSwapProtectedLoads(), DCHECK_LE, v8::internal::compiler::turboshaft::Operation::Effects(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::Graph::Get(), graph(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::OpIndex::offset(), v8::internal::compiler::turboshaft::Graph::PreviousIndex(), and v8::internal::TRACE().
Referenced by CanBePacked().
NewBundlePackNode()
BundlePackNode * v8::internal::compiler::turboshaft::SLPTree::NewBundlePackNode (const NodeGroup & node_group, OpIndex base, int8_t offset, uint8_t lane_size, bool is_sign_extract, bool is_sign_convert) [private]
Definition at line 367 of file wasm-revec-reducer.cc.
                                                                 {
  Operation& op = graph_.Get(node_group[0]);
  TRACE("PackNode %s(#%d:, #%d)\n", GetSimdOpcodeName(op).c_str(),
        node_group[0].id(), node_group[1].id());
  BundlePackNode* pnode = phase_zone_->New<BundlePackNode>(
      phase_zone_, node_group, base, offset, lane_size, is_sign_extract,
      is_sign_convert);
  for (OpIndex node : node_group) {
    node_to_packnode_[node] = pnode;
  }
  return pnode;
}
References v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph_, v8::internal::Zone::New(), node_to_packnode_, phase_zone_, and v8::internal::TRACE().
Referenced by BuildTreeRec().
NewCommutativePackNodeAndRecurs()
PackNode * v8::internal::compiler::turboshaft::SLPTree::NewCommutativePackNodeAndRecurs (const NodeGroup & node_group, unsigned depth) [private]
Definition at line 415 of file wasm-revec-reducer.cc.
                                                                   {
  PackNode* pnode = NewPackNode(node_group);
  const Simd128BinopOp& op0 = graph_.Get(node_group[0]).Cast<Simd128BinopOp>();
  const Simd128BinopOp& op1 = graph_.Get(node_group[1]).Cast<Simd128BinopOp>();
  bool same_kind =
      (op0.left() == op1.left()) ||
      IsSameOpAndKind(graph_.Get(op0.left()), graph_.Get(op1.left()));
  bool need_swap = Simd128BinopOp::IsCommutative(op0.kind) && !same_kind;
  if (need_swap) {
    TRACE("Change the order of binop operands\n");
  }
  for (int i = 0; i < 2; ++i) {
    // Swap the left and right input if necessary
    unsigned node1_input_index = need_swap ? 1 - i : i;
    NodeGroup operands(graph_.Get(node_group[0]).input(i),
                       graph_.Get(node_group[1]).input(node1_input_index));
    PackNode* child = BuildTreeRec(operands, depth + 1);
    if (child) {
      pnode->SetOperand(i, child);
    } else {
      return nullptr;
    }
  }
  return pnode;
}
References BuildTreeRec(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::IsSameOpAndKind(), NewPackNode(), v8::internal::compiler::turboshaft::PackNode::SetOperand(), and v8::internal::TRACE().
Referenced by BuildTreeRec().
NewForcePackNode()
PackNode * v8::internal::compiler::turboshaft::SLPTree::NewForcePackNode (const NodeGroup & node_group, ForcePackNode::ForcePackType type, const Graph & graph) [private]
Definition at line 336 of file wasm-revec-reducer.cc.
                                                        {
  // Currently we only support force packing two nodes.
  DCHECK_EQ(node_group.size(), 2);
  // We should guarantee that the one node in the NodeGroup does not rely on the
  // result of the other. Because it is costly to force pack such candidates.
  // For example, we have four nodes {A, B, C, D} which are connected by input
  // edges: A <-- B <-- C <-- D. If {B} and {D} are already packed into a
  // PackNode and we want to force pack {A} and {C}, we need to duplicate {B}
  // and the result will be {A, B, C}, {B, D}. This increase the cost of
  // ForcePack so currently we do not support it.
  if (HasInputDependencies(node_group)) {
    TRACE("ForcePackNode %s(#%d, #%d) failed due to input dependencies.\n",
          GetSimdOpcodeName(graph_.Get(node_group[0])).c_str(),
          node_group[0].id(), node_group[1].id());
    return nullptr;
  }
  TRACE("ForcePackNode %s(#%d, #%d)\n",
        GetSimdOpcodeName(graph_.Get(node_group[0])).c_str(),
        node_group[0].id(), node_group[1].id());
  ForcePackNode* pnode =
      phase_zone_->New<ForcePackNode>(phase_zone_, node_group, type);
  for (OpIndex node : node_group) {
    node_to_packnode_[node] = pnode;
  }
  return pnode;
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph_, HasInputDependencies(), v8::internal::Zone::New(), node_to_packnode_, phase_zone_, v8::internal::compiler::turboshaft::NodeGroup::size(), v8::internal::TRACE(), and v8::internal::tracing::type.
Referenced by BuildTreeRec().
NewIntersectPackNode()
PackNode * v8::internal::compiler::turboshaft::SLPTree::NewIntersectPackNode (const NodeGroup & node_group) [private]
Definition at line 384 of file wasm-revec-reducer.cc.
                                                                   {
  // Similar as ForcePackNode, dependent inputs are not supported.
  if (HasInputDependencies(node_group)) {
    TRACE("IntersectPackNode %s(#%d, #%d) failed due to input dependencies.\n",
          GetSimdOpcodeName(graph_.Get(node_group[0])).c_str(),
          node_group[0].id(), node_group[1].id());
    return nullptr;
  }
  TRACE("IntersectPackNode %s(#%d, #%d)\n",
        GetSimdOpcodeName(graph_.Get(node_group[0])).c_str(),
        node_group[0].id(), node_group[1].id());
  PackNode* intersect_pnode = phase_zone_->New<PackNode>(
      phase_zone_, node_group, PackNode::kIntersectPackNode);
  for (int i = 0; i < static_cast<int>(node_group.size()); i++) {
    OpIndex op_idx = node_group[i];
    if (i > 0 && op_idx == node_group[0]) continue;
    auto it = node_to_intersect_packnodes_.find(op_idx);
    if (it == node_to_intersect_packnodes_.end()) {
      bool result;
      std::tie(it, result) = node_to_intersect_packnodes_.emplace(
          op_idx, ZoneVector<PackNode*>(phase_zone_));
      DCHECK(result);
    }
    it->second.push_back(intersect_pnode);
  }
  return intersect_pnode;
}
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph_, HasInputDependencies(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::PackNode::kIntersectPackNode, v8::internal::Zone::New(), node_to_intersect_packnodes_, phase_zone_, v8::base::internal::result, v8::internal::compiler::turboshaft::NodeGroup::size(), and v8::internal::TRACE().
Referenced by BuildTreeRec().
NewPackNode()
PackNode * v8::internal::compiler::turboshaft::SLPTree::NewPackNode (const NodeGroup & node_group) [private]
Definition at line 325 of file wasm-revec-reducer.cc.
                                                          {
  TRACE("PackNode %s(#%d, #%d)\n",
        GetSimdOpcodeName(graph_.Get(node_group[0])).c_str(),
        node_group[0].id(), node_group[1].id());
  PackNode* pnode = phase_zone_->New<PackNode>(phase_zone_, node_group);
  for (OpIndex node : node_group) {
    node_to_packnode_[node] = pnode;
  }
  return pnode;
}
References v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph_, v8::internal::Zone::New(), node_to_packnode_, phase_zone_, and v8::internal::TRACE().
Referenced by BuildTreeRec(), NewCommutativePackNodeAndRecurs(), and NewPackNodeAndRecurs().
NewPackNodeAndRecurs()
PackNode * v8::internal::compiler::turboshaft::SLPTree::NewPackNodeAndRecurs (const NodeGroup & node_group, int start_index, int count, unsigned depth) [private]
Definition at line 445 of file wasm-revec-reducer.cc.
                                                        {
  PackNode* pnode = NewPackNode(node_group);
  for (int i = 0; i < count; ++i) {
    // Prepare the operand vector.
    int input_index = i + start_index;
    NodeGroup operands(graph_.Get(node_group[0]).input(input_index),
                       graph_.Get(node_group[1]).input(input_index));
    PackNode* child = BuildTreeRec(operands, depth + 1);
    if (child) {
      pnode->SetOperand(i, child);
    } else {
      return nullptr;
    }
  }
  return pnode;
}
References BuildTreeRec(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Operation::input(), NewPackNode(), and v8::internal::compiler::turboshaft::PackNode::SetOperand().
Referenced by BuildTreeRec().
NewShufflePackNode()
ShufflePackNode * v8::internal::compiler::turboshaft::SLPTree::NewShufflePackNode (const NodeGroup & node_group, ShufflePackNode::SpecificInfo::Kind kind) [private]
Definition at line 465 of file wasm-revec-reducer.cc.
                                                                       {
  Operation& op = graph_.Get(node_group[0]);
  TRACE("PackNode %s(#%d:, #%d)\n", GetSimdOpcodeName(op).c_str(),
        node_group[0].id(), node_group[1].id());
  ShufflePackNode* pnode =
      phase_zone_->New<ShufflePackNode>(phase_zone_, node_group, kind);
  for (OpIndex node : node_group) {
    node_to_packnode_[node] = pnode;
  }
  return pnode;
}
References v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::GetSimdOpcodeName(), graph_, v8::internal::Zone::New(), node_to_packnode_, phase_zone_, and v8::internal::TRACE().
Referenced by BuildTreeRec(), and Try256ShuffleMatchLoad8x8U().
Print()
void v8::internal::compiler::turboshaft::SLPTree::Print (const char * info)
Definition at line 282 of file wasm-revec-reducer.cc.
                                    {
  TRACE("%s, %zu Packed node:\n", info, node_to_packnode_.size());
  if (!v8_flags.trace_wasm_revectorize) {
    return;
  }
  ForEach([this](PackNode const* pnode) { pnode->Print(&graph_); },
          node_to_packnode_);
  ForEach([this](PackNode const* pnode) { pnode->Print(&graph_); },
          node_to_intersect_packnodes_);
}
References v8::internal::compiler::turboshaft::ForEach(), graph_, node_to_intersect_packnodes_, node_to_packnode_, v8::internal::compiler::turboshaft::PackNode::Print(), v8::internal::TRACE(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run().
Try256ShuffleMatchLoad8x8U()
ShufflePackNode * v8::internal::compiler::turboshaft::SLPTree::Try256ShuffleMatchLoad8x8U (const NodeGroup & node_group, const uint8_t * shuffle0, const uint8_t * shuffle1) [private]
Definition at line 478 of file wasm-revec-reducer.cc.
                             {
  uint8_t shuffle_copy0[kSimd128Size];
  uint8_t shuffle_copy1[kSimd128Size];
  V<Simd128> op_idx0 = node_group[0];
  V<Simd128> op_idx1 = node_group[1];
  const Simd128ShuffleOp& op0 = graph_.Get(op_idx0).Cast<Simd128ShuffleOp>();
  const Simd128ShuffleOp& op1 = graph_.Get(op_idx1).Cast<Simd128ShuffleOp>();
  if (op0.kind != Simd128ShuffleOp::Kind::kI8x16 ||
      op1.kind != Simd128ShuffleOp::Kind::kI8x16) {
    return nullptr;
  }
  if (op0.left() == op0.right() || op1.left() == op1.right()) {
    // Here shuffle couldn't be swizzle
    return nullptr;
  }
  CopyChars(shuffle_copy0, shuffle0, kSimd128Size);
  CopyChars(shuffle_copy1, shuffle1, kSimd128Size);
  bool need_swap, is_swizzle;
#define CANONICALIZE_SHUFFLE(n) \
  wasm::SimdShuffle::CanonicalizeShuffle(false, shuffle_copy##n, &need_swap, \
                                         &is_swizzle); \
  if (is_swizzle) { \
    /* Here shuffle couldn't be swizzle*/ \
    return nullptr; \
  } \
  V<Simd128> shuffle##n##_left_idx = need_swap ? op##n.right() : op##n.left(); \
  V<Simd128> shuffle##n##_right_idx = need_swap ? op##n.left() : op##n.right();
  CANONICALIZE_SHUFFLE(0);
  CANONICALIZE_SHUFFLE(1);
#undef CANONICALIZE_SHUFFLE
  if (shuffle0_left_idx != shuffle1_left_idx) {
    // Not the same left
    return nullptr;
  }
  const Simd128LoadTransformOp* load_transform =
      graph_.Get(shuffle0_left_idx).TryCast<Simd128LoadTransformOp>();
  if (!load_transform) {
    // shuffle left is not Simd128LoadTransformOp
    return nullptr;
  }
  Simd128ConstantOp* shuffle0_const =
      graph_.Get(shuffle0_right_idx).TryCast<Simd128ConstantOp>();
  Simd128ConstantOp* shuffle1_const =
      graph_.Get(shuffle1_right_idx).TryCast<Simd128ConstantOp>();
  if (!shuffle0_const || !shuffle1_const || !shuffle0_const->IsZero() ||
      !shuffle1_const->IsZero()) {
    // Shuffle right is not zero
    return nullptr;
  }
  if (load_transform->transform_kind ==
      Simd128LoadTransformOp::TransformKind::k64Zero) {
    /*
      should look like this:
      shuffle0 = 0,x,x,x, 1,x,x,x 2,x,x,x 3,x,x,x
      shuffle1 = 4,x,x,x, 5,x,x,x 6,x,x,x 7,x,x,x
      x >= 16
    */
    for (int i = 0; i < kSimd128Size / 4; ++i) {
      if (shuffle_copy0[i * 4] != i || shuffle_copy1[i * 4] != i + 4) {
        // not match
        return nullptr;
      }
      if (shuffle_copy0[i * 4 + 1] < kSimd128Size ||
          shuffle_copy0[i * 4 + 2] < kSimd128Size ||
          shuffle_copy0[i * 4 + 3] < kSimd128Size ||
          shuffle_copy1[i * 4 + 1] < kSimd128Size ||
          shuffle_copy1[i * 4 + 2] < kSimd128Size ||
          shuffle_copy1[i * 4 + 3] < kSimd128Size) {
        // not match
        return nullptr;
      }
    }
    TRACE("match load extend 8x8->32x8\n");
    return NewShufflePackNode(
        node_group, ShufflePackNode::SpecificInfo::Kind::kS256Load8x8U);
  }
  return nullptr;
}
References CANONICALIZE_SHUFFLE, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::CopyChars(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kS256Load8x8U, v8::internal::kSimd128Size, NewShufflePackNode(), v8::internal::TRACE(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by BuildTreeRec().
TryGetExtendIntToF32x4Info()
std::optional< SLPTree::ExtendIntToF32x4Info > v8::internal::compiler::turboshaft::SLPTree::TryGetExtendIntToF32x4Info (OpIndex index) [private]
Definition at line 677 of file wasm-revec-reducer.cc.
                                                 {
  OpIndex current = index;
  LaneExtendInfo lane_extend_info[4];
  // Get information for lane 1 to lane 3
  for (int lane_index = 3; lane_index > 0; lane_index--) {
    const Simd128ReplaceLaneOp* replace_lane =
        graph_.Get(current)
            .TryCast<turboshaft::Opmask::kSimd128ReplaceLaneF32x4>();
    if (!replace_lane) {
      TRACE("Mismatch in replace lane\n");
      return {};
    }
    const ChangeOp* change =
        graph_.Get(replace_lane->new_lane()).TryCast<ChangeOp>();
    if (!change) {
      TRACE("Mismatch in type convert\n");
      return {};
    }
    const Simd128ExtractLaneOp* extract_lane =
        graph_.Get(change->input()).TryCast<Simd128ExtractLaneOp>();
    if (!extract_lane) {
      TRACE("Mismatch in extract lane\n");
      return {};
    }
    lane_extend_info[lane_index].replace_lane_index = replace_lane->lane;
    lane_extend_info[lane_index].change_kind = change->kind;
    lane_extend_info[lane_index].extract_from = extract_lane->input();
    lane_extend_info[lane_index].extract_kind = extract_lane->kind;
    lane_extend_info[lane_index].extract_lane_index = extract_lane->lane;
    current = replace_lane->into();
  }
  // Get information for lane 0(splat)
  const Simd128SplatOp* splat = graph_.Get(current).TryCast<Simd128SplatOp>();
  if (!splat) {
    TRACE("Mismatch in splat\n");
    return {};
  }
  const ChangeOp* change = graph_.Get(splat->input()).TryCast<ChangeOp>();
  if (!change) {
    TRACE("Mismatch in splat type convert\n");
    return {};
  }
  const Simd128ExtractLaneOp* extract_lane =
      graph_.Get(change->input()).TryCast<Simd128ExtractLaneOp>();
  if (!extract_lane) {
    TRACE("Mismatch in splat extract lane\n");
    return {};
  }
  lane_extend_info[0].replace_lane_index = 0;
  lane_extend_info[0].change_kind = change->kind;
  lane_extend_info[0].extract_from = extract_lane->input();
  lane_extend_info[0].extract_kind = extract_lane->kind;
  lane_extend_info[0].extract_lane_index = extract_lane->lane;
  // Pattern matching for f32x4.convert_i32x4(i32x4.extract_lane)
  for (int i = 0; i < 4; i++) {
    if (lane_extend_info[i].replace_lane_index != i) {
      return {};
    }
    if (lane_extend_info[i].change_kind != lane_extend_info[0].change_kind ||
        (lane_extend_info[i].change_kind != ChangeOp::Kind::kSignedToFloat &&
         lane_extend_info[i].change_kind != ChangeOp::Kind::kUnsignedToFloat)) {
      return {};
    }
    if (lane_extend_info[i].extract_from != lane_extend_info[0].extract_from) {
      return {};
    }
    if (lane_extend_info[i].extract_kind != lane_extend_info[0].extract_kind ||
        (lane_extend_info[i].extract_kind !=
             Simd128ExtractLaneOp::Kind::kI8x16S &&
         lane_extend_info[i].extract_kind !=
             Simd128ExtractLaneOp::Kind::kI8x16U &&
         lane_extend_info[i].extract_kind !=
             Simd128ExtractLaneOp::Kind::kI16x8S &&
         lane_extend_info[i].extract_kind !=
             Simd128ExtractLaneOp::Kind::kI16x8U)) {
      return {};
    }
    if (lane_extend_info[i].extract_lane_index !=
        lane_extend_info[0].extract_lane_index + i) {
      return {};
    }
  }
  ExtendIntToF32x4Info info;
  info.extend_from = lane_extend_info[0].extract_from;
  info.start_lane = lane_extend_info[0].extract_lane_index;
  if (lane_extend_info[0].extract_kind == Simd128ExtractLaneOp::Kind::kI8x16S ||
      lane_extend_info[0].extract_kind == Simd128ExtractLaneOp::Kind::kI8x16U) {
    info.lane_size = 1;
  } else {
    info.lane_size = 2;
  }
  info.is_sign_extract =
      lane_extend_info[0].extract_kind == Simd128ExtractLaneOp::Kind::kI8x16S ||
      lane_extend_info[0].extract_kind == Simd128ExtractLaneOp::Kind::kI16x8S;
  info.is_sign_convert =
      lane_extend_info[0].change_kind == ChangeOp::Kind::kSignedToFloat;
  return info;
}
References v8::internal::compiler::turboshaft::SLPTree::LaneExtendInfo::change_kind, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::extend_from, v8::internal::compiler::turboshaft::SLPTree::LaneExtendInfo::extract_from, v8::internal::compiler::turboshaft::SLPTree::LaneExtendInfo::extract_kind, v8::internal::compiler::turboshaft::SLPTree::LaneExtendInfo::extract_lane_index, v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, v8::internal::compiler::turboshaft::ChangeOp::input(), v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::is_sign_convert, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::is_sign_extract, v8::internal::compiler::turboshaft::ChangeOp::kind, v8::internal::compiler::turboshaft::ChangeOp::kSignedToFloat, v8::internal::compiler::turboshaft::ChangeOp::kUnsignedToFloat, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::lane_size, v8::internal::compiler::turboshaft::SLPTree::LaneExtendInfo::replace_lane_index, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::start_lane, v8::internal::TRACE(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by TryMatchExtendIntToF32x4().
TryMatchExtendIntToF32x4()
bool v8::internal::compiler::turboshaft::SLPTree::TryMatchExtendIntToF32x4 (const NodeGroup & node_group, ExtendIntToF32x4Info * info) [private]
Definition at line 782 of file wasm-revec-reducer.cc.
                                                                   {
  OpIndex node0 = node_group[0];
  OpIndex node1 = node_group[1];
  std::optional<ExtendIntToF32x4Info> info0 = TryGetExtendIntToF32x4Info(node0);
  std::optional<ExtendIntToF32x4Info> info1 = TryGetExtendIntToF32x4Info(node1);
  if (!info0.has_value() || !info1.has_value()) {
    return false;
  }
  if (info0.value().extend_from != info1.value().extend_from ||
      info0.value().is_sign_extract != info1.value().is_sign_extract ||
      info0.value().lane_size != info1.value().lane_size ||
      info0.value().is_sign_convert != info1.value().is_sign_convert) {
    return false;
  }
  uint32_t min_lane_index =
      std::min(info0.value().start_lane, info1.value().start_lane);
  if (std::abs(info0.value().start_lane - info1.value().start_lane) != 4) {
    return false;
  }
  if (info0.value().lane_size == 1) {
    if (min_lane_index != 0 && min_lane_index != 8) {
      return false;
    }
  } else {
    DCHECK_EQ(info0.value().lane_size, 2);
    if (min_lane_index != 0) {
      return false;
    }
  }
  *info = info0.value();
  info->start_lane = min_lane_index;
  return true;
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::SLPTree::ExtendIntToF32x4Info::start_lane, and TryGetExtendIntToF32x4Info().
Referenced by BuildTreeRec().
zone()
Zone* v8::internal::compiler::turboshaft::SLPTree::zone () const [inline], [private]
Definition at line 573 of file wasm-revec-reducer.h.
{ return phase_zone_; }
References phase_zone_.
Member Data Documentation
analyzer_
WasmRevecAnalyzer* v8::internal::compiler::turboshaft::SLPTree::analyzer_ [private]
Definition at line 576 of file wasm-revec-reducer.h.
Referenced by BuildTreeRec(), and GetPackNode().
graph_
Graph& v8::internal::compiler::turboshaft::SLPTree::graph_ [private]
Definition at line 575 of file wasm-revec-reducer.h.
Referenced by BuildTreeRec(), CanBePacked(), graph(), HasInputDependencies(), IsEqual(), NewBundlePackNode(), NewCommutativePackNodeAndRecurs(), NewForcePackNode(), NewIntersectPackNode(), NewPackNode(), NewPackNodeAndRecurs(), NewShufflePackNode(), Print(), Try256ShuffleMatchLoad8x8U(), and TryGetExtendIntToF32x4Info().
node_to_intersect_packnodes_
ZoneUnorderedMap<OpIndex, ZoneVector<PackNode*> > v8::internal::compiler::turboshaft::SLPTree::node_to_intersect_packnodes_ [private]
Definition at line 582 of file wasm-revec-reducer.h.
Referenced by GetIntersectNodeMapping(), GetIntersectPackNodes(), NewIntersectPackNode(), and Print().
node_to_packnode_
ZoneUnorderedMap<OpIndex, PackNode*> v8::internal::compiler::turboshaft::SLPTree::node_to_packnode_ [private]
Definition at line 580 of file wasm-revec-reducer.h.
Referenced by GetNodeMapping(), GetPackNode(), NewBundlePackNode(), NewForcePackNode(), NewPackNode(), NewShufflePackNode(), and Print().
phase_zone_
Zone* v8::internal::compiler::turboshaft::SLPTree::phase_zone_ [private]
Definition at line 577 of file wasm-revec-reducer.h.
Referenced by HasInputDependencies(), NewBundlePackNode(), NewForcePackNode(), NewIntersectPackNode(), NewPackNode(), NewShufflePackNode(), and zone().
RecursionMaxDepth
constexpr size_t v8::internal::compiler::turboshaft::SLPTree::RecursionMaxDepth = 1000 [static], [constexpr], [private]
Definition at line 583 of file wasm-revec-reducer.h.
Referenced by BuildTreeRec().
root_
PackNode* v8::internal::compiler::turboshaft::SLPTree::root_ [private]
Definition at line 578 of file wasm-revec-reducer.h.
Referenced by BuildTree().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.cc