v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo Class Reference
#include <wasm-revec-reducer.h>
Classes
union Param
Public Types
enum class Kind { kS256Load32Transform
, kS256Load64Transform
, kS256Load8x8U
 }
Public Member Functions
Kind kind ()
void set_kind (Kind kind)
void set_splat_index (uint8_t value)
int splat_index () const
Private Attributes
Kind kind_
Param param_
Detailed Description
Definition at line 346 of file wasm-revec-reducer.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::Kind [strong]
Enumerator
kS256Load32Transform
kS256Load64Transform
kS256Load8x8U
Definition at line 348 of file wasm-revec-reducer.h.
                    {
      kS256Load32Transform,
      kS256Load64Transform,
      kS256Load8x8U,
#ifdef V8_TARGET_ARCH_X64
      kShufd,
      kShufps,
      kS32x8UnpackLow,
      kS32x8UnpackHigh,
#endif // V8_TARGET_ARCH_X64
    };
Member Function Documentation
kind()
Kind v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kind () [inline]
Definition at line 367 of file wasm-revec-reducer.h.
{ return kind_; }
References kind_.
Referenced by set_kind(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
set_kind()
void v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::set_kind (Kind kind) [inline]
Definition at line 368 of file wasm-revec-reducer.h.
{ kind_ = kind; }
References kind(), and kind_.
Referenced by v8::internal::compiler::turboshaft::ShufflePackNode::ShufflePackNode().
set_splat_index()
void v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::set_splat_index (uint8_t value) [inline]
Definition at line 370 of file wasm-revec-reducer.h.
                                        {
      DCHECK(kind_ == Kind::kS256Load32Transform ||
             kind_ == Kind::kS256Load64Transform);
      param_.splat_index = value;
    }
References v8::internal::DCHECK(), kind_, kS256Load32Transform, kS256Load64Transform, param_, v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::Param::splat_index, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec().
splat_index()
int v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::splat_index () const [inline]
Definition at line 375 of file wasm-revec-reducer.h.
                            {
      DCHECK(kind_ == Kind::kS256Load32Transform ||
             kind_ == Kind::kS256Load64Transform);
      return param_.splat_index;
    }
References v8::internal::DCHECK(), kind_, kS256Load32Transform, kS256Load64Transform, param_, and v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::Param::splat_index.
Referenced by v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
Member Data Documentation
kind_
Kind v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::kind_ [private]
Definition at line 402 of file wasm-revec-reducer.h.
Referenced by kind(), set_kind(), set_splat_index(), and splat_index().
param_
Param v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::param_ [private]
Definition at line 403 of file wasm-revec-reducer.h.
Referenced by set_splat_index(), and splat_index().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h