v8::internal::CodeEntryStorage Class Reference
#include <profile-generator.h>
Public Member Functions
void AddRef (CodeEntry *)
void DecRef (CodeEntry *)
StringsStorage & strings ()
Static Public Member Functions
template<typename... Args>
static CodeEntry * Create (Args &&... args)
Private Attributes
StringsStorage function_and_resource_names_
Detailed Description
Definition at line 534 of file profile-generator.h.
Member Function Documentation
AddRef()
void v8::internal::CodeEntryStorage::AddRef (CodeEntry * entry)
Definition at line 949 of file profile-generator.cc.
                                              {
  if (entry->is_ref_counted()) entry->AddRef();
}
References v8::internal::CodeEntry::AddRef(), and v8::internal::CodeEntry::is_ref_counted().
Referenced by v8::internal::ProfileNode::ProfileNode().
Create()
template<typename... Args>
static CodeEntry* v8::internal::CodeEntryStorage::Create (Args &&... args) [inline], [static]
Definition at line 537 of file profile-generator.h.
                                           {
    CodeEntry* const entry = new CodeEntry(std::forward<Args>(args)...);
    entry->mark_ref_counted();
    return entry;
  }
References v8::base::args, and v8::internal::CodeEntry::mark_ref_counted().
Referenced by v8::internal::ProfilerListener::CallbackEvent(), v8::internal::ProfilerListener::CodeCreateEvent(), v8::internal::ProfilerCodeObserver::CreateEntriesForRuntimeCallStats(), v8::internal::ProfilerListener::GetterCallbackEvent(), v8::internal::ProfilerListener::RegExpCodeCreateEvent(), v8::internal::ProfilerListener::SetterCallbackEvent(), and v8::internal::ReportBuiltinEventRecord::UpdateCodeMap().
DecRef()
void v8::internal::CodeEntryStorage::DecRef (CodeEntry * entry)
Definition at line 953 of file profile-generator.cc.
                                              {
  if (entry->is_ref_counted() && entry->DecRef() == 0) {
    if (entry->rare_data_) {
      for (auto* inline_entry : entry->rare_data_->inline_entries_) {
        DecRef(inline_entry);
      }
    }
    entry->ReleaseStrings(function_and_resource_names_);
    delete entry;
  }
}
References v8::internal::CodeEntry::DecRef(), function_and_resource_names_, v8::internal::CodeEntry::is_ref_counted(), v8::internal::CodeEntry::rare_data_, and v8::internal::CodeEntry::ReleaseStrings().
Referenced by v8::internal::InstructionStreamMap::Clear(), v8::internal::InstructionStreamMap::ClearCodesInRange(), v8::internal::anonymous_namespace{profiler-listener.cc}::GetOrInsertCachedEntry(), v8::internal::InstructionStreamMap::RemoveCode(), and v8::internal::ProfileNode::~ProfileNode().
strings()
StringsStorage& v8::internal::CodeEntryStorage::strings () [inline]
Definition at line 546 of file profile-generator.h.
{ return function_and_resource_names_; }
Referenced by v8::internal::ProfilerCodeObserver::GetEstimatedMemoryUsage(), and v8::internal::CpuProfiler::~CpuProfiler().
Member Data Documentation
function_and_resource_names_
StringsStorage v8::internal::CodeEntryStorage::function_and_resource_names_ [private]
Definition at line 549 of file profile-generator.h.
Referenced by DecRef().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profile-generator.h
/mnt/V8SourceCode/src/profiler/profile-generator.cc