v8::internal::compiler::JSForInPrepareNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSForInPrepareNode (Node *node)
const ForInParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1737 of file js-operator.h.
Constructor & Destructor Documentation
JSForInPrepareNode()
constexpr v8::internal::compiler::JSForInPrepareNode::JSForInPrepareNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1739 of file js-operator.h.
                                                    : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSForInPrepare, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const ForInParameters& v8::internal::compiler::JSForInPrepareNode::Parameters () const [inline]
Definition at line 1743 of file js-operator.h.
                                            {
    return ForInParametersOf(node()->op());
  }
References v8::internal::compiler::ForInParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h