v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer Class Reference
#include <wasm-gc-typed-optimization-reducer.h>
Public Member Functions
WasmGCTypeAnalyzer (PipelineData *data, Graph &graph, Zone *zone)
void Run ()
wasm::ValueType GetInputTypeOrSentinelType (OpIndex op) const
Private Types
using TypeSnapshotTable = SparseOpIndexSnapshotTable< wasm::ValueType >
using Snapshot = TypeSnapshotTable::Snapshot
using MaybeSnapshot = TypeSnapshotTable::MaybeSnapshot
Private Member Functions
void StartNewSnapshotFor (const Block &block)
void ProcessOperations (const Block &block)
void ProcessBlock (const Block &block)
void ProcessBranchOnTarget (const BranchOp &branch, const Block &target)
void ProcessTypeCast (const WasmTypeCastOp &type_cast)
void ProcessTypeCheck (const WasmTypeCheckOp &type_check)
void ProcessAssertNotNull (const AssertNotNullOp &type_cast)
void ProcessNull (const NullOp &null)
void ProcessIsNull (const IsNullOp &is_null)
void ProcessParameter (const ParameterOp &parameter)
void ProcessStructGet (const StructGetOp &struct_get)
void ProcessStructSet (const StructSetOp &struct_set)
void ProcessArrayGet (const ArrayGetOp &array_get)
void ProcessArrayLength (const ArrayLengthOp &array_length)
void ProcessGlobalGet (const GlobalGetOp &global_get)
void ProcessRefFunc (const WasmRefFuncOp &ref_func)
void ProcessAllocateArray (const WasmAllocateArrayOp &allocate_array)
void ProcessAllocateStruct (const WasmAllocateStructOp &allocate_struct)
void ProcessPhi (const PhiOp &phi)
void ProcessTypeAnnotation (const WasmTypeAnnotationOp &type_annotation)
wasm::ValueType GetTypeForPhiInput (const PhiOp &phi, int input_index)
void CreateMergeSnapshot (const Block &block)
bool CreateMergeSnapshot (base::Vector< const Snapshot > predecessors, base::Vector< const bool > reachable)
wasm::ValueType RefineTypeKnowledge (OpIndex object, wasm::ValueType new_type, const Operation &op)
wasm::ValueType RefineTypeKnowledgeNotNull (OpIndex object, const Operation &op)
OpIndex ResolveAliases (OpIndex object) const
wasm::ValueType GetResolvedType (OpIndex object) const
bool IsReachable (const Block &block) const
Private Attributes
PipelineData * data_
Graph & graph_
Zone * phase_zone_
const wasm::WasmModule * module_ = data_->wasm_module()
const wasm::FunctionSig * signature_ = data_->wasm_module_sig()
TypeSnapshotTable types_table_ {phase_zone_}
FixedBlockSidetable< MaybeSnapshot > block_to_snapshot_
BitVector block_is_unreachable_
const Block * current_block_ = nullptr
ZoneUnorderedMap< OpIndex, wasm::ValueType > input_type_map_ {phase_zone_}
bool is_first_loop_header_evaluation_ = false
Detailed Description
Definition at line 43 of file wasm-gc-typed-optimization-reducer.h.
Member Typedef Documentation
MaybeSnapshot
using v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::MaybeSnapshot = TypeSnapshotTable::MaybeSnapshot [private]
Definition at line 65 of file wasm-gc-typed-optimization-reducer.h.
Snapshot
using v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Snapshot = TypeSnapshotTable::Snapshot [private]
Definition at line 64 of file wasm-gc-typed-optimization-reducer.h.
TypeSnapshotTable
using v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::TypeSnapshotTable = SparseOpIndexSnapshotTable<wasm::ValueType> [private]
Definition at line 63 of file wasm-gc-typed-optimization-reducer.h.
Constructor & Destructor Documentation
WasmGCTypeAnalyzer()
v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::WasmGCTypeAnalyzer (PipelineData * data, Graph & graph, Zone * zone) [inline]
Definition at line 45 of file wasm-gc-typed-optimization-reducer.h.
      : data_(data), graph_(graph), phase_zone_(zone) {
    // If we ever want to run this analyzer for Wasm wrappers, we'll need
    // to make it handle their {CanonicalSig} signatures.
    DCHECK_NOT_NULL(signature_);
  }
References DCHECK_NOT_NULL, and signature_.
Member Function Documentation
CreateMergeSnapshot() [1/2]
bool v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot (base::Vector< const Snapshot > predecessors, base::Vector< const bool > reachable) [private]
Definition at line 511 of file wasm-gc-typed-optimization-reducer.cc.
                                      {
  DCHECK_EQ(predecessors.size(), reachable.size());
  // The merging logic is also used to evaluate if two snapshots are
  // "identical", i.e. the known types for all operations are the same.
  bool types_are_equivalent = true;
  types_table_.StartNewSnapshot(
      predecessors, [this, &types_are_equivalent, reachable](
                        TypeSnapshotTable::Key,
                        base::Vector<const wasm::ValueType> predecessors) {
        DCHECK_GT(predecessors.size(), 1);
        size_t i = 0;
        // Initialize the type based on the first reachable predecessor.
        wasm::ValueType first = wasm::kWasmBottom;
        for (; i < reachable.size(); ++i) {
          // Uninhabitated types can only occur in unreachable code e.g. as a
          // result of an always failing cast. Still reachability tracking might
          // in some cases miss that a block becomes unreachable, so we still
          // check for uninhabited in the if below.
          DCHECK_IMPLIES(reachable[i], !predecessors[i].is_uninhabited());
          if (reachable[i] && !predecessors[i].is_uninhabited()) {
            first = predecessors[i];
            ++i;
            break;
          }
        }
        wasm::ValueType res = first;
        for (; i < reachable.size(); ++i) {
          if (!reachable[i]) continue; // Skip unreachable predecessors.
          wasm::ValueType type = predecessors[i];
          // Uninhabitated types can only occur in unreachable code e.g. as a
          // result of an always failing cast. Still reachability tracking might
          // in some cases miss that a block becomes unreachable, so we still
          // check for uninhabited in the if below.
          DCHECK(!type.is_uninhabited());
          if (type.is_uninhabited()) continue;
          types_are_equivalent &= first == type;
          if (res == wasm::ValueType() || type == wasm::ValueType()) {
            res = wasm::ValueType();
          } else {
            res = wasm::Union(res, type, module_).type;
          }
        }
        return res;
      });
  return !types_are_equivalent;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kWasmBottom, module_, v8::base::Vector< T >::size(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), v8::internal::tracing::type, v8::internal::wasm::TypeInModule::type, types_table_, and v8::internal::wasm::Union().
CreateMergeSnapshot() [2/2]
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::CreateMergeSnapshot (const Block & block) [private]
Definition at line 475 of file wasm-gc-typed-optimization-reducer.cc.
                                                               {
  base::SmallVector<Snapshot, 8> snapshots;
  // Unreachable predecessors should be ignored when merging but we can't remove
  // them from the predecessors as that would mess up the phi inputs. Therefore
  // the reachability of the predecessors is passed as a separate list.
  base::SmallVector<bool, 8> reachable;
  bool all_predecessors_unreachable = true;
  for (const Block* predecessor : block.PredecessorsIterable()) {
    snapshots.push_back(block_to_snapshot_[predecessor->index()].value());
    bool predecessor_reachable = IsReachable(*predecessor);
    reachable.push_back(predecessor_reachable);
    all_predecessors_unreachable &= !predecessor_reachable;
  }
  if (all_predecessors_unreachable) {
    TRACE("[b%u] Block unreachable as all predecessors are unreachable\n",
          block.index().id());
    block_is_unreachable_.Add(block.index().id());
  } else if (v8_flags.trace_wasm_typer) {
    std::stringstream str;
    size_t i = 0;
    for (const Block* predecessor : block.PredecessorsIterable()) {
      if (i != 0) str << ", ";
      str << 'b' << predecessor->index().id() << (reachable[i] ? "" : "u");
      ++i;
    }
    TRACE("[b%u] Predecessors reachability: %s\n", block.index().id(),
          str.str().c_str());
  }
  // The predecessor snapshots need to be reversed to restore the "original"
  // order of predecessors. (This is used to map phi inputs to their
  // corresponding predecessor.)
  std::reverse(snapshots.begin(), snapshots.end());
  std::reverse(reachable.begin(), reachable.end());
  CreateMergeSnapshot(base::VectorOf(snapshots), base::VectorOf(reachable));
}
References v8::internal::BitVector::Add(), v8::base::SmallVector< T, kSize, Allocator >::begin(), block_is_unreachable_, block_to_snapshot_, v8::base::SmallVector< T, kSize, Allocator >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), IsReachable(), v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::TRACE(), v8::internal::v8_flags, and v8::base::VectorOf().
Referenced by Run(), and StartNewSnapshotFor().
GetInputTypeOrSentinelType()
wasm::ValueType v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType (OpIndex op) const [inline]
Definition at line 56 of file wasm-gc-typed-optimization-reducer.h.
                                                             {
    auto iter = input_type_map_.find(op);
    DCHECK_NE(iter, input_type_map_.end());
    return iter->second;
  }
References DCHECK_NE, and input_type_map_.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::ArrayLength(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AssertNotNull(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
GetResolvedType()
wasm::ValueType v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetResolvedType (OpIndex object) const [private]
Definition at line 636 of file wasm-gc-typed-optimization-reducer.cc.
                                                                      {
  return types_table_.Get(ResolveAliases(object));
}
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), ResolveAliases(), and types_table_.
Referenced by ProcessBranchOnTarget(), ProcessIsNull(), ProcessPhi(), and ProcessTypeCheck().
GetTypeForPhiInput()
wasm::ValueType v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput (const PhiOp & phi, int input_index) [private]
Definition at line 349 of file wasm-gc-typed-optimization-reducer.cc.
                                                                        {
  OpIndex phi_id = graph_.Index(phi);
  OpIndex input = ResolveAliases(phi.input(input_index));
  // If the input of the phi is in the same block as the phi and appears
  // before the phi, don't use the predecessor value.
  if (current_block_->begin().id() <= input.id() && input.id() < phi_id.id()) {
    // Phi instructions have to be at the beginning of the block, so this can
    // only happen for inputs that are also phis. Furthermore, this is only
    // possible in loop headers of loops and only for the backedge-input.
    DCHECK(graph_.Get(input).Is<PhiOp>());
    DCHECK(current_block_->IsLoop());
    DCHECK_EQ(input_index, 1);
    return types_table_.Get(input);
  }
  return types_table_.GetPredecessorValue(input, input_index);
}
References v8::internal::compiler::turboshaft::Block::begin(), current_block_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::GetPredecessorValue(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Block::IsLoop(), ResolveAliases(), and types_table_.
Referenced by ProcessPhi().
IsReachable()
bool v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::IsReachable (const Block & block) const [private]
Definition at line 632 of file wasm-gc-typed-optimization-reducer.cc.
                                                             {
  return !block_is_unreachable_.Contains(block.index().id());
}
References block_is_unreachable_, v8::internal::BitVector::Contains(), v8::internal::compiler::turboshaft::BlockIndex::id(), and v8::internal::compiler::turboshaft::Block::index().
Referenced by CreateMergeSnapshot(), RefineTypeKnowledge(), RefineTypeKnowledgeNotNull(), Run(), and StartNewSnapshotFor().
ProcessAllocateArray()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateArray (const WasmAllocateArrayOp & allocate_array) [private]
Definition at line 308 of file wasm-gc-typed-optimization-reducer.cc.
                                               {
  wasm::ModuleTypeIndex type_index =
      graph_.Get(allocate_array.rtt()).Cast<RttCanonOp>().type_index;
  RefineTypeKnowledge(graph_.Index(allocate_array),
                      wasm::ValueType::Ref(module_->heap_type(type_index)),
                      allocate_array);
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::wasm::WasmModule::heap_type(), v8::internal::compiler::turboshaft::Graph::Index(), module_, v8::internal::wasm::ValueType::Ref(), and RefineTypeKnowledge().
Referenced by ProcessOperations().
ProcessAllocateStruct()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct (const WasmAllocateStructOp & allocate_struct) [private]
Definition at line 317 of file wasm-gc-typed-optimization-reducer.cc.
                                                 {
  Operation& rtt = graph_.Get(allocate_struct.rtt());
  wasm::ModuleTypeIndex type_index;
  if (RttCanonOp* canon = rtt.TryCast<RttCanonOp>()) {
    type_index = canon->type_index;
  } else if (LoadOp* load = rtt.TryCast<LoadOp>()) {
    DCHECK(load->kind.tagged_base && load->offset == WasmStruct::kHeaderSize);
    OpIndex descriptor = load->base();
    wasm::ValueType desc_type = types_table_.Get(descriptor);
    if (!desc_type.has_index()) {
      // We hope that this happens rarely or never. If there is evidence that
      // we get this case a lot, we should store the original struct.new
      // operation's type index immediate on the {WasmAllocateStructOp} to
      // use it as a better upper bound than "structref" here.
      RefineTypeKnowledge(graph_.Index(allocate_struct), wasm::kWasmStructRef,
                          allocate_struct);
      return;
    }
    const wasm::TypeDefinition& desc_typedef =
        module_->type(desc_type.ref_index());
    DCHECK(desc_typedef.is_descriptor());
    type_index = desc_typedef.describes;
  } else {
    // The graph builder only emits the two patterns above.
    UNREACHABLE();
  }
  RefineTypeKnowledge(graph_.Index(allocate_struct),
                      wasm::ValueType::Ref(module_->heap_type(type_index)),
                      allocate_struct);
}
References v8::internal::DCHECK(), v8::internal::wasm::TypeDefinition::describes, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), graph_, v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::WasmModule::heap_type(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::wasm::TypeDefinition::is_descriptor(), v8::internal::wasm::kWasmStructRef, module_, v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::ref_index(), RefineTypeKnowledge(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::wasm::WasmModule::type(), types_table_, and v8::internal::UNREACHABLE().
Referenced by ProcessOperations().
ProcessArrayGet()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessArrayGet (const ArrayGetOp & array_get) [private]
Definition at line 278 of file wasm-gc-typed-optimization-reducer.cc.
                                                                    {
  // array.get traps on null. (Typically already on the array length access
  // needed for the bounds check.)
  RefineTypeKnowledgeNotNull(array_get.array(), array_get);
  // The result type is at least the static array element type.
  RefineTypeKnowledge(graph_.Index(array_get),
                      array_get.array_type->element_type().Unpacked(),
                      array_get);
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), RefineTypeKnowledge(), and RefineTypeKnowledgeNotNull().
Referenced by ProcessOperations().
ProcessArrayLength()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessArrayLength (const ArrayLengthOp & array_length) [private]
Definition at line 288 of file wasm-gc-typed-optimization-reducer.cc.
                                                                             {
  // array.len performs a null check.
  wasm::ValueType type =
      RefineTypeKnowledgeNotNull(array_length.array(), array_length);
  input_type_map_[graph_.Index(array_length)] = type;
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), input_type_map_, RefineTypeKnowledgeNotNull(), and v8::internal::tracing::type.
Referenced by ProcessOperations().
ProcessAssertNotNull()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAssertNotNull (const AssertNotNullOp & type_cast) [private]
Definition at line 240 of file wasm-gc-typed-optimization-reducer.cc.
                                            {
  V<Object> object = assert_not_null.object();
  wasm::ValueType new_type = assert_not_null.type.AsNonNull();
  wasm::ValueType known_input_type =
      RefineTypeKnowledge(object, new_type, assert_not_null);
  input_type_map_[graph_.Index(assert_not_null)] = known_input_type;
}
References v8::internal::wasm::ValueType::AsNonNull(), graph_, v8::internal::compiler::turboshaft::Graph::Index(), input_type_map_, and RefineTypeKnowledge().
Referenced by ProcessOperations().
ProcessBlock()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBlock (const Block & block) [private]
Definition at line 85 of file wasm-gc-typed-optimization-reducer.cc.
                                                        {
  DCHECK_NULL(current_block_);
  current_block_ = &block;
  StartNewSnapshotFor(block);
  ProcessOperations(block);
  current_block_ = nullptr;
}
References current_block_, DCHECK_NULL, ProcessOperations(), and StartNewSnapshotFor().
Referenced by Run().
ProcessBranchOnTarget()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget (const BranchOp & branch, const Block & target) [private]
Definition at line 415 of file wasm-gc-typed-optimization-reducer.cc.
                                                                    {
  DCHECK_EQ(current_block_, &target);
  const Operation& condition = graph_.Get(branch.condition());
  switch (condition.opcode) {
    case Opcode::kWasmTypeCheck: {
      const WasmTypeCheckOp& check = condition.Cast<WasmTypeCheckOp>();
      if (branch.if_true == &target) {
        // It is known from now on that the type is at least the checked one.
        RefineTypeKnowledge(check.object(), check.config.to, branch);
      } else {
        DCHECK_EQ(branch.if_false, &target);
        if (wasm::IsSubtypeOf(GetResolvedType(check.object()), check.config.to,
                              module_)) {
          // The type check always succeeds, the target is impossible to be
          // reached.
          DCHECK_EQ(target.PredecessorCount(), 1);
          block_is_unreachable_.Add(target.index().id());
          TRACE(
              "[b%uu] Block unreachable as #%u(%s) used in #%u(%s) is always "
              "true\n",
              target.index().id(), branch.condition().id(),
              OpcodeName(condition.opcode), graph_.Index(branch).id(),
              OpcodeName(branch.opcode));
        }
      }
    } break;
    case Opcode::kIsNull: {
      const IsNullOp& is_null = condition.Cast<IsNullOp>();
      if (branch.if_true == &target) {
        if (GetResolvedType(is_null.object()).is_non_nullable()) {
          // The target is impossible to be reached.
          DCHECK_EQ(target.PredecessorCount(), 1);
          block_is_unreachable_.Add(target.index().id());
          TRACE(
              "[b%uu] Block unreachable as #%u(%s) used in #%u(%s) is always "
              "false\n",
              target.index().id(), branch.condition().id(),
              OpcodeName(condition.opcode), graph_.Index(branch).id(),
              OpcodeName(branch.opcode));
          return;
        }
        RefineTypeKnowledge(is_null.object(),
                            wasm::ToNullSentinel({is_null.type, module_}),
                            branch);
      } else {
        DCHECK_EQ(branch.if_false, &target);
        RefineTypeKnowledge(is_null.object(), is_null.type.AsNonNull(), branch);
      }
    } break;
    default:
      break;
  }
}
References v8::internal::BitVector::Add(), block_is_unreachable_, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::BranchOp::condition(), current_block_, DCHECK_EQ, v8::internal::compiler::turboshaft::Graph::Get(), GetResolvedType(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::IsSubtypeOf(), module_, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OperationT< Derived >::opcode, v8::internal::compiler::turboshaft::OpcodeName(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), RefineTypeKnowledge(), v8::internal::wasm::ToNullSentinel(), and v8::internal::TRACE().
Referenced by StartNewSnapshotFor().
ProcessGlobalGet()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessGlobalGet (const GlobalGetOp & global_get) [private]
Definition at line 295 of file wasm-gc-typed-optimization-reducer.cc.
                                                                       {
  RefineTypeKnowledge(graph_.Index(global_get), global_get.global->type,
                      global_get);
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), and RefineTypeKnowledge().
Referenced by ProcessOperations().
ProcessIsNull()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessIsNull (const IsNullOp & is_null) [private]
Definition at line 249 of file wasm-gc-typed-optimization-reducer.cc.
                                                              {
  input_type_map_[graph_.Index(is_null)] = GetResolvedType(is_null.object());
}
References GetResolvedType(), graph_, v8::internal::compiler::turboshaft::Graph::Index(), and input_type_map_.
Referenced by ProcessOperations().
ProcessNull()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessNull (const NullOp & null) [private]
Definition at line 470 of file wasm-gc-typed-optimization-reducer.cc.
                                                       {
  wasm::ValueType null_type = wasm::ToNullSentinel({null.type, module_});
  RefineTypeKnowledge(graph_.Index(null), null_type, null);
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), module_, RefineTypeKnowledge(), and v8::internal::wasm::ToNullSentinel().
Referenced by ProcessOperations().
ProcessOperations()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessOperations (const Block & block) [private]
Definition at line 166 of file wasm-gc-typed-optimization-reducer.cc.
                                                             {
  for (OpIndex op_idx : graph_.OperationIndices(block)) {
    Operation& op = graph_.Get(op_idx);
    switch (op.opcode) {
      case Opcode::kWasmTypeCast:
        ProcessTypeCast(op.Cast<WasmTypeCastOp>());
        break;
      case Opcode::kWasmTypeCheck:
        ProcessTypeCheck(op.Cast<WasmTypeCheckOp>());
        break;
      case Opcode::kAssertNotNull:
        ProcessAssertNotNull(op.Cast<AssertNotNullOp>());
        break;
      case Opcode::kNull:
        ProcessNull(op.Cast<NullOp>());
        break;
      case Opcode::kIsNull:
        ProcessIsNull(op.Cast<IsNullOp>());
        break;
      case Opcode::kParameter:
        ProcessParameter(op.Cast<ParameterOp>());
        break;
      case Opcode::kStructGet:
        ProcessStructGet(op.Cast<StructGetOp>());
        break;
      case Opcode::kStructSet:
        ProcessStructSet(op.Cast<StructSetOp>());
        break;
      case Opcode::kArrayGet:
        ProcessArrayGet(op.Cast<ArrayGetOp>());
        break;
      case Opcode::kArrayLength:
        ProcessArrayLength(op.Cast<ArrayLengthOp>());
        break;
      case Opcode::kGlobalGet:
        ProcessGlobalGet(op.Cast<GlobalGetOp>());
        break;
      case Opcode::kWasmRefFunc:
        ProcessRefFunc(op.Cast<WasmRefFuncOp>());
        break;
      case Opcode::kWasmAllocateArray:
        ProcessAllocateArray(op.Cast<WasmAllocateArrayOp>());
        break;
      case Opcode::kWasmAllocateStruct:
        ProcessAllocateStruct(op.Cast<WasmAllocateStructOp>());
        break;
      case Opcode::kPhi:
        ProcessPhi(op.Cast<PhiOp>());
        break;
      case Opcode::kWasmTypeAnnotation:
        ProcessTypeAnnotation(op.Cast<WasmTypeAnnotationOp>());
        break;
      case Opcode::kBranch:
        // Handling branch conditions implying special values is handled on the
        // beginning of the successor block.
      default:
        break;
    }
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::OperationIndices(), ProcessAllocateArray(), ProcessAllocateStruct(), ProcessArrayGet(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessGlobalGet(), ProcessIsNull(), ProcessNull(), ProcessParameter(), ProcessPhi(), ProcessRefFunc(), ProcessStructGet(), ProcessStructSet(), ProcessTypeAnnotation(), ProcessTypeCast(), and ProcessTypeCheck().
Referenced by ProcessBlock().
ProcessParameter()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessParameter (const ParameterOp & parameter) [private]
Definition at line 253 of file wasm-gc-typed-optimization-reducer.cc.
                                                                      {
  if (parameter.parameter_index != wasm::kWasmInstanceDataParameterIndex) {
    RefineTypeKnowledge(graph_.Index(parameter),
                        signature_->GetParam(parameter.parameter_index - 1),
                        parameter);
  }
}
References v8::internal::Signature< T >::GetParam(), graph_, v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::wasm::kWasmInstanceDataParameterIndex, v8::internal::compiler::turboshaft::ParameterOp::parameter_index, RefineTypeKnowledge(), and signature_.
Referenced by ProcessOperations().
ProcessPhi()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi (const PhiOp & phi) [private]
Definition at line 368 of file wasm-gc-typed-optimization-reducer.cc.
                                                    {
  // The result type of a phi is the union of all its input types.
  // If any of the inputs is the default value ValueType(), there isn't any type
  // knowledge inferrable.
  DCHECK_GT(phi.input_count, 0);
  if (is_first_loop_header_evaluation_) {
    // We don't know anything about the backedge yet, so we only use the
    // forward edge. We will revisit the loop header again once the block with
    // the back edge is evaluated.
    RefineTypeKnowledge(graph_.Index(phi), GetResolvedType((phi.input(0))),
                        phi);
    return;
  }
  wasm::ValueType union_type = GetTypeForPhiInput(phi, 0);
  if (union_type == wasm::ValueType()) return;
  for (int i = 1; i < phi.input_count; ++i) {
    wasm::ValueType input_type = GetTypeForPhiInput(phi, i);
    if (input_type == wasm::ValueType()) return;
    // <bottom> types have to be skipped as an unreachable predecessor doesn't
    // change our type knowledge.
    // TODO(mliedtke): Ideally, we'd skip unreachable predecessors here
    // completely, as we might loosen the known type due to an unreachable
    // predecessor.
    if (input_type.is_uninhabited()) continue;
    if (union_type.is_uninhabited()) {
      union_type = input_type;
    } else {
      union_type = wasm::Union(union_type, input_type, module_).type;
    }
  }
  RefineTypeKnowledge(graph_.Index(phi), union_type, phi);
  if (v8_flags.trace_wasm_typer) {
    for (int i = 0; i < phi.input_count; ++i) {
      OpIndex input = phi.input(i);
      wasm::ValueType type = GetTypeForPhiInput(phi, i);
      TRACE("- phi input %d: #%u(%s) -> %s\n", i, input.id(),
            OpcodeName(graph_.Get(input).opcode), type.name().c_str());
    }
  }
}
References DCHECK_GT, v8::internal::compiler::turboshaft::Graph::Get(), GetResolvedType(), GetTypeForPhiInput(), graph_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::turboshaft::Operation::input_count, is_first_loop_header_evaluation_, v8::internal::wasm::ValueTypeBase::is_uninhabited(), module_, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OpcodeName(), RefineTypeKnowledge(), v8::internal::TRACE(), v8::internal::tracing::type, v8::internal::wasm::TypeInModule::type, v8::internal::wasm::Union(), and v8::internal::v8_flags.
Referenced by ProcessOperations().
ProcessRefFunc()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessRefFunc (const WasmRefFuncOp & ref_func) [private]
Definition at line 300 of file wasm-gc-typed-optimization-reducer.cc.
                                                                     {
  wasm::ModuleTypeIndex sig_index =
      module_->functions[ref_func.function_index].sig_index;
  RefineTypeKnowledge(graph_.Index(ref_func),
                      wasm::ValueType::Ref(module_->heap_type(sig_index)),
                      ref_func);
}
References v8::internal::wasm::WasmModule::functions, graph_, v8::internal::wasm::WasmModule::heap_type(), v8::internal::compiler::turboshaft::Graph::Index(), module_, v8::internal::wasm::ValueType::Ref(), and RefineTypeKnowledge().
Referenced by ProcessOperations().
ProcessStructGet()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessStructGet (const StructGetOp & struct_get) [private]
Definition at line 261 of file wasm-gc-typed-optimization-reducer.cc.
                                                                       {
  // struct.get performs a null check.
  wasm::ValueType type =
      RefineTypeKnowledgeNotNull(struct_get.object(), struct_get);
  input_type_map_[graph_.Index(struct_get)] = type;
  RefineTypeKnowledge(graph_.Index(struct_get),
                      struct_get.type->field(struct_get.field_index).Unpacked(),
                      struct_get);
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), input_type_map_, RefineTypeKnowledge(), RefineTypeKnowledgeNotNull(), and v8::internal::tracing::type.
Referenced by ProcessOperations().
ProcessStructSet()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessStructSet (const StructSetOp & struct_set) [private]
Definition at line 271 of file wasm-gc-typed-optimization-reducer.cc.
                                                                       {
  // struct.set performs a null check.
  wasm::ValueType type =
      RefineTypeKnowledgeNotNull(struct_set.object(), struct_set);
  input_type_map_[graph_.Index(struct_set)] = type;
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), input_type_map_, RefineTypeKnowledgeNotNull(), and v8::internal::tracing::type.
Referenced by ProcessOperations().
ProcessTypeAnnotation()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessTypeAnnotation (const WasmTypeAnnotationOp & type_annotation) [private]
Definition at line 409 of file wasm-gc-typed-optimization-reducer.cc.
                                                 {
  RefineTypeKnowledge(type_annotation.value(), type_annotation.type,
                      type_annotation);
}
References RefineTypeKnowledge().
Referenced by ProcessOperations().
ProcessTypeCast()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessTypeCast (const WasmTypeCastOp & type_cast) [private]
Definition at line 227 of file wasm-gc-typed-optimization-reducer.cc.
                                                                        {
  V<Object> object = type_cast.object();
  wasm::ValueType target_type = type_cast.config.to;
  wasm::ValueType known_input_type =
      RefineTypeKnowledge(object, target_type, type_cast);
  input_type_map_[graph_.Index(type_cast)] = known_input_type;
}
References graph_, v8::internal::compiler::turboshaft::Graph::Index(), input_type_map_, and RefineTypeKnowledge().
Referenced by ProcessOperations().
ProcessTypeCheck()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessTypeCheck (const WasmTypeCheckOp & type_check) [private]
Definition at line 235 of file wasm-gc-typed-optimization-reducer.cc.
                                                                           {
  wasm::ValueType type = GetResolvedType(type_check.object());
  input_type_map_[graph_.Index(type_check)] = type;
}
References GetResolvedType(), graph_, v8::internal::compiler::turboshaft::Graph::Index(), input_type_map_, and v8::internal::tracing::type.
Referenced by ProcessOperations().
RefineTypeKnowledge()
wasm::ValueType v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge (OpIndex object, wasm::ValueType new_type, const Operation & op) [private]
Definition at line 561 of file wasm-gc-typed-optimization-reducer.cc.
                                                                 {
  DCHECK_NOT_NULL(current_block_);
  object = ResolveAliases(object);
  wasm::ValueType previous_value = types_table_.Get(object);
  wasm::ValueType intersection_type =
      previous_value == wasm::ValueType()
          ? new_type
          : wasm::Intersection(previous_value, new_type, module_).type;
  if (intersection_type == previous_value) return previous_value;
  TRACE("[b%u%s] #%u(%s): Refine type for object #%u(%s) -> %s%s\n",
        current_block_->index().id(), !IsReachable(*current_block_) ? "u" : "",
        graph_.Index(op).id(), OpcodeName(op.opcode), object.id(),
        OpcodeName(graph_.Get(object).opcode), intersection_type.name().c_str(),
        intersection_type.is_uninhabited() ? " (unreachable!)" : "");
  types_table_.Set(object, intersection_type);
  if (intersection_type.is_uninhabited()) {
    // After this instruction all other instructions in the current block are
    // unreachable.
    block_is_unreachable_.Add(current_block_->index().id());
    // Return bottom to indicate that the operation `op` shall always trap.
    return wasm::kWasmBottom;
  }
  return previous_value;
}
References v8::internal::BitVector::Add(), block_is_unreachable_, current_block_, DCHECK_NOT_NULL, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::wasm::Intersection(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), IsReachable(), v8::internal::wasm::kWasmBottom, module_, v8::internal::wasm::ValueTypeBase::name(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OpcodeName(), ResolveAliases(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), v8::internal::TRACE(), v8::internal::wasm::TypeInModule::type, and types_table_.
Referenced by ProcessAllocateArray(), ProcessAllocateStruct(), ProcessArrayGet(), ProcessAssertNotNull(), ProcessBranchOnTarget(), ProcessGlobalGet(), ProcessNull(), ProcessParameter(), ProcessPhi(), ProcessRefFunc(), ProcessStructGet(), ProcessTypeAnnotation(), and ProcessTypeCast().
RefineTypeKnowledgeNotNull()
wasm::ValueType v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull (OpIndex object, const Operation & op) [private]
Definition at line 589 of file wasm-gc-typed-optimization-reducer.cc.
                                         {
  object = ResolveAliases(object);
  wasm::ValueType previous_value = types_table_.Get(object);
  if (previous_value.is_non_nullable()) return previous_value;
  wasm::ValueType not_null_type = previous_value.AsNonNull();
  TRACE("[b%u%s] #%u(%s): Refine type for object #%u(%s) -> %s%s\n",
        current_block_->index().id(), !IsReachable(*current_block_) ? "u" : "",
        graph_.Index(op).id(), OpcodeName(op.opcode), object.id(),
        OpcodeName(graph_.Get(object).opcode), not_null_type.name().c_str(),
        not_null_type.is_uninhabited() ? " (unreachable!)" : "");
  types_table_.Set(object, not_null_type);
  if (not_null_type.is_uninhabited()) {
    // After this instruction all other instructions in the current block are
    // unreachable.
    block_is_unreachable_.Add(current_block_->index().id());
    // Return bottom to indicate that the operation `op` shall always trap.
    return wasm::kWasmBottom;
  }
  return previous_value;
}
References v8::internal::BitVector::Add(), v8::internal::wasm::ValueType::AsNonNull(), block_is_unreachable_, current_block_, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::wasm::ValueTypeBase::is_non_nullable(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), IsReachable(), v8::internal::wasm::kWasmBottom, v8::internal::wasm::ValueTypeBase::name(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OpcodeName(), ResolveAliases(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), v8::internal::TRACE(), and types_table_.
Referenced by ProcessArrayGet(), ProcessArrayLength(), ProcessStructGet(), and ProcessStructSet().
ResolveAliases()
OpIndex v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ResolveAliases (OpIndex object) const [private]
Definition at line 613 of file wasm-gc-typed-optimization-reducer.cc.
                                                               {
  while (true) {
    const Operation* op = &graph_.Get(object);
    switch (op->opcode) {
      case Opcode::kWasmTypeCast:
        object = op->Cast<WasmTypeCastOp>().object();
        break;
      case Opcode::kAssertNotNull:
        object = op->Cast<AssertNotNullOp>().object();
        break;
      case Opcode::kWasmTypeAnnotation:
        object = op->Cast<WasmTypeAnnotationOp>().value();
        break;
      default:
        return object;
    }
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Operation::opcode, and v8::internal::value.
Referenced by GetResolvedType(), GetTypeForPhiInput(), RefineTypeKnowledge(), and RefineTypeKnowledgeNotNull().
Run()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run ()
Definition at line 18 of file wasm-gc-typed-optimization-reducer.cc.
                             {
  LoopFinder loop_finder(phase_zone_, &graph_, LoopFinder::Config{});
  AnalyzerIterator iterator(phase_zone_, graph_, loop_finder);
  while (iterator.HasNext()) {
    const Block& block = *iterator.Next();
    ProcessBlock(block);
    // Finish snapshot.
    block_to_snapshot_[block.index()] = MaybeSnapshot(types_table_.Seal());
    // Consider re-processing for loops.
    if (const GotoOp* last = block.LastOperation(graph_).TryCast<GotoOp>()) {
      if (IsReachable(block) && last->destination->IsLoop() &&
          last->destination->LastPredecessor() == &block) {
        TRACE("[b%u] Reprocessing loop header b%u at backedge #%u\n",
              block.index().id(), last->destination->index().id(),
              graph_.Index(block.LastOperation(graph_)).id());
        const Block& loop_header = *last->destination;
        // Create a merged snapshot state for the forward- and backedge and
        // process all operations inside the loop header.
        ProcessBlock(loop_header);
        Snapshot old_snapshot = block_to_snapshot_[loop_header.index()].value();
        Snapshot snapshot = types_table_.Seal();
        // TODO(14108): The snapshot isn't needed at all, we only care about the
        // information if two snapshots are equivalent. Unfortunately, currently
        // this can only be answered by creating a merge snapshot.
        bool needs_revisit =
            CreateMergeSnapshot(base::VectorOf({old_snapshot, snapshot}),
                                base::VectorOf({true, true}));
        types_table_.Seal(); // Discard the snapshot.
        TRACE("[b%u] Loop header b%u reprocessed at backedge #%u: %s\n",
              block.index().id(), last->destination->index().id(),
              graph_.Index(block.LastOperation(graph_)).id(),
              needs_revisit ? "Scheduling loop body revisitation"
                            : "No revisit of loop body needed");
        // TODO(14108): This currently encodes a fixed point analysis where the
        // analysis is finished once the backedge doesn't provide updated type
        // information any more compared to the previous iteration. This could
        // be stopped in cases where the backedge only refines types (i.e. only
        // defines more precise types than the previous iteration).
        if (needs_revisit) {
          block_to_snapshot_[loop_header.index()] = MaybeSnapshot(snapshot);
          if (block.index() != loop_header.index()) {
            // This will push the successors of the loop header to the iterator
            // stack, so the loop body will be visited in the next iteration.
            iterator.MarkLoopForRevisitSkipHeader();
          } else {
            // A single-block loop doesn't have any successors which would be
            // re-evaluated and which might trigger another re-evaluation of the
            // loop header.
            // TODO(mliedtke): This is not a great design: We don't just
            // schedule revisiting the loop header but afterwards we revisit it
            // once again to evaluate whether we need to revisit it more times,
            // so for single block loops the revisitation count will always be a
            // multiple of 2. While this is inefficient, single-block loops are
            // rare and are either endless loops or need to trigger an exception
            // (e.g. a wasm trap) to terminate.
            iterator.MarkLoopForRevisit();
          }
        }
      }
    }
  }
}
References block_to_snapshot_, CreateMergeSnapshot(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Graph::Index(), IsReachable(), v8::internal::compiler::turboshaft::Block::LastOperation(), phase_zone_, ProcessBlock(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::TRACE(), v8::internal::compiler::turboshaft::Operation::TryCast(), types_table_, and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::Analyze().
StartNewSnapshotFor()
void v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor (const Block & block) [private]
Definition at line 93 of file wasm-gc-typed-optimization-reducer.cc.
                                                               {
  is_first_loop_header_evaluation_ = false;
  // Reset reachability information. This can be outdated in case of loop
  // revisits. Below the reachability is calculated again and potentially
  // re-added.
  bool block_was_previously_reachable = IsReachable(block);
  if (!block_was_previously_reachable) {
    TRACE("[b%u] Removing unreachable flag as block is re-evaluated\n",
          block.index().id());
  }
  block_is_unreachable_.Remove(block.index().id());
  // Start new snapshot based on predecessor information.
  if (block.HasPredecessors() == 0) {
    // The first block just starts with an empty snapshot.
    DCHECK_EQ(block.index().id(), 0);
    types_table_.StartNewSnapshot();
  } else if (block.IsLoop()) {
    const Block& forward_predecessor =
        *block.LastPredecessor()->NeighboringPredecessor();
    if (!IsReachable(forward_predecessor)) {
      // If a loop isn't reachable through its forward edge, it can't possibly
      // become reachable via the backedge.
      TRACE(
          "[b%uu] Loop unreachable as forward predecessor b%u is unreachable\n",
          block.index().id(), forward_predecessor.index().id());
      block_is_unreachable_.Add(block.index().id());
    }
    MaybeSnapshot back_edge_snap =
        block_to_snapshot_[block.LastPredecessor()->index()];
    if (back_edge_snap.has_value() && block_was_previously_reachable) {
      // The loop was already visited at least once. In this case use the
      // available information from the backedge.
      // Note that we only do this if the loop wasn't marked as unreachable
      // before. This solves an issue where a single block loop would think the
      // backedge is reachable as we just removed the unreachable information
      // above. Once the analyzer hits the backedge, it will re-evaluate if the
      // backedge changes any analysis results and then potentially revisit
      // this loop with forward edge and backedge.
      CreateMergeSnapshot(block);
    } else {
      // The loop wasn't visited yet. There isn't any type information available
      // for the backedge.
      TRACE(
          "[b%u%s] First loop header evaluation: Ignoring all backedges on "
          "phis\n",
          block.index().id(), !IsReachable(*current_block_) ? "u" : "");
      is_first_loop_header_evaluation_ = true;
      Snapshot forward_edge_snap =
          block_to_snapshot_[forward_predecessor.index()].value();
      types_table_.StartNewSnapshot(forward_edge_snap);
    }
  } else if (block.IsBranchTarget()) {
    DCHECK_EQ(block.PredecessorCount(), 1);
    const Block& predecessor = *block.LastPredecessor();
    types_table_.StartNewSnapshot(
        block_to_snapshot_[predecessor.index()].value());
    if (IsReachable(predecessor)) {
      const BranchOp* branch =
          block.Predecessors()[0]->LastOperation(graph_).TryCast<BranchOp>();
      if (branch != nullptr) {
        ProcessBranchOnTarget(*branch, block);
      }
    } else {
      TRACE("[b%uu] Block unreachable as sole predecessor b%u is unreachable\n",
            block.index().id(), predecessor.index().id());
      block_is_unreachable_.Add(block.index().id());
    }
  } else {
    DCHECK_EQ(block.kind(), Block::Kind::kMerge);
    CreateMergeSnapshot(block);
  }
}
References v8::internal::BitVector::Add(), block_is_unreachable_, block_to_snapshot_, CreateMergeSnapshot(), current_block_, DCHECK_EQ, graph_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::has_value(), v8::internal::compiler::turboshaft::Block::HasPredecessors(), v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), is_first_loop_header_evaluation_, v8::internal::compiler::turboshaft::Block::IsBranchTarget(), v8::internal::compiler::turboshaft::Block::IsLoop(), IsReachable(), v8::internal::compiler::turboshaft::Block::kind(), v8::internal::compiler::turboshaft::Block::kMerge, v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::Block::Predecessors(), ProcessBranchOnTarget(), v8::internal::BitVector::Remove(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), v8::internal::TRACE(), and types_table_.
Referenced by ProcessBlock().
Member Data Documentation
block_is_unreachable_
BitVector v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::block_is_unreachable_ [private]
Initial value:
{static_cast<int>(graph_.block_count()),
                                  phase_zone_}
Definition at line 132 of file wasm-gc-typed-optimization-reducer.h.
Referenced by CreateMergeSnapshot(), IsReachable(), ProcessBranchOnTarget(), RefineTypeKnowledge(), RefineTypeKnowledgeNotNull(), and StartNewSnapshotFor().
block_to_snapshot_
FixedBlockSidetable<MaybeSnapshot> v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::block_to_snapshot_ [private]
Initial value:
{graph_.block_count(),
                                                        phase_zone_}
Definition at line 124 of file wasm-gc-typed-optimization-reducer.h.
Referenced by CreateMergeSnapshot(), Run(), and StartNewSnapshotFor().
current_block_
const Block* v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::current_block_ = nullptr [private]
Definition at line 135 of file wasm-gc-typed-optimization-reducer.h.
Referenced by GetTypeForPhiInput(), ProcessBlock(), ProcessBranchOnTarget(), RefineTypeKnowledge(), RefineTypeKnowledgeNotNull(), and StartNewSnapshotFor().
data_
PipelineData* v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::data_ [private]
Definition at line 115 of file wasm-gc-typed-optimization-reducer.h.
graph_
Graph& v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::graph_ [private]
Definition at line 116 of file wasm-gc-typed-optimization-reducer.h.
Referenced by GetTypeForPhiInput(), ProcessAllocateArray(), ProcessAllocateStruct(), ProcessArrayGet(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessBranchOnTarget(), ProcessGlobalGet(), ProcessIsNull(), ProcessNull(), ProcessOperations(), ProcessParameter(), ProcessPhi(), ProcessRefFunc(), ProcessStructGet(), ProcessStructSet(), ProcessTypeCast(), ProcessTypeCheck(), RefineTypeKnowledge(), RefineTypeKnowledgeNotNull(), ResolveAliases(), Run(), and StartNewSnapshotFor().
input_type_map_
ZoneUnorderedMap<OpIndex, wasm::ValueType> v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::input_type_map_ {phase_zone_} [private]
Definition at line 138 of file wasm-gc-typed-optimization-reducer.h.
Referenced by GetInputTypeOrSentinelType(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessIsNull(), ProcessStructGet(), ProcessStructSet(), ProcessTypeCast(), and ProcessTypeCheck().
is_first_loop_header_evaluation_
bool v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::is_first_loop_header_evaluation_ = false [private]
Definition at line 142 of file wasm-gc-typed-optimization-reducer.h.
Referenced by ProcessPhi(), and StartNewSnapshotFor().
module_
const wasm::WasmModule* v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::module_ = data_->wasm_module() [private]
Definition at line 118 of file wasm-gc-typed-optimization-reducer.h.
Referenced by CreateMergeSnapshot(), ProcessAllocateArray(), ProcessAllocateStruct(), ProcessBranchOnTarget(), ProcessNull(), ProcessPhi(), ProcessRefFunc(), and RefineTypeKnowledge().
phase_zone_
Zone* v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::phase_zone_ [private]
Definition at line 117 of file wasm-gc-typed-optimization-reducer.h.
Referenced by Run().
signature_
const wasm::FunctionSig* v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::signature_ = data_->wasm_module_sig() [private]
Definition at line 119 of file wasm-gc-typed-optimization-reducer.h.
Referenced by ProcessParameter(), and WasmGCTypeAnalyzer().
types_table_
TypeSnapshotTable v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::types_table_ {phase_zone_} [private]
Definition at line 121 of file wasm-gc-typed-optimization-reducer.h.
Referenced by CreateMergeSnapshot(), GetResolvedType(), GetTypeForPhiInput(), ProcessAllocateStruct(), RefineTypeKnowledge(), RefineTypeKnowledgeNotNull(), Run(), and StartNewSnapshotFor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-gc-typed-optimization-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-gc-typed-optimization-reducer.cc