v8::internal::WasmDispatchTable Class Reference
#include <wasm-objects.h>
Public Types
enum NewOrExistingEntry : bool { kNewEntry
, kExistingEntry
 }
Public Member Functions
int length () const
int length (AcquireLoadTag) const
int capacity () const
DECL_PROTECTED_POINTER_ACCESSORS (protected_offheap_data, TrustedManaged< WasmDispatchTableData >) inline WasmDispatchTableData *offheap_data() const
Tagged< Object > implicit_arg (int index) const
WasmCodePointer target (int index) const
wasm::CanonicalTypeIndex sig (int index) const
void V8_EXPORT_PRIVATE SetForNonWrapper (int index, Tagged< Union< Smi, WasmTrustedInstanceData >> implicit_arg, WasmCodePointer call_target, wasm::CanonicalTypeIndex sig_id, NewOrExistingEntry new_or_existing)
void V8_EXPORT_PRIVATE SetForWrapper (int index, Tagged< WasmImportData > implicit_arg, std::shared_ptr< wasm::WasmImportWrapperHandle > wrapper_handle, wasm::CanonicalTypeIndex sig_id, NewOrExistingEntry new_or_existing)
void Clear (int index, NewOrExistingEntry new_or_existing)
V8_EXPORT_PRIVATE std::optional< std::shared_ptr< wasm::WasmImportWrapperHandle > > MaybeGetWrapperHandle (int index) const
OBJECT_CONSTRUCTORS (WasmDispatchTable, ExposedTrustedObject)
Static Public Member Functions
static constexpr int SizeFor (int length)
static constexpr int OffsetOf (int index)
static void V8_EXPORT_PRIVATE AddUse (Isolate *isolate, DirectHandle< WasmDispatchTable > dispatch_table, DirectHandle< WasmTrustedInstanceData > instance, int table_index)
static Tagged< ProtectedWeakFixedArray > MaybeGrowUsesList (Isolate *isolate, DirectHandle< WasmDispatchTable > dispatch_table)
static V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT DirectHandle< WasmDispatchTable > New (Isolate *isolate, int length, wasm::CanonicalValueType table_type, bool shared)
static V8_WARN_UNUSED_RESULT DirectHandle< WasmDispatchTable > Grow (Isolate *, DirectHandle< WasmDispatchTable >, uint32_t new_length)
Static Public Attributes
static constexpr size_t kLengthOffset = kHeaderSize
static constexpr size_t kCapacityOffset = kLengthOffset + kUInt32Size
static constexpr size_t kProtectedOffheapDataOffset
static constexpr size_t kProtectedUsesOffset
static constexpr size_t kTableTypeOffset = kProtectedUsesOffset + kTaggedSize
static constexpr size_t kPaddingSize = TAGGED_SIZE_8_BYTES ? kUInt32Size : 0
static constexpr size_t kEntriesOffset
static constexpr size_t kTargetBias = 0
static constexpr size_t kSigBias = kTargetBias + kUInt32Size
static constexpr size_t kImplicitArgBias = kSigBias + kUInt32Size
static constexpr size_t kEntrySize = kImplicitArgBias + kTaggedSize
static constexpr int kMaxLength = (kMaxInt - kEntriesOffset) / kEntrySize
Additional Inherited Members
Detailed Description
Definition at line 806 of file wasm-objects.h.
Member Enumeration Documentation
NewOrExistingEntry
enum v8::internal::WasmDispatchTable::NewOrExistingEntry : bool
Enumerator
kNewEntry
kExistingEntry
Definition at line 815 of file wasm-objects.h.
: bool { kNewEntry, kExistingEntry };
Member Function Documentation
AddUse()
void v8::internal::WasmDispatchTable::AddUse (Isolate * isolate, DirectHandle< WasmDispatchTable > dispatch_table, DirectHandle< WasmTrustedInstanceData > instance, int table_index) [static]
Definition at line 2546 of file wasm-objects.cc.
                                                {
  Tagged<ProtectedWeakFixedArray> uses =
      MaybeGrowUsesList(isolate, dispatch_table);
  int cursor = GetUsedLength(uses);
  // {MaybeGrowUsesList} ensures that we have enough capacity.
  SetEntry(uses, cursor, *instance, table_index);
  SetUsedLength(uses, cursor + 2);
}
References v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength(), MaybeGrowUsesList(), v8::internal::anonymous_namespace{wasm-objects.cc}::SetEntry(), and v8::internal::anonymous_namespace{wasm-objects.cc}::SetUsedLength().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1_Infallible().
capacity()
int v8::internal::WasmDispatchTable::capacity () const [inline]
Definition at line 369 of file wasm-objects-inl.h.
                                      {
  return ReadField<int>(kCapacityOffset);
}
Referenced by MaybeGrowUsesList().
Clear()
void v8::internal::WasmDispatchTable::Clear (int index, NewOrExistingEntry new_or_existing)
Definition at line 2525 of file wasm-objects.cc.
                                                                           {
  SBXCHECK_BOUNDS(index, length());
  const int offset = OffsetOf(index);
  // When clearing an existing entry, we must update the refcount of any
  // wrappers. When clear-initializing new entries, we must not read
  // uninitialized memory.
  if (new_or_existing == kExistingEntry) {
    offheap_data()->Remove(index);
  }
  ClearProtectedPointerField(offset + kImplicitArgBias);
  WriteField<uint32_t>(offset + kTargetBias,
                       wasm::kInvalidWasmCodePointer.value());
  WriteField<int>(offset + kSigBias, -1);
}
References v8::internal::TrustedObject::ClearProtectedPointerField(), v8::internal::index, kExistingEntry, kImplicitArgBias, v8::internal::wasm::kInvalidWasmCodePointer, kSigBias, kTargetBias, length(), OffsetOf(), SBXCHECK_BOUNDS, and v8::internal::value.
Referenced by SetForNonWrapper().
DECL_PROTECTED_POINTER_ACCESSORS()
v8::internal::WasmDispatchTable::DECL_PROTECTED_POINTER_ACCESSORS (protected_offheap_data , TrustedManaged< WasmDispatchTableData >) const
Grow()
DirectHandle< WasmDispatchTable > v8::internal::WasmDispatchTable::Grow (Isolate * isolate, DirectHandle< WasmDispatchTable > old_table, uint32_t new_length) [static]
Definition at line 2628 of file wasm-objects.cc.
                         {
  uint32_t old_length = old_table->length();
  // This method should only be called if we actually grow. For sandbox
  // purposes we also want to ensure tables can never shrink below their
  // static minimum size.
  SBXCHECK_LT(old_length, new_length);
  uint32_t old_capacity = old_table->capacity();
  // Catch possible corruption. {new_length} is computed from untrusted data.
  SBXCHECK_LE(new_length, wasm::max_table_size());
  // {old_length} and {old_capacity} are read from trusted space, so we trust
  // them. The DCHECKs give fuzzers a chance to catch potential bugs.
  DCHECK_LE(old_length, wasm::max_table_size());
  DCHECK_LE(old_capacity, wasm::max_table_size());
  if (new_length < old_capacity) {
    RELEASE_WRITE_INT32_FIELD(*old_table, kLengthOffset, new_length);
    // All fields within the old capacity are already cleared (see below).
    return old_table;
  }
  // Grow table exponentially to guarantee amortized constant allocation and gc
  // time.
  uint32_t limit =
      std::min<uint32_t>(WasmDispatchTable::kMaxLength, wasm::max_table_size());
  uint32_t max_grow = limit - old_capacity;
  uint32_t min_grow = new_length - old_capacity;
  CHECK_LE(min_grow, max_grow);
  // Grow by old capacity, and at least by 8. Clamp to min_grow and max_grow.
  uint32_t exponential_grow = std::max(old_capacity, 8u);
  uint32_t grow = std::clamp(exponential_grow, min_grow, max_grow);
  uint32_t new_capacity = old_capacity + grow;
  DCHECK_LE(new_capacity, limit);
  DirectHandle<WasmDispatchTable> new_table =
      WasmDispatchTable::New(isolate, new_capacity, old_table->table_type(),
                             HeapLayout::InAnySharedSpace(*old_table));
  DisallowGarbageCollection no_gc;
  // Writing non-atomically is fine here because this is a freshly allocated
  // object.
  new_table->WriteField<int>(kLengthOffset, new_length);
  for (uint32_t i = 0; i < old_length; ++i) {
    WasmCodePointer call_target = old_table->target(i);
    // Update any stored call origins, so that future compiled wrappers
    // get installed into the new dispatch table.
    Tagged<Object> implicit_arg = old_table->implicit_arg(i);
    if (IsWasmImportData(implicit_arg)) {
      Tagged<WasmImportData> import_data = Cast<WasmImportData>(implicit_arg);
      // After installing a compiled wrapper, we don't set or update
      // call origins any more.
      if (import_data->has_call_origin()) {
        if (import_data->call_origin() == *old_table) {
          import_data->set_call_origin(*new_table);
        } else {
          DCHECK(v8_flags.wasm_jitless ||
                 wasm::GetWasmImportWrapperCache()->IsCompiledWrapper(
                     call_target));
        }
      }
    }
    if (implicit_arg == Smi::zero()) {
      new_table->Clear(i, kNewEntry);
      continue;
    }
    const int offset = OffsetOf(i);
    if (!v8_flags.wasm_jitless) {
      new_table->WriteField<uint32_t>(offset + kTargetBias,
                                      call_target.value());
    } else {
#if V8_ENABLE_DRUMBRAKE
      // Ignore call_target, not used in jitless mode.
      new_table->WriteField<int>(offset + kFunctionIndexBias,
                                 old_table->function_index(i));
#endif // V8_ENABLE_DRUMBRAKE
    }
    new_table->WriteProtectedPointerField(offset + kImplicitArgBias,
                                          Cast<TrustedObject>(implicit_arg));
    CONDITIONAL_WRITE_BARRIER(*new_table, offset + kImplicitArgBias,
                              implicit_arg, UPDATE_WRITE_BARRIER);
    new_table->WriteField<uint32_t>(offset + kSigBias, old_table->sig(i).index);
  }
  new_table->offheap_data()->wrappers_ =
      std::move(old_table->offheap_data()->wrappers_);
  // Update users.
  Tagged<ProtectedWeakFixedArray> uses = old_table->protected_uses();
  new_table->set_protected_uses(uses);
  int used_length = GetUsedLength(uses);
  for (int i = kReservedSlotOffset; i < used_length; i += 2) {
    if (uses->get(i).IsCleared()) continue;
    Tagged<WasmTrustedInstanceData> instance = GetInstance(uses, i);
    int table_index = GetTableIndex(uses, i);
    DCHECK_EQ(instance->dispatch_tables()->get(table_index), *old_table);
    instance->dispatch_tables()->set(table_index, *new_table);
    if (table_index == 0) {
      DCHECK_EQ(instance->dispatch_table0(), *old_table);
      instance->set_dispatch_table0(*new_table);
    }
  }
  return new_table;
}
References CHECK_LE, CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::anonymous_namespace{wasm-objects.cc}::GetInstance(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetTableIndex(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength(), v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, implicit_arg(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), kImplicitArgBias, kLengthOffset, kMaxLength, kNewEntry, v8::internal::anonymous_namespace{wasm-objects.cc}::kReservedSlotOffset, kSigBias, kTargetBias, v8::internal::wasm::max_table_size(), New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, OffsetOf(), RELEASE_WRITE_INT32_FIELD, SBXCHECK_LE, SBXCHECK_LT, v8::internal::UPDATE_WRITE_BARRIER, v8::internal::v8_flags, v8::internal::WasmCodePointer::value(), and v8::internal::Smi::zero().
Referenced by v8::internal::WasmTableObject::Grow().
implicit_arg()
Tagged< Object > v8::internal::WasmDispatchTable::implicit_arg (int index) const [inline]
Definition at line 373 of file wasm-objects-inl.h.
                                                                     {
  DCHECK_LT(index, length());
  Tagged<Object> implicit_arg =
      ReadProtectedPointerField(OffsetOf(index) + kImplicitArgBias);
  DCHECK(IsWasmTrustedInstanceData(implicit_arg) ||
         IsWasmImportData(implicit_arg) || implicit_arg == Smi::zero());
  return implicit_arg;
}
References DCHECK, DCHECK_LT, v8::internal::index, v8::internal::length, and v8::internal::zero.
Referenced by Grow(), SetForNonWrapper(), and SetForWrapper().
length() [1/2]
int v8::internal::WasmDispatchTable::length () const [inline]
Definition at line 367 of file wasm-objects-inl.h.
{ return ReadField<int>(kLengthOffset); }
Referenced by Clear(), New(), SetForNonWrapper(), and SetForWrapper().
length() [2/2]
int v8::internal::WasmDispatchTable::length (AcquireLoadTag) const [inline]
Definition at line 363 of file wasm-objects-inl.h.
                                                  {
  return ACQUIRE_READ_INT32_FIELD(*this, kLengthOffset);
}
References ACQUIRE_READ_INT32_FIELD.
MaybeGetWrapperHandle()
std::optional< std::shared_ptr< wasm::WasmImportWrapperHandle > > v8::internal::WasmDispatchTable::MaybeGetWrapperHandle (int index) const
Definition at line 2541 of file wasm-objects.cc.
                                                        {
  return offheap_data()->MaybeGetWrapperHandle(index);
}
References v8::internal::index.
MaybeGrowUsesList()
Tagged< ProtectedWeakFixedArray > v8::internal::WasmDispatchTable::MaybeGrowUsesList (Isolate * isolate, DirectHandle< WasmDispatchTable > dispatch_table) [static]
Definition at line 2559 of file wasm-objects.cc.
                                                                      {
  Tagged<ProtectedWeakFixedArray> uses = dispatch_table->protected_uses();
  int capacity = uses->length();
  if (capacity == 0) {
    constexpr int kInitialLength = 3; // 1 slot + 1 pair.
    DirectHandle<ProtectedWeakFixedArray> new_uses =
        isolate->factory()->NewProtectedWeakFixedArray(kInitialLength);
    SetUsedLength(*new_uses, kReservedSlotOffset);
    dispatch_table->set_protected_uses(*new_uses);
    return *new_uses;
  }
  DCHECK_GT(uses->length(), 0);
  int used_length = GetUsedLength(uses);
  if (used_length < capacity) return uses;
  // Try to compact, grow if that doesn't free up enough space.
  int cleared_entries = 0;
  int write_cursor = kReservedSlotOffset;
  for (int i = kReservedSlotOffset; i < capacity; i += 2) {
    DCHECK(uses->get(i).IsWeakOrCleared());
    if (uses->get(i).IsCleared()) {
      cleared_entries++;
      continue;
    }
    if (write_cursor != i) {
      CopyEntry(uses, write_cursor, uses, i);
    }
    write_cursor += 2;
  }
  // We need at least one free entry. We want at least half the array to be
  // empty; each entry needs two slots.
  int min_free_entries = 1 + (capacity >> 2);
  if (cleared_entries >= min_free_entries) {
    SetUsedLength(uses, write_cursor);
    return uses;
  }
  // Grow by 50%, at least one entry.
  DirectHandle<ProtectedWeakFixedArray> uses_handle(uses, isolate);
  uses = {};
  int old_entries = capacity >> 1; // Two slots per entry.
  int new_entries = std::max(old_entries + 1, old_entries + (old_entries >> 1));
  int new_capacity = new_entries * 2 + kReservedSlotOffset;
  DirectHandle<ProtectedWeakFixedArray> new_uses =
      isolate->factory()->NewProtectedWeakFixedArray(new_capacity);
  // The allocation could have triggered GC, freeing more entries.
  // The previous compaction's {write_cursor} is the new upper bound on
  // existing entries.
  used_length = write_cursor;
  DisallowGarbageCollection no_gc;
  uses = *uses_handle;
  write_cursor = kReservedSlotOffset;
  for (int i = kReservedSlotOffset; i < used_length; i += 2) {
    if (uses->get(i).IsCleared()) continue;
    CopyEntry(*new_uses, write_cursor, uses, i);
    write_cursor += 2;
  }
  SetUsedLength(*new_uses, write_cursor);
  dispatch_table->set_protected_uses(*new_uses);
  return *new_uses;
}
References capacity(), v8::internal::anonymous_namespace{wasm-objects.cc}::CopyEntry(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{wasm-objects.cc}::GetUsedLength(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), v8::internal::anonymous_namespace{wasm-objects.cc}::kReservedSlotOffset, v8::internal::FactoryBase< Impl >::NewProtectedWeakFixedArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{wasm-objects.cc}::SetUsedLength().
Referenced by AddUse().
New()
DirectHandle< WasmDispatchTable > v8::internal::WasmDispatchTable::New (Isolate * isolate, int length, wasm::CanonicalValueType table_type, bool shared) [static]
Definition at line 2621 of file wasm-objects.cc.
                 {
  return isolate->factory()->NewWasmDispatchTable(length, table_type, shared);
}
References v8::internal::Isolate::factory(), and length().
Referenced by Grow().
OBJECT_CONSTRUCTORS()
v8::internal::WasmDispatchTable::OBJECT_CONSTRUCTORS (WasmDispatchTable , ExposedTrustedObject)
OffsetOf()
static constexpr int v8::internal::WasmDispatchTable::OffsetOf (int index) [inline], [static], [constexpr]
Definition at line 862 of file wasm-objects.h.
                                           {
    DCHECK_LT(index, kMaxLength);
    return SizeFor(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), Clear(), Grow(), SetForNonWrapper(), and SetForWrapper().
SetForNonWrapper()
void v8::internal::WasmDispatchTable::SetForNonWrapper (int index, Tagged< Union< Smi, WasmTrustedInstanceData >> implicit_arg, WasmCodePointer call_target, wasm::CanonicalTypeIndex sig_id, NewOrExistingEntry new_or_existing)
Definition at line 2448 of file wasm-objects.cc.
                                        {
  if (implicit_arg == Smi::zero()) {
    DCHECK(v8_flags.wasm_jitless ||
           (wasm::kInvalidWasmCodePointer == call_target));
    Clear(index, new_or_existing);
    return;
  }
  SBXCHECK_BOUNDS(index, length());
  DCHECK(IsWasmTrustedInstanceData(implicit_arg));
  DCHECK(sig_id.valid());
  const int offset = OffsetOf(index);
  if (!v8_flags.wasm_jitless) {
    // When overwriting an existing entry, we must decrement the refcount
    // of any overwritten wrappers. When initializing an entry, we must not
    // read uninitialized memory.
    if (new_or_existing == kExistingEntry) {
      offheap_data()->Remove(index);
    }
    WriteField<uint32_t>(offset + kTargetBias, call_target.value());
  } else {
#if V8_ENABLE_DRUMBRAKE
    // Ignore call_target, not used in jitless mode.
    WriteField<int>(offset + kFunctionIndexBias, function_index);
#endif // V8_ENABLE_DRUMBRAKE
  }
  WriteProtectedPointerField(offset + kImplicitArgBias,
                             Cast<TrustedObject>(implicit_arg));
  CONDITIONAL_WRITE_BARRIER(*this, offset + kImplicitArgBias, implicit_arg,
                            UPDATE_WRITE_BARRIER);
  WriteField<uint32_t>(offset + kSigBias, sig_id.index);
}
References Clear(), CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), implicit_arg(), v8::internal::index, v8::internal::wasm::TypeIndex::index, kExistingEntry, kImplicitArgBias, v8::internal::wasm::kInvalidWasmCodePointer, kSigBias, kTargetBias, length(), OffsetOf(), SBXCHECK_BOUNDS, v8::internal::UPDATE_WRITE_BARRIER, v8::internal::v8_flags, v8::internal::wasm::TypeIndex::valid(), v8::internal::WasmCodePointer::value(), v8::internal::TrustedObject::WriteProtectedPointerField(), and v8::internal::Smi::zero().
SetForWrapper()
void v8::internal::WasmDispatchTable::SetForWrapper (int index, Tagged< WasmImportData > implicit_arg, std::shared_ptr< wasm::WasmImportWrapperHandle > wrapper_handle, wasm::CanonicalTypeIndex sig_id, NewOrExistingEntry new_or_existing)
Definition at line 2487 of file wasm-objects.cc.
                                        {
  DCHECK_NE(implicit_arg, Smi::zero());
  SBXCHECK(v8_flags.wasm_jitless || !wrapper_handle->has_code() ||
           !wrapper_handle->code().is_dying());
  SBXCHECK_BOUNDS(index, length());
  DCHECK(sig_id.valid());
  const int offset = OffsetOf(index);
  WriteProtectedPointerField(offset + kImplicitArgBias,
                             Cast<TrustedObject>(implicit_arg));
  CONDITIONAL_WRITE_BARRIER(*this, offset + kImplicitArgBias, implicit_arg,
                            UPDATE_WRITE_BARRIER);
  if (!v8_flags.wasm_jitless) {
    // When overwriting an existing entry, we must decrement the refcount
    // of any overwritten wrappers. When initializing an entry, we must not
    // read uninitialized memory.
    if (new_or_existing == kExistingEntry) {
      offheap_data()->Remove(index);
    }
    WriteField<uint32_t>(offset + kTargetBias,
                         wrapper_handle->code_pointer().value());
    offheap_data()->Add(index, std::move(wrapper_handle));
  } else {
#if V8_ENABLE_DRUMBRAKE
    // Ignore call_target, not used in jitless mode.
    WriteField<int>(offset + kFunctionIndexBias, function_index);
#endif // V8_ENABLE_DRUMBRAKE
  }
  WriteField<uint32_t>(offset + kSigBias, sig_id.index);
}
References CONDITIONAL_WRITE_BARRIER, v8::internal::DCHECK(), DCHECK_NE, implicit_arg(), v8::internal::index, v8::internal::wasm::TypeIndex::index, kExistingEntry, kImplicitArgBias, kSigBias, kTargetBias, length(), OffsetOf(), SBXCHECK, SBXCHECK_BOUNDS, v8::internal::UPDATE_WRITE_BARRIER, v8::internal::v8_flags, v8::internal::wasm::TypeIndex::valid(), v8::internal::TrustedObject::WriteProtectedPointerField(), and v8::internal::Smi::zero().
sig()
wasm::CanonicalTypeIndex v8::internal::WasmDispatchTable::sig (int index) const [inline]
Definition at line 389 of file wasm-objects-inl.h.
                                                                    {
  DCHECK_LT(index, length());
  return wasm::CanonicalTypeIndex{
      ReadField<uint32_t>(OffsetOf(index) + kSigBias)};
}
References DCHECK_LT, v8::internal::index, and v8::internal::length.
SizeFor()
static constexpr int v8::internal::WasmDispatchTable::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 857 of file wasm-objects.h.
                                           {
    DCHECK_LE(length, kMaxLength);
    return kEntriesOffset + length * kEntrySize;
  }
References DCHECK_LE, cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, and v8::internal::length.
Referenced by v8::internal::HeapObject::SizeFromMap().
target()
WasmCodePointer v8::internal::WasmDispatchTable::target (int index) const [inline]
Definition at line 382 of file wasm-objects-inl.h.
                                                                {
  DCHECK_LT(index, length());
  if (v8_flags.wasm_jitless) return wasm::kInvalidWasmCodePointer;
  static_assert(sizeof(WasmCodePointer) == sizeof(uint32_t));
  return WasmCodePointer{ReadField<uint32_t>(OffsetOf(index) + kTargetBias)};
}
References DCHECK_LT, v8::internal::index, v8::internal::wasm::kInvalidWasmCodePointer, v8::internal::length, and v8::internal::v8_flags.
Member Data Documentation
kCapacityOffset
constexpr size_t v8::internal::WasmDispatchTable::kCapacityOffset = kLengthOffset + kUInt32Size [static], [constexpr]
Definition at line 820 of file wasm-objects.h.
kEntriesOffset
constexpr size_t v8::internal::WasmDispatchTable::kEntriesOffset [static], [constexpr]
Initial value:
=
      kTableTypeOffset + kUInt32Size + kPaddingSize
Definition at line 827 of file wasm-objects.h.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl().
kEntrySize
constexpr size_t v8::internal::WasmDispatchTable::kEntrySize = kImplicitArgBias + kTaggedSize [static], [constexpr]
Definition at line 847 of file wasm-objects.h.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl().
kImplicitArgBias
constexpr size_t v8::internal::WasmDispatchTable::kImplicitArgBias = kSigBias + kUInt32Size [static], [constexpr]
Definition at line 846 of file wasm-objects.h.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), Clear(), Grow(), SetForNonWrapper(), and SetForWrapper().
kLengthOffset
constexpr size_t v8::internal::WasmDispatchTable::kLengthOffset = kHeaderSize [static], [constexpr]
Definition at line 819 of file wasm-objects.h.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), and Grow().
kMaxLength
constexpr int v8::internal::WasmDispatchTable::kMaxLength = (kMaxInt - kEntriesOffset) / kEntrySize [static], [constexpr]
Definition at line 855 of file wasm-objects.h.
Referenced by Grow().
kPaddingSize
constexpr size_t v8::internal::WasmDispatchTable::kPaddingSize = TAGGED_SIZE_8_BYTES ? kUInt32Size : 0 [static], [constexpr]
Definition at line 826 of file wasm-objects.h.
kProtectedOffheapDataOffset
constexpr size_t v8::internal::WasmDispatchTable::kProtectedOffheapDataOffset [static], [constexpr]
Initial value:
=
      kCapacityOffset + kUInt32Size
Definition at line 821 of file wasm-objects.h.
kProtectedUsesOffset
constexpr size_t v8::internal::WasmDispatchTable::kProtectedUsesOffset [static], [constexpr]
Initial value:
=
      kProtectedOffheapDataOffset + kTaggedSize
Definition at line 823 of file wasm-objects.h.
kSigBias
constexpr size_t v8::internal::WasmDispatchTable::kSigBias = kTargetBias + kUInt32Size [static], [constexpr]
Definition at line 845 of file wasm-objects.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), Clear(), Grow(), SetForNonWrapper(), and SetForWrapper().
kTableTypeOffset
constexpr size_t v8::internal::WasmDispatchTable::kTableTypeOffset = kProtectedUsesOffset + kTaggedSize [static], [constexpr]
Definition at line 825 of file wasm-objects.h.
kTargetBias
constexpr size_t v8::internal::WasmDispatchTable::kTargetBias = 0 [static], [constexpr]
Definition at line 838 of file wasm-objects.h.
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallDirect(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), Clear(), Grow(), SetForNonWrapper(), and SetForWrapper().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc