v8::internal::wasm::gdb_server::TransportBase Class Reference
#include <transport.h>
Public Member Functions
virtual ~TransportBase ()
virtual bool AcceptConnection ()=0
virtual bool Read (char *dst, int32_t len)=0
virtual bool Write (const char *src, int32_t len)=0
virtual bool IsDataAvailable () const =0
virtual void Disconnect ()=0
virtual void Close ()=0
virtual void WaitForDebugStubEvent ()=0
virtual bool SignalThreadEvent ()=0
Detailed Description
Definition at line 72 of file transport.h.
Constructor & Destructor Documentation
 TransportBase()
virtual v8::internal::wasm::gdb_server::TransportBase::~TransportBase () [inline], [virtual]
Definition at line 74 of file transport.h.
{}
Member Function Documentation
AcceptConnection()
virtual bool v8::internal::wasm::gdb_server::TransportBase::AcceptConnection () [pure virtual]
Implemented in v8::internal::wasm::gdb_server::SocketTransport.
Close()
virtual void v8::internal::wasm::gdb_server::TransportBase::Close () [pure virtual]
Implemented in v8::internal::wasm::gdb_server::Transport.
Disconnect()
virtual void v8::internal::wasm::gdb_server::TransportBase::Disconnect () [pure virtual]
Implemented in v8::internal::wasm::gdb_server::Transport.
Referenced by v8::internal::wasm::gdb_server::Session::Disconnect().
IsDataAvailable()
virtual bool v8::internal::wasm::gdb_server::TransportBase::IsDataAvailable () const [pure virtual]
Implemented in v8::internal::wasm::gdb_server::Transport.
Referenced by v8::internal::wasm::gdb_server::Session::IsDataAvailable().
Read()
virtual bool v8::internal::wasm::gdb_server::TransportBase::Read (char * dst, int32_t len) [pure virtual]
Implemented in v8::internal::wasm::gdb_server::Transport.
Referenced by v8::internal::wasm::gdb_server::Session::GetChar().
SignalThreadEvent()
virtual bool v8::internal::wasm::gdb_server::TransportBase::SignalThreadEvent () [pure virtual]
Implemented in v8::internal::wasm::gdb_server::SocketTransport.
Referenced by v8::internal::wasm::gdb_server::Session::SignalThreadEvent().
WaitForDebugStubEvent()
virtual void v8::internal::wasm::gdb_server::TransportBase::WaitForDebugStubEvent () [pure virtual]
Implemented in v8::internal::wasm::gdb_server::SocketTransport.
Referenced by v8::internal::wasm::gdb_server::Session::WaitForDebugStubEvent().
Write()
virtual bool v8::internal::wasm::gdb_server::TransportBase::Write (const char * src, int32_t len) [pure virtual]
Implemented in v8::internal::wasm::gdb_server::Transport.
Referenced by v8::internal::wasm::gdb_server::Session::GetPacket(), and v8::internal::wasm::gdb_server::Session::SendPacket().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/transport.h