v8::internal::wasm::WasmBytecodeGenerator Class Reference
#include <wasm-interpreter.h>
Classes
struct BlockData
class RollbackStack
struct Simd128Hash
Public Types
typedef void(WasmBytecodeGenerator::* MemIndexPushFunc) (bool emit)
typedef void(WasmBytecodeGenerator::* MemIndexPopFunc) (bool emit)
Public Member Functions
WasmBytecodeGenerator (uint32_t function_index, InterpreterCode *wasm_code, const WasmModule *module)
std::unique_ptr< WasmBytecode > GenerateBytecode ()
Static Public Member Functions
static void PrintBytecodeCompressionStats ()
Private Member Functions
uint32_t const_slots_start () const
uint32_t GetStackFrameSize () const
uint32_t CurrentCodePos () const
WasmInstruction DecodeInstruction (pc_t pc, Decoder &decoder)
void DecodeGCOp (WasmOpcode opcode, WasmInstruction::Optional *optional, Decoder *decoder, InterpreterCode *code, pc_t pc, int *const len)
void DecodeNumericOp (WasmOpcode opcode, WasmInstruction::Optional *optional, Decoder *decoder, InterpreterCode *code, pc_t pc, int *const len)
void DecodeAtomicOp (WasmOpcode opcode, WasmInstruction::Optional *optional, Decoder *decoder, InterpreterCode *code, pc_t pc, int *const len)
bool DecodeSimdOp (WasmOpcode opcode, WasmInstruction::Optional *optional, Decoder *decoder, InterpreterCode *code, pc_t pc, int *const len)
bool ToRegisterIsAllowed (const WasmInstruction &instr)
RegMode EncodeInstruction (const WasmInstruction &instr, RegMode curr_reg_mode, RegMode next_reg_mode)
RegMode DoEncodeInstruction (const WasmInstruction &instr, RegMode curr_reg_mode, RegMode next_reg_mode)
bool EncodeSuperInstruction (RegMode &reg_mode, const WasmInstruction &curr_instr, const WasmInstruction &next_instr)
bool DoEncodeSuperInstruction (RegMode &reg_mode, const WasmInstruction &curr_instr, const WasmInstruction &next_instr)
uint32_t ScanConstInstructions () const
void Emit (const void *buff, size_t len)
void I32Push (bool emit=true)
void I64Push (bool emit=true)
void MemIndexPush (bool emit=true)
void ITableIndexPush (bool is_table64, bool emit=true)
void F32Push (bool emit=true)
void F64Push (bool emit=true)
void S128Push (bool emit=true)
void RefPush (ValueType type, bool emit=true)
void Push (ValueType type)
void I32Pop (bool emit=true)
void I64Pop (bool emit=true)
void MemIndexPop (bool emit=true)
void F32Pop (bool emit=true)
void F64Pop (bool emit=true)
void S128Pop (bool emit=true)
ValueType RefPop (bool emit=true)
void Pop (ValueKind kind, bool emit=true)
void EmitI16Const (int16_t value)
void EmitI32Const (int32_t value)
void EmitF32Const (float value)
void EmitF64Const (double value)
void EmitSlotOffset (uint32_t value)
void EmitMemoryOffset (uint64_t value)
void EmitStackIndex (int32_t value)
void EmitRefStackIndex (int32_t value)
void EmitRefValueType (int32_t value)
void EmitStructFieldOffset (int32_t value)
void EmitFnId (InstructionHandler func_id, uint32_t pc=UINT_MAX)
void EmitCopySlot (ValueType value_type, uint32_t from_slot_index, uint32_t to_slot_index, bool copy_from_reg=false)
bool IsMemory64 () const
bool IsMultiMemory () const
ValueKind GetGlobalType (uint32_t index) const
void EmitGlobalIndex (uint32_t index)
uint32_t ReserveBlockSlots (uint8_t opcode, const WasmInstruction::Optional::Block &block_data, size_t *rets_slots_count, size_t *params_slots_count)
void StoreBlockParamsIntoSlots (uint32_t target_block_index, bool update_stack)
void StoreBlockParamsAndResultsIntoSlots (uint32_t target_block_index, WasmOpcode opcode)
bool HasVoidSignature (const WasmBytecodeGenerator::BlockData &block_data) const
uint32_t ParamsCount (const WasmBytecodeGenerator::BlockData &block_data) const
ValueType GetParamType (const WasmBytecodeGenerator::BlockData &block_data, size_t index) const
uint32_t ReturnsCount (const WasmBytecodeGenerator::BlockData &block_data) const
ValueType GetReturnType (const WasmBytecodeGenerator::BlockData &block_data, size_t index) const
void PreserveArgsAndLocals ()
int32_t BeginBlock (WasmOpcode opcode, const WasmInstruction::Optional::Block signature)
void BeginElseBlock (uint32_t if_block_index, bool dummy)
int32_t EndBlock (WasmOpcode opcode)
void Return ()
void EmitBranchOffset (uint32_t delta)
void EmitIfElseBranchOffset ()
void EmitTryCatchBranchOffset ()
void EmitBranchTableOffset (uint32_t delta, uint32_t code_pos)
uint32_t GetCurrentBranchDepth () const
int32_t GetTargetBranch (uint32_t delta) const
int GetCurrentTryBlockIndex (bool return_matching_try_for_catch_blocks) const
void PatchBranchOffsets ()
void PatchLoopBeginInstructions ()
void RestoreIfElseParams (uint32_t if_block_index)
bool HasSharedSlot (uint32_t stack_index) const
bool FindSharedSlot (uint32_t stack_index, uint32_t *new_slot_index)
const FunctionSig * GetFunctionSignature (uint32_t function_index) const
ValueKind GetTopStackType (RegMode reg_mode) const
uint32_t function_index () const
uint32_t CreateSlot (ValueType value_type)
template<typename T >
uint32_t CreateSlot (ValueType value_type)
uint32_t CreateWasmRefSlot (ValueType value_type)
template<typename T >
uint32_t GetConstSlot (T value)
uint32_t GetI32ConstSlot (int32_t value)
uint32_t GetI64ConstSlot (int64_t value)
uint32_t GetF32ConstSlot (float value)
uint32_t GetF64ConstSlot (double value)
uint32_t GetS128ConstSlot (Simd128 value)
template<typename T >
uint32_t CreateConstSlot (T value)
template<typename T >
uint32_t PushConstSlot (T value)
void PushConstSlot (uint32_t slot_index)
void PushSlot (uint32_t slot_index)
uint32_t _PushSlot (ValueType value_type)
void PushCopySlot (uint32_t from_stack_index)
uint32_t PopSlot ()
void CopyToSlot (ValueType value_type, uint32_t from_slot_index, uint32_t to_stack_index, bool copy_from_reg)
void CopyToSlotAndPop (ValueType value_type, uint32_t to, bool is_tee, bool copy_from_reg)
void SetSlotType (uint32_t stack_index, ValueType type)
void UpdateStack (uint32_t index, uint32_t slot_index)
void UpdateStack (uint32_t index, uint32_t slot_index, ValueType value_type)
uint32_t stack_top_index () const
uint32_t stack_size () const
void SetUnreachableMode ()
void InitSlotsForFunctionArgs (const FunctionSig *sig, bool is_indirect_call)
bool TryCompactInstructionHandler (InstructionHandler func_addr)
bool TypeCheckAlwaysSucceeds (ValueType obj_type, HeapType type) const
bool TypeCheckAlwaysFails (ValueType obj_type, HeapType expected_type, bool null_succeeds) const
WasmBytecodeGenerator (const WasmBytecodeGenerator &)=delete
WasmBytecodeGenerator & operator= (const WasmBytecodeGenerator &)=delete
Private Attributes
std::vector< Slot > slots_
MemIndexPushFunc int_mem_push_
MemIndexPopFunc int_mem_pop_
bool is_memory64_
std::vector< uint8_t > const_slots_values_
uint32_t const_slot_offset_
std::unordered_map< int32_t, uint32_t > i32_const_cache_
std::unordered_map< int64_t, uint32_t > i64_const_cache_
std::unordered_map< float, uint32_t > f32_const_cache_
std::unordered_map< double, uint32_t > f64_const_cache_
std::unordered_map< Simd128, uint32_t, Simd128Hash > s128_const_cache_
std::vector< Simd128 > simd_immediates_
uint32_t slot_offset_
RollbackStack stack_
uint32_t ref_slots_count_
uint32_t function_index_
InterpreterCode * wasm_code_
uint32_t args_count_
uint32_t args_slots_size_
uint32_t return_count_
uint32_t rets_slots_size_
uint32_t locals_count_
std::vector< uint8_t > code_
std::vector< BlockData > blocks_
int32_t current_block_index_
bool is_instruction_reachable_
uint32_t unreachable_block_count_
base::SmallVector< uint32_t, 8 > br_table_labels_
base::SmallVector< uint32_t, 16 > loop_begin_code_offsets_
const WasmModule * module_
std::map< CodeOffset, pc_t > code_pc_map_
CodeOffset last_instr_offset_
WasmEHDataGenerator eh_data_
InstrHandlerSize handler_size_
bool current_instr_encoding_failed_
bool no_nested_emit_instr_handler_guard_
Static Private Attributes
static const CodeOffset kInvalidCodeOffset = (CodeOffset)-1
static std::atomic< size_t > total_bytecode_size_ = 0
static std::atomic< size_t > emitted_short_slot_offset_count_ = 0
static std::atomic< size_t > emitted_short_memory_offset_count_
Detailed Description
Definition at line 1454 of file wasm-interpreter.h.
Member Typedef Documentation
MemIndexPopFunc
typedef void(WasmBytecodeGenerator::* v8::internal::wasm::WasmBytecodeGenerator::MemIndexPopFunc) (bool emit)
Definition at line 1457 of file wasm-interpreter.h.
MemIndexPushFunc
typedef void(WasmBytecodeGenerator::* v8::internal::wasm::WasmBytecodeGenerator::MemIndexPushFunc) (bool emit)
Definition at line 1456 of file wasm-interpreter.h.
Constructor & Destructor Documentation
WasmBytecodeGenerator() [1/2]
v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator (uint32_t function_index, InterpreterCode * wasm_code, const WasmModule * module)
Definition at line 7377 of file wasm-interpreter.cc.
    : const_slot_offset_(0),
      slot_offset_(0),
      ref_slots_count_(0),
      function_index_(function_index),
      wasm_code_(wasm_code),
      args_count_(0),
      args_slots_size_(0),
      return_count_(0),
      rets_slots_size_(0),
      locals_count_(0),
      current_block_index_(-1),
      is_instruction_reachable_(true),
      unreachable_block_count_(0),
#ifdef DEBUG
      was_current_instruction_reachable_(true),
#endif // DEBUG
      module_(module),
      last_instr_offset_(kInvalidCodeOffset),
      handler_size_(InstrHandlerSize::Large),
      current_instr_encoding_failed_(false)
#ifdef DEBUG
      ,
      no_nested_emit_instr_handler_guard_(false)
#endif // DEBUG
{
  DCHECK(v8_flags.wasm_jitless);
  // Multiple memories not supported.
  DCHECK_LE(module->memories.size(), 1);
  size_t wasm_code_size = wasm_code_->end - wasm_code_->start;
  code_.reserve(wasm_code_size * 6);
  slots_.reserve(wasm_code_size / 2);
  stack_.reserve(wasm_code_size / 4);
  blocks_.reserve(wasm_code_size / 8);
  const FunctionSig* sig = module_->functions[function_index].sig;
  args_count_ = static_cast<uint32_t>(sig->parameter_count());
  args_slots_size_ = WasmBytecode::ArgsSizeInSlots(sig);
  return_count_ = static_cast<uint32_t>(sig->return_count());
  rets_slots_size_ = WasmBytecode::RetsSizeInSlots(sig);
  locals_count_ = static_cast<uint32_t>(wasm_code->locals.num_locals);
  is_memory64_ = IsMemory64();
  if (is_memory64_) {
    int_mem_push_ = &WasmBytecodeGenerator::I64Push;
    int_mem_pop_ = &WasmBytecodeGenerator::I64Pop;
  } else {
    int_mem_push_ = &WasmBytecodeGenerator::I32Push;
    int_mem_pop_ = &WasmBytecodeGenerator::I32Pop;
  }
}
References args_count_, args_slots_size_, v8::internal::wasm::WasmBytecode::ArgsSizeInSlots(), blocks_, code_, v8::internal::DCHECK(), DCHECK_LE, v8::internal::wasm::InterpreterCode::end, function_index(), v8::internal::wasm::WasmModule::functions, I32Pop(), I32Push(), I64Pop(), I64Push(), int_mem_pop_, int_mem_push_, is_memory64_, IsMemory64(), v8::internal::wasm::InterpreterCode::locals, locals_count_, v8::internal::wasm::WasmModule::memories, module_, v8::internal::wasm::BodyLocalDecls::num_locals, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::reserve(), rets_slots_size_, v8::internal::wasm::WasmBytecode::RetsSizeInSlots(), return_count_, v8::internal::sig, slots_, stack_, v8::internal::wasm::InterpreterCode::start, v8::internal::v8_flags, and wasm_code_.
WasmBytecodeGenerator() [2/2]
v8::internal::wasm::WasmBytecodeGenerator::WasmBytecodeGenerator (const WasmBytecodeGenerator &) [private], [delete]
Member Function Documentation
_PushSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::_PushSlot (ValueType value_type) [inline], [private]
Definition at line 1896 of file wasm-interpreter.h.
                                                  {
    PushSlot(static_cast<uint32_t>(slots_.size()));
    return CreateSlot(value_type);
  }
References CreateSlot(), PushSlot(), slots_, and v8::internal::wasm::value_type().
Referenced by GenerateBytecode().
BeginBlock()
int32_t v8::internal::wasm::WasmBytecodeGenerator::BeginBlock (WasmOpcode opcode, const WasmInstruction::Optional::Block signature) [private]
Definition at line 13055 of file wasm-interpreter.cc.
                                                                     {
  int32_t block_index = static_cast<int32_t>(blocks_.size());
  uint32_t stack_size = this->stack_size();
  uint32_t first_block_index = 0;
  size_t rets_slots_count = 0;
  size_t params_slots_count = 0;
  if (block_index > 0 && (opcode != kExprElse && opcode != kExprCatch &&
                          opcode != kExprCatchAll)) {
    first_block_index = ReserveBlockSlots(opcode, signature, &rets_slots_count,
                                          &params_slots_count);
  }
  uint32_t parent_block_index = current_block_index_;
  if (opcode == kExprCatch || opcode == kExprCatchAll) {
    parent_block_index =
        blocks_[eh_data_.GetCurrentTryBlockIndex()].parent_block_index_;
  }
  blocks_.emplace_back(opcode, CurrentCodePos(), parent_block_index, stack_size,
                       signature, first_block_index, rets_slots_count,
                       params_slots_count, eh_data_.GetCurrentTryBlockIndex());
  current_block_index_ = block_index;
  if (opcode == kExprIf && params_slots_count > 0) {
    DCHECK_GE(stack_size, params_slots_count);
    blocks_.back().SaveParams(&stack_[stack_size - params_slots_count],
                              params_slots_count);
  }
  if (opcode == kExprLoop) {
    StoreBlockParamsIntoSlots(current_block_index_, true);
    loop_begin_code_offsets_.push_back(CurrentCodePos());
    blocks_[current_block_index_].begin_code_offset_ = CurrentCodePos();
    last_instr_offset_ = kInvalidCodeOffset;
    START_EMIT_INSTR_HANDLER_WITH_ID(s2s_OnLoopBegin) {}
    END_EMIT_INSTR_HANDLER()
  }
  return current_block_index_;
}
References blocks_, current_block_index_, CurrentCodePos(), DCHECK_GE, eh_data_, END_EMIT_INSTR_HANDLER, v8::internal::wasm::WasmEHDataGenerator::GetCurrentTryBlockIndex(), kInvalidCodeOffset, last_instr_offset_, loop_begin_code_offsets_, v8::base::SmallVector< T, kSize, Allocator >::push_back(), ReserveBlockSlots(), stack_, stack_size(), START_EMIT_INSTR_HANDLER_WITH_ID, and StoreBlockParamsIntoSlots().
Referenced by DoEncodeInstruction(), and GenerateBytecode().
BeginElseBlock()
void v8::internal::wasm::WasmBytecodeGenerator::BeginElseBlock (uint32_t if_block_index, bool dummy) [inline], [private]
Definition at line 573 of file wasm-interpreter-inl.h.
                                                              {
  EndBlock(kExprElse); // End matching if block.
  RestoreIfElseParams(if_block_index);
  int32_t else_block_index =
      BeginBlock(kExprElse, blocks_[if_block_index].signature_);
  blocks_[if_block_index].if_else_block_index_ = else_block_index;
  blocks_[else_block_index].if_else_block_index_ = if_block_index;
  blocks_[else_block_index].first_block_index_ =
      blocks_[if_block_index].first_block_index_;
}
Referenced by DoEncodeInstruction().
const_slots_start()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::const_slots_start () const [inline], [private]
Definition at line 1525 of file wasm-interpreter.h.
                                     {
    return rets_slots_size_ + args_slots_size_;
  }
References args_slots_size_, and rets_slots_size_.
Referenced by CreateConstSlot().
CopyToSlot()
void v8::internal::wasm::WasmBytecodeGenerator::CopyToSlot (ValueType value_type, uint32_t from_slot_index, uint32_t to_stack_index, bool copy_from_reg) [private]
Definition at line 7607 of file wasm-interpreter.cc.
                                                           {
  const ValueKind kind = value_type.kind();
  uint32_t to_slot_index = stack_[to_stack_index];
  DCHECK(copy_from_reg || CheckEqualKind(kind, slots_[from_slot_index].kind()));
  DCHECK(CheckEqualKind(slots_[to_slot_index].kind(), kind));
  uint32_t new_slot_index;
  // If the slot is shared {FindSharedSlot} creates a new slot and makes all the
  // 'non-locals' stack entries that shared the old slot point to this new slot.
  // We need to emit a {PreserveCopySlot} instruction to dynamically copy the
  // old value into the new slot.
  if (FindSharedSlot(to_stack_index, &new_slot_index)) {
    START_EMIT_INSTR_HANDLER() {
      switch (kind) {
        case kI32:
          if (copy_from_reg) {
            EMIT_INSTR_HANDLER(r2s_PreserveCopyR0ToSlot32);
          } else {
            EMIT_INSTR_HANDLER(s2s_PreserveCopySlot32);
          }
          break;
        case kI64:
          if (copy_from_reg) {
            EMIT_INSTR_HANDLER(r2s_PreserveCopyR0ToSlot64);
          } else {
            EMIT_INSTR_HANDLER(s2s_PreserveCopySlot64);
          }
          break;
        case kF32:
          if (copy_from_reg) {
            EMIT_INSTR_HANDLER(r2s_PreserveCopyFp0ToSlot32);
          } else {
            EMIT_INSTR_HANDLER(s2s_PreserveCopySlot32);
          }
          break;
        case kF64:
          if (copy_from_reg) {
            EMIT_INSTR_HANDLER(r2s_PreserveCopyFp0ToSlot64);
          } else {
            EMIT_INSTR_HANDLER(s2s_PreserveCopySlot64);
          }
          break;
        case kS128:
          DCHECK(!copy_from_reg);
          EMIT_INSTR_HANDLER(s2s_PreserveCopySlot128);
          break;
        case kRef:
        case kRefNull:
        default:
          UNREACHABLE();
      }
      if (kind == kRefNull || kind == kRef) {
        DCHECK(!copy_from_reg);
        EmitRefStackIndex(slots_[from_slot_index].ref_stack_index);
        EmitRefStackIndex(slots_[to_slot_index].ref_stack_index);
        EmitRefStackIndex(slots_[new_slot_index].ref_stack_index);
      } else {
        if (!copy_from_reg) {
          EmitSlotOffset(slots_[from_slot_index].slot_offset);
        }
        EmitSlotOffset(slots_[to_slot_index].slot_offset);
        EmitSlotOffset(slots_[new_slot_index].slot_offset);
      }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      if (v8_flags.trace_drumbrake_execution &&
          v8_flags.trace_drumbrake_execution_verbose) {
        printf("emit s2s_PreserveCopySlot: %d %d %d\n",
               slots_[from_slot_index].slot_offset,
               slots_[to_slot_index].slot_offset,
               slots_[new_slot_index].slot_offset);
      }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    }
    END_EMIT_INSTR_HANDLER()
  } else {
    EmitCopySlot(value_type, from_slot_index, to_slot_index, copy_from_reg);
  }
}
References v8::internal::DCHECK(), EMIT_INSTR_HANDLER, EmitCopySlot(), EmitRefStackIndex(), EmitSlotOffset(), END_EMIT_INSTR_HANDLER, FindSharedSlot(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, slots_, stack_, START_EMIT_INSTR_HANDLER, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::wasm::value_type().
Referenced by CopyToSlotAndPop(), and DoEncodeSuperInstruction().
CopyToSlotAndPop()
void v8::internal::wasm::WasmBytecodeGenerator::CopyToSlotAndPop (ValueType value_type, uint32_t to, bool is_tee, bool copy_from_reg) [private]
Definition at line 7692 of file wasm-interpreter.cc.
                                                                              {
  DCHECK(!stack_.empty());
  DCHECK_LT(to_stack_index, stack_.size() - (copy_from_reg ? 0 : 1));
  // LocalGet uses a "copy-on-write" mechanism: the arg/local value is not
  // copied and instead the stack entry references the same slot. When the
  // arg/local value is modified, we need to preserve the old value of the stack
  // entry in a new slot.
  CopyToSlot(value_type, stack_.back(), to_stack_index, copy_from_reg);
  if (!is_tee && !copy_from_reg) {
    PopSlot();
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      START_EMIT_INSTR_HANDLER_WITH_ID(trace_PopSlot) {}
      END_EMIT_INSTR_HANDLER()
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  }
}
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back(), CopyToSlot(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::empty(), END_EMIT_INSTR_HANDLER, PopSlot(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), stack_, START_EMIT_INSTR_HANDLER_WITH_ID, v8::internal::v8_flags, and v8::internal::wasm::value_type().
Referenced by DoEncodeInstruction().
CreateConstSlot()
template<typename T >
uint32_t v8::internal::wasm::WasmBytecodeGenerator::CreateConstSlot (T value) [inline], [private]
Definition at line 1854 of file wasm-interpreter.h.
                                           {
    if constexpr (std::is_same_v<T, WasmRef>) {
      UNREACHABLE();
    }
    uint32_t slot_index = GetConstSlot(value);
    if (slot_index == UINT_MAX) {
      uint32_t offset = const_slot_offset_ * sizeof(uint32_t);
      DCHECK_LE(offset + sizeof(T), const_slots_values_.size());
      slot_index = static_cast<uint32_t>(slots_.size());
      slots_.push_back(
          {value_type<T>(), const_slots_start() + const_slot_offset_, 0});
      base::WriteUnalignedValue<T>(
          reinterpret_cast<Address>(const_slots_values_.data() + offset),
          value);
      const_slot_offset_ += sizeof(T) / kSlotSize;
    }
    return slot_index;
  }
References const_slot_offset_, const_slots_start(), const_slots_values_, DCHECK_LE, GetConstSlot(), v8::internal::wasm::kSlotSize, slots_, T, v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by DoEncodeInstruction(), and PushConstSlot().
CreateSlot() [1/2]
uint32_t v8::internal::wasm::WasmBytecodeGenerator::CreateSlot (ValueType value_type) [inline], [private]
Definition at line 1757 of file wasm-interpreter.h.
                                                   {
    switch (value_type.kind()) {
      case kI32:
        return CreateSlot<int32_t>(value_type);
      case kI64:
        return CreateSlot<int64_t>(value_type);
      case kF32:
        return CreateSlot<float>(value_type);
      case kF64:
        return CreateSlot<double>(value_type);
      case kS128:
        return CreateSlot<Simd128>(value_type);
      case kRef:
      case kRefNull:
        return CreateSlot<WasmRef>(value_type);
      default:
        UNREACHABLE();
    }
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::UNREACHABLE(), and v8::internal::wasm::value_type().
Referenced by _PushSlot(), DoEncodeInstruction(), FindSharedSlot(), GenerateBytecode(), InitSlotsForFunctionArgs(), and ReserveBlockSlots().
CreateSlot() [2/2]
template<typename T >
uint32_t v8::internal::wasm::WasmBytecodeGenerator::CreateSlot (ValueType value_type) [inline], [private]
Definition at line 1778 of file wasm-interpreter.h.
                                                   {
    // A gcc bug causes "error: explicit specialization in non-namespace scope"
    // with explicit specializations here:
    // https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85282
    if constexpr (std::is_same_v<T, WasmRef>) {
      return CreateWasmRefSlot(value_type);
    }
    uint32_t slot_index = static_cast<uint32_t>(slots_.size());
    slots_.push_back({value_type, slot_offset_, 0});
    slot_offset_ += sizeof(T) / kSlotSize;
    return slot_index;
  }
References CreateWasmRefSlot(), v8::internal::wasm::kSlotSize, slot_offset_, slots_, T, and v8::internal::wasm::value_type().
CreateWasmRefSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::CreateWasmRefSlot (ValueType value_type) [inline], [private]
Definition at line 1790 of file wasm-interpreter.h.
                                                          {
    uint32_t slot_index = static_cast<uint32_t>(slots_.size());
    slots_.push_back({value_type, slot_offset_, ref_slots_count_});
    slot_offset_ += sizeof(WasmRef) / kSlotSize;
    ref_slots_count_++;
    return slot_index;
  }
References v8::internal::wasm::kSlotSize, ref_slots_count_, slot_offset_, slots_, and v8::internal::wasm::value_type().
Referenced by CreateSlot().
CurrentCodePos()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::CurrentCodePos () const [inline], [private]
Definition at line 1531 of file wasm-interpreter.h.
                                  {
    return static_cast<uint32_t>(code_.size());
  }
References code_.
Referenced by BeginBlock(), DoEncodeInstruction(), EmitFnId(), and EndBlock().
DecodeAtomicOp()
void v8::internal::wasm::WasmBytecodeGenerator::DecodeAtomicOp (WasmOpcode opcode, WasmInstruction::Optional * optional, Decoder * decoder, InterpreterCode * code, pc_t pc, int *const len) [private]
Definition at line 8561 of file wasm-interpreter.cc.
                                                           {
  switch (opcode) {
    case kExprAtomicNotify:
    case kExprI32AtomicWait: {
      MachineType memtype = MachineType::Uint32();
      MemoryAccessImmediate imm(decoder, code->at(pc + *len),
                                ElementSizeLog2Of(memtype.representation()),
                                Decoder::kNoValidation);
      optional->offset = imm.offset;
      *len += imm.length;
      break;
    }
    case kExprI64AtomicWait: {
      MachineType memtype = MachineType::Uint64();
      MemoryAccessImmediate imm(decoder, code->at(pc + *len),
                                ElementSizeLog2Of(memtype.representation()),
                                Decoder::kNoValidation);
      optional->offset = imm.offset;
      *len += imm.length;
      break;
    }
    case kExprAtomicFence:
      *len += 1;
      break;
#define ATOMIC_BINOP(name, Type, ctype, type, op_ctype, op_type, operation) \
  case kExpr##name: { \
    MachineType memtype = MachineType::Type(); \
    MemoryAccessImmediate imm(decoder, code->at(pc + *len), \
                              ElementSizeLog2Of(memtype.representation()), \
                              Decoder::kNoValidation); \
    optional->offset = imm.offset; \
    *len += imm.length; \
    break; \
  }
      FOREACH_ATOMIC_BINOP(ATOMIC_BINOP)
#undef ATOMIC_BINOP
#define ATOMIC_OP(name, Type, ctype, type, op_ctype, op_type) \
  case kExpr##name: { \
    MachineType memtype = MachineType::Type(); \
    MemoryAccessImmediate imm(decoder, code->at(pc + *len), \
                              ElementSizeLog2Of(memtype.representation()), \
                              Decoder::kNoValidation); \
    optional->offset = imm.offset; \
    *len += imm.length; \
    break; \
  }
      FOREACH_ATOMIC_COMPARE_EXCHANGE_OP(ATOMIC_OP)
      FOREACH_ATOMIC_LOAD_OP(ATOMIC_OP)
      FOREACH_ATOMIC_STORE_OP(ATOMIC_OP)
#undef ATOMIC_OP
    default:
      FATAL("Unknown or unimplemented opcode #%d:%s", code->start[pc],
            WasmOpcodes::OpcodeName(static_cast<WasmOpcode>(code->start[pc])));
      UNREACHABLE();
  }
}
References ATOMIC_BINOP, ATOMIC_OP, code, v8::internal::ElementSizeLog2Of(), FATAL, FOREACH_ATOMIC_BINOP, FOREACH_ATOMIC_COMPARE_EXCHANGE_OP, FOREACH_ATOMIC_LOAD_OP, FOREACH_ATOMIC_STORE_OP, v8::internal::wasm::Decoder::kNoValidation, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::MemoryAccessImmediate::offset, v8::internal::wasm::WasmInstruction::Optional::offset, v8::internal::wasm::WasmOpcodes::OpcodeName(), v8::internal::MachineType::representation(), v8::internal::MachineType::Uint32(), v8::internal::MachineType::Uint64(), and v8::internal::UNREACHABLE().
Referenced by DecodeInstruction().
DecodeGCOp()
void v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp (WasmOpcode opcode, WasmInstruction::Optional * optional, Decoder * decoder, InterpreterCode * code, pc_t pc, int *const len) [private]
Definition at line 8336 of file wasm-interpreter.cc.
                                                                {
  WasmDetectedFeatures detected;
  switch (opcode) {
    case kExprStructNew:
    case kExprStructNewDefault: {
      StructIndexImmediate imm(decoder, code->at(pc + *len),
                               Decoder::kNoValidation);
      optional->index = imm.index.index;
      *len += imm.length;
      break;
    }
    case kExprStructGet:
    case kExprStructGetS:
    case kExprStructGetU:
    case kExprStructSet: {
      FieldImmediate imm(decoder, code->at(pc + *len), Decoder::kNoValidation);
      optional->gc_field_immediate = {imm.struct_imm.index.index,
                                      imm.field_imm.index};
      *len += imm.length;
      break;
    }
    case kExprArrayNew:
    case kExprArrayNewDefault:
    case kExprArrayGet:
    case kExprArrayGetS:
    case kExprArrayGetU:
    case kExprArraySet:
    case kExprArrayFill: {
      ArrayIndexImmediate imm(decoder, code->at(pc + *len),
                              Decoder::kNoValidation);
      optional->index = imm.index.index;
      *len += imm.length;
      break;
    }
    case kExprArrayNewFixed: {
      ArrayIndexImmediate array_imm(decoder, code->at(pc + *len),
                                    Decoder::kNoValidation);
      optional->gc_array_new_fixed.array_index = array_imm.index.index;
      *len += array_imm.length;
      IndexImmediate data_imm(decoder, code->at(pc + *len), "array length",
                              Decoder::kNoValidation);
      optional->gc_array_new_fixed.length = data_imm.index;
      *len += data_imm.length;
      break;
    }
    case kExprArrayNewData:
    case kExprArrayNewElem:
    case kExprArrayInitData:
    case kExprArrayInitElem: {
      ArrayIndexImmediate array_imm(decoder, code->at(pc + *len),
                                    Decoder::kNoValidation);
      optional->gc_array_new_or_init_data.array_index = array_imm.index.index;
      *len += array_imm.length;
      IndexImmediate data_imm(decoder, code->at(pc + *len), "segment index",
                              Decoder::kNoValidation);
      optional->gc_array_new_or_init_data.data_index = data_imm.index;
      *len += data_imm.length;
      break;
    }
    case kExprArrayCopy: {
      ArrayIndexImmediate dest_array_imm(decoder, code->at(pc + *len),
                                         Decoder::kNoValidation);
      optional->gc_array_copy.dest_array_index = dest_array_imm.index.index;
      *len += dest_array_imm.length;
      ArrayIndexImmediate src_array_imm(decoder, code->at(pc + *len),
                                        Decoder::kNoValidation);
      optional->gc_array_copy.src_array_index = src_array_imm.index.index;
      *len += src_array_imm.length;
      break;
    }
    case kExprRefI31:
    case kExprI31GetS:
    case kExprI31GetU:
    case kExprAnyConvertExtern:
    case kExprExternConvertAny:
    case kExprArrayLen:
      break;
    case kExprRefCast:
    case kExprRefCastNull:
    case kExprRefTest:
    case kExprRefTestNull: {
      HeapTypeImmediate imm(WasmEnabledFeatures::All(), &detected, decoder,
                            code->at(pc + *len), Decoder::kNoValidation);
      value_type_reader::Populate(&imm.type, module_);
      optional->gc_heap_type_immediate.length = imm.length;
      optional->gc_heap_type_immediate.heap_type_bit_field =
          imm.type.raw_bit_field();
      *len += imm.length;
      break;
    }
    case kExprBrOnCast:
    case kExprBrOnCastFail: {
      BrOnCastImmediate flags_imm(decoder, code->at(pc + *len),
                                  Decoder::kNoValidation);
      *len += flags_imm.length;
      BranchDepthImmediate branch(decoder, code->at(pc + *len),
                                  Decoder::kNoValidation);
      *len += branch.length;
      HeapTypeImmediate source_imm(WasmEnabledFeatures::All(), &detected,
                                   decoder, code->at(pc + *len),
                                   Decoder::kNoValidation);
      value_type_reader::Populate(&source_imm.type, module_);
      *len += source_imm.length;
      HeapTypeImmediate target_imm(WasmEnabledFeatures::All(), &detected,
                                   decoder, code->at(pc + *len),
                                   Decoder::kNoValidation);
      value_type_reader::Populate(&target_imm.type, module_);
      *len += target_imm.length;
      DCHECK(target_imm.type.raw_bit_field() <
             (1 << kBranchOnCastDataTargetTypeBitSize));
      optional->br_on_cast_data = BranchOnCastData{
          branch.depth, flags_imm.flags.src_is_null,
          flags_imm.flags.res_is_null, target_imm.type.raw_bit_field()};
      break;
    }
    default:
      FATAL("Unknown or unimplemented opcode #%d:%s", code->start[pc],
            WasmOpcodes::OpcodeName(static_cast<WasmOpcode>(code->start[pc])));
      UNREACHABLE();
  }
}
References v8::internal::wasm::WasmEnabledFeatures::All(), v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewFixed::array_index, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewOrInitData::array_index, v8::internal::wasm::WasmInstruction::Optional::br_on_cast_data, code, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewOrInitData::data_index, v8::internal::DCHECK(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayCopy::dest_array_index, FATAL, v8::internal::wasm::FieldImmediate::field_imm, v8::internal::wasm::BrOnCastImmediate::flags, v8::internal::wasm::WasmInstruction::Optional::gc_array_copy, v8::internal::wasm::WasmInstruction::Optional::gc_array_new_fixed, v8::internal::wasm::WasmInstruction::Optional::gc_array_new_or_init_data, v8::internal::wasm::WasmInstruction::Optional::gc_field_immediate, v8::internal::wasm::WasmInstruction::Optional::gc_heap_type_immediate, v8::internal::wasm::WasmInstruction::Optional::GC_HeapTypeImmediate::heap_type_bit_field, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::WasmInstruction::Optional::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::kBranchOnCastDataTargetTypeBitSize, v8::internal::wasm::Decoder::kNoValidation, v8::internal::wasm::BrOnCastImmediate::length, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::FieldImmediate::length, v8::internal::wasm::HeapTypeImmediate::length, v8::internal::wasm::WasmInstruction::Optional::GC_HeapTypeImmediate::length, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewFixed::length, module_, v8::internal::wasm::WasmOpcodes::OpcodeName(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::internal::wasm::BrOnCastFlags::res_is_null, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayCopy::src_array_index, v8::internal::wasm::BrOnCastFlags::src_is_null, v8::internal::wasm::FieldImmediate::struct_imm, v8::internal::wasm::HeapTypeImmediate::type, and v8::internal::UNREACHABLE().
Referenced by DecodeInstruction().
DecodeInstruction()
WasmInstruction v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction (pc_t pc, Decoder & decoder) [private]
Definition at line 7972 of file wasm-interpreter.cc.
                                                                           {
  pc_t limit = wasm_code_->end - wasm_code_->start;
  if (pc >= limit) return WasmInstruction();
  int len = 1;
  uint8_t orig = wasm_code_->start[pc];
  WasmOpcode opcode = static_cast<WasmOpcode>(orig);
  if (WasmOpcodes::IsPrefixOpcode(opcode)) {
    uint32_t prefixed_opcode_length;
    std::tie(opcode, prefixed_opcode_length) =
        decoder.read_prefixed_opcode<Decoder::NoValidationTag>(
            wasm_code_->at(pc));
    // skip breakpoint by switching on original code.
    len = prefixed_opcode_length;
  }
  WasmInstruction::Optional optional;
  WasmDetectedFeatures detected;
  switch (orig) {
    case kExprUnreachable:
      break;
    case kExprNop:
      break;
    case kExprBlock:
    case kExprLoop:
    case kExprIf:
    case kExprTry: {
      BlockTypeImmediate imm(WasmEnabledFeatures::All(), &detected, &decoder,
                             wasm_code_->at(pc + 1), Decoder::kNoValidation);
      if (imm.sig_index.valid()) {
        // The block has at least one argument or at least two results, its
        // signature is identified by sig_index.
        optional.block.sig_index = imm.sig_index;
        optional.block.value_type_bitfield = kWasmBottom.raw_bit_field();
      } else if (imm.sig.return_count() + imm.sig.parameter_count() == 0) {
        // Void signature: no arguments and no results.
        optional.block.sig_index = ModuleTypeIndex::Invalid();
        optional.block.value_type_bitfield = kWasmVoid.raw_bit_field();
      } else {
        // No arguments and one result.
        optional.block.sig_index = ModuleTypeIndex::Invalid();
        std::optional<wasm::ValueType> wasm_return_type =
            GetWasmReturnTypeFromSignature(&imm.sig);
        DCHECK(wasm_return_type.has_value());
        optional.block.value_type_bitfield =
            wasm_return_type.value().raw_bit_field();
      }
      len = 1 + imm.length;
      break;
    }
    case kExprElse:
      break;
    case kExprCatch: {
      TagIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                            Decoder::kNoValidation);
      optional.index = imm.index;
      len = 1 + imm.length;
      break;
    }
    case kExprCatchAll:
      break;
    case kExprEnd:
      break;
    case kExprThrow: {
      TagIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                            Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprRethrow:
    case kExprBr:
    case kExprBrIf:
    case kExprBrOnNull:
    case kExprBrOnNonNull:
    case kExprDelegate: {
      BranchDepthImmediate imm(&decoder, wasm_code_->at(pc + 1),
                               Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.depth = imm.depth;
      break;
    }
    case kExprBrTable: {
      BranchTableImmediate imm(&decoder, wasm_code_->at(pc + 1),
                               Decoder::kNoValidation);
      BranchTableIterator<Decoder::NoValidationTag> iterator(&decoder, imm);
      optional.br_table.table_count = imm.table_count;
      optional.br_table.labels_index =
          static_cast<uint32_t>(br_table_labels_.size());
      for (uint32_t i = 0; i <= imm.table_count; i++) {
        DCHECK(iterator.has_next());
        br_table_labels_.emplace_back(iterator.next());
      }
      len = static_cast<int>(1 + iterator.pc() - imm.start);
      break;
    }
    case kExprReturn:
      break;
    case kExprCallFunction:
    case kExprReturnCall: {
      CallFunctionImmediate imm(&decoder, wasm_code_->at(pc + 1),
                                Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprCallIndirect:
    case kExprReturnCallIndirect: {
      CallIndirectImmediate imm(&decoder, wasm_code_->at(pc + 1),
                                Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.indirect_call.table_index = imm.table_imm.index;
      optional.indirect_call.sig_index = imm.sig_imm.index.index;
      break;
    }
    case kExprDrop:
      break;
    case kExprSelect:
      break;
    case kExprSelectWithType: {
      SelectTypeImmediate imm(WasmEnabledFeatures::All(), &detected, &decoder,
                              wasm_code_->at(pc + 1), Decoder::kNoValidation);
      len = 1 + imm.length;
      break;
    }
    case kExprLocalGet: {
      IndexImmediate imm(&decoder, wasm_code_->at(pc + 1), "local index",
                         Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprLocalSet: {
      IndexImmediate imm(&decoder, wasm_code_->at(pc + 1), "local index",
                         Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprLocalTee: {
      IndexImmediate imm(&decoder, wasm_code_->at(pc + 1), "local index",
                         Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprGlobalGet: {
      GlobalIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                               Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprGlobalSet: {
      GlobalIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                               Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprTableGet: {
      IndexImmediate imm(&decoder, wasm_code_->at(pc + 1), "table index",
                         Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
    case kExprTableSet: {
      IndexImmediate imm(&decoder, wasm_code_->at(pc + 1), "table index",
                         Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.index = imm.index;
      break;
    }
#define LOAD_CASE(name, ctype, mtype, rep, type) \
  case kExpr##name: { \
    MemoryAccessImmediate imm(\
        &decoder, wasm_code_->at(pc + 1), sizeof(ctype), \
        Decoder::kNoValidation); \
    len = 1 + imm.length; \
    optional.offset = imm.offset; \
    break; \
  }
      LOAD_CASE(I32LoadMem8S, int32_t, int8_t, kWord8, I32);
      LOAD_CASE(I32LoadMem8U, int32_t, uint8_t, kWord8, I32);
      LOAD_CASE(I32LoadMem16S, int32_t, int16_t, kWord16, I32);
      LOAD_CASE(I32LoadMem16U, int32_t, uint16_t, kWord16, I32);
      LOAD_CASE(I64LoadMem8S, int64_t, int8_t, kWord8, I64);
      LOAD_CASE(I64LoadMem8U, int64_t, uint8_t, kWord16, I64);
      LOAD_CASE(I64LoadMem16S, int64_t, int16_t, kWord16, I64);
      LOAD_CASE(I64LoadMem16U, int64_t, uint16_t, kWord16, I64);
      LOAD_CASE(I64LoadMem32S, int64_t, int32_t, kWord32, I64);
      LOAD_CASE(I64LoadMem32U, int64_t, uint32_t, kWord32, I64);
      LOAD_CASE(I32LoadMem, int32_t, int32_t, kWord32, I32);
      LOAD_CASE(I64LoadMem, int64_t, int64_t, kWord64, I64);
      LOAD_CASE(F32LoadMem, Float32, uint32_t, kFloat32, F32);
      LOAD_CASE(F64LoadMem, Float64, uint64_t, kFloat64, F64);
#undef LOAD_CASE
#define STORE_CASE(name, ctype, mtype, rep, type) \
  case kExpr##name: { \
    MemoryAccessImmediate imm(\
        &decoder, wasm_code_->at(pc + 1), sizeof(ctype), \
        Decoder::kNoValidation); \
    len = 1 + imm.length; \
    optional.offset = imm.offset; \
    break; \
  }
      STORE_CASE(I32StoreMem8, int32_t, int8_t, kWord8, I32);
      STORE_CASE(I32StoreMem16, int32_t, int16_t, kWord16, I32);
      STORE_CASE(I64StoreMem8, int64_t, int8_t, kWord8, I64);
      STORE_CASE(I64StoreMem16, int64_t, int16_t, kWord16, I64);
      STORE_CASE(I64StoreMem32, int64_t, int32_t, kWord32, I64);
      STORE_CASE(I32StoreMem, int32_t, int32_t, kWord32, I32);
      STORE_CASE(I64StoreMem, int64_t, int64_t, kWord64, I64);
      STORE_CASE(F32StoreMem, Float32, uint32_t, kFloat32, F32);
      STORE_CASE(F64StoreMem, Float64, uint64_t, kFloat64, F64);
#undef STORE_CASE
    case kExprMemorySize: {
      MemoryIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                               Decoder::kNoValidation);
      len = 1 + imm.length;
      break;
    }
    case kExprMemoryGrow: {
      MemoryIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                               Decoder::kNoValidation);
      len = 1 + imm.length;
      break;
    }
    case kExprI32Const: {
      ImmI32Immediate imm(&decoder, wasm_code_->at(pc + 1),
                          Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.i32 = imm.value;
      break;
    }
    case kExprI64Const: {
      ImmI64Immediate imm(&decoder, wasm_code_->at(pc + 1),
                          Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.i64 = imm.value;
      break;
    }
    case kExprF32Const: {
      ImmF32Immediate imm(&decoder, wasm_code_->at(pc + 1),
                          Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.f32 = imm.value;
      break;
    }
    case kExprF64Const: {
      ImmF64Immediate imm(&decoder, wasm_code_->at(pc + 1),
                          Decoder::kNoValidation);
      len = 1 + imm.length;
      optional.f64 = imm.value;
      break;
    }
#define EXECUTE_BINOP(name, ctype, reg, op, type) \
  case kExpr##name: \
    break;
      FOREACH_COMPARISON_BINOP(EXECUTE_BINOP)
      FOREACH_ARITHMETIC_BINOP(EXECUTE_BINOP)
      FOREACH_TRAPPING_BINOP(EXECUTE_BINOP)
      FOREACH_MORE_BINOP(EXECUTE_BINOP)
#undef EXECUTE_BINOP
#define EXECUTE_UNOP(name, ctype, reg, op, type) \
  case kExpr##name: \
    break;
      FOREACH_SIMPLE_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, from_reg, to_ctype, to_type, \
                     to_reg) \
  case kExpr##name: \
    break;
      FOREACH_ADDITIONAL_CONVERT_UNOP(EXECUTE_UNOP)
      FOREACH_CONVERT_UNOP(EXECUTE_UNOP)
      FOREACH_REINTERPRET_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, to_ctype, to_type, op) \
  case kExpr##name: \
    break;
      FOREACH_BITS_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, to_ctype, to_type) \
  case kExpr##name: \
    break;
      FOREACH_EXTENSION_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
    case kExprRefNull: {
      HeapTypeImmediate imm(WasmEnabledFeatures::All(), &detected, &decoder,
                            wasm_code_->at(pc + 1), Decoder::kNoValidation);
      value_type_reader::Populate(&imm.type, module_);
      optional.ref_type_bit_field = imm.type.raw_bit_field();
      len = 1 + imm.length;
      break;
    }
    case kExprRefIsNull:
    case kExprRefEq:
    case kExprRefAsNonNull: {
      len = 1;
      break;
    }
    case kExprRefFunc: {
      IndexImmediate imm(&decoder, wasm_code_->at(pc + 1), "function index",
                         Decoder::kNoValidation);
      optional.index = imm.index;
      len = 1 + imm.length;
      break;
    }
    case kGCPrefix:
      DecodeGCOp(opcode, &optional, &decoder, wasm_code_, pc, &len);
      break;
    case kNumericPrefix:
      DecodeNumericOp(opcode, &optional, &decoder, wasm_code_, pc, &len);
      break;
    case kAtomicPrefix:
      DecodeAtomicOp(opcode, &optional, &decoder, wasm_code_, pc, &len);
      break;
    case kSimdPrefix: {
      bool is_valid_simd_op =
          DecodeSimdOp(opcode, &optional, &decoder, wasm_code_, pc, &len);
      if (V8_UNLIKELY(!is_valid_simd_op)) {
        UNREACHABLE();
      }
      break;
    }
    case kExprCallRef:
    case kExprReturnCallRef: {
      SigIndexImmediate imm(&decoder, wasm_code_->at(pc + 1),
                            Decoder::kNoValidation);
      optional.index = imm.index.index;
      len = 1 + imm.length;
      break;
    }
    default:
      // Not implemented yet
      UNREACHABLE();
  }
  return WasmInstruction{orig, opcode, len, static_cast<uint32_t>(pc),
                         optional};
}
References v8::internal::wasm::WasmEnabledFeatures::All(), v8::internal::wasm::InterpreterCode::at(), v8::internal::wasm::WasmInstruction::Optional::block, v8::internal::wasm::WasmInstruction::Optional::br_table, br_table_labels_, v8::internal::DCHECK(), DecodeAtomicOp(), DecodeGCOp(), DecodeNumericOp(), DecodeSimdOp(), v8::internal::wasm::BranchDepthImmediate::depth, v8::internal::wasm::WasmInstruction::Optional::depth, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::wasm::InterpreterCode::end, EXECUTE_BINOP, EXECUTE_UNOP, v8::internal::wasm::WasmInstruction::Optional::f32, v8::internal::wasm::WasmInstruction::Optional::f64, FOREACH_ADDITIONAL_CONVERT_UNOP, FOREACH_ARITHMETIC_BINOP, FOREACH_BITS_UNOP, FOREACH_COMPARISON_BINOP, FOREACH_CONVERT_UNOP, FOREACH_EXTENSION_UNOP, FOREACH_MORE_BINOP, FOREACH_REINTERPRET_UNOP, FOREACH_SIMPLE_UNOP, FOREACH_TRAPPING_BINOP, v8::internal::wasm::anonymous_namespace{wasm-interpreter.cc}::GetWasmReturnTypeFromSignature(), v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::wasm::WasmInstruction::Optional::i32, v8::internal::wasm::WasmInstruction::Optional::i64, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::WasmInstruction::Optional::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::WasmInstruction::Optional::indirect_call, v8::internal::wasm::ModuleTypeIndex::Invalid(), v8::internal::wasm::WasmOpcodes::IsPrefixOpcode(), v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::wasm::Decoder::kNoValidation, v8::internal::wasm::kWasmBottom, v8::internal::wasm::kWasmVoid, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::wasm::WasmInstruction::Optional::BrTable::labels_index, v8::internal::wasm::ImmI32Immediate::length, v8::internal::wasm::ImmI64Immediate::length, v8::internal::wasm::ImmF32Immediate::length, v8::internal::wasm::ImmF64Immediate::length, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::TypeIndexImmediate::length, v8::internal::wasm::SelectTypeImmediate::length, v8::internal::wasm::BlockTypeImmediate::length, v8::internal::wasm::BranchDepthImmediate::length, v8::internal::wasm::CallIndirectImmediate::length, v8::internal::wasm::HeapTypeImmediate::length, LOAD_CASE, module_, v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::BranchTableIterator< ValidationTag >::pc(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::internal::wasm::Decoder::read_prefixed_opcode(), v8::internal::wasm::WasmInstruction::Optional::ref_type_bit_field, v8::internal::Signature< T >::return_count(), v8::internal::wasm::BlockTypeImmediate::sig, v8::internal::wasm::CallIndirectImmediate::sig_imm, v8::internal::wasm::BlockTypeImmediate::sig_index, v8::internal::wasm::WasmInstruction::Optional::IndirectCall::sig_index, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, v8::base::SmallVector< T, kSize, Allocator >::size(), v8::internal::wasm::BranchTableImmediate::start, v8::internal::wasm::InterpreterCode::start, STORE_CASE, v8::internal::wasm::BranchTableImmediate::table_count, v8::internal::wasm::WasmInstruction::Optional::BrTable::table_count, v8::internal::wasm::CallIndirectImmediate::table_imm, v8::internal::wasm::WasmInstruction::Optional::IndirectCall::table_index, v8::internal::wasm::HeapTypeImmediate::type, v8::internal::UNREACHABLE(), V8_UNLIKELY, v8::internal::wasm::TypeIndex::valid(), v8::internal::wasm::ImmI32Immediate::value, v8::internal::wasm::ImmI64Immediate::value, v8::internal::wasm::ImmF32Immediate::value, v8::internal::wasm::ImmF64Immediate::value, v8::internal::wasm::WasmInstruction::Optional::Block::value_type_bitfield, and wasm_code_.
Referenced by GenerateBytecode().
DecodeNumericOp()
void v8::internal::wasm::WasmBytecodeGenerator::DecodeNumericOp (WasmOpcode opcode, WasmInstruction::Optional * optional, Decoder * decoder, InterpreterCode * code, pc_t pc, int *const len) [private]
Definition at line 8468 of file wasm-interpreter.cc.
                                                            {
  switch (opcode) {
#define DECODE_UNOP(name, from_ctype, from_type, from_reg, to_ctype, to_type, \
                    to_reg) \
  case kExpr##name: \
    break;
    FOREACH_TRUNCSAT_UNOP(DECODE_UNOP)
#undef DECODE_UNOP
    case kExprMemoryInit: {
      MemoryInitImmediate imm(decoder, code->at(pc + *len),
                              Decoder::kNoValidation);
      DCHECK_LT(imm.data_segment.index, module_->num_declared_data_segments);
      optional->index = imm.data_segment.index;
      *len += imm.length;
      break;
    }
    case kExprDataDrop: {
      IndexImmediate imm(decoder, code->at(pc + *len), "data segment index",
                         Decoder::kNoValidation);
      DCHECK_LT(imm.index, module_->num_declared_data_segments);
      optional->index = imm.index;
      *len += imm.length;
      break;
    }
    case kExprMemoryCopy: {
      MemoryCopyImmediate imm(decoder, code->at(pc + *len),
                              Decoder::kNoValidation);
      *len += imm.length;
      break;
    }
    case kExprMemoryFill: {
      MemoryIndexImmediate imm(decoder, code->at(pc + *len),
                               Decoder::kNoValidation);
      *len += imm.length;
      break;
    }
    case kExprTableInit: {
      TableInitImmediate imm(decoder, code->at(pc + *len),
                             Decoder::kNoValidation);
      optional->table_init.table_index = imm.table.index;
      optional->table_init.element_segment_index = imm.element_segment.index;
      *len += imm.length;
      break;
    }
    case kExprElemDrop: {
      IndexImmediate imm(decoder, code->at(pc + *len), "element segment index",
                         Decoder::kNoValidation);
      optional->index = imm.index;
      *len += imm.length;
      break;
    }
    case kExprTableCopy: {
      TableCopyImmediate imm(decoder, code->at(pc + *len),
                             Decoder::kNoValidation);
      optional->table_copy.dst_table_index = imm.table_dst.index;
      optional->table_copy.src_table_index = imm.table_src.index;
      *len += imm.length;
      break;
    }
    case kExprTableGrow: {
      IndexImmediate imm(decoder, code->at(pc + *len), "table index",
                         Decoder::kNoValidation);
      optional->index = imm.index;
      *len += imm.length;
      break;
    }
    case kExprTableSize: {
      IndexImmediate imm(decoder, code->at(pc + *len), "table index",
                         Decoder::kNoValidation);
      optional->index = imm.index;
      *len += imm.length;
      break;
    }
    case kExprTableFill: {
      IndexImmediate imm(decoder, code->at(pc + *len), "table index",
                         Decoder::kNoValidation);
      optional->index = imm.index;
      *len += imm.length;
      break;
    }
    default:
      FATAL("Unknown or unimplemented opcode #%d:%s", code->start[pc],
            WasmOpcodes::OpcodeName(static_cast<WasmOpcode>(code->start[pc])));
      UNREACHABLE();
  }
}
References code, v8::internal::wasm::MemoryInitImmediate::data_segment, DCHECK_LT, DECODE_UNOP, v8::internal::wasm::WasmInstruction::Optional::TableCopy::dst_table_index, v8::internal::wasm::TableInitImmediate::element_segment, v8::internal::wasm::WasmInstruction::Optional::TableInit::element_segment_index, FATAL, FOREACH_TRUNCSAT_UNOP, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::WasmInstruction::Optional::index, v8::internal::wasm::Decoder::kNoValidation, v8::internal::wasm::IndexImmediate::length, v8::internal::wasm::MemoryInitImmediate::length, v8::internal::wasm::MemoryCopyImmediate::length, v8::internal::wasm::TableInitImmediate::length, v8::internal::wasm::TableCopyImmediate::length, module_, v8::internal::wasm::WasmModule::num_declared_data_segments, v8::internal::wasm::WasmOpcodes::OpcodeName(), v8::internal::wasm::WasmInstruction::Optional::TableCopy::src_table_index, v8::internal::wasm::TableInitImmediate::table, v8::internal::wasm::WasmInstruction::Optional::table_copy, v8::internal::wasm::TableCopyImmediate::table_dst, v8::internal::wasm::WasmInstruction::Optional::TableInit::table_index, v8::internal::wasm::WasmInstruction::Optional::table_init, v8::internal::wasm::TableCopyImmediate::table_src, and v8::internal::UNREACHABLE().
Referenced by DecodeInstruction().
DecodeSimdOp()
bool v8::internal::wasm::WasmBytecodeGenerator::DecodeSimdOp (WasmOpcode opcode, WasmInstruction::Optional * optional, Decoder * decoder, InterpreterCode * code, pc_t pc, int *const len) [private]
Definition at line 17 of file wasm-interpreter-simd.cc.
                                                         {
  static const bool kIsReservedSimdOpcode[256] = {
      // simdop Instruction Immediate operands
      // --------------------------------------------------------
      false, // 0x00 v128.load m:memarg
      false, // 0x01 v128.load8x8_s m:memarg
      false, // 0x02 v128.load8x8_u m:memarg
      false, // 0x03 v128.load16x4_s m:memarg
      false, // 0x04 v128.load16x4_u m:memarg
      false, // 0x05 v128.load32x2_s m:memarg
      false, // 0x06 v128.load32x2_u m:memarg
      false, // 0x07 v128.load8_splat m:memarg
      false, // 0x08 v128.load16_splat m:memarg
      false, // 0x09 v128.load32_splat m:memarg
      false, // 0x0a v128.load64_splat m:memarg
      false, // 0x0b v128.store m:memarg
      false, // 0x0c v128.const i:ImmByte[16]
      false, // 0x0d i8x16.shuffle s:ImmLaneIdx32[16]
      false, // 0x0e i8x16.swizzle -
      false, // 0x0f i8x16.splat -
      false, // 0x10 i16x8.splat -
      false, // 0x11 i32x4.splat -
      false, // 0x12 i64x2.splat -
      false, // 0x13 f32x4.splat -
      false, // 0x14 f64x2.splat -
      false, // 0x15 i8x16.extract_lane_s i:ImmLaneIdx16
      false, // 0x16 i8x16.extract_lane_u i:ImmLaneIdx16
      false, // 0x17 i8x16.replace_lane i:ImmLaneIdx16
      false, // 0x18 i16x8.extract_lane_s i:ImmLaneIdx8
      false, // 0x19 i16x8.extract_lane_u i:ImmLaneIdx8
      false, // 0x1a i16x8.replace_lane i:ImmLaneIdx8
      false, // 0x1b i32x4.extract_lane i:ImmLaneIdx4
      false, // 0x1c i32x4.replace_lane i:ImmLaneIdx4
      false, // 0x1d i64x2.extract_lane i:ImmLaneIdx2
      false, // 0x1e i64x2.replace_lane i:ImmLaneIdx2
      false, // 0x1f f32x4.extract_lane i:ImmLaneIdx4
      false, // 0x20 f32x4.replace_lane i:ImmLaneIdx4
      false, // 0x21 f64x2.extract_lane i:ImmLaneIdx2
      false, // 0x22 f64x2.replace_lane i:ImmLaneIdx2
      false, // 0x23 i8x16.eq -
      false, // 0x24 i8x16.ne -
      false, // 0x25 i8x16.lt_s -
      false, // 0x26 i8x16.lt_u -
      false, // 0x27 i8x16.gt_s -
      false, // 0x28 i8x16.gt_u -
      false, // 0x29 i8x16.le_s -
      false, // 0x2a i8x16.le_u -
      false, // 0x2b i8x16.ge_s -
      false, // 0x2c i8x16.ge_u -
      false, // 0x2d i16x8.eq -
      false, // 0x2e i16x8.ne -
      false, // 0x2f i16x8.lt_s -
      false, // 0x30 i16x8.lt_u -
      false, // 0x31 i16x8.gt_s -
      false, // 0x32 i16x8.gt_u -
      false, // 0x33 i16x8.le_s -
      false, // 0x34 i16x8.le_u -
      false, // 0x35 i16x8.ge_s -
      false, // 0x36 i16x8.ge_u -
      false, // 0x37 i32x4.eq -
      false, // 0x38 i32x4.ne -
      false, // 0x39 i32x4.lt_s -
      false, // 0x3a i32x4.lt_u -
      false, // 0x3b i32x4.gt_s -
      false, // 0x3c i32x4.gt_u -
      false, // 0x3d i32x4.le_s -
      false, // 0x3e i32x4.le_u -
      false, // 0x3f i32x4.ge_s -
      false, // 0x40 i32x4.ge_u -
      false, // 0x41 f32x4.eq -
      false, // 0x42 f32x4.ne -
      false, // 0x43 f32x4.lt -
      false, // 0x44 f32x4.gt -
      false, // 0x45 f32x4.le -
      false, // 0x46 f32x4.ge -
      false, // 0x47 f64x2.eq -
      false, // 0x48 f64x2.ne -
      false, // 0x49 f64x2.lt -
      false, // 0x4a f64x2.gt -
      false, // 0x4b f64x2.le -
      false, // 0x4c f64x2.ge -
      false, // 0x4d v128.not -
      false, // 0x4e v128.and -
      false, // 0x4f v128.andnot -
      false, // 0x50 v128.or -
      false, // 0x51 v128.xor -
      false, // 0x52 v128.bitselect -
      false, // 0x53 v128.any_true -
      false, // 0x54 v128.load8_lane m:memarg, i:ImmLaneIdx16
      false, // 0x55 v128.load16_lane m:memarg, i:ImmLaneIdx8
      false, // 0x56 v128.load32_lane m:memarg, i:ImmLaneIdx4
      false, // 0x57 v128.load64_lane m:memarg, i:ImmLaneIdx2
      false, // 0x58 v128.store8_lane m:memarg, i:ImmLaneIdx16
      false, // 0x59 v128.store16_lane m:memarg, i:ImmLaneIdx8
      false, // 0x5a v128.store32_lane m:memarg, i:ImmLaneIdx4
      false, // 0x5b v128.store64_lane m:memarg, i:ImmLaneIdx2
      false, // 0x5c v128.load32_zero m:memarg
      false, // 0x5d v128.load64_zero m:memarg
      false, // 0x5e f32x4.demote_f64x2_zero -
      false, // 0x5f f64x2.promote_low_f32x4 -
      false, // 0x60 i8x16.abs -
      false, // 0x61 i8x16.neg -
      false, // 0x62 i8x16.popcnt -
      false, // 0x63 i8x16.all_true -
      false, // 0x64 i8x16.bitmask -
      false, // 0x65 i8x16.narrow_i16x8_s -
      false, // 0x66 i8x16.narrow_i16x8_u -
      false, // 0x67 f32x4.ceil -
      false, // 0x68 f32x4.floor -
      false, // 0x69 f32x4.trunc -
      false, // 0x6a f32x4.nearest -
      false, // 0x6b i8x16.shl -
      false, // 0x6c i8x16.shr_s -
      false, // 0x6d i8x16.shr_u -
      false, // 0x6e i8x16.add -
      false, // 0x6f i8x16.add_sat_s -
      false, // 0x70 i8x16.add_sat_u -
      false, // 0x71 i8x16.sub -
      false, // 0x72 i8x16.sub_sat_s -
      false, // 0x73 i8x16.sub_sat_u -
      false, // 0x74 f64x2.ceil -
      false, // 0x75 f64x2.floor -
      false, // 0x76 i8x16.min_s -
      false, // 0x77 i8x16.min_u -
      false, // 0x78 i8x16.max_s -
      false, // 0x79 i8x16.max_u -
      false, // 0x7a f64x2.trunc -
      false, // 0x7b i8x16.avgr_u -
      false, // 0x7c i16x8.extadd_pairwise_i8x16_s -
      false, // 0x7d i16x8.extadd_pairwise_i8x16_u -
      false, // 0x7e i32x4.extadd_pairwise_i16x8_s -
      false, // 0x7f i32x4.extadd_pairwise_i16x8_u -
      false, // 0x80 i16x8.abs -
      false, // 0x81 i16x8.neg -
      false, // 0x82 i16x8.q15mulr_sat_s -
      false, // 0x83 i16x8.all_true -
      false, // 0x84 i16x8.bitmask -
      false, // 0x85 i16x8.narrow_i32x4_s -
      false, // 0x86 i16x8.narrow_i32x4_u -
      false, // 0x87 i16x8.extend_low_i8x16_s -
      false, // 0x88 i16x8.extend_high_i8x16_s -
      false, // 0x89 i16x8.extend_low_i8x16_u -
      false, // 0x8a i16x8.extend_high_i8x16_u -
      false, // 0x8b i16x8.shl -
      false, // 0x8c i16x8.shr_s -
      false, // 0x8d i16x8.shr_u -
      false, // 0x8e i16x8.add -
      false, // 0x8f i16x8.add_sat_s -
      false, // 0x90 i16x8.add_sat_u -
      false, // 0x91 i16x8.sub -
      false, // 0x92 i16x8.sub_sat_s -
      false, // 0x93 i16x8.sub_sat_u -
      false, // 0x94 f64x2.nearest -
      false, // 0x95 i16x8.mul -
      false, // 0x96 i16x8.min_s -
      false, // 0x97 i16x8.min_u -
      false, // 0x98 i16x8.max_s -
      false, // 0x99 i16x8.max_u -
      true, // 0x9a (reserved)
      false, // 0x9b i16x8.avgr_u -
      false, // 0x9c i16x8.extmul_low_i8x16_s -
      false, // 0x9d i16x8.extmul_high_i8x16_s -
      false, // 0x9e i16x8.extmul_low_i8x16_u -
      false, // 0x9f i16x8.extmul_high_i8x16_u -
      false, // 0xa0 i32x4.abs -
      false, // 0xa1 i32x4.neg -
      true, // 0xa2 (reserved)
      false, // 0xa3 i32x4.all_true -
      false, // 0xa4 i32x4.bitmask -
      true, // 0xa5 (reserved)
      true, // 0xa6 (reserved)
      false, // 0xa7 i32x4.extend_low_i16x8_s -
      false, // 0xa8 i32x4.extend_high_i16x8_s -
      false, // 0xa9 i32x4.extend_low_i16x8_u -
      false, // 0xaa i32x4.extend_high_i16x8_u -
      false, // 0xab i32x4.shl -
      false, // 0xac i32x4.shr_s -
      false, // 0xad i32x4.shr_u -
      false, // 0xae i32x4.add -
      true, // 0xaf (reserved)
      true, // 0xb0 (reserved)
      false, // 0xb1 i32x4.sub -
      true, // 0xb2 (reserved)
      true, // 0xb3 (reserved)
      true, // 0xb4 (reserved)
      false, // 0xb5 i32x4.mul -
      false, // 0xb6 i32x4.min_s -
      false, // 0xb7 i32x4.min_u -
      false, // 0xb8 i32x4.max_s -
      false, // 0xb9 i32x4.max_u -
      false, // 0xba i32x4.dot_i16x8_s -
      true, // 0xbb (reserved)
      false, // 0xbc i32x4.extmul_low_i16x8_s -
      false, // 0xbd i32x4.extmul_high_i16x8_s -
      false, // 0xbe i32x4.extmul_low_i16x8_u -
      false, // 0xbf i32x4.extmul_high_i16x8_u -
      false, // 0xc0 i64x2.abs -
      false, // 0xc1 i64x2.neg -
      true, // 0xc2 (reserved)
      false, // 0xc3 i64x2.all_true -
      false, // 0xc4 i64x2.bitmask -
      true, // 0xc5 (reserved)
      true, // 0xc6 (reserved)
      false, // 0xc7 i64x2.extend_low_i32x4_s -
      false, // 0xc8 i64x2.extend_high_i32x4_s -
      false, // 0xc9 i64x2.extend_low_i32x4_u -
      false, // 0xca i64x2.extend_high_i32x4_u -
      false, // 0xcb i64x2.shl -
      false, // 0xcc i64x2.shr_s -
      false, // 0xcd i64x2.shr_u -
      false, // 0xce i64x2.add -
      true, // 0xcf (reserved)
      true, // 0xd0 (reserved)
      false, // 0xd1 i64x2.sub -
      true, // 0xd2 (reserved)
      true, // 0xd3 (reserved)
      true, // 0xd4 (reserved)
      false, // 0xd5 i64x2.mul -
      false, // 0xd6 i64x2.eq -
      false, // 0xd7 i64x2.ne -
      false, // 0xd8 i64x2.lt_s -
      false, // 0xd9 i64x2.gt_s -
      false, // 0xda i64x2.le_s -
      false, // 0xdb i64x2.ge_s -
      false, // 0xdc i64x2.extmul_low_i32x4_s -
      false, // 0xdd i64x2.extmul_high_i32x4_s -
      false, // 0xde i64x2.extmul_low_i32x4_u -
      false, // 0xdf i64x2.extmul_high_i32x4_u -
      false, // 0xe0 f32x4.abs -
      false, // 0xe1 f32x4.neg -
      true, // 0xe2 (reserved)
      false, // 0xe3 f32x4.sqrt -
      false, // 0xe4 f32x4.add -
      false, // 0xe5 f32x4.sub -
      false, // 0xe6 f32x4.mul -
      false, // 0xe7 f32x4.div -
      false, // 0xe8 f32x4.min -
      false, // 0xe9 f32x4.max -
      false, // 0xea f32x4.pmin -
      false, // 0xeb f32x4.pmax -
      false, // 0xec f64x2.abs -
      false, // 0xed f64x2.neg -
      false, // 0xef f64x2.sqrt -
      false, // 0xf0 f64x2.add -
      false, // 0xf1 f64x2.sub -
      false, // 0xf2 f64x2.mul -
      false, // 0xf3 f64x2.div -
      false, // 0xf4 f64x2.min -
      false, // 0xf5 f64x2.max -
      false, // 0xf6 f64x2.pmin -
      false, // 0xf7 f64x2.pmax -
      false, // 0xf8 i32x4.trunc_sat_f32x4_s -
      false, // 0xf9 i32x4.trunc_sat_f32x4_u -
      false, // 0xfa f32x4.convert_i32x4_s -
      false, // 0xfb f32x4.convert_i32x4_u -
      false, // 0xfc i32x4.trunc_sat_f64x2_s_zero -
      false, // 0xfd i32x4.trunc_sat_f64x2_u_zero -
      false, // 0xfe f64x2.convert_low_i32x4_s -
      false // 0xff f64x2.convert_low_i32x4_u -
  };
  if ((opcode >= kExprS128LoadMem && opcode <= kExprS128StoreMem) ||
      opcode == kExprS128Load32Zero || opcode == kExprS128Load64Zero) {
    MemoryAccessImmediate imm(decoder, code->at(pc + *len), 64,
                              Decoder::kNoValidation);
    optional->offset = imm.offset;
    *len += imm.length;
  } else if (opcode == kExprS128Const) {
    Simd128Immediate imm(decoder, code->at(pc + *len), kNoValidate);
    optional->simd_immediate_index = simd_immediates_.size();
    simd_immediates_.push_back(
        Simd128(imm.value)); // TODO(paolosev@microsoft.com): avoid duplicates?
    *len += 16;
  } else if (opcode == kExprI8x16Shuffle) {
    Simd128Immediate imm(decoder, code->at(pc + *len), kNoValidate);
    optional->simd_immediate_index = simd_immediates_.size();
    simd_immediates_.push_back(
        Simd128(imm.value)); // TODO(paolosev@microsoft.com): avoid duplicates?
    *len += 16;
  } else if ((opcode >= kExprI8x16ExtractLaneS) &&
             (opcode <= kExprF64x2ReplaceLane)) {
    SimdLaneImmediate imm(decoder, code->at(pc + *len), kNoValidate);
    if (imm.lane >= kSimd128Size) {
      return false;
    }
    optional->simd_lane = imm.lane;
    *len += 1;
  } else if ((opcode >= kExprS128Load8Lane) &&
             (opcode <= kExprS128Store64Lane)) {
    MemoryAccessImmediate mem_imm(decoder, code->at(pc + *len), 64,
                                  Decoder::kNoValidation);
    if (mem_imm.offset >= ((uint64_t)1 << 48)) {
      return false;
    }
    *len += mem_imm.length;
    SimdLaneImmediate lane_imm(decoder, code->at(pc + *len), kNoValidate);
    if (lane_imm.lane >= kSimd128Size) {
      return false;
    }
    optional->simd_loadstore_lane.offset = mem_imm.offset;
    optional->simd_loadstore_lane.lane = lane_imm.lane;
    *len += lane_imm.length;
  } else if (WasmOpcodes::IsRelaxedSimdOpcode(opcode)) {
    // Relaxed SIMD opcodes:
    // 0x100 i8x16.relaxed_swizzle -
    // 0x101 i32x4.relaxed_trunc_f32x4_s -
    // 0x102 i32x4.relaxed_trunc_f32x4_u -
    // 0x103 i32x4.relaxed_trunc_f64x2_s_zero -
    // 0x104 i32x4.relaxed_trunc_f64x2_u_zero -
    // 0x105 f32x4.relaxed_madd -
    // 0x106 f32x4.relaxed_nmadd -
    // 0x107 f64x2.relaxed_madd -
    // 0x108 f64x2.relaxed_nmadd -
    // 0x109 i8x16.relaxed_laneselect -
    // 0x10a i16x8.relaxed_laneselect -
    // 0x10b i32x4.relaxed_laneselect -
    // 0x10c i64x2.relaxed_laneselect -
    // 0x10d f32x4.relaxed_min -
    // 0x10e f32x4.relaxed_max -
    // 0x10f f64x2.relaxed_min -
    // 0x110 f64x2.relaxed_max -
    // 0x111 i16x8.relaxed_q15mulr_s -
    // 0x112 i16x8.relaxed_dot_i8x16_i7x16_s -
    // 0x113 i32x4.relaxed_dot_i8x16_i7x16_add_s -
    return opcode <= 0xfd113;
    // Handle relaxed SIMD opcodes (in [0xfd100, 0xfd1ff]).
  } else if (opcode >= 0xfd200 || kIsReservedSimdOpcode[opcode & 0xff]) {
    FATAL("Unknown or unimplemented opcode #%d:%s", code->start[pc],
          WasmOpcodes::OpcodeName(static_cast<WasmOpcode>(code->start[pc])));
    UNREACHABLE();
  } else {
    // No immediate operands.
  }
  return true;
}
References code, FATAL, v8::internal::wasm::WasmOpcodes::IsRelaxedSimdOpcode(), v8::internal::wasm::kNoValidate, v8::internal::wasm::Decoder::kNoValidation, v8::internal::kSimd128Size, v8::internal::wasm::SimdLaneImmediate::lane, v8::internal::wasm::WasmInstruction::Optional::SimdLaneLoad::lane, v8::internal::wasm::MemoryAccessImmediate::length, v8::internal::wasm::SimdLaneImmediate::length, v8::internal::wasm::MemoryAccessImmediate::offset, v8::internal::wasm::WasmInstruction::Optional::offset, v8::internal::wasm::WasmInstruction::Optional::SimdLaneLoad::offset, v8::internal::wasm::WasmOpcodes::OpcodeName(), v8::internal::wasm::WasmInstruction::Optional::simd_immediate_index, simd_immediates_, v8::internal::wasm::WasmInstruction::Optional::simd_lane, v8::internal::wasm::WasmInstruction::Optional::simd_loadstore_lane, v8::internal::UNREACHABLE(), and v8::internal::wasm::Simd128Immediate::value.
Referenced by DecodeInstruction().
DoEncodeInstruction()
RegMode v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction (const WasmInstruction & instr, RegMode curr_reg_mode, RegMode next_reg_mode) [private]
Definition at line 9352 of file wasm-interpreter.cc.
                                                                          {
  DCHECK(curr_reg_mode != RegMode::kAnyReg);
#ifdef DEBUG
  was_current_instruction_reachable_ = is_instruction_reachable_;
#endif // DEBUG
  if (!is_instruction_reachable_) {
    if (instr.opcode == kExprBlock || instr.opcode == kExprLoop ||
        instr.opcode == kExprIf || instr.opcode == kExprTry) {
      unreachable_block_count_++;
    } else if (instr.opcode == kExprEnd || instr.opcode == kExprDelegate) {
      DCHECK_GT(unreachable_block_count_, 0);
      if (0 == --unreachable_block_count_) {
        is_instruction_reachable_ = true;
      }
    } else if (instr.opcode == kExprElse || instr.opcode == kExprCatch ||
               instr.opcode == kExprCatchAll) {
      if (1 == unreachable_block_count_) {
        is_instruction_reachable_ = true;
        unreachable_block_count_ = 0;
      }
    }
  }
  if (!is_instruction_reachable_) return RegMode::kNoReg;
  ValueKind top_stack_slot_type = GetTopStackType(curr_reg_mode);
  OperatorMode mode = kS2S;
  if (v8_flags.drumbrake_register_optimization) {
    switch (next_reg_mode) {
      case RegMode::kNoReg:
        if (curr_reg_mode != RegMode::kNoReg) {
          mode = kR2S;
        }
        break;
      case RegMode::kAnyReg:
      default: // kI32Reg|kI64Reg|kF32Reg|kF64Reg
        if (curr_reg_mode == RegMode::kNoReg) {
          if (ToRegisterIsAllowed(instr)) {
            mode = kS2R;
          } else {
            mode = kS2S;
          }
        } else {
          if (ToRegisterIsAllowed(instr)) {
            mode = kR2R;
          } else {
            mode = kR2S;
          }
        }
        break;
    }
  }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_bytecode_generator) {
    printf("PRE @%-3u: %-24s: %3s %-7s -> %-7s\n", instr.pc,
           wasm::WasmOpcodes::OpcodeName(static_cast<WasmOpcode>(instr.opcode)),
           GetOperatorModeString(mode), GetRegModeString(curr_reg_mode),
           GetRegModeString(next_reg_mode));
  }
  if (v8_flags.trace_drumbrake_execution) {
    EMIT_INSTR_HANDLER(s2s_TraceInstruction);
    EmitI32Const(instr.pc);
    EmitI32Const(instr.opcode);
    EmitI32Const(static_cast<int>(curr_reg_mode));
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  switch (instr.opcode) {
    case kExprUnreachable: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_Unreachable, instr.pc);
      SetUnreachableMode();
      break;
    }
    case kExprNop:
      break;
    case kExprBlock:
    case kExprLoop: {
      PreserveArgsAndLocals();
      BeginBlock(instr.opcode, instr.optional.block);
      break;
    }
    case kExprTry: {
      PreserveArgsAndLocals();
      int parent_or_matching_try_block_index = GetCurrentTryBlockIndex(true);
      int ancestor_try_block_index = GetCurrentTryBlockIndex(false);
      int try_block_index = BeginBlock(instr.opcode, instr.optional.block);
      eh_data_.AddTryBlock(try_block_index, parent_or_matching_try_block_index,
                           ancestor_try_block_index);
      break;
    }
    case kExprIf: {
      PreserveArgsAndLocals();
      if (mode == kR2S) {
        EMIT_INSTR_HANDLER(r2s_If);
      } else {
        DCHECK_EQ(mode, kS2S);
        EMIT_INSTR_HANDLER(s2s_If);
        I32Pop(); // cond
      }
      BeginBlock(instr.opcode, instr.optional.block);
      EmitIfElseBranchOffset();
      break;
    }
    case kExprElse: {
      DCHECK_GT(current_block_index_, 0);
      DCHECK(blocks_[current_block_index_].IsIf());
      BeginElseBlock(current_block_index_, false);
      EMIT_INSTR_HANDLER(s2s_Else);
      EmitIfElseBranchOffset(); // Jumps to the end of the 'else' block.
      break;
    }
    case kExprCatch:
    case kExprCatchAll: {
      DCHECK_GT(current_block_index_, 0);
      int try_block_index = eh_data_.GetCurrentTryBlockIndex();
      DCHECK_GT(try_block_index, 0);
      EndBlock(instr.opcode); // End previous try or catch.
      stack_.resize(blocks_[try_block_index].stack_size_);
      int32_t catch_block_index =
          BeginBlock(instr.opcode, blocks_[try_block_index].signature_);
      EMIT_INSTR_HANDLER(s2s_Catch);
      EmitTryCatchBranchOffset(); // Jumps to the end of the try/catch blocks.
      uint32_t first_param_slot_index = UINT_MAX;
      uint32_t first_ref_param_slot_index = UINT_MAX;
      if (instr.opcode == kExprCatch) {
        // Exception arguments are pushed into the stack.
        const WasmTag& tag = module_->tags[instr.optional.index];
        const FunctionSig* sig = tag.sig;
        for (size_t i = 0; i < sig->parameter_count(); ++i) {
          const ValueType value_type = sig->GetParam(i);
          const ValueKind kind = value_type.kind();
          switch (kind) {
            case kI32:
            case kI64:
            case kF32:
            case kF64:
            case kS128:
            case kRef:
            case kRefNull: {
              uint32_t slot_index = CreateSlot(value_type);
              if (first_param_slot_index == UINT_MAX) {
                first_param_slot_index = slot_index;
              }
              if ((kind == kRefNull || kind == kRef) &&
                  first_ref_param_slot_index == UINT_MAX) {
                first_ref_param_slot_index = slot_index;
              }
              PushSlot(slot_index);
              slots_[slot_index].value_type = value_type;
              break;
            }
            default:
              UNREACHABLE();
          }
        }
      }
      blocks_[catch_block_index].first_block_index_ =
          blocks_[try_block_index].first_block_index_;
      if (instr.opcode == kExprCatch) {
        eh_data_.AddCatchBlock(
            current_block_index_, instr.optional.index,
            first_param_slot_index == UINT_MAX
                ? 0
                : slots_[first_param_slot_index].slot_offset,
            first_ref_param_slot_index == UINT_MAX
                ? 0
                : slots_[first_ref_param_slot_index].ref_stack_index,
            static_cast<int>(code_.size()));
      } else { // kExprCatchAll
        eh_data_.AddCatchBlock(current_block_index_,
                               WasmEHData::kCatchAllTagIndex, 0, 0,
                               static_cast<int>(code_.size()));
      }
      break;
    }
    case kExprDelegate: {
      int32_t target_block_index = GetTargetBranch(instr.optional.depth + 1);
      DCHECK_LT(target_block_index, blocks_.size());
      int32_t delegated_try_block_index = WasmEHData::kDelegateToCallerIndex;
      if (target_block_index > 0) {
        const BlockData& target_block = blocks_[target_block_index];
        delegated_try_block_index = target_block.IsTry()
                                        ? target_block_index
                                        : target_block.parent_try_block_index_;
      }
      eh_data_.AddDelegatedBlock(delegated_try_block_index);
      EndBlock(kExprDelegate);
      break;
    }
    case kExprThrow: {
      EMIT_INSTR_HANDLER(s2s_Throw);
      EmitI32Const(instr.optional.index);
      // Exception arguments are popped from the stack (in reverse order!)
      const WasmTag& tag = module_->tags[instr.optional.index];
      const WasmTagSig* sig = tag.sig;
      DCHECK_GE(stack_.size(), sig->parameter_count());
      size_t stack_index = stack_.size() - sig->parameter_count();
      for (size_t index = 0; index < sig->parameter_count();
           index++, stack_index++) {
        ValueKind kind = sig->GetParam(index).kind();
        DCHECK(CheckEqualKind(kind, slots_[stack_[stack_index]].kind()));
        switch (kind) {
          case kI32:
          case kI64:
          case kF32:
          case kF64:
          case kS128: {
            EmitSlotOffset(slots_[stack_[stack_index]].slot_offset);
            break;
          }
          case kRef:
          case kRefNull: {
            uint32_t ref_index = slots_[stack_[stack_index]].ref_stack_index;
            Emit(&ref_index, sizeof(uint32_t));
            break;
          }
          default:
            UNREACHABLE();
        }
      }
      stack_.resize(stack_.size() - sig->parameter_count());
      eh_data_.RecordPotentialExceptionThrowingInstruction(instr.opcode,
                                                           CurrentCodePos());
      SetUnreachableMode();
      break;
    }
    case kExprRethrow: {
      EMIT_INSTR_HANDLER(s2s_Rethrow);
      int32_t target_branch_index = GetTargetBranch(instr.optional.depth);
      DCHECK(blocks_[target_branch_index].IsCatch() ||
             blocks_[target_branch_index].IsCatchAll());
      Emit(&target_branch_index, sizeof(int32_t));
      eh_data_.RecordPotentialExceptionThrowingInstruction(instr.opcode,
                                                           CurrentCodePos());
      SetUnreachableMode();
      break;
    }
    case kExprEnd: {
      // If there is an 'if...end' statement without an 'else' branch, create
      // a dummy else branch used to store results.
      if (blocks_[current_block_index_].IsIf()) {
        uint32_t if_block_index = current_block_index_;
        DCHECK(!blocks_[if_block_index].HasElseBranch());
        uint32_t params_count = ParamsCount(blocks_[if_block_index]);
        if (params_count > 0) {
          BeginElseBlock(if_block_index, true);
          EMIT_INSTR_HANDLER(s2s_Else);
          EmitIfElseBranchOffset(); // Jumps to the end of the 'else' block.
        }
      }
      if (EndBlock(kExprEnd) < 0) {
        Return();
      }
      break;
    }
    case kExprBr: {
      int32_t target_branch_index = GetTargetBranch(instr.optional.depth);
      StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBr);
      EMIT_INSTR_HANDLER(s2s_Branch);
      EmitBranchOffset(instr.optional.depth);
      SetUnreachableMode();
      break;
    }
    case kExprBrIf: {
      int32_t target_branch_index = GetTargetBranch(instr.optional.depth);
      const WasmBytecodeGenerator::BlockData& target_block_data =
          blocks_[target_branch_index];
      if (HasVoidSignature(target_block_data)) {
        if (mode == kR2S) {
          EMIT_INSTR_HANDLER(r2s_BranchIf);
        } else {
          DCHECK_EQ(mode, kS2S);
          EMIT_INSTR_HANDLER(s2s_BranchIf);
          I32Pop(); // condition
        }
        // Emit code offset to branch to if the condition is true.
        EmitBranchOffset(instr.optional.depth);
      } else {
        if (mode == kR2S) {
          EMIT_INSTR_HANDLER(r2s_BranchIfWithParams);
        } else {
          DCHECK_EQ(mode, kS2S);
          EMIT_INSTR_HANDLER(s2s_BranchIfWithParams);
          I32Pop(); // condition
        }
        // Emit code offset to branch to if the condition is not true.
        const uint32_t if_false_code_offset = CurrentCodePos();
        Emit(&if_false_code_offset, sizeof(if_false_code_offset));
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrIf);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchOffset(instr.optional.depth);
        // Patch the 'if-false' offset with the correct jump offset.
        int32_t delta = CurrentCodePos() - if_false_code_offset;
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(code_.data() + if_false_code_offset),
            delta);
      }
      break;
    }
    case kExprBrOnNull: {
      DCHECK_EQ(mode, kS2S);
      int32_t target_branch_index = GetTargetBranch(instr.optional.depth);
      const WasmBytecodeGenerator::BlockData& target_block_data =
          blocks_[target_branch_index];
      if (HasVoidSignature(target_block_data)) {
        EMIT_INSTR_HANDLER(s2s_BranchOnNull);
        ValueType value_type = RefPop(); // pop condition
        EmitRefValueType(value_type.raw_bit_field());
        // Remove nullability.
        if (value_type.kind() == kRefNull) {
          value_type = ValueType::Ref(value_type.heap_type());
        }
        RefPush(value_type); // re-push condition value
        // Emit code offset to branch to if the condition is true.
        EmitBranchOffset(instr.optional.depth);
      } else {
        EMIT_INSTR_HANDLER(s2s_BranchOnNullWithParams);
        ValueType value_type = RefPop(); // pop condition
        EmitRefValueType(value_type.raw_bit_field());
        // Remove nullability.
        if (value_type.kind() == kRefNull) {
          value_type = ValueType::Ref(value_type.heap_type());
        }
        RefPush(value_type); // re-push condition value
        // Emit code offset to branch to if the condition is not true.
        const uint32_t if_false_code_offset = CurrentCodePos();
        Emit(&if_false_code_offset, sizeof(if_false_code_offset));
        uint32_t stack_top = stack_.back();
        RefPop(false); // Drop the null reference.
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrIf);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchOffset(instr.optional.depth);
        stack_.push_back(stack_top); // re-push non-null ref on top of stack
        // Patch the 'if-false' offset with the correct jump offset.
        int32_t delta = CurrentCodePos() - if_false_code_offset;
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(code_.data() + if_false_code_offset),
            delta);
      }
      break;
    }
    case kExprBrOnNonNull: {
      DCHECK_EQ(mode, kS2S);
      int32_t target_branch_index = GetTargetBranch(instr.optional.depth);
      const WasmBytecodeGenerator::BlockData& target_block_data =
          blocks_[target_branch_index];
      if (HasVoidSignature(target_block_data)) {
        EMIT_INSTR_HANDLER(s2s_BranchOnNonNull);
        ValueType value_type = RefPop(); // pop condition
        EmitRefValueType(value_type.raw_bit_field());
        RefPush(value_type); // re-push condition value
        // Emit code offset to branch to if the condition is true.
        EmitBranchOffset(instr.optional.depth);
        RefPop(false); // Drop the null reference.
      } else {
        EMIT_INSTR_HANDLER(s2s_BranchOnNonNullWithParams);
        ValueType value_type = RefPop(); // pop condition
        EmitRefValueType(value_type.raw_bit_field());
        RefPush(value_type); // re-push condition value
        // Emit code offset to branch to if the condition is not true.
        const uint32_t if_false_code_offset = CurrentCodePos();
        Emit(&if_false_code_offset, sizeof(if_false_code_offset));
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrIf);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchOffset(instr.optional.depth);
        // Patch the 'if-false' offset with the correct jump offset.
        int32_t delta = CurrentCodePos() - if_false_code_offset;
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(code_.data() + if_false_code_offset),
            delta);
        RefPop(false); // Drop the null reference.
      }
      break;
    }
    case kExprBrOnCast: {
      const BranchOnCastData& br_on_cast_data = instr.optional.br_on_cast_data;
      const int32_t target_branch_index =
          GetTargetBranch(br_on_cast_data.label_depth);
      bool null_succeeds = br_on_cast_data.res_is_null;
      const ValueType target_type = ValueType::RefMaybeNull(
          HeapType::FromBits(br_on_cast_data.target_type_bit_fields),
          null_succeeds ? kNullable : kNonNullable);
      const ValueType obj_type = slots_[stack_.back()].value_type;
      DCHECK(obj_type.is_object_reference());
      // This logic ensures that code generation can assume that functions can
      // only be cast to function types, and data objects to data types.
      if (V8_UNLIKELY(
              TypeCheckAlwaysSucceeds(obj_type, target_type.heap_type()))) {
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrOnCast);
        // The branch will still not be taken on null if not {null_succeeds}.
        if (obj_type.is_nullable() && !null_succeeds) {
          EMIT_INSTR_HANDLER(s2s_BranchOnNull);
          RefPop(); // pop condition
          EmitRefValueType(obj_type.raw_bit_field());
          RefPush(target_type); // re-push condition value with a new HeapType.
          EmitBranchOffset(br_on_cast_data.label_depth);
        } else {
          EMIT_INSTR_HANDLER(s2s_Branch);
          EmitBranchOffset(br_on_cast_data.label_depth);
        }
      } else if (V8_LIKELY(!TypeCheckAlwaysFails(
                     obj_type, target_type.heap_type(), null_succeeds))) {
        EMIT_INSTR_HANDLER(s2s_BranchOnCast);
        EmitI32Const(null_succeeds);
        HeapType br_on_cast_data_target_type(
            HeapType::FromBits(br_on_cast_data.target_type_bit_fields));
        EmitI32Const(br_on_cast_data_target_type.is_index()
                         ? br_on_cast_data_target_type.raw_bit_field()
                         : target_type.heap_type().raw_bit_field());
        ValueType value_type = RefPop();
        EmitRefValueType(value_type.raw_bit_field());
        RefPush(value_type);
        // Emit code offset to branch to if the condition is not true.
        const uint32_t no_branch_code_offset = CurrentCodePos();
        Emit(&no_branch_code_offset, sizeof(no_branch_code_offset));
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrOnCast);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchOffset(br_on_cast_data.label_depth);
        // Patch the 'if-false' offset with the correct jump offset.
        int32_t delta = CurrentCodePos() - no_branch_code_offset;
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(code_.data() + no_branch_code_offset),
            delta);
      }
      break;
    }
    case kExprBrOnCastFail: {
      const BranchOnCastData& br_on_cast_data = instr.optional.br_on_cast_data;
      int32_t target_branch_index =
          GetTargetBranch(br_on_cast_data.label_depth);
      bool null_succeeds = br_on_cast_data.res_is_null;
      HeapType br_on_cast_data_target_type =
          HeapType::FromBits(br_on_cast_data.target_type_bit_fields);
      const ValueType target_type =
          ValueType::RefMaybeNull(br_on_cast_data_target_type,
                                  null_succeeds ? kNullable : kNonNullable);
      const ValueType obj_type = slots_[stack_.back()].value_type;
      DCHECK(obj_type.is_object_reference());
      // This logic ensures that code generation can assume that functions can
      // only be cast to function types, and data objects to data types.
      if (V8_UNLIKELY(TypeCheckAlwaysFails(obj_type, target_type.heap_type(),
                                           null_succeeds))) {
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrOnCast);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchOffset(br_on_cast_data.label_depth);
      } else if (V8_UNLIKELY(TypeCheckAlwaysSucceeds(
                     obj_type, target_type.heap_type()))) {
        // The branch can still be taken on null.
        if (obj_type.is_nullable() && !null_succeeds) {
          StoreBlockParamsAndResultsIntoSlots(target_branch_index,
                                              kExprBrOnCast);
          EMIT_INSTR_HANDLER(s2s_BranchOnNull);
          RefPop(); // pop condition
          EmitRefValueType(obj_type.raw_bit_field());
          RefPush(target_type); // re-push condition value with a new HeapType.
          EmitBranchOffset(br_on_cast_data.label_depth);
        } else {
          // Fallthrough.
        }
      } else {
        EMIT_INSTR_HANDLER(s2s_BranchOnCastFail);
        EmitI32Const(null_succeeds);
        EmitI32Const(br_on_cast_data_target_type.is_index()
                         ? br_on_cast_data_target_type.raw_bit_field()
                         : target_type.heap_type().raw_bit_field());
        ValueType value_type = RefPop();
        EmitRefValueType(value_type.raw_bit_field());
        RefPush(value_type);
        // Emit code offset to branch to if the condition is not true.
        const uint32_t no_branch_code_offset = CurrentCodePos();
        Emit(&no_branch_code_offset, sizeof(no_branch_code_offset));
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrOnCast);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchOffset(br_on_cast_data.label_depth);
        // Patch the 'if-false' offset with the correct jump offset.
        int32_t delta = CurrentCodePos() - no_branch_code_offset;
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(code_.data() + no_branch_code_offset),
            delta);
      }
      break;
    }
    case kExprBrTable: {
      if (mode == kR2S) {
        EMIT_INSTR_HANDLER(r2s_BrTable);
      } else {
        DCHECK_EQ(mode, kS2S);
        EMIT_INSTR_HANDLER(s2s_BrTable);
        I32Pop(); // branch label
      }
      // We emit the following bytecode for a br_table instruction:
      // s2s_BrTable handler id
      // (uint32) labels_count
      // (uint32) offset branch 0
      // (uint32) offset branch 1
      // ...
      // (uint32) offset branch labels_count - 1
      // (uint32) offset branch labels_count (default branch)
      // { Branch 0 slots }
      // { Branch 1 slots }
      // ...
      // { Branch labels_count slots }
      //
      // Where each {Branch i slots} contains the slots to execute a Branch
      // instruction:
      // { CopySlots for branch results, if present }
      // s2s_Branch handler id
      // (uint32) branch_offset (to be patched later)
      //
      const uint32_t labels_count = instr.optional.br_table.table_count;
      EmitI32Const(labels_count);
      uint32_t labels_offset_start = CurrentCodePos();
      for (uint32_t i = 0; i <= labels_count; i++) {
        // Here we don't know what will be the offset of this branch yet, so we
        // pass the current bytecode position as offset. This value will be
        // overwritten in the next loop.
        const uint32_t label_offset = CurrentCodePos();
        Emit(&label_offset, sizeof(label_offset));
      }
      for (uint32_t i = 0; i <= labels_count; i++) {
        uint32_t label =
            br_table_labels_[instr.optional.br_table.labels_index + i];
        int32_t target_branch_index = GetTargetBranch(label);
        uint32_t branch_code_start = CurrentCodePos();
        StoreBlockParamsAndResultsIntoSlots(target_branch_index, kExprBrTable);
        EMIT_INSTR_HANDLER(s2s_Branch);
        EmitBranchTableOffset(label, CurrentCodePos());
        // Patch the branch offset with the correct jump offset.
        uint32_t label_offset = labels_offset_start + i * sizeof(uint32_t);
        int32_t delta = branch_code_start - label_offset;
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(code_.data() + label_offset), delta);
      }
      SetUnreachableMode();
      break;
    }
    case kExprReturn: {
      Return();
      SetUnreachableMode();
      break;
    }
    case kExprCallFunction:
    case kExprReturnCall: {
      uint32_t function_index = instr.optional.index;
      const FunctionSig* sig = GetFunctionSignature(function_index);
      // Layout of a frame:
      // ------------------
      // stack slot #N-1 \
      // ... |
      // stack slot #0 _/
      // local #L-1 \
      // ... |
      // local #0 _/
      // const #C-1 \
      // ... |
      // const #0 _/
      // param #P-1 \
      // ... |
      // param #0 _/
      // return #R-1 \
      // ... |
      // return #0 _/
      // ------------------
      const bool is_imported = (module_->functions[function_index].imported);
      const bool is_tail_call = (instr.opcode == kExprReturnCall);
      uint32_t slot_offset = GetStackFrameSize() * kSlotSize;
      uint32_t ref_stack_fp_offset = ref_slots_count_;
      std::vector<uint32_t> rets_slots;
      rets_slots.resize(sig->return_count());
      for (size_t index = 0; index < sig->return_count(); index++) {
        rets_slots[index] = is_tail_call ? static_cast<uint32_t>(index)
                                         : CreateSlot(sig->GetReturn(index));
      }
      InitSlotsForFunctionArgs(sig, false);
      if (is_imported) {
        if (is_tail_call) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_ReturnCallImportedFunction, instr.pc);
          EmitSlotOffset(WasmBytecode::RetsSizeInSlots(sig) * kSlotSize);
          EmitSlotOffset(WasmBytecode::ArgsSizeInSlots(sig) * kSlotSize);
          EmitI32Const(WasmBytecode::RefRetsCount(sig));
          EmitI32Const(WasmBytecode::RefArgsCount(sig));
        } else {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_CallImportedFunction, instr.pc);
        }
      } else {
        if (is_tail_call) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_ReturnCall, instr.pc);
          EmitSlotOffset(WasmBytecode::RetsSizeInSlots(sig) * kSlotSize);
          EmitSlotOffset(WasmBytecode::ArgsSizeInSlots(sig) * kSlotSize);
          EmitI32Const(WasmBytecode::RefRetsCount(sig));
          EmitI32Const(WasmBytecode::RefArgsCount(sig));
        } else {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_CallFunction, instr.pc);
        }
      }
      EmitI32Const(function_index);
      EmitStackIndex(static_cast<uint32_t>(stack_.size()));
      EmitSlotOffset(slot_offset);
      EmitRefStackIndex(ref_stack_fp_offset);
      // Function arguments are popped from the stack.
      for (size_t index = sig->parameter_count(); index > 0; index--) {
        Pop(sig->GetParam(index - 1).kind(), false);
      }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      if (v8_flags.trace_drumbrake_execution) {
        EmitSlotOffset(rets_slots.empty()
                           ? 0
                           : slots_[rets_slots[0]].slot_offset * kSlotSize);
      }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
      if (!is_tail_call) {
        eh_data_.RecordPotentialExceptionThrowingInstruction(instr.opcode,
                                                             CurrentCodePos());
      }
      // Function results are pushed to the stack.
      for (size_t index = 0; index < sig->return_count(); index++) {
        const ValueType value_type = sig->GetReturn(index);
        const ValueKind kind = value_type.kind();
        switch (kind) {
          case kI32:
          case kI64:
          case kF32:
          case kF64:
          case kS128:
          case kRef:
          case kRefNull:
            PushSlot(rets_slots[index]);
            SetSlotType(stack_top_index(), value_type);
            break;
          default:
            UNREACHABLE();
        }
      }
      // If this is a tail call, the following instructions in this block are
      // unreachable.
      if (is_tail_call) {
        SetUnreachableMode();
      }
      return RegMode::kNoReg;
    }
    case kExprCallIndirect:
    case kExprReturnCallIndirect: {
      const FunctionSig* sig = module_->signature(
          ModuleTypeIndex({instr.optional.indirect_call.sig_index}));
      const bool is_tail_call = (instr.opcode == kExprReturnCallIndirect);
      uint32_t slot_offset = GetStackFrameSize() * kSlotSize;
      uint32_t ref_stack_fp_offset = ref_slots_count_;
      // Reserve space for return values.
      std::vector<uint32_t> rets_slots;
      rets_slots.resize(sig->return_count());
      for (size_t index = 0; index < sig->return_count(); index++) {
        rets_slots[index] = is_tail_call ? static_cast<uint32_t>(index)
                                         : CreateSlot(sig->GetReturn(index));
      }
      InitSlotsForFunctionArgs(sig, true);
      bool is_table64 =
          module_->tables[instr.optional.indirect_call.table_index]
              .is_table64();
      if (is_tail_call) {
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_ReturnCallIndirect,
                                         s2s_ReturnCallIndirect64, is_table64,
                                         instr.pc);
        EmitSlotOffset(WasmBytecode::RetsSizeInSlots(sig) * kSlotSize);
        EmitSlotOffset(WasmBytecode::ArgsSizeInSlots(sig) * kSlotSize);
        EmitI32Const(WasmBytecode::RefRetsCount(sig));
        EmitI32Const(WasmBytecode::RefArgsCount(sig));
      } else {
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_CallIndirect, s2s_CallIndirect64,
                                         is_table64, instr.pc);
      }
      // Pops the index of the function to call.
      is_table64 ? I64Pop() : I32Pop();
      EmitI32Const(instr.optional.indirect_call.table_index);
      EmitI32Const(instr.optional.indirect_call.sig_index);
      EmitStackIndex(stack_size());
      EmitSlotOffset(slot_offset);
      EmitRefStackIndex(ref_stack_fp_offset);
      // Function arguments are popped from the stack.
      for (size_t index = sig->parameter_count(); index > 0; index--) {
        Pop(sig->GetParam(index - 1).kind(), false);
      }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      if (v8_flags.trace_drumbrake_execution) {
        EmitSlotOffset(rets_slots.empty()
                           ? 0
                           : slots_[rets_slots[0]].slot_offset * kSlotSize);
      }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
      if (!is_tail_call) {
        eh_data_.RecordPotentialExceptionThrowingInstruction(instr.opcode,
                                                             CurrentCodePos());
      }
      // Function result is pushed to the stack.
      for (size_t index = 0; index < sig->return_count(); index++) {
        ValueType value_type = sig->GetReturn(index);
        switch (value_type.kind()) {
          case kI32:
          case kI64:
          case kF32:
          case kF64:
          case kS128:
          case kRef:
          case kRefNull:
            PushSlot(rets_slots[index]);
            SetSlotType(stack_top_index(), value_type);
            break;
          default:
            UNREACHABLE();
        }
      }
      // If this is a tail call, the following instructions in this block are
      // unreachable.
      if (is_tail_call) {
        SetUnreachableMode();
      }
      return RegMode::kNoReg;
    }
    case kExprCallRef:
    case kExprReturnCallRef: {
      const FunctionSig* sig =
          module_->signature(ModuleTypeIndex({instr.optional.index}));
      const bool is_tail_call = (instr.opcode == kExprReturnCallRef);
      uint32_t slot_offset = GetStackFrameSize() * kSlotSize;
      uint32_t ref_stack_fp_offset = ref_slots_count_;
      // Reserve space for return values.
      std::vector<uint32_t> rets_slots;
      rets_slots.resize(sig->return_count());
      for (size_t index = 0; index < sig->return_count(); index++) {
        rets_slots[index] = is_tail_call ? static_cast<uint32_t>(index)
                                         : CreateSlot(sig->GetReturn(index));
      }
      InitSlotsForFunctionArgs(sig, true);
      if (is_tail_call) {
        EMIT_INSTR_HANDLER_WITH_PC(s2s_ReturnCallRef, instr.pc);
        EmitSlotOffset(WasmBytecode::RetsSizeInSlots(sig) * kSlotSize);
        EmitSlotOffset(WasmBytecode::ArgsSizeInSlots(sig) * kSlotSize);
        EmitI32Const(WasmBytecode::RefRetsCount(sig));
        EmitI32Const(WasmBytecode::RefArgsCount(sig));
      } else {
        EMIT_INSTR_HANDLER_WITH_PC(s2s_CallRef, instr.pc);
      }
      // Pops the function to call.
      RefPop();
      EmitI32Const(instr.optional.index); // Signature index.
      EmitStackIndex(stack_size());
      EmitSlotOffset(slot_offset);
      EmitRefStackIndex(ref_stack_fp_offset);
      // Function arguments are popped from the stack.
      for (size_t index = sig->parameter_count(); index > 0; index--) {
        Pop(sig->GetParam(index - 1).kind(), false);
      }
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      if (v8_flags.trace_drumbrake_execution) {
        EmitSlotOffset(rets_slots.empty()
                           ? 0
                           : slots_[rets_slots[0]].slot_offset * kSlotSize);
      }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
      if (!is_tail_call) {
        eh_data_.RecordPotentialExceptionThrowingInstruction(instr.opcode,
                                                             CurrentCodePos());
      }
      // Function result is pushed to the stack.
      for (size_t index = 0; index < sig->return_count(); index++) {
        const ValueType value_type = sig->GetReturn(index);
        const ValueKind kind = value_type.kind();
        switch (kind) {
          case kI32:
          case kI64:
          case kF32:
          case kF64:
          case kS128:
          case kRef:
          case kRefNull:
            PushSlot(rets_slots[index]);
            SetSlotType(stack_top_index(), value_type);
            break;
          default:
            UNREACHABLE();
        }
      }
      // If this is a tail call, the following instructions in this block are
      // unreachable.
      if (is_tail_call) {
        SetUnreachableMode();
      }
      return RegMode::kNoReg;
    }
    case kExprDrop: {
      switch (top_stack_slot_type) {
        case kI32:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_I32Drop);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I32Drop);
              I32Pop();
              return RegMode::kNoReg;
          }
          break;
        case kI64:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_I64Drop);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I64Drop);
              I64Pop();
              return RegMode::kNoReg;
          }
          break;
        case kF32:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_F32Drop);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F32Drop);
              F32Pop();
              return RegMode::kNoReg;
          }
          break;
        case kF64:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_F64Drop);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F64Drop);
              F64Pop();
              return RegMode::kNoReg;
          }
          break;
        case kS128:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_S128Drop);
              S128Pop();
              return RegMode::kNoReg;
          }
          break;
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_RefDrop);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_RefDrop);
              RefPop();
              return RegMode::kNoReg;
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprSelect:
    case kExprSelectWithType: {
      DCHECK_GE(stack_size(), 2);
      switch (slots_[stack_[stack_size() - 2]].kind()) {
        case kI32:
          switch (mode) {
            case kR2R:
              EMIT_INSTR_HANDLER(r2r_I32Select);
              I32Pop(); // val2
              I32Pop(); // val1
              return RegMode::kI32Reg;
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_I32Select);
              I32Pop(); // val2
              I32Pop(); // val1
              I32Push(); // result
              return RegMode::kNoReg;
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_I32Select);
              I32Pop(); // condition
              I32Pop(); // val2
              I32Pop(); // val1
              return RegMode::kI32Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I32Select);
              I32Pop(); // condition
              I32Pop(); // val2
              I32Pop(); // val1
              I32Push(); // result
              return RegMode::kNoReg;
          }
          break;
        case kI64:
          switch (mode) {
            case kR2R:
              EMIT_INSTR_HANDLER(r2r_I64Select);
              I64Pop(); // val2
              I64Pop(); // val1
              return RegMode::kI64Reg;
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_I64Select);
              I64Pop(); // val2
              I64Pop(); // val1
              I64Push(); // result
              return RegMode::kNoReg;
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_I64Select);
              I32Pop(); // condition
              I64Pop(); // val2
              I64Pop(); // val1
              return RegMode::kI64Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I64Select);
              I32Pop(); // condition
              I64Pop();
              I64Pop();
              I64Push();
              return RegMode::kNoReg;
          }
          break;
        case kF32:
          switch (mode) {
            case kR2R:
              EMIT_INSTR_HANDLER(r2r_F32Select);
              F32Pop(); // val2
              F32Pop(); // val1
              return RegMode::kF32Reg;
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_F32Select);
              F32Pop(); // val2
              F32Pop(); // val1
              F32Push(); // result
              return RegMode::kNoReg;
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_F32Select);
              I32Pop(); // condition
              F32Pop(); // val2
              F32Pop(); // val1
              return RegMode::kF32Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F32Select);
              I32Pop(); // condition
              F32Pop();
              F32Pop();
              F32Push();
              return RegMode::kNoReg;
          }
          break;
        case kF64:
          switch (mode) {
            case kR2R:
              EMIT_INSTR_HANDLER(r2r_F64Select);
              F64Pop(); // val2
              F64Pop(); // val1
              return RegMode::kF64Reg;
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_F64Select);
              F64Pop(); // val2
              F64Pop(); // val1
              F64Push(); // result
              return RegMode::kNoReg;
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_F64Select);
              I32Pop(); // condition
              F64Pop(); // val2
              F64Pop(); // val1
              return RegMode::kF64Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F64Select);
              I32Pop(); // condition
              F64Pop();
              F64Pop();
              F64Push();
              return RegMode::kNoReg;
          }
          break;
        case kS128:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_S128Select);
              S128Pop();
              S128Pop();
              S128Push();
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_S128Select);
              I32Pop(); // condition
              S128Pop();
              S128Pop();
              S128Push();
              return RegMode::kNoReg;
          }
          break;
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S: {
              EMIT_INSTR_HANDLER(r2s_RefSelect);
              RefPop(); // val2
              ValueType type = RefPop(); // val1
              RefPush(type); // result
              return RegMode::kNoReg;
            }
            case kS2S: {
              EMIT_INSTR_HANDLER(s2s_RefSelect);
              I32Pop(); // condition
              RefPop();
              ValueType type = RefPop();
              RefPush(type);
              return RegMode::kNoReg;
            }
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprLocalGet: {
      switch (slots_[stack_[instr.optional.index]].kind()) {
        case kI32:
        case kI64:
        case kF32:
        case kF64:
        case kS128:
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              PushCopySlot(instr.optional.index);
              return RegMode::kNoReg;
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprLocalSet: {
      DCHECK_LE(instr.optional.index, stack_size());
      // Validation ensures that the target slot type must be the same as the
      // stack top slot type.
      const ValueType value_type =
          slots_[stack_[instr.optional.index]].value_type;
      const ValueKind kind = value_type.kind();
      DCHECK(CheckEqualKind(kind, top_stack_slot_type));
      switch (kind) {
        case kI32:
        case kI64:
        case kF32:
        case kF64:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              CopyToSlotAndPop(value_type, instr.optional.index, false, true);
              return RegMode::kNoReg;
            case kS2S:
              CopyToSlotAndPop(value_type, instr.optional.index, false, false);
              return RegMode::kNoReg;
          }
          break;
        case kS128:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              CopyToSlotAndPop(value_type, instr.optional.index, false, false);
              return RegMode::kNoReg;
          }
          break;
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              CopyToSlotAndPop(slots_[stack_.back()].value_type,
                               instr.optional.index, false, false);
              return RegMode::kNoReg;
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprLocalTee: {
      DCHECK_LE(instr.optional.index, stack_size());
      // Validation ensures that the target slot type must be the same as the
      // stack top slot type.
      const ValueType value_type =
          slots_[stack_[instr.optional.index]].value_type;
      const ValueKind kind = value_type.kind();
      DCHECK(CheckEqualKind(kind, top_stack_slot_type));
      switch (kind) {
        case kI32:
        case kI64:
        case kF32:
        case kF64:
          switch (mode) {
            case kR2R:
              CopyToSlotAndPop(value_type, instr.optional.index, true, true);
              return GetRegMode(value_type.kind());
            case kR2S:
              UNREACHABLE();
            case kS2R:
              UNREACHABLE();
            case kS2S:
              CopyToSlotAndPop(value_type, instr.optional.index, true, false);
              return RegMode::kNoReg;
          }
          break;
        case kS128:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              CopyToSlotAndPop(value_type, instr.optional.index, true, false);
              return RegMode::kNoReg;
          }
          break;
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              CopyToSlotAndPop(slots_[stack_.back()].value_type,
                               instr.optional.index, true, false);
              return RegMode::kNoReg;
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprGlobalGet: {
      switch (GetGlobalType(instr.optional.index)) {
        case kI32:
          switch (mode) {
            case kR2R:
            case kR2S:
              UNREACHABLE();
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_I32GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kI32Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I32GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              I32Push();
              return RegMode::kNoReg;
          }
          break;
        case kI64:
          switch (mode) {
            case kR2R:
            case kR2S:
              UNREACHABLE();
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_I64GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kI64Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I64GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              I64Push();
              return RegMode::kNoReg;
          }
          break;
        case kF32:
          switch (mode) {
            case kR2R:
            case kR2S:
              UNREACHABLE();
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_F32GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kF32Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F32GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              F32Push();
              return RegMode::kNoReg;
          }
          break;
        case kF64:
          switch (mode) {
            case kR2R:
            case kR2S:
              UNREACHABLE();
            case kS2R:
              EMIT_INSTR_HANDLER(s2r_F64GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kF64Reg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F64GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              F64Push();
              return RegMode::kNoReg;
          }
          break;
        case kS128:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_S128GlobalGet);
              EmitGlobalIndex(instr.optional.index);
              S128Push();
              return RegMode::kNoReg;
          }
          break;
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_RefGlobalGet);
              EmitGlobalIndex(instr.optional.index);
              RefPush(module_->globals[instr.optional.index].type);
              return RegMode::kNoReg;
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprGlobalSet: {
      switch (top_stack_slot_type) {
        case kI32:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_I32GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I32GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              I32Pop();
              return RegMode::kNoReg;
          }
          break;
        case kI64:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_I64GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_I64GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              I64Pop();
              return RegMode::kNoReg;
          }
          break;
        case kF32:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_F32GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F32GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              F32Pop();
              return RegMode::kNoReg;
          }
          break;
        case kF64:
          switch (mode) {
            case kR2R:
            case kS2R:
              UNREACHABLE();
            case kR2S:
              EMIT_INSTR_HANDLER(r2s_F64GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              return RegMode::kNoReg;
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_F64GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              F64Pop();
              return RegMode::kNoReg;
          }
          break;
        case kS128:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_S128GlobalSet);
              EmitGlobalIndex(instr.optional.index);
              S128Pop();
              return RegMode::kNoReg;
          }
          break;
        case kRef:
        case kRefNull:
          switch (mode) {
            case kR2R:
            case kR2S:
            case kS2R:
              UNREACHABLE();
            case kS2S:
              EMIT_INSTR_HANDLER(s2s_RefGlobalSet);
              EmitGlobalIndex(instr.optional.index);
              RefPop();
              return RegMode::kNoReg;
          }
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprTableGet: {
      bool is_table64 = module_->tables[instr.optional.index].is_table64();
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_TableGet, s2s_Table64Get, is_table64,
                                       instr.pc);
      EmitI32Const(instr.optional.index);
      is_table64 ? I64Pop() : I32Pop();
      RefPush(module_->tables[instr.optional.index].type);
      break;
    }
    case kExprTableSet: {
      bool is_table64 = module_->tables[instr.optional.index].is_table64();
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_TableSet, s2s_Table64Set, is_table64,
                                       instr.pc);
      EmitI32Const(instr.optional.index);
      RefPop();
      is_table64 ? I64Pop() : I32Pop();
      break;
    }
#define LOAD_CASE(name, ctype, mtype, rep, type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2r_##name, r2r_##name##_Idx64, \
                                         is_memory64_, instr.pc); \
        EmitMemoryOffset(instr.optional.offset); \
        return RegMode::k##type##Reg; \
      case kR2S: \
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_##name, r2s_##name##_Idx64, \
                                         is_memory64_, instr.pc); \
        EmitMemoryOffset(instr.optional.offset); \
        type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2r_##name, s2r_##name##_Idx64, \
                                         is_memory64_, instr.pc); \
        EmitMemoryOffset(instr.optional.offset); \
        MemIndexPop(); \
        return RegMode::k##type##Reg; \
      case kS2S: \
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                         is_memory64_, instr.pc); \
        EmitMemoryOffset(instr.optional.offset); \
        MemIndexPop(); \
        type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      LOAD_CASE(I32LoadMem8S, int32_t, int8_t, kWord8, I32);
      LOAD_CASE(I32LoadMem8U, int32_t, uint8_t, kWord8, I32);
      LOAD_CASE(I32LoadMem16S, int32_t, int16_t, kWord16, I32);
      LOAD_CASE(I32LoadMem16U, int32_t, uint16_t, kWord16, I32);
      LOAD_CASE(I64LoadMem8S, int64_t, int8_t, kWord8, I64);
      LOAD_CASE(I64LoadMem8U, int64_t, uint8_t, kWord16, I64);
      LOAD_CASE(I64LoadMem16S, int64_t, int16_t, kWord16, I64);
      LOAD_CASE(I64LoadMem16U, int64_t, uint16_t, kWord16, I64);
      LOAD_CASE(I64LoadMem32S, int64_t, int32_t, kWord32, I64);
      LOAD_CASE(I64LoadMem32U, int64_t, uint32_t, kWord32, I64);
      LOAD_CASE(I32LoadMem, int32_t, int32_t, kWord32, I32);
      LOAD_CASE(I64LoadMem, int64_t, int64_t, kWord64, I64);
      LOAD_CASE(F32LoadMem, Float32, uint32_t, kFloat32, F32);
      LOAD_CASE(F64LoadMem, Float64, uint64_t, kFloat64, F64);
#undef LOAD_CASE
#define STORE_CASE(name, ctype, mtype, rep, type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
      case kS2R: \
        UNREACHABLE(); \
        break; \
      case kR2S: \
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_##name, r2s_##name##_Idx64, \
                                         is_memory64_, instr.pc); \
        EmitMemoryOffset(instr.optional.offset); \
        MemIndexPop(); \
        return RegMode::kNoReg; \
      case kS2S: \
        EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                         is_memory64_, instr.pc); \
        type##Pop(); \
        EmitMemoryOffset(instr.optional.offset); \
        MemIndexPop(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      STORE_CASE(I32StoreMem8, int32_t, int8_t, kWord8, I32);
      STORE_CASE(I32StoreMem16, int32_t, int16_t, kWord16, I32);
      STORE_CASE(I64StoreMem8, int64_t, int8_t, kWord8, I64);
      STORE_CASE(I64StoreMem16, int64_t, int16_t, kWord16, I64);
      STORE_CASE(I64StoreMem32, int64_t, int32_t, kWord32, I64);
      STORE_CASE(I32StoreMem, int32_t, int32_t, kWord32, I32);
      STORE_CASE(I64StoreMem, int64_t, int64_t, kWord64, I64);
      STORE_CASE(F32StoreMem, Float32, uint32_t, kFloat32, F32);
      STORE_CASE(F64StoreMem, Float64, uint64_t, kFloat64, F64);
#undef STORE_CASE
    case kExprMemoryGrow: {
      EMIT_MEM64_INSTR_HANDLER(s2s_MemoryGrow, s2s_Memory64Grow, is_memory64_);
      MemIndexPop();
      MemIndexPush();
      break;
    }
    case kExprMemorySize:
      EMIT_MEM64_INSTR_HANDLER(s2s_MemorySize, s2s_Memory64Size, is_memory64_);
      MemIndexPush();
      break;
    case kExprI32Const: {
      switch (mode) {
        case kR2R:
        case kR2S:
        case kS2R:
          UNREACHABLE();
        case kS2S:
          PushConstSlot<int32_t>(instr.optional.i32);
          return RegMode::kNoReg;
      }
      break;
    }
    case kExprI64Const: {
      switch (mode) {
        case kR2R:
        case kR2S:
        case kS2R:
          UNREACHABLE();
        case kS2S:
          PushConstSlot<int64_t>(instr.optional.i64);
          return RegMode::kNoReg;
      }
      break;
    }
    case kExprF32Const: {
      switch (mode) {
        case kR2R:
        case kR2S:
        case kS2R:
          UNREACHABLE();
        case kS2S:
          PushConstSlot<float>(instr.optional.f32);
          return RegMode::kNoReg;
      }
      break;
    }
    case kExprF64Const: {
      switch (mode) {
        case kR2R:
        case kR2S:
        case kS2R:
          UNREACHABLE();
        case kS2S:
          PushConstSlot<double>(instr.optional.f64);
          return RegMode::kNoReg;
      }
      break;
    }
#define EXECUTE_BINOP(name, ctype, reg, op, type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER(r2r_##name); \
        type##Pop(); \
        return RegMode::kI32Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER(r2s_##name); \
        type##Pop(); \
        I32Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER(s2r_##name); \
        type##Pop(); \
        type##Pop(); \
        return RegMode::kI32Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER(s2s_##name); \
        type##Pop(); \
        type##Pop(); \
        I32Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_COMPARISON_BINOP(EXECUTE_BINOP)
#undef EXECUTE_BINOP
#define EXECUTE_BINOP(name, ctype, reg, op, type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER(r2r_##name); \
        type##Pop(); \
        return RegMode::k##type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER(r2s_##name); \
        type##Pop(); \
        type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER(s2r_##name); \
        type##Pop(); \
        type##Pop(); \
        return RegMode::k##type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER(s2s_##name); \
        type##Pop(); \
        type##Pop(); \
        type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_ARITHMETIC_BINOP(EXECUTE_BINOP)
      FOREACH_MORE_BINOP(EXECUTE_BINOP)
#undef EXECUTE_BINOP
#define EXECUTE_BINOP(name, ctype, reg, op, type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER_WITH_PC(r2r_##name, instr.pc); \
        type##Pop(); \
        return RegMode::k##type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER_WITH_PC(r2s_##name, instr.pc); \
        type##Pop(); \
        type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER_WITH_PC(s2r_##name, instr.pc); \
        type##Pop(); \
        type##Pop(); \
        return RegMode::k##type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER_WITH_PC(s2s_##name, instr.pc); \
        type##Pop(); \
        type##Pop(); \
        type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_TRAPPING_BINOP(EXECUTE_BINOP)
#undef EXECUTE_BINOP
#define EXECUTE_UNOP(name, ctype, reg, op, type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER(r2r_##name); \
        return RegMode::k##type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER(r2s_##name); \
        type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER(s2r_##name); \
        type##Pop(); \
        return RegMode::k##type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER(s2s_##name); \
        type##Pop(); \
        type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_SIMPLE_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, from_reg, to_ctype, to_type, \
                     to_reg) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER(r2r_##name); \
        return RegMode::k##to_type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER(r2s_##name); \
        to_type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER(s2r_##name); \
        from_type##Pop(); \
        return RegMode::k##to_type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER(s2s_##name); \
        from_type##Pop(); \
        to_type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_ADDITIONAL_CONVERT_UNOP(EXECUTE_UNOP)
      FOREACH_OTHER_CONVERT_UNOP(EXECUTE_UNOP)
      FOREACH_REINTERPRET_UNOP(EXECUTE_UNOP)
      FOREACH_TRUNCSAT_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, from_reg, to_ctype, to_type, \
                     to_reg) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER_WITH_PC(r2r_##name, instr.pc); \
        return RegMode::k##to_type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER_WITH_PC(r2s_##name, instr.pc); \
        to_type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER_WITH_PC(s2r_##name, instr.pc); \
        from_type##Pop(); \
        return RegMode::k##to_type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER_WITH_PC(s2s_##name, instr.pc); \
        from_type##Pop(); \
        to_type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_I64_CONVERT_FROM_FLOAT_UNOP(EXECUTE_UNOP)
      FOREACH_I32_CONVERT_FROM_FLOAT_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, to_ctype, to_type, op) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER(r2r_##name); \
        return RegMode::k##to_type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER(r2s_##name); \
        to_type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER(s2r_##name); \
        from_type##Pop(); \
        return RegMode::k##to_type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER(s2s_##name); \
        from_type##Pop(); \
        to_type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_BITS_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
#define EXECUTE_UNOP(name, from_ctype, from_type, to_ctype, to_type) \
  case kExpr##name: { \
    switch (mode) { \
      case kR2R: \
        EMIT_INSTR_HANDLER(r2r_##name); \
        return RegMode::k##to_type##Reg; \
      case kR2S: \
        EMIT_INSTR_HANDLER(r2s_##name); \
        to_type##Push(); \
        return RegMode::kNoReg; \
      case kS2R: \
        EMIT_INSTR_HANDLER(s2r_##name); \
        from_type##Pop(); \
        return RegMode::k##to_type##Reg; \
      case kS2S: \
        EMIT_INSTR_HANDLER(s2s_##name); \
        from_type##Pop(); \
        to_type##Push(); \
        return RegMode::kNoReg; \
    } \
    break; \
  }
      FOREACH_EXTENSION_UNOP(EXECUTE_UNOP)
#undef EXECUTE_UNOP
    case kExprRefNull: {
      EMIT_INSTR_HANDLER(s2s_RefNull);
      ValueType value_type = ValueType::RefNull(
          HeapType::FromBits(instr.optional.ref_type_bit_field));
      EmitRefValueType(value_type.raw_bit_field());
      RefPush(value_type);
      break;
    }
    case kExprRefIsNull:
      EMIT_INSTR_HANDLER(s2s_RefIsNull);
      RefPop();
      I32Push();
      break;
    case kExprRefFunc: {
      EMIT_INSTR_HANDLER(s2s_RefFunc);
      EmitI32Const(instr.optional.index);
      ModuleTypeIndex sig_index =
          module_->functions[instr.optional.index].sig_index;
      ValueType value_type = ValueType::Ref(module_->heap_type(sig_index));
      RefPush(value_type);
      break;
    }
    case kExprRefEq:
      EMIT_INSTR_HANDLER(s2s_RefEq);
      RefPop();
      RefPop();
      I32Push();
      break;
    case kExprRefAsNonNull: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_RefAsNonNull, instr.pc);
      ValueType value_type = RefPop();
      RefPush(value_type);
      break;
    }
    case kExprStructNew: {
      EMIT_INSTR_HANDLER(s2s_StructNew);
      EmitI32Const(instr.optional.index);
      // Pops args
      const StructType* struct_type = module_->struct_type(
          ModuleTypeIndex({instr.optional.gc_field_immediate.struct_index}));
      for (uint32_t i = struct_type->field_count(); i > 0;) {
        i--;
        ValueKind kind = struct_type->field(i).kind();
        Pop(kind);
      }
      ModuleTypeIndex type_index{instr.optional.index};
      RefPush(ValueType::Ref(module_->heap_type(type_index)));
      break;
    }
    case kExprStructNewDefault: {
      EMIT_INSTR_HANDLER(s2s_StructNewDefault);
      EmitI32Const(instr.optional.index);
      ModuleTypeIndex type_index{instr.optional.index};
      RefPush(ValueType::Ref(module_->heap_type(type_index)));
      break;
    }
    case kExprStructGet:
    case kExprStructGetS:
    case kExprStructGetU: {
      bool is_signed = (instr.opcode == wasm::kExprStructGetS);
      const StructType* struct_type = module_->struct_type(
          ModuleTypeIndex({instr.optional.gc_field_immediate.struct_index}));
      uint32_t field_index = instr.optional.gc_field_immediate.field_index;
      ValueType value_type = struct_type->field(field_index);
      ValueKind kind = value_type.kind();
      int offset = StructFieldOffset(struct_type, field_index);
      switch (kind) {
        case kI8:
          if (is_signed) {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I8SStructGet, instr.pc);
          } else {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I8UStructGet, instr.pc);
          }
          RefPop();
          EmitStructFieldOffset(offset);
          I32Push();
          break;
        case kI16:
          if (is_signed) {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I16SStructGet, instr.pc);
          } else {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I16UStructGet, instr.pc);
          }
          RefPop();
          EmitStructFieldOffset(offset);
          I32Push();
          break;
        case kI32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I32StructGet, instr.pc);
          RefPop();
          EmitStructFieldOffset(offset);
          I32Push();
          break;
        case kI64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I64StructGet, instr.pc);
          RefPop();
          EmitStructFieldOffset(offset);
          I64Push();
          break;
        case kF32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F32StructGet, instr.pc);
          RefPop();
          EmitStructFieldOffset(offset);
          F32Push();
          break;
        case kF64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F64StructGet, instr.pc);
          RefPop();
          EmitStructFieldOffset(offset);
          F64Push();
          break;
        case kS128:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_S128StructGet, instr.pc);
          RefPop();
          EmitStructFieldOffset(offset);
          S128Push();
          break;
        case kRef:
        case kRefNull:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefStructGet, instr.pc);
          RefPop();
          EmitStructFieldOffset(offset);
          RefPush(value_type);
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprStructSet: {
      const StructType* struct_type = module_->struct_type(
          ModuleTypeIndex({instr.optional.gc_field_immediate.struct_index}));
      uint32_t field_index = instr.optional.gc_field_immediate.field_index;
      int offset = StructFieldOffset(struct_type, field_index);
      ValueKind kind = struct_type->field(field_index).kind();
      switch (kind) {
        case kI8:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I8StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          I32Pop();
          break;
        case kI16:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I16StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          I32Pop();
          break;
        case kI32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I32StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          I32Pop();
          break;
        case kI64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I64StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          I64Pop();
          break;
        case kF32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F32StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          F32Pop();
          break;
        case kF64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F64StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          F64Pop();
          break;
        case kS128:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_S128StructSet, instr.pc);
          EmitStructFieldOffset(offset);
          S128Pop();
          break;
        case kRef:
        case kRefNull:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefStructSet, instr.pc);
          EmitStructFieldOffset(offset);
          RefPop();
          break;
        default:
          UNREACHABLE();
      }
      RefPop(); // The object to set the field to.
      break;
    }
    case kExprArrayNew: {
      uint32_t array_index = instr.optional.gc_array_new_fixed.array_index;
      const ArrayType* array_type =
          module_->array_type(ModuleTypeIndex({array_index}));
      ValueType element_type = array_type->element_type();
      ValueKind kind = element_type.kind();
      // Pop a single value to be used to initialize the array.
      switch (kind) {
        case kI8:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I8ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop(); // Array length.
          I32Pop(); // Initialization value.
          break;
        case kI16:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I16ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          I32Pop();
          break;
        case kI32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I32ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          I32Pop();
          break;
        case kI64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I64ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          I64Pop();
          break;
        case kF32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F32ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          F32Pop();
          break;
        case kF64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F64ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          F64Pop();
          break;
        case kS128:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_S128ArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          S128Pop();
          break;
        case kRef:
        case kRefNull:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefArrayNew, instr.pc);
          EmitI32Const(array_index);
          I32Pop();
          RefPop();
          break;
        default:
          UNREACHABLE();
      }
      // Push the new array.
      RefPush(
          ValueType::Ref(module_->heap_type(ModuleTypeIndex({array_index}))));
      break;
    }
    case kExprArrayNewFixed: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayNewFixed, instr.pc);
      uint32_t length = instr.optional.gc_array_new_fixed.length;
      uint32_t array_index = instr.optional.gc_array_new_fixed.array_index;
      EmitI32Const(array_index);
      EmitI32Const(length);
      const ArrayType* array_type =
          module_->array_type(ModuleTypeIndex({array_index}));
      ValueType element_type = array_type->element_type();
      ValueKind kind = element_type.kind();
      // Pop values to initialize the array.
      for (uint32_t i = 0; i < length; i++) {
        switch (kind) {
          case kI8:
          case kI16:
          case kI32:
            I32Pop();
            break;
          case kI64:
            I64Pop();
            break;
          case kF32:
            F32Pop();
            break;
          case kF64:
            F64Pop();
            break;
          case kS128:
            S128Pop();
            break;
          case kRef:
          case kRefNull:
            RefPop();
            break;
          default:
            UNREACHABLE();
        }
      }
      // Push the new array.
      RefPush(
          ValueType::Ref(module_->heap_type(ModuleTypeIndex({array_index}))));
      break;
    }
    case kExprArrayNewDefault: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayNewDefault, instr.pc);
      EmitI32Const(instr.optional.index);
      I32Pop();
      // Push the new array.
      ModuleTypeIndex array_index{instr.optional.index};
      RefPush(
          ValueType::Ref(module_->heap_type(ModuleTypeIndex({array_index}))));
      break;
    }
    case kExprArrayNewData: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayNewData, instr.pc);
      uint32_t array_index =
          instr.optional.gc_array_new_or_init_data.array_index;
      EmitI32Const(array_index);
      uint32_t data_index = instr.optional.gc_array_new_or_init_data.data_index;
      EmitI32Const(data_index);
      I32Pop();
      I32Pop();
      // Push the new array.
      RefPush(
          ValueType::Ref(module_->heap_type(ModuleTypeIndex({array_index}))));
      break;
    }
    case kExprArrayNewElem: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayNewElem, instr.pc);
      uint32_t array_index =
          instr.optional.gc_array_new_or_init_data.array_index;
      EmitI32Const(array_index);
      uint32_t data_index = instr.optional.gc_array_new_or_init_data.data_index;
      EmitI32Const(data_index);
      I32Pop();
      I32Pop();
      // Push the new array.
      RefPush(
          ValueType::Ref(module_->heap_type(ModuleTypeIndex({array_index}))));
      break;
    }
    case kExprArrayInitData: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayInitData, instr.pc);
      uint32_t array_index =
          instr.optional.gc_array_new_or_init_data.array_index;
      EmitI32Const(array_index);
      uint32_t data_index = instr.optional.gc_array_new_or_init_data.data_index;
      EmitI32Const(data_index);
      I32Pop(); // size
      I32Pop(); // src offset
      I32Pop(); // dest offset
      RefPop(); // array to initialize
      break;
    }
    case kExprArrayInitElem: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayInitElem, instr.pc);
      uint32_t array_index =
          instr.optional.gc_array_new_or_init_data.array_index;
      EmitI32Const(array_index);
      uint32_t data_index = instr.optional.gc_array_new_or_init_data.data_index;
      EmitI32Const(data_index);
      I32Pop(); // size
      I32Pop(); // src offset
      I32Pop(); // dest offset
      RefPop(); // array to initialize
      break;
    }
    case kExprArrayLen: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayLen, instr.pc);
      RefPop();
      I32Push();
      break;
    }
    case kExprArrayCopy: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_ArrayCopy, instr.pc);
      EmitI32Const(instr.optional.gc_array_copy.dest_array_index);
      EmitI32Const(instr.optional.gc_array_copy.src_array_index);
      I32Pop(); // size
      I32Pop(); // src offset
      RefPop(); // src array
      I32Pop(); // dest offset
      RefPop(); // dest array
      break;
    }
    case kExprArrayGet:
    case kExprArrayGetS:
    case kExprArrayGetU: {
      bool is_signed = (instr.opcode == wasm::kExprArrayGetS);
      const ArrayType* array_type =
          module_->array_type(ModuleTypeIndex({instr.optional.index}));
      ValueType element_type = array_type->element_type();
      ValueKind kind = element_type.kind();
      switch (kind) {
        case kI8:
          if (is_signed) {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I8SArrayGet, instr.pc);
          } else {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I8UArrayGet, instr.pc);
          }
          I32Pop();
          RefPop();
          I32Push();
          break;
        case kI16:
          if (is_signed) {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I16SArrayGet, instr.pc);
          } else {
            EMIT_INSTR_HANDLER_WITH_PC(s2s_I16UArrayGet, instr.pc);
          }
          I32Pop();
          RefPop();
          I32Push();
          break;
        case kI32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I32ArrayGet, instr.pc);
          I32Pop();
          RefPop();
          I32Push();
          break;
        case kI64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I64ArrayGet, instr.pc);
          I32Pop();
          RefPop();
          I64Push();
          break;
        case kF32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F32ArrayGet, instr.pc);
          I32Pop();
          RefPop();
          F32Push();
          break;
        case kF64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F64ArrayGet, instr.pc);
          I32Pop();
          RefPop();
          F64Push();
          break;
        case kS128:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_S128ArrayGet, instr.pc);
          I32Pop();
          RefPop();
          S128Push();
          break;
        case kRef:
        case kRefNull:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefArrayGet, instr.pc);
          I32Pop();
          RefPop();
          RefPush(element_type);
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprArraySet: {
      const ArrayType* array_type =
          module_->array_type(ModuleTypeIndex({instr.optional.index}));
      ValueKind kind = array_type->element_type().kind();
      switch (kind) {
        case kI8:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I8ArraySet, instr.pc);
          I32Pop();
          I32Pop();
          RefPop();
          break;
        case kI16:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I16ArraySet, instr.pc);
          I32Pop();
          I32Pop();
          RefPop();
          break;
        case kI32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I32ArraySet, instr.pc);
          I32Pop();
          I32Pop();
          RefPop();
          break;
        case kI64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I64ArraySet, instr.pc);
          I64Pop();
          I32Pop();
          RefPop();
          break;
        case kF32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F32ArraySet, instr.pc);
          F32Pop();
          I32Pop();
          RefPop();
          break;
        case kF64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F64ArraySet, instr.pc);
          F64Pop();
          I32Pop();
          RefPop();
          break;
        case kS128:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_S128ArraySet, instr.pc);
          S128Pop();
          I32Pop();
          RefPop();
          break;
        case kRef:
        case kRefNull:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefArraySet, instr.pc);
          RefPop();
          I32Pop();
          RefPop();
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprArrayFill: {
      const ArrayType* array_type =
          module_->array_type(ModuleTypeIndex({instr.optional.index}));
      ValueKind kind = array_type->element_type().kind();
      switch (kind) {
        case kI8:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I8ArrayFill, instr.pc);
          I32Pop(); // The size of the filled slice.
          I32Pop(); // The value with which to fill the array.
          I32Pop(); // The offset at which to begin filling.
          RefPop(); // The array to fill.
          break;
        case kI16:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I16ArrayFill, instr.pc);
          I32Pop();
          I32Pop();
          I32Pop();
          RefPop();
          break;
        case kI32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I32ArrayFill, instr.pc);
          I32Pop();
          I32Pop();
          I32Pop();
          RefPop();
          break;
        case kI64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_I64ArrayFill, instr.pc);
          I32Pop();
          I64Pop();
          I32Pop();
          RefPop();
          break;
        case kF32:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F32ArrayFill, instr.pc);
          I32Pop();
          F32Pop();
          I32Pop();
          RefPop();
          break;
        case kF64:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_F64ArrayFill, instr.pc);
          I32Pop();
          F64Pop();
          I32Pop();
          RefPop();
          break;
        case kS128:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_S128ArrayFill, instr.pc);
          I32Pop();
          S128Pop();
          I32Pop();
          RefPop();
          break;
        case kRef:
        case kRefNull:
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefArrayFill, instr.pc);
          I32Pop();
          RefPop();
          I32Pop();
          RefPop();
          break;
        default:
          UNREACHABLE();
      }
      break;
    }
    case kExprRefI31: {
      EMIT_INSTR_HANDLER(s2s_RefI31);
      I32Pop();
      RefPush(ValueType::Ref(kWasmRefI31));
      break;
    }
    case kExprI31GetS: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_I31GetS, instr.pc);
      RefPop();
      I32Push();
      break;
    }
    case kExprI31GetU: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_I31GetU, instr.pc);
      RefPop();
      I32Push();
      break;
    }
    case kExprRefCast:
    case kExprRefCastNull: {
      bool null_succeeds = (instr.opcode == kExprRefCastNull);
      HeapType target_type = HeapType::FromBits(
          instr.optional.gc_heap_type_immediate.heap_type_bit_field);
      ValueType resulting_value_type = ValueType::RefMaybeNull(
          target_type, null_succeeds ? kNullable : kNonNullable);
      ValueType obj_type = slots_[stack_.back()].value_type;
      DCHECK(obj_type.is_object_reference());
      // This logic ensures that code generation can assume that functions
      // can only be cast to function types, and data objects to data types.
      if (V8_UNLIKELY(TypeCheckAlwaysSucceeds(obj_type, target_type))) {
        if (obj_type.is_nullable() && !null_succeeds) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_AssertNotNullTypecheck, instr.pc);
          ValueType value_type = RefPop();
          EmitRefValueType(value_type.raw_bit_field());
          RefPush(resulting_value_type);
        } else {
          // Just forward the ref object.
        }
      } else if (V8_UNLIKELY(TypeCheckAlwaysFails(obj_type, target_type,
                                                  null_succeeds))) {
        // Unrelated types. The only way this will not trap is if the object
        // is null.
        if (obj_type.is_nullable() && null_succeeds) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_AssertNullTypecheck, instr.pc);
          ValueType value_type = RefPop();
          EmitRefValueType(value_type.raw_bit_field());
          RefPush(resulting_value_type);
        } else {
          // In this case we just trap.
          EMIT_INSTR_HANDLER_WITH_PC(s2s_TrapIllegalCast, instr.pc);
        }
      } else {
        if (instr.opcode == kExprRefCast) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefCast, instr.pc);
        } else {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_RefCastNull, instr.pc);
        }
        EmitI32Const(instr.optional.gc_heap_type_immediate.heap_type_bit_field);
        ValueType value_type = RefPop();
        EmitRefValueType(value_type.raw_bit_field());
        RefPush(resulting_value_type);
      }
      break;
    }
    case kExprRefTest:
    case kExprRefTestNull: {
      bool null_succeeds = (instr.opcode == kExprRefTestNull);
      HeapType target_type = HeapType::FromBits(
          instr.optional.gc_heap_type_immediate.heap_type_bit_field);
      ValueType obj_type = slots_[stack_.back()].value_type;
      DCHECK(obj_type.is_object_reference());
      // This logic ensures that code generation can assume that functions
      // can only be cast to function types, and data objects to data types.
      if (V8_UNLIKELY(TypeCheckAlwaysSucceeds(obj_type, target_type))) {
        // Type checking can still fail for null.
        if (obj_type.is_nullable() && !null_succeeds) {
          EMIT_INSTR_HANDLER(s2s_RefIsNonNull);
          RefPop();
          I32Push(); // bool
        } else {
          EMIT_INSTR_HANDLER(s2s_RefTestSucceeds);
          RefPop();
          I32Push(); // bool=true
        }
      } else if (V8_UNLIKELY(TypeCheckAlwaysFails(obj_type, target_type,
                                                  null_succeeds))) {
        EMIT_INSTR_HANDLER(s2s_RefTestFails);
        RefPop();
        I32Push(); // bool=false
      } else {
        if (instr.opcode == kExprRefTest) {
          EMIT_INSTR_HANDLER(s2s_RefTest);
        } else {
          EMIT_INSTR_HANDLER(s2s_RefTestNull);
        }
        EmitI32Const(instr.optional.gc_heap_type_immediate.heap_type_bit_field);
        ValueType value_type = RefPop();
        EmitRefValueType(value_type.raw_bit_field());
        I32Push(); // bool
      }
      break;
    }
    case kExprAnyConvertExtern: {
      EMIT_INSTR_HANDLER_WITH_PC(s2s_AnyConvertExtern, instr.pc);
      ValueType extern_val = RefPop();
      ValueType intern_type = ValueType::RefMaybeNull(
          kWasmAnyRef, Nullability(extern_val.is_nullable()));
      RefPush(intern_type);
      break;
    }
    case kExprExternConvertAny: {
      EMIT_INSTR_HANDLER(s2s_ExternConvertAny);
      ValueType value_type = RefPop();
      ValueType extern_type = ValueType::RefMaybeNull(
          kWasmExternRef, Nullability(value_type.is_nullable()));
      RefPush(extern_type);
      break;
    }
    case kExprMemoryInit:
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_MemoryInit, s2s_Memory64Init,
                                       is_memory64_, instr.pc);
      EmitI32Const(instr.optional.index);
      I32Pop();
      I32Pop();
      MemIndexPop();
      break;
    case kExprDataDrop:
      EMIT_INSTR_HANDLER(s2s_DataDrop);
      EmitI32Const(instr.optional.index);
      break;
    case kExprMemoryCopy:
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_MemoryCopy, s2s_Memory64Copy,
                                       is_memory64_, instr.pc);
      MemIndexPop();
      MemIndexPop();
      MemIndexPop();
      break;
    case kExprMemoryFill:
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_MemoryFill, s2s_Memory64Fill,
                                       is_memory64_, instr.pc);
      MemIndexPop();
      I32Pop();
      MemIndexPop();
      break;
    case kExprTableInit: {
      bool is_table64 = module_->tables[instr.optional.index].is_table64();
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_TableInit, s2s_Table64Init,
                                       is_table64, instr.pc);
      EmitI32Const(instr.optional.table_init.table_index);
      EmitI32Const(instr.optional.table_init.element_segment_index);
      I32Pop();
      I32Pop();
      is_table64 ? I64Pop() : I32Pop();
    } break;
    case kExprElemDrop:
      EMIT_INSTR_HANDLER(s2s_ElemDrop);
      EmitI32Const(instr.optional.index);
      break;
    case kExprTableCopy: {
      bool is_src_table64 =
          module_->tables[instr.optional.table_copy.src_table_index]
              .is_table64();
      bool is_dst_table64 =
          module_->tables[instr.optional.table_copy.dst_table_index]
              .is_table64();
      if (is_src_table64) {
        if (is_dst_table64) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_Table64Copy_64_64_64, instr.pc);
        } else {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_Table64Copy_32_64_32, instr.pc);
        }
      } else {
        if (is_dst_table64) {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_Table64Copy_64_32_32, instr.pc);
        } else {
          EMIT_INSTR_HANDLER_WITH_PC(s2s_TableCopy, instr.pc);
        }
      }
      EmitI32Const(instr.optional.table_copy.dst_table_index);
      EmitI32Const(instr.optional.table_copy.src_table_index);
      is_dst_table64&& is_src_table64 ? I64Pop() : I32Pop();
      is_src_table64 ? I64Pop() : I32Pop();
      is_dst_table64 ? I64Pop() : I32Pop();
    } break;
    case kExprTableGrow: {
      bool is_table64 = module_->tables[instr.optional.index].is_table64();
      if (is_table64) {
        EMIT_INSTR_HANDLER(s2s_Table64Grow);
        EmitI32Const(instr.optional.index);
        I64Pop();
        RefPop();
        I64Push();
      } else {
        EMIT_INSTR_HANDLER(s2s_TableGrow);
        EmitI32Const(instr.optional.index);
        I32Pop();
        RefPop();
        I32Push();
      }
    } break;
    case kExprTableSize: {
      bool is_table64 = module_->tables[instr.optional.index].is_table64();
      if (is_table64) {
        EMIT_INSTR_HANDLER(s2s_Table64Size);
        EmitI32Const(instr.optional.index);
        I64Push();
      } else {
        EMIT_INSTR_HANDLER(s2s_TableSize);
        EmitI32Const(instr.optional.index);
        I32Push();
      }
    } break;
    case kExprTableFill: {
      bool is_table64 = module_->tables[instr.optional.index].is_table64();
      if (is_table64) {
        EMIT_INSTR_HANDLER_WITH_PC(s2s_Table64Fill, instr.pc);
        EmitI32Const(instr.optional.index);
        I64Pop();
        RefPop();
        I64Pop();
      } else {
        EMIT_INSTR_HANDLER_WITH_PC(s2s_TableFill, instr.pc);
        EmitI32Const(instr.optional.index);
        I32Pop();
        RefPop();
        I32Pop();
      }
    } break;
    case kExprAtomicNotify:
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_AtomicNotify, s2s_AtomicNotify_Idx64,
                                       is_memory64_, instr.pc);
      I32Pop(); // val
      EmitMemoryOffset(instr.optional.offset);
      MemIndexPop(); // memory index
      I32Push();
      break;
    case kExprI32AtomicWait:
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(
          s2s_I32AtomicWait, s2s_I32AtomicWait_Idx64, is_memory64_, instr.pc);
      I64Pop(); // timeout
      I32Pop(); // val
      EmitMemoryOffset(instr.optional.offset);
      MemIndexPop(); // memory index
      I32Push();
      break;
    case kExprI64AtomicWait:
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(
          s2s_I64AtomicWait, s2s_I64AtomicWait_Idx64, is_memory64_, instr.pc);
      I64Pop(); // timeout
      I64Pop(); // val
      EmitMemoryOffset(instr.optional.offset);
      MemIndexPop(); // memory index
      I32Push();
      break;
    case kExprAtomicFence:
      EMIT_INSTR_HANDLER(s2s_AtomicFence);
      break;
#define ATOMIC_BINOP(name, Type, ctype, type, op_ctype, op_type, operation) \
  case kExpr##name: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                     is_memory64_, instr.pc); \
    op_type##Pop(); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    op_type##Push(); \
    return RegMode::kNoReg; \
  }
      FOREACH_ATOMIC_BINOP(ATOMIC_BINOP)
#undef ATOMIC_BINOP
#define ATOMIC_COMPARE_EXCHANGE_OP(name, Type, ctype, type, op_ctype, op_type) \
  case kExpr##name: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                     is_memory64_, instr.pc); \
    op_type##Pop(); \
    op_type##Pop(); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    op_type##Push(); \
    return RegMode::kNoReg; \
  }
      FOREACH_ATOMIC_COMPARE_EXCHANGE_OP(ATOMIC_COMPARE_EXCHANGE_OP)
#undef ATOMIC_COMPARE_EXCHANGE_OP
#define ATOMIC_LOAD_OP(name, Type, ctype, type, op_ctype, op_type) \
  case kExpr##name: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                     is_memory64_, instr.pc); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    op_type##Push(); \
    return RegMode::kNoReg; \
  }
      FOREACH_ATOMIC_LOAD_OP(ATOMIC_LOAD_OP)
#undef ATOMIC_LOAD_OP
#define ATOMIC_STORE_OP(name, Type, ctype, type, op_ctype, op_type) \
  case kExpr##name: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                     is_memory64_, instr.pc); \
    op_type##Pop(); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    return RegMode::kNoReg; \
  }
      FOREACH_ATOMIC_STORE_OP(ATOMIC_STORE_OP)
#undef ATOMIC_STORE_OP
#define SPLAT_CASE(format, stype, valType, op_type, num) \
  case kExpr##format##Splat: { \
    EMIT_INSTR_HANDLER(s2s_Simd##format##Splat); \
    op_type##Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      SPLAT_CASE(F64x2, float64x2, double, F64, 2)
      SPLAT_CASE(F32x4, float32x4, float, F32, 4)
      SPLAT_CASE(I64x2, int64x2, int64_t, I64, 2)
      SPLAT_CASE(I32x4, int32x4, int32_t, I32, 4)
      SPLAT_CASE(I16x8, int16x8, int32_t, I32, 8)
      SPLAT_CASE(I8x16, int8x16, int32_t, I32, 16)
#undef SPLAT_CASE
#define EXTRACT_LANE_CASE(format, stype, op_type, name) \
  case kExpr##format##ExtractLane: { \
    EMIT_INSTR_HANDLER(s2s_Simd##format##ExtractLane); \
    /* emit 8 bits ? */ \
    EmitI16Const(instr.optional.simd_lane); \
    S128Pop(); \
    op_type##Push(); \
    return RegMode::kNoReg; \
  }
      EXTRACT_LANE_CASE(F64x2, float64x2, F64, f64x2)
      EXTRACT_LANE_CASE(F32x4, float32x4, F32, f32x4)
      EXTRACT_LANE_CASE(I64x2, int64x2, I64, i64x2)
      EXTRACT_LANE_CASE(I32x4, int32x4, I32, i32x4)
#undef EXTRACT_LANE_CASE
#define EXTRACT_LANE_EXTEND_CASE(format, stype, name, sign, extended_type) \
  case kExpr##format##ExtractLane##sign: { \
    EMIT_INSTR_HANDLER(s2s_Simd##format##ExtractLane##sign); \
    /* emit 8 bits ? */ \
    EmitI16Const(instr.optional.simd_lane); \
    S128Pop(); \
    I32Push(); \
    return RegMode::kNoReg; \
  }
      EXTRACT_LANE_EXTEND_CASE(I16x8, int16x8, i16x8, S, int32_t)
      EXTRACT_LANE_EXTEND_CASE(I16x8, int16x8, i16x8, U, uint32_t)
      EXTRACT_LANE_EXTEND_CASE(I8x16, int8x16, i8x16, S, int32_t)
      EXTRACT_LANE_EXTEND_CASE(I8x16, int8x16, i8x16, U, uint32_t)
#undef EXTRACT_LANE_EXTEND_CASE
#define BINOP_CASE(op, name, stype, count, expr) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      BINOP_CASE(F64x2Add, f64x2, float64x2, 2, a + b)
      BINOP_CASE(F64x2Sub, f64x2, float64x2, 2, a - b)
      BINOP_CASE(F64x2Mul, f64x2, float64x2, 2, a * b)
      BINOP_CASE(F64x2Div, f64x2, float64x2, 2, base::Divide(a, b))
      BINOP_CASE(F64x2Min, f64x2, float64x2, 2, JSMin(a, b))
      BINOP_CASE(F64x2Max, f64x2, float64x2, 2, JSMax(a, b))
      BINOP_CASE(F64x2Pmin, f64x2, float64x2, 2, std::min(a, b))
      BINOP_CASE(F64x2Pmax, f64x2, float64x2, 2, std::max(a, b))
      BINOP_CASE(F32x4RelaxedMin, f32x4, float32x4, 4, std::min(a, b))
      BINOP_CASE(F32x4RelaxedMax, f32x4, float32x4, 4, std::max(a, b))
      BINOP_CASE(F64x2RelaxedMin, f64x2, float64x2, 2, std::min(a, b))
      BINOP_CASE(F64x2RelaxedMax, f64x2, float64x2, 2, std::max(a, b))
      BINOP_CASE(F32x4Add, f32x4, float32x4, 4, a + b)
      BINOP_CASE(F32x4Sub, f32x4, float32x4, 4, a - b)
      BINOP_CASE(F32x4Mul, f32x4, float32x4, 4, a * b)
      BINOP_CASE(F32x4Div, f32x4, float32x4, 4, a / b)
      BINOP_CASE(F32x4Min, f32x4, float32x4, 4, JSMin(a, b))
      BINOP_CASE(F32x4Max, f32x4, float32x4, 4, JSMax(a, b))
      BINOP_CASE(F32x4Pmin, f32x4, float32x4, 4, std::min(a, b))
      BINOP_CASE(F32x4Pmax, f32x4, float32x4, 4, std::max(a, b))
      BINOP_CASE(I64x2Add, i64x2, int64x2, 2, base::AddWithWraparound(a, b))
      BINOP_CASE(I64x2Sub, i64x2, int64x2, 2, base::SubWithWraparound(a, b))
      BINOP_CASE(I64x2Mul, i64x2, int64x2, 2, base::MulWithWraparound(a, b))
      BINOP_CASE(I32x4Add, i32x4, int32x4, 4, base::AddWithWraparound(a, b))
      BINOP_CASE(I32x4Sub, i32x4, int32x4, 4, base::SubWithWraparound(a, b))
      BINOP_CASE(I32x4Mul, i32x4, int32x4, 4, base::MulWithWraparound(a, b))
      BINOP_CASE(I32x4MinS, i32x4, int32x4, 4, a < b ? a : b)
      BINOP_CASE(I32x4MinU, i32x4, int32x4, 4,
                 static_cast<uint32_t>(a) < static_cast<uint32_t>(b) ? a : b)
      BINOP_CASE(I32x4MaxS, i32x4, int32x4, 4, a > b ? a : b)
      BINOP_CASE(I32x4MaxU, i32x4, int32x4, 4,
                 static_cast<uint32_t>(a) > static_cast<uint32_t>(b) ? a : b)
      BINOP_CASE(S128And, i32x4, int32x4, 4, a & b)
      BINOP_CASE(S128Or, i32x4, int32x4, 4, a | b)
      BINOP_CASE(S128Xor, i32x4, int32x4, 4, a ^ b)
      BINOP_CASE(S128AndNot, i32x4, int32x4, 4, a & ~b)
      BINOP_CASE(I16x8Add, i16x8, int16x8, 8, base::AddWithWraparound(a, b))
      BINOP_CASE(I16x8Sub, i16x8, int16x8, 8, base::SubWithWraparound(a, b))
      BINOP_CASE(I16x8Mul, i16x8, int16x8, 8, base::MulWithWraparound(a, b))
      BINOP_CASE(I16x8MinS, i16x8, int16x8, 8, a < b ? a : b)
      BINOP_CASE(I16x8MinU, i16x8, int16x8, 8,
                 static_cast<uint16_t>(a) < static_cast<uint16_t>(b) ? a : b)
      BINOP_CASE(I16x8MaxS, i16x8, int16x8, 8, a > b ? a : b)
      BINOP_CASE(I16x8MaxU, i16x8, int16x8, 8,
                 static_cast<uint16_t>(a) > static_cast<uint16_t>(b) ? a : b)
      BINOP_CASE(I16x8AddSatS, i16x8, int16x8, 8, SaturateAdd<int16_t>(a, b))
      BINOP_CASE(I16x8AddSatU, i16x8, int16x8, 8, SaturateAdd<uint16_t>(a, b))
      BINOP_CASE(I16x8SubSatS, i16x8, int16x8, 8, SaturateSub<int16_t>(a, b))
      BINOP_CASE(I16x8SubSatU, i16x8, int16x8, 8, SaturateSub<uint16_t>(a, b))
      BINOP_CASE(I16x8RoundingAverageU, i16x8, int16x8, 8,
                 RoundingAverageUnsigned<uint16_t>(a, b))
      BINOP_CASE(I16x8Q15MulRSatS, i16x8, int16x8, 8,
                 SaturateRoundingQMul<int16_t>(a, b))
      BINOP_CASE(I16x8RelaxedQ15MulRS, i16x8, int16x8, 8,
                 SaturateRoundingQMul<int16_t>(a, b))
      BINOP_CASE(I8x16Add, i8x16, int8x16, 16, base::AddWithWraparound(a, b))
      BINOP_CASE(I8x16Sub, i8x16, int8x16, 16, base::SubWithWraparound(a, b))
      BINOP_CASE(I8x16MinS, i8x16, int8x16, 16, a < b ? a : b)
      BINOP_CASE(I8x16MinU, i8x16, int8x16, 16,
                 static_cast<uint8_t>(a) < static_cast<uint8_t>(b) ? a : b)
      BINOP_CASE(I8x16MaxS, i8x16, int8x16, 16, a > b ? a : b)
      BINOP_CASE(I8x16MaxU, i8x16, int8x16, 16,
                 static_cast<uint8_t>(a) > static_cast<uint8_t>(b) ? a : b)
      BINOP_CASE(I8x16AddSatS, i8x16, int8x16, 16, SaturateAdd<int8_t>(a, b))
      BINOP_CASE(I8x16AddSatU, i8x16, int8x16, 16, SaturateAdd<uint8_t>(a, b))
      BINOP_CASE(I8x16SubSatS, i8x16, int8x16, 16, SaturateSub<int8_t>(a, b))
      BINOP_CASE(I8x16SubSatU, i8x16, int8x16, 16, SaturateSub<uint8_t>(a, b))
      BINOP_CASE(I8x16RoundingAverageU, i8x16, int8x16, 16,
                 RoundingAverageUnsigned<uint8_t>(a, b))
#undef BINOP_CASE
#define UNOP_CASE(op, name, stype, count, expr) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      UNOP_CASE(F64x2Abs, f64x2, float64x2, 2, std::abs(a))
      UNOP_CASE(F64x2Neg, f64x2, float64x2, 2, -a)
      UNOP_CASE(F64x2Sqrt, f64x2, float64x2, 2, std::sqrt(a))
      UNOP_CASE(F64x2Ceil, f64x2, float64x2, 2,
                (AixFpOpWorkaround<double, &ceil>(a)))
      UNOP_CASE(F64x2Floor, f64x2, float64x2, 2,
                (AixFpOpWorkaround<double, &floor>(a)))
      UNOP_CASE(F64x2Trunc, f64x2, float64x2, 2,
                (AixFpOpWorkaround<double, &trunc>(a)))
      UNOP_CASE(F64x2NearestInt, f64x2, float64x2, 2,
                (AixFpOpWorkaround<double, &nearbyint>(a)))
      UNOP_CASE(F32x4Abs, f32x4, float32x4, 4, std::abs(a))
      UNOP_CASE(F32x4Neg, f32x4, float32x4, 4, -a)
      UNOP_CASE(F32x4Sqrt, f32x4, float32x4, 4, std::sqrt(a))
      UNOP_CASE(F32x4Ceil, f32x4, float32x4, 4,
                (AixFpOpWorkaround<float, &ceilf>(a)))
      UNOP_CASE(F32x4Floor, f32x4, float32x4, 4,
                (AixFpOpWorkaround<float, &floorf>(a)))
      UNOP_CASE(F32x4Trunc, f32x4, float32x4, 4,
                (AixFpOpWorkaround<float, &truncf>(a)))
      UNOP_CASE(F32x4NearestInt, f32x4, float32x4, 4,
                (AixFpOpWorkaround<float, &nearbyintf>(a)))
      UNOP_CASE(I64x2Neg, i64x2, int64x2, 2, base::NegateWithWraparound(a))
      UNOP_CASE(I32x4Neg, i32x4, int32x4, 4, base::NegateWithWraparound(a))
      // Use llabs which will work correctly on both 64-bit and 32-bit.
      UNOP_CASE(I64x2Abs, i64x2, int64x2, 2, std::llabs(a))
      UNOP_CASE(I32x4Abs, i32x4, int32x4, 4, std::abs(a))
      UNOP_CASE(S128Not, i32x4, int32x4, 4, ~a)
      UNOP_CASE(I16x8Neg, i16x8, int16x8, 8, base::NegateWithWraparound(a))
      UNOP_CASE(I16x8Abs, i16x8, int16x8, 8, std::abs(a))
      UNOP_CASE(I8x16Neg, i8x16, int8x16, 16, base::NegateWithWraparound(a))
      UNOP_CASE(I8x16Abs, i8x16, int8x16, 16, std::abs(a))
      UNOP_CASE(I8x16Popcnt, i8x16, int8x16, 16,
                base::bits::CountPopulation<uint8_t>(a))
#undef UNOP_CASE
#define BITMASK_CASE(op, name, stype, count) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    I32Push(); \
    return RegMode::kNoReg; \
  }
      BITMASK_CASE(I8x16BitMask, i8x16, int8x16, 16)
      BITMASK_CASE(I16x8BitMask, i16x8, int16x8, 8)
      BITMASK_CASE(I32x4BitMask, i32x4, int32x4, 4)
      BITMASK_CASE(I64x2BitMask, i64x2, int64x2, 2)
#undef BITMASK_CASE
#define CMPOP_CASE(op, name, stype, out_stype, count, expr) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      CMPOP_CASE(F64x2Eq, f64x2, float64x2, int64x2, 2, a == b)
      CMPOP_CASE(F64x2Ne, f64x2, float64x2, int64x2, 2, a != b)
      CMPOP_CASE(F64x2Gt, f64x2, float64x2, int64x2, 2, a > b)
      CMPOP_CASE(F64x2Ge, f64x2, float64x2, int64x2, 2, a >= b)
      CMPOP_CASE(F64x2Lt, f64x2, float64x2, int64x2, 2, a < b)
      CMPOP_CASE(F64x2Le, f64x2, float64x2, int64x2, 2, a <= b)
      CMPOP_CASE(F32x4Eq, f32x4, float32x4, int32x4, 4, a == b)
      CMPOP_CASE(F32x4Ne, f32x4, float32x4, int32x4, 4, a != b)
      CMPOP_CASE(F32x4Gt, f32x4, float32x4, int32x4, 4, a > b)
      CMPOP_CASE(F32x4Ge, f32x4, float32x4, int32x4, 4, a >= b)
      CMPOP_CASE(F32x4Lt, f32x4, float32x4, int32x4, 4, a < b)
      CMPOP_CASE(F32x4Le, f32x4, float32x4, int32x4, 4, a <= b)
      CMPOP_CASE(I64x2Eq, i64x2, int64x2, int64x2, 2, a == b)
      CMPOP_CASE(I64x2Ne, i64x2, int64x2, int64x2, 2, a != b)
      CMPOP_CASE(I64x2LtS, i64x2, int64x2, int64x2, 2, a < b)
      CMPOP_CASE(I64x2GtS, i64x2, int64x2, int64x2, 2, a > b)
      CMPOP_CASE(I64x2LeS, i64x2, int64x2, int64x2, 2, a <= b)
      CMPOP_CASE(I64x2GeS, i64x2, int64x2, int64x2, 2, a >= b)
      CMPOP_CASE(I32x4Eq, i32x4, int32x4, int32x4, 4, a == b)
      CMPOP_CASE(I32x4Ne, i32x4, int32x4, int32x4, 4, a != b)
      CMPOP_CASE(I32x4GtS, i32x4, int32x4, int32x4, 4, a > b)
      CMPOP_CASE(I32x4GeS, i32x4, int32x4, int32x4, 4, a >= b)
      CMPOP_CASE(I32x4LtS, i32x4, int32x4, int32x4, 4, a < b)
      CMPOP_CASE(I32x4LeS, i32x4, int32x4, int32x4, 4, a <= b)
      CMPOP_CASE(I32x4GtU, i32x4, int32x4, int32x4, 4,
                 static_cast<uint32_t>(a) > static_cast<uint32_t>(b))
      CMPOP_CASE(I32x4GeU, i32x4, int32x4, int32x4, 4,
                 static_cast<uint32_t>(a) >= static_cast<uint32_t>(b))
      CMPOP_CASE(I32x4LtU, i32x4, int32x4, int32x4, 4,
                 static_cast<uint32_t>(a) < static_cast<uint32_t>(b))
      CMPOP_CASE(I32x4LeU, i32x4, int32x4, int32x4, 4,
                 static_cast<uint32_t>(a) <= static_cast<uint32_t>(b))
      CMPOP_CASE(I16x8Eq, i16x8, int16x8, int16x8, 8, a == b)
      CMPOP_CASE(I16x8Ne, i16x8, int16x8, int16x8, 8, a != b)
      CMPOP_CASE(I16x8GtS, i16x8, int16x8, int16x8, 8, a > b)
      CMPOP_CASE(I16x8GeS, i16x8, int16x8, int16x8, 8, a >= b)
      CMPOP_CASE(I16x8LtS, i16x8, int16x8, int16x8, 8, a < b)
      CMPOP_CASE(I16x8LeS, i16x8, int16x8, int16x8, 8, a <= b)
      CMPOP_CASE(I16x8GtU, i16x8, int16x8, int16x8, 8,
                 static_cast<uint16_t>(a) > static_cast<uint16_t>(b))
      CMPOP_CASE(I16x8GeU, i16x8, int16x8, int16x8, 8,
                 static_cast<uint16_t>(a) >= static_cast<uint16_t>(b))
      CMPOP_CASE(I16x8LtU, i16x8, int16x8, int16x8, 8,
                 static_cast<uint16_t>(a) < static_cast<uint16_t>(b))
      CMPOP_CASE(I16x8LeU, i16x8, int16x8, int16x8, 8,
                 static_cast<uint16_t>(a) <= static_cast<uint16_t>(b))
      CMPOP_CASE(I8x16Eq, i8x16, int8x16, int8x16, 16, a == b)
      CMPOP_CASE(I8x16Ne, i8x16, int8x16, int8x16, 16, a != b)
      CMPOP_CASE(I8x16GtS, i8x16, int8x16, int8x16, 16, a > b)
      CMPOP_CASE(I8x16GeS, i8x16, int8x16, int8x16, 16, a >= b)
      CMPOP_CASE(I8x16LtS, i8x16, int8x16, int8x16, 16, a < b)
      CMPOP_CASE(I8x16LeS, i8x16, int8x16, int8x16, 16, a <= b)
      CMPOP_CASE(I8x16GtU, i8x16, int8x16, int8x16, 16,
                 static_cast<uint8_t>(a) > static_cast<uint8_t>(b))
      CMPOP_CASE(I8x16GeU, i8x16, int8x16, int8x16, 16,
                 static_cast<uint8_t>(a) >= static_cast<uint8_t>(b))
      CMPOP_CASE(I8x16LtU, i8x16, int8x16, int8x16, 16,
                 static_cast<uint8_t>(a) < static_cast<uint8_t>(b))
      CMPOP_CASE(I8x16LeU, i8x16, int8x16, int8x16, 16,
                 static_cast<uint8_t>(a) <= static_cast<uint8_t>(b))
#undef CMPOP_CASE
#define REPLACE_LANE_CASE(format, name, stype, ctype, op_type) \
  case kExpr##format##ReplaceLane: { \
    EMIT_INSTR_HANDLER(s2s_Simd##format##ReplaceLane); \
    /* emit 8 bits ? */ \
    EmitI16Const(instr.optional.simd_lane); \
    op_type##Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      REPLACE_LANE_CASE(F64x2, f64x2, float64x2, double, F64)
      REPLACE_LANE_CASE(F32x4, f32x4, float32x4, float, F32)
      REPLACE_LANE_CASE(I64x2, i64x2, int64x2, int64_t, I64)
      REPLACE_LANE_CASE(I32x4, i32x4, int32x4, int32_t, I32)
      REPLACE_LANE_CASE(I16x8, i16x8, int16x8, int32_t, I32)
      REPLACE_LANE_CASE(I8x16, i8x16, int8x16, int32_t, I32)
#undef REPLACE_LANE_CASE
    case kExprS128LoadMem: {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_SimdS128LoadMem,
                                       s2s_SimdS128LoadMem_Idx64, is_memory64_,
                                       instr.pc);
      EmitMemoryOffset(instr.optional.offset);
      MemIndexPop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprS128StoreMem: {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_SimdS128StoreMem,
                                       s2s_SimdS128StoreMem_Idx64, is_memory64_,
                                       instr.pc);
      S128Pop();
      EmitMemoryOffset(instr.optional.offset);
      MemIndexPop();
      return RegMode::kNoReg;
    }
#define SHIFT_CASE(op, name, stype, count, expr) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    I32Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      SHIFT_CASE(I64x2Shl, i64x2, int64x2, 2,
                 static_cast<uint64_t>(a) << (shift % 64))
      SHIFT_CASE(I64x2ShrS, i64x2, int64x2, 2, a >> (shift % 64))
      SHIFT_CASE(I64x2ShrU, i64x2, int64x2, 2,
                 static_cast<uint64_t>(a) >> (shift % 64))
      SHIFT_CASE(I32x4Shl, i32x4, int32x4, 4,
                 static_cast<uint32_t>(a) << (shift % 32))
      SHIFT_CASE(I32x4ShrS, i32x4, int32x4, 4, a >> (shift % 32))
      SHIFT_CASE(I32x4ShrU, i32x4, int32x4, 4,
                 static_cast<uint32_t>(a) >> (shift % 32))
      SHIFT_CASE(I16x8Shl, i16x8, int16x8, 8,
                 static_cast<uint16_t>(a) << (shift % 16))
      SHIFT_CASE(I16x8ShrS, i16x8, int16x8, 8, a >> (shift % 16))
      SHIFT_CASE(I16x8ShrU, i16x8, int16x8, 8,
                 static_cast<uint16_t>(a) >> (shift % 16))
      SHIFT_CASE(I8x16Shl, i8x16, int8x16, 16,
                 static_cast<uint8_t>(a) << (shift % 8))
      SHIFT_CASE(I8x16ShrS, i8x16, int8x16, 16, a >> (shift % 8))
      SHIFT_CASE(I8x16ShrU, i8x16, int8x16, 16,
                 static_cast<uint8_t>(a) >> (shift % 8))
#undef SHIFT_CASE
#define EXT_MUL_CASE(op) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      EXT_MUL_CASE(I16x8ExtMulLowI8x16S)
      EXT_MUL_CASE(I16x8ExtMulHighI8x16S)
      EXT_MUL_CASE(I16x8ExtMulLowI8x16U)
      EXT_MUL_CASE(I16x8ExtMulHighI8x16U)
      EXT_MUL_CASE(I32x4ExtMulLowI16x8S)
      EXT_MUL_CASE(I32x4ExtMulHighI16x8S)
      EXT_MUL_CASE(I32x4ExtMulLowI16x8U)
      EXT_MUL_CASE(I32x4ExtMulHighI16x8U)
      EXT_MUL_CASE(I64x2ExtMulLowI32x4S)
      EXT_MUL_CASE(I64x2ExtMulHighI32x4S)
      EXT_MUL_CASE(I64x2ExtMulLowI32x4U)
      EXT_MUL_CASE(I64x2ExtMulHighI32x4U)
#undef EXT_MUL_CASE
#define CONVERT_CASE(op, src_type, name, dst_type, count, start_index, ctype, \
                     expr) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      CONVERT_CASE(F32x4SConvertI32x4, int32x4, i32x4, float32x4, 4, 0, int32_t,
                   static_cast<float>(a))
      CONVERT_CASE(F32x4UConvertI32x4, int32x4, i32x4, float32x4, 4, 0,
                   uint32_t, static_cast<float>(a))
      CONVERT_CASE(I32x4SConvertF32x4, float32x4, f32x4, int32x4, 4, 0, float,
                   base::saturated_cast<int32_t>(a))
      CONVERT_CASE(I32x4UConvertF32x4, float32x4, f32x4, int32x4, 4, 0, float,
                   base::saturated_cast<uint32_t>(a))
      CONVERT_CASE(I32x4RelaxedTruncF32x4S, float32x4, f32x4, int32x4, 4, 0,
                   float, base::saturated_cast<int32_t>(a))
      CONVERT_CASE(I32x4RelaxedTruncF32x4U, float32x4, f32x4, int32x4, 4, 0,
                   float, base::saturated_cast<uint32_t>(a))
      CONVERT_CASE(I64x2SConvertI32x4Low, int32x4, i32x4, int64x2, 2, 0,
                   int32_t, a)
      CONVERT_CASE(I64x2SConvertI32x4High, int32x4, i32x4, int64x2, 2, 2,
                   int32_t, a)
      CONVERT_CASE(I64x2UConvertI32x4Low, int32x4, i32x4, int64x2, 2, 0,
                   uint32_t, a)
      CONVERT_CASE(I64x2UConvertI32x4High, int32x4, i32x4, int64x2, 2, 2,
                   uint32_t, a)
      CONVERT_CASE(I32x4SConvertI16x8High, int16x8, i16x8, int32x4, 4, 4,
                   int16_t, a)
      CONVERT_CASE(I32x4UConvertI16x8High, int16x8, i16x8, int32x4, 4, 4,
                   uint16_t, a)
      CONVERT_CASE(I32x4SConvertI16x8Low, int16x8, i16x8, int32x4, 4, 0,
                   int16_t, a)
      CONVERT_CASE(I32x4UConvertI16x8Low, int16x8, i16x8, int32x4, 4, 0,
                   uint16_t, a)
      CONVERT_CASE(I16x8SConvertI8x16High, int8x16, i8x16, int16x8, 8, 8,
                   int8_t, a)
      CONVERT_CASE(I16x8UConvertI8x16High, int8x16, i8x16, int16x8, 8, 8,
                   uint8_t, a)
      CONVERT_CASE(I16x8SConvertI8x16Low, int8x16, i8x16, int16x8, 8, 0, int8_t,
                   a)
      CONVERT_CASE(I16x8UConvertI8x16Low, int8x16, i8x16, int16x8, 8, 0,
                   uint8_t, a)
      CONVERT_CASE(F64x2ConvertLowI32x4S, int32x4, i32x4, float64x2, 2, 0,
                   int32_t, static_cast<double>(a))
      CONVERT_CASE(F64x2ConvertLowI32x4U, int32x4, i32x4, float64x2, 2, 0,
                   uint32_t, static_cast<double>(a))
      CONVERT_CASE(I32x4TruncSatF64x2SZero, float64x2, f64x2, int32x4, 2, 0,
                   double, base::saturated_cast<int32_t>(a))
      CONVERT_CASE(I32x4TruncSatF64x2UZero, float64x2, f64x2, int32x4, 2, 0,
                   double, base::saturated_cast<uint32_t>(a))
      CONVERT_CASE(I32x4RelaxedTruncF64x2SZero, float64x2, f64x2, int32x4, 2, 0,
                   double, base::saturated_cast<int32_t>(a))
      CONVERT_CASE(I32x4RelaxedTruncF64x2UZero, float64x2, f64x2, int32x4, 2, 0,
                   double, base::saturated_cast<uint32_t>(a))
      CONVERT_CASE(F32x4DemoteF64x2Zero, float64x2, f64x2, float32x4, 2, 0,
                   float, DoubleToFloat32(a))
      CONVERT_CASE(F64x2PromoteLowF32x4, float32x4, f32x4, float64x2, 2, 0,
                   float, static_cast<double>(a))
#undef CONVERT_CASE
#define PACK_CASE(op, src_type, name, dst_type, count, dst_ctype) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      PACK_CASE(I16x8SConvertI32x4, int32x4, i32x4, int16x8, 8, int16_t)
      PACK_CASE(I16x8UConvertI32x4, int32x4, i32x4, int16x8, 8, uint16_t)
      PACK_CASE(I8x16SConvertI16x8, int16x8, i16x8, int8x16, 16, int8_t)
      PACK_CASE(I8x16UConvertI16x8, int16x8, i16x8, int8x16, 16, uint8_t)
#undef PACK_CASE
#define SELECT_CASE(op) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      SELECT_CASE(I8x16RelaxedLaneSelect)
      SELECT_CASE(I16x8RelaxedLaneSelect)
      SELECT_CASE(I32x4RelaxedLaneSelect)
      SELECT_CASE(I64x2RelaxedLaneSelect)
      SELECT_CASE(S128Select)
#undef SELECT_CASE
    case kExprI32x4DotI16x8S: {
      EMIT_INSTR_HANDLER(s2s_SimdI32x4DotI16x8S);
      S128Pop();
      S128Pop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprS128Const: {
      PushConstSlot<Simd128>(
          simd_immediates_[instr.optional.simd_immediate_index]);
      return RegMode::kNoReg;
    }
    case kExprI16x8DotI8x16I7x16S: {
      EMIT_INSTR_HANDLER(s2s_SimdI16x8DotI8x16I7x16S);
      S128Pop();
      S128Pop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprI32x4DotI8x16I7x16AddS: {
      EMIT_INSTR_HANDLER(s2s_SimdI32x4DotI8x16I7x16AddS);
      S128Pop();
      S128Pop();
      S128Pop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprI8x16RelaxedSwizzle: {
      EMIT_INSTR_HANDLER(s2s_SimdI8x16RelaxedSwizzle);
      S128Pop();
      S128Pop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprI8x16Swizzle: {
      EMIT_INSTR_HANDLER(s2s_SimdI8x16Swizzle);
      S128Pop();
      S128Pop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprI8x16Shuffle: {
      uint32_t slot_index = CreateConstSlot(
          simd_immediates_[instr.optional.simd_immediate_index]);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      TracePushConstSlot(slot_index);
#endif // V8_ENABLE_DRUMBRAKE_TRACING
      EMIT_INSTR_HANDLER(s2s_SimdI8x16Shuffle);
      PushSlot(slot_index);
      S128Pop();
      S128Pop();
      S128Pop();
      S128Push();
      return RegMode::kNoReg;
    }
    case kExprV128AnyTrue: {
      EMIT_INSTR_HANDLER(s2s_SimdV128AnyTrue);
      S128Pop();
      I32Push();
      return RegMode::kNoReg;
    }
#define REDUCTION_CASE(op, name, stype, count, operation) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    I32Push(); \
    return RegMode::kNoReg; \
  }
      REDUCTION_CASE(I64x2AllTrue, i64x2, int64x2, 2, &)
      REDUCTION_CASE(I32x4AllTrue, i32x4, int32x4, 4, &)
      REDUCTION_CASE(I16x8AllTrue, i16x8, int16x8, 8, &)
      REDUCTION_CASE(I8x16AllTrue, i8x16, int8x16, 16, &)
#undef REDUCTION_CASE
#define QFM_CASE(op, name, stype, count, operation) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Pop(); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      QFM_CASE(F32x4Qfma, f32x4, float32x4, 4, +)
      QFM_CASE(F32x4Qfms, f32x4, float32x4, 4, -)
      QFM_CASE(F64x2Qfma, f64x2, float64x2, 2, +)
      QFM_CASE(F64x2Qfms, f64x2, float64x2, 2, -)
#undef QFM_CASE
#define LOAD_SPLAT_CASE(op) \
  case kExprS128##op: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(\
        s2s_SimdS128##op, s2s_SimdS128##op##_Idx64, is_memory64_, instr.pc); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      LOAD_SPLAT_CASE(Load8Splat)
      LOAD_SPLAT_CASE(Load16Splat)
      LOAD_SPLAT_CASE(Load32Splat)
      LOAD_SPLAT_CASE(Load64Splat)
#undef LOAD_SPLAT_CASE
#define LOAD_EXTEND_CASE(op) \
  case kExprS128##op: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(\
        s2s_SimdS128##op, s2s_SimdS128##op##_Idx64, is_memory64_, instr.pc); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      LOAD_EXTEND_CASE(Load8x8S)
      LOAD_EXTEND_CASE(Load8x8U)
      LOAD_EXTEND_CASE(Load16x4S)
      LOAD_EXTEND_CASE(Load16x4U)
      LOAD_EXTEND_CASE(Load32x2S)
      LOAD_EXTEND_CASE(Load32x2U)
#undef LOAD_EXTEND_CASE
#define LOAD_ZERO_EXTEND_CASE(op, load_type) \
  case kExprS128##op: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(\
        s2s_SimdS128##op, s2s_SimdS128##op##_Idx64, is_memory64_, instr.pc); \
    EmitMemoryOffset(instr.optional.offset); \
    MemIndexPop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      LOAD_ZERO_EXTEND_CASE(Load32Zero, I32)
      LOAD_ZERO_EXTEND_CASE(Load64Zero, I64)
#undef LOAD_ZERO_EXTEND_CASE
#define LOAD_LANE_CASE(op) \
  case kExprS128##op: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(\
        s2s_SimdS128##op, s2s_SimdS128##op##_Idx64, is_memory64_, instr.pc); \
    S128Pop(); \
    EmitMemoryOffset(instr.optional.simd_loadstore_lane.offset); \
    MemIndexPop(); \
    /* emit 8 bits ? */ \
    EmitI16Const(instr.optional.simd_loadstore_lane.lane); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      LOAD_LANE_CASE(Load8Lane)
      LOAD_LANE_CASE(Load16Lane)
      LOAD_LANE_CASE(Load32Lane)
      LOAD_LANE_CASE(Load64Lane)
#undef LOAD_LANE_CASE
#define STORE_LANE_CASE(op) \
  case kExprS128##op: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(\
        s2s_SimdS128##op, s2s_SimdS128##op##_Idx64, is_memory64_, instr.pc); \
    S128Pop(); \
    EmitMemoryOffset(instr.optional.simd_loadstore_lane.offset); \
    MemIndexPop(); \
    /* emit 8 bits ? */ \
    EmitI16Const(instr.optional.simd_loadstore_lane.lane); \
    return RegMode::kNoReg; \
  }
      STORE_LANE_CASE(Store8Lane)
      STORE_LANE_CASE(Store16Lane)
      STORE_LANE_CASE(Store32Lane)
      STORE_LANE_CASE(Store64Lane)
#undef STORE_LANE_CASE
#define EXT_ADD_PAIRWISE_CASE(op) \
  case kExpr##op: { \
    EMIT_INSTR_HANDLER(s2s_Simd##op); \
    S128Pop(); \
    S128Push(); \
    return RegMode::kNoReg; \
  }
      EXT_ADD_PAIRWISE_CASE(I32x4ExtAddPairwiseI16x8S)
      EXT_ADD_PAIRWISE_CASE(I32x4ExtAddPairwiseI16x8U)
      EXT_ADD_PAIRWISE_CASE(I16x8ExtAddPairwiseI8x16S)
      EXT_ADD_PAIRWISE_CASE(I16x8ExtAddPairwiseI8x16U)
#undef EXT_ADD_PAIRWISE_CASE
    default:
      FATAL("Unknown or unimplemented opcode #%d:%s",
            wasm_code_->start[instr.pc],
            WasmOpcodes::OpcodeName(
                static_cast<WasmOpcode>(wasm_code_->start[instr.pc])));
      UNREACHABLE();
  }
  return RegMode::kNoReg;
}
References v8::internal::wasm::WasmEHDataGenerator::AddCatchBlock(), v8::internal::wasm::WasmEHDataGenerator::AddDelegatedBlock(), v8::internal::wasm::WasmEHDataGenerator::AddTryBlock(), v8::internal::wasm::WasmBytecode::ArgsSizeInSlots(), v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewFixed::array_index, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewOrInitData::array_index, v8::internal::wasm::WasmModule::array_type(), ATOMIC_BINOP, ATOMIC_COMPARE_EXCHANGE_OP, ATOMIC_LOAD_OP, ATOMIC_STORE_OP, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back(), BeginBlock(), BeginElseBlock(), BINOP_CASE, BITMASK_CASE, v8::internal::wasm::WasmInstruction::Optional::block, blocks_, v8::internal::wasm::WasmInstruction::Optional::br_on_cast_data, v8::internal::wasm::WasmInstruction::Optional::br_table, br_table_labels_, CMPOP_CASE, code_, CONVERT_CASE, CopyToSlotAndPop(), CreateConstSlot(), CreateSlot(), current_block_index_, CurrentCodePos(), v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewOrInitData::data_index, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::wasm::WasmInstruction::Optional::depth, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayCopy::dest_array_index, v8::base::Divide(), v8::internal::DoubleToFloat32(), v8::internal::wasm::WasmInstruction::Optional::TableCopy::dst_table_index, eh_data_, v8::internal::wasm::WasmInstruction::Optional::TableInit::element_segment_index, v8::internal::wasm::ArrayType::element_type(), Emit(), EMIT_INSTR_HANDLER, EMIT_INSTR_HANDLER_WITH_PC, EMIT_MEM64_INSTR_HANDLER, EMIT_MEM64_INSTR_HANDLER_WITH_PC, EmitBranchOffset(), EmitBranchTableOffset(), EmitGlobalIndex(), EmitI32Const(), EmitIfElseBranchOffset(), EmitMemoryOffset(), EmitRefStackIndex(), EmitRefValueType(), EmitSlotOffset(), EmitStackIndex(), EmitStructFieldOffset(), EmitTryCatchBranchOffset(), EndBlock(), EXECUTE_BINOP, EXECUTE_UNOP, EXT_ADD_PAIRWISE_CASE, EXT_MUL_CASE, EXTRACT_LANE_CASE, EXTRACT_LANE_EXTEND_CASE, v8::internal::wasm::WasmInstruction::Optional::f32, F32Pop(), F32Push(), v8::internal::wasm::WasmInstruction::Optional::f64, F64Pop(), F64Push(), FATAL, v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::WasmInstruction::Optional::GC_FieldImmediate::field_index, FOREACH_ADDITIONAL_CONVERT_UNOP, FOREACH_ARITHMETIC_BINOP, FOREACH_ATOMIC_BINOP, FOREACH_ATOMIC_COMPARE_EXCHANGE_OP, FOREACH_ATOMIC_LOAD_OP, FOREACH_ATOMIC_STORE_OP, FOREACH_BITS_UNOP, FOREACH_COMPARISON_BINOP, FOREACH_EXTENSION_UNOP, FOREACH_I32_CONVERT_FROM_FLOAT_UNOP, FOREACH_I64_CONVERT_FROM_FLOAT_UNOP, FOREACH_MORE_BINOP, FOREACH_OTHER_CONVERT_UNOP, FOREACH_REINTERPRET_UNOP, FOREACH_SIMPLE_UNOP, FOREACH_TRAPPING_BINOP, FOREACH_TRUNCSAT_UNOP, v8::internal::wasm::HeapType::FromBits(), function_index(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WasmInstruction::Optional::gc_array_copy, v8::internal::wasm::WasmInstruction::Optional::gc_array_new_fixed, v8::internal::wasm::WasmInstruction::Optional::gc_array_new_or_init_data, v8::internal::wasm::WasmInstruction::Optional::gc_field_immediate, v8::internal::wasm::WasmInstruction::Optional::gc_heap_type_immediate, v8::internal::wasm::WasmEHDataGenerator::GetCurrentTryBlockIndex(), GetCurrentTryBlockIndex(), GetFunctionSignature(), GetGlobalType(), v8::internal::wasm::GetOperatorModeString(), v8::internal::wasm::GetRegMode(), v8::internal::wasm::GetRegModeString(), GetStackFrameSize(), GetTargetBranch(), GetTopStackType(), v8::internal::wasm::WasmModule::globals, HasVoidSignature(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::WasmModule::heap_type(), v8::internal::wasm::WasmInstruction::Optional::GC_HeapTypeImmediate::heap_type_bit_field, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmInstruction::Optional::i32, I32Pop(), I32Push(), v8::internal::wasm::WasmInstruction::Optional::i64, I64Pop(), I64Push(), v8::internal::index, v8::internal::wasm::WasmInstruction::Optional::index, v8::internal::wasm::WasmInstruction::Optional::indirect_call, InitSlotsForFunctionArgs(), v8::internal::wasm::HeapType::is_index(), is_instruction_reachable_, is_memory64_, v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_object_reference(), v8::internal::is_signed(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsTry(), v8::internal::JSMax(), v8::internal::JSMin(), v8::internal::wasm::kAnyReg, v8::internal::wasm::WasmEHData::kCatchAllTagIndex, v8::internal::wasm::WasmEHData::kDelegateToCallerIndex, v8::internal::kF32, v8::internal::wasm::kF32Reg, v8::internal::kF64, v8::internal::wasm::kF64Reg, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kI16, v8::internal::kI32, v8::internal::wasm::kI32Reg, v8::internal::kI64, v8::internal::wasm::kI64Reg, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNonNullable, v8::internal::wasm::kNoReg, v8::internal::wasm::kNullable, v8::internal::wasm::kR2R, v8::internal::wasm::kR2S, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::kS2R, v8::internal::wasm::kS2S, v8::internal::wasm::kSlotSize, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmExternRef, v8::internal::wasm::kWasmRefI31, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::wasm::BranchOnCastData::label_depth, v8::internal::wasm::WasmInstruction::Optional::BrTable::labels_index, v8::internal::length, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayNewFixed::length, LOAD_CASE, LOAD_EXTEND_CASE, LOAD_LANE_CASE, LOAD_SPLAT_CASE, LOAD_ZERO_EXTEND_CASE, MemIndexPop(), MemIndexPush(), mode(), module_, v8::base::MulWithWraparound(), v8::base::NegateWithWraparound(), v8::internal::wasm::WasmInstruction::Optional::offset, v8::internal::wasm::WasmInstruction::opcode, v8::internal::wasm::WasmOpcodes::OpcodeName(), v8::internal::wasm::WasmInstruction::optional, PACK_CASE, ParamsCount(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::parent_try_block_index_, v8::internal::wasm::WasmInstruction::pc, Pop(), PreserveArgsAndLocals(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::push_back(), PushCopySlot(), PushSlot(), QFM_CASE, v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::internal::wasm::WasmEHDataGenerator::RecordPotentialExceptionThrowingInstruction(), REDUCTION_CASE, v8::internal::wasm::ValueType::Ref(), ref_slots_count_, v8::internal::wasm::WasmInstruction::Optional::ref_type_bit_field, v8::internal::wasm::WasmBytecode::RefArgsCount(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::wasm::ValueType::RefNull(), RefPop(), RefPush(), v8::internal::wasm::WasmBytecode::RefRetsCount(), REPLACE_LANE_CASE, v8::internal::wasm::BranchOnCastData::res_is_null, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::resize(), v8::internal::wasm::WasmBytecode::RetsSizeInSlots(), Return(), v8::internal::S, S128Pop(), S128Push(), SELECT_CASE, SetSlotType(), SetUnreachableMode(), SHIFT_CASE, v8::internal::wasm::WasmTag::sig, v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::IndirectCall::sig_index, v8::internal::wasm::WasmModule::signature(), v8::internal::wasm::WasmInstruction::Optional::simd_immediate_index, simd_immediates_, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), slots_, SPLAT_CASE, v8::internal::wasm::WasmInstruction::Optional::GC_ArrayCopy::src_array_index, v8::internal::wasm::WasmInstruction::Optional::TableCopy::src_table_index, stack_, stack_size(), stack_top_index(), v8::internal::wasm::InterpreterCode::start, STORE_CASE, STORE_LANE_CASE, StoreBlockParamsAndResultsIntoSlots(), v8::internal::wasm::WasmInstruction::Optional::GC_FieldImmediate::struct_index, v8::internal::wasm::WasmModule::struct_type(), v8::internal::wasm::StructFieldOffset(), v8::internal::wasm::WasmInstruction::Optional::table_copy, v8::internal::wasm::WasmInstruction::Optional::BrTable::table_count, v8::internal::wasm::WasmInstruction::Optional::IndirectCall::table_index, v8::internal::wasm::WasmInstruction::Optional::TableInit::table_index, v8::internal::wasm::WasmInstruction::Optional::table_init, v8::internal::wasm::WasmModule::tables, v8::internal::wasm::WasmModule::tags, v8::internal::wasm::BranchOnCastData::target_type_bit_fields, ToRegisterIsAllowed(), v8::internal::tracing::type, TypeCheckAlwaysFails(), TypeCheckAlwaysSucceeds(), v8::internal::U, UNOP_CASE, v8::internal::UNREACHABLE(), unreachable_block_count_, v8::internal::v8_flags, V8_LIKELY, V8_UNLIKELY, v8::internal::wasm::value_type(), and wasm_code_.
Referenced by EncodeInstruction().
DoEncodeSuperInstruction()
bool v8::internal::wasm::WasmBytecodeGenerator::DoEncodeSuperInstruction (RegMode & reg_mode, const WasmInstruction & curr_instr, const WasmInstruction & next_instr) [private]
Definition at line 12770 of file wasm-interpreter.cc.
                                       {
  if (curr_instr.orig >= kExprI32LoadMem &&
      curr_instr.orig <= kExprI64LoadMem32U &&
      next_instr.orig == kExprLocalSet) {
    // Do not optimize if we are updating a shared slot.
    uint32_t to_stack_index = next_instr.optional.index;
    if (HasSharedSlot(to_stack_index)) return false;
    switch (curr_instr.orig) {
// The implementation of r2s_LoadMem_LocalSet is identical to the
// implementation of r2s_LoadMem, so we can reuse the same builtin.
#define LOAD_CASE(name, ctype, mtype, rep, type) \
  case kExpr##name: { \
    if (reg_mode == RegMode::kNoReg) { \
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name##_LocalSet, \
                                       s2s_##name##_LocalSet_Idx64, \
                                       is_memory64_, curr_instr.pc); \
      EmitMemoryOffset(curr_instr.optional.offset); \
      MemIndexPop(); \
      EmitSlotOffset(slots_[stack_[to_stack_index]].slot_offset); \
      reg_mode = RegMode::kNoReg; \
    } else { \
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_##name, r2s_##name##_Idx64, \
                                       is_memory64_, curr_instr.pc); \
      EmitMemoryOffset(static_cast<uint64_t>(curr_instr.optional.offset)); \
      EmitSlotOffset(slots_[stack_[to_stack_index]].slot_offset); \
      reg_mode = RegMode::kNoReg; \
    } \
    return true; \
  }
      LOAD_CASE(I32LoadMem8S, int32_t, int8_t, kWord8, I32);
      LOAD_CASE(I32LoadMem8U, int32_t, uint8_t, kWord8, I32);
      LOAD_CASE(I32LoadMem16S, int32_t, int16_t, kWord16, I32);
      LOAD_CASE(I32LoadMem16U, int32_t, uint16_t, kWord16, I32);
      LOAD_CASE(I64LoadMem8S, int64_t, int8_t, kWord8, I64);
      LOAD_CASE(I64LoadMem8U, int64_t, uint8_t, kWord16, I64);
      LOAD_CASE(I64LoadMem16S, int64_t, int16_t, kWord16, I64);
      LOAD_CASE(I64LoadMem16U, int64_t, uint16_t, kWord16, I64);
      LOAD_CASE(I64LoadMem32S, int64_t, int32_t, kWord32, I64);
      LOAD_CASE(I64LoadMem32U, int64_t, uint32_t, kWord32, I64);
      LOAD_CASE(I32LoadMem, int32_t, int32_t, kWord32, I32);
      LOAD_CASE(I64LoadMem, int64_t, int64_t, kWord64, I64);
      LOAD_CASE(F32LoadMem, Float32, uint32_t, kFloat32, F32);
      LOAD_CASE(F64LoadMem, Float64, uint64_t, kFloat64, F64);
#undef LOAD_CASE
      default:
        return false;
    }
  } else if (curr_instr.orig == kExprI32LoadMem &&
             next_instr.orig == kExprI32StoreMem) {
    if (reg_mode == RegMode::kNoReg) {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_I32LoadStoreMem,
                                       s2s_I32LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset); // load_offset
      MemIndexPop(); // load_index
    } else {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_I32LoadStoreMem,
                                       r2s_I32LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset); // load_offset
    }
    EmitMemoryOffset(next_instr.optional.offset); // store_offset
    MemIndexPop(); // store_index
    reg_mode = RegMode::kNoReg;
    return true;
  } else if (curr_instr.orig == kExprI64LoadMem &&
             next_instr.orig == kExprI64StoreMem) {
    if (reg_mode == RegMode::kNoReg) {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_I64LoadStoreMem,
                                       s2s_I64LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset);
      MemIndexPop();
    } else {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_I64LoadStoreMem,
                                       r2s_I64LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset);
    }
    EmitMemoryOffset(next_instr.optional.offset);
    MemIndexPop();
    reg_mode = RegMode::kNoReg;
    return true;
  } else if (curr_instr.orig == kExprF32LoadMem &&
             next_instr.orig == kExprF32StoreMem) {
    if (reg_mode == RegMode::kNoReg) {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_F32LoadStoreMem,
                                       s2s_F32LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset);
      MemIndexPop();
    } else {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_F32LoadStoreMem,
                                       r2s_F32LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset);
    }
    EmitMemoryOffset(next_instr.optional.offset);
    MemIndexPop();
    reg_mode = RegMode::kNoReg;
    return true;
  } else if (curr_instr.orig == kExprF64LoadMem &&
             next_instr.orig == kExprF64StoreMem) {
    if (reg_mode == RegMode::kNoReg) {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_F64LoadStoreMem,
                                       s2s_F64LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset);
      MemIndexPop();
    } else {
      EMIT_MEM64_INSTR_HANDLER_WITH_PC(r2s_F64LoadStoreMem,
                                       r2s_F64LoadStoreMem_Idx64, is_memory64_,
                                       curr_instr.pc);
      EmitMemoryOffset(curr_instr.optional.offset);
    }
    EmitMemoryOffset(next_instr.optional.offset);
    MemIndexPop();
    reg_mode = RegMode::kNoReg;
    return true;
  } else if (curr_instr.orig >= kExprI32Const &&
             curr_instr.orig <= kExprF32Const &&
             next_instr.orig == kExprLocalSet) {
    uint32_t to_stack_index = next_instr.optional.index;
    switch (curr_instr.orig) {
      case kExprI32Const: {
        uint32_t from_slot_index =
            CreateConstSlot<int32_t>(curr_instr.optional.i32);
        CopyToSlot(kWasmI32, from_slot_index, to_stack_index, false);
        reg_mode = RegMode::kNoReg;
        return true;
      }
      case kExprI64Const: {
        uint32_t from_slot_index =
            CreateConstSlot<int64_t>(curr_instr.optional.i64);
        CopyToSlot(kWasmI64, from_slot_index, to_stack_index, false);
        reg_mode = RegMode::kNoReg;
        return true;
      }
      case kExprF32Const: {
        uint32_t from_slot_index =
            CreateConstSlot<float>(curr_instr.optional.f32);
        CopyToSlot(kWasmF32, from_slot_index, to_stack_index, false);
        reg_mode = RegMode::kNoReg;
        return true;
      }
      case kExprF64Const: {
        uint32_t from_slot_index =
            CreateConstSlot<double>(curr_instr.optional.f64);
        CopyToSlot(kWasmF64, from_slot_index, to_stack_index, false);
        reg_mode = RegMode::kNoReg;
        return true;
      }
      default:
        return false;
    }
  } else if (curr_instr.orig == kExprLocalGet &&
             next_instr.orig >= kExprI32StoreMem &&
             next_instr.orig <= kExprI64StoreMem32) {
    switch (next_instr.orig) {
// The implementation of r2s_LocalGet_StoreMem is identical to the
// implementation of r2s_StoreMem, so we can reuse the same builtin.
#define STORE_CASE(name, ctype, mtype, rep, type) \
  case kExpr##name: { \
    EMIT_MEM64_INSTR_HANDLER_WITH_PC(s2s_##name, s2s_##name##_Idx64, \
                                     is_memory64_, curr_instr.pc); \
    EmitSlotOffset(slots_[stack_[curr_instr.optional.index]].slot_offset); \
    EmitMemoryOffset(next_instr.optional.offset); \
    MemIndexPop(); \
    reg_mode = RegMode::kNoReg; \
    return true; \
  }
      STORE_CASE(I32StoreMem8, int32_t, int8_t, kWord8, I32);
      STORE_CASE(I32StoreMem16, int32_t, int16_t, kWord16, I32);
      STORE_CASE(I64StoreMem8, int64_t, int8_t, kWord8, I64);
      STORE_CASE(I64StoreMem16, int64_t, int16_t, kWord16, I64);
      STORE_CASE(I64StoreMem32, int64_t, int32_t, kWord32, I64);
      STORE_CASE(I32StoreMem, int32_t, int32_t, kWord32, I32);
      STORE_CASE(I64StoreMem, int64_t, int64_t, kWord64, I64);
      STORE_CASE(F32StoreMem, Float32, uint32_t, kFloat32, F32);
      STORE_CASE(F64StoreMem, Float64, uint64_t, kFloat64, F64);
#undef STORE_CASE
      default:
        return false;
    }
  }
  return false;
}
References CopyToSlot(), EMIT_MEM64_INSTR_HANDLER_WITH_PC, EmitMemoryOffset(), v8::internal::wasm::WasmInstruction::Optional::f32, v8::internal::wasm::WasmInstruction::Optional::f64, HasSharedSlot(), v8::internal::wasm::WasmInstruction::Optional::i32, v8::internal::wasm::WasmInstruction::Optional::i64, v8::internal::wasm::WasmInstruction::Optional::index, is_memory64_, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::wasm::kNoReg, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI64, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, LOAD_CASE, MemIndexPop(), v8::internal::wasm::WasmInstruction::Optional::offset, v8::internal::wasm::WasmInstruction::optional, v8::internal::wasm::WasmInstruction::orig, v8::internal::wasm::WasmInstruction::pc, and STORE_CASE.
Referenced by EncodeSuperInstruction().
Emit()
void v8::internal::wasm::WasmBytecodeGenerator::Emit (const void * buff, size_t len) [inline], [private]
Definition at line 1564 of file wasm-interpreter.h.
                                          {
    code_.insert(code_.end(), static_cast<const uint8_t*>(buff),
                 static_cast<const uint8_t*>(buff) + len);
  }
References code_.
Referenced by DoEncodeInstruction(), EmitF32Const(), EmitF64Const(), EmitFnId(), EmitI16Const(), EmitI32Const(), EmitMemoryOffset(), EmitRefStackIndex(), EmitRefValueType(), EmitSlotOffset(), EmitStackIndex(), and EmitStructFieldOffset().
EmitBranchOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitBranchOffset (uint32_t delta) [inline], [private]
Definition at line 532 of file wasm-interpreter-inl.h.
                                                                  {
  int32_t target_branch_index = GetTargetBranch(delta);
  DCHECK_GE(target_branch_index, 0);
  blocks_[target_branch_index].branch_code_offsets_.emplace_back(
      CurrentCodePos());
  const uint32_t current_code_offset = CurrentCodePos();
  Emit(&current_code_offset, sizeof(current_code_offset));
}
References DCHECK_GE.
Referenced by DoEncodeInstruction().
EmitBranchTableOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitBranchTableOffset (uint32_t delta, uint32_t code_pos) [inline], [private]
Definition at line 542 of file wasm-interpreter-inl.h.
                                                                            {
  int32_t target_branch_index = GetTargetBranch(delta);
  DCHECK_GE(target_branch_index, 0);
  blocks_[target_branch_index].branch_code_offsets_.emplace_back(code_pos);
  Emit(&code_pos, sizeof(code_pos));
}
References DCHECK_GE.
Referenced by DoEncodeInstruction().
EmitCopySlot()
void v8::internal::wasm::WasmBytecodeGenerator::EmitCopySlot (ValueType value_type, uint32_t from_slot_index, uint32_t to_slot_index, bool copy_from_reg = false) [private]
Definition at line 7518 of file wasm-interpreter.cc.
                                                             {
  START_EMIT_INSTR_HANDLER() {
    const ValueKind kind = value_type.kind();
    switch (kind) {
      case kI32:
        if (copy_from_reg) {
          EMIT_INSTR_HANDLER(r2s_CopyR0ToSlot32);
        } else {
          EMIT_INSTR_HANDLER(s2s_CopySlot32);
        }
        break;
      case kI64:
        if (copy_from_reg) {
          EMIT_INSTR_HANDLER(r2s_CopyR0ToSlot64);
        } else {
          EMIT_INSTR_HANDLER(s2s_CopySlot64);
        }
        break;
      case kF32:
        if (copy_from_reg) {
          EMIT_INSTR_HANDLER(r2s_CopyFp0ToSlot32);
        } else {
          EMIT_INSTR_HANDLER(s2s_CopySlot32);
        }
        break;
      case kF64:
        if (copy_from_reg) {
          EMIT_INSTR_HANDLER(r2s_CopyFp0ToSlot64);
        } else {
          EMIT_INSTR_HANDLER(s2s_CopySlot64);
        }
        break;
      case kS128:
        DCHECK(!copy_from_reg);
        EMIT_INSTR_HANDLER(s2s_CopySlot128);
        break;
      case kRef:
      case kRefNull:
        DCHECK(!copy_from_reg);
        EMIT_INSTR_HANDLER(s2s_CopySlotRef);
        break;
      default:
        UNREACHABLE();
    }
    if (kind == kRefNull || kind == kRef) {
      DCHECK(!copy_from_reg);
      EmitRefStackIndex(slots_[from_slot_index].ref_stack_index);
      EmitRefStackIndex(slots_[to_slot_index].ref_stack_index);
    } else {
      if (!copy_from_reg) {
        EmitSlotOffset(slots_[from_slot_index].slot_offset);
      }
      EmitSlotOffset(slots_[to_slot_index].slot_offset);
    }
  }
  END_EMIT_INSTR_HANDLER()
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_bytecode_generator &&
      v8_flags.trace_drumbrake_execution_verbose) {
    printf("emit CopySlot: %d(%d) -> %d(%d)\n", from_slot_index,
           slots_[from_slot_index].slot_offset, to_slot_index,
           slots_[to_slot_index].slot_offset);
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
}
References v8::internal::DCHECK(), EMIT_INSTR_HANDLER, EmitRefStackIndex(), EmitSlotOffset(), END_EMIT_INSTR_HANDLER, v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, slots_, START_EMIT_INSTR_HANDLER, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::wasm::value_type().
Referenced by CopyToSlot(), InitSlotsForFunctionArgs(), PreserveArgsAndLocals(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
EmitF32Const()
void v8::internal::wasm::WasmBytecodeGenerator::EmitF32Const (float value) [inline], [private]
Definition at line 1620 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
EmitF64Const()
void v8::internal::wasm::WasmBytecodeGenerator::EmitF64Const (double value) [inline], [private]
Definition at line 1621 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
EmitFnId()
void v8::internal::wasm::WasmBytecodeGenerator::EmitFnId (InstructionHandler func_id, uint32_t pc = UINT_MAX) [inline], [private]
Definition at line 1671 of file wasm-interpreter.h.
                                                                           {
    // If possible, compacts two consecutive CopySlot32 or CopySlot64
    // instructions into a single instruction, to save one dispatch.
    if (TryCompactInstructionHandler(func_id)) return;
    if (pc != UINT_MAX) {
      code_pc_map_[code_.size()] = pc;
    }
    last_instr_offset_ = CurrentCodePos();
    int16_t id = func_id;
    if (V8_UNLIKELY(handler_size_ == InstrHandlerSize::Large)) {
      id += kInstructionCount;
    } else {
      DCHECK_EQ(handler_size_, InstrHandlerSize::Small);
    }
    Emit(&id, sizeof(id));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_compact_bytecode) {
      printf("* EmitFnId %04x %s%s\n", id, kInstructionHandlerNames[func_id],
             id >= kInstructionCount ? " (large)" : "");
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  }
References code_, code_pc_map_, CurrentCodePos(), DCHECK_EQ, Emit(), handler_size_, v8::internal::wasm::kInstructionCount, v8::internal::wasm::Large, last_instr_offset_, v8::internal::wasm::Small, TryCompactInstructionHandler(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by InitSlotsForFunctionArgs().
EmitGlobalIndex()
void v8::internal::wasm::WasmBytecodeGenerator::EmitGlobalIndex (uint32_t index) [inline], [private]
Definition at line 508 of file wasm-interpreter-inl.h.
                                                                 {
  Emit(&index, sizeof(index));
}
References v8::internal::index.
Referenced by DoEncodeInstruction().
EmitI16Const()
void v8::internal::wasm::WasmBytecodeGenerator::EmitI16Const (int16_t value) [inline], [private]
Definition at line 1618 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
EmitI32Const()
void v8::internal::wasm::WasmBytecodeGenerator::EmitI32Const (int32_t value) [inline], [private]
Definition at line 1619 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
Referenced by DoEncodeInstruction(), and InitSlotsForFunctionArgs().
EmitIfElseBranchOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitIfElseBranchOffset () [inline], [private]
Definition at line 551 of file wasm-interpreter-inl.h.
                                                          {
  // Initially emits offset to jump the end of the 'if' block. If we meet an
  // 'else' instruction later, this offset needs to be updated with the offset
  // to the beginning of that 'else' block.
  blocks_[current_block_index_].branch_code_offsets_.emplace_back(
      CurrentCodePos());
  const uint32_t current_code_offset = CurrentCodePos();
  Emit(&current_code_offset, sizeof(current_code_offset));
}
Referenced by DoEncodeInstruction().
EmitMemoryOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitMemoryOffset (uint64_t value) [inline], [private]
Definition at line 1643 of file wasm-interpreter.h.
                                               {
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_compact_bytecode) {
      printf("EmitMemoryOffset %llu\n", value);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    if (handler_size_ == InstrHandlerSize::Small) {
      if (V8_UNLIKELY(value > 0xffffffff)) {
        current_instr_encoding_failed_ = true;
      } else {
        uint32_t u32 = static_cast<uint32_t>(value);
        Emit(&u32, sizeof(u32));
        emitted_short_memory_offset_count_++;
      }
    } else {
      DCHECK_EQ(handler_size_, InstrHandlerSize::Large);
      Emit(&value, sizeof(value));
    }
  }
References current_instr_encoding_failed_, DCHECK_EQ, Emit(), emitted_short_memory_offset_count_, handler_size_, v8::internal::wasm::Large, v8::internal::wasm::Small, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
Referenced by DoEncodeInstruction(), and DoEncodeSuperInstruction().
EmitRefStackIndex()
void v8::internal::wasm::WasmBytecodeGenerator::EmitRefStackIndex (int32_t value) [inline], [private]
Definition at line 1665 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
Referenced by CopyToSlot(), DoEncodeInstruction(), EmitCopySlot(), and RefPop().
EmitRefValueType()
void v8::internal::wasm::WasmBytecodeGenerator::EmitRefValueType (int32_t value) [inline], [private]
Definition at line 1666 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
Referenced by DoEncodeInstruction().
EmitSlotOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitSlotOffset (uint32_t value) [inline], [private]
Definition at line 1623 of file wasm-interpreter.h.
                                             {
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_compact_bytecode) {
      printf("EmitSlotOffset %d\n", value);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    if (handler_size_ == InstrHandlerSize::Small) {
      if (V8_UNLIKELY(value > 0xffff)) {
        current_instr_encoding_failed_ = true;
      } else {
        uint16_t u16 = static_cast<uint16_t>(value);
        Emit(&u16, sizeof(u16));
        emitted_short_slot_offset_count_++;
      }
    } else {
      DCHECK_EQ(handler_size_, InstrHandlerSize::Large);
      Emit(&value, sizeof(value));
    }
  }
References current_instr_encoding_failed_, DCHECK_EQ, Emit(), emitted_short_slot_offset_count_, handler_size_, v8::internal::wasm::Large, v8::internal::wasm::Small, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
Referenced by CopyToSlot(), DoEncodeInstruction(), EmitCopySlot(), FindSharedSlot(), InitSlotsForFunctionArgs(), Pop(), RestoreIfElseParams(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
EmitStackIndex()
void v8::internal::wasm::WasmBytecodeGenerator::EmitStackIndex (int32_t value) [inline], [private]
Definition at line 1664 of file wasm-interpreter.h.
{ Emit(&value, sizeof(value)); }
References Emit(), and v8::internal::value.
Referenced by DoEncodeInstruction(), FindSharedSlot(), RestoreIfElseParams(), Return(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
EmitStructFieldOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitStructFieldOffset (int32_t value) [inline], [private]
Definition at line 1667 of file wasm-interpreter.h.
                                                   {
    Emit(&value, sizeof(value));
  }
References Emit(), and v8::internal::value.
Referenced by DoEncodeInstruction().
EmitTryCatchBranchOffset()
void v8::internal::wasm::WasmBytecodeGenerator::EmitTryCatchBranchOffset () [inline], [private]
Definition at line 562 of file wasm-interpreter-inl.h.
                                                            {
  // Initially emits offset to jump the end of the 'try/catch' blocks. When we
  // meet the corresponding 'end' instruction later, this offset needs to be
  // updated with the offset to the 'end' instruction.
  blocks_[current_block_index_].branch_code_offsets_.emplace_back(
      CurrentCodePos());
  const uint32_t current_code_offset = CurrentCodePos();
  Emit(&current_code_offset, sizeof(current_code_offset));
}
Referenced by DoEncodeInstruction().
EncodeInstruction()
RegMode v8::internal::wasm::WasmBytecodeGenerator::EncodeInstruction (const WasmInstruction & instr, RegMode curr_reg_mode, RegMode next_reg_mode) [private]
Definition at line 9323 of file wasm-interpreter.cc.
                                                                        {
  if (!v8_flags.drumbrake_compact_bytecode) {
    DCHECK_EQ(handler_size_, InstrHandlerSize::Large);
    return DoEncodeInstruction(instr, curr_reg_mode, next_reg_mode);
  }
  size_t current_instr_code_offset = code_.size();
  size_t current_slots_size = slots_.size();
  current_instr_encoding_failed_ = false;
  handler_size_ = InstrHandlerSize::Small;
  stack_.clear_history();
  RegMode reg_mode = DoEncodeInstruction(instr, curr_reg_mode, next_reg_mode);
  if (current_instr_encoding_failed_) {
    DCHECK(!HasSideEffects(instr.opcode));
    code_.resize(current_instr_code_offset);
    slots_.resize(current_slots_size);
    stack_.rollback();
    current_instr_encoding_failed_ = false;
    handler_size_ = InstrHandlerSize::Large;
    reg_mode = DoEncodeInstruction(instr, curr_reg_mode, next_reg_mode);
    DCHECK(!current_instr_encoding_failed_);
  }
  return reg_mode;
}
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::clear_history(), code_, current_instr_encoding_failed_, v8::internal::DCHECK(), DCHECK_EQ, DoEncodeInstruction(), handler_size_, v8::internal::wasm::Large, v8::internal::wasm::WasmInstruction::opcode, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::rollback(), slots_, v8::internal::wasm::Small, stack_, and v8::internal::v8_flags.
Referenced by GenerateBytecode().
EncodeSuperInstruction()
bool v8::internal::wasm::WasmBytecodeGenerator::EncodeSuperInstruction (RegMode & reg_mode, const WasmInstruction & curr_instr, const WasmInstruction & next_instr) [private]
Definition at line 12742 of file wasm-interpreter.cc.
                                       {
  if (!v8_flags.drumbrake_compact_bytecode) {
    DCHECK_EQ(handler_size_, InstrHandlerSize::Large);
    return DoEncodeSuperInstruction(reg_mode, curr_instr, next_instr);
  }
  size_t current_instr_code_offset = code_.size();
  size_t current_slots_size = slots_.size();
  current_instr_encoding_failed_ = false;
  handler_size_ = InstrHandlerSize::Small;
  stack_.clear_history();
  bool result = DoEncodeSuperInstruction(reg_mode, curr_instr, next_instr);
  if (result && current_instr_encoding_failed_) {
    code_.resize(current_instr_code_offset);
    slots_.resize(current_slots_size);
    stack_.rollback();
    current_instr_encoding_failed_ = false;
    handler_size_ = InstrHandlerSize::Large;
    result = DoEncodeSuperInstruction(reg_mode, curr_instr, next_instr);
    DCHECK(!current_instr_encoding_failed_);
  }
  return result;
}
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::clear_history(), code_, current_instr_encoding_failed_, v8::internal::DCHECK(), DCHECK_EQ, DoEncodeSuperInstruction(), handler_size_, v8::internal::wasm::Large, v8::base::internal::result, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::rollback(), slots_, v8::internal::wasm::Small, stack_, and v8::internal::v8_flags.
Referenced by GenerateBytecode().
EndBlock()
int32_t v8::internal::wasm::WasmBytecodeGenerator::EndBlock (WasmOpcode opcode) [private]
Definition at line 7928 of file wasm-interpreter.cc.
                                                         {
  WasmBytecodeGenerator::BlockData& block_data = blocks_[current_block_index_];
  bool is_try_catch =
      block_data.IsTry() || block_data.IsCatch() || block_data.IsCatchAll();
  StoreBlockParamsAndResultsIntoSlots(current_block_index_, opcode);
  block_data.end_code_offset_ = CurrentCodePos();
  if (opcode == kExprEnd && block_data.IsElse()) {
    DCHECK_GT(block_data.if_else_block_index_, 0);
    blocks_[block_data.if_else_block_index_].end_code_offset_ =
        CurrentCodePos();
  }
  if (!is_try_catch) {
    current_block_index_ = blocks_[current_block_index_].parent_block_index_;
  }
  if (is_try_catch && (opcode == kExprEnd || opcode == kExprDelegate)) {
    int32_t try_block_index =
        eh_data_.EndTryCatchBlocks(current_block_index_, CurrentCodePos());
    DCHECK_GE(try_block_index, 0);
    current_block_index_ = blocks_[try_block_index].parent_block_index_;
  }
  last_instr_offset_ = kInvalidCodeOffset;
  return current_block_index_;
}
References blocks_, current_block_index_, CurrentCodePos(), DCHECK_GE, DCHECK_GT, eh_data_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::end_code_offset_, v8::internal::wasm::WasmEHDataGenerator::EndTryCatchBlocks(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::if_else_block_index_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsCatch(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsCatchAll(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsElse(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsTry(), kInvalidCodeOffset, last_instr_offset_, and StoreBlockParamsAndResultsIntoSlots().
Referenced by DoEncodeInstruction().
F32Pop()
void v8::internal::wasm::WasmBytecodeGenerator::F32Pop (bool emit = true) [inline], [private]
Definition at line 1582 of file wasm-interpreter.h.
{ Pop(kF32, emit); }
References v8::internal::kF32, and Pop().
Referenced by DoEncodeInstruction().
F32Push()
void v8::internal::wasm::WasmBytecodeGenerator::F32Push (bool emit = true) [inline], [private]
Definition at line 373 of file wasm-interpreter-inl.h.
                                                    {
  uint32_t slot_index = _PushSlot(kWasmF32);
  uint32_t slot_offset = slots_[slot_index].slot_offset;
  if (emit) EmitSlotOffset(slot_offset);
}
References v8::internal::wasm::kWasmF32.
Referenced by DoEncodeInstruction().
F64Pop()
void v8::internal::wasm::WasmBytecodeGenerator::F64Pop (bool emit = true) [inline], [private]
Definition at line 1583 of file wasm-interpreter.h.
{ Pop(kF64, emit); }
References v8::internal::kF64, and Pop().
Referenced by DoEncodeInstruction().
F64Push()
void v8::internal::wasm::WasmBytecodeGenerator::F64Push (bool emit = true) [inline], [private]
Definition at line 379 of file wasm-interpreter-inl.h.
                                                    {
  uint32_t slot_index = _PushSlot(kWasmF64);
  uint32_t slot_offset = slots_[slot_index].slot_offset;
  if (emit) EmitSlotOffset(slot_offset);
}
References v8::internal::wasm::kWasmF64.
Referenced by DoEncodeInstruction().
FindSharedSlot()
bool v8::internal::wasm::WasmBytecodeGenerator::FindSharedSlot (uint32_t stack_index, uint32_t * new_slot_index) [private]
Definition at line 7463 of file wasm-interpreter.cc.
                                                                     {
  *new_slot_index = UINT_MAX;
  ValueType value_type = slots_[stack_[stack_index]].value_type;
  if (value_type.is_reference()) return false;
  // Only consider stack entries added in the current block.
  // We don't need to consider ancestor blocks because if a block has a
  // non-empty signature we always pass arguments and results into separate
  // slots, emitting CopySlot operations.
  uint32_t start_slot_index = blocks_[current_block_index_].stack_size_;
  for (uint32_t i = start_slot_index; i < stack_.size(); i++) {
    if (stack_[i] == stack_[stack_index]) {
      // Allocate new slot to preserve the old value of a shared slot.
      *new_slot_index = CreateSlot(value_type);
      break;
    }
  }
  if (*new_slot_index == UINT_MAX) return false;
  // If there was a collision and we allocated a new slot to preserve the old
  // value, we need to do two things to keep the state up to date:
  // 1. For each shared slot, we update the stack value to refer to the new
  // slot. This track the change at bytecode generation time.
  // 2. We return {true} to indicate that the slot was shared and the caller
  // should emit a 's2s_PreserveCopySlot...' instruction to copy the old slot
  // value into the new slot, at runtime.
  // This loop works because stack_index is always greater or equal to the index
  // of args/globals.
  DCHECK_GT(start_slot_index, stack_index);
  for (uint32_t i = start_slot_index; i < stack_.size(); i++) {
    if (stack_[i] == stack_[stack_index]) {
      // Copy value into the new slot.
      UpdateStack(i, *new_slot_index);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      if (v8_flags.trace_drumbrake_execution &&
          v8_flags.trace_drumbrake_execution_verbose) {
        START_EMIT_INSTR_HANDLER_WITH_ID(trace_UpdateStack) {
          EmitStackIndex(i);
          EmitSlotOffset(slots_[*new_slot_index].slot_offset * kSlotSize);
          printf("Preserve UpdateStack: [%d] = %d\n", i,
                 slots_[*new_slot_index].slot_offset);
        }
        END_EMIT_INSTR_HANDLER()
      }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    }
  }
  return true;
}
References blocks_, CreateSlot(), current_block_index_, DCHECK_GT, EmitSlotOffset(), EmitStackIndex(), END_EMIT_INSTR_HANDLER, v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), slots_, stack_, START_EMIT_INSTR_HANDLER_WITH_ID, UpdateStack(), v8::internal::v8_flags, and v8::internal::wasm::value_type().
Referenced by CopyToSlot(), and PreserveArgsAndLocals().
function_index()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::function_index () const [inline], [private]
Definition at line 1753 of file wasm-interpreter.h.
{ return function_index_; }
References function_index_.
Referenced by DoEncodeInstruction(), and WasmBytecodeGenerator().
GenerateBytecode()
std::unique_ptr< WasmBytecode > v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode ()
Definition at line 12964 of file wasm-interpreter.cc.
                                                                    {
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  if (v8_flags.trace_drumbrake_bytecode_generator) {
    printf("\nGenerate bytecode for function: %d\n", function_index_);
  }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  uint32_t const_slots = ScanConstInstructions();
  const_slots_values_.resize(const_slots * kSlotSize);
  pc_t pc = wasm_code_->locals.encoded_size;
  RegMode reg_mode = RegMode::kNoReg;
  Decoder decoder(wasm_code_->start, wasm_code_->end);
  current_block_index_ = -1;
  // Init stack_ with return values, args and local types.
  for (uint32_t index = 0; index < return_count_; index++) {
    CreateSlot(wasm_code_->function->sig->GetReturn(index));
  }
  for (uint32_t index = 0; index < args_count_; index++) {
    _PushSlot(wasm_code_->function->sig->GetParam(index));
  }
  // Reserve space for const slots
  slot_offset_ += const_slots;
  for (uint32_t index = 0; index < wasm_code_->locals.num_locals; index++) {
    _PushSlot(wasm_code_->locals.local_types[index]);
  }
  current_block_index_ = BeginBlock(
      kExprBlock,
      {wasm_code_->function->sig_index, kWasmBottom.raw_bit_field()});
  WasmInstruction curr_instr;
  WasmInstruction next_instr;
  pc_t limit = wasm_code_->end - wasm_code_->start;
  while (pc < limit) {
    DCHECK_NOT_NULL(wasm_code_->start);
    if (!curr_instr) {
      curr_instr = DecodeInstruction(pc, decoder);
      if (curr_instr) pc += curr_instr.length;
    }
    if (!curr_instr) break;
    DCHECK(!next_instr);
    next_instr = DecodeInstruction(pc, decoder);
    if (next_instr) pc += next_instr.length;
    if (next_instr) {
      if (v8_flags.drumbrake_super_instructions && is_instruction_reachable_ &&
          EncodeSuperInstruction(reg_mode, curr_instr, next_instr)) {
        curr_instr = {};
        next_instr = {};
      } else {
        reg_mode =
            EncodeInstruction(curr_instr, reg_mode, next_instr.InputRegMode());
        curr_instr = next_instr;
        next_instr = {};
      }
    } else {
      reg_mode = EncodeInstruction(curr_instr, reg_mode, RegMode::kNoReg);
      curr_instr = {};
    }
    if (pc == limit && curr_instr) {
      reg_mode = EncodeInstruction(curr_instr, reg_mode, RegMode::kNoReg);
    }
  }
  PatchLoopBeginInstructions();
  PatchBranchOffsets();
  total_bytecode_size_ += code_.size();
  CanonicalTypeIndex canonical_sig_index =
      module_->canonical_sig_id(module_->functions[function_index_].sig_index);
  const CanonicalSig* canonicalized_sig =
      GetTypeCanonicalizer()->LookupFunctionSignature(canonical_sig_index);
  return std::make_unique<WasmBytecode>(
      function_index_, code_.data(), code_.size(), slot_offset_,
      module_->functions[function_index_].sig, canonicalized_sig, wasm_code_,
      blocks_.size(), const_slots_values_.data(), const_slots_values_.size(),
      ref_slots_count_, std::move(eh_data_), std::move(code_pc_map_));
}
References _PushSlot(), args_count_, BeginBlock(), blocks_, v8::internal::wasm::WasmModule::canonical_sig_id(), code_, code_pc_map_, const_slots_values_, CreateSlot(), current_block_index_, v8::internal::DCHECK(), DCHECK_NOT_NULL, DecodeInstruction(), eh_data_, v8::internal::wasm::BodyLocalDecls::encoded_size, EncodeInstruction(), EncodeSuperInstruction(), v8::internal::wasm::InterpreterCode::end, v8::internal::wasm::InterpreterCode::function, function_index_, v8::internal::wasm::WasmModule::functions, v8::internal::Signature< T >::GetParam(), v8::internal::Signature< T >::GetReturn(), v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::index, v8::internal::wasm::WasmInstruction::InputRegMode(), is_instruction_reachable_, v8::internal::wasm::kNoReg, v8::internal::wasm::kSlotSize, v8::internal::wasm::kWasmBottom, v8::internal::wasm::WasmInstruction::length, v8::internal::wasm::BodyLocalDecls::local_types, v8::internal::wasm::InterpreterCode::locals, v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), module_, v8::internal::wasm::BodyLocalDecls::num_locals, PatchBranchOffsets(), PatchLoopBeginInstructions(), v8::internal::wasm::ValueTypeBase::raw_bit_field(), ref_slots_count_, return_count_, ScanConstInstructions(), v8::internal::wasm::WasmFunction::sig, v8::internal::wasm::WasmFunction::sig_index, slot_offset_, v8::internal::wasm::InterpreterCode::start, total_bytecode_size_, v8::internal::v8_flags, and wasm_code_.
Referenced by v8::internal::wasm::WasmInterpreter::CodeMap::Preprocess().
GetConstSlot()
template<typename T >
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetConstSlot (T value) [inline], [private]
Definition at line 1799 of file wasm-interpreter.h.
                                        {
    if constexpr (std::is_same_v<T, int32_t>) {
      return GetI32ConstSlot(value);
    }
    if constexpr (std::is_same_v<T, int64_t>) {
      return GetI64ConstSlot(value);
    }
    if constexpr (std::is_same_v<T, float>) {
      return GetF32ConstSlot(value);
    }
    if constexpr (std::is_same_v<T, double>) {
      return GetF64ConstSlot(value);
    }
    if constexpr (std::is_same_v<T, Simd128>) {
      return GetS128ConstSlot(value);
    }
    UNREACHABLE();
  }
References GetF32ConstSlot(), GetF64ConstSlot(), GetI32ConstSlot(), GetI64ConstSlot(), GetS128ConstSlot(), v8::internal::UNREACHABLE(), and v8::internal::value.
Referenced by CreateConstSlot().
GetCurrentBranchDepth()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetCurrentBranchDepth () const [inline], [private]
Definition at line 512 of file wasm-interpreter-inl.h.
                                                                   {
  DCHECK_GE(current_block_index_, 0);
  int index = blocks_[current_block_index_].parent_block_index_;
  uint32_t depth = 0;
  while (index >= 0) {
    depth++;
    index = blocks_[index].parent_block_index_;
  }
  return depth;
}
References DCHECK_GE, and v8::internal::index.
GetCurrentTryBlockIndex()
int v8::internal::wasm::WasmBytecodeGenerator::GetCurrentTryBlockIndex (bool return_matching_try_for_catch_blocks) const [private]
Definition at line 13098 of file wasm-interpreter.cc.
                                                     {
  DCHECK_GE(current_block_index_, 0);
  int index = current_block_index_;
  while (index >= 0) {
    const auto& block = blocks_[index];
    if (block.IsTry()) return index;
    if (return_matching_try_for_catch_blocks &&
        (block.IsCatch() || block.IsCatchAll())) {
      return block.parent_try_block_index_;
    }
    index = blocks_[index].parent_block_index_;
  }
  return -1;
}
References blocks_, current_block_index_, DCHECK_GE, and v8::internal::index.
Referenced by DoEncodeInstruction().
GetF32ConstSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetF32ConstSlot (float value) [inline], [private]
Definition at line 1831 of file wasm-interpreter.h.
                                               {
    auto it = f32_const_cache_.find(value);
    if (it != f32_const_cache_.end()) {
      return it->second;
    }
    return UINT_MAX;
  }
References f32_const_cache_, and v8::internal::value.
Referenced by GetConstSlot().
GetF64ConstSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetF64ConstSlot (double value) [inline], [private]
Definition at line 1838 of file wasm-interpreter.h.
                                                {
    auto it = f64_const_cache_.find(value);
    if (it != f64_const_cache_.end()) {
      return it->second;
    }
    return UINT_MAX;
  }
References f64_const_cache_, and v8::internal::value.
Referenced by GetConstSlot().
GetFunctionSignature()
const FunctionSig * v8::internal::wasm::WasmBytecodeGenerator::GetFunctionSignature (uint32_t function_index) const [inline], [private]
Definition at line 586 of file wasm-interpreter-inl.h.
                                   {
  return module_->functions[function_index].sig;
}
Referenced by DoEncodeInstruction().
GetGlobalType()
ValueKind v8::internal::wasm::WasmBytecodeGenerator::GetGlobalType (uint32_t index) const [inline], [private]
Definition at line 496 of file wasm-interpreter-inl.h.
                                                                          {
  return module_->globals[index].type.kind();
}
References v8::internal::index.
Referenced by DoEncodeInstruction().
GetI32ConstSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetI32ConstSlot (int32_t value) [inline], [private]
Definition at line 1817 of file wasm-interpreter.h.
                                                 {
    auto it = i32_const_cache_.find(value);
    if (it != i32_const_cache_.end()) {
      return it->second;
    }
    return UINT_MAX;
  }
References i32_const_cache_, and v8::internal::value.
Referenced by GetConstSlot().
GetI64ConstSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetI64ConstSlot (int64_t value) [inline], [private]
Definition at line 1824 of file wasm-interpreter.h.
                                                 {
    auto it = i64_const_cache_.find(value);
    if (it != i64_const_cache_.end()) {
      return it->second;
    }
    return UINT_MAX;
  }
References i64_const_cache_, and v8::internal::value.
Referenced by GetConstSlot().
GetParamType()
ValueType v8::internal::wasm::WasmBytecodeGenerator::GetParamType (const WasmBytecodeGenerator::BlockData & block_data, size_t index) const [inline], [private]
Definition at line 465 of file wasm-interpreter-inl.h.
                                                                          {
  DCHECK(block_data.signature_.is_bottom());
  const FunctionSig* sig = module_->signature(block_data.signature_.sig_index);
  return sig->GetParam(index);
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom(), v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, and v8::internal::wasm::WasmBytecodeGenerator::BlockData::signature_.
Referenced by RestoreIfElseParams(), and StoreBlockParamsIntoSlots().
GetReturnType()
ValueType v8::internal::wasm::WasmBytecodeGenerator::GetReturnType (const WasmBytecodeGenerator::BlockData & block_data, size_t index) const [inline], [private]
Definition at line 484 of file wasm-interpreter-inl.h.
                                                                          {
  DCHECK_NE(block_data.signature_.value_type(), kWasmVoid);
  if (block_data.signature_.is_bottom()) {
    const FunctionSig* sig =
        module_->signature(block_data.signature_.sig_index);
    return sig->GetReturn(index);
  }
  DCHECK_EQ(index, 0);
  return block_data.signature_.value_type();
}
References DCHECK_EQ, DCHECK_NE, v8::internal::index, v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom(), v8::internal::wasm::kWasmVoid, v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, v8::internal::wasm::WasmBytecodeGenerator::BlockData::signature_, and v8::internal::wasm::WasmInstruction::Optional::Block::value_type().
Referenced by StoreBlockParamsAndResultsIntoSlots().
GetS128ConstSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetS128ConstSlot (Simd128 value) [inline], [private]
Definition at line 1845 of file wasm-interpreter.h.
                                                  {
    auto it = s128_const_cache_.find(reinterpret_cast<Simd128&>(value));
    if (it != s128_const_cache_.end()) {
      return it->second;
    }
    return UINT_MAX;
  }
References s128_const_cache_, and v8::internal::value.
Referenced by GetConstSlot().
GetStackFrameSize()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::GetStackFrameSize () const [inline], [private]
Definition at line 1529 of file wasm-interpreter.h.
{ return slot_offset_; }
References slot_offset_.
Referenced by DoEncodeInstruction().
GetTargetBranch()
int32_t v8::internal::wasm::WasmBytecodeGenerator::GetTargetBranch (uint32_t delta) const [inline], [private]
Definition at line 523 of file wasm-interpreter-inl.h.
                                                                          {
  int index = current_block_index_;
  while (delta--) {
    DCHECK_GE(index, 0);
    index = blocks_[index].parent_block_index_;
  }
  return index;
}
References DCHECK_GE, and v8::internal::index.
Referenced by DoEncodeInstruction().
GetTopStackType()
ValueKind v8::internal::wasm::WasmBytecodeGenerator::GetTopStackType (RegMode reg_mode) const [inline], [private]
Definition at line 591 of file wasm-interpreter-inl.h.
                            {
  switch (reg_mode) {
    case RegMode::kNoReg:
      if (stack_.empty()) return kI32; // not used
      return slots_[stack_[stack_top_index()]].kind();
    case RegMode::kI32Reg:
      return kI32;
    case RegMode::kI64Reg:
      return kI64;
    case RegMode::kF32Reg:
      return kF32;
    case RegMode::kF64Reg:
      return kF64;
    case RegMode::kAnyReg:
    default:
      UNREACHABLE();
  }
}
References v8::internal::wasm::kAnyReg, v8::internal::kF32, v8::internal::wasm::kF32Reg, v8::internal::kF64, v8::internal::wasm::kF64Reg, v8::internal::kI32, v8::internal::wasm::kI32Reg, v8::internal::kI64, v8::internal::wasm::kI64Reg, v8::internal::wasm::kNoReg, and v8::internal::UNREACHABLE().
Referenced by DoEncodeInstruction().
HasSharedSlot()
bool v8::internal::wasm::WasmBytecodeGenerator::HasSharedSlot (uint32_t stack_index) const [private]
Definition at line 7443 of file wasm-interpreter.cc.
                                                                    {
  // Only consider stack entries added in the current block.
  // We don't need to consider ancestor blocks because if a block has a
  // non-empty signature we always pass arguments and results into separate
  // slots, emitting CopySlot operations.
  uint32_t start_slot_index = blocks_[current_block_index_].stack_size_;
  for (uint32_t i = start_slot_index; i < stack_.size(); i++) {
    if (stack_[i] == stack_[stack_index]) {
      return true;
    }
  }
  return false;
}
References blocks_, current_block_index_, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), and stack_.
Referenced by DoEncodeSuperInstruction().
HasVoidSignature()
bool v8::internal::wasm::WasmBytecodeGenerator::HasVoidSignature (const WasmBytecodeGenerator::BlockData & block_data) const [inline], [private]
Definition at line 443 of file wasm-interpreter-inl.h.
                                                            {
  if (block_data.signature_.is_bottom()) {
    const FunctionSig* sig =
        module_->signature(block_data.signature_.sig_index);
    return 0 == (sig->parameter_count() + sig->return_count());
  } else if (block_data.signature_.value_type() == kWasmVoid) {
    return true;
  }
  return false;
}
References v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom(), v8::internal::wasm::kWasmVoid, v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, v8::internal::wasm::WasmBytecodeGenerator::BlockData::signature_, and v8::internal::wasm::WasmInstruction::Optional::Block::value_type().
Referenced by DoEncodeInstruction().
I32Pop()
void v8::internal::wasm::WasmBytecodeGenerator::I32Pop (bool emit = true) [inline], [private]
Definition at line 1579 of file wasm-interpreter.h.
{ Pop(kI32, emit); }
References v8::internal::kI32, and Pop().
Referenced by DoEncodeInstruction(), and WasmBytecodeGenerator().
I32Push()
void v8::internal::wasm::WasmBytecodeGenerator::I32Push (bool emit = true) [inline], [private]
Definition at line 361 of file wasm-interpreter-inl.h.
                                                    {
  uint32_t slot_index = _PushSlot(kWasmI32);
  uint32_t slot_offset = slots_[slot_index].slot_offset;
  if (emit) EmitSlotOffset(slot_offset);
}
References v8::internal::wasm::kWasmI32.
Referenced by DoEncodeInstruction(), and WasmBytecodeGenerator().
I64Pop()
void v8::internal::wasm::WasmBytecodeGenerator::I64Pop (bool emit = true) [inline], [private]
Definition at line 1580 of file wasm-interpreter.h.
{ Pop(kI64, emit); }
References v8::internal::kI64, and Pop().
Referenced by DoEncodeInstruction(), and WasmBytecodeGenerator().
I64Push()
void v8::internal::wasm::WasmBytecodeGenerator::I64Push (bool emit = true) [inline], [private]
Definition at line 367 of file wasm-interpreter-inl.h.
                                                    {
  uint32_t slot_index = _PushSlot(kWasmI64);
  uint32_t slot_offset = slots_[slot_index].slot_offset;
  if (emit) EmitSlotOffset(slot_offset);
}
References v8::internal::wasm::kWasmI64.
Referenced by DoEncodeInstruction(), and WasmBytecodeGenerator().
InitSlotsForFunctionArgs()
void v8::internal::wasm::WasmBytecodeGenerator::InitSlotsForFunctionArgs (const FunctionSig * sig, bool is_indirect_call) [private]
Definition at line 8702 of file wasm-interpreter.cc.
                                                                            {
  size_t stack_index;
  if (is_indirect_call) {
    // Subtract one to discard the function index on the top of the stack.
    DCHECK_LE(sig->parameter_count(), stack_.size() - 1);
    stack_index = stack_.size() - sig->parameter_count() - 1;
  } else {
    DCHECK_LE(sig->parameter_count(), stack_.size());
    stack_index = stack_.size() - sig->parameter_count();
  }
  bool fast_path = sig->parameter_count() > 1 && sig->parameter_count() < 32 &&
                   !WasmBytecode::HasRefOrSimdArgs(sig);
  if (fast_path) {
    if (sig->parameter_count() == 2) {
      const ValueType type0 = sig->GetParam(0);
      const ValueKind kind0 = type0.kind();
      ValueType type1 = sig->GetParam(1);
      const ValueKind kind1 = type1.kind();
      uint32_t to = CreateSlot(type0);
      CreateSlot(type1);
      uint32_t copyslot32_two_args_func_id =
          ((kind0 == kI64 || kind0 == kF64) ? 0x01 : 0x00) |
          ((kind1 == kI64 || kind1 == kF64) ? 0x02 : 0x00);
      static const InstructionHandler kCopySlot32TwoArgFuncs[4] = {
          k_s2s_CopySlot_ll, k_s2s_CopySlot_lq, k_s2s_CopySlot_ql,
          k_s2s_CopySlot_qq};
      START_EMIT_INSTR_HANDLER() {
        EmitFnId(kCopySlot32TwoArgFuncs[copyslot32_two_args_func_id]);
        EmitSlotOffset(slots_[to].slot_offset);
        EmitSlotOffset(slots_[stack_[stack_index]].slot_offset);
        stack_index++;
        EmitSlotOffset(slots_[stack_[stack_index]].slot_offset);
        stack_index++;
      }
      END_EMIT_INSTR_HANDLER()
    } else {
      START_EMIT_INSTR_HANDLER_WITH_ID(s2s_CopySlotMulti) {
        EmitI32Const(static_cast<uint32_t>(sig->parameter_count()));
        uint32_t arg_size_mask = 0;
        for (size_t index = 0; index < sig->parameter_count(); index++) {
          const ValueType value_type = sig->GetParam(index);
          const ValueKind kind = value_type.kind();
          if (kind == kI64 || kind == kF64) {
            arg_size_mask |= (1 << index);
          }
        }
        EmitI32Const(arg_size_mask);
        uint32_t to = 0;
        for (size_t index = 0; index < sig->parameter_count(); index++) {
          const ValueType value_type = sig->GetParam(index);
          to = CreateSlot(value_type);
          if (index == 0) {
            EmitSlotOffset(slots_[to].slot_offset);
          }
          EmitSlotOffset(slots_[stack_[stack_index]].slot_offset);
          stack_index++;
        }
      }
      END_EMIT_INSTR_HANDLER()
    }
  } else {
    // Slow path.
    for (size_t index = 0; index < sig->parameter_count(); index++) {
      ValueType value_type = sig->GetParam(index);
      uint32_t to = CreateSlot(value_type);
      EmitCopySlot(value_type, stack_[stack_index], to);
      stack_index++;
    }
  }
}
References CreateSlot(), DCHECK_LE, EmitCopySlot(), EmitFnId(), EmitI32Const(), EmitSlotOffset(), END_EMIT_INSTR_HANDLER, v8::internal::wasm::WasmBytecode::HasRefOrSimdArgs(), v8::internal::index, v8::internal::kF64, v8::internal::kI64, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::sig, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), slots_, stack_, START_EMIT_INSTR_HANDLER, START_EMIT_INSTR_HANDLER_WITH_ID, and v8::internal::wasm::value_type().
Referenced by DoEncodeInstruction().
IsMemory64()
bool v8::internal::wasm::WasmBytecodeGenerator::IsMemory64 () const [inline], [private]
Definition at line 500 of file wasm-interpreter-inl.h.
                                                    {
  return !module_->memories.empty() && module_->memories[0].is_memory64();
}
Referenced by WasmBytecodeGenerator().
IsMultiMemory()
bool v8::internal::wasm::WasmBytecodeGenerator::IsMultiMemory () const [inline], [private]
Definition at line 504 of file wasm-interpreter-inl.h.
                                                       {
  return module_->memories.size() > 1;
}
ITableIndexPush()
void v8::internal::wasm::WasmBytecodeGenerator::ITableIndexPush (bool is_table64, bool emit = true) [inline], [private]
MemIndexPop()
void v8::internal::wasm::WasmBytecodeGenerator::MemIndexPop (bool emit = true) [inline], [private]
Definition at line 1581 of file wasm-interpreter.h.
{ (this->*int_mem_pop_)(emit); }
References int_mem_pop_.
Referenced by DoEncodeInstruction(), and DoEncodeSuperInstruction().
MemIndexPush()
void v8::internal::wasm::WasmBytecodeGenerator::MemIndexPush (bool emit = true) [inline], [private]
Definition at line 1571 of file wasm-interpreter.h.
{ (this->*int_mem_push_)(emit); }
References int_mem_push_.
Referenced by DoEncodeInstruction().
operator=()
WasmBytecodeGenerator& v8::internal::wasm::WasmBytecodeGenerator::operator= (const WasmBytecodeGenerator &) [private], [delete]
ParamsCount()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::ParamsCount (const WasmBytecodeGenerator::BlockData & block_data) const [inline], [private]
Definition at line 455 of file wasm-interpreter-inl.h.
                                                            {
  if (block_data.signature_.is_bottom()) {
    const FunctionSig* sig =
        module_->signature(block_data.signature_.sig_index);
    return static_cast<uint32_t>(sig->parameter_count());
  }
  return 0;
}
References v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom(), v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, and v8::internal::wasm::WasmBytecodeGenerator::BlockData::signature_.
Referenced by DoEncodeInstruction(), RestoreIfElseParams(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
PatchBranchOffsets()
void v8::internal::wasm::WasmBytecodeGenerator::PatchBranchOffsets () [private]
Definition at line 13124 of file wasm-interpreter.cc.
                                               {
  static const uint32_t kElseBlockStartOffset =
      sizeof(InstructionHandler) + sizeof(uint32_t);
  for (int block_index = 0; block_index < static_cast<int>(blocks_.size());
       block_index++) {
    const BlockData block_data = blocks_[block_index];
    for (size_t i = 0; i < block_data.branch_code_offsets_.size(); i++) {
      uint32_t current_code_offset = block_data.branch_code_offsets_[i];
      uint32_t target_offset = block_data.end_code_offset_;
      if (block_data.IsLoop()) {
        target_offset = block_data.begin_code_offset_;
      } else if (block_data.IsIf() && block_data.if_else_block_index_ >= 0 &&
                 current_code_offset == block_data.begin_code_offset_) {
        // Jumps to the 'else' branch.
        target_offset =
            blocks_[block_data.if_else_block_index_].begin_code_offset_ +
            kElseBlockStartOffset;
      } else if ((block_data.IsCatch() || block_data.IsCatchAll()) &&
                 current_code_offset == block_data.begin_code_offset_ +
                                            sizeof(InstructionHandler)) {
        // Jumps to the end of a sequence of 'try'/'catch' branches.
        target_offset = static_cast<uint32_t>(
            eh_data_.GetEndInstructionOffsetFor(block_index));
      }
      int32_t delta = target_offset - current_code_offset;
      base::WriteUnalignedValue<uint32_t>(
          reinterpret_cast<Address>(code_.data() + current_code_offset), delta);
    }
  }
}
References v8::internal::wasm::WasmBytecodeGenerator::BlockData::begin_code_offset_, blocks_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::branch_code_offsets_, code_, eh_data_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::end_code_offset_, v8::internal::wasm::WasmEHData::GetEndInstructionOffsetFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::WasmBytecodeGenerator::BlockData::if_else_block_index_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsCatch(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsCatchAll(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsIf(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::IsLoop(), and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by GenerateBytecode().
PatchLoopBeginInstructions()
void v8::internal::wasm::WasmBytecodeGenerator::PatchLoopBeginInstructions () [private]
Definition at line 13114 of file wasm-interpreter.cc.
                                                       {
  if (ref_slots_count_ == 0) {
    for (size_t i = 0; i < loop_begin_code_offsets_.size(); i++) {
      base::WriteUnalignedValue<InstructionHandler>(
          reinterpret_cast<Address>(code_.data() + loop_begin_code_offsets_[i]),
          k_s2s_OnLoopBeginNoRefSlots);
    }
  }
}
References code_, loop_begin_code_offsets_, ref_slots_count_, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by GenerateBytecode().
Pop()
void v8::internal::wasm::WasmBytecodeGenerator::Pop (ValueKind kind, bool emit = true) [inline], [private]
Definition at line 1608 of file wasm-interpreter.h.
                                                    {
    if (kind == kRefNull || kind == kRef) {
      RefPop(emit);
      return;
    }
    DCHECK(CheckEqualKind(kind, slots_[stack_.back()].kind()));
    uint32_t slot_offset = PopSlot();
    if (emit) EmitSlotOffset(slot_offset);
  }
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back(), v8::internal::DCHECK(), EmitSlotOffset(), v8::internal::kRef, v8::internal::kRefNull, PopSlot(), RefPop(), slots_, and stack_.
Referenced by DoEncodeInstruction(), F32Pop(), F64Pop(), I32Pop(), I64Pop(), and S128Pop().
PopSlot()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::PopSlot () [inline], [private]
Definition at line 1906 of file wasm-interpreter.h.
                            {
    // TODO(paolosev@microsoft.com) - We should try to mark as 'invalid' and
    // later reuse slots in the stack once we are sure they won't be referred
    // again, which should be the case once a slot is popped. This could make
    // the stack frame size smaller, especially for large Wasm functions.
    uint32_t slot_offset = slots_[stack_.back()].slot_offset;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_bytecode_generator &&
        v8_flags.trace_drumbrake_execution_verbose) {
      printf(" pop - slot[%d] = %d\n", stack_size() - 1, stack_.back());
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    stack_.pop_back();
    return slot_offset;
  }
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::pop_back(), slots_, stack_, stack_size(), and v8::internal::v8_flags.
Referenced by CopyToSlotAndPop(), Pop(), and RefPop().
PreserveArgsAndLocals()
void v8::internal::wasm::WasmBytecodeGenerator::PreserveArgsAndLocals () [private]
Definition at line 7724 of file wasm-interpreter.cc.
                                                  {
  uint32_t num_args_and_locals = args_count_ + locals_count_;
  // If there are only args/locals entries in the stack, nothing to do.
  if (num_args_and_locals >= stack_size()) return;
  for (uint32_t local_index = 0; local_index < num_args_and_locals;
       ++local_index) {
    uint32_t new_slot_index;
    if (FindSharedSlot(local_index, &new_slot_index)) {
      ValueType value_type = slots_[stack_[local_index]].value_type;
      EmitCopySlot(value_type, stack_[local_index], new_slot_index);
    }
  }
}
References args_count_, EmitCopySlot(), FindSharedSlot(), locals_count_, slots_, stack_, stack_size(), and v8::internal::wasm::value_type().
Referenced by DoEncodeInstruction().
PrintBytecodeCompressionStats()
void v8::internal::wasm::WasmBytecodeGenerator::PrintBytecodeCompressionStats () [static]
Definition at line 8689 of file wasm-interpreter.cc.
                                                          {
  size_t total_bytecode_size = std::atomic_load(&total_bytecode_size_);
  printf("Total bytecode size: %zu bytes.\n", total_bytecode_size);
  size_t space_saved_in_bytes =
      2 * std::atomic_load(&emitted_short_slot_offset_count_) +
      4 * std::atomic_load(&emitted_short_memory_offset_count_);
  double saved_pct = (total_bytecode_size + space_saved_in_bytes == 0)
                         ? .0
                         : 100.0 * space_saved_in_bytes /
                               (total_bytecode_size + space_saved_in_bytes);
  printf("Bytes saved: %zu (%.1f%%).\n", space_saved_in_bytes, saved_pct);
}
References emitted_short_memory_offset_count_, emitted_short_slot_offset_count_, and total_bytecode_size_.
Referenced by v8::internal::wasm::WasmInterpreter::GlobalTearDown().
Push()
void v8::internal::wasm::WasmBytecodeGenerator::Push (ValueType type) [inline], [private]
Definition at line 400 of file wasm-interpreter-inl.h.
                                                      {
  switch (type.kind()) {
    case kI32:
      I32Push();
      break;
    case kI64:
      I64Push();
      break;
    case kF32:
      F32Push();
      break;
    case kF64:
      F64Push();
      break;
    case kS128:
      S128Push();
      break;
    case kRef:
    case kRefNull:
      RefPush(type);
      break;
    default:
      UNREACHABLE();
  }
}
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
PushConstSlot() [1/2]
template<typename T >
uint32_t v8::internal::wasm::WasmBytecodeGenerator::PushConstSlot (T value) [inline], [private]
Definition at line 1875 of file wasm-interpreter.h.
                                         {
    uint32_t new_slot_index = CreateConstSlot(value);
    PushConstSlot(new_slot_index);
    return new_slot_index;
  }
References CreateConstSlot(), and v8::internal::value.
PushConstSlot() [2/2]
void v8::internal::wasm::WasmBytecodeGenerator::PushConstSlot (uint32_t slot_index) [inline], [private]
Definition at line 435 of file wasm-interpreter-inl.h.
                                                                    {
  PushSlot(slot_index);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  TracePushConstSlot(slot_index);
#endif // V8_ENABLE_DRUMBRAKE_TRACING
}
PushCopySlot()
void v8::internal::wasm::WasmBytecodeGenerator::PushCopySlot (uint32_t from_stack_index) [inline], [private]
Definition at line 426 of file wasm-interpreter-inl.h.
                                                                         {
  DCHECK_LT(from_stack_index, stack_.size());
  PushSlot(stack_[from_stack_index]);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
  TracePushCopySlot(from_stack_index);
#endif // V8_ENABLE_DRUMBRAKE_TRACING
}
References DCHECK_LT.
Referenced by DoEncodeInstruction().
PushSlot()
void v8::internal::wasm::WasmBytecodeGenerator::PushSlot (uint32_t slot_index) [inline], [private]
Definition at line 1885 of file wasm-interpreter.h.
                                            {
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_bytecode_generator &&
        v8_flags.trace_drumbrake_execution_verbose) {
      printf(" push - slot[%d] = %d\n", stack_size(), slot_index);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    stack_.push_back(slot_index);
  }
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::push_back(), stack_, stack_size(), and v8::internal::v8_flags.
Referenced by _PushSlot(), and DoEncodeInstruction().
RefPop()
ValueType v8::internal::wasm::WasmBytecodeGenerator::RefPop (bool emit = true) [inline], [private]
Definition at line 1586 of file wasm-interpreter.h.
                                            {
    DCHECK(wasm::is_reference(slots_[stack_.back()].kind()));
    uint32_t ref_index = slots_[stack_.back()].ref_stack_index;
    ValueType value_type = slots_[stack_.back()].value_type;
    DCHECK(value_type.is_object_reference());
    PopSlot();
    if (emit) EmitRefStackIndex(ref_index);
    return value_type;
  }
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::back(), v8::internal::DCHECK(), EmitRefStackIndex(), v8::internal::wasm::ValueTypeBase::is_object_reference(), v8::internal::wasm::is_reference(), PopSlot(), slots_, stack_, and v8::internal::wasm::value_type().
Referenced by DoEncodeInstruction(), and Pop().
RefPush()
void v8::internal::wasm::WasmBytecodeGenerator::RefPush (ValueType type, bool emit = true) [inline], [private]
Definition at line 391 of file wasm-interpreter-inl.h.
                                                                    {
  uint32_t slot_index = _PushSlot(type);
  uint32_t slot_offset = slots_[slot_index].slot_offset;
  if (emit) {
    EmitSlotOffset(slot_offset);
    EmitRefStackIndex(slots_[slot_index].ref_stack_index);
  }
}
References v8::internal::tracing::type.
Referenced by DoEncodeInstruction().
ReserveBlockSlots()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::ReserveBlockSlots (uint8_t opcode, const WasmInstruction::Optional::Block & block_data, size_t * rets_slots_count, size_t * params_slots_count) [private]
Definition at line 7740 of file wasm-interpreter.cc.
                                                          {
  uint32_t first_slot_index = 0;
  *rets_slots_count = 0;
  *params_slots_count = 0;
  bool first_slot_found = false;
  const ValueType value_type = block_data.value_type();
  if (value_type == kWasmBottom) {
    const FunctionSig* sig = module_->signature(block_data.sig_index);
    *rets_slots_count = sig->return_count();
    for (uint32_t i = 0; i < *rets_slots_count; i++) {
      uint32_t slot_index = CreateSlot(sig->GetReturn(i));
      if (!first_slot_found) {
        first_slot_index = slot_index;
        first_slot_found = true;
      }
    }
    *params_slots_count = sig->parameter_count();
    for (uint32_t i = 0; i < *params_slots_count; i++) {
      uint32_t slot_index = CreateSlot(sig->GetParam(i));
      if (!first_slot_found) {
        first_slot_index = slot_index;
        first_slot_found = true;
      }
    }
  } else if (value_type != kWasmVoid) {
    *rets_slots_count = 1;
    first_slot_index = CreateSlot(value_type);
  }
  return first_slot_index;
}
References CreateSlot(), v8::internal::wasm::kWasmBottom, v8::internal::wasm::kWasmVoid, module_, v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, v8::internal::wasm::WasmModule::signature(), v8::internal::wasm::value_type(), and v8::internal::wasm::WasmInstruction::Optional::Block::value_type().
Referenced by BeginBlock().
RestoreIfElseParams()
void v8::internal::wasm::WasmBytecodeGenerator::RestoreIfElseParams (uint32_t if_block_index) [private]
Definition at line 7880 of file wasm-interpreter.cc.
                                                                       {
  const WasmBytecodeGenerator::BlockData& if_block_data =
      blocks_[if_block_index];
  DCHECK_EQ(if_block_data.opcode_, kExprIf);
  stack_.resize(blocks_[if_block_index].stack_size_);
  uint32_t params_count = if_block_index == 0 ? 0 : ParamsCount(if_block_data);
  for (uint32_t i = 0; i < params_count; i++) {
    UpdateStack(if_block_data.stack_size_ - params_count + i,
                if_block_data.GetParam(i), GetParamType(if_block_data, i));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      START_EMIT_INSTR_HANDLER_WITH_ID(trace_UpdateStack) {
        EmitStackIndex(if_block_data.stack_size_ - params_count + i);
        EmitSlotOffset(slots_[if_block_data.GetParam(i)].slot_offset *
                       kSlotSize);
      }
      END_EMIT_INSTR_HANDLER()
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  }
}
References blocks_, DCHECK_EQ, EmitSlotOffset(), EmitStackIndex(), END_EMIT_INSTR_HANDLER, v8::internal::wasm::WasmBytecodeGenerator::BlockData::GetParam(), GetParamType(), v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecodeGenerator::BlockData::opcode_, ParamsCount(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::resize(), slots_, stack_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::stack_size_, START_EMIT_INSTR_HANDLER_WITH_ID, UpdateStack(), and v8::internal::v8_flags.
Return()
void v8::internal::wasm::WasmBytecodeGenerator::Return () [private]
Definition at line 7958 of file wasm-interpreter.cc.
                                   {
  if (current_block_index_ >= 0) {
    StoreBlockParamsAndResultsIntoSlots(0, kExprReturn);
  }
  START_EMIT_INSTR_HANDLER_WITH_ID(s2s_Return) {
    const WasmBytecodeGenerator::BlockData& target_block_data = blocks_[0];
    uint32_t final_stack_size =
        target_block_data.stack_size_ + ReturnsCount(target_block_data);
    EmitStackIndex(final_stack_size);
  }
  END_EMIT_INSTR_HANDLER()
}
References blocks_, current_block_index_, EmitStackIndex(), END_EMIT_INSTR_HANDLER, ReturnsCount(), v8::internal::wasm::WasmBytecodeGenerator::BlockData::stack_size_, START_EMIT_INSTR_HANDLER_WITH_ID, and StoreBlockParamsAndResultsIntoSlots().
Referenced by DoEncodeInstruction().
ReturnsCount()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::ReturnsCount (const WasmBytecodeGenerator::BlockData & block_data) const [inline], [private]
Definition at line 472 of file wasm-interpreter-inl.h.
                                                            {
  if (block_data.signature_.is_bottom()) {
    const FunctionSig* sig =
        module_->signature(block_data.signature_.sig_index);
    return static_cast<uint32_t>(sig->return_count());
  } else if (block_data.signature_.value_type() == kWasmVoid) {
    return 0;
  }
  return 1;
}
References v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom(), v8::internal::wasm::kWasmVoid, v8::internal::sig, v8::internal::wasm::WasmInstruction::Optional::Block::sig_index, v8::internal::wasm::WasmBytecodeGenerator::BlockData::signature_, and v8::internal::wasm::WasmInstruction::Optional::Block::value_type().
Referenced by Return(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
S128Pop()
void v8::internal::wasm::WasmBytecodeGenerator::S128Pop (bool emit = true) [inline], [private]
Definition at line 1584 of file wasm-interpreter.h.
{ Pop(kS128, emit); }
References v8::internal::kS128, and Pop().
Referenced by DoEncodeInstruction().
S128Push()
void v8::internal::wasm::WasmBytecodeGenerator::S128Push (bool emit = true) [inline], [private]
Definition at line 385 of file wasm-interpreter-inl.h.
                                                     {
  uint32_t slot_index = _PushSlot(kWasmS128);
  uint32_t slot_offset = slots_[slot_index].slot_offset;
  if (emit) EmitSlotOffset(slot_offset);
}
References v8::internal::wasm::kWasmS128.
Referenced by DoEncodeInstruction().
ScanConstInstructions()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::ScanConstInstructions () const [private]
Definition at line 7903 of file wasm-interpreter.cc.
                                                            {
  Decoder decoder(wasm_code_->start, wasm_code_->end);
  uint32_t const_slots_size = 0;
  pc_t pc = wasm_code_->locals.encoded_size;
  pc_t limit = wasm_code_->end - wasm_code_->start;
  while (pc < limit) {
    uint32_t opcode = wasm_code_->start[pc];
    if (opcode == kExprI32Const || opcode == kExprF32Const) {
      const_slots_size += sizeof(uint32_t) / kSlotSize;
    } else if (opcode == kExprI64Const || opcode == kExprF64Const) {
      const_slots_size += sizeof(uint64_t) / kSlotSize;
    } else if (opcode == kSimdPrefix) {
      auto [opcode_index, opcode_len] =
          decoder.read_u32v<Decoder::FullValidationTag>(
              wasm_code_->start + pc + 1, "prefixed opcode index");
      opcode = (kSimdPrefix << 8) | opcode_index;
      if (opcode == kExprS128Const || opcode == kExprI8x16Shuffle) {
        const_slots_size += sizeof(Simd128) / kSlotSize;
      }
    }
    pc++;
  }
  return const_slots_size;
}
References v8::internal::wasm::BodyLocalDecls::encoded_size, v8::internal::wasm::InterpreterCode::end, v8::internal::wasm::kSlotSize, v8::internal::wasm::InterpreterCode::locals, v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::InterpreterCode::start, and wasm_code_.
Referenced by GenerateBytecode().
SetSlotType()
void v8::internal::wasm::WasmBytecodeGenerator::SetSlotType (uint32_t stack_index, ValueType type) [inline], [private]
Definition at line 1929 of file wasm-interpreter.h.
                                                                {
    DCHECK_LT(stack_index, stack_.size());
    uint32_t slot_index = stack_[stack_index];
    slots_[slot_index].value_type = type;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    TraceSetSlotType(stack_index, type);
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  }
References DCHECK_LT, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), slots_, stack_, and v8::internal::tracing::type.
Referenced by DoEncodeInstruction(), and UpdateStack().
SetUnreachableMode()
void v8::internal::wasm::WasmBytecodeGenerator::SetUnreachableMode () [inline], [private]
Definition at line 1963 of file wasm-interpreter.h.
                                   {
    is_instruction_reachable_ = false;
    unreachable_block_count_ = 1;
    CHECK_GE(current_block_index_, 0);
    blocks_[current_block_index_].is_unreachable_ = true;
  }
References blocks_, CHECK_GE, current_block_index_, is_instruction_reachable_, and unreachable_block_count_.
Referenced by DoEncodeInstruction().
stack_size()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::stack_size () const [inline], [private]
Definition at line 1959 of file wasm-interpreter.h.
                                     {
    return static_cast<uint32_t>(stack_.size());
  }
References v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), and stack_.
Referenced by BeginBlock(), DoEncodeInstruction(), PopSlot(), PreserveArgsAndLocals(), and PushSlot().
stack_top_index()
uint32_t v8::internal::wasm::WasmBytecodeGenerator::stack_top_index () const [inline], [private]
Definition at line 1955 of file wasm-interpreter.h.
                                          {
    DCHECK(!stack_.empty());
    return static_cast<uint32_t>(stack_.size() - 1);
  }
References v8::internal::DCHECK(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::empty(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), and stack_.
Referenced by DoEncodeInstruction(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
StoreBlockParamsAndResultsIntoSlots()
void v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsAndResultsIntoSlots (uint32_t target_block_index, WasmOpcode opcode) [private]
Definition at line 7813 of file wasm-interpreter.cc.
                                                    {
  bool is_branch = kExprBr == opcode || kExprBrIf == opcode ||
                   kExprBrTable == opcode || kExprBrOnNull == opcode ||
                   kExprBrOnNonNull == opcode || kExprBrOnCast == opcode;
  const WasmBytecodeGenerator::BlockData& target_block_data =
      blocks_[target_block_index];
  bool is_target_loop_block = target_block_data.opcode_ == kExprLoop;
  if (is_target_loop_block && is_branch) {
    StoreBlockParamsIntoSlots(target_block_index, false);
  }
  // Ignore params if this is the function main block.
  uint32_t params_count =
      target_block_index == 0 ? 0 : ParamsCount(target_block_data);
  uint32_t rets_count = ReturnsCount(target_block_data);
  // If we are branching to a loop block we go back to the beginning of the
  // block, therefore we don't need to store the block results.
  if (!is_target_loop_block || !is_branch) {
    // There could be valid code where there are not enough elements in the
    // stack if some code in unreachable (for example if a 'i32.const 0' is
    // followed by a 'br_if' the if branch is never reachable).
    uint32_t count = std::min(static_cast<uint32_t>(stack_.size()), rets_count);
    for (uint32_t i = 0; i < count; i++) {
      uint32_t from_slot_index = stack_[stack_top_index() - (count - 1) + i];
      uint32_t to_slot_index = target_block_data.first_block_index_ + i;
      if (from_slot_index != to_slot_index) {
        EmitCopySlot(GetReturnType(target_block_data, i), from_slot_index,
                     to_slot_index);
      }
    }
  }
  bool is_else = (kExprElse == opcode);
  bool is_return = (kExprReturn == opcode);
  bool is_catch = (kExprCatch == opcode || kExprCatchAll == opcode);
  if (!is_branch && !is_return && !is_else && !is_catch) {
    uint32_t new_stack_height =
        target_block_data.stack_size_ - params_count + rets_count;
    DCHECK(new_stack_height <= stack_.size() ||
           !was_current_instruction_reachable_);
    stack_.resize(new_stack_height);
    for (uint32_t i = 0; i < rets_count; i++) {
      DCHECK_EQ(GetReturnType(target_block_data, i),
                slots_[target_block_data.first_block_index_ + i].value_type);
      DCHECK_EQ(GetReturnType(target_block_data, i),
                slots_[target_block_data.first_block_index_ + i].value_type);
      UpdateStack(target_block_data.stack_size_ - params_count + i,
                  target_block_data.first_block_index_ + i);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
      if (v8_flags.trace_drumbrake_execution) {
        START_EMIT_INSTR_HANDLER_WITH_ID(trace_UpdateStack) {
          EmitStackIndex(target_block_data.stack_size_ - params_count + i);
          EmitSlotOffset(
              slots_[target_block_data.first_block_index_ + i].slot_offset *
              kSlotSize);
        }
        END_EMIT_INSTR_HANDLER()
      }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    }
  }
}
References blocks_, v8::internal::DCHECK(), DCHECK_EQ, EmitCopySlot(), EmitSlotOffset(), EmitStackIndex(), END_EMIT_INSTR_HANDLER, v8::internal::wasm::WasmBytecodeGenerator::BlockData::first_block_index_, GetReturnType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecodeGenerator::BlockData::opcode_, ParamsCount(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::resize(), ReturnsCount(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), slots_, stack_, v8::internal::wasm::WasmBytecodeGenerator::BlockData::stack_size_, stack_top_index(), START_EMIT_INSTR_HANDLER_WITH_ID, StoreBlockParamsIntoSlots(), UpdateStack(), and v8::internal::v8_flags.
Referenced by DoEncodeInstruction(), EndBlock(), and Return().
StoreBlockParamsIntoSlots()
void v8::internal::wasm::WasmBytecodeGenerator::StoreBlockParamsIntoSlots (uint32_t target_block_index, bool update_stack) [private]
Definition at line 7773 of file wasm-interpreter.cc.
                                                    {
  const WasmBytecodeGenerator::BlockData& target_block_data =
      blocks_[target_block_index];
  DCHECK_EQ(target_block_data.opcode_, kExprLoop);
  uint32_t params_count = ParamsCount(target_block_data);
  uint32_t rets_count = ReturnsCount(target_block_data);
  uint32_t first_param_slot_index =
      target_block_data.first_block_index_ + rets_count;
  for (uint32_t i = 0; i < params_count; i++) {
    uint32_t from_slot_index =
        stack_[stack_top_index() - (params_count - 1) + i];
    uint32_t to_slot_index = first_param_slot_index + i;
    if (from_slot_index != to_slot_index) {
      EmitCopySlot(GetParamType(target_block_data, i), from_slot_index,
                   to_slot_index);
      if (update_stack) {
        DCHECK_EQ(GetParamType(target_block_data, i),
                  slots_[first_param_slot_index + i].value_type);
        DCHECK_EQ(GetParamType(target_block_data, i),
                  slots_[first_param_slot_index + i].value_type);
        UpdateStack(stack_top_index() - (params_count - 1) + i,
                    first_param_slot_index + i);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
        if (v8_flags.trace_drumbrake_execution) {
          START_EMIT_INSTR_HANDLER_WITH_ID(trace_UpdateStack) {
            EmitStackIndex(stack_top_index() - (params_count - 1) + i);
            EmitSlotOffset(slots_[first_param_slot_index + i].slot_offset *
                           kSlotSize);
          }
          END_EMIT_INSTR_HANDLER()
        }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
      }
    }
  }
}
References blocks_, DCHECK_EQ, EmitCopySlot(), EmitSlotOffset(), EmitStackIndex(), END_EMIT_INSTR_HANDLER, v8::internal::wasm::WasmBytecodeGenerator::BlockData::first_block_index_, GetParamType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kSlotSize, v8::internal::wasm::WasmBytecodeGenerator::BlockData::opcode_, ParamsCount(), ReturnsCount(), slots_, stack_, stack_top_index(), START_EMIT_INSTR_HANDLER_WITH_ID, UpdateStack(), v8::internal::v8_flags, and v8::internal::wasm::value_type().
Referenced by BeginBlock(), and StoreBlockParamsAndResultsIntoSlots().
ToRegisterIsAllowed()
bool v8::internal::wasm::WasmBytecodeGenerator::ToRegisterIsAllowed (const WasmInstruction & instr) [inline], [private]
Definition at line 339 of file wasm-interpreter-inl.h.
                                  {
  if (!instr.SupportsToRegister()) return false;
  // Even if the instruction is marked as supporting ToRegister, reference
  // values should not be stored in the register.
  switch (instr.opcode) {
    case kExprGlobalGet: {
      ValueKind kind = GetGlobalType(instr.optional.index);
      return !wasm::is_reference(kind) && kind != kS128;
    }
    case kExprSelect:
    case kExprSelectWithType: {
      DCHECK_GE(stack_size(), 2);
      ValueKind kind = slots_[stack_[stack_size() - 2]].kind();
      return !wasm::is_reference(kind) && kind != kS128;
    }
    default:
      return true;
  }
}
References DCHECK_GE, v8::internal::wasm::WasmInstruction::Optional::index, v8::internal::wasm::is_reference(), v8::internal::kS128, v8::internal::wasm::WasmInstruction::opcode, v8::internal::wasm::WasmInstruction::optional, and v8::internal::wasm::WasmInstruction::SupportsToRegister().
Referenced by DoEncodeInstruction().
TryCompactInstructionHandler()
bool v8::internal::wasm::WasmBytecodeGenerator::TryCompactInstructionHandler (InstructionHandler func_addr) [private]
Definition at line 13157 of file wasm-interpreter.cc.
                                {
  if (last_instr_offset_ == kInvalidCodeOffset) return false;
  InstructionHandler* prev_instr_addr =
      reinterpret_cast<InstructionHandler*>(code_.data() + last_instr_offset_);
  InstructionHandler prev_instr_handler = *prev_instr_addr;
  if (func_id == k_s2s_CopySlot32 && prev_instr_handler == k_s2s_CopySlot32) {
    // Tranforms:
    // [CopySlot32: InstrId][from: slot_offset_t][to: slot_offset_t]
    // into:
    // [CopySlot32x2: InstrId][from0: slot_offset_t][to0: slot_offset_t][from1:
    // slot_offset_t][to1: slot_offset_t]
    DCHECK(handler_size_ == InstrHandlerSize::Large ||
           v8_flags.drumbrake_compact_bytecode);
    base::WriteUnalignedValue<InstructionHandler>(
        reinterpret_cast<Address>(prev_instr_addr), k_s2s_CopySlot32x2);
    return true;
  } else if (func_id == k_s2s_CopySlot64 &&
             prev_instr_handler == k_s2s_CopySlot64) {
    DCHECK(handler_size_ == InstrHandlerSize::Large ||
           v8_flags.drumbrake_compact_bytecode);
    base::WriteUnalignedValue<InstructionHandler>(
        reinterpret_cast<Address>(prev_instr_addr), k_s2s_CopySlot64x2);
    return true;
  }
  return false;
}
References code_, v8::internal::DCHECK(), handler_size_, kInvalidCodeOffset, v8::internal::wasm::Large, last_instr_offset_, and v8::internal::v8_flags.
Referenced by EmitFnId().
TypeCheckAlwaysFails()
bool v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails (ValueType obj_type, HeapType expected_type, bool null_succeeds) const [private]
Definition at line 8794 of file wasm-interpreter.cc.
                                                                           {
  bool types_unrelated =
      !IsSubtypeOf(ValueType::Ref(expected_type), obj_type, module_) &&
      !IsSubtypeOf(obj_type, ValueType::RefNull(expected_type), module_);
  // (Comment copied from function-body-decoder-impl.h).
  // For "unrelated" types the check can still succeed for the null value on
  // instructions treating null as a successful check.
  // TODO(12868): For string views, this implementation anticipates that
  // https://github.com/WebAssembly/stringref/issues/40 will be resolved
  // by making the views standalone types.
  return (types_unrelated &&
          (!null_succeeds || !obj_type.is_nullable() ||
           obj_type.is_string_view() || expected_type.is_string_view())) ||
         (!null_succeeds &&
          (expected_type.representation() == HeapType::kNone ||
           expected_type.representation() == HeapType::kNoFunc ||
           expected_type.representation() == HeapType::kNoExtern));
}
References v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::ValueTypeBase::is_string_view(), v8::internal::wasm::IsSubtypeOf(), v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, module_, v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::RefNull(), and v8::internal::wasm::HeapType::representation().
Referenced by DoEncodeInstruction().
TypeCheckAlwaysSucceeds()
bool v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysSucceeds (ValueType obj_type, HeapType type) const [private]
Definition at line 8786 of file wasm-interpreter.cc.
                                                                         {
  return IsSubtypeOf(obj_type, ValueType::RefNull(type), module_);
}
References v8::internal::wasm::IsSubtypeOf(), module_, v8::internal::wasm::ValueType::RefNull(), and v8::internal::tracing::type.
Referenced by DoEncodeInstruction().
UpdateStack() [1/2]
void v8::internal::wasm::WasmBytecodeGenerator::UpdateStack (uint32_t index, uint32_t slot_index) [inline], [private]
Definition at line 1944 of file wasm-interpreter.h.
                                                               {
    DCHECK_LT(index, stack_.size());
    stack_[index] = slot_index;
  }
References DCHECK_LT, v8::internal::index, v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), and stack_.
Referenced by FindSharedSlot(), RestoreIfElseParams(), StoreBlockParamsAndResultsIntoSlots(), and StoreBlockParamsIntoSlots().
UpdateStack() [2/2]
void v8::internal::wasm::WasmBytecodeGenerator::UpdateStack (uint32_t index, uint32_t slot_index, ValueType value_type) [inline], [private]
Definition at line 1948 of file wasm-interpreter.h.
                                                {
    DCHECK_LT(index, stack_.size());
    stack_[index] = slot_index;
    SetSlotType(index, value_type);
  }
References DCHECK_LT, v8::internal::index, SetSlotType(), v8::internal::wasm::WasmBytecodeGenerator::RollbackStack::size(), stack_, and v8::internal::wasm::value_type().
Member Data Documentation
args_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::args_count_ [private]
Definition at line 2055 of file wasm-interpreter.h.
Referenced by GenerateBytecode(), PreserveArgsAndLocals(), and WasmBytecodeGenerator().
args_slots_size_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::args_slots_size_ [private]
Definition at line 2056 of file wasm-interpreter.h.
Referenced by const_slots_start(), and WasmBytecodeGenerator().
blocks_
std::vector<BlockData> v8::internal::wasm::WasmBytecodeGenerator::blocks_ [private]
Definition at line 2063 of file wasm-interpreter.h.
Referenced by BeginBlock(), DoEncodeInstruction(), EndBlock(), FindSharedSlot(), GenerateBytecode(), GetCurrentTryBlockIndex(), HasSharedSlot(), PatchBranchOffsets(), RestoreIfElseParams(), Return(), SetUnreachableMode(), StoreBlockParamsAndResultsIntoSlots(), StoreBlockParamsIntoSlots(), and WasmBytecodeGenerator().
br_table_labels_
base::SmallVector<uint32_t, 8> v8::internal::wasm::WasmBytecodeGenerator::br_table_labels_ [private]
Definition at line 2072 of file wasm-interpreter.h.
Referenced by DecodeInstruction(), and DoEncodeInstruction().
code_
std::vector<uint8_t> v8::internal::wasm::WasmBytecodeGenerator::code_ [private]
Definition at line 2061 of file wasm-interpreter.h.
Referenced by CurrentCodePos(), DoEncodeInstruction(), Emit(), EmitFnId(), EncodeInstruction(), EncodeSuperInstruction(), GenerateBytecode(), PatchBranchOffsets(), PatchLoopBeginInstructions(), TryCompactInstructionHandler(), and WasmBytecodeGenerator().
code_pc_map_
std::map<CodeOffset, pc_t> v8::internal::wasm::WasmBytecodeGenerator::code_pc_map_ [private]
Definition at line 2085 of file wasm-interpreter.h.
Referenced by EmitFnId(), and GenerateBytecode().
const_slot_offset_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::const_slot_offset_ [private]
Definition at line 1990 of file wasm-interpreter.h.
Referenced by CreateConstSlot().
const_slots_values_
std::vector<uint8_t> v8::internal::wasm::WasmBytecodeGenerator::const_slots_values_ [private]
Definition at line 1989 of file wasm-interpreter.h.
Referenced by CreateConstSlot(), and GenerateBytecode().
current_block_index_
int32_t v8::internal::wasm::WasmBytecodeGenerator::current_block_index_ [private]
Definition at line 2064 of file wasm-interpreter.h.
Referenced by BeginBlock(), DoEncodeInstruction(), EndBlock(), FindSharedSlot(), GenerateBytecode(), GetCurrentTryBlockIndex(), HasSharedSlot(), Return(), and SetUnreachableMode().
current_instr_encoding_failed_
bool v8::internal::wasm::WasmBytecodeGenerator::current_instr_encoding_failed_ [private]
Definition at line 2094 of file wasm-interpreter.h.
Referenced by EmitMemoryOffset(), EmitSlotOffset(), EncodeInstruction(), and EncodeSuperInstruction().
eh_data_
WasmEHDataGenerator v8::internal::wasm::WasmBytecodeGenerator::eh_data_ [private]
Definition at line 2090 of file wasm-interpreter.h.
Referenced by BeginBlock(), DoEncodeInstruction(), EndBlock(), GenerateBytecode(), and PatchBranchOffsets().
emitted_short_memory_offset_count_
std::atomic< size_t > v8::internal::wasm::WasmBytecodeGenerator::emitted_short_memory_offset_count_ [static], [private]
Initial value:
=
    0
Definition at line 2098 of file wasm-interpreter.h.
Referenced by EmitMemoryOffset(), and PrintBytecodeCompressionStats().
emitted_short_slot_offset_count_
std::atomic< size_t > v8::internal::wasm::WasmBytecodeGenerator::emitted_short_slot_offset_count_ = 0 [static], [private]
Definition at line 2097 of file wasm-interpreter.h.
Referenced by EmitSlotOffset(), and PrintBytecodeCompressionStats().
f32_const_cache_
std::unordered_map<float, uint32_t> v8::internal::wasm::WasmBytecodeGenerator::f32_const_cache_ [private]
Definition at line 1993 of file wasm-interpreter.h.
Referenced by GetF32ConstSlot().
f64_const_cache_
std::unordered_map<double, uint32_t> v8::internal::wasm::WasmBytecodeGenerator::f64_const_cache_ [private]
Definition at line 1994 of file wasm-interpreter.h.
Referenced by GetF64ConstSlot().
function_index_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::function_index_ [private]
Definition at line 2053 of file wasm-interpreter.h.
Referenced by function_index(), and GenerateBytecode().
handler_size_
InstrHandlerSize v8::internal::wasm::WasmBytecodeGenerator::handler_size_ [private]
Definition at line 2093 of file wasm-interpreter.h.
Referenced by EmitFnId(), EmitMemoryOffset(), EmitSlotOffset(), EncodeInstruction(), EncodeSuperInstruction(), and TryCompactInstructionHandler().
i32_const_cache_
std::unordered_map<int32_t, uint32_t> v8::internal::wasm::WasmBytecodeGenerator::i32_const_cache_ [private]
Definition at line 1991 of file wasm-interpreter.h.
Referenced by GetI32ConstSlot().
i64_const_cache_
std::unordered_map<int64_t, uint32_t> v8::internal::wasm::WasmBytecodeGenerator::i64_const_cache_ [private]
Definition at line 1992 of file wasm-interpreter.h.
Referenced by GetI64ConstSlot().
int_mem_pop_
MemIndexPopFunc v8::internal::wasm::WasmBytecodeGenerator::int_mem_pop_ [private]
Definition at line 1986 of file wasm-interpreter.h.
Referenced by MemIndexPop(), and WasmBytecodeGenerator().
int_mem_push_
MemIndexPushFunc v8::internal::wasm::WasmBytecodeGenerator::int_mem_push_ [private]
Definition at line 1985 of file wasm-interpreter.h.
Referenced by MemIndexPush(), and WasmBytecodeGenerator().
is_instruction_reachable_
bool v8::internal::wasm::WasmBytecodeGenerator::is_instruction_reachable_ [private]
Definition at line 2066 of file wasm-interpreter.h.
Referenced by DoEncodeInstruction(), GenerateBytecode(), and SetUnreachableMode().
is_memory64_
bool v8::internal::wasm::WasmBytecodeGenerator::is_memory64_ [private]
Definition at line 1987 of file wasm-interpreter.h.
Referenced by DoEncodeInstruction(), DoEncodeSuperInstruction(), and WasmBytecodeGenerator().
kInvalidCodeOffset
const CodeOffset v8::internal::wasm::WasmBytecodeGenerator::kInvalidCodeOffset = (CodeOffset)-1 [static], [private]
Definition at line 2087 of file wasm-interpreter.h.
Referenced by BeginBlock(), EndBlock(), and TryCompactInstructionHandler().
last_instr_offset_
CodeOffset v8::internal::wasm::WasmBytecodeGenerator::last_instr_offset_ [private]
Definition at line 2088 of file wasm-interpreter.h.
Referenced by BeginBlock(), EmitFnId(), EndBlock(), and TryCompactInstructionHandler().
locals_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::locals_count_ [private]
Definition at line 2059 of file wasm-interpreter.h.
Referenced by PreserveArgsAndLocals(), and WasmBytecodeGenerator().
loop_begin_code_offsets_
base::SmallVector<uint32_t, 16> v8::internal::wasm::WasmBytecodeGenerator::loop_begin_code_offsets_ [private]
Definition at line 2073 of file wasm-interpreter.h.
Referenced by BeginBlock(), and PatchLoopBeginInstructions().
module_
const WasmModule* v8::internal::wasm::WasmBytecodeGenerator::module_ [private]
Definition at line 2075 of file wasm-interpreter.h.
Referenced by DecodeGCOp(), DecodeInstruction(), DecodeNumericOp(), DoEncodeInstruction(), GenerateBytecode(), ReserveBlockSlots(), TypeCheckAlwaysFails(), TypeCheckAlwaysSucceeds(), and WasmBytecodeGenerator().
no_nested_emit_instr_handler_guard_
bool v8::internal::wasm::WasmBytecodeGenerator::no_nested_emit_instr_handler_guard_ [private]
Definition at line 2095 of file wasm-interpreter.h.
ref_slots_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::ref_slots_count_ [private]
Definition at line 2051 of file wasm-interpreter.h.
Referenced by CreateWasmRefSlot(), DoEncodeInstruction(), GenerateBytecode(), and PatchLoopBeginInstructions().
rets_slots_size_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::rets_slots_size_ [private]
Definition at line 2058 of file wasm-interpreter.h.
Referenced by const_slots_start(), and WasmBytecodeGenerator().
return_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::return_count_ [private]
Definition at line 2057 of file wasm-interpreter.h.
Referenced by GenerateBytecode(), and WasmBytecodeGenerator().
s128_const_cache_
std::unordered_map<Simd128, uint32_t, Simd128Hash> v8::internal::wasm::WasmBytecodeGenerator::s128_const_cache_ [private]
Definition at line 1999 of file wasm-interpreter.h.
Referenced by GetS128ConstSlot().
simd_immediates_
std::vector<Simd128> v8::internal::wasm::WasmBytecodeGenerator::simd_immediates_ [private]
Definition at line 2001 of file wasm-interpreter.h.
Referenced by DecodeSimdOp(), and DoEncodeInstruction().
slot_offset_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::slot_offset_ [private]
Definition at line 2002 of file wasm-interpreter.h.
Referenced by CreateSlot(), CreateWasmRefSlot(), GenerateBytecode(), and GetStackFrameSize().
slots_
std::vector<Slot> v8::internal::wasm::WasmBytecodeGenerator::slots_ [private]
Definition at line 1755 of file wasm-interpreter.h.
Referenced by _PushSlot(), CopyToSlot(), CreateConstSlot(), CreateSlot(), CreateWasmRefSlot(), DoEncodeInstruction(), EmitCopySlot(), EncodeInstruction(), EncodeSuperInstruction(), FindSharedSlot(), InitSlotsForFunctionArgs(), Pop(), PopSlot(), PreserveArgsAndLocals(), RefPop(), RestoreIfElseParams(), SetSlotType(), StoreBlockParamsAndResultsIntoSlots(), StoreBlockParamsIntoSlots(), and WasmBytecodeGenerator().
stack_
RollbackStack v8::internal::wasm::WasmBytecodeGenerator::stack_ [private]
Definition at line 2049 of file wasm-interpreter.h.
Referenced by BeginBlock(), CopyToSlot(), CopyToSlotAndPop(), DoEncodeInstruction(), EncodeInstruction(), EncodeSuperInstruction(), FindSharedSlot(), HasSharedSlot(), InitSlotsForFunctionArgs(), Pop(), PopSlot(), PreserveArgsAndLocals(), PushSlot(), RefPop(), RestoreIfElseParams(), SetSlotType(), stack_size(), stack_top_index(), StoreBlockParamsAndResultsIntoSlots(), StoreBlockParamsIntoSlots(), UpdateStack(), and WasmBytecodeGenerator().
total_bytecode_size_
std::atomic< size_t > v8::internal::wasm::WasmBytecodeGenerator::total_bytecode_size_ = 0 [static], [private]
Definition at line 2096 of file wasm-interpreter.h.
Referenced by GenerateBytecode(), and PrintBytecodeCompressionStats().
unreachable_block_count_
uint32_t v8::internal::wasm::WasmBytecodeGenerator::unreachable_block_count_ [private]
Definition at line 2067 of file wasm-interpreter.h.
Referenced by DoEncodeInstruction(), and SetUnreachableMode().
wasm_code_
InterpreterCode* v8::internal::wasm::WasmBytecodeGenerator::wasm_code_ [private]
Definition at line 2054 of file wasm-interpreter.h.
Referenced by DecodeInstruction(), DoEncodeInstruction(), GenerateBytecode(), ScanConstInstructions(), and WasmBytecodeGenerator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-simd.cc
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc