v8::internal::torque::ls::Message Class Reference
#include <message.h>
Public Member Functions
Message ()
Message (JsonValue value)
JsonValue & GetJsonValue ()
Protected Member Functions
const JsonObject & object () const override
JsonObject & object () override
Private Attributes
JsonValue value_
Detailed Description
Definition at line 70 of file message.h.
Constructor & Destructor Documentation
Message() [1/2]
v8::internal::torque::ls::Message::Message () [inline]
Definition at line 72 of file message.h.
            {
    value_ = JsonValue::From(JsonObject{});
    set_jsonrpc("2.0");
  }
References v8::internal::torque::ls::JsonValue::From(), and value_.
Message() [2/2]
v8::internal::torque::ls::Message::Message (JsonValue value) [inline], [explicit]
Definition at line 76 of file message.h.
                                    : value_(std::move(value)) {
    CHECK(value_.tag == JsonValue::OBJECT);
  }
References CHECK, v8::internal::torque::ls::JsonValue::OBJECT, v8::internal::torque::ls::JsonValue::tag, and value_.
Member Function Documentation
GetJsonValue()
JsonValue& v8::internal::torque::ls::Message::GetJsonValue () [inline]
Definition at line 80 of file message.h.
{ return value_; }
References value_.
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleGotoDefinitionRequest(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleInitializedNotification(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleInitializeRequest(), v8::internal::torque::ls::HandleMessage(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::ResetCompilationErrorDiagnostics(), and v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::SendCompilationDiagnostics().
object() [1/2]
const JsonObject& v8::internal::torque::ls::Message::object () const [inline], [override], [protected], [virtual]
Implements v8::internal::torque::ls::BaseJsonAccessor.
Definition at line 85 of file message.h.
{ return value_.ToObject(); }
References v8::internal::torque::ls::JsonValue::ToObject(), and value_.
Referenced by v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleTorqueFileListNotification().
object() [2/2]
JsonObject& v8::internal::torque::ls::Message::object () [inline], [override], [protected], [virtual]
Implements v8::internal::torque::ls::BaseJsonAccessor.
Definition at line 86 of file message.h.
{ return value_.ToObject(); }
References v8::internal::torque::ls::JsonValue::ToObject(), and value_.
Member Data Documentation
value_
JsonValue v8::internal::torque::ls::Message::value_ [private]
Definition at line 89 of file message.h.
Referenced by GetJsonValue(), Message(), and object().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/ls/message.h