v8::internal::compiler::AssertParameters Class Reference
#include <common-operator.h>
Public Member Functions
AssertParameters (BranchSemantics semantics, const char *condition_string, const char *file, int line)
BranchSemantics semantics () const
const char * condition_string () const
const char * file () const
int line () const
Private Attributes
const BranchSemantics semantics_
const char * condition_string_
const char * file_
const int line_
Detailed Description
Definition at line 106 of file common-operator.h.
Constructor & Destructor Documentation
AssertParameters()
v8::internal::compiler::AssertParameters::AssertParameters (BranchSemantics semantics, const char * condition_string, const char * file, int line) [inline]
Definition at line 108 of file common-operator.h.
      : semantics_(semantics),
        condition_string_(condition_string),
        file_(file),
        line_(line) {}
Member Function Documentation
condition_string()
const char* v8::internal::compiler::AssertParameters::condition_string () const [inline]
Definition at line 116 of file common-operator.h.
{ return condition_string_; }
References condition_string_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
file()
const char* v8::internal::compiler::AssertParameters::file () const [inline]
Definition at line 117 of file common-operator.h.
{ return file_; }
References file_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
line()
int v8::internal::compiler::AssertParameters::line () const [inline]
Definition at line 118 of file common-operator.h.
{ return line_; }
References line_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
semantics()
BranchSemantics v8::internal::compiler::AssertParameters::semantics () const [inline]
Definition at line 115 of file common-operator.h.
{ return semantics_; }
References semantics_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
condition_string_
const char* v8::internal::compiler::AssertParameters::condition_string_ [private]
Definition at line 122 of file common-operator.h.
Referenced by condition_string().
file_
const char* v8::internal::compiler::AssertParameters::file_ [private]
Definition at line 123 of file common-operator.h.
Referenced by file().
line_
const int v8::internal::compiler::AssertParameters::line_ [private]
Definition at line 124 of file common-operator.h.
Referenced by line().
semantics_
const BranchSemantics v8::internal::compiler::AssertParameters::semantics_ [private]
Definition at line 121 of file common-operator.h.
Referenced by semantics().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h