cppgc::internal::GCInvoker::GCInvokerImpl Class Reference
Classes
class GCTask
Public Member Functions
GCInvokerImpl (GarbageCollector *, cppgc::Platform *, cppgc::Heap::StackSupport)
~GCInvokerImpl ()
GCInvokerImpl (const GCInvokerImpl &)=delete
GCInvokerImpl & operator= (const GCInvokerImpl &)=delete
void CollectGarbage (GCConfig) final
void StartIncrementalGarbageCollection (GCConfig) final
size_t epoch () const final
std::optional< EmbedderStackState > overridden_stack_state () const final
void set_override_stack_state (EmbedderStackState state) final
void clear_overridden_stack_state () final
Private Attributes
GarbageCollector * collector_
cppgc::Platform * platform_
cppgc::Heap::StackSupport stack_support_
GCTask::Handle gc_task_handle_
Detailed Description
Definition at line 17 of file gc-invoker.cc.
Constructor & Destructor Documentation
GCInvokerImpl() [1/2]
cppgc::internal::GCInvoker::GCInvokerImpl::GCInvokerImpl (GarbageCollector * collector, cppgc::Platform * platform, cppgc::Heap::StackSupport stack_support)
Definition at line 85 of file gc-invoker.cc.
    : collector_(collector),
      platform_(platform),
      stack_support_(stack_support) {}
 GCInvokerImpl()
cppgc::internal::GCInvoker::GCInvokerImpl::~GCInvokerImpl ()
Definition at line 92 of file gc-invoker.cc.
                                       {
  if (gc_task_handle_) {
    gc_task_handle_.Cancel();
  }
}
GCInvokerImpl() [2/2]
cppgc::internal::GCInvoker::GCInvokerImpl::GCInvokerImpl (const GCInvokerImpl &) [delete]
Member Function Documentation
clear_overridden_stack_state()
void cppgc::internal::GCInvoker::GCInvokerImpl::clear_overridden_stack_state () [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 34 of file gc-invoker.cc.
                                            {
    collector_->clear_overridden_stack_state();
  }
References cppgc::internal::GarbageCollector::clear_overridden_stack_state(), and collector_.
CollectGarbage()
void cppgc::internal::GCInvoker::GCInvokerImpl::CollectGarbage (GCConfig config) [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 98 of file gc-invoker.cc.
                                                           {
  DCHECK_EQ(config.marking_type, cppgc::Heap::MarkingType::kAtomic);
  if ((config.stack_state == StackState::kNoHeapPointers) ||
      (stack_support_ ==
       cppgc::Heap::StackSupport::kSupportsConservativeStackScan)) {
    collector_->CollectGarbage(config);
  } else if (platform_->GetForegroundTaskRunner() &&
             platform_->GetForegroundTaskRunner()->NonNestableTasksEnabled()) {
    if (!gc_task_handle_) {
      // Force a precise GC since it will run in a non-nestable task.
      config.stack_state = StackState::kNoHeapPointers;
      DCHECK_NE(cppgc::Heap::StackSupport::kSupportsConservativeStackScan,
                stack_support_);
      gc_task_handle_ = GCTask::Post(
          collector_, platform_->GetForegroundTaskRunner().get(), config);
    }
  }
}
References DCHECK_EQ, DCHECK_NE, cppgc::Heap::kAtomic, cppgc::Heap::kSupportsConservativeStackScan, cppgc::internal::GCConfig::marking_type, and cppgc::internal::GCConfig::stack_state.
epoch()
size_t cppgc::internal::GCInvoker::GCInvokerImpl::epoch () const [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 27 of file gc-invoker.cc.
{ return collector_->epoch(); }
References collector_, and cppgc::internal::GarbageCollector::epoch().
operator=()
GCInvokerImpl& cppgc::internal::GCInvoker::GCInvokerImpl::operator= (const GCInvokerImpl &) [delete]
overridden_stack_state()
std::optional<EmbedderStackState> cppgc::internal::GCInvoker::GCInvokerImpl::overridden_stack_state () const [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 28 of file gc-invoker.cc.
                                                                       {
    return collector_->overridden_stack_state();
  }
References collector_, and cppgc::internal::GarbageCollector::overridden_stack_state().
set_override_stack_state()
void cppgc::internal::GCInvoker::GCInvokerImpl::set_override_stack_state (EmbedderStackState state) [inline], [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 31 of file gc-invoker.cc.
                                                                {
    collector_->set_override_stack_state(state);
  }
References collector_, and cppgc::internal::GarbageCollector::set_override_stack_state().
StartIncrementalGarbageCollection()
void cppgc::internal::GCInvoker::GCInvokerImpl::StartIncrementalGarbageCollection (GCConfig config) [final], [virtual]
Implements cppgc::internal::GarbageCollector.
Definition at line 117 of file gc-invoker.cc.
                     {
  DCHECK_NE(config.marking_type, cppgc::Heap::MarkingType::kAtomic);
  if ((stack_support_ !=
       cppgc::Heap::StackSupport::kSupportsConservativeStackScan) &&
      (!platform_->GetForegroundTaskRunner() ||
       !platform_->GetForegroundTaskRunner()->NonNestableTasksEnabled())) {
    // In this configuration the GC finalization can only be triggered through
    // ForceGarbageCollectionSlow. If incremental GC is started, there is no
    // way to know how long it will remain enabled (and the write barrier with
    // it). For that reason, we do not support running incremental GCs in this
    // configuration.
    return;
  }
  // No need to postpone starting incremental GC since the stack is not scanned
  // until GC finalization.
  collector_->StartIncrementalGarbageCollection(config);
}
References DCHECK_NE, cppgc::Heap::kAtomic, cppgc::Heap::kSupportsConservativeStackScan, and cppgc::internal::GCConfig::marking_type.
Member Data Documentation
collector_
GarbageCollector* cppgc::internal::GCInvoker::GCInvokerImpl::collector_ [private]
Definition at line 79 of file gc-invoker.cc.
Referenced by clear_overridden_stack_state(), epoch(), overridden_stack_state(), and set_override_stack_state().
gc_task_handle_
GCTask::Handle cppgc::internal::GCInvoker::GCInvokerImpl::gc_task_handle_ [private]
Definition at line 82 of file gc-invoker.cc.
platform_
cppgc::Platform* cppgc::internal::GCInvoker::GCInvokerImpl::platform_ [private]
Definition at line 80 of file gc-invoker.cc.
stack_support_
cppgc::Heap::StackSupport cppgc::internal::GCInvoker::GCInvokerImpl::stack_support_ [private]
Definition at line 81 of file gc-invoker.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/gc-invoker.cc