v8::internal::compiler::turboshaft::WasmShuffleReducer< Next > Class Template Reference
#include <wasm-shuffle-reducer.h>
Public Member Functions
void Analyze ()
OpIndex REDUCE_INPUT_GRAPH() Simd128Shuffle (OpIndex ig_index, const Simd128ShuffleOp &shuffle)
Private Attributes
std::optional< WasmShuffleAnalyzer > analyzer_
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >
Definition at line 227 of file wasm-shuffle-reducer.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Analyze () [inline]
Definition at line 277 of file wasm-shuffle-reducer.h.
                 {
    analyzer_.emplace(__ phase_zone(), __ input_graph());
    analyzer_->Run();
    Next::Analyze();
  }
References __, and v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::analyzer_.
Simd128Shuffle()
template<class Next >
OpIndex REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle (OpIndex ig_index, const Simd128ShuffleOp & shuffle) [inline]
Definition at line 334 of file wasm-shuffle-reducer.h.
                                                                              {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphSimd128Shuffle(ig_index, shuffle);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    if (shuffle.kind != Simd128ShuffleOp::Kind::kI8x16) goto no_change;
    auto og_left = __ MapToNewGraph(shuffle.left());
    auto og_right = __ MapToNewGraph(shuffle.right());
    std::array<uint8_t, kSimd128Size> shuffle_bytes = {0};
    std::copy(shuffle.shuffle, shuffle.shuffle + kSimd128Size,
              shuffle_bytes.begin());
#if V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
    if (auto maybe_deinterleaved_load = IsDeinterleaveLoadShuffle(&shuffle)) {
      const auto* deinterleaved_load = maybe_deinterleaved_load.value();
      return __ Projection(deinterleaved_load->og_index,
                           deinterleaved_load->result_index,
                           RegisterRepresentation::Simd128());
    }
#endif // V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
    constexpr size_t half_lanes = kSimd128Size / 2;
    bool does_shuffle_into_low_half =
        analyzer_->DoesShuffleIntoLowHalf(&shuffle);
    bool does_shuffle_into_high_half =
        analyzer_->DoesShuffleIntoHighHalf(&shuffle);
    // Shuffles to adjust because one, or both, of their inputs have been
    // narrowed.
    if (does_shuffle_into_low_half && does_shuffle_into_high_half) {
      DCHECK(analyzer_->ShouldRewriteShuffleToLow(shuffle.left()));
      DCHECK(analyzer_->ShouldRewriteShuffleToLow(shuffle.right()));
      // We have a shuffle where both inputs have been reduced and shifted, so
      // something like this:
      // |--------|--------|---a1---|---b3---| shf0 = (a, b)
      //
      // |--------|--------|---c2---|---d4---| shf1 = (c, d)
      //
      // |---a1---|---b3---|---c2---|---d4---| shf2 = (shf0, shf1)
      //
      // Is being changed into this:
      // |---a1---|---b3---|--------|--------| shf0 = (a, b)
      //
      // |---c2---|---d4---|--------|--------| shf1 = (c, d)
      //
      // |---a1---|---b3---|---c2---|---d4---| shf2 = (shf0, shf1)
      std::transform(shuffle_bytes.begin(), shuffle_bytes.end(),
                     shuffle_bytes.begin(),
                     [](uint8_t lane) { return lane - half_lanes; });
    } else if (does_shuffle_into_low_half) {
      DCHECK(analyzer_->ShouldRewriteShuffleToLow(shuffle.left()) ||
             analyzer_->ShouldRewriteShuffleToLow(shuffle.right()));
      DCHECK_NE(analyzer_->ShouldRewriteShuffleToLow(shuffle.left()),
                analyzer_->ShouldRewriteShuffleToLow(shuffle.right()));
      // We have a shuffle where both inputs have been reduced and one has
      // been shifted, so something like this:
      // |--------|--------|---a1---|---b3---| shf0 = (a, b)
      //
      // |---c2---|---d4---|--------|--------| shf1 = (c, d)
      //
      // |---a1---|---b3---|---c2---|---d4---| shf2 = (shf0, shf1)
      //
      // Is being changed into this:
      // |---a1---|---b3---|--------|--------| shf0 = (a, b)
      //
      // |---c2---|---d4---|--------|--------| shf1 = (c, d)
      //
      // |---a1---|---b3---|---c2---|---d4---| shf2 = (shf0, shf1)
      //
      // Original shf2 lane-wise shuffle: [2, 3, 4, 5]
      // Needs to be converted to: [0, 1, 4, 5]
      std::transform(shuffle_bytes.begin(), shuffle_bytes.begin() + half_lanes,
                     shuffle_bytes.begin(),
                     [](uint8_t lane) { return lane - half_lanes; });
    } else if (does_shuffle_into_high_half) {
      DCHECK(analyzer_->ShouldRewriteShuffleToLow(shuffle.left()) ||
             analyzer_->ShouldRewriteShuffleToLow(shuffle.right()));
      DCHECK_NE(analyzer_->ShouldRewriteShuffleToLow(shuffle.left()),
                analyzer_->ShouldRewriteShuffleToLow(shuffle.right()));
      // We have a shuffle where both inputs have been reduced and one has
      // been shifted, so something like this:
      // |---a1---|---b3---|--------|--------| shf0 = (a, b)
      //
      // |--------|--------|---c2---|---d4---| shf1 = (c, d)
      //
      // |---a1---|---b3---|---c2---|---d4---| shf2 = (shf0, shf1)
      //
      // Is being changed into this:
      // |---a1---|---b3---|--------|--------| shf0 = (a, b)
      //
      // |---c2---|---d4---|--------|--------| shf1 = (c, d)
      //
      // |---a1---|---b3---|---c2---|---d4---| shf2 = (shf0, shf1)
      std::transform(shuffle_bytes.begin() + half_lanes, shuffle_bytes.end(),
                     shuffle_bytes.begin() + half_lanes,
                     [](uint8_t lane) { return lane - half_lanes; });
    }
    if (does_shuffle_into_low_half || does_shuffle_into_high_half) {
      return __ Simd128Shuffle(og_left, og_right,
                               Simd128ShuffleOp::Kind::kI8x16,
                               shuffle_bytes.data());
    }
    // Shuffles to narrow.
    if (auto maybe_lanes = analyzer_->DemandedByteLanes(&shuffle)) {
      auto lanes = maybe_lanes.value();
      if (analyzer_->ShouldRewriteShuffleToLow(&shuffle)) {
        DCHECK_EQ(lanes, DemandedElementAnalysis::k8x8Low);
        // Take the top half of the shuffle bytes and these will now write
        // those values into the low half of the result instead.
        std::copy(shuffle.shuffle + half_lanes, shuffle.shuffle + kSimd128Size,
                  shuffle_bytes.begin());
      } else {
        // Just truncate the lower half.
        std::copy(shuffle.shuffle, shuffle.shuffle + half_lanes,
                  shuffle_bytes.begin());
      }
      if (lanes == DemandedElementAnalysis::k8x2Low) {
        return __ Simd128Shuffle(og_left, og_right,
                                 Simd128ShuffleOp::Kind::kI8x2,
                                 shuffle_bytes.data());
      } else if (lanes == DemandedElementAnalysis::k8x4Low) {
        return __ Simd128Shuffle(og_left, og_right,
                                 Simd128ShuffleOp::Kind::kI8x4,
                                 shuffle_bytes.data());
      } else if (lanes == DemandedElementAnalysis::k8x8Low) {
        return __ Simd128Shuffle(og_left, og_right,
                                 Simd128ShuffleOp::Kind::kI8x8,
                                 shuffle_bytes.data());
      }
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::analyzer_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x2Low, v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x4Low, v8::internal::compiler::turboshaft::DemandedElementAnalysis::k8x8Low, v8::internal::kSimd128Size, LABEL_BLOCK, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128().
Member Data Documentation
analyzer_
template<class Next >
std::optional<WasmShuffleAnalyzer> v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::analyzer_ [private]
Definition at line 229 of file wasm-shuffle-reducer.h.
Referenced by v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Analyze(), and v8::internal::compiler::turboshaft::WasmShuffleReducer< Next >::Simd128Shuffle().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-shuffle-reducer.h