v8::internal::maglev::ConstructInvokeStubDeoptFrame Class Reference
#include <maglev-ir.h>
Public Member Functions
ConstructInvokeStubDeoptFrame (const MaglevCompilationUnit &unit, SourcePosition source_position, ValueNode *receiver, ValueNode *context, DeoptFrame *parent)
const MaglevCompilationUnit & unit () const
ValueNode *& receiver ()
ValueNode * receiver () const
ValueNode *& context ()
ValueNode * context () const
SourcePosition source_position () const
Private Member Functions
ConstructInvokeStubFrameData & data ()
const ConstructInvokeStubFrameData & data () const
Additional Inherited Members
Detailed Description
Definition at line 1674 of file maglev-ir.h.
Constructor & Destructor Documentation
ConstructInvokeStubDeoptFrame()
v8::internal::maglev::ConstructInvokeStubDeoptFrame::ConstructInvokeStubDeoptFrame (const MaglevCompilationUnit & unit, SourcePosition source_position, ValueNode * receiver, ValueNode * context, DeoptFrame * parent) [inline]
Definition at line 1676 of file maglev-ir.h.
      : DeoptFrame(ConstructInvokeStubFrameData{unit, source_position, receiver,
                                                context},
                   parent) {}
Member Function Documentation
context() [1/2]
ValueNode*& v8::internal::maglev::ConstructInvokeStubDeoptFrame::context () [inline]
Definition at line 1687 of file maglev-ir.h.
{ return data().context; }
References v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::context, and data().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
context() [2/2]
ValueNode* v8::internal::maglev::ConstructInvokeStubDeoptFrame::context () const [inline]
Definition at line 1688 of file maglev-ir.h.
{ return data().context; }
References v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::context, and data().
data() [1/2]
ConstructInvokeStubFrameData& v8::internal::maglev::ConstructInvokeStubDeoptFrame::data () [inline], [private]
Definition at line 1692 of file maglev-ir.h.
                                       {
    return data_.get<ConstructInvokeStubFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
Referenced by context(), receiver(), source_position(), and unit().
data() [2/2]
const ConstructInvokeStubFrameData& v8::internal::maglev::ConstructInvokeStubDeoptFrame::data () const [inline], [private]
Definition at line 1695 of file maglev-ir.h.
                                                   {
    return data_.get<ConstructInvokeStubFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
receiver() [1/2]
ValueNode*& v8::internal::maglev::ConstructInvokeStubDeoptFrame::receiver () [inline]
Definition at line 1685 of file maglev-ir.h.
{ return data().receiver; }
References data(), and v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::receiver.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
receiver() [2/2]
ValueNode* v8::internal::maglev::ConstructInvokeStubDeoptFrame::receiver () const [inline]
Definition at line 1686 of file maglev-ir.h.
{ return data().receiver; }
References data(), and v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::receiver.
source_position()
SourcePosition v8::internal::maglev::ConstructInvokeStubDeoptFrame::source_position () const [inline]
Definition at line 1689 of file maglev-ir.h.
{ return data().source_position; }
References data(), and v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::source_position.
Referenced by v8::internal::maglev::DeoptFrame::GetSourcePosition().
unit()
const MaglevCompilationUnit& v8::internal::maglev::ConstructInvokeStubDeoptFrame::unit () const [inline]
Definition at line 1684 of file maglev-ir.h.
{ return data().unit; }
References data(), and v8::internal::maglev::DeoptFrame::ConstructInvokeStubFrameData::unit.
Referenced by v8::internal::maglev::DeoptFrame::GetCompilationUnit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h