v8::internal::compiler::JSTypeHintLowering::LoweringResult Class Reference
#include <js-type-hint-lowering.h>
Public Member Functions
Node * value () const
Node * effect () const
Node * control () const
bool Changed () const
bool IsExit () const
bool IsSideEffectFree () const
Static Public Member Functions
static LoweringResult SideEffectFree (Node *value, Node *effect, Node *control)
static LoweringResult NoChange ()
static LoweringResult Exit (Node *control)
Private Types
enum class LoweringResultKind { kNoChange
, kSideEffectFree
, kExit
 }
Private Member Functions
LoweringResult (LoweringResultKind kind, Node *value, Node *effect, Node *control)
Private Attributes
LoweringResultKind kind_
Node * value_
Node * effect_
Node * control_
Detailed Description
Definition at line 59 of file js-type-hint-lowering.h.
Member Enumeration Documentation
LoweringResultKind
enum v8::internal::compiler::JSTypeHintLowering::LoweringResult::LoweringResultKind [strong], [private]
Enumerator
kNoChange
kSideEffectFree
kExit
Definition at line 91 of file js-type-hint-lowering.h.
{ kNoChange, kSideEffectFree, kExit };
Constructor & Destructor Documentation
LoweringResult()
v8::internal::compiler::JSTypeHintLowering::LoweringResult::LoweringResult (LoweringResultKind kind, Node * value, Node * effect, Node * control) [inline], [private]
Definition at line 93 of file js-type-hint-lowering.h.
        : kind_(kind), value_(value), effect_(effect), control_(control) {}
Referenced by Exit(), NoChange(), and SideEffectFree().
Member Function Documentation
Changed()
bool v8::internal::compiler::JSTypeHintLowering::LoweringResult::Changed () const [inline]
Definition at line 65 of file js-type-hint-lowering.h.
{ return kind_ != LoweringResultKind::kNoChange; }
References kind_, and kNoChange.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ApplyEarlyReduction(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOpWithImmediate(), v8::internal::compiler::BytecodeGraphBuilder::BuildCompareOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), and v8::internal::compiler::BytecodeGraphBuilder::BuildUnaryOp().
control()
Node* v8::internal::compiler::JSTypeHintLowering::LoweringResult::control () const [inline]
Definition at line 63 of file js-type-hint-lowering.h.
{ return control_; }
References control_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ApplyEarlyReduction(), Exit(), and SideEffectFree().
effect()
Node* v8::internal::compiler::JSTypeHintLowering::LoweringResult::effect () const [inline]
Definition at line 62 of file js-type-hint-lowering.h.
{ return effect_; }
References effect_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ApplyEarlyReduction(), and SideEffectFree().
Exit()
static LoweringResult v8::internal::compiler::JSTypeHintLowering::LoweringResult::Exit (Node * control) [inline], [static]
Definition at line 85 of file js-type-hint-lowering.h.
                                              {
      return LoweringResult(LoweringResultKind::kExit, nullptr, nullptr,
                            control);
    }
References control(), kExit, and LoweringResult().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceConstructOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceForInNextOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceForInPrepareOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceGetIteratorOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceLoadKeyedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceLoadNamedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceStoreKeyedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceStoreNamedOperation(), and v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation().
IsExit()
bool v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsExit () const [inline]
Definition at line 66 of file js-type-hint-lowering.h.
{ return kind_ == LoweringResultKind::kExit; }
References kExit, and kind_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ApplyEarlyReduction(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOpWithImmediate(), v8::internal::compiler::BytecodeGraphBuilder::BuildCompareOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), and v8::internal::compiler::BytecodeGraphBuilder::BuildUnaryOp().
IsSideEffectFree()
bool v8::internal::compiler::JSTypeHintLowering::LoweringResult::IsSideEffectFree () const [inline]
Definition at line 67 of file js-type-hint-lowering.h.
                                  {
      return kind_ == LoweringResultKind::kSideEffectFree;
    }
References kind_, and kSideEffectFree.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::ApplyEarlyReduction(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOpWithImmediate(), v8::internal::compiler::BytecodeGraphBuilder::BuildCompareOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), and v8::internal::compiler::BytecodeGraphBuilder::BuildUnaryOp().
NoChange()
static LoweringResult v8::internal::compiler::JSTypeHintLowering::LoweringResult::NoChange () [inline], [static]
Definition at line 80 of file js-type-hint-lowering.h.
                                     {
      return LoweringResult(LoweringResultKind::kNoChange, nullptr, nullptr,
                            nullptr);
    }
References kNoChange, and LoweringResult().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceConstructOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceForInNextOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceForInPrepareOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceGetIteratorOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceLoadKeyedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceLoadNamedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceStoreKeyedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceStoreNamedOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation(), and v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation().
SideEffectFree()
static LoweringResult v8::internal::compiler::JSTypeHintLowering::LoweringResult::SideEffectFree (Node * value, Node * effect, Node * control) [inline], [static]
Definition at line 71 of file js-type-hint-lowering.h.
                                                        {
      DCHECK_NOT_NULL(effect);
      DCHECK_NOT_NULL(control);
      DCHECK(value->op()->HasProperty(Operator::kNoThrow));
      return LoweringResult(LoweringResultKind::kSideEffectFree, value, effect,
                            control);
    }
References control(), v8::internal::DCHECK(), DCHECK_NOT_NULL, effect(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Operator::kNoThrow, kSideEffectFree, LoweringResult(), v8::internal::compiler::Node::op(), and value().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation(), v8::internal::compiler::JSTypeHintLowering::ReduceToNumberOperation(), and v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation().
value()
Node* v8::internal::compiler::JSTypeHintLowering::LoweringResult::value () const [inline]
Definition at line 61 of file js-type-hint-lowering.h.
{ return value_; }
References value_.
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildBinaryOpWithImmediate(), v8::internal::compiler::BytecodeGraphBuilder::BuildCompareOp(), v8::internal::compiler::BytecodeGraphBuilder::BuildNamedStore(), v8::internal::compiler::BytecodeGraphBuilder::BuildUnaryOp(), and SideEffectFree().
Member Data Documentation
control_
Node* v8::internal::compiler::JSTypeHintLowering::LoweringResult::control_ [private]
Definition at line 100 of file js-type-hint-lowering.h.
Referenced by control().
effect_
Node* v8::internal::compiler::JSTypeHintLowering::LoweringResult::effect_ [private]
Definition at line 99 of file js-type-hint-lowering.h.
Referenced by effect().
kind_
LoweringResultKind v8::internal::compiler::JSTypeHintLowering::LoweringResult::kind_ [private]
Definition at line 97 of file js-type-hint-lowering.h.
Referenced by Changed(), IsExit(), and IsSideEffectFree().
value_
Node* v8::internal::compiler::JSTypeHintLowering::LoweringResult::value_ [private]
Definition at line 98 of file js-type-hint-lowering.h.
Referenced by value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-type-hint-lowering.h