v8::internal::JSArrayBuffer::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Public Types
using Base = JSAPIObjectWithEmbedderSlots::BodyDescriptor
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 600 of file objects-body-descriptors-inl.h.
Member Typedef Documentation
Base
using v8::internal::JSArrayBuffer::BodyDescriptor::Base = JSAPIObjectWithEmbedderSlots::BodyDescriptor
Definition at line 603 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::JSArrayBuffer::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 606 of file objects-body-descriptors-inl.h.
                                                                    {
    // JSObject with wrapper field.
    IterateJSAPIObjectWithEmbedderSlotsHeader(map, obj, object_size, v);
    // JSArrayBuffer.
    IteratePointers(obj, JSArrayBuffer::kStartOfStrongFieldsOffset,
                    JSArrayBuffer::kEndOfStrongFieldsOffset, v);
    v->VisitExternalPointer(
        obj, obj->RawExternalPointerField(JSArrayBuffer::kExtensionOffset,
                                          kArrayBufferExtensionTag));
    // JSObject tail: possible embedder fields + in-object properties.
    if constexpr (JSArrayBuffer::kContainsEmbedderFields) {
      IterateJSAPIObjectWithEmbedderSlotsTail<JSArrayBuffer>(map, obj,
                                                             object_size, v);
    } else {
      IterateJSAPIObjectWithoutEmbedderSlotsTail<JSArrayBuffer>(map, obj,
                                                                object_size, v);
    }
  }
References v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsHeader(), v8::internal::BodyDescriptorBase::IteratePointers(), v8::internal::kArrayBufferExtensionTag, v8::internal::JSArrayBuffer::kContainsEmbedderFields, and v8::internal::ObjectVisitor::VisitExternalPointer().
Referenced by v8::internal::ScavengeVisitor::VisitJSArrayBuffer().
SizeOf()
static int v8::internal::JSArrayBuffer::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 626 of file objects-body-descriptors-inl.h.
                                                                       {
    return map->instance_size();
  }
Referenced by v8::internal::ScavengeVisitor::VisitJSArrayBuffer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h