v8::internal::BufferedUtf16CharacterStream Class Reference
Public Member Functions
BufferedUtf16CharacterStream ()
Protected Member Functions
bool ReadBlock (size_t position) final
virtual size_t FillBuffer (size_t position)=0
Protected Attributes
base::uc16 buffer_ [kBufferSize]
Static Protected Attributes
static const size_t kBufferSize = 512
Additional Inherited Members
Detailed Description
Definition at line 386 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
BufferedUtf16CharacterStream()
v8::internal::BufferedUtf16CharacterStream::BufferedUtf16CharacterStream ()
Definition at line 404 of file scanner-character-streams.cc.
    : Utf16CharacterStream(buffer_, buffer_, buffer_, 0) {}
Member Function Documentation
FillBuffer()
virtual size_t v8::internal::BufferedUtf16CharacterStream::FillBuffer (size_t position) [protected], [pure virtual]
Implemented in v8::internal::Utf8ExternalStreamingStream.
Referenced by ReadBlock().
ReadBlock()
bool v8::internal::BufferedUtf16CharacterStream::ReadBlock (size_t position) [final], [protected], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 407 of file scanner-character-streams.cc.
                                                            {
  DCHECK_EQ(buffer_start_, buffer_);
  buffer_pos_ = position;
  buffer_cursor_ = buffer_;
  buffer_end_ = buffer_ + FillBuffer(position);
  DCHECK_EQ(pos(), position);
  DCHECK_LE(buffer_end_, buffer_start_ + kBufferSize);
  return buffer_cursor_ < buffer_end_;
}
References buffer_, v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf16CharacterStream::buffer_pos_, v8::internal::Utf16CharacterStream::buffer_start_, DCHECK_EQ, DCHECK_LE, FillBuffer(), kBufferSize, and v8::internal::Utf16CharacterStream::pos().
Member Data Documentation
buffer_
base::uc16 v8::internal::BufferedUtf16CharacterStream::buffer_[kBufferSize] [protected]
Definition at line 401 of file scanner-character-streams.cc.
Referenced by v8::internal::Utf8ExternalStreamingStream::FillBuffer(), v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), and ReadBlock().
kBufferSize
const size_t v8::internal::BufferedUtf16CharacterStream::kBufferSize = 512 [static], [protected]
Definition at line 391 of file scanner-character-streams.cc.
Referenced by v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk(), and ReadBlock().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc