v8::anonymous_namespace{d8-test.cc}::FastCApiObject Class Reference
Public Types
typedef int32_t Type
Public Member Functions
int fast_call_count () const
int slow_call_count () const
void reset_counts ()
Static Public Member Functions
static FastCApiObject & instance ()
static int ThrowNoFallbackFastCallback (Local< Object > receiver)
static void ThrowFallbackSlowCallback (const FunctionCallbackInfo< Value > &info)
static void CopyStringFastCallback (Local< Object > receiver, const FastOneByteString &source, Local< Object > out, FastApiCallbackOptions &options)
static void CopyStringSlowCallback (const FunctionCallbackInfo< Value > &info)
static double AddAllFastCallback (Local< Object > receiver, int32_t arg_i32, uint32_t arg_u32, int64_t arg_i64, uint64_t arg_u64, float arg_f32, double arg_f64, FastApiCallbackOptions &options)
static double AddAllFastCallbackNoOptions (Local< Object > receiver, int32_t arg_i32, uint32_t arg_u32, int64_t arg_i64, uint64_t arg_u64, float arg_f32, double arg_f64)
static void AddAllSlowCallback (const FunctionCallbackInfo< Value > &info)
static Type AddAllSequenceJSArrayHelper (v8::Isolate *isolate, Local< Array > seq_arg)
static Type AddAllSequenceFastCallback (Local< Object > receiver, Local< Object > seq_arg, FastApiCallbackOptions &options)
static void AddAllSequenceSlowCallback (const FunctionCallbackInfo< Value > &info)
template<typename T >
static Type AddAllTypedArrayFastCallback (Local< Object > receiver, Local< Value > typed_array_arg, FastApiCallbackOptions &options)
static void AddAllTypedArraySlowCallback (const FunctionCallbackInfo< Value > &info)
static int Add32BitIntFastCallback (v8::Local< v8::Object > receiver, int32_t arg_i32, uint32_t arg_u32, FastApiCallbackOptions &options)
static void Add32BitIntSlowCallback (const FunctionCallbackInfo< Value > &info)
static int AddAll32BitIntFastCallback_8Args (Local< Object > receiver, int32_t arg1_i32, int32_t arg2_i32, int32_t arg3_i32, uint32_t arg4_u32, uint32_t arg5_u32, uint32_t arg6_u32, uint32_t arg7_u32, uint32_t arg8_u32, FastApiCallbackOptions &options)
static int AddAll32BitIntFastCallback_6Args (Local< Object > receiver, int32_t arg1_i32, int32_t arg2_i32, int32_t arg3_i32, uint32_t arg4_u32, uint32_t arg5_u32, uint32_t arg6_u32, FastApiCallbackOptions &options)
static int AddAll32BitIntFastCallback_5Args (Local< Object > receiver, int32_t arg1_i32, int32_t arg2_i32, int32_t arg3_i32, uint32_t arg4_u32, uint32_t arg5_u32, FastApiCallbackOptions &options)
static void AddAll32BitIntSlowCallback (const FunctionCallbackInfo< Value > &info)
template<v8::CTypeInfo::Flags flags>
static double AddAllAnnotateFastCallback (Local< Object > receiver, int32_t arg_i32, uint32_t arg_u32, int64_t arg_i64, uint64_t arg_u64, FastApiCallbackOptions &options)
static void AddAllAnnotateSlowCallback (const FunctionCallbackInfo< Value > &info)
template<typename IntegerT >
static bool EnforceRangeCompare (Local< Object > receiver, double real_arg, IntegerT checked_arg, FastApiCallbackOptions &options)
template<typename IntegerT >
static void EnforceRangeCompareSlowCallback (const FunctionCallbackInfo< Value > &info)
template<typename IntegerT >
static double ClampCompareCompute (bool in_range, double real_arg, IntegerT checked_arg)
template<typename IntegerT >
static double ClampCompare (Local< Object > receiver, bool in_range, double real_arg, IntegerT checked_arg, FastApiCallbackOptions &options)
template<typename IntegerT >
static void ClampCompareSlowCallback (const FunctionCallbackInfo< Value > &info)
static bool IsFastCApiObjectFastCallback (v8::Local< v8::Object > receiver, v8::Local< v8::Value > arg, FastApiCallbackOptions &options)
static void IsFastCApiObjectSlowCallback (const FunctionCallbackInfo< Value > &info)
static void CallToNumberFastCallback (Local< Object > receiver, Local< Object > arg, FastApiCallbackOptions &options)
static void CallToNumberSlowCallback (const FunctionCallbackInfo< Value > &info)
static bool TestWasmMemoryFastCallback (Local< Object > receiver, uint32_t address, FastApiCallbackOptions &options)
static void TestWasmMemorySlowCallback (const FunctionCallbackInfo< Value > &info)
static void AssertIsExternal (const FunctionCallbackInfo< Value > &info)
static void * GetPointerFastCallback (Local< Object > receiver, FastApiCallbackOptions &options)
static void GetPointerSlowCallback (const FunctionCallbackInfo< Value > &info)
static void * GetNullPointerFastCallback (Local< Object > receiver, FastApiCallbackOptions &options)
static void GetNullPointerSlowCallback (const FunctionCallbackInfo< Value > &info)
static void * PassPointerFastCallback (Local< Object > receiver, void *pointer, FastApiCallbackOptions &options)
static void PassPointerSlowCallback (const FunctionCallbackInfo< Value > &info)
static bool ComparePointersFastCallback (Local< Object > receiver, void *pointer_a, void *pointer_b, FastApiCallbackOptions &options)
static void ComparePointersSlowCallback (const FunctionCallbackInfo< Value > &info)
static int64_t sumInt64FastCallback (Local< Object > receiver, int64_t a, int64_t b, FastApiCallbackOptions &options)
template<typename T >
static bool Convert (double value, T *out_result)
static void sumInt64AsNumberSlowCallback (const FunctionCallbackInfo< Value > &info)
static void sumInt64AsBigIntSlowCallback (const FunctionCallbackInfo< Value > &info)
static uint64_t sumUint64FastCallback (Local< Object > receiver, uint64_t a, uint64_t b, FastApiCallbackOptions &options)
static void sumUint64AsNumberSlowCallback (const FunctionCallbackInfo< Value > &info)
static void sumUint64AsBigIntSlowCallback (const FunctionCallbackInfo< Value > &info)
static void AttributeGetterSlowCallback (const FunctionCallbackInfo< Value > &info)
static int AttributeGetterFastCallback (Local< Object > receiver, FastApiCallbackOptions &options)
static void AttributeSetterSlowCallback (const FunctionCallbackInfo< Value > &info)
static void AttributeSetterFastCallback (Local< Object > receiver, int32_t value, FastApiCallbackOptions &options)
static void FastCallCount (const FunctionCallbackInfo< Value > &info)
static void SlowCallCount (const FunctionCallbackInfo< Value > &info)
static void ResetCounts (const FunctionCallbackInfo< Value > &info)
static void SupportsFPParams (const FunctionCallbackInfo< Value > &info)
Static Public Attributes
static const int kV8WrapperObjectIndex = 1
Static Private Member Functions
static bool IsValidApiObject (Local< Object > object)
static FastCApiObject * UnwrapObject (Local< Object > object)
Private Attributes
int fast_call_count_ = 0
int slow_call_count_ = 0
int attribute_value_ = 0
bool supports_fp_params_ = false
Detailed Description
Definition at line 41 of file d8-test.cc.
Member Typedef Documentation
Type
typedef int32_t v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Type
Definition at line 213 of file d8-test.cc.
Member Function Documentation
Add32BitIntFastCallback()
static int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntFastCallback (v8::Local< v8::Object > receiver, int32_t arg_i32, uint32_t arg_u32, FastApiCallbackOptions & options) [inline], [static]
Definition at line 465 of file d8-test.cc.
                                                                      {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    return arg_i32 + arg_u32;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
Add32BitIntSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 474 of file d8-test.cc.
                                                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    double sum = 0;
    if (info.Length() > 0 && info[0]->IsNumber()) {
      sum += info[0]->Int32Value(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 1 && info[1]->IsNumber()) {
      sum += info[1]->Uint32Value(isolate->GetCurrentContext()).FromJust();
    }
    info.GetReturnValue().Set(Number::New(isolate, sum));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
AddAll32BitIntFastCallback_5Args()
static int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntFastCallback_5Args (Local< Object > receiver, int32_t arg1_i32, int32_t arg2_i32, int32_t arg3_i32, uint32_t arg4_u32, uint32_t arg5_u32, FastApiCallbackOptions & options) [inline], [static]
Definition at line 561 of file d8-test.cc.
                                       {
    return AddAll32BitIntFastCallback_6Args(
        receiver, arg1_i32, arg2_i32, arg3_i32, arg4_u32, arg5_u32, 0, options);
  }
AddAll32BitIntFastCallback_6Args()
static int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntFastCallback_6Args (Local< Object > receiver, int32_t arg1_i32, int32_t arg2_i32, int32_t arg3_i32, uint32_t arg4_u32, uint32_t arg5_u32, uint32_t arg6_u32, FastApiCallbackOptions & options) [inline], [static]
Definition at line 546 of file d8-test.cc.
                                       {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    int64_t result = static_cast<int64_t>(arg1_i32) + arg2_i32 + arg3_i32 +
                     arg4_u32 + arg5_u32 + arg6_u32;
    if (result > INT_MAX) return INT_MAX;
    if (result < INT_MIN) return INT_MIN;
    return static_cast<int>(result);
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS, and v8::base::internal::result.
AddAll32BitIntFastCallback_8Args()
static int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntFastCallback_8Args (Local< Object > receiver, int32_t arg1_i32, int32_t arg2_i32, int32_t arg3_i32, uint32_t arg4_u32, uint32_t arg5_u32, uint32_t arg6_u32, uint32_t arg7_u32, uint32_t arg8_u32, FastApiCallbackOptions & options) [inline], [static]
Definition at line 532 of file d8-test.cc.
                                                                             {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    int64_t result = static_cast<int64_t>(arg1_i32) + arg2_i32 + arg3_i32 +
                     arg4_u32 + arg5_u32 + arg6_u32 + arg7_u32 + arg8_u32;
    if (result > INT_MAX) return INT_MAX;
    if (result < INT_MIN) return INT_MIN;
    return static_cast<int>(result);
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS, and v8::base::internal::result.
AddAll32BitIntSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 568 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    Local<Context> context = isolate->GetCurrentContext();
    double sum = 0;
    if (info.Length() > 0 && info[0]->IsNumber()) {
      sum += info[0]->Int32Value(context).FromJust();
    }
    if (info.Length() > 1 && info[1]->IsNumber()) {
      sum += info[1]->Int32Value(context).FromJust();
    }
    if (info.Length() > 2 && info[2]->IsNumber()) {
      sum += info[2]->Int32Value(context).FromJust();
    }
    if (info.Length() > 3 && info[3]->IsNumber()) {
      sum += info[3]->Uint32Value(context).FromJust();
    }
    if (info.Length() > 4 && info[4]->IsNumber()) {
      sum += info[4]->Uint32Value(context).FromJust();
    }
    if (info.Length() > 5 && info[5]->IsNumber()) {
      sum += info[5]->Uint32Value(context).FromJust();
    }
    if (info.Length() > 7 && info[6]->IsNumber() && info[7]->IsNumber()) {
      // info[6] and info[7] only get handled together, because we want to
      // have functions in the list of overloads with 6 parameters and with 8
      // parameters, but not with 7 parameters.
      sum += info[6]->Uint32Value(context).FromJust();
      sum += info[7]->Uint32Value(context).FromJust();
    }
    info.GetReturnValue().Set(Number::New(isolate, sum));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
AddAllAnnotateFastCallback()
template<v8::CTypeInfo::Flags flags>
static double v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateFastCallback (Local< Object > receiver, int32_t arg_i32, uint32_t arg_u32, int64_t arg_i64, uint64_t arg_u64, FastApiCallbackOptions & options) [inline], [static]
Definition at line 624 of file d8-test.cc.
                                                                            {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_NOT_NULL(self);
    self->fast_call_count_++;
    return static_cast<double>(arg_i32) + static_cast<double>(arg_u32) +
           static_cast<double>(arg_i64) + static_cast<double>(arg_u64);
  }
References CHECK_NOT_NULL.
AddAllAnnotateSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 636 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    double sum = 0;
    if (info.Length() > 1 && info[1]->IsNumber()) {
      sum += info[1]->Int32Value(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 2 && info[2]->IsNumber()) {
      sum += info[2]->Uint32Value(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 3 && info[3]->IsNumber()) {
      sum += info[3]->IntegerValue(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 4 && info[4]->IsNumber()) {
      sum += info[4]->IntegerValue(isolate->GetCurrentContext()).FromJust();
    }
    info.GetReturnValue().Set(Number::New(isolate, sum));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
AddAllFastCallback()
static double v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllFastCallback (Local< Object > receiver, int32_t arg_i32, uint32_t arg_u32, int64_t arg_i64, uint64_t arg_u64, float arg_f32, double arg_f64, FastApiCallbackOptions & options) [inline], [static]
Definition at line 133 of file d8-test.cc.
                                                                    {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    return static_cast<double>(arg_i32) + static_cast<double>(arg_u32) +
           static_cast<double>(arg_i64) + static_cast<double>(arg_u64) +
           static_cast<double>(arg_f32) + arg_f64;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
AddAllFastCallbackNoOptions()
static double v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllFastCallbackNoOptions (Local< Object > receiver, int32_t arg_i32, uint32_t arg_u32, int64_t arg_i64, uint64_t arg_u64, float arg_f32, double arg_f64) [inline], [static]
Definition at line 159 of file d8-test.cc.
                                                                           {
    FastCApiObject* self = UnwrapObject(receiver);
    if (!self) {
      self = &FastCApiObject::instance();
    }
    self->fast_call_count_++;
    return static_cast<double>(arg_i32) + static_cast<double>(arg_u32) +
           static_cast<double>(arg_i64) + static_cast<double>(arg_u64) +
           static_cast<double>(arg_f32) + arg_f64;
  }
AddAllSequenceFastCallback()
static Type v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback (Local< Object > receiver, Local< Object > seq_arg, FastApiCallbackOptions & options) [inline], [static]
Definition at line 269 of file d8-test.cc.
                                                                          {
    if (seq_arg->IsUint32Array()) {
      return AddAllTypedArrayFastCallback<uint32_t>(receiver, seq_arg, options);
    }
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    HandleScope handle_scope(options.isolate);
    if (!seq_arg->IsArray()) {
      options.isolate->ThrowError(
          "This method expects an array as a first argument.");
      return 0;
    }
    Local<Array> array = seq_arg.As<Array>();
    uint32_t length = array->Length();
    if (length > 1024) {
      options.isolate->ThrowError(
          "Invalid length of array, must be between 0 and 1024.");
      return 0;
    }
    Type buffer[1024];
    bool result = TryToCopyAndConvertArrayToCppBuffer<
        CTypeInfoBuilder<Type>::Build().GetId(), Type>(array, buffer, 1024);
    if (!result) {
      return AddAllSequenceJSArrayHelper(options.isolate, array);
    }
    DCHECK_EQ(array->Length(), length);
    Type sum = 0;
    for (uint32_t i = 0; i < length; ++i) {
      sum += buffer[i];
    }
    return sum;
  }
References v8::Local< T >::As(), v8::CTypeInfoBuilder< T, Flags >::Build(), CHECK_SELF_OR_THROW_FAST_OPTIONS, DCHECK_EQ, v8::CTypeInfo::GetId(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Value::IsArray(), v8::FastApiCallbackOptions::isolate, v8::Value::IsUint32Array(), v8::internal::length, v8::base::internal::result, v8::Isolate::ThrowError(), and v8::TryToCopyAndConvertArrayToCppBuffer().
AddAllSequenceJSArrayHelper()
static Type v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper (v8::Isolate * isolate, Local< Array > seq_arg) [inline], [static]
Definition at line 231 of file d8-test.cc.
                                                                {
    if (i::v8_flags.fuzzing) {
      // TODO(418936518): The code below may trigger deopt. Once deopt support
      // for fast API calls with return values is supported, remove this early
      // return here again.
      return 0;
    }
    Type sum = 0;
    uint32_t length = seq_arg->Length();
    if (length > 1024) {
      isolate->ThrowError(
          "Invalid length of array, must be between 0 and 1024.");
      return sum;
    }
    for (uint32_t i = 0; i < length; ++i) {
      v8::MaybeLocal<v8::Value> maybe_element =
          seq_arg->Get(isolate->GetCurrentContext(),
                       v8::Integer::NewFromUnsigned(isolate, i));
      if (maybe_element.IsEmpty()) return sum;
      v8::Local<v8::Value> element = maybe_element.ToLocalChecked();
      if (element->IsNumber()) {
        double value = element->ToNumber(isolate->GetCurrentContext())
                           .ToLocalChecked()
                           ->Value();
        sum += value;
      } else if (element->IsUndefined()) {
        // Hole: ignore the element.
      } else {
        isolate->ThrowError("unexpected element type in JSArray");
        return sum;
      }
    }
    return sum;
  }
References v8::Isolate::GetCurrentContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::MaybeLocal< T >::IsEmpty(), v8::Value::IsNumber(), v8::Value::IsUndefined(), v8::internal::length, v8::Integer::NewFromUnsigned(), v8::Isolate::ThrowError(), v8::MaybeLocal< T >::ToLocalChecked(), v8::Value::ToNumber(), v8::internal::v8_flags, and v8::internal::value.
AddAllSequenceSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 310 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    HandleScope handle_scope(isolate);
    if (info.Length() < 1) {
      self->slow_call_count_++;
      isolate->ThrowError("This method expects at least 1 arguments.");
      return;
    }
    if (info[0]->IsTypedArray()) {
      AddAllTypedArraySlowCallback(info);
      return;
    }
    if (info[0]->IsNumber()) {
      AddAllSlowCallback(info);
      return;
    }
    self->slow_call_count_++;
    if (info[0]->IsUndefined()) {
      Type dummy_result = 0;
      info.GetReturnValue().Set(Number::New(isolate, dummy_result));
      return;
    }
    if (!info[0]->IsArray()) {
      isolate->ThrowError("This method expects an array as a first argument.");
      return;
    }
    Local<Array> seq_arg = info[0].As<Array>();
    Type sum = AddAllSequenceJSArrayHelper(isolate, seq_arg);
    info.GetReturnValue().Set(Number::New(isolate, sum));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::IsNumber(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
AddAllSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 174 of file d8-test.cc.
                                                                          {
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    double sum = 0;
    if (info.Length() > 0 && info[0]->IsNumber()) {
      sum += info[0]->Int32Value(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 1 && info[1]->IsNumber()) {
      sum += info[1]->Uint32Value(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 2 && info[2]->IsNumber()) {
      sum += info[2]->IntegerValue(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 3 && info[3]->IsNumber()) {
      sum += info[3]->IntegerValue(isolate->GetCurrentContext()).FromJust();
    }
    if (info.Length() > 4 && info[4]->IsNumber()) {
      sum += info[4]->NumberValue(isolate->GetCurrentContext()).FromJust();
    } else {
      sum += std::numeric_limits<double>::quiet_NaN();
    }
    if (info.Length() > 5 && info[5]->IsNumber()) {
      sum += info[5]->NumberValue(isolate->GetCurrentContext()).FromJust();
    } else {
      sum += std::numeric_limits<double>::quiet_NaN();
    }
    info.GetReturnValue().Set(Number::New(isolate, sum));
  }
References CHECK_SELF_OR_THROW_SLOW, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), and v8::FunctionCallbackInfo< T >::This().
AddAllTypedArrayFastCallback()
template<typename T >
static Type v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArrayFastCallback (Local< Object > receiver, Local< Value > typed_array_arg, FastApiCallbackOptions & options) [inline], [static]
Definition at line 368 of file d8-test.cc.
                                                                            {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    HandleScope handle_scope(options.isolate);
    if (!typed_array_arg->IsTypedArray()) {
      options.isolate->ThrowError(
          "This method expects a TypedArray as a first argument.");
      return 0;
    }
    T* memory = reinterpret_cast<T*>(
        typed_array_arg.As<TypedArray>()->Buffer()->Data());
    size_t length = typed_array_arg.As<TypedArray>()->ByteLength() / sizeof(T);
    double sum = 0;
    for (size_t i = 0; i < length; ++i) {
      sum += static_cast<double>(memory[i]);
    }
    return static_cast<Type>(sum);
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_FAST_OPTIONS, v8::Data::Data(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::FastApiCallbackOptions::isolate, v8::internal::length, T, and v8::Isolate::ThrowError().
AddAllTypedArraySlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 391 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    if (info.Length() < 1) {
      isolate->ThrowError("This method expects at least 1 arguments.");
      return;
    }
    if (!info[0]->IsTypedArray()) {
      isolate->ThrowError(
          "This method expects a TypedArray as a second argument.");
      return;
    }
    Local<TypedArray> typed_array_arg = info[0].As<TypedArray>();
    size_t length = typed_array_arg->Length();
    void* data = typed_array_arg->Buffer()->GetBackingStore()->Data();
    if (typed_array_arg->IsUint8Array() || typed_array_arg->IsInt32Array() ||
        typed_array_arg->IsUint32Array() ||
        typed_array_arg->IsBigInt64Array() ||
        typed_array_arg->IsBigUint64Array()) {
      int64_t sum = 0;
      for (unsigned i = 0; i < length; ++i) {
        if (typed_array_arg->IsUint8Array()) {
          sum += static_cast<uint8_t*>(data)[i];
        } else if (typed_array_arg->IsInt32Array()) {
          sum += static_cast<int32_t*>(data)[i];
        } else if (typed_array_arg->IsUint32Array()) {
          sum += static_cast<uint32_t*>(data)[i];
        } else if (typed_array_arg->IsBigInt64Array()) {
          sum += static_cast<int64_t*>(data)[i];
        } else if (typed_array_arg->IsBigUint64Array()) {
          sum += static_cast<uint64_t*>(data)[i];
        }
      }
      info.GetReturnValue().Set(Number::New(isolate, sum));
    } else if (typed_array_arg->IsFloat32Array() ||
               typed_array_arg->IsFloat64Array()) {
      double sum = 0;
      for (unsigned i = 0; i < length; ++i) {
        if (typed_array_arg->IsFloat32Array()) {
          sum += static_cast<float*>(data)[i];
        } else if (typed_array_arg->IsFloat64Array()) {
          sum += static_cast<double*>(data)[i];
        }
      }
      info.GetReturnValue().Set(Number::New(isolate, sum));
    } else {
      isolate->ThrowError("TypedArray type is not supported.");
      return;
    }
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::FunctionCallbackInfo< T >::Length(), v8::internal::length, v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
AssertIsExternal()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AssertIsExternal (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1023 of file d8-test.cc.
                                                                        {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    Local<Value> value = info[0];
    if (!value->IsExternal()) {
      info.GetIsolate()->ThrowError("Did not get an external.");
    }
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), v8::internal::ValidateCallbackInfo(), and v8::internal::value.
AttributeGetterFastCallback()
static int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeGetterFastCallback (Local< Object > receiver, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1359 of file d8-test.cc.
                                                                          {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    return self->attribute_value_;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
AttributeGetterSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeGetterSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1352 of file d8-test.cc.
                                               {
    FastCApiObject* self = UnwrapObject(info.This());
    self->slow_call_count_++;
    info.GetReturnValue().Set(self->attribute_value_);
  }
References v8::FunctionCallbackInfo< T >::GetReturnValue(), and v8::FunctionCallbackInfo< T >::This().
AttributeSetterFastCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterFastCallback (Local< Object > receiver, int32_t value, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1396 of file d8-test.cc.
                                                                           {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS();
    self->fast_call_count_++;
    self->attribute_value_ = value;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS, and v8::internal::value.
AttributeSetterSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1377 of file d8-test.cc.
                                               {
    FastCApiObject* self = UnwrapObject(info.This());
    self->slow_call_count_++;
    if (info.Length() < 1 || !info[0]->IsNumber()) {
      info.GetIsolate()->ThrowError(
          "The attribute requires a number as a new value");
      return;
    }
    double double_val =
        info[0]->NumberValue(info.GetIsolate()->GetCurrentContext()).FromJust();
    if (!base::IsValueInRangeForNumericType<int>(double_val)) {
      info.GetIsolate()->ThrowError(
          "New value of attribute is not within int32 range");
      return;
    }
    self->attribute_value_ = static_cast<int>(double_val);
  }
References v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::FunctionCallbackInfo< T >::This(), and v8::Isolate::ThrowError().
CallToNumberFastCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberFastCallback (Local< Object > receiver, Local< Object > arg, FastApiCallbackOptions & options) [inline], [static]
Definition at line 954 of file d8-test.cc.
                                                                        {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS();
    self->fast_call_count_++;
    HandleScope handle_scope(options.isolate);
    USE(arg->ToNumber(options.isolate->GetCurrentContext()));
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS, v8::Isolate::GetCurrentContext(), v8::FastApiCallbackOptions::isolate, v8::Value::ToNumber(), and USE.
CallToNumberSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 965 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    if (info.Length() < 1) {
      info.GetIsolate()->ThrowError(
          "is_valid_api_object should be called with an argument");
      return;
    }
    USE(info[0]->ToNumber(info.GetIsolate()->GetCurrentContext()));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::Length(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), v8::internal::ToNumber(), USE, and v8::internal::ValidateCallbackInfo().
ClampCompare()
template<typename IntegerT >
static double v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompare (Local< Object > receiver, bool in_range, double real_arg, IntegerT checked_arg, FastApiCallbackOptions & options) [inline], [static]
Definition at line 840 of file d8-test.cc.
                                                              {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_NOT_NULL(self);
    self->fast_call_count_++;
    double result = ClampCompareCompute(in_range, real_arg, checked_arg);
    return static_cast<double>(result);
  }
References CHECK_NOT_NULL, and v8::base::internal::result.
ClampCompareCompute()
template<typename IntegerT >
static double v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareCompute (bool in_range, double real_arg, IntegerT checked_arg) [inline], [static]
Definition at line 797 of file d8-test.cc.
                                                          {
    if (i::v8_flags.fuzzing) {
      return static_cast<double>(checked_arg);
    }
    if (!in_range) {
      IntegerT lower_bound = std::numeric_limits<IntegerT>::min();
      IntegerT upper_bound = std::numeric_limits<IntegerT>::max();
      if (lower_bound < internal::kMinSafeInteger) {
        lower_bound = static_cast<IntegerT>(internal::kMinSafeInteger);
      }
      if (upper_bound > internal::kMaxSafeInteger) {
        upper_bound = static_cast<IntegerT>(internal::kMaxSafeInteger);
      }
      CHECK(!std::isnan(real_arg));
      if (real_arg < static_cast<double>(lower_bound)) {
        CHECK_EQ(lower_bound, checked_arg);
      } else if (real_arg > static_cast<double>(upper_bound)) {
        CHECK_EQ(upper_bound, checked_arg);
      } else {
        FATAL("Expected value to be out of range.");
      }
    } else if (!std::isnan(real_arg)) {
      if (real_arg != checked_arg) {
        // Check if rounding towards nearest even number happened.
        double diff = std::fabs(real_arg - checked_arg);
        CHECK_LE(diff, 0.5);
        if (diff == 0) {
          // Check if rounding towards nearest even number happened.
          CHECK_EQ(0, checked_arg % 2);
        } else if (checked_arg % 2 == 1) {
          // Behave as if rounding towards nearest even number *has*
          // happened (as it does on the fast path).
          checked_arg += 1;
        }
      } else {
        CHECK_EQ(static_cast<IntegerT>(real_arg), checked_arg);
      }
    }
    return checked_arg;
  }
References CHECK, CHECK_EQ, CHECK_LE, FATAL, v8::internal::kMaxSafeInteger, v8::internal::kMinSafeInteger, and v8::internal::v8_flags.
ClampCompareSlowCallback()
template<typename IntegerT >
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 852 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    double real_arg = 0;
    if (info.Length() > 1 && info[1]->IsNumber()) {
      real_arg = info[1]->NumberValue(isolate->GetCurrentContext()).FromJust();
    }
    double checked_arg_dbl = std::numeric_limits<double>::max();
    if (info.Length() > 2 && info[2]->IsNumber()) {
      checked_arg_dbl = info[2].As<Number>()->Value();
    }
    bool in_range =
        info[0]->IsBoolean() && info[0]->BooleanValue(isolate) &&
        base::IsValueInRangeForNumericType<IntegerT>(real_arg) &&
        base::IsValueInRangeForNumericType<IntegerT>(checked_arg_dbl);
    IntegerT checked_arg = std::numeric_limits<IntegerT>::max();
    if (in_range) {
      if (checked_arg_dbl != std::numeric_limits<double>::max()) {
        checked_arg = static_cast<IntegerT>(checked_arg_dbl);
      }
      double result = ClampCompareCompute(in_range, real_arg, checked_arg);
      info.GetReturnValue().Set(Number::New(isolate, result));
    } else {
      IntegerT clamped = std::numeric_limits<IntegerT>::max();
      if (std::isnan(checked_arg_dbl) || std::isnan(real_arg)) {
        clamped = 0;
      } else {
        IntegerT lower_bound = std::numeric_limits<IntegerT>::min();
        IntegerT upper_bound = std::numeric_limits<IntegerT>::max();
        if (lower_bound < internal::kMinSafeInteger) {
          lower_bound = static_cast<IntegerT>(internal::kMinSafeInteger);
        }
        if (upper_bound > internal::kMaxSafeInteger) {
          upper_bound = static_cast<IntegerT>(internal::kMaxSafeInteger);
        }
        clamped = std::clamp(real_arg, static_cast<double>(lower_bound),
                             static_cast<double>(upper_bound));
      }
      info.GetReturnValue().Set(Number::New(isolate, clamped));
    }
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::internal::kMaxSafeInteger, v8::internal::kMinSafeInteger, v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::base::internal::result, v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
ComparePointersFastCallback()
static bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersFastCallback (Local< Object > receiver, void * pointer_a, void * pointer_b, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1118 of file d8-test.cc.
                                                                           {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(false);
    self->fast_call_count_++;
    return pointer_a == pointer_b;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
ComparePointersSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1128 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (info.Length() != 2) {
      info.GetIsolate()->ThrowError(
          "Invalid number of arguments, expected two.");
      return;
    }
    Local<Value> value_a = info[0];
    Local<Value> value_b = info[1];
    void* pointer_a;
    if (value_a->IsNull()) {
      pointer_a = nullptr;
    } else if (value_a->IsExternal()) {
      pointer_a = value_a.As<External>()->Value();
    } else {
      info.GetIsolate()->ThrowError(
          "Did not get an external as first parameter.");
      return;
    }
    void* pointer_b;
    if (value_b->IsNull()) {
      pointer_b = nullptr;
    } else if (value_b->IsExternal()) {
      pointer_b = value_b.As<External>()->Value();
    } else {
      info.GetIsolate()->ThrowError(
          "Did not get an external as second parameter.");
      return;
    }
    info.GetReturnValue().Set(pointer_a == pointer_b);
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
Convert()
template<typename T >
static bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Convert (double value, T * out_result) [inline], [static]
Definition at line 1180 of file d8-test.cc.
                                                   {
    if (!base::IsValueInRangeForNumericType<T>(value)) return false;
    *out_result = static_cast<T>(value);
    return true;
  }
References v8::internal::value.
CopyStringFastCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringFastCallback (Local< Object > receiver, const FastOneByteString & source, Local< Object > out, FastApiCallbackOptions & options) [inline], [static]
Definition at line 89 of file d8-test.cc.
                                                                      {
    FastCApiObject* self = UnwrapObject(receiver);
    self->fast_call_count_++;
    HandleScope handle_scope(options.isolate);
    if (!out->IsUint8Array()) {
      options.isolate->ThrowError(
          "Invalid parameter, the second parameter has to be a a Uint8Array.");
      return;
    }
    Local<Uint8Array> array = out.As<Uint8Array>();
    if (array->Length() < source.length) {
      options.isolate->ThrowError(
          "Invalid parameter, destination array is too small.");
      return;
    }
    uint8_t* memory =
        reinterpret_cast<uint8_t*>(out.As<Uint8Array>()->Buffer()->Data());
    memcpy(memory, source.data, source.length);
  }
References v8::Local< T >::As(), v8::Data::Data(), v8::FastOneByteString::data, v8::FastApiCallbackOptions::isolate, v8::Value::IsUint8Array(), v8::FastOneByteString::length, and v8::Isolate::ThrowError().
CopyStringSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 113 of file d8-test.cc.
                                                                              {
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
  }
References CHECK_SELF_OR_THROW_SLOW, and v8::FunctionCallbackInfo< T >::This().
EnforceRangeCompare()
template<typename IntegerT >
static bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompare (Local< Object > receiver, double real_arg, IntegerT checked_arg, FastApiCallbackOptions & options) [inline], [static]
Definition at line 708 of file d8-test.cc.
                                                                   {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_NOT_NULL(self);
    self->fast_call_count_++;
    if (!base::IsValueInRangeForNumericType<IntegerT>(real_arg)) {
      return false;
    }
    return static_cast<IntegerT>(real_arg) == checked_arg;
  }
References CHECK_NOT_NULL.
EnforceRangeCompareSlowCallback()
template<typename IntegerT >
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 722 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    double real_arg = 0;
    if (info.Length() > 0 && info[0]->IsNumber()) {
      real_arg = info[0]->NumberValue(isolate->GetCurrentContext()).FromJust();
    }
    // Special range checks for int64 and uint64. uint64_max rounds to 2^64 when
    // converted to double, so 2^64 would be considered within uint64 range even
    // though it's not. For int64 the same happens with 2^63.
    bool in_range = base::IsValueInRangeForNumericType<IntegerT>(real_arg);
    if (in_range) {
      IntegerT checked_arg = 0;
      if (info.Length() > 1 && info[1]->IsNumber()) {
        double checked_arg_as_double =
            info[1]->NumberValue(isolate->GetCurrentContext()).FromJust();
        if (base::IsValueInRangeForNumericType<IntegerT>(
                checked_arg_as_double)) {
          checked_arg = static_cast<IntegerT>(checked_arg_as_double);
        }
      }
      info.GetReturnValue().Set(static_cast<IntegerT>(real_arg) == checked_arg);
    } else {
      info.GetIsolate()->ThrowError("Argument out of range.");
    }
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::Isolate::GetCurrentContext(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
fast_call_count()
int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::fast_call_count () const [inline]
Definition at line 1440 of file d8-test.cc.
{ return fast_call_count_; }
FastCallCount()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::FastCallCount (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1413 of file d8-test.cc.
                                                                     {
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    info.GetReturnValue().Set(
        Number::New(info.GetIsolate(), self->fast_call_count()));
  }
References CHECK_SELF_OR_THROW_SLOW, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Number::New(), and v8::FunctionCallbackInfo< T >::This().
GetNullPointerFastCallback()
static void* v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetNullPointerFastCallback (Local< Object > receiver, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1061 of file d8-test.cc.
                                                                           {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(nullptr);
    self->fast_call_count_++;
    return nullptr;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
GetNullPointerSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetNullPointerSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1070 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    info.GetReturnValue().Set(v8::Null(isolate));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Null(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
GetPointerFastCallback()
static void* v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerFastCallback (Local< Object > receiver, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1035 of file d8-test.cc.
                                                                       {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(nullptr);
    self->fast_call_count_++;
    if (i::v8_flags.fuzzing) {
      return nullptr;
    }
    return static_cast<void*>(self);
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS, and v8::internal::v8_flags.
GetPointerSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1047 of file d8-test.cc.
                                                                              {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (i::v8_flags.fuzzing) {
      info.GetReturnValue().Set(v8::Null(isolate));
      return;
    }
    info.GetReturnValue().Set(External::New(isolate, static_cast<void*>(self)));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::External::New(), v8::Null(), v8::FunctionCallbackInfo< T >::This(), v8::internal::v8_flags, and v8::internal::ValidateCallbackInfo().
instance()
FastCApiObject & v8::FastCApiObject::instance () [static]
Definition at line 1490 of file d8-test.cc.
{ return kFastCApiObject; }
References v8::anonymous_namespace{d8-test.cc}::kFastCApiObject.
IsFastCApiObjectFastCallback()
static bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectFastCallback (v8::Local< v8::Object > receiver, v8::Local< v8::Value > arg, FastApiCallbackOptions & options) [inline], [static]
Definition at line 902 of file d8-test.cc.
                                                                            {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(false);
    self->fast_call_count_++;
    if (!arg->IsObject()) {
      return false;
    }
    Local<Object> object = arg.As<Object>();
    if (!IsValidApiObject(object)) return false;
    Isolate* isolate = options.isolate;
    HandleScope handle_scope(isolate);
    return PerIsolateData::Get(isolate)
        ->GetTestApiObjectCtor()
        ->IsLeafTemplateForApiObject(object);
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_FAST_OPTIONS, v8::PerIsolateData::Get(), v8::PerIsolateData::GetTestApiObjectCtor(), v8::Value::IsObject(), and v8::FastApiCallbackOptions::isolate.
IsFastCApiObjectSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 923 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    HandleScope handle_scope(isolate);
    bool result = false;
    if (info.Length() < 1) {
      info.GetIsolate()->ThrowError(
          "is_valid_api_object should be called with an argument");
      return;
    }
    if (info[0]->IsObject()) {
      Local<Object> object = info[0].As<Object>();
      if (!IsValidApiObject(object)) {
        result = false;
      } else {
        result = PerIsolateData::Get(info.GetIsolate())
                     ->GetTestApiObjectCtor()
                     ->IsLeafTemplateForApiObject(object);
      }
    }
    info.GetReturnValue().Set(result);
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::PerIsolateData::Get(), v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::PerIsolateData::GetTestApiObjectCtor(), v8::internal::IsObject(), v8::FunctionCallbackInfo< T >::Length(), v8::base::internal::result, v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
IsValidApiObject()
static bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsValidApiObject (Local< Object > object) [inline], [static], [private]
Definition at line 1450 of file d8-test.cc.
                                                     {
    if (object->IsInt32()) return false;
    auto instance_type = i::Internals::GetInstanceType(
        internal::ValueHelper::ValueAsAddress(*object));
    return (base::IsInRange(instance_type, i::Internals::kFirstJSApiObjectType,
                            i::Internals::kLastJSApiObjectType) ||
            instance_type == i::Internals::kJSSpecialApiObjectType);
  }
References v8::internal::Internals::GetInstanceType(), v8::Value::IsInt32(), v8::internal::Internals::kFirstJSApiObjectType, v8::internal::Internals::kJSSpecialApiObjectType, v8::internal::Internals::kLastJSApiObjectType, and v8::internal::ValueHelper::ValueAsAddress().
PassPointerFastCallback()
static void* v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerFastCallback (Local< Object > receiver, void * pointer, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1081 of file d8-test.cc.
                                                                        {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(nullptr);
    self->fast_call_count_++;
    return pointer;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
PassPointerSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1090 of file d8-test.cc.
                                                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (info.Length() != 1) {
      info.GetIsolate()->ThrowError(
          "Invalid number of arguments, expected one.");
      return;
    }
    Local<Value> maybe_external = info[0].As<Value>();
    if (maybe_external->IsNull()) {
      info.GetReturnValue().Set(maybe_external);
      return;
    }
    if (!maybe_external->IsExternal()) {
      info.GetIsolate()->ThrowError("Did not get an external.");
      return;
    }
    Local<External> external = info[0].As<External>();
    info.GetReturnValue().Set(external);
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
reset_counts()
void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::reset_counts () [inline]
Definition at line 1442 of file d8-test.cc.
                      {
    fast_call_count_ = 0;
    slow_call_count_ = 0;
  }
ResetCounts()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ResetCounts (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1426 of file d8-test.cc.
                                                                   {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->reset_counts();
    info.GetReturnValue().Set(Undefined(info.GetIsolate()));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::This(), v8::Undefined(), and v8::internal::ValidateCallbackInfo().
slow_call_count()
int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::slow_call_count () const [inline]
Definition at line 1441 of file d8-test.cc.
{ return slow_call_count_; }
SlowCallCount()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SlowCallCount (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1419 of file d8-test.cc.
                                                                     {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    info.GetReturnValue().Set(
        Number::New(info.GetIsolate(), self->slow_call_count()));
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
sumInt64AsBigIntSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1226 of file d8-test.cc.
                                               {
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (info.Length() != 2) {
      info.GetIsolate()->ThrowError(
          "Invalid number of arguments, expected two.");
      return;
    }
    Local<Value> value_a = info[0];
    Local<Value> value_b = info[1];
    int64_t a;
    if (value_a->IsBigInt()) {
      a = static_cast<int64_t>(value_a.As<BigInt>()->Int64Value());
    } else {
      info.GetIsolate()->ThrowError("Did not get a BigInt as first parameter.");
      return;
    }
    int64_t b;
    if (value_b->IsBigInt()) {
      b = static_cast<int64_t>(value_b.As<BigInt>()->Int64Value());
    } else {
      info.GetIsolate()->ThrowError(
          "Did not get a BigInt as second parameter.");
      return;
    }
    info.GetReturnValue().Set(BigInt::New(isolate, a + b));
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_SLOW, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::BigInt::New(), v8::FunctionCallbackInfo< T >::This(), and v8::Isolate::ThrowError().
sumInt64AsNumberSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1186 of file d8-test.cc.
                                               {
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (info.Length() != 2) {
      info.GetIsolate()->ThrowError(
          "Invalid number of arguments, expected two.");
      return;
    }
    Local<Value> value_a = info[0];
    Local<Value> value_b = info[1];
    if (!value_a->IsNumber()) {
      info.GetIsolate()->ThrowError("Did not get a number as first parameter.");
      return;
    }
    int64_t a;
    if (!Convert(value_a.As<Number>()->Value(), &a)) {
      info.GetIsolate()->ThrowError("First number is out of int64_t range.");
      return;
    }
    if (!value_b->IsNumber()) {
      info.GetIsolate()->ThrowError(
          "Did not get a number as second parameter.");
      return;
    }
    int64_t b;
    if (!Convert(value_b.As<Number>()->Value(), &b)) {
      info.GetIsolate()->ThrowError("Second number is out of int64_t range.");
      return;
    }
    info.GetReturnValue().Set(Number::New(isolate, static_cast<double>(a + b)));
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_SLOW, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::Number::Value().
sumInt64FastCallback()
static int64_t v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64FastCallback (Local< Object > receiver, int64_t a, int64_t b, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1169 of file d8-test.cc.
                                                                       {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    return a + b;
  }
References CHECK_SELF_OR_THROW_FAST_OPTIONS.
sumUint64AsBigIntSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1316 of file d8-test.cc.
                                               {
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (info.Length() != 2) {
      info.GetIsolate()->ThrowError(
          "Invalid number of arguments, expected two.");
      return;
    }
    Local<Value> value_a = info[0];
    Local<Value> value_b = info[1];
    uint64_t a;
    if (value_a->IsBigInt()) {
      a = static_cast<uint64_t>(value_a.As<BigInt>()->Uint64Value());
    } else {
      info.GetIsolate()->ThrowError("Did not get a BigInt as first parameter.");
      return;
    }
    uint64_t b;
    if (value_b->IsBigInt()) {
      b = static_cast<uint64_t>(value_b.As<BigInt>()->Uint64Value());
    } else {
      info.GetIsolate()->ThrowError(
          "Did not get a BigInt as second parameter.");
      return;
    }
    info.GetReturnValue().Set(BigInt::NewFromUnsigned(isolate, a + b));
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_SLOW, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::BigInt::NewFromUnsigned(), v8::FunctionCallbackInfo< T >::This(), and v8::Isolate::ThrowError().
sumUint64AsNumberSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1276 of file d8-test.cc.
                                               {
    Isolate* isolate = info.GetIsolate();
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    if (info.Length() != 2) {
      info.GetIsolate()->ThrowError(
          "Invalid number of arguments, expected two.");
      return;
    }
    Local<Value> value_a = info[0];
    Local<Value> value_b = info[1];
    if (!value_a->IsNumber()) {
      info.GetIsolate()->ThrowError("Did not get a number as first parameter.");
      return;
    }
    uint64_t a;
    if (!Convert(value_a.As<Number>()->Value(), &a)) {
      info.GetIsolate()->ThrowError("First number is out of uint64_t range.");
      return;
    }
    if (!value_b->IsNumber()) {
      info.GetIsolate()->ThrowError(
          "Did not get a number as second parameter.");
      return;
    }
    uint64_t b;
    if (!Convert(value_b.As<Number>()->Value(), &b)) {
      info.GetIsolate()->ThrowError("Second number is out of uint64_t range.");
      return;
    }
    info.GetReturnValue().Set(Number::New(isolate, static_cast<double>(a + b)));
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_SLOW, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::Length(), v8::Number::New(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::Number::Value().
sumUint64FastCallback()
static uint64_t v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64FastCallback (Local< Object > receiver, uint64_t a, uint64_t b, FastApiCallbackOptions & options) [inline], [static]
Definition at line 1262 of file d8-test.cc.
                                                                         {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(0);
    self->fast_call_count_++;
    // This CHECK here is unnecessary, but it keeps this function from getting
    // merged with `sumInt64FastCallback`. There is a test which relies on
    // `sumUint64FastCallback` and `sumInt64FastCallback` being different call
    // targets.
    CHECK_GT(self->fast_call_count_, 0);
    return a + b;
  }
References CHECK_GT, and CHECK_SELF_OR_THROW_FAST_OPTIONS.
SupportsFPParams()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SupportsFPParams (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1433 of file d8-test.cc.
                                                                        {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    info.GetReturnValue().Set(self->supports_fp_params_);
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetReturnValue(), v8::FunctionCallbackInfo< T >::This(), and v8::internal::ValidateCallbackInfo().
TestWasmMemoryFastCallback()
static bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback (Local< Object > receiver, uint32_t address, FastApiCallbackOptions & options) [inline], [static]
Definition at line 984 of file d8-test.cc.
                                                                          {
    FastCApiObject* self = UnwrapObject(receiver);
    CHECK_SELF_OR_THROW_FAST_OPTIONS(false);
    self->fast_call_count_++;
    if (i::v8_flags.fuzzing) {
      return true;
    }
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::HandleScope handle_scope(isolate);
    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Local<v8::String> mem_string =
        v8::String::NewFromUtf8(isolate, "wasm_memory").ToLocalChecked();
    v8::Local<v8::Value> mem;
    if (!receiver->Get(context, mem_string).ToLocal(&mem)) {
      isolate->ThrowError(
          "wasm_memory was used when the WebAssembly.Memory was not set on the "
          "receiver.");
    }
    v8::Local<v8::WasmMemoryObject> wasm_memory =
        mem.As<v8::WasmMemoryObject>();
    reinterpret_cast<uint8_t*>(wasm_memory->Buffer()->Data())[address] = 42;
    return true;
  }
References v8::Local< T >::As(), CHECK_SELF_OR_THROW_FAST_OPTIONS, v8::Object::Get(), v8::Isolate::GetCurrent(), v8::Isolate::GetCurrentContext(), v8::String::NewFromUtf8(), v8::Isolate::ThrowError(), v8::MaybeLocal< T >::ToLocal(), and v8::internal::v8_flags.
TestWasmMemorySlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemorySlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 1013 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    info.GetIsolate()->ThrowError("should be unreachable from wasm");
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
ThrowFallbackSlowCallback()
static void v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowFallbackSlowCallback (const FunctionCallbackInfo< Value > & info) [inline], [static]
Definition at line 68 of file d8-test.cc.
                                               {
    DCHECK(i::ValidateCallbackInfo(info));
    FastCApiObject* self = UnwrapObject(info.This());
    CHECK_SELF_OR_THROW_SLOW();
    self->slow_call_count_++;
    info.GetIsolate()->ThrowError("Exception from slow callback");
  }
References CHECK_SELF_OR_THROW_SLOW, DCHECK, v8::FunctionCallbackInfo< T >::GetIsolate(), v8::FunctionCallbackInfo< T >::This(), v8::Isolate::ThrowError(), and v8::internal::ValidateCallbackInfo().
ThrowNoFallbackFastCallback()
static int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowNoFallbackFastCallback (Local< Object > receiver) [inline], [static]
Definition at line 54 of file d8-test.cc.
                                                                 {
    FastCApiObject* self = UnwrapObject(receiver);
    if (!self) {
      self = &FastCApiObject::instance();
    }
    self->fast_call_count_++;
    v8::Isolate* isolate = v8::Isolate::GetCurrent();
    v8::HandleScope scope(isolate);
    v8::Local<v8::Context> context = isolate->GetCurrentContext();
    v8::Context::Scope context_scope(context);
    isolate->ThrowError("Exception from fast callback");
    return 0;
  }
References v8::Isolate::GetCurrent(), v8::Isolate::GetCurrentContext(), and v8::Isolate::ThrowError().
UnwrapObject()
static FastCApiObject* v8::anonymous_namespace{d8-test.cc}::FastCApiObject::UnwrapObject (Local< Object > object) [inline], [static], [private]
Definition at line 1458 of file d8-test.cc.
                                                            {
    if (!IsValidApiObject(object)) {
      return nullptr;
    }
    if (object->InternalFieldCount() <= kV8WrapperObjectIndex) {
      return nullptr;
    }
    FastCApiObject* wrapped = reinterpret_cast<FastCApiObject*>(
        object->GetAlignedPointerFromInternalField(kV8WrapperObjectIndex));
    CHECK_NOT_NULL(wrapped);
    return wrapped;
  }
References CHECK_NOT_NULL, and v8::Object::InternalFieldCount().
Member Data Documentation
attribute_value_
int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::attribute_value_ = 0 [private]
Definition at line 1472 of file d8-test.cc.
fast_call_count_
int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::fast_call_count_ = 0 [private]
Definition at line 1471 of file d8-test.cc.
kV8WrapperObjectIndex
const int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::kV8WrapperObjectIndex = 1 [static]
Definition at line 1447 of file d8-test.cc.
slow_call_count_
int v8::anonymous_namespace{d8-test.cc}::FastCApiObject::slow_call_count_ = 0 [private]
Definition at line 1471 of file d8-test.cc.
supports_fp_params_
bool v8::anonymous_namespace{d8-test.cc}::FastCApiObject::supports_fp_params_ = false [private]
Definition at line 1476 of file d8-test.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8-test.cc