v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam > Class Template Reference
Public Types
using ElementsTraits = ElementsTraitsParam
using BackingStore = typename ElementsTraitsParam::BackingStore
Public Member Functions
ElementsAccessorBase ()=default
ElementsAccessorBase (const ElementsAccessorBase &)=delete
ElementsAccessorBase & operator= (const ElementsAccessorBase &)=delete
void Validate (Isolate *isolate, Tagged< JSObject > holder) final
bool HasElement (Isolate *isolate, Tagged< JSObject > holder, uint32_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter) final
bool HasEntry (Isolate *isolate, Tagged< JSObject > holder, InternalIndex entry) final
bool HasAccessors (Tagged< JSObject > holder) final
Handle< Object > Get (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry) final
Handle< Object > GetAtomic (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry, SeqCstAccessTag tag) final
void SetAtomic (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) final
Handle< Object > SwapAtomic (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) final
Handle< Object > CompareAndSwapAtomic (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) final
void Set (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) final
void Reconfigure (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) final
Maybe< bool > Add (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) final
Maybe< uint32_t > Push (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t push_size) final
Maybe< uint32_t > Unshift (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t unshift_size) final
Tagged< Object > Pop (Isolate *isolate, DirectHandle< JSArray > receiver) final
Tagged< Object > Shift (Isolate *isolate, DirectHandle< JSArray > receiver) final
Maybe< bool > SetLength (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length) final
size_t NumberOfElements (Isolate *isolate, Tagged< JSObject > receiver) final
void TransitionElementsKind (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > map) final
Maybe< bool > GrowCapacityAndConvert (Isolate *isolate, DirectHandle< JSObject > object, uint32_t capacity) final
Maybe< bool > GrowCapacity (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index) final
void Delete (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry) final
void CopyElements (Isolate *isolate, Tagged< JSObject > from_holder, uint32_t from_start, ElementsKind from_kind, DirectHandle< FixedArrayBase > to, uint32_t to_start, int copy_size) final
void CopyElements (Isolate *isolate, DirectHandle< FixedArrayBase > source, ElementsKind source_kind, DirectHandle< FixedArrayBase > destination, int size) override
void CopyTypedArrayElementsSlice (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end) override
Tagged< Object > CopyElements (Isolate *isolate, DirectHandle< JSAny > source, DirectHandle< JSObject > destination, size_t length, size_t offset) final
DirectHandle< NumberDictionary > Normalize (Isolate *isolate, DirectHandle< JSObject > object) final
Maybe< bool > CollectValuesOrEntries (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int *nof_items, PropertyFilter filter) override
V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndices (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator *keys) final
MaybeHandle< FixedArray > PrependElementIndices (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter) final
V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulator (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert) final
size_t GetCapacity (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) final
MaybeDirectHandle< Object > Fill (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end) override
Maybe< bool > IncludesValue (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) final
Maybe< int64_t > IndexOfValue (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) final
Maybe< int64_t > LastIndexOfValue (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from) final
void Reverse (Tagged< JSObject > receiver) final
InternalIndex GetEntryForIndex (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index) final
PropertyDetails GetDetails (Tagged< JSObject > holder, InternalIndex entry) final
Handle< FixedArray > CreateListFromArrayLike (Isolate *isolate, DirectHandle< JSObject > object, uint32_t length) final
Static Public Member Functions
static ElementsKind kind ()
static void ValidateContents (Isolate *isolate, Tagged< JSObject > holder, size_t length)
static void ValidateImpl (Isolate *isolate, Tagged< JSObject > holder)
static bool HasElementImpl (Isolate *isolate, Tagged< JSObject > holder, size_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter=ALL_PROPERTIES)
static bool HasEntryImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static bool HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static Handle< Object > GetInternalImpl (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)
static Handle< Object > GetImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static Handle< Object > GetAtomicInternalImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, SeqCstAccessTag tag)
static void SetAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)
static Handle< Object > SwapAtomicInternalImpl (Isolate *isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag)
static Tagged< Object > CompareAndSwapAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static Maybe< uint32_t > PushImpl (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t push_sized)
static Maybe< uint32_t > UnshiftImpl (Isolate *isolate, DirectHandle< JSArray > receiver, BuiltinArguments *args, uint32_t unshift_size)
static Tagged< Object > PopImpl (Isolate *isolate, DirectHandle< JSArray > receiver)
static Tagged< Object > ShiftImpl (Isolate *isolate, DirectHandle< JSArray > receiver)
static void DecreaseLength (Isolate *isolate, Tagged< BackingStore > backing_store, uint32_t old_length, uint32_t length)
static Maybe< bool > SetLengthImpl (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store)
static uint32_t NumberOfElementsImpl (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store)
static size_t GetMaxIndex (Tagged< JSObject > receiver, Tagged< FixedArrayBase > elements)
static size_t GetMaxNumberOfEntries (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > elements)
static MaybeDirectHandle< FixedArrayBase > ConvertElementsWithCapacity (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > old_elements, ElementsKind from_kind, uint32_t capacity)
static MaybeDirectHandle< FixedArrayBase > ConvertElementsWithCapacity (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > old_elements, ElementsKind from_kind, uint32_t capacity, uint32_t src_index, uint32_t dst_index)
static void TransitionElementsKindImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > to_map)
static Maybe< bool > GrowCapacityAndConvertImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t capacity)
static Maybe< bool > BasicGrowCapacityAndConvertImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > old_elements, ElementsKind from_kind, ElementsKind to_kind, uint32_t capacity)
static void CopyElementsImpl (Isolate *isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size)
static void CopyTypedArrayElementsSliceImpl (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end)
static Tagged< Object > CopyElementsHandleImpl (Isolate *isolate, DirectHandle< Object > source, DirectHandle< JSObject > destination, size_t length, size_t offset)
static DirectHandle< NumberDictionary > NormalizeImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > elements)
static Maybe< bool > CollectValuesOrEntriesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int *nof_items, PropertyFilter filter)
static V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator *keys)
static Handle< FixedArray > DirectCollectElementIndicesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, GetKeysConversion convert, PropertyFilter filter, Handle< FixedArray > list, uint32_t *nof_indices, uint32_t insertion_index=0)
static MaybeHandle< FixedArray > PrependElementIndicesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter)
static uint32_t GetCapacityImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static MaybeDirectHandle< Object > FillImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end)
static Maybe< bool > IncludesValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
static Maybe< int64_t > IndexOfValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length)
static Maybe< int64_t > LastIndexOfValueImpl (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from)
static void ReverseImpl (Tagged< JSObject > receiver)
static InternalIndex GetEntryForIndexImpl (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index, PropertyFilter filter)
static PropertyDetails GetDetailsImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry)
static PropertyDetails GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry)
static Handle< FixedArray > CreateListFromArrayLikeImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t length)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename ElementsTraitsParam>
class v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >
Definition at line 591 of file elements.cc.
Member Typedef Documentation
BackingStore
template<typename Subclass , typename ElementsTraitsParam >
using v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BackingStore = typename ElementsTraitsParam::BackingStore
Definition at line 598 of file elements.cc.
ElementsTraits
template<typename Subclass , typename ElementsTraitsParam >
using v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ElementsTraits = ElementsTraitsParam
Definition at line 597 of file elements.cc.
Constructor & Destructor Documentation
ElementsAccessorBase() [1/2]
template<typename Subclass , typename ElementsTraitsParam >
v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ElementsAccessorBase () [default]
ElementsAccessorBase() [2/2]
template<typename Subclass , typename ElementsTraitsParam >
v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ElementsAccessorBase (const ElementsAccessorBase< Subclass, ElementsTraitsParam > &) [delete]
Member Function Documentation
Add()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Add (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 760 of file elements.cc.
                                                                              {
    return Subclass::AddImpl(isolate, object, index, value, attributes,
                             new_capacity);
  }
References v8::internal::index, and v8::internal::value.
AddElementsToKeyAccumulator()
template<typename Subclass , typename ElementsTraitsParam >
V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::AddElementsToKeyAccumulator (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1418 of file elements.cc.
                                      {
    return Subclass::AddElementsToKeyAccumulatorImpl(receiver, accumulator,
                                                     convert);
  }
AddImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 767 of file elements.cc.
                                                    {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
BasicGrowCapacityAndConvertImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::BasicGrowCapacityAndConvertImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > old_elements, ElementsKind from_kind, ElementsKind to_kind, uint32_t capacity) [inline], [static]
Definition at line 1042 of file elements.cc.
                                               {
    DirectHandle<FixedArrayBase> elements;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, elements,
        ConvertElementsWithCapacity(isolate, object, old_elements, from_kind,
                                    capacity),
        Nothing<bool>());
    if (IsHoleyElementsKind(from_kind)) {
      to_kind = GetHoleyElementsKind(to_kind);
    }
    DirectHandle<Map> new_map =
        JSObject::GetElementsTransitionMap(isolate, object, to_kind);
    JSObject::SetMapAndElements(isolate, object, new_map, elements);
    // Transition through the allocation site as well if present.
    JSObject::UpdateAllocationSite(isolate, object, to_kind);
    if (v8_flags.trace_elements_transitions) {
      JSObject::PrintElementsTransition(stdout, object, from_kind, old_elements,
                                        to_kind, elements);
    }
    return Just(true);
  }
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::JSObject::GetElementsTransitionMap(), v8::internal::GetHoleyElementsKind(), v8::internal::IsHoleyElementsKind(), v8::Just(), v8::internal::JSObject::PrintElementsTransition(), v8::internal::JSObject::SetMapAndElements(), v8::internal::JSObject::UpdateAllocationSite(), and v8::internal::v8_flags.
CollectElementIndices()
template<typename Subclass , typename ElementsTraitsParam >
V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndices (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator * keys) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1279 of file elements.cc.
                                  {
    return Subclass::CollectElementIndicesImpl(object, backing_store, keys);
  }
CollectElementIndicesImpl()
template<typename Subclass , typename ElementsTraitsParam >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator * keys) [inline], [static]
Definition at line 1285 of file elements.cc.
                            {
    DCHECK_NE(DICTIONARY_ELEMENTS, kind());
    // Non-dictionary elements can't have all-can-read accessors.
    size_t length = Subclass::GetMaxIndex(*object, *backing_store);
    PropertyFilter filter = keys->filter();
    Isolate* isolate = keys->isolate();
    Factory* factory = isolate->factory();
    for (size_t i = 0; i < length; i++) {
      if (Subclass::HasElementImpl(isolate, *object, i, *backing_store,
                                   filter)) {
        RETURN_FAILURE_IF_NOT_SUCCESSFUL(
            keys->AddKey(factory->NewNumberFromSize(i)));
      }
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), DCHECK_NE, v8::internal::DICTIONARY_ELEMENTS, v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::filter(), v8::internal::KeyAccumulator::isolate(), v8::internal::kSuccess, v8::internal::length, v8::internal::FactoryBase< Impl >::NewNumberFromSize(), and RETURN_FAILURE_IF_NOT_SUCCESSFUL.
CollectValuesOrEntries()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntries (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int * nof_items, PropertyFilter filter) [inline], [override], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1200 of file elements.cc.
                                                                     {
    return Subclass::CollectValuesOrEntriesImpl(
        isolate, object, values_or_entries, get_entries, nof_items, filter);
  }
CollectValuesOrEntriesImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectValuesOrEntriesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int * nof_items, PropertyFilter filter) [inline], [static]
Definition at line 1209 of file elements.cc.
                                             {
    DCHECK_EQ(*nof_items, 0);
    KeyAccumulator accumulator(isolate, KeyCollectionMode::kOwnOnly,
                               ALL_PROPERTIES);
    RETURN_NOTHING_IF_NOT_SUCCESSFUL(Subclass::CollectElementIndicesImpl(
        object, direct_handle(object->elements(), isolate), &accumulator));
    DirectHandle<FixedArray> keys = accumulator.GetKeys();
    int count = 0;
    int i = 0;
    ElementsKind original_elements_kind = object->GetElementsKind();
    for (; i < keys->length(); ++i) {
      DirectHandle<Object> key(keys->get(i), isolate);
      uint32_t index;
      if (!Object::ToUint32(*key, &index)) continue;
      DCHECK_EQ(object->GetElementsKind(), original_elements_kind);
      InternalIndex entry = Subclass::GetEntryForIndexImpl(
          isolate, *object, object->elements(), index, filter);
      if (entry.is_not_found()) continue;
      PropertyDetails details = Subclass::GetDetailsImpl(*object, entry);
      DirectHandle<Object> value;
      if (details.kind() == PropertyKind::kData) {
        value = Subclass::GetInternalImpl(isolate, object, entry);
      } else {
        // This might modify the elements and/or change the elements kind.
        LookupIterator it(isolate, object, index, LookupIterator::OWN);
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, value, Object::GetProperty(&it), Nothing<bool>());
      }
      if (get_entries) value = MakeEntryPair(isolate, index, value);
      values_or_entries->set(count++, *value);
      if (object->GetElementsKind() != original_elements_kind) break;
    }
    // Slow path caused by changes in elements kind during iteration.
    for (; i < keys->length(); i++) {
      DirectHandle<Object> key(keys->get(i), isolate);
      uint32_t index;
      if (!Object::ToUint32(*key, &index)) continue;
      if (filter & ONLY_ENUMERABLE) {
        InternalElementsAccessor* accessor =
            reinterpret_cast<InternalElementsAccessor*>(
                object->GetElementsAccessor());
        InternalIndex entry = accessor->GetEntryForIndex(
            isolate, *object, object->elements(), index);
        if (entry.is_not_found()) continue;
        PropertyDetails details = accessor->GetDetails(*object, entry);
        if (!details.IsEnumerable()) continue;
      }
      DirectHandle<Object> value;
      LookupIterator it(isolate, object, index, LookupIterator::OWN);
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, value, Object::GetProperty(&it),
                                       Nothing<bool>());
      if (get_entries) value = MakeEntryPair(isolate, index, value);
      values_or_entries->set(count++, *value);
    }
    *nof_items = count;
    return Just(true);
  }
References v8::internal::ALL_PROPERTIES, ASSIGN_RETURN_ON_EXCEPTION_VALUE, DCHECK_EQ, v8::internal::direct_handle(), v8::internal::anonymous_namespace{elements.cc}::InternalElementsAccessor::GetDetails(), v8::internal::anonymous_namespace{elements.cc}::InternalElementsAccessor::GetEntryForIndex(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::InternalIndex::is_not_found(), v8::internal::PropertyDetails::IsEnumerable(), v8::Just(), v8::internal::kData, v8::internal::key, v8::internal::PropertyDetails::kind(), v8::internal::kOwnOnly, v8::internal::MakeEntryPair(), v8::internal::ONLY_ENUMERABLE, v8::internal::LookupIterator::OWN, RETURN_NOTHING_IF_NOT_SUCCESSFUL, v8::internal::Object::ToUint32(), and v8::internal::value.
CompareAndSwapAtomic()
template<typename Subclass , typename ElementsTraitsParam >
Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CompareAndSwapAtomic (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 718 of file elements.cc.
                                                                 {
    return handle(HeapObject::SeqCst_CompareAndSwapField(
                      expected, value,
                      [=](Tagged<Object> expected_value,
                          Tagged<Object> new_value) {
                        return Subclass::CompareAndSwapAtomicInternalImpl(
                            holder->elements(), entry, expected_value,
                            new_value, tag);
                      }),
                  isolate);
  }
References v8::internal::handle(), and v8::internal::value.
CompareAndSwapAtomicInternalImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CompareAndSwapAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > expected, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 735 of file elements.cc.
                                                                          {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
ConvertElementsWithCapacity() [1/2]
template<typename Subclass , typename ElementsTraitsParam >
static MaybeDirectHandle<FixedArrayBase> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > old_elements, ElementsKind from_kind, uint32_t capacity) [inline], [static]
Definition at line 934 of file elements.cc.
                         {
    return ConvertElementsWithCapacity(isolate, object, old_elements, from_kind,
                                       capacity, 0, 0);
  }
ConvertElementsWithCapacity() [2/2]
template<typename Subclass , typename ElementsTraitsParam >
static MaybeDirectHandle<FixedArrayBase> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > old_elements, ElementsKind from_kind, uint32_t capacity, uint32_t src_index, uint32_t dst_index) [inline], [static]
Definition at line 942 of file elements.cc.
                                                                 {
    DirectHandle<FixedArrayBase> new_elements;
    // TODO(victorgomes): Retrieve native context in optimized code
    // and remove the check isolate->context().is_null().
    if (IsDoubleElementsKind(kind())) {
      if (!isolate->context().is_null() &&
          !base::IsInRange(capacity, 0, FixedDoubleArray::kMaxLength)) {
        THROW_NEW_ERROR(isolate,
                        NewRangeError(MessageTemplate::kInvalidArrayLength));
      }
      new_elements = isolate->factory()->NewFixedDoubleArray(capacity);
    } else {
      if (!isolate->context().is_null() &&
          !base::IsInRange(capacity, 0, FixedArray::kMaxLength)) {
        THROW_NEW_ERROR(isolate,
                        NewRangeError(MessageTemplate::kInvalidArrayLength));
      }
      new_elements = isolate->factory()->NewFixedArray(capacity);
    }
    int packed_size = kPackedSizeNotKnown;
    if (IsFastPackedElementsKind(from_kind) && IsJSArray(*object)) {
      packed_size = Smi::ToInt(Cast<JSArray>(*object)->length());
    }
    Subclass::CopyElementsImpl(isolate, *old_elements, src_index, *new_elements,
                               from_kind, dst_index, packed_size,
                               kCopyToEndAndInitializeToHole);
    return MaybeDirectHandle<FixedArrayBase>(new_elements);
  }
References v8::internal::Isolate::context(), v8::internal::Isolate::factory(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastPackedElementsKind(), v8::internal::anonymous_namespace{elements.cc}::kCopyToEndAndInitializeToHole, v8::internal::FixedArray::kMaxLength, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::anonymous_namespace{elements.cc}::kPackedSizeNotKnown, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::FactoryBase< Impl >::NewFixedDoubleArray(), THROW_NEW_ERROR, and v8::internal::Smi::ToInt().
CopyElements() [1/3]
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements (Isolate * isolate, DirectHandle< FixedArrayBase > source, ElementsKind source_kind, DirectHandle< FixedArrayBase > destination, int size) [inline], [override], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1155 of file elements.cc.
                                       {
    Subclass::CopyElementsImpl(isolate, *source, 0, *destination, source_kind,
                               0, kPackedSizeNotKnown, size);
  }
References v8::internal::anonymous_namespace{elements.cc}::kPackedSizeNotKnown, and size().
CopyElements() [2/3]
template<typename Subclass , typename ElementsTraitsParam >
Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements (Isolate * isolate, DirectHandle< JSAny > source, DirectHandle< JSObject > destination, size_t length, size_t offset) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1175 of file elements.cc.
                                                   {
    return Subclass::CopyElementsHandleImpl(isolate, source, destination,
                                            length, offset);
  }
References v8::internal::length.
CopyElements() [3/3]
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElements (Isolate * isolate, Tagged< JSObject > from_holder, uint32_t from_start, ElementsKind from_kind, DirectHandle< FixedArrayBase > to, uint32_t to_start, int copy_size) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1128 of file elements.cc.
                                         {
    int packed_size = kPackedSizeNotKnown;
    bool is_packed =
        IsFastPackedElementsKind(from_kind) && IsJSArray(from_holder);
    if (is_packed) {
      packed_size = Smi::ToInt(Cast<JSArray>(from_holder)->length());
      if (copy_size >= 0 && packed_size > copy_size) {
        packed_size = copy_size;
      }
    }
    Tagged<FixedArrayBase> from = from_holder->elements();
    // NOTE: the Subclass::CopyElementsImpl() methods
    // violate the handlified function signature convention:
    // raw pointer parameters in the function that allocates. This is done
    // intentionally to avoid ArrayConcat() builtin performance degradation.
    //
    // Details: The idea is that allocations actually happen only in case of
    // copying from object with fast double elements to object with object
    // elements. In all the other cases there are no allocations performed and
    // handle creation causes noticeable performance degradation of the builtin.
    Subclass::CopyElementsImpl(isolate, from, from_start, *to, from_kind,
                               to_start, packed_size, copy_size);
  }
References v8::internal::wasm::is_packed(), v8::internal::IsFastPackedElementsKind(), v8::internal::anonymous_namespace{elements.cc}::kPackedSizeNotKnown, v8::internal::length, and v8::internal::Smi::ToInt().
CopyElementsHandleImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElementsHandleImpl (Isolate * isolate, DirectHandle< Object > source, DirectHandle< JSObject > destination, size_t length, size_t offset) [inline], [static]
Definition at line 1182 of file elements.cc.
                                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
CopyElementsImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyElementsImpl (Isolate * isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size) [inline], [static]
Definition at line 1121 of file elements.cc.
                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
CopyTypedArrayElementsSlice()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyTypedArrayElementsSlice (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end) [inline], [override], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1163 of file elements.cc.
                                                                      {
    Subclass::CopyTypedArrayElementsSliceImpl(source, destination, start, end);
  }
References v8::internal::compiler::end().
CopyTypedArrayElementsSliceImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CopyTypedArrayElementsSliceImpl (Tagged< JSTypedArray > source, Tagged< JSTypedArray > destination, size_t start, size_t end) [inline], [static]
Definition at line 1169 of file elements.cc.
                                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
CreateListFromArrayLike()
template<typename Subclass , typename ElementsTraitsParam >
Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CreateListFromArrayLike (Isolate * isolate, DirectHandle< JSObject > object, uint32_t length) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1540 of file elements.cc.
                                                                    {
    return Subclass::CreateListFromArrayLikeImpl(isolate, object, length);
  }
References v8::internal::length.
CreateListFromArrayLikeImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CreateListFromArrayLikeImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t length) [inline], [static]
Definition at line 1546 of file elements.cc.
                                                                        {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DecreaseLength()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DecreaseLength (Isolate * isolate, Tagged< BackingStore > backing_store, uint32_t old_length, uint32_t length) [inline], [static]
Definition at line 821 of file elements.cc.
                                                                   {
    uint32_t capacity = backing_store->capacity();
    // It's possible we got here through left-trimming, which would have reduced
    // the capacity.
    if (V8_UNLIKELY(2 * length + JSObject::kMinAddedElementsCapacity <=
                    capacity)) {
      // If more than half the elements won't be used, trim the array.
      // Do not trim from short arrays to prevent frequent trimming on
      // repeated pop operations.
      // Leave some space to allow for subsequent push operations.
      uint32_t new_capacity =
          length + 1 == old_length ? (capacity + length) / 2 : length;
      DCHECK_LT(new_capacity, capacity);
      isolate->heap()->RightTrimArray(backing_store, new_capacity, capacity);
      capacity = new_capacity;
    }
  }
References DCHECK_LT, v8::internal::Isolate::heap(), v8::internal::JSObject::kMinAddedElementsCapacity, v8::internal::length, v8::internal::Heap::RightTrimArray(), and V8_UNLIKELY.
Delete()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Delete (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1116 of file elements.cc.
                                         {
    Subclass::DeleteImpl(isolate, obj, entry);
  }
DirectCollectElementIndicesImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DirectCollectElementIndicesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, GetKeysConversion convert, PropertyFilter filter, Handle< FixedArray > list, uint32_t * nof_indices, uint32_t insertion_index = 0) [inline], [static]
Definition at line 1304 of file elements.cc.
                                    {
    size_t length = Subclass::GetMaxIndex(*object, *backing_store);
    for (size_t i = 0; i < length; i++) {
      if (Subclass::HasElementImpl(isolate, *object, i, *backing_store,
                                   filter)) {
        if (convert == GetKeysConversion::kConvertToString) {
          // Avoid trashing the number to string cache with numbers that
          // are not likely to be needed.
          bool use_cache = i < SmiStringCache::kMaxCapacity;
          DirectHandle<String> index_string =
              isolate->factory()->SizeToString(i, use_cache);
          list->set(insertion_index, *index_string);
        } else {
          DirectHandle<Object> number =
              isolate->factory()->NewNumberFromSize(i);
          list->set(insertion_index, *number);
        }
        insertion_index++;
      }
    }
    *nof_indices = insertion_index;
    return list;
  }
References v8::internal::Isolate::factory(), v8::internal::kConvertToString, v8::internal::SmiStringCache::kMaxCapacity, v8::internal::length, v8::internal::FactoryBase< Impl >::NewNumberFromSize(), and v8::internal::Factory::SizeToString().
Fill()
template<typename Subclass , typename ElementsTraitsParam >
MaybeDirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Fill (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end) [inline], [override], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1442 of file elements.cc.
                                                      {
    return Subclass::FillImpl(isolate, receiver, obj_value, start, end);
  }
References v8::internal::compiler::end().
FillImpl()
template<typename Subclass , typename ElementsTraitsParam >
static MaybeDirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::FillImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > obj_value, size_t start, size_t end) [inline], [static]
Definition at line 1435 of file elements.cc.
                                                                      {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Get()
template<typename Subclass , typename ElementsTraitsParam >
Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Get (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 664 of file elements.cc.
                                                {
    return Subclass::GetInternalImpl(isolate, holder, entry);
  }
GetAtomic()
template<typename Subclass , typename ElementsTraitsParam >
Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetAtomic (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry, SeqCstAccessTag tag) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 682 of file elements.cc.
                                                                           {
    return Subclass::GetAtomicInternalImpl(isolate, holder->elements(), entry,
                                           tag);
  }
GetAtomicInternalImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetAtomicInternalImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, SeqCstAccessTag tag) [inline], [static]
Definition at line 688 of file elements.cc.
                                                {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetCapacity()
template<typename Subclass , typename ElementsTraitsParam >
size_t v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetCapacity (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1430 of file elements.cc.
                                                                 {
    return Subclass::GetCapacityImpl(holder, backing_store);
  }
GetCapacityImpl()
template<typename Subclass , typename ElementsTraitsParam >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetCapacityImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 1425 of file elements.cc.
                                                                        {
    return backing_store->length();
  }
GetDetails()
template<typename Subclass , typename ElementsTraitsParam >
PropertyDetails v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetDetails (Tagged< JSObject > holder, InternalIndex entry) [inline], [final], [virtual]
Implements v8::internal::anonymous_namespace{elements.cc}::InternalElementsAccessor.
Definition at line 1535 of file elements.cc.
                                                        {
    return Subclass::GetDetailsImpl(holder, entry);
  }
GetDetailsImpl() [1/2]
template<typename Subclass , typename ElementsTraitsParam >
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetDetailsImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 1523 of file elements.cc.
                                                             {
    return PropertyDetails(PropertyKind::kData, NONE,
                           PropertyCellType::kNoCell);
  }
References v8::internal::kData, v8::internal::kNoCell, and v8::internal::NONE.
GetDetailsImpl() [2/2]
template<typename Subclass , typename ElementsTraitsParam >
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 1529 of file elements.cc.
                                                             {
    return PropertyDetails(PropertyKind::kData, NONE,
                           PropertyCellType::kNoCell);
  }
References v8::internal::kData, v8::internal::kNoCell, and v8::internal::NONE.
GetEntryForIndex()
template<typename Subclass , typename ElementsTraitsParam >
InternalIndex v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetEntryForIndex (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index) [inline], [final], [virtual]
Implements v8::internal::anonymous_namespace{elements.cc}::InternalElementsAccessor.
Definition at line 1516 of file elements.cc.
                                                     {
    return Subclass::GetEntryForIndexImpl(isolate, holder, backing_store, index,
                                          ALL_PROPERTIES);
  }
References v8::internal::ALL_PROPERTIES, and v8::internal::index.
GetEntryForIndexImpl()
template<typename Subclass , typename ElementsTraitsParam >
static InternalIndex v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetEntryForIndexImpl (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index, PropertyFilter filter) [inline], [static]
Definition at line 1495 of file elements.cc.
                             {
    DCHECK(IsFastElementsKind(kind()) ||
           IsAnyNonextensibleElementsKind(kind()));
    size_t length = Subclass::GetMaxIndex(holder, backing_store);
    if (IsHoleyElementsKindForRead(kind())) {
      DCHECK_IMPLIES(
          index < length,
          index <= static_cast<size_t>(std::numeric_limits<int>::max()));
      return index < length &&
                     !Cast<BackingStore>(backing_store)
                          ->is_the_hole(isolate, static_cast<int>(index))
                 ? InternalIndex(index)
                 : InternalIndex::NotFound();
    } else {
      return index < length ? InternalIndex(index) : InternalIndex::NotFound();
    }
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::index, v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKindForRead(), v8::internal::length, and v8::internal::InternalIndex::NotFound().
GetImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 675 of file elements.cc.
                                                     {
    return handle(Cast<BackingStore>(backing_store)->get(entry.as_int()),
                  isolate);
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::handle().
GetInternalImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetInternalImpl (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 669 of file elements.cc.
                                                             {
    return Subclass::GetImpl(isolate, holder->elements(), entry);
  }
GetMaxIndex()
template<typename Subclass , typename ElementsTraitsParam >
static size_t v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetMaxIndex (Tagged< JSObject > receiver, Tagged< FixedArrayBase > elements) [inline], [static]
Definition at line 918 of file elements.cc.
                                                             {
    if (IsJSArray(receiver)) {
      DCHECK(IsSmi(Cast<JSArray>(receiver)->length()));
      return static_cast<uint32_t>(
          Smi::ToInt(Cast<JSArray>(receiver)->length()));
    }
    return Subclass::GetCapacityImpl(receiver, elements);
  }
References v8::internal::DCHECK(), v8::internal::IsSmi(), v8::internal::length, and v8::internal::Smi::ToInt().
GetMaxNumberOfEntries()
template<typename Subclass , typename ElementsTraitsParam >
static size_t v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GetMaxNumberOfEntries (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > elements) [inline], [static]
Definition at line 928 of file elements.cc.
                                                                       {
    return Subclass::GetMaxIndex(receiver, elements);
  }
GrowCapacity()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GrowCapacity (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1081 of file elements.cc.
                                                 {
    // This function is intended to be called from optimized code. We don't
    // want to trigger lazy deopts there, so refuse to handle cases that would.
    if (object->map()->is_prototype_map() ||
        object->WouldConvertToSlowElements(index)) {
      return Just(false);
    }
    DirectHandle<FixedArrayBase> old_elements(object->elements(), isolate);
    uint32_t new_capacity = JSObject::NewElementsCapacity(index + 1);
    DCHECK(static_cast<uint32_t>(old_elements->length()) < new_capacity);
    static_assert(FixedArray::kMaxLength == FixedDoubleArray::kMaxLength);
    constexpr uint32_t kMaxLength = FixedArray::kMaxLength;
    if (new_capacity > kMaxLength) {
      return Just(false);
    }
    DirectHandle<FixedArrayBase> elements;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, elements,
        ConvertElementsWithCapacity(isolate, object, old_elements, kind(),
                                    new_capacity),
        Nothing<bool>());
    DCHECK_EQ(object->GetElementsKind(), kind());
    // Transition through the allocation site as well if present.
    if (JSObject::UpdateAllocationSite<AllocationSiteUpdateMode::kCheckOnly>(
            isolate, object, kind())) {
      return Just(false);
    }
    object->set_elements(*elements);
    return Just(true);
  }
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::Just(), v8::internal::FixedArray::kMaxLength, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, and v8::internal::JSObject::NewElementsCapacity().
GrowCapacityAndConvert()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GrowCapacityAndConvert (Isolate * isolate, DirectHandle< JSObject > object, uint32_t capacity) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1075 of file elements.cc.
                                                              {
    return Subclass::GrowCapacityAndConvertImpl(isolate, object, capacity);
  }
GrowCapacityAndConvertImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::GrowCapacityAndConvertImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t capacity) [inline], [static]
Definition at line 1022 of file elements.cc.
                                                                   {
    ElementsKind from_kind = object->GetElementsKind();
    if (IsSmiOrObjectElementsKind(from_kind)) {
      // Array optimizations rely on the prototype lookups of Array objects
      // always returning undefined. If there is a store to the initial
      // prototype object, make sure all of these optimizations are invalidated.
      isolate->UpdateNoElementsProtectorOnSetLength(object);
    }
    DirectHandle<FixedArrayBase> old_elements(object->elements(), isolate);
    // This method should only be called if there's a reason to update the
    // elements.
    DCHECK(IsDoubleElementsKind(from_kind) != IsDoubleElementsKind(kind()) ||
           IsDictionaryElementsKind(from_kind) ||
           static_cast<uint32_t>(old_elements->length()) < capacity);
    return Subclass::BasicGrowCapacityAndConvertImpl(
        isolate, object, old_elements, from_kind, kind(), capacity);
  }
References v8::internal::DCHECK(), v8::internal::IsDictionaryElementsKind(), v8::internal::IsDoubleElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), and v8::internal::Isolate::UpdateNoElementsProtectorOnSetLength().
HasAccessors()
template<typename Subclass , typename ElementsTraitsParam >
bool v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::HasAccessors (Tagged< JSObject > holder) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 655 of file elements.cc.
                                                   {
    return Subclass::HasAccessorsImpl(holder, holder->elements());
  }
HasAccessorsImpl()
template<typename Subclass , typename ElementsTraitsParam >
static bool v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 659 of file elements.cc.
                                                                     {
    return false;
  }
HasElement()
template<typename Subclass , typename ElementsTraitsParam >
bool v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::HasElement (Isolate * isolate, Tagged< JSObject > holder, uint32_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 629 of file elements.cc.
                                               {
    return Subclass::HasElementImpl(isolate, holder, index, backing_store,
                                    filter);
  }
References v8::internal::index.
HasElementImpl()
template<typename Subclass , typename ElementsTraitsParam >
static bool v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::HasElementImpl (Isolate * isolate, Tagged< JSObject > holder, size_t index, Tagged< FixedArrayBase > backing_store, PropertyFilter filter = ALL_PROPERTIES) [inline], [static]
Definition at line 636 of file elements.cc.
                                                                     {
    return Subclass::GetEntryForIndexImpl(isolate, holder, backing_store, index,
                                          filter)
        .is_found();
  }
References v8::internal::index.
HasEntry()
template<typename Subclass , typename ElementsTraitsParam >
bool v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::HasEntry (Isolate * isolate, Tagged< JSObject > holder, InternalIndex entry) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 644 of file elements.cc.
                                           {
    return Subclass::HasEntryImpl(isolate, holder->elements(), entry);
  }
HasEntryImpl()
template<typename Subclass , typename ElementsTraitsParam >
static bool v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::HasEntryImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry) [inline], [static]
Definition at line 649 of file elements.cc.
                                                {
    UNIMPLEMENTED();
  }
References v8::internal::UNIMPLEMENTED().
IncludesValue()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::IncludesValue (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1456 of file elements.cc.
                                                 {
    return Subclass::IncludesValueImpl(isolate, receiver, value, start_from,
                                       length);
  }
References v8::internal::length, and v8::internal::value.
IncludesValueImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::IncludesValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 1449 of file elements.cc.
                                                                         {
    return IncludesValueSlowPath(isolate, receiver, value, start_from, length);
  }
References v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::length, and v8::internal::value.
IndexOfValue()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::IndexOfValue (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1470 of file elements.cc.
                                                   {
    return Subclass::IndexOfValueImpl(isolate, receiver, value, start_from,
                                      length);
  }
References v8::internal::length, and v8::internal::value.
IndexOfValueImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::IndexOfValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 1463 of file elements.cc.
                                                                           {
    return IndexOfValueSlowPath(isolate, receiver, value, start_from, length);
  }
References v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath(), v8::internal::length, and v8::internal::value.
kind()
template<typename Subclass , typename ElementsTraitsParam >
static ElementsKind v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::kind () [inline], [static]
Definition at line 600 of file elements.cc.
{ return ElementsTraits::Kind; }
LastIndexOfValue()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::LastIndexOfValue (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1483 of file elements.cc.
                                                           {
    return Subclass::LastIndexOfValueImpl(receiver, value, start_from);
  }
References v8::internal::value.
LastIndexOfValueImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::LastIndexOfValueImpl (DirectHandle< JSObject > receiver, DirectHandle< Object > value, size_t start_from) [inline], [static]
Definition at line 1477 of file elements.cc.
                                                                {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Normalize()
template<typename Subclass , typename ElementsTraitsParam >
DirectHandle<NumberDictionary> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Normalize (Isolate * isolate, DirectHandle< JSObject > object) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1188 of file elements.cc.
                                                             {
    return Subclass::NormalizeImpl(isolate, object,
                                   direct_handle(object->elements(), isolate));
  }
References v8::internal::direct_handle().
NormalizeImpl()
template<typename Subclass , typename ElementsTraitsParam >
static DirectHandle<NumberDictionary> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::NormalizeImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > elements) [inline], [static]
Definition at line 1194 of file elements.cc.
                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
NumberOfElements()
template<typename Subclass , typename ElementsTraitsParam >
size_t v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::NumberOfElements (Isolate * isolate, Tagged< JSObject > receiver) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 907 of file elements.cc.
                                                                             {
    return Subclass::NumberOfElementsImpl(isolate, receiver,
                                          receiver->elements());
  }
NumberOfElementsImpl()
template<typename Subclass , typename ElementsTraitsParam >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::NumberOfElementsImpl (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 912 of file elements.cc.
                                                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
operator=()
template<typename Subclass , typename ElementsTraitsParam >
ElementsAccessorBase& v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::operator= (const ElementsAccessorBase< Subclass, ElementsTraitsParam > &) [delete]
Pop()
template<typename Subclass , typename ElementsTraitsParam >
Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Pop (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 797 of file elements.cc.
                                                                             {
    return Subclass::PopImpl(isolate, receiver);
  }
PopImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PopImpl (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [static]
Definition at line 801 of file elements.cc.
                                                                {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
PrependElementIndices()
template<typename Subclass , typename ElementsTraitsParam >
MaybeHandle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndices (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1332 of file elements.cc.
                                                              {
    return Subclass::PrependElementIndicesImpl(isolate, object, backing_store,
                                               keys, convert, filter);
  }
PrependElementIndicesImpl()
template<typename Subclass , typename ElementsTraitsParam >
static MaybeHandle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, DirectHandle< FixedArray > keys, GetKeysConversion convert, PropertyFilter filter) [inline], [static]
Definition at line 1340 of file elements.cc.
                                                        {
    uint32_t nof_property_keys = keys->length();
    size_t initial_list_length =
        Subclass::GetMaxNumberOfEntries(isolate, *object, *backing_store);
    if (initial_list_length > FixedArray::kMaxLength - nof_property_keys) {
      THROW_NEW_ERROR(isolate,
                      NewRangeError(MessageTemplate::kInvalidArrayLength));
    }
    initial_list_length += nof_property_keys;
    // Collect the element indices into a new list.
    DCHECK_LE(initial_list_length, std::numeric_limits<int>::max());
    MaybeHandle<FixedArray> raw_array = isolate->factory()->TryNewFixedArray(
        static_cast<int>(initial_list_length));
    Handle<FixedArray> combined_keys;
    // If we have a holey backing store try to precisely estimate the backing
    // store size as a last emergency measure if we cannot allocate the big
    // array.
    if (!raw_array.ToHandle(&combined_keys)) {
      if (IsHoleyOrDictionaryElementsKind(kind())) {
        // If we overestimate the result list size we might end up in the
        // large-object space which doesn't free memory on shrinking the list.
        // Hence we try to estimate the final size for holey backing stores more
        // precisely here.
        initial_list_length =
            Subclass::NumberOfElementsImpl(isolate, *object, *backing_store);
        initial_list_length += nof_property_keys;
      }
      DCHECK_LE(initial_list_length, std::numeric_limits<int>::max());
      combined_keys = isolate->factory()->NewFixedArray(
          static_cast<int>(initial_list_length));
    }
    uint32_t nof_indices = 0;
    bool needs_sorting = IsDictionaryElementsKind(kind()) ||
                         IsSloppyArgumentsElementsKind(kind());
    combined_keys = Subclass::DirectCollectElementIndicesImpl(
        isolate, object, backing_store,
        needs_sorting ? GetKeysConversion::kKeepNumbers : convert, filter,
        combined_keys, &nof_indices);
    if (needs_sorting) {
      SortIndices(isolate, combined_keys, nof_indices);
      // Indices from dictionary elements should only be converted after
      // sorting.
      if (convert == GetKeysConversion::kConvertToString) {
        for (uint32_t i = 0; i < nof_indices; i++) {
          DirectHandle<Object> index_string =
              isolate->factory()->Uint32ToString(
                  Object::NumberValue(combined_keys->get(i)));
          combined_keys->set(i, *index_string);
        }
      }
    }
    // Copy over the passed-in property keys.
    CopyObjectToObjectElements(isolate, *keys, PACKED_ELEMENTS, 0,
                               *combined_keys, PACKED_ELEMENTS, nof_indices,
                               nof_property_keys);
    // For holey elements and arguments we might have to shrink the collected
    // keys since the estimates might be off.
    if (IsHoleyOrDictionaryElementsKind(kind()) ||
        IsSloppyArgumentsElementsKind(kind())) {
      // Shrink combined_keys to the final size.
      int final_size = nof_indices + nof_property_keys;
      DCHECK_LE(final_size, combined_keys->length());
      return FixedArray::RightTrimOrEmpty(isolate, combined_keys, final_size);
    }
    return combined_keys;
  }
References v8::internal::anonymous_namespace{elements.cc}::CopyObjectToObjectElements(), DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::IsDictionaryElementsKind(), v8::internal::IsHoleyOrDictionaryElementsKind(), v8::internal::IsSloppyArgumentsElementsKind(), v8::internal::kConvertToString, v8::internal::kKeepNumbers, v8::internal::FixedArray::kMaxLength, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Object::NumberValue(), v8::internal::PACKED_ELEMENTS, v8::internal::anonymous_namespace{elements.cc}::SortIndices(), THROW_NEW_ERROR, v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::Factory::TryNewFixedArray(), and v8::internal::Factory::Uint32ToString().
Push()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Push (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t push_size) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 774 of file elements.cc.
                                                                         {
    return Subclass::PushImpl(isolate, receiver, args, push_size);
  }
References v8::base::args.
PushImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PushImpl (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t push_sized) [inline], [static]
Definition at line 779 of file elements.cc.
                                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Reconfigure()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Reconfigure (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 746 of file elements.cc.
                                                        {
    Subclass::ReconfigureImpl(isolate, object, store, entry, value, attributes);
  }
References store(), and v8::internal::value.
ReconfigureImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 753 of file elements.cc.
                                                             {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Reverse()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Reverse (Tagged< JSObject > receiver) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1491 of file elements.cc.
                                                {
    Subclass::ReverseImpl(receiver);
  }
ReverseImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ReverseImpl (Tagged< JSObject > receiver) [inline], [static]
Definition at line 1489 of file elements.cc.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
Set()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Set (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 741 of file elements.cc.
                                       {
    Subclass::SetImpl(holder, entry, value);
  }
References v8::internal::value.
SetAtomic()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetAtomic (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 694 of file elements.cc.
                                                                  {
    Subclass::SetAtomicInternalImpl(holder->elements(), entry, value, tag);
  }
References v8::internal::value.
SetAtomicInternalImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetAtomicInternalImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 699 of file elements.cc.
                                                         {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SetLength()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLength (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 815 of file elements.cc.
                                               {
    return Subclass::SetLengthImpl(isolate, array, length,
                                   direct_handle(array->elements(), isolate));
  }
References v8::internal::direct_handle(), and v8::internal::length.
SetLengthImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SetLengthImpl (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > backing_store) [inline], [static]
Definition at line 841 of file elements.cc.
                                                                               {
    DCHECK(!array->SetLengthWouldNormalize(length));
    DCHECK(IsFastElementsKind(array->GetElementsKind()));
    uint32_t old_length = 0;
    CHECK(Object::ToArrayIndex(array->length(), &old_length));
    if (old_length < length) {
      ElementsKind kind = array->GetElementsKind();
      if (!IsHoleyElementsKind(kind)) {
        kind = GetHoleyElementsKind(kind);
        JSObject::TransitionElementsKind(isolate, array, kind);
      }
    }
    // Check whether the backing store should be shrunk or grown.
    uint32_t capacity = backing_store->length();
    old_length = std::min(old_length, capacity);
    if (length == 0) {
      array->initialize_elements();
    } else if (length <= capacity) {
      if (IsSmiOrObjectElementsKind(kind())) {
        JSObject::EnsureWritableFastElements(isolate, array);
        if (array->elements() != *backing_store) {
          backing_store = direct_handle(array->elements(), isolate);
        }
      }
      DecreaseLength(isolate, Cast<BackingStore>(*backing_store), old_length,
                     length);
      // Fill the non-trimmed elements with holes.
      // Also use min if we don't RightTrim. It's possible we got here through
      // left-trimming.
      capacity = backing_store->length();
      Cast<BackingStore>(*backing_store)
          ->FillWithHoles(length, std::min(old_length, capacity));
    } else {
      // Calculate a new capacity for the array.
      uint32_t new_capacity;
      if (capacity == 0) {
        // If the existing capacity is zero, assume we are setting the length to
        // presize to the exact size we want.
        new_capacity = length;
      } else {
        // Otherwise, assume we want exponential growing semantics, and grow as
        // if we were pushing. We might not grow enough for the length, so take
        // the max of hte two values.
        new_capacity = std::max(length, JSArray::NewElementsCapacity(capacity));
      }
      // Grow the array to the new capacity. Note that this code will allow
      // create backing stores that consist almost entirely of holes, for which
      // `JSObject::ShouldConvertToSlowElements` would return "true". This is
      // intentional, because we are assuming the user is setting a length to
      // pre-size an array to then write to it within bounds. A subsequent
      // resizing operation, like Array.p.push, might still trigger a transition
      // to dictionary elements because of sparseness.
      MAYBE_RETURN(
          Subclass::GrowCapacityAndConvertImpl(isolate, array, new_capacity),
          Nothing<bool>());
    }
    array->set_length(Smi::FromInt(length));
    JSObject::ValidateElements(isolate, *array);
    return Just(true);
  }
References CHECK, v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::JSObject::EnsureWritableFastElements(), v8::internal::Smi::FromInt(), v8::internal::GetHoleyElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::Just(), v8::internal::length, MAYBE_RETURN, v8::internal::Object::ToArrayIndex(), v8::internal::JSObject::TransitionElementsKind(), and v8::internal::JSObject::ValidateElements().
Shift()
template<typename Subclass , typename ElementsTraitsParam >
Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Shift (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 806 of file elements.cc.
                                                                               {
    return Subclass::ShiftImpl(isolate, receiver);
  }
ShiftImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ShiftImpl (Isolate * isolate, DirectHandle< JSArray > receiver) [inline], [static]
Definition at line 810 of file elements.cc.
                                                                  {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SwapAtomic()
template<typename Subclass , typename ElementsTraitsParam >
Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SwapAtomic (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 705 of file elements.cc.
                                                       {
    return Subclass::SwapAtomicInternalImpl(isolate, holder->elements(), entry,
                                            value, tag);
  }
References v8::internal::value.
SwapAtomicInternalImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::SwapAtomicInternalImpl (Isolate * isolate, Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, SeqCstAccessTag tag) [inline], [static]
Definition at line 712 of file elements.cc.
                                                                      {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
TransitionElementsKind()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::TransitionElementsKind (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > map) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 1070 of file elements.cc.
                                                           {
    Subclass::TransitionElementsKindImpl(isolate, object, map);
  }
TransitionElementsKindImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::TransitionElementsKindImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > to_map) [inline], [static]
Definition at line 977 of file elements.cc.
                                                                   {
    DirectHandle<Map> from_map(object->map(), isolate);
    ElementsKind from_kind = from_map->elements_kind();
    ElementsKind to_kind = to_map->elements_kind();
    if (IsHoleyElementsKind(from_kind)) {
      to_kind = GetHoleyElementsKind(to_kind);
    }
    if (from_kind != to_kind) {
      // This method should never be called for any other case.
      DCHECK(IsFastElementsKind(from_kind));
      DCHECK(IsFastElementsKind(to_kind));
      DCHECK_NE(TERMINAL_FAST_ELEMENTS_KIND, from_kind);
      DirectHandle<FixedArrayBase> from_elements(object->elements(), isolate);
      if (object->elements() == ReadOnlyRoots(isolate).empty_fixed_array() ||
          IsDoubleElementsKind(from_kind) == IsDoubleElementsKind(to_kind)) {
        // No change is needed to the elements() buffer, the transition
        // only requires a map change.
        JSObject::MigrateToMap(isolate, object, to_map);
      } else {
        DCHECK(
            (IsSmiElementsKind(from_kind) && IsDoubleElementsKind(to_kind)) ||
            (IsDoubleElementsKind(from_kind) && IsObjectElementsKind(to_kind)));
        uint32_t capacity = static_cast<uint32_t>(object->elements()->length());
        // Since the max length of FixedArray and FixedDoubleArray is the same,
        // we can safely assume that element conversion with the same capacity
        // will succeed.
        static_assert(FixedArray::kMaxLength == FixedDoubleArray::kMaxLength);
        DCHECK_LE(capacity, FixedArray::kMaxLength);
        DirectHandle<FixedArrayBase> elements =
            ConvertElementsWithCapacity(isolate, object, from_elements,
                                        from_kind, capacity)
                .ToHandleChecked();
        JSObject::SetMapAndElements(isolate, object, to_map, elements);
      }
      if (v8_flags.trace_elements_transitions) {
        JSObject::PrintElementsTransition(
            stdout, object, from_kind, from_elements, to_kind,
            direct_handle(object->elements(), isolate));
      }
    }
  }
References v8::internal::DCHECK(), DCHECK_LE, DCHECK_NE, v8::internal::direct_handle(), v8::internal::GetHoleyElementsKind(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsHoleyElementsKind(), v8::internal::IsObjectElementsKind(), v8::internal::IsSmiElementsKind(), v8::internal::FixedArray::kMaxLength, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::JSObject::MigrateToMap(), v8::internal::JSObject::PrintElementsTransition(), v8::internal::JSObject::SetMapAndElements(), v8::internal::TERMINAL_FAST_ELEMENTS_KIND, and v8::internal::v8_flags.
Unshift()
template<typename Subclass , typename ElementsTraitsParam >
Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Unshift (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t unshift_size) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 785 of file elements.cc.
                                                                               {
    return Subclass::UnshiftImpl(isolate, receiver, args, unshift_size);
  }
References v8::base::args.
UnshiftImpl()
template<typename Subclass , typename ElementsTraitsParam >
static Maybe<uint32_t> v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::UnshiftImpl (Isolate * isolate, DirectHandle< JSArray > receiver, BuiltinArguments * args, uint32_t unshift_size) [inline], [static]
Definition at line 790 of file elements.cc.
                                                            {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Validate()
template<typename Subclass , typename ElementsTraitsParam >
void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::Validate (Isolate * isolate, Tagged< JSObject > holder) [inline], [final], [virtual]
Implements v8::internal::ElementsAccessor.
Definition at line 624 of file elements.cc.
                                                                 {
    DisallowGarbageCollection no_gc;
    Subclass::ValidateImpl(isolate, holder);
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
ValidateContents()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ValidateContents (Isolate * isolate, Tagged< JSObject > holder, size_t length) [inline], [static]
Definition at line 602 of file elements.cc.
                                              {}
ValidateImpl()
template<typename Subclass , typename ElementsTraitsParam >
static void v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ValidateImpl (Isolate * isolate, Tagged< JSObject > holder) [inline], [static]
Definition at line 605 of file elements.cc.
                                                                      {
    Tagged<FixedArrayBase> fixed_array_base = holder->elements();
    if (!IsHeapObject(fixed_array_base)) return;
    // Arrays that have been shifted in place can't be verified.
    if (IsFreeSpaceOrFiller(fixed_array_base)) return;
    size_t length = 0;
    if (IsJSArray(holder)) {
      Tagged<Object> length_obj = Cast<JSArray>(holder)->length();
      if (IsSmi(length_obj)) {
        length = Smi::ToInt(length_obj);
      }
    } else if (IsJSTypedArray(holder)) {
      length = Cast<JSTypedArray>(holder)->GetLength();
    } else {
      length = fixed_array_base->length();
    }
    Subclass::ValidateContents(isolate, holder, length);
  }
References v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::IsHeapObject(), v8::internal::IsSmi(), v8::internal::length, and v8::internal::Smi::ToInt().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc