v8::internal::torque::LocalValue Class Reference
#include <implementation-visitor.h>
Public Member Functions
LocalValue (LocationReference reference)
LocalValue (std::string inaccessible_explanation)
LocalValue (std::function< LocationReference()> lazy)
LocationReference GetLocationReference (Binding< LocalValue > *binding)
bool IsAccessibleNonLazy () const
Private Attributes
std::optional< LocationReference > value
std::optional< std::function< LocationReference()> > lazy
std::string inaccessible_explanation
Detailed Description
Definition at line 376 of file implementation-visitor.h.
Constructor & Destructor Documentation
LocalValue() [1/3]
v8::internal::torque::LocalValue::LocalValue (LocationReference reference) [inline], [explicit]
Definition at line 378 of file implementation-visitor.h.
      : value(std::move(reference)) {}
LocalValue() [2/3]
v8::internal::torque::LocalValue::LocalValue (std::string inaccessible_explanation) [inline], [explicit]
Definition at line 380 of file implementation-visitor.h.
      : inaccessible_explanation(std::move(inaccessible_explanation)) {}
LocalValue() [3/3]
v8::internal::torque::LocalValue::LocalValue (std::function< LocationReference()> lazy) [inline], [explicit]
Definition at line 382 of file implementation-visitor.h.
      : lazy(std::move(lazy)) {}
Member Function Documentation
GetLocationReference()
LocationReference v8::internal::torque::LocalValue::GetLocationReference (Binding< LocalValue > * binding) [inline]
Definition at line 385 of file implementation-visitor.h.
                                                                       {
    if (value) {
      const LocationReference& ref = *value;
      if (ref.IsVariableAccess()) {
        // Attach the binding to enable the never-assigned-to lint check.
        return LocationReference::VariableAccess(ref.GetVisitResult(), binding);
      }
      return ref;
    } else if (lazy) {
      return (*lazy)();
    } else {
      Error("Cannot access ", binding->name(), ": ", inaccessible_explanation)
          .Throw();
    }
  }
References v8::internal::torque::Error(), v8::internal::torque::LocationReference::GetVisitResult(), inaccessible_explanation, v8::internal::torque::LocationReference::IsVariableAccess(), lazy, v8::internal::torque::Binding< T >::name(), v8::internal::torque::MessageBuilder::Throw(), value, and v8::internal::torque::LocationReference::VariableAccess().
IsAccessibleNonLazy()
bool v8::internal::torque::LocalValue::IsAccessibleNonLazy () const [inline]
Definition at line 401 of file implementation-visitor.h.
{ return value.has_value(); }
References value.
Member Data Documentation
inaccessible_explanation
std::string v8::internal::torque::LocalValue::inaccessible_explanation [private]
Definition at line 406 of file implementation-visitor.h.
Referenced by GetLocationReference().
lazy
std::optional<std::function<LocationReference()> > v8::internal::torque::LocalValue::lazy [private]
Definition at line 405 of file implementation-visitor.h.
Referenced by GetLocationReference().
value
std::optional<LocationReference> v8::internal::torque::LocalValue::value [private]
Definition at line 404 of file implementation-visitor.h.
Referenced by GetLocationReference(), and IsAccessibleNonLazy().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.h