cppgc::internal::MakeGarbageCollectedTraitInternal Class Reference
#include <allocation.h>
Classes
struct AllocationDispatcher
struct AllocationDispatcher< GCInfoType, CustomSpace, api_constants::kDefaultAlignment >
struct AllocationDispatcher< GCInfoType, void, alignment >
struct AllocationDispatcher< GCInfoType, void, api_constants::kDefaultAlignment >
Static Protected Member Functions
static void MarkObjectAsFullyConstructed (const void *payload)
Static Private Member Functions
static void *CPPGC_DEFAULT_ALIGNED Allocate (cppgc::AllocationHandle &, size_t, GCInfoIndex)
static void *CPPGC_DOUBLE_WORD_ALIGNED Allocate (cppgc::AllocationHandle &, size_t, AlignVal, GCInfoIndex)
static void *CPPGC_DEFAULT_ALIGNED Allocate (cppgc::AllocationHandle &, size_t, GCInfoIndex, CustomSpaceIndex)
static void *CPPGC_DOUBLE_WORD_ALIGNED Allocate (cppgc::AllocationHandle &, size_t, AlignVal, GCInfoIndex, CustomSpaceIndex)
Friends
class HeapObjectHeader
Detailed Description
Definition at line 49 of file allocation.h.
Member Function Documentation
Allocate() [1/4]
CPPGC_FORCE_ALWAYS_INLINE void * cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate (cppgc::AllocationHandle & handle, size_t size, AlignVal alignment, GCInfoIndex index) [static], [private]
Definition at line 44 of file allocation.cc.
                       {
  return static_cast<ObjectAllocator&>(handle).AllocateObject(size, alignment,
                                                              index);
}
References v8::internal::handle(), v8::internal::index, and size().
Allocate() [2/4]
CPPGC_FORCE_ALWAYS_INLINE void * cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate (cppgc::AllocationHandle & handle, size_t size, AlignVal alignment, GCInfoIndex index, CustomSpaceIndex space_index) [static], [private]
Definition at line 64 of file allocation.cc.
                                                     {
  return static_cast<ObjectAllocator&>(handle).AllocateObject(
      size, alignment, index, space_index);
}
References v8::internal::handle(), v8::internal::index, and size().
Allocate() [3/4]
CPPGC_FORCE_ALWAYS_INLINE void * cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate (cppgc::AllocationHandle & handle, size_t size, GCInfoIndex index) [static], [private]
Definition at line 36 of file allocation.cc.
                                                                   {
  return static_cast<ObjectAllocator&>(handle).AllocateObject(size, index);
}
References v8::internal::handle(), v8::internal::index, and size().
Referenced by cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, alignment >::Invoke(), cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, api_constants::kDefaultAlignment >::Invoke(), cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, void, alignment >::Invoke(), and cppgc::internal::MakeGarbageCollectedTraitInternal::AllocationDispatcher< GCInfoType, CustomSpace, api_constants::kDefaultAlignment >::Invoke().
Allocate() [4/4]
CPPGC_FORCE_ALWAYS_INLINE void * cppgc::internal::MakeGarbageCollectedTraitInternal::Allocate (cppgc::AllocationHandle & handle, size_t size, GCInfoIndex index, CustomSpaceIndex space_index) [static], [private]
Definition at line 54 of file allocation.cc.
                                  {
  return static_cast<ObjectAllocator&>(handle).AllocateObject(size, index,
                                                              space_index);
}
References v8::internal::handle(), v8::internal::index, and size().
MarkObjectAsFullyConstructed()
static void cppgc::internal::MakeGarbageCollectedTraitInternal::MarkObjectAsFullyConstructed (const void * payload) [inline], [static], [protected]
Definition at line 51 of file allocation.h.
                                                                       {
    // See api_constants for an explanation of the constants.
    std::atomic<uint16_t>* atomic_mutable_bitfield =
        reinterpret_cast<std::atomic<uint16_t>*>(
            const_cast<uint16_t*>(reinterpret_cast<const uint16_t*>(
                reinterpret_cast<const uint8_t*>(payload) -
                api_constants::kFullyConstructedBitFieldOffsetFromPayload)));
    // It's safe to split use load+store here (instead of a read-modify-write
    // operation), since it's guaranteed that this 16-bit bitfield is only
    // modified by a single thread. This is cheaper in terms of code bloat (on
    // ARM) and performance.
    uint16_t value = atomic_mutable_bitfield->load(std::memory_order_relaxed);
    value |= api_constants::kFullyConstructedBitMask;
    atomic_mutable_bitfield->store(value, std::memory_order_release);
  }
References cppgc::internal::api_constants::kFullyConstructedBitFieldOffsetFromPayload, cppgc::internal::api_constants::kFullyConstructedBitMask, and v8::internal::value.
Referenced by cppgc::internal::HeapObjectHeader::MarkAsFullyConstructed(), and cppgc::MakeGarbageCollectedTraitBase< T >::MarkObjectAsFullyConstructed().
Friends And Related Function Documentation
HeapObjectHeader
friend class HeapObjectHeader [friend]
Definition at line 133 of file allocation.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/allocation.h
/mnt/V8SourceCode/src/heap/cppgc/allocation.cc