v8::internal::CodeAddressMap Class Reference
#include <serializer.h>
Classes
class NameMap
Public Member Functions
CodeAddressMap (Isolate *isolate)
~CodeAddressMap () override
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
const char * Lookup (Address address)
Private Member Functions
void LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo >, const char *name, size_t length) override
Private Attributes
NameMap address_to_name_map_
Additional Inherited Members
Detailed Description
Definition at line 25 of file serializer.h.
Constructor & Destructor Documentation
CodeAddressMap()
v8::internal::CodeAddressMap::CodeAddressMap (Isolate * isolate) [inline], [explicit]
Definition at line 27 of file serializer.h.
                                            : CodeEventLogger(isolate) {
    CHECK(isolate->logger()->AddListener(this));
  }
References v8::internal::Logger::AddListener(), CHECK, and v8::internal::Isolate::logger().
 CodeAddressMap()
v8::internal::CodeAddressMap::~CodeAddressMap () [inline], [override]
Definition at line 31 of file serializer.h.
                             {
    CHECK(isolate_->logger()->RemoveListener(this));
  }
References CHECK, v8::internal::CodeEventLogger::isolate_, v8::internal::Isolate::logger(), and v8::internal::Logger::RemoveListener().
Member Function Documentation
BytecodeMoveEvent()
void v8::internal::CodeAddressMap::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 39 of file serializer.h.
                                                            {
    address_to_name_map_.Move(from.address(), to.address());
  }
References v8::internal::Tagged< HeapObject >::address(), address_to_name_map_, and v8::internal::CodeAddressMap::NameMap::Move().
CodeDisableOptEvent()
void v8::internal::CodeAddressMap::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 44 of file serializer.h.
                                                                             {}
CodeMoveEvent()
void v8::internal::CodeAddressMap::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 35 of file serializer.h.
                                                            {
    address_to_name_map_.Move(from.address(), to.address());
  }
References v8::internal::Tagged< HeapObject >::address(), address_to_name_map_, and v8::internal::CodeAddressMap::NameMap::Move().
LogRecordedBuffer()
void v8::internal::CodeAddressMap::LogRecordedBuffer (Tagged< AbstractCode > code, MaybeDirectHandle< SharedFunctionInfo > , const char * name, size_t length) [inline], [override], [private], [virtual]
Implements v8::internal::CodeEventLogger.
Definition at line 126 of file serializer.h.
                                                                   {
    DisallowGarbageCollection no_gc;
    address_to_name_map_.Insert(code.address(), name, length);
  }
References address_to_name_map_, code, v8::internal::CodeAddressMap::NameMap::Insert(), v8::internal::length, v8::internal::name, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Lookup()
const char* v8::internal::CodeAddressMap::Lookup (Address address) [inline]
Definition at line 47 of file serializer.h.
                                      {
    return address_to_name_map_.Lookup(address);
  }
References address_to_name_map_, and v8::internal::CodeAddressMap::NameMap::Lookup().
Member Data Documentation
address_to_name_map_
NameMap v8::internal::CodeAddressMap::address_to_name_map_ [private]
Definition at line 140 of file serializer.h.
Referenced by BytecodeMoveEvent(), CodeMoveEvent(), LogRecordedBuffer(), and Lookup().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/serializer.h