v8::internal::ActionNode Class Reference
#include <regexp-nodes.h>
Public Types
enum ActionType {
SET_REGISTER_FOR_LOOP
, INCREMENT_REGISTER
, CLEAR_POSITION
, RESTORE_POSITION
,
BEGIN_POSITIVE_SUBMATCH
, BEGIN_NEGATIVE_SUBMATCH
, POSITIVE_SUBMATCH_SUCCESS
, EMPTY_MATCH_CHECK
,
CLEAR_CAPTURES
, MODIFY_FLAGS
 }
Public Member Functions
ActionNode * AsActionNode () override
void Accept (NodeVisitor *visitor) override
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
ActionType action_type () const
int FixedLengthLoopLength () override
RegExpFlags flags () const
ActionNode * success_node () const
bool Mentions (int reg) const
int value () const
bool IsSimpleAction () const
int register_from () const
int register_to () const
Static Public Member Functions
static ActionNode * SetRegisterForLoop (int reg, int val, RegExpNode *on_success)
static ActionNode * IncrementRegister (int reg, RegExpNode *on_success)
static ActionNode * ClearPosition (int reg, RegExpNode *on_success)
static ActionNode * RestorePosition (int reg, RegExpNode *on_success)
static ActionNode * ClearCaptures (Interval range, RegExpNode *on_success)
static ActionNode * BeginPositiveSubmatch (int stack_pointer_reg, int position_reg, RegExpNode *body, ActionNode *success_node)
static ActionNode * BeginNegativeSubmatch (int stack_pointer_reg, int position_reg, RegExpNode *on_success)
static ActionNode * PositiveSubmatchSuccess (int stack_pointer_reg, int restore_reg, int clear_capture_count, int clear_capture_from, RegExpNode *on_success)
static ActionNode * EmptyMatchCheck (int start_register, int repetition_register, int repetition_limit, RegExpNode *on_success)
static ActionNode * ModifyFlags (RegExpFlags flags, RegExpNode *on_success)
Protected Member Functions
ActionNode (ActionType action_type, RegExpNode *on_success)
ActionNode (ActionType action_type, RegExpNode *on_success, int from, int to=-1, int value=0)
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 struct {
  int register_from
  int register_to
  int value
 } u_simple
 struct {
  int stack_pointer_register
  int current_position_register
  int clear_register_count
  int clear_register_from
  ActionNode * success_node
 } u_submatch
 struct {
  int start_register
  int repetition_register
  int repetition_limit
 } u_empty_match_check
 struct {
  int flags
 } u_modify_flags
} data_
ActionType action_type_
friend Zone
Friends
class DotPrinterImpl
Additional Inherited Members
Detailed Description
Definition at line 327 of file regexp-nodes.h.
Member Enumeration Documentation
ActionType
enum v8::internal::ActionNode::ActionType
Enumerator
SET_REGISTER_FOR_LOOP
INCREMENT_REGISTER
CLEAR_POSITION
RESTORE_POSITION
BEGIN_POSITIVE_SUBMATCH
BEGIN_NEGATIVE_SUBMATCH
POSITIVE_SUBMATCH_SUCCESS
EMPTY_MATCH_CHECK
CLEAR_CAPTURES
MODIFY_FLAGS
Definition at line 329 of file regexp-nodes.h.
                  {
    SET_REGISTER_FOR_LOOP,
    INCREMENT_REGISTER,
    CLEAR_POSITION,
    RESTORE_POSITION,
    BEGIN_POSITIVE_SUBMATCH,
    BEGIN_NEGATIVE_SUBMATCH,
    POSITIVE_SUBMATCH_SUCCESS,
    EMPTY_MATCH_CHECK,
    CLEAR_CAPTURES,
    MODIFY_FLAGS
  };
Constructor & Destructor Documentation
ActionNode() [1/2]
v8::internal::ActionNode::ActionNode (ActionType action_type, RegExpNode * on_success) [inline], [protected]
Definition at line 410 of file regexp-nodes.h.
      : SeqRegExpNode(on_success), action_type_(action_type) {}
ActionNode() [2/2]
v8::internal::ActionNode::ActionNode (ActionType action_type, RegExpNode * on_success, int from, int to = -1, int value = 0) [inline], [protected]
Definition at line 413 of file regexp-nodes.h.
      : SeqRegExpNode(on_success), action_type_(action_type) {
    data_.u_simple.register_from = from;
    data_.u_simple.register_to = to == -1 ? from : to;
    data_.u_simple.value = value;
    DCHECK(IsSimpleAction());
  }
References data_, v8::internal::DCHECK(), IsSimpleAction(), and value.
Member Function Documentation
Accept()
void v8::internal::ActionNode::Accept (NodeVisitor * visitor) [override], [virtual]
Implements v8::internal::RegExpNode.
action_type()
ActionType v8::internal::ActionNode::action_type () const [inline]
Definition at line 371 of file regexp-nodes.h.
{ return action_type_; }
References action_type_.
Referenced by flags(), GetQuickCheckDetails(), IsSimpleAction(), v8::internal::Trace::PerformDeferredActions(), success_node(), value(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction(), and v8::internal::Analysis< Propagators >::VisitAction().
AsActionNode()
ActionNode* v8::internal::ActionNode::AsActionNode () [inline], [override]
Definition at line 363 of file regexp-nodes.h.
{ return this; }
Referenced by v8::internal::RegExpLookaround::Builder::ForMatch().
BeginNegativeSubmatch()
ActionNode * v8::internal::ActionNode::BeginNegativeSubmatch (int stack_pointer_reg, int position_reg, RegExpNode * on_success) [static]
Definition at line 679 of file regexp-compiler.cc.
                                                                      {
  ActionNode* result =
      on_success->zone()->New<ActionNode>(BEGIN_NEGATIVE_SUBMATCH, on_success);
  result->data_.u_submatch.stack_pointer_register = stack_reg;
  result->data_.u_submatch.current_position_register = position_reg;
  return result;
}
References BEGIN_NEGATIVE_SUBMATCH, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), v8::base::internal::result, and v8::internal::RegExpNode::zone().
Referenced by v8::internal::RegExpLookaround::Builder::ForMatch().
BeginPositiveSubmatch()
ActionNode * v8::internal::ActionNode::BeginPositiveSubmatch (int stack_pointer_reg, int position_reg, RegExpNode * body, ActionNode * success_node) [static]
Definition at line 668 of file regexp-compiler.cc.
                                                                        {
  ActionNode* result =
      body->zone()->New<ActionNode>(BEGIN_POSITIVE_SUBMATCH, body);
  result->data_.u_submatch.stack_pointer_register = stack_reg;
  result->data_.u_submatch.current_position_register = position_reg;
  result->data_.u_submatch.success_node = success_node;
  return result;
}
References BEGIN_POSITIVE_SUBMATCH, v8::internal::Zone::New(), v8::base::internal::result, success_node, and v8::internal::RegExpNode::zone().
Referenced by v8::internal::RegExpLookaround::Builder::ForMatch().
ClearCaptures()
ActionNode * v8::internal::ActionNode::ClearCaptures (Interval range, RegExpNode * on_success) [static]
Definition at line 663 of file regexp-compiler.cc.
                                                                            {
  return on_success->zone()->New<ActionNode>(CLEAR_CAPTURES, on_success,
                                             range.from(), range.to());
}
References CLEAR_CAPTURES, v8::internal::Interval::from(), v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), v8::internal::Interval::to(), and v8::internal::RegExpNode::zone().
ClearPosition()
ActionNode * v8::internal::ActionNode::ClearPosition (int reg, RegExpNode * on_success) [static]
Definition at line 655 of file regexp-compiler.cc.
                                                                     {
  return on_success->zone()->New<ActionNode>(CLEAR_POSITION, on_success, reg);
}
References CLEAR_POSITION, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
Emit()
void v8::internal::ActionNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 3478 of file regexp-compiler.cc.
                                                            {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  LimitResult limit_result = LimitVersions(compiler, trace);
  if (limit_result == DONE) return;
  DCHECK(limit_result == CONTINUE);
  RecursionCheck rc(compiler);
  switch (action_type_) {
    // Start with the actions we know how to defer. These are just recorded in
    // the new trace, no code is emitted right now. (If we backtrack then we
    // don't have to perform and undo these actions.)
    case CLEAR_POSITION:
    case RESTORE_POSITION:
    case INCREMENT_REGISTER:
    case SET_REGISTER_FOR_LOOP:
    case CLEAR_CAPTURES: {
      Trace new_trace = *trace;
      new_trace.add_action(this);
      on_success()->Emit(compiler, &new_trace);
      break;
    }
    // We don't yet have the ability to defer these.
    case BEGIN_POSITIVE_SUBMATCH:
    case BEGIN_NEGATIVE_SUBMATCH:
      if (!trace->is_trivial()) {
        // Complex situation: Flush the trace state to the assembler and
        // generate a generic version of this action. This call will
        // recurse back to the else clause here.
        trace->Flush(compiler, this);
      } else {
        assembler->WriteCurrentPositionToRegister(
            data_.u_submatch.current_position_register, 0);
        assembler->WriteStackPointerToRegister(
            data_.u_submatch.stack_pointer_register);
        on_success()->Emit(compiler, trace);
      }
      break;
    case EMPTY_MATCH_CHECK: {
      int start_pos_reg = data_.u_empty_match_check.start_register;
      int stored_pos = 0;
      int rep_reg = data_.u_empty_match_check.repetition_register;
      bool has_minimum = (rep_reg != RegExpCompiler::kNoRegister);
      bool know_dist = trace->GetStoredPosition(start_pos_reg, &stored_pos);
      if (know_dist && !has_minimum && stored_pos == trace->cp_offset()) {
        // If we know we haven't advanced and there is no minimum we
        // can just backtrack immediately.
        assembler->GoTo(trace->backtrack());
      } else if (know_dist && stored_pos < trace->cp_offset()) {
        // If we know we've advanced we can generate the continuation
        // immediately.
        on_success()->Emit(compiler, trace);
      } else if (!trace->is_trivial()) {
        trace->Flush(compiler, this);
      } else {
        Label skip_empty_check;
        // If we have a minimum number of repetitions we check the current
        // number first and skip the empty check if it's not enough.
        if (has_minimum) {
          int limit = data_.u_empty_match_check.repetition_limit;
          assembler->IfRegisterLT(rep_reg, limit, &skip_empty_check);
        }
        // If the match is empty we bail out, otherwise we fall through
        // to the on-success continuation.
        assembler->IfRegisterEqPos(data_.u_empty_match_check.start_register,
                                   trace->backtrack());
        assembler->Bind(&skip_empty_check);
        on_success()->Emit(compiler, trace);
      }
      break;
    }
    case POSITIVE_SUBMATCH_SUCCESS: {
      if (!trace->is_trivial()) {
        trace->Flush(compiler, this, Trace::kFlushSuccess);
        return;
      }
      assembler->ReadCurrentPositionFromRegister(
          data_.u_submatch.current_position_register);
      assembler->ReadStackPointerFromRegister(
          data_.u_submatch.stack_pointer_register);
      int clear_register_count = data_.u_submatch.clear_register_count;
      if (clear_register_count == 0) {
        on_success()->Emit(compiler, trace);
        return;
      }
      int clear_registers_from = data_.u_submatch.clear_register_from;
      Label clear_registers_backtrack;
      Trace new_trace = *trace;
      new_trace.set_backtrack(&clear_registers_backtrack);
      on_success()->Emit(compiler, &new_trace);
      assembler->Bind(&clear_registers_backtrack);
      int clear_registers_to = clear_registers_from + clear_register_count - 1;
      assembler->ClearRegisters(clear_registers_from, clear_registers_to);
      DCHECK(trace->backtrack() == nullptr);
      assembler->Backtrack();
      return;
    }
    case MODIFY_FLAGS: {
      compiler->set_flags(flags());
      on_success()->Emit(compiler, trace);
      break;
    }
    default:
      UNREACHABLE();
  }
}
References action_type_, v8::internal::Trace::add_action(), v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::Backtrack(), BEGIN_NEGATIVE_SUBMATCH, BEGIN_POSITIVE_SUBMATCH, v8::internal::RegExpMacroAssembler::Bind(), CLEAR_CAPTURES, CLEAR_POSITION, clear_register_count, v8::internal::RegExpMacroAssembler::ClearRegisters(), v8::internal::RegExpNode::CONTINUE, v8::internal::Trace::cp_offset(), data_, v8::internal::DCHECK(), v8::internal::RegExpNode::DONE, v8::internal::RegExpNode::Emit(), EMPTY_MATCH_CHECK, flags, v8::internal::Trace::Flush(), v8::internal::Trace::GetStoredPosition(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::RegExpMacroAssembler::IfRegisterEqPos(), v8::internal::RegExpMacroAssembler::IfRegisterLT(), INCREMENT_REGISTER, v8::internal::Trace::is_trivial(), v8::internal::Trace::kFlushSuccess, v8::internal::RegExpCompiler::kNoRegister, v8::internal::RegExpNode::LimitVersions(), v8::internal::RegExpCompiler::macro_assembler(), MODIFY_FLAGS, v8::internal::SeqRegExpNode::on_success(), POSITIVE_SUBMATCH_SUCCESS, v8::internal::RegExpMacroAssembler::ReadCurrentPositionFromRegister(), v8::internal::RegExpMacroAssembler::ReadStackPointerFromRegister(), RESTORE_POSITION, v8::internal::Trace::set_backtrack(), v8::internal::RegExpCompiler::set_flags(), SET_REGISTER_FOR_LOOP, v8::internal::UNREACHABLE(), v8::internal::RegExpMacroAssembler::WriteCurrentPositionToRegister(), and v8::internal::RegExpMacroAssembler::WriteStackPointerToRegister().
EmptyMatchCheck()
ActionNode * v8::internal::ActionNode::EmptyMatchCheck (int start_register, int repetition_register, int repetition_limit, RegExpNode * on_success) [static]
Definition at line 701 of file regexp-compiler.cc.
                                                                {
  ActionNode* result =
      on_success->zone()->New<ActionNode>(EMPTY_MATCH_CHECK, on_success);
  result->data_.u_empty_match_check.start_register = start_register;
  result->data_.u_empty_match_check.repetition_register = repetition_register;
  result->data_.u_empty_match_check.repetition_limit = repetition_limit;
  return result;
}
References EMPTY_MATCH_CHECK, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), repetition_limit, repetition_register, v8::base::internal::result, start_register, and v8::internal::RegExpNode::zone().
FillInBMInfo()
void v8::internal::ActionNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::SeqRegExpNode.
Definition at line 1399 of file regexp-compiler.cc.
                                                                          {
  std::optional<RegExpFlags> old_flags;
  if (action_type_ == MODIFY_FLAGS) {
    // It is not guaranteed that we hit the resetting modify flags node, due to
    // recursion budget limitation for filling in BMInfo. Therefore we reset the
    // flags manually to the previous state after recursing.
    old_flags = bm->compiler()->flags();
    bm->compiler()->set_flags(flags());
  }
  if (action_type_ == BEGIN_POSITIVE_SUBMATCH) {
    // We use the node after the lookaround to fill in the eats_at_least info
    // so we have to use the same node to fill in the Boyer-Moore info.
    success_node()->on_success()->FillInBMInfo(isolate, offset, budget - 1, bm,
                                               not_at_start);
  } else if (action_type_ != POSITIVE_SUBMATCH_SUCCESS) {
    // We don't use the node after a positive submatch success because it
    // rewinds the position. Since we returned 0 as the eats_at_least value for
    // this node, we don't need to fill in any data.
    on_success()->FillInBMInfo(isolate, offset, budget - 1, bm, not_at_start);
  }
  SaveBMInfo(bm, not_at_start, offset);
  if (old_flags.has_value()) {
    bm->compiler()->set_flags(*old_flags);
  }
}
References action_type_, BEGIN_POSITIVE_SUBMATCH, v8::internal::BoyerMooreLookahead::compiler(), v8::internal::RegExpNode::FillInBMInfo(), v8::internal::RegExpCompiler::flags(), flags, MODIFY_FLAGS, v8::internal::SeqRegExpNode::on_success(), POSITIVE_SUBMATCH_SUCCESS, v8::internal::RegExpNode::SaveBMInfo(), v8::internal::RegExpCompiler::set_flags(), and success_node.
FixedLengthLoopLength()
int v8::internal::ActionNode::FixedLengthLoopLength () [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 373 of file regexp-nodes.h.
                                       {
    return kNodeIsTooComplexForFixedLengthLoops;
  }
References v8::internal::RegExpNode::kNodeIsTooComplexForFixedLengthLoops.
flags()
RegExpFlags v8::internal::ActionNode::flags () const [inline]
Definition at line 376 of file regexp-nodes.h.
                            {
    DCHECK_EQ(action_type(), MODIFY_FLAGS);
    return RegExpFlags{data_.u_modify_flags.flags};
  }
References action_type(), data_, DCHECK_EQ, and MODIFY_FLAGS.
GetQuickCheckDetails()
void v8::internal::ActionNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int filled_in, bool not_at_start) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 1426 of file regexp-compiler.cc.
                                                         {
  if (action_type_ == SET_REGISTER_FOR_LOOP) {
    on_success()->GetQuickCheckDetailsFromLoopEntry(details, compiler,
                                                    filled_in, not_at_start);
  } else if (action_type_ == BEGIN_POSITIVE_SUBMATCH) {
    // We use the node after the lookaround to fill in the eats_at_least info
    // so we have to use the same node to fill in the QuickCheck info.
    success_node()->on_success()->GetQuickCheckDetails(details, compiler,
                                                       filled_in, not_at_start);
  } else if (action_type() != POSITIVE_SUBMATCH_SUCCESS) {
    // We don't use the node after a positive submatch success because it
    // rewinds the position. Since we returned 0 as the eats_at_least value
    // for this node, we don't need to fill in any data.
    std::optional<RegExpFlags> old_flags;
    if (action_type() == MODIFY_FLAGS) {
      // It is not guaranteed that we hit the resetting modify flags node, as
      // GetQuickCheckDetails doesn't travers the whole graph. Therefore we
      // reset the flags manually to the previous state after recursing.
      old_flags = compiler->flags();
      compiler->set_flags(flags());
    }
    on_success()->GetQuickCheckDetails(details, compiler, filled_in,
                                       not_at_start);
    if (old_flags.has_value()) {
      compiler->set_flags(*old_flags);
    }
  }
}
References action_type(), action_type_, BEGIN_POSITIVE_SUBMATCH, v8::internal::RegExpCompiler::flags(), flags, v8::internal::RegExpNode::GetQuickCheckDetails(), v8::internal::RegExpNode::GetQuickCheckDetailsFromLoopEntry(), MODIFY_FLAGS, v8::internal::SeqRegExpNode::on_success(), POSITIVE_SUBMATCH_SUCCESS, v8::internal::RegExpCompiler::set_flags(), SET_REGISTER_FOR_LOOP, and success_node.
IncrementRegister()
ActionNode * v8::internal::ActionNode::IncrementRegister (int reg, RegExpNode * on_success) [static]
Definition at line 650 of file regexp-compiler.cc.
                                                                         {
  return on_success->zone()->New<ActionNode>(INCREMENT_REGISTER, on_success,
                                             reg);
}
References INCREMENT_REGISTER, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
IsSimpleAction()
bool v8::internal::ActionNode::IsSimpleAction () const [inline]
Definition at line 394 of file regexp-nodes.h.
                              {
    return action_type() == CLEAR_POSITION ||
           action_type() == RESTORE_POSITION ||
           action_type() == INCREMENT_REGISTER ||
           action_type() == SET_REGISTER_FOR_LOOP ||
           action_type() == CLEAR_CAPTURES;
  }
References action_type(), CLEAR_CAPTURES, CLEAR_POSITION, INCREMENT_REGISTER, RESTORE_POSITION, and SET_REGISTER_FOR_LOOP.
Referenced by ActionNode(), and register_from().
Mentions()
bool v8::internal::ActionNode::Mentions (int reg) const [inline]
Definition at line 385 of file regexp-nodes.h.
                               {
    return base::IsInRange(reg, register_from(), register_to());
  }
References register_from, and register_to.
Referenced by v8::internal::Trace::PerformDeferredActions().
ModifyFlags()
ActionNode * v8::internal::ActionNode::ModifyFlags (RegExpFlags flags, RegExpNode * on_success) [static]
Definition at line 713 of file regexp-compiler.cc.
                                                                             {
  ActionNode* result =
      on_success->zone()->New<ActionNode>(MODIFY_FLAGS, on_success);
  result->data_.u_modify_flags.flags = flags;
  return result;
}
References flags, MODIFY_FLAGS, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), v8::base::internal::result, and v8::internal::RegExpNode::zone().
PositiveSubmatchSuccess()
ActionNode * v8::internal::ActionNode::PositiveSubmatchSuccess (int stack_pointer_reg, int restore_reg, int clear_capture_count, int clear_capture_from, RegExpNode * on_success) [static]
Definition at line 688 of file regexp-compiler.cc.
                                                                        {
  ActionNode* result = on_success->zone()->New<ActionNode>(
      POSITIVE_SUBMATCH_SUCCESS, on_success);
  result->data_.u_submatch.stack_pointer_register = stack_reg;
  result->data_.u_submatch.current_position_register = position_reg;
  result->data_.u_submatch.clear_register_count = clear_register_count;
  result->data_.u_submatch.clear_register_from = clear_register_from;
  return result;
}
References clear_register_count, clear_register_from, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), POSITIVE_SUBMATCH_SUCCESS, v8::base::internal::result, and v8::internal::RegExpNode::zone().
Referenced by v8::internal::RegExpLookaround::Builder::Builder().
register_from()
int v8::internal::ActionNode::register_from () const [inline]
Definition at line 402 of file regexp-nodes.h.
                            {
    DCHECK(IsSimpleAction());
    return data_.u_simple.register_from;
  }
References data_, v8::internal::DCHECK(), and IsSimpleAction().
register_to()
int v8::internal::ActionNode::register_to () const [inline]
Definition at line 407 of file regexp-nodes.h.
{ return data_.u_simple.register_to; }
References data_.
RestorePosition()
ActionNode * v8::internal::ActionNode::RestorePosition (int reg, RegExpNode * on_success) [static]
Definition at line 659 of file regexp-compiler.cc.
                                                                       {
  return on_success->zone()->New<ActionNode>(RESTORE_POSITION, on_success, reg);
}
References v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), RESTORE_POSITION, and v8::internal::RegExpNode::zone().
SetRegisterForLoop()
ActionNode * v8::internal::ActionNode::SetRegisterForLoop (int reg, int val, RegExpNode * on_success) [static]
Definition at line 644 of file regexp-compiler.cc.
                                                                   {
  return on_success->zone()->New<ActionNode>(SET_REGISTER_FOR_LOOP, on_success,
                                             reg, reg, val);
}
References v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), SET_REGISTER_FOR_LOOP, and v8::internal::RegExpNode::zone().
success_node()
ActionNode* v8::internal::ActionNode::success_node () const [inline]
Definition at line 380 of file regexp-nodes.h.
                                   {
    DCHECK_EQ(action_type(), BEGIN_POSITIVE_SUBMATCH);
    return data_.u_submatch.success_node;
  }
References action_type(), BEGIN_POSITIVE_SUBMATCH, data_, and DCHECK_EQ.
value()
int v8::internal::ActionNode::value () const [inline]
Definition at line 389 of file regexp-nodes.h.
                    {
    DCHECK(action_type() == SET_REGISTER_FOR_LOOP);
    return data_.u_simple.value;
  }
References action_type(), data_, v8::internal::DCHECK(), and SET_REGISTER_FOR_LOOP.
Friends And Related Function Documentation
DotPrinterImpl
friend class DotPrinterImpl [friend]
Definition at line 447 of file regexp-nodes.h.
Member Data Documentation
action_type_
ActionType v8::internal::ActionNode::action_type_ [private]
Definition at line 446 of file regexp-nodes.h.
Referenced by action_type(), Emit(), FillInBMInfo(), and GetQuickCheckDetails().
clear_register_count
int v8::internal::ActionNode::clear_register_count
Definition at line 432 of file regexp-nodes.h.
Referenced by Emit(), and PositiveSubmatchSuccess().
clear_register_from
int v8::internal::ActionNode::clear_register_from
Definition at line 433 of file regexp-nodes.h.
Referenced by PositiveSubmatchSuccess().
current_position_register
int v8::internal::ActionNode::current_position_register
Definition at line 431 of file regexp-nodes.h.
union { ... } v8::internal::ActionNode::data_ [private]
Referenced by ActionNode(), Emit(), flags(), register_from(), register_to(), success_node(), and value().
flags
int v8::internal::ActionNode::flags
Definition at line 442 of file regexp-nodes.h.
Referenced by Emit(), FillInBMInfo(), GetQuickCheckDetails(), ModifyFlags(), and v8::internal::Analysis< Propagators >::VisitAction().
register_from
int v8::internal::ActionNode::register_from
Definition at line 425 of file regexp-nodes.h.
Referenced by v8::internal::Trace::FindAffectedRegisters(), and Mentions().
register_to
int v8::internal::ActionNode::register_to
Definition at line 426 of file regexp-nodes.h.
Referenced by v8::internal::Trace::FindAffectedRegisters(), and Mentions().
repetition_limit
int v8::internal::ActionNode::repetition_limit
Definition at line 439 of file regexp-nodes.h.
Referenced by EmptyMatchCheck().
repetition_register
int v8::internal::ActionNode::repetition_register
Definition at line 438 of file regexp-nodes.h.
Referenced by EmptyMatchCheck().
stack_pointer_register
int v8::internal::ActionNode::stack_pointer_register
Definition at line 430 of file regexp-nodes.h.
start_register
int v8::internal::ActionNode::start_register
Definition at line 437 of file regexp-nodes.h.
Referenced by EmptyMatchCheck().
success_node
ActionNode* v8::internal::ActionNode::success_node
Definition at line 434 of file regexp-nodes.h.
Referenced by BeginPositiveSubmatch(), FillInBMInfo(), GetQuickCheckDetails(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAction().
struct { ... } v8::internal::ActionNode::u_empty_match_check
struct { ... } v8::internal::ActionNode::u_modify_flags
struct { ... } v8::internal::ActionNode::u_simple
struct { ... } v8::internal::ActionNode::u_submatch
value
int v8::internal::ActionNode::value
Definition at line 427 of file regexp-nodes.h.
Referenced by ActionNode(), and v8::internal::Trace::PerformDeferredActions().
Zone
friend v8::internal::ActionNode::Zone [private]
Definition at line 448 of file regexp-nodes.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc