v8::internal::BitVector::Iterator Class Reference
#include <bit-vector.h>
Classes
struct EndTag
struct StartTag
Public Member Functions
V8_EXPORT_PRIVATE void operator++ ()
int operator* () const
bool operator== (const Iterator &other) const
bool operator!= (const Iterator &other) const
Private Member Functions
Iterator (const BitVector *target, StartTag)
Iterator (const BitVector *target, EndTag)
Private Attributes
uintptr_t * ptr_
uintptr_t * end_
int current_index_
Static Private Attributes
static constexpr struct v8::internal::BitVector::Iterator::StartTag kStartTag = {}
static constexpr struct v8::internal::BitVector::Iterator::EndTag kEndTag = {}
Friends
class BitVector
Detailed Description
Definition at line 19 of file bit-vector.h.
Constructor & Destructor Documentation
Iterator() [1/2]
v8::internal::BitVector::Iterator::Iterator (const BitVector * target, StartTag) [inline], [explicit], [private]
Definition at line 67 of file bit-vector.h.
        :
#ifdef DEBUG
          target_(target),
#endif
          ptr_(target->data_begin_),
          end_(target->data_end_),
          current_index_(0) {
      DCHECK_LT(ptr_, end_);
      while (*ptr_ == 0) {
        ++ptr_;
        current_index_ += kDataBits;
        if (ptr_ == end_) return;
      }
      current_index_ += base::bits::CountTrailingZeros(*ptr_);
    }
References v8::base::bits::CountTrailingZeros(), and DCHECK_LT.
Iterator() [2/2]
v8::internal::BitVector::Iterator::Iterator (const BitVector * target, EndTag) [inline], [explicit], [private]
Definition at line 84 of file bit-vector.h.
        :
#ifdef DEBUG
          target_(target),
#endif
          ptr_(target->data_end_),
          end_(target->data_end_),
          current_index_(target->data_length() * kDataBits) {
    }
Member Function Documentation
operator!=()
bool v8::internal::BitVector::Iterator::operator!= (const Iterator & other) const [inline]
Definition at line 59 of file bit-vector.h.
{ return !(*this == other); }
operator*()
int v8::internal::BitVector::Iterator::operator* () const [inline]
Definition at line 45 of file bit-vector.h.
                          {
      DCHECK_NE(end_, ptr_);
      DCHECK(target_->Contains(current_index_));
      return current_index_;
    }
References v8::internal::DCHECK(), and DCHECK_NE.
operator++()
V8_EXPORT_PRIVATE void v8::internal::BitVector::Iterator::operator++ () [inline]
Definition at line 21 of file bit-vector.h.
                                               {
      int bit_in_word = current_index_ & (kDataBits - 1);
      if (bit_in_word < kDataBits - 1) {
        uintptr_t remaining_bits = *ptr_ >> (bit_in_word + 1);
        if (remaining_bits) {
          int next_bit_in_word = base::bits::CountTrailingZeros(remaining_bits);
          current_index_ += next_bit_in_word + 1;
          return;
        }
      }
      // Move {current_index_} down to the beginning of the current word, before
      // starting to search for the next non-empty word.
      current_index_ = RoundDown(current_index_, kDataBits);
      do {
        ++ptr_;
        current_index_ += kDataBits;
        if (ptr_ == end_) return;
      } while (*ptr_ == 0);
      uintptr_t trailing_zeros = base::bits::CountTrailingZeros(*ptr_);
      current_index_ += trailing_zeros;
    }
References v8::base::bits::CountTrailingZeros(), and RoundDown().
operator==()
bool v8::internal::BitVector::Iterator::operator== (const Iterator & other) const [inline]
Definition at line 51 of file bit-vector.h.
                                                 {
      DCHECK_EQ(target_, other.target_);
      DCHECK_EQ(end_, other.end_);
      DCHECK_IMPLIES(current_index_ == other.current_index_,
                     ptr_ == other.ptr_);
      return current_index_ == other.current_index_;
    }
References current_index_, DCHECK_EQ, DCHECK_IMPLIES, end_, and ptr_.
Friends And Related Function Documentation
BitVector
friend class BitVector [friend]
Definition at line 101 of file bit-vector.h.
Member Data Documentation
current_index_
int v8::internal::BitVector::Iterator::current_index_ [private]
Definition at line 99 of file bit-vector.h.
Referenced by operator==().
end_
uintptr_t* v8::internal::BitVector::Iterator::end_ [private]
Definition at line 98 of file bit-vector.h.
Referenced by operator==().
kEndTag
constexpr struct v8::internal::BitVector::Iterator::EndTag v8::internal::BitVector::Iterator::kEndTag = {} [static], [private]
kStartTag
constexpr struct v8::internal::BitVector::Iterator::StartTag v8::internal::BitVector::Iterator::kStartTag = {} [static], [private]
ptr_
uintptr_t* v8::internal::BitVector::Iterator::ptr_ [private]
Definition at line 97 of file bit-vector.h.
Referenced by operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/bit-vector.h