cppgc::Visitor Class Reference
Visitor passed to trace methods.
#include <visitor.h>
Classes
class Key
Public Member Functions
Visitor (Key)
virtual ~Visitor ()=default
template<typename T >
void Trace (const Member< T > &member)
Trace method for Member.
template<typename T >
void Trace (const WeakMember< T > &weak_member)
Trace method for WeakMember.
template<typename T >
void TraceMultiple (const subtle::UncompressedMember< T > *start, size_t len)
template<typename T , std::enable_if_t<!std::is_same_v< Member< T >, subtle::UncompressedMember< T >>> * = nullptr>
void TraceMultiple (const Member< T > *start, size_t len)
template<typename T >
void Trace (const T &object)
Trace method for inlined objects that are not allocated themselves but otherwise follow managed heap layout and have a Trace() method.
template<typename T >
void TraceMultiple (const T *start, size_t len)
template<typename T , void(T::*)(const LivenessBroker &) method>
void RegisterWeakCallbackMethod (const T *object)
Registers a weak callback method on the object of type T.
template<typename K , typename V >
void Trace (const EphemeronPair< K, V > &ephemeron_pair)
Trace method for EphemeronPair.
template<typename KeyType , typename ValueType >
void TraceEphemeron (const WeakMember< KeyType > &weak_member_key, const Member< ValueType > *member_value)
Trace method for a single ephemeron.
template<typename KeyType , typename ValueType >
void TraceEphemeron (const WeakMember< KeyType > &weak_member_key, const ValueType *value)
Trace method for a single ephemeron.
template<typename T >
void TraceStrongly (const WeakMember< T > &weak_member)
Trace method that strongifies a WeakMember.
template<typename T >
void TraceStrongContainer (const T *object)
Trace method for retaining containers strongly.
template<typename T >
void TraceWeakContainer (const T *object, WeakCallback callback, const void *callback_data)
Trace method for retaining containers weakly.
template<typename T >
void RegisterMovableReference (const T **slot)
Registers a slot containing a reference to an object allocated on a compactable space.
virtual void RegisterWeakCallback (WeakCallback callback, const void *data)
Registers a weak callback that is invoked during garbage collection.
virtual V8_WARN_UNUSED_RESULT bool DeferTraceToMutatorThreadIfConcurrent (const void *parameter, TraceCallback callback, size_t deferred_size)
Defers tracing an object from a concurrent thread to the mutator thread.
virtual bool IsConcurrent () const
Checks whether the visitor is running concurrently to the mutator or not.
Protected Member Functions
virtual void Visit (const void *self, TraceDescriptor)
virtual void VisitWeak (const void *self, TraceDescriptor, WeakCallback, const void *weak_member)
virtual void VisitEphemeron (const void *key, const void *value, TraceDescriptor value_desc)
virtual void VisitWeakContainer (const void *self, TraceDescriptor strong_desc, TraceDescriptor weak_desc, WeakCallback callback, const void *data)
virtual void HandleMovableReference (const void **)
virtual void VisitMultipleUncompressedMember (const void *start, size_t len, TraceDescriptorCallback get_trace_descriptor)
Private Member Functions
template<typename T >
void TraceImpl (const T *t)
Static Private Member Functions
template<typename T , void(T::*)(const LivenessBroker &) method>
static void WeakCallbackMethodDelegate (const LivenessBroker &info, const void *self)
template<typename PointerType >
static void HandleWeak (const LivenessBroker &info, const void *object)
Friends
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
class internal::BasicCrossThreadPersistent
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
class internal::BasicPersistent
class internal::ConservativeTracingVisitor
class internal::VisitorBase
Detailed Description
Visitor passed to trace methods.
All managed pointers must have called the Visitor's trace method on them.
class Foo final : public GarbageCollected<Foo> {
 public:
  void Trace(Visitor* visitor) const {
    visitor->Trace(foo_);
    visitor->Trace(weak_foo_);
  }
 private:
  Member<Foo> foo_;
  WeakMember<Foo> weak_foo_;
};
Definition at line 75 of file visitor.h.
Constructor & Destructor Documentation
Visitor()
cppgc::Visitor::Visitor (Key) [inline], [explicit]
Definition at line 83 of file visitor.h.
{}
 Visitor()
virtual cppgc::Visitor::~Visitor () [virtual], [default]
Member Function Documentation
DeferTraceToMutatorThreadIfConcurrent()
virtual V8_WARN_UNUSED_RESULT bool cppgc::Visitor::DeferTraceToMutatorThreadIfConcurrent (const void * parameter, TraceCallback callback, size_t deferred_size) [inline], [virtual]
Defers tracing an object from a concurrent thread to the mutator thread.
Should be called by Trace methods of types that are not safe to trace concurrently.
Parameters
parameter tells the trace callback which object was deferred.
callback to be invoked for tracing on the mutator thread.
deferred_size size of deferred object.
Returns
false if the object does not need to be deferred (i.e. currently traced on the mutator thread) and true otherwise (i.e. currently traced on a concurrent thread).
Reimplemented in cppgc::internal::ConcurrentMarkingVisitor, and v8::internal::ConcurrentUnifiedHeapMarkingVisitor.
Definition at line 366 of file visitor.h.
                                                                           {
    // By default tracing is not deferred.
    return false;
  }
HandleMovableReference()
virtual void cppgc::Visitor::HandleMovableReference (const void **) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::MarkingVisitorBase, and v8::internal::UnifiedHeapMarkingVisitorBase.
Definition at line 386 of file visitor.h.
{}
HandleWeak()
template<typename PointerType >
static void cppgc::Visitor::HandleWeak (const LivenessBroker & info, const void * object) [inline], [static], [private]
Definition at line 431 of file visitor.h.
                                                                         {
    const PointerType* weak = static_cast<const PointerType*>(object);
    if (!info.IsHeapObjectAlive(weak->GetFromGC())) {
      weak->ClearFromGC();
    }
  }
References cppgc::LivenessBroker::IsHeapObjectAlive().
IsConcurrent()
virtual bool cppgc::Visitor::IsConcurrent () const [inline], [virtual]
Checks whether the visitor is running concurrently to the mutator or not.
Reimplemented in cppgc::internal::ConcurrentMarkingVisitor, and v8::internal::ConcurrentUnifiedHeapMarkingVisitor.
Definition at line 375 of file visitor.h.
{ return false; }
RegisterMovableReference()
template<typename T >
void cppgc::Visitor::RegisterMovableReference (const T ** slot) [inline]
Registers a slot containing a reference to an object allocated on a compactable space.
Such references maybe be arbitrarily moved by the GC.
Parameters
slot location of reference to object that might be moved by the GC. The slot must contain an uncompressed pointer.
Definition at line 336 of file visitor.h.
                                                {
    static_assert(internal::IsAllocatedOnCompactableSpace<T>::value,
                  "Only references to objects allocated on compactable spaces "
                  "should be registered as movable slots.");
    static_assert(!IsGarbageCollectedMixinTypeV<T>,
                  "Mixin types do not support compaction.");
    HandleMovableReference(reinterpret_cast<const void**>(slot));
  }
RegisterWeakCallback()
virtual void cppgc::Visitor::RegisterWeakCallback (WeakCallback callback, const void * data) [inline], [virtual]
Registers a weak callback that is invoked during garbage collection.
Parameters
callback to be invoked.
data custom data that is passed to the callback.
Reimplemented in cppgc::internal::MarkingVisitorBase.
Definition at line 351 of file visitor.h.
{}
RegisterWeakCallbackMethod()
template<typename T , void(T::*)(const LivenessBroker &) method>
void cppgc::Visitor::RegisterWeakCallbackMethod (const T * object) [inline]
Registers a weak callback method on the object of type T.
See LivenessBroker for an usage example.
Parameters
object of type T specifying a weak callback method.
Definition at line 207 of file visitor.h.
                                                   {
    RegisterWeakCallback(&WeakCallbackMethodDelegate<T, method>, object);
  }
Trace() [1/4]
template<typename K , typename V >
void cppgc::Visitor::Trace (const EphemeronPair< K, V > & ephemeron_pair) [inline]
Trace method for EphemeronPair.
Parameters
ephemeron_pair EphemeronPair reference weakly retaining a key object and strongly retaining a value object in case the key object is alive.
Definition at line 218 of file visitor.h.
                                                        {
    TraceEphemeron(ephemeron_pair.key, &ephemeron_pair.value);
    RegisterWeakCallbackMethod<EphemeronPair<K, V>,
                               &EphemeronPair<K, V>::ClearValueIfKeyIsDead>(
        &ephemeron_pair);
  }
References cppgc::EphemeronPair< K, V >::key, and cppgc::EphemeronPair< K, V >::value.
Trace() [2/4]
template<typename T >
void cppgc::Visitor::Trace (const Member< T > & member) [inline]
Trace method for Member.
Parameters
member Member reference retaining an object.
Definition at line 93 of file visitor.h.
                                      {
    const T* value = member.GetAtomic();
    CPPGC_DCHECK(value != kSentinelPointer);
    TraceImpl(value);
  }
References CPPGC_DCHECK, cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetAtomic(), cppgc::kSentinelPointer, and v8::internal::value.
Referenced by cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::Trace().
Trace() [3/4]
template<typename T >
void cppgc::Visitor::Trace (const T & object) [inline]
Trace method for inlined objects that are not allocated themselves but otherwise follow managed heap layout and have a Trace() method.
Parameters
object reference of the inlined object.
Definition at line 169 of file visitor.h.
                              {
#if V8_ENABLE_CHECKS
    // This object is embedded in potentially multiple nested objects. The
    // outermost object must not be in construction as such objects are (a) not
    // processed immediately, and (b) only processed conservatively if not
    // otherwise possible.
    CheckObjectNotInConstruction(&object);
#endif // V8_ENABLE_CHECKS
    TraceTrait<T>::Trace(this, &object);
  }
References cppgc::internal::TraceTraitBase< T >::Trace().
Trace() [4/4]
template<typename T >
void cppgc::Visitor::Trace (const WeakMember< T > & weak_member) [inline]
Trace method for WeakMember.
Parameters
weak_member WeakMember reference weakly retaining an object.
Definition at line 105 of file visitor.h.
                                               {
    static_assert(sizeof(T), "Pointee type must be fully defined.");
    static_assert(internal::IsGarbageCollectedOrMixinType<T>::value,
                  "T must be GarbageCollected or GarbageCollectedMixin type");
    static_assert(!internal::IsAllocatedOnCompactableSpace<T>::value,
                  "Weak references to compactable objects are not allowed");
    const T* value = weak_member.GetAtomic();
    // Bailout assumes that WeakMember emits write barrier.
    if (!value) {
      return;
    }
    CPPGC_DCHECK(value != kSentinelPointer);
    VisitWeak(value, TraceTrait<T>::GetTraceDescriptor(value),
              &HandleWeak<WeakMember<T>>, &weak_member);
  }
References CPPGC_DCHECK, cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetAtomic(), cppgc::kSentinelPointer, and v8::internal::value.
TraceEphemeron() [1/2]
template<typename KeyType , typename ValueType >
void cppgc::Visitor::TraceEphemeron (const WeakMember< KeyType > & weak_member_key, const Member< ValueType > * member_value) [inline]
Trace method for a single ephemeron.
Used for tracing a raw ephemeron in which the key and value are kept separately.
Parameters
weak_member_key WeakMember reference weakly retaining a key object.
member_value Member reference with ephemeron semantics.
Definition at line 233 of file visitor.h.
                                                             {
    const KeyType* key = weak_member_key.GetAtomic();
    if (!key) return;
    // `value` must always be non-null.
    CPPGC_DCHECK(member_value);
    const ValueType* value = member_value->GetAtomic();
    if (!value) return;
    // KeyType and ValueType may refer to GarbageCollectedMixin.
    TraceDescriptor value_desc =
        TraceTrait<ValueType>::GetTraceDescriptor(value);
    CPPGC_DCHECK(value_desc.base_object_payload);
    const void* key_base_object_payload =
        TraceTrait<KeyType>::GetTraceDescriptor(key).base_object_payload;
    CPPGC_DCHECK(key_base_object_payload);
    VisitEphemeron(key_base_object_payload, value, value_desc);
  }
References cppgc::TraceDescriptor::base_object_payload, CPPGC_DCHECK, cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetAtomic(), cppgc::internal::TraceTraitBase< T >::GetTraceDescriptor(), v8::internal::key, and v8::internal::value.
Referenced by cppgc::EphemeronPair< K, V >::Trace().
TraceEphemeron() [2/2]
template<typename KeyType , typename ValueType >
void cppgc::Visitor::TraceEphemeron (const WeakMember< KeyType > & weak_member_key, const ValueType * value) [inline]
Trace method for a single ephemeron.
Used for tracing a raw ephemeron in which the key and value are kept separately. Note that this overload is for non-GarbageCollected values that can be traced though.
Parameters
key WeakMember reference weakly retaining a key object.
value Reference weakly retaining a value object. Note that ValueType here should not be Member. It is expected that TraceTrait<ValueType>::GetTraceDescriptor(value) returns a TraceDescriptor with a null base pointer but a valid trace method.
Definition at line 266 of file visitor.h.
                                              {
    static_assert(!IsGarbageCollectedOrMixinTypeV<ValueType>,
                  "garbage-collected types must use WeakMember and Member");
    const KeyType* key = weak_member_key.GetAtomic();
    if (!key) return;
    // `value` must always be non-null.
    CPPGC_DCHECK(value);
    TraceDescriptor value_desc =
        TraceTrait<ValueType>::GetTraceDescriptor(value);
    // `value_desc.base_object_payload` must be null as this override is only
    // taken for non-garbage-collected values.
    CPPGC_DCHECK(!value_desc.base_object_payload);
    // KeyType might be a GarbageCollectedMixin.
    const void* key_base_object_payload =
        TraceTrait<KeyType>::GetTraceDescriptor(key).base_object_payload;
    CPPGC_DCHECK(key_base_object_payload);
    VisitEphemeron(key_base_object_payload, value, value_desc);
  }
References cppgc::TraceDescriptor::base_object_payload, CPPGC_DCHECK, cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetAtomic(), cppgc::internal::TraceTraitBase< T >::GetTraceDescriptor(), v8::internal::key, and v8::internal::value.
TraceImpl()
template<typename T >
void cppgc::Visitor::TraceImpl (const T * t) [inline], [private]
Definition at line 439 of file visitor.h.
                             {
    static_assert(sizeof(T), "Pointee type must be fully defined.");
    static_assert(internal::IsGarbageCollectedOrMixinType<T>::value,
                  "T must be GarbageCollected or GarbageCollectedMixin type");
    if (!t) {
      return;
    }
    Visit(t, TraceTrait<T>::GetTraceDescriptor(t));
  }
Referenced by cppgc::internal::VisitorBase::TraceRawForTesting().
TraceMultiple() [1/3]
template<typename T , std::enable_if_t<!std::is_same_v< Member< T >, subtle::UncompressedMember< T >>> * = nullptr>
void cppgc::Visitor::TraceMultiple (const Member< T > * start, size_t len) [inline]
Definition at line 150 of file visitor.h.
                                                         {
    static_assert(sizeof(T), "Pointee type must be fully defined.");
    static_assert(internal::IsGarbageCollectedOrMixinType<T>::value,
                  "T must be GarbageCollected or GarbageCollectedMixin type");
#if defined(CPPGC_POINTER_COMPRESSION)
    static_assert(std::is_same_v<Member<T>, subtle::CompressedMember<T>>,
                  "Member and CompressedMember must be the same.");
    VisitMultipleCompressedMember(start, len,
                                  &TraceTrait<T>::GetTraceDescriptor);
#endif // defined(CPPGC_POINTER_COMPRESSION)
  }
TraceMultiple() [2/3]
template<typename T >
void cppgc::Visitor::TraceMultiple (const subtle::UncompressedMember< T > * start, size_t len) [inline]
Definition at line 139 of file visitor.h.
                                                                           {
    static_assert(sizeof(T), "Pointee type must be fully defined.");
    static_assert(internal::IsGarbageCollectedOrMixinType<T>::value,
                  "T must be GarbageCollected or GarbageCollectedMixin type");
    VisitMultipleUncompressedMember(start, len,
                                    &TraceTrait<T>::GetTraceDescriptor);
  }
TraceMultiple() [3/3]
template<typename T >
void cppgc::Visitor::TraceMultiple (const T * start, size_t len) [inline]
Definition at line 181 of file visitor.h.
                                                 {
#if V8_ENABLE_CHECKS
    // This object is embedded in potentially multiple nested objects. The
    // outermost object must not be in construction as such objects are (a) not
    // processed immediately, and (b) only processed conservatively if not
    // otherwise possible.
    CheckObjectNotInConstruction(start);
#endif // V8_ENABLE_CHECKS
    for (size_t i = 0; i < len; ++i) {
      const T* object = &start[i];
      if constexpr (std::is_polymorphic_v<T>) {
        // The object's vtable may be uninitialized in which case the object is
        // not traced.
        if (*reinterpret_cast<const uintptr_t*>(object) == 0) continue;
      }
      TraceTrait<T>::Trace(this, object);
    }
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and cppgc::internal::TraceTraitBase< T >::Trace().
TraceStrongContainer()
template<typename T >
void cppgc::Visitor::TraceStrongContainer (const T * object) [inline]
Trace method for retaining containers strongly.
Parameters
object reference to the container.
Definition at line 307 of file visitor.h.
                                             {
    TraceImpl(object);
  }
TraceStrongly()
template<typename T >
void cppgc::Visitor::TraceStrongly (const WeakMember< T > & weak_member) [inline]
Trace method that strongifies a WeakMember.
Parameters
weak_member WeakMember reference retaining an object.
Definition at line 295 of file visitor.h.
                                                       {
    const T* value = weak_member.GetAtomic();
    CPPGC_DCHECK(value != kSentinelPointer);
    TraceImpl(value);
  }
References CPPGC_DCHECK, cppgc::internal::BasicMember< T, WeaknessTag, WriteBarrierPolicy, CheckingPolicy, StorageType >::GetAtomic(), cppgc::kSentinelPointer, and v8::internal::value.
TraceWeakContainer()
template<typename T >
void cppgc::Visitor::TraceWeakContainer (const T * object, WeakCallback callback, const void * callback_data) [inline]
Trace method for retaining containers weakly.
Note that weak containers should emit write barriers.
Parameters
object reference to the container.
callback to be invoked.
callback_data custom data that is passed to the callback.
Definition at line 320 of file visitor.h.
                                                     {
    if (!object) return;
    VisitWeakContainer(object, TraceTrait<T>::GetTraceDescriptor(object),
                       TraceTrait<T>::GetWeakTraceDescriptor(object), callback,
                       callback_data);
  }
Visit()
virtual void cppgc::Visitor::Visit (const void * self, TraceDescriptor) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::MarkingVisitorBase, v8::internal::UnifiedHeapMarkingVisitorBase, cppgc::internal::anonymous_namespace{marking-verifier.cc}::VerificationVisitor, v8::internal::anonymous_namespace{unified-heap-marking-verifier.cc}::UnifiedHeapVerificationVisitor, v8::internal::GraphBuildingVisitor, and v8::internal::VisiblityVisitor.
Definition at line 378 of file visitor.h.
{}
Referenced by cppgc::internal::ConservativeTracingVisitor::VisitFullyConstructedConservatively().
VisitEphemeron()
virtual void cppgc::Visitor::VisitEphemeron (const void * key, const void * value, TraceDescriptor value_desc) [inline], [protected], [virtual]
Reimplemented in v8::internal::WeakVisitor, cppgc::internal::MarkingVisitorBase, and v8::internal::UnifiedHeapMarkingVisitorBase.
Definition at line 381 of file visitor.h.
                                                          {}
VisitMultipleUncompressedMember()
virtual void cppgc::Visitor::VisitMultipleUncompressedMember (const void * start, size_t len, TraceDescriptorCallback get_trace_descriptor) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::MarkingVisitorBase.
Definition at line 388 of file visitor.h.
                                                    {
    // Default implementation merely delegates to Visit().
    const char* it = static_cast<const char*>(start);
    const char* end = it + len * internal::kSizeOfUncompressedMember;
    for (; it < end; it += internal::kSizeOfUncompressedMember) {
      const auto* current = reinterpret_cast<const internal::RawPointer*>(it);
      const void* object = current->LoadAtomic();
      if (!object) continue;
      Visit(object, get_trace_descriptor(object));
    }
  }
References v8::internal::compiler::end(), cppgc::internal::kSizeOfUncompressedMember, and cppgc::internal::RawPointer::LoadAtomic().
VisitWeak()
virtual void cppgc::Visitor::VisitWeak (const void * self, TraceDescriptor , WeakCallback , const void * weak_member) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::MarkingVisitorBase, cppgc::internal::anonymous_namespace{marking-verifier.cc}::VerificationVisitor, and v8::internal::anonymous_namespace{unified-heap-marking-verifier.cc}::UnifiedHeapVerificationVisitor.
Definition at line 379 of file visitor.h.
                                                  {}
VisitWeakContainer()
virtual void cppgc::Visitor::VisitWeakContainer (const void * self, TraceDescriptor strong_desc, TraceDescriptor weak_desc, WeakCallback callback, const void * data) [inline], [protected], [virtual]
Reimplemented in cppgc::internal::anonymous_namespace{marking-verifier.cc}::VerificationVisitor, cppgc::internal::MarkingVisitorBase, v8::internal::anonymous_namespace{unified-heap-marking-verifier.cc}::UnifiedHeapVerificationVisitor, v8::internal::GraphBuildingVisitor, and v8::internal::WeakVisitor.
Definition at line 383 of file visitor.h.
                                                                           {}
WeakCallbackMethodDelegate()
template<typename T , void(T::*)(const LivenessBroker &) method>
static void cppgc::Visitor::WeakCallbackMethodDelegate (const LivenessBroker & info, const void * self) [inline], [static], [private]
Definition at line 423 of file visitor.h.
                                                           {
    // Callback is registered through a potential const Trace method but needs
    // to be able to modify fields. See HandleWeak.
    (const_cast<T*>(static_cast<const T*>(self))->*method)(info);
  }
Friends And Related Function Documentation
internal::BasicCrossThreadPersistent
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
friend class internal::BasicCrossThreadPersistent [friend]
Definition at line 455 of file visitor.h.
internal::BasicPersistent
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
friend class internal::BasicPersistent [friend]
Definition at line 458 of file visitor.h.
internal::ConservativeTracingVisitor
friend class internal::ConservativeTracingVisitor [friend]
Definition at line 459 of file visitor.h.
internal::VisitorBase
friend class internal::VisitorBase [friend]
Definition at line 460 of file visitor.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/visitor.h