v8::internal::LiveEdit Class Reference
Liveedit step-by-step:
#include <liveedit.h>
Static Public Member Functions
static void CompareStrings (Isolate *isolate, Handle< String > a, Handle< String > b, std::vector< SourceChangeRange > *diffs)
static int TranslatePosition (const std::vector< SourceChangeRange > &changed, int position)
static void PatchScript (Isolate *isolate, Handle< Script > script, Handle< String > source, bool preview, bool allow_top_frame_live_editing, debug::LiveEditResult *result)
Detailed Description
Liveedit step-by-step:
calculate diff between old source and new source,
map function literals from old source to new source,
create new script for new_source,
mark literals with changed code as changed, all others as unchanged,
check that for changed literals there are no:
running generators in the heap,
non droppable frames (e.g. running generator) above them on stack.
mark the bottom most frame with changed function as scheduled for restart if any,
for unchanged functions:
deoptimize,
remove from cache,
update source positions,
move to new script,
reset feedback information and preparsed scope information if any,
replace any sfi in constant pool with changed one if any.
for changed functions:
deoptimize
remove from cache,
reset feedback information,
update all links from js functions to old shared with new one.
swap scripts.
Definition at line 57 of file liveedit.h.
Member Function Documentation
CompareStrings()
void v8::internal::LiveEdit::CompareStrings (Isolate * isolate, Handle< String > a, Handle< String > b, std::vector< SourceChangeRange > * diffs) [static]
Definition at line 1117 of file liveedit.cc.
                                                                   {
  s1 = String::Flatten(isolate, s1);
  s2 = String::Flatten(isolate, s2);
  LineEndsWrapper line_ends1(isolate, s1);
  LineEndsWrapper line_ends2(isolate, s2);
  LineArrayCompareInput input(s1, s2, line_ends1, line_ends2);
  TokenizingLineArrayCompareOutput output(isolate, line_ends1, line_ends2, s1,
                                          s2, diffs);
  NarrowDownInput(&input, &output);
  Comparator::CalculateDifference(&input, &output);
}
References v8::internal::Comparator::CalculateDifference(), and v8::internal::anonymous_namespace{liveedit.cc}::NarrowDownInput().
Referenced by PatchScript().
PatchScript()
void v8::internal::LiveEdit::PatchScript (Isolate * isolate, Handle< Script > script, Handle< String > source, bool preview, bool allow_top_frame_live_editing, debug::LiveEditResult * result) [static]
Definition at line 851 of file liveedit.cc.
                                                        {
  std::vector<SourceChangeRange> diffs;
  LiveEdit::CompareStrings(isolate,
                           handle(Cast<String>(script->source()), isolate),
                           new_source, &diffs);
  if (diffs.empty()) {
    result->status = debug::LiveEditResult::OK;
    return;
  }
  ReusableUnoptimizedCompileState reusable_state(isolate);
  UnoptimizedCompileState compile_state;
  UnoptimizedCompileFlags flags =
      UnoptimizedCompileFlags::ForScriptCompile(isolate, *script);
  flags.set_is_eager(true);
  flags.set_is_reparse(true);
  ParseInfo parse_info(isolate, flags, &compile_state, &reusable_state);
  MaybeDirectHandle<ScopeInfo> outer_scope_info =
      DetermineOuterScopeInfo(isolate, script);
  std::vector<FunctionLiteral*> literals;
  std::map<uint32_t, std::vector<uint32_t>> eval_calls;
  if (!ParseScript(isolate, script, &parse_info, outer_scope_info, false,
                   &literals, &eval_calls, result))
    return;
  Handle<Script> new_script =
      isolate->factory()->CloneScript(script, new_source);
  UnoptimizedCompileState new_compile_state;
  UnoptimizedCompileFlags new_flags =
      UnoptimizedCompileFlags::ForScriptCompile(isolate, *new_script);
  new_flags.set_is_eager(true);
  ParseInfo new_parse_info(isolate, new_flags, &new_compile_state,
                           &reusable_state);
  std::vector<FunctionLiteral*> new_literals;
  std::map<uint32_t, std::vector<uint32_t>> new_eval_calls;
  if (!ParseScript(isolate, new_script, &new_parse_info, outer_scope_info, true,
                   &new_literals, &new_eval_calls, result)) {
    return;
  }
  FunctionLiteralChanges literal_changes;
  CalculateFunctionLiteralChanges(literals, diffs, &literal_changes);
  LiteralMap changed;
  LiteralMap unchanged;
  MapLiterals(literal_changes, new_literals, &unchanged, &changed);
  FunctionDataMap function_data_map;
  for (const auto& mapping : changed) {
    function_data_map.AddInterestingLiteral(script->id(), mapping.first);
    function_data_map.AddInterestingLiteral(new_script->id(), mapping.second);
  }
  for (const auto& mapping : unchanged) {
    function_data_map.AddInterestingLiteral(script->id(), mapping.first);
  }
  function_data_map.Fill(isolate);
  if (!CanPatchScript(changed, script, new_script, function_data_map,
                      allow_top_frame_live_editing, result)) {
    return;
  }
  if (preview) {
    result->status = debug::LiveEditResult::OK;
    return;
  }
  // Patching a script means that the bytecode on the stack may no longer
  // correspond to the bytecode of the JSFunction for that frame. As a result
  // it is no longer safe to flush bytecode since we might flush the new
  // bytecode for a JSFunction that is on the stack with an old bytecode, which
  // breaks the invariant that any JSFunction active on the stack is compiled.
  isolate->set_disable_bytecode_flushing(true);
  std::map<int, int> start_position_to_unchanged_id;
  for (const auto& mapping : unchanged) {
    FunctionData* data = nullptr;
    if (!function_data_map.Lookup(script, mapping.first, &data)) continue;
    Handle<SharedFunctionInfo> sfi;
    if (!data->shared.ToHandle(&sfi)) continue;
    DCHECK_EQ(sfi->script(), *script);
    isolate->compilation_cache()->Remove(sfi);
    isolate->debug()->DeoptimizeFunction(sfi);
    if (std::optional<Tagged<DebugInfo>> di = sfi->TryGetDebugInfo(isolate)) {
      DirectHandle<DebugInfo> debug_info(di.value(), isolate);
      isolate->debug()->RemoveBreakInfoAndMaybeFree(debug_info);
    }
    SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, sfi);
    UpdatePositions(isolate, sfi, mapping.second, diffs);
    sfi->set_script(*new_script, kReleaseStore);
    std::vector<uint32_t> source_infos =
        eval_calls[sfi->function_literal_id(kRelaxedLoad)];
    sfi->set_function_literal_id(mapping.second->function_literal_id(),
                                 kRelaxedStore);
    std::vector<uint32_t> target_infos =
        new_eval_calls[sfi->function_literal_id(kRelaxedLoad)];
    new_script->infos()->set(mapping.second->function_literal_id(),
                             MakeWeak(*sfi));
    if (sfi->HasBytecodeArray()) {
      for (size_t i = 0; i < source_infos.size(); i++) {
        Tagged<ScopeInfo> scope_info = Cast<ScopeInfo>(
            script->infos()->get(source_infos[i]).GetHeapObjectAssumeWeak());
        new_script->infos()->set(target_infos[i], MakeWeak(scope_info));
      }
    }
    DCHECK_EQ(sfi->function_literal_id(kRelaxedLoad),
              mapping.second->function_literal_id());
    // Save the new start_position -> id mapping, so that we can recover it when
    // iterating over changed functions' constant pools.
    start_position_to_unchanged_id[mapping.second->start_position()] =
        mapping.second->function_literal_id();
    if (sfi->HasUncompiledDataWithPreparseData(isolate)) {
      sfi->ClearPreparseData(isolate);
    }
    for (auto& js_function : data->js_functions) {
      js_function->set_raw_feedback_cell(
          *isolate->factory()->many_closures_cell());
      if (!js_function->is_compiled(isolate)) continue;
      IsCompiledScope is_compiled_scope(
          js_function->shared()->is_compiled_scope(isolate));
      JSFunction::EnsureFeedbackVector(isolate, js_function,
                                       &is_compiled_scope);
    }
    if (!sfi->HasBytecodeArray()) continue;
    Tagged<TrustedFixedArray> constants =
        sfi->GetBytecodeArray(isolate)->constant_pool();
    for (int i = 0; i < constants->length(); ++i) {
      if (!IsSharedFunctionInfo(constants->get(i))) continue;
      data = nullptr;
      if (!function_data_map.Lookup(Cast<SharedFunctionInfo>(constants->get(i)),
                                    &data)) {
        continue;
      }
      auto change_it = changed.find(data->literal);
      if (change_it == changed.end()) continue;
      if (!function_data_map.Lookup(new_script, change_it->second, &data)) {
        continue;
      }
      Handle<SharedFunctionInfo> new_sfi;
      if (!data->shared.ToHandle(&new_sfi)) continue;
      constants->set(i, *new_sfi);
    }
  }
  isolate->LocalsBlockListCacheRehash();
  for (const auto& mapping : changed) {
    FunctionData* data = nullptr;
    if (!function_data_map.Lookup(new_script, mapping.second, &data)) continue;
    Handle<SharedFunctionInfo> new_sfi;
    // In most cases the new FunctionLiteral should also have an SFI, but there
    // are some exceptions. E.g the compiler doesn't create SFIs for
    // inner functions that are never referenced.
    if (!data->shared.ToHandle(&new_sfi)) continue;
    DCHECK_EQ(new_sfi->script(), *new_script);
    if (!function_data_map.Lookup(script, mapping.first, &data)) continue;
    Handle<SharedFunctionInfo> sfi;
    if (!data->shared.ToHandle(&sfi)) continue;
    isolate->debug()->DeoptimizeFunction(sfi);
    isolate->compilation_cache()->Remove(sfi);
    for (auto& js_function : data->js_functions) {
      js_function->set_raw_feedback_cell(
          *isolate->factory()->many_closures_cell());
#ifdef V8_ENABLE_LEAPTIERING
      auto code = handle(new_sfi->GetCode(isolate), isolate);
      JSFunction::AllocateDispatchHandle(
          js_function, isolate,
          new_sfi->internal_formal_parameter_count_with_receiver(), code);
#endif
      js_function->set_shared(*new_sfi);
      if (!js_function->is_compiled(isolate)) continue;
      IsCompiledScope is_compiled_scope(
          js_function->shared()->is_compiled_scope(isolate));
      JSFunction::EnsureFeedbackVector(isolate, js_function,
                                       &is_compiled_scope);
    }
  }
  SharedFunctionInfo::ScriptIterator it(isolate, *new_script);
  for (Tagged<SharedFunctionInfo> sfi = it.Next(); !sfi.is_null();
       sfi = it.Next()) {
    if (!sfi->HasBytecodeArray()) continue;
    Tagged<TrustedFixedArray> constants =
        sfi->GetBytecodeArray(isolate)->constant_pool();
    for (int i = 0; i < constants->length(); ++i) {
      if (!IsSharedFunctionInfo(constants->get(i))) continue;
      Tagged<SharedFunctionInfo> inner_sfi =
          Cast<SharedFunctionInfo>(constants->get(i));
      // See if there is a mapping from this function's start position to an
      // unchanged function's id.
      auto unchanged_it =
          start_position_to_unchanged_id.find(inner_sfi->StartPosition());
      if (unchanged_it == start_position_to_unchanged_id.end()) continue;
      // Grab that function id from the new script's SFI list, which should have
      // already been updated in in the unchanged pass.
      Tagged<SharedFunctionInfo> old_unchanged_inner_sfi =
          Cast<SharedFunctionInfo>(
              new_script->infos()->get(unchanged_it->second).GetHeapObject());
      if (old_unchanged_inner_sfi == inner_sfi) continue;
      DCHECK_NE(old_unchanged_inner_sfi, inner_sfi);
      // Now some sanity checks. Make sure that the unchanged SFI has already
      // been processed and patched to be on the new script ...
      DCHECK_EQ(old_unchanged_inner_sfi->script(), *new_script);
      constants->set(i, old_unchanged_inner_sfi);
    }
  }
#ifdef DEBUG
  {
    // Check that all the functions in the new script are valid, that their
    // function literals match what is expected, and that start positions are
    // unique.
    DisallowGarbageCollection no_gc;
    SharedFunctionInfo::ScriptIterator script_it(isolate, *new_script);
    std::set<int> start_positions;
    for (Tagged<SharedFunctionInfo> sfi = script_it.Next(); !sfi.is_null();
         sfi = script_it.Next()) {
      DCHECK_EQ(sfi->script(), *new_script);
      DCHECK_EQ(sfi->function_literal_id(kRelaxedLoad),
                script_it.CurrentIndex());
      // Don't check the start position of the top-level function, as it can
      // overlap with a function in the script.
      if (sfi->is_toplevel()) {
        DCHECK_EQ(start_positions.find(sfi->StartPosition()),
                  start_positions.end());
        start_positions.insert(sfi->StartPosition());
      }
      if (!sfi->HasBytecodeArray()) continue;
      // Check that all the functions in this function's constant pool are also
      // on the new script, and that their id matches their index in the new
      // scripts function list.
      Tagged<TrustedFixedArray> constants =
          sfi->GetBytecodeArray(isolate)->constant_pool();
      for (int i = 0; i < constants->length(); ++i) {
        if (!IsSharedFunctionInfo(constants->get(i))) continue;
        Tagged<SharedFunctionInfo> inner_sfi =
            Cast<SharedFunctionInfo>(constants->get(i));
        DCHECK_EQ(inner_sfi->script(), *new_script);
        DCHECK_EQ(inner_sfi,
                  new_script->infos()
                      ->get(inner_sfi->function_literal_id(kRelaxedLoad))
                      .GetHeapObject());
      }
    }
  }
#endif
  int script_id = script->id();
  script->set_id(new_script->id());
  new_script->set_id(script_id);
  result->status = debug::LiveEditResult::OK;
  result->script = ToApiHandle<v8::debug::Script>(new_script);
}
References v8::internal::anonymous_namespace{liveedit.cc}::CalculateFunctionLiteralChanges(), v8::internal::anonymous_namespace{liveedit.cc}::CanPatchScript(), v8::internal::Factory::CloneScript(), code, CompareStrings(), v8::internal::Isolate::compilation_cache(), v8::internal::SharedFunctionInfo::ScriptIterator::CurrentIndex(), DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::debug(), v8::internal::Debug::DeoptimizeFunction(), v8::internal::anonymous_namespace{liveedit.cc}::DetermineOuterScopeInfo(), v8::internal::JSFunction::EnsureFeedbackVector(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::UnoptimizedCompileFlags::ForScriptCompile(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::kRelaxedLoad, v8::kRelaxedStore, v8::kReleaseStore, v8::internal::Isolate::LocalsBlockListCacheRehash(), v8::internal::MakeWeak(), v8::internal::anonymous_namespace{liveedit.cc}::MapLiterals(), v8::internal::SharedFunctionInfo::ScriptIterator::Next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::debug::LiveEditResult::OK, v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8::internal::CompilationCache::Remove(), v8::internal::Debug::RemoveBreakInfoAndMaybeFree(), v8::base::internal::result, v8::internal::script, and v8::internal::anonymous_namespace{liveedit.cc}::UpdatePositions().
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::Debug::SetScriptSource().
TranslatePosition()
int v8::internal::LiveEdit::TranslatePosition (const std::vector< SourceChangeRange > & changed, int position) [static]
Definition at line 1135 of file liveedit.cc.
                                              {
  auto it = std::lower_bound(diffs.begin(), diffs.end(), position,
                             [](const SourceChangeRange& change, int position) {
                               return change.end_position < position;
                             });
  if (it != diffs.end() && position == it->end_position) {
    return it->new_end_position;
  }
  if (it == diffs.begin()) return position;
  DCHECK(it == diffs.end() || position <= it->start_position);
  it = std::prev(it);
  return position + (it->new_end_position - it->end_position);
}
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/liveedit.h
/mnt/V8SourceCode/src/debug/liveedit.cc