v8::ObjectTemplate Class Reference
An ObjectTemplate is used to create objects at runtime.
#include <v8-template.h>
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeLocal< Object > NewInstance (Local< Context > context)
Creates a new instance of this template.
void SetHandler (const NamedPropertyHandlerConfiguration &configuration)
Sets a named property handler on the object template.
void SetHandler (const IndexedPropertyHandlerConfiguration &configuration)
Sets an indexed property handler on the object template.
void SetCallAsFunctionHandler (FunctionCallback callback, Local< Value > data=Local< Value >())
Sets the callback to be used when calling instances created from this template as a function.
void MarkAsUndetectable ()
Mark object instances of the template as undetectable.
void SetAccessCheckCallback (AccessCheckCallback callback, Local< Value > data=Local< Value >())
Sets access check callback on the object template and enables access checks.
void SetAccessCheckCallbackAndHandler (AccessCheckCallback callback, const NamedPropertyHandlerConfiguration &named_handler, const IndexedPropertyHandlerConfiguration &indexed_handler, Local< Value > data=Local< Value >())
Like SetAccessCheckCallback but invokes an interceptor on failed access checks instead of looking up all-can-read properties.
int InternalFieldCount () const
Gets the number of internal fields for objects generated from this template.
void SetInternalFieldCount (int value)
Sets the number of internal fields for objects generated from this template.
bool IsImmutableProto () const
Returns true if the object will be an immutable prototype exotic object.
void SetImmutableProto ()
Makes the ObjectTemplate for an immutable prototype exotic object, with an immutable proto.
void SetCodeLike ()
Support for TC39 `dynamic code brand checks` proposal.
bool IsCodeLike () const
void SealAndPrepareForPromotionToReadOnly ()
Seal the object and mark it for promotion to read only space during context snapshot creation.
Static Public Member Functions
static Local< ObjectTemplate > New (Isolate *isolate, Local< FunctionTemplate > constructor=Local< FunctionTemplate >())
Creates an ObjectTemplate.
static ObjectTemplate * Cast (Data *data)
Private Member Functions
ObjectTemplate ()
Static Private Member Functions
static void CheckCast (Data *that)
Friends
class FunctionTemplate
Detailed Description
An ObjectTemplate is used to create objects at runtime.
Properties added to an ObjectTemplate are added to each object created from the ObjectTemplate.
Definition at line 938 of file v8-template.h.
Constructor & Destructor Documentation
ObjectTemplate()
v8::ObjectTemplate::ObjectTemplate () [private]
Member Function Documentation
Cast()
ObjectTemplate * v8::ObjectTemplate::Cast (Data * data) [inline], [static]
Definition at line 1144 of file v8-template.h.
                                               {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<ObjectTemplate*>(data);
}
References CheckCast().
CheckCast()
void v8::ObjectTemplate::CheckCast (Data * that) [static], [private]
Definition at line 7333 of file api.cc.
                                           {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsObjectTemplateInfo(*obj), "v8::ObjectTemplate::Cast",
                  "Value is not an ObjectTemplate");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
InternalFieldCount()
int v8::ObjectTemplate::InternalFieldCount () const
Gets the number of internal fields for objects generated from this template.
Definition at line 1683 of file api.cc.
                                             {
  return Utils::OpenDirectHandle(this)->embedder_field_count();
}
References v8::Utils::OpenDirectHandle().
IsCodeLike()
bool v8::ObjectTemplate::IsCodeLike () const
Definition at line 1715 of file api.cc.
                                      {
  return Utils::OpenDirectHandle(this)->code_like();
}
References v8::Utils::OpenDirectHandle().
IsImmutableProto()
bool v8::ObjectTemplate::IsImmutableProto () const
Returns true if the object will be an immutable prototype exotic object.
Definition at line 1704 of file api.cc.
                                            {
  return Utils::OpenDirectHandle(this)->immutable_proto();
}
References v8::Utils::OpenDirectHandle().
MarkAsUndetectable()
void v8::ObjectTemplate::MarkAsUndetectable ()
Mark object instances of the template as undetectable.
In many ways, undetectable objects behave as though they are not there. They behave like 'undefined' in conditionals and when printed. However, properties can be accessed and called as on normal objects.
Definition at line 1574 of file api.cc.
                                        {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto cons = EnsureConstructor(i_isolate, this);
  EnsureNotPublished(cons, "v8::ObjectTemplate::MarkAsUndetectable");
  cons->set_undetectable(true);
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), and v8::anonymous_namespace{api.cc}::EnsureNotPublished().
New()
Local< ObjectTemplate > v8::ObjectTemplate::New (Isolate * isolate, v8::Local< FunctionTemplate > constructor = Local<FunctionTemplate>()) [static]
Creates an ObjectTemplate.
Definition at line 1392 of file api.cc.
                                                                {
  auto i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_ObjectTemplate_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  constexpr bool do_not_cache = false;
  i::DirectHandle<i::ObjectTemplateInfo> obj =
      i_isolate->factory()->NewObjectTemplateInfo(
          Utils::OpenDirectHandle(*constructor, true), do_not_cache);
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewObjectTemplateInfo(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::CreateAsyncHookTemplate(), v8::Shell::CreateD8Template(), v8::CreateEnvironment(), v8::Shell::CreateGlobalTemplate(), v8::Shell::CreateOSTemplate(), v8::Shell::CreatePerformanceTemplate(), v8::Shell::CreateRealmTemplate(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), v8::NewObjectTemplate(), v8::internal::RUNTIME_FUNCTION(), and v8_inspector::V8Console::taskTemplate().
NewInstance()
MaybeLocal< v8::Object > v8::ObjectTemplate::NewInstance (Local< Context > context)
Creates a new instance of this template.
Parameters
context The context in which the instance is created.
Definition at line 7324 of file api.cc.
                                                                       {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_ObjectTemplate_NewInstance};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  return api_scope.EscapeMaybe(
      i::ApiNatives::InstantiateObject(i_isolate, self));
}
References v8::internal::ApiNatives::InstantiateObject(), and v8::Utils::OpenDirectHandle().
SealAndPrepareForPromotionToReadOnly()
void v8::ObjectTemplate::SealAndPrepareForPromotionToReadOnly ()
Seal the object and mark it for promotion to read only space during context snapshot creation.
This is an experimental feature and may still change significantly.
Definition at line 7421 of file api.cc.
                                                          {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = self->GetIsolateChecked();
  i::ObjectTemplateInfo::SealAndPrepareForPromotionToReadOnly(i_isolate, self);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::ObjectTemplateInfo::SealAndPrepareForPromotionToReadOnly().
SetAccessCheckCallback()
void v8::ObjectTemplate::SetAccessCheckCallback (AccessCheckCallback callback, Local< Value > data = Local<Value>())
Sets access check callback on the object template and enables access checks.
When accessing properties on instances of this object template, the access check callback will be called to determine whether or not to allow cross-context access to the properties.
Definition at line 1583 of file api.cc.
                                                               {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto cons = EnsureConstructor(i_isolate, this);
  EnsureNotPublished(cons, "v8::ObjectTemplate::SetAccessCheckCallback");
  i::DirectHandle<i::Struct> struct_info = i_isolate->factory()->NewStruct(
      i::ACCESS_CHECK_INFO_TYPE, i::AllocationType::kOld);
  auto info = i::Cast<i::AccessCheckInfo>(struct_info);
  SET_FIELD_WRAPPED(i_isolate, info, set_callback, callback,
                    internal::kApiAccessCheckCallbackTag);
  info->set_named_interceptor(i::Smi::zero());
  info->set_indexed_interceptor(i::Smi::zero());
  if (data.IsEmpty()) {
    data = v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
  }
  info->set_data(*Utils::OpenDirectHandle(*data));
  i::FunctionTemplateInfo::SetAccessCheckInfo(i_isolate, cons, info);
  cons->set_needs_access_check(true);
}
References v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::internal::Isolate::factory(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kApiAccessCheckCallbackTag, v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewStruct(), v8::Utils::OpenDirectHandle(), SET_FIELD_WRAPPED, v8::Undefined(), and v8::internal::Smi::zero().
SetAccessCheckCallbackAndHandler()
void v8::ObjectTemplate::SetAccessCheckCallbackAndHandler (AccessCheckCallback callback, const NamedPropertyHandlerConfiguration & named_handler, const IndexedPropertyHandlerConfiguration & indexed_handler, Local< Value > data = Local<Value>())
Like SetAccessCheckCallback but invokes an interceptor on failed access checks instead of looking up all-can-read properties.
You can only use either this method or SetAccessCheckCallback, but not both at the same time.
Definition at line 1609 of file api.cc.
                       {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto cons = EnsureConstructor(i_isolate, this);
  EnsureNotPublished(cons,
                     "v8::ObjectTemplate::SetAccessCheckCallbackWithHandler");
  i::DirectHandle<i::Struct> struct_info = i_isolate->factory()->NewStruct(
      i::ACCESS_CHECK_INFO_TYPE, i::AllocationType::kOld);
  auto info = i::Cast<i::AccessCheckInfo>(struct_info);
  SET_FIELD_WRAPPED(i_isolate, info, set_callback, callback,
                    internal::kApiAccessCheckCallbackTag);
  auto named_interceptor = CreateNamedInterceptorInfo(
      i_isolate, named_handler.getter, named_handler.setter,
      named_handler.query, named_handler.descriptor, named_handler.deleter,
      named_handler.enumerator, named_handler.definer, named_handler.data,
      named_handler.flags);
  info->set_named_interceptor(*named_interceptor);
  auto indexed_interceptor = CreateIndexedInterceptorInfo(
      i_isolate, indexed_handler.getter, indexed_handler.setter,
      indexed_handler.query, indexed_handler.descriptor,
      indexed_handler.deleter, indexed_handler.enumerator,
      indexed_handler.definer, indexed_handler.data, indexed_handler.flags);
  info->set_indexed_interceptor(*indexed_interceptor);
  if (data.IsEmpty()) {
    data = v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
  }
  info->set_data(*Utils::OpenDirectHandle(*data));
  i::FunctionTemplateInfo::SetAccessCheckInfo(i_isolate, cons, info);
  cons->set_needs_access_check(true);
}
References v8::anonymous_namespace{api.cc}::CreateIndexedInterceptorInfo(), v8::anonymous_namespace{api.cc}::CreateNamedInterceptorInfo(), v8::internal::Isolate::Current(), v8::NamedPropertyHandlerConfiguration::data, v8::IndexedPropertyHandlerConfiguration::data, v8::NamedPropertyHandlerConfiguration::definer, v8::IndexedPropertyHandlerConfiguration::definer, v8::NamedPropertyHandlerConfiguration::deleter, v8::IndexedPropertyHandlerConfiguration::deleter, v8::NamedPropertyHandlerConfiguration::descriptor, v8::IndexedPropertyHandlerConfiguration::descriptor, v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::NamedPropertyHandlerConfiguration::enumerator, v8::IndexedPropertyHandlerConfiguration::enumerator, v8::internal::Isolate::factory(), v8::NamedPropertyHandlerConfiguration::flags, v8::IndexedPropertyHandlerConfiguration::flags, v8::NamedPropertyHandlerConfiguration::getter, v8::IndexedPropertyHandlerConfiguration::getter, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kApiAccessCheckCallbackTag, v8::internal::kOld, v8::internal::FactoryBase< Impl >::NewStruct(), v8::Utils::OpenDirectHandle(), v8::NamedPropertyHandlerConfiguration::query, v8::IndexedPropertyHandlerConfiguration::query, SET_FIELD_WRAPPED, v8::NamedPropertyHandlerConfiguration::setter, v8::IndexedPropertyHandlerConfiguration::setter, and v8::Undefined().
SetCallAsFunctionHandler()
void v8::ObjectTemplate::SetCallAsFunctionHandler (FunctionCallback callback, Local< Value > data = Local<Value>())
Sets the callback to be used when calling instances created from this template as a function.
If no callback is set, instances behave like normal JavaScript objects that cannot be called as a function.
Definition at line 1663 of file api.cc.
                                                                 {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto cons = EnsureConstructor(i_isolate, this);
  EnsureNotPublished(cons, "v8::ObjectTemplate::SetCallAsFunctionHandler");
  DCHECK_NOT_NULL(callback);
  // This template is just a container for callback and data values and thus
  // it's not supposed to be instantiated. Don't cache it.
  constexpr bool do_not_cache = true;
  constexpr int length = 0;
  i::DirectHandle<i::FunctionTemplateInfo> templ =
      i_isolate->factory()->NewFunctionTemplateInfo(length, do_not_cache);
  templ->set_is_object_template_call_handler(true);
  Utils::ToLocal(templ)->SetCallHandler(callback, data);
  i::FunctionTemplateInfo::SetInstanceCallHandler(i_isolate, cons, templ);
}
References v8::internal::Isolate::Current(), DCHECK_NOT_NULL, v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::internal::Isolate::factory(), v8::internal::length, and v8::internal::Factory::NewFunctionTemplateInfo().
SetCodeLike()
void v8::ObjectTemplate::SetCodeLike ()
Support for TC39 `dynamic code brand checks` proposal.
This API allows to mark (& query) objects as `code like`, which causes them to be treated like Strings in the context of eval and function constructor.
Reference: https://github.com/tc39/proposal-dynamic-code-brand-checks
Definition at line 1719 of file api.cc.
                                 {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  self->set_code_like(true);
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
SetHandler() [1/2]
void v8::ObjectTemplate::SetHandler (const IndexedPropertyHandlerConfiguration & configuration)
Sets an indexed property handler on the object template.
Whenever an indexed property is accessed on objects created from this object template, the provided callback is invoked instead of accessing the property directly on the JavaScript object.
Parameters
configuration The IndexedPropertyHandlerConfiguration that defines the callbacks to invoke when accessing a property.
Definition at line 1649 of file api.cc.
                                                       {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  auto cons = EnsureConstructor(i_isolate, this);
  EnsureNotPublished(cons, "v8::ObjectTemplate::SetHandler");
  auto obj = CreateIndexedInterceptorInfo(
      i_isolate, config.getter, config.setter, config.query, config.descriptor,
      config.deleter, config.enumerator, config.definer, config.data,
      config.flags);
  i::FunctionTemplateInfo::SetIndexedPropertyHandler(i_isolate, cons, obj);
}
References v8::anonymous_namespace{api.cc}::CreateIndexedInterceptorInfo(), v8::internal::Isolate::Current(), v8::IndexedPropertyHandlerConfiguration::data, v8::IndexedPropertyHandlerConfiguration::definer, v8::IndexedPropertyHandlerConfiguration::deleter, v8::IndexedPropertyHandlerConfiguration::descriptor, v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::IndexedPropertyHandlerConfiguration::enumerator, v8::IndexedPropertyHandlerConfiguration::flags, v8::IndexedPropertyHandlerConfiguration::getter, v8::IndexedPropertyHandlerConfiguration::query, and v8::IndexedPropertyHandlerConfiguration::setter.
SetHandler() [2/2]
void v8::ObjectTemplate::SetHandler (const NamedPropertyHandlerConfiguration & configuration)
Sets a named property handler on the object template.
Whenever a property whose name is a string or a symbol is accessed on objects created from this object template, the provided callback is invoked instead of accessing the property directly on the JavaScript object.
Parameters
configuration The NamedPropertyHandlerConfiguration that defines the callbacks to invoke when accessing a property.
Definition at line 1566 of file api.cc.
                                                     {
  ObjectTemplateSetNamedPropertyHandler(
      this, config.getter, config.setter, config.query, config.descriptor,
      config.deleter, config.enumerator, config.definer, config.data,
      config.flags);
}
References v8::NamedPropertyHandlerConfiguration::data, v8::NamedPropertyHandlerConfiguration::definer, v8::NamedPropertyHandlerConfiguration::deleter, v8::NamedPropertyHandlerConfiguration::descriptor, v8::NamedPropertyHandlerConfiguration::enumerator, v8::NamedPropertyHandlerConfiguration::flags, v8::NamedPropertyHandlerConfiguration::getter, v8::anonymous_namespace{api.cc}::ObjectTemplateSetNamedPropertyHandler(), v8::NamedPropertyHandlerConfiguration::query, and v8::NamedPropertyHandlerConfiguration::setter.
SetImmutableProto()
void v8::ObjectTemplate::SetImmutableProto ()
Makes the ObjectTemplate for an immutable prototype exotic object, with an immutable proto.
Definition at line 1708 of file api.cc.
                                       {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  self->set_immutable_proto(true);
}
References v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
SetInternalFieldCount()
void v8::ObjectTemplate::SetInternalFieldCount (int value)
Sets the number of internal fields for objects generated from this template.
Definition at line 1687 of file api.cc.
                                                    {
  i::Isolate* i_isolate = i::Isolate::Current();
  if (!Utils::ApiCheck(i::Smi::IsValid(value),
                       "v8::ObjectTemplate::SetInternalFieldCount()",
                       "Invalid embedder field count")) {
    return;
  }
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  if (value > 0) {
    // The embedder field count is set by the constructor function's
    // construct code, so we ensure that there is a constructor
    // function to do the setting.
    EnsureConstructor(i_isolate, this);
  }
  Utils::OpenDirectHandle(this)->set_embedder_field_count(value);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::internal::Smi::IsValid(), v8::Utils::OpenDirectHandle(), and v8::internal::value.
Friends And Related Function Documentation
FunctionTemplate
friend class FunctionTemplate [friend]
Definition at line 1068 of file v8-template.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-template.h
/mnt/V8SourceCode/src/api/api.cc