v8::internal::OnHeapProducedPreparseData Class Reference
Public Member Functions
OnHeapProducedPreparseData (Handle< PreparseData > data)
Handle< PreparseData > Serialize (Isolate *isolate) final
Handle< PreparseData > Serialize (LocalIsolate *isolate) final
ZonePreparseData * Serialize (Zone *zone) final
Private Attributes
Handle< PreparseData > data_
Additional Inherited Members
Detailed Description
Definition at line 521 of file preparse-data.cc.
Constructor & Destructor Documentation
OnHeapProducedPreparseData()
v8::internal::OnHeapProducedPreparseData::OnHeapProducedPreparseData (Handle< PreparseData > data) [inline], [explicit]
Definition at line 523 of file preparse-data.cc.
      : data_(data) {}
Member Function Documentation
Serialize() [1/3]
Handle<PreparseData> v8::internal::OnHeapProducedPreparseData::Serialize (Isolate * isolate) [inline], [final], [virtual]
Implements v8::internal::ProducedPreparseData.
Definition at line 526 of file preparse-data.cc.
                                                         {
    DCHECK(!data_.is_null());
    return data_;
  }
References v8::internal::DCHECK().
Serialize() [2/3]
Handle<PreparseData> v8::internal::OnHeapProducedPreparseData::Serialize (LocalIsolate * isolate) [inline], [final], [virtual]
Implements v8::internal::ProducedPreparseData.
Definition at line 531 of file preparse-data.cc.
                                                              {
    DCHECK(!data_.is_null());
    DCHECK_IMPLIES(!isolate->is_main_thread(),
                   isolate->heap()->ContainsLocalHandle(data_.location()));
    return data_;
  }
References v8::internal::DCHECK(), and DCHECK_IMPLIES.
Serialize() [3/3]
ZonePreparseData* v8::internal::OnHeapProducedPreparseData::Serialize (Zone * zone) [inline], [final], [virtual]
Implements v8::internal::ProducedPreparseData.
Definition at line 538 of file preparse-data.cc.
                                                {
    // Not required.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Member Data Documentation
data_
Handle<PreparseData> v8::internal::OnHeapProducedPreparseData::data_ [private]
Definition at line 544 of file preparse-data.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparse-data.cc