v8::BigInt Class Reference
A JavaScript BigInt value (https://tc39.github.io/proposal-bigint)
#include <v8-primitive.h>
Public Member Functions
uint64_t Uint64Value (bool *lossless=nullptr) const
Returns the value of this BigInt as an unsigned 64-bit integer.
int64_t Int64Value (bool *lossless=nullptr) const
Returns the value of this BigInt as a signed 64-bit integer.
int WordCount () const
Returns the number of 64-bit words needed to store the result of ToWordsArray().
void ToWordsArray (int *sign_bit, int *word_count, uint64_t *words) const
Writes the contents of this BigInt to a specified memory location.
Static Public Member Functions
static Local< BigInt > New (Isolate *isolate, int64_t value)
static Local< BigInt > NewFromUnsigned (Isolate *isolate, uint64_t value)
static MaybeLocal< BigInt > NewFromWords (Local< Context > context, int sign_bit, int word_count, const uint64_t *words)
Creates a new BigInt object using a specified sign bit and a specified list of digits/words.
static BigInt * Cast (v8::Data *data)
Private Member Functions
BigInt ()
Static Private Member Functions
static void CheckCast (v8::Data *that)
Detailed Description
A JavaScript BigInt value (https://tc39.github.io/proposal-bigint)
Definition at line 923 of file v8-primitive.h.
Constructor & Destructor Documentation
BigInt()
v8::BigInt::BigInt () [private]
Member Function Documentation
Cast()
static BigInt* v8::BigInt::Cast (v8::Data * data) [inline], [static]
Definition at line 968 of file v8-primitive.h.
                                              {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<BigInt*>(data);
  }
CheckCast()
void v8::BigInt::CheckCast (v8::Data * that) [static], [private]
Definition at line 3950 of file api.cc.
                                     {
  Utils::ApiCheck(Value::Cast(that)->IsBigInt(), "v8::BigInt::Cast",
                  "Value is not a BigInt");
}
References v8::Utils::ApiCheck(), and v8::Value::Cast().
Int64Value()
int64_t v8::BigInt::Int64Value (bool * lossless = nullptr) const
Returns the value of this BigInt as a signed 64-bit integer.
If lossless is provided, it will reflect whether this BigInt was truncated or not.
Definition at line 9594 of file api.cc.
                                                 {
  return Utils::OpenDirectHandle(this)->AsInt64(lossless);
}
References v8::Utils::OpenDirectHandle().
New()
Local< BigInt > v8::BigInt::New (Isolate * isolate, int64_t value) [static]
Definition at line 9566 of file api.cc.
                                                              {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::BigInt> result = i::BigInt::FromInt64(i_isolate, value);
  return Utils::ToLocal(result);
}
References v8::internal::BigInt::FromInt64(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalGetValueCommon().
NewFromUnsigned()
Local< BigInt > v8::BigInt::NewFromUnsigned (Isolate * isolate, uint64_t value) [static]
Definition at line 9573 of file api.cc.
                                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::BigInt> result = i::BigInt::FromUint64(i_isolate, value);
  return Utils::ToLocal(result);
}
References v8::internal::BigInt::FromUint64(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::AddressValueFromUnsigned(), and v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback().
NewFromWords()
MaybeLocal< BigInt > v8::BigInt::NewFromWords (Local< Context > context, int sign_bit, int word_count, const uint64_t * words) [static]
Creates a new BigInt object using a specified sign bit and a specified list of digits/words.
The resulting number is calculated as:
(-1)^sign_bit * (words[0] * (2^64)^0 + words[1] * (2^64)^1 + ...)
Definition at line 9580 of file api.cc.
                                                                   {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptScope<InternalEscapableScope> api_scope{
      i_isolate, context, RCCId::kAPI_BigInt_NewFromWords};
  return api_scope.EscapeMaybe(
      i::BigInt::FromWords64(i_isolate, sign_bit, word_count, words));
}
References v8::internal::Isolate::Current(), and v8::internal::BigInt::FromWords64().
ToWordsArray()
void v8::BigInt::ToWordsArray (int * sign_bit, int * word_count, uint64_t * words) const
Writes the contents of this BigInt to a specified memory location.
sign_bit must be provided and will be set to 1 if this BigInt is negative. *word_count has to be initialized to the length of the words array. Upon return, it will be set to the actual number of words that would be needed to store this BigInt (i.e. the return value of WordCount()).
Definition at line 9602 of file api.cc.
                                                 {
  // TODO(saelo): consider migrating the public API to also use uint32_t or
  // size_t for length and count values.
  uint32_t unsigned_word_count = *word_count;
  Utils::OpenDirectHandle(this)->ToWordsArray64(sign_bit, &unsigned_word_count,
                                                words);
  *word_count = base::checked_cast<int>(unsigned_word_count);
}
References v8::Utils::OpenDirectHandle().
Uint64Value()
uint64_t v8::BigInt::Uint64Value (bool * lossless = nullptr) const
Returns the value of this BigInt as an unsigned 64-bit integer.
If lossless is provided, it will reflect whether the return value was truncated or wrapped around. In particular, it is set to false if this BigInt is negative.
Definition at line 9590 of file api.cc.
                                                   {
  return Utils::OpenDirectHandle(this)->AsUint64(lossless);
}
References v8::Utils::OpenDirectHandle().
WordCount()
int v8::BigInt::WordCount () const
Returns the number of 64-bit words needed to store the result of ToWordsArray().
Definition at line 9598 of file api.cc.
                            {
  return Utils::OpenDirectHandle(this)->Words64Count();
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc