v8::internal::torque::TypeArgumentInference Class Reference
#include <type-inference.h>
Public Member Functions
TypeArgumentInference (const GenericParameters &type_parameters, const TypeVector &explicit_type_arguments, const std::vector< TypeExpression * > &term_parameters, const std::vector< std::optional< const Type * >> &term_argument_types)
bool HasFailed () const
const std::string & GetFailureReason ()
TypeVector GetResult () const
void Fail (std::string reason)
Private Member Functions
void Match (TypeExpression *parameter, const Type *argument_type)
void MatchGeneric (BasicTypeExpression *parameter, const Type *argument_type)
Private Attributes
size_t num_explicit_
std::unordered_map< std::string, size_t > type_parameter_from_name_
std::vector< std::optional< const Type * > > inferred_
std::optional< std::string > failure_reason_
Detailed Description
Definition at line 54 of file type-inference.h.
Constructor & Destructor Documentation
TypeArgumentInference()
v8::internal::torque::TypeArgumentInference::TypeArgumentInference (const GenericParameters & type_parameters, const TypeVector & explicit_type_arguments, const std::vector< TypeExpression * > & term_parameters, const std::vector< std::optional< const Type * >> & term_argument_types)
Definition at line 11 of file type-inference.cc.
    : num_explicit_(explicit_type_arguments.size()),
      type_parameter_from_name_(type_parameters.size()),
      inferred_(type_parameters.size()) {
  if (num_explicit_ > type_parameters.size()) {
    Fail("more explicit type arguments than expected");
    return;
  }
  if (term_argument_types.size() > term_parameters.size()) {
    Fail("more arguments than expected");
    return;
  }
  for (size_t i = 0; i < type_parameters.size(); i++) {
    type_parameter_from_name_[type_parameters[i].name->value] = i;
  }
  for (size_t i = 0; i < num_explicit_; i++) {
    inferred_[i] = {explicit_type_arguments[i]};
  }
  for (size_t i = 0; i < term_argument_types.size(); i++) {
    if (term_argument_types[i])
      Match(term_parameters[i], *term_argument_types[i]);
    if (HasFailed()) return;
  }
  for (size_t i = 0; i < type_parameters.size(); i++) {
    if (!inferred_[i]) {
      Fail("failed to infer arguments for all type parameters");
      return;
    }
  }
}
References Fail(), HasFailed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, inferred_, Match(), num_explicit_, and type_parameter_from_name_.
Member Function Documentation
Fail()
void v8::internal::torque::TypeArgumentInference::Fail (std::string reason) [inline]
Definition at line 65 of file type-inference.h.
{ failure_reason_ = {reason}; }
References failure_reason_.
Referenced by v8::internal::torque::GenericCallable::InferSpecializationTypes(), Match(), MatchGeneric(), and TypeArgumentInference().
GetFailureReason()
const std::string& v8::internal::torque::TypeArgumentInference::GetFailureReason () [inline]
Definition at line 63 of file type-inference.h.
{ return *failure_reason_; }
References failure_reason_.
Referenced by v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), and v8::internal::torque::ImplementationVisitor::LookupCallable().
GetResult()
TypeVector v8::internal::torque::TypeArgumentInference::GetResult () const
Definition at line 49 of file type-inference.cc.
                                                  {
  CHECK(!HasFailed());
  TypeVector result(inferred_.size());
  std::transform(
      inferred_.begin(), inferred_.end(), result.begin(),
      [](std::optional<const Type*> maybe_type) { return *maybe_type; });
  return result;
}
References CHECK, HasFailed(), inferred_, and v8::base::internal::result.
Referenced by v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), v8::internal::torque::GenericCallable::InferSpecializationTypes(), and v8::internal::torque::ImplementationVisitor::LookupCallable().
HasFailed()
bool v8::internal::torque::TypeArgumentInference::HasFailed () const [inline]
Definition at line 62 of file type-inference.h.
{ return failure_reason_.has_value(); }
References failure_reason_.
Referenced by v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), GetResult(), v8::internal::torque::GenericCallable::InferSpecializationTypes(), v8::internal::torque::ImplementationVisitor::LookupCallable(), MatchGeneric(), TypeArgumentInference(), and v8::internal::torque::DeclarationVisitor::Visit().
Match()
void v8::internal::torque::TypeArgumentInference::Match (TypeExpression * parameter, const Type * argument_type) [private]
Definition at line 58 of file type-inference.cc.
                                                             {
  if (BasicTypeExpression* basic =
          BasicTypeExpression::DynamicCast(parameter)) {
    // If the parameter is referring to one of the type parameters, substitute
    if (basic->namespace_qualification.empty() && !basic->is_constexpr) {
      auto result = type_parameter_from_name_.find(basic->name->value);
      if (result != type_parameter_from_name_.end()) {
        size_t type_parameter_index = result->second;
        if (type_parameter_index < num_explicit_) {
          return;
        }
        std::optional<const Type*>& maybe_inferred =
            inferred_[type_parameter_index];
        if (maybe_inferred && *maybe_inferred != argument_type) {
          Fail("found conflicting types for generic parameter");
        } else {
          inferred_[type_parameter_index] = {argument_type};
        }
        return;
      }
    }
    // Try to recurse in case of generic types
    if (!basic->generic_arguments.empty()) {
      MatchGeneric(basic, argument_type);
    }
    // NOTE: We could also check whether ground parameter types match the
    // argument types, but we are only interested in inferring type arguments
    // here
  } else {
    // TODO(gsps): Perform inference on function and union types
  }
}
References Fail(), inferred_, MatchGeneric(), num_explicit_, v8::base::internal::result, and type_parameter_from_name_.
Referenced by MatchGeneric(), and TypeArgumentInference().
MatchGeneric()
void v8::internal::torque::TypeArgumentInference::MatchGeneric (BasicTypeExpression * parameter, const Type * argument_type) [private]
Definition at line 92 of file type-inference.cc.
                                                                    {
  QualifiedName qualified_name{parameter->namespace_qualification,
                               parameter->name->value};
  GenericType* generic_type =
      Declarations::LookupUniqueGenericType(qualified_name);
  auto& specialized_from = argument_type->GetSpecializedFrom();
  if (!specialized_from || specialized_from->generic != generic_type) {
    return Fail("found conflicting generic type constructors");
  }
  auto& parameters = parameter->generic_arguments;
  auto& argument_types = specialized_from->specialized_types;
  if (parameters.size() != argument_types.size()) {
    Error(
        "cannot infer types from generic-struct-typed parameter with "
        "incompatible number of arguments")
        .Position(parameter->pos)
        .Throw();
  }
  for (size_t i = 0; i < parameters.size(); i++) {
    Match(parameters[i], argument_types[i]);
    if (HasFailed()) return;
  }
}
References v8::internal::torque::Error(), Fail(), v8::internal::torque::BasicTypeExpression::generic_arguments, v8::internal::torque::Type::GetSpecializedFrom(), HasFailed(), v8::internal::torque::Declarations::LookupUniqueGenericType(), Match(), v8::internal::torque::BasicTypeExpression::name, v8::internal::torque::BasicTypeExpression::namespace_qualification, v8::internal::torque::AstNode::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::MessageBuilder::Throw(), and v8::internal::torque::Identifier::value.
Referenced by Match().
Member Data Documentation
failure_reason_
std::optional<std::string> v8::internal::torque::TypeArgumentInference::failure_reason_ [private]
Definition at line 74 of file type-inference.h.
Referenced by Fail(), GetFailureReason(), and HasFailed().
inferred_
std::vector<std::optional<const Type*> > v8::internal::torque::TypeArgumentInference::inferred_ [private]
Definition at line 73 of file type-inference.h.
Referenced by GetResult(), Match(), and TypeArgumentInference().
num_explicit_
size_t v8::internal::torque::TypeArgumentInference::num_explicit_ [private]
Definition at line 71 of file type-inference.h.
Referenced by Match(), and TypeArgumentInference().
type_parameter_from_name_
std::unordered_map<std::string, size_t> v8::internal::torque::TypeArgumentInference::type_parameter_from_name_ [private]
Definition at line 72 of file type-inference.h.
Referenced by Match(), and TypeArgumentInference().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/type-inference.h
/mnt/V8SourceCode/src/torque/type-inference.cc