v8::internal::FreeListManyCachedFastPathBase Class Reference
#include <free-list.h>
Public Types
enum class SmallBlocksMode { kAllow
, kProhibit
 }
Public Member Functions
FreeListManyCachedFastPathBase (SmallBlocksMode small_blocks_mode)
V8_WARN_UNUSED_RESULT Tagged< FreeSpace > Allocate (size_t size_in_bytes, size_t *node_size, AllocationOrigin origin) override
Protected Member Functions
FreeListCategoryType SelectFastAllocationFreeListCategoryType (size_t size_in_bytes)
Static Protected Attributes
static const FreeListCategoryType kFastPathFirstCategory = 18
static const size_t kFastPathStart = 2048
static const size_t kTinyObjectMaxSize = 128
static const size_t kFastPathOffset = kFastPathStart - kTinyObjectMaxSize
static const FreeListCategoryType kFastPathFallBackTiny = 15
Private Member Functions
FRIEND_TEST (SpacesTest, FreeListManyCachedFastPathSelectFastAllocationFreeListCategoryType)
Private Attributes
SmallBlocksMode small_blocks_mode_
Additional Inherited Members
Detailed Description
Definition at line 434 of file free-list.h.
Member Enumeration Documentation
SmallBlocksMode
enum v8::internal::FreeListManyCachedFastPathBase::SmallBlocksMode [strong]
Enumerator
kAllow
kProhibit
Definition at line 437 of file free-list.h.
{ kAllow, kProhibit };
Constructor & Destructor Documentation
FreeListManyCachedFastPathBase()
v8::internal::FreeListManyCachedFastPathBase::FreeListManyCachedFastPathBase (SmallBlocksMode small_blocks_mode) [inline], [explicit]
Definition at line 439 of file free-list.h.
      : small_blocks_mode_(small_blocks_mode) {
    if (small_blocks_mode_ == SmallBlocksMode::kProhibit) {
      min_block_size_ =
          (v8_flags.minor_ms && (v8_flags.minor_ms_min_lab_size_kb > 0))
              ? (v8_flags.minor_ms_min_lab_size_kb * KB)
              : kFastPathStart;
    }
  }
References v8::internal::KB, and v8::internal::v8_flags.
Member Function Documentation
Allocate()
Tagged< FreeSpace > v8::internal::FreeListManyCachedFastPathBase::Allocate (size_t size_in_bytes, size_t * node_size, AllocationOrigin origin) [override], [virtual]
Reimplemented from v8::internal::FreeListManyCached.
Reimplemented in v8::internal::FreeListManyCachedOrigin.
Definition at line 363 of file free-list.cc.
                                                                      {
  USE(origin);
  DCHECK_GE(kMaxBlockSize, size_in_bytes);
  Tagged<FreeSpace> node;
  // Fast path part 1: searching the last categories
  FreeListCategoryType first_category =
      SelectFastAllocationFreeListCategoryType(size_in_bytes);
  FreeListCategoryType type = first_category;
  for (type = next_nonempty_category[type]; type <= last_category_;
       type = next_nonempty_category[type + 1]) {
    node = TryFindNodeIn(type, size_in_bytes, node_size);
    if (!node.is_null()) break;
  }
  // Fast path part 2: searching the medium categories for tiny objects
  if (small_blocks_mode_ == SmallBlocksMode::kAllow) {
    if (node.is_null()) {
      if (size_in_bytes <= kTinyObjectMaxSize) {
        DCHECK_EQ(kFastPathFirstCategory, first_category);
        for (type = next_nonempty_category[kFastPathFallBackTiny];
             type < kFastPathFirstCategory;
             type = next_nonempty_category[type + 1]) {
          node = TryFindNodeIn(type, size_in_bytes, node_size);
          if (!node.is_null()) break;
        }
        first_category = kFastPathFallBackTiny;
      }
    }
  }
  // Searching the last category
  if (node.is_null()) {
    // Searching each element of the last category.
    type = last_category_;
    node = SearchForNodeInList(type, size_in_bytes, node_size);
  }
  // Finally, search the most precise category
  if (node.is_null()) {
    type = SelectFreeListCategoryType(size_in_bytes);
    for (type = next_nonempty_category[type]; type < first_category;
         type = next_nonempty_category[type + 1]) {
      node = TryFindNodeIn(type, size_in_bytes, node_size);
      if (!node.is_null()) break;
    }
  }
  if (!node.is_null()) {
    if (categories_[type] == nullptr) UpdateCacheAfterRemoval(type);
    PageMetadata::FromHeapObject(node)->IncreaseAllocatedBytes(*node_size);
  }
#ifdef DEBUG
  CheckCacheIntegrity();
#endif
  VerifyAvailable();
  return node;
}
References v8::internal::FreeList::categories_, DCHECK_EQ, DCHECK_GE, v8::internal::PageMetadata::FromHeapObject(), v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes(), v8::internal::Tagged< HeapObject >::is_null(), kAllow, kFastPathFallBackTiny, kFastPathFirstCategory, v8::internal::FreeListMany::kMaxBlockSize, kTinyObjectMaxSize, v8::internal::FreeList::last_category_, v8::internal::FreeListManyCached::next_nonempty_category, v8::internal::FreeList::SearchForNodeInList(), SelectFastAllocationFreeListCategoryType(), v8::internal::FreeListMany::SelectFreeListCategoryType(), small_blocks_mode_, v8::internal::FreeList::TryFindNodeIn(), v8::internal::tracing::type, v8::internal::FreeListManyCached::UpdateCacheAfterRemoval(), USE, and v8::internal::FreeList::VerifyAvailable().
Referenced by v8::internal::FreeListManyCachedOrigin::Allocate().
FRIEND_TEST()
v8::internal::FreeListManyCachedFastPathBase::FRIEND_TEST (SpacesTest , FreeListManyCachedFastPathSelectFastAllocationFreeListCategoryType) [private]
SelectFastAllocationFreeListCategoryType()
FreeListCategoryType v8::internal::FreeListManyCachedFastPathBase::SelectFastAllocationFreeListCategoryType (size_t size_in_bytes) [inline], [protected]
Definition at line 466 of file free-list.h.
                            {
    DCHECK(size_in_bytes < kMaxBlockSize);
    if (size_in_bytes >= categories_min[last_category_]) return last_category_;
    size_in_bytes += kFastPathOffset;
    for (int cat = kFastPathFirstCategory; cat < last_category_; cat++) {
      if (size_in_bytes <= categories_min[cat]) {
        return cat;
      }
    }
    return last_category_;
  }
References v8::internal::DCHECK().
Referenced by Allocate().
Member Data Documentation
kFastPathFallBackTiny
const FreeListCategoryType v8::internal::FreeListManyCachedFastPathBase::kFastPathFallBackTiny = 15 [static], [protected]
Definition at line 460 of file free-list.h.
Referenced by Allocate().
kFastPathFirstCategory
const FreeListCategoryType v8::internal::FreeListManyCachedFastPathBase::kFastPathFirstCategory = 18 [static], [protected]
Definition at line 455 of file free-list.h.
Referenced by Allocate().
kFastPathOffset
const size_t v8::internal::FreeListManyCachedFastPathBase::kFastPathOffset = kFastPathStart - kTinyObjectMaxSize [static], [protected]
Definition at line 458 of file free-list.h.
kFastPathStart
const size_t v8::internal::FreeListManyCachedFastPathBase::kFastPathStart = 2048 [static], [protected]
Definition at line 456 of file free-list.h.
kTinyObjectMaxSize
const size_t v8::internal::FreeListManyCachedFastPathBase::kTinyObjectMaxSize = 128 [static], [protected]
Definition at line 457 of file free-list.h.
Referenced by Allocate().
small_blocks_mode_
SmallBlocksMode v8::internal::FreeListManyCachedFastPathBase::small_blocks_mode_ [private]
Definition at line 482 of file free-list.h.
Referenced by Allocate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/free-list.h
/mnt/V8SourceCode/src/heap/free-list.cc