v8::internal::DeoptimizationData Class Reference
#include <deoptimization-data.h>
Public Types
using SharedFunctionInfoWrapperOrSmi = UnionOf< Smi, SharedFunctionInfoWrapper >
Public Member Functions
DECL_ELEMENT_ACCESSORS (FrameTranslation, Tagged< DeoptimizationFrameTranslation >) DECL_ELEMENT_ACCESSORS(ProtectedLiteralArray
Tagged< ProtectedDeoptimizationLiteralArray > DECL_ELEMENT_ACCESSORS (WrappedSharedFunctionInfo, Tagged< SharedFunctionInfoWrapperOrSmi >) DECL_ELEMENT_ACCESSORS(InliningPositions
Tagged< ProtectedDeoptimizationLiteralArray > Tagged< TrustedPodArray< InliningPosition > > Tagged< SharedFunctionInfo > GetSharedFunctionInfo () const
BytecodeOffset GetBytecodeOffsetOrBuiltinContinuationId (int i) const
void SetBytecodeOffset (int i, BytecodeOffset value)
int DeoptCount () const
Tagged< SharedFunctionInfo > GetInlinedFunction (int index)
Static Public Member Functions
static Handle< DeoptimizationData > New (Isolate *isolate, int deopt_entry_count)
static Handle< DeoptimizationData > New (LocalIsolate *isolate, int deopt_entry_count)
static V8_EXPORT_PRIVATE Handle< DeoptimizationData > Empty (Isolate *isolate)
static V8_EXPORT_PRIVATE Handle< DeoptimizationData > Empty (LocalIsolate *isolate)
Static Public Attributes
static const int kFrameTranslationIndex = 0
static const int kInlinedFunctionCountIndex = 1
static const int kProtectedLiteralArrayIndex = 2
static const int kLiteralArrayIndex = 3
static const int kOsrBytecodeOffsetIndex = 4
static const int kOsrPcOffsetIndex = 5
static const int kOptimizationIdIndex = 6
static const int kWrappedSharedFunctionInfoIndex = 7
static const int kInliningPositionsIndex = 8
static const int kDeoptExitStartIndex = 9
static const int kEagerDeoptCountIndex = 10
static const int kLazyDeoptCountIndex = 11
static const int kFirstDeoptEntryIndex = 12
static const int kBytecodeOffsetRawOffset = 0
static const int kTranslationIndexOffset = 1
static const int kPcOffset = 2
static const int kDeoptEntrySize = 3
static const int kNotInlinedIndex = -1
Static Private Member Functions
static int IndexForEntry (int i)
static int LengthFor (int entry_count)
Additional Inherited Members
Detailed Description
Definition at line 262 of file deoptimization-data.h.
Member Typedef Documentation
SharedFunctionInfoWrapperOrSmi
using v8::internal::DeoptimizationData::SharedFunctionInfoWrapperOrSmi = UnionOf<Smi, SharedFunctionInfoWrapper>
Definition at line 264 of file deoptimization-data.h.
Member Function Documentation
DECL_ELEMENT_ACCESSORS() [1/2]
v8::internal::DeoptimizationData::DECL_ELEMENT_ACCESSORS (FrameTranslation , Tagged< DeoptimizationFrameTranslation >)
DECL_ELEMENT_ACCESSORS() [2/2]
Tagged<ProtectedDeoptimizationLiteralArray> v8::internal::DeoptimizationData::DECL_ELEMENT_ACCESSORS (WrappedSharedFunctionInfo , Tagged< SharedFunctionInfoWrapperOrSmi >)
DeoptCount()
int v8::internal::DeoptimizationData::DeoptCount () const [inline]
Definition at line 58 of file deoptimization-data-inl.h.
                                         {
  return (length() - kFirstDeoptEntryIndex) / kDeoptEntrySize;
}
References kDeoptEntrySize, kFirstDeoptEntryIndex, and v8::internal::length.
Empty() [1/2]
Handle< DeoptimizationData > v8::internal::DeoptimizationData::Empty (Isolate * isolate) [static]
Definition at line 65 of file deoptimization-data.cc.
                                                                     {
  return Cast<DeoptimizationData>(
      isolate->factory()->empty_protected_fixed_array());
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
Empty() [2/2]
Handle< DeoptimizationData > v8::internal::DeoptimizationData::Empty (LocalIsolate * isolate) [static]
Definition at line 70 of file deoptimization-data.cc.
                                                                          {
  return Cast<DeoptimizationData>(
      isolate->factory()->empty_protected_fixed_array());
}
References v8::internal::LocalIsolate::factory().
GetBytecodeOffsetOrBuiltinContinuationId()
BytecodeOffset v8::internal::DeoptimizationData::GetBytecodeOffsetOrBuiltinContinuationId (int i) const [inline]
GetInlinedFunction()
Tagged< SharedFunctionInfo > v8::internal::DeoptimizationData::GetInlinedFunction (int index)
Definition at line 75 of file deoptimization-data.cc.
                                                                           {
  if (index == -1) {
    return GetSharedFunctionInfo();
  } else {
    return Cast<i::SharedFunctionInfo>(LiteralArray()->get(index));
  }
}
References v8::internal::TaggedArrayBase< ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout >::get(), GetSharedFunctionInfo(), and v8::internal::index.
GetSharedFunctionInfo()
Tagged<ProtectedDeoptimizationLiteralArray> Tagged<TrustedPodArray<InliningPosition> > Tagged<SharedFunctionInfo> v8::internal::DeoptimizationData::GetSharedFunctionInfo () const [inline]
Referenced by GetInlinedFunction().
IndexForEntry()
static int v8::internal::DeoptimizationData::IndexForEntry (int i) [inline], [static], [private]
Definition at line 369 of file deoptimization-data.h.
                                  {
    return kFirstDeoptEntryIndex + (i * kDeoptEntrySize);
  }
References kDeoptEntrySize, and kFirstDeoptEntryIndex.
Referenced by LengthFor().
LengthFor()
static int v8::internal::DeoptimizationData::LengthFor (int entry_count) [inline], [static], [private]
Definition at line 373 of file deoptimization-data.h.
{ return IndexForEntry(entry_count); }
References IndexForEntry().
Referenced by New().
New() [1/2]
Handle< DeoptimizationData > v8::internal::DeoptimizationData::New (Isolate * isolate, int deopt_entry_count) [static]
Definition at line 53 of file deoptimization-data.cc.
                                                                          {
  return Cast<DeoptimizationData>(
      isolate->factory()->NewProtectedFixedArray(LengthFor(deopt_entry_count)));
}
References v8::internal::Isolate::factory(), LengthFor(), and v8::internal::FactoryBase< Impl >::NewProtectedFixedArray().
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
New() [2/2]
Handle< DeoptimizationData > v8::internal::DeoptimizationData::New (LocalIsolate * isolate, int deopt_entry_count) [static]
Definition at line 59 of file deoptimization-data.cc.
                                                                          {
  return Cast<DeoptimizationData>(
      isolate->factory()->NewProtectedFixedArray(LengthFor(deopt_entry_count)));
}
References v8::internal::LocalIsolate::factory(), LengthFor(), and v8::internal::FactoryBase< Impl >::NewProtectedFixedArray().
SetBytecodeOffset()
void v8::internal::DeoptimizationData::SetBytecodeOffset (int i, BytecodeOffset value) [inline]
Member Data Documentation
kBytecodeOffsetRawOffset
const int v8::internal::DeoptimizationData::kBytecodeOffsetRawOffset = 0 [static]
Definition at line 283 of file deoptimization-data.h.
kDeoptEntrySize
const int v8::internal::DeoptimizationData::kDeoptEntrySize = 3 [static]
Definition at line 290 of file deoptimization-data.h.
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE(), DeoptCount(), and IndexForEntry().
kDeoptExitStartIndex
const int v8::internal::DeoptimizationData::kDeoptExitStartIndex = 9 [static]
Definition at line 277 of file deoptimization-data.h.
kEagerDeoptCountIndex
const int v8::internal::DeoptimizationData::kEagerDeoptCountIndex = 10 [static]
Definition at line 278 of file deoptimization-data.h.
kFirstDeoptEntryIndex
const int v8::internal::DeoptimizationData::kFirstDeoptEntryIndex = 12 [static]
Definition at line 280 of file deoptimization-data.h.
Referenced by v8::internal::DEF_HEAP_OBJECT_PREDICATE(), DeoptCount(), and IndexForEntry().
kFrameTranslationIndex
const int v8::internal::DeoptimizationData::kFrameTranslationIndex = 0 [static]
Definition at line 268 of file deoptimization-data.h.
kInlinedFunctionCountIndex
const int v8::internal::DeoptimizationData::kInlinedFunctionCountIndex = 1 [static]
Definition at line 269 of file deoptimization-data.h.
kInliningPositionsIndex
const int v8::internal::DeoptimizationData::kInliningPositionsIndex = 8 [static]
Definition at line 276 of file deoptimization-data.h.
kLazyDeoptCountIndex
const int v8::internal::DeoptimizationData::kLazyDeoptCountIndex = 11 [static]
Definition at line 279 of file deoptimization-data.h.
kLiteralArrayIndex
const int v8::internal::DeoptimizationData::kLiteralArrayIndex = 3 [static]
Definition at line 271 of file deoptimization-data.h.
kNotInlinedIndex
const int v8::internal::DeoptimizationData::kNotInlinedIndex = -1 [static]
Definition at line 344 of file deoptimization-data.h.
Referenced by v8::internal::OptimizedCompilationInfo::InlinedFunctionHolder::InlinedFunctionHolder().
kOptimizationIdIndex
const int v8::internal::DeoptimizationData::kOptimizationIdIndex = 6 [static]
Definition at line 274 of file deoptimization-data.h.
kOsrBytecodeOffsetIndex
const int v8::internal::DeoptimizationData::kOsrBytecodeOffsetIndex = 4 [static]
Definition at line 272 of file deoptimization-data.h.
kOsrPcOffsetIndex
const int v8::internal::DeoptimizationData::kOsrPcOffsetIndex = 5 [static]
Definition at line 273 of file deoptimization-data.h.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement().
kPcOffset
const int v8::internal::DeoptimizationData::kPcOffset = 2 [static]
Definition at line 285 of file deoptimization-data.h.
kProtectedLiteralArrayIndex
const int v8::internal::DeoptimizationData::kProtectedLiteralArrayIndex = 2 [static]
Definition at line 270 of file deoptimization-data.h.
kTranslationIndexOffset
const int v8::internal::DeoptimizationData::kTranslationIndexOffset = 1 [static]
Definition at line 284 of file deoptimization-data.h.
kWrappedSharedFunctionInfoIndex
const int v8::internal::DeoptimizationData::kWrappedSharedFunctionInfoIndex = 7 [static]
Definition at line 275 of file deoptimization-data.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/deoptimization-data.h
/mnt/V8SourceCode/src/objects/deoptimization-data-inl.h
/mnt/V8SourceCode/src/objects/deoptimization-data.cc