v8::internal::StressScavengeObserver Class Reference
#include <stress-scavenge-observer.h>
Public Member Functions
StressScavengeObserver (Heap *heap)
void Step (int bytes_allocated, Address soon_object, size_t size) override
bool HasRequestedGC () const
void RequestedGCDone ()
double MaxNewSpaceSizeReached () const
Private Member Functions
int NextLimit (int min=0)
Private Attributes
Heap * heap_
int limit_percentage_
bool has_requested_gc_
double max_new_space_size_reached_
Additional Inherited Members
Detailed Description
Definition at line 13 of file stress-scavenge-observer.h.
Constructor & Destructor Documentation
StressScavengeObserver()
v8::internal::StressScavengeObserver::StressScavengeObserver (Heap * heap) [explicit]
Definition at line 16 of file stress-scavenge-observer.cc.
    : AllocationObserver(64),
      heap_(heap),
      has_requested_gc_(false),
      max_new_space_size_reached_(0.0) {
  limit_percentage_ = NextLimit();
  if (v8_flags.trace_stress_scavenge && !v8_flags.fuzzer_gc_analysis) {
    heap_->isolate()->PrintWithTimestamp(
        "[StressScavenge] %d%% is the new limit\n", limit_percentage_);
  }
}
References heap_, v8::internal::Heap::isolate(), limit_percentage_, NextLimit(), and v8::internal::v8_flags.
Member Function Documentation
HasRequestedGC()
bool v8::internal::StressScavengeObserver::HasRequestedGC () const
Definition at line 60 of file stress-scavenge-observer.cc.
                                                  {
  return has_requested_gc_;
}
References has_requested_gc_.
Referenced by v8::internal::Heap::HandleGCRequest().
MaxNewSpaceSizeReached()
double v8::internal::StressScavengeObserver::MaxNewSpaceSizeReached () const
Definition at line 83 of file stress-scavenge-observer.cc.
                                                            {
  return max_new_space_size_reached_;
}
References max_new_space_size_reached_.
Referenced by v8::internal::Heap::PrintMaxNewSpaceSizeReached().
NextLimit()
int v8::internal::StressScavengeObserver::NextLimit (int min = 0) [private]
Definition at line 87 of file stress-scavenge-observer.cc.
                                             {
  int max = v8_flags.stress_scavenge;
  if (min >= max) {
    return max;
  }
  return min + heap_->isolate()->fuzzer_rng()->NextInt(max - min + 1);
}
References v8::internal::Isolate::fuzzer_rng(), heap_, v8::internal::Heap::isolate(), v8::base::RandomNumberGenerator::NextInt(), and v8::internal::v8_flags.
Referenced by RequestedGCDone(), and StressScavengeObserver().
RequestedGCDone()
void v8::internal::StressScavengeObserver::RequestedGCDone ()
Definition at line 64 of file stress-scavenge-observer.cc.
                                             {
  size_t new_space_size = heap_->new_space()->Size();
  double current_percent =
      new_space_size
          ? new_space_size * 100.0 / heap_->new_space()->TotalCapacity()
          : 0;
  limit_percentage_ = NextLimit(static_cast<int>(current_percent));
  if (v8_flags.trace_stress_scavenge) {
    heap_->isolate()->PrintWithTimestamp(
        "[Scavenge] %.2lf%% of the new space capacity reached\n",
        current_percent);
    heap_->isolate()->PrintWithTimestamp("[Scavenge] %d%% is the new limit\n",
                                         limit_percentage_);
  }
  has_requested_gc_ = false;
}
References has_requested_gc_, heap_, v8::internal::Heap::isolate(), limit_percentage_, v8::internal::Heap::new_space(), NextLimit(), v8::internal::NewSpace::TotalCapacity(), and v8::internal::v8_flags.
Referenced by v8::internal::Heap::HandleGCRequest().
Step()
void v8::internal::StressScavengeObserver::Step (int bytes_allocated, Address soon_object, size_t size) [override], [virtual]
Implements v8::internal::AllocationObserver.
Definition at line 29 of file stress-scavenge-observer.cc.
                                               {
  if (has_requested_gc_ || heap_->new_space()->Capacity() == 0) {
    return;
  }
  double current_percent =
      heap_->new_space()->Size() * 100.0 / heap_->new_space()->TotalCapacity();
  if (v8_flags.trace_stress_scavenge) {
    heap_->isolate()->PrintWithTimestamp(
        "[Scavenge] %.2lf%% of the new space capacity reached\n",
        current_percent);
  }
  if (v8_flags.fuzzer_gc_analysis) {
    max_new_space_size_reached_ =
        std::max(max_new_space_size_reached_, current_percent);
    return;
  }
  if (static_cast<int>(current_percent) >= limit_percentage_) {
    if (v8_flags.trace_stress_scavenge) {
      heap_->isolate()->PrintWithTimestamp("[Scavenge] GC requested\n");
    }
    has_requested_gc_ = true;
    heap_->isolate()->stack_guard()->RequestGC();
  }
}
References v8::internal::NewSpace::Capacity(), has_requested_gc_, heap_, v8::internal::Heap::isolate(), limit_percentage_, max_new_space_size_reached_, v8::internal::Heap::new_space(), v8::internal::Isolate::stack_guard(), v8::internal::NewSpace::TotalCapacity(), and v8::internal::v8_flags.
Member Data Documentation
has_requested_gc_
bool v8::internal::StressScavengeObserver::has_requested_gc_ [private]
Definition at line 29 of file stress-scavenge-observer.h.
Referenced by HasRequestedGC(), RequestedGCDone(), and Step().
heap_
Heap* v8::internal::StressScavengeObserver::heap_ [private]
Definition at line 27 of file stress-scavenge-observer.h.
Referenced by NextLimit(), RequestedGCDone(), Step(), and StressScavengeObserver().
limit_percentage_
int v8::internal::StressScavengeObserver::limit_percentage_ [private]
Definition at line 28 of file stress-scavenge-observer.h.
Referenced by RequestedGCDone(), Step(), and StressScavengeObserver().
max_new_space_size_reached_
double v8::internal::StressScavengeObserver::max_new_space_size_reached_ [private]
Definition at line 31 of file stress-scavenge-observer.h.
Referenced by MaxNewSpaceSizeReached(), and Step().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/stress-scavenge-observer.h
/mnt/V8SourceCode/src/heap/stress-scavenge-observer.cc