v8::internal::AstStringConstants Class Reference
#include <ast-value-factory.h>
Public Member Functions
AstStringConstants (Isolate *isolate, uint64_t hash_seed)
AstStringConstants (const AstStringConstants &)=delete
AstStringConstants & operator= (const AstStringConstants &)=delete
uint64_t hash_seed () const
const AstRawStringMap * string_table () const
const AstRawString * one_character_string (int c) const
Static Public Attributes
static constexpr int kMaxOneCharStringValue
Private Attributes
Zone zone_
AstRawStringMap string_table_
uint64_t hash_seed_
Detailed Description
Definition at line 295 of file ast-value-factory.h.
Constructor & Destructor Documentation
AstStringConstants() [1/2]
v8::internal::AstStringConstants::AstStringConstants (Isolate * isolate, uint64_t hash_seed)
Definition at line 295 of file ast-value-factory.cc.
    : zone_(isolate->allocator(), ZONE_NAME),
      string_table_(),
      hash_seed_(hash_seed) {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
#define F(name, str) \
  { \
    static const char data[] = str; \
    base::Vector<const uint8_t> literal(\
        reinterpret_cast<const uint8_t*>(data), \
        static_cast<int>(arraysize(data) - 1)); \
    IndirectHandle<String> handle = isolate->factory()->name(); \
    uint32_t raw_hash_field = handle->raw_hash_field(); \
    DCHECK_EQ(raw_hash_field, \
              StringHasher::HashSequentialString<uint8_t>(\
                  literal.begin(), literal.length(), hash_seed_)); \
    DCHECK_EQ(literal.length(), handle->length()); \
    name##_ = zone_.New<AstRawString>(true, literal, raw_hash_field); \
    /* The Handle returned by the factory is located on the roots */ \
    /* array, not on the temporary HandleScope, so this is safe. */ \
    name##_->set_string(handle); \
    string_table_.InsertNew(name##_, name##_->Hash()); \
  }
  AST_STRING_CONSTANTS(F)
#undef F
}
References AST_STRING_CONSTANTS, v8::internal::ThreadId::Current(), DCHECK_EQ, v8::internal::F, and v8::internal::Isolate::thread_id().
AstStringConstants() [2/2]
v8::internal::AstStringConstants::AstStringConstants (const AstStringConstants &) [delete]
Member Function Documentation
hash_seed()
uint64_t v8::internal::AstStringConstants::hash_seed () const [inline]
Definition at line 311 of file ast-value-factory.h.
{ return hash_seed_; }
References hash_seed_.
Referenced by v8::internal::AstValueFactory::AstValueFactory().
one_character_string()
const AstRawString* v8::internal::AstStringConstants::one_character_string (int c) const [inline]
Definition at line 313 of file ast-value-factory.h.
                                                        {
    DCHECK_GE(c, 0);
    DCHECK_LT(c, kMaxOneCharStringValue);
    // Make sure we can access the one character strings via an offset
    // from ascii_nul_string_.
#define F(name, str) \
  static_assert(offsetof(AstStringConstants, name##_) == \
                offsetof(AstStringConstants, ascii_nul_string_) + \
                    str[0] * sizeof(AstRawString*));
    SINGLE_CHARACTER_ASCII_AST_STRING_CONSTANTS(F)
#undef F
    return (&ascii_nul_string_)[c];
  }
References DCHECK_GE, DCHECK_LT, v8::internal::F, kMaxOneCharStringValue, and SINGLE_CHARACTER_ASCII_AST_STRING_CONSTANTS.
Referenced by v8::internal::AstValueFactory::GetOneByteStringInternal().
operator=()
AstStringConstants& v8::internal::AstStringConstants::operator= (const AstStringConstants &) [delete]
string_table()
const AstRawStringMap* v8::internal::AstStringConstants::string_table () const [inline]
Definition at line 312 of file ast-value-factory.h.
{ return &string_table_; }
References string_table_.
Member Data Documentation
hash_seed_
uint64_t v8::internal::AstStringConstants::hash_seed_ [private]
Definition at line 332 of file ast-value-factory.h.
Referenced by hash_seed().
kMaxOneCharStringValue
constexpr int v8::internal::AstStringConstants::kMaxOneCharStringValue [static], [constexpr]
Initial value:
=
      0 SINGLE_CHARACTER_ASCII_AST_STRING_CONSTANTS(F)
Definition at line 298 of file ast-value-factory.h.
Referenced by v8::internal::AstValueFactory::GetOneByteStringInternal(), and one_character_string().
string_table_
AstRawStringMap v8::internal::AstStringConstants::string_table_ [private]
Definition at line 331 of file ast-value-factory.h.
Referenced by string_table().
zone_
Zone v8::internal::AstStringConstants::zone_ [private]
Definition at line 330 of file ast-value-factory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast-value-factory.h
/mnt/V8SourceCode/src/ast/ast-value-factory.cc