v8::internal::SharedMacroAssembler< Impl > Class Template Reference
#include <macro-assembler-shared-ia32-x64.h>
Public Member Functions
void Abspd (XMMRegister dst, XMMRegister src, Register tmp)
void Absps (XMMRegister dst, XMMRegister src, Register tmp)
void Absph (XMMRegister dst, XMMRegister src, Register tmp)
void Negpd (XMMRegister dst, XMMRegister src, Register tmp)
void Negps (XMMRegister dst, XMMRegister src, Register tmp)
void Negph (XMMRegister dst, XMMRegister src, Register tmp)
void Pextrd (Register dst, XMMRegister src, uint8_t imm8)
template<typename Op >
void Pinsrd (XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t *load_pc_offset=nullptr)
template<typename Op >
void Pinsrd (XMMRegister dst, Op src, uint8_t imm8, uint32_t *load_pc_offset=nullptr)
void F64x2ConvertLowI32x4U (XMMRegister dst, XMMRegister src, Register scratch)
void I32x4SConvertF32x4 (XMMRegister dst, XMMRegister src, XMMRegister tmp, Register scratch)
void I32x4TruncSatF64x2SZero (XMMRegister dst, XMMRegister src, XMMRegister scratch, Register tmp)
void I32x4TruncSatF64x2UZero (XMMRegister dst, XMMRegister src, XMMRegister scratch, Register tmp)
void I32x4TruncF32x4U (XMMRegister dst, XMMRegister src, XMMRegister scratch1, XMMRegister scratch2)
void I32x4ExtAddPairwiseI16x8S (XMMRegister dst, XMMRegister src, Register scratch)
void I16x8ExtAddPairwiseI8x16S (XMMRegister dst, XMMRegister src, XMMRegister scratch, Register tmp)
void I16x8ExtAddPairwiseI8x16U (XMMRegister dst, XMMRegister src, Register scratch)
void I8x16Swizzle (XMMRegister dst, XMMRegister src, XMMRegister mask, XMMRegister scratch, Register tmp, bool omit_add=false)
void I8x16Popcnt (XMMRegister dst, XMMRegister src, XMMRegister tmp1, XMMRegister tmp2, Register scratch)
Private Types
using FloatInstruction = void(SharedMacroAssemblerBase::*)(XMMRegister, XMMRegister, Operand)
Private Member Functions
Impl * impl ()
Operand ExternalReferenceAsOperand (ExternalReference reference, Register scratch)
void FloatUnop (XMMRegister dst, XMMRegister src, Register tmp, FloatInstruction op, ExternalReference ext)
Additional Inherited Members
Detailed Description
template<typename Impl>
class v8::internal::SharedMacroAssembler< Impl >
Definition at line 618 of file macro-assembler-shared-ia32-x64.h.
Member Typedef Documentation
FloatInstruction
template<typename Impl >
using v8::internal::SharedMacroAssembler< Impl >::FloatInstruction = void (SharedMacroAssemblerBase::*)(XMMRegister, XMMRegister, Operand) [private]
Definition at line 1033 of file macro-assembler-shared-ia32-x64.h.
Member Function Documentation
Abspd()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Abspd (XMMRegister dst, XMMRegister src, Register tmp) [inline]
Definition at line 622 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    FloatUnop(dst, src, tmp, &SharedMacroAssemblerBase::Andps,
              ExternalReference::address_of_double_abs_constant());
  }
Absph()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Absph (XMMRegister dst, XMMRegister src, Register tmp) [inline]
Definition at line 632 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    FloatUnop(dst, src, tmp, &SharedMacroAssemblerBase::Andps,
              ExternalReference::address_of_fp16_abs_constant());
  }
Absps()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Absps (XMMRegister dst, XMMRegister src, Register tmp) [inline]
Definition at line 627 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    FloatUnop(dst, src, tmp, &SharedMacroAssemblerBase::Andps,
              ExternalReference::address_of_float_abs_constant());
  }
ExternalReferenceAsOperand()
template<typename Impl >
Operand v8::internal::SharedMacroAssembler< Impl >::ExternalReferenceAsOperand (ExternalReference reference, Register scratch) [inline], [private]
Definition at line 1028 of file macro-assembler-shared-ia32-x64.h.
                                                       {
    return impl()->ExternalReferenceAsOperand(reference, scratch);
  }
References wasm::impl().
F64x2ConvertLowI32x4U()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::F64x2ConvertLowI32x4U (XMMRegister dst, XMMRegister src, Register scratch) [inline]
Definition at line 692 of file macro-assembler-shared-ia32-x64.h.
                                               {
    ASM_CODE_COMMENT(this);
    // dst = [ src_low, 0x43300000, src_high, 0x4330000 ];
    // 0x43300000'00000000 is a special double where the significand bits
    // precisely represents all uint32 numbers.
    if (!CpuFeatures::IsSupported(AVX) && dst != src) {
      movaps(dst, src);
      src = dst;
    }
    Unpcklps(dst, src,
             ExternalReferenceAsOperand(
                 ExternalReference::
                     address_of_wasm_f64x2_convert_low_i32x4_u_int_mask(),
                 scratch));
    Subpd(dst,
          ExternalReferenceAsOperand(
              ExternalReference::address_of_wasm_double_2_power_52(), scratch));
  }
References ASM_CODE_COMMENT, and v8::internal::CpuFeatures::IsSupported().
FloatUnop()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::FloatUnop (XMMRegister dst, XMMRegister src, Register tmp, FloatInstruction op, ExternalReference ext) [inline], [private]
Definition at line 1036 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    if (!CpuFeatures::IsSupported(AVX) && (dst != src)) {
      movaps(dst, src);
      src = dst;
    }
    SharedMacroAssemblerBase* assm = this;
    (assm->*op)(dst, src, ExternalReferenceAsOperand(ext, tmp));
  }
References v8::internal::CpuFeatures::IsSupported().
I16x8ExtAddPairwiseI8x16S()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I16x8ExtAddPairwiseI8x16S (XMMRegister dst, XMMRegister src, XMMRegister scratch, Register tmp) [inline]
Definition at line 884 of file macro-assembler-shared-ia32-x64.h.
                                                                    {
    ASM_CODE_COMMENT(this);
    // pmaddubsw treats the first operand as unsigned, so pass the external
    // reference to it as the first operand.
    Operand op = ExternalReferenceAsOperand(
        ExternalReference::address_of_wasm_i8x16_splat_0x01(), tmp);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      vmovdqa(scratch, op);
      vpmaddubsw(dst, scratch, src);
    } else {
      CpuFeatureScope sse_scope(this, SSSE3);
      if (dst == src) {
        movaps(scratch, op);
        pmaddubsw(scratch, src);
        movaps(dst, scratch);
      } else {
        movaps(dst, op);
        pmaddubsw(dst, src);
      }
    }
  }
References ASM_CODE_COMMENT, and v8::internal::CpuFeatures::IsSupported().
I16x8ExtAddPairwiseI8x16U()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I16x8ExtAddPairwiseI8x16U (XMMRegister dst, XMMRegister src, Register scratch) [inline]
Definition at line 908 of file macro-assembler-shared-ia32-x64.h.
                                                   {
    ASM_CODE_COMMENT(this);
    Operand op = ExternalReferenceAsOperand(
        ExternalReference::address_of_wasm_i8x16_splat_0x01(), scratch);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      vpmaddubsw(dst, src, op);
    } else {
      CpuFeatureScope sse_scope(this, SSSE3);
      if (dst != src) {
        movaps(dst, src);
      }
      pmaddubsw(dst, op);
    }
  }
References ASM_CODE_COMMENT, and v8::internal::CpuFeatures::IsSupported().
I32x4ExtAddPairwiseI16x8S()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I32x4ExtAddPairwiseI16x8S (XMMRegister dst, XMMRegister src, Register scratch) [inline]
Definition at line 867 of file macro-assembler-shared-ia32-x64.h.
                                                   {
    ASM_CODE_COMMENT(this);
    Operand op = ExternalReferenceAsOperand(
        ExternalReference::address_of_wasm_i16x8_splat_0x0001(), scratch);
    // pmaddwd multiplies signed words in src and op, producing
    // signed doublewords, then adds pairwise.
    // src = |a|b|c|d|e|f|g|h|
    // dst = | a*1 + b*1 | c*1 + d*1 | e*1 + f*1 | g*1 + h*1 |
    if (!CpuFeatures::IsSupported(AVX) && (dst != src)) {
      movaps(dst, src);
      src = dst;
    }
    Pmaddwd(dst, src, op);
  }
References ASM_CODE_COMMENT, and v8::internal::CpuFeatures::IsSupported().
I32x4SConvertF32x4()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I32x4SConvertF32x4 (XMMRegister dst, XMMRegister src, XMMRegister tmp, Register scratch) [inline]
Definition at line 712 of file macro-assembler-shared-ia32-x64.h.
                                            {
    ASM_CODE_COMMENT(this);
    Operand op = ExternalReferenceAsOperand(
        ExternalReference::address_of_wasm_int32_overflow_as_float(), scratch);
    // This algorithm works by:
    // 1. lanes with NaNs are zero-ed
    // 2. lanes ge than 2147483648.0f (MAX_INT32+1) set to 0xffff'ffff
    // 3. cvttps2dq sets all out of range lanes to 0x8000'0000
    // a. correct for underflows (< MIN_INT32)
    // b. wrong for overflow, and we know which lanes overflow from 2.
    // 4. adjust for 3b by xor-ing 2 and 3
    // a. 0x8000'0000 xor 0xffff'ffff = 0x7fff'ffff (MAX_INT32)
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope scope(this, AVX);
      vcmpeqps(tmp, src, src);
      vandps(dst, src, tmp);
      vcmpgeps(tmp, src, op);
      vcvttps2dq(dst, dst);
      vpxor(dst, dst, tmp);
    } else {
      if (src == dst) {
        movaps(tmp, src);
        cmpeqps(tmp, tmp);
        andps(dst, tmp);
        movaps(tmp, op);
        cmpleps(tmp, dst);
        cvttps2dq(dst, dst);
        xorps(dst, tmp);
      } else {
        movaps(tmp, op);
        cmpleps(tmp, src);
        cvttps2dq(dst, src);
        xorps(dst, tmp);
        movaps(tmp, src);
        cmpeqps(tmp, tmp);
        andps(dst, tmp);
      }
    }
  }
References ASM_CODE_COMMENT, and v8::internal::CpuFeatures::IsSupported().
I32x4TruncF32x4U()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I32x4TruncF32x4U (XMMRegister dst, XMMRegister src, XMMRegister scratch1, XMMRegister scratch2) [inline]
Definition at line 831 of file macro-assembler-shared-ia32-x64.h.
                                              {
    // NAN->0, negative->0.
    Pxor(scratch1, scratch1);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope scope(this, AVX);
      vmaxps(dst, src, scratch1);
    } else {
      if (dst != src) movaps(dst, src);
      maxps(dst, scratch1);
    }
    // scratch: float representation of max_signed.
    Pcmpeqd(scratch1, scratch1);
    Psrld(scratch1, uint8_t{1}); // 0x7fffffff
    Cvtdq2ps(scratch1, scratch1); // 0x4f000000
    // scratch2: convert (src-max_signed).
    // Set positive overflow lanes to 0x7FFFFFFF.
    // Set negative lanes to 0.
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope scope(this, AVX);
      vsubps(scratch2, dst, scratch1);
    } else {
      movaps(scratch2, dst);
      subps(scratch2, scratch1);
    }
    Cmpleps(scratch1, scratch2);
    Cvttps2dq(scratch2, scratch2);
    Pxor(scratch2, scratch1);
    Pxor(scratch1, scratch1);
    Pmaxsd(scratch2, scratch1);
    // Convert to int. Overflow lanes above max_signed will be 0x80000000.
    Cvttps2dq(dst, dst);
    // Add (src-max_signed) for overflow lanes.
    Paddd(dst, scratch2);
  }
References v8::internal::CpuFeatures::IsSupported().
I32x4TruncSatF64x2SZero()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I32x4TruncSatF64x2SZero (XMMRegister dst, XMMRegister src, XMMRegister scratch, Register tmp) [inline]
Definition at line 754 of file macro-assembler-shared-ia32-x64.h.
                                                                  {
    ASM_CODE_COMMENT(this);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      XMMRegister original_dst = dst;
      // Make sure we don't overwrite src.
      if (dst == src) {
        DCHECK_NE(src, scratch);
        dst = scratch;
      }
      // dst = 0 if src == NaN, else all ones.
      vcmpeqpd(dst, src, src);
      // dst = 0 if src == NaN, else INT32_MAX as double.
      vandpd(
          dst, dst,
          ExternalReferenceAsOperand(
              ExternalReference::address_of_wasm_int32_max_as_double(), tmp));
      // dst = 0 if src == NaN, src is saturated to INT32_MAX as double.
      vminpd(dst, src, dst);
      // Values > INT32_MAX already saturated, values < INT32_MIN raises an
      // exception, which is masked and returns 0x80000000.
      vcvttpd2dq(original_dst, dst);
    } else {
      if (dst != src) {
        movaps(dst, src);
      }
      movaps(scratch, dst);
      cmpeqpd(scratch, dst);
      andps(scratch,
            ExternalReferenceAsOperand(
                ExternalReference::address_of_wasm_int32_max_as_double(), tmp));
      minpd(dst, scratch);
      cvttpd2dq(dst, dst);
    }
  }
References ASM_CODE_COMMENT, DCHECK_NE, and v8::internal::CpuFeatures::IsSupported().
I32x4TruncSatF64x2UZero()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I32x4TruncSatF64x2UZero (XMMRegister dst, XMMRegister src, XMMRegister scratch, Register tmp) [inline]
Definition at line 791 of file macro-assembler-shared-ia32-x64.h.
                                                                  {
    ASM_CODE_COMMENT(this);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      vxorpd(scratch, scratch, scratch);
      // Saturate to 0.
      vmaxpd(dst, src, scratch);
      // Saturate to UINT32_MAX.
      vminpd(
          dst, dst,
          ExternalReferenceAsOperand(
              ExternalReference::address_of_wasm_uint32_max_as_double(), tmp));
      // Truncate.
      vroundpd(dst, dst, kRoundToZero);
      // Add to special double where significant bits == uint32.
      vaddpd(dst, dst,
             ExternalReferenceAsOperand(
                 ExternalReference::address_of_wasm_double_2_power_52(), tmp));
      // Extract low 32 bits of each double's significand, zero top lanes.
      // dst = [dst[0], dst[2], 0, 0]
      vshufps(dst, dst, scratch, 0x88);
    } else {
      CpuFeatureScope scope(this, SSE4_1);
      if (dst != src) {
        movaps(dst, src);
      }
      xorps(scratch, scratch);
      maxpd(dst, scratch);
      minpd(dst, ExternalReferenceAsOperand(
                     ExternalReference::address_of_wasm_uint32_max_as_double(),
                     tmp));
      roundpd(dst, dst, kRoundToZero);
      addpd(dst,
            ExternalReferenceAsOperand(
                ExternalReference::address_of_wasm_double_2_power_52(), tmp));
      shufps(dst, scratch, 0x88);
    }
  }
References ASM_CODE_COMMENT, v8::internal::CpuFeatures::IsSupported(), and v8::internal::kRoundToZero.
I8x16Popcnt()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I8x16Popcnt (XMMRegister dst, XMMRegister src, XMMRegister tmp1, XMMRegister tmp2, Register scratch) [inline]
Definition at line 955 of file macro-assembler-shared-ia32-x64.h.
                                                       {
    ASM_CODE_COMMENT(this);
    DCHECK_NE(dst, tmp1);
    DCHECK_NE(src, tmp1);
    DCHECK_NE(dst, tmp2);
    DCHECK_NE(src, tmp2);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      vmovdqa(tmp1, ExternalReferenceAsOperand(
                        ExternalReference::address_of_wasm_i8x16_splat_0x0f(),
                        scratch));
      vpandn(tmp2, tmp1, src);
      vpand(dst, tmp1, src);
      vmovdqa(tmp1, ExternalReferenceAsOperand(
                        ExternalReference::address_of_wasm_i8x16_popcnt_mask(),
                        scratch));
      vpsrlw(tmp2, tmp2, 4);
      vpshufb(dst, tmp1, dst);
      vpshufb(tmp2, tmp1, tmp2);
      vpaddb(dst, dst, tmp2);
    } else if (CpuFeatures::IsSupported(INTEL_ATOM)) {
      // Pre-Goldmont low-power Intel microarchitectures have very slow
      // PSHUFB instruction, thus use PSHUFB-free divide-and-conquer
      // algorithm on these processors. ATOM CPU feature captures exactly
      // the right set of processors.
      movaps(tmp1, src);
      psrlw(tmp1, 1);
      if (dst != src) {
        movaps(dst, src);
      }
      andps(tmp1, ExternalReferenceAsOperand(
                      ExternalReference::address_of_wasm_i8x16_splat_0x55(),
                      scratch));
      psubb(dst, tmp1);
      Operand splat_0x33 = ExternalReferenceAsOperand(
          ExternalReference::address_of_wasm_i8x16_splat_0x33(), scratch);
      movaps(tmp1, dst);
      andps(dst, splat_0x33);
      psrlw(tmp1, 2);
      andps(tmp1, splat_0x33);
      paddb(dst, tmp1);
      movaps(tmp1, dst);
      psrlw(dst, 4);
      paddb(dst, tmp1);
      andps(dst, ExternalReferenceAsOperand(
                     ExternalReference::address_of_wasm_i8x16_splat_0x0f(),
                     scratch));
    } else {
      CpuFeatureScope sse_scope(this, SSSE3);
      movaps(tmp1, ExternalReferenceAsOperand(
                       ExternalReference::address_of_wasm_i8x16_splat_0x0f(),
                       scratch));
      Operand mask = ExternalReferenceAsOperand(
          ExternalReference::address_of_wasm_i8x16_popcnt_mask(), scratch);
      if (tmp2 != tmp1) {
        movaps(tmp2, tmp1);
      }
      andps(tmp1, src);
      andnps(tmp2, src);
      psrlw(tmp2, 4);
      movaps(dst, mask);
      pshufb(dst, tmp1);
      movaps(tmp1, mask);
      pshufb(tmp1, tmp2);
      paddb(dst, tmp1);
    }
  }
References ASM_CODE_COMMENT, DCHECK_NE, and v8::internal::CpuFeatures::IsSupported().
I8x16Swizzle()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::I8x16Swizzle (XMMRegister dst, XMMRegister src, XMMRegister mask, XMMRegister scratch, Register tmp, bool omit_add = false) [inline]
Definition at line 925 of file macro-assembler-shared-ia32-x64.h.
                                                                              {
    ASM_CODE_COMMENT(this);
    if (omit_add) {
      // We have determined that the indices are immediates, and they are either
      // within bounds, or the top bit is set, so we can omit the add.
      Pshufb(dst, src, mask);
      return;
    }
    // Out-of-range indices should return 0, add 112 so that any value > 15
    // saturates to 128 (top bit set), so pshufb will zero that lane.
    Operand op = ExternalReferenceAsOperand(
        ExternalReference::address_of_wasm_i8x16_swizzle_mask(), tmp);
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope avx_scope(this, AVX);
      vpaddusb(scratch, mask, op);
      vpshufb(dst, src, scratch);
    } else {
      CpuFeatureScope sse_scope(this, SSSE3);
      movaps(scratch, op);
      if (dst != src) {
        DCHECK_NE(dst, mask);
        movaps(dst, src);
      }
      paddusb(scratch, mask);
      pshufb(dst, scratch);
    }
  }
References ASM_CODE_COMMENT, DCHECK_NE, and v8::internal::CpuFeatures::IsSupported().
impl()
template<typename Impl >
Impl* v8::internal::SharedMacroAssembler< Impl >::impl () [inline], [private]
Definition at line 1026 of file macro-assembler-shared-ia32-x64.h.
{ return static_cast<Impl*>(this); }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
Negpd()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Negpd (XMMRegister dst, XMMRegister src, Register tmp) [inline]
Definition at line 637 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    FloatUnop(dst, src, tmp, &SharedMacroAssemblerBase::Xorps,
              ExternalReference::address_of_double_neg_constant());
  }
Negph()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Negph (XMMRegister dst, XMMRegister src, Register tmp) [inline]
Definition at line 647 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    FloatUnop(dst, src, tmp, &SharedMacroAssemblerBase::Xorps,
              ExternalReference::address_of_fp16_neg_constant());
  }
Negps()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Negps (XMMRegister dst, XMMRegister src, Register tmp) [inline]
Definition at line 642 of file macro-assembler-shared-ia32-x64.h.
                                                             {
    FloatUnop(dst, src, tmp, &SharedMacroAssemblerBase::Xorps,
              ExternalReference::address_of_float_neg_constant());
  }
Pextrd()
template<typename Impl >
void v8::internal::SharedMacroAssembler< Impl >::Pextrd (Register dst, XMMRegister src, uint8_t imm8) [inline]
Definition at line 653 of file macro-assembler-shared-ia32-x64.h.
                                                           {
    if (imm8 == 0) {
      Movd(dst, src);
      return;
    }
    if (CpuFeatures::IsSupported(AVX)) {
      CpuFeatureScope scope(this, AVX);
      vpextrd(dst, src, imm8);
    } else if (CpuFeatures::IsSupported(SSE4_1)) {
      CpuFeatureScope sse_scope(this, SSE4_1);
      pextrd(dst, src, imm8);
    } else {
      DCHECK_LT(imm8, 2);
      impl()->PextrdPreSse41(dst, src, imm8);
    }
  }
References DCHECK_LT, wasm::impl(), and v8::internal::CpuFeatures::IsSupported().
Pinsrd() [1/2]
template<typename Impl >
template<typename Op >
void v8::internal::SharedMacroAssembler< Impl >::Pinsrd (XMMRegister dst, Op src, uint8_t imm8, uint32_t * load_pc_offset = nullptr) [inline]
Definition at line 687 of file macro-assembler-shared-ia32-x64.h.
                                                  {
    Pinsrd(dst, dst, src, imm8, load_pc_offset);
  }
Pinsrd() [2/2]
template<typename Impl >
template<typename Op >
void v8::internal::SharedMacroAssembler< Impl >::Pinsrd (XMMRegister dst, XMMRegister src1, Op src2, uint8_t imm8, uint32_t * load_pc_offset = nullptr) [inline]
Definition at line 672 of file macro-assembler-shared-ia32-x64.h.
                                                  {
    if (CpuFeatures::IsSupported(SSE4_1)) {
      PinsrHelper(this, &Assembler::vpinsrd, &Assembler::pinsrd, dst, src1,
                  src2, imm8, load_pc_offset,
                  std::optional<CpuFeature>(SSE4_1));
    } else {
      if (dst != src1) {
        movaps(dst, src1);
      }
      impl()->PinsrdPreSse41(dst, src2, imm8, load_pc_offset);
    }
  }
References wasm::impl(), v8::internal::CpuFeatures::IsSupported(), v8::internal::Assembler::pinsrd(), and v8::internal::Assembler::vpinsrd().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/shared-ia32-x64/macro-assembler-shared-ia32-x64.h