v8::internal::Code::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 1398 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::Code::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 1401 of file objects-body-descriptors-inl.h.
                                                                    {
    IterateSelfIndirectPointer(obj, kCodeIndirectPointerTag, v);
    IterateProtectedPointer(
        obj, Code::kDeoptimizationDataOrInterpreterDataOffset, v);
    IterateProtectedPointer(obj, Code::kPositionTableOffset, v);
    IteratePointers(obj, Code::kStartOfStrongFieldsOffset,
                    Code::kEndOfStrongFieldsWithMainCageBaseOffset, v);
    static_assert(Code::kEndOfStrongFieldsWithMainCageBaseOffset ==
                  Code::kInstructionStreamOffset);
#ifdef V8_ENABLE_LEAPTIERING
    IterateJSDispatchEntry(obj, kDispatchHandleOffset, v);
#endif // V8_ENABLE_LEAPTIERING
    v->VisitInstructionStreamPointer(
        Cast<Code>(obj),
        obj->RawInstructionStreamField(kInstructionStreamOffset));
  }
References v8::internal::BodyDescriptorBase::IteratePointers(), v8::internal::BodyDescriptorBase::IterateProtectedPointer(), v8::internal::BodyDescriptorBase::IterateSelfIndirectPointer(), and v8::internal::ObjectVisitor::VisitInstructionStreamPointer().
SizeOf()
static int v8::internal::Code::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 1422 of file objects-body-descriptors-inl.h.
                                                                       {
    return Code::kSize;
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h