v8::internal::AlignedCachedData Class Reference
#include <code-serializer.h>
Public Member Functions
AlignedCachedData (const uint8_t *data, int length)
~AlignedCachedData ()
AlignedCachedData (const AlignedCachedData &)=delete
AlignedCachedData & operator= (const AlignedCachedData &)=delete
const uint8_t * data () const
int length () const
bool rejected () const
void Reject ()
bool HasDataOwnership () const
void AcquireDataOwnership ()
void ReleaseDataOwnership ()
Private Attributes
bool owns_data_: 1
bool rejected_: 1
const uint8_t * data_
int length_
Detailed Description
Definition at line 19 of file code-serializer.h.
Constructor & Destructor Documentation
AlignedCachedData() [1/2]
v8::internal::AlignedCachedData::AlignedCachedData (const uint8_t * data, int length)
Definition at line 34 of file code-serializer.cc.
    : owns_data_(false), rejected_(false), data_(data), length_(length) {
  if (!IsAligned(reinterpret_cast<intptr_t>(data), kPointerAlignment)) {
    uint8_t* copy = NewArray<uint8_t>(length);
    DCHECK(IsAligned(reinterpret_cast<intptr_t>(copy), kPointerAlignment));
    CopyBytes(copy, data, length);
    data_ = copy;
    AcquireDataOwnership();
  }
}
References AcquireDataOwnership(), v8::internal::CopyBytes(), data(), data_, v8::internal::DCHECK(), IsAligned(), v8::internal::kPointerAlignment, and length().
 AlignedCachedData()
v8::internal::AlignedCachedData::~AlignedCachedData () [inline]
Definition at line 22 of file code-serializer.h.
                       {
    if (owns_data_) DeleteArray(data_);
  }
AlignedCachedData() [2/2]
v8::internal::AlignedCachedData::AlignedCachedData (const AlignedCachedData &) [delete]
Member Function Documentation
AcquireDataOwnership()
void v8::internal::AlignedCachedData::AcquireDataOwnership () [inline]
Definition at line 36 of file code-serializer.h.
                              {
    DCHECK(!owns_data_);
    owns_data_ = true;
  }
References v8::internal::DCHECK().
Referenced by AlignedCachedData(), and v8::internal::BackgroundDeserializeTask::BackgroundDeserializeTask().
data()
const uint8_t* v8::internal::AlignedCachedData::data () const [inline]
Definition at line 28 of file code-serializer.h.
{ return data_; }
Referenced by AlignedCachedData(), and v8::internal::CodeSerializer::Serialize().
HasDataOwnership()
bool v8::internal::AlignedCachedData::HasDataOwnership () const [inline]
Definition at line 34 of file code-serializer.h.
{ return owns_data_; }
Referenced by v8::internal::BackgroundDeserializeTask::BackgroundDeserializeTask().
length()
int v8::internal::AlignedCachedData::length () const [inline]
Definition at line 29 of file code-serializer.h.
{ return length_; }
Referenced by AlignedCachedData(), v8::internal::CodeSerializer::Deserialize(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), and v8::internal::CodeSerializer::Serialize().
operator=()
AlignedCachedData& v8::internal::AlignedCachedData::operator= (const AlignedCachedData &) [delete]
Reject()
void v8::internal::AlignedCachedData::Reject () [inline]
Definition at line 32 of file code-serializer.h.
{ rejected_ = true; }
Referenced by v8::internal::SerializedCodeData::FromCachedData(), v8::internal::SerializedCodeData::FromCachedDataWithoutSource(), and v8::internal::SerializedCodeData::FromPartiallySanityCheckedCachedData().
rejected()
bool v8::internal::AlignedCachedData::rejected () const [inline]
Definition at line 30 of file code-serializer.h.
{ return rejected_; }
Referenced by v8::internal::CodeSerializer::Deserialize(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), and v8::internal::CodeSerializer::StartDeserializeOffThread().
ReleaseDataOwnership()
void v8::internal::AlignedCachedData::ReleaseDataOwnership () [inline]
Definition at line 41 of file code-serializer.h.
                              {
    DCHECK(owns_data_);
    owns_data_ = false;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::CodeSerializer::Serialize().
Member Data Documentation
data_
const uint8_t* v8::internal::AlignedCachedData::data_ [private]
Definition at line 49 of file code-serializer.h.
Referenced by AlignedCachedData().
length_
int v8::internal::AlignedCachedData::length_ [private]
Definition at line 50 of file code-serializer.h.
owns_data_
bool v8::internal::AlignedCachedData::owns_data_ [private]
Definition at line 47 of file code-serializer.h.
rejected_
bool v8::internal::AlignedCachedData::rejected_ [private]
Definition at line 48 of file code-serializer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/code-serializer.h
/mnt/V8SourceCode/src/snapshot/code-serializer.cc