v8::Module Class Reference
A compiled JavaScript module.
#include <v8-script.h>
Public Types
enum Status {
kUninstantiated
, kInstantiating
, kInstantiated
, kEvaluating
,
kEvaluated
, kErrored
 }
The different states a module can be in.
using ResolveModuleCallback = MaybeLocal< Module >(*)(Local< Context > context, Local< String > specifier, Local< FixedArray > import_attributes, Local< Module > referrer)
using ResolveSourceCallback = MaybeLocal< Object >(*)(Local< Context > context, Local< String > specifier, Local< FixedArray > import_attributes, Local< Module > referrer)
using SyntheticModuleEvaluationSteps = MaybeLocal< Value >(*)(Local< Context > context, Local< Module > module)
Public Member Functions
Status GetStatus () const
Returns the module's current status.
Local< Value > GetException () const
For a module in kErrored status, this returns the corresponding exception.
Local< FixedArray > GetModuleRequests () const
Returns the ModuleRequests for this module.
Location SourceOffsetToLocation (int offset) const
For the given source text offset in this module, returns the corresponding Location with line and column numbers.
int GetIdentityHash () const
Returns the identity hash for this object.
V8_WARN_UNUSED_RESULT Maybe< bool > InstantiateModule (Local< Context > context, ResolveModuleCallback module_callback, ResolveSourceCallback source_callback=nullptr)
Instantiates the module and its dependencies.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > Evaluate (Local< Context > context)
Evaluates the module and its dependencies.
Local< Value > GetModuleNamespace ()
Returns the namespace object of this module.
Local< UnboundModuleScript > GetUnboundModuleScript ()
Returns the corresponding context-unbound module script.
int ScriptId () const
Returns the underlying script's id.
bool IsGraphAsync () const
Returns whether this module or any of its requested modules is async, i.e.
bool HasTopLevelAwait () const
Returns whether this module is individually asynchronous (for example, if it's a Source Text Module Record containing a top-level await).
bool IsSourceTextModule () const
Returns whether the module is a SourceTextModule.
bool IsSyntheticModule () const
Returns whether the module is a SyntheticModule.
V8_WARN_UNUSED_RESULT Maybe< bool > SetSyntheticModuleExport (Isolate *isolate, Local< String > export_name, Local< Value > export_value)
Set this module's exported value for the name export_name to the specified export_value.
std::pair< LocalVector< Module >, LocalVector< Message > > GetStalledTopLevelAwaitMessages (Isolate *isolate)
Search the modules requested directly or indirectly by the module for any top-level await that has not yet resolved.
Static Public Member Functions
static Local< Module > CreateSyntheticModule (Isolate *isolate, Local< String > module_name, const MemorySpan< const Local< String >> &export_names, SyntheticModuleEvaluationSteps evaluation_steps)
Creates a new SyntheticModule with the specified export names, where evaluation_steps will be executed upon module evaluation.
static Module * Cast (Data *data)
Static Private Member Functions
static void CheckCast (Data *obj)
Detailed Description
A compiled JavaScript module.
Definition at line 172 of file v8-script.h.
Member Typedef Documentation
ResolveModuleCallback
using v8::Module::ResolveModuleCallback = MaybeLocal<Module> (*)(Local<Context> context, Local<String> specifier, Local<FixedArray> import_attributes, Local<Module> referrer)
Definition at line 216 of file v8-script.h.
ResolveSourceCallback
using v8::Module::ResolveSourceCallback = MaybeLocal<Object> (*)(Local<Context> context, Local<String> specifier, Local<FixedArray> import_attributes, Local<Module> referrer)
Definition at line 219 of file v8-script.h.
SyntheticModuleEvaluationSteps
using v8::Module::SyntheticModuleEvaluationSteps = MaybeLocal<Value> (*)(Local<Context> context, Local<Module> module)
Definition at line 300 of file v8-script.h.
Member Enumeration Documentation
Status
enum v8::Module::Status
The different states a module can be in.
This corresponds to the states used in ECMAScript except that `evaluated` is split into kEvaluated and kErrored, indicating success and failure, respectively.
Enumerator
kUninstantiated
kInstantiating
kInstantiated
kEvaluating
kEvaluated
kErrored
Definition at line 181 of file v8-script.h.
              {
    kUninstantiated,
    kInstantiating,
    kInstantiated,
    kEvaluating,
    kEvaluated,
    kErrored
  };
Member Function Documentation
Cast()
Module * v8::Module::Cast (Data * data) [inline], [static]
Definition at line 943 of file v8-script.h.
                               {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<Module*>(data);
}
CheckCast()
void v8::Module::CheckCast (v8::Data * that) [static], [private]
Definition at line 3916 of file api.cc.
                                     {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsModule(*obj), "v8::Module::Cast",
                  "Value is not a Module");
}
References v8::Utils::ApiCheck(), v8::internal::IsModule(), and v8::Utils::OpenDirectHandle().
CreateSyntheticModule()
Local< Module > v8::Module::CreateSyntheticModule (Isolate * isolate, Local< String > module_name, const MemorySpan< const Local< String >> & export_names, SyntheticModuleEvaluationSteps evaluation_steps) [static]
Creates a new SyntheticModule with the specified export names, where evaluation_steps will be executed upon module evaluation.
export_names must not contain duplicates. module_name is used solely for logging/debugging and doesn't affect module behavior.
Definition at line 2301 of file api.cc.
                                                             {
  auto i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto i_module_name = Utils::OpenDirectHandle(*module_name);
  i::DirectHandle<i::FixedArray> i_export_names =
      i_isolate->factory()->NewFixedArray(
          static_cast<int>(export_names.size()));
  for (int i = 0; i < i_export_names->length(); ++i) {
    i::DirectHandle<i::String> str = i_isolate->factory()->InternalizeString(
        Utils::OpenDirectHandle(*export_names[i]));
    i_export_names->set(i, *str);
  }
  return v8::Utils::ToLocal(
      i::DirectHandle<i::Module>(i_isolate->factory()->NewSyntheticModule(
          i_module_name, i_export_names, evaluation_steps)));
}
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Factory::InternalizeString(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewSyntheticModule(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::FetchModuleTree().
Evaluate()
MaybeLocal< Value > v8::Module::Evaluate (Local< Context > context)
Evaluates the module and its dependencies.
If status is kInstantiated, run the module's code and return a Promise object. On success, set status to kEvaluated and resolve the Promise with the completion value; on failure, set status to kErrored and reject the Promise with the error.
If IsGraphAsync() is false, the returned Promise is settled.
Definition at line 2283 of file api.cc.
                                                         {
  auto i_isolate = i::Isolate::Current();
  TRACE_EVENT_CALL_STATS_SCOPED(i_isolate, "v8", "V8.Execute");
  EnterV8Scope<InternalEscapableScope> api_scope{i_isolate, context,
                                                 RCCId::kAPI_Module_Evaluate};
  i::TimerEventScope<i::TimerEventExecute> timer_scope(i_isolate);
  i::NestedTimedHistogramScope execute_timer(i_isolate->counters()->execute(),
                                             i_isolate);
  i::AggregatingHistogramTimerScope timer(
      i_isolate->counters()->compile_lazy());
  auto self = Utils::OpenHandle(this);
  Utils::ApiCheck(self->status() >= i::Module::kLinked, "Module::Evaluate",
                  "Expected instantiated module");
  return api_scope.EscapeMaybe(i::Module::Evaluate(i_isolate, self));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::counters(), v8::internal::Isolate::Current(), v8::internal::Module::Evaluate(), v8::internal::Module::kLinked, v8::Utils::OpenHandle(), and TRACE_EVENT_CALL_STATS_SCOPED.
GetException()
Local< Value > v8::Module::GetException () const
For a module in kErrored status, this returns the corresponding exception.
Definition at line 2158 of file api.cc.
                                        {
  Utils::ApiCheck(GetStatus() == kErrored, "v8::Module::GetException",
                  "Module status must be kErrored");
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return ToApiHandle<Value>(i::direct_handle(self->GetException(), i_isolate));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
GetIdentityHash()
int v8::Module::GetIdentityHash () const
Returns the identity hash for this object.
Definition at line 2263 of file api.cc.
                                  {
  auto self = Utils::OpenDirectHandle(this);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return self->hash();
}
References v8::Utils::OpenDirectHandle().
GetModuleNamespace()
Local< Value > v8::Module::GetModuleNamespace ()
Returns the namespace object of this module.
The module's status must be at least kInstantiated.
Definition at line 2198 of file api.cc.
                                        {
  Utils::ApiCheck(
      GetStatus() >= kInstantiated, "v8::Module::GetModuleNamespace",
      "v8::Module::GetModuleNamespace must be used on an instantiated module");
  auto self = Utils::OpenHandle(this);
  auto i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  i::DirectHandle<i::JSModuleNamespace> module_namespace =
      i::Module::GetModuleNamespace(i_isolate, self);
  return ToApiHandle<Value>(module_namespace);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Module::GetModuleNamespace(), and v8::Utils::OpenHandle().
GetModuleRequests()
Local< FixedArray > v8::Module::GetModuleRequests () const
Returns the ModuleRequests for this module.
Definition at line 2167 of file api.cc.
                                                  {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  if (i::IsSyntheticModule(*self)) {
    // Synthetic modules are leaf nodes in the module graph. They have no
    // ModuleRequests.
    return ToApiHandle<FixedArray>(i_isolate->factory()->empty_fixed_array());
  } else {
    return ToApiHandle<FixedArray>(i::direct_handle(
        i::Cast<i::SourceTextModule>(self)->info()->module_requests(),
        i_isolate));
  }
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), and v8::Utils::OpenDirectHandle().
GetStalledTopLevelAwaitMessages()
std::pair< LocalVector< Module >, LocalVector< Message > > v8::Module::GetStalledTopLevelAwaitMessages (Isolate * isolate)
Search the modules requested directly or indirectly by the module for any top-level await that has not yet resolved.
If there is any, the returned pair of vectors (of equal size) contain the unresolved module and corresponding message with the pending top-level await. An embedder may call this before exiting to improve error messages.
Definition at line 2344 of file api.cc.
                                                        {
  auto i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  auto self = Utils::OpenDirectHandle(this);
  Utils::ApiCheck(i::IsSourceTextModule(*self),
                  "v8::Module::GetStalledTopLevelAwaitMessages",
                  "v8::Module::GetStalledTopLevelAwaitMessages must only be "
                  "called on a SourceTextModule");
  std::pair<i::DirectHandleVector<i::SourceTextModule>,
            i::DirectHandleVector<i::JSMessageObject>>
      stalled_awaits =
          i::Cast<i::SourceTextModule>(self)->GetStalledTopLevelAwaitMessages(
              i_isolate);
  LocalVector<Module> modules(isolate);
  if (size_t stalled_awaits_count = stalled_awaits.first.size();
      stalled_awaits_count > 0) {
    modules.reserve(stalled_awaits_count);
    for (auto module : stalled_awaits.first)
      modules.push_back(ToApiHandle<Module>(module));
  }
  LocalVector<Message> messages(isolate);
  if (size_t stalled_awaits_count = stalled_awaits.second.size();
      stalled_awaits_count > 0) {
    messages.reserve(stalled_awaits_count);
    for (auto message : stalled_awaits.second)
      messages.push_back(ToApiHandle<Message>(message));
  }
  return {modules, messages};
}
References v8::Utils::ApiCheck(), v8::Utils::OpenDirectHandle(), v8::LocalVector< T >::push_back(), and v8::LocalVector< T >::reserve().
GetStatus()
Module::Status v8::Module::GetStatus () const
Returns the module's current status.
Definition at line 2136 of file api.cc.
                                     {
  auto self = Utils::OpenDirectHandle(this);
  switch (self->status()) {
    case i::Module::kUnlinked:
    case i::Module::kPreLinking:
      return kUninstantiated;
    case i::Module::kLinking:
      return kInstantiating;
    case i::Module::kLinked:
      return kInstantiated;
    case i::Module::kEvaluating:
      return kEvaluating;
    case i::Module::kEvaluatingAsync:
      // TODO(syg): Expose kEvaluatingAsync in API as well.
    case i::Module::kEvaluated:
      return kEvaluated;
    case i::Module::kErrored:
      return kErrored;
  }
  UNREACHABLE();
}
References v8::internal::Module::kErrored, v8::internal::Module::kEvaluated, v8::internal::Module::kEvaluating, v8::internal::Module::kEvaluatingAsync, v8::internal::Module::kLinked, v8::internal::Module::kLinking, v8::internal::Module::kPreLinking, v8::internal::Module::kUnlinked, v8::Utils::OpenDirectHandle(), and UNREACHABLE.
GetUnboundModuleScript()
Local< UnboundModuleScript > v8::Module::GetUnboundModuleScript ()
Returns the corresponding context-unbound module script.
The module must be unevaluated, i.e. its status must not be kEvaluating, kEvaluated or kErrored.
Definition at line 2211 of file api.cc.
                                                          {
  auto self = Utils::OpenDirectHandle(this);
  Utils::ApiCheck(
      i::IsSourceTextModule(*self), "v8::Module::GetUnboundModuleScript",
      "v8::Module::GetUnboundModuleScript must be used on an SourceTextModule");
  auto i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return ToApiHandle<UnboundModuleScript>(i::direct_handle(
      i::Cast<i::SourceTextModule>(self)->GetSharedFunctionInfo(), i_isolate));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::ETWJITInterface::GetSharedFunctionInfo(), and v8::Utils::OpenDirectHandle().
HasTopLevelAwait()
bool v8::Module::HasTopLevelAwait () const
Returns whether this module is individually asynchronous (for example, if it's a Source Text Module Record containing a top-level await).
See [[HasTLA]] in https://tc39.es/ecma262/#sec-cyclic-module-records
Definition at line 2232 of file api.cc.
                                    {
  i::Tagged<i::Module> self = *Utils::OpenDirectHandle(this);
  if (!i::IsSourceTextModule(self)) return false;
  return i::Cast<i::SourceTextModule>(self)->has_toplevel_await();
}
References v8::Utils::OpenDirectHandle().
InstantiateModule()
Maybe< bool > v8::Module::InstantiateModule (Local< Context > context, ResolveModuleCallback module_callback, ResolveSourceCallback source_callback = nullptr)
Instantiates the module and its dependencies.
Returns an empty Maybe<bool> if an exception occurred during instantiation. (In the case where the callback throws an exception, that exception is propagated.)
Definition at line 2270 of file api.cc.
                                                                             {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Module_InstantiateModule};
  if (!i::Module::Instantiate(i_isolate, Utils::OpenHandle(this), context,
                              module_callback, source_callback)) {
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::internal::Module::Instantiate(), v8::Just(), and v8::Utils::OpenHandle().
IsGraphAsync()
bool v8::Module::IsGraphAsync () const
Returns whether this module or any of its requested modules is async, i.e.
contains top-level await.
The module's status must be at least kInstantiated.
Definition at line 2238 of file api.cc.
                                {
  Utils::ApiCheck(
      GetStatus() >= kInstantiated, "v8::Module::IsGraphAsync",
      "v8::Module::IsGraphAsync must be used on an instantiated module");
  i::Tagged<i::Module> self = *Utils::OpenDirectHandle(this);
  auto i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return self->IsGraphAsync(i_isolate);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), and v8::Utils::OpenDirectHandle().
IsSourceTextModule()
bool v8::Module::IsSourceTextModule () const
Returns whether the module is a SourceTextModule.
Definition at line 2249 of file api.cc.
                                      {
  auto self = Utils::OpenDirectHandle(this);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return i::IsSourceTextModule(*self);
}
References v8::Utils::OpenDirectHandle().
IsSyntheticModule()
bool v8::Module::IsSyntheticModule () const
Returns whether the module is a SyntheticModule.
Definition at line 2256 of file api.cc.
                                     {
  auto self = Utils::OpenDirectHandle(this);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return i::IsSyntheticModule(*self);
}
References v8::Utils::OpenDirectHandle().
ScriptId()
int v8::Module::ScriptId () const
Returns the underlying script's id.
The module must be a SourceTextModule and must not have a kErrored status.
Definition at line 2223 of file api.cc.
                           {
  i::Tagged<i::Module> self = *Utils::OpenDirectHandle(this);
  Utils::ApiCheck(i::IsSourceTextModule(self), "v8::Module::ScriptId",
                  "v8::Module::ScriptId must be used on an SourceTextModule");
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return i::Cast<i::SourceTextModule>(self)->GetScript()->id();
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
SetSyntheticModuleExport()
Maybe< bool > v8::Module::SetSyntheticModuleExport (Isolate * isolate, Local< String > export_name, Local< Value > export_value)
Set this module's exported value for the name export_name to the specified export_value.
This method must be called only on Modules created via CreateSyntheticModule. An error will be thrown if export_name is not one of the export_names that were passed in that CreateSyntheticModule call. Returns Just(true) on success, Nothing<bool>() if an error was thrown.
Definition at line 2321 of file api.cc.
                                                                          {
  auto i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto i_export_name = Utils::OpenDirectHandle(*export_name);
  auto i_export_value = Utils::OpenDirectHandle(*export_value);
  auto self = Utils::OpenDirectHandle(this);
  Utils::ApiCheck(i::IsSyntheticModule(*self),
                  "v8::Module::SyntheticModuleSetExport",
                  "v8::Module::SyntheticModuleSetExport must only be called on "
                  "a SyntheticModule");
  EnterV8NoScriptScope<> api_scope{i_isolate, v8_isolate->GetCurrentContext(),
                                   RCCId::kAPI_Module_SetSyntheticModuleExport};
  if (i::SyntheticModule::SetExport(i_isolate,
                                    i::Cast<i::SyntheticModule>(self),
                                    i_export_name, i_export_value)
          .IsNothing()) {
    return {};
  }
  return Just(true);
}
References v8::Utils::ApiCheck(), v8::Isolate::GetCurrentContext(), v8::Just(), v8::Utils::OpenDirectHandle(), and v8::internal::SyntheticModule::SetExport().
SourceOffsetToLocation()
Location v8::Module::SourceOffsetToLocation (int offset) const
For the given source text offset in this module, returns the corresponding Location with line and column numbers.
Definition at line 2183 of file api.cc.
                                                        {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  Utils::ApiCheck(
      i::IsSourceTextModule(*self), "v8::Module::SourceOffsetToLocation",
      "v8::Module::SourceOffsetToLocation must be used on an SourceTextModule");
  i::DirectHandle<i::Script> script(
      i::Cast<i::SourceTextModule>(self)->GetScript(), i_isolate);
  i::Script::PositionInfo info;
  i::Script::GetPositionInfo(script, offset, &info);
  return v8::Location(info.line, info.column);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Script::GetPositionInfo(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc