v8::internal::HandleScope Class Reference
#include <handles.h>
Public Member Functions
HandleScope (Isolate *isolate)
HandleScope (HandleScope &&other) V8_NOEXCEPT
HandleScope (const HandleScope &)=delete
HandleScope & operator= (const HandleScope &)=delete
void * operator new (size_t size, void *storage)
void * operator new (size_t size)=delete
void operator delete (void *size_t)=delete
~HandleScope ()
HandleScope & operator= (HandleScope &&other) V8_NOEXCEPT
template<typename T , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>) HandleType< T > CloseAndEscape(HandleType< T > handle_value)
Isolate * isolate ()
Static Public Member Functions
static V8_EXPORT_PRIVATE int NumberOfHandles (Isolate *isolate)
static Address * CreateHandle (Isolate *isolate, Address value)
static V8_EXPORT_PRIVATE void DeleteExtensions (Isolate *isolate)
static Address current_next_address (Isolate *isolate)
static Address current_limit_address (Isolate *isolate)
static Address current_level_address (Isolate *isolate)
Static Public Attributes
static const int kCheckHandleThreshold = 30 * 1024
Static Private Member Functions
static void CloseScope (Isolate *isolate, Address *prev_next, Address *prev_limit)
V8_EXPORT_PRIVATE static V8_NOINLINE Address * Extend (Isolate *isolate)
Private Attributes
Isolate * isolate_
Address * prev_next_
Address * prev_limit_
Friends
class v8::HandleScope
class HandleScopeImplementer
class Isolate
class LocalHandles
class LocalHandleScope
class PersistentHandles
Detailed Description
Definition at line 263 of file handles.h.
Constructor & Destructor Documentation
HandleScope() [1/3]
v8::internal::HandleScope::HandleScope (Isolate * isolate) [inline], [explicit]
Definition at line 177 of file handles-inl.h.
                                         {
  HandleScopeData* data = isolate->handle_scope_data();
  isolate_ = isolate;
  prev_next_ = data->next;
  prev_limit_ = data->limit;
  data->level++;
#ifdef V8_ENABLE_CHECKS
  scope_level_ = data->level;
#endif
}
References v8::internal::Isolate::handle_scope_data(), v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, v8::HandleScope::prev_limit_, and v8::HandleScope::prev_next_.
HandleScope() [2/3]
v8::internal::HandleScope::HandleScope (HandleScope && other) [inline]
Definition at line 188 of file handles-inl.h.
    : isolate_(other.isolate_),
      prev_next_(other.prev_next_),
      prev_limit_(other.prev_limit_) {
  other.isolate_ = nullptr;
#ifdef V8_ENABLE_CHECKS
  scope_level_ = other.scope_level_;
#endif
}
HandleScope() [3/3]
v8::internal::HandleScope::HandleScope (const HandleScope &) [delete]
 HandleScope()
v8::internal::HandleScope::~HandleScope () [inline]
Definition at line 198 of file handles-inl.h.
                          {
  if (V8_UNLIKELY(isolate_ == nullptr)) return;
#ifdef V8_ENABLE_CHECKS
  CHECK_EQ(scope_level_, isolate_->handle_scope_data()->level);
#endif
  CloseScope(isolate_, prev_next_, prev_limit_);
}
References CHECK_EQ, v8::HandleScope::prev_limit_, v8::HandleScope::prev_next_, and V8_UNLIKELY.
Member Function Documentation
CloseScope()
void v8::internal::HandleScope::CloseScope (Isolate * isolate, Address * prev_next, Address * prev_limit) [inline], [static], [private]
Definition at line 225 of file handles-inl.h.
                                                  {
#ifdef DEBUG
  int before = v8_flags.check_handle_count ? NumberOfHandles(isolate) : 0;
#endif
  DCHECK_NOT_NULL(isolate);
  HandleScopeData* current = isolate->handle_scope_data();
  std::swap(current->next, prev_next);
  current->level--;
  Address* limit = prev_next;
  if (V8_UNLIKELY(current->limit != prev_limit)) {
    current->limit = prev_limit;
    limit = prev_limit;
    DeleteExtensions(isolate);
  }
#ifdef ENABLE_LOCAL_HANDLE_ZAPPING
  ZapRange(current->next, limit);
#endif
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(
      current->next,
      static_cast<size_t>(reinterpret_cast<Address>(limit) -
                          reinterpret_cast<Address>(current->next)));
#ifdef DEBUG
  int after = v8_flags.check_handle_count ? NumberOfHandles(isolate) : 0;
  DCHECK_LT(after - before, kCheckHandleThreshold);
  DCHECK_LT(before, kCheckHandleThreshold);
#endif
}
References DCHECK_LT, DCHECK_NOT_NULL, v8::internal::Isolate::handle_scope_data(), v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, MSAN_ALLOCATED_UNINITIALIZED_MEMORY, v8::internal::HandleScopeData::next, v8::HandleScope::NumberOfHandles(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::LocalHandleScope::CloseMainThreadScope(), and v8::HandleScope::~HandleScope().
CreateHandle()
Address * v8::internal::HandleScope::CreateHandle (Isolate * isolate, Address value) [inline], [static]
Definition at line 276 of file handles-inl.h.
                                                                  {
  DCHECK(AllowHandleAllocation::IsAllowed());
  DCHECK_EQ(isolate, Isolate::TryGetCurrent());
#ifdef DEBUG
  if (!AllowHandleUsageOnAllThreads::IsAllowed()) {
    DCHECK(isolate->main_thread_local_heap()->IsRunning());
    DCHECK_WITH_MSG(
        isolate->thread_id() == ThreadId::Current(),
        "main-thread handle can only be created on the main thread.");
  }
  // We should only allocate handles for objects that can be referenced from the
  // isolate's heap.
#ifdef ENABLE_SLOW_DCHECKS
  if (!HAS_SMI_TAG(value)) {
    DCHECK(HAS_STRONG_HEAP_OBJECT_TAG(value));
    Tagged<HeapObject> obj = UncheckedCast<HeapObject>(Tagged<Object>{value});
    SLOW_DCHECK(isolate->heap()->CanReferenceHeapObject(obj));
  }
#endif // ENABLE_SLOW_DCHECKS
#endif // DEBUG
  HandleScopeData* data = isolate->handle_scope_data();
  Address* result = data->next;
  if (V8_UNLIKELY(result == data->limit)) {
    result = Extend(isolate);
  }
  // Update the current next field, set the value in the created handle,
  // and return the result.
  DCHECK_LT(reinterpret_cast<Address>(result),
            reinterpret_cast<Address>(data->limit));
  data->next = reinterpret_cast<Address*>(reinterpret_cast<Address>(result) +
                                          sizeof(Address));
  *result = value;
  return result;
}
References v8::internal::Heap::CanReferenceHeapObject(), DCHECK, DCHECK_EQ, DCHECK_LT, DCHECK_WITH_MSG, v8::internal::Isolate::handle_scope_data(), HAS_SMI_TAG, HAS_STRONG_HEAP_OBJECT_TAG, v8::internal::Isolate::heap(), v8::internal::LocalHeap::IsRunning(), v8::internal::HandleScopeData::limit, v8::internal::Isolate::main_thread_local_heap(), v8::internal::HandleScopeData::next, v8::base::internal::result, SLOW_DCHECK, v8::internal::Isolate::thread_id(), v8::Isolate::TryGetCurrent(), V8_UNLIKELY, and v8::internal::value.
Referenced by v8::HandleScope::CreateHandle(), v8::internal::LocalHandleScope::GetMainThreadHandle(), and v8::internal::Handle< T >::New().
current_level_address()
Address v8::internal::HandleScope::current_level_address (Isolate * isolate) [static]
Definition at line 235 of file handles.cc.
                                                           {
  return reinterpret_cast<Address>(&isolate->handle_scope_data()->level);
}
References v8::internal::Isolate::handle_scope_data(), isolate(), and v8::internal::HandleScopeData::level.
current_limit_address()
Address v8::internal::HandleScope::current_limit_address (Isolate * isolate) [static]
Definition at line 243 of file handles.cc.
                                                           {
  return reinterpret_cast<Address>(&isolate->handle_scope_data()->limit);
}
References v8::internal::Isolate::handle_scope_data(), isolate(), and v8::internal::HandleScopeData::limit.
current_next_address()
Address v8::internal::HandleScope::current_next_address (Isolate * isolate) [static]
Definition at line 239 of file handles.cc.
                                                          {
  return reinterpret_cast<Address>(&isolate->handle_scope_data()->next);
}
References v8::internal::Isolate::handle_scope_data(), isolate(), and v8::internal::HandleScopeData::next.
DeleteExtensions()
void v8::internal::HandleScope::DeleteExtensions (Isolate * isolate) [static]
Definition at line 220 of file handles.cc.
                                                   {
  HandleScopeData* current = isolate->handle_scope_data();
  isolate->handle_scope_implementer()->DeleteExtensions(current->limit);
}
References v8::internal::HandleScopeImplementer::DeleteExtensions(), v8::internal::Isolate::handle_scope_data(), v8::internal::Isolate::handle_scope_implementer(), isolate(), and v8::internal::HandleScopeData::limit.
Extend()
Address * v8::internal::HandleScope::Extend (Isolate * isolate) [static], [private]
Definition at line 182 of file handles.cc.
                                             {
  HandleScopeData* current = isolate->handle_scope_data();
  Address* result = current->next;
  DCHECK(result == current->limit);
  // Make sure there's at least one scope on the stack and that the
  // top of the scope stack isn't a barrier.
  if (!Utils::ApiCheck(current->level != current->sealed_level,
                       "v8::HandleScope::CreateHandle()",
                       "Cannot create a handle without a HandleScope")) {
    return nullptr;
  }
  HandleScopeImplementer* impl = isolate->handle_scope_implementer();
  // If there's more room in the last block, we use that. This is used
  // for fast creation of scopes after scope barriers.
  if (!impl->blocks()->empty()) {
    Address* limit = &impl->blocks()->back()[kHandleBlockSize];
    if (current->limit != limit) {
      current->limit = limit;
      DCHECK_LT(limit - current->next, kHandleBlockSize);
    }
  }
  // If we still haven't found a slot for the handle, we extend the
  // current handle scope by allocating a new handle block.
  if (result == current->limit) {
    // If there's a spare block, use it for growing the current scope.
    result = impl->GetSpareOrNewBlock();
    // Add the extension to the global list of blocks, but count the
    // extension as part of the current scope.
    impl->blocks()->push_back(result);
    current->limit = &result[kHandleBlockSize];
  }
  return result;
}
References v8::Utils::ApiCheck(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::Isolate::handle_scope_data(), v8::internal::Isolate::handle_scope_implementer(), wasm::impl(), isolate(), v8::internal::kHandleBlockSize, v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, v8::base::internal::result, and v8::internal::HandleScopeData::sealed_level.
isolate()
Isolate* v8::internal::HandleScope::isolate () [inline]
Definition at line 310 of file handles.h.
{ return isolate_; }
Referenced by current_level_address(), current_limit_address(), current_next_address(), DeleteExtensions(), Extend(), and NumberOfHandles().
NumberOfHandles()
int v8::internal::HandleScope::NumberOfHandles (Isolate * isolate) [static]
Definition at line 173 of file handles.cc.
                                                 {
  HandleScopeImplementer* impl = isolate->handle_scope_implementer();
  int n = static_cast<int>(impl->blocks()->size());
  if (n == 0) return 0;
  return ((n - 1) * kHandleBlockSize) +
         static_cast<int>(
             (isolate->handle_scope_data()->next - impl->blocks()->back()));
}
References v8::internal::Isolate::handle_scope_data(), v8::internal::Isolate::handle_scope_implementer(), wasm::impl(), isolate(), v8::internal::kHandleBlockSize, and v8::internal::HandleScopeData::next.
Referenced by v8::HandleScope::NumberOfHandles().
operator delete()
void v8::internal::HandleScope::operator delete (void * size_t) [delete]
operator new() [1/2]
void* v8::internal::HandleScope::operator new (size_t size) [delete]
operator new() [2/2]
void* v8::internal::HandleScope::operator new (size_t size, void * storage) [inline]
Definition at line 271 of file handles.h.
                                                 {
    return ::operator new(size, storage);
  }
References size().
operator=() [1/2]
HandleScope& v8::internal::HandleScope::operator= (const HandleScope &) [delete]
operator=() [2/2]
HandleScope & v8::internal::HandleScope::operator= (HandleScope && other) [inline]
Definition at line 206 of file handles-inl.h.
                                                                   {
  if (isolate_ == nullptr) {
    isolate_ = other.isolate_;
  } else {
    DCHECK_EQ(isolate_, other.isolate_);
#ifdef V8_ENABLE_CHECKS
    CHECK_EQ(scope_level_, isolate_->handle_scope_data()->level);
#endif
    CloseScope(isolate_, prev_next_, prev_limit_);
  }
  prev_next_ = other.prev_next_;
  prev_limit_ = other.prev_limit_;
  other.isolate_ = nullptr;
#ifdef V8_ENABLE_CHECKS
  scope_level_ = other.scope_level_;
#endif
  return *this;
}
References CHECK_EQ, and DCHECK_EQ.
requires()
template<typename T , template< typename > typename HandleType>
v8::internal::HandleScope::requires (std::is_convertible_v< HandleType< T >, DirectHandle< T >>)
Friends And Related Function Documentation
HandleScopeImplementer
friend class HandleScopeImplementer [friend]
Definition at line 341 of file handles.h.
Isolate
friend class Isolate [friend]
Definition at line 342 of file handles.h.
LocalHandles
friend class LocalHandles [friend]
Definition at line 343 of file handles.h.
LocalHandleScope
friend class LocalHandleScope [friend]
Definition at line 344 of file handles.h.
PersistentHandles
friend class PersistentHandles [friend]
Definition at line 345 of file handles.h.
v8::HandleScope
friend class v8::HandleScope [friend]
Definition at line 340 of file handles.h.
Member Data Documentation
isolate_
Isolate* v8::internal::HandleScope::isolate_ [private]
Definition at line 318 of file handles.h.
kCheckHandleThreshold
const int v8::internal::HandleScope::kCheckHandleThreshold = 30 * 1024 [static]
Definition at line 315 of file handles.h.
Referenced by v8::internal::CheckHandleCountVisitor::~CheckHandleCountVisitor().
prev_limit_
Address* v8::internal::HandleScope::prev_limit_ [private]
Definition at line 320 of file handles.h.
prev_next_
Address* v8::internal::HandleScope::prev_next_ [private]
Definition at line 319 of file handles.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/handles.h
/mnt/V8SourceCode/src/handles/handles-inl.h
/mnt/V8SourceCode/src/handles/handles.cc