v8::internal::compiler::turboshaft::SupportedOperations Class Reference
#include <operations.h>
Static Public Member Functions
static void Initialize ()
static bool IsUnalignedLoadSupported (MemoryRepresentation repr)
static bool IsUnalignedStoreSupported (MemoryRepresentation repr)
static bool HasFullUnalignedSupport ()
Static Private Attributes
static bool initialized_
static base::LazyMutex mutex_ = LAZY_MUTEX_INITIALIZER
static SupportedOperations instance_
Detailed Description
Definition at line 1335 of file operations.h.
Member Function Documentation
HasFullUnalignedSupport()
bool v8::internal::compiler::turboshaft::SupportedOperations::HasFullUnalignedSupport () [static]
Definition at line 2077 of file operations.cc.
                                                  {
  return InstructionSelector::AlignmentRequirements().HasFullUnalignedSupport();
}
References v8::internal::compiler::InstructionSelector::AlignmentRequirements(), and v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::HasFullUnalignedSupport().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy().
Initialize()
void v8::internal::compiler::turboshaft::SupportedOperations::Initialize () [static]
Definition at line 2045 of file operations.cc.
                                     {
  base::MutexGuard lock(mutex_.Pointer());
  if (initialized_) return;
  initialized_ = true;
  MachineOperatorBuilder::Flags supported =
      InstructionSelector::SupportedMachineOperatorFlags();
#define SET_SUPPORTED(name, machine_name) \
  instance_.name##_ = supported & MachineOperatorBuilder::Flag::k##machine_name;
  SUPPORTED_OPERATIONS_LIST(SET_SUPPORTED)
#undef SET_SUPPORTED
}
References initialized_, mutex_, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), SET_SUPPORTED, SUPPORTED_OPERATIONS_LIST, and v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags().
Referenced by v8::internal::compiler::turboshaft::Assembler< Reducers >::Assembler().
IsUnalignedLoadSupported()
bool v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported (MemoryRepresentation repr) [static]
Definition at line 2065 of file operations.cc.
                                                                            {
  return InstructionSelector::AlignmentRequirements().IsUnalignedLoadSupported(
      repr.ToMachineType().representation());
}
References v8::internal::compiler::InstructionSelector::AlignmentRequirements(), v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedLoadSupported(), v8::internal::MachineType::representation(), and v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::GetMemoryAccessKind(), v8::internal::compiler::turboshaft::LoadOp::Kind::MaybeUnaligned(), v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeLoad(), v8::internal::compiler::turboshaft::LoadOp::Validate(), and v8::internal::compiler::turboshaft::StoreOp::Validate().
IsUnalignedStoreSupported()
bool v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedStoreSupported (MemoryRepresentation repr) [static]
Definition at line 2071 of file operations.cc.
                                                                             {
  return InstructionSelector::AlignmentRequirements().IsUnalignedStoreSupported(
      repr.ToMachineType().representation());
}
References v8::internal::compiler::InstructionSelector::AlignmentRequirements(), v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedStoreSupported(), v8::internal::MachineType::representation(), and v8::internal::compiler::turboshaft::MemoryRepresentation::ToMachineType().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::SafeStore().
Member Data Documentation
initialized_
bool v8::internal::compiler::turboshaft::SupportedOperations::initialized_ [static], [private]
Definition at line 1356 of file operations.h.
Referenced by Initialize().
instance_
SupportedOperations v8::internal::compiler::turboshaft::SupportedOperations::instance_ [static], [private]
Definition at line 1358 of file operations.h.
mutex_
base::LazyMutex v8::internal::compiler::turboshaft::SupportedOperations::mutex_ = LAZY_MUTEX_INITIALIZER [static], [private]
Definition at line 1357 of file operations.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/operations.h
/mnt/V8SourceCode/src/compiler/turboshaft/operations.cc