v8::internal::SafepointScope Class Reference
#include <safepoint.h>
Public Member Functions
V8_EXPORT_PRIVATE SafepointScope (Isolate *initiator, SafepointKind kind)
V8_EXPORT_PRIVATE SafepointScope (Isolate *initiator, GlobalSafepointForSharedSpaceIsolateTag)
Private Attributes
std::optional< IsolateSafepointScope > isolate_safepoint_
std::optional< GlobalSafepointScope > global_safepoint_
Detailed Description
Definition at line 243 of file safepoint.h.
Constructor & Destructor Documentation
SafepointScope() [1/2]
v8::internal::SafepointScope::SafepointScope (Isolate * initiator, SafepointKind kind) [explicit]
Definition at line 448 of file safepoint.cc.
                                                                     {
  if (kind == SafepointKind::kIsolate) {
    isolate_safepoint_.emplace(initiator->heap());
  } else {
    DCHECK_EQ(kind, SafepointKind::kGlobal);
    global_safepoint_.emplace(initiator);
  }
}
References DCHECK_EQ, global_safepoint_, v8::internal::Isolate::heap(), isolate_safepoint_, v8::internal::kGlobal, and v8::internal::kIsolate.
SafepointScope() [2/2]
v8::internal::SafepointScope::SafepointScope (Isolate * initiator, GlobalSafepointForSharedSpaceIsolateTag) [explicit]
Definition at line 457 of file safepoint.cc.
                                                                        {
  if (initiator->is_shared_space_isolate()) {
    global_safepoint_.emplace(initiator);
  } else {
    isolate_safepoint_.emplace(initiator->heap());
  }
}
References global_safepoint_, v8::internal::Isolate::heap(), v8::internal::Isolate::is_shared_space_isolate(), and isolate_safepoint_.
Member Data Documentation
global_safepoint_
std::optional<GlobalSafepointScope> v8::internal::SafepointScope::global_safepoint_ [private]
Definition at line 252 of file safepoint.h.
Referenced by SafepointScope().
isolate_safepoint_
std::optional<IsolateSafepointScope> v8::internal::SafepointScope::isolate_safepoint_ [private]
Definition at line 251 of file safepoint.h.
Referenced by SafepointScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/safepoint.h
/mnt/V8SourceCode/src/heap/safepoint.cc