v8::internal::PagePool::PoolImpl< PoolEntry > Class Template Reference
Public Member Functions
~PoolImpl ()
void PutLocal (Isolate *isolate, PoolEntry entry)
std::optional< PoolEntry > Get (Isolate *isolate)
bool MoveLocalToShared (Isolate *isolate, InternalTime release_time)
void ReleaseShared ()
void ReleaseLocal ()
void ReleaseLocal (Isolate *isolate)
size_t ReleaseUpTo (InternalTime release_time)
void TearDown ()
size_t Size () const
size_t LocalSize (Isolate *isolate) const
size_t SharedSize () const
Private Attributes
absl::flat_hash_map< Isolate *, std::vector< PoolEntry > > local_pools_
std::vector< std::pair< InternalTime, std::vector< PoolEntry > > > shared_pool_
base::Mutex mutex_
Detailed Description
template<typename PoolEntry>
class v8::internal::PagePool::PoolImpl< PoolEntry >
Definition at line 89 of file page-pool.h.
Constructor & Destructor Documentation
 PoolImpl()
template<typename PoolEntry >
v8::internal::PagePool::PoolImpl< PoolEntry >::~PoolImpl () [inline]
Definition at line 91 of file page-pool.h.
                {
      DCHECK(local_pools_.empty());
      DCHECK(shared_pool_.empty());
    }
References v8::internal::DCHECK(), v8::internal::PagePool::PoolImpl< PoolEntry >::local_pools_, and v8::internal::PagePool::PoolImpl< PoolEntry >::shared_pool_.
Member Function Documentation
Get()
template<typename PoolEntry >
std::optional< PoolEntry > v8::internal::PagePool::PoolImpl< PoolEntry >::Get (Isolate * isolate)
Definition at line 32 of file page-pool.cc.
                                                                        {
  DCHECK_NOT_NULL(isolate);
  base::MutexGuard guard(&mutex_);
  // Try to get a page from the page pool for the given isolate first.
  auto it = local_pools_.find(isolate);
  if (it == local_pools_.end()) {
    // Pages in this pool will be flushed soon. Take them first.
    if (!shared_pool_.empty()) {
      auto& shared_entries = shared_pool_.back().second;
      if (!shared_entries.empty()) {
        PoolEntry shared_entry = std::move(shared_entries.back());
        shared_entries.pop_back();
        if (shared_entries.empty()) {
          shared_pool_.pop_back();
        }
        return {std::move(shared_entry)};
      }
    }
    // Otherwise steal from some other isolate's local pool.
    it = local_pools_.begin();
  }
  if (it != local_pools_.end()) {
    DCHECK(!it->second.empty());
    std::vector<PoolEntry>& entries = it->second;
    if (!entries.empty()) {
      PoolEntry local_entry = std::move(entries.back());
      entries.pop_back();
      if (entries.empty()) {
        local_pools_.erase(it);
      }
      return {std::move(local_entry)};
    }
  }
  return std::nullopt;
}
References v8::internal::DCHECK(), and DCHECK_NOT_NULL.
Referenced by v8::internal::PagePool::Remove().
LocalSize()
template<typename PoolEntry >
size_t v8::internal::PagePool::PoolImpl< PoolEntry >::LocalSize (Isolate * isolate) const
Definition at line 139 of file page-pool.cc.
                                                                    {
  base::MutexGuard guard(&mutex_);
  const auto it = local_pools_.find(isolate);
  return (it != local_pools_.end()) ? it->second.size() : 0;
}
Referenced by v8::internal::PagePool::GetCount().
MoveLocalToShared()
template<typename PoolEntry >
bool v8::internal::PagePool::PoolImpl< PoolEntry >::MoveLocalToShared (Isolate * isolate, InternalTime release_time)
Definition at line 74 of file page-pool.cc.
                                                 {
  base::MutexGuard guard(&mutex_);
  auto it = local_pools_.find(isolate);
  if (it != local_pools_.end()) {
    DCHECK(!it->second.empty());
    shared_pool_.push_back(std::make_pair(release_time, std::move(it->second)));
    local_pools_.erase(it);
  }
  return !shared_pool_.empty();
}
References v8::internal::DCHECK().
Referenced by v8::internal::PagePool::ReleaseOnTearDown().
PutLocal()
template<typename PoolEntry >
void v8::internal::PagePool::PoolImpl< PoolEntry >::PutLocal (Isolate * isolate, PoolEntry entry)
Definition at line 25 of file page-pool.cc.
                                                              {
  base::MutexGuard guard(&mutex_);
  local_pools_[isolate].emplace_back(std::move(entry));
}
Referenced by v8::internal::PagePool::Add().
ReleaseLocal() [1/2]
template<typename PoolEntry >
void v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseLocal ()
Definition at line 98 of file page-pool.cc.
                                               {
  std::vector<std::vector<PoolEntry>> entries_to_free;
  {
    base::MutexGuard page_guard(&mutex_);
    for (auto& entry : local_pools_) {
      entries_to_free.push_back(std::move(entry.second));
    }
    local_pools_.clear();
  }
  // Entries will be freed automatically here.
}
Referenced by v8::internal::PagePool::ReleaseImmediately().
ReleaseLocal() [2/2]
template<typename PoolEntry >
void v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseLocal (Isolate * isolate)
Definition at line 111 of file page-pool.cc.
                                                               {
  std::vector<PoolEntry> entries_to_free;
  {
    base::MutexGuard page_guard(&mutex_);
    const auto it = local_pools_.find(isolate);
    if (it != local_pools_.end()) {
      DCHECK(!it->second.empty());
      entries_to_free = std::move(it->second);
      local_pools_.erase(it);
    }
  }
  // Entries will be freed automatically here.
}
References v8::internal::DCHECK().
ReleaseShared()
template<typename PoolEntry >
void v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseShared ()
Definition at line 87 of file page-pool.cc.
                                                {
  std::vector<std::pair<InternalTime, std::vector<PoolEntry>>> entries_to_free;
  {
    base::MutexGuard guard(&mutex_);
    entries_to_free = std::move(shared_pool_);
    shared_pool_.clear();
  }
  // Entries will be freed automatically here.
}
Referenced by v8::internal::PagePool::ReleaseOnTearDown().
ReleaseUpTo()
template<typename PoolEntry >
size_t v8::internal::PagePool::PoolImpl< PoolEntry >::ReleaseUpTo (InternalTime release_time)
Definition at line 156 of file page-pool.cc.
                                                                         {
  std::vector<std::vector<PoolEntry>> entries_to_free;
  size_t freed = 0;
  {
    base::MutexGuard guard(&mutex_);
    std::erase_if(shared_pool_,
                  [&entries_to_free, &freed, release_time](auto& entry) {
                    if (entry.first <= release_time) {
                      freed += entry.second.size();
                      entries_to_free.push_back(std::move(entry.second));
                      return true;
                    }
                    return false;
                  });
  }
  // Entries will be freed automatically here.
  return freed;
}
References v8::base::erase_if().
Referenced by v8::internal::PagePool::ReleaseUpTo().
SharedSize()
template<typename PoolEntry >
size_t v8::internal::PagePool::PoolImpl< PoolEntry >::SharedSize () const
Definition at line 146 of file page-pool.cc.
                                                     {
  base::MutexGuard guard(&mutex_);
  size_t count = 0;
  for (const auto& entry : shared_pool_) {
    count += entry.second.size();
  }
  return count;
}
Referenced by v8::internal::PagePool::GetSharedCount().
Size()
template<typename PoolEntry >
size_t v8::internal::PagePool::PoolImpl< PoolEntry >::Size () const
Definition at line 126 of file page-pool.cc.
                                               {
  base::MutexGuard guard(&mutex_);
  size_t count = 0;
  for (const auto& entry : local_pools_) {
    count += entry.second.size();
  }
  for (const auto& entry : shared_pool_) {
    count += entry.second.size();
  }
  return count;
}
Referenced by v8::internal::PagePool::GetTotalCount().
TearDown()
template<typename PoolEntry >
void v8::internal::PagePool::PoolImpl< PoolEntry >::TearDown ()
Definition at line 19 of file page-pool.cc.
                                           {
  DCHECK(local_pools_.empty());
  shared_pool_.clear();
}
References v8::internal::DCHECK().
Referenced by v8::internal::PagePool::TearDown().
Member Data Documentation
local_pools_
template<typename PoolEntry >
absl::flat_hash_map<Isolate*, std::vector<PoolEntry> > v8::internal::PagePool::PoolImpl< PoolEntry >::local_pools_ [private]
Definition at line 110 of file page-pool.h.
Referenced by v8::internal::PagePool::PoolImpl< PoolEntry >::~PoolImpl().
mutex_
template<typename PoolEntry >
base::Mutex v8::internal::PagePool::PoolImpl< PoolEntry >::mutex_ [mutable], [private]
Definition at line 114 of file page-pool.h.
shared_pool_
template<typename PoolEntry >
std::vector<std::pair<InternalTime, std::vector<PoolEntry> > > v8::internal::PagePool::PoolImpl< PoolEntry >::shared_pool_ [private]
Definition at line 113 of file page-pool.h.
Referenced by v8::internal::PagePool::PoolImpl< PoolEntry >::~PoolImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/page-pool.h
/mnt/V8SourceCode/src/heap/page-pool.cc