v8::internal::TextElement Class Reference
#include <regexp-ast.h>
Public Types
enum TextType { ATOM
, CLASS_RANGES
 }
Public Member Functions
int cp_offset () const
void set_cp_offset (int cp_offset)
int length () const
TextType text_type () const
RegExpTree * tree () const
RegExpAtom * atom () const
RegExpClassRanges * class_ranges () const
Static Public Member Functions
static TextElement Atom (RegExpAtom *atom)
static TextElement ClassRanges (RegExpClassRanges *class_ranges)
Private Member Functions
TextElement (TextType text_type, RegExpTree *tree)
Private Attributes
int cp_offset_
TextType text_type_
RegExpTree * tree_
Detailed Description
Definition at line 490 of file regexp-ast.h.
Member Enumeration Documentation
TextType
enum v8::internal::TextElement::TextType
Enumerator
ATOM
CLASS_RANGES
Definition at line 492 of file regexp-ast.h.
{ ATOM, CLASS_RANGES };
Constructor & Destructor Documentation
TextElement()
v8::internal::TextElement::TextElement (TextType text_type, RegExpTree * tree) [inline], [private]
Definition at line 516 of file regexp-ast.h.
      : cp_offset_(-1), text_type_(text_type), tree_(tree) {}
Member Function Documentation
atom()
RegExpAtom* v8::internal::TextElement::atom () const [inline]
Definition at line 505 of file regexp-ast.h.
                           {
    DCHECK(text_type() == ATOM);
    return reinterpret_cast<RegExpAtom*>(tree());
  }
References ATOM, v8::internal::DCHECK(), text_type(), and tree().
Referenced by v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), and v8::internal::TextNode::TextEmitPass().
Atom()
TextElement v8::internal::TextElement::Atom (RegExpAtom * atom) [static]
Definition at line 210 of file regexp-compiler.cc.
                                              {
  return TextElement(ATOM, atom);
}
Referenced by v8::internal::RegExpAtom::AppendToText(), v8::internal::TextNode::CreateForSurrogatePair(), and v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms().
class_ranges()
RegExpClassRanges* v8::internal::TextElement::class_ranges () const [inline]
Definition at line 510 of file regexp-ast.h.
                                          {
    DCHECK(text_type() == CLASS_RANGES);
    return reinterpret_cast<RegExpClassRanges*>(tree());
  }
References CLASS_RANGES, v8::internal::DCHECK(), text_type(), and tree().
Referenced by v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::TextNode::MakeCaseIndependent(), and v8::internal::TextNode::TextEmitPass().
ClassRanges()
TextElement v8::internal::TextElement::ClassRanges (RegExpClassRanges * class_ranges) [static]
Definition at line 214 of file regexp-compiler.cc.
                                                                    {
  return TextElement(CLASS_RANGES, class_ranges);
}
Referenced by v8::internal::RegExpClassRanges::AppendToText(), v8::internal::TextNode::CreateForSurrogatePair(), and v8::internal::TextNode::TextNode().
cp_offset()
int v8::internal::TextElement::cp_offset () const [inline]
Definition at line 497 of file regexp-ast.h.
{ return cp_offset_; }
References cp_offset_.
Referenced by v8::internal::TextNode::Length(), set_cp_offset(), and v8::internal::TextNode::TextEmitPass().
length()
int v8::internal::TextElement::length () const
Definition at line 218 of file regexp-compiler.cc.
                              {
  switch (text_type()) {
    case ATOM:
      return atom()->length();
    case CLASS_RANGES:
      return 1;
  }
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::RegExpText::AddElement(), v8::internal::TextNode::CalculateOffsets(), and v8::internal::TextNode::Length().
set_cp_offset()
void v8::internal::TextElement::set_cp_offset (int cp_offset) [inline]
Definition at line 498 of file regexp-ast.h.
{ cp_offset_ = cp_offset; }
References cp_offset(), and cp_offset_.
Referenced by v8::internal::TextNode::CalculateOffsets().
text_type()
TextType v8::internal::TextElement::text_type () const [inline]
Definition at line 501 of file regexp-ast.h.
{ return text_type_; }
References text_type_.
Referenced by atom(), class_ranges(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::TextNode::MakeCaseIndependent(), and v8::internal::TextNode::TextEmitPass().
tree()
RegExpTree* v8::internal::TextElement::tree () const [inline]
Definition at line 503 of file regexp-ast.h.
{ return tree_; }
References tree_.
Referenced by atom(), and class_ranges().
Member Data Documentation
cp_offset_
int v8::internal::TextElement::cp_offset_ [private]
Definition at line 519 of file regexp-ast.h.
Referenced by cp_offset(), and set_cp_offset().
text_type_
TextType v8::internal::TextElement::text_type_ [private]
Definition at line 520 of file regexp-ast.h.
Referenced by text_type().
tree_
RegExpTree* v8::internal::TextElement::tree_ [private]
Definition at line 521 of file regexp-ast.h.
Referenced by tree().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc