v8::internal::OldGenerationMemoryChunkIterator Class Reference
#include <paged-spaces.h>
Public Member Functions
OldGenerationMemoryChunkIterator (Heap *heap)
MutablePageMetadata * next ()
Static Public Member Functions
template<typename Callback >
static void ForAll (Heap *heap, Callback callback)
Private Types
enum State {
kOldSpace
, kCodeSpace
, kLargeObjectSpace
, kCodeLargeObjectSpace
,
kTrustedSpace
, kTrustedLargeObjectSpace
, kFinished
 }
Private Attributes
Heap *const heap_
State state_
std::variant< PageIterator, LargePageIterator > iterator_
Detailed Description
Definition at line 576 of file paged-spaces.h.
Member Enumeration Documentation
State
enum v8::internal::OldGenerationMemoryChunkIterator::State [private]
Enumerator
kOldSpace
kCodeSpace
kLargeObjectSpace
kCodeLargeObjectSpace
kTrustedSpace
kTrustedLargeObjectSpace
kFinished
Definition at line 593 of file paged-spaces.h.
             {
    kOldSpace,
    kCodeSpace,
    kLargeObjectSpace,
    kCodeLargeObjectSpace,
    kTrustedSpace,
    kTrustedLargeObjectSpace,
    kFinished
  };
Constructor & Destructor Documentation
OldGenerationMemoryChunkIterator()
v8::internal::OldGenerationMemoryChunkIterator::OldGenerationMemoryChunkIterator (Heap * heap) [inline], [explicit]
Definition at line 65 of file spaces-inl.h.
    : heap_(heap), state_(kOldSpace), iterator_(heap->old_space()->begin()) {}
Member Function Documentation
ForAll()
template<typename Callback >
static void v8::internal::OldGenerationMemoryChunkIterator::ForAll (Heap * heap, Callback callback) [inline], [static]
Definition at line 585 of file paged-spaces.h.
                                                    {
    OldGenerationMemoryChunkIterator it(heap);
    while (MutablePageMetadata* chunk = it.next()) {
      callback(chunk);
    }
  }
References next().
Referenced by v8::internal::ScavengerCollector::CollectGarbage(), and v8::internal::YoungGenerationRememberedSetsMarkingWorklist::CollectItems().
next()
MutablePageMetadata * v8::internal::OldGenerationMemoryChunkIterator::next () [inline]
Definition at line 68 of file spaces-inl.h.
                                                            {
  switch (state_) {
    case kOldSpace: {
      PageIterator& iterator = std::get<PageIterator>(iterator_);
      if (iterator != heap_->old_space()->end()) return *(iterator++);
      state_ = kCodeSpace;
      iterator_ = heap_->code_space()->begin();
      [[fallthrough]];
    }
    case kCodeSpace: {
      PageIterator& iterator = std::get<PageIterator>(iterator_);
      if (iterator != heap_->code_space()->end()) return *(iterator++);
      state_ = kLargeObjectSpace;
      iterator_ = heap_->lo_space()->begin();
      [[fallthrough]];
    }
    case kLargeObjectSpace: {
      LargePageIterator& iterator = std::get<LargePageIterator>(iterator_);
      if (iterator != heap_->lo_space()->end()) return *(iterator++);
      state_ = kCodeLargeObjectSpace;
      iterator_ = heap_->code_lo_space()->begin();
      [[fallthrough]];
    }
    case kCodeLargeObjectSpace: {
      LargePageIterator& iterator = std::get<LargePageIterator>(iterator_);
      if (iterator != heap_->code_lo_space()->end()) return *(iterator++);
      state_ = kTrustedSpace;
      iterator_ = heap_->trusted_space()->begin();
      [[fallthrough]];
    }
    case kTrustedSpace: {
      PageIterator& iterator = std::get<PageIterator>(iterator_);
      if (iterator != heap_->trusted_space()->end()) return *(iterator++);
      state_ = kTrustedLargeObjectSpace;
      iterator_ = heap_->trusted_lo_space()->begin();
      [[fallthrough]];
    }
    case kTrustedLargeObjectSpace: {
      LargePageIterator& iterator = std::get<LargePageIterator>(iterator_);
      if (iterator != heap_->trusted_lo_space()->end()) return *(iterator++);
      state_ = kFinished;
      [[fallthrough]];
    }
    case kFinished:
      return nullptr;
  }
}
References v8::internal::LargeObjectSpace::begin(), v8::internal::PagedSpaceBase::begin(), v8::internal::Heap::code_lo_space(), v8::internal::Heap::code_space(), v8::internal::LargeObjectSpace::end(), v8::internal::PagedSpaceBase::end(), heap_, iterator_, kCodeLargeObjectSpace, kCodeSpace, kFinished, kLargeObjectSpace, kOldSpace, kTrustedLargeObjectSpace, kTrustedSpace, v8::internal::Heap::lo_space(), v8::internal::Heap::old_space(), state_, v8::internal::Heap::trusted_lo_space(), and v8::internal::Heap::trusted_space().
Referenced by v8::internal::RememberedSet< type >::ClearAll(), ForAll(), v8::internal::RememberedSet< type >::IterateMemoryChunks(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), and v8::internal::HeapLayoutTracer::PrintHeapLayout().
Member Data Documentation
heap_
Heap* const v8::internal::OldGenerationMemoryChunkIterator::heap_ [private]
Definition at line 602 of file paged-spaces.h.
Referenced by next().
iterator_
std::variant<PageIterator, LargePageIterator> v8::internal::OldGenerationMemoryChunkIterator::iterator_ [private]
Definition at line 605 of file paged-spaces.h.
Referenced by next().
state_
State v8::internal::OldGenerationMemoryChunkIterator::state_ [private]
Definition at line 603 of file paged-spaces.h.
Referenced by next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/spaces-inl.h