v8::internal::ObjectEntriesValuesBuiltinsAssembler Class Reference
Public Member Functions
ObjectEntriesValuesBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Types
enum CollectType { kEntries
, kValues
 }
Protected Member Functions
TNode< BoolT > IsPropertyEnumerable (TNode< Uint32T > details)
TNode< BoolT > IsPropertyKindAccessor (TNode< Uint32T > kind)
TNode< BoolT > IsPropertyKindData (TNode< Uint32T > kind)
TNode< Uint32T > LoadPropertyKind (TNode< Uint32T > details)
void GetOwnValuesOrEntries (TNode< Context > context, TNode< Object > maybe_object, CollectType collect_type)
TNode< JSArray > FastGetOwnValuesOrEntries (TNode< Context > context, TNode< JSObject > object, Label *if_call_runtime_with_fast_path, Label *if_no_properties, CollectType collect_type)
TNode< JSArray > FinalizeValuesOrEntriesJSArray (TNode< Context > context, TNode< FixedArray > values_or_entries, TNode< IntPtrT > size, TNode< Map > array_map, Label *if_empty)
Additional Inherited Members
Detailed Description
Definition at line 29 of file builtins-object-gen.cc.
Member Enumeration Documentation
CollectType
enum v8::internal::ObjectEntriesValuesBuiltinsAssembler::CollectType [protected]
Enumerator
kEntries
kValues
Definition at line 36 of file builtins-object-gen.cc.
{ kEntries, kValues };
Constructor & Destructor Documentation
ObjectEntriesValuesBuiltinsAssembler()
v8::internal::ObjectEntriesValuesBuiltinsAssembler::ObjectEntriesValuesBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 31 of file builtins-object-gen.cc.
      : ObjectBuiltinsAssembler(state) {}
Member Function Documentation
FastGetOwnValuesOrEntries()
TNode< JSArray > v8::internal::ObjectEntriesValuesBuiltinsAssembler::FastGetOwnValuesOrEntries (TNode< Context > context, TNode< JSObject > object, Label * if_call_runtime_with_fast_path, Label * if_no_properties, CollectType collect_type) [protected]
Definition at line 195 of file builtins-object-gen.cc.
                              {
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<Map> array_map =
      LoadJSArrayElementsMap(PACKED_ELEMENTS, native_context);
  TNode<Map> map = LoadMap(object);
  TNode<Uint32T> bit_field3 = LoadMapBitField3(map);
  Label if_has_enum_cache(this), if_not_has_enum_cache(this),
      collect_entries(this);
  TNode<IntPtrT> object_enum_length =
      Signed(DecodeWordFromWord32<Map::Bits3::EnumLengthBits>(bit_field3));
  TNode<BoolT> has_enum_cache = WordNotEqual(
      object_enum_length, IntPtrConstant(kInvalidEnumCacheSentinel));
  // In case, we found enum_cache in object,
  // we use it as array_length because it has same size for
  // Object.(entries/values) result array object length.
  // So object_enum_length use less memory space than
  // NumberOfOwnDescriptorsBits value.
  // And in case, if enum_cache_not_found,
  // we call runtime and initialize enum_cache for subsequent call of
  // CSA fast path.
  Branch(has_enum_cache, &if_has_enum_cache, if_call_runtime_with_fast_path);
  BIND(&if_has_enum_cache);
  {
    GotoIf(WordEqual(object_enum_length, IntPtrConstant(0)), if_no_properties);
    TNode<FixedArray> values_or_entries =
        CAST(AllocateFixedArray(PACKED_ELEMENTS, object_enum_length));
    // If in case we have enum_cache,
    // we can't detect accessor of object until loop through descriptors.
    // So if object might have accessor,
    // we will remain invalid addresses of FixedArray.
    // Because in that case, we need to jump to runtime call.
    // So the array filled by the-hole even if enum_cache exists.
    FillFixedArrayWithValue(PACKED_ELEMENTS, values_or_entries,
                            IntPtrConstant(0), object_enum_length,
                            RootIndex::kTheHoleValue);
    TVARIABLE(IntPtrT, var_result_index, IntPtrConstant(0));
    TVARIABLE(IntPtrT, var_descriptor_number, IntPtrConstant(0));
    // Let desc be ? O.[[GetOwnProperty]](key).
    TNode<DescriptorArray> descriptors = LoadMapDescriptors(map);
    Label loop(this, {&var_descriptor_number, &var_result_index}),
        after_loop(this), next_descriptor(this);
    Branch(IntPtrEqual(var_descriptor_number.value(), object_enum_length),
           &after_loop, &loop);
    // We dont use BuildFastLoop.
    // Instead, we use hand-written loop
    // because of we need to use 'continue' functionality.
    BIND(&loop);
    {
      // Currently, we will not invoke getters,
      // so, map will not be changed.
      CSA_DCHECK(this, TaggedEqual(map, LoadMap(object)));
      TNode<IntPtrT> descriptor_entry = var_descriptor_number.value();
      TNode<Name> next_key =
          LoadKeyByDescriptorEntry(descriptors, descriptor_entry);
      // Skip Symbols.
      GotoIf(IsSymbol(next_key), &next_descriptor);
      TNode<Uint32T> details =
          LoadDetailsByDescriptorEntry(descriptors, descriptor_entry);
      TNode<Uint32T> kind = LoadPropertyKind(details);
      // If property is accessor, we escape fast path and call runtime.
      GotoIf(IsPropertyKindAccessor(kind), if_call_runtime_with_fast_path);
      CSA_DCHECK(this, IsPropertyKindData(kind));
      // If desc is not undefined and desc.[[Enumerable]] is true, then skip to
      // the next descriptor.
      GotoIfNot(IsPropertyEnumerable(details), &next_descriptor);
      TVARIABLE(Object, var_property_value, UndefinedConstant());
      TNode<IntPtrT> descriptor_name_index = ToKeyIndex<DescriptorArray>(
          Unsigned(TruncateIntPtrToInt32(var_descriptor_number.value())));
      // Let value be ? Get(O, key).
      LoadPropertyFromFastObject(object, map, descriptors,
                                 descriptor_name_index, details,
                                 &var_property_value);
      // If kind is "value", append value to properties.
      TNode<Object> value = var_property_value.value();
      if (collect_type == CollectType::kEntries) {
        // Let entry be CreateArrayFromList(« key, value »).
        TNode<JSArray> array;
        TNode<FixedArrayBase> elements;
        std::tie(array, elements) = AllocateUninitializedJSArrayWithElements(
            PACKED_ELEMENTS, array_map, SmiConstant(2), std::nullopt,
            IntPtrConstant(2));
        StoreFixedArrayElement(CAST(elements), 0, next_key, SKIP_WRITE_BARRIER);
        StoreFixedArrayElement(CAST(elements), 1, value, SKIP_WRITE_BARRIER);
        value = array;
      }
      StoreFixedArrayElement(values_or_entries, var_result_index.value(),
                             value);
      Increment(&var_result_index);
      Goto(&next_descriptor);
      BIND(&next_descriptor);
      {
        Increment(&var_descriptor_number);
        Branch(IntPtrEqual(var_result_index.value(), object_enum_length),
               &after_loop, &loop);
      }
    }
    BIND(&after_loop);
    return FinalizeValuesOrEntriesJSArray(context, values_or_entries,
                                          var_result_index.value(), array_map,
                                          if_no_properties);
  }
}
References v8::internal::CodeStubAssembler::AllocateFixedArray(), v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), v8::internal::bit_field3, v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::CodeStubAssembler::FillFixedArrayWithValue(), FinalizeValuesOrEntriesJSArray(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::Increment(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), IsPropertyEnumerable(), IsPropertyKindAccessor(), IsPropertyKindData(), v8::internal::kInvalidEnumCacheSentinel, v8::internal::CodeStubAssembler::LoadDetailsByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadKeyByDescriptorEntry(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapBitField3(), v8::internal::CodeStubAssembler::LoadMapDescriptors(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadPropertyFromFastObject(), LoadPropertyKind(), v8::internal::native_context, v8::internal::PACKED_ELEMENTS, v8::internal::compiler::CodeAssembler::Signed(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreFixedArrayElement(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::CodeAssembler::Unsigned(), v8::internal::value, v8::internal::compiler::CodeAssembler::WordEqual(), and v8::internal::compiler::CodeAssembler::WordNotEqual().
Referenced by GetOwnValuesOrEntries().
FinalizeValuesOrEntriesJSArray()
TNode< JSArray > v8::internal::ObjectEntriesValuesBuiltinsAssembler::FinalizeValuesOrEntriesJSArray (TNode< Context > context, TNode< FixedArray > values_or_entries, TNode< IntPtrT > size, TNode< Map > array_map, Label * if_empty) [protected]
Definition at line 319 of file builtins-object-gen.cc.
                                           {
  CSA_DCHECK(this, IsJSArrayMap(array_map));
  GotoIf(IntPtrEqual(size, IntPtrConstant(0)), if_empty);
  TNode<JSArray> array = AllocateJSArray(array_map, result, SmiTag(size));
  return array;
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::CodeStubAssembler::IsJSArrayMap(), v8::base::internal::result, size(), and v8::internal::CodeStubAssembler::SmiTag().
Referenced by FastGetOwnValuesOrEntries().
GetOwnValuesOrEntries()
void v8::internal::ObjectEntriesValuesBuiltinsAssembler::GetOwnValuesOrEntries (TNode< Context > context, TNode< Object > maybe_object, CollectType collect_type) [protected]
Definition at line 136 of file builtins-object-gen.cc.
                              {
  TNode<JSReceiver> receiver = ToObject_Inline(context, maybe_object);
  Label if_call_runtime_with_fast_path(this, Label::kDeferred),
      if_call_runtime(this, Label::kDeferred),
      if_no_properties(this, Label::kDeferred);
  TNode<Map> map = LoadMap(receiver);
  GotoIfNot(IsJSObjectMap(map), &if_call_runtime);
  GotoIfMapHasSlowProperties(map, &if_call_runtime);
  TNode<JSObject> object = CAST(receiver);
  TNode<FixedArrayBase> elements = LoadElements(object);
  // If the object has elements, we treat it as slow case.
  // So, we go to runtime call.
  GotoIfNot(IsEmptyFixedArray(elements), &if_call_runtime_with_fast_path);
  TNode<JSArray> result = FastGetOwnValuesOrEntries(
      context, object, &if_call_runtime_with_fast_path, &if_no_properties,
      collect_type);
  Return(result);
  BIND(&if_no_properties);
  {
    TNode<NativeContext> native_context = LoadNativeContext(context);
    TNode<Map> array_map =
        LoadJSArrayElementsMap(PACKED_ELEMENTS, native_context);
    TNode<JSArray> empty_array = AllocateJSArray(
        PACKED_ELEMENTS, array_map, IntPtrConstant(0), SmiConstant(0));
    Return(empty_array);
  }
  BIND(&if_call_runtime_with_fast_path);
  {
    // In slow case, we simply call runtime.
    if (collect_type == CollectType::kEntries) {
      Return(CallRuntime(Runtime::kObjectEntries, context, object));
    } else {
      DCHECK(collect_type == CollectType::kValues);
      Return(CallRuntime(Runtime::kObjectValues, context, object));
    }
  }
  BIND(&if_call_runtime);
  {
    // In slow case, we simply call runtime.
    if (collect_type == CollectType::kEntries) {
      Return(
          CallRuntime(Runtime::kObjectEntriesSkipFastPath, context, receiver));
    } else {
      DCHECK(collect_type == CollectType::kValues);
      Return(
          CallRuntime(Runtime::kObjectValuesSkipFastPath, context, receiver));
    }
  }
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::DCHECK(), FastGetOwnValuesOrEntries(), v8::internal::CodeStubAssembler::GotoIfMapHasSlowProperties(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IsJSObjectMap(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::PACKED_ELEMENTS, v8::base::internal::result, v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::ToObject_Inline().
IsPropertyEnumerable()
TNode< BoolT > v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyEnumerable (TNode< Uint32T > details) [protected]
Definition at line 117 of file builtins-object-gen.cc.
                            {
  TNode<Uint32T> attributes =
      DecodeWord32<PropertyDetails::AttributesField>(details);
  return IsNotSetWord32(attributes, PropertyAttributes::DONT_ENUM);
}
References v8::internal::DONT_ENUM, and v8::internal::CodeStubAssembler::IsNotSetWord32().
Referenced by FastGetOwnValuesOrEntries().
IsPropertyKindAccessor()
TNode< BoolT > v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyKindAccessor (TNode< Uint32T > kind) [protected]
Definition at line 124 of file builtins-object-gen.cc.
                         {
  return Word32Equal(kind,
                     Int32Constant(static_cast<int>(PropertyKind::kAccessor)));
}
References v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::kAccessor, and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by FastGetOwnValuesOrEntries().
IsPropertyKindData()
TNode< BoolT > v8::internal::ObjectEntriesValuesBuiltinsAssembler::IsPropertyKindData (TNode< Uint32T > kind) [protected]
Definition at line 130 of file builtins-object-gen.cc.
                         {
  return Word32Equal(kind,
                     Int32Constant(static_cast<int>(PropertyKind::kData)));
}
References v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::kData, and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by FastGetOwnValuesOrEntries().
LoadPropertyKind()
TNode<Uint32T> v8::internal::ObjectEntriesValuesBuiltinsAssembler::LoadPropertyKind (TNode< Uint32T > details) [inline], [protected]
Definition at line 44 of file builtins-object-gen.cc.
                                                          {
    return DecodeWord32<PropertyDetails::KindField>(details);
  }
Referenced by FastGetOwnValuesOrEntries().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-object-gen.cc