v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency Class Reference
Public Member Functions
StableMapDependency (MapRef map)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef map_
Additional Inherited Members
Detailed Description
Definition at line 287 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
StableMapDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::StableMapDependency (MapRef map) [inline], [explicit]
Definition at line 289 of file compilation-dependencies.cc.
      : CompilationDependency(kStableMap), map_(map) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 309 of file compilation-dependencies.cc.
                                                                {
    const StableMapDependency* const zat = that->AsStableMap();
    return map_.equals(zat->map_);
  }
References map_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 304 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(map_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 298 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(map_.object(), DependentCode::kPrototypeCheckGroup);
  }
References broker(), v8::internal::DependentCode::kPrototypeCheckGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 292 of file compilation-dependencies.cc.
                                                    {
    // TODO(v8:11670): Consider turn this back into a CHECK inside the
    // constructor and DependOnStableMap, if possible in light of concurrent
    // heap state modifications.
    return !map_.object()->is_dictionary_map() && map_.object()->is_stable();
  }
Member Data Documentation
map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::StableMapDependency::map_ [private]
Definition at line 314 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc