v8::EscapableHandleScopeBase Class Reference
A HandleScope which first allocates a handle in the current scope which will be later filled with the escape value.
#include <v8-local-handle.h>
Public Member Functions
EscapableHandleScopeBase (Isolate *isolate)
~EscapableHandleScopeBase ()=default
EscapableHandleScopeBase (const EscapableHandleScopeBase &)=delete
void operator= (const EscapableHandleScopeBase &)=delete
void * operator new (size_t size)=delete
void * operator new[] (size_t size)=delete
void operator delete (void *, size_t)=delete
void operator delete[] (void *, size_t)=delete
Protected Member Functions
internal::Address * EscapeSlot (internal::Address *escape_value)
Pushes the value into the previous scope and returns a handle to it.
Private Attributes
internal::Address * escape_slot_
Additional Inherited Members
Detailed Description
A HandleScope which first allocates a handle in the current scope which will be later filled with the escape value.
Definition at line 745 of file v8-local-handle.h.
Constructor & Destructor Documentation
EscapableHandleScopeBase() [1/2]
v8::EscapableHandleScopeBase::EscapableHandleScopeBase (Isolate * isolate) [explicit]
Definition at line 755 of file api.cc.
                                                                      {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  escape_slot_ = CreateHandle(
      i_isolate, i::ReadOnlyRoots(i_isolate).the_hole_value().ptr());
  Initialize(v8_isolate);
}
References v8::HandleScope::CreateHandle(), escape_slot_, and v8::HandleScope::Initialize().
 EscapableHandleScopeBase()
v8::EscapableHandleScopeBase::~EscapableHandleScopeBase () [inline], [default]
EscapableHandleScopeBase() [2/2]
v8::EscapableHandleScopeBase::EscapableHandleScopeBase (const EscapableHandleScopeBase &) [delete]
Member Function Documentation
EscapeSlot()
i::Address * v8::EscapableHandleScopeBase::EscapeSlot (internal::Address * escape_value) [protected]
Pushes the value into the previous scope and returns a handle to it.
Cannot be called twice.
Definition at line 762 of file api.cc.
                                                                     {
  DCHECK_NOT_NULL(escape_value);
  DCHECK(i::IsTheHole(i::Tagged<i::Object>(*escape_slot_),
                      reinterpret_cast<i::Isolate*>(GetIsolate())));
  *escape_slot_ = *escape_value;
  return escape_slot_;
}
References DCHECK, DCHECK_NOT_NULL, escape_slot_, and v8::HandleScope::GetIsolate().
operator delete()
void v8::EscapableHandleScopeBase::operator delete (void * , size_t) [delete]
operator delete[]()
void v8::EscapableHandleScopeBase::operator delete[] (void * , size_t) [delete]
operator new()
void* v8::EscapableHandleScopeBase::operator new (size_t size) [delete]
operator new[]()
void* v8::EscapableHandleScopeBase::operator new[] (size_t size) [delete]
operator=()
void v8::EscapableHandleScopeBase::operator= (const EscapableHandleScopeBase &) [delete]
Member Data Documentation
escape_slot_
internal::Address* v8::EscapableHandleScopeBase::escape_slot_ [private]
Definition at line 765 of file v8-local-handle.h.
Referenced by EscapableHandleScopeBase(), and EscapeSlot().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-local-handle.h
/mnt/V8SourceCode/src/api/api.cc