v8::internal::SetOncePointer< T > Class Template Reference
#include <utils.h>
Public Member Functions
SetOncePointer ()=default
bool is_set () const
T * get () const
void set (T *value)
SetOncePointer & operator= (T *value)
bool operator== (std::nullptr_t) const
bool operator!= (std::nullptr_t) const
Private Attributes
T * pointer_ = nullptr
Detailed Description
template<typename T>
class v8::internal::SetOncePointer< T >
Definition at line 328 of file utils.h.
Constructor & Destructor Documentation
SetOncePointer()
template<typename T >
v8::internal::SetOncePointer< T >::SetOncePointer () [default]
Member Function Documentation
get()
template<typename T >
T* v8::internal::SetOncePointer< T >::get () const [inline]
Definition at line 334 of file utils.h.
                 {
    DCHECK_NOT_NULL(pointer_);
    return pointer_;
  }
References DCHECK_NOT_NULL, and v8::internal::SetOncePointer< T >::pointer_.
is_set()
template<typename T >
bool v8::internal::SetOncePointer< T >::is_set () const [inline]
Definition at line 332 of file utils.h.
{ return pointer_ != nullptr; }
References v8::internal::SetOncePointer< T >::pointer_.
operator!=()
template<typename T >
bool v8::internal::SetOncePointer< T >::operator!= (std::nullptr_t) const [inline]
Definition at line 350 of file utils.h.
{ return pointer_ != nullptr; }
References v8::internal::SetOncePointer< T >::pointer_.
operator=()
template<typename T >
SetOncePointer& v8::internal::SetOncePointer< T >::operator= (T * value) [inline]
Definition at line 344 of file utils.h.
                                      {
    set(value);
    return *this;
  }
References v8::internal::SetOncePointer< T >::set(), and v8::internal::value.
operator==()
template<typename T >
bool v8::internal::SetOncePointer< T >::operator== (std::nullptr_t) const [inline]
Definition at line 349 of file utils.h.
{ return pointer_ == nullptr; }
References v8::internal::SetOncePointer< T >::pointer_.
set()
template<typename T >
void v8::internal::SetOncePointer< T >::set (T * value) [inline]
Definition at line 339 of file utils.h.
                     {
    DCHECK(pointer_ == nullptr && value != nullptr);
    pointer_ = value;
  }
References v8::internal::DCHECK(), v8::internal::SetOncePointer< T >::pointer_, and v8::internal::value.
Referenced by v8::internal::SetOncePointer< T >::operator=().
Member Data Documentation
pointer_
template<typename T >
T* v8::internal::SetOncePointer< T >::pointer_ = nullptr [private]
Definition at line 353 of file utils.h.
Referenced by v8::internal::SetOncePointer< T >::get(), v8::internal::SetOncePointer< T >::is_set(), v8::internal::SetOncePointer< T >::operator!=(), v8::internal::SetOncePointer< T >::operator==(), and v8::internal::SetOncePointer< T >::set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/utils.h