v8::internal::JsonStringifier Class Reference
Classes
class NoExtendBuilder
class SimplePropertyKeyCache
Public Member Functions
JsonStringifier (Isolate *isolate)
~JsonStringifier ()
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Stringify (Handle< JSAny > object, Handle< JSAny > replacer, Handle< Object > gap)
Private Types
enum Result { UNCHANGED
, SUCCESS
, EXCEPTION
, NEED_STACK
 }
using KeyObject = std::pair< Handle< Object >, Handle< Object > >
Private Member Functions
bool InitializeReplacer (Handle< JSAny > replacer)
bool InitializeGap (Handle< Object > gap)
V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > ApplyToJsonFunction (Handle< JSAny > object, DirectHandle< Object > key)
V8_WARN_UNUSED_RESULT MaybeHandle< JSAny > ApplyReplacerFunction (Handle< JSAny > value, DirectHandle< Object > key, DirectHandle< Object > initial_holder)
Result SerializeObject (Handle< JSAny > obj)
Result SerializeElement (Isolate *isolate, Handle< JSAny > object, int i)
Result SerializeProperty (Handle< JSAny > object, bool deferred_comma, Handle< String > deferred_key)
template<typename SrcChar , typename DestChar >
void Append (SrcChar c)
void AppendCharacter (uint8_t c)
template<size_t N>
void AppendCStringLiteral (const char(&literal)[N])
template<typename SrcChar >
void AppendCString (const SrcChar *s)
template<typename SrcChar >
void AppendString (std::basic_string_view< SrcChar > s)
bool CurrentPartCanFit (size_t length)
bool EscapedLengthIfCurrentPartFits (size_t length)
void AppendStringByCopy (Tagged< String > string, size_t length, const DisallowGarbageCollection &no_gc)
V8_NOINLINE void AppendString (Handle< String > string_handle)
template<typename SrcChar >
void AppendSubstringByCopy (const SrcChar *src, size_t count)
template<typename SrcChar >
V8_NOINLINE void AppendSubstring (const SrcChar *src, size_t from, size_t to)
bool HasValidCurrentIndex () const
template<bool deferred_string_key>
Result Serialize_ (Handle< JSAny > object, bool comma, Handle< Object > key)
void SerializeDeferredKey (bool deferred_comma, Handle< Object > deferred_key)
Result SerializeSmi (Tagged< Smi > object)
Result SerializeDouble (double number)
Result SerializeHeapNumber (DirectHandle< HeapNumber > object)
Result SerializeJSPrimitiveWrapper (Handle< JSPrimitiveWrapper > object, Handle< Object > key)
Result SerializeJSArray (Handle< JSArray > object, Handle< Object > key)
Result SerializeJSObject (Handle< JSObject > object, Handle< Object > key)
Result SerializeJSProxy (Handle< JSProxy > object, Handle< Object > key)
Result SerializeJSReceiverSlow (DirectHandle< JSReceiver > object)
template<ElementsKind kind>
Result SerializeFixedArrayWithInterruptCheck (DirectHandle< JSArray > array, uint32_t length, uint32_t *slow_path_index)
template<ElementsKind kind>
Result SerializeFixedArrayWithPossibleTransitions (DirectHandle< JSArray > array, uint32_t length, uint32_t *slow_path_index)
template<ElementsKind kind, typename T >
Result SerializeFixedArrayElement (Tagged< T > elements, uint32_t i, Tagged< JSArray > array, bool can_treat_hole_as_undefined)
Result SerializeArrayLikeSlow (DirectHandle< JSReceiver > object, uint32_t start, uint32_t length)
template<bool raw_json>
bool SerializeString (Handle< String > object)
template<typename SrcChar , typename DestChar , bool raw_json>
bool SerializeString_ (Tagged< String > string, const DisallowGarbageCollection &no_gc)
template<typename DestChar >
bool TrySerializeSimplePropertyKey (Tagged< String > string, const DisallowGarbageCollection &no_gc)
void NewLine ()
V8_NOINLINE void NewLineOutline ()
void Indent ()
void Unindent ()
void Separator (bool first)
DirectHandle< JSReceiver > CurrentHolder (DirectHandle< Object > value, DirectHandle< Object > inital_holder)
Result StackPush (Handle< Object > object, Handle< Object > key)
void StackPop ()
Handle< String > ConstructCircularStructureErrorMessage (DirectHandle< Object > last_key, size_t start_index)
Factory * factory ()
V8_NOINLINE void Extend ()
V8_NOINLINE void ChangeEncoding ()
Static Private Member Functions
template<typename SrcChar , typename DestChar , bool raw_json>
static bool SerializeStringUnchecked_ (base::Vector< const SrcChar > src, NoExtendBuilder< DestChar > *dest)
Private Attributes
Isolate * isolate_
String::Encoding encoding_
Handle< FixedArray > property_list_
Handle< JSReceiver > replacer_function_
uint8_t * one_byte_ptr_
base::uc16 * gap_
base::uc16 * two_byte_ptr_
void * part_ptr_
int indent_
size_t part_length_
size_t current_index_
int stack_nesting_level_
bool overflowed_
bool need_stack_
std::vector< KeyObject > stack_
SimplePropertyKeyCache key_cache_
uint8_t one_byte_array_ [kInitialPartLength]
Static Private Attributes
static constexpr int kCircularErrorMessagePrefixCount = 2
static constexpr int kCircularErrorMessagePostfixCount = 1
static constexpr size_t kInitialPartLength = 2048
static constexpr size_t kMaxPartLength = 16 * 1024
static constexpr size_t kPartLengthGrowthFactor = 2
Detailed Description
Definition at line 34 of file json-stringifier.cc.
Member Typedef Documentation
KeyObject
using v8::internal::JsonStringifier::KeyObject = std::pair<Handle<Object>, Handle<Object> > [private]
Definition at line 451 of file json-stringifier.cc.
Member Enumeration Documentation
Result
enum v8::internal::JsonStringifier::Result [private]
Enumerator
UNCHANGED
SUCCESS
EXCEPTION
NEED_STACK
Definition at line 48 of file json-stringifier.cc.
{ UNCHANGED, SUCCESS, EXCEPTION, NEED_STACK };
Constructor & Destructor Documentation
JsonStringifier()
v8::internal::JsonStringifier::JsonStringifier (Isolate * isolate) [explicit]
Definition at line 596 of file json-stringifier.cc.
    : isolate_(isolate),
      encoding_(String::ONE_BYTE_ENCODING),
      gap_(nullptr),
      two_byte_ptr_(nullptr),
      indent_(0),
      part_length_(kInitialPartLength),
      current_index_(0),
      stack_nesting_level_(0),
      overflowed_(false),
      need_stack_(false),
      stack_(),
      key_cache_(isolate) {
  one_byte_ptr_ = one_byte_array_;
  part_ptr_ = one_byte_ptr_;
}
References one_byte_array_, one_byte_ptr_, and part_ptr_.
 JsonStringifier()
v8::internal::JsonStringifier::~JsonStringifier () [inline]
Definition at line 38 of file json-stringifier.cc.
                     {
    if (one_byte_ptr_ != one_byte_array_) delete[] one_byte_ptr_;
    if (two_byte_ptr_) delete[] two_byte_ptr_;
    DeleteArray(gap_);
  }
References gap_, one_byte_array_, one_byte_ptr_, and two_byte_ptr_.
Member Function Documentation
Append()
template<typename SrcChar , typename DestChar >
void v8::internal::JsonStringifier::Append (SrcChar c) [inline], [private]
Definition at line 82 of file json-stringifier.cc.
                                   {
    DCHECK_EQ(encoding_ == String::ONE_BYTE_ENCODING, sizeof(DestChar) == 1);
    if (sizeof(DestChar) == 1) {
      DCHECK_EQ(String::ONE_BYTE_ENCODING, encoding_);
      one_byte_ptr_[current_index_++] = c;
    } else {
      DCHECK_EQ(String::TWO_BYTE_ENCODING, encoding_);
      // Make sure to use unsigned extension even when SrcChar == char.
      two_byte_ptr_[current_index_++] =
          static_cast<std::make_unsigned_t<SrcChar>>(c);
    }
    if V8_UNLIKELY (current_index_ == part_length_) Extend();
  }
References current_index_, DCHECK_EQ, encoding_, Extend(), v8::internal::String::ONE_BYTE_ENCODING, one_byte_ptr_, part_length_, v8::internal::String::TWO_BYTE_ENCODING, two_byte_ptr_, and V8_UNLIKELY.
AppendCharacter()
void v8::internal::JsonStringifier::AppendCharacter (uint8_t c) [inline], [private]
Definition at line 96 of file json-stringifier.cc.
                                            {
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      Append<uint8_t, uint8_t>(c);
    } else {
      Append<uint8_t, base::uc16>(c);
    }
  }
References encoding_, and v8::internal::String::ONE_BYTE_ENCODING.
Referenced by AppendCStringLiteral(), NewLineOutline(), Separator(), SerializeDeferredKey(), SerializeJSArray(), SerializeJSObject(), SerializeJSProxy(), and SerializeJSReceiverSlow().
AppendCString()
template<typename SrcChar >
void v8::internal::JsonStringifier::AppendCString (const SrcChar * s) [inline], [private]
Definition at line 123 of file json-stringifier.cc.
                                                 {
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      while (*s != '\0') Append<SrcChar, uint8_t>(*s++);
    } else {
      while (*s != '\0') Append<SrcChar, base::uc16>(*s++);
    }
  }
References encoding_, and v8::internal::String::ONE_BYTE_ENCODING.
Referenced by AppendCStringLiteral(), NewLineOutline(), and SerializeString_().
AppendCStringLiteral()
template<size_t N>
void v8::internal::JsonStringifier::AppendCStringLiteral (const char(&) literal[N]) [inline], [private]
Definition at line 105 of file json-stringifier.cc.
                                                                {
    // Note that the literal contains the zero char.
    constexpr size_t length = N - 1;
    static_assert(length > 0);
    if (length == 1) return AppendCharacter(literal[0]);
    if (encoding_ == String::ONE_BYTE_ENCODING && CurrentPartCanFit(N)) {
      const uint8_t* chars = reinterpret_cast<const uint8_t*>(literal);
      CopyChars<uint8_t, uint8_t>(one_byte_ptr_ + current_index_, chars,
                                  length);
      current_index_ += length;
      if (current_index_ == part_length_) Extend();
      DCHECK(HasValidCurrentIndex());
      return;
    }
    return AppendCString(literal);
  }
References AppendCharacter(), AppendCString(), current_index_, CurrentPartCanFit(), v8::internal::DCHECK(), encoding_, Extend(), HasValidCurrentIndex(), v8::internal::length, v8::internal::N, v8::internal::String::ONE_BYTE_ENCODING, one_byte_ptr_, and part_length_.
Referenced by Serialize_(), SerializeArrayLikeSlow(), SerializeDouble(), SerializeFixedArrayElement(), SerializeFixedArrayWithPossibleTransitions(), SerializeJSArray(), SerializeJSObject(), SerializeJSPrimitiveWrapper(), and SerializeString_().
AppendString() [1/2]
V8_NOINLINE void v8::internal::JsonStringifier::AppendString (Handle< String > string_handle) [inline], [private]
Definition at line 189 of file json-stringifier.cc.
                                                              {
    {
      DisallowGarbageCollection no_gc;
      Tagged<String> string = *string_handle;
      const bool representation_ok =
          encoding_ == String::TWO_BYTE_ENCODING ||
          (string->IsFlat() &&
           String::IsOneByteRepresentationUnderneath(string));
      if (representation_ok) {
        size_t length = string->length();
        while (!CurrentPartCanFit(length + 1)) {
          Extend();
          if (V8_UNLIKELY(overflowed_)) return;
        }
        AppendStringByCopy(string, length, no_gc);
        return;
      }
    }
    SerializeString<true>(string_handle);
  }
References AppendStringByCopy(), CurrentPartCanFit(), encoding_, Extend(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, overflowed_, v8::internal::String::TWO_BYTE_ENCODING, and V8_UNLIKELY.
AppendString() [2/2]
template<typename SrcChar >
void v8::internal::JsonStringifier::AppendString (std::basic_string_view< SrcChar > s) [inline], [private]
Definition at line 132 of file json-stringifier.cc.
                                                               {
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      for (SrcChar c : s) Append<SrcChar, uint8_t>(c);
    } else {
      for (SrcChar c : s) Append<SrcChar, base::uc16>(c);
    }
  }
References encoding_, and v8::internal::String::ONE_BYTE_ENCODING.
Referenced by Serialize_(), SerializeDouble(), SerializeSmi(), and SerializeString_().
AppendStringByCopy()
void v8::internal::JsonStringifier::AppendStringByCopy (Tagged< String > string, size_t length, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 156 of file json-stringifier.cc.
                                                                  {
    DCHECK_EQ(length, string->length());
    DCHECK(encoding_ == String::TWO_BYTE_ENCODING ||
           (string->IsFlat() &&
            String::IsOneByteRepresentationUnderneath(string)));
    DCHECK(CurrentPartCanFit(length + 1));
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      if (String::IsOneByteRepresentationUnderneath(string)) {
        CopyChars<uint8_t, uint8_t>(
            one_byte_ptr_ + current_index_,
            string->GetCharVector<uint8_t>(no_gc).begin(), length);
      } else {
        ChangeEncoding();
        CopyChars<uint16_t, uint16_t>(
            two_byte_ptr_ + current_index_,
            string->GetCharVector<uint16_t>(no_gc).begin(), length);
      }
    } else {
      if (String::IsOneByteRepresentationUnderneath(string)) {
        CopyChars<uint8_t, uint16_t>(
            two_byte_ptr_ + current_index_,
            string->GetCharVector<uint8_t>(no_gc).begin(), length);
      } else {
        CopyChars<uint16_t, uint16_t>(
            two_byte_ptr_ + current_index_,
            string->GetCharVector<uint16_t>(no_gc).begin(), length);
      }
    }
    current_index_ += length;
    DCHECK(current_index_ <= part_length_);
  }
References ChangeEncoding(), current_index_, CurrentPartCanFit(), v8::internal::DCHECK(), DCHECK_EQ, encoding_, v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::ONE_BYTE_ENCODING, one_byte_ptr_, part_length_, v8::internal::string, v8::internal::String::TWO_BYTE_ENCODING, and two_byte_ptr_.
Referenced by AppendString().
AppendSubstring()
template<typename SrcChar >
V8_NOINLINE void v8::internal::JsonStringifier::AppendSubstring (const SrcChar * src, size_t from, size_t to) [inline], [private]
Definition at line 230 of file json-stringifier.cc.
                                                                               {
    if (from == to) return;
    DCHECK_LT(from, to);
    size_t count = to - from;
    while (!CurrentPartCanFit(count + 1)) {
      Extend();
      if (V8_UNLIKELY(overflowed_)) return;
    }
    AppendSubstringByCopy(src + from, count);
  }
References AppendSubstringByCopy(), CurrentPartCanFit(), DCHECK_LT, Extend(), overflowed_, and V8_UNLIKELY.
Referenced by SerializeString_().
AppendSubstringByCopy()
template<typename SrcChar >
void v8::internal::JsonStringifier::AppendSubstringByCopy (const SrcChar * src, size_t count) [inline], [private]
Definition at line 211 of file json-stringifier.cc.
                                                               {
    DCHECK(CurrentPartCanFit(count + 1));
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      if (sizeof(SrcChar) == 1) {
        CopyChars<SrcChar, uint8_t>(one_byte_ptr_ + current_index_, src, count);
      } else {
        ChangeEncoding();
        CopyChars<SrcChar, base::uc16>(two_byte_ptr_ + current_index_, src,
                                       count);
      }
    } else {
      CopyChars<SrcChar, base::uc16>(two_byte_ptr_ + current_index_, src,
                                     count);
    }
    current_index_ += count;
    DCHECK_LE(current_index_, part_length_);
  }
References ChangeEncoding(), current_index_, CurrentPartCanFit(), v8::internal::DCHECK(), DCHECK_LE, encoding_, v8::internal::String::ONE_BYTE_ENCODING, one_byte_ptr_, part_length_, and two_byte_ptr_.
Referenced by AppendSubstring().
ApplyReplacerFunction()
MaybeHandle< JSAny > v8::internal::JsonStringifier::ApplyReplacerFunction (Handle< JSAny > value, DirectHandle< Object > key, DirectHandle< Object > initial_holder) [private]
Definition at line 762 of file json-stringifier.cc.
                                         {
  HandleScope scope(isolate_);
  if (IsSmi(*key)) key = factory()->SmiToString(Cast<Smi>(*key));
  DirectHandle<Object> args[] = {key, value};
  DirectHandle<JSReceiver> holder = CurrentHolder(value, initial_holder);
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate_, value,
      Cast<JSAny>(Execution::Call(isolate_, replacer_function_, holder,
                                  base::VectorOf(args))));
  return scope.CloseAndEscape(value);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), CurrentHolder(), factory(), isolate_, v8::internal::IsSmi(), v8::internal::key, replacer_function_, v8::internal::FactoryBase< Impl >::SmiToString(), v8::internal::value, and v8::base::VectorOf().
Referenced by Serialize_().
ApplyToJsonFunction()
MaybeHandle< JSAny > v8::internal::JsonStringifier::ApplyToJsonFunction (Handle< JSAny > object, DirectHandle< Object > key) [private]
Definition at line 741 of file json-stringifier.cc.
                                                    {
  HandleScope scope(isolate_);
  // Retrieve toJSON function. The LookupIterator automatically handles
  // the ToObject() equivalent ("GetRoot") if {object} is a BigInt.
  DirectHandle<Object> fun;
  LookupIterator it(isolate_, object, factory()->toJSON_string(),
                    LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  ASSIGN_RETURN_ON_EXCEPTION(isolate_, fun, Object::GetProperty(&it));
  if (!IsCallable(*fun)) return object;
  // Call toJSON function.
  if (IsSmi(*key)) key = factory()->SmiToString(Cast<Smi>(*key));
  DirectHandle<Object> args[] = {key};
  ASSIGN_RETURN_ON_EXCEPTION(isolate_, object,
                             Cast<JSAny>(Execution::Call(
                                 isolate_, fun, object, base::VectorOf(args))));
  return scope.CloseAndEscape(object);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), factory(), v8::internal::Object::GetProperty(), isolate_, v8::internal::IsSmi(), v8::internal::key, v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, v8::internal::FactoryBase< Impl >::SmiToString(), and v8::base::VectorOf().
Referenced by Serialize_().
ChangeEncoding()
void v8::internal::JsonStringifier::ChangeEncoding () [private]
Definition at line 1793 of file json-stringifier.cc.
                                     {
  encoding_ = String::TWO_BYTE_ENCODING;
  two_byte_ptr_ = new base::uc16[part_length_];
  for (uint32_t i = 0; i < current_index_; i++) {
    two_byte_ptr_[i] = one_byte_ptr_[i];
  }
  part_ptr_ = two_byte_ptr_;
  if (one_byte_ptr_ != one_byte_array_) delete[] one_byte_ptr_;
  one_byte_ptr_ = nullptr;
}
References current_index_, encoding_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, one_byte_array_, one_byte_ptr_, part_length_, part_ptr_, v8::internal::String::TWO_BYTE_ENCODING, and two_byte_ptr_.
Referenced by AppendStringByCopy(), AppendSubstringByCopy(), InitializeGap(), and SerializeString().
ConstructCircularStructureErrorMessage()
Handle< String > v8::internal::JsonStringifier::ConstructCircularStructureErrorMessage (DirectHandle< Object > last_key, size_t start_index) [private]
Definition at line 909 of file json-stringifier.cc.
                                                       {
  DCHECK(start_index < stack_.size());
  CircularStructureMessageBuilder builder(isolate_);
  // We track the index to be printed next for better readability.
  size_t index = start_index;
  const size_t stack_size = stack_.size();
  builder.AppendStartLine(stack_[index++].second);
  // Append a maximum of kCircularErrorMessagePrefixCount normal lines.
  const size_t prefix_end =
      std::min(stack_size, index + kCircularErrorMessagePrefixCount);
  for (; index < prefix_end; ++index) {
    builder.AppendNormalLine(stack_[index].first, stack_[index].second);
  }
  // If the circle consists of too many objects, we skip them and just
  // print an ellipsis.
  if (stack_size > index + kCircularErrorMessagePostfixCount) {
    builder.AppendEllipsis();
  }
  // Since we calculate the postfix lines from the back of the stack,
  // we have to ensure that lines are not printed twice.
  index = std::max(index, stack_size - kCircularErrorMessagePostfixCount);
  for (; index < stack_size; ++index) {
    builder.AppendNormalLine(stack_[index].first, stack_[index].second);
  }
  builder.AppendClosingLine(last_key);
  Handle<String> result;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate_, result,
                                   indirect_handle(builder.Finish(), isolate_),
                                   factory()->empty_string());
  return result;
}
References v8::internal::CircularStructureMessageBuilder::AppendClosingLine(), v8::internal::CircularStructureMessageBuilder::AppendEllipsis(), v8::internal::CircularStructureMessageBuilder::AppendNormalLine(), v8::internal::CircularStructureMessageBuilder::AppendStartLine(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), factory(), v8::internal::CircularStructureMessageBuilder::Finish(), v8::internal::index, v8::internal::indirect_handle(), isolate_, kCircularErrorMessagePostfixCount, kCircularErrorMessagePrefixCount, v8::base::internal::result, and stack_.
Referenced by StackPush().
CurrentHolder()
DirectHandle< JSReceiver > v8::internal::JsonStringifier::CurrentHolder (DirectHandle< Object > value, DirectHandle< Object > inital_holder) [private]
Definition at line 776 of file json-stringifier.cc.
                                                                     {
  if (stack_.empty()) {
    DirectHandle<JSObject> holder =
        factory()->NewJSObject(isolate_->object_function());
    JSObject::AddProperty(isolate_, holder, factory()->empty_string(),
                          initial_holder, NONE);
    return holder;
  } else {
    return DirectHandle<JSReceiver>(Cast<JSReceiver>(*stack_.back().second),
                                    isolate_);
  }
}
References v8::internal::JSObject::AddProperty(), factory(), isolate_, v8::internal::Factory::NewJSObject(), v8::internal::NONE, and stack_.
Referenced by ApplyReplacerFunction().
CurrentPartCanFit()
bool v8::internal::JsonStringifier::CurrentPartCanFit (size_t length) [inline], [private]
Definition at line 140 of file json-stringifier.cc.
                                                  {
    return part_length_ - current_index_ > length;
  }
References current_index_, v8::internal::length, and part_length_.
Referenced by AppendCStringLiteral(), AppendString(), AppendStringByCopy(), AppendSubstring(), AppendSubstringByCopy(), EscapedLengthIfCurrentPartFits(), and TrySerializeSimplePropertyKey().
EscapedLengthIfCurrentPartFits()
bool v8::internal::JsonStringifier::EscapedLengthIfCurrentPartFits (size_t length) [inline], [private]
Definition at line 148 of file json-stringifier.cc.
                                                               {
    if (length > kMaxPartLength) return false;
    static_assert(kMaxPartLength <= (String::kMaxLength >> 3));
    // This shift will not overflow because length is already less than the
    // maximum part length.
    return CurrentPartCanFit(length << 3);
  }
References CurrentPartCanFit(), v8::internal::String::kMaxLength, kMaxPartLength, and v8::internal::length.
Referenced by SerializeString_().
Extend()
void v8::internal::JsonStringifier::Extend () [private]
Definition at line 1768 of file json-stringifier.cc.
                             {
  if (part_length_ >= String::kMaxLength) {
    // Set the flag and carry on. Delay throwing the exception till the end.
    current_index_ = 0;
    overflowed_ = true;
    return;
  }
  part_length_ *= kPartLengthGrowthFactor;
  if (encoding_ == String::ONE_BYTE_ENCODING) {
    uint8_t* tmp_ptr = new uint8_t[part_length_];
    memcpy(tmp_ptr, one_byte_ptr_, current_index_);
    if (one_byte_ptr_ != one_byte_array_) delete[] one_byte_ptr_;
    one_byte_ptr_ = tmp_ptr;
    part_ptr_ = one_byte_ptr_;
  } else {
    base::uc16* tmp_ptr = new base::uc16[part_length_];
    for (uint32_t i = 0; i < current_index_; i++) {
      tmp_ptr[i] = two_byte_ptr_[i];
    }
    delete[] two_byte_ptr_;
    two_byte_ptr_ = tmp_ptr;
    part_ptr_ = two_byte_ptr_;
  }
}
References current_index_, encoding_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::String::kMaxLength, kPartLengthGrowthFactor, one_byte_array_, v8::internal::String::ONE_BYTE_ENCODING, one_byte_ptr_, overflowed_, part_length_, part_ptr_, and two_byte_ptr_.
Referenced by Append(), AppendCStringLiteral(), AppendString(), and AppendSubstring().
factory()
Factory* v8::internal::JsonStringifier::factory () [inline], [private]
Definition at line 431 of file json-stringifier.cc.
{ return isolate_->factory(); }
References v8::internal::Isolate::factory(), and isolate_.
Referenced by ApplyReplacerFunction(), ApplyToJsonFunction(), ConstructCircularStructureErrorMessage(), CurrentHolder(), InitializeReplacer(), Serialize_(), SerializeJSPrimitiveWrapper(), SerializeObject(), StackPush(), and Stringify().
HasValidCurrentIndex()
bool v8::internal::JsonStringifier::HasValidCurrentIndex () const [inline], [private]
Definition at line 241 of file json-stringifier.cc.
{ return current_index_ < part_length_; }
References current_index_, and part_length_.
Referenced by AppendCStringLiteral().
Indent()
void v8::internal::JsonStringifier::Indent () [inline], [private]
Definition at line 408 of file json-stringifier.cc.
{ indent_++; }
References indent_.
Referenced by SerializeJSArray(), SerializeJSObject(), SerializeJSProxy(), and SerializeJSReceiverSlow().
InitializeGap()
bool v8::internal::JsonStringifier::InitializeGap (Handle< Object > gap) [private]
Definition at line 700 of file json-stringifier.cc.
                                                      {
  DCHECK_NULL(gap_);
  HandleScope scope(isolate_);
  if (IsJSPrimitiveWrapper(*gap)) {
    DirectHandle<Object> value(Cast<JSPrimitiveWrapper>(gap)->value(),
                               isolate_);
    if (IsString(*value)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate_, gap,
                                       Object::ToString(isolate_, gap), false);
    } else if (IsNumber(*value)) {
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate_, gap,
                                       Object::ToNumber(isolate_, gap), false);
    }
  }
  if (IsString(*gap)) {
    auto gap_string = Cast<String>(gap);
    if (gap_string->length() > 0) {
      uint32_t gap_length = std::min(gap_string->length(), 10u);
      gap_ = NewArray<base::uc16>(gap_length + 1);
      String::WriteToFlat(*gap_string, gap_, 0, gap_length);
      for (uint32_t i = 0; i < gap_length; i++) {
        if (gap_[i] > String::kMaxOneByteCharCode) {
          ChangeEncoding();
          break;
        }
      }
      gap_[gap_length] = '\0';
    }
  } else if (IsNumber(*gap)) {
    double value = std::min(Object::NumberValue(*gap), 10.0);
    if (value > 0) {
      uint32_t gap_length = DoubleToUint32(value);
      gap_ = NewArray<base::uc16>(gap_length + 1);
      for (uint32_t i = 0; i < gap_length; i++) gap_[i] = ' ';
      gap_[gap_length] = '\0';
    }
  }
  return true;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, ChangeEncoding(), DCHECK_NULL, v8::internal::DoubleToUint32(), gap_, v8::internal::IsNumber(), isolate_, v8::internal::String::kMaxOneByteCharCode, v8::internal::Object::NumberValue(), v8::Value::ToNumber(), v8::Value::ToString(), v8::internal::value, and v8::internal::String::WriteToFlat().
Referenced by Stringify().
InitializeReplacer()
bool v8::internal::JsonStringifier::InitializeReplacer (Handle< JSAny > replacer) [private]
Definition at line 650 of file json-stringifier.cc.
                                                               {
  DCHECK(property_list_.is_null());
  DCHECK(replacer_function_.is_null());
  Maybe<bool> is_array = Object::IsArray(replacer);
  if (is_array.IsNothing()) return false;
  if (is_array.FromJust()) {
    HandleScope handle_scope(isolate_);
    Handle<OrderedHashSet> set = factory()->NewOrderedHashSet();
    DirectHandle<Object> length_obj;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, length_obj,
        Object::GetLengthFromArrayLike(isolate_, Cast<JSReceiver>(replacer)),
        false);
    uint32_t length;
    if (!Object::ToUint32(*length_obj, &length)) length = kMaxUInt32;
    for (uint32_t i = 0; i < length; i++) {
      Handle<Object> element;
      Handle<String> key;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate_, element, Object::GetElement(isolate_, replacer, i), false);
      if (IsNumber(*element) || IsString(*element)) {
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate_, key, Object::ToString(isolate_, element), false);
      } else if (IsJSPrimitiveWrapper(*element)) {
        DirectHandle<Object> value(Cast<JSPrimitiveWrapper>(element)->value(),
                                   isolate_);
        if (IsNumber(*value) || IsString(*value)) {
          ASSIGN_RETURN_ON_EXCEPTION_VALUE(
              isolate_, key, Object::ToString(isolate_, element), false);
        }
      }
      if (key.is_null()) continue;
      // Object keys are internalized, so do it here.
      key = factory()->InternalizeString(key);
      MaybeHandle<OrderedHashSet> set_candidate =
          OrderedHashSet::Add(isolate_, set, key);
      if (!set_candidate.ToHandle(&set)) {
        CHECK(isolate_->has_exception());
        return false;
      }
    }
    property_list_ = OrderedHashSet::ConvertToKeysArray(
        isolate_, set, GetKeysConversion::kKeepNumbers);
    property_list_ = handle_scope.CloseAndEscape(property_list_);
  } else if (IsCallable(*replacer)) {
    replacer_function_ = Cast<JSReceiver>(replacer);
  }
  return true;
}
References v8::bigint::Add(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::OrderedHashSet::ConvertToKeysArray(), v8::internal::DCHECK(), factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetElement(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::Isolate::has_exception(), v8::internal::Factory::InternalizeString(), v8::internal::Object::IsArray(), v8::Maybe< T >::IsNothing(), v8::internal::IsNumber(), isolate_, v8::internal::key, v8::internal::kKeepNumbers, v8::internal::kMaxUInt32, v8::internal::length, v8::internal::Factory::NewOrderedHashSet(), property_list_, replacer_function_, v8::internal::MaybeHandle< T >::ToHandle(), v8::Value::ToString(), v8::internal::Object::ToUint32(), and v8::internal::value.
Referenced by Stringify().
NewLine()
void v8::internal::JsonStringifier::NewLine () [inline], [private]
Definition at line 1709 of file json-stringifier.cc.
                              {
  if (gap_ == nullptr) return;
  NewLineOutline();
}
References gap_, and NewLineOutline().
Referenced by Separator(), SerializeJSArray(), SerializeJSObject(), SerializeJSProxy(), and SerializeJSReceiverSlow().
NewLineOutline()
void v8::internal::JsonStringifier::NewLineOutline () [private]
Definition at line 1714 of file json-stringifier.cc.
                                     {
  AppendCharacter('\n');
  for (int i = 0; i < indent_; i++) AppendCString(gap_);
}
References AppendCharacter(), AppendCString(), gap_, and indent_.
Referenced by NewLine().
Separator()
void v8::internal::JsonStringifier::Separator (bool first) [inline], [private]
Definition at line 1719 of file json-stringifier.cc.
                                          {
  if (!first) AppendCharacter(',');
  NewLine();
}
References AppendCharacter(), and NewLine().
Referenced by SerializeArrayLikeSlow(), SerializeDeferredKey(), SerializeFixedArrayElement(), and SerializeFixedArrayWithPossibleTransitions().
Serialize_()
template<bool deferred_string_key>
JsonStringifier::Result v8::internal::JsonStringifier::Serialize_ (Handle< JSAny > object, bool comma, Handle< Object > key) [private]
Definition at line 960 of file json-stringifier.cc.
                                                                        {
  StackLimitCheck interrupt_check(isolate_);
  if (interrupt_check.InterruptRequested() &&
      IsException(isolate_->stack_guard()->HandleInterrupts(), isolate_)) {
    return EXCEPTION;
  }
  DirectHandle<JSAny> initial_value = object;
  PtrComprCageBase cage_base(isolate_);
  if (!IsSmi(*object)) {
    InstanceType instance_type =
        Cast<HeapObject>(*object)->map(cage_base)->instance_type();
    if ((InstanceTypeChecker::IsJSReceiver(instance_type) &&
         MayHaveInterestingProperties(isolate_, Cast<JSReceiver>(*object))) ||
        InstanceTypeChecker::IsBigInt(instance_type)) {
      if (!need_stack_ && stack_nesting_level_ > 0) {
        need_stack_ = true;
        return NEED_STACK;
      }
      need_stack_ = true;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate_, object, ApplyToJsonFunction(object, key), EXCEPTION);
    }
  }
  if (!replacer_function_.is_null()) {
    need_stack_ = true;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, object, ApplyReplacerFunction(object, key, initial_value),
        EXCEPTION);
  }
  if (IsSmi(*object)) {
    if (deferred_string_key) SerializeDeferredKey(comma, key);
    return SerializeSmi(Cast<Smi>(*object));
  }
  InstanceType instance_type =
      Cast<HeapObject>(*object)->map(cage_base)->instance_type();
  switch (instance_type) {
    case HEAP_NUMBER_TYPE:
      if (deferred_string_key) SerializeDeferredKey(comma, key);
      return SerializeHeapNumber(Cast<HeapNumber>(object));
    case BIGINT_TYPE:
      isolate_->Throw(
          *factory()->NewTypeError(MessageTemplate::kBigIntSerializeJSON));
      return EXCEPTION;
    case ODDBALL_TYPE:
      switch (Cast<Oddball>(*object)->kind()) {
        case Oddball::kFalse:
          if (deferred_string_key) SerializeDeferredKey(comma, key);
          AppendCStringLiteral("false");
          return SUCCESS;
        case Oddball::kTrue:
          if (deferred_string_key) SerializeDeferredKey(comma, key);
          AppendCStringLiteral("true");
          return SUCCESS;
        case Oddball::kNull:
          if (deferred_string_key) SerializeDeferredKey(comma, key);
          AppendCStringLiteral("null");
          return SUCCESS;
        default:
          return UNCHANGED;
      }
    case JS_ARRAY_TYPE:
      if (deferred_string_key) SerializeDeferredKey(comma, key);
      return SerializeJSArray(Cast<JSArray>(object), key);
    case JS_PRIMITIVE_WRAPPER_TYPE:
      if (!need_stack_) {
        need_stack_ = true;
        return NEED_STACK;
      }
      if (deferred_string_key) SerializeDeferredKey(comma, key);
      return SerializeJSPrimitiveWrapper(Cast<JSPrimitiveWrapper>(object), key);
    case SYMBOL_TYPE:
      return UNCHANGED;
    case JS_RAW_JSON_TYPE:
      if (deferred_string_key) SerializeDeferredKey(comma, key);
      {
        DirectHandle<JSRawJson> raw_json_obj = Cast<JSRawJson>(object);
        Handle<String> raw_json;
        if (raw_json_obj->HasInitialLayout(isolate_)) {
          // Fast path: the object returned by JSON.rawJSON has its initial map
          // intact.
          raw_json = Cast<String>(handle(
              raw_json_obj->InObjectPropertyAt(JSRawJson::kRawJsonInitialIndex),
              isolate_));
        } else {
          // Slow path: perform a property get for "rawJSON". Because raw JSON
          // objects are created frozen, it is still guaranteed that there will
          // be a property named "rawJSON" that is a String. Their initial maps
          // only change due to VM-internal operations like being optimized for
          // being used as a prototype.
          raw_json = Cast<String>(
              JSObject::GetProperty(isolate_, raw_json_obj,
                                    isolate_->factory()->raw_json_string())
                  .ToHandleChecked());
        }
        AppendString(raw_json);
      }
      return SUCCESS;
    case HOLE_TYPE:
      UNREACHABLE();
#if V8_ENABLE_WEBASSEMBLY
    case WASM_STRUCT_TYPE:
    case WASM_ARRAY_TYPE:
      return UNCHANGED;
#endif
    default:
      if (InstanceTypeChecker::IsString(instance_type)) {
        if (deferred_string_key) SerializeDeferredKey(comma, key);
        SerializeString<false>(Cast<String>(object));
        return SUCCESS;
      } else {
        // Make sure that we have a JSReceiver before we cast it to one.
        // If we ever leak an internal object that is not a JSReceiver it could
        // end up here and lead to a type confusion.
        CHECK(IsJSReceiver(*object));
        if (IsCallable(Cast<HeapObject>(*object), cage_base)) return UNCHANGED;
        // Go to slow path for global proxy and objects requiring access checks.
        if (deferred_string_key) SerializeDeferredKey(comma, key);
        if (InstanceTypeChecker::IsJSProxy(instance_type)) {
          return SerializeJSProxy(Cast<JSProxy>(object), key);
        }
        // WASM_{STRUCT,ARRAY}_TYPE are handled in `case:` blocks above.
        DCHECK(IsJSObject(*object));
        return SerializeJSObject(Cast<JSObject>(object), key);
      }
  }
  UNREACHABLE();
}
References AppendCStringLiteral(), AppendString(), ApplyReplacerFunction(), ApplyToJsonFunction(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::BIGINT_TYPE, CHECK, v8::internal::DCHECK(), EXCEPTION, v8::internal::Isolate::factory(), factory(), v8::internal::handle(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::StackLimitCheck::InterruptRequested(), isolate_, v8::internal::IsSmi(), v8::internal::key, v8::internal::Oddball::kFalse, v8::internal::Oddball::kNull, v8::internal::JSRawJson::kRawJsonInitialIndex, v8::internal::Oddball::kTrue, v8::internal::MayHaveInterestingProperties(), NEED_STACK, need_stack_, replacer_function_, SerializeDeferredKey(), SerializeHeapNumber(), SerializeJSArray(), SerializeJSObject(), SerializeJSPrimitiveWrapper(), SerializeJSProxy(), SerializeSmi(), v8::internal::Isolate::stack_guard(), stack_nesting_level_, SUCCESS, v8::internal::Isolate::Throw(), UNCHANGED, and v8::internal::UNREACHABLE().
SerializeArrayLikeSlow()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeArrayLikeSlow (DirectHandle< JSReceiver > object, uint32_t start, uint32_t length) [private]
Definition at line 1317 of file json-stringifier.cc.
                                                                      {
  if (!need_stack_) {
    need_stack_ = true;
    return NEED_STACK;
  }
  // We need to write out at least two characters per array element.
  static constexpr uint32_t kMaxSerializableArrayLength =
      String::kMaxLength / 2;
  if (length > kMaxSerializableArrayLength) {
    isolate_->Throw(*isolate_->factory()->NewInvalidStringLengthError());
    return EXCEPTION;
  }
  HandleScope handle_scope(isolate_);
  for (uint32_t i = start; i < length; i++) {
    Separator(i == 0);
    Handle<Object> element;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, element, JSReceiver::GetElement(isolate_, object, i),
        EXCEPTION);
    Result result = SerializeElement(isolate_, Cast<JSAny>(element), i);
    if (result == SUCCESS) continue;
    if (result == UNCHANGED) {
      // Detect overflow sooner for large sparse arrays.
      if (overflowed_) {
        isolate_->Throw(*isolate_->factory()->NewInvalidStringLengthError());
        return EXCEPTION;
      }
      AppendCStringLiteral("null");
    } else {
      return result;
    }
  }
  return SUCCESS;
}
References AppendCStringLiteral(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, EXCEPTION, v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetElement(), isolate_, v8::internal::String::kMaxLength, v8::internal::length, NEED_STACK, need_stack_, v8::internal::Factory::NewInvalidStringLengthError(), overflowed_, v8::base::internal::result, Separator(), SerializeElement(), SUCCESS, v8::internal::Isolate::Throw(), and UNCHANGED.
Referenced by SerializeJSArray(), and SerializeJSProxy().
SerializeDeferredKey()
void v8::internal::JsonStringifier::SerializeDeferredKey (bool deferred_comma, Handle< Object > deferred_key) [inline], [private]
Definition at line 1724 of file json-stringifier.cc.
                                                                        {
  Separator(!deferred_comma);
  Handle<String> string_key = Cast<String>(deferred_key);
  bool wrote_simple = false;
  {
    DisallowGarbageCollection no_gc;
    wrote_simple =
        encoding_ == String::ONE_BYTE_ENCODING
            ? TrySerializeSimplePropertyKey<uint8_t>(*string_key, no_gc)
            : TrySerializeSimplePropertyKey<base::uc16>(*string_key, no_gc);
  }
  if (!wrote_simple) {
    bool required_escaping = SerializeString<false>(string_key);
    if (!required_escaping) {
      key_cache_.TryInsert(*string_key);
    }
    AppendCharacter(':');
  }
  if (gap_ != nullptr) AppendCharacter(' ');
}
References AppendCharacter(), encoding_, gap_, key_cache_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::ONE_BYTE_ENCODING, Separator(), and v8::internal::JsonStringifier::SimplePropertyKeyCache::TryInsert().
Referenced by Serialize_().
SerializeDouble()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeDouble (double number) [private]
Definition at line 1136 of file json-stringifier.cc.
                                                                    {
  if (std::isinf(number) || std::isnan(number)) {
    AppendCStringLiteral("null");
    return SUCCESS;
  }
  static constexpr uint32_t kBufferSize = 100;
  char chars[kBufferSize];
  base::Vector<char> buffer(chars, kBufferSize);
  std::string_view str = DoubleToStringView(number, buffer);
  AppendString(str);
  return SUCCESS;
}
References AppendCStringLiteral(), AppendString(), v8::internal::DoubleToStringView(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, and SUCCESS.
Referenced by SerializeFixedArrayElement(), and SerializeHeapNumber().
SerializeElement()
Result v8::internal::JsonStringifier::SerializeElement (Isolate * isolate, Handle< JSAny > object, int i) [inline], [private]
Definition at line 66 of file json-stringifier.cc.
                                           {
    return Serialize_<false>(object, false,
                             Handle<Object>(Smi::FromInt(i), isolate));
  }
References v8::internal::Smi::FromInt().
Referenced by SerializeArrayLikeSlow(), and SerializeFixedArrayWithPossibleTransitions().
SerializeFixedArrayElement()
template<ElementsKind kind, typename T >
JsonStringifier::Result v8::internal::JsonStringifier::SerializeFixedArrayElement (Tagged< T > elements, uint32_t i, Tagged< JSArray > array, bool can_treat_hole_as_undefined) [inline], [private]
Definition at line 1294 of file json-stringifier.cc.
                          {
  if constexpr (IsHoleyElementsKind(kind)) {
    if (elements->is_the_hole(isolate_, i)) {
      if (bailout_on_hole) return UNCHANGED;
      Separator(i == 0);
      AppendCStringLiteral("null");
      return SUCCESS;
    }
  }
  DCHECK(!elements->is_the_hole(isolate_, i));
  Separator(i == 0);
  if constexpr (IsSmiElementsKind(kind)) {
    SerializeSmi(Cast<Smi>(elements->get(i)));
  } else if constexpr (IsDoubleElementsKind(kind)) {
    SerializeDouble(elements->get_scalar(i));
  } else {
    UNREACHABLE();
  }
  return SUCCESS;
}
References AppendCStringLiteral(), v8::internal::DCHECK(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), isolate_, v8::internal::IsSmiElementsKind(), Separator(), SerializeDouble(), SerializeSmi(), SUCCESS, UNCHANGED, and v8::internal::UNREACHABLE().
SerializeFixedArrayWithInterruptCheck()
template<ElementsKind kind>
JsonStringifier::Result v8::internal::JsonStringifier::SerializeFixedArrayWithInterruptCheck (DirectHandle< JSArray > array, uint32_t length, uint32_t * slow_path_index) [inline], [private]
Definition at line 1205 of file json-stringifier.cc.
                                                                             {
  static_assert(IsSmiElementsKind(kind) || IsDoubleElementsKind(kind));
  using ArrayT = std::conditional_t<IsDoubleElementsKind(kind),
                                    FixedDoubleArray, FixedArray>;
  StackLimitCheck interrupt_check(isolate_);
  constexpr uint32_t kInterruptLength = 4000;
  uint32_t limit = std::min(length, kInterruptLength);
  constexpr uint32_t kMaxAllowedFastPackedLength =
      std::numeric_limits<uint32_t>::max() - kInterruptLength;
  static_assert(FixedArray::kMaxLength < kMaxAllowedFastPackedLength);
  constexpr bool is_holey = IsHoleyElementsKind(kind);
  bool bailout_on_hole =
      is_holey ? !CanFastSerializeJSArray(isolate_, *array) : true;
  uint32_t i = 0;
  while (true) {
    for (; i < limit; i++) {
      Result result = SerializeFixedArrayElement<kind>(
          Cast<ArrayT>(array->elements()), i, *array, bailout_on_hole);
      if constexpr (is_holey) {
        if (result != SUCCESS) {
          *slow_path_index = i;
          return result;
        }
      } else {
        USE(result);
        DCHECK_EQ(result, SUCCESS);
      }
    }
    if (i >= length) return SUCCESS;
    DCHECK_LT(limit, kMaxAllowedFastPackedLength);
    limit = std::min(length, limit + kInterruptLength);
    if (interrupt_check.InterruptRequested() &&
        IsException(isolate_->stack_guard()->HandleInterrupts(), isolate_)) {
      return EXCEPTION;
    }
  }
  return SUCCESS;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::CanFastSerializeJSArray(), DCHECK_EQ, DCHECK_LT, EXCEPTION, v8::internal::StackGuard::HandleInterrupts(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::IsDoubleElementsKind(), v8::internal::IsHoleyElementsKind(), isolate_, v8::internal::IsSmiElementsKind(), v8::internal::FixedArray::kMaxLength, v8::internal::length, v8::base::internal::result, v8::internal::Isolate::stack_guard(), SUCCESS, and USE.
SerializeFixedArrayWithPossibleTransitions()
template<ElementsKind kind>
JsonStringifier::Result v8::internal::JsonStringifier::SerializeFixedArrayWithPossibleTransitions (DirectHandle< JSArray > array, uint32_t length, uint32_t * slow_path_index) [inline], [private]
Definition at line 1250 of file json-stringifier.cc.
                                                                             {
  static_assert(IsObjectElementsKind(kind));
  HandleScope handle_scope(isolate_);
  DirectHandle<Object> old_length(array->length(), isolate_);
  constexpr bool is_holey = IsHoleyElementsKind(kind);
  bool should_check_treat_hole_as_undefined = true;
  for (uint32_t i = 0; i < length; i++) {
    if (array->length() != *old_length || kind != array->GetElementsKind()) {
      // Array was modified during SerializeElement.
      *slow_path_index = i;
      return UNCHANGED;
    }
    Tagged<Object> current_element =
        Cast<FixedArray>(array->elements())->get(i);
    if (is_holey && IsTheHole(current_element)) {
      if (should_check_treat_hole_as_undefined) {
        if (!CanFastSerializeJSArray(isolate_, *array)) {
          *slow_path_index = i;
          return UNCHANGED;
        }
        should_check_treat_hole_as_undefined = false;
      }
      Separator(i == 0);
      AppendCStringLiteral("null");
    } else {
      Separator(i == 0);
      Result result = SerializeElement(
          isolate_, handle(Cast<JSAny>(current_element), isolate_), i);
      if (result == UNCHANGED) {
        AppendCStringLiteral("null");
      } else if (result != SUCCESS) {
        return result;
      }
      if constexpr (is_holey) {
        should_check_treat_hole_as_undefined = true;
      }
    }
  }
  return SUCCESS;
}
References AppendCStringLiteral(), v8::internal::anonymous_namespace{json-stringifier.cc}::CanFastSerializeJSArray(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::IsHoleyElementsKind(), v8::internal::IsObjectElementsKind(), isolate_, v8::internal::length, v8::base::internal::result, Separator(), SerializeElement(), SUCCESS, and UNCHANGED.
SerializeHeapNumber()
Result v8::internal::JsonStringifier::SerializeHeapNumber (DirectHandle< HeapNumber > object) [inline], [private]
Definition at line 252 of file json-stringifier.cc.
                                                                        {
    return SerializeDouble(object->value());
  }
References SerializeDouble().
Referenced by Serialize_(), and SerializeJSPrimitiveWrapper().
SerializeJSArray()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeJSArray (Handle< JSArray > object, Handle< Object > key) [inline], [private]
Definition at line 1149 of file json-stringifier.cc.
                                                {
  uint32_t length = 0;
  CHECK(Object::ToArrayLength(object->length(), &length));
  DCHECK(!IsAccessCheckNeeded(*object));
  if (length == 0) {
    AppendCStringLiteral("[]");
    return SUCCESS;
  }
  Result stack_push = StackPush(object, key);
  if (stack_push != SUCCESS) return stack_push;
  AppendCharacter('[');
  Indent();
  uint32_t slow_path_index = 0;
  Result result = UNCHANGED;
  if (replacer_function_.is_null()) {
#define CASE_WITH_INTERRUPT(kind) \
  case kind: \
    result = SerializeFixedArrayWithInterruptCheck<kind>(object, length, \
                                                         &slow_path_index); \
    break;
#define CASE_WITH_TRANSITION(kind) \
  case kind: \
    result = SerializeFixedArrayWithPossibleTransitions<kind>(\
        object, length, &slow_path_index); \
    break;
    switch (object->GetElementsKind()) {
      CASE_WITH_INTERRUPT(PACKED_SMI_ELEMENTS)
      CASE_WITH_INTERRUPT(HOLEY_SMI_ELEMENTS)
      CASE_WITH_TRANSITION(PACKED_ELEMENTS)
      CASE_WITH_TRANSITION(HOLEY_ELEMENTS)
      CASE_WITH_INTERRUPT(PACKED_DOUBLE_ELEMENTS)
      CASE_WITH_INTERRUPT(HOLEY_DOUBLE_ELEMENTS)
      default:
        break;
    }
#undef CASE_WITH_TRANSITION
#undef CASE_WITH_INTERRUPT
  }
  if (result == UNCHANGED) {
    // Slow path for non-fast elements and fall-back in edge cases.
    result = SerializeArrayLikeSlow(object, slow_path_index, length);
  }
  if (result != SUCCESS) return result;
  Unindent();
  NewLine();
  AppendCharacter(']');
  StackPop();
  return SUCCESS;
}
References AppendCharacter(), AppendCStringLiteral(), CASE_WITH_INTERRUPT, CASE_WITH_TRANSITION, CHECK, v8::internal::DCHECK(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, Indent(), v8::internal::key, v8::internal::length, NewLine(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, replacer_function_, v8::base::internal::result, SerializeArrayLikeSlow(), StackPop(), StackPush(), SUCCESS, v8::internal::Object::ToArrayLength(), UNCHANGED, and Unindent().
Referenced by Serialize_().
SerializeJSObject()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeJSObject (Handle< JSObject > object, Handle< Object > key) [inline], [private]
Definition at line 1353 of file json-stringifier.cc.
                                                 {
  PtrComprCageBase cage_base(isolate_);
  HandleScope handle_scope(isolate_);
  if (!property_list_.is_null() ||
      !CanFastSerializeJSObject(*object, isolate_)) {
    if (!need_stack_) {
      need_stack_ = true;
      return NEED_STACK;
    }
    Result stack_push = StackPush(object, key);
    if (stack_push != SUCCESS) return stack_push;
    Result result = SerializeJSReceiverSlow(object);
    if (result != SUCCESS) return result;
    StackPop();
    return SUCCESS;
  }
  DCHECK(!IsJSGlobalProxy(*object));
  DCHECK(!object->HasIndexedInterceptor());
  DCHECK(!object->HasNamedInterceptor());
  DirectHandle<Map> map(object->map(cage_base), isolate_);
  if (map->NumberOfOwnDescriptors() == 0) {
    AppendCStringLiteral("{}");
    return SUCCESS;
  }
  Result stack_push = StackPush(object, key);
  if (stack_push != SUCCESS) return stack_push;
  AppendCharacter('{');
  Indent();
  bool comma = false;
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    Handle<String> key_name;
    PropertyDetails details = PropertyDetails::Empty();
    {
      DisallowGarbageCollection no_gc;
      Tagged<DescriptorArray> descriptors =
          map->instance_descriptors(cage_base);
      Tagged<Name> name = descriptors->GetKey(i);
      // TODO(rossberg): Should this throw?
      if (!IsString(name, cage_base)) continue;
      key_name = handle(Cast<String>(name), isolate_);
      details = descriptors->GetDetails(i);
    }
    if (details.IsDontEnum()) continue;
    Handle<JSAny> property;
    if (details.location() == PropertyLocation::kField &&
        *map == object->map(cage_base)) {
      DCHECK_EQ(PropertyKind::kData, details.kind());
      FieldIndex field_index = FieldIndex::ForDetails(*map, details);
      if (replacer_function_.is_null()) {
        // If there's no replacer function, read the raw property to avoid
        // reboxing doubles in mutable boxes.
        property = handle(object->RawFastPropertyAt(field_index), isolate_);
      } else {
        // Rebox the value if there is a replacer function since it could change
        // the value in the box.
        property = JSObject::FastPropertyAt(
            isolate_, object, details.representation(), field_index);
      }
    } else {
      if (!need_stack_) {
        need_stack_ = true;
        return NEED_STACK;
      }
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate_, property,
          Cast<JSAny>(Object::GetPropertyOrElement(isolate_, object, key_name)),
          EXCEPTION);
    }
    Result result = SerializeProperty(property, comma, key_name);
    if (!comma && result == SUCCESS) comma = true;
    if (result == EXCEPTION || result == NEED_STACK) return result;
  }
  Unindent();
  if (comma) NewLine();
  AppendCharacter('}');
  StackPop();
  return SUCCESS;
}
References AppendCharacter(), AppendCStringLiteral(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::anonymous_namespace{json-stringifier.cc}::CanFastSerializeJSObject(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::PropertyDetails::Empty(), EXCEPTION, v8::internal::JSObject::FastPropertyAt(), v8::internal::FieldIndex::ForDetails(), v8::internal::Object::GetPropertyOrElement(), v8::internal::handle(), Indent(), v8::internal::PropertyDetails::IsDontEnum(), isolate_, v8::internal::kData, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::name, NEED_STACK, need_stack_, NewLine(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, property_list_, replacer_function_, v8::internal::PropertyDetails::representation(), v8::base::internal::result, SerializeJSReceiverSlow(), SerializeProperty(), StackPop(), StackPush(), SUCCESS, and Unindent().
Referenced by Serialize_(), and SerializeJSPrimitiveWrapper().
SerializeJSPrimitiveWrapper()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeJSPrimitiveWrapper (Handle< JSPrimitiveWrapper > object, Handle< Object > key) [private]
Definition at line 1094 of file json-stringifier.cc.
                                                           {
  Tagged<Object> raw = object->value();
  if (IsString(raw)) {
    Handle<Object> value;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, value, Object::ToString(isolate_, object), EXCEPTION);
    SerializeString<false>(Cast<String>(value));
  } else if (IsNumber(raw)) {
    DirectHandle<Object> value;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, value, Object::ToNumber(isolate_, object), EXCEPTION);
    if (IsSmi(*value)) return SerializeSmi(Cast<Smi>(*value));
    SerializeHeapNumber(Cast<HeapNumber>(value));
  } else if (IsBigInt(raw)) {
    isolate_->Throw(
        *factory()->NewTypeError(MessageTemplate::kBigIntSerializeJSON));
    return EXCEPTION;
  } else if (IsBoolean(raw)) {
    if (IsTrue(raw, isolate_)) {
      AppendCStringLiteral("true");
    } else {
      AppendCStringLiteral("false");
    }
  } else {
    // ES6 24.3.2.1 step 10.c, serialize as an ordinary JSObject.
    return SerializeJSObject(object, key);
  }
  return SUCCESS;
}
References AppendCStringLiteral(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, EXCEPTION, factory(), v8::internal::IsNumber(), isolate_, v8::internal::IsSmi(), v8::internal::key, SerializeHeapNumber(), SerializeJSObject(), SerializeSmi(), SUCCESS, v8::internal::Isolate::Throw(), v8::Value::ToNumber(), v8::Value::ToString(), and v8::internal::value.
Referenced by Serialize_().
SerializeJSProxy()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeJSProxy (Handle< JSProxy > object, Handle< Object > key) [private]
Definition at line 1467 of file json-stringifier.cc.
                                                {
  HandleScope scope(isolate_);
  Result stack_push = StackPush(object, key);
  if (stack_push != SUCCESS) return stack_push;
  Maybe<bool> is_array = Object::IsArray(object);
  if (is_array.IsNothing()) return EXCEPTION;
  if (is_array.FromJust()) {
    DirectHandle<Object> length_object;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, length_object,
        Object::GetLengthFromArrayLike(isolate_, Cast<JSReceiver>(object)),
        EXCEPTION);
    uint32_t length;
    if (!Object::ToUint32(*length_object, &length)) {
      // Technically, we need to be able to handle lengths outside the
      // uint32_t range. However, we would run into string size overflow
      // if we tried to stringify such an array.
      isolate_->Throw(*isolate_->factory()->NewInvalidStringLengthError());
      return EXCEPTION;
    }
    AppendCharacter('[');
    Indent();
    Result result = SerializeArrayLikeSlow(object, 0, length);
    if (result != SUCCESS) return result;
    Unindent();
    if (length > 0) NewLine();
    AppendCharacter(']');
  } else {
    Result result = SerializeJSReceiverSlow(object);
    if (result != SUCCESS) return result;
  }
  StackPop();
  return SUCCESS;
}
References AppendCharacter(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, EXCEPTION, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Object::GetLengthFromArrayLike(), Indent(), v8::internal::Object::IsArray(), v8::Maybe< T >::IsNothing(), isolate_, v8::internal::key, v8::internal::length, v8::internal::Factory::NewInvalidStringLengthError(), NewLine(), v8::base::internal::result, SerializeArrayLikeSlow(), SerializeJSReceiverSlow(), StackPop(), StackPush(), SUCCESS, v8::internal::Isolate::Throw(), v8::internal::Object::ToUint32(), and Unindent().
Referenced by Serialize_().
SerializeJSReceiverSlow()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeJSReceiverSlow (DirectHandle< JSReceiver > object) [private]
Definition at line 1437 of file json-stringifier.cc.
                                     {
  DirectHandle<FixedArray> contents = property_list_;
  if (contents.is_null()) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, contents,
        KeyAccumulator::GetKeys(isolate_, object, KeyCollectionMode::kOwnOnly,
                                ENUMERABLE_STRINGS,
                                GetKeysConversion::kConvertToString),
        EXCEPTION);
  }
  AppendCharacter('{');
  Indent();
  bool comma = false;
  for (int i = 0; i < contents->length(); i++) {
    Handle<String> key(Cast<String>(contents->get(i)), isolate_);
    Handle<Object> property;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate_, property, Object::GetPropertyOrElement(isolate_, object, key),
        EXCEPTION);
    Result result = SerializeProperty(Cast<JSAny>(property), comma, key);
    if (!comma && result == SUCCESS) comma = true;
    if (result == EXCEPTION || result == NEED_STACK) return result;
  }
  Unindent();
  if (comma) NewLine();
  AppendCharacter('}');
  return SUCCESS;
}
References AppendCharacter(), ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::ENUMERABLE_STRINGS, EXCEPTION, v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetPropertyOrElement(), Indent(), v8::internal::DirectHandle< T >::is_null(), isolate_, v8::internal::kConvertToString, v8::internal::key, v8::internal::kOwnOnly, NEED_STACK, NewLine(), property_list_, v8::base::internal::result, SerializeProperty(), SUCCESS, and Unindent().
Referenced by SerializeJSObject(), and SerializeJSProxy().
SerializeObject()
Result v8::internal::JsonStringifier::SerializeObject (Handle< JSAny > obj) [inline], [private]
Definition at line 60 of file json-stringifier.cc.
                                                      {
    return Serialize_<false>(obj, false, factory()->empty_string());
  }
References factory().
Referenced by Stringify().
SerializeProperty()
Result v8::internal::JsonStringifier::SerializeProperty (Handle< JSAny > object, bool deferred_comma, Handle< String > deferred_key) [inline], [private]
Definition at line 75 of file json-stringifier.cc.
                                                                  {
    DCHECK(!deferred_key.is_null());
    return Serialize_<true>(object, deferred_comma, deferred_key);
  }
References v8::internal::DCHECK(), and v8::internal::HandleBase::is_null().
Referenced by SerializeJSObject(), and SerializeJSReceiverSlow().
SerializeSmi()
JsonStringifier::Result v8::internal::JsonStringifier::SerializeSmi (Tagged< Smi > object) [private]
Definition at line 1125 of file json-stringifier.cc.
                                                                      {
  static_assert(Smi::kMaxValue <= 2147483647);
  static_assert(Smi::kMinValue >= -2147483648);
  // sizeof(string) includes \0.
  static constexpr uint32_t kBufferSize = sizeof("-2147483648") - 1;
  char chars[kBufferSize];
  base::Vector<char> buffer(chars, kBufferSize);
  AppendString(IntToStringView(object.value(), buffer));
  return SUCCESS;
}
References AppendString(), v8::internal::IntToStringView(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::kBufferSize, v8::internal::Smi::kMaxValue, v8::internal::Smi::kMinValue, SUCCESS, and v8::internal::value.
Referenced by Serialize_(), SerializeFixedArrayElement(), and SerializeJSPrimitiveWrapper().
SerializeString()
template<bool raw_json>
bool v8::internal::JsonStringifier::SerializeString (Handle< String > object) [private]
Definition at line 1749 of file json-stringifier.cc.
                                                           {
  object = String::Flatten(isolate_, object);
  DisallowGarbageCollection no_gc;
  auto string = *object;
  if (encoding_ == String::ONE_BYTE_ENCODING) {
    if (String::IsOneByteRepresentationUnderneath(string)) {
      return SerializeString_<uint8_t, uint8_t, raw_json>(string, no_gc);
    } else {
      ChangeEncoding();
    }
  }
  DCHECK_EQ(encoding_, String::TWO_BYTE_ENCODING);
  if (String::IsOneByteRepresentationUnderneath(string)) {
    return SerializeString_<uint8_t, base::uc16, raw_json>(string, no_gc);
  } else {
    return SerializeString_<base::uc16, base::uc16, raw_json>(string, no_gc);
  }
}
References ChangeEncoding(), DCHECK_EQ, encoding_, isolate_, v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::ONE_BYTE_ENCODING, and v8::internal::String::TWO_BYTE_ENCODING.
SerializeString_()
template<typename SrcChar , typename DestChar , bool raw_json>
bool v8::internal::JsonStringifier::SerializeString_ (Tagged< String > string, const DisallowGarbageCollection & no_gc) [inline], [private]
Definition at line 1577 of file json-stringifier.cc.
                                                                               {
  bool required_escaping = false;
  if (!raw_json) Append<uint8_t, DestChar>('"');
  // We might be able to fit the whole escaped string in the current string
  // part, or we might need to allocate.
  base::Vector<const SrcChar> vector = string->GetCharVector<SrcChar>(no_gc);
  if V8_LIKELY (EscapedLengthIfCurrentPartFits(vector.size())) {
    NoExtendBuilder<DestChar> no_extend(
        reinterpret_cast<DestChar*>(part_ptr_) + current_index_,
        &current_index_);
    required_escaping = SerializeStringUnchecked_<SrcChar, DestChar, raw_json>(
        vector, &no_extend);
  } else {
    DCHECK(encoding_ == String::TWO_BYTE_ENCODING ||
           (string->IsFlat() &&
            String::IsOneByteRepresentationUnderneath(string)));
    size_t uncopied_src_index = 0; // Index of first char not copied yet.
    for (size_t i = 0; i < vector.size(); i++) {
      SrcChar c = vector.at(i);
      if (raw_json || DoNotEscape(c)) {
        continue;
      } else if (sizeof(SrcChar) != 1 &&
                 base::IsInRange(c, static_cast<SrcChar>(0xD800),
                                 static_cast<SrcChar>(0xDFFF))) {
        // The current character is a surrogate.
        required_escaping = true;
        AppendSubstring(vector.data(), uncopied_src_index, i);
        char double_to_radix_chars[kDoubleToRadixMaxChars];
        base::Vector<char> double_to_radix_buffer =
            base::ArrayVector(double_to_radix_chars);
        if (c <= 0xDBFF) {
          // The current character is a leading surrogate.
          if (i + 1 < vector.size()) {
            // There is a next character.
            SrcChar next = vector.at(i + 1);
            if (base::IsInRange(next, static_cast<SrcChar>(0xDC00),
                                static_cast<SrcChar>(0xDFFF))) {
              // The next character is a trailing surrogate, meaning this is a
              // surrogate pair.
              Append<SrcChar, DestChar>(c);
              Append<SrcChar, DestChar>(next);
              i++;
            } else {
              // The next character is not a trailing surrogate. Thus, the
              // current character is a lone leading surrogate.
              AppendCStringLiteral("\\u");
              std::string_view hex =
                  DoubleToRadixStringView(c, 16, double_to_radix_buffer);
              AppendString(hex);
            }
          } else {
            // There is no next character. Thus, the current character is a
            // lone leading surrogate.
            AppendCStringLiteral("\\u");
            std::string_view hex =
                DoubleToRadixStringView(c, 16, double_to_radix_buffer);
            AppendString(hex);
          }
        } else {
          // The current character is a lone trailing surrogate. (If it had
          // been preceded by a leading surrogate, we would've ended up in the
          // other branch earlier on, and the current character would've been
          // handled as part of the surrogate pair already.)
          AppendCStringLiteral("\\u");
          std::string_view hex =
              DoubleToRadixStringView(c, 16, double_to_radix_buffer);
          AppendString(hex);
        }
        uncopied_src_index = i + 1;
      } else {
        required_escaping = true;
        AppendSubstring(vector.data(), uncopied_src_index, i);
        DCHECK_LT(c, 0x60);
        AppendCString(&JsonEscapeTable[c * kJsonEscapeTableEntrySize]);
        uncopied_src_index = i + 1;
      }
    }
    AppendSubstring(vector.data(), uncopied_src_index, vector.size());
  }
  if (!raw_json) Append<uint8_t, DestChar>('"');
  return required_escaping;
}
References AppendCString(), AppendCStringLiteral(), AppendString(), AppendSubstring(), v8::base::ArrayVector(), v8::base::Vector< T >::at(), current_index_, v8::base::Vector< T >::data(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::DoNotEscape(), v8::internal::DoubleToRadixStringView(), encoding_, EscapedLengthIfCurrentPartFits(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::anonymous_namespace{json-stringifier.cc}::JsonEscapeTable, v8::internal::kDoubleToRadixMaxChars, v8::internal::anonymous_namespace{json-stringifier.cc}::kJsonEscapeTableEntrySize, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, part_ptr_, v8::base::Vector< T >::size(), v8::internal::string, v8::internal::String::TWO_BYTE_ENCODING, and V8_LIKELY.
SerializeStringUnchecked_()
template<typename SrcChar , typename DestChar , bool raw_json>
bool v8::internal::JsonStringifier::SerializeStringUnchecked_ (base::Vector< const SrcChar > src, NoExtendBuilder< DestChar > * dest) [inline], [static], [private]
Definition at line 1504 of file json-stringifier.cc.
                                                                    {
  // Assert that base::uc16 character is not truncated down to 8 bit.
  // The <base::uc16, char> version of this method must not be called.
  DCHECK(sizeof(DestChar) >= sizeof(SrcChar));
  bool required_escaping = false;
  size_t uncopied_src_index = 0; // Index of first char not copied yet.
  for (size_t i = 0; i < src.size(); i++) {
    SrcChar c = src[i];
    if (raw_json || DoNotEscape(c)) {
      continue;
    } else if (sizeof(SrcChar) != 1 &&
               base::IsInRange(c, static_cast<SrcChar>(0xD800),
                               static_cast<SrcChar>(0xDFFF))) {
      // The current character is a surrogate.
      required_escaping = true;
      dest->AppendSubstring(src.data(), uncopied_src_index, i);
      char double_to_radix_chars[kDoubleToRadixMaxChars];
      base::Vector<char> double_to_radix_buffer =
          base::ArrayVector(double_to_radix_chars);
      if (c <= 0xDBFF) {
        // The current character is a leading surrogate.
        if (i + 1 < src.size()) {
          // There is a next character.
          SrcChar next = src[i + 1];
          if (base::IsInRange(next, static_cast<SrcChar>(0xDC00),
                              static_cast<SrcChar>(0xDFFF))) {
            // The next character is a trailing surrogate, meaning this is a
            // surrogate pair.
            dest->Append(c);
            dest->Append(next);
            i++;
          } else {
            // The next character is not a trailing surrogate. Thus, the
            // current character is a lone leading surrogate.
            dest->AppendCString("\\u");
            std::string_view hex =
                DoubleToRadixStringView(c, 16, double_to_radix_buffer);
            dest->AppendString(hex);
          }
        } else {
          // There is no next character. Thus, the current character is a lone
          // leading surrogate.
          dest->AppendCString("\\u");
          std::string_view hex =
              DoubleToRadixStringView(c, 16, double_to_radix_buffer);
          dest->AppendString(hex);
        }
      } else {
        // The current character is a lone trailing surrogate. (If it had been
        // preceded by a leading surrogate, we would've ended up in the other
        // branch earlier on, and the current character would've been handled
        // as part of the surrogate pair already.)
        dest->AppendCString("\\u");
        std::string_view hex =
            DoubleToRadixStringView(c, 16, double_to_radix_buffer);
        dest->AppendString(hex);
      }
      uncopied_src_index = i + 1;
    } else {
      required_escaping = true;
      dest->AppendSubstring(src.data(), uncopied_src_index, i);
      DCHECK_LT(c, 0x60);
      dest->AppendCString(&JsonEscapeTable[c * kJsonEscapeTableEntrySize]);
      uncopied_src_index = i + 1;
    }
  }
  dest->AppendSubstring(src.data(), uncopied_src_index, src.size());
  return required_escaping;
}
References v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::Append(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendCString(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendString(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendSubstring(), v8::base::ArrayVector(), v8::base::Vector< T >::data(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::DoNotEscape(), v8::internal::DoubleToRadixStringView(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::anonymous_namespace{json-stringifier.cc}::JsonEscapeTable, v8::internal::kDoubleToRadixMaxChars, v8::internal::anonymous_namespace{json-stringifier.cc}::kJsonEscapeTableEntrySize, and v8::base::Vector< T >::size().
StackPop()
void v8::internal::JsonStringifier::StackPop () [private]
Definition at line 826 of file json-stringifier.cc.
                               {
  if V8_LIKELY (!need_stack_) {
    --stack_nesting_level_;
    return;
  }
  stack_.pop_back();
}
References need_stack_, stack_, stack_nesting_level_, and V8_LIKELY.
Referenced by SerializeJSArray(), SerializeJSObject(), and SerializeJSProxy().
StackPush()
JsonStringifier::Result v8::internal::JsonStringifier::StackPush (Handle< Object > object, Handle< Object > key) [private]
Definition at line 790 of file json-stringifier.cc.
                                                                       {
  if (!need_stack_) {
    ++stack_nesting_level_;
    if V8_UNLIKELY (stack_nesting_level_ > 10) {
      need_stack_ = true;
      return NEED_STACK;
    }
    return SUCCESS;
  }
  StackLimitCheck check(isolate_);
  if (check.HasOverflowed()) {
    isolate_->StackOverflow();
    return EXCEPTION;
  }
  {
    DisallowGarbageCollection no_gc;
    Tagged<Object> raw_obj = *object;
    size_t size = stack_.size();
    for (size_t i = 0; i < size; ++i) {
      if (*stack_[i].second == raw_obj) {
        AllowGarbageCollection allow_to_return_error;
        Handle<String> circle_description =
            ConstructCircularStructureErrorMessage(key, i);
        DirectHandle<Object> error = factory()->NewTypeError(
            MessageTemplate::kCircularStructure, circle_description);
        isolate_->Throw(*error);
        return EXCEPTION;
      }
    }
  }
  stack_.emplace_back(key, object);
  return SUCCESS;
}
References ConstructCircularStructureErrorMessage(), EXCEPTION, factory(), v8::internal::StackLimitCheck::HasOverflowed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::key, NEED_STACK, need_stack_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), stack_, stack_nesting_level_, v8::internal::Isolate::StackOverflow(), SUCCESS, v8::internal::Isolate::Throw(), and V8_UNLIKELY.
Referenced by SerializeJSArray(), SerializeJSObject(), and SerializeJSProxy().
Stringify()
MaybeDirectHandle< Object > v8::internal::JsonStringifier::Stringify (Handle< JSAny > object, Handle< JSAny > replacer, Handle< Object > gap)
Definition at line 613 of file json-stringifier.cc.
                                                                         {
  if (!InitializeReplacer(replacer)) {
    CHECK(isolate_->has_exception());
    return MaybeDirectHandle<Object>();
  }
  if (!IsUndefined(*gap, isolate_) && !InitializeGap(gap)) {
    CHECK(isolate_->has_exception());
    return MaybeDirectHandle<Object>();
  }
  Result result = SerializeObject(object);
  if (result == NEED_STACK) {
    indent_ = 0;
    current_index_ = 0;
    result = SerializeObject(object);
  }
  if (result == UNCHANGED) return factory()->undefined_value();
  if (result == SUCCESS) {
    if (overflowed_ || current_index_ > String::kMaxLength) {
      THROW_NEW_ERROR(isolate_, NewInvalidStringLengthError());
    }
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      return isolate_->factory()
          ->NewStringFromOneByte(base::OneByteVector(
              reinterpret_cast<char*>(one_byte_ptr_), current_index_))
          .ToHandleChecked();
    } else {
      return isolate_->factory()->NewStringFromTwoByte(
          base::Vector<const base::uc16>(two_byte_ptr_, current_index_));
    }
  }
  DCHECK(result == EXCEPTION);
  CHECK(isolate_->has_exception());
  return MaybeDirectHandle<Object>();
}
References CHECK, current_index_, v8::internal::DCHECK(), encoding_, EXCEPTION, v8::internal::Isolate::factory(), factory(), v8::internal::Isolate::has_exception(), indent_, InitializeGap(), InitializeReplacer(), isolate_, v8::internal::String::kMaxLength, NEED_STACK, v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), v8::internal::Factory::NewStringFromTwoByte(), v8::internal::String::ONE_BYTE_ENCODING, one_byte_ptr_, v8::base::OneByteVector(), overflowed_, v8::base::internal::result, SerializeObject(), SUCCESS, THROW_NEW_ERROR, two_byte_ptr_, and UNCHANGED.
Referenced by v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify(), and v8::internal::JsonStringify().
TrySerializeSimplePropertyKey()
template<typename DestChar >
bool v8::internal::JsonStringifier::TrySerializeSimplePropertyKey (Tagged< String > string, const DisallowGarbageCollection & no_gc) [private]
Definition at line 1663 of file json-stringifier.cc.
                                                                {
  ReadOnlyRoots roots(isolate_);
  if (key->map() != roots.internalized_one_byte_string_map()) {
    return false;
  }
  if (!key_cache_.Contains(key)) {
    return false;
  }
  size_t length = key->length();
  size_t copy_length = length;
  if constexpr (sizeof(DestChar) == 1) {
    // CopyChars has fast paths for small integer lengths, and is generally a
    // little faster if we round the length up to the nearest 4. This is still
    // within the bounds of the object on the heap, because object alignment is
    // never less than 4 for any build configuration.
    constexpr int kRounding = 4;
    static_assert(kRounding <= kObjectAlignment);
    copy_length = RoundUp(length, kRounding);
  }
  // Add three for the quote marks and colon, to determine how much output space
  // is needed. We might actually require a little less output space than this,
  // depending on how much rounding happened above, but it's more important to
  // compute the requirement quickly than to be precise.
  size_t required_length = copy_length + 3;
  if (!CurrentPartCanFit(required_length)) {
    return false;
  }
  NoExtendBuilder<DestChar> no_extend(
      reinterpret_cast<DestChar*>(part_ptr_) + current_index_, &current_index_);
  no_extend.Append('"');
  base::Vector<const uint8_t> chars(
      Cast<SeqOneByteString>(key)->GetChars(no_gc), copy_length);
  DCHECK_LE(reinterpret_cast<Address>(chars.end()),
            key.address() + key->Size());
#if DEBUG
  for (size_t i = 0; i < length; ++i) {
    DCHECK(DoNotEscape(chars[i]));
  }
#endif // DEBUG
  no_extend.AppendChars(chars, length);
  no_extend.Append('"');
  no_extend.Append(':');
  return true;
}
References v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::Append(), v8::internal::JsonStringifier::NoExtendBuilder< DestChar >::AppendChars(), v8::internal::JsonStringifier::SimplePropertyKeyCache::Contains(), current_index_, CurrentPartCanFit(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::DoNotEscape(), v8::base::Vector< T >::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate_, v8::internal::key, key_cache_, v8::internal::kObjectAlignment, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, part_ptr_, and RoundUp().
Unindent()
void v8::internal::JsonStringifier::Unindent () [inline], [private]
Definition at line 409 of file json-stringifier.cc.
{ indent_--; }
References indent_.
Referenced by SerializeJSArray(), SerializeJSObject(), SerializeJSProxy(), and SerializeJSReceiverSlow().
Member Data Documentation
current_index_
size_t v8::internal::JsonStringifier::current_index_ [private]
Definition at line 446 of file json-stringifier.cc.
Referenced by Append(), AppendCStringLiteral(), AppendStringByCopy(), AppendSubstringByCopy(), ChangeEncoding(), CurrentPartCanFit(), Extend(), HasValidCurrentIndex(), SerializeString_(), Stringify(), and TrySerializeSimplePropertyKey().
encoding_
String::Encoding v8::internal::JsonStringifier::encoding_ [private]
Definition at line 437 of file json-stringifier.cc.
Referenced by Append(), AppendCharacter(), AppendCString(), AppendCStringLiteral(), AppendString(), AppendStringByCopy(), AppendSubstringByCopy(), ChangeEncoding(), Extend(), SerializeDeferredKey(), SerializeString(), SerializeString_(), and Stringify().
gap_
base::uc16* v8::internal::JsonStringifier::gap_ [private]
Definition at line 441 of file json-stringifier.cc.
Referenced by InitializeGap(), NewLine(), NewLineOutline(), SerializeDeferredKey(), and ~JsonStringifier().
indent_
int v8::internal::JsonStringifier::indent_ [private]
Definition at line 444 of file json-stringifier.cc.
Referenced by Indent(), NewLineOutline(), Stringify(), and Unindent().
isolate_
Isolate* v8::internal::JsonStringifier::isolate_ [private]
Definition at line 436 of file json-stringifier.cc.
Referenced by ApplyReplacerFunction(), ApplyToJsonFunction(), ConstructCircularStructureErrorMessage(), CurrentHolder(), factory(), InitializeGap(), InitializeReplacer(), Serialize_(), SerializeArrayLikeSlow(), SerializeFixedArrayElement(), SerializeFixedArrayWithInterruptCheck(), SerializeFixedArrayWithPossibleTransitions(), SerializeJSObject(), SerializeJSPrimitiveWrapper(), SerializeJSProxy(), SerializeJSReceiverSlow(), SerializeString(), StackPush(), Stringify(), and TrySerializeSimplePropertyKey().
kCircularErrorMessagePostfixCount
constexpr int v8::internal::JsonStringifier::kCircularErrorMessagePostfixCount = 1 [static], [constexpr], [private]
Definition at line 425 of file json-stringifier.cc.
Referenced by ConstructCircularStructureErrorMessage().
kCircularErrorMessagePrefixCount
constexpr int v8::internal::JsonStringifier::kCircularErrorMessagePrefixCount = 2 [static], [constexpr], [private]
Definition at line 424 of file json-stringifier.cc.
Referenced by ConstructCircularStructureErrorMessage().
key_cache_
SimplePropertyKeyCache v8::internal::JsonStringifier::key_cache_ [private]
Definition at line 454 of file json-stringifier.cc.
Referenced by SerializeDeferredKey(), and TrySerializeSimplePropertyKey().
kInitialPartLength
constexpr size_t v8::internal::JsonStringifier::kInitialPartLength = 2048 [static], [constexpr], [private]
Definition at line 427 of file json-stringifier.cc.
kMaxPartLength
constexpr size_t v8::internal::JsonStringifier::kMaxPartLength = 16 * 1024 [static], [constexpr], [private]
Definition at line 428 of file json-stringifier.cc.
Referenced by EscapedLengthIfCurrentPartFits().
kPartLengthGrowthFactor
constexpr size_t v8::internal::JsonStringifier::kPartLengthGrowthFactor = 2 [static], [constexpr], [private]
Definition at line 429 of file json-stringifier.cc.
Referenced by Extend().
need_stack_
bool v8::internal::JsonStringifier::need_stack_ [private]
Definition at line 449 of file json-stringifier.cc.
Referenced by Serialize_(), SerializeArrayLikeSlow(), SerializeJSObject(), StackPop(), and StackPush().
one_byte_array_
uint8_t v8::internal::JsonStringifier::one_byte_array_[kInitialPartLength] [private]
Definition at line 455 of file json-stringifier.cc.
Referenced by ChangeEncoding(), Extend(), JsonStringifier(), and ~JsonStringifier().
one_byte_ptr_
uint8_t* v8::internal::JsonStringifier::one_byte_ptr_ [private]
Definition at line 440 of file json-stringifier.cc.
Referenced by Append(), AppendCStringLiteral(), AppendStringByCopy(), AppendSubstringByCopy(), ChangeEncoding(), Extend(), JsonStringifier(), Stringify(), and ~JsonStringifier().
overflowed_
bool v8::internal::JsonStringifier::overflowed_ [private]
Definition at line 448 of file json-stringifier.cc.
Referenced by AppendString(), AppendSubstring(), Extend(), SerializeArrayLikeSlow(), and Stringify().
part_length_
size_t v8::internal::JsonStringifier::part_length_ [private]
Definition at line 445 of file json-stringifier.cc.
Referenced by Append(), AppendCStringLiteral(), AppendStringByCopy(), AppendSubstringByCopy(), ChangeEncoding(), CurrentPartCanFit(), Extend(), and HasValidCurrentIndex().
part_ptr_
void* v8::internal::JsonStringifier::part_ptr_ [private]
Definition at line 443 of file json-stringifier.cc.
Referenced by ChangeEncoding(), Extend(), JsonStringifier(), SerializeString_(), and TrySerializeSimplePropertyKey().
property_list_
Handle<FixedArray> v8::internal::JsonStringifier::property_list_ [private]
Definition at line 438 of file json-stringifier.cc.
Referenced by InitializeReplacer(), SerializeJSObject(), and SerializeJSReceiverSlow().
replacer_function_
Handle<JSReceiver> v8::internal::JsonStringifier::replacer_function_ [private]
Definition at line 439 of file json-stringifier.cc.
Referenced by ApplyReplacerFunction(), InitializeReplacer(), Serialize_(), SerializeJSArray(), and SerializeJSObject().
stack_
std::vector<KeyObject> v8::internal::JsonStringifier::stack_ [private]
Definition at line 452 of file json-stringifier.cc.
Referenced by ConstructCircularStructureErrorMessage(), CurrentHolder(), StackPop(), and StackPush().
stack_nesting_level_
int v8::internal::JsonStringifier::stack_nesting_level_ [private]
Definition at line 447 of file json-stringifier.cc.
Referenced by Serialize_(), StackPop(), and StackPush().
two_byte_ptr_
base::uc16* v8::internal::JsonStringifier::two_byte_ptr_ [private]
Definition at line 442 of file json-stringifier.cc.
Referenced by Append(), AppendStringByCopy(), AppendSubstringByCopy(), ChangeEncoding(), Extend(), Stringify(), and ~JsonStringifier().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc