v8::internal::IC Class Reference
#include <ic.h>
Public Types
using State = InlineCacheState
Public Member Functions
IC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
virtual ~IC ()=default
State state () const
void UpdateState (DirectHandle< Object > lookup_start_object, DirectHandle< Object > name)
bool RecomputeHandlerForName (DirectHandle< Object > name)
void MarkRecomputeHandler (DirectHandle< Object > name)
bool IsAnyHas () const
bool IsAnyLoad () const
bool IsAnyStore () const
bool IsAnyDefineOwn () const
void OnFeedbackChanged (const char *reason)
Static Public Member Functions
static bool IsHandler (Tagged< MaybeObject > object)
static void OnFeedbackChanged (Isolate *isolate, Tagged< FeedbackVector > vector, FeedbackSlot slot, const char *reason)
Protected Member Functions
void set_slow_stub_reason (const char *reason)
void set_accessor (Handle< Object > accessor)
MaybeHandle< Object > accessor () const
Isolate * isolate () const
bool is_vector_set ()
bool vector_needs_update ()
bool ConfigureVectorState (IC::State new_state, DirectHandle< Object > key)
void ConfigureVectorState (DirectHandle< Name > name, DirectHandle< Map > map, DirectHandle< Object > handler)
void ConfigureVectorState (DirectHandle< Name > name, DirectHandle< Map > map, const MaybeObjectDirectHandle &handler)
void ConfigureVectorState (DirectHandle< Name > name, MapHandlesSpan maps, MaybeObjectHandles *handlers)
void ConfigureVectorState (DirectHandle< Name > name, MapsAndHandlers const &maps_and_handlers)
char TransitionMarkFromState (IC::State state)
void TraceIC (const char *type, DirectHandle< Object > name)
void TraceIC (const char *type, DirectHandle< Object > name, State old_state, State new_state)
MaybeDirectHandle< Object > TypeError (MessageTemplate, Handle< Object > object, Handle< Object > key)
MaybeDirectHandle< Object > ReferenceError (Handle< Name > name)
void UpdateMonomorphicIC (const MaybeObjectDirectHandle &handler, DirectHandle< Name > name)
bool UpdateMegaDOMIC (const MaybeObjectDirectHandle &handler, DirectHandle< Name > name)
bool UpdateOneMapManyNamesIC (DirectHandle< Name > new_name)
bool UpdatePolymorphicIC (DirectHandle< Name > name, const MaybeObjectDirectHandle &handler)
void UpdateMegamorphicCache (DirectHandle< Map > map, DirectHandle< Name > name, const MaybeObjectDirectHandle &handler)
StubCache * stub_cache ()
void CopyICToMegamorphicCache (DirectHandle< Name > name)
bool IsTransitionOfMonomorphicTarget (Tagged< Map > source_map, Tagged< Map > target_map)
void SetCache (DirectHandle< Name > name, Handle< Object > handler)
void SetCache (DirectHandle< Name > name, const MaybeObjectHandle &handler)
FeedbackSlotKind kind () const
bool IsGlobalIC () const
bool IsLoadIC () const
bool IsLoadGlobalIC () const
bool IsKeyedLoadIC () const
bool IsStoreGlobalIC () const
bool IsSetNamedIC () const
bool IsDefineNamedOwnIC () const
bool IsStoreInArrayLiteralIC () const
bool IsKeyedStoreIC () const
bool IsKeyedHasIC () const
bool IsDefineKeyedOwnIC () const
bool is_keyed () const
bool ShouldRecomputeHandler (DirectHandle< String > name)
Handle< Map > lookup_start_object_map ()
void update_lookup_start_object_map (DirectHandle< Object > object)
void TargetMaps (MapHandles *list)
Tagged< Map > FirstTargetMap ()
const FeedbackNexus * nexus () const
FeedbackNexus * nexus ()
Private Member Functions
void FindTargetMaps ()
DISALLOW_IMPLICIT_CONSTRUCTORS (IC)
Private Attributes
Isolate * isolate_
bool vector_set_
State old_state_
State state_
FeedbackSlotKind kind_
Handle< Map > lookup_start_object_map_
MaybeHandle< Object > accessor_
MapHandles target_maps_
bool target_maps_set_
const char * slow_stub_reason_
FeedbackNexus nexus_
Detailed Description
Definition at line 27 of file ic.h.
Member Typedef Documentation
State
using v8::internal::IC::State = InlineCacheState
Definition at line 30 of file ic.h.
Constructor & Destructor Documentation
IC()
v8::internal::IC::IC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
Definition at line 181 of file ic.cc.
    : isolate_(isolate),
      vector_set_(false),
      kind_(kind),
      target_maps_(isolate),
      target_maps_set_(false),
      slow_stub_reason_(nullptr),
      nexus_(isolate, vector, slot) {
  DCHECK_IMPLIES(!vector.is_null(), kind_ == nexus_.kind());
  state_ = (vector.is_null()) ? NO_FEEDBACK : nexus_.ic_state();
  old_state_ = state_;
}
References DCHECK_IMPLIES, v8::internal::FeedbackNexus::ic_state(), v8::internal::HandleBase::is_null(), v8::internal::FeedbackNexus::kind(), kind_, nexus_, v8::internal::NO_FEEDBACK, old_state_, and state_.
 IC()
virtual v8::internal::IC::~IC () [virtual], [default]
Member Function Documentation
accessor()
MaybeHandle<Object> v8::internal::IC::accessor () const [inline], [protected]
Definition at line 76 of file ic.h.
{ return accessor_; }
References accessor_.
Referenced by set_accessor(), and UpdateMegaDOMIC().
ConfigureVectorState() [1/5]
void v8::internal::IC::ConfigureVectorState (DirectHandle< Name > name, DirectHandle< Map > map, const MaybeObjectDirectHandle & handler) [protected]
Definition at line 352 of file ic.cc.
                                                                      {
  if (IsGlobalIC()) {
    nexus()->ConfigureHandlerMode(handler);
  } else {
    // Non-keyed ICs don't track the name explicitly.
    if (!is_keyed()) name = Handle<Name>::null();
    nexus()->ConfigureMonomorphic(name, map, handler);
  }
  OnFeedbackChanged(IsLoadGlobalIC() ? "LoadGlobal" : "Monomorphic");
}
References v8::internal::FeedbackNexus::ConfigureHandlerMode(), v8::internal::FeedbackNexus::ConfigureMonomorphic(), is_keyed(), IsGlobalIC(), IsLoadGlobalIC(), v8::internal::name, nexus(), v8::internal::Handle< T >::null(), and OnFeedbackChanged().
ConfigureVectorState() [2/5]
void v8::internal::IC::ConfigureVectorState (DirectHandle< Name > name, DirectHandle< Map > map, DirectHandle< Object > handler) [protected]
Definition at line 347 of file ic.cc.
                                                            {
  ConfigureVectorState(name, map, MaybeObjectDirectHandle(handler));
}
References ConfigureVectorState(), and v8::internal::name.
ConfigureVectorState() [3/5]
void v8::internal::IC::ConfigureVectorState (DirectHandle< Name > name, MapHandlesSpan maps, MaybeObjectHandles * handlers) [protected]
Definition at line 365 of file ic.cc.
                                                            {
  DCHECK(!IsGlobalIC());
  MapsAndHandlers maps_and_handlers(isolate());
  maps_and_handlers.reserve(maps.size());
  DCHECK_EQ(maps.size(), handlers->size());
  for (size_t i = 0; i < maps.size(); i++) {
    maps_and_handlers.emplace_back(maps[i], handlers->at(i));
  }
  ConfigureVectorState(name, maps_and_handlers);
}
References ConfigureVectorState(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MapsAndHandlers::emplace_back(), IsGlobalIC(), isolate(), v8::internal::name, v8::internal::MapsAndHandlers::reserve(), and v8::MemorySpan< T >::size().
ConfigureVectorState() [4/5]
void v8::internal::IC::ConfigureVectorState (DirectHandle< Name > name, MapsAndHandlers const & maps_and_handlers) [protected]
Definition at line 377 of file ic.cc.
                                                                        {
  DCHECK(!IsGlobalIC());
  // Non-keyed ICs don't track the name explicitly.
  if (!is_keyed()) name = Handle<Name>::null();
  nexus()->ConfigurePolymorphic(name, maps_and_handlers);
  OnFeedbackChanged("Polymorphic");
}
References v8::internal::FeedbackNexus::ConfigurePolymorphic(), v8::internal::DCHECK(), is_keyed(), IsGlobalIC(), v8::internal::name, nexus(), v8::internal::Handle< T >::null(), and OnFeedbackChanged().
ConfigureVectorState() [5/5]
bool v8::internal::IC::ConfigureVectorState (IC::State new_state, DirectHandle< Object > key) [protected]
Definition at line 336 of file ic.cc.
                                                                         {
  DCHECK_EQ(MEGAMORPHIC, new_state);
  DCHECK_IMPLIES(!is_keyed(), IsName(*key));
  bool changed = nexus()->ConfigureMegamorphic(
      IsName(*key) ? IcCheckType::kProperty : IcCheckType::kElement);
  if (changed) {
    OnFeedbackChanged("Megamorphic");
  }
  return changed;
}
References v8::internal::FeedbackNexus::ConfigureMegamorphic(), DCHECK_EQ, DCHECK_IMPLIES, is_keyed(), v8::internal::kElement, v8::internal::key, v8::internal::kProperty, v8::internal::MEGAMORPHIC, nexus(), and OnFeedbackChanged().
Referenced by ConfigureVectorState(), v8::internal::KeyedLoadIC::Load(), v8::internal::KeyedLoadIC::LoadName(), SetCache(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::KeyedStoreIC::Store(), v8::internal::KeyedLoadIC::UpdateLoadElement(), UpdateMonomorphicIC(), UpdateOneMapManyNamesIC(), UpdatePolymorphicIC(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
CopyICToMegamorphicCache()
void v8::internal::IC::CopyICToMegamorphicCache (DirectHandle< Name > name) [protected]
Definition at line 726 of file ic.cc.
                                                         {
  MapsAndHandlers maps_and_handlers(isolate());
  nexus()->ExtractMapsAndHandlers(&maps_and_handlers);
  for (auto [map, handler] : maps_and_handlers) {
    UpdateMegamorphicCache(map, name, handler);
  }
}
References v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), isolate(), v8::internal::name, nexus(), and UpdateMegamorphicCache().
Referenced by SetCache().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::IC::DISALLOW_IMPLICIT_CONSTRUCTORS (IC) [private]
FindTargetMaps()
void v8::internal::IC::FindTargetMaps () [inline], [private]
Definition at line 161 of file ic.h.
                        {
    if (target_maps_set_) return;
    target_maps_set_ = true;
    nexus()->ExtractMaps(&target_maps_);
  }
References v8::internal::FeedbackNexus::ExtractMaps(), nexus(), target_maps_, and target_maps_set_.
Referenced by FirstTargetMap(), and TargetMaps().
FirstTargetMap()
Tagged<Map> v8::internal::IC::FirstTargetMap () [inline], [protected]
Definition at line 152 of file ic.h.
                               {
    FindTargetMaps();
    return !target_maps_.empty() ? *target_maps_[0] : Tagged<Map>();
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::empty(), FindTargetMaps(), and target_maps_.
Referenced by ShouldRecomputeHandler().
is_keyed()
bool v8::internal::IC::is_keyed () const [inline], [protected]
Definition at line 136 of file ic.h.
                        {
    return IsKeyedLoadIC() || IsKeyedStoreIC() || IsStoreInArrayLiteralIC() ||
           IsKeyedHasIC() || IsDefineKeyedOwnIC();
  }
References IsDefineKeyedOwnIC(), IsKeyedHasIC(), IsKeyedLoadIC(), IsKeyedStoreIC(), and IsStoreInArrayLiteralIC().
Referenced by ConfigureVectorState(), RecomputeHandlerForName(), SetCache(), TraceIC(), and UpdatePolymorphicIC().
is_vector_set()
bool v8::internal::IC::is_vector_set () [inline], [protected]
Definition at line 80 of file ic.h.
{ return vector_set_; }
References vector_set_.
Referenced by v8::internal::KeyedLoadIC::Load().
IsAnyDefineOwn()
bool v8::internal::IC::IsAnyDefineOwn () const [inline]
Definition at line 61 of file ic.h.
                              {
    return IsDefineNamedOwnIC() || IsDefineKeyedOwnIC();
  }
References IsDefineKeyedOwnIC(), and IsDefineNamedOwnIC().
Referenced by v8::internal::StoreIC::ComputeHandler(), v8::internal::StoreIC::LookupForWrite(), v8::internal::StoreIC::Store(), v8::internal::KeyedStoreIC::StoreElementHandler(), and stub_cache().
IsAnyHas()
bool v8::internal::IC::IsAnyHas () const [inline]
Definition at line 52 of file ic.h.
{ return IsKeyedHasIC(); }
References IsKeyedHasIC().
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::LoadIC::Load(), v8::internal::KeyedLoadIC::LoadElementHandler(), v8::internal::LoadIC::LoadIC(), SetCache(), stub_cache(), and UpdateMegamorphicCache().
IsAnyLoad()
bool v8::internal::IC::IsAnyLoad () const [inline]
Definition at line 53 of file ic.h.
                         {
    return IsLoadIC() || IsLoadGlobalIC() || IsKeyedLoadIC();
  }
References IsKeyedLoadIC(), IsLoadGlobalIC(), and IsLoadIC().
Referenced by v8::internal::LoadIC::LoadIC(), SetCache(), and stub_cache().
IsAnyStore()
bool v8::internal::IC::IsAnyStore () const [inline]
Definition at line 56 of file ic.h.
                          {
    return IsSetNamedIC() || IsDefineNamedOwnIC() || IsStoreGlobalIC() ||
           IsKeyedStoreIC() || IsStoreInArrayLiteralICKind(kind()) ||
           IsDefineKeyedOwnIC();
  }
References IsDefineKeyedOwnIC(), IsDefineNamedOwnIC(), IsKeyedStoreIC(), IsSetNamedIC(), IsStoreGlobalIC(), v8::internal::IsStoreInArrayLiteralICKind(), and kind().
Referenced by SetCache(), v8::internal::StoreIC::StoreIC(), and stub_cache().
IsDefineKeyedOwnIC()
bool v8::internal::IC::IsDefineKeyedOwnIC () const [inline], [protected]
Definition at line 135 of file ic.h.
{ return IsDefineKeyedOwnICKind(kind_); }
References v8::internal::IsDefineKeyedOwnICKind(), and kind_.
Referenced by v8::internal::StoreIC::ComputeHandler(), is_keyed(), IsAnyDefineOwn(), IsAnyStore(), v8::internal::StoreIC::Store(), v8::internal::KeyedStoreIC::Store(), v8::internal::KeyedStoreIC::StoreElementHandler(), and TraceIC().
IsDefineNamedOwnIC()
bool v8::internal::IC::IsDefineNamedOwnIC () const [inline], [protected]
Definition at line 129 of file ic.h.
{ return IsDefineNamedOwnICKind(kind_); }
References v8::internal::IsDefineNamedOwnICKind(), and kind_.
Referenced by v8::internal::StoreIC::ComputeHandler(), IsAnyDefineOwn(), IsAnyStore(), and v8::internal::StoreIC::Store().
IsGlobalIC()
bool v8::internal::IC::IsGlobalIC () const [inline], [protected]
Definition at line 123 of file ic.h.
{ return IsLoadGlobalIC() || IsStoreGlobalIC(); }
References IsLoadGlobalIC(), and IsStoreGlobalIC().
Referenced by ConfigureVectorState(), SetCache(), and ShouldRecomputeHandler().
IsHandler()
bool v8::internal::IC::IsHandler (Tagged< MaybeObject > object) [inline], [static]
Definition at line 29 of file ic-inl.h.
                                             {
  Tagged<HeapObject> heap_object;
  return (IsSmi(object) && (object.ptr() != kNullAddress)) ||
         (object.GetHeapObjectIfWeak(&heap_object) &&
          (IsMap(heap_object) || IsPropertyCell(heap_object) ||
           IsAccessorPair(heap_object))) ||
         (object.GetHeapObjectIfStrong(&heap_object) &&
          (IsDataHandler(heap_object) || IsCode(heap_object)));
}
References v8::internal::IsSmi(), and v8::internal::kNullAddress.
Referenced by v8::internal::FeedbackNexus::ConfigureHandlerMode(), v8::internal::FeedbackNexus::ConfigureMonomorphic(), v8::internal::FeedbackNexus::ConfigurePolymorphic(), v8::internal::FeedbackNexus::ExtractMapsAndHandlers(), SetCache(), v8::internal::StubCache::StubCache(), UpdateMonomorphicIC(), and UpdatePolymorphicIC().
IsKeyedHasIC()
bool v8::internal::IC::IsKeyedHasIC () const [inline], [protected]
Definition at line 134 of file ic.h.
{ return IsKeyedHasICKind(kind_); }
References v8::internal::IsKeyedHasICKind(), and kind_.
Referenced by is_keyed(), IsAnyHas(), and v8::internal::KeyedLoadIC::RuntimeLoad().
IsKeyedLoadIC()
bool v8::internal::IC::IsKeyedLoadIC () const [inline], [protected]
Definition at line 126 of file ic.h.
{ return IsKeyedLoadICKind(kind_); }
References v8::internal::IsKeyedLoadICKind(), and kind_.
Referenced by is_keyed(), IsAnyLoad(), v8::internal::KeyedLoadIC::RuntimeLoad(), TraceIC(), and UpdateOneMapManyNamesIC().
IsKeyedStoreIC()
bool v8::internal::IC::IsKeyedStoreIC () const [inline], [protected]
Definition at line 133 of file ic.h.
{ return IsKeyedStoreICKind(kind_); }
References v8::internal::IsKeyedStoreICKind(), and kind_.
Referenced by is_keyed(), IsAnyStore(), TraceIC(), and UpdateOneMapManyNamesIC().
IsLoadGlobalIC()
bool v8::internal::IC::IsLoadGlobalIC () const [inline], [protected]
Definition at line 125 of file ic.h.
{ return IsLoadGlobalICKind(kind_); }
References v8::internal::IsLoadGlobalICKind(), and kind_.
Referenced by v8::internal::LoadIC::ComputeHandler(), ConfigureVectorState(), IsAnyLoad(), IsGlobalIC(), v8::internal::LoadIC::Load(), and v8::internal::LoadIC::UpdateCaches().
IsLoadIC()
bool v8::internal::IC::IsLoadIC () const [inline], [protected]
Definition at line 124 of file ic.h.
{ return IsLoadICKind(kind_); }
References v8::internal::IsLoadICKind(), and kind_.
Referenced by IsAnyLoad(), and UpdateMegaDOMIC().
isolate()
Isolate* v8::internal::IC::isolate () const [inline], [protected]
Definition at line 78 of file ic.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), ConfigureVectorState(), CopyICToMegamorphicCache(), IsTransitionOfMonomorphicTarget(), v8::internal::LoadIC::Load(), v8::internal::KeyedLoadIC::Load(), v8::internal::LoadGlobalIC::Load(), v8::internal::KeyedLoadIC::LoadElementHandler(), v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers(), v8::internal::KeyedLoadIC::LoadName(), v8::internal::StoreIC::LookupForWrite(), OnFeedbackChanged(), ReferenceError(), v8::internal::KeyedLoadIC::RuntimeLoad(), ShouldRecomputeHandler(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::StoreIC::Store(), v8::internal::KeyedStoreIC::Store(), v8::internal::StoreGlobalIC::Store(), v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::KeyedStoreIC::StoreElementPolymorphicHandlers(), stub_cache(), TraceIC(), TypeError(), v8::internal::LoadIC::UpdateCaches(), v8::internal::StoreIC::UpdateCaches(), v8::internal::KeyedLoadIC::UpdateLoadElement(), UpdateMegaDOMIC(), UpdateOneMapManyNamesIC(), UpdatePolymorphicIC(), UpdateState(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
IsSetNamedIC()
bool v8::internal::IC::IsSetNamedIC () const [inline], [protected]
Definition at line 128 of file ic.h.
{ return IsSetNamedICKind(kind_); }
References v8::internal::IsSetNamedICKind(), and kind_.
Referenced by IsAnyStore().
IsStoreGlobalIC()
bool v8::internal::IC::IsStoreGlobalIC () const [inline], [protected]
Definition at line 127 of file ic.h.
{ return IsStoreGlobalICKind(kind_); }
References v8::internal::IsStoreGlobalICKind(), and kind_.
Referenced by v8::internal::StoreIC::ComputeHandler(), IsAnyStore(), IsGlobalIC(), v8::internal::StoreIC::LookupForWrite(), v8::internal::StoreIC::Store(), and v8::internal::StoreIC::UpdateCaches().
IsStoreInArrayLiteralIC()
bool v8::internal::IC::IsStoreInArrayLiteralIC () const [inline], [protected]
Definition at line 130 of file ic.h.
                                       {
    return IsStoreInArrayLiteralICKind(kind_);
  }
References v8::internal::IsStoreInArrayLiteralICKind(), and kind_.
Referenced by is_keyed(), v8::internal::KeyedStoreIC::StoreElementHandler(), TraceIC(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
IsTransitionOfMonomorphicTarget()
bool v8::internal::IC::IsTransitionOfMonomorphicTarget (Tagged< Map > source_map, Tagged< Map > target_map) [protected]
Definition at line 734 of file ic.cc.
                                                                 {
  if (source_map.is_null()) return true;
  if (target_map.is_null()) return false;
  if (source_map->is_abandoned_prototype_map()) return false;
  ElementsKind target_elements_kind = target_map->elements_kind();
  bool more_general_transition = IsMoreGeneralElementsKindTransition(
      source_map->elements_kind(), target_elements_kind);
  Tagged<Map> transitioned_map;
  if (more_general_transition) {
    DirectHandle<Map> single_map[1] = {direct_handle(target_map, isolate_)};
    transitioned_map = source_map->FindElementsKindTransitionedMap(
        isolate(), single_map, ConcurrencyMode::kSynchronous);
  }
  return transitioned_map == target_map;
}
References v8::internal::direct_handle(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IsMoreGeneralElementsKindTransition(), isolate(), isolate_, and v8::internal::kSynchronous.
Referenced by UpdatePolymorphicIC(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
kind()
FeedbackSlotKind v8::internal::IC::kind () const [inline], [protected]
Definition at line 122 of file ic.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::StoreIC::ComputeHandler(), IsAnyStore(), v8::internal::LoadIC::ShouldThrowReferenceError(), and v8::internal::StoreInArrayLiteralIC::StoreInArrayLiteralIC().
lookup_start_object_map()
Handle<Map> v8::internal::IC::lookup_start_object_map () [inline], [protected]
Definition at line 142 of file ic.h.
{ return lookup_start_object_map_; }
References lookup_start_object_map_.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), SetCache(), ShouldRecomputeHandler(), TraceIC(), v8::internal::LoadIC::UpdateCaches(), UpdateMegaDOMIC(), UpdateMonomorphicIC(), UpdateOneMapManyNamesIC(), and UpdatePolymorphicIC().
MarkRecomputeHandler()
void v8::internal::IC::MarkRecomputeHandler (DirectHandle< Object > name) [inline]
Definition at line 46 of file ic.h.
                                                       {
    DCHECK(RecomputeHandlerForName(name));
    old_state_ = state_;
    state_ = InlineCacheState::RECOMPUTE_HANDLER;
  }
References v8::internal::DCHECK(), v8::internal::name, old_state_, v8::internal::RECOMPUTE_HANDLER, RecomputeHandlerForName(), and state_.
Referenced by UpdateState().
nexus() [1/2]
FeedbackNexus* v8::internal::IC::nexus () [inline], [protected]
Definition at line 158 of file ic.h.
{ return &nexus_; }
References nexus_.
nexus() [2/2]
const FeedbackNexus* v8::internal::IC::nexus () const [inline], [protected]
Definition at line 157 of file ic.h.
{ return &nexus_; }
References nexus_.
Referenced by v8::internal::StoreIC::ComputeHandler(), ConfigureVectorState(), CopyICToMegamorphicCache(), FindTargetMaps(), v8::internal::KeyedLoadIC::GetKeyedAccessLoadModeFor(), v8::internal::KeyedStoreIC::GetKeyedAccessStoreMode(), v8::internal::LoadGlobalIC::Load(), OnFeedbackChanged(), RecomputeHandlerForName(), ShouldRecomputeHandler(), v8::internal::StoreGlobalIC::Store(), TraceIC(), v8::internal::LoadIC::UpdateCaches(), v8::internal::StoreIC::UpdateCaches(), UpdateMegaDOMIC(), UpdateOneMapManyNamesIC(), UpdatePolymorphicIC(), v8::internal::KeyedStoreIC::UpdateStoreElement(), and vector_needs_update().
OnFeedbackChanged() [1/2]
void v8::internal::IC::OnFeedbackChanged (const char * reason)
Definition at line 305 of file ic.cc.
                                             {
  vector_set_ = true;
  Tagged<FeedbackVector> vector = nexus()->vector();
  FeedbackSlot slot = nexus()->slot();
  OnFeedbackChanged(isolate(), vector, slot, reason);
}
References isolate(), nexus(), OnFeedbackChanged(), v8::internal::FeedbackNexus::slot(), v8::internal::FeedbackNexus::vector(), and vector_set_.
OnFeedbackChanged() [2/2]
void v8::internal::IC::OnFeedbackChanged (Isolate * isolate, Tagged< FeedbackVector > vector, FeedbackSlot slot, const char * reason) [static]
Definition at line 313 of file ic.cc.
                                                                  {
#ifdef V8_TRACE_FEEDBACK_UPDATES
  if (v8_flags.trace_feedback_updates) {
    FeedbackVector::TraceFeedbackChange(isolate, vector, slot, reason);
  }
#endif
  isolate->tiering_manager()->NotifyICChanged(vector);
}
References isolate(), v8::internal::TieringManager::NotifyICChanged(), v8::internal::Isolate::tiering_manager(), and v8::internal::v8_flags.
Referenced by v8::internal::JSFunction::ClearAllTypeFeedbackInfoForTesting(), ConfigureVectorState(), and OnFeedbackChanged().
RecomputeHandlerForName()
bool v8::internal::IC::RecomputeHandlerForName (DirectHandle< Object > name)
Definition at line 265 of file ic.cc.
                                                          {
  if (is_keyed()) {
    // Determine whether the failure is due to a name failure.
    if (!IsName(*name)) return false;
    Tagged<Name> stub_name = nexus()->GetName();
    if (*name != stub_name) return false;
  }
  return true;
}
References v8::internal::FeedbackNexus::GetName(), is_keyed(), v8::internal::name, and nexus().
Referenced by MarkRecomputeHandler(), and ShouldRecomputeHandler().
ReferenceError()
MaybeDirectHandle< Object > v8::internal::IC::ReferenceError (Handle< Name > name) [protected]
Definition at line 299 of file ic.cc.
                                                              {
  HandleScope scope(isolate());
  THROW_NEW_ERROR(isolate(),
                  NewReferenceError(MessageTemplate::kNotDefined, name));
}
References isolate(), v8::internal::name, and THROW_NEW_ERROR.
Referenced by v8::internal::LoadIC::Load().
set_accessor()
void v8::internal::IC::set_accessor (Handle< Object > accessor) [inline], [protected]
Definition at line 75 of file ic.h.
{ accessor_ = accessor; }
References accessor(), and accessor_.
Referenced by v8::internal::LoadIC::ComputeHandler().
set_slow_stub_reason()
void v8::internal::IC::set_slow_stub_reason (const char * reason) [inline], [protected]
Definition at line 74 of file ic.h.
{ slow_stub_reason_ = reason; }
References slow_stub_reason_.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::KeyedStoreIC::Store(), v8::internal::KeyedStoreIC::StoreElementHandler(), v8::internal::StoreIC::UpdateCaches(), v8::internal::KeyedLoadIC::UpdateLoadElement(), and v8::internal::KeyedStoreIC::UpdateStoreElement().
SetCache() [1/2]
void v8::internal::IC::SetCache (DirectHandle< Name > name, const MaybeObjectHandle & handler) [protected]
Definition at line 755 of file ic.cc.
                                                                           {
  DCHECK(IsHandler(*handler));
  // Currently only load and store ICs support non-code handlers.
  DCHECK(IsAnyLoad() || IsAnyStore() || IsAnyHas());
  switch (state()) {
    case NO_FEEDBACK:
      UNREACHABLE();
    case UNINITIALIZED:
      UpdateMonomorphicIC(handler, name);
      break;
    case RECOMPUTE_HANDLER:
    case MONOMORPHIC:
      if (IsGlobalIC()) {
        UpdateMonomorphicIC(handler, name);
        break;
      }
      if (UpdateOneMapManyNamesIC(name)) break;
      [[fallthrough]];
    case POLYMORPHIC:
      if (UpdatePolymorphicIC(name, handler)) break;
      if (UpdateMegaDOMIC(handler, name)) break;
      if (!is_keyed() || state() == RECOMPUTE_HANDLER) {
        CopyICToMegamorphicCache(name);
      }
      [[fallthrough]];
    case MEGADOM:
      ConfigureVectorState(MEGAMORPHIC, name);
      [[fallthrough]];
    case MEGAMORPHIC:
      UpdateMegamorphicCache(lookup_start_object_map(), name, handler);
      // Indicate that we've handled this case.
      vector_set_ = true;
      break;
    case GENERIC:
      UNREACHABLE();
  }
}
References ConfigureVectorState(), CopyICToMegamorphicCache(), v8::internal::DCHECK(), v8::internal::GENERIC, is_keyed(), IsAnyHas(), IsAnyLoad(), IsAnyStore(), IsGlobalIC(), IsHandler(), lookup_start_object_map(), v8::internal::MEGADOM, v8::internal::MEGAMORPHIC, v8::internal::MONOMORPHIC, v8::internal::name, v8::internal::NO_FEEDBACK, v8::internal::POLYMORPHIC, v8::internal::RECOMPUTE_HANDLER, state(), v8::internal::UNINITIALIZED, v8::internal::UNREACHABLE(), UpdateMegaDOMIC(), UpdateMegamorphicCache(), UpdateMonomorphicIC(), UpdateOneMapManyNamesIC(), UpdatePolymorphicIC(), and vector_set_.
SetCache() [2/2]
void v8::internal::IC::SetCache (DirectHandle< Name > name, Handle< Object > handler) [protected]
Definition at line 751 of file ic.cc.
                                                                 {
  SetCache(name, MaybeObjectHandle(handler));
}
References v8::internal::name.
Referenced by v8::internal::LoadIC::Load(), v8::internal::LoadGlobalIC::Load(), v8::internal::StoreIC::Store(), v8::internal::StoreGlobalIC::Store(), v8::internal::LoadIC::UpdateCaches(), and v8::internal::StoreIC::UpdateCaches().
ShouldRecomputeHandler()
bool v8::internal::IC::ShouldRecomputeHandler (DirectHandle< String > name) [protected]
Definition at line 237 of file ic.cc.
                                                         {
  if (!RecomputeHandlerForName(name)) return false;
  // This is a contextual access, always just update the handler and stay
  // monomorphic.
  if (IsGlobalIC()) return true;
  MaybeObjectDirectHandle maybe_handler =
      nexus()->FindHandlerForMap(lookup_start_object_map());
  // The current map wasn't handled yet. There's no reason to stay monomorphic,
  // *unless* we're moving from a deprecated map to its replacement, or
  // to a more general elements kind.
  // TODO(verwaest): Check if the current map is actually what the old map
  // would transition to.
  if (maybe_handler.is_null()) {
    if (!IsJSObjectMap(*lookup_start_object_map())) return false;
    Tagged<Map> first_map = FirstTargetMap();
    if (first_map.is_null()) return false;
    DirectHandle<Map> old_map(first_map, isolate());
    if (old_map->is_deprecated()) return true;
    return IsMoreGeneralElementsKindTransition(
        old_map->elements_kind(), lookup_start_object_map()->elements_kind());
  }
  return true;
}
References v8::internal::FeedbackNexus::FindHandlerForMap(), FirstTargetMap(), v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::Tagged< HeapObject >::is_null(), IsGlobalIC(), v8::internal::IsMoreGeneralElementsKindTransition(), isolate(), lookup_start_object_map(), v8::internal::name, nexus(), and RecomputeHandlerForName().
Referenced by UpdateState().
state()
State v8::internal::IC::state () const [inline]
Definition at line 38 of file ic.h.
{ return state_; }
References state_.
Referenced by v8::internal::LoadIC::Load(), v8::internal::KeyedLoadIC::Load(), v8::internal::LoadGlobalIC::Load(), SetCache(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::StoreIC::Store(), v8::internal::KeyedStoreIC::Store(), v8::internal::StoreGlobalIC::Store(), TraceIC(), TransitionMarkFromState(), v8::internal::KeyedLoadIC::UpdateLoadElement(), UpdateOneMapManyNamesIC(), UpdatePolymorphicIC(), UpdateState(), v8::internal::KeyedStoreIC::UpdateStoreElement(), and vector_needs_update().
stub_cache()
StubCache * v8::internal::IC::stub_cache () [protected]
Definition at line 836 of file ic.cc.
                          {
  // HasICs and each of the store own ICs require its own stub cache.
  // Until we create them, don't allow accessing the load/store stub caches.
  DCHECK(!IsAnyHas());
  if (IsAnyLoad()) {
    return isolate()->load_stub_cache();
  } else if (IsAnyDefineOwn()) {
    return isolate()->define_own_stub_cache();
  } else {
    DCHECK(IsAnyStore());
    return isolate()->store_stub_cache();
  }
}
References v8::internal::DCHECK(), v8::internal::Isolate::define_own_stub_cache(), IsAnyDefineOwn(), IsAnyHas(), IsAnyLoad(), IsAnyStore(), isolate(), v8::internal::Isolate::load_stub_cache(), and v8::internal::Isolate::store_stub_cache().
Referenced by UpdateMegamorphicCache().
TargetMaps()
void v8::internal::IC::TargetMaps (MapHandles * list) [inline], [protected]
Definition at line 145 of file ic.h.
                                    {
    FindTargetMaps();
    for (DirectHandle<Map> map : target_maps_) {
      list->push_back(map);
    }
  }
References FindTargetMaps(), v8::internal::DirectHandleSmallVector< T, kSize >::push_back(), and target_maps_.
Referenced by v8::internal::KeyedLoadIC::UpdateLoadElement().
TraceIC() [1/2]
void v8::internal::IC::TraceIC (const char * type, DirectHandle< Object > name) [protected]
Definition at line 108 of file ic.cc.
                                                            {
  if (V8_LIKELY(!TracingFlags::is_ic_stats_enabled())) return;
  State new_state =
      (state() == NO_FEEDBACK) ? NO_FEEDBACK : nexus()->ic_state();
  TraceIC(type, name, state(), new_state);
}
References v8::internal::FeedbackNexus::ic_state(), v8::internal::TracingFlags::is_ic_stats_enabled(), v8::internal::name, nexus(), v8::internal::NO_FEEDBACK, state(), v8::internal::tracing::type, and V8_LIKELY.
Referenced by v8::internal::LoadIC::Load(), v8::internal::KeyedLoadIC::Load(), v8::internal::LoadGlobalIC::Load(), v8::internal::KeyedLoadIC::LoadName(), v8::internal::StoreInArrayLiteralIC::Store(), v8::internal::StoreIC::Store(), v8::internal::KeyedStoreIC::Store(), v8::internal::StoreGlobalIC::Store(), v8::internal::LoadIC::UpdateCaches(), and v8::internal::StoreIC::UpdateCaches().
TraceIC() [2/2]
void v8::internal::IC::TraceIC (const char * type, DirectHandle< Object > name, State old_state, State new_state) [protected]
Definition at line 115 of file ic.cc.
                                  {
  if (V8_LIKELY(!TracingFlags::is_ic_stats_enabled())) return;
  DirectHandle<Map> map = lookup_start_object_map(); // Might be empty.
  const char* modifier = "";
  if (state() == NO_FEEDBACK) {
    modifier = "";
  } else if (IsKeyedLoadIC()) {
    KeyedAccessLoadMode mode = nexus()->GetKeyedAccessLoadMode();
    modifier = GetModifier(mode);
  } else if (IsKeyedStoreIC() || IsStoreInArrayLiteralIC() ||
             IsDefineKeyedOwnIC()) {
    KeyedAccessStoreMode mode = nexus()->GetKeyedAccessStoreMode();
    modifier = GetModifier(mode);
  }
  bool keyed_prefix = is_keyed() && !IsStoreInArrayLiteralIC();
  if (!(TracingFlags::ic_stats.load(std::memory_order_relaxed) &
        v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING)) {
    LOG(isolate(), ICEvent(type, keyed_prefix, map, name,
                           TransitionMarkFromState(old_state),
                           TransitionMarkFromState(new_state), modifier,
                           slow_stub_reason_));
    return;
  }
  JavaScriptStackFrameIterator it(isolate());
  JavaScriptFrame* frame = it.frame();
  DisallowGarbageCollection no_gc;
  Tagged<JSFunction> function = frame->function();
  ICStats::instance()->Begin();
  ICInfo& ic_info = ICStats::instance()->Current();
  ic_info.type = keyed_prefix ? "Keyed" : "";
  ic_info.type += type;
  int code_offset = 0;
  Tagged<AbstractCode> code;
  std::tie(code, code_offset) = frame->GetActiveCodeAndOffset();
  JavaScriptFrame::CollectFunctionAndOffsetForICStats(isolate(), function, code,
                                                      code_offset);
  // Reserve enough space for IC transition state, the longest length is 17.
  ic_info.state.reserve(17);
  ic_info.state = "(";
  ic_info.state += TransitionMarkFromState(old_state);
  ic_info.state += "->";
  ic_info.state += TransitionMarkFromState(new_state);
  ic_info.state += modifier;
  ic_info.state += ")";
  if (!map.is_null()) {
    ic_info.map = reinterpret_cast<void*>(map->ptr());
    ic_info.is_dictionary_map = map->is_dictionary_map();
    ic_info.number_of_own_descriptors = map->NumberOfOwnDescriptors();
    ic_info.instance_type = std::to_string(map->instance_type());
  } else {
    ic_info.map = nullptr;
  }
  // TODO(lpy) Add name as key field in ICStats.
  ICStats::instance()->End();
}
References v8::internal::ICStats::Begin(), code, v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(), v8::internal::ICStats::Current(), v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING, v8::internal::ICStats::End(), v8::internal::JavaScriptStackFrameIterator::frame(), v8::internal::JavaScriptFrame::function(), v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), v8::internal::FeedbackNexus::GetKeyedAccessLoadMode(), v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), v8::internal::anonymous_namespace{ic.cc}::GetModifier(), v8::internal::TracingFlags::ic_stats, v8::internal::ICStats::instance(), v8::internal::ICInfo::instance_type, v8::internal::ICInfo::is_dictionary_map, v8::internal::TracingFlags::is_ic_stats_enabled(), is_keyed(), v8::internal::DirectHandle< T >::is_null(), IsDefineKeyedOwnIC(), IsKeyedLoadIC(), IsKeyedStoreIC(), isolate(), IsStoreInArrayLiteralIC(), LOG, lookup_start_object_map(), v8::internal::ICInfo::map, mode(), v8::internal::name, nexus(), v8::internal::NO_FEEDBACK, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ICInfo::number_of_own_descriptors, slow_stub_reason_, v8::internal::ICInfo::state, state(), TransitionMarkFromState(), v8::internal::ICInfo::type, v8::internal::tracing::type, and V8_LIKELY.
TransitionMarkFromState()
char v8::internal::IC::TransitionMarkFromState (IC::State state) [protected]
Definition at line 55 of file ic.cc.
                                              {
  switch (state) {
    case NO_FEEDBACK:
      return 'X';
    case UNINITIALIZED:
      return '0';
    case MONOMORPHIC:
      return '1';
    case RECOMPUTE_HANDLER:
      return '^';
    case POLYMORPHIC:
      return 'P';
    case MEGAMORPHIC:
      return 'N';
    case MEGADOM:
      return 'D';
    case GENERIC:
      return 'G';
  }
  UNREACHABLE();
}
References v8::internal::GENERIC, v8::internal::MEGADOM, v8::internal::MEGAMORPHIC, v8::internal::MONOMORPHIC, v8::internal::NO_FEEDBACK, v8::internal::POLYMORPHIC, v8::internal::RECOMPUTE_HANDLER, state(), v8::internal::UNINITIALIZED, and v8::internal::UNREACHABLE().
Referenced by TraceIC().
TypeError()
MaybeDirectHandle< Object > v8::internal::IC::TypeError (MessageTemplate index, Handle< Object > object, Handle< Object > key) [protected]
Definition at line 292 of file ic.cc.
                                                            {
  HandleScope scope(isolate());
  THROW_NEW_ERROR(isolate(), NewTypeError(index, key, object));
}
References v8::internal::index, isolate(), v8::internal::key, and THROW_NEW_ERROR.
Referenced by v8::internal::LoadIC::Load(), v8::internal::StoreIC::Store(), and v8::internal::StoreGlobalIC::Store().
update_lookup_start_object_map()
void v8::internal::IC::update_lookup_start_object_map (DirectHandle< Object > object) [inline], [protected]
Definition at line 20 of file ic-inl.h.
                                                                   {
  if (IsSmi(*object)) {
    lookup_start_object_map_ = isolate_->factory()->heap_number_map();
  } else {
    lookup_start_object_map_ =
        handle(Cast<HeapObject>(*object)->map(), isolate_);
  }
}
References v8::internal::Isolate::factory(), v8::internal::handle(), isolate_, v8::internal::IsSmi(), and lookup_start_object_map_.
Referenced by v8::internal::LoadIC::Load(), v8::internal::StoreIC::LookupForWrite(), v8::internal::StoreIC::Store(), and UpdateState().
UpdateMegaDOMIC()
bool v8::internal::IC::UpdateMegaDOMIC (const MaybeObjectDirectHandle & handler, DirectHandle< Name > name) [protected]
Definition at line 552 of file ic.cc.
                                                  {
  if (!v8_flags.mega_dom_ic) return false;
  // TODO(gsathya): Enable fuzzing once this feature is more stable.
  if (v8_flags.fuzzing) return false;
  // TODO(gsathya): Support KeyedLoadIC, StoreIC and KeyedStoreIC.
  if (!IsLoadIC()) return false;
  // Check if DOM protector cell is valid.
  if (!Protectors::IsMegaDOMIntact(isolate())) return false;
  // Check if current lookup object is an API object
  DirectHandle<Map> map = lookup_start_object_map();
  if (!InstanceTypeChecker::IsJSApiObject(map->instance_type())) return false;
  Handle<Object> accessor_obj;
  // TODO(gsathya): Check if there are overloads possible for this accessor and
  // transition only if it isn't possible.
  if (!accessor().ToHandle(&accessor_obj)) return false;
  // TODO(gsathya): This is also created in IC::ComputeHandler, find a way to
  // reuse it here.
  CallOptimization call_optimization(isolate(), accessor_obj);
  // Check if accessor is an API function
  if (!call_optimization.is_simple_api_call()) return false;
  // Check if accessor requires access checks
  if (call_optimization.accept_any_receiver()) return false;
  // Check if accessor requires signature checks
  if (!call_optimization.requires_signature_check()) return false;
  // Check if the receiver is the holder
  CallOptimization::HolderLookup holder_lookup;
  call_optimization.LookupHolderOfExpectedType(isolate(), map, &holder_lookup);
  if (holder_lookup != CallOptimization::kHolderIsReceiver) return false;
  DirectHandle<NativeContext> accessor_context =
      GetAccessorContext(call_optimization, *map, isolate());
  DirectHandle<FunctionTemplateInfo> fti;
  if (IsJSFunction(*accessor_obj)) {
    fti = direct_handle(
        Cast<JSFunction>(*accessor_obj)->shared()->api_func_data(), isolate());
  } else {
    fti = Cast<FunctionTemplateInfo>(accessor_obj);
  }
  DirectHandle<MegaDomHandler> new_handler =
      isolate()->factory()->NewMegaDomHandler(
          MaybeObjectDirectHandle::Weak(fti),
          MaybeObjectDirectHandle::Weak(accessor_context));
  nexus()->ConfigureMegaDOM(MaybeObjectDirectHandle(new_handler));
  return true;
}
References v8::internal::CallOptimization::accept_any_receiver(), accessor(), v8::internal::FeedbackNexus::ConfigureMegaDOM(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{ic.cc}::GetAccessorContext(), v8::internal::CallOptimization::is_simple_api_call(), IsLoadIC(), isolate(), v8::internal::CallOptimization::kHolderIsReceiver, lookup_start_object_map(), v8::internal::CallOptimization::LookupHolderOfExpectedType(), v8::internal::Factory::NewMegaDomHandler(), nexus(), v8::internal::CallOptimization::requires_signature_check(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::v8_flags, and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by SetCache().
UpdateMegamorphicCache()
void v8::internal::IC::UpdateMegamorphicCache (DirectHandle< Map > map, DirectHandle< Name > name, const MaybeObjectDirectHandle & handler) [protected]
Definition at line 850 of file ic.cc.
                                                                        {
  if (!IsAnyHas()) {
    stub_cache()->Set(*name, *map, *handler);
  }
}
References IsAnyHas(), v8::internal::name, v8::internal::StubCache::Set(), and stub_cache().
Referenced by CopyICToMegamorphicCache(), and SetCache().
UpdateMonomorphicIC()
void v8::internal::IC::UpdateMonomorphicIC (const MaybeObjectDirectHandle & handler, DirectHandle< Name > name) [protected]
Definition at line 720 of file ic.cc.
                                                      {
  DCHECK(IsHandler(*handler));
  ConfigureVectorState(name, lookup_start_object_map(), handler);
}
References ConfigureVectorState(), v8::internal::DCHECK(), IsHandler(), lookup_start_object_map(), and v8::internal::name.
Referenced by SetCache().
UpdateOneMapManyNamesIC()
bool v8::internal::IC::UpdateOneMapManyNamesIC (DirectHandle< Name > new_name) [protected]
Definition at line 611 of file ic.cc.
                                                            {
#if V8_ENABLE_WEBASSEMBLY
  if (state() != MONOMORPHIC) return false;
  if (!IsKeyedLoadIC() && !IsKeyedStoreIC()) return false;
  // For JS objects, using the generic stub is faster. Wasm objects benefit
  // from collecting a map that the optimizing compiler can use.
  Tagged<Map> old_map = nexus()->GetFirstMap();
  if (old_map.is_null() || !IsWasmObjectMap(old_map)) return false;
  if (old_map != *lookup_start_object_map()) return false;
  Tagged<Name> old_name = nexus()->GetName();
  if (old_name.is_null()) return false; // Saw indexed access before.
  if (old_name == *new_name) return false; // Something else is wrong.
  DirectHandle<Smi> generic = IsKeyedLoadIC()
                                  ? LoadHandler::LoadGeneric(isolate())
                                  : StoreHandler::StoreGeneric(isolate());
  ConfigureVectorState(DirectHandle<Name>(), lookup_start_object_map(),
                       generic);
  return true;
#else
  return false;
#endif // V8_ENABLE_WEBASSEMBLY
}
References ConfigureVectorState(), v8::internal::FeedbackNexus::GetFirstMap(), v8::internal::FeedbackNexus::GetName(), v8::internal::Tagged< HeapObject >::is_null(), IsKeyedLoadIC(), IsKeyedStoreIC(), isolate(), v8::internal::LoadHandler::LoadGeneric(), lookup_start_object_map(), v8::internal::MONOMORPHIC, nexus(), state(), and v8::internal::StoreHandler::StoreGeneric().
Referenced by SetCache().
UpdatePolymorphicIC()
bool v8::internal::IC::UpdatePolymorphicIC (DirectHandle< Name > name, const MaybeObjectDirectHandle & handler) [protected]
Definition at line 634 of file ic.cc.
                                                                     {
  DCHECK(IsHandler(*handler));
  if (is_keyed() && state() != RECOMPUTE_HANDLER) {
    if (nexus()->GetName() != *name) return false;
  }
  DirectHandle<Map> map = lookup_start_object_map();
  MapsAndHandlers maps_and_handlers(isolate());
  maps_and_handlers.reserve(v8_flags.max_valid_polymorphic_map_count);
  int deprecated_maps = 0;
  int handler_to_overwrite = -1;
  {
    DisallowGarbageCollection no_gc;
    int i = 0;
    for (FeedbackIterator it(nexus()); !it.done(); it.Advance()) {
      if (it.handler().IsCleared()) continue;
      MaybeObjectDirectHandle existing_handler(it.handler(), isolate());
      DirectHandle<Map> existing_map(it.map(), isolate());
      maps_and_handlers.emplace_back(existing_map, existing_handler);
      if (existing_map->is_deprecated()) {
        // Filter out deprecated maps to ensure their instances get migrated.
        deprecated_maps++;
      } else if (map.is_identical_to(existing_map)) {
        // If both map and handler stayed the same (and the name is also the
        // same as checked above, for keyed accesses), we're not progressing
        // in the lattice and need to go MEGAMORPHIC instead. There's one
        // exception to this rule, which is when we're in RECOMPUTE_HANDLER
        // state, there we allow to migrate to a new handler.
        if (handler.is_identical_to(existing_handler) &&
            state() != RECOMPUTE_HANDLER) {
          return false;
        }
        // If the receiver type is already in the polymorphic IC, this indicates
        // there was a prototoype chain failure. In that case, just overwrite
        // the handler.
        handler_to_overwrite = i;
      } else if (handler_to_overwrite == -1 &&
                 IsTransitionOfMonomorphicTarget(*existing_map, *map)) {
        handler_to_overwrite = i;
      }
      i++;
    }
    DCHECK_LE(i, maps_and_handlers.size());
  }
  int number_of_maps = static_cast<int>(maps_and_handlers.size());
  int number_of_valid_maps =
      number_of_maps - deprecated_maps - (handler_to_overwrite != -1);
  if (number_of_valid_maps >= v8_flags.max_valid_polymorphic_map_count) {
    return false;
  }
  if (deprecated_maps >= v8_flags.max_valid_polymorphic_map_count) {
    return false;
  }
  if (number_of_maps == 0 && state() != MONOMORPHIC && state() != POLYMORPHIC) {
    return false;
  }
  number_of_valid_maps++;
  if (number_of_valid_maps == 1) {
    ConfigureVectorState(name, lookup_start_object_map(), handler);
  } else {
    if (is_keyed() && nexus()->GetName() != *name) return false;
    if (handler_to_overwrite >= 0) {
      maps_and_handlers.set_handler(handler_to_overwrite, handler);
      if (!map.is_identical_to(
              maps_and_handlers.maps()[handler_to_overwrite])) {
        maps_and_handlers.set_map(handler_to_overwrite, map);
      }
    } else {
      maps_and_handlers.emplace_back(map, handler);
    }
    ConfigureVectorState(name, maps_and_handlers);
  }
  return true;
}
References ConfigureVectorState(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::FeedbackIterator::done(), v8::internal::MapsAndHandlers::emplace_back(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MaybeObjectDirectHandle::is_identical_to(), v8::internal::DirectHandle< T >::is_identical_to(), is_keyed(), IsHandler(), isolate(), IsTransitionOfMonomorphicTarget(), lookup_start_object_map(), v8::internal::MapsAndHandlers::maps(), v8::internal::MONOMORPHIC, v8::internal::name, nexus(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::POLYMORPHIC, v8::internal::RECOMPUTE_HANDLER, v8::internal::MapsAndHandlers::reserve(), v8::internal::MapsAndHandlers::set_handler(), v8::internal::MapsAndHandlers::set_map(), v8::internal::MapsAndHandlers::size(), state(), and v8::internal::v8_flags.
Referenced by SetCache().
UpdateState()
void v8::internal::IC::UpdateState (DirectHandle< Object > lookup_start_object, DirectHandle< Object > name)
Definition at line 276 of file ic.cc.
                                                {
  if (state() == NO_FEEDBACK) return;
  update_lookup_start_object_map(lookup_start_object);
  if (!IsString(*name)) return;
  if (state() != MONOMORPHIC && state() != POLYMORPHIC) return;
  if (IsNullOrUndefined(*lookup_start_object, isolate())) return;
  // Remove the target from the code cache if it became invalid
  // because of changes in the prototype chain to avoid hitting it
  // again.
  if (ShouldRecomputeHandler(Cast<String>(name))) {
    MarkRecomputeHandler(name);
  }
}
References v8::internal::IsNullOrUndefined(), isolate(), MarkRecomputeHandler(), v8::internal::MONOMORPHIC, v8::internal::name, v8::internal::NO_FEEDBACK, v8::internal::POLYMORPHIC, ShouldRecomputeHandler(), state(), and update_lookup_start_object_map().
Referenced by v8::internal::LoadIC::Load(), and v8::internal::RUNTIME_FUNCTION().
vector_needs_update()
bool v8::internal::IC::vector_needs_update () [inline], [protected]
Definition at line 39 of file ic-inl.h.
                             {
  if (state() == InlineCacheState::NO_FEEDBACK) return false;
  return (!vector_set_ && (state() != InlineCacheState::MEGAMORPHIC ||
                           nexus()->GetKeyType() != IcCheckType::kElement));
}
References v8::internal::kElement, v8::internal::MEGAMORPHIC, nexus(), v8::internal::NO_FEEDBACK, state(), and vector_set_.
Referenced by v8::internal::KeyedLoadIC::Load(), v8::internal::KeyedLoadIC::LoadName(), v8::internal::StoreInArrayLiteralIC::Store(), and v8::internal::KeyedStoreIC::Store().
Member Data Documentation
accessor_
MaybeHandle<Object> v8::internal::IC::accessor_ [private]
Definition at line 174 of file ic.h.
Referenced by accessor(), and set_accessor().
isolate_
Isolate* v8::internal::IC::isolate_ [private]
Definition at line 167 of file ic.h.
Referenced by isolate(), IsTransitionOfMonomorphicTarget(), and update_lookup_start_object_map().
kind_
FeedbackSlotKind v8::internal::IC::kind_ [private]
Definition at line 172 of file ic.h.
Referenced by IC(), IsDefineKeyedOwnIC(), IsDefineNamedOwnIC(), IsKeyedHasIC(), IsKeyedLoadIC(), IsKeyedStoreIC(), IsLoadGlobalIC(), IsLoadIC(), IsSetNamedIC(), IsStoreGlobalIC(), IsStoreInArrayLiteralIC(), and kind().
lookup_start_object_map_
Handle<Map> v8::internal::IC::lookup_start_object_map_ [private]
Definition at line 173 of file ic.h.
Referenced by lookup_start_object_map(), and update_lookup_start_object_map().
nexus_
FeedbackNexus v8::internal::IC::nexus_ [private]
Definition at line 180 of file ic.h.
Referenced by IC(), and nexus().
old_state_
State v8::internal::IC::old_state_ [private]
Definition at line 170 of file ic.h.
Referenced by IC(), and MarkRecomputeHandler().
slow_stub_reason_
const char* v8::internal::IC::slow_stub_reason_ [private]
Definition at line 178 of file ic.h.
Referenced by set_slow_stub_reason(), and TraceIC().
state_
State v8::internal::IC::state_ [private]
Definition at line 171 of file ic.h.
Referenced by IC(), MarkRecomputeHandler(), and state().
target_maps_
MapHandles v8::internal::IC::target_maps_ [private]
Definition at line 175 of file ic.h.
Referenced by FindTargetMaps(), FirstTargetMap(), and TargetMaps().
target_maps_set_
bool v8::internal::IC::target_maps_set_ [private]
Definition at line 176 of file ic.h.
Referenced by FindTargetMaps().
vector_set_
bool v8::internal::IC::vector_set_ [private]
Definition at line 169 of file ic.h.
Referenced by is_vector_set(), OnFeedbackChanged(), SetCache(), and vector_needs_update().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic-inl.h
/mnt/V8SourceCode/src/ic/ic.cc