v8::internal::compiler::NodeOrigin Class Reference
#include <node-origin-table.h>
Public Types
enum OriginKind { kWasmBytecode
, kGraphNode
, kJSBytecode
 }
Public Member Functions
NodeOrigin (const char *phase_name, const char *reducer_name, NodeId created_from)
NodeOrigin (const char *phase_name, const char *reducer_name, OriginKind origin_kind, uint64_t created_from)
NodeOrigin (const NodeOrigin &other) V8_NOEXCEPT=default
NodeOrigin & operator= (const NodeOrigin &other) V8_NOEXCEPT=default
bool IsKnown ()
int64_t created_from () const
const char * reducer_name () const
const char * phase_name () const
OriginKind origin_kind () const
bool operator== (const NodeOrigin &o) const
void PrintJson (std::ostream &out) const
Static Public Member Functions
static NodeOrigin Unknown ()
Private Member Functions
NodeOrigin ()
Private Attributes
const char * phase_name_
const char * reducer_name_
OriginKind origin_kind_
int64_t created_from_
Detailed Description
Definition at line 17 of file node-origin-table.h.
Member Enumeration Documentation
OriginKind
enum v8::internal::compiler::NodeOrigin::OriginKind
Enumerator
kWasmBytecode
kGraphNode
kJSBytecode
Definition at line 19 of file node-origin-table.h.
{ kWasmBytecode, kGraphNode, kJSBytecode };
Constructor & Destructor Documentation
NodeOrigin() [1/4]
v8::internal::compiler::NodeOrigin::NodeOrigin (const char * phase_name, const char * reducer_name, NodeId created_from) [inline]
Definition at line 20 of file node-origin-table.h.
      : phase_name_(phase_name),
        reducer_name_(reducer_name),
        origin_kind_(kGraphNode),
        created_from_(created_from) {}
NodeOrigin() [2/4]
v8::internal::compiler::NodeOrigin::NodeOrigin (const char * phase_name, const char * reducer_name, OriginKind origin_kind, uint64_t created_from) [inline]
Definition at line 27 of file node-origin-table.h.
      : phase_name_(phase_name),
        reducer_name_(reducer_name),
        origin_kind_(origin_kind),
        created_from_(created_from) {}
NodeOrigin() [3/4]
v8::internal::compiler::NodeOrigin::NodeOrigin (const NodeOrigin & other) [default]
NodeOrigin() [4/4]
v8::internal::compiler::NodeOrigin::NodeOrigin () [inline], [private]
Definition at line 52 of file node-origin-table.h.
      : phase_name_(""),
        reducer_name_(""),
        created_from_(std::numeric_limits<int64_t>::min()) {}
Referenced by Unknown().
Member Function Documentation
created_from()
int64_t v8::internal::compiler::NodeOrigin::created_from () const [inline]
Definition at line 39 of file node-origin-table.h.
{ return created_from_; }
References created_from_.
Referenced by PrintJson().
IsKnown()
bool v8::internal::compiler::NodeOrigin::IsKnown () [inline]
Definition at line 38 of file node-origin-table.h.
{ return created_from_ >= 0; }
References created_from_.
Referenced by v8::internal::compiler::NodeOriginTable::PrintJson(), v8::internal::compiler::JSONGraphWriter::PrintNode(), and v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes().
operator=()
NodeOrigin& v8::internal::compiler::NodeOrigin::operator= (const NodeOrigin & other) [default]
operator==()
bool v8::internal::compiler::NodeOrigin::operator== (const NodeOrigin & o) const [inline]
Definition at line 45 of file node-origin-table.h.
                                             {
    return reducer_name_ == o.reducer_name_ && created_from_ == o.created_from_;
  }
References created_from_, and reducer_name_.
origin_kind()
OriginKind v8::internal::compiler::NodeOrigin::origin_kind () const [inline]
Definition at line 43 of file node-origin-table.h.
{ return origin_kind_; }
References origin_kind_.
phase_name()
const char* v8::internal::compiler::NodeOrigin::phase_name () const [inline]
Definition at line 41 of file node-origin-table.h.
{ return phase_name_; }
References phase_name_.
Referenced by PrintJson().
PrintJson()
void v8::internal::compiler::NodeOrigin::PrintJson (std::ostream & out) const
Definition at line 14 of file node-origin-table.cc.
                                                {
  out << "{ ";
  switch (origin_kind_) {
    case kGraphNode:
      out << "\"nodeId\" : ";
      break;
    case kWasmBytecode:
    case kJSBytecode:
      out << "\"bytecodePosition\" : ";
      break;
  }
  out << created_from();
  out << ", \"reducer\" : \"" << reducer_name() << "\"";
  out << ", \"phase\" : \"" << phase_name() << "\"";
  out << "}";
}
References created_from(), kGraphNode, kJSBytecode, kWasmBytecode, origin_kind_, phase_name(), and reducer_name().
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::NodeOriginTable::PrintJson().
reducer_name()
const char* v8::internal::compiler::NodeOrigin::reducer_name () const [inline]
Definition at line 40 of file node-origin-table.h.
{ return reducer_name_; }
References reducer_name_.
Referenced by PrintJson().
Unknown()
static NodeOrigin v8::internal::compiler::NodeOrigin::Unknown () [inline], [static]
Definition at line 36 of file node-origin-table.h.
{ return NodeOrigin(); }
References NodeOrigin().
Referenced by v8::internal::compiler::NodeOriginTable::UnknownNodeOrigin().
Member Data Documentation
created_from_
int64_t v8::internal::compiler::NodeOrigin::created_from_ [private]
Definition at line 59 of file node-origin-table.h.
Referenced by created_from(), IsKnown(), and operator==().
origin_kind_
OriginKind v8::internal::compiler::NodeOrigin::origin_kind_ [private]
Definition at line 58 of file node-origin-table.h.
Referenced by origin_kind(), and PrintJson().
phase_name_
const char* v8::internal::compiler::NodeOrigin::phase_name_ [private]
Definition at line 56 of file node-origin-table.h.
Referenced by phase_name().
reducer_name_
const char* v8::internal::compiler::NodeOrigin::reducer_name_ [private]
Definition at line 57 of file node-origin-table.h.
Referenced by operator==(), and reducer_name().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-origin-table.h
/mnt/V8SourceCode/src/compiler/node-origin-table.cc