v8::internal::compiler::FeedbackParameter Class Reference
#include <js-operator.h>
Public Member Functions
FeedbackParameter (FeedbackSource const &feedback)
FeedbackSource const & feedback () const
Private Attributes
FeedbackSource const feedback_
Detailed Description
Definition at line 424 of file js-operator.h.
Constructor & Destructor Documentation
FeedbackParameter()
v8::internal::compiler::FeedbackParameter::FeedbackParameter (FeedbackSource const & feedback) [inline], [explicit]
Definition at line 426 of file js-operator.h.
      : feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::FeedbackParameter::feedback () const [inline]
Definition at line 429 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::JSBinopReduction::GetBinaryOperationHint(), v8::internal::compiler::JSBinopReduction::GetCompareOperationHint(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnPropertyInLiteral(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreInArrayLiteral().
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::FeedbackParameter::feedback_ [private]
Definition at line 432 of file js-operator.h.
Referenced by feedback().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h