v8::internal::PrototypeInfo Class Reference
#include <prototype-info.h>
Classes
class BodyDescriptor
Public Types
enum CachedHandlerIndex { kLoadNonExistentHandlerDefault = 0
, kLoadNonExistentHandlerWithLookupOnReceiver
, kCachedHandlerCount
 }
Public Member Functions
Tagged< MaybeObject > ObjectCreateMap (AcquireLoadTag)
Tagged< MaybeObject > ObjectCreateMap ()
Tagged< MaybeObject > GetDerivedMap (DirectHandle< Map > from)
Static Public Member Functions
static void SetObjectCreateMap (DirectHandle< PrototypeInfo > info, DirectHandle< Map > map, Isolate *isolate)
static void AddDerivedMap (DirectHandle< PrototypeInfo > info, DirectHandle< Map > to, Isolate *isolate)
static bool IsPrototypeInfoFast (Tagged< Object > object)
Static Public Attributes
static constexpr int kSize
static const int UNREGISTERED = -1
Detailed Description
Definition at line 22 of file prototype-info.h.
Member Enumeration Documentation
CachedHandlerIndex
enum v8::internal::PrototypeInfo::CachedHandlerIndex
Enumerator
kLoadNonExistentHandlerDefault
kLoadNonExistentHandlerWithLookupOnReceiver
kCachedHandlerCount
Definition at line 26 of file prototype-info.h.
                          {
    // No access check, no lookup on receiver.
    kLoadNonExistentHandlerDefault = 0,
    kLoadNonExistentHandlerWithLookupOnReceiver,
    kCachedHandlerCount,
  };
Member Function Documentation
AddDerivedMap()
void v8::internal::PrototypeInfo::AddDerivedMap (DirectHandle< PrototypeInfo > info, DirectHandle< Map > to, Isolate * isolate) [inline], [static]
Definition at line 101 of file prototype-info-inl.h.
                                                                          {
  if (IsUndefined(info->derived_maps())) {
    // Index 0 is the map for object create
    Tagged<WeakArrayList> derived = *isolate->factory()->NewWeakArrayList(2);
    // GetConstructMap assumes a weak pointer.
    derived->Set(0, ClearedValue(isolate));
    derived->Set(1, MakeWeak(*to));
    derived->set_length(2);
    info->set_derived_maps(derived, kReleaseStore);
    return;
  }
  auto derived = handle(Cast<WeakArrayList>(info->derived_maps()), isolate);
  // Index 0 is the map for object create
  int i = 1;
  for (; i < derived->length(); ++i) {
    Tagged<MaybeObject> el = derived->Get(i);
    if (el.IsCleared()) {
      derived->Set(i, MakeWeak(*to));
      return;
    }
  }
  auto bigger = WeakArrayList::EnsureSpace(isolate, derived, i + 1);
  bigger->Set(i, MakeWeak(*to));
  bigger->set_length(i + 1);
  if (*bigger != *derived) {
    info->set_derived_maps(*bigger, kReleaseStore);
  }
}
References v8::internal::ClearedValue(), v8::internal::WeakArrayList::EnsureSpace(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::kReleaseStore, v8::internal::MakeWeak(), and v8::internal::Factory::NewWeakArrayList().
Referenced by v8::internal::Map::GetDerivedMap().
GetDerivedMap()
Tagged< MaybeObject > v8::internal::PrototypeInfo::GetDerivedMap (DirectHandle< Map > from) [inline]
Definition at line 80 of file prototype-info-inl.h.
                                                                       {
  if (IsUndefined(derived_maps())) {
    return Tagged<MaybeObject>();
  }
  auto derived = Cast<WeakArrayList>(derived_maps());
  // Index 0 is the map for object create
  for (int i = 1; i < derived->length(); ++i) {
    Tagged<MaybeObject> el = derived->Get(i);
    Tagged<Map> map_obj;
    if (el.GetHeapObjectIfWeak(&map_obj)) {
      Tagged<Map> to = Cast<Map>(map_obj);
      if (to->GetConstructor() == from->GetConstructor() &&
          to->instance_type() == from->instance_type()) {
        return el;
      }
    }
  }
  return Tagged<MaybeObject>();
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
IsPrototypeInfoFast()
bool v8::internal::PrototypeInfo::IsPrototypeInfoFast (Tagged< Object > object) [inline], [static]
Definition at line 132 of file prototype-info-inl.h.
                                                             {
  bool is_proto_info = object != Smi::zero();
  DCHECK_EQ(is_proto_info, IsPrototypeInfo(object));
  return is_proto_info;
}
References DCHECK_EQ, and v8::internal::Smi::zero().
Referenced by v8::internal::Map::has_prototype_info(), and v8::internal::Map::TryGetPrototypeInfo().
ObjectCreateMap() [1/2]
Tagged<MaybeObject> v8::internal::PrototypeInfo::ObjectCreateMap () [inline]
ObjectCreateMap() [2/2]
Tagged< MaybeObject > v8::internal::PrototypeInfo::ObjectCreateMap (AcquireLoadTag tag) [inline]
Definition at line 50 of file prototype-info-inl.h.
                                                                     {
  auto derived = derived_maps(tag);
  if (IsUndefined(derived)) {
    return Tagged<MaybeObject>();
  }
  // Index 0 is the map for object create
  Tagged<WeakArrayList> derived_list = Cast<WeakArrayList>(derived);
  DCHECK_GT(derived_list->length(), 0);
  Tagged<MaybeObject> el = derived_list->Get(0);
  DCHECK(el.IsWeakOrCleared());
  return el;
}
References v8::internal::DCHECK(), DCHECK_GT, and v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared().
SetObjectCreateMap()
void v8::internal::PrototypeInfo::SetObjectCreateMap (DirectHandle< PrototypeInfo > info, DirectHandle< Map > map, Isolate * isolate) [inline], [static]
Definition at line 64 of file prototype-info-inl.h.
                                                         {
  if (IsUndefined(info->derived_maps())) {
    Tagged<WeakArrayList> derived = *isolate->factory()->NewWeakArrayList(1);
    derived->Set(0, MakeWeak(*map));
    derived->set_length(1);
    info->set_derived_maps(derived, kReleaseStore);
  } else {
    Tagged<WeakArrayList> derived = Cast<WeakArrayList>(info->derived_maps());
    DCHECK(derived->Get(0).IsCleared());
    DCHECK_GT(derived->length(), 0);
    derived->Set(0, MakeWeak(*map));
  }
}
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::Isolate::factory(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::kReleaseStore, v8::internal::MakeWeak(), and v8::internal::Factory::NewWeakArrayList().
Referenced by v8::internal::Map::GetObjectCreateMap().
Member Data Documentation
kSize
constexpr int v8::internal::PrototypeInfo::kSize [static], [constexpr]
Initial value:
=
      kCachedHandlerOffset + kCachedHandlerCount * kTaggedSize
Definition at line 34 of file prototype-info.h.
UNREGISTERED
const int v8::internal::PrototypeInfo::UNREGISTERED = -1 [static]
Definition at line 37 of file prototype-info.h.
Referenced by v8::internal::JSObject::LazyRegisterPrototypeUser(), v8::internal::Factory::NewPrototypeInfo(), v8::internal::JSObject::UnregisterPrototypeUser(), and v8::internal::JSObject::UpdatePrototypeUserRegistration().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/prototype-info.h
/mnt/V8SourceCode/src/objects/prototype-info-inl.h