v8::internal::OnStackReplacementDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::TaggedSigned()) static const expr inline Register MaybeTargetCodeRegister()
Static Public Member Functions
static constexpr Register ExpectedParameterCountRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 2397 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::OnStackReplacementDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::TaggedSigned()) const
ExpectedParameterCountRegister()
constexpr Register v8::internal::OnStackReplacementDescriptor::ExpectedParameterCountRegister () [inline], [static], [constexpr]
Definition at line 531 of file interface-descriptors-inl.h.
                                                             {
  return registers()[1];
}
References registers().
registers()
constexpr auto v8::internal::OnStackReplacementDescriptor::registers () [inline], [static], [constexpr]
Definition at line 500 of file interface-descriptors-inl.h.
                                                       {
#if V8_TARGET_ARCH_MIPS64
  return RegisterArray(kReturnRegister0, kJavaScriptCallArgCountRegister,
                       kJavaScriptCallTargetRegister,
                       kJavaScriptCallCodeStartRegister,
                       kJavaScriptCallNewTargetRegister);
#else
  return DefaultRegisterArray();
#endif
}
References v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJavaScriptCallCodeStartRegister, v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::kJavaScriptCallTargetRegister, v8::internal::kReturnRegister0, and v8::internal::RegisterArray().
Referenced by ExpectedParameterCountRegister().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h