v8::internal::torque::ImplementationVisitor::StackScope Class Reference
Public Member Functions
StackScope (ImplementationVisitor *visitor)
VisitResult Yield (VisitResult result)
void Close ()
~StackScope ()
Private Attributes
ImplementationVisitor * visitor_
BottomOffset base_
bool closed_ = false
Detailed Description
Definition at line 632 of file implementation-visitor.h.
Constructor & Destructor Documentation
StackScope()
v8::internal::torque::ImplementationVisitor::StackScope::StackScope (ImplementationVisitor * visitor) [inline], [explicit]
Definition at line 634 of file implementation-visitor.h.
                                                        : visitor_(visitor) {
      base_ = visitor_->assembler().CurrentStack().AboveTop();
    }
 StackScope()
v8::internal::torque::ImplementationVisitor::StackScope::~StackScope () [inline]
Definition at line 665 of file implementation-visitor.h.
                  {
      if (closed_) {
        DCHECK_IMPLIES(
            !visitor_->assembler().CurrentBlockIsComplete(),
            base_ == visitor_->assembler().CurrentStack().AboveTop());
      } else {
        Close();
      }
    }
References DCHECK_IMPLIES.
Member Function Documentation
Close()
void v8::internal::torque::ImplementationVisitor::StackScope::Close () [inline]
Definition at line 657 of file implementation-visitor.h.
                 {
      DCHECK(!closed_);
      closed_ = true;
      if (!visitor_->assembler().CurrentBlockIsComplete()) {
        visitor_->assembler().DropTo(base_);
      }
    }
References v8::internal::DCHECK().
Yield()
VisitResult v8::internal::torque::ImplementationVisitor::StackScope::Yield (VisitResult result) [inline]
Definition at line 637 of file implementation-visitor.h.
                                          {
      DCHECK(!closed_);
      closed_ = true;
      if (!result.IsOnStack()) {
        if (!visitor_->assembler().CurrentBlockIsComplete()) {
          visitor_->assembler().DropTo(base_);
        }
        return result;
      }
      DCHECK_LE(base_, result.stack_range().begin());
      DCHECK_LE(result.stack_range().end(),
                visitor_->assembler().CurrentStack().AboveTop());
      visitor_->assembler().DropTo(result.stack_range().end());
      visitor_->assembler().DeleteRange(
          StackRange{base_, result.stack_range().begin()});
      base_ = visitor_->assembler().CurrentStack().AboveTop();
      return VisitResult(result.type(), visitor_->assembler().TopRange(
                                            result.stack_range().Size()));
    }
References v8::internal::compiler::begin(), v8::internal::DCHECK(), DCHECK_LE, and v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), v8::internal::torque::ImplementationVisitor::GenerateExpressionBranch(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert(), v8::internal::torque::ImplementationVisitor::GeneratePointerCall(), and v8::internal::torque::ImplementationVisitor::Visit().
Member Data Documentation
base_
BottomOffset v8::internal::torque::ImplementationVisitor::StackScope::base_ [private]
Definition at line 677 of file implementation-visitor.h.
closed_
bool v8::internal::torque::ImplementationVisitor::StackScope::closed_ = false [private]
Definition at line 678 of file implementation-visitor.h.
visitor_
ImplementationVisitor* v8::internal::torque::ImplementationVisitor::StackScope::visitor_ [private]
Definition at line 676 of file implementation-visitor.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.h