v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::NoThrowingScopeRequired Class Reference
Public Member Functions
NoThrowingScopeRequired (maglev::NodeBase *node)
Detailed Description
Definition at line 5944 of file turbolev-graph-builder.cc.
Constructor & Destructor Documentation
NoThrowingScopeRequired()
v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::NoThrowingScopeRequired::NoThrowingScopeRequired (maglev::NodeBase * node) [inline], [explicit]
Definition at line 5946 of file turbolev-graph-builder.cc.
                                {
   public:
    explicit NoThrowingScopeRequired(maglev::NodeBase* node) {
      // If this DCHECK fails, then the caller should instead use a
      // ThrowingScope. Additionally, all of the calls it contains should
References v8::internal::maglev::OpProperties::can_throw(), v8::internal::DCHECK(), and v8::internal::maglev::NodeBase::properties().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/turbolev-graph-builder.cc