v8::internal::compiler::SlackTrackingPrediction Class Reference
#include <compilation-dependencies.h>
Public Member Functions
SlackTrackingPrediction (MapRef initial_map, int instance_size)
int inobject_property_count () const
int instance_size () const
Private Attributes
int instance_size_
int inobject_property_count_
Detailed Description
Definition at line 17 of file compilation-dependencies.h.
Constructor & Destructor Documentation
SlackTrackingPrediction()
v8::internal::compiler::SlackTrackingPrediction::SlackTrackingPrediction (MapRef initial_map, int instance_size)
Definition at line 1609 of file compilation-dependencies.cc.
    : instance_size_(instance_size),
      inobject_property_count_(
          (instance_size >> kTaggedSizeLog2) -
          initial_map.GetInObjectPropertiesStartInWords()) {}
Member Function Documentation
inobject_property_count()
int v8::internal::compiler::SlackTrackingPrediction::inobject_property_count () const [inline]
Definition at line 21 of file compilation-dependencies.h.
{ return inobject_property_count_; }
References inobject_property_count_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject().
instance_size()
int v8::internal::compiler::SlackTrackingPrediction::instance_size () const [inline]
Definition at line 22 of file compilation-dependencies.h.
{ return instance_size_; }
References instance_size_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArray(), v8::internal::maglev::MaglevGraphBuilder::CreateJSConstructor(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject().
Member Data Documentation
inobject_property_count_
int v8::internal::compiler::SlackTrackingPrediction::inobject_property_count_ [private]
Definition at line 26 of file compilation-dependencies.h.
Referenced by inobject_property_count().
instance_size_
int v8::internal::compiler::SlackTrackingPrediction::instance_size_ [private]
Definition at line 25 of file compilation-dependencies.h.
Referenced by instance_size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.h
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc