v8::internal::SourceRangeMap Class Reference
#include <ast-source-ranges.h>
Public Member Functions
SourceRangeMap (Zone *zone)
AstNodeSourceRanges * Find (ZoneObject *node)
Private Attributes
ZoneMap< ZoneObject *, AstNodeSourceRanges * > map_
Detailed Description
Definition at line 423 of file ast-source-ranges.h.
Constructor & Destructor Documentation
SourceRangeMap()
v8::internal::SourceRangeMap::SourceRangeMap (Zone * zone) [inline], [explicit]
Definition at line 425 of file ast-source-ranges.h.
: map_(zone) {}
Member Function Documentation
Find()
AstNodeSourceRanges* v8::internal::SourceRangeMap::Find (ZoneObject * node) [inline]
Definition at line 427 of file ast-source-ranges.h.
                                              {
    auto it = map_.find(node);
    if (it == map_.end()) return nullptr;
    return it->second;
  }
References map_.
Referenced by v8::internal::interpreter::BlockCoverageBuilder::AllocateBlockCoverageSlot(), v8::internal::interpreter::BlockCoverageBuilder::AllocateConditionalChainBlockCoverageSlot(), v8::internal::interpreter::BlockCoverageBuilder::AllocateNaryBlockCoverageSlot(), v8::internal::SourceRangeAstVisitor::MaybeRemoveContinuationRange(), v8::internal::SourceRangeAstVisitor::VisitBlock(), and v8::internal::SourceRangeAstVisitor::VisitNode().
Member Data Documentation
map_
ZoneMap<ZoneObject*, AstNodeSourceRanges*> v8::internal::SourceRangeMap::map_ [private]
Definition at line 443 of file ast-source-ranges.h.
Referenced by Find().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h