v8::BigIntObject Class Reference
A BigInt object (https://tc39.github.io/proposal-bigint)
#include <v8-primitive-object.h>
Public Member Functions
Local< BigInt > ValueOf () const
Static Public Member Functions
static Local< Value > New (Isolate *isolate, int64_t value)
static BigIntObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A BigInt object (https://tc39.github.io/proposal-bigint)
Definition at line 39 of file v8-primitive-object.h.
Member Function Documentation
Cast()
static BigIntObject* v8::BigIntObject::Cast (Value * value) [inline], [static]
Definition at line 45 of file v8-primitive-object.h.
                                                    {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<BigIntObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::BigIntObject::CheckCast (v8::Value * that) [static], [private]
Definition at line 4153 of file api.cc.
                                            {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsBigIntWrapper(obj), "v8::BigIntObject::Cast()",
                  "Value is not a BigIntObject");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
Local< v8::Value > v8::BigIntObject::New (Isolate * isolate, int64_t value) [static]
Definition at line 7866 of file api.cc.
                                                                     {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_BigIntObject_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Object> bigint = i::BigInt::FromInt64(i_isolate, value);
  i::DirectHandle<i::Object> obj =
      i::Object::ToObject(i_isolate, bigint).ToHandleChecked();
  return Utils::ToLocal(obj);
}
References v8::internal::BigInt::FromInt64(), v8::anonymous_namespace{api.cc}::ToObject(), and v8::internal::value.
ValueOf()
Local< v8::BigInt > v8::BigIntObject::ValueOf () const
Definition at line 7876 of file api.cc.
                                              {
  auto obj = Utils::OpenDirectHandle(this);
  auto js_primitive_wrapper = i::Cast<i::JSPrimitiveWrapper>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_BigIntObject_BigIntValue);
  return Utils::ToLocal(i::direct_handle(
      i::Cast<i::BigInt>(js_primitive_wrapper->value()), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive-object.h
/mnt/V8SourceCode/src/api/api.cc