v8::internal::compiler::turboshaft::AccessBuilderTS Class Reference
#include <access-builder.h>
Public Types
using HeapNumberOrOddballOrHole = Union< HeapNumber, Oddball, Hole >
Public Member Functions
TF_FIELD_ACCESS (HeapNumberOrOddballOrHole, Float64, ForHeapNumberOrOddballOrHoleValue) static FieldAccessTS< Object
Map ForMap (WriteBarrierKind write_barrier=kMapWriteBarrier)
Static Public Member Functions
static FieldAccessTS< FeedbackVector, Word32 > ForFeedbackVectorLength ()
template<IsTagged T>
static ElementAccessTS< FixedArray, T > ForFixedArrayElement ()
Static Public Attributes
template<typename Class >
static constexpr bool is_array_buffer_v = std::is_same_v<Class, ArrayBuffer>
Detailed Description
Definition at line 48 of file access-builder.h.
Member Typedef Documentation
HeapNumberOrOddballOrHole
using v8::internal::compiler::turboshaft::AccessBuilderTS::HeapNumberOrOddballOrHole = Union<HeapNumber, Oddball, Hole>
Definition at line 60 of file access-builder.h.
Member Function Documentation
ForFeedbackVectorLength()
static FieldAccessTS<FeedbackVector, Word32> v8::internal::compiler::turboshaft::AccessBuilderTS::ForFeedbackVectorLength () [inline], [static]
Definition at line 69 of file access-builder.h.
                                                                         {
    return FieldAccessTS<FeedbackVector, Word32>(compiler::FieldAccess{
        BaseTaggedness::kTaggedBase, FeedbackVector::kLengthOffset,
        Handle<Name>(), OptionalMapRef(), TypeCache::Get()->kInt32,
        MachineType::Int32(), WriteBarrierKind::kNoWriteBarrier});
  }
References v8::internal::compiler::TypeCache::Get(), v8::internal::MachineType::Int32(), v8::internal::compiler::TypeCache::kInt32, v8::internal::compiler::kNoWriteBarrier, and v8::internal::compiler::kTaggedBase.
Referenced by v8::internal::FeedbackCollectorReducer< Next >::LoadFeedbackVectorLength().
ForFixedArrayElement()
template<IsTagged T>
static ElementAccessTS<FixedArray, T> v8::internal::compiler::turboshaft::AccessBuilderTS::ForFixedArrayElement () [inline], [static]
Definition at line 86 of file access-builder.h.
                                                               {
    static_assert(!is_array_buffer_v<FixedArray>);
    return ElementAccessTS<FixedArray, T>{
        compiler::AccessBuilder::ForFixedArrayElement(), false};
  }
References v8::internal::compiler::AccessBuilder::ForFixedArrayElement().
ForMap()
Map v8::internal::compiler::turboshaft::AccessBuilderTS::ForMap (WriteBarrierKind write_barrier = kMapWriteBarrier) [inline]
Definition at line 64 of file access-builder.h.
                                                         {
    return FieldAccessTS<Object, Map>(
        compiler::AccessBuilder::ForMap(write_barrier));
  }
References v8::internal::compiler::AccessBuilder::ForMap().
Referenced by v8::internal::StringBuiltinsReducer< Next >::AllocateSeqOneByteString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateSeqTwoByteString(), and v8::internal::StringBuiltinsReducer< Next >::AllocateSeqTwoByteString().
TF_FIELD_ACCESS()
v8::internal::compiler::turboshaft::AccessBuilderTS::TF_FIELD_ACCESS (HeapNumberOrOddballOrHole , Float64 , ForHeapNumberOrOddballOrHoleValue)
Member Data Documentation
is_array_buffer_v
template<typename Class >
constexpr bool v8::internal::compiler::turboshaft::AccessBuilderTS::is_array_buffer_v = std::is_same_v<Class, ArrayBuffer> [static], [constexpr]
Definition at line 51 of file access-builder.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/access-builder.h