v8::internal::compiler::PackNode Class Reference
#include <revectorizer.h>
Public Member Functions
PackNode (Zone *zone, const ZoneVector< Node * > &node_group)
const ZoneVector< Node * > & Nodes () const
bool IsSame (const ZoneVector< Node * > &node_group) const
Node * RevectorizedNode () const
void SetRevectorizedNode (Node *node)
PackNode * GetOperand (size_t index)
ZoneVector< PackNode * >::size_type GetOperandsSize () const
void SetOperand (size_t index, PackNode *pnode)
void Print () const
Private Attributes
ZoneVector< Node * > nodes_
ZoneVector< PackNode * > operands_
Node * revectorized_node_
Detailed Description
Definition at line 43 of file revectorizer.h.
Constructor & Destructor Documentation
PackNode()
v8::internal::compiler::PackNode::PackNode (Zone * zone, const ZoneVector< Node * > & node_group) [inline], [explicit]
Definition at line 45 of file revectorizer.h.
      : nodes_(node_group.cbegin(), node_group.cend(), zone),
        operands_(zone),
        revectorized_node_(nullptr) {}
Member Function Documentation
GetOperand()
PackNode* v8::internal::compiler::PackNode::GetOperand (size_t index) [inline]
Definition at line 56 of file revectorizer.h.
                                     {
    DCHECK_LT(index, operands_.size());
    return operands_[index];
  }
References DCHECK_LT, v8::internal::index, and operands_.
Referenced by v8::internal::compiler::Revectorizer::VectorizeTree().
GetOperandsSize()
ZoneVector<PackNode*>::size_type v8::internal::compiler::PackNode::GetOperandsSize () const [inline]
Definition at line 61 of file revectorizer.h.
                                                         {
    return operands_.size();
  }
References operands_.
IsSame()
bool v8::internal::compiler::PackNode::IsSame (const ZoneVector< Node * > & node_group) const [inline]
Definition at line 50 of file revectorizer.h.
                                                         {
    return nodes_ == node_group;
  }
References nodes_.
Nodes()
const ZoneVector<Node*>& v8::internal::compiler::PackNode::Nodes () const [inline]
Definition at line 49 of file revectorizer.h.
{ return nodes_; }
References nodes_.
Referenced by v8::internal::compiler::Revectorizer::DecideVectorize(), v8::internal::compiler::Revectorizer::SetEffectInput(), v8::internal::compiler::Revectorizer::SetMemoryOpInputs(), and v8::internal::compiler::Revectorizer::VectorizeTree().
Print()
void v8::internal::compiler::PackNode::Print () const
Definition at line 390 of file revectorizer.cc.
                           {
  if (revectorized_node_ != nullptr) {
    TRACE("0x%p #%d:%s(%d %d, %s)\n", this, revectorized_node_->id(),
          revectorized_node_->op()->mnemonic(), nodes_[0]->id(),
          nodes_[1]->id(), nodes_[0]->op()->mnemonic());
  } else {
    TRACE("0x%p null(%d %d, %s)\n", this, nodes_[0]->id(), nodes_[1]->id(),
          nodes_[0]->op()->mnemonic());
  }
}
References v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), nodes_, v8::internal::compiler::Node::op(), revectorized_node_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::SLPTree::Print().
RevectorizedNode()
Node* v8::internal::compiler::PackNode::RevectorizedNode () const [inline]
Definition at line 53 of file revectorizer.h.
{ return revectorized_node_; }
References revectorized_node_.
Referenced by v8::internal::compiler::Revectorizer::ReduceStoreChain(), and v8::internal::compiler::Revectorizer::VectorizeTree().
SetOperand()
void v8::internal::compiler::PackNode::SetOperand (size_t index, PackNode * pnode) [inline]
Definition at line 65 of file revectorizer.h.
                                                 {
    if (operands_.size() < index + 1) operands_.resize(index + 1);
    operands_[index] = pnode;
  }
References v8::internal::index, and operands_.
Referenced by v8::internal::compiler::SLPTree::NewPackNodeAndRecurs(), and v8::internal::compiler::Revectorizer::SetEffectInput().
SetRevectorizedNode()
void v8::internal::compiler::PackNode::SetRevectorizedNode (Node * node) [inline]
Definition at line 54 of file revectorizer.h.
{ revectorized_node_ = node; }
References revectorized_node_.
Referenced by v8::internal::compiler::Revectorizer::VectorizeTree().
Member Data Documentation
nodes_
ZoneVector<Node*> v8::internal::compiler::PackNode::nodes_ [private]
Definition at line 73 of file revectorizer.h.
Referenced by IsSame(), Nodes(), and Print().
operands_
ZoneVector<PackNode*> v8::internal::compiler::PackNode::operands_ [private]
Definition at line 74 of file revectorizer.h.
Referenced by GetOperand(), GetOperandsSize(), and SetOperand().
revectorized_node_
Node* v8::internal::compiler::PackNode::revectorized_node_ [private]
Definition at line 75 of file revectorizer.h.
Referenced by Print(), RevectorizedNode(), and SetRevectorizedNode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/revectorizer.h
/mnt/V8SourceCode/src/compiler/revectorizer.cc