v8::internal::wasm::WasmValue Class Reference
#include <wasm-value.h>
Public Member Functions
WasmValue ()
WasmValue (const uint8_t *raw_bytes, CanonicalValueType type)
WasmValue (DirectHandle< Object > ref, CanonicalValueType type)
DirectHandle< Object > to_ref () const
CanonicalValueType type () const
const WasmModule * module () const
bool operator== (const WasmValue &other) const
void CopyTo (uint8_t *to) const
WasmValue Packed (ValueType packed_type) const
template<typename T >
T to () const
template<typename T >
T to_unchecked () const
std::string to_string () const
bool zero_byte_representation ()
Static Public Member Functions
static WasmValue ForUintPtr (uintptr_t value)
Private Attributes
CanonicalValueType type_
uint8_t bit_pattern_ [16]
const WasmModule * module_ = nullptr
Detailed Description
Definition at line 47 of file wasm-value.h.
Constructor & Destructor Documentation
WasmValue() [1/3]
v8::internal::wasm::WasmValue::WasmValue () [inline]
Definition at line 49 of file wasm-value.h.
: type_(kWasmVoid), bit_pattern_{} {}
Referenced by Packed().
WasmValue() [2/3]
v8::internal::wasm::WasmValue::WasmValue (const uint8_t * raw_bytes, CanonicalValueType type) [inline]
Definition at line 70 of file wasm-value.h.
      : type_(type), bit_pattern_{} {
    DCHECK(type_.is_numeric());
    memcpy(bit_pattern_, raw_bytes, type.value_kind_size());
  }
References bit_pattern_, v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::is_numeric(), type(), type_, and v8::internal::wasm::ValueTypeBase::value_kind_size().
WasmValue() [3/3]
v8::internal::wasm::WasmValue::WasmValue (DirectHandle< Object > ref, CanonicalValueType type) [inline]
Definition at line 76 of file wasm-value.h.
      : type_(type), bit_pattern_{} {
    static_assert(sizeof(DirectHandle<Object>) <= sizeof(bit_pattern_),
                  "bit_pattern_ must be large enough to fit a Handle");
    DCHECK(type.is_reference());
    base::WriteUnalignedValue<DirectHandle<Object>>(
        reinterpret_cast<Address>(bit_pattern_), ref);
  }
References bit_pattern_, v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::is_reference(), and type().
Member Function Documentation
CopyTo()
void v8::internal::wasm::WasmValue::CopyTo (uint8_t * to) const [inline]
Definition at line 103 of file wasm-value.h.
                                 {
    static_assert(sizeof(float) == sizeof(Float32));
    static_assert(sizeof(double) == sizeof(Float64));
    DCHECK(type_.is_numeric());
    memcpy(to, bit_pattern_, type_.value_kind_size());
  }
References bit_pattern_, v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::is_numeric(), to(), type_, and v8::internal::wasm::ValueTypeBase::value_kind_size().
Referenced by v8::internal::wasm::InstanceBuilder::InitGlobals().
ForUintPtr()
static WasmValue v8::internal::wasm::WasmValue::ForUintPtr (uintptr_t value) [inline], [static]
Definition at line 130 of file wasm-value.h.
                                               {
    using type =
        std::conditional_t<kSystemPointerSize == 8, uint64_t, uint32_t>;
    return WasmValue{type{value}};
  }
References type(), and v8::internal::value.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BoundsCheckMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckMaxSteps(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckNan(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CheckS128Nan(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateOutOfLineCode(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Throw().
module()
const WasmModule* v8::internal::wasm::WasmValue::module () const [inline]
Definition at line 93 of file wasm-value.h.
{ return module_; }
References module_.
operator==()
bool v8::internal::wasm::WasmValue::operator== (const WasmValue & other) const [inline]
Definition at line 96 of file wasm-value.h.
                                                {
    return type_ == other.type_ &&
           !memcmp(bit_pattern_, other.bit_pattern_,
                   type_.is_reference() ? sizeof(DirectHandle<Object>)
                                        : type_.value_kind_size());
  }
References bit_pattern_, v8::internal::wasm::ValueTypeBase::is_reference(), type_, and v8::internal::wasm::ValueTypeBase::value_kind_size().
Packed()
WasmValue v8::internal::wasm::WasmValue::Packed (ValueType packed_type) const [inline]
Definition at line 112 of file wasm-value.h.
                                                {
    if (packed_type == kWasmI8) {
      DCHECK_EQ(type_, kWasmI32);
      return WasmValue(static_cast<int8_t>(to_i32()));
    }
    if (packed_type == kWasmI16) {
      DCHECK_EQ(type_, kWasmI32);
      return WasmValue(static_cast<int16_t>(to_i32()));
    }
    return *this;
  }
References DCHECK_EQ, v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI32, v8::internal::wasm::kWasmI8, type_, and WasmValue().
to()
template<typename T >
T v8::internal::wasm::WasmValue::to () const [inline]
Referenced by CopyTo().
to_ref()
DirectHandle<Object> v8::internal::wasm::WasmValue::to_ref () const [inline]
Definition at line 85 of file wasm-value.h.
                                      {
    DCHECK(type_.is_reference());
    return base::ReadUnalignedValue<DirectHandle<Object>>(
        reinterpret_cast<Address>(bit_pattern_));
  }
References bit_pattern_, v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::is_reference(), and type_.
Referenced by v8::internal::wasm::ConstantExpressionInterface::GetRtt(), v8::internal::wasm::InstanceBuilder::InitGlobals(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), and to_string().
to_string()
std::string v8::internal::wasm::WasmValue::to_string () const [inline]
Definition at line 136 of file wasm-value.h.
                                     {
    switch (type_.kind()) {
      case kI8:
        return std::to_string(to_i8());
      case kI16:
        return std::to_string(to_i16());
      case kI32:
        return std::to_string(to_i32());
      case kI64:
        return std::to_string(to_i64());
      case kF16:
        return std::to_string(fp16_ieee_to_fp32_value(to_f16()));
      case kF32:
        return std::to_string(to_f32());
      case kF64:
        return std::to_string(to_f64());
      case kS128: {
        std::stringstream stream;
        stream << "0x" << std::hex;
        for (int8_t uint8_t : bit_pattern_) {
          if (!(uint8_t & 0xf0)) stream << '0';
          stream << uint8_t;
        }
        return stream.str();
      }
      case kRefNull:
      case kRef:
        return "DirectHandle [" + std::to_string(to_ref().address()) + "]";
      case kVoid:
      case kTop:
      case kBottom:
        UNREACHABLE();
    }
  }
References bit_pattern_, v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, to_ref(), type_, and v8::internal::UNREACHABLE().
to_unchecked()
template<typename T >
T v8::internal::wasm::WasmValue::to_unchecked () const [inline]
type()
CanonicalValueType v8::internal::wasm::WasmValue::type () const [inline]
Definition at line 91 of file wasm-value.h.
{ return type_; }
References type_.
Referenced by ForUintPtr(), v8::internal::wasm::ConstantExpressionInterface::GetRtt(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmValue(), v8::internal::wasm::InstanceBuilder::LoadTableSegments(), WasmValue(), and zero_byte_representation().
zero_byte_representation()
bool v8::internal::wasm::WasmValue::zero_byte_representation () [inline]
Definition at line 171 of file wasm-value.h.
                                  {
    DCHECK(type().is_numeric());
    uint32_t byte_count = type().value_kind_size();
    return static_cast<uint32_t>(std::count(
               bit_pattern_, bit_pattern_ + byte_count, 0)) == byte_count;
  }
References bit_pattern_, v8::internal::DCHECK(), type(), and v8::internal::wasm::ValueTypeBase::value_kind_size().
Member Data Documentation
bit_pattern_
uint8_t v8::internal::wasm::WasmValue::bit_pattern_[16] [private]
Definition at line 180 of file wasm-value.h.
Referenced by CopyTo(), operator==(), to_ref(), to_string(), WasmValue(), and zero_byte_representation().
module_
const WasmModule* v8::internal::wasm::WasmValue::module_ = nullptr [private]
Definition at line 181 of file wasm-value.h.
Referenced by module().
type_
CanonicalValueType v8::internal::wasm::WasmValue::type_ [private]
Definition at line 179 of file wasm-value.h.
Referenced by CopyTo(), operator==(), Packed(), to_ref(), to_string(), type(), and WasmValue().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-value.h