v8::internal::SafepointEntryBase Class Reference
#include <safepoint-table-base.h>
Public Member Functions
SafepointEntryBase ()=default
SafepointEntryBase (int pc, int deopt_index, int trampoline_pc)
bool is_initialized () const
int pc () const
int trampoline_pc () const
bool has_deoptimization_index () const
int deoptimization_index () const
void Reset ()
Static Public Attributes
static constexpr int kNoDeoptIndex = -1
static constexpr int kNoTrampolinePC = -1
Protected Member Functions
bool operator== (const SafepointEntryBase &other) const
Private Attributes
int pc_ = 0
int deopt_index_ = kNoDeoptIndex
int trampoline_pc_ = kNoTrampolinePC
Detailed Description
Definition at line 20 of file safepoint-table-base.h.
Constructor & Destructor Documentation
SafepointEntryBase() [1/2]
v8::internal::SafepointEntryBase::SafepointEntryBase () [default]
SafepointEntryBase() [2/2]
v8::internal::SafepointEntryBase::SafepointEntryBase (int pc, int deopt_index, int trampoline_pc) [inline]
Definition at line 27 of file safepoint-table-base.h.
      : pc_(pc), deopt_index_(deopt_index), trampoline_pc_(trampoline_pc) {
    DCHECK(is_initialized());
  }
References v8::internal::DCHECK(), and is_initialized().
Member Function Documentation
deoptimization_index()
int v8::internal::SafepointEntryBase::deoptimization_index () const [inline]
Definition at line 45 of file safepoint-table-base.h.
                                   {
    DCHECK(has_deoptimization_index());
    return deopt_index_;
  }
References v8::internal::DCHECK(), deopt_index_, and has_deoptimization_index().
Referenced by v8::internal::OptimizedJSFrame::GetDeoptimizationData(), v8::internal::MaglevSafepointTable::Print(), and v8::internal::SafepointTable::Print().
has_deoptimization_index()
bool v8::internal::SafepointEntryBase::has_deoptimization_index () const [inline]
Definition at line 41 of file safepoint-table-base.h.
                                        {
    return deopt_index_ != kNoDeoptIndex;
  }
References deopt_index_, and kNoDeoptIndex.
Referenced by deoptimization_index(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::OptimizedJSFrame::GetDeoptimizationData(), v8::internal::MaglevSafepointTable::Print(), and v8::internal::SafepointTable::Print().
is_initialized()
bool v8::internal::SafepointEntryBase::is_initialized () const [inline]
Definition at line 32 of file safepoint-table-base.h.
{ return pc_ != 0; }
References pc_.
Referenced by v8::internal::anonymous_namespace{frames.cc}::GetMaglevSafepointEntryFromCodeCache(), v8::internal::anonymous_namespace{frames.cc}::GetSafepointEntryFromCodeCache(), v8::internal::MaglevSafepointEntry::MaglevSafepointEntry(), pc(), v8::internal::SafepointEntry::SafepointEntry(), SafepointEntryBase(), v8::internal::SafepointEntry::tagged_register_indexes(), and v8::internal::SafepointEntry::tagged_slots().
operator==()
bool v8::internal::SafepointEntryBase::operator== (const SafepointEntryBase & other) const [inline], [protected]
Definition at line 53 of file safepoint-table-base.h.
                                                         {
    return pc_ == other.pc_ && deopt_index_ == other.deopt_index_ &&
           trampoline_pc_ == other.trampoline_pc_;
  }
References deopt_index_, pc_, and trampoline_pc_.
Referenced by v8::internal::MaglevSafepointEntry::operator==(), and v8::internal::SafepointEntry::operator==().
pc()
int v8::internal::SafepointEntryBase::pc () const [inline]
Definition at line 34 of file safepoint-table-base.h.
                 {
    DCHECK(is_initialized());
    return pc_;
  }
References v8::internal::DCHECK(), is_initialized(), and pc_.
Referenced by v8::internal::MaglevSafepointTable::find_return_pc(), v8::internal::SafepointTable::find_return_pc(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::MaglevSafepointTable::Print(), v8::internal::SafepointTable::Print(), and v8::internal::SafepointTable::TryFindEntry().
Reset()
void v8::internal::SafepointEntryBase::Reset () [inline]
Definition at line 50 of file safepoint-table-base.h.
{ pc_ = 0; }
References pc_.
trampoline_pc()
int v8::internal::SafepointEntryBase::trampoline_pc () const [inline]
Definition at line 39 of file safepoint-table-base.h.
{ return trampoline_pc_; }
References trampoline_pc_.
Referenced by v8::internal::MaglevSafepointTable::find_return_pc(), v8::internal::SafepointTable::find_return_pc(), v8::internal::MaglevSafepointTable::FindEntry(), v8::internal::MaglevSafepointTable::Print(), v8::internal::SafepointTable::Print(), v8::internal::SafepointTable::TryFindEntry(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
Member Data Documentation
deopt_index_
int v8::internal::SafepointEntryBase::deopt_index_ = kNoDeoptIndex [private]
Definition at line 60 of file safepoint-table-base.h.
Referenced by deoptimization_index(), has_deoptimization_index(), and operator==().
kNoDeoptIndex
constexpr int v8::internal::SafepointEntryBase::kNoDeoptIndex = -1 [static], [constexpr]
Definition at line 22 of file safepoint-table-base.h.
Referenced by v8::internal::SafepointTableBuilder::Emit(), v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), v8::internal::OptimizedJSFrame::GetDeoptimizationData(), v8::internal::SafepointTable::GetEntry(), v8::internal::OptimizedJSFrame::GetFunctions(), has_deoptimization_index(), v8::internal::OptimizedJSFrame::Summarize(), v8::internal::TranslatedState::TranslatedState(), and v8::internal::SafepointTableBuilder::UpdateDeoptimizationInfo().
kNoTrampolinePC
constexpr int v8::internal::SafepointEntryBase::kNoTrampolinePC = -1 [static], [constexpr]
Definition at line 23 of file safepoint-table-base.h.
Referenced by v8::internal::SafepointTableBuilder::Emit(), v8::internal::SafepointTable::GetEntry(), v8::internal::SafepointTableBuilder::UpdateDeoptimizationInfo(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
pc_
int v8::internal::SafepointEntryBase::pc_ = 0 [private]
Definition at line 59 of file safepoint-table-base.h.
Referenced by is_initialized(), operator==(), pc(), and Reset().
trampoline_pc_
int v8::internal::SafepointEntryBase::trampoline_pc_ = kNoTrampolinePC [private]
Definition at line 61 of file safepoint-table-base.h.
Referenced by operator==(), and trampoline_pc().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/safepoint-table-base.h