v8::internal::StringsStorage Class Reference
#include <strings-storage.h>
Public Member Functions
StringsStorage ()
~StringsStorage ()
StringsStorage (const StringsStorage &)=delete
StringsStorage & operator= (const StringsStorage &)=delete
const char * GetCopy (const char *src)
PRINTF_FORMAT (2, 3) const char *GetFormatted(const char *format
const char * GetName (Tagged< Name > name)
const char * GetName (int index)
const char * GetConsName (const char *prefix, Tagged< Name > name)
bool Release (const char *str)
size_t GetStringCountForTesting () const
size_t GetStringSize ()
bool empty () const
Private Member Functions
const char * AddOrDisposeString (char *str, size_t len)
base::CustomMatcherHashMap::Entry * GetEntry (const char *str, size_t len)
const char * GetVFormatted (const char *format, va_list args)
const char * GetSymbol (Tagged< Symbol > sym)
Static Private Member Functions
static bool StringsMatch (void *key1, void *key2)
Private Attributes
base::CustomMatcherHashMap names_
base::Mutex mutex_
size_t string_size_ = 0
Detailed Description
Definition at line 23 of file strings-storage.h.
Constructor & Destructor Documentation
StringsStorage() [1/2]
v8::internal::StringsStorage::StringsStorage ()
Definition at line 22 of file strings-storage.cc.
: names_(StringsMatch) {}
 StringsStorage()
v8::internal::StringsStorage::~StringsStorage ()
Definition at line 24 of file strings-storage.cc.
                                {
  for (base::HashMap::Entry* p = names_.Start(); p != nullptr;
       p = names_.Next(p)) {
    DeleteArray(reinterpret_cast<const char*>(p->key));
  }
}
References names_.
StringsStorage() [2/2]
v8::internal::StringsStorage::StringsStorage (const StringsStorage &) [delete]
Member Function Documentation
AddOrDisposeString()
const char * v8::internal::StringsStorage::AddOrDisposeString (char * str, size_t len) [private]
Definition at line 55 of file strings-storage.cc.
                                                                    {
  base::MutexGuard guard(&mutex_);
  base::HashMap::Entry* entry = GetEntry(str, len);
  if (entry->value == nullptr) {
    // New entry added.
    entry->key = str;
    string_size_ += len;
  } else {
    DeleteArray(str);
  }
  entry->value =
      reinterpret_cast<void*>(reinterpret_cast<size_t>(entry->value) + 1);
  return reinterpret_cast<const char*>(entry->key);
}
References GetEntry(), mutex_, and string_size_.
Referenced by GetConsName(), GetName(), GetSymbol(), and GetVFormatted().
empty()
bool v8::internal::StringsStorage::empty () const [inline]
Definition at line 54 of file strings-storage.h.
{ return names_.occupancy() == 0; }
Referenced by v8::internal::CpuProfiler::~CpuProfiler().
GetConsName()
const char * v8::internal::StringsStorage::GetConsName (const char * prefix, Tagged< Name > name)
Definition at line 116 of file strings-storage.cc.
                                                                             {
  if (IsString(name)) {
    Tagged<String> str = Cast<String>(name);
    uint32_t length =
        std::min(v8_flags.heap_snapshot_string_limit.value(), str->length());
    size_t data_length = 0;
    std::unique_ptr<char[]> data = str->ToCString(0, length, &data_length);
    size_t cons_length = data_length + strlen(prefix) + 1;
    char* cons_result = NewArray<char>(cons_length);
    snprintf(cons_result, cons_length, "%s%s", prefix, data.get());
    return AddOrDisposeString(cons_result, cons_length - 1);
  } else if (IsSymbol(name)) {
    return GetSymbol(Cast<Symbol>(name));
  }
  return "";
}
References AddOrDisposeString(), GetSymbol(), v8::internal::length, v8::internal::name, and v8::internal::v8_flags.
GetCopy()
const char * v8::internal::StringsStorage::GetCopy (const char * src)
Definition at line 31 of file strings-storage.cc.
                                                   {
  base::MutexGuard guard(&mutex_);
  int len = static_cast<int>(strlen(src));
  base::HashMap::Entry* entry = GetEntry(src, len);
  if (entry->value == nullptr) {
    base::Vector<char> dst = base::Vector<char>::New(len + 1);
    base::StrNCpy(dst, src, len);
    dst[len] = '\0';
    entry->key = dst.begin();
    string_size_ += len;
  }
  entry->value =
      reinterpret_cast<void*>(reinterpret_cast<size_t>(entry->value) + 1);
  return reinterpret_cast<const char*>(entry->key);
}
References v8::base::Vector< T >::begin(), GetEntry(), mutex_, v8::base::Vector< T >::New(), string_size_, and v8::base::StrNCpy().
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::AllocationTracker::AddFunctionInfo(), v8::internal::SamplingHeapProfiler::AddStack(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeName(), v8::internal::V8HeapExplorer::ExtractNumberReference(), GetVFormatted(), and v8::internal::NativeObjectsExplorer::IterateAndExtractReferences().
GetEntry()
base::HashMap::Entry * v8::internal::StringsStorage::GetEntry (const char * str, size_t len) [private]
Definition at line 181 of file strings-storage.cc.
                                                                      {
  uint32_t hash = ComputeStringHash(str, len);
  return names_.LookupOrInsert(const_cast<char*>(str), hash);
}
References v8::internal::anonymous_namespace{strings-storage.cc}::ComputeStringHash(), and names_.
Referenced by AddOrDisposeString(), and GetCopy().
GetName() [1/2]
const char * v8::internal::StringsStorage::GetName (int index)
Definition at line 112 of file strings-storage.cc.
                                             {
  return GetFormatted("%d", index);
}
References v8::internal::index.
GetName() [2/2]
const char * v8::internal::StringsStorage::GetName (Tagged< Name > name)
Definition at line 98 of file strings-storage.cc.
                                                     {
  if (IsString(name)) {
    Tagged<String> str = Cast<String>(name);
    uint32_t length =
        std::min(v8_flags.heap_snapshot_string_limit.value(), str->length());
    size_t data_length = 0;
    std::unique_ptr<char[]> data = str->ToCString(0, length, &data_length);
    return AddOrDisposeString(data.release(), data_length);
  } else if (IsSymbol(name)) {
    return GetSymbol(Cast<Symbol>(name));
  }
  return "";
}
References AddOrDisposeString(), GetSymbol(), v8::internal::length, v8::internal::name, and v8::internal::v8_flags.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::AllocationTracker::AddFunctionInfo(), v8::internal::V8HeapExplorer::SetContextReference(), v8::internal::V8HeapExplorer::SetInternalReference(), v8::internal::HeapEntry::SetNamedAutoIndexReference(), v8::internal::V8HeapExplorer::SetPropertyReference(), and v8::internal::SamplingHeapProfiler::TranslateAllocationNode().
GetStringCountForTesting()
size_t v8::internal::StringsStorage::GetStringCountForTesting () const
Definition at line 172 of file strings-storage.cc.
                                                      {
  return names_.occupancy();
}
References names_.
GetStringSize()
size_t v8::internal::StringsStorage::GetStringSize ()
Definition at line 176 of file strings-storage.cc.
                                     {
  base::MutexGuard guard(&mutex_);
  return string_size_;
}
References mutex_, and string_size_.
Referenced by v8::internal::ProfilerCodeObserver::GetEstimatedMemoryUsage().
GetSymbol()
const char * v8::internal::StringsStorage::GetSymbol (Tagged< Symbol > sym) [private]
Definition at line 80 of file strings-storage.cc.
                                                        {
  if (!IsString(sym->description())) {
    return "<symbol>";
  }
  Tagged<String> description = Cast<String>(sym->description());
  uint32_t length = std::min(v8_flags.heap_snapshot_string_limit.value(),
                             description->length());
  size_t data_length = 0;
  auto data = description->ToCString(0, length, &data_length);
  if (sym->is_private_name()) {
    return AddOrDisposeString(data.release(), data_length);
  }
  auto str_length = 8 + data_length + 1 + 1;
  auto str_result = NewArray<char>(str_length);
  snprintf(str_result, str_length, "<symbol %s>", data.get());
  return AddOrDisposeString(str_result, str_length - 1);
}
References AddOrDisposeString(), v8::internal::length, and v8::internal::v8_flags.
Referenced by GetConsName(), and GetName().
GetVFormatted()
const char * v8::internal::StringsStorage::GetVFormatted (const char * format, va_list args) [private]
Definition at line 70 of file strings-storage.cc.
                                                                          {
  base::Vector<char> str = base::Vector<char>::New(1024);
  int len = base::VSNPrintF(str, format, args);
  if (len == -1) {
    DeleteArray(str.begin());
    return GetCopy(format);
  }
  return AddOrDisposeString(str.begin(), len);
}
References AddOrDisposeString(), v8::base::args, v8::base::Vector< T >::begin(), v8::internal::format, GetCopy(), v8::base::Vector< T >::New(), and v8::base::VSNPrintF().
operator=()
StringsStorage& v8::internal::StringsStorage::operator= (const StringsStorage &) [delete]
PRINTF_FORMAT()
v8::internal::StringsStorage::PRINTF_FORMAT (2 , 3) const
Release()
bool v8::internal::StringsStorage::Release (const char * str)
Definition at line 147 of file strings-storage.cc.
                                            {
  base::MutexGuard guard(&mutex_);
  size_t len = strlen(str);
  uint32_t hash = ComputeStringHash(str, len);
  base::HashMap::Entry* entry = names_.Lookup(const_cast<char*>(str), hash);
  // If an entry wasn't found or the address of the found entry doesn't match
  // the one passed in, this string wasn't managed by this StringsStorage
  // instance (i.e. a constant). Ignore this.
  if (!entry || entry->key != str) {
    return false;
  }
  DCHECK(entry->value);
  entry->value =
      reinterpret_cast<void*>(reinterpret_cast<size_t>(entry->value) - 1);
  if (entry->value == 0) {
    string_size_ -= len;
    names_.Remove(const_cast<char*>(str), hash);
    DeleteArray(str);
  }
  return true;
}
References v8::internal::anonymous_namespace{strings-storage.cc}::ComputeStringHash(), v8::internal::DCHECK(), mutex_, names_, and string_size_.
Referenced by v8::internal::CodeEntry::ReleaseStrings().
StringsMatch()
bool v8::internal::StringsStorage::StringsMatch (void * key1, void * key2) [static], [private]
Definition at line 17 of file strings-storage.cc.
                                                        {
  return strcmp(reinterpret_cast<char*>(key1), reinterpret_cast<char*>(key2)) ==
         0;
}
Member Data Documentation
mutex_
base::Mutex v8::internal::StringsStorage::mutex_ [private]
Definition at line 67 of file strings-storage.h.
Referenced by AddOrDisposeString(), GetCopy(), GetStringSize(), and Release().
names_
base::CustomMatcherHashMap v8::internal::StringsStorage::names_ [private]
Definition at line 66 of file strings-storage.h.
Referenced by GetEntry(), GetStringCountForTesting(), Release(), and ~StringsStorage().
string_size_
size_t v8::internal::StringsStorage::string_size_ = 0 [private]
Definition at line 68 of file strings-storage.h.
Referenced by AddOrDisposeString(), GetCopy(), GetStringSize(), and Release().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/strings-storage.h
/mnt/V8SourceCode/src/profiler/strings-storage.cc