v8::internal::compiler::SwitchInfo Class Reference
#include <instruction-selector-impl.h>
Public Member Functions
SwitchInfo (ZoneVector< CaseInfo > const &cases, int32_t min_value, int32_t max_value, turboshaft::Block *default_branch)
std::vector< CaseInfo > CasesSortedByValue () const
const ZoneVector< CaseInfo > & CasesUnsorted () const
int32_t min_value () const
int32_t max_value () const
size_t value_range () const
size_t case_count () const
turboshaft::Block * default_branch () const
Private Attributes
const ZoneVector< CaseInfo > & cases_
int32_t min_value_
int32_t max_value_
size_t value_range_
turboshaft::Block * default_branch_
Detailed Description
Definition at line 30 of file instruction-selector-impl.h.
Constructor & Destructor Documentation
SwitchInfo()
v8::internal::compiler::SwitchInfo::SwitchInfo (ZoneVector< CaseInfo > const & cases, int32_t min_value, int32_t max_value, turboshaft::Block * default_branch) [inline]
Definition at line 32 of file instruction-selector-impl.h.
      : cases_(cases),
        min_value_(min_value),
        max_value_(max_value),
        default_branch_(default_branch) {
    if (cases.size() != 0) {
      DCHECK_LE(min_value, max_value);
      // Note that {value_range} can be 0 if {min_value} is -2^31 and
      // {max_value} is 2^31-1, so don't assume that it's non-zero below.
      value_range_ = 1u + base::bit_cast<uint32_t>(max_value) -
                     base::bit_cast<uint32_t>(min_value);
    } else {
      value_range_ = 0;
    }
  }
References DCHECK_LE, max_value(), min_value(), v8::internal::ZoneVector< T >::size(), and value_range_.
Member Function Documentation
case_count()
size_t v8::internal::compiler::SwitchInfo::case_count () const [inline]
Definition at line 59 of file instruction-selector-impl.h.
{ return cases_.size(); }
References cases_.
Referenced by v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch(), v8::internal::compiler::InstructionSelector::VisitSwitch(), and v8::internal::compiler::VisitWordCompare().
CasesSortedByValue()
std::vector<CaseInfo> v8::internal::compiler::SwitchInfo::CasesSortedByValue () const [inline]
Definition at line 49 of file instruction-selector-impl.h.
                                                 {
    std::vector<CaseInfo> result(cases_.begin(), cases_.end());
    std::stable_sort(result.begin(), result.end(),
                     [](CaseInfo a, CaseInfo b) { return a.value < b.value; });
    return result;
  }
References cases_, and v8::base::internal::result.
Referenced by v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch().
CasesUnsorted()
const ZoneVector<CaseInfo>& v8::internal::compiler::SwitchInfo::CasesUnsorted () const [inline]
Definition at line 55 of file instruction-selector-impl.h.
{ return cases_; }
References cases_.
Referenced by v8::internal::compiler::InstructionSelector::EmitTableSwitch().
default_branch()
turboshaft::Block* v8::internal::compiler::SwitchInfo::default_branch () const [inline]
Definition at line 60 of file instruction-selector-impl.h.
{ return default_branch_; }
References default_branch_.
Referenced by v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch(), and v8::internal::compiler::InstructionSelector::EmitTableSwitch().
max_value()
int32_t v8::internal::compiler::SwitchInfo::max_value () const [inline]
Definition at line 57 of file instruction-selector-impl.h.
{ return max_value_; }
References max_value_.
Referenced by SwitchInfo().
min_value()
int32_t v8::internal::compiler::SwitchInfo::min_value () const [inline]
Definition at line 56 of file instruction-selector-impl.h.
{ return min_value_; }
References min_value_.
Referenced by v8::internal::compiler::InstructionSelector::EmitTableSwitch(), SwitchInfo(), v8::internal::compiler::InstructionSelector::VisitSwitch(), and v8::internal::compiler::VisitWordCompare().
value_range()
size_t v8::internal::compiler::SwitchInfo::value_range () const [inline]
Definition at line 58 of file instruction-selector-impl.h.
{ return value_range_; }
References value_range_.
Referenced by v8::internal::compiler::InstructionSelector::EmitTableSwitch(), v8::internal::compiler::InstructionSelector::VisitSwitch(), and v8::internal::compiler::VisitWordCompare().
Member Data Documentation
cases_
const ZoneVector<CaseInfo>& v8::internal::compiler::SwitchInfo::cases_ [private]
Definition at line 63 of file instruction-selector-impl.h.
Referenced by case_count(), CasesSortedByValue(), and CasesUnsorted().
default_branch_
turboshaft::Block* v8::internal::compiler::SwitchInfo::default_branch_ [private]
Definition at line 67 of file instruction-selector-impl.h.
Referenced by default_branch().
max_value_
int32_t v8::internal::compiler::SwitchInfo::max_value_ [private]
Definition at line 65 of file instruction-selector-impl.h.
Referenced by max_value().
min_value_
int32_t v8::internal::compiler::SwitchInfo::min_value_ [private]
Definition at line 64 of file instruction-selector-impl.h.
Referenced by min_value().
value_range_
size_t v8::internal::compiler::SwitchInfo::value_range_ [private]
Definition at line 66 of file instruction-selector-impl.h.
Referenced by SwitchInfo(), and value_range().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector-impl.h