v8::internal::compiler::turboshaft::IterationCount Class Reference
#include <loop-unrolling-reducer.h>
Public Member Functions
IterationCount ()
IterationCount (Kind kind)
IterationCount (Kind kind, size_t count)
size_t exact_count () const
size_t approx_count () const
bool IsExact () const
bool IsApprox () const
bool IsUnknown () const
bool IsSmallerThan (size_t max)
Static Public Member Functions
static IterationCount Exact (size_t count)
static IterationCount Approx (size_t count)
static IterationCount Unknown ()
Private Types
enum class Kind { kExact
, kApprox
, kUnknown
 }
Private Attributes
Kind kind_
size_t count_
Detailed Description
Definition at line 39 of file loop-unrolling-reducer.h.
Member Enumeration Documentation
Kind
enum v8::internal::compiler::turboshaft::IterationCount::Kind [strong], [private]
Enumerator
kExact
kApprox
kUnknown
Definition at line 40 of file loop-unrolling-reducer.h.
{ kExact, kApprox, kUnknown };
Constructor & Destructor Documentation
IterationCount() [1/3]
v8::internal::compiler::turboshaft::IterationCount::IterationCount () [inline]
Definition at line 53 of file loop-unrolling-reducer.h.
: kind_(Kind::kUnknown) {}
References v8::internal::kUnknown.
Referenced by Approx(), Exact(), and Unknown().
IterationCount() [2/3]
v8::internal::compiler::turboshaft::IterationCount::IterationCount (Kind kind) [inline], [explicit]
Definition at line 54 of file loop-unrolling-reducer.h.
                                     : kind_(kind) {
    DCHECK_NE(kind, Kind::kExact);
  }
References DCHECK_NE, and kExact.
IterationCount() [3/3]
v8::internal::compiler::turboshaft::IterationCount::IterationCount (Kind kind, size_t count) [inline]
Definition at line 57 of file loop-unrolling-reducer.h.
                                          : kind_(kind), count_(count) {
    DCHECK_EQ(kind, any_of(Kind::kExact, Kind::kApprox));
  }
References v8::internal::compiler::turboshaft::any_of(), DCHECK_EQ, kApprox, and kExact.
Member Function Documentation
Approx()
static IterationCount v8::internal::compiler::turboshaft::IterationCount::Approx (size_t count) [inline], [static]
Definition at line 48 of file loop-unrolling-reducer.h.
                                             {
    return IterationCount(Kind::kApprox, count);
  }
References IterationCount(), and kApprox.
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl().
approx_count()
size_t v8::internal::compiler::turboshaft::IterationCount::approx_count () const [inline]
Definition at line 65 of file loop-unrolling-reducer.h.
                              {
    DCHECK_EQ(kind_, Kind::kApprox);
    return count_;
  }
References count_, DCHECK_EQ, kApprox, and kind_.
Exact()
static IterationCount v8::internal::compiler::turboshaft::IterationCount::Exact (size_t count) [inline], [static]
Definition at line 44 of file loop-unrolling-reducer.h.
                                            {
    return IterationCount(Kind::kExact, count);
  }
References IterationCount(), and kExact.
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::CountIterationsImpl().
exact_count()
size_t v8::internal::compiler::turboshaft::IterationCount::exact_count () const [inline]
Definition at line 61 of file loop-unrolling-reducer.h.
                             {
    DCHECK_EQ(kind_, Kind::kExact);
    return count_;
  }
References count_, DCHECK_EQ, kExact, and kind_.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingReducer< Next >::FullyUnrollLoop().
IsApprox()
bool v8::internal::compiler::turboshaft::IterationCount::IsApprox () const [inline]
Definition at line 71 of file loop-unrolling-reducer.h.
{ return kind_ == Kind::kApprox; }
References kApprox, and kind_.
Referenced by IsSmallerThan().
IsExact()
bool v8::internal::compiler::turboshaft::IterationCount::IsExact () const [inline]
Definition at line 70 of file loop-unrolling-reducer.h.
{ return kind_ == Kind::kExact; }
References kExact, and kind_.
Referenced by IsSmallerThan().
IsSmallerThan()
bool v8::internal::compiler::turboshaft::IterationCount::IsSmallerThan (size_t max) [inline]
Definition at line 74 of file loop-unrolling-reducer.h.
                                 {
    return (IsExact() || IsApprox()) && count_ < max;
  }
References count_, IsApprox(), and IsExact().
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::DetectUnrollableLoops().
IsUnknown()
bool v8::internal::compiler::turboshaft::IterationCount::IsUnknown () const [inline]
Definition at line 72 of file loop-unrolling-reducer.h.
{ return kind_ == Kind::kUnknown; }
References kind_, and kUnknown.
Unknown()
static IterationCount v8::internal::compiler::turboshaft::IterationCount::Unknown () [inline], [static]
Definition at line 51 of file loop-unrolling-reducer.h.
{ return IterationCount(Kind::kUnknown); }
References IterationCount(), and kUnknown.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingAnalyzer::GetIterationCount().
Member Data Documentation
count_
size_t v8::internal::compiler::turboshaft::IterationCount::count_ [private]
Definition at line 80 of file loop-unrolling-reducer.h.
Referenced by approx_count(), exact_count(), and IsSmallerThan().
kind_
Kind v8::internal::compiler::turboshaft::IterationCount::kind_ [private]
Definition at line 79 of file loop-unrolling-reducer.h.
Referenced by approx_count(), exact_count(), IsApprox(), IsExact(), and IsUnknown().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/loop-unrolling-reducer.h