v8::internal::Scavenger Class Reference
#include <scavenger.h>
Classes
struct PromotedListEntry
Public Types
using CopiedList = ::heap::base::Worklist< Tagged< HeapObject >, kCopiedListSegmentSize >
using ObjectAndMap = std::pair< Tagged< HeapObject >, Tagged< Map > >
using PinnedList = ::heap::base::Worklist< ObjectAndMap, kPinnedListSegmentSize >
using PromotedList = ::heap::base::Worklist< PromotedListEntry, kPromotedListSegmentSize >
using EmptyChunksList = ::heap::base::Worklist< MutablePageMetadata *, 64 >
Public Member Functions
Scavenger (ScavengerCollector *collector, Heap *heap, bool is_logging, EmptyChunksList *empty_chunks, CopiedList *copied_list, PinnedList *pinned_list, PromotedList *promoted_list, EphemeronRememberedSet::TableList *ephemeron_table_list)
void ScavengePage (MutablePageMetadata *page)
void Process (JobDelegate *delegate=nullptr)
void Finalize ()
void Publish ()
void AddEphemeronHashTable (Tagged< EphemeronHashTable > table)
bool PromoteIfLargeObject (Tagged< HeapObject > object)
void PinAndPushObject (MemoryChunk *chunk, Tagged< HeapObject > object, MapWord map_word)
void VisitPinnedObjects ()
size_t bytes_copied () const
size_t bytes_promoted () const
Static Public Attributes
static constexpr int kCopiedListSegmentSize = 256
static constexpr int kPinnedListSegmentSize = 64
static constexpr int kPromotedListSegmentSize = 256
Private Types
enum PromotionHeapChoice { kPromoteIntoLocalHeap
, kPromoteIntoSharedHeap
 }
Private Member Functions
Heap * heap ()
void SynchronizePageAccess (Tagged< MaybeObject > object) const
void AddPageToSweeperIfNecessary (MutablePageMetadata *page)
template<typename TSlot >
SlotCallbackResult CheckAndScavengeObject (Heap *heap, TSlot slot)
template<typename TSlot >
void CheckOldToNewSlotForSharedUntyped (MemoryChunk *chunk, MutablePageMetadata *page, TSlot slot)
void CheckOldToNewSlotForSharedTyped (MemoryChunk *chunk, MutablePageMetadata *page, SlotType slot_type, Address slot_address, Tagged< MaybeObject > new_target)
template<typename THeapObjectSlot >
SlotCallbackResult ScavengeObject (THeapObjectSlot p, Tagged< HeapObject > object)
bool MigrateObject (Tagged< Map > map, Tagged< HeapObject > source, Tagged< HeapObject > target, int size, PromotionHeapChoice promotion_heap_choice)
SlotCallbackResult RememberedSetEntryNeeded (CopyAndForwardResult result)
template<typename THeapObjectSlot >
CopyAndForwardResult SemiSpaceCopyObject (Tagged< Map > map, THeapObjectSlot slot, Tagged< HeapObject > object, int object_size, ObjectFields object_fields)
template<typename THeapObjectSlot , PromotionHeapChoice promotion_heap_choice = kPromoteIntoLocalHeap>
CopyAndForwardResult PromoteObject (Tagged< Map > map, THeapObjectSlot slot, Tagged< HeapObject > object, int object_size, ObjectFields object_fields)
template<typename THeapObjectSlot >
SlotCallbackResult EvacuateObject (THeapObjectSlot slot, Tagged< Map > map, Tagged< HeapObject > source)
bool HandleLargeObject (Tagged< Map > map, Tagged< HeapObject > object, int object_size, ObjectFields object_fields)
template<typename THeapObjectSlot , PromotionHeapChoice promotion_heap_choice = kPromoteIntoLocalHeap>
SlotCallbackResult EvacuateObjectDefault (Tagged< Map > map, THeapObjectSlot slot, Tagged< HeapObject > object, int object_size, ObjectFields object_fields)
template<typename THeapObjectSlot >
SlotCallbackResult EvacuateThinString (Tagged< Map > map, THeapObjectSlot slot, Tagged< ThinString > object, int object_size)
template<typename THeapObjectSlot >
SlotCallbackResult EvacuateShortcutCandidate (Tagged< Map > map, THeapObjectSlot slot, Tagged< ConsString > object, int object_size)
template<typename THeapObjectSlot >
SlotCallbackResult EvacuateInPlaceInternalizableString (Tagged< Map > map, THeapObjectSlot slot, Tagged< String > string, int object_size, ObjectFields object_fields)
void IterateAndScavengePromotedObject (Tagged< HeapObject > target, Tagged< Map > map, int size)
void RememberPromotedEphemeron (Tagged< EphemeronHashTable > table, int index)
bool ShouldEagerlyProcessPromotedList () const
void PushPinnedObject (Tagged< HeapObject > object, Tagged< Map > map, int object_size)
void PushPinnedPromotedObject (Tagged< HeapObject > object, Tagged< Map > map, int object_size)
Private Attributes
ScavengerCollector *const collector_
Heap *const heap_
EmptyChunksList::Local local_empty_chunks_
CopiedList::Local local_copied_list_
PinnedList::Local local_pinned_list_
PromotedList::Local local_promoted_list_
EphemeronRememberedSet::TableList::Local local_ephemeron_table_list_
PretenuringHandler::PretenuringFeedbackMap local_pretenuring_feedback_
EphemeronRememberedSet::TableMap local_ephemeron_remembered_set_
SurvivingNewLargeObjectsMap local_surviving_new_large_objects_
size_t copied_size_ {0}
size_t promoted_size_ {0}
EvacuationAllocator allocator_
const bool is_logging_
const bool shared_string_table_
const bool mark_shared_heap_
const bool shortcut_strings_
Static Private Attributes
static const int kInterruptThreshold = 128
Friends
class IterateAndScavengePromotedObjectsVisitor
class RootScavengeVisitor
class ScavengeVisitor
Detailed Description
Definition at line 42 of file scavenger.h.
Member Typedef Documentation
CopiedList
using v8::internal::Scavenger::CopiedList = ::heap::base::Worklist<Tagged<HeapObject>, kCopiedListSegmentSize>
Definition at line 48 of file scavenger.h.
EmptyChunksList
using v8::internal::Scavenger::EmptyChunksList = ::heap::base::Worklist<MutablePageMetadata*, 64>
Definition at line 63 of file scavenger.h.
ObjectAndMap
using v8::internal::Scavenger::ObjectAndMap = std::pair<Tagged<HeapObject>, Tagged<Map> >
Definition at line 51 of file scavenger.h.
PinnedList
using v8::internal::Scavenger::PinnedList = ::heap::base::Worklist<ObjectAndMap, kPinnedListSegmentSize>
Definition at line 52 of file scavenger.h.
PromotedList
using v8::internal::Scavenger::PromotedList = ::heap::base::Worklist<PromotedListEntry, kPromotedListSegmentSize>
Definition at line 60 of file scavenger.h.
Member Enumeration Documentation
PromotionHeapChoice
enum v8::internal::Scavenger::PromotionHeapChoice [private]
Enumerator
kPromoteIntoLocalHeap
kPromoteIntoSharedHeap
Definition at line 95 of file scavenger.h.
{ kPromoteIntoLocalHeap, kPromoteIntoSharedHeap };
Constructor & Destructor Documentation
Scavenger()
v8::internal::Scavenger::Scavenger (ScavengerCollector * collector, Heap * heap, bool is_logging, EmptyChunksList * empty_chunks, CopiedList * copied_list, PinnedList * pinned_list, PromotedList * promoted_list, EphemeronRememberedSet::TableList * ephemeron_table_list)
Definition at line 1125 of file scavenger.cc.
    : collector_(collector),
      heap_(heap),
      local_empty_chunks_(*empty_chunks),
      local_copied_list_(*copied_list),
      local_pinned_list_(*pinned_list),
      local_promoted_list_(*promoted_list),
      local_ephemeron_table_list_(*ephemeron_table_list),
      local_pretenuring_feedback_(PretenuringHandler::kInitialFeedbackCapacity),
      allocator_(heap, CompactionSpaceKind::kCompactionSpaceForScavenge),
      is_logging_(is_logging),
      shared_string_table_(v8_flags.shared_string_table &&
                           heap->isolate()->has_shared_space()),
      mark_shared_heap_(heap->isolate()->is_shared_space_isolate()),
      shortcut_strings_(
          heap->CanShortcutStringsDuringGC(GarbageCollector::SCAVENGER)) {
  DCHECK(!heap->incremental_marking()->IsMarking());
}
References v8::internal::DCHECK(), v8::internal::kCompactionSpaceForScavenge, and v8::internal::SCAVENGER.
Member Function Documentation
AddEphemeronHashTable()
void v8::internal::Scavenger::AddEphemeronHashTable (Tagged< EphemeronHashTable > table)
Definition at line 1386 of file scavenger.cc.
                                                                      {
  local_ephemeron_table_list_.Push(table);
}
Referenced by v8::internal::ScavengeVisitor::VisitEphemeronHashTable().
AddPageToSweeperIfNecessary()
void v8::internal::Scavenger::AddPageToSweeperIfNecessary (MutablePageMetadata * page) [private]
bytes_copied()
size_t v8::internal::Scavenger::bytes_copied () const [inline]
Definition at line 91 of file scavenger.h.
{ return copied_size_; }
References copied_size_.
Referenced by v8::internal::ScavengerCollector::JobTask::ProcessItems().
bytes_promoted()
size_t v8::internal::Scavenger::bytes_promoted () const [inline]
Definition at line 92 of file scavenger.h.
{ return promoted_size_; }
References promoted_size_.
Referenced by v8::internal::ScavengerCollector::JobTask::ProcessItems().
CheckAndScavengeObject()
template<typename TSlot >
SlotCallbackResult v8::internal::Scavenger::CheckAndScavengeObject (Heap * heap, TSlot slot) [inline], [private]
Definition at line 418 of file scavenger-inl.h.
                                                                           {
  static_assert(
      std::is_same_v<TSlot, FullMaybeObjectSlot> ||
          std::is_same_v<TSlot, MaybeObjectSlot>,
      "Only FullMaybeObjectSlot and MaybeObjectSlot are expected here");
  using THeapObjectSlot = typename TSlot::THeapObjectSlot;
  Tagged<MaybeObject> object = *slot;
  if (Heap::InFromPage(object)) {
    Tagged<HeapObject> heap_object = object.GetHeapObject();
    SlotCallbackResult result =
        ScavengeObject(THeapObjectSlot(slot), heap_object);
    DCHECK_IMPLIES(result == REMOVE_SLOT,
                   !HeapLayout::InYoungGeneration((*slot).GetHeapObject()) ||
                       MemoryChunk::FromHeapObject((*slot).GetHeapObject())
                           ->IsLargePage() ||
                       MemoryChunk::FromHeapObject((*slot).GetHeapObject())
                           ->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED));
    return result;
  } else if (Heap::InToPage(object)) {
    // Already updated slot. This can happen when processing of the work list
    // is interleaved with processing roots.
    return KEEP_SLOT;
  }
  // Slots can point to "to" space if the slot has been recorded multiple
  // times in the remembered set. We remove the redundant slot now.
  return REMOVE_SLOT;
}
References DCHECK_IMPLIES, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::Heap::InFromPage(), v8::internal::Heap::InToPage(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsLargePage(), heap::base::KEEP_SLOT, heap::base::REMOVE_SLOT, v8::base::internal::result, ScavengeObject(), and v8::internal::MemoryChunk::WILL_BE_PROMOTED.
Referenced by ScavengePage().
CheckOldToNewSlotForSharedTyped()
void v8::internal::Scavenger::CheckOldToNewSlotForSharedTyped (MemoryChunk * chunk, MutablePageMetadata * page, SlotType slot_type, Address slot_address, Tagged< MaybeObject > new_target) [inline], [private]
Definition at line 1404 of file scavenger.cc.
                                                          {
  Tagged<HeapObject> heap_object;
  if (new_target.GetHeapObject(&heap_object) &&
      HeapLayout::InWritableSharedSpace(heap_object)) {
    const uintptr_t offset = chunk->Offset(slot_address);
    DCHECK_LT(offset, static_cast<uintptr_t>(TypedSlotSet::kMaxOffset));
    base::MutexGuard guard(page->mutex());
    RememberedSet<OLD_TO_SHARED>::InsertTyped(page, slot_type,
                                              static_cast<uint32_t>(offset));
  }
}
References DCHECK_LT, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::MutablePageMetadata::mutex(), and v8::internal::MemoryChunk::Offset().
Referenced by ScavengePage().
CheckOldToNewSlotForSharedUntyped()
template<typename TSlot >
void v8::internal::Scavenger::CheckOldToNewSlotForSharedUntyped (MemoryChunk * chunk, MutablePageMetadata * page, TSlot slot) [inline], [private]
Definition at line 1391 of file scavenger.cc.
                                                              {
  Tagged<MaybeObject> object = *slot;
  Tagged<HeapObject> heap_object;
  if (object.GetHeapObject(&heap_object) &&
      HeapLayout::InWritableSharedSpace(heap_object)) {
    RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::ATOMIC>(
        page, chunk->Offset(slot.address()));
  }
}
References v8::internal::MemoryChunk::Offset().
Referenced by ScavengePage().
EvacuateInPlaceInternalizableString()
template<typename THeapObjectSlot >
SlotCallbackResult v8::internal::Scavenger::EvacuateInPlaceInternalizableString (Tagged< Map > map, THeapObjectSlot slot, Tagged< String > string, int object_size, ObjectFields object_fields) [inline], [private]
Definition at line 313 of file scavenger-inl.h.
                                                 {
  DCHECK(String::IsInPlaceInternalizable(map->instance_type()));
  DCHECK_EQ(object_fields, Map::ObjectFieldsFrom(map->visitor_id()));
  if (shared_string_table_) {
    return EvacuateObjectDefault<THeapObjectSlot, kPromoteIntoSharedHeap>(
        map, slot, object, object_size, object_fields);
  }
  return EvacuateObjectDefault(map, slot, object, object_size, object_fields);
}
References v8::internal::DCHECK(), DCHECK_EQ, EvacuateObjectDefault(), v8::internal::String::IsInPlaceInternalizable(), v8::internal::Map::ObjectFieldsFrom(), and shared_string_table_.
Referenced by EvacuateObject().
EvacuateObject()
template<typename THeapObjectSlot >
SlotCallbackResult v8::internal::Scavenger::EvacuateObject (THeapObjectSlot slot, Tagged< Map > map, Tagged< HeapObject > source) [inline], [private]
Definition at line 326 of file scavenger-inl.h.
                                                                        {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  SLOW_DCHECK(Heap::InFromPage(source));
  SLOW_DCHECK(!MapWord::FromMap(map).IsForwardingAddress());
  int size = source->SizeFromMap(map);
  // Cannot use ::cast() below because that would add checks in debug mode
  // that require re-reading the map.
  VisitorId visitor_id = map->visitor_id();
  switch (visitor_id) {
    case kVisitThinString:
      // At the moment we don't allow weak pointers to thin strings.
      DCHECK(!(*slot).IsWeak());
      return EvacuateThinString(map, slot, UncheckedCast<ThinString>(source),
                                size);
    case kVisitShortcutCandidate:
      DCHECK(!(*slot).IsWeak());
      // At the moment we don't allow weak pointers to cons strings.
      return EvacuateShortcutCandidate(map, slot,
                                       UncheckedCast<ConsString>(source), size);
    case kVisitSeqOneByteString:
    case kVisitSeqTwoByteString:
      DCHECK(String::IsInPlaceInternalizable(map->instance_type()));
      static_assert(Map::ObjectFieldsFrom(kVisitSeqOneByteString) ==
                    Map::ObjectFieldsFrom(kVisitSeqTwoByteString));
      return EvacuateInPlaceInternalizableString(
          map, slot, UncheckedCast<String>(source), size,
          Map::ObjectFieldsFrom(kVisitSeqOneByteString));
    default:
      return EvacuateObjectDefault(map, slot, source, size,
                                   Map::ObjectFieldsFrom(visitor_id));
  }
}
References v8::internal::DCHECK(), EvacuateInPlaceInternalizableString(), EvacuateObjectDefault(), EvacuateShortcutCandidate(), EvacuateThinString(), v8::internal::MapWord::FromMap(), v8::internal::Heap::InFromPage(), v8::internal::String::IsInPlaceInternalizable(), v8::internal::Map::ObjectFieldsFrom(), size(), and SLOW_DCHECK.
Referenced by ScavengeObject().
EvacuateObjectDefault()
template<typename THeapObjectSlot , Scavenger::PromotionHeapChoice promotion_heap_choice>
SlotCallbackResult v8::internal::Scavenger::EvacuateObjectDefault (Tagged< Map > map, THeapObjectSlot slot, Tagged< HeapObject > object, int object_size, ObjectFields object_fields) [inline], [private]
Definition at line 200 of file scavenger-inl.h.
                                                 {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  SLOW_DCHECK(object->SizeFromMap(map) == object_size);
  CopyAndForwardResult result;
  if (HandleLargeObject(map, object, object_size, object_fields)) {
    return REMOVE_SLOT;
  }
  SLOW_DCHECK(static_cast<size_t>(object_size) <=
              MemoryChunkLayout::AllocatableMemoryInDataPage());
  if (!heap()->semi_space_new_space()->ShouldBePromoted(object.address())) {
    // A semi-space copy may fail due to fragmentation. In that case, we
    // try to promote the object.
    result = SemiSpaceCopyObject(map, slot, object, object_size, object_fields);
    if (result != CopyAndForwardResult::FAILURE) {
      return RememberedSetEntryNeeded(result);
    }
  }
  // We may want to promote this object if the object was already semi-space
  // copied in a previous young generation GC or if the semi-space copy above
  // failed.
  result = PromoteObject<THeapObjectSlot, promotion_heap_choice>(
      map, slot, object, object_size, object_fields);
  if (result != CopyAndForwardResult::FAILURE) {
    return RememberedSetEntryNeeded(result);
  }
  // If promotion failed, we try to copy the object to the other semi-space.
  result = SemiSpaceCopyObject(map, slot, object, object_size, object_fields);
  if (result != CopyAndForwardResult::FAILURE) {
    return RememberedSetEntryNeeded(result);
  }
  heap()->FatalProcessOutOfMemory("Scavenger: semi-space copy");
  UNREACHABLE();
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInDataPage(), v8::internal::FAILURE, v8::internal::Heap::FatalProcessOutOfMemory(), HandleLargeObject(), heap(), RememberedSetEntryNeeded(), heap::base::REMOVE_SLOT, v8::base::internal::result, SemiSpaceCopyObject(), SLOW_DCHECK, and v8::internal::UNREACHABLE().
Referenced by EvacuateInPlaceInternalizableString(), EvacuateObject(), EvacuateShortcutCandidate(), and EvacuateThinString().
EvacuateShortcutCandidate()
template<typename THeapObjectSlot >
SlotCallbackResult v8::internal::Scavenger::EvacuateShortcutCandidate (Tagged< Map > map, THeapObjectSlot slot, Tagged< ConsString > object, int object_size) [inline], [private]
Definition at line 271 of file scavenger-inl.h.
                     {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  DCHECK(IsShortcutCandidate(map->instance_type()));
  if (shortcut_strings_ &&
      object->unchecked_second() == ReadOnlyRoots(heap()).empty_string()) {
    Tagged<HeapObject> first = Cast<HeapObject>(object->unchecked_first());
    UpdateHeapObjectReferenceSlot(slot, first);
    if (!HeapLayout::InYoungGeneration(first)) {
      object->set_map_word_forwarded(first, kRelaxedStore);
      return REMOVE_SLOT;
    }
    MapWord first_word = first->map_word(kRelaxedLoad);
    if (first_word.IsForwardingAddress()) {
      Tagged<HeapObject> target = first_word.ToForwardingAddress(first);
      UpdateHeapObjectReferenceSlot(slot, target);
      SynchronizePageAccess(target);
      object->set_map_word_forwarded(target, kRelaxedStore);
      return HeapLayout::InYoungGeneration(target) ? KEEP_SLOT : REMOVE_SLOT;
    }
    Tagged<Map> first_map = first_word.ToMap();
    SlotCallbackResult result = EvacuateObjectDefault(
        first_map, slot, first, first->SizeFromMap(first_map),
        Map::ObjectFieldsFrom(first_map->visitor_id()));
    object->set_map_word_forwarded(slot.ToHeapObject(), kRelaxedStore);
    return result;
  }
  DCHECK_EQ(ObjectFields::kMaybePointers,
            Map::ObjectFieldsFrom(map->visitor_id()));
  return EvacuateObjectDefault(map, slot, object, object_size,
                               ObjectFields::kMaybePointers);
}
References v8::internal::DCHECK(), DCHECK_EQ, EvacuateObjectDefault(), heap(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MapWord::IsForwardingAddress(), v8::internal::IsShortcutCandidate(), heap::base::KEEP_SLOT, v8::internal::kMaybePointers, v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::Map::ObjectFieldsFrom(), heap::base::REMOVE_SLOT, v8::base::internal::result, shortcut_strings_, SynchronizePageAccess(), v8::internal::MapWord::ToForwardingAddress(), v8::internal::MapWord::ToMap(), and v8::internal::UpdateHeapObjectReferenceSlot().
Referenced by EvacuateObject().
EvacuateThinString()
template<typename THeapObjectSlot >
SlotCallbackResult v8::internal::Scavenger::EvacuateThinString (Tagged< Map > map, THeapObjectSlot slot, Tagged< ThinString > object, int object_size) [inline], [private]
Definition at line 245 of file scavenger-inl.h.
                                                                  {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  if (shortcut_strings_) {
    // The ThinString should die after Scavenge, so avoid writing the proper
    // forwarding pointer and instead just signal the actual object as forwarded
    // reference.
    Tagged<String> actual = object->actual();
    // ThinStrings always refer to internalized strings, which are always in old
    // space.
    DCHECK(!HeapLayout::InYoungGeneration(actual));
    UpdateHeapObjectReferenceSlot(slot, actual);
    return REMOVE_SLOT;
  }
  DCHECK_EQ(ObjectFields::kMaybePointers,
            Map::ObjectFieldsFrom(map->visitor_id()));
  return EvacuateObjectDefault(map, slot, object, object_size,
                               ObjectFields::kMaybePointers);
}
References v8::internal::DCHECK(), DCHECK_EQ, EvacuateObjectDefault(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::kMaybePointers, v8::internal::Map::ObjectFieldsFrom(), heap::base::REMOVE_SLOT, shortcut_strings_, and v8::internal::UpdateHeapObjectReferenceSlot().
Referenced by EvacuateObject().
Finalize()
void v8::internal::Scavenger::Finalize ()
Definition at line 1355 of file scavenger.cc.
                         {
  heap()->pretenuring_handler()->MergeAllocationSitePretenuringFeedback(
      local_pretenuring_feedback_);
  for (const auto& it : local_ephemeron_remembered_set_) {
    // The ephemeron objects in the remembered set should be either large
    // objects, promoted to old space, or pinned objects on quarantined pages
    // that will be promoted.
    DCHECK_IMPLIES(
        !MemoryChunk::FromHeapObject(it.first)->IsLargePage(),
        !HeapLayout::InYoungGeneration(it.first) ||
            (HeapLayout::IsSelfForwarded(it.first) &&
             MemoryChunk::FromHeapObject(it.first)->IsQuarantined() &&
             MemoryChunk::FromHeapObject(it.first)->IsFlagSet(
                 MemoryChunk::WILL_BE_PROMOTED)));
    heap()->ephemeron_remembered_set()->RecordEphemeronKeyWrites(
        it.first, std::move(it.second));
  }
  heap()->IncrementNewSpaceSurvivingObjectSize(copied_size_);
  heap()->IncrementPromotedObjectsSize(promoted_size_);
  collector_->MergeSurvivingNewLargeObjects(local_surviving_new_large_objects_);
  allocator_.Finalize();
  local_empty_chunks_.Publish();
  local_ephemeron_table_list_.Publish();
}
References DCHECK_IMPLIES, and heap().
HandleLargeObject()
bool v8::internal::Scavenger::HandleLargeObject (Tagged< Map > map, Tagged< HeapObject > object, int object_size, ObjectFields object_fields) [inline], [private]
Definition at line 169 of file scavenger-inl.h.
                                                                               {
  // Quick check first: A large object is the first (and only) object on a data
  // page (code pages have a different offset but are never young). This check
  // avoids the page flag access.
  if (MemoryChunk::AddressToOffset(object.address()) !=
      MemoryChunkLayout::ObjectStartOffsetInDataPage()) {
    return false;
  }
  // Most objects are already filtered out. Use page flags to filter out regular
  // objects at the beginning of a page.
  if (!MemoryChunk::FromHeapObject(object)->InNewLargeObjectSpace()) {
    return false;
  }
  DCHECK_EQ(NEW_LO_SPACE,
            MutablePageMetadata::FromHeapObject(object)->owner_identity());
  if (object->relaxed_compare_and_swap_map_word_forwarded(MapWord::FromMap(map),
                                                          object)) {
    local_surviving_new_large_objects_.insert({object, map});
    promoted_size_ += object_size;
    if (object_fields == ObjectFields::kMaybePointers) {
      local_promoted_list_.Push({object, map, object_size});
    }
  }
  return true;
}
References v8::internal::MemoryChunk::AddressToOffset(), DCHECK_EQ, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MapWord::FromMap(), v8::internal::kMaybePointers, local_promoted_list_, local_surviving_new_large_objects_, v8::internal::NEW_LO_SPACE, v8::internal::MemoryChunkLayout::ObjectStartOffsetInDataPage(), promoted_size_, and heap::base::Worklist< EntryType, MinSegmentSize >::Local::Push().
Referenced by EvacuateObjectDefault().
heap()
Heap* v8::internal::Scavenger::heap () [inline], [private]
Definition at line 101 of file scavenger.h.
{ return heap_; }
References heap_.
Referenced by EvacuateObjectDefault(), EvacuateShortcutCandidate(), MigrateObject(), PromoteObject(), ScavengeObject(), ScavengePage(), SemiSpaceCopyObject(), v8::internal::ScavengeVisitor::VisitExternalPointer(), and v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitExternalPointer().
IterateAndScavengePromotedObject()
void v8::internal::Scavenger::IterateAndScavengePromotedObject (Tagged< HeapObject > target, Tagged< Map > map, int size) [private]
Definition at line 1147 of file scavenger.cc.
                                                                            {
  // We are not collecting slots on new space objects during mutation thus we
  // have to scan for pointers to evacuation candidates when we promote
  // objects. But we should not record any slots in non-black objects. Grey
  // object's slots would be rescanned. White object might not survive until
  // the end of collection it would be a violation of the invariant to record
  // its slots.
  IterateAndScavengePromotedObjectsVisitor visitor(this);
  // Iterate all outgoing pointers including map word.
  visitor.Visit(map, target, size);
  if (IsJSArrayBufferMap(map)) {
    DCHECK(!MemoryChunk::FromHeapObject(target)->IsLargePage());
    GCSafeCast<JSArrayBuffer>(target, heap_)->YoungMarkExtensionPromoted();
  }
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), heap_, size(), and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
Referenced by Process().
MigrateObject()
bool v8::internal::Scavenger::MigrateObject (Tagged< Map > map, Tagged< HeapObject > source, Tagged< HeapObject > target, int size, PromotionHeapChoice promotion_heap_choice) [inline], [private]
Definition at line 49 of file scavenger-inl.h.
                                                                         {
  // This CAS can be relaxed because we do not access the object body if the
  // object was already copied by another thread. We only access the page header
  // of such objects and this is safe because of the memory fence after page
  // header initialization.
  if (!source->relaxed_compare_and_swap_map_word_forwarded(
          MapWord::FromMap(map), target)) {
    // Other task migrated the object.
    return false;
  }
  // Copy the content of source to target. Note that we do this on purpose
  // *after* the CAS. This avoids copying of the object in the (unlikely)
  // failure case. It also helps us to ensure that we do not rely on non-relaxed
  // memory ordering for the CAS above.
  target->set_map_word(map, kRelaxedStore);
  heap()->CopyBlock(target.address() + kTaggedSize,
                    source.address() + kTaggedSize, size - kTaggedSize);
  if (V8_UNLIKELY(is_logging_)) {
    heap()->OnMoveEvent(source, target, size);
  }
  PretenuringHandler::UpdateAllocationSite(heap_, map, source, size,
                                           &local_pretenuring_feedback_);
  return true;
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::Heap::CopyBlock(), v8::internal::MapWord::FromMap(), heap(), heap_, is_logging_, v8::kRelaxedStore, v8::internal::kTaggedSize, local_pretenuring_feedback_, v8::internal::Heap::OnMoveEvent(), size(), v8::internal::PretenuringHandler::UpdateAllocationSite(), and V8_UNLIKELY.
Referenced by PromoteObject(), and SemiSpaceCopyObject().
PinAndPushObject()
void v8::internal::Scavenger::PinAndPushObject (MemoryChunk * chunk, Tagged< HeapObject > object, MapWord map_word)
Definition at line 1426 of file scavenger.cc.
                                                   {
  DCHECK(chunk->Metadata()->Contains(object->address()));
  DCHECK_EQ(map_word, object->map_word(kRelaxedLoad));
  Tagged<Map> map = map_word.ToMap();
  int object_size = object->SizeFromMap(map);
  PretenuringHandler::UpdateAllocationSite(heap_, map, object, object_size,
                                           &local_pretenuring_feedback_);
  object->set_map_word_forwarded(object, kRelaxedStore);
  DCHECK(object->map_word(kRelaxedLoad).IsForwardingAddress());
  DCHECK(HeapLayout::IsSelfForwarded(object));
  if (chunk->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED)) {
    PushPinnedPromotedObject(object, map, object_size);
  } else {
    PushPinnedObject(object, map, object_size);
  }
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::MemoryChunkMetadata::Contains(), DCHECK, DCHECK_EQ, v8::internal::MemoryChunk::IsFlagSet(), v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::MemoryChunk::Metadata(), and v8::internal::MapWord::ToMap().
Process()
void v8::internal::Scavenger::Process (JobDelegate * delegate = nullptr)
Definition at line 1261 of file scavenger.cc.
                                             {
  ScavengeVisitor scavenge_visitor(this);
  bool done;
  size_t objects = 0;
  do {
    done = true;
    Tagged<HeapObject> object;
    while (!ShouldEagerlyProcessPromotedList() &&
           local_copied_list_.Pop(&object)) {
      scavenge_visitor.Visit(object);
      done = false;
      if (delegate && ((++objects % kInterruptThreshold) == 0)) {
        if (!local_copied_list_.IsLocalEmpty()) {
          delegate->NotifyConcurrencyIncrease();
        }
      }
    }
    struct PromotedListEntry entry;
    while (local_promoted_list_.Pop(&entry)) {
      Tagged<HeapObject> target = entry.heap_object;
      IterateAndScavengePromotedObject(target, entry.map, entry.size);
      done = false;
      if (delegate && ((++objects % kInterruptThreshold) == 0)) {
        if (!local_promoted_list_.IsGlobalEmpty()) {
          delegate->NotifyConcurrencyIncrease();
        }
      }
    }
  } while (!done);
}
References v8::internal::Scavenger::PromotedListEntry::heap_object, heap::base::Worklist< EntryType, MinSegmentSize >::Local::IsGlobalEmpty(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::IsLocalEmpty(), IterateAndScavengePromotedObject(), kInterruptThreshold, local_copied_list_, local_promoted_list_, v8::internal::Scavenger::PromotedListEntry::map, v8::JobDelegate::NotifyConcurrencyIncrease(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::Pop(), ShouldEagerlyProcessPromotedList(), v8::internal::Scavenger::PromotedListEntry::size, and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
Referenced by v8::internal::ScavengerCollector::JobTask::ProcessItems().
PromoteIfLargeObject()
bool v8::internal::Scavenger::PromoteIfLargeObject (Tagged< HeapObject > object)
Definition at line 1420 of file scavenger.cc.
                                                              {
  Tagged<Map> map = object->map();
  return HandleLargeObject(map, object, object->SizeFromMap(map),
                           Map::ObjectFieldsFrom(map->visitor_id()));
}
PromoteObject()
template<typename THeapObjectSlot , Scavenger::PromotionHeapChoice promotion_heap_choice>
CopyAndForwardResult v8::internal::Scavenger::PromoteObject (Tagged< Map > map, THeapObjectSlot slot, Tagged< HeapObject > object, int object_size, ObjectFields object_fields) [inline], [private]
Definition at line 119 of file scavenger-inl.h.
                                                                          {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  DCHECK_GE(object_size, Heap::kMinObjectSizeInTaggedWords * kTaggedSize);
  AllocationSpace target_space =
      promotion_heap_choice == kPromoteIntoLocalHeap ? OLD_SPACE : SHARED_SPACE;
  AllocationAlignment alignment =
      HeapObject::RequiredAlignment(target_space, map);
  AllocationResult allocation =
      allocator_.Allocate(target_space, object_size, alignment);
  Tagged<HeapObject> target;
  if (allocation.To(&target)) {
    DCHECK(heap()->non_atomic_marking_state()->IsUnmarked(target));
    const bool self_success =
        MigrateObject(map, object, target, object_size, promotion_heap_choice);
    if (!self_success) {
      allocator_.FreeLast(target_space, target, object_size);
      MapWord map_word = object->map_word(kRelaxedLoad);
      UpdateHeapObjectReferenceSlot(slot, map_word.ToForwardingAddress(object));
      SynchronizePageAccess(*slot);
      DCHECK(!Heap::InFromPage(*slot));
      return Heap::InToPage(*slot)
                 ? CopyAndForwardResult::SUCCESS_YOUNG_GENERATION
                 : CopyAndForwardResult::SUCCESS_OLD_GENERATION;
    }
    UpdateHeapObjectReferenceSlot(slot, target);
    if (object_fields == ObjectFields::kMaybePointers) {
      local_promoted_list_.Push({target, map, object_size});
    }
    promoted_size_ += object_size;
    return CopyAndForwardResult::SUCCESS_OLD_GENERATION;
  }
  return CopyAndForwardResult::FAILURE;
}
References v8::internal::EvacuationAllocator::Allocate(), allocator_, v8::internal::DCHECK(), DCHECK_GE, v8::internal::FAILURE, v8::internal::EvacuationAllocator::FreeLast(), heap(), v8::internal::Heap::InFromPage(), v8::internal::Heap::InToPage(), v8::internal::kMaybePointers, v8::internal::Heap::kMinObjectSizeInTaggedWords, kPromoteIntoLocalHeap, v8::kRelaxedLoad, v8::internal::kTaggedSize, local_promoted_list_, MigrateObject(), v8::internal::OLD_SPACE, promoted_size_, heap::base::Worklist< EntryType, MinSegmentSize >::Local::Push(), v8::internal::HeapObject::RequiredAlignment(), v8::internal::SHARED_SPACE, v8::internal::SUCCESS_OLD_GENERATION, v8::internal::SUCCESS_YOUNG_GENERATION, SynchronizePageAccess(), v8::internal::AllocationResult::To(), v8::internal::MapWord::ToForwardingAddress(), and v8::internal::UpdateHeapObjectReferenceSlot().
Publish()
void v8::internal::Scavenger::Publish ()
Definition at line 1380 of file scavenger.cc.
                        {
  local_copied_list_.Publish();
  local_pinned_list_.Publish();
  local_promoted_list_.Publish();
}
Referenced by v8::internal::RootScavengeVisitor::~RootScavengeVisitor().
PushPinnedObject()
void v8::internal::Scavenger::PushPinnedObject (Tagged< HeapObject > object, Tagged< Map > map, int object_size) [private]
Definition at line 1444 of file scavenger.cc.
                                                  {
  DCHECK(HeapLayout::IsSelfForwarded(object));
  DCHECK(!MemoryChunk::FromHeapObject(object)->IsFlagSet(
      MemoryChunk::WILL_BE_PROMOTED));
  DCHECK_EQ(object_size, object->SizeFromMap(map));
  local_pinned_list_.Push(ObjectAndMap(object, map));
  copied_size_ += object_size;
}
References DCHECK, and DCHECK_EQ.
PushPinnedPromotedObject()
void v8::internal::Scavenger::PushPinnedPromotedObject (Tagged< HeapObject > object, Tagged< Map > map, int object_size) [private]
Definition at line 1454 of file scavenger.cc.
                                                                           {
  DCHECK(HeapLayout::IsSelfForwarded(object));
  DCHECK(MemoryChunk::FromHeapObject(object)->IsFlagSet(
      MemoryChunk::WILL_BE_PROMOTED));
  DCHECK_EQ(object_size, object->SizeFromMap(map));
  local_promoted_list_.Push({object, map, object_size});
  promoted_size_ += object_size;
}
References DCHECK, and DCHECK_EQ.
RememberedSetEntryNeeded()
SlotCallbackResult v8::internal::Scavenger::RememberedSetEntryNeeded (CopyAndForwardResult result) [inline], [private]
Definition at line 162 of file scavenger-inl.h.
                                 {
  DCHECK_NE(CopyAndForwardResult::FAILURE, result);
  return result == CopyAndForwardResult::SUCCESS_YOUNG_GENERATION ? KEEP_SLOT
                                                                  : REMOVE_SLOT;
}
References DCHECK_NE, v8::internal::FAILURE, heap::base::KEEP_SLOT, heap::base::REMOVE_SLOT, v8::base::internal::result, and v8::internal::SUCCESS_YOUNG_GENERATION.
Referenced by EvacuateObjectDefault().
RememberPromotedEphemeron()
void v8::internal::Scavenger::RememberPromotedEphemeron (Tagged< EphemeronHashTable > table, int index) [private]
Definition at line 1166 of file scavenger.cc.
                                                     {
  auto indices = local_ephemeron_remembered_set_.insert(
      {table, std::unordered_set<int>()});
  indices.first->second.insert(index);
}
References v8::internal::index, and local_ephemeron_remembered_set_.
Referenced by v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitEphemeron().
ScavengeObject()
template<typename THeapObjectSlot >
SlotCallbackResult v8::internal::Scavenger::ScavengeObject (THeapObjectSlot p, Tagged< HeapObject > object) [inline], [private]
Definition at line 364 of file scavenger-inl.h.
                                                                        {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  DCHECK(Heap::InFromPage(object));
  // Check whether object was already successfully forwarded by the CAS in
  // MigrateObject. No memory ordering required because we only access the page
  // header of a relocated object. Page header initialization uses a memory
  // fence.
  MapWord first_word = object->map_word(kRelaxedLoad);
  // If the first word is a forwarding address, the object has already been
  // copied.
  if (first_word.IsForwardingAddress()) {
    Tagged<HeapObject> dest = first_word.ToForwardingAddress(object);
    DCHECK_IMPLIES(HeapLayout::IsSelfForwarded(object, first_word),
                   dest == object);
    if (dest == object) {
      MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
      return chunk->IsFlagSet(MemoryChunk::WILL_BE_PROMOTED) ||
                     chunk->IsLargePage()
                 ? REMOVE_SLOT
                 : KEEP_SLOT;
    }
    UpdateHeapObjectReferenceSlot(p, dest);
    SynchronizePageAccess(dest);
    // A forwarded object in new space is either in the second (to) semi space,
    // a large object, or a pinned object on a quarantined page.
    // Pinned objects have a self forwarding map word. However, since forwarding
    // addresses are set with relaxed atomics and before the object is actually
    // copied, it is unfortunately not safe to access `dest` to check whether it
    // is pinned or not.
    DCHECK_IMPLIES(HeapLayout::InYoungGeneration(dest),
                   Heap::InToPage(dest) || Heap::IsLargeObject(dest) ||
                       MemoryChunk::FromHeapObject(dest)->IsQuarantined());
    // This load forces us to have memory ordering for the map load above. We
    // need to have the page header properly initialized.
    MemoryChunk* chunk = MemoryChunk::FromHeapObject(dest);
    return !chunk->InYoungGeneration() || chunk->IsLargePage() ? REMOVE_SLOT
                                                               : KEEP_SLOT;
  }
  Tagged<Map> map = first_word.ToMap();
  // AllocationMementos are unrooted and shouldn't survive a scavenge
  DCHECK_NE(ReadOnlyRoots(heap()).allocation_memento_map(), map);
  // Call the slow part of scavenge object.
  return EvacuateObject(p, map, object);
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NE, EvacuateObject(), v8::internal::MemoryChunk::FromHeapObject(), heap(), v8::internal::Heap::InFromPage(), v8::internal::Heap::InToPage(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MapWord::IsForwardingAddress(), v8::internal::Heap::IsLargeObject(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::HeapLayout::IsSelfForwarded(), heap::base::KEEP_SLOT, v8::kRelaxedLoad, heap::base::REMOVE_SLOT, SynchronizePageAccess(), v8::internal::MapWord::ToForwardingAddress(), v8::internal::MapWord::ToMap(), v8::internal::UpdateHeapObjectReferenceSlot(), and v8::internal::MemoryChunk::WILL_BE_PROMOTED.
Referenced by CheckAndScavengeObject(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), and v8::internal::ScavengeVisitor::VisitHeapObjectImpl().
ScavengePage()
void v8::internal::Scavenger::ScavengePage (MutablePageMetadata * page)
Definition at line 1173 of file scavenger.cc.
                                                      {
  const bool record_old_to_shared_slots = heap_->isolate()->has_shared_space();
  MemoryChunk* chunk = page->Chunk();
  if (page->slot_set<OLD_TO_NEW, AccessMode::ATOMIC>() != nullptr) {
    RememberedSet<OLD_TO_NEW>::IterateAndTrackEmptyBuckets(
        page,
        [this, chunk, page, record_old_to_shared_slots](MaybeObjectSlot slot) {
          SlotCallbackResult result = CheckAndScavengeObject(heap_, slot);
          // A new space string might have been promoted into the shared heap
          // during GC.
          if (result == REMOVE_SLOT && record_old_to_shared_slots) {
            CheckOldToNewSlotForSharedUntyped(chunk, page, slot);
          }
          return result;
        },
        &local_empty_chunks_);
  }
  if (chunk->executable()) {
    std::vector<std::tuple<Tagged<HeapObject>, SlotType, Address>> slot_updates;
    // The code running write access to executable memory poses CFI attack
    // surface and needs to be kept to a minimum. So we do the the iteration in
    // two rounds. First we iterate the slots and scavenge objects and in the
    // second round with write access, we only perform the pointer updates.
    const auto typed_slot_count = RememberedSet<OLD_TO_NEW>::IterateTyped(
        page, [this, chunk, page, record_old_to_shared_slots, &slot_updates](
                  SlotType slot_type, Address slot_address) {
          Tagged<HeapObject> old_target =
              UpdateTypedSlotHelper::GetTargetObject(heap_, slot_type,
                                                     slot_address);
          Tagged<HeapObject> new_target = old_target;
          FullMaybeObjectSlot slot(&new_target);
          SlotCallbackResult result = CheckAndScavengeObject(heap(), slot);
          if (result == REMOVE_SLOT && record_old_to_shared_slots) {
            CheckOldToNewSlotForSharedTyped(chunk, page, slot_type,
                                            slot_address, *slot);
          }
          if (new_target != old_target) {
            slot_updates.emplace_back(new_target, slot_type, slot_address);
          }
          return result;
        });
    // Typed slots only exist in code objects. Since code is never young, it is
    // safe to release an empty typed slot set as no other scavenge thread will
    // attempt to promote to the page and write to the slot set.
    if (typed_slot_count == 0) {
      page->ReleaseTypedSlotSet(OLD_TO_NEW);
    }
    WritableJitPage jit_page = ThreadIsolation::LookupWritableJitPage(
        page->area_start(), page->area_size());
    for (auto& slot_update : slot_updates) {
      Tagged<HeapObject> new_target = std::get<0>(slot_update);
      SlotType slot_type = std::get<1>(slot_update);
      Address slot_address = std::get<2>(slot_update);
      WritableJitAllocation jit_allocation =
          jit_page.LookupAllocationContaining(slot_address);
      UpdateTypedSlotHelper::UpdateTypedSlot(
          jit_allocation, heap_, slot_type, slot_address,
          [new_target](FullMaybeObjectSlot slot) {
            slot.store(new_target);
            return KEEP_SLOT;
          });
    }
  } else {
    DCHECK_NULL(page->typed_slot_set<OLD_TO_NEW>());
  }
  if (page->slot_set<OLD_TO_NEW_BACKGROUND, AccessMode::ATOMIC>() != nullptr) {
    RememberedSet<OLD_TO_NEW_BACKGROUND>::IterateAndTrackEmptyBuckets(
        page,
        [this, chunk, page, record_old_to_shared_slots](MaybeObjectSlot slot) {
          SlotCallbackResult result = CheckAndScavengeObject(heap_, slot);
          // A new space string might have been promoted into the shared heap
          // during GC.
          if (result == REMOVE_SLOT && record_old_to_shared_slots) {
            CheckOldToNewSlotForSharedUntyped(chunk, page, slot);
          }
          return result;
        },
        &local_empty_chunks_);
  }
}
References v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::ATOMIC, CheckAndScavengeObject(), CheckOldToNewSlotForSharedTyped(), CheckOldToNewSlotForSharedUntyped(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_NULL, v8::internal::MemoryChunk::executable(), v8::internal::UpdateTypedSlotHelper::GetTargetObject(), v8::internal::Isolate::has_shared_space(), heap(), heap_, v8::internal::Heap::isolate(), v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets(), v8::internal::RememberedSet< type >::IterateTyped(), heap::base::KEEP_SLOT, local_empty_chunks_, v8::internal::WritableJitPage::LookupAllocationContaining(), v8::internal::ThreadIsolation::LookupWritableJitPage(), v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_NEW_BACKGROUND, v8::internal::MutablePageMetadata::ReleaseTypedSlotSet(), heap::base::REMOVE_SLOT, v8::base::internal::result, v8::internal::MutablePageMetadata::slot_set(), v8::internal::FullMaybeObjectSlot::store(), v8::internal::MutablePageMetadata::typed_slot_set(), and v8::internal::UpdateTypedSlotHelper::UpdateTypedSlot().
Referenced by v8::internal::ScavengerCollector::JobTask::ConcurrentScavengePages().
SemiSpaceCopyObject()
template<typename THeapObjectSlot >
CopyAndForwardResult v8::internal::Scavenger::SemiSpaceCopyObject (Tagged< Map > map, THeapObjectSlot slot, Tagged< HeapObject > object, int object_size, ObjectFields object_fields) [inline], [private]
Definition at line 81 of file scavenger-inl.h.
                                                 {
  static_assert(std::is_same_v<THeapObjectSlot, FullHeapObjectSlot> ||
                    std::is_same_v<THeapObjectSlot, HeapObjectSlot>,
                "Only FullHeapObjectSlot and HeapObjectSlot are expected here");
  DCHECK(heap()->AllowedToBeMigrated(map, object, NEW_SPACE));
  AllocationAlignment alignment = HeapObject::RequiredAlignment(NEW_SPACE, map);
  AllocationResult allocation =
      allocator_.Allocate(NEW_SPACE, object_size, alignment);
  Tagged<HeapObject> target;
  if (allocation.To(&target)) {
    DCHECK(heap()->marking_state()->IsUnmarked(target));
    const bool self_success =
        MigrateObject(map, object, target, object_size, kPromoteIntoLocalHeap);
    if (!self_success) {
      allocator_.FreeLast(NEW_SPACE, target, object_size);
      MapWord map_word = object->map_word(kRelaxedLoad);
      UpdateHeapObjectReferenceSlot(slot, map_word.ToForwardingAddress(object));
      SynchronizePageAccess(*slot);
      DCHECK(!Heap::InFromPage(*slot));
      return Heap::InToPage(*slot)
                 ? CopyAndForwardResult::SUCCESS_YOUNG_GENERATION
                 : CopyAndForwardResult::SUCCESS_OLD_GENERATION;
    }
    UpdateHeapObjectReferenceSlot(slot, target);
    if (object_fields == ObjectFields::kMaybePointers) {
      local_copied_list_.Push(target);
    }
    copied_size_ += object_size;
    return CopyAndForwardResult::SUCCESS_YOUNG_GENERATION;
  }
  return CopyAndForwardResult::FAILURE;
}
References v8::internal::EvacuationAllocator::Allocate(), allocator_, copied_size_, v8::internal::DCHECK(), v8::internal::FAILURE, v8::internal::EvacuationAllocator::FreeLast(), heap(), v8::internal::Heap::InFromPage(), v8::internal::Heap::InToPage(), v8::internal::kMaybePointers, kPromoteIntoLocalHeap, v8::kRelaxedLoad, local_copied_list_, MigrateObject(), v8::internal::NEW_SPACE, heap::base::Worklist< EntryType, MinSegmentSize >::Local::Push(), v8::internal::HeapObject::RequiredAlignment(), v8::internal::SUCCESS_OLD_GENERATION, v8::internal::SUCCESS_YOUNG_GENERATION, SynchronizePageAccess(), v8::internal::AllocationResult::To(), v8::internal::MapWord::ToForwardingAddress(), and v8::internal::UpdateHeapObjectReferenceSlot().
Referenced by EvacuateObjectDefault().
ShouldEagerlyProcessPromotedList()
bool v8::internal::Scavenger::ShouldEagerlyProcessPromotedList () const [inline], [private]
Definition at line 30 of file scavenger-inl.h.
                                                       {
  // Threshold when to prioritize processing of the promoted list. Right
  // now we only look into the regular object list.
  const int kProcessPromotedListThreshold = kPromotedListSegmentSize / 2;
  return local_promoted_list_.PushSegmentSize() >=
         kProcessPromotedListThreshold;
}
References kPromotedListSegmentSize, local_promoted_list_, and heap::base::Worklist< EntryType, MinSegmentSize >::Local::PushSegmentSize().
Referenced by Process().
SynchronizePageAccess()
void v8::internal::Scavenger::SynchronizePageAccess (Tagged< MaybeObject > object) const [inline], [private]
Definition at line 38 of file scavenger-inl.h.
                                                                      {
#ifdef THREAD_SANITIZER
  // Perform a dummy acquire load to tell TSAN that there is no data race
  // with page initialization.
  Tagged<HeapObject> heap_object;
  if (object.GetHeapObject(&heap_object)) {
    MemoryChunk::FromHeapObject(heap_object)->SynchronizedLoad();
  }
#endif
}
References v8::internal::MemoryChunk::FromHeapObject().
Referenced by EvacuateShortcutCandidate(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), PromoteObject(), ScavengeObject(), and SemiSpaceCopyObject().
VisitPinnedObjects()
void v8::internal::Scavenger::VisitPinnedObjects ()
Definition at line 1464 of file scavenger.cc.
                                   {
  ScavengeVisitor scavenge_visitor(this);
  ObjectAndMap object_and_map;
  while (local_pinned_list_.Pop(&object_and_map)) {
    DCHECK(HeapLayout::IsSelfForwarded(object_and_map.first));
    scavenge_visitor.Visit(object_and_map.second, object_and_map.first);
  }
}
References DCHECK, and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
Referenced by v8::internal::ScavengerCollector::JobTask::ProcessItems().
Friends And Related Function Documentation
IterateAndScavengePromotedObjectsVisitor
friend class IterateAndScavengePromotedObjectsVisitor [friend]
Definition at line 211 of file scavenger.h.
RootScavengeVisitor
friend class RootScavengeVisitor [friend]
Definition at line 212 of file scavenger.h.
ScavengeVisitor
friend class ScavengeVisitor [friend]
Definition at line 213 of file scavenger.h.
Member Data Documentation
allocator_
EvacuationAllocator v8::internal::Scavenger::allocator_ [private]
Definition at line 204 of file scavenger.h.
Referenced by PromoteObject(), and SemiSpaceCopyObject().
collector_
ScavengerCollector* const v8::internal::Scavenger::collector_ [private]
Definition at line 192 of file scavenger.h.
copied_size_
size_t v8::internal::Scavenger::copied_size_ {0} [private]
Definition at line 202 of file scavenger.h.
Referenced by bytes_copied(), and SemiSpaceCopyObject().
heap_
Heap* const v8::internal::Scavenger::heap_ [private]
Definition at line 193 of file scavenger.h.
Referenced by heap(), IterateAndScavengePromotedObject(), MigrateObject(), and ScavengePage().
is_logging_
const bool v8::internal::Scavenger::is_logging_ [private]
Definition at line 206 of file scavenger.h.
Referenced by MigrateObject().
kCopiedListSegmentSize
constexpr int v8::internal::Scavenger::kCopiedListSegmentSize = 256 [static], [constexpr]
Definition at line 44 of file scavenger.h.
kInterruptThreshold
const int v8::internal::Scavenger::kInterruptThreshold = 128 [static], [private]
Definition at line 99 of file scavenger.h.
Referenced by Process().
kPinnedListSegmentSize
constexpr int v8::internal::Scavenger::kPinnedListSegmentSize = 64 [static], [constexpr]
Definition at line 45 of file scavenger.h.
kPromotedListSegmentSize
constexpr int v8::internal::Scavenger::kPromotedListSegmentSize = 256 [static], [constexpr]
Definition at line 46 of file scavenger.h.
Referenced by ShouldEagerlyProcessPromotedList().
local_copied_list_
CopiedList::Local v8::internal::Scavenger::local_copied_list_ [private]
Definition at line 195 of file scavenger.h.
Referenced by Process(), and SemiSpaceCopyObject().
local_empty_chunks_
EmptyChunksList::Local v8::internal::Scavenger::local_empty_chunks_ [private]
Definition at line 194 of file scavenger.h.
Referenced by ScavengePage().
local_ephemeron_remembered_set_
EphemeronRememberedSet::TableMap v8::internal::Scavenger::local_ephemeron_remembered_set_ [private]
Definition at line 200 of file scavenger.h.
Referenced by RememberPromotedEphemeron().
local_ephemeron_table_list_
EphemeronRememberedSet::TableList::Local v8::internal::Scavenger::local_ephemeron_table_list_ [private]
Definition at line 198 of file scavenger.h.
local_pinned_list_
PinnedList::Local v8::internal::Scavenger::local_pinned_list_ [private]
Definition at line 196 of file scavenger.h.
local_pretenuring_feedback_
PretenuringHandler::PretenuringFeedbackMap v8::internal::Scavenger::local_pretenuring_feedback_ [private]
Definition at line 199 of file scavenger.h.
Referenced by MigrateObject().
local_promoted_list_
PromotedList::Local v8::internal::Scavenger::local_promoted_list_ [private]
Definition at line 197 of file scavenger.h.
Referenced by HandleLargeObject(), Process(), PromoteObject(), and ShouldEagerlyProcessPromotedList().
local_surviving_new_large_objects_
SurvivingNewLargeObjectsMap v8::internal::Scavenger::local_surviving_new_large_objects_ [private]
Definition at line 201 of file scavenger.h.
Referenced by HandleLargeObject().
mark_shared_heap_
const bool v8::internal::Scavenger::mark_shared_heap_ [private]
Definition at line 208 of file scavenger.h.
promoted_size_
size_t v8::internal::Scavenger::promoted_size_ {0} [private]
Definition at line 203 of file scavenger.h.
Referenced by bytes_promoted(), HandleLargeObject(), and PromoteObject().
shared_string_table_
const bool v8::internal::Scavenger::shared_string_table_ [private]
Definition at line 207 of file scavenger.h.
Referenced by EvacuateInPlaceInternalizableString().
shortcut_strings_
const bool v8::internal::Scavenger::shortcut_strings_ [private]
Definition at line 209 of file scavenger.h.
Referenced by EvacuateShortcutCandidate(), and EvacuateThinString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger.h
/mnt/V8SourceCode/src/heap/scavenger-inl.h
/mnt/V8SourceCode/src/heap/scavenger.cc