v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope Class Reference
Public Member Functions
BackgroundCompileScope (std::weak_ptr< NativeModule > native_module)
NativeModule * native_module () const
CompilationStateImpl * compilation_state () const
bool cancelled () const
Private Attributes
std::shared_ptr< NativeModule > native_module_
Detailed Description
Definition at line 85 of file module-compiler.cc.
Constructor & Destructor Documentation
BackgroundCompileScope()
v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::BackgroundCompileScope (std::weak_ptr< NativeModule > native_module) [inline], [explicit]
Definition at line 87 of file module-compiler.cc.
      : native_module_(native_module.lock()) {}
Member Function Documentation
cancelled()
bool v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::cancelled () const
Definition at line 879 of file module-compiler.cc.
                                             {
  return native_module_ == nullptr ||
         Impl(native_module_->compilation_state())->cancelled();
}
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::cancelled(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::GetMaxConcurrency().
compilation_state()
CompilationStateImpl * v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::compilation_state () const [inline]
Definition at line 841 of file module-compiler.cc.
                                                                      {
  DCHECK(native_module_);
  return Impl(native_module_->compilation_state());
}
References v8::internal::DCHECK(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileJob::GetMaxConcurrency().
native_module()
NativeModule* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::native_module () const [inline]
Definition at line 90 of file module-compiler.cc.
                                      {
    DCHECK(native_module_);
    return native_module_.get();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ExecuteCompilationUnits().
Member Data Documentation
native_module_
std::shared_ptr<NativeModule> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::BackgroundCompileScope::native_module_ [private]
Definition at line 100 of file module-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc