v8::internal::compiler::X64OperandConverter Class Reference
Public Member Functions
X64OperandConverter (CodeGenerator *gen, Instruction *instr)
Immediate InputImmediate (size_t index)
Operand InputOperand (size_t index, int extra=0)
Operand OutputOperand ()
Immediate ToImmediate (InstructionOperand *operand)
Operand ToOperand (InstructionOperand *op, int extra=0)
Operand SlotToOperand (int slot_index, int extra=0)
Operand MemoryOperand (size_t *offset)
Operand MemoryOperand (size_t first_input=0)
Static Public Member Functions
static size_t NextOffset (size_t *offset)
static ScaleFactor ScaleFor (AddressingMode one, AddressingMode mode)
Additional Inherited Members
Detailed Description
Definition at line 128 of file code-generator-x64.cc.
Constructor & Destructor Documentation
X64OperandConverter()
v8::internal::compiler::X64OperandConverter::X64OperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 130 of file code-generator-x64.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
InputImmediate()
Immediate v8::internal::compiler::X64OperandConverter::InputImmediate (size_t index) [inline]
Definition at line 133 of file code-generator-x64.cc.
                                         {
    return ToImmediate(instr_->InputAt(index));
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToImmediate().
InputOperand()
Operand v8::internal::compiler::X64OperandConverter::InputOperand (size_t index, int extra = 0) [inline]
Definition at line 137 of file code-generator-x64.cc.
                                                    {
    return ToOperand(instr_->InputAt(index), extra);
  }
References v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, and ToOperand().
MemoryOperand() [1/2]
Operand v8::internal::compiler::X64OperandConverter::MemoryOperand (size_t * offset) [inline]
Definition at line 188 of file code-generator-x64.cc.
                                        {
    AddressingMode mode = AddressingModeField::decode(instr_->opcode());
    switch (mode) {
      case kMode_MR: {
        Register base = InputRegister(NextOffset(offset));
        int32_t disp = 0;
        return Operand(base, disp);
      }
      case kMode_MRI: {
        Register base = InputRegister(NextOffset(offset));
        int32_t disp = InputInt32(NextOffset(offset));
        return Operand(base, disp);
      }
      case kMode_MR1:
      case kMode_MR2:
      case kMode_MR4:
      case kMode_MR8: {
        Register base = InputRegister(NextOffset(offset));
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_MR1, mode);
        int32_t disp = 0;
        return Operand(base, index, scale, disp);
      }
      case kMode_MR1I:
      case kMode_MR2I:
      case kMode_MR4I:
      case kMode_MR8I: {
        Register base = InputRegister(NextOffset(offset));
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_MR1I, mode);
        int32_t disp = InputInt32(NextOffset(offset));
        return Operand(base, index, scale, disp);
      }
      case kMode_M1: {
        Register base = InputRegister(NextOffset(offset));
        int32_t disp = 0;
        return Operand(base, disp);
      }
      case kMode_M2:
        UNREACHABLE(); // Should use kModeMR with more compact encoding instead
      case kMode_M4:
      case kMode_M8: {
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_M1, mode);
        int32_t disp = 0;
        return Operand(index, scale, disp);
      }
      case kMode_M1I:
      case kMode_M2I:
      case kMode_M4I:
      case kMode_M8I: {
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = ScaleFor(kMode_M1I, mode);
        int32_t disp = InputInt32(NextOffset(offset));
        return Operand(index, scale, disp);
      }
      case kMode_Root: {
        Register base = kRootRegister;
        int32_t disp = InputInt32(NextOffset(offset));
        return Operand(base, disp);
      }
      case kMode_MCR: {
        Register base = kPtrComprCageBaseRegister;
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = static_cast<ScaleFactor>(0);
        int32_t disp = 0;
        return Operand(base, index, scale, disp);
      }
      case kMode_MCRI: {
        Register base = kPtrComprCageBaseRegister;
        Register index = InputRegister(NextOffset(offset));
        ScaleFactor scale = static_cast<ScaleFactor>(0);
        int32_t disp = InputInt32(NextOffset(offset));
        return Operand(base, index, scale, disp);
      }
      case kMode_None:
        UNREACHABLE();
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kPtrComprCageBaseRegister, v8::internal::kRootRegister, mode(), NextOffset(), v8::internal::compiler::Instruction::opcode(), ScaleFor(), and v8::internal::UNREACHABLE().
Referenced by MemoryOperand().
MemoryOperand() [2/2]
Operand v8::internal::compiler::X64OperandConverter::MemoryOperand (size_t first_input = 0) [inline]
Definition at line 269 of file code-generator-x64.cc.
                                                {
    return MemoryOperand(&first_input);
  }
References MemoryOperand().
NextOffset()
static size_t v8::internal::compiler::X64OperandConverter::NextOffset (size_t * offset) [inline], [static]
Definition at line 172 of file code-generator-x64.cc.
                                           {
    size_t i = *offset;
    (*offset)++;
    return i;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by MemoryOperand().
OutputOperand()
Operand v8::internal::compiler::X64OperandConverter::OutputOperand () [inline]
Definition at line 141 of file code-generator-x64.cc.
{ return ToOperand(instr_->Output()); }
References v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::Instruction::Output(), and ToOperand().
ScaleFor()
static ScaleFactor v8::internal::compiler::X64OperandConverter::ScaleFor (AddressingMode one, AddressingMode mode) [inline], [static]
Definition at line 178 of file code-generator-x64.cc.
                                                                       {
    static_assert(0 == static_cast<int>(times_1));
    static_assert(1 == static_cast<int>(times_2));
    static_assert(2 == static_cast<int>(times_4));
    static_assert(3 == static_cast<int>(times_8));
    int scale = static_cast<int>(mode - one);
    DCHECK(scale >= 0 && scale < 4);
    return static_cast<ScaleFactor>(scale);
  }
References v8::internal::DCHECK(), mode(), one, v8::internal::times_1, v8::internal::times_2, v8::internal::times_4, and v8::internal::times_8.
Referenced by MemoryOperand().
SlotToOperand()
Operand v8::internal::compiler::X64OperandConverter::SlotToOperand (int slot_index, int extra = 0) [inline]
Definition at line 166 of file code-generator-x64.cc.
                                                       {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot_index);
    return Operand(offset.from_stack_pointer() ? rsp : rbp,
                   offset.offset() + extra);
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToOperand().
ToImmediate()
Immediate v8::internal::compiler::X64OperandConverter::ToImmediate (InstructionOperand * operand) [inline]
Definition at line 143 of file code-generator-x64.cc.
                                                     {
    Constant constant = ToConstant(operand);
    if (constant.type() == Constant::kCompressedHeapObject) {
      CHECK(COMPRESS_POINTERS_BOOL);
      CHECK(V8_STATIC_ROOTS_BOOL || !gen_->isolate()->bootstrapper());
      RootIndex root_index;
      CHECK(gen_->isolate()->roots_table().IsRootHandle(constant.ToHeapObject(),
                                                        &root_index));
      return Immediate(
          MacroAssemblerBase::ReadOnlyRootPtr(root_index, gen_->isolate()));
    }
    if (constant.type() == Constant::kFloat64) {
      DCHECK_EQ(0, constant.ToFloat64().AsUint64());
      return Immediate(0);
    }
    return Immediate(constant.ToInt32(), constant.rmode());
  }
References v8::base::Double::AsUint64(), v8::internal::Isolate::bootstrapper(), CHECK, COMPRESS_POINTERS_BOOL, DCHECK_EQ, v8::internal::compiler::InstructionOperandConverter::gen_, v8::internal::compiler::CodeGenerator::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kFloat64, v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::compiler::Constant::rmode(), v8::internal::Isolate::roots_table(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::type(), and V8_STATIC_ROOTS_BOOL.
Referenced by InputImmediate().
ToOperand()
Operand v8::internal::compiler::X64OperandConverter::ToOperand (InstructionOperand * op, int extra = 0) [inline]
Definition at line 161 of file code-generator-x64.cc.
                                                           {
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToOperand(AllocatedOperand::cast(op)->index(), extra);
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToOperand().
Referenced by InputOperand(), and OutputOperand().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/x64/code-generator-x64.cc