v8::internal::compiler::GlobalAccessFeedback Class Reference
#include <processed-feedback.h>
Public Member Functions
GlobalAccessFeedback (PropertyCellRef cell, FeedbackSlotKind slot_kind)
GlobalAccessFeedback (ContextRef script_context, int slot_index, bool immutable, FeedbackSlotKind slot_kind)
GlobalAccessFeedback (FeedbackSlotKind slot_kind)
bool IsMegamorphic () const
bool IsPropertyCell () const
PropertyCellRef property_cell () const
bool IsScriptContextSlot () const
ContextRef script_context () const
int slot_index () const
bool immutable () const
OptionalObjectRef GetConstantHint (JSHeapBroker *broker) const
Private Attributes
OptionalObjectRef const cell_or_context_
int const index_and_immutable_
Additional Inherited Members
Detailed Description
Definition at line 78 of file processed-feedback.h.
Constructor & Destructor Documentation
GlobalAccessFeedback() [1/3]
v8::internal::compiler::GlobalAccessFeedback::GlobalAccessFeedback (PropertyCellRef cell, FeedbackSlotKind slot_kind)
Definition at line 252 of file js-heap-broker.cc.
    : ProcessedFeedback(kGlobalAccess, slot_kind),
      cell_or_context_(cell),
      index_and_immutable_(0 /* doesn't matter */) {
  DCHECK(IsGlobalICKind(slot_kind));
}
References v8::internal::DCHECK(), v8::internal::IsGlobalICKind(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
GlobalAccessFeedback() [2/3]
v8::internal::compiler::GlobalAccessFeedback::GlobalAccessFeedback (ContextRef script_context, int slot_index, bool immutable, FeedbackSlotKind slot_kind)
Definition at line 266 of file js-heap-broker.cc.
    : ProcessedFeedback(kGlobalAccess, slot_kind),
      cell_or_context_(script_context),
      index_and_immutable_(FeedbackNexus::SlotIndexBits::encode(slot_index) |
                           FeedbackNexus::ImmutabilityBit::encode(immutable)) {
  DCHECK_EQ(this->slot_index(), slot_index);
  DCHECK_EQ(this->immutable(), immutable);
  DCHECK(IsGlobalICKind(slot_kind));
}
References v8::internal::DCHECK(), DCHECK_EQ, immutable(), v8::internal::IsGlobalICKind(), slot_index(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
GlobalAccessFeedback() [3/3]
v8::internal::compiler::GlobalAccessFeedback::GlobalAccessFeedback (FeedbackSlotKind slot_kind) [explicit]
Definition at line 260 of file js-heap-broker.cc.
    : ProcessedFeedback(kGlobalAccess, slot_kind),
      index_and_immutable_(0 /* doesn't matter */) {
  DCHECK(IsGlobalICKind(slot_kind));
}
References v8::internal::DCHECK(), v8::internal::IsGlobalICKind(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
Member Function Documentation
GetConstantHint()
OptionalObjectRef v8::internal::compiler::GlobalAccessFeedback::GetConstantHint (JSHeapBroker * broker) const
Definition at line 304 of file js-heap-broker.cc.
                                {
  if (IsPropertyCell()) {
    bool cell_cached = property_cell().Cache(broker);
    CHECK(cell_cached); // Can't fail on the main thread.
    return property_cell().value(broker);
  } else if (IsScriptContextSlot() && immutable()) {
    return script_context().get(broker, slot_index());
  } else {
    return std::nullopt;
  }
}
References broker(), v8::internal::compiler::PropertyCellRef::Cache(), CHECK, v8::internal::compiler::ContextRef::get(), immutable(), IsPropertyCell(), IsScriptContextSlot(), property_cell(), script_context(), slot_index(), and v8::internal::compiler::PropertyCellRef::value().
immutable()
bool v8::internal::compiler::GlobalAccessFeedback::immutable () const
Definition at line 299 of file js-heap-broker.cc.
                                           {
  DCHECK(IsScriptContextSlot());
  return FeedbackNexus::ImmutabilityBit::decode(index_and_immutable_);
}
References v8::internal::DCHECK(), index_and_immutable_, and IsScriptContextSlot().
Referenced by GetConstantHint(), GlobalAccessFeedback(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextConstantLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextStore().
IsMegamorphic()
bool v8::internal::compiler::GlobalAccessFeedback::IsMegamorphic () const
Definition at line 278 of file js-heap-broker.cc.
                                               {
  return !cell_or_context_.has_value();
}
References cell_or_context_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalStore().
IsPropertyCell()
bool v8::internal::compiler::GlobalAccessFeedback::IsPropertyCell () const
Definition at line 281 of file js-heap-broker.cc.
                                                {
  return cell_or_context_.has_value() && cell_or_context_->IsPropertyCell();
}
References cell_or_context_.
Referenced by GetConstantHint(), property_cell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalStore(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
IsScriptContextSlot()
bool v8::internal::compiler::GlobalAccessFeedback::IsScriptContextSlot () const
Definition at line 284 of file js-heap-broker.cc.
                                                     {
  return cell_or_context_.has_value() && cell_or_context_->IsContext();
}
References cell_or_context_.
Referenced by GetConstantHint(), immutable(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), script_context(), slot_index(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildGlobalStore(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextConstantLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextStore().
property_cell()
PropertyCellRef v8::internal::compiler::GlobalAccessFeedback::property_cell () const
Definition at line 287 of file js-heap-broker.cc.
                                                          {
  CHECK(IsPropertyCell());
  return cell_or_context_->AsPropertyCell();
}
References cell_or_context_, CHECK, and IsPropertyCell().
Referenced by GetConstantHint(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildPropertyCellStore().
script_context()
ContextRef v8::internal::compiler::GlobalAccessFeedback::script_context () const
Definition at line 291 of file js-heap-broker.cc.
                                                      {
  CHECK(IsScriptContextSlot());
  return cell_or_context_->AsContext();
}
References cell_or_context_, CHECK, and IsScriptContextSlot().
Referenced by GetConstantHint(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextConstantLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextStore().
slot_index()
int v8::internal::compiler::GlobalAccessFeedback::slot_index () const
Definition at line 295 of file js-heap-broker.cc.
                                           {
  DCHECK(IsScriptContextSlot());
  return FeedbackNexus::SlotIndexBits::decode(index_and_immutable_);
}
References v8::internal::DCHECK(), index_and_immutable_, and IsScriptContextSlot().
Referenced by GetConstantHint(), GlobalAccessFeedback(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSStoreGlobal(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextConstantLoad(), v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextLoad(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildScriptContextStore().
Member Data Documentation
cell_or_context_
OptionalObjectRef const v8::internal::compiler::GlobalAccessFeedback::cell_or_context_ [private]
Definition at line 98 of file processed-feedback.h.
Referenced by IsMegamorphic(), IsPropertyCell(), IsScriptContextSlot(), property_cell(), and script_context().
index_and_immutable_
int const v8::internal::compiler::GlobalAccessFeedback::index_and_immutable_ [private]
Definition at line 99 of file processed-feedback.h.
Referenced by immutable(), and slot_index().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/processed-feedback.h
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc