v8::internal::maglev::BuiltinContinuationDeoptFrame Class Reference
#include <maglev-ir.h>
Public Member Functions
BuiltinContinuationDeoptFrame (Builtin builtin_id, base::Vector< ValueNode * > parameters, ValueNode *context, compiler::OptionalJSFunctionRef maybe_js_target, DeoptFrame *parent)
const Builtin & builtin_id () const
base::Vector< ValueNode * > parameters () const
ValueNode *& context ()
ValueNode * context () const
bool is_javascript () const
compiler::JSFunctionRef javascript_target () const
Private Member Functions
BuiltinContinuationFrameData & data ()
const BuiltinContinuationFrameData & data () const
Additional Inherited Members
Detailed Description
Definition at line 1714 of file maglev-ir.h.
Constructor & Destructor Documentation
BuiltinContinuationDeoptFrame()
v8::internal::maglev::BuiltinContinuationDeoptFrame::BuiltinContinuationDeoptFrame (Builtin builtin_id, base::Vector< ValueNode * > parameters, ValueNode * context, compiler::OptionalJSFunctionRef maybe_js_target, DeoptFrame * parent) [inline]
Definition at line 1716 of file maglev-ir.h.
      : DeoptFrame(BuiltinContinuationFrameData{builtin_id, parameters, context,
                                                maybe_js_target},
                   parent) {}
Member Function Documentation
builtin_id()
const Builtin& v8::internal::maglev::BuiltinContinuationDeoptFrame::builtin_id () const [inline]
Definition at line 1725 of file maglev-ir.h.
{ return data().builtin_id; }
References v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::builtin_id, and data().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize().
context() [1/2]
ValueNode*& v8::internal::maglev::BuiltinContinuationDeoptFrame::context () [inline]
Definition at line 1727 of file maglev-ir.h.
{ return data().context; }
References v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::context, and data().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
context() [2/2]
ValueNode* v8::internal::maglev::BuiltinContinuationDeoptFrame::context () const [inline]
Definition at line 1728 of file maglev-ir.h.
{ return data().context; }
References v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::context, and data().
data() [1/2]
BuiltinContinuationFrameData& v8::internal::maglev::BuiltinContinuationDeoptFrame::data () [inline], [private]
Definition at line 1735 of file maglev-ir.h.
                                       {
    return data_.get<BuiltinContinuationFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
Referenced by builtin_id(), context(), is_javascript(), javascript_target(), and parameters().
data() [2/2]
const BuiltinContinuationFrameData& v8::internal::maglev::BuiltinContinuationDeoptFrame::data () const [inline], [private]
Definition at line 1738 of file maglev-ir.h.
                                                   {
    return data_.get<BuiltinContinuationFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
is_javascript()
bool v8::internal::maglev::BuiltinContinuationDeoptFrame::is_javascript () const [inline]
Definition at line 1729 of file maglev-ir.h.
{ return data().maybe_js_target.has_value(); }
References data(), and v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::maybe_js_target.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::DeoptFrame::IsJsFrame().
javascript_target()
compiler::JSFunctionRef v8::internal::maglev::BuiltinContinuationDeoptFrame::javascript_target () const [inline]
Definition at line 1730 of file maglev-ir.h.
                                                  {
    return data().maybe_js_target.value();
  }
References data(), and v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::maybe_js_target.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
parameters()
base::Vector<ValueNode*> v8::internal::maglev::BuiltinContinuationDeoptFrame::parameters () const [inline]
Definition at line 1726 of file maglev-ir.h.
{ return data().parameters; }
References data(), and v8::internal::maglev::DeoptFrame::BuiltinContinuationFrameData::parameters.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h