v8::internal::CaseClauseSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
CaseClauseSourceRanges (const SourceRange &body_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
Private Attributes
SourceRange body_range_
Detailed Description
Definition at line 128 of file ast-source-ranges.h.
Constructor & Destructor Documentation
CaseClauseSourceRanges()
v8::internal::CaseClauseSourceRanges::CaseClauseSourceRanges (const SourceRange & body_range) [inline], [explicit]
Definition at line 130 of file ast-source-ranges.h.
      : body_range_(body_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::CaseClauseSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 133 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    return body_range_;
  }
References body_range_, v8::internal::DCHECK(), and HasRange().
HasRange()
bool v8::internal::CaseClauseSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 138 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kBody;
  }
References v8::internal::kBody.
Referenced by GetRange().
Member Data Documentation
body_range_
SourceRange v8::internal::CaseClauseSourceRanges::body_range_ [private]
Definition at line 143 of file ast-source-ranges.h.
Referenced by GetRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h