v8::PrepareForDebugInterfaceExecutionScope Class Reference
#include <api-inl.h>
Public Member Functions
PrepareForDebugInterfaceExecutionScope (i::Isolate *i_isolate, Local< Context > context)
template<typename T >
Local< T > Escape (Local< T > value)
template<typename T >
MaybeLocal< T > EscapeMaybe (MaybeLocal< T > value)
Private Attributes
InternalEscapableScope handle_scope_
CallDepthScope< false > call_depth_scope_
i::VMState< v8::OTHER > vm_state_
Detailed Description
Definition at line 384 of file api-inl.h.
Constructor & Destructor Documentation
PrepareForDebugInterfaceExecutionScope()
v8::PrepareForDebugInterfaceExecutionScope::PrepareForDebugInterfaceExecutionScope (i::Isolate * i_isolate, Local< Context > context) [inline]
Definition at line 386 of file api-inl.h.
      : handle_scope_{i_isolate},
        call_depth_scope_{i_isolate, context},
        vm_state_{i_isolate} {
    DCHECK(!i_isolate->is_execution_terminating());
    DCHECK_EQ(i_isolate, i::Isolate::TryGetCurrent());
  }
References DCHECK, DCHECK_EQ, and v8::internal::Isolate::is_execution_terminating().
Member Function Documentation
Escape()
template<typename T >
Local<T> v8::PrepareForDebugInterfaceExecutionScope::Escape (Local< T > value) [inline]
Definition at line 396 of file api-inl.h.
                                            {
    return handle_scope_.Escape(value);
  }
References v8::internal::value.
Referenced by v8::debug::CompileInspectorScript().
EscapeMaybe()
template<typename T >
MaybeLocal<T> v8::PrepareForDebugInterfaceExecutionScope::EscapeMaybe (MaybeLocal< T > value) [inline]
Definition at line 401 of file api-inl.h.
                                                           {
    return handle_scope_.EscapeMaybe(value);
  }
References v8::internal::value.
Referenced by v8::debug::CallFunctionOn(), and v8::debug::EvaluateGlobal().
Member Data Documentation
call_depth_scope_
CallDepthScope<false> v8::PrepareForDebugInterfaceExecutionScope::call_depth_scope_ [private]
Definition at line 407 of file api-inl.h.
handle_scope_
InternalEscapableScope v8::PrepareForDebugInterfaceExecutionScope::handle_scope_ [private]
Definition at line 406 of file api-inl.h.
vm_state_
i::VMState<v8::OTHER> v8::PrepareForDebugInterfaceExecutionScope::vm_state_ [private]
Definition at line 408 of file api-inl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/api/api-inl.h