v8::internal::maglev::InlinedArgumentsDeoptFrame Class Reference
#include <maglev-ir.h>
Public Member Functions
InlinedArgumentsDeoptFrame (const MaglevCompilationUnit &unit, BytecodeOffset bytecode_position, ValueNode *closure, base::Vector< ValueNode * > arguments, DeoptFrame *parent)
const MaglevCompilationUnit & unit () const
BytecodeOffset bytecode_position () const
ValueNode *& closure ()
ValueNode * closure () const
base::Vector< ValueNode * > arguments () const
Private Member Functions
InlinedArgumentsFrameData & data ()
const InlinedArgumentsFrameData & data () const
Additional Inherited Members
Detailed Description
Definition at line 1635 of file maglev-ir.h.
Constructor & Destructor Documentation
InlinedArgumentsDeoptFrame()
v8::internal::maglev::InlinedArgumentsDeoptFrame::InlinedArgumentsDeoptFrame (const MaglevCompilationUnit & unit, BytecodeOffset bytecode_position, ValueNode * closure, base::Vector< ValueNode * > arguments, DeoptFrame * parent) [inline]
Definition at line 1637 of file maglev-ir.h.
      : DeoptFrame(InlinedArgumentsFrameData{unit, bytecode_position, closure,
                                             arguments},
                   parent) {}
Member Function Documentation
arguments()
base::Vector<ValueNode*> v8::internal::maglev::InlinedArgumentsDeoptFrame::arguments () const [inline]
Definition at line 1650 of file maglev-ir.h.
{ return data().arguments; }
References v8::internal::maglev::DeoptFrame::InlinedArgumentsFrameData::arguments, and data().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), and v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize().
bytecode_position()
BytecodeOffset v8::internal::maglev::InlinedArgumentsDeoptFrame::bytecode_position () const [inline]
Definition at line 1647 of file maglev-ir.h.
{ return data().bytecode_position; }
References v8::internal::maglev::DeoptFrame::InlinedArgumentsFrameData::bytecode_position, and data().
closure() [1/2]
ValueNode*& v8::internal::maglev::InlinedArgumentsDeoptFrame::closure () [inline]
Definition at line 1648 of file maglev-ir.h.
{ return data().closure; }
References v8::internal::maglev::DeoptFrame::InlinedArgumentsFrameData::closure, and data().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame().
closure() [2/2]
ValueNode* v8::internal::maglev::InlinedArgumentsDeoptFrame::closure () const [inline]
Definition at line 1649 of file maglev-ir.h.
{ return data().closure; }
References v8::internal::maglev::DeoptFrame::InlinedArgumentsFrameData::closure, and data().
data() [1/2]
InlinedArgumentsFrameData& v8::internal::maglev::InlinedArgumentsDeoptFrame::data () [inline], [private]
Definition at line 1653 of file maglev-ir.h.
                                    {
    return data_.get<InlinedArgumentsFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
Referenced by arguments(), bytecode_position(), closure(), and unit().
data() [2/2]
const InlinedArgumentsFrameData& v8::internal::maglev::InlinedArgumentsDeoptFrame::data () const [inline], [private]
Definition at line 1656 of file maglev-ir.h.
                                                {
    return data_.get<InlinedArgumentsFrameData>();
  }
References v8::internal::maglev::DeoptFrame::data_, and v8::base::DiscriminatedUnion< TagEnum, Ts >::get().
unit()
const MaglevCompilationUnit& v8::internal::maglev::InlinedArgumentsDeoptFrame::unit () const [inline]
Definition at line 1646 of file maglev-ir.h.
{ return data().unit; }
References data(), and v8::internal::maglev::DeoptFrame::InlinedArgumentsFrameData::unit.
Referenced by v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), and v8::internal::maglev::DeoptFrame::GetCompilationUnit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h