v8::internal::compiler::CsaLoadElimination Class Reference
#include <csa-load-elimination.h>
Classes
struct AbstractState
struct FieldInfo
class HalfState
Public Member Functions
CsaLoadElimination (Editor *editor, JSGraph *jsgraph, Zone *zone)
~CsaLoadElimination () final=default
CsaLoadElimination (const CsaLoadElimination &)=delete
CsaLoadElimination & operator= (const CsaLoadElimination &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceLoadFromObject (Node *node, ObjectAccess const &access)
Reduction ReduceStoreToObject (Node *node, ObjectAccess const &access)
Reduction ReduceEffectPhi (Node *node)
Reduction ReduceStart (Node *node)
Reduction ReduceCall (Node *node)
Reduction ReduceOtherNode (Node *node)
Reduction UpdateState (Node *node, AbstractState const *state)
Reduction PropagateInputState (Node *node)
AbstractState const * ComputeLoopState (Node *node, AbstractState const *state) const
Node * TruncateAndExtend (Node *node, MachineRepresentation from, MachineType to)
Reduction AssertUnreachable (Node *node)
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
Isolate * isolate () const
TFGraph * graph () const
JSGraph * jsgraph () const
Zone * zone () const
AbstractState const * empty_state () const
Private Attributes
AbstractState const empty_state_
NodeAuxData< AbstractState const * > node_states_
JSGraph *const jsgraph_
Zone * zone_
Detailed Description
Definition at line 26 of file csa-load-elimination.h.
Constructor & Destructor Documentation
CsaLoadElimination() [1/2]
v8::internal::compiler::CsaLoadElimination::CsaLoadElimination (Editor * editor, JSGraph * jsgraph, Zone * zone) [inline]
Definition at line 29 of file csa-load-elimination.h.
      : AdvancedReducer(editor),
        empty_state_(zone),
        node_states_(jsgraph->graph()->NodeCount(), zone),
        jsgraph_(jsgraph),
        zone_(zone) {}
 CsaLoadElimination()
v8::internal::compiler::CsaLoadElimination::~CsaLoadElimination () [final], [default]
CsaLoadElimination() [2/2]
v8::internal::compiler::CsaLoadElimination::CsaLoadElimination (const CsaLoadElimination &) [delete]
Member Function Documentation
AssertUnreachable()
Reduction v8::internal::compiler::CsaLoadElimination::AssertUnreachable (Node * node) [private]
Definition at line 335 of file csa-load-elimination.cc.
                                                          {
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* unreachable =
      graph()->NewNode(jsgraph()->common()->Unreachable(), effect, control);
  return Replace(unreachable);
}
References common(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), jsgraph(), v8::internal::compiler::TFGraph::NewNode(), and v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace().
Referenced by ReduceStoreToObject().
common()
CommonOperatorBuilder * v8::internal::compiler::CsaLoadElimination::common () const [private]
Definition at line 608 of file csa-load-elimination.cc.
                                                        {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by AssertUnreachable(), and ReduceLoadFromObject().
ComputeLoopState()
CsaLoadElimination::AbstractState const * v8::internal::compiler::CsaLoadElimination::ComputeLoopState (Node * node, AbstractState const * state) const [private]
Definition at line 523 of file csa-load-elimination.cc.
                                                  {
  DCHECK_EQ(node->opcode(), IrOpcode::kEffectPhi);
  std::queue<Node*> queue;
  std::unordered_set<Node*> visited;
  visited.insert(node);
  for (int i = 1; i < node->InputCount() - 1; ++i) {
    queue.push(node->InputAt(i));
  }
  while (!queue.empty()) {
    Node* const current = queue.front();
    queue.pop();
    if (visited.insert(current).second) {
      if (current->opcode() == IrOpcode::kStoreToObject) {
        Node* object = NodeProperties::GetValueInput(current, 0);
        Node* offset = NodeProperties::GetValueInput(current, 1);
        MachineRepresentation repr =
            ObjectAccessOf(current->op()).machine_type.representation();
        const HalfState* new_mutable_state =
            state->mutable_state.KillField(object, offset, repr);
        state = zone()->New<AbstractState>(*new_mutable_state,
                                           state->immutable_state);
      } else if (current->opcode() == IrOpcode::kInitializeImmutableInObject) {
#if DEBUG
        // We are not allowed to reset an immutable (object, offset) pair.
        Node* object = NodeProperties::GetValueInput(current, 0);
        Node* offset = NodeProperties::GetValueInput(current, 1);
        CHECK(state->immutable_state.Lookup(object, offset).IsEmpty());
#endif
      } else if (!current->op()->HasProperty(Operator::kNoWrite)) {
        return zone()->New<AbstractState>(HalfState(zone()),
                                          state->immutable_state);
      }
      for (int i = 0; i < current->op()->EffectInputCount(); ++i) {
        queue.push(NodeProperties::GetEffectInput(current, i));
      }
    }
  }
  return state;
}
References CHECK, DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::CsaLoadElimination::AbstractState::immutable_state, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::CsaLoadElimination::FieldInfo::IsEmpty(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::CsaLoadElimination::HalfState::Lookup(), v8::internal::compiler::ObjectAccess::machine_type, v8::internal::compiler::CsaLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), v8::internal::compiler::ObjectAccessOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::MachineType::representation(), and zone().
Referenced by ReduceEffectPhi().
empty_state()
AbstractState const* v8::internal::compiler::CsaLoadElimination::empty_state () const [inline], [private]
Definition at line 173 of file csa-load-elimination.h.
{ return &empty_state_; }
Referenced by ReduceStart().
graph()
TFGraph * v8::internal::compiler::CsaLoadElimination::graph () const [private]
Definition at line 616 of file csa-load-elimination.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by AssertUnreachable(), ReduceLoadFromObject(), and TruncateAndExtend().
isolate()
Isolate * v8::internal::compiler::CsaLoadElimination::isolate () const [private]
Definition at line 618 of file csa-load-elimination.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::CsaLoadElimination::jsgraph () const [inline], [private]
Definition at line 171 of file csa-load-elimination.h.
{ return jsgraph_; }
Referenced by AssertUnreachable(), common(), graph(), isolate(), machine(), ReduceLoadFromObject(), and TruncateAndExtend().
machine()
MachineOperatorBuilder * v8::internal::compiler::CsaLoadElimination::machine () const [private]
Definition at line 612 of file csa-load-elimination.cc.
                                                          {
  return jsgraph()->machine();
}
References jsgraph(), and v8::internal::compiler::MachineGraph::machine().
Referenced by TruncateAndExtend().
operator=()
CsaLoadElimination& v8::internal::compiler::CsaLoadElimination::operator= (const CsaLoadElimination &) [delete]
PropagateInputState()
Reduction v8::internal::compiler::CsaLoadElimination::PropagateInputState (Node * node) [private]
Definition at line 516 of file csa-load-elimination.cc.
                                                            {
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  return UpdateState(node, state);
}
References v8::internal::compiler::NodeProperties::GetEffectInput(), node_states_, and UpdateState().
Referenced by Reduce(), and ReduceCall().
Reduce()
Reduction v8::internal::compiler::CsaLoadElimination::Reduce (Node * node) [final]
Definition at line 16 of file csa-load-elimination.cc.
                                               {
  if (v8_flags.trace_turbo_load_elimination) {
    if (node->op()->EffectInputCount() > 0) {
      PrintF(" visit #%d:%s", node->id(), node->op()->mnemonic());
      if (node->op()->ValueInputCount() > 0) {
        PrintF("(");
        for (int i = 0; i < node->op()->ValueInputCount(); ++i) {
          if (i > 0) PrintF(", ");
          Node* const value = NodeProperties::GetValueInput(node, i);
          PrintF("#%d:%s", value->id(), value->op()->mnemonic());
        }
        PrintF(")");
      }
      PrintF("\n");
      for (int i = 0; i < node->op()->EffectInputCount(); ++i) {
        Node* const effect = NodeProperties::GetEffectInput(node, i);
        if (AbstractState const* const state = node_states_.Get(effect)) {
          PrintF(" state[%i]: #%d:%s\n", i, effect->id(),
                 effect->op()->mnemonic());
          state->mutable_state.Print();
          state->immutable_state.Print();
        } else {
          PrintF(" no state[%i]: #%d:%s\n", i, effect->id(),
                 effect->op()->mnemonic());
        }
      }
    }
  }
  switch (node->opcode()) {
    case IrOpcode::kLoadFromObject:
    case IrOpcode::kLoadImmutableFromObject:
      return ReduceLoadFromObject(node, ObjectAccessOf(node->op()));
    case IrOpcode::kStoreToObject:
    case IrOpcode::kInitializeImmutableInObject:
      return ReduceStoreToObject(node, ObjectAccessOf(node->op()));
    case IrOpcode::kDebugBreak:
    case IrOpcode::kAbortCSADcheck:
      // Avoid changing optimizations in the presence of debug instructions.
      return PropagateInputState(node);
    case IrOpcode::kCall:
      return ReduceCall(node);
    case IrOpcode::kEffectPhi:
      return ReduceEffectPhi(node);
    case IrOpcode::kDead:
      return NoChange();
    case IrOpcode::kStart:
      return ReduceStart(node);
    default:
      return ReduceOtherNode(node);
  }
  UNREACHABLE();
}
References v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::kStart, v8::internal::compiler::Operator::mnemonic(), node_states_, v8::internal::compiler::ObjectAccessOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::PrintF(), PropagateInputState(), ReduceCall(), ReduceEffectPhi(), ReduceLoadFromObject(), ReduceOtherNode(), ReduceStart(), ReduceStoreToObject(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, v8::internal::value, and v8::internal::compiler::Operator::ValueInputCount().
ReduceCall()
Reduction v8::internal::compiler::CsaLoadElimination::ReduceCall (Node * node) [private]
Definition at line 471 of file csa-load-elimination.cc.
                                                   {
  Node* value = NodeProperties::GetValueInput(node, 0);
  ExternalReferenceMatcher m(value);
  if (m.Is(ExternalReference::check_object_type())) {
    return PropagateInputState(node);
  }
  return ReduceOtherNode(node);
}
References v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::ExternalReferenceMatcher::Is(), PropagateInputState(), ReduceOtherNode(), and v8::internal::value.
Referenced by Reduce().
ReduceEffectPhi()
Reduction v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi (Node * node) [private]
Definition at line 434 of file csa-load-elimination.cc.
                                                        {
  Node* const effect0 = NodeProperties::GetEffectInput(node, 0);
  Node* const control = NodeProperties::GetControlInput(node);
  AbstractState const* state0 = node_states_.Get(effect0);
  if (state0 == nullptr) return NoChange();
  if (control->opcode() == IrOpcode::kLoop) {
    // Here we rely on having only reducible loops:
    // The loop entry edge always dominates the header, so we can just take
    // the state from the first input, and compute the loop state based on it.
    AbstractState const* state = ComputeLoopState(node, state0);
    return UpdateState(node, state);
  }
  DCHECK_EQ(IrOpcode::kMerge, control->opcode());
  // Shortcut for the case when we do not know anything about some input.
  int const input_count = node->op()->EffectInputCount();
  for (int i = 1; i < input_count; ++i) {
    Node* const effect = NodeProperties::GetEffectInput(node, i);
    if (node_states_.Get(effect) == nullptr) return NoChange();
  }
  // Make a copy of the first input's state and intersect it with the state
  // from other inputs.
  // TODO(manoskouk): Consider computing phis for at least a subset of the
  // state.
  AbstractState* state = zone()->New<AbstractState>(*state0);
  for (int i = 1; i < input_count; ++i) {
    Node* const input = NodeProperties::GetEffectInput(node, i);
    state->IntersectWith(node_states_.Get(input));
  }
  return UpdateState(node, state);
}
References ComputeLoopState(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::CsaLoadElimination::AbstractState::IntersectWith(), v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), UpdateState(), and zone().
Referenced by Reduce().
ReduceLoadFromObject()
Reduction v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject (Node * node, ObjectAccess const & access) [private]
Definition at line 343 of file csa-load-elimination.cc.
                                                                               {
  DCHECK(node->opcode() == IrOpcode::kLoadFromObject ||
         node->opcode() == IrOpcode::kLoadImmutableFromObject);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* offset = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  bool is_mutable = node->opcode() == IrOpcode::kLoadFromObject;
  // We can only find the field in the wrong half-state in unreachable code.
  if (!(is_mutable ? &state->immutable_state : &state->mutable_state)
           ->Lookup(object, offset)
           .IsEmpty()) {
    Node* control = NodeProperties::GetControlInput(node);
    Node* unreachable =
        graph()->NewNode(jsgraph()->common()->Unreachable(), effect, control);
    auto rep = ObjectAccessOf(node->op()).machine_type.representation();
    Node* dead_value =
        graph()->NewNode(jsgraph()->common()->DeadValue(rep), unreachable);
    ReplaceWithValue(node, dead_value, unreachable, control);
    node->Kill();
    return Replace(dead_value);
  }
  HalfState const* half_state =
      is_mutable ? &state->mutable_state : &state->immutable_state;
  MachineRepresentation representation = access.machine_type.representation();
  FieldInfo lookup_result = half_state->Lookup(object, offset);
  if (!lookup_result.IsEmpty()) {
    // Make sure we don't reuse values that were recorded with a different
    // representation or resurrect dead {replacement} nodes.
    MachineRepresentation from = lookup_result.representation;
    if (Helpers::Subsumes(from, representation) &&
        !lookup_result.value->IsDead()) {
      Node* replacement =
          TruncateAndExtend(lookup_result.value, from, access.machine_type);
      ReplaceWithValue(node, replacement, effect);
      // This might have opened an opportunity for escape analysis to eliminate
      // the object altogether.
      Revisit(object);
      return Replace(replacement);
    }
  }
  half_state = half_state->AddField(object, offset, node, representation);
  AbstractState const* new_state =
      is_mutable
          ? zone()->New<AbstractState>(*half_state, state->immutable_state)
          : zone()->New<AbstractState>(state->mutable_state, *half_state);
  return UpdateState(node, new_state);
}
References v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), common(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::CsaLoadElimination::AbstractState::immutable_state, v8::internal::compiler::Node::IsDead(), v8::internal::compiler::CsaLoadElimination::FieldInfo::IsEmpty(), jsgraph(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::CsaLoadElimination::HalfState::Lookup(), v8::internal::compiler::ObjectAccess::machine_type, v8::internal::compiler::CsaLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), v8::internal::compiler::TFGraph::NewNode(), node_states_, v8::internal::compiler::ObjectAccessOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::MachineType::representation(), v8::internal::compiler::CsaLoadElimination::FieldInfo::representation, v8::internal::compiler::CsaLoadEliminationHelpers::Subsumes(), TruncateAndExtend(), UpdateState(), v8::internal::compiler::CsaLoadElimination::FieldInfo::value, and zone().
Referenced by Reduce().
ReduceOtherNode()
Reduction v8::internal::compiler::CsaLoadElimination::ReduceOtherNode (Node * node) [private]
Definition at line 480 of file csa-load-elimination.cc.
                                                        {
  if (node->op()->EffectInputCount() == 1 &&
      node->op()->EffectOutputCount() == 1) {
    Node* const effect = NodeProperties::GetEffectInput(node);
    AbstractState const* state = node_states_.Get(effect);
    // If we do not know anything about the predecessor, do not propagate just
    // yet because we will have to recompute anyway once we compute the
    // predecessor.
    if (state == nullptr) return NoChange();
    // If this {node} has some uncontrolled side effects, set its state to
    // the immutable half-state of its input state, otherwise to its input
    // state.
    return UpdateState(
        node, node->op()->HasProperty(Operator::kNoWrite)
                  ? state
                  : zone()->New<AbstractState>(HalfState(zone()),
                                               state->immutable_state));
  }
  DCHECK_EQ(0, node->op()->EffectOutputCount());
  return NoChange();
}
References DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::CsaLoadElimination::AbstractState::immutable_state, v8::internal::compiler::Operator::kNoWrite, node_states_, v8::internal::compiler::Node::op(), UpdateState(), and zone().
Referenced by Reduce(), and ReduceCall().
reducer_name()
const char* v8::internal::compiler::CsaLoadElimination::reducer_name () const [inline], [override]
Definition at line 39 of file csa-load-elimination.h.
{ return "CsaLoadElimination"; }
ReduceStart()
Reduction v8::internal::compiler::CsaLoadElimination::ReduceStart (Node * node) [private]
Definition at line 467 of file csa-load-elimination.cc.
                                                    {
  return UpdateState(node, empty_state());
}
References empty_state(), and UpdateState().
Referenced by Reduce().
ReduceStoreToObject()
Reduction v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject (Node * node, ObjectAccess const & access) [private]
Definition at line 397 of file csa-load-elimination.cc.
                                                                              {
  DCHECK(node->opcode() == IrOpcode::kStoreToObject ||
         node->opcode() == IrOpcode::kInitializeImmutableInObject);
  Node* object = NodeProperties::GetValueInput(node, 0);
  Node* offset = NodeProperties::GetValueInput(node, 1);
  Node* value = NodeProperties::GetValueInput(node, 2);
  Node* effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  MachineRepresentation repr = access.machine_type.representation();
  if (node->opcode() == IrOpcode::kStoreToObject) {
    // We can only find the field in the wrong half-state in unreachable code.
    if (!(state->immutable_state.Lookup(object, offset).IsEmpty())) {
      return AssertUnreachable(node);
    }
    HalfState const* mutable_state =
        state->mutable_state.KillField(object, offset, repr);
    mutable_state = mutable_state->AddField(object, offset, value, repr);
    AbstractState const* new_state =
        zone()->New<AbstractState>(*mutable_state, state->immutable_state);
    return UpdateState(node, new_state);
  } else {
    // We can only find the field in the wrong half-state in unreachable code.
    if (!(state->mutable_state.Lookup(object, offset).IsEmpty())) {
      return AssertUnreachable(node);
    }
    // We should not initialize the same immutable field twice.
    DCHECK(state->immutable_state.Lookup(object, offset).IsEmpty());
    HalfState const* immutable_state =
        state->immutable_state.AddField(object, offset, value, repr);
    AbstractState const* new_state =
        zone()->New<AbstractState>(state->mutable_state, *immutable_state);
    return UpdateState(node, new_state);
  }
}
References v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), AssertUnreachable(), v8::internal::DCHECK(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::CsaLoadElimination::AbstractState::immutable_state, v8::internal::compiler::CsaLoadElimination::FieldInfo::IsEmpty(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::Lookup(), v8::internal::compiler::ObjectAccess::machine_type, v8::internal::compiler::CsaLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::opcode(), v8::internal::MachineType::representation(), UpdateState(), v8::internal::value, and zone().
Referenced by Reduce().
TruncateAndExtend()
Node * v8::internal::compiler::CsaLoadElimination::TruncateAndExtend (Node * node, MachineRepresentation from, MachineType to) [private]
Definition at line 564 of file csa-load-elimination.cc.
                                                            {
  DCHECK(Helpers::Subsumes(from, to.representation()));
  DCHECK_GE(ElementSizeInBytes(from), ElementSizeInBytes(to.representation()));
  if (to == MachineType::Int8() || to == MachineType::Int16()) {
    // 1st case: We want to eliminate a signed 8/16-bit load using the value
    // from a previous subsuming load or store. Since that value might be
    // outside 8/16-bit range, we first truncate it accordingly. Then we
    // sign-extend the result to 32-bit.
    DCHECK_EQ(to.semantic(), MachineSemantic::kInt32);
    if (from == MachineRepresentation::kWord64) {
      node = graph()->NewNode(machine()->TruncateInt64ToInt32(), node);
    }
    int shift = 32 - 8 * ElementSizeInBytes(to.representation());
    return graph()->NewNode(machine()->Word32Sar(),
                            graph()->NewNode(machine()->Word32Shl(), node,
                                             jsgraph()->Int32Constant(shift)),
                            jsgraph()->Int32Constant(shift));
  } else if (to == MachineType::Uint8() || to == MachineType::Uint16()) {
    // 2nd case: We want to eliminate an unsigned 8/16-bit load using the value
    // from a previous subsuming load or store. Since that value might be
    // outside 8/16-bit range, we first truncate it accordingly.
    if (from == MachineRepresentation::kWord64) {
      node = graph()->NewNode(machine()->TruncateInt64ToInt32(), node);
    }
    int mask = (1 << 8 * ElementSizeInBytes(to.representation())) - 1;
    return graph()->NewNode(machine()->Word32And(), node,
                            jsgraph()->Int32Constant(mask));
  } else if (from == MachineRepresentation::kWord64 &&
             to.representation() == MachineRepresentation::kWord32) {
    // 3rd case: Truncate 64-bits into 32-bits.
    return graph()->NewNode(machine()->TruncateInt64ToInt32(), node);
  } else {
    // 4th case: No need for truncation.
    DCHECK((from == to.representation() &&
            (from == MachineRepresentation::kWord32 ||
             from == MachineRepresentation::kWord64 || !IsIntegral(from))) ||
           (IsAnyTagged(from) && IsAnyTagged(to.representation())));
    return node;
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::ElementSizeInBytes(), graph(), v8::internal::MachineType::Int16(), v8::internal::MachineType::Int8(), v8::internal::IsAnyTagged(), v8::internal::IsIntegral(), jsgraph(), v8::internal::kInt32, v8::internal::kWord32, v8::internal::kWord64, machine(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::MachineType::representation(), v8::internal::MachineType::semantic(), v8::internal::compiler::CsaLoadEliminationHelpers::Subsumes(), v8::internal::MachineType::Uint16(), and v8::internal::MachineType::Uint8().
Referenced by ReduceLoadFromObject().
UpdateState()
Reduction v8::internal::compiler::CsaLoadElimination::UpdateState (Node * node, AbstractState const * state) [private]
Definition at line 502 of file csa-load-elimination.cc.
                                                                      {
  AbstractState const* original = node_states_.Get(node);
  // Only signal that the {node} has Changed, if the information about {state}
  // has changed wrt. the {original}.
  if (state != original) {
    if (original == nullptr || !state->Equals(original)) {
      node_states_.Set(node, state);
      return Changed(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::CsaLoadElimination::AbstractState::Equals(), and node_states_.
Referenced by PropagateInputState(), ReduceEffectPhi(), ReduceLoadFromObject(), ReduceOtherNode(), ReduceStart(), and ReduceStoreToObject().
zone()
Zone* v8::internal::compiler::CsaLoadElimination::zone () const [inline], [private]
Definition at line 172 of file csa-load-elimination.h.
{ return zone_; }
Referenced by ComputeLoopState(), v8::internal::compiler::CsaLoadElimination::HalfState::KillOffset(), ReduceEffectPhi(), ReduceLoadFromObject(), ReduceOtherNode(), and ReduceStoreToObject().
Member Data Documentation
empty_state_
AbstractState const v8::internal::compiler::CsaLoadElimination::empty_state_ [private]
Definition at line 175 of file csa-load-elimination.h.
jsgraph_
JSGraph* const v8::internal::compiler::CsaLoadElimination::jsgraph_ [private]
Definition at line 177 of file csa-load-elimination.h.
node_states_
NodeAuxData<AbstractState const*> v8::internal::compiler::CsaLoadElimination::node_states_ [private]
Definition at line 176 of file csa-load-elimination.h.
Referenced by PropagateInputState(), Reduce(), ReduceEffectPhi(), ReduceLoadFromObject(), ReduceOtherNode(), ReduceStoreToObject(), and UpdateState().
zone_
Zone* v8::internal::compiler::CsaLoadElimination::zone_ [private]
Definition at line 178 of file csa-load-elimination.h.
Referenced by v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), and v8::internal::compiler::CsaLoadElimination::HalfState::KillField().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/csa-load-elimination.h
/mnt/V8SourceCode/src/compiler/csa-load-elimination.cc