v8::internal::Uri Class Reference
#include <uri.h>
Static Public Member Functions
static MaybeDirectHandle< String > DecodeUri (Isolate *isolate, DirectHandle< String > uri)
static MaybeDirectHandle< String > DecodeUriComponent (Isolate *isolate, DirectHandle< String > component)
static MaybeDirectHandle< String > EncodeUri (Isolate *isolate, DirectHandle< String > uri)
static MaybeDirectHandle< String > EncodeUriComponent (Isolate *isolate, DirectHandle< String > component)
static MaybeDirectHandle< String > Escape (Isolate *isolate, Handle< String > string)
static MaybeDirectHandle< String > Unescape (Isolate *isolate, Handle< String > string)
Static Private Member Functions
static MaybeDirectHandle< String > Decode (Isolate *isolate, DirectHandle< String > uri, bool is_uri)
static MaybeDirectHandle< String > Encode (Isolate *isolate, DirectHandle< String > uri, bool is_uri)
Detailed Description
Definition at line 14 of file uri.h.
Member Function Documentation
Decode()
MaybeDirectHandle< String > v8::internal::Uri::Decode (Isolate * isolate, DirectHandle< String > uri, bool is_uri) [static], [private]
Definition at line 177 of file uri.cc.
                                                                             {
  uri = String::Flatten(isolate, uri);
  std::vector<uint8_t> one_byte_buffer;
  std::vector<base::uc16> two_byte_buffer;
  if (!IntoOneAndTwoByte(uri, is_uri, &one_byte_buffer, &two_byte_buffer)) {
    THROW_NEW_ERROR(isolate, NewURIError());
  }
  if (two_byte_buffer.empty()) {
    return isolate->factory()->NewStringFromOneByte(base::Vector<const uint8_t>(
        one_byte_buffer.data(), static_cast<int>(one_byte_buffer.size())));
  }
  DirectHandle<SeqTwoByteString> result;
  int result_length =
      static_cast<int>(one_byte_buffer.size() + two_byte_buffer.size());
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, result, isolate->factory()->NewRawTwoByteString(result_length));
  DisallowGarbageCollection no_gc;
  base::uc16* chars = result->GetChars(no_gc);
  if (!one_byte_buffer.empty()) {
    CopyChars(chars, one_byte_buffer.data(), one_byte_buffer.size());
    chars += one_byte_buffer.size();
  }
  if (!two_byte_buffer.empty()) {
    CopyChars(chars, two_byte_buffer.data(), two_byte_buffer.size());
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::CopyChars(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{uri.cc}::IntoOneAndTwoByte(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and THROW_NEW_ERROR.
Referenced by DecodeUri(), and DecodeUriComponent().
DecodeUri()
static MaybeDirectHandle<String> v8::internal::Uri::DecodeUri (Isolate * isolate, DirectHandle< String > uri) [inline], [static]
Definition at line 17 of file uri.h.
                                                                       {
    return Decode(isolate, uri, true);
  }
References Decode().
Referenced by v8::internal::BUILTIN().
DecodeUriComponent()
static MaybeDirectHandle<String> v8::internal::Uri::DecodeUriComponent (Isolate * isolate, DirectHandle< String > component) [inline], [static]
Definition at line 23 of file uri.h.
                                                        {
    return Decode(isolate, component, false);
  }
References Decode().
Referenced by v8::internal::BUILTIN().
Encode()
MaybeDirectHandle< String > v8::internal::Uri::Encode (Isolate * isolate, DirectHandle< String > uri, bool is_uri) [static], [private]
Definition at line 280 of file uri.cc.
                                                                             {
  uri = String::Flatten(isolate, uri);
  int uri_length = uri->length();
  std::vector<uint8_t> buffer;
  buffer.reserve(uri_length);
  bool throw_error = false;
  {
    DisallowGarbageCollection no_gc;
    String::FlatContent uri_content = uri->GetFlatContent(no_gc);
    for (int k = 0; k < uri_length; k++) {
      base::uc16 cc1 = uri_content.Get(k);
      if (unibrow::Utf16::IsLeadSurrogate(cc1)) {
        k++;
        if (k < uri_length) {
          base::uc16 cc2 = uri->Get(k);
          if (unibrow::Utf16::IsTrailSurrogate(cc2)) {
            EncodePair(cc1, cc2, &buffer);
            continue;
          }
        }
      } else if (!unibrow::Utf16::IsTrailSurrogate(cc1)) {
        if (IsUnescapePredicateInUriComponent(cc1) ||
            (is_uri && IsUriSeparator(cc1))) {
          buffer.push_back(cc1);
        } else {
          EncodeSingle(cc1, &buffer);
        }
        continue;
      }
      // String::FlatContent DCHECKs its contents did not change during its
      // lifetime. Throwing the error inside the loop may cause GC and move the
      // string contents.
      throw_error = true;
      break;
    }
  }
  if (throw_error) THROW_NEW_ERROR(isolate, NewURIError());
  if (buffer.size() > v8::String::kMaxLength) {
    THROW_NEW_ERROR(isolate, NewInvalidStringLengthError());
  }
  return isolate->factory()->NewStringFromOneByte(base::VectorOf(buffer));
}
References v8::internal::anonymous_namespace{uri.cc}::EncodePair(), v8::internal::anonymous_namespace{uri.cc}::EncodeSingle(), v8::internal::Isolate::factory(), v8::internal::String::FlatContent::Get(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), v8::internal::anonymous_namespace{uri.cc}::IsUnescapePredicateInUriComponent(), v8::internal::anonymous_namespace{uri.cc}::IsUriSeparator(), v8::String::kMaxLength, v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, THROW_NEW_ERROR, and v8::base::VectorOf().
Referenced by EncodeUri(), and EncodeUriComponent().
EncodeUri()
static MaybeDirectHandle<String> v8::internal::Uri::EncodeUri (Isolate * isolate, DirectHandle< String > uri) [inline], [static]
Definition at line 29 of file uri.h.
                                                                       {
    return Encode(isolate, uri, true);
  }
References Encode().
Referenced by v8::internal::BUILTIN().
EncodeUriComponent()
static MaybeDirectHandle<String> v8::internal::Uri::EncodeUriComponent (Isolate * isolate, DirectHandle< String > component) [inline], [static]
Definition at line 35 of file uri.h.
                                                        {
    return Encode(isolate, component, false);
  }
References Encode().
Referenced by v8::internal::BUILTIN().
Escape()
MaybeDirectHandle< String > v8::internal::Uri::Escape (Isolate * isolate, Handle< String > string) [static]
Definition at line 510 of file uri.cc.
                                                                             {
  string = String::Flatten(isolate, string);
  return String::IsOneByteRepresentationUnderneath(*string)
             ? EscapePrivate<uint8_t>(isolate, string)
             : EscapePrivate<base::uc16>(isolate, string);
}
References v8::internal::String::IsOneByteRepresentationUnderneath().
Referenced by v8::internal::BUILTIN().
Unescape()
MaybeDirectHandle< String > v8::internal::Uri::Unescape (Isolate * isolate, Handle< String > string) [static]
Definition at line 517 of file uri.cc.
                                                               {
  string = String::Flatten(isolate, string);
  return String::IsOneByteRepresentationUnderneath(*string)
             ? UnescapePrivate<uint8_t>(isolate, string)
             : UnescapePrivate<base::uc16>(isolate, string);
}
References v8::internal::String::IsOneByteRepresentationUnderneath().
Referenced by v8::internal::BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/uri.h
/mnt/V8SourceCode/src/strings/uri.cc