v8::internal::compiler::InstructionScheduler::StressSchedulerQueue Class Reference
Public Member Functions
StressSchedulerQueue (InstructionScheduler *scheduler)
ScheduleGraphNode * PopBestCandidate (int cycle)
Private Member Functions
base::RandomNumberGenerator * random_number_generator ()
Additional Inherited Members
Detailed Description
Definition at line 136 of file instruction-scheduler.h.
Constructor & Destructor Documentation
StressSchedulerQueue()
v8::internal::compiler::InstructionScheduler::StressSchedulerQueue::StressSchedulerQueue (InstructionScheduler * scheduler) [inline], [explicit]
Definition at line 138 of file instruction-scheduler.h.
        : SchedulingQueueBase(scheduler) {}
Member Function Documentation
PopBestCandidate()
InstructionScheduler::ScheduleGraphNode * v8::internal::compiler::InstructionScheduler::StressSchedulerQueue::PopBestCandidate (int cycle)
Definition at line 51 of file instruction-scheduler.cc.
                                                                    {
  DCHECK(!IsEmpty());
  // Choose a random element from the ready list.
  auto candidate = nodes_.begin();
  std::advance(candidate, random_number_generator()->NextInt(
                              static_cast<int>(nodes_.size())));
  ScheduleGraphNode* result = *candidate;
  nodes_.erase(candidate);
  return result;
}
References v8::internal::DCHECK(), v8::internal::compiler::InstructionScheduler::random_number_generator(), and v8::base::internal::result.
random_number_generator()
base::RandomNumberGenerator* v8::internal::compiler::InstructionScheduler::StressSchedulerQueue::random_number_generator () [inline], [private]
Definition at line 144 of file instruction-scheduler.h.
                                                         {
      return scheduler_->random_number_generator();
    }
References v8::internal::compiler::InstructionScheduler::random_number_generator(), and v8::internal::compiler::InstructionScheduler::SchedulingQueueBase::scheduler_.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction-scheduler.h
/mnt/V8SourceCode/src/compiler/backend/instruction-scheduler.cc