v8::debug::Script Class Reference
Native wrapper around v8::internal::Script object.
#include <debug-interface.h>
Public Types
enum class GetSourceOffsetMode { kStrict
, kClamp
 }
Public Member Functions
ScriptOriginOptions OriginOptions () const
bool WasCompiled () const
bool IsEmbedded () const
int Id () const
int StartLine () const
int StartColumn () const
int EndLine () const
int EndColumn () const
MaybeLocal< String > Name () const
MaybeLocal< String > SourceURL () const
MaybeLocal< String > SourceMappingURL () const
MaybeLocal< String > DebugId () const
MaybeLocal< String > GetSha256Hash () const
Maybe< int > ContextId () const
Local< ScriptSource > Source () const
bool IsModule () const
bool GetPossibleBreakpoints (const debug::Location &start, const debug::Location &end, bool restrict_to_function, std::vector< debug::BreakLocation > *locations) const
Maybe< int > GetSourceOffset (const debug::Location &location, GetSourceOffsetMode mode=GetSourceOffsetMode::kStrict) const
v8::debug::Location GetSourceLocation (int offset) const
bool SetScriptSource (v8::Local< v8::String > newSource, bool preview, bool allow_top_frame_live_editing, LiveEditResult *result) const
bool SetBreakpoint (v8::Local< v8::String > condition, debug::Location *location, BreakpointId *id) const
bool SetInstrumentationBreakpoint (BreakpointId *id) const
Detailed Description
Native wrapper around v8::internal::Script object.
Definition at line 206 of file debug-interface.h.
Member Enumeration Documentation
GetSourceOffsetMode
enum v8::debug::Script::GetSourceOffsetMode [strong]
Enumerator
kStrict
kClamp
Definition at line 228 of file debug-interface.h.
{ kStrict, kClamp };
Member Function Documentation
ContextId()
Maybe< int > v8::debug::Script::ContextId () const
Definition at line 576 of file debug-interface.cc.
                                   {
  auto script = Utils::OpenDirectHandle(this);
  i::Tagged<i::Object> value = script->context_data();
  if (IsSmi(value)) return Just(i::Smi::ToInt(value));
  return {};
}
References v8::internal::IsSmi(), v8::Just(), v8::Utils::OpenDirectHandle(), v8::internal::script, v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8_inspector::V8DebuggerScript::Initialize().
DebugId()
MaybeLocal< String > v8::debug::Script::DebugId () const
Definition at line 560 of file debug-interface.cc.
                                         {
  auto script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> value(script->debug_id(), isolate);
  if (!IsString(*value)) return MaybeLocal<String>();
  return Utils::ToLocal(i::Cast<i::String>(value));
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::value.
Referenced by v8_inspector::V8DebuggerScript::buildId().
EndColumn()
int v8::debug::Script::EndColumn () const
Definition at line 518 of file debug-interface.cc.
                            {
  i::DirectHandle<i::Script> script = Utils::OpenDirectHandle(this);
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == i::Script::Type::kWasm) {
    return script->wasm_native_module()->wire_bytes().length();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  if (!IsString(script->source())) {
    return script->column_offset();
  }
  i::Isolate* isolate = i::Isolate::Current();
  i::HandleScope scope(isolate);
  i::Script::PositionInfo info;
  i::Script::GetPositionInfo(
      script, i::Cast<i::String>(script->source())->length(), &info);
  return info.column;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetPositionInfo(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
Referenced by v8_inspector::V8DebuggerScript::Initialize().
EndLine()
int v8::debug::Script::EndLine () const
Definition at line 502 of file debug-interface.cc.
                          {
  i::DirectHandle<i::Script> script = Utils::OpenDirectHandle(this);
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == i::Script::Type::kWasm) return 0;
#endif // V8_ENABLE_WEBASSEMBLY
  if (!IsString(script->source())) {
    return script->line_offset();
  }
  i::Isolate* isolate = i::Isolate::Current();
  i::HandleScope scope(isolate);
  i::Script::PositionInfo info;
  i::Script::GetPositionInfo(
      script, i::Cast<i::String>(script->source())->length(), &info);
  return info.line;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetPositionInfo(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
Referenced by v8_inspector::V8DebuggerScript::Initialize().
GetPossibleBreakpoints()
bool v8::debug::Script::GetPossibleBreakpoints (const debug::Location & start, const debug::Location & end, bool restrict_to_function, std::vector< debug::BreakLocation > * locations) const
Definition at line 620 of file debug-interface.cc.
                                               {
  CHECK(!start.IsEmpty());
  i::Handle<i::Script> script = Utils::OpenHandle(this);
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == i::Script::Type::kWasm) {
    i::wasm::NativeModule* native_module = script->wasm_native_module();
    return i::WasmScript::GetPossibleBreakpoints(native_module, start, end,
                                                 locations);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  i::Isolate* isolate = i::Isolate::Current();
  int start_offset, end_offset;
  if (!GetSourceOffset(start, GetSourceOffsetMode::kClamp).To(&start_offset)) {
    return false;
  }
  if (end.IsEmpty()) {
    end_offset = std::numeric_limits<int>::max();
  } else if (!GetSourceOffset(end, GetSourceOffsetMode::kClamp)
                  .To(&end_offset)) {
    return false;
  }
  if (start_offset >= end_offset) return true;
  std::vector<i::BreakLocation> v8_locations;
  if (!isolate->debug()->GetPossibleBreakpoints(
          script, start_offset, end_offset, restrict_to_function,
          &v8_locations)) {
    return false;
  }
  std::sort(v8_locations.begin(), v8_locations.end(), CompareBreakLocation);
  for (const auto& v8_location : v8_locations) {
    Location location = GetSourceLocation(v8_location.position());
    locations->emplace_back(location.GetLineNumber(),
                            location.GetColumnNumber(), v8_location.type());
  }
  return true;
}
References CHECK, v8::debug::anonymous_namespace{debug-interface.cc}::CompareBreakLocation(), v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::internal::compiler::end(), v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::internal::Debug::GetPossibleBreakpoints(), v8::internal::WasmScript::GetPossibleBreakpoints(), GetSourceLocation(), GetSourceOffset(), v8::debug::Location::IsEmpty(), kClamp, v8::Utils::OpenHandle(), v8::internal::script, and v8::base::sort().
Referenced by v8_inspector::V8DebuggerScript::getPossibleBreakpoints().
GetSha256Hash()
MaybeLocal< String > v8::debug::Script::GetSha256Hash () const
Definition at line 568 of file debug-interface.cc.
                                               {
  i::DirectHandle<i::Script> script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::String> value =
      i::Script::GetScriptHash(isolate, script, /* forceForInspector: */ true);
  return Utils::ToLocal(value);
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetScriptHash(), v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::value.
Referenced by v8_inspector::V8DebuggerScript::Initialize().
GetSourceLocation()
Location v8::debug::Script::GetSourceLocation (int offset) const
Definition at line 724 of file debug-interface.cc.
                                                   {
  i::DirectHandle<i::Script> script = Utils::OpenDirectHandle(this);
  i::Script::PositionInfo info;
  i::Script::GetPositionInfo(script, offset, &info);
  if (script->HasSourceURLComment()) {
    // Line/column number for inline <script>s with sourceURL annotation
    // are supposed to be related to the <script> tag, otherwise they
    // are relative to the parent file. Keep this in sync with the logic
    // in GetSourceOffset() above.
    info.line -= script->line_offset();
    if (info.line == 0) info.column -= script->column_offset();
  }
  return Location(info.line, info.column);
}
References v8::internal::Script::GetPositionInfo(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
Referenced by GetPossibleBreakpoints(), and SetBreakpoint().
GetSourceOffset()
Maybe< int > v8::debug::Script::GetSourceOffset (const debug::Location & location, GetSourceOffsetMode mode = GetSourceOffsetMode::kStrict) const
Definition at line 663 of file debug-interface.cc.
                                                                   {
  i::DirectHandle<i::Script> script = Utils::OpenDirectHandle(this);
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == i::Script::Type::kWasm) {
    return location.GetLineNumber() == 0 ? Just(location.GetColumnNumber())
                                         : Nothing<int>();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  int line = location.GetLineNumber();
  int column = location.GetColumnNumber();
  if (!script->HasSourceURLComment()) {
    // Line/column number for inline <script>s with sourceURL annotation
    // are supposed to be related to the <script> tag, otherwise they
    // are relative to the parent file. Keep this in sync with the logic
    // in GetSourceLocation() below.
    line -= script->line_offset();
    if (line == 0) column -= script->column_offset();
  }
  i::Isolate* isolate = i::Isolate::Current();
  i::Script::InitLineEnds(isolate, script);
  auto line_ends =
      i::Cast<i::FixedArray>(i::direct_handle(script->line_ends(), isolate));
  if (line < 0) {
    if (mode == GetSourceOffsetMode::kClamp) {
      return Just(0);
    }
    return {};
  }
  if (line >= line_ends->length()) {
    if (mode == GetSourceOffsetMode::kClamp) {
      return Just(GetSmiValue(line_ends, line_ends->length() - 1));
    }
    return {};
  }
  if (column < 0) {
    if (mode != GetSourceOffsetMode::kClamp) {
      return {};
    }
    column = 0;
  }
  int offset = column;
  if (line > 0) {
    int prev_line_end_offset = GetSmiValue(line_ends, line - 1);
    offset += prev_line_end_offset + 1;
  }
  int line_end_offset = GetSmiValue(line_ends, line);
  if (offset > line_end_offset) {
    // Be permissive with columns that don't exist,
    // as long as they are clearly within the range
    // of the script.
    if (line < line_ends->length() - 1 || mode == GetSourceOffsetMode::kClamp) {
      return Just(line_end_offset);
    }
    return {};
  }
  return Just(offset);
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::debug::anonymous_namespace{debug-interface.cc}::GetSmiValue(), v8::internal::Script::InitLineEnds(), v8::Just(), kClamp, v8::internal::length, mode(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
Referenced by GetPossibleBreakpoints(), and SetBreakpoint().
Id()
int v8::debug::Script::Id () const
Definition at line 492 of file debug-interface.cc.
{ return Utils::OpenDirectHandle(this)->id(); }
References v8::Utils::OpenDirectHandle().
IsEmbedded()
bool v8::debug::Script::IsEmbedded () const
Definition at line 487 of file debug-interface.cc.
                              {
  auto script = Utils::OpenDirectHandle(this);
  return script->context_data() == i::GetReadOnlyRoots().uninitialized_symbol();
}
References v8::internal::GetReadOnlyRoots(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
IsModule()
bool v8::debug::Script::IsModule () const
Definition at line 603 of file debug-interface.cc.
                            {
  return Utils::OpenDirectHandle(this)->origin_options().IsModule();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8DebuggerScript::Initialize().
Name()
MaybeLocal< String > v8::debug::Script::Name () const
Definition at line 536 of file debug-interface.cc.
                                      {
  auto script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> value(script->name(), isolate);
  if (!IsString(*value)) return MaybeLocal<String>();
  return Utils::ToLocal(i::Cast<i::String>(value));
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::value.
Referenced by v8_inspector::V8DebuggerScript::GetScriptName().
OriginOptions()
ScriptOriginOptions v8::debug::Script::OriginOptions () const
Definition at line 478 of file debug-interface.cc.
                                                {
  return Utils::OpenDirectHandle(this)->origin_options();
}
References v8::Utils::OpenDirectHandle().
SetBreakpoint()
bool v8::debug::Script::SetBreakpoint (v8::Local< v8::String > condition, debug::Location * location, BreakpointId * id) const
Definition at line 749 of file debug-interface.cc.
                                                   {
  i::Handle<i::Script> script = Utils::OpenHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  int offset;
  if (!GetSourceOffset(*location).To(&offset)) {
    return false;
  }
  if (!isolate->debug()->SetBreakPointForScript(
          script, Utils::OpenDirectHandle(*condition), &offset, id)) {
    return false;
  }
  *location = GetSourceLocation(offset);
  return true;
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), GetSourceLocation(), GetSourceOffset(), v8::Utils::OpenDirectHandle(), v8::Utils::OpenHandle(), v8::internal::script, and v8::internal::Debug::SetBreakPointForScript().
Referenced by v8_inspector::V8DebuggerScript::setBreakpoint().
SetInstrumentationBreakpoint()
bool v8::debug::Script::SetInstrumentationBreakpoint (BreakpointId * id) const
Definition at line 765 of file debug-interface.cc.
                                                                {
  i::DirectHandle<i::Script> script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == i::Script::Type::kWasm) {
    isolate->debug()->SetInstrumentationBreakpointForWasmScript(script, id);
    return true;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  i::SharedFunctionInfo::ScriptIterator it(isolate, *script);
  for (i::Tagged<i::SharedFunctionInfo> sfi = it.Next(); !sfi.is_null();
       sfi = it.Next()) {
    if (sfi->is_toplevel()) {
      return isolate->debug()->SetBreakpointForFunction(
          handle(sfi, isolate), isolate->factory()->empty_string(), id,
          internal::Debug::kInstrumentation);
    }
  }
  return false;
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Debug::kInstrumentation, v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::Debug::SetBreakpointForFunction().
Referenced by v8_inspector::V8DebuggerScript::setInstrumentationBreakpoint().
SetScriptSource()
bool v8::debug::Script::SetScriptSource (v8::Local< v8::String > newSource, bool preview, bool allow_top_frame_live_editing, LiveEditResult * result) const
Definition at line 739 of file debug-interface.cc.
                                                           {
  i::Handle<i::Script> script = Utils::OpenHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  return isolate->debug()->SetScriptSource(
      script, Utils::OpenHandle(*newSource), preview,
      allow_top_frame_live_editing, result);
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::debug(), v8::Utils::OpenHandle(), v8::base::internal::result, v8::internal::script, and v8::internal::Debug::SetScriptSource().
Source()
Local< ScriptSource > v8::debug::Script::Source () const
Definition at line 583 of file debug-interface.cc.
                                         {
  auto script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (script->type() == i::Script::Type::kWasm) {
    i::DirectHandle<i::Object> wasm_native_module(
        script->wasm_managed_native_module(), isolate);
    return Utils::Convert<i::Object, ScriptSource>(wasm_native_module);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  i::DirectHandle<i::PrimitiveHeapObject> source(script->source(), isolate);
  return Utils::Convert<i::PrimitiveHeapObject, ScriptSource>(source);
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), and v8::internal::script.
Referenced by v8_inspector::V8DebuggerScript::Initialize().
SourceMappingURL()
MaybeLocal< String > v8::debug::Script::SourceMappingURL () const
Definition at line 552 of file debug-interface.cc.
                                                  {
  auto script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::Object> value(script->source_mapping_url(), isolate);
  if (!IsString(*value)) return MaybeLocal<String>();
  return Utils::ToLocal(i::Cast<i::String>(value));
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::value.
Referenced by v8_inspector::V8DebuggerScript::Initialize().
SourceURL()
MaybeLocal< String > v8::debug::Script::SourceURL () const
Definition at line 544 of file debug-interface.cc.
                                           {
  auto script = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::DirectHandle<i::PrimitiveHeapObject> value(script->source_url(), isolate);
  if (!IsString(*value)) return MaybeLocal<String>();
  return Utils::ToLocal(i::Cast<i::String>(value));
}
References v8::internal::Isolate::Current(), v8::Utils::OpenDirectHandle(), v8::internal::script, and v8::internal::value.
Referenced by v8_inspector::V8DebuggerScript::GetScriptURL(), and v8_inspector::V8DebuggerScript::Initialize().
StartColumn()
int v8::debug::Script::StartColumn () const
Definition at line 498 of file debug-interface.cc.
                              {
  return Utils::OpenDirectHandle(this)->column_offset();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8DebuggerScript::Initialize().
StartLine()
int v8::debug::Script::StartLine () const
Definition at line 494 of file debug-interface.cc.
                            {
  return Utils::OpenDirectHandle(this)->line_offset();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8DebuggerScript::Initialize().
WasCompiled()
bool v8::debug::Script::WasCompiled () const
Definition at line 482 of file debug-interface.cc.
                               {
  return Utils::OpenDirectHandle(this)->compilation_state() ==
         i::Script::CompilationState::kCompiled;
}
References v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-interface.h
/mnt/V8SourceCode/src/debug/debug-interface.cc