v8::internal::compiler::ControlEquivalence Class Reference
#include <control-equivalence.h>
Classes
struct Bracket
struct DFSStackEntry
struct NodeData
Public Member Functions
ControlEquivalence (Zone *zone, TFGraph *graph)
void Run (Node *exit)
size_t ClassOf (Node *node)
Private Types
enum DFSDirection { kInputDirection
, kUseDirection
 }
using BracketList = ZoneLinkedList< Bracket >
using DFSStack = ZoneStack< DFSStackEntry >
using Data = ZoneVector< NodeData * >
Private Member Functions
void VisitPre (Node *node)
void VisitMid (Node *node, DFSDirection direction)
void VisitPost (Node *node, Node *parent_node, DFSDirection direction)
void VisitBackedge (Node *from, Node *to, DFSDirection direction)
void RunUndirectedDFS (Node *exit)
void DetermineParticipationEnqueue (ZoneQueue< Node * > &queue, Node *node)
void DetermineParticipation (Node *exit)
NodeData * GetData (Node *node)
void AllocateData (Node *node)
int NewClassNumber ()
int NewDFSNumber ()
bool Participates (Node *node)
size_t GetClass (Node *node)
void SetClass (Node *node, size_t number)
BracketList & GetBracketList (Node *node)
void SetBracketList (Node *node, BracketList &list)
void DFSPush (DFSStack &stack, Node *node, Node *from, DFSDirection dir)
void DFSPop (DFSStack &stack, Node *node)
void BracketListDelete (BracketList &blist, Node *to, DFSDirection direction)
void BracketListTRACE (BracketList &blist)
Private Attributes
Zone *const zone_
TFGraph *const graph_
int dfs_number_
int class_number_
Data node_data_
Static Private Attributes
static const size_t kInvalidClass = static_cast<size_t>(-1)
Detailed Description
Definition at line 33 of file control-equivalence.h.
Member Typedef Documentation
BracketList
using v8::internal::compiler::ControlEquivalence::BracketList = ZoneLinkedList<Bracket> [private]
Definition at line 70 of file control-equivalence.h.
Data
using v8::internal::compiler::ControlEquivalence::Data = ZoneVector<NodeData*> [private]
Definition at line 97 of file control-equivalence.h.
DFSStack
using v8::internal::compiler::ControlEquivalence::DFSStack = ZoneStack<DFSStackEntry> [private]
Definition at line 81 of file control-equivalence.h.
Member Enumeration Documentation
DFSDirection
enum v8::internal::compiler::ControlEquivalence::DFSDirection [private]
Enumerator
kInputDirection
kUseDirection
Definition at line 59 of file control-equivalence.h.
{ kInputDirection, kUseDirection };
Constructor & Destructor Documentation
ControlEquivalence()
v8::internal::compiler::ControlEquivalence::ControlEquivalence (Zone * zone, TFGraph * graph) [inline]
Definition at line 36 of file control-equivalence.h.
      : zone_(zone),
        graph_(graph),
        dfs_number_(0),
        class_number_(1),
        node_data_(graph->NodeCount(), zone) {}
Member Function Documentation
AllocateData()
void v8::internal::compiler::ControlEquivalence::AllocateData (Node * node) [inline], [private]
Definition at line 136 of file control-equivalence.h.
                                {
    size_t const index = node->id();
    if (index >= node_data_.size()) node_data_.resize(index + 1);
    node_data_[index] = zone_->New<NodeData>(zone_);
  }
References v8::internal::compiler::Node::id(), and v8::internal::index.
Referenced by DetermineParticipationEnqueue().
BracketListDelete()
void v8::internal::compiler::ControlEquivalence::BracketListDelete (BracketList & blist, Node * to, DFSDirection direction) [private]
Definition at line 207 of file control-equivalence.cc.
                                                                   {
  // TODO(turbofan): Optimize this to avoid linear search.
  for (BracketList::iterator i = blist.begin(); i != blist.end(); /*nop*/) {
    if (i->to == to && i->direction != direction) {
      TRACE(" BList erased: {%d->%d}\n", i->from->id(), i->to->id());
      i = blist.erase(i);
    } else {
      ++i;
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::TRACE().
Referenced by VisitMid(), and VisitPost().
BracketListTRACE()
void v8::internal::compiler::ControlEquivalence::BracketListTRACE (BracketList & blist) [private]
Definition at line 221 of file control-equivalence.cc.
                                                            {
  if (v8_flags.trace_turbo_ceq) {
    TRACE(" BList: ");
    for (Bracket bracket : blist) {
      TRACE("{%d->%d} ", bracket.from->id(), bracket.to->id());
    }
    TRACE("\n");
  }
}
References v8::internal::TRACE(), and v8::internal::v8_flags.
Referenced by VisitMid().
ClassOf()
size_t v8::internal::compiler::ControlEquivalence::ClassOf (Node * node) [inline]
Definition at line 52 of file control-equivalence.h.
                             {
    DCHECK_NE(kInvalidClass, GetClass(node));
    return GetClass(node);
  }
References DCHECK_NE.
Referenced by v8::internal::compiler::CFGBuilder::IsSingleEntrySingleExitRegion().
DetermineParticipation()
void v8::internal::compiler::ControlEquivalence::DetermineParticipation (Node * exit) [private]
Definition at line 174 of file control-equivalence.cc.
                                                          {
  ZoneQueue<Node*> queue(zone_);
  DetermineParticipationEnqueue(queue, exit);
  while (!queue.empty()) { // Breadth-first backwards traversal.
    Node* node = queue.front();
    queue.pop();
    int max = NodeProperties::PastControlIndex(node);
    for (int i = NodeProperties::FirstControlIndex(node); i < max; i++) {
      DetermineParticipationEnqueue(queue, node->InputAt(i));
    }
  }
}
References DetermineParticipationEnqueue(), v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NodeProperties::PastControlIndex(), and zone_.
Referenced by Run().
DetermineParticipationEnqueue()
void v8::internal::compiler::ControlEquivalence::DetermineParticipationEnqueue (ZoneQueue< Node * > & queue, Node * node) [private]
Definition at line 165 of file control-equivalence.cc.
                                                                   {
  if (!Participates(node)) {
    AllocateData(node);
    queue.push(node);
  }
}
References AllocateData(), and Participates().
Referenced by DetermineParticipation().
DFSPop()
void v8::internal::compiler::ControlEquivalence::DFSPop (DFSStack & stack, Node * node) [private]
Definition at line 199 of file control-equivalence.cc.
                                                           {
  DCHECK_EQ(stack.top().node, node);
  GetData(node)->on_stack = false;
  GetData(node)->visited = true;
  stack.pop();
}
References DCHECK_EQ, GetData(), v8::internal::compiler::ControlEquivalence::NodeData::on_stack, v8::internal::stack, and v8::internal::compiler::ControlEquivalence::NodeData::visited.
Referenced by RunUndirectedDFS().
DFSPush()
void v8::internal::compiler::ControlEquivalence::DFSPush (DFSStack & stack, Node * node, Node * from, DFSDirection dir) [private]
Definition at line 188 of file control-equivalence.cc.
                                                   {
  DCHECK(Participates(node));
  DCHECK(!GetData(node)->visited);
  GetData(node)->on_stack = true;
  Node::InputEdges::iterator input = node->input_edges().begin();
  Node::UseEdges::iterator use = node->use_edges().begin();
  stack.push({dir, input, use, from, node});
}
References v8::internal::compiler::Node::UseEdges::begin(), v8::internal::compiler::Node::InputEdges::begin(), v8::internal::DCHECK(), GetData(), v8::internal::compiler::Node::input_edges(), v8::internal::compiler::ControlEquivalence::NodeData::on_stack, Participates(), v8::internal::stack, use(), and v8::internal::compiler::Node::use_edges().
Referenced by RunUndirectedDFS().
GetBracketList()
BracketList& v8::internal::compiler::ControlEquivalence::GetBracketList (Node * node) [inline], [private]
Definition at line 155 of file control-equivalence.h.
                                          {
    DCHECK(Participates(node));
    return GetData(node)->blist;
  }
References v8::internal::DCHECK().
Referenced by VisitBackedge(), VisitMid(), and VisitPost().
GetClass()
size_t v8::internal::compiler::ControlEquivalence::GetClass (Node * node) [inline], [private]
Definition at line 148 of file control-equivalence.h.
{ return GetData(node)->class_number; }
Referenced by Run(), and VisitMid().
GetData()
NodeData* v8::internal::compiler::ControlEquivalence::GetData (Node * node) [inline], [private]
Definition at line 131 of file control-equivalence.h.
                                {
    size_t const index = node->id();
    if (index >= node_data_.size()) node_data_.resize(index + 1);
    return node_data_[index];
  }
References v8::internal::compiler::Node::id(), and v8::internal::index.
Referenced by DFSPop(), DFSPush(), and RunUndirectedDFS().
NewClassNumber()
int v8::internal::compiler::ControlEquivalence::NewClassNumber () [inline], [private]
Definition at line 142 of file control-equivalence.h.
{ return class_number_++; }
Referenced by VisitMid().
NewDFSNumber()
int v8::internal::compiler::ControlEquivalence::NewDFSNumber () [inline], [private]
Definition at line 143 of file control-equivalence.h.
{ return dfs_number_++; }
Participates()
bool v8::internal::compiler::ControlEquivalence::Participates (Node * node) [inline], [private]
Definition at line 145 of file control-equivalence.h.
{ return GetData(node) != nullptr; }
Referenced by DetermineParticipationEnqueue(), DFSPush(), Run(), and RunUndirectedDFS().
Run()
void v8::internal::compiler::ControlEquivalence::Run (Node * exit)
Definition at line 17 of file control-equivalence.cc.
                                       {
  if (!Participates(exit) || GetClass(exit) == kInvalidClass) {
    DetermineParticipation(exit);
    RunUndirectedDFS(exit);
  }
}
References DetermineParticipation(), GetClass(), kInvalidClass, Participates(), and RunUndirectedDFS().
Referenced by v8::internal::compiler::CFGBuilder::Run().
RunUndirectedDFS()
void v8::internal::compiler::ControlEquivalence::RunUndirectedDFS (Node * exit) [private]
Definition at line 88 of file control-equivalence.cc.
                                                    {
  ZoneStack<DFSStackEntry> stack(zone_);
  DFSPush(stack, exit, nullptr, kInputDirection);
  VisitPre(exit);
  while (!stack.empty()) { // Undirected depth-first backwards traversal.
    DFSStackEntry& entry = stack.top();
    Node* node = entry.node;
    if (entry.direction == kInputDirection) {
      if (entry.input != node->input_edges().end()) {
        Edge edge = *entry.input;
        Node* input = edge.to();
        ++(entry.input);
        if (NodeProperties::IsControlEdge(edge)) {
          // Visit next control input.
          if (!Participates(input)) continue;
          if (GetData(input)->visited) continue;
          if (GetData(input)->on_stack) {
            // Found backedge if input is on stack.
            if (input != entry.parent_node) {
              VisitBackedge(node, input, kInputDirection);
            }
          } else {
            // Push input onto stack.
            DFSPush(stack, input, node, kInputDirection);
            VisitPre(input);
          }
        }
        continue;
      }
      if (entry.use != node->use_edges().end()) {
        // Switch direction to uses.
        entry.direction = kUseDirection;
        VisitMid(node, kInputDirection);
        continue;
      }
    }
    if (entry.direction == kUseDirection) {
      if (entry.use != node->use_edges().end()) {
        Edge edge = *entry.use;
        Node* use = edge.from();
        ++(entry.use);
        if (NodeProperties::IsControlEdge(edge)) {
          // Visit next control use.
          if (!Participates(use)) continue;
          if (GetData(use)->visited) continue;
          if (GetData(use)->on_stack) {
            // Found backedge if use is on stack.
            if (use != entry.parent_node) {
              VisitBackedge(node, use, kUseDirection);
            }
          } else {
            // Push use onto stack.
            DFSPush(stack, use, node, kUseDirection);
            VisitPre(use);
          }
        }
        continue;
      }
      if (entry.input != node->input_edges().end()) {
        // Switch direction to inputs.
        entry.direction = kInputDirection;
        VisitMid(node, kUseDirection);
        continue;
      }
    }
    // Pop node from stack when done with all inputs and uses.
    DCHECK(entry.input == node->input_edges().end());
    DCHECK(entry.use == node->use_edges().end());
    VisitPost(node, entry.parent_node, entry.direction);
    DFSPop(stack, node);
  }
}
References v8::internal::DCHECK(), DFSPop(), DFSPush(), v8::internal::compiler::ControlEquivalence::DFSStackEntry::direction, v8::internal::compiler::Node::UseEdges::end(), v8::internal::compiler::Node::InputEdges::end(), v8::internal::compiler::Edge::from(), GetData(), v8::internal::compiler::ControlEquivalence::DFSStackEntry::input, v8::internal::compiler::Node::input_edges(), v8::internal::compiler::NodeProperties::IsControlEdge(), kInputDirection, kUseDirection, v8::internal::compiler::ControlEquivalence::DFSStackEntry::node, v8::internal::compiler::ControlEquivalence::NodeData::on_stack, v8::internal::compiler::ControlEquivalence::DFSStackEntry::parent_node, Participates(), v8::internal::stack, v8::internal::compiler::Edge::to(), v8::internal::compiler::ControlEquivalence::DFSStackEntry::use, use(), v8::internal::compiler::Node::use_edges(), VisitBackedge(), v8::internal::compiler::ControlEquivalence::NodeData::visited, VisitMid(), VisitPost(), VisitPre(), and zone_.
Referenced by Run().
SetBracketList()
void v8::internal::compiler::ControlEquivalence::SetBracketList (Node * node, BracketList & list) [inline], [private]
Definition at line 159 of file control-equivalence.h.
                                                     {
    DCHECK(Participates(node));
    GetData(node)->blist = list;
  }
References v8::internal::DCHECK().
SetClass()
void v8::internal::compiler::ControlEquivalence::SetClass (Node * node, size_t number) [inline], [private]
Definition at line 149 of file control-equivalence.h.
                                           {
    DCHECK(Participates(node));
    GetData(node)->class_number = number;
  }
References v8::internal::DCHECK().
Referenced by VisitMid().
VisitBackedge()
void v8::internal::compiler::ControlEquivalence::VisitBackedge (Node * from, Node * to, DFSDirection direction) [private]
Definition at line 77 of file control-equivalence.cc.
                                                               {
  TRACE("CEQ: Backedge from #%d:%s to #%d:%s\n", from->id(),
        from->op()->mnemonic(), to->id(), to->op()->mnemonic());
  // Push backedge onto the bracket list [line:25].
  Bracket bracket = {direction, kInvalidClass, 0, from, to};
  GetBracketList(from).push_back(bracket);
}
References GetBracketList(), v8::internal::compiler::Node::id(), kInvalidClass, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), and v8::internal::TRACE().
Referenced by RunUndirectedDFS(), and VisitMid().
VisitMid()
void v8::internal::compiler::ControlEquivalence::VisitMid (Node * node, DFSDirection direction) [private]
Definition at line 34 of file control-equivalence.cc.
                                                                    {
  TRACE("CEQ: Mid-visit of #%d:%s\n", node->id(), node->op()->mnemonic());
  BracketList& blist = GetBracketList(node);
  // Remove brackets pointing to this node [line:19].
  BracketListDelete(blist, node, direction);
  // Potentially introduce artificial dependency from start to end.
  if (blist.empty()) {
    DCHECK_EQ(kInputDirection, direction);
    VisitBackedge(node, graph_->end(), kInputDirection);
  }
  // Potentially start a new equivalence class [line:37].
  BracketListTRACE(blist);
  Bracket* recent = &blist.back();
  if (recent->recent_size != blist.size()) {
    recent->recent_size = blist.size();
    recent->recent_class = NewClassNumber();
  }
  // Assign equivalence class to node.
  SetClass(node, recent->recent_class);
  TRACE(" Assigned class number is %zu\n", GetClass(node));
}
References BracketListDelete(), BracketListTRACE(), DCHECK_EQ, v8::internal::compiler::TFGraph::end(), GetBracketList(), GetClass(), graph_, v8::internal::compiler::Node::id(), kInputDirection, v8::internal::compiler::Operator::mnemonic(), NewClassNumber(), v8::internal::compiler::Node::op(), v8::internal::compiler::ControlEquivalence::Bracket::recent_class, v8::internal::compiler::ControlEquivalence::Bracket::recent_size, SetClass(), v8::internal::TRACE(), and VisitBackedge().
Referenced by RunUndirectedDFS().
VisitPost()
void v8::internal::compiler::ControlEquivalence::VisitPost (Node * node, Node * parent_node, DFSDirection direction) [private]
Definition at line 61 of file control-equivalence.cc.
                                                           {
  TRACE("CEQ: Post-visit of #%d:%s\n", node->id(), node->op()->mnemonic());
  BracketList& blist = GetBracketList(node);
  // Remove brackets pointing to this node [line:19].
  BracketListDelete(blist, node, direction);
  // Propagate bracket list up the DFS tree [line:13].
  if (parent_node != nullptr) {
    BracketList& parent_blist = GetBracketList(parent_node);
    parent_blist.splice(parent_blist.end(), blist);
  }
}
References BracketListDelete(), GetBracketList(), v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), and v8::internal::TRACE().
Referenced by RunUndirectedDFS().
VisitPre()
void v8::internal::compiler::ControlEquivalence::VisitPre (Node * node) [private]
Definition at line 29 of file control-equivalence.cc.
                                            {
  TRACE("CEQ: Pre-visit of #%d:%s\n", node->id(), node->op()->mnemonic());
}
References v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), and v8::internal::TRACE().
Referenced by RunUndirectedDFS().
Member Data Documentation
class_number_
int v8::internal::compiler::ControlEquivalence::class_number_ [private]
Definition at line 176 of file control-equivalence.h.
dfs_number_
int v8::internal::compiler::ControlEquivalence::dfs_number_ [private]
Definition at line 175 of file control-equivalence.h.
graph_
TFGraph* const v8::internal::compiler::ControlEquivalence::graph_ [private]
Definition at line 174 of file control-equivalence.h.
Referenced by VisitMid().
kInvalidClass
STATIC_CONST_MEMBER_DEFINITION const size_t v8::internal::compiler::ControlEquivalence::kInvalidClass = static_cast<size_t>(-1) [static], [private]
Definition at line 58 of file control-equivalence.h.
Referenced by Run(), and VisitBackedge().
node_data_
Data v8::internal::compiler::ControlEquivalence::node_data_ [private]
Definition at line 177 of file control-equivalence.h.
zone_
Zone* const v8::internal::compiler::ControlEquivalence::zone_ [private]
Definition at line 173 of file control-equivalence.h.
Referenced by DetermineParticipation(), and RunUndirectedDFS().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/control-equivalence.h
/mnt/V8SourceCode/src/compiler/control-equivalence.cc