v8::internal::compiler::FrameStateInfo Class Reference
#include <frame-states.h>
Public Member Functions
FrameStateInfo (BytecodeOffset bailout_id, OutputFrameStateCombine state_combine, const FrameStateFunctionInfo *info)
FrameStateType type () const
BytecodeOffset bailout_id () const
OutputFrameStateCombine state_combine () const
MaybeIndirectHandle< SharedFunctionInfo > shared_info () const
MaybeIndirectHandle< BytecodeArray > bytecode_array () const
uint16_t parameter_count () const
uint16_t parameter_count_without_receiver () const
uint16_t max_arguments () const
int local_count () const
int stack_count () const
const FrameStateFunctionInfo * function_info () const
Private Attributes
BytecodeOffset const bailout_id_
OutputFrameStateCombine const frame_state_combine_
const FrameStateFunctionInfo *const info_
Detailed Description
Definition at line 177 of file frame-states.h.
Constructor & Destructor Documentation
FrameStateInfo()
v8::internal::compiler::FrameStateInfo::FrameStateInfo (BytecodeOffset bailout_id, OutputFrameStateCombine state_combine, const FrameStateFunctionInfo * info) [inline]
Definition at line 179 of file frame-states.h.
      : bailout_id_(bailout_id),
        frame_state_combine_(state_combine),
        info_(info) {}
Member Function Documentation
bailout_id()
BytecodeOffset v8::internal::compiler::FrameStateInfo::bailout_id () const [inline]
Definition at line 190 of file frame-states.h.
{ return bailout_id_; }
References bailout_id_.
Referenced by v8::internal::compiler::CloneFrameState(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::hash_value(), v8::internal::compiler::turboshaft::FrameStateOp::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
bytecode_array()
MaybeIndirectHandle<BytecodeArray> v8::internal::compiler::FrameStateInfo::bytecode_array () const [inline]
Definition at line 196 of file frame-states.h.
                                                            {
    return info_ == nullptr ? MaybeIndirectHandle<BytecodeArray>()
                            : info_->bytecode_array();
  }
References v8::internal::compiler::FrameStateFunctionInfo::bytecode_array(), and info_.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter().
function_info()
const FrameStateFunctionInfo* v8::internal::compiler::FrameStateInfo::function_info () const [inline]
Definition at line 219 of file frame-states.h.
{ return info_; }
References info_.
Referenced by v8::internal::compiler::CloneFrameState(), v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::GetFunctionInfo(), and v8::internal::compiler::operator==().
local_count()
int v8::internal::compiler::FrameStateInfo::local_count () const [inline]
Definition at line 212 of file frame-states.h.
                          {
    DCHECK_NOT_NULL(info_);
    return info_->local_count();
  }
References DCHECK_NOT_NULL, info_, and v8::internal::compiler::FrameStateFunctionInfo::local_count().
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), and v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal().
max_arguments()
uint16_t v8::internal::compiler::FrameStateInfo::max_arguments () const [inline]
Definition at line 208 of file frame-states.h.
                                 {
    DCHECK_NOT_NULL(info_);
    return info_->max_arguments();
  }
References DCHECK_NOT_NULL, info_, and v8::internal::compiler::FrameStateFunctionInfo::max_arguments().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal().
parameter_count()
uint16_t v8::internal::compiler::FrameStateInfo::parameter_count () const [inline]
Definition at line 200 of file frame-states.h.
                                   {
    DCHECK_NOT_NULL(info_);
    return info_->parameter_count();
  }
References DCHECK_NOT_NULL, info_, and v8::internal::compiler::FrameStateFunctionInfo::parameter_count().
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), and v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal().
parameter_count_without_receiver()
uint16_t v8::internal::compiler::FrameStateInfo::parameter_count_without_receiver () const [inline]
Definition at line 204 of file frame-states.h.
                                                    {
    DCHECK_NOT_NULL(info_);
    return info_->parameter_count_without_receiver();
  }
References DCHECK_NOT_NULL, info_, and v8::internal::compiler::FrameStateFunctionInfo::parameter_count_without_receiver().
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
shared_info()
MaybeIndirectHandle<SharedFunctionInfo> v8::internal::compiler::FrameStateInfo::shared_info () const [inline]
Definition at line 192 of file frame-states.h.
                                                              {
    return info_ == nullptr ? MaybeIndirectHandle<SharedFunctionInfo>()
                            : info_->shared_info();
  }
References info_, and v8::internal::compiler::FrameStateFunctionInfo::shared_info().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::operator<<(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments().
stack_count()
int v8::internal::compiler::FrameStateInfo::stack_count () const [inline]
Definition at line 216 of file frame-states.h.
                          {
    return type() == FrameStateType::kUnoptimizedFunction ? 1 : 0;
  }
References v8::internal::compiler::kUnoptimizedFunction, and type().
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), and v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal().
state_combine()
OutputFrameStateCombine v8::internal::compiler::FrameStateInfo::state_combine () const [inline]
Definition at line 191 of file frame-states.h.
{ return frame_state_combine_; }
References frame_state_combine_.
Referenced by v8::internal::compiler::turboshaft::WasmJSLoweringReducer< Next >::CreateFrameStateWithUpdatedBailoutId(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct().
type()
FrameStateType v8::internal::compiler::FrameStateInfo::type () const [inline]
Definition at line 186 of file frame-states.h.
                              {
    return info_ == nullptr ? FrameStateType::kUnoptimizedFunction
                            : info_->type();
  }
References info_, v8::internal::compiler::kUnoptimizedFunction, and v8::internal::compiler::FrameStateFunctionInfo::type().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), and stack_count().
Member Data Documentation
bailout_id_
BytecodeOffset const v8::internal::compiler::FrameStateInfo::bailout_id_ [private]
Definition at line 222 of file frame-states.h.
Referenced by bailout_id().
frame_state_combine_
OutputFrameStateCombine const v8::internal::compiler::FrameStateInfo::frame_state_combine_ [private]
Definition at line 223 of file frame-states.h.
Referenced by state_combine().
info_
const FrameStateFunctionInfo* const v8::internal::compiler::FrameStateInfo::info_ [private]
Definition at line 224 of file frame-states.h.
Referenced by bytecode_array(), function_info(), local_count(), max_arguments(), parameter_count(), parameter_count_without_receiver(), shared_info(), and type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/frame-states.h