v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap Class Reference
Public Member Functions
void Add (LiftoffRegister src, LiftoffRegister dst)
std::optional< LiftoffRegister > Lookup (LiftoffRegister src)
Private Attributes
base::SmallVector< LiftoffRegister, 8 > map_
Detailed Description
Definition at line 33 of file liftoff-assembler.cc.
Member Function Documentation
Add()
void v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::Add (LiftoffRegister src, LiftoffRegister dst) [inline]
Definition at line 35 of file liftoff-assembler.cc.
                                                     {
    if ([[maybe_unused]] auto previous = Lookup(src)) {
      DCHECK_EQ(previous, dst);
      return;
    }
    map_.emplace_back(src);
    map_.emplace_back(dst);
  }
References DCHECK_EQ.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion().
Lookup()
std::optional<LiftoffRegister> v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::Lookup (LiftoffRegister src) [inline]
Definition at line 44 of file liftoff-assembler.cc.
                                                           {
    for (auto it = map_.begin(), end = map_.end(); it != end; it += 2) {
      if (it->is_gp_pair() == src.is_gp_pair() &&
          it->is_fp_pair() == src.is_fp_pair() && *it == src)
        return *(it + 1);
    }
    return {};
  }
References v8::internal::compiler::end(), v8::internal::wasm::LiftoffRegister::is_fp_pair(), and v8::internal::wasm::LiftoffRegister::is_gp_pair().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::InitMergeRegion().
Member Data Documentation
map_
base::SmallVector<LiftoffRegister, 8> v8::internal::wasm::anonymous_namespace{liftoff-assembler.cc}::RegisterReuseMap::map_ [private]
Definition at line 55 of file liftoff-assembler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-assembler.cc