v8::internal::RegExpResultVector Class Reference
#include <regexp-result-vector.h>
Static Public Member Functions
static int32_t * Allocate (Isolate *isolate, uint32_t size)
static void Free (Isolate *isolate, int32_t *vector)
Detailed Description
Definition at line 33 of file regexp-result-vector.h.
Member Function Documentation
Allocate()
int32_t * v8::internal::RegExpResultVector::Allocate (Isolate * isolate, uint32_t size) [static]
Definition at line 51 of file regexp-result-vector.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  auto vector = new int32_t[size];
  isolate->active_dynamic_regexp_result_vectors().insert(vector);
  return vector;
}
References v8::internal::Isolate::active_dynamic_regexp_result_vectors(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
Referenced by v8::internal::RegExpResultVectorScope::Initialize().
Free()
void v8::internal::RegExpResultVector::Free (Isolate * isolate, int32_t * vector) [static]
Definition at line 60 of file regexp-result-vector.cc.
                                                               {
  DisallowGarbageCollection no_gc;
  DCHECK_NOT_NULL(vector);
  isolate->active_dynamic_regexp_result_vectors().erase(vector);
  delete[] vector;
}
References v8::internal::Isolate::active_dynamic_regexp_result_vectors(), DCHECK_NOT_NULL, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::RegExpResultVectorScope::~RegExpResultVectorScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-result-vector.h
/mnt/V8SourceCode/src/regexp/regexp-result-vector.cc