v8::internal::wasm::AsmType Class Reference
#include <asm-types.h>
Public Types
enum : int32_t { kNotHeapType = -1
 }
Public Member Functions
AsmValueType * AsValueType ()
AsmCallableType * AsCallableType ()
std::string Name ()
bool IsA (AsmType *that)
int32_t ElementSizeInBytes ()
AsmType * LoadType ()
AsmType * StoreType ()
Static Public Member Functions
static AsmType * Function (Zone *zone, AsmType *ret)
static AsmType * OverloadedFunction (Zone *zone)
static AsmType * FroundType (Zone *zone)
static AsmType * MinMaxType (Zone *zone, AsmType *dest, AsmType *src)
static bool IsExactly (AsmType *x, AsmType *y)
Detailed Description
Definition at line 178 of file asm-types.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : int32_t
Enumerator
kNotHeapType
Definition at line 230 of file asm-types.h.
: int32_t { kNotHeapType = -1 };
Member Function Documentation
AsCallableType()
AsmCallableType * v8::internal::wasm::AsmType::AsCallableType ()
Definition at line 13 of file asm-types.cc.
                                         {
  if (AsValueType() != nullptr) {
    return nullptr;
  }
  return reinterpret_cast<AsmCallableType*>(this);
}
References AsValueType().
Referenced by v8::internal::wasm::AsmOverloadedFunctionType::AddOverload(), v8::internal::wasm::AsmCallableType::IsA(), IsA(), Name(), and v8::internal::wasm::AsmJsParser::ValidateCall().
AsValueType()
AsmValueType* v8::internal::wasm::AsmType::AsValueType () [inline]
Definition at line 196 of file asm-types.h.
{ return AsmValueType::AsValueType(this); }
References v8::internal::wasm::AsmValueType::AsValueType().
Referenced by AsCallableType(), ElementSizeInBytes(), IsA(), IsExactly(), LoadType(), MinMaxType(), Name(), and StoreType().
ElementSizeInBytes()
int32_t v8::internal::wasm::AsmType::ElementSizeInBytes ()
Definition at line 72 of file asm-types.cc.
                                    {
  auto* value = AsValueType();
  if (value == nullptr) {
    return AsmType::kNotHeapType;
  }
  switch (value->Bitset()) {
    case AsmValueType::kAsmInt8Array:
    case AsmValueType::kAsmUint8Array:
      return 1;
    case AsmValueType::kAsmInt16Array:
    case AsmValueType::kAsmUint16Array:
      return 2;
    case AsmValueType::kAsmInt32Array:
    case AsmValueType::kAsmUint32Array:
    case AsmValueType::kAsmFloat32Array:
      return 4;
    case AsmValueType::kAsmFloat64Array:
      return 8;
    default:
      return AsmType::kNotHeapType;
  }
}
References AsValueType(), kNotHeapType, and v8::internal::value.
Referenced by v8::internal::wasm::AsmJsParser::ValidateHeapAccess().
FroundType()
AsmType * v8::internal::wasm::AsmType::FroundType (Zone * zone) [static]
Definition at line 171 of file asm-types.cc.
                                       {
  auto* Fround = zone->New<AsmFroundType>();
  return reinterpret_cast<AsmType*>(Fround);
}
References v8::internal::Zone::New().
Referenced by v8::internal::wasm::AsmJsParser::InitializeStdlibTypes().
Function()
static AsmType* v8::internal::wasm::AsmType::Function (Zone * zone, AsmType * ret) [inline], [static]
Definition at line 201 of file asm-types.h.
                                                     {
    AsmFunctionType* f = zone->New<AsmFunctionType>(zone, ret);
    return reinterpret_cast<AsmType*>(f);
  }
References v8::internal::Zone::New().
Referenced by v8::internal::wasm::AsmJsParser::InitializeStdlibTypes(), v8::internal::wasm::AsmJsParser::ValidateCall(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
IsA()
bool v8::internal::wasm::AsmType::IsA (AsmType * that)
Definition at line 55 of file asm-types.cc.
                               {
  // IsA is used for querying inheritance relationships. Therefore it is only
  // meaningful for basic types.
  if (auto* avt = this->AsValueType()) {
    if (auto* tavt = that->AsValueType()) {
      return (avt->Bitset() & tavt->Bitset()) == tavt->Bitset();
    }
    return false;
  }
  if (auto* as_callable = this->AsCallableType()) {
    return as_callable->IsA(that);
  }
  UNREACHABLE();
}
References AsCallableType(), AsValueType(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::AsmJsParser::AdditiveExpression(), v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::BitwiseANDExpression(), v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::wasm::AsmJsParser::BitwiseXORExpression(), v8::internal::wasm::AsmJsParser::CallExpression(), v8::internal::wasm::AsmJsParser::ConditionalExpression(), v8::internal::wasm::AsmJsParser::ConvertSignature(), v8::internal::wasm::AsmJsParser::Expression(), v8::internal::wasm::AsmJsParser::ExpressionStatement(), v8::internal::wasm::AsmJsParser::ForStatement(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), v8::internal::wasm::AsmJsParser::ReturnStatement(), v8::internal::wasm::AsmJsParser::ShiftExpression(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), v8::internal::wasm::AsmJsParser::ValidateFunction(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), v8::internal::wasm::AsmJsParser::ValidateFunctionParams(), v8::internal::wasm::AsmJsParser::ValidateFunctionTable(), v8::internal::wasm::AsmJsParser::ValidateHeapAccess(), and v8::internal::wasm::AsmJsParser::ValidateModuleVarFromGlobal().
IsExactly()
bool v8::internal::wasm::AsmType::IsExactly (AsmType * x, AsmType * y) [static]
Definition at line 38 of file asm-types.cc.
                                              {
  // TODO(jpp): maybe this can become x == y.
  if (x == nullptr) return y == nullptr;
  AsmValueType* avt = x->AsValueType();
  if (avt != nullptr) {
    AsmValueType* tavt = y->AsValueType();
    if (tavt == nullptr) {
      return false;
    }
    return avt->Bitset() == tavt->Bitset();
  }
  // TODO(jpp): is it useful to allow non-value types to be tested with
  // IsExactly?
  return x == y;
}
References AsValueType(), v8::internal::wasm::AsmValueType::Bitset(), and v8::internal::y.
Referenced by v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::wasm::anonymous_namespace{asm-types.cc}::AsmMinMaxType::CanBeInvokedWith(), v8::internal::wasm::AsmFunctionType::CanBeInvokedWith(), and v8::internal::wasm::AsmFunctionType::IsA().
LoadType()
AsmType * v8::internal::wasm::AsmType::LoadType ()
Definition at line 95 of file asm-types.cc.
                           {
  auto* value = AsValueType();
  if (value == nullptr) {
    return AsmType::None();
  }
  switch (value->Bitset()) {
    case AsmValueType::kAsmInt8Array:
    case AsmValueType::kAsmUint8Array:
    case AsmValueType::kAsmInt16Array:
    case AsmValueType::kAsmUint16Array:
    case AsmValueType::kAsmInt32Array:
    case AsmValueType::kAsmUint32Array:
      return AsmType::Intish();
    case AsmValueType::kAsmFloat32Array:
      return AsmType::FloatQ();
    case AsmValueType::kAsmFloat64Array:
      return AsmType::DoubleQ();
    default:
      return AsmType::None();
  }
}
References AsValueType(), v8::None, and v8::internal::value.
MinMaxType()
AsmType * v8::internal::wasm::AsmType::MinMaxType (Zone * zone, AsmType * dest, AsmType * src) [static]
Definition at line 229 of file asm-types.cc.
                                                                    {
  DCHECK_NOT_NULL(dest->AsValueType());
  DCHECK_NOT_NULL(src->AsValueType());
  auto* MinMax = zone->New<AsmMinMaxType>(dest, src);
  return reinterpret_cast<AsmType*>(MinMax);
}
References AsValueType(), DCHECK_NOT_NULL, and v8::internal::Zone::New().
Referenced by v8::internal::wasm::AsmJsParser::InitializeStdlibTypes().
Name()
std::string v8::internal::wasm::AsmType::Name ()
Definition at line 21 of file asm-types.cc.
                        {
  AsmValueType* avt = this->AsValueType();
  if (avt != nullptr) {
    switch (avt->Bitset()) {
#define RETURN_TYPE_NAME(CamelName, string_name, number, parent_types) \
  case AsmValueType::kAsm##CamelName: \
    return string_name;
      FOR_EACH_ASM_VALUE_TYPE_LIST(RETURN_TYPE_NAME)
#undef RETURN_TYPE_NAME
      default:
        UNREACHABLE();
    }
  }
  return this->AsCallableType()->Name();
}
References AsCallableType(), AsValueType(), v8::internal::wasm::AsmValueType::Bitset(), FOR_EACH_ASM_VALUE_TYPE_LIST, v8::internal::wasm::AsmCallableType::Name(), RETURN_TYPE_NAME, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::AsmFunctionType::Name().
OverloadedFunction()
static AsmType* v8::internal::wasm::AsmType::OverloadedFunction (Zone * zone) [inline], [static]
Definition at line 208 of file asm-types.h.
                                                 {
    auto* f = zone->New<AsmOverloadedFunctionType>(zone);
    return reinterpret_cast<AsmType*>(f);
  }
References v8::internal::Zone::New().
Referenced by v8::internal::wasm::AsmJsParser::InitializeStdlibTypes().
StoreType()
AsmType * v8::internal::wasm::AsmType::StoreType ()
Definition at line 117 of file asm-types.cc.
                            {
  auto* value = AsValueType();
  if (value == nullptr) {
    return AsmType::None();
  }
  switch (value->Bitset()) {
    case AsmValueType::kAsmInt8Array:
    case AsmValueType::kAsmUint8Array:
    case AsmValueType::kAsmInt16Array:
    case AsmValueType::kAsmUint16Array:
    case AsmValueType::kAsmInt32Array:
    case AsmValueType::kAsmUint32Array:
      return AsmType::Intish();
    case AsmValueType::kAsmFloat32Array:
      return AsmType::FloatishDoubleQ();
    case AsmValueType::kAsmFloat64Array:
      return AsmType::FloatQDoubleQ();
    default:
      return AsmType::None();
  }
}
References AsValueType(), v8::None, and v8::internal::value.
Referenced by v8::internal::wasm::AsmJsParser::MemberExpression().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/asmjs/asm-types.h
/mnt/V8SourceCode/src/asmjs/asm-types.cc