v8::Array Class Reference
An instance of the built-in array constructor (ECMA-262, 15.4.2).
#include <v8-container.h>
Public Types
enum class CallbackResult { kException
, kBreak
, kContinue
 }
using IterationCallback = CallbackResult(*)(uint32_t index, Local< Value > element, void *data)
Public Member Functions
uint32_t Length () const
Maybe< void > Iterate (Local< Context > context, IterationCallback callback, void *callback_data)
Calls {callback} for every element of this array, passing {callback_data} as its {data} parameter.
Static Public Member Functions
static Local< Array > New (Isolate *isolate, int length=0)
Creates a JavaScript array with the given length.
static Local< Array > New (Isolate *isolate, Local< Value > *elements, size_t length)
Creates a JavaScript array out of a Local<Value> array in C++ with a known length.
static Array * Cast (Value *value)
static MaybeLocal< Array > New (Local< Context > context, size_t length, std::function< MaybeLocal< v8::Value >()> next_value_callback)
Creates a JavaScript array from a provided callback.
Private Member Functions
Array ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
An instance of the built-in array constructor (ECMA-262, 15.4.2).
Definition at line 25 of file v8-container.h.
Member Typedef Documentation
IterationCallback
using v8::Array::IterationCallback = CallbackResult (*)(uint32_t index, Local<Value> element, void* data)
Definition at line 69 of file v8-container.h.
Member Enumeration Documentation
CallbackResult
enum v8::Array::CallbackResult [strong]
Enumerator
kException
kBreak
kContinue
Definition at line 64 of file v8-container.h.
                            {
    kException,
    kBreak,
    kContinue,
  };
Constructor & Destructor Documentation
Array()
v8::Array::Array () [private]
Member Function Documentation
Cast()
static Array* v8::Array::Cast (Value * value) [inline], [static]
Definition at line 41 of file v8-container.h.
                                             {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<Array*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::Array::CheckCast (Value * obj) [static], [private]
Definition at line 3961 of file api.cc.
                                   {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsJSArray(*obj), "v8::Array::Cast",
                  "Value is not an Array");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Iterate()
Maybe< void > v8::Array::Iterate (Local< Context > context, IterationCallback callback, void * callback_data)
Calls {callback} for every element of this array, passing {callback_data} as its {data} parameter.
This function will typically be faster than calling {Get()} repeatedly. As a consequence of being optimized for low overhead, the provided callback must adhere to the following restrictions:
It must not allocate any V8 objects and continue iterating; it may allocate (e.g. an error message/object) and then immediately terminate the iteration.
It must not modify the array being iterated.
It must not call back into V8 (unless it can guarantee that such a call does not violate the above restrictions, which is difficult).
The {Local<Value> element} must not `escape`, i.e. must not be assigned to any other {Local}. Creating a {Global} from it, or updating a v8::TypecheckWitness with it, is safe. These restrictions may be lifted in the future if use cases arise that justify a slower but more robust implementation.
Returns {Nothing} on exception; use a {TryCatch} to catch and handle this exception. When the {callback} returns {kException}, iteration is terminated immediately, returning {Nothing}. By returning {kBreak}, the callback can request non-exceptional early termination of the iteration.
Definition at line 8317 of file api.cc.
                                                    {
  auto array = Utils::OpenDirectHandle(this);
  i::Isolate* isolate = i::Isolate::Current();
  i::FastIterateResult fast_result =
      i::FastIterateArray(array, isolate, callback, callback_data);
  if (fast_result == i::FastIterateResult::kException) return {};
  // Early breaks and completed iteration both return successfully.
  if (fast_result != i::FastIterateResult::kSlowPath) return JustVoid();
  // Slow path: retrieving elements could have side effects.
  EnterV8Scope<> api_scope{isolate, context, RCCId::kAPI_Array_Iterate};
  for (uint32_t i = 0; i < i::GetLength(*array); ++i) {
    i::DirectHandle<i::Object> element;
    if (!i::JSReceiver::GetElement(isolate, array, i).ToHandle(&element)) {
      return {};
    }
    using Result = v8::Array::CallbackResult;
    Result result = callback(i, Utils::ToLocal(element), callback_data);
    if (result == Result::kException) return {};
    if (result == Result::kBreak) return JustVoid();
  }
  return JustVoid();
}
References v8::internal::Isolate::Current(), v8::internal::FastIterateArray(), v8::internal::JSReceiver::GetElement(), v8::internal::GetLength(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::JustVoid(), v8::internal::kException, v8::debug::kException, v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Length()
uint32_t v8::Array::Length () const
Definition at line 8156 of file api.cc.
                               {
  return i::GetLength(*Utils::OpenDirectHandle(this));
}
References v8::internal::GetLength(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append(), v8_inspector::arrayToProtocolValue(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrivateMethodList(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForScopeList(), v8_inspector::generateCustomPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::getEntries(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::V8Debugger::internalProperties(), v8_inspector::objectToProtocolValue(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8_inspector::V8Console::valuesCallback(), and v8_inspector::InjectedScript::wrapTable().
New() [1/3]
Local< v8::Array > v8::Array::New (Isolate * isolate, int length = 0) [static]
Creates a JavaScript array with the given length.
If the length is negative the returned array will have length 0.
Definition at line 8091 of file api.cc.
                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Array_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  int real_length = length > 0 ? length : 0;
  i::DirectHandle<i::JSArray> obj =
      i_isolate->factory()->NewJSArray(real_length);
  i::DirectHandle<i::Number> length_obj =
      i_isolate->factory()->NewNumberFromInt(real_length);
  obj->set_length(*length_obj);
  return Utils::ToLocal(obj);
}
References v8::internal::Isolate::factory(), v8::internal::length, v8::internal::Factory::NewJSArray(), and v8::internal::FactoryBase< Impl >::NewNumberFromInt().
Referenced by v8::anonymous_namespace{d8.cc}::ChainDynamicImportPromise(), v8_inspector::V8Debugger::collectionsEntries(), v8::Shell::CreateEvaluationContext(), v8_inspector::V8Debugger::getTargetScopes(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8_inspector::V8Console::keysCallback(), v8::Object::PreviewEntries(), v8_inspector::V8Debugger::privateMethods(), v8_inspector::V8Debugger::queryObjects(), v8::Shell::System(), v8_inspector::V8Console::valuesCallback(), and v8_inspector::V8ConsoleMessage::wrapArguments().
New() [2/3]
Local< v8::Array > v8::Array::New (Isolate * isolate, Local< Value > * elements, size_t length) [static]
Creates a JavaScript array out of a Local<Value> array in C++ with a known length.
Definition at line 8104 of file api.cc.
                                               {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::Factory* factory = i_isolate->factory();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Array_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  int len = static_cast<int>(length);
  i::DirectHandle<i::FixedArray> result = factory->NewFixedArray(len);
  for (int i = 0; i < len; i++) {
    auto element = Utils::OpenDirectHandle(*elements[i]);
    result->set(i, *element);
  }
  return Utils::ToLocal(
      factory->NewJSArrayWithElements(result, i::PACKED_ELEMENTS, len));
}
References v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::Utils::OpenDirectHandle(), v8::internal::PACKED_ELEMENTS, and v8::base::internal::result.
New() [3/3]
MaybeLocal< v8::Array > v8::Array::New (Local< Context > context, size_t length, std::function< MaybeLocal< v8::Value >()> next_value_callback) [static]
Creates a JavaScript array from a provided callback.
Parameters
context The v8::Context to create the array in.
length The length of the array to be created.
next_value_callback The callback that is invoked to retrieve elements for the array. The embedder can signal that the array initialization should be aborted by throwing an exception and returning an empty MaybeLocal.
Returns
The v8::Array if all elements were constructed successfully and an empty MaybeLocal otherwise.
Definition at line 8123 of file api.cc.
                                                            {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Array_New};
  i::Isolate* i_isolate = api_scope.i_isolate();
  i::Factory* factory = i_isolate->factory();
  const int len = static_cast<int>(length);
  i::DirectHandle<i::FixedArray> backing = factory->NewFixedArray(len);
  v8::Local<v8::Value> value;
  for (int i = 0; i < len; i++) {
    MaybeLocal<v8::Value> maybe_value = next_value_callback();
    // The embedder may signal to abort creation on exception via an empty
    // local.
    if (!maybe_value.ToLocal(&value)) {
      CHECK(i_isolate->has_exception());
      return {};
    }
    backing->set(i, *Utils::OpenDirectHandle(*value));
  }
  return api_scope.Escape(Utils::ToLocal(
      factory->NewJSArrayWithElements(backing, i::PACKED_ELEMENTS, len)));
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Factory::NewJSArrayWithElements(), v8::Utils::OpenDirectHandle(), v8::internal::PACKED_ELEMENTS, v8::MaybeLocal< T >::ToLocal(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-container.h
/mnt/V8SourceCode/src/api/api.cc