cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > Class Template Reference
#include <cross-thread-persistent.h>
Classes
class UnsafeCtorTag
Public Types
using PointeeType = T
Public Member Functions
~BasicCrossThreadPersistent ()
BasicCrossThreadPersistent (const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (std::nullptr_t, const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (SentinelPointer s, const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (T *raw, const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (UnsafeCtorTag, T *raw, const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (T &raw, const SourceLocation &loc=SourceLocation::Current())
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicCrossThreadPersistent (internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > member, const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (const BasicCrossThreadPersistent &other, const SourceLocation &loc=SourceLocation::Current())
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicCrossThreadPersistent (const BasicCrossThreadPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > &other, const SourceLocation &loc=SourceLocation::Current())
BasicCrossThreadPersistent (BasicCrossThreadPersistent &&other, const SourceLocation &loc=SourceLocation::Current()) noexcept
BasicCrossThreadPersistent & operator= (const BasicCrossThreadPersistent &other)
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicCrossThreadPersistent & operator= (const BasicCrossThreadPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > &other)
BasicCrossThreadPersistent & operator= (BasicCrossThreadPersistent &&other)
BasicCrossThreadPersistent & operator= (T *other)
Assigns a raw pointer.
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicCrossThreadPersistent & operator= (internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > member)
BasicCrossThreadPersistent & operator= (std::nullptr_t)
Assigns a nullptr.
BasicCrossThreadPersistent & operator= (SentinelPointer s)
Assigns the sentinel pointer.
V8_CLANG_NO_SANITIZE (`cfi-unrelated-cast`) T *Get() const
Returns a pointer to the stored object.
void Clear ()
Clears the stored object.
T * Release ()
Returns a pointer to the stored object and releases it.
operator bool () const
Conversio to boolean.
operator T* () const
Conversion to object of type T.
T * operator-> () const
Dereferences the stored object.
T & operator* () const
template<typename U , typename OtherWeaknessPolicy = WeaknessPolicy, typename OtherLocationPolicy = LocationPolicy, typename OtherCheckingPolicy = CheckingPolicy>
BasicCrossThreadPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > To () const
template<typename U = T, typename = std::enable_if_t<!BasicCrossThreadPersistent< U, WeaknessPolicy>::IsStrongPersistent::value>>
BasicCrossThreadPersistent< U, internal::StrongCrossThreadPersistentPolicy > Lock () const
Private Member Functions
void AssignUnsafe (T *ptr)
void AssignSafe (PersistentRegionLock &, T *ptr)
void ClearFromGC () const
T * GetFromGC () const
Static Private Member Functions
static bool IsValid (const void *ptr)
static void TraceAsRoot (RootVisitor &root_visitor, const void *ptr)
Friends
class internal::RootVisitor
Additional Inherited Members
Detailed Description
template<typename T, typename WeaknessPolicy, typename LocationPolicy, typename CheckingPolicy>
class cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >
Definition at line 71 of file cross-thread-persistent.h.
Member Typedef Documentation
PointeeType
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
using cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::PointeeType = T
Definition at line 77 of file cross-thread-persistent.h.
Constructor & Destructor Documentation
 BasicCrossThreadPersistent()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent () [inline]
Definition at line 79 of file cross-thread-persistent.h.
                                {
    // This implements fast path for destroying empty/sentinel.
    //
    // Simplified version of `AssignUnsafe()` to allow calling without a
    // complete type `T`. Uses double-checked locking with a simple thread-safe
    // check for a valid handle based on a node.
    if (GetNodeSafe()) {
      PersistentRegionLock guard;
      const void* old_value = GetValue();
      // The fast path check (GetNodeSafe()) does not acquire the lock. Recheck
      // validity while holding the lock to ensure the reference has not been
      // cleared.
      if (IsValid(old_value)) {
        CrossThreadPersistentRegion& region =
            this->GetPersistentRegion(old_value);
        region.FreeNode(GetNode());
        SetNode(nullptr);
      } else {
        CPPGC_DCHECK(!GetNode());
      }
    }
    // No need to call SetValue() as the handle is not used anymore. This can
    // leave behind stale sentinel values but will always destroy the underlying
    // node.
  }
References CPPGC_DCHECK, cppgc::internal::CrossThreadPersistentRegion::FreeNode(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::CrossThreadPersistentBase::GetNodeSafe(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), and cppgc::internal::PersistentBase::SetNode().
BasicCrossThreadPersistent() [1/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 105 of file cross-thread-persistent.h.
      : LocationPolicy(loc) {}
BasicCrossThreadPersistent() [2/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (std::nullptr_t , const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 109 of file cross-thread-persistent.h.
      : LocationPolicy(loc) {}
BasicCrossThreadPersistent() [3/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (SentinelPointer s, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 113 of file cross-thread-persistent.h.
      : CrossThreadPersistentBase(s), LocationPolicy(loc) {}
BasicCrossThreadPersistent() [4/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (T * raw, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 117 of file cross-thread-persistent.h.
      : CrossThreadPersistentBase(raw), LocationPolicy(loc) {
    if (!IsValid(raw)) return;
    PersistentRegionLock guard;
    CrossThreadPersistentRegion& region = this->GetPersistentRegion(raw);
    SetNode(region.AllocateNode(this, &TraceAsRoot));
    this->CheckPointer(raw);
  }
References cppgc::internal::CrossThreadPersistentRegion::AllocateNode(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
BasicCrossThreadPersistent() [5/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (UnsafeCtorTag , T * raw, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 135 of file cross-thread-persistent.h.
      : CrossThreadPersistentBase(raw), LocationPolicy(loc) {
    if (!IsValid(raw)) return;
    CrossThreadPersistentRegion& region = this->GetPersistentRegion(raw);
    SetNode(region.AllocateNode(this, &TraceAsRoot));
    this->CheckPointer(raw);
  }
References cppgc::internal::CrossThreadPersistentRegion::AllocateNode(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
BasicCrossThreadPersistent() [6/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (T & raw, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 145 of file cross-thread-persistent.h.
      : BasicCrossThreadPersistent(&raw, loc) {}
BasicCrossThreadPersistent() [7/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > member, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 153 of file cross-thread-persistent.h.
      : BasicCrossThreadPersistent(member.Get(), loc) {}
BasicCrossThreadPersistent() [8/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (const BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > & other, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 160 of file cross-thread-persistent.h.
      : BasicCrossThreadPersistent(loc) {
    // Invoke operator=.
    *this = other;
  }
BasicCrossThreadPersistent() [9/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (const BasicCrossThreadPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > & other, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 172 of file cross-thread-persistent.h.
      : BasicCrossThreadPersistent(loc) {
    *this = other;
  }
BasicCrossThreadPersistent() [10/10]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent (BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > && other, const SourceLocation & loc = SourceLocation::Current()) [inline], [noexcept]
Definition at line 181 of file cross-thread-persistent.h.
                                                                    {
    // Invoke operator=.
    *this = std::move(other);
  }
Member Function Documentation
AssignSafe()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe (PersistentRegionLock & , T * ptr) [inline], [private]
Definition at line 386 of file cross-thread-persistent.h.
                                                 {
    PersistentRegionLock::AssertLocked();
    const void* old_value = GetValue();
    if (IsValid(old_value)) {
      CrossThreadPersistentRegion& region =
          this->GetPersistentRegion(old_value);
      if (IsValid(ptr) && (&region == &this->GetPersistentRegion(ptr))) {
        SetValue(ptr);
        this->CheckPointer(ptr);
        return;
      }
      region.FreeNode(GetNode());
      SetNode(nullptr);
    }
    SetValue(ptr);
    if (!IsValid(ptr)) return;
    SetNode(this->GetPersistentRegion(ptr).AllocateNode(this, &TraceAsRoot));
    this->CheckPointer(ptr);
  }
References cppgc::internal::PersistentRegionLock::AssertLocked(), cppgc::internal::CrossThreadPersistentRegion::FreeNode(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), cppgc::internal::PersistentBase::SetValue(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
AssignUnsafe()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe (T * ptr) [inline], [private]
Definition at line 358 of file cross-thread-persistent.h.
                            {
    const void* old_value = GetValue();
    if (IsValid(old_value)) {
      PersistentRegionLock guard;
      old_value = GetValue();
      // The fast path check (IsValid()) does not acquire the lock. Reload
      // the value to ensure the reference has not been cleared.
      if (IsValid(old_value)) {
        CrossThreadPersistentRegion& region =
            this->GetPersistentRegion(old_value);
        if (IsValid(ptr) && (&region == &this->GetPersistentRegion(ptr))) {
          SetValue(ptr);
          this->CheckPointer(ptr);
          return;
        }
        region.FreeNode(GetNode());
        SetNode(nullptr);
      } else {
        CPPGC_DCHECK(!GetNode());
      }
    }
    SetValue(ptr);
    if (!IsValid(ptr)) return;
    PersistentRegionLock guard;
    SetNode(this->GetPersistentRegion(ptr).AllocateNode(this, &TraceAsRoot));
    this->CheckPointer(ptr);
  }
References CPPGC_DCHECK, cppgc::internal::CrossThreadPersistentRegion::FreeNode(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), cppgc::internal::PersistentBase::SetValue(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
Clear()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear () [inline]
Clears the stored object.
Definition at line 281 of file cross-thread-persistent.h.
               {
    PersistentRegionLock guard;
    AssignSafe(guard, nullptr);
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Release().
ClearFromGC()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
void cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC () const [inline], [private]
Definition at line 406 of file cross-thread-persistent.h.
                           {
    if (IsValid(GetValueFromGC())) {
      WeaknessPolicy::GetPersistentRegion(GetValueFromGC())
          .FreeNode(GetNodeFromGC());
      CrossThreadPersistentBase::ClearFromGC();
    }
  }
References cppgc::internal::CrossThreadPersistentBase::ClearFromGC(), cppgc::internal::CrossThreadPersistentBase::GetNodeFromGC(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid().
GetFromGC()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T* cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::GetFromGC () const [inline], [private]
Definition at line 416 of file cross-thread-persistent.h.
                       {
    return static_cast<T*>(const_cast<void*>(GetValueFromGC()));
  }
IsValid()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
static bool cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid (const void * ptr) [inline], [static], [private]
Definition at line 350 of file cross-thread-persistent.h.
                                       {
    return ptr && ptr != kSentinelPointer;
  }
References cppgc::kSentinelPointer.
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent().
Lock()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U = T, typename = std::enable_if_t<!BasicCrossThreadPersistent< U, WeaknessPolicy>::IsStrongPersistent::value>>
BasicCrossThreadPersistent<U, internal::StrongCrossThreadPersistentPolicy> cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Lock () const [inline]
Definition at line 344 of file cross-thread-persistent.h.
               {
    return BasicCrossThreadPersistent<
        U, internal::StrongCrossThreadPersistentPolicy>(*this);
  }
References v8::base::internal::U.
operator bool()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator bool () const [inline], [explicit]
Conversio to boolean.
Note: Not thread-safe.
Returns
true if an actual object has been stored and false otherwise.
Definition at line 306 of file cross-thread-persistent.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator T*()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator T* () const [inline]
Conversion to object of type T.
Note: Not thread-safe.
Returns
the object.
Definition at line 315 of file cross-thread-persistent.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator*()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator* () const [inline]
Definition at line 323 of file cross-thread-persistent.h.
{ return *Get(); }
References v8::internal::compiler::turboshaft::Get().
operator->()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T* cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator-> () const [inline]
Dereferences the stored object.
Note: Not thread-safe.
Definition at line 322 of file cross-thread-persistent.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator=() [1/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > && other) [inline]
Definition at line 207 of file cross-thread-persistent.h.
                                                                            {
    if (this == &other) return *this;
    Clear();
    PersistentRegionLock guard;
    PersistentBase::operator=(std::move(other));
    LocationPolicy::operator=(std::move(other));
    if (!IsValid(GetValue())) return *this;
    GetNode()->UpdateOwner(this);
    other.SetValue(nullptr);
    other.SetNode(nullptr);
    this->CheckPointer(Get());
    return *this;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), v8::internal::compiler::turboshaft::Get(), cppgc::internal::PersistentBase::GetNode(), cppgc::internal::PersistentBase::GetValue(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::PersistentBase::SetNode(), cppgc::internal::PersistentBase::SetValue(), and cppgc::internal::PersistentNode::UpdateOwner().
operator=() [2/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (const BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy > & other) [inline]
Definition at line 188 of file cross-thread-persistent.h.
                                               {
    PersistentRegionLock guard;
    AssignSafe(guard, other.Get());
    return *this;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
operator=() [3/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename OtherWeaknessPolicy , typename OtherLocationPolicy , typename OtherCheckingPolicy , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (const BasicCrossThreadPersistent< U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy > & other) [inline]
Definition at line 198 of file cross-thread-persistent.h.
                                                                    {
    PersistentRegionLock guard;
    AssignSafe(guard, other.Get());
    return *this;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe().
operator=() [4/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename MemberBarrierPolicy , typename MemberWeaknessTag , typename MemberCheckingPolicy , typename MemberStorageType , typename = std::enable_if_t<std::is_base_of_v<T, U>>>
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (internal::BasicMember< U, MemberBarrierPolicy, MemberWeaknessTag, MemberCheckingPolicy, MemberStorageType > member) [inline]
Definition at line 236 of file cross-thread-persistent.h.
                  {
    return operator=(member.Get());
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
operator=() [5/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (SentinelPointer s) [inline]
Assigns the sentinel pointer.
Returns
the handle.
Definition at line 258 of file cross-thread-persistent.h.
                                                           {
    PersistentRegionLock guard;
    AssignSafe(guard, s);
    return *this;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe().
operator=() [6/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (std::nullptr_t) [inline]
Assigns a nullptr.
Returns
the handle.
Definition at line 248 of file cross-thread-persistent.h.
                                                      {
    Clear();
    return *this;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear().
operator=() [7/7]
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
BasicCrossThreadPersistent& cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator= (T * other) [inline]
Assigns a raw pointer.
Note: Not thread-safe.
Definition at line 226 of file cross-thread-persistent.h.
                                                  {
    AssignUnsafe(other);
    return *this;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe().
Release()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
T* cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Release () [inline]
Returns a pointer to the stored object and releases it.
Note: Not thread-safe.
Returns
a pointer to the stored object.
Definition at line 293 of file cross-thread-persistent.h.
               {
    T* result = Get();
    Clear();
    return result;
  }
References cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), v8::internal::compiler::turboshaft::Get(), and v8::base::internal::result.
To()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
template<typename U , typename OtherWeaknessPolicy = WeaknessPolicy, typename OtherLocationPolicy = LocationPolicy, typename OtherCheckingPolicy = CheckingPolicy>
BasicCrossThreadPersistent<U, OtherWeaknessPolicy, OtherLocationPolicy, OtherCheckingPolicy> cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::To () const [inline]
Definition at line 330 of file cross-thread-persistent.h.
             {
    using OtherBasicCrossThreadPersistent =
        BasicCrossThreadPersistent<U, OtherWeaknessPolicy, OtherLocationPolicy,
                                   OtherCheckingPolicy>;
    PersistentRegionLock guard;
    return OtherBasicCrossThreadPersistent(
        typename OtherBasicCrossThreadPersistent::UnsafeCtorTag(),
        static_cast<U*>(Get()));
  }
References v8::internal::compiler::turboshaft::Get(), and v8::base::internal::U.
TraceAsRoot()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
static void cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::TraceAsRoot (RootVisitor & root_visitor, const void * ptr) [inline], [static], [private]
Definition at line 354 of file cross-thread-persistent.h.
                                                                      {
    root_visitor.Trace(*static_cast<const BasicCrossThreadPersistent*>(ptr));
  }
References cppgc::internal::RootVisitor::Trace().
Referenced by cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent().
V8_CLANG_NO_SANITIZE()
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::V8_CLANG_NO_SANITIZE (`cfi-unrelated-cast`) const [inline]
Returns a pointer to the stored object.
Note: Not thread-safe.
Returns
a pointer to the stored object.
Definition at line 274 of file cross-thread-persistent.h.
                                                            {
    return static_cast<T*>(const_cast<void*>(GetValue()));
  }
References cppgc::internal::PersistentBase::GetValue().
Friends And Related Function Documentation
internal::RootVisitor
template<typename T , typename WeaknessPolicy , typename LocationPolicy , typename CheckingPolicy >
friend class internal::RootVisitor [friend]
Definition at line 420 of file cross-thread-persistent.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/cross-thread-persistent.h