v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder Class Reference
Classes
class EntryBuilder
Public Types
enum AssumeSpilling { kAssumeSpilling
, kAllowRegisters
, kDidSpill
 }
Public Member Functions
void NewEntry (int pc_offset, base::Vector< DebugSideTable::Entry::Value > values)
EntryBuilder * NewOOLEntry (base::Vector< DebugSideTable::Entry::Value > values)
void SetNumLocals (int num_locals)
std::unique_ptr< DebugSideTable > GenerateDebugSideTable ()
Private Types
using Entry = DebugSideTable::Entry
using Value = Entry::Value
Static Private Member Functions
static std::vector< Value > GetChangedStackValues (std::vector< Value > &last_values, base::Vector< Value > values)
Private Attributes
int num_locals_ = -1
std::vector< Value > last_values_
std::vector< EntryBuilder > entries_
std::vector< Value > last_ool_values_
std::list< EntryBuilder > ool_entries_
Detailed Description
Definition at line 198 of file liftoff-compiler.cc.
Member Typedef Documentation
Entry
using v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::Entry = DebugSideTable::Entry [private]
Definition at line 199 of file liftoff-compiler.cc.
Value
using v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::Value = Entry::Value [private]
Definition at line 200 of file liftoff-compiler.cc.
Member Enumeration Documentation
AssumeSpilling
enum v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::AssumeSpilling
Enumerator
kAssumeSpilling
kAllowRegisters
kDidSpill
Definition at line 203 of file liftoff-compiler.cc.
                      {
    // All register values will be spilled before the pc covered by the debug
    // side table entry. Register slots will be marked as stack slots in the
    // generated debug side table entry.
    kAssumeSpilling,
    // Register slots will be written out as they are.
    kAllowRegisters,
    // Register slots cannot appear since we already spilled.
    kDidSpill
  };
Member Function Documentation
GenerateDebugSideTable()
std::unique_ptr<DebugSideTable> v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::GenerateDebugSideTable () [inline]
Definition at line 271 of file liftoff-compiler.cc.
                                                         {
    DCHECK_LE(0, num_locals_);
    // Connect {entries_} and {ool_entries_} by removing redundant stack
    // information from the first {ool_entries_} entry (based on
    // {last_values_}).
    if (!entries_.empty() && !ool_entries_.empty()) {
      ool_entries_.front().MinimizeBasedOnPreviousStack(last_values_);
    }
    std::vector<Entry> entries;
    entries.reserve(entries_.size() + ool_entries_.size());
    for (auto& entry : entries_) entries.push_back(entry.ToTableEntry());
    for (auto& entry : ool_entries_) entries.push_back(entry.ToTableEntry());
    DCHECK(std::is_sorted(
        entries.begin(), entries.end(),
        [](Entry& a, Entry& b) { return a.pc_offset() < b.pc_offset(); }));
    return std::make_unique<DebugSideTable>(num_locals_, std::move(entries));
  }
References v8::internal::DCHECK(), and DCHECK_LE.
GetChangedStackValues()
static std::vector<Value> v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::GetChangedStackValues (std::vector< Value > & last_values, base::Vector< Value > values) [inline], [static], [private]
Definition at line 292 of file liftoff-compiler.cc.
                                                               {
    std::vector<Value> changed_values;
    int old_stack_size = static_cast<int>(last_values.size());
    last_values.resize(values.size());
    int index = 0;
    for (const auto& value : values) {
      if (index >= old_stack_size || last_values[index] != value) {
        changed_values.push_back(value);
        last_values[index] = value;
      }
      ++index;
    }
    return changed_values;
  }
References v8::internal::index, v8::base::Vector< T >::size(), and v8::internal::value.
NewEntry()
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::NewEntry (int pc_offset, base::Vector< DebugSideTable::Entry::Value > values) [inline]
Definition at line 250 of file liftoff-compiler.cc.
                                                             {
    entries_.emplace_back(pc_offset, static_cast<int>(values.size()),
                          GetChangedStackValues(last_values_, values));
  }
References v8::base::Vector< T >::size().
NewOOLEntry()
EntryBuilder* v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::NewOOLEntry (base::Vector< DebugSideTable::Entry::Value > values) [inline]
Definition at line 258 of file liftoff-compiler.cc.
                                                                         {
    constexpr int kNoPcOffsetYet = -1;
    ool_entries_.emplace_back(kNoPcOffsetYet, static_cast<int>(values.size()),
                              GetChangedStackValues(last_ool_values_, values));
    return &ool_entries_.back();
  }
References v8::base::Vector< T >::size().
SetNumLocals()
void v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::SetNumLocals (int num_locals) [inline]
Definition at line 265 of file liftoff-compiler.cc.
                                    {
    DCHECK_EQ(-1, num_locals_);
    DCHECK_LE(0, num_locals);
    num_locals_ = num_locals;
  }
References DCHECK_EQ, and DCHECK_LE.
Member Data Documentation
entries_
std::vector<EntryBuilder> v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::entries_ [private]
Definition at line 313 of file liftoff-compiler.cc.
last_ool_values_
std::vector<Value> v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::last_ool_values_ [private]
Definition at line 318 of file liftoff-compiler.cc.
last_values_
std::vector<Value> v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::last_values_ [private]
Definition at line 312 of file liftoff-compiler.cc.
num_locals_
int v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::num_locals_ = -1 [private]
Definition at line 309 of file liftoff-compiler.cc.
ool_entries_
std::list<EntryBuilder> v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::DebugSideTableBuilder::ool_entries_ [private]
Definition at line 319 of file liftoff-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-compiler.cc