v8::internal::maglev::ValueNode Class Reference
#include <maglev-ir.h>
Classes
struct LiveRange
Public Member Functions
ValueLocation & result ()
const ValueLocation & result () const
int use_count () const
bool is_used () const
bool unused_inputs_were_visited () const
void add_use ()
void remove_use ()
void mark_unused_inputs_visited ()
void SetHint (compiler::InstructionOperand hint)
void ClearHint ()
bool has_hint ()
template<typename RegisterT >
RegisterT GetRegisterHint ()
const compiler::InstructionOperand & hint () const
bool is_loadable () const
bool is_spilled () const
void SetNoSpill ()
void SetConstantLocation ()
void LoadToRegister (MaglevAssembler *, Register)
void LoadToRegister (MaglevAssembler *, DoubleRegister)
void DoLoadToRegister (MaglevAssembler *, Register)
void DoLoadToRegister (MaglevAssembler *, DoubleRegister)
DirectHandle< Object > Reify (LocalIsolate *isolate) const
void Spill (compiler::AllocatedOperand operand)
compiler::AllocatedOperand spill_slot () const
compiler::InstructionOperand loadable_slot () const
void record_next_use (NodeIdT id, InputLocation *input_location)
bool has_valid_live_range () const
LiveRange live_range () const
NodeIdT current_next_use () const
void advance_next_use (NodeIdT use)
bool has_no_more_uses () const
constexpr bool use_double_register () const
constexpr bool is_tagged () const
constexpr bool decompresses_tagged_result () const
constexpr ValueRepresentation value_representation () const
constexpr MachineRepresentation GetMachineRepresentation () const
compiler::OptionalHeapObjectRef TryGetConstant (compiler::JSHeapBroker *broker)
NodeType GetStaticType (compiler::JSHeapBroker *broker)
bool StaticTypeIs (compiler::JSHeapBroker *broker, NodeType type)
void InitializeRegisterData ()
void AddRegister (Register reg)
void AddRegister (DoubleRegister reg)
void RemoveRegister (Register reg)
void RemoveRegister (DoubleRegister reg)
template<typename T >
RegListBase< T > ClearRegisters ()
int num_registers () const
bool has_register () const
bool is_in_register (Register reg) const
bool is_in_register (DoubleRegister reg) const
template<typename T >
RegListBase< T > result_registers ()
compiler::InstructionOperand allocation () const
template<> RegList ClearRegisters ()
Protected Types
using ReservedField = void
Protected Member Functions
ValueNode (uint64_t bitfield)
int FirstRegisterCode () const
NodeIdT start_id () const
Protected Attributes
NodeIdT end_id_ = kInvalidNodeId
NodeIdT next_use_ = kInvalidNodeId
ValueLocation result_
xx xx xx xx xx xx xx xx xx
union {
 RegList registers_with_result_
 DoubleRegList double_registers_with_result_
};
xx xx xx xx xx xx xx xx xx
union {
 NodeIdT * last_uses_next_use_id_
 compiler::InstructionOperand spill_
};
compiler::InstructionOperand hint_
int use_count_
Private Types
using TaggedResultNeedsDecompressField = NodeBase::ReservedField
Additional Inherited Members
Detailed Description
Definition at line 2608 of file maglev-ir.h.
Member Typedef Documentation
ReservedField
using v8::internal::maglev::ValueNode::ReservedField = void [protected]
Definition at line 2613 of file maglev-ir.h.
TaggedResultNeedsDecompressField
using v8::internal::maglev::ValueNode::TaggedResultNeedsDecompressField = NodeBase::ReservedField [private]
Definition at line 2610 of file maglev-ir.h.
Constructor & Destructor Documentation
ValueNode()
v8::internal::maglev::ValueNode::ValueNode (uint64_t bitfield) [inline], [explicit], [protected]
Definition at line 2864 of file maglev-ir.h.
      : Node(bitfield),
        last_uses_next_use_id_(&next_use_),
        hint_(compiler::InstructionOperand()),
        use_count_(0)
#ifdef DEBUG
        ,
        state_(kLastUse)
#endif // DEBUG
  {
    InitializeRegisterData();
  }
References InitializeRegisterData().
Member Function Documentation
add_use()
void v8::internal::maglev::ValueNode::add_use () [inline]
Definition at line 2626 of file maglev-ir.h.
                 {
    // Make sure a saturated use count won't overflow.
    DCHECK_LT(use_count_, kMaxInt);
    use_count_++;
  }
References DCHECK_LT, v8::internal::kMaxInt, and use_count_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), and v8::internal::maglev::NodeBase::set_input().
AddRegister() [1/2]
void v8::internal::maglev::ValueNode::AddRegister (DoubleRegister reg) [inline]
Definition at line 2804 of file maglev-ir.h.
                                       {
    DCHECK(use_double_register());
    double_registers_with_result_.set(reg);
  }
References v8::internal::DCHECK(), double_registers_with_result_, v8::internal::RegListBase< RegisterT >::set(), and use_double_register().
AddRegister() [2/2]
void v8::internal::maglev::ValueNode::AddRegister (Register reg) [inline]
Definition at line 2800 of file maglev-ir.h.
                                 {
    DCHECK(!use_double_register());
    registers_with_result_.set(reg);
  }
References v8::internal::DCHECK(), registers_with_result_, v8::internal::RegListBase< RegisterT >::set(), and use_double_register().
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::SetValue(), and v8::internal::maglev::RegisterFrameState< RegisterT >::SetValueWithoutBlocking().
advance_next_use()
void v8::internal::maglev::ValueNode::advance_next_use (NodeIdT use) [inline]
Definition at line 2724 of file maglev-ir.h.
{ next_use_ = use; }
References next_use_, and use().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse().
allocation()
compiler::InstructionOperand v8::internal::maglev::ValueNode::allocation () const [inline]
Definition at line 2853 of file maglev-ir.h.
                                                {
    if (has_register()) {
      return compiler::AllocatedOperand(compiler::LocationOperand::REGISTER,
                                        GetMachineRepresentation(),
                                        FirstRegisterCode());
    }
    CHECK(is_loadable());
    return spill_;
  }
References CHECK, FirstRegisterCode(), GetMachineRepresentation(), has_register(), is_loadable(), v8::internal::compiler::LocationOperand::REGISTER, and spill_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignAnyInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::maglev::StraightForwardRegisterAllocator::InitializeBranchTargetPhis(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::RecordMoves().
ClearHint()
void v8::internal::maglev::ValueNode::ClearHint () [inline]
Definition at line 2641 of file maglev-ir.h.
{ hint_ = compiler::InstructionOperand(); }
References hint_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), and v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput().
ClearRegisters() [1/2]
template<typename T >
RegListBase<T> v8::internal::maglev::ValueNode::ClearRegisters () [inline]
Referenced by v8::internal::maglev::RegisterFrameState< RegisterT >::FreeRegistersUsedBy().
ClearRegisters() [2/2]
template<>
DoubleRegList v8::internal::maglev::ValueNode::ClearRegisters () [inline]
Definition at line 2923 of file maglev-ir.h.
                                         {
  DCHECK(!use_double_register());
  return std::exchange(registers_with_result_, kEmptyRegList);
}
References v8::internal::DCHECK(), v8::internal::kEmptyRegList, registers_with_result_, and use_double_register().
current_next_use()
NodeIdT v8::internal::maglev::ValueNode::current_next_use () const [inline]
Definition at line 2720 of file maglev-ir.h.
{ return next_use_; }
References next_use_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
decompresses_tagged_result()
constexpr bool v8::internal::maglev::ValueNode::decompresses_tagged_result () const [inline], [constexpr]
Definition at line 2760 of file maglev-ir.h.
{ return false; }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToRegister(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::RecordMoveToStackSlot().
DoLoadToRegister() [1/2]
void v8::internal::maglev::ValueNode::DoLoadToRegister (MaglevAssembler * , DoubleRegister)
DoLoadToRegister() [2/2]
void v8::internal::maglev::ValueNode::DoLoadToRegister (MaglevAssembler * , Register)
FirstRegisterCode()
int v8::internal::maglev::ValueNode::FirstRegisterCode () const [inline], [protected]
Definition at line 2877 of file maglev-ir.h.
                                {
    if (use_double_register()) {
      return double_registers_with_result_.first().code();
    }
    return registers_with_result_.first().code();
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), double_registers_with_result_, v8::internal::RegListBase< RegisterT >::first(), registers_with_result_, and use_double_register().
Referenced by allocation().
GetMachineRepresentation()
constexpr MachineRepresentation v8::internal::maglev::ValueNode::GetMachineRepresentation () const [inline], [constexpr]
Definition at line 2767 of file maglev-ir.h.
                                                                   {
    switch (properties().value_representation()) {
      case ValueRepresentation::kTagged:
        return MachineRepresentation::kTagged;
      case ValueRepresentation::kInt32:
      case ValueRepresentation::kUint32:
        return MachineRepresentation::kWord32;
      case ValueRepresentation::kIntPtr:
        return MachineType::PointerRepresentation();
      case ValueRepresentation::kFloat64:
        return MachineRepresentation::kFloat64;
      case ValueRepresentation::kHoleyFloat64:
        return MachineRepresentation::kFloat64;
    }
  }
References v8::internal::kFloat64, v8::internal::maglev::kFloat64, v8::internal::maglev::kHoleyFloat64, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::kTagged, v8::internal::maglev::kTagged, v8::internal::maglev::kUint32, v8::internal::kWord32, v8::internal::MachineType::PointerRepresentation(), v8::internal::maglev::NodeBase::properties(), and value_representation().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot(), allocation(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads(), and v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::OperandForNodeRegister().
GetRegisterHint()
template<typename RegisterT >
RegisterT v8::internal::maglev::ValueNode::GetRegisterHint () [inline]
Definition at line 2646 of file maglev-ir.h.
                              {
    if (hint_.IsInvalid()) return RegisterT::no_reg();
    return RegisterT::from_code(
        compiler::UnallocatedOperand::cast(hint_).fixed_register_index());
  }
References hint_, and v8::internal::no_reg.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters(), and v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads().
GetStaticType()
NodeType v8::internal::maglev::ValueNode::GetStaticType (compiler::JSHeapBroker * broker)
Definition at line 515 of file maglev-ir.cc.
                                                              {
  switch (properties().value_representation()) {
    case ValueRepresentation::kInt32:
    case ValueRepresentation::kUint32:
    case ValueRepresentation::kFloat64:
    case ValueRepresentation::kIntPtr:
      return NodeType::kNumber;
    case ValueRepresentation::kHoleyFloat64:
      return NodeType::kNumberOrOddball;
    case ValueRepresentation::kTagged:
      break;
  }
  switch (opcode()) {
    case Opcode::kPhi:
      return Cast<Phi>()->type();
    case Opcode::kCheckedSmiTagInt32:
    case Opcode::kCheckedSmiTagUint32:
    case Opcode::kCheckedSmiTagIntPtr:
    case Opcode::kCheckedSmiTagFloat64:
    case Opcode::kUnsafeSmiTagInt32:
    case Opcode::kUnsafeSmiTagUint32:
    case Opcode::kUnsafeSmiTagIntPtr:
    case Opcode::kSmiConstant:
      return NodeType::kSmi;
    case Opcode::kInt32ToNumber:
    case Opcode::kUint32ToNumber:
    case Opcode::kIntPtrToNumber:
    case Opcode::kFloat64ToTagged:
      return NodeType::kNumber;
    case Opcode::kHoleyFloat64ToTagged:
      return NodeType::kNumberOrOddball;
    case Opcode::kAllocationBlock:
    case Opcode::kInlinedAllocation: {
      auto obj = Cast<InlinedAllocation>()->object();
      if (obj->has_static_map()) {
        return StaticTypeForMap(obj->map(), broker);
      } else {
        switch (obj->type()) {
          case VirtualObject::kConsString:
            return NodeType::kString;
          case VirtualObject::kDefault:
          case VirtualObject::kHeapNumber:
          case VirtualObject::kFixedDoubleArray:
            UNREACHABLE();
        }
      }
    }
    case Opcode::kRootConstant: {
      RootConstant* constant = Cast<RootConstant>();
      switch (constant->index()) {
        case RootIndex::kTrueValue:
        case RootIndex::kFalseValue:
          return NodeType::kBoolean;
        case RootIndex::kUndefinedValue:
        case RootIndex::kNullValue:
          return NodeType::kOddball;
        default:
          break;
      }
      [[fallthrough]];
    }
    case Opcode::kConstant: {
      compiler::HeapObjectRef ref = TryGetConstant(broker).value();
      return StaticTypeForConstant(broker, ref);
    }
    case Opcode::kToNumberOrNumeric:
      if (Cast<ToNumberOrNumeric>()->mode() == Object::Conversion::kToNumber) {
        return NodeType::kNumber;
      }
      // TODO(verwaest): Check what we need here.
      return NodeType::kUnknown;
    case Opcode::kBuiltinStringPrototypeCharCodeOrCodePointAt:
    case Opcode::kBuiltinSeqOneByteStringCharCodeAt:
      return NodeType::kNumber;
    case Opcode::kToString:
    case Opcode::kNumberToString:
    case Opcode::kUnwrapStringWrapper:
    case Opcode::kStringAt:
    case Opcode::kStringConcat:
    case Opcode::kBuiltinStringFromCharCode:
      return NodeType::kString;
    case Opcode::kCheckedInternalizedString:
      return NodeType::kInternalizedString;
    case Opcode::kSeqOneByteStringAt:
      // Seq one-byte StringAt will always return an internalized string from
      // the single character roots.
      return NodeType::kROSeqInternalizedOneByteString;
    case Opcode::kToObject:
    case Opcode::kCreateObjectLiteral:
    case Opcode::kCreateShallowObjectLiteral:
      return NodeType::kJSReceiver;
    case Opcode::kCreateArrayLiteral:
    case Opcode::kCreateShallowArrayLiteral:
      return NodeType::kJSArray;
    case Opcode::kToName:
      return NodeType::kName;
    case Opcode::kFastCreateClosure:
    case Opcode::kCreateClosure:
      return NodeType::kJSFunction;
    case Opcode::kInt32Compare:
    case Opcode::kFloat64Compare:
    case Opcode::kGenericEqual:
    case Opcode::kGenericStrictEqual:
    case Opcode::kGenericLessThan:
    case Opcode::kGenericLessThanOrEqual:
    case Opcode::kGenericGreaterThan:
    case Opcode::kGenericGreaterThanOrEqual:
    case Opcode::kLogicalNot:
    case Opcode::kStringEqual:
    case Opcode::kTaggedEqual:
    case Opcode::kTaggedNotEqual:
    case Opcode::kTestInstanceOf:
    case Opcode::kTestTypeOf:
    case Opcode::kTestUndetectable:
    case Opcode::kToBoolean:
    case Opcode::kToBooleanLogicalNot:
    case Opcode::kIntPtrToBoolean:
    case Opcode::kSetPrototypeHas:
      return NodeType::kBoolean;
    case Opcode::kCreateFunctionContext:
      return NodeType::kContext;
    case Opcode::kCallRuntime:
      switch (Cast<CallRuntime>()->function_id()) {
        case Runtime::kPushBlockContext:
        case Runtime::kPushCatchContext:
        case Runtime::kNewFunctionContext:
          return NodeType::kContext;
        default:
          return NodeType::kUnknown;
      }
      UNREACHABLE();
      // Not value nodes:
#define GENERATE_CASE(Name) case Opcode::k##Name:
      CONTROL_NODE_LIST(GENERATE_CASE)
      NON_VALUE_NODE_LIST(GENERATE_CASE)
#undef GENERATE_CASE
      UNREACHABLE();
    case Opcode::kCreateFastArrayElements:
    case Opcode::kTransitionElementsKind:
    // Unsorted value nodes. TODO(maglev): See which of these should return
    // something else than kUnknown.
    case Opcode::kIdentity:
    case Opcode::kArgumentsElements:
    case Opcode::kArgumentsLength:
    case Opcode::kRestLength:
    case Opcode::kCall:
    case Opcode::kCallBuiltin:
    case Opcode::kCallCPPBuiltin:
    case Opcode::kCallForwardVarargs:
    case Opcode::kCallWithArrayLike:
    case Opcode::kCallWithSpread:
    case Opcode::kCallKnownApiFunction:
    case Opcode::kCallKnownJSFunction:
    case Opcode::kCallSelf:
    case Opcode::kConstruct:
    case Opcode::kCheckConstructResult:
    case Opcode::kCheckDerivedConstructResult:
    case Opcode::kConstructWithSpread:
    case Opcode::kConvertReceiver:
    case Opcode::kConvertHoleToUndefined:
    case Opcode::kCreateRegExpLiteral:
    case Opcode::kDeleteProperty:
    case Opcode::kEnsureWritableFastElements:
    case Opcode::kExtendPropertiesBackingStore:
    case Opcode::kForInPrepare:
    case Opcode::kForInNext:
    case Opcode::kGeneratorRestoreRegister:
    case Opcode::kGetIterator:
    case Opcode::kGetSecondReturnedValue:
    case Opcode::kGetTemplateObject:
    case Opcode::kHasInPrototypeChain:
    case Opcode::kInitialValue:
    case Opcode::kLoadTaggedField:
    case Opcode::kLoadTaggedFieldForProperty:
    case Opcode::kLoadTaggedFieldForContextSlotNoCells:
    case Opcode::kLoadTaggedFieldForContextSlot:
    case Opcode::kLoadDoubleField:
    case Opcode::kLoadFloat64:
    case Opcode::kLoadInt32:
    case Opcode::kLoadTaggedFieldByFieldIndex:
    case Opcode::kLoadFixedArrayElement:
    case Opcode::kLoadFixedDoubleArrayElement:
    case Opcode::kLoadHoleyFixedDoubleArrayElement:
    case Opcode::kLoadHoleyFixedDoubleArrayElementCheckedNotHole:
    case Opcode::kLoadSignedIntDataViewElement:
    case Opcode::kLoadDoubleDataViewElement:
    case Opcode::kLoadTypedArrayLength:
    case Opcode::kLoadSignedIntTypedArrayElement:
    case Opcode::kLoadUnsignedIntTypedArrayElement:
    case Opcode::kLoadDoubleTypedArrayElement:
    case Opcode::kLoadSignedIntConstantTypedArrayElement:
    case Opcode::kLoadUnsignedIntConstantTypedArrayElement:
    case Opcode::kLoadDoubleConstantTypedArrayElement:
    case Opcode::kLoadEnumCacheLength:
    case Opcode::kLoadGlobal:
    case Opcode::kLoadNamedGeneric:
    case Opcode::kLoadNamedFromSuperGeneric:
    case Opcode::kMaybeGrowFastElements:
    case Opcode::kMigrateMapIfNeeded:
    case Opcode::kSetNamedGeneric:
    case Opcode::kDefineNamedOwnGeneric:
    case Opcode::kStoreInArrayLiteralGeneric:
    case Opcode::kStoreGlobal:
    case Opcode::kGetKeyedGeneric:
    case Opcode::kSetKeyedGeneric:
    case Opcode::kDefineKeyedOwnGeneric:
    case Opcode::kRegisterInput:
    case Opcode::kCheckedSmiSizedInt32:
    case Opcode::kCheckedSmiUntag:
    case Opcode::kUnsafeSmiUntag:
    case Opcode::kCheckedObjectToIndex:
    case Opcode::kCheckedTruncateNumberOrOddballToInt32:
    case Opcode::kCheckedInt32ToUint32:
    case Opcode::kCheckedIntPtrToUint32:
    case Opcode::kUnsafeInt32ToUint32:
    case Opcode::kCheckedUint32ToInt32:
    case Opcode::kCheckedIntPtrToInt32:
    case Opcode::kChangeInt32ToFloat64:
    case Opcode::kChangeUint32ToFloat64:
    case Opcode::kChangeIntPtrToFloat64:
    case Opcode::kCheckedTruncateFloat64ToInt32:
    case Opcode::kCheckedTruncateFloat64ToUint32:
    case Opcode::kTruncateNumberOrOddballToInt32:
    case Opcode::kCheckedNumberToInt32:
    case Opcode::kTruncateUint32ToInt32:
    case Opcode::kTruncateFloat64ToInt32:
    case Opcode::kUnsafeTruncateUint32ToInt32:
    case Opcode::kUnsafeTruncateFloat64ToInt32:
    case Opcode::kInt32ToUint8Clamped:
    case Opcode::kUint32ToUint8Clamped:
    case Opcode::kFloat64ToUint8Clamped:
    case Opcode::kCheckedNumberToUint8Clamped:
    case Opcode::kFloat64ToHeapNumberForField:
    case Opcode::kCheckedNumberOrOddballToFloat64:
    case Opcode::kUncheckedNumberOrOddballToFloat64:
    case Opcode::kCheckedNumberOrOddballToHoleyFloat64:
    case Opcode::kCheckedHoleyFloat64ToFloat64:
    case Opcode::kHoleyFloat64ToMaybeNanFloat64:
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case Opcode::kFloat64ToHoleyFloat64:
    case Opcode::kConvertHoleNanToUndefinedNan:
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    case Opcode::kHoleyFloat64IsHole:
    case Opcode::kSetPendingMessage:
    case Opcode::kStringLength:
    case Opcode::kAllocateElementsArray:
    case Opcode::kUpdateJSArrayLength:
    case Opcode::kVirtualObject:
    case Opcode::kGetContinuationPreservedEmbedderData:
    case Opcode::kFloat64Constant:
    case Opcode::kInt32Constant:
    case Opcode::kUint32Constant:
    case Opcode::kIntPtrConstant:
    case Opcode::kTaggedIndexConstant:
    case Opcode::kTrustedConstant:
    case Opcode::kInt32AbsWithOverflow:
    case Opcode::kInt32AddWithOverflow:
    case Opcode::kInt32SubtractWithOverflow:
    case Opcode::kInt32MultiplyWithOverflow:
    case Opcode::kInt32DivideWithOverflow:
    case Opcode::kInt32ModulusWithOverflow:
    case Opcode::kInt32BitwiseAnd:
    case Opcode::kInt32BitwiseOr:
    case Opcode::kInt32BitwiseXor:
    case Opcode::kInt32ShiftLeft:
    case Opcode::kInt32ShiftRight:
    case Opcode::kInt32ShiftRightLogical:
    case Opcode::kInt32BitwiseNot:
    case Opcode::kInt32NegateWithOverflow:
    case Opcode::kInt32IncrementWithOverflow:
    case Opcode::kInt32DecrementWithOverflow:
    case Opcode::kInt32ToBoolean:
    case Opcode::kFloat64Abs:
    case Opcode::kFloat64Add:
    case Opcode::kFloat64Subtract:
    case Opcode::kFloat64Multiply:
    case Opcode::kFloat64Divide:
    case Opcode::kFloat64Exponentiate:
    case Opcode::kFloat64Modulus:
    case Opcode::kFloat64Negate:
    case Opcode::kFloat64Round:
    case Opcode::kFloat64ToBoolean:
    case Opcode::kFloat64Ieee754Unary:
    case Opcode::kInt32CountLeadingZeros:
    case Opcode::kSmiCountLeadingZeros:
    case Opcode::kFloat64CountLeadingZeros:
    case Opcode::kCheckedSmiIncrement:
    case Opcode::kCheckedSmiDecrement:
    case Opcode::kGenericAdd:
    case Opcode::kGenericSubtract:
    case Opcode::kGenericMultiply:
    case Opcode::kGenericDivide:
    case Opcode::kGenericModulus:
    case Opcode::kGenericExponentiate:
    case Opcode::kGenericBitwiseAnd:
    case Opcode::kGenericBitwiseOr:
    case Opcode::kGenericBitwiseXor:
    case Opcode::kGenericShiftLeft:
    case Opcode::kGenericShiftRight:
    case Opcode::kGenericShiftRightLogical:
    case Opcode::kGenericBitwiseNot:
    case Opcode::kGenericNegate:
    case Opcode::kGenericIncrement:
    case Opcode::kGenericDecrement:
    case Opcode::kConsStringMap:
    case Opcode::kMapPrototypeGet:
    case Opcode::kMapPrototypeGetInt32Key:
      return NodeType::kUnknown;
  }
}
References broker(), CONTROL_NODE_LIST, GENERATE_CASE, v8::internal::maglev::RootConstant::index(), v8::internal::maglev::VirtualObject::kConsString, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::maglev::VirtualObject::kDefault, v8::internal::maglev::VirtualObject::kFixedDoubleArray, v8::internal::maglev::kFloat64, v8::internal::maglev::VirtualObject::kHeapNumber, v8::internal::maglev::kHoleyFloat64, v8::internal::anonymous_namespace{assert-scope.cc}::kInitialValue, v8::internal::maglev::kInt32, v8::internal::maglev::kIntPtr, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::compiler::kSmi, v8::internal::maglev::kTagged, v8::internal::Object::kToNumber, v8::internal::maglev::kUint32, mode(), NON_VALUE_NODE_LIST, v8::internal::maglev::NodeBase::opcode(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::StaticTypeForConstant(), v8::internal::maglev::StaticTypeForMap(), TryGetConstant(), v8::internal::UNREACHABLE(), and value_representation().
Referenced by v8::internal::maglev::KnownNodeAspects::CheckType(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::KnownNodeAspects::EnsureType(), v8::internal::maglev::KnownNodeAspects::GetOrCreateInfoFor(), v8::internal::maglev::KnownNodeAspects::GetType(), v8::internal::maglev::KnownNodeAspects::MayBeNullOrUndefined(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObjectValue(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), and StaticTypeIs().
has_hint()
bool v8::internal::maglev::ValueNode::has_hint () [inline]
Definition at line 2643 of file maglev-ir.h.
{ return !hint_.IsInvalid(); }
References hint_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult().
has_no_more_uses()
bool v8::internal::maglev::ValueNode::has_no_more_uses () const [inline]
Definition at line 2726 of file maglev-ir.h.
{ return next_use_ == kInvalidNodeId; }
References v8::internal::maglev::kInvalidNodeId, and next_use_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), and v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse().
has_register()
bool v8::internal::maglev::ValueNode::has_register () const [inline]
Definition at line 2827 of file maglev-ir.h.
                            {
    if (use_double_register()) {
      return double_registers_with_result_ != kEmptyDoubleRegList;
    }
    return registers_with_result_ != kEmptyRegList;
  }
References double_registers_with_result_, v8::internal::kEmptyDoubleRegList, v8::internal::kEmptyRegList, registers_with_result_, and use_double_register().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), allocation(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopSpills(), and v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues().
has_valid_live_range()
bool v8::internal::maglev::ValueNode::has_valid_live_range () const [inline]
Definition at line 2718 of file maglev-ir.h.
{ return end_id_ != 0; }
References end_id_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), and record_next_use().
hint()
const compiler::InstructionOperand& v8::internal::maglev::ValueNode::hint () const [inline]
Definition at line 2652 of file maglev-ir.h.
                                                 {
    DCHECK(hint_.IsInvalid() || hint_.IsUnallocated());
    return hint_;
  }
References v8::internal::DCHECK(), and hint_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisterAtEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint(), and SetHint().
InitializeRegisterData()
void v8::internal::maglev::ValueNode::InitializeRegisterData () [inline]
Definition at line 2792 of file maglev-ir.h.
                                {
    if (use_double_register()) {
      double_registers_with_result_ = kEmptyDoubleRegList;
    } else {
      registers_with_result_ = kEmptyRegList;
    }
  }
References double_registers_with_result_, v8::internal::kEmptyDoubleRegList, v8::internal::kEmptyRegList, registers_with_result_, and use_double_register().
Referenced by ValueNode().
is_in_register() [1/2]
bool v8::internal::maglev::ValueNode::is_in_register (DoubleRegister reg) const [inline]
Definition at line 2837 of file maglev-ir.h.
                                                {
    DCHECK(use_double_register());
    return double_registers_with_result_.has(reg);
  }
References v8::internal::DCHECK(), double_registers_with_result_, v8::internal::RegListBase< RegisterT >::has(), and use_double_register().
is_in_register() [2/2]
bool v8::internal::maglev::ValueNode::is_in_register (Register reg) const [inline]
Definition at line 2833 of file maglev-ir.h.
                                          {
    DCHECK(!use_double_register());
    return registers_with_result_.has(reg);
  }
References v8::internal::DCHECK(), v8::internal::RegListBase< RegisterT >::has(), registers_with_result_, and use_double_register().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::VerifyRegisterState().
is_loadable()
bool v8::internal::maglev::ValueNode::is_loadable () const [inline]
Definition at line 2657 of file maglev-ir.h.
                           {
    DCHECK_EQ(state_, kSpill);
    return spill_.IsConstant() || spill_.IsAnyStackSlot();
  }
References DCHECK_EQ, v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), and spill_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateEagerDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot(), allocation(), v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads(), loadable_slot(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), Spill(), and v8::internal::maglev::StraightForwardRegisterAllocator::Spill().
is_spilled()
bool v8::internal::maglev::ValueNode::is_spilled () const [inline]
Definition at line 2662 of file maglev-ir.h.
                          {
    DCHECK_EQ(state_, kSpill);
    return spill_.IsAnyStackSlot();
  }
References DCHECK_EQ, v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), and spill_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), spill_slot(), and v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse().
is_tagged()
constexpr bool v8::internal::maglev::ValueNode::is_tagged () const [inline], [constexpr]
Definition at line 2732 of file maglev-ir.h.
                                   {
    return (properties().value_representation() ==
            ValueRepresentation::kTagged);
  }
References v8::internal::maglev::kTagged, v8::internal::maglev::NodeBase::properties(), and value_representation().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfRootConstant(), v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfUndefinedOrNull(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckNotHole(), v8::internal::maglev::MaglevGraphBuilder::BuildConvertHoleToUndefined(), v8::internal::maglev::MaglevPhiRepresentationSelector::EnsurePhiInputsTagged(), v8::internal::maglev::MaglevGraphBuilder::TryReduceArrayIteratingBuiltin(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceGetIterator().
is_used()
bool v8::internal::maglev::ValueNode::is_used () const [inline]
Definition at line 2624 of file maglev-ir.h.
{ return use_count_ > 0; }
References use_count_.
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses(), and v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult().
live_range()
LiveRange v8::internal::maglev::ValueNode::live_range () const [inline]
Definition at line 2719 of file maglev-ir.h.
{ return {start_id(), end_id_}; }
References end_id_, and start_id().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot(), v8::internal::maglev::StraightForwardRegisterAllocator::IsCurrentNodeLastUseOf(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::IsLiveAtTarget(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), and v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse().
loadable_slot()
compiler::InstructionOperand v8::internal::maglev::ValueNode::loadable_slot () const [inline]
Definition at line 2696 of file maglev-ir.h.
                                                   {
    DCHECK_EQ(state_, kSpill);
    DCHECK(is_loadable());
    return spill_;
  }
References v8::internal::DCHECK(), DCHECK_EQ, is_loadable(), and spill_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateLazyDeopt(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads(), v8::internal::maglev::StraightForwardRegisterAllocator::MergeRegisterValues(), and spill_slot().
LoadToRegister() [1/2]
void v8::internal::maglev::ValueNode::LoadToRegister (MaglevAssembler * , DoubleRegister)
LoadToRegister() [2/2]
void v8::internal::maglev::ValueNode::LoadToRegister (MaglevAssembler * , Register)
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ParallelMoveResolver< RegisterT, DecompressIfNeeded >::EmitMoves(), v8::internal::maglev::MaglevAssembler::FromAnyToRegister(), v8::internal::maglev::detail::PushInput(), and v8::internal::maglev::detail::ToRegister().
mark_unused_inputs_visited()
void v8::internal::maglev::ValueNode::mark_unused_inputs_visited () [inline]
Definition at line 2634 of file maglev-ir.h.
                                    {
    DCHECK_EQ(use_count_, 0);
    use_count_ = -1;
  }
References DCHECK_EQ, and use_count_.
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses().
num_registers()
int v8::internal::maglev::ValueNode::num_registers () const [inline]
Definition at line 2821 of file maglev-ir.h.
                            {
    if (use_double_register()) {
      return double_registers_with_result_.Count();
    }
    return registers_with_result_.Count();
  }
References v8::internal::RegListBase< RegisterT >::Count(), double_registers_with_result_, registers_with_result_, and use_double_register().
record_next_use()
void v8::internal::maglev::ValueNode::record_next_use (NodeIdT id, InputLocation * input_location) [inline]
Definition at line 2702 of file maglev-ir.h.
                                                                  {
    DCHECK_EQ(state_, kLastUse);
    DCHECK_NE(id, kInvalidNodeId);
    DCHECK_LT(start_id(), id);
    DCHECK_IMPLIES(has_valid_live_range(), id >= end_id_);
    end_id_ = id;
    *last_uses_next_use_id_ = id;
    last_uses_next_use_id_ = input_location->get_next_use_id_address();
    DCHECK_EQ(*last_uses_next_use_id_, kInvalidNodeId);
  }
References DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LT, DCHECK_NE, end_id_, v8::internal::maglev::InputLocation::get_next_use_id_address(), has_valid_live_range(), v8::internal::maglev::NodeBase::id(), v8::internal::maglev::kInvalidNodeId, last_uses_next_use_id_, and start_id().
Referenced by v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkUse().
Reify()
DirectHandle< Object > v8::internal::maglev::ValueNode::Reify (LocalIsolate * isolate) const
Definition at line 1195 of file maglev-ir.cc.
                                                                 {
  switch (opcode()) {
#define V(Name) \
  case Opcode::k##Name: \
    return this->Cast<Name>()->DoReify(isolate);
    CONSTANT_VALUE_NODE_LIST(V)
#undef V
    default:
      UNREACHABLE();
  }
}
References CONSTANT_VALUE_NODE_LIST, v8::internal::maglev::NodeBase::opcode(), and v8::internal::UNREACHABLE().
remove_use()
void v8::internal::maglev::ValueNode::remove_use () [inline]
Definition at line 128 of file maglev-ir-inl.h.
                           {
  // Make sure a saturated use count won't drop below zero.
  DCHECK_GT(use_count_, 0);
  use_count_--;
  if (auto alloc = TryCast<InlinedAllocation>()) {
    // Unfortunately we cannot know if the removed use was escaping or not. To
    // be safe we need to assume it wasn't.
    alloc->RemoveNonEscapingUses(1);
  }
}
References DCHECK_GT, and use_count_.
Referenced by v8::internal::maglev::NodeBase::change_input(), v8::internal::maglev::Input::clear(), and v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses().
RemoveRegister() [1/2]
void v8::internal::maglev::ValueNode::RemoveRegister (DoubleRegister reg) [inline]
Definition at line 2813 of file maglev-ir.h.
                                          {
    DCHECK(use_double_register());
    double_registers_with_result_.clear(reg);
  }
References v8::internal::RegListBase< RegisterT >::clear(), v8::internal::DCHECK(), double_registers_with_result_, and use_double_register().
RemoveRegister() [2/2]
void v8::internal::maglev::ValueNode::RemoveRegister (Register reg) [inline]
Definition at line 2809 of file maglev-ir.h.
                                    {
    DCHECK(!use_double_register());
    registers_with_result_.clear(reg);
  }
References v8::internal::RegListBase< RegisterT >::clear(), v8::internal::DCHECK(), registers_with_result_, and use_double_register().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValue(), and v8::internal::maglev::StraightForwardRegisterAllocator::DropRegisterValueAtEnd().
result() [1/2]
ValueLocation& v8::internal::maglev::ValueNode::result () [inline]
Definition at line 2616 of file maglev-ir.h.
{ return result_; }
References result_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::GetReservedRegisters(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::InputHint(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::SameAsInput(), and SetConstantLocation().
result() [2/2]
const ValueLocation& v8::internal::maglev::ValueNode::result () const [inline]
Definition at line 2617 of file maglev-ir.h.
{ return result_; }
References result_.
result_registers()
template<typename T >
RegListBase<T> v8::internal::maglev::ValueNode::result_registers () [inline]
Definition at line 2843 of file maglev-ir.h.
                                    {
    if constexpr (std::is_same_v<T, DoubleRegister>) {
      DCHECK(use_double_register());
      return double_registers_with_result_;
    } else {
      DCHECK(!use_double_register());
      return registers_with_result_;
    }
  }
References v8::internal::DCHECK(), double_registers_with_result_, registers_with_result_, and use_double_register().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopSpills(), v8::internal::maglev::RegisterFrameState< RegisterT >::TryChooseInputRegister(), v8::internal::maglev::RegisterFrameState< RegisterT >::TryChooseUnblockedInputRegister(), and v8::internal::maglev::StraightForwardRegisterAllocator::VerifyRegisterState().
SetConstantLocation()
void v8::internal::maglev::ValueNode::SetConstantLocation ()
Definition at line 493 of file maglev-ir.cc.
                                    {
  DCHECK(IsConstantNode(opcode()));
#ifdef DEBUG
  state_ = kSpill;
#endif // DEBUG
  spill_ = compiler::ConstantOperand(
      compiler::UnallocatedOperand::cast(result().operand())
          .virtual_register());
}
References v8::internal::DCHECK(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::NodeBase::opcode(), result(), and spill_.
SetHint()
void v8::internal::maglev::ValueNode::SetHint (compiler::InstructionOperand hint)
Definition at line 467 of file maglev-ir.cc.
                                                       {
  if (!hint_.IsInvalid()) return;
  hint_ = hint;
  if (result_.operand().IsUnallocated()) {
    auto operand = compiler::UnallocatedOperand::cast(result_.operand());
    if (operand.HasSameAsInputPolicy()) {
      input(operand.input_index()).node()->SetHint(hint);
    }
  }
  if (this->Is<Phi>()) {
    for (Input& input : *this) {
      if (input.node()->has_id() && input.node()->id() < this->id()) {
        input.node()->SetHint(hint);
      }
    }
  }
}
References v8::internal::maglev::NodeBase::has_id(), hint(), hint_, v8::internal::maglev::NodeBase::id(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::Input::node(), v8::internal::maglev::ValueLocation::operand(), result_, SetHint(), and v8::internal::this.
Referenced by SetHint(), and v8::internal::maglev::UseFixed().
SetNoSpill()
void v8::internal::maglev::ValueNode::SetNoSpill ()
Definition at line 485 of file maglev-ir.cc.
                           {
  DCHECK(!IsConstantNode(opcode()));
#ifdef DEBUG
  state_ = kSpill;
#endif // DEBUG
  spill_ = compiler::InstructionOperand();
}
References v8::internal::DCHECK(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::NodeBase::opcode(), and spill_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult().
Spill()
void v8::internal::maglev::ValueNode::Spill (compiler::AllocatedOperand operand) [inline]
Definition at line 2677 of file maglev-ir.h.
                                               {
#ifdef DEBUG
    if (state_ == kLastUse) {
      state_ = kSpill;
    } else {
      DCHECK(!is_loadable());
    }
#endif // DEBUG
    DCHECK(!IsConstantNode(opcode()));
    DCHECK(operand.IsAnyStackSlot());
    spill_ = operand;
    DCHECK(spill_.IsAnyStackSlot());
  }
References v8::internal::DCHECK(), is_loadable(), v8::internal::compiler::InstructionOperand::IsAnyStackSlot(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::NodeBase::opcode(), and spill_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), and v8::internal::maglev::StraightForwardRegisterAllocator::AllocateSpillSlot().
spill_slot()
compiler::AllocatedOperand v8::internal::maglev::ValueNode::spill_slot () const [inline]
Definition at line 2691 of file maglev-ir.h.
                                              {
    DCHECK(is_spilled());
    return compiler::AllocatedOperand::cast(loadable_slot());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), is_spilled(), and loadable_slot().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::StraightForwardRegisterAllocator::Spill(), and v8::internal::maglev::StraightForwardRegisterAllocator::UpdateUse().
start_id()
NodeIdT v8::internal::maglev::ValueNode::start_id () const [inline], [protected]
Definition at line 2885 of file maglev-ir.h.
{ return id(); }
References v8::internal::maglev::NodeBase::id().
Referenced by live_range(), and record_next_use().
StaticTypeIs()
bool v8::internal::maglev::ValueNode::StaticTypeIs (compiler::JSHeapBroker * broker, NodeType type) [inline]
Definition at line 2788 of file maglev-ir.h.
                                                                 {
    return NodeTypeIs(GetStaticType(broker), type);
  }
References broker(), GetStaticType(), v8::internal::maglev::NodeTypeIs(), and v8::internal::tracing::type.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCheckSmi(), v8::internal::maglev::KnownNodeAspects::CheckTypes(), and v8::internal::maglev::KnownNodeAspects::EnsureType().
TryGetConstant()
compiler::OptionalHeapObjectRef v8::internal::maglev::ValueNode::TryGetConstant (compiler::JSHeapBroker * broker)
Definition at line 503 of file maglev-ir.cc.
                                  {
  if (Constant* c = TryCast<Constant>()) {
    return c->object();
  }
  if (RootConstant* c = TryCast<RootConstant>()) {
    return MakeRef(broker, broker->local_isolate()->root_handle(c->index()))
        .AsHeapObject();
  }
  return {};
}
References broker(), and v8::internal::compiler::MakeRef().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionContext(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadJSFunctionFeedbackCell(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayLength(), v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap(), GetStaticType(), and v8::internal::maglev::MaglevGraphBuilder::TryGetConstant().
unused_inputs_were_visited()
bool v8::internal::maglev::ValueNode::unused_inputs_were_visited () const [inline]
Definition at line 2625 of file maglev-ir.h.
{ return use_count_ == -1; }
References use_count_.
Referenced by v8::internal::maglev::AnyUseMarkingProcessor::DropInputUses().
use_count()
int v8::internal::maglev::ValueNode::use_count () const [inline]
Definition at line 2619 of file maglev-ir.h.
                        {
    // Invalid to check use_count externally once an id is allocated.
    DCHECK(!has_id());
    return use_count_;
  }
References v8::internal::DCHECK(), v8::internal::maglev::NodeBase::has_id(), and use_count_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintResult().
use_double_register()
constexpr bool v8::internal::maglev::ValueNode::use_double_register () const [inline], [constexpr]
Definition at line 2728 of file maglev-ir.h.
                                             {
    return IsDoubleRepresentation(properties().value_representation());
  }
References v8::internal::maglev::IsDoubleRepresentation(), v8::internal::maglev::NodeBase::properties(), and value_representation().
Referenced by AddRegister(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegister(), v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisterAtEnd(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignArbitraryRegisterInput(), ClearRegisters(), FirstRegisterCode(), v8::internal::maglev::StraightForwardRegisterAllocator::ForceAllocate(), v8::internal::maglev::StraightForwardRegisterAllocator::FreeRegistersUsedBy(), has_register(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopReloads(), v8::internal::maglev::StraightForwardRegisterAllocator::HoistLoopSpills(), InitializeRegisterData(), is_in_register(), v8::internal::maglev::StraightForwardRegisterAllocator::MarkAsClobbered(), num_registers(), RemoveRegister(), result_registers(), and v8::internal::maglev::StraightForwardRegisterAllocator::VerifyRegisterState().
value_representation()
constexpr ValueRepresentation v8::internal::maglev::ValueNode::value_representation () const [inline], [constexpr]
Definition at line 2763 of file maglev-ir.h.
                                                             {
    return properties().value_representation();
  }
References v8::internal::maglev::NodeBase::properties(), and v8::internal::maglev::OpProperties::value_representation().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBranchIfToBooleanTrue(), v8::internal::maglev::MaglevGraphBuilder::BuildCheckSmi(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForConsString(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevGraphBuilder::DoTryReduceMathRound(), v8::internal::maglev::MaglevInliner::EnsureTagged(), v8::internal::maglev::MaglevPhiRepresentationSelector::FixLoopPhisBackedge(), GetMachineRepresentation(), GetStaticType(), is_tagged(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::MakePhiMaybePermuteInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateUntaggingOfPhi(), use_double_register(), and v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation().
Member Data Documentation
union { ... } [protected]
union { ... } [protected]
double_registers_with_result_
DoubleRegList v8::internal::maglev::ValueNode::double_registers_with_result_
Definition at line 2892 of file maglev-ir.h.
Referenced by AddRegister(), FirstRegisterCode(), has_register(), InitializeRegisterData(), is_in_register(), num_registers(), RemoveRegister(), and result_registers().
end_id_
NodeIdT v8::internal::maglev::ValueNode::end_id_ = kInvalidNodeId [protected]
Definition at line 2887 of file maglev-ir.h.
Referenced by has_valid_live_range(), live_range(), and record_next_use().
hint_
compiler::InstructionOperand v8::internal::maglev::ValueNode::hint_ [protected]
Definition at line 2901 of file maglev-ir.h.
Referenced by ClearHint(), GetRegisterHint(), has_hint(), hint(), and SetHint().
last_uses_next_use_id_
NodeIdT* v8::internal::maglev::ValueNode::last_uses_next_use_id_
Definition at line 2898 of file maglev-ir.h.
Referenced by record_next_use().
next_use_
NodeIdT v8::internal::maglev::ValueNode::next_use_ = kInvalidNodeId [protected]
Definition at line 2888 of file maglev-ir.h.
Referenced by advance_next_use(), current_next_use(), and has_no_more_uses().
registers_with_result_
RegList v8::internal::maglev::ValueNode::registers_with_result_
Definition at line 2891 of file maglev-ir.h.
Referenced by AddRegister(), ClearRegisters(), FirstRegisterCode(), has_register(), InitializeRegisterData(), is_in_register(), num_registers(), RemoveRegister(), and result_registers().
result_
ValueLocation v8::internal::maglev::ValueNode::result_ [protected]
Definition at line 2889 of file maglev-ir.h.
Referenced by result(), and SetHint().
spill_
compiler::InstructionOperand v8::internal::maglev::ValueNode::spill_
Definition at line 2899 of file maglev-ir.h.
Referenced by allocation(), is_loadable(), is_spilled(), loadable_slot(), SetConstantLocation(), SetNoSpill(), and Spill().
use_count_
int v8::internal::maglev::ValueNode::use_count_ [protected]
Definition at line 2903 of file maglev-ir.h.
Referenced by add_use(), is_used(), mark_unused_inputs_visited(), remove_use(), unused_inputs_were_visited(), and use_count().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir-inl.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc