v8::internal::interpreter::InterpreterCompilationJob Class Reference
Public Member Functions
InterpreterCompilationJob (ParseInfo *parse_info, FunctionLiteral *literal, Handle< Script > script, AccountingAllocator *allocator, std::vector< FunctionLiteral * > *eager_inner_literals, LocalIsolate *local_isolate)
InterpreterCompilationJob (const InterpreterCompilationJob &)=delete
InterpreterCompilationJob & operator= (const InterpreterCompilationJob &)=delete
Protected Member Functions
Status ExecuteJobImpl () final
Status FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, Isolate *isolate) final
Status FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate *isolate) final
Private Member Functions
BytecodeGenerator * generator ()
template<typename IsolateT >
void CheckAndPrintBytecodeMismatch (IsolateT *isolate, Handle< Script > script, DirectHandle< BytecodeArray > bytecode)
template<typename IsolateT >
Status DoFinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, IsolateT *isolate)
Private Attributes
Zone zone_
UnoptimizedCompilationInfo compilation_info_
LocalIsolate * local_isolate_
BytecodeGenerator generator_
Additional Inherited Members
Detailed Description
Definition at line 31 of file interpreter.cc.
Constructor & Destructor Documentation
InterpreterCompilationJob() [1/2]
v8::internal::interpreter::InterpreterCompilationJob::InterpreterCompilationJob (ParseInfo * parse_info, FunctionLiteral * literal, Handle< Script > script, AccountingAllocator * allocator, std::vector< FunctionLiteral * > * eager_inner_literals, LocalIsolate * local_isolate)
Definition at line 170 of file interpreter.cc.
    : UnoptimizedCompilationJob(parse_info->stack_limit(), parse_info,
                                &compilation_info_),
      zone_(allocator, ZONE_NAME),
      compilation_info_(&zone_, parse_info, literal),
      local_isolate_(local_isolate),
      generator_(local_isolate, &zone_, &compilation_info_,
                 parse_info->ast_string_constants(), eager_inner_literals,
                 script) {}
InterpreterCompilationJob() [2/2]
v8::internal::interpreter::InterpreterCompilationJob::InterpreterCompilationJob (const InterpreterCompilationJob &) [delete]
Member Function Documentation
CheckAndPrintBytecodeMismatch()
template<typename IsolateT >
void v8::internal::interpreter::InterpreterCompilationJob::CheckAndPrintBytecodeMismatch (IsolateT * isolate, Handle< Script > script, DirectHandle< BytecodeArray > bytecode) [private]
Referenced by DoFinalizeJobImpl().
DoFinalizeJobImpl()
template<typename IsolateT >
InterpreterCompilationJob::Status v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, IsolateT * isolate) [private]
Definition at line 266 of file interpreter.cc.
                                                                     {
  Handle<BytecodeArray> bytecodes = compilation_info_.bytecode_array();
  if (bytecodes.is_null()) {
    bytecodes = generator()->FinalizeBytecode(
        isolate, handle(Cast<Script>(shared_info->script()), isolate));
    if (generator()->HasStackOverflow()) {
      return FAILED;
    }
    compilation_info()->SetBytecodeArray(bytecodes);
  }
  if (compilation_info()->SourcePositionRecordingMode() ==
      SourcePositionTableBuilder::RecordingMode::RECORD_SOURCE_POSITIONS) {
    DirectHandle<TrustedByteArray> source_position_table =
        generator()->FinalizeSourcePositionTable(isolate);
    bytecodes->set_source_position_table(*source_position_table, kReleaseStore);
  }
  if (ShouldPrintBytecode(shared_info)) {
    StdoutStream os;
    std::unique_ptr<char[]> name =
        compilation_info()->literal()->GetDebugName();
    os << "[generated bytecode for function: " << name.get() << " ("
       << shared_info << ")]" << std::endl;
    os << "Bytecode length: " << bytecodes->length() << std::endl;
    bytecodes->Disassemble(os);
    os << std::flush;
  }
#ifdef DEBUG
  if (parse_info()->literal()->shared_function_info().is_null()) {
    parse_info()->literal()->set_shared_function_info(
        indirect_handle(shared_info, isolate));
  }
  CheckAndPrintBytecodeMismatch(
      isolate, handle(Cast<Script>(shared_info->script()), isolate), bytecodes);
#endif
  return SUCCEEDED;
}
References v8::internal::UnoptimizedCompilationInfo::bytecode_array(), CheckAndPrintBytecodeMismatch(), v8::internal::UnoptimizedCompilationJob::compilation_info(), compilation_info_, v8::internal::CompilationJob::FAILED, v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode(), v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable(), generator(), v8::internal::FunctionLiteral::GetDebugName(), v8::internal::handle(), v8::internal::indirect_handle(), v8::internal::HandleBase::is_null(), v8::kReleaseStore, v8::internal::UnoptimizedCompilationInfo::literal(), v8::internal::ParseInfo::literal(), v8::internal::name, v8::internal::UnoptimizedCompilationJob::parse_info(), v8::internal::FunctionLiteral::set_shared_function_info(), v8::internal::UnoptimizedCompilationInfo::SetBytecodeArray(), v8::internal::interpreter::anonymous_namespace{interpreter.cc}::ShouldPrintBytecode(), and v8::internal::CompilationJob::SUCCEEDED.
Referenced by FinalizeJobImpl().
ExecuteJobImpl()
InterpreterCompilationJob::Status v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl () [final], [protected], [virtual]
Implements v8::internal::UnoptimizedCompilationJob.
Definition at line 184 of file interpreter.cc.
                                                                          {
  RCS_SCOPE(parse_info()->runtime_call_stats(),
            RuntimeCallCounterId::kCompileIgnition,
            RuntimeCallStats::kThreadSpecific);
  // TODO(lpy): add support for background compilation RCS trace.
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.CompileIgnition");
  // Print AST if flag is enabled. Note, if compiling on a background thread
  // then ASTs from different functions may be intersperse when printed.
  {
    DisallowGarbageCollection no_heap_access;
    MaybePrintAst(parse_info(), compilation_info());
  }
  local_isolate_->ParkIfOnBackgroundAndExecute(
      [this]() { generator()->GenerateBytecode(stack_limit()); });
  if (generator()->HasStackOverflow()) {
    return FAILED;
  }
  return SUCCEEDED;
}
References v8::internal::UnoptimizedCompilationJob::compilation_info(), v8::internal::CompilationJob::FAILED, v8::internal::interpreter::BytecodeGenerator::GenerateBytecode(), generator(), local_isolate_, v8::internal::interpreter::anonymous_namespace{interpreter.cc}::MaybePrintAst(), v8::internal::LocalIsolate::ParkIfOnBackgroundAndExecute(), v8::internal::UnoptimizedCompilationJob::parse_info(), RCS_SCOPE, v8::internal::UnoptimizedCompilationJob::stack_limit(), v8::internal::CompilationJob::SUCCEEDED, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
FinalizeJobImpl() [1/2]
InterpreterCompilationJob::Status v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, Isolate * isolate) [final], [protected], [virtual]
Implements v8::internal::UnoptimizedCompilationJob.
Definition at line 247 of file interpreter.cc.
                                                                    {
  RCS_SCOPE(parse_info()->runtime_call_stats(),
            RuntimeCallCounterId::kCompileIgnitionFinalization);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.CompileIgnitionFinalization");
  return DoFinalizeJobImpl(shared_info, isolate);
}
References DoFinalizeJobImpl(), v8::internal::UnoptimizedCompilationJob::parse_info(), RCS_SCOPE, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
FinalizeJobImpl() [2/2]
InterpreterCompilationJob::Status v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate * isolate) [final], [protected], [virtual]
Implements v8::internal::UnoptimizedCompilationJob.
Definition at line 256 of file interpreter.cc.
                                                                         {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kCompileIgnitionFinalization,
            RuntimeCallStats::kThreadSpecific);
  TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
               "V8.CompileIgnitionFinalization");
  return DoFinalizeJobImpl(shared_info, isolate);
}
References DoFinalizeJobImpl(), RCS_SCOPE, TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
generator()
BytecodeGenerator* v8::internal::interpreter::InterpreterCompilationJob::generator () [inline], [private]
Definition at line 50 of file interpreter.cc.
{ return &generator_; }
References generator_.
Referenced by DoFinalizeJobImpl(), and ExecuteJobImpl().
operator=()
InterpreterCompilationJob& v8::internal::interpreter::InterpreterCompilationJob::operator= (const InterpreterCompilationJob &) [delete]
Member Data Documentation
compilation_info_
UnoptimizedCompilationInfo v8::internal::interpreter::InterpreterCompilationJob::compilation_info_ [private]
Definition at line 60 of file interpreter.cc.
Referenced by DoFinalizeJobImpl().
generator_
BytecodeGenerator v8::internal::interpreter::InterpreterCompilationJob::generator_ [private]
Definition at line 62 of file interpreter.cc.
Referenced by generator().
local_isolate_
LocalIsolate* v8::internal::interpreter::InterpreterCompilationJob::local_isolate_ [private]
Definition at line 61 of file interpreter.cc.
Referenced by ExecuteJobImpl().
zone_
Zone v8::internal::interpreter::InterpreterCompilationJob::zone_ [private]
Definition at line 59 of file interpreter.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/interpreter.cc