v8::internal::wasm::AsyncCompileJob::CompileTask Class Reference
Public Member Functions
CompileTask (AsyncCompileJob *job, bool on_foreground)
~CompileTask () override
void RunInternal () final
void Cancel ()
Private Member Functions
void ResetPendingForegroundTask () const
Private Attributes
AsyncCompileJob * job_
bool on_foreground_
Additional Inherited Members
Detailed Description
Definition at line 2933 of file module-compiler.cc.
Constructor & Destructor Documentation
CompileTask()
v8::internal::wasm::AsyncCompileJob::CompileTask::CompileTask (AsyncCompileJob * job, bool on_foreground) [inline]
Definition at line 2935 of file module-compiler.cc.
      : CancelableTask(on_foreground ? job->isolate_->cancelable_task_manager()
                                     : &job->background_task_manager_),
        job_(job),
        on_foreground_(on_foreground) {}
 CompileTask()
v8::internal::wasm::AsyncCompileJob::CompileTask::~CompileTask () [inline], [override]
Definition at line 2945 of file module-compiler.cc.
                          {
    if (job_ != nullptr && on_foreground_) ResetPendingForegroundTask();
  }
References job_, on_foreground_, and ResetPendingForegroundTask().
Member Function Documentation
Cancel()
void v8::internal::wasm::AsyncCompileJob::CompileTask::Cancel () [inline]
Definition at line 2958 of file module-compiler.cc.
                {
    DCHECK_NOT_NULL(job_);
    job_ = nullptr;
  }
References DCHECK_NOT_NULL, and job_.
Referenced by v8::internal::wasm::AsyncCompileJob::CancelPendingForegroundTask().
ResetPendingForegroundTask()
void v8::internal::wasm::AsyncCompileJob::CompileTask::ResetPendingForegroundTask () const [inline], [private]
Definition at line 2968 of file module-compiler.cc.
                                          {
    DCHECK_EQ(this, job_->pending_foreground_task_);
    job_->pending_foreground_task_ = nullptr;
  }
References DCHECK_EQ, job_, and v8::internal::wasm::AsyncCompileJob::pending_foreground_task_.
Referenced by RunInternal(), and ~CompileTask().
RunInternal()
void v8::internal::wasm::AsyncCompileJob::CompileTask::RunInternal () [inline], [final], [virtual]
Implements v8::internal::CancelableTask.
Definition at line 2949 of file module-compiler.cc.
                           {
    if (!job_) return;
    if (on_foreground_) ResetPendingForegroundTask();
    job_->step_->Run(job_, on_foreground_);
    // After execution, reset {job_} such that we don't try to reset the pending
    // foreground task when the task is deleted.
    job_ = nullptr;
  }
References job_, on_foreground_, ResetPendingForegroundTask(), and v8::internal::wasm::AsyncCompileJob::step_.
Member Data Documentation
job_
AsyncCompileJob* v8::internal::wasm::AsyncCompileJob::CompileTask::job_ [private]
Definition at line 2965 of file module-compiler.cc.
Referenced by Cancel(), ResetPendingForegroundTask(), RunInternal(), and ~CompileTask().
on_foreground_
bool v8::internal::wasm::AsyncCompileJob::CompileTask::on_foreground_ [private]
Definition at line 2966 of file module-compiler.cc.
Referenced by RunInternal(), and ~CompileTask().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc