v8::WasmStreaming::WasmStreamingImpl Class Reference
Public Member Functions
WasmStreamingImpl (i::Isolate *isolate, const char *api_method_name, CompileTimeImports compile_imports, std::shared_ptr< internal::wasm::CompilationResultResolver > resolver)
void OnBytesReceived (const uint8_t *bytes, size_t size)
void Finish (bool can_use_compiled_module)
void Abort (i::MaybeHandle< i::JSAny > exception)
bool SetCompiledModuleBytes (base::Vector< const uint8_t > bytes)
void SetMoreFunctionsCanBeSerializedCallback (std::function< void(CompiledWasmModule)> callback)
void SetUrl (base::Vector< const char > url)
Private Attributes
i::Isolate *const i_isolate_
const WasmEnabledFeatures enabled_features_
const std::shared_ptr< internal::wasm::StreamingDecoder > streaming_decoder_
const std::shared_ptr< internal::wasm::CompilationResultResolver > resolver_
Detailed Description
Definition at line 11953 of file api.cc.
Constructor & Destructor Documentation
WasmStreamingImpl()
v8::WasmStreaming::WasmStreamingImpl::WasmStreamingImpl (i::Isolate * isolate, const char * api_method_name, CompileTimeImports compile_imports, std::shared_ptr< internal::wasm::CompilationResultResolver > resolver) [inline]
Definition at line 61 of file wasm-js.cc.
      : i_isolate_(isolate),
        enabled_features_(WasmEnabledFeatures::FromIsolate(i_isolate_)),
        streaming_decoder_(i::wasm::GetWasmEngine()->StartStreamingCompilation(
            i_isolate_, enabled_features_, std::move(compile_imports),
            direct_handle(i_isolate_->context(), i_isolate_), api_method_name,
            resolver)),
        resolver_(std::move(resolver)) {}
Member Function Documentation
Abort()
void v8::WasmStreaming::WasmStreamingImpl::Abort (i::MaybeHandle< i::JSAny > exception) [inline]
Definition at line 80 of file wasm-js.cc.
                                             {
    i::HandleScope scope(i_isolate_);
    streaming_decoder_->Abort();
    // If no exception value is provided, we do not reject the promise. This can
    // happen when streaming compilation gets aborted when no script execution
    // is allowed anymore, e.g. when a browser tab gets refreshed.
    if (exception.is_null()) return;
    resolver_->OnCompilationFailed(exception.ToHandleChecked());
  }
References i_isolate_, v8::internal::MaybeHandle< T >::is_null(), resolver_, streaming_decoder_, and v8::internal::MaybeHandle< T >::ToHandleChecked().
Finish()
void v8::WasmStreaming::WasmStreamingImpl::Finish (bool can_use_compiled_module) [inline]
Definition at line 76 of file wasm-js.cc.
                                            {
    streaming_decoder_->Finish(can_use_compiled_module);
  }
References streaming_decoder_.
OnBytesReceived()
void v8::WasmStreaming::WasmStreamingImpl::OnBytesReceived (const uint8_t * bytes, size_t size) [inline]
Definition at line 73 of file wasm-js.cc.
                                                          {
    streaming_decoder_->OnBytesReceived(base::VectorOf(bytes, size));
  }
References size(), streaming_decoder_, and v8::base::VectorOf().
SetCompiledModuleBytes()
bool v8::WasmStreaming::WasmStreamingImpl::SetCompiledModuleBytes (base::Vector< const uint8_t > bytes) [inline]
Definition at line 92 of file wasm-js.cc.
                                                               {
    if (!i::wasm::IsSupportedVersion(bytes, enabled_features_)) return false;
    streaming_decoder_->SetCompiledModuleBytes(bytes);
    return true;
  }
References enabled_features_, v8::internal::wasm::IsSupportedVersion(), and streaming_decoder_.
SetMoreFunctionsCanBeSerializedCallback()
void v8::WasmStreaming::WasmStreamingImpl::SetMoreFunctionsCanBeSerializedCallback (std::function< void(CompiledWasmModule)> callback) [inline]
Definition at line 98 of file wasm-js.cc.
                                                      {
    streaming_decoder_->SetMoreFunctionsCanBeSerializedCallback(
        [callback = std::move(callback),
         url = streaming_decoder_->shared_url()](
            const std::shared_ptr<i::wasm::NativeModule>& native_module) {
          callback(CompiledWasmModule{native_module, url->data(), url->size()});
        });
  }
References streaming_decoder_.
SetUrl()
void v8::WasmStreaming::WasmStreamingImpl::SetUrl (base::Vector< const char > url) [inline]
Definition at line 108 of file wasm-js.cc.
{ streaming_decoder_->SetUrl(url); }
Member Data Documentation
enabled_features_
const WasmEnabledFeatures v8::WasmStreaming::WasmStreamingImpl::enabled_features_ [private]
Definition at line 112 of file wasm-js.cc.
Referenced by SetCompiledModuleBytes().
i_isolate_
i::Isolate* const v8::WasmStreaming::WasmStreamingImpl::i_isolate_ [private]
Definition at line 111 of file wasm-js.cc.
Referenced by Abort().
resolver_
const std::shared_ptr<internal::wasm::CompilationResultResolver> v8::WasmStreaming::WasmStreamingImpl::resolver_ [private]
Definition at line 114 of file wasm-js.cc.
Referenced by Abort().
streaming_decoder_
const std::shared_ptr<internal::wasm::StreamingDecoder> v8::WasmStreaming::WasmStreamingImpl::streaming_decoder_ [private]
Definition at line 113 of file wasm-js.cc.
Referenced by Abort(), Finish(), OnBytesReceived(), SetCompiledModuleBytes(), and SetMoreFunctionsCanBeSerializedCallback().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api.cc
/mnt/V8SourceCode/src/wasm/wasm-js.cc