v8::SourceLocation Class Reference
Encapsulates source location information.
#include <v8-source-location.h>
Public Member Functions
constexpr SourceLocation ()=default
Constructs unspecified source location information.
constexpr const char * Function () const
Returns the name of the function associated with the position represented by this object, if any.
constexpr const char * FileName () const
Returns the name of the current source file represented by this object.
constexpr size_t Line () const
Returns the line number represented by this object.
std::string ToString () const
Returns a human-readable string representing this object.
Static Public Member Functions
static constexpr SourceLocation Current ()
Construct source location information corresponding to the location of the call site.
Private Member Functions
constexpr SourceLocation (const char *function, const char *file, size_t line)
Private Attributes
const char * function_ = nullptr
const char * file_ = nullptr
size_t line_ = 0u
Detailed Description
Encapsulates source location information.
Mimics C++20's std::source_location.
Definition at line 31 of file v8-source-location.h.
Constructor & Destructor Documentation
SourceLocation() [1/2]
constexpr v8::SourceLocation::SourceLocation () [constexpr], [default]
Constructs unspecified source location information.
SourceLocation() [2/2]
constexpr v8::SourceLocation::SourceLocation (const char * function, const char * file, size_t line) [inline], [constexpr], [private]
Definition at line 87 of file v8-source-location.h.
      : function_(function), file_(file), line_(line) {}
Member Function Documentation
Current()
static constexpr SourceLocation v8::SourceLocation::Current () [inline], [static], [constexpr]
Construct source location information corresponding to the location of the call site.
Definition at line 44 of file v8-source-location.h.
{ return SourceLocation(); }
FileName()
constexpr const char* v8::SourceLocation::FileName () const [inline], [constexpr]
Returns the name of the current source file represented by this object.
Returns
the file name as cstring.
Definition at line 65 of file v8-source-location.h.
{ return file_; }
Referenced by v8::internal::CodeStubAssembler::Check(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CodeComment(), v8::internal::compiler::CodeAssembler::Comment(), cppgc::internal::DCheckImpl(), cppgc::internal::Fatal(), cppgc::internal::FatalImpl(), cppgc::internal::FatalOutOfMemoryHandler::operator()(), v8::internal::compiler::CodeAssembler::Parameter(), and v8::internal::AssemblerBase::RecordComment().
Function()
constexpr const char* v8::SourceLocation::Function () const [inline], [constexpr]
Returns the name of the function associated with the position represented by this object, if any.
Returns
the function name as cstring.
Definition at line 58 of file v8-source-location.h.
{ return function_; }
Line()
constexpr size_t v8::SourceLocation::Line () const [inline], [constexpr]
Returns the line number represented by this object.
Returns
the line number.
Definition at line 72 of file v8-source-location.h.
{ return line_; }
Referenced by v8::internal::CodeStubAssembler::Check(), cppgc::internal::DCheckImpl(), cppgc::internal::Fatal(), cppgc::internal::FatalImpl(), cppgc::internal::FatalOutOfMemoryHandler::operator()(), and v8::internal::compiler::CodeAssembler::Parameter().
ToString()
std::string v8::SourceLocation::ToString () const [inline]
Returns a human-readable string representing this object.
Returns
a human-readable string representing source location information.
Definition at line 79 of file v8-source-location.h.
                             {
    if (!file_) {
      return {};
    }
    return std::string(function_) + "@" + file_ + ":" + std::to_string(line_);
  }
References v8::internal::string.
Referenced by v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CodeComment(), v8::internal::compiler::CodeAssembler::Comment(), v8::internal::AssemblerBase::RecordComment(), and v8::internal::CppGraphBuilderImpl::VisitRootForGraphBuilding().
Member Data Documentation
file_
const char* v8::SourceLocation::file_ = nullptr [private]
Definition at line 91 of file v8-source-location.h.
function_
const char* v8::SourceLocation::function_ = nullptr [private]
Definition at line 90 of file v8-source-location.h.
line_
size_t v8::SourceLocation::line_ = 0u [private]
Definition at line 92 of file v8-source-location.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-source-location.h