v8_inspector::V8InspectorClient Class Reference
#include <v8-inspector.h>
Public Types
typedef void(* TimerCallback) (void *)
Public Member Functions
virtual ~V8InspectorClient ()=default
virtual void runMessageLoopOnPause (int contextGroupId)
virtual void runMessageLoopOnInstrumentationPause (int contextGroupId)
virtual void quitMessageLoopOnPause ()
virtual void runIfWaitingForDebugger (int contextGroupId)
virtual void muteMetrics (int contextGroupId)
virtual void unmuteMetrics (int contextGroupId)
virtual void beginUserGesture ()
virtual void endUserGesture ()
virtual std::unique_ptr< DeepSerializationResult > deepSerialize (v8::Local< v8::Value > v8Value, int maxDepth, v8::Local< v8::Object > additionalParameters)
virtual std::unique_ptr< StringBuffer > valueSubtype (v8::Local< v8::Value >)
virtual std::unique_ptr< StringBuffer > descriptionForValueSubtype (v8::Local< v8::Context >, v8::Local< v8::Value >)
virtual bool isInspectableHeapObject (v8::Local< v8::Object >)
virtual v8::Local< v8::Context > ensureDefaultContextInGroup (int contextGroupId)
virtual void beginEnsureAllContextsInGroup (int contextGroupId)
virtual void endEnsureAllContextsInGroup (int contextGroupId)
virtual void installAdditionalCommandLineAPI (v8::Local< v8::Context >, v8::Local< v8::Object >)
virtual void consoleAPIMessage (int contextGroupId, v8::Isolate::MessageErrorLevel level, const StringView &message, const StringView &url, unsigned lineNumber, unsigned columnNumber, V8StackTrace *)
virtual v8::MaybeLocal< v8::Value > memoryInfo (v8::Isolate *, v8::Local< v8::Context >)
virtual void consoleTime (v8::Isolate *isolate, v8::Local< v8::String > label)
virtual void consoleTimeEnd (v8::Isolate *isolate, v8::Local< v8::String > label)
virtual void consoleTimeStamp (v8::Isolate *isolate, v8::Local< v8::String > label)
virtual void consoleTimeStampWithArgs (v8::Isolate *isolate, v8::Local< v8::String > label, const v8::LocalVector< v8::Value > &args)
virtual void consoleClear (int contextGroupId)
virtual double currentTimeMS ()
virtual void startRepeatingTimer (double, TimerCallback, void *data)
virtual void cancelTimer (void *data)
virtual bool canExecuteScripts (int contextGroupId)
virtual void maxAsyncCallStackDepthChanged (int depth)
virtual std::unique_ptr< StringBuffer > resourceNameToUrl (const StringView &resourceName)
virtual int64_t generateUniqueId ()
virtual void dispatchError (v8::Local< v8::Context >, v8::Local< v8::Message >, v8::Local< v8::Value >)
Detailed Description
Definition at line 251 of file v8-inspector.h.
Member Typedef Documentation
TimerCallback
typedef void(* v8_inspector::V8InspectorClient::TimerCallback) (void *)
Definition at line 311 of file v8-inspector.h.
Constructor & Destructor Documentation
 V8InspectorClient()
virtual v8_inspector::V8InspectorClient::~V8InspectorClient () [virtual], [default]
Member Function Documentation
beginEnsureAllContextsInGroup()
virtual void v8_inspector::V8InspectorClient::beginEnsureAllContextsInGroup (int contextGroupId) [inline], [virtual]
Definition at line 286 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8RuntimeAgentImpl::enable().
beginUserGesture()
virtual void v8_inspector::V8InspectorClient::beginUserGesture () [inline], [virtual]
Definition at line 265 of file v8-inspector.h.
{}
cancelTimer()
virtual void v8_inspector::V8InspectorClient::cancelTimer (void * data) [inline], [virtual]
Definition at line 313 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), and v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjectsInternal().
canExecuteScripts()
virtual bool v8_inspector::V8InspectorClient::canExecuteScripts (int contextGroupId) [inline], [virtual]
Definition at line 317 of file v8-inspector.h.
{ return true; }
Referenced by v8_inspector::V8DebuggerAgentImpl::enable(), and v8_inspector::V8DebuggerAgentImpl::restore().
consoleAPIMessage()
virtual void v8_inspector::V8InspectorClient::consoleAPIMessage (int contextGroupId, v8::Isolate::MessageErrorLevel level, const StringView & message, const StringView & url, unsigned lineNumber, unsigned columnNumber, V8StackTrace *) [inline], [virtual]
Definition at line 291 of file v8-inspector.h.
                                                                       {}
Referenced by v8_inspector::V8ConsoleMessage::createForConsoleAPI().
consoleClear()
virtual void v8_inspector::V8InspectorClient::consoleClear (int contextGroupId) [inline], [virtual]
Definition at line 309 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8Console::Clear().
consoleTime()
virtual void v8_inspector::V8InspectorClient::consoleTime (v8::Isolate * isolate, v8::Local< v8::String > label) [inline], [virtual]
Definition at line 301 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8Console::Time().
consoleTimeEnd()
virtual void v8_inspector::V8InspectorClient::consoleTimeEnd (v8::Isolate * isolate, v8::Local< v8::String > label) [inline], [virtual]
Definition at line 302 of file v8-inspector.h.
                                                       {}
Referenced by v8_inspector::V8Console::TimeEnd().
consoleTimeStamp()
virtual void v8_inspector::V8InspectorClient::consoleTimeStamp (v8::Isolate * isolate, v8::Local< v8::String > label) [inline], [virtual]
Definition at line 304 of file v8-inspector.h.
                                                         {}
consoleTimeStampWithArgs()
virtual void v8_inspector::V8InspectorClient::consoleTimeStampWithArgs (v8::Isolate * isolate, v8::Local< v8::String > label, const v8::LocalVector< v8::Value > & args) [inline], [virtual]
Definition at line 306 of file v8-inspector.h.
                                          {}
Referenced by v8_inspector::V8Console::TimeStamp().
currentTimeMS()
virtual double v8_inspector::V8InspectorClient::currentTimeMS () [inline], [virtual]
Definition at line 310 of file v8-inspector.h.
{ return 0; }
Referenced by v8_inspector::V8InspectorImpl::exceptionRevoked(), v8_inspector::V8InspectorImpl::exceptionThrown(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8_inspector::V8HeapProfilerAgentImpl::requestHeapStatsUpdate(), v8_inspector::V8ConsoleMessageStorage::timeEnd(), and v8_inspector::V8ConsoleMessageStorage::timeLog().
deepSerialize()
virtual std::unique_ptr<DeepSerializationResult> v8_inspector::V8InspectorClient::deepSerialize (v8::Local< v8::Value > v8Value, int maxDepth, v8::Local< v8::Object > additionalParameters) [inline], [virtual]
Definition at line 268 of file v8-inspector.h.
                                              {
    return nullptr;
  }
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::ObjectMirror::buildDeepSerializedValue().
descriptionForValueSubtype()
virtual std::unique_ptr<StringBuffer> v8_inspector::V8InspectorClient::descriptionForValueSubtype (v8::Local< v8::Context > , v8::Local< v8::Value >) [inline], [virtual]
Definition at line 276 of file v8-inspector.h.
                                            {
    return nullptr;
  }
Referenced by v8_inspector::clientMirror().
dispatchError()
virtual void v8_inspector::V8InspectorClient::dispatchError (v8::Local< v8::Context > , v8::Local< v8::Message > , v8::Local< v8::Value >) [inline], [virtual]
Definition at line 330 of file v8-inspector.h.
                                               {}
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), and v8_inspector::InjectedScript::wrapEvaluateResult().
endEnsureAllContextsInGroup()
virtual void v8_inspector::V8InspectorClient::endEnsureAllContextsInGroup (int contextGroupId) [inline], [virtual]
Definition at line 287 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8RuntimeAgentImpl::disable().
endUserGesture()
virtual void v8_inspector::V8InspectorClient::endUserGesture () [inline], [virtual]
Definition at line 266 of file v8-inspector.h.
{}
ensureDefaultContextInGroup()
virtual v8::Local<v8::Context> v8_inspector::V8InspectorClient::ensureDefaultContextInGroup (int contextGroupId) [inline], [virtual]
Reimplemented in v8::InspectorClient.
Definition at line 282 of file v8-inspector.h.
                          {
    return v8::Local<v8::Context>();
  }
Referenced by v8_inspector::V8Debugger::continueProgram(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), and v8_inspector::V8RuntimeAgentImpl::terminateExecution().
generateUniqueId()
virtual int64_t v8_inspector::V8InspectorClient::generateUniqueId () [inline], [virtual]
Definition at line 328 of file v8-inspector.h.
{ return 0; }
Referenced by v8_inspector::V8InspectorImpl::generateUniqueId().
installAdditionalCommandLineAPI()
virtual void v8_inspector::V8InspectorClient::installAdditionalCommandLineAPI (v8::Local< v8::Context > , v8::Local< v8::Object >) [inline], [virtual]
Definition at line 289 of file v8-inspector.h.
                                                                  {}
Referenced by v8_inspector::V8Console::createCommandLineAPI().
isInspectableHeapObject()
virtual bool v8_inspector::V8InspectorClient::isInspectableHeapObject (v8::Local< v8::Object >) [inline], [virtual]
Definition at line 280 of file v8-inspector.h.
{ return true; }
Referenced by v8_inspector::V8HeapProfilerAgentImpl::addInspectedHeapObject(), and v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId().
maxAsyncCallStackDepthChanged()
virtual void v8_inspector::V8InspectorClient::maxAsyncCallStackDepthChanged (int depth) [inline], [virtual]
Definition at line 319 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8Debugger::setAsyncCallStackDepth().
memoryInfo()
virtual v8::MaybeLocal<v8::Value> v8_inspector::V8InspectorClient::memoryInfo (v8::Isolate * , v8::Local< v8::Context >) [inline], [virtual]
Definition at line 296 of file v8-inspector.h.
                                                                   {
    return v8::MaybeLocal<v8::Value>();
  }
Referenced by v8_inspector::V8Console::memoryGetterCallback().
muteMetrics()
virtual void v8_inspector::V8InspectorClient::muteMetrics (int contextGroupId) [inline], [virtual]
Definition at line 262 of file v8-inspector.h.
{}
quitMessageLoopOnPause()
virtual void v8_inspector::V8InspectorClient::quitMessageLoopOnPause () [inline], [virtual]
Reimplemented in v8::InspectorClient.
Definition at line 259 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8Debugger::continueProgram(), v8_inspector::V8Debugger::disable(), and v8_inspector::V8Debugger::quitMessageLoopIfAgentsFinishedInstrumentation().
resourceNameToUrl()
virtual std::unique_ptr<StringBuffer> v8_inspector::V8InspectorClient::resourceNameToUrl (const StringView & resourceName) [inline], [virtual]
Definition at line 321 of file v8-inspector.h.
                                      {
    return nullptr;
  }
Referenced by v8_inspector::StackFrame::buildInspectorObject(), v8_inspector::V8DebuggerScript::GetScriptName(), and v8_inspector::anonymous_namespace{v8-profiler-agent-impl.cc}::resourceNameToUrl().
runIfWaitingForDebugger()
virtual void v8_inspector::V8InspectorClient::runIfWaitingForDebugger (int contextGroupId) [inline], [virtual]
Definition at line 260 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8RuntimeAgentImpl::runIfWaitingForDebugger(), and v8_inspector::V8DebuggerBarrier::~V8DebuggerBarrier().
runMessageLoopOnInstrumentationPause()
virtual void v8_inspector::V8InspectorClient::runMessageLoopOnInstrumentationPause (int contextGroupId) [inline], [virtual]
Definition at line 256 of file v8-inspector.h.
                                                                        {
    runMessageLoopOnPause(contextGroupId);
  }
Referenced by v8_inspector::V8Debugger::BreakOnInstrumentation().
runMessageLoopOnPause()
virtual void v8_inspector::V8InspectorClient::runMessageLoopOnPause (int contextGroupId) [inline], [virtual]
Reimplemented in v8::InspectorClient.
Definition at line 255 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8Debugger::handleProgramBreak().
startRepeatingTimer()
virtual void v8_inspector::V8InspectorClient::startRepeatingTimer (double , TimerCallback , void * data) [inline], [virtual]
Definition at line 312 of file v8-inspector.h.
{}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), and v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal().
unmuteMetrics()
virtual void v8_inspector::V8InspectorClient::unmuteMetrics (int contextGroupId) [inline], [virtual]
Definition at line 263 of file v8-inspector.h.
{}
valueSubtype()
virtual std::unique_ptr<StringBuffer> v8_inspector::V8InspectorClient::valueSubtype (v8::Local< v8::Value >) [inline], [virtual]
Definition at line 273 of file v8-inspector.h.
                                                                     {
    return nullptr;
  }
Referenced by v8_inspector::ValueMirror::create(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-inspector.h