v8::internal::DataViewBuiltinsAssembler Class Reference
#include <builtins-data-view-gen.h>
Public Member Functions
DataViewBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< Uint8T > LoadUint8 (TNode< RawPtrT > data_pointer, TNode< UintPtrT > offset)
TNode< Int8T > LoadInt8 (TNode< RawPtrT > data_pointer, TNode< UintPtrT > offset)
void StoreWord8 (TNode< RawPtrT > data_pointer, TNode< UintPtrT > offset, TNode< Word32T > value)
int32_t DataViewElementSize (ElementsKind elements_kind)
TNode< Uint32T > DataViewEncodeBigIntBits (bool sign, int32_t digits)
TNode< Uint32T > DataViewDecodeBigIntLength (TNode< BigInt > value)
TNode< Uint32T > DataViewDecodeBigIntSign (TNode< BigInt > value)
Additional Inherited Members
Detailed Description
Definition at line 15 of file builtins-data-view-gen.h.
Constructor & Destructor Documentation
DataViewBuiltinsAssembler()
v8::internal::DataViewBuiltinsAssembler::DataViewBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 17 of file builtins-data-view-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
DataViewDecodeBigIntLength()
TNode<Uint32T> v8::internal::DataViewBuiltinsAssembler::DataViewDecodeBigIntLength (TNode< BigInt > value) [inline]
Definition at line 45 of file builtins-data-view-gen.h.
                                                                 {
    TNode<Word32T> bitfield = LoadBigIntBitfield(value);
    return DecodeWord32<BigIntBase::LengthBits>(bitfield);
  }
References v8::internal::CodeStubAssembler::LoadBigIntBitfield(), and v8::internal::value.
DataViewDecodeBigIntSign()
TNode<Uint32T> v8::internal::DataViewBuiltinsAssembler::DataViewDecodeBigIntSign (TNode< BigInt > value) [inline]
Definition at line 50 of file builtins-data-view-gen.h.
                                                               {
    TNode<Word32T> bitfield = LoadBigIntBitfield(value);
    return DecodeWord32<BigIntBase::SignBits>(bitfield);
  }
References v8::internal::CodeStubAssembler::LoadBigIntBitfield(), and v8::internal::value.
DataViewElementSize()
int32_t v8::internal::DataViewBuiltinsAssembler::DataViewElementSize (ElementsKind elements_kind) [inline]
Definition at line 36 of file builtins-data-view-gen.h.
                                                          {
    return ElementsKindToByteSize(elements_kind);
  }
References v8::internal::ElementsKindToByteSize().
DataViewEncodeBigIntBits()
TNode<Uint32T> v8::internal::DataViewBuiltinsAssembler::DataViewEncodeBigIntBits (bool sign, int32_t digits) [inline]
Definition at line 40 of file builtins-data-view-gen.h.
                                                                     {
    return Unsigned(Int32Constant(BigInt::SignBits::encode(sign) |
                                  BigInt::LengthBits::encode(digits)));
  }
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::sign, and v8::internal::compiler::CodeAssembler::Unsigned().
LoadInt8()
TNode<Int8T> v8::internal::DataViewBuiltinsAssembler::LoadInt8 (TNode< RawPtrT > data_pointer, TNode< UintPtrT > offset) [inline]
Definition at line 25 of file builtins-data-view-gen.h.
                                                                             {
    return UncheckedCast<Int8T>(
        Load(MachineType::Int8(), data_pointer, offset));
  }
References v8::internal::MachineType::Int8(), and v8::internal::compiler::CodeAssembler::Load().
LoadUint8()
TNode<Uint8T> v8::internal::DataViewBuiltinsAssembler::LoadUint8 (TNode< RawPtrT > data_pointer, TNode< UintPtrT > offset) [inline]
Definition at line 20 of file builtins-data-view-gen.h.
                                                                               {
    return UncheckedCast<Uint8T>(
        Load(MachineType::Uint8(), data_pointer, offset));
  }
References v8::internal::compiler::CodeAssembler::Load(), and v8::internal::MachineType::Uint8().
StoreWord8()
void v8::internal::DataViewBuiltinsAssembler::StoreWord8 (TNode< RawPtrT > data_pointer, TNode< UintPtrT > offset, TNode< Word32T > value) [inline]
Definition at line 30 of file builtins-data-view-gen.h.
                                        {
    StoreNoWriteBarrier(MachineRepresentation::kWord8, data_pointer, offset,
                        value);
  }
References v8::internal::kWord8, v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-data-view-gen.h