v8::internal::wasm::ClearThreadInWasmScope Class Reference
#include <wasm-interpreter.h>
Public Member Functions
ClearThreadInWasmScope (Isolate *isolate)
~ClearThreadInWasmScope ()
Private Attributes
Isolate * isolate_
Detailed Description
Definition at line 2105 of file wasm-interpreter.h.
Constructor & Destructor Documentation
ClearThreadInWasmScope()
v8::internal::wasm::ClearThreadInWasmScope::ClearThreadInWasmScope (Isolate * isolate) [explicit]
Definition at line 13185 of file wasm-interpreter.cc.
    : isolate_(isolate) {
  DCHECK_IMPLIES(trap_handler::IsTrapHandlerEnabled(),
                 trap_handler::IsThreadInWasm());
  trap_handler::ClearThreadInWasm();
}
References v8::internal::trap_handler::ClearThreadInWasm(), DCHECK_IMPLIES, v8::internal::trap_handler::IsThreadInWasm(), and v8::internal::trap_handler::IsTrapHandlerEnabled().
 ClearThreadInWasmScope()
v8::internal::wasm::ClearThreadInWasmScope::~ClearThreadInWasmScope ()
Definition at line 13192 of file wasm-interpreter.cc.
                                                 {
  DCHECK_IMPLIES(trap_handler::IsTrapHandlerEnabled(),
                 !trap_handler::IsThreadInWasm());
  if (!isolate_->has_exception()) {
    trap_handler::SetThreadInWasm();
  }
  // Otherwise we only want to set the flag if the exception is caught in
  // wasm. This is handled by the unwinder.
}
References DCHECK_IMPLIES, v8::internal::Isolate::has_exception(), isolate_, v8::internal::trap_handler::IsThreadInWasm(), v8::internal::trap_handler::IsTrapHandlerEnabled(), and v8::internal::trap_handler::SetThreadInWasm().
Member Data Documentation
isolate_
Isolate* v8::internal::wasm::ClearThreadInWasmScope::isolate_ [private]
Definition at line 2111 of file wasm-interpreter.h.
Referenced by ~ClearThreadInWasmScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc