v8::internal::UnoptimizedCompilationJob Class Reference
#include <compiler.h>
Public Member Functions
UnoptimizedCompilationJob (uintptr_t stack_limit, ParseInfo *parse_info, UnoptimizedCompilationInfo *compilation_info)
V8_WARN_UNUSED_RESULT Status ExecuteJob ()
V8_WARN_UNUSED_RESULT Status FinalizeJob (DirectHandle< SharedFunctionInfo > shared_info, Isolate *isolate)
V8_WARN_UNUSED_RESULT Status FinalizeJob (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate *isolate)
void RecordCompilationStats (Isolate *isolate) const
void RecordFunctionCompilation (LogEventListener::CodeTag code_type, Handle< SharedFunctionInfo > shared, Isolate *isolate) const
ParseInfo * parse_info () const
UnoptimizedCompilationInfo * compilation_info () const
uintptr_t stack_limit () const
base::TimeDelta time_taken_to_execute () const
base::TimeDelta time_taken_to_finalize () const
void ClearParseInfo ()
Protected Member Functions
virtual Status ExecuteJobImpl ()=0
virtual Status FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, Isolate *isolate)=0
virtual Status FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate *isolate)=0
Private Attributes
uintptr_t stack_limit_
ParseInfo * parse_info_
UnoptimizedCompilationInfo * compilation_info_
base::TimeDelta time_taken_to_execute_
base::TimeDelta time_taken_to_finalize_
Additional Inherited Members
Detailed Description
Definition at line 335 of file compiler.h.
Constructor & Destructor Documentation
UnoptimizedCompilationJob()
v8::internal::UnoptimizedCompilationJob::UnoptimizedCompilationJob (uintptr_t stack_limit, ParseInfo * parse_info, UnoptimizedCompilationInfo * compilation_info) [inline]
Definition at line 337 of file compiler.h.
      : CompilationJob(State::kReadyToExecute),
        stack_limit_(stack_limit),
        parse_info_(parse_info),
        compilation_info_(compilation_info) {}
Member Function Documentation
ClearParseInfo()
void v8::internal::UnoptimizedCompilationJob::ClearParseInfo () [inline]
Definition at line 379 of file compiler.h.
{ parse_info_ = nullptr; }
References parse_info_.
compilation_info()
UnoptimizedCompilationInfo* v8::internal::UnoptimizedCompilationJob::compilation_info () const [inline]
Definition at line 366 of file compiler.h.
                                                       {
    return compilation_info_;
  }
References compilation_info_.
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), and v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob().
ExecuteJob()
CompilationJob::Status v8::internal::UnoptimizedCompilationJob::ExecuteJob ()
Definition at line 392 of file compiler.cc.
                                                           {
  // Delegate to the underlying implementation.
  DCHECK_EQ(state(), State::kReadyToExecute);
  base::ScopedTimer t(v8_flags.log_function_events ? &time_taken_to_execute_
                                                   : nullptr);
  return UpdateState(ExecuteJobImpl(), State::kReadyToFinalize);
}
References DCHECK_EQ, ExecuteJobImpl(), v8::internal::CompilationJob::kReadyToExecute, v8::internal::CompilationJob::kReadyToFinalize, v8::internal::CompilationJob::state(), time_taken_to_execute_, v8::internal::CompilationJob::UpdateState(), and v8::internal::v8_flags.
ExecuteJobImpl()
virtual Status v8::internal::UnoptimizedCompilationJob::ExecuteJobImpl () [protected], [pure virtual]
Implemented in v8::internal::interpreter::InterpreterCompilationJob, and v8::internal::AsmJsCompilationJob.
Referenced by ExecuteJob().
FinalizeJob() [1/2]
CompilationJob::Status v8::internal::UnoptimizedCompilationJob::FinalizeJob (DirectHandle< SharedFunctionInfo > shared_info, Isolate * isolate)
Definition at line 400 of file compiler.cc.
                                                                    {
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  DisallowCodeDependencyChange no_dependency_change;
  DisallowJavascriptExecution no_js(isolate);
  // Delegate to the underlying implementation.
  DCHECK_EQ(state(), State::kReadyToFinalize);
  base::ScopedTimer t(v8_flags.log_function_events ? &time_taken_to_finalize_
                                                   : nullptr);
  return UpdateState(FinalizeJobImpl(shared_info, isolate), State::kSucceeded);
}
References v8::internal::ThreadId::Current(), DCHECK_EQ, FinalizeJobImpl(), v8::internal::CompilationJob::kReadyToFinalize, v8::internal::CompilationJob::kSucceeded, v8::internal::CompilationJob::state(), v8::internal::Isolate::thread_id(), time_taken_to_finalize_, v8::internal::CompilationJob::UpdateState(), and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob().
FinalizeJob() [2/2]
CompilationJob::Status v8::internal::UnoptimizedCompilationJob::FinalizeJob (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate * isolate)
Definition at line 413 of file compiler.cc.
                                                                         {
  // Delegate to the underlying implementation.
  DCHECK_EQ(state(), State::kReadyToFinalize);
  base::ScopedTimer t(v8_flags.log_function_events ? &time_taken_to_finalize_
                                                   : nullptr);
  return UpdateState(FinalizeJobImpl(shared_info, isolate), State::kSucceeded);
}
References DCHECK_EQ, FinalizeJobImpl(), v8::internal::CompilationJob::kReadyToFinalize, v8::internal::CompilationJob::kSucceeded, v8::internal::CompilationJob::state(), time_taken_to_finalize_, v8::internal::CompilationJob::UpdateState(), and v8::internal::v8_flags.
FinalizeJobImpl() [1/2]
virtual Status v8::internal::UnoptimizedCompilationJob::FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, Isolate * isolate) [protected], [pure virtual]
Implemented in v8::internal::interpreter::InterpreterCompilationJob, and v8::internal::AsmJsCompilationJob.
Referenced by FinalizeJob().
FinalizeJobImpl() [2/2]
virtual Status v8::internal::UnoptimizedCompilationJob::FinalizeJobImpl (DirectHandle< SharedFunctionInfo > shared_info, LocalIsolate * isolate) [protected], [pure virtual]
Implemented in v8::internal::interpreter::InterpreterCompilationJob, and v8::internal::AsmJsCompilationJob.
parse_info()
ParseInfo* v8::internal::UnoptimizedCompilationJob::parse_info () const [inline]
Definition at line 362 of file compiler.h.
                                {
    DCHECK_NOT_NULL(parse_info_);
    return parse_info_;
  }
References DCHECK_NOT_NULL, and parse_info_.
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl(), and v8::internal::interpreter::InterpreterCompilationJob::FinalizeJobImpl().
RecordCompilationStats()
void v8::internal::UnoptimizedCompilationJob::RecordCompilationStats (Isolate * isolate) const
RecordFunctionCompilation()
void v8::internal::UnoptimizedCompilationJob::RecordFunctionCompilation (LogEventListener::CodeTag code_type, Handle< SharedFunctionInfo > shared, Isolate * isolate) const
stack_limit()
uintptr_t v8::internal::UnoptimizedCompilationJob::stack_limit () const [inline]
Definition at line 370 of file compiler.h.
{ return stack_limit_; }
References stack_limit_.
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), and v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl().
time_taken_to_execute()
base::TimeDelta v8::internal::UnoptimizedCompilationJob::time_taken_to_execute () const [inline]
Definition at line 372 of file compiler.h.
                                              {
    return time_taken_to_execute_;
  }
References time_taken_to_execute_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob().
time_taken_to_finalize()
base::TimeDelta v8::internal::UnoptimizedCompilationJob::time_taken_to_finalize () const [inline]
Definition at line 375 of file compiler.h.
                                               {
    return time_taken_to_finalize_;
  }
References time_taken_to_finalize_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob().
Member Data Documentation
compilation_info_
UnoptimizedCompilationInfo* v8::internal::UnoptimizedCompilationJob::compilation_info_ [private]
Definition at line 392 of file compiler.h.
Referenced by compilation_info().
parse_info_
ParseInfo* v8::internal::UnoptimizedCompilationJob::parse_info_ [private]
Definition at line 391 of file compiler.h.
Referenced by ClearParseInfo(), and parse_info().
stack_limit_
uintptr_t v8::internal::UnoptimizedCompilationJob::stack_limit_ [private]
Definition at line 390 of file compiler.h.
Referenced by stack_limit().
time_taken_to_execute_
base::TimeDelta v8::internal::UnoptimizedCompilationJob::time_taken_to_execute_ [private]
Definition at line 393 of file compiler.h.
Referenced by ExecuteJob(), and time_taken_to_execute().
time_taken_to_finalize_
base::TimeDelta v8::internal::UnoptimizedCompilationJob::time_taken_to_finalize_ [private]
Definition at line 394 of file compiler.h.
Referenced by FinalizeJob(), and time_taken_to_finalize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compiler.h
/mnt/V8SourceCode/src/codegen/compiler.cc