v8::Promise::Resolver Class Reference
#include <v8-promise.h>
Public Member Functions
Local< Promise > GetPromise ()
Extract the associated promise.
V8_WARN_UNUSED_RESULT Maybe< bool > Resolve (Local< Context > context, Local< Value > value)
Resolve/reject the associated promise with a given value.
V8_WARN_UNUSED_RESULT Maybe< bool > Reject (Local< Context > context, Local< Value > value)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< Resolver > New (Local< Context > context)
Create a new resolver, along with an associated promise in pending state.
static Resolver * Cast (Value *value)
Private Member Functions
Resolver ()
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
Definition at line 32 of file v8-promise.h.
Constructor & Destructor Documentation
Resolver()
v8::Promise::Resolver::Resolver () [private]
Member Function Documentation
Cast()
static Resolver* v8::Promise::Resolver::Cast (Value * value) [inline], [static]
Definition at line 55 of file v8-promise.h.
                                                  {
#ifdef V8_ENABLE_CHECKS
      CheckCast(value);
#endif
      return static_cast<Promise::Resolver*>(value);
    }
References v8::internal::value.
CheckCast()
void v8::Promise::Resolver::CheckCast (Value * obj) [static], [private]
Definition at line 3982 of file api.cc.
                                             {
  Utils::ApiCheck(that->IsPromise(), "v8::Promise::Resolver::Cast",
                  "Value is not a Promise::Resolver");
}
References v8::Utils::ApiCheck(), and v8::Value::IsPromise().
GetPromise()
Local< Promise > v8::Promise::Resolver::GetPromise ()
Extract the associated promise.
Definition at line 8622 of file api.cc.
                                           {
  auto promise = Utils::OpenDirectHandle(this);
  return Local<Promise>::Cast(Utils::ToLocal(promise));
}
References v8::Local< T >::Cast(), and v8::Utils::OpenDirectHandle().
New()
MaybeLocal< Promise::Resolver > v8::Promise::Resolver::New (Local< Context > context) [static]
Create a new resolver, along with an associated promise in pending state.
Definition at line 8609 of file api.cc.
                                                                       {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Promise_Resolver_New};
  i::Isolate* i_isolate = api_scope.i_isolate();
  Local<Promise::Resolver> result =
      Utils::ToLocal(i::Cast<i::JSObject>(i_isolate->factory()->NewJSPromise()))
          .As<Promise::Resolver>();
  // Also check if promise hooks set an exception.
  // TODO(clemensb): Should `Factory::NewJSPromise()` return a MaybeHandle
  // instead?
  if (i_isolate->has_exception()) return {};
  return api_scope.Escape(result);
}
References v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::Factory::NewJSPromise(), and v8::base::internal::result.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8::Shell::DoHostImportModuleDynamically(), v8::internal::GCExtension::GC(), v8::Shell::HostImportModuleWithPhaseDynamically(), v8::Shell::JSONModuleEvaluationSteps(), v8::internal::anonymous_namespace{isolate.cc}::NewRejectedPromise(), v8::Shell::PerformanceMeasureMemory(), v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileStreaming(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateStreaming().
Reject()
Maybe< bool > v8::Promise::Resolver::Reject (Local< Context > context, Local< Value > value)
Definition at line 8646 of file api.cc.
                                                          {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Promise_Resolver_Reject};
  auto self = Utils::OpenDirectHandle(this);
  auto promise = i::Cast<i::JSPromise>(self);
  if (promise->status() != Promise::kPending) {
    return Just(true);
  }
  if (i::JSPromise::Reject(promise, Utils::OpenDirectHandle(*value))
          .is_null()) {
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::Just(), v8::Promise::kPending, v8::Utils::OpenDirectHandle(), v8::internal::JSPromise::Reject(), and v8::internal::value.
Resolve()
Maybe< bool > v8::Promise::Resolver::Resolve (Local< Context > context, Local< Value > value)
Resolve/reject the associated promise with a given value.
Ignored if the promise is no longer pending.
Definition at line 8627 of file api.cc.
                                                           {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context,
                           RCCId::kAPI_Promise_Resolver_Resolve};
  auto self = Utils::OpenDirectHandle(this);
  auto promise = i::Cast<i::JSPromise>(self);
  if (promise->status() != Promise::kPending) {
    return Just(true);
  }
  if (i::JSPromise::Resolve(promise, Utils::OpenDirectHandle(*value))
          .is_null()) {
    return {};
  }
  return Just(true);
}
References v8::internal::Isolate::Current(), v8::Just(), v8::Promise::kPending, v8::Utils::OpenDirectHandle(), v8::internal::JSPromise::Resolve(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-promise.h
/mnt/V8SourceCode/src/api/api.cc