v8::internal::compiler::LoadElimination::AliasStateInfo Class Reference
Public Member Functions
AliasStateInfo (const AbstractState *state, Node *object, MapRef map)
AliasStateInfo (const AbstractState *state, Node *object)
bool MayAlias (Node *other) const
Private Attributes
const AbstractState * state_
Node * object_
OptionalMapRef map_
Detailed Description
Definition at line 276 of file load-elimination.cc.
Constructor & Destructor Documentation
AliasStateInfo() [1/2]
v8::internal::compiler::LoadElimination::AliasStateInfo::AliasStateInfo (const AbstractState * state, Node * object, MapRef map) [inline]
Definition at line 278 of file load-elimination.cc.
      : state_(state), object_(object), map_(map) {}
AliasStateInfo() [2/2]
v8::internal::compiler::LoadElimination::AliasStateInfo::AliasStateInfo (const AbstractState * state, Node * object) [inline]
Definition at line 280 of file load-elimination.cc.
      : state_(state), object_(object) {}
Member Function Documentation
MayAlias()
bool v8::internal::compiler::LoadElimination::AliasStateInfo::MayAlias (Node * other) const
Definition at line 710 of file load-elimination.cc.
                                                              {
  // If {object} is being initialized right here (indicated by {object} being
  // an Allocate node instead of a FinishRegion node), we know that {other}
  // can only alias with {object} if they refer to exactly the same node.
  if (object_->opcode() == IrOpcode::kAllocate) {
    return object_ == other;
  }
  // Decide aliasing based on the node kinds.
  if (!compiler::MayAlias(object_, other)) {
    return false;
  }
  // Decide aliasing based on maps (if available).
  if (map_.has_value()) {
    MapRef map = *map_;
    ZoneRefSet<Map> other_maps;
    if (state_->LookupMaps(other, &other_maps) && other_maps.size() == 1) {
      if (map != other_maps.at(0)) {
        return false;
      }
    }
  }
  return true;
}
References v8::internal::ZoneCompactSet< T >::at(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias(), and v8::internal::ZoneCompactSet< T >::size().
Referenced by v8::internal::compiler::LoadElimination::AbstractField::Kill(), and v8::internal::compiler::LoadElimination::AbstractMaps::Kill().
Member Data Documentation
map_
OptionalMapRef v8::internal::compiler::LoadElimination::AliasStateInfo::map_ [private]
Definition at line 288 of file load-elimination.cc.
object_
Node* v8::internal::compiler::LoadElimination::AliasStateInfo::object_ [private]
Definition at line 287 of file load-elimination.cc.
state_
const AbstractState* v8::internal::compiler::LoadElimination::AliasStateInfo::state_ [private]
Definition at line 286 of file load-elimination.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/load-elimination.cc