v8::internal::wasm::LinkageLocationAllocator Class Reference
#include <wasm-linkage.h>
Public Member Functions
template<size_t kNumGpRegs, size_t kNumFpRegs>
constexpr LinkageLocationAllocator (const Register(&gp)[kNumGpRegs], const DoubleRegister(&fp)[kNumFpRegs], int slot_offset)
LinkageLocation Next (MachineRepresentation rep)
int NumStackSlots () const
void EndSlotArea ()
Private Attributes
LinkageAllocator allocator_
int slot_offset_
Detailed Description
Definition at line 264 of file wasm-linkage.h.
Constructor & Destructor Documentation
LinkageLocationAllocator()
template<size_t kNumGpRegs, size_t kNumFpRegs>
constexpr v8::internal::wasm::LinkageLocationAllocator::LinkageLocationAllocator (const Register(&) gp[kNumGpRegs], const DoubleRegister(&) fp[kNumFpRegs], int slot_offset) [inline], [constexpr]
Definition at line 267 of file wasm-linkage.h.
      : allocator_(LinkageAllocator(gp, fp)), slot_offset_(slot_offset) {}
Member Function Documentation
EndSlotArea()
void v8::internal::wasm::LinkageLocationAllocator::EndSlotArea () [inline]
Definition at line 289 of file wasm-linkage.h.
{ allocator_.EndSlotArea(); }
References allocator_, and v8::internal::wasm::LinkageAllocator::EndSlotArea().
Referenced by v8::internal::wasm::IterateSignatureImpl().
Next()
LinkageLocation v8::internal::wasm::LinkageLocationAllocator::Next (MachineRepresentation rep) [inline]
Definition at line 272 of file wasm-linkage.h.
                                                  {
    MachineType type = MachineType::TypeForRepresentation(rep);
    if (IsFloatingPoint(rep)) {
      if (allocator_.CanAllocateFP(rep)) {
        int reg_code = allocator_.NextFpReg(rep);
        return LinkageLocation::ForRegister(reg_code, type);
      }
    } else if (allocator_.CanAllocateGP()) {
      int reg_code = allocator_.NextGpReg();
      return LinkageLocation::ForRegister(reg_code, type);
    }
    // Cannot use register; use stack slot.
    int index = -1 - (slot_offset_ + allocator_.NextStackSlot(rep));
    return LinkageLocation::ForCallerFrameSlot(index, type);
  }
References allocator_, v8::internal::wasm::LinkageAllocator::CanAllocateFP(), v8::internal::wasm::LinkageAllocator::CanAllocateGP(), v8::internal::LinkageLocation::ForCallerFrameSlot(), v8::internal::LinkageLocation::ForRegister(), v8::internal::index, v8::internal::IsFloatingPoint(), v8::internal::wasm::LinkageAllocator::NextFpReg(), v8::internal::wasm::LinkageAllocator::NextGpReg(), v8::internal::wasm::LinkageAllocator::NextStackSlot(), slot_offset_, v8::internal::tracing::type, and v8::internal::MachineType::TypeForRepresentation().
Referenced by v8::internal::wasm::IterateSignatureImpl().
NumStackSlots()
int v8::internal::wasm::LinkageLocationAllocator::NumStackSlots () const [inline]
Definition at line 288 of file wasm-linkage.h.
{ return allocator_.NumStackSlots(); }
References allocator_, and v8::internal::wasm::LinkageAllocator::NumStackSlots().
Referenced by v8::internal::wasm::IterateSignatureImpl().
Member Data Documentation
allocator_
LinkageAllocator v8::internal::wasm::LinkageLocationAllocator::allocator_ [private]
Definition at line 292 of file wasm-linkage.h.
Referenced by EndSlotArea(), Next(), and NumStackSlots().
slot_offset_
int v8::internal::wasm::LinkageLocationAllocator::slot_offset_ [private]
Definition at line 296 of file wasm-linkage.h.
Referenced by Next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-linkage.h