v8::internal::JSPromise Class Reference
#include <js-promise.h>
Public Member Functions
Tagged< Object > result () const
Tagged< Object > reactions () const
bool has_async_task_id () const
uint32_t async_task_id () const
void set_async_task_id (uint32_t id)
V8_EXPORT_PRIVATE Promise::PromiseState status () const
void set_status (Promise::PromiseState status)
Static Public Member Functions
static uint32_t GetNextAsyncTaskId (uint32_t current_async_task_id)
static const char * Status (Promise::PromiseState status)
static V8_EXPORT_PRIVATE Handle< Object > Fulfill (DirectHandle< JSPromise > promise, DirectHandle< Object > value)
static Handle< Object > Reject (DirectHandle< JSPromise > promise, DirectHandle< Object > reason, bool debug_event=true)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > Resolve (DirectHandle< JSPromise > promise, DirectHandle< Object > resolution)
Static Public Attributes
static constexpr uint32_t kInvalidAsyncTaskId = 0
static const int kSizeWithEmbedderFields
Static Private Member Functions
static Handle< Object > TriggerPromiseReactions (Isolate *isolate, DirectHandle< Object > reactions, DirectHandle< Object > argument, PromiseReaction::Type type)
Detailed Description
Definition at line 31 of file js-promise.h.
Member Function Documentation
async_task_id()
uint32_t v8::internal::JSPromise::async_task_id () const [inline]
Definition at line 40 of file js-promise-inl.h.
                                        {
  return AsyncTaskIdBits::decode(flags());
}
References v8::internal::flags.
Referenced by has_async_task_id().
Fulfill()
Handle< Object > v8::internal::JSPromise::Fulfill (DirectHandle< JSPromise > promise, DirectHandle< Object > value) [static]
Definition at line 5049 of file objects.cc.
                                                              {
  Isolate* const isolate = Isolate::Current();
#ifdef V8_ENABLE_JAVASCRIPT_PROMISE_HOOKS
  if (isolate->HasContextPromiseHooks()) {
    isolate->raw_native_context()->RunPromiseHook(
        PromiseHookType::kResolve, indirect_handle(promise, isolate),
        isolate->factory()->undefined_value());
  }
#endif
  // 1. Assert: The value of promise.[[PromiseState]] is "pending".
  CHECK_EQ(Promise::kPending, promise->status());
  // 2. Let reactions be promise.[[PromiseFulfillReactions]].
  DirectHandle<Object> reactions(promise->reactions(), isolate);
  // 3. Set promise.[[PromiseResult]] to value.
  // 4. Set promise.[[PromiseFulfillReactions]] to undefined.
  // 5. Set promise.[[PromiseRejectReactions]] to undefined.
  promise->set_reactions_or_result(Cast<JSAny>(*value));
  // 6. Set promise.[[PromiseState]] to "fulfilled".
  promise->set_status(Promise::kFulfilled);
  // 7. Return TriggerPromiseReactions(reactions, value).
  return TriggerPromiseReactions(isolate, reactions, value,
                                 PromiseReaction::kFulfill);
}
References CHECK_EQ, v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Isolate::HasContextPromiseHooks(), v8::internal::indirect_handle(), v8::internal::PromiseReaction::kFulfill, v8::Promise::kFulfilled, v8::Promise::kPending, v8::kResolve, v8::internal::Isolate::raw_native_context(), and v8::internal::value.
GetNextAsyncTaskId()
uint32_t v8::internal::JSPromise::GetNextAsyncTaskId (uint32_t current_async_task_id) [inline], [static]
Definition at line 28 of file js-promise-inl.h.
                                                             {
  do {
    ++async_task_id;
    async_task_id &= AsyncTaskIdBits::kMax;
  } while (async_task_id == kInvalidAsyncTaskId);
  return async_task_id;
}
Referenced by v8::internal::Isolate::OnAsyncFunctionSuspended(), and v8::internal::Isolate::OnPromiseThen().
has_async_task_id()
bool v8::internal::JSPromise::has_async_task_id () const [inline]
Definition at line 36 of file js-promise-inl.h.
                                        {
  return async_task_id() != kInvalidAsyncTaskId;
}
References async_task_id(), and kInvalidAsyncTaskId.
reactions()
Tagged< Object > v8::internal::JSPromise::reactions () const [inline]
Definition at line 53 of file js-promise-inl.h.
                                          {
  DCHECK_EQ(Promise::kPending, status());
  return reactions_or_result();
}
References DCHECK_EQ, v8::Promise::kPending, and status().
Reject()
Handle< Object > v8::internal::JSPromise::Reject (DirectHandle< JSPromise > promise, DirectHandle< Object > reason, bool debug_event = true) [static]
Definition at line 5100 of file objects.cc.
                                                   {
  Isolate* const isolate = Isolate::Current();
  DCHECK(
      !reinterpret_cast<v8::Isolate*>(isolate)->GetCurrentContext().IsEmpty());
  MoveMessageToPromise(isolate, promise);
  if (debug_event) isolate->debug()->OnPromiseReject(promise, reason);
  isolate->RunAllPromiseHooks(PromiseHookType::kResolve, promise,
                              isolate->factory()->undefined_value());
  // 1. Assert: The value of promise.[[PromiseState]] is "pending".
  CHECK_EQ(Promise::kPending, promise->status());
  // 2. Let reactions be promise.[[PromiseRejectReactions]].
  DirectHandle<Object> reactions(promise->reactions(), isolate);
  // 3. Set promise.[[PromiseResult]] to reason.
  // 4. Set promise.[[PromiseFulfillReactions]] to undefined.
  // 5. Set promise.[[PromiseRejectReactions]] to undefined.
  promise->set_reactions_or_result(Cast<JSAny>(*reason));
  // 6. Set promise.[[PromiseState]] to "rejected".
  promise->set_status(Promise::kRejected);
  // 7. If promise.[[PromiseIsHandled]] is false, perform
  // HostPromiseRejectionTracker(promise, "reject").
  if (!promise->has_handler()) {
    isolate->ReportPromiseReject(promise, reason, kPromiseRejectWithNoHandler);
  }
  // 8. Return TriggerPromiseReactions(reactions, reason).
  return TriggerPromiseReactions(isolate, reactions, reason,
                                 PromiseReaction::kReject);
}
References CHECK_EQ, v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::Promise::kPending, v8::kPromiseRejectWithNoHandler, v8::internal::PromiseReaction::kReject, v8::Promise::kRejected, v8::kResolve, v8::internal::MoveMessageToPromise(), v8::internal::Debug::OnPromiseReject(), v8::internal::Isolate::ReportPromiseReject(), and v8::internal::Isolate::RunAllPromiseHooks().
Referenced by v8::internal::SourceTextModule::AsyncModuleExecutionRejected(), v8::internal::BUILTIN(), v8::internal::Module::Evaluate(), v8::internal::SourceTextModule::Evaluate(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::Promise::Resolver::Reject(), and v8::internal::RUNTIME_FUNCTION().
Resolve()
MaybeHandle< Object > v8::internal::JSPromise::Resolve (DirectHandle< JSPromise > promise, DirectHandle< Object > resolution) [static]
Definition at line 5140 of file objects.cc.
                                                                            {
  Isolate* const isolate = Isolate::Current();
  DCHECK(
      !reinterpret_cast<v8::Isolate*>(isolate)->GetCurrentContext().IsEmpty());
  isolate->RunPromiseHook(PromiseHookType::kResolve, promise,
                          isolate->factory()->undefined_value());
  // 7. If SameValue(resolution, promise) is true, then
  if (promise.is_identical_to(resolution_obj)) {
    // a. Let selfResolutionError be a newly created TypeError object.
    DirectHandle<Object> self_resolution_error =
        isolate->factory()->NewTypeError(MessageTemplate::kPromiseCyclic,
                                         resolution_obj);
    // b. Return RejectPromise(promise, selfResolutionError).
    return Reject(promise, self_resolution_error);
  }
  // 8. If Type(resolution) is not Object, then
  DirectHandle<JSReceiver> resolution_recv;
  if (!TryCast<JSReceiver>(resolution_obj, &resolution_recv)) {
    // a. Return FulfillPromise(promise, resolution).
    return Fulfill(promise, resolution_obj);
  }
  // 9. Let then be Get(resolution, "then").
  MaybeDirectHandle<Object> then;
  // Make sure a lookup of "then" on any JSPromise whose [[Prototype]] is the
  // initial %PromisePrototype% yields the initial method. In addition this
  // protector also guards the negative lookup of "then" on the intrinsic
  // %ObjectPrototype%, meaning that such lookups are guaranteed to yield
  // undefined without triggering any side-effects.
  if (IsJSPromise(*resolution_recv) &&
      resolution_recv->map()->prototype()->map()->instance_type() ==
          JS_PROMISE_PROTOTYPE_TYPE &&
      Protectors::IsPromiseThenLookupChainIntact(isolate)) {
    // We can skip the "then" lookup on {resolution} if its [[Prototype]]
    // is the (initial) Promise.prototype and the Promise#then protector
    // is intact, as that guards the lookup path for the "then" property
    // on JSPromise instances which have the (initial) %PromisePrototype%.
    then = isolate->promise_then();
  } else {
    then = JSReceiver::GetProperty(isolate, resolution_recv,
                                   isolate->factory()->then_string());
  }
  // 10. If then is an abrupt completion, then
  DirectHandle<Object> then_action;
  if (!then.ToHandle(&then_action)) {
    // The "then" lookup can cause termination.
    if (!isolate->is_catchable_by_javascript(isolate->exception())) {
      return kNullMaybeHandle;
    }
    // a. Return RejectPromise(promise, then.[[Value]]).
    DirectHandle<Object> reason(isolate->exception(), isolate);
    isolate->clear_exception();
    return Reject(promise, reason, false);
  }
  // 11. Let thenAction be then.[[Value]].
  // 12. If IsCallable(thenAction) is false, then
  if (!IsCallable(*then_action)) {
    // a. Return FulfillPromise(promise, resolution).
    return Fulfill(promise, resolution_recv);
  }
  // 13. Let job be NewPromiseResolveThenableJob(promise, resolution,
  // thenAction).
  DirectHandle<NativeContext> then_context;
  if (!JSReceiver::GetContextForMicrotask(Cast<JSReceiver>(then_action))
           .ToHandle(&then_context)) {
    then_context = isolate->native_context();
  }
  DirectHandle<PromiseResolveThenableJobTask> task =
      isolate->factory()->NewPromiseResolveThenableJobTask(
          promise, resolution_recv, Cast<JSReceiver>(then_action),
          then_context);
  if (isolate->debug()->is_active() && IsJSPromise(*resolution_recv)) {
    // Mark the dependency of the new {promise} on the {resolution}.
    Object::SetProperty(isolate, resolution_recv,
                        isolate->factory()->promise_handled_by_symbol(),
                        promise)
        .Check();
  }
  MicrotaskQueue* microtask_queue = then_context->microtask_queue();
  if (microtask_queue) microtask_queue->EnqueueMicrotask(*task);
  // 15. Return undefined.
  return isolate->factory()->undefined_value();
}
References v8::internal::Isolate::clear_exception(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::internal::Isolate::exception(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetContextForMicrotask(), v8::internal::JSReceiver::GetProperty(), v8::internal::Debug::is_active(), v8::internal::Isolate::is_catchable_by_javascript(), v8::internal::DirectHandle< T >::is_identical_to(), v8::internal::kNullMaybeHandle, v8::kResolve, v8::internal::Isolate::native_context(), v8::internal::Factory::NewPromiseResolveThenableJobTask(), v8::internal::Isolate::RunPromiseHook(), v8::internal::Object::SetProperty(), v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::SourceTextModule::AsyncModuleExecutionFulfilled(), v8::internal::BUILTIN(), v8::internal::SyntheticModule::Evaluate(), v8::internal::SourceTextModule::Evaluate(), v8::internal::JSAtomicsMutex::HandleAsyncNotify(), v8::internal::JSAtomicsCondition::HandleAsyncNotify(), v8::internal::JSAtomicsMutex::HandleAsyncTimeout(), v8::internal::JSAtomicsMutex::LockAsync(), v8::internal::JSAsyncDisposableStack::NextDisposeAsyncIteration(), v8::Promise::Resolver::Resolve(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromise(), and v8::internal::RUNTIME_FUNCTION().
result()
Tagged< Object > v8::internal::JSPromise::result () const [inline]
Definition at line 48 of file js-promise-inl.h.
                                       {
  DCHECK_NE(Promise::kPending, status());
  return reactions_or_result();
}
References DCHECK_NE, v8::Promise::kPending, and status().
set_async_task_id()
void v8::internal::JSPromise::set_async_task_id (uint32_t id) [inline]
Definition at line 44 of file js-promise-inl.h.
                                             {
  set_flags(AsyncTaskIdBits::update(flags(), id));
}
References v8::internal::flags.
set_status()
void v8::internal::JSPromise::set_status (Promise::PromiseState status)
Definition at line 5030 of file objects.cc.
                                                     {
  int value = flags() & ~StatusBits::kMask;
  set_flags(value | status);
}
References v8::internal::Script::flags(), v8::internal::Script::set_flags(), v8::internal::status, and v8::internal::value.
status()
v8::Promise::PromiseState v8::internal::JSPromise::status () const
Definition at line 5024 of file objects.cc.
                                              {
  int value = flags() & StatusBits::kMask;
  DCHECK(value == 0 || value == 1 || value == 2);
  return static_cast<v8::Promise::PromiseState>(value);
}
References v8::internal::DCHECK(), v8::internal::Script::flags(), and v8::internal::value.
Referenced by reactions(), and result().
Status()
const char * v8::internal::JSPromise::Status (Promise::PromiseState status) [static]
Definition at line 5036 of file objects.cc.
                                                          {
  switch (status) {
    case v8::Promise::kFulfilled:
      return "fulfilled";
    case v8::Promise::kPending:
      return "pending";
    case v8::Promise::kRejected:
      return "rejected";
  }
  UNREACHABLE();
}
References v8::Promise::kFulfilled, v8::Promise::kPending, v8::Promise::kRejected, v8::internal::status, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Runtime::GetInternalProperties().
TriggerPromiseReactions()
Handle< Object > v8::internal::JSPromise::TriggerPromiseReactions (Isolate * isolate, DirectHandle< Object > reactions, DirectHandle< Object > argument, PromiseReaction::Type type) [static], [private]
Definition at line 5236 of file objects.cc.
                                                             {
  CHECK(IsSmi(*reactions) || IsPromiseReaction(*reactions));
  // We need to reverse the {reactions} here, since we record them
  // on the JSPromise in the reverse order.
  {
    DisallowGarbageCollection no_gc;
    Tagged<UnionOf<Smi, PromiseReaction>> current =
        Cast<UnionOf<Smi, PromiseReaction>>(*reactions);
    Tagged<UnionOf<Smi, PromiseReaction>> reversed = Smi::zero();
    while (!IsSmi(current)) {
      Tagged<UnionOf<Smi, PromiseReaction>> next =
          Cast<PromiseReaction>(current)->next();
      Cast<PromiseReaction>(current)->set_next(reversed);
      reversed = current;
      current = next;
    }
    reactions = direct_handle(reversed, isolate);
  }
  // Morph the {reactions} into PromiseReactionJobTasks
  // and push them onto the microtask queue.
  while (!IsSmi(*reactions)) {
    auto task = Cast<HeapObject>(reactions);
    auto reaction = Cast<PromiseReaction>(task);
    reactions = direct_handle(reaction->next(), isolate);
    // According to HTML, we use the context of the appropriate handler as the
    // context of the microtask. See step 3 of HTML's EnqueueJob:
    // https://html.spec.whatwg.org/C/#enqueuejob(queuename,-job,-arguments)
    DirectHandle<NativeContext> handler_context;
    DirectHandle<UnionOf<Undefined, JSCallable>> primary_handler;
    DirectHandle<UnionOf<Undefined, JSCallable>> secondary_handler;
    if (type == PromiseReaction::kFulfill) {
      primary_handler = direct_handle(reaction->fulfill_handler(), isolate);
      secondary_handler = direct_handle(reaction->reject_handler(), isolate);
    } else {
      primary_handler = direct_handle(reaction->reject_handler(), isolate);
      secondary_handler = direct_handle(reaction->fulfill_handler(), isolate);
    }
    bool has_handler_context = false;
    if (IsJSReceiver(*primary_handler)) {
      has_handler_context =
          JSReceiver::GetContextForMicrotask(Cast<JSReceiver>(primary_handler))
              .ToHandle(&handler_context);
    }
    if (!has_handler_context && IsJSReceiver(*secondary_handler)) {
      has_handler_context = JSReceiver::GetContextForMicrotask(
                                Cast<JSReceiver>(secondary_handler))
                                .ToHandle(&handler_context);
    }
    if (!has_handler_context) handler_context = isolate->native_context();
    static_assert(
        static_cast<int>(PromiseReaction::kSize) ==
        static_cast<int>(
            PromiseReactionJobTask::kSizeOfAllPromiseReactionJobTasks));
    if (type == PromiseReaction::kFulfill) {
      task->set_map(
          isolate,
          ReadOnlyRoots(isolate).promise_fulfill_reaction_job_task_map(),
          kReleaseStore);
      Cast<PromiseFulfillReactionJobTask>(task)->set_argument(*argument);
      Cast<PromiseFulfillReactionJobTask>(task)->set_context(*handler_context);
      static_assert(
          static_cast<int>(PromiseReaction::kFulfillHandlerOffset) ==
          static_cast<int>(PromiseFulfillReactionJobTask::kHandlerOffset));
      static_assert(
          static_cast<int>(PromiseReaction::kPromiseOrCapabilityOffset) ==
          static_cast<int>(
              PromiseFulfillReactionJobTask::kPromiseOrCapabilityOffset));
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
      static_assert(
          static_cast<int>(
              PromiseReaction::kContinuationPreservedEmbedderDataOffset) ==
          static_cast<int>(PromiseFulfillReactionJobTask::
                               kContinuationPreservedEmbedderDataOffset));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    } else {
      DisallowGarbageCollection no_gc;
      task->set_map(
          isolate,
          ReadOnlyRoots(isolate).promise_reject_reaction_job_task_map(),
          kReleaseStore);
      Cast<PromiseRejectReactionJobTask>(task)->set_argument(*argument);
      Cast<PromiseRejectReactionJobTask>(task)->set_context(*handler_context);
      Cast<PromiseRejectReactionJobTask>(task)->set_handler(*primary_handler);
      static_assert(
          static_cast<int>(PromiseReaction::kPromiseOrCapabilityOffset) ==
          static_cast<int>(
              PromiseRejectReactionJobTask::kPromiseOrCapabilityOffset));
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
      static_assert(
          static_cast<int>(
              PromiseReaction::kContinuationPreservedEmbedderDataOffset) ==
          static_cast<int>(PromiseRejectReactionJobTask::
                               kContinuationPreservedEmbedderDataOffset));
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
    }
    MicrotaskQueue* microtask_queue = handler_context->microtask_queue();
    if (microtask_queue) {
      microtask_queue->EnqueueMicrotask(*Cast<PromiseReactionJobTask>(task));
    }
  }
  return isolate->factory()->undefined_value();
}
References CHECK, v8::internal::direct_handle(), v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetContextForMicrotask(), v8::internal::IsSmi(), v8::internal::PromiseReaction::kFulfill, v8::kReleaseStore, v8::internal::PromiseReactionJobTask::kSizeOfAllPromiseReactionJobTasks, v8::internal::Isolate::native_context(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::tracing::type, and v8::internal::Smi::zero().
Member Data Documentation
kInvalidAsyncTaskId
constexpr uint32_t v8::internal::JSPromise::kInvalidAsyncTaskId = 0 [static], [constexpr]
Definition at line 34 of file js-promise.h.
Referenced by has_async_task_id().
kSizeWithEmbedderFields
const int v8::internal::JSPromise::kSizeWithEmbedderFields [static]
Initial value:
=
      kHeaderSize + v8::Promise::kEmbedderFieldCount * kEmbedderDataSlotSize
Definition at line 75 of file js-promise.h.
Referenced by v8::internal::PromiseBuiltinsAssembler::AllocateJSPromise(), v8::internal::Genesis::InitializeGlobal(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), and v8::internal::PromiseBuiltinsAssembler::ZeroOutEmbedderOffsets().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-promise.h
/mnt/V8SourceCode/src/objects/js-promise-inl.h
/mnt/V8SourceCode/src/objects/objects.cc