v8::internal::SourcePositionTableIterator Class Reference
#include <source-position-table.h>
Classes
struct IndexAndPositionState
Public Types
enum IterationFilter { kJavaScriptOnly = 0
, kExternalOnly = 1
, kAll = 2
 }
enum FunctionEntryFilter { kSkipFunctionEntry = 0
, kDontSkipFunctionEntry = 1
 }
Public Member Functions
SourcePositionTableIterator (Handle< TrustedByteArray > byte_array, IterationFilter iteration_filter=kJavaScriptOnly, FunctionEntryFilter function_entry_filter=kSkipFunctionEntry)
SourcePositionTableIterator (Tagged< TrustedByteArray > byte_array, IterationFilter iteration_filter=kJavaScriptOnly, FunctionEntryFilter function_entry_filter=kSkipFunctionEntry)
SourcePositionTableIterator (base::Vector< const uint8_t > bytes, IterationFilter iteration_filter=kJavaScriptOnly, FunctionEntryFilter function_entry_filter=kSkipFunctionEntry)
void Advance ()
int code_offset () const
SourcePosition source_position () const
bool is_statement () const
bool is_breakable () const
bool done () const
IndexAndPositionState GetState () const
void RestoreState (const IndexAndPositionState &saved_state)
Private Member Functions
void Initialize ()
Private Attributes
base::Vector< const uint8_t > raw_table_
Handle< TrustedByteArray > table_
int index_ = 0
PositionTableEntry current_
IterationFilter iteration_filter_
FunctionEntryFilter function_entry_filter_
Static Private Attributes
static const int kDone = -1
Detailed Description
Definition at line 79 of file source-position-table.h.
Member Enumeration Documentation
FunctionEntryFilter
enum v8::internal::SourcePositionTableIterator::FunctionEntryFilter
Enumerator
kSkipFunctionEntry
kDontSkipFunctionEntry
Definition at line 87 of file source-position-table.h.
                           {
    kSkipFunctionEntry = 0,
    kDontSkipFunctionEntry = 1
  };
IterationFilter
enum v8::internal::SourcePositionTableIterator::IterationFilter
Enumerator
kJavaScriptOnly
kExternalOnly
kAll
Definition at line 83 of file source-position-table.h.
{ kJavaScriptOnly = 0, kExternalOnly = 1, kAll = 2 };
Constructor & Destructor Documentation
SourcePositionTableIterator() [1/3]
v8::internal::SourcePositionTableIterator::SourcePositionTableIterator (Handle< TrustedByteArray > byte_array, IterationFilter iteration_filter = kJavaScriptOnly, FunctionEntryFilter function_entry_filter = kSkipFunctionEntry) [explicit]
Definition at line 257 of file source-position-table.cc.
    : table_(byte_array),
      iteration_filter_(iteration_filter),
      function_entry_filter_(function_entry_filter) {
  Initialize();
#ifdef DEBUG
  // We can enable allocation because we keep the table in a handle.
  no_gc.Release();
#endif // DEBUG
}
References Initialize(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::Release().
SourcePositionTableIterator() [2/3]
v8::internal::SourcePositionTableIterator::SourcePositionTableIterator (Tagged< TrustedByteArray > byte_array, IterationFilter iteration_filter = kJavaScriptOnly, FunctionEntryFilter function_entry_filter = kSkipFunctionEntry) [explicit]
Definition at line 248 of file source-position-table.cc.
    : raw_table_(VectorFromByteArray(byte_array)),
      iteration_filter_(iteration_filter),
      function_entry_filter_(function_entry_filter) {
  Initialize();
}
References Initialize().
SourcePositionTableIterator() [3/3]
v8::internal::SourcePositionTableIterator::SourcePositionTableIterator (base::Vector< const uint8_t > bytes, IterationFilter iteration_filter = kJavaScriptOnly, FunctionEntryFilter function_entry_filter = kSkipFunctionEntry) [explicit]
Definition at line 270 of file source-position-table.cc.
    : raw_table_(bytes),
      iteration_filter_(iteration_filter),
      function_entry_filter_(function_entry_filter) {
  Initialize();
#ifdef DEBUG
  // We can enable allocation because the underlying vector does not move.
  no_gc.Release();
#endif // DEBUG
}
References Initialize(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::PerThreadAssertScopeEmpty< kAllow, kTypes >::Release().
Member Function Documentation
Advance()
void v8::internal::SourcePositionTableIterator::Advance ()
Definition at line 283 of file source-position-table.cc.
                                          {
  base::Vector<const uint8_t> bytes =
      table_.is_null() ? raw_table_ : VectorFromByteArray(*table_);
  DCHECK(!done());
  DCHECK(index_ >= 0 && index_ <= bytes.length());
  bool filter_satisfied = false;
  while (!done() && !filter_satisfied) {
    if (index_ >= bytes.length()) {
      index_ = kDone;
    } else {
      PositionTableEntry tmp;
      DecodeEntry(bytes, &index_, &tmp);
      AddAndSetEntry(&current_, tmp);
      SourcePosition p = source_position();
      filter_satisfied =
          (iteration_filter_ == kAll) ||
          (iteration_filter_ == kJavaScriptOnly && p.IsJavaScript()) ||
          (iteration_filter_ == kExternalOnly && p.IsExternal());
    }
  }
}
References v8::internal::anonymous_namespace{source-position-table.cc}::AddAndSetEntry(), current_, v8::internal::DCHECK(), v8::internal::anonymous_namespace{source-position-table.cc}::DecodeEntry(), done(), index_, v8::internal::SourcePosition::IsExternal(), v8::internal::SourcePosition::IsJavaScript(), iteration_filter_, kAll, kDone, kExternalOnly, kJavaScriptOnly, v8::base::Vector< T >::length(), raw_table_, source_position(), table_, and v8::internal::anonymous_namespace{source-position-table.cc}::VectorFromByteArray().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), v8::internal::BytecodeArray::Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), Initialize(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::BreakIterator::Next(), v8::internal::maglev::MaglevGraphBuilder::UpdateSourceAndBytecodePosition(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
code_offset()
int v8::internal::SourcePositionTableIterator::code_offset () const [inline]
Definition at line 127 of file source-position-table.h.
                          {
    DCHECK(!done());
    return current_.code_offset;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), v8::internal::BytecodeArray::Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::maglev::MaglevGraphBuilder::UpdateSourceAndBytecodePosition(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
done()
bool v8::internal::SourcePositionTableIterator::done () const [inline]
Definition at line 143 of file source-position-table.h.
{ return index_ == kDone; }
Referenced by Advance(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::ProfilerListener::CodeCreateEvent(), v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), v8::internal::wasm::WasmCode::Disassemble(), v8::internal::BytecodeArray::Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), v8::internal::wasm::WasmCode::GetSourcePositionBefore(), Initialize(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::BytecodeArray::SourcePosition(), v8::internal::Code::SourcePosition(), v8::internal::BytecodeArray::SourceStatementPosition(), v8::internal::Code::SourceStatementPosition(), v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable(), v8::internal::maglev::MaglevGraphBuilder::UpdateSourceAndBytecodePosition(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
GetState()
IndexAndPositionState v8::internal::SourcePositionTableIterator::GetState () const [inline]
Definition at line 145 of file source-position-table.h.
                                         {
    return {index_, current_, iteration_filter_, function_entry_filter_};
  }
Initialize()
void v8::internal::SourcePositionTableIterator::Initialize () [private]
Definition at line 240 of file source-position-table.cc.
                                             {
  Advance();
  if (function_entry_filter_ == kSkipFunctionEntry &&
      current_.code_offset == kFunctionEntryBytecodeOffset && !done()) {
    Advance();
  }
}
References Advance(), v8::internal::PositionTableEntry::code_offset, current_, done(), function_entry_filter_, v8::internal::kFunctionEntryBytecodeOffset, and kSkipFunctionEntry.
Referenced by SourcePositionTableIterator().
is_breakable()
bool v8::internal::SourcePositionTableIterator::is_breakable () const [inline]
Definition at line 139 of file source-position-table.h.
                            {
    DCHECK(!done());
    return current_.is_breakable;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::BytecodeArray::Disassemble(), and v8::internal::BreakIterator::Next().
is_statement()
bool v8::internal::SourcePositionTableIterator::is_statement () const [inline]
Definition at line 135 of file source-position-table.h.
                            {
    DCHECK(!done());
    return current_.is_statement;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), v8::internal::BytecodeArray::Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), v8::internal::BreakIterator::GetDebugBreakType(), and v8::internal::BreakIterator::Next().
RestoreState()
void v8::internal::SourcePositionTableIterator::RestoreState (const IndexAndPositionState & saved_state) [inline]
Definition at line 149 of file source-position-table.h.
                                                              {
    index_ = saved_state.index_;
    current_ = saved_state.position_;
    iteration_filter_ = saved_state.iteration_filter_;
    function_entry_filter_ = saved_state.function_entry_filter_;
  }
References v8::internal::SourcePositionTableIterator::IndexAndPositionState::function_entry_filter_, v8::internal::SourcePositionTableIterator::IndexAndPositionState::index_, v8::internal::SourcePositionTableIterator::IndexAndPositionState::iteration_filter_, and v8::internal::SourcePositionTableIterator::IndexAndPositionState::position_.
source_position()
SourcePosition v8::internal::SourcePositionTableIterator::source_position () const [inline]
Definition at line 131 of file source-position-table.h.
                                         {
    DCHECK(!done());
    return SourcePosition::FromRaw(current_.source_position);
  }
References v8::internal::DCHECK(), and v8::internal::SourcePosition::FromRaw().
Referenced by Advance(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), v8::internal::BytecodeArray::Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::BreakIterator::Next(), v8::internal::maglev::MaglevGraphBuilder::UpdateSourceAndBytecodePosition(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
Member Data Documentation
current_
PositionTableEntry v8::internal::SourcePositionTableIterator::current_ [private]
Definition at line 166 of file source-position-table.h.
Referenced by Advance(), and Initialize().
function_entry_filter_
FunctionEntryFilter v8::internal::SourcePositionTableIterator::function_entry_filter_ [private]
Definition at line 168 of file source-position-table.h.
Referenced by Initialize().
index_
int v8::internal::SourcePositionTableIterator::index_ = 0 [private]
Definition at line 165 of file source-position-table.h.
Referenced by Advance().
iteration_filter_
IterationFilter v8::internal::SourcePositionTableIterator::iteration_filter_ [private]
Definition at line 167 of file source-position-table.h.
Referenced by Advance().
kDone
const int v8::internal::SourcePositionTableIterator::kDone = -1 [static], [private]
Definition at line 161 of file source-position-table.h.
Referenced by Advance().
raw_table_
base::Vector<const uint8_t> v8::internal::SourcePositionTableIterator::raw_table_ [private]
Definition at line 163 of file source-position-table.h.
Referenced by Advance().
table_
Handle<TrustedByteArray> v8::internal::SourcePositionTableIterator::table_ [private]
Definition at line 164 of file source-position-table.h.
Referenced by Advance().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/source-position-table.h
/mnt/V8SourceCode/src/codegen/source-position-table.cc