v8::internal::maglev::InitialValue Class Reference
#include <maglev-ir.h>
Public Member Functions
InitialValue (uint64_t bitfield, interpreter::Register source)
interpreter::Register source () const
uint32_t stack_slot () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Member Functions
static uint32_t stack_slot (uint32_t register_idx)
Private Types
using Base = FixedInputValueNodeT< 0, InitialValue >
Private Attributes
const interpreter::Register source_
Additional Inherited Members
Detailed Description
Definition at line 5486 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::InitialValue::Base = FixedInputValueNodeT<0, InitialValue> [private]
Definition at line 5487 of file maglev-ir.h.
Constructor & Destructor Documentation
InitialValue()
v8::internal::maglev::InitialValue::InitialValue (uint64_t bitfield, interpreter::Register source) [explicit]
Definition at line 167 of file maglev-ir.cc.
    : Base(bitfield), source_(source) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::InitialValue::GenerateCode (MaglevAssembler * , const ProcessingState &)
options()
auto v8::internal::maglev::InitialValue::options () const [inline]
Definition at line 5500 of file maglev-ir.h.
{ return std::tuple{source()}; }
References source().
PrintParams()
void v8::internal::maglev::InitialValue::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7942 of file maglev-ir.cc.
                                                                          {
  os << "(" << source().ToString() << ")";
}
References source(), and v8::internal::interpreter::Register::ToString().
SetValueLocationConstraints()
void v8::internal::maglev::InitialValue::SetValueLocationConstraints ()
source()
interpreter::Register v8::internal::maglev::InitialValue::source () const [inline]
Definition at line 5492 of file maglev-ir.h.
{ return source_; }
References source_.
Referenced by options(), PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
stack_slot() [1/2]
uint32_t v8::internal::maglev::InitialValue::stack_slot () const
Referenced by v8::internal::maglev::Graph::min_maglev_stackslots_for_unoptimized_frame_size().
stack_slot() [2/2]
static uint32_t v8::internal::maglev::InitialValue::stack_slot (uint32_t register_idx) [static]
Member Data Documentation
source_
const interpreter::Register v8::internal::maglev::InitialValue::source_ [private]
Definition at line 5503 of file maglev-ir.h.
Referenced by source().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc