v8::internal::PersistentHandlesScope Class Reference
#include <persistent-handles.h>
Public Member Functions
V8_EXPORT_PRIVATE PersistentHandlesScope (Isolate *isolate)
V8_EXPORT_PRIVATE ~PersistentHandlesScope ()
V8_EXPORT_PRIVATE std::unique_ptr< PersistentHandles > Detach ()
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsActive (Isolate *isolate)
Private Attributes
Address * first_block_
Address * prev_limit_
Address * prev_next_
HandleScopeImplementer *const impl_
Detailed Description
Definition at line 119 of file persistent-handles.h.
Constructor & Destructor Documentation
PersistentHandlesScope()
v8::internal::PersistentHandlesScope::PersistentHandlesScope (Isolate * isolate) [explicit]
Definition at line 133 of file persistent-handles.cc.
    : impl_(isolate->handle_scope_implementer()) {
  impl_->BeginPersistentScope();
  HandleScopeData* data = impl_->isolate()->handle_scope_data();
  Address* new_next = impl_->GetSpareOrNewBlock();
  Address* new_limit = &new_next[kHandleBlockSize];
  impl_->blocks()->push_back(new_next);
#ifdef DEBUG
  prev_level_ = data->level;
#endif
  data->level++;
  first_block_ = new_next;
  prev_limit_ = data->limit;
  prev_next_ = data->next;
  data->next = new_next;
  data->limit = new_limit;
}
References v8::internal::HandleScopeImplementer::BeginPersistentScope(), v8::internal::HandleScopeImplementer::blocks(), first_block_, v8::internal::HandleScopeImplementer::GetSpareOrNewBlock(), v8::internal::Isolate::handle_scope_data(), impl_, v8::internal::HandleScopeImplementer::isolate(), v8::internal::kHandleBlockSize, v8::internal::HandleScopeData::level, v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, prev_limit_, and prev_next_.
 PersistentHandlesScope()
v8::internal::PersistentHandlesScope::~PersistentHandlesScope ()
Definition at line 152 of file persistent-handles.cc.
                                                {
  DCHECK(handles_detached_);
  impl_->isolate()->handle_scope_data()->level--;
  DCHECK_EQ(impl_->isolate()->handle_scope_data()->level, prev_level_);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::handle_scope_data(), impl_, v8::internal::HandleScopeImplementer::isolate(), and v8::internal::HandleScopeData::level.
Member Function Documentation
Detach()
std::unique_ptr< PersistentHandles > v8::internal::PersistentHandlesScope::Detach ()
Definition at line 158 of file persistent-handles.cc.
                                                                {
  std::unique_ptr<PersistentHandles> ph = impl_->DetachPersistent(first_block_);
  HandleScopeData* data = impl_->isolate()->handle_scope_data();
  data->next = prev_next_;
  data->limit = prev_limit_;
#ifdef DEBUG
  handles_detached_ = true;
#endif
  return ph;
}
References v8::internal::HandleScopeImplementer::DetachPersistent(), first_block_, v8::internal::Isolate::handle_scope_data(), impl_, v8::internal::HandleScopeImplementer::isolate(), v8::internal::HandleScopeData::limit, v8::internal::HandleScopeData::next, prev_limit_, and prev_next_.
Referenced by v8::internal::CompilationHandleScope::~CompilationHandleScope().
IsActive()
bool v8::internal::PersistentHandlesScope::IsActive (Isolate * isolate) [static]
Definition at line 170 of file persistent-handles.cc.
                                                      {
  return isolate->handle_scope_implementer()->HasPersistentScope();
}
References v8::internal::Isolate::handle_scope_implementer(), and v8::internal::HandleScopeImplementer::HasPersistentScope().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::CanonicalHandle(), v8::internal::OptimizedCompilationInfo::CanonicalHandle(), v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle(), and v8::internal::compiler::ObjectData::ObjectData().
Member Data Documentation
first_block_
Address* v8::internal::PersistentHandlesScope::first_block_ [private]
Definition at line 132 of file persistent-handles.h.
Referenced by Detach(), and PersistentHandlesScope().
impl_
HandleScopeImplementer* const v8::internal::PersistentHandlesScope::impl_ [private]
Definition at line 135 of file persistent-handles.h.
Referenced by Detach(), PersistentHandlesScope(), and ~PersistentHandlesScope().
prev_limit_
Address* v8::internal::PersistentHandlesScope::prev_limit_ [private]
Definition at line 133 of file persistent-handles.h.
Referenced by Detach(), and PersistentHandlesScope().
prev_next_
Address* v8::internal::PersistentHandlesScope::prev_next_ [private]
Definition at line 134 of file persistent-handles.h.
Referenced by Detach(), and PersistentHandlesScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/persistent-handles.h
/mnt/V8SourceCode/src/handles/persistent-handles.cc