v8::internal::CombinedHeapObjectIterator Class Reference
#include <combined-heap.h>
Public Member Functions
CombinedHeapObjectIterator (Heap *heap, HeapObjectIterator::HeapObjectsFiltering filtering=HeapObjectIterator::HeapObjectsFiltering::kNoFiltering)
Tagged< HeapObject > Next ()
Private Attributes
HeapObjectIterator heap_iterator_
ReadOnlyHeapObjectIterator ro_heap_iterator_
Detailed Description
Definition at line 19 of file combined-heap.h.
Constructor & Destructor Documentation
CombinedHeapObjectIterator()
v8::internal::CombinedHeapObjectIterator::CombinedHeapObjectIterator (Heap * heap, HeapObjectIterator::HeapObjectsFiltering filtering = HeapObjectIterator::HeapObjectsFiltering::kNoFiltering)
Definition at line 11 of file combined-heap.cc.
    : heap_iterator_(heap, filtering),
      ro_heap_iterator_(heap->isolate()->read_only_heap()) {}
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::CombinedHeapObjectIterator::Next ()
Definition at line 16 of file combined-heap.cc.
                                                    {
  Tagged<HeapObject> object = ro_heap_iterator_.Next();
  if (!object.is_null()) {
    return object;
  }
  return heap_iterator_.Next();
}
References heap_iterator_, v8::internal::HeapObjectIterator::Next(), v8::internal::ReadOnlyHeapObjectIterator::Next(), and ro_heap_iterator_.
Referenced by v8::internal::V8HeapExplorer::EstimateObjectsCount(), v8::internal::HeapProfiler::FindHeapObjectById(), v8::internal::V8HeapExplorer::IterateAndExtractReferences(), v8::internal::anonymous_namespace{object-stats.cc}::IterateHeap(), v8::internal::V8FileLogger::LogAllMaps(), v8::internal::ExistingCodeLogger::LogCodeObjects(), v8::internal::HeapProfiler::QueryObjects(), and v8::internal::HeapObjectsMap::UpdateHeapObjectsMap().
Member Data Documentation
heap_iterator_
HeapObjectIterator v8::internal::CombinedHeapObjectIterator::heap_iterator_ [private]
Definition at line 27 of file combined-heap.h.
Referenced by Next().
ro_heap_iterator_
ReadOnlyHeapObjectIterator v8::internal::CombinedHeapObjectIterator::ro_heap_iterator_ [private]
Definition at line 28 of file combined-heap.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/combined-heap.h
/mnt/V8SourceCode/src/heap/combined-heap.cc