v8::internal::GCCallbacksScope Class Reference
#include <heap.h>
Public Member Functions
GCCallbacksScope (Heap *heap)
~GCCallbacksScope ()
bool CheckReenter () const
Private Attributes
Heap *const heap_
Detailed Description
Definition at line 2614 of file heap.h.
Constructor & Destructor Documentation
GCCallbacksScope()
v8::internal::GCCallbacksScope::GCCallbacksScope (Heap * heap) [explicit]
Definition at line 1195 of file heap.cc.
                                             : heap_(heap) {
  heap_->gc_callbacks_depth_++;
}
References v8::internal::Heap::gc_callbacks_depth_, and heap_.
 GCCallbacksScope()
v8::internal::GCCallbacksScope::~GCCallbacksScope ()
Definition at line 1199 of file heap.cc.
{ heap_->gc_callbacks_depth_--; }
References v8::internal::Heap::gc_callbacks_depth_, and heap_.
Member Function Documentation
CheckReenter()
bool v8::internal::GCCallbacksScope::CheckReenter () const
Definition at line 1201 of file heap.cc.
                                          {
  return heap_->gc_callbacks_depth_ == 1;
}
References v8::internal::Heap::gc_callbacks_depth_, and heap_.
Referenced by v8::internal::Heap::CallGCEpilogueCallbacks(), v8::internal::Heap::CallGCPrologueCallbacks(), and v8::internal::GlobalHandles::InvokeSecondPassPhantomCallbacks().
Member Data Documentation
heap_
Heap* const v8::internal::GCCallbacksScope::heap_ [private]
Definition at line 2622 of file heap.h.
Referenced by CheckReenter(), GCCallbacksScope(), and ~GCCallbacksScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap.cc