v8::internal::RegExpMacroAssemblerTracer Class Reference
#include <regexp-macro-assembler-tracer.h>
Public Member Functions
RegExpMacroAssemblerTracer (Isolate *isolate, RegExpMacroAssembler *assembler)
~RegExpMacroAssemblerTracer () override
void AbortedCodeGeneration () override
int stack_limit_slack_slot_count () override
bool CanReadUnaligned () const override
void AdvanceCurrentPosition (int by) override
void AdvanceRegister (int reg, int by) override
void Backtrack () override
void Bind (Label *label) override
void CheckCharacter (unsigned c, Label *on_equal) override
void CheckCharacterAfterAnd (unsigned c, unsigned and_with, Label *on_equal) override
void CheckCharacterGT (base::uc16 limit, Label *on_greater) override
void CheckCharacterLT (base::uc16 limit, Label *on_less) override
void CheckFixedLengthLoop (Label *on_tos_equals_current_position) override
void CheckAtStart (int cp_offset, Label *on_at_start) override
void CheckNotAtStart (int cp_offset, Label *on_not_at_start) override
void CheckNotBackReference (int start_reg, bool read_backward, Label *on_no_match) override
void CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label *on_no_match) override
void CheckNotCharacter (unsigned c, Label *on_not_equal) override
void CheckNotCharacterAfterAnd (unsigned c, unsigned and_with, Label *on_not_equal) override
void CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 and_with, Label *on_not_equal) override
void CheckCharacterInRange (base::uc16 from, base::uc16 to, Label *on_in_range) override
void CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label *on_not_in_range) override
bool CheckCharacterInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_in_range) override
bool CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_not_in_range) override
void CheckBitInTable (Handle< ByteArray > table, Label *on_bit_set) override
bool SkipUntilBitInTableUseSimd (int advance_by) override
void SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) override
void CheckPosition (int cp_offset, Label *on_outside_input) override
bool CheckSpecialClassRanges (StandardCharacterSet type, Label *on_no_match) override
void Fail () override
DirectHandle< HeapObject > GetCode (DirectHandle< String > source, RegExpFlags flags) override
void GoTo (Label *label) override
void IfRegisterGE (int reg, int comparand, Label *if_ge) override
void IfRegisterLT (int reg, int comparand, Label *if_lt) override
void IfRegisterEqPos (int reg, Label *if_eq) override
IrregexpImplementation Implementation () override
void LoadCurrentCharacterImpl (int cp_offset, Label *on_end_of_input, bool check_bounds, int characters, int eats_at_least) override
void PopCurrentPosition () override
void PopRegister (int register_index) override
void PushBacktrack (Label *label) override
void PushCurrentPosition () override
void PushRegister (int register_index, StackCheckFlag check_stack_limit) override
void ReadCurrentPositionFromRegister (int reg) override
void ReadStackPointerFromRegister (int reg) override
void SetCurrentPositionFromEnd (int by) override
void SetRegister (int register_index, int to) override
bool Succeed () override
void WriteCurrentPositionToRegister (int reg, int cp_offset) override
void ClearRegisters (int reg_from, int reg_to) override
void WriteStackPointerToRegister (int reg) override
Private Attributes
RegExpMacroAssembler * assembler_
Additional Inherited Members
Detailed Description
Definition at line 15 of file regexp-macro-assembler-tracer.h.
Constructor & Destructor Documentation
RegExpMacroAssemblerTracer()
v8::internal::RegExpMacroAssemblerTracer::RegExpMacroAssemblerTracer (Isolate * isolate, RegExpMacroAssembler * assembler)
Definition at line 13 of file regexp-macro-assembler-tracer.cc.
    : RegExpMacroAssembler(isolate, assembler->zone()), assembler_(assembler) {
  PrintF("RegExpMacroAssembler%s();\n",
         ImplementationToString(assembler->Implementation()));
}
References v8::internal::RegExpMacroAssembler::Implementation(), v8::internal::RegExpMacroAssembler::ImplementationToString(), and v8::internal::PrintF().
 RegExpMacroAssemblerTracer()
v8::internal::RegExpMacroAssemblerTracer::~RegExpMacroAssemblerTracer () [override], [default]
Member Function Documentation
AbortedCodeGeneration()
void v8::internal::RegExpMacroAssemblerTracer::AbortedCodeGeneration () [override], [virtual]
Reimplemented from v8::internal::RegExpMacroAssembler.
Definition at line 22 of file regexp-macro-assembler-tracer.cc.
                                                       {
  PrintF(" AbortedCodeGeneration\n");
  assembler_->AbortedCodeGeneration();
}
References v8::internal::RegExpMacroAssembler::AbortedCodeGeneration(), assembler_, and v8::internal::PrintF().
AdvanceCurrentPosition()
void v8::internal::RegExpMacroAssemblerTracer::AdvanceCurrentPosition (int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 41 of file regexp-macro-assembler-tracer.cc.
                                                              {
  PrintF(" AdvanceCurrentPosition(by=%d);\n", by);
  assembler_->AdvanceCurrentPosition(by);
}
References v8::internal::RegExpMacroAssembler::AdvanceCurrentPosition(), assembler_, and v8::internal::PrintF().
AdvanceRegister()
void v8::internal::RegExpMacroAssemblerTracer::AdvanceRegister (int reg, int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 110 of file regexp-macro-assembler-tracer.cc.
                                                                {
  PrintF(" AdvanceRegister(register=%d, by=%d);\n", reg, by);
  assembler_->AdvanceRegister(reg, by);
}
References v8::internal::RegExpMacroAssembler::AdvanceRegister(), assembler_, and v8::internal::PrintF().
Backtrack()
void v8::internal::RegExpMacroAssemblerTracer::Backtrack () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 63 of file regexp-macro-assembler-tracer.cc.
                                           {
  PrintF(" Backtrack();\n");
  assembler_->Backtrack();
}
References assembler_, v8::internal::RegExpMacroAssembler::Backtrack(), and v8::internal::PrintF().
Bind()
void v8::internal::RegExpMacroAssemblerTracer::Bind (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 35 of file regexp-macro-assembler-tracer.cc.
                                                  {
  PrintF("label[%08x]: (Bind)\n", LabelToInt(label));
  assembler_->Bind(label);
}
References assembler_, v8::internal::RegExpMacroAssembler::Bind(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CanReadUnaligned()
bool v8::internal::RegExpMacroAssemblerTracer::CanReadUnaligned () const [inline], [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 23 of file regexp-macro-assembler-tracer.h.
                                         {
    return assembler_->CanReadUnaligned();
  }
References assembler_, and v8::internal::RegExpMacroAssembler::CanReadUnaligned().
CheckAtStart()
void v8::internal::RegExpMacroAssemblerTracer::CheckAtStart (int cp_offset, Label * on_at_start) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 227 of file regexp-macro-assembler-tracer.cc.
                                                                  {
  PrintF(" CheckAtStart(cp_offset=%d, label[%08x]);\n", cp_offset,
         LabelToInt(on_at_start));
  assembler_->CheckAtStart(cp_offset, on_at_start);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckAtStart(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckBitInTable()
void v8::internal::RegExpMacroAssemblerTracer::CheckBitInTable (Handle< ByteArray > table, Label * on_bit_set) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 359 of file regexp-macro-assembler-tracer.cc.
                                                {
  PrintF(" CheckBitInTable(label[%08x] ", LabelToInt(on_bit_set));
  for (int i = 0; i < kTableSize; i++) {
    PrintF("%c", table->get(i) != 0 ? 'X' : '.');
    if (i % 32 == 31 && i != kTableMask) {
      PrintF("\n ");
    }
  }
  PrintF(");\n");
  assembler_->CheckBitInTable(table, on_bit_set);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckBitInTable(), v8::internal::RegExpMacroAssembler::kTableMask, v8::internal::RegExpMacroAssembler::kTableSize, v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacter()
void v8::internal::RegExpMacroAssemblerTracer::CheckCharacter (unsigned c, Label * on_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 218 of file regexp-macro-assembler-tracer.cc.
                                                                           {
  PrintablePrinter printable(c);
  PrintF(" CheckCharacter(c=0x%04x%s, label[%08x]);\n",
         c,
         *printable,
         LabelToInt(on_equal));
  assembler_->CheckCharacter(c, on_equal);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacter(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacterAfterAnd()
void v8::internal::RegExpMacroAssemblerTracer::CheckCharacterAfterAnd (unsigned c, unsigned and_with, Label * on_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 253 of file regexp-macro-assembler-tracer.cc.
                     {
  PrintablePrinter printable(c);
  PrintF(" CheckCharacterAfterAnd(c=0x%04x%s, mask=0x%04x, label[%08x]);\n",
         c,
         *printable,
         mask,
         LabelToInt(on_equal));
  assembler_->CheckCharacterAfterAnd(c, mask, on_equal);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterAfterAnd(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacterGT()
void v8::internal::RegExpMacroAssemblerTracer::CheckCharacterGT (base::uc16 limit, Label * on_greater) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 208 of file regexp-macro-assembler-tracer.cc.
                                                                     {
  PrintablePrinter printable(limit);
  PrintF(" CheckCharacterGT(c=0x%04x%s, label[%08x]);\n",
         limit,
         *printable,
         LabelToInt(on_greater));
  assembler_->CheckCharacterGT(limit, on_greater);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterGT(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacterInRange()
void v8::internal::RegExpMacroAssemblerTracer::CheckCharacterInRange (base::uc16 from, base::uc16 to, Label * on_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 291 of file regexp-macro-assembler-tracer.cc.
                                                                               {
  PrintablePrinter printable_from(from);
  PrintablePrinter printable_to(to);
  PrintF(" CheckCharacterInRange(from=0x%04x%s, to=0x%04x%s, label[%08x]);\n",
         from,
         *printable_from,
         to,
         *printable_to,
         LabelToInt(on_not_in_range));
  assembler_->CheckCharacterInRange(from, to, on_not_in_range);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterInRange(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacterInRangeArray()
bool v8::internal::RegExpMacroAssemblerTracer::CheckCharacterInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 335 of file regexp-macro-assembler-tracer.cc.
                                                                {
  PrintF(
      " CheckCharacterInRangeArray(\n"
      " label[%08x]);\n",
      LabelToInt(on_in_range));
  PrintRangeArray(ranges);
  return assembler_->CheckCharacterInRangeArray(ranges, on_in_range);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterInRangeArray(), v8::internal::LabelToInt(), v8::internal::PrintF(), and v8::internal::anonymous_namespace{regexp-macro-assembler-tracer.cc}::PrintRangeArray().
CheckCharacterLT()
void v8::internal::RegExpMacroAssemblerTracer::CheckCharacterLT (base::uc16 limit, Label * on_less) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 198 of file regexp-macro-assembler-tracer.cc.
                                                                  {
  PrintablePrinter printable(limit);
  PrintF(" CheckCharacterLT(c=0x%04x%s, label[%08x]);\n",
         limit,
         *printable,
         LabelToInt(on_less));
  assembler_->CheckCharacterLT(limit, on_less);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterLT(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacterNotInRange()
void v8::internal::RegExpMacroAssemblerTracer::CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label * on_not_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 305 of file regexp-macro-assembler-tracer.cc.
                                                                              {
  PrintablePrinter printable_from(from);
  PrintablePrinter printable_to(to);
  PrintF(
      " CheckCharacterNotInRange(from=0x%04x%s," " to=%04x%s, label[%08x]);\n",
      from,
      *printable_from,
      to,
      *printable_to,
      LabelToInt(on_in_range));
  assembler_->CheckCharacterNotInRange(from, to, on_in_range);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterNotInRange(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckCharacterNotInRangeArray()
bool v8::internal::RegExpMacroAssemblerTracer::CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_not_in_range) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 345 of file regexp-macro-assembler-tracer.cc.
                                                                    {
  bool emitted =
      assembler_->CheckCharacterNotInRangeArray(ranges, on_not_in_range);
  if (emitted) {
    PrintF(
        " CheckCharacterNotInRangeArray(\n"
        " label[%08x]);\n",
        LabelToInt(on_not_in_range));
    PrintRangeArray(ranges);
  }
  return emitted;
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckCharacterNotInRangeArray(), v8::internal::LabelToInt(), v8::internal::PrintF(), and v8::internal::anonymous_namespace{regexp-macro-assembler-tracer.cc}::PrintRangeArray().
CheckFixedLengthLoop()
void v8::internal::RegExpMacroAssemblerTracer::CheckFixedLengthLoop (Label * on_tos_equals_current_position) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 46 of file regexp-macro-assembler-tracer.cc.
                                                                  {
  PrintF(" CheckFixedLengthLoop(label[%08x]);\n\n", LabelToInt(label));
  assembler_->CheckFixedLengthLoop(label);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckFixedLengthLoop(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckNotAtStart()
void v8::internal::RegExpMacroAssemblerTracer::CheckNotAtStart (int cp_offset, Label * on_not_at_start) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 234 of file regexp-macro-assembler-tracer.cc.
                                                                         {
  PrintF(" CheckNotAtStart(cp_offset=%d, label[%08x]);\n", cp_offset,
         LabelToInt(on_not_at_start));
  assembler_->CheckNotAtStart(cp_offset, on_not_at_start);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckNotAtStart(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckNotBackReference()
void v8::internal::RegExpMacroAssemblerTracer::CheckNotBackReference (int start_reg, bool read_backward, Label * on_no_match) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 406 of file regexp-macro-assembler-tracer.cc.
                                                                           {
  PrintF(" CheckNotBackReference(register=%d, %s, label[%08x]);\n", start_reg,
         read_backward ? "backward" : "forward", LabelToInt(on_no_match));
  assembler_->CheckNotBackReference(start_reg, read_backward, on_no_match);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckNotBackReference(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckNotBackReferenceIgnoreCase()
void v8::internal::RegExpMacroAssemblerTracer::CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label * on_no_match) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 414 of file regexp-macro-assembler-tracer.cc.
                                                                         {
  PrintF(" CheckNotBackReferenceIgnoreCase(register=%d, %s %s, label[%08x]);\n",
         start_reg, read_backward ? "backward" : "forward",
         unicode ? "unicode" : "non-unicode", LabelToInt(on_no_match));
  assembler_->CheckNotBackReferenceIgnoreCase(start_reg, read_backward, unicode,
                                              on_no_match);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckNotBackReferenceIgnoreCase(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckNotCharacter()
void v8::internal::RegExpMacroAssemblerTracer::CheckNotCharacter (unsigned c, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 242 of file regexp-macro-assembler-tracer.cc.
                                                                        {
  PrintablePrinter printable(c);
  PrintF(" CheckNotCharacter(c=0x%04x%s, label[%08x]);\n",
         c,
         *printable,
         LabelToInt(on_not_equal));
  assembler_->CheckNotCharacter(c, on_not_equal);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckNotCharacter(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckNotCharacterAfterAnd()
void v8::internal::RegExpMacroAssemblerTracer::CheckNotCharacterAfterAnd (unsigned c, unsigned and_with, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 267 of file regexp-macro-assembler-tracer.cc.
                         {
  PrintablePrinter printable(c);
  PrintF(" CheckNotCharacterAfterAnd(c=0x%04x%s, mask=0x%04x, label[%08x]);\n",
         c,
         *printable,
         mask,
         LabelToInt(on_not_equal));
  assembler_->CheckNotCharacterAfterAnd(c, mask, on_not_equal);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterAnd(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckNotCharacterAfterMinusAnd()
void v8::internal::RegExpMacroAssemblerTracer::CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 and_with, Label * on_not_equal) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 280 of file regexp-macro-assembler-tracer.cc.
                                                                    {
  PrintF(" CheckNotCharacterAfterMinusAnd(c=0x%04x, minus=%04x, mask=0x%04x, "
             "label[%08x]);\n",
         c,
         minus,
         mask,
         LabelToInt(on_not_equal));
  assembler_->CheckNotCharacterAfterMinusAnd(c, minus, mask, on_not_equal);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterMinusAnd(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckPosition()
void v8::internal::RegExpMacroAssemblerTracer::CheckPosition (int cp_offset, Label * on_outside_input) [override], [virtual]
Reimplemented from v8::internal::RegExpMacroAssembler.
Definition at line 423 of file regexp-macro-assembler-tracer.cc.
                                                                        {
  PrintF(" CheckPosition(cp_offset=%d, label[%08x]);\n", cp_offset,
         LabelToInt(on_outside_input));
  assembler_->CheckPosition(cp_offset, on_outside_input);
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckPosition(), v8::internal::LabelToInt(), and v8::internal::PrintF().
CheckSpecialClassRanges()
bool v8::internal::RegExpMacroAssemblerTracer::CheckSpecialClassRanges (StandardCharacterSet type, Label * on_no_match) [override], [virtual]
Reimplemented from v8::internal::RegExpMacroAssembler.
Definition at line 430 of file regexp-macro-assembler-tracer.cc.
                                                   {
  bool supported = assembler_->CheckSpecialClassRanges(type, on_no_match);
  PrintF(" CheckSpecialClassRanges(type='%c', label[%08x]): %s;\n",
         static_cast<char>(type), LabelToInt(on_no_match),
         supported ? "true" : "false");
  return supported;
}
References assembler_, v8::internal::RegExpMacroAssembler::CheckSpecialClassRanges(), v8::internal::LabelToInt(), v8::internal::PrintF(), and v8::internal::tracing::type.
ClearRegisters()
void v8::internal::RegExpMacroAssemblerTracer::ClearRegisters (int reg_from, int reg_to) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 137 of file regexp-macro-assembler-tracer.cc.
                                                                        {
  PrintF(" ClearRegister(from=%d, to=%d);\n", reg_from, reg_to);
  assembler_->ClearRegisters(reg_from, reg_to);
}
References assembler_, v8::internal::RegExpMacroAssembler::ClearRegisters(), and v8::internal::PrintF().
Fail()
void v8::internal::RegExpMacroAssemblerTracer::Fail () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 88 of file regexp-macro-assembler-tracer.cc.
                                      {
  PrintF(" Fail();");
  assembler_->Fail();
}
References assembler_, v8::internal::RegExpMacroAssembler::Fail(), and v8::internal::PrintF().
GetCode()
DirectHandle< HeapObject > v8::internal::RegExpMacroAssemblerTracer::GetCode (DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 468 of file regexp-macro-assembler-tracer.cc.
                                                    {
  DirectHandle<String> flags_str =
      JSRegExp::StringFromFlags(isolate(), JSRegExp::AsJSRegExpFlags(flags));
  PrintF(" GetCode('%s', '%s');\n", source->ToCString().get(),
         flags_str->ToCString().get());
  return assembler_->GetCode(source, flags);
}
References v8::internal::JSRegExp::AsJSRegExpFlags(), assembler_, v8::internal::flags, v8::internal::RegExpMacroAssembler::GetCode(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::PrintF(), and v8::internal::JSRegExp::StringFromFlags().
GoTo()
void v8::internal::RegExpMacroAssemblerTracer::GoTo (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 69 of file regexp-macro-assembler-tracer.cc.
                                                  {
  PrintF(" GoTo(label[%08x]);\n\n", LabelToInt(label));
  assembler_->GoTo(label);
}
References assembler_, v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::LabelToInt(), and v8::internal::PrintF().
IfRegisterEqPos()
void v8::internal::RegExpMacroAssemblerTracer::IfRegisterEqPos (int reg, Label * if_eq) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 447 of file regexp-macro-assembler-tracer.cc.
                                                               {
  PrintF(" IfRegisterEqPos(register=%d, label[%08x]);\n",
         register_index, LabelToInt(if_eq));
  assembler_->IfRegisterEqPos(register_index, if_eq);
}
References assembler_, v8::internal::RegExpMacroAssembler::IfRegisterEqPos(), v8::internal::LabelToInt(), and v8::internal::PrintF().
IfRegisterGE()
void v8::internal::RegExpMacroAssemblerTracer::IfRegisterGE (int reg, int comparand, Label * if_ge) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 455 of file regexp-macro-assembler-tracer.cc.
                                                                           {
  PrintF(" IfRegisterGE(register=%d, number=%d, label[%08x]);\n",
         register_index, comparand, LabelToInt(if_ge));
  assembler_->IfRegisterGE(register_index, comparand, if_ge);
}
References assembler_, v8::internal::RegExpMacroAssembler::IfRegisterGE(), v8::internal::LabelToInt(), and v8::internal::PrintF().
IfRegisterLT()
void v8::internal::RegExpMacroAssemblerTracer::IfRegisterLT (int reg, int comparand, Label * if_lt) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 439 of file regexp-macro-assembler-tracer.cc.
                                                                           {
  PrintF(" IfRegisterLT(register=%d, number=%d, label[%08x]);\n",
         register_index, comparand, LabelToInt(if_lt));
  assembler_->IfRegisterLT(register_index, comparand, if_lt);
}
References assembler_, v8::internal::RegExpMacroAssembler::IfRegisterLT(), v8::internal::LabelToInt(), and v8::internal::PrintF().
Implementation()
RegExpMacroAssembler::IrregexpImplementation v8::internal::RegExpMacroAssemblerTracer::Implementation () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 464 of file regexp-macro-assembler-tracer.cc.
                                               {
  return assembler_->Implementation();
}
References assembler_, and v8::internal::RegExpMacroAssembler::Implementation().
LoadCurrentCharacterImpl()
void v8::internal::RegExpMacroAssemblerTracer::LoadCurrentCharacterImpl (int cp_offset, Label * on_end_of_input, bool check_bounds, int characters, int eats_at_least) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 160 of file regexp-macro-assembler-tracer.cc.
                       {
  const char* check_msg = check_bounds ? "" : " (unchecked)";
  PrintF(
      " LoadCurrentCharacter(cp_offset=%d, label[%08x]%s (%d chars) (eats at "
      "least %d));\n",
      cp_offset, LabelToInt(on_end_of_input), check_msg, characters,
      eats_at_least);
  assembler_->LoadCurrentCharacter(cp_offset, on_end_of_input, check_bounds,
                                   characters, eats_at_least);
}
References assembler_, v8::internal::LabelToInt(), v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), and v8::internal::PrintF().
PopCurrentPosition()
void v8::internal::RegExpMacroAssemblerTracer::PopCurrentPosition () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 51 of file regexp-macro-assembler-tracer.cc.
                                                    {
  PrintF(" PopCurrentPosition();\n");
  assembler_->PopCurrentPosition();
}
References assembler_, v8::internal::RegExpMacroAssembler::PopCurrentPosition(), and v8::internal::PrintF().
PopRegister()
void v8::internal::RegExpMacroAssemblerTracer::PopRegister (int register_index) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 94 of file regexp-macro-assembler-tracer.cc.
                                                               {
  PrintF(" PopRegister(register=%d);\n", register_index);
  assembler_->PopRegister(register_index);
}
References assembler_, v8::internal::RegExpMacroAssembler::PopRegister(), and v8::internal::PrintF().
PushBacktrack()
void v8::internal::RegExpMacroAssemblerTracer::PushBacktrack (Label * label) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 75 of file regexp-macro-assembler-tracer.cc.
                                                           {
  PrintF(" PushBacktrack(label[%08x]);\n", LabelToInt(label));
  assembler_->PushBacktrack(label);
}
References assembler_, v8::internal::LabelToInt(), v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::PushBacktrack().
PushCurrentPosition()
void v8::internal::RegExpMacroAssemblerTracer::PushCurrentPosition () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 57 of file regexp-macro-assembler-tracer.cc.
                                                     {
  PrintF(" PushCurrentPosition();\n");
  assembler_->PushCurrentPosition();
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::PushCurrentPosition().
PushRegister()
void v8::internal::RegExpMacroAssemblerTracer::PushRegister (int register_index, StackCheckFlag check_stack_limit) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 100 of file regexp-macro-assembler-tracer.cc.
                                      {
  PrintF(" PushRegister(register=%d, %s);\n",
         register_index,
         check_stack_limit ? "check stack limit" : "");
  assembler_->PushRegister(register_index, check_stack_limit);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::PushRegister().
ReadCurrentPositionFromRegister()
void v8::internal::RegExpMacroAssemblerTracer::ReadCurrentPositionFromRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 143 of file regexp-macro-assembler-tracer.cc.
                                                                        {
  PrintF(" ReadCurrentPositionFromRegister(register=%d);\n", reg);
  assembler_->ReadCurrentPositionFromRegister(reg);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::ReadCurrentPositionFromRegister().
ReadStackPointerFromRegister()
void v8::internal::RegExpMacroAssemblerTracer::ReadStackPointerFromRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 155 of file regexp-macro-assembler-tracer.cc.
                                                                     {
  PrintF(" ReadStackPointerFromRegister(register=%d);\n", reg);
  assembler_->ReadStackPointerFromRegister(reg);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::ReadStackPointerFromRegister().
SetCurrentPositionFromEnd()
void v8::internal::RegExpMacroAssemblerTracer::SetCurrentPositionFromEnd (int by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 116 of file regexp-macro-assembler-tracer.cc.
                                                                 {
  PrintF(" SetCurrentPositionFromEnd(by=%d);\n", by);
  assembler_->SetCurrentPositionFromEnd(by);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::SetCurrentPositionFromEnd().
SetRegister()
void v8::internal::RegExpMacroAssemblerTracer::SetRegister (int register_index, int to) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 122 of file regexp-macro-assembler-tracer.cc.
                                                                       {
  PrintF(" SetRegister(register=%d, to=%d);\n", register_index, to);
  assembler_->SetRegister(register_index, to);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::SetRegister().
SkipUntilBitInTable()
void v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 372 of file regexp-macro-assembler-tracer.cc.
                    {
  PrintF("SkipUntilBitInTable(cp_offset=%d, advance_by=%d\n ", cp_offset,
         advance_by);
  for (int i = 0; i < kTableSize; i++) {
    PrintF("%c", table->get(i) != 0 ? 'X' : '.');
    if (i % 32 == 31 && i != kTableMask) {
      PrintF("\n ");
    }
  }
  static_assert(kTableSize == 128);
  static constexpr int kRows = 16;
  static_assert(kRows * kBitsPerByte == kTableSize);
  if (!nibble_table.is_null()) {
    PrintF("\n");
    PrintF(" +----------------\n");
    PrintF(" |");
    for (int j = 0; j < kBitsPerByte; j++) {
      PrintF(" %x", j);
    }
    PrintF("\n--+----------------");
    for (int i = 0; i < kRows; i++) {
      int r = nibble_table->get(i);
      PrintF("\n%x |", i);
      for (int j = 0; j < kBitsPerByte; j++) {
        PrintF(" %c", (r & (1 << j)) == 0 ? '.' : 'X');
      }
    }
  }
  PrintF(");\n");
  assembler_->SkipUntilBitInTable(cp_offset, table, nibble_table, advance_by);
}
References assembler_, v8::internal::HandleBase::is_null(), v8::internal::kBitsPerByte, v8::internal::RegExpMacroAssembler::kTableMask, v8::internal::RegExpMacroAssembler::kTableSize, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::SkipUntilBitInTable().
SkipUntilBitInTableUseSimd()
bool v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTableUseSimd (int advance_by) [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpMacroAssembler.
Definition at line 58 of file regexp-macro-assembler-tracer.h.
                                                           {
    return assembler_->SkipUntilBitInTableUseSimd(advance_by);
  }
References assembler_, and v8::internal::RegExpMacroAssembler::SkipUntilBitInTableUseSimd().
stack_limit_slack_slot_count()
int v8::internal::RegExpMacroAssemblerTracer::stack_limit_slack_slot_count () [inline], [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 20 of file regexp-macro-assembler-tracer.h.
                                              {
    return assembler_->stack_limit_slack_slot_count();
  }
References assembler_, and v8::internal::RegExpMacroAssembler::stack_limit_slack_slot_count().
Succeed()
bool v8::internal::RegExpMacroAssemblerTracer::Succeed () [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 81 of file regexp-macro-assembler-tracer.cc.
                                         {
  bool restart = assembler_->Succeed();
  PrintF(" Succeed();%s\n", restart ? " [restart for global match]" : "");
  return restart;
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::Succeed().
WriteCurrentPositionToRegister()
void v8::internal::RegExpMacroAssemblerTracer::WriteCurrentPositionToRegister (int reg, int cp_offset) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 128 of file regexp-macro-assembler-tracer.cc.
                                                                               {
  PrintF(" WriteCurrentPositionToRegister(register=%d,cp_offset=%d);\n",
         reg,
         cp_offset);
  assembler_->WriteCurrentPositionToRegister(reg, cp_offset);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::WriteCurrentPositionToRegister().
WriteStackPointerToRegister()
void v8::internal::RegExpMacroAssemblerTracer::WriteStackPointerToRegister (int reg) [override], [virtual]
Implements v8::internal::RegExpMacroAssembler.
Definition at line 149 of file regexp-macro-assembler-tracer.cc.
                                                                    {
  PrintF(" WriteStackPointerToRegister(register=%d);\n", reg);
  assembler_->WriteStackPointerToRegister(reg);
}
References assembler_, v8::internal::PrintF(), and v8::internal::RegExpMacroAssembler::WriteStackPointerToRegister().
Member Data Documentation
assembler_
RegExpMacroAssembler* v8::internal::RegExpMacroAssemblerTracer::assembler_ [private]
Definition at line 94 of file regexp-macro-assembler-tracer.h.
Referenced by AbortedCodeGeneration(), AdvanceCurrentPosition(), AdvanceRegister(), Backtrack(), Bind(), CanReadUnaligned(), CheckAtStart(), CheckBitInTable(), CheckCharacter(), CheckCharacterAfterAnd(), CheckCharacterGT(), CheckCharacterInRange(), CheckCharacterInRangeArray(), CheckCharacterLT(), CheckCharacterNotInRange(), CheckCharacterNotInRangeArray(), CheckFixedLengthLoop(), CheckNotAtStart(), CheckNotBackReference(), CheckNotBackReferenceIgnoreCase(), CheckNotCharacter(), CheckNotCharacterAfterAnd(), CheckNotCharacterAfterMinusAnd(), CheckPosition(), CheckSpecialClassRanges(), ClearRegisters(), Fail(), GetCode(), GoTo(), IfRegisterEqPos(), IfRegisterGE(), IfRegisterLT(), Implementation(), LoadCurrentCharacterImpl(), PopCurrentPosition(), PopRegister(), PushBacktrack(), PushCurrentPosition(), PushRegister(), ReadCurrentPositionFromRegister(), ReadStackPointerFromRegister(), SetCurrentPositionFromEnd(), SetRegister(), SkipUntilBitInTable(), SkipUntilBitInTableUseSimd(), stack_limit_slack_slot_count(), Succeed(), WriteCurrentPositionToRegister(), and WriteStackPointerToRegister().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-macro-assembler-tracer.h
/mnt/V8SourceCode/src/regexp/regexp-macro-assembler-tracer.cc