cppgc::internal::ObjectView< AccessMode > Class Template Reference
#include <object-view.h>
Public Member Functions
ObjectView (const HeapObjectHeader &header)
Address Start () const
ConstAddress End () const
size_t Size () const
Private Attributes
const HeapObjectHeader & header_
const BasePage * base_page_
const bool is_large_object_
Detailed Description
template<AccessMode = AccessMode::kNonAtomic>
class cppgc::internal::ObjectView< AccessMode >
Definition at line 19 of file object-view.h.
Constructor & Destructor Documentation
ObjectView()
template<AccessMode access_mode>
cppgc::internal::ObjectView< access_mode >::ObjectView (const HeapObjectHeader & header) [inline], [explicit]
Definition at line 34 of file object-view.h.
    : header_(header),
      base_page_(
          BasePage::FromPayload(const_cast<HeapObjectHeader*>(&header_))),
      is_large_object_(header_.IsLargeObject<access_mode>()) {
  DCHECK_EQ(Start() + Size(), End());
}
References DCHECK_EQ, cppgc::internal::ObjectView< AccessMode >::End(), cppgc::internal::ObjectView< AccessMode >::Size(), and cppgc::internal::ObjectView< AccessMode >::Start().
Member Function Documentation
End()
template<AccessMode access_mode>
ConstAddress cppgc::internal::ObjectView< access_mode >::End [inline]
Definition at line 48 of file object-view.h.
                                                {
  return is_large_object_ ? LargePage::From(base_page_)->PayloadEnd()
                          : header_.ObjectEnd<access_mode>();
}
References cppgc::internal::LargePage::From(), and cppgc::internal::LargePage::PayloadEnd().
Referenced by cppgc::internal::ObjectView< AccessMode >::ObjectView().
Size()
template<AccessMode access_mode>
size_t cppgc::internal::ObjectView< access_mode >::Size [inline]
Definition at line 54 of file object-view.h.
                                           {
  return is_large_object_ ? LargePage::From(base_page_)->ObjectSize()
                          : header_.ObjectSize<access_mode>();
}
References cppgc::internal::LargePage::From(), and cppgc::internal::LargePage::ObjectSize().
Referenced by cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::BaseObjectSizeTrait::GetObjectSizeForGarbageCollected(), cppgc::internal::anonymous_namespace{heap-base.cc}::ObjectSizeCounter::ObjectSize(), cppgc::internal::ObjectView< AccessMode >::ObjectView(), cppgc::internal::MarkingVerifierBase::ReportDifferences(), and cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader().
Start()
template<AccessMode access_mode>
Address cppgc::internal::ObjectView< access_mode >::Start [inline]
Definition at line 43 of file object-view.h.
                                             {
  return header_.ObjectStart();
}
Referenced by cppgc::internal::ObjectView< AccessMode >::ObjectView().
Member Data Documentation
base_page_
template<AccessMode = AccessMode::kNonAtomic>
const BasePage* cppgc::internal::ObjectView< AccessMode >::base_page_ [private]
Definition at line 29 of file object-view.h.
header_
template<AccessMode = AccessMode::kNonAtomic>
const HeapObjectHeader& cppgc::internal::ObjectView< AccessMode >::header_ [private]
Definition at line 28 of file object-view.h.
is_large_object_
template<AccessMode = AccessMode::kNonAtomic>
const bool cppgc::internal::ObjectView< AccessMode >::is_large_object_ [private]
Definition at line 30 of file object-view.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/object-view.h