v8::internal::FixedIntegerArrayBase< T, Base > Class Template Reference
#include <fixed-array.h>
Public Member Functions
T get (int index) const
void set (int index, T value)
int length () const
Static Public Member Functions
template<typename... MoreArgs>
static Handle< FixedIntegerArrayBase< T, Base > > New (Isolate *isolate, int length, MoreArgs &&... more_args)
static constexpr int OffsetOfElementAt (int index)
Protected Member Functions
Address get_element_address (int index) const
Detailed Description
template<typename T, typename Base>
class v8::internal::FixedIntegerArrayBase< T, Base >
Definition at line 838 of file fixed-array.h.
Member Function Documentation
get()
template<typename T , typename Base >
T v8::internal::FixedIntegerArrayBase< T, Base >::get (int index) const
Definition at line 845 of file fixed-array-inl.h.
                                                     {
  static_assert(std::is_integral_v<T>);
  return base::ReadUnalignedValue<T>(get_element_address(index));
}
References v8::internal::index.
get_element_address()
template<typename T , typename Base >
Address v8::internal::FixedIntegerArrayBase< T, Base >::get_element_address (int index) const [protected]
Definition at line 838 of file fixed-array-inl.h.
                                                                           {
  DCHECK_GE(index, 0);
  DCHECK_LT(index, length());
  return reinterpret_cast<Address>(&this->values()[index * sizeof(T)]);
}
References DCHECK_GE, DCHECK_LT, v8::internal::index, v8::internal::length, and T.
length()
template<typename T , typename Base >
int v8::internal::FixedIntegerArrayBase< T, Base >::length [inline]
Definition at line 857 of file fixed-array-inl.h.
                                                 {
  DCHECK_EQ(Base::length() % sizeof(T), 0);
  return Base::length() / sizeof(T);
}
References DCHECK_EQ, v8::internal::length, and T.
New()
template<typename T , typename Base >
template<typename... MoreArgs>
Handle< FixedIntegerArrayBase< T, Base > > v8::internal::FixedIntegerArrayBase< T, Base >::New (Isolate * isolate, int length, MoreArgs &&... more_args) [static]
Definition at line 829 of file fixed-array-inl.h.
                                                           {
  int byte_length;
  CHECK(!base::bits::SignedMulOverflow32(length, sizeof(T), &byte_length));
  return Cast<FixedIntegerArrayBase<T, Base>>(
      Base::New(isolate, byte_length, std::forward<MoreArgs>(more_args)...));
}
References CHECK, v8::internal::length, v8::internal::anonymous_namespace{intl-objects.cc}::New(), and v8::base::bits::SignedMulOverflow32().
Referenced by v8::internal::BasicBlockProfilerData::CopyToJSHeap(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray(), and v8::internal::WasmTrustedInstanceData::New().
OffsetOfElementAt()
template<typename T , typename Base >
static constexpr int v8::internal::FixedIntegerArrayBase< T, Base >::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 853 of file fixed-array.h.
                                                    {
    return sizeof(typename Base::Header) + index * sizeof(T);
  }
References v8::internal::ETWJITInterface::Header(), and v8::internal::FixedArray::index.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::DataDrop(), v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedUInt32Array(), and v8::internal::wasm::ObjectAccess::ElementOffsetInTaggedFixedUInt8Array().
set()
template<typename T , typename Base >
void v8::internal::FixedIntegerArrayBase< T, Base >::set (int index, T value)
Definition at line 851 of file fixed-array-inl.h.
                                                           {
  static_assert(std::is_integral_v<T>);
  return base::WriteUnalignedValue<T>(get_element_address(index), value);
}
References v8::internal::index, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/factory-base.h
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h