v8::internal::ObjectLiteralBoilerplateBuilder Class Reference
#include <ast.h>
Public Types
using Property = ObjectLiteralProperty
Public Member Functions
ObjectLiteralBoilerplateBuilder (ZoneList< Property * > *properties, uint32_t boilerplate_properties, bool has_rest_property)
DirectHandle< ObjectBoilerplateDescription > boilerplate_description () const
bool IsFastCloningSupported () const
int properties_count () const
const ZonePtrList< Property > * properties () const
bool has_elements () const
bool has_rest_property () const
bool fast_elements () const
bool has_null_prototype () const
template<typename IsolateT >
void BuildBoilerplateDescription (IsolateT *isolate)
template<typename IsolateT >
Handle< ObjectBoilerplateDescription > GetOrBuildBoilerplateDescription (IsolateT *isolate)
bool is_empty () const
int ComputeFlags (bool disable_mementos=false) const
bool IsEmptyObjectLiteral () const
int EncodeLiteralType ()
void InitDepthAndFlags ()
Private Types
using HasElementsField = LiteralBoilerplateBuilder::NextBitField< bool, 1 >
using HasRestPropertyField = HasElementsField::Next< bool, 1 >
using FastElementsField = HasRestPropertyField::Next< bool, 1 >
using HasNullPrototypeField = FastElementsField::Next< bool, 1 >
Private Member Functions
void InitFlagsForPendingNullPrototype (int i)
void set_has_elements (bool has_elements)
void set_fast_elements (bool fast_elements)
void set_has_null_protoype (bool has_null_prototype)
Private Attributes
ZoneList< Property * > * properties_
uint32_t boilerplate_properties_
IndirectHandle< ObjectBoilerplateDescription > boilerplate_description_
Additional Inherited Members
Detailed Description
Definition at line 1292 of file ast.h.
Member Typedef Documentation
FastElementsField
using v8::internal::ObjectLiteralBoilerplateBuilder::FastElementsField = HasRestPropertyField::Next<bool, 1> [private]
Definition at line 1373 of file ast.h.
HasElementsField
using v8::internal::ObjectLiteralBoilerplateBuilder::HasElementsField = LiteralBoilerplateBuilder::NextBitField<bool, 1> [private]
Definition at line 1371 of file ast.h.
HasNullPrototypeField
using v8::internal::ObjectLiteralBoilerplateBuilder::HasNullPrototypeField = FastElementsField::Next<bool, 1> [private]
Definition at line 1374 of file ast.h.
HasRestPropertyField
using v8::internal::ObjectLiteralBoilerplateBuilder::HasRestPropertyField = HasElementsField::Next<bool, 1> [private]
Definition at line 1372 of file ast.h.
Property
using v8::internal::ObjectLiteralBoilerplateBuilder::Property = ObjectLiteralProperty
Definition at line 1294 of file ast.h.
Constructor & Destructor Documentation
ObjectLiteralBoilerplateBuilder()
v8::internal::ObjectLiteralBoilerplateBuilder::ObjectLiteralBoilerplateBuilder (ZoneList< Property * > * properties, uint32_t boilerplate_properties, bool has_rest_property) [inline]
Definition at line 1296 of file ast.h.
      : properties_(properties),
        boilerplate_properties_(boilerplate_properties) {
    bit_field_ |= HasElementsField::encode(false) |
                  HasRestPropertyField::encode(has_rest_property) |
                  FastElementsField::encode(false) |
                  HasNullPrototypeField::encode(false);
  }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), and has_rest_property().
Member Function Documentation
boilerplate_description()
DirectHandle<ObjectBoilerplateDescription> v8::internal::ObjectLiteralBoilerplateBuilder::boilerplate_description () const [inline]
Definition at line 1306 of file ast.h.
                                                                             {
    DCHECK(!boilerplate_description_.is_null());
    return boilerplate_description_;
  }
References boilerplate_description_, and v8::internal::DCHECK().
Referenced by BuildBoilerplateDescription(), and v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue().
BuildBoilerplateDescription()
template<typename IsolateT >
void v8::internal::ObjectLiteralBoilerplateBuilder::BuildBoilerplateDescription (IsolateT * isolate)
Definition at line 479 of file ast.cc.
                       {
  if (!boilerplate_description_.is_null()) return;
  int index_keys = 0;
  bool has_seen_proto = false;
  for (int i = 0; i < properties()->length(); i++) {
    ObjectLiteral::Property* property = properties()->at(i);
    if (property->IsPrototype()) {
      has_seen_proto = true;
      continue;
    }
    if (property->is_computed_name()) continue;
    Literal* key = property->key()->AsLiteral();
    if (!key->IsPropertyName()) index_keys++;
  }
  Handle<ObjectBoilerplateDescription> boilerplate_description =
      isolate->factory()->NewObjectBoilerplateDescription(
          boilerplate_properties_, properties()->length(), index_keys,
          has_seen_proto);
  int position = 0;
  for (int i = 0; i < properties()->length(); i++) {
    ObjectLiteral::Property* property = properties()->at(i);
    if (property->IsPrototype()) continue;
    if (static_cast<uint32_t>(position) == boilerplate_properties_) {
      DCHECK(property->is_computed_name());
      break;
    }
    DCHECK(!property->is_computed_name());
    MaterializedLiteral* m_literal = property->value()->AsMaterializedLiteral();
    if (m_literal != nullptr) {
      BuildConstants(isolate, m_literal);
    }
    // Add CONSTANT and COMPUTED properties to boilerplate. Use the
    // 'uninitialized' Oddball for COMPUTED properties, the real value is filled
    // in at runtime. The enumeration order is maintained.
    Literal* key_literal = property->key()->AsLiteral();
    uint32_t element_index = 0;
    DirectHandle<Object> key =
        key_literal->AsArrayIndex(&element_index)
            ? isolate->factory()
                  ->template NewNumberFromUint<AllocationType::kOld>(
                      element_index)
            : Cast<Object>(key_literal->AsRawPropertyName()->string());
    DirectHandle<Object> value =
        GetBoilerplateValue(property->value(), isolate);
    boilerplate_description->set_key_value(position++, *key, *value);
  }
  boilerplate_description->set_flags(EncodeLiteralType());
  boilerplate_description_ = boilerplate_description;
}
References v8::internal::Literal::AsArrayIndex(), v8::internal::AstNode::AsMaterializedLiteral(), v8::internal::Literal::AsRawPropertyName(), boilerplate_description(), boilerplate_description_, boilerplate_properties_, v8::internal::LiteralBoilerplateBuilder::BuildConstants(), v8::internal::DCHECK(), EncodeLiteralType(), v8::internal::LiteralBoilerplateBuilder::GetBoilerplateValue(), v8::internal::key, v8::internal::length, properties(), v8::internal::AstRawString::string(), and v8::internal::value.
Referenced by GetOrBuildBoilerplateDescription().
ComputeFlags()
int v8::internal::ObjectLiteralBoilerplateBuilder::ComputeFlags (bool disable_mementos = false) const
Definition at line 387 of file ast.cc.
                                                                             {
  int flags = LiteralBoilerplateBuilder::ComputeFlags(disable_mementos);
  if (fast_elements()) flags |= ObjectLiteral::kFastElements;
  if (has_null_prototype()) flags |= ObjectLiteral::kHasNullPrototype;
  return flags;
}
References v8::internal::LiteralBoilerplateBuilder::ComputeFlags(), fast_elements(), v8::internal::flags, has_null_prototype(), v8::internal::ObjectLiteral::kFastElements, and v8::internal::ObjectLiteral::kHasNullPrototype.
EncodeLiteralType()
int v8::internal::ObjectLiteralBoilerplateBuilder::EncodeLiteralType ()
Definition at line 404 of file ast.cc.
                                                       {
  int flags = AggregateLiteral::kNoFlags;
  if (fast_elements()) flags |= ObjectLiteral::kFastElements;
  if (has_null_prototype()) flags |= ObjectLiteral::kHasNullPrototype;
  return flags;
}
References fast_elements(), v8::internal::flags, has_null_prototype(), v8::internal::ObjectLiteral::kFastElements, v8::internal::ObjectLiteral::kHasNullPrototype, and v8::internal::AggregateLiteral::kNoFlags.
Referenced by BuildBoilerplateDescription().
fast_elements()
bool v8::internal::ObjectLiteralBoilerplateBuilder::fast_elements () const [inline]
Definition at line 1319 of file ast.h.
{ return FastElementsField::decode(bit_field_); }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by ComputeFlags(), EncodeLiteralType(), and set_fast_elements().
GetOrBuildBoilerplateDescription()
template<typename IsolateT >
Handle<ObjectBoilerplateDescription> v8::internal::ObjectLiteralBoilerplateBuilder::GetOrBuildBoilerplateDescription (IsolateT * isolate) [inline]
Definition at line 1330 of file ast.h.
                         {
    if (boilerplate_description_.is_null()) {
      BuildBoilerplateDescription(isolate);
    }
    return boilerplate_description_;
  }
References boilerplate_description_, and BuildBoilerplateDescription().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
has_elements()
bool v8::internal::ObjectLiteralBoilerplateBuilder::has_elements () const [inline]
Definition at line 1315 of file ast.h.
{ return HasElementsField::decode(bit_field_); }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by is_empty(), and set_has_elements().
has_null_prototype()
bool v8::internal::ObjectLiteralBoilerplateBuilder::has_null_prototype () const [inline]
Definition at line 1320 of file ast.h.
                                  {
    return HasNullPrototypeField::decode(bit_field_);
  }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by ComputeFlags(), EncodeLiteralType(), InitDepthAndFlags(), IsEmptyObjectLiteral(), and set_has_null_protoype().
has_rest_property()
bool v8::internal::ObjectLiteralBoilerplateBuilder::has_rest_property () const [inline]
Definition at line 1316 of file ast.h.
                                 {
    return HasRestPropertyField::decode(bit_field_);
  }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringObjectAssignment(), and ObjectLiteralBoilerplateBuilder().
InitDepthAndFlags()
void v8::internal::ObjectLiteralBoilerplateBuilder::InitDepthAndFlags ()
Definition at line 411 of file ast.cc.
                                                        {
  if (is_initialized()) return;
  bool is_simple = true;
  bool has_seen_prototype = false;
  bool needs_initial_allocation_site = false;
  DepthKind depth_acc = kShallow;
  uint32_t nof_properties = 0;
  uint32_t elements = 0;
  uint32_t max_element_index = 0;
  for (int i = 0; i < properties()->length(); i++) {
    ObjectLiteral::Property* property = properties()->at(i);
    if (property->IsPrototype()) {
      has_seen_prototype = true;
      // __proto__:null has no side-effects and is set directly on the
      // boilerplate.
      if (property->IsNullPrototype()) {
        set_has_null_protoype(true);
        continue;
      }
      DCHECK(!has_null_prototype());
      is_simple = false;
      continue;
    }
    if (nof_properties == boilerplate_properties_) {
      DCHECK(property->is_computed_name());
      is_simple = false;
      if (!has_seen_prototype) InitFlagsForPendingNullPrototype(i);
      break;
    }
    DCHECK(!property->is_computed_name());
    MaterializedLiteral* literal = property->value()->AsMaterializedLiteral();
    if (literal != nullptr) {
      LiteralBoilerplateBuilder::InitDepthAndFlags(literal);
      depth_acc = kNotShallow;
      needs_initial_allocation_site |= literal->NeedsInitialAllocationSite();
    }
    Literal* key = property->key()->AsLiteral();
    Expression* value = property->value();
    bool is_compile_time_value = value->IsCompileTimeValue();
    is_simple = is_simple && is_compile_time_value;
    // Keep track of the number of elements in the object literal and
    // the largest element index. If the largest element index is
    // much larger than the number of elements, creating an object
    // literal with fast elements will be a waste of space.
    uint32_t element_index = 0;
    if (key->AsArrayIndex(&element_index)) {
      max_element_index = std::max(element_index, max_element_index);
      elements++;
    } else {
      DCHECK(key->IsPropertyName());
    }
    nof_properties++;
  }
  set_depth(depth_acc);
  set_is_simple(is_simple);
  set_needs_initial_allocation_site(needs_initial_allocation_site);
  set_has_elements(elements > 0);
  set_fast_elements((max_element_index <= 32) ||
                    ((2 * elements) >= max_element_index));
}
References v8::internal::AstNode::AsMaterializedLiteral(), boilerplate_properties_, v8::internal::DCHECK(), has_null_prototype(), v8::internal::LiteralBoilerplateBuilder::InitDepthAndFlags(), InitFlagsForPendingNullPrototype(), v8::internal::LiteralBoilerplateBuilder::is_initialized(), v8::internal::LiteralBoilerplateBuilder::is_simple(), v8::internal::key, v8::internal::LiteralBoilerplateBuilder::kNotShallow, v8::internal::LiteralBoilerplateBuilder::kShallow, v8::internal::LiteralBoilerplateBuilder::needs_initial_allocation_site(), v8::internal::MaterializedLiteral::NeedsInitialAllocationSite(), properties(), v8::internal::LiteralBoilerplateBuilder::set_depth(), set_fast_elements(), set_has_elements(), set_has_null_protoype(), v8::internal::LiteralBoilerplateBuilder::set_is_simple(), v8::internal::LiteralBoilerplateBuilder::set_needs_initial_allocation_site(), and v8::internal::value.
InitFlagsForPendingNullPrototype()
void v8::internal::ObjectLiteralBoilerplateBuilder::InitFlagsForPendingNullPrototype (int i) [private]
Definition at line 394 of file ast.cc.
                                                                            {
  // We still check for __proto__:null after computed property names.
  for (; i < properties()->length(); i++) {
    if (properties()->at(i)->IsNullPrototype()) {
      set_has_null_protoype(true);
      break;
    }
  }
}
References properties(), and set_has_null_protoype().
Referenced by InitDepthAndFlags().
is_empty()
bool v8::internal::ObjectLiteralBoilerplateBuilder::is_empty () const [inline]
Definition at line 1338 of file ast.h.
                        {
    DCHECK(is_initialized());
    return !has_elements() && properties_count() == 0 &&
           properties()->length() == 0;
  }
References v8::internal::DCHECK(), has_elements(), v8::internal::LiteralBoilerplateBuilder::is_initialized(), properties(), and properties_count().
Referenced by IsEmptyObjectLiteral().
IsEmptyObjectLiteral()
bool v8::internal::ObjectLiteralBoilerplateBuilder::IsEmptyObjectLiteral () const [inline]
Definition at line 1346 of file ast.h.
                                    {
    return is_empty() && !has_null_prototype();
  }
References has_null_prototype(), and is_empty().
IsFastCloningSupported()
bool v8::internal::ObjectLiteralBoilerplateBuilder::IsFastCloningSupported () const
properties()
const ZonePtrList<Property>* v8::internal::ObjectLiteralBoilerplateBuilder::properties () const [inline]
Definition at line 1314 of file ast.h.
{ return properties_; }
References properties_.
Referenced by BuildBoilerplateDescription(), InitDepthAndFlags(), InitFlagsForPendingNullPrototype(), and is_empty().
properties_count()
int v8::internal::ObjectLiteralBoilerplateBuilder::properties_count () const [inline]
Definition at line 1313 of file ast.h.
{ return boilerplate_properties_; }
References boilerplate_properties_.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants(), and is_empty().
set_fast_elements()
void v8::internal::ObjectLiteralBoilerplateBuilder::set_fast_elements (bool fast_elements) [inline], [private]
Definition at line 1361 of file ast.h.
                                             {
    bit_field_ = FastElementsField::update(bit_field_, fast_elements);
  }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, fast_elements(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by InitDepthAndFlags().
set_has_elements()
void v8::internal::ObjectLiteralBoilerplateBuilder::set_has_elements (bool has_elements) [inline], [private]
Definition at line 1358 of file ast.h.
                                           {
    bit_field_ = HasElementsField::update(bit_field_, has_elements);
  }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, has_elements(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by InitDepthAndFlags().
set_has_null_protoype()
void v8::internal::ObjectLiteralBoilerplateBuilder::set_has_null_protoype (bool has_null_prototype) [inline], [private]
Definition at line 1364 of file ast.h.
                                                      {
    bit_field_ = HasNullPrototypeField::update(bit_field_, has_null_prototype);
  }
References v8::internal::LiteralBoilerplateBuilder::bit_field_, has_null_prototype(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by InitDepthAndFlags(), and InitFlagsForPendingNullPrototype().
Member Data Documentation
boilerplate_description_
IndirectHandle<ObjectBoilerplateDescription> v8::internal::ObjectLiteralBoilerplateBuilder::boilerplate_description_ [private]
Definition at line 1369 of file ast.h.
Referenced by boilerplate_description(), BuildBoilerplateDescription(), and GetOrBuildBoilerplateDescription().
boilerplate_properties_
uint32_t v8::internal::ObjectLiteralBoilerplateBuilder::boilerplate_properties_ [private]
Definition at line 1368 of file ast.h.
Referenced by BuildBoilerplateDescription(), InitDepthAndFlags(), and properties_count().
properties_
ZoneList<Property*>* v8::internal::ObjectLiteralBoilerplateBuilder::properties_ [private]
Definition at line 1367 of file ast.h.
Referenced by properties().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc