v8::internal::maglev::StoreGlobal Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreGlobal (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource &feedback)
compiler::NameRef name () const
compiler::FeedbackSource feedback () const
Input & context ()
Input & value ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 2, StoreGlobal >
Private Attributes
const compiler::NameRef name_
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 9267 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreGlobal::Base = FixedInputValueNodeT<2, StoreGlobal> [private]
Definition at line 9268 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreGlobal()
v8::internal::maglev::StoreGlobal::StoreGlobal (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 9271 of file maglev-ir.h.
      : Base(bitfield), name_(name), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::StoreGlobal::context () [inline]
Definition at line 9283 of file maglev-ir.h.
{ return input(0); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::StoreGlobal::feedback () const [inline]
Definition at line 9281 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::StoreGlobal::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::StoreGlobal::MaxCallStackArgs () const
name()
compiler::NameRef v8::internal::maglev::StoreGlobal::name () const [inline]
Definition at line 9280 of file maglev-ir.h.
{ return name_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreGlobal::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 7952 of file maglev-ir.cc.
                                                                         {
  os << "(" << *name().object() << ")";
}
References name(), and v8::internal::compiler::NameRef::object().
SetValueLocationConstraints()
void v8::internal::maglev::StoreGlobal::SetValueLocationConstraints ()
value()
Input& v8::internal::maglev::StoreGlobal::value () [inline]
Definition at line 9284 of file maglev-ir.h.
{ return input(1); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::StoreGlobal::feedback_ [private]
Definition at line 9293 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreGlobal::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged}
Definition at line 9277 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreGlobal::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9276 of file maglev-ir.h.
name_
const compiler::NameRef v8::internal::maglev::StoreGlobal::name_ [private]
Definition at line 9292 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc