v8::internal::ObjectTemplateInfo Class Reference
#include <templates.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
Tagged< ObjectTemplateInfo > GetParent (Isolate *isolate)
Static Public Member Functions
static void SealAndPrepareForPromotionToReadOnly (Isolate *isolate, DirectHandle< ObjectTemplateInfo > info)
Detailed Description
Definition at line 309 of file templates.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::ObjectTemplateInfo::BodyDescriptor = StructBodyDescriptor
Definition at line 324 of file templates.h.
Member Function Documentation
GetParent()
Tagged< ObjectTemplateInfo > v8::internal::ObjectTemplateInfo::GetParent (Isolate * isolate) [inline]
Definition at line 245 of file templates-inl.h.
                                                                         {
  Tagged<Object> maybe_ctor = constructor();
  if (IsUndefined(maybe_ctor, isolate)) return ObjectTemplateInfo();
  Tagged<FunctionTemplateInfo> constructor =
      Cast<FunctionTemplateInfo>(maybe_ctor);
  while (true) {
    constructor = constructor->GetParent(isolate);
    if (constructor.is_null()) return ObjectTemplateInfo();
    Tagged<Object> maybe_obj = constructor->GetInstanceTemplate();
    if (!IsUndefined(maybe_obj, isolate)) {
      return Cast<ObjectTemplateInfo>(maybe_obj);
    }
  }
  return Tagged<ObjectTemplateInfo>();
}
References v8::internal::Tagged< HeapObject >::is_null().
SealAndPrepareForPromotionToReadOnly()
void v8::internal::ObjectTemplateInfo::SealAndPrepareForPromotionToReadOnly (Isolate * isolate, DirectHandle< ObjectTemplateInfo > info) [static]
Definition at line 191 of file templates.cc.
                                                             {
  if (info->should_promote_to_read_only()) return;
  CHECK(!HeapLayout::InReadOnlySpace(*info));
  info->EnsureHasSerialNumber(isolate);
  info->set_should_promote_to_read_only(true);
}
References CHECK, and v8::internal::HeapLayout::InReadOnlySpace().
Referenced by v8::ObjectTemplate::SealAndPrepareForPromotionToReadOnly().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/templates.h
/mnt/V8SourceCode/src/objects/templates-inl.h
/mnt/V8SourceCode/src/objects/templates.cc