v8::internal::maglev::DeadNodeSweepingProcessor Class Reference
#include <maglev-post-hoc-optimizations-processors.h>
Public Member Functions
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
ProcessResult Process (AllocationBlock *node, const ProcessingState &state)
ProcessResult Process (InlinedAllocation *node, const ProcessingState &state)
template<typename NodeT >
ProcessResult Process (NodeT *node, const ProcessingState &state)
Private Attributes
MaglevGraphLabeller * labeller_ = nullptr
Detailed Description
Definition at line 331 of file maglev-post-hoc-optimizations-processors.h.
Member Function Documentation
PostPhiProcessing()
void v8::internal::maglev::DeadNodeSweepingProcessor::PostPhiProcessing () [inline]
Definition at line 343 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessBasicBlock()
void v8::internal::maglev::DeadNodeSweepingProcessor::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 339 of file maglev-post-hoc-optimizations-processors.h.
{}
PostProcessGraph()
void v8::internal::maglev::DeadNodeSweepingProcessor::PostProcessGraph (Graph * graph) [inline]
Definition at line 338 of file maglev-post-hoc-optimizations-processors.h.
{}
PreProcessBasicBlock()
BlockProcessResult v8::internal::maglev::DeadNodeSweepingProcessor::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 340 of file maglev-post-hoc-optimizations-processors.h.
                                                             {
    return BlockProcessResult::kContinue;
  }
References v8::internal::maglev::kContinue.
PreProcessGraph()
void v8::internal::maglev::DeadNodeSweepingProcessor::PreProcessGraph (Graph * graph) [inline]
Definition at line 333 of file maglev-post-hoc-optimizations-processors.h.
                                     {
    if (graph->has_graph_labeller()) {
      labeller_ = graph->graph_labeller();
    }
  }
References graph(), and labeller_.
Process() [1/3]
ProcessResult v8::internal::maglev::DeadNodeSweepingProcessor::Process (AllocationBlock * node, const ProcessingState & state) [inline]
Definition at line 345 of file maglev-post-hoc-optimizations-processors.h.
                                                                             {
    // Note: this need to be done before ValueLocationConstraintProcessor, since
    // it access the allocation offsets.
    int size = 0;
    for (auto alloc : node->allocation_list()) {
      if (alloc->HasEscaped()) {
        alloc->set_offset(size);
        size += alloc->size();
      }
    }
    // ... and update its size.
    node->set_size(size);
    // If size is zero, then none of the inlined allocations have escaped, we
    // can remove the allocation block.
    if (size == 0) return ProcessResult::kRemove;
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::AllocationBlock::allocation_list(), v8::internal::maglev::kContinue, v8::internal::maglev::kRemove, v8::internal::maglev::AllocationBlock::set_size(), and size().
Process() [2/3]
ProcessResult v8::internal::maglev::DeadNodeSweepingProcessor::Process (InlinedAllocation * node, const ProcessingState & state) [inline]
Definition at line 363 of file maglev-post-hoc-optimizations-processors.h.
                                                                               {
    // Remove inlined allocation that became non-escaping.
    if (!node->HasEscaped()) {
      if (v8_flags.trace_maglev_escape_analysis) {
        std::cout << "* Removing allocation node "
                  << PrintNodeLabel(labeller_, node) << std::endl;
      }
      return ProcessResult::kRemove;
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::InlinedAllocation::HasEscaped(), v8::internal::maglev::kContinue, v8::internal::maglev::kRemove, labeller_, and v8::internal::v8_flags.
Process() [3/3]
template<typename NodeT >
ProcessResult v8::internal::maglev::DeadNodeSweepingProcessor::Process (NodeT * node, const ProcessingState & state) [inline]
Definition at line 376 of file maglev-post-hoc-optimizations-processors.h.
                                                                   {
    if constexpr (IsValueNode(Node::opcode_of<NodeT>) &&
                  (!NodeT::kProperties.is_required_when_unused() ||
                   std::is_same_v<ArgumentsElements, NodeT>)) {
      if (!node->is_used()) {
        return ProcessResult::kRemove;
      }
      return ProcessResult::kContinue;
    }
    if constexpr (CanBeStoreToNonEscapedObject<NodeT>()) {
      if (InlinedAllocation* object =
              node->input(0).node()->template TryCast<InlinedAllocation>()) {
        if (!object->HasEscaped()) {
          if (v8_flags.trace_maglev_escape_analysis) {
            std::cout << "* Removing store node "
                      << PrintNodeLabel(labeller_, node) << " to allocation "
                      << PrintNodeLabel(labeller_, object) << std::endl;
          }
          return ProcessResult::kRemove;
        }
      }
    }
    return ProcessResult::kContinue;
  }
References v8::internal::maglev::IsValueNode(), v8::internal::maglev::kContinue, v8::internal::maglev::kRemove, labeller_, and v8::internal::v8_flags.
Member Data Documentation
labeller_
MaglevGraphLabeller* v8::internal::maglev::DeadNodeSweepingProcessor::labeller_ = nullptr [private]
Definition at line 403 of file maglev-post-hoc-optimizations-processors.h.
Referenced by PreProcessGraph(), and Process().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-post-hoc-optimizations-processors.h