cppgc::subtle::DisallowGarbageCollectionScope Class Reference
Disallows garbage collection finalizations.
#include <heap-consistency.h>
Public Member Functions
DisallowGarbageCollectionScope (HeapHandle &heap_handle)
Constructs a scoped object that automatically enters and leaves a disallow garbage collection scope based on its lifetime.
~DisallowGarbageCollectionScope ()
DisallowGarbageCollectionScope (const DisallowGarbageCollectionScope &)=delete
DisallowGarbageCollectionScope & operator= (const DisallowGarbageCollectionScope &)=delete
Static Public Member Functions
static bool IsGarbageCollectionAllowed (HeapHandle &heap_handle)
static void Enter (HeapHandle &heap_handle)
Enters a disallow garbage collection scope.
static void Leave (HeapHandle &heap_handle)
Leaves a disallow garbage collection scope.
Private Member Functions
CPPGC_STACK_ALLOCATED ()
Private Attributes
HeapHandle & heap_handle_
Detailed Description
Disallows garbage collection finalizations.
Any garbage collection triggers result in a crash when in this scope.
Note that the garbage collector already covers paths that can lead to garbage collections, so user code does not require checking IsGarbageCollectionAllowed() before allocations.
Definition at line 220 of file heap-consistency.h.
Constructor & Destructor Documentation
DisallowGarbageCollectionScope() [1/2]
cppgc::subtle::DisallowGarbageCollectionScope::DisallowGarbageCollectionScope (cppgc::HeapHandle & heap_handle) [explicit]
Constructs a scoped object that automatically enters and leaves a disallow garbage collection scope based on its lifetime.
Parameters
heap_handle The corresponding heap.
Definition at line 33 of file heap-consistency.cc.
    : heap_handle_(heap_handle) {
  Enter(heap_handle);
}
References Enter().
 DisallowGarbageCollectionScope()
cppgc::subtle::DisallowGarbageCollectionScope::~DisallowGarbageCollectionScope ()
Definition at line 39 of file heap-consistency.cc.
                                                                {
  Leave(heap_handle_);
}
References heap_handle_, and Leave().
DisallowGarbageCollectionScope() [2/2]
cppgc::subtle::DisallowGarbageCollectionScope::DisallowGarbageCollectionScope (const DisallowGarbageCollectionScope &) [delete]
Member Function Documentation
CPPGC_STACK_ALLOCATED()
cppgc::subtle::DisallowGarbageCollectionScope::CPPGC_STACK_ALLOCATED () [private]
Enter()
void cppgc::subtle::DisallowGarbageCollectionScope::Enter (cppgc::HeapHandle & heap_handle) [static]
Enters a disallow garbage collection scope.
Must be paired with Leave(). Prefer a scope instance of DisallowGarbageCollectionScope.
Parameters
heap_handle The corresponding heap.
Definition at line 22 of file heap-consistency.cc.
                                                                       {
  auto& heap_base = internal::HeapBase::From(heap_handle);
  heap_base.EnterDisallowGCScope();
}
References cppgc::internal::HeapBase::From().
Referenced by DisallowGarbageCollectionScope().
IsGarbageCollectionAllowed()
bool cppgc::subtle::DisallowGarbageCollectionScope::IsGarbageCollectionAllowed (cppgc::HeapHandle & heap_handle) [static]
Returns
whether garbage collections are currently allowed.
Definition at line 15 of file heap-consistency.cc.
                                  {
  auto& heap_base = internal::HeapBase::From(heap_handle);
  return !heap_base.IsGCForbidden();
}
References cppgc::internal::HeapBase::From().
Leave()
void cppgc::subtle::DisallowGarbageCollectionScope::Leave (cppgc::HeapHandle & heap_handle) [static]
Leaves a disallow garbage collection scope.
Must be paired with Enter(). Prefer a scope instance of DisallowGarbageCollectionScope.
Parameters
heap_handle The corresponding heap.
Definition at line 28 of file heap-consistency.cc.
                                                                       {
  auto& heap_base = internal::HeapBase::From(heap_handle);
  heap_base.LeaveDisallowGCScope();
}
References cppgc::internal::HeapBase::From().
Referenced by ~DisallowGarbageCollectionScope().
operator=()
DisallowGarbageCollectionScope& cppgc::subtle::DisallowGarbageCollectionScope::operator= (const DisallowGarbageCollectionScope &) [delete]
Member Data Documentation
heap_handle_
HeapHandle& cppgc::subtle::DisallowGarbageCollectionScope::heap_handle_ [private]
Definition at line 260 of file heap-consistency.h.
Referenced by ~DisallowGarbageCollectionScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/heap-consistency.h
/mnt/V8SourceCode/src/heap/cppgc/heap-consistency.cc