v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer Class Reference
#include <wasm-load-elimination-reducer.h>
Classes
struct Snapshot
Public Types
using AliasTable = SparseOpIndexSnapshotTable< bool >
using AliasKey = AliasTable::Key
using AliasSnapshot = AliasTable::Snapshot
using MemoryKey = wle::WasmMemoryContentTable::Key
using MemorySnapshot = wle::WasmMemoryContentTable::Snapshot
Public Member Functions
WasmLoadEliminationAnalyzer (PipelineData *data, Graph &graph, Zone *phase_zone)
void Run ()
OpIndex Replacement (OpIndex index)
Private Member Functions
void ProcessBlock (const Block &block, bool compute_start_snapshot)
void ProcessStructGet (OpIndex op_idx, const StructGetOp &op)
void ProcessStructSet (OpIndex op_idx, const StructSetOp &op)
void ProcessArrayLength (OpIndex op_idx, const ArrayLengthOp &op)
void ProcessWasmAllocateArray (OpIndex op_idx, const WasmAllocateArrayOp &op)
void ProcessStringAsWtf16 (OpIndex op_idx, const StringAsWtf16Op &op)
void ProcessStringPrepareForGetCodeUnit (OpIndex op_idx, const StringPrepareForGetCodeUnitOp &op)
void ProcessAnyConvertExtern (OpIndex op_idx, const AnyConvertExternOp &op)
void ProcessAssertNotNull (OpIndex op_idx, const AssertNotNullOp &op)
void ProcessAllocate (OpIndex op_idx, const AllocateOp &op)
void ProcessCall (OpIndex op_idx, const CallOp &op)
void ProcessPhi (OpIndex op_idx, const PhiOp &op)
void DcheckWordBinop (OpIndex op_idx, const WordBinopOp &binop)
template<bool for_loop_revisit = false>
bool BeginBlock (const Block *block)
void FinishBlock (const Block *block)
void SealAndDiscard ()
void StoreLoopSnapshotInForwardPredecessor (const Block &loop_header)
bool BackedgeHasSnapshot (const Block &loop_header) const
void InvalidateAllNonAliasingInputs (const Operation &op)
void InvalidateIfAlias (OpIndex op_idx)
Private Attributes
Graph & graph_
Zone * phase_zone_
FixedOpIndexSidetable< OpIndex > replacements_
AliasTable non_aliasing_objects_
wle::WasmMemoryContentTable memory_
FixedBlockSidetable< std::optional< Snapshot > > block_to_snapshot_mapping_
ZoneVector< AliasSnapshot > predecessor_alias_snapshots_
ZoneVector< MemorySnapshot > predecessor_memory_snapshots_
Detailed Description
Definition at line 384 of file wasm-load-elimination-reducer.h.
Member Typedef Documentation
AliasKey
using v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::AliasKey = AliasTable::Key
Definition at line 387 of file wasm-load-elimination-reducer.h.
AliasSnapshot
using v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::AliasSnapshot = AliasTable::Snapshot
Definition at line 388 of file wasm-load-elimination-reducer.h.
AliasTable
using v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::AliasTable = SparseOpIndexSnapshotTable<bool>
Definition at line 386 of file wasm-load-elimination-reducer.h.
MemoryKey
using v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::MemoryKey = wle::WasmMemoryContentTable::Key
Definition at line 390 of file wasm-load-elimination-reducer.h.
MemorySnapshot
using v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::MemorySnapshot = wle::WasmMemoryContentTable::Snapshot
Definition at line 391 of file wasm-load-elimination-reducer.h.
Constructor & Destructor Documentation
WasmLoadEliminationAnalyzer()
v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::WasmLoadEliminationAnalyzer (PipelineData * data, Graph & graph, Zone * phase_zone) [inline]
Definition at line 393 of file wasm-load-elimination-reducer.h.
      : graph_(graph),
        phase_zone_(phase_zone),
        replacements_(graph.op_id_count(), phase_zone, &graph),
        non_aliasing_objects_(phase_zone),
        memory_(data, phase_zone, non_aliasing_objects_, replacements_, graph_),
        block_to_snapshot_mapping_(graph.block_count(), phase_zone),
        predecessor_alias_snapshots_(phase_zone),
        predecessor_memory_snapshots_(phase_zone) {}
Member Function Documentation
BackedgeHasSnapshot()
bool v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BackedgeHasSnapshot (const Block & loop_header) const [private]
Definition at line 1003 of file wasm-load-elimination-reducer.h.
                                    {
  DCHECK(loop_header.IsLoop());
  return block_to_snapshot_mapping_[loop_header.LastPredecessor()->index()]
      .has_value();
}
References block_to_snapshot_mapping_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::Block::LastPredecessor().
Referenced by ProcessBlock().
BeginBlock()
template<bool for_loop_revisit>
bool v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::BeginBlock (const Block * block) [private]
Definition at line 1011 of file wasm-load-elimination-reducer.h.
                                                               {
  DCHECK_IMPLIES(
      for_loop_revisit,
      block->IsLoop() &&
          block_to_snapshot_mapping_[block->LastPredecessor()->index()]
              .has_value());
  // Collect the snapshots of all predecessors.
  {
    predecessor_alias_snapshots_.clear();
    predecessor_memory_snapshots_.clear();
    for (const Block* p : block->PredecessorsIterable()) {
      auto pred_snapshots = block_to_snapshot_mapping_[p->index()];
      // When we visit the loop for the first time, the loop header hasn't
      // been visited yet, so we ignore it.
      DCHECK_IMPLIES(!pred_snapshots.has_value(),
                     block->IsLoop() && block->LastPredecessor() == p);
      if (!pred_snapshots.has_value()) {
        DCHECK(!for_loop_revisit);
        continue;
      }
      // Note that the backedge snapshot of an inner loop in kFirstVisit will
      // also be taken into account if we are in the kSecondVisit of an outer
      // loop. The data in the backedge snapshot could be out-dated, but if it
      // is, then it's fine: if the backedge of the outer-loop was more
      // restrictive than its forward incoming edge, then the forward incoming
      // edge of the inner loop should reflect this restriction.
      predecessor_alias_snapshots_.push_back(pred_snapshots->alias_snapshot);
      predecessor_memory_snapshots_.push_back(pred_snapshots->memory_snapshot);
    }
  }
  // Note that predecessors are in reverse order, which means that the backedge
  // is at offset 0.
  constexpr int kBackedgeOffset = 0;
  constexpr int kForwardEdgeOffset = 1;
  bool loop_needs_revisit = false;
  // Start a new snapshot for this block by merging information from
  // predecessors.
  auto merge_aliases = [&](AliasKey key,
                           base::Vector<const bool> predecessors) -> bool {
    if (for_loop_revisit && predecessors[kForwardEdgeOffset] &&
        !predecessors[kBackedgeOffset]) {
      // The backedge doesn't think that {key} is no-alias, but the loop
      // header previously thought it was --> need to revisit.
      loop_needs_revisit = true;
    }
    return base::all_of(predecessors);
  };
  non_aliasing_objects_.StartNewSnapshot(
      base::VectorOf(predecessor_alias_snapshots_), merge_aliases);
  // Merging for {memory_} means setting values to Invalid unless all
  // predecessors have the same value.
  // TODO(dmercadier): we could insert of Phis during the pass to merge existing
  // information. This is a bit hard, because we are currently in an analyzer
  // rather than a reducer. Still, we could "prepare" the insertion now and then
  // really insert them during the Reduce phase of the CopyingPhase.
  auto merge_memory = [&](MemoryKey key,
                          base::Vector<const OpIndex> predecessors) -> OpIndex {
    if (for_loop_revisit && predecessors[kForwardEdgeOffset].valid() &&
        predecessors[kBackedgeOffset] != predecessors[kForwardEdgeOffset]) {
      // {key} had a value in the loop header, but the backedge and the forward
      // edge don't agree on its value, which means that the loop invalidated
      // some memory data, and thus needs to be revisited.
      loop_needs_revisit = true;
    }
    return base::all_equal(predecessors) ? predecessors[0] : OpIndex::Invalid();
  };
  memory_.StartNewSnapshot(base::VectorOf(predecessor_memory_snapshots_),
                           merge_memory);
  if (block->IsLoop()) return loop_needs_revisit;
  return false;
}
References v8::base::all_equal(), v8::base::all_of(), block_to_snapshot_mapping_, v8::internal::ZoneVector< T >::clear(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::key, v8::internal::compiler::turboshaft::Block::LastPredecessor(), memory_, non_aliasing_objects_, predecessor_alias_snapshots_, predecessor_memory_snapshots_, v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), and v8::base::VectorOf().
Referenced by ProcessBlock().
DcheckWordBinop()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::DcheckWordBinop (OpIndex op_idx, const WordBinopOp & binop) [private]
Definition at line 932 of file wasm-load-elimination-reducer.h.
                                                                            {
#ifdef DEBUG
  auto check = [&](V<Word> left, V<Word> right) {
    if (auto key = non_aliasing_objects_.TryGetKeyFor(left);
        key.has_value() && non_aliasing_objects_.Get(*key)) {
      int64_t cst;
      DCHECK_EQ(binop.kind, WordBinopOp::Kind::kBitwiseAnd);
      DCHECK(OperationMatcher(graph_).MatchSignedIntegralConstant(right, &cst));
      DCHECK_EQ(cst, kSmiTagMask);
    }
  };
  check(binop.left(), binop.right());
  check(binop.right(), binop.left());
#endif
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), graph_, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::key, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::kSmiTagMask, v8::internal::compiler::turboshaft::WordBinopOp::left(), non_aliasing_objects_, v8::internal::compiler::turboshaft::WordBinopOp::right(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::TryGetKeyFor().
Referenced by ProcessBlock().
FinishBlock()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::FinishBlock (const Block * block) [private]
Definition at line 980 of file wasm-load-elimination-reducer.h.
                                                                {
  block_to_snapshot_mapping_[block->index()] =
      Snapshot{non_aliasing_objects_.Seal(), memory_.Seal()};
}
References block_to_snapshot_mapping_, v8::internal::compiler::turboshaft::Block::index(), memory_, non_aliasing_objects_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
Referenced by ProcessBlock(), and Run().
InvalidateAllNonAliasingInputs()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::InvalidateAllNonAliasingInputs (const Operation & op) [private]
Definition at line 909 of file wasm-load-elimination-reducer.h.
                         {
  for (OpIndex input : op.inputs()) {
    InvalidateIfAlias(input);
  }
}
References v8::internal::compiler::turboshaft::Operation::inputs(), and InvalidateIfAlias().
Referenced by ProcessBlock(), ProcessCall(), and ProcessPhi().
InvalidateIfAlias()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::InvalidateIfAlias (OpIndex op_idx) [private]
Definition at line 916 of file wasm-load-elimination-reducer.h.
                                                                  {
  if (auto key = non_aliasing_objects_.TryGetKeyFor(op_idx);
      key.has_value() && non_aliasing_objects_.Get(*key)) {
    // An known non-aliasing object was passed as input to the Call; the Call
    // could create aliases, so we have to consider going forward that this
    // object could actually have aliases.
    non_aliasing_objects_.Set(*key, false);
  }
}
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::key, non_aliasing_objects_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::TryGetKeyFor().
Referenced by InvalidateAllNonAliasingInputs().
ProcessAllocate()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAllocate (OpIndex op_idx, const AllocateOp & op) [private]
Definition at line 949 of file wasm-load-elimination-reducer.h.
                                                                     {
  // In particular, this handles {struct.new}.
  non_aliasing_objects_.Set(op_idx, true);
}
References non_aliasing_objects_, and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set().
Referenced by ProcessBlock().
ProcessAnyConvertExtern()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern (OpIndex op_idx, const AnyConvertExternOp & op) [private]
Definition at line 846 of file wasm-load-elimination-reducer.h.
                                                       {
  static constexpr int offset = wle::kAnyConvertExternIndex;
  OpIndex existing = memory_.FindLoadLike(convert.object(), offset);
  if (existing.valid()) {
    DCHECK_EQ(Opcode::kAnyConvertExtern, graph_.Get(existing).opcode);
    replacements_[op_idx] = existing;
    return;
  }
  replacements_[op_idx] = OpIndex::Invalid();
  memory_.InsertLoadLike(convert.object(), offset, op_idx);
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindLoadLike(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::wle::kAnyConvertExternIndex, memory_, v8::internal::compiler::turboshaft::Operation::opcode, replacements_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessArrayLength()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength (OpIndex op_idx, const ArrayLengthOp & op) [private]
Definition at line 794 of file wasm-load-elimination-reducer.h.
                                                 {
  static constexpr int offset = wle::kArrayLengthFieldIndex;
  OpIndex existing = memory_.FindLoadLike(length.array(), offset);
  if (existing.valid()) {
#if DEBUG
    const Operation& replacement = graph_.Get(existing);
    DCHECK_EQ(replacement.outputs_rep().size(), 1);
    DCHECK_EQ(length.outputs_rep().size(), 1);
    DCHECK_EQ(replacement.outputs_rep()[0], length.outputs_rep()[0]);
#endif
    replacements_[op_idx] = existing;
    return;
  }
  replacements_[op_idx] = OpIndex::Invalid();
  memory_.InsertLoadLike(length.array(), offset, op_idx);
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindLoadLike(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::wle::kArrayLengthFieldIndex, v8::internal::length, memory_, v8::internal::compiler::turboshaft::Operation::outputs_rep(), replacements_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessAssertNotNull()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull (OpIndex op_idx, const AssertNotNullOp & op) [private]
Definition at line 859 of file wasm-load-elimination-reducer.h.
                                                   {
  static constexpr int offset = wle::kAssertNotNullIndex;
  OpIndex existing = memory_.FindLoadLike(assert.object(), offset);
  if (existing.valid()) {
    DCHECK_EQ(Opcode::kAssertNotNull, graph_.Get(existing).opcode);
    replacements_[op_idx] = existing;
    return;
  }
  replacements_[op_idx] = OpIndex::Invalid();
  memory_.InsertLoadLike(assert.object(), offset, op_idx);
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindLoadLike(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::wle::kAssertNotNullIndex, memory_, v8::internal::compiler::turboshaft::Operation::opcode, replacements_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessBlock()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock (const Block & block, bool compute_start_snapshot) [private]
Definition at line 582 of file wasm-load-elimination-reducer.h.
                                                                            {
  if (compute_start_snapshot) {
    BeginBlock(&block);
  }
  if (block.IsLoop() && BackedgeHasSnapshot(block)) {
    // Update the associated snapshot for the forward edge with the merged
    // snapshot information from the forward- and backward edge.
    // This will make sure that when evaluating whether a loop needs to be
    // revisited, the inner loop compares the merged state with the backedge
    // preventing us from exponential revisits for loops where the backedge
    // invalidates loads which are eliminatable on the forward edge.
    StoreLoopSnapshotInForwardPredecessor(block);
  }
  for (OpIndex op_idx : graph_.OperationIndices(block)) {
    Operation& op = graph_.Get(op_idx);
    if (ShouldSkipOptimizationStep()) continue;
    if (ShouldSkipOperation(op)) continue;
    switch (op.opcode) {
      case Opcode::kStructGet:
        ProcessStructGet(op_idx, op.Cast<StructGetOp>());
        break;
      case Opcode::kStructSet:
        ProcessStructSet(op_idx, op.Cast<StructSetOp>());
        break;
      case Opcode::kStructAtomicRMW:
        ProcessAtomicRMW(op_idx, op.Cast<StructAtomicRMWOp>());
        break;
      case Opcode::kArrayLength:
        ProcessArrayLength(op_idx, op.Cast<ArrayLengthOp>());
        break;
      case Opcode::kWasmAllocateArray:
        ProcessWasmAllocateArray(op_idx, op.Cast<WasmAllocateArrayOp>());
        break;
      case Opcode::kStringAsWtf16:
        ProcessStringAsWtf16(op_idx, op.Cast<StringAsWtf16Op>());
        break;
      case Opcode::kStringPrepareForGetCodeUnit:
        ProcessStringPrepareForGetCodeUnit(
            op_idx, op.Cast<StringPrepareForGetCodeUnitOp>());
        break;
      case Opcode::kAnyConvertExtern:
        ProcessAnyConvertExtern(op_idx, op.Cast<AnyConvertExternOp>());
        break;
      case Opcode::kAssertNotNull:
        // TODO(14108): We'll probably want to handle WasmTypeCast as
        // a "load-like" instruction too, to eliminate repeated casts.
        ProcessAssertNotNull(op_idx, op.Cast<AssertNotNullOp>());
        break;
      case Opcode::kArraySet:
        break;
      case Opcode::kAllocate:
        // Create new non-alias.
        ProcessAllocate(op_idx, op.Cast<AllocateOp>());
        break;
      case Opcode::kCall:
        // Invalidate state (+ maybe invalidate aliases).
        ProcessCall(op_idx, op.Cast<CallOp>());
        break;
      case Opcode::kPhi:
        // Invalidate aliases.
        ProcessPhi(op_idx, op.Cast<PhiOp>());
        break;
      case Opcode::kLoad:
        // Atomic loads have the "can_write" bit set, because they make
        // writes on other threads visible. At any rate, we have to
        // explicitly skip them here.
      case Opcode::kStore:
        // We rely on having no raw "Store" operations operating on Wasm
        // objects at this point in the pipeline.
        // TODO(jkummerow): Is there any way to DCHECK that?
      case Opcode::kAssumeMap:
      case Opcode::kCatchBlockBegin:
      case Opcode::kRetain:
      case Opcode::kDidntThrow:
      case Opcode::kCheckException:
      case Opcode::kAtomicRMW:
      case Opcode::kAtomicWord32Pair:
      case Opcode::kMemoryBarrier:
      case Opcode::kJSStackCheck:
      case Opcode::kWasmStackCheck:
      case Opcode::kSimd128LaneMemory:
      case Opcode::kGlobalSet:
      case Opcode::kParameter:
      case Opcode::kSetStackPointer:
        // We explicitly break for those operations that have can_write effects
        // but don't actually write, or cannot interfere with load elimination.
        break;
      case Opcode::kWordBinop:
        // A WordBinop should never invalidate aliases (since the only time when
        // it should take a non-aliasing object as input is for Smi checks).
        DcheckWordBinop(op_idx, op.Cast<WordBinopOp>());
        break;
      case Opcode::kFrameState:
      case Opcode::kDeoptimizeIf:
      case Opcode::kComparison:
      case Opcode::kTrapIf:
        // We explicitly break for these opcodes so that we don't call
        // InvalidateAllNonAliasingInputs on their inputs, since they don't
        // really create aliases. (and also, they don't write so it's
        // fine to break)
        DCHECK(!op.Effects().can_write());
        break;
      case Opcode::kDeoptimize:
      case Opcode::kReturn:
        // We explicitly break for these opcodes so that we don't call
        // InvalidateAllNonAliasingInputs on their inputs, since they are block
        // terminators without successors, meaning that it's not useful for the
        // rest of the analysis to invalidate anything here.
        DCHECK(op.IsBlockTerminator() && SuccessorBlocks(op).empty());
        break;
      default:
        // Operations that `can_write` should invalidate the state. All such
        // operations should be already handled above, which means that we don't
        // need a `if (can_write) { Invalidate(); }` here.
        CHECK(!op.Effects().can_write());
        // Even if the operation doesn't write, it could create an alias to its
        // input by returning it. This happens for instance in Phis and in
        // Change (although ChangeOp is already handled earlier by calling
        // ProcessChange). We are conservative here by calling
        // InvalidateAllNonAliasingInputs for all operations even though only
        // few can actually create aliases to fresh allocations, the reason
        // being that missing such a case would be a security issue, and it
        // should be rare for fresh allocations to be used outside of
        // Call/Store/Load/Change anyways.
        InvalidateAllNonAliasingInputs(op);
        break;
    }
  }
  FinishBlock(&block);
}
References BackedgeHasSnapshot(), BeginBlock(), v8::internal::compiler::turboshaft::OpEffects::can_write(), v8::internal::compiler::turboshaft::Operation::Cast(), CHECK, v8::internal::DCHECK(), DcheckWordBinop(), v8::internal::compiler::turboshaft::Operation::Effects(), FinishBlock(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, InvalidateAllNonAliasingInputs(), v8::internal::compiler::turboshaft::Operation::IsBlockTerminator(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::OperationIndices(), ProcessAllocate(), ProcessAnyConvertExtern(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessCall(), ProcessPhi(), ProcessStringAsWtf16(), ProcessStringPrepareForGetCodeUnit(), ProcessStructGet(), ProcessStructSet(), ProcessWasmAllocateArray(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), StoreLoopSnapshotInForwardPredecessor(), and v8::internal::compiler::turboshaft::SuccessorBlocks().
Referenced by Run().
ProcessCall()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall (OpIndex op_idx, const CallOp & op) [private]
Definition at line 876 of file wasm-load-elimination-reducer.h.
                                                                {
  // Some builtins do not create aliases and do not invalidate existing
  // memory, and some even return fresh objects. For such cases, we don't
  // invalidate the state, and record the non-alias if any.
  if (!op.Effects().can_write()) {
    return;
  }
  // TODO(jkummerow): Add special handling to builtins that are known not to
  // have relevant side effects. Alternatively, specify their effects to not
  // include `CanWriteMemory()`.
#if 0
  if (auto builtin_id = TryGetBuiltinId(
          graph_.Get(op.callee()).TryCast<ConstantOp>(), broker_)) {
    switch (*builtin_id) {
      case Builtin::kExample:
        // This builtin touches no Wasm objects, and calls no other functions.
        return;
      default:
        break;
    }
  }
#endif
  // Not a builtin call, or not a builtin that we know doesn't invalidate
  // memory.
  InvalidateAllNonAliasingInputs(op);
  // The call could modify arbitrary memory, so we invalidate every
  // potentially-aliasing object.
  memory_.InvalidateMaybeAliasing();
}
References v8::internal::compiler::turboshaft::CallOp::callee(), v8::internal::compiler::turboshaft::OpEffects::can_write(), v8::internal::compiler::turboshaft::CallOp::Effects(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, InvalidateAllNonAliasingInputs(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InvalidateMaybeAliasing(), memory_, v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::compiler::turboshaft::TryGetBuiltinId().
Referenced by ProcessBlock().
ProcessPhi()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessPhi (OpIndex op_idx, const PhiOp & op) [private]
Definition at line 955 of file wasm-load-elimination-reducer.h.
                                                                             {
  InvalidateAllNonAliasingInputs(phi);
  base::Vector<const OpIndex> inputs = phi.inputs();
  // This copies some of the functionality of {RequiredOptimizationReducer}:
  // Phis whose inputs are all the same value can be replaced by that value.
  // We need to have this logic here because interleaving it with other cases
  // of load elimination can unlock further optimizations: simplifying Phis
  // can allow elimination of more loads, which can then allow simplification
  // of even more Phis.
  if (inputs.size() > 0) {
    bool same_inputs = true;
    OpIndex first = memory_.ResolveBase(inputs.first());
    for (const OpIndex& input : inputs.SubVectorFrom(1)) {
      if (memory_.ResolveBase(input) != first) {
        same_inputs = false;
        break;
      }
    }
    if (same_inputs) {
      replacements_[op_idx] = first;
    }
  }
}
References v8::base::Vector< T >::first(), v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), InvalidateAllNonAliasingInputs(), memory_, replacements_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::ResolveBase(), v8::base::Vector< T >::size(), and v8::base::Vector< T >::SubVectorFrom().
Referenced by ProcessBlock().
ProcessStringAsWtf16()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16 (OpIndex op_idx, const StringAsWtf16Op & op) [private]
Definition at line 819 of file wasm-load-elimination-reducer.h.
                                               {
  static constexpr int offset = wle::kStringAsWtf16Index;
  OpIndex existing = memory_.FindLoadLike(op.string(), offset);
  if (existing.valid()) {
    DCHECK_EQ(Opcode::kStringAsWtf16, graph_.Get(existing).opcode);
    replacements_[op_idx] = existing;
    return;
  }
  replacements_[op_idx] = OpIndex::Invalid();
  memory_.InsertLoadLike(op.string(), offset, op_idx);
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindLoadLike(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::wle::kStringAsWtf16Index, memory_, v8::internal::compiler::turboshaft::Operation::opcode, replacements_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessStringPrepareForGetCodeUnit()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit (OpIndex op_idx, const StringPrepareForGetCodeUnitOp & op) [private]
Definition at line 832 of file wasm-load-elimination-reducer.h.
                                                               {
  static constexpr int offset = wle::kStringPrepareForGetCodeunitIndex;
  OpIndex existing = memory_.FindLoadLike(prep.string(), offset);
  if (existing.valid()) {
    DCHECK_EQ(Opcode::kStringPrepareForGetCodeUnit,
              graph_.Get(existing).opcode);
    replacements_[op_idx] = existing;
    return;
  }
  replacements_[op_idx] = OpIndex::Invalid();
  memory_.InsertLoadLike(prep.string(), offset, op_idx);
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::FindLoadLike(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::wle::kStringPrepareForGetCodeunitIndex, memory_, v8::internal::compiler::turboshaft::Operation::opcode, replacements_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessStructGet()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet (OpIndex op_idx, const StructGetOp & op) [private]
Definition at line 748 of file wasm-load-elimination-reducer.h.
                                                                           {
  // TODO(mliedtke): struct.atomic.get also participates in load-elimination by
  // providing values that can be used to load-eliminate struct.get operations
  // for the same field. Is this the desired behavior?
  OpIndex existing = memory_.Find(get);
  if (existing.valid()) {
    const Operation& replacement = graph_.Get(existing);
    DCHECK_EQ(replacement.outputs_rep().size(), 1);
    DCHECK_EQ(get.outputs_rep().size(), 1);
    uint8_t size = get.type->field(get.field_index).value_kind_size();
    if (RepIsCompatible(replacement.outputs_rep()[0], get.outputs_rep()[0],
                        size)) {
      replacements_[op_idx] = existing;
      return;
    }
  }
  replacements_[op_idx] = OpIndex::Invalid();
  memory_.Insert(get, op_idx);
}
References DCHECK_EQ, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Find(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Insert(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), memory_, v8::internal::compiler::turboshaft::Operation::outputs_rep(), v8::internal::compiler::turboshaft::RepIsCompatible(), replacements_, size(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessStructSet()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructSet (OpIndex op_idx, const StructSetOp & op) [private]
Definition at line 769 of file wasm-load-elimination-reducer.h.
                                                                           {
  if (memory_.HasValueWithIncorrectMutability(set)) {
    // This struct.set is unreachable. We don't have a good way to annotate
    // it as such, so we use "replace with itself" as a sentinel.
    // TODO(jkummerow): Check how often this case is triggered in practice.
    replacements_[op_idx] = op_idx;
    return;
  }
  memory_.Invalidate(set);
  memory_.Insert(set);
  // Updating aliases if the value stored was known as non-aliasing.
  OpIndex value = set.value();
  if (non_aliasing_objects_.HasKeyFor(value)) {
    non_aliasing_objects_.Set(value, false);
  }
}
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::HasKeyFor(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::HasValueWithIncorrectMutability(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Insert(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::Invalidate(), memory_, non_aliasing_objects_, replacements_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), and v8::internal::value.
Referenced by ProcessBlock().
ProcessWasmAllocateArray()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessWasmAllocateArray (OpIndex op_idx, const WasmAllocateArrayOp & op) [private]
Definition at line 812 of file wasm-load-elimination-reducer.h.
                                                      {
  non_aliasing_objects_.Set(op_idx, true);
  static constexpr int offset = wle::kArrayLengthFieldIndex;
  memory_.InsertLoadLike(op_idx, offset, alloc.length());
}
References v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::InsertLoadLike(), v8::internal::compiler::turboshaft::wle::kArrayLengthFieldIndex, memory_, non_aliasing_objects_, and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set().
Referenced by ProcessBlock().
Replacement()
OpIndex v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Replacement (OpIndex index) [inline]
Definition at line 454 of file wasm-load-elimination-reducer.h.
{ return replacements_[index]; }
References v8::internal::index, and replacements_.
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructGet(), and v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::StructSet().
Run()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::Run () [inline]
Definition at line 404 of file wasm-load-elimination-reducer.h.
             {
    LoopFinder loop_finder(phase_zone_, &graph_, LoopFinder::Config{});
    AnalyzerIterator iterator(phase_zone_, graph_, loop_finder);
    bool compute_start_snapshot = true;
    while (iterator.HasNext()) {
      const Block* block = iterator.Next();
      ProcessBlock(*block, compute_start_snapshot);
      compute_start_snapshot = true;
      // Consider re-processing for loops.
      if (const GotoOp* last = block->LastOperation(graph_).TryCast<GotoOp>()) {
        if (last->destination->IsLoop() &&
            last->destination->LastPredecessor() == block) {
          const Block* loop_header = last->destination;
          // {block} is the backedge of a loop. We recompute the loop header's
          // initial snapshots, and if they differ from its original snapshot,
          // then we revisit the loop.
          if (BeginBlock<true>(loop_header)) {
            // We set the snapshot of the loop's 1st predecessor to the newly
            // computed snapshot. It's not quite correct, but this predecessor
            // is guaranteed to end with a Goto, and we are now visiting the
            // loop, which means that we don't really care about this
            // predecessor anymore.
            // The reason for saving this snapshot is to prevent infinite
            // looping, since the next time we reach this point, the backedge
            // snapshot could still invalidate things from the forward edge
            // snapshot. By restricting the forward edge snapshot, we prevent
            // this.
            const Block* loop_1st_pred =
                loop_header->LastPredecessor()->NeighboringPredecessor();
            FinishBlock(loop_1st_pred);
            // And we start a new fresh snapshot from this predecessor.
            auto pred_snapshots =
                block_to_snapshot_mapping_[loop_1st_pred->index()];
            non_aliasing_objects_.StartNewSnapshot(
                pred_snapshots->alias_snapshot);
            memory_.StartNewSnapshot(pred_snapshots->memory_snapshot);
            iterator.MarkLoopForRevisit();
            compute_start_snapshot = false;
          } else {
            SealAndDiscard();
          }
        }
      }
    }
  }
References block_to_snapshot_mapping_, FinishBlock(), graph_, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), memory_, v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), non_aliasing_objects_, phase_zone_, ProcessBlock(), SealAndDiscard(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::turboshaft::WasmLoadEliminationReducer< Next >::Analyze().
SealAndDiscard()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::SealAndDiscard () [private]
Definition at line 985 of file wasm-load-elimination-reducer.h.
                                                 {
  non_aliasing_objects_.Seal();
  memory_.Seal();
}
References memory_, non_aliasing_objects_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
Referenced by Run().
StoreLoopSnapshotInForwardPredecessor()
void v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor (const Block & loop_header) [private]
Definition at line 990 of file wasm-load-elimination-reducer.h.
                              {
  auto non_aliasing_snapshot = non_aliasing_objects_.Seal();
  auto memory_snapshot = memory_.Seal();
  block_to_snapshot_mapping_
      [loop_header.LastPredecessor()->NeighboringPredecessor()->index()] =
          Snapshot{non_aliasing_snapshot, memory_snapshot};
  non_aliasing_objects_.StartNewSnapshot(non_aliasing_snapshot);
  memory_.StartNewSnapshot(memory_snapshot);
}
References block_to_snapshot_mapping_, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), memory_, v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), non_aliasing_objects_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot().
Referenced by ProcessBlock().
Member Data Documentation
block_to_snapshot_mapping_
FixedBlockSidetable<std::optional<Snapshot> > v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::block_to_snapshot_mapping_ [private]
Definition at line 509 of file wasm-load-elimination-reducer.h.
Referenced by BackedgeHasSnapshot(), BeginBlock(), FinishBlock(), Run(), and StoreLoopSnapshotInForwardPredecessor().
graph_
Graph& v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::graph_ [private]
Definition at line 497 of file wasm-load-elimination-reducer.h.
Referenced by DcheckWordBinop(), ProcessAnyConvertExtern(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessBlock(), ProcessCall(), ProcessStringAsWtf16(), ProcessStringPrepareForGetCodeUnit(), ProcessStructGet(), and Run().
memory_
wle::WasmMemoryContentTable v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::memory_ [private]
Definition at line 503 of file wasm-load-elimination-reducer.h.
Referenced by BeginBlock(), FinishBlock(), ProcessAnyConvertExtern(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessCall(), ProcessPhi(), ProcessStringAsWtf16(), ProcessStringPrepareForGetCodeUnit(), ProcessStructGet(), ProcessStructSet(), ProcessWasmAllocateArray(), Run(), SealAndDiscard(), and StoreLoopSnapshotInForwardPredecessor().
non_aliasing_objects_
AliasTable v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::non_aliasing_objects_ [private]
Definition at line 502 of file wasm-load-elimination-reducer.h.
Referenced by BeginBlock(), DcheckWordBinop(), FinishBlock(), InvalidateIfAlias(), ProcessAllocate(), ProcessStructSet(), ProcessWasmAllocateArray(), Run(), SealAndDiscard(), and StoreLoopSnapshotInForwardPredecessor().
phase_zone_
Zone* v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::phase_zone_ [private]
Definition at line 498 of file wasm-load-elimination-reducer.h.
Referenced by Run().
predecessor_alias_snapshots_
ZoneVector<AliasSnapshot> v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::predecessor_alias_snapshots_ [private]
Definition at line 514 of file wasm-load-elimination-reducer.h.
Referenced by BeginBlock().
predecessor_memory_snapshots_
ZoneVector<MemorySnapshot> v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::predecessor_memory_snapshots_ [private]
Definition at line 515 of file wasm-load-elimination-reducer.h.
Referenced by BeginBlock().
replacements_
FixedOpIndexSidetable<OpIndex> v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::replacements_ [private]
Definition at line 500 of file wasm-load-elimination-reducer.h.
Referenced by ProcessAnyConvertExtern(), ProcessArrayLength(), ProcessAssertNotNull(), ProcessPhi(), ProcessStringAsWtf16(), ProcessStringPrepareForGetCodeUnit(), ProcessStructGet(), ProcessStructSet(), and Replacement().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-load-elimination-reducer.h