v8::internal::ExternalLogEventListener Class Reference
#include <log.h>
Public Member Functions
ExternalLogEventListener (Isolate *isolate)
~ExternalLogEventListener () override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char *comment) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > source, int line, int column) override
void RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) override
void CallbackEvent (DirectHandle< Name > name, Address entry_point) override
void GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SharedFunctionInfoMoveEvent (Address from, Address to) override
void NativeContextMoveEvent (Address from, Address to) override
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
void CodeMovingGCEvent () override
void CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) override
void CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char *reason) override
void WeakCodeClearEvent () override
void StartListening (v8::CodeEventHandler *code_event_handler)
void StopListening ()
bool is_listening_to_code_events () override
Private Member Functions
void LogExistingCode ()
Private Attributes
bool is_listening_
Isolate * isolate_
v8::CodeEventHandler * code_event_handler_
Additional Inherited Members
Detailed Description
Definition at line 500 of file log.h.
Constructor & Destructor Documentation
ExternalLogEventListener()
v8::internal::ExternalLogEventListener::ExternalLogEventListener (Isolate * isolate) [explicit]
Definition at line 483 of file log.cc.
    : is_listening_(false), isolate_(isolate), code_event_handler_(nullptr) {}
 ExternalLogEventListener()
v8::internal::ExternalLogEventListener::~ExternalLogEventListener () [override]
Definition at line 486 of file log.cc.
                                                    {
  if (is_listening_) {
    StopListening();
  }
}
References is_listening_, and StopListening().
Member Function Documentation
BytecodeMoveEvent()
void v8::internal::ExternalLogEventListener::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 663 of file log.cc.
                                                                           {
  CodeEvent code_event;
  InitializeCodeEvent(isolate_, &code_event, from->GetFirstBytecodeAddress(),
                      to->GetFirstBytecodeAddress(), to->length());
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code_event_handler_, v8::CodeEventHandler::Handle(), v8::internal::anonymous_namespace{log.cc}::InitializeCodeEvent(), and isolate_.
CallbackEvent()
void v8::internal::ExternalLogEventListener::CallbackEvent (DirectHandle< Name > name, Address entry_point) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 525 of file log.h.
{}
CodeCreateEvent() [1/4]
void v8::internal::ExternalLogEventListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char * comment) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 521 of file log.cc.
                                                                    {
  PtrComprCageBase cage_base(isolate_);
  CodeEvent code_event;
  code_event.code_start_address =
      static_cast<uintptr_t>(code->InstructionStart(cage_base));
  code_event.code_size = static_cast<size_t>(code->InstructionSize(cage_base));
  code_event.function_name = isolate_->factory()->empty_string();
  code_event.script_name = isolate_->factory()->empty_string();
  code_event.script_line = 0;
  code_event.script_column = 0;
  code_event.code_type = GetCodeEventTypeForTag(tag);
  code_event.comment = comment;
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code, code_event_handler_, v8::internal::CodeEvent::code_size, v8::internal::CodeEvent::code_start_address, v8::internal::CodeEvent::code_type, v8::internal::CodeEvent::comment, v8::internal::Isolate::factory(), v8::internal::CodeEvent::function_name, v8::internal::anonymous_namespace{log.cc}::GetCodeEventTypeForTag(), v8::CodeEventHandler::Handle(), isolate_, v8::internal::CodeEvent::script_column, v8::internal::CodeEvent::script_line, and v8::internal::CodeEvent::script_name.
CodeCreateEvent() [2/4]
void v8::internal::ExternalLogEventListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 539 of file log.cc.
                                                                        {
  DirectHandle<String> name_string =
      Name::ToFunctionName(isolate_, name).ToHandleChecked();
  PtrComprCageBase cage_base(isolate_);
  CodeEvent code_event;
  code_event.code_start_address =
      static_cast<uintptr_t>(code->InstructionStart(cage_base));
  code_event.code_size = static_cast<size_t>(code->InstructionSize(cage_base));
  code_event.function_name = name_string;
  code_event.script_name = isolate_->factory()->empty_string();
  code_event.script_line = 0;
  code_event.script_column = 0;
  code_event.code_type = GetCodeEventTypeForTag(tag);
  code_event.comment = "";
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code, code_event_handler_, v8::internal::CodeEvent::code_size, v8::internal::CodeEvent::code_start_address, v8::internal::CodeEvent::code_type, v8::internal::CodeEvent::comment, v8::internal::Isolate::factory(), v8::internal::CodeEvent::function_name, v8::internal::anonymous_namespace{log.cc}::GetCodeEventTypeForTag(), v8::CodeEventHandler::Handle(), isolate_, v8::internal::name, v8::internal::CodeEvent::script_column, v8::internal::CodeEvent::script_line, v8::internal::CodeEvent::script_name, and v8::internal::Name::ToFunctionName().
CodeCreateEvent() [3/4]
void v8::internal::ExternalLogEventListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 560 of file log.cc.
                                                                      {
  DirectHandle<String> name_string =
      Name::ToFunctionName(isolate_, name).ToHandleChecked();
  PtrComprCageBase cage_base(isolate_);
  CodeEvent code_event;
  code_event.code_start_address =
      static_cast<uintptr_t>(code->InstructionStart(cage_base));
  code_event.code_size = static_cast<size_t>(code->InstructionSize(cage_base));
  code_event.function_name = name_string;
  code_event.script_name = isolate_->factory()->empty_string();
  code_event.script_line = 0;
  code_event.script_column = 0;
  code_event.code_type = GetCodeEventTypeForTag(tag);
  code_event.comment = "";
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code, code_event_handler_, v8::internal::CodeEvent::code_size, v8::internal::CodeEvent::code_start_address, v8::internal::CodeEvent::code_type, v8::internal::CodeEvent::comment, v8::internal::Isolate::factory(), v8::internal::CodeEvent::function_name, v8::internal::anonymous_namespace{log.cc}::GetCodeEventTypeForTag(), v8::CodeEventHandler::Handle(), isolate_, v8::internal::name, v8::internal::CodeEvent::script_column, v8::internal::CodeEvent::script_line, v8::internal::CodeEvent::script_name, and v8::internal::Name::ToFunctionName().
CodeCreateEvent() [4/4]
void v8::internal::ExternalLogEventListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > source, int line, int column) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 581 of file log.cc.
                          {
  DirectHandle<String> name_string =
      Name::ToFunctionName(isolate_, direct_handle(shared->Name(), isolate_))
          .ToHandleChecked();
  DirectHandle<String> source_string =
      Name::ToFunctionName(isolate_, source).ToHandleChecked();
  PtrComprCageBase cage_base(isolate_);
  CodeEvent code_event;
  code_event.code_start_address =
      static_cast<uintptr_t>(code->InstructionStart(cage_base));
  code_event.code_size = static_cast<size_t>(code->InstructionSize(cage_base));
  code_event.function_name = name_string;
  code_event.script_name = source_string;
  code_event.script_line = line;
  code_event.script_column = column;
  code_event.code_type = GetCodeEventTypeForTag(tag);
  code_event.comment = "";
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code, code_event_handler_, v8::internal::CodeEvent::code_size, v8::internal::CodeEvent::code_start_address, v8::internal::CodeEvent::code_type, v8::internal::CodeEvent::comment, v8::internal::direct_handle(), v8::internal::CodeEvent::function_name, v8::internal::anonymous_namespace{log.cc}::GetCodeEventTypeForTag(), v8::CodeEventHandler::Handle(), isolate_, v8::internal::CodeEvent::script_column, v8::internal::CodeEvent::script_line, v8::internal::CodeEvent::script_name, and v8::internal::Name::ToFunctionName().
CodeDeoptEvent()
void v8::internal::ExternalLogEventListener::CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 539 of file log.h.
                                                   {}
CodeDependencyChangeEvent()
void v8::internal::ExternalLogEventListener::CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char * reason) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 541 of file log.h.
                                                              {}
CodeDisableOptEvent()
void v8::internal::ExternalLogEventListener::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 536 of file log.h.
                                                                             {}
CodeMoveEvent()
void v8::internal::ExternalLogEventListener::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 654 of file log.cc.
                                                                           {
  CodeEvent code_event;
  InitializeCodeEvent(isolate_, &code_event, from->instruction_start(),
                      to->instruction_start(),
                      to->code(kAcquireLoad)->instruction_size());
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code_event_handler_, v8::CodeEventHandler::Handle(), v8::internal::anonymous_namespace{log.cc}::InitializeCodeEvent(), isolate_, and v8::kAcquireLoad.
CodeMovingGCEvent()
void v8::internal::ExternalLogEventListener::CodeMovingGCEvent () [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 538 of file log.h.
{}
GetterCallbackEvent()
void v8::internal::ExternalLogEventListener::GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 526 of file log.h.
                                                         {}
is_listening_to_code_events()
bool v8::internal::ExternalLogEventListener::is_listening_to_code_events () [inline], [override], [virtual]
Reimplemented from v8::internal::LogEventListener.
Definition at line 549 of file log.h.
{ return true; }
LogExistingCode()
void v8::internal::ExternalLogEventListener::LogExistingCode () [private]
Definition at line 492 of file log.cc.
                                               {
  HandleScope scope(isolate_);
  ExistingCodeLogger logger(isolate_, this);
  logger.LogBuiltins();
  logger.LogCodeObjects();
  logger.LogCompiledFunctions();
}
References isolate_, v8::internal::ExistingCodeLogger::LogBuiltins(), v8::internal::ExistingCodeLogger::LogCodeObjects(), and v8::internal::ExistingCodeLogger::LogCompiledFunctions().
Referenced by StartListening().
NativeContextMoveEvent()
void v8::internal::ExternalLogEventListener::NativeContextMoveEvent (Address from, Address to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 531 of file log.h.
{}
RegExpCodeCreateEvent()
void v8::internal::ExternalLogEventListener::RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 616 of file log.cc.
                       {
  PtrComprCageBase cage_base(isolate_);
  CodeEvent code_event;
  code_event.code_start_address =
      static_cast<uintptr_t>(code->InstructionStart(cage_base));
  code_event.code_size = static_cast<size_t>(code->InstructionSize(cage_base));
  code_event.function_name = source;
  code_event.script_name = isolate_->factory()->empty_string();
  code_event.script_line = 0;
  code_event.script_column = 0;
  code_event.code_type =
      GetCodeEventTypeForTag(LogEventListener::CodeTag::kRegExp);
  code_event.comment = "";
  code_event_handler_->Handle(reinterpret_cast<v8::CodeEvent*>(&code_event));
}
References code, code_event_handler_, v8::internal::CodeEvent::code_size, v8::internal::CodeEvent::code_start_address, v8::internal::CodeEvent::code_type, v8::internal::CodeEvent::comment, v8::internal::Isolate::factory(), v8::internal::CodeEvent::function_name, v8::internal::anonymous_namespace{log.cc}::GetCodeEventTypeForTag(), v8::CodeEventHandler::Handle(), isolate_, v8::internal::CodeEvent::script_column, v8::internal::CodeEvent::script_line, and v8::internal::CodeEvent::script_name.
SetterCallbackEvent()
void v8::internal::ExternalLogEventListener::SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 528 of file log.h.
                                                         {}
SharedFunctionInfoMoveEvent()
void v8::internal::ExternalLogEventListener::SharedFunctionInfoMoveEvent (Address from, Address to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 530 of file log.h.
{}
StartListening()
void v8::internal::ExternalLogEventListener::StartListening (v8::CodeEventHandler * code_event_handler)
Definition at line 500 of file log.cc.
                                          {
  if (is_listening_ || code_event_handler == nullptr) {
    return;
  }
  code_event_handler_ = code_event_handler;
  is_listening_ = isolate_->logger()->AddListener(this);
  if (is_listening_) {
    LogExistingCode();
  }
}
References v8::internal::Logger::AddListener(), code_event_handler_, is_listening_, isolate_, LogExistingCode(), and v8::internal::Isolate::logger().
StopListening()
void v8::internal::ExternalLogEventListener::StopListening ()
Definition at line 512 of file log.cc.
                                             {
  if (!is_listening_) {
    return;
  }
  isolate_->logger()->RemoveListener(this);
  is_listening_ = false;
}
References is_listening_, isolate_, v8::internal::Isolate::logger(), and v8::internal::Logger::RemoveListener().
Referenced by ~ExternalLogEventListener().
WeakCodeClearEvent()
void v8::internal::ExternalLogEventListener::WeakCodeClearEvent () [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 544 of file log.h.
{}
Member Data Documentation
code_event_handler_
v8::CodeEventHandler* v8::internal::ExternalLogEventListener::code_event_handler_ [private]
Definition at line 556 of file log.h.
Referenced by BytecodeMoveEvent(), CodeCreateEvent(), CodeMoveEvent(), RegExpCodeCreateEvent(), and StartListening().
is_listening_
bool v8::internal::ExternalLogEventListener::is_listening_ [private]
Definition at line 554 of file log.h.
Referenced by StartListening(), StopListening(), and ~ExternalLogEventListener().
isolate_
Isolate* v8::internal::ExternalLogEventListener::isolate_ [private]
Definition at line 555 of file log.h.
Referenced by BytecodeMoveEvent(), CodeCreateEvent(), CodeMoveEvent(), LogExistingCode(), RegExpCodeCreateEvent(), StartListening(), and StopListening().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/log.h
/mnt/V8SourceCode/src/logging/log.cc