v8::internal::interpreter::ConstantArrayBuilder Class Reference
#include <constant-array-builder.h>
Classes
struct ConstantArraySlice
class Entry
Public Member Functions
ConstantArrayBuilder (Zone *zone)
template<typename IsolateT >
Handle< TrustedFixedArray > ToFixedArray (IsolateT *isolate)
template<typename IsolateT >
MaybeHandle< Object > At (size_t index, IsolateT *isolate) const
size_t size () const
size_t Insert (Tagged< Smi > smi)
size_t Insert (double number)
size_t Insert (const AstRawString *raw_string)
size_t Insert (const AstConsString *cons_string)
size_t Insert (AstBigInt bigint)
size_t Insert (const Scope *scope)
size_t InsertDeferred ()
size_t InsertJumpTable (size_t size)
void SetDeferredAt (size_t index, Handle< Object > object)
void SetJumpTableSmi (size_t index, Tagged< Smi > smi)
OperandSize CreateReservedEntry (OperandSize minimum_operand_size=OperandSize::kNone)
size_t CommitReservedEntry (OperandSize operand_size, Tagged< Smi > value)
void DiscardReservedEntry (OperandSize operand_size)
Static Public Attributes
static const size_t k8BitCapacity = 1u << kBitsPerByte
static const size_t k16BitCapacity = (1u << 2 * kBitsPerByte) - k8BitCapacity
static const size_t k32BitCapacity
Private Types
using index_t = uint32_t
Private Member Functions
index_t AllocateIndex (Entry constant_entry)
index_t AllocateIndexArray (Entry constant_entry, size_t size)
index_t AllocateReservedEntry (Tagged< Smi > value)
ConstantArraySlice * IndexToSlice (size_t index) const
ConstantArraySlice * OperandSizeToSlice (OperandSize operand_size) const
Private Attributes
ConstantArraySlice * idx_slice_ [3]
base::TemplateHashMapImpl< intptr_t, index_t, base::KeyEqualityMatcher< intptr_t >, ZoneAllocationPolicy > constants_map_
ZoneMap< Tagged< Smi >, index_t > smi_map_
ZoneVector< std::pair< Tagged< Smi >, index_t > > smi_pairs_
ZoneMap< double, index_t > heap_number_map_
Detailed Description
Definition at line 39 of file constant-array-builder.h.
Member Typedef Documentation
index_t
using v8::internal::interpreter::ConstantArrayBuilder::index_t = uint32_t [private]
Definition at line 111 of file constant-array-builder.h.
Constructor & Destructor Documentation
ConstantArrayBuilder()
v8::internal::interpreter::ConstantArrayBuilder::ConstantArrayBuilder (Zone * zone) [explicit]
Definition at line 137 of file constant-array-builder.cc.
    : constants_map_(16, base::KeyEqualityMatcher<intptr_t>(),
                     ZoneAllocationPolicy(zone)),
      smi_map_(zone),
      smi_pairs_(zone),
      heap_number_map_(zone) {
  idx_slice_[0] =
      zone->New<ConstantArraySlice>(zone, 0, k8BitCapacity, OperandSize::kByte);
  idx_slice_[1] = zone->New<ConstantArraySlice>(
      zone, k8BitCapacity, k16BitCapacity, OperandSize::kShort);
  idx_slice_[2] = zone->New<ConstantArraySlice>(
      zone, k8BitCapacity + k16BitCapacity, k32BitCapacity, OperandSize::kQuad);
}
References idx_slice_, k16BitCapacity, k32BitCapacity, k8BitCapacity, v8::internal::interpreter::kByte, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, and v8::internal::Zone::New().
Member Function Documentation
AllocateIndex()
ConstantArrayBuilder::index_t v8::internal::interpreter::ConstantArrayBuilder::AllocateIndex (ConstantArrayBuilder::Entry entry) [private]
Definition at line 294 of file constant-array-builder.cc.
                                     {
  return AllocateIndexArray(entry, 1);
}
References AllocateIndexArray().
Referenced by AllocateReservedEntry(), Insert(), and InsertDeferred().
AllocateIndexArray()
ConstantArrayBuilder::index_t v8::internal::interpreter::ConstantArrayBuilder::AllocateIndexArray (ConstantArrayBuilder::Entry entry, size_t size) [private]
Definition at line 299 of file constant-array-builder.cc.
                                                   {
  for (size_t i = 0; i < arraysize(idx_slice_); ++i) {
    if (idx_slice_[i]->available() >= count) {
      return static_cast<index_t>(idx_slice_[i]->Allocate(entry, count));
    }
  }
  UNREACHABLE();
}
References v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Allocate(), arraysize, available(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, idx_slice_, and v8::internal::UNREACHABLE().
Referenced by AllocateIndex(), and InsertJumpTable().
AllocateReservedEntry()
ConstantArrayBuilder::index_t v8::internal::interpreter::ConstantArrayBuilder::AllocateReservedEntry (Tagged< Smi > value) [private]
Definition at line 363 of file constant-array-builder.cc.
                       {
  index_t index = static_cast<index_t>(AllocateIndex(Entry(value)));
  smi_map_[value] = index;
  return index;
}
References AllocateIndex(), v8::internal::index, smi_map_, and v8::internal::value.
Referenced by CommitReservedEntry().
At()
template<typename IsolateT >
MaybeHandle< Object > v8::internal::interpreter::ConstantArrayBuilder::At (size_t index, IsolateT * isolate) const
Definition at line 173 of file constant-array-builder.cc.
                                                                      {
  const ConstantArraySlice* slice = IndexToSlice(index);
  DCHECK_LT(index, slice->capacity());
  if (index < slice->start_index() + slice->size()) {
    const Entry& entry = slice->At(index);
    if (!entry.IsDeferred()) return entry.ToHandle(isolate);
  }
  return MaybeHandle<Object>();
}
References v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::At(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::capacity(), DCHECK_LT, v8::internal::index, IndexToSlice(), v8::internal::interpreter::ConstantArrayBuilder::Entry::IsDeferred(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::size(), and v8::internal::interpreter::ConstantArrayBuilder::Entry::ToHandle().
CommitReservedEntry()
size_t v8::internal::interpreter::ConstantArrayBuilder::CommitReservedEntry (OperandSize operand_size, Tagged< Smi > value)
Definition at line 370 of file constant-array-builder.cc.
                                                                    {
  DiscardReservedEntry(operand_size);
  size_t index;
  auto entry = smi_map_.find(value);
  if (entry == smi_map_.end()) {
    index = AllocateReservedEntry(value);
  } else {
    ConstantArraySlice* slice = OperandSizeToSlice(operand_size);
    index = entry->second;
    if (index > slice->max_index()) {
      // The object is already in the constant array, but may have an
      // index too big for the reserved operand_size. So, duplicate
      // entry with the smaller operand size.
      index = AllocateReservedEntry(value);
    }
    DCHECK_LE(index, slice->max_index());
  }
  return index;
}
References AllocateReservedEntry(), DCHECK_LE, DiscardReservedEntry(), v8::internal::index, v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::max_index(), OperandSizeToSlice(), smi_map_, and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), and v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand().
CreateReservedEntry()
OperandSize v8::internal::interpreter::ConstantArrayBuilder::CreateReservedEntry (OperandSize minimum_operand_size = OperandSize::kNone)
Definition at line 351 of file constant-array-builder.cc.
                                      {
  for (size_t i = 0; i < arraysize(idx_slice_); ++i) {
    if (idx_slice_[i]->available() > 0 &&
        idx_slice_[i]->operand_size() >= minimum_operand_size) {
      idx_slice_[i]->Reserve();
      return idx_slice_[i]->operand_size();
    }
  }
  UNREACHABLE();
}
References arraysize, available(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, idx_slice_, v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::operand_size(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Reserve(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJump().
DiscardReservedEntry()
void v8::internal::interpreter::ConstantArrayBuilder::DiscardReservedEntry (OperandSize operand_size)
Definition at line 391 of file constant-array-builder.cc.
                                                                        {
  OperandSizeToSlice(operand_size)->Unreserve();
}
References OperandSizeToSlice(), and v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::Unreserve().
Referenced by CommitReservedEntry(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(), and v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand().
IndexToSlice()
ConstantArrayBuilder::ConstantArraySlice * v8::internal::interpreter::ConstantArrayBuilder::IndexToSlice (size_t index) const [private]
Definition at line 162 of file constant-array-builder.cc.
                        {
  for (ConstantArraySlice* slice : idx_slice_) {
    if (index <= slice->max_index()) {
      return slice;
    }
  }
  UNREACHABLE();
}
References idx_slice_, and v8::internal::UNREACHABLE().
Referenced by At(), SetDeferredAt(), and SetJumpTableSmi().
Insert() [1/6]
size_t v8::internal::interpreter::ConstantArrayBuilder::Insert (AstBigInt bigint)
Definition at line 268 of file constant-array-builder.cc.
                                                    {
  return constants_map_
      .LookupOrInsert(reinterpret_cast<intptr_t>(bigint.c_str()),
                      static_cast<uint32_t>(base::hash_value(bigint.c_str())),
                      [&]() { return AllocateIndex(Entry(bigint)); })
      ->value;
}
References v8::internal::AstBigInt::c_str(), constants_map_, and v8::base::hash_value().
Insert() [2/6]
size_t v8::internal::interpreter::ConstantArrayBuilder::Insert (const AstConsString * cons_string)
Definition at line 259 of file constant-array-builder.cc.
                                                                    {
  const AstRawString* last = cons_string->last();
  uint32_t hash = last == nullptr ? 0 : last->Hash();
  return constants_map_
      .LookupOrInsert(reinterpret_cast<intptr_t>(cons_string), hash,
                      [&]() { return AllocateIndex(Entry(cons_string)); })
      ->value;
}
References AllocateIndex(), constants_map_, v8::internal::AstRawString::Hash(), v8::internal::AstConsString::last(), and v8::internal::value.
Insert() [3/6]
size_t v8::internal::interpreter::ConstantArrayBuilder::Insert (const AstRawString * raw_string)
Definition at line 251 of file constant-array-builder.cc.
                                                                  {
  return constants_map_
      .LookupOrInsert(reinterpret_cast<intptr_t>(raw_string),
                      raw_string->Hash(),
                      [&]() { return AllocateIndex(Entry(raw_string)); })
      ->value;
}
References constants_map_, and v8::internal::AstRawString::Hash().
Insert() [4/6]
size_t v8::internal::interpreter::ConstantArrayBuilder::Insert (const Scope * scope)
Definition at line 276 of file constant-array-builder.cc.
                                                      {
  return constants_map_
      .LookupOrInsert(reinterpret_cast<intptr_t>(scope),
                      static_cast<uint32_t>(base::hash_value(scope)),
                      [&]() { return AllocateIndex(Entry(scope)); })
      ->value;
}
References AllocateIndex(), constants_map_, v8::base::hash_value(), and v8::internal::value.
Insert() [5/6]
size_t v8::internal::interpreter::ConstantArrayBuilder::Insert (double number)
Definition at line 240 of file constant-array-builder.cc.
                                                 {
  if (std::isnan(number)) return InsertNaN();
  auto entry = heap_number_map_.find(number);
  if (entry == heap_number_map_.end()) {
    index_t index = static_cast<index_t>(AllocateIndex(Entry(number)));
    heap_number_map_[number] = index;
    return index;
  }
  return entry->second;
}
References AllocateIndex(), heap_number_map_, and v8::internal::index.
Insert() [6/6]
size_t v8::internal::interpreter::ConstantArrayBuilder::Insert (Tagged< Smi > smi)
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::GetConstantPoolEntry().
InsertDeferred()
size_t v8::internal::interpreter::ConstantArrayBuilder::InsertDeferred ()
Definition at line 329 of file constant-array-builder.cc.
                                            {
  return AllocateIndex(Entry::Deferred());
}
References AllocateIndex(), and v8::internal::interpreter::ConstantArrayBuilder::Entry::Deferred().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AllocateDeferredConstantPoolEntry().
InsertJumpTable()
size_t v8::internal::interpreter::ConstantArrayBuilder::InsertJumpTable (size_t size)
Definition at line 333 of file constant-array-builder.cc.
                                                        {
  return AllocateIndexArray(Entry::UninitializedJumpTableSmi(), size);
}
References AllocateIndexArray(), size(), and v8::internal::interpreter::ConstantArrayBuilder::Entry::UninitializedJumpTableSmi().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::AllocateJumpTable().
OperandSizeToSlice()
ConstantArrayBuilder::ConstantArraySlice * v8::internal::interpreter::ConstantArrayBuilder::OperandSizeToSlice (OperandSize operand_size) const [private]
Definition at line 310 of file constant-array-builder.cc.
                                                                       {
  ConstantArraySlice* slice = nullptr;
  switch (operand_size) {
    case OperandSize::kNone:
      UNREACHABLE();
    case OperandSize::kByte:
      slice = idx_slice_[0];
      break;
    case OperandSize::kShort:
      slice = idx_slice_[1];
      break;
    case OperandSize::kQuad:
      slice = idx_slice_[2];
      break;
  }
  DCHECK(slice->operand_size() == operand_size);
  return slice;
}
References v8::internal::DCHECK(), idx_slice_, v8::internal::interpreter::kByte, v8::internal::interpreter::kNone, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::operand_size(), and v8::internal::UNREACHABLE().
Referenced by CommitReservedEntry(), and DiscardReservedEntry().
SetDeferredAt()
void v8::internal::interpreter::ConstantArrayBuilder::SetDeferredAt (size_t index, Handle< Object > object)
Definition at line 337 of file constant-array-builder.cc.
                                                                            {
  ConstantArraySlice* slice = IndexToSlice(index);
  return slice->At(index).SetDeferred(object);
}
References v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::At(), v8::internal::index, IndexToSlice(), and v8::internal::interpreter::ConstantArrayBuilder::Entry::SetDeferred().
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::SetDeferredConstantPoolEntry().
SetJumpTableSmi()
void v8::internal::interpreter::ConstantArrayBuilder::SetJumpTableSmi (size_t index, Tagged< Smi > smi)
Definition at line 342 of file constant-array-builder.cc.
                                                                        {
  ConstantArraySlice* slice = IndexToSlice(index);
  // Allow others to reuse these Smis, but insert using emplace to avoid
  // overwriting existing values in the Smi map (which may have a smaller
  // operand size).
  smi_map_.emplace(smi, static_cast<index_t>(index));
  return slice->At(index).SetJumpTableSmi(smi);
}
References v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::At(), v8::internal::index, IndexToSlice(), v8::internal::interpreter::ConstantArrayBuilder::Entry::SetJumpTableSmi(), and smi_map_.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::BindJumpTableEntry().
size()
size_t v8::internal::interpreter::ConstantArrayBuilder::size () const
Definition at line 151 of file constant-array-builder.cc.
                                        {
  size_t i = arraysize(idx_slice_);
  while (i > 0) {
    ConstantArraySlice* slice = idx_slice_[--i];
    if (slice->size() > 0) {
      return slice->start_index() + slice->size();
    }
  }
  return idx_slice_[0]->size();
}
References arraysize, v8::internal::anonymous_namespace{json-stringifier.cc}::i, idx_slice_, v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::size(), and v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::start_index().
Referenced by v8::internal::interpreter::ConstantArrayBuilder::ConstantArraySlice::At(), and InsertJumpTable().
ToFixedArray()
template<typename IsolateT >
Handle<TrustedFixedArray> v8::internal::interpreter::ConstantArrayBuilder::ToFixedArray (IsolateT * isolate)
Referenced by v8::internal::interpreter::BytecodeArrayWriter::ToBytecodeArray().
Member Data Documentation
constants_map_
base::TemplateHashMapImpl<intptr_t, index_t, base::KeyEqualityMatcher<intptr_t>, ZoneAllocationPolicy> v8::internal::interpreter::ConstantArrayBuilder::constants_map_ [private]
Definition at line 242 of file constant-array-builder.h.
Referenced by Insert().
heap_number_map_
ZoneMap<double, index_t> v8::internal::interpreter::ConstantArrayBuilder::heap_number_map_ [private]
Definition at line 245 of file constant-array-builder.h.
Referenced by Insert().
idx_slice_
ConstantArraySlice* v8::internal::interpreter::ConstantArrayBuilder::idx_slice_[3] [private]
Definition at line 238 of file constant-array-builder.h.
Referenced by AllocateIndexArray(), ConstantArrayBuilder(), CreateReservedEntry(), IndexToSlice(), OperandSizeToSlice(), and size().
k16BitCapacity
STATIC_CONST_MEMBER_DEFINITION const size_t v8::internal::interpreter::ConstantArrayBuilder::k16BitCapacity = (1u << 2 * kBitsPerByte) - k8BitCapacity [static]
Definition at line 45 of file constant-array-builder.h.
Referenced by ConstantArrayBuilder().
k32BitCapacity
STATIC_CONST_MEMBER_DEFINITION const size_t v8::internal::interpreter::ConstantArrayBuilder::k32BitCapacity [static]
Initial value:
=
      kMaxUInt32 - k16BitCapacity - k8BitCapacity + 1
Definition at line 48 of file constant-array-builder.h.
Referenced by ConstantArrayBuilder().
k8BitCapacity
STATIC_CONST_MEMBER_DEFINITION const size_t v8::internal::interpreter::ConstantArrayBuilder::k8BitCapacity = 1u << kBitsPerByte [static]
Definition at line 42 of file constant-array-builder.h.
Referenced by ConstantArrayBuilder().
smi_map_
ZoneMap<Tagged<Smi>, index_t> v8::internal::interpreter::ConstantArrayBuilder::smi_map_ [private]
Definition at line 243 of file constant-array-builder.h.
Referenced by AllocateReservedEntry(), CommitReservedEntry(), and SetJumpTableSmi().
smi_pairs_
ZoneVector<std::pair<Tagged<Smi>, index_t> > v8::internal::interpreter::ConstantArrayBuilder::smi_pairs_ [private]
Definition at line 244 of file constant-array-builder.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/constant-array-builder.h
/mnt/V8SourceCode/src/interpreter/constant-array-builder.cc