v8::internal::FinalizationRegistryCleanupTask Class Reference
#include <finalization-registry-cleanup-task.h>
Public Member Functions
FinalizationRegistryCleanupTask (Heap *heap)
~FinalizationRegistryCleanupTask () override=default
FinalizationRegistryCleanupTask (const FinalizationRegistryCleanupTask &)=delete
void operator= (const FinalizationRegistryCleanupTask &)=delete
Private Member Functions
void RunInternal () override
void SlowAssertNoActiveJavaScript ()
Private Attributes
Heap * heap_
Additional Inherited Members
Detailed Description
Definition at line 17 of file finalization-registry-cleanup-task.h.
Constructor & Destructor Documentation
FinalizationRegistryCleanupTask() [1/2]
v8::internal::FinalizationRegistryCleanupTask::FinalizationRegistryCleanupTask (Heap * heap) [explicit]
Definition at line 18 of file finalization-registry-cleanup-task.cc.
    : CancelableTask(heap->isolate()), heap_(heap) {}
 FinalizationRegistryCleanupTask()
v8::internal::FinalizationRegistryCleanupTask::~FinalizationRegistryCleanupTask () [override], [default]
FinalizationRegistryCleanupTask() [2/2]
v8::internal::FinalizationRegistryCleanupTask::FinalizationRegistryCleanupTask (const FinalizationRegistryCleanupTask &) [delete]
Member Function Documentation
operator=()
void v8::internal::FinalizationRegistryCleanupTask::operator= (const FinalizationRegistryCleanupTask &) [delete]
RunInternal()
void v8::internal::FinalizationRegistryCleanupTask::RunInternal () [override], [private], [virtual]
Implements v8::internal::CancelableTask.
Definition at line 38 of file finalization-registry-cleanup-task.cc.
                                                  {
  Isolate* isolate = heap_->isolate();
  SlowAssertNoActiveJavaScript();
  TRACE_EVENT_CALL_STATS_SCOPED(isolate, "v8",
                                "V8.FinalizationRegistryCleanupTask");
  // First clear that the task is posted in case of early returns below.
  heap_->set_is_finalization_registry_cleanup_task_posted(false);
  HandleScope handle_scope(isolate);
  DirectHandle<JSFinalizationRegistry> finalization_registry;
  // There could be no dirty FinalizationRegistries. When a context is disposed
  // by the embedder, its FinalizationRegistries are removed from the dirty
  // list.
  if (!heap_->DequeueDirtyJSFinalizationRegistry().ToHandle(
          &finalization_registry)) {
    return;
  }
  finalization_registry->set_scheduled_for_cleanup(false);
  // Since FinalizationRegistry cleanup callbacks are scheduled by V8, enter the
  // FinalizationRegistry's context.
  DirectHandle<NativeContext> native_context(
      finalization_registry->native_context(), isolate);
  v8::Context::Scope context_scope(v8::Utils::ToLocal(native_context));
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  v8::TryCatch catcher(v8_isolate);
  catcher.SetVerbose(true);
  std::unique_ptr<MicrotasksScope> microtasks_scope;
  MicrotaskQueue* microtask_queue =
      finalization_registry->native_context()->microtask_queue();
  if (!microtask_queue) microtask_queue = isolate->default_microtask_queue();
  if (microtask_queue &&
      microtask_queue->microtasks_policy() == v8::MicrotasksPolicy::kScoped) {
    // InvokeFinalizationRegistryCleanupFromTask will call into V8 API methods,
    // so we need a valid microtasks scope on the stack to avoid running into
    // the CallDepthScope check.
    microtasks_scope.reset(new v8::MicrotasksScope(
        v8_isolate, microtask_queue, v8::MicrotasksScope::kDoNotRunMicrotasks));
  }
  // Exceptions are reported via the message handler. This is ensured by the
  // verbose TryCatch.
  //
  // Cleanup is interrupted if there is an exception. The HTML spec calls for a
  // microtask checkpoint after each cleanup task, so the task should return
  // after an exception so the host can perform a microtask checkpoint. In case
  // of exception, check if the FinalizationRegistry still needs cleanup
  // and should be requeued.
  //
  // TODO(syg): Implement better scheduling for finalizers.
  InvokeFinalizationRegistryCleanupFromTask(native_context,
                                            finalization_registry);
  if (finalization_registry->NeedsCleanup() &&
      !finalization_registry->scheduled_for_cleanup()) {
    auto nop = [](Tagged<HeapObject>, ObjectSlot, Tagged<Object>) {};
    heap_->EnqueueDirtyJSFinalizationRegistry(*finalization_registry, nop);
  }
  // Repost if there are remaining dirty FinalizationRegistries.
  heap_->PostFinalizationRegistryCleanupTaskIfNeeded();
}
References v8::internal::Heap::DequeueDirtyJSFinalizationRegistry(), v8::internal::Heap::EnqueueDirtyJSFinalizationRegistry(), heap_, v8::internal::InvokeFinalizationRegistryCleanupFromTask(), v8::internal::Heap::isolate(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::kScoped, v8::internal::MicrotaskQueue::microtasks_policy(), v8::internal::native_context, v8::internal::Heap::PostFinalizationRegistryCleanupTaskIfNeeded(), v8::internal::Heap::set_is_finalization_registry_cleanup_task_posted(), v8::TryCatch::SetVerbose(), SlowAssertNoActiveJavaScript(), and TRACE_EVENT_CALL_STATS_SCOPED.
SlowAssertNoActiveJavaScript()
void v8::internal::FinalizationRegistryCleanupTask::SlowAssertNoActiveJavaScript () [private]
Definition at line 21 of file finalization-registry-cleanup-task.cc.
                                                                   {
#ifdef ENABLE_SLOW_DCHECKS
  class NoActiveJavaScript : public ThreadVisitor {
   public:
    void VisitThread(Isolate* isolate, ThreadLocalTop* top) override {
      for (StackFrameIterator it(isolate, top); !it.done(); it.Advance()) {
        DCHECK(!it.frame()->is_javascript());
      }
    }
  };
  NoActiveJavaScript no_active_js_visitor;
  Isolate* isolate = heap_->isolate();
  no_active_js_visitor.VisitThread(isolate, isolate->thread_local_top());
  isolate->thread_manager()->IterateArchivedThreads(&no_active_js_visitor);
#endif // ENABLE_SLOW_DCHECKS
}
References v8::internal::DCHECK(), v8::internal::StackFrameIteratorBase::done(), heap_, v8::internal::Heap::isolate(), v8::internal::ThreadManager::IterateArchivedThreads(), v8::internal::Isolate::thread_local_top(), and v8::internal::Isolate::thread_manager().
Referenced by RunInternal().
Member Data Documentation
heap_
Heap* v8::internal::FinalizationRegistryCleanupTask::heap_ [private]
Definition at line 29 of file finalization-registry-cleanup-task.h.
Referenced by RunInternal(), and SlowAssertNoActiveJavaScript().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/finalization-registry-cleanup-task.h
/mnt/V8SourceCode/src/heap/finalization-registry-cleanup-task.cc