v8::internal::compiler::X64OperandGenerator Class Reference
Public Member Functions
X64OperandGenerator (InstructionSelector *selector)
bool CanBeImmediate (OpIndex node)
int32_t GetImmediateIntegerValue (OpIndex node)
bool CanBeMemoryOperand (InstructionCode opcode, OpIndex node, OpIndex input, int effect_level)
bool IsZeroIntConstant (OpIndex node) const
AddressingMode GenerateMemoryOperandInputs (OptionalOpIndex index, int scale_exponent, OpIndex base, int64_t displacement, DisplacementMode displacement_mode, InstructionOperand inputs[], size_t *input_count, RegisterUseKind reg_kind=RegisterUseKind::kUseRegister)
AddressingMode GetEffectiveAddressMemoryOperand (OpIndex operand, InstructionOperand inputs[], size_t *input_count, RegisterUseKind reg_kind=RegisterUseKind::kUseRegister)
InstructionOperand GetEffectiveIndexOperand (OpIndex index, AddressingMode *mode)
bool CanBeBetterLeftOperand (OpIndex node) const
Additional Inherited Members
Detailed Description
Definition at line 534 of file instruction-selector-x64.cc.
Constructor & Destructor Documentation
X64OperandGenerator()
v8::internal::compiler::X64OperandGenerator::X64OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 536 of file instruction-selector-x64.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeBetterLeftOperand()
bool v8::internal::compiler::X64OperandGenerator::CanBeBetterLeftOperand (OpIndex node) const [inline]
Definition at line 735 of file instruction-selector-x64.cc.
                                                  {
    return !selector()->IsReallyLive(node);
  }
Referenced by v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul().
CanBeImmediate()
bool v8::internal::compiler::X64OperandGenerator::CanBeImmediate (OpIndex node) [inline]
Definition at line 539 of file instruction-selector-x64.cc.
                                    {
    return compiler::CanBeImmediate(this->selector(), node);
  }
References v8::internal::compiler::CanBeImmediate().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare().
CanBeMemoryOperand()
bool v8::internal::compiler::X64OperandGenerator::CanBeMemoryOperand (InstructionCode opcode, OpIndex node, OpIndex input, int effect_level) [inline]
Definition at line 547 of file instruction-selector-x64.cc.
                                            {
    if (!selector()->IsLoadOrLoadImmutable(input)) return false;
    if (!selector()->CanCover(node, input)) return false;
    if (effect_level != selector()->GetEffectLevel(input)) {
      return false;
    }
    MachineRepresentation rep =
        selector()->load_view(input).loaded_rep().representation();
    switch (opcode) {
      case kX64And:
      case kX64Or:
      case kX64Xor:
      case kX64Add:
      case kX64Sub:
      case kX64Push:
      case kX64Cmp:
      case kX64Test:
        // When pointer compression is enabled 64-bit memory operands can't be
        // used for tagged values.
        return rep == MachineRepresentation::kWord64 ||
               (!COMPRESS_POINTERS_BOOL && IsAnyTagged(rep));
      case kX64And32:
      case kX64Or32:
      case kX64Xor32:
      case kX64Add32:
      case kX64Sub32:
      case kX64Cmp32:
      case kX64Test32:
        // When pointer compression is enabled 32-bit memory operands can be
        // used for tagged values.
        return rep == MachineRepresentation::kWord32 ||
               (COMPRESS_POINTERS_BOOL &&
                (IsAnyTagged(rep) || IsAnyCompressed(rep)));
      case kAVXFloat64Add:
      case kAVXFloat64Sub:
      case kAVXFloat64Mul:
        DCHECK_EQ(MachineRepresentation::kFloat64, rep);
        return true;
      case kAVXFloat32Add:
      case kAVXFloat32Sub:
      case kAVXFloat32Mul:
        DCHECK_EQ(MachineRepresentation::kFloat32, rep);
        return true;
      case kX64Cmp16:
      case kX64Test16:
        return rep == MachineRepresentation::kWord16;
      case kX64Cmp8:
      case kX64Test8:
        return rep == MachineRepresentation::kWord8;
      default:
        break;
    }
    return false;
  }
References COMPRESS_POINTERS_BOOL, DCHECK_EQ, v8::internal::IsAnyCompressed(), v8::internal::IsAnyTagged(), v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, and v8::internal::kWord8.
Referenced by v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare().
GenerateMemoryOperandInputs()
AddressingMode v8::internal::compiler::X64OperandGenerator::GenerateMemoryOperandInputs (OptionalOpIndex index, int scale_exponent, OpIndex base, int64_t displacement, DisplacementMode displacement_mode, InstructionOperand inputs[], size_t * input_count, RegisterUseKind reg_kind = RegisterUseKind::kUseRegister) [inline]
Definition at line 619 of file instruction-selector-x64.cc.
                                                              {
    AddressingMode mode = kMode_MRI;
    OpIndex base_before_folding = base;
    bool fold_base_into_displacement = false;
    int64_t fold_value = 0;
    if (base.valid() && (index.valid() || displacement != 0)) {
      if (CanBeImmediate(base) && index.valid() &&
          ValueFitsIntoImmediate(displacement)) {
        fold_value = GetImmediateIntegerValue(base);
        if (displacement_mode == kNegativeDisplacement) {
          fold_value -= displacement;
        } else {
          fold_value += displacement;
        }
        if (V8_UNLIKELY(fold_value == 0)) {
          base = OpIndex{};
          displacement = 0;
        } else if (ValueFitsIntoImmediate(fold_value)) {
          base = OpIndex{};
          fold_base_into_displacement = true;
        }
      } else if (IsZeroIntConstant(base)) {
        base = OpIndex{};
      }
    }
    if (base.valid()) {
      inputs[(*input_count)++] = UseRegister(base, reg_kind);
      if (index.valid()) {
        DCHECK(scale_exponent >= 0 && scale_exponent <= 3);
        inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
        if (displacement != 0) {
          inputs[(*input_count)++] = UseImmediate64(
              displacement_mode == kNegativeDisplacement ? -displacement
                                                         : displacement);
          static const AddressingMode kMRnI_modes[] = {kMode_MR1I, kMode_MR2I,
                                                       kMode_MR4I, kMode_MR8I};
          mode = kMRnI_modes[scale_exponent];
        } else {
          static const AddressingMode kMRn_modes[] = {kMode_MR1, kMode_MR2,
                                                      kMode_MR4, kMode_MR8};
          mode = kMRn_modes[scale_exponent];
        }
      } else {
        if (displacement == 0) {
          mode = kMode_MR;
        } else {
          inputs[(*input_count)++] = UseImmediate64(
              displacement_mode == kNegativeDisplacement ? -displacement
                                                         : displacement);
          mode = kMode_MRI;
        }
      }
    } else {
      DCHECK(scale_exponent >= 0 && scale_exponent <= 3);
      if (fold_base_into_displacement) {
        DCHECK(!base.valid());
        DCHECK(index.valid());
        inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
        inputs[(*input_count)++] = UseImmediate(static_cast<int>(fold_value));
        static const AddressingMode kMnI_modes[] = {kMode_MRI, kMode_M2I,
                                                    kMode_M4I, kMode_M8I};
        mode = kMnI_modes[scale_exponent];
      } else if (displacement != 0) {
        if (!index.valid()) {
          // This seems to only occur in (0 + k) cases, but we don't have an
          // addressing mode for a simple constant, so we use the base in a
          // register for kMode_MRI.
          CHECK(IsZeroIntConstant(base_before_folding));
          inputs[(*input_count)++] = UseRegister(base_before_folding, reg_kind);
          inputs[(*input_count)++] = UseImmediate64(
              displacement_mode == kNegativeDisplacement ? -displacement
                                                         : displacement);
          mode = kMode_MRI;
        } else {
          inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
          inputs[(*input_count)++] = UseImmediate64(
              displacement_mode == kNegativeDisplacement ? -displacement
                                                         : displacement);
          static const AddressingMode kMnI_modes[] = {kMode_MRI, kMode_M2I,
                                                      kMode_M4I, kMode_M8I};
          mode = kMnI_modes[scale_exponent];
        }
      } else {
        DCHECK(index.valid());
        inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
        static const AddressingMode kMn_modes[] = {kMode_MR, kMode_MR1,
                                                   kMode_M4, kMode_M8};
        mode = kMn_modes[scale_exponent];
        if (mode == kMode_MR1) {
          // [%r1 + %r1*1] has a smaller encoding than [%r1*2+0]
          inputs[(*input_count)++] = UseRegister(index.value(), reg_kind);
        }
      }
    }
    return mode;
  }
References v8::internal::compiler::CanBeImmediate(), CHECK, v8::internal::DCHECK(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::index, v8::internal::compiler::kNegativeDisplacement, mode(), v8::internal::maglev::UseRegister(), V8_UNLIKELY, v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::ValueFitsIntoImmediate().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon().
GetEffectiveAddressMemoryOperand()
AddressingMode v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand (OpIndex operand, InstructionOperand inputs[], size_t * input_count, RegisterUseKind reg_kind = RegisterUseKind::kUseRegister)
Definition at line 764 of file instruction-selector-x64.cc.
                              {
  const Operation& op = Get(operand);
  if (op.Is<LoadOp>() || op.Is<StoreOp>()) {
    LoadStoreView load_or_store(op);
    if (ExternalReference reference;
        MatchExternalConstant(load_or_store.base, &reference) &&
        !load_or_store.index.valid()) {
      if (selector()->CanAddressRelativeToRootsRegister(reference)) {
        const ptrdiff_t delta =
            load_or_store.offset +
            MacroAssemblerBase::RootRegisterOffsetForExternalReference(
                selector()->isolate(), reference);
        if (is_int32(delta)) {
          inputs[(*input_count)++] = TempImmediate(static_cast<int32_t>(delta));
          return kMode_Root;
        }
      }
    }
  }
  auto m = TryMatchBaseWithScaledIndexAndDisplacement64(selector(), operand);
  DCHECK(m.has_value());
  if (IsCompressed(selector(), m->base)) {
    DCHECK(!m->index.valid());
    DCHECK(m->displacement == 0 || ValueFitsIntoImmediate(m->displacement));
    AddressingMode mode = kMode_MCR;
    inputs[(*input_count)++] = UseRegister(m->base, reg_kind);
    if (m->displacement != 0) {
      inputs[(*input_count)++] =
          m->displacement_mode == kNegativeDisplacement
              ? UseImmediate(static_cast<int>(-m->displacement))
              : UseImmediate(static_cast<int>(m->displacement));
      mode = kMode_MCRI;
    }
    return mode;
  }
  if (m->base.valid() && selector()->Get(m->base).Is<LoadRootRegisterOp>() &&
      !m->index.valid()) {
    DCHECK_EQ(m->scale, 0);
    DCHECK(ValueFitsIntoImmediate(m->displacement));
    inputs[(*input_count)++] = UseImmediate(static_cast<int>(m->displacement));
    return kMode_Root;
  } else if (ValueFitsIntoImmediate(m->displacement)) {
    return GenerateMemoryOperandInputs(m->index, m->scale, m->base,
                                       m->displacement, m->displacement_mode,
                                       inputs, input_count, reg_kind);
  } else if (!m->base.valid() &&
             m->displacement_mode == kPositiveDisplacement) {
    // The displacement cannot be an immediate, but we can use the
    // displacement as base instead and still benefit from addressing
    // modes for the scale.
    UNIMPLEMENTED();
  } else {
    // TODO(nicohartmann@): Turn this into a `DCHECK` once we have some
    // coverage.
    CHECK_EQ(m->displacement, 0);
    inputs[(*input_count)++] = UseRegister(m->base, reg_kind);
    inputs[(*input_count)++] = UseRegister(m->index, reg_kind);
    return kMode_MR1;
  }
}
References CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed(), v8::internal::compiler::kNegativeDisplacement, v8::internal::compiler::kPositiveDisplacement, mode(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), v8::internal::compiler::UNIMPLEMENTED(), v8::internal::maglev::UseRegister(), and v8::internal::compiler::ValueFitsIntoImmediate().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon().
GetEffectiveIndexOperand()
InstructionOperand v8::internal::compiler::X64OperandGenerator::GetEffectiveIndexOperand (OpIndex index, AddressingMode * mode) [inline]
Definition at line 724 of file instruction-selector-x64.cc.
                                                                    {
    if (CanBeImmediate(index)) {
      *mode = kMode_MRI;
      return UseImmediate(index);
    } else {
      *mode = kMode_MR1;
      return UseUniqueRegister(index);
    }
  }
References v8::internal::compiler::CanBeImmediate(), v8::internal::index, and mode().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon().
GetImmediateIntegerValue()
int32_t v8::internal::compiler::X64OperandGenerator::GetImmediateIntegerValue (OpIndex node) [inline]
Definition at line 543 of file instruction-selector-x64.cc.
                                                 {
    return compiler::GetImmediateIntegerValue(this->selector(), node);
  }
References v8::internal::compiler::GetImmediateIntegerValue().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift().
IsZeroIntConstant()
bool v8::internal::compiler::X64OperandGenerator::IsZeroIntConstant (OpIndex node) const [inline]
Definition at line 605 of file instruction-selector-x64.cc.
                                             {
    if (const ConstantOp* op = selector()->TryCast<ConstantOp>(node)) {
      switch (op->kind) {
        case ConstantOp::Kind::kWord32:
          return op->word32() == 0;
        case ConstantOp::Kind::kWord64:
          return op->word64() == 0;
        default:
          break;
      }
    }
    return false;
  }
References v8::internal::compiler::turboshaft::ConstantOp::kWord32, and v8::internal::compiler::turboshaft::ConstantOp::kWord64.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/x64/instruction-selector-x64.cc