v8::internal::CppHeapPointerSlot Class Reference
#include <slots.h>
Public Member Functions
CppHeapPointerSlot ()
CppHeapPointerSlot (Address ptr)
Address try_load (IsolateForPointerCompression isolate, CppHeapPointerTagRange tag_range) const
void store (IsolateForPointerCompression isolate, Address value, CppHeapPointerTag tag) const
void init () const
Additional Inherited Members
Detailed Description
Definition at line 444 of file slots.h.
Constructor & Destructor Documentation
CppHeapPointerSlot() [1/2]
v8::internal::CppHeapPointerSlot::CppHeapPointerSlot () [inline]
Definition at line 448 of file slots.h.
: SlotBase(kNullAddress) {}
CppHeapPointerSlot() [2/2]
v8::internal::CppHeapPointerSlot::CppHeapPointerSlot (Address ptr) [inline]
Definition at line 450 of file slots.h.
: SlotBase(ptr) {}
Member Function Documentation
init()
void v8::internal::CppHeapPointerSlot::init () const [inline]
Definition at line 352 of file slots-inl.h.
                                    {
#ifdef V8_COMPRESS_POINTERS
  base::AsAtomic32::Release_Store(location(), kNullCppHeapPointerHandle);
#else // !V8_COMPRESS_POINTERS
  base::AsAtomicPointer::Release_Store(location(), kNullAddress);
#endif // !V8_COMPRESS_POINTERS
}
References v8::internal::kNullAddress, v8::internal::kNullCppHeapPointerHandle, v8::internal::SlotBase< CppHeapPointerSlot, CppHeapPointer_t, sizeof(CppHeapPointer_t)>::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store().
Referenced by v8::internal::HeapObject::SetupLazilyInitializedCppHeapPointerField().
store()
void v8::internal::CppHeapPointerSlot::store (IsolateForPointerCompression isolate, Address value, CppHeapPointerTag tag) const [inline]
Definition at line 341 of file slots-inl.h.
                                                                           {
#ifdef V8_COMPRESS_POINTERS
  CppHeapPointerTable& table = isolate.GetCppHeapPointerTable();
  CppHeapPointerHandle handle = Relaxed_LoadHandle();
  table.Set(handle, value, tag);
#else // !V8_COMPRESS_POINTERS
  base::AsAtomicPointer::Relaxed_Store(location(), value);
#endif // !V8_COMPRESS_POINTERS
}
References v8::internal::handle(), v8::internal::SlotBase< CppHeapPointerSlot, CppHeapPointer_t, sizeof(CppHeapPointer_t)>::location(), v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and v8::internal::value.
Referenced by v8::internal::WriteLazilyInitializedCppHeapPointerField().
try_load()
Address v8::internal::CppHeapPointerSlot::try_load (IsolateForPointerCompression isolate, CppHeapPointerTagRange tag_range) const [inline]
Definition at line 330 of file slots-inl.h.
                                                                             {
#ifdef V8_COMPRESS_POINTERS
  const CppHeapPointerTable& table = isolate.GetCppHeapPointerTable();
  CppHeapPointerHandle handle = Relaxed_LoadHandle();
  return table.Get(handle, tag_range);
#else // !V8_COMPRESS_POINTERS
  return static_cast<Address>(base::AsAtomicPointer::Relaxed_Load(location()));
#endif // !V8_COMPRESS_POINTERS
}
References v8::internal::handle(), v8::internal::SlotBase< CppHeapPointerSlot, CppHeapPointer_t, sizeof(CppHeapPointer_t)>::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by v8::internal::ReadCppHeapPointerField(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitCppHeapPointer(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitCppHeapPointer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/slots.h
/mnt/V8SourceCode/src/objects/slots-inl.h