v8::StringObject Class Reference
A String object (ECMA-262, 4.3.18).
#include <v8-primitive-object.h>
Public Member Functions
Local< String > ValueOf () const
Static Public Member Functions
static Local< Value > New (Isolate *isolate, Local< String > value)
static StringObject * Cast (Value *value)
Static Private Member Functions
static void CheckCast (Value *obj)
Additional Inherited Members
Detailed Description
A String object (ECMA-262, 4.3.18).
Definition at line 79 of file v8-primitive-object.h.
Member Function Documentation
Cast()
static StringObject* v8::StringObject::Cast (Value * value) [inline], [static]
Definition at line 85 of file v8-primitive-object.h.
                                                    {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<StringObject*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::StringObject::CheckCast (v8::Value * that) [static], [private]
Definition at line 4135 of file api.cc.
                                            {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsStringWrapper(obj), "v8::StringObject::Cast()",
                  "Value is not a StringObject");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
Local< v8::Value > v8::StringObject::New (Isolate * isolate, Local< String > value) [static]
Definition at line 7906 of file api.cc.
                                                            {
  auto string = Utils::OpenDirectHandle(*value);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_StringObject_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::Object> obj =
      i::Object::ToObject(i_isolate, string).ToHandleChecked();
  return Utils::ToLocal(obj);
}
References v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToObject(), and v8::internal::value.
ValueOf()
Local< v8::String > v8::StringObject::ValueOf () const
Definition at line 7917 of file api.cc.
                                              {
  auto obj = Utils::OpenDirectHandle(this);
  auto js_primitive_wrapper = i::Cast<i::JSPrimitiveWrapper>(obj);
  i::Isolate* i_isolate = i::Isolate::Current();
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_StringObject_StringValue);
  return Utils::ToLocal(i::direct_handle(
      i::Cast<i::String>(js_primitive_wrapper->value()), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive-object.h
/mnt/V8SourceCode/src/api/api.cc