v8::ScriptCompiler::ConsumeCodeCacheTask Class Reference
A task which the embedder must run on a background thread to consume a V8 code cache.
#include <v8-script.h>
Public Member Functions
~ConsumeCodeCacheTask ()
void Run ()
void SourceTextAvailable (Isolate *isolate, Local< String > source_text, const ScriptOrigin &origin)
Provides the source text string and origin information to the consumption task.
bool ShouldMergeWithExistingScript () const
Returns whether the embedder should call MergeWithExistingScript.
void MergeWithExistingScript ()
Merges newly deserialized data into an existing script which was found during SourceTextAvailable.
Private Member Functions
ConsumeCodeCacheTask (std::unique_ptr< internal::BackgroundDeserializeTask > impl)
Private Attributes
std::unique_ptr< internal::BackgroundDeserializeTask > impl_
Friends
class ScriptCompiler
Detailed Description
A task which the embedder must run on a background thread to consume a V8 code cache.
Returned by ScriptCompiler::StartConsumingCodeCache.
Definition at line 628 of file v8-script.h.
Constructor & Destructor Documentation
 ConsumeCodeCacheTask()
v8::ScriptCompiler::ConsumeCodeCacheTask::~ConsumeCodeCacheTask () [default]
ConsumeCodeCacheTask()
v8::ScriptCompiler::ConsumeCodeCacheTask::ConsumeCodeCacheTask (std::unique_ptr< internal::BackgroundDeserializeTask > impl) [explicit], [private]
Definition at line 2591 of file api.cc.
    : impl_(std::move(impl)) {}
Member Function Documentation
MergeWithExistingScript()
void v8::ScriptCompiler::ConsumeCodeCacheTask::MergeWithExistingScript ()
Merges newly deserialized data into an existing script which was found during SourceTextAvailable.
May be called only after Run() has completed. Can execute on any thread, like Run().
Definition at line 2622 of file api.cc.
                                                                 {
  DCHECK(
      i::v8_flags.merge_background_deserialized_script_with_compilation_cache);
  impl_->MergeWithExistingScript();
}
References DCHECK, and v8::internal::v8_flags.
Run()
void v8::ScriptCompiler::ConsumeCodeCacheTask::Run ()
Definition at line 2597 of file api.cc.
{ impl_->Run(); }
ShouldMergeWithExistingScript()
bool v8::ScriptCompiler::ConsumeCodeCacheTask::ShouldMergeWithExistingScript () const
Returns whether the embedder should call MergeWithExistingScript.
This function may be called from any thread, any number of times, but its return value is only meaningful after SourceTextAvailable has completed.
Definition at line 2613 of file api.cc.
          {
  if (!i::v8_flags
           .merge_background_deserialized_script_with_compilation_cache) {
    return false;
  }
  return impl_->ShouldMergeWithExistingScript();
}
References v8::internal::v8_flags.
SourceTextAvailable()
void v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable (Isolate * isolate, Local< String > source_text, const ScriptOrigin & origin)
Provides the source text string and origin information to the consumption task.
May be called before, during, or after Run(). This step checks whether the script matches an existing script in the Isolate's compilation cache. To check whether such a script was found, call ShouldMergeWithExistingScript.
The Isolate provided must be the same one used during StartConsumingCodeCache and must be currently entered on the thread that calls this function. The source text and origin provided in this step must precisely match those used later in the ScriptCompiler::Source that will contain this ConsumeCodeCacheTask.
Definition at line 2599 of file api.cc.
                                {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  auto str = Utils::OpenHandle(*source_text);
  i::ScriptDetails script_details =
      GetScriptDetails(i_isolate, origin.ResourceName(), origin.LineOffset(),
                       origin.ColumnOffset(), origin.SourceMapUrl(),
                       origin.GetHostDefinedOptions(), origin.Options());
  impl_->SourceTextAvailable(i_isolate, str, script_details);
}
References v8::ScriptOrigin::ColumnOffset(), v8::ScriptOrigin::GetHostDefinedOptions(), v8::anonymous_namespace{api.cc}::GetScriptDetails(), v8::ScriptOrigin::LineOffset(), v8::Utils::OpenHandle(), v8::ScriptOrigin::Options(), v8::ScriptOrigin::ResourceName(), and v8::ScriptOrigin::SourceMapUrl().
Friends And Related Function Documentation
ScriptCompiler
friend class ScriptCompiler [friend]
Definition at line 665 of file v8-script.h.
Member Data Documentation
impl_
std::unique_ptr<internal::BackgroundDeserializeTask> v8::ScriptCompiler::ConsumeCodeCacheTask::impl_ [private]
Definition at line 670 of file v8-script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc