v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types > Class Template Reference
Static Public Member Functions
template<typename... Operands>
static BytecodeNode Make (BytecodeArrayBuilder *builder, Operands... operands)
Detailed Description
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
class v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types >
Definition at line 350 of file bytecode-array-builder.cc.
Member Function Documentation
Make()
template<Bytecode bytecode, ImplicitRegisterUse implicit_register_use, OperandType... operand_types>
template<typename... Operands>
static BytecodeNode v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types >::Make (BytecodeArrayBuilder * builder, Operands... operands) [inline], [static]
Definition at line 353 of file bytecode-array-builder.cc.
                                                           {
    static_assert(sizeof...(Operands) <= Bytecodes::kMaxOperands,
                  "too many operands for bytecode");
    builder->PrepareToOutputBytecode<bytecode, implicit_register_use>();
    // The "OperandHelper<operand_types>::Convert(builder, operands)..." will
    // expand both the OperandType... and Operands... parameter packs e.g. for:
    // BytecodeNodeBuilder<OperandType::kReg, OperandType::kImm>::Make<
    // Register, int>(..., Register reg, int immediate)
    // the code will expand into:
    // OperandHelper<OperandType::kReg>::Convert(builder, reg),
    // OperandHelper<OperandType::kImm>::Convert(builder, immediate),
    return BytecodeNode::Create<bytecode, implicit_register_use,
                                operand_types...>(
        builder->CurrentSourcePosition(bytecode),
        OperandHelper<operand_types>::Convert(builder, operands)...);
  }
References v8::internal::interpreter::BytecodeNode::Create(), v8::internal::interpreter::BytecodeArrayBuilder::CurrentSourcePosition(), v8::internal::interpreter::Bytecodes::kMaxOperands, and v8::internal::interpreter::BytecodeArrayBuilder::PrepareToOutputBytecode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-array-builder.cc