v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile Class Reference
Public Member Functions
PrepareAndStartCompile (std::shared_ptr< const WasmModule > module, bool start_compilation, bool lazy_functions_are_validated, size_t code_size_estimate)
Private Member Functions
void RunInForeground (AsyncCompileJob *job) override
Private Attributes
const std::shared_ptr< const WasmModule > module_
const bool start_compilation_
const bool lazy_functions_are_validated_
const size_t code_size_estimate_
Detailed Description
Definition at line 3099 of file module-compiler.cc.
Constructor & Destructor Documentation
PrepareAndStartCompile()
v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::PrepareAndStartCompile (std::shared_ptr< const WasmModule > module, bool start_compilation, bool lazy_functions_are_validated, size_t code_size_estimate) [inline]
Definition at line 3101 of file module-compiler.cc.
      : module_(std::move(module)),
        start_compilation_(start_compilation),
        lazy_functions_are_validated_(lazy_functions_are_validated),
        code_size_estimate_(code_size_estimate) {}
Member Function Documentation
RunInForeground()
void v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::RunInForeground (AsyncCompileJob * job) [inline], [override], [private], [virtual]
Reimplemented from v8::internal::wasm::AsyncCompileJob::CompileStep.
Definition at line 3111 of file module-compiler.cc.
                                                      {
    TRACE_COMPILE("(2) Prepare and start compile...\n");
    const bool streaming = job->wire_bytes_.length() == 0;
    if (streaming) {
      // Streaming compilation already checked for cache hits.
      job->CreateNativeModule(module_, code_size_estimate_);
    } else if (job->GetOrCreateNativeModule(std::move(module_),
                                            code_size_estimate_)) {
      job->FinishCompile(true);
      return;
    } else if (!lazy_functions_are_validated_) {
      // If we are not streaming and did not get a cache hit, we might have hit
      // the path where the streaming decoder got a prefix cache hit, but the
      // module then turned out to be invalid, and we are running it through
      // non-streaming decoding again. In this case, function bodies have not
      // been validated yet (would have happened in the {DecodeModule} phase
      // if we would not come via the non-streaming path). Thus do this now.
      // Note that we only need to validate lazily compiled functions, others
      // will be validated during eager compilation.
      DCHECK(start_compilation_);
      if (!v8_flags.wasm_lazy_validation &&
          ValidateFunctions(*job->native_module_, kOnlyLazyFunctions)
              .has_error()) {
        job->Failed();
        return;
      }
    }
    // Make sure all compilation tasks stopped running. Decoding (async step)
    // is done.
    job->background_task_manager_.CancelAndWait();
    CompilationStateImpl* compilation_state =
        Impl(job->native_module_->compilation_state());
    compilation_state->AddCallback(
        std::make_unique<CompilationStateCallback>(job));
    if (base::TimeTicks::IsHighResolution()) {
      auto compile_mode = job->stream_ == nullptr
                              ? CompilationTimeCallback::kAsync
                              : CompilationTimeCallback::kStreaming;
      compilation_state->AddCallback(std::make_unique<CompilationTimeCallback>(
          job->isolate_->async_counters(), job->isolate_->metrics_recorder(),
          job->context_id_, job->native_module_, compile_mode));
    }
    if (start_compilation_) {
      // TODO(13209): Use PGO for async compilation, if available.
      constexpr ProfileInformation* kNoProfileInformation = nullptr;
      std::unique_ptr<CompilationUnitBuilder> builder = InitializeCompilation(
          job->isolate(), job->native_module_.get(), kNoProfileInformation);
      compilation_state->InitializeCompilationUnits(std::move(builder));
      // In single-threaded mode there are no worker tasks that will do the
      // compilation. We call {WaitForCompilationEvent} here so that the main
      // thread participates and finishes the compilation.
      if (v8_flags.wasm_num_compilation_tasks == 0 || v8_flags.wasm_jitless) {
        compilation_state->WaitForCompilationEvent(
            CompilationEvent::kFinishedBaselineCompilation);
      }
    }
  }
References v8::internal::Isolate::async_counters(), v8::internal::wasm::AsyncCompileJob::background_task_manager_, v8::internal::CancelableTaskManager::CancelAndWait(), code_size_estimate_, v8::internal::wasm::AsyncCompileJob::context_id_, v8::internal::wasm::AsyncCompileJob::CreateNativeModule(), v8::internal::DCHECK(), v8::internal::wasm::AsyncCompileJob::Failed(), v8::internal::wasm::AsyncCompileJob::FinishCompile(), v8::internal::wasm::AsyncCompileJob::GetOrCreateNativeModule(), v8::internal::wasm::WasmError::has_error(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::InitializeCompilation(), v8::base::TimeTicks::IsHighResolution(), v8::internal::wasm::AsyncCompileJob::isolate(), v8::internal::wasm::AsyncCompileJob::isolate_, v8::internal::wasm::kFinishedBaselineCompilation, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kOnlyLazyFunctions, lazy_functions_are_validated_, v8::internal::wasm::ModuleWireBytes::length(), v8::internal::Isolate::metrics_recorder(), module_, v8::internal::wasm::AsyncCompileJob::native_module_, start_compilation_, v8::internal::wasm::AsyncCompileJob::stream_, TRACE_COMPILE, v8::internal::v8_flags, v8::internal::wasm::ValidateFunctions(), and v8::internal::wasm::AsyncCompileJob::wire_bytes_.
Member Data Documentation
code_size_estimate_
const size_t v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::code_size_estimate_ [private]
Definition at line 3176 of file module-compiler.cc.
Referenced by RunInForeground().
lazy_functions_are_validated_
const bool v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::lazy_functions_are_validated_ [private]
Definition at line 3175 of file module-compiler.cc.
Referenced by RunInForeground().
module_
const std::shared_ptr<const WasmModule> v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::module_ [private]
Definition at line 3173 of file module-compiler.cc.
Referenced by RunInForeground().
start_compilation_
const bool v8::internal::wasm::AsyncCompileJob::PrepareAndStartCompile::start_compilation_ [private]
Definition at line 3174 of file module-compiler.cc.
Referenced by RunInForeground().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc