v8::internal::wasm::DebugSideTable::Entry Class Reference
#include <wasm-debug.h>
Classes
struct Value
Public Types
enum Storage : int8_t { kConstant
, kRegister
, kStack
 }
Public Member Functions
Entry (int pc_offset, int stack_height, std::vector< Value > changed_values)
Entry (int pc_offset)
int pc_offset () const
int stack_height () const
base::Vector< const Value > changed_values () const
const Value * FindChangedValue (int stack_index) const
void Print (std::ostream &) const
size_t EstimateCurrentMemoryConsumption () const
Private Attributes
int pc_offset_
int stack_height_
std::vector< Value > changed_values_
Detailed Description
Definition at line 44 of file wasm-debug.h.
Member Enumeration Documentation
Storage
enum v8::internal::wasm::DebugSideTable::Entry::Storage : int8_t
Enumerator
kConstant
kRegister
kStack
Definition at line 46 of file wasm-debug.h.
: int8_t { kConstant, kRegister, kStack };
Constructor & Destructor Documentation
Entry() [1/2]
v8::internal::wasm::DebugSideTable::Entry::Entry (int pc_offset, int stack_height, std::vector< Value > changed_values) [inline]
Definition at line 78 of file wasm-debug.h.
        : pc_offset_(pc_offset),
          stack_height_(stack_height),
          changed_values_(std::move(changed_values)) {}
Entry() [2/2]
v8::internal::wasm::DebugSideTable::Entry::Entry (int pc_offset) [inline], [explicit]
Definition at line 84 of file wasm-debug.h.
: pc_offset_(pc_offset) {}
Member Function Documentation
changed_values()
base::Vector<const Value> v8::internal::wasm::DebugSideTable::Entry::changed_values () const [inline]
Definition at line 91 of file wasm-debug.h.
                                                   {
      return base::VectorOf(changed_values_);
    }
References changed_values_, and v8::base::VectorOf().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::DebugSideTable::Entry::EstimateCurrentMemoryConsumption () const
Definition at line 116 of file wasm-debug.cc.
                                                                   {
  UPDATE_WHEN_CLASS_CHANGES(DebugSideTable::Entry, 32);
  return ContentSize(changed_values_);
}
References v8::internal::wasm::ContentSize(), and UPDATE_WHEN_CLASS_CHANGES.
FindChangedValue()
const Value* v8::internal::wasm::DebugSideTable::Entry::FindChangedValue (int stack_index) const [inline]
Definition at line 95 of file wasm-debug.h.
                                                         {
      DCHECK_GT(stack_height_, stack_index);
      auto it = std::lower_bound(
          changed_values_.begin(), changed_values_.end(), stack_index,
          [](const Value& changed_value, int stack_index) {
            return changed_value.index < stack_index;
          });
      return it != changed_values_.end() && it->index == stack_index ? &*it
                                                                     : nullptr;
    }
References changed_values_, DCHECK_GT, and stack_height_.
Referenced by v8::internal::wasm::DebugSideTable::FindValue().
pc_offset()
int v8::internal::wasm::DebugSideTable::Entry::pc_offset () const [inline]
Definition at line 86 of file wasm-debug.h.
{ return pc_offset_; }
References pc_offset_.
Referenced by v8::internal::wasm::DebugSideTable::EntryPositionLess::operator()().
Print()
void v8::internal::wasm::DebugSideTable::Entry::Print (std::ostream & os) const
Definition at line 96 of file wasm-debug.cc.
                                                    {
  os << std::setw(6) << std::hex << pc_offset_ << std::dec << " stack height "
     << stack_height_ << " [";
  for (auto& value : changed_values_) {
    os << " " << value.type.name() << ":";
    switch (value.storage) {
      case kConstant:
        os << "const#" << value.i32_const;
        break;
      case kRegister:
        os << "reg#" << value.reg_code;
        break;
      case kStack:
        os << "stack#" << value.stack_offset;
        break;
    }
  }
  os << " ]\n";
}
References changed_values_, kConstant, kRegister, kStack, pc_offset_, stack_height_, and v8::internal::value.
stack_height()
int v8::internal::wasm::DebugSideTable::Entry::stack_height () const [inline]
Definition at line 89 of file wasm-debug.h.
{ return stack_height_; }
References stack_height_.
Referenced by v8::internal::wasm::DebugInfoImpl::GetStackDepth(), and v8::internal::wasm::DebugInfoImpl::GetStackValue().
Member Data Documentation
changed_values_
std::vector<Value> v8::internal::wasm::DebugSideTable::Entry::changed_values_ [private]
Definition at line 114 of file wasm-debug.h.
Referenced by changed_values(), FindChangedValue(), and Print().
pc_offset_
int v8::internal::wasm::DebugSideTable::Entry::pc_offset_ [private]
Definition at line 111 of file wasm-debug.h.
Referenced by pc_offset(), and Print().
stack_height_
int v8::internal::wasm::DebugSideTable::Entry::stack_height_ [private]
Definition at line 112 of file wasm-debug.h.
Referenced by FindChangedValue(), Print(), and stack_height().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-debug.h
/mnt/V8SourceCode/src/wasm/wasm-debug.cc