cppgc::internal::MemoryRegion Class Reference
#include <page-memory.h>
Public Member Functions
MemoryRegion ()=default
MemoryRegion (Address base, size_t size)
Address base () const
size_t size () const
Address end () const
bool Contains (ConstAddress addr) const
bool Contains (const MemoryRegion &other) const
Private Attributes
Address base_ = nullptr
size_t size_ = 0
Detailed Description
Definition at line 22 of file page-memory.h.
Constructor & Destructor Documentation
MemoryRegion() [1/2]
cppgc::internal::MemoryRegion::MemoryRegion () [default]
MemoryRegion() [2/2]
cppgc::internal::MemoryRegion::MemoryRegion (Address base, size_t size) [inline]
Definition at line 25 of file page-memory.h.
                                          : base_(base), size_(size) {
    DCHECK(base);
    DCHECK_LT(0u, size);
  }
References DCHECK, DCHECK_LT, and size().
Member Function Documentation
base()
Address cppgc::internal::MemoryRegion::base () const [inline]
Definition at line 30 of file page-memory.h.
{ return base_; }
Referenced by cppgc::internal::PageMemoryRegionTree::Add(), cppgc::internal::NormalPageMemoryPool::Add(), Contains(), cppgc::internal::anonymous_namespace{page-memory.cc}::FreeMemoryRegion(), cppgc::internal::PageMemoryRegion::Lookup(), cppgc::internal::PageMemoryRegionTree::Remove(), cppgc::internal::anonymous_namespace{page-memory.cc}::ReserveMemoryRegion(), cppgc::internal::NormalPageMemoryPool::Take(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryDiscard(), and cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect().
Contains() [1/2]
bool cppgc::internal::MemoryRegion::Contains (const MemoryRegion & other) const [inline]
Definition at line 39 of file page-memory.h.
                                                 {
    return base_ <= other.base() && other.end() <= end();
  }
References base(), end(), and v8::internal::compiler::end().
Contains() [2/2]
bool cppgc::internal::MemoryRegion::Contains (ConstAddress addr) const [inline]
Definition at line 34 of file page-memory.h.
                                         {
    return (reinterpret_cast<uintptr_t>(addr) -
            reinterpret_cast<uintptr_t>(base_)) < size_;
  }
Referenced by cppgc::internal::PageMemoryRegion::Lookup().
end()
Address cppgc::internal::MemoryRegion::end () const [inline]
Definition at line 32 of file page-memory.h.
{ return base_ + size_; }
Referenced by Contains(), and cppgc::internal::anonymous_namespace{page-memory.cc}::ReserveMemoryRegion().
size()
size_t cppgc::internal::MemoryRegion::size () const [inline]
Definition at line 31 of file page-memory.h.
{ return size_; }
Referenced by cppgc::internal::NormalPageMemoryPool::Add(), cppgc::internal::anonymous_namespace{page-memory.cc}::FreeMemoryRegion(), cppgc::internal::NormalPageMemoryPool::Take(), cppgc::internal::anonymous_namespace{page-memory.cc}::TryDiscard(), and cppgc::internal::anonymous_namespace{page-memory.cc}::TryUnprotect().
Member Data Documentation
base_
Address cppgc::internal::MemoryRegion::base_ = nullptr [private]
Definition at line 44 of file page-memory.h.
size_
size_t cppgc::internal::MemoryRegion::size_ = 0 [private]
Definition at line 45 of file page-memory.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/page-memory.h