v8::internal::wasm::WasmEnabledFeatures Class Reference
#include <wasm-features.h>
Public Member Functions
constexpr WasmEnabledFeatures ()=default
constexpr WasmEnabledFeatures (std::initializer_list< WasmEnabledFeature > features)
Static Public Member Functions
static constexpr WasmEnabledFeatures All ()
static constexpr WasmEnabledFeatures None ()
static constexpr WasmEnabledFeatures ForAsmjs ()
static V8_EXPORT_PRIVATE WasmEnabledFeatures FromFlags ()
static V8_EXPORT_PRIVATE WasmEnabledFeatures FromIsolate (Isolate *)
static V8_EXPORT_PRIVATE WasmEnabledFeatures FromContext (Isolate *, DirectHandle< NativeContext >)
Additional Inherited Members
Detailed Description
Definition at line 55 of file wasm-features.h.
Constructor & Destructor Documentation
WasmEnabledFeatures() [1/2]
constexpr v8::internal::wasm::WasmEnabledFeatures::WasmEnabledFeatures () [constexpr], [default]
Referenced by All().
WasmEnabledFeatures() [2/2]
constexpr v8::internal::wasm::WasmEnabledFeatures::WasmEnabledFeatures (std::initializer_list< WasmEnabledFeature > features) [inline], [explicit], [constexpr]
Definition at line 58 of file wasm-features.h.
      : EnumSet(features) {}
Member Function Documentation
All()
static constexpr WasmEnabledFeatures v8::internal::wasm::WasmEnabledFeatures::All () [inline], [static], [constexpr]
Definition at line 71 of file wasm-features.h.
                                                    {
#define LIST_FEATURE(feat, ...) WasmEnabledFeature::feat,
    return WasmEnabledFeatures({FOREACH_WASM_FEATURE_FLAG(LIST_FEATURE)});
#undef LIST_FEATURE
  }
References FOREACH_WASM_FEATURE_FLAG, LIST_FEATURE, and WasmEnabledFeatures().
Referenced by v8::internal::wasm::BytecodeIterator::BytecodeIterator(), v8::internal::wasm::OffsetsProvider::CollectOffsets(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::DecodeWasmModuleForDisassembler(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::CompilationEnv::NoModuleAllFeaturesForTesting(), v8::internal::wasm::OpcodeLength(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::OpcodeLength(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
ForAsmjs()
static constexpr WasmEnabledFeatures v8::internal::wasm::WasmEnabledFeatures::ForAsmjs () [inline], [static], [constexpr]
Definition at line 77 of file wasm-features.h.
{ return {}; }
Referenced by v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs().
FromContext()
WasmEnabledFeatures v8::internal::wasm::WasmEnabledFeatures::FromContext (Isolate * isolate, DirectHandle< NativeContext > context) [static]
Definition at line 41 of file wasm-features.cc.
                                                           {
  WasmEnabledFeatures features = WasmEnabledFeatures::FromFlags();
  if (!v8_flags.wasm_jitless) {
    if (isolate->IsWasmStringRefEnabled(context)) {
      features.Add(WasmEnabledFeature::stringref);
    }
    if (isolate->IsWasmImportedStringsEnabled(context)) {
      features.Add(WasmEnabledFeature::imported_strings);
    }
    if (isolate->IsWasmJSPIEnabled(context)) {
      features.Add(WasmEnabledFeature::jspi);
    }
  }
  // This space intentionally left blank for future Wasm origin trials.
  return features;
}
References v8::base::EnumSet< E, T >::Add(), FromFlags(), v8::internal::Isolate::IsWasmImportedStringsEnabled(), v8::internal::Isolate::IsWasmJSPIEnabled(), v8::internal::Isolate::IsWasmStringRefEnabled(), and v8::internal::v8_flags.
Referenced by FromIsolate().
FromFlags()
WasmEnabledFeatures v8::internal::wasm::WasmEnabledFeatures::FromFlags () [static]
Definition at line 17 of file wasm-features.cc.
                                                   {
  WasmEnabledFeatures features = WasmEnabledFeatures::None();
#if V8_ENABLE_DRUMBRAKE
  // DrumBrake supports only a subset or older versions of some Wasm features.
  if (v8_flags.wasm_jitless) {
    features.Add(WasmEnabledFeature::legacy_eh);
  }
#endif // V8_ENABLE_DRUMBRAKE
#define CHECK_FEATURE_FLAG(feat, ...) \
  if (!v8_flags.wasm_jitless && v8_flags.experimental_wasm_##feat) \
    features.Add(WasmEnabledFeature::feat);
  FOREACH_WASM_FEATURE_FLAG(CHECK_FEATURE_FLAG)
#undef CHECK_FEATURE_FLAG
  return features;
}
References v8::base::EnumSet< E, T >::Add(), CHECK_FEATURE_FLAG, FOREACH_WASM_FEATURE_FLAG, None(), and v8::internal::v8_flags.
Referenced by FromContext().
FromIsolate()
WasmEnabledFeatures v8::internal::wasm::WasmEnabledFeatures::FromIsolate (Isolate * isolate) [static]
Definition at line 36 of file wasm-features.cc.
                                                                     {
  return FromContext(isolate, isolate->native_context());
}
References FromContext(), and v8::internal::Isolate::native_context().
Referenced by v8::internal::wasm::DeserializeNativeModule().
None()
static constexpr WasmEnabledFeatures v8::internal::wasm::WasmEnabledFeatures::None () [inline], [static], [constexpr]
Definition at line 76 of file wasm-features.h.
{ return {}; }
Referenced by v8::internal::wasm::AnalyzeLoopAssignmentForTesting(), v8::internal::wasm::ModuleDecoderImpl::consume_heap_type(), v8::internal::wasm::ModuleDecoderImpl::consume_value_type(), and FromFlags().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-features.h
/mnt/V8SourceCode/src/wasm/wasm-features.cc