v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor Class Reference
Public Member Functions
ControlScopeForDerivedConstructor (BytecodeGenerator *generator, Register result_register, BytecodeLabels *check_return_value_labels)
Protected Member Functions
bool Execute (Command command, Statement *statement, int source_position) override
Private Attributes
Register result_register_
BytecodeLabels * check_return_value_labels_
Additional Inherited Members
Detailed Description
Definition at line 576 of file bytecode-generator.cc.
Constructor & Destructor Documentation
ControlScopeForDerivedConstructor()
v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::ControlScopeForDerivedConstructor (BytecodeGenerator * generator, Register result_register, BytecodeLabels * check_return_value_labels) [inline]
Definition at line 579 of file bytecode-generator.cc.
      : ControlScope(generator),
        result_register_(result_register),
        check_return_value_labels_(check_return_value_labels) {}
Member Function Documentation
Execute()
bool v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::Execute (Command command, Statement * statement, int source_position) [inline], [override], [protected], [virtual]
Implements v8::internal::interpreter::BytecodeGenerator::ControlScope.
Definition at line 587 of file bytecode-generator.cc.
                                             {
    // Constructors are never async.
    DCHECK_NE(CMD_ASYNC_RETURN, command);
    if (command == CMD_RETURN) {
      PopContextToExpectedDepth();
      generator()->builder()->SetStatementPosition(source_position);
      generator()->builder()->StoreAccumulatorInRegister(result_register_);
      generator()->builder()->Jump(check_return_value_labels_->New());
      return true;
    }
    return false;
  }
References v8::internal::interpreter::BytecodeGenerator::builder(), check_return_value_labels_, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_ASYNC_RETURN, v8::internal::interpreter::BytecodeGenerator::ControlScope::CMD_RETURN, DCHECK_NE, v8::internal::interpreter::BytecodeGenerator::ControlScope::generator(), v8::internal::interpreter::BytecodeArrayBuilder::Jump(), v8::internal::interpreter::BytecodeLabels::New(), v8::internal::interpreter::BytecodeGenerator::ControlScope::PopContextToExpectedDepth(), result_register_, v8::internal::interpreter::BytecodeArrayBuilder::SetStatementPosition(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
Member Data Documentation
check_return_value_labels_
BytecodeLabels* v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::check_return_value_labels_ [private]
Definition at line 603 of file bytecode-generator.cc.
Referenced by Execute().
result_register_
Register v8::internal::interpreter::BytecodeGenerator::ControlScopeForDerivedConstructor::result_register_ [private]
Definition at line 602 of file bytecode-generator.cc.
Referenced by Execute().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc