v8::StdMapTraits< K, V > Class Template Reference
A default trait implementation for PersistentValueMap which uses std::map as a backing map.
#include <v8-util.h>
Public Types
typedef std::map< K, PersistentContainerValue > Impl
typedef Impl::iterator Iterator
Static Public Member Functions
static bool Empty (Impl *impl)
static size_t Size (Impl *impl)
static void Swap (Impl &a, Impl &b)
static Iterator Begin (Impl *impl)
static Iterator End (Impl *impl)
static K Key (Iterator it)
static PersistentContainerValue Value (Iterator it)
static PersistentContainerValue Set (Impl *impl, K key, PersistentContainerValue value)
static PersistentContainerValue Get (Impl *impl, K key)
static PersistentContainerValue Remove (Impl *impl, K key)
Detailed Description
template<typename K, typename V>
class v8::StdMapTraits< K, V >
A default trait implementation for PersistentValueMap which uses std::map as a backing map.
Users will have to implement their own weak callbacks & dispose traits.
Definition at line 44 of file v8-util.h.
Member Typedef Documentation
Impl
template<typename K , typename V >
typedef std::map<K, PersistentContainerValue> v8::StdMapTraits< K, V >::Impl
Definition at line 47 of file v8-util.h.
Iterator
template<typename K , typename V >
typedef Impl::iterator v8::StdMapTraits< K, V >::Iterator
Definition at line 48 of file v8-util.h.
Member Function Documentation
Begin()
template<typename K , typename V >
static Iterator v8::StdMapTraits< K, V >::Begin (Impl * impl) [inline], [static]
Definition at line 53 of file v8-util.h.
{ return impl->begin(); }
References wasm::impl().
Empty()
template<typename K , typename V >
static bool v8::StdMapTraits< K, V >::Empty (Impl * impl) [inline], [static]
Definition at line 50 of file v8-util.h.
{ return impl->empty(); }
References wasm::impl().
End()
template<typename K , typename V >
static Iterator v8::StdMapTraits< K, V >::End (Impl * impl) [inline], [static]
Definition at line 54 of file v8-util.h.
{ return impl->end(); }
References wasm::impl().
Get()
template<typename K , typename V >
static PersistentContainerValue v8::StdMapTraits< K, V >::Get (Impl * impl, K key) [inline], [static]
Definition at line 67 of file v8-util.h.
                                                         {
    Iterator it = impl->find(key);
    if (it == impl->end()) return kPersistentContainerNotFound;
    return it->second;
  }
References wasm::impl(), v8::internal::key, and v8::kPersistentContainerNotFound.
Key()
template<typename K , typename V >
static K v8::StdMapTraits< K, V >::Key (Iterator it) [inline], [static]
Definition at line 55 of file v8-util.h.
{ return it->first; }
Remove()
template<typename K , typename V >
static PersistentContainerValue v8::StdMapTraits< K, V >::Remove (Impl * impl, K key) [inline], [static]
Definition at line 72 of file v8-util.h.
                                                            {
    Iterator it = impl->find(key);
    if (it == impl->end()) return kPersistentContainerNotFound;
    PersistentContainerValue value = it->second;
    impl->erase(it);
    return value;
  }
References wasm::impl(), v8::internal::key, v8::kPersistentContainerNotFound, and v8::internal::value.
Set()
template<typename K , typename V >
static PersistentContainerValue v8::StdMapTraits< K, V >::Set (Impl * impl, K key, PersistentContainerValue value) [inline], [static]
Definition at line 57 of file v8-util.h.
                                      {
    std::pair<Iterator, bool> res = impl->insert(std::make_pair(key, value));
    PersistentContainerValue old_value = kPersistentContainerNotFound;
    if (!res.second) {
      old_value = res.first->second;
      res.first->second = value;
    }
    return old_value;
  }
References wasm::impl(), v8::internal::key, v8::kPersistentContainerNotFound, and v8::internal::value.
Size()
template<typename K , typename V >
static size_t v8::StdMapTraits< K, V >::Size (Impl * impl) [inline], [static]
Definition at line 51 of file v8-util.h.
{ return impl->size(); }
References wasm::impl().
Swap()
template<typename K , typename V >
static void v8::StdMapTraits< K, V >::Swap (Impl & a, Impl & b) [inline], [static]
Definition at line 52 of file v8-util.h.
{ std::swap(a, b); }
Value()
template<typename K , typename V >
static PersistentContainerValue v8::StdMapTraits< K, V >::Value (Iterator it) [inline], [static]
Definition at line 56 of file v8-util.h.
{ return it->second; }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-util.h