v8::internal::interpreter::BytecodeGenerator::ContextScope Class Reference
Public Member Functions
ContextScope (BytecodeGenerator *generator, Scope *scope, Register outer_context_reg=Register())
~ContextScope ()
ContextScope (const ContextScope &)=delete
ContextScope & operator= (const ContextScope &)=delete
int ContextChainDepth (Scope *scope)
ContextScope * Previous (int depth)
Register reg () const
Private Member Functions
const BytecodeArrayBuilder * builder () const
void set_register (Register reg)
Private Attributes
BytecodeGenerator * generator_
Scope * scope_
ContextScope * outer_
Register register_
int depth_
Detailed Description
Definition at line 50 of file bytecode-generator.cc.
Constructor & Destructor Documentation
ContextScope() [1/2]
v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextScope (BytecodeGenerator * generator, Scope * scope, Register outer_context_reg = Register()) [inline]
Definition at line 52 of file bytecode-generator.cc.
      : generator_(generator),
        scope_(scope),
        outer_(generator_->execution_context()),
        register_(Register::current_context()),
        depth_(0) {
    DCHECK(scope->NeedsContext() || outer_ == nullptr);
    if (outer_) {
      depth_ = outer_->depth_ + 1;
      // Push the outer context into a new context register.
      if (!outer_context_reg.is_valid()) {
        outer_context_reg = generator_->register_allocator()->NewRegister();
      }
      outer_->set_register(outer_context_reg);
      generator_->builder()->PushContext(outer_context_reg);
    }
    generator_->set_execution_context(this);
  }
References v8::internal::DCHECK(), and v8::internal::Scope::NeedsContext().
 ContextScope()
v8::internal::interpreter::BytecodeGenerator::ContextScope::~ContextScope () [inline]
Definition at line 73 of file bytecode-generator.cc.
                  {
    if (outer_) {
      DCHECK_EQ(register_.index(), Register::current_context().index());
      generator_->builder()->PopContext(outer_->reg());
      outer_->set_register(register_);
    }
    generator_->set_execution_context(outer_);
  }
References v8::internal::interpreter::Register::current_context(), DCHECK_EQ, and v8::internal::interpreter::Register::index().
ContextScope() [2/2]
v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextScope (const ContextScope &) [delete]
Member Function Documentation
builder()
const BytecodeArrayBuilder* v8::internal::interpreter::BytecodeGenerator::ContextScope::builder () const [inline], [private]
Definition at line 107 of file bytecode-generator.cc.
{ return generator_->builder(); }
ContextChainDepth()
int v8::internal::interpreter::BytecodeGenerator::ContextScope::ContextChainDepth (Scope * scope) [inline]
Definition at line 86 of file bytecode-generator.cc.
                                      {
    return scope_->ContextChainLength(scope);
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
operator=()
ContextScope& v8::internal::interpreter::BytecodeGenerator::ContextScope::operator= (const ContextScope &) [delete]
Previous()
ContextScope* v8::internal::interpreter::BytecodeGenerator::ContextScope::Previous (int depth) [inline]
Definition at line 92 of file bytecode-generator.cc.
                                    {
    if (depth > depth_) {
      return nullptr;
    }
    ContextScope* previous = this;
    for (int i = depth; i > 0; --i) {
      previous = previous->outer_;
    }
    return previous;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and outer_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
reg()
Register v8::internal::interpreter::BytecodeGenerator::ContextScope::reg () const [inline]
Definition at line 104 of file bytecode-generator.cc.
{ return register_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildVariableAssignment(), and v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad().
set_register()
void v8::internal::interpreter::BytecodeGenerator::ContextScope::set_register (Register reg) [inline], [private]
Definition at line 109 of file bytecode-generator.cc.
{ register_ = reg; }
Member Data Documentation
depth_
int v8::internal::interpreter::BytecodeGenerator::ContextScope::depth_ [private]
Definition at line 115 of file bytecode-generator.cc.
generator_
BytecodeGenerator* v8::internal::interpreter::BytecodeGenerator::ContextScope::generator_ [private]
Definition at line 111 of file bytecode-generator.cc.
outer_
ContextScope* v8::internal::interpreter::BytecodeGenerator::ContextScope::outer_ [private]
Definition at line 113 of file bytecode-generator.cc.
Referenced by Previous().
register_
Register v8::internal::interpreter::BytecodeGenerator::ContextScope::register_ [private]
Definition at line 114 of file bytecode-generator.cc.
scope_
Scope* v8::internal::interpreter::BytecodeGenerator::ContextScope::scope_ [private]
Definition at line 112 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc