cppgc::internal::PreFinalizerHandler Class Reference
#include <prefinalizer-handler.h>
Public Member Functions
PreFinalizerHandler (HeapBase &heap)
void RegisterPrefinalizer (PreFinalizer pre_finalizer)
void InvokePreFinalizers ()
bool IsInvokingPreFinalizers () const
void NotifyAllocationInPrefinalizer (size_t)
size_t ExtractBytesAllocatedInPrefinalizers ()
Private Member Functions
bool CurrentThreadIsCreationThread ()
Private Attributes
std::vector< PreFinalizer > ordered_pre_finalizers_
std::vector< PreFinalizer > * current_ordered_pre_finalizers_
HeapBase & heap_
bool is_invoking_ = false
size_t bytes_allocated_in_prefinalizers = 0u
Detailed Description
Definition at line 27 of file prefinalizer-handler.h.
Constructor & Destructor Documentation
PreFinalizerHandler()
cppgc::internal::PreFinalizerHandler::PreFinalizerHandler (HeapBase & heap) [explicit]
Definition at line 30 of file prefinalizer-handler.cc.
    : current_ordered_pre_finalizers_(&ordered_pre_finalizers_),
      heap_(heap)
{
  DCHECK(CurrentThreadIsCreationThread());
}
References CurrentThreadIsCreationThread(), and DCHECK.
Member Function Documentation
CurrentThreadIsCreationThread()
bool cppgc::internal::PreFinalizerHandler::CurrentThreadIsCreationThread () [private]
Definition at line 88 of file prefinalizer-handler.cc.
                                                        {
#ifdef DEBUG
  return heap_.CurrentThreadIsHeapThread();
#else
  return true;
#endif
}
References cppgc::internal::HeapBase::CurrentThreadIsHeapThread(), and heap_.
Referenced by InvokePreFinalizers(), PreFinalizerHandler(), and RegisterPrefinalizer().
ExtractBytesAllocatedInPrefinalizers()
size_t cppgc::internal::PreFinalizerHandler::ExtractBytesAllocatedInPrefinalizers () [inline]
Definition at line 38 of file prefinalizer-handler.h.
                                                {
    return std::exchange(bytes_allocated_in_prefinalizers, 0);
  }
References bytes_allocated_in_prefinalizers.
InvokePreFinalizers()
void cppgc::internal::PreFinalizerHandler::InvokePreFinalizers ()
Definition at line 48 of file prefinalizer-handler.cc.
                                              {
  StatsCollector::EnabledScope stats_scope(heap_.stats_collector(),
                                           StatsCollector::kAtomicSweep);
  StatsCollector::EnabledScope nested_stats_scope(
      heap_.stats_collector(), StatsCollector::kSweepInvokePreFinalizers);
  DCHECK(CurrentThreadIsCreationThread());
  LivenessBroker liveness_broker = LivenessBrokerFactory::Create();
  is_invoking_ = true;
  DCHECK_EQ(0u, bytes_allocated_in_prefinalizers);
  // Reset all LABs to force allocations to the slow path for black allocation.
  // This also ensures that a CHECK() hits in case prefinalizers allocate in the
  // configuration that prohibits this.
  heap_.object_allocator().ResetLinearAllocationBuffers();
  // Prefinalizers can allocate other objects with prefinalizers, which will
  // modify ordered_pre_finalizers_ and break iterators.
  std::vector<PreFinalizer> new_ordered_pre_finalizers;
  current_ordered_pre_finalizers_ = &new_ordered_pre_finalizers;
  ordered_pre_finalizers_.erase(
      ordered_pre_finalizers_.begin(),
      std::remove_if(ordered_pre_finalizers_.rbegin(),
                     ordered_pre_finalizers_.rend(),
                     [liveness_broker](const PreFinalizer& pf) {
                       return (pf.callback)(liveness_broker, pf.object);
                     })
          .base());
#ifndef CPPGC_ALLOW_ALLOCATIONS_IN_PREFINALIZERS
  CHECK(new_ordered_pre_finalizers.empty());
#else // CPPGC_ALLOW_ALLOCATIONS_IN_PREFINALIZERS
  // Newly added objects with prefinalizers will always survive the current GC
  // cycle, so it's safe to add them after clearing out the older prefinalizers.
  ordered_pre_finalizers_.insert(ordered_pre_finalizers_.end(),
                                 new_ordered_pre_finalizers.begin(),
                                 new_ordered_pre_finalizers.end());
#endif // CPPGC_ALLOW_ALLOCATIONS_IN_PREFINALIZERS
  current_ordered_pre_finalizers_ = &ordered_pre_finalizers_;
  is_invoking_ = false;
  ordered_pre_finalizers_.shrink_to_fit();
}
References bytes_allocated_in_prefinalizers, CHECK, cppgc::internal::LivenessBrokerFactory::Create(), current_ordered_pre_finalizers_, CurrentThreadIsCreationThread(), DCHECK, DCHECK_EQ, heap_, is_invoking_, cppgc::internal::HeapBase::object_allocator(), ordered_pre_finalizers_, cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers(), and cppgc::internal::HeapBase::stats_collector().
IsInvokingPreFinalizers()
bool cppgc::internal::PreFinalizerHandler::IsInvokingPreFinalizers () const [inline]
Definition at line 35 of file prefinalizer-handler.h.
{ return is_invoking_; }
References is_invoking_.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicyBase::CheckPointerImpl(), and cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint().
NotifyAllocationInPrefinalizer()
void cppgc::internal::PreFinalizerHandler::NotifyAllocationInPrefinalizer (size_t size)
Definition at line 96 of file prefinalizer-handler.cc.
                                                                    {
  DCHECK_GT(bytes_allocated_in_prefinalizers + size,
            bytes_allocated_in_prefinalizers);
  bytes_allocated_in_prefinalizers += size;
}
References bytes_allocated_in_prefinalizers, DCHECK_GT, and size().
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint().
RegisterPrefinalizer()
void cppgc::internal::PreFinalizerHandler::RegisterPrefinalizer (PreFinalizer pre_finalizer)
Definition at line 37 of file prefinalizer-handler.cc.
                                                                         {
  DCHECK(CurrentThreadIsCreationThread());
  DCHECK_EQ(ordered_pre_finalizers_.end(),
            std::find(ordered_pre_finalizers_.begin(),
                      ordered_pre_finalizers_.end(), pre_finalizer));
  DCHECK_EQ(current_ordered_pre_finalizers_->end(),
            std::find(current_ordered_pre_finalizers_->begin(),
                      current_ordered_pre_finalizers_->end(), pre_finalizer));
  current_ordered_pre_finalizers_->push_back(pre_finalizer);
}
References current_ordered_pre_finalizers_, CurrentThreadIsCreationThread(), DCHECK, DCHECK_EQ, and ordered_pre_finalizers_.
Member Data Documentation
bytes_allocated_in_prefinalizers
size_t cppgc::internal::PreFinalizerHandler::bytes_allocated_in_prefinalizers = 0u [private]
Definition at line 57 of file prefinalizer-handler.h.
Referenced by ExtractBytesAllocatedInPrefinalizers(), InvokePreFinalizers(), and NotifyAllocationInPrefinalizer().
current_ordered_pre_finalizers_
std::vector<PreFinalizer>* cppgc::internal::PreFinalizerHandler::current_ordered_pre_finalizers_ [private]
Definition at line 51 of file prefinalizer-handler.h.
Referenced by InvokePreFinalizers(), and RegisterPrefinalizer().
heap_
HeapBase& cppgc::internal::PreFinalizerHandler::heap_ [private]
Definition at line 53 of file prefinalizer-handler.h.
Referenced by CurrentThreadIsCreationThread(), and InvokePreFinalizers().
is_invoking_
bool cppgc::internal::PreFinalizerHandler::is_invoking_ = false [private]
Definition at line 54 of file prefinalizer-handler.h.
Referenced by InvokePreFinalizers(), and IsInvokingPreFinalizers().
ordered_pre_finalizers_
std::vector<PreFinalizer> cppgc::internal::PreFinalizerHandler::ordered_pre_finalizers_ [private]
Definition at line 50 of file prefinalizer-handler.h.
Referenced by InvokePreFinalizers(), and RegisterPrefinalizer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/prefinalizer-handler.h
/mnt/V8SourceCode/src/heap/cppgc/prefinalizer-handler.cc