v8::internal::NegativeSubmatchSuccess Class Reference
#include <regexp-nodes.h>
Public Member Functions
NegativeSubmatchSuccess (int stack_pointer_reg, int position_reg, int clear_capture_count, int clear_capture_start, Zone *zone)
void Emit (RegExpCompiler *compiler, Trace *trace) override
Private Attributes
int stack_pointer_register_
int current_position_register_
int clear_capture_count_
int clear_capture_start_
Additional Inherited Members
Detailed Description
Definition at line 608 of file regexp-nodes.h.
Constructor & Destructor Documentation
NegativeSubmatchSuccess()
v8::internal::NegativeSubmatchSuccess::NegativeSubmatchSuccess (int stack_pointer_reg, int position_reg, int clear_capture_count, int clear_capture_start, Zone * zone) [inline]
Definition at line 610 of file regexp-nodes.h.
      : EndNode(NEGATIVE_SUBMATCH_SUCCESS, zone),
        stack_pointer_register_(stack_pointer_reg),
        current_position_register_(position_reg),
        clear_capture_count_(clear_capture_count),
        clear_capture_start_(clear_capture_start) {}
Member Function Documentation
Emit()
void v8::internal::NegativeSubmatchSuccess::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Reimplemented from v8::internal::EndNode.
Definition at line 589 of file regexp-compiler.cc.
                                                                         {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  // Omit flushing the trace. We discard the entire stack frame anyway.
  if (!label()->is_bound()) {
    // We are completely independent of the trace, since we ignore it,
    // so this code can be used as the generic version.
    assembler->Bind(label());
  }
  // Throw away everything on the backtrack stack since the start
  // of the negative submatch and restore the character position.
  assembler->ReadCurrentPositionFromRegister(current_position_register_);
  assembler->ReadStackPointerFromRegister(stack_pointer_register_);
  if (clear_capture_count_ > 0) {
    // Clear any captures that might have been performed during the success
    // of the body of the negative look-ahead.
    int clear_capture_end = clear_capture_start_ + clear_capture_count_ - 1;
    assembler->ClearRegisters(clear_capture_start_, clear_capture_end);
  }
  // Now that we have unwound the stack we find at the top of the stack the
  // backtrack that the BeginNegativeSubmatch node got.
  assembler->Backtrack();
}
References v8::internal::RegExpMacroAssembler::Backtrack(), v8::internal::RegExpMacroAssembler::Bind(), clear_capture_count_, clear_capture_start_, v8::internal::RegExpMacroAssembler::ClearRegisters(), current_position_register_, v8::internal::RegExpNode::label(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::RegExpMacroAssembler::ReadCurrentPositionFromRegister(), v8::internal::RegExpMacroAssembler::ReadStackPointerFromRegister(), and stack_pointer_register_.
Member Data Documentation
clear_capture_count_
int v8::internal::NegativeSubmatchSuccess::clear_capture_count_ [private]
Definition at line 623 of file regexp-nodes.h.
Referenced by Emit().
clear_capture_start_
int v8::internal::NegativeSubmatchSuccess::clear_capture_start_ [private]
Definition at line 624 of file regexp-nodes.h.
Referenced by Emit().
current_position_register_
int v8::internal::NegativeSubmatchSuccess::current_position_register_ [private]
Definition at line 622 of file regexp-nodes.h.
Referenced by Emit().
stack_pointer_register_
int v8::internal::NegativeSubmatchSuccess::stack_pointer_register_ [private]
Definition at line 621 of file regexp-nodes.h.
Referenced by Emit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc