v8::internal::FoldedMutableHeapNumberAllocation Class Reference
Public Member Functions
FoldedMutableHeapNumberAllocation (Isolate *isolate, int count)
Handle< ByteArray > raw_bytes () const
Private Attributes
Handle< ByteArray > raw_bytes_ = {}
Detailed Description
Definition at line 637 of file json-parser.cc.
Constructor & Destructor Documentation
FoldedMutableHeapNumberAllocation()
v8::internal::FoldedMutableHeapNumberAllocation::FoldedMutableHeapNumberAllocation (Isolate * isolate, int count) [inline]
Definition at line 643 of file json-parser.cc.
                                                                 {
    if (count == 0) return;
    int size = count * sizeof(HeapNumber);
    raw_bytes_ = isolate->factory()->NewByteArray(size);
  }
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewByteArray(), raw_bytes_, and size().
Member Function Documentation
raw_bytes()
Handle<ByteArray> v8::internal::FoldedMutableHeapNumberAllocation::raw_bytes () const [inline]
Definition at line 649 of file json-parser.cc.
{ return raw_bytes_; }
References raw_bytes_.
Referenced by v8::internal::FoldedMutableHeapNumberAllocator::FoldedMutableHeapNumberAllocator().
Member Data Documentation
raw_bytes_
Handle<ByteArray> v8::internal::FoldedMutableHeapNumberAllocation::raw_bytes_ = {} [private]
Definition at line 652 of file json-parser.cc.
Referenced by FoldedMutableHeapNumberAllocation(), and raw_bytes().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-parser.cc