cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 > Class Template Reference
#include <tagged-member.h>
Public Member Functions
TaggedUncompressedMember (Tag1, Pointee *ptr)
TaggedUncompressedMember (Tag2, Pointee *ptr)
template<typename Tag >
Pointee * GetAs () const
template<typename Tag >
Pointee * TryGetAs () const
Pointee * GetUntagged () const
template<typename Tag >
void SetAs (Pointee *pointee)
template<typename Tag >
bool Is () const
void Trace (Visitor *v) const
Private Member Functions
CPPGC_DISALLOW_NEW ()
CPPGC_PLUGIN_IGNORE (`See Trace()`) UncompressedMember< Pointee > ptr_
Static Private Attributes
static constexpr uintptr_t kTagBit = 0b1
Detailed Description
template<typename Pointee, typename Tag1, typename Tag2>
class cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >
Definition at line 32 of file tagged-member.h.
Constructor & Destructor Documentation
TaggedUncompressedMember() [1/2]
template<typename Pointee , typename Tag1 , typename Tag2 >
cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::TaggedUncompressedMember (Tag1 , Pointee * ptr) [inline]
Definition at line 39 of file tagged-member.h.
: ptr_(ptr) {}
TaggedUncompressedMember() [2/2]
template<typename Pointee , typename Tag1 , typename Tag2 >
cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::TaggedUncompressedMember (Tag2 , Pointee * ptr) [inline]
Definition at line 40 of file tagged-member.h.
      : ptr_(reinterpret_cast<Pointee*>(reinterpret_cast<uintptr_t>(ptr) |
                                        kTagBit)) {}
Member Function Documentation
CPPGC_DISALLOW_NEW()
template<typename Pointee , typename Tag1 , typename Tag2 >
cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::CPPGC_DISALLOW_NEW () [private]
CPPGC_PLUGIN_IGNORE()
template<typename Pointee , typename Tag1 , typename Tag2 >
cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::CPPGC_PLUGIN_IGNORE (`See Trace()`) [private]
GetAs()
template<typename Pointee , typename Tag1 , typename Tag2 >
template<typename Tag >
Pointee* cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::GetAs () const [inline]
Definition at line 45 of file tagged-member.h.
                         {
    auto* raw = ptr_.Get();
    if constexpr (std::same_as<Tag, Tag1>) {
      CPPGC_DCHECK(Is<Tag1>());
      return raw;
    } else {
      static_assert(std::same_as<Tag, Tag2>);
      CPPGC_DCHECK(Is<Tag2>());
      return GetUntagged();
    }
  }
References CPPGC_DCHECK, and cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::GetUntagged().
GetUntagged()
template<typename Pointee , typename Tag1 , typename Tag2 >
Pointee* cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::GetUntagged () const [inline]
Definition at line 71 of file tagged-member.h.
                               {
    return reinterpret_cast<Pointee*>(reinterpret_cast<uintptr_t>(ptr_.Get()) &
                                      ~kTagBit);
  }
References cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::kTagBit.
Referenced by cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::GetAs().
Is()
template<typename Pointee , typename Tag1 , typename Tag2 >
template<typename Tag >
bool cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::Is () const [inline]
Definition at line 88 of file tagged-member.h.
                  {
    const bool tag_set = reinterpret_cast<uintptr_t>(ptr_.Get()) & kTagBit;
    if constexpr (std::same_as<Tag, Tag1>) {
      return !tag_set;
    } else {
      static_assert(std::same_as<Tag, Tag2>);
      return tag_set;
    }
  }
References cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::kTagBit.
SetAs()
template<typename Pointee , typename Tag1 , typename Tag2 >
template<typename Tag >
void cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::SetAs (Pointee * pointee) [inline]
Definition at line 77 of file tagged-member.h.
                               {
    if constexpr (std::same_as<Tag, Tag1>) {
      ptr_ = pointee;
    } else {
      static_assert(std::same_as<Tag, Tag2>);
      ptr_ = reinterpret_cast<Pointee*>(reinterpret_cast<uintptr_t>(pointee) |
                                        kTagBit);
    }
  }
References cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::kTagBit.
Trace()
template<typename Pointee , typename Tag1 , typename Tag2 >
void cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::Trace (Visitor * v) const [inline]
Definition at line 98 of file tagged-member.h.
                               {
    // Construct an untagged pointer and pass it to Visitor::Trace(). The plugin
    // would warn that ptr_ is untraced, which is why CPPGC_PLUGIN_IGNORE is
    // used.
    auto* untagged = reinterpret_cast<Pointee*>(
        reinterpret_cast<uintptr_t>(ptr_.GetRawAtomic()) & ~kTagBit);
    UncompressedMember<Pointee> temp(untagged);
    v->Trace(temp);
  }
References cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::kTagBit, and cppgc::Visitor::Trace().
TryGetAs()
template<typename Pointee , typename Tag1 , typename Tag2 >
template<typename Tag >
Pointee* cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::TryGetAs () const [inline]
Definition at line 58 of file tagged-member.h.
                            {
    auto* raw = ptr_.Get();
    if constexpr (std::same_as<Tag, Tag1>) {
      return (reinterpret_cast<uintptr_t>(raw) & kTagBit) ? nullptr : raw;
    } else {
      static_assert(std::same_as<Tag, Tag2>);
      return (reinterpret_cast<uintptr_t>(raw) & kTagBit)
                 ? reinterpret_cast<Pointee*>(reinterpret_cast<uintptr_t>(raw) &
                                              ~kTagBit)
                 : nullptr;
    }
  }
References cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::kTagBit, and nullptr.
Member Data Documentation
kTagBit
template<typename Pointee , typename Tag1 , typename Tag2 >
constexpr uintptr_t cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::kTagBit = 0b1 [static], [constexpr], [private]
Definition at line 34 of file tagged-member.h.
Referenced by cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::GetUntagged(), cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::Is(), cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::SetAs(), cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::Trace(), and cppgc::subtle::TaggedUncompressedMember< Pointee, Tag1, Tag2 >::TryGetAs().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/member.h
/mnt/V8SourceCode/include/cppgc/tagged-member.h