v8::internal::DoWhileStatement Class Reference
#include <ast.h>
Public Member Functions
void Initialize (Expression *cond, Statement *body)
Expression * cond () const
Private Member Functions
DoWhileStatement (int pos)
Private Attributes
friend Zone
Expression * cond_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 452 of file ast.h.
Constructor & Destructor Documentation
DoWhileStatement()
v8::internal::DoWhileStatement::DoWhileStatement (int pos) [inline], [explicit], [private]
Definition at line 465 of file ast.h.
      : IterationStatement(pos, kDoWhileStatement), cond_(nullptr) {}
Member Function Documentation
cond()
Expression* v8::internal::DoWhileStatement::cond () const [inline]
Definition at line 459 of file ast.h.
{ return cond_; }
References cond_.
Referenced by Initialize().
Initialize()
void v8::internal::DoWhileStatement::Initialize (Expression * cond, Statement * body) [inline]
Definition at line 454 of file ast.h.
                                                     {
    IterationStatement::Initialize(body);
    cond_ = cond;
  }
References v8::internal::IterationStatement::body(), cond(), cond_, and v8::internal::IterationStatement::Initialize().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 462 of file ast.h.
Member Data Documentation
cond_
Expression* v8::internal::DoWhileStatement::cond_ [private]
Definition at line 468 of file ast.h.
Referenced by cond(), and Initialize().
Zone
friend v8::internal::DoWhileStatement::Zone [private]
Definition at line 463 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h