v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl Class Reference
Classes
struct Value
Public Member Functions
WasmIntoJSInlinerImpl (Zone *zone, const wasm::WasmModule *module, MachineGraph *mcgraph, const wasm::FunctionBody &body, base::Vector< const uint8_t > bytes, SourcePositionTable *source_position_table, int inlining_id)
Node * Param (int index, const char *debug_name=nullptr)
bool TryInlining ()
Private Types
using ValidationTag = NoValidationTag
Private Member Functions
Value ParseAnyConvertExtern (Value input)
Value ParseExternConvertAny (Value input)
Value ParseLocalGet ()
Value ParseStructGet (Value struct_val, WasmOpcode opcode)
void ParseStructSet (Value wasm_struct, Value value)
Value ParseRefCast (Value input, bool null_succeeds)
Value ParseArrayLen (Value input)
Value ParseArrayGet (Value array, Value index, WasmOpcode opcode)
void ParseArraySet (Value array, Value index, Value value)
WasmOpcode ReadOpcode ()
Value TypeNode (Node *node, wasm::ValueType type)
void SetSourcePosition (Node *node)
Private Attributes
const wasm::WasmModule * module_
MachineGraph * mcgraph_
const wasm::FunctionBody & body_
Node ** parameters_
TFGraph * graph_
Node * trusted_data_node_
WasmGraphAssembler gasm_
SourcePositionTable * source_position_table_ = nullptr
const uint8_t * instruction_start_ = pc_
int inlining_id_
bool is_inlineable_ = true
Additional Inherited Members
Detailed Description
Definition at line 26 of file wasm-inlining-into-js.cc.
Member Typedef Documentation
ValidationTag
using v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ValidationTag = NoValidationTag [private]
Definition at line 27 of file wasm-inlining-into-js.cc.
Constructor & Destructor Documentation
WasmIntoJSInlinerImpl()
v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl (Zone * zone, const wasm::WasmModule * module, MachineGraph * mcgraph, const wasm::FunctionBody & body, base::Vector< const uint8_t > bytes, SourcePositionTable * source_position_table, int inlining_id) [inline]
Definition at line 35 of file wasm-inlining-into-js.cc.
      : wasm::Decoder(bytes.begin(), bytes.end()),
        module_(module),
        mcgraph_(mcgraph),
        body_(body),
        graph_(mcgraph->graph()),
        gasm_(mcgraph, zone),
        source_position_table_(source_position_table),
        inlining_id_(inlining_id) {
    // +1 for instance node.
    size_t params = body.sig->parameter_count() + 1;
    Node* start =
        graph_->NewNode(mcgraph->common()->Start(static_cast<int>(params)));
    graph_->SetStart(start);
    graph_->SetEnd(graph_->NewNode(mcgraph->common()->End(0)));
    gasm_.InitializeEffectControl(start, start);
    // Initialize parameter nodes.
    // We have to add another +1 as the minimum parameter index is actually
    // -1, not 0...
    size_t params_extended = params + 1;
    parameters_ = zone->AllocateArray<Node*>(params_extended);
    for (unsigned i = 0; i < params_extended; i++) {
      parameters_[i] = nullptr;
    }
    // Instance node at parameter 0.
    trusted_data_node_ = Param(wasm::kWasmInstanceDataParameterIndex);
  }
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::MachineGraph::common(), v8::internal::compiler::CommonOperatorBuilder::End(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kWasmInstanceDataParameterIndex, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::FunctionBody::sig, and v8::internal::compiler::CommonOperatorBuilder::Start().
Member Function Documentation
Param()
Node* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Param (int index, const char * debug_name = nullptr) [inline]
Definition at line 68 of file wasm-inlining-into-js.cc.
                                                           {
    DCHECK_NOT_NULL(graph_->start());
    // Turbofan allows negative parameter indices.
    DCHECK_GE(index, kMinParameterIndex);
    int array_index = index - kMinParameterIndex;
    if (parameters_[array_index] == nullptr) {
      Node* param = graph_->NewNode(
          mcgraph_->common()->Parameter(index, debug_name), graph_->start());
      if (index > wasm::kWasmInstanceDataParameterIndex) {
        // Add a type guard to keep type information based on the inlinee's
        // signature.
        wasm::ValueType type = body_.sig->GetParam(index - 1);
        Type tf_type = compiler::Type::Wasm(type, module_, graph_->zone());
        param = gasm_.TypeGuard(tf_type, param);
      }
      parameters_[array_index] = param;
    }
    return parameters_[array_index];
  }
References DCHECK_GE, DCHECK_NOT_NULL, v8::internal::index, v8::internal::kMinParameterIndex, v8::internal::wasm::kWasmInstanceDataParameterIndex, and v8::internal::tracing::type.
ParseAnyConvertExtern()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseAnyConvertExtern (Value input) [inline], [private]
Definition at line 189 of file wasm-inlining-into-js.cc.
                                           {
    DCHECK(input.type.is_reference_to(wasm::HeapType::kExtern) ||
           input.type.is_reference_to(wasm::HeapType::kNoExtern));
    wasm::ValueType result_type = wasm::ValueType::Generic(
        wasm::GenericKind::kAny, input.type.nullability(), kNotShared);
    Node* internalized = gasm_.WasmAnyConvertExtern(input.node);
    return TypeNode(internalized, result_type);
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueType::Generic(), v8::internal::wasm::ValueType::is_reference_to(), v8::internal::wasm::HeapType::kExtern, v8::internal::wasm::HeapType::kNoExtern, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::wasm::ValueTypeBase::nullability(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type.
ParseArrayGet()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayGet (Value array, Value index, WasmOpcode opcode) [inline], [private]
Definition at line 308 of file wasm-inlining-into-js.cc.
                                                                   {
    wasm::ModuleTypeIndex array_index{consume_u32v()};
    DCHECK(module_->has_array(array_index));
    const wasm::ArrayType* array_type = module_->array_type(array_index);
    const bool is_signed = opcode == WasmOpcode::kExprArrayGetS;
    const CheckForNull null_check =
        array.type.is_nullable() ? kWithNullCheck : kWithoutNullCheck;
    // Perform bounds check.
    Node* length = gasm_.ArrayLength(array.node, null_check);
    SetSourcePosition(length);
    gasm_.TrapUnless(gasm_.Uint32LessThan(index.node, length),
                     TrapId::kTrapArrayOutOfBounds);
    SetSourcePosition(gasm_.effect());
    // Perform array.get.
    Node* element =
        gasm_.ArrayGet(array.node, index.node, array_type, is_signed);
    return TypeNode(element, array_type->element_type().Unpacked());
  }
References v8::internal::DCHECK(), v8::internal::wasm::ArrayType::element_type(), v8::internal::index, v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::is_signed(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, v8::internal::length, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type, and v8::internal::wasm::ValueType::Unpacked().
ParseArrayLen()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen (Value input) [inline], [private]
Definition at line 298 of file wasm-inlining-into-js.cc.
                                   {
    DCHECK(wasm::IsHeapSubtypeOf(input.type.heap_type(),
                                 wasm::kWasmArrayRef.heap_type(), module_));
    const CheckForNull null_check =
        input.type.is_nullable() ? kWithNullCheck : kWithoutNullCheck;
    Node* len = gasm_.ArrayLength(input.node, null_check);
    SetSourcePosition(len);
    return TypeNode(len, wasm::kWasmI32);
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::IndependentHeapType::heap_type(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::wasm::kWasmArrayRef, v8::internal::wasm::kWasmI32, v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type.
ParseArraySet()
void v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArraySet (Value array, Value index, Value value) [inline], [private]
Definition at line 327 of file wasm-inlining-into-js.cc.
                                                            {
    wasm::ModuleTypeIndex array_index{consume_u32v()};
    DCHECK(module_->has_array(array_index));
    const wasm::ArrayType* array_type = module_->array_type(array_index);
    const CheckForNull null_check =
        array.type.is_nullable() ? kWithNullCheck : kWithoutNullCheck;
    // Perform bounds check.
    Node* length = gasm_.ArrayLength(array.node, null_check);
    SetSourcePosition(length);
    gasm_.TrapUnless(gasm_.Uint32LessThan(index.node, length),
                     TrapId::kTrapArrayOutOfBounds);
    SetSourcePosition(gasm_.effect());
    // Perform array.set.
    gasm_.ArraySet(array.node, index.node, value.node, array_type);
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, v8::internal::length, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type, and v8::internal::value.
ParseExternConvertAny()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseExternConvertAny (Value input) [inline], [private]
Definition at line 198 of file wasm-inlining-into-js.cc.
                                           {
    DCHECK(input.type.is_reference());
    wasm::ValueType result_type = wasm::ValueType::Generic(
        wasm::GenericKind::kExtern, input.type.nullability(), kNotShared);
    Node* internalized = gasm_.WasmExternConvertAny(input.node);
    return TypeNode(internalized, result_type);
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueType::Generic(), v8::internal::wasm::ValueTypeBase::is_reference(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::wasm::ValueTypeBase::nullability(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type.
ParseLocalGet()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseLocalGet () [inline], [private]
Definition at line 206 of file wasm-inlining-into-js.cc.
                        {
    uint32_t index = consume_u32v();
    DCHECK_LT(index, body_.sig->parameter_count());
    return TypeNode(Param(index + 1), body_.sig->GetParam(index));
  }
References DCHECK_LT, and v8::internal::index.
ParseRefCast()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast (Value input, bool null_succeeds) [inline], [private]
Definition at line 241 of file wasm-inlining-into-js.cc.
                                                      {
    auto [heap_index, length] = read_i33v<ValidationTag>(pc_);
    pc_ += length;
    if (heap_index < 0) {
      if ((heap_index & 0x7f) != wasm::kArrayRefCode) {
        // Abstract casts for non array type are not supported.
        is_inlineable_ = false;
        return {};
      }
      auto done = gasm_.MakeLabel();
      // Abstract cast to array.
      if (input.type.is_nullable() && null_succeeds) {
        gasm_.GotoIf(gasm_.IsNull(input.node, input.type), &done);
      }
      gasm_.TrapIf(gasm_.IsSmi(input.node), TrapId::kTrapIllegalCast);
      gasm_.TrapUnless(gasm_.HasInstanceType(input.node, WASM_ARRAY_TYPE),
                       TrapId::kTrapIllegalCast);
      SetSourcePosition(gasm_.effect());
      gasm_.Goto(&done);
      gasm_.Bind(&done);
      // Add TypeGuard for graph typing.
      TFGraph* graph = mcgraph_->graph();
      wasm::ValueType result_type = wasm::ValueType::Generic(
          wasm::GenericKind::kArray,
          null_succeeds ? wasm::kNullable : wasm::kNonNullable, kNotShared);
      Node* type_guard =
          graph->NewNode(mcgraph_->common()->TypeGuard(
                             Type::Wasm(result_type, module_, graph->zone())),
                         input.node, gasm_.effect(), gasm_.control());
      gasm_.InitializeEffectControl(type_guard, gasm_.control());
      return TypeNode(type_guard, result_type);
    }
    wasm::ModuleTypeIndex target_type_index{static_cast<uint32_t>(heap_index)};
    if (module_->has_signature(target_type_index)) {
      is_inlineable_ = false;
      return {};
    }
    wasm::ValueType target_type = wasm::ValueType::RefMaybeNull(
        module_->heap_type(target_type_index),
        null_succeeds ? wasm::kNullable : wasm::kNonNullable);
    Node* rtt = mcgraph_->graph()->NewNode(
        gasm_.simplified()->RttCanon(target_type.ref_index()),
        trusted_data_node_);
    // Technically this is incorrect: the {rtt} node doesn't hold a reference
    // to an object of type {target_type}, but to such an object's map. But
    // we only need this type annotation so {ReduceWasmTypeCast} can get to
    // the {ref_index}, we never need the type's {kind()}.
    TypeNode(rtt, wasm::ValueType::Ref(target_type.heap_type()));
    Node* cast = gasm_.WasmTypeCast(
        input.node, rtt,
        {input.type, target_type,
         module_->type(target_type_index).is_final ? kExactMatchOnly
                                                   : kMayBeSubtype});
    SetSourcePosition(cast);
    return TypeNode(cast, target_type);
  }
References v8::internal::wasm::ValueType::Generic(), graph(), v8::internal::wasm::ValueType::heap_type(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::wasm::kArrayRefCode, v8::internal::wasm::kNonNullable, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, v8::internal::wasm::kNullable, v8::internal::length, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::ValueType::ref_index(), v8::internal::wasm::ValueType::RefMaybeNull(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type.
ParseStructGet()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructGet (Value struct_val, WasmOpcode opcode) [inline], [private]
Definition at line 212 of file wasm-inlining-into-js.cc.
                                                            {
    wasm::ModuleTypeIndex struct_index{consume_u32v()};
    DCHECK(module_->has_struct(struct_index));
    const wasm::StructType* struct_type = module_->struct_type(struct_index);
    uint32_t field_index = consume_u32v();
    DCHECK_GT(struct_type->field_count(), field_index);
    const bool is_signed = opcode == wasm::kExprStructGetS;
    const CheckForNull null_check =
        struct_val.type.is_nullable() ? kWithNullCheck : kWithoutNullCheck;
    Node* member = gasm_.StructGet(struct_val.node, struct_type, field_index,
                                   is_signed, null_check);
    SetSourcePosition(member);
    return TypeNode(member, struct_type->field(field_index).Unpacked());
  }
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::is_signed(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type, and v8::internal::wasm::ValueType::Unpacked().
ParseStructSet()
void v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructSet (Value wasm_struct, Value value) [inline], [private]
Definition at line 227 of file wasm-inlining-into-js.cc.
                                                      {
    wasm::ModuleTypeIndex struct_index{consume_u32v()};
    DCHECK(module_->has_struct(struct_index));
    const wasm::StructType* struct_type = module_->struct_type(struct_index);
    uint32_t field_index = consume_u32v();
    DCHECK_GT(struct_type->field_count(), field_index);
    const CheckForNull null_check =
        wasm_struct.type.is_nullable() ? kWithNullCheck : kWithoutNullCheck;
    gasm_.StructSet(wasm_struct.node, value.node, struct_type, field_index,
                    null_check);
    SetSourcePosition(gasm_.effect());
  }
References v8::internal::DCHECK(), DCHECK_GT, v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::ValueTypeBase::is_nullable(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::node, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::Value::type, and v8::internal::value.
ReadOpcode()
WasmOpcode v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ReadOpcode () [inline], [private]
Definition at line 343 of file wasm-inlining-into-js.cc.
                          {
    DCHECK_LT(pc_, end_);
    instruction_start_ = pc();
    WasmOpcode opcode = static_cast<WasmOpcode>(*pc_);
    if (!WasmOpcodes::IsPrefixOpcode(opcode)) {
      ++pc_;
      return opcode;
    }
    auto [opcode_with_prefix, length] =
        read_prefixed_opcode<ValidationTag>(pc_);
    pc_ += length;
    return opcode_with_prefix;
  }
References DCHECK_LT, and v8::internal::length.
SetSourcePosition()
void v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::SetSourcePosition (Node * node) [inline], [private]
Definition at line 363 of file wasm-inlining-into-js.cc.
                                     {
    if (!source_position_table_->IsEnabled()) return;
    int offset = static_cast<int>(instruction_start_ - start());
    source_position_table_->SetSourcePosition(
        node, SourcePosition(offset, inlining_id_));
  }
TryInlining()
bool v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::TryInlining () [inline]
Definition at line 88 of file wasm-inlining-into-js.cc.
                     {
    if (body_.sig->return_count() > 1) {
      return false; // Multi-return is not supported.
    }
    // Parse locals.
    if (consume_u32v() != 0) {
      // Functions with locals are not supported.
      return false;
    }
    // Parse body.
    base::SmallVector<Value, 4> stack;
    while (is_inlineable_) {
      WasmOpcode opcode = ReadOpcode();
      switch (opcode) {
        case wasm::kExprAnyConvertExtern:
          DCHECK(!stack.empty());
          stack.back() = ParseAnyConvertExtern(stack.back());
          continue;
        case wasm::kExprExternConvertAny:
          DCHECK(!stack.empty());
          stack.back() = ParseExternConvertAny(stack.back());
          continue;
        case wasm::kExprRefCast:
        case wasm::kExprRefCastNull:
          DCHECK(!stack.empty());
          stack.back() =
              ParseRefCast(stack.back(), opcode == wasm::kExprRefCastNull);
          continue;
        case wasm::kExprArrayLen:
          DCHECK(!stack.empty());
          stack.back() = ParseArrayLen(stack.back());
          continue;
        case wasm::kExprArrayGet:
        case wasm::kExprArrayGetS:
        case wasm::kExprArrayGetU: {
          DCHECK_GE(stack.size(), 2);
          Value index = stack.back();
          stack.pop_back();
          Value array = stack.back();
          stack.back() = ParseArrayGet(array, index, opcode);
          continue;
        }
        case wasm::kExprArraySet: {
          DCHECK_GE(stack.size(), 3);
          Value value = stack.back();
          stack.pop_back();
          Value index = stack.back();
          stack.pop_back();
          Value array = stack.back();
          stack.pop_back();
          ParseArraySet(array, index, value);
          continue;
        }
        case wasm::kExprStructGet:
        case wasm::kExprStructGetS:
        case wasm::kExprStructGetU:
          DCHECK(!stack.empty());
          stack.back() = ParseStructGet(stack.back(), opcode);
          continue;
        case wasm::kExprStructSet: {
          DCHECK_GE(stack.size(), 2);
          Value value = stack.back();
          stack.pop_back();
          Value wasm_struct = stack.back();
          stack.pop_back();
          ParseStructSet(wasm_struct, value);
          continue;
        }
        case wasm::kExprLocalGet:
          stack.push_back(ParseLocalGet());
          continue;
        case wasm::kExprDrop:
          DCHECK(!stack.empty());
          stack.pop_back();
          continue;
        case wasm::kExprEnd: {
          DCHECK_LT(stack.size(), 2);
          int return_count = static_cast<int>(stack.size());
          base::SmallVector<Node*, 8> buf(return_count + 3);
          buf[0] = mcgraph_->Int32Constant(0);
          if (return_count) {
            buf[1] = stack.back().node;
          }
          buf[return_count + 1] = gasm_.effect();
          buf[return_count + 2] = gasm_.control();
          Node* ret = graph_->NewNode(mcgraph_->common()->Return(return_count),
                                      return_count + 3, buf.data());
          gasm_.MergeControlToEnd(ret);
          return true;
        }
        default:
          // Instruction not supported for inlining.
          return false;
      }
    }
    // The decoder found an instruction it couldn't inline successfully.
    return false;
  }
References v8::base::SmallVector< T, kSize, Allocator >::data(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, v8::internal::index, v8::internal::stack, and v8::internal::value.
TypeNode()
Value v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::TypeNode (Node * node, wasm::ValueType type) [inline], [private]
Definition at line 357 of file wasm-inlining-into-js.cc.
                                                 {
    compiler::NodeProperties::SetType(
        node, compiler::Type::Wasm(type, module_, graph_->zone()));
    return {node, type};
  }
References v8::internal::compiler::NodeProperties::SetType(), and v8::internal::tracing::type.
Member Data Documentation
body_
const wasm::FunctionBody& v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::body_ [private]
Definition at line 372 of file wasm-inlining-into-js.cc.
gasm_
WasmGraphAssembler v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::gasm_ [private]
Definition at line 376 of file wasm-inlining-into-js.cc.
graph_
TFGraph* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::graph_ [private]
Definition at line 374 of file wasm-inlining-into-js.cc.
inlining_id_
int v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::inlining_id_ [private]
Definition at line 379 of file wasm-inlining-into-js.cc.
instruction_start_
const uint8_t* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::instruction_start_ = pc_ [private]
Definition at line 378 of file wasm-inlining-into-js.cc.
is_inlineable_
bool v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::is_inlineable_ = true [private]
Definition at line 380 of file wasm-inlining-into-js.cc.
mcgraph_
MachineGraph* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::mcgraph_ [private]
Definition at line 371 of file wasm-inlining-into-js.cc.
module_
const wasm::WasmModule* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::module_ [private]
Definition at line 370 of file wasm-inlining-into-js.cc.
parameters_
Node** v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::parameters_ [private]
Definition at line 373 of file wasm-inlining-into-js.cc.
source_position_table_
SourcePositionTable* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::source_position_table_ = nullptr [private]
Definition at line 377 of file wasm-inlining-into-js.cc.
trusted_data_node_
Node* v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::trusted_data_node_ [private]
Definition at line 375 of file wasm-inlining-into-js.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/wasm-inlining-into-js.cc