v8::internal::ThreadManager Class Reference
#include <v8threads.h>
Public Member Functions
void Lock ()
V8_EXPORT_PRIVATE void Unlock ()
void InitThread (const ExecutionAccess &)
void ArchiveThread ()
bool RestoreThread ()
void FreeThreadResources ()
bool IsArchived ()
void Iterate (RootVisitor *v)
void IterateArchivedThreads (ThreadVisitor *v)
bool IsLockedByCurrentThread () const
bool IsLockedByThread (ThreadId id) const
ThreadId CurrentId ()
ThreadState * FirstThreadStateInUse ()
ThreadState * GetFreeThreadState ()
Private Member Functions
ThreadManager (Isolate *isolate)
~ThreadManager ()
void DeleteThreadStateList (ThreadState *anchor)
void EagerlyArchiveThread ()
ASSERT_TRIVIALLY_COPYABLE (i::ThreadId)
Private Attributes
base::Mutex mutex_
std::atomic< ThreadId > mutex_owner_
ThreadId lazily_archived_thread_
ThreadState * lazily_archived_thread_state_
ThreadState * free_anchor_
ThreadState * in_use_anchor_
Isolate * isolate_
Friends
class Isolate
class ThreadState
Detailed Description
Definition at line 60 of file v8threads.h.
Constructor & Destructor Documentation
ThreadManager()
v8::internal::ThreadManager::ThreadManager (Isolate * isolate) [explicit], [private]
Definition at line 220 of file v8threads.cc.
    : mutex_owner_(ThreadId::Invalid()),
      lazily_archived_thread_(ThreadId::Invalid()),
      lazily_archived_thread_state_(nullptr),
      free_anchor_(nullptr),
      in_use_anchor_(nullptr),
      isolate_(isolate) {
  free_anchor_ = new ThreadState(this);
  in_use_anchor_ = new ThreadState(this);
}
References free_anchor_, in_use_anchor_, and ThreadState.
 ThreadManager()
v8::internal::ThreadManager::~ThreadManager () [private]
Definition at line 231 of file v8threads.cc.
                              {
  DeleteThreadStateList(free_anchor_);
  DeleteThreadStateList(in_use_anchor_);
}
References DeleteThreadStateList(), free_anchor_, and in_use_anchor_.
Member Function Documentation
ArchiveThread()
void v8::internal::ThreadManager::ArchiveThread ()
Definition at line 246 of file v8threads.cc.
                                  {
  DCHECK_EQ(lazily_archived_thread_, ThreadId::Invalid());
  DCHECK(!IsArchived());
  DCHECK(IsLockedByCurrentThread());
  ThreadState* state = GetFreeThreadState();
  state->Unlink();
  Isolate::PerIsolateThreadData* per_thread =
      isolate_->FindOrAllocatePerThreadDataForThisThread();
  per_thread->set_thread_state(state);
  lazily_archived_thread_ = ThreadId::Current();
  lazily_archived_thread_state_ = state;
  DCHECK_EQ(state->id(), ThreadId::Invalid());
  state->set_id(CurrentId());
  DCHECK_NE(state->id(), ThreadId::Invalid());
}
References v8::internal::ThreadId::Current(), CurrentId(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::Isolate::FindOrAllocatePerThreadDataForThisThread(), GetFreeThreadState(), v8::internal::ThreadState::id(), v8::internal::ThreadId::Invalid(), IsArchived(), IsLockedByCurrentThread(), isolate_, lazily_archived_thread_, lazily_archived_thread_state_, v8::internal::ThreadState::set_id(), and v8::internal::ThreadState::Unlink().
Referenced by v8::Unlocker::Initialize(), and v8::Locker::~Locker().
ASSERT_TRIVIALLY_COPYABLE()
v8::internal::ThreadManager::ASSERT_TRIVIALLY_COPYABLE (i::ThreadId) [private]
CurrentId()
ThreadId v8::internal::ThreadManager::CurrentId ()
Definition at line 324 of file v8threads.cc.
{ return ThreadId::Current(); }
References v8::internal::ThreadId::Current().
Referenced by ArchiveThread().
DeleteThreadStateList()
void v8::internal::ThreadManager::DeleteThreadStateList (ThreadState * anchor) [private]
Definition at line 236 of file v8threads.cc.
                                                             {
  // The list starts and ends with the anchor.
  for (ThreadState* current = anchor->next_; current != anchor;) {
    ThreadState* next = current->next_;
    delete current;
    current = next;
  }
  delete anchor;
}
References v8::internal::ThreadState::next_.
Referenced by ~ThreadManager().
EagerlyArchiveThread()
void v8::internal::ThreadManager::EagerlyArchiveThread () [private]
Definition at line 262 of file v8threads.cc.
                                         {
  DCHECK(IsLockedByCurrentThread());
  ThreadState* state = lazily_archived_thread_state_;
  state->LinkInto(ThreadState::IN_USE_LIST);
  char* to = state->data();
  // Ensure that data containing GC roots are archived first, and handle them
  // in ThreadManager::Iterate(RootVisitor*).
  to = isolate_->handle_scope_implementer()->ArchiveThread(to);
  to = isolate_->ArchiveThread(to);
  to = Relocatable::ArchiveState(isolate_, to);
  to = isolate_->stack_guard()->ArchiveStackGuard(to);
  to = isolate_->debug()->ArchiveDebug(to);
  to = isolate_->regexp_stack()->ArchiveStack(to);
  to = isolate_->bootstrapper()->ArchiveState(to);
  lazily_archived_thread_ = ThreadId::Invalid();
  lazily_archived_thread_state_ = nullptr;
}
References v8::internal::Debug::ArchiveDebug(), v8::internal::RegExpStack::ArchiveStack(), v8::internal::StackGuard::ArchiveStackGuard(), v8::internal::Bootstrapper::ArchiveState(), v8::internal::Relocatable::ArchiveState(), v8::internal::HandleScopeImplementer::ArchiveThread(), v8::internal::Isolate::ArchiveThread(), v8::internal::Isolate::bootstrapper(), v8::internal::ThreadState::data(), v8::internal::DCHECK(), v8::internal::Isolate::debug(), v8::internal::Isolate::handle_scope_implementer(), v8::internal::ThreadState::IN_USE_LIST, v8::internal::ThreadId::Invalid(), IsLockedByCurrentThread(), isolate_, lazily_archived_thread_, lazily_archived_thread_state_, v8::internal::ThreadState::LinkInto(), v8::internal::Isolate::regexp_stack(), and v8::internal::Isolate::stack_guard().
Referenced by RestoreThread().
FirstThreadStateInUse()
ThreadState * v8::internal::ThreadManager::FirstThreadStateInUse ()
Definition at line 208 of file v8threads.cc.
                                                  {
  return in_use_anchor_->Next();
}
References in_use_anchor_, and v8::internal::ThreadState::Next().
Referenced by Iterate(), IterateArchivedThreads(), and v8::internal::StartupSerializer::SerializeStrongReferences().
FreeThreadResources()
void v8::internal::ThreadManager::FreeThreadResources ()
Definition at line 280 of file v8threads.cc.
                                        {
  // This method might be called on a thread that's not bound to any Isolate
  // and thus pointer compression schemes might have cage base value unset.
  // So, allow heap access here to let the checks work.
  PtrComprCageAccessScope ptr_compr_cage_access_scope(isolate_);
  DCHECK(!isolate_->has_exception());
  DCHECK_NULL(isolate_->try_catch_handler());
  isolate_->handle_scope_implementer()->FreeThreadResources();
  isolate_->FreeThreadResources();
  isolate_->debug()->FreeThreadResources();
  isolate_->stack_guard()->FreeThreadResources();
  isolate_->regexp_stack()->FreeThreadResources();
  isolate_->bootstrapper()->FreeThreadResources();
}
References v8::internal::Isolate::bootstrapper(), v8::internal::DCHECK(), DCHECK_NULL, v8::internal::Isolate::debug(), v8::internal::HandleScopeImplementer::FreeThreadResources(), v8::internal::Debug::FreeThreadResources(), v8::internal::Isolate::FreeThreadResources(), v8::internal::StackGuard::FreeThreadResources(), v8::internal::Bootstrapper::FreeThreadResources(), v8::internal::RegExpStack::FreeThreadResources(), v8::internal::Isolate::handle_scope_implementer(), v8::internal::Isolate::has_exception(), isolate_, v8::internal::Isolate::regexp_stack(), v8::internal::Isolate::stack_guard(), and v8::internal::Isolate::try_catch_handler().
Referenced by v8::Locker::~Locker().
GetFreeThreadState()
ThreadState * v8::internal::ThreadManager::GetFreeThreadState ()
Definition at line 197 of file v8threads.cc.
                                               {
  ThreadState* gotten = free_anchor_->next_;
  if (gotten == free_anchor_) {
    ThreadState* new_thread_state = new ThreadState(this);
    new_thread_state->AllocateSpace();
    return new_thread_state;
  }
  return gotten;
}
References v8::internal::ThreadState::AllocateSpace(), free_anchor_, v8::internal::ThreadState::next_, and ThreadState.
Referenced by ArchiveThread().
InitThread()
void v8::internal::ThreadManager::InitThread (const ExecutionAccess & lock)
Definition at line 87 of file v8threads.cc.
                                                          {
  isolate_->InitializeThreadLocal();
  isolate_->stack_guard()->InitThread(lock);
  isolate_->debug()->InitThread(lock);
}
References v8::internal::Isolate::debug(), v8::internal::Isolate::InitializeThreadLocal(), v8::internal::Debug::InitThread(), v8::internal::StackGuard::InitThread(), isolate_, and v8::internal::Isolate::stack_guard().
Referenced by RestoreThread().
IsArchived()
bool v8::internal::ThreadManager::IsArchived ()
Definition at line 296 of file v8threads.cc.
                               {
  Isolate::PerIsolateThreadData* data =
      isolate_->FindPerThreadDataForThisThread();
  return data != nullptr && data->thread_state() != nullptr;
}
References v8::internal::Isolate::FindPerThreadDataForThisThread(), and isolate_.
Referenced by ArchiveThread().
IsLockedByCurrentThread()
bool v8::internal::ThreadManager::IsLockedByCurrentThread () const [inline]
Definition at line 73 of file v8threads.h.
                                       {
    return mutex_owner_.load(std::memory_order_relaxed) == ThreadId::Current();
  }
References v8::internal::ThreadId::Current(), and mutex_owner_.
Referenced by ArchiveThread(), v8::internal::CppHeap::CurrentThreadIsHeapThread(), EagerlyArchiveThread(), v8::HandleScope::Initialize(), v8::Unlocker::Initialize(), v8::Locker::Initialize(), v8::Locker::IsLocked(), Lock(), v8::Isolate::MemoryPressureNotification(), v8::Shell::QuitOnce(), RestoreThread(), v8::Locker::~Locker(), and v8::Unlocker::~Unlocker().
IsLockedByThread()
bool v8::internal::ThreadManager::IsLockedByThread (ThreadId id) const [inline]
Definition at line 76 of file v8threads.h.
                                           {
    return mutex_owner_.load(std::memory_order_relaxed) == id;
  }
References mutex_owner_.
Iterate()
void v8::internal::ThreadManager::Iterate (RootVisitor * v)
Definition at line 302 of file v8threads.cc.
                                          {
  // Expecting no threads during serialization/deserialization
  for (ThreadState* state = FirstThreadStateInUse(); state != nullptr;
       state = state->Next()) {
    char* data = state->data();
    data = HandleScopeImplementer::Iterate(v, data);
    data = isolate_->Iterate(v, data);
    data = Relocatable::Iterate(v, data);
    data = StackGuard::Iterate(v, data);
    data = Debug::Iterate(v, data);
  }
}
References FirstThreadStateInUse(), isolate_, v8::internal::HandleScopeImplementer::Iterate(), v8::internal::Relocatable::Iterate(), v8::internal::Debug::Iterate(), v8::internal::Isolate::Iterate(), v8::internal::StackGuard::Iterate(), and v8::internal::ThreadState::Next().
Referenced by v8::internal::Heap::IterateRoots().
IterateArchivedThreads()
void v8::internal::ThreadManager::IterateArchivedThreads (ThreadVisitor * v)
Definition at line 315 of file v8threads.cc.
                                                           {
  for (ThreadState* state = FirstThreadStateInUse(); state != nullptr;
       state = state->Next()) {
    char* data = state->data();
    data += HandleScopeImplementer::ArchiveSpacePerThread();
    isolate_->IterateThread(v, data);
  }
}
References v8::internal::HandleScopeImplementer::ArchiveSpacePerThread(), FirstThreadStateInUse(), isolate_, v8::internal::Isolate::IterateThread(), and v8::internal::ThreadState::Next().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CheckNoArchivedThreads(), v8::internal::DebugInfo::ClearBreakInfo(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::Debug::DiscardAllBaselineCode(), v8::internal::Debug::DiscardBaselineCode(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::Fill(), v8::internal::Debug::PrepareFunctionForDebugExecution(), and v8::internal::FinalizationRegistryCleanupTask::SlowAssertNoActiveJavaScript().
Lock()
void v8::internal::ThreadManager::Lock ()
Definition at line 149 of file v8threads.cc.
                         {
  mutex_.Lock();
  mutex_owner_.store(ThreadId::Current(), std::memory_order_relaxed);
  DCHECK(IsLockedByCurrentThread());
}
References v8::internal::ThreadId::Current(), v8::internal::DCHECK(), IsLockedByCurrentThread(), v8::base::Mutex::Lock(), mutex_, and mutex_owner_.
Referenced by v8::Locker::Initialize(), and v8::Unlocker::~Unlocker().
RestoreThread()
bool v8::internal::ThreadManager::RestoreThread ()
Definition at line 93 of file v8threads.cc.
                                  {
  DCHECK(IsLockedByCurrentThread());
  // First check whether the current thread has been 'lazily archived', i.e.
  // not archived at all. If that is the case we put the state storage we
  // had prepared back in the free list, since we didn't need it after all.
  if (lazily_archived_thread_ == ThreadId::Current()) {
    lazily_archived_thread_ = ThreadId::Invalid();
    Isolate::PerIsolateThreadData* per_thread =
        isolate_->FindPerThreadDataForThisThread();
    DCHECK_NOT_NULL(per_thread);
    DCHECK(per_thread->thread_state() == lazily_archived_thread_state_);
    lazily_archived_thread_state_->set_id(ThreadId::Invalid());
    lazily_archived_thread_state_->LinkInto(ThreadState::FREE_LIST);
    lazily_archived_thread_state_ = nullptr;
    per_thread->set_thread_state(nullptr);
    return true;
  }
  // Make sure that the preemption thread cannot modify the thread state while
  // it is being archived or restored.
  ExecutionAccess access(isolate_);
  // If there is another thread that was lazily archived then we have to really
  // archive it now.
  if (lazily_archived_thread_.IsValid()) {
    EagerlyArchiveThread();
  }
  Isolate::PerIsolateThreadData* per_thread =
      isolate_->FindPerThreadDataForThisThread();
  if (per_thread == nullptr || per_thread->thread_state() == nullptr) {
    // This is a new thread.
    InitThread(access);
    return false;
  }
  // In case multi-cage pointer compression mode is enabled ensure that
  // current thread's cage base values are properly initialized.
  PtrComprCageAccessScope ptr_compr_cage_access_scope(isolate_);
  ThreadState* state = per_thread->thread_state();
  char* from = state->data();
  from = isolate_->handle_scope_implementer()->RestoreThread(from);
  from = isolate_->RestoreThread(from);
  from = Relocatable::RestoreState(isolate_, from);
  // Stack guard should be restored before Debug, etc. since Debug etc. might
  // depend on a correct stack guard.
  from = isolate_->stack_guard()->RestoreStackGuard(from);
  from = isolate_->debug()->RestoreDebug(from);
  from = isolate_->regexp_stack()->RestoreStack(from);
  from = isolate_->bootstrapper()->RestoreState(from);
  per_thread->set_thread_state(nullptr);
  state->set_id(ThreadId::Invalid());
  state->Unlink();
  state->LinkInto(ThreadState::FREE_LIST);
  return true;
}
References v8::internal::Isolate::bootstrapper(), v8::internal::ThreadId::Current(), v8::internal::ThreadState::data(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Isolate::debug(), EagerlyArchiveThread(), v8::internal::Isolate::FindPerThreadDataForThisThread(), v8::internal::ThreadState::FREE_LIST, v8::internal::Isolate::handle_scope_implementer(), InitThread(), v8::internal::ThreadId::Invalid(), IsLockedByCurrentThread(), isolate_, v8::internal::ThreadId::IsValid(), lazily_archived_thread_, lazily_archived_thread_state_, v8::internal::ThreadState::LinkInto(), v8::internal::Isolate::regexp_stack(), v8::internal::Debug::RestoreDebug(), v8::internal::RegExpStack::RestoreStack(), v8::internal::StackGuard::RestoreStackGuard(), v8::internal::Bootstrapper::RestoreState(), v8::internal::Relocatable::RestoreState(), v8::internal::HandleScopeImplementer::RestoreThread(), v8::internal::Isolate::RestoreThread(), v8::internal::ThreadState::set_id(), v8::internal::Isolate::stack_guard(), and v8::internal::ThreadState::Unlink().
Referenced by v8::Locker::Initialize(), and v8::Unlocker::~Unlocker().
Unlock()
void v8::internal::ThreadManager::Unlock ()
Definition at line 155 of file v8threads.cc.
                           {
  mutex_owner_.store(ThreadId::Invalid(), std::memory_order_relaxed);
  mutex_.Unlock();
}
References v8::internal::ThreadId::Invalid(), mutex_, mutex_owner_, and v8::base::Mutex::Unlock().
Referenced by v8::Unlocker::Initialize(), v8::Shell::QuitOnce(), and v8::Locker::~Locker().
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 111 of file v8threads.h.
ThreadState
friend class ThreadState [friend]
Definition at line 112 of file v8threads.h.
Referenced by GetFreeThreadState(), and ThreadManager().
Member Data Documentation
free_anchor_
ThreadState* v8::internal::ThreadManager::free_anchor_ [private]
Definition at line 105 of file v8threads.h.
Referenced by GetFreeThreadState(), v8::internal::ThreadState::LinkInto(), ThreadManager(), and ~ThreadManager().
in_use_anchor_
ThreadState* v8::internal::ThreadManager::in_use_anchor_ [private]
Definition at line 107 of file v8threads.h.
Referenced by FirstThreadStateInUse(), v8::internal::ThreadState::LinkInto(), v8::internal::ThreadState::Next(), ThreadManager(), and ~ThreadManager().
isolate_
Isolate* v8::internal::ThreadManager::isolate_ [private]
Definition at line 109 of file v8threads.h.
Referenced by ArchiveThread(), EagerlyArchiveThread(), FreeThreadResources(), InitThread(), IsArchived(), Iterate(), IterateArchivedThreads(), and RestoreThread().
lazily_archived_thread_
ThreadId v8::internal::ThreadManager::lazily_archived_thread_ [private]
Definition at line 98 of file v8threads.h.
Referenced by ArchiveThread(), EagerlyArchiveThread(), and RestoreThread().
lazily_archived_thread_state_
ThreadState* v8::internal::ThreadManager::lazily_archived_thread_state_ [private]
Definition at line 99 of file v8threads.h.
Referenced by ArchiveThread(), EagerlyArchiveThread(), and RestoreThread().
mutex_
base::Mutex v8::internal::ThreadManager::mutex_ [private]
Definition at line 94 of file v8threads.h.
Referenced by Lock(), and Unlock().
mutex_owner_
std::atomic<ThreadId> v8::internal::ThreadManager::mutex_owner_ [private]
Definition at line 97 of file v8threads.h.
Referenced by v8::internal::Isolate::DiscardPerThreadDataForThisThread(), IsLockedByCurrentThread(), IsLockedByThread(), Lock(), and Unlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/v8threads.h
/mnt/V8SourceCode/src/execution/v8threads.cc