v8::internal::wasm::WasmGraphBuilderBase Class Reference
#include <turboshaft-graph-interface.h>
Public Types
using Assembler = compiler::turboshaft::TSAssembler< compiler::turboshaft::SelectLoweringReducer, compiler::turboshaft::DataViewLoweringReducer, compiler::turboshaft::VariableReducer >
template<typename T >
using Var = compiler::turboshaft::Var< T, Assembler >
template<typename T >
using ScopedVar = compiler::turboshaft::ScopedVar< T, Assembler >
using OpIndex = compiler::turboshaft::OpIndex
Public Member Functions
void BuildModifyThreadInWasmFlagHelper (Zone *zone, OpIndex thread_in_wasm_flag_address, bool new_value)
void BuildModifyThreadInWasmFlag (Zone *zone, bool new_value)
Protected Types
using RegisterRepresentation = compiler::turboshaft::RegisterRepresentation
using TSCallDescriptor = compiler::turboshaft::TSCallDescriptor
using Word32 = compiler::turboshaft::Word32
using Word64 = compiler::turboshaft::Word64
using WordPtr = compiler::turboshaft::WordPtr
using CallTarget = compiler::turboshaft::CallTarget
using Word = compiler::turboshaft::Word
using Any = compiler::turboshaft::Any
template<typename T >
using V = compiler::turboshaft::V< T >
template<typename T >
using ConstOrV = compiler::turboshaft::ConstOrV< T >
Protected Member Functions
WasmGraphBuilderBase (Zone *zone, Assembler &assembler)
OpIndex CallRuntime (Zone *zone, Runtime::FunctionId f, std::initializer_list< const OpIndex > args, V< Context > context)
OpIndex GetBuiltinPointerTarget (Builtin builtin)
V< WordPtr > GetTargetForBuiltinCall (Builtin builtin, StubCallMode stub_mode)
V< BigInt > BuildChangeInt64ToBigInt (V< Word64 > input, StubCallMode stub_mode)
std::pair< V< Word32 >, V< HeapObject > > BuildImportedFunctionTargetAndImplicitArg (ConstOrV< Word32 > func_index, V< WasmTrustedInstanceData > trusted_instance_data)
std::pair< V< Word32 >, V< ExposedTrustedObject > > BuildFunctionTargetAndImplicitArg (V< WasmInternalFunction > internal_function)
RegisterRepresentation RepresentationFor (ValueTypeBase type)
OpIndex CallC (const MachineSignature *sig, ExternalReference ref, std::initializer_list< OpIndex > args)
OpIndex CallC (const MachineSignature *sig, OpIndex function, std::initializer_list< OpIndex > args)
OpIndex CallC (const MachineSignature *sig, ExternalReference ref, OpIndex arg)
void BuildSetNewStackLimit (V< WordPtr > old_limit, V< WordPtr > new_limit)
V< WordPtr > BuildSwitchToTheCentralStack (V< WordPtr > old_limit)
std::pair< V< WordPtr >, V< WordPtr > > BuildSwitchToTheCentralStackIfNeeded ()
void BuildSwitchBackFromCentralStack (V< WordPtr > old_sp, V< WordPtr > old_limit)
Assembler & Asm ()
Protected Attributes
Zone * zone_
Assembler & asm_
Friends
template<typename T , typename A >
class compiler::turboshaft::Var
template<typename T , typename A >
class compiler::turboshaft::ScopedVar
Detailed Description
Definition at line 59 of file turboshaft-graph-interface.h.
Member Typedef Documentation
Any
using v8::internal::wasm::WasmGraphBuilderBase::Any = compiler::turboshaft::Any [protected]
Definition at line 92 of file turboshaft-graph-interface.h.
Assembler
using v8::internal::wasm::WasmGraphBuilderBase::Assembler = compiler::turboshaft::TSAssembler< compiler::turboshaft::SelectLoweringReducer, compiler::turboshaft::DataViewLoweringReducer, compiler::turboshaft::VariableReducer>
Definition at line 61 of file turboshaft-graph-interface.h.
CallTarget
using v8::internal::wasm::WasmGraphBuilderBase::CallTarget = compiler::turboshaft::CallTarget [protected]
Definition at line 90 of file turboshaft-graph-interface.h.
ConstOrV
template<typename T >
using v8::internal::wasm::WasmGraphBuilderBase::ConstOrV = compiler::turboshaft::ConstOrV<T> [protected]
Definition at line 97 of file turboshaft-graph-interface.h.
OpIndex
using v8::internal::wasm::WasmGraphBuilderBase::OpIndex = compiler::turboshaft::OpIndex
Definition at line 75 of file turboshaft-graph-interface.h.
RegisterRepresentation
using v8::internal::wasm::WasmGraphBuilderBase::RegisterRepresentation = compiler::turboshaft::RegisterRepresentation [protected]
Definition at line 85 of file turboshaft-graph-interface.h.
ScopedVar
template<typename T >
using v8::internal::wasm::WasmGraphBuilderBase::ScopedVar = compiler::turboshaft::ScopedVar<T, Assembler>
Definition at line 68 of file turboshaft-graph-interface.h.
TSCallDescriptor
using v8::internal::wasm::WasmGraphBuilderBase::TSCallDescriptor = compiler::turboshaft::TSCallDescriptor [protected]
Definition at line 86 of file turboshaft-graph-interface.h.
V
template<typename T >
using v8::internal::wasm::WasmGraphBuilderBase::V = compiler::turboshaft::V<T> [protected]
Definition at line 95 of file turboshaft-graph-interface.h.
Var
template<typename T >
using v8::internal::wasm::WasmGraphBuilderBase::Var = compiler::turboshaft::Var<T, Assembler>
Definition at line 66 of file turboshaft-graph-interface.h.
Word
using v8::internal::wasm::WasmGraphBuilderBase::Word = compiler::turboshaft::Word [protected]
Definition at line 91 of file turboshaft-graph-interface.h.
Word32
using v8::internal::wasm::WasmGraphBuilderBase::Word32 = compiler::turboshaft::Word32 [protected]
Definition at line 87 of file turboshaft-graph-interface.h.
Word64
using v8::internal::wasm::WasmGraphBuilderBase::Word64 = compiler::turboshaft::Word64 [protected]
Definition at line 88 of file turboshaft-graph-interface.h.
WordPtr
using v8::internal::wasm::WasmGraphBuilderBase::WordPtr = compiler::turboshaft::WordPtr [protected]
Definition at line 89 of file turboshaft-graph-interface.h.
Constructor & Destructor Documentation
WasmGraphBuilderBase()
v8::internal::wasm::WasmGraphBuilderBase::WasmGraphBuilderBase (Zone * zone, Assembler & assembler) [inline], [protected]
Definition at line 82 of file turboshaft-graph-interface.h.
      : zone_(zone), asm_(assembler) {}
Member Function Documentation
Asm()
Assembler& v8::internal::wasm::WasmGraphBuilderBase::Asm () [inline], [protected]
Definition at line 130 of file turboshaft-graph-interface.h.
{ return asm_; }
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringHash(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope().
BuildChangeInt64ToBigInt()
V< BigInt > v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt (V< Word64 > input, StubCallMode stub_mode) [protected]
Definition at line 189 of file turboshaft-graph-interface.cc.
                                             {
  Builtin builtin = Is64() ? Builtin::kI64ToBigInt : Builtin::kI32PairToBigInt;
  V<WordPtr> target = GetTargetForBuiltinCall(builtin, stub_mode);
  CallInterfaceDescriptor interface_descriptor =
      Builtins::CallInterfaceDescriptorFor(builtin);
  const CallDescriptor* call_descriptor =
      compiler::Linkage::GetStubCallDescriptor(
          __ graph_zone(), // zone
          interface_descriptor,
          0, // stack parameter count
          CallDescriptor::kNoFlags, // flags
          Operator::kNoProperties, // properties
          stub_mode);
  const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
      call_descriptor, compiler::CanThrow::kNo, compiler::LazyDeoptOnThrow::kNo,
      __ graph_zone());
  if constexpr (Is64()) {
    return V<BigInt>::Cast(__ Call(target, {input}, ts_call_descriptor));
  }
  V<Word32> low_word = __ TruncateWord64ToWord32(input);
  V<Word32> high_word = __ TruncateWord64ToWord32(__ ShiftRightLogical(
      input, __ Word32Constant(32), WordRepresentation::Word64()));
  return V<BigInt>::Cast(
      __ Call(target, {low_word, high_word}, ts_call_descriptor));
}
References __, v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), GetTargetForBuiltinCall(), v8::internal::Is64(), v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicWait(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::ToJS().
BuildFunctionTargetAndImplicitArg()
std::pair< V< Word32 >, V< ExposedTrustedObject > > v8::internal::wasm::WasmGraphBuilderBase::BuildFunctionTargetAndImplicitArg (V< WasmInternalFunction > internal_function) [protected]
Definition at line 253 of file turboshaft-graph-interface.cc.
                                               {
  V<ExposedTrustedObject> implicit_arg =
      V<ExposedTrustedObject>::Cast(__ LoadProtectedPointerField(
          internal_function, LoadOp::Kind::TaggedBase().Immutable(),
          WasmInternalFunction::kProtectedImplicitArgOffset));
  V<Word32> target = __ Load(internal_function, LoadOp::Kind::TaggedBase(),
                             MemoryRepresentation::Uint32(),
                             WasmInternalFunction::kRawCallTargetOffset);
  return {target, implicit_arg};
}
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallAndReturn(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildFunctionReferenceTargetAndImplicitArg().
BuildImportedFunctionTargetAndImplicitArg()
std::pair< V< Word32 >, V< HeapObject > > v8::internal::wasm::WasmGraphBuilderBase::BuildImportedFunctionTargetAndImplicitArg (ConstOrV< Word32 > func_index, V< WasmTrustedInstanceData > trusted_instance_data) [protected]
Definition at line 217 of file turboshaft-graph-interface.cc.
                                                      {
  V<WasmDispatchTable> dispatch_table = LOAD_IMMUTABLE_PROTECTED_INSTANCE_FIELD(
      trusted_instance_data, DispatchTableForImports, WasmDispatchTable);
  // Handle constant indexes specially to reduce graph size, even though later
  // optimization would optimize this to the same result.
  if (func_index.is_constant()) {
    int offset = WasmDispatchTable::OffsetOf(func_index.constant_value());
    V<Word32> target = __ Load(dispatch_table, LoadOp::Kind::TaggedBase(),
                               MemoryRepresentation::Uint32(),
                               offset + WasmDispatchTable::kTargetBias);
    V<ExposedTrustedObject> implicit_arg =
        V<ExposedTrustedObject>::Cast(__ LoadProtectedPointerField(
            dispatch_table, LoadOp::Kind::TaggedBase(),
            offset + WasmDispatchTable::kImplicitArgBias));
    return {target, implicit_arg};
  }
  V<WordPtr> dispatch_table_entry_offset =
      __ WordPtrMul(__ ChangeUint32ToUintPtr(func_index.value()),
                    WasmDispatchTable::kEntrySize);
  V<Word32> target = __ Load(
      dispatch_table, dispatch_table_entry_offset, LoadOp::Kind::TaggedBase(),
      MemoryRepresentation::Uint32(),
      WasmDispatchTable::kEntriesOffset + WasmDispatchTable::kTargetBias);
  V<ExposedTrustedObject> implicit_arg = V<ExposedTrustedObject>::Cast(
      __ LoadProtectedPointerField(dispatch_table, dispatch_table_entry_offset,
                                   LoadOp::Kind::TaggedBase(),
                                   WasmDispatchTable::kEntriesOffset +
                                       WasmDispatchTable::kImplicitArgBias,
                                   0));
  return {target, implicit_arg};
}
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::constant_value(), v8::internal::compiler::turboshaft::ConstOrV< T, C >::is_constant(), v8::internal::WasmDispatchTable::kEntriesOffset, v8::internal::WasmDispatchTable::kEntrySize, v8::internal::WasmDispatchTable::kImplicitArgBias, v8::internal::WasmDispatchTable::kTargetBias, v8::Load(), LOAD_IMMUTABLE_PROTECTED_INSTANCE_FIELD, v8::internal::WasmDispatchTable::OffsetOf(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), and v8::internal::compiler::turboshaft::ConstOrV< T, C >::value().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildImportedFunctionTargetAndImplicitArg().
BuildModifyThreadInWasmFlag()
void v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlag (Zone * zone, bool new_value)
Definition at line 314 of file turboshaft-graph-interface.cc.
                                                                       {
  if (!trap_handler::IsTrapHandlerEnabled()) return;
  OpIndex isolate_root = __ LoadRootRegister();
  OpIndex thread_in_wasm_flag_address =
      __ Load(isolate_root, LoadOp::Kind::RawAligned().Immutable(),
              MemoryRepresentation::UintPtr(),
              Isolate::thread_in_wasm_flag_address_offset());
  BuildModifyThreadInWasmFlagHelper(zone, thread_in_wasm_flag_address,
                                    new_value);
}
References __, BuildModifyThreadInWasmFlagHelper(), v8::internal::trap_handler::IsTrapHandlerEnabled(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::Isolate::thread_in_wasm_flag_address_offset(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetStringIndexOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
BuildModifyThreadInWasmFlagHelper()
void v8::internal::wasm::WasmGraphBuilderBase::BuildModifyThreadInWasmFlagHelper (Zone * zone, OpIndex thread_in_wasm_flag_address, bool new_value)
Definition at line 293 of file turboshaft-graph-interface.cc.
                                                                     {
  if (v8_flags.debug_code) {
    V<Word32> flag_value =
        __ Load(thread_in_wasm_flag_address, LoadOp::Kind::RawAligned(),
                MemoryRepresentation::Int32(), 0);
    IF (UNLIKELY(__ Word32Equal(flag_value, new_value))) {
      OpIndex message_id = __ TaggedIndexConstant(static_cast<int32_t>(
          new_value ? AbortReason::kUnexpectedThreadInWasmSet
                    : AbortReason::kUnexpectedThreadInWasmUnset));
      CallRuntime(zone, Runtime::kAbort, {message_id}, __ NoContextConstant());
      __ Unreachable();
    }
  }
  __ Store(thread_in_wasm_flag_address, __ Word32Constant(new_value),
           LoadOp::Kind::RawAligned(), MemoryRepresentation::Int32(),
           compiler::kNoWriteBarrier);
}
References __, CallRuntime(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::kNoWriteBarrier, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::wasm::liftoff::Store(), v8::internal::v8_flags, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by BuildModifyThreadInWasmFlag(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope().
BuildSetNewStackLimit()
void v8::internal::wasm::WasmGraphBuilderBase::BuildSetNewStackLimit (V< WordPtr > old_limit, V< WordPtr > new_limit) [protected]
Definition at line 349 of file turboshaft-graph-interface.cc.
                                                                       {
  // Set the new interrupt limit and real limit. Use a compare-and-swap for
  // the interrupt limit to avoid overwriting a pending interrupt.
  __ AtomicCompareExchange(
      __ IsolateField(IsolateFieldId::kJsLimitAddress), __ UintPtrConstant(0),
      old_limit, new_limit, RegisterRepresentation::WordPtr(),
      MemoryRepresentation::UintPtr(), compiler::MemoryAccessKind::kNormal,
      RegisterRepresentation::WordPtr());
  __ Store(__ LoadRootRegister(), new_limit, StoreOp::Kind::RawAligned(),
           MemoryRepresentation::UintPtr(), compiler::kNoWriteBarrier,
           IsolateData::real_jslimit_offset());
}
References __, v8::internal::compiler::kNormal, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::IsolateData::real_jslimit_offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Referenced by BuildSwitchBackFromCentralStack(), and BuildSwitchToTheCentralStack().
BuildSwitchBackFromCentralStack()
void v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchBackFromCentralStack (V< WordPtr > old_sp, V< WordPtr > old_limit) [protected]
Definition at line 416 of file turboshaft-graph-interface.cc.
                                             {
  IF_NOT (LIKELY(__ WordPtrEqual(old_sp, __ IntPtrConstant(0)))) {
    // Reset is_on_central_stack flag.
    V<WordPtr> isolate_root = __ LoadRootRegister();
    __ Store(isolate_root, __ Word32Constant(0), StoreOp::Kind::RawAligned(),
             MemoryRepresentation::Uint8(), compiler::kNoWriteBarrier,
             IsolateData::is_on_central_stack_flag_offset());
    // Clear stack switch info.
    // We are not on the main stack, so the active stack must be set.
    V<WordPtr> active_stack = __ Load(isolate_root, LoadOp::Kind::RawAligned(),
                                      MemoryRepresentation::UintPtr(),
                                      IsolateData::active_stack_offset());
    __ Store(active_stack, __ UintPtrConstant(0), StoreOp::Kind::RawAligned(),
             MemoryRepresentation::UintPtr(), compiler::kNoWriteBarrier,
             StackMemory::stack_switch_source_fp_offset());
    // Restore the old stack limit and stack pointer.
    V<WordPtr> real_jslimit = __ Load(isolate_root, LoadOp::Kind::RawAligned(),
                                      MemoryRepresentation::UintPtr(),
                                      IsolateData::real_jslimit_offset());
    BuildSetNewStackLimit(real_jslimit, old_limit);
    __ SetStackPointer(old_sp);
  }
}
References __, BuildSetNewStackLimit(), v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::kNoWriteBarrier, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::IsolateData::real_jslimit_offset(), v8::internal::wasm::StackMemory::stack_switch_source_fp_offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
BuildSwitchToTheCentralStack()
V< WordPtr > v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStack (V< WordPtr > old_limit) [protected]
Definition at line 363 of file turboshaft-graph-interface.cc.
                          {
  // Set the is_on_central_stack flag.
  OpIndex isolate_root = __ LoadRootRegister();
  __ Store(isolate_root, __ Word32Constant(1), LoadOp::Kind::RawAligned(),
           MemoryRepresentation::Uint8(), compiler::kNoWriteBarrier,
           IsolateData::is_on_central_stack_flag_offset());
  // Save the old fp and the target sp in the StackMemory's stack switch info.
  // We are not on the main stack, so the active stack must be set.
  V<WordPtr> active_stack = __ Load(isolate_root, LoadOp::Kind::RawAligned(),
                                    MemoryRepresentation::UintPtr(),
                                    IsolateData::active_stack_offset());
  __ Store(active_stack, __ FramePointer(), StoreOp::Kind::RawAligned(),
           MemoryRepresentation::UintPtr(), compiler::kNoWriteBarrier,
           StackMemory::stack_switch_source_fp_offset());
  V<WordPtr> central_stack_sp = __ Load(
      isolate_root, LoadOp::Kind::RawAligned(), MemoryRepresentation::UintPtr(),
      Isolate::central_stack_sp_offset());
  __ Store(active_stack, central_stack_sp, StoreOp::Kind::RawAligned(),
           MemoryRepresentation::UintPtr(), compiler::kNoWriteBarrier,
           StackMemory::stack_switch_target_sp_offset());
  // Switch the stack limit and the stack pointer.
  V<WordPtr> central_stack_limit = __ Load(
      isolate_root, LoadOp::Kind::RawAligned(), MemoryRepresentation::UintPtr(),
      Isolate::central_stack_limit_offset());
  BuildSetNewStackLimit(old_limit, central_stack_limit);
  OpIndex old_sp = __ LoadStackPointer();
  __ SetStackPointer(central_stack_sp);
  return old_sp;
}
References __, BuildSetNewStackLimit(), v8::internal::Isolate::central_stack_limit_offset(), v8::internal::Isolate::central_stack_sp_offset(), v8::internal::compiler::kNoWriteBarrier, v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::wasm::StackMemory::stack_switch_source_fp_offset(), v8::internal::wasm::StackMemory::stack_switch_target_sp_offset(), v8::internal::wasm::liftoff::Store(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), and BuildSwitchToTheCentralStackIfNeeded().
BuildSwitchToTheCentralStackIfNeeded()
std::pair< V< WordPtr >, V< WordPtr > > v8::internal::wasm::WasmGraphBuilderBase::BuildSwitchToTheCentralStackIfNeeded () [protected]
Definition at line 398 of file turboshaft-graph-interface.cc.
                                                           {
  V<WordPtr> isolate_root = __ LoadRootRegister();
  V<Word32> is_on_central_stack_flag = __ Load(
      isolate_root, LoadOp::Kind::RawAligned(), MemoryRepresentation::Uint8(),
      IsolateData::is_on_central_stack_flag_offset());
  ScopedVar<WordPtr> old_sp_var(this, __ IntPtrConstant(0));
  ScopedVar<WordPtr> old_limit_var(this, __ IntPtrConstant(0));
  IF_NOT (LIKELY(is_on_central_stack_flag)) {
    V<WordPtr> old_limit = __ Load(isolate_root, LoadOp::Kind::RawAligned(),
                                   MemoryRepresentation::UintPtr(),
                                   IsolateData::real_jslimit_offset());
    V<WordPtr> old_sp = BuildSwitchToTheCentralStack(old_limit);
    old_sp_var = old_sp;
    old_limit_var = old_limit;
  }
  return {old_sp_var, old_limit_var};
}
References __, BuildSwitchToTheCentralStack(), v8::internal::compiler::IntPtrConstant(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::IsolateData::real_jslimit_offset(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
CallC() [1/3]
OpIndex v8::internal::wasm::WasmGraphBuilderBase::CallC (const MachineSignature * sig, ExternalReference ref, OpIndex arg) [inline], [protected]
Definition at line 120 of file turboshaft-graph-interface.h.
                             {
    return CallC(sig, ref, {arg});
  }
References v8::internal::sig.
CallC() [2/3]
OpIndex v8::internal::wasm::WasmGraphBuilderBase::CallC (const MachineSignature * sig, ExternalReference ref, std::initializer_list< OpIndex > args) [protected]
Definition at line 329 of file turboshaft-graph-interface.cc.
                                                                       {
  return WasmGraphBuilderBase::CallC(sig, __ ExternalConstant(ref), args);
}
References __, v8::base::args, and v8::internal::sig.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::AtomicNotify(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCcallConvertFloatSat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildCCallForFloatConversion(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildDiv64Call(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIntToFloatConversionInstruction(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToInt32(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallCStackSlotToStackSlot(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryCopy(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryInit(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl().
CallC() [3/3]
OpIndex v8::internal::wasm::WasmGraphBuilderBase::CallC (const MachineSignature * sig, OpIndex function, std::initializer_list< OpIndex > args) [protected]
Definition at line 335 of file turboshaft-graph-interface.cc.
                                                                       {
  DCHECK_LE(sig->return_count(), 1);
  DCHECK_EQ(sig->parameter_count(), args.size());
  const CallDescriptor* call_descriptor =
      compiler::Linkage::GetSimplifiedCDescriptor(__ graph_zone(), sig);
  const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
      call_descriptor, compiler::CanThrow::kNo, compiler::LazyDeoptOnThrow::kNo,
      __ graph_zone());
  return __ Call(function, OpIndex::Invalid(), base::VectorOf(args),
                 ts_call_descriptor);
}
References __, v8::base::args, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::kNo, v8::internal::sig, and v8::base::VectorOf().
CallRuntime()
OpIndex v8::internal::wasm::WasmGraphBuilderBase::CallRuntime (Zone * zone, Runtime::FunctionId f, std::initializer_list< const OpIndex > args, V< Context > context) [protected]
Definition at line 148 of file turboshaft-graph-interface.cc.
                                                                 {
  const Runtime::Function* fun = Runtime::FunctionForId(f);
  OpIndex isolate_root = __ LoadRootRegister();
  DCHECK_EQ(1, fun->result_size);
  int builtin_slot_offset =
      IsolateData::BuiltinSlotOffset(Builtin::kWasmCEntry);
  OpIndex centry_stub =
      __ Load(isolate_root, LoadOp::Kind::RawAligned(),
              MemoryRepresentation::UintPtr(), builtin_slot_offset);
  // CallRuntime is always called with 0 or 1 argument, so a vector of size 4
  // always suffices.
  SmallZoneVector<OpIndex, 4> centry_args(zone);
  for (OpIndex arg : args) centry_args.emplace_back(arg);
  centry_args.emplace_back(__ ExternalConstant(ExternalReference::Create(f)));
  centry_args.emplace_back(__ Word32Constant(fun->nargs));
  centry_args.emplace_back(context);
  const CallDescriptor* call_descriptor =
      compiler::Linkage::GetRuntimeCallDescriptor(
          __ graph_zone(), f, fun->nargs, Operator::kNoProperties,
          CallDescriptor::kNoFlags);
  const TSCallDescriptor* ts_call_descriptor = TSCallDescriptor::Create(
      call_descriptor, compiler::CanThrow::kYes,
      compiler::LazyDeoptOnThrow::kNo, __ graph_zone());
  return __ Call(centry_stub, OpIndex::Invalid(), base::VectorOf(centry_args),
                 ts_call_descriptor);
}
References __, v8::base::args, v8::internal::IsolateData::BuiltinSlotOffset(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::ExternalReference::Create(), DCHECK_EQ, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::internal::Runtime::FunctionForId(), v8::internal::compiler::Linkage::GetRuntimeCallDescriptor(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::kNo, v8::internal::compiler::CallDescriptor::kNoFlags, v8::internal::compiler::Operator::kNoProperties, v8::internal::compiler::kYes, v8::Load(), v8::internal::Runtime::Function::nargs, v8::internal::compiler::turboshaft::LoadOp::Kind::RawAligned(), v8::internal::Runtime::Function::result_size, v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr(), and v8::base::VectorOf().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::AbortIfNot(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCheckString(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildJSToWasmWrapper(), BuildModifyThreadInWasmFlagHelper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::TraceMemoryOperation().
GetBuiltinPointerTarget()
OpIndex v8::internal::wasm::WasmGraphBuilderBase::GetBuiltinPointerTarget (Builtin builtin) [protected]
Definition at line 177 of file turboshaft-graph-interface.cc.
                                                                     {
  static_assert(std::is_same_v<Smi, BuiltinPtr>, "BuiltinPtr must be Smi");
  return __ SmiConstant(Smi::FromInt(static_cast<int>(builtin)));
}
References __, and v8::internal::Smi::FromInt().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildSuspend(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), and GetTargetForBuiltinCall().
GetTargetForBuiltinCall()
V< WordPtr > v8::internal::wasm::WasmGraphBuilderBase::GetTargetForBuiltinCall (Builtin builtin, StubCallMode stub_mode) [protected]
Definition at line 182 of file turboshaft-graph-interface.cc.
                                             {
  return stub_mode == StubCallMode::kCallWasmRuntimeStub
             ? __ RelocatableWasmBuiltinCallTarget(builtin)
             : GetBuiltinPointerTarget(builtin);
}
References __, and GetBuiltinPointerTarget().
Referenced by BuildChangeInt64ToBigInt(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::GetTargetForBuiltinCall().
RepresentationFor()
RegisterRepresentation v8::internal::wasm::WasmGraphBuilderBase::RepresentationFor (ValueTypeBase type) [protected]
Definition at line 267 of file turboshaft-graph-interface.cc.
                        {
  switch (type.kind()) {
    case kI8:
    case kI16:
    case kI32:
      return RegisterRepresentation::Word32();
    case kI64:
      return RegisterRepresentation::Word64();
    case kF16:
    case kF32:
      return RegisterRepresentation::Float32();
    case kF64:
      return RegisterRepresentation::Float64();
    case kRefNull:
    case kRef:
      return RegisterRepresentation::Tagged();
    case kS128:
      return RegisterRepresentation::Simd128();
    case kVoid:
    case kTop:
    case kBottom:
      UNREACHABLE();
  }
}
References v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::compiler::turboshaft::RegisterRepresentation::Simd128(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::tracing::type, v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCallWasmFromWrapper(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildCapiCallWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmCall(), v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallIndirect(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallRef(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Loop(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MaybePhi(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Select(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StringViewWtf8Encode().
Friends And Related Function Documentation
compiler::turboshaft::ScopedVar
template<typename T , typename A >
friend class compiler::turboshaft::ScopedVar [friend]
Definition at line 72 of file turboshaft-graph-interface.h.
compiler::turboshaft::Var
template<typename T , typename A >
friend class compiler::turboshaft::Var [friend]
Definition at line 70 of file turboshaft-graph-interface.h.
Member Data Documentation
asm_
Assembler& v8::internal::wasm::WasmGraphBuilderBase::asm_ [protected]
Definition at line 133 of file turboshaft-graph-interface.h.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Asm(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BinOpImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildIndirectCallTargetAndImplicitArg(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ChangeTaggedNumberToIntPtr(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetCodeUnitImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetDataViewByteLength(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetStringIndexOf(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryGrow(), v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringCodePointAt(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEqImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGrow(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
zone_
Zone* v8::internal::wasm::WasmGraphBuilderBase::zone_ [protected]
Definition at line 132 of file turboshaft-graph-interface.h.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::BuildWasmToJSWrapper().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/turboshaft-graph-interface.h
/mnt/V8SourceCode/src/wasm/turboshaft-graph-interface.cc