v8::internal::interpreter::RegisterTransferWriter Class Reference
Public Member Functions
RegisterTransferWriter (BytecodeArrayBuilder *builder)
~RegisterTransferWriter () override=default
void EmitLdar (Register input) override
void EmitStar (Register output) override
void EmitMov (Register input, Register output) override
Private Attributes
BytecodeArrayBuilder * builder_
Detailed Description
Definition at line 27 of file bytecode-array-builder.cc.
Constructor & Destructor Documentation
RegisterTransferWriter()
v8::internal::interpreter::RegisterTransferWriter::RegisterTransferWriter (BytecodeArrayBuilder * builder) [inline], [explicit]
Definition at line 31 of file bytecode-array-builder.cc.
      : builder_(builder) {}
 RegisterTransferWriter()
v8::internal::interpreter::RegisterTransferWriter::~RegisterTransferWriter () [override], [default]
Member Function Documentation
EmitLdar()
void v8::internal::interpreter::RegisterTransferWriter::EmitLdar (Register input) [inline], [override]
Definition at line 35 of file bytecode-array-builder.cc.
{ builder_->OutputLdarRaw(input); }
References builder_, and v8::internal::interpreter::BytecodeArrayBuilder::OutputLdarRaw().
EmitMov()
void v8::internal::interpreter::RegisterTransferWriter::EmitMov (Register input, Register output) [inline], [override]
Definition at line 39 of file bytecode-array-builder.cc.
                                                         {
    builder_->OutputMovRaw(input, output);
  }
References builder_, and v8::internal::interpreter::BytecodeArrayBuilder::OutputMovRaw().
EmitStar()
void v8::internal::interpreter::RegisterTransferWriter::EmitStar (Register output) [inline], [override]
Definition at line 37 of file bytecode-array-builder.cc.
{ builder_->OutputStarRaw(output); }
References builder_, and v8::internal::interpreter::BytecodeArrayBuilder::OutputStarRaw().
Member Data Documentation
builder_
BytecodeArrayBuilder* v8::internal::interpreter::RegisterTransferWriter::builder_ [private]
Definition at line 44 of file bytecode-array-builder.cc.
Referenced by EmitLdar(), EmitMov(), and EmitStar().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-array-builder.cc