v8::internal::wasm::IndependentHeapType Class Reference
#include <value-type.h>
Public Member Functions
constexpr IndependentHeapType (GenericKind kind, Nullability nullable=kNullable, bool shared=false)
constexpr IndependentHeapType AsNonNull () const
constexpr HeapType heap_type () const
constexpr operator HeapType () const
Additional Inherited Members
Detailed Description
Definition at line 1136 of file value-type.h.
Constructor & Destructor Documentation
IndependentHeapType()
constexpr v8::internal::wasm::IndependentHeapType::IndependentHeapType (GenericKind kind, Nullability nullable = kNullable, bool shared = false) [inline], [explicit], [constexpr]
Definition at line 1138 of file value-type.h.
      : IndependentValueType(kind, nullable, shared) {}
Referenced by AsNonNull().
Member Function Documentation
AsNonNull()
constexpr IndependentHeapType v8::internal::wasm::IndependentHeapType::AsNonNull () const [inline], [constexpr]
Definition at line 1143 of file value-type.h.
                                                  {
    return IndependentHeapType(generic_kind(), kNonNullable, is_shared());
  }
References v8::internal::wasm::ValueTypeBase::generic_kind(), IndependentHeapType(), v8::internal::wasm::ValueTypeBase::is_shared(), and v8::internal::wasm::kNonNullable.
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), and v8::internal::compiler::WasmGraphBuilder::SetType().
heap_type()
constexpr HeapType v8::internal::wasm::IndependentHeapType::heap_type () const [inline], [constexpr]
Definition at line 1147 of file value-type.h.
{ return HeapType{*this}; }
Referenced by v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen().
operator HeapType()
constexpr v8::internal::wasm::IndependentHeapType::operator HeapType () const [inline], [constexpr]
Definition at line 1148 of file value-type.h.
{ return HeapType{*this}; }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/value-type.h