v8::internal::interpreter::BytecodeArrayRandomIterator Class Reference
#include <bytecode-array-random-iterator.h>
Public Member Functions
BytecodeArrayRandomIterator (Handle< BytecodeArray > bytecode_array, Zone *zone)
BytecodeArrayRandomIterator (const BytecodeArrayRandomIterator &)=delete
BytecodeArrayRandomIterator & operator= (const BytecodeArrayRandomIterator &)=delete
BytecodeArrayRandomIterator & operator++ ()
BytecodeArrayRandomIterator & operator-- ()
BytecodeArrayRandomIterator & operator+= (int offset)
BytecodeArrayRandomIterator & operator-= (int offset)
int current_index () const
int size () const
void GoToIndex (int index)
void GoToStart ()
void GoToEnd ()
bool IsValid () const
Private Member Functions
void Initialize ()
void UpdateOffsetFromIndex ()
Private Attributes
ZoneVector< int > offsets_
int current_index_
Additional Inherited Members
Detailed Description
Definition at line 18 of file bytecode-array-random-iterator.h.
Constructor & Destructor Documentation
BytecodeArrayRandomIterator() [1/2]
v8::internal::interpreter::BytecodeArrayRandomIterator::BytecodeArrayRandomIterator (Handle< BytecodeArray > bytecode_array, Zone * zone)
Definition at line 13 of file bytecode-array-random-iterator.cc.
    : BytecodeArrayIterator(bytecode_array, 0), offsets_(zone) {
  offsets_.reserve(bytecode_array->length() / 2);
  Initialize();
}
References v8::internal::interpreter::BytecodeArrayIterator::bytecode_array(), Initialize(), offsets_, and v8::internal::ZoneVector< T >::reserve().
BytecodeArrayRandomIterator() [2/2]
v8::internal::interpreter::BytecodeArrayRandomIterator::BytecodeArrayRandomIterator (const BytecodeArrayRandomIterator &) [delete]
Member Function Documentation
current_index()
int v8::internal::interpreter::BytecodeArrayRandomIterator::current_index () const [inline]
Definition at line 50 of file bytecode-array-random-iterator.h.
{ return current_index_; }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
GoToEnd()
void v8::internal::interpreter::BytecodeArrayRandomIterator::GoToEnd () [inline]
Definition at line 62 of file bytecode-array-random-iterator.h.
                 {
    current_index_ = size() - 1;
    UpdateOffsetFromIndex();
  }
References size().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
GoToIndex()
void v8::internal::interpreter::BytecodeArrayRandomIterator::GoToIndex (int index) [inline]
Definition at line 54 of file bytecode-array-random-iterator.h.
                            {
    current_index_ = index;
    UpdateOffsetFromIndex();
  }
References v8::internal::index.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
GoToStart()
void v8::internal::interpreter::BytecodeArrayRandomIterator::GoToStart () [inline]
Definition at line 58 of file bytecode-array-random-iterator.h.
                   {
    current_index_ = 0;
    UpdateOffsetFromIndex();
  }
Referenced by Initialize().
Initialize()
void v8::internal::interpreter::BytecodeArrayRandomIterator::Initialize () [private]
Definition at line 20 of file bytecode-array-random-iterator.cc.
                                             {
  // Run forwards through the bytecode array to determine the offset of each
  // bytecode.
  while (!done()) {
    offsets_.push_back(current_offset());
    Advance();
  }
  GoToStart();
}
References v8::internal::interpreter::BytecodeArrayIterator::Advance(), v8::internal::interpreter::BytecodeArrayIterator::current_offset(), v8::internal::interpreter::BytecodeArrayIterator::done(), GoToStart(), offsets_, and v8::internal::ZoneVector< T >::push_back().
Referenced by BytecodeArrayRandomIterator().
IsValid()
bool v8::internal::interpreter::BytecodeArrayRandomIterator::IsValid () const
Definition at line 30 of file bytecode-array-random-iterator.cc.
                                                {
  return current_index_ >= 0 &&
         static_cast<size_t>(current_index_) < offsets_.size();
}
References current_index_, offsets_, and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), and UpdateOffsetFromIndex().
operator++()
BytecodeArrayRandomIterator& v8::internal::interpreter::BytecodeArrayRandomIterator::operator++ () [inline]
Definition at line 27 of file bytecode-array-random-iterator.h.
                                            {
    ++current_index_;
    UpdateOffsetFromIndex();
    return *this;
  }
operator+=()
BytecodeArrayRandomIterator& v8::internal::interpreter::BytecodeArrayRandomIterator::operator+= (int offset) [inline]
Definition at line 38 of file bytecode-array-random-iterator.h.
                                                      {
    current_index_ += offset;
    UpdateOffsetFromIndex();
    return *this;
  }
operator--()
BytecodeArrayRandomIterator& v8::internal::interpreter::BytecodeArrayRandomIterator::operator-- () [inline]
Definition at line 32 of file bytecode-array-random-iterator.h.
                                            {
    --current_index_;
    UpdateOffsetFromIndex();
    return *this;
  }
operator-=()
BytecodeArrayRandomIterator& v8::internal::interpreter::BytecodeArrayRandomIterator::operator-= (int offset) [inline]
Definition at line 44 of file bytecode-array-random-iterator.h.
                                                      {
    current_index_ -= offset;
    UpdateOffsetFromIndex();
    return *this;
  }
operator=()
BytecodeArrayRandomIterator& v8::internal::interpreter::BytecodeArrayRandomIterator::operator= (const BytecodeArrayRandomIterator &) [delete]
size()
int v8::internal::interpreter::BytecodeArrayRandomIterator::size () const [inline]
Definition at line 52 of file bytecode-array-random-iterator.h.
{ return static_cast<int>(offsets_.size()); }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
UpdateOffsetFromIndex()
void v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex () [private]
Definition at line 35 of file bytecode-array-random-iterator.cc.
                                                        {
  if (IsValid()) {
    SetOffsetUnchecked(offsets_[current_index_]);
  }
}
References current_index_, IsValid(), offsets_, and v8::internal::interpreter::BytecodeArrayIterator::SetOffsetUnchecked().
Member Data Documentation
current_index_
int v8::internal::interpreter::BytecodeArrayRandomIterator::current_index_ [private]
Definition at line 71 of file bytecode-array-random-iterator.h.
Referenced by IsValid(), and UpdateOffsetFromIndex().
offsets_
ZoneVector<int> v8::internal::interpreter::BytecodeArrayRandomIterator::offsets_ [private]
Definition at line 70 of file bytecode-array-random-iterator.h.
Referenced by BytecodeArrayRandomIterator(), Initialize(), IsValid(), and UpdateOffsetFromIndex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-array-random-iterator.h
/mnt/V8SourceCode/src/interpreter/bytecode-array-random-iterator.cc