v8::CTypeInfoBuilder< T, Flags > Class Template Reference
#include <v8-fast-api-calls.h>
Public Types
using BaseType = T
Static Public Member Functions
static constexpr CTypeInfo Build ()
Static Private Member Functions
template<typename... Rest>
static constexpr CTypeInfo::Flags MergeFlags (CTypeInfo::Flags flags, Rest... rest)
static constexpr CTypeInfo::Flags MergeFlags ()
Detailed Description
template<typename T, CTypeInfo::Flags... Flags>
class v8::CTypeInfoBuilder< T, Flags >
Definition at line 635 of file v8-fast-api-calls.h.
Member Typedef Documentation
BaseType
template<typename T , CTypeInfo::Flags... Flags>
using v8::CTypeInfoBuilder< T, Flags >::BaseType = T
Definition at line 637 of file v8-fast-api-calls.h.
Member Function Documentation
Build()
template<typename T , CTypeInfo::Flags... Flags>
static constexpr CTypeInfo v8::CTypeInfoBuilder< T, Flags >::Build () [inline], [static], [constexpr]
Definition at line 639 of file v8-fast-api-calls.h.
                                     {
    constexpr CTypeInfo::Flags kFlags =
        MergeFlags(internal::TypeInfoHelper<T>::Flags(), Flags...);
    constexpr CTypeInfo::Type kType = internal::TypeInfoHelper<T>::Type();
    STATIC_ASSERT_IMPLIES(
        uint8_t(kFlags) & uint8_t(CTypeInfo::Flags::kEnforceRangeBit),
        CTypeInfo::IsIntegralType(kType),
        "kEnforceRangeBit is only allowed for integral types.");
    STATIC_ASSERT_IMPLIES(
        uint8_t(kFlags) & uint8_t(CTypeInfo::Flags::kClampBit),
        CTypeInfo::IsIntegralType(kType),
        "kClampBit is only allowed for integral types.");
    STATIC_ASSERT_IMPLIES(
        uint8_t(kFlags) & uint8_t(CTypeInfo::Flags::kIsRestrictedBit),
        CTypeInfo::IsFloatingPointType(kType),
        "kIsRestrictedBit is only allowed for floating point types.");
    // Return the same type with the merged flags.
    return CTypeInfo(internal::TypeInfoHelper<T>::Type(), kFlags);
  }
References v8::internal::Flags(), v8::CTypeInfo::IsFloatingPointType(), v8::CTypeInfo::IsIntegralType(), v8::CTypeInfo::kClampBit, v8::CTypeInfo::kEnforceRangeBit, v8::CTypeInfo::kIsRestrictedBit, and STATIC_ASSERT_IMPLIES.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback().
MergeFlags() [1/2]
template<typename T , CTypeInfo::Flags... Flags>
static constexpr CTypeInfo::Flags v8::CTypeInfoBuilder< T, Flags >::MergeFlags () [inline], [static], [constexpr], [private]
Definition at line 667 of file v8-fast-api-calls.h.
{ return CTypeInfo::Flags(0); }
MergeFlags() [2/2]
template<typename T , CTypeInfo::Flags... Flags>
template<typename... Rest>
static constexpr CTypeInfo::Flags v8::CTypeInfoBuilder< T, Flags >::MergeFlags (CTypeInfo::Flags flags, Rest... rest) [inline], [static], [constexpr], [private]
Definition at line 663 of file v8-fast-api-calls.h.
                                                             {
    return CTypeInfo::Flags(uint8_t(flags) | uint8_t(MergeFlags(rest...)));
  }
References flags().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-fast-api-calls.h