v8::internal::AstBigInt Class Reference
#include <ast-value-factory.h>
Public Member Functions
AstBigInt (const char *bigint)
const char * c_str () const
Private Attributes
const char * bigint_
Detailed Description
Definition at line 211 of file ast-value-factory.h.
Constructor & Destructor Documentation
AstBigInt()
v8::internal::AstBigInt::AstBigInt (const char * bigint) [inline], [explicit]
Definition at line 216 of file ast-value-factory.h.
: bigint_(bigint) {}
Member Function Documentation
c_str()
const char* v8::internal::AstBigInt::c_str () const [inline]
Definition at line 218 of file ast-value-factory.h.
{ return bigint_; }
References bigint_.
Referenced by v8::internal::Literal::BuildValue(), v8::internal::interpreter::ConstantArrayBuilder::Insert(), and v8::internal::interpreter::ConstantArrayBuilder::Entry::ToHandle().
Member Data Documentation
bigint_
const char* v8::internal::AstBigInt::bigint_ [private]
Definition at line 221 of file ast-value-factory.h.
Referenced by c_str().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-value-factory.h