v8::internal::EhFrameIterator Class Reference
#include <eh-frame.h>
Public Member Functions
EhFrameIterator (const uint8_t *start, const uint8_t *end)
void SkipCie ()
void SkipToFdeDirectives ()
void Skip (int how_many)
uint32_t GetNextUInt32 ()
uint16_t GetNextUInt16 ()
uint8_t GetNextByte ()
EhFrameConstants::DwarfOpcodes GetNextOpcode ()
uint32_t GetNextULeb128 ()
int32_t GetNextSLeb128 ()
bool Done () const
int GetCurrentOffset () const
int GetBufferSize ()
const void * current_address () const
Private Member Functions
template<typename T >
T GetNextValue ()
Static Private Member Functions
static uint32_t DecodeULeb128 (const uint8_t *encoded, int *encoded_size)
static int32_t DecodeSLeb128 (const uint8_t *encoded, int *encoded_size)
Private Attributes
const uint8_t * start_
const uint8_t * next_
const uint8_t * end_
Static Private Attributes
static const int kDirectivesOffsetInFde = 4 * kInt32Size + 1
Detailed Description
Definition at line 213 of file eh-frame.h.
Constructor & Destructor Documentation
EhFrameIterator()
v8::internal::EhFrameIterator::EhFrameIterator (const uint8_t * start, const uint8_t * end) [inline]
Definition at line 215 of file eh-frame.h.
      : start_(start), next_(start), end_(end) {
    DCHECK_LE(start, end);
  }
References DCHECK_LE, and v8::internal::compiler::end().
Member Function Documentation
current_address()
const void* v8::internal::EhFrameIterator::current_address () const [inline]
Definition at line 261 of file eh-frame.h.
                                      {
    return reinterpret_cast<const void*>(next_);
  }
DecodeSLeb128()
int32_t v8::internal::EhFrameIterator::DecodeSLeb128 (const uint8_t * encoded, int * encoded_size) [static], [private]
Definition at line 440 of file eh-frame.cc.
                                                          {
  static const uint8_t kSignBitMask = 0x40;
  const uint8_t* current = encoded;
  int32_t result = 0;
  int shift = 0;
  uint8_t chunk;
  do {
    chunk = *current++;
    DCHECK_LT(shift, 8 * static_cast<int>(sizeof(result)));
    result |= (chunk & 0x7F) << shift;
    shift += 7;
  } while (chunk >= 128);
  // Sign extend the result if the last chunk has the sign bit set.
  if (chunk & kSignBitMask) result |= (~0ull) << shift;
  DCHECK_NOT_NULL(encoded_size);
  *encoded_size = static_cast<int>(current - encoded);
  return result;
}
References DCHECK_LT, DCHECK_NOT_NULL, and v8::base::internal::result.
Referenced by GetNextSLeb128().
DecodeULeb128()
uint32_t v8::internal::EhFrameIterator::DecodeULeb128 (const uint8_t * encoded, int * encoded_size) [static], [private]
Definition at line 421 of file eh-frame.cc.
                                                           {
  const uint8_t* current = encoded;
  uint32_t result = 0;
  int shift = 0;
  do {
    DCHECK_LT(shift, 8 * static_cast<int>(sizeof(result)));
    result |= (*current & 0x7F) << shift;
    shift += 7;
  } while (*current++ >= 128);
  DCHECK_NOT_NULL(encoded_size);
  *encoded_size = static_cast<int>(current - encoded);
  return result;
}
References DCHECK_LT, DCHECK_NOT_NULL, and v8::base::internal::result.
Referenced by GetNextULeb128().
Done()
bool v8::internal::EhFrameIterator::Done () const [inline]
Definition at line 249 of file eh-frame.h.
                    {
    DCHECK_LE(next_, end_);
    return next_ == end_;
  }
References DCHECK_LE.
GetBufferSize()
int v8::internal::EhFrameIterator::GetBufferSize () [inline]
Definition at line 259 of file eh-frame.h.
{ return static_cast<int>(end_ - start_); }
GetCurrentOffset()
int v8::internal::EhFrameIterator::GetCurrentOffset () const [inline]
Definition at line 254 of file eh-frame.h.
                               {
    DCHECK_GE(next_, start_);
    return static_cast<int>(next_ - start_);
  }
References DCHECK_GE.
GetNextByte()
uint8_t v8::internal::EhFrameIterator::GetNextByte () [inline]
Definition at line 241 of file eh-frame.h.
{ return GetNextValue<uint8_t>(); }
GetNextOpcode()
EhFrameConstants::DwarfOpcodes v8::internal::EhFrameIterator::GetNextOpcode () [inline]
Definition at line 242 of file eh-frame.h.
                                               {
    return static_cast<EhFrameConstants::DwarfOpcodes>(GetNextByte());
  }
GetNextSLeb128()
int32_t v8::internal::EhFrameIterator::GetNextSLeb128 ()
Definition at line 412 of file eh-frame.cc.
                                        {
  int size = 0;
  int32_t result = DecodeSLeb128(next_, &size);
  DCHECK_LE(next_ + size, end_);
  next_ += size;
  return result;
}
References DCHECK_LE, DecodeSLeb128(), end_, next_, v8::base::internal::result, and size().
GetNextUInt16()
uint16_t v8::internal::EhFrameIterator::GetNextUInt16 () [inline]
Definition at line 240 of file eh-frame.h.
{ return GetNextValue<uint16_t>(); }
GetNextUInt32()
uint32_t v8::internal::EhFrameIterator::GetNextUInt32 () [inline]
Definition at line 239 of file eh-frame.h.
{ return GetNextValue<uint32_t>(); }
GetNextULeb128()
uint32_t v8::internal::EhFrameIterator::GetNextULeb128 ()
Definition at line 404 of file eh-frame.cc.
                                         {
  int size = 0;
  uint32_t result = DecodeULeb128(next_, &size);
  DCHECK_LE(next_ + size, end_);
  next_ += size;
  return result;
}
References DCHECK_LE, DecodeULeb128(), end_, next_, v8::base::internal::result, and size().
GetNextValue()
template<typename T >
T v8::internal::EhFrameIterator::GetNextValue () [inline], [private]
Definition at line 272 of file eh-frame.h.
                   {
    T result;
    DCHECK_LE(next_ + sizeof(result), end_);
    result = base::ReadUnalignedValue<T>(reinterpret_cast<Address>(next_));
    next_ += sizeof(result);
    return result;
  }
References DCHECK_LE, and v8::base::internal::result.
Skip()
void v8::internal::EhFrameIterator::Skip (int how_many) [inline]
Definition at line 233 of file eh-frame.h.
                          {
    DCHECK_GE(how_many, 0);
    next_ += how_many;
    DCHECK_LE(next_, end_);
  }
References DCHECK_GE, and DCHECK_LE.
SkipCie()
void v8::internal::EhFrameIterator::SkipCie () [inline]
Definition at line 220 of file eh-frame.h.
                 {
    DCHECK_EQ(next_, start_);
    next_ +=
        base::ReadUnalignedValue<uint32_t>(reinterpret_cast<Address>(next_)) +
        kInt32Size;
  }
References DCHECK_EQ, and v8::internal::kInt32Size.
SkipToFdeDirectives()
void v8::internal::EhFrameIterator::SkipToFdeDirectives () [inline]
Definition at line 227 of file eh-frame.h.
                             {
    SkipCie();
    // Skip the FDE header.
    Skip(kDirectivesOffsetInFde);
  }
Member Data Documentation
end_
const uint8_t* v8::internal::EhFrameIterator::end_ [private]
Definition at line 282 of file eh-frame.h.
Referenced by GetNextSLeb128(), and GetNextULeb128().
kDirectivesOffsetInFde
const int v8::internal::EhFrameIterator::kDirectivesOffsetInFde = 4 * kInt32Size + 1 [static], [private]
Definition at line 266 of file eh-frame.h.
next_
const uint8_t* v8::internal::EhFrameIterator::next_ [private]
Definition at line 281 of file eh-frame.h.
Referenced by GetNextSLeb128(), and GetNextULeb128().
start_
const uint8_t* v8::internal::EhFrameIterator::start_ [private]
Definition at line 280 of file eh-frame.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/eh-frame.h
/mnt/V8SourceCode/src/diagnostics/eh-frame.cc