v8::internal::ScavengeVisitor Class Reference
#include <scavenger-inl.h>
Public Member Functions
ScavengeVisitor (Scavenger *scavenger)
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
size_t VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > object, MaybeObjectSize)
size_t VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize)
size_t VisitJSApiObject (Tagged< Map > map, Tagged< JSObject > object, MaybeObjectSize)
size_t VisitCppHeapExternalObject (Tagged< Map > map, Tagged< CppHeapExternalObject > object, MaybeObjectSize)
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot)
Static Public Member Functions
static constexpr bool CanEncounterFillerOrFreeSpace ()
template<typename T >
static Tagged< T > Cast (Tagged< HeapObject > object, const Heap *heap)
Private Member Functions
template<typename TSlot >
void VisitHeapObjectImpl (TSlot slot, Tagged< HeapObject > heap_object)
template<typename TSlot >
void VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end)
Private Attributes
Scavenger *const scavenger_
Additional Inherited Members
Detailed Description
Definition at line 447 of file scavenger-inl.h.
Constructor & Destructor Documentation
ScavengeVisitor()
v8::internal::ScavengeVisitor::ScavengeVisitor (Scavenger * scavenger) [explicit]
Definition at line 1507 of file scavenger.cc.
    : NewSpaceVisitor<ScavengeVisitor>(scavenger->heap()->isolate()),
      scavenger_(scavenger) {}
Member Function Documentation
CanEncounterFillerOrFreeSpace()
static constexpr bool v8::internal::ScavengeVisitor::CanEncounterFillerOrFreeSpace () [inline], [static], [constexpr]
Definition at line 469 of file scavenger-inl.h.
                                                                  {
    return false;
  }
Cast()
template<typename T >
static Tagged<T> v8::internal::ScavengeVisitor::Cast (Tagged< HeapObject > object, const Heap * heap) [inline], [static]
Definition at line 474 of file scavenger-inl.h.
                                                                               {
    return GCSafeCast<T>(object, heap);
  }
VisitCppHeapExternalObject()
size_t v8::internal::ScavengeVisitor::VisitCppHeapExternalObject (Tagged< Map > map, Tagged< CppHeapExternalObject > object, MaybeObjectSize) [inline]
Definition at line 546 of file scavenger-inl.h.
                                                                            {
  int size = CppHeapExternalObject::BodyDescriptor::SizeOf(map, object);
  CppHeapExternalObject::BodyDescriptor::IterateBody(map, object, size, this);
  return size;
}
References v8::internal::CppHeapExternalObject::BodyDescriptor::IterateBody(), size(), and v8::internal::CppHeapExternalObject::BodyDescriptor::SizeOf().
VisitEphemeronHashTable()
size_t v8::internal::ScavengeVisitor::VisitEphemeronHashTable (Tagged< Map > map, Tagged< EphemeronHashTable > object, MaybeObjectSize) [inline]
Definition at line 571 of file scavenger-inl.h.
                                                                        {
  // Register table with the scavenger, so it can take care of the weak keys
  // later. This allows to only iterate the tables' values, which are treated
  // as strong independently of whether the key is live.
  scavenger_->AddEphemeronHashTable(table);
  for (InternalIndex i : table->IterateEntries()) {
    ObjectSlot value_slot =
        table->RawFieldOfElementAt(EphemeronHashTable::EntryToValueIndex(i));
    VisitPointer(table, value_slot);
  }
  return table->SizeFromMap(map);
}
References v8::internal::Scavenger::AddEphemeronHashTable(), scavenger_, and v8::internal::ObjectVisitor::VisitPointer().
VisitExternalPointer()
void v8::internal::ScavengeVisitor::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 553 of file scavenger-inl.h.
                                                                     {
#ifdef V8_COMPRESS_POINTERS
  DCHECK(!slot.tag_range().IsEmpty());
  DCHECK(!IsSharedExternalPointerType(slot.tag_range()));
  DCHECK(HeapLayout::InYoungGeneration(host));
  // TODO(chromium:337580006): Remove when pointer compression always uses
  // EPT.
  if (!slot.HasExternalPointerHandle()) return;
  ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
  Heap* heap = scavenger_->heap();
  ExternalPointerTable& table = heap->isolate()->external_pointer_table();
  table.Mark(heap->young_external_pointer_space(), handle, slot.address());
#endif // V8_COMPRESS_POINTERS
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::Scavenger::heap(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::TagRange< Tag >::IsEmpty(), v8::internal::IsSharedExternalPointerType(), scavenger_, and v8::internal::ExternalPointerSlot::tag_range().
VisitHeapObjectImpl()
template<typename TSlot >
void v8::internal::ScavengeVisitor::VisitHeapObjectImpl (TSlot slot, Tagged< HeapObject > heap_object) [inline], [private]
Definition at line 502 of file scavenger-inl.h.
                                                                          {
  if (HeapLayout::InYoungGeneration(heap_object)) {
    using THeapObjectSlot = typename TSlot::THeapObjectSlot;
    scavenger_->ScavengeObject(THeapObjectSlot(slot), heap_object);
  }
}
References v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Scavenger::ScavengeObject(), and scavenger_.
Referenced by VisitPointersImpl().
VisitJSApiObject()
size_t v8::internal::ScavengeVisitor::VisitJSApiObject (Tagged< Map > map, Tagged< JSObject > object, MaybeObjectSize) [inline]
Definition at line 537 of file scavenger-inl.h.
                                                          {
  int size = JSAPIObjectWithEmbedderSlots::BodyDescriptor::SizeOf(map, object);
  JSAPIObjectWithEmbedderSlots::BodyDescriptor::IterateBody(map, object, size,
                                                            this);
  return size;
}
References v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor::IterateBody(), size(), and v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor::SizeOf().
VisitJSArrayBuffer()
size_t v8::internal::ScavengeVisitor::VisitJSArrayBuffer (Tagged< Map > map, Tagged< JSArrayBuffer > object, MaybeObjectSize) [inline]
Definition at line 528 of file scavenger-inl.h.
                                                            {
  object->YoungMarkExtension();
  int size = JSArrayBuffer::BodyDescriptor::SizeOf(map, object);
  JSArrayBuffer::BodyDescriptor::IterateBody(map, object, size, this);
  return size;
}
References v8::internal::JSArrayBuffer::BodyDescriptor::IterateBody(), size(), and v8::internal::JSArrayBuffer::BodyDescriptor::SizeOf().
VisitPointers() [1/2]
void v8::internal::ScavengeVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 495 of file scavenger-inl.h.
                                                         {
  return VisitPointersImpl(host, start, end);
}
References v8::internal::compiler::end(), and VisitPointersImpl().
VisitPointers() [2/2]
void v8::internal::ScavengeVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 490 of file scavenger-inl.h.
                                                    {
  return VisitPointersImpl(host, start, end);
}
References v8::internal::compiler::end(), and VisitPointersImpl().
VisitPointersImpl()
template<typename TSlot >
void v8::internal::ScavengeVisitor::VisitPointersImpl (Tagged< HeapObject > host, TSlot start, TSlot end) [inline], [private]
Definition at line 511 of file scavenger-inl.h.
                                                   {
  for (TSlot slot = start; slot < end; ++slot) {
    const std::optional<Tagged<Object>> optional_object =
        this->GetObjectFilterReadOnlyAndSmiFast(slot);
    if (!optional_object) {
      continue;
    }
    typename TSlot::TObject object = *optional_object;
    Tagged<HeapObject> heap_object;
    // Treat weak references as strong.
    if (object.GetHeapObject(&heap_object)) {
      VisitHeapObjectImpl(slot, heap_object);
    }
  }
}
References v8::internal::compiler::end(), v8::internal::HeapVisitor< ConcreteVisitor >::GetObjectFilterReadOnlyAndSmiFast(), and VisitHeapObjectImpl().
Referenced by VisitPointers().
Member Data Documentation
scavenger_
Scavenger* const v8::internal::ScavengeVisitor::scavenger_ [private]
Definition at line 487 of file scavenger-inl.h.
Referenced by VisitEphemeronHashTable(), VisitExternalPointer(), and VisitHeapObjectImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger-inl.h
/mnt/V8SourceCode/src/heap/scavenger.cc