v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character > Class Template Reference
Classes
class InterpreterThread
class LastInputIndex
struct Lookaround
Public Member Functions
NfaInterpreter (Isolate *isolate, RegExp::CallOrigin call_origin, Tagged< TrustedByteArray > bytecode, int register_count_per_match, Tagged< String > input, int32_t input_index, Zone *zone)
int FindMatches (int32_t *output_registers, int output_register_count)
Private Member Functions
V8_WARN_UNUSED_RESULT int FillLookaroundTable ()
V8_WARN_UNUSED_RESULT int FillLookaroundCaptures (InterpreterThread &main_thread)
V8_WARN_UNUSED_RESULT int RunActiveThreadsToEnd ()
V8_WARN_UNUSED_RESULT int HandleInterrupts ()
void SetInputIndex (int new_input_index)
int FindNextMatch ()
int RunActiveThread (InterpreterThread t)
int RunActiveThreads ()
void FlushBlockedThreads (base::uc16 input_char)
bool FoundMatch () const
size_t ApproximateTotalMemoryUsage ()
int CheckMemoryConsumption ()
base::Vector< int > GetRegisterArray (InterpreterThread t)
base::Vector< int > GetLookaroundMatchIndexArray (InterpreterThread t)
base::Vector< uint64_t > GetQuantifierClockArray (InterpreterThread t)
base::Vector< uint64_t > GetCaptureClockArray (InterpreterThread t)
base::Vector< uint64_t > GetLookaroundClockArray (InterpreterThread t)
int * NewRegisterArrayUninitialized ()
int * NewRegisterArray (int fill_value)
void FreeRegisterArray (int *register_array_begin)
int * NewLookaroundMatchIndexArrayUninitialized ()
int * NewLookaroundMatchIndexArray (int fill_value)
void FreeLookaroundMatchIndexArray (int *lookaround_match_index_array_begin)
uint64_t * NewQuantifierClockArrayUninitialized ()
uint64_t * NewQuantifierClockArray (uint64_t fill_value)
void FreeQuantifierClockArray (uint64_t *quantifier_clock_array_begin)
uint64_t * NewCaptureClockArrayUninitialized ()
uint64_t * NewCaptureClockArray (uint64_t fill_value)
void FreeCaptureClockArray (uint64_t *capture_clock_array_begin)
uint64_t * NewLookaroundClockArrayUninitialized ()
uint64_t * NewLookaroundClockArray (uint64_t fill_value)
void FreeLookaroundClockArray (uint64_t *lookaround_clock_array_begin)
InterpreterThread NewEmptyThread (int pc)
InterpreterThread NewUninitializedThread (int pc)
V8_WARN_UNUSED_RESULT int GetFilteredRegisters (InterpreterThread main_thread, base::Vector< int > &filtered_registers)
void DestroyThread (InterpreterThread t)
bool IsPcProcessed (int pc, typename InterpreterThread::ConsumedCharacter consumed_since_last_quantifier)
void MarkPcProcessed (int pc, typename InterpreterThread::ConsumedCharacter consumed_since_last_quantifier)
Private Attributes
Isolate *const isolate_
const RegExp::CallOrigin call_origin_
DisallowGarbageCollection no_gc_
Tagged< TrustedByteArray > bytecode_object_
base::Vector< const RegExpInstruction > bytecode_
const int register_count_per_match_
int quantifier_count_
Tagged< String > input_object_
base::Vector< const Character > input_
int input_index_
uint64_t clock
base::Vector< LastInputIndex > pc_last_input_index_
ZoneList< InterpreterThread > active_threads_
ZoneList< InterpreterThread > blocked_threads_
RecyclingZoneAllocator< int > register_array_allocator_
std::optional< RecyclingZoneAllocator< int > > lookaround_match_index_array_allocator_
std::optional< RecyclingZoneAllocator< uint64_t > > lookaround_clock_array_allocator_
std::optional< RecyclingZoneAllocator< uint64_t > > quantifier_array_allocator_
std::optional< RecyclingZoneAllocator< uint64_t > > capture_clock_array_allocator_
std::optional< InterpreterThread > best_match_thread_
ZoneList< Lookaround > lookarounds_
std::optional< ZoneVector< ZoneVector< bool > > > lookaround_table_
std::optional< ZoneList< bool > > lookbehind_table_
bool only_captureless_lookbehinds_
bool reverse_
int current_lookaround_
std::optional< int > filter_groups_pc_
uint64_t memory_consumption_per_thread_
Zone * zone_
Detailed Description
template<class Character>
class v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >
Definition at line 241 of file experimental-interpreter.cc.
Constructor & Destructor Documentation
NfaInterpreter()
template<class Character >
v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NfaInterpreter (Isolate * isolate, RegExp::CallOrigin call_origin, Tagged< TrustedByteArray > bytecode, int register_count_per_match, Tagged< String > input, int32_t input_index, Zone * zone) [inline]
Definition at line 336 of file experimental-interpreter.cc.
      : isolate_(isolate),
        call_origin_(call_origin),
        bytecode_object_(bytecode),
        bytecode_(ToInstructionVector(bytecode, no_gc_)),
        register_count_per_match_(register_count_per_match),
        quantifier_count_(0),
        input_object_(input),
        input_(ToCharacterVector<Character>(input, no_gc_)),
        input_index_(input_index),
        clock(0),
        pc_last_input_index_(
            zone->AllocateArray<LastInputIndex>(bytecode->length()),
            bytecode->length()),
        active_threads_(0, zone),
        blocked_threads_(0, zone),
        register_array_allocator_(zone),
        lookaround_match_index_array_allocator_(std::nullopt),
        lookaround_clock_array_allocator_(std::nullopt),
        quantifier_array_allocator_(std::nullopt),
        capture_clock_array_allocator_(std::nullopt),
        best_match_thread_(std::nullopt),
        lookarounds_(0, zone),
        lookaround_table_(std::nullopt),
        lookbehind_table_(std::nullopt),
        only_captureless_lookbehinds_(true),
        reverse_(false),
        current_lookaround_(-1),
        filter_groups_pc_(std::nullopt),
        zone_(zone) {
    DCHECK(!bytecode_.empty());
    DCHECK_GE(input_index_, 0);
    DCHECK_LE(input_index_, input_.length());
    // Iterate over the bytecode to find the PC of the filtering
    // instructions and lookarounds, and the number of quantifiers.
    std::optional<struct Lookaround> lookaround;
    bool in_lookaround = false;
    int lookaround_index;
    for (int i = 0; i < bytecode_.length() - 1; ++i) {
      auto& inst = bytecode_[i];
      if (inst.opcode == RegExpInstruction::START_LOOKAROUND) {
        DCHECK(!lookaround.has_value());
        in_lookaround = true;
        // Stores the partial information for a lookaround. The rest will be
        // determined upon reaching a `WRITE_LOOKAROUND_TABLE` instruction.
        lookaround_index = inst.payload.lookaround.index();
        lookaround = Lookaround{.match_pc = i,
                                .capture_pc = -1,
                                .type = inst.payload.lookaround.type()};
        if (inst.payload.lookaround.type() ==
            RegExpLookaround::Type::LOOKAHEAD) {
          only_captureless_lookbehinds_ = false;
        }
      }
      if (inst.opcode == RegExpInstruction::SET_REGISTER_TO_CP &&
          in_lookaround) {
        only_captureless_lookbehinds_ = false;
      }
      if (inst.opcode == RegExpInstruction::WRITE_LOOKAROUND_TABLE) {
        DCHECK(lookaround.has_value());
        // Fills the current lookaround data.
        lookaround->capture_pc = i + 1;
        // Since the lookarounds are not in order in the `lookarounds_` array,
        // we first fill it until it has the correct size.
        while (lookarounds_.length() <= lookaround_index) {
          lookarounds_.Add({-1, -1, RegExpLookaround::Type::LOOKBEHIND}, zone_);
        }
        lookarounds_.Set(lookaround_index, *lookaround);
        lookaround = {};
      }
      if (inst.opcode == RegExpInstruction::END_LOOKAROUND) {
        in_lookaround = false;
      }
      // The first `FILTER_*` instruction encountered is the start of the
      // `FILTER_*` section.
      if (!filter_groups_pc_.has_value() && RegExpInstruction::IsFilter(inst)) {
        DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
        filter_groups_pc_ = i;
      }
      if (inst.opcode == RegExpInstruction::SET_QUANTIFIER_TO_CLOCK) {
        DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
        quantifier_count_ =
            std::max(quantifier_count_, inst.payload.quantifier_id + 1);
      }
    }
    // Iniitializes the lookaround truth table and required allocators.
    if (only_captureless_lookbehinds_) {
      lookbehind_table_.emplace(lookarounds_.length(), zone_);
      lookbehind_table_->AddBlock(false, lookarounds_.length(), zone_);
    } else {
      DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
      lookaround_clock_array_allocator_.emplace(zone_);
      lookaround_match_index_array_allocator_.emplace(zone_);
      lookaround_table_.emplace(zone_);
      for (int i = lookarounds_.length() - 1; i >= 0; --i) {
        lookaround_table_->emplace_back(input_.length() + 1, zone_);
      }
    }
    // Precomputes the memory consumption of a single thread, to be used by
    // `CheckMemoryConsumption()`.
    if (v8_flags.experimental_regexp_engine_capture_group_opt) {
      quantifier_array_allocator_.emplace(zone_);
      capture_clock_array_allocator_.emplace(zone_);
      memory_consumption_per_thread_ =
          register_count_per_match_ * sizeof(int) + // RegisterArray
          quantifier_count_ * sizeof(uint64_t) + // QuantifierClockArray
          register_count_per_match_ * sizeof(uint64_t) + // CaptureClockArray
          lookarounds_.length() * sizeof(uint64_t) + // LookaroundClockArray
          lookarounds_.length() * sizeof(int) + // LookaroundMatchIndexArray
          sizeof(InterpreterThread);
    }
    std::fill(pc_last_input_index_.begin(), pc_last_input_index_.end(),
              LastInputIndex());
  }
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::RegExpInstruction::END_LOOKAROUND, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpInstruction::IsFilter(), v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::Lookaround::match_pc, v8::internal::RegExpInstruction::SET_QUANTIFIER_TO_CLOCK, v8::internal::RegExpInstruction::SET_REGISTER_TO_CP, v8::internal::RegExpInstruction::START_LOOKAROUND, v8::internal::v8_flags, and v8::internal::RegExpInstruction::WRITE_LOOKAROUND_TABLE.
Member Function Documentation
ApproximateTotalMemoryUsage()
template<class Character >
size_t v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::ApproximateTotalMemoryUsage () [inline], [private]
Definition at line 1155 of file experimental-interpreter.cc.
                                       {
    return (blocked_threads_.length() + active_threads_.length()) *
           memory_consumption_per_thread_;
  }
CheckMemoryConsumption()
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::CheckMemoryConsumption () [inline], [private]
Definition at line 1162 of file experimental-interpreter.cc.
                               {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    // Copmputes an approximation of the total current memory usage of the
    // intepreter. It is based only on the threads' consumption, since the rest
    // is negligible in comparison.
    uint64_t approx = (blocked_threads_.length() + active_threads_.length()) *
                      memory_consumption_per_thread_;
    return (approx <
            v8_flags.experimental_regexp_engine_capture_group_opt_max_memory_usage *
                MB)
               ? RegExp::kInternalRegExpSuccess
               : RegExp::kInternalRegExpException;
  }
References v8::internal::DCHECK(), v8::internal::RegExp::kInternalRegExpException, v8::internal::RegExp::kInternalRegExpSuccess, v8::internal::MB, and v8::internal::v8_flags.
DestroyThread()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::DestroyThread (InterpreterThread t) [inline], [private]
Definition at line 1381 of file experimental-interpreter.cc.
                                          {
    FreeRegisterArray(t.register_array_begin);
    if (v8_flags.experimental_regexp_engine_capture_group_opt) {
      FreeQuantifierClockArray(t.quantifier_clock_array_begin);
      FreeCaptureClockArray(t.captures_clock_array_begin);
      if (!only_captureless_lookbehinds_) {
        FreeLookaroundClockArray(t.lookaround_clock_array_begin);
        FreeLookaroundMatchIndexArray(t.lookaround_match_index_array_begin);
      }
    }
  }
References v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::captures_clock_array_begin, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::lookaround_clock_array_begin, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::lookaround_match_index_array_begin, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::quantifier_clock_array_begin, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::register_array_begin, and v8::internal::v8_flags.
FillLookaroundCaptures()
template<class Character >
V8_WARN_UNUSED_RESULT int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FillLookaroundCaptures (InterpreterThread & main_thread) [inline], [private]
Definition at line 625 of file experimental-interpreter.cc.
                                      {
    DCHECK(best_match_thread_.has_value());
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK(!only_captureless_lookbehinds_);
    if (lookarounds_.is_empty()) {
      return RegExp::kInternalRegExpSuccess;
    }
    // We need to capture the lookarounds from parents to childrens, since we
    // need the index on which the lookaround was matched, and those indexes are
    // computed when the parent expression is captured.
    for (int i = 0; i < lookarounds_.length(); ++i) {
      if (GetLookaroundMatchIndexArray(main_thread)[i] ==
          kUndefinedMatchIndexValue) {
        continue;
      }
      Lookaround& lookaround = lookarounds_[i];
      std::fill(pc_last_input_index_.begin(), pc_last_input_index_.end(),
                LastInputIndex());
      // Clean up left-over data from last iteration.
      for (InterpreterThread t : blocked_threads_) {
        DestroyThread(t);
      }
      blocked_threads_.Rewind(0);
      for (InterpreterThread t : active_threads_) {
        DestroyThread(t);
      }
      active_threads_.Rewind(0);
      best_match_thread_ = std::nullopt;
      reverse_ = lookaround.type == RegExpLookaround::Type::LOOKBEHIND;
      input_index_ = GetLookaroundMatchIndexArray(main_thread)[i];
      // We reuse the same thread as initial thread, to avoid having to merge
      // the new `best_match_thread_` with the previous results.
      main_thread.pc = lookaround.capture_pc;
      main_thread.consumed_since_last_quantifier =
          InterpreterThread::ConsumedCharacter::DidConsume;
      active_threads_.Add(main_thread, zone_);
      int err_code = RunActiveThreadsToEnd();
      if (err_code != RegExp::kInternalRegExpSuccess) {
        return err_code;
      }
      // The lookaround has already been matched once on this position during
      // the match research.
      DCHECK(best_match_thread_.has_value());
      main_thread = *best_match_thread_;
    }
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::Lookaround::capture_pc, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::consumed_since_last_quantifier, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExp::kInternalRegExpSuccess, v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedMatchIndexValue, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::pc, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::Lookaround::type, and v8::internal::v8_flags.
FillLookaroundTable()
template<class Character >
V8_WARN_UNUSED_RESULT int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FillLookaroundTable () [inline], [private]
Definition at line 580 of file experimental-interpreter.cc.
                                                  {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK(!only_captureless_lookbehinds_);
    if (lookarounds_.is_empty()) {
      return RegExp::kInternalRegExpSuccess;
    }
    std::fill(pc_last_input_index_.begin(), pc_last_input_index_.end(),
              LastInputIndex());
    int old_input_index = input_index_;
    for (int i = lookarounds_.length() - 1; i >= 0; --i) {
      // Clean up left-over data from last iteration.
      for (InterpreterThread t : blocked_threads_) {
        DestroyThread(t);
      }
      blocked_threads_.Rewind(0);
      for (InterpreterThread t : active_threads_) {
        DestroyThread(t);
      }
      active_threads_.Rewind(0);
      current_lookaround_ = i;
      reverse_ = lookarounds_.at(i).type == RegExpLookaround::Type::LOOKAHEAD;
      input_index_ = reverse_ ? input_.length() : 0;
      active_threads_.Add(NewEmptyThread(lookarounds_.at(i).match_pc), zone_);
      int err_code = RunActiveThreadsToEnd();
      if (err_code != RegExp::kInternalRegExpSuccess) {
        return err_code;
      }
    }
    reverse_ = false;
    current_lookaround_ = -1;
    input_index_ = old_input_index;
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExp::kInternalRegExpSuccess, and v8::internal::v8_flags.
FindMatches()
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindMatches (int32_t * output_registers, int output_register_count) [inline]
Definition at line 476 of file experimental-interpreter.cc.
                                                                        {
    const int max_match_num = output_register_count / register_count_per_match_;
    if (!only_captureless_lookbehinds_) {
      int err_code = FillLookaroundTable();
      if (err_code != RegExp::kInternalRegExpSuccess) {
        return err_code;
      }
    }
    int match_num = 0;
    while (match_num != max_match_num) {
      int err_code = FindNextMatch();
      if (err_code != RegExp::kInternalRegExpSuccess) return err_code;
      if (!FoundMatch()) break;
      base::Vector<int> registers;
      err_code = GetFilteredRegisters(*best_match_thread_, registers);
      if (err_code != RegExp::kInternalRegExpSuccess) {
        return err_code;
      }
      output_registers =
          std::copy(registers.begin(), registers.end(), output_registers);
      ++match_num;
      const int match_begin = registers[0];
      const int match_end = registers[1];
      DCHECK_LE(match_begin, match_end);
      const int match_length = match_end - match_begin;
      if (match_length != 0) {
        SetInputIndex(match_end);
      } else if (match_end == input_.length()) {
        // Zero-length match, input exhausted.
        SetInputIndex(match_end);
        break;
      } else {
        // Zero-length match, more input. We don't want to report more matches
        // here endlessly, so we advance by 1.
        SetInputIndex(match_end + 1);
        // TODO(mbid,v8:10765): If we're in unicode mode, we have to advance to
        // the next codepoint, not to the next code unit. See also
        // `RegExpUtils::AdvanceStringIndex`.
        static_assert(!ExperimentalRegExp::kSupportsUnicode);
      }
    }
    return match_num;
  }
References v8::base::Vector< T >::begin(), DCHECK_LE, v8::base::Vector< T >::end(), v8::internal::RegExp::kInternalRegExpSuccess, and v8::internal::ExperimentalRegExp::kSupportsUnicode.
FindNextMatch()
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindNextMatch () [inline], [private]
Definition at line 810 of file experimental-interpreter.cc.
                      {
    DCHECK(active_threads_.is_empty());
    // TODO(mbid,v8:10765): Can we get around resetting `pc_last_input_index_`
    // here? As long as
    //
    // pc_last_input_index_[pc] < input_index_
    //
    // for all possible program counters pc that are reachable without input
    // from pc = 0 and
    //
    // pc_last_input_index_[k] <= input_index_
    //
    // for all k > 0 hold I think everything should be fine. Maybe we can do
    // something about this in `SetInputIndex`.
    std::fill(pc_last_input_index_.begin(), pc_last_input_index_.end(),
              LastInputIndex());
    // Clean up left-over data from a previous call to FindNextMatch.
    for (InterpreterThread t : blocked_threads_) {
      DestroyThread(t);
    }
    blocked_threads_.Rewind(0);
    for (InterpreterThread t : active_threads_) {
      DestroyThread(t);
    }
    active_threads_.Rewind(0);
    if (best_match_thread_.has_value()) {
      DestroyThread(*best_match_thread_);
      best_match_thread_ = std::nullopt;
    }
    active_threads_.Add(NewEmptyThread(0), zone_);
    if (only_captureless_lookbehinds_) {
      for (int i = 0; i < lookarounds_.length(); ++i) {
        active_threads_.Add(NewEmptyThread(lookarounds_.at(i).match_pc), zone_);
      }
    }
    int err_code = RunActiveThreadsToEnd();
    if (err_code != RegExp::kInternalRegExpSuccess) {
      return err_code;
    }
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::RegExp::kInternalRegExpSuccess.
FlushBlockedThreads()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FlushBlockedThreads (base::uc16 input_char) [inline], [private]
Definition at line 1111 of file experimental-interpreter.cc.
                                                {
    // The threads in blocked_threads_ are sorted from high to low priority,
    // but active_threads_ needs to be sorted from low to high priority, so we
    // need to activate blocked threads in reverse order.
    for (int i = blocked_threads_.length() - 1; i >= 0; --i) {
      InterpreterThread t = blocked_threads_[i];
      // Number of ranges to check.
      int32_t ranges = 1;
      // Consume success.
      bool has_matched = false;
      if (bytecode_[t.pc].opcode == RegExpInstruction::RANGE_COUNT) {
        ranges = bytecode_[t.pc].payload.num_ranges;
        ++t.pc;
      }
      // pc of the instruction after all ranges.
      int next_pc = t.pc + ranges;
      // Checking all ranges.
      for (int pc = t.pc; pc < next_pc; ++pc) {
        RegExpInstruction inst = bytecode_[pc];
        DCHECK_EQ(inst.opcode, RegExpInstruction::CONSUME_RANGE);
        RegExpInstruction::Uc16Range range = inst.payload.consume_range;
        if (input_char >= range.min && input_char <= range.max) {
          // The current char matches the current range.
          t.pc = next_pc;
          t.consumed_since_last_quantifier =
              InterpreterThread::ConsumedCharacter::DidConsume;
          has_matched = true;
          break;
        }
      }
      if (has_matched) {
        active_threads_.Add(t, zone_);
      } else {
        DestroyThread(t);
      }
    }
    blocked_threads_.Rewind(0);
  }
References v8::internal::RegExpInstruction::CONSUME_RANGE, v8::internal::RegExpInstruction::consume_range, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::consumed_since_last_quantifier, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpInstruction::Uc16Range::max, v8::internal::RegExpInstruction::Uc16Range::min, v8::internal::RegExpInstruction::opcode, v8::internal::RegExpInstruction::payload, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::pc, and v8::internal::RegExpInstruction::RANGE_COUNT.
FoundMatch()
template<class Character >
bool v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FoundMatch () const [inline], [private]
Definition at line 1153 of file experimental-interpreter.cc.
{ return best_match_thread_.has_value(); }
FreeCaptureClockArray()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FreeCaptureClockArray (uint64_t * capture_clock_array_begin) [inline], [private]
Definition at line 1279 of file experimental-interpreter.cc.
                                                                  {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    capture_clock_array_allocator_->deallocate(capture_clock_array_begin,
                                               register_count_per_match_);
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
FreeLookaroundClockArray()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FreeLookaroundClockArray (uint64_t * lookaround_clock_array_begin) [inline], [private]
Definition at line 1299 of file experimental-interpreter.cc.
                                                                        {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    lookaround_clock_array_allocator_->deallocate(lookaround_clock_array_begin,
                                                  lookaround_table_->size());
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
FreeLookaroundMatchIndexArray()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FreeLookaroundMatchIndexArray (int * lookaround_match_index_array_begin) [inline], [private]
Definition at line 1240 of file experimental-interpreter.cc.
                                                                              {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    lookaround_match_index_array_allocator_->deallocate(
        lookaround_match_index_array_begin, lookaround_table_->size());
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
FreeQuantifierClockArray()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FreeQuantifierClockArray (uint64_t * quantifier_clock_array_begin) [inline], [private]
Definition at line 1260 of file experimental-interpreter.cc.
                                                                        {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    quantifier_array_allocator_->deallocate(quantifier_clock_array_begin,
                                            quantifier_count_);
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
FreeRegisterArray()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FreeRegisterArray (int * register_array_begin) [inline], [private]
Definition at line 1222 of file experimental-interpreter.cc.
                                                    {
    register_array_allocator_.deallocate(register_array_begin,
                                         register_count_per_match_);
  }
GetCaptureClockArray()
template<class Character >
base::Vector<uint64_t> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetCaptureClockArray (InterpreterThread t) [inline], [private]
Definition at line 1196 of file experimental-interpreter.cc.
                                                                 {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK_NOT_NULL(t.captures_clock_array_begin);
    return base::Vector<uint64_t>(t.captures_clock_array_begin,
                                  register_count_per_match_);
  }
References v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::captures_clock_array_begin, v8::internal::DCHECK(), DCHECK_NOT_NULL, and v8::internal::v8_flags.
GetFilteredRegisters()
template<class Character >
V8_WARN_UNUSED_RESULT int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetFilteredRegisters (InterpreterThread main_thread, base::Vector< int > & filtered_registers) [inline], [private]
Definition at line 1348 of file experimental-interpreter.cc.
                                                                          {
    if (!only_captureless_lookbehinds_) {
      int err_code = FillLookaroundCaptures(main_thread);
      if (err_code != RegExp::kInternalRegExpSuccess) {
        return err_code;
      }
    }
    base::Vector<int> registers = GetRegisterArray(main_thread);
    if (filter_groups_pc_.has_value()) {
      filtered_registers = base::Vector<int>(
          NewRegisterArray(kUndefinedRegisterValue), register_count_per_match_);
      filtered_registers[0] = registers[0];
      filtered_registers[1] = registers[1];
      filtered_registers = FilterGroups::Filter(
          *filter_groups_pc_, GetRegisterArray(main_thread),
          GetQuantifierClockArray(main_thread),
          GetCaptureClockArray(main_thread),
          only_captureless_lookbehinds_
              ? std::nullopt
              : std::optional(GetLookaroundClockArray(main_thread)),
          filtered_registers, bytecode_, zone_);
    } else {
      filtered_registers = registers;
    }
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::RegExp::kInternalRegExpSuccess, and v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedRegisterValue.
GetLookaroundClockArray()
template<class Character >
base::Vector<uint64_t> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetLookaroundClockArray (InterpreterThread t) [inline], [private]
Definition at line 1203 of file experimental-interpreter.cc.
                                                                    {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK_NOT_NULL(t.lookaround_clock_array_begin);
    return base::Vector<uint64_t>(t.lookaround_clock_array_begin,
                                  lookaround_table_->size());
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::lookaround_clock_array_begin, and v8::internal::v8_flags.
GetLookaroundMatchIndexArray()
template<class Character >
base::Vector<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetLookaroundMatchIndexArray (InterpreterThread t) [inline], [private]
Definition at line 1181 of file experimental-interpreter.cc.
                                                                    {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK_NOT_NULL(t.lookaround_match_index_array_begin);
    return base::Vector<int>(t.lookaround_match_index_array_begin,
                             lookaround_table_->size());
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::lookaround_match_index_array_begin, and v8::internal::v8_flags.
GetQuantifierClockArray()
template<class Character >
base::Vector<uint64_t> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetQuantifierClockArray (InterpreterThread t) [inline], [private]
Definition at line 1189 of file experimental-interpreter.cc.
                                                                    {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK_NOT_NULL(t.captures_clock_array_begin);
    return base::Vector<uint64_t>(t.quantifier_clock_array_begin,
                                  quantifier_count_);
  }
References v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::captures_clock_array_begin, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::quantifier_clock_array_begin, and v8::internal::v8_flags.
GetRegisterArray()
template<class Character >
base::Vector<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::GetRegisterArray (InterpreterThread t) [inline], [private]
Definition at line 1178 of file experimental-interpreter.cc.
                                                        {
    return base::Vector<int>(t.register_array_begin, register_count_per_match_);
  }
References v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::register_array_begin.
HandleInterrupts()
template<class Character >
V8_WARN_UNUSED_RESULT int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::HandleInterrupts () [inline], [private]
Definition at line 736 of file experimental-interpreter.cc.
                                               {
    StackLimitCheck check(isolate_);
    if (call_origin_ == RegExp::CallOrigin::kFromJs) {
      // Direct calls from JavaScript can be interrupted in two ways:
      // 1. A real stack overflow, in which case we let the caller throw the
      // exception.
      // 2. The stack guard was used to interrupt execution for another purpose,
      // forcing the call through the runtime system.
      if (check.JsHasOverflowed()) {
        return RegExp::kInternalRegExpException;
      } else if (check.InterruptRequested()) {
        return RegExp::kInternalRegExpRetry;
      }
    } else {
      DCHECK(call_origin_ == RegExp::CallOrigin::kFromRuntime);
      HandleScope handles(isolate_);
      DirectHandle<TrustedByteArray> bytecode_handle(bytecode_object_,
                                                     isolate_);
      DirectHandle<String> input_handle(input_object_, isolate_);
      if (check.JsHasOverflowed()) {
        // We abort the interpreter now anyway, so gc can't invalidate any
        // pointers.
        AllowGarbageCollection yes_gc;
        isolate_->StackOverflow();
        return RegExp::kInternalRegExpException;
      } else if (check.InterruptRequested()) {
        // TODO(mbid): Is this really equivalent to whether the string is
        // one-byte or two-byte? A comment at the declaration of
        // IsOneByteRepresentationUnderneath says that this might fail for
        // external strings.
        const bool was_one_byte =
            String::IsOneByteRepresentationUnderneath(input_object_);
        Tagged<Object> result;
        {
          AllowGarbageCollection yes_gc;
          result = isolate_->stack_guard()->HandleInterrupts();
        }
        if (IsException(result, isolate_)) {
          return RegExp::kInternalRegExpException;
        }
        // If we changed between a LATIN1 and a UC16 string, we need to restart
        // regexp matching with the appropriate template instantiation of
        // RawMatch.
        if (String::IsOneByteRepresentationUnderneath(*input_handle) !=
            was_one_byte) {
          return RegExp::kInternalRegExpRetry;
        }
        // Update objects and pointers in case they have changed during gc.
        bytecode_object_ = *bytecode_handle;
        bytecode_ = ToInstructionVector(bytecode_object_, no_gc_);
        input_object_ = *input_handle;
        input_ = ToCharacterVector<Character>(input_object_, no_gc_);
      }
    }
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::DCHECK(), v8::internal::StackLimitCheck::InterruptRequested(), v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::StackLimitCheck::JsHasOverflowed(), v8::internal::RegExp::kInternalRegExpException, v8::internal::RegExp::kInternalRegExpRetry, v8::internal::RegExp::kInternalRegExpSuccess, v8::base::internal::result, and v8::internal::anonymous_namespace{experimental-interpreter.cc}::ToInstructionVector().
IsPcProcessed()
template<class Character >
bool v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::IsPcProcessed (int pc, typename InterpreterThread::ConsumedCharacter consumed_since_last_quantifier) [inline], [private]
Definition at line 1408 of file experimental-interpreter.cc.
                                                                 {
    switch (consumed_since_last_quantifier) {
      case InterpreterThread::ConsumedCharacter::DidConsume:
        return pc_last_input_index_[pc].having_consumed_character ==
               input_index_;
      case InterpreterThread::ConsumedCharacter::DidNotConsume:
        return pc_last_input_index_[pc].not_having_consumed_character ==
               input_index_;
    }
  }
MarkPcProcessed()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::MarkPcProcessed (int pc, typename InterpreterThread::ConsumedCharacter consumed_since_last_quantifier) [inline], [private]
Definition at line 1422 of file experimental-interpreter.cc.
                                                                   {
    switch (consumed_since_last_quantifier) {
      case InterpreterThread::ConsumedCharacter::DidConsume:
        pc_last_input_index_[pc].having_consumed_character = input_index_;
        break;
      case InterpreterThread::ConsumedCharacter::DidNotConsume:
        pc_last_input_index_[pc].not_having_consumed_character = input_index_;
        break;
    }
  }
NewCaptureClockArray()
template<class Character >
uint64_t* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewCaptureClockArray (uint64_t fill_value) [inline], [private]
Definition at line 1271 of file experimental-interpreter.cc.
                                                      {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    uint64_t* array_begin = NewCaptureClockArrayUninitialized();
    uint64_t* array_end = array_begin + register_count_per_match_;
    std::fill(array_begin, array_end, fill_value);
    return array_begin;
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewCaptureClockArrayUninitialized()
template<class Character >
uint64_t* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewCaptureClockArrayUninitialized () [inline], [private]
Definition at line 1266 of file experimental-interpreter.cc.
                                                {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    return capture_clock_array_allocator_->allocate(register_count_per_match_);
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewEmptyThread()
template<class Character >
InterpreterThread v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewEmptyThread (int pc) [inline], [private]
Definition at line 1308 of file experimental-interpreter.cc.
                                           {
    if (v8_flags.experimental_regexp_engine_capture_group_opt) {
      return InterpreterThread(
          pc, NewRegisterArray(kUndefinedRegisterValue),
          only_captureless_lookbehinds_
              ? nullptr
              : NewLookaroundMatchIndexArray(kUndefinedMatchIndexValue),
          NewQuantifierClockArray(0), NewCaptureClockArray(0),
          only_captureless_lookbehinds_ ? nullptr : NewLookaroundClockArray(0),
          InterpreterThread::ConsumedCharacter::DidConsume);
    } else {
      return InterpreterThread(
          pc, NewRegisterArray(kUndefinedRegisterValue), nullptr, nullptr,
          nullptr, nullptr, InterpreterThread::ConsumedCharacter::DidConsume);
    }
  }
References v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedMatchIndexValue, v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedRegisterValue, and v8::internal::v8_flags.
NewLookaroundClockArray()
template<class Character >
uint64_t* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewLookaroundClockArray (uint64_t fill_value) [inline], [private]
Definition at line 1291 of file experimental-interpreter.cc.
                                                         {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    uint64_t* array_begin = NewLookaroundClockArrayUninitialized();
    uint64_t* array_end = array_begin + lookaround_table_->size();
    std::fill(array_begin, array_end, fill_value);
    return array_begin;
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewLookaroundClockArrayUninitialized()
template<class Character >
uint64_t* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewLookaroundClockArrayUninitialized () [inline], [private]
Definition at line 1285 of file experimental-interpreter.cc.
                                                   {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    return lookaround_clock_array_allocator_->allocate(
        lookaround_table_->size());
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewLookaroundMatchIndexArray()
template<class Character >
int* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewLookaroundMatchIndexArray (int fill_value) [inline], [private]
Definition at line 1233 of file experimental-interpreter.cc.
                                                    {
    int* array_begin = NewLookaroundMatchIndexArrayUninitialized();
    int* array_end = array_begin + lookaround_table_->size();
    std::fill(array_begin, array_end, fill_value);
    return array_begin;
  }
NewLookaroundMatchIndexArrayUninitialized()
template<class Character >
int* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewLookaroundMatchIndexArrayUninitialized () [inline], [private]
Definition at line 1227 of file experimental-interpreter.cc.
                                                   {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    return lookaround_match_index_array_allocator_->allocate(
        lookaround_table_->size());
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewQuantifierClockArray()
template<class Character >
uint64_t* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewQuantifierClockArray (uint64_t fill_value) [inline], [private]
Definition at line 1251 of file experimental-interpreter.cc.
                                                         {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    uint64_t* array_begin = NewQuantifierClockArrayUninitialized();
    uint64_t* array_end = array_begin + quantifier_count_;
    std::fill(array_begin, array_end, fill_value);
    return array_begin;
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewQuantifierClockArrayUninitialized()
template<class Character >
uint64_t* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewQuantifierClockArrayUninitialized () [inline], [private]
Definition at line 1246 of file experimental-interpreter.cc.
                                                   {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    return quantifier_array_allocator_->allocate(quantifier_count_);
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
NewRegisterArray()
template<class Character >
int* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewRegisterArray (int fill_value) [inline], [private]
Definition at line 1215 of file experimental-interpreter.cc.
                                        {
    int* array_begin = NewRegisterArrayUninitialized();
    int* array_end = array_begin + register_count_per_match_;
    std::fill(array_begin, array_end, fill_value);
    return array_begin;
  }
NewRegisterArrayUninitialized()
template<class Character >
int* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewRegisterArrayUninitialized () [inline], [private]
Definition at line 1211 of file experimental-interpreter.cc.
                                       {
    return register_array_allocator_.allocate(register_count_per_match_);
  }
NewUninitializedThread()
template<class Character >
InterpreterThread v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::NewUninitializedThread (int pc) [inline], [private]
Definition at line 1328 of file experimental-interpreter.cc.
                                                   {
    if (v8_flags.experimental_regexp_engine_capture_group_opt) {
      return InterpreterThread(
          pc, NewRegisterArrayUninitialized(),
          only_captureless_lookbehinds_
              ? nullptr
              : NewLookaroundMatchIndexArrayUninitialized(),
          NewQuantifierClockArrayUninitialized(),
          NewCaptureClockArrayUninitialized(),
          only_captureless_lookbehinds_
              ? nullptr
              : NewLookaroundClockArrayUninitialized(),
          InterpreterThread::ConsumedCharacter::DidConsume);
    } else {
      return InterpreterThread(
          pc, NewRegisterArrayUninitialized(), nullptr, nullptr, nullptr,
          nullptr, InterpreterThread::ConsumedCharacter::DidConsume);
    }
  }
References v8::internal::v8_flags.
RunActiveThread()
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThread (InterpreterThread t) [inline], [private]
Definition at line 865 of file experimental-interpreter.cc.
                                           {
    while (true) {
      SBXCHECK_GE(t.pc, 0);
      SBXCHECK_LT(t.pc, bytecode_.size());
      ++clock;
      // Since the clock is a `uint64_t`, it is almost guaranteed
      // not to overflow. An `uint64_t` being at least 64 bits, it
      // would take at least a hundred years to overflow if the clock was
      // incremented at each cycle of a 3 GHz processor.
      DCHECK_GT(clock, 0);
      if (IsPcProcessed(t.pc, t.consumed_since_last_quantifier)) {
        DestroyThread(t);
        return RegExp::kInternalRegExpSuccess;
      }
      MarkPcProcessed(t.pc, t.consumed_since_last_quantifier);
      RegExpInstruction inst = bytecode_[t.pc];
      switch (inst.opcode) {
        case RegExpInstruction::CONSUME_RANGE:
        case RegExpInstruction::RANGE_COUNT: {
          blocked_threads_.Add(t, zone_);
          return RegExp::kInternalRegExpSuccess;
        }
        case RegExpInstruction::ASSERTION:
          if (!SatisfiesAssertion(inst.payload.assertion_type, input_,
                                  input_index_)) {
            DestroyThread(t);
            return RegExp::kInternalRegExpSuccess;
          }
          ++t.pc;
          break;
        case RegExpInstruction::FORK: {
          InterpreterThread fork = NewUninitializedThread(inst.payload.pc);
          fork.consumed_since_last_quantifier =
              t.consumed_since_last_quantifier;
          base::Vector<int> fork_registers = GetRegisterArray(fork);
          base::Vector<int> t_registers = GetRegisterArray(t);
          DCHECK_EQ(fork_registers.length(), t_registers.length());
          std::copy(t_registers.begin(), t_registers.end(),
                    fork_registers.begin());
          if (v8_flags.experimental_regexp_engine_capture_group_opt) {
            base::Vector<uint64_t> fork_quantifier_clocks =
                GetQuantifierClockArray(fork);
            base::Vector<uint64_t> t_fork_quantifier_clocks =
                GetQuantifierClockArray(t);
            DCHECK_EQ(fork_quantifier_clocks.length(),
                      t_fork_quantifier_clocks.length());
            std::copy(t_fork_quantifier_clocks.begin(),
                      t_fork_quantifier_clocks.end(),
                      fork_quantifier_clocks.begin());
            base::Vector<uint64_t> fork_capture_clocks =
                GetCaptureClockArray(fork);
            base::Vector<uint64_t> t_fork_capture_clocks =
                GetCaptureClockArray(t);
            DCHECK_EQ(fork_capture_clocks.length(),
                      t_fork_capture_clocks.length());
            std::copy(t_fork_capture_clocks.begin(),
                      t_fork_capture_clocks.end(), fork_capture_clocks.begin());
            if (!only_captureless_lookbehinds_) {
              base::Vector<int> fork_lookaround_match_index =
                  GetLookaroundMatchIndexArray(fork);
              base::Vector<int> t_fork_lookaround_match_index =
                  GetLookaroundMatchIndexArray(t);
              DCHECK_EQ(fork_lookaround_match_index.length(),
                        t_fork_lookaround_match_index.length());
              std::copy(t_fork_lookaround_match_index.begin(),
                        t_fork_lookaround_match_index.end(),
                        fork_lookaround_match_index.begin());
              base::Vector<uint64_t> fork_lookaround_clocks =
                  GetLookaroundClockArray(fork);
              base::Vector<uint64_t> t_fork_lookaround_clocks =
                  GetLookaroundClockArray(t);
              DCHECK_EQ(fork_lookaround_clocks.length(),
                        t_fork_lookaround_clocks.length());
              std::copy(t_fork_lookaround_clocks.begin(),
                        t_fork_lookaround_clocks.end(),
                        fork_lookaround_clocks.begin());
            }
          }
          active_threads_.Add(fork, zone_);
          if (v8_flags.experimental_regexp_engine_capture_group_opt) {
            int err_code = CheckMemoryConsumption();
            if (err_code != RegExp::kInternalRegExpSuccess) return err_code;
          }
          ++t.pc;
          break;
        }
        case RegExpInstruction::JMP:
          t.pc = inst.payload.pc;
          break;
        case RegExpInstruction::ACCEPT:
          if (best_match_thread_.has_value()) {
            DestroyThread(*best_match_thread_);
          }
          best_match_thread_ = t;
          for (InterpreterThread s : active_threads_) {
            DestroyThread(s);
          }
          active_threads_.Rewind(0);
          return RegExp::kInternalRegExpSuccess;
        case RegExpInstruction::SET_QUANTIFIER_TO_CLOCK:
          GetQuantifierClockArray(t)[inst.payload.quantifier_id] = clock;
          ++t.pc;
          break;
        case RegExpInstruction::CLEAR_REGISTER:
          SBXCHECK_BOUNDS(inst.payload.register_index,
                          register_count_per_match_);
          GetRegisterArray(t)[inst.payload.register_index] =
              kUndefinedRegisterValue;
          ++t.pc;
          break;
        case RegExpInstruction::SET_REGISTER_TO_CP:
          SBXCHECK_BOUNDS(inst.payload.register_index,
                          register_count_per_match_);
          GetRegisterArray(t)[inst.payload.register_index] = input_index_;
          if (v8_flags.experimental_regexp_engine_capture_group_opt) {
            GetCaptureClockArray(t)[inst.payload.register_index] = clock;
          }
          ++t.pc;
          break;
        case RegExpInstruction::FILTER_QUANTIFIER:
        case RegExpInstruction::FILTER_GROUP:
        case RegExpInstruction::FILTER_LOOKAROUND:
        case RegExpInstruction::FILTER_CHILD:
          UNREACHABLE();
        case RegExpInstruction::BEGIN_LOOP:
          t.consumed_since_last_quantifier =
              InterpreterThread::ConsumedCharacter::DidNotConsume;
          ++t.pc;
          break;
        case RegExpInstruction::END_LOOP:
          // If the thread did not consume any character during a whole
          // quantifier iteration,then it must be destroyed, since quantifier
          // repetitions are not allowed to match the empty string.
          if (t.consumed_since_last_quantifier ==
              InterpreterThread::ConsumedCharacter::DidNotConsume) {
            DestroyThread(t);
            return RegExp::kInternalRegExpSuccess;
          }
          ++t.pc;
          break;
        case RegExpInstruction::START_LOOKAROUND:
          ++t.pc;
          break;
        case RegExpInstruction::END_LOOKAROUND:
          if (best_match_thread_.has_value()) {
            DestroyThread(*best_match_thread_);
          }
          best_match_thread_ = t;
          for (InterpreterThread s : active_threads_) {
            DestroyThread(s);
          }
          active_threads_.Rewind(0);
          return RegExp::kInternalRegExpSuccess;
        case RegExpInstruction::WRITE_LOOKAROUND_TABLE:
          // Reaching this instruction means that the current lookaround thread
          // has found a match and needs to be destroyed. Since the lookaround
          // is verified at this position, we update the `lookaround_table_`.
          if (!only_captureless_lookbehinds_) {
            SBXCHECK_BOUNDS(current_lookaround_, lookaround_table_->size());
            (*lookaround_table_)[current_lookaround_][input_index_] = true;
          } else {
            SBXCHECK_BOUNDS(inst.payload.lookaround_id,
                            lookbehind_table_->length());
            lookbehind_table_->Set(inst.payload.lookaround_id, true);
          }
          DestroyThread(t);
          return RegExp::kInternalRegExpSuccess;
        case RegExpInstruction::READ_LOOKAROUND_TABLE:
          // Destroy the thread if the corresponding lookaround did or did not
          // complete a match at the current position (depending on whether or
          // not the lookaround is positive). The lookaround priority list
          // ensures that all the relevant lookarounds has already been run.
          if (!only_captureless_lookbehinds_) {
            SBXCHECK_BOUNDS(inst.payload.lookaround.index(),
                            lookaround_table_->size());
            if ((*lookaround_table_)[inst.payload.lookaround.index()]
                                    [input_index_] !=
                inst.payload.lookaround.is_positive()) {
              DestroyThread(t);
              return RegExp::kInternalRegExpSuccess;
            }
            // Store the match informations for positive lookarounds.
            if (inst.payload.lookaround.is_positive() &&
                !only_captureless_lookbehinds_) {
              GetLookaroundClockArray(t)[inst.payload.lookaround.index()] =
                  clock;
              GetLookaroundMatchIndexArray(t)[inst.payload.lookaround.index()] =
                  input_index_;
            }
            ++t.pc;
            break;
          } else {
            const int32_t lookbehind_index = inst.payload.lookaround.index();
            SBXCHECK_BOUNDS(lookbehind_index, lookbehind_table_->length());
            if (lookbehind_table_->at(lookbehind_index) !=
                inst.payload.lookaround.is_positive()) {
              DestroyThread(t);
              return RegExp::kInternalRegExpSuccess;
            }
            ++t.pc;
            break;
          }
      }
    }
  }
References v8::internal::RegExpInstruction::ACCEPT, v8::internal::RegExpInstruction::ASSERTION, v8::internal::RegExpInstruction::assertion_type, v8::base::Vector< T >::begin(), v8::internal::RegExpInstruction::BEGIN_LOOP, v8::internal::RegExpInstruction::CLEAR_REGISTER, v8::internal::RegExpInstruction::CONSUME_RANGE, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::consumed_since_last_quantifier, DCHECK_EQ, DCHECK_GT, v8::base::Vector< T >::end(), v8::internal::RegExpInstruction::END_LOOKAROUND, v8::internal::RegExpInstruction::END_LOOP, v8::internal::RegExpInstruction::FILTER_CHILD, v8::internal::RegExpInstruction::FILTER_GROUP, v8::internal::RegExpInstruction::FILTER_LOOKAROUND, v8::internal::RegExpInstruction::FILTER_QUANTIFIER, v8::internal::RegExpInstruction::FORK, v8::internal::RegExpInstruction::LookaroundPayload::index(), v8::internal::RegExpInstruction::LookaroundPayload::is_positive(), v8::internal::RegExpInstruction::JMP, v8::internal::RegExp::kInternalRegExpSuccess, v8::internal::anonymous_namespace{experimental-interpreter.cc}::kUndefinedRegisterValue, v8::base::Vector< T >::length(), v8::internal::RegExpInstruction::lookaround, v8::internal::RegExpInstruction::lookaround_id, v8::internal::RegExpInstruction::opcode, v8::internal::RegExpInstruction::payload, v8::internal::RegExpInstruction::pc, v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::InterpreterThread::pc, v8::internal::RegExpInstruction::quantifier_id, v8::internal::RegExpInstruction::RANGE_COUNT, v8::internal::RegExpInstruction::READ_LOOKAROUND_TABLE, v8::internal::RegExpInstruction::register_index, v8::internal::anonymous_namespace{experimental-interpreter.cc}::SatisfiesAssertion(), SBXCHECK_BOUNDS, SBXCHECK_GE, SBXCHECK_LT, v8::internal::RegExpInstruction::SET_QUANTIFIER_TO_CLOCK, v8::internal::RegExpInstruction::SET_REGISTER_TO_CP, v8::internal::RegExpInstruction::START_LOOKAROUND, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::RegExpInstruction::WRITE_LOOKAROUND_TABLE.
RunActiveThreads()
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThreads () [inline], [private]
Definition at line 1099 of file experimental-interpreter.cc.
                         {
    while (!active_threads_.is_empty()) {
      int err_code = RunActiveThread(active_threads_.RemoveLast());
      if (err_code != RegExp::kInternalRegExpSuccess) return err_code;
    }
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::RegExp::kInternalRegExpSuccess.
RunActiveThreadsToEnd()
template<class Character >
V8_WARN_UNUSED_RESULT int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::RunActiveThreadsToEnd () [inline], [private]
Definition at line 686 of file experimental-interpreter.cc.
                                                    {
    // Run the initial thread, potentially forking new threads, until every
    // thread is blocked without further input.
    RunActiveThreads();
    // We stop if one of the following conditions hold:
    // - We have exhausted the entire input.
    // - We have found a match at some point, and there are no remaining
    // threads with higher priority than the thread that produced the match.
    // Threads with low priority have been aborted earlier, and the remaining
    // threads are blocked here, so the latter simply means that
    // `blocked_threads_` is empty.
    while ((reverse_ ? ((0 < input_index_ && input_index_ <= input_.length()))
                     : (0 <= input_index_ && input_index_ < input_.length())) &&
           !(FoundMatch() && blocked_threads_.is_empty())) {
      DCHECK(active_threads_.is_empty());
      if (lookbehind_table_.has_value()) {
        std::fill(lookbehind_table_->begin(), lookbehind_table_->end(), false);
      }
      if (reverse_) {
        --input_index_;
      }
      base::uc16 input_char = input_[input_index_];
      if (!reverse_) {
        ++input_index_;
      }
      static constexpr int kTicksBetweenInterruptHandling = 64;
      if (input_index_ % kTicksBetweenInterruptHandling == 0) {
        int err_code = HandleInterrupts();
        if (err_code != RegExp::kInternalRegExpSuccess) return err_code;
      }
      // We unblock all blocked_threads_ by feeding them the input char.
      FlushBlockedThreads(input_char);
      // Run all threads until they block or accept.
      RunActiveThreads();
    }
    return RegExp::kInternalRegExpSuccess;
  }
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{regexp-interpreter.cc}::HandleInterrupts(), and v8::internal::RegExp::kInternalRegExpSuccess.
SetInputIndex()
template<class Character >
void v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::SetInputIndex (int new_input_index) [inline], [private]
Definition at line 798 of file experimental-interpreter.cc.
                                          {
    DCHECK_GE(new_input_index, 0);
    DCHECK_LE(new_input_index, input_.length());
    input_index_ = new_input_index;
  }
References DCHECK_GE, and DCHECK_LE.
Member Data Documentation
active_threads_
template<class Character >
ZoneList<InterpreterThread> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::active_threads_ [private]
Definition at line 1479 of file experimental-interpreter.cc.
best_match_thread_
template<class Character >
std::optional<InterpreterThread> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::best_match_thread_ [private]
Definition at line 1497 of file experimental-interpreter.cc.
blocked_threads_
template<class Character >
ZoneList<InterpreterThread> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::blocked_threads_ [private]
Definition at line 1484 of file experimental-interpreter.cc.
bytecode_
template<class Character >
base::Vector<const RegExpInstruction> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::bytecode_ [private]
Definition at line 1441 of file experimental-interpreter.cc.
bytecode_object_
template<class Character >
Tagged<TrustedByteArray> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::bytecode_object_ [private]
Definition at line 1440 of file experimental-interpreter.cc.
call_origin_
template<class Character >
const RegExp::CallOrigin v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::call_origin_ [private]
Definition at line 1436 of file experimental-interpreter.cc.
capture_clock_array_allocator_
template<class Character >
std::optional<RecyclingZoneAllocator<uint64_t> > v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::capture_clock_array_allocator_ [private]
Definition at line 1495 of file experimental-interpreter.cc.
clock
template<class Character >
uint64_t v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::clock [private]
Definition at line 1454 of file experimental-interpreter.cc.
current_lookaround_
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::current_lookaround_ [private]
Definition at line 1535 of file experimental-interpreter.cc.
filter_groups_pc_
template<class Character >
std::optional<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::filter_groups_pc_ [private]
Definition at line 1541 of file experimental-interpreter.cc.
input_
template<class Character >
base::Vector<const Character> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::input_ [private]
Definition at line 1450 of file experimental-interpreter.cc.
input_index_
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::input_index_ [private]
Definition at line 1451 of file experimental-interpreter.cc.
input_object_
template<class Character >
Tagged<String> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::input_object_ [private]
Definition at line 1449 of file experimental-interpreter.cc.
isolate_
template<class Character >
Isolate* const v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::isolate_ [private]
Definition at line 1434 of file experimental-interpreter.cc.
lookaround_clock_array_allocator_
template<class Character >
std::optional<RecyclingZoneAllocator<uint64_t> > v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::lookaround_clock_array_allocator_ [private]
Definition at line 1492 of file experimental-interpreter.cc.
lookaround_match_index_array_allocator_
template<class Character >
std::optional<RecyclingZoneAllocator<int> > v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::lookaround_match_index_array_allocator_ [private]
Definition at line 1490 of file experimental-interpreter.cc.
lookaround_table_
template<class Character >
std::optional<ZoneVector<ZoneVector<bool> > > v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::lookaround_table_ [private]
Definition at line 1518 of file experimental-interpreter.cc.
lookarounds_
template<class Character >
ZoneList<Lookaround> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::lookarounds_ [private]
Definition at line 1512 of file experimental-interpreter.cc.
lookbehind_table_
template<class Character >
std::optional<ZoneList<bool> > v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::lookbehind_table_ [private]
Definition at line 1523 of file experimental-interpreter.cc.
memory_consumption_per_thread_
template<class Character >
uint64_t v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::memory_consumption_per_thread_ [private]
Definition at line 1543 of file experimental-interpreter.cc.
no_gc_
template<class Character >
DisallowGarbageCollection v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::no_gc_ [private]
Definition at line 1438 of file experimental-interpreter.cc.
only_captureless_lookbehinds_
template<class Character >
bool v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::only_captureless_lookbehinds_ [private]
Definition at line 1528 of file experimental-interpreter.cc.
pc_last_input_index_
template<class Character >
base::Vector<LastInputIndex> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::pc_last_input_index_ [private]
Definition at line 1475 of file experimental-interpreter.cc.
quantifier_array_allocator_
template<class Character >
std::optional<RecyclingZoneAllocator<uint64_t> > v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::quantifier_array_allocator_ [private]
Definition at line 1493 of file experimental-interpreter.cc.
quantifier_count_
template<class Character >
int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::quantifier_count_ [private]
Definition at line 1447 of file experimental-interpreter.cc.
register_array_allocator_
template<class Character >
RecyclingZoneAllocator<int> v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::register_array_allocator_ [private]
Definition at line 1488 of file experimental-interpreter.cc.
register_count_per_match_
template<class Character >
const int v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::register_count_per_match_ [private]
Definition at line 1444 of file experimental-interpreter.cc.
reverse_
template<class Character >
bool v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::reverse_ [private]
Definition at line 1531 of file experimental-interpreter.cc.
zone_
template<class Character >
Zone* v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::zone_ [private]
Definition at line 1545 of file experimental-interpreter.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-interpreter.cc