v8::internal::compiler::Operator1< T, Pred, Hash > Class Template Reference
#include <operator.h>
Public Member Functions
Operator1 (Opcode opcode, Properties properties, const char *mnemonic, size_t value_in, size_t effect_in, size_t control_in, size_t value_out, size_t effect_out, size_t control_out, T parameter, Pred const &pred=Pred(), Hash const &hash=Hash())
T const & parameter () const
bool Equals (const Operator *other) const final
size_t HashCode () const final
virtual void PrintParameter (std::ostream &os, PrintVerbosity verbose) const
void PrintToImpl (std::ostream &os, PrintVerbosity verbose) const override
void PrintParameter (std::ostream &os, PrintVerbosity verbose) const
void PrintParameter (std::ostream &os, PrintVerbosity verbose) const
Private Attributes
T const parameter_
Pred const pred_
Hash const hash_
Additional Inherited Members
Detailed Description
template<typename T, typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
class v8::internal::compiler::Operator1< T, Pred, Hash >
Definition at line 167 of file operator.h.
Constructor & Destructor Documentation
Operator1()
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
v8::internal::compiler::Operator1< T, Pred, Hash >::Operator1 (Opcode opcode, Properties properties, const char * mnemonic, size_t value_in, size_t effect_in, size_t control_in, size_t value_out, size_t effect_out, size_t control_out, T parameter, Pred const & pred = Pred(), Hash const & hash = Hash()) [inline]
Definition at line 169 of file operator.h.
      : Operator(opcode, properties, mnemonic, value_in, effect_in, control_in,
                 value_out, effect_out, control_out),
        parameter_(parameter),
        pred_(pred),
        hash_(hash) {}
Member Function Documentation
Equals()
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
bool v8::internal::compiler::Operator1< T, Pred, Hash >::Equals (const Operator * other) const [inline], [final], [virtual]
Reimplemented from v8::internal::compiler::Operator.
Definition at line 181 of file operator.h.
                                                 {
    if (opcode() != other->opcode()) return false;
    const Operator1<T, Pred, Hash>* that =
        reinterpret_cast<const Operator1<T, Pred, Hash>*>(other);
    return this->pred_(this->parameter(), that->parameter());
  }
References v8::internal::compiler::Operator::opcode(), v8::internal::compiler::Operator1< T, Pred, Hash >::parameter(), and v8::internal::compiler::Operator1< T, Pred, Hash >::pred_.
HashCode()
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
size_t v8::internal::compiler::Operator1< T, Pred, Hash >::HashCode () const [inline], [final], [virtual]
Reimplemented from v8::internal::compiler::Operator.
Definition at line 187 of file operator.h.
                                {
    return base::hash_combine(this->opcode(), this->hash_(this->parameter()));
  }
References v8::internal::compiler::Operator1< T, Pred, Hash >::hash_, v8::base::hash_combine(), v8::internal::compiler::Operator::opcode(), and v8::internal::compiler::Operator1< T, Pred, Hash >::parameter().
parameter()
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
T const& v8::internal::compiler::Operator1< T, Pred, Hash >::parameter () const [inline]
Definition at line 179 of file operator.h.
{ return parameter_; }
References v8::internal::compiler::Operator1< T, Pred, Hash >::parameter_.
Referenced by v8::internal::compiler::Operator1< T, Pred, Hash >::Equals(), v8::internal::compiler::Operator1< T, Pred, Hash >::HashCode(), and v8::internal::compiler::Operator1< T, Pred, Hash >::PrintParameter().
PrintParameter() [1/3]
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
virtual void v8::internal::compiler::Operator1< T, Pred, Hash >::PrintParameter (std::ostream & os, PrintVerbosity verbose) const [inline], [virtual]
Definition at line 196 of file operator.h.
                                                                            {
    os << "[" << parameter() << "]";
  }
References v8::internal::compiler::Operator1< T, Pred, Hash >::parameter().
Referenced by v8::internal::compiler::Operator1< T, Pred, Hash >::PrintToImpl().
PrintParameter() [2/3]
void v8::internal::compiler::Operator1< FieldAccess >::PrintParameter (std::ostream & os, PrintVerbosity verbose) const
Definition at line 108 of file simplified-operator.cc.
                                                                          {
  if (verbose == PrintVerbosity::kVerbose) {
    os << parameter();
  } else {
    os << "[+" << parameter().offset << "]";
  }
}
PrintParameter() [3/3]
void v8::internal::compiler::Operator1< FieldAccess >::PrintParameter (std::ostream & os, PrintVerbosity verbose) const
PrintToImpl()
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
void v8::internal::compiler::Operator1< T, Pred, Hash >::PrintToImpl (std::ostream & os, PrintVerbosity verbose) const [inline], [override], [virtual]
Reimplemented from v8::internal::compiler::Operator.
Definition at line 200 of file operator.h.
                                                                          {
    os << mnemonic();
    PrintParameter(os, verbose);
  }
References v8::internal::compiler::Operator::mnemonic(), and v8::internal::compiler::Operator1< T, Pred, Hash >::PrintParameter().
Member Data Documentation
hash_
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
Hash const v8::internal::compiler::Operator1< T, Pred, Hash >::hash_ [private]
Definition at line 208 of file operator.h.
Referenced by v8::internal::compiler::Operator1< T, Pred, Hash >::HashCode().
parameter_
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
T const v8::internal::compiler::Operator1< T, Pred, Hash >::parameter_ [private]
Definition at line 206 of file operator.h.
Referenced by v8::internal::compiler::Operator1< T, Pred, Hash >::parameter().
pred_
template<typename T , typename Pred = OpEqualTo<T>, typename Hash = OpHash<T>>
Pred const v8::internal::compiler::Operator1< T, Pred, Hash >::pred_ [private]
Definition at line 207 of file operator.h.
Referenced by v8::internal::compiler::Operator1< T, Pred, Hash >::Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/operator.h