v8::internal::RuntimeState Class Reference
#include <runtime.h>
Public Member Functions
RuntimeState (const RuntimeState &)=delete
RuntimeState & operator= (const RuntimeState &)=delete
unibrow::Mapping< unibrow::ToUppercase, 128 > * to_upper_mapping ()
unibrow::Mapping< unibrow::ToLowercase, 128 > * to_lower_mapping ()
Runtime::Function * redirected_intrinsic_functions ()
void set_redirected_intrinsic_functions (Runtime::Function *redirected_intrinsic_functions)
Private Member Functions
RuntimeState ()=default
Private Attributes
unibrow::Mapping< unibrow::ToUppercase, 128 > to_upper_mapping_
unibrow::Mapping< unibrow::ToLowercase, 128 > to_lower_mapping_
std::unique_ptr< Runtime::Function[]> redirected_intrinsic_functions_
Friends
class Isolate
class Runtime
Detailed Description
Definition at line 1053 of file runtime.h.
Constructor & Destructor Documentation
RuntimeState() [1/2]
v8::internal::RuntimeState::RuntimeState (const RuntimeState &) [delete]
RuntimeState() [2/2]
v8::internal::RuntimeState::RuntimeState () [private], [default]
Member Function Documentation
operator=()
RuntimeState& v8::internal::RuntimeState::operator= (const RuntimeState &) [delete]
redirected_intrinsic_functions()
Runtime::Function* v8::internal::RuntimeState::redirected_intrinsic_functions () [inline]
Definition at line 1066 of file runtime.h.
                                                    {
    return redirected_intrinsic_functions_.get();
  }
References redirected_intrinsic_functions_.
Referenced by v8::internal::Runtime::RuntimeFunctionTable(), and set_redirected_intrinsic_functions().
set_redirected_intrinsic_functions()
void v8::internal::RuntimeState::set_redirected_intrinsic_functions (Runtime::Function * redirected_intrinsic_functions) [inline]
Definition at line 1070 of file runtime.h.
                                                       {
    redirected_intrinsic_functions_.reset(redirected_intrinsic_functions);
  }
References redirected_intrinsic_functions(), and redirected_intrinsic_functions_.
Referenced by v8::internal::Runtime::RuntimeFunctionTable().
to_lower_mapping()
unibrow::Mapping<unibrow::ToLowercase, 128>* v8::internal::RuntimeState::to_lower_mapping () [inline]
Definition at line 1061 of file runtime.h.
                                                              {
    return &to_lower_mapping_;
  }
References to_lower_mapping_.
to_upper_mapping()
unibrow::Mapping<unibrow::ToUppercase, 128>* v8::internal::RuntimeState::to_upper_mapping () [inline]
Definition at line 1058 of file runtime.h.
                                                              {
    return &to_upper_mapping_;
  }
References to_upper_mapping_.
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 1084 of file runtime.h.
Runtime
friend class Runtime [friend]
Definition at line 1085 of file runtime.h.
Member Data Documentation
redirected_intrinsic_functions_
std::unique_ptr<Runtime::Function[]> v8::internal::RuntimeState::redirected_intrinsic_functions_ [private]
Definition at line 1082 of file runtime.h.
Referenced by redirected_intrinsic_functions(), and set_redirected_intrinsic_functions().
to_lower_mapping_
unibrow::Mapping<unibrow::ToLowercase, 128> v8::internal::RuntimeState::to_lower_mapping_ [private]
Definition at line 1079 of file runtime.h.
Referenced by to_lower_mapping().
to_upper_mapping_
unibrow::Mapping<unibrow::ToUppercase, 128> v8::internal::RuntimeState::to_upper_mapping_ [private]
Definition at line 1078 of file runtime.h.
Referenced by to_upper_mapping().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime.h