v8::internal::StackArgumentsAccessor Class Reference
#include <macro-assembler-ia32.h>
Public Member Functions
StackArgumentsAccessor (Register argc)
Operand operator[] (int index) const
Operand GetArgumentOperand (int index) const
Operand GetReceiverOperand () const
StackArgumentsAccessor (Register argc)
Operand operator[] (int index) const
Operand GetArgumentOperand (int index) const
Operand GetReceiverOperand () const
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (StackArgumentsAccessor)
DISALLOW_IMPLICIT_CONSTRUCTORS (StackArgumentsAccessor)
Private Attributes
const Register argc_
Detailed Description
Definition at line 53 of file macro-assembler-ia32.h.
Constructor & Destructor Documentation
StackArgumentsAccessor() [1/2]
v8::internal::StackArgumentsAccessor::StackArgumentsAccessor (Register argc) [inline], [explicit]
Definition at line 56 of file macro-assembler-ia32.h.
                                                 : argc_(argc) {
    DCHECK_NE(argc_, no_reg);
  }
References argc_, DCHECK_NE, and v8::internal::no_reg.
StackArgumentsAccessor() [2/2]
v8::internal::StackArgumentsAccessor::StackArgumentsAccessor (Register argc) [inline], [explicit]
Definition at line 43 of file macro-assembler-x64.h.
                                                 : argc_(argc) {
    DCHECK_NE(argc_, no_reg);
  }
References argc_, DCHECK_NE, and v8::internal::no_reg.
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS() [1/2]
v8::internal::StackArgumentsAccessor::DISALLOW_IMPLICIT_CONSTRUCTORS (StackArgumentsAccessor) [private]
DISALLOW_IMPLICIT_CONSTRUCTORS() [2/2]
v8::internal::StackArgumentsAccessor::DISALLOW_IMPLICIT_CONSTRUCTORS (StackArgumentsAccessor) [private]
GetArgumentOperand() [1/2]
Operand v8::internal::StackArgumentsAccessor::GetArgumentOperand (int index) const
Referenced by GetReceiverOperand(), and operator[]().
GetArgumentOperand() [2/2]
Operand v8::internal::StackArgumentsAccessor::GetArgumentOperand (int index) const
GetReceiverOperand() [1/2]
Operand v8::internal::StackArgumentsAccessor::GetReceiverOperand () const [inline]
Definition at line 64 of file macro-assembler-ia32.h.
{ return GetArgumentOperand(0); }
References GetArgumentOperand().
GetReceiverOperand() [2/2]
Operand v8::internal::StackArgumentsAccessor::GetReceiverOperand () const [inline]
Definition at line 51 of file macro-assembler-x64.h.
{ return GetArgumentOperand(0); }
References GetArgumentOperand().
operator[]() [1/2]
Operand v8::internal::StackArgumentsAccessor::operator[] (int index) const [inline]
Definition at line 61 of file macro-assembler-ia32.h.
{ return GetArgumentOperand(index); }
References GetArgumentOperand(), and v8::internal::index.
operator[]() [2/2]
Operand v8::internal::StackArgumentsAccessor::operator[] (int index) const [inline]
Definition at line 48 of file macro-assembler-x64.h.
{ return GetArgumentOperand(index); }
References GetArgumentOperand(), and v8::internal::index.
Member Data Documentation
argc_
const Register v8::internal::StackArgumentsAccessor::argc_ [private]
Definition at line 67 of file macro-assembler-ia32.h.
Referenced by StackArgumentsAccessor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/ia32/macro-assembler-ia32.h
/mnt/V8SourceCode/src/codegen/x64/macro-assembler-x64.h