v8::internal::Serializer::ObjectSerializer Class Reference
#include <serializer.h>
Public Member Functions
ObjectSerializer (Serializer *serializer, Handle< HeapObject > obj, SnapshotByteSink *sink)
~ObjectSerializer () override
void Serialize (SlotType slot_type)
void SerializeObject ()
void SerializeDeferred ()
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) override
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *target) override
void VisitExternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitInternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *target) override
void VisitOffHeapTarget (Tagged< InstructionStream > host, RelocInfo *target) override
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) override
void VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) override
void VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) override
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) override
void VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) override
void VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) override
Isolate * isolate ()
Private Member Functions
void SerializePrologue (SnapshotSpace space, int size, Tagged< Map > map)
void SerializeContent (Tagged< Map > map, int size)
void OutputExternalReference (Address target, int target_size, bool sandboxify, ExternalPointerTag tag)
void OutputRawData (Address up_to)
uint32_t SerializeBackingStore (void *backing_store, uint32_t byte_length, Maybe< uint32_t > max_byte_length)
void SerializeJSTypedArray ()
void SerializeJSArrayBuffer ()
void SerializeExternalString ()
void SerializeExternalStringAsSequentialString ()
Private Attributes
Isolate * isolate_
Serializer * serializer_
Handle< HeapObject > object_
SnapshotByteSink * sink_
int bytes_processed_so_far_
Detailed Description
Definition at line 455 of file serializer.h.
Constructor & Destructor Documentation
ObjectSerializer()
v8::internal::Serializer::ObjectSerializer::ObjectSerializer (Serializer * serializer, Handle< HeapObject > obj, SnapshotByteSink * sink) [inline]
Definition at line 457 of file serializer.h.
      : isolate_(serializer->isolate()),
        serializer_(serializer),
        object_(obj),
        sink_(sink),
        bytes_processed_so_far_(0) {
#ifdef DEBUG
    serializer_->PushStack(obj);
#endif // DEBUG
  }
References serializer_.
 ObjectSerializer()
v8::internal::Serializer::ObjectSerializer::~ObjectSerializer () [inline], [override]
Definition at line 468 of file serializer.h.
                               {
#ifdef DEBUG
    serializer_->PopStack();
#endif // DEBUG
  }
References serializer_.
Member Function Documentation
isolate()
Isolate* v8::internal::Serializer::ObjectSerializer::isolate () [inline]
Definition at line 508 of file serializer.h.
{ return isolate_; }
References isolate_.
Referenced by SerializePrologue().
OutputExternalReference()
void v8::internal::Serializer::ObjectSerializer::OutputExternalReference (Address target, int target_size, bool sandboxify, ExternalPointerTag tag) [private]
Definition at line 1073 of file serializer.cc.
                                                                              {
  DCHECK_LE(target_size, sizeof(target)); // Must fit in Address.
  DCHECK_IMPLIES(sandboxify, V8_ENABLE_SANDBOX_BOOL);
  DCHECK_IMPLIES(sandboxify,
                 tag != kExternalPointerNullTag || target == kNullAddress);
  ExternalReferenceEncoder::Value encoded_reference;
  bool encoded_successfully;
  if (serializer_->allow_unknown_external_references_for_testing()) {
    encoded_successfully =
        serializer_->TryEncodeExternalReference(target).To(&encoded_reference);
  } else {
    encoded_reference = serializer_->EncodeExternalReference(target);
    encoded_successfully = true;
  }
  if (!encoded_successfully) {
    // In this case the serialized snapshot will not be used in a different
    // Isolate and thus the target address will not change between
    // serialization and deserialization. We can serialize seen external
    // references verbatim.
    CHECK(serializer_->allow_unknown_external_references_for_testing());
    CHECK(IsAligned(target_size, kTaggedSize));
    CHECK_LE(target_size, kFixedRawDataCount * kTaggedSize);
    if (sandboxify) {
      CHECK_EQ(target_size, kSystemPointerSize);
      sink_->Put(kSandboxedRawExternalReference, "SandboxedRawReference");
      sink_->PutRaw(reinterpret_cast<uint8_t*>(&target), target_size,
                    "raw pointer");
    } else {
      // Encode as FixedRawData instead of RawExternalReference as the target
      // may be less than kSystemPointerSize large.
      int size_in_tagged = target_size >> kTaggedSizeLog2;
      sink_->Put(FixedRawDataWithSize::Encode(size_in_tagged), "FixedRawData");
      sink_->PutRaw(reinterpret_cast<uint8_t*>(&target), target_size,
                    "raw pointer");
    }
  } else if (encoded_reference.is_from_api()) {
    if (sandboxify) {
      sink_->Put(kSandboxedApiReference, "SandboxedApiRef");
    } else {
      sink_->Put(kApiReference, "ApiRef");
    }
    sink_->PutUint30(encoded_reference.index(), "reference index");
  } else {
    if (sandboxify) {
      sink_->Put(kSandboxedExternalReference, "SandboxedExternalRef");
    } else {
      sink_->Put(kExternalReference, "ExternalRef");
    }
    sink_->PutUint30(encoded_reference.index(), "reference index");
  }
  if (sandboxify) {
    sink_->PutUint30(tag, "external pointer tag");
  }
}
References CHECK, CHECK_EQ, CHECK_LE, DCHECK_IMPLIES, DCHECK_LE, v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), v8::internal::ExternalReferenceEncoder::Value::index(), v8::internal::ExternalReferenceEncoder::Value::is_from_api(), IsAligned(), v8::internal::SerializerDeserializer::kApiReference, v8::internal::kExternalPointerNullTag, v8::internal::SerializerDeserializer::kExternalReference, v8::internal::SerializerDeserializer::kFixedRawDataCount, v8::internal::kNullAddress, v8::internal::SerializerDeserializer::kSandboxedApiReference, v8::internal::SerializerDeserializer::kSandboxedExternalReference, v8::internal::SerializerDeserializer::kSandboxedRawExternalReference, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::kTaggedSizeLog2, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::Serializer::sink_, and V8_ENABLE_SANDBOX_BOOL.
OutputRawData()
void v8::internal::Serializer::ObjectSerializer::OutputRawData (Address up_to) [private]
Definition at line 1361 of file serializer.cc.
                                                            {
  Address object_start = object_->address();
  int base = bytes_processed_so_far_;
  int up_to_offset = static_cast<int>(up_to - object_start);
  int to_skip = up_to_offset - bytes_processed_so_far_;
  int bytes_to_output = to_skip;
  DCHECK(IsAligned(bytes_to_output, kTaggedSize));
  int tagged_to_output = bytes_to_output / kTaggedSize;
  bytes_processed_so_far_ += to_skip;
  DCHECK_GE(to_skip, 0);
  if (bytes_to_output != 0) {
    DCHECK(to_skip == bytes_to_output);
    if (tagged_to_output <= kFixedRawDataCount) {
      sink_->Put(FixedRawDataWithSize::Encode(tagged_to_output),
                 "FixedRawData");
    } else {
      sink_->Put(kVariableRawData, "VariableRawData");
      sink_->PutUint30(tagged_to_output, "length");
    }
#ifdef MEMORY_SANITIZER
    // Check that we do not serialize uninitialized memory.
    __msan_check_mem_is_initialized(
        reinterpret_cast<void*>(object_start + base), bytes_to_output);
#endif // MEMORY_SANITIZER
    PtrComprCageBase cage_base(isolate_);
    if (IsSharedFunctionInfo(*object_, cage_base)) {
      // The bytecode age field can be changed by GC concurrently.
      static_assert(SharedFunctionInfo::kAgeSize == kUInt16Size);
      uint16_t field_value = 0;
      OutputRawWithCustomField(sink_, object_start, base, bytes_to_output,
                               SharedFunctionInfo::kAgeOffset,
                               sizeof(field_value),
                               reinterpret_cast<uint8_t*>(&field_value));
    } else if (IsDescriptorArray(*object_, cage_base)) {
      // The number of marked descriptors field can be changed by GC
      // concurrently.
      const auto field_value = DescriptorArrayMarkingState::kInitialGCState;
      static_assert(sizeof(field_value) == DescriptorArray::kSizeOfRawGcState);
      OutputRawWithCustomField(sink_, object_start, base, bytes_to_output,
                               DescriptorArray::kRawGcStateOffset,
                               sizeof(field_value),
                               reinterpret_cast<const uint8_t*>(&field_value));
    } else if (IsCode(*object_, cage_base)) {
#ifdef V8_ENABLE_SANDBOX
      // When the sandbox is enabled, this field contains the handle to this
      // Code object's code pointer table entry. This will be recomputed after
      // deserialization.
      static uint8_t field_value[kIndirectPointerSize] = {0};
      OutputRawWithCustomField(sink_, object_start, base, bytes_to_output,
                               Code::kSelfIndirectPointerOffset,
                               sizeof(field_value), field_value);
#else
      // In this case, instruction_start field contains a raw value that will
      // similarly be recomputed after deserialization, so write zeros to keep
      // the snapshot deterministic.
      static uint8_t field_value[kSystemPointerSize] = {0};
      OutputRawWithCustomField(sink_, object_start, base, bytes_to_output,
                               Code::kInstructionStartOffset,
                               sizeof(field_value), field_value);
#endif // V8_ENABLE_SANDBOX
    } else if (IsSeqString(*object_)) {
      // SeqStrings may contain padding. Serialize the padding bytes as 0s to
      // make the snapshot content deterministic.
      SeqString::DataAndPaddingSizes sizes =
          Cast<SeqString>(*object_)->GetDataAndPaddingSizes();
      DCHECK_EQ(bytes_to_output, sizes.data_size - base + sizes.padding_size);
      int data_bytes_to_output = sizes.data_size - base;
      sink_->PutRaw(reinterpret_cast<uint8_t*>(object_start + base),
                    data_bytes_to_output, "SeqStringData");
      sink_->PutN(sizes.padding_size, 0, "SeqStringPadding");
    } else {
      sink_->PutRaw(reinterpret_cast<uint8_t*>(object_start + base),
                    bytes_to_output, "Bytes");
    }
  }
}
References v8::internal::Serializer::cage_base(), v8::internal::SeqString::DataAndPaddingSizes::data_size, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), IsAligned(), v8::internal::Serializer::isolate_, v8::internal::InstanceTypeChecker::IsSeqString(), v8::internal::SharedFunctionInfo::kAgeSize, v8::internal::SerializerDeserializer::kFixedRawDataCount, v8::internal::kIndirectPointerSize, v8::internal::DescriptorArrayMarkingState::kInitialGCState, v8::internal::DescriptorArray::kSizeOfRawGcState, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::kUInt16Size, v8::internal::SerializerDeserializer::kVariableRawData, v8::internal::anonymous_namespace{serializer.cc}::OutputRawWithCustomField(), v8::internal::SeqString::DataAndPaddingSizes::padding_size, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutN(), v8::internal::SnapshotByteSink::PutRaw(), v8::internal::SnapshotByteSink::PutUint30(), and v8::internal::Serializer::sink_.
Serialize()
void v8::internal::Serializer::ObjectSerializer::Serialize (SlotType slot_type)
Definition at line 794 of file serializer.cc.
                                                             {
  RecursionScope recursion(serializer_);
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> raw = *object_;
    // Defer objects as "pending" if they cannot be serialized now, or if we
    // exceed a certain recursion depth. Some objects cannot be deferred.
    bool should_defer =
        recursion.ExceedsMaximum() || serializer_->MustBeDeferred(raw);
    if (should_defer && CanBeDeferred(raw, slot_type)) {
      if (v8_flags.trace_serializer) {
        PrintF(" Deferring heap object: ");
        ShortPrint(*object_);
        PrintF("\n");
      }
      // Deferred objects are considered "pending".
      serializer_->RegisterObjectIsPending(raw);
      serializer_->PutPendingForwardReference(
          *serializer_->forward_refs_per_pending_object_.Find(raw));
      serializer_->QueueDeferredObject(raw);
      return;
    } else {
      if (v8_flags.trace_serializer && recursion.ExceedsMaximum()) {
        PrintF(" Exceeding max recursion depth by %d for: ",
               recursion.ExceedsMaximumBy());
        ShortPrint(*object_);
        PrintF("\n");
      }
    }
    if (v8_flags.trace_serializer) {
      PrintF(" Encoding heap object: ");
      ShortPrint(*object_);
      PrintF("\n");
    }
  }
  PtrComprCageBase cage_base(isolate());
  InstanceType instance_type = object_->map(cage_base)->instance_type();
  if (InstanceTypeChecker::IsExternalString(instance_type)) {
    SerializeExternalString();
    return;
  }
  if (InstanceTypeChecker::IsJSTypedArray(instance_type)) {
    SerializeJSTypedArray();
    return;
  }
  if (InstanceTypeChecker::IsJSArrayBuffer(instance_type)) {
    SerializeJSArrayBuffer();
    return;
  }
  if (InstanceTypeChecker::IsScript(instance_type)) {
    // Clear cached line ends & compiled lazy function positions.
    Cast<Script>(object_)->set_line_ends(Smi::zero());
    Cast<Script>(object_)->set_compiled_lazy_function_positions(
        ReadOnlyRoots(isolate()).undefined_value());
  }
#if V8_ENABLE_WEBASSEMBLY
  // The padding for wasm null is a free space filler. We put it into the roots
  // table to be able to skip its payload when serializing the read only heap
  // in the ReadOnlyHeapImageSerializer.
  DCHECK_IMPLIES(
      !object_->SafeEquals(ReadOnlyRoots(isolate()).wasm_null_padding()),
      !IsFreeSpaceOrFiller(*object_, cage_base));
#else
  DCHECK(!IsFreeSpaceOrFiller(*object_, cage_base));
#endif
  SerializeObject();
}
References v8::internal::Serializer::cage_base(), v8::internal::SerializerDeserializer::CanBeDeferred(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Serializer::RecursionScope::ExceedsMaximum(), v8::internal::Serializer::RecursionScope::ExceedsMaximumBy(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::Serializer::isolate(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::internal::Serializer::SerializeObject(), v8::internal::ShortPrint(), v8::internal::v8_flags, and v8::internal::Smi::zero().
Referenced by v8::internal::CodeSerializer::SerializeGeneric(), v8::internal::ContextSerializer::SerializeObjectImpl(), v8::internal::StartupSerializer::SerializeObjectImpl(), v8::internal::SharedHeapSerializer::SerializeObjectImpl(), and v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields().
SerializeBackingStore()
uint32_t v8::internal::Serializer::ObjectSerializer::SerializeBackingStore (void * backing_store, uint32_t byte_length, Maybe< uint32_t > max_byte_length) [private]
Definition at line 568 of file serializer.cc.
                                     {
  DisallowGarbageCollection no_gc;
  const SerializerReference* reference_ptr =
      serializer_->reference_map()->LookupBackingStore(backing_store);
  // Serialize the off-heap backing store.
  if (reference_ptr) {
    return reference_ptr->off_heap_backing_store_index();
  }
  if (max_byte_length.IsJust()) {
    sink_->Put(kOffHeapResizableBackingStore,
               "Off-heap resizable backing store");
  } else {
    sink_->Put(kOffHeapBackingStore, "Off-heap backing store");
  }
  sink_->PutUint32(byte_length, "length");
  if (max_byte_length.IsJust()) {
    sink_->PutUint32(max_byte_length.FromJust(), "max length");
  }
  sink_->PutRaw(static_cast<uint8_t*>(backing_store), byte_length,
                "BackingStore");
  DCHECK_NE(0, serializer_->seen_backing_stores_index_);
  SerializerReference reference =
      SerializerReference::OffHeapBackingStoreReference(
          serializer_->seen_backing_stores_index_++);
  // Mark this backing store as already serialized.
  serializer_->reference_map()->AddBackingStore(backing_store, reference);
  return reference.off_heap_backing_store_index();
}
References DCHECK_NE, v8::Maybe< T >::FromJust(), v8::Maybe< T >::IsJust(), v8::internal::SerializerDeserializer::kOffHeapBackingStore, v8::internal::SerializerDeserializer::kOffHeapResizableBackingStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SerializerReference::off_heap_backing_store_index(), v8::internal::SerializerReference::OffHeapBackingStoreReference(), v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), v8::internal::SnapshotByteSink::PutUint32(), and v8::internal::Serializer::sink_.
SerializeContent()
void v8::internal::Serializer::ObjectSerializer::SerializeContent (Tagged< Map > map, int size) [private]
Definition at line 955 of file serializer.cc.
                                                                           {
  Tagged<HeapObject> raw = *object_;
  UnlinkWeakNextScope unlink_weak_next(isolate()->heap(), raw);
  // Iterate references first.
  VisitObjectBody(isolate(), map, raw, this);
  // Then output data payload, if any.
  OutputRawData(raw.address() + size);
}
References v8::internal::Tagged< HeapObject >::address(), heap(), v8::internal::Serializer::isolate(), size(), and v8::internal::VisitObjectBody().
SerializeDeferred()
void v8::internal::Serializer::ObjectSerializer::SerializeDeferred ()
Definition at line 936 of file serializer.cc.
                                                   {
  const SerializerReference* back_reference =
      serializer_->reference_map()->LookupReference(object_);
  if (back_reference != nullptr) {
    if (v8_flags.trace_serializer) {
      PrintF(" Deferred heap object ");
      ShortPrint(*object_);
      PrintF(" was already serialized\n");
    }
    return;
  }
  if (v8_flags.trace_serializer) {
    PrintF(" Encoding deferred heap object\n");
  }
  Serialize(SlotType::kAnySlot);
}
References v8::internal::SerializerDeserializer::kAnySlot, v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
SerializeExternalString()
void v8::internal::Serializer::ObjectSerializer::SerializeExternalString () [private]
Definition at line 682 of file serializer.cc.
                                                         {
  // For external strings with known resources, we replace the resource field
  // with the encoded external reference, which we restore upon deserialize.
  // For the rest we serialize them to look like ordinary sequential strings.
  auto string = Cast<ExternalString>(object_);
  Address resource = string->resource_as_address();
  ExternalReferenceEncoder::Value reference;
  if (serializer_->external_reference_encoder_.TryEncode(resource).To(
          &reference)) {
    DCHECK(reference.is_from_api());
#ifdef V8_ENABLE_SANDBOX
    uint32_t external_pointer_entry =
        string->GetResourceRefForDeserialization();
#endif
    string->SetResourceRefForSerialization(reference.index());
    SerializeObject();
#ifdef V8_ENABLE_SANDBOX
    string->SetResourceRefForSerialization(external_pointer_entry);
#else
    string->set_address_as_resource(isolate(), resource);
#endif
  } else {
    SerializeExternalStringAsSequentialString();
  }
}
References v8::internal::DCHECK(), v8::internal::ExternalReferenceEncoder::Value::index(), v8::internal::ExternalReferenceEncoder::Value::is_from_api(), v8::internal::Serializer::isolate(), and v8::internal::Serializer::SerializeObject().
SerializeExternalStringAsSequentialString()
void v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString () [private]
Definition at line 708 of file serializer.cc.
                                                                           {
  // Instead of serializing this as an external string, we serialize
  // an imaginary sequential string with the same content.
  ReadOnlyRoots roots(isolate());
  PtrComprCageBase cage_base(isolate());
  DCHECK(IsExternalString(*object_, cage_base));
  DirectHandle<ExternalString> string = Cast<ExternalString>(object_);
  uint32_t length = string->length();
  Tagged<Map> map;
  int content_size;
  int allocation_size;
  const uint8_t* resource;
  // Find the map and size for the imaginary sequential string.
  bool internalized = IsInternalizedString(*object_, cage_base);
  if (IsExternalOneByteString(*object_, cage_base)) {
    map = internalized ? roots.internalized_one_byte_string_map()
                       : roots.seq_one_byte_string_map();
    allocation_size = SeqOneByteString::SizeFor(length);
    content_size = length * kCharSize;
    resource = reinterpret_cast<const uint8_t*>(
        Cast<ExternalOneByteString>(string)->resource()->data());
  } else {
    map = internalized ? roots.internalized_two_byte_string_map()
                       : roots.seq_two_byte_string_map();
    allocation_size = SeqTwoByteString::SizeFor(length);
    content_size = length * kShortSize;
    resource = reinterpret_cast<const uint8_t*>(
        Cast<ExternalTwoByteString>(string)->resource()->data());
  }
  SnapshotSpace space = SnapshotSpace::kOld;
  SerializePrologue(space, allocation_size, map);
  // Output the rest of the imaginary string.
  int bytes_to_output = allocation_size - HeapObject::kHeaderSize;
  DCHECK(IsAligned(bytes_to_output, kTaggedSize));
  int slots_to_output = bytes_to_output >> kTaggedSizeLog2;
  // Output raw data header. Do not bother with common raw length cases here.
  sink_->Put(kVariableRawData, "RawDataForString");
  sink_->PutUint30(slots_to_output, "length");
  // Serialize string header (except for map).
  uint8_t* string_start = reinterpret_cast<uint8_t*>(string->address());
  for (size_t i = sizeof(HeapObjectLayout); i < sizeof(SeqString); i++) {
    sink_->Put(string_start[i], "StringHeader");
  }
  // Serialize string content.
  sink_->PutRaw(resource, content_size, "StringContent");
  // Since the allocation size is rounded up to object alignment, there
  // maybe left-over bytes that need to be padded.
  size_t padding_size = allocation_size - sizeof(SeqString) - content_size;
  DCHECK(0 <= padding_size && padding_size < kObjectAlignment);
  for (size_t i = 0; i < padding_size; i++) {
    sink_->Put(static_cast<uint8_t>(0), "StringPadding");
  }
}
References v8::internal::Serializer::cage_base(), v8::internal::DCHECK(), IsAligned(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::Serializer::isolate(), v8::internal::kCharSize, v8::internal::HeapObject::kHeaderSize, v8::internal::kObjectAlignment, v8::internal::kOld, v8::internal::kShortSize, v8::internal::kTaggedSize, v8::internal::kTaggedSizeLog2, v8::internal::SerializerDeserializer::kVariableRawData, v8::internal::length, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::Serializer::sink_, v8::internal::SeqOneByteString::SizeFor(), v8::internal::SeqTwoByteString::SizeFor(), and space.
SerializeJSArrayBuffer()
void v8::internal::Serializer::ObjectSerializer::SerializeJSArrayBuffer () [private]
Definition at line 642 of file serializer.cc.
                                                        {
  ArrayBufferExtension* extension;
  void* backing_store;
  {
    DisallowGarbageCollection no_gc;
    Tagged<JSArrayBuffer> buffer = Cast<JSArrayBuffer>(*object_);
    backing_store = buffer->backing_store();
    // We cannot store byte_length or max_byte_length larger than uint32 range
    // in the snapshot.
    size_t byte_length_size = buffer->GetByteLength();
    CHECK_LE(byte_length_size, std::numeric_limits<uint32_t>::max());
    uint32_t byte_length = static_cast<uint32_t>(byte_length_size);
    Maybe<uint32_t> max_byte_length = Nothing<uint32_t>();
    if (buffer->is_resizable_by_js()) {
      CHECK_LE(buffer->max_byte_length(), std::numeric_limits<uint32_t>::max());
      max_byte_length = Just(static_cast<uint32_t>(buffer->max_byte_length()));
    }
    extension = buffer->extension();
    // Only serialize non-empty backing stores.
    if (buffer->IsEmpty()) {
      buffer->SetBackingStoreRefForSerialization(kEmptyBackingStoreRefSentinel);
    } else {
      uint32_t ref =
          SerializeBackingStore(backing_store, byte_length, max_byte_length);
      buffer->SetBackingStoreRefForSerialization(ref);
    }
    // Ensure deterministic output by setting extension to null during
    // serialization.
    buffer->set_extension(nullptr);
  }
  SerializeObject();
  {
    Tagged<JSArrayBuffer> buffer = Cast<JSArrayBuffer>(*object_);
    buffer->set_backing_store(isolate(), backing_store);
    buffer->set_extension(extension);
  }
}
References CHECK_LE, v8::internal::Serializer::isolate(), v8::Just(), v8::internal::SerializerDeserializer::kEmptyBackingStoreRefSentinel, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Serializer::SerializeObject().
SerializeJSTypedArray()
void v8::internal::Serializer::ObjectSerializer::SerializeJSTypedArray () [private]
Definition at line 600 of file serializer.cc.
                                                       {
  {
    DisallowGarbageCollection no_gc;
    Tagged<JSTypedArray> typed_array = Cast<JSTypedArray>(*object_);
    if (typed_array->is_on_heap()) {
      typed_array->RemoveExternalPointerCompensationForSerialization(isolate());
    } else {
      if (!typed_array->IsDetachedOrOutOfBounds()) {
        // Explicitly serialize the backing store now.
        Tagged<JSArrayBuffer> buffer =
            Cast<JSArrayBuffer>(typed_array->buffer());
        // We cannot store byte_length or max_byte_length larger than uint32
        // range in the snapshot.
        size_t byte_length_size = buffer->GetByteLength();
        CHECK_LE(byte_length_size,
                 size_t{std::numeric_limits<uint32_t>::max()});
        uint32_t byte_length = static_cast<uint32_t>(byte_length_size);
        Maybe<uint32_t> max_byte_length = Nothing<uint32_t>();
        if (buffer->is_resizable_by_js()) {
          CHECK_LE(buffer->max_byte_length(),
                   std::numeric_limits<uint32_t>::max());
          max_byte_length =
              Just(static_cast<uint32_t>(buffer->max_byte_length()));
        }
        size_t byte_offset = typed_array->byte_offset();
        // We need to calculate the backing store from the data pointer
        // because the ArrayBuffer may already have been serialized.
        void* backing_store = reinterpret_cast<void*>(
            reinterpret_cast<Address>(typed_array->DataPtr()) - byte_offset);
        uint32_t ref =
            SerializeBackingStore(backing_store, byte_length, max_byte_length);
        typed_array->SetExternalBackingStoreRefForSerialization(ref);
      } else {
        typed_array->SetExternalBackingStoreRefForSerialization(0);
      }
    }
  }
  SerializeObject();
}
References CHECK_LE, v8::internal::Serializer::isolate(), v8::Just(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Serializer::SerializeObject().
SerializeObject()
void v8::internal::Serializer::ObjectSerializer::SerializeObject ()
Definition at line 911 of file serializer.cc.
                                                 {
  Tagged<Map> map = object_->map(serializer_->cage_base());
  int size = object_->SizeFromMap(map);
  // Descriptor arrays have complex element weakness, that is dependent on the
  // maps pointing to them. During deserialization, this can cause them to get
  // prematurely trimmed if one of their owners isn't deserialized yet. We work
  // around this by forcing all descriptor arrays to be serialized as "strong",
  // i.e. no custom weakness, and "re-weaken" them in the deserializer once
  // deserialization completes.
  //
  // See also `Deserializer::WeakenDescriptorArrays`.
  if (map == ReadOnlyRoots(isolate()).descriptor_array_map()) {
    map = ReadOnlyRoots(isolate()).strong_descriptor_array_map();
  }
  SnapshotSpace space = GetSnapshotSpace(*object_);
  SerializePrologue(space, size, map);
  // Serialize the rest of the object.
  CHECK_EQ(0, bytes_processed_so_far_);
  bytes_processed_so_far_ = kTaggedSize;
  SerializeContent(map, size);
}
References CHECK_EQ, v8::internal::anonymous_namespace{serializer.cc}::GetSnapshotSpace(), v8::internal::Serializer::isolate(), v8::internal::kTaggedSize, size(), and space.
SerializePrologue()
void v8::internal::Serializer::ObjectSerializer::SerializePrologue (SnapshotSpace space, int size, Tagged< Map > map) [private]
Definition at line 459 of file serializer.cc.
                                                                      {
  if (serializer_->code_address_map_) {
    const char* code_name =
        serializer_->code_address_map_->Lookup(object_->address());
    LOG(serializer_->isolate_,
        CodeNameEvent(object_->address(), sink_->Position(), code_name));
  }
  if (map.SafeEquals(*object_)) {
    if (map == ReadOnlyRoots(isolate()).meta_map()) {
      DCHECK_EQ(space, SnapshotSpace::kReadOnlyHeap);
      sink_->Put(kNewContextlessMetaMap, "NewContextlessMetaMap");
    } else {
      DCHECK_EQ(space, SnapshotSpace::kOld);
      DCHECK(IsContext(map->native_context_or_null()));
      sink_->Put(kNewContextfulMetaMap, "NewContextfulMetaMap");
      // Defer serialization of the native context in order to break
      // a potential cycle through the map slot:
      // MAP -> meta map -> NativeContext -> ... -> MAP
      // Otherwise it'll be a "forward ref to a map" problem: deserializer
      // will not be able to create {obj} because {MAP} is not deserialized yet.
      Tagged<NativeContext> native_context = map->native_context();
      // Sanity check - the native context must not be serialized yet since
      // it has a contextful map and thus the respective meta map must be
      // serialized first. So we don't have to search the native context
      // among the back refs before adding it to the deferred queue.
      DCHECK_NULL(
          serializer_->reference_map()->LookupReference(native_context));
      if (!serializer_->forward_refs_per_pending_object_.Find(native_context)) {
        serializer_->RegisterObjectIsPending(native_context);
        serializer_->QueueDeferredObject(native_context);
      }
    }
    DCHECK_EQ(size, Map::kSize);
  } else {
    sink_->Put(NewObject::Encode(space), "NewObject");
    // TODO(leszeks): Skip this when the map has a fixed size.
    sink_->PutUint30(size >> kObjectAlignmentBits, "ObjectSizeInWords");
    // Until the space for the object is allocated, it is considered "pending".
    serializer_->RegisterObjectIsPending(*object_);
    // Serialize map (first word of the object) before anything else, so that
    // the deserializer can access it when allocating. Make sure that the map
    // is known to be being serialized for the map slot, so that it is not
    // deferred.
    DCHECK(IsMap(map));
    serializer_->SerializeObject(handle(map, isolate()), SlotType::kMapSlot);
    // Make sure the map serialization didn't accidentally recursively serialize
    // this object.
    DCHECK_IMPLIES(
        !serializer_->IsNotMappedSymbol(*object_),
        serializer_->reference_map()->LookupReference(object_) == nullptr);
    // To support deserializing pending objects referenced through indirect
    // pointers, we need to make sure that the 'self' indirect pointer is
    // initialized before the pending reference is resolved. Otherwise, the
    // object cannot be referenced.
    if (V8_ENABLE_SANDBOX_BOOL && IsExposedTrustedObject(*object_)) {
      sink_->Put(kInitializeSelfIndirectPointer,
                 "InitializeSelfIndirectPointer");
    }
    // Now that the object is allocated, we can resolve pending references to
    // it.
    serializer_->ResolvePendingObject(*object_);
  }
  if (v8_flags.serialization_statistics) {
    serializer_->CountAllocation(object_->map(), size, space);
  }
  // The snapshot should only contain internalized strings (since these end up
  // in RO space). If this DCHECK fails, allocate the object_ String through
  // Factory::InternalizeString instead.
  // TODO(jgruber,v8:13789): Try to enable this DCHECK once custom snapshots
  // can extend RO space. We may have to do a pass over the heap prior to
  // serialization that in-place converts all strings to internalized strings.
  // DCHECK_IMPLIES(object_->IsString(), object_->IsInternalizedString());
  // Mark this object as already serialized, and add it to the reference map so
  // that it can be accessed by backreference by future objects.
  serializer_->num_back_refs_++;
#ifdef DEBUG
  serializer_->back_refs_.Push(*object_);
  DCHECK_EQ(serializer_->back_refs_.size(), serializer_->num_back_refs_);
#endif
  if (!serializer_->IsNotMappedSymbol(*object_)) {
    // Only add the object to the map if it's not not_mapped_symbol, else
    // the reference IdentityMap has issues. We don't expect to have back
    // references to the not_mapped_symbol anyway, so it's fine.
    SerializerReference back_reference =
        SerializerReference::BackReference(serializer_->num_back_refs_ - 1);
    serializer_->reference_map()->Add(*object_, back_reference);
    DCHECK_EQ(*object_,
              *serializer_->back_refs_[back_reference.back_ref_index()]);
    DCHECK_EQ(back_reference.back_ref_index(), serializer_->reference_map()
                                                   ->LookupReference(object_)
                                                   ->back_ref_index());
  }
}
References v8::internal::SerializerReferenceMap::Add(), v8::internal::SerializerReference::back_ref_index(), v8::internal::SerializerReference::BackReference(), v8::internal::Serializer::code_address_map_, v8::internal::Serializer::CountAllocation(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NULL, v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), v8::internal::Serializer::forward_refs_per_pending_object_, v8::internal::handle(), v8::internal::Serializer::IsNotMappedSymbol(), isolate(), v8::internal::Serializer::isolate_, v8::internal::SerializerDeserializer::kInitializeSelfIndirectPointer, v8::internal::SerializerDeserializer::kMapSlot, v8::internal::SerializerDeserializer::kNewContextfulMetaMap, v8::internal::SerializerDeserializer::kNewContextlessMetaMap, v8::internal::kObjectAlignmentBits, v8::internal::kOld, v8::internal::kReadOnlyHeap, LOG, v8::internal::SerializerReferenceMap::LookupReference(), v8::internal::native_context, v8::internal::Serializer::num_back_refs_, object_, v8::internal::SnapshotByteSink::Position(), v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::Serializer::QueueDeferredObject(), v8::internal::Serializer::reference_map(), v8::internal::Serializer::RegisterObjectIsPending(), v8::internal::Serializer::ResolvePendingObject(), v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals(), v8::internal::Serializer::SerializeObject(), serializer_, sink_, size(), space, V8_ENABLE_SANDBOX_BOOL, and v8::internal::v8_flags.
VisitCodeTarget()
void v8::internal::Serializer::ObjectSerializer::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * target) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1068 of file serializer.cc.
                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
VisitCppHeapPointer()
void v8::internal::Serializer::ObjectSerializer::VisitCppHeapPointer (Tagged< HeapObject > host, CppHeapPointerSlot slot) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1131 of file serializer.cc.
                                                      {
  PtrComprCageBase cage_base(isolate());
  // Currently there's only very limited support for CppHeapPointerSlot
  // serialization as it's only used for API wrappers.
  //
  // We serialize the slot as initialized-but-unused slot. The actual API
  // wrapper serialization is implemented in
  // `ContextSerializer::SerializeApiWrapperFields()`.
  DCHECK(IsJSApiWrapperObjectMap(object_->map(cage_base)));
  static_assert(kCppHeapPointerSlotSize % kTaggedSize == 0);
  sink_->Put(
      FixedRawDataWithSize::Encode(kCppHeapPointerSlotSize >> kTaggedSizeLog2),
      "FixedRawData");
  sink_->PutRaw(reinterpret_cast<const uint8_t*>(&kNullCppHeapPointer),
                kCppHeapPointerSlotSize, "empty cpp heap pointer handle");
  bytes_processed_so_far_ += kCppHeapPointerSlotSize;
}
References v8::internal::Serializer::cage_base(), v8::internal::DCHECK(), v8::internal::SerializerDeserializer::BytecodeValueEncoder< kBytecode, kMinValue, kMaxValue, TValue >::Encode(), v8::internal::Serializer::isolate(), v8::internal::kCppHeapPointerSlotSize, v8::internal::kNullCppHeapPointer, v8::internal::kTaggedSize, v8::internal::kTaggedSizeLog2, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutRaw(), and v8::internal::Serializer::sink_.
VisitEmbeddedPointer()
void v8::internal::Serializer::ObjectSerializer::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * target) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1048 of file serializer.cc.
                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
VisitExternalPointer()
void v8::internal::Serializer::ObjectSerializer::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1150 of file serializer.cc.
                                                       {
  PtrComprCageBase cage_base(isolate());
  InstanceType instance_type = object_->map(cage_base)->instance_type();
  if (InstanceTypeChecker::IsForeign(instance_type) ||
      InstanceTypeChecker::IsJSExternalObject(instance_type) ||
      InstanceTypeChecker::IsAccessorInfo(instance_type) ||
      InstanceTypeChecker::IsInterceptorInfo(instance_type) ||
      InstanceTypeChecker::IsFunctionTemplateInfo(instance_type)) {
    // Output raw data payload, if any.
    OutputRawData(slot.address());
    Address value = slot.load(isolate());
#ifdef V8_ENABLE_SANDBOX
    // We need to load the actual tag from the table here since the slot may
    // use a generic tag (e.g. kAnyExternalPointerTag) if the concrete tag is
    // unknown by the visitor (for example the case for Foreigns).
    ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
    ExternalPointerTag tag = isolate()->external_pointer_table().GetTag(handle);
#else
    ExternalPointerTag tag = kExternalPointerNullTag;
#endif // V8_ENABLE_SANDBOX
    const bool sandboxify = V8_ENABLE_SANDBOX_BOOL;
    OutputExternalReference(value, kSystemPointerSize, sandboxify, tag);
    bytes_processed_so_far_ += kExternalPointerSlotSize;
  } else {
    // Serialization of external references in other objects is handled
    // elsewhere or not supported.
    DCHECK(
        // Serialization of external pointers stored in EmbedderDataArray
        // is not supported yet, mostly because it's not used.
        InstanceTypeChecker::IsEmbedderDataArray(instance_type) ||
        // See ObjectSerializer::SerializeJSTypedArray().
        InstanceTypeChecker::IsJSTypedArray(instance_type) ||
        // See ObjectSerializer::SerializeJSArrayBuffer().
        InstanceTypeChecker::IsJSArrayBuffer(instance_type) ||
        // See ObjectSerializer::SerializeExternalString().
        InstanceTypeChecker::IsExternalString(instance_type) ||
        // See ObjectSerializer::SanitizeNativeContextScope.
        InstanceTypeChecker::IsNativeContext(instance_type) ||
        // Serialization of external pointers stored in
        // JSSynchronizationPrimitive is not supported.
        // TODO(v8:12547): JSSynchronizationPrimitives should also be sanitized
        // to always be serialized in an unlocked state.
        InstanceTypeChecker::IsJSSynchronizationPrimitive(instance_type) ||
        // See ContextSerializer::SerializeObjectWithEmbedderFields().
        (InstanceTypeChecker::IsJSObject(instance_type) &&
         Cast<JSObject>(host)->GetEmbedderFieldCount() > 0));
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::Serializer::cage_base(), v8::internal::DCHECK(), v8::internal::handle(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::Serializer::isolate(), v8::internal::kExternalPointerNullTag, v8::internal::kExternalPointerSlotSize, v8::internal::kSystemPointerSize, v8::internal::ExternalPointerSlot::load(), V8_ENABLE_SANDBOX_BOOL, and v8::internal::value.
VisitExternalReference()
void v8::internal::Serializer::ObjectSerializer::VisitExternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1053 of file serializer.cc.
                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
VisitIndirectPointer()
void v8::internal::Serializer::ObjectSerializer::VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1200 of file serializer.cc.
                              {
#ifdef V8_ENABLE_SANDBOX
  // If the slot is empty (i.e. contains a null handle), then we can just skip
  // it since in that case the correct action is to encode the null handle as
  // raw data, which will automatically happen if the slot is skipped here.
  if (slot.IsEmpty()) return;
  // If necessary, output any raw data preceding this slot.
  OutputRawData(slot.address());
  // The slot must be properly initialized at this point, so will always contain
  // a reference to a HeapObject.
  Handle<HeapObject> slot_value(Cast<HeapObject>(slot.load(isolate())),
                                isolate());
  CHECK(IsHeapObject(*slot_value));
  bytes_processed_so_far_ += kIndirectPointerSize;
  // Currently we cannot see pending objects here, but we may need to support
  // them in the future. They should already be supported by the deserializer.
  CHECK(!serializer_->SerializePendingObject(*slot_value));
  sink_->Put(kIndirectPointerPrefix, "IndirectPointer");
  serializer_->SerializeObject(slot_value, SlotType::kAnySlot);
#else
  UNREACHABLE();
#endif
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), CHECK, v8::internal::IndirectPointerSlot::IsEmpty(), v8::internal::IsHeapObject(), v8::internal::Serializer::isolate(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SerializerDeserializer::kIndirectPointerPrefix, v8::internal::kIndirectPointerSize, v8::internal::IndirectPointerSlot::load(), v8::internal::SnapshotByteSink::Put(), v8::internal::Serializer::sink_, and v8::internal::UNREACHABLE().
VisitInstructionStreamPointer()
void v8::internal::Serializer::ObjectSerializer::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1041 of file serializer.cc.
                                                   {
  DCHECK(!host->has_instruction_stream());
}
References v8::internal::DCHECK().
VisitInternalReference()
void v8::internal::Serializer::ObjectSerializer::VisitInternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1058 of file serializer.cc.
                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
VisitJSDispatchTableEntry()
void v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry (Tagged< HeapObject > host, JSDispatchHandle handle) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1297 of file serializer.cc.
                                                      {
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  // If the slot is empty, we will skip it here and then just serialize the
  // null handle as raw data.
  if (handle == kNullJSDispatchHandle) return;
  // TODO(saelo): we might want to call OutputRawData here, but for that we
  // first need to pass the slot address to this method (e.g. as part of a
  // JSDispatchHandleSlot struct).
#if !defined(V8_COMPRESS_POINTERS) && defined(V8_TARGET_ARCH_64_BIT)
  static_assert(kJSDispatchHandleSize + JSFunction::kPaddingOffsetEnd + 1 -
                    JSFunction::kPaddingOffset ==
                kSystemPointerSize);
#endif // COMPRESS_POINTERS
  bytes_processed_so_far_ += RoundUp(kJSDispatchHandleSize, kTaggedSize);
  auto it = serializer_->dispatch_handle_map_.find(handle);
  if (it == serializer_->dispatch_handle_map_.end()) {
    auto id = static_cast<uint32_t>(serializer_->dispatch_handle_map_.size());
    serializer_->dispatch_handle_map_[handle] = id;
    sink_->Put(kAllocateJSDispatchEntry, "AllocateJSDispatchEntry");
    sink_->PutUint30(jdt->GetParameterCount(handle), "ParameterCount");
    // Currently we cannot see pending objects here, but we may need to support
    // them in the future. They should already be supported by the deserializer.
    Handle<Code> code(jdt->GetCode(handle), isolate());
    CHECK(!serializer_->SerializePendingObject(*code));
    serializer_->SerializeObject(code, SlotType::kAnySlot);
  } else {
    sink_->Put(kJSDispatchEntry, "JSDispatchEntry");
    sink_->PutUint30(it->second, "EntryID");
  }
#else
  UNREACHABLE();
#endif // V8_ENABLE_LEAPTIERING
}
References CHECK, code, v8::internal::IsolateGroup::current(), v8::internal::handle(), v8::internal::Serializer::isolate(), v8::internal::SerializerDeserializer::kAllocateJSDispatchEntry, v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SerializerDeserializer::kJSDispatchEntry, v8::internal::kJSDispatchHandleSize, v8::internal::kNullJSDispatchHandle(), v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), RoundUp(), v8::internal::Serializer::sink_, and v8::internal::UNREACHABLE().
VisitOffHeapTarget()
void v8::internal::Serializer::ObjectSerializer::VisitOffHeapTarget (Tagged< InstructionStream > host, RelocInfo * target) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1063 of file serializer.cc.
                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
VisitPointers() [1/2]
void v8::internal::Serializer::ObjectSerializer::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 970 of file serializer.cc.
                                                                      {
  HandleScope scope(isolate());
  PtrComprCageBase cage_base(isolate());
  DisallowGarbageCollection no_gc;
  MaybeObjectSlot current = start;
  while (current < end) {
    while (current < end && current.load(cage_base).IsSmi()) {
      ++current;
    }
    if (current < end) {
      OutputRawData(current.address());
    }
    // TODO(ishell): Revisit this change once we stick to 32-bit compressed
    // tagged values.
    while (current < end && current.load(cage_base).IsCleared()) {
      sink_->Put(kClearedWeakReference, "ClearedWeakReference");
      bytes_processed_so_far_ += kTaggedSize;
      ++current;
    }
    Tagged<HeapObject> current_contents;
    HeapObjectReferenceType reference_type;
    while (current < end && current.load(cage_base).GetHeapObject(
                                &current_contents, &reference_type)) {
      // Write a weak prefix if we need it. This has to be done before the
      // potential pending object serialization.
      if (reference_type == HeapObjectReferenceType::WEAK) {
        sink_->Put(kWeakPrefix, "WeakReference");
      }
      Handle<HeapObject> obj = handle(current_contents, isolate());
      if (serializer_->SerializePendingObject(*obj)) {
        bytes_processed_so_far_ += kTaggedSize;
        ++current;
        continue;
      }
      RootIndex root_index;
      // Compute repeat count and write repeat prefix if applicable.
      // Repeats are not subject to the write barrier so we can only use
      // immortal immovable root members. In practice we're most likely to only
      // repeat smaller root indices, so we limit the root index to 256 to keep
      // decoding simple.
      static_assert(UINT8_MAX <=
                    static_cast<int>(RootIndex::kLastImmortalImmovableRoot));
      MaybeObjectSlot repeat_end = current + 1;
      if (repeat_end < end &&
          serializer_->root_index_map()->Lookup(*obj, &root_index) &&
          static_cast<uint32_t>(root_index) <= UINT8_MAX &&
          current.load(cage_base) == repeat_end.load(cage_base) &&
          reference_type == HeapObjectReferenceType::STRONG) {
        DCHECK(!HeapLayout::InYoungGeneration(*obj));
        while (repeat_end < end &&
               repeat_end.load(cage_base) == current.load(cage_base)) {
          repeat_end++;
        }
        int repeat_count = static_cast<int>(repeat_end - current);
        current = repeat_end;
        bytes_processed_so_far_ += repeat_count * kTaggedSize;
        serializer_->PutRepeatRoot(repeat_count, root_index);
      } else {
        bytes_processed_so_far_ += kTaggedSize;
        ++current;
        serializer_->SerializeObject(obj, SlotType::kAnySlot);
      }
    }
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::Serializer::cage_base(), v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::handle(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::Serializer::isolate(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SerializerDeserializer::kClearedWeakReference, v8::internal::kLastImmortalImmovableRoot, v8::internal::kTaggedSize, v8::internal::SerializerDeserializer::kWeakPrefix, v8::internal::FullMaybeObjectSlot::load(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SnapshotByteSink::Put(), v8::internal::Serializer::sink_, STRONG, and WEAK.
VisitPointers() [2/2]
void v8::internal::Serializer::ObjectSerializer::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 964 of file serializer.cc.
                                                                 {
  VisitPointers(host, MaybeObjectSlot(start), MaybeObjectSlot(end));
}
References v8::internal::compiler::end().
VisitProtectedPointer() [1/2]
void v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1267 of file serializer.cc.
                                                               {
  Tagged<MaybeObject> maybe_content = slot.load();
  // Empty slots (Smi::zero()) and Smi slots can be skipped here.
  if (maybe_content.IsSmi()) return;
  // If necessary, output any raw data preceding this slot.
  OutputRawData(slot.address());
  if (maybe_content.IsCleared()) {
    sink_->Put(kClearedWeakReference, "ClearedWeakReference");
    bytes_processed_so_far_ += kTaggedSize;
    return;
  }
  Tagged<HeapObject> content;
  HeapObjectReferenceType reference_type;
  if (maybe_content.GetHeapObject(&content, &reference_type)) {
    if (reference_type == HeapObjectReferenceType::WEAK) {
      sink_->Put(kWeakPrefix, "WeakReference");
    }
    Handle<HeapObject> object = handle(content, isolate());
    // Currently we cannot see pending objects here, but we may need to support
    // them in the future. They should already be supported by the deserializer.
    CHECK(!serializer_->SerializePendingObject(*object));
    sink_->Put(kProtectedPointerPrefix, "ProtectedPointer");
    serializer_->SerializeObject(object, SlotType::kAnySlot);
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), CHECK, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::handle(), v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::Serializer::isolate(), v8::internal::Tagged< HeapObject >::IsSmi(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SerializerDeserializer::kClearedWeakReference, v8::internal::SerializerDeserializer::kProtectedPointerPrefix, v8::internal::kTaggedSize, v8::internal::SerializerDeserializer::kWeakPrefix, v8::internal::FullMaybeObjectSlot::load(), v8::internal::SnapshotByteSink::Put(), v8::internal::Serializer::sink_, and WEAK.
VisitProtectedPointer() [2/2]
void v8::internal::Serializer::ObjectSerializer::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1245 of file serializer.cc.
                                                           {
  Tagged<Object> content = slot.load(isolate());
  // Similar to the indirect pointer case, if the slot is empty (i.e. contains
  // Smi::zero()), then we skip it here.
  if (content == Smi::zero()) return;
  DCHECK(!IsSmi(content));
  // If necessary, output any raw data preceeding this slot.
  OutputRawData(slot.address());
  Handle<HeapObject> object(Cast<HeapObject>(content), isolate());
  bytes_processed_so_far_ += kTaggedSize;
  // Currently we cannot see pending objects here, but we may need to support
  // them in the future. They should already be supported by the deserializer.
  CHECK(!serializer_->SerializePendingObject(*object));
  sink_->Put(kProtectedPointerPrefix, "ProtectedPointer");
  serializer_->SerializeObject(object, SlotType::kAnySlot);
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), CHECK, v8::internal::DCHECK(), v8::internal::Serializer::isolate(), v8::internal::IsSmi(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::SerializerDeserializer::kProtectedPointerPrefix, v8::internal::kTaggedSize, v8::internal::FullObjectSlot::load(), v8::internal::SnapshotByteSink::Put(), v8::internal::Serializer::sink_, and v8::internal::Smi::zero().
VisitTrustedPointerTableEntry()
void v8::internal::Serializer::ObjectSerializer::VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1229 of file serializer.cc.
                                                       {
#ifdef V8_ENABLE_SANDBOX
  // These fields only exist on the ExposedTrustedObject class, and they are
  // located directly after the Map word.
  DCHECK_EQ(bytes_processed_so_far_,
            ExposedTrustedObject::kSelfIndirectPointerOffset);
  // Nothing to do here. We already emitted the kInitializeSelfIndirectPointer
  // after processing the Map word in SerializePrologue.
  bytes_processed_so_far_ += kIndirectPointerSize;
#else
  UNREACHABLE();
#endif
}
References DCHECK_EQ, v8::internal::kIndirectPointerSize, and v8::internal::UNREACHABLE().
Member Data Documentation
bytes_processed_so_far_
int v8::internal::Serializer::ObjectSerializer::bytes_processed_so_far_ [private]
Definition at line 530 of file serializer.h.
isolate_
Isolate* v8::internal::Serializer::ObjectSerializer::isolate_ [private]
Definition at line 526 of file serializer.h.
Referenced by isolate().
object_
Handle<HeapObject> v8::internal::Serializer::ObjectSerializer::object_ [private]
Definition at line 528 of file serializer.h.
Referenced by SerializePrologue().
serializer_
Serializer* v8::internal::Serializer::ObjectSerializer::serializer_ [private]
Definition at line 527 of file serializer.h.
Referenced by ObjectSerializer(), SerializePrologue(), and ~ObjectSerializer().
sink_
SnapshotByteSink* v8::internal::Serializer::ObjectSerializer::sink_ [private]
Definition at line 529 of file serializer.h.
Referenced by SerializePrologue().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/serializer.h
/mnt/V8SourceCode/src/snapshot/serializer.cc